### ISSUE TITLE
Allow only create_at or updated_at

### ISSUE THREAD

**Issue by rentalhost** [laravel/framework#10005]
Currently Laravel forces users to use Blueprint::timestamps() to create `created_at` and `updated_at` (or disable both). If user need only of `created_at` or `updated_at`, they will need hardcode it.

**Suggestion is allow define separately this behaviours.**

Example:

```php
class User extends Model
{
    public $timestamps = false; // disable all behaviour
    public $timestamps = true; // enable all behaviour
    public $timestamps = [ "created_at" ]; // enable only to created_at
    public $timestamps = [ "updated_at" ]; // enable only to updated_at
    public $timestamps = [ "created_at", "updated_at" ]; // same that true
}
```

It'll not cause break-changing, I guess.

**Comment by BeingTomGreen** [comment]
If you're talking about dates on a model, you can override the `getDates` method like so:

```php
    public function getDates()
    {
        return ['created_at', 'expire_date'];
    }
```

I'm not sure this currently appears in the docs.

To disable timestamps completely you can just use `public $timestamps = false;`.

**Comment by GrahamCampbell** [comment]
> If you're talking about dates on a model, you can override the getDates method like so:

No, "timestamps" are unrelated to that.

**Comment by absolux** [comment]
To disable only updated_at column, i tried to override only
```php
public function setUpdatedAt($value) {
    // Do nothing.
}
```
but,
```php
public function getUpdatedAtColumn() {
    return null;
}
```
should be overridden, because Laravel is processing updated_at twice
* in performUpdate with $this->updateTimestamps() 
* and then later in Builder with $this->addUpdatedAtColumn($values).

**Comment by rentalhost** [comment]
Exactly. Here I created a trait that override two methods `setUpdateAt($value)` returning `null`, and `usesTimestamps()` returning `false` (it'll help with the `Builder` issue).

**Comment by rentalhost** [comment]
@GrahamCampbell Can you explain the reason to close this FR? Thanks.

**Comment by GrahamCampbell** [comment]
Because you provided a solution, and we don't process proposal issues anyway.

**Comment by rentalhost** [comment]
This solution is a workaround of a thing that I suppose to be native. One time that Laravel support both features, but only together. And on real life, it can be more than the need. For instance, I don't need update_at on a change log table. Only created_at. Solution is very simple and not is a break change. 

But if I pull request it can be availed better, or is a "full closed case"?

**Comment by GrahamCampbell** [comment]
Yeh, I'm not closing is to say don't talk about it again. I'm just moving it off our immediately todo list.

All proposals need to be discussed over a pull request, or directly with Taylor.

**Comment by mpyw** [comment]
Solution here: https://github.com/laravel/framework/pull/19139#issuecomment-300698303
