### ISSUE TITLE
Answer from server in appropriate format when using ajax.

### ISSUE THREAD

**Issue by berpcor** [laravel/framework#10008]
Hello. I use ajax. In my php controller I get an Exception. In my client side in console I get html page with message about the exception - not message in appropriate format. I've found solution (2-nd answer) here - http://stackoverflow.com/questions/28944097/laravel-5-handle-exceptions-when-request-wants-json It is a working solution, but such kind of functionality should be available out of the box, as I think. 
My suggestion is to add this functionality to framework. I understand that there is no universal format of answer, but it could be some default format (with possibility to change it) which could be described in docs.

**Comment by GrahamCampbell** [comment]
I'd recommend checking out https://github.com/GrahamCampbell/Laravel-Exceptions. It has a concept of displayers to handle any content type you want.

**Comment by GrahamCampbell** [comment]
The answer you got on the forums was a bit poor. It's better to look at what the client actually accepts, following the http spec, then assuming the Accept header is exactly "application/json".
