### ISSUE TITLE
Enviornment vars are not loading from .env file on rapid page refresh

### ISSUE THREAD

**Issue by janakaonline** [laravel/framework#10015]
Hi,
After the recent 5.1 update, I'm getting "ERROR: exception 'RuntimeException' with message 'No supported encrypter found.." error when I do short interval page refreshes. This only occurs sometimes. I have tried to debug the error, but so far I'm only able to find that the $_ENV is empty so the env() function returning the default value.

With some googling I have found that this is some sort of a common issue.
http://laravel.io/forum/06-26-2015-laravel-5-multiple-requests-in-short-time-cause-500-internal-server-error

As in the link, I have tried hard cording the config files and it works.
Even it a temporary fix for the issue, the core problem still to be fixed. 

I am digging in to the issue, but I thought it would be better to get this fixed faster with some support from experts.

If someone has a fix for this I would love to hear it.
thanks

**Comment by Sladewill** [comment]
Yeah its becoming a utter nightmare using dotenv its been nothing but problems since it was implemented in 5.0.

**Comment by crynobone** [comment]
Any reason not to use `php artisan config:cache`?

**Comment by janakaonline** [comment]
@crynobone Thanks. yes it fixed the issue. But what I trying to figure out is what causing the issue.
any idea?

Thanks

**Comment by crynobone** [comment]
This could be the related issue #7354

**Comment by janakaonline** [comment]
Yeah, Im reading it now. Thanks for the tip :)

**Comment by Sladewill** [comment]
I've found the issue still occurs even after config:cache we've got bugsnag on our sites and all of them are getting the occasional occurrence of this.
