### ISSUE TITLE
`Cache:has()` only works with Predis, but not PECL or HHVM extensions

### ISSUE THREAD

**Issue by tillkruss** [laravel/framework#10018]
In our environment (Heroku; Laravel 5.1.10; PHP 5.6.12) the PECL Redis extensions returns `false` instead of `null` if a key doesn't exist in the cache. `Illuminate\Cache\Repository::has()` is checking for `is_null()`, so `Cache::has()` returns `true`, even tho `Cache::get()` returns `false`.

Extending the default check was rejected: #8340.

The HHVM Redis extension switched from returning `null` to returning `false` to match the behavior of phpredis: https://github.com/facebook/hhvm/commit/47b3503c741d2124ed972d1e617eb712148c92c8

It would be nice if Laravel would support the PECL and HHVM Redis extensions out of the box, because they are both significantly faster alternatives to Predis and [it's quite an effort to get them running](https://gist.github.com/tillkruss/cf4772c50149162109bb).

I'd be happy to submit a pull request.

**Comment by tillkruss** [comment]
The HHVM Redis extension switched as well from returning `null` to returning `false` to match the behavior of phpredis: https://github.com/facebook/hhvm/commit/47b3503c741d2124ed972d1e617eb712148c92c8

**Comment by it-can** [comment]
This would be very nice

**Comment by GrahamCampbell** [comment]
Predis will use those extensions under the hood if they're installed. You still need to install predis though.

**Comment by it-can** [comment]
Predis uses phpiredis and not phpredis...

**Comment by GrahamCampbell** [comment]
Well, that's not a laravel bug then, is it?

**Comment by tillkruss** [comment]
@GrahamCampbell Could you explain why exactly Laravel shouldn't support the Redis PECL and HHVM extension out of the box? Both are [significantly](http://alekseykorzun.com/post/53283070010/benchmarking-memcached-and-redis-clients) [faster](http://dev.af83.com/2011/01/01/which-php-library-to-use-with-redis-the-benchmark.html) than Predis.

**Comment by crynobone** [comment]
@tillkruss because it's already using Predis to handle any Redis related usage, having additional code doesn't necessary good unless the core contributor use it as well (bug is harder to find and solve).

> Predis uses phpiredis and not phpredis...
> Well, that's not a laravel bug then, is it?

What @GrahamCampbell trying to say, why not push this request to Predis.

**Comment by tillkruss** [comment]
https://gist.github.com/tillkruss/27eda66e77280f1ba727
