### ISSUE TITLE
[5.1] Event Listeners do not receive the event, but the model instead

### ISSUE THREAD

**Issue by Francismori7** [laravel/framework#10016]
```bash
ErrorException in InvalidateClientsCache.php line 24: Argument 1 passed to App\Listeners\InvalidateClientsCache::handle() must be an instance of App\Events\ClientWasCreated, instance of App\Client given
```

Okay so I have multiple events, let's take one here for the sake of an exemple:

```php
class ClientWasCreated extends Event
{
    use SerializesModels;
    /**
     * @var Client
     */
    public $client;

    /**
     * Create a new event instance.
     *
     * @param Client $client
     */
    public function __construct(Client $client)
    {
        $this->client = $client;
    }

    /**
     * Get the channels the event should be broadcast on.
     *
     * @return array
     */
    public function broadcastOn()
    {
        return ['clients'];
    }
}
```

And here is the listener, it is properly set up, and is properly fired if I remove TYPE-HINTING in the handle() method:

```php
class InvalidateClientsCache
{
    /**
     * Create the event listener.
     */
    public function __construct()
    {
        //
    }

    /**
     * Handle the event.
     *
     * @param Client $client
     */
    public function handle(ClientWasCreated $event)
    {
        dd($event->client);

        if (Cache::has('clients')) {
            Cache::forget('clients');
        }
    }
}
```

If I remove the type-hinting of ClientWasCreated, I also get an error, client is not defined in the the passed object, because the passed object is the model itself.

I have no idea what is going on here, my other projects seem to work fine with EVENTS type-hinted in the listeners, this one just calls straight the model itself.

**Comment by GrahamCampbell** [comment]
Looks like user error to me. Please ask on the forums.

**Comment by GrahamCampbell** [comment]
https://github.com/StyleCI/StyleCI/tree/master/app is an example codebase that clearly shows that this stuff works.

**Comment by Francismori7** [comment]
My point exactly, it works, just not now, with a fresh install of Laravel. My other L5.1 projects work properly

**Comment by Francismori7** [comment]
The thing is, I do not control what is sent to the listeners, none of any private code could control that, it's deep in the Laravel framework, which is untouched of course.

Yet, it's sending the wrong thing.

**Comment by Francismori7** [comment]
@GrahamCampbell

Further info, using ARTISAN TINKER to call event(), I get the expected result - the event instance is passed to the handle() methods.
