### ISSUE TITLE
Bug: Eloquent Update affecting more than one row.

### ISSUE THREAD

**Issue by pmuralikrishna111** [laravel/framework#10017]
$custid="C0001"
        $empid="E0001"
        $cemp = new EloquentModel1;
        $emp=$cemp->where('Cust_ID','=',$custid)
                ->where('Employee_ID','=',$empid)->first();

        $emp->fill(Input::all());
        $emp->update();
This update statement getting updated in two rows. 

Table Data.
CustID Employee_ID        Address
C0001  E0001                   2
C0002  E0001                   1

**Comment by GrahamCampbell** [comment]
What Laravel version?

**Comment by GrahamCampbell** [comment]
What do you have set as the primary key?

**Comment by pmuralikrishna111** [comment]
Version : 5.0.14
protected $primaryKey='Employee_ID';
protected $foreignKey='Cust_ID';

**Comment by GrahamCampbell** [comment]
Only Laravel 5.1 is supported.

**Comment by GrahamCampbell** [comment]
Please upgrade to 5.1 and report if the bug is still present.
