### ISSUE TITLE
MorphMany does not return all attributes after create

### ISSUE THREAD

**Issue by MartijnThomas** [laravel/framework#10013]
I'm not sure why this is happening, but once you create a new morphed model through a morph relation not the entire model is returned.

Lets say you have the following Models

    class Run extends Model
	{
	    /**
		 * The database table used by the model.
		 *
		 * @var string
		 */
		protected $table = 'runs';

		/**
		 * The attributes that are mass assignable.
		 *
		 * @var array
		 */
		protected $fillable = ['statistics'];

	    /**
	     * The list of attributes to cast.
	     *
	     * @var array
	     */
	    protected $casts = [
	        'statistics' => 'json'
	    ];

	    /**
	     * Get all of the owning runnable models.
	     */
	    public function kind()
	    {
	        return $this->morphTo();
	    }
	}

    class Spider extends Model
	{
		/**
		 * The database table used by the model.
		 *
		 * @var string
		 */
		protected $table = 'spiders';

		/**
		 * The attributes that are mass assignable.
		 *
		 * @var array
		 */
		protected $fillable = ['settings'];

		/**
	     * Get all the spider runs
	     */
	    public function runs()
	    {
	        return $this->morphMany(\App\Run::class, 'kind');
	    }
	}

Where the database migrations look like this

    Schema::create('runs', function (Blueprint $table) {
        $table->increments('id');
        $table->integer('kind_id')->unsigned();
        $table->string('kind_type');
        $table->json('statistics')->default('[]');
        $table->timestamps();
    });

	Schema::create('spiders', function (Blueprint $table) {
		$table->increments('id');
		$table->integer('site_id')->unsigned();
		$table->json('settings')->default('[]');
		$table->timestamps();

		$table->foreign('site_id')->references('id')->on('sites');
	});

Once you create the model through an existing spider `$spider->runs()->create([])` the `statistics` attribute is missing from the model (it is not null, it is just missing).

If you after the Run has been created fetches the run again using `Run::find($run->id)` the `statistics` param is present.

As far as I can tell on normal creates all available attributes return.

The result of the missing attribute are "Undefined property" errors. I tried to trace back the problem in the Eloquent source but not sure why this is happening.

I'm currently using 5.1.10 with the database driver set to `pgsql` on Laravel Homestead.

**Comment by janakaonline** [comment]
Hi, Well I dont know much about "json" casting in laravel 5.1. But there is are [array and object casting features] (http://laravel.com/docs/5.1/eloquent-mutators#attribute-casting).  

And why there is a 
```php
return new JsonAccessor('statistics', $this);
}
```

in the Run Class?

**Comment by MartijnThomas** [comment]
@janakaonline the JsonAccessor should not be in the post, somehow it ended up there.

I know there are several ways to cast the json string. Json casting works find if you do Run::find($run->id), but it does not work when created through the relation.

**Comment by MartijnThomas** [comment]
@GrahamCampbell Why did you close this? Can you please explain why this is not an Laravel issue?

**Comment by janakaonline** [comment]
@MartijnThomas Interesting, you code actually works for me with mysql. Then it should be something to do with pgsql driver.
