### ISSUE TITLE
castAttribute could handle dates?

### ISSUE THREAD

**Issue by jbrooksuk** [laravel/framework#10025]
Currently there is a `$dates` property for mutating database values to a Carbon object, but then we have a separate `$casts` property for general casting.

Is it worth thinking about allowing dates to be casted within the [`castAttribute` method](https://github.com/laravel/framework/blob/d530ce218cab621909825e66860e781fb9c91f65/src/Illuminate/Database/Eloquent/Model.php#L2764-L2792)? This would at least make `$dates` optional, assuming everything internally is ran through `castAttributes`, so that date fields are properly handled?

Also, we cast `collection` type, so date could just as easily be handled?

**Comment by GrahamCampbell** [comment]
See https://github.com/laravel/framework/pull/10280. :)
