### ISSUE TITLE
Routing HTTP Exceptions through Controller

### ISSUE THREAD

**Issue by browner12** [laravel/framework#10022]
### Background

the framework currently allows you to easily define views for specific HTTP status code responses.  For example, an HTTP status code of 404 will display the `resources/views/errors/404.blade.php` view automatically if it exists.  it works the same for other codes like 500 errors.

### Problem

All of the routes on my site are processed through controllers, all of which extend a base `Controller`.  This base controller sometimes initializes the user, sets the current timezone, and other random stuff. The master template often relies on these variables. For example, if a user is logged in, the `Controller` figures that out and passes that user to the view. My master template looks for that user, and shows certain functionality if present. When a 404 is hit, I want to still be able to show the user specific menus, and continue using that 404 view.

### Proposal

IMHO it would be ideal if the framework would still catch those exceptions, but instead of immediately rendering the view, send them to a specific route. Then we could create an `ErrorController` with specific methods for each status code.

```php
class ErrorController extends Controller
{
    public function e404() //method names cannot start with numbers
    {
        return view('errors.404');
    }
}
```

Before I start on a PR, I am looking for some feedback on this, to see if other people are running into a similar issue as me, and if they've come up with different (maybe better) solutions to it.

Thanks!

**Comment by GrahamCampbell** [comment]
Deal with this in your exception handler.

**Comment by GrahamCampbell** [comment]
It is technically possible for you to get this to work with custom code.

**Comment by browner12** [comment]
i'm sure it is, but i was curious if it was a problem for other people as well. And if so, that we could make an internal change to make it easier for everyone.

Is there a use case where immediately rendering the view is preferential, and routing through a controller would be undesired?

**Comment by GrahamCampbell** [comment]
I'd say we definitely shouldn't change the current behaviour, but it is absolutely possible for you to get this behaviour if you want it. Just be careful though, because current if an exception is handled by the exception handler, the middleware system has already been broken out of, so anything that would have wrapped the response is no longer executed (ie, headers, cookies never get attached to the response).
