### ISSUE TITLE
TransportManager::createSesDriver() more helpful error message please

### ISSUE THREAD

**Issue by adrian7** [laravel/framework#10029]
```php
if ($config['key'] && $config['secret']) {
    $config['credentials'] = Arr::only($config, ['key', 'secret']);
}
```

Basically if you set your MAIL_DRIVER to ses and then don't define your secret and key, the error message you get is "undefined index 'key'".
Although the message pretty gets the point, you can't tell from the message itself what you may do to fix it.

Thanks.

**Comment by GrahamCampbell** [comment]
We're open to PRs. :)
