### ISSUE TITLE
[Proposal] [Validator] [5.1] 'at_least:foo,bar' rule

### ISSUE THREAD

**Issue by rafaelbeckel** [laravel/framework#10020]
Sometimes we have a form that does not contain any required fields. For example, an 'edit your account' form.

So, you write validation rules to validate input formats for its optional fields. However, a user can send the form without filling any field. Your validation rules will pass, because no field has the 'required' attribute.

I just had this situation here, and I could (and should) write a custom validation rule. However, it seemed too cumbersome for something simple that should be a one liner. So, I ended up using: 

```
'empty_hidden_field' => 'size:0|required_without_all:field_a,field_b,....,field_N'
```
...and edited the 'required_without_all' message to be "You need to fill at least one field". It works like a charm, but it's definitely **not** the right way to do it.

It would be cool if the framework had a built-in validation rule for this not-too-specific case.

It could be something like: `'at_least:foo,bar'` or `'at_least:any'`

**Comment by GrahamCampbell** [comment]
We don't process proposal issues. Issues are only here for the community to share and fix.

**Comment by rafaelbeckel** [comment]
So why are there issues tagged by you as "Proposal"?

Where should I post them? Just do a PR and that's all? Is there any place to talk about it before pushing?
