### ISSUE TITLE
composer update with output of 'array(1) {   [0]=>   string(38) "/var/www/MY-PROJECT/app/config/../views" }'

### ISSUE THREAD

**Issue by MeicaiRose** [laravel/framework#10026]
* when i update laravel(4.2.17) this day with composer update(the symfony event-dispacher component, symfony filesystem component and monolog have renewal,there is something output with the message of

``` 
array(1) {
  [0]=>
  string(38) "/var/www/MY-PROJECT/app/config/../views"
}
```
.However, when i downgrade the version laravel with 4.2.10,everything works well.On the other hand, the  
symfony event-dispacher component and symfony filesystem component have been updated 1 hour ago.

**Comment by Sladewill** [comment]
4.2 is no longer supported try the forums http://laravel.io/forum
