### ISSUE TITLE
[5.1] [5.2] $model->save(['timestamps' => false]) has no effect.

### ISSUE THREAD

**Issue by websanova** [laravel/framework#10028]
Not an Eloquent expert, but maybe some bug in the Builder.

if you look at: `Illuminate\Database\Eloquent\Model@performUpdate`

There is a line `$this->setKeysForSaveQuery($query)->update($dirty);`

Which from `setKeysForSaveQuery` receives a `Builder` object.

The update is being called from that` Builder` which seems to ONLY check the models `timestamps` field and no longer the `timestamps` argument passed in `save()`.

Inside of: `Illuminate\Database\Eloquent\Builder@update`

There is a line `return $this->query->update($this->addUpdatedAtColumn($values));`

Which if you follow along will set the update field even though we passed the argument in. It's only checking the `$model->timestamps` parameter.

I tried it in 5.1.2 and 5.1.10 

~~~
namespace App\Models;

class Language extends \Illuminate\Database\Eloquent\Model
{

}
~~~

~~~
$router->get('/test', function () {
    $model = \App\Models\Language::find(1);

    $model->words_total = $model->words_total + 1;
    $model->save(['timestamps' => false]);

    return 'boo';
});
~~~

**Comment by lukasgeiter** [comment]
To fix this, instead of having to pass the `options` array all the way through to the `update` method on the query builder, we could just temporarily change the `timestamps` property. Like:

    $previousTimestamps = $this->timestamps;
    $this->timestamps = Arr::get($options, 'timestamps', $this->timestamps);

    // rest of the save method

    $this->timestamps = $previousTimestamps;
    return $saved;

@GrahamCampbell @taylorotwell Thoughts?

**Comment by vlakoff** [comment]
Same issue as #6192. Refs #5840.

I can't find a better solution than yours, i.e. temporarily setting Model->timestamps to false during execution of Eloquent\Builder->update(). Maybe someone has a better idea?

**Comment by vlakoff** [comment]
There is a bug indeed. The test erroneously succeeds as `Eloquent\Builder::update()` is mocked, so it doesn't execute `$this->query->update($this->addUpdatedAtColumn($values));`.

**Comment by vlakoff** [comment]
I tried to write a proper test, but it had become a gigantic mess.
If it may be of inspiration, here's [another attempt](https://github.com/laravel/framework/compare/5.1...vlakoff:eloquent-save-notimestamps), but of course it breaks other things.
@GrahamCampbell please reopen (or give a reason for closing…)

**Comment by vlakoff** [comment]
Only for the sake of demonstration, here is [yet another attempt](https://github.com/laravel/framework/compare/5.1...vlakoff:eloquent-save-notimestamps-2).

Just to show how it becomes clumsy (in particular concerning the tests) to repair the functionality without making any change to the API.

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell.

**Comment by peterkinnaird** [comment]
Any updates to this issue?

**Comment by mkwsra** [comment]
@taylorotwell buddy, I guess this is a small issue to be solved by you.

For me as a user of Laravel I need this:
e.i: I got couple functions that should update my model without touching the updated_at and simply this way isn't enabled.

Thanks in advance for any response

**Comment by aemr3** [comment]
+1 @taylorotwell

**Comment by websanova** [comment]
+1 @taylorotwell

**Comment by acasar** [comment]
@websanova @aemr3 @mkwsra Can you all describe the problem a little better? Because I just added the following test and it passes:

https://github.com/acasar/framework/commit/dfc8d484cae57d9cc2cd68f79fb577f35e40acd1

**Comment by JosephSilber** [comment]
You're not changing anything there, so it doesn't even perform an update. Try setting the email to a new value.

**Comment by acasar** [comment]
Argh, typo :) I should really find a way to test my tests...

Yeah I have the bug now. Will try to fix it..

**Comment by vlakoff** [comment]
This feature never worked and will just be removed in 5.3.

(issue can be closed)

**Comment by zvladvitamin** [comment]
2019 year :)
Its dont fix. Why?
