### ISSUE TITLE
Testing API in another host fails with $this->call (Request)

### ISSUE THREAD

**Issue by thiagof** [laravel/framework#10034]
`$this->call` only hits localhost, despite the full-domain $uri param

Please consider this TestCase

```php
class ApiTest extends TestCase {
    public function testUri() {
        $response = $this->call('GET', 'http://example.com/');
        $this->assertContains('Example Domain', $response->getContent());
    }
}
```

Will fail and throw "Laravel" content.
It's `laravel 5.0`

**The Response**

    Illuminate\Http\RedirectResponse[10]
        request = Illuminate\Http\Request[32]
            routeResolver = Closure[2]
                static = array[1]
                    route = Illuminate\Routing\Route[10]
                        ...
                this = Illuminate\Routing\Router[13]
                    verbs = array[7]
                        ...
            server = Symfony\Component\HttpFoundation\ServerBag[1]
                parameters = array[16]
                    SERVER_NAME = (string) example.com
                    SERVER_PORT = (int) 80
                    HTTP_HOST = (string) example.com
                    HTTP_USER_AGENT = (string) Symfony/2.X
                    HTTP_ACCEPT = (string) text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
                    HTTP_ACCEPT_LANGUAGE = (string) en-us,en;q=0.5
                    HTTP_ACCEPT_CHARSET = (string) ISO-8859-1,utf-8;q=0.7,*;q=0.7
                    REMOTE_ADDR = (string) 127.0.0.1
                    SCRIPT_NAME = <string>
                    SCRIPT_FILENAME = <string>
                    SERVER_PROTOCOL = (string) HTTP/1.1
                    REQUEST_TIME = (int) 1440461774
                    PATH_INFO = <string>
                    REQUEST_METHOD = (string) GET
                    REQUEST_URI = (string) /
                    QUERY_STRING = <string>
            session = Illuminate\Session\Store[8]
                id = (string) 01543bf47cce1f5eb4a65dbb09141850f9b154fa
                name = (string) laravel_session
                attributes = array[2]
                    _token = (string) MzzGLlOFx525NQDKNFr1kuNztpVxeCh9faVs86QH
                    _previous = array[1]
                        ...
        session = Illuminate\Session\Store[8]
            id = (string) 01543bf47cce1f5eb4a65dbb09141850f9b154fa
            name = (string) laravel_session
            attributes = array[2]
                _token = (string) MzzGLlOFx525NQDKNFr1kuNztpVxeCh9faVs86QH
                _previous = array[1]
                    url = (string) http://example.com
            started = (bool) 1
        targetUrl = (string) http://example.com/site/carros
        headers = Symfony\Component\HttpFoundation\ResponseHeaderBag[5]
            headers = array[4]
                cache-control = array[1]
                    0 = (string) no-cache
                date = array[1]
                    0 = (string) Tue, 25 Aug 2015 00:16:14 GMT
                location = array[1]
                    0 = (string) http://example.com/site/carros
                content-type = array[1]
                    0 = (string) text/html; charset=UTF-8
            cacheControl = array[0]
        content = (string) <!DOCTYPE html> <html>     <head>         <meta charset="UTF-8" />         <meta http-equiv="refresh" content="1;url=http://example.com/site/carros" />          <title>Redirecting to http://example.com/site/carros</title>     </head>     <body>         Redirecting to <a href="http://example.com/site/carros">http://example.com/site/carros</a>.     </body> </html>
        version = (string) 1.1
        statusCode = (int) 302
        statusText = (string) Found
        charset = <null>

related #1342

**Comment by GrahamCampbell** [comment]
5.0 is not supported
