### ISSUE TITLE
[5.1] forceDelete() will not works if you soft delete() first

### ISSUE THREAD

**Issue by rentalhost** [laravel/framework#10041]
Basically, if you load a `trashed()` row or just `delete()` it first, and try to `forceDelete()` it, it'll not work because, internally, the `$exists` is used to check if something will be do.

**Example:**

    $user = new User;
    $user->username = 'John Doe';
    $user->save(); 

    $user->delete();      // now $user->exists === false, ok
    $user->forceDelete(); // nothing happen, $user still exists on DB.

    $user->restore();     // now $user->exists === true, ok
    $user->forceDelete(); // now row is really removed from DB.

It'll happen too if you do that with a previously soft deleted row:

    $user = User::withTrashed()->find(1); // soft-deleted row
    $user->forceDelete(); // nothing! :(

**Comment by rentalhost** [comment]
Seems that `Illuminate\Database\Eloquent\SoftDeletes` set a property called `$forceDeleting` to `true`. But this value is not used in nowhere, except in `self::performDeleteOnModel()`, that is not called because `delete()` (from `Illuminate\Database\Eloquent\Model`) will fail to check if `$this->exists`.

**Comment by GrahamCampbell** [comment]
See https://github.com/laravel/framework/pull/9806.
