### ISSUE TITLE
[5.1] Event broadcasting fires before event handled by the listener

### ISSUE THREAD

**Issue by mlanin** [laravel/framework#10046]
When event is fired, broadcasting fires before it's listener. It brings lots of problems when you want to modify data within the listener.

Lets create an example. I create a job, that has a status `working`, then I fire `JobFinished` event, that  has a listener, that changes it's status to `finished` and then broadcasts.

```php
$job = new Job(['status' => 'working']);
event(new JobFinished($job));
```

**Event**

```php
<?php

namespace App\Events;

use App\Job;
use App\Events\Event;
use Illuminate\Queue\SerializesModels;
use Illuminate\Contracts\Broadcasting\ShouldBroadcast;

class JobFinished extends Event implements ShouldBroadcast
{
    use SerializesModels;
    /**
     * @var Job
     */
    public $job;

    /**
     * Create a new event instance.
     *
     * @param Job $job
     */
    public function __construct(Job $job)
    {
        $this->job = $job;
    }

    /**
     * Get the channels the event should be broadcast on.
     *
     * @return array
     */
    public function broadcastOn()
    {
        return ['user.'.\Auth::id()];
    }
}
```

**Listener**

```php
<?php

namespace App\Listeners;

use App\Job;
use App\Events\JobFinished;

class UpdateJobOnFinish
{
    /**
     * Handle the event.
     *
     * @param  JobFinished  $event
     * @return void
     */
    public function handle(JobFinished $event)
    {
        $event->job->status = 'finished';
        $event->job->save();
    }
}
```

I was waiting that event will be broadcasted with already finished job, but the job will be sent untouched, because event broadcasts before listener is fired. 

This is a big problem, because you have to update your data in your controller before event is fired (that is not always suitable) or in the event itself (that is not a best way too).

**Comment by GrahamCampbell** [comment]
This is the expected behaviour. If you don't want this, you need to write an event handler to do the equivalent of broadcasting your event.

**Comment by mlanin** [comment]
@GrahamCampbell Event listeners are mostly used for using and updating data passed through events. With this behaviour listeners become useless because you can modify whatever you want, but you will never see your changes on the client.

**Comment by alankarglobant** [comment]
I am also facing this same issue in Laravel 5.6. The same event is broadcasted and have Listener. 
So, Listener updates the status of the records but the UI is not reflected accordingly. 
My analysis is also same I think the event is broadcasted first before it is being handled by his listeners.
