### ISSUE TITLE
[5.2] Support to Model::morphsObject

### ISSUE THREAD

**Issue by rentalhost** [laravel/framework#10057]
It'll help you set a morph object to a morph columns.

**Usage example:** imagine that you have two morphs columns in a single model, like this:

    $table->morphs('where'); // where_id, where_type
    $table->morphs('agent'); // agent_id, agent_type

Now you need set two objects to this morphs columns. Currently you need do it manually (*or not?*). Like it:

    $row->where_id = $where->id;
    $row->where_type = get_class($where);
    $row->agent_id = $agent->id;
    $row->agent_type = get_class($agent);

But it is too simple, and `$where` or `$agent` can be `null`, so you need check it more before to do that.

My suggestion is a single method on `Model` that will help you set this values. I don't guess that need a method to get it, because you can work with `Relation`, but is valid too (*I'll exemplify later*).

    $row->morphsObject($where, "where"); // Mode 1
    $row->morphsObject($agent, "agent_id", "agent_type"); // Mode 2

Both modes will works, but *mode 1* is how Laravel works currently by use `id` and `type` as column suffix. The *mode 2* is only if user set a own column suffixes.

It should accept a mixed value, but only will work if it is a instance of `Model`, because it needs the model class name and the current id. I suggest something like that (*simplified*):

```
function morphsObject($object, $columnBasis, ...) {
    if ($object instanceof self && $object->exists) {
        $this->{$columnBasis . '_id'} = $object->id;
        $this->{$columnBasis . '_type'} = get_class($object);

        return;
    }

    $this->{$columnBasis . '_id'} = null;
    $this->{$columnBasis . '_type'} = null;
}
```

**Signature suggestion:** 

```
/**
 * @param Model|mixed     $object      The object to morphs to.
 * @param string          $columnId    The column id to morphs to or the column basis.
 * @param string          $columnType  The column type to morphs to.
 *
 * @return void
 */
function morphsObject ($object, $columnId, $columnType = null); 
```

When `$columnType` is null, consider `$columnId` as the column basis and append their suffixes. Example:

    $columnType = $columnId . '_type';
    $columnId = $columnId . '_id';

**Additional:** supports to `Model::morphedObject` to retrieve the morphed object on column. The signature will be the same, except that it'll not have the first argument.

    $where = $row->morphedObject("where");
    $agent = $row->morphedObject("agent");

It'll returns `null` if columns are empty, or will do a `Model::find()` and return it.

**Comment by GrahamCampbell** [comment]
Closing due to no interest.
