### ISSUE TITLE
Multiple subviews extending a master template only works once.

### ISSUE THREAD

**Issue by rogue780** [laravel/framework#10052]
This issue is essentially a duplicate of this SO post I managed to find: http://stackoverflow.com/questions/25093731/blade-extending-a-template-in-multiple-subviews

Basically, I have a template called cards.card:

```
<div class="panel panel-primary">
    <div class="panel-heading">
        @yield('heading')
    </div>
    <div class="panel-body">
        @yield('body')
    </div>
    <div class="panel-footer">
        @yield('footer')
    </div>
</div>
```

And I have several templates extending it:

```
//cards.files
@extends('cards.card')

@section('heading')
    Files
@stop

@section('body')
    ...
@stop

@section('footer')
    <button class="btn btn-primary">Submit</button>
@stop

//cards.register
@extends('cards.card')

@section('heading')
    Register
@endsection

@section('body')
        @include('forms.register')
@endsection

@section('footer')
        <button class="btn btn-primary">Submit</button>
@endsection

//more templates, but you get the picture

```

And then I'm using them as such:

```
@extends('layouts.master')

@section('content')
    <div class="row">
        @include('cards.register')
    </div>
    <div class="row">
        @include('cards.upload')
    </div>
    <div class="row">
        @include('cards.packages')
    </div>
    <div class="row">
        @include('cards.files')
    </div>
@endsection
```

The problem is, then, that all of the templates are showing as the cards.register template, as you can see here:
![image](https://cloud.githubusercontent.com/assets/247716/9505836/a4b1c45e-4c12-11e5-99e1-1e776d191baf.png)

Now, to me, it seems intuitive that each time I @include a view, it would have its own scope/instance/whatever instead of being immutable after the first one. But that doesn't seem to be the case here. I've also tried using {!! view('cards.upload') !!} in case that ran differently, but to no avail.

Am I missing something obvious?

**Comment by GrahamCampbell** [comment]
Please ask on the forums.

**Comment by rogue780** [comment]
@GrahamCampbell I've been in larachat talking about it. I'm wanting clarification if it's a bug or an undocumented "feature" and if it's the former, I'd like to have it queued to get fixed.

**Comment by rogue780** [comment]
I mean, if you really want, I can make a forum post, and then come back tomorrow and make the same exact issue again. Would you prefer that?

**Comment by GrahamCampbell** [comment]
Well, our issues are only here for the community to ask each other about bugs and fix them, and are not used by Taylor. If you want clarification, you'd have to ask him directly.

**Comment by rogue780** [comment]
Would you mind telling me how I should have worded it to indicate that I
was asking about this bug? I didn't think Taylor was the only person who
could provide clarification.

Regardless, I have created a forum post here:
http://laravel.io/forum/08-26-2015-multiple-subviews-extending-a-master-template-only-works-once
and in 24 hours when I either get no replies or, like in larachat, I get
people who have had the same issue and not had the bug get fixed, I will
create the issue again. Perhaps with less information about what exactly is
going on and less politeness since that seems to have caused some confusion
as to whether I was reporting a bug or not.
