### ISSUE TITLE
[5.1] Catching Log Events

### ISSUE THREAD

**Issue by stevebauman** [laravel/framework#10051]
I'm not too sure how to go about this, but technically shouldn't the outcome of the code below be `Log was written to`?:

```php
Route::get('/', function () {

    Event::listen('illuminate.log', function()
    {
        die('Log was written to');
    });

    throw new Exception('Exception');
});
```

When exceptions are thrown, a log entry is created, however it doesn't seem the event is dispatched when this happens. Only when you explicitly call the log will the event be dispatched. For example the output of this is `Log was written to`:

```php
Route::get('/', function () {

    Event::listen('illuminate.log', function()
    {
        die('Log was written to');
    });

    Log::info('info');

    throw new Exception('Exception');
});
```

I'm not exactly sure if this is a bug or not? I'm guessing not, and if that's the case, does anyone have any tips on doing this? I just need to catch when the log is being written to and save the information along with it.

https://github.com/laravel/framework/blob/5.1/src/Illuminate/Log/Writer.php#L295.

**Comment by GrahamCampbell** [comment]
Please ask on the forums.
