### ISSUE TITLE
Run query scope on eager loaded relationship

### ISSUE THREAD

**Issue by cabloo** [laravel/framework#10061]
I ran into the [issue described here](http://stackoverflow.com/questions/22942021/eager-loading-related-model-using-query-scope) and also hoped there might be a shorthand for query scoping an eager loaded relationship (without having to add a method to the Model). I realize this could be done with global scopes but I'd like to be able to use this with more complicated examples as well - not obvious ones like active/visible mentioned below. I have proposed some syntax below for how this could be laid out.

### Proposed syntax (according to the models in the issue above):

```php
Box::with('widgets#active')->get()
```

In this case, the query for widgets would have the `active` query scope run on it, so only widgets that were active would appear.

### Multiple scopes

```php
Box::with('widgets#active#frontPage')->get()
```

Same as above, with the additional `frontPage` scope run, so only front page widgets would appear.

### Nested relationships

```php
Box::with('widgets#active.parent#visible')->get()
```

Show only active widgets, and eager load all the parents, scoped by `visible`. The parent would be null on widgets that did not have a `visible` parent. The logic at this point would be up to debate - whether or not to filter out widgets with a null parent.

**Comment by antonybudianto** [comment]
nice :+1:  
but for multiple scopes, I will prefer 
```php
Box::with('widgets[active, frontPage].parent[visible]');
```
since I hate to repeat the same '#' sign over and over, well just opinion :smiley:

**Comment by cabloo** [comment]
I agree Antony. I thought of that with parentheses instead but it seemed
hard to read due to the parentheses in the functions as well. That is
definitely cleaner syntax.

**Comment by phroggyy** [comment]
What's the problem with doing 
```
Box::with(['widgets' => function ($widget) {
    $widget->active()->frontPage();
}
```

Or did I misunderstand?

**Comment by cabloo** [comment]
@phroggyy that quickly expands into multiple complex nested groups - it seems like for how simple that would be to emulate by a computer vs. how unnecessarily ugly it is to write every time as a programmer, it's an obvious choice to make it easier.

**Comment by lukasgeiter** [comment]
:+1: I like the idea.

@cabloo You should try to implement a solution and make a PR for this.

**Comment by cabloo** [comment]
Will do when I get some time this weekend.

Does anyone disagree that this format:

```
Box::with('widgets[active,frontPage].parent[visible]');
```

is better than this one:

```
Box::with('widgets#active.parent#visible')->get()
```

Or have another suggested format? I will precede assuming the first one is best unless someone offers a better one.

**Comment by emjayess** [comment]
nothing was ever implemented for this, eh?
