### ISSUE TITLE
Request validation when array passed

### ISSUE THREAD

**Issue by ZiFFeL1992** [laravel/framework#10065]
Boolean validation doesn't work when an array is passed from the HTML form
Also should be nice to add "on" like a "true" value as "on" is returned when you use checked instead of value="1|true" on the HTML.

The first image shows the return of the request without using boolean on the rules, if i use it i'm unable to complete the request.

I've just try to do the same with role, but "numeric" this time and again a validation error, so if "array" is passed to validation the rules before it should be specially treated.

![captura de pantalla 2015-08-28 a las 4 40 59](https://cloud.githubusercontent.com/assets/5492960/9537926/09b8505c-4d3f-11e5-9a3d-dae8d539a6bd.png)
![captura de pantalla 2015-08-28 a las 4 40 14](https://cloud.githubusercontent.com/assets/5492960/9537925/09b7fa4e-4d3f-11e5-8fa7-41b398a8243c.png)

**Comment by antonybudianto** [comment]
I already created a [PR](https://github.com/laravel/framework/pull/9959) for that, waiting for approval :smiley:

**Comment by ZiFFeL1992** [comment]
Thanks you both :D
