### ISSUE TITLE
[5.1] Content not being properly rendered with multiple subviews extending the same master template.

### ISSUE THREAD

**Issue by rogue780** [laravel/framework#10073]
Including multiple views with different content that extend the same master template results in all of the views showing the data from the first template.

The problem is likely due to the way that the View Factory keeps track of the sections in ```$sections``` by only referencing the section name rather than keeping track of which view is extending the master template.

So, for example, if I have a template that has 

```//card
@yield('content')
```

and two views as such:

```//view1
@extends('card')
@section('content')
    foo
@stop
```

```//view2
@extends('card')
@section('content')
    bar
@stop
```

and then include them as such:

```
@include('view1')

@include('view2')
```

the output is

```
foo
foo
```

instead of the expected

```
foo
bar
```

As @GrahamCampbell suggested, I have posted it to the forums, but I have found no solution.

To be clear, I am reporting a bug in the blade/view system in Laravel 5.1.

**Comment by rogue780** [comment]
I have created a repo to demonstrate the issue: https://github.com/rogue780/bladeissue

**Comment by TerrePorter** [comment]
@rogue780 I thought my post was a bit long for github so I posted a reply on your forum post at http://laravel.io/forum/08-26-2015-multiple-subviews-extending-a-master-template-only-works-once

**Comment by rogue780** [comment]
@TerrePorter thanks. I understand why it happens, but I guess I don't think it should happen that way. As far as the complexity of a change goes, there really only needs to be a new scope created when the ```@extends``` directive is used (I think). It could be done, perhaps, by making ```$sections``` work like: ```$sections[$extendedTemplate][$section]``` or even by putting the views into a tree and compiling them from the branches towards the root(s).

**Comment by ansata2001** [comment]
Try using the @overwrite directive instead of the @stop. It will wipe out the previous value. This doesn't work for @section('name', 'value') though unfortunately

**Comment by rogue780** [comment]
thanks @ansata2001 that worked. Thanks, for letting me have this issue, @GrahamCampbell. Pip pip cheerio!
