### ISSUE TITLE
Validating max size of an uploaded image with ajax request that exceed upload_max_filesize directive

### ISSUE THREAD

**Issue by ahlechandre** [laravel/framework#10077]
I'm using ajax request to send an image (as FormData) to server and returning immediately some data. (for test)

```php
return [
  'photo' => Request::file('avatar'),
  'hasFile' => Request::hasFile('avatar'),
  'extension' => Request::file('avatar')->getClientOriginalExtension(),
  'size' => Request::file('avatar')->getClientSize(),
  'maxFileSize' => Request::file('avatar')->getMaxFilesize()
];
```

When image is less than **upload_max_filesize** directive, i have this response:

```json
{"photo":{},"hasFile":true,"extension":"jpg","size":900498,"maxFileSize":2097152}
```
or
```php
Input::file('avatar')->getSize() // 900498
```
When image is greater than **upload_max_filesize** directive, i have this response:

```json
{"photo":{},"hasFile":false,"extension":"jpg","size":0,"maxFileSize":2097152}
```
or
```php
Input::file('avatar')->getSize() // false
```
Look at ```size``` on last response. I expected some feedback as *The file "avatar.jpg" exceeds your upload_max_filesize ini directive* for php.ini fails related to the max size. 

How i can access the value of size when exceed the directive?

**Comment by bonzai** [comment]
You're probably [exceeding](http://us.php.net/manual/en/ini.core.php#ini.post-max-size) the `post_max_size` limit:

> If the size of post data is greater than post_max_size, the $_POST and $_FILES superglobals are empty.

Try to increase it or check the size of an uploaded file with JavaScript.

**Comment by GrahamCampbell** [comment]
This has come up before. Please read the previous issues and PRs.
