### ISSUE TITLE
Only Chrome TokenMismatchException

### ISSUE THREAD

**Issue by rafaelsisweb** [laravel/framework#10075]
Hi, im getting some problems using CSRF. Every form submited on Google Chrome fails with TokenMismatchException. In some cases if I try to refresh and force to resubmit some times so this works, but always fail on firsts.

Doing same with FF works like a charm.

I'd test with simple forms and default routes to Auth. (http://laravel.com/docs/5.1/authentication#authentication-quickstart)
The forms has "{!! csrf_field() !!}". 

Disabling csrf verification in Kernel config works well. 

My sytem info:
Laravel 5.1.10
Chrome 44.0.2403.157 (64-bit) (LINUX)

![screenshot-preview 6nh0r8omakbj4ispvuu9vrpmzvkj4iq32orz8r7rykfbt9 box codeanywhere com 8000 2015-08-28 12-47-58](https://cloud.githubusercontent.com/assets/7429379/9556344/6114cac2-4daa-11e5-87b8-e892cc50d958.png)

**Comment by GrahamCampbell** [comment]
Please ask on the forums.

**Comment by rafaelsisweb** [comment]
Thanks.
