### ISSUE TITLE
[Proposal] Add optional messages to AssertionsTrait assertions

### ISSUE THREAD

**Issue by euoia** [laravel/framework#10078]
TestCase.php extends PHPUnit_Framework_TestCase and adds AssertionsTrait which provides some additional assertions beyond those provided by PHPUnit.

For consistency with the PHPUnit assertions, it would be nice if the assertions added by AssertionsTrait took an optional message parameter to display when the assertion fails.

All the PHPUnit assertions have optional messages. This suggested change should be as simple as passing through the message to the PHPUnit assertions that are used by AssertionsTrait.

I can submit a PR for this if it is likely to be accepted.

See PHPUnit documentation for more information:
https://phpunit.de/manual/current/en/phpunit-book.html

**Comment by ArjanSchouten** [comment]
:+1:

**Comment by thekonz** [comment]
+1

**Comment by GrahamCampbell** [comment]
We don't process proposal issues, only proposal PRs. If you have any questions, contact Taylor on slack.
