### ISSUE TITLE
EloquentUserProvider does not seem to honor setting for config/auth User model 

### ISSUE THREAD

**Issue by tommhuth** [laravel/framework#10085]
I've change the location of my User model, updated the namespace accordingly and updated config/auth. Still Laravel 5.1 fails with a:

~~~
FatalErrorException in EloquentUserProvider.php line 127: 
Class '\App\User' not found
~~~

If I change the method `createModel` there to return a fixed string (my User class name), instead of the `model` paramter passed in, everything works. It's as if it's completey ignoring the auth/config setting, and return a default one. If i leave the default User class, it also works as expected.

If I do Auth::user() the default class is used. Since this is a AJAX application and the correct user is fetched through an API key stored with the user id in a table, and Auth is only used for inital access, I do not access data through Auth::user() so it does not pose a problem for me -- still ugly though. 

Custom User class:

~~~
namespace  App\Todo\Users;

use App\Todo\IIdentifiable;
use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Support\Facades\Hash;
use Nicolaslopezj\Searchable\SearchableTrait;


class User extends Model implements AuthenticatableContract, IIdentifiable {

	use Authenticatable, SearchableTrait;
       

       /* relations and custom methods */
}
~~~

config\auth.php:
~~~ 
'model' => '\App\Todo\Users\User',
~~~

Does anyone know what is going on here? Is there something missing in relation to `AuthenticatableContract`?

**Comment by GrahamCampbell** [comment]
```php
    /**
     * Create an instance of the Eloquent user provider.
     *
     * @return \Illuminate\Auth\EloquentUserProvider
     */
    protected function createEloquentProvider()
    {
        $model = $this->app['config']['auth.model'];

        return new EloquentUserProvider($this->app['hash'], $model);
    }
```

**Comment by GrahamCampbell** [comment]
Looking at the code, this definetely works.

**Comment by GrahamCampbell** [comment]
Are you trying to change that value at runtime, You'll need to clear the resolved eloquent user provider instance if that's the case.

**Comment by tommhuth** [comment]
No, not changeing anything at runtime. 

When I do `dd($this->model)` in `createEloquentProvider()` I still returns 'App\User'. Is there any caching of the config files I am stuck with? 

This is really wired, it does not appear to have any trouble reading any of my other config files entries.

**Comment by tommhuth** [comment]
Is there any default  values provided for the $app['config'] getter?

**Comment by tommhuth** [comment]
more digging reveales that changes in my auth config isn't reflected, though where it gets the default values I have no idea.

**Comment by GrahamCampbell** [comment]
> Is there any caching of the config files I am stuck with?

yes there is. You need to clear the config cache. There's an artisan command for that.

**Comment by tommhuth** [comment]
Thanks man! 

Can't believe it was that easy! (Clearing the config worked)
