### ISSUE TITLE
Optional one-to-many relationships generate impossible SQL statements

### ISSUE THREAD

**Issue by fisharebest** [laravel/framework#10090]
Suppose a table has an optional foreign key.  i.e. a column can contain NULL, as well as the primary key from another table.

If we attempt to fetch a non-existant relationship (e.g. `$model->note` where `$model->note_id` is `null`), then lavarel correctly returns NULL for the foreign object - but only after having executed a query such as

```sql
select * from "note" where "note"."id" is null limit 1
```

This will obviously not return any rows, the primary key cannot be NULL.

A possible fix is to change `BelongsTo::getResults()` from

```php
return $this->query->first();
```

```php
if (/* the foreign key */ === null) {
    return null;
} else {
    return $this->query->first();
}
```

**Comment by jrumbut** [comment]
Is it returning rows when it shouldn't be returning rows?

I just tested out that scenario in the MySQL console and there was no error, it just returns an empty set.

Maybe try

```
if($model->note_id !== null) {

**Comment by fisharebest** [comment]
> Is it returning rows when it shouldn't be returning rows?

No.  It is simply executing a query that can never return any rows: `SELECT * FROM table WHERE primary_key IS NULL;`

> Or even implement something like `public function hasNote()` in Model to check note availability?

If I was just fetching one linked record from one table, then maybe.

But I'm using eager loading with lots of related tables, e.g. `$model->where(...)->with('foo','bar.baz')`.

I can't easily check whether any of the `model->bar` entities will have a linked `baz` entity.  If they don't, then the framework will needlessly execute `SELECT * FROM baz WHERE id_key IS NULL;`

**Comment by fisharebest** [comment]
...correction.  For eager loading, it runs `SELECT * FROM baz WHERE id IN (0)`.  Which also will never return any rows.

**Comment by jrumbut** [comment]
A primary key can be equal to 0 (in MySQL anyway), in fact if you don't set up AUTO-INCREMENT, have a primary key of type INT, and don't set the primary key when inserting a record, it will be equal  to 0. See https://bugs.mysql.com/bug.php?id=41734

It seems like the behavior here is consistent, and that trying to predict when a syntactically valid SQL statement won't return records is likely to frustrate as many users as it helps.

If you are dealing with a collection of `Model`s you could use a scope, that seems like the best way forward here.

**Comment by fisharebest** [comment]
> A primary key can be equal to 0

But my foreign key is `NULL`.  So, the framework is converting my `NULL` to `0`, and then trying to use it to look up another table.  If I did have a primary key of `0` in the other table, it would be fetching the wrong row!

In any case, this is a different problem - and should be in a different bug report.

This report is about pointlessly fetching rows where the FK is NULL.

**Comment by jrumbut** [comment]
I understand that this seems wasteful, however when you execute $model->note you're asking it to fetch a note. I worry that this will add unnecessarily to the cyclomatic complexity of Eloquent. Nullable foreign keys seem to often lead to hinkier code. 

If you are iterating over Models and need to ensure they all have notes just add:

```
public function scopeHasNote($query)
{
    return $query->whereNotNull('note_id');
}
```

Then you can run something like `Model::hasNote()->get()` instead of `Model::all()`

**Comment by fisharebest** [comment]
> I worry that this will add unnecessarily to the cyclomatic complexity of Eloquent

This solution works for me.  One extra `if` statement.

```
    BelongsTo::getResults() {
        if ($this->parent->{$this->foreignKey} === null) {
            return null;
        } else {
            return $this->query->first();
        }
    }
```

**Comment by jrumbut** [comment]
Does that work if the foreign key is not on the other model's primary key?

**Comment by jrumbut** [comment]
Meaning, does it allow the use of null as a valid foreign key on those fields?

**Comment by fisharebest** [comment]
> Does that work if the foreign key is not on the other model's primary key?

It is conventional that a foreign key is linked to the primary key on another table.  But as you point out, it can also be linked to any column with a unique index.  This difference, of course, is that unlike a primary key, a unique index may contain `NULL`.

However, the behavior is the same - and yes the code above works.  A `NULL` value in a foreign key will **never** match a row in another table, because `NULL` does not equal anything (not even `NULL`!).

**Comment by fisharebest** [comment]
Is this being closed because:

1) the issue is considered invalid and no pull requests will be accepted.
2) the issue is considered valid, but nobody produced a PR.

Some guidance here would be helpful.  Nobody wants to waste time producing PRs that aren't going to be accepted.

**Comment by GrahamCampbell** [comment]
Sorry. I forgot to explain. Basically, we don't process proposal issues. Feel free to discus on slack though before sending a PR.
