### ISSUE TITLE
Parameter mismatch when formatting SQL error

### ISSUE THREAD

**Issue by richardwyke** [laravel/framework#10107]
The error i see when trying to do an insert of a large array of records is
```preg_replace(): Parameter mismatch, pattern is a string while replacement is an array```

Commenting out everything after the getMessage + the str_replace_array here, \Illuminate\Database\QueryException::formatMessage
```php
protected function formatMessage($sql, $bindings, $previous)
{
    return $previous->getMessage().' (SQL: '.str_replace_array('\?', $bindings, $sql).')';
}
```

I get the actual error which is:
```SQLSTATE[21S01]: Insert value list does not match column list: 1136 Column count doesn't match value count at row 80```

**Comment by dmgawel** [comment]
SQL Inserts in Laravel are treated as batch inserts. It means, that every record in your big array must be uniform (have exactly the same set of columns).

For example, this will **fail**:
```php
DB::table('users')->insert(array(
    array('email' => 'john@example.com'),
    array('email' => 'john2@example.com', 'name' => 'John2')
));
```
But this will **work**:
```php
DB::table('users')->insert([
    ['email' => 'john@example.com', 'name' => 'John'],
    ['email' => 'john2@example.com', 'name' => 'John2']
]);
```
If you have inconsistent records split them into separate inserts.
