### ISSUE TITLE
[Suggestion] Migration Rollback Feature

### ISSUE THREAD

**Issue by darryldecode** [laravel/framework#10108]
Hi, would it be good if we have additional feature for rolling back migrations like for example, you want to see all available migration batch:

```
php artisan migrate:rollback --list
```

The command above will list all available rollback batches.

some like:

---------------------------------------------------------------------------------------------------------------------
| BATCH | DATE MIGRATED | DESCRIPTION                                       |
|-------|---------------|---------------------------------------------------|
| 1     | xxxx-xx-xx    | "My custom component database migrations"         |
| 2     | xxxx-xx-xx    | "My another custom component database migrations" |
| 3     | xxxx-xx-xx    | "Some other migrations"  |
---------------------------------------------------------------------------------------------------------------------

Then we can select a specific migration to rollback:
``` php artisan migrate:rollback --batch=2```

The command above will rollback all migrations at specific batch which is on batch 2..

I guess this will be useful in some other cases like you want to rollback some specific batch but don't want to mess with the latest migrations, or not rollback everything just to rollback migrations on the midst batch.. Just a thought..

Thank you!

**Comment by jbrooksuk** [comment]
Rolling back `x` migrations won't be supported it seems; https://github.com/laravel/framework/pull/9028

**Comment by GrahamCampbell** [comment]
What you can do is just extend laravel's migrator.
