### ISSUE TITLE
Unnecessary HMAC signature when create a new token for the user.

### ISSUE THREAD

**Issue by m00t** [laravel/framework#10112]
https://github.com/laravel/framework/blob/5.1/src/Illuminate/Auth/Passwords/DatabaseTokenRepository.php#L171
```php
    /**
     * Create a new token for the user.
     *
     * @return string
     */
    public function createNewToken()
    {
        return hash_hmac('sha256', Str::random(40), $this->hashKey);
    }
```

Since Str::random and Str::randomBytes are crypto strong, this should be replaced by something like this

```php
        $bytes = Str::randomBytes(32);
        $token = '';
        for ($i = 0; $i < 32; $i++) {
            $token .= sprintf('%02x', ord($bytes[$i]));
        }
        return $token;
```

Or for lazy developer and more readability like this:

```php
        return sha256(Str::randomBytes(32));
```

But sha256 really does not do anything here except for readability and simplicity.

**Comment by dmgawel** [comment]
@m00t is right. Unless we use HMAC for proving something (and in our case we're not) it's not necessary. Additionally: SHA does not adds entropy. So I would go with first approach (using bin2hex).

**Comment by GrahamCampbell** [comment]
We're open to PRs. :)

**Comment by m00t** [comment]
SHA does not add entrypy, yeah. I used it because I did not know about bin2hex function =) bin2hex is perfectly ok here.
