### ISSUE TITLE
[5.1] User isn't being injected into Gate

### ISSUE THREAD

**Issue by Jnesselr** [laravel/framework#10117]
I believe I did the upgrade correctly, but I'm having some issue with the new authorization stuff. It didn't matter whether the policy returned true or false, it still came up as false. Looking into Illuminate\Auth\Access\Gate, it seems it returns false if there's no user. I added these lines before the user check:
```
error_log(\Auth::user());
error_log(app('auth')->user());
error_log($this->user);
```
The first two show the user logged in, while the last one doesn't. I'm sure I just did something incorrectly with the upgrade, but I can't figure out what.

**Comment by GrahamCampbell** [comment]
The user isn;'t meant be be injected. It's dynamically resolved.

**Comment by GrahamCampbell** [comment]
I assume you're on 5.1.11. This was fixed in 5.1.12.

**Comment by Jnesselr** [comment]
Shouldn't there be a note or something about that, then? I mean technically you have to upgrade to 5.1.12 to get the gates to work.

**Comment by GrahamCampbell** [comment]
No, we assume people update to the latest version. We don't support anything but the latest version.

**Comment by Jnesselr** [comment]
I assumed 5.1.11 was the latest version. Where can I find information on what the latest version is without running a composer update?

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/releases

**Comment by GrahamCampbell** [comment]
https://packagist.org/packages/laravel/framework
