### ISSUE TITLE
[bug]The env function can not be read on async queue.

### ISSUE THREAD

**Issue by zhangmazi** [laravel/framework#10126]
@taylorotwell 
Laravel Version:5.1.12(LTS)
config/app.php code ...
>  'url' => env('SITE_DOMAIN_WWW', 'http://localhost'),

config/queue.php code...
>'default' => env('QUEUE_DRIVER', 'sync'),

my /.env code...
>QUEUE_DRIVER=database
>SITE_DOMAIN_WWW=http://www.dev.local.cn

routes.php code..
>Route::get('hello/world.html', array('as' => 'hello_world', 'uses' => 'IndexController@HelloWorld'));

resources/views/index.blade.php   code...
>route('hello/world.html');

I wish the content is "http://www.dev.local.cn/hello/world.html", but it show "http://localhost/hello/world.html" context of  blade view was rendered when the console excute "queue:liste" for fire a queue job;

**Comment by stars8422** [comment]
www.dev.local.cn not a url.Need http or https

**Comment by zhangmazi** [comment]
@stars8422 I have edited the issue and add "http://",  but it was not solved.

**Comment by zhangmazi** [comment]
@stars8422  Maybe Laravel do not require env function on procedure of async queue.

**Comment by GrahamCampbell** [comment]
Likely you forgot to clear the config cache.

**Comment by zhangmazi** [comment]
@GrahamCampbell 
I had tried todo config:cache, but it was not solved.
