### ISSUE TITLE
Laravel 5.1 Homestead VBoxHeadless.exe Application error Windows 7 64

### ISSUE THREAD

**Issue by stars8422** [laravel/framework#10124]
![untitled](https://cloud.githubusercontent.com/assets/11686687/9613598/2363eff2-510e-11e5-8027-6837ffe2138f.png)
When  run vagrant up then show that error.

**Comment by lukasgeiter** [comment]
I doubt this is a homestead issue. Sounds more like a virtualbox (or maybe vagrant) problem...

**Comment by GrahamCampbell** [comment]
Try updating to the latest version of virtual box.
