### ISSUE TITLE
Can't use "url" helper function in config files. Artisan doesn't work

### ISSUE THREAD

**Issue by mspiderv** [laravel/framework#10125]
When I use "url" helper function in some config file, then Artisan doesn't work. I gets this error 

> PHP Catchable fatal error:  Argument 2 passed to Illuminate\Routing\UrlGenerator::__construct() must be an instance of Illuminate\Http\Request, null given, called in /var/www/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php on line 64 and defined in /var/www/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php on line 99

**Comment by stars8422** [comment]
Are you create a new URL that doesn't exist in your route

**Comment by mspiderv** [comment]
If I understand you correctly, then my answer is no. It don't depends if URL passed to "url" helper function is real or fake. It will always show this error, but only in Artisan. You can try it.

**Comment by lukasgeiter** [comment]
I don't think you should be using the URL helper in your config files at all.

**Comment by mspiderv** [comment]
Why ? Check this https://github.com/barryvdh/laravel-elfinder/blob/master/config/elfinder.php#L24

**Comment by stars8422** [comment]
@mspiderv  Install elFinder Package perfectly then its work

**Comment by mspiderv** [comment]
I don't understand you. If I require package "barryvdh/laravel-elfinder" or any other and then put "url" function in some configuration file, Artisan will NOT work. That is everything I wanted to say. I don't know whether I can use "url" function in config files, but when I use it, application WILL work in browser, but it WILL NOT work in Artisan. That's all I wanted to say. So can I use "urL" function in config files or no ?

**Comment by arrilot** [comment]
That's a problem of a package, not framework.
You are not supposed to use anything except Dotenv in configs.
