### ISSUE TITLE
[5.1] Unable to fetch the Gate facade

### ISSUE THREAD

**Issue by antoinerey** [laravel/framework#10120]
Hello !

I'm trying to implement the new policy system. I followed every step described in the upgrade guide and it seems that my vendors directory does not include the Gate facade.

Btw, when starting a fresh project, the facade is here.

Any idea ?

PS : After updating, my project is using the Laravel v5.1.12.

**Comment by GrahamCampbell** [comment]
Can't replicate.

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/archive/v5.1.12.zip
