### ISSUE TITLE
Please move Authorizable to illuminate/auth

### ISSUE THREAD

**Issue by winkbrace** [laravel/framework#10123]
I have a separate composer package that handles the authentication stuff. It contains the User object.

The object used to be valid with a dependency on illuminate/auth, but after upgrading the User class according to the 5.1.11 upgrade guide I have 2 issues:

1. The latest illuminate/contracts does not contain Illuminate\Contracts\Auth\Access\Authorizable
2. The Authorizable trait is in Illuminate\Foundation\Auth\Access\Authorizable. If instead placed in Illuminate\Auth\Access\Authorizable, I don't need to require the entire framework to make my User class valid.

I really would like to use the Access Control features in this latest Laravel version, so simply not including the Authorizable interface and trait are not an option.

**Comment by GrahamCampbell** [comment]
New releases of the illuminate packages haven't happened yet. They'll be happening in due course.

**Comment by winkbrace** [comment]
Does that mean the Authorizable trait will get moved to illuminate/auth?

**Comment by GrahamCampbell** [comment]
No.

**Comment by GrahamCampbell** [comment]
the contracts package is a dependency of the auth package

**Comment by winkbrace** [comment]
I know. I can wait on updates of the packages, no problem.

I just don't think it makes sense that you have to require the entire framework just to use the trait. Especially since the other traits are in the auth package.

```
use Illuminate\Auth\Authenticatable;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
```

**Comment by GrahamCampbell** [comment]
We can't move it now as that would be a breaking change, sorry.

**Comment by winkbrace** [comment]
:'( Okay, too bad. Thanks for the quick responses, tho.
