### ISSUE TITLE
503 can't be overridden in L5.1

### ISSUE THREAD

**Issue by renege** [laravel/framework#10138]
The docs telling to change the ```resources/views/errors/503.blade.php.``` for getting your own Maintenance Mode Response Template, but that doesn't work.

Default page is still shown. Same for the 403. 

It's just an empty html:

```
<!DOCTYPE html>
<html lang="en">
    <head>
      <meta charset="utf-8">
      <title>Be right back</title>

      <meta http-equiv="cleartype" content="on">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">

      <meta name="csrf-token" content="{{ csrf_token() }}">

      <link rel="stylesheet" href="{{ elixir('css/app.css') }}">
    </head>
    <body>
        
          <div class="logo">
              <img src="/img/foobar.png" />
          </div>
          <h2>Text</h2>

    </body>
</html>
```

**Comment by renege** [comment]
@GrahamCampbell why close ? i have the problem with multiple projects, just checked it.

**Comment by GrahamCampbell** [comment]
It's not an issue with laravel, rather, with your usage. Please ask on the forums, and I'm sure someone can help you. :)

**Comment by GrahamCampbell** [comment]
> The docs telling to change the resources/views/errors/503.blade.php. for getting your own Maintenance Mode Response Template, but that doesn't work.

You probably need to modify the maintenance middleware to throw an exception if you want the exception handler to handle that situation.
