### ISSUE TITLE
Laravel validator ignoring unique rule on update model

### ISSUE THREAD

**Issue by ahlechandre** [laravel/framework#10136]
I'm trying to validate an unique e-mail on 2 tables.

Something like:

*Foo* model
```php
$rules = [ 'email': 'required|unique:foo|unique:bar' ];
```

*Bar* model
```php
$rules = [ 'email': 'required|unique:bar|unique:foo' ];
```
Above rules works fine **on creating** the models. The problem is when i need to update it.

**On updating** Laravel Validator ignore the unique rules. For example, if set:

*Bar* || *Foo* model

```php
$rules = [ 'email': 'required|unique:WHATEVER|unique:WHATEVER' ];
```
When save i don't have exceptions or errors and the unique validations rule "works" only on the table of model. (**don't matter if table name is wrong**)

> To make sure, the email columns has unique index on database

**Comment by rkgrep** [comment]
Read the [docs](http://laravel.com/docs/5.1/validation#rule-unique)

You should pass additional parameters for exclusion

`unique:foo,ID_HERE` or `unique:foo,VALUE_HERE,ID_HERE`
