### ISSUE TITLE
[5.1] [Suggestion] Check ability and throw exception

### ISSUE THREAD

**Issue by DarKDinDoN** [laravel/framework#10131]
Hello,

So the new Authorization feature allows us to perform a check. If the method fails Laravel throw a 403. :

```php
$this->authorize('update', $model); // Fail = 403
```

But the user MUST pass a model for this method to work. What if there is no Model to pass ?

```php
public function allUsers()
{
    $this->authorize('manageUsers');
    // If ok, then return a collection of users
    ...
}
```

We could use the check() method from the Gate class, but it is tedious and it doesn't throw a 403 : 
```php
public function allUsers(Gate $gate)
{
    if(! $gate->check('manageUsers'))
    {
        abort(403);
    }
    // If ok, then return a collection of users
    ...
}
```

Can't we add a method in the AuthorizesRequests trait or create a specific helper for this ?

Thanks

**Comment by JosephSilber** [comment]
Fixed: https://github.com/laravel/framework/commit/fae83dac4ce0dbe8b13da2563851be563db3a45b
