### ISSUE TITLE
WithoutOverlapping on scheduled task NOT Working on Windows

### ISSUE THREAD

**Issue by AragornYY** [laravel/framework#10151]
The issue arises from `Illuminate\Console\Scheduling\Event::buildCommand()`:

```php
    ...
    if ($this->withoutOverlapping) {
        $command = '(touch '.$this->mutexPath().'; '.$this->command.'; rm '.$this->mutexPath().') > '.$this->output.' 2>&1 &';
    }
    ...
```

On Windows, using `; ` to separate commands is not working. 

#### Using ` & `

One possible way to fix it is to use ` & ` to separate commands on Windows.

```php
    $cmdSeparator = (strpos(strtoupper(PHP_OS), 'WIN') === 0) ? ' & ' : '; ';

    if ($this->withoutOverlapping) {
        $command = '(touch '.$this->mutexPath().$cmdSeparator.$this->command.$cmdSeparator.'rm '.$this->mutexPath().') > '.$this->output.' 2>&1 &';
```

I'm currently using this way. The drawback is that this requires some external settings to make `touch` and `rm` commands runnable in the Windows environment. 

#### Using `before()` and `after()`
I originally updated `buildCommand()` like the following, so the `touch` and `rm` wouldn't be called:
```php
    ...
    if ($this->withoutOverlapping and strpos(strtoupper(PHP_OS), 'WIN') !== 0) {
        $command = '(touch '.$this->mutexPath().'; '.$this->command.'; rm '.$this->mutexPath().') > '.$this->output.' 2>&1 &';
    }
    ...
```

And also updated the `return` in `withoutOverlapping()` to mimic the `touch` and `rm`:

```php
    return $this->skip(function () {
        return file_exists($this->mutexPath());
    })->before(function () {
        touch($this->mutexPath());
    })->after(function () {
        unlink($this->mutexPath());
    });
```

It works, but not perfect. Ideally, this `touch()` should be the last one in the "before" callbacks queue, and the `unlink()` should be the first one in the "after" callbacks queue. I have no clue how to achieve that. 

I'm thinking how to combine these two approaches, any suggestion?

**Comment by GrahamCampbell** [comment]
I think this was already fixed, if not, we're open to PRs. ;)
