### ISSUE TITLE
[Proposal] PHP Artisan Command to Make Test

### ISSUE THREAD

**Issue by alnutile** [laravel/framework#10152]
So many great artisan commands to make Models, Controllers etc. I would like to make one to make a Test File.

For example 

~~~
php artisan make:test FooTest
~~~

Would make a default file to get going

```php
<?php 

class FooTest extends \TestCase {
 
     use \Illuminate\Foundation\Testing\DatabaseMigrations; 
    
}
```

**Comment by TheKoon** [comment]
:+1:  :smiley:

**Comment by GrahamCampbell** [comment]
We're open to PRs.

**Comment by alnutile** [comment]
Sorry thought I was suppose to write a proposal before I write the code?
More than happy to start the code.
On Sat, Sep 5, 2015 at 1:19 PM Graham Campbell <notifications@github.com>
wrote:

> We're open to PRs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laravel/framework/issues/10152#issuecomment-137978329>
> .
>
-- 
Alfred Nutile
--------------
DevelopersHangout Podcast
http://www.developershangout.io/

https://alfrednutile.info/
