### ISSUE TITLE
[Proposal] Working with foreign URLs

### ISSUE THREAD

**Issue by Lotuashvili** [laravel/framework#10150]
In my application users have to input their portfolio urls, then I have to link them.

The problem is that I can't find helper function that will transform `www.portfolio.com` to valid url like `http://www.portfolio.com/`

`url('www.portfolio.com')` returns `http://mysite.com/www.portfolio.com`.

Hope there will be some fix for that.

**Comment by crynobone** [comment]
You need to include the protocol to send it to external URL.

```php
url('http://www.portfolio.com');
```

**Comment by Lotuashvili** [comment]
You didn't get what I said. I know that with http it will send to external url, but if user wrote link without protocol? I hopd I don't have check it manually...

**Comment by crynobone** [comment]
What stopping you to build this "helper" on your own? I see no reason why Laravel need to include this by default based on that use case.

**Comment by Lotuashvili** [comment]
That's not a problem, but it will be better I think if Laravel will have included this function by default

**Comment by abhimanyusharma003** [comment]
`var_dump(filter_var('www.portfolio.com', FILTER_VALIDATE_URL));` will return false, in your app add `url` validation.
