### ISSUE TITLE
Laravel 5.1: Service Container>Contextual Binding

### ISSUE THREAD

**Issue by tratotui** [laravel/framework#10153]
Good day!
I'm sorry, i have one problem when use bundle 
``` php
$this->app->when(...)->needs->(...)->give(...)
```
I have contract :
``` php
namespace App\Contracts;

interface AdminStatsDataSource {

	/**
	 * Метод возвращает именование поля даты
	 *
	 * @return string
	 */
	public function dateField();

}
```

Have many models with this interfaces(one for example):
``` php
class RevenueReport extends Model implements AdminStatsDataSource {

	protected $table = 'tranzit';

	protected $primaryKey = 'id';

    // ...

	public function dateField()
	{
		return 'pdate';
	}
```

Command :

``` php
namespace App\Commands;

use App\Commands\Command;
use Illuminate\Contracts\Bus\SelfHandling;

use App\Contracts\AdminStatsDataSource as DataSource;

class TestCommand extends Command implements SelfHandling
{
   
    public function __construct()
    {
        //
    }

    public function handle(DataSource $source)
    {
        dd(
           $source->dateField()
        );
    }
}
```

And Service Container:
``` php
namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class AdminStatsProvider extends ServiceProvider
{


    public function register()
    {
        //$this->app->bind('App\Contracts\AdminStatsDataSource', 'App\Models\PModels\Stats\RevenueReport');// <-- it works

        $this->app->when('App\Commands\TestCommand')
                 ->needs('App\Contracts\AdminStatsDataSource')
                 ->give('App\Models\Stats\RevenueReport');
    }
}
```

I have error on page
```php 
Target [App\Contracts\AdminStatsDataSource] is not instantiable.
```
Somebody faced with the same problem?

**Comment by letrunghieu** [comment]
The current contextual binding can only be resolved in the caller **constructor**. You should inject the `App\Contracts\AdminStatsDataSource` dependency into the command constructor instead of the `handle` method. Your command can be rewritten like this:

    namespace App\Commands;

    use App\Commands\Command;
    use Illuminate\Contracts\Bus\SelfHandling;

    use App\Contracts\AdminStatsDataSource as DataSource;

    class TestCommand extends Command implements SelfHandling
    {

        protected $source;

        public function __construct(DataSource $source)
        {
            parent::__construct();
            
            $this->source = $source;
        }

        public function handle()
        {
            dd(
               $this->source->dateField()
            );
        }
    }
