### ISSUE TITLE
@parent totally breaks since 5.1.13

### ISSUE THREAD

**Issue by HazeDevelopment** [laravel/framework#10156]
the @parent function in blade totally breaks since these commits.
I can't figure out why.

I thought I would just give you a heads up.
Everything works fine on 5.1.12.

**Comment by GrahamCampbell** [comment]
Can you paste your code please/

**Comment by chilion** [comment]
indeed some m***f** issue here.

**Comment by GrahamCampbell** [comment]
If you're not hardcoding parent into blade files, then that explains why. We've stopped allowing dynamic use of parent for security reasons.

**Comment by HazeDevelopment** [comment]
@extends('shop.checkout.template.base')

@section('javascripts')
    @parent
    {!! HTML::script('js/tipped.js') !!}
    {!! HTML::script('js/select2.min.js') !!}
    {!! HTML::script('js/shop/checkout/index.js') !!}
    {!! HTML::script('js/shop/checkout/selectInput.js') !!}
    {!! HTML::script('js/moment-with-locales.js') !!}
    {!! HTML::script('js/picker/picker.js') !!}
    {!! HTML::script('js/picker/picker.date.js') !!}
    {!! HTML::script('js/picker/translations/nl_NL.js') !!}
    
    <script type="text/javascript">
        data = $.parseJSON('{!! json_encode($dates) !!}');

        function updateSelects(date)
        {
            $("select[name='deliver_time']").find('option').remove();
            first = false;
            $.each(data[date], function(key, times)
            {
                if(first == false)
                {
                    first = times.start;
                }

                start = times.start.split(":");
                end = times.end.split(":");

                inputField = $.el('option', {'value' : times.start}).html("Tussen " + start[0] + "." + start[1]  + " & " + end[0] + "." + end[1]);
                $("select[name='deliver_time']").append(inputField);
            });

            $("select[name='deliver_time']").val(first).trigger("change");
        }

        $(function(){
            enabledDates = [true];

            firstSet = false;
            $.each(data, function(date, steps){
                if(firstSet == false)
                {
                    updateSelects(date);
                    firstSet = true;
                }

                splitted = date.split('-');
                enabledDates.push([splitted[0], (splitted[1]-1), splitted[2]]);
            });

            $input = $("input[name='deliver_date']").pickadate({
              disable: enabledDates,
              formatSubmit: 'yyyy-mm-dd',
              clear: false,
              close: false,
              onSet: function(context)
              {
                value = $("input[name='deliver_date_submit']").val();
                updateSelects(value);
              }
            });


            var picker = $input.pickadate('picker')
            keys = Object.keys(data);
            keys = keys[0].split('-');
            picker.set('select', [keys[0], (keys[1]-1), keys[2]]);
        });
    </script>
@endsection

@section('style')  
    @parent

    {!! HTML::style('css/tipped.css') !!}
    {!! HTML::style('css/picker/classic.css') !!}
    {!! HTML::style('css/picker/classic.date.css') !!}
@endsection

@section('content')

    <div class="container">
        <div class="steps">
            <div class="part deliver done">Gegevens</div>
            <div class="part spacer"><div class="spacer"></div></div>
            <div class="part payment">Betalen</div>
            <div class="part spacer"><div class="spacer"></div></div>
            <div class="part success">Voltooid</div>
        </div>
        <div class="content">
            <form method="post" action="{{ route('getPayment') }}" class="order_form">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                @include('shop.checkout.components.bags')
                <div class="row centerize">
                </div>


                <div class="row centerize">
                    <div class="col-s-12 col-md-4"><h1>Bezorgdatum</h1></div>
                    <div class="col-s-12 col-md-8" id="deliver_date_div">
                        <input type="text" name="deliver_date" placeholder="Selecteer een datum" />
                    </div>
                </div>

                <div class="row centerize">
                    <div class="col-s-12 col-md-4"><h1>Bezorgtijd</h1></div>
                    <div class="col-s-12 col-md-8" id="deliver_time_div">
                        <select id="deliver_time" name="deliver_time" class="custom" style="width:100%"></select>
                    </div>
                </div>

                @if($mobile == false)
                    <div class="row centerize">
                        <div class="col-s-12 col-md-4"><h1>Telefoon</h1></div>
                        <div class="col-s-12 col-md-8">
                            <input type="text" placeholder="Zodat we je kunnen bereiken" name="mobile_number">
                        </div>
                    </div>
                @endif
                <div class="row centerize">
                    <div class="col-s-12 col-md-4"><h1>Opmerking</h1></div>
                    <div class="col-s-12 col-md-8"><textarea name="comments" placeholder="Wij zitten op de tweede verdieping"></textarea></div>
                    <div class="footer">
                        <div class="back"><a href="{{ URL::to("winkelen/".$store)}}"><i class="fa fa-angle-left"></i> Terug</a></div>
                        <div class="next"><button class="button button_purple verder disabled" title="U moet een adres en bezorgtijd selecteren om verder te gaan.">Verder <div class="icon"><i class="fa fa-angle-right"></i></div></button></div>
                    </div>
            </form>
        </div>
    </div>

@endsection


@include('shop.checkout.components.addAddress')

**Comment by GrahamCampbell** [comment]
Ohh, I see. You need to clear your compiled views.

**Comment by chilion** [comment]
@GrahamCampbell care to elaborate?

**Comment by GrahamCampbell** [comment]
Go in your storage folder and delete your compiled views. What's not clear about that?

**Comment by chilion** [comment]
Problem is, im not a complete idiot and tried that already. It didn't work.

**Comment by GrahamCampbell** [comment]
What does your compiled file look like please

**Comment by HazeDevelopment** [comment]
You want them all or just the one of the particulair code I send?

**Comment by HazeDevelopment** [comment]
with all I mean with just loading that one particular page, it generated a bunch

**Comment by GrahamCampbell** [comment]
Just one for any file containing a `@parent` please.

**Comment by HazeDevelopment** [comment]
<?php $__env->startSection('javascripts'); ?>
    <?php $__env->appendParent(); ?>
    <?php echo HTML::script('js/tipped.js'); ?>

    <?php echo HTML::script('js/select2.min.js'); ?>

    <?php echo HTML::script('js/shop/checkout/index.js'); ?>

    <?php echo HTML::script('js/shop/checkout/selectInput.js'); ?>

    <?php echo HTML::script('js/moment-with-locales.js'); ?>

    <?php echo HTML::script('js/picker/picker.js'); ?>

    <?php echo HTML::script('js/picker/picker.date.js'); ?>

    <?php echo HTML::script('js/picker/translations/nl_NL.js'); ?>

    
    <script type="text/javascript">
        data = $.parseJSON('<?php echo json_encode($dates); ?>');

        function updateSelects(date)
        {
            $("select[name='deliver_time']").find('option').remove();
            first = false;
            $.each(data[date], function(key, times)
            {
                if(first == false)
                {
                    first = times.start;
                }

                start = times.start.split(":");
                end = times.end.split(":");

                inputField = $.el('option', {'value' : times.start}).html("Tussen " + start[0] + "." + start[1]  + " & " + end[0] + "." + end[1]);
                $("select[name='deliver_time']").append(inputField);
            });

            $("select[name='deliver_time']").val(first).trigger("change");
        }

        $(function(){
            enabledDates = [true];

            firstSet = false;
            $.each(data, function(date, steps){
                if(firstSet == false)
                {
                    updateSelects(date);
                    firstSet = true;
                }

                splitted = date.split('-');
                enabledDates.push([splitted[0], (splitted[1]-1), splitted[2]]);
            });

            $input = $("input[name='deliver_date']").pickadate({
              disable: enabledDates,
              formatSubmit: 'yyyy-mm-dd',
              clear: false,
              close: false,
              onSet: function(context)
              {
                value = $("input[name='deliver_date_submit']").val();
                updateSelects(value);
              }
            });


            var picker = $input.pickadate('picker')
            keys = Object.keys(data);
            keys = keys[0].split('-');
            picker.set('select', [keys[0], (keys[1]-1), keys[2]]);
        });
    </script>
<?php $__env->stopSection(); ?>

<?php $__env->startSection('style'); ?>  
    <?php $__env->appendParent(); ?>

    <?php echo HTML::style('css/tipped.css'); ?>

    <?php echo HTML::style('css/picker/classic.css'); ?>

    <?php echo HTML::style('css/picker/classic.date.css'); ?>

<?php $__env->stopSection(); ?>

<?php $__env->startSection('content'); ?>

    <div class="container">
        <div class="steps">
            <div class="part deliver done">Gegevens</div>
            <div class="part spacer"><div class="spacer"></div></div>
            <div class="part payment">Betalen</div>
            <div class="part spacer"><div class="spacer"></div></div>
            <div class="part success">Voltooid</div>
        </div>
        <div class="content">
            <form method="post" action="<?php echo e(route('getPayment')); ?>" class="order_form">
                <input type="hidden" name="_token" value="<?php echo e(csrf_token()); ?>">
                <?php echo $__env->make('shop.checkout.components.bags', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>
                <div class="row centerize">
                </div>


                <div class="row centerize">
                    <div class="col-s-12 col-md-4"><h1>Bezorgdatum</h1></div>
                    <div class="col-s-12 col-md-8" id="deliver_date_div">
                        <input type="text" name="deliver_date" placeholder="Selecteer een datum" />
                    </div>
                </div>

                <div class="row centerize">
                    <div class="col-s-12 col-md-4"><h1>Bezorgtijd</h1></div>
                    <div class="col-s-12 col-md-8" id="deliver_time_div">
                        <select id="deliver_time" name="deliver_time" class="custom" style="width:100%"></select>
                    </div>
                </div>

                <?php if($mobile == false): ?>
                    <div class="row centerize">
                        <div class="col-s-12 col-md-4"><h1>Telefoon</h1></div>
                        <div class="col-s-12 col-md-8">
                            <input type="text" placeholder="Zodat we je kunnen bereiken" name="mobile_number">
                        </div>
                    </div>
                <?php endif; ?>
                <div class="row centerize">
                    <div class="col-s-12 col-md-4"><h1>Opmerking</h1></div>
                    <div class="col-s-12 col-md-8"><textarea name="comments" placeholder="Wij zitten op de tweede verdieping"></textarea></div>
                    <div class="footer">
                        <div class="back"><a href="<?php echo e(URL::to("winkelen/".$store)); ?>"><i class="fa fa-angle-left"></i> Terug</a></div>
                        <div class="next"><button class="button button_purple verder disabled" title="U moet een adres en bezorgtijd selecteren om verder te gaan.">Verder <div class="icon"><i class="fa fa-angle-right"></i></div></button></div>
                    </div>
            </form>
        </div>
    </div>

<?php $__env->stopSection(); ?>


<?php echo $__env->make('shop.checkout.components.addAddress', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>

<?php echo $__env->make('shop.checkout.template.base', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>

**Comment by HazeDevelopment** [comment]
that's the particular one I send you earlier where the problem occurs.

**Comment by GrahamCampbell** [comment]
Hmm, ok, this is somewhat unexpected. Ping @taylorotwell.

**Comment by HazeDevelopment** [comment]
Thought so.

**Comment by taylorotwell** [comment]
We'll have to revert the change.

**Comment by chilion** [comment]
Please keep us posted :-)

**Comment by chilion** [comment]
I see it is fixed! Tnx,

https://github.com/laravel/framework/commit/e34dcc0c57e0f560248aec5128161256ff8bf4e1

**Comment by taylorotwell** [comment]
Yes. Reverted.

**Comment by abhimanyusharma003** [comment]
@taylorotwell revert fix this issue, but #10068 is back, I hope you can look into this.
