### ISSUE TITLE
getMorphClass() ignores $morphClass attributes

### ISSUE THREAD

**Issue by a-komarev** [laravel/framework#10167]
Related to: #9891 

I'm not sure is this critical or not but if `$morphMap` is assigned - `$this->getMorphClass()` will ignore manually assigned `$morphClass` attributes (always return false), even in case when morph key is not found in `$morphMap`.

**Comment by tomschlick** [comment]
Can you give us a quick snippet of code to demonstrate this? My weekend brain can't visualize that very well...

**Comment by a-komarev** [comment]
**AppServiceProvider.php**

```php
<?php namespace App\Providers;

use Illuminate\Database\Eloquent\Relations\Relation;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider {
	public function boot()
	{
		Relation::morphMap([
			'page' => \App\Page::class,
		]);
	}
}
```

**Page.php**

```php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Page extends Model
{
    public function test()
    {
        return $this->getMorphClass();
    }
}
```

**Content.php**

```php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Content extends Model
{
    protected $morphClass = 'content';

    public function test()
    {
        return $this->getMorphClass();
    }
}
```

`Page->test()` will return `page` when `Content->test()` will return `false`.

**Comment by phroggyy** [comment]
I'll look into this tonight or tomorrow
