### ISSUE TITLE
removeLeadingBoolean does not remove upper case AND/OR

### ISSUE THREAD

**Issue by timgws** [laravel/framework#10173]
Using the following code:

        $builder->where('tim', '=', 'bob', 'AND');
        $statement = $builder->toSql();

`$statement` will build something similar to:

      select * where AND `tim` = ?

expected:

     select * where `tim` = ?

A simple fix might just be to add a case insensitive flag to `removeLeadingBoolean` in `Illuminate\Database\Query\Grammars\Grammar`

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell.

**Comment by phroggyy** [comment]
@timgws is there any scenario in which you would need to distinguish between case? Just thinking if it needs to be a flag or if we could just rewrite it with a `strtolower`

**Comment by timgws** [comment]
@phroggyy not that I know of. I don't think there is any database that is case sensitive for the conditions. Changing all of the operators/booleans with `strtolower` was my first thought, but there are so many functions that would need to be changed. This is why I thought changing the regular expression in `removeLeadingBoolean` might be better, as less code would need to be updated.

**Comment by phroggyy** [comment]
@timgws I just solved this using a simple `strtolower` in `removeLeadingBoolean`, do you see any flaws in this?
