### ISSUE TITLE
event:generate: wrong EventServiceProvider used to generate Events/Listeners

### ISSUE THREAD

**Issue by sirvantos** [laravel/framework#10172]
I have found strange issue.

I use https://github.com/prettus/laravel-repository in my project, laravel-repository contains class EventServiceProvider which extends parent class Illuminate\Foundation\Support\Providers\EventServiceProvider

and now when i run command event:generate, laravel generates events/listeners from Prettus\Repository\Providers\EventServiceProvider (not from my class App\Providers\EventServiceProvider).

the reason there

EventGenerateCommand

it uses method laravel->getProvider('Illuminate\Foundation\Support\Providers\EventServiceProvider') which returns first class which extended 'Illuminate\Foundation\Support\Providers\EventServiceProvider'.

in my case it is: Prettus\Repository\Providers\EventServiceProvider but  it should return: App\Providers\EventServiceProvider

It iooks like it is a bug :( no?

**Comment by jobrios** [comment]
Your link points to [`andersao/laravel-repository`](https://github.com/andersao/laravel-repository), an abandoned repo that suggests installing [`andersao/l5-repository`](https://github.com/andersao/l5-repository) instead. (Composer complained when I tried installing `andersao/laravel-repository`.)

After requiring `andersao/l5-repository` on Laravel 5.1.16 and adding `Prettus\Repository\Providers\RepositoryServiceProvider::class` to `config/app.php`, I ran `artisan event:generate`, which generated the `SomeEvent` and `EventListener` pair that comes pre-entered in a fresh install's `App\Providers\EventServiceProvider`. Then I went into `artisan tinker` and entered

```
$esp = App::getProvider('Illuminate\Foundation\Support\Providers\EventServiceProvider')
$esp->listens()
```

The output showed that I'd retrieved an `App\Providers\EventServiceProvider` instance, not `Prettus\Repository\Providers\EventServiceProvider`.

```
=> App\Providers\EventServiceProvider
=> [
     "App\Events\SomeEvent" => [
       "App\Listeners\EventListener",
     ],
   ]
```

Could something else be causing the problem? Are you able to install `andersao/l5-repository`?

**Comment by sirvantos** [comment]
Hi.

Thank you for answer!

DId you add provider 'Prettus\Repository\Providers\RepositoryServiceProvider::class' to your config/app.php before ?

> Could something else be causing the problem? Are you able to install andersao/l5-repository?

my composer.json require section

"require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1.*",
        "prettus/l5-repository": "~2.1"
    },

My tinker console:

Psy Shell v0.5.2 (PHP 5.5.19 тАФ cli) by Justin Hileman
>>> $esp = App::getProvider('Illuminate\Foundation\Support\Providers\EventServiceProvider');
=> Prettus\Repository\Providers\EventServiceProvider {#99}
>>> $esp->listens()
=> [
     "Prettus\Repository\Events\RepositoryEntityCreated" => [
       "Prettus\Repository\Listeners\CleanCacheRepository",
     ],
     "Prettus\Repository\Events\RepositoryEntityUpdated" => [
       "Prettus\Repository\Listeners\CleanCacheRepository",
     ],
     "Prettus\Repository\Events\RepositoryEntityDeleted" => [
       "Prettus\Repository\Listeners\CleanCacheRepository",
     ],
   ]
>>>

**Comment by jobrios** [comment]
Same composer require section as you (except I also have [laravel-ide-helper](https://github.com/barryvdh/laravel-ide-helper)). I acted in this order: Composer update > append `Prettus\Repository\Providers\RepositoryServiceProvider::class` to `app/config.php` `providers` array > run `artisan event:generate` > run `artisan tinker`.

**Comment by sirvantos** [comment]
strange.

what laravel/php version do you have ?

**Comment by GrahamCampbell** [comment]
Please continue on the forums.
