### ISSUE TITLE
"php artisan make:console ..." generates incorrect code.

### ISSUE THREAD

**Issue by beningreenjam** [laravel/framework#10175]
Generates:
`namespace App\Commands;`
`use App\Commands\Command;`

Should be:
`namespace App\Console\Commands;`
`use Illuminate\Console\Command;`

Also shouldn't include a `__construct` method.

**CORRECTION**

Should be:
`namespace App\Commands;`
`use Illuminate\Console\Command;`

 Should include a __construct method which calls the parent constructor.

Also should not implement the SelfHandling class.

**Comment by GrahamCampbell** [comment]
This does that because it assumes you have a base command. Maybe we need to try to detect if that class exists first?

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell. Would you accept a pull to check if that class exists and use if it does? I'd be happy to write that - should be pretty trivial. ;)

**Comment by arrilot** [comment]
There is no way this can happen.

Here is the stub that this command uses https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Console/stubs/console.stub

**Comment by GrahamCampbell** [comment]
Please make sure you're using the latest version of Laravel.
