### ISSUE TITLE
Scheduler :: on a multi server setup

### ISSUE THREAD

**Issue by ryanhungate** [laravel/framework#10176]
Just wanted to know the proper way to handle a multi server scheduler setup, where cron jobs would be split up on a per server basis?  I'm sure it's something really easy to configure, but it's just not standing out to me just yet...  i'm assuming that there would be a flag to use so that the Kernel class would only load certain jobs at runtime?  Is this not supported, or am I blind?  Hoping it's that i'm blind... Or does anyone have a suggestion on this one?

**Comment by GrahamCampbell** [comment]
Please ask on the forums.

**Comment by ryanhungate** [comment]
Well I will do that if its not a relevant question here but I'm seeing this more as a package related question for the Scheduler.  I can't imagine I'm the only one that would want to limit cron jobs per server.  It's such a helpful addition to the framework and I feel it's missing a 

        php artisan schedule:run my_flag_name 

To get an argument in the class to switch function loading per server would be great... If I'm off base here I apologize in advance.
