### ISSUE TITLE
Group Namespace doesn't work well for Route::Controller

### ISSUE THREAD

**Issue by drtzack** [laravel/framework#10185]
Here is my code

	Route::group(['prefix' => 'api', 'namespace' => 'Modules\User\Http\Controllers'], function () {
		Route::controller('auth', 'AuthController');
		Route::resource('user', 'UserController');
	});

Group Namespace works fine for resource but doesn't work for controller. It prepends current namespace.

Class App\Http\Controllers\Modules\User\Http\Controllers\AuthController does not exist

It should see as Modules\User\Http\Controllers\AuthController but It doesn't.

**Comment by busayo** [comment]
Apppend a '\' before `Modules\User\Http\Controllers` to exit the current namespace
