### ISSUE TITLE
Illuminate\Console\Scheduling\Schedule::command() Should Enclose PHP_BINARY in Double Quotes if it Contains Spaces

### ISSUE THREAD

**Issue by voidstate** [laravel/framework#10187]
It is common on Windows to have spaces in file paths, for example when PHP is installed via Microsoft's Web Platform Installer, it is found at `C:\Program Files (x86)\PHP\v5.6\php.exe`.

Using `$schedule->command` in the console kernal fails in this case. But if the path is enclosed in double quotes, it does not fail.

Changing `laravel\framework\src\Illuminate\Console\Scheduling\Schedule.php` (line 45) to this allows scheduled tasks to run on Windows:

`return $this->exec('"'.PHP_BINARY.'" "'.$artisan.'" '.$command, $parameters);`

**Comment by GrahamCampbell** [comment]
I really tried to have that done but Taylor rejected the idea of correctly escaping the path.

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell. This was quite a long time ago, and to be fair, my PR did do some other stuff too, which was probably the underly reason.
