### ISSUE TITLE
Request::has() on empty get string

### ISSUE THREAD

**Issue by sciasfreelancer** [laravel/framework#10189]
URL: http://localhost/?admin

Templates/welcome.blade.php
{{dd(Request::has('admin'), Request::input())}}

prints:
false

array:3 [▼
  "admin" => ""
]

URL: http://localhost/
prints:
false

array:0 [▼
]

Problem: Laravel does not recognize empty $_GET strings.

Documentation "To determine if a value is present on the request, you may use the has method. The has method returns true if the value is present and is not an empty string:".
But what about empty string $_GET ? Usually doing isset($_GET['something']) is enough, but in laravel ?

**Comment by GrahamCampbell** [comment]
This is intentional, sorry.

**Comment by sciasfreelancer** [comment]
y r srs
