### ISSUE TITLE
[NFR] Adding `nullable(false)` and/or `notNullable()` methods

### ISSUE THREAD

**Issue by salarmehr** [laravel/framework#10181]
Currently, it seems there is no command to undo `nullable()` method. A function to prevent null value (not nullable) is really necessary. e.i.  `nullable(false)` and/or `notNullable()`

**Comment by jobrios** [comment]
You *can* use `nullable(false)` already.

**Comment by AlexRadch** [comment]
Can you add in documentation about nullable(false) ?
