### ISSUE TITLE
[5.1] Testing “failed” requests

### ISSUE THREAD

**Issue by wayneashleyberry** [laravel/framework#10202]
I'm not sure where this problem comes from, if it's PHPUnit, the web crawler, Symfony or Laravel. There also might be a better way of testing this kind of thing - if someone could point me to it that would be great!

That said, here's what I'm trying to achieve:

I have a route which for whatever reason is unauthorized:

```php
Route::get('/test', function () {
    abort(403);
});
```

I have the following test to make sure it is indeed inaccessible:

```php
/**
 * You shall not pass!
 *
 * @expectedException Symfony\Component\HttpKernel\Exception\HttpException
 */
public function testUnauthorizedRoute()
{
    $this->visit('/test');
}
```

However, when I run phpunit, the exception is not caught as per the `@expectedException` annotation... I get the following error message instead:

```
There was 1 failure:

1) ExampleTest::testUnauthorizedRoute
A request to [http://localhost/test] failed. Received status code [403].

/Users/Wayne/source/laravel-test/vendor/laravel/framework/src/Illuminate/Foundation/Testing/CrawlerTrait.php:259
/Users/Wayne/source/laravel-test/vendor/laravel/framework/src/Illuminate/Foundation/Testing/CrawlerTrait.php:177
/Users/Wayne/source/laravel-test/vendor/laravel/framework/src/Illuminate/Foundation/Testing/CrawlerTrait.php:59
/Users/Wayne/source/laravel-test/tests/ExampleTest.php:12
phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:176
phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:129

Caused by
exception 'Symfony\Component\HttpKernel\Exception\HttpException' in /Users/Wayne/source/laravel-test/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:882
```

---

I do currently have a workaround, the actual exception thrown is an instance of `PHPUnit_Framework_ExpectationFailedException`, so I just catch it and check the message:

```php
try {
    $this->visit('/test');
} catch (\Exception $err) {
    $this->assertContains('Received status code [403]', $err->getMessage());
}
```

---

For posterity's sake, I've created a test repo over at https://github.com/wayneashleyberry/laravel-test

You can replicate this issue by following these commands:

```sh
git clone git@github.com:wayneashleyberry/laravel-test.git
cd laravel-test
cp .env.example .env
composer install
php artisan key:generate
vendor/bin/phpunit
```

**Comment by wayneashleyberry** [comment]
In these simplified examples I realise custom http requests would work, as follows:

```php
$response = $this->call('GET', '/test');

$this->assertEquals(403, $response->status());
```

But I need the crawler to fill out forms, here's my real world test:

```php
try {
    $this->visit('/auth/login')
        ->type($user['email'], 'email')
        ->type($user['password'], 'password')
        ->press('Sign in');
} catch (\Exception $err) {
    $this->assertContains('Received status code [403]', $err->getMessage());
}

```

**Comment by GrahamCampbell** [comment]
Better for you to NOT use visit if you want to catch the http exception. I disagree that the solution provided by @wayneashleyberry is a good one.

**Comment by wayneashleyberry** [comment]
Do you have a better solution @GrahamCampbell?

**Comment by GrahamCampbell** [comment]
Yes, there are other methods other than visit that do throw the http exception, as I said. Use them.

**Comment by wayneashleyberry** [comment]
Would you mind telling me what those methods are? I can'd find anything in the docs other than doing custom http requests.

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Testing/CrawlerTrait.php

**Comment by wayneashleyberry** [comment]
`seeStatusCode` returns the same error...

```php
        $this->visit('/auth/login')
            ->type($user['email'], 'email')
            ->type($user['password'], 'password')
            ->press('Sign in')
            ->seeStatusCode(403);
```

```
There was 1 failure:

1) AuthTest::testUnauthorizedLogin
A request to [http://testing.lvh.me/auth/login] failed. Received status code [403].
```

**Comment by GrahamCampbell** [comment]
You CAN NOT use the visit method if you want to catch the http exception, because the visit method throws straight away.

**Comment by wayneashleyberry** [comment]
So is this basically not possible?

**Comment by crynobone** [comment]
How could you possibly be typing email or password when the server already return 403? Does it still return the form when you visit it using a browser?

**Comment by wayneashleyberry** [comment]
@crynobone `/auth/login` returns a `200`

I want to test a user filling out the login form, submitting it and getting a `403` in response.

**Comment by wayneashleyberry** [comment]
I'm struggling to get `$this->call('POST', '/auth/login', $user);` to work because of the CSRF protection.

**Comment by GrahamCampbell** [comment]
Please ask on the forums.

**Comment by crynobone** [comment]
```php
/**
     * You shall not pass!
     *
     * @expectedException PHPUnit_Framework_ExpectationFailedException
     * @expectedMessage Received status code [403]
     */
    public function testUnauthorizedRoute()
    {
        $this->visit('/test');
    }
```

This being handled via CrawlerTrait itself, <https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Testing/CrawlerTrait.php#L250>, called from `makeRequest`.

**Comment by wayneashleyberry** [comment]
I might end up doing that, thanks @crynobone
