### ISSUE TITLE
Upgrade guide to 5.1 doesn't contain relevant info on ModelFactory

### ISSUE THREAD

**Issue by JonoB** [laravel/framework#10209]
I believe that model factories were introduced in 5.1.

http://laravel.com/docs/5.1/testing#model-factories:

> To get started, take a look at the database/factories/ModelFactory.php file in your application. 

My app, which was originally built on 5.0 and then upgraded to 5.1 does not contain this file and there is no mention made in the docs (http://laravel.com/docs/master/upgrade#upgrade-5.1.0).

**Comment by GrahamCampbell** [comment]
That's because you don't have to do anything to upgrade.
