### ISSUE TITLE
Strange console command behaivor 

### ISSUE THREAD

**Issue by Borkache** [laravel/framework#10205]
I've created 2 separate console command . Into one of them I injected model , and this command works good, just php artisan and the other command was broken by core exception. 

Code examples here below : 
CheckerCommand
The main problem appears when I'm trying to add Model in any style directly into construct, by the "new", by the App::make, no difference.

use App\Models\PlatformAccount;

public function __construct(
        CommandQueueManager $commandQueue,
        Mt4User $userModel,
        PlatformAccount $platformAccountModel
    )
    {
        parent::__construct();

        $this->commandQueue = $commandQueue;
        $this->userModel = $userModel;
        $this->sendGrid = \App::make('SendGrid');
        $this->platformAccountModel = $platformAccountModel;

    }

the second command which will be broken by first one's does not have this Model at all
UserCreator
    public function __construct()
    {
        parent::__construct();

        $this->sendGrid = \App::make('SendGrid');
        $this->faker = Faker::create();
    }

the main strange thing is that you use PlatformAccount Model inside 
public function handle() , there is no error.

Kernel code

	protected $commands = [
                'App\Console\Commands\WebApiChecker',
		'App\Console\Commands\CreateUser',
		
	];

just added model into Checker constructor 
 public function __construct(
        PlatformAccount $platformAccount
    )

and received this 

Error message

PHP Fatal error:  Cannot use Illuminate\Database\Eloquent\Model as Model because the name is already in use in /var/www/lava/app/Models/User.php on line 6
PHP Stack trace:
PHP   1. {main}() /var/www/lava/artisan:0
PHP   2. Illuminate\Foundation\Console\Kernel->handle() /var/www/lava/artisan:36
PHP   3. Symfony\Component\Console\Application->run() /var/www/lava/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:100
PHP   4. Symfony\Component\Console\Application->doRun() /var/www/lava/vendor/symfony/console/Application.php:126
PHP   5. Symfony\Component\Console\Application->doRunCommand() /var/www/lava/vendor/symfony/console/Application.php:195
PHP   6. Illuminate\Console\Command->run() /var/www/lava/vendor/symfony/console/Application.php:878
PHP   7. Symfony\Component\Console\Command\Command->run() /var/www/lava/vendor/laravel/framework/src/Illuminate/Console/Command.php:136
PHP   8. Illuminate\Console\Command->execute() /var/www/lava/vendor/symfony/console/Command/Command.php:259
PHP   9. Illuminate\Container\Container->call() /var/www/lava/vendor/laravel/framework/src/Illuminate/Console/Command.php:150
PHP  10. call_user_func_array:{/var/www/lava/vendor/laravel/framework/src/Illuminate/Container/Container.php:502}() /var/www/lava/vendor/laravel/framework/src/Illuminate/Container/Container.php:502
PHP  11. App\Console\Commands\CreateUser->handle() /var/www/lava/vendor/laravel/framework/src/Illuminate/Container/Container.php:502
PHP  12. spl_autoload_call() /var/www/lava/vendor/laravel/framework/src/Illuminate/Container/Container.php:73
PHP  13. Composer\Autoload\ClassLoader->loadClass() /var/www/lava/vendor/laravel/framework/src/Illuminate/Container/Container.php:73
PHP  14. Composer\Autoload\includeFile() /var/www/lava/vendor/composer/ClassLoader.php:301

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Cannot use Illuminate\Database\Eloquent\Model as Model because the name is
  already in use

**Comment by crynobone** [comment]
Check your error. This has nothing to do with console.

```
PHP Fatal error: Cannot use Illuminate\Database\Eloquent\Model as Model because the name is already in use in /var/www/lava/app/Models/User.php on line 6
```

**Comment by Borkache** [comment]
the main thing that if I will comment PlatformModel in constructor the error will go out, User Model is a standard one, which comes with laravel and not in usage inside Console at all. 
Also in non-console part I have not ever received this error.
