### ISSUE TITLE
[L5.1] DB::transaction() does not trigger a reconnection

### ISSUE THREAD

**Issue by rikh42** [laravel/framework#10204]
When a new db transaction is started with DB::transaction(), and the PDO connection has timed out, DB::reconnect() is not automatically called.

The first SQL statement inside the transaction does trigger a reconnection, which attempts to set the PDO object to NULL in the middle of the transaction. You can not change the PDO driver mid transaction, so this throws an exception that is not handled.

Suggest that starting a transaction should attempt to ensure the connection is still alive, and reconnect automatically, prior to starting the transaction.

**Comment by ArjanSchouten** [comment]
Same issue https://github.com/laravel/framework/issues/10146 with closed PR https://github.com/laravel/framework/pull/10158
