### ISSUE TITLE
Auth::check() returns false on RouteServiceProvider even when logged in

### ISSUE THREAD

**Issue by geocine** [laravel/framework#10211]
I have replicated this issue on a fresh Laravel project using **5.1.16** . 

https://github.com/geocine/l5-routserviceprovider-issue

Because of this ``Auth::user()`` is null and I cannot get a ``User`` object

I believe that this has been working on previous versions of Laravel. I have seen it being used on different repositories here on Github.

- https://github.com/ElasticOrange/tarot/blob/c96fa55078f11ec380f837ede2162ed8b74aa705/app/Providers/RouteServiceProvider.php

- https://github.com/nguyentrongbang/api.oceanbeauty.com.vn/blob/8997caf494485023b396899d1a46de62beebf1b7/app/Providers/RouteServiceProvider.php

- https://github.com/tightenco/symposium/blob/cbf6635f2195c62ff7c001bc7650b914ceef77e6/app/Providers/RouteServiceProvider.php

**Comment by letrunghieu** [comment]
In those repositories, the `Auth::user()` is not **called** inside the `boot` method of the `RouteServiceProvider`. It's used in a closure that will be called later in the application.

**Comment by geocine** [comment]
@letrunghieu right I figured out . I don't know where to ask probably you could take a look at my post on StackOverflow if you have time. I am trying to pass a different middleware and namespace parameter to a route group based on a users role. But I couldn't access the users role from those files.  I would like to use the same routes but would be mapped to a different controller based on the users role . I hope that makes sense. Here is what I am trying to accomplish:
http://stackoverflow.com/questions/32487350/couldnt-access-auth-from-routeserviceprovider-or-routes-php-file
