### ISSUE TITLE
Please make all Blade functions available as normal PHP functions in pure PHP views. 

### ISSUE THREAD

**Issue by salarmehr** [laravel/framework#10215]
When for some reason its not possible or desired to use Blade syntax, I should be yey possible to structure view hierarchy without using blade. It sees currently there is no pure php counterparts of blade directives (i,e @section, @extend , etc)? PHP counterpart function of Blade directive is really necessary,  something similar to `<?php extend('foo') ?>`

In Phalcon framework, while it has its own template engine (Volt) all of its template engine capability is also available in pure PHP syntax.

**Comment by GrahamCampbell** [comment]
If you want to use normal functions, that's fine, just look at what it gets compiled to, and use that.

**Comment by salarmehr** [comment]
@GrahamCampbell How fast you close the issue!

The compiled code is totally ugly and verbose. I mean some clean method. Here is an example of compiled code:
~~~~~
<?php $__env->startSection('content'); ?>
asdasd
<?php $__env->stopSection(); ?>
<?php echo $__env->make('temp.template', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>

**Comment by franzliedke** [comment]
Good idea, @salarmehr. :+1:

**Comment by GrahamCampbell** [comment]
I don't think there are any plans to do this. Just use blade.

**Comment by crynobone** [comment]
Would it be possible?

```php
@extends('temp.template')

@section('content')
Just a test
@stop
```

Would actually echo as.

```php
<?php $__env->startSection('content'); ?>
Just a test
<?php $__env->stopSection(); ?>
<?php echo $__env->make('temp.template', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>
```

Unless you want to make blade parse normal PHP, but that would be redundant.

**Comment by franzliedke** [comment]
Can we at least get @taylorotwell's opinion?

**Comment by salarmehr** [comment]
@crynobone I'm don't get you comment point. Why do you think blade need to compile the PHP?! 

The PHP view of you blade code should be as: 

~~~~
<?php extends('temp.template'); ?>

<?php section('content');?>
Just a tes
<?php stop();>

**Comment by salarmehr** [comment]
@GrahamCampbell  "Just use blade."!!! The developer should be allowed to use his desired syntax. Using Blase syntax should not be an obligation. Almost all frameworks let user to choose his view template engine. 

For example when when a project's views are already wrote  in another framework and they decide to migrate some part to Laravel the possibility to use the same template engine is really helpful.

**Comment by GrahamCampbell** [comment]
> Can we at least get @taylorotwell's opinion?

Sure, ask him on larachat. Please don't create issues if you want Taylor to review them. You need to contact him directly if you want his opinion.

**Comment by GrahamCampbell** [comment]
> @GrahamCampbell "Just use blade."!!! The developer should be allowed to use his desired syntax. Using Blase syntax should not be an obligation. Almost all frameworks let user to choose his view template engine.

Blade is PHP. You can use it just like a PHP file.

**Comment by salarmehr** [comment]
Please reopen the issue and add a suitable label e.g. [under discussion]

**Comment by taylorotwell** [comment]
If you want that functionality maybe just pull in Plates via Composer?

**Comment by crynobone** [comment]
> I didn't get your comment point. Why do you think blade need to compile the PHP pure code?!

If we use.

```php
<?php extends('temp.template'); ?>
```

1. How would the layout fetch the defined variable? Does adding `get_defined_vars()` in `extends()` provide the available variables as when using blade?
2. How would PHP collect the section when calling `extends()` already echo out the template. PHP works from top to bottom. How do you think we can make it possible to deferred the echo up until the end of file (just like how blade compile it to)?

**Comment by salarmehr** [comment]
@crynobone It is technically possible using buffering or …

**Comment by crynobone** [comment]
> It is technically possible using buffering or …

While maintaining single set of library as Blade, or a completely different code for handling PHP based template?

**Comment by salarmehr** [comment]
@taylorotwell some simple expansion can bring such feature to Laravel. While Plates is also awesome, having such capability in Laravel is really preferred.

**Comment by briedis** [comment]
@salarmehr You should check out what Taylor suggested - Plates (http://platesphp.com/engine/).
I would use blade, but phpstorm support for it is really bad. You can typehint variables, formatting is messed up, javascript errors highlighted even though they're not there. Eh, blade is not really usable with an IDE.
