### ISSUE TITLE
Laravel log file

### ISSUE THREAD

**Issue by BardiaAfshin** [laravel/framework#10228]
Is there an option that will tell laravel to only keep 1 days worth of log? A restriction for how long log files should be kept.

**Comment by GrahamCampbell** [comment]
You'd need to implement your own gc.

**Comment by BardiaAfshin** [comment]
What is gc?

**Comment by kamui545** [comment]
garbage collector

**Comment by BardiaAfshin** [comment]
Do you recommend writing a artiscan command for this? or simply writing a crontab to execute on the directory every so often. Community experience with this? Log files are a common problem for disks running out space, and needing a log rotator of sorts. Laravel doing anything to address this common problem?

**Comment by deefour** [comment]
http://www.linuxcommand.org/man_pages/logrotate8.html
