### ISSUE TITLE
Artisan make:test is missing in 5.1

### ISSUE THREAD

**Issue by lopezchairez** [laravel/framework#10224]
In the docs it says "To create a new test case, use the make:test Artisan command". But the command doesn't exists (Command file not found in Illuminate\Foundation\Console directory).

**Comment by GrahamCampbell** [comment]
That's because that feature has not been released yet. I'll be available in the next 5.1 release.

**Comment by GrahamCampbell** [comment]
NB I think Taylor will be releasing on Tuesday, but don't quote me on that.

**Comment by MartinWeise** [comment]
Thanks for the info. Struggling with the same problem.

**Comment by kyrenator** [comment]
Waiting for next release then...

**Comment by chrismedina** [comment]
LOL. Same problem here. Is this now live and well?

**Comment by paper777** [comment]
Same problem here...
