### ISSUE TITLE
implement add comment to columns created by migrations

### ISSUE THREAD

**Issue by marwan2** [laravel/framework#10221]
I would like you to implement column comments, such as this

Schema::create('event', function($table){
             $table->increments('id');
             $table->string('title')->nullable();
             $table->text('gallery')->nullable()->comment('this will hold images in comma separated format');
             $table->timestamps();
          });
 
It will save a lot of time & efforts plus completing DB Migration Solution

**Comment by GrahamCampbell** [comment]
Was already proposed and rejected, sorry.

**Comment by patrickcarlohickman** [comment]
@marwan2 It looks like this has already been implemented for MySQL since L4.2. Are you using a different database engine?
