### ISSUE TITLE
Mailer has no option for sending raw mail as html

### ISSUE THREAD

**Issue by athahersirnaik** [laravel/framework#10235]
In Mailer class there is no option for sending raw (string) mail as html. Suppose, that I want to get the body of the mail from a template stored in database, and it is html. I can't use raw as it will treat, as a text not html.

    protected function addContent($message, $view, $plain, $raw, $data)
    {
        if (isset($view)) {
            $message->setBody($this->getView($view, $data), 'text/html');
        }
    
        if (isset($plain)) {
            $message->addPart($this->getView($plain, $data), 'text/plain');
        }
    
        if (isset($raw)) {
            $message->addPart($raw, 'text/plain');
        }
    }

**Comment by GrahamCampbell** [comment]
What you can do is just implement your own mailer. That's what I've done.

**Comment by GrahamCampbell** [comment]
That's one of the reasons Laravel has contracts.

**Comment by athahersirnaik** [comment]
Ok

**Comment by shahidkarimi** [comment]
Sending raw html is a headache in Laravel

**Comment by nickwest** [comment]
The easiest way to send a raw html email is to use:
`Mail::send('customrawtemplate', array('html' => 'your raw html goes here')...)` 

and create a raw email template that just has:
`{!! $html !!}`

**Comment by str** [comment]
OK, the way I did it was:

```php
        Mail::send([], [], function($message) use ($data) {
            $message->from($data['from']);
            $message->to($data['to']);
            $message->subject($data['subject']);
            $message->setBody($data['content'], 'text/html');
        });
```

**Comment by abellion** [comment]
Being stuck with blade make no sense --'

**Comment by jubairsaidi** [comment]
yea I like the whole improved workflow for sending emails with 5.5 but honestly, it's overkill in many situations.  There is often the case to simply sent an attachment with a 1 liner in the body of the email etc.  Not all emails are client facing, and may not need the extra work of creating a view and format... like sending a csv report to a web admin for example, they don't care about the email contents, just the file.

**Comment by jubairsaidi** [comment]
I send  a number of csv/pdf/other generated file reports at regular intervals to web admins who don't care about anything in the email except for the attachment so I simply use `Mail::raw('see attached', function($message) { ... })` for those instances.  My only disappointment is you can't do this with a Mailable class.

**Comment by bhawani007** [comment]
thanks bro... code working fine.

**Comment by abellion** [comment]
https://github.com/laravel/framework/pull/22809

You can now use the `html()` method on both Mailer and Mailable.

**Comment by kenmoini** [comment]
> The easiest way to send a raw html email is to use:
> `Mail::send('customrawtemplate', array('html' => 'your raw html goes here')...)`
> 
> and create customrawtemplate.blade.php that just has:
> `{!! $html !!}`

After a day or so of trying, this is the only thing that worked 100%.  Simple, and genius.

**Comment by boldstar** [comment]
@abellion , how do we pass data to the `html()` method?

for instance when I am building an email using `view()` I can use the `->withd([ 'data', => $data ])` on the end and I will have access to that data in the view..

is there a way to do this using the `html()` method?

Note: using laravel version 5.6 currently...

**Comment by abellion** [comment]
@boldstar when using the `html()` method the given _plain_ content doesn't pass through any template engine. I think you should use a view (i.e. a blade template) if you want to format its content.

**Comment by boldstar** [comment]
@abellion , yeah I was trying to make templates that could be pulled from the database and be rendered with data. When I run the `view()` (i.e. blade template) it looks for  a view which is obviously not available since it is from the database and throws an alarm, unless maybe there is a way I can create views on the fly before passing it in to the `view()` method?
