### ISSUE TITLE
5.1.16 route:cache breaking Model Binding from routes.php into Controller

### ISSUE THREAD

**Issue by sharf224** [laravel/framework#10242]
I was creating a project that I ended up breaking and after repeated testing I've been able to consistently recreate the issue. Before I attempt a pull request I wanted some feedback to see if this is expected behavior and I'm just doing it wrong.

When running `php artisan route:cache` and creating a cache file, all `show` Models stop getting passed.

Following tutorials online, including Laracasts, I set my route to something like this:

    $router->bind('page', function($slug)
    {
        return App\Page::where('slug', $slug)->first();
    });

    $router->resource('page', 'PageController');

The result is the same if I use a resource or create a list of matching `get`s, `puts`, etc.

My `PageController`'s `show` method looks like:

    function public show(Page $page)
    {
        return $page;
    });
    

I'm `use`ing `App\Page` at the top, and everything works perfect using the route file above and using the `show` method above. (this has been tested with several different databases, tables, etc. all on fresh `laravel new` projects).

However, as soon as I use `php artisan route:cache` a cache file is created under `bootstrap/cache/routes.php`. Now, if you reload the `/page/{page}` page in your browser, the returned Page Model is just empty brackets ( [] ). As soon as I run `php artisan route:clear` or delete the file manually, everything begins to work again.

I am currently in a 'local' environment, and have not tested this in production.

Any insights?

**Comment by GrahamCampbell** [comment]
You can't compile routes containing closures.

**Comment by MarkVaughn** [comment]
For any future people stumbling across this issue and wanting a solution to the problem.
Caching seems to strip out all bindings, but after the boot method loads the cached routes you can apply your bindings this works!

```
    /**
     * Define your route model bindings, pattern filters, etc.
     */
    public function boot()
    {
        parent::boot();

        $router->bind('page', function($slug)
        {
            return App\Page::where('slug', $slug)->first();
        });
    }
```

**Comment by casperwilkes** [comment]
Was running into similar issue. My problem was I was defining the binding inside the `routes/web.php` file instead of the `RouteServiceProvider.php`
