### ISSUE TITLE
\Illuminate\Http\Request fails silently on json decode errors

### ISSUE THREAD

**Issue by aedart** [laravel/framework#10257]
In case that a client sends a malformed json string, which cannot be decoded correctly, the `json()` method just ignores it; well... it just ensures that an empty array is being set internally.

I do find this to be a bit frustrating, because it can be very difficult to debug - unless you know exactly that this json behaviour can happen in the request instance.

*Possible solution*
Check the decoded json string for `null` value, and `json_last_error`. If any json error is present, perhaps throw an exception - one that doesn't need to be logged.

**Comment by aedart** [comment]
Btw, ... I have resolved this issue in my given project, in a custom form-request for json. But thought that this might be helpful for Laravel, if the request would someone let the user / client know about malformed json...

**Comment by jrumbut** [comment]
@aedart would it be possible for you to post the custom request (or a snippet containing the JSON error detection logic) you used to fix this issue?

I think I've run into the same problem and it definitely adds to the debugging time.

Thank you :)

**Comment by GrahamCampbell** [comment]
We're open to PRs to 5.2 I guess.

**Comment by aedart** [comment]
@jrumbut I have used the following code, in order to get around this issue;

```php
    protected function getInputSource()
    {
        if($this->isJson()){
            $this->assertCanDecodeJson($this->getContent());
        }
        return parent::getInputSource();
    }

    public function assertCanDecodeJson($rawContent){
        if(is_null(json_decode($rawContent, true)) && json_last_error() != JSON_ERROR_NONE){
            throw new BadRequestException(); // A custom exception...
        }
    }
```

**Comment by jrumbut** [comment]
@aedart Thank you very much, that pointed me in the right direction on a couple issues actually!

**Comment by KamilKopaczyk** [comment]
This is related to #5022. This issue and #5022 are both closed and won't be implemented in any way?
