### ISSUE TITLE
[Request] Allow the withoutMigrations() method on Illuminate\Foundation\Testing\CrawlerTrait to accept arguments of which middleware to disable.

### ISSUE THREAD

**Issue by EnolaLabs** [laravel/framework#10254]
The **WithoutMiddleware** option is a fantastic feature for testing APIs. However, there are some packages that use middleware as a way to slip in new functionality. For example, Dingo API adds its own routing list by using a middleware. When testing, this gets to be a problem because if you want to disable middleware for security, you also end up disabling the routing middleware causing all HTTP calls 
```php
$this->get(), 
$this->post(),
// etc.
```
to end up being 404 errors.

It would be great to be able to say 
```php
$this->withoutMiddleware(['auth', ...]);
```

Thanks

**Comment by FooBarQuaxx** [comment]
@EnolaLabs Yes it would be great especially for testing.

**Comment by GrahamCampbell** [comment]
This isn't currently easily possible, sorry
