### ISSUE TITLE
Tracking database changes on related models

### ISSUE THREAD

**Issue by mrfarooqkhalid** [laravel/framework#10258]
We are trying to detect the changes in Laravel related models at attribute level, as we have to keep audit trail of all the changes which are made via the application.

We can track the changes via isDirty method on the Eloquent model for single model that is not related to any other model, but there is no way that we can track the changes on the related eloquent models. isDirty doesn't work on related models attributes. Can some one please help us on this?

Thanks

**Comment by mrfarooqkhalid** [comment]
Just to elaborate on the question, actually we are trying to track changes on the pivot table that has extra attributes as well defined on it. IsDirty method doesn't work on those extra attributes which are defined in the pivot table. Yes we are detecting CRUD changes as we have to create audit trail.

**Comment by GrahamCampbell** [comment]
Feel free to ask on the forums.
