### ISSUE TITLE
[5.1.*] Authentication and Register Behaviour

### ISSUE THREAD

**Issue by jrean** [laravel/framework#10255]
Hi,

For instance:

Update the users table:

```
        Schema::table('users', function (Blueprint $table) {
            $table->boolean('foo')->default(false);
            $table->string('bar')->nullable();
        });
```

Step 1
Process the user registration:
https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Auth/RegistersUsers.php

```
    public function postRegister(Request $request)
    {
        $validator = $this->validator($request->all());
        if ($validator->fails()) {
            $this->throwValidationException(
                $request, $validator
            );
        }
        Auth::login($this->create($request->all()));

        dd(auth()->user()); // <-- HERE

        return redirect($this->redirectPath());
    }
```

It outputs:

```
User {#173 ▼
  ...
  #attributes: array:6 [▼
    "name" => "jean"
    "email" => "foo@bar.com"
    "password" => "xxx"
    "updated_at" => "2015-09-14 03:10:12"
    "created_at" => "2015-09-14 03:10:12"
    "id" => 17
  ]
```

Question 1: How can I have access to the `auth()->user()` because it happens before the `redirect()`?
Question 2: Why the `auth()->user()` is not returning the full attributes list? (remember_token, foo and bar)

Step 2
Now for instance:

```
Route::get('/', function () {
    dd(auth()->user());
});
```

Outputs:

`null`

Question 3: How could I had access in step 1 to `auth()->user()` (before the redirect) and not in step 2? (as far as I know it is normal to not have access because the user wasn't put in session, but I still don't understand why I had access to it in step 1)

--

If I repeat exactly the same process but this time without the `var dump` within the `postRegister()` method the user is registered, logged in and redirected to the `redirectPath()`. Great.

Now for instance:

```
Route::get('/', function () {
    dd(auth()->user());
});
```

Outputs:

```
User {#161 ▼
...
  #attributes: array:9 [▼
    "id" => "19"
    "name" => "jean"
    "email" => "foo@bar.com"
    "password" => "xxx"
    "remember_token" => null
    "created_at" => "2015-09-14 03:22:59"
    "updated_at" => "2015-09-14 03:22:59"
    "foo" => "0"
    "bar" => null
  ]
```

Question 4: Why this time the `remember_token`, `foo` and `bar` attributes are listed and not previously?

Question 5: Is it the normal behaviour?

Question 6: How could I have access to the full attribute list in the `postRegister()` method, just after the registration and just before the `redirect()` happens?
 
Thank you.

**Comment by GrahamCampbell** [comment]
Please ask on the forums.
