### ISSUE TITLE
Default session cookie (CookieJar) does not use config option for 'secure'

### ISSUE THREAD

**Issue by terrencegf** [laravel/framework#10268]
When using the cookie session driver (as configured in `config/session.php`), the value for `secure` is ignored in `CookieServiceProvider.php`. This results in session id cookies (i.e., the ones with 40-character hexadecimal string names like `055f7f3e004c69f30b1add93160054334b5d6aca`) being marked as **not** secure, while the configured cookie named (by default) `laravel_session` being marked as secure. This is true for Laravel v.4.2 and v.5.1.

I think the fix is relatively simple. In `CookieServiceProvider.php`, simply add the 'secure' value as a third parameter to `setDefaultPathAndDomain()`, like so:

```php
public function register()
{
    $this->app->singleton('cookie', function ($app) {
        $config = $app['config']['session'];
        return (new CookieJar)->setDefaultPathAndDomain($config['path'], $config['domain'], $config['secure']);
    });
}
```

Then modify `CookieJar.php` to support the extra parameter. 

I have successfully done this in my local project. I would like to submit a patch to GitHub as I think it is a bug to have some cookies secure and some cookies insecure.

**Comment by GrahamCampbell** [comment]
Closing due to no interest. We might accept a good quality PR though.
