### ISSUE TITLE
Production environment variable

### ISSUE THREAD

**Issue by BardiaAfshin** [laravel/framework#10266]
Setting the 
APP_ENV=production

doesn't change anything. Specifically, what I'd like to see is when there is a NotFoundHTTPException, hide the details and just log it.

Help?

**Comment by wdmtech** [comment]
I'm experiencing the same issue right now - `Dotenv::makeMutable();` makes Dotenv obey the .env config, but I'm sure there used to be a start.php/environment.php for env detection last time I looked!

**Comment by GrahamCampbell** [comment]
> doesn't change anything.

Did you clear your config cache?

**Comment by GrahamCampbell** [comment]
Any further issues, please ask on the forums.

**Comment by wdmtech** [comment]
Just tried clearing my caches also, to no avail - still says env is `local` when `APP_ENV=staging`

**Comment by GrahamCampbell** [comment]
I can't replicate. Is the file named correctly?

**Comment by wdmtech** [comment]
Anything to do with me using `artisan serve` perhaps? I normally use vagrant.

Can confirm `artisan key:generate` worked, file is named `.env`

**Comment by wdmtech** [comment]
.env `APP_ENV` is working fine on homestead.

**Comment by BardiaAfshin** [comment]
I think it's getting cached in /vendor/config.php, wipe out this file and see if it works for you?
