### ISSUE TITLE
Helper "elixir" function has hardcoded "build" path

### ISSUE THREAD

**Issue by blackakula** [laravel/framework#10274]
I want my versioned assets not to be located in "build" folder, but in public itself. I'm able to do this with second parameter of `mix.version`: `mix.version('css/styles.css', 'public');`, but how I can refer to them in my templates now if `elixir` function (located in `src/Illuminate/Foundation/helpers.php`) has hardcoded `build` folder? Of course it doesn't find my `public/rev-manifest.json` and throws `InvalidArgumentException`

**Comment by GrahamCampbell** [comment]
Sorry, we don't allow you to customize that out of the box.

**Comment by Rjs37** [comment]
Would it be worth a pull request (not something I've needed to do before but I'd I'd give it a shot) or is the idea of overriding the build path shot down entirely?
