### ISSUE TITLE
The php artisan app:name New-namespace is not effect

### ISSUE THREAD

**Issue by XingFang** [laravel/framework#10270]
I am new to Laravel,this morning i would like to change my project namespace,then i run command "php artisan app:name New-Name",but when i open browser to visit my project,it is a blank page,Like this:
![qq 20150915112329](https://cloud.githubusercontent.com/assets/13644079/9867098/811896dc-5b9c-11e5-9329-a25addff738a.png)
when i revert my project to before change,everything is ok!!  I do not understand what it is！！
And another question,if i would like to create a directory under the "app",Whether composer will automatically load the folder?

**Comment by scrothers** [comment]
Hello,

You cannot use dashes in your application namespace. However, before I assume that "New-Name" is actually the namespace you were using (I actually suspect you were using something else) perhaps you can attach a log from Laravel in the form of a gist?

**Comment by XingFang** [comment]
I didn't do that like new-name,this is a example..In fact, I wrote "Myblog".The project is not open,so,it is not generate log file ,this is my Screenshot:
![qq 20150915122302](https://cloud.githubusercontent.com/assets/13644079/9867923/5e6e6fea-5ba5-11e5-9a5e-7cec4e1c07e6.png)

**Comment by scrothers** [comment]
I suspect that the app:name didn't rename your namespaces correctly, no matter what the issue's root cause is though, everyone will need to see the logs on here to help with any diagnosis. So if you can reproduce the issue and paste the logs to a gist, that would be key to helping you with the problem.

**Comment by XingFang** [comment]
I found the root of the problem ,cause I customize a boot file "app_custom.php", while Laravel only modify its own boot file "app.php" inside namespace ,i'm sorry,This is my carelessness. anyway, still thank you very much.

**Comment by XingFang** [comment]
And another question,if i would like to create a directory under the "app",Whether composer will automatically load the folder?
