### ISSUE TITLE
How do I clone model properly?

### ISSUE THREAD

**Issue by miraage** [laravel/framework#10287]
Imagine tables: 
```
orders (id INT PRIMARY KEY, status SMALLINT)
order_details(id INT PRIMARY, order_id, some_option BOOLEAN)
```

```
$order = Order::find(1);
$newOrder = $order->replicate();
```

`$newOrder` will have old relations because they've [simple assigned](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Database/Eloquent/Model.php#L2980). After saving there should be new `order_detail` with changed foreign key but same data.

Any ideas?

**Comment by armendarabyan** [comment]
have you tried to pass $except argument for replicate?

**Comment by miraage** [comment]
@armendarabyan `$except` only affects attributes. I think relations should be replicated properly.

**Comment by miraage** [comment]
@GrahamCampbell why issue is closed? Could anyone give me real explanation? :)

**Comment by GrahamCampbell** [comment]
Closed because this belongs on the forums please.
