### ISSUE TITLE
How to specify queue name in event listeners

### ISSUE THREAD

**Issue by pavankumarkatakam** [laravel/framework#10284]
When using jobs, we can dispatch job to queue by specifing the `onQueue('queueName')`, but how to specify in case of event and its listeners.

**Comment by GrahamCampbell** [comment]
Duplicate.

**Comment by pavankumarkatakam** [comment]
if it is duplicate, please specify the duplicate issue. i have checked but no luck.

**Comment by sakalauskas** [comment]
I was looking for this as well, It took me quite a while to find it actually.

Here is the solution: https://github.com/laravel/framework/pull/9869#issuecomment-150181293

**Comment by pavankumarkatakam** [comment]
oh, thanks @sakalauskas

**Comment by Jimmea** [comment]
U can set a property $queue = 'your_name_queue' in class Listener u created. 
I have test on laravel 5.5. It's ok... Before u have create two app to run multiple queue work. 
php artisan queue:work database --queue=job_spider
php artisan queue:work database --queue=job_user
