### ISSUE TITLE
all storage logs in one file instead of dated filestamp files.

### ISSUE THREAD

**Issue by BardiaAfshin** [laravel/framework#10297]
I'd like to have Laravel (Laravel 5) write all the logs to one file, and truncate them at the end of the day, is this possible? I don't see anything in the documentation provided on the website.

**Comment by GrahamCampbell** [comment]
Yes.

**Comment by GrahamCampbell** [comment]
It's document in the config file.

**Comment by BardiaAfshin** [comment]
I changed the value to 'daily' /app/config/app.php and ran a few requests against the localhost
no new storage log files are being created.

And which config file? /vendor/config?

**Comment by GrahamCampbell** [comment]
Did you clear the config cache?

**Comment by GrahamCampbell** [comment]
It's documented in app.php, and daily isn't want you want. That'll create multiple files.

**Comment by BardiaAfshin** [comment]
I did run
./artisan config:clear && ./artisan config:cache

and appologies, I had changed it to 'log' => 'single'  , not 'daily' as I had stated earlier, it was previously daily

From the app.php
```app.php
	/*
	|--------------------------------------------------------------------------
	| Logging Configuration
	|--------------------------------------------------------------------------
	|
	| Here you may configure the log settings for your application. Out of
	| the box, Laravel uses the Monolog PHP logging library. This gives
	| you a variety of powerful log handlers / formatters to utilize.
	|
	| Available Settings: "single", "daily", "syslog", "errorlog"
	|
	*/
```

It would actually work better if it goes to RSYSLOG daemon running on the server, I know the two are not the same, but rsyslog and syslog are used interachangeably by people. Will this work?

My overall goal is have Loggly index everything, if I can use rsyslog for this logging , and it won't slow down the actual web requests, it would be a smart solution to what I need achieved.
