### ISSUE TITLE
seeCookie() not working with `EncryptCookies` middleware

### ISSUE THREAD

**Issue by tillkruss** [laravel/framework#10298]
When I'm using `CrawlerTrait::seeCookie()` I get the following failure message:

    Cookie [FOOBAR] was found, but value [ENCRYPTED-STRING] does not match [PLAIN-STRING].

It looks like the `$value` given to `seeCookie()` doesn't get encrypted.

Is there a way to disable only the `EncryptCookies` middleware for a single unit test? I tried using the `WithoutMiddleware` trait, but that causes loads of issues.

**Comment by GrahamCampbell** [comment]
Please ask on the forums.

**Comment by tillkruss** [comment]
That's the only way I found that worked:

```
$this->app->resolving(EncryptCookies::class, function ($object) {
    $object->disableFor('cookie-name');
});
```
