### ISSUE TITLE
make:event and event:generate command overwrite existing event file

### ISSUE THREAD

**Issue by HiroKws** [laravel/framework#10290]
As title said. artisan make:event command overwrite existing file. So event:generate command also.

In event documents say "untouched" it. so it is incorrect now.

I think document is correct, the commands behaver incorrectly.

**Comment by HiroKws** [comment]
Aha. EventGeneraterCommand extends GeneratorCommand. GeneratorCommand check if a target file already exist. 
While EventGeneratorCommand just extends Command. Maybe Taylor intended to extend GeneratorCommand, but seems to forget it.  :)

**Comment by HiroKws** [comment]
Oh something I missed. Once close this.

**Comment by HiroKws** [comment]
OK, now I understood whole.

Situation:

1. Execute 'php artisan make:event TestEvent', then this command generated 'App\Events\TestEvent' class.
2. Modified 'App\Events\TestEvent' class.
3. Execute again 'php artisan make:event TestEvent' command. So 'App\Events\TestEvent' class was overwrote by newly generated stub class.

Came from:

Illuminate\Foundation\Console\EventMakeCommand class is the generator command class. This class extends Illuminate\Console\GeneratorCommand that correctly checked class existence based on  namespace in alreadyExists method. 

However EventMakeCommand overwrote alreadyExists to check without class namespace. 

In result, make:event Artisan cli became destructive.

I just commented out alreadyExists method in EventMakeCommand, then it work properly.

**Comment by HiroKws** [comment]
https://github.com/laravel/framework/commit/4c331c9fd98be29c77b3397bac1abc36211d1af8

Maybe on this commit, no needed changes on EventMakeCommand.

This commit seems to try to resolve same issue, but generated now one... needed well tests...

**Comment by GrahamCampbell** [comment]
So, what's the actual issue then?

**Comment by HiroKws** [comment]
try

1.  Execute 'php artisan make:event TestEvent', then this command generated 'App\Events\TestEvent' class.
2.  Modified 'App\Events\TestEvent' class.
3.  Execute again 'php artisan make:event TestEvent' command. So 'App\Events\TestEvent' class was overwrote by newly generated stub class.

As mentioned, this command overwrite existing class file.  Other generate commands never. Only when full namespaced class name specified, file checking work correctly. 

php artisan make:event TestEvent  <= this will overwrite existing app/Events/TestEvent.php file.
php artisan make:event 'App\Events\TestEvent' <= This display error message as "file existed".

**Comment by GrahamCampbell** [comment]
I can't replicate that behaviour. Are you sure you named the file correctly? The class name MUST match the file name.

**Comment by HiroKws** [comment]
Of cause muched, whole namespace + class name is muched file structure, because the command generated.

And again, I just have installed fresh 5.1LTS, and still overwrote existing file as I mentioned. 

If you read the Illuminate\Foundation\Console\EventMakeCommand, you may understand I'm right. The source code showed behaviour I reported.

**Comment by HiroKws** [comment]
Please re open. Another problem is there.

When you will make View event file when app\Events\View.php file dose not exist. You may type :

```
$ php artisan make:event View
```

This command return 'Event already exists!' everytime!! (Of course also when the file is not there)

Because 'View' is registered as facade alias on the top of name space. Other facades' name will make same situation.

Do you think this behaver is correct???
