### ISSUE TITLE
PostLogin method not executed using actingAs

### ISSUE THREAD

**Issue by acacha** [laravel/framework#10304]
Maybe I'm wrong but when using actingAs method is Laravel tests I assume to act the same way as a login used. The problem is that the method postLogin is not executed so is not exactly the same.

For example in my app after login I register some session variables (suppose only one with name applocalmodel)

This test does not work 
```php
       $user = factory(User::class)->create();
       $this->actingAs($user)
            ->visit('/home')
            ->see('Disseny de Normes');
```

because the session variable is used in /home page

I have to manually establish the session values with:

```php
       $user = factory(User::class)->create();
       $this->actingAs($user)
            ->withSession(['applocalemodel' => 'ca'])
            ->visit('/home')
            ->see('Disseny de Normes');
```

Anyway if this is the way Laravel is expected to behave anyone could suggest my any way of executing postLogin method in tests?

**Comment by dan-har** [comment]
The reason your first test is not working is because the ```actingAs()``` method sets the user on the session, but it wont start the session, to do so you have to use ```$this->sessionStart()``` or ```$this->withSession()```.

This can be used when you want to test without performing http request for login.

For example :
``` php
public function testSomething(){
       $user = factory(User::class)->create();
       $this->asLoginUser($user) // <- note this function
              ->visit('/home')
              ->see('Disseny de Normes');
}

protected function asLoginUser(User $user){
       return $this->actingAs($user)
                   ->withSession(['applocalemodel' => 'ca']);
}
```

But if you want to perform login with http request then
we can just change the ```asLoginUser()``` and make an example of use of ```postLogin()``` :
``` php
protected function asLoginUser(User $user){
      $this->startSession();
      
      $this->call('POST', 'auth/login', [
             'email' => 'some@email.com',
             'passowrd' =>'pass',
             'remember' => 0,
             '_token' => csrf_token() // <- dont foget the csrf token check
      ]);
      
      //asserts that the user was logged 
      $this->assertSessionHas('applocalemodel', 'ca');
      $this->assertRedirectedTo('/home');

       return $this;
}
```

**Comment by acacha** [comment]
Thanks @dan-har for the explanation
