### ISSUE TITLE
FormRequest always returns JSON for AJAX requests

### ISSUE THREAD

**Issue by jp7carlos** [laravel/framework#10307]
I know it is something pretty hard to get right, but i disagree with the way FormRequest checks if it should return JSON.

The code says:  

    if ($this->ajax() || $this->wantsJson()) {
             return new JsonResponse($errors, 422);
    }

So when the request is AJAX, it won't even check if i want JSON. 

* What if I explicitly said that I want HTML (XML or anything else) in my AJAX request?
* Is it a convention that is used elsewhere in Laravel?

It seems to me that being a AJAX request and wanting (or accepting) JSON are two different things.

**Comment by morloderex** [comment]
@jp7carlos You can just overwrite the method checking for this :)

**Comment by GrahamCampbell** [comment]
I've brought this up before, and we looked into change it, but we ended up deciding this implementation is an OK default.
