### ISSUE TITLE
'single' file logging

### ISSUE THREAD

**Issue by BardiaAfshin** [laravel/framework#10305]
when APP_LOG=single option is set, I'd like to set a filename for this option. Is there a build in parameter/option/variable/config for this?

Right now it's giving a file that has a timestamp named laravel-2015-09-18.log, instead it'd be nice to just get laravel.log or something along those lines.

EDIT:
The current laravel framework version is 5.0

**Comment by GrahamCampbell** [comment]
Sorry, 5.0 isn't supported, and out of the box in 5.1, we do do just that.
