### ISSUE TITLE
"Lang::get" or "trans" in Config files

### ISSUE THREAD

**Issue by DaBourz** [laravel/framework#10300]
With Laravel 4 I was using "Lang::get" or "trans" in Config files, like : 

```'myKey' => Lang::get('awa-mail.myKey'),```

In an array.

But now "Lang::get" is a class not found and "trans" crashes the App, to the point it can even find "Log" (probably because it crashes in the config so Log is not loaded at this point.

Is this a bug ? Or we can't do that anymore ?

**Comment by crynobone** [comment]
> Is this a bug ? Or we can't do that anymore ?

We can't do that anymore

**Comment by DaBourz** [comment]
That's all ? :-) Finished ? ;-)

**Comment by rifayman** [comment]
Did you find out the soluction ??? couse i get the same probleme

**Comment by DaBourz** [comment]
The boss has spoken man, you can't do this anymore.
