### ISSUE TITLE
Provide base domain for testing

### ISSUE THREAD

**Issue by spyric** [laravel/framework#10311]
Hello. Now in config/app.php files there is parameter 'url' that is not using in testing features.

For example I have next `routes.php`

```php
Route::group([ 'domain' => 'somedomain.my' ], function ()
{
    Route::post('/', ['as' => 'index','uses'=> 'Index@index']);
}
```

in `config/app.php`

```php
...
	'url' => 'http://somedomain.my/',
...
```

When I tesing application  with next class

```php
<?php
class ExampleTest extends TestCase {
    /**
     * A basic functional test example.
     *
     * @return void
     */
    public function testBasicExample()
    {
        $response = $this->call('GET', '/');
        $this->assertEquals(200, $response->getStatusCode());
    }
}
```

I hope that it will emulate request to http://somedomain.my/ instead of http://localhost/

And this test fails. But there is not 404 error in fact.

I offer:
1. Use `app.url` for testing request
2. Give ability to set domain for tesing. It will be useful if all test cases in file are testing only one subdomain

**Comment by crynobone** [comment]
You should be able to do that already <https://github.com/laravel/laravel/blob/master/tests/TestCase.php#L10>
