### ISSUE TITLE
cant register schedual task outside the console kernel

### ISSUE THREAD

**Issue by rotembo** [laravel/framework#10317]
Hi,
I am making kind of a modules based application that each  module have its own ServiceProvider.php 
there I can register new commands and schedule task. I have encountered an issue with the console kernel which instantiate the schedule in the container after the boot process had finished which cause every schedule registration that committed on the external service provider to be thrown away, to make it work I overrided the constructor at Illuminate\Foundation\Console\Kernel
and replace these lines:
        $this->app->booted(function () {
            $this->defineConsoleSchedule();
        });
with this one:
       $this->defineConsoleSchedule();

which I have difficult to understand why it should work after boot in the first place
can anyone explain to me what is the purpose of the original code was?

**Comment by GrahamCampbell** [comment]
Please ask on the forums.
