### ISSUE TITLE
InvalidArgumentException with message 'Data missing' in Illuminate\Database\Eloquent\Model::asDateTime()

### ISSUE THREAD

**Issue by Elandril** [laravel/framework#10312]
Calling asDateTime() with a full SQL DateTime string, e.g. asDateTime('2015-09-19 12:00:00'), fails with the following exception:
```
InvalidArgumentException with message 'Data missing'
```

This happens both as a instance call and as a static call. Calling the method with only a date string ('2015-09-19') or a timestamp works.

The problem seems to stem from **line 2937 in Illuminate\Database\Eloquent\Model.php**:
```php
return Carbon::createFromFormat($this->getDateFormat(), $value);
```
There getDateFormat() is called as an instance method to retrieve the proper date format, but this fails with an exception:
```
BadMethodCallException with message 'Call to undefined method Illuminate\Database\Query\Builder::getDateFormat()'
```
A static call to static::getDateFormat yields the correct result ("Y-m-d H:i:s" in my case).

This happens with the most current released version 5.1.17.

Edit: Corrected version number typo.

**Comment by GrahamCampbell** [comment]
> This happens with the most current released version 5.1.12.

The latest version is 5.1.17...

**Comment by Elandril** [comment]
Sorry that was a typo. 
I am actually on version 5.1.17... so the issue is valid.

**Comment by GrahamCampbell** [comment]
Could you provide a very small piece of code so we can replicate this please. Without that, you haven't really reported anything.

**Comment by Elandril** [comment]
Here a small piece of code that triggers the error:
```php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class AcctSession extends Model
{

    public function scopeActiveSince($query, $time = '2015-09-19 15:00')
    {
        // following line raises InvalidArgumentException with message 'Data missing'
        // when $time is a full SQL DateTime string, but not if it's a timestamp or 
        // date-only value (e.g. '2015-09-19')
        $time = static::asDateTime($time);

        return $query->where('start_time', '<=', $time)
                     ->whereNull('stop_time');
    }

}

```

**Comment by GrahamCampbell** [comment]
Can I see the strack trace please?

**Comment by Elandril** [comment]
I debugged the Model with artisan tinker, which unfortunately didn't output a stack track. Now I put it into some site code, and immediately found the underlying reason: a component in between the calls shortened the time part of the SQL DateTime to minutes accuracy (like in my default value above), which apparently breaks Carbon... hard. It seems that there is no tolerance for shortened time string (omitting seconds).

Here a slightly shortened stack trace, if you're still interested:
```
InvalidArgumentException in Carbon.php line 414:
Data missing

in Carbon.php line 414
at Carbon::createFromFormat('Y-m-d H:i:s', '2015-09-19 18:00') in Model.php line 2925
at Model->asDateTime('2015-09-19 18:00') in AcctSession.php line 66
at AcctSession->scopeActiveSince(object(Builder), '2015-09-19 18:00')
at call_user_func_array(array(object(AcctSession), 'scopeActiveSince'), array(object(Builder), '2015-09-19 18:00')) in Builder.php line 829
at Builder->callScope('scopeActiveSince', array('2015-09-19 18:00')) in Builder.php line 940
at Builder->__call('ActiveSince', array('2015-09-19 18:00'))
at Builder->ActiveSince('2015-09-19 18:00')
at call_user_func_array(array(object(Builder), 'ActiveSince'), array('2015-09-19 18:00')) in Model.php line 3423
at Model->__call('ActiveSince', array('2015-09-19 18:00'))
at AcctSession->ActiveSince('2015-09-19 18:00')
at call_user_func_array(array(object(AcctSession), 'ActiveSince'), array('2015-09-19 18:00')) in Model.php line 3437
at Model::__callStatic('ActiveSince', array('2015-09-19 18:00')) in AcctSessionController.php line 98
at AcctSession::ActiveSince('2015-09-19 18:00') in AcctSessionController.php line 98
```

Sorry to have wasted your time, since the issue lies elsewhere. It would be great though, if there was some way to add or ignore the missing seconds.

**Comment by syaiful6** [comment]
Ouh, it's not bug.. You just call it incorretcly, before call ```asDateTime``` check the string, or you also call it with ```Y-m-d``` format. or only accept ```DateTime``` instance on ```scopeActiveSince``` method.

If you prefer catch the exception and try add seconds part, here my solution:
```
try {
    $datetime = static::asDateTime($time);
} catch(InvalidArgumentException $e) {
   // try add your seconds
   $datetime = static::asDateTime($time . ':00');
  // or you can grab the format Y-m-d part with  
  // $match = []
  // preg_match('/^(\d{4})-(\d{2})-(\d{2})/',  $time, $match);
 // take $match[0];
}
```
