### ISSUE TITLE
URL parameters

### ISSUE THREAD

**Issue by gaaarfild** [laravel/framework#10329]
i.e. I have this route
``` PHP
Route::any('/{foo?}/{bar?}/{baz?}', [
    'as' => 'foobar',
    'uses' => 'FooController@index',
]);
```
And I'm doing like this:
``` PHP
$params = [
    'foo' => '1',
    'wall' => '2',
    'nut' => '3',
    'sick' => '4',
];
return Redirect::route('foobar', $params, 301);
```
As a result, redirect is going to `http://website.loc/1/2/3?sick=4`
Why? I have a concrete param names. But laravel fills it with incorrect array values.
It supposed to be `http://website.loc/1?wall=2&nut=3&sick=4`

**Comment by GrahamCampbell** [comment]
Hmmm, what happens if you do this for params:

```
$params = [
    0      => '1',
    'wall' => '2',
    'nut'  => '3',
    'sick' => '4',
];

**Comment by gaaarfild** [comment]
I guess, it will be `http://website.loc/1/2/3?sick=4`

**Comment by GrahamCampbell** [comment]
Could you try it please?

**Comment by gaaarfild** [comment]
I tried. I was right.

**Comment by GrahamCampbell** [comment]
Hmm, well, the tests kind of imply that this is actually the intended behaviour.

**Comment by gaaarfild** [comment]
Yeah. I checked the. But do you personally think that it is correct behaviour?

**Comment by GrahamCampbell** [comment]
Not really up to me tbh. Maybe should should directly contact Taylor on slack to check what he thinks.
