### ISSUE TITLE
include function for retriesleft in login throttling.

### ISSUE THREAD

**Issue by pavankumarkatakam** [laravel/framework#10326]
it will be nice to have a function `retriesleft()`which returns the number of attempts to login in Authenticatingusers trait.

**Comment by GrahamCampbell** [comment]
I agree this would be useful, especially when setting headers on the response for example.

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell.

**Comment by pavankumarkatakam** [comment]
Yeah, it is very helpfull
