### ISSUE TITLE
Impossible to call `EncryptCookies::disableFor()`?

### ISSUE THREAD

**Issue by tillkruss** [laravel/framework#10327]
Making `app('App\Http\Middleware\EncryptCookies')` returns a different object each call, so the method [`disableFor()`](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Cookie/Middleware/EncryptCookies.php#L45) can't be called, is that correct?

Or is there a way to access the middleware stack of the current request to call `disableFor()` on the used `EncryptCookies` instance?

**Comment by syaiful6** [comment]
Middleware is run before the request dispatching to your route, so any call to it will too late, by the way if you just want a cokkie name to exclude, just add your cookie name to ```except``` property on ```EncryptCookies``` which live on your app folder (not the one on laravel).

**Comment by tillkruss** [comment]
Context: I'd like to disable *a single* (not all) cookie in a unit test.

**Comment by tillkruss** [comment]
```
$this->app->resolving(EncryptCookies::class, function ($object) {
    $object->disableFor('cookie-name');
});
```
