### ISSUE TITLE
[Proposal] Add a "true" artisan verbose flag or option

### ISSUE THREAD

**Issue by voydz** [laravel/framework#10330]
**Background (probably not that interesting)**: Today I implemented breadcrumbs into one of my laravel projects. To define breadcrumb paths I additionally added a `breadcrumbs.php` file besides my `routes.php` in the `Http` directory and required (`require base_path('..')`) it in the `boot()` method of my `RouteServiceProvider`. While the `breadcrumbs.php` file was empty (just containing `<?php`) every call to artisan generated an `Symfony\Component\Debug\Exception\FatalErrorException` with the message `parse error`.

**The problem**: If you generate any errors in files that are loaded whenever artisan is booted you have a hard time finding that issue, since the default CLI exception renderer displays only the exception's class name and message. At this point the general verbose flag has no impact. (An option would be manipulating the exception handlers `render` method with a `var_dump()` or anything like this whenever such a situation occurs.)

**Possible solution**: Make the verbose flag display the whole exception backtrace to streamline and simplify the debug workflow in such cases.

*I am not quite sure if this is even worth to look at but I found myself quite some times in various cases where artisan stopped working and I had to figure out why.*

**Comment by fgreinus** [comment]
:+1: would be really awesome to have this in order to avoid those messy errors!

**Comment by GrahamCampbell** [comment]
We already have verbosity levels as provided by symfony.

**Comment by GrahamCampbell** [comment]
If you don't like the way cli exceptions are handled, please contact symfony.

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Exceptions/Handler.php#L120

**Comment by voydz** [comment]
You read the whole description I gave? At the point artisan would error, the verbose flag is not even respected. IMHO, it is not even remotely applicable to the way symfony handles its CLI errors, since symfony encapsulates the whole service resolving, while laravel is booting all it's (not defering) service providers.

*This is totally fine*, but as you are developing you touch their logic and produce global errors in the boot sequence of the framework. If you access the app through the browser you get a fine exception + backtrace served and you are able to fix the error immediately. But if you then try to access the app via artisan you are left in the dark. 

And only because of this imparity I came to the conclusion that might be a thing which laravel could easly intercept and handle somewhat differently than symfony.

Not to change your mind, but I felt like you got me wrong.

**Comment by carlosvini** [comment]
For anyone interested, just change your artisan file with this:

```
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$output = new ConsoleOutput;
if (in_array('-v', $argv) || in_array('-vv', $argv) || in_array('-vvv', $argv)) {
  $output->setVerbosity(ConsoleOutput::VERBOSITY_DEBUG);
}

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    $output
);
```

**Comment by GLStephen** [comment]
@carlosvini this is more than a little weird of a thing for Laravel to seem so resistant to fix
