### ISSUE TITLE
Unused write database connections.

### ISSUE THREAD

**Issue by ryannjohnson** [laravel/framework#10337]
Everytime a connection is initiated for any query with seperate read and write hosts, eg:

```php
<?php $user = \App\User::find(1); ?>
```

... a connection is made to the write node. This occurs even when no writing queries are run (including `set names 'utf8'`, etc).

**Comment by crynobone** [comment]
@ryannjohnson Could you test the following config.

```
DB_CONNECTION=mysql::read
```

instead of 

```
DB_CONNECTION=mysql
```

**Comment by ryannjohnson** [comment]
@crynobone Using `::read` could allow me to create a workaround (turn off config caching and detect the uri). However, even when I'm able to get `Illuminate\Database\DatabaseManager::parseConnectionName()` to parse the `::read` correctly, the following queries (and therefore the write connection) is still run:

```sql
execute pdo_stmt_00000001: set names 'utf8'
execute pdo_stmt_00000002: set search_path to "public"
```

Note that I'm using 5.0.

**Comment by GrahamCampbell** [comment]
NB, 5.0 is not supported, but I assume the issue is the same in 5.1.

**Comment by GrahamCampbell** [comment]
Closing due to no response.
