### ISSUE TITLE
[RuntimeException] 

### ISSUE THREAD

**Issue by xuqihua** [laravel/framework#10339]
[RuntimeException]
  Error Output: PHP Fatal error:  Call to undefined method Illuminate\Routing\RouteCollection::refreshNameLookups() in ./vendor/laravel/f
  ramework/src/Illuminate/Foundation/Support/Providers/RouteServiceProvider.php on line 33

**Comment by whoishoward** [comment]
I got the same problem! How did you fix that?

**Comment by GrahamCampbell** [comment]
Maybe clear all the compiled files?

**Comment by whoishoward** [comment]
Cannot use command clear-compiled. It will returns same issues.

**Comment by GrahamCampbell** [comment]
I didn't mean use the command. I meant actually delete the files yourself.

**Comment by GrahamCampbell** [comment]
And, actually that command doesn't even delete all the files I was talking about anyway.

**Comment by xuqihua** [comment]
I forget how to fix it....maybe just re-install run `composer update`

**Comment by whoishoward** [comment]
I solved this issue. Just download the new routing files in this repository and override the old one in your application.
