### ISSUE TITLE
Composer as apart repository

### ISSUE THREAD

**Issue by bobmulder** [laravel/framework#10338]
Hi guys,

I am looking for a way to work with composer in browser. For that I am working on a library where you can update, install and require with.

For example:

```
   $composer->requirePackages(['my/package' => 'dev-master']);
```

I've found this class which could be helpful for me to use: https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Composer.php

I am not working with Laravel itself, but I got the idea to split this class up into a new repository and work it out. I would like to hear from you what you think about it.

Greetz

Bob

**Comment by bobmulder** [comment]
@GrahamCampbell Thank you for your pretty, kind response. I really appreciate your feedback :)

**Comment by GrahamCampbell** [comment]
Please ask on the forums.

**Comment by GrahamCampbell** [comment]
If you want to contact Taylor, please do that directly on slack.
