### ISSUE TITLE
Date values cannot be set to empty string

### ISSUE THREAD

**Issue by hackel** [laravel/framework#10335]
In the last clause of Illuminate\Database\Eloquent\Model::getAttributeValue(), it checks if a date value is empty using `if (! is_null($value))` to determine whether to try to convert it to a Carbon object.  Does this need to be a strict type check?  If I don't set a value for a date form field, it gets saved to the DB anyway, but as an empty string (at least with MongoDB, no strict DB schema).  This method doesn't consider an empty string null, so I get an InvalidArgumentException from Carbon (Data missing) when it tries to convert an empty string into a date.  Changing this test to just `if ($value != null)` or even `if(empty($value))` would solve this problem.  Perhaps this check is better handled in asDateTime()?

Thoughts?  I realize that I can also control what gets written to my DB, and convert from an empty string to a null before I set the attribute.  It just seems like this should be handled automatically.

**Comment by GrahamCampbell** [comment]
Yes, NULL is not the same as empty string in the db.

**Comment by GrahamCampbell** [comment]
Yes, as in, the current behaviour is already correct.

**Comment by GrahamCampbell** [comment]
Empty string should error but null should not.

**Comment by hackel** [comment]
Why should an empty string error out instead of not be converted into a DateTime?  This means I need to take the extra step of manually iterating over my input variables and testing for "" to set them to null.  Is there some advantage to doing strict type checking for null in this instance that I'm not aware of?
