### ISSUE TITLE
Sessions without cookies

### ISSUE THREAD

**Issue by allantatter** [laravel/framework#10349]
Hello,

I'm building an API that will be used by web client, iOS app and Android app. The iOS and Android developer don't want to handle cookies and they would prefer sending an Authorization header (some token) with each request they make to the API but they still like the session to be stored on the API side.

So, I'd like to use the default session functionality provided by Laravel out-of-the-box BUT instead of using 'laravel_session' cookie, the client (web app, mobile app, etc) would send that same hash as an Authorization header and would have to handle storing the token locally itself some other way.

Can I switch to this approach easily and how?

I'm aware of JWT, but this means that the sessions is stored on the client side and has some drawbacks (not pointing out security), although it would make the API stateless. I'd prefer a solution for what I described.

Thanks,
Allan

**Comment by GrahamCampbell** [comment]
Please ask on the fourms.
