### ISSUE TITLE
Relation caching after create

### ISSUE THREAD

**Issue by jlem** [laravel/framework#10344]
This is a bit of a weird bug. The behavior is somewhat unexpected, but understandable after spending time debugging.

Given this model:

```php
class Section extends \Eloquent
{
    protected $table = "ibf_games";
    protected $primaryKey = "ga_id";

    public function league()
    {
        return $this->hasOne(League::class, 'section_id', $this->primaryKey);
    }

    public function enableLeague() 
    {
        if (!is_null($this->league)) {
            throw new Exceptions\LeagueAlreadyEnabledException;
        }

        return $this->league()->create([]);
    }
}
```

If you then call the two methods in this order:

```php
$section->enableLeague();
dd($section->league);
```

You will get `null` for the value of `$section->league`, even though you just created (and yes, the record does get created)

What has happened is you did an initial check for the existence of the league, which was null. Eloquent then automatically cached this result, so the subsequent call to `$section->league` will have the cached value, which is null. This makes sense.

However, it is expected that `$this->league()->create([])` on a one-to-one relationship would purge the relation cache since now a relation has been created, and therefore the relation status has changed.

The work around to this presently is to call `$this->load(['league'])` immediately after the create so as to replace the cache with a new query of the freshly created object.

**Comment by GrahamCampbell** [comment]
Sorry, this is actually the expected behaviour, and you do need to call load, or manually set the relation.

**Comment by jlem** [comment]
It's strange expected behavior for the database representation of a model to be "ahead" of the in-memory representation, when the database change was made *through* the model whose in-memory state is stale.

**Comment by GrahamCampbell** [comment]
I don't think it is, sorry. It's very consistent behaviour, and makes total sense.

**Comment by GrahamCampbell** [comment]
Consistent with the way eloquent works that is.
