### ISSUE TITLE
Query builder "whereDate" with SQL Server

### ISSUE THREAD

**Issue by Eyewash01** [laravel/framework#10343]
If you try and use the query builder whereDate method with an SQL Server connection, it fails, as there is no DATE() function in SQL Server.

Should there not be an override of this in the SqlServerGrammar class - even if it is just to throw an exception stating that this cannot be done on this platform?

**Comment by GrahamCampbell** [comment]
What laravel and sql server version?

**Comment by maddhatter** [comment]
I can reproduce this on Laravel 5.1 (and without testing, it looks like previous version would have the same issue) and SQL Server version won't matter - [T-SQL does not define a date() method](https://msdn.microsoft.com/en-us/library/ms186724.aspx).

I'll send a PR with a fix in a minute

**Comment by GrahamCampbell** [comment]
Thanks.
