### ISSUE TITLE
Add UrlGenerator::share() like View::share()

### ISSUE THREAD

**Issue by pilot911** [laravel/framework#10342]
Hello. I have language locale assigned to many GET routes. I dont want to use "prefix" in routers.
And it's so hard to write in every route() function line in parameters like:

route('named.route', [...., 'locale' => config('app.locale')]);

I just want to have "global" keys (can set them in middleware)

UrlGenerator::share(['locale' => config('app.locale')]);

So route() parameters will filled by UrlGenerator by default.

Think this nice idea.

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by pilot911** [comment]
Why ?

**Comment by GrahamCampbell** [comment]
I don't like the idea...

**Comment by GrahamCampbell** [comment]
Why else?

**Comment by pilot911** [comment]
Why View::share() then ?

**Comment by pilot911** [comment]
so, in hundred routes i should write the same code:
````php
route('named.route', [...., 'locale' => config('app.locale'), ....]);
```

**Comment by HwapX** [comment]
+1

**Comment by lukasgeiter** [comment]
@pilot911 As a simple solution you could just use a custom `route` helper, let's say `locale_route` and call the original route function after adding the current locale to the parameters ;)

**Comment by pilot911** [comment]
use a custom route helper - it's wry solution, i think we should add special method like View::share
