### ISSUE TITLE
[feature-request] Resolve FactoryBuilder from IoC container

### ISSUE THREAD

**Issue by Evertt** [laravel/framework#10350]
I like factories for creating new model-entities with random data. However, I don't use Eloquent, I use Analogue and so I'd like to make an Analogue Factory, but then I'd like to register that Factory in the nice pretty way.

[See here for more information](https://github.com/analogueorm/analogue/issues/64)

**Comment by syaiful6** [comment]
you could do the same way as laravel do, just register your FactoryBuilder to Ioc. OR you could rebinding it of course..

**Comment by Evertt** [comment]
But normally Laravel registers all its services via a contract, right? So then when you build your own package you can simply tell Laravel to use your implementation rather than Laravel's implementation.

[Well here that's not the case.](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Database/DatabaseServiceProvider.php) It seems like Laravel's eloquent factory isn't registered via a contract, but directly and that means I can't just substitute my own package for it.

Of course I can still register my own package and then open all the files in `database_path('factories')` myself, but it's just less neat than the substituting-implementation-of-contract-way.

**Comment by RemiCollin** [comment]
I think what @syaiful6 meant what it should be possible to override the original binding with something like : 

```php
$app->bind(EloquentFactory::class, function($app) {
     return new CustomFactory;
});
```

Is that correct ?

**Comment by syaiful6** [comment]
Yes correct @RemiCollin about rebinding, or just forget it and build your own factory for your entity
