### ISSUE TITLE
Validator | Catch exceptions for Date & Date Format rules 

### ISSUE THREAD

**Issue by werdlv** [laravel/framework#10360]
There might be situations when date based rules are used but the value provided is not a string. Therefore built in functions like:
- date_parse_from_format
- date_parse
- strtotime

will trigger a warning and further on ```Illuminate\Exception\Handler->handleError``` will throw an exception.
I suggest wrapping them in try-catch block and simply return false on exception which clearly means that attribute is not valid against given rule.

**Comment by rkgrep** [comment]
You can pass a `string` rule before your date validation.
