### ISSUE TITLE
Redirect route not found

### ISSUE THREAD

**Issue by PugalAmp** [laravel/framework#10378]
I had use this type Redirect  route method , not found come, Any one help.

public function defaulttemplate(){
	         //TODO: Select emailapp template 
		// $createemail = new CreateEmail;
		 
		  $createemail = CreateEmail::firstOrNew(array('id' => Input::get('lastid')));
		//$createemail->template_id = Input::get('template_id');
		   $createemail->email_name = Input::get('name');
			$createemail->subject_line = Input::get('subject');
			$createemail->save();
        $lastInsertedId= $createemail->id;
		$template_id=  Input::get('id');
		
		return view('emailapp.defaulttemplate')->with (['lastid' =>  $lastInsertedId,'templateid' => $template_id]);

**Comment by busayo** [comment]
You mean you did a `redirect()->route('named-route')-with(['lastid' =>  $lastInsertedId,'templateid' => $template_id])` and it didn't work?

**Comment by PugalAmp** [comment]
yes

**Comment by busayo** [comment]
Did you give it a named route?...and can i see how your `routes.php` file look like?

**Comment by PugalAmp** [comment]
actually i want redirect to another blade with values.

**Comment by PugalAmp** [comment]
sure ill ... 

Route::get('emailapp/defaulttemplate', 'emailapp\EmailappController@defaulttemplate');
Route::post('emailapp/defaulttemplate', array('uses'=>'emailapp\EmailappController@getdefaulttemplate'));

Route::post('emailapp/columnone', array('uses'=>'emailapp\EmailappController@getcolumnone'));
Route::post('emailapp/saved/savenewsletterd',  array('uses'=>'emailapp\EmailappController@savenewsletterd'));

**Comment by PugalAmp** [comment]
in route.php
Route::get('emailapp/defaulttemplate', 'emailapp\EmailappController@defaulttemplate');
Route::post('emailapp/defaulttemplate', array('uses'=>'emailapp\EmailappController@getdefaulttemplate'));

Route::post('emailapp/columnone', array('uses'=>'emailapp\EmailappController@getcolumnone'));
Route::post('emailapp/saved/savenewsletterd',  array('uses'=>'emailapp\EmailappController@savenewsletterd'));

in emailcontroller
----------------------------------
public function defaulttemplate(){
	         //TODO: Select emailapp template 
		// $createemail = new CreateEmail;
		 
		  $createemail = CreateEmail::firstOrNew(array('id' => Input::get('lastid')));
		//$createemail->template_id = Input::get('template_id');
		   $createemail->email_name = Input::get('name');
			$createemail->subject_line = Input::get('subject');
			$createemail->save();
        $lastInsertedId= $createemail->id;
		$template_id=  Input::get('id');
		
		return Redirect::route('emailapp.defaulttemplate')->with (['lastid' =>  $lastInsertedId,'templateid' => $template_id]);  // this line shows error like route(emailapp.defaulttemplate) Not Found
		
		 
    }

**Comment by busayo** [comment]
You didn't give it a named route

**Comment by busayo** [comment]
Route::get('emailapp/defaulttemplate', 'emailapp\EmailappController@defaulttemplate');
Route::post('emailapp/defaulttemplate', array('uses'=>'emailapp\EmailappController@getdefaulttemplate', 'as' => 'emailapp.defaulttemplate'));

**Comment by PugalAmp** [comment]
in route.php i did this code
Route::get('emailapp/defaulttemplate', 'emailapp\EmailappController@defaulttemplate');

**Comment by busayo** [comment]
Route::get('emailapp/defaulttemplate', 'emailapp\EmailappController@defaulttemplate'); should be 

```php
Route::get('emailapp/defaulttemplate', [
  'uses' =>'emailapp\EmailappController@defaulttemplate', 
  'as' => 'emailapp.defaulttemplate'
]);
```

**Comment by PugalAmp** [comment]
yaa its working but parameter values doesnt pass.. its shows error 
ErrorException in 782201ec81afbe40e4d3bcc780d966e9 line 2023: Undefined variable: lastid (View: D:\Apache24\htdocs\Mason_dev\resources\views\emailapp\defaulttemplate.blade.php)

**Comment by PugalAmp** [comment]
in defaulttemplate blade i used code
<input name="lastid" id="lastid" type="text" value="{{$lastid}}"/> 
its does not take this value

**Comment by busayo** [comment]
Really??..that should work just fine

**Comment by PugalAmp** [comment]
but doesnt work.. i think it didnt pass value

**Comment by PugalAmp** [comment]
ya fine its working yar.. thanks a lot.. :) :) :+1:
