### ISSUE TITLE
Using back() in a RESTful destroy() action deletes the parent object too

### ISSUE THREAD

**Issue by mstralka** [laravel/framework#10383]
I have the following domain objects:
* Person
* PhoneNumber

A Person has 0 or many phone numbers, a Phone Number belongs to one person.

I have the following routes defined:
````
Route::resource('people', 'Admin\PersonController'); // for Person objects - /admin/people/{id}
Route::resource('person_phones', 'Admin\PersonPhoneController'); // For Phone objects - /admin/person_phones/{id}
````

When I am on the `people.show` route for any user (`User #1 for example`), I have a button that can delete any of the person's phone number objects.  This button uses jQuery ajax like this:

````
$.ajax({
    url: url,
    type: 'DELETE',
    success: function(data) {
        location.reload();
    }
});
````

In `PersonPhoneController`, my `destroy()` function looks like this:

````
public function destroy(PersonPhoneService $personPhoneService, BaseRequest $request, $id)
{
    $personPhone = $personPhoneService->getById($id);
    $personId = $personPhone->person_id;
    $personPhone->delete();
    return back();
}
````

If I press the button to delete the person's phone number, the Person object is incorrectly deleted too, because the `back()` function is making my browser do a redirect back to /admin/people/1, but with the `DELETE` method instead of the `GET` method.  By default, the back() function is using status code `302`.  If I change it to status code `303`, then the parent object is not deleted (correct behavior):
````
return back(303);
````

I know I can check the type of request and return a JSON response instead to jQuery, and only redirect back to a URL if the user made a regular HTTP request, but I thought I should raise this as a potential bug or at least a gotcha.

Reading the [HTTP spec for the 303 code](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.3.4):
> The response to the request can be found under a different URI and SHOULD be retrieved using a GET method on that resource. This method exists primarily to allow the output of a POST-activated script to redirect the user agent to a selected resource. The new URI is not a substitute reference for the originally requested resource. The 303 response MUST NOT be cached, but the response to the second (redirected) request might be cacheable.
The different URI SHOULD be given by the Location field in the response. Unless the request method was HEAD, the entity of the response SHOULD contain a short hypertext note with a hyperlink to the new URI(s).

**Comment by GrahamCampbell** [comment]
Please ask on the forums. This looks more like your usage is wrong.
