### ISSUE TITLE
pingBefore and thenPing prevent the scheduled jobs from running in parallel

### ISSUE THREAD

**Issue by lasselehtinen** [laravel/framework#10389]
Hi,

I have scheduled a few jobs to be triggered at the same time with cronitor.io callbacks before and after the job. It seems like if you define either pingBefore or thenPing, jobs scheduled at the same time won't run in parallel but instead wait until the first job is finished. Without those two  all jobs immediately go to the background.

    $schedule->command('foo:bar1')->daily()->pingBefore('https://cronitor.link/abc/run')->thenPing('https://cronitor.link/abc/complete');
    $schedule->command('foo:bar2')->daily()->pingBefore('https://cronitor.link/def/run')->thenPing('https://cronitor.link/def/complete');

After running php artisan schedule:run

    Running scheduled command: /usr/bin/php5 "artisan" foo:bar1 > /dev/null 2>&1 &

It waits until the first job is finished and then moves to the next one. If I remove the pingBefore and thenPing both jobs are launched to the background instantly. In my case the jobs take very long time to run so I would naturally like to run them in parallel. Naturally this happens only if jobs are triggered on the same schedule:run. As a workaround, I have adjust scheduled jobs to run on separate minutes.

Is this intentional or not?

**Comment by GrahamCampbell** [comment]
Yes.

**Comment by lasselehtinen** [comment]
Could you elaborate why this is intentional? For me it seems quite counter intuitive that adding a ping before or after the job causes prevents it from running in parallel.

**Comment by KerryJones** [comment]
Anymore on this?
