### ISSUE TITLE
Undefined model attributes should throw an exception instead of returning NULL.

### ISSUE THREAD

**Issue by chamby** [laravel/framework#10382]
Currently, trying to access `$model_obj->nonexistant_attribute` will simply return `NULL`. I think that a model, after exhausting all possible attribute lookups and relationships in `getAttribute()`, should throw an exception. I have been caught several times trying to debug unexpected behavior related to trying to access attributes that did not exist. This could happen for something as simple as a typo. PHP does not have an `undefined` value like JavaScript, and `NULL` should not be used since legitimate values can be set as `NULL` for reasons other than being undefined.

**Comment by GrahamCampbell** [comment]
> Undefined model attributes should throw an exception instead of returning NULL.

Sorry, no they shouldn't.

**Comment by chamby** [comment]
If you are defending that implementation, that is fine. But, how can I use the framework to the differentiate between a `NULL` value and an attribute that doesn't exist? I can't find a method like `hasAttribute()` on the model, and `$attributes` is protected for me to run `array_key_exists()` myself.
