### ISSUE TITLE
[5.1] The New Fluent Routing Interface doesn't work with Named Routes in Route Groups

### ISSUE THREAD

**Issue by zlatevbg** [laravel/framework#10380]
The old syntax (not fluent) is working fine:

```
Route::group(['as' => 'users.'], function() {
    Route::get('admins', ['as' => 'admins', 'uses' => 'UserController@admins']);
});
```
The result of `php artisan route:list` is:

| Domain            | Method   | URI          | Name         | Action                                     |
|-------------------|----------|--------------|--------------|--------------------------------------------|
| www.laravel.local | GET HEAD | users/admins | **users.admins** | App\Http\Controllers\UserController@admins |

The new syntax (fluent) doesn't work:
```
Route::group(['as' => 'users.'], function() {
    Route::get('admins', 'UserController@admins')->name('admins');
});
```
The result of `php artisan route:list` is:

| Domain            | Method   | URI          | Name         | Action                                     |
|-------------------|----------|--------------|--------------|--------------------------------------------|
| www.laravel.local | GET HEAD | users/admins | **admins** | App\Http\Controllers\UserController@admins |

**Comment by taylorotwell** [comment]
Fixed.
