### ISSUE TITLE
Form request object attribute returns empty when have some string

### ISSUE THREAD

**Issue by kneipp** [laravel/framework#10403]
Hello,
Is this correct? I was validating an image when this happens:

    public function store(Requests\FormRequest $request)
    {
        var_dump($request->image); // #1
        var_dump(empty($request->image)); // #2
        die;

    public function store(Requests\FormRequest $request)
    {
        $t = $request->image;
        var_dump($t); // #1
        var_dump(empty($t)); // #3
        die;

#1 ~/work/vila/app/Http/Controllers/FormController.php:53:string 'Screen Shot 2015-09-25 at 06.49.32.png' (length=38)
#2 ~//work/vila/app/Http/Controllers/FormController.php:55:boolean true
#3 ~/work/vila/app/Http/Controllers/FormController.php:55:boolean false

**Comment by GrahamCampbell** [comment]
Yes.

**Comment by kneipp** [comment]
Why string attributes returns empty when is not empty on Laravel Form Request Object?

**Comment by beeblebrox3** [comment]
When you do `$request->image` you are calling the `__get` method from `Request` and getting the returned value. The `empty` function only works with variables (php.net/empty).

**Comment by kneipp** [comment]
Hey @beeblebrox3 thx for reply, btw testing this again work like expect with pure php (5.6):
    public function test()
    {
        return 'b';
    }
var_dump(empty($this->test())); #bool(false)

**Comment by beeblebrox3** [comment]
Yeah, sorry about that.

Look this gist: https://gist.github.com/beeblebrox3/0b5c2efd176ce3c4370e
When I do `empty($obj->a)`  the `__get` method is not called. 

Technically, `$obj->a` doesnt exists, so `empty` will return true

**Comment by rentalhost** [comment]
@GrahamCampbell Look, it's really a Laravel bug. When you do `empty($instance->property)` it will check first for `__isset()` method on `$instance` and after for `__get()` method.

In this case, nether `FormRequest` or `Request` or `ArrayAccess` defines the `__isset()` method. And it is needly to it works. And considering that you are working with a FormRequest, you should be capable to do it.

Currently you should "hack" to make it works property, by two ways (but not that it's a workaround):

- Copying attribute to variable: `$value = $instance->value;` then `empty($value)`
- Force casting to jump over `__isset()`: `empty( (string) $instance->value )`

**Comment by kneipp** [comment]
Not sure it's laravel bug: https://gist.github.com/kneipp/aee5802d08505d605676

**Comment by rentalhost** [comment]
Yes, it's. Note that empty() fail on line 16 because you not have defined the method __isset(). And empty() will first try call __isset() and, only if it returns true, __get() will be called.

Try to define this method and you will see that __get() will be called as should be expected.

**Comment by kneipp** [comment]
Yea, we're right it's a laravel bug.
