### ISSUE TITLE
Laravel DB::TABLE()->SELECT overwrite selected tables

### ISSUE THREAD

**Issue by raaaas** [laravel/framework#10411]
hello , 

i got this query 

"
$posts = DB::table('posts')->Select('*', 'users.name as uname')->leftJoin('users','users.id','=','posts.user_id')->where('type','futured')->get();
"
return => 
"
and its return Array ( [0] => stdClass Object ( [id] => 1 [name] => test [user_id] => 1 [slug] => Ø§ÙˆÙ„ÛŒ [latitude] => 35.790986 [longitude] => 51.416320 [address] => 5 no , jafar abad [start] => 1394-06-01 [finish] => 1394-06-02 [description] =>

asd
[media] => [counter] => 100 [likes] => 54 [type] => futured [created_at] => 2015-09-06 09:43:42 [updated_at] => 2015-09-06 11:10:11 [brand] => [ader] => [facebook] => [googlep] => [instagram] => [pinterest] => [linkdin] => [logo] => http://localhost:8000/asstes/dist/img/user2-160x160.jpg [brandlogo] => [email] => test@test.com [phone] => 0 [password] =>  [remember_token] =>  [role] => admin [uname] => test ) [1] => stdClass Object ( [id] => 1 [name] => test [user_id] => 1 [slug] => Ø³ÙˆÙ…ÛŒ [latitude] => [longitude] => [address] => [start] => 1394-06-08 [finish] => 1394-06-22 [description] =>

tetetetet
[media] => [counter] => 0 [likes] => 0 [type] => futured [created_at] => 2015-09-06 09:43:42 [updated_at] => 2015-09-06 11:10:11 [brand] => [ader] => [facebook] => [googlep] => [instagram] => [pinterest] => [linkdin] => [logo] => http://localhost:8000/asstes/dist/img/user2-160x160.jpg [brandlogo] => [email] => test@test.com [phone] => 0 [password] =>[remember_token] => [role] => admin [uname] => test ) [2] => stdClass Object ( [id] => 1 [name] => test [user_id] => 1 [slug] => Ú†Ù‡Ø§Ø±Ù…ÛŒ [latitude] => [longitude] => [address] => [start] => 0000-00-00 [finish] => 0000-00-00 [description] => [media] => [counter] => 0 [likes] => 0 [type] => futured [created_at] => 2015-09-06 09:43:42 [updated_at] => 2015-09-06 11:10:11 [brand] => [ader] => [facebook] => [googlep] => [instagram] => [pinterest] => [linkdin] => [logo] => http://localhost:8000/asstes/dist/img/user2-160x160.jpg [brandlogo] => [email] => test@test.com [phone] => 0 [password] =>  [remember_token] =>  [role] => admin [uname] => test ) [3] => stdClass Object ( [id] => 2 [name] => testmon1 [user_id] => 2 [slug] => Ø¯ÙˆÙ…ÛŒ [latitude] => [longitude] => [address] => [start] => 0000-00-00 [finish] => 0000-00-00 [description] => [media] => [counter] => 0 [likes] => 0 [type] => futured [created_at] => 0000-00-00 00:00:00 [updated_at] => 2015-09-22 13:50:50 [brand] => koko@aaa.com [ader] => [facebook] => [googlep] => [instagram] => [pinterest] => [linkdin] => [logo] => /uploads/arch/1442929850123.png [brandlogo] => [email] => Test@test1.com [phone] => 321312 [password] => 1234 [remember_token] => [role] => arch [uname] => testmon1 ) ) 
"

which overwritten 'name' by 'uname' and return same data  ('test')

but in pma i got right return  

for fixing this i added another part 

		$posts = DB::table('posts')->Select('*', 'users.name as uname','posts.name as pname' )->leftJoin('users','users.id','=','posts.user_id')->where('type','futured')->get();

which i think its not necessary

**Comment by rentalhost** [comment]
I don't understand well what do you mean here.

1. What do you expect to receive?
2. What do you received instead?

**Comment by raaaas** [comment]
i have 2 name in 2 diffrent tables, 

i want to get both names because 2 of them have same name i could not get them by * so i need change one name to (AS) hname  so i could get both of them,

my query runs well on mysql(PMA) but when i want to exceute same mechanic (query) with laravel 
one name overwrite other name and change it 

( [0] => stdClass Object ( [id] => 1 [name] => test  [uname] => test ) which is wrong

**Comment by rentalhost** [comment]
It's normal. You do "*", it'll get all data about "from" and all "joins". What you can do is specify from where you will get "*" data, for instance:

`select("users.*", "posts.name as pname")->from("users")->join(...)`

But the right way to do what you want, maybe is use Eloquent Relations, so you will not need to use `as`, and it'll works like it (example):

```
$users = User::all();
$users[0]->post->name;
```

**Comment by rkgrep** [comment]
I think this should be closed, as it is intended behaviour.
