### ISSUE TITLE
[Proposal] Add an @embed tag to Blade

### ISSUE THREAD

**Issue by whipsterCZ** [laravel/framework#10415]
Hi.

i thing it would be great to add `@embed` directive, which is well know from TWIG
http://twig.sensiolabs.org/doc/tags/embed.html

It is basically way to use layouts inside @sections.it helps to do shorter blade templates

usage
-----------
~~~~~ php
@section('content')
    ....
    @embed('layout.box')
        @section('title','My form')
        @section('body')
             @include('my._form')
         @endsection
    @endembed
  
@endsection
~~~~~

~~~~~ php
layout.box.blade
<div class="box">
      @if ($__env->yieldContent('title',false))
            <div class="ibox-title">
                  <h2>@yield('title')</h2>			
            </div>
      @endif	
      <div class='toolbar'>...</div>
      <div class="body">
            @yield('body')
      </div>
      <div class='footer'>...</div>
</div>
~~~~~

Requirements
  -  global blade **variables whould be accessible** inside @embed
  -  it would be nice if i can define @section in @embed -  for example `@section('scripts')` to have opportunity, to add some `<scripts>` from inside my `_form.blade.php` template  
    - this could be tricky - i know..

Thank you. And many thanks for Laravel Framework - it is masterpeace

**Comment by BrandonSurowiec** [comment]
You can use this package for the **@embed** feature. It would be cool to have it native in Laravel though :+1: 

https://github.com/RobinRadic/blade-extensions

**Comment by GrahamCampbell** [comment]
We do not process proposal issues.

**Comment by whipsterCZ** [comment]
https://github.com/RobinRadic/blade-extensions doesn't work properly.
IMHO `@embed` is must have feature.. So it should be available out of the box...

Nette, Symphony2, Yii &Zend has it :)
