### ISSUE TITLE
need for different $dateFormat for database storage vs. serialization as array/JSON (eloquent date mutators)

### ISSUE THREAD

**Issue by hartmut-ltd** [laravel/framework#10414]
Hi,

we would like to make use of Eloquent date mutators
http://laravel.com/docs/5.1/eloquent-mutators#date-mutators

in the way to store our dates as UTC to our mysql database (default)
while we would like to have them formatted as ISO8601 for JSON serialisation => REST API responses..

At the moment this is not possible for the same property $dateFormat is used for both serialisation types (db | array). What about having the option to define one date format each way?

Thanks

**Comment by bencorlett** [comment]
In your example, would you be able to get away with get/set mutators instead?

**Comment by GrahamCampbell** [comment]
Yeh, I think you would.

**Comment by hartmut-ltd** [comment]
Ah nice! Still needs adding additional functions for each date / datetime property then but can confirm it's working.

Thanks!

**Comment by davesouthey** [comment]
I am working on a API built with Laravel which uses dates extensively. Currently I use $dateFormat to define the storage format, as UTC, for the database. This means I have to add lots of get mutators to the models to handle the date to JSON conversion. Is there a nicer way of doing this?

The relevant columns are already listed in the $dates array, in the models, and so I can't help but think that we can come up with a way to set a default format to use for all $dates columns when serializing to JSON.

**Comment by hartmut-ltd** [comment]
Hi, 

please note another issue I've had with defined getters:
once getters are in place, you can't access your dates as Carbon objects anymore, for any access on the attribute
```
$model->my_date
$model->getAttribute('my_date')
```
will return the formatted date (as defined in getter).

So we ended up with parsing them again to Carbon for diffs, .... -> a lot of additional date parsing and formatting...

@davesouthey: you may provide the setters by a Trait. 
[ModelISO8601Trait.php.txt](https://github.com/laravel/framework/files/38195/ModelISO8601Trait.php.txt)
