### ISSUE TITLE
Overridden core class does not work when in artisan

### ISSUE THREAD

**Issue by Propaganistas** [laravel/framework#10439]
Hi

In a fresh Laravel build, I cannot get overridden IoC bindings to work everywhere in the application.

Suppose a service provider that overrides a core class, e.g. cache:

```php
class NewServiceProvider extends ServiceProvider
{
    protected $defer = true;

    public function register()
    {
        $this->app->bind('cache', function($app) {
        	return new \stdClass; // demo purpose
        });
    }

    public function provides()
    {
    	return ['cache'];
    }
}
```

The provider is then added at the bottom of `app.providers` config.

Now modify `routes.php` to the following and go check the result:
```php
Route::get('/', function () {
    dd(app('cache'));
});

// Results in an empty stdClass being shown. It works!
```

However, fire up `artisan tinker` and do the same:

```php
$ php artisan tinker
>>> app('cache')
=> Illuminate\Cache\CacheManager
```

Suddenly the override isn't working anymore...

The same behavior is encountered when processing event listeners...

Is this normal behavior and am I overlooking something? Or is this some kind of bug?

**Comment by GrahamCampbell** [comment]
Please ask on the fourms.

**Comment by Propaganistas** [comment]
Well, since it could be a bug I'd thought to post it over here..

Anyhow:
http://laravel.io/forum/10-01-2015-overridden-core-class-does-not-work-when-in-artisan

**Comment by Propaganistas** [comment]
I'm sorry to reopen this issue @GrahamCampbell but after some more digging I'm quite convinced this is a bug in the framework...
