### ISSUE TITLE
[5.1] Make Frontend Tests Portable

### ISSUE THREAD

**Issue by amenk** [laravel/framework#10440]
In 5.1 you have to define a front-url for testing.

See:

https://github.com/laravel/framework/issues/9156
https://github.com/laravel/docs/pull/1534

Hardcoding causes problems when working on different machines. I would like to read that info from `.env`.
What do you think about adding to following code to the frontend tests?

    public function __construct($name = null, array $data = array(), $dataName = '')
    {
        parent::__construct($name, $data, $dataName);
        $this->createApplication();
        $this->baseUrl = env('TEST_BASE_URL', 'http://localhost');
    }

**Comment by GrahamCampbell** [comment]
You can do this yourself in your app.

**Comment by amenk** [comment]
I know and I did. But we aim to have a developer-friendly framework that just work's, don't we?
Please reopen.

**Comment by GrahamCampbell** [comment]
I don't think this needs changing. It's already fine, and I think the behaviour your suggesting would be wrong.

**Comment by amenk** [comment]
I just don't like to have an URL in the code. That is why I am using env. But I am not happy which initializing the application via createApplication()
