### ISSUE TITLE
Union and Union All issue when a table has a join or leftJoin function with additional where clause

### ISSUE THREAD

**Issue by Al3xR0** [laravel/framework#10451]
Issue tested on v5.1.17 and v5.1.18

I have this scenario tested on different tables and variables

    $table1 = DB::table('users')
            ->groupBy('users.id')
            ->select('users.id');

    $table2 = DB::table('users')
            ->leftJoin('user_devices', function ($join)
            {
                $join->on('user_devices.user_id', '=', 'users.id')
                    ->where('user_devices.type', '=', 1);
            })
            ->groupBy('users.id')
            ->select('users.id');

    return $table1->unionAll($table2)->get();

This example will work only if I inverse tables when I create the union:

    $table2->unionAll($table1)->get();

If I want to union $table1 with $table2 I have to remove the where clause from the join function:

    ->where('user_devices.type', '=', 1);
otherwise will give me this error

```
1/2
PDOException in Connection.php line 312:
SQLSTATE[HY000]: General error: 2031

2/2
QueryException in Connection.php line 636:
SQLSTATE[HY000]: General error: 2031 (SQL: (select `users`.`id` from `users` group by `users`.`id`) union all (select `users`.`id` from `users` left join `user_devices` on `user_devices`.`user_id` = `users`.`id` and `user_devices`.`type` = ? group by `users`.`id`))
```

If I execute the SQL query from the error it works perfect.

On another scenario based on the same where clause in the join function I receive this error

```
1/2
PDOException in Connection.php line 312:
SQLSTATE[HY093]: Invalid parameter number

2/2
QueryException in Connection.php line 636:
SQLSTATE[HY093]: Invalid parameter number (SQL: (select .........
```

**Comment by acasar** [comment]
Experienced the same problem several times. Looks like join bindings don't get merged properly on unions.
