### ISSUE TITLE
Replacing type hints from Closure to callable

### ISSUE THREAD

**Issue by vlakoff** [laravel/framework#10450]
(and of course `$callback()` to `call_user_func($callback)`)

Similar work already done in #7566.
Searching `(Closure $` in the codebase, I'm currently getting 48 results. Looks like the change would sometimes be useful (e.g. in `Query\Builder::whereExists()`, `Log\Writer::listen()`...)

We should determine where it is appropriate to do the replacement, and more importantly, where `Closure` should be kept.

ping @JosephSilber :)

**Comment by GrahamCampbell** [comment]
Duplicate.

**Comment by GrahamCampbell** [comment]
See https://github.com/laravel/framework/issues/9565.
