### ISSUE TITLE
Use a polyfill for random_bytes() and random_int() in PHP < 7

### ISSUE THREAD

**Issue by paragonie-scott** [laravel/framework#10465]
Hi Laravel team,

I previously emailed @taylorotwell asking if there was any interest in a standard polyfill for `random_bytes()` and `random_int()` for PHP 5 projects.

I just wanted to let everyone know that [random_compat](https://github.com/paragonie/random_compat) is stable, if you would like to hammer at it and then deliberate whether or not to adopt it, please do.

Of interest, [ERRATA.md](https://github.com/paragonie/random_compat/blob/master/ERRATA.md) and [PHP bug 70014](https://bugs.php.net/bug.php?id=70014) are worth a read before anyone says, "Why don't we just use `openssl_random_pseudo_bytes()`?"

**Comment by rentalhost** [comment]
Do you mean add this polyfill as a Laravel helper? If you do, I guess that you created a good helper, but Laravel don't will need it as helper, each user can require it individually when it be needs.

**Comment by GrahamCampbell** [comment]
Feel free to open a PR.

Also, please note that we do no process proposal issues on GitHub. Please contact Taylor on slack if you have any questions.

**Comment by taylorotwell** [comment]
Who has reviewed this library for correctness?

**Comment by GrahamCampbell** [comment]
Ping @ircmaxell for advice regarding security. :)

**Comment by ircmaxell** [comment]
Hey, sorry for the delay in response.

`random_compat` as made by `paragonie` has been reviewed multiple times (by me, and others). I would definitely recommend it.

**Comment by GrahamCampbell** [comment]
Thanks @ircmaxell. :)

**Comment by paragonie-scott** [comment]
> Feel free to open a PR.

Sure thing, but to clarify, this should target 5.1, right? It won't introduce any backward incompatibilities (other than those that should already be remediated by `composer update`).

**Comment by GrahamCampbell** [comment]
Please target at 5.2. I've just talked to Taylor about this.

**Comment by GrahamCampbell** [comment]
Unless there is a really good reason why you think the 5.1 implementation is unsuitable for use. :)

**Comment by paragonie-scott** [comment]
See #10499
