### ISSUE TITLE
FactoryBuilder Exception not very helpful

### ISSUE THREAD

**Issue by Sladewill** [laravel/framework#10460]
This error below is not very useful

> InvalidArgumentException: Unable to locate factory with name [default].

FactoryBuilder.php line 127

```php
throw new InvalidArgumentException("Unable to locate factory with name [{$this->name}].");
```
now if it also told you the class name in the exception then it would be more useful, what do you think?

```php
 throw new InvalidArgumentException("Unable to locate factory with name [{$this->name} {$this->class}].");
```

**Comment by GrahamCampbell** [comment]
Sure. Please open a PR. :)
