### ISSUE TITLE
the error message needs to be changed(Whoops, looks like something went wrong).

### ISSUE THREAD

**Issue by nurettintopal** [laravel/framework#10466]
Hi,

We all know the famous error message "Whoops, looks like something went wrong". I think this message needs to be changed. Therefore, you should use a template in the views folder(such as 500.blade.php or 404.blade.php). In this way, you can change this message and template when you want.

This is not a personal request. Just a suggestion for a more flexible structure.

![screen shot 2015-10-03 at 11 18 48](https://cloud.githubusercontent.com/assets/1067132/10262059/9c116fe0-69c0-11e5-92e3-01e7d5e0cf16.png)

Thanks.
Nurettin

**Comment by GrahamCampbell** [comment]
Already possible.

**Comment by lukasgeiter** [comment]
A quick search in the documentation and you would have found this: http://laravel.com/docs/5.1/errors#http-exceptions

**Comment by GrahamCampbell** [comment]
Alternative, just read the source code. I always find that more useful.

**Comment by ryancwalsh** [comment]
It took me forever to figure out a proper way to override that message. Here is the answer: http://stackoverflow.com/a/41753753/470749
