### ISSUE TITLE
Seeding a single table

### ISSUE THREAD

**Issue by Yannik** [laravel/framework#10470]
In http://laravel.com/docs/5.1/seeding#running-seeders, it is recommended to have a single 'DatabaseSeeder' class, which calls the other table-specific seeders like this:
```
/**
 * Run the database seeds.
 *
 * @return void
 */
public function run()
{
    Model::unguard();

    $this->call(UserTableSeeder::class);
    $this->call(PostsTableSeeder::class);
    $this->call(CommentsTableSeeder::class);
}
```
(Source: http://laravel.com/docs/5.1/seeding#calling-additional-seeders, https://github.com/laravel/laravel/blob/v5.1.11/database/seeds/DatabaseSeeder.php)

On the same documentation page, it is also recommended to run individual seeders like this: ```php artisan db:seed --class=UserTableSeeder```.

Now, if the Model that is being seeded has any non-fillable (guarded) fields, this is gonna result in database entries with empty fields, even though they were passed to Model::create when calling a individual seeder. 
Either, Model::unguard() and Model::reguard() should be called in the individual seeders, or there should be something like a preSeed() postSeed() method. Else, this is very confusing as calling a individual seeder results in empty fields.

Here is an example with a failing test:

```
class User extends Model
{
    protected $table = 'users';

    protected $fillable = ['username', 'email', 'password'];
}
```
```
class UserTableSeeder extends Seeder {

    public function run() {

        User::create(array(
            'username' => 'abc',
            'password' => 'def',
            'firstname' => 'Svea'
        ));
    }
}


```
```
class testSeeds {
    //this succeeds
    public function testAllSeeds() {
        Artisan::call('db:seed');
        $this->assertNotEmpty(User::find(1)->firstname)
    }

    //this fails
    public function testSpecificSeed()
    {
        Artisan::call('db:seed --class=UserTableSeeder');
        $this->assertNotEmpty(User::find(1)->firstname)
    }
}

```

**Comment by rkgrep** [comment]
Ping @Yannik @GrahamCampbell 
This is fixed.
