### ISSUE TITLE
url(), action() helpers ignoring https.

### ISSUE THREAD

**Issue by shazamjad** [laravel/framework#10486]
A small issue that's cropped up now that I've just installed SSL - I'm finding the `action()` and `url()` helpers in views still provide `http` instead of the `https` - the site is only accessible right now via https.

Is there a setting I've overlooked or something more I need to do to enforce https url's?

I'm on a bog standard Laravel install; just ran `composer update` to the latest versions of everything.

**Comment by GrahamCampbell** [comment]
Likely you haven't set up the trusted proxies correctly.

**Comment by GrahamCampbell** [comment]
Feel free to google that. There's plenty of resources for it once you know what you're looking for. :)

**Comment by shazamjad** [comment]
Yup that was it! Just set it up and works like a charm, thanks! :)
