### ISSUE TITLE
Why treat an unauthenticated user so different from an authenticated one? Why not treat it as a user with role "guest" ?

### ISSUE THREAD

**Issue by Evertt** [laravel/framework#10488]
As I explained on [reddit](https://www.reddit.com/r/laravel/comments/3ncm7j/why_treat_an_unauthenticated_user_so_different/), treating an unauthenticated user as a user with role "guest" allows one to easily dynamically add / remove permissions to it, just like with authenticated users. And you can then use the same auth-checking code everywhere:

```php
$user->can('view', $entity);
```

I want to check with this community, would you guys like it if in a next release this is implemented in a Taylor-style fashion?

**Comment by crynobone** [comment]
> I want to check with this community, would you guys like it if in a next release this is implemented in a Taylor-style fashion?

Not really appreciate such a huge breaking change on the next minor release.

**Comment by GrahamCampbell** [comment]
We don't process proposals here. Bugs only.

**Comment by Evertt** [comment]
Where do proposals go?

**Comment by ibrasho** [comment]
Submit a PR if you have a proposal.

**Comment by GrahamCampbell** [comment]
Sorry if our contribution docs aren't clear. Feel free to discuss proposals on slack and/or sent a partially completed PR so Taylor can review the idea.
