### ISSUE TITLE
How about filtering the path when using `active_url` validation?

### ISSUE THREAD

**Issue by skys215** [laravel/framework#10482]
Hi,
   There's a field in my form which requires an URL, it passes the url validation, but it doesn't pass the active_url validation. Because it uses checkdnsrr php function to check the activity.
   The problem is, the input from the form could be an URL with path, like http://www.google.com/test.txt. But checkdnsrr just need host as the first argument.
   So how about using parse_url php function and get the host to use it in checkdnsrr?

   If it's not a good idea, are there any way to do it in my Request file?

Thanks.

**Comment by GrahamCampbell** [comment]
Please direct questions to the forums and proposals directly to Taylor.

**Comment by skys215** [comment]
Sorry..
