### ISSUE TITLE
Misusing @stop (@endsection) tag causes headers and content to be sent immediately and stop buffering.

### ISSUE THREAD

**Issue by m00t** [laravel/framework#10491]
When you write this
```
@section('name', 'content')
@stop
```
Then @section doesnt do ob_start(), but @stop does ob_end_clean(), so output buffering becomes closed and bad things happen which are extremely hard to debug.

**Comment by GrahamCampbell** [comment]
Not that much we can really do here. We'd be open to PRs if you can think of something though. :)
