### ISSUE TITLE
ServiceProvider boot() method optimization

### ISSUE THREAD

**Issue by a-komarev** [laravel/framework#10492]
Hello, guys!

Because that all code inside ServiceProviders boot() methods is calling all the time in all requests, it even trying to publish migrations, configs and in some of packages it doing some kind of preparations of files before publishing or doing other stuff which isn't needed for production usage and should be used only in console. Am I missed something?

If it's true, what do you think about optimization of this behaviour by adding a helper methods to separate blocks on code for only console usage in boot method or at least write about it in documentation. Because I haven't seen any kind of checks for such thing in any of packages I've used recently.

**Comment by brunogaspar** [comment]
You can pretty much check if the app is running on console or not but doing something like

```php
if ($this->app->runningInConsole()) { 
   // stuff that should run only on console here 
}
```

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/spark/blob/master/app/Providers/SparkServiceProvider.php#L59

**Comment by GrahamCampbell** [comment]
If you want an example.

**Comment by a-komarev** [comment]
Thanks for the publishing solution. I mean that maybe it would be good to have this recommendation in official documentation? Because most of the packages don't have it. It could be helpful to make custom packages better.
