### ISSUE TITLE
CacheRepository will discard puts with expiration < 1 minute

### ISSUE THREAD

**Issue by sfudeus** [laravel/framework#10504]
The put interface for the CacheRepository allows to give minutes (as int) or a DataTime object to define the expiry of the cache item. When giving a DateTime object (e.g. using Carbon), which is less than 1 minute in the future, the cache entry will (unexpectedly) not be done, since the timestamp is transformed to "minutes in the future" again and 0 is considered null, which leads to skipping the write operation. 

There was a report (#2954) on a similar issue a while ago (in Laravel 4), which was marked as "fixed". 
I understand the API does define "int" and by that describe that smaller values are not usable - but in parallel a DateTime object is allowed and there is no documentation stating that small expiration are not unsupported. Caching for a small amount of time and not caching at all can make a large difference.

**Comment by GrahamCampbell** [comment]
This is known, and expected I'm afraid.

**Comment by sfudeus** [comment]
Any chance of switching to DateTime being the authoritative source for the expiration and enhancing the cache drivers to support that?

**Comment by GrahamCampbell** [comment]
Please direct all proposals at Taylor on slack.

**Comment by GeeH** [comment]
Currently, this does a NOOP when the optional parameter `$minutes` in `put` is not passed. Either `$minutes` should be a required parameter (as it is in the `Store` interface that the adapters use), or should throw an exception if it's not a valid parameter. Silently doing a NOOP is not great IMO.
