### ISSUE TITLE
snake_case with space as delimiter does not work properly

### ISSUE THREAD

**Issue by marcostvz** [laravel/framework#10509]
I'm migrating the code from 4.2 to 5.1 and I've noticed that the helper function snake_case does not work nice with space as delimiter, instead it ignores them.

Ie:
```
snake_case('aSimpleExample', ' '); // should return 'a simple example', but it returns 'asimpleexample'
```

**Comment by dwightwatson** [comment]
Looks like this was introduced in 5.1, see #9535.

**Comment by marcostvz** [comment]
:+1: Thanks so much! :)
