### ISSUE TITLE
ValidatesRequests Question.

### ISSUE THREAD

**Issue by brunocascio** [laravel/framework#10518]
Hi taylor and laravel's devs.

I tried to install the package `illuminate/foundation` for using `ValidatesRequest` trait , but outside of laravel. I'm creating a microframework for my studies, and i will like do use laravel validators.
Is it possible?

I tried add this as composer dependence, but doesn't work (access right error):
```
require: {
 "illuminate/foundation": "*",
}
```

Thanks!

**Comment by GrahamCampbell** [comment]
> illuminate/foundation

This package doesn't exist in L5. Please don't try to use it.

**Comment by GrahamCampbell** [comment]
The foundation stuff is only available in a full framework install.

**Comment by brunocascio** [comment]
ok, thanks!

**Comment by GrahamCampbell** [comment]
If you do want to copy/paste that class, please make sure you distribute laravel's license and link to it in the file, and you're all good.
