### ISSUE TITLE
How to not allow null when validating input

### ISSUE THREAD

**Issue by jchamberlain** [laravel/framework#10517]
Sometimes I have optional fields that, if sent by the client, can't be null. For example, let's say I have a column in the database defined as `count INT(11) NOT NULL DEFAULT 0`. It's optional and defaults to zero, but my app only accepts integers from the client. Laravel's validation has no way to express that. A simple `"integer"` rule will let `null` pass right through, but `"required|integer"` will make it always required.

I would like the `integer` rule to complain that `null` is not an integer. What are the odds of a PR being acceptable?

**Comment by GrahamCampbell** [comment]
Please direct all questions to the forums.

**Comment by jchamberlain** [comment]
Let me restate this: there's a bug in the validator. I want it fixed.

**Comment by GrahamCampbell** [comment]
No bug.

**Comment by GrahamCampbell** [comment]
You need to drop `required`.

**Comment by GrahamCampbell** [comment]
Or implement a custom validation rule.

**Comment by jchamberlain** [comment]
:p Excuse me? Did you read what I wrote?

**Comment by GrahamCampbell** [comment]
Yes, I did. I've seen this issue before, in my own code too.

**Comment by jchamberlain** [comment]
I don't mean to be rude, but have tried you implementing a custom validation rule for this? In case you're wondering, it won't get past `Illuminate\Validation::presentOrRulesImplicit()`. There's even an undocumented rule called "fillable" that doesn't work because of that. I can open a new issue if you like an explicitly state that the failure to call `validateFillable()` is a bug.

**Comment by jchamberlain** [comment]
To be clear, after reading `Illuminate\Valdation`, I now know that I should be able to use the rule "integer|filled", but that fails because of how `Illuminate\Validation::presentOrRulesImplicit()` is implemented.

**Comment by GrahamCampbell** [comment]
Meh. Reopening this to see what the community says. If there is no response a month, this issue may be closed again. Laravel's issues are here for the community rather than to be addressed by Taylor. Hopefully this was made clear in the contribution guide lines.

**Comment by jchamberlain** [comment]
Gotcha. Sorry, I haven't read the guidelines in several months.

**Comment by jchamberlain** [comment]
So I just re-read the docs on the subject and now see that the combination of "sometimes" and "required" meets my immediate need, e.g., "integer|required|sometimes". (I mistakenly thought "sometimes" required a callback.) It also does what the broken "filled" rule was intended to do. My apologies for not reading the docs more thoroughly.

That said, there are other cases in which I need an actual "not null" type of rule (e.g., for strings), so I will open a PR for that.

**Comment by ddctd143** [comment]
@jchamberlain have you done a PR ?
