### ISSUE TITLE
Call to undefined method Illuminate\Database\Eloquent\Collection::join()

### ISSUE THREAD

**Issue by XerraSham** [laravel/framework#10519]
public function index() 
    {

        $faculties = faculties::all()
                    ->join('institutes','faculties.institutes_id','=','institutes.id')
                    ->select('institutes.name','faculties.name')
                    ->get();

        return view('faculties.index')
           ->with('faculties', $faculties);
    }

FACULTIES:                
id(pk)
institutes_id(fk)
name
created_at
updated_at
deleted_at

INSTITUTES:
id(pk)
name
type
established
created_at
updated_at
deleted_at 

got error on this (facultiesController.php). any ideas?

**Comment by GrahamCampbell** [comment]
You called `all` which executed the query. Don't do that.

**Comment by XerraSham** [comment]
i removed all() already but still got errors. then how? Or the method i used to call query was wrong.

this is my index.blade.php

@foreach($faculties as $row)

					        <tr>
					        	<td>{{ $row->institutes.name }}</td>
					            <td>{{ $row->faculties.name }}</td>

					           	
					            <td>
					                <a class="btn btn-small btn-info" href="{{ route('faculties.edit', $faculties->id) }}">EDIT</a>
					                <a class="btn btn-small btn-danger" href="{{ route('faculties.delete', $faculties->id) }}">DELETE</a>
					            </td>
					        </tr>
					    @endforeach
