### ISSUE TITLE
Attributes in the $appends array not loaded when Models are retrieved through a relation

### ISSUE THREAD

**Issue by davidhemphill** [laravel/framework#10511]
Basically, when one uses the $appends array on a model, the attributes are available when you retrieve the model directly, but not when the model is retrieved through a relation.

```
$model = User::find(4);
var_dump($model->appendsColumn); // This works

$parent = Parent::find(4);
var_dump($parent->model->appendsColumn); // This doesn't have the appended attributes
```

There are a number of situations where this is really inconvenient. :-)

**Comment by Edgpaez** [comment]
This works for me.

Given the appends requires you create a `getMyColumnAttribute` and the [getAttribute](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Database/Eloquent/Model.php#L2623) checks if such method exists using the [hasGetMutator](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Database/Eloquent/Model.php#L2730) it doesn't matter *how* the model is loaded, the method will always be found and called.

Maybe share more code!
