### ISSUE TITLE
QueryException while paginating on Microsoft SQL Server

### ISSUE THREAD

**Issue by MatasElectronics** [laravel/framework#10522]
The intranet of the company I work for has backed by a SQL Server database. Today while building a new page on the intranet I ran into the following problem:

I'm trying to paginate the results of a pretty simple query with a join. Sadly this is throwing an exception when you try to visit page 2. Here is the exception:

```
QLSTATE[42000]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]
The column 'CallNr' was specified multiple times for 'temp_table'. (SQL: select * from (select [MD_CallRegistrationMeta].*, [T_CallRegistration].*, row_number() over (order by [RegistrationDate] desc) as row_num from [T_CallRegistration] left join [MD_CallRegistrationMeta] on [MD_CallRegistrationMeta].[CallNr] = [T_CallRegistration].[CallNr] where [CallTypeCode] in (AG1, AL1, NO1, PRO, TD1) and [CallStatusCode] <> 99 and [CallStatusCode] <> 00) as temp_table where row_num between 9 and 16) 
```

The problem seems to be the fact that for the content of `temp_table` the select includes all fields of both tables, and both tables have a CallNr column. 

I'd like some help on this :smile:

**Comment by risan** [comment]
As you mentioned earlier the problem came from the duplicated `CallNr` column in `MD_CallRegistrationMeta` and `T_CallRegistration` tables. You need to specify which `CallNr` column to fetch:

```
SELECT 
  MD_CallRegistrationMeta.CallNr,
  MD_CallRegistrationMeta.other_column,
  MD_T_CallRegistration.other_column,
FROM T_CallRegistration LEFT JOIN MD_CallRegistrationMeta ON
  MD_CallRegistrationMeta.CallNr = T_CallRegistration.CallNr
```

Hope this help.

**Comment by GrahamCampbell** [comment]
We're open to PRs.
