### ISSUE TITLE
[L4.2] PDO Fetch Mode Resetting in Artisan Commands

### ISSUE THREAD

**Issue by hskrasek** [laravel/framework#10540]
I am fairly confident I have tracked down a bug, or I am somehow doing something wrong, either way this has caused me some grief.

I ran an artisan command through XDebug that receives an instance of `\Illuminate\Database\DatabaseManager` in the constructor, and then I immediately set a db property to `$databaseManager->connection();`

```php
public function __construct(DatabaseManager $databaseManager, CacheManager $cacheManager)
    {
        parent::__construct();
        $this->db    = $databaseManager->connection();
        $this->cache = $cacheManager;
    }
```

When I inspect the property, I can see that the fetchMode is set to 8 (PDO::FETCH_CLASS), which is exactly what I expect it to be.

But then if I follow the path artisan goes through to run the actual command, something weird happens. By time you wind up on line #435 of `\Symfony\Component\Console\Application`, when I inspect the `$this->commands` property and find the instance of the command I am going to run, all of a sudden `$this->db->fetchMode` has magically become 2 (PDO::FETCH_ASSOC) which just so happens to be the default specified in the `\Illuminate\Database\Connection` class.

So.. any ideas as to why this is magically switching fetch modes?

**Comment by GrahamCampbell** [comment]
4.2 not supported.

**Comment by hskrasek** [comment]
Alright I was finally able to track down what was happening.. not sure if it makes sense. Another artisan command was setting the fetch mode to `PDO::FETCH_ASSOC`, but I don't get how a separate command changing the fetch mode would affect other artisan commands.

The other commands constructor:

```php
public function __construct(DatabaseManager $databaseManager)
    {
        parent::__construct();
        $this->db = $databaseManager->connection('mysql');
        $this->db->setFetchMode(PDO::FETCH_ASSOC);
    }
```

I'm calling setFetchMode on the artisan command classes own `$this->db` property, and not the connection stored on the DatabaseManager, unless I am missing something
