### ISSUE TITLE
Update dotenv

### ISSUE THREAD

**Issue by guilhermecvm** [laravel/framework#10547]
Any reasons why laravel is not using [dotenv](https://github.com/vlucas/phpdotenv) [v2.0.1](https://github.com/vlucas/phpdotenv/releases/tag/v2.0.1) or [v1.1.1](https://github.com/vlucas/phpdotenv/releases/tag/v1.1.1) or [v1.0.9](https://github.com/vlucas/phpdotenv/releases/tag/v1.0.9)?

Nesting variables are a great feature.

**Comment by GrahamCampbell** [comment]
We ARE using 1.1.1.

**Comment by tomschlick** [comment]
Nested variables would be a nice feature... Are there any BC breaks with upgrading to 2.0.1?

**Comment by GrahamCampbell** [comment]
I think some small ones. I wanted to upgrade to 2.x for L5.1's launch, but Taylor didn't see the point since 1.x works just fine. See if you can convince him to upgrade for L5.2. :)

**Comment by GrahamCampbell** [comment]
I'll make a PR to upgrade us. Can't promise anything though.

**Comment by guilhermecvm** [comment]
That's great, thanks @GrahamCampbell
