### ISSUE TITLE
[Discussion] Use a View in Mail::send

### ISSUE THREAD

**Issue by rentalhost** [laravel/framework#10549]
Currently, you *can* use a View on `Mail::send`, but only by passing the View path and data, instead of an instance of View. That surprises me because it will accept a View by "reconstruct" it on `Mail::send` parameter, only.

After I study this method, I see that accept only a View is inviable because you can too pass an array that will fill the `html`, `text` and `raw` versions of content. But it's acceptable too if I use a View for that instead of this path.

It'll not work (at least for me):

```
$view = view('mail');

Mail::send($view, [], $callback);
```

Firstly, I think that Mail::send signature should receives a View and a Callback. Like Mail::send(View, Closure). But currently, it'll not work to avoid breaking changes. But Mail::send(View, [], Closure) should work. What I'm missing?

A PR can help with that, or exists some reason to work like it?

**Comment by GrahamCampbell** [comment]
Just pass `'mail` as `view`. Don't try to render it.

**Comment by rentalhost** [comment]
But this is justly the problem. I need send the view unconstructed, where I should pass the instance. Because of it I like to discuss before close it.
