### ISSUE TITLE
Better errors for views

### ISSUE THREAD

**Issue by CupOfTea696** [laravel/framework#10551]
Hi,

I was wondering if it is at all possible to have better errors for views. Currently, the error thrown gives the compiled view file as the place where the error occurred. It'd be nice if it would show the actual view file that contains the error. Maybe using php comments in the compiled file to indicate the original view location and use that when an error occurs?

**Comment by GrahamCampbell** [comment]
We're open to PRs. :)

**Comment by GrahamCampbell** [comment]
> Maybe using php comments in the compiled file to indicate the original view location and use that when an error occurs?

No, don't do that.

**Comment by GrahamCampbell** [comment]
I guess we'd have to rethrow, which messes up the stack trace, so maybe we shouldn't do anything.

**Comment by GrahamCampbell** [comment]
The stack trace should already show you the view used?

**Comment by CupOfTea696** [comment]
I don't think the Stack Trace does. Or at least not in all cases:

<img width="983" alt="screen shot 2015-10-11 at 14 58 52" src="https://cloud.githubusercontent.com/assets/7327050/10417129/a79b0844-7028-11e5-92b3-47004945d652.png">

**Comment by GrahamCampbell** [comment]
Look in Response.php at line 51.
