### ISSUE TITLE
Word 'batch' is reserved in some DBMS as result migrations won't work there

### ISSUE THREAD

**Issue by Dalamar** [laravel/framework#10563]
For instance I want to use Graph DB (OrientDB) for my new Laravel 5.1 based project.
I found OrientDB driver for Laravel - sgpatil/orientdb-laravel-5
https://github.com/sgpatil/orientdb-laravel-5
But I came across very bad situation with migrations.
Laravel uses column name `batch` to keep the ID (version) of migration.
The problem is that this word `batch` is kinda reserved in OrientDB and simple query
```INSERT INTO migrations (migration, batch) VALUES ('2015_10_12_161815_create_users_table', 1)
```
fails…

Is it possible to make this field name configurable with default name as it is now?

**Comment by GrahamCampbell** [comment]
We don't support that, sorry.
