### ISSUE TITLE
Route::when() for Middleware

### ISSUE THREAD

**Issue by brazorf** [laravel/framework#10561]
In L4 we were able to set filters for single route patterns,i.e. `Route::when('api', 'filter');`

Now with L5 we can apply Middleware  to single routes, route groups, or all http requests but seems like we are not able to select url patterns. 

Is there any way to achieve this? Or is it a planned feature?

**Comment by GrahamCampbell** [comment]
Please direct questions to the forums, or other mediums. I'm sure someone can help you there. :)

**Comment by GrahamCampbell** [comment]
We have to keep our issues strictly for bugs so we can stand any chance of keeping track of everything. :)

**Comment by sebastiaanluca** [comment]
@GrahamCampbell Where to request or discuss a new feature? I was also searching for an answer to why this was deprecated. Filters got replaced by middleware, but I see no reason to remove this route pattern (and even URI regex) feature. Desperately need this.

**Comment by GrahamCampbell** [comment]
Forums and/or slack.

**Comment by sebastiaanluca** [comment]
Which forums exactly? https://laracasts.com/discuss/channels/general-discussion/l5-routewhen-loading-filters-instead-of-middlewares?page=0 ?

**Comment by sebastiaanluca** [comment]
@brazorf and anyone interested: I quickly mashed up the following example to add middleware to routes of a certain name like you can/could do with filters without changed the Router or Route class. You can easily change this to check the URI path.

```php
$routes = $this->router->getRoutes()->getIterator();
$filters = 'admin.users';
$middleware = SiteContextMiddleware::class;

// Middleware route filter
// AKA Route::when() but for middleware
/** @var \Illuminate\Routing\Route $route */
foreach ($routes as $route) {
    // Add middleware to routes contained in filter
    if (starts_with($route->getName(), $filters)) {
        $route->middleware($middleware);
    }
}
```
