### ISSUE TITLE
$collection->merge() bug?

### ISSUE THREAD

**Issue by huglester** [laravel/framework#10560]
Hello everybody,

today I've spoted, that in some situations I get incorrect items count after merge, for example:

```php
        echo count($expenses);
        // gives 2 (OK)

        $payouts = $balance->worker->payouts;
        echo count($payouts);
        // gives 2 (OK)

        // merge
        $merged = $expenses->merge($payouts);
        echo count($merged);

        // gives 3!
```

Somehow merged result is 3 items (instead of 4). Any idea why?

Thank you!

**Comment by willrowe** [comment]
It's probably because `$payouts` and `$expenses` have one key that's the same and is being overwritten in the merge.

**Comment by huglester** [comment]
there is a big change, that "id" keys could be the same, any way around this?

**Comment by willrowe** [comment]
Are the keys integers or something like an UUID?

**Comment by huglester** [comment]
Pk is named id and in fact is autoincrementing ID.

But is the unique id is really needed?
Since merge() would return array ob objects.. so I assume it should support event identical objects?

**Comment by willrowe** [comment]
Can you do a `var_dump()` on the `$payouts` and `$expenses` variables and paste what it prints out?

**Comment by JosephSilber** [comment]
The Eloquent collection uses the model keys to handle the merge. If that's not what you want, use the base collection:

```php
$merged = $expenses->toBase()->merge($payouts);
```
