### ISSUE TITLE
php artisan always returns:    [ErrorException]   Undefined offset: 1

### ISSUE THREAD

**Issue by llnk** [laravel/framework#10576]
I am on Windows 8.1, with PHP 5.6.12.

Inside my working directory, whenever I try to run any ```artisan command``` I get:

      [ErrorException]   Undefined offset: 1

I am using Laravel '5.1.19 (LTS)'. Note I cannot even run 

     php artisan --version

The version I found was in: vendor\laravel\framework\src\Illuminate\Foundation\Application.php

![screenshot_1](https://cloud.githubusercontent.com/assets/1444881/10450605/a5ef71be-719b-11e5-9559-b3309bea094b.png)

**Comment by GrahamCampbell** [comment]
We're going to need more information than that please. What's in your logs?

**Comment by llnk** [comment]
All right I found the error. It was due to my custom code in routes.php. (I need a website that changes the routes according to the language, so I need some code to run before defining the routes, but that was not going nice when artisan ran it. Thanks, closing)
