### ISSUE TITLE
[Bug] Blade::directive requires a space before @

### ISSUE THREAD

**Issue by tmarsteel** [laravel/framework#10577]
Hi everyone,

currently, i am upgrading an application from 4.2 to 5.1. We have some Blade extensions in use, e.g. this one:
```php
Blade::extend(function($view, $compiler) {
    $pattern = $compiler->createMatcher('url');

    return preg_replace($pattern, '$1<?php echo urlencode($2); ?>', $view);
});
```

If i understand the documentation on extending blade in 5.1 correctly, this should be the equivalent for 5.1.:

```php
Blade::directive('url', function($expression) {
    return '<?php echo urlencode(' . $expression . '); ?>';
});
```

**This is the bug:**
In Laravel 4.2 this extension worked acceptable but in 5.1, the directive does **not** work unless there is at least one space preceeding the @:

```html
<a href="/users/@url($user->uid)">klick</a>
```
Expected output:
```html
<a href="/users/f5acbe21">klick</a>
```
Actual Output:
```html
<a href="/users/@url($user->uid)">klick</a>
```
---
```html
<!-- note the space before the @ ! -->
<a href="/users/ @url($user->uid)">klick</a>
```
Actual Output:
```html
<a href="/users/ f5acbe21">klick</a>
```

**Comment by GrahamCampbell** [comment]
Not a bug. Just the conditions have changed and now you need a space.

**Comment by tmarsteel** [comment]
Then why is this not pointed out in the documentation? And how am i going to use the blade extensions within URLs without puptting a space in?
This breaks more than half of ~ 10.000 - 15.000 lines of template code in this codebase.
