### ISSUE TITLE
return void in constructors docbloc

### ISSUE THREAD

**Issue by Ellrion** [laravel/framework#10572]
http://www.phpdoc.org/docs/latest/references/phpdoc/tags/return.html
> constructors, the @return tag MAY be omitted here, in which case @return self is implied.

Shouldn't `@return void` be replaced with `@return self` in docbloc for constructors?

**Comment by GrahamCampbell** [comment]
No, self is wrong.

**Comment by GrahamCampbell** [comment]
php documentor is wrong here. constructors only return self if you actually put `return $this` at the end.
