### ISSUE TITLE
File a documentation bug regarding calling "composer dump-autoload" after renaming the app.

### ISSUE THREAD

**Issue by navid-anwar** [laravel/framework#10575]
Hi,

I have installed the laravel 5.1.11 version today and then rename the app using following command i.e.

php artisan app:name FiGlass

Then during discussion on IRC channel, one of the experienced developer asked me to run the following command i.e.

php artisan tinker

and got the following output i.e.
PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class FiGlass\Console\Kernel does not exist' in www.example.com/vendor/laravel/framework/src/Illuminate/Container/Container.php:737 

Then, I run the following command as advised i.e.
composer dump-autoload

Then view the files and they all pointed to the new namespace i.e. FiGlass. Then run the page and got the default "Laravel 5" text on laravel welcome page.

Hope someone will put in the documentation somewhere how to rename the app properly and what are the post rename steps.

Good Luck!

Cheers,
Naveed.

**Comment by GrahamCampbell** [comment]
Yes, you need to dump-autoload before actually using the app.
