### ISSUE TITLE
[5.1] Query Builder exists() creates incorrect syntax for sqlserver

### ISSUE THREAD

**Issue by rogierborst** [laravel/framework#10580]
As of commit cf668a67bd4959d9265b8e5ea46d0fce24b871f3, when working with **SQL Server**, the `exists` method generates incorrect sql syntax.
The following statement
```php
User::where('loginId', 1)->exists();
```
generates:
```sql
select exists(from [user] where [user].[deleted_at] is null and [loginId] = 1) as [exists])
```
I'm honestly no expert in SQL queries, but even just counting the braces tells me there's something going wrong in the query builder.

**Comment by acasar** [comment]
@rogierborst Can you check if this https://github.com/laravel/framework/pull/10633 fixes your problem?

**Comment by rogierborst** [comment]
Alas, although the number of braces is correct now, it's still invalid syntax:
```sql
select exists(select * from [Module] where [ModuleId] = 20) as [exists]
```

**Comment by HipsterJazzbo** [comment]
I'm not that familiar with SQL Server. Should it be more like [this](http://stackoverflow.com/questions/2759756/is-it-possible-to-select-exists-directly-as-a-bit)?

**Comment by HipsterJazzbo** [comment]
@rogierborst I'm not that familiar with SQL Server. Should it be more like [this](http://stackoverflow.com/questions/2759756/is-it-possible-to-select-exists-directly-as-a-bit)?

**Comment by rogierborst** [comment]
Yes, that would work...
```sql
SELECT CAST(
   CASE WHEN EXISTS(SELECT * FROM Module where ModuleId = 20) THEN 1 
   ELSE 0 
   END 
AS BIT)
```
But the old way it was implemented worked too. I believe that was more like this:
```sql
SELECT COUNT(*) FROM Module WHERE ModuleId = 20
```
