### ISSUE TITLE
Console\Scheduling\Event sets events up with an extra time period

### ISSUE THREAD

**Issue by erunion** [laravel/framework#10588]
Cron only has support for 5 date time periods, but every `->cron()` call in `Console\Scheduling\Event` is using six date time periods. 

Example from `master`:

```
    public function everyMinute()
    {
        return $this->cron('* * * * * *');
    }
```

Is this intended, or just a typo?

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell.

**Comment by taylorotwell** [comment]
Cron does have six date time periods: http://www.nncron.ru/help/EN/working/cron-format.htm
