### ISSUE TITLE
InvalidArgumentException: Input "language_id" cannot take "1" as a value (possible values: ).

### ISSUE THREAD

**Issue by Dreaw** [laravel/framework#10590]
Hi,
I have a problem with Unit Testing in Laravel 5.1. 

In database I have 2 tables: orders and languages.
The orders collumn language_id has a relationship whit languages.

When I submit the form in browser, everything works fine, but when I submit the form In UnitTest, I get error message InvalidArgumentException: Input "language_id" cannot take "1" as a value (possible values: ).

In languages table I have row with ID 1 :)

Does anybody know, what to do? 

Thx for any response :)
Martin

**Comment by GrahamCampbell** [comment]
Please ask on the forums.
