### ISSUE TITLE
Improve the slug function

### ISSUE THREAD

**Issue by nicolaslemoine** [laravel/framework#10595]
Can the quotes be replaced by the separator instead of being removed?
Currently, in french such string "J'aime les pommes" becomes (with the dash separator) "jaime-les-pommes" which is not best for the SEO...
The french slug should be "j-aime-les-pommes".

**Comment by GrahamCampbell** [comment]
Sorry, we don't process proposal issues. Please read the contribution guidelines.

**Comment by JesseLeite** [comment]
@GrahamCampbell, if user doesn't feel comfortable/knowledgeable enough to submit PR, how is user supposed to suggest change?

**Comment by GrahamCampbell** [comment]
Directly to Taylor.
