### ISSUE TITLE
BelongsTo relationship with different databases not working

### ISSUE THREAD

**Issue by nirradian** [laravel/framework#10597]
Laravel 4.2:

I've seen in several places to "stay away" from this, but alas - this is how my DB is built:

class Album extends Eloquent {

   // default connection

   public function genre() {
       return $this->belongsTo('genre');
   }
and the Genre table:

class Genre extends Eloquent {
    $connection = 'Resources';

}
and when I try to run

Album::whereHas('genre', function ($q) {
   $q->where('genre', 'German HopScotch'); 
});
it doesn't select properly (doesn't add the database name to the table "genres"):

Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mysql.genres' doesn't exist
Its important to note that this works perfectly:

Album::first()->genre;

**Comment by GrahamCampbell** [comment]
Only L5.1 or 5.2 are supported.
