### ISSUE TITLE
RateLimiter going from 0 to 2 in under 1 second...

### ISSUE THREAD

**Issue by SeoRoman** [laravel/framework#10600]
RateLimiter.php

<?php
 public function hit($key, $decayMinutes = 1)
 {
    $this->cache->add($key, 1, $decayMinutes);

    return (int) $this->cache->increment($key);
 }
?>

Problem is... on first creation... the key is added with a (1) value, and then immediately incremented to (2)... so ->attempts($key) is retrieving 0 first... and then 2 right after... (any subsequent tries, are incremented, because ->add() fails if it exists)

// Test Code
<?php
 var_dump($request->only("username"));

 var_dump($this->rateLimiter->attempts($this->getThrottleKey($request))); // 0

 $this->incrementLoginAttempts($request);  

 var_dump($this->rateLimiter->attempts($this->getThrottleKey($request))); // 2

 dd();
?>

getThrottleKey() simply returns a common key name for the $request

**Comment by SeoRoman** [comment]
revised RateLimiter code

 public function hit($key, $decayMinutes = 1)
    {
        if ($this->cache->has($key))
            return (int) $this->cache->increment($key);

        $this->cache->add($key, 1, $decayMinutes);
        return $this->cache->get($key, 0);
    }

seems to work, probably not the best looking bit

**Comment by SeoRoman** [comment]
Side Note: using FileStore (not sure if that makes a difference...) I've checked also the Cache add() function which should not add key if it doesn't exist... and FileStore.php increment function (which all seems to be in order), but for some reason, it's still duplicating... using the above code stops it, however it seems like it should be stopped already but it's not ...

**Comment by GrahamCampbell** [comment]
We're open to PRs.
