### ISSUE TITLE
[Suggestion] Arr::random() method

### ISSUE THREAD

**Issue by vlakoff** [laravel/framework#10602]
Because the native [`array_rand()`](http://php.net/manual/en/function.array-rand.php) may be a bit unintuitive as it returns keys (which we don't need in most cases), and more importantly, using it often appears to be somewhat verbose: `$readConfig['host'][array_rand($readConfig['host'])]`, and it gets worse when getting several items.

It would basically be the same as [`Collection::random()`](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Support/Collection.php). But directly on array, thus removing the need to create a collection only for this :)

Was already asked in #8330 (but with support for picking only one item)

**Comment by EdwardNelson** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
We don't process proposal issues. Please just either ask Taylor on slack, or send a PR.
