### ISSUE TITLE
[5.1] Call to undefined method Swift_Plugins_LoggerPlugin::beforeSendPerformed()

### ISSUE THREAD

**Issue by vkartaviy** [laravel/framework#10607]
When using Swift mailer plugins such as ```Swift_Plugins_LoggerPlugin``` which doesn't implement ```Swift_Events_SendListener``` interface throws this exception.

As I understand that is due to calling ```$plugin->beforeSendPerformed``` method without checking interface implementation [here](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Mail/Transport/Transport.php#L65).

I stumbled upon this when trying to send mails with enabled ```DebugBar``` extension and ```['mail']['full_log'] = true``` which uses ```Swift_Plugins_LoggerPlugin```.

**Comment by GrahamCampbell** [comment]
Are there any other places where we need to fix similar things?

**Comment by GrahamCampbell** [comment]
Does #10610 fix this for you? Please comment on that PR since I don't read comments on closed issues. I can reopen this if needed if the PR doesn't do what you need.
