### ISSUE TITLE
Middleware does not kick in for the OPTIONS request

### ISSUE THREAD

**Issue by kyrenator** [laravel/framework#10617]
Example behavior:
```php
class midllewareTest {
    public function handle($request, Closure $next)
        dd('middleware running');
    {
}

Route::group(['middleware' => 'midllewareTest'], function () {
    Route::any('test', function(){
        return 'middleware not executed';
    });
});
```

When sending GET, POST etc requests 'middleware running' is returned.
When sending OPTIONS request nothing is returned.

In order to make middleware run with OPTIONS I specified this route

```php
Route::group(['middleware' => 'midllewareTest'], function () {
    Route::options('test', function(){
        return 'middleware not executed';
    });
});
```
Then when sending OPTIONS request 'middleware running' is returned.

I believe that since the Route test is inside the group, the midllewareTest must always run despite the REQUEST method.

**Comment by marcvdm** [comment]
The middleware is bound to all the routes inside it!

In your first example you do Route::any which does not include the OPTIONS method. (https://github.com/laravel/framework/blob/5.1/src/Illuminate/Routing/Router.php#L204)

Since the router did not find a match for the uri in combination with the method it just stops with either a NotFoundException or a MethodNotAllowedException if the uri matches but the method does not

**Comment by kyrenator** [comment]
Yes but when you are working with a mobile app for example and you have a Route::post() you need the middlewares (ex CORS) to be applied to OPTIONS method too inside a specific group.

Thats the point of OPTIONS method, to run before GET, POST, etc.

example scenario:
You have this route
```php
    Route::get('user', ['middleware' => 'CORS'], function (){
        //get user
    });
});`
```
And you want to get user from another domain using ajax. The browser sends OPTIONS request to get the allowed header (ex Authorization) and then proceeds with the GET request.

With the way OPTIONS method works now the browser will not received the expected headers and a Cross-Origin Resource Sharing exception will be thrown.

The only way to work with CORS now is to configure nginx to apply options to specific routes.

**Comment by marcvdm** [comment]
I guess you should then put the middleware globally. And if you only want the middleware for example for the api/ namespace you can do the following
```php
if (strpos($request->path(), 'api') === 0) {
    // Do some cors stuff here for the api routes only
}

// or

if ($request->method() == 'OPTIONS') {
    // Do some cors stuff here for the api routes only
}
```
And maybe this package can help you along https://github.com/barryvdh/laravel-cors

**Comment by kyrenator** [comment]
This is what I am doing finally, but I think it should work this way by default so we dont have to define all routes we need Cors inside the middleware.
