### ISSUE TITLE
DatabaseMigrations trait exhausts database connections

### ISSUE THREAD

**Issue by mfn** [laravel/framework#10619]
Using `DatabaseMigrations` with a lot of tests will exhaust all connections to the dabatase, i.e. they're not freed/returned to the system.

How to reproduce, as suggested from http://laravel.com/docs/5.1/testing#resetting-the-database-after-each-test :
1) `composer.phar create-project laravel/laravel --prefer-dist`
2) `cd laravel`
3) Change `.env` to point to a valid database connecion
4) Create a test script with many tests, using the trait; e.g. using this bash lines:
```SH
echo "<?php class ExhaustionTest extends TestCase {" > tests/ExhaustionTest.php
echo "use Illuminate\Foundation\Testing\DatabaseMigrations;" >> tests/ExhaustionTest.php
for i in $(seq 1 500); do echo "function test$i() {}" >>  tests/ExhaustionTest.php; done
echo "}" >> tests/ExhaustionTest.php
```
5) Run the tests with `vendor/bin/phpunit`

After a some tests they start to fail with the following error (or similar, depending on your DB):
`PDOException: SQLSTATE[08004] [1040] Too many connections`

Here's an example trace:
```
1) ExhaustionTest::test143
PDOException: SQLSTATE[08004] [1040] Too many connections

/home/vagrant/src/test/laravel/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:55
/home/vagrant/src/test/laravel/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php:22
/home/vagrant/src/test/laravel/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php:60
/home/vagrant/src/test/laravel/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php:49
/home/vagrant/src/test/laravel/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:175
/home/vagrant/src/test/laravel/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:67
/home/vagrant/src/test/laravel/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php:171
/home/vagrant/src/test/laravel/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php:139
/home/vagrant/src/test/laravel/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:393
/home/vagrant/src/test/laravel/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php:100
/home/vagrant/src/test/laravel/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php:58
/home/vagrant/src/test/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:503
/home/vagrant/src/test/laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php:150
/home/vagrant/src/test/laravel/vendor/symfony/console/Command/Command.php:259
/home/vagrant/src/test/laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php:136
/home/vagrant/src/test/laravel/vendor/laravel/framework/src/Illuminate/Console/Application.php:62
/home/vagrant/src/test/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:159
/home/vagrant/src/test/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Testing/ApplicationTrait.php:299
/home/vagrant/src/test/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Testing/DatabaseMigrations.php:12
```

To fix this for my suite, I created a trait similar to this:
```PHP
trait DatabaseMigrationsCleanupTrait
{
    use Illuminate\Foundation\Testing\DatabaseMigrations;

    /**
     * @after
     */
    public function disconnectAllDatabases()
    {
        /** @var \Illuminate\Database\Connection $connection */
        foreach (\DB::getConnections() as $connection) {
            $connection->disconnect();
        }
    }
}
```
I would open a PR if someone points me in the right direction where the fix would be appropriate.

I tried this, which also worked:
```DIFF
diff --git a/vendor/laravel/framework/src/Illuminate/Foundation/Testing/DatabaseMigrations.php b/vendor/laravel/framework/src/Illuminate/Foundation/Testing/DatabaseMigrations.php
index d53b34e..b4a3205 100644
--- a/vendor/laravel/framework/src/Illuminate/Foundation/Testing/DatabaseMigrations.php
+++ b/vendor/laravel/framework/src/Illuminate/Foundation/Testing/DatabaseMigrations.php
@@ -13,6 +13,9 @@ trait DatabaseMigrations

         $this->beforeApplicationDestroyed(function () {
             $this->artisan('migrate:rollback');
+            foreach (\DB::getConnections() as $connection) {
+                $connection->disconnect();
+            }
         });
     }
 }
```

**Comment by GrahamCampbell** [comment]
This should happen anyway?

**Comment by GrahamCampbell** [comment]
When the applications are destroyed the connections should be garbage collected. Have you turned off the garbage collector?

**Comment by GrahamCampbell** [comment]
> \DB::getConnections()

You definitely wouldn't want to do that. You'd want to call this->app->...

**Comment by mfn** [comment]
> Have you turned off the garbage collector?

Not that I'm aware of. Tested with
```
$ php -v 
PHP 5.6.14-1+deb.sury.org~trusty+1 (cli)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

$ php -i|grep enable_gc
zend.enable_gc => On => On
```
from https://launchpad.net/~ondrej/+archive/ubuntu/php5 for Ubuntu 14.04 LTS

> You definitely wouldn't want to do that. You'd want to call this->app->...

Yeah, I thought so ... :-)

The underlying `PDO` does not support explicit disconnects and relies on being unrefed, maybe there's a dangling reference kept somewhere.

**Comment by pulkitjalan** [comment]
Having the same issue.

```
$ php -i | grep enable_gc
zend.enable_gc => On => On
```

The above fix solves the issue.

```
foreach ($this->app->make('db')->getConnections() as $connection) {
    $connection->disconnect();
}
```

**Comment by mfn** [comment]
I've switched my project from using the `DatbaseMigrations` to `DatabaseTransactions` and have seen the same problem.

I replaced it with my own trait, not only because of this bug, but also because the included `DatabaseTransactions` only covers the default connections and not others:
```PHP
<?php

trait MultiDatabaseTransactionsTrait
{
    /**
     * @before
     */
    public function beginDatabaseTransaction()
    {
        /** @var \Illuminate\Database\DatabaseManager $db */
        $db = $this->app->make('db');
        $names = array_keys($this->app['config']['database.connections']);

        foreach ($names as $name) {
            $db->connection($name)->beginTransaction();
        }

        $this->beforeApplicationDestroyed(function () use ($db, $names) {
            foreach ($names as $name) {
                $connection = $db->connection($name);
                $connection->rollBack();
                $connection->disconnect();
            }
        });
    }
}
```

**Comment by mfn** [comment]
Why closed? This issue isn't solved?

**Comment by RomainLanz** [comment]
Look at the PR linked above https://github.com/laravel/framework/pull/10731

**Comment by pulkitjalan** [comment]
That PR did not fix the issue and does not work. The pr was closed not merged.

**Comment by pulkitjalan** [comment]
This issue is still not solved.

**Comment by RomainLanz** [comment]
Did you read the PR?

cc @GrahamCampbell

**Comment by GrahamCampbell** [comment]
Being marked as a no-fix, or technical limitation.

**Comment by GrahamCampbell** [comment]
If someone has a really good fix, we're open to PRs. ;)

**Comment by KNabityMailServicesLC** [comment]
I'm having problems with this too.  Where is the better solution?

**Comment by mfn** [comment]
@KNabityMailServicesLC just being an observer here, but as I see that the [DatabaseTransaction](https://github.com/laravel/framework/blob/8584aa23bc140c3739b57fa008412ce6a4d33e76/src/Illuminate/Foundation/Testing/DatabaseTransactions.php) code hasn't changed substantially since I created this issue, I think my https://github.com/laravel/framework/issues/10619#issuecomment-151075567 still holds.

I can confirm that it works insofar as the codebase is heavily developed on and the tests run locally and in our CI infrastructure many many times a day without known problems.

**Comment by cythrawll** [comment]
So I seemed to solve this myself by setting persistent connections on in the configuration environment. I make it an env(), and set it to true in phpunit.xml.  Not the best solution, but it seems to fix the issue.

**Comment by lehnen** [comment]
@cythrawll: Saved my day ;)

`        'mysql' => [
            'driver'    => 'mysql',
            'host'      => env('DB_HOST'    , 'localhost'),
            'database'  => env('DB_DATABASE', 'forge'),
            'username'  => env('DB_USERNAME', 'forge'),
            'password'  => env('DB_PASSWORD', ''),
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
            'strict'    => false,
            'options'   => array(
                PDO::ATTR_PERSISTENT => env('DB_PERSISTENT', false),
            ),
        ],`
