### ISSUE TITLE
Question for Illuminate\Database\Query\Builder

### ISSUE THREAD

**Issue by heydavid713** [laravel/framework#10614]
I noticed that the functionality of get and getFresh function was inverted. Is there a reason for this change that I'm missing. We are using a 3rd party connector for another database and this change is breaking our codebase.

Thanks in advance!

**Comment by GrahamCampbell** [comment]
Please ask Taylor directly. :)

**Comment by ctorresrodz** [comment]
GrahamCampbell ... please provide his contact info. Will call ASAP.
