### ISSUE TITLE
[Proposal] Marketing for the next major version number of Laravel

### ISSUE THREAD

**Issue by tortuetorche** [laravel/framework#10625]
Hi folks,

As you know the next major version of Laravel, the one after <del>5.2</del> **5.3**, will be only compatible with PHP **7**, which is fine.
So we can take this opportunity to skip Laravel **6** and directly released Laravel **7**!

Why? 
* PHP did it, PHP **6** will never be released
* Microsoft did it, with Windows **9**
* Winamp did it, with version **4**
* Node JS did it, from version **0.12.7** to **4.0.0** (Wow!)
* JRuby did it, from version **1.7.21** to **9.0.0.0** _aka **9000**_ (Double wow!)
* And many others...
* Because not following [Semantic Version](http://semver.org/) numbers is the new hype

But after that, we can do better:
* Microsoft is the master for skipping version numbers: Xbox (**1**), then Xbox **360** (What?) and finally Xbox **One** (Oh, wait...)

So the next major version of Laravel, after Laravel **7**, could be named Laravel **One** or Laravel **The First**, isn't it?

For more fun: [The Amazing World of Version Numbers](http://www.technologizer.com/2009/07/14/version-numbers/)

Happy Friday troll,
Tortue Torche

**Comment by GrahamCampbell** [comment]
> As you know the next major version of Laravel, the one after 5.2, will be only compatible with PHP 7, which is fine.

The next release will likely be 5.3, and it will remain compatible with php 5.

**Comment by tortuetorche** [comment]
@GrahamCampbell Alright, but it's not the next _major_ version.

**Comment by GrahamCampbell** [comment]
> the one after 5.2

Not that then. ;P

**Comment by GrahamCampbell** [comment]
:-1: For skipping L6.

**Comment by tortuetorche** [comment]
@GrahamCampbell So you are in the Semantic Versioning camp...
But Laravel **The First** is appealing, isn't it?

**Comment by GrahamCampbell** [comment]
> So you are in the Semantic Versioning camp...

No. Laravel doesn't follow semver at all.

**Comment by tortuetorche** [comment]
Good to know, so what's the problem?

**Comment by GrahamCampbell** [comment]
I'm actually going to close this since we don't process proposal issues on GitHub. Feel free to have a chat to Taylor on Slack, if you both have time.

**Comment by tortuetorche** [comment]
At least I tried :innocent:
