### ISSUE TITLE
Disable middlewares selectively 

### ISSUE THREAD

**Issue by andrea-imparato-sociomantic** [laravel/framework#10631]
The WithoutMiddleware disables all the middlewares for testing. But could it be possible to have also some methods to disable only one or more middlewares and not all of them? In my case I have a middlware for authentication and one for caching. When I want to write an integration test for the caching middleware I don't want to pass through the auth middleware

**Comment by GrahamCampbell** [comment]
Duplicate.

**Comment by andrea-imparato-sociomantic** [comment]
Duplicate where? Can you give me the issue number?

**Comment by GrahamCampbell** [comment]
Sorry, I don't know what issue it is.

**Comment by andrea-imparato-sociomantic** [comment]
Can you tell me if it has been fixed? Because I don't find it in the open issues
