### ISSUE TITLE
4.2: SoftDeletingScope prevents restore on Eloquent model

### ISSUE THREAD

**Issue by ryrobbo** [laravel/framework#10630]
I have initially posted my issue on Stackoverflow detailing my findings:

http://stackoverflow.com/questions/33171033/laravel-restore-trashed-not-working?noredirect=1#comment54150454_33171033

To summarise, I have a model that uses the SoftDeleteTrait and I am trying to execute the restore method to restore the record in the database. 

The restore method executes the following SQL:

`update UserClasses set updated_by = ?, deleted_at = ? where UserClasses.deleted_at is null and id = ?`

{"bindings":["1",null,"2086"],"time":0.72}

If you look at the WHERE statement, you will see "deleted_at is null" which is being injected by the SoftDeletingScope and preventing the record from being updated.

I can get my code to work by manually commenting out $builder->whereNull within the "apply" method of the SoftDeletingScope class.

**Comment by GrahamCampbell** [comment]
4.2 not supported

**Comment by MarkBaker** [comment]
Given that it looks as though the same issue is also present in the 5.0 and 5.1 branches, I'd have thought you'd be a little less dismissive of a bug report

And I'm sure that a lot of Laravel users aren't aware that 4.2 is no longer supported, then perhaps it's also time to consider making it more obvious to them what versions are and aren't supported.

**Comment by ryrobbo** [comment]
I was under the impression that with 4.2 documentation still on the Laravel website, it was still supported...
