### ISSUE TITLE
Support json responses in the exception hander

### ISSUE THREAD

**Issue by dan-har** [laravel/framework#10639]
When using the framework for api's, the exception handler does not render ```HttpException``` as a json response. Ofcourse one can override the ```render()``` and the ```renderHttpException()```  to achive that, but It feels like the framework should support that, same as api tests functions are supported. 

For example when using some of the good stuff like ```FormRequests``` and ```Authorization``` in some API controller and ```HttpException``` is thrown the response to the client will be html which is not not the expected response. With support of json responses in the exception handler these features will work out of the box for API's also.

A possible implementation for that may be the follow (Working on 5.2, the ```renderHttpException()```signature needs to change):

``` php
// file: src/Illuminate/Foundation/Exceptions/Handler.php

    /**
     * Render an exception into a response.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Exception  $e
     * @return \Illuminate\Http\Response
     */
    public function render($request, Exception $e)
    {
        if ($e instanceof ModelNotFoundException) {
            $e = new NotFoundHttpException($e->getMessage(), $e);
        } elseif ($e instanceof AuthorizationException) {
            $e = new HttpException(403, $e->getMessage());
        } elseif ($e instanceof ValidationException && $e->response) {
            return $e->response;
        }
        if ($this->isHttpException($e)) {
            // <- change start
            return $this->toIlluminateResponse($this->renderHttpException($e, $request), $e); 
            // <- change ends
        } else {
            return $this->toIlluminateResponse($this->convertExceptionToResponse($e), $e);
        }
    }


    /**
     * Render the given HttpException.
     *
     * @param  \Symfony\Component\HttpKernel\Exception\HttpException  $e
     * @param  \Illuminate\Http\Request
     * @return \Symfony\Component\HttpFoundation\Response
     */
    protected function renderHttpException(HttpException $e, Request $request)
    {
        $status = $e->getStatusCode();
        // <- change start
        if($this->respondWithJson($request)) {
            return response()->json([/** maybe an error message should be added*/], $status);
        } else /** change ends **/ if (view()->exists("errors.{$status}")) {
            return response()->view("errors.{$status}", ['exception' => $e], $status);
        } else {
            return $this->convertExceptionToResponse($e);
        }
    }

    
    /**
     * Determine if the response should a JSON response
     *
     * @param  Request  $request
     * @return  bool
     */
    protected function respondWithJson(Request $request)
    {
        return $request->wantsJson() || $request->ajax() 
    }
```

What do you think?

**Comment by GrahamCampbell** [comment]
Just implement this in your own app. Everyone wants different things.

**Comment by GrahamCampbell** [comment]
Might be worth checking out https://github.com/GrahamCampbell/Laravel-Exceptions though. That package provides a powerful system to return error responses based on acceptable content types and various other things.

**Comment by dan-har** [comment]
OK thank, Ill look into it.

**Comment by GrahamCampbell** [comment]
The idea of the package is you can add your own stuff that implements the interfaces, like https://github.com/StyleCI/StyleCI/tree/master/app/Exceptions.

**Comment by dan-har** [comment]
:thumbsup:
