### ISSUE TITLE
Collection `groupBy()` & `where()` not working with Carbon attribute

### ISSUE THREAD

**Issue by tillkruss** [laravel/framework#10657]
Not sure if this is a bug, or expected. When I run `groupBy()` on an attribute with a Carbon object value it fails:

```
array_key_exists(): The first argument should be either a string or an integer
```

Same issue when calling `where()`.

**Comment by frankweb** [comment]
Because of the message `The first argument should be either a string or an integer` I think this is expected. Probably you could get a string from the Carbon object before trying to use `groupBy` or `where`.
