### ISSUE TITLE
Extend PhpDoc with @method tags

### ISSUE THREAD

**Issue by rkgrep** [laravel/framework#10653]
Managers, facades and query builder classes currently does not provide proper hinting in IDE because they handle methods through `__call`.
Implementing `@method` tags will make these classes much more easy.

I am not sure if this was discussed already, so I need your opinion before making a PR on this.

**Comment by RomainLanz** [comment]
This has been discussed multiple times and always refused.

Some examples:
- https://github.com/laravel/framework/pull/10567
- https://github.com/laravel/framework/issues/7558
