### ISSUE TITLE
Timestamps and Timezone Problem

### ISSUE THREAD

**Issue by stefanhuber** [laravel/framework#10661]
I am using laravel 5.1 with mysql as DBMS. I have create a migration for a table and used the timestamps feature: `$table->timestamps();`. The column type in mysql for created_at and updated_at is TIMESTAMP. Mysql stores the timestamp always as unix timestamp in utc.

Whatever I try, I always get the Time in UTC, altough I want it in CEST. My servers local is CEST, Mysql timezones are CEST and php timezone is CEST. I also tried `$table->timestampsTz();`, however it didn't help.

Is it a bug, or do I miss something?

**Comment by rkgrep** [comment]
Did you try to set `timezone` parameter in database config? it is not documented.

**Comment by stefanhuber** [comment]
Ok. Sorry for that, I found the problem as you said... i changed the timezone inside the app config! Thx for your answer. The issue can be closed.
