### ISSUE TITLE
overidden attributes with same name in many-many relationship

### ISSUE THREAD

**Issue by ctadlock** [laravel/framework#10665]
I have models `account` and `project` in a standard many-many relationship with a join table `account_project`. All tables have `created_at` and `updated_at` columns. When I query for all of the projects for a specific account the following query is executed. The issue is that when the models are returned it is setting the values of both the `created_at` and `updated_at` attributes to be from the `account_project` table instead of the `project` table. I dont need any attributes from the `account_project` table.

```select * from `project` inner join `account_project` on `project`.`id` = `account_project`.`project_id` where `account_project`.`account_id` = ?```

I can add `->select("project.*")` to the query but that seems a bit hackish. I would expect the framework would keep the attributes separate. That results in the query:

```select `project`.* from `project` inner join `account_project` on `project`.`id` = `account_project`.`project_id` where `account_project`.`account_id` = ? order by `project`.`created_at````

What is the recommended way to handle this situation or is this actually a framework issue?

**Comment by RDelorier** [comment]
Thats just a normal sql situation, if you join tables then you need to specify the table.
