### ISSUE TITLE
elixir() helper includes hardcoded paths, while the mix.version() don't

### ISSUE THREAD

**Issue by igorsantos07** [laravel/framework#10664]
When using Elixir versioning task, you can provide a specific path for your assets to be saved at. 
However, the `elixir()` Blade helper contains **hardcoded** paths, rendering the second argument for `mix.version()` useless.

### Example:
```js
elixir(function(mix) {
  mix.less(['*.less', 'public/css/styles.css']);
  mix.coffee(['*.coffee', 'public/js/app.js']);
  mix.version(['css/styles.css', 'js/app.js'], 'public');
});
```
```html
<script src="{{ elixir('js/app.js') }}"></script>
```

### Results in:
> ErrorException in helpers.php line 273:
> file_get_contents(/var/www/public/build/rev-manifest.json): failed to open stream: No such file or directory
As per the `mix.version()` call, the `rev-manifest.json` file was saved to `public`, not `public/build`, but [the `elixir()` helper does not know it](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/helpers.php#L273 (a couple of lines below it also returns a fixed path for the file that was asked).

### Suggestion of fix:
I'm a newbie in Laravel so I'm not yet pushing a PR directly, but this is my bet on the fix: the build dir, specified on `mix.version()` should be stored in `rev-manifest.json`. Also, that manifest file should be saved in a fixed place, regardless of the build path - say, in `/public`, since this is a "fixed" dir in Laravel dir structure.

**Comment by GrahamCampbell** [comment]
Duplicate. The decision was to not allow changing the path in Laravel. That ability is only available in exlixir to allow use outside of Laravel.

**Comment by GrahamCampbell** [comment]
If there is an elixir specific issue here, please report this to Jeffery by creating an issue on the Elixir repo. :)

**Comment by igorsantos07** [comment]
Sorry, I didn't know there was a specific repository for that. As I found the `elixir()` source here, I though I could report it here.
I guess this should be documented in the function PHPDoc, at least? I guess others will stumble in the same problem. Given we can use an option in Elixir but not in the PHP helper, it smells like a missing feature.

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/elixir

**Comment by GrahamCampbell** [comment]
Reopening for Taylor or Jeffery to look at here. Thank you for reporting this @igorsantos07.

Ping @taylorotwell and/or @JeffreyWay.

**Comment by vinkla** [comment]
Could we just add the path to the `rev-manifest.json` as an argument on the `elixir()` method?

```php
function elixir($file, $manifestPath = 'build/rev-manifest.json')
{
    static $manifest = null;

    if (is_null($manifest)) {
        $manifest = json_decode(file_get_contents(public_path($manifestPath)), true);
    }

    if (isset($manifest[$file])) {
        return '/build/'.$manifest[$file];
    }

    throw new InvalidArgumentException("File {$file} not defined in asset manifest.");
}
```
In this way we wont break anything.

**Comment by igorsantos07** [comment]
I think it makes little sense, as you're still hardcoding the built asset
path. The best would be to set the root build Dir, as it happens on Elixir
code.
Or else, as it adds complexity and was discussed before, leve it out - but
document the discrepancy!

**Comment by erayaydin** [comment]
:+1: there should be a parameter with `$manifestPath`

**Comment by bachmay** [comment]
I have the same exact problem and no solution. I have to keep the manifest in the public directory, while everything else is copied to my public_html directory.

**Comment by bretmette** [comment]
@GrahamCampbell why was this closed and why isn't this moved to a config variable? What is the purpose of hard-coding it? Moving it to a config var would keep the default behavior while enabling people that want to override the build dir to be able to do so.

This seems like an anti-laravel decision, what is the reasoning behind it?

**Comment by erayaydin** [comment]
Its fixed with second parameter `$manifestDirectory` in **5.4**. I'm not checked 5.1

https://github.com/laravel/framework/blob/6d6191bb4c3a998c54aa6c12cf97c17cbaaa173a/src/Illuminate/Foundation/helpers.php#L561
