### ISSUE TITLE
Idea/proposal for router aliases

### ISSUE THREAD

**Issue by SerafimArts** [laravel/framework#10672]
Aliases for routes are popular function of laravel routing, but current usage like a monster. As example:
```php
// Without alias
Route::get('/home', 'HomeController@index');

// With alias
Route::get('/home', ['as' => 'home', 'uses' => 'HomeController@index']);
```

What you think about additional dsl-syntax for aliases? As example:
```php
// Variant 1
Route::get('/home', 'home:HomeController@index');

// Variant 2
Route::get('/home', 'home#HomeController@index');

// Another....
// ?
```

**Comment by rkgrep** [comment]
````php
//Variant 3
Route::get('/home', 'Home@index', 'home');
````

**Comment by SerafimArts** [comment]
UPD: Laravel has method `name`:

```
Route::get('/home', 'HomeController@index')->name('home');
```
But this method has no in official documentation. I think this example must be added in http://laravel.com/docs/5.1/routing#named-routes

**Comment by CupOfTea696** [comment]
I'd just keep it like is, but add the example with `->name()` to the documentation. Adding it to the dsl-syntax will only complicate stuff and it'd become less readable. However, if there were to be made any modifications in the dsl-syntax, I'd propose the route name to be added at the back somewhere, it makes more sense to me and is more readable.

```
// Variant 1
Route::get('/home', 'HomeController@index:home');

// Variant 2
Route::get('/home', 'HomeController@index#home');
```

**Comment by brunogaspar** [comment]
:-1: 

This way looks confusing, less intuitive and gives no real extra benefits.

What's wrong with `Route::get('home', 'HomeController@index')->name('home');`?

**Comment by GrahamCampbell** [comment]
I agree this doesn't need to change.

**Comment by SerafimArts** [comment]
@GrahamCampbell me agree too. I think need pull request in docs with description for this method. Create?

**Comment by GrahamCampbell** [comment]
The docs repo is open to PRs.
