### ISSUE TITLE
CORS issue with POST routes

### ISSUE THREAD

**Issue by hfuccillo** [laravel/framework#10677]
I'm working with AngularJS and a Laravel API. 
This is my route:
`Route::group(array('middleware' => 'cors'), function(){`
   `Route::post('dashboard/save', array('uses' => 'DashboardController@save', 'as' => 'api.dashboard.save'));`
`});`

And this is my middleware cors:

`    public function handle($request, Closure $next)
    {
`
 `       return $next($request)
                ->header('Access-Control-Allow-Origin', '*')                
                ->header('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
  `              
  `  }`

All my GET routes are working OK, but when I try to use a POST route, it throws an 'Access-Control-Allow-Origin' error.

**Comment by GrahamCampbell** [comment]
Please ask on the forums.
