### ISSUE TITLE
Auth::once doenst work when no password given

### ISSUE THREAD

**Issue by Fuzzyma** [laravel/framework#10676]
If you try to login a user for a single request you may use `Auth::once($credentials)`. I dont have a password and thats why the login fails in the [EloquentUserProvider L112](https://github.com/laravel/framework/blob/5f9a9d287027ed5772a19d078f1c863dd3b96322/src/Illuminate/Auth/EloquentUserProvider.php#L112) because it tries to access a 'password' which is not there.

**Comment by GrahamCampbell** [comment]
You need to provide that. Please ask on the forums for more help.

**Comment by crynobone** [comment]
This should work fine.

```php
Auth::setUser(User::find(5));
```

**Comment by Fuzzyma** [comment]
Or I just use the undocumented function `Auth::onceUsingId($id)`.

Why the 'password' is mandatory?
Using another name for password renders the auth-lib kinda useless because you cannot use `attempt` and so on
