### ISSUE TITLE
Improve route definitions features

### ISSUE THREAD

**Issue by rkgrep** [laravel/framework#10671]
I like the way routes defined in [StyleCI](https://github.com/StyleCI/StyleCI) and [CatchetHQ](https://github.com/cachethq/Cachet). Is it possible to add route mappers as default functionality in Laravel?
I propose making a Mapper Contract - so developers can make own mappers. And add [this code](https://github.com/StyleCI/StyleCI/blob/master/app/Providers/RouteServiceProvider.php#L83) to default RouteServiceProvider.
````php
interface Mapper
{
    /**
     * Defines if these routes are for the browser.
     *
     * @return bool
     */
    public function browser();

    /**
     * Map route actions.
     *
     * @param \Illuminate\Contracts\Routing\Registrar $router
     */
    public function map(Registrar $router);

    /**
     * Middleware applied to routes map.
     *
     * @return array
     */
    public function middleware();
}
````

**Comment by brunogaspar** [comment]
:-1: 

I find that way a bit overwhelming.

If you need it that way, just either implement on your applications or create a package, maybe?

**Comment by GrahamCampbell** [comment]
This is fine for people to just do in their own apps if they want it. That's exactly what I did in StyleCI and Cachet. :)
