### ISSUE TITLE
BeanstalkdJob converts objects to arrays when decoding job data

### ISSUE THREAD

**Issue by elazar** [laravel/framework#10682]
[This behavior](https://github.com/laravel/framework/blob/f4f1403219b54779fd44cd73acca3698c12d158c/src/Illuminate/Queue/Jobs/BeanstalkdJob.php#L54) has been in place since the switch from using PHP to JSON for serializing job data.

My expectation when I began using this code -- one in which I suspect I'm not alone -- was that, when I enqueued an object value, it would be identical in form / structure when it was dequeued.

This contrasts with the current behavior, where an enqueued object and any nested objects it contains will be converted to arrays when dequeued.

I personally consider this a bug, though I understand that's a matter of opinion. If there's consensus with my view, I'd be happy to submit a PR that changes this behavior and updates the tests.

I understand that this is a potentially breaking change. Until the next major release, a possible stop-gap measure might be to add a configuration setting that enables the new behavior. This setting could be deprecated and removed in the next major release when the new behavior is made the default. Again, if there's agreement with this approach, I'd be happy to submit a PR that implements it.

**Comment by GrahamCampbell** [comment]
We're open to PRs. 5.2 is the place for breaking stuff, or if it's after the 5.2.0 release, 5.3 please.
