### ISSUE TITLE
[Query Builder] New methods to Query Builder

### ISSUE THREAD

**Issue by PheRum** [laravel/framework#10687]
Hello, you can add new methods to work with the Query Builder such as insertIgnore, insertOnDuplicateKeyUpdate and more?
This methods have been implemented in this repository https://github.com/mrjgreen/database#on-duplicate-key-update

**Comment by rkgrep** [comment]
I don't think this is a good idea, since it is not supported in all databases.

**Comment by GrahamCampbell** [comment]
I agree.

**Comment by GrahamCampbell** [comment]
NB, in future, please direct all proposals more directly to Taylor, since we don't process proposal issues.
