### ISSUE TITLE
Discussion: Collection::unify()

### ISSUE THREAD

**Issue by rentalhost** [laravel/framework#10680]
I want write the `unify()` method to `Collection` class. But before do it, I need to know if it is welcome. I too need to improve the name (maybe *unify* don't be clear) and maybe Laravel yet support it with other name.

**Signature**:

    public function unify(): Collection;

**Behavior**:

It'll merge a *collection of collections|array* into a unique collection. It'll ignore all values that not is an accepted value.

**Example**:

    $users = collect(
        User::where(...)->get(), // Returns a collection of User (User#1, User#2)
        User::where(...)->get()  // Returns a collection of User (User#3, User#4)
        [ User#5 ],
        [ "accept" ]
        "ignore"
    )->unify();

    $users === collect(
        User#1,  // From first sub-collection.
        User#2,  // From first sub-collection.
        User#3,  // From second sub-collection.
        User#4,  // From second sub-collection.
        User#5,  // From the sub-array.
        "accept" // Because it comes from an array.
    );

**Real use case**:

It'll be useful in cases where you receives different collections that should be unified. The previous example is a good real use case example.

**To be discussed**:

The ignored (`"ignore"`) value should be part of return collection or should be ignored, as was?

**What will not do:**

This method will not *unique()* results, just merge. So if it have two `User#1` it'll be keep into result collection.

**Additionally**

Maybe the `array_unify()` can be implemented too, based on same concept, but returning an array instead of a collection.

**Comment by JosephSilber** [comment]
How is this different from `$collection->flatten()` and `array_flatten`?

**Comment by rentalhost** [comment]
`$collection->flatten()` or `array_flatten` on this case will not have any effect. It just will return an equal object. `array_flatten` works if I call `toArray()` on `$collection` first, but it'll converts all collection to array too.

**Comment by JosephSilber** [comment]
`array_flatten` in 5.2 [supports collections too](https://github.com/laravel/framework/blob/master/src/Illuminate/Support/Arr.php#L155-L172).

**Comment by rentalhost** [comment]
It works on 5.2! 

On really, I should just pass `$depth = 1` and it'll works perfecly. 
In this case, I think that a new method is not required here.
