### ISSUE TITLE
 Session not persisting,always lost session,TokenMismatchException in VerifyCsrfToken

### ISSUE THREAD

**Issue by timxd** [laravel/framework#10686]
laravel 5.1/XAMPP Version: 5.6.8/Windows 7 Ultimate SP1 64-bit/php 5.6.8

Always lost authentication session after login.

Got token mismatch exception when send post request.

TokenMismatchException in VerifyCsrfToken.php line 53:

I found this also a session issue.

There are many similar issue,if search "session" keyword.

https://laracasts.com/discuss?q=session

And I have not find any correct solution yet.

**Comment by GrahamCampbell** [comment]
Duplicate. Can usually be solved by using a session driver like redis. "file" isn't meant for production use.

**Comment by rkgrep** [comment]
Also may happen if you don't return response properly (e. g. call `exit` somewhere)

**Comment by timxd** [comment]
@GrahamCampbell 
@rkgrep 

Get back the lost session,if I run this code:

Route::get('session', function() { return Session::all(); });

Then print session:all()

There are something new in session data:

[_previous] => Array ( [url] => http://... ) [flash] => Array ( [old] => Array ( ) [new] => Array ( ) )

Whats the defferent?

**Comment by timxd** [comment]
I found a useful comment

https://github.com/laravel/framework/issues/9522

iLeoDo mentioned blade template

Then I made a simple form in a view without blade template,and its all correct now!??

**Comment by rkgrep** [comment]
iLeoDo had done same mistake, that I have described (interrupting the application before kernel termination).
As for session data, you have, - it is laravel internal variables for saving previous url and input.
