### ISSUE TITLE
Methods in Support\Collection should support "deep copy" for custom collections

### ISSUE THREAD

**Issue by alexweissman** [laravel/framework#10695]
Most of the non-idempotent methods in `Support\Collection` return a new `Collection`, constructed by calling `new static` with the `$items` member.  For example:

```
public function reverse()
{
    return new static(array_reverse($this->items));
}
```

Unfortunately, if I extend `Collection` with another class that has some additional member variables, and then call one of these methods, those additional member variables will not get copied.  For example:

```
class BoogerCollection extends \Illuminate\Database\Eloquent\Collection {

    // Metadata used by my collection
    protected $some_array = [];

    public function setArray(){
        $this->some_array = [1,2,3];
    }

    public function getArray(){
        return $this->some_array;
    }
}
```

If I call:

```
$collection = new BoogerCollection();
$collection->setArray();
print_r($collection->getArray());   // Prints out Array ( [0] => 1 [1] => 2 [2] => 3 )
```
everything works as expected.  But then if I call, for example, `reverse()` on this collection, the returned BoogerCollection will have an empty `$some_array`:

```
$collection = $collection->reverse();
print_r($collection->getArray());      // Prints out Array ( )
```

I propose that these methods (`reverse`, `diff`, `intersect`, etc) in `Collection` create the new object by first invoking `__clone` (which could be defined in the custom collection), and then updating the contents of `$items` in the cloned object before returning.

**Comment by c4pone** [comment]
I don't think that is a good idea. The collection should just hold it items and every action that changes the state of the items, creates a new Collection.

I would recommend creating a wrapper instead of extending the Collection class.

    class SomeClassNameThatMakesSense {
        protected $collection;
        protected $metadata;
        
        public function collection() {
            return $this->collection;
        }
        
        public function setMetadata($metadata) {
        //...
        }
        
        public function metadata() {
        //...
        }
        
        public function someMethodThatDepenceOnMetadataAndTheCollection() {
          $foo = array();
          foreach ($this->collection()->reverse()  as $item) {
             //do something
          }
        }
    }

    $foo = new SomeClassNameThatMakesSense();
    $collection = $foo->collection()->reverse();
    
    $foo->setMetadata(['lolcat']);
    $foo->someMethodThatDepenceOnMetadataAndTheCollection()


So as long as you have some action that depends on the collection and some data from the class make a new method in the wrapper.

When you want to add functionality that purely depends on the items of the collection, then extend the Collection and add the functionality there.

I hope that makes somehow sense.

**Comment by rkgrep** [comment]
I agree with @c4pone 
here is an alternative wrapper solution which requires less coding.
````php
class SomeWrapper
{
    public function __construct(Collection $collection, $metadata)
    {
        $this->collection = $collection;
        $this->metadata = $metadata;
    }

    // Your methods

    public function __call($method, $arguments)
    {
        return new static(call_user_func_array([$this->collection, $method], $arguments), $this->metadata);
    }

}
````
Example: 
````php
$meta = new SomeWrapper(collect(['foo', 'bar']), ['meta']);
$reversed = $meta->reverse(); //new SomeWrapper with same meta and modified collection
````
