### ISSUE TITLE
Throwing HttpException from app\Http\Request responds twice

### ISSUE THREAD

**Issue by gnarlycharlie4** [laravel/framework#10692]
Calling 

`abort(400, 'a message');` (thus) `throw new HttpException(400);`

from the controller works perfectly, but for some reason, calling it from the application's `app\Http\Request` class in an overridden `failedValidation` method yields 2 identical error responses.

I have not been able to solve it fully, but commenting out the implementation of `handleException($e)` at `\Illuminate\Foundation\Bootstrap\HandleExceptions.php` leads to abort() working correctly wherever it's called.

Thanks to anyone who gives this a read.  I'd be happy to zip up an example project upon request.

**Comment by GrahamCampbell** [comment]
The abort function should just throw an exception.

**Comment by gnarlycharlie4** [comment]
@GrahamCampbell, that's a great point.  
Calling `throw new HttpException(400);` from the overridden `Request` class has the same effect.
I'll update my original issue.

**Comment by GrahamCampbell** [comment]
Hmmm, let me investigate this.

**Comment by gnarlycharlie4** [comment]
Okay so I spun up a new project and the problem wasn't there.  This was my mistake.  
Thanks Graham, for looking into it. I apologize for the confusing false alarm.

If interested, the problem was that we injected our `CustomRequest` into a piece of middleware, thus baffling the whole system and somehow hitting the abort(400) method twice.

Thanks again, I hope to return the favor and try to answer someone else's impossible request in the future :)
