### ISSUE TITLE
URL::to with multi-dimensional array of $extra parameters

### ISSUE THREAD

**Issue by jbrooksuk** [laravel/framework#10706]
Say you have this array:

```
array(9) {
  ["itemcode"]=>
  string(5) "foo"
  ["nights"]=>
  string(1) "7"
  ["board"]=>
  string(2) "AI"
  ["dep_iata"]=>
  string(3) "Any"
  ["rooms"]=>
  string(1) "1"
  ["room"]=>
  array(1) {
    [0]=>
    array(1) {
      ["adults"]=>
      string(1) "2"
    }
  }
  ["max_child_age"]=>
  string(2) "12"
  ["month"]=>
  string(2) "10"
  ["year"]=>
  string(4) "2015"
}
```

Now you need to redirect to a route with the parameters:

```php
URL::to($request->path(), $options)
```

It will throw this error:

```
rawurlencode() expects parameter 1 to be string, array given
```

Because of the `to` method:

```
$tail = implode('/', array_map(
    'rawurlencode', (array) $extra)
);
```

**Comment by jairovsky** [comment]
`URL::to` Isn't intended to deal with associative arrays (there's no specification for this behaviour in `RoutingUrlGeneratorTest`). The fact that it works with single-level associative arrays is "just luck". If you really need this sort of behaviour I recommend creating a helper method to flatten your array.

**Comment by GrahamCampbell** [comment]
Going to close this since it's a feature request more than a bug report since it wasn't intended to work when it was implemented here. If anyone has a decent implementation of this, feel free to contact Taylor and see about a PR.
