### ISSUE TITLE
Support need for dynamic field validation 

### ISSUE THREAD

**Issue by IftekherSunny** [laravel/framework#10708]
@taylorotwell if you can please add support for dynamic field validation.

Eric L. Barnes shows a way to validate dynamic field on his [blog](http://ericlbarnes.com/laravel-array-validation/) But Its still hard to maintain when fields and rules increased !!!

So, If you make a support for dynamic field validation with syntax like as fieldName.* to handle dynamic field its more helpful.

**Comment by GrahamCampbell** [comment]
Sorry, we don't process proposal issues. Please contact Taylor more directly, or open a discussion on the forums.
