### ISSUE TITLE
Scope Query unable to return false (zero) instead Eloquent Builder returns an object

### ISSUE THREAD

**Issue by harishtoshniwal** [laravel/framework#10701]
Why dosen't the scoped queries return 0 when there is no data found for example on using the count() in the query and instead the Eloquent Builder returns an object. 
It should return false(zero) if nothing is found. Also, the Laravel Docs should be updated about this!

Shocked to see no attention has been paid to this important issue in the Laravel framework. 
I am sure there would have been many important discussions about it but no positive input or reaction from Taylor or respective collaborators.

Reference to some of those discussions: 
https://github.com/laravel/framework/issues/5405 (raised by @kyranb )
http://stackoverflow.com/questions/21373860/how-do-i-return-falsey-values-from-a-scope-query-in-laravel-4
http://stackoverflow.com/questions/20563166/eloquent-collection-counting-and-detect-empty

**Comment by dadopl** [comment]
Problem exists in laravel 5.4 👎 and return error "htmlspecialchars() expects parameter 1 to be string, object given..."

**Comment by lem93** [comment]
:-1:
