### ISSUE TITLE
5.1.20 Stopped My Routes Working

### ISSUE THREAD

**Issue by seivad** [laravel/framework#10702]
Hey after doing a quick composer update, it went from 5.1.10 to 5.1.20 and all my routes stopped working... did something dramatic change? 

I updated composer back to 5.1.10 and everything was fine, so I'll stick with that for now.

Cheers

**Comment by crynobone** [comment]
I update my Laravel to 5.1.20 and my routes works fine. So could you be more specific.

**Comment by GrahamCampbell** [comment]
Closing due to lack of info. Feel free to open a new issue if you want to provide more information.
