### ISSUE TITLE
[Cache: Suggestion] Partial/Segmented caching

### ISSUE THREAD

**Issue by vitor-faiante** [laravel/framework#10710]
Hi, I do not know if this is the best place to place feature suggestions and probably will be making a fool of myself but I just thought this could be a good feature to have. So I am slightly new to Laravel and I am currently doing a project (Laravel 4.2) that I wanted to cache the view for better performance on the site. 
However I had this part of the view that had to be random stories which totally messed up the idea of caching.

Initially I though of creating a partial for the area that was not dynamic and the do something like:

```php

public function show($storyId)
{
    $story = Api::get('stories/'.$storyId); // An API we built
    $storyContent = Cache::remember('story_content_'.$storyId, 60*24*7, function() use($storyId) {
        return View::make('stories.storyContent', [ 'story' => $story ])->render();
    });
    ...
    return View::make('stories.show', [ 'storyContent' => $storyContent, 'relatedStories' => $relatedStories]);
}

```

Now this was a bit convoluted and not as beautiful looking as the rest of Laravel. I would prefer something like this in a view:

```php

@cache('story_content_'.$story->id, 60)
    // HTML here
@endcache

```

Also having the capability to work with tags too would be amazing. I was told that some other frameworks have similar things like in Django and Ruby on Rails, but I know that as of now this does not yet work out of the box in Laravel. It would be a nice to have. Thanks for the time and sorry once again if I posted this suggestion in the wrong place.

**Comment by GrahamCampbell** [comment]
There are laravel packages out there that can do this for you. :)

**Comment by vitor-faiante** [comment]
@GrahamCampbell Hi I tried to have a look and the ones that I found are extremely old which I doubt that they are maintained anymore. Unless you know of any I did not manage then please do share as that would be helpful.

However on the other hand this is indeed something that could be considered to be made part of Laravel by default. Cmon I cannot be the only one thinking that this is very helpful for so many situations and projects instead of having to add yet another package when we could use something native. Like I said other frameworks which Laravel has some inspiration from have this kind of thing in them by default.
