### ISSUE TITLE
Don't import 

### ISSUE THREAD

**Issue by NitroBAY** [laravel/framework#10715]
When I do in routes :
get('lang/{n}', 'LanguageController@lang'); to ONLY return view "home" in controller my app don't import elements from a framework so my app is not stylised WHEREAS is do get('{n}' my app use the import and so my app is beautiful 
In all cases if I want to transmit {n} that works in my views

**Comment by rkgrep** [comment]
If you mean CSS `@import` then you should use leading slash, e. g. `@import('/css/file.css`')`
