### ISSUE TITLE
Optimize should consider custom vendor directory

### ISSUE THREAD

**Issue by IngwiePhoenix** [laravel/framework#10716]
I just installed L5.x and wanted to run the optimize command, and ran into this:

```
  [InvalidArgumentException]                                                                                                                                                                               
  Configuration file "/Users/Ingwie/Work/BIRD3/,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,  
  ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,," does not exist.                                                                                                                                               
```

Looking into `laravel/framework/src/Illuminate/Foundation/Console/Optimize/config.php`, I saw what the problem was, right away:

```
<?php

$basePath = $app['path.base'];

return array_map('realpath', [
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Container/Container.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Container/ContextualBindingBuilder.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Foundation/Application.php',
(...)
```

I don't use `vendor` as my PHP module path; in fact, I use `php_modules` to have a distinct diversity between NPM, PHP and Bower.

Hardcoding the vendor path seems a bit off, considering how flexible it is otherwise.

The only workaround I currently see is to resolve the config file somehow, then run over the arrays and `str_replace("/vendor/", $vendorPath, $val)`, but this is all but optimal.

**Comment by GrahamCampbell** [comment]
How can we get the vendor path then?

**Comment by GrahamCampbell** [comment]
> Configuration file "/Users/Ingwie/Work/BIRD3/,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,  
  ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,," does not exist. 

All those commas look like a bug in class preloader. Hmmm.

**Comment by GrahamCampbell** [comment]
Looks like you are using Laravel 5.0.x. Only 5.1.x is supported.

**Comment by GrahamCampbell** [comment]
I know this because that error can only be generated by class preloader 1.x, not 2.x, that Laravel 5.1 uses.

**Comment by GrahamCampbell** [comment]
I'm going to try to fix this on 5.1 for you, but you will need to upgrade to get the fix.

**Comment by GrahamCampbell** [comment]
How does this look? https://github.com/laravel/framework/pull/10763

**Comment by IngwiePhoenix** [comment]
I am indeed using 5.1 - after all, that is in my composer file too. :)

The fix looks like it'll work. We could extend the fix by utilizing the `config()` helper. As in, if the user specified `compile.vendorPath`, we could use that - alternatively fall back to the relative path variant you choose here.

**Comment by IngwiePhoenix** [comment]
Also, the commas came from the simple fact that all the filenames were `NULL`. So you'd get a good load of commas, I'd guess.

**Comment by IngwiePhoenix** [comment]
This should give you an idea of how I use Laravel.

https://github.com/DragonsInn/BIRD3/blob/yii1_to_laravel5/composer.json

I migrated from Yii1, so I did the installation part manually, as well as overriding a few classes to advance path structure.

**Comment by GrahamCampbell** [comment]
> "laravel/framework": "^5.1",

You should change that. Laravel does NOT follow semver, so `^5.1` is the equiv of `5.x|6.x|7.x|8.x`.

**Comment by GrahamCampbell** [comment]
> I am indeed using 5.1 - after all, that is in my composer file too. :)

Well the error you gave me there does not ever happen on Laravel 5.1.

**Comment by GrahamCampbell** [comment]
Please let me know if the PR I linked you to works. Please comment on the PR rather than here btw, since I tend to miss comments on closed issues.
