### ISSUE TITLE
Translator->has cannot work due to fallback_locale

### ISSUE THREAD

**Issue by llnk** [laravel/framework#10718]
If you need to check if a key is localized in a certain lang you can do: 

     $translator->has($id, $locale)) 

But if $id is localized in the fallback_locale that method will return true since it is defined as:

[Link to code](https://github.com/laravel/framework/blob/076a054b6c78888acb3d0b93030402dbf736d824/src/Illuminate/Translation/Translator.php#L61)

    /**
     * Determine if a translation exists.
     *
     * @param  string  $key
     * @param  string  $locale
     * @return bool
     */
    public function has($key, $locale = null)
    {
        return $this->get($key, [], $locale) !== $key;
    }

It simply checks if `get` returns something different than $key (that is true when it fallbacks to another locale). The check should work in another way

**Comment by zlatevbg** [comment]
I'm also looking for a solution about this problem.

I've just opened a thread here: https://laracasts.com/discuss/channels/laravel/determining-if-a-translation-in-specific-locale-exists

**Comment by GrahamCampbell** [comment]
I think this is the expected behaviour is it not? Maybe we need a param to force not using the fallback?

**Comment by zlatevbg** [comment]
We definitely need a way to check if a translation doesn't exist for a specific locale.

If we use the `Lang::has()` method with no $locale param then this method can use the fallback locale, but if we pass a $locale param it shouldn't use the fallback one when checking if the key exists.

**Comment by llnk** [comment]
Contex: I need a way to log whenever translation is used in a view doesn't exists (note: this should be logged by default). A possibile solution is:

```
  function trans_safe($id = null, $parameters = [], $domain = 'messages', $locale = null)
  {
    $translator = app('translator');

    if (is_null($id)) {
        return app('translator');
    }

    if (! $translator->has($id, $locale)) {
        \Log::warning("$id doesn't exist... ");
    }

    return app('translator')->trans($id, $parameters, $domain, $locale);
  }
```

So instead to use {{ trans('...') }} in a view you can use trans_safe('...') and get a log whenever that phrase hasn't been translated yet. The problem is that with fallback_locale you cannot get the right results.

A possibile workaround temporarily would be to set a nonexisting locale:

     config(['app.fallback_locale' => '--']);

**Comment by zlatevbg** [comment]
Another hack that I'm using now is to leave the translation key but with empty value like that:

```
// /lang/en/messages.php
return [
    'test' => 'ok'
]
```
```
// /lang/de/messages.php
return [
    'test' => ''
]
```
```
dd(empty(Lang::get('messages.test', [], 'de'))) // if true then translation doesn't exist!
```

However it would be great if when you pass a `$locale` to the `Lang::has()` method it doesn't fallback to the default locale and check for translation only in the passed locale files.
