### ISSUE TITLE
adding modules to laravel

### ISSUE THREAD

**Issue by mohamedsharaf** [laravel/framework#10729]
i founded this package
hope you have a look at it 
is there is any alternative to this in laravel ?
can i work in integration with the framework core ?

http://sky.pingpong-labs.com/docs/2.1/modules

https://github.com/pingpong-labs/modules

**Comment by brunogaspar** [comment]
Not everyone needs this kind of stuff, just use them as packages, that's their purpose.

**Comment by mohamedsharaf** [comment]
@brunogaspar 
may be not every one need it but it would be great feature for the framework

think of not having to group routes for all modules in one file routes.php

every module can have its own routes - controller - views - migrations - assets 
this will increase modules reusability 

i am new to laravel can u till me if i can separate routes - migration and views for each package

**Comment by rkgrep** [comment]
You can do everything via service providers and have custom content in every package.

Either use github and install via composer or make a directory inside your Laravel installation and add auoloading definition to composer.json.

**Comment by GrahamCampbell** [comment]
Yeh, this is already possible, and is already super flexible.

**Comment by mohamedsharaf** [comment]
think this will help new users specially  if you came from zf2 zend framework2 and u need to make modules this is the best way dont dig for any other users packages

http://laravel.com/docs/5.1/packages#introduction
