### ISSUE TITLE
lists() ambigous column

### ISSUE THREAD

**Issue by okneloper** [laravel/framework#10728]
Using lists() on a joined query when more than one table have the same column name results in a MySQL error: 
```php
<?php
DB::table('orders')
    ->join('order_products', function ($join) {
        return $join->on('order.id', '=', 'order_products.order_id')
            ->where('order_products.item_id', '=', ITEM_ID);
    })
    ->groupBy('order.id')
    ->where('order.paid', 1)
    ->lists('order.id');

// Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in field list is ambiguous' in ...
```
Caused by
https://github.com/laravel/framework/blob/5.1/src/Illuminate/Database/Query/Builder.php#L1592

**Comment by gnarlycharlie4** [comment]
Hey @okneloper, you may want to try dumping the sql by chaining  `->toSql()` to the end of your query there. If the problem is still a mystery, maybe post the sql to this thread.

**Comment by gnarlycharlie4** [comment]
You may find luck with `lists(DB::raw('order.id'))` which injects the plain string into the query rather than the sanitized and parsed string.

**Comment by okneloper** [comment]
HI @gnarlycharlie4,
Thanks for the comments. If you look at the code behind the link I provided inmy first post, you will see that DB::raw won't help. It's hardocded to remove anything before the dot.

**Comment by gnarlycharlie4** [comment]
@okneloper maybe you can user `->select(DB::raw("order.id AS order_id"))` and then just reference the aliased column with `lists("order_id")` ?

**Comment by Edgpaez** [comment]
There's no need to wrap in a `DB::raw(..)` the alias, but that's how you fix it:

```php
DB::table('orders')
    ->join('order_products', function ($join) {
        return $join->on('order.id', '=', 'order_products.order_id')
            ->where('order_products.item_id', '=', ITEM_ID);
    })
    ->groupBy('order.id')
    ->where('order.paid', TRUE) // I personally prefer over the not so clear 1
    ->select('order.id as order_id')  
    ->lists('order_id');
```

**Comment by okneloper** [comment]
Thanks, this solves my problem, but seems to be a little bit of a crunch - doesn't really fit the "elegance" laravel claims to offer.

So I don't agree this should be closed.
