### ISSUE TITLE
[Proposal] Add foreignExists or dropForeignIfExists to Blueprint Schema Builder.

### ISSUE THREAD

**Issue by EnolaLabs** [laravel/framework#10738]
There is a ```dropIfExists``` for tables, but no counterpart for foreign keys. If a migration or rollback tries to drop a foreign constraint that doesn't exists, an error is thrown. Likewise, if a table or column is attempted to be dropped with a foreign key that a developer does not know of, an error is thrown. Both are acceptable, but there is no abstracted way to determine if a foreign key constraint exists. Either adding a ```dropForeignIfExists``` method, or a simple boolean ```foreignExists``` method would be extremely helpful.

**Comment by rkgrep** [comment]
Your migrations should keep consistency in applying/rolling back.
If a foreign key appears out of nowhere in your schema, it is definitely an engineering mistake.

**Comment by EnolaLabs** [comment]
It's not a "mistake" if Laravel is being added to legacy software and has to account for large systems that may or may not be consistent across multiple replicated databases.
