### ISSUE TITLE
[Proposal] Resolve class via `event()` helper function

### ISSUE THREAD

**Issue by cabloo** [laravel/framework#10739]
I would like to be able to call

```
event('App\Events\Event', [$arg1, $arg2]);
```

instead of

```
event(app('App\Events\Event', [$arg1, $arg2]));
```

I'm not sure about best practice here, I use `app()` not for IoC injection in this case but to quiet PHP Mess Detector, which gives warnings when I use `new Event($arg1, $arg2)`.

**Comment by GrahamCampbell** [comment]
I'd consider it a bad practice to resolve events from the ioc rather than directly creating them. If you really want to, you can using that code sample though.

**Comment by GrahamCampbell** [comment]
Example of how I think events should be used: https://github.com/StyleCI/StyleCI/blob/master/app/Handlers/Commands/Repo/EnableRepoCommandHandler.php#L43.

Disclaimer: all projects are different, and StyleCI is using a very heavy architecture unsuitable for most small apps.

**Comment by cabloo** [comment]
@GrahamCampbell Worth noting that I edited my description shortly after posting to say

> I'm not sure about best practice here, I use `app()` not for IoC injection in this case but to quiet PHP Mess Detector, which gives warnings when I use `new Event($arg1, $arg2)`.

I don't use it for injection but have considered using the IoC container to resolve different instances of Events on different environments. I decided against it and perhaps that sort of (ab-)use of the system is what you're trying to avoid here.

As for StyleCI, I found their structure very interesting (using Commands to create Models, and validating them through Commands), do you happen to know if there's a name for that or any good documentation out there on that sort of structure or is it unique to StyleCI?
