### ISSUE TITLE
Multiple routes with the same signature, but different constraints

### ISSUE THREAD

**Issue by tpavlek** [laravel/framework#10736]
As far as I can tell this is currently unsupported behaviour, but what I'd propose is that a route like this:

```php
    get('persons/{id}', function ($id) {
        dd("matching numeric ID");
    })
        ->name('test2')
        ->where('id', '^[0-9,]+\d$');

    get('persons/{id}', function ($id) {
        dd("string name");
    })
        ->name('test1');
```

Essentially, I'd like to be able to perform different actions based on whether or not the provided argument matches the regex or not.

**Comment by rkgrep** [comment]
You should do matching inside controller/closure then.
