### ISSUE TITLE
php artisan not working with Carbon locale "de"

### ISSUE THREAD

**Issue by LMCom** [laravel/framework#10748]
**How to reproduce**:
Put this code in your autoload.php:

    Carbon::setLocale('de');

Use an artisan command, for example "php artisan list".

We can assume, that any other locale than "en" does not work.
This bug was not easy to find, since artisan does not output any error and nothing is written into the log.
The rest of the application works fine with locale "de" and behaves as expected.

**Comment by GrahamCampbell** [comment]
Thanks for the report.
