### ISSUE TITLE
Touching parent timestamps is not working

### ISSUE THREAD

**Issue by Krzysztofik8** [laravel/framework#10741]
There is a bug in function 
    
    public function touchOwners()
    {
        foreach ($this->touches as $relation) {
            $this->$relation()->touch();

            if ($this->$relation instanceof self) {
                $this->$relation->touchOwners();
            } elseif ($this->$relation instanceof Collection) {
                $this->$relation->each(function (Model $relation) {
                    $relation->touchOwners();
                });
            }
        }
    }

in Model.php, line 1646.

It should be *$this->$relation->touch();* instead of *$this->$relation()->touch();*

**Comment by Sladewill** [comment]
https://github.com/laravel/framework/blob/5.1/src/Illuminate/Database/Eloquent/Model.php#L1646

**Comment by rkgrep** [comment]
You are wrong.
`touch` method is in `Relation` class which is returned by method.
https://github.com/laravel/framework/blob/5.1/src/Illuminate/Database/Eloquent/Relations/Relation.php#L121

**Comment by Sladewill** [comment]
Either way that bit of code is wrong shouldn't have the dollar variable sign.

**Comment by rkgrep** [comment]
Why shouldn't it? `$relation` variable contains relation name, so `$this->$relation()` calls relation method.
````
protected $touches = ['user'];
// ...
foreach ($this->touches as $relation) {
    // $relation == 'user';
    $this->$relation()->touch(); // $this->user()->touch();
    //...
}
````
