### ISSUE TITLE
Docs: impossible to discover  what $factory is

### ISSUE THREAD

**Issue by rulatir** [laravel/framework#10743]
I am reporting this here as the documentation repo doesn't have "Issues".

URL: http://laravel.com/docs/5.1/testing#model-factories

The documentation doesn't say anywhere what the type of the $factory object is. It is not discoverable from that place. I can learn from the docs about the additional defineAs() method, but the rest of the factory API remains a mystery and I don't know where to look.

The ModelFactory.php file in its initial form doesn't contain any hints either. There is only one direct occurence of 'ModelFactory.php' as a string in all Laravel's php files, and it is not an include statement, so I can't even examine the context here. I could set a breakpoint in the file but I really, really, really, really shouldn't have to.

Please document what things are.

**Comment by Sladewill** [comment]
If you update it should be in the latest release, I done a pull req that got merged already see #10463.
