### ISSUE TITLE
Empty array passes 'string' validation rule

### ISSUE THREAD

**Issue by mfn** [laravel/framework#10747]
See the following examples:
```
$ php artisan tinker
Psy Shell v0.5.2 (PHP 5.6.14-1+deb.sury.org~trusty+1 — cli) by Justin Hileman
>>> $validator = \Validator::make( ['field' => []], ['field' => 'string'] );
=> Illuminate\Validation\Validator {#817}
>>> $validator->passes();
=> true
```
Shouldn't this *not* pass, i.e. return `false`?

Other non-string values seem to work OK:
```
>>> $validator = \Validator::make( ['field' => 0], ['field' => 'string'] );
=> Illuminate\Validation\Validator {#811}
>>> $validator->passes();
=> false
>>> $validator = \Validator::make( ['field' => new stdClass], ['field' => 'string'] );
=> Illuminate\Validation\Validator {#820}
>>> $validator->passes();
=> false
```

Tested with:
```
$ php artisan --version
Laravel Framework version 5.1.20 (LTS)
```

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell.

**Comment by Sladewill** [comment]
Looks like because its not got required it wont even bother hitting that rule.

**Comment by GrahamCampbell** [comment]
Hmm, that can't be correct.

**Comment by GrahamCampbell** [comment]
If it exists, then it must match the rule, even if not "required".

**Comment by GrahamCampbell** [comment]
Oh, right I see. The empty array evaluates as falsey, so it's treated as no input. Looks like the correct behaviour.

**Comment by taylorotwell** [comment]
So to get the behavior I think you are wanting you should do:

```
$validator = Validator::make(['field' => []], ['field' => 'sometimes|required|string']);
```

To explain, it sounds like the value isn't actually required on every request, but *if* it is present (sometimes) we want to require it to be a string.

**Comment by arrilot** [comment]
That doesn't look intuitive to me.
Why can't we just check whether the field is set instead of checking that it's not falsey?

**Comment by taylorotwell** [comment]
I agree this is unintuitive. I made this more sensible in 5.2. I can't do it in 5.1 because it is a slightly breaking change if people are posting the wrong types with their forms.

https://github.com/laravel/framework/commit/980d098ad091a5087a93202ebd4c091e336f3e58
