### ISSUE TITLE
Using limit(0) with Query Builder returns all items

### ISSUE THREAD

**Issue by orrd** [laravel/framework#10749]
Using the Query Builder with a limit() value of zero causes Laravel to ignore the limit.  This can cause some unexpected edge case issues for some code since devs assume that limit(0) would return no results.  I believe this is the underlying cause of https://github.com/laravel/framework/issues/9960 as well.

Looking at the Laravel Query Builder code, it looks like if the $limit value is <= 0, that is assumed to indicate that no limit has been set.  So a better design might be to use null to indicate the no limit has been set. I'm pretty sure a fix involves editing the database Grammars of the various database implementations.  I'm not sure I'm feeling confident enough with my familiarity with Query Builder's internals to come up with a PR for this one, but I can give it a shot if this is something that should be fixed and no one else wants to do it.

**Comment by rkgrep** [comment]
Do you really need to execute query statements with `LIMIT 0`? That's terrible.

**Comment by GrahamCampbell** [comment]
Looks like an issue with your app rather than us. You should never be executing a select limit 0.

**Comment by orrd** [comment]
There is an expected behavior for LIMT 0 that should be handled properly by the framework.

**Comment by taylorotwell** [comment]
Fixed in 5.1. Will be available in next tagged release.
