### ISSUE TITLE
Class autoload issue on make:migration

### ISSUE THREAD

**Issue by ssi-anik** [laravel/framework#10768]
I've set up PSR-4 for my library inside app folder. When I run composer dump-autoload -o it works fine. Inside my Library I've event subscriber class. But, today I found that whenever I use command "php artisan make:migration create_xyz_table" this does create the table. And when I create the model for that table says that the EventSubscriber class is not found. Then I created another migration and check the autoload_classmap file found that the migration file is autoloaded but the PSR-4 classes are skipped. What kind of problem can it be?

**Comment by GrahamCampbell** [comment]
You just need to make sure you run the dump autoload command after creating the kigrations.

**Comment by GrahamCampbell** [comment]
> I've set up PSR-4 for my library inside app folder.

You need a classmap onthe database folder.

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/laravel/blob/master/composer.json#L18
