### ISSUE TITLE
Route::uses vs Route::currentRouteUses vs the phpdoc vs usage

### ISSUE THREAD

**Issue by Grummfy** [laravel/framework#10761]
Hello,

The less usefull stuff, but I want to show it:
When I read the phpdoc  from \Illuminate\Routing\Router, I see that
currentRouteUses should be aliased by uses method , but the code was different, so it's not an alias. But it working in the same way, so it's ok, but an update of the phpdoc cool be good.

But the main issue is about the way it works :
* Route::getCurrentAction(); // that return App\Http\Controllers\Controller@action
* Route::currentRouteUses('App\Http\Controllers\Controller@action'); // that will true
* Route::uses('App\Http\Controllers\Controller@action'); // that will return true
* Route::currentRouteUses('Controller@action'); // that will return false
* Route::uses('Controller@action'); // that will return false

What people expect is this :
* Route::currentRouteUses('App\Http\Controllers\Controller@action'); // that will true
* Route::uses('App\Http\Controllers\Controller@action'); // that will return true
* Route::currentRouteUses('Controller@action'); // that will return true
* Route::uses('Controller@action'); // that will return true

Why? Because we define route with 'Controller@action' and not with 'App\Http\Controllers\Controller@action' even if in RouteServiceProvider we know that we set the namespace . So at least for the namespace of the app, uses and currentRouteUses method should work with short route definition.
We use the same shorcut for route redirection (\Illuminate\Routing\Redirector::action), so, for me, it should works the same for identifying current route.

thanks

the only related ticket I see about this issue was the ticket #10371

**Comment by GrahamCampbell** [comment]
I'm sorry, but the current behaviour really is correct. The controller is called `App\Http\Controllers\Controller` not `Controller`.

**Comment by GrahamCampbell** [comment]
If people are expecting `Controller` to work, perhapse they need to look at the code in the route service provider, and notice their is a group that prefixes the class name on registration.

**Comment by GrahamCampbell** [comment]
Thank you for your concern though. :)

**Comment by Grummfy** [comment]
Well, ok but why in \Illuminate\Routing\Redirector::action can we ue the shortcut Controller@action in this case?

**Comment by GrahamCampbell** [comment]
> Well, ok but why in \Illuminate\Routing\Redirector::action can we ue the shortcut Controller@action in this case?

Because of that code I talked about. Let me find it so I can link you to it.

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Support/Providers/RouteServiceProvider.php#L49

**Comment by GrahamCampbell** [comment]
That basically allow people to use that namespace, but should still remain mindful of the actual internal representation.

**Comment by Grummfy** [comment]
Yes I know it. It's what I talk when I speak about RouteServiceProvider that do this for everybody without knowing it.

but because route definition, for people who are not digging are Controller@action, because redirect and action are also with this shorcut form, perhaps we can see to add something to have something that works in the same direction.

**Comment by GrahamCampbell** [comment]
I do agree that this is somewhat confusing. Ping @taylorotwell. What do you think we can do here?

**Comment by Grummfy** [comment]
Perhaps we can add a new method for this.

**Comment by GrahamCampbell** [comment]
We're open to PRs.
