### ISSUE TITLE
Validator required_unless rule

### ISSUE THREAD

**Issue by CupOfTea696** [laravel/framework#10765]
Since that Laravel already comes with the `required_if` validation rule out of the box, I thought it would make sense to add a `required_unless` rule too. It would do the exact opposite, and require a field unless another field is set to value.

I've already got the function ready for the Validator, but I figured since I would need to make a Pull Request for this in both laravel/framework and laravel/laravel I thought I'd just open it as an issue.

```php
    /**
     * Validate that an attribute exists when another attribute does not have a given value.
     *
     * @param  string  $attribute
     * @param  mixed   $value
     * @param  mixed   $parameters
     * @return bool
     */
    protected function validateRequiredUnless($attribute, $value, $parameters)
    {
        $this->requireParameterCount(2, $parameters, 'required_unless');

        $data = Arr::get($this->data, $parameters[0]);

        $values = array_slice($parameters, 1);

        if (! in_array($data, $values)) {
            return $this->validateRequired($attribute, $value);
        }

        return true;
    }
```

**Comment by GrahamCampbell** [comment]
> I've already got the function ready for the Validator, but I figured since I would need to make a Pull Request for this in both laravel/framework and laravel/laravel I thought I'd just open it as an issue.

I appreciate this, but we don't actually process proposal issues. Please just send the PR in future. :)

**Comment by CupOfTea696** [comment]
So do I make two pull requests in laravel/laravel and laravel/framework?

**Comment by GrahamCampbell** [comment]
Just send one to laravel/framework, then see what Taylor thinks of it first. :)

**Comment by CupOfTea696** [comment]
Okay!

**Comment by codeblur** [comment]
This version does not seem to work. I think the correct version should be:

```php
    /**
     * Validate that an attribute exists when another attribute does not have a given value.
     *
     * @param  string  $attribute
     * @param  mixed  $value
     * @param  mixed  $parameters
     * @return bool
     */
    protected function validateRequiredUnless($attribute, $value, $parameters)
    {
        $this->requireParameterCount(2, $parameters, 'required_unless');

        $data = Arr::get($this->data, $parameters[0]);

        $values = array_slice($parameters, 1);

        if (in_array($data, $values)) {
            return false;
        }

        return true;
    }
```
