### ISSUE TITLE
Laravel authentication failing in IE

### ISSUE THREAD

**Issue by ajeeeunni** [laravel/framework#10769]
Authentication not working in Internet explorer and Edge. It was working well in all browsers in staging server. After switch to production server it's not working. When i check laravel's log I have found errors like given below

production.ERROR: 405 - Exception @ www.google.pl:443^M
exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in /home/user/public_html/sys
tem/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php:210
Stack trace:
#0 /home/user/public_html/system/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php(197): Ill
uminate\Routing\RouteCollection->methodNotAllowed(Array)
#1 /home/user/public_html/system/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php(145): Ill
uminate\Routing\RouteCollection->getOtherMethodsRoute(Object(Illuminate\Http\Request), Array)
#2 /home/user/public_html/system/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1054): Illuminate\
Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#3 /home/user/public_html/system/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1022): Illuminate\
Routing\Router->findRoute(Object(Illuminate\Http\Request))
#4 /home/user/public_html/system/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\
Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#5 /home/user/public_html/system/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illu
minate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#6 /home/user/public_html/system/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illu
minate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#7 /home/user/public_html/system/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Fou
ndation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#8 /home/user/public_html/system/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\
Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#9 /home/user/public_html/system/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Sess
ion\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#10 /home/user/public_html/system/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Coo
kie\Queue->handle(Object(Illuminate\Http\Request), 1, true)

**Comment by GrahamCampbell** [comment]
Doesn't look like a bug in Laravel, sorry.

**Comment by GrahamCampbell** [comment]
Feel free to ask for help on the forums though.
