### ISSUE TITLE
Model events (C/S/U/D) not firing when acted on via a relation

### ISSUE THREAD

**Issue by shazamjad** [laravel/framework#10770]
There's a few issue's that reference model events for related models; but in my use case I don't really need to know if it was an attach/associate/detach/pivot etc - I'd be very happy to have the basic saving/saved/updating/updated/creating/created/deleting/deleted events fire on the model that has been action on via a related model (wether that's via a `->relation()->save()`, `->attach()` etc).

Actually I'm not too sure if that should be happening already or not - but in my case it isn't.

To give context on my use case - I have a redis cache of `ids` that have a specific attribute; and these items are acted on both via a relation or on their own - I get the model events to update the redis cache but it only ever triggers when the model method is called on it's own (not via a relation).

**Comment by GrahamCampbell** [comment]
I think this is intended? Ping @taylorotwell.
