### ISSUE TITLE
Laravel Route Model Binding to Route::controller()

### ISSUE THREAD

**Issue by hulu8004** [laravel/framework#10772]
I haven't seen anything referencing this, please let me know if it doesn't exists yet.

I've got the following routes:

    Route::controllers([
        'auth' => 'Auth\AuthController',
        'password' => 'Auth\PasswordController',
        'admin' => 'AdminController',
        'site' => 'SiteController'
    ]);
And then I've got the following method in the `SiteController`:

	/**
	 * Get site details and pass to view
	 *
	 * @param Site $site
	 * @return mixed
	 * @internal param $site_id
	 */
	public function getDetails( Site $site )
	{
	    return $site;
	}
When I go to the URL `site.com/site/details/13` it doesn't return the site object.

I've added `$router->model( 'one', 'App\Site' );` into the `RouteServiceProvider` and it works, but what if later down the road I want to add another controller like this but use it for `jobs`, and use the `getDetails` method again and pass through the `App\Job` object? It will automatically send the `App\Site` model instead.

So is there a way I can prevent this from happening?

**Comment by rkgrep** [comment]
Related #10659

**Comment by hulu8004** [comment]
Are you saying there is a way to work around this? Cause I just read a couple issues related to the one you posted and I couldn't find a solution.

**Comment by rkgrep** [comment]
Unfortunately, no. Looks like you will have to define routes manually, instead of using `controller` method.

**Comment by hulu8004** [comment]
That's a lot of methods though, is there anyway something like this can be put in a later version?
