### ISSUE TITLE
[Proposal] Allow passing route parameters to middleware

### ISSUE THREAD

**Issue by phroggyy** [laravel/framework#10788]
Currently, route middlewares can be used as

```
$router->get('/', ['middleware' => 'role:editor', function () {
    // ...
}]);
```

However, I believe it would be convenient if we could have something like

```
$router->get('{subdomain}', ['middleware' => 'tenant:{subdomain}', function () {
    // ...
}]);
```

Thoughts and opinions?

**Comment by glorand** [comment]
In the middleware, you can access the Request object. ( \Illuminate\Http\Request $request )

**Comment by GrahamCampbell** [comment]
Yeh, I don't think we need to make the router any more convoluted than it already is.
