### ISSUE TITLE
Injected request parameter gets lost when using Form Request Validation

### ISSUE THREAD

**Issue by guilhermecvm** [laravel/framework#10791]
If we inject a parameter on a request on a Middleware, if we try to get this parameter in a controller using a form request validation, this parameter doesn't exists.

```php
<?php
class TestMiddleware {
	public function handle($request, Closure $next)
	{
			$request[name'] = 'Guilherme';
			return $next($request);
	}
}
```

```php
<?php
class TestRequest extends Request {
    public function rules()
    {
        return ['id' => 'required'];
    }
}
```

```php
<?php
class TestController extends Controller
    public function test(TestRequest $request)
    {
        return response()->json($request->all()); // 'name' doesn't exists
    }
```

```php
<?php
class Test2Controller extends Controller
    public function test(Request $request)
    {
        return response()->json($request->all()); // 'name' exists
    }
```

**Comment by glorand** [comment]
If you want to edit your request in a Middleware do it in this way. Check in your request validate class or controller, the 'name' will exists
``` php 
class TestMiddleware {
    public function handle($request, Closure $next)
    {
            $request_array = $request->all();
            $request_array['name'] = 'Guilherme';
            $request->replace($request_array);
            return $next($request);
    }
}

 ```

**Comment by athletto** [comment]
@glorand I tried the snippet you provided. The injected parameter is available within the middleware (obviously). However, it is not available in the controller nor in the request validate class.
The code sample given by @guilhermecvm is similar to the scenario I am talking about.

@guilhermecvm Can you confirm if @glorand 's workaround resolved you issue?

**Comment by guilhermecvm** [comment]
@athletto, unfortunately sniped provided by @glorand didn't work. :(

**Comment by sisve** [comment]
1) Request comes in and is matched against a route. The router is firing the router.matched event.
https://github.com/laravel/framework/blob/5.1/src/Illuminate/Routing/Router.php#L665
https://github.com/laravel/framework/blob/5.2/src/Illuminate/Routing/Router.php#L697

2) The FormRequestServiceProvider listens on router.matched and initiates FormRequest objects by copying all data from Request to the FormRequest object.
https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Providers/FormRequestServiceProvider.php#L45-L62
https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Providers/FoundationServiceProvider.php#L63-L81

3) The middlewares execute with the original Request.
https://github.com/laravel/framework/blob/5.1/src/Illuminate/Routing/Router.php#L673-L675
https://github.com/laravel/framework/blob/5.2/src/Illuminate/Routing/Router.php#L699

Your behavior matches this; when working with the FormRequest you get what the Request object contained before your middleware executed, when working with Request you get the actual Request object which you have modified.

**Comment by thebrubaker** [comment]
I'm having the same issue, I'm trying to turn a base64 string into an image so that I can validate and then save it appropriately. But with merge, or even replace, I can't get it to my FormRequest or Controller. Middleware would be a great place for me to manage this code, and I'm not really sure where else to handle this to make validation work.

Does anyone know a work around or a better method? Here is a link to my middleware: http://laravel.io/bin/KkOd7

Sounds like I need to move this transformation into the FormRequest object. I wonder which method is best to do this.

**Comment by thebrubaker** [comment]
By the way, the merged values are available on the Request object in a parameter bag: $request->request->all()

That might help someone along the way.

**Comment by athletto** [comment]
@thebrubaker As @sisve explained, the param that is merged in the middleware will not be present in the FormRequest object, as the Form request is created before the middleware is processed. If you would like to validate the input params, you could inject the FormRequest to the controller. However, if you want to access the param added in the middle, inject the Request object as well to the controller.
Below is an example of what worked for me:

`
<?php
class TestController extends Controller
    public function test(Request $request, TestRequest $formRequest)
    {
        return response()->json($request->all());
    }
`

**Comment by thebrubaker** [comment]
@athletto that's an interesting approach, I didn't think to add the Request as another dependency into the Controller method. But at the end of the day, I always knew how to access the properties manually. They actually exist on the FormRequest object under $formRequest->request->all() (which is not called on the nifty validator trait that the rest of my app works with). I ended up solving my problem manually on the FormRequest, but the Middleware seemed like a better, more logical place to make the transformation.

I've seen Taylor add in headers, modify cookies, etc through middleware and it definitely just feels like the right place for this, but the way the FormRequest object works currently, its not going to be setup to modify input on a middleware level.

So basically the answer to anyone asking is: you should not modify Request input through Middleware in laravel's current design. You will need to modify it either in the FormRequest object or at the Controller level. If you need the input modified for the automatic trait validation, you should override the all() method on your FormRequest to merge in the attributes, and then return array_replace_recursive($this->input(), $this->allFiles())

Here was my final solution as a trait that I can add to FormRequests that need to modify base64 strings into images going into the app:

```
<?php

namespace Support\Base64;

/**
 * For use on FormRequest Objects only
 */
trait DecodesBase64ImagesTrait
{
  /**
  * Modify all() to decode base64 into an image and replace it on the request
  * @return array
  */
  public function all()
  {
    $decoder = app(Base64Decoder::class);
    if ($this->has('image') && $data = $this->get('image')) {
      $decoder->createImage($data, function($image) {
        $this->merge(['image' => $image]);
      });
    }
    // This is unmodified from what is called on the parent all() method
    return array_replace_recursive($this->input(), $this->allFiles());
  }
}
```

**Comment by pleckey** [comment]
Simple (hopefully temporary) solution ... 

In the abstract `Request` class that ships with Laravel at `app/Http/Requests/Request.php`, I simply changed to the following:

```php
<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

abstract class Request extends FormRequest
{
    public function all()
    {
        /*
         * Fixes an issue with FormRequest-based requests not
         * containing parameters added / modified by middleware
         * due to the FormRequest copying Request parameters
         * before the middleware is run.
         *
         * See:
         * https://github.com/laravel/framework/issues/10791
         */
        $this->merge( $this->request->all() );

        return parent::all();
    }
}
```

This allows it to work as expected with input parameters added in middleware, custom requests, etc. as long as they extend this class.

**Comment by mcblum** [comment]
It would be awesome to see this fixed!

**Comment by rotorsolutions** [comment]
The fix from @pleckey did not work for me at once. (I also use Dingo).

Changing the line to this, did work:

`
$this->merge(\Request::all());
`

**Comment by fumpierrez** [comment]
has this been fixed for recent versions of Laravel?

**Comment by sisve** [comment]
@fumpierrez No, but you're welcome to submit a PR that does it. However, it will be hard since the Request instance differs from the FormRequest instance. Perhaps let the FormRequest instance have real references to the original parameter bags to keep up with any changes?

**Comment by byrnedo** [comment]
Is there a concept of 'Context' in laravel for this kind of thing? So one would just add it to the context object/array instead?

**Comment by socheatsok78** [comment]
I created a middleware for transform `Base64` input into `Illuminate\Http\UploadedFile` instance but each time the `file` failed to upload even though the request already submitted.

Here the Middleware I create base on the `Illuminate\Foundation\Http\Middleware\TransformsRequest`.

https://gist.github.com/socheatsok78/73e2de210b28f3254b1621744916e226

My controller:
```php
public function store(AvatarRequest $request, Model $model)
{
    if (!$request->has('file')) {
        return;
    }

    $file = $request->file('file');
    $path = $file->storePublicly('public/avatars');

    // ...
}
```

The above controller will return `422` error code with the following response:
```json
{
  "message": "The given data was invalid.",
  "errors": {
    "file": [
      "The file failed to upload."
    ]
  }
}
```

Without using `AvatarRequest` and use the regular `Illuminate\Http\Request` the following code work fine and the file is successfully saved to the storage.
```php
public function store(Request $request, Model $model)
{
    if (!$request->has('file')) {
        return;
    }

    $file = $request->file('file');
    $path = $file->storePublicly('public/avatars');

    // ...
}
```

So is there another way that I can transform the request without this issue?

Here a dump result of my request before & after transformed the input into `Illuminate\Http\UploadedFile`:

![Screen Shot 2020-01-10 at 4 21 15 PM](https://user-images.githubusercontent.com/4363857/72141472-8455a280-33c5-11ea-85a3-081a97b05455.png)
