### ISSUE TITLE
Can we expand \Illuminate\Filesystem\FilesystemAdapter::put with $customConfig ?

### ISSUE THREAD

**Issue by mfn** [laravel/framework#10804]
Currently the implementation of `\Illuminate\Filesystem\FilesystemAdapter::put()` does not allow to provide arbitrary `$config` parameters for the destination disk, which sometimes would be useful. Code from master:
```PHP
    public function put($path, $contents, $visibility = null)
    {
        if ($visibility = $this->parseVisibility($visibility)) {
            $config = ['visibility' => $visibility];
        } else {
            $config = [];
        }
        if (is_resource($contents)) {
            return $this->driver->putStream($path, $contents, $config);
        } else {
            return $this->driver->put($path, $contents, $config);
        }
    }
```
A possible fix could be add a fourth optional parameters `$customConfig`, like this:
```PHP
    public function put($path, $contents, $visibility = null, array $customConfig = [])
    {
        if ($visibility = $this->parseVisibility($visibility)) {
            $config = ['visibility' => $visibility];
        } else {
            $config = [];
        }

        $config += $customConfig;

        if (is_resource($contents)) {
            return $this->driver->putStream($path, $contents, $config);
        } else {
            return $this->driver->put($path, $contents, $config);
        }
    }
```
But before producing a PR:
- would this be acceptable?
- If not, are you open to another solution for this, do you have a suggestion?

To achive this currently, I've to:
- bind my own instance of `FilesystemManager` to override `adapt`
- provide my own `FilesystemAdapter` implementation to contain a separate `putWithConfig`
- in my actual code, I've to ensure that my own `FilesystemAdapter` is the actual disk instance before calling `putWithConfig`

For some perspective, as to why:
I upload my assets to S3 with a custom header which I can pass as another `$config` parameter, as long as it's exposed.

I know the proposed change isn't really nice, because the disk abstraction is generic and the config is definitely driver specific!

**Comment by GrahamCampbell** [comment]
That would be a bad design decision imo. If you need different config, create a new object to do that. That's why we have objects.

NB Creating a new object is just done through adding a new connection and accessing it via the manager class.
