### ISSUE TITLE
Add names to index caches - Allow multiple caches of the same type. 

### ISSUE THREAD

**Issue by Aner-Git** [laravel/framework#10800]
When using the cache interface there is no way to create named  caches of the same type. 

This feature may not make sense for all cache drivers, but for some it is useful, for example, named array caches. 

So I might have a named Array cache  'Users' for user-IDs and another for Hobbies for hobbies-id. 

Since user-id, hobby-id might have the same keys type (say ints), it is useful to have both (otherwise the keys can  'clash', )  . 

The interface might look like this:

 $mgr = new CacheManager(....); 

$users = $mgr->namedStore('User' , 'array'); 

$hobbies = $mgr->namedStore('Hobby', 'array');

**Comment by jairovsky** [comment]
I think [Cache Tags](http://laravel.com/docs/5.1/cache#cache-tags) can solve your problem if you're using a cache store other than Filesystem and Database.
