### ISSUE TITLE
Parse Environment variables to PHP Data Types

### ISSUE THREAD

**Issue by jpcercal** [laravel/framework#10809]
Hi guys,

I wrote a library to get values from environment variables and parse to the PHP data types. This library can be used to parse environment variables to PHP data types (like the casting to integer, float, null, boolean), parse the complex data structures like a JSON string and more with the contribution of the commnunity.

I opened a issue to phpdotenv project, and it was accept:
https://github.com/vlucas/phpdotenv/issues/121

Actually your code is used to parse some values here (boolean, empty and null):
https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/helpers.php#L292

I suggest to implement my library and put the responsability on it (my library is 100% covered by php unit tests and is following the PHP-FIG patterns PSR-2 and PSR-4).

Thanks! I appreciate your suggestions.

**Comment by GrahamCampbell** [comment]
Thanks, but this can be tracked on the phpdotenv repo.

**Comment by jpcercal** [comment]
@GrahamCampbell @taylorotwell i believe that this component is interest to this project. The focus of phpdotenv project is load the environment variables and not get your values. Different of your purpose, where is necessary get the data and frequently pass on validation process like the if statement.

By example: 
export ENV_BOOLEAN_TRUE=true
export ENV_BOOLEAN_FALSE=false

// the expression result true
if (Environment::get("ENV_BOOLEAN_TRUE")) { ... }

// the expression result false
if (Environment::get("ENV_BOOLEAN_FALSE")) { ... }

Otherwise without this library:

export ENV_BOOLEAN_TRUE=true
export ENV_BOOLEAN_FALSE=false

// the expression result true
if (getenv("ENV_BOOLEAN_TRUE") === "true") { ... }

// the expression result true
if (getenv("ENV_BOOLEAN_FALSE") === "false") { ... }

It is a simple example, and the library supports more resource types, like: boolean, numeric (int and float), null, json, array and unknown. See the https://github.com/jpcercal/environment/blob/master/README.md to more details.

Thanks.

**Comment by GrahamCampbell** [comment]
> i believe that this component is interest to this project.

Yes, but if you want that changing, it needs doing on that repo. I'm a collaborator there too.

**Comment by jpcercal** [comment]
Why is it needed to do this?

**Comment by jpcercal** [comment]
?
