### ISSUE TITLE
[Proposal] Add Query String to Named Routes Generator

### ISSUE THREAD

**Issue by ileodo** [laravel/framework#10801]
As @ghost mentioned in issues https://github.com/laravel/framework/issues/935
> Add Query String Arguments Named Routes Generator
> It would be really nice to be able to append query strings to named routes, particularly when redirecting.
> `URL::route('docs')->withQuery('hello' => 'world');`
> `return Redirect::route('docs')->withQuery('hello' => 'world');`

I think this feature is very important, especially in the case that we want to generate a url representing a GET request. So that this GET request can be processed by `Http\Request` class(`authrized()`,`rule()` etc.)

As for the reply from @JoostK :
> Any key you provide which is not part of the URI route is already added as query param.

If only use controller action but not url to define route, the feature he mentioned doesn't work any more, So I think this feature is very necessary.

**Comment by su-xiaolin** [comment]
same question

**Comment by rkgrep** [comment]
related #10920

**Comment by GrahamCampbell** [comment]
We're open to PRs.
