### ISSUE TITLE
Config::get does not find a config item if the key contains dots ('.')

### ISSUE THREAD

**Issue by facundofarias** [laravel/framework#10818]
Hi there!
I am migrating from Laravel 4 to Laravel 5.1, quite hard though :/. One the things that I've found, but I am not sure if it is by design or not, is the following:

Let's suppose I am trying to get a config, in this way ``` Config::get('app.test.test') ```, I do have the app.php file on the config folder, with the entry ```'test.test' => true,```, but it cannot be resolved, and it results NULL.

Now, if I change the entry name to 'test_test', it does work. So, it seems to be some kind of issue when the entry name contains dots. Is that correct?

Thanks!

**Comment by GrahamCampbell** [comment]
Sorry, this is the intended behaviour.

**Comment by facundofarias** [comment]
@GrahamCampbell so the keys cannot contains dots? Is there any way to escape them?

**Comment by darthmaim** [comment]
Instead of `'test.test' => true` you could write `'test' => ['test' => true]` in your config.

**Comment by anteriovieira** [comment]
I agree

**Comment by facundofarias** [comment]
@darthmaim Since in the language resource files the dots are allowed, shouldn't be allowed here as well? (I mean, only to be consistent).
