### ISSUE TITLE
First character capitalization in month names

### ISSUE THREAD

**Issue by mikeher** [laravel/framework#10813]
https://github.com/laravel/framework/commit/f250dc75fa0bbfc2ccf071836cab4e038d971895

Most countries (all except English and German speaking countries?) do not capitalize month names, so how about adding a ucfirst() around the strftime()? Without capitalization the result doesn't always look too good:
![glaedelig_jul](https://cloud.githubusercontent.com/assets/5235664/10963775/297079f2-83a3-11e5-9951-3f0378b42294.jpg)
(Danish)

Also, maybe I am doing something wrong, but I wasn't able to use the localized names without setting the locale with php manually:
```
setlocale(LC_ALL, 'da_DK'); // Danish
```
Of course that's fine, but this is a piece of Laravel centric code. I would expect the locale setting in the app config file to be enough. Since PHP's setlocale() method is never called from the Laravel application, I assume there's a good reason for this.

I know there was an issue about this where it was discussed whether the localization should come from php's locale settings or a laravel language file. Why at least not check if such a language file exists before defaulting to php's locale?

Another solution would be to be able to override the month names by passing along an array with the proper names.

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell.

**Comment by mikeher** [comment]
Thanks @GrahamCampbell 

Now that we're pinging people, let's ping Mr. Way (the original contributor) :-)

Ping @JeffreyWay

**Comment by mikeher** [comment]
I made a somewhat shitty pull request, forcing me to realize it is perhaps not convenient utilizing the translator module within the formbuilder.

https://github.com/laravel/framework/pull/10815

I would however still suggest wrapping the strftime() call with ucfirst() to avoid the capitalization issue I first described.
```
$months[$month] = ucfirst(strftime($format, mktime(0, 0, 0, $month, 1)));
```

**Comment by rkgrep** [comment]
`strftime('%B')` already returns capitalized month names, so it looks like your local system bug.

https://3v4l.org/85hgA

**Comment by mikeher** [comment]
@rkgrep My friend. I think you need to read my issue one more time. The problem only exist on non-english and non-german locales ;-)

**Comment by crynobone** [comment]
@mikeher While this may be a valid argument, HTML components has been deprecated (no longer maintain in the core). Which version of Laravel are you using at the moment?

**Comment by GrahamCampbell** [comment]
That's true.
