### ISSUE TITLE
Iron MQ error 400 A reservation_id is required

### ISSUE THREAD

**Issue by justmyfreak** [laravel/framework#10828]
Hi,

I'm using Laravel 5.1 and Iron MQ 4.0.1
I encountered error when calling $job->delete();

```
 [IronCore\HttpException]
  http error: 400 | {"msg":"A reservation_id is required"}
```

I've tried Iron MQ v 2 as suggested on Laravel 5.1 documentation, but I got error that I need to use v3 API, so I updated Iron MQ to 2.*

Thanks

**Comment by GrahamCampbell** [comment]
We only work with the 2.x package.

**Comment by GrahamCampbell** [comment]
The 4.x package must require that new field.

**Comment by GrahamCampbell** [comment]
Maybe you need to enable the older version of the API on your control panel or something?

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell. You use IronMQ don't you?

**Comment by davzie** [comment]
I also am having this issue on Laravel 4.2 with Version 3.* of IronMQ. Can't seem to find a way to activate the legacy API for IronMQ so we can use a different branch either. It looks like the job can't be removed though!

**Comment by GrahamCampbell** [comment]
> I also am having this issue on Laravel 4.2 with Version 3.* of IronMQ.

You CAN NOT use 4.x in Laravel 4.2. You MUST use 1.x as documented.

**Comment by davzie** [comment]
It may be documented mate, but it doesn't work. I think IronMQ turned off anything that isn't API v3 from working. At least that was the response messages I was getting back.

**Comment by GrahamCampbell** [comment]
> but it doesn't work.

It's not meant to. API v3 can't be used on Laravel at all yet. Soon it'll be available on 5.1+.

**Comment by davzie** [comment]
Do you feel it may be better for me to not use IronMQ for this project then and to utilise SQS?

**Comment by davzie** [comment]
Graham plz

**Comment by taylorotwell** [comment]
Sure try SQS.

**Comment by davzie** [comment]
Hah! Thanks T-dog.

**Comment by robclancy** [comment]
Was this ever fixed? Why is it closed?

**Comment by davzie** [comment]
Cause programming ¯\_(ツ)_/¯
