### ISSUE TITLE
saving json data after a cast.

### ISSUE THREAD

**Issue by thedangler** [laravel/framework#10826]
I'm casting my saved json data to an array for example say I have '{"foo" : 1, "bar": 3}'
in my postgresql DB and i get it out of the model it does get turned into an array correctly.
However if I add to the array and json_encode(changed_array) and save it
it gets saved out like "{\"food\":1,\"bar\":3,\"new\":2}"
This breaks the cast if I want to edit it ever again.
 When I try to pull that back out with the cast it comes back as a string and never gets cast as an array.  
How do I get around this.  it should leave it as a normal string '....' and no escape the "

**Comment by rkgrep** [comment]
Could you provide a code example here?

**Comment by thedangler** [comment]
// in the model
// ClientSlideProgress 
protected $casts = ['completed' => 'array']

// controller

$clientProgress = ClientSlideProgress::firstOrNew(['user_id' => Auth::user()->id]);

$completed = $clientProgress->completed;

//first time set up a blank json object
        if($completed == Null) {

            $completed = ["completed" => ["chapter" => [],"volume"=>[]]];

        }

       // some other crap

       $completed['completed']['chapter'][] = $current_slide->chapter_id;

        $completed = json_encode($completed);
        //$clientProgress->completed = $completed    // doesn't work saves it out with double quotes and escaped quotes  ex: "{\"food\":1,\"bar\":3,\"new\":2}"
        $clientProgress->save();

        // hack because saving json is broken
        DB::update('update client_progress set completed = ? where user_id = ?',[$completed,Auth::user()->id]);

**Comment by rkgrep** [comment]
Just don't use `$completed = json_encode($completed);` - Eloquent converts arrays to json automatically if casting is present.
