### ISSUE TITLE
dev_providers

### ISSUE THREAD

**Issue by halaei** [laravel/framework#10842]
I like to use `barryvdh/laravel-ide-helper` and `barryvdh/laravel-debugbar` while developing, but don't need them to be installed in production. Therefore I was thinking of putting them in require-dev in composer.json file. But the problem is that these packages need to have service provides registered in app.php providers array and running `composer install --no-dev` will lead to fatal errors. So they have to be somehow remove for every deployment.

I am now thinking if it is a good idea to have a `dev_providers` array in app.php that works exactly as `providers` array except that it tells Laravel to ignore the classes that do not exist.

**Comment by RomainLanz** [comment]
You should register the ServiceProvider in your `app/Providers/AppServiceProvider.php`.

```php
public function register()
{
    if ($this->app->environment() == 'local') {
        $this->app->register(ServiceProvider::class);
    }
}
```

**Comment by halaei** [comment]
That will also do. Thanks @RomainLanz

**Comment by halaei** [comment]
just to make sure
```php
        if ($this->app->environment() == 'local' && class_exists(IdeHelperServiceProvider::class)) {
            $this->app->register(IdeHelperServiceProvider::class);
        }

```
