### ISSUE TITLE
Something for the schema

### ISSUE THREAD

**Issue by dlmwolf** [laravel/framework#10844]
I know i need something like `->Comment()`.
And i find in issues and pull requests.
I see something like #3462 ,
I want to know the code must like what to into laravel.
thank for your time.

**Comment by dlmwolf** [comment]
And how to make a column to bit.

**Comment by GrahamCampbell** [comment]
We don't support adding comments, sorry.

**Comment by dlmwolf** [comment]
Ok,get this.Thank for your time.
