### ISSUE TITLE
Rendered variables interpreted as Blade commands

### ISSUE THREAD

**Issue by mromnia** [laravel/framework#10849]
I have an extremely simple case - I'm trying to render "@parent" (a string with that content) into a Blade view that extends another view. It seems the input is interpreted as the `@parent` command instead, and inserts the parent section's contents.

Full code demonstrating the bug, along with a failing unit test, can be found here: https://github.com/mromnia/laravel-bug

To further explain what I'm doing, the parent view (called main) has this section:

```
@section('content')
This is the parent view.
@show
```

The child looks like this:
```
@extends ('main')

@section('content')
@{{ $testInput }}
This is the child view.
@endsection
```

Everything is fine as long as `$testInput` is not `@parent`. If it is, this is what is getting rendered:
```
This is the parent view.
This is the child view.
```

Interestingly enough, I couldn't get it to work with `@include` or any other command.

**Comment by GrahamCampbell** [comment]
Thanks, but this is actually a duplicate. :)

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/issues/10068
