### ISSUE TITLE
[5.1] Clear column aliases break 'as' query for pagination

### ISSUE THREAD

**Issue by annamiy** [laravel/framework#10855]
I am using pagination with some filters and I'm stuck with aliases field.

So, I calculate 'age' from the 'birth_date' field and I'm trying to get all users above 40 years, for example
```php
$age = DB::raw('(YEAR(CURRENT_TIMESTAMP) - YEAR(birth_date) - (RIGHT(CURRENT_TIMESTAMP, 5) < RIGHT(birth_date, 5))) AS age');

$users = User::orderBy($sortField, $sortOrder)
                   ->where('age', '>=',  $ageFrom)
                   ->paginate(15, ['users.*', $age]);
```

it gives me mysql error
```mysql
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'age' in 'where clause' 
(SQL: select count(*) as aggregate from `users` where `users`.`deleted_at` is null 
and `age` >= 40)
```

If I remove aliases everything will be ok. But it isn't solution.
I determined that method clearSelectAliases which was added in https://github.com/laravel/framework/issues/9993 is cutting 'as' from select part
```php
clearSelectAliases($columns) from the /Illuminate/Database/Query/Builder.php 
```

Thanks

**Comment by GrahamCampbell** [comment]
Closing due to the PR.
