### ISSUE TITLE
Upgrade guide

### ISSUE THREAD

**Issue by pjebs** [laravel/framework#10859]
I started my project in Laravel 5.
I've decided to upgrade to Laravel 5.1 now.

The upgrade guide doesn't make it clear that we need to change our composer.json file.
`
	"require": {
		"laravel/framework": "5.0.*",
`

What should it be change to?
`
5.1.*???
or 5.*???
`

**Comment by GrahamCampbell** [comment]
`5.1.*`. Sorry if that was unclear.

> I started my project in Laravel 5.

NB, you started with 5.0 rather than 5. That distinction should make it clearer that your upgrading to 5.1. :)
