### ISSUE TITLE
Test isolation for Eloquent morph

### ISSUE THREAD

**Issue by vlakoff** [laravel/framework#10860]
When I run: `phpunit --filter DatabaseEloquentMo`, tests pass.

But when I run: `phpunit --filter DatabaseEloquentMorph` (same tests as above, except for `DatabaseEloquentModelTest`), I get this:

    There was 1 error:

    1) DatabaseEloquentMorphTest::testCreateFunctionOnNamespacedMorph
    Argument 2 passed to Illuminate\Database\Eloquent\Relations\MorphOneOrMany::__construct()
    must be an instance of Illuminate\Database\Eloquent\Model, instance of
    Mockery_2__Foo_Bar_EloquentModelNamespacedStub given, called in
    C:\laravel\tests\Database\DatabaseEloquentMorphTest.php on line 229 and defined

    C:\laravel\src\Illuminate\Database\Eloquent\Relations\MorphOneOrMany.php:34
    C:\laravel\tests\Database\DatabaseEloquentMorphTest.php:229
    C:\laravel\tests\Database\DatabaseEloquentMorphTest.php:173

    FAILURES!
    Tests: 23, Assertions: 15, Errors: 1.

So I guess `DatabaseEloquentMorphTest` is relying on some set up made in `DatabaseEloquentModelTest`, which isn't ideal. I couldn't figure it out yet. Anyone?

**Comment by jairovsky** [comment]
Hey, I found the dependency:

`DatabaseEloquentMorphTest` is depending on `EloquentModelNamespacedStub` ([see the exact line here](https://github.com/laravel/framework/blob/9f4dca8d8c3830b694bcb6e89f6907cf2797f5c3/tests/Database/DatabaseEloquentMorphTest.php#L224)).

`EloquentModelNamespacedStub` is required only on [line 909 of DatabaseEloquent**Model**Test.php](https://github.com/laravel/framework/blob/9f4dca8d8c3830b694bcb6e89f6907cf2797f5c3/tests/Database/DatabaseEloquentModelTest.php#L909), which makes `DatabaseEloquentMorphTest` fail miserably.

To solve the problem we just need to require `EloquentModelNamespacedStub` before the class definition:
```php
// file DatabaseEloquentMorphTest.php
require_once __DIR__.'/stubs/EloquentModelNamespacedStub.php';

class DatabaseEloquentMorphTest extends PHPUnit_Framework_TestCase
{
// ... all fine
```

**Comment by crynobone** [comment]
It's better to use `autoload-dev` if we want to split the stubs files.

**Comment by vlakoff** [comment]
Apparently, it is the only stub file.

(there are also "SuperProvider" and "SuperSuperProvider" stubs, but they are in facts leftovers which have to be removed, maybe a PR to come for this)

**Comment by vlakoff** [comment]
Just for reference: #419 and #9891
