### ISSUE TITLE
Where method not worked for [Eloquent Object]

### ISSUE THREAD

**Issue by lvht** [laravel/framework#10862]
Hello, we have encountered a strange problem. The code is
```php
$user = new App\User;
$user->where('name', 'lvht');
$user->get();
```
and the actual SQL is `select * from users`!!!

In my opinion, the expected SQL should be `select * from users where name = 'lvht'`.

Is there any thing be wrong?

---
With investigating the Eloquent source, I found the reason is this magic method of Eloquent Model
```php
    public function __call($method, $parameters)
    {
        if (in_array($method, ['increment', 'decrement'])) {
            return call_user_func_array([$this, $method], $parameters);
        }

        $query = $this->newQuery();

        return call_user_func_array([$query, $method], $parameters);
    }
```
Any call to the the missed method, like `where`, of Eloquent model obj, we have a new $query instance, which reset all the previous constraints.

Would it be reasonable to let the `$query` variable to be an attribute of Eloquent model instance? Just like
```php
    public function __call($method, $parameters)
    {
        // ...
        if (!$this->query) {
            $this->query = $this->newQuery();
        }

        return call_user_func_array([$this->query, $method], $parameters);
    }
```

**Comment by crynobone** [comment]
```
$user = App\User::newQuery();
$user->where('name', 'lvht');
$user->get();
```
