### ISSUE TITLE
MySQL JSON Grammars

### ISSUE THREAD

**Issue by petecoop** [laravel/framework#10867]
MySQL 5.7 is now generally available which adds a [JSON Data Type](https://dev.mysql.com/doc/refman/5.7/en/json.html) natively to MySQL. The current MySQL Grammers treat json as text, could this be updated?

**Comment by salarmehr** [comment]
+1

**Comment by GrahamCampbell** [comment]
The decision was taken not to do this, sorry.

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/pull/10899#issuecomment-156144045

**Comment by GrahamCampbell** [comment]
> The current MySQL Grammers treat json as text, could this be updated?

Oh right. Yes, then it can. Infact, it has. :)
