### ISSUE TITLE
php artisan route:list ERROR

### ISSUE THREAD

**Issue by minkbear** [laravel/framework#10868]
I have app/Http/navigation.php and in that file I call Auth::user()->can('Foo') which my User model using EntrustUserTrait.
When I call php artisan route:list on command, It shows error below. How can I solved this problem.

Thanks

PHP Fatal error:  Call to a member function can() on null in C:\foo_project\app\Http\navigation.
php on line ..

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Call to a member function can() on null

**Comment by GrahamCampbell** [comment]
Not a bug. Looks like your code in navigation.php is not inside a closure.

**Comment by minkbear** [comment]
But In navigation.php it is something like
Below is not a closure??? Please advice.

```php
Menu::make('MyNavBar', function($menu){

  if (Auth::user()->can('mng_foo')) {
      $menu->add('Home');
  }

});
```

**Comment by brunogaspar** [comment]
@minkbear Since you're running through the CLI, and on the CLI you're not logged in, the `Auth::user()` is returning `null` or `false`, since it's not returning the user object calling `->can()` will throw an exception, it's expected.

You need to kinda rework that piece of code, and check if the user is logged in before proceeding i guess, but i don't use the Laravel Auth so i can be wrong on the response.

**Comment by minkbear** [comment]
@brunogaspar  Thank you much for your initially idea.
I got the solution by checking that application is running in CLI mode or not.

**Comment by crynobone** [comment]
> I got the solution by checking that application is running in CLI mode or not.

WHY?

```php
$user = Auth::user();

if (! is_null($user) && $user->can('mng_foo')) {
      $menu->add('Home');
  }
```

**Comment by arcanedev-maroc** [comment]
OR:

```php
Menu::make('MyNavBar', function($menu) {
    if (Auth::check()) {
        if (Auth::user()->can('mng_foo')) {
            $menu->add('Home');
        }
    }
});
```

**Comment by ghprod** [comment]
@crynobone  Thats clean :+1:
