### ISSUE TITLE
Adding filters to blade?

### ISSUE THREAD

**Issue by davidsoderberg** [laravel/framework#10876]
Hi, I would like if blade had filters like twig it would make it much more readable.

**Comment by jairovsky** [comment]
I think it's possible to use [Directives](http://laravel.com/docs/5.1/blade#extending-blade) to achieve pretty much anything Twig Filters can do, with good readability.

**Comment by davidsoderberg** [comment]
But I can not nest Directives :(

**Comment by jairovsky** [comment]
Actually you can, with a bit of manipulation.

See this example project I made: https://github.com/jairovsky/laravel-nested-directive-example, files `welcome.blade.php` and `AppServiceProvider.php`

**Comment by davidsoderberg** [comment]
Ok thanks :)
