### ISSUE TITLE
seeJsonHasKey in CrawlerTrait

### ISSUE THREAD

**Issue by tpavlek** [laravel/framework#10872]
It would be useful for testing JSON to be able to assert that the JSON response has a particular set of properties without necessarily knowing the values of those properties.

For example:

```php
$this->post(
    'json_endpoint',
    $body
)->seeJsonHasKey([ 'access_token', 'expires_in' ])
```

**Comment by jadjoubran** [comment]
Why not implement it yourself?
I've implemented a bunch of them, useful for testing APIs:

https://github.com/jadjoubran/laravel5-angular-material-starter/blob/master/tests/TestCase.php#L52

* seeJsonKey
* seeJsonArray
* seeJsonObject
* seeApiSuccess
* seeValidationError

**Comment by countless-integers** [comment]
https://github.com/laracasts/Integrated/issues/101

**Comment by GrahamCampbell** [comment]
We're open to PRs, but don't process proposal issues.
