### ISSUE TITLE
remember cookie is always set to be forgotten on auth logout

### ISSUE THREAD

**Issue by ctadlock** [laravel/framework#10896]
My app doesnt use auth remember tokens or cookies. My app is an API that uses JSON tokens for auth. Everything functionality works fine... However when `Auth::logout()` is called the `Guard` class is setting the `remember` cookie to be forgotten. As I was developing an API client this seemed very strange to me. This cookie should only be set to be forgotten if it was set in the request.

Example of the API logout (which blacklists the token); you can see the `Set-Cookie` in the HTTP response.
![image](https://cloud.githubusercontent.com/assets/1539397/11112086/6306b714-88c4-11e5-858f-709eafe8c059.png)

I dont feel comfortable submitting a pull request for this as I wouldnt want to cause any unforeseen issues. My suggestion is that the call to queue the cookie on line 576 of `laravel/framework/src/Illuminate/Auth/Guard.php` should be wrapped with a check for the `remember` cookie on the request.

![image](https://cloud.githubusercontent.com/assets/1539397/11112154/401a9986-88c5-11e5-8fa5-69700bfc054d.png)

**Comment by ctadlock** [comment]
As a workaround you can remove `AddQueuedCookiesToResponse` from the global middleware and add it to the specific route middleware. I still think this is a bug as it shouldnt try to forget a cookie that never existed.

**Comment by GrahamCampbell** [comment]
I think this is the intended behaviour.

**Comment by GrahamCampbell** [comment]
> I still think this is a bug as it shouldnt try to forget a cookie that never existed.

Oh, yeh.

**Comment by GrahamCampbell** [comment]
That part's a bug. Sorry. Didn't read this properly. :)

**Comment by GrahamCampbell** [comment]
Looks like this was fixed. Thanks for the report.
