### ISSUE TITLE
migrate:status cannot accept --path or --database

### ISSUE THREAD

**Issue by mreschke** [laravel/framework#10914]
The `migrate` command can accept a `--path` option, but the `migrate:status` command cannot.  For those of use who maintain migrations in alternate locations, the `migrate:status` command does not work.  Would need to accept `--database` option as well.

**Comment by mreschke** [comment]
Issued a pr https://github.com/laravel/framework/pull/10915

**Comment by GrahamCampbell** [comment]
Thanks. :)
