### ISSUE TITLE
[Request] Support for selectRaw() with prepared statement in Eloquent/Query Builder

### ISSUE THREAD

**Issue by raczkiewicz-jacek** [laravel/framework#10926]
Similar to whereRaw()/orderByRaw() I'd welcome an option to set the value for SELECT manually with prepared statement.
Right now this is only supported for orderByRaw()/whereRaw() but not for selectRaw().

The use case for this is that the field name is sometimes a dynamic variable that needs to be escaped properly. For example In my use-case I can do this (data is a json field in Postgresql):
whereRaw("\"data\"->?->>'name' ILIKE ?",[$country,$phrase])
orderByRaw("\"data\"->?->>'name' ASC",[$country])

But for selectRaw() need to use workaround:
selectRaw("id, \"data\"->".$this->connection->getPdo()->quote($country)."->>'name' AS name")

**Comment by GrahamCampbell** [comment]
We're open to PRs, but don't process proposal issues.
