### ISSUE TITLE
Proposal: fire an event in guard::setUser

### ISSUE THREAD

**Issue by KnutHelland** [laravel/framework#10929]
I don't know if this is a good ida, but I think it would be a good idea to fire an event like `auth.authenticated` or something in `Guard::setUser`.

`Guard` already fires the events `auth.login`, `auth.logout` and `auth.attempt`.

I would like an `auth.authenticated` triggered when `Guard::setUser` is called, and my use case is:

I use Sentry for capturing warnings and errors, and I want to provide user context with the errors. To set the user context as early as possible after the user has been identified is important. Another solution could be to do this in a middleware, but I would like to set it as early in the request lifecycle as possible, which would be right after `setUser` is called.

**Comment by GrahamCampbell** [comment]
We're open to PRs, but don't process proposal issues.
