### ISSUE TITLE
Documentation on Middleware options missing

### ISSUE THREAD

**Issue by igorsantos07** [laravel/framework#10945]
Please,clarify in the [API doc](http://laravel.com/api/5.1/Illuminate/Routing/Controller.html#method_middleware) about what kind of `$options` are available, and also when Middlewares are mentioned in the [Authentication doc page](http://laravel.com/docs/5.1/authentication#protecting-routes), as this is very very common for auth procedures - not all routes for a controller are protected, for instance.

It's easy to misunderstand these `$options` as [Middleware parameters](http://laravel.com/docs/5.1/middleware#middleware-parameters) for new users (btw, how do we pass parameters through `Controller::middleware()`? I found no mention as well).

Last but not least, shouldn't be a mention on how to use [Middlewares inside Controllers](http://laravel.com/docs/5.1/controllers#controller-middleware) in the [Middleware](http://laravel.com/docs/5.1/middleware) page as well?

**Comment by GrahamCampbell** [comment]
We're open to PRs to the docs.
