### ISSUE TITLE
[5.1] FileStore cache driver expiration bug.

### ISSUE THREAD

**Issue by olsgreen** [laravel/framework#10955]
The FileStore cache driver only interprets the first 10 chars as the expiration time while reading the payload from file ([L64](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Cache/FileStore.php#L64)), where as when generating expiration timestamps no limit is placed. ([L210](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Cache/FileStore.php#L210))

This bug shows its self when trying to `Cache:increment()` or `Cache:decrement()` without first adding a key to cache. After the second increment the counter will return to zero as the expiration time that the driver tries to set is over 10 chars long resulting a corrupt payload. The issue can be reproduced like this using the default file storage setup:

    Cache::increment('test', 1); // 1
    Cache::increment('test', 1); // 2
    Cache::increment('test', 1); // 1
    Cache::increment('test', 1); // 2
    Cache::increment('test', 1); // 1
    /// etc

**Comment by GrahamCampbell** [comment]
Thanks for reporting.
