### ISSUE TITLE
wantsJson doesn't understand RESTful requests

### ISSUE THREAD

**Issue by aleemb** [laravel/framework#10969]
Via http://jsonapi.org/format/

> JSON API requires use of the JSON API media type (application/vnd.api+json) for exchanging data.

So it would be very welcome if `wantsJson` returned true for `application/vnd.foo.v1+json` instead of just `application/json`.

The [dingo/api](https://github.com/dingo/api) would also benefit from this (@jasonlewis).

**Comment by GrahamCampbell** [comment]
Not a bug,

**Comment by GrahamCampbell** [comment]
Use the accepts method we have.

**Comment by GrahamCampbell** [comment]
That way you can reliably check if the client understands the content type.

**Comment by aleemb** [comment]
@GrahamCampbell Why not use WantsJson? TO fixed it in any case https://github.com/laravel/framework/pull/10970

**Comment by crynobone** [comment]
Should already be available in `v5.1.25` based on @0fcceed

**Comment by GrahamCampbell** [comment]
And that. ;P

**Comment by GrahamCampbell** [comment]
I'm still against that change though, because wantsJson is incorrect if the client asked for `application/foo+json` and the server returns `application/json`.

**Comment by GrahamCampbell** [comment]
That's why you should always use the accepts method to actually be sure.
