### ISSUE TITLE
Laravel/Framework Updated to 5.1.24 but Some Files didn't changed.

### ISSUE THREAD

**Issue by justmyfreak** [laravel/framework#10968]
Currently I have issue running IronMQ on Laravel 5.1 and opened issue #10828. The issue has been fixed trough pull request #10848. So I updated my `laravel/framework` to `v5.1.24`. But files merged with pull request #10848 didn't changed on my vendor. 

I've removed all vendor, then clear composer cache before running composer install again. 

I also got Class 'IronMQ\IronMQ' not found error. I'm using `"iron-io/iron_mq": "4.*"` on my composer.json.

**Comment by GrahamCampbell** [comment]
In the meanwhile v2 will still work. Seems v4 isn't even namespaced anymore. I've got no idea what the ironmq devs are doing...

**Comment by justmyfreak** [comment]
Too bad.
I got endpoint error when using v2 of IronMQ.

**Comment by GrahamCampbell** [comment]
You need to switch to the old API. There must be something in the settings to do that.

**Comment by justmyfreak** [comment]
Thanks, I'll look into it

**Comment by carvefx** [comment]
Hi, I also ran into the same issue as @justmyfreak 
After doing some digging it seems like the changes from this commit: https://github.com/laravel/framework/commit/ad8ce4ca211f9f55ae006648c00281faf4c92e31

do not exist on the tagged v5.1.24 release
https://github.com/laravel/framework/blob/v5.1.24/src/Illuminate/Queue/Jobs/IronJob.php#L86
 for some reason, which leads to the vendor/* files not being updated on composer update 

Bad merge? Am I missing something?

**Comment by GrahamCampbell** [comment]
It's in the process of getting reverted.

**Comment by carvefx** [comment]
so is v5.1.25 going to include the fix?

**Comment by GrahamCampbell** [comment]
No.

**Comment by GrahamCampbell** [comment]
Taylor will explain in more detail soon. :)

**Comment by carvefx** [comment]
any updates on this @GrahamCampbell ?

**Comment by oscarbatlle** [comment]
Any updates on this @GrahamCampbell ?

**Comment by GrahamCampbell** [comment]
Yes. We reverted the changes. Only is supported. Also note that all ironmq support was removed from L5.2. It's been moved to the community to maintain. Feel free to go to that laravel collective repo and ask them to support this.
