### ISSUE TITLE
[5.1+] Flashed session data does not persist across redirects when using integrated testing methods (such as $this->visit)

### ISSUE THREAD

**Issue by squigg** [laravel/framework#10976]
**Tests:**
https://github.com/squigg/laravel-5-session-flash/blob/master/tests/ExampleTest.php
**Controller:**
https://github.com/squigg/laravel-5-session-flash/blob/master/app/Http/Controllers/BasicController.php
**Routes:**
https://github.com/squigg/laravel-5-session-flash/blob/master/app/Http/routes.php
** View:**
https://github.com/squigg/laravel-5-session-flash/blob/master/resources/views/output.blade.php

Tested on latest 5.1 and also on dev-master.

**Expected behaviour:**
Test should mimic browser behaviour - flashed session data should be retained for a single redirect and available in the view.

**Observed behaviour:**
The flashed session data is not persisted across redirects when using the Integrated testing features such as `$this->visit` within a `TestCase`. The above test `testRedirectWithFlashedSessionData` fails, as the requested session key does not exist.

I have narrowed this down to when the [followRedirects](https://github.com/laravel/framework/blob/125758c5997331a724f424a2b67c2fdd53ca46cb/src/Illuminate/Foundation/Testing/InteractsWithPages.php#L106) method (that is used by `visit`) calls `makeRequest` without passing any additional cookie/session information. I assume the session is then rebuilt from scratch during this request (meaning that data that was stored using 'put' is available), but any flashed session data seems to be lost.

A quick hacky workaround that will get the test to pass is to save the session data prior to this call to `makeRequest`, and then pass it back in afterwards using `withSession`, but this would mean flashed session data would persist for multiple redirects, which may not be intended behaviour.
```
while ($this->response->isRedirect()) {
            $session = session()->all();
            $this->makeRequest('GET', $this->response->getTargetUrl())->withSession($session);
        }
```
I'm not 100% sure how the session data flashing actually works in the framework, so any guidance on whether this is actually a bug, and where might be the best place to fix it would be helpful.

**Comment by GrahamCampbell** [comment]
Intended. You need to reflash at each redirect.

**Comment by squigg** [comment]
Flashed data should be available for the next HTTP request - i.e. following a single redirect. At the moment it doesn't persist at all - not even for a single redirect. This is not the same as the behaviour when visiting the exact same route using a browser.

I would expect testing using something like `visit` to directly mimic the behaviour you would see in the browser. Using a browser to visit http://localhost:8888/routeWithSessionFlash correctly shows the flashed session data within the view that is output.

Not having this same behaviour when using programmatic testing means that the page output could be completely different between using a browser and using the integrated testing if anything is dependent on flashed session data - surely this is not desirable?

**Comment by squigg** [comment]
@GrahamCampbell I still think this is a bug - the flashed session data does not seem to be staying even for a **single** redirect. My example code above with the failing test just does a simple flash and return redirect(), This works perfectly fine outside of the integrated testing framework, therefore I don't think the answer is to reflash.

**Comment by squigg** [comment]
Ignore me - the issue is with me using the assertion for seeInSession, which at the time the response is already sent is (I suppose correctly) returning null for the flashed value.
