### ISSUE TITLE
Racksapce internal url (SNET)

### ISSUE THREAD

**Issue by BadChoice** [laravel/framework#10972]
Add the option to use the internal network on rackspace (SNET) it really improves the velocity of connections when server is in the same datacenter (and they do not bill you extra bandwith)

It is only adding `snet` prefix on the api URL.
It should be good to add the option on the config 

```
'internal'	=> true/false,
```
on `config/filesystem.php`

**Comment by edcs** [comment]
The Laravel filesystem uses `league/flysystem`; in turn, Flysystem uses PHP Opencloud by Rackspace. This option would need to be implemented by Flysystem before Laravel could make use of it.

**Comment by GrahamCampbell** [comment]
> This option would need to be implemented by Flysystem before Laravel could make use of it.

No it wouldn't? This is surely something we just pass through to to the underlying rackspace object we're using?

**Comment by GrahamCampbell** [comment]
We don't process proposal issues though, so closing this. We're open to PRs if you want to add this though.
