### ISSUE TITLE
Support for Virtual Columns in Mysql 5.7 

### ISSUE THREAD

**Issue by igormatkovic** [laravel/framework#10973]
Are there any plans to support the new Virtual Columns in Mysql 5.7?

https://dev.mysql.com/doc/refman/5.7/en/create-table.html

MariaDB also has their own implementation of the feature:
https://mariadb.com/kb/en/mariadb/virtual-computed-columns/

**Comment by imalitavakoli** [comment]
Not what you're looking for exactly... But for anyone looking for a similar behaviour to implement it on their Models, you can define [Accessors & Mutators](http://laravel.com/docs/5.0/eloquent#accessors-and-mutators) that work like a virtual custom column.

Also to add [array attributes](http://laravel.com/docs/5.0/eloquent#converting-to-arrays-or-json) that do not have a corresponding column in database, again accessors can help:

```php
public function getIsAdminAttribute()
{
    return $this->attributes['admin'] == 'yes';
}
```

Once you have created the accessor, just add the value to the appends property on the model:
```php
protected $appends = ['is_admin'];
```

Once the attribute has been added to the appends list, it will be included in both the model's array and JSON forms.
```php
// includes 'is_admin' attribute in results too as if you had a 'is_admin' column in your database.
$usersArr = User::all()->toArray();
```

**Comment by igormatkovic** [comment]
Why is this closed? 

Accessors and Mutators might look similar but they are two completely different things.

Generated columns are a part of the 5.7 now, it exists in Maria DB and will eventually be implemented in the Percona version of mysql.

Having Generated columns in the actual DB that allow you to assign indexes to them and order by them is a huge thing.

Here is a good example of these types of columns:
https://www.percona.com/blog/2015/04/29/generated-virtual-columns-in-mysql-5-7-labs/
