### ISSUE TITLE
Policy 'before' method not being called.

### ISSUE THREAD

**Issue by Jamesking56** [laravel/framework#10983]
Hello!

I have been using Laravel's new Policy classes to help with ACLs in my application.

For some reason however, when following this portion of the documentation on http://laravel.com/docs/5.1/authorization#writing-policies:

> Sometimes, you may wish to grant all abilities to a specific user on a policy. For this situation, define a before method on the policy. This method will be run before all other authorization checks on the policy:
> 
> ````php
> public function before($user, $ability)
{
    if ($user->isSuperAdmin()) {
        return true;
    }
}
> ````

My `before` method never gets called. Here is my code:

````php
class AdminUserPolicy
{
    use HandlesAuthorization;

    /**
     * @var Guard
     */
    protected $auth;

    /**
     * Create a new policy instance.
     *
     * @param Guard $auth
     */
    public function __construct(Guard $auth)
    {
        $this->auth = $auth;
    }

    public function before($user, $ability)
    {
        dd('before');
        if (Auth::user()->isSuperAdmin()) {
            return true;
        }
    }

    public function create()
    {
        return true;
    }

    public function edit(User $user)
    {
        return $this->auth->user()->isAdmin() && !$user->isAdmin();
    }

    public function delete(User $user)
    {
        if ($this->auth->user()->id == $user->id) {
            return false;
        }

        return $this->auth->user()->isAdmin() && !$user->isAdmin();
    }
}
````

the `dd('before');` is never called although I have verified that all of the other methods get called.

My app is running Laravel 5.1.24 (LTS).

**Comment by rkgrep** [comment]
How do you use this policy in your code?

**Comment by Jamesking56** [comment]
`policy($user)->edit($user)`

**Comment by rkgrep** [comment]
This just calls `edit` directly, because you resolve the policy for manual usage (same as `app(AdminUserPolicy::class)`. While `before` is used when you call `allows` / `denies` / `check` methods on gate instance.

You should use at least 2 arguments in your policy methods - 1st is the authenticated user (instead of `$this->auth->user()` in your example, 2nd - is the instance
````php
public function edit(User $authenticated, User $user)
{
    return $authenticated->isAdmin() && !$user->isAdmin();
}
````
Then use `Gate` facade or any other way to validate action
````php
if (Gate::allows('edit', $user)) {
 //do action
}
````
````

**Comment by Jamesking56** [comment]
Yeah its working now thanks.
