### ISSUE TITLE
Validator ignores white spaces at the beginning of the string when validating unique

### ISSUE THREAD

**Issue by iaroel** [laravel/framework#10994]
Hi,

When validating unique values validator ignores white spaces at the beginning of the string.
Here is my code:

````
$rules=['name'=>'required|unique:table,name'];
````
When I enter some_value   with spaces at the and it trims and works perfectly, however when there is/are spaces at the beginning it passes the validation.

**Comment by jairovsky** [comment]
I think something is going on *before* your input reaches Validator.

Method [`Illuminate\Validation\Validator#validateUnique`](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Validation/Validator.php#L1034) doesn't do any trimming/cleanup/transformation on the input. If your input is `"    my_string       "` it will search in the database exactly like that, without trimming.

What Laravel version are you using?

**Comment by iaroel** [comment]
Hi Jairo,

Thanks for your reply.
I'm using Laravel 5.1 and really nothing is going on before the validation.

Please see the code that I have in controller and the html.
````
 public function store(Request $request)
    {
        $rules=['name'=>'required|table,name]

<input type="text" name="name" id="name" value="{{old('name')!='' ? old('name') : ''}}" class="form-control">
````

**Comment by jairovsky** [comment]
Thanks for posting your code. I see you're using Angular.

I think what's causing the problem here is that Angular by default trims `<input type="text">`. [See here the documentation and how to disable this behaviour](https://docs.angularjs.org/api/ng/input/input%5Btext%5D).

**Comment by iaroel** [comment]
Sorry for confusing but it's not Angular.
The curly braces are from a blade template.

**Comment by jairovsky** [comment]
Oh sorry. What a mistake.

Can you post the steps to reproduce the error or a repo with an example
project reproducing the error?

**Comment by iaroel** [comment]
Let's say you have a table named any_table which have id and name columns.
Assume there is only one record like:

id=1
name="some text"

And you want to prevent user to enter same name more than once.

At the html side you have very basic form with a text field named "name"

And finally at the controller you're validating the name field as unique like:

````
$rules=['name'=>'required|unique:table_name,name'];
		$validator=Validator::make($request->input(), $rules);
		if ($validator->fails()) {
			print_r($validator->errors());
		}else{
			exit('passes');
		}
````

The interesting thing is when you enter something like "some text" or "some text    "   validator catches however if you enter something like " some text" or "     some text" validation won't catches.

**Comment by iaroel** [comment]
Here is the walkaround but I think it needs to be fixed.
Especially if you are generating url slugs according to entered value.
 
Just before the validation enter:
````
if($request->input('name')!=''){
            $request->replace(array('name' => trim($request->input('name'))));
        }
````

**Comment by bespired** [comment]
So it's not ignoring them... it's taking them into account. 
What you'd want if you are validating a password that starts with some spaces....

**Comment by bespired** [comment]
Bit old...
Beginning 5.4 Laravel has \App\Http\Middleware\TrimStrings::class.
Input is space trimmed except for the input where you don't want that, passwords for example.
An array with exceptions can be defined in \App\Http\Middleware\TrimStrings.php
