### ISSUE TITLE
missingMethod parameters not an array

### ISSUE THREAD

**Issue by arjasco** [laravel/framework#10998]
When defining missingMethod in my controllers $parameters seems to be a string and not an array. Is there any reason for this to be documented as / defaulted to an array in the abstract controller? 

```php
    /**
     * Handle calls to missing methods on the controller.
     *
     * @param  array   $parameters
     * @return mixed
     *
     * @throws \Symfony\Component\HttpKernel\Exception\NotFoundHttpException
     */
    public function missingMethod($parameters = [])
```

**Comment by jairovsky** [comment]
Interesting... `missingMethod` appears on Laravel 4.2 docs (http://laravel.com/docs/4.2/controllers#handling-missing-methods) but not on 5.0+ docs. Also, `missingMethod` works as expected in Laravel 4.2: `$parameters` is actually an array and not a string. (I encourage you to try it and see for yourself).

Are there plans to remove this funcionality or it's just being refactored/documented?

**Comment by arjasco** [comment]
Didn't notice the documentation! I should have mentioned I'm using 5.1. I have quite a few 4.2 projects so never have had a problem. 

I did noticed a revert of a commit from Graham that does show routing methods being deprecated, I believe one or more of them methods is called when missingMethod is called after closer inspection. So this could be the case.
