### ISSUE TITLE
firstOrNew() doesn't work with withTrashed()?

### ISSUE THREAD

**Issue by imalitavakoli** [laravel/framework#10996]
This code:
```php
$cat = Category::withTrashed()->firstOrNew(['id' => '1']);
```

gives the following error:
```
BadMethodCallException in Builder.php line 1999:
Call to undefined method Illuminate\Database\Query\Builder::firstOrNew()
```

**Comment by PhiloNL** [comment]
You need to call `withTrashed` after `firstOrNew`:

```
Category::firstOrNew(['id' => '1'])->withTrashed();
```

**Comment by rkgrep** [comment]
@PhiloNL how do you think, this supposed to work if `firstOrNew` already returns an instance, while `withTrashed` a query builder.

**Comment by PhiloNL** [comment]
@rkgrep `firstOrNew` is a static method only available on the model. `withTrashed` returns an instance of the query builder, therefore the `firstOrNew` method is undefined.

**Comment by rkgrep** [comment]
Intended usage.
````php
$category = Category::firstOrNew(['id' => '1']); // Either new category or found one.
$category->title = 'new';
$category->save(); // id => 1, title => new
````
While in your your proposal calling `firstOrNew` makes no sense.
````php
$category = Category::firstOrNew(['id' => '1'])->withTrashed(); // Returns Builder instance
$category->title = 'new'; //FAIL
````

Manual selection should be used here.
````php
$attributes = ['id' => 1];
if (! $category = Category::withTrashed()->where($attributes)->first()) {
    $category = new Category($attributes);
}
$category->title = 'new';
$category->save();
````

**Comment by imalitavakoli** [comment]
@rkgrep you're correct. However, putting an if statment and doing something like this would be tedious:
```php
$cat = Category::withTrashed()->find(1);
if (!$cat) $cat = new Category;
```

If there was a convenient short-cut for this that would be so much better... As this is something that might be needed a lot...

**Comment by arjasco** [comment]
I see nothing wrong there, that is how I have approached it

If you really wanted to stay on one line you could just do

```php
$cat = Category::withTrashed()->find(1) ?: new Category;
```

**Comment by imalitavakoli** [comment]
Of course you can do that my friend. It's not the mater of writing a code in one line!
We're talking about a functionality here.

`firstOrNew()` semantically means that it should find a model based on an attribute or instantiate the model if it didn't exist. And `withTrashed()` means including trashed records too. Now if they both work together that would be better, isn't it? Just like how `withTrashed()` works with `find()` or `first()`.

**Comment by rkgrep** [comment]
I think, `firstOrNew` should just ignore any scopes, I'll make a PR.

**Comment by GrahamCampbell** [comment]
thx
