### ISSUE TITLE
Laravel pagination fails in building the correct query

### ISSUE THREAD

**Issue by salarmehr** [laravel/framework#10995]
When I try to run this query:

    SELECT CONCAT(`user`.`firstName`,' ',`user`.`lastName`) AS `fullName`" 
    FROM `user`
    WHERE `fullName` LIKE '%a%'

 
using the `User` model, Laravel send the following query by-itself before running my query: 

    SELECT COUNT(*) AS AGGREGATE
    FROM `user`
    WHERE `fullName` LIKE '%a%'

which leds to `SQLSTATE[42S22]: Column not found: 1054 Unknown column 'userFullName' in 'where clause` exception. What is wrong with Laravel? How to run the above query regarding this issue?

**Comment by rkgrep** [comment]
This is because you use pagination (this query resolves total count). However any aliased fields are ignored because they cause errors in different engines.
See #10856
