### ISSUE TITLE
[Query Builder] where('my_col', '!=', null) rewrite doesn't work

### ISSUE THREAD

**Issue by alexander-malahov** [laravel/framework#11007]
This query `MyModel::where('my_col', '=', null);`
will be rewritten as `select * from "my_model" where "my_col" is null` 
thanks to the [check in `where` method](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Database/Query/Builder.php#L493).

However `MyModel::where('my_col', '!=', null);` will [throw new InvalidArgumentException('Illegal operator and value combination.')](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Database/Query/Builder.php#L466)

**Comment by alexander-malahov** [comment]
If I got this right, the fix would be to replace inside [`invalidOperatorAndValue`](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Database/Query/Builder.php#L531) method current return with:
`return $isOperator && is_null($value) && !in_array($operator, ['=', '!=', '<>']);`

**Comment by jairovsky** [comment]
Is there any reason in particular for you to be using `where` instead of  `MyModel::whereNotNull('my_col')`?

**Comment by davesouthey** [comment]
It would also require a change to the ["check in where method"](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Database/Query/Builder.php#L493) to make it check the operator is "=" and when the operator is "!=" or "<>" add the whereNotNull instead of whereNull.

**Comment by alexander-malahov** [comment]
@jairovsky nope, I just expected it to work because of symmetry with `'=', null`. It would be more consistent. 
And from reading the code inside [`if (is_null($value))`](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Database/Query/Builder.php#L493), I'm pretty sure `'!=', null` was intended to work. The only reason it doesn't - `invalidOperatorAndValue` check isn't passed earlier in the method.

@davesouthey it's already handled by the 3rd argument of `whereNull`.  [`whereNotNull`](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Database/Query/Builder.php#L883) is just `return $this->whereNull($column, $boolean, true);`

**Comment by alexander-malahov** [comment]
@GrahamCampbell some rationale would be nice. Looks like a bug to me.
