### ISSUE TITLE
[Proposal] new "laravel lts" installor command for 5.1

### ISSUE THREAD

**Issue by HiroKws** [laravel/framework#11002]
`laravel new` will install the latest version of Laravel into local environment every time.

Soon Laravel 5.2 will been released. After released, this command make 5.2 project.

Laravel 5.1 is LTS, so we need a easy way to install this version.

I suggested `laravel new --lts` in larachat. Taylor replied `laravel lts` command is acceptable.

**Comment by GrahamCampbell** [comment]
Great. We're open to PRs then. :)

**Comment by GrahamCampbell** [comment]
NB, we don't usually process proposal issues. Talking on slack is sufficient.
