### ISSUE TITLE
Illuminate/queue missing dependency (composer)

### ISSUE THREAD

**Issue by SamMousa** [laravel/framework#11014]
Illuminate/queue requires an implementation of the `Illuminate\Contracts\Bus\Dispatcher` class, I think it should either require or suggest the illuminate/bus package.

**Comment by GrahamCampbell** [comment]
No need. We require the contract. It's up to the user to make sure an implementation exists.

**Comment by GrahamCampbell** [comment]
We should really be using virtual packages on composer I guess, but that's not caught on. Maybe for Laravel 6. ;)
