### ISSUE TITLE
ORM has tight dependency on LengthAwarePaginator

### ISSUE THREAD

**Issue by Daveawb** [laravel/framework#11017]
At the moment the query builder instantiates a fresh LengthAwarePaginator each time the pagination method is called. As times are moving on a lot of developers are starting to use Laravel more and more for API driven applications. I for one am writing a JSON API v1.0 API in Laravel 5.1 at the moment and have had to write a rather ugly adapter for the LengthAwarePaginator due to the inability to swap out the paginator used by the ORM.

Currently the method looks like this.

```php
/**
 * Paginate the given query into a simple paginator.
 *
 * @param  int  $perPage
 * @param  array  $columns
 * @param  string  $pageName
 * @param  int|null  $page
 * @return \Illuminate\Contracts\Pagination\LengthAwarePaginator
 */
public function paginate($perPage = 15, $columns = ['*'], $pageName = 'page', $page = null)
{
    $page = $page ?: Paginator::resolveCurrentPage($pageName);

    $total = $this->getCountForPagination($columns);

    $results = $this->forPage($page, $perPage)->get($columns);

    return new LengthAwarePaginator($results, $total, $perPage, $page, [
        'path' => Paginator::resolveCurrentPath(),
        'pageName' => $pageName,
    ]);
}
```

If the `LengthAwarePaginator` was built through the IoC this problem would not exist.

Is this a problem anyone else has faced? I would like to submit a PR to allow this functionality but would like some feedback before I make any headway on it.

**Comment by tomschlick** [comment]
I don't see a problem with creating a new Illuminate contact to make this work via the IoC... but there looks like it would be a decent amount of work to make it happen.

**Comment by GrahamCampbell** [comment]
You'd better talk to Taylor about this on one slack. Maybe this is something we can get done for L5.3.

**Comment by Daveawb** [comment]
I spoke to Taylor about this and we came up with an alternative as he
wasn't keen on having something resolving from the IoC with arguments but
recognised that we could do something. It'll probably take on the form of a
static resolving method to build the LAP instance. I'm going to go ahead
and put this together.
