### ISSUE TITLE
[Auth] Policy always overrides abilitiy defined with closure or class reference

### ISSUE THREAD

**Issue by cedricziel** [laravel/framework#11011]
I just thought it was a bug and while running the tests for my  patch I discovered this is indeed intended behaviour. I think this is a bad decision. 

The container will resolve a policy formulated for that particular Domain object, where I want to make a decision based on a *named* ability. - That way, I explicitly stated, which ability to use - not something else. I use the identifier of the ability, so why should the Gate intercept and call something else?

Example:

*AuthServiceProvider.php*
```php
class AuthServiceProvider extends ServiceProvider
{
    /**
     * The policy mappings for the application.
     *
     * @var array
     */
    protected $policies = [
        'App\Model'     => 'App\Policies\ModelPolicy',
        Activity::class => ActivityPolicy::class,
    ];

    public function boot(GateContract $gate)
    {
        $this->registerPolicies($gate);

        $gate->define('create-blogpost-for-activity', function ($user, $activity) {

            return $user->id === $activity->initiator_id;
        });

        $gate->define('index-blogpost-for-activity', 'App\Policies\Activity\BlogPolicy@canIndexBlogPostsForActivity'); // BlogPolicy is just a class name to burry my access voter in
    }
}
```

With the given example, *every* request to a named ability such as ``@can('index-blogpost-for-activity', $instanceOfActivity)`` will internally be routed to the policy as it has a matching policy-method though I defined a very specific method to be called for that ability.

https://github.com/laravel/framework/blob/5.1/src/Illuminate/Auth/Access/Gate.php#L317

I'd be happy pull-requesting if I was sure about if there's a chance for the patch to be accepted. I'll work around in the meantime by not using policies at all since I think it's a bug :)

**EDIT:** ``Gate::allows('index-blogpost-for-activity', [Auth::user(), $activity])`` matches the defined method on the class instead of the policy which is inconsistent and confusing.

**Comment by rkgrep** [comment]
I'm not sure if this is a bug.

If a policy is defined, it should handle all actions on its instance. Otherwise you might get unexpected results.

In your case `canIndexBlogPostsForActivity` should be placed in `ActivityPolicy` because result depends on activity, but not on blog instance.
