### ISSUE TITLE
Extended PHP dotenv functionalities with env_or_fail

### ISSUE THREAD

**Issue by mathiasgrimm** [laravel/framework#11016]
I would like to discuss about the possibility of having an env_or_fail function that would throw an Exception when the variable is not defined or empty

As a project grows, maintaining the variables become challenging.

## Option 1:
<pre>
function env_or_fail($variableName)
{
    if (!$value = env($variableName)) {
        throw new \Exception("Variable '$value' not defined in the .env");
    }

    return $value;
}
</pre>

## Option 2:
alternatively there could be one file (config) that would be read by the PHP dotenv package (https://github.com/vlucas/phpdotenv) that would allow an extended usage of the package.

<pre>
$dotenv->required(['DB_HOST', 'DB_NAME', 'DB_USER', 'DB_PASS']);
$dotenv->required('DATABASE_DSN')->notEmpty();
$dotenv->required('SESSION_STORE')->allowedValues(['Filesystem', 'Memcached']);
</pre>

## Option 3:
This would be the proposed config file using the default Laravel Validation (http://laravel.com/docs/5.1/validation)
<pre>
    // config/env.php
    return [
        'SESSION_STORE' => 'required|sometimes|in:FileSystem,Memcached',
        'APP_ENV '              => 'required|in:production,local',
       // ...
    ]
</pre>

**Comment by mathiasgrimm** [comment]
They don't need to be mutually exclusive and in fairness I think the option 1 and 3 can work well together.

**Comment by mathiasgrimm** [comment]
Quick dirty implementation

https://gist.github.com/mathiasgrimm/da38b385bef1be6a6a4e

**Comment by GrahamCampbell** [comment]
Probablt just define these in your app, or make a packae.

**Comment by mathiasgrimm** [comment]
alright
