### ISSUE TITLE
[5.1] [5.2] SQlite primary key issue

### ISSUE THREAD

**Issue by FranPregernik** [laravel/framework#11028]
Hi,

we are using Laravel 5.1 (latest) and are trying to enforce naming conventions when creating PK and we want to specify names of the PK.
```php
    public function up()
    {
        Schema::create('xyz', function(Blueprint $table){
            $table->increments('id');
            $table->primary('id', 'xyz_pk');
        });
    }
```

This works fine in some databases (oracle via laravel-oci8) but when we try to run it against sqlite we get an error. Similar issue was posted here #7570 so sqlserver has the same issue.

This generates a sqlite create table (paraphrazing):
```sql
create table xyz("id" integer primary key autoincrements, primary key "xyz_pk" (pk));
```
which produces the error:
```
 [PDOException]                                                                      
  SQLSTATE[HY000]: General error: 1 table "xyz" has more than one primary key  
```

I feel that the increments (and similar) method should call internaly the primary method and not use the modifyIncrements (like in Illuminate\Database\Schema\Grammars\SQLiteGrammar::modifyIncrements) later on to tack on the primary key. Maybe even make modifyIncrements check if there was a primary call and then not tack on the primary key in front of autoincrements.

**Comment by activatedgeek** [comment]
:+1:

**Comment by CurosMJ** [comment]
https://www.sqlite.org/lang_createtable.html

Does SQLite support naming primary keys ?

**Comment by CurosMJ** [comment]
```sql 
create table "xyz" ("id" integer not null primary key autoincrement, primary key ("id"));
```
This is the SQL being generated as a result of the schema definition you provided.

**Comment by CurosMJ** [comment]
Declaring named primary keys in SQLite should look like this : 

```sql
CREATE TABLE "xyz" ("id" integer not null, constraint "my_key" primary key ("id"));
```
This works, AND, behind the scenes, the "id" IS autoincrementing. (I manually inserted a row (once with "id" set to null, and once I didn't provide the value for "id"), and the "id" got converted into a number).

Maybe this explains the above behavior : http://www.sqlite.org/faq.html#q1

**Comment by GrahamCampbell** [comment]
Yeh, I don't think this is actually a laravel bug.

**Comment by CurosMJ** [comment]
do we need to change grammar? i think it is a bug, because using increments() and primary () together does not work.

maybe we should state this clearly in the docs.

**Comment by CurosMJ** [comment]
ping @GrahamCampbell
