### ISSUE TITLE
Routes use wrong controller when correct namespace is set, but controller name is same as elsewhere

### ISSUE THREAD

**Issue by afraca** [laravel/framework#11035]
Suppose we have 

`App\Http\Controllers\FooController`

and 

`Somewhere\Else\FooController`

Then this route will trigger an exception saying App\Http\Controllers\FooController@quiz is not defined:

`Route::get('bar', ['namespace' => 'Somewhere\Else', 'uses' => 'FooController@quiz'])` 

I verified this was not because of overwriting routes elsewhere. However, in another routefile this was included:

`Route::get('__', ['namespace' => 'App\Http\Controllers', 'uses' => 'FooController@__'])` 

Additionally, and this is quite interesting, when we wrap the first route definition in a route group with the namespace set it works fine....

**Comment by afraca** [comment]
I apologize for the title, that is VERY confusing..... Feel free to edit.

**Comment by GrahamCampbell** [comment]
This the expected behaviour. Your routes file is wrapped in a routing group that adds a base namespace.

**Comment by GrahamCampbell** [comment]
Feel free to ask on the forums if you need more help.

**Comment by afraca** [comment]
I'm sorry for the confusion. If you mean how the default 
`App\Providers\RouteServiceProvider` works, then this is NOT the case for me. 

This is in a completely different package ServiceProvider, in the 
`boot` method I simply do

`require __DIR__ . routing/routes.php`

**Comment by GrahamCampbell** [comment]
Not really sure what you mean still?

**Comment by afraca** [comment]
I have two controllers with an identical classname, but they live in a completely different namespace. In my package I also have a routes.php file somewhere in my package and also simply included in the serviceprovider. When I want a very simple route to a method in the __controller from my package__, I somehow end up in the other controller! 

This is not expected when the route is defined like this:
`Route::get('foobar', ['namespace' => 'My\Package', 'uses' => 'FooController@packageThingy'])`

**Comment by arjasco** [comment]
In your service provider wrap your route file in a route group defining the namespace.

Example: 
```php
$router->group(['namespace' => 'Namespace\Goes\Here'], function() {
    require __DIR__ . '/path/to/routes.php';
});
```

**Comment by afraca** [comment]
That's curing a symptom, but there is clearly SOMETHING going wrong in the routing. I'm sorry for being pushy, but when I define a route with a namespace set for that route, and that route definition is NOT wrapped in some other group (as is the case with my service provider), it should use THAT namespace, not something else. That is a BUG. 

If namespaces set on an individual route like
`Route::get('bar', ['namespace' => 'Somewhere\Else', 'uses' => 'FooController@quiz'])`

SHOULD not work (even when they're not in a route group), then that option should simply NOT exists, and. Anyway, I stand by my case that this is a bug, and have not seen evidence of it otherwise.

**Comment by rkgrep** [comment]
You don't need `namespace` option for that. Just define controller class with leading `\`
````
Route::get('bar', ['uses' => '\Somewhere\Else\FooController@quiz']);
````

**Comment by afraca** [comment]
Yup, don't need it. still a bug. Waiting for counter-arguments.

**Comment by arjasco** [comment]
After inspection of Illuminate/Routing/Router.php, it looks like namespace isn't an argument that is used on adding routes. You will have to go with route grouping.

rkgrep shows another valid way which is visible here - https://github.com/laravel/framework/blob/5.1/src/Illuminate/Routing/Router.php#L597

**Comment by afraca** [comment]
Hmm, interesting, thanks! No idea why it was included in the routes file I was porting over from a 4.2 installation..... My apologies, though it would've been nice if not everyone was saying "do it different!"

**Comment by ikramullah01** [comment]
**hello brother** ### dddd
