### ISSUE TITLE
LogicException: The command defined in [class] cannot have an empty name.

### ISSUE THREAD

**Issue by brazorf** [laravel/framework#11043]
I have an exception on an Artisan command, in the very first line of constructor 

```php
public function __construct(RouteInstaller $routes) {
    parent::__construct();
    $this->routes = $routes;
}
```

that is where i'm calling the super constructor.

The exception occurs while trying a build with php 5.4 (see here https://travis-ci.org/foothing/laravel-wrappr/jobs/92312916) while there are no problems with php 5.5 or hhvm. 

The command itself is very trivial and the full code is here: https://github.com/foothing/laravel-wrappr/blob/develop/src/Foothing/Wrappr/Commands/Install.php

**Comment by vioclick** [comment]
Hi, could you resolve it?

**Comment by walterred** [comment]
Hi, could you resolve it?

**Comment by zlodes** [comment]
Hi, could you resolve it?
