### ISSUE TITLE
unsuitable treatment PostgreSQL quote

### ISSUE THREAD

**Issue by iugo** [laravel/framework#11048]
> MySQL uses ' or " to quote values (i.e. WHERE name = "John"). This is not the ANSI standard for databases. PostgreSQL uses only single quotes for this (i.e. WHERE name = 'John'). Double quotes are used to quote system identifiers; field names, table names, etc. (i.e. WHERE "last name" = 'Smith').

The following two statements will result in an error. Because the SQL statement Lavavel unsuitable treatment.
```
DB::select('SELECT ? FROM users WHERE id = ?', ["name", 1]);
DB::select('SELECT ?::character(10) FROM users WHERE id = ?', ["name", 1]);
```

It is error:
`SELECT 'name' FROM users WHERE id = '1';`
It is correct:
`SELECT "name" FROM users WHERE id = '1';`

**Comment by rkgrep** [comment]
You must not put identifiers (table names, columns etc) in bindings. Only values should be passed this way.
