### ISSUE TITLE
[Filesystem] Prepend and Append - their purpose and performance

### ISSUE THREAD

**Issue by shehi** [laravel/framework#11041]
https://github.com/laravel/framework/blob/5.1/src/Illuminate/Filesystem/FilesystemAdapter.php#L122

I believe the purpose of these methods should be as documented: prepending and appending to files. However, when inspected, we can see that in addition to the ```$data``` provided, ```PHP_EOL``` is added to the content as well. To me at least, this was a bad surprise.

Additionally, from performance standpoint, these methods get *all* content from the original file and only _then_ append/prepend to it. If the original file is very large, you get the idea. My question is: why streams weren't used instead? Streams could do these tasks much faster and cheaper. Additionally, for scenarios like prepend, we could devise multiple flows depending on the filesize: if file is small, do it the old way; if it's large, we could create a bit longer method which takes more steps, but almost no memory to accomplish.

So, shall I work on this and send PR?

**Comment by arjasco** [comment]
Utilising streams would be excellent.

I just did a couple of tests of append and prepend with a 1GB file using the `File` and `Storage` facades

These are both using the local file system, no cloud.

`File::append` took >50ms 
(FILE_APPEND moves the pointer to the end of the file so quick enough anyway. https://github.com/laravel/framework/blob/5.1/src/Illuminate/Filesystem/Filesystem.php#L109)
`File::prepend` took >4.5s

`Storage::append` and `Storage::prepend` both got to about 20 seconds and ran out of memory..

**Comment by GrahamCampbell** [comment]
We don't process proposal issues. Feel free to send a PR though. Probably target 5.2 or 5.3.

**Comment by ejunker** [comment]
@shehi have you implemented `append()` with streams?

I think the issue may be that not all Flysystem adapters could support this. There is some discussion of this at: https://github.com/thephpleague/flysystem/issues/90

I think implementing this in Flysystem would be better than doing it in Laravel.

**Comment by shehi** [comment]
Been busy lately. Though during my preliminary research, I realized it will be a bit of a custom work, especially when it comes to ```prepend()```. That's why I have been so late with implementation.
