### ISSUE TITLE
whereRaw for join clause

### ISSUE THREAD

**Issue by Elyahou** [laravel/framework#11053]
As The title says, this function is currently missing.

**Comment by acasar** [comment]
This can usually be solved by ``DB::raw``. What is your use case?

**Comment by Elyahou** [comment]
I need to add an on clause to my join that use the postgres unaccent
extension so I need WhereRaw since where cant use unaccent function

2015-11-22 17:34 GMT+02:00 Anže Časar <notifications@github.com>:

**Comment by acasar** [comment]
Not familiar with unaccent functions, but still something like that should work:

->on('col1', '=', DB::raw('my_function(col2)'));

**Comment by Elyahou** [comment]
Thank you I will give it a try

2015-11-22 20:58 GMT+02:00 Anže Časar <notifications@github.com>:

**Comment by simplenotezy** [comment]
It can be achieved like this:

    ->on('col1', '=', DB::raw('my_function(col2)'));

But not like this:

    ->on('col1', '=', 'something')->where('col1', '=', DB::raw('my_function(col2)'));

Don't know why
