### ISSUE TITLE
Route group's prefix should not be added to a resource's name if the group's name is specified

### ISSUE THREAD

**Issue by ssang** [laravel/framework#11054]
This is a group that I currently have

```php
Route::group(
    [
        'prefix' => 'admin',
        'middleware' => 'auth',
        'as' => 'admin::'
    ],

...

```

When I make a resource within this group, for example, a users resource, I expect the route name for it to be `admin::users.method` but instead I get `admin::admin.users.method`

Even if I specify the resource name, it gives me `admin::user.admin.user.method`

**Comment by GrahamCampbell** [comment]
This behaviour is correct. Please checkout loads of similar issues.
