### ISSUE TITLE
"queue:retry all" documented, but no 5.1.* tag exists with the supporting code

### ISSUE THREAD

**Issue by landons** [laravel/framework#11050]
I just found out about the "all" argument for the "queue:retry" command from reading the documentation for 5.1:
http://laravel.com/docs/5.1/queues#retrying-failed-jobs

I'm on 5.1.20, which doesn't have that ability when I try it from artisan.  I then checked each of the later 5.1.* tags to see if any of them do, which they don't either.

I don't know that this is a code issue per-se, but it's at least confusing when the documentation doesn't line up with any released version.

**Comment by GrahamCampbell** [comment]
Yes, it's an upcoming feature, that'll be available in 5.1.25.
