### ISSUE TITLE
Known limitation, bug in Service Container implmentation, or something else?

### ISSUE THREAD

**Issue by mmic-bjohnson** [laravel/framework#11057]
I'm a bit surprised to find that this combination of import statements (`use ...`), class declarations, and dependency-injections causes a fatal error when working with https://cartalyst.com/manual/themes/3.0 .

Granted, Cartalyst Themes is a third-party package, and the fatal error happens with a package-specific Artisan command (`php artisan theme:compile`), but I've run this by the developers at Cartalyst and they contend that this problem is not specific to its Themes package, but rather, it is either a bug in core PHP, a bug Symfony, a bug in Laravel's Service Container implementation, or a "known limitation" in one or more of the aforementioned.

Ultimately, I am curious if the Laravel developers have encountered this before and have a rational explanation.

Also, the documentation at http://laravel.com/docs/5.1/container makes no mention of the fact that the order in which dependencies are injected matters. Maybe this fact is intended to be self-evident, and if so, it is not, and therefore should be stated clearly in the documentation.

The simplest means by which to reproduce this (credit to @suwardany ) appears to be something like this. Particularly important are the comments in the last file, because they explain the problem, specifically, and in a way that it should be trivial to reproduce in "stock Laravel".

`/foo/src/Classes/Committee.php`
```php
<?php namespace Bar\Foo\Classes;

use Bar\Foo\Models\Organization;

class Committee {

    public function __construct(Organization $organization) {
        $this->organization = $organization;
    }

}
```

`/foo/src/Classes/Organization.php`
```php
<?php namespace Bar\Foo\Classes;

class Organization {

}
```

`/foo/src/Models/Organization.php`
```php
<?php namespace Bar\Foo\Models;

class Organization {

}
```

`/foo/src/Controllers/Frontend/Organization.php`
```php
<?php namespace Bar\Foo\Controllers\Frontend;

use Platform\Foundation\Controllers\Controller;

class FooController extends Controller {
    public function index()
    {
        // Let's instantiate the Organization class;
        // this class has no injections or anything.
        
        app()->make('Bar\Foo\Classes\Organization');

        // `Bar\Foo\Classes\Organization` is now loaded into the declared classes.
        // This is demonstrated by uncommenting the following line.

        // dd(get_declared_classes());

        // Now, let's attempt to instantiate the Committee class, which has
        // the `Organization` model (Bar\Foo\Models\Organization) as an injected dependency.
        // The instantiated class is attempting to import the Organization model now.
        // Unfortunately, since an `Organization` class is already imported above
        // (not the same class, and not the same namespace; they share only the last segment),
        // the 'Symfony\Component\Debug\Exception\FatalErrorException' is thrown.
        
        app()->make('Bar\Foo\Classes\Committee');

        // Now, attempt to disable the first app()->make call and uncomment the following line.

        // dd(get_declared_classes());

        // You will see the imported classes at the end of the dump.

        // Furthermore, the order in which these classes are instantiated
        // does play a role as well. Attempt to switch them by putting the
        // Committee first, then the Organization; no collision occurs.
    }
}
```

With these resources in-place, one need only execute `php artisan theme:compile` to receive a fatal exception:

```
 [Symfony\Component\Debug\Exception\FatalErrorException]
  Cannot use Bar\Foo\Models\Organization as Organization because the name is already in use
```

If I am barking up the wrong tree here, I am happy to lodge this Issue with the appropriate entity; I just need to know who/what that might be.

Thank you in advance for looking at this!

**Comment by crynobone** [comment]
```php

namespace Bar\Foo\Models {
    class Organization {

    }
}

namespace Bar\Foo\Classes {

    use Bar\Foo\Models\Organization;

    class Committee {

    }

    class Organization {

    }

} 
```

Surely you can see the problem here, you're trying to use `Organization` when the same class is already exist in the same namespace.

**Comment by mmic-bjohnson** [comment]
@crynobone Firstly, thanks a lot jumping on this so quickly. I really appreciate your assistance and insight.

Well, when you put it like that, yes, I can see the problem; it is glaringly obvious when the code is rearranged to consider execution scope.

Ultimately, I suppose it wasn't clear to me that this is the order in which, and the scope within which, these classes would be resolved, ultimately.

Just so I understand the problem, fundamentally, is this the call that produces the snippet you posted, ultimately?

```php
    public function __construct(Organization $organization) {
        $this->organization = $organization;
    }
```

**Comment by crynobone** [comment]
Yes, the issue is when `Committee` wants to use `Organization`, PHP doesn't know which `Organization` class should be injected, does `Committee` actually wants the `Organization` model, or the `Organization` class under the same namespace (which require no import/`use ...`). 

So the exception is thrown, and this can easily be solved by adding `use Bar\Foo\Models\Organization as OrganizationModel;` and 

```php
public function __construct(OrganizationModel $organization) {
     $this->organization = $organization;
}
```

**Comment by mmic-bjohnson** [comment]
Again, thanks for the immediate reply!

Yes, that is how I resolved the issue, to the letter.

I suppose that I need to be more careful to use aliases when assigning the same name to a class and a final namespace segment when the potential for them to conflict occurs.

Just out of curiosity, do you find yourself having to do this (aliasing to avoid these types of conflicts) often? Or am I employing an undesirable pattern here?

Thanks again for your invaluable assistance. I'll close the issue, now that you've made clear why it's not a bug.
