### ISSUE TITLE
[5.1] No connector for [] - when using QUEUE_DRIVER=null

### ISSUE THREAD

**Issue by jadjoubran** [laravel/framework#11051]
The `QUEUE_DRIVER=null` option throws the following error:

No connector for []

You can simulate the error by simply changing your queue driver to null, and dispatching a job

**Comment by GrahamCampbell** [comment]
I've seen this before too.

**Comment by arjasco** [comment]
https://github.com/laravel/framework/blob/5.1/src/Illuminate/Queue/QueueManager.php#L150
Looks like correct behaviour, just incorrect response. 
Check for null and return an InvalidArgumentException that says that a driver must be defined maybe??

```php
if (is_null($driver)) {
    throw new InvalidArgumentException("A queue driver has not been defined");
}
```

Haven't had a closer look but does DotEnv parse nulls as a strings?

**Comment by arjasco** [comment]
1. If null as a string is passed to `env` it will be ignored and null will be returned 
https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/helpers.php#L315

2. A null driver needs to be defined in your queue config file like so.
```php
'null' => [
    'driver' => 'null'
]
```

I could submit a PR tomorrow to fix this??

**Comment by jadjoubran** [comment]
Thanks @arjasco 
 I can confirm that, as a temporary workaround, I can define a null driver by using any word other than `null`:

        'drop' => [
            'driver' => 'null'
        ],

`QUEUE_DRIVER=drop`

**Comment by GrahamCampbell** [comment]
> as a temporary workaround

Doesn't need to be temporary. There's no requirement to match the driver name with the connection name. Choosing a different connection name is just fine.

**Comment by jasonmccreary** [comment]
Just ran into this issue, while I understand you can configure your own *null* driver, if Laravel has one, I should be able to use it.

Setting the driver to *null* (either `null` or `'null'`) as instructed by the documentation results in this error. I'd consider that a bug. This should be reopened and fixed or the documentation should be changed.

**Comment by GrahamCampbell** [comment]
It's not really a bug. It is a limitation though. A fix for using the "null" driver is to set the default to `"null"` in the config file.

**Comment by jasonmccreary** [comment]
As noted, I tried that. Laravel 5.2. Same error. It's a bug.

**Comment by GrahamCampbell** [comment]
You need to clear your config cache.

**Comment by GrahamCampbell** [comment]
Did you not read my other comment?

**Comment by GrahamCampbell** [comment]
Replace `'default' => env('QUEUE_DRIVER', 'sync'),` with `'default' => env('QUEUE_DRIVER', 'null'),`.

**Comment by GrahamCampbell** [comment]
Or, just rename the null connection to something else. I agree that calling it null was a bad default though.

**Comment by GrahamCampbell** [comment]
There's no reason why connection names need to match driver names.

**Comment by jasonmccreary** [comment]
Tried both `php artisan config:clear ` and `php artisan cache:clear`, still throws the exception using the code you provided running Laravel 5.2. One of us is missing something.

Not a big deal. I have my workaround.

**Comment by jadjoubran** [comment]
@jasonmccreary I have found the below to be a good workaround

```
 'drop' => [
        'driver' => 'null'
    ],
```

Since `drop` is more accurate & descriptive compared to `null` in this scenario and you'll escape the null & "null" issues in the config

**Comment by jasonmccreary** [comment]
I understand the workarounds. My crusade began because I followed the comments/docs and set the driver to `null`. Upon doing so I received an exception.

Either Laravel should use `drop` instead of `null` or resolve the issue with using `null` directly. Both would require a code change to behave as intended, hence why I feel this is a *bug*. This is, of course, assuming others are experience this same misbehavior.

**Comment by GrahamCampbell** [comment]
I agree it needs changing. Perhapse send a PR and see what Taylor thinks?

**Comment by alphabravo8** [comment]
if you're going with the solutions above don't forget to `php artisan config:clear`

**Comment by mukeshrana90** [comment]
h

**Comment by mukeshrana90** [comment]
@ #1. > [``](url)
