### ISSUE TITLE
Eloquent / SQL Server Binary Columns

### ISSUE THREAD

**Issue by StevenBock** [laravel/framework#11059]
Hello,

First of all, this is one of the first reports I've ever made so forgive me if it lacks details.  With that said:

I'm using Eloquent in a system that uses SQL Server as the primary database.  Many of the tables in this database have a primary key with a type of BINARY(16).  I'm unable to use Eloquent relationships on these tables as the SQL that is generated by Eloquent does not return anything.

As an example, if I have a row in a table that has a primary key with a value of 0x0000BEE7FF64DF41AE39DAD82BCA3111, Eloquent generates a query that looks something like this:

```SELECT * FROM table WHERE binary_primary_key = '0000BEE7FF64DF41AE39DAD82BCA3111'.  ```

This does not return anything, as it is treating the primary key as a string instead of a binary key.  These queries would return data, however Eloquent does not seem to generate them out of the box:

```SELECT * FROM table WHERE binary_primary_key = 0x0000BEE7FF64DF41AE39DAD82BCA3111```

```SELECT * FROM table WHERE binary_primary_key = CAST(binary(16), binary_primary_key, '0000BEE7FF64DF41AE39DAD82BCA3111')```

Any ideas?  Hopefully this is just a user error on my part.. anyways, please let me know if you need more details.  Thanks

**Comment by GrahamCampbell** [comment]
Thanks for sending an issue. We're open to PRs.
