### ISSUE TITLE
phpunit: Unable to find JSON fragment

### ISSUE THREAD

**Issue by Fuzzyma** [laravel/framework#11068]
When I test my api I get the following error:

```
Unable to find JSON fragment ["company":{"name":"Johnston Group","token":"JVW","updated_at":"2015-11-24 16:47:04","created_at":"2015-11-24 16:47:04","id":1}] within [{"company":{"created_at":"2015-11-24 16:47:04","id":"1","name":"Johnston Group","token":"JVW","updated_at":"2015-11-24 16:47:04"},"company_id":"1","created_at":"2015-11-24 16:47:04","firstname":"","id":1,"lastname":"","pin":"1234","token":"JVWBkC","updated_at":"2015-11-24 16:47:04"}].
```

Here again the both json outputs aligned:
```javascript
 ["company":{"name":"Johnston Group","token":"JVW","updated_at":"2015-11-24 16:47:04","created_at":"2015-11-24 16:47:04","id":1}]
[{"company":{"created_at":"2015-11-24 16:47:04","id":"1","name":"Johnston Group","token":"JVW","updated_at":"2015-11-24 16:47:04"},"company_id":"1","created_at":"2015-11-24 16:47:04","firstname":"","id":1,"lastname":"","pin":"1234","token":"JVWBkC","updated_at":"2015-11-24 16:47:04"}]
```

As you can see the fragment is indeed present (wrong order, though). So why this error appears?

My seeJSON command tests on this:
```
            ->seeJson([
               'company' => $company,
               'firstname' => '',
               'lastname' => '',
               'pin' => 1234,
               'role' => 1
            ]);
```

**Comment by jairovsky** [comment]
`seeJson` make strict comparisons, so `'pin' => 1234` (interpreted as integer) will fail because the JSON returned by your API is actually `"pin":"1234"` (interpreted as string).

Also, the JSON returned by your API lacks a `role` attribute.

**Comment by Fuzzyma** [comment]
I agree that i missed the role. However the error remains when I comment out pin and role.
Furtermore the error is pointing to the company-object which is obviously not found and not the pin or role.

So there actually is an issue here (or is there some other magic involved?)

**Comment by Fuzzyma** [comment]
I dont know why this was closed prematurely since this is a real problem

**Comment by wojtekk** [comment]
I have the same issue like @jairovsky.

Do you need more details?

**Comment by diegosurita** [comment]
I'm having the same problem as described by @Fuzzyma

**Comment by akoskm** [comment]
@jairovsky @GrahamCampbell @Fuzzyma this problem still exists. The assertion fails with

```
["data":{"attributes":{"username":"hello123"},"id":1,"type":"users"}]

within

[{"data":{"attributes":{"created_at":"2016-05-22 13:10:19","created_by":"sql",
location_id":1,"username":"hello123"},"id":1,"type":"users"}}].
```

my assertion looks like:

```
             ->assertJsonFragment([
                 'data' => [
                    'id' => 1,
                    'type' => 'users',
                    'attributes' => [
                        'username' => 'hello123'
                    ]
                 ]
             ]);
```

I see that the difference in `[{"data"` vs `["data"`, but I'm not sure how to format the parameter of `assertJsonFragment` so that it later becomes `["data"`.

**Comment by ZiperRom1** [comment]
Same problem here.

```
Tests\API\FlowTest::testCreation
Unable to find JSON fragment ["response":{"description":"Aut adipisci aut quidem iste. Quaerat est placeat iste officiis molestiae. Molestiae in eum aut et. Dolorem nam qui eos voluptates architecto ex.","label":"esse optio quo","user_id":2}] within [{"message":"Success","response":{"created_at":"2017-08-25 19:10:01","description":"Aut adipisci aut quidem iste. Quaerat est placeat iste officiis molestiae. Molestiae in eum aut et. Dolorem nam qui eos voluptates architecto ex.","id":3,"label":"esse optio quo","updated_at":"2017-08-25 19:10:01","user_id":2},"success":true}].
```

Because even with the good matching data, it seems than if more JSON fields are returned into a non root level JSON field, the method fails while it should not.

**Comment by ZiperRom1** [comment]
I "fixed" the issue by editing Lumen / Laravel `MakesHttpRequests.php` class.
I just added 4 lines of code in `SeeJsonContains` method.

Lines added:

```php
    if (is_array($value)) {
        $this->seeJsonContains($value, $negate);
        continue;
    }
```

New `SeeJsonContains` methods

```php
/**
     * Assert that the response contains the given JSON.
     *
     * @param  array  $data
     * @param  bool  $negate
     * @return $this
     */
    protected function seeJsonContains(array $data, $negate = false)
    {
        $method = $negate ? 'assertFalse' : 'assertTrue';

        $actual = json_decode($this->response->getContent(), true);

        if (is_null($actual) || $actual === false) {
            return PHPUnit::fail('Invalid JSON was returned from the route. Perhaps an exception was thrown?');
        }

        $actual = json_encode(array_sort_recursive(
            (array) $actual
        ));

        foreach (array_sort_recursive($data) as $key => $value) {
            $expected = $this->formatToExpectedJson($key, $value);

            if (is_array($value)) {
                $this->seeJsonContains($value, $negate);
                continue;
            }

            PHPUnit::{$method}(
                Str::contains($actual, $expected),
                ($negate ? 'Found unexpected' : 'Unable to find')." JSON fragment [{$expected}] within [{$actual}]."
            );
        }

        return $this;
    }
```

I don't know if I should make a merge request as it is a bit "hacky"...

**Comment by johnlui** [comment]
@ZiperRom1 Thank you for your code!

I think it's better to do it in `TestCase.php`.

**Comment by systemovich** [comment]
A workaround for the bug with `$response->assertJson($array)` is `$response->assertSee(json_encode($array))`.

**Comment by microdesign** [comment]
I just come to this problem,
is there still no working example to **seeJsonStructure** alternative in Laravel 5.8 ?

**Comment by mdiazr2000** [comment]
Hi I have this json structure
'data' : [ 
"salesOrder": [
      4690,
      1597,
    ],
"repairOrder": [
      0,
      50,
]
]
If I need to find  an specific value inside of subarrays I do this

$this->get('url...')
            ->assertJsonStructure([
                'data' => [
                    'salesOrder','repairOrder'
                ]
            ])
            ->assertJsonFragment([
                '0' => 1597])

and it will make ok assertions , if i not use any key text , if i put 0 in key value the string to compare in assertions only contain the value that is necesary to compare.
The string to compare wil be 1597] , 1597} 1597, and PHP unit could find that string in our Json

**Comment by mdiazr2000** [comment]
> I just come to this problem,
> is there still no working example to **seeJsonStructure** alternative in Laravel 5.8 ?

Hello microdesign
The method alternative to seeJsonStructure in laravel 5.8 is  assertJsonStructure

Example
In the next json file
{
 'data' : [
   total : {},
   salesOrder : {}
    ]
}

 ->assertJsonStructure([
                'total' => [
                    'total', 'salesOrder'
                ],
            ])

**Comment by kgkg** [comment]
+1 
This is still issue, comparing array containing other array is impossible right now without some workarounds. Is it going to fixed anytime in future?

**Comment by Fuzzyma** [comment]
Since this issue is already 4 years old, it seems like nobody cares about that even though it feels like this could be fixed fairly easily. @jairovsky @GrahamCampbell any news?

**Comment by kgkg** [comment]
Fuzzyma: maybe try to create new issue, I think they may ignore it since it's closed.
This is a serious issue, because right now there is no convenient method to check API response if it's not just flat array.

Btw I created workaround updated for Laravel 5.8, based on original @ZiperRom1 workaround. 
Feel free to use it in pull request if you want.

```
protected function seeJsonContains(array $data, $negate = false)
    {
        $method = $negate ? 'assertFalse' : 'assertTrue';

        $actual = json_decode($this->response->getContent(), true);

        if (is_null($actual) || $actual === false) {
            PHPUnit::fail('Invalid JSON was returned from the route. Perhaps an exception was thrown?');
        }

        $actual = json_encode(
          Arr::sortRecursive(
            (array)$actual
          )
        );

        foreach (Arr::sortRecursive($data) as $key => $value) {
            $expected = $this->formatToExpectedJson($key, $value);

            if (is_array($value)) {
                $this->seeJsonContains($value, $negate);
                continue;
            }

            PHPUnit::{$method}(
              Str::contains($actual, $expected),
              ($negate ? 'Found unexpected' : 'Unable to find') . " JSON fragment [{$expected}] within [{$actual}]."
            );
        }

        return $this;
    }
```

**Comment by Fuzzyma** [comment]
@kgkg would be cool if you could handle that new issue. I didnt use Laravel in a long time. I just keep geeting updates about this issue and its actually quite amusing and sad at the same time :D

**Comment by ZiperRom1** [comment]
Same, I don't use Lumen anymore but it is quite funny that such an important point that testing API response (main purpose of this framework) is still not resolved several years after the bug came out.

**Comment by systemovich** [comment]
I wonder how many of these types of closed-but-unresolved issues exist.

**Comment by microdesign** [comment]
The problem is solvable and that is why maybe there is not a fix.

I just rewrite my tests to check the response in the new way:

`->assertJsonStructure(['token']);`

**Comment by kgkg** [comment]
@microdesign maybe it's solvable in trivial api responses you presented.
But in anything more like real world example it's not.

**Comment by nicolas-costa** [comment]
2020 and this is still a thing.
