### ISSUE TITLE
Commenting on magic methods with @method

### ISSUE THREAD

**Issue by adhiravishankar** [laravel/framework#11061]
AWS PHP SDK  has all of its methods which do not exist in code but can be called via __call(), Laravel needs to do this with some of its methods to show that those methods actually do exist and are viable. 

One example is whereIn, which is possible through the Eloquent Builder class but is not an express method, but still can be called. There are many other examples. I am working on a pull request for many of them, but I feel that this is best done by the people who continuously work with all the segments of code, because you would know most if not all of the magic methods. 

This is the related issue in AWS that I have been referring: https://github.com/aws/aws-sdk-php/issues/754

**Comment by GrahamCampbell** [comment]
Sorry. This was proposed before, and was rejected.

**Comment by GrahamCampbell** [comment]
Too much of a pain to maintain.
