### ISSUE TITLE
mysql foreign key constrains violation

### ISSUE THREAD

**Issue by milon** [laravel/framework#11073]
I tried to do a foreign key with 2 table. table names are `hms_institute_ownership_translation` and `hms_institute_ownership`. my up method of migration class looks like this.
```
Schema::create('institute_ownership_translation', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('institute_ownership_id')->unsigned();
            $table->string('name');
            $table->string('locale');

            $table->unique(['institute_ownership_id', 'locale']);
            $table->foreign('institute_ownership_id')->on('id')->references('institute_ownership')->onDelete('cascade');
        });
```
the problem is when I tried to run migration it shows foreign key constrains violation. seems laravel tried to create a foreign key and tried to name its contrains as `hms_institute_ownership_hmsinstitute_ownership_translation_hms_institute_ownership_id`. Mysql supports 64 character long foreign key constrains. So, I thinks we should check whether it is tried to make a foreign key more than 64 character, if then we should trim it to 64 character.

**Comment by rkgrep** [comment]
Trimming could cause duplicate foreign key names.
On the other hand if we generate some random part, it will become impossible to drop foreigns in migrations.
So you should just pass name manually as second parameter.
`$table->foreign('institute_ownership_id', 'some_shorter_name')`

**Comment by milon** [comment]
Thanks @rkgrep

**Comment by pepijnolivier** [comment]
We should probably still detect when the foreign key lenght is larger than 64 chars, and if so, maybe use an md5 hash of the key.

**Comment by rkgrep** [comment]
@pepijnolivier that will be hard to control on rolling back. Hashed keys will also confuse if someone explores the database directly, as you cannot determine key purpose by hashed name.

Manual control is the best solution here IMO.
