### ISSUE TITLE
`url.intended` saves POST request url and thows 404 after login

### ISSUE THREAD

**Issue by hassansin** [laravel/framework#11072]
If a guest tries to POST to a authenticated page, `url.inteded` is saved to that POST url. After login when attempting to redirect, it makes a GET request to that POST-only url and throw a NotFoundHttpException. IMHO, if current request is GET then use [`$this->generator->full()`](https://github.com/laravel/framework/blob/076a054b6c78888acb3d0b93030402dbf736d824/src/Illuminate/Routing/Redirector.php#L83) and if non-GET then it should be `$session->previousUrl()`

**Comment by GrahamCampbell** [comment]
I guess we need to only flash it for a "safe" request. That's defined as `'GET'` or `'HEAD'`.
