### ISSUE TITLE
[Blade] Commenting out an extend will still echo the parent view

### ISSUE THREAD

**Issue by bastiaan89** [laravel/framework#11081]
When placing an `@extends` tag in comments (like `{{--@extends('default')--}}`), the `default` view will still be loaded. I don't think that is intended behavior. The result is an empty PHP comment, followed by the inclusion of the `default` view. This can also be tested by running `Blade::compileString("{{-- @extends('default')--}}")` in `artisan tinker`. A possible solution would be to completely ignore comments (as proposed earlier in #5441), or to add comments around the include line.

**Comment by GrahamCampbell** [comment]
Thanks, but this is actually a known bug, and we had to revert the fix because it broke loads of things.

**Comment by bastiaan89** [comment]
Cheers, then I'll just remember not to leave those in comments.
