### ISSUE TITLE
It's not possible to define an ability that accept more than one parameter

### ISSUE THREAD

**Issue by salarmehr** [laravel/framework#11082]
It seems currently the following ability definition is not possible.
~~~~~
$gate->define('ability', function ($user, $foo, $bar) {
            return $foo || $bar;
        });

~~~~
 The second parameter is not sent to ability closure `authenticate('abilitiy`,true,false);` . Is it intended behavior?

**Comment by GrahamCampbell** [comment]
Yes.

**Comment by GrahamCampbell** [comment]
Leaving this open as feature request though.

**Comment by salarmehr** [comment]
@GrahamCampbell  Yeah, I wonder why it does not send other parameters to closure. This constraint  is not reflected in the docs as well.

**Comment by GrahamCampbell** [comment]
We're open to PRs, but don't process proposal issues.

**Comment by salarmehr** [comment]
@GrahamCampbell Actually it's an api inconsistency rather that a proposal.
