### ISSUE TITLE
Strange behavior of isDirty()

### ISSUE THREAD

**Issue by dlnsk** [laravel/framework#11086]
I noticed a strange behavior of Eloquent Model's isDirty()
In first example Picture just extents Model.
In second example pictures() defined in Variation as:
```
	public function pictures() {
		return $this->belongsToMany('App\Picture');
	}
```
In third example variations() defined in Product as:
```
	public function variations() {
		return $this->hasMany('App\Variation');
	}
```
and only here it works as expected!

**EXAMPLES:**
```
Psy Shell v0.5.2 (PHP 5.5.30-1+deb.sury.org~precise+1 — cli) by Justin Hileman

>>> $pic = \App\Picture::firstOrNew(['hash'=>'ddd']);   // first example
=> App\Picture {#767}
>>> $pic->exists
=> false
>>> $pic->isDirty()
=> false                       // WHY?

>>> $v = \App\Variation::find(1);    // second example
=> App\Variation {#755
     id: "1",
     product_id: "1",
     sku: "",
     barcode: "6917308707361",
   }
>>> $pic2 = $v->pictures()->firstOrNew(['hash'=>'ddd']);
=> App\Picture {#784}
>>> $pic2->exists
=> false
>>> $pic2->isDirty()
=> false                       // WHY?

>>> $p = \App\Product::find(1);  // third example
=> App\Product {#758
     id: "1",
     company_id: "1",
     brand: "Zara",
   }
>>> $v2 = $p->variations()->firstOrNew(['barcode' => 'ddd']);
=> App\Variation {#788
     barcode: "ddd",
     product_id: "1",
   }
>>> $v2->exists
=> false
>>> $v2->isDirty()
=> true                       // THAT's RIGHT!
```

**Comment by codefocus** [comment]
All of the "incorrect" examples use `App\Picture` while the "correct" example uses `App\Variation`.

It looks like your `App\Picture` model has no attributes that could get dirty. If `hash` were an available attribute, it would be set, and the model instance would be dirty.

**Comment by dlnsk** [comment]
In all three examples was create new model. Why new (unsaved) model is not dirty?

**Comment by codefocus** [comment]
@dlnsk "dirty" indicates that one or more attributes' values have changed.

If no attributes' values have changed (or the model has no attributes), nothing is dirty.

**Comment by dlnsk** [comment]
@codefocus thanks! I will use `exists` in future.
