### ISSUE TITLE
SUGGESTION: Put models in a separate folder

### ISSUE THREAD

**Issue by anik786** [laravel/framework#11080]
I think its a good idea to put all new models created via the artisan console command `make:model` in a separate dedicated folder  called `app\models` instead of putting it all in `app`. 

This makes sense as we already put controllers, middlewares, migrations, providers, listeners, policies, seeders, commands etc in separate folders. Therefore it only makes sense to put models in a separate folder as well (especially considering models are much more common compared to other files such as policies)! 

Please +1 if you are ok with this or state why your not. I will try to make a branch soon (almost done, but don't want to waste time working on a feature no-one wants).

Also should the merge request be with "master" or with "5.2"?

**Comment by GrahamCampbell** [comment]
It's fine for you to do this in your own app. I do that. :)

**Comment by GrahamCampbell** [comment]
https://github.com/StyleCI/StyleCI/tree/master/app/Models

**Comment by anik786** [comment]
I'm aware but chouldnt it do this by default for new applications! It just makes sense, expecially for new users. 

As I said before, if we put middlewares, migrations, providers, listeners, policies, seeders, commands and more in separate folders by default during the make command; why not put one of the most common files in a Models directory by default. 

I understand I can do this for my app already, as Laravel allows many changes to directories, but this is more about  providing sensible defaults!!!
