### ISSUE TITLE
Giving scalar value to inject into the action from the routes

### ISSUE THREAD

**Issue by Rezouce** [laravel/framework#11083]
I may be wrong, but I think it's not possible to inject the value of a scalar parameter from a route to an action

We could have something like this:
``` php
public function doSomething($parameter) {}
```

And then inject the parameter(s) per route:
``` php
Route::get('foo', ['uses' => 'Controller@doSomething', 'parameter' => 'foo']);
Route::get('bar', ['uses' => 'Controller@doSomething', 'parameter' => 'bar']);
```

**Comment by GrahamCampbell** [comment]
Not possible, no..

**Comment by Rezouce** [comment]
For now I've done this:
``` php
public function foo()
{
    $this->doSomething('foo');
}

public function bar()
{
    $this->doSomething('bar');
}

public function doSomething($parameter) {}

Route::get('foo', ['uses' => 'Controller@foo']);
Route::get('bar', ['uses' => 'Controller@bar']);
```

But I think it's a lot of extra code which could be avoid.
Do you think this is a dumb idea or is it worth trying to implement it?

If it is worth it, is the syntax I used in my proposal the most relevant one?
