### ISSUE TITLE
Model relation with same name of local row problem

### ISSUE THREAD

**Issue by BrainClot** [laravel/framework#11090]
We had a weird problem in the project I am working on at the moment.
We have a model that has this field:
```php
protected $fillable = [
    'education_level'
];
```

There is a relation on this column:
```php
public function education_level()
{
    return $this->hasOne(Education::class, 'id', 'education_level_id');
}
```

Invoking this relation with load results in a server error 500 and out of memory running in the terminal with 2GB limit.

For example:
```php
$job = Job::find(1);
$job->load(['education_level']);
```

**Comment by dwightwatson** [comment]
Generally when this happens you'll need to give the relationship a different name to the table column name.

In this instance, you could also adopt the PSR style guide and use camelCase for method names, so `educationLevel()` instead, which would not conflict with the table column.

**Comment by GrahamCampbell** [comment]
Yes, we assume you're following at least PSR-1 in all our code.
