### ISSUE TITLE
Service Container: Forgetting an instance

### ISSUE THREAD

**Issue by IngwiePhoenix** [laravel/framework#11092]
I am running Laravel as a server process, so most of the application state is persisted across requests.

But I want to replace a specific instance over and over, for every time the server is hit. I tried to do so using this:

```php
<?php
// Within my main request routine
    if($app->bound(HproseHolder::class)) {
        $app->forgetInstance(HproseHolder::class);
    }
    $app->instance(HproseHolder::class, new HproseHolder($ctx["optional"]));
    assert(
        \Hprose::get("wpHash") == $ctx["optional"]["wpHash"],
        "WebPack hash does not match!"
    );
```

Unfortunately, as soon as the WebPack hash changes, the assertion is triggered. This is not supposed to happen, obviously.

What is the correct way of replacing an instance like this?

As a reference, the full code for this is here: https://github.com/DragonsInn/BIRD3/blob/master/app/App/Entry/PhpServer/Frontend.php#L99-L133

**Comment by GrahamCampbell** [comment]
Please ask questions on the forums and I'm sure someone can help you there. :)

**Comment by IngwiePhoenix** [comment]
I did ask on SO, but got no answer. So that is why I came here.
Oh well… gotta keep trying.

Thanks, anyway. :)
