### ISSUE TITLE
[5.1] Bugged behavior of json_encode when trying to encode Model with binary data as attributes

### ISSUE THREAD

**Issue by Nicarim** [laravel/framework#11100]
This caused me a headache with job queues. Basically, when you pass a user that contains binary data in database as attribute (like, new MySQL 5.6 Point() column, or binary image) to a json_encode, it fails without any constructive error. It can be easily replicated by using a job queue:
 - Create User table with column type "Point"
 - Create a job class.
 - Create a job object, and pass user to its contstructor.
 - Try to run queue.

In case of sync queue: It will throw ```Class not found``` message when *trying to add onto queue*, without even pointing what class is not being found.

In case of redis queue, error is as useless as before: 
```
[ErrorException]
 Undefined index: job
```
When trying to run artisan queue:listen.

Die and Dump of failing user:
```
User {#294
  #table: "users"
  #fillable: array:13 [
    0 => "username"
    1 => "email"
    2 => "password"
    3 => "birthdate"
    4 => "hair"
    5 => "eye"
    6 => "sex"
    7 => "height"
    8 => "fb_id"
    9 => "avatar"
    10 => "photo"
    11 => "status"
    12 => "statusDescription"
  ]
  #hidden: array:4 [
    0 => "password"
    1 => "remember_token"
    2 => "location"
    3 => "photo"
  ]
  #appends: array:2 [
    0 => "age"
    1 => "range"
  ]
  #connection: null
  #primaryKey: "id"
  #perPage: 15
  +incrementing: true
  +timestamps: true
  #attributes: array:22 [
    "id" => 22
    "username" => "username"
    "email" => "username@gmail.com"
    "password" => "$2y$10$j2gREyjhKQrviiHRt2dCx.zff0W96sVBgsv96P9Sb545irhQozh4q"
    "remember_token" => null
    "fb_id" => ""
    "photo" => "f2bf3271ae26fde7444366a3b6f29dae"
    "eye" => 0
    "hair" => 0
    "sex" => "male"
    "birthdate" => "2015-09-18"
    "height" => "220"
    "longitude" => 15.256949094515
    "latitude" => 52.755289869627
    "location" => b"\x00\x00\x00\x00\x01\x01\x00\x00\x00\x1F5\x1C\tú\x1CJ@\x13‡‰>&\x045@"
    "avatar_id" => 82
    "ip" => ""
    "updated_at" => "2015-11-27 19:53:23"
    "created_at" => "2015-11-18 10:20:12"
    "admin" => 0
    "status" => 0
    "statusDescription" => null
  ]
  #original: array:22 [
    "id" => 22
    "username" => "username"
    "email" => "username@gmail.com"
    "password" => "$2y$10$j2gREyjhKQrviiHRt2dCx.zff0W96sVBgsv96P9Sb545irhQozh4q"
    "remember_token" => null
    "fb_id" => ""
    "photo" => "f2bf3271ae26fde7444366a3b6f29dae"
    "eye" => 0
    "hair" => 0
    "sex" => "male"
    "birthdate" => "2015-09-18"
    "height" => "220"
    "longitude" => 15.256949094515
    "latitude" => 52.755289869627
    "location" => b"\x00\x00\x00\x00\x01\x01\x00\x00\x00\x1F5\x1C\tú\x1CJ@\x13‡‰>&\x045@"
    "avatar_id" => 82
    "ip" => ""
    "updated_at" => "2015-11-27 19:53:23"
    "created_at" => "2015-11-18 10:20:12"
    "admin" => 0
    "status" => 0
    "statusDescription" => null
  ]
  #relations: []
  #visible: []
  #guarded: array:1 [
    0 => "*"
  ]
  #dates: []
  #dateFormat: null
  #casts: []
  #touches: []
  #observables: []
  #with: []
  #morphClass: null
  +exists: true
  +wasRecentlyCreated: false
}
```

Data that you can input into *Point* column: 
```
0000000001010000001F351C09FA1C4A401387893E26043540
```

**Comment by jairovsky** [comment]
I just found out that `json_encode` does not play well with some binary strings.

Try this:
```php
var_dump ( json_encode ( hex2bin("0000000001010000001F351C09FA1C4A401387893E26043540") ) );
```
As far as I tested, it will silently fail and return:
- `bool(false)` in PHP 5.6.14
- `string(4) "null"` in PHP 5.5.

Now try this (assuming that your `User` has some binary column):
```php
$user = User::find( ... );

var_dump($user->toJson());
```

If `json_encode` fails, the effect will be propagated and `toJson()` will return `false` too.

**Comment by xiphiaz** [comment]
JSON the format doesn't support binary directly - they are expected to be encoded as strings - typically base64 encoding is used.

It should be then up to the developer to manage the casting/hydration of the data coming back to the model into a string that can be encoded by json. It might be appropriate to add a `binary` option to `Model::castAttribute` to allow the Model to register the binary casting in `$casts`

**Comment by Nicarim** [comment]
Problem here is that:
 - there is no descriptive error, but rather framework complete failure
 -  it ignores hidden properties
Both should be addressed in my opinion, sadly I don't have time to do that

In the meanwhile, fix here is to add method that allows removing underlaying class properties $attributes and $original which have binary data, then it works.
