### ISSUE TITLE
Suggestion: Collection::column() / toList()

### ISSUE THREAD

**Issue by igorsantos07** [laravel/framework#11107]
I'm willing to implement the inner code if there's a green flag for this feature: similar implementation of the new-ish [`array_column()`](http://br2.php.net/manual/en/function.array-column.php) for Laravel Collections. Useful for creating a simple list of items through `ul` or `select`, for instance :)

It's not possible to pass a Collection into the method since it expects an array, not an object...

**Comment by rkgrep** [comment]
You can use `$collection->pluck('column', 'key')->all();`
