### ISSUE TITLE
Problematic testing with assertResponseStatus - it does not return fluent object

### ISSUE THREAD

**Issue by vukanac** [laravel/framework#11106]
This test pass:

      $this->actingAs($user)
             ->get('/company/'.$company->id)
             ->see($company->id)
             ->assertResponseStatus(200);

But this fails:

      $this->actingAs($user)
             ->get('/company/'.$company->id)
             ->assertResponseStatus(200)
             ->see($company->id);

with error ~ accessing method `see` on non-object `null`.
Laravel Framework version 5.1.24 (LTS).

**`assertResponseStatus()`  - it does not return fluent object.**

Solutions:
* `assertResponseStatus()` should be called last in fluent chain (hm!), or
* create similar method in `InteractWithPage.php` that will return fluent object like others.

**Comment by GrahamCampbell** [comment]
We're open to PRs. :)
