### ISSUE TITLE
Larvel does not let me run postgres "string_agg()" method

### ISSUE THREAD

**Issue by kadnan** [laravel/framework#11110]
So here is my query:

```
$result = self::where
(['posts.id' => $id, 'user_id' => $user_id])
->leftJoin('post_attachments', 'posts.id', "=", 'post_attachments.post_id') 
->leftJoin('project_types', 'posts.project_type_id', '=', 'project_types.id') 
->groupBy(['posts.id','project_type_name']) 
->select('posts.*',\DB::raw('string_agg("post_attachments"."file_name",",") as file_names'),
'project_types.name as project_type_name') ->get();
```

and the exception I am getting as:

```
SQLSTATE[42703]: Undefined column: 7 ERROR: column "," does not exist
LINE 1: ...fs".*, string_agg("post_attachments"."file_name",",") as fi...
^ 
```

I am using Laravel 5.1.14.

**Comment by darthmaim** [comment]
Well, the error says `column "," does not exist`, which should be enough for you to find your error:

```sql
string_agg("post_attachments"."file_name", ",")
                                            ^
```

Not a laravel bug.

**Comment by kadnan** [comment]
@darthmaim  the 2nd parameter is actually part of `string_agg`. How else then I mention it? I know exactly reason of error but not sure why is it coming an where am I doing wrong

**Comment by rkgrep** [comment]
Postgres uses single quote (`'`) for strings and double quotes (`"`) for expressions.
Youy should use `string_agg("post_attachments"."file_name",',')`

**Comment by kadnan** [comment]
It was escaping issue, not a Laravel one. Thanks for comments.
