### ISSUE TITLE
why use is_null?

### ISSUE THREAD

**Issue by undercloud** [laravel/framework#11111]
https://github.com/laravel/framework/search?utf8=%E2%9C%93&q=is_null
http://php.net/manual/ru/function.is-null.php#84161

**Comment by ArjanSchouten** [comment]
Have you read the whole note? Do you want to change it for speed? 
 1.  This is written 7 years ago and performance can be improved already! 
 2.  Micro optimization is not worth it!
 3.  Don't know if I always prefer the syntax ```===``` over the in some situations ```is_null```

What's your point? What do you want to say?

**Comment by GrahamCampbell** [comment]
Because we can.

**Comment by GrahamCampbell** [comment]
:troll:

**Comment by lucasmichot** [comment]
Sorry @GrahamCampbell but this time your reply killed and an Obama-isation is thus required

![yes-we-can](https://cloud.githubusercontent.com/assets/513603/11477272/8322ba6c-9787-11e5-909b-73845e2e05f7.jpg)

**Comment by GrahamCampbell** [comment]
LOL. If it were my choice, we'd not be using the `is_null` function, but it's not, and even then, changing it is kind of pointless anyway.

**Comment by ArjanSchouten** [comment]
Lets skip null at all :smile: never get a null references :smile:

**Comment by neomerx** [comment]
**GrahamCampbell**
> Because we can.
> changing it is kind of pointless anyway.

hubris is pointless

is_null is a function and calling it has some costs. Before `Closures` it was convenient to pass it to algorithm function.

```
is_null time:0.49425601959229
!==null time:0.13493800163269
diff 3.6628378485823 x times
```

```php
const N = 1000000;

function getTime(Closure $closure, &$time)
{
    $time_start = microtime(true);
    try {
        return $closure();
    } finally {
        $time_end = microtime(true);
        $time     = $time_end - $time_start;
    }
}

$functionTime = 0;
getTime(function () {
    for ($idx = 0; $idx < N; ++$idx) {
        is_null($idx);
    }
}, $functionTime);

$operatorTime = 0;
getTime(function () {
    for ($idx = 0; $idx < N; ++$idx) {
        $idx !== null;
    }
}, $operatorTime);

echo 'is_null time:' . $functionTime . PHP_EOL;
echo '!==null time:' . $operatorTime . PHP_EOL;
echo 'diff ' . $functionTime / $operatorTime . ' x times' . PHP_EOL;
```
