### ISSUE TITLE
ConnectionFactory does not consider database when resolving from IoC container

### ISSUE THREAD

**Issue by spiritix** [laravel/framework#11122]
Laravel provides the possibility to use custom connection classes, see ConnectionFactory.php:210

```php
    protected function createConnection($driver, PDO $connection, $database, $prefix = '', array $config = [])
    {
        if ($this->container->bound($key = "db.connection.{$driver}")) {
            return $this->container->make($key, [$connection, $database, $prefix, $config]);
        }

        switch ($driver) {
            case 'mysql':
                return new MySqlConnection($connection, $database, $prefix, $config);
       
        // ...
    }
```

Then in a service provider one can just register his custom connection class:

```php
        $this->app->singleton('db.connection.mysql', function ($app, $parameters) {
            list($connection, $database, $prefix, $config) = $parameters;
            return new CustomMysqlConnection($connection, $database, $prefix, $config);
        });
```

Unfortunately it does not consider the database name when resolving from the IoC container.
This works well if you are using only one database, but as soon as you are using multiple databases within the same driver it won't work anymore.
Then you'll be required to bind the regular way without singleton which creates a new connection instance every time a model is being used.

It would be much better if resolving from the container would be done like this:

```php
        if ($this->container->bound($key = "db.connection.{$driver}.{$database}")) {
            return $this->container->make($key, [$connection, $database, $prefix, $config]);
        }
```

**Comment by crynobone** [comment]
Any reason why you are using singleton instead of bind?

**Comment by spiritix** [comment]
Well if you use "bind", the container will create a new instance of the connection class every time you initialize a model (at least). This results in a lot of open connections which is quite bad...

**Comment by crynobone** [comment]
> the container will create a new instance of the connection class every time you initialize a model (at least).

Why would it do that when `DatabaseManager` already cache the resolved instance? 

https://github.com/laravel/framework/blob/5.1/src/Illuminate/Database/DatabaseManager.php#L66-L72

Unless there a bug with that and you're seeing new connection on every model initialisation.

**Comment by spiritix** [comment]
Right, did not consider DatabaseManager.
