### ISSUE TITLE
Laravel 5 routing

### ISSUE THREAD

**Issue by nayanafrancis** [laravel/framework#11123]
I am trying to create HMVC structure in laravel.I have  created a modules folder with sub folders in it(form and project).

This project folder has in it controller,route.php and ServiceProvider.php.I want to route to method in the project controller but when i try i get the error 'Class Modules\Project\Controllers\ProjectController does not exist'.

How to load controller method from it's route.

This is the structure of files in modules folder.
![iimvv](https://cloud.githubusercontent.com/assets/16097958/11497316/2ecee684-97e6-11e5-8798-30fa15d8c04f.png)

**Comment by nayanafrancis** [comment]
@GrahamCampbell 
Can you please tell me why this issue was closed, i am a bit confused about doing this.Could you please help me?

**Comment by GrahamCampbell** [comment]
Please ask on the forums,

**Comment by nayanafrancis** [comment]
Thankyou.
