### ISSUE TITLE
Array to string conversion when _token is array

### ISSUE THREAD

**Issue by andkom** [laravel/framework#11124]
When I submit form with *_token* variable as array:

```html
<form>
<input name="_token[]" value="..." type="hidden">
.....
</form>
```

 I get:

```
ErrorException in Str.php line 296: Array to string conversion
```

Stacktrace:

```php
....
Str::equals(string, array) in VerifyCsrfToken.php line 87
VerifyCsrfToken->tokensMatch(object(Request)) in VerifyCsrfToken.php line 49
VerifyCsrfToken->handle(object(Request), object(Closure))
...
```

**Comment by spiritix** [comment]
``_token`` is a reserved keyword for Laravel's internal CSRF protection, see http://laravel.com/docs/5.1/routing#csrf-protection

Just use another name.

**Comment by GrahamCampbell** [comment]
Thanks for catching this bug. We need to check it's type first rather than casting it. I'll make that update now.

**Comment by GrahamCampbell** [comment]
See https://github.com/laravel/framework/pull/11126.

**Comment by andkom** [comment]
I know, i already use laravel's built in CSRF protection.
I meant Laravel doesn't handle this error itself, when user submit _token as array. So any user can potentially down the site.
