### ISSUE TITLE
Laravel 5.1 login error

### ISSUE THREAD

**Issue by zekree** [laravel/framework#11140]
i am using laravel authentication without any changes or overrides on default auth controller and suddenly the login doesn't work and always give the message
These credentials do not match our records.
i am using the correct credentials but it doesn't login
when i try to reset password the reset works and log me in after password reset but when i log out i can't log in again.
any help please.

**Comment by RomainLanz** [comment]
Can I see your html for your login form?

**Comment by zekree** [comment]
<div class="cls-content">
			<div class="cls-content-sm panel">
				<div class="panel-body">
					@if($errors->any())
					<div class="alert alert-danger">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						<strong>Error!</strong>
						@foreach($errors->all() as $error)
							<p>{{ $error }}</p>
						@endforeach
					</div>
					@endif

					<p class="pad-btm">Sign In to your account</p>
					{!! Form::open(['method' => 'POST', 'url' => 'auth/login', 'role' => 'form']) !!}
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon"><i class="fa fa-envelope"></i></div>
								{!! Form::text('email', null, ['class' => 'form-control', 'id' => 'email', 'placeholder' => 'Email']) !!}
							</div>
						</div>
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon"><i class="fa fa-asterisk"></i></div>
								{!! Form::password('password', ['class' => 'form-control', 'id' => 'password', 'placeholder' => 'Password']) !!}
							</div>
						</div>
						<div class="row">
							<div class="col-xs-8 text-left checkbox">
								<label class="form-checkbox form-icon">
								{!! Form::checkbox('remember') !!} Remember me
								</label>
							</div>
							<div class="col-xs-4">
								<div class="form-group text-right">
								{!! Form::submit('Sign In', ['class' => 'btn btn-success text-uppercase']) !!}
								</div>
							</div>
						</div>
					</form>
				</div>
			</div>
			<div class="pad-ver">
				<a href="{{ url('/password/email') }}" class="btn-link mar-rgt">Forgot password ?</a>
				<a href="{{ url('/auth/register') }}" class="btn-link mar-lft">Create a new account</a>
			</div>
		</div>

**Comment by GrahamCampbell** [comment]
Please ask on the forums. :)

**Comment by zekree** [comment]
this is a bug
