### ISSUE TITLE
[Proposal] improve performance by optimizing the use of `debug_backtrace`

### ISSUE THREAD

**Issue by AaronJan** [laravel/framework#11157]
There are 5 places used `debug_backtrace` like this:

```php
debug_backtrace(false);
```

According to [php.net](http://php.net/manual/en/function.debug-backtrace.php):

> Before 5.3.6, the only values recognized are TRUE or FALSE, which are the same as setting or not setting the DEBUG_BACKTRACE_PROVIDE_OBJECT option respectively.

And there's more:

> As of 5.3.6, this parameter is a bitmask for the following options:
> DEBUG_BACKTRACE_PROVIDE_OBJECT	Whether or not to populate the "object" index.
> DEBUG_BACKTRACE_IGNORE_ARGS	Whether or not to omit the "args" index, and thus all the function/method arguments, to save memory.

 `Laravel 5.1` requires `PHP >= 5.5.9`, also these 5 places don't need the arguments (they just want the function name), so I think we can safely use the `DEBUG_BACKTRACE_IGNORE_ARGS` option.

I did these changes in my project and works just fine (why wouldn't..). 

I found [an old proposal](https://github.com/laravel/framework/issues/3567) that had the same thing I said.

**Comment by GrahamCampbell** [comment]
We're open to PRs, but don't process proposal issues. ;)

**Comment by AaronJan** [comment]
Can I make a PR about this? :smile:

**Comment by GrahamCampbell** [comment]
Thanks. :)
