### ISSUE TITLE
[Bug?] SQLSRV query fail with fatal error 'Maximum function nesting level of '256' reached, aborting!'

### ISSUE THREAD

**Issue by wuhsien** [laravel/framework#11156]
I have multiple database connections in `config/database.php`:

```php
'connections' => [
    'mysql' => [
        'driver'    => 'mysql',
        'read' => [
            'host' => env('DB_READ_HOST', 'localhost'),
        ],
        'write' => [
            'host' => env('DB_WRITE_HOST', 'localhost'),
        ],
        'database'  => env('DB_DATABASE', ''),
        'username'  => env('DB_USERNAME', ''),
        'password'  => env('DB_PASSWORD', ''),
        'charset'   => 'utf8',
        'collation' => 'utf8_unicode_ci',
        'prefix'    => '',
        'strict'    => false,
    ],
    'sqlsrv' => [
        'driver'   => 'sqlsrv',
        'host'     => 'localhost',
        'database' => 'mytest',
        'username' => '',
        'password' => '',
        'charset'  => 'utf8',
        'prefix'   => '',
    ],
]
```
I use `Query Builder` to qyery data from sqlserver, and will get the `Fatal error`:

```php
DB::connection('sqlsrv')->table($this->table)
    ->where('FDate', date('Ymd'))
    ->take(1)
    ->get();
```    

    PHP Fatal error:  Maximum function nesting level of '256' reached, aborting! in Unknown on line 0
    PHP Stack trace:
    PHP   1. {main}() /Users/..../fork/artisan:0
    PHP   2. Illuminate\Foundation\Console\Kernel->handle() /Users/..../fork/artisan:36
    PHP   3. Symfony\Component\Console\Application->run() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:107
    PHP   4. Symfony\Component\Console\Application->doRun() /Users/..../fork/vendor/symfony/console/Application.php:120
    PHP   5. Symfony\Component\Console\Application->doRunCommand() /Users/..../fork/vendor/symfony/console/Application.php:189
    PHP   6. Illuminate\Console\Command->run() /Users/..../fork/vendor/symfony/console/Application.php:838
    PHP   7. Symfony\Component\Console\Command\Command->run() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Console/Command.php:136
    PHP   8. Illuminate\Console\Command->execute() /Users/..../fork/vendor/symfony/console/Command/Command.php:256
    PHP   9. Illuminate\Container\Container->call() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Console/Command.php:150
    PHP  10. call_user_func_array:{/Users/..../fork/vendor/laravel/framework/src/Illuminate/Container/Container.php:503}() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Container/Container.php:503
    PHP  11. App\Console\Commands\SyncTWSE5MinutesChartSource->handle() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Container/Container.php:503
    PHP  12. App\Models\SqlSrv\QTSE012->demo() /Users/..../fork/app/Console/Commands/SyncTWSE5MinutesChartSource.php:19
    PHP  13. Illuminate\Database\Query\Builder->get() /Users/..../fork/app/Models/SqlSrv/QTSE012.php:15
    PHP  14. Illuminate\Database\Query\Builder->runSelect() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:1383
    PHP  15. Illuminate\Database\Query\Builder->toSql() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:1406
    PHP  16. Illuminate\Database\Query\Grammars\SqlServerGrammar->compileSelect() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:1315
    PHP  17. Illuminate\Database\Query\Grammars\Grammar->compileComponents() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/SqlServerGrammar.php:32
    PHP  18. Illuminate\Database\Query\Grammars\SqlServerGrammar->compileFrom() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php:62
    PHP  19. Illuminate\Database\Query\Grammars\Grammar->compileFrom() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/SqlServerGrammar.php:78
    PHP  20. Illuminate\Database\Grammar->wrapTable() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php:120
    PHP  21. Illuminate\Database\Grammar->wrap() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:39
    PHP  22. Illuminate\Database\Grammar->wrapTable() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:77
    PHP  23. Illuminate\Database\Grammar->wrap() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:39
    PHP  24. Illuminate\Database\Grammar->wrapTable() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:77
    PHP  25. Illuminate\Database\Grammar->wrap() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:39
    PHP  26. Illuminate\Database\Grammar->wrapTable() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:77
    PHP  27. Illuminate\Database\Grammar->wrap() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:39
    PHP  28. Illuminate\Database\Grammar->wrapTable() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:77
    PHP  29. Illuminate\Database\Grammar->wrap() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:39
    PHP  30. Illuminate\Database\Grammar->wrapTable() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:77
    PHP  31. Illuminate\Database\Grammar->wrap() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:39
    PHP  32. Illuminate\Database\Grammar->wrapTable() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:77
    PHP  33. Illuminate\Database\Grammar->wrap() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:39
    PHP  34. Illuminate\Database\Grammar->wrapTable() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:77
    PHP  35. Illuminate\Database\Grammar->wrap() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:39
    PHP  36. Illuminate\Database\Grammar->wrapTable() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:77
    PHP  37. Illuminate\Database\Grammar->wrap() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:39
    PHP  38. Illuminate\Database\Grammar->wrapTable() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:77
    PHP  39. Illuminate\Database\Grammar->wrap() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:39
    PHP  40. Illuminate\Database\Grammar->wrapTable() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:77
    PHP  41. Illuminate\Database\Grammar->wrap() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:39
    PHP  42. Illuminate\Database\Grammar->wrapTable() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:77
    PHP  43. Illuminate\Database\Grammar->wrap() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:39
    PHP  44. Illuminate\Database\Grammar->wrapTable() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:77
    PHP  45. Illuminate\Database\Grammar->wrap() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:39
    PHP  46. Illuminate\Database\Grammar->wrapTable() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:77
    PHP  47. Illuminate\Database\Grammar->wrap() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:39
    PHP  48. Illuminate\Database\Grammar->wrapTable() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:77
    PHP  49. Illuminate\Database\Grammar->wrap() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:39
    PHP  50. Illuminate\Database\Grammar->wrapTable() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:77
    PHP  51. Illuminate\Database\Grammar->wrap() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:39
    PHP  52. Illuminate\Database\Grammar->wrapTable() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:77
    PHP  53. Illuminate\Database\Grammar->wrap() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:39
    PHP  54. Illuminate\Database\Grammar->wrapTable() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:77
    PHP  55. Illuminate\Database\Grammar->wrap() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:39
    PHP  56. Illuminate\Database\Grammar->wrapTable() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:77
    PHP  57. Illuminate\Database\Grammar->wrap() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:39
    PHP  58. Illuminate\Database\Grammar->wrapTable() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:77
    PHP  59. Illuminate\Database\Grammar->wrap() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:39
    PHP  60. Illuminate\Database\Grammar->wrapTable() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:77
    PHP  61. Illuminate\Database\Grammar->wrap() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:39
    PHP  62. Illuminate\Database\Grammar->wrapTable() /Users/..../fork/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:77
    
I change the `xdebug` setting like following:

    [xdebug]
    zend_extension="/usr/local/opt/php56-xdebug/xdebug.so"
    xdebug.max_nesting_level = 1000
   
but it still got the same error.   
This is happening in Laravel 5.1.25 (LTS).
    
My PHP version is following:

    PHP 5.6.16 (cli) (built: Nov 28 2015 22:22:08) 
    Copyright (c) 1997-2015 The PHP Group
    Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
        with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
        with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans

**Comment by GrahamCampbell** [comment]
This was fixed in 5.1.26. :)
