### ISSUE TITLE
[Laravel 4.2] hasColumns in wrong database schema

### ISSUE THREAD

**Issue by thiagomata** [laravel/framework#11164]
This command:

    Schema::hasColumn('someschema.sometable', 'somecolumn');

Does not work as expected. It execute this query:

    select column_name from information_schema.columns where table_name = 'someschema.sometable'

When the right query should be something like:

    select column_name from information_schema.columns where table_name = 'sometable' and table_schema = 'someschema';

**Comment by GrahamCampbell** [comment]
Sorry. 4.2 is not supported.
