### ISSUE TITLE
[5.1] [5.2] SQLSRV query fail with fatal error 'Maximum function nesting level of '256' reached, aborting!'

### ISSUE THREAD

**Issue by wuhsien** [laravel/framework#11163]
mentioned in [[Bug?] SQLSRV query fail with fatal error 'Maximum function nesting level of '256' reached, aborting!'](https://github.com/laravel/framework/issues/11156)

I upgrade my `Laravel` version:

```
18:59:34 › php artisan -V
Laravel Framework version 5.1.26 (LTS)
```

and still got the same error

**Comment by GrahamCampbell** [comment]
Thanks for reporting. :)

**Comment by Modelizer** [comment]
@wuhsien try this cli command `php -i "echo phpinfo();" | grep "xdebug.max_nesting_level"` 

If the value is set to 256 then you have set `xdebug.max_nesting_level` in that file which is not loaded by PHP.

I think this should solve the problem because its seem related to xdebug, correct me if I'm wrong.

**Comment by GrahamCampbell** [comment]
@Modelizer No, there is an actual issue with an infinite loop here. Blindly just changing that value is not how to "fix" this.

**Comment by Modelizer** [comment]
@GrahamCampbell I faced the same issue and it was resolved my increasing `max_nesting_level` to 1000 and if loop is infinite then error will persist even after changing `max_nesting_level`.

**Comment by joko-wandiro** [comment]
@wuhsien just update XDebug configuration to 0 in php.ini and restart Apache.
xdebug.max_nesting_level = 0

**Comment by Modelizer** [comment]
@joko-wandiro I think it will go in an infinite loop :thinking: Would not be a better approach.

**Comment by GrahamCampbell** [comment]
> xdebug.max_nesting_level = 0

Not a good idea really.

**Comment by laurencei** [comment]
Can anyone confirm if this occurs on Laravel 5.5? 5.1 and 5.2 are no longer supported...
