### ISSUE TITLE
Can't Login After Logout

### ISSUE THREAD

**Issue by zekree** [laravel/framework#11162]
I think this is a bug
When the user logout he can't ever login again
I am using the default AuthController with no changes

The Error
These credentials do not match our records.

**Comment by bobbybouwmann** [comment]
I think this has something to do with your code and hashing the password. You can post a question on https://laracasts.com ;)

**Comment by zekree** [comment]
i posted in laravel.io but no good replies

i am hashing the password on creating the use by bcrypt
