### ISSUE TITLE
[5.1] [5.2] Optional morphTo relationship fatal error when not set

### ISSUE THREAD

**Issue by AdenFraser** [laravel/framework#11169]
i've just encountered an issue where when a morphTo relation is not defined for a model instance but is called, lets say with `if ($model->morphRelation()) {` then a fatal error occurs:
`Fatal error: Class '' not found in /vagrant/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php on line 875`

This seems like unexpected behaviour since if the relationship is optional, the expected response would be null or false (I'm assuming null) rather than an attempt to return a class based on the empty morph_type column.

This has been discussed as an issue briefly before, but didn't appear to go anywhere:
https://github.com/laravel/framework/issues/1450

I was wondering if this is expected behaviour, a bug or perhaps an enhancement could be made to allow for optional morphTo relations? If that's the case I'd look into it and create a PR with the outcome.

It just seems odd that every other relation either usually returns null (in the case of single relations not existing) or an empty collection (in the case of multi relations not being found) but with morphTo it does not.

Thoughts?

**Comment by GrahamCampbell** [comment]
Hmm. Thanks for reporting. This does look like a bug. Are you able to send a PR?

**Comment by AdenFraser** [comment]
Sure, I'll take a look into it tomorrow if I get a chance :)

**Comment by RobertYearwood** [comment]
Just weighing in as I hit this same issue.

This is technically not a bug, but a side-effect of the value for the morph_type field being an empty string ('') instead of a proper null.

The fix that we implemented involved copying the morphTo function from Illuminate\Database\Eloquent\Model.php to our base model and expanding the is_null check to also check for an empty string.

Specifically this:
```php
if (is_null($class = $this->$type)) {
```
Turned into:
```php
if (is_null($class = $this->$type) || $class === '') {
```

After that, it worked as expected for us.

**Comment by vjoao** [comment]
Any fix on this?

**Comment by garygreen** [comment]
Bump. I've having this same problem as well, it's even a problem on 4.2 upwards. Every other relationship allows for nullable but why not morphs?

**Comment by vaites** [comment]
You can use an accessor that check if has a relation:

    public function getNotificableAttribute()
    {
        if(!is_null($this->notificable_id))
        {
            return $this->relations['notificable'] = $this->notificable->getResults();
        }
    }

    public function notificable()
    {
        return $this->morphTo();
    }

**Comment by AdenFraser** [comment]
@vaites This is similar to a solution that I've been using too.

Never got around to putting together a PR... Guess i really should!

**Comment by vaites** [comment]
@AdenFraser I think there's no need to modify Laravel behaviour, there are only a few cases and is solved with only 5 lines of code. Maybe a better documentation on Eloquent relations suggesting an accessor...

**Comment by AdenFraser** [comment]
@vaites I disagree. While what you propose would be simpler, this is inconsistent behaviour with all other relation functionality.

**Comment by RobertYearwood** [comment]
It's a single line modification to resolve it and make it consistent with no breaking changes.

**Comment by AdenFraser** [comment]
@RobertYearwood Exactly. I'm putting in a PR now.
