### ISSUE TITLE
[Proposal] Container::offsetExists() should delegate to Container::bound()

### ISSUE THREAD

**Issue by levacic** [laravel/framework#11167]
Currently, [`Illuminate\Container\Container::offsetExists()`](https://github.com/laravel/framework/blob/6e5e2ef8b331fedc3ff1981590204efd593f93c4/src/Illuminate/Container/Container.php#L1140-L1149) just checks the internal `$bindings` array to figure out whether a binding exists.

However, instances and aliases can also be bound, but the method skips those, so testing for their existence via `isset($app['abstract'])` won't work.

I suggest that the method should just call [`$this->bound()`](https://github.com/laravel/framework/blob/6e5e2ef8b331fedc3ff1981590204efd593f93c4/src/Illuminate/Container/Container.php#L126-L135) instead - which would also check deferred services as well when called in the context of an application object (which is probably the context in which most people deal with a `Container` instance).

I can send a PR if others think my reasoning is correct, I'm just not sure if there is something I'm missing, ie. a specific reason why accessing the bindings via array syntax only performs the current check.

**Comment by GrahamCampbell** [comment]
Thanks for the report, but we don't process proposal issues, but we are open to PRs.
