### ISSUE TITLE
Artisan migrate always warns in producion

### ISSUE THREAD

**Issue by shrimpwagon** [laravel/framework#11176]
Not sure why it always says this. I realize there is a --force command but this seems counter-intuitive. If it involves setting a flag then I would like to know how and where.

**Comment by jarnovanleeuwen** [comment]
This message is shown when `APP_ENV` is set to `production`. Of course, this is to prevent you from accidentally running commands in a production environment. In your development environment you can set the value to `local` to get rid of the warning. See http://laravel.com/docs/5.1/installation#environment-configuration.
