### ISSUE TITLE
Problems with "active_url" validation, and suggested fix

### ISSUE THREAD

**Issue by cviebrock** [laravel/framework#11173]
There are several problems with the `active_url` validation rule:

```php
    protected function validateActiveUrl($attribute, $value)
    {
        $url = str_replace(['http://', 'https://', 'ftp://'], '', strtolower($value));

        return checkdnsrr($url, 'A');
    }
```

At a minimum, `checkdnsrr` works with hostnames, not URLs, which user's are likely to assume based on the rule's name.  Also, I'm not sure if the check will fail for hosts that use CNAME records to alias to another host (although this does seem to work).

In any event, "http://laravel.com/docs/5.1/validation" fails the `active_url` validation.

Could we at least change the function, so it only validates the hostname passed to it?  i.e.:

```php
    protected function validateActiveUrl($attribute, $value)
    {
        $host = parse_url($value, PHP_URL_HOST);

        return checkdnsrr($host, 'A');
    }
```

If we _really_ wanted to check the URL, I think the only true way would be to make a Guzzle request or something, and check for a 2xx response.  That's pretty slow, so I don't think I'd suggest it unless it was another validation rule entirely (to keep BC).

**Comment by nicholas-eden** [comment]
We encountered the same problem and ended up creating a custom validation rule similar to the one you posted.  It would make sense to change it in the framework.

**Comment by jairovsky** [comment]
Backward compatible suggestion:

- Add a `fully_active_url` validation rule (anyone got a better name?) that will make a cURL request (to avoid more dependencies on production code) and assert for a status code in 2xx range.

Non-backward compatible suggestion:
- Rename `active_url` to `active_domain`since the name is misleading;
- `active_url` will make a cURL request (to avoid more dependencies on production code) and assert for a status code in 2xx range.

Built-in functions can be mocked with https://github.com/php-mock/php-mock-mockery so cURL won't affect testability.

Opinions?

**Comment by cviebrock** [comment]
My opinion: keep `active_url` but use the code I posted above, so that it at least works as advertised.

I have no issue with creating a new validation rule that does an HTTP request, but making `active_url` do that is going to cause issues for people who already use that rule ("why do my validations take so long now?").  So I'd suggest a new rule for that ... `valid_url` for example, or `fully_active_url` (although that does seem rather wordy).

As for cURL vs other libraries, I don't have an opinion.  I'd probably lean towards using guzzle over native curl functions, though.

**Comment by murph133** [comment]
Create a custom validation rule: https://laravel.com/docs/5.4/validation#custom-validation-rules

AND

Create setters in the Eloquent model: https://laravel.com/docs/5.4/eloquent-mutators

**Comment by jengeese** [comment]
dear all,

I want to ask another question.

I use 'required|active_url' command to check if the form input is correct or not.

But I want to accept also the url address which starts with "www." only instead of "https//:www." how to ignore http:// , https:// etc.?
