### ISSUE TITLE
Laravel 5.1 big issue with Centos OS

### ISSUE THREAD

**Issue by dhiman252** [laravel/framework#11196]
Hi Team,

I have recently created a project and uploaded it on the live server and found that it get breaks on every form request.

Please have a look at the actual error link.
Error Link -> http://prntscr.com/9a8hdh

One major concern is that the same app when hosted on ubuntu server works fine.

It is very frustrating as i am not able to figure out the actual break-off of the laravel app.
After spending a lot of time debugging i found that on my browser the laravel default cookie is not generated.

Is there any specific settings to Centos OS which we need to make so that it can get started working ?

I have also installed a fresh project on the Centos server but the same problem exists there but working fine on the ubuntu.

**Comment by GrahamCampbell** [comment]
Doesn't look a bug specific to CentOS, more a configuration issue. Please discuss on the forums.
