### ISSUE TITLE
phpunit failure after upgrade to phpunit 5.1.0, framework 5.1.26

### ISSUE THREAD

**Issue by zachleigh** [laravel/framework#11197]
After upgrading phpunit/phpunit to 5.1.0 and laravel/framework to 5.1.26, tests will not run.  Here's the error message:
```
PHP Fatal error:  Call to a member function instance() on null in /home/zachleigh/Web/Nihongodera/vendor/laravel/framework/src/Illuminate/Foundation/Testing/ApplicationTrait.php on line 189
```
   
Dumping $this->app in ApplicationTrait shows null.   
   
Laracasts thread: https://laracasts.com/discuss/channels/laravel/laravel-51-and-phpunit-51-error

**Comment by GrahamCampbell** [comment]
This is a known issue. Thank you though.

**Comment by GrahamCampbell** [comment]
Officially, we only support phpunit 4.x though.

**Comment by GrahamCampbell** [comment]
Since, phpunit 5.x has exception handler issues, and doesn;t support php 5.5, and phpunit 5.1+ has broken all our before annotations.

**Comment by GrahamCampbell** [comment]
> doesn;t support php 5.5

It's important that people's lock files work on php 5.5, otherwise it's incorrect to say that their app supports php 5.5.

**Comment by zachleigh** [comment]
Thanks for clearing that up Graham.
