### ISSUE TITLE
[5.1] No fireModelEvent for models touched by touches

### ISSUE THREAD

**Issue by mattmcdonald-uk** [laravel/framework#11198]
Not sure if this is a bug or by design?

Any model for which you have registered an observable event (like saved), that event won't get called when it's triggered by a child that touches the parent model.

So if you have code that runs when the 'saved' event is observed on model A, that code won't get triggered if a model which touches model A is saved.

But model A is being saved, its timestamp changes and that change is saved.

**Comment by jairovsky** [comment]
Can you create a project reproducing the error? Also, which Laravel version are you using?

It's working for me on `5.1.26`.

**Comment by GrahamCampbell** [comment]
Anything other than the latest 5.1.x version is not supported. 5.1.26 is currently the latest.

**Comment by mattmcdonald-uk** [comment]
@jairovsky I created an example repo here: https://github.com/mattmcdonald-uk/l51-bug-reproduce

You'll need to create an entry in the towns table and an entry in the countries table. The entry in the towns table needs to be linked to the entry in the countries table.

When you visit the "/" route the record with ID 1 for Town model is saved. Town model touches Countries model, and the Country updated_at is being set correctly.

If you look at EventServiceProvider, saving a country should trigger an event. And if you save a Country directly that event is triggered. But saving the Town which touches the Country doesn't trigger the event.

@GrahamCampbell This is happening in the latest supported version, 5.1.26 

I can submit a PR for this, but want to see if intended behaviour or not?

**Comment by GrahamCampbell** [comment]
We're open to PRs. I find they;re an easier way to debate the expected behaviour.
