### ISSUE TITLE
Manage single session on laravel and magento

### ISSUE THREAD

**Issue by pratikindia143** [laravel/framework#11193]
I want manage single session on laravel application and magento application. so i have changed the laravel session name to frontend as magento uses frontend as the cookie name and both are under same domain name.

 So i thought it would be simple as i will be able to get session details on both application but its little tricky as laravel set session id encrypted in session cookies. 

Is there any way i can disable the encryption of session while creating session cookies or i can override the session management in laravel only for this encryption of session cookie. 

Even i also want to exactly where this encryption is done while creating session cookies in the code so i can verify as it will work or not?

**Comment by GrahamCampbell** [comment]
Please ask on the forums.

**Comment by pratikindia143** [comment]
Ok thanks buddy
