### ISSUE TITLE
The 'sometimes' validation rule will skip validation if you only input a whitespace

### ISSUE THREAD

**Issue by mengidd** [laravel/framework#11204]
If you use this validation rule:
```
$this->validate($request, [
    'password' => 'sometimes|min:6'
]);
```

When the user enters a whitespace as password, it will not run the "min:6" validation rule and the password is "valid" according to the validator and $request->get('password') will return a whitespace.

**Comment by KennedyTedesco** [comment]
You need to add the `required` rule.

```
$this->validate($request, [
    'password' => 'sometimes|required|min:6'
]);
```
