### ISSUE TITLE
Error when try to register user

### ISSUE THREAD

**Issue by APdevelopments** [laravel/framework#11219]
I try to register user at this view /auth/register ... I fill everything properly but when I click to register then laravel show me this message:

FatalErrorException in User.php line 8:
Class 'Illuminate\Foundation\Auth\User' not found

in User.php line 8
at FatalErrorException->__construct() in HandleExceptions.php line 133
at HandleExceptions->fatalExceptionFromError() in HandleExceptions.php line 118
at HandleExceptions->handleShutdown() in HandleExceptions.php line 0
in ClassLoader.php line 412

etc... ...

Can somebody tell me what is the problem here and how to solve it?

**Comment by GrahamCampbell** [comment]
Sounds like you're using Laravel 5.2 code on Laravel 5.1.

**Comment by APdevelopments** [comment]
but I change in composer.json rom laravel 5.2.* to 5.1.* and then run composer update...

**Comment by APdevelopments** [comment]
this is my composer.json file:

{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1.*",
        "doctrine/dbal": "^2.5",
        "laravelcollective/html": "~5.1",
        "illuminate/html": "~5.0",
        "bestmomo/scafold": "dev-master"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "symfony/css-selector": "2.7.*",
        "symfony/dom-crawler": "2.7.*"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-install-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "pre-update-cmd": [
            "php artisan clear-compiled"
        ],
        "post-update-cmd": [
            "php artisan optimize"
        ],
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ]
    },
    "config": {
        "preferred-install": "dist"
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}

**Comment by APdevelopments** [comment]
@GrahamCampbell  How to swich version from 5.2 to 5.1 ... I was tried to change composer.json file and run composer update... but as you can see dont work - I cant register user...

**Comment by GrahamCampbell** [comment]
But, your code in your app is using a class that only exist in 5.2...

**Comment by APdevelopments** [comment]
I only have model Article that I rewrite from beginer-laracast tutorial...

**Comment by APdevelopments** [comment]
Can I just delete vendor folder, change at composer.json laravel version and  then run composer install  ?

**Comment by GrahamCampbell** [comment]
No. I'm referring to your actual app code.

**Comment by GrahamCampbell** [comment]
Please ask on the forums

**Comment by APdevelopments** [comment]
@GrahamCampbell ok - https://github.com/laravel/framework/issues/11220
