### ISSUE TITLE
Eloquent's save() doesn't work with non-increments primary key

### ISSUE THREAD

**Issue by artaex** [laravel/framework#11212]
Eloquent seems to have problems updating models when the primary key is not an integer.

**Schema creation code (this causes problems):**
```
Schema::create('sessions', function(Blueprint $table) {
  $table->char('id', 32)->primary();
  $table->string('test');
});
```

Initially creating and inserting the model with ``save()`` works fine, but calling it a second time won't result in an updated table row.

**Test code:**
```
$session = new Session();
$session->test = 'Hey!';
$session->save(); // This part works fine. Creates a new row in the database

$session->test = 'Hello';
$session->save();
// Nothing happens. Local model attributes are updated, but database record remains unaltered.
// The test attribute in the database contains 'Hey!'
```

**The workaround:**
By changing the Schema creation code to the following, the problem is solved:
```
Schema::create('sessions', function(Blueprint $table) {
  $table->increments('id');
  $table->char('session_id', 32)->unique();
  $table->string('test');
});
```

However, I should be able to use a non-integer attribute as a primary key. So I guess it's a bug.

**Note:** This has nothing to do with Laravel's sessions.

**Comment by GrahamCampbell** [comment]
Not a bug. You need to set the increments property on the model to false.

**Comment by GrahamCampbell** [comment]
This caught me out in the past too, though. I make an idiot of myself on https://github.com/laravel/framework/issues/6440. Feel free to have a read through. It should explain the problem you're having. :)
