### ISSUE TITLE
Laravel say that Auth guard [] is not defined

### ISSUE THREAD

**Issue by APdevelopments** [laravel/framework#11216]
I'm beginer and I start learn and code with laravel... To enable user login nad registration I write this (as I see on one tutorilal):

at routes.php

 Route::controllers([
     'auth'=>'Auth\AuthController',
     'password'=>'Auth\PasswordController', ]);
and now when I type: http://localhost:8888/auth/login I get error:

InvalidArgumentException in AuthManager.php line 71: Auth guard [] is not defined.

http://i.stack.imgur.com/2MgUj.png

Also in view folder there is no auth directory and login.blade.php files and other. I add it manually from Laravel5.0 but again I get message: Auth::guard[] is not defined

Please help me...

**Comment by crynobone** [comment]
> Auth guard [] is not defined

This would only happen if you're on Laravel Framework v5.2 (which is still under development). Are you sure you have the right version installed.

**Comment by APdevelopments** [comment]
hm, yes, but How to swich now to 5.1 or 5.0 (What you suggest?) ? I already have many created code so I dont want to strt from strach

**Comment by GrahamCampbell** [comment]
Make sure you don't have something like `~5.1` for a version constraint on `laravel/framework`. Put `5.1.*` or something.
