### ISSUE TITLE
Illuminate\Database\Eloquent\Factory::{closure}()

### ISSUE THREAD

**Issue by radiart** [laravel/framework#11221]
I have error: ``Missing argument 2 for Illuminate\Database\Eloquent\Factory::{closure}()``

When I using ``$factory->defineAs``

**FACTORY:**

$factory->define('App\Content', function ($faker) {
    // Title & Seo Title
    $title = $faker->sentence($nbWords = 6, true);
    $seo_url = Safeurl::make($title);
    return [
        'user_id'         => factory('App\User')->create()->id,
        'title'           => $title,
        'content'         => $faker->sentences($nb = 3, true),
        'default_photo'   => factory('App\Photo')->create()->id,
   	'seo_url'         => $seo_url,
    ];
});

// Ads
$factory->defineAs('App\Content', 'ads', function ($faker) use ($factory) {
    $content = $factory->raw('App\Content');
    return array_merge( $content, [
        'content_type_id' => 1
    ]);
});

// Profiles
$factory->defineAs('App\Content', 'profiles', function ($faker) use ($factory) {
    $content = $factory->raw('App\Content');
    return array_merge( $content, [
        'content_type_id' => 2
    ]);
});

**SEED:**

    	// Ads
        factory('App\Content', 'ads', 50)
        	->create()
        	->each( function( $i ) {

	        	// Ads
	        	$i->ads()->save( factory( App\Ads::class )->make() );

	        	// Photos
	        	for ($x = 0; $x <= 2; $x++) {
					$i->photos()->save( factory( App\Photo::class )->make() );
				} 
	    	});``

       	// Profiles
        factory('App\Content', 'profiles', 50)
        	->create()
        	->each( function( $i ) {

	        	// Photos
	        	for ($x = 0; $x <= 2; $x++) {
					$i->photos()->save( factory( App\Photo::class )->make() );
				} 
	    	});

**Comment by radiart** [comment]
@GrahamCampbell  ?

**Comment by bulgariamitko** [comment]
i guess there is a problem in your code and not the framework itself, best idea is to post if u have questions like those in stackoverflow then here. i guess that's why @GrahamCampbell  have closed your issue without telling you anything
