### ISSUE TITLE
Call to a member function getConnection() on null in Capsule/Manager

### ISSUE THREAD

**Issue by CupOfTea696** [laravel/framework#11235]
When using the Capsule Manager from `illuminate/database` I get the error `Call to a member function getConnection() on null in Capsule/Manager`

I quickly checked the file, and the $instance variable is never actually set.

See: https://github.com/illuminate/database/blob/master/Capsule/Manager.php#L74

**Comment by GrahamCampbell** [comment]
You need to set it. ;)

**Comment by CupOfTea696** [comment]
Ooh you need to setAsGlobal method, I see now :p

**Comment by extsalt** [comment]
`$capsule->setAsGlobal();`
