### ISSUE TITLE
Paginator Exception

### ISSUE THREAD

**Issue by Sladewill** [laravel/framework#11241]
If a user enters ?page=1e309 into a page containing a paginator it will break the page and return an error like -9223372036854775808 because 1e309 resolves to a number.

> SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-9223372036854775808' at line 1

It appears all sites running laravel have this issue including laracasts - https://laracasts.com/discuss?page=1e309

@maclof

**Comment by GrahamCampbell** [comment]
For reference: https://3v4l.org/OWOf7.

**Comment by Sladewill** [comment]
Fixed by commit https://github.com/laravel/framework/commit/83ad23cbd3b7d1b3930cd68d57776aae331ce7f5
