### ISSUE TITLE
Namespace specified in routes.php gets inherited outside of group.

### ISSUE THREAD

**Issue by sigismund** [laravel/framework#11247]
In Lumen routes.php namespace is inherited outside of Route::group.

```
$app->group(['namespace' => 'App\Http\Controllers'], function ($app) {
	$app->get('/sample/{category}', 'ContentController@show');
	$app->group(['prefix' => 'something', 'middleware' => 'wordpress', 'namespace' => 'App\Http\Controllers\Wordpress'], function ($app) {
		$app->get('/', 'ContentController@show');
		$app->get('/{slug:[a-z0-9-/]+}', 'ContentController@show');
	});
	$app->get('{route:[a-z0-9-/]+}', 'ContentController@show');
});
```
Using the following code I get `Class ContentController does not exist` error. But if I add namespace to last ContentController or remove nested group, everythng works fine. 

Not sure if this happens also in Laravel routing...

**Comment by GrahamCampbell** [comment]
This is the expected behaviour. Your routing service provider adds a group for you.
