### ISSUE TITLE
Upgrade from 5.0 to 5.1 leads into VerifyCsrfToken error

### ISSUE THREAD

**Issue by vaske** [laravel/framework#11254]
Hey guys,

I followed up procedure for upgrade to 5.1.0 version and after that I run into this error

`FatalErrorException in VerifyCsrfToken.php line 33:
Class 'Symfony\Component\Security\Core\Util\StringUtils' not found`

any hint what I'm missing here?

**Comment by GrahamCampbell** [comment]
Please upgrade to the latest 5.1.x rather than 5.1.0.

**Comment by GrahamCampbell** [comment]
> VerifyCsrfToken.php

Is that in laravel/laravel. If so, you need to update it to use the laravel 5.1 version.

**Comment by vaske** [comment]
@GrahamCampbell yeah my version is 5.1.26

**Comment by GrahamCampbell** [comment]
Did you delete the compiled.php file?

**Comment by vaske** [comment]
I do not have compiled.php at my code base.

**Comment by GrahamCampbell** [comment]
This doesn't look like a bug in our code. Looks more like your code is relying on a dependency that we no longer have. As I said, you need to fix your middleware. Do a search of your code for `equals(`.

**Comment by GrahamCampbell** [comment]
Any other questions, please ask on the forums.

**Comment by vaske** [comment]
gotcha, seems like composer didn't update laravel code base on proper way, I see `abstract class BaseEncrypter` but that one doesn't exist anymore, etc..
