### ISSUE TITLE
form-data not accessible in middleware via $request

### ISSUE THREAD

**Issue by Vishal0203** [laravel/framework#11278]
Hi,

I'm unable to access my form-data in middleware, however, If I send the same data as a JSON, I can access it. Is anything missed in the documentation? Any resolution to this?

The question relating this
http://stackoverflow.com/questions/34191178/laravel-5-1-unable-to-get-form-data-in-middleware

**Comment by GrahamCampbell** [comment]
Please direct questions to the forums.
