### ISSUE TITLE
Exception Context missing with Artisan Console Commands

### ISSUE THREAD

**Issue by superdummy** [laravel/framework#11279]
Please, please, please improve the Exception Context, that is provide Full(!) Stacktrace with Artisan Console Commands (-vvv Options, but they seem to not work):

`D:\xampp\htdocs\app>php artisan route:list -vvv
  [Symfony\Component\Debug\Exception\FatalErrorException]
  Cannot use View as View because the name is already in use`

Or 

`D:\xampp\htdocs\app>php artisan route:list -vvv
  [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'App\Http\Controllers\UserBaseController' not found`

I have an App with about 50 Controllers (with lots of inheritance) and I am now in the second hour to find the problems, what should be a thing of a second. (I now have to strip all packages of the framework and reinclude them one by one as I have no clue, where the second error comes from. This classname is actually constructed somewhere by concatenating a base namespace with the class name but I was not able to find where this is done, So (partial) String matches failed). That's so important for a framework to have a full stacktrace if something is going wrong. 

Thanks!

UPDATE:
`ReflectionExceptions` are however reported with full stacktrace using the -vvv option!

**Comment by tomschlick** [comment]
:+1: for better exceptions in the console

**Comment by GrahamCampbell** [comment]
We just use symfony to do that. If there's anything we're doing wrong, please send a pull request.

**Comment by GrahamCampbell** [comment]
Actually, this is NOT a bug. FatalErrorException will NEVER give you lots of detail. Only actual exceptions will do that.

**Comment by GrahamCampbell** [comment]
FatalErrorException is NOT an exception - it's created from when a Throwable is thrown, and we have to convert it to an exception for display. We will never be able to support Throwables correctly because symfony will never change the typehints on it's methods for BC reasons.

**Comment by superdummy** [comment]
Hello Graham, thanks for your answer. 

What I meant is not necessarily a full stacktrace, but at least some minimum information, that allows to resolve where the error happend.  The Information is there, but it is not propagated and this needs to be addressed: 

Please see, how to reproduce the problem and note the small differences (that are so important)

1.)	Create an Syntax Error by inserteing in  a Controller (here FrontendBaseController) an arbitrary character  (here„c“)

2.)	
`php artisan route:list
[Symfony\Component\Debug\Exception\FatalErrorException]
syntax error, unexpected 'c' (T_STRING), expecting function (T_FUNCTION)`

3.)	Calling it from via Brwoser: 
`FatalErrorException in FrontendBaseController.php line 13:syntax error, unexpected 'c' (T_STRING), expecting function (T_FUNCTION)`
`1.	in FrontendBaseController.php line 13`
`... Full stacktrace here`

Here I get the File and Line Number the error occured and that's so important! Otherwise I will have to go through all(!) files to find the error. And I do not know which file contained the error. That not programming that's guessworking. 

You are the Laravel and Symphony Expert. So my question is: Is this really impossible to get the `„FatalErrorException in FrontendBaseController.php line 13:“` passed to the console? Thats the minimum Information, that helps to resolve a problem in a state of art fashion. Is this really impossible to get this information in the console Output too? 

Thanks

**Comment by GrahamCampbell** [comment]
Interesting. It's possible that this might be something that symfony need to fix, but I'm not entirely sure. I'll re-open this until someone has time to investigate the ootions.

**Comment by superdummy** [comment]
Thanks opening it for investigation.

For the Experts to start with: 
Instead of `dd` my whole app I spend the time looking at the exception handling. It seems that when integrating this 	
`dd($e);`
in the `renderForConsole()` method, of 
https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Exceptions/Handler.php#L141 than all relevant information is printed out.

This helped me to find the error reletively fast, as the the dump contained all relevant information. Maybe this is helpfull for anyone in the meantime.

**Comment by laravel-internals** [comment]
Sorry, we don't process requests/proposals here. Please see https://github.com/laravel/internals/issues.

**Comment by SirriC** [comment]
I get the line of the error in php5.6 but not php7.
