### ISSUE TITLE
Making the Config Facade Mockable from TestCases

### ISSUE THREAD

**Issue by JamesGuthrie** [laravel/framework#11273]
As others (#4072, #8979), I have run into the issue that it's not possible to naïvely mock the config facade in a Laravel `TestCase`.

After some digging, it appears to be possible to do so, albeit somewhat non-trivial. As I am not a Laravel expert, I would like some feedback on the details the implementation which would make this possible.

### The issue

```
Config::shouldReceive('get')
    ->once()
    ->with('config.param.path')
    ->andReturn($my_override);
```

"Naïve" mocking doesn't work in a `TestCase` in which the config is mocked and then a request is made to the application. The reason for this is that the mocked config is only capable of responding to the single method which it is configured to respond to, and not to the plethora of queries which are made to the config in a typical request.

### The simple solution

Apparently it's possible to use `Config::set('config.param.path', $my_override)`. While this works, it still seems as though it ought to be possible to mock the config facade as others can be mocked.

### The solution

Fortunately, Mockery provides the helpful `shouldDeferMissing()` function, which will defer any calls which cannot be fulfilled by the mock to the class being mocked. Adding this line in the `Facade.php` would make the backing Config class respond. Fantastic!

```
protected static function createFreshMockInstance($name)
{
    static::$resolvedInstance[$name] = $mock = static::createMockByName($name);

    $mock->shouldAllowMockingProtectedMethods();
    $mock->shouldDeferMissing();

    if (isset(static::$app)) {
        static::$app->instance($name, $mock);
    }

    return $mock;
}
```

Not quite. A chicken-egg problem arises in Laravel. In order to mock the Config facade, the application needs to be loaded (to access the Facades). Once mocked, the new Config does not contain any values, because the config was already bootstrapped on application initialisation.

So what we need to do is mock the Config, then trigger a config reload on the new mocked config in order to fill it with values. As all of the value set operations are not handled in the mock, they will be deferred to the class being mocked.

The reload can be triggered by overriding the `shouldReceive` method in the Config Facade:
```
public static function shouldReceive()
{
    $reloadConfig = false;
    if (!static::isMock()) {
        $reloadConfig = true;
    }
    $result = parent::shouldReceive();
    if ($reloadConfig) {
        static::$app->make(LoadConfiguration::class)->bootstrap(static::$app);
    }
    return $result;
}
```

Unfortunately, just mocking and then triggering a reload doesn't work, because `LoadConfiguration.php` doesn't use Service Containers to instantiate the Cache https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php#L32, rather, it directly instantiates the Illuminate\Config\Repository class. The result is that our mocked configuration doesn't work at all.

### The question

It appears to me as though the reason why the service container isn't used in `LoadConfiguration.php` is that the application isn't fully initialised at that point, and so it cannot use the service container.
My solution to this problem was to replace the following line in `LoadConfiguration.php`:
```
$app->instance('config', $config = $app->make(Repository::class, $items));
```
with:
```
if ($app->isBooted()) {
    $app->instance('config', $config = $app->make(Repository::class, $items));
} else {
    $app->instance('config', $config = new Repository($items));
}
```
While this covers this case, I feel as though it's kind of an ugly solution. I suppose that ideally we would just use the service container in both cases. Is it possible to force the loading of it at this point? Do you have any feedback on the details of this solution?

**Comment by GrahamCampbell** [comment]
We're open to PRs, but don't process proposal issues.
