### ISSUE TITLE
Capitalize translation placeholders

### ISSUE THREAD

**Issue by Propaganistas** [laravel/framework#11285]
Hi

The issue's title says it all, but let's provide an example:

Consider a validation error language line for 2 languages, for example English and Dutch:

```php
'accepted' => 'The :attribute must be accepted.', // English
'accepted' => ':attribute moet geaccepteerd zijn.', // Dutch
```

In Dutch, the `:attribute` placeholder is placed at the very beginning of the string. When validation fails for this rule, this would yield as output:

> English: The term must be accepted. 
> Dutch: term moet geaccepteerd zijn.

As like the English variant, the field name isn't capitalized in the Dutch line. However, since the field name is placed at the start, this yields undesirable aesthetics.

So how about introducing a capitalized placeholder that capitalizes its replacement?

Example:
```php
:attribute // would yield 'term'
:Attribute // would yield 'Term'
```

This way it's very easy for developers to have placeholders capitalized when needed...

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by anteriovieira** [comment]
:+1: very good

**Comment by andkom** [comment]
:+1:

**Comment by jvleusden** [comment]
+1

**Comment by AdenFraser** [comment]
This is definitely a good addition, useful for middle of sentence capitalisation in some languages such as German (where all all nouns are capitalized).

**Comment by GrahamCampbell** [comment]
Good. Closing though, since we don't process proposal issues. Feel free to talk to Taylor about it though, and/or send a PR.
