### ISSUE TITLE
supportedDrivers and availableDrivers both return dblib which is not supported

### ISSUE THREAD

**Issue by chelseau** [laravel/framework#11281]
supportedDrivers and availableDrivers return dblib as an available driver even though it is not (sqlsrv just uses dblib if available).

They should probably not return it, or the 2 switches in Connectors\ConnectionFactory should include an extra case for dblib, or some such thing.

**Comment by GrahamCampbell** [comment]
We're open to PRs. :)

**Comment by chelseau** [comment]
Sent a PR - https://github.com/laravel/framework/pull/11303

However, I think #11187 (my original pull request) makes more sense since it removes the repetition of the drivers and doesn't depend on Eloquent driver names mapping 1:1 with PDO drivers. I'm not sure why that one was rejected though -- too many changes or something to do with the implementation details? (@taylorotwell)

**Comment by taylorotwell** [comment]
A few too many changes. Hopefully what I put in is still helpful to you!

**Comment by chelseau** [comment]
Thought that might be it -- It is helpful! Only issue is dblib being returned :)
