### ISSUE TITLE
Laravel doesn't send cookies on error

### ISSUE THREAD

**Issue by andkom** [laravel/framework#11292]
If I set cookie and there was some error before response then, cookies aren't sent to browser.

the following examaple sets cookie as expected:
```php
Route::get('/test', function() 
    cookie()->queue('test', time());
});
```

no cookies are sent in this case:
```php
Route::get('/test', function() {
    cookie()->queue('test', time());
    throw new \Exception('some');
});
```

I am not sure if it's intended but native PHP code will work as expected:

```php
<?php

setcookie('test', time());

throw new \Exception('some')
```

**Comment by akalongman** [comment]
+1

**Comment by GrahamCampbell** [comment]
This is actually the expected behaviour, but, Taylor and I were talking about this just the other day, and a solution for 5.2 MIGHT be just around the corner.
