### ISSUE TITLE
Current Release Version Number

### ISSUE THREAD

**Issue by SachinAgarwal1337** [laravel/framework#11306]
I think by mistake the new release is given version number as 5.0.34 instead of 5.1.34

**Comment by GrahamCampbell** [comment]
No, there's not.

**Comment by GrahamCampbell** [comment]
That was an extra release on the 5.0.x line.

**Comment by GrahamCampbell** [comment]
The latest release on 5.1.x is v5.1.26, and for now, that's the latest 5.x too.

**Comment by SachinAgarwal1337** [comment]
@GrahamCampbell ok thank you clarification. :)

**Comment by GrahamCampbell** [comment]
NP. The next release will be v5.1.27. It's also possible that we will have a v5.2.0-beta1 (maybe beta2 and RC1, etc too) before the final v5.2.0.
