### ISSUE TITLE
ModelFactory.php - Naming Convention like Class but it is no class?

### ISSUE THREAD

**Issue by superdummy** [laravel/framework#11305]
This is an improvement Idea or at least thought, as laravel is highly based on  conventions (what I really appreciate): I was quite confused (also being quite new in PHP), that the `database\factories\ModelFactory.php` File is named as according Class-Conventions (CamelCase) but actually contains "only"

`$factory->define(App\User::class, function (Faker\Generator $faker) {  
    return [    
        'name' => $faker->name,    
        'email' => $faker->email,    
        'password' => bcrypt(str_random(10)),  
        'remember_token' => str_random(10),  
    ];  
});`

would maybe the naming "factory.php" might be more correct as filename?  

Background: For a newbie this is not easy to understand where the `$factory` variable magically appears. More clear to understand is for example the `routes.php` file with Facades like `Route::group()` so you know exactly the "callpath" and can easyly understand the logic/callpath. Maybe here something like `Faker::define()` would be more clear?

Thanks.

**Comment by GrahamCampbell** [comment]
There is no class in that file.

**Comment by GrahamCampbell** [comment]
So, we can name it what we like. ;)

**Comment by superdummy** [comment]
Yes you are correct its not a Class and as you stated/argumented it the other way round, please let me clarify what I mean:

I meant only name Classes CamelCase, everything else (config files, functional helpers) lowercase. And I think this is followed (what I really appreciate) everywhere I have encountered (like route files and configfiles) in the framework so far.  And the FactoryModel.php seems to be a configuration of a Model-Factory (but not a Model Factory itself!). So to be in line with for example route.php I think it would be more correctly named lowercase (factory.php).

Just want to prevent someone later writing "Laravel - A Fractal of Bad Design" if too many inconsistencies are introduced. 

But thanks for the answer, appreciate it. I only want to make larvel better.
