### ISSUE TITLE
proposal: fetch the previous url of the page in blade files

### ISSUE THREAD

**Issue by phecho** [laravel/framework#11319]
In order to fetch the previous url of the page in blade files easily, Is it necessary to add a function in Illuminate/Foundation/helpers.php? 
```php
if (! function_exists('previous')) {
    /**
     * Returns the previous.
     *
     * @return string
     */
    function previous()
    {
        return app('url')->previous();
    }
}
```
then  we can fetch the previous url in home.blade.php file
```html
<a href="{{ previous() }}" class="btn btn-default">Back</a>
```

**Comment by GrahamCampbell** [comment]
Looks ok to me. We don't process proposal issues though. The only way to find out if Taylor likes this to send a PR, or ask him directly.

**Comment by phecho** [comment]
@GrahamCampbell  @taylorotwell 
Thanks, I have sent the PR #11327.
