### ISSUE TITLE
ParseError in PHP 7 results in FatalThrowableError

### ISSUE THREAD

**Issue by TheShiftExchange** [laravel/framework#11329]
Running Laravel 5.1.26 on Homestead PHP7.0.0RC5 I got this error:

```
FatalThrowableError in FlattenException.php line 76:
Type error: Argument 1 passed to Symfony\Component\Debug\Exception\FlattenException::create() must be an instance of Exception, instance of ParseError given, called in /home/vagrant/www/ambulance/myshift/vendor/symfony/debug/Exception/FlattenException.php on line 98

in FlattenException.php line 76
at FlattenException::create(object(ParseError)) in FlattenException.php line 98
at FlattenException::create(object(ReflectionException)) in ExceptionHandler.php line 209
at ExceptionHandler->createResponse(object(ReflectionException)) in Handler.php line 155
at Handler->convertExceptionToResponse(object(ReflectionException)) in Handler.php line 98
at Handler->render(object(Request), object(ReflectionException)) in Handler.php line 55
at Handler->render(object(Request), object(ReflectionException)) in Kernel.php line 281
at Kernel->renderException(object(Request), object(ReflectionException)) in Kernel.php line 91
at Kernel->handle(object(Request)) in index.php line 53
```

I had a syntax error in my PHP code - but I couldnt work it out for ages (because the error message wasnt helpful). In my FormRequest object I had this:

```
return [
            'date' => 'required|string|date_format:d-m-Y'
            'area_list' => 'required|string|exists:area_staff_sheet_lists,id'
            'shift_type' => 'required|string|in:day,night,oncall'
        ];
```

Notice the missing 'commas' at the end of each row.

Looks like it is related to this - but it is already fixed? https://github.com/symfony/symfony/issues/15245

**Comment by GrahamCampbell** [comment]
This looks pretty impossible to me. ;?

**Comment by GrahamCampbell** [comment]
> at FlattenException::create(object(ReflectionException)) in ExceptionHandler.php line 209

Is this the exception handler in your own app?

**Comment by GrahamCampbell** [comment]
Is your exception handler custom?

**Comment by GrahamCampbell** [comment]
After some debugging, it;s clear that is a bug in Symfony's flatten exception class.

**Comment by GrahamCampbell** [comment]
See how it's recursively going through the previous exceptions: https://github.com/symfony/debug/blob/2.7/Exception/FlattenException.php#L98.

**Comment by GrahamCampbell** [comment]
It needs to only do that if the previous is actually an instance of Exception

**Comment by GrahamCampbell** [comment]
I'm going to send a PR to symfony for you.

**Comment by GrahamCampbell** [comment]
There we go: https://github.com/symfony/symfony/pull/17052.

Thanks for reporting,

**Comment by TheShiftExchange** [comment]
Thanks @GrahamCampbell

**Comment by pnoonan** [comment]
Getting a similar problem running 4.2 on php 7 with the Whoops file handler. I basically had to register a custom error handler that would log all Throwable types in order to get anything other than a Whoops error. 

Can this be addressed just by updating the Whoops dependency (looks like they have resolved this filp/whoops#352)?

**Comment by GrahamCampbell** [comment]
@pnoonan Sorry, but Laravel 4.2, and the related symfony version will never get fixed. You need to upgrade to Laravel 5.1.

> Can this be addressed just by updating the Whoops dependency (looks like they have resolved this filp/whoops#352)?

Sorry, it can't. That won't work.

**Comment by GrahamCampbell** [comment]
Laravel 5.1 is the first version of laravel to support php 7.0.

**Comment by GrahamCampbell** [comment]
@TheShiftExchange Symfony have merged and tagged my fix now btw. ;)

**Comment by eelkevdbos** [comment]
For anyone ending up on this thread. Laravel 4.2.20 is out and supports PHP7.
