### ISSUE TITLE
storage_path helper should escape spaces

### ISSUE THREAD

**Issue by snapey** [laravel/framework#11320]
Event class, `sendOutputTo()` using a path such as `storage_path('logs/backup.log')` on OSX local drive can end up with a full path like `/Volumes/Macintosh HD/webdev/projectname/storage/logs/backups.log`

The unescaped path in the folder name results in 'Too many arguments' error in /Volumes/Macintosh HD/webdev/projectname/vendor/symfony/console/Input/ArgvInput.php:177

The helper could avoid this issue by escaping any spaces found in the path.

**Comment by GrahamCampbell** [comment]
Breaking change, and I totally disagree anyway. It gives you the "storage path". It made no claims about the output being suitable to pass into the command line.

**Comment by GrahamCampbell** [comment]
> Event class, sendOutputTo()

However it does look like a bug in sendOutputTo. That function should be escaping the path you give it.

**Comment by GrahamCampbell** [comment]
Made a new issue for you: https://github.com/laravel/framework/issues/11321.
