### ISSUE TITLE
[suggestion] [5.2] Add units type to new generic rate limiter middleware 

### ISSUE THREAD

**Issue by a-moses** [laravel/framework#11336]
Hay

Maybe The new generic rate limiter middleware  should be also with unit type argument ? 
 to force developers  to do less mistakes ? :)
```php
Route::get('/somthing/{something',[ 'middleware' => 'rate:3,1,m'', function(){}
```

```php
Route::get('/somthing/{something',[ 'middleware' => 'rate:3,30,s'', function(){}
```
rate: request ,number of times  , unit type

**Comment by GrahamCampbell** [comment]
:-1: Very clunky IMO.

**Comment by a-moses** [comment]
Okay i tried ...
