### ISSUE TITLE
InteractsWithPages::see() does not accept regexes

### ISSUE THREAD

**Issue by carlosafonso** [laravel/framework#11347]
Hi,

I'm pretty sure there's a sensible reason for this, but the `see()` method in the `InteractsWithPages` trait does not allow custom regular expressions, as anything passed to it will be automatically escaped and converted to a regular expression of its own.

I like how fluent the `see()` method is when testing, but sometimes I'd like to be less restrictive when testing the presence of a string in a rendered view. Consider this example:

```php
public function testFooIsCreated()
{
    $this->doThis()
        ->doThat()
        ->see('/Foo with ID .* has been created/i');
}
```

I can test the above with `assertRegExp`, but I love the fluent syntax of Laravel's test helpers.

How about a new method (something like `seeRegex()`) or modifying `see()` to allow this? I can contribute with a PR if the maintainers find it appropriate.

Thank you.

**Comment by dwightwatson** [comment]
Even if it wasn't a full-blown regex it would be nice to be able to use `*` as a wildcard, and there is a precedence for this in the framework. For example, `\Illuminate\Support\Str::is()` will handle the asterisk in this manner.

**Comment by carlosafonso** [comment]
Yeah, I think that would cover the most common use cases.

**Comment by GrahamCampbell** [comment]
We're open to PRs, but don't process proposal issues.

**Comment by carlosafonso** [comment]
Sure. I wanted to know the maintainer's view on this first before submitting a PR. I see that @dwightwatson got there first though.

Thank you both.
