### ISSUE TITLE
Homestead PHP 7 not available through packagist for per project installations

### ISSUE THREAD

**Issue by citricsquid** [laravel/framework#11344]
[Per Project Installation](http://laravel.com/docs/5.1/homestead#per-project-installation) of Homestead depends on including Homestead as a dependency, however the php-7 branch of laravel/homestead isn't available through packagist, and because the branch doesn't [start with dev- we can't include it from the repository](https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository). As far as I can find the only option is to fork and rename the branch, which isn't ideal.

**Comment by GrahamCampbell** [comment]
I think you've misunderstood. `dev-` goes in front of the branch name to indicate you want a branch.

**Comment by GrahamCampbell** [comment]
The branch itself should not include `dev-` in the name.

**Comment by citricsquid** [comment]
@GrahamCampbell Ah, my brain completely misunderstood "Your custom branch name must be prefixed with "dev-"." in the composer documentation. Thanks for the fast response.
