### ISSUE TITLE
Open ajax request - security flaw

### ISSUE THREAD

**Issue by Kiszko** [laravel/framework#11352]
REDACTED

**Comment by GrahamCampbell** [comment]
Please email Taylor directly about this.

**Comment by Kiszko** [comment]
I understand, to you believe it too be legit? Man, now I have to rewrite all of that :(

**Comment by barryvdh** [comment]
If you want, I'll mail you a copy.

**Comment by Kiszko** [comment]
Thanks, vimisomagic@gmail.com

**Comment by crynobone** [comment]
Wouldn't the `remember_token` become invalid if the user explicitly logout, any session for that user would become invalid by then.

**Comment by Kiszko** [comment]
Try it.

**Comment by GrahamCampbell** [comment]
Are you using the file session driver by any chance? That has know issues and is not suitable for production use.

**Comment by Kiszko** [comment]
No in fact I am using redis.

**Comment by Kiszko** [comment]
Any news on this? I was able to recreate on a live setup. It does not matter which session driver is used.

I also tried wrapping the ajax route with a filter to block the laravel session headers:

```
Route::filter('no.session.cookie', function()
{
    Config::set('session.driver', 'array');
    Config::set('cookie.driver', 'array');
});
```

No dice.
