### ISSUE TITLE
belongsToMany $otherKey argument not functioning correctly?

### ISSUE THREAD

**Issue by llaski** [laravel/framework#11359]
Seems like the $otherKey argument is not functioning correctly in that under the hood the primary key is still getting used for the comparison vs. the key name that is passed in.

`BelongsToMany.php`

```
	protected function setWhere()
	{
		$foreign = $this->getForeignKey();

		$this->query->where($foreign, '=', $this->parent->getKey()); 

		return $this;
	}
```

Shouldn't `$this->parent->getKey()` be using the `$otherKey` if its available?

**Comment by GrahamCampbell** [comment]
Not 100% sure. Please send a PR so Taylor can review your proposed change.
