### ISSUE TITLE
Issue with error flashing and Log facade

### ISSUE THREAD

**Issue by ReactionJordan** [laravel/framework#11355]
This is an issue in the latest version of laravel and likely at least a few versions back as well (cannot confirm the exact version this came up).

Basically when using the `Log` facade it breaks any flash session that comes after it, making it not clear after the next request. To test this use a regular form and send data to another route , then use the following code in the controller function.

```
\Log::error('test');
return redirect()->route('test-form')->withErrors(['test']);
```

The flash message for the error should be persistent to clearing cache and refreshing, the only way to get rid of it is to dump sessions or overwrite it with another error.

I have taken a look into the log writer class however I cannot find anything that jumps out as causing this.

**Comment by GrahamCampbell** [comment]
Logging has nothing to do with sessions.

**Comment by GrahamCampbell** [comment]
I also can't replicate this.

**Comment by ReactionJordan** [comment]
Correct it doesn't so why this is happening is confusing me. Commenting out the log it works fine. Without it the flash message persists.

**Comment by ReactionJordan** [comment]
Ok based on more testing this happens at least between `5.1.20` to `5.1.26`
