### ISSUE TITLE
Error in unique form request validation with postgresql.

### ISSUE THREAD

**Issue by rdehnhardt** [laravel/framework#11362]
When I set up a unique key validation in postgresql using schemas, the request form returns the error below!

Validation
'email' => 'required|email|unique:schema.table'

Error
Database [schema] not configured.

How can I fix this?

Thanks!

**Comment by GrahamCampbell** [comment]
That's not the correct database name.

**Comment by GrahamCampbell** [comment]
Please use the connection name in your laravel config.

**Comment by rdehnhardt** [comment]
'pgsql' => [
            'driver' => 'pgsql',
            'host' => '999999',
            'database' => webstage,
            'username' => '999999',
            'password' => '999999',
            'charset' => 'utf8',
            'prefix' => '',
            'schema' => 'public',
            'port' => env('DB_POST', 5432)
        ],

And my model

protected $table = 'schema.table';

I have 8 schemas in my datadabe.

I did not understand how to solve it!

**Comment by GrahamCampbell** [comment]
Oh, I don't think we support dots in table names.

**Comment by GrahamCampbell** [comment]
Laravel's looking for `schema` where `pgsql` is defined.

**Comment by rdehnhardt** [comment]
like this?

'email' => 'required|email|unique:pgsql.schema.table' ?
