### ISSUE TITLE
Environment caching issue with multiple instances on the same server.

### ISSUE THREAD

**Issue by Buuntu** [laravel/framework#11363]
Basically I'm having issues with database settings in the Laravel environment files when multiple Laravel instances are running the same server.  It acts as if it caches one environment file and often uses it for both running instances (resulting in connection issues if they're different databases).  Here is the issue explained in a little more detail: http://stackoverflow.com/questions/32876066/weird-laravel-5-caching-using-wrong-database-name/33380770#33380770

I still haven't found a solution or why this is happening yet.  Any ideas?

**Comment by GrahamCampbell** [comment]
The issue is that you haven't run the config cache command.

**Comment by GrahamCampbell** [comment]
Once you do that, the "environment" is ignored by the config, and, from 5.2+, we don't even read the env file once a config cache is present.

**Comment by Buuntu** [comment]
I just ran those commands and I'm still getting the SQL connection issue.  It looks like it does work at first after running config cache but then it reverts to the same issue.

I should note that these are two APIs and I'm having the issue when one calls the other one.  Both are hosted on the same server running XAMPP.  Maybe this is an Apache issue, not a Laravel one?

**Comment by Buuntu** [comment]
I ran a composer update as well but should I try upgrading to 5.2?

**Comment by GrahamCampbell** [comment]
Upgrading to 5.2 is potentially non-trivial, and could have large consequences depending on which features you're using. L5.2 is also not quite ready yet, and could have more breaking changes to come.

**Comment by GrahamCampbell** [comment]
A simple composer update normally won't cut it for upgrading between Laravel minor versions. Treat them like semver Major versions.

**Comment by Buuntu** [comment]
Yeah, I'll just hard code the database configuration for now and not upgrade to 5.2.  It's a frustrating issue that I've had for a while and have run out of ideas to fix it.  I guess I could always include my own configuration file that is outside of version control?
