### ISSUE TITLE
Blade not ignoring HTML comments

### ISSUE THREAD

**Issue by ranieribt** [laravel/framework#11373]
Hi,

I'm building the basic quickstart app to try larevel...
When I've commented out the @include('common.errors'), with  to get a preview of the tasks.blade.php view, I've got the error "View [common.errors] not found.".
This only works when I remove the line...
I think this is an error, since it's a valid markup comment.

**Comment by rkgrep** [comment]
Blade has own comment tags: `{{--` and `--}}`
Html comments must not be hidden from output.

**Comment by GrahamCampbell** [comment]
That behaviour is correct. Your common.errors file is evaluated, and put inside the html comment tags.
