### ISSUE TITLE
problem with list concatenate 

### ISSUE THREAD

**Issue by tanviralamshawn** [laravel/framework#11371]
User::where('users.company_id', '=' ,$selected_company_id)
                        ->where('users.department_id', '=' ,$selected_department_id)
                        ->join('userlogs', 'userlogs.user_id', '=', 'users.id')
                        ->lists('firstname', 'lastname', 'id');

need to concatenate firstname and lastname for drop-down

**Comment by GrahamCampbell** [comment]
What exactly is the problem?

**Comment by tanviralamshawn** [comment]
->select(DB::raw('concat(firstname," ",lastname) as full_name,id'))

is not working

**Comment by tanviralamshawn** [comment]
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'concat(firstname,"' in 'field list'

SQL: SELECT `concat(firstname,"` AS `as` FROM `users` INNER JOIN `userlogs` ON `userlogs`.`user_id` = `users`.`id` WHERE `users`.`company_id` = ? AND `users`.`department_id` = ?

Bindings: array (
  0 => '33',
  1 => '63',
)

**Comment by GrahamCampbell** [comment]
That's not our code that's broken there. I'd recommend just concatenating it at the PHP side too.

**Comment by rkgrep** [comment]
You can also use `lists` or `pluck` on the resulting collection.
```
...->get([DB::raw('concat(firstname," ",lastname) as full_name'], 'id'))->lists('full_name', 'id');
```
