### ISSUE TITLE
Class 'XXXXX\Http\Controllers\finfo' not found

### ISSUE THREAD

**Issue by bsh314** [laravel/framework#11370]
```php
$file_info = new finfo(FILEINFO_MIME_TYPE);
$mime_type = $file_info->buffer(file_get_contents('http://www.columbia.edu/~dj114/excel-examples.xls'));
die($mime_type);
```
Using this code inside Laravel controller my app goes throw FatalErrorException, but using it in plain php file located at public dir it works fine and it gives:
```php
application/octet-stream
```
Same server, Same config, 2 diferent result. Framework is searching 'finfo' class in project, but instead it should use the default php pre-defined one.

I'm trying to validate file mime-type, extension & name before saving it. If there is no solution, someone can give me some other option, please.

Thanks for all the help.

**Comment by Sladewill** [comment]
Not an issue with php or laravel, your probably using namespaced code which means you need to import the class

```php
<?php

namespace Your\Namespace;

use finfo;
```

**Comment by rkgrep** [comment]
[Read about namespaces](http://php.net/manual/en/language.namespaces.rationale.php).

You should use a leading `\` if using a global class inside a namespace.
````
$file_info = new \finfo(FILEINFO_MIME_TYPE);
````

**Comment by GrahamCampbell** [comment]
You DO NOT need a leading slash. You just need to make sure that function is actually enabled on your server. PHP couldn't find it in the global scope or in the namespace, hense the somewhat missleading error.

**Comment by GrahamCampbell** [comment]
Oh, right, this is actually a class name. Your incorrect case misslead me.

**Comment by GrahamCampbell** [comment]
Either import it or put a leading slash, yes.

**Comment by bsh314** [comment]
That slash was one of my failed intents to get it working, so i'll edit  it now. Neither without slash it don't work.

**Comment by bsh314** [comment]
close this issue already, plz

**Comment by rust-x** [comment]
have the same issue

**Comment by MauriceKaluti** [comment]
> ```
> use finfo;
> ```



> Not an issue with php or laravel, your probably using namespaced code which means you need to import the class
> 
> ```
> <?php
> 
> namespace Your\Namespace;
> 
> use finfo;
> ```


use finfo; seems to be working fine with me when using the finfo function in laravel controller

**Comment by MauriceKaluti** [comment]
> use finfo; seems to be working fine with me when using the finfo function in laravel controller
> 
> ```
> <?php
> 
> namespace Your\Namespace;
> 
> use finfo;
> ```
