### ISSUE TITLE
Can't remove nullable in migration

### ISSUE THREAD

**Issue by andkom** [laravel/framework#11380]
I can add nullable flag to a column:
```php
    public function up()
    {
        Schema::table('table, function(Blueprint $table) {
            $table->integer('some')->nullable()->change();
        });
    }
```

but rollback won't work:

```php
    public function down()
    {
        Schema::table('table', function(Blueprint $table) {
            $table->integer('some')->change();
        });
    }
```

after rollback the column will be still nullable

**Comment by darthmaim** [comment]
You can use `nullable(false)` to remove nullable.

    public function down()
    {
        Schema::table('table', function(Blueprint $table) {
            $table->integer('some')->nullable(false)->change();
        });
    }

**Comment by andkom** [comment]
thanks

**Comment by zvermafia** [comment]
I'm getting error:

>[Illuminate\Database\QueryException]
SQLSTATE[22004]: Null value not allowed: 1138 Invalid use of NULL value (SQL: ALTER TABLE users CHANGE email email VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE password password VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci)

>[Doctrine\DBAL\Driver\PDOException]
SQLSTATE[22004]: Null value not allowed: 1138 Invalid use of NULL value

>[PDOException]
SQLSTATE[22004]: Null value not allowed: 1138 Invalid use of NULL value

My migration code:
```
// OK
public function up()
{
    Schema::table('users', function (Blueprint $table) {
        $table->string('email')->nullable()->change();
        $table->string('password')->nullable()->change();
    });
}

// Fail
public function down()
{
    Schema::table('users', function (Blueprint $table) {
        $table->string('email')->nullable(false)->change();
        $table->string('password')->nullable(false)->change();
    });
}
```

What's wrong?

**Comment by zvermafia** [comment]
`notNull()` gives the same error

**Comment by csmillie** [comment]
This error usually means there are NULL values in the table and the database cannot be altered until they are removed.
