### ISSUE TITLE
[5.1] [5.2] belongsToMany Buggy with Aliasing and Self Join

### ISSUE THREAD

**Issue by aleemb** [laravel/framework#11393]
I am trying to achieve the following

```
// Relationship
class Posts
{
    public function categories()
    {
        return $this->belongsToMany('\App\Models\Category', 'categories', 'post_id', 'id');
    }
}

```

Which results in

```
SELECT
  `categories`.*,
  `categories`.`post_id` as `pivot_post_id`,
  `categories`.`id` as `pivot_id`
FROM `categories`
INNER JOIN `categories`
  ON `id` = `categories`.`id`
WHERE `categories`.`post_id` = 123
```

Which raises an error `SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias` because of the self-join.

However, Laravel supports aliasing tables so I tried that,

```
class Posts
{
    public function categories()
    {
        return $this->belongsToMany('\App\Models\Category', 'categories as c2', 'post_id', 'id');
    }
}
```

which results in

```
SELECT
  `categories`.*,
  `categories`.`post_id` as `pivot_post_id`,
  `categories`.`id` as `pivot_id`
FROM `categories`
INNER JOIN `categories` as `c2`
  ON `categories`.`id` = `categories as c2`.`id`
WHERE `categories as c2`.`post_id` = 123
```

The last two lines are incorrect and should have `c2` instead of `categories as c2`.

**Comment by GrahamCampbell** [comment]
What Laravel version please?

**Comment by aleemb** [comment]
@GrahamCampbell 5.1.26

**Comment by taylorotwell** [comment]
Where is the self referencing relationship actually define. I only see a Post model referencing Categories, but your SQL example is categories referencing back into categories which I don't see in your model examples.

**Comment by aleemb** [comment]
This is how I had it setup and it was failing for me. I have added the relevant schema/columns on the table:

```
// Post: (id, foo)
class Post
{
    public function categories()
    {
        return $this->belongsToMany('\App\Models\Category', 'categories', 'post_id', 'id');
    }
}

// Category: (id, post_id, bar)
class Category {
    public static function post() {
        return $this->hasMany('\App\Models\Post', 'categories', 'post_id', 'id');
    }
}
```

I figured, if I added an alias in the table name it would work but it wasn't parsed correctly and the generated SQL was problematic.

Currently I am having to do it manually and I am not sure if this is the best approach:

```
public function categories()
{
    // Doesn't work
    // return $this->belongsToMany('\App\Models\Category', 'categories', 'post_id', 'id');

    // Doesn't work either
    // return $this->belongsToMany('\App\Models\Category', 'categories as c2', 'post_id', 'id');

    // A bit of a hack which works
    $relation = $this->belongsToMany('\App\Models\Category', 'categories as c2', 'post_id', 'id');
    unset($relation->getQuery()->getQuery()->joins);
    $relation->join('categories as c2', 'c2.id', '=', 'categories.id');
    return $relation;
}
```

Another approach is to not use `belongsToMany()` and instead use `hasMany()` which isn't ideal because it doesn't offer `sync()` and it executes multiple queries when calling `saveMany`.

The key difference in the schema above is that I don't have a `category_post` table and instead just have the `post_id` in the `category` table.

Category and Post are used as examples here. In my actual implementation things are a bit different which necessitates this schema.

**Comment by AdenFraser** [comment]
If what you are saying is true:
`The key difference in the schema above is that I don't have a category_post table and instead just have the post_id in the category table.`

Then your Category model shouldn't have a hasMany relation to post(), it would be a belongsTo?

**Comment by aleemb** [comment]
@AdenFraser you're right, it is actually `belongsTo` (my code was in flux when I wrote that here). I have corrected the typo in the post above. The bug still persists.

**Comment by aleemb** [comment]
On having considered this further, this relationship seems a bit unnatural and would break the order of things. The more appropriate thing to do is set this up as a `hasMany`.

However, it would be good to see a `sync()` style helper for `1:M` relations.
