### ISSUE TITLE
Blade HTML escaping bug

### ISSUE THREAD

**Issue by beyondlimits** [laravel/framework#11390]
HTML entities are not escaped.
Code: `{{ '&lt; >' }}`
Expected result: `&amp;lt; &gt;` (as htmlentities does)
Actual result: `&lt; &gt;`

**Comment by GrahamCampbell** [comment]
No, this is correct, we're actually calling `return htmlentities($value, ENT_QUOTES, 'UTF-8', false);`.

**Comment by beyondlimits** [comment]
What's the point of such partial escaping? I expected my strings to be escaped in such way that it is reliably displayed in browser. For now when I type `&lt &gt` into text field and get the valie back after page reload, it is `< >`.
