### ISSUE TITLE
[5.2] Throttles request and RateLimiter

### ISSUE THREAD

**Issue by lucasmichot** [laravel/framework#11399]
Introducing the RateLimiter to `5.2` is great, as within on project an API, frontend and backend will be perfectly handled.

But at the moment, I see 2 issues with `ThrottleRequests` and `RateLimiter`:

**First issue:**
Many API provide a throttling reset within one hour or some hours. But some API also set this reset period on a full month duration. At the moment, for instance, if I decide to allow 100 request for 1 hour, on the 101th request, next requests will be refused.
If I update this setting and decide to change the duration and the maxattempts, the requests will still be refused.
The only way to solve this is to flush the cache variable and we really DON'T WANT to lose track of the number of request remaining for the user, as this could be part of the pricing plan.

**Second issue:**
(RL for RateLimiter / TR for ThrottleRequests)
* First request : RL2 + TR3 => 5
* Next requests : RL2 + TR3 => 5
* Locking: RL4 => 4
* Locked : RL1 => 1

These are the number of hits (by "one hit" I mean either a read or write operation in cache).
* Locked is great - only one hit, super fast
* Locking happens only once, so it's not a big deal if there are 4 hits

But Next request and First request need 5 hits in the cache per request, on large application it can quickly become a performance issue.
I think the number of hits should be reduced.
The optimal situation would be: 
* First request : 2 (read + write)
* Next requests : 2 (read + write)
* Locking: 2 (read + write)
* Locked : 1 (read)

---

I feel like this piece of code should be optimized to match requirements and performance.

@taylorotwell @GrahamCampbell @crynobone @JosephSilber 
@jasonlewis
Your opinion is welcome ?

---

Note:
`cache->has` or `cache->put` count each for 1 hit, but `cache->add` counts for 2

**Comment by GrahamCampbell** [comment]
We're open to PRs, but don't process proposal issues. Feel free to discuss on slack though, of course.
