### ISSUE TITLE
[Homestead] PHP 7 Missing Readline Extension

### ISSUE THREAD

**Issue by jaesung2061** [laravel/framework#11402]
I'm not sure if this is the place to post this. I upgraded to Homestead 7. On Laravel 5.1.

In artisan tinker, when I press arrow keys, it's outputting a string instead of moving the cursor.

Left arrow key gives this: `^[[D`  
Right arrow key gives this: `^[[C`

**Comment by GrahamCampbell** [comment]
You need to install the readline extension.

**Comment by GrahamCampbell** [comment]
If you look in the suggested dependencies composer gives you on install, it'll be in that list.

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell Looks like this extension is missing from the default homestead install.

**Comment by GrahamCampbell** [comment]
Just renamed this issue to describe what's actually wrong here.

**Comment by jaesung2061** [comment]
Thanks. Also, as a note, this happens in Putty, not Git Bash.

**Comment by taylorotwell** [comment]
Fixed. Just need to upload the new boxes. Will do today or tomorrow.
