### ISSUE TITLE
FatalErrorException in ProviderRepository.php line 146: Class 'Illuminate\Routing\ControllerServiceProvider' not found

### ISSUE THREAD

**Issue by nonfu** [laravel/framework#11404]

**Comment by GrahamCampbell** [comment]
Indeed that class has been removed. Please remove your services.json/services.php files.

**Comment by GrahamCampbell** [comment]
Also, you you're using `~5.1` as a version constraint, I'd recommend changing it to `5.1.*`, because minor releases in Laravel are breaking.

**Comment by nonfu** [comment]
Ok, In fact, I'm now upgrading to 5.2.0 beta 1 from laravel 5.1.* and get this error, and finanlly I fix it by removing ControllerServiceProvider from config/app.php's providers array, thanks!

**Comment by GrahamCampbell** [comment]
You'll need to make these changes your your app: https://github.com/laravel/laravel/compare/master...develop.

**Comment by nonfu** [comment]
Ok，I've Got  It，Thank you!

**Comment by Ghafoorfahim** [comment]
I've done all these but still have this error!!

**Comment by trantuanckc** [comment]
:confounded:

**Comment by provectusblue** [comment]
command line: composer update

**Comment by ChettaDarkkill** [comment]
absolutely.
