### ISSUE TITLE
[Feature] Add Model::make(), which Intentionally doesn't Save

### ISSUE THREAD

**Issue by tylernathanreed** [laravel/framework#11409]
Currently there's two popular ways to make a new Model Instance:

    $model = new Model;

    $model->attribute1 = $value1;
    $model->attribute2 = $value2;
    ...
    $model->attributeN = $valueN;

And

    $model = Model::create([
        'attribute1' => $value1,
        'attribute2' => $value2, 
        ...
        'attribute3' => $value3
    ]);

The issue here is that I can create a Model using an array (Second Option), but the `create` method automatically saves. I know that we can use `Model::firstOrNew`, but I don't want to require a Database Lookup when I know that I'm creating a new Model.

I would like to be able to do this:

    $model = Model::make([
        'attribute1' => $value1,
        'attribute2' => $value2, 
        ...
        'attribute3' => $value3
    ]);

    $model->save();

I know it doesn't make sense when it's all in one code block, but if I wanted to pass in the Model to a function before it was saved, I would have to use the first option. With `Model::make()`, I could do this:

    class Having extends Model
    {
        public function things() { return $this->hasMany(Thing:class); }

        public function addThing(Thing $thing)
        {
            return $thing->having()->associate($this)->save();
        }
    }

    $thing = Thing::make([ ... ]); // having_id not known!
    $having = Having::create([ ... ]);

    $having->addThing($thing);

As you can see, this would be primarily for `belongsTo` relationships where the Belonging Model is created before the Having Model, or if the Belonging Model is created independently of the Having Model in some other function.

**Comment by brunogaspar** [comment]
Doesn't the below do what you need?

```php
$model = new Model([
    'attribute1' => $value1,
    'attribute2' => $value2, 
    'attribute3' => $value3,
]);
```

**Comment by tylernathanreed** [comment]
Found that out just a moment earlier. I tried to come back and erase my stupidity. Thanks for the reply.
