### ISSUE TITLE
Form Request Validation array attributes problem

### ISSUE THREAD

**Issue by dhiman252** [laravel/framework#11407]
Hi Team,

I am stuck with an issue described as follows:
Step 1: Create a form request like following with attributes defines as array:
<pre>
namespace App\Http\Requests\Auth;

use App\Http\Requests\Request;

class LoginRequest extends Request {
        
        public function __construct(){
            
            parent::__construct();
            
        }
        
        public function authorize(){
            
            return $this->isGuest === TRUE;
            
        }

	/**
	 * Get the validation rules that apply to the request.
	 *
	 * @return array
	 */
	public function rules()
	{
            return [
                'user[email]' => 'required', 
                'user[password]' => 'required',
            ];
	}

}
</pre>
Step 2: a simple login form 
<pre>

form method="post" action="{{ url('/user/login') }}">
  {!! csrf_field() !!}
  input type="email" class="form-control uname" name="user[email]" value="{{ old('user[email]') }}"
  input type="password" class="form-control pword" name="user[password]"
  input type="hidden" class="form-control pword" name="type" value="admin"
  button type="submit" class="btn btn-success btn-block">Subimit</button
/form

</pre>

Step3: Now try to submit this form and it will never get validated inspite of filling the values in the form.
The form requests never validate this.
 It never reaches to the controller action.

**Comment by GrahamCampbell** [comment]
Please ask on the forums.

**Comment by dhiman252** [comment]
Now we need to discuss issues on forums. great
