### ISSUE TITLE
MethodNotAllowedHttpException when using validates function in controller.

### ISSUE THREAD

**Issue by mirago** [laravel/framework#11403]
Hi,

I'm not sure what I'm doing wrong, could someone help me? 

I have a route 
```php
 Route::post('/api/v1/ticket', 'Api\TicketController@store');
```
and a controller with method store
```php
public function store(Request $request)
{
        $this->validate($request, [
            'from' => 'required',
            'subject' => 'required',
            'content' => 'required'
        ]);

        dd($request->all());
        $ticket = Ticket::create($request->all());
        return $ticket;
}
```
I'm using postman for testing this, however when I POST to http://project.app/api/v1/ticket
I get 
```
MethodNotAllowedHttpException in RouteCollection.php line 219:
```
I have tried to add headers with content type json etc. Nothing worked. I'm using laravel 5.1 please could someone help me to find out what I'm doing wrong? Also if I delete validation it seems to be working, however from the docs I can see that it should also be working with post requests...
Thanks

**Comment by mirago** [comment]
Why was this closed straight away with no explanation? Seems like a bug to me?

**Comment by GrahamCampbell** [comment]
Not a bug. Please ask on the forums.
