### ISSUE TITLE
[FormRequest] Custom validation message format

### ISSUE THREAD

**Issue by arcanedev-maroc** [laravel/framework#11411]
Hi artisans,

I was playing with the form requests and i found something missing with the validation message bag.

I want to format all validation messages with a specific format from my base Form Request, so i created a base request form like this:

```php
<?php namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;

abstract class Request extends FormRequest
{
    /**
     * The errors format.
     *
     * @var string
     */
    protected $errorsFormat;

    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return false;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    abstract public function rules();

    /**
     * {@inheritdoc}
     */
    protected function formatErrors(Validator $validator)
    {
        if (is_null($this->errorsFormat)) {
            return parent::formatErrors($validator);
        }

        $errors   = [];
        $messages = $validator->getMessageBag();

        foreach ($messages->keys() as $key) {
            $errors[$key] = $messages->get($key, $this->messageFormat);
        }

        return $errors;
    }
}
```

**My question is :** How can i change the **format** property of `Illuminate\Support\ViewErrorBag` (aka the `$errors` variable in views) from a Form Request.

**Comment by GrahamCampbell** [comment]
Yes, I suggest you just manually write the code to do that. Feel free to discuss on the forums.

**Comment by shahrukh4** [comment]
After the updation of laravel documentation, you don't need to override the response() anymore, all you have to do is, just write your bussiness logics inside the protected failedValidation() inside your custom FormRequest class like follows,

	    use Illuminate\Http\Exceptions\HttpResponseException;
	    use Illuminate\Contracts\Validation\Validator;

        /**
        * [failedValidation [Overriding the event validator for custom error response]]
        * @param  Validator $validator [description]
        * @return [object][object of various validation errors]
        */
    	public function failedValidation(Validator $validator) { 
		     //write your bussiness logic here otherwise it will give same old JSON response
        	throw new HttpResponseException(response()->json($validator->errors(), 422)); 
    	}
