### ISSUE TITLE
Undefined variable $errors

### ISSUE THREAD

**Issue by reshadman** [laravel/framework#11428]
In some requests the ```$errors``` varaible in my blade view is undefined.

My middleware stack is like below:
```php
    protected $middleware = [
        CheckForMaintenanceMode::class,
        EncryptCookies::class,
        AddQueuedCookiesToResponse::class,
        StartSession::class,
        ShareErrorsFromSession::class, // Error binder //
        RedirectsFirstPage::class,
        EtagCheck::class,
        ChecksEmailConfirmation::class,
        CheckBannedUsers::class
    ];
``` 
Docs mention that ```$errors``` variable are always bound.

Here is where I use the ```$errors``` variable:
```js
window.formErrors = JSON.parse('<?php echo json_encode((object) $errors->toArray()); ?>');
```

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/blob/5.2/src/Illuminate/View/Middleware/ShareErrorsFromSession.php

**Comment by GrahamCampbell** [comment]
It is always bound, but only if no exception is thrown before that code is executed.
