### ISSUE TITLE
[5.2] Eloquent paginate does not work

### ISSUE THREAD

**Issue by programmator** [laravel/framework#11432]
Paginate ignores the limit set and returns all items.

```
Project::with('user')->paginate(20);
```
Build queries:

```
select count(*) as aggregate from `projects` where `projects`.`deleted_at` is null
select * from `projects` where `projects`.`deleted_at` is null
```
There are no problems with simplePaginate:

```
Project::with('user')->simplePaginate(20);
```

```
select * from `projects` where `projects`.`deleted_at` is null limit 21 offset 0
```

**Comment by Prashank25** [comment]
I think that query is just to count the total number of rows to build the number of pages. There should be another one that retrieves the rows with a limit clause.

**Comment by GrahamCampbell** [comment]
Is this broken on 5.1 too? If so, the fix MUST go to 5.1.

**Comment by programmator** [comment]
@Prashank25 I pointed on two queries.
@GrahamCampbell No in 5.1 no problems.

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell. Was this change intentional?\

**Comment by Prashank25** [comment]
@programmator oops, my bad.

**Comment by taylorotwell** [comment]
Fixed.
