### ISSUE TITLE
Route::group does not work with a namespaces outside App/Http/Controllers

### ISSUE THREAD

**Issue by mathiasgrimm** [laravel/framework#11444]
I have a controller that resides outside the App/Http/Controllers folder and it does not work when using groups.

This first case works just fine:

<pre>
Route::get('m', '\Mathias\Controller@test');
</pre>

but if it is within a group, it does not:

<pre>
Route::group([
    'prefix'     => 'mathias',
    'namespace'  => '\Mathias'
], function () {
   Route::get('m', 'Controller@test');
});
</pre>

This is what I get for the second case:
Class App\\Http\\Controllers\\Mathias\\Controller does not exist

I am not sure whether this is a bug or not but I have been recommended to implement this: 
https://laracasts.com/discuss/channels/general-discussion/registering-a-controller-outside-from-the-controllers-folder 
which I think is out of question as I would have to change all other routes. I rather fix the ones on that group that is failing.

**Comment by ollieread** [comment]
You can configure the 'default' namespace in `App\Providers\RouteServiceProvider::$namespace`.

You have several choices for how to get around this, either remove the need for that namespace or use a separate file for the routes. This is an example `RouteServiceProvider::map()`.

    public function map(Router $router)
    {
        $router->group(['namespace' => $this->namespace], function ($router) {
            /** @noinspection PhpIncludeInspection */
            require app_path('Http/routes.php');
        });

        $router->group(['prefix' => '/admin'], function ($router) {
            /** @noinspection PhpIncludeInspection */
            require app_path('Http/admin.php');
        });
    }

The first route group uses the value set in `$this->namespace` where as the second uses none.
