### ISSUE TITLE
[5.1] OrderBy with -

### ISSUE THREAD

**Issue by set0x** [laravel/framework#11445]
When I try to do this with "orderBy" return me a error saying that column doesnt't exist, it´s possible do this without "orderbyRaw".

- This return error.
`$(....)->orderBy('-`order`',  'DESC')->get();`

- This run pefect.
`$(....)->orderByRaw('-`order` DESC')->get();`

**Comment by GrahamCampbell** [comment]
The direction needs to be lowercase.

**Comment by GrahamCampbell** [comment]
desc
