### ISSUE TITLE
[5.2] random_bytes() issue

### ISSUE THREAD

**Issue by daison12006013** [laravel/framework#11448]
refer to this: https://github.com/laravel/framework/pull/8699 @GrahamCampbell requests to use PHP7 function

Well based on the documentation it should support up to >= 5.5.9 for Laravel5.2, however **random_bytes()** is a PHP7 function while upgrading from L5.1 to L5.2, I'm getting a lot of errors now regarding this class **Str::random()**. 

While before we have the if-elseif to check if random_bytes() exists, but now https://github.com/laravel/framework/blob/5.2/src/Illuminate/Support/Str.php#L233

or the Documentation itself is not updated yet?

if this is the case then, we should also change the composer.json require section to use PHP7 instead of >= 5.5.9, but I have no idea if this is essential while there is a code that requires to use PHP7

**Comment by crynobone** [comment]
We're loading a `random_bytes()` polyfill when loading the whole framework. You can check the composer.json to find out.

**Comment by crynobone** [comment]
You shouldn't be seeing any error if you're loading the whole framework. However if you're seeing this when developing packages (or using `illuminate/support`) outside of Laravel app (you should have mention this in your issue!) then you need to include the polyfill in your project `composer.json`.

https://github.com/illuminate/support/blob/master/composer.json#L38

```
"paragonie/random_compat": "Provides a compatible interface like PHP7's random_bytes() in PHP 5 projects (~1.1).",
```

**Comment by daison12006013** [comment]
@crynobone, you're correct, I was trying to upgrade my 5.1 project to 5.2 based on the upgrade guideline, I might missed something as I can't see any polyfill repository in the upgrade guide, while checking the 5.2 there is the symfony/polyfill-56, inwhich I forgot to include as well.

Anyway, thanks.

**Comment by GrahamCampbell** [comment]
You DO NOT need to add this dependency to your project.

**Comment by GrahamCampbell** [comment]
laravel/framework deals with that for you.

**Comment by iWedmak** [comment]
i have this problem.
lib paragonie/random_compat is gets me an error like is_readable(): open_basedir restriction in effect. File(/dev/urandom) 
open base dir is working, its an security issue )
sooo i cant realy work... what to do?
