### ISSUE TITLE
[5.2] Input Class Not Found?

### ISSUE THREAD

**Issue by masterpowers** [laravel/framework#11442]
Ive Checked the Documentation, there is no Update Around this
That Input Facade is Already Not Included Upon Installing Laravel 5.2
Got Also My App From 5.1 Breaking Issue With This?
I Add this in my config/app.php
```
'Input'     => Illuminate\Support\Facades\Input::class,
```
Hope you also Add this In the Laravel 5.2 Documentation :)

**Comment by GrahamCampbell** [comment]
Just use the `Request` facade.

**Comment by GrahamCampbell** [comment]
Laravel 5.2 is NOT ready for use yet. The docs are not complete yet.

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell. This does need adding to the docs though. ;)
