### ISSUE TITLE
[5.1][5.2] Error "Missing argument 1 for Illuminate\Auth\AuthManager::createDriver()" after update to 5.2 - problem with auth.php file?

### ISSUE THREAD

**Issue by szymonides** [laravel/framework#11454]
I've just updated Laravel from 5.1 to 5.2. I did it with this instructions: http://laravel.com/docs/5.2/upgrade#upgrade-5.2.0

I've changed /config/auth.php file to this https://github.com/laravel/laravel/blob/develop/config/auth.php. But then I saw the error message: 
> Missing argument 1 for Illuminate\Auth\AuthManager::createDriver(), called in /home/vagrant/Code/edumood/vendor/laravel/framework/src/Illuminate/Support/Manager.php on line 87 and defined

I've noticed that in \Illuminate\Auth\AuthManager.php file there are references to /config/auth.php file:
```php
return $this->app['config']['auth.driver'];
```

```php
$model = $this->app['config']['auth.model'];
```

```php
$table = $this->app['config']['auth.table'];
```

```php
$this->app['config']['auth.driver'] = $name;
```

So, in array in /config/auth.php should be this elements: __table__, __driver__ and __model__.
I added this elements, and after that my application started to work properly.

There is a bug or I've done something wrong with updating?

**Comment by GrahamCampbell** [comment]
Not a bug. Please ask on the fourms.

**Comment by bobbybouwmann** [comment]
I have the same issue, not sure what it could be? I added all the config I need like the OP said, but it's still not working here...
```
// config/auth.php

'providers' => [
    'users' => [
        'driver' => 'eloquent',
        'model' => App\User::class,
        'table' => 'users',
    ],
],
```

**Comment by Luddinus** [comment]
Same here, it works if you add

'driver' => 'eloquent'

in the auth.php file...

**Comment by sainhale** [comment]
same here still looking

**Comment by orrd** [comment]
I was getting the same error and it turned out I hadn't actually upgraded to 5.2 (I updated my composer.json but forgot that I hadn't actually run "composer update" on one of the several sites I had updated that day). You can use artisan to check your Laravel version.
