### ISSUE TITLE
utf8mb4 charset using the mysql error

### ISSUE THREAD

**Issue by goudiao** [laravel/framework#11451]
“php artisan migrate ”   Unable to create a database
charset: utf8mb4
==========================
 SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `users` add unique `users_email_unique`(`email`))

**Comment by GrahamCampbell** [comment]
Please ask on the forums.

**Comment by joelcuevas** [comment]
MAybe this will help:

**Comment by joelcuevas** [comment]
Maybe this will help:

https://github.com/laravel/framework/issues/2823#issuecomment-172971309

Basically, reduce the email field length to 191 chars and hope nobody needs the extra 64 chars for his super dooper long email address.

**Comment by ossar** [comment]
Can I use barracuda file system?

my.cnf

    [mysqld]
    innodb_large_prefix
    innodb_file_format=BARRACUDA
    innodb_file_per_table

config/database.php

    'engine' => 'InnoDB ROW_FORMAT=COMPRESSED',
