### ISSUE TITLE
[5.2] Undefined variable: errors

### ISSUE THREAD

**Issue by PheRum** [laravel/framework#11457]
http://laravel.com/docs/master/validation
```
<!-- /resources/views/post/create.blade.php -->

<h1>Create Post</h1>

@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<!-- Create Post Form -->
```

```
ErrorException in 146820125ca4b230f9c1f73ff3a4495c08e4d193.php line 75: 
Undefined variable: errors 
(View: /Users/PheRum/Sites/laravel.local/resources/views/layouts/app.blade.php) 
(View: /Users/PheRum/Sites/laravel.local/resources/views/layouts/app.blade.php)
```

**Comment by PheRum** [comment]
this decision will be normal or corrected the laravel?
```
@if ($errors->all())
		<div class="alert alert-danger">
			<ul>
				@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
				@endforeach
			</ul>
		</div>
		@endif
```

**Comment by GrahamCampbell** [comment]
You probably forgot to pass through the errors. Please ask on the forums

**Comment by bendo01** [comment]
i'm using form request validation, and if read docs
http://laravel.com/docs/5.2/validation
it said :
So, it is important to note that an $errors variable will always be available in all of your views on every request, allowing you to conveniently assume the $errors variable is always defined and can be safely used
and after i upgrade to 5.2 I've got same error notification
Undefined variable: errors, is it possible that $errors variable is not always available?

**Comment by arthurkirkosa** [comment]
You must group all your routes under a group with the 'web' middleware applied. That attaches the \Illuminate\View\Middleware\ShareErrorsFromSession::class middleware; or add this to the global middleware (but that's not wise if you have stateless APIs)

**Comment by bendo01** [comment]
@arthurkirkosa thank you for your suggestion :)

**Comment by PheRum** [comment]
that's a temporary solution until you correct the error in laravel 5.2

**/app/Http/Kernel.php**
```php
class Kernel extends HttpKernel
{
    /**
     * The application's global HTTP middleware stack.
     *
     * These middleware are run during every request to your application.
     *
     * @var array
     */
    protected $middleware = [
        CheckForMaintenanceMode::class,
        //
        EncryptCookies::class,
        AddQueuedCookiesToResponse::class,
        StartSession::class,
        ShareErrorsFromSession::class,
        VerifyCsrfToken::class,
    ];

    /**
     * The application's route middleware groups.
     *
     * @var array
     */
    protected $middlewareGroups = [
        'web' => [
            //
        ],

        'api' => [
            'throttle:60,1',
        ],
    ];
```

**Comment by GrahamCampbell** [comment]
That's not a workaround. That's just incorrect.

**Comment by GrahamCampbell** [comment]
There is no error.

**Comment by PheRum** [comment]
@GrahamCampbell try it yourself))

in **app.blade.php**

```
@include('errors.list')
```
**errors/list.blade.php**
```
@if ($errors->any())
	<div class="row">
		<div class="col-xs-12">
			<div class="alert alert-danger alert-alt">
				<strong><i class="fa fa-bug fa-fw"></i> Ошибка</strong><br>
				<ul>
					@foreach ($errors->all() as $error)
						<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div>
		</div>
	</div>
	<br/>
@endif
```

then go to a nonexistent page http://laravel.local/get-me-bug

**Response:**
```
Undefined variable: errors 
(View: /Users/PheRum/Sites/lored.local/resources/views/errors/list.blade.php)
```

**Comment by arthurkirkosa** [comment]
@PheRum https://github.com/laravel/laravel/blob/master/app/Http/routes.php#L29-L31

**Comment by PheRum** [comment]
@arthurkirkosa a non-existent page is not related to the router

**Comment by GrahamCampbell** [comment]
It DOES work. You MUST be on a page that's loaded from inside the web middleware group.

**Comment by PheRum** [comment]
This is understandable, but it is possible transitions to non-existent pages, in such a case, the error will be played.
so this is a bug laravel 5.2

**Comment by GrahamCampbell** [comment]
No, it's not. It was never intended to work as you say.

**Comment by taylorotwell** [comment]
Can you describe why this view is loaded on a non-existent page? Do you render a custom error page for 404s and include this or something?

**Comment by taylorotwell** [comment]
If so, my suggestion is to do `isset($errors)` in your check.

**Comment by PheRum** [comment]
@taylorotwell like this works as expected. Many thanks :)
P.S. Correct here https://github.com/laravel/docs/blame/5.1/validation.md#L128
```
@if (isset($errors) && $errors->any())
```

**Comment by alesmana** [comment]
After generating make:auth, I see Route::auth() was outside 'web' group.
As Graham mentioned, once I put inside Route group 'web', the $errors msg is gone

    Route::group(['middleware' => 'web'], function () {
      Route::auth(); // must be inside 'web'
      Route::get('/home', 'HomeController@index');
    });

**Comment by canhphong** [comment]
`@extends('master')
@section('content')
    <div class="fullwidthbanner-container">
        <div class="fullwidthbanner">
            <div class="bannercontainer">
                <div class="banner">
                    <ul>
                        
                        @foreach($slide as $sl)
                            <li data-transition="boxfade" data-slotamount="20" class="active-revslide"
                                style="width: 100%; height: 100%; overflow: hidden; z-index: 18; visibility: hidden; opacity: 0;">
                                <div class="slotholder" style="width:100%;height:100%;" data-duration="undefined"
                                     data-zoomstart="undefined" data-zoomend="undefined" data-rotationstart="undefined"
                                     data-rotationend="undefined" data-ease="undefined" data-bgpositionend="undefined"
                                     data-bgposition="undefined" data-kenburns="undefined" data-easeme="undefined"
                                     data-bgfit="undefined" data-bgfitend="undefined" data-owidth="undefined"
                                     data-oheight="undefined">
                                    <div class="tp-bgimg defaultimg" data-lazyload="undefined" data-bgfit="cover"
                                         data-bgposition="center center" data-bgrepeat="no-repeat"
                                         data-lazydone="undefined"
                                         src="source/image/slide/{{$sl->image}}"
                                         data-src="source/image/slide/{{$sl->image}}"
                                         style="background-color: rgba(0, 0, 0, 0); background-repeat: no-repeat; background-image: url('source/image/slide/{{$sl->image}}'); background-size: cover; background-position: center center; width: 100%; height: 100%; opacity: 1; visibility: inherit;">
                                    </div>
                                </div>
                            </li>
                        @endforeach

                    </ul>
                </div>
            </div>

            <div class="tp-bannertimer"></div>
        </div>
    </div>
    
    </div>
    <div class="container">
        <div id="content" class="space-top-none">
            <div class="main-content">
                <div class="space60">&nbsp;</div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="beta-products-list">
                            <h4>Sản phẩm mới</h4>
                            <div class="beta-products-details">
                                <p class="pull-left">Tìm thấy {{count($new_product)}} sản phẩm</p>
                                <div class="clearfix"></div>
                            </div>

                            <div class="row">
                                @foreach($new_product as $new)
                                    <div class="col-sm-3">
                                        <div class="single-item">
                                            @if($new->promotion_price!=0)
                                                <div class="ribbon-wrapper">
                                                    <div class="ribbon sale">Sale</div>
                                                </div>
                                            @endif
                                            <div class="single-item-header">
                                                <a href="{{route('chitietsanpham', $new->id)}}"><img
                                                            src="source/image/product/{{$new->image}}"
                                                            alt=""></a>
                                            </div>
                                            <div class="single-item-body">
                                                <p class="single-item-title">{{$new->name}}</p>
                                                <p class="single-item-price">
                                                    @if($new->promotion_price == 0)
                                                        <span class="flash-sale">{{number_format($new->unit_price)}} đồng</span>
                                                    @else
                                                        <span class="flash-del">{{number_format($new->unit_price)}} đồng</span>
                                                        <span class="flash-sale">{{number_format($new->promotion_price)}} đồng</span>
                                                    @endif
                                                </p>
                                            </div>
                                            <div class="single-item-caption">
                                                <a class="add-to-cart pull-left" href="{{route('themgiohang',$new->id)}}"><i
                                                            class="fa fa-shopping-cart"></i></a>
                                                <a class="beta-btn primary" href="{{route('chitietsanpham', $new->id)}}">Details <i
                                                            class="fa fa-chevron-right"></i></a>
                                                <div class="clearfix"></div>
                                            </div>
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                            <div class="row">{{$new_product->links()}}</div>
                        </div> 


                        <div class="space50">&nbsp;</div>

                        <div class="beta-products-list">
                            <h4>Sản phẩm khuyến mãi</h4>
                            <div class="beta-products-details">
                                <p class="pull-left">Tìm thấy {{count($sanpham_khuyenmai)}} sản phẩm</p>
                                <div class="clearfix"></div>
                            </div>

                            <div class="row">
                                @foreach($sanpham_khuyenmai as $spkm)
                                <div class="col-sm-3">
                                    <div class="single-item">
                                        <div class="single-item-header">
                                            <a href="{{route('chitietsanpham', $spkm->id)}}"><img src="source/image/product/{{$spkm->image}}" alt="" height="250px"></a>
                                        </div>
                                        <div class="single-item-body">
                                            <p class="single-item-title">{{$spkm->name}}</p>
                                            <p class="single-item-price">
                                                <span class="flash-del">{{number_format($spkm->promotion_price)}} đồng</span>
                                                <span class="flash-sale">{{number_format($spkm->unit_price)}} đồng</span>
                                            </p>
                                        </div>
                                        <div class="single-item-caption">
                                            <a class="add-to-cart pull-left" href="{{route('themgiohang', $new->id)}}"><i
                                                        class="fa fa-shopping-cart"></i></a>
                                            <a class="beta-btn primary" href="{{route('chitietsanpham', $spkm->id)}}">Chi tiết <i
                                                        class="fa fa-chevron-right"></i></a>
                                            <div class="clearfix"></div>
                                        </div>
                                    </div>
                                </div>
                                @endforeach
                            </div>
                        </div> 
                        <div class="row">{{$sanpham_khuyenmai->links()}}</div>
                    </div>
                </div> 


            </div> 
        </div> 
@endsection`
