### ISSUE TITLE
loginPath() removed, not in upgrade guide for 5.2

### ISSUE THREAD

**Issue by Sheby** [laravel/framework#11459]
Not sure if this is a right place to put this.
But it would be nice if this 

https://github.com/laravel/framework/commit/4326dc07d8d96161fdc18d0d5859928c395819ad

was mentioned in the upgrade guide, because it may break some functionality on existing projects.

**Comment by GrahamCampbell** [comment]
Feel free to send a PR to the 5.2 branch of the docs.
