### ISSUE TITLE
Model ID is 0 after inserting when primary key is not autoincrementing

### ISSUE THREAD

**Issue by carlosafonso** [laravel/framework#11467]
Hi,

I came across the following in Laravel 5.1. Here's a dummy model:

```php
// model
class Foo extends Model
{
	protected $fillable = ['id'];
	public $timestamps = false;
}

// schema builder statement
Schema::create('foos', function(Blueprint $table) {
    $table->integer('id')->unsigned()->primary();
});
```

As you can see, the primary key is not an autoincrementing field.

I have a controller method which does this:

```php
public function doStuff()
{
    $foo = \App\Foo::create(['id' => 123]);
    dd($foo->id);   // <-- HERE
}
```

I would expect the `dd()` call to print `123`, but `0` is shown. However, the model is correctly inserted with `123` as the value.

This causes trouble if Foo had many Bars, and I was to extend the previous function into something like this:

```php
public function doStuff()
{
    $foo = \App\Foo::create(['id' => 123]);
    $foo->bars()->create(['param' => 'value']);
}
```

The insertion of the related Bar fails with a foreign key error because Laravel attempts to reference a `Foo` with ID 0, which does not exist.

**Comment by GrahamCampbell** [comment]
No bug. You need to set the incrementing property to false.

**Comment by carlosafonso** [comment]
Sorry about that, wasn't aware of such attribute.
