### ISSUE TITLE
[homestead][v0.4.0] After update to php7 vagrant box not working

### ISSUE THREAD

**Issue by galimru** [laravel/framework#11468]
Site in vagrant box not working correctly.
It's happens because in /etc/nginx/sites-available/site.name wrong path to php-fpm socket.

Need replace:
```
/var/run/php5-fpm.sock
```
on
```
/var/run/php/php7.0-fpm.sock
```

**Comment by JeroenVanOort** [comment]
Have you tried provisioning the box? It should regenerate the nginx config.

**Comment by galimru** [comment]
No. I just add vagrant box from atlas.

**Comment by GrahamCampbell** [comment]
Can't replicate.
