### ISSUE TITLE
[5.2] url helper breaks when no path set

### ISSUE THREAD

**Issue by DougSisk** [laravel/framework#11477]
When using the `url()` helper and the `$path` is not set, a `UrlGenerator` class is returned. Previously, not setting the path would spit out a string containing the root url (http://laravel.com). This is a major breaking change.

Commit with the breaking change: e970dacf4ce0c72e5a920cf763586a1be2c52500

**Comment by GrahamCampbell** [comment]
This is a major breaking change, that is correct. That's why it was made to L5.2 and not L5.1.

**Comment by DougSisk** [comment]
But it is not documented.

**Comment by GrahamCampbell** [comment]
Laravel does not follow semver. Treat minor releases as semver major releases.

**Comment by GrahamCampbell** [comment]
> But it is not documented.

We're open to PRs. ;)

**Comment by DougSisk** [comment]
I will submit a PR to the docs later tonight
