### ISSUE TITLE
[5.2] Laravel auto casts ID key to integer.

### ISSUE THREAD

**Issue by ddctd143** [laravel/framework#11484]
From Laravel 5.2 there is new method in Model.php which autocasts primary key to integer.

```
    /**
     * Get the casts array.
     *
     * @return array
     */
    protected function getCasts()
    {
        if ($this->incrementing) {
            return array_merge([
                $this->getKeyName() => 'int',
            ], $this->casts);
        }

        return $this->casts;
    }
```

If textual primary keys are used, they also will be casted to integers and will result in "0" when trying to get them.

At example countries table which has ISO country chars as primary keys
id => LV
name => Latvia

will result in casting ID as 0.

I have found solution to bypass this, if adding variable in your model 
```
class MyModel extends Illuminate\Database\Eloquent\Model
{
    public $incrementing = false;
}
```

But I think that this is breaking change, and if this is normal behavior then this should be added to upgrade guide.

**Comment by GrahamCampbell** [comment]
We'd accept a PR to document this.

**Comment by jarnovanleeuwen** [comment]
+1

**Comment by phanan** [comment]
Or you can just explicitly cast the PK to string, just saying.

**Comment by isometriq** [comment]
default and automatic casting using `DB::getDoctrineSchemaManager`
https://gist.github.com/isometriq/b947e940913ecdc984e767ad4ba3d06a

**Comment by maitandat1507** [comment]
But I see when you using another Model, and wanna join to the table has customized `id` field, it still return to integer again even if you using abow solution.

Solution for this issue is simple way, ALIAS `id` field to another name when you select, like:
`Foo::select('bar.id as id_bar')->join('bar', 'foo.id_bar', '=', 'bar.id')->get()`
