### ISSUE TITLE
[Laravel 5.2] csrf_token() don't generate anything

### ISSUE THREAD

**Issue by kocoten1992** [laravel/framework#11487]
I'm on fresh install of laravel 5.2

csrf_token() is just blank.

**Comment by danharper** [comment]
On a fresh install, make sure your route is within `web` middleware group 

```php
<?php

Route::get('foo', function () {
    return csrf_token(); // null
});

Route::group(['middleware' => 'web'], function () {
    Route::get('bar', function () {
        return csrf_token(); // works
    });
});
```

Otherwise the `StartSession` middleware [isn't loaded](https://github.com/laravel/laravel/blob/master/app/Http/Kernel.php#L29) and so no token exists on the session.

**Comment by kocoten1992** [comment]
:+1:
