### ISSUE TITLE
Bug? "Can't swap PDO instance while within transaction."

### ISSUE THREAD

**Issue by punchi** [laravel/framework#11480]
Sorry, Laravel is fine, problem with codeception (https://github.com/Codeception/Codeception/issues/2659), can't delete this post =/
-------------------
I have a nested transaction with \DB::beginTransaction();

When executing a test with Codeception, this error is returned:

  [RuntimeException]
  Can't swap PDO instance while within transaction.

And on https://github.com/illuminate/database/blob/master/Connection.php is

```
if ($this->transactions >= 1) {
    throw new RuntimeException("Can't swap PDO instance while within transaction.");
}
```

So, if nested transaction are supported, why it limits to >= 1?

**Comment by GrahamCampbell** [comment]
No problem. ;)

**Comment by felipemarques** [comment]
This problem occurred with me too... some anymore have this problem ?

**Comment by punchi** [comment]
Hola Felipe! make sure in the code you'r closing all the possible ways, I (barely however) remember that was my problem.
