### ISSUE TITLE
[5.2] Command::setLaravel type hint

### ISSUE THREAD

**Issue by CupOfTea696** [laravel/framework#11488]
I just noticed that the type hint in `Command::setLaravel` ([Illuminate/Console/Command.php#L497](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Console/Command.php#L497)) was removed. Is this intentional or a bug?

**Comment by GrahamCampbell** [comment]
I think it was to allow people to shove in arrays and such for testing purposes. I don't really like the change myself, but I don't "hate" it.

**Comment by CupOfTea696** [comment]
Just checking if it was intended :)

**Comment by GrahamCampbell** [comment]
If it were upto me, I'd typehint all the things. ;)
