### ISSUE TITLE
[5.1] [5.2] In Schema Builder

### ISSUE THREAD

**Issue by pjebs** [laravel/framework#11481]
In SchemaBuilder (L5.1),
$table->timestamp('expires')

This sets an invalid default value in Mysql.
I suspect timestamps() also sets an invalid default value.

**Comment by GrahamCampbell** [comment]
Any chance of a PR to fix please? Or, even just a couple of failing test cases.

**Comment by thecrypticace** [comment]
This has to do with MySQL 5.7 being configured to not allow zero dates by default. There's a `useCurrent()` method you can use to set the default value of the field to `CURRENT_TIMESTAMP`. It does not work with `timestamps()` as that method returns void. This workaround does not seem to be covered in the L5.1 documentation.

Try this:
```php
$table->timestamp("expires")->useCurrent();
```

If you're replacing a call to `timestamps()` then you can use this:
```php
$table->timestamp("created_at")->useCurrent();
$table->timestamp("updated_at")->useCurrent();
```

**Comment by GrahamCampbell** [comment]
Thanks @thecrypticace.
