### ISSUE TITLE
[5.1] Eloquent with sqlsrv connection can't use Table-valued Functions as Table

### ISSUE THREAD

**Issue by Murtnowski** [laravel/framework#11493]
When creating a model that extends Eloquent and has a connection using the sqlsrv driver, if you set the table property to be a MSSQL table-value function it can't run any queries because it wraps the function in square brackets and crahes with "SQLSTATE[HY000]: General error: 208 General SQL Server error: Check messages from the SQL Server"

Meaning if set the table property to 

myTableValueFunction()

the query that runs later uses

...from [myTableValueFunction()]

If the query was instead 

...from \[myTableValueFunction]()

then it would work.  Even

...from myTableValueFunction()

would work.

**Comment by GrahamCampbell** [comment]
We're open to PRs.

**Comment by rodrigopedra** [comment]
@Murtnowski do you expect to pass bindings to the table valued function in the from clause?

for example :

~~~php
\DB::table('myTableValueFunction(?,?)', [1,2])->get();
~~~

That would require a lot of changes, but for the case without bindings I have it working, I am just waiting for another PR to be merged/closed to commit it 

(I don't know how to commit to a different PR, tried to find in the docs but here [ https://help.github.com/articles/using-pull-requests/ ] it says: ***"After you send a pull request, any commit that's pushed to your branch will be automatically added to your pull request..."***)

**Comment by rodrigopedra** [comment]
Nevermind, I commited to another branch and merged it as a different PR

**Comment by Murtnowski** [comment]
@rodrigopedra Right now I'm just trying to use it in a Eloquent model

See this to understand what the model looks like http://pastebin.com/nxY37Zz5

So i'm not directly using the DB functions nor do I need to pass anything into the table-value function.
