### ISSUE TITLE
[5.1.27] SoftDeletes do not work on Relationships

### ISSUE THREAD

**Issue by heisian** [laravel/framework#11498]
### Parent Model:
```
<?php namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

use Watson\Validating\ValidatingTrait;

class Thing extends Model {

	use SoftDeletes;
	use ValidatingTrait;

	protected $table = 'things';

	protected $dates = ['deleted_at'];

	public function children() {
		return $this->hasMany('App\ThingChildren');
		// to provide the desired result, I have to modify the code to this:
		// return $this->hasMany('App\ThingChildren')->with('deleted_at', NULL);
	}
}
```

### Child Model:
```
<?php namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class ThingChildren extends Model
{
	use SoftDeletes;

	protected $table = 'thing_children';

	protected $dates = ['deleted_at'];

	public function thing() {
		return $this->belongsTo('App\Thing');
	}
}
```

### Querying the relation:
```
return Thing::find(1)->children();
```
The above returns all of the children, whether or not the `deleted_at` column is `NULL`.  "Trashed" children are returned in the collection.  Changing the code within the parent model to include `->where('deleted_at', NULL)` as in the commented line makes the query work as desired.  Is this a bug or is this the expected behaviour?

### Deletion:
Interestingly enough, SoftDeletes break down in relationships when deleting records as well:
```
Thing::find(1)->children()->delete();
```
Permanently deletes all child records, instead of SoftDeleting them.

This is my workaround:
```
// dependency-injected:
$softDeleteArray = $this->thing->children->lists('id')->toArray();
Children::destroy($softDeleteArray);
```

This works for me, but unfortunately the above code creates a separate DELETE query for each record, which I assume is for the benefit of updating the `deleted_at` timestamps individually.  I would rather have the framework run one single query and update all rows with the same timestamp, however.

Another caveat of the above method is that the `->lists('id')` method MUST be used in constructing the array for the `destroy()` method.  Using `array_push()` to construct the array will cause the `destroy()` method to not do anything.  Granted, using the `lists()` method is easier and cleaner but we're all about options here.

Are these bugs or are these expected behaviours that we need to work around?  I'm not for adding more complication to the framework for the sake of cleanliness and flexibility, but the above issues seem to point out some inconsistencies within the framework to me.

Thanks,

**Comment by GrahamCampbell** [comment]
I think this is intended.

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell.

**Comment by GrahamCampbell** [comment]
Taylor can re-open this if he believes it's a bug, but I don't think it is. I think you need to apply the scope yourself when defining the relation.

**Comment by heisian** [comment]
Not a problem, I was just a bit confused by the behaviour since it wasn't really made clear in the documentation.  Do you have any suggestions for the `destroy()` method creating multiple `DELETE` queries?  In practice, I'm really only ever be deleting one record at a time, so not a big deal, but seems like it would be nice to have in case.

**Comment by heisian** [comment]
I think there may be an issue with my installation specifically (it was an upgrade from 4.2), because when I run this query:

```
ThingChildren::where('thing_id', $thing->id)->firstOrFail();
```

I get back a ThingChildren model with the `deleted_at` column that has been set.  So to me, this indicates that the `SoftDeletes` trait is not working as intended in my installation.  Where would I look to see how to address this?

**Comment by taylorotwell** [comment]
Can you post your ThingChildren model?

**Comment by taylorotwell** [comment]
You don't need to do anything other than how you defined your model. Not sure what @GrahamCampbell is referring to.

**Comment by taylorotwell** [comment]
Is there any other code to this model that you didn't include?

**Comment by heisian** [comment]
I removed certain things to abstract it out as generally as possible for the issue.  Here is an unfiltered version of the 'ThingChildren' model:

```
<?php namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

use App\ExternalClasses\TokBox;

class KubiSession extends Model
{
	use SoftDeletes;

	protected $table = 'kubi_sessions';

	protected $hidden = array('id');

	protected $dates = ['deleted_at'];

	protected $fillable = ['kubi_id', 'location_id', 'sessionId', 'token', 'streamId', 'scope'];

	public function kubi() {
		return $this->belongsTo('App\Kubi');
	}

	public static function boot()
	{
		// Auto-create a TokBox session as well:
		KubiSession::creating(function($session) {
			$tokBox = TokBox::makeSession($session->kubi_id);
			$session->sessionId = $tokBox['sessionId'];
			$session->token = $tokBox['token'];
		});

		KubiSession::deleting(function($session) {
			// Calculate total session time for this session on softDelete
			$total_time = date("Y-m-d H:i:s", time() - strtotime($session->created_at));
			\Log::info($session);
			\Log::info($total_time);
			$session->total_time = $total_time;
			$session->deleted_at = time(); // we're manually setting this b/c we want to put two update queries into one
			$session->update();
			\Log::info('Deleting event triggered.');

			return false; // prevent from running two update deleted_at queries
		});
	}

}
```

**Comment by taylorotwell** [comment]
You need to call parent::boot() at the top of your boot method.

**Comment by heisian** [comment]
works! thank you for the support.
