### ISSUE TITLE
[Bug?][Laravel 5.2] Implicit Model Binding is running before middleware is applied 

### ISSUE THREAD

**Issue by bgarrison25** [laravel/framework#11496]
So in my routes I have a placeholder in the "uses". So something like `{api-version}\MembersController@index`. This is read in by my middleware and replaced with the correct namespace. 

However, in Laravel 5.2 you now do implicit model binding which does a reflection check on the "uses" class and method to grab its parameters for possible model binding. Since this happens BEFORE middleware is run it fails and crashes the application. 

I have two suggestions. A) Create a new event called BeforeRouteMatched that people can listen to and modify the route if need be. B) Allow us to set a config option to disable implicit model binding. I believe A) would be the easier and more efficient route but I leave it up to you guys!

**Comment by GrahamCampbell** [comment]
Not a bug. All model binding runs before route middlewares are applied.

**Comment by GrahamCampbell** [comment]
That is intended. If you don't want that, you can hack extend the router and the application in order to rebind it, and then write yourself a middleware to apply the bindings.

**Comment by GrahamCampbell** [comment]
:+1: for adding option A btw ;)

**Comment by GrahamCampbell** [comment]
Sorry I was reading this and adding comments as I went. ;)

**Comment by bgarrison25** [comment]
lol no problem...you may have just set my ADD into overdrive though...thanks :P. In all honestly I think option A) is the way to go....I could obviously hack the core code to implement this but id rather not ...so i brought it here....I've never put together a patch before but I could try!

**Comment by bgarrison25** [comment]
Could we re-open it to implement option a)?

**Comment by GrahamCampbell** [comment]
We don't process proposal issues normally on github.

**Comment by acasar** [comment]
It's a small change - I sent a PR: https://github.com/laravel/framework/pull/11497

**Comment by bgarrison25** [comment]
your awesome :)

**Comment by amosmos** [comment]
Hey @GrahamCampbell ,

What if I use implicit model binding and in my admin I only want admins to have access (for inserting, editing and deleting resources). Then if you are a guest, and happen to go to a URL inside the admin, with a parameter that doesn't correctly resolve to a resource, you get a 'No query results for model' instead of being redirected to the login page.

Isn't this scenario wrong...? Maybe I'm missing something...
