### ISSUE TITLE
[5.2] error after running the php artisan make:auth

### ISSUE THREAD

**Issue by donnigunawan** [laravel/framework#11504]
Hi, I am using laravel 5.2 fresh install in xampp. everything is running well, but after I run a command php artisan make:auth, I got 3 errors ErrorException in helpers.php line 294. 
1st error:
file_get_contents(C:\xampp\htdocs\fb\public\build/rev-manifest.json): failed to open stream: No such file or directory (View: C:\xampp\htdocs\fb\resources\views\layouts\app.blade.php) (View: C:\xampp\htdocs\fb\resources\views\layouts\app.blade.php)

2nd error:
file_get_contents(C:\xampp\htdocs\fb\public\build/rev-manifest.json): failed to open stream: No such file or directory (View: C:\xampp\htdocs\fb\resources\views\layouts\app.blade.php)

3rd error:
file_get_contents(C:\xampp\htdocs\fb\public\build/rev-manifest.json): failed to open stream: No such file or directory

**Comment by phecho** [comment]
step 1
```shell
mkdir public/build
touch public/build/rev-manifest.json
```
step 2
```json
{
  "css/app.css": "css/app.css",
  "js/app.js": "js/app.js"
}
```
add content above to public/build/rev-manifest.json

**Comment by donnigunawan** [comment]
thank you @phecho that's works!

**Comment by neowill2013** [comment]
@phecho  facing same issue, added as you said, but it is searching for app.css in build/css directory instead of public/css directory
