### ISSUE TITLE
[5.2] Sessions Aren't Persisting

### ISSUE THREAD

**Issue by GeonetTerry** [laravel/framework#11505]
Using a fresh installation of Laravel 5.2, I've tried setting a session like so:

    Session::put('foo', 'bar');

I visit the page in my browser to set the session, then remove that line. However, when I try to output the session like so:

     dd(Session::get('foo'));

...it returns null. I get the expected result of `bar` when using the same code and scenario in Laravel 5.1.

**Comment by GrahamCampbell** [comment]
That's because dd kills the app before the session is saved...

**Comment by GrahamCampbell** [comment]
The put method doesn't actually persist the data, if you like, it rather, just queues it to be persisted at the end.

**Comment by GrahamCampbell** [comment]
Also, make sure you include these routes inside the group with the web middleare applied.
