### ISSUE TITLE
Improvements in View Composer.

### ISSUE THREAD

**Issue by SachinAgarwal1337** [laravel/framework#11509]
If I add View Composer for all the views that is if i do something like this:
```
 View::composer('*', GlobalComposer::class);
```

It will include it in all the sub views also. That is if i have say 5 @include statements in my base view, Then View Composer will run the queries total of 6 times for same view.

And if I do like this:
```
 View::composer('template.app', GlobalComposer::class);
```
That is, If I make View Composer for base template, then the variables are not available for the child view extending the `app.blade.php`

I suggest it will be better if I add Variables from view composer to a template then all its child views extending that template should have those variables.

**Comment by GrahamCampbell** [comment]
We're open to PRs.

**Comment by GrahamCampbell** [comment]
That change should be pretty trivial I think.
