### ISSUE TITLE
"Your local changes to the following files would be overwritten"

### ISSUE THREAD

**Issue by llioor** [laravel/framework#11501]
Almost every time I'm doing git pull on my production server I have this massage:

```
error: Your local changes to the following files would be overwritten by merge:
        app/Http/helpers.php
Please, commit your changes or stash them before you can merge.
Aborting
```
Now it is helpers.php and next time it will be the next changed file.
It is not happening with all files but almost every time I run the git pull it happens.

I didn't make any change on the server it self. I'm logging in to production and immediately run to git pull commend.

Any help to avoid this issue for my next pull requests...
Thank you in advanced

**Comment by GrahamCampbell** [comment]
Please ask on the forums. This is unrelated to laravel.

**Comment by llioor** [comment]
Can you give me a link to the forums?
Sorry and thanks
