### ISSUE TITLE
error exception in the factory.php for @stop

### ISSUE THREAD

**Issue by MicroDreamIT** [laravel/framework#11515]
Suddenly i update composer and i found that laravel stop working.

**Comment by GrahamCampbell** [comment]
No details provided at all. Please create a new issue if you'd like to provide some details.

**Comment by MicroDreamIT** [comment]
its start working again. My layout file was pretty complicated. Start with 
'''
@extends('app')
......
@stop
'''

then i just delete @stop and delete it from every files

now the layout is look like
'''
@extends('app')
@section('body')
@endsection
'''
now this is without @stop. But without @stop it doesnt make any sense to me at all.

**Comment by MicroDreamIT** [comment]
@GrahamCampbell detail provided.
