### ISSUE TITLE
Blackfire agent no installed on Laravel Homestead v3.0.1 (vagrant box )

### ISSUE THREAD

**Issue by acacha** [laravel/framework#11514]
My environment:

```bash
$ vagrant box list
laravel/homestead (virtualbox, 0.4.0)

$ composer global show laravel/homestead
...
v3.0.1
```

When provisioning with blackfire configuration on Homestead.yaml and error occurs:

<pre>
Running provisioner: shell...
    default: Running: /tmp/vagrant-shell20151224-32362-s244m2.sh
==> default: /tmp/vagrant-shell: line 22: /etc/blackfire/agent: No such file or directory
==> default:  * Restarting HHVM FastCGI Daemon hhvm
==> default:    ...done.
==> default:  * Restarting PHP 7.0 FastCGI Process Manager php-fpm7.0
==> default:    ...done.
==> default: blackfire-agent: unrecognized service
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
</pre>

After executing:

```bash
$ sudo apt-get install blackfire-agent
```
On homestead no more problems provisioning.

**Comment by GrahamCampbell** [comment]
Blackfire is not compatible with php 7.

**Comment by acacha** [comment]
Ok thanks. Then I will create an issue on docs https://laravel.com/docs/master/homestead

**Comment by djallits** [comment]
Posting the pre-req's from Blackfire's site to avoid any future misunderstandings:

>     The Agent, and the Client work on Linux, MacOS X, FreeBSD and Windows;
>     The Probe works on Linux and MacOS X with PHP 5.3, 5.4, 5.5, 5.6, and 7.0;
>     The Companion is currently only available for Google Chrome;
>     The Website works on all browsers but Internet Explorer.


https://blackfire.io/docs/up-and-running/installation
