### ISSUE TITLE
[Homestead] MongoDB

### ISSUE THREAD

**Issue by pjebs** [laravel/framework#11519]
Could Homestead and Forge please include the official MongoDB PHP/HHVM driver.
http://php.net/manual/en/set.mongodb.php

**Comment by lcdss** [comment]
Would better request this on [homestead repository](https://github.com/laravel/homestead)

**Comment by GrahamCampbell** [comment]
Issues are disabled on that repo.

**Comment by GrahamCampbell** [comment]
Thanks for the request. Ping @taylorotwell.

**Comment by lcdss** [comment]
Beyond MongoDB, I would like if was included [Cassandra](https://pecl.php.net/package/cassandra),  [PhalconPHP](https://phalconphp.com) and [Yaf](https://pecl.php.net/package/yaf). Maybe some apps out of box too: phpmyadmin, phpredisadmin, opcachegui. I think this will be useful.

**Comment by pjebs** [comment]
Well regarding MongoDB, the actual Laravel documentation tells you how to create a custom cache and session interface for MongoDB.

**Comment by GrahamCampbell** [comment]
The mongo extension isn't available on ubuntu and php 7 yet.

**Comment by pjebs** [comment]
https://github.com/mongodb/mongo-php-driver/releases

**Comment by GrahamCampbell** [comment]
Yes, I am aware, but it's not available on ubuntu yet.

**Comment by pjebs** [comment]
Only for windows servers they provide a binary version of the extension. For linux, they expect you to build it for your particular version of linux and hhvm/php.

**Comment by GrahamCampbell** [comment]
We dont't build it ourselves.

**Comment by GrahamCampbell** [comment]
As soon as it becomes available, we'll include it in homestead again.

**Comment by pjebs** [comment]
For HHVM, there is no package manager. They've never provided a pre-compiled version so you'll have no choice but to build.

**Comment by pjebs** [comment]
This is just information for other people trying to install MongoDB extension into homestead.

**Comment by pjebs** [comment]
For Php 7 (the extension seems to work perfectly):
1) sudo apt-get install pkg-config libsasl2-dev
2) sudo pecl install mongodb
3) add extension=mongodb.so to /etc/php/7.0/fpm/php.ini AND /etc/php/7.0/cli/php.ini (so your composer dependencies can detect you have mongo extension installed).

**Comment by pjebs** [comment]
for HHVM:
I have created a Dockerfile to build the mongodb.so required for hhvm. It simply does not seem to build from within Homestead.
As @taylorotwell  changes the ubuntu version for homestead, you will have to change the dockerfile ubuntu version.
Also, you will need to check https://s3.amazonaws.com/drivers.mongodb.org/hhvm/ for the latest mongodb source file and modify line 26, 29 and 30 accordingly.
Then you will need to somehow copy the mongodb.so file from the docker container to docker host using `docker cp <containerId>:/file/path/within/container /host/path/target`.

Then inside homestead run:
`sudo mkdir -p /usr/local/lib/x86_64-linux-gnu/hhvm/extensions/20150212`
`sudo cp mongodb.so /usr/local/lib/x86_64-linux-gnu/hhvm/extensions/20150212` [Copy the mongodb.so file to hhvm's extensions location].

Modify hhvm's php.ini file to include:
`hhvm.dynamic_extension_path=/usr/local/lib/x86_64-linux-gnu/hhvm/extensions/20150212`
`hhvm.dynamic_extensions[mongodb]=mongodb.so`

Then restart hhvm: `sudo service hhvm restart`.

**Comment by pjebs** [comment]
In composer.json, add:
`"mongodb/mongodb": "^1.0.0@beta"`

Make sure you use hhvm to run composer update instead of the default php 7. See https://github.com/mongodb/mongo-php-library/issues/82

**Comment by pjebs** [comment]
DOCKERFILE:

FROM ubuntu:14.04
MAINTAINER pjebs <github.com/pjebs>

### INSTALL HHVM-DEV EDITION

RUN apt-get install -y software-properties-common

RUN apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0x5a16e7281be7a449
RUN add-apt-repository "deb http://dl.hhvm.com/ubuntu $(lsb_release -sc) main"
RUN apt-get update
RUN apt-get install -y hhvm-dev
RUN apt-get install -y wget
#RUN apt-get install -y apt-show-versions

### BUILD MONGO DB EXTENSION - https://s3.amazonaws.com/drivers.mongodb.org/hhvm/hhvm-mongodb-1.0beta1.tgz

RUN apt-get install -y libtool
WORKDIR /tmp
RUN wget https://s3.amazonaws.com/drivers.mongodb.org/hhvm/hhvm-mongodb-1.0beta1.tgz
RUN mkdir hhvm-mongodb
WORKDIR /tmp/hhvm-mongodb
RUN tar -xvzf ../hhvm-mongodb-1.0beta1.tgz
WORKDIR /tmp/hhvm-mongodb/hhvm-mongodb-1.0beta1
RUN hphpize
RUN cmake .
RUN make configlib
RUN make -j 1
RUN make install
