### ISSUE TITLE
Illuminate\Validation\Validator::getCustomMessageFromTranslator() is inefficient

### ISSUE THREAD

**Issue by halaei** [laravel/framework#11512]
It sounds like that the time complexity of this function is linearly proportional to the size of validation.custom array. I think this is not OK. Suppose you have a 100 custom rules, which I consider normal, and a user sends you 100 invalid data. In this case there can be 10000 comparison against keys in validation.custom. I guess that even can be regarded as a security issue, because the CPU usage of Laravel app will be 100x the CPU usage of the attacker.

**Comment by GrahamCampbell** [comment]
We're open to PRs.

**Comment by GrahamCampbell** [comment]
Thanks for bringing this up. We're open to PRs if you want to have a go at improving this.

**Comment by halaei** [comment]
One way to do this is to use to parse trans files into a trie data structure once, and then query it every for multiple times, if required.

I think we should have a benchmark before any try to fix. Maybe there is no problem at all, or maybe a try to optimize do the opposite.

Another thing in my mind is that, maybe, the following style does not worth the extra effort for writing custom trans:
```php
'custom' => [
    'person.*.email' => [
        'unique' => 'Each person must have a unique e-mail address',
    ]
],
```
instead, why not doing this:
```php
'custom' => [
    'person' =>
        '*' =>
            'email' => [
                'unique' => 'Each person must have a unique e-mail address',
            ]
       ]
    ]
],
```

**Comment by halaei** [comment]
@GrahamCampbell sounds like you closed this issue mistakingly.
That pull request has nothing to do with this issue. Am I right?
