### ISSUE TITLE
[5.1] [5.2] Bug with task scheduling when using emailOutputTo()

### ISSUE THREAD

**Issue by neamtua** [laravel/framework#11517]
Ever since i've updated to 5.2 from 5.1 I get an error when my task runs saying that emailOutputTo can't find the file I'm writing to with sendOutputTo.

```
live.ERROR: exception 'ErrorException' with message 'file_get_contents('/home/mysite/site/storage/logs/cron_deletetempfiles_2015_12_25.txt'): failed to open stream: No such file or directory' in /home/mysite/site/vendor/laravel/framework/src/Illuminate/Console/Scheduling/Event.php:710
```

Code I'm using in app/Console/Kernel.php is

```php
$schedule->command('deletetempfiles')
		->daily()
		->sendOutputTo(storage_path().'/logs/cron_deletetempfiles_'.date('Y_m_d').'.txt')
		->emailOutputTo('myemail');
```

I checked and the file exists and has the proper info in it.

**Comment by arrilot** [comment]
That's probably cause if the change in `sendOutputTo`.
I'll look into this tomorrow

**Comment by GrahamCampbell** [comment]
Thank you very much for the report @neamtua. @arrilot Thanks. :snowman:

**Comment by GrahamCampbell** [comment]
> Ever since i've updated to 5.2 from 5.1

Actually, this bug is present on 5.1 too. You must have just been using an older version of 5.1.
