### ISSUE TITLE
Get Request Args

### ISSUE THREAD

**Issue by gfazioli** [laravel/framework#11513]
I suggest to add this helper function for get the arguments in GET request:

```php
if ( ! function_exists( 'get_request_args' ) ) {

/**
* Get the request args.
*
* @param array $defaults Optional. Default values for args.
*
* @return array
*/
function get_request_args( $defaults = [ ] )
{
  $args = [ ];

  // loop into request
  foreach ( request()->all() as $key => $value ) {
    if ( 'q' == $key && ! empty( $value ) ) {
      list( $param, $paramValue ) = explode( '=', $value );
      $args[ $param ] = $paramValue;
    }
    elseif ( 'q' != $key ) {
      $args[ $key ] = $value;
    }
  }

  // set defaults
  if ( ! empty( $defaults ) ) {
    foreach ( $defaults as $key => $value ) {
      if ( ! isset( $args[ $key ] ) ) {
        $args[ $key ] = $value;
      }
    }
  }
  return $args;
  }
}
```

**Comment by GrahamCampbell** [comment]
This isn't really suitable for the core. Thanks though.

**Comment by gfazioli** [comment]
@GrahamCampbell I mean... in the helper functions?

**Comment by GrahamCampbell** [comment]
Yeh, so do I. ;)

**Comment by GrahamCampbell** [comment]
"core" referring to the repo laravel/framework

**Comment by gfazioli** [comment]
:+1:

**Comment by gfazioli** [comment]
@GrahamCampbell UPDATE, you can ignore this function beacuse it is caused by an error on my ngnix, in other words my vagrant installation used:

`try_files $uri $uri/ /index.php?q=$query_string;`

instead

`try_files $uri $uri/ /index.php?$query_string;`

for example, I got

![image](https://cloud.githubusercontent.com/assets/432181/12153679/86fff02c-b4bb-11e5-8f4f-34c17d4e701a.png)
