### ISSUE TITLE
Possible Issue With JSON Request In Testing

### ISSUE THREAD

**Issue by edcs** [laravel/framework#11521]
I've written the following test to try and create an access token for my API:

```php
public function testAccessTokenCanBeCreated()
{
    $user = factory(User::class)->create();

    $body = [
        'grant_type'    => 'password',
        'client_id'     => parent::CLIENT_ID,
        'client_secret' => parent::CLIENT_SECRET,
        'username'      => $user->email,
        'password'      => $user->email
    ];

    $this->json('post', route('oauth.access_token'), $body);
}
```

It simply posts some parameters to my OAuth 2.0 endpoint - I'm using the League package with a custom implementation. My service provider is setup like this:

```php
$this->app->singleton(AuthorizationServer::class, function (Application $app) {
    $server = new AuthorizationServer;

    $server->setSessionStorage($app->make(SessionStorage::class));
    $server->setAccessTokenStorage($app->make(AccessTokenStorage::class));
    $server->setRefreshTokenStorage($app->make(RefreshTokenStorage::class));
    $server->setClientStorage($app->make(ClientStorage::class));
    $server->setScopeStorage($app->make(ScopeStorage::class));
    $server->setAuthCodeStorage($app->make(AuthCodeStorage::class));

    $passwordGrant = new PasswordGrant;

    $passwordGrant->setVerifyCredentialsCallback(function ($email, $password) use ($app) {
        $user  = $app[User::class]->where('email', $email)->first();
        return $app[Hasher::class]->check($password, $user->password);
    });

    $server->addGrantType($passwordGrant);

    $refreshTokenGrant = new RefreshTokenGrant;

    $server->addGrantType($refreshTokenGrant);
    $server->setRequest($app['request']);

    return $server;
});
```

The method for this endpoint in my controller looks like this (the `dd` is in there for debugging - I'll get to that in a sec):

```php
public function accessToken(Request $request)
{
    dd($request->request);
    $response = $this->server->issueAccessToken();

    return response()->json($response);
}
```

When I run a request using Postman, the endpoint works perfectly and returns the payload containing the access and refresh tokens. However, when I run it in the test suite it fails stating that the `grant_type` parameter is missing.

When I run the request with that `dd` in place using Postman, I see this:

```php
ParameterBag {#33
  #parameters: array:5 [
    "grant_type" => "password"
    "client_id" => "wh5jgIZC8J8SiAm4kMhea6ASOrbBq4rg"
    "client_secret" => "CXC6Ceg3wBhnaxz1D5z6kWSYxQOk6IAk7C8bygKSPyrrZAG2"
    "username" => "e.coleridgesmith@edcs.me"
    "password" => "e.coleridgesmith@edcs.me"
  ]
}
```

Which is awesome, the parameters are all there so everything is working. This is what I see when I run the request in the test suite:

```php
Symfony\Component\HttpFoundation\ParameterBag {#712
  #parameters: []
}
```

Which leads me to believe that the request isn't being properly created by the test suite? I've tried debugging the OAuth package, the Symfony request and the Laravel test suite but I can't seem to see the culprit. The correct headers are being sent to state that this is a JSON request but that's as far as I've managed to get.

Does anyone have any thoughts on what's going on?

**Comment by GrahamCampbell** [comment]
Thanks for the issue, but I think this belongs on the forums please.

**Comment by GrahamCampbell** [comment]
http://laravel.io/forum

**Comment by edcs** [comment]
I've been digging around, and I'm sure there is a problem here. My code works when I test it in the browser or with Postman, but when I try running a functional test I get an error. To debug this, I've stuck a `dd($request)` on the the first line of the `handle()` method in `Illuminate\Foundation\Http\Kernel`.

I am POSTing some JSON similar to this:

```javascript
{
    "grant_type": "password",
    "client_id": "kzruwsK44YzmDirOdqcvYnmxBFo5NyxZ",
    "client_secret": "ha1cnJtfBPxVHAwwCG7y1Lz1tD7jcJhtuEAVccvEmEd6sRdt",
    "username": "e.coleridgesmith@edcs.me",
    "password": "e.coleridgesmith@edcs.me"
}
```

The results from Postman look a bit like this:

```
Request {#41
  #json: ParameterBag {#33
    #parameters: array:5 [
      "grant_type" => "password"
      "client_id" => "kzruwsK44YzmDirOdqcvYnmxBFo5NyxZ"
      "client_secret" => "ha1cnJtfBPxVHAwwCG7y1Lz1tD7jcJhtuEAVccvEmEd6sRdt"
      "username" => "e.coleridgesmith@edcs.me"
      "password" => "e.coleridgesmith@edcs.me"
    ]
  }
```

But when I run them using the functional tester I get this:

```
Illuminate\Http\Request {#693
  #json: null
```

I'm not doing anything fancy with the tests either, I'm just using something like this:

```php
$credentials = $this->getResourceOwnerCredentials();

$body = [
    'grant_type'    => 'password',
    'client_id'     => $credentials->id,
    'client_secret' => $credentials->secret,
    'username'      => $username,
    'password'      => $password
];

$this->json('post', route('oauth.access_token'), $body);
```

The JSON body is definitely not getting set during testing - I've dug around and can't really figure out what's going on. I'll try fixing it if someone points me in the right direction...
