### ISSUE TITLE
Session in laravel5.2

### ISSUE THREAD

**Issue by hichamhadraoui** [laravel/framework#11527]
hello,

i have a probleme in login , when i make a login i see in the header the name of the user that logged in
but after i go to another page , the username gets removed !! i don't know why! the session are stored in the file i can see them . ++ if i go to /register they redirect me to the home page and that's mean there's a session , i change the session to a session table and i see the session in the database but as i said when i do refresh the name is not found + Auth::user() = null !! even though when i go to /register or /login the app redirect me to the home page!

**Comment by GrahamCampbell** [comment]
In the default app, the `/` route does not include sessions. You must put all code you want to have sessions inside the web group at the bottom of the routes file.

**Comment by hichamhadraoui** [comment]
oh yeah ok i will test that thank you bro (y)
