### ISSUE TITLE
[5.2]Session store not set on request

### ISSUE THREAD

**Issue by nandanvrs** [laravel/framework#11524]
while using laravel form builder formers/former or form old() function . getting these error.

1st Error :  ErrorException in Request.php line 775:
Session store not set on request. 

2nd Error:  RuntimeException in Request.php line 775:
Session store not set on request.

**Comment by GrahamCampbell** [comment]
Thank you for reporting, but it looks like you've forgotten to start a session. Most likely your route wasn't put in the new web middleware.

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/laravel/blob/master/app/Http/Kernel.php

**Comment by GrahamCampbell** [comment]
See that second group at the bottom. Anything that depends on sessions needs to be defined in there.

**Comment by GrahamCampbell** [comment]
Oops, wrong file: https://github.com/laravel/laravel/blob/master/app/Http/routes.php.

**Comment by nandanvrs** [comment]
Thanks @GrahamCampbell , It's working.

**Comment by GrahamCampbell** [comment]
:christmas_tree:

**Comment by liaokong** [comment]
how to write the routes.php ? the default is wrong ? https://github.com/laravel/laravel/blob/master/app/Http/routes.php.
but how to write it,thank you

**Comment by gravataLonga** [comment]
Hi, i ran this command ```php artisan route:list``` and give me this error: 

```
[RuntimeException]                 
  Session store not set on request.  
```

But when i navigate on my project all see me ok, what happen?  

My laravel version is 5.x.

Many Thanks,
Jonathan Fontes
