### ISSUE TITLE
In welcome.blade.php. Show a text stating whether DB connection is successful

### ISSUE THREAD

**Issue by gibtang** [laravel/framework#11528]
Seeing that Laravel is used mostly for applications that require a DB connection. Won't it be useful to put in some code to do a DB connection and then display the result of the DB connection in the welcome.blade.php instead of letting user put in their own code later to attempt the DB connection

**Comment by mikerockett** [comment]
Are you referring to some kind of quick-start guide on the welcome view? I don't think this is necessary.

**Comment by gibtang** [comment]
Not really. Just a text saying 'Connection to database successful' or 'Error connecting to database due to'. I mention this because when someone creates a new app and sets up the DB connection, they normally go to welcome.blade.php to see if it is ok. Then they must write additional code to do a query and then the person will know if the database settings are correct. If the person sees the database connection successful message, then the person will know his database settings are correct and proceed to write his code

**Comment by mikerockett** [comment]
I still think it isn't necessary - you should be checking the connection settings yourself anyway.

Going to let @GrahamCampbell chime in on this now.

**Comment by GrahamCampbell** [comment]
I don't think this will be accepted for the same reason the default `/` route doesn't load sessions. So we look good on benchmarks. Thanks for the idea though.

**Comment by gibtang** [comment]
No worries. I understand the rational behind the reason
