### ISSUE TITLE
[Laravel v5.2]RuntimeException in Request.php line 775: Session store not set on request.

### ISSUE THREAD

**Issue by duruitang** [laravel/framework#11525]
![image](https://cloud.githubusercontent.com/assets/13196890/12002416/56184a9a-ab38-11e5-95bd-19b6bcf92363.png)

**Comment by GrahamCampbell** [comment]
Thank you for reporting. On upgrading to laravel 5.2, make sure you either move the session middleware to the global part, or put all your routes depending on it inside a group that has the web middleware.

**Comment by duruitang** [comment]
Thanks! You guys doing great!

**Comment by GrahamCampbell** [comment]
No problem. :christmas_tree:
