### ISSUE TITLE
[5.2][Authentication] Show logged in user's name and the logout link in every page

### ISSUE THREAD

**Issue by mbsvpn** [laravel/framework#11536]
I created a new authentication scaffolding in Laravel 5.2 using

`php artisan make:auth`

everything worked perfectly except I get Login/Register links even after logging in when I'm in route 

`/`

but it shows the user's name with a logout link (which is what I think would be better to have in every page) when I'm in route

`/home`

Isn't it better to show logged in user's name and the logout link in every page?
![Don't](http://i.stack.imgur.com/KNu1v.jpg)

![Do](http://i.stack.imgur.com/3R7RE.jpg)

**Comment by lagbox** [comment]
Apply the `web` middleware group to your `/` route.

**Comment by GrahamCampbell** [comment]
> Apply the web middleware group to your / route.

Yes, you need to do that.

**Comment by napoleon101392** [comment]
extend the layout at 'layout.app'
