### ISSUE TITLE
[Homestead] [Forge] HHVM PHP7

### ISSUE THREAD

**Issue by pjebs** [laravel/framework#11532]
Can Homestead and Forge please support PHP7 mode for HHVM.

Some people want to use PHP7 code in HHVM.
It requires the `php.ini` file to include: `hhvm.php7.all = 1`.
It's a bit annoying having to change it everytime I kickstart homestead.

https://docs.hhvm.com/hhvm/configuration/INI-settings#php-7-settings

**Comment by GrahamCampbell** [comment]
This shouldn't be needed IMO. HHVM will be making that mode the default at some point in the near future once they implement more PHP 7 features. TBH, we're still waiting on some php 5.6 features too, like having arrays as constants.
