### ISSUE TITLE
Auth::logout() not working

### ISSUE THREAD

**Issue by pjebs** [laravel/framework#11535]
The docs state this:

To log users out of your application, you may use the logout method on the Auth facade. This will clear the authentication information in the user's session...

What is the intended behaviour of Auth::logout()? What is it meant to do?

`Auth::login($user);` //This logs the user in
I can log user in and make it persist through different requests but
`Auth::logout()` makes them logout for that particular request but does not persist the log out? They are still considered logged in for future requests as per: `Auth::user();`

**Comment by GrahamCampbell** [comment]
Thank you for reporting, but as I said, this isn't actually a bug. It's the expected behaviour.

**Comment by GrahamCampbell** [comment]
The 2nd request finishing will store the session, regardless of if a previous request running at the same time was meant to log the user out.

**Comment by GrahamCampbell** [comment]
https://github.com/AltThree/Locker/blob/master/src/Http/Middleware/LockingMiddleware.php

**Comment by GrahamCampbell** [comment]
I wrote an example middleware there. Just mofiy it to lock for all types of requests if you want maximal locking.

**Comment by GrahamCampbell** [comment]
Ie, delete:

```
        if ($request->isMethodSafe()) {
            return $next($request);
        }
```

**Comment by pjebs** [comment]
Was this changed with L5.1?

**Comment by pjebs** [comment]
What is the intended behaviour of Auth::logout()? What is it meant to do?

**Comment by GrahamCampbell** [comment]
Logout only performs an operation on the session, which is persisted when the session is saved. If someone else overwrites the saved data just after, than we have a problem. This is the issue you're experiencing, which is why I'm suggesting to take a look at locking. Hope this makes sense. ;)

**Comment by pjebs** [comment]
Thanks

**Comment by GrahamCampbell** [comment]
> Was this changed with L5.1?

Oh? I assumed you were using L5.1. We only support L5.1 LTS, or L5.2. ;)

**Comment by pjebs** [comment]
No I am using L5.1.
I upgraded my project from L5 where it logout worked.
