### ISSUE TITLE
Auth::logout() not working

### ISSUE THREAD

**Issue by pjebs** [laravel/framework#11534]
I'm using Laravel 5.1 on Homestead using redis session. (Although I also tried 'file').

Auth::logout() does not seem to clear session because it doesn't persist the log out scenario.

If you run that command, during the request everything will behave as if use is logged out from that point forward. But in the next request, the person is still logged in.

**Comment by GrahamCampbell** [comment]
Thanks, but this is the expected behaviour I'm afraid. Feel free to implement a locking system in your own app if you want, but that's way out of the scope of the core. (i have locking implemented in somr private apps i have)

**Comment by pjebs** [comment]
It use to log out the user in L5.
What changed?
What do you mean locking system?

**Comment by pjebs** [comment]
So your telling me
Auth::login($user);
Can log user in and make it persist through different requests but
auth::logout makes them logout for that request but does not persist the log out?

That is a security issue

**Comment by pjebs** [comment]
The docs state this:

To log users out of your application, you may use the logout method on the Auth facade. This will clear the authentication information in the user's session:

**Comment by pjebs** [comment]
To log users out of your application, you may use the logout method on the Auth facade. This will clear the authentication information in the user's session:
