### ISSUE TITLE
HttpResponseException do not reach Exceptions\Handler.php class

### ISSUE THREAD

**Issue by SachinAgarwal1337** [laravel/framework#11531]
When A `FormRequest` throws `HttpResposeException` It is not been handled by `Exceptions\Handler.php` The `render` method is not even touched.

**Comment by GrahamCampbell** [comment]
Yes, this is intended. An `HttpResponseException` already has the response contained with in it.

**Comment by GrahamCampbell** [comment]
That response is used.

**Comment by SachinAgarwal1337** [comment]
@GrahamCampbell ok so how do I make my default `403.blade.php` visible if a FormRequest `authorize` method return false?

**Comment by GrahamCampbell** [comment]
Which laravel version please?

**Comment by SachinAgarwal1337** [comment]
5.1

**Comment by GrahamCampbell** [comment]
There is no work around in Laravel 5.1 I'm afraid. Sorry.

**Comment by GrahamCampbell** [comment]
I the router, we have this code:

```php
    /**
     * Run the route action and return the response.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return mixed
     */
    public function run(Request $request)
    {
        $this->container = $this->container ?: new Container;

        try {
            if (! is_string($this->action['uses'])) {
                return $this->runCallable($request);
            }

            if ($this->customDispatcherIsBound()) {
                return $this->runWithCustomDispatcher($request);
            }

            return $this->runController($request);
        } catch (HttpResponseException $e) {
            return $e->getResponse();
        }
    }
```

**Comment by GrahamCampbell** [comment]
In Laravel 5.2, that's abstracted to the exception handler, so you can hack the beahviour much more easily.

**Comment by SachinAgarwal1337** [comment]
ok. Will figure it out somehow. But It will be great if you consider my pr https://github.com/laravel/framework/pull/11530 for v5.2.* or v5.3

**Comment by GrahamCampbell** [comment]
The idea is that you render that view you want in the `forbiddenResponse` method. If you don't want that, then I'd recommend not using form requests.
