### ISSUE TITLE
5.2 MySQL PDO Error with HHVM

### ISSUE THREAD

**Issue by j42** [laravel/framework#11537]
I don't understand what's going on here... I've hardcoded the authentication parameters in `config/database.php` so there's 0 chance it's an environment-related misconfiguration.  I've also accessed the DB via my homestead vagrant box `mysql -u homestead -p` with `secret` (it worked).

I set up a simple route to test the database:

```php
Route::get('test', function() {
        $db = app()->make('db');
        dd($db->table('transactions')->get());
});
```

There's no situation where this shouldn't work... the tables are defined normally, and I've ensured with HHVM's `get_loaded_extensions` that the mysql PDO extension is there (it is).

Instead, I get this cryptic error:

![screen shot 2015-12-26 at 12 09 04 am](https://cloud.githubusercontent.com/assets/5133586/12005191/eb24bbc4-ab64-11e5-81c0-042b314a76da.png)

-------

Notice how the MySQL error is not associate with an error code -- that makes me think it's an issue connecting to the database (which is why I tried hardcoding values in `config/database.php` to preclude any environment issues potentially) but if there is a problem, I can't find it.

```
HipHop VM 3.11.0 (rel)
Compiler: tags/HHVM-3.11.0-0-g3dd564a8cde23e3205a29720d3435c771274085e
Repo schema: 52047bdda550f21c2ec2fcc295e0e6d02407be51
```

Please help! I've spent my entire Christmas afternoon stuck on this :)

**Comment by j42** [comment]
I just had a revelation.  The problem is not related to HHVM at all!!!!

For some reason Laravel is having a problem with the table name: `transactions`.

If I run that same query on the users table, for example, the mysterious "General error:" goes away.

Thoughts?  Is this a reserved table for something I don't know about?

**Comment by j42** [comment]
The issue seems to be present with Eloquent's `firstOrCreate` as well, for example, I'm getting:

```
QueryException in Connection.php line 653:
SQLSTATE[HY000]: General error: (SQL: select * from `orders` where (`txn` = ch_17MBim2UmEGMwu1wLz8RrIG2 and `email` = scrubbed) limit 1)

```

**Comment by j42** [comment]
Also I switched off `hhvm: true` in my `Homestead.yaml` and everything magically works again.

That said, I really feel like this should be working with HHVM.

**Comment by j42** [comment]
no explanation?

**Comment by GrahamCampbell** [comment]
Thanks for reporting, but actually it's up to HHVM to work with us, not the other way around. Please report this error to HHVM.

**Comment by j42** [comment]
Thanks I'll report this to their team immediately.

**Comment by GrahamCampbell** [comment]
> no explanation?

I was just typing it.
