### ISSUE TITLE
About global scope, I'm not sure it's a bug or a normal design

### ISSUE THREAD

**Issue by phecho** [laravel/framework#11539]
Here is the case with my application:

###  the User Model has a global scope
```php
class User extends Model
{
    public static function boot()
    {
        parent::boot();

        static::addGlobalScope(function($builder) {
            $builder->where('is_active', 1);
        });
    }
}
```
###  I defined a route model in RouteServiceProvider
```php
protected function registerBindings()
    {
        $this->app->router->model('user', 'App\Models\User');
    }
```
### In my User controller has function named getUser(User $user)
```php
public function getUser(User $user)
    {
        return Redirect::route('user.show');
    }
```
I can't get to the user who's is_active not equal 1 here.  

###  I read the code in Illuminate/Routing/Router.php. it has a function named model.
```php
public function model($key, $class, Closure $callback = null) {
...
$instance = $this->container->make($class);
            if ($model = $instance->where($instance->getRouteKeyName(), $value)->first()) {
                return $model;
            }
...
}
```
It seems that the function above doesn't support withoutGlobalScope.

###  My problem is : how can I fetch the user ignore its value of is_active. The possible way I think about it is:

```php
public function getUser($id)
    {
        $user = User::find($id);
        return Redirect::route('user.show');
    }
```
Any others?

**Comment by GrahamCampbell** [comment]
This is definitely by design. Take soft deleting as an example to think about. ;)
