### ISSUE TITLE
Deploying Laravel into shared hosting server

### ISSUE THREAD

**Issue by shsbd** [laravel/framework#11533]
Hello,
Is there any easy to way to upload and deploy Laravel into shared cPanel hosting?

When working with local development, it works fine but when decided to upload into web server, it shows files and folder directory instead of welcome page.

Hoping someone will share some ideas to solve the problem.

Laravel Version: 5.2
Server type: Site5.com shared hosting
PHP Version 5.5.30

Thanks in advance.

![screenshot_1](https://cloud.githubusercontent.com/assets/12555542/12004597/51da5fd8-ab90-11e5-9d60-91664cc09d11.png)

**Comment by GrahamCampbell** [comment]
Please ask on the fourms.
