### ISSUE TITLE
[L5.1] Nesting Route Groups

### ISSUE THREAD

**Issue by pjebs** [laravel/framework#11538]
You don't seem to be able to nest route groups within route groups.

`Route::group(['domain' => 'hello.com' ], function()
{

Route::group(['prefix' => 'settings' ], function()
    {
      //Route should correspond to hello.com/settings/password
        Route::post('/password', 'SettingsController@password');
    });

}`

**Comment by pjebs** [comment]
The docs say you can with namespaces but the above code doesn't work.

**Comment by pjebs** [comment]
Actually the code above works.
My actual code defines middleware in the inner route group - that is what makes it not work.

`
//Should be this in the above example
    Route::group(['prefix' => 'settings', 'middleware' => ['auth', 'csrf', 'https']], function()
    {

        // Change password
        Route::post('/password', 'SettingsController@password');


    });

`

**Comment by mikerockett** [comment]
It works in 5.2 - are you getting an exception?

**Comment by pjebs** [comment]
Just NotFoundHttpException

**Comment by mikerockett** [comment]
Just to confirm, the following works for me on 5.2. As far as I am aware, no significant changes were made to routing in 5.2, and so this should be working in 5.1.

```php
Route::group(['domain' => 'hello.com'], function () {
    Route::group(['prefix' => 'settings'], function () {
        Route::get('password', 'SettingsController@getChangePassword');
        Route::post('password', 'SettingsController@postChangePassword');
    });
});
```

**Comment by GrahamCampbell** [comment]
Thanks for reporting, but we were unable to fix on 5.1 for technical reasons causing BC breaks.

**Comment by mikerockett** [comment]
@GrahamCampbell So are you confirming that there is indeed a bug in 5.1 LTS?

**Comment by GrahamCampbell** [comment]
Yeh, there are quite a few known issues in the routing and database issues that we can't fix because it broke more actually applications than it fixed.

**Comment by mikerockett** [comment]
Understood, thanks for the clarification.
