### ISSUE TITLE
Validating required array fields

### ISSUE THREAD

**Issue by danieliancu** [laravel/framework#11545]
Say you want to validate a list of persons and ensure that for each one you have a name and an email address.

```php
$this->validate($request, [
    'persons.*.name'  => 'required|...',
    'persons.*.email' => 'required|...',
]);
```

Should be enough, right?

Well, it's not. This will only ensure that at least one person has a name set and at least one person has an email set (they can be different persons).

Searching the internet I found that array validation in Laravel is quite painful. But I think this has changed. The release of 5.2 even allows the use `*` in dot syntax.

I think that a rule like `has_keys`, which validates the given fields (keys) on the specified array attribute, can help solve this problem, thus improving array validation.

So you can do things like:

```php
$this->validate($request, [
    'persons.*'  => 'has_keys:name,email',
]);
```

or

```php
$this->validate($request, [
    'person'  => 'has_keys:name,email',
]);
```

if you want the person array to have the name and email fields (single set).
Though in this case you can do:

```php
$this->validate($request, [
    'person.name'  => 'required|...',
    'person.email' => 'required|...',
]);
```

While writing this I also see a need for a `has_only_keys` rule which will check that only the given fields are present, in case you pass the input to a model/repository and having other keys can trigger other actions.

Another name for the rules could be `has_fields`, but it is not as evident as `has_keys` that is referring to an array.

I love the framework that you built and it's awesome to be able to use it in my projects. I want to start contributing to it. To solve this issue I would like to create a PR, but I also wanted to hear your opinion on this matter.

Merry Christmas!

**Comment by danieliancu** [comment]
Regarding the `has_only_keys` rule, I think that having `$request->only(['persons.*.name', 'persons.*.email'])` is more the laravel way. Or even `$request->only(['persons.*.{name,email}'])`.
Let me know your opinion.

**Comment by GrahamCampbell** [comment]
Thanks for reporting. We don't process proposals on GitHub though. Feel free to raise it on slack, and/or create a PR.
