### ISSUE TITLE
Blackfire on Laravel Homestead docs but not compatible and not installed

### ISSUE THREAD

**Issue by acacha** [laravel/framework#11540]
As @GrahamCampbell said on issue:

https://github.com/laravel/framework/issues/11514

Blackfire is not installed on Homestead with php 7 because is not compatible. Then maybe have to e removed or some comment have to be added on docs?

https://laravel.com/docs/master/homestead

**Comment by GrahamCampbell** [comment]
We're open to PRs on the docs. ;)
