### ISSUE TITLE
Laravel 5.2 Fresh install Class log does not exist

### ISSUE THREAD

**Issue by Ham3D** [laravel/framework#11541]
When i try to install a Fresh Laravel 5.2 using Composer it gives me error:
Error Output: PHP Fatal error:  Uncaught ReflectionException: Class log does not exist in BLAH/vendor/laravel/framework/src/Illuminate/Container/Container.php:736
 -- 
i tried removing cache, tried laravel installer or composer way, none worked.
both gives this error

**Comment by GrahamCampbell** [comment]
Sounds like you're having an issue before we setup the log bindings. Are you file permissions.

Respectfully, I'm going to close this and ask if you could seek help on the forums, because I don't believe this to be a bug in laravel.

**Comment by GrahamCampbell** [comment]
Thanks anyway though. ;)

**Comment by Ham3D** [comment]
Humor me Graham, can you please do me a favor and try to install a fresh laravel right now ?
i tried to install a fresh installition of laravel on my Production server with 3 already working laravel apps...
there is that error again.

**Comment by GrahamCampbell** [comment]
I just installed a fresh laravel app and it worked just fine: https://i.starbs.net/a7yB.

**Comment by Ham3D** [comment]
Tnx man For checkup, @GrahamCampbell

**Comment by priyeshwar-AGL** [comment]
Fatal error: Uncaught ReflectionException: Class log does not exist in /var/www/html/babynatura/vendor/laravel/framework/src/Illuminate/Container/Container.php:741 Stack trace: #0 /var/www/html/babynatura/vendor/laravel/framework/src/Illuminate/Container/Container.php(741): ReflectionClass->__construct('log') #1 /var/www/html/babynatura/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('log', Array) #2 /var/www/html/babynatura/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('log', Array) #3 /var/www/html/babynatura/vendor/laravel/framework/src/Illuminate/Container/Container.php(842): Illuminate\Foundation\Application->make('log') #4 /var/www/html/babynatura/vendor/laravel/framework/src/Illuminate/Container/Container.php(805): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter)) #5 /var/www/html/babynatura/vendor/laravel/framework/src/Illuminate/Container/Container.php(775): Illuminat in /var/www/html/babynatura/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 741

**Comment by priyeshwar-AGL** [comment]
I am using laravel 5.1
I have install package and remove it then i have getting this error please help 
 Fatal error: Uncaught ReflectionException: Class log does not exist in /var/www/html/babynatura/vendor/laravel/framework/src/Illuminate/Container/Container.php:741 Stack trace: #0 /var/www/html/babynatura/vendor/laravel/framework/src/Illuminate/Container/Container.php(741): ReflectionClass->__construct('log') #1 /var/www/html/babynatura/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('log', Array) #2 /var/www/html/babynatura/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('log', Array) #3 /var/www/html/babynatura/vendor/laravel/framework/src/Illuminate/Container/Container.php(842): Illuminate\Foundation\Application->make('log') #4 /var/www/html/babynatura/vendor/laravel/framework/src/Illuminate/Container/Container.php(805): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter)) #5 /var/www/html/babynatura/vendor/laravel/framework/src/Illuminate/Container/Container.php(775): Illuminat in /var/www/html/babynatura/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 741
