### ISSUE TITLE
[5.2] delete() stopped working on models that uses SoftDeletes trait after upgrading to 5.2 from 5.1.27

### ISSUE THREAD

**Issue by neutralrockets** [laravel/framework#11548]
The delete() method has stopped working on models that use SoftDeletes trait after upgrading to Laravel 5.2.5 from 5.1.27.

Here is a basic scenario to illustrate the issue. I have defined a model called Subscription, which uses the SoftDeletes trait:

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Subscription extends Model
{
    use SoftDeletes;

    protected $primaryKey = 'email';

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'subscriptions';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['email'];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];
}
```

I have a migration to create a subscriptions table:

```
        Schema::create('subscriptions', function (Blueprint $table) {
            $table->string('email')->index();
            $table->timestamps();
            $table->softDeletes();
        });
```

Now I try to soft-delete an existing subscription from the database, which does not work (deleted_at column is not populated with a timestamp):

```
$subscription = Subscription::withTrashed()->find('test@example.com');
$subscription->delete();
```

this doesn't work either:

```
$subscription = Subscription::find('test@example.com');
$subscription->delete();
```

However, this works (deleted_at column is updated as expected):

```
Subscription::withTrashed()->where('email', 'test@example.com')->delete();
```

In both of the situations above, the model object is returned as expected and I can access the properties of $subscription. In fact, restore() seems to work just fine and the "deleted_at" column becomes NULL again as expected. It seems that only delete() is not working.

I have verified the above works on my old version of Laravel 5.1.27, but since upgrading to 5.2.5 the delete() functionality has broken. I have also checked this with a fresh install of 5.2.5 and seems to be broken in the same way.

Is this a legitimate problem or am I doing something wrong?

**Comment by GrahamCampbell** [comment]
Thanks for the issue, but this is the correct behaviour. We made some tweaks in L5.2 to improve things.

**Comment by neutralrockets** [comment]
Thanks for letting me know that this is the expected behaviour. Is there any explanation for why the delete() behaviour has been changed or what it was replaced with? It seems strange that delete() no longer does anything and just fails silently.

**Comment by GrahamCampbell** [comment]
It's not really failing silently, it's just being executed on an empty set of results.

**Comment by neutralrockets** [comment]
I'm confused about how the result set is empty if find() is retrieving the object from the database and populating all the fields? What is the empty set of results that delete() is working on?

**Comment by neutralrockets** [comment]
When I print_r the $subscription object, I can see that the "deleted_at" field is updated as expected after the call to delete(), however it is never persisted to the database.

**Comment by GrahamCampbell** [comment]
This does seem a bit odd. Ping @taylorotwell.

**Comment by taylorotwell** [comment]
I need to see the entire actual model class.

**Comment by acasar** [comment]
I tested this exact scenario and it works as expected...

@neutralrockets Can you paste the entire model as Taylor suggested?

**Comment by acasar** [comment]
@neutralrockets OK I got it. In 5.2 incrementing keys are automatically cast to ``int``. Since `email` is not an incrementing key in your case, you should set the `public $incrementing` property to false on your model.

@taylorotwell Should we mention this in the docs?

**Comment by EliasZ** [comment]
@acasar Sounds like an undocumented feature to me.

**Comment by taylorotwell** [comment]
Yes, we should probably mention that ID's are cast to int. But, yes,
definitely incrementing should be set to false if you are not using
auto-incrementing IDs.

**Comment by neutralrockets** [comment]
@acasar After adding the following:

```
public $incrementing = false;
```

to the model, it is now soft-deleting correctly! Thanks for working this out it was driving me nuts.

This should definitely be documented somewhere as a caveat when using non-incrementing IDs.

**Comment by GrahamCampbell** [comment]
> This should definitely be documented somewhere as a caveat when using non-incrementing IDs.

I'm a bit shocked that it's not already documented?
