### ISSUE TITLE
Allow request input retrieval using dot syntax

### ISSUE THREAD

**Issue by danieliancu** [laravel/framework#11546]
I find it awesome since 5.2 that we can use the `*` character in dot syntax for validation.

I think we should also be able to retrieve input using the same syntax.
Like:

```php
$request->input('persons.*.name');

$request->only([
    'persons.*.name',
    'persons.*.email',
]);
```

I want to create a PR.
Please let me know of your opinion.

**Comment by GrahamCampbell** [comment]
Thank you, but as stated in our docs, we don't process proposal issues. Please either just skip strait to the PR part, or ask for feedback on slack first.

**Comment by GrahamCampbell** [comment]
Also, note, that it's fine for a PR to be partial, or just contain tests for the implimitation, without the implication, as a way to get feedback before completing the PR.

**Comment by danieliancu** [comment]
@GrahamCampbell thank you, it's exactly what I'll be doing.
