### ISSUE TITLE
[5.1] Request object is not serializing

### ISSUE THREAD

**Issue by SachinAgarwal1337** [laravel/framework#11551]
I have a queued Job which accepts `Request` object. But I get error stating:

```
Serialization of 'Closure' is not allowed
```

Tried Debugging, found out that Request object is not getting serialized.
Plus, It is an object, why is it getting as Closure.?

**Comment by GrahamCampbell** [comment]
The request object cannot be serialized. This is because it contains properties which contain objects containing closures.

**Comment by GrahamCampbell** [comment]
You can get all the data out the request by writing `(string) $request` though.

**Comment by SachinAgarwal1337** [comment]
I got it from doing `$request->all()`

**Comment by sjors-bootmine** [comment]
Please be aware that if your original request had a json content type the request object might not function as expected.
Use: `$request->headers->remove('CONTENT_TYPE');` as a fix
