### ISSUE TITLE
Middleware failures in route groups: "ErrorException in Application.php line 1102: Array to string conversion"

### ISSUE THREAD

**Issue by k98kurz** [laravel/framework#11554]
## Overview of Issue

When nesting route groups in Lumen, the ability to pass an array of middleware to the nested group or route definition completely breaks, resulting in `ErrorException in Application.php line 1102: Array to string conversion`.

### Working code (outside of a route group):

    $app->get('/api/v0/test-role/admin', ['middleware' => ['apiauth', 'is:admin'], 'uses' => 'Controller@testApiRoleAdmin']);

### Non-working code - middleware array in route within a nested route group:

    $app->group(['prefix' => 'api/v0', 'namespace' => 'App\Http\Controllers\Api', 'middleware' => 'apiauth'], function ($app) {
        $app->group(['prefix' => '/api/v0/users/{id}', 'namespace' => 'App\Http\Controllers\Api', 'middleware' => 'apiauth'], function ($app) {
            $app->patch('roles', ['middleware' => ['load:App\User', 'can:manage roles'], 'uses' => 'UserController@rolesUpdate']);

### Non-working code - middleware array in route group within a route group:

    $app->group(['prefix' => 'api/v0', 'namespace' => 'App\Http\Controllers\Api', 'middleware' => 'apiauth'], function ($app) {
        $app->group(['prefix' => '/api/v0/users/{id}', 'namespace' => 'App\Http\Controllers\Api', 'middleware' => ['apiauth', 'load:App\User']], function ($app) {

### Non-working code - single middleware string on a route within a group with middleware array:

    $app->group(['prefix' => 'api/v0/users/{id}', 'namespace' => 'App\Http\Controllers\Api', 'middleware' => ['apiauth', 'load:App\User']], function ($app) {
        $app->get('things', ['middleware' => 'can:see things', 'uses' => 'UserController@things']);

It does not matter what middleware I choose, adding an array of middleware to a nested route or group definition always fails. It also does not matter what route or group is assigned the middleware array.

## The buggy `Application.php` code that generates this error:

    protected function mergeMiddlewareGroup($action)
    {
        if (isset($this->groupAttributes['middleware'])) {
            if (isset($action['middleware'])) {
                $action['middleware'] = $this->groupAttributes['middleware'].'|'.$action['middleware'];
            } else {
                $action['middleware'] = $this->groupAttributes['middleware'];
            }
        }

        return $action;
    }

## Another strange bug worth noting

When using the following syntax, the middleware classes are suddenly no longer defined.

    $app->group(['prefix' => 'api/v0', 'namespace' => 'App\Http\Controllers\Api', 'middleware' => 'apiauth'], function ($app) {
        $app->group(['prefix' => '/api/v0/users/{id}', 'namespace' => 'App\Http\Controllers\Api', 'middleware' => 'apiauth'], function ($app) {
            $app->patch('roles', 'UserController@rolesUpdate')->middleware(['load:App\User', 'can:manage roles']);

The above results in `ReflectionException in Container.php line 737: Class load does not exist`, despite the fact that it is defined in my bootstrap/app.php file and otherwise works with routing.

    $app->routeMiddleware([ //...
        'load' => 'App\Http\Middleware\LoadResourceMiddleware',
        // ...
    ]);

**Comment by GrahamCampbell** [comment]
Thanks for reporting, but please report lumen issues on the lumen repo.

> When nesting route groups in Lumen

Lumen actually doesn't support nested groups.

**Comment by k98kurz** [comment]
The Lumen repo does not have an issues section, so reporting them there is not possible.

Also, if it does not support that, then why does the documentation not say so?

**Comment by GrahamCampbell** [comment]
Yes it does? https://github.com/laravel/lumen-framework/issues

**Comment by k98kurz** [comment]
Ah, I see. The one not linked to in any documentation. Got it.

The one that the lumen.laravel.com site links to is https://github.com/laravel/lumen, which does not have a tracker and does not explain where to report issues.

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/lumen is the equlivlent of https://github.com/laravel/laravel.

**Comment by k98kurz** [comment]
Like so many other things Laravel, obfuscation is an art even with the bug reporting system, I suppose. Perhaps I should have done a mental regex to convert links from the Laravel documentation into Lumen equivalents for issue tracking.
