### ISSUE TITLE
\Illuminate\Foundation\Auth\ResetPasswords enumeration and refactor

### ISSUE THREAD

**Issue by EliasZ** [laravel/framework#11559]
#9658 already discussed this but was closed and apparently comments on closed issues are not considered, so creating one anew

- [ ] enumeration

It is kind of a weird default implementation to allow email address pinging (enumeration). For example, OWASP (for what it's worth) [states the following](https://www.owasp.org/index.php/OWASP_Periodic_Table_of_Vulnerabilities_-_Insufficient_Password_Recovery):

>The reset form should not expose an account enumeration vulnerability

An answer over at Security SE explains the potential attack vector: "[hypothetical yet very plausible scenario](http://security.stackexchange.com/a/42873)".

- [x] odd behavior (UX) (fixed by #11585)

On a related note, it is also odd that in the reset process, when filling in a reset (`reset` method), it is expected that the request should contain the email address of which the password is being changed. With solely the token - which could very well be unique - the email address can be retrieved from the database. It feels kinda redundant when you receive such a token in your email inbox, you still have to fill in your email address. 

I have not yet come across a reset password process where after following a tokenized URL, I still had to fill in my email address.

<sup>Yes, from a security standpoint, without email confirmation, you could *potentially* brute force a 32 character random token to find active "password resets" and hijack said account without knowing the email address associated. And yes, I am aware the implementation can be changed at application level. Just think that it is beneficial for all users to have a sane default implementation.</sup>

<sup>This issue can be circumvented by not stating for which email address/user you are resetting the password (thinking about it, automatic login should be disabled then as well - given the odds of brute forcing the token I personally don't consider this a threat).</sup>

- [ ] refactor

The boilerplate is very specific. You cannot change the behavior of `reset` without checking the response returned or completely duplicating all of the code and hand tailoring it.

For example, if you wish to modify what happens after `reset`, you currently have two options:

- call `reset`, store the controller action its response and then verify what to do based on which session data is set (`status`, which is already a translated string or whether the session has errors)
- copy all the code of `reset` over and write your own implementation

For example, in an application, wanting to modify the `ResetsPasswords` trait its behavior, we had to do this:

    use ResetsPasswords;

    public function postEmail(Request $request, Store $session)
    {
        $response = $this->sendResetLinkEmail($request);

        if ($session->has('status')) {
            $this->notification->info(PasswordBroker::RESET_LINK_SENT);
        }

        return $response;
    }

    public function postReset(Request $request, Store $session)
    {
        $response = $this->reset($request);

        if ($session->has('status')) {
            $this->notification->info(PasswordBroker::PASSWORD_RESET);
        }

        return $response;
    }

Wouldn't it make more sense if the action (like `reset` and `sendResetLinkEmail`) would return the result of the `PasswordBroker` and the actual controller action would form the response based on that? So it is easier to customize the behavior.

This also affects #11335 - in terms of it being hard to modify as the proposed `VerifiesEmails` trait has all logic-executing code [in one method](https://github.com/tjbp/framework/commit/3d3a5bb041bdd2171bf6e381fc30021e82b3e039#diff-486a52a064bc4b5cae64d2085549bf2fR28).

**Comment by dwightwatson** [comment]
Perhaps the email that is sent to you to reset your password could also include the email address encoded in the link. That way the form can automatically pre-populate the email address in the form so people legitimately changing their password aren't hassled. 

The odds of brute-forcing a reset token are low, but if your app gets big enough or important enough then there will be people who try it. Requiring the reset token AND the correct email address makes this significantly harder to do.

**Comment by EliasZ** [comment]
@dwightwatson I have just checked with Twitter and I didn't look that deep into it, but their password reset link does introduce a few other parameters other than an unique token but does not require you to supply an email address or even an account name (it can also be found in the tokenized URL).

I didn't do the math, but I think it's a safe assumption that brute forcing a 64 character random token over HTTP cannot be considered an attack vector. Even if it is, the base implementation can easily be modified if you reach the scale and sensitivity of "app gets big enough or important enough ". The reset logic can be extended and for example introduce another unique identifier which increases the brute force complexity drastically.

I do agree with you that it is also an option to modify the default behavior, including the email address as a parameter in the tokenized URL and auto filled in the form when possible.

**Comment by phroggyy** [comment]
I'd include an encoded version of the email in the url parameters. Such as a simple `base64_encode($email)` if just for obfuscation (then you could of course salt it or whatnot if you want to make it more difficult)

**Comment by dwightwatson** [comment]
Instead of base64 it might be better to use the encrypter provided by Laravel, which I believe uses the app key to make it harder to decrypt.

**Comment by sumityadav** [comment]
Can we introduce Throttling to prevent the brute force attack and not tweaked the logic (that is already there) and keep it simple with using the token?

**Comment by EliasZ** [comment]
@sumityadav Note that as per #11585 the logic has already been changed (non-breaking, email can now be passed as a query parameter).

As per default implementation supplied by the framework, I don't think throttling is a necessity for password resets. It is a random 40 character token. If you are inclined, it is fairly straightforward to use the `RateLimiter` and build this functionality on your own. The `ThrottlesLogins` trait is a good start to see how it is done for logins.

But asking the framework maintainers is a safer bet than going with my opinion.

**Comment by GrahamCampbell** [comment]
Feel free to keep discussing this here, or in slack, or wherever, but closing since it's not a bug, and we don't process proposals on GitHub.
