### ISSUE TITLE
[5.2] TokenRepositoryInterface is not bound 

### ISSUE THREAD

**Issue by rodrigopedra** [laravel/framework#11555]
In 5.1 if you run this command on tinker:

~~~php
app()->make('Illuminate\Auth\Passwords\TokenRepositoryInterface');
~~~

The IoC container would instantiate the correct concrete class.

In 5.2 it outputs this error:

~~~
ReflectionException with message 'Class auth.password.tokens does not exist'
~~~

I tried to fix the error, but didn't have success. It seems that this issue has something to do with the new multi-auth architecture.

On my app I am binding the concrete class (`DatabaseTokenRepository`) directly on the `AppServiceProvider`.

**Comment by GrahamCampbell** [comment]
Thanks for reporting. Ping @taylorotwell. The `auth:clear-resets` command is also broken.

**Comment by taylorotwell** [comment]
Hey @rodrigopedra,

Yeah I can see how this would be an issue in 5.2. Can you tell me your use case for wanting to access the token repository directly?

@GrahamCampbell auth:clear-resets is fixed now.

**Comment by rodrigopedra** [comment]
Hi @taylorotwell ,

I used it to let the user change the password whille logged in without the need to send the reset e-mail.

As the `ResetsPasswords@postReset` method requires the `token` field, I injected the  `TokenRepositoryInterface` to generate the token for the `auth.reset` view:


~~~php
    public function getReset( $token = null )
    {
        if (auth()->guest() && is_null( $token )) {
            return $this->getEmail();
        }

        if (auth()->check() && is_null( $token )) {
            $token = $this->tokenRepository->create( auth()->user() );
        }

        return view( 'auth.reset' )->with( 'token', $token );
    }
~~~

**Comment by taylorotwell** [comment]
You can get an instance of the token repository via
Password::getRepository().

**Comment by rodrigopedra** [comment]
ok, thanks!

**Comment by lukebro** [comment]
The `getRepository` method is protected so it gives me a 

`call_user_func_array() expects parameter 1 to be a valid callback, cannot access protected method Illuminate\Auth\Passwords\PasswordBroker::getRepository()`.

Any other way to get the token repository?

**Comment by taylorotwell** [comment]
It's not protected: http://d.pr/i/1jwTI/4fvqZTRv

**Comment by lukebro** [comment]
@taylorotwell yup, sorry for that.  Mine was still protected, all fixed now thank you so much. :)
