### ISSUE TITLE
Eloquent Relationship Events

### ISSUE THREAD

**Issue by IsraelOrtuno** [laravel/framework#11557]
It might be great to keep Eloquent relationships under control with some events such as:

```php
class RelationLoaded {

    public $model;
    public $relation;

    function __construct($model, $relation)
    {
        $this->model = $model;
        $this->relation = $relation;
    }
} 
```

Any thoughts?

**Comment by GrahamCampbell** [comment]
Thank you very much for getting in touch, but as per our contribution docs, we don't process proposal issues on GitHub. Feel free to ask for feedback on slack, and/or create a partial PR to serve as a proposal.
