### ISSUE TITLE
Validation rule: time

### ISSUE THREAD

**Issue by krzystof** [laravel/framework#11568]
Would it be interesting to implement a validation rule that would check if the input can be parsed to a time.

The following would return true:
- 8
- 20
- 8:00
- 08:00

I can submit a PR if this is something you would be willing to add.

**Comment by Sladewill** [comment]
Why not just use date_format:H:i?

**Comment by GrahamCampbell** [comment]
Thanks, but we don't process proposal issues as described in our docs.
