### ISSUE TITLE
Empty CSRF-Token on Laravel 5.2

### ISSUE THREAD

**Issue by Jasperrr91** [laravel/framework#11564]
Both the csrf_token() and csrf_field() functions/helpers are returning an empty value on a fresh Laravel 5.2 installation.

**Comment by crynobone** [comment]
Are you sure the route you're accessing uses `StartSession` middleware?

**Comment by danharper** [comment]
On a fresh install, make sure your route is within `web` middleware group 

```php
<?php

Route::get('foo', function () {
    return csrf_token(); // null
});

Route::group(['middleware' => 'web'], function () {
    Route::get('bar', function () {
        return csrf_token(); // works
    });
});
```

Otherwise the `StartSession` middleware [isn't loaded](https://github.com/laravel/laravel/blob/master/app/Http/Kernel.php#L29) and so no token exists on the session.

**Comment by irfanwv** [comment]
I am also faced same Issue? Above solutions are not worked.

**Comment by Jasperrr91** [comment]
Are you sure you're using Laravel 5.2 and your route is in the Web middleware group? `csrf_token();` should work then. Make sure the StartSession class is present in the middleware group in your Kernel:
```php
protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
        ],
    ];
```

**Comment by irfanwv** [comment]
Yes, I am using same code

**Comment by Jasperrr91** [comment]
What happens when you try out Dan's test routes? Does `/bar` give you an empty page as well?

**Comment by irfanwv** [comment]
Only Blank screen, Nothing happend

**Comment by rabbitns** [comment]
me too ,just return null !! why?

**Comment by AMABK** [comment]
Both get and post for that view should be under web middleware

**Comment by kannratha** [comment]
# [](url)
