### ISSUE TITLE
Laravel 5.2 json type migration error

### ISSUE THREAD

**Issue by fsyauqy** [laravel/framework#11577]
I cannot migrate a table with a json type in Laravel 5.2.
Always a syntax error occured during migration.
Tried it in 5.1 and it works.
Any idea?

```
Schema::create('test', function (Blueprint $table) {
    $table->increments('id');
    $table->json('options');
});
```

**Comment by GrahamCampbell** [comment]
Thanks, but this is not a bug, and is documented in our upgrading guide.

**Comment by GrahamCampbell** [comment]
Using `->json` requires mysql 5.7 or greater, if you're using mysql, starting from laravel 5.2.0.

**Comment by GrahamCampbell** [comment]
Basically, we're now using the actual json type rather than the text fallback we used to use in 5.1.
