### ISSUE TITLE
.env does not parse spaces in variables

### ISSUE THREAD

**Issue by viraj-khatavkar** [laravel/framework#11589]
my .env had a variable with spaces in between

`VARIABLE_NAME=abc def ghi`

With Laravel 5.1, it had a 1.0.* version and everything was working fine, but, when I upgraded to Laravel 5.2, it returns null for above variable.

**Comment by crynobone** [comment]
```
VARIABLE_NAME="abc def ghi"
```

**Comment by viraj-khatavkar** [comment]
@crynobone :)

**Comment by locojuhi** [comment]
I know this is and old question... but what happend with the (+) sign... it seens scaping

**Comment by onekit** [comment]
And then if you use it in TWIG templates, then use something like `variableName|trim('"')`
