### ISSUE TITLE
Proposal: php artisan make:auth will change redirectTo in AuthController to /home

### ISSUE THREAD

**Issue by acacha** [laravel/framework#11580]
Hello,

Maybe I'm wrong but in my opinion it seems more logical:

- Default layout have two links to same place (/). As I proposed in https://github.com/laravel/framework/pull/11579 it seems better to me Home link in navigation bar points to /home
- Then (I don't know exactly how sorry) change redirectTo in AuthController to /home
- Welcome page not showing login and register when user is logged. Welcome page uses same layout as home page but welcome page is not in web middleware group so never the user will be authenticated is a bit odd behaviour in my opinion

**Comment by SpiralOutDotEu** [comment]
Totally agree with you acacha. see my pull request: [#11635](https://github.com/laravel/framework/pull/11635) for a complete solution.
