### ISSUE TITLE
HtmlBuilder

### ISSUE THREAD

**Issue by alesl** [laravel/framework#11583]
Not sure if this is correct place to post this issue, but it seems to me url should be escaped here:
https://github.com/illuminate/html/blob/master/HtmlBuilder.php#L115

```php
return '<a href="'.$this->entities($url).'"'.$this->attributes($attributes).'>'.$this->entities($title).'</a>';
```

**Comment by thecrypticace** [comment]
The `illuminate/html` package is no longer supported.
Use `laravelcollective/html` instead.

Documentation is located here: https://laravelcollective.com/docs/5.2/html
