### ISSUE TITLE
[5.1] [5.2] Database reads fail when write connection is down

### ISSUE THREAD

**Issue by stevenmyhre** [laravel/framework#11586]
The separate read/write database connections are great, but it seems like the main potential benefit of them is completely left out.

Simply put, anytime a read is done, connections are opened on BOTH the read & write servers.  I would expect that the write connection would only be opened if you are doing an insert/update or are currently within a transaction (read from write connection while in a transaction).

My use case:

I have multiple database slaves and one master.  If the master goes down, I would like the slave(s) to still remain operational from a read perspective.  (each slave can read from its current copy but writes would fail, as they would be redirected to the master)

Even if the master is up, it still slows down reads on any slave server, since, before executing any SQL on the read connection, the write connection is opened.  In most replication scenarios, the write connection would be more expensive to open, with higher latency.  Therefore, this superfluous connection is adding time to each request.

I've seen a couple other issues that have been closed, but cannot find any branch this has been fixed.  The read & write connection branching logic seems tightly coupled to a single "Connection" instance, so I'm not sure how you'd want to refactor this.

**Comment by stevenmyhre** [comment]
Related issues: #9151, #10337

**Comment by GrahamCampbell** [comment]
Is it the instantiation of a PDO instance that makes the actual db connection?

**Comment by GrahamCampbell** [comment]
If so, we could just refactor the connection class to accept a closure that creates the pdo class lazily instead.

That's breaking and would need to be targetted at 5.3 though.

**Comment by stevenmyhre** [comment]
Yes, the instantiation of the PDO instance kicks off the connection.  There is a ConnectorInterface that looks like it's just the "closure" we're looking for.  What makes this a breaking change?  The Connection objects are only instantiated internally, right?

**Comment by GrahamCampbell** [comment]
It's still a breaking change. Anyone mocking the connection object will be screwed over if we change the constructor definition.

**Comment by stevenmyhre** [comment]
Gotcha.  Guess I'll be forking the 5.1 branch then.  I can send a pull request if it's helpful.

**Comment by GrahamCampbell** [comment]
Please send one to 5.3. We'll have to be careful we really do address all places where this is a potential issue though.

**Comment by stevenmyhre** [comment]
By 5.3 do you mean master at this point?

**Comment by GrahamCampbell** [comment]
Yes. :)

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/blob/master/composer.json#L95
