### ISSUE TITLE
[5.2] ThrottleRequests middleware throw exception when using Symfony response

### ISSUE THREAD

**Issue by lialosiu** [laravel/framework#11587]
I using `\Illuminate\Routing\Middleware\ThrottleRequests` middleware to handler API router.

And my API have some method return `response()->download()`  use to show show picture or download files.

After I upgrade to Laravel 5.2, I got the exception:

`Fatal error: Call to undefined method Symfony\Component\HttpFoundation\BinaryFileResponse::withHeaders()`

It look like ThrottleRequests middleware can't process the Symfony response, because Symfony response do not have method `withHeaders()` to set headers

**Comment by phroggyy** [comment]
`withHeaders` is a method of `Illuminate\Http\ResponseTrait`. This means that, to use `ThrottleRequests`, you **must** use an Illuminate response.

**Comment by lialosiu** [comment]
well, I try to extends the ThrottleRequests and override handle method like this 

```php
    public function handle($request, Closure $next, $maxAttempts = 60, $decayMinutes = 1)
    {
        $key = $this->resolveRequestSignature($request);

        if ($this->limiter->tooManyAttempts($key, $maxAttempts, $decayMinutes)) {
            return new Response('Too Many Attempts.', 429, [
                'Retry-After'           => $this->limiter->availableIn($key),
                'X-RateLimit-Limit'     => $maxAttempts,
                'X-RateLimit-Remaining' => 0,
            ]);
        }

        $this->limiter->hit($key, $decayMinutes);

        $response = $next($request);
        $response->headers->set('X-RateLimit-Limit', $maxAttempts);
        $response->headers->set('X-RateLimit-Remaining', $maxAttempts - $this->limiter->attempts($key) + 1);

        return $response;
    }
```

It work no problem with Symfony response now :)

**Comment by lagbox** [comment]
Seems perhaps the throttle middleware should just be adjusted to not use `withHeaders`. If that method is just a convenience method, it shouldn't be an issue to not use it here.

An issue I had earlier was resolved with a recent commit, but I am not sure if everything can be changed to an Illuminate Response so easily.

**Comment by GrahamCampbell** [comment]
Please could you send a PR to fix compatibility with a symfony response?

**Comment by lagbox** [comment]
sure

**Comment by quanhub** [comment]
Same problem here! 

"Type error: Argument 1 passed to Illuminate\Routing\Middleware\ThrottleRequests::addHeaders() must be an instance of Symfony\Component\HttpFoundation\Response, null given, called in /vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php on line 61"
