### ISSUE TITLE
Xdebug not installed at Laravel Homestead 4.0

### ISSUE THREAD

**Issue by acacha** [laravel/framework#11594]
As far as I known Xdebug is installed at previous versions of Laravel Homestead. I don't know if this is a bug or anything else because I haven't found any docs about this.

For whom it may concern I achieve to install manually with this commands:

http://acacha.org/mediawiki/Homestead#Laravel_Homestead_4.0_amb_PHP_7

I've used http://xdebug.org/wizard.php with some litle changes

**Comment by GrahamCampbell** [comment]
Thanks, but this is by design. xdebug was removed from the default box now.

**Comment by acacha** [comment]
@GrahamCampbell Ok thanks for the info!

**Comment by jonagoldman** [comment]
I just can't get it to work.
I installed and configured Xdebug 2.4.0rc3 following the [docs] (http://xdebug.org/docs/install).
I see the extension in phpinfo() and PhpStorm recognizes the remote debugger, but I can't get it to listen and stop on breakpoints.

The problem is that Xdebug seems to be installed as a PHP extension, instead of a Zend Extension, wich is strange as I configured ```zend_extension="/usr/.../xdebug.so"```.

Any ideas?

**Comment by jjeaton** [comment]
@GrahamCampbell are you able to share the reasoning behind removing xdebug by default? Solely for our curiosity. :) Is there meant to be a replacement developers should be using?

**Comment by GrahamCampbell** [comment]
I think it's because it's not stable yet. For example, my app segfauls on php 7 with code coverage enabled when running phpunit.

**Comment by jjeaton** [comment]
@GrahamCampbell Thanks for the info! So there is a chance that future iterations will include xdebug once it's stable with PHP7?

**Comment by GrahamCampbell** [comment]
It's not really up to me. It's up to Taylor to decide if and when he wants to put it back in.

**Comment by jonagoldman** [comment]
Is it possible at least to put a short step by step list on configuring Xdebug with Homestead 4?

**Comment by jjeaton** [comment]
FWIW, I was able to get it running following these instructions: http://gilbert.pellegrom.me/setting-up-xdebug-on-homestead-4-php-7/ Although that feels pretty fragile, as it won't stick around if I need to `vagrant destroy` for any reason.

**Comment by jonagoldman** [comment]
:+1: @jjeaton
