### ISSUE TITLE
[5.1] [5.2] Event Dispatcher forget doesn't clean up the wildcard listeners.

### ISSUE THREAD

**Issue by Asarew** [laravel/framework#11598]
So the title says it all i think. when ever you register a listener with a wildcard and try to the forget this wildcard listener using the same event key, the listener is still being fired.

```php
Event::listen('foo.bar', function()
{
	echo 'foo.bar (without wildcard)' . PHP_EOL;
});

Event::listen('foo.*', function()
{
	echo 'foo.bar (with wildcard)' . PHP_EOL;
});

Event::fire('foo.bar');
// foo.bar (without wildcard)
// foo.bar (with wildcard)

Event::forget('foo.bar');
Event::forget('foo.*');

Event::fire('foo.bar');
// foo.bar (with wildcard)
```
Is this intended behaviour or might this be a bug?

**Comment by GrahamCampbell** [comment]
What laravel version please?

**Comment by Asarew** [comment]
I'm runing 5.1 but it's also in the master branch and version 5.2

**Comment by GrahamCampbell** [comment]
Thanks for the report.

**Comment by GrahamCampbell** [comment]
Closing due to https://github.com/laravel/framework/pull/11603.
