### ISSUE TITLE
in migrations, class name conflicts should be resolved during registering phase

### ISSUE THREAD

**Issue by UnrulyNatives** [laravel/framework#11595]
While still working on 5.1, I stumbled upon some isssue with migrations. 

Step 1
I created migration with name `2015_11_28_095622_add_columns_to_inquiries_table`. A migration file was generated: `2015_11_28_095622_add_columns_to_inquiries_table.php`. Then i ran the migration.

Step 2
Then I decided to add new columns, so I just created another migration with EXACTLY the same command and ran the migration. The file generated had name `2015_11_28_095622_add_columns_to_inquiries_table`

The class name in BOTH files were exacly the same: `AddColumnsToInquiriesTable`

THE OUTCOME:
On my local server on Win7 the two migrations worked fine. On production server (Linux 14.4, Digital Ocean standard droplet), however, I got this:

`[Symfony\Component\Debug\Exception\FatalErrorException] Cannot redeclare class AddColumnsToInquiriesTable`

this issue made reverting the last migration (the one with duplicate class) impossible.

Suggestion: in migrations, class name conflicts should be resolved during registering phase

**Comment by GrahamCampbell** [comment]
This isn't really a bug. Just be careful when naming your migrations.
