### ISSUE TITLE
Error in dispatching Job Classes from request [dispatchFrom]

### ISSUE THREAD

**Issue by viraj-khatavkar** [laravel/framework#11590]
When I updated to 5.2, I am getting an error when my app is dispatching job classes

`"Method [dispatchFrom] does not exist."`

**Comment by crynobone** [comment]
![screen shot 2015-12-29 at 4 27 56 pm](https://cloud.githubusercontent.com/assets/172966/12031625/2ab77b50-ae49-11e5-9fe1-6a2f60c093c6.png)

https://laravel.com/docs/5.2/upgrade#upgrade-5.2.0
