### ISSUE TITLE
[5.2] TokenRepositoryInterface is not bound

### ISSUE THREAD

**Issue by MateEke** [laravel/framework#11605]
I have the same issue as in [#11555](https://github.com/laravel/framework/issues/11555)

@taylorotwell gave this answer:
>You can get an instance of the token repository via
>Password::getRepository().

But the getRepository() function is protected, and I don't know how to use it.

I used the TokenRepositoryInterface in my AuthController to create user activation tokens, the same way as the built in password reset method.

**Comment by GrahamCampbell** [comment]
> But the getRepository() function is protected, and I don't know how to use it.

No, it's not.

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/blob/5.2/src/Illuminate/Auth/Passwords/PasswordBroker.php#L249

**Comment by MateEke** [comment]
@GrahamCampbell I have installed the latest version with composer today, and the getRepository function protected in my file. Strange.

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/commit/d06899de5b6d7a6d1dbd37bc06e4566e1e25040f

**Comment by GrahamCampbell** [comment]
Indeed it's still protected in the latest stable release. I'd recommend not using dev stability globally

**Comment by GrahamCampbell** [comment]
You'll have to use `5.2.*@dev` until this is included in the next release.

**Comment by MateEke** [comment]
Ok, now it's public, but the suggested method still doesn't work
`$token = Password::getRepository()->create($user);`

>ErrorException in AuthController.php line 214:
>Non-static method Illuminate\Auth\Passwords\PasswordBroker::getRepository() should not be called statically, assuming $this from incompatible context

**Comment by MateEke** [comment]
Please provide a solution to use TokenRepositoryInterface, I don't want to reimplement it's functionality...

**Comment by taylorotwell** [comment]
Will look into it in a few minutes.

**Comment by taylorotwell** [comment]
`dd(Password::getRepository());` works for me. Don't import the full class,
just use the facade.

**Comment by MateEke** [comment]
@taylorotwell Thank you very much, this way it works!
