### ISSUE TITLE
HasMany returning trashed models

### ISSUE THREAD

**Issue by andrioli** [laravel/framework#11601]
Actually, IDK if this is a feature or a bug.

I have two models (ModelA, ModelB). ModelA has many ModelB. Both are SoftDelete.

I setup the relationship as the doc says, e.g:

```php
class ModelA extends Model
{
    use SoftDeletes;

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];
 
    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany|\Illuminate\Database\Eloquent\Builder
     */
    public function models()
    {
        return $this->hasMany(ModelB::class);
    }
}

class ModelB extends Model
{
    use SoftDeletes;

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];
}
```

The possible "problem" is: I'm trying to soft delete all ModelBs belonging to a instance of ModelA ($modelA) at once.

If I get the collection of objects (i.e., `$modelA->models`) only the not deleted objects are returned (`deleted_at = NULL`) . But if I call the method (i.e., `$modelA->models()`) the deleted objects are included in the query and soft deletes don't work.

Example:

My first attempt was: `$modelA->models()->delete()`. But it  force delete all ModelBs belonging to `$modelA`.

Second attempt was `$modelA->models()->update(['deleted_at' => Carbon::now()])`. It also updates the already deleted ModelBs belonging to `$modelA`. I was expecting this to be something like `$modelA->models()->withTrashed()->... `

Finally, my solution was `$modelA->models()->where('deleted_at', null)->update(['deleted_at' => Carbon::now()])`. IMO this is too cumbersome.

This is the expected behaviour?

**Comment by GrahamCampbell** [comment]
What laravel version please?

**Comment by GrahamCampbell** [comment]
If you are overring the boot method, are you remember to call the parent?

**Comment by andrioli** [comment]
The Laravel version that I was trying is 5.2 and I don't override the boot method.

**Comment by GrahamCampbell** [comment]
> My first attempt was: $modelA->models()->delete(). But it force delete all ModelBs belonging to $modelA.

Does it even delete those that were already soft deleted?

**Comment by andrioli** [comment]
@GrahamCampbell yes, it deletes all

**Comment by GrahamCampbell** [comment]
What about `$modelA->models()->each(function ($model) { $model->delete(); });`?

**Comment by GrahamCampbell** [comment]
What version of 5.2 are you using btw. My last code example will only work on `5.2.*@dev`.

**Comment by andrioli** [comment]
I was on 5.2.0. Just updated to 5.2.5 and works fine :+1:
