### ISSUE TITLE
Introducing more Interfaces/Contracts

### ISSUE THREAD

**Issue by stefanbauer** [laravel/framework#11611]
Here is the short version: Is there any reason why Laravel provides not much Interfaces? If no, is it an idea to provide much more? For instance for the EventSubscriber. I would like to see much more interfaces, because it makes it much easier 

a) to code against these interfaces
b) to know what to implement
c) to read. For me it is enough to read the interfaces, to understand what happens

If there is any interest, let me know. I could do also some work on it. I wanted just discuss this stuff before doing anything which is not wanted.

Long version/discussion can be found here https://laracasts.com/discuss/channels/laravel/missing-a-lot-of-interfacescontracts

Smaller hint/question: Is there any special reason why the interfaces are in contracts directory and are "named" like implementations? I find it hard to read during development. For DI i think it is more readable if there is a xxxInterface to see immediately an interface is expected and not the implementation.

**Comment by GrahamCampbell** [comment]
Laravel provides interfaces only where someone might actually want to swap out code for their own implementation.

**Comment by stefanbauer** [comment]
That's it? That's the reason? Very short-term thinking. With such a reason, you jettison all the knowledge about (professional) architecture and great software design from every other developer out there. For me, that is no constructive reason/valid argument, sorry. I thought there will be "more" or at least a more technical reason. This reason seems so "It is how it is. It has no reason, but accept it or go".

**Comment by GrahamCampbell** [comment]
If anything, we were thinking about removing some more of the contracts. Like, the application contract seems a little silly to me.

**Comment by GrahamCampbell** [comment]
Abstraction for the sake of abstraction is silly. You mentioned the long term. We can just change our code in the long term. Every 6 months laravel makes releases with breaking changes.

**Comment by GrahamCampbell** [comment]
> you jettison all the knowledge about (professional) architecture and great software design from every other developer out there. 

That's simply not true.

**Comment by GrahamCampbell** [comment]
Interfaces for various technical reasons make life hard for a framework like laravel. Adding new methods or new parameters to methods becomes a major breaking change. If interfaces are so magic for everyone, then symfony would be all over them, but they;re not, and for good reason.

**Comment by GrahamCampbell** [comment]
I hope I've better answered your question.

**Comment by stefanbauer** [comment]
Graham, please don't get me wrong. It was not personally. Sorry if u got the feeling. I was just disappointed about the short answer "it is how it is". This is something i am not used to from you guys.

Abstraction for the sake of abstraction is silly. 100% agree!

> make life hard for a framework like laravel
But this was the only answer i hoped to get. That in general it is not impossible but for a framework like laravel and their target group, it makes the life harder.

But when we are talking right now about such stuff... What is about the laravel events which laravel fires? As i mentioned in the post, i find it hard to find the information which events do exist. There is no official documentation about it and it would be cool (in my eyes) that there are event classes that hold some constants for different events that can easy be accessed from everywhere and it is ensured that maintaining is easier because developer are using these constants. Or is that also just a "it is how it is"? and that makes laravel life hard :)

**Comment by GrahamCampbell** [comment]
> That in general it is not impossible but for a framework like laravel and their target group, it makes the life harder.

Making life harder for the framework in this case is making upgrading harder for the consumers.
