### ISSUE TITLE
str_slug function ascii character problem

### ISSUE THREAD

**Issue by kaptanblack** [laravel/framework#11619]
Hi,

I have a problem with ascii characters on laravel 5.2.5 (in Turkish)

(I know 5.2 don't use Stringy)

str_slug('özgür karagöz') => 'oezguer-karagoez'

it must be;

str_slug('özgür karagöz') => 'ozgur-karagoz' (laravel 5.1)

For example in Turkish Language:

'Ö'  => 'O',
'ö' => 'o',

in German or etc

'Ö'  => 'OE',
'ö' => 'oe',

**Comment by GrahamCampbell** [comment]
What does laravel 5.1 do with the latest version of stringy?

**Comment by GrahamCampbell** [comment]
5.2 does use stringy's code. We just copied over the small part of stringy we actually needed and dropped the dependency.

**Comment by kaptanblack** [comment]
Laravel 5.1 Stringy Version: "danielstjules/stringy": "~1.8"

Actually, this problem Stringy's problem too :)

The latest version of danielstjules/stringy same problem too.

Slugify method must run by locale.

**Comment by GrahamCampbell** [comment]
Ok then, consider this a breaking change then, but not a bug.

**Comment by GrahamCampbell** [comment]
If you would like this changed, please send a PR to stringy, and we'll update our code to match what they do each time then tag a release.

**Comment by blackfyre** [comment]
@ozgurkaragoz You can refer to my blog article on how to fix this issue: https://blackfyre.ninja/blog/fixing-slug-generation-problems
