### ISSUE TITLE
[Authentication] - Route::get('/logout', 'AuthController@getLogin' not works

### ISSUE THREAD

**Issue by romarioliveira25** [laravel/framework#11613]
Hi,

In my studies about this great framework, I've come across with an issue related to authentication, more specifically, the logout() method.

Well, what happens is, when I created an route to the logout method (Route::get('/logout', 'AuthController@getLogout', what would should call the function logout() at the trait AuthenticatesUsers), not worked fine. BTW, in an test, I tried creating the route again, but call directly de method logout() (Route::get('/logout', 'AuthController@logout) and it, YEP, works fine.

So, no very happy with this, I stayed curious to know the cause of this issue, and checking the class controller 'AuthController' could see it : 

    public function __construct()
    {
        $this->middleware('guest', ['except' => 'logout']);  //
    }

At the construct function, the values of the middleware related with exception were defined as 'logout', when I changed it to 'getLogout' everything worked fine also!

I don't know if it's an know issue, or if really is an issue (I'm starting with Laravel :-P), anyway I hope it can helps.

**Comment by GrahamCampbell** [comment]
Feel free to ask questions on the forums.
