### ISSUE TITLE
[5.1] Error with Route Patterns and named routes.

### ISSUE THREAD

**Issue by pjebs** [laravel/framework#11622]
[pseudo code]

Route::pattern('domain', 'hello.com');
$domain = '{domain}';

Route::group(['domain' => 'oauth.' . $domain], function()
{

    Route::match(['get', 'post'], '/route', ['middleware' => 'csrf', 'as' => 'name', 'uses' => 'Controller@route']);

});

**Comment by pjebs** [comment]
`route('name')` results in http://oauth.{domain}

**Comment by pjebs** [comment]
route('name') should resolve to http://oauth.hello.com

But the actual ROUTING works perfectly (subject to https://github.com/laravel/framework/issues/11538)

**Comment by GrahamCampbell** [comment]
I think this is actually correct.

**Comment by pjebs** [comment]
@taylorotwell  Is this correct behaviour?

Shouldn't route('X') resolve to the actual name of route?

**Comment by pjebs** [comment]
We certainly can't use the route() command to generate links.

**Comment by taylorotwell** [comment]
Eh, no that's not really how `pattern` works. Pattern is to limit the incoming request URIs to a given regular expression. You need to do `route('name', ['domain' => 'value']);` to generate the URL.

**Comment by pjebs** [comment]
thanks
