### ISSUE TITLE
Removal of router helper functions not mentioned in upgrade guide to 5.2

### ISSUE THREAD

**Issue by felixkiss** [laravel/framework#11629]
See https://github.com/laravel/framework/commit/62cbae78ba2d40944892c5a16f2d2463087bce23#commitcomment-15116643

**Comment by GrahamCampbell** [comment]
We'd accept a PR to add it under the existing `Helper Functions` header.

**Comment by GrahamCampbell** [comment]
on https://laravel.com/docs/5.2/upgrade.
