### ISSUE TITLE
Object of class Illuminate\Routing\UrlGenerator could not be converted to string laravel 5.2 Error 

### ISSUE THREAD

**Issue by umairali** [laravel/framework#11638]
I install new laravel 5.2 project and i m facing this error on URL() code. Please suggest any thing.

![capture](https://cloud.githubusercontent.com/assets/5318005/12062170/36769fcc-afb9-11e5-98d4-3298b8c7711f.PNG)

**Comment by crynobone** [comment]
See #11479

**Comment by anuj-know** [comment]
use {{ url('/')}}
