### ISSUE TITLE
Class 'Input' not found laravel 5.2

### ISSUE THREAD

**Issue by umairali** [laravel/framework#11639]
Class 'Input' not found
Input::get('email');

![capture](https://cloud.githubusercontent.com/assets/5318005/12062253/84ff6c72-afba-11e5-9c0f-e125fc741a35.PNG)

**Comment by mikerockett** [comment]
Input facade is no longer available.

https://laravel.com/docs/5.2/requests#retrieving-input

**Comment by umairali** [comment]
ok now i m trying with 

use Illuminate\Http\Request;

$request->input('email');

now i m facing this error

Undefined variable: request

**Comment by phecho** [comment]
@umairali 
```php
public function postAction(Request $request)
{
    $request->input('email');
}
```

Or

```php
use Illuminate\Support\Facades\Request;

public function postAction()
{
    Request::get('email');
}
```

**Comment by umairali** [comment]
Thanks @phecho 2nd is working

**Comment by GrahamCampbell** [comment]
It was removed from the default aliases in laravel/laravel. Feel free to add it back if you want it.

**Comment by superdummy** [comment]
What are the Reasons for Removing the Input:: facade? I think Taylor did this with a reason, what are the reasons, can someone list/name them? Why is using the $request variable a best practice / better to using the Facade? Thanks.

**Comment by DeeJaVu** [comment]
+1 @superdummy

**Comment by GrahamCampbell** [comment]
You can easily add it back by aliasing the request facade in your app config.

**Comment by DeeJaVu** [comment]
@GrahamCampbell Fixed but you did not answers @superdummy's question

**Comment by GrahamCampbell** [comment]
> @GrahamCampbell Fixed but you did not answers @superdummy's question

As demonstrated by my suggestion, it's not removed.
