### ISSUE TITLE
Decryption is attempted on CSRF token only when passed via X-XSRF-TOKEN

### ISSUE THREAD

**Issue by evictor** [laravel/framework#11633]
See this line of code: https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php#L114

This is odd because decryption will (correctly) not be performed if the CRSF token comes in via other means. The token is sent by default from XSRF-TOKEN by AngularJS via the X-XSRF-TOKEN header, so this arises when using Laravel and AngularJS out of the box.

The token is never encrypted at any point when it is stored in this VerifyCsrfToken.php class, so therefore I think this is just a simple mistake that has surprisingly somehow not been caught until now.

**Comment by crynobone** [comment]
All cookie value will be encrypted by default.

**Comment by evictor** [comment]
Why did you close this? There is a bug. Can you at least click through the link and look at the 2-3 lines of code? It's pretty glaringly obvious.

**Comment by crynobone** [comment]
The reply would be pretty glaringly obvious too, but if it isn't check #7528

**Comment by evictor** [comment]
It's not... Thanks for the additional info.
