### ISSUE TITLE
Is it possible to add support to use postgres functions with DB::raw

### ISSUE THREAD

**Issue by mehany** [laravel/framework#11636]
DB builder does not seem to allow the execution of postgres function in a simple <code>DB::raw </code> call. For example the bellow statement will not execute as is and it will throw an error but if I run the sql statement that gets bound to the error message within PGAdmin3  it will return the expected result.

    \DB::connection('pgsql')
        ->select('SELECT DISTINCT(someColumn) FROM example WHERE ST_Within(ST_SetSRID(ST_Point(?, ?), 900914), wkb_geometry)', array($lon, $lat));

wkb_geometry is a column on the example table. I hope I am missing something! 

P.S
here is the error i get

    SQLSTATE[42883]: Undefined function: 7 ERROR: function st_point(unknown, unknown) does not exist

and the hint:

    HINT: No function matches the given name and argument types. You might need to add explicit type casts. 

generated sql

    SELECT DISTINCT(someColumn) FROM example WHERE ST_Within(ST_SetSRID(ST_Point(-73.996299743652, 40.756053924561), 4326), wkb_geometry)

**Comment by GrahamCampbell** [comment]
It should be. Please direct questions to the forums.

**Comment by mehany** [comment]
@GrahamCampbell This is not a question really, this is an issue where the framework claims to support this while it is not!  I provided above the error message I get! Can you show how to get the above statement to work?

Here is a <a href="https://laracasts.com/discuss/channels/eloquent/how-to-run-raw-sql-with-functions-in-postgres-using-query-builder">question</a> I posted on laracasts a month ago

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell for advice.

**Comment by taylorotwell** [comment]
This doesn't look like a Laravel error. You can see that the generated SQL is valid.

**Comment by GrahamCampbell** [comment]
As I thought. Thanks @taylorotwell.

**Comment by mehany** [comment]
@taylorotwell a month ago I needed to get this to work so I created my own class which makes a connection to a postgres DB and holds some functions such as the bellow:

    public function lat_lon_to_address($lat, $lon){
        $q =  pg_query_params($this->connection,
            "SELECT pprint_addy(r.addy[1]) As st1, pprint_addy(r.addy[2]) As st2, pprint_addy(r.addy[3]) As st3,
            array_to_string(r.street, ',') As cross_streets
        FROM reverse_geocode(ST_GeomFromText('POINT($1 $2)',4269),true) As r",
            array(
                $lat,
                $lon
            ));
        return pg_fetch_row($q);
    }
    
The above function executes successfully. When I try to use eloquent with the above statement, I get errors. When I use <code>pg_query()</code> or <code>pg_query_param</code> it works. Can you explain why? and can you show a working example?
