### ISSUE TITLE
Method [beforeFilter] does not exist. Laravel 5.2

### ISSUE THREAD

**Issue by umairali** [laravel/framework#11640]
i m using beforeFilter to redirect user to login page when session expire but before filter not working in laravel 5.2    

public function __construct()
    {
            $this->beforeFilter(function()
            {
                return Redirect(URL('/') . "/login");
            });
    }

and this error message throw

![capture](https://cloud.githubusercontent.com/assets/5318005/12062459/d4a025d8-afbe-11e5-9840-74ffcb0ce292.PNG)

**Comment by crynobone** [comment]
Deprecated in 5.1 and removed in 5.2

**Comment by mikerockett** [comment]
@umairali - I suggest you read through the documentation for 5.2 - lots of changes, even in 5.1, which now uses [Middleware](https://laravel.com/docs/5.2/middleware), and not Filters.

**Comment by KaneCohen** [comment]
@umairali here you can find descriptions of changes between versions: https://laravel.com/docs/5.2/upgrade

**Comment by umairali** [comment]
ok please me any suggestion for redirection in controller constructor

**Comment by umairali** [comment]
***Solution***

Change 

# My Markdown
public function __construct()
{
$this->beforeFilter(function()
{
return Redirect(URL('/') . "/login");
});
}
```
To
 
# My Markdown
public function __construct()
{
Redirect('login')->send();
}
```

**Comment by GrahamCampbell** [comment]
That's not a correct solution.

**Comment by GrahamCampbell** [comment]
You should never send a response directly in the code, ever.

**Comment by brunoirodriguez** [comment]
http://stackoverflow.com/questions/34475274/replacement-method-in-laravel-5-2

**Comment by brunoirodriguez** [comment]
`http://stackoverflow.com/questions/34475274/replacement-method-in-laravel-5-2`
