### ISSUE TITLE
Postgres pretend mode bug

### ISSUE THREAD

**Issue by rkgrep** [laravel/framework#11641]
PostgresProcessor tries to get undefined offset 0 at [line 24](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Query/Processors/PostgresProcessor.php#L24).
This bug appears when using pretend mode with saving model both in Laravel 5.1 and 5.2

**Comment by GrahamCampbell** [comment]
Pretend mode isn't intended to work for those sorts of queries.
