### ISSUE TITLE
[5.2] Validating array using asterisk (*) against another array field doesn't do anything

### ISSUE THREAD

**Issue by bridgeport** [laravel/framework#11648]
Hi,

Using Laravel 5.2.6, I'm extending the Request class and returning a rule, such as:
```
$rules = [
    'locations.*.phones.*.number' => 'required_with:locations.*.phones.*.phone_type_id',
];
```

When trying to validate a multi-dimensional array field against another multi-dimensional array field using the asterisk (*) approach, it doesn't have any impact. So, it's not clear how to get the following to function if the target field also includes an asterisk:

> required_if
> required_unless
> required_with
> required_with_all
> required_without
> required_without_all

Is this approach not yet supported?

Thanks.

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch.

> Is this approach not yet supported?

I'd have to assume so. Ping @taylorotwell for details.

**Comment by danpastori** [comment]
I have the same issue if a little extra code helps.

If I do an asterisk for a validation rule it doesn't work, but if I add a hard coded index, it works correctly.

Doesn't work:
```
$cafeValidator = Validator::make( $request->all(), [
	'cafes' 			=> 'array',
	'cafes.*.name' 		=> 'required_with:cafes'
]);
```

Works:
```
$cafeValidator = Validator::make( $request->all(), [
	'cafes' 			=> 'array',
	'cafes.0.name' 		=> 'required_with:cafes'
]);
```

If any more code is needed from me let me know!

**Comment by themsaid** [comment]
This is a proposed fix https://github.com/laravel/framework/pull/11927

**Comment by taijuten** [comment]
Although that fix has been merged, I'm still finding this issue, and this issue remains open. Can anyone else confirm that this isn't fixed in all cases?

I'm trying to use the `before` and `after` validation on dates, as part of an array input.

		$validator = Validator::make(
			$request->all(),
			[
				'sessions'			=> 'required | array',
				'sessions.*.id'			=> 'sometimes | integer | exists:sessions,id,event_id,'.$event->id,
				'sessions.*.title' 		=> 'required',
				'sessions.*.starts' 		=> 'required | date | before:sessions.*.ends',
				'sessions.*.ends' 		=> 'required | date | after:sessions.*.starts'
			]
		);

**Comment by rela589n** [comment]
I have another issue.
```'q.new.*.v.*.text' => [
        'required',
        'min:2',
        'max:128',
]```
That works and i can see errors in my form, but when i add new `q.new.*.v` item and send form, this element is not flashed to the storage, and i can't access it using `old()` function.

**Comment by AymanElshehawy** [comment]
https://stackoverflow.com/questions/60279464/validate-field-value-against-another-with-arrays-in-laravel/60281129#60281129
