### ISSUE TITLE
[5.2] Implicit model bindings with plurally named resource routes

### ISSUE THREAD

**Issue by nhowell** [laravel/framework#11644]
Given this resource route:
```
Route::resource('users', 'UserController');
```
It currently generates route URIs like:
```
users/{users}
users/{users}/edit
// ... and so on
```

This, unfortunately, doesn't go along well with implicit model bindings due to the plural, rather than singular, wildcards.

For example, in order to use implicit model bindings in our ```UserController```:
```
...
public function show(User $users)
{
    // $users is a single User... :(
}
...
```
Notice that we're required to name the variable ```$users``` (plural), rather than ```$user``` (singular), because it's the name of the wildcard.

Maybe we could change the behavior of ```Route::resource``` to use the singular name of the resource for the wildcard?

I, personally, would prefer resource routes to use the singular name for wildcards, anyway, regardless of this issue with implicit model bindings.

Thoughts?

**Comment by GrahamCampbell** [comment]
> // $users is a single User

That makes no sense?

**Comment by GrahamCampbell** [comment]
> That makes no sense?

Ah, I see that was rather your point. ;)

**Comment by lagbox** [comment]
We could use the $options array for something like this if it was needed. (just as an idea)

    Route::resource('users.photos', 'PhotoController', ['wildcards' => [
        'users' => 'user', 'photos' => 'photo'
    ]]);

Potentially even more generalized (or some other variation)

    ['wildcards' => 'singular'] 

Extending ResourceRegistrar for this isn't difficult and it wouldn't appear to be breaking.

**Comment by lagbox** [comment]
I wrote up a gist for the functionality I mentioned by extending ResourceRegistrar but if you just want all resource wildcards to be singular always you should be able to just override one method.

    class YourResourceRegistrar extends \Illuminate\Routing\ResourceRegistrar
    {
        public function getResourceWildcard($value)
        {
            return str_singular(parent::getResourceWildcard($value));
        }
    }

Then just bind that class to `Illuminate\Routing\ResourceRegistrar`.

**Comment by lagbox** [comment]
@nhowell there is now the ability to set all the route parameters for resource routes to singular. `Route::singularResourceParameters();`
@GrahamCampbell
