### ISSUE TITLE
[View] @{{{ }}} not gettig escaped right

### ISSUE THREAD

**Issue by spaceemotion** [laravel/framework#11642]
I just stumbled upon this edge case, in which I need to not HTML-escape a variable with VueJS using the `{{{ data }}}` syntax.
As I can let blade know to not process the VueJs tags by prepending them with an `@`-symbol I tried the same for the triple braces, no success; `@{{{ data }}}` is incorrectly getting parsed to `@<?php echo e(data); ?>`

We are still using v5.0.33, if this has been fixed in the future versions, please let me know and this can be closed immediately (we were planning on upgrading next week anyways). Cheers, and happy new Year!

**Comment by GrahamCampbell** [comment]
Thanks. I'm honestly not sure. If it doesn't work on 5.1, please open a new issue.

**Comment by spaceemotion** [comment]
@GrahamCampbell Okay, just checked on a fresh install. This has already been fixed. Thanks anyways!
