### ISSUE TITLE
[5.1][5.2] Upgrade problem

### ISSUE THREAD

**Issue by shinokada** [laravel/framework#11650]
After following [upgrade doc](https://laravel.com/docs/master/upgrade#upgrade-5.2.0), I run composer update. Then I get the following error. 

    Loading composer repositories with package information
    Installing dependencies (including require-dev)
    Your requirements could not be resolved to an installable set of packages.
    
      Problem 1
        - laravel/framework v5.1.18 requires symfony/css-selector 2.7.* -> no matching package found.
        - Conclusion: don't install laravel/framework v5.2.6
        - Conclusion: don't install laravel/framework v5.2.5
        - Conclusion: don't install laravel/framework v5.2.4
        - Conclusion: don't install laravel/framework v5.2.3
        - Conclusion: don't install laravel/framework v5.2.2
        - Conclusion: don't install laravel/framework v5.2.1
        - lewis/presenter v1.0.0 requires illuminate/support 5.1.* -> satisfiable by laravel/framework[v5.1.18], illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.6, v5.1.8].
        - lewis/presenter v1.0.0 requires illuminate/support 5.1.* -> satisfiable by laravel/framework[v5.1.18], illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.6, v5.1.8].
        - don't install illuminate/support v5.1.1|don't install laravel/framework v5.2.0
        - don't install illuminate/support v5.1.13|don't install laravel/framework v5.2.0
        - don't install illuminate/support v5.1.16|don't install laravel/framework v5.2.0
        - don't install illuminate/support v5.1.2|don't install laravel/framework v5.2.0
        - don't install illuminate/support v5.1.20|don't install laravel/framework v5.2.0
        - don't install illuminate/support v5.1.22|don't install laravel/framework v5.2.0
        - don't install illuminate/support v5.1.25|don't install laravel/framework v5.2.0
        - don't install illuminate/support v5.1.28|don't install laravel/framework v5.2.0
        - don't install illuminate/support v5.1.6|don't install laravel/framework v5.2.0
        - don't install illuminate/support v5.1.8|don't install laravel/framework v5.2.0
        - Installation request for laravel/framework 5.2.* -> satisfiable by laravel/framework[v5.2.0, v5.2.1, v5.2.2, v5.2.3, v5.2.4, v5.2.5, v5.2.6].
        - Installation request for lewis/presenter ^1.0 -> satisfiable by lewis/presenter[v1.0.0].
    
    Potential causes:
     - A typo in the package name
     - The package is not available in a stable-enough version according to your minimum-stability setting
       see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.
    
    Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by crynobone** [comment]
```
- lewis/presenter v1.0.0 requires illuminate/support 5.1.* -> satisfiable by laravel/framework[v5.1.18], illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.6, v5.1.8].
    - lewis/presenter v1.0.0 requires illuminate/support 5.1.* -> satisfiable by laravel/framework[v5.1.18], illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.6, v5.1.8].
    - don't install illuminate/support v5.1.1|don't install laravel/framework v5.2.0
```

This error is already clear IMHO.

**Comment by lcdss** [comment]
I had the same error while installing Spark on Windows:

![Error while installing Spark](http://i.imgur.com/m6VkGK5.png)

**Comment by GrahamCampbell** [comment]
You are trying to install packages that do not work on L5.2.
