### ISSUE TITLE
Laravel 5.2 orderby method not exists

### ISSUE THREAD

**Issue by ssuhat** [laravel/framework#11651]
Hi,

I'm using eloquent to query and order it "desc". 

      $query = Feedback::orderBy('created_at', 'DESC')->get();

My Feedback model:

    class Feedback extends Model
    {
        protected $fillable = ['title', 'content', 'rating'];
    }

When I run it 

![untitled](https://cloud.githubusercontent.com/assets/10653041/12074058/b7fcaf82-b171-11e5-93d2-4eb7bee72bbc.png)

Is this a bug? or i make mistake?

**Comment by ssuhat** [comment]
Never mind i found the culprit.

Sorry.

**Comment by grafxflow** [comment]
What caused the issue?
