### ISSUE TITLE
404 page without session

### ISSUE THREAD

**Issue by caiquecastro** [laravel/framework#11653]
After upgrading to 5.2, I started getting errors for my 404 pages: Session store not set on request.

I get this because I have a modal loaded on this page.

Is it an error because i didn't get this errors before, but now that \Illuminate\Session\Middleware\StartSession::class is not a general middleware, i get this error.

**Comment by GrahamCampbell** [comment]
That's because we only start the session if the route was matched.

**Comment by GrahamCampbell** [comment]
Sorry if this isn't clear.

**Comment by faniuta** [comment]
To avoid problems when you have other exception or recive request with api middleware,change the render function In App/Exceptions/Handler.php to :
` public function render ($request, Exception $exception)
{
    if ($this->isHttpException($exception)) {
        switch ($exception->getStatusCode()) {
            case '404':
                \Route::any(request()->path(), function () use ($exception, $request) {
                    return parent::render($request, $exception);
                })->middleware('web');
                return app()->make(Kernel::class)->handle($request);
                break;
            default:
                return $this->renderHttpException($exception);
                break;
        }
    } else {

        return parent::render($request, $exception);
    }
}`

**Comment by faniuta** [comment]
To avoid problems when you have other exception or recive request with api middleware,change the render function In App/Exceptions/Handler.php to :
```
 public function render ($request, Exception $exception)
{
    if ($this->isHttpException($exception)) {
        switch ($exception->getStatusCode()) {
            case '404':
                \Route::any(request()->path(), function () use ($exception, $request) {
                    return parent::render($request, $exception);
                })->middleware('web');
                return app()->make(Kernel::class)->handle($request);
                break;
            default:
                return $this->renderHttpException($exception);
                break;
        }
    } else {

        return parent::render($request, $exception);
    }
}
```
