### ISSUE TITLE
[5.2] 5.2.5 -> 5.2.6 (composer update) after the update "ReflectionException"

### ISSUE THREAD

**Issue by HeuJung** [laravel/framework#11659]
5.2.5 working.

but, 5.2.6 error occurred after an upgrade.
![2](https://cloud.githubusercontent.com/assets/10345170/12075954/311cef06-b1d8-11e5-9b92-5703a114626a.png)

**Comment by GrahamCampbell** [comment]
It's because your .env file it badly formmatted.

**Comment by GrahamCampbell** [comment]
We were previously hiding that error by mistake.

**Comment by HeuJung** [comment]
@GrahamCampbell Thanks!
