### ISSUE TITLE
[5.2] laravel/config/session.php comments update from database to legacy-database

### ISSUE THREAD

**Issue by jdrda** [laravel/framework#11667]
As datatabase session driver is renamed to legacy-database, this should be also changed in configuaration comments, as new users do not know this.

/*
    |--------------------------------------------------------------------------
    | Default Session Driver
    |--------------------------------------------------------------------------
    |
    | This option controls the default session "driver" that will be used on
    | requests. By default, we will use the lightweight native driver but
    | you may specify any of the other wonderful drivers provided here.
    |
    | Supported: "file", "cookie", "database", "apc",
    |            "memcached", "redis", "array"
    |
    */

**Comment by hiendv** [comment]
`legacy-database` driver is the old `database` driver, the changes are already documented in Upgrade Guide. I don't think we should encourage users using a deprecated (is it?) driver.

**Comment by jdrda** [comment]
From: https://laravel.com/docs/5.2/upgrade#upgrade-5.2.0

The database session driver from 5.1 has been renamed to legacy-database and will be removed. Consult notes on the "database session driver" above for more information.

So from this, it means "database" is old name and "legacy-database" is the new one.

**Comment by hiendv** [comment]
I don't think so. "database" driver is re-written: same name, different implementation while "legacy-database" is supposed to be the deprecated driver from my point of view. I quote the full text:
> If you would like to **continue using the old driver** you may specify the `legacy-database` driver in your session.php configuration file.

**Comment by jdrda** [comment]
OK, it seems, it is clear for all, so I am closing the issue.
