### ISSUE TITLE
Image upload to s3 using filesystem

### ISSUE THREAD

**Issue by hoshomoh** [laravel/framework#11671]
I dont think this is really an issue. Maybe there is somehing am doing worng.
I am trying to upload images to s3 using laravel 5.1 filesystem. I set up my filesystem.php config file to use the correct driver and settings and I also required the league/filesysystem package as noted in the laravel filesystem documentation. But when i tried to test  keep getting this 

`S3Exception in WrappedHttpHandler.php line 159: Error executing "PutObject" on "https://s3.your-region.amazonaws.com/your-bucket/halls/3edf6142206cc1851fc05fa8730e34eb-1.jpeg"; AWS HTTP error: cURL error 6: Could not resolve host: s3.your-region.amazonaws.com (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`

I would realy appreciate if anyone can help debug this.

**Comment by GrahamCampbell** [comment]
Just replace `your-region` with `us-east-1`, or whatever region you're using. ;)

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/laravel/blob/master/config/filesystems.php#L69

**Comment by GrahamCampbell** [comment]
Remember to run `php artisan config:cache` after making any changes to the .env file, or the config files.

**Comment by hoshomoh** [comment]
I already added the correct region to the config file. Let me try to run `php artisan config:cache` and see if that fixes it.

**Comment by hoshomoh** [comment]
Hi @GrahamCampbell That seems to work. Thanks. But this error keeps popping out 

CredentialsException in InstanceProfileProvider.php line 79:
Error retrieving credentials from the instance profile metadata server. (cURL error 28: Connection timed out after 1001 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html))

Any ideas?
