### ISSUE TITLE
[5.2] Update v5.2.5 -> 5.2.6 Uncaught ReflectionException: Class log does not exist

### ISSUE THREAD

**Issue by schulzefelix** [laravel/framework#11673]
After the update from 5.2.5 to 5.2.6 I get the following error:
```
PHP Fatal error:  Uncaught ReflectionException: Class log does not exist in /home/vagrant/code/xxx/vendor/laravel/framework/src/Illuminate/Container/Container.php:736
```

Any suggestion? Thanks.

**Comment by GrahamCampbell** [comment]
You have a syntax error in your .env file.

**Comment by GrahamCampbell** [comment]
Laravel was previously silently ignoring all entries after the syntax error. Now, we throw an exception.

**Comment by schulzefelix** [comment]
Thanks! For others having this issue, I placed some quotes around several env variables.

**Comment by GrahamCampbell** [comment]
You'll only need to do this when they have spaces, as documented.

**Comment by GrahamCampbell** [comment]
https://github.com/vlucas/phpdotenv

**Comment by danielcmm** [comment]
This affected me too.. lost a lot of time until i found this issue. Maybe should be more well documented?

**Comment by GrahamCampbell** [comment]
The error message is a different bug in laravel's exception handler.

**Comment by cardi777** [comment]
i can't fix this issue, really bugging me

**Comment by ufoe** [comment]
This affected me too.

But my issue is not something wrong with .env file. It is because i missed a ; in a config file.

**Comment by idhamhafidz** [comment]
Which config file? Mine was working okay until after composer update and this error comes out

**Comment by lopez9117** [comment]
in my case only is the :: in the line:
'Datatables' => Yajra\Datatables\Facades\Datatables::class,
