### ISSUE TITLE
[Homestead] report:502 Bad Gateway

### ISSUE THREAD

**Issue by XingFang** [laravel/framework#11670]
First, my operating system is windows 10 ,I do that step by step according to the Laravel documentation,added the domain to my hosts file,my domain is "laravel.dev". then,when viisit laravel.dev,the Browser reporting 502  Bad Gateway,I don‘t know why.anybody has occured this question?Please give me some ideas!!
![qq 20160104203457](https://cloud.githubusercontent.com/assets/13644079/12089715/cbc9aee0-b322-11e5-9fbf-679cd9fb1433.png)
![qq 20160104210603](https://cloud.githubusercontent.com/assets/13644079/12090151/2c035d0c-b327-11e5-99db-8c96fca26958.png)

**Comment by morloderex** [comment]
You must NOT use tabs in the homestead.yaml file. for indentation use spaces. 
That's the error here.

**Comment by XingFang** [comment]
As you said above, I modified the homestead.yaml file.Errors disappears,my operating system has installed VMware Workstation,and i modified provide:vmware_workstation,Why has reported no provide:virtualbox.like this
![qq 20160104214539](https://cloud.githubusercontent.com/assets/13644079/12090785/e4ba8adc-b32c-11e5-959c-c9eef683f603.png)
![qq 20160104214716](https://cloud.githubusercontent.com/assets/13644079/12090786/e9c84870-b32c-11e5-9e06-fb517cbc37be.png)

**Comment by XingFang** [comment]
what's the problem?
![qq 20160104231413](https://cloud.githubusercontent.com/assets/13644079/12092660/711cbc96-b339-11e5-9395-b9a21298af08.png)

**Comment by GrahamCampbell** [comment]
Please feel free to continue this on the forums. Closing this since it's not an actual issue with laravel.

**Comment by XingFang** [comment]
OK..i'm sorry!!
