### ISSUE TITLE
[5.2] An additional '()' in SQL

### ISSUE THREAD

**Issue by Daniyal-Javani** [laravel/framework#11672]
In mysql mode with follow code 
``
            $table->foreign('user_id')->refrences('id')->on('users')->onDelete('cascade');
``
produce:
``
alter table `articles` add constraint articles_user_id_foreign foreign key (`user_id`) references `users` () on delete cascade
``

Full error:
``[Illuminate\Database\QueryException]                                                                                                            
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL   
  server version for the right syntax to use near ') on delete cascade' at line 1 (SQL: alter table `articles` add constraint articles_user_id_f  
  oreign foreign key (`user_id`) references `users` () on delete cascade)  ``
I'm new in Laravel, please tell me if you require additional information or if this is not a bug!

**Comment by schulzefelix** [comment]
$table->foreign('user_id')->refrences('id')->on('users')->onDelete('cascade'); 

should be

$table->foreign('user_id')->**references**('id')->on('users')->onDelete('cascade');

**Comment by fenglou** [comment]
same problem, the sql statement generated by laravel is:
alter table `articles` add constraint articles_user_id_foreign foreign key      (`user_id`) references `users` () on delete cascade;
It missed "id" after users, a bug? I have to manually run:
alter table `articles` add constraint articles_user_id_foreign foreign key      (`user_id`) references `users` (id) on delete cascade;

**Comment by GrahamCampbell** [comment]
Thanks everyone. If this issue is still persisting, please open a new issue.
