### ISSUE TITLE
L5.1 Failed Jobs always tried to call MySQL, but I'm using PostgreSQL 

### ISSUE THREAD

**Issue by Jaspur** [laravel/framework#11683]
When a job is failing, it should try to write the error to the default queue's failed_jobs table. But it gives an exception:
```
PDOException · vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:55
SQLSTATE[HY000] [2002] No such file or directory
```
SQLSTATE[HY000] [2002] is a MySQL-error. And that is correct, because I deleted MySQL from the Server and I'm using PostgreSQL everywhere as connection. But for some reason it tries to connect to MySQL? In my .env I have ```DB_CONNECTION=pgsql```

**Comment by GrahamCampbell** [comment]
Sync your queue config with the laravel/laravel 5.1 branch.

**Comment by nikosv** [comment]
@Jaspur I am facing the same issue. I was wondering if and how dit you solve it?

**Comment by Jaspur** [comment]
@nikosv in ```config.queue```: 

```
'failed'      => [
        'database' => env('DB_CONNECTION', 'mysql'),
        'table'    => 'failed_jobs',
    ],
```
But that was already fixed by a PR I did, so a fresh config pull from the 5.1 branch also worked.
