### ISSUE TITLE
[5.2] Can't access token repository

### ISSUE THREAD

**Issue by lukebro** [laravel/framework#11686]
I'm trying to accomplish a similar thing as in #11555, however the `getRepository()` method Taylor recommended to use through the facade is protected and returns the error:

```
call_user_func_array() expects parameter 1 to be a valid callback, 
cannot access protected method Illuminate\Auth\Passwords\PasswordBroker::getRepository()
```

Anyways I can get access to the tokens repository?

Thank you!

**Comment by lukebro** [comment]
It is public, but my version had private for some reason.

**Comment by GrahamCampbell** [comment]
`composer update` :P

**Comment by lukebro** [comment]
@GrahamCampbell :P yeah, didn't realize that Taylor updated it in the .6 release.  Sorry for the trouble!
