### ISSUE TITLE
Tinker doesn't allow globally reserved words in php7

### ISSUE THREAD

**Issue by ixmanuel** [laravel/framework#11690]
Expectation:
    - PHP7.0.X Other changes: Loosening Reserved Word Restrictions

Environment: 
    - Homestead 0.4.0
    - Psy Shell v0.6.1 (PHP 7.0.1-1+deb.sury.org~trusty+2 — cli) by Justin Hillman

Case:
```javascript
class Foo
{
    public function new()
    {
    }

    public function with()
    {
    }

    public function for() 
    {    	
    }
}
```

Output:
PHP Parse error: Syntax error, unexpected T_NEW, expecting T_STRING on line 3
PHP Parse error: Syntax error, unexpected T_PUBLIC on line 1
PHP Parse error: Syntax error, unexpected T_PUBLIC on line 1

**Comment by lagbox** [comment]
Must be something with that version of PHP 7. This works in tinker for me, but I am not using homestead.

>Psy Shell v0.6.1 (PHP 7.0.1-4+deb.sury.org~wily+1 — cli) by Justin Hileman

**Comment by GrahamCampbell** [comment]
It's probably because you have another dependency installed that required php parser 1.x. You will only be able to use all the php 7 features if your dependencies allow composer to resolve php parser 2.x.
