### ISSUE TITLE
[Homestead] Decided to update homestead... big mistake

### ISSUE THREAD

**Issue by Jamesking56** [laravel/framework#11693]
Hello!

I've had Homestead running for a while and I decided to update my VM setup.

I have installed the Homestead machine inside the project so I destroyed my VM, updated Virtualbox and ran `composer update` to pull in `laravel/homestead` package changes.

Now when I run `homestead up` and visit my VM's site, I get a `502 Bad Gateway` message.

To track down the issue, I've opened up my nginx site error logs and found this:

````
2016/01/05 11:40:22 [crit] 6001#6001: *1 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 192.168.10.1, server: metrics.app, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "metrics.app"
````

What is going on and what is required to fix this?

**Comment by Jamesking56** [comment]
Aha! I have found the issue.

It seems as though PHP was updated from 5.6 to 7.0 (which is perfectly fine for my project).

However, the nginx site configuration is pointing to the php5-fpm socket rather than the php7.0-fpm socket.

So I just needed to update the site - should this be documented somewhere?

**Comment by crynobone** [comment]
You need to upgrade to `"laravel/homestead": "~3.0.0"`

**Comment by Jamesking56** [comment]
Thanks for clarifying this @crynobone is it worth documenting this at all?
