### ISSUE TITLE
[5.2] BladeCompiler getTags inconsistency

### ISSUE THREAD

**Issue by CupOfTea696** [laravel/framework#11699]
I just noticed an inconsistency between `getRawTags` and `getTags` in the `BladeCompiler`.

When getting the 'raw' tags, it simply returns them as they are sent on the object, while for the content and escape content tags, it removes the slashes before returning them.

Making this an issue rather than a PR because I'm not sure which way you want to return the tags (although I assume it'll be the ones with the slashes stripped)

See [BladeCompiler.php#L802-L877](https://github.com/laravel/framework/blob/5.2/src/Illuminate/View/Compilers/BladeCompiler.php#L802-L877)

**Comment by GrahamCampbell** [comment]
Thanks. We're open to PRs. Probably best to ask on slack first though. :)
