### ISSUE TITLE
[5.2.6] Validation errors not handled well in AJAX request.

### ISSUE THREAD

**Issue by jarnovanleeuwen** [laravel/framework#11696]
Hi,

Starting from 5.2.6, our application is returning a 500 status code (`HttpResponseException`) when validation errors arise inside an AJAX request. I have dug into the issue and it seems that the problem disappears when the `getInitialSlice` method is removed from `Illuminate\Routing\Pipeline` (https://github.com/laravel/framework/blob/5.2/src/Illuminate/Routing/Pipeline.php#L42-L59).

Jarno

**Comment by GrahamCampbell** [comment]
This logic has moved to the controller now.

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/commit/2782c026bf7f3792c5e68dbfde3735ec7058931d

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/commit/74910637b1c0389ab57f136721dc09404fa470dc

**Comment by jarnovanleeuwen** [comment]
Thanks for your reply.

We do not make use of Laravel's authentication controllers. The problem occurs for any FormRequest that fails validation. Is this also taken into consideration? Thanks again :+1:
