### ISSUE TITLE
How can I use phpredis extension instead of predis as Redis Driver ?

### ISSUE THREAD

**Issue by jiaojie1989** [laravel/framework#11692]
As mentioned in #1066 , I recognized that I must rename the alias `Redis` or declare the namespace `Illuminate\Support\Facades\Redis` while using `Redis`.

But I have a question why not we use phpredis extension instead ?

**Comment by GrahamCampbell** [comment]
That library will use the extension if installed under the hood.

**Comment by jiaojie1989** [comment]
Yeah, I see in the `predis/predis` components source code.

Thanks a lot !

**Comment by jiaojie1989** [comment]
After all, I see `predis/predis` using `sockets` in its case.
But I find another component `vetruvet/laravel-phpredis`, with changing of the `redis` service provider, usage of `phpredis` extension can be possible.
