### ISSUE TITLE
laravel 5.2 authentication 

### ISSUE THREAD

**Issue by Rahul-Giri** [laravel/framework#11703]
Hi , 
i have just noticed a very small thing regarding laravel authentication. after scaffolding laravel builtin authentication , when i register in the view its actually redirecting to '/' main route which is the dashboard  and in nav bar showing login or register not  on '/home' routes and showing you are logged in. so i think new user can get stuck like me for 5 mints. so i fixed it . please add redirect to '/home'. thanks. :)

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/compare/v5.2.6...5.2
