### ISSUE TITLE
[Proposal] Add the ability to unique stacks in blade.

### ISSUE THREAD

**Issue by IanCaunce** [laravel/framework#11704]
After reading the docs regarding [stacks] (https://laravel.com/docs/5.2/blade#stacks) in blade it would be great if you could unique a them. 

Consider this scenario:

If I have a blade template which relies on a JavaScript file, I can push that to a stack and output it in the head of the document. However if the template is included multiple times, the snippet of code would be added multiple times to the stack and therefore outputted multiple times. If I could unique the stack when calling `@stack` it would solve this issue and be massively beneficial.

**Comment by GrahamCampbell** [comment]
That's really what sections are for.

**Comment by jayenne** [comment]
I guess, instead of a common @yield('footer-scripts') I could use @yield('x_script') @yield('y-script') but this is a dredful solution for those who don't know what sections will be needed beforehand.
