### ISSUE TITLE
[5.1] [5.2] A malformed blade comment followed by a correct one hides error

### ISSUE THREAD

**Issue by thecrypticace** [laravel/framework#11711]
I ran into an issue earlier today where I had a space just after the `--` in a blade comment but it did not result in an error. Compilation continued without errors. This is because it was followed by another, correctly-formed blade comment. The combination of the two let parsing continue in an incorrect manner. Thankfully, my integration tests caught the issue but the cause took a while to track down. I have tested this on the latest versions of Laravel 5.1, 5.2, and 5.2.x-dev.

Example:
```
{{-- This a malformed blade comment -- }}
{{-- But it will continue into this one and let parsing continue in an incorrect manner --}}

<div id="{{ $lookHere }}">This should result in an undefined variable error but does not</div>
```

This is because it ends up compiling to:
```
<div id="{{ $lookHere); ?>">This should result in an undefined variable error but does not</div>
```

Notice that the interpolation isn't replaced correctly and makes the content inside the `{{ }}` tags visible in the rendered output.

Notes:
1. Removing the space between `--` and `}}` causes it to act correctly.
2. Removing the `{{--` in the second comment also causes it act correctly.

Suggestions:
1. Parse error for the comment OR
2. Fix parsing issue when a blade comment opening tag appears in a blade comment.

Repository with reproduction of the issue: https://github.com/thecrypticace/blade-error

**Comment by GrahamCampbell** [comment]
I don't agree this is a bug.

**Comment by thecrypticace** [comment]
Seeing that partially parsed PHP is output to the user I would disagree. However, if this indeed expected then you can close the issue.

I will note that the fully compiled output (in `storage/views`) looks like so:
```php
<?php /* This a malformed blade comment -- }}
<?php echo e(-- But it will continue into this one and let parsing continue in an incorrect manner */ ?>

<div id="{{ $lookHere); ?>">This should result in an undefined variable error but does not</div>
```

**Comment by GrahamCampbell** [comment]
I'd say it's expected, just as if you don't close a comment properly in actual php code.

**Comment by thecrypticace** [comment]
FWIW, blade comments containing an unclosed interpolation tag does the same thing. The problem appears to be that blade is parsing content inside a comment while most languages, including PHP, will not. I recall there being some discussion around discarding the contents of blade comments. That would also fix this as far as I can tell.

```
{{-- This is a reduced test case with braces in the middle {{ that shows the the same problen. --}}
<div id="{{ $lookHere }}">This should result in an undefined variable error but does not</div>
```

Another example of interpolations inside comments causing problems:

```
{{--
<script>
/* some commented javascript */
some other code
</script>
--}}
```

**Comment by GrahamCampbell** [comment]
> Another example of interpolations inside comments causing problems:

That's not a bug imo.

**Comment by GrahamCampbell** [comment]
We might change blade to just discard the contents of a comment instead of compiling it. That would fix your 2nd issue.

**Comment by thecrypticace** [comment]
Discarding contents of comments would fix all issues listed above. Discarding the contents would invalidate any interpolations. I'm good with that. :+1:
