### ISSUE TITLE
[5.1] Discard Blade Comment Contents

### ISSUE THREAD

**Issue by GrahamCampbell** [laravel/framework#11718]

**Comment by vlakoff** [comment]
This has been recently discussed here: #12506 (in the "commented on an outdated diff").

**Comment by GrahamCampbell** [comment]
I still think we should consider stripping them. Maybe just from 5.3 onwards.

**Comment by vlakoff** [comment]
Why "still"? Taylor said the same:
> I personally think comments should be entirely removed.

**Comment by ockle** [comment]
Really hope this gets added for 5.3. Being able to get errors from code that you've commented out is counter-intuitive.

**Comment by GrahamCampbell** [comment]
Here we go guys: https://github.com/laravel/framework/pull/14029.

**Comment by billmn** [comment]
@GrahamCampbell I think this can be closed :)

**Comment by GrahamCampbell** [comment]
Yeh, thanks. ;)
