### ISSUE TITLE
[5.2] .env file now requires quotes around strings

### ISSUE THREAD

**Issue by ikari7789** [laravel/framework#11715]
After updating from 5.2.5 to 5.2.6 dotenv defined strings now require quotes around them whereas they did not in the past. I'm not sure if this was the expected behavior to begin with or not though.

Under 5.2.5, the following was still working:
__config/mail.php__
```php
<?php
return [
    'from' => ['address' => env('MAIL_FROM_ADDRESS', null), 'name'=> env('MAIL_FROM_NAME', null)],
];
```

__.env__
```
MAIL_FROM_NAME=System Administrator
```

Under 5.2.6, this same configuration results in the following error:

```
PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class log does not exist' in /var/www/trafficgate/vendor/laravel/framework/src/Illuminate/Container/Container.php:736
Stack trace:
#0 /var/www/trafficgate/vendor/laravel/framework/src/Illuminate/Container/Container.php(736): ReflectionClass->__construct('log')
#1 /var/www/trafficgate/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('log', Array)
#2 /var/www/trafficgate/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('log', Array)
#3 /var/www/trafficgate/vendor/laravel/framework/src/Illuminate/Container/Container.php(845): Illuminate\Foundation\Application->make('Psr\\Log\\LoggerI...')
#4 /var/www/trafficgate/vendor/laravel/framework/src/Illuminate/Container/Container.php(800): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /var/www/trafficgate/vendor/laravel/framework/src/Illuminate/Container/Container.php( in /var/www/trafficgate/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 736

Fatal error: Uncaught exception 'ReflectionException' with message 'Class log does not exist' in /var/www/trafficgate/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 736

ReflectionException: Class log does not exist in /var/www/trafficgate/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 736

Call Stack:
    0.0003     228112   1. {main}() /var/www/trafficgate/artisan:0
    0.0607    2598944   2. Illuminate\Foundation\Console\Kernel->handle() /var/www/trafficgate/artisan:36
    0.0701    2815328   3. Illuminate\Foundation\Console\Kernel->reportException() /var/www/trafficgate/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:109
    0.0701    2815376   4. Illuminate\Container\Container->offsetGet() /var/www/trafficgate/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:250
    0.0701    2815376   5. Illuminate\Foundation\Application->make() /var/www/trafficgate/vendor/laravel/framework/src/Illuminate/Container/Container.php:1168
    0.0701    2815512   6. Illuminate\Container\Container->make() /var/www/trafficgate/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:674
    0.0701    2815624   7. Illuminate\Container\Container->build() /var/www/trafficgate/vendor/laravel/framework/src/Illuminate/Container/Container.php:631
    0.0701    2815624   8. Illuminate\Container\Container->Illuminate\Container\{closure}() /var/www/trafficgate/vendor/laravel/framework/src/Illuminate/Container/Container.php:733
    0.0701    2815672   9. Illuminate\Foundation\Application->make() /var/www/trafficgate/vendor/laravel/framework/src/Illuminate/Container/Container.php:230
    0.0701    2815672  10. Illuminate\Container\Container->make() /var/www/trafficgate/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:674
    0.0702    2815768  11. Illuminate\Container\Container->build() /var/www/trafficgate/vendor/laravel/framework/src/Illuminate/Container/Container.php:631
    0.0723    2872752  12. Illuminate\Container\Container->getDependencies() /var/www/trafficgate/vendor/laravel/framework/src/Illuminate/Container/Container.php:771
    0.0730    2886728  13. Illuminate\Container\Container->resolveClass() /var/www/trafficgate/vendor/laravel/framework/src/Illuminate/Container/Container.php:800
    0.0730    2886816  14. Illuminate\Foundation\Application->make() /var/www/trafficgate/vendor/laravel/framework/src/Illuminate/Container/Container.php:845
    0.0730    2886952  15. Illuminate\Container\Container->make() /var/www/trafficgate/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:674
    0.0730    2887032  16. Illuminate\Container\Container->build() /var/www/trafficgate/vendor/laravel/framework/src/Illuminate/Container/Container.php:631
    0.0730    2887248  17. ReflectionClass->__construct() /var/www/trafficgate/vendor/laravel/framework/src/Illuminate/Container/Container.php:736
```

This took me far longer to track down than I had hoped as the error that was thrown gave no suggestion to me that the cause was due to the .env file.
The only difference in my testing was Laravel/Framework v5.2.5 and Laravel/Framework v5.2.6. All other packages, including vlucas/dotenv (v2.2.0) were already at their latest.
I couldn't seem to find anything in the diff between 5.2.5 and 5.2.6 that would suggest this would happen.

**Comment by ikari7789** [comment]
It's caused by the change of ```InvalidArgumentException``` to ```InvalidPathException``` in ```src/Illuminate/Foundation/Bootstrap/DetectEnvironment.php```, but I'm not sure why this would cause it to fail unless it's been working by a bug until now.

**Comment by lcdss** [comment]
This error happened with me sometimes and deleting /bootstrap/compiled.php manually solved the problem.

**Comment by EliasZ** [comment]
https://github.com/vlucas/phpdotenv/issues/133#issuecomment-152707290

**Comment by ikari7789** [comment]
Wow, thanks for that.
Considering I've never had to quote a string literal that appears on its own line before, I find this decision to be quite obnoxious.
Worse yet that is isn't mentioned in the documentation for Laravel anywhere since they transferred from dotenv v1 to v2. Definitely warrants an upgrade message I would think as it is BC.

**Comment by GrahamCampbell** [comment]
> It's caused by the change of InvalidArgumentException to InvalidPathException in src/Illuminate/Foundation/Bootstrap/DetectEnvironment.php, but I'm not sure why this would cause it to fail unless it's been working by a bug until now.

Not it wasn't. Before it was just failing silently and discarding half your .env file...

**Comment by GrahamCampbell** [comment]
> Under 5.2.5, the following was still working:

No it wasn't. It was failing silently.

**Comment by ikari7789** [comment]
That's even worse. This is handled extremely poorly for invalid files. You don't even know it's the .env file causing the failure based on the exception thrown by Laravel.

**Comment by GrahamCampbell** [comment]
That's a different bug, yes.

**Comment by GrahamCampbell** [comment]
It's because an exception is thrown trying to log the original exception.

**Comment by JonasGrosvald** [comment]
This error happened with me sometimes and deleting /bootstrap/compiled.php manually solved the problem.

thanks @lcdss !!

**Comment by GrahamCampbell** [comment]
> thanks @lcdss !!

That DOES NOT solve this problem, BUT it could solve other problems.

**Comment by JonasGrosvald** [comment]
@GrahamCampbell well, I've posted the issue here https://laracasts.com/discuss/channels/general-discussion/class-log-does-not-exist-1?page=1#reply-138188

I have been unable to progress since yesterday. After deleting the bootstrap compiled file it works.

But you are correct, it is not related to the .env files. My bad

**Comment by tomcastleman** [comment]
@GrahamCampbell I have just submitted a [PR](https://github.com/laravel/docs/pull/2223) to the docs to warn about this.
Do you think within [Bootstrap/DetectEnvironment.php](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Bootstrap/DetectEnvironment.php#L23) we should be catching the [InvalidFileException](https://github.com/vlucas/phpdotenv/blob/master/src/Loader.php#L228) ?

**Comment by GrahamCampbell** [comment]
>  we should be catching

No, we purposefully throw it in order to crash the app because the env file is invalid.

**Comment by tomcastleman** [comment]
@GrahamCampbell Sure, but the current stack trace is useless. I had to use step debugging with xdebug to figure out what was going on. This isn't particularly accessible when a better error could be presented.
Even a `die('Environment file is invalid')` would be better.

**Comment by GrahamCampbell** [comment]
>  Sure, but the current stack trace is useless.

Yes, we do need to fix the case where the logger is not bound, and crash without having a 2nd crash.

**Comment by GrahamCampbell** [comment]
Dieing and leaking information to the user like that would be bad though.

**Comment by tomcastleman** [comment]
> Dieing and leaking information to the user like that would be bad though.

I agree, my point was just that we should present a more useful error message :+1: 

Is there an existing issue for the exception thrown before logger bound issue?

**Comment by GrahamCampbell** [comment]
yes: https://github.com/laravel/framework/issues/11756

**Comment by ikari7789** [comment]
@GrahamCampbell why does this still not have any documentation about it in the Laravel upgrade docs? Laravel 5.1 uses ```"vlucas/phpdotenv": "~1.0"```, which means .env files don't need quoted and nesting variables is done using ```{$VARIABLE}``` syntax instead of ```${VARIABLE}``` syntax. It's a breaking change, but yet there is no documentation about it anywhere.

**Comment by tomcastleman** [comment]
@ikari7789 I submitted [PR #2223](https://github.com/laravel/docs/pull/2223) but @taylorotwell closed it and isn't engaging with me how it can be accepted.

**Comment by GrahamCampbell** [comment]
It's because your PR didn't explain the actual upgrading details. It just stated the new behaviour out of context.
