### ISSUE TITLE
[5.2] ExceptionHandler not persisting Session

### ISSUE THREAD

**Issue by Propaganistas** [laravel/framework#11710]
Hi

It seems that the ExceptionHandler is (once again? cfr. #6068, #6394) not working properly with sessions.

In `app/Exceptions/Handler.php`:

```php
public function render($request, Exception $e)
{
    // Example code
    session()->put('key', 'value');
    return redirect('/');
}
```

Nonetheless the session key is *not* set when checking it after redirection. Not even when calling `    session()->save()` after the `session()->put()` statement...

Any comments on this?

**Comment by acasar** [comment]
Just to be sure - are you applying the "web" middleware on that route?

**Comment by Propaganistas** [comment]
@acasar Yes. The `StartSession` middleware is up and running.
Nonetheless calling `session()->all()` in the ExceptionHandler's `render()` method yields an empty array.

**Comment by GrahamCampbell** [comment]
If this is for an error 404 because the route isn't matched, then this is the expected behaviour.

**Comment by Propaganistas** [comment]
Hi Graham, it is not meant for a 404 error but for custom defined exceptions.

**Comment by GrahamCampbell** [comment]
Can anyone else replicate this?

**Comment by Propaganistas** [comment]
Hmm after trying a myriad of exceptions and setups, the described behavior happens quite randomly. If no one can replicate this, then I guess there's something on my local machine inducing this.

**Comment by GrahamCampbell** [comment]
It sounds like you might be having concurrency issues with session storage to me.
