### ISSUE TITLE
Worker::logFailedJob uses function outside contract.

### ISSUE THREAD

**Issue by SamMousa** [laravel/framework#11720]
In `Illuminate\Queue\Worker::logFailedJob` at https://github.com/laravel/framework/blob/5.2/src/Illuminate/Queue/Worker.php#L261

Snippet:

````
    /**
     * Log a failed job into storage.
     *
     * @param  string  $connection
     * @param  \Illuminate\Contracts\Queue\Job  $job
     * @return array
     */
    protected function logFailedJob($connection, Job $job)
    {
        if ($this->failer) {
            $this->failer->log($connection, $job->getQueue(), $job->getRawBody());

            $job->delete();

            $job->failed();

            $this->raiseFailedJobEvent($connection, $job);
        }

        return ['job' => $job, 'failed' => true];
    }
````

However, `failed()` is not specified in the `Job`contract, thus there is an implicit requirement on the concrete `Job` object to have such a method.

**Comment by GrahamCampbell** [comment]
We don't specify protected methods in interfaces.

**Comment by SamMousa** [comment]
Read again @GrahamCampbell , the function `failed()` is not a protected method...
````
 /**
     * Call the failed method on the job instance.
     *
     * @return void
     */
    public function failed()
    {
        $payload = json_decode($this->getRawBody(), true);

        list($class, $method) = $this->parseJob($payload['job']);

        $this->instance = $this->resolve($class);

        if (method_exists($this->instance, 'failed')) {
            $this->instance->failed($this->resolveQueueableEntities($payload['data']));
        }
    }

````

**Comment by SamMousa** [comment]
By the way, another more friendly approach to handling these kinds of issues would be to reply and ask me to close if the reply resolves the issue...

**Comment by GrahamCampbell** [comment]
> Read again @GrahamCampbell , the function failed() is not a protected method...

Why did you paste that code snippet then.

> By the way, another more friendly approach to handling these kinds of issues would be to reply and ask me to close if the reply resolves the issue...

The issues aren't really there to be a support tool for people, they're there to help the framework. We have forums for support tickets.

> However, failed() is not specified in the Jobcontract, thus there is an implicit requirement on the concrete Job object to have such a method.

Feel free to end a PR to L5.3 since adding a method to an interface is a major breaking change, so will not be accepted into 5.1 or 5.2. I also can't guarantee that Taylor will accept this into L5.3 either.

**Comment by SamMousa** [comment]
@GrahamCampbell I'll try to explain my apparently totally illogical reasoning.

The code snippet I posted is the code that is incorrectly making assumptions about a function being present in a concrete implementation of a contract.
I can't judge if the contract is at fault, or the Worker (where the snippet) came from.

Depending on the wishes of the team, I need to know in what direction I need to go to fix this. I can't make a PR unless I know that...

Basically if you take a bit more time you could have seen that yourself.

What I can do for you without any more feedback, is write a test for `Worker::process()` providing it with a concrete `Job` that does not implement `failed()` and that test will fail 100% of the time.

I am not asking for support on using your code which is why I am not posting my question in the support forums. I am merely noting an error in your code and need possible directions for solutions to that error.

So if you tell me how to fix it (ie what direction to go, I do not need your help coding), then I will be able to create a PR without running the risk of spending time on coding for stuff that will not be used.

That said, adding a method to the interface is indeed a major breaking change, but there are other options like adding a check to see if the `failed()` method exists on the instance.
This is a change that does not break BC and it does make your code objectively better.

**Comment by GrahamCampbell** [comment]
> That said, adding a method to the interface is indeed a major breaking change, but there are other options like adding a check to see if the failed() method exists on the instance.

Feel free to send that change to 5.1. You don't need to ask before sending PRs, infact, our contribution guide says don't.

**Comment by SamMousa** [comment]
Will do. There is actually a bigger underlying issue with the tests in general.
Since Mockery allows mocking non existing functions when mocking interfaces you are happily testing stuff that is not in your interfaces.
So you successfully test that your concrete classes which say the need an instance of some contract are actually dependent on specific implementations of that contract..

**Comment by SamMousa** [comment]
How about you open this in the mean time so other developers can actually join in this discussion :)

**Comment by EliasZ** [comment]
@SamMousa Graham gets a commission on the amount of issues he closes hence he always closes them so fast without verifying whether the issue is still valid. He also doesn't read comments on closed issues, to tighten his commission targets.

(it's a joke)
(but it might as well be true ;)

**Comment by SamMousa** [comment]
That's okay, I am stubborn and don't give up easily. In my experience every
project has one of those; I just keep opening issues until another team
member responds with actual insights.

**Comment by SamMousa** [comment]
Related to #11733 #11732

**Comment by jaketoolson** [comment]
@EliasZ @SamMousa lol.  Why is it every time I search and find a relevant issue pertaining to the bug I'm experiencing, there is always someone(s) disappointed in @GrahamCampbell ? It's a growing trend.

**Comment by SamMousa** [comment]
Well every project needs one of those, I've given up on laravel though;
nice framework but not worth trying to communicate with that guy...
