### ISSUE TITLE
Console Command Errors = Filename and Linenumber required

### ISSUE THREAD

**Issue by superdummy** [laravel/framework#11726]
https://github.com/laravel/framework/issues/11279  ticket was about a full Exception Trace. As Graham commented, a full stracktrace is not possible. 

`D:\xampp\htdocs\super>php artisan clear-compiled -vvv`
`[ReflectionException]
  Class request does not exist`

But what is required (and this ticket is about), stating the **Filename** and **Linenumber** an error/excpetion occured as minimum information. Everything less is a disaster for a framework.  

Please. see above. This is a >25.000 LOC Laravel App.The app works while accessing over http, but any artisan commands fail with `Class request does not exist` (This seems to be an DI-Resolution Error, but I have no clue where in the 25.000 lines the error is. I migrated to L5.2 and that seemed to have introduced the error.)

Of course I can start, file by file, inserting any debug statements to find the error and spend several hours finding just a single error, but thats an absolutely nogo for a framwork that is skyrocketing google trends. **Please please add for Console Commands the filename and linumber where an error occoured.**

Thanks!

**Comment by GrahamCampbell** [comment]
I'd recommend manually deleting the compiled file, because it's broken due to it containing L5.1 code.

**Comment by GrahamCampbell** [comment]
There is already an open issue regarding this problem btw. ;)

**Comment by superdummy** [comment]
@Graham, ok then I am sorry very much! 

Absoolutely great when this is in the making. Just want to address: Laravel is soo great. But I have lost soo much time to the console, it kills all productivity. 

Thanks very much for your help, very much appreciated!

**Comment by graham** [comment]
Looks like you have the wrong @graham

Cool project!

**Comment by superdummy** [comment]
@graham, I am sorry!
