### ISSUE TITLE
using  Illuminate\Foundation\Testing\DatabaseTransactions

### ISSUE THREAD

**Issue by gerardZf2Comments** [laravel/framework#11746]
Sorry to open an issue without running any code but i think i have enough info to ask what others may be wondering.

Mysql seems to commit open transactions when a new one is open. http://stackoverflow.com/questions/1490846/mysql-transactions-within-transactions

So how does the Illuminate\Foundation\Testing\DatabaseTransactions trait in this package work if the code called in the test starts a new transaction and commits it. In this case could a rollback work?

If not does that mean this trait can only be used to test code that doesn't use transactions?

Would a problem develop if someone used it wrongly i.e. could wrong use of this feature corrupt the db for later tests?

**Comment by GrahamCampbell** [comment]
What laravel vesion?

**Comment by GrahamCampbell** [comment]
I'm sure we fixed this?

**Comment by gerardZf2Comments** [comment]
I think this applies to at least  5.2 and the current tree. If you say you think we fixed this does that mean it's a sounds something like valid issue? Has it been discussed somewhere?
