### ISSUE TITLE
[5.2] Route parameters with spaces semantics change.

### ISSUE THREAD

**Issue by zwagoth** [laravel/framework#11747]
As of commit cef79d827cc8024ba5c5295adff4e0efafcf4455 there was a change from rawurlencode to urlencode that causes breaking changes. Spaces are now rendered as '+' characters, where previously in earlier version of 5.2.x and 5.1 they were rendered as '%20'. This change breaks routes that have been configured with a parameter that does not allow for the '+' character, as it is not being automatically decoded back into a space.

I'd like to request that this be changed back to '%20' by changing the use of urlencode back to rawurlencode, as percent encoding is ultimately safer and better supported.

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell.

**Comment by taylorotwell** [comment]
Can you send a PR for this? Does it changing it back break something else?

**Comment by zwagoth** [comment]
I can probably whip up a PR for this. I don't know if it breaks anything else. I am still unsure why it was changed. The code as of 5.0, 5.1 and earlier version of 5.2 all appear to use rawurlencode.

**Comment by taylorotwell** [comment]
Hmm, ok
