### ISSUE TITLE
Database driver when testing not working after updating to 5.2.7

### ISSUE THREAD

**Issue by IsraelOrtuno** [laravel/framework#11752]
I have just updated to Laravel `5.2.7` and it looks database driver selector has been broken somewhere I do not really find out where.

```
$this->app['config']->set('database.default', 'sqlite');
$this->app['config']->set('database.connections.sqlite.database', ':memory:');
```

I am getting the following error when running the tests... It is using the MySqlConnector object.

```
1) SessionsTest::it_starts_an_unexsisting_session_with_sample_data
PDOException: SQLSTATE[HY000] [2002] No such file or directory

/Users/Israel/Code/Jobs/Samples/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:55
/Users/Israel/Code/Jobs/Samples/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php:22
/Users/Israel/Code/Jobs/Samples/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php:61
```

It works perfect if I force composer to get back to `<=5.2.6`.

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell...

**Comment by taylorotwell** [comment]
Can you paste a more complete code example including where this is called, etc.

**Comment by IsraelOrtuno** [comment]
@taylorotwell this is my TestCase class https://gist.github.com/IsraelOrtuno/145edcaacd44d63ae5f1

**Comment by GrahamCampbell** [comment]
I'd recommend setting this config using env variables in the phpunit config to avoid this.

**Comment by IsraelOrtuno** [comment]
Thanks, I will take that into account ;). However shouldn't this work at any case?

**Comment by taylorotwell** [comment]
Eh, yes this should definitely be done via environment variables in your phpunit.xml

**Comment by taylorotwell** [comment]
Unfortuantely setting it the way you are is broken in 5.2.7 because of another bug fix that rolling back would cause more serious bugs unfortuantely.

**Comment by GrahamCampbell** [comment]
https://github.com/CachetHQ/Cachet/blob/master/phpunit.xml.dist#L30

**Comment by GrahamCampbell** [comment]
Just set variables like that in your phpunit config, then you don't need to write to the config at runtime like that.

**Comment by IsraelOrtuno** [comment]
@GrahamCampbell @taylorotwell yep updating that way gets the right connector but I was setting it manyally as for any reason the path `:memory:` does not work if it's set in the config file.

**Comment by GrahamCampbell** [comment]
It's because you're now setting that value after we're already read the config.

**Comment by IsraelOrtuno** [comment]
```
'connections' => [

        'sqlite' => [
            'driver'   => 'sqlite',
            'database' => ':memory:',
            'prefix'   => '',
        ],
```

This does not really work, it makes testing `DatabaseMigrations` to fail.

**Comment by IsraelOrtuno** [comment]
Completely updated to your way and it's working, thanks

**Comment by GrahamCampbell** [comment]
Great. ;)
