### ISSUE TITLE
$app->environment('foo') in config files throws error

### ISSUE THREAD

**Issue by KaneCohen** [laravel/framework#11758]
In Laravel 5.1.x it was possible to do `$app->environment('foo')` check within the config/*.php files. In 5.2.6 however that is not possible due to errors stating `Class log does not exist` - probably because at the moment when these files are loaded Log class is not yet injected into the app.

So, my question is mostly about intention - is that an intended behavior?

**Comment by GrahamCampbell** [comment]
Yeh, this is no longer supported starting from 5.2.

**Comment by GrahamCampbell** [comment]
This needs to be documented in the upgrading guide. Ping @taylorotwell.

**Comment by taylorotwell** [comment]
Would be curious to see your entire config file to know why you were making that call.

**Comment by KaneCohen** [comment]
@taylorotwell reason in my case - setting default DB connection to "testing" which uses different MySQL configs compared to standard ones. That is done so that I can run `php artisan db:seed --env=testing` and it will seed testing DB with testing data.

**Comment by GrahamCampbell** [comment]
That won't work if you cache the config though.

**Comment by GrahamCampbell** [comment]
I'd recommend overriding that part of the config at runtime. What do you think @taylorotwell?

**Comment by KaneCohen** [comment]
@GrahamCampbell I wonder if it would make sense to change Console so that it would load .env.xxx file based on what you've included in `--env` option.

**Comment by GrahamCampbell** [comment]
We don't even load the .env file on 5.2 though. We only load it for the purpose of population the config cache one time only. Applications need to be designed about that principle.

**Comment by taylorotwell** [comment]
Can you do DB::setDefaultConnection('testing') in your DatabaseSeeder class based on an environment check?

**Comment by KaneCohen** [comment]
@taylorotwell yep. Thanks - that approach does work.

**Comment by KaneCohen** [comment]
@GrahamCampbell @taylorotwell missed something important. Taylor's idea about setting default connection via `DB::setDefaultConnection('testing')` does work in a seeders, but that won't exactly work when it comes to migrations.
