### ISSUE TITLE
Container Fatal error on DonEnv InvalidFileException.

### ISSUE THREAD

**Issue by lgalaz** [laravel/framework#11755]
If on your environment file you have a value with spaces that is not formatted correctly, as in:
```
MY_NAME=Luis Galaz
```

DotEnv will throw the following exception:
**"throw new InvalidFileException('Dotenv values containing spaces must be surrounded by quotes.');"**
This is at **"DotEnv\Loader, line 228", method "sanitiseVariableValue"**

However, when caught by the Http Kernel Handle, it fails when reporting the exception since it cant report the exception. This, at **"Illuminate\Foundation\Http\Kernel, line 279", method "reportException"**

The exception message now is:
**"Fatal error: Uncaught exception 'ReflectionException' with message 'Class log does not exist' in /.../vendor/laravel/framework/src/Illuminate/Container/Container.php on line 736"**

**Comment by GrahamCampbell** [comment]
Thanks for reporting. We're aware of this bug in the exception handler, but there's no real solution at the moment.

**Comment by GrahamCampbell** [comment]
I'll make a new issue since we don't actually have one for this. We just have unrelated issues about the .env file that ultimately point to the same bug.

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/issues/11756

**Comment by GrahamCampbell** [comment]
What I have in mind there is to just rethrow the exception if there's no logger.

**Comment by lgalaz** [comment]
That would be a graceful way to handle it.

I think the only issue is not getting the correct error message, so that
would fix it.

Thanks.

**Comment by Scottzozer** [comment]
My fix was just to quote the string that has spaces in the .env file. Not sure if that is the same problem

**Comment by lgalaz** [comment]
@Scottzozer, yes, it was the same problem I was having.
Actually, it was easy to find a way to solve it (don't know if I googled it, got the solution on Larachat, or whatever). 

The bug report had the intention of maybe getting some better feedback from the exception since it seemed somewhat misleading at first.

**Comment by Masoudkhalili** [comment]
Igalaz you are right

**Comment by drahun** [comment]
You should remove all spaces from .env file to make an app work again.

If you have to use spaces, instead of this:

VAR=some data

Use quotes:

VAR="some data"
