### ISSUE TITLE
Routes defined in service provider are not working

### ISSUE THREAD

**Issue by ionesculiviucristian** [laravel/framework#11760]
I'm trying to use this in a service provider under the boot method:

        $this->app['router']->get('test', function () {
            return 'test';
        });

When I do route:list i can see it there but when I use the URL for the route it gives me a 404 error.

If i move the above code into the register method of the provider, it works.

What am I doing wrong ?

**Comment by GrahamCampbell** [comment]
This is likely happening due to cached routes messing with things.

**Comment by GrahamCampbell** [comment]
You should really only define routes by means of extending the Illuminate\Foundation\Support\Providers\RouteServiceProvider class.

**Comment by ionesculiviucristian** [comment]
I've done the route:clear thing. Is the same. I need to define the routes in the provider if i want to make a package that handles them.

**Comment by GrahamCampbell** [comment]
There's no reason why it shouldn't work, because that's how laravel already defines them in every app anyway.

I'd recommend asking on the forums since this isn't a laravel bug.

**Comment by ionesculiviucristian** [comment]
Yes. It was my fault. I had a route that caught everything in the routes file.
