### ISSUE TITLE
Rolling back migrations that used --path

### ISSUE THREAD

**Issue by leoncottell** [laravel/framework#11778]
I created a migration using --path so the migration class was created in a different directory.
e.g. php artisan make:migration SS_20160108 --path My/Path/Here

That seems to work OK, creates the file and I can run the migration fine with
php artisan migrate --path My/Path/Here

However, when i run php artisan migrate:rollback I get

[Symfony\Component\Debug\Exception\FatalErrorException]
Class 'SS20160108' not found 

When I run php artisan migrate:rollback --path My/Path/Here I get

[Symfony\Component\Console\Exception\RuntimeException]  
  The "--path" option does not exist.

There doesn't seem to be a way to roll back migrations that are not stored in the standard location?

**Comment by acasar** [comment]
You just need to autoload your alternative path as well. No ``--path`` option is needed for ``rollback``. https://github.com/laravel/laravel/blob/master/composer.json#L20

**Comment by leoncottell** [comment]
Ah yes, thanks.
