### ISSUE TITLE
Calling `Auth::User()->Model->first()->first()` gives unauthorized result

### ISSUE THREAD

**Issue by JeroenSormani** [laravel/framework#11770]
Hi there :smile: 

I came across this, and though its my/devs fault for doing something stupid like calling `first()` twice, it would be great if it would give the first authorized result back or maybe just an error, and not just the first found record.

Here's an example of something I was doing (wrong):
```
$project = \Auth::User()->projects->first()
[...]
$project->first()->id; // Gives the ID of the first found project record, even when its not relational to the user.
```

I almost overlooked this but luckily noticed some IDs in the DB were off, as there isn't any error it can be overlooked quickly.

**Comment by JeroenSormani** [comment]
Did another test, also unlikely scenario that it happens, but also gives the same like result.

```
dd( \Auth::User()->projects()->find(14)->id ); // 14 is related to this user, all good.
dd( \Auth::User()->projects()->find(15)->id ); // 15 is NOT of this user, gives back an error, all good
dd( \Auth::User()->projects()->find(14)->find(15)->id ); // Gives back '15', not from this user, undesired result
```

**Comment by GrahamCampbell** [comment]
`Auth::User()->projects()->first()` is what you want

**Comment by GrahamCampbell** [comment]
> // Gives back '15', not from this user, undesired result

That is intended.

**Comment by GrahamCampbell** [comment]
> $project->first()->id; // Gives the ID of the first found project record, even when its not relational to the user.

That's because the project object is just the project, and has nothing to do with relations.

At this point your code is the same as writing `Plan::first()->id`.
