### ISSUE TITLE
Model Observers, Updated/Updating not Firing

### ISSUE THREAD

**Issue by vitroz** [laravel/framework#11777]
I've been facing this issue for the past 2 days, and had no luck finding any solution.
I did a generic observer for my models, which works fine for create and delete, but for some reason it  does not work at all for update.

For more detailed info and code: http://laravel.io/forum/01-07-2016-model-observers-not-working-for-update

http://stackoverflow.com/questions/34663078/model-observer-not-working-for-update

**Comment by GrahamCampbell** [comment]
What laravel version please?

**Comment by vitroz** [comment]
I've tested with both 5.1 and 5.2

**Comment by GrahamCampbell** [comment]
What laravel version please?

As in, like 5.1.28, or what?

**Comment by vitroz** [comment]
5.1.28

**Comment by acasar** [comment]
@vitroz Can you paste the code where you update the model?

**Comment by vitroz** [comment]
Sure @acasar
Its in my controller, i get the data from my form and then perform the update inside the controller.

public function putEdit($id, StorePainelRequest $request){

        $painel = $this->painelRepository->find($id);     

        if (!$painel) {
            Flash::error('Painel não existe.');
            return redirect('/gestor/painel/index');
        }

        $data = $request->only('pai_app_id', 'pai_titulo', 'pai_subtitulo', 'pai_classcss', 'pai_observacao'); 

        $painel = $this->painelRepository->update($data,$painel->pai_id, 'pai_id');

        if (!$painel) {
            Flash::error('Erro ao tentar salvar.');
            return redirect()->back()->withInput($request->all());
        }

        Flash::success('Painel atualizado com sucesso.');
            return redirect('/gestor/painel/index');
    }

**Comment by lagbox** [comment]
How is that repository updating the model?

**Comment by vitroz** [comment]
@lagbox The repository is simply an instance of my model, so it has access to all the Model class methods

obs: Sorry for the delayed response! and still no luck solving this.

**Comment by acasar** [comment]
@vitroz Your didn't provide correct parameters for the update method: https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/Model.php#L1475

And also, update events are only fired when you update your model directly without building a new query.

So, this will fire events:
```php
$model = MyMOdel::find($id);
$model->update($data);
```

And this won't:
```php
MyModel::where('id', $id)->update($data);
```

That's intentional, since updating models with a query could potentially update millions of rows at once and it's a huge performance issue to fire events for each updated row.

**Comment by vitroz** [comment]
Thank you guys so much for the support and help!
@acasar One last thing, could you provide me the right way to perform the update in my case?

The only query method i'm using is the "update",so the events are not firing because i'm using the repository instance? (I'll only be able to test it tomorrow, that's the reason for this question, sorry and thanks!)
    $painel = $this->painelRepository->update($data,$painel->pai_id, 'pai_id');

**Comment by acasar** [comment]
Instead of:
```php
 $painel = $this->painelRepository->update($data,$painel->pai_id, 'pai_id');
```

Try doing:
```php
 $painel->update($data);
```

**Comment by vitroz** [comment]
@acasar Passing by to confirm, this solved it for me, thanks!

**Comment by PadawanTony** [comment]
@acasar Can you please explain why the following is true?

This works: `User::find(1)->update(['earings' => 0]);`

While this doesn't: 
```
$user = User::find(1); 
$user->earings=0; 
$user->update(). 

```
In the second case, the event is not being fired. Can you explain why? What is the difference between the two statements? Aren't they both mass assignment? From what I see the only difference is that in the second statement we run the `update()` method without passing the data (since we have already modified it through the $user instance). Is this the reason the event is not being fired? And why?

**Comment by acasar** [comment]
The second case is wrong. You should call save() instead of update(). Please refer to the docs.

**Comment by PadawanTony** [comment]
I know how you can call save(). My question was about the lack of parameters in update().

Anyhow, I think I figured it out. There is this code in the `Model.php` in Laravel:

```
$dirty = $this->getDirty();

        if (count($dirty) > 0) {
            $this->setKeysForSaveQuery($query)->update($dirty);

            $this->syncChanges();

            $this->fireModelEvent('updated', false);
        }
```

In essence, `getDirty()` gives you the parameters you have passed (the data with which to update the instance); so, if you give it no data (like so: `update()`), it will never run the `$this->fireModelEvent('updated', false);` line, so the `updated` event will not be fired.

Or, at least this is what I understand.

**Comment by PadawanTony** [comment]
You are right. It will work with save(). But the question is why it doesn't work when update() has no parameters.

**Comment by thaifani** [comment]
you can do it such this
````php
$bookTrip=BookingTrip::where('id',$bookTrip_id)->where('driver_id',$driver_id)->first();
$bookTrip->current_status='new_status';
$bookTrip->save()
````

**Comment by Hadid74** [comment]
> You are right. It will work with save(). But the question is why it doesn't work when update() has no parameters.

When issuing a mass update via Eloquent, the saving, saved, updating, and updated model events will not be fired for the updated models. This is because the models are never actually retrieved when issuing a mass update
