### ISSUE TITLE
Eloquent ORM: using substr in hasOne

### ISSUE THREAD

**Issue by AviRns** [laravel/framework#11774]
I have two tables **user** and **pno**

**user:**
```ticket_no as (tno.file_no) eg 499385```

**and pno:**
```
tno eg. 99385
file_no, eg. 4
```

every user has one pno.

How can i use?
```return $this->hasOne('Userpno','tno', substr('ticket_no',1);```
to relate these two table in one to one.

Please help.
Thanks

**Comment by GrahamCampbell** [comment]
Please direct questions to the fourms.
