### ISSUE TITLE
[5.2] Migration Error on Creating Integer Field with specific size

### ISSUE THREAD

**Issue by evertramos** [laravel/framework#11776]
When creating a new field (on a new migration), integer, specifying the size of this field, such as in:

<code>
$table->integer('age', 4);
</code>

It assumes as 'not null', 'auto_increment' and 'primary key' automatically, which is not always applicable.

**Comment by GrahamCampbell** [comment]
That's because the 2nd parameter isn't the size, it's a boolean value.

**Comment by GrahamCampbell** [comment]
```
    /**
     * Create a new integer (4-byte) column on the table.
     *
     * @param  string  $column
     * @param  bool  $autoIncrement
     * @param  bool  $unsigned
     * @return \Illuminate\Support\Fluent
     */
    public function integer($column, $autoIncrement = false, $unsigned = false)
    {
        return $this->addColumn('integer', $column, compact('autoIncrement', 'unsigned'));
    }
```

**Comment by evertramos** [comment]
Sorry... my bad. Thank you very much! I will read everything before posting...

**Comment by GrahamCampbell** [comment]
No worries at all. You're not the first person to have been confused by this. This is like the 20th time I've been asked about this. ;)
