### ISSUE TITLE
[5.2] PasswordBroker forces confirmation

### ISSUE THREAD

**Issue by CupOfTea696** [laravel/framework#11775]
The `PasswordBroker` forces a password confirmation, even when a custom validator is set. I think that, at least when setting a custom validator, you should leave people the choice of whether or not they want to use a password confirmation field.

See [PasswordBroker.php#L201](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Auth/Passwords/PasswordBroker.php#L201)

**Comment by GrahamCampbell** [comment]
We're open to PRs. ;)
