### ISSUE TITLE
[5.2] Should Model::unguard()/reguard() still be called in DatabaseSeeder class?

### ISSUE THREAD

**Issue by danieliancu** [laravel/framework#11786]
I saw that in L 5.2 the calls to `Model::unguard()` and `Model::reguard()` were removed from the DatabaseSeeder class, but they are still mentioned in docs.

**Comment by GrahamCampbell** [comment]
Thanks for the report. We're open to PRs to the docs. Since this not a bug in the framework, I'm going to close this.

**Comment by danieliancu** [comment]
I will asume the answer is no.
