### ISSUE TITLE
Conditionally define a variable within a view to avoid undefined variable notices

### ISSUE THREAD

**Issue by kelvinj** [laravel/framework#11789]
Problem:
Notices being thrown when a variable isn't defined.

Current solution:
1. All controllers that use a view have to declare all variables
2. In blade having to `@if (isset($var) && $var)` and `{{$var or ''}}`

To counter this issue, we declare a Blade directive that allows us to initialise variables:

```php
Blade::directive('init', function ($expression) {
    $php = <<<'VAL'
<?php
// variable initialisation
foreach (array%s as $__init_k => $__init_v) {
    $__init_default = null;

    if (!is_numeric($__init_k)) {
        $__init_default = $__init_v;
        $__init_v = $__init_k;
    }

    if (!isset($$__init_v)) {
        $$__init_v = $__init_default;
    }
}
?>
VAL;
    return sprintf($php, $expression);
});
```

This allows us to do this:

```php
@init('var')
```

or multiple variables with defaults:

```php
@init('title' => 'Our great website', 'meta' => 'Some blurb about our site')
```

This works well for us.

If this is something that would be of interest in the framework itself, I'd be happy to put a PR together.

Cheers.

**Comment by EliasZ** [comment]
>Just use <?php $foo = 'bar'; ?>

https://github.com/laravel/framework/issues/1844#issuecomment-21733531

**Comment by kelvinj** [comment]
@EliasZ it's more akin to `<?php $foo = $foo ?? 'bar'; ?>` in PHP 7.

**Comment by kelvinj** [comment]
On second thoughts, I think this belongs in an extension.
