### ISSUE TITLE
Middleware StartSession do not working!!!

### ISSUE THREAD

**Issue by XingFang** [laravel/framework#11787]
Hi,my laravel is 5.2,when i use {!! csrf_field() !!} in my test.blade.php ,i find "_token" is null,then i call 
session()->has("_token"),return false,i call session()->->isStarted(),return the same result...when i put the  \Illuminate\Session\Middleware\StartSession::class from $middlewareGroups  to the $middleware,everything is OK !  i don't why!!This is my problem or framework BUG?
![qq 20160109225658](https://cloud.githubusercontent.com/assets/13644079/12216670/9b6e6ec4-b724-11e5-8a9a-8fa3e701cf0a.png)
![qq 20160109225731](https://cloud.githubusercontent.com/assets/13644079/12216673/b0c44564-b724-11e5-851b-99b68a32d95d.png)

**Comment by GrahamCampbell** [comment]
Looks like you forgot to put your route inside the web middleware group.

**Comment by XingFang** [comment]
thank you !! but I remember do not this step in laravel5.1

**Comment by GrahamCampbell** [comment]
> thank you !! but I remember do not this step in laravel5.1

Yes. Please see the L5.2 upgrading docs

**Comment by GrahamCampbell** [comment]
Or, just add this middleware to your global middlewares to get the same behaviour as in 5.1 if you want.

**Comment by XingFang** [comment]
Just contact laravel5.2,I'm a little uncomfortable.I will remember your say。thank you !!
