### ISSUE TITLE
Use custom monolog configuration and laravel default configuration at the same time

### ISSUE THREAD

**Issue by xian13** [laravel/framework#11781]
Hi @taylorotwell,

monolog configurator force us to choose either using our own monolog configuration or using default laravel monolog configuration.

What I want to achieve is that because monolog can have multiple handlers, I want to using my configuration and laravel default configuration at the same time.

It isn't possible because according this commit 3ed034e23677155acbe963068fbd950f4e9e4bdb, you use if else.

```
if ($app->hasMonologConfigurator()) {
    call_user_func(
        $app->getMonologConfigurator(), $log->getMonolog()
    );
} else {
    $this->configureHandlers($app, $log);
}
```

Can we use this instead ?
```
if ($app->hasMonologConfigurator()) {
    call_user_func(
        $app->getMonologConfigurator(), $log->getMonolog()
    );
}
$this->configureHandlers($app, $log);
```

And in the configureHandlers
```
/**
 * Configure the Monolog handlers for the application.
 *
 * @param  \Illuminate\Contracts\Foundation\Application  $app
 * @param  \Illuminate\Log\Writer  $log
 * @return void
 */
protected function configureHandlers(Application $app, Writer $log)
{
    if (! ($logConfiguration = $app['config']['app.log'])) {
        return;
    }

    $method = 'configure'.ucfirst($logConfiguration).'Handler';

    $this->{$method}($app, $log);
}
```

so we still can use laravel default configuration if we want to, if we don't want, we could set the app.log to null.

If you agree, I'll create a PR about it.

Thank you.

**Comment by GrahamCampbell** [comment]
These issues arn't a way to contact Taylor. Please discuss on slack, or just go straight to a PR as implied by our docs.

**Comment by bhuvidya** [comment]
So @xian13 did you do a PR for this? I want the same thing! If you haven't done a PR and it's still not possible to do this then I will do one. Your approach seems sound.

**Comment by xian13** [comment]
@bhuvidya because the discussion was ended, I didn't make the PR. But what I do to achieve this is creating a Service Provider that push handler to the monolog in boot method.
