### ISSUE TITLE
Integers are being casted as string in the collection when using SQL Server

### ISSUE THREAD

**Issue by malhayek2014** [laravel/framework#11780]
Hello - 

I found an issue when I change my database from MySQL to SQL server. The problem occurs when I use eloquent to get data from a model. The problem is that all the attributes are casted to string (or probably not casted correctly).

To help you see the issue, I produced the same step on both MySQL and SQL Server.

Here is my code
	$surveyPools = QuestionPool::where('status', 'Active')
									   ->where('survey_id', $this->interview->survey_id)
									   ->get()
									   ->keyBy('id');

	$pools = $surveyPools->pluck('id');

	$questionToPoolRelation = QuestionToPool::whereIn('pool_id', $pools)->get();

Now, on MySQL the following code works like expected with no issues

	$questionToPoolRelation->where('question_id', $question->id);
	
However, it fails on SQL Server because the data set returned by `get()` treats integers as string.

To work around the problem I had to change my code to this
	$questionToPoolRelation->whereLoose('question_id', $question->id);

To give you visual of the problem have a look at the following 2 images

This is what I get with MySQL Server
![MySQL](http://s23.postimg.org/atcgj78aj/Screenshot_3.png)

This is what I get with MS SQL Server

![SQL Server](http://s14.postimg.org/wnrm36ukh/Screenshot_2.png)

To help you validate the schema  here is a copied from my migration script

        Schema::create('survey_questions_to_pools', function(Blueprint $table)
        {
            $table->increments('id');
            $table->integer('question_id')->unsigned()->index();
            $table->integer('pool_id')->unsigned()->index();
            $table->enum('status',['Active','Inactive'])->default('Active');
            $table->nullableTimestamps();
        });

**Comment by JoostK** [comment]
This is probably an issue with the PDO driver, which in the case of MySQL (using the mysqlnd driver) returns data as defined by the database schema, whereas the SQL Server seemingly returns strings in all cases.

Perhaps you can try some PDO settings to change this behaviour, check [here](http://stackoverflow.com/a/20123337/171436) on what flags may be set, although the link is for MySQL (I do not know how it would work with SQL Server).

**Comment by malhayek2014** [comment]
@JoostK thank you so much for this info.
Here are the options that are available for the SQL Server driver http://php.net/manual/en/ref.pdo-sqlsrv.php. any idea on which one that that would solve this problem?

**Comment by hiendv** [comment]
@malhayek2014 Try MySQL Native Driver `mysqlnd` : http://php.net/manual/en/book.mysqlnd.php
If you're running debian:
```
sudo apt-get install php5-mysqlnd
```
And don't forget to restart the web server.

**Comment by JoostK** [comment]
None listed there I guess, but I took only a quick glance. Did you try setting `PDO::ATTR_EMULATE_PREPARES` and `PDO::ATTR_STRINGIFY_FETCHES` as my earlier link suggests?

**Comment by malhayek2014** [comment]
@JoostK 
I added this
     PDO::ATTR_STRINGIFY_FETCHES => false,

but when adding this to the option I get an error
     PDO::ATTR_EMULATE_PREPARES => false,


  [PDOException]
  SQLSTATE[IMSSP]: The given attribute is only supported on the PDOStatement object.

**Comment by progmars** [comment]
I stumbled upon the same issue using PostgreSQL. But for me the difference indeed seems to be coming from PDO or PHP itself because I'm using the same version of Laravel and PostgreSQL on my local machine and server, but still ID fields are being read as integers on the server and as strings on local machine. I'm not sure what could we do to make it consistent and whether Laravel could do anything at all to help with the issue.

**Comment by spiderweb-solutions** [comment]
We are seeing the same issue but using MySQL on different servers. MySQL 5.5.46 and 5.7.10 on two Debian boxes, both running PHP 5.6.14-0+deb8u1 are both displaying ints as strings.

PHP 5.6.17 on a CentOS box running MySQL 5.5.44 is not displaying this issue.

**Comment by unitedworx** [comment]
I have this issue on different environments while both using mysql.

**Comment by barroca** [comment]
maybe we can add a function like whereInIntegerArray or add a string_escape parameter = false on whereIn clause. 

BTW, I share the same problem here, with the string cast the query takes 1.9s, and without, 0.1s

**Comment by barroca** [comment]
Just figure out that this issue is affecting Not just on whereIn() queries, but also on with() queries.

**Comment by adriandmitroca** [comment]
+1

Happened to me with MySQL on different environments.

**Comment by spencerdeinum** [comment]
For the people using Linux you need to check to see if you are using the `mysql` driver or the `mysqlnd` driver as already stated in this thread.

The `mysqlnd` driver casts between the sql datatypes and php types in the driver itself.

**Comment by restored18** [comment]
Going back to the issue with SQL Server, I'm running Laravel 5.3 and any integers in the database are being returned as strings for my Eloquent models. It doesn't do it with the same table structure on MySQL. Let me know if you need to see any code for verification.

**Comment by restored18** [comment]
Nevermind, looks like Microsoft fixed this issue [https://github.com/Microsoft/msphpsql](https://github.com/Microsoft/msphpsql). Loading the latest version of the SQL Server PDO driver allows you to add a PDO attribute for fetching integers as integers. Here is an SO thread about it as well: [http://stackoverflow.com/questions/31563747/laravel-pdo-settings](http://stackoverflow.com/questions/31563747/laravel-pdo-settings).

Looks like this issue can be closed.

**Comment by MichalKrakow** [comment]
Hi, 
just run into it in mid 2018 with newest version of PDO drivers (sqlsrv) so i put my solution:
in your config/database.php add the following options:
```
'sqlsrv' => [
            'driver' => 'sqlsrv',
            'host' => env('DB_HOST', 'localhost'),
            'port' => env('DB_PORT', '1433'),
            'database' => env('DB_DATABASE', ''),
            'username' => env('DB_USERNAME', ''),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
            'options' => array(
                PDO::ATTR_STRINGIFY_FETCHES => false,
                PDO::SQLSRV_ATTR_FETCHES_NUMERIC_TYPE => true
            )
        ],
```
and you're good to go.
cheers.

**Comment by fahmiegerton** [comment]
I got this problem too in my hosting (but not locally) and I'm using mariadb, anyway to fix it?

**Comment by Erutan409** [comment]
I don't think this is an ideal workaround, but this seems to be the only way I can get `bigint` to be properly cast as integers (regardless of the driver configuration):

```php
<?php

namespace App\Database;

use Illuminate\Database\Eloquent\Model as Base;

class Model extends Base {

    private static $castsCache = [];

    final public function getAttribute($key) {

        if (!empty($this->attributes) && !isset(static::$castsCache[static::class])) {
            static::$castsCache[static::class] = true;
        }

        return parent::getAttribute($key);

    }

    final public function getCasts() {

        if (!is_array($casts = data_get(static::$castsCache, static::class, []))) {

            $casts = [];

            foreach (array_keys($this->attributes) as $column) {

                if (str($column)->endsWith('_id')) {
                    $casts[$column] = 'int';
                }

            }

            static::$castsCache[static::class] = $casts;

        }

        return array_merge($casts, parent::getCasts());

    }

}
```

I was already using a custom base `Model` class. So, I added these overloads to do some [performant] casting for relationship id's. I'm very much welcome to someone picking this apart, suggesting a better solution.

**Comment by a-batashev** [comment]
I had this problem on shared hosting with MariaDB 10.5.
The problem was solved by disabling PHP extension "pdo_mysql" and enabling  "nd_pdo_mysql".
