### ISSUE TITLE
[5.2] Implicit route model binding a binded interface

### ISSUE THREAD

**Issue by cornex** [laravel/framework#11791]
Hello, I try to do a implicit route model binding on a interface that is binded to my User model but it wont work. I created a thread on Laracasts about this, so you can see the example over there. https://laracasts.com/discuss/channels/laravel/implicit-route-model-bind-a-contract

EDIT: Adding the example here as well

```php
// routes.php
$router->get('/implicit/{id}', function(App\Contracts\User $id){
    dd($id);
});
```
```php
// AppServiceProvider .php
class AppServiceProvider extends ServiceProvider
{
    /**
     * Hold the bidnings
     *
     * @var array
     */
    protected $bindings = [
        'user' => [\App\Contracts\User::class => \App\User::class],
    ];

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        //
    }

    /**
     * Register
     *
     * @return void
     */
    public function register()
    {
        if (! isset($this->bindings)) return;

        foreach ($this->bindings as $alias => $binding) {
            list($abstract, $concrete) = [key($binding), current($binding)];

            $this->app->bind([$alias => $abstract], $concrete);
        }
    }
}
```
```php
// User.php
class User extends Authenticatable implements Contracts\User
{
    protected $table = 'players';
}
```
````php
// Contracts/User.php
interface User
{

}
```

Is there a way to accomplish this? Thanks :)

**Comment by GrahamCampbell** [comment]
Thanks you for your question, but I politely ask that questions do remain on the forums.

**Comment by fulopattila122** [comment]
I'm also having this issue (type hinting with interface doesn't load the model). I dug in Laravel's source and I think I could implement it. The question is would that PR be accepted? If yes, I'll do it so it would be a nice addition to 5.5 ;)

**Comment by krychu90** [comment]
Still implicit model binding on interface is not working in Laravel 8.x
