### ISSUE TITLE
Locale vs Lang (In)-Consistency

### ISSUE THREAD

**Issue by superdummy** [laravel/framework#11792]
The default App of Laravel contains a `lang`  folder and interchangeable talks about language and locale. 

Improvements: 
Locale is the worlwide standard and reduces a lot of misconceptions (see below):
- Renaming the `"lang"` to `"locale"` folder (Maybe this is open for discussion whats a real best practice. There are frameworks using locales others using lang. But the following two points are extremely important):
- Most important: Introduce (also in the documentation) in the default App an example directory/file that uses a real "locale identifier" like `en_US.php`! Its fine having support for "catch all country locales" like `"en_*"` (in effect `"en"`) but it should be obvious (and also explicitly stated), that laravel internally support real locales (en_US) and not just "languages". 
- Officialy state that laravel is build around locales (and not only languages) and encourages to use real locales (as every more standard-conform application does)!. Also the `conf/app.php` file does not make this abvious. To make this abvious the best would be a default settings (in app.php) like
		`app.locale = 'en_US',`
		`app.fallback_locale' => 'en',`
		This would make it clear to everyone that full locales are supported

Why/Problems:
- Standardization (with all the many benefits)
- Missconceptions and Hacks: I was not aware, that laravel seems to support real locales like en_US. I ever thought (due to folder naming and documentation) that only languages is supported (like "en"). But my app internally uses real locales and I started to introduces messy hacks to convert between them. 
- I use some thridparty packages for translation handling: It seems they also are not aware of the laravel support of locales (due to the problems stated above). They now do not even support real locales (so I had to fork them and change a lot).

Thanks.

**Comment by Mevrael** [comment]
What are you suggesting except renaming lang to locale and en to en_US?

> But my app internally uses real locales and I started to introduces messy hacks to convert between them.

Could you tell a bit more about how are you using locales and how are you converting between them?

> I use some thridparty packages for translation handling: It seems they also are not aware of the laravel support of locales (due to the problems stated above). They now do not even support real locales (so I had to fork them and change a lot).

Could you link those packages and maybe your fork. What have you changed? What are your requirements?

In other words, I am asking for your opinion on how Laravel locale system could be done better because there will be probably many changes in 5.3.

**Comment by robclancy** [comment]
I remember thinking this years ago. Personally I like `translate` or just `t` which I use in other areas.

**Comment by matthew-sycle** [comment]
Ideally, the Lang/Country/Locale logic can be brought in line with Symfony:
http://symfony.com/doc/current/reference/forms/types/locale.html

We currently just had a breaking change affect us in https://github.com/micheleangioni/laravel-js-lang-converter/issues/4, as that package is following the Laravel convention, which uses the Language as the Locale (unlike Symfony).

**Comment by themsaid** [comment]
Closing since this is not actually a bug report.

For suggestions and feature requests please use the https://github.com/laravel/internals repo.
