### ISSUE TITLE
Auth middleware not running for closure route

### ISSUE THREAD

**Issue by leoncottell** [laravel/framework#11804]
Using latest version of Laravel (5.2.7)

I have a controller that calls $this->middleware('auth');	in it's constructor.

If I use this route, the middleware runs OK and redirects non authenticated users

Route::get('home', '\Crown\Http\Controllers\dashboard@showHome'); 

If I use a closure in the route instead, the authentication doesn't happen, can view even when logged out 

Route::get('home', function () { 
    return (new \Crown\Http\Controllers\dashboard)->showHome();
});

**Comment by GrahamCampbell** [comment]
That is because you're never meant to call `new Controller()` on your controler yourself, You MUST let the framework do that.

**Comment by GrahamCampbell** [comment]
Or, more seriously, call that method. That's bypassing the internals that make this work.
