### ISSUE TITLE
Nested route Model Binding

### ISSUE THREAD

**Issue by kevdotbadger** [laravel/framework#11805]
On 5.2 you can do stuff like

    Route::get('client/{client}', function(App/Client){
        return $client;
    });

which queries the Client model `->where(getRouteKeyName(), '=', $client);`

however, doing

    Route::get('client/{client}/project/{project}', function(App/Client $client, App/Project $project){
        return $project;
    });

obviously queries Project by the getRouteKeyName().

Would it be safe to assume that the second binding replies on the first binding? So shouldn't the query be more along the lines of `Project->where(Clients->getRouteKeyName(), '=', $client)->where(getRouteKeyName(), '=', $project);`?

Does this make sense? Or should it be better not use nested routes and just use single resources?

**Comment by GrahamCampbell** [comment]
Sounds bit overkill to me. Feel free to discuss on slack if you really want this though.
