### ISSUE TITLE
  [Symfony\Component\Debug\Exception\FatalErrorException]  Call to a member function filter() on null

### ISSUE THREAD

**Issue by appledev44** [laravel/framework#11814]
I am using L 5.1 version,

Following error comes when I fire "composer update" command

 [Symfony\Component\Debug\Exception\FatalErrorException]
 Call to a member function filter() on null

There is no any compiled.php file in vendor folder
Please suggest me about this.

**Comment by GrahamCampbell** [comment]
The compiled.php file is located in `bootstrap/cache`.
