### ISSUE TITLE
Prevent recursive view including (infinite recursion)

### ISSUE THREAD

**Issue by swayok** [laravel/framework#11813]
Hi, I've spent quite much time trying to fix issue with emails sending while real problem was in recursive view include. It is 100% my fault but I think it needs to be prevented by renderer because this situation is not throwing any errors or shows anything that explain what happened. Investigation might waste a lot of time.
Also it works different depending on OS:
In Windows this causes rendered template to be echoed without any explanation.
In Linux it causes "Segmentation fault". 

I think that including view inside itself is very rare situation, so

Suggestion 1:
1. Prevent including view inside itself by default (throw exception with clear message)
2. Add possibility to include view inside itself somehow (for example - by argument like $allowRecursion in @include())

Suggestion 2:
When recursion counter is high enough (something like 30-50+) - analyze situation and throw exception if there is infinite recursion. This should not affect perfomance or functionality and will solve the problem.

Thank you.

**Comment by GrahamCampbell** [comment]
Xdebug is designed to catch such issues for you. ;)

**Comment by swayok** [comment]
It still takes around 30 min in difficult situations.
