### ISSUE TITLE
Serialization of closure failed when using Mail::queue with use($request)

### ISSUE THREAD

**Issue by redgluten** [laravel/framework#11817]
It it possible that this has to do with PHP rather than Laravel but I’m not seasoned enough to clarify this.

Trying to pass a request to the closure on `Mail::queue()` results in the the following error: `Serialization of closure failed: Serialization of 'Closure' is not allowed`. The same code works with `Mail::send()`.

My method:

```php
    public function contact(ContactRequest $request)
    {
        Mail::queue('emails/contact-email', compact('request'), function($message) use ($request) {
            $message->from($request->email, 'New contact');

            $message->to(env('CONTACT_EMAIL'))->subject($request->subject);
        });

        return redirect()->route('/')->with('message', 'Your message was sent.');
    }
```

Tested on Laravel 5.1.

**Comment by GrahamCampbell** [comment]
This is the intended behaviour. You cannot serialise a request.

The following code will work for you though:

```php
    public function contact(ContactRequest $request)
    {
        $email = $request->email;
        $subject = $request->subject;

        Mail::queue('emails/contact-email', compact('request'), function($message) use ($email, $subject) {
            $message->from($email, 'New contact');

            $message->to(env('CONTACT_EMAIL'))->subject($subject);
        });

        return redirect()->route('/')->with('message', 'Your message was sent.');
    }
```

**Comment by GrahamCampbell** [comment]
Also, you should NEVER use the `env` function outside the `config` folder in Laravel. Infact, this will not work anymore starting from Laravel 5.2.
