### ISSUE TITLE
Listen Broadcast Events on Backend

### ISSUE THREAD

**Issue by dbpolito** [laravel/framework#11818]
I was playing around with Laravel Broadcasts events and it is really awesome, but when you have to pass data from Frontend to Backend there is no fancy way currently... Of course we could do normal ajax but as we already have a socket opened, i think it would be good if we could also use socket for that too...

I have a working prototype, which i will share here, if i got some :+1: with this i can open a proper PR for it.

### Gist with related files

https://gist.github.com/dbpolito/fe384eac8cc8a309cf49

### Entire laravel project

https://github.com/dbpolito/chat

## What this basically does is:

1. Socket server listen for all events and adds to redis channel (this needs better configuration)
2. Created a command that basically listen for redis channel and trigger events

Please let me know your thoughts...

**Comment by GrahamCampbell** [comment]
Please discuss on forums/slack.
