### ISSUE TITLE
[5.2] Routing: Controller `__call` method no longer called on non-existent methods

### ISSUE THREAD

**Issue by 4lun** [laravel/framework#11812]
I have a `__call` method in my controller to catch calls to non-existant methods from a route, but after upgrading to 5.2 it never gets called.

Instead an error is thrown:

    ReflectionException in Route.php line 264:
    Method App\Http\Controllers\PagesController::aboutUs() does not exist

It was very useful for serving static pages, as it avoided having dozens of controller methods that just returned a view.

For example, I could do the following and just serve a matching template (if it existed) based on the method name via the `__call` method (Advantage of using the method name was the path and name can change).

    Route::get('/about-us', [
        'as' => 'pages.about-us',
        'uses' => 'PagesController@aboutUs',
    ]);

Full example here: https://github.com/4lun/laravel-call-test/commit/ea10eb1c40b0a85e91411640b387e7f13ef987a5
Was this a deliberate change?

**Comment by rodrigopedra** [comment]
Why not overriding `missingMethod` method from `Illuminate\Routing\Controller`?

~~~php
namespace App\Http\Controllers;

class TestController extends Controller
{
    protected $staticRoutes = [ 'about-us', 'contact-us' ];

    public function missingMethod( $parameters = [ ] )
    {
        $path = reset( $parameters );

        if (!in_array( $path, $this->staticRoutes )) {
            return parent::missingMethod( $parameters );
        }

        return view( $path );
    }
}
~~~

**Comment by TheGIBSON** [comment]
+1, I came across the same problem.

**Comment by taylorotwell** [comment]
This isn't supported anymore. Maybe you can define a /{wildcard} route and handle it that way.
