### ISSUE TITLE
artisan queue:restart not working properly with daemon

### ISSUE THREAD

**Issue by Grummfy** [laravel/framework#11821]
Hello,
I know this bug as already been reported, but all issue related have been closed, example: #6950.

What's the issue:
* run queue daemon (```php artisan queue:work --daemon``` on 5.2)
* run ```ps |grep php``` you will see your process
* run queue restart (```php artisan queue:restart```)
* run ```ps |grep php``` process has been killed, not restarted

I test it with redis and rabbitmq drivers. Bug exist since 4.1 at least. If you need a working project to see the bug on action, I can provide one.

How It should work, when we do a restart, the process should be reloaded after spawining it.

Solution I see:
* fix to make this working as wanted and provided by the documentation => complex, but it could help
* adapt the documentation to say what it really do following you use daemon or listen option in queues => easy, no code to change, just habit of people

**Comment by GrahamCampbell** [comment]
What cache driver please?

**Comment by crynobone** [comment]
Correct me if I'm wrong, don't you still need supervisord (or equivalent) to start the new process.

**Comment by GrahamCampbell** [comment]
Yes, you are totally correct @crynobone. Restart just means "stop".

**Comment by Grummfy** [comment]
So I raise an issue in the documentation?

**Comment by lk77** [comment]
hello,
i've a question,
when i'm doing a queue:restart and then a ps, 
my workers are still there.

it's a cache problem?

thanks
