### ISSUE TITLE
AuthenticatesUsers trait doesn't response with JSON on AJAX request

### ISSUE THREAD

**Issue by socieboy** [laravel/framework#11820]
Hi, I just trying to make simple auth with Vue and Laravel, but I found each time that I send the request with wrong email and password the response is a redirect view (HTML), is there someway to fix that? or I have to overwrite the AuthController?

**Comment by johnschmuff** [comment]
Well that page it redirects to should have errors() array populated. Why couldn't you just populate a json encoded version of that array into a VueJS data? Which will be the login form to begin with so you could properly output the errors.
