### ISSUE TITLE
Schema timestamps() doesn't add default current on updated_at

### ISSUE THREAD

**Issue by sebastiansipos90** [laravel/framework#11829]
Hello,

I've wrote a simple migration using only the increments and timestamps() and mysql 5.5.46 on debian adds on created_at 
default: CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
because it's the first field and none have this specified.
This fella's post explains in detail what happens if you leave default timestamp fields: http://jasonbos.co/two-timestamp-columns-in-mysql/

#edit: laravel 5.2.6, php5.6.13

**Comment by EliasZ** [comment]
see #11518

This should be fixed [in 5.2.8](https://github.com/laravel/framework/commit/0c2b7da2635f7bbbaf63d1b93fa817232bdd9d65).
