### ISSUE TITLE
Add method signature PHPDOC to facades

### ISSUE THREAD

**Issue by meglio** [laravel/framework#11823]
Currently, using facades in an IDE is not so convenient as the IDE highlight methods as unrecognized ones.

For instance, when using the `Cache` facade:

```php
class Cache extends Facade { }
// ...
$user = Cache::get('user:'.$id);
```

... the call to `get()` gets highlighted by the IDE (PHPSTORM in my case). Also, after typing `::`, no popup with methods available is shown in the IDE.

Because all Cache engines implement particular interfaces (contracts), the issue can be easily fixed by adding PHPDOC signatures for all interface methods, for example:

```php
/**
 * @method mixed get(string $key, mixed $default) Retrieve an item from the cache by key.
 * @see \Illuminate\Cache\Repository
 */
class Cache extends Facade { ... }
```

The same goes for all facades.

**Comment by GrahamCampbell** [comment]
Sorry, there are no plans to add this.

**Comment by GrahamCampbell** [comment]
https://github.com/barryvdh/laravel-ide-helper might be of use to you though.

**Comment by meglio** [comment]
Making PHP code self-documenting in terms of PHPDOC has always been a good idea. Is there any particular reason you do not wish to accept the improvement, or would you accept a PR?

Alternatively, is there a way to access the instances without using facets and in that way that IDE recognizes all the methods correctly?

**Comment by hughgrigg** [comment]
@meglio you might prefer to inject instances of the classes that the facades use. That would get you the IDE benefits you want, among other things.

http://taylorotwell.com/response-dont-use-facades/

**Comment by meglio** [comment]
May I ask you for an example, please? I've read the article but haven't understood how it helps type-hinting.

Still, adding PHPDOC method declarations is not a challenging thing. If introduced, it would make type hinting work just out of the box, without the need to inject instances into controllers. Why are you against something that would improve on usability without requiring additional efforts - what is the logic behind your decision?

**Comment by jheagle** [comment]
I also find this to be a frustrating issue, it is unfortunate that I have to edit core laravel code to get this to work nicely with PHPStorm.
Adding the following did seem to resolve this for me:
```
 * @method static mixed get(string $key, \mixed $default) Retrieve an item from the cache by key.
```

**Comment by ardzz** [comment]
@jheagle if there many methods, do you write it manually?

**Comment by jheagle** [comment]
> @jheagle if there many methods, do you write it manually?

@ardzz For some of these it is helpful to add them, there is also the Laravel IDE Helper project which adds some automated support for method hinting (mentioned above in an earlier comment). I've just gotten used to ignoring them, though it occasionally bothers me still.
