### ISSUE TITLE
Updating to laravel 5.2.8 multi authentication not working

### ISSUE THREAD

**Issue by ssuhat** [laravel/framework#11842]
hi,

Today i've update my laravel version to 5.2.8 and made the multi authentication not working. I revert to 5.2.7 it's working perfectly.

here is my config/auth.php:
```
'guards' => [
        'client' => [
            'driver'   => 'session',
            'provider' => 'users',
        ],

        'admin' => [
            'driver'   => 'session',
            'provider' => 'admins'
        ],
]

'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model'  => App\User::class,
        ],

        'admins' => [
            'driver' => 'eloquent',
            'model'  => App\Admin::class,
        ],
]
```
Auth Controller:

```
$auth = auth()->guard('admin');
if ($auth->attempt(['email' => $request->email, 'password' => $request->password])) {
   /* all other stuff for login if success */
}
```

And i got this error:

![error](https://cloud.githubusercontent.com/assets/10653041/12287153/d860671c-b9fc-11e5-91ef-fb0a3c0dc21f.png)

Is this a bug or i make a mistake?

**Comment by tomschlick** [comment]
what is auth() outputting?

**Comment by tomschlick** [comment]
as in if you run 
```php 
dd(auth());
```

**Comment by tomschlick** [comment]
and does Auth::guard() work?

**Comment by ssuhat** [comment]
Default working perfectly. But if I specify it with guards name it became error .

**Comment by ssuhat** [comment]
I add 2 image for the dd result. is it enough? because the result is too long.

![1](https://cloud.githubusercontent.com/assets/10653041/12287759/ad192472-ba01-11e5-82ae-5c70e1483bf0.png)
![2](https://cloud.githubusercontent.com/assets/10653041/12287760/ad1d0ac4-ba01-11e5-950e-a69765911a46.png)

**Comment by imrealashu** [comment]
@ssuhat can you please send me entire working code. 
I have been trying to implement but laravel is not creating session for my admin table. https://github.com/laravel/framework/issues/11831 here's my code. please correct me if I'm doing it wrong.

**Comment by ssuhat** [comment]
hi @imrealashu i've update my above code. you can use it. :)

**Comment by imrealashu** [comment]
@ssuhat did you see any errors in my issue. Please have a look.

**Comment by ssuhat** [comment]
@imrealashu what laravel version (5.2.*) are you using? if you using like mine (5.2.8), you not alone. 

and i make the authentication from scratch instead of using laravel provide.

**Comment by imrealashu** [comment]
I'm using 5.2.8 and default laravel's authentication still not working. I will use yours. Thanks :+1:

**Comment by taylorotwell** [comment]
Fixed in 5.2.10.

**Comment by imrealashu** [comment]
@taylorotwell 
For user table, After authentication `Auth::user()` return json of logged in user. But if authenticated from another table lets say `admin` then its not returning any json.

**Comment by imrealashu** [comment]
I've resolved it.

If you're authenticating from `admin` table then use `admin` guard to get logged in admin's details.
e.g.,
`Auth::guard('admin')->user()` will return logged in admin's json.

**Comment by imrealashu** [comment]
@ssuhat I've done it here. http://stackoverflow.com/questions/34614753/can-anyone-explain-laravel-5-2-multi-auth-with-example/34783443#34783443 you can use default AuthController to authenticate Admin.

**Comment by Er-Pallavi** [comment]
hi whatsup :)
