### ISSUE TITLE
It's not possible to explicitly specify model binding in REST routes.

### ISSUE THREAD

**Issue by salarmehr** [laravel/framework#11841]
Consider this:
~~~~
Route::model('bar', '\App\Models\AModel');  // the issue is the same with or without this line. 
Route::resource('foo/bar', 'MyController');
~~~
Laravel will look for a model named `Bar` for all REST routes (e.g. for `foo/bar/2` it looks for a `Foo` model with `id=2`). It seems it is not possible to map that resource to another model (e..g `Baz` model).

**Comment by jingmaoxiaoqiang** [comment]
yes I have the same question

**Comment by lagbox** [comment]
If you are talking about implicit bindings, those are matched up via the name of the parameter to the name of the variable that is type hinted in the method. You can have that type hinted as any model you want. There is nothing special about the resource to model relationship here.

```php
Route::resource('blah/foo', 'UController');

class UController ....
{
    public function show(\App\User $foo)
    {
        dd($foo);
    }
}

// http://yoursite/blah/foo/1
```

You would get the User model with id 1 dumped out.

**Comment by salarmehr** [comment]
@lagbox That simply does not work!

**Comment by lagbox** [comment]
Works fine for me for all implicit bindings in 5.2.

**Comment by GrahamCampbell** [comment]
I don't see a bug here?

**Comment by salarmehr** [comment]
@lagbox Thanks for you response. Actually the issue was posted for version 5.1. Now, it's works as expected.
