### ISSUE TITLE
Request: IBAN validation

### ISSUE THREAD

**Issue by thijsdemaa** [laravel/framework#11854]
Since all banks will be using IBAN account numbers from now on, might it be a good idea to add this as a validation rule?

**Comment by alexwhitman** [comment]
There's [plenty of packages](https://packagist.org/search/?q=iban) which validate and generate IBANs already including [intervention/validation](https://packagist.org/packages/intervention/validation) which adds Laravel validation methods.

**Comment by thijsdemaa** [comment]
Hi Alex, thanks! I will look into this package. Sorry to bother you with
this (a)
Op wo 13 jan. 2016 om 15:51 schreef Graham Campbell <
notifications@github.com>
