### ISSUE TITLE
Collection::random($amount) returns element if $amount equals 1

### ISSUE THREAD

**Issue by powelski** [laravel/framework#11851]
`Illuminate\Support\Collection` class has nice `random()` method. It returns a random element if we don't specify the number of entries to be returned, or collection otherwise. There is one exception: if we set `$amount` to `1`, it returns an element.

This might seem like convenient solution, but it rather leads to problems. Consider the following code:
```
$amount = rand(1, $fruits->count());
$pickups = $fruits->random($amount);
```

Even though I'm using the same method signature: `Collection::random(int $x)`, the return type is different depending on the value of an argument.

I think it would be more stable to always return a collection if `$amount` is provided and a random element otherwise.

**Comment by GrahamCampbell** [comment]
This is a duplicate.

**Comment by JoostK** [comment]
A duplicate of what? Quick search for 'collection' or 'random' does not find an open issue.

I have had the same issue where I needed to constrain `$amount` based on the actual number of elements in the collection. If there is only a single item, you'd unexpectedly get only a single element back. I avoided the problem by subclassing and introducing an additional method to fix the issue:

```php
use Illuminate\Support\Collection as BaseCollection;

class Collection extends BaseCollection
{
	public function sample($amount = 1)
	{
		switch ($amount = min($amount, $this->count()))
		{
			case 0: return new static;
			case 1: return new static(array(parent::random(1)));
			default: return new static(array_values(parent::random($amount)));
		}
	}
}
```

**Comment by powelski** [comment]
I found the duplicated issue and commented on it: #11654

**Comment by powelski** [comment]
And @JoostK +1 for you for returning empty collection if `$amount` equals 0.
