### ISSUE TITLE
[Proposal] Create contract(s) around `Dotenv` and promote it to a proper singleton

### ISSUE THREAD

**Issue by HipsterJazzbo** [laravel/framework#11868]
The `Dotenv\Dotenv` library includes a number of pretty useful methods for requiring that certain environment variables be set, and that they match certain values or types of value.

Currently, there's no elegant way to use these features within Laravel because of the way `Dotenv` is booted directly instead of being loaded into the IoC container ([here](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Bootstrap/DetectEnvironment.php#L21)).

I propose that we:

1. Create one or two contracts to wrap `Dotenv`. Perhaps `Foundation\Environment\Loader` and `Foundation\Environment\Validator`.
2. Bind those contracts as singletons early in the `Application` boot process. Perhaps in `Illuminate\Foundation\Application::registerBaseBindings()`
3. Use those bound instances when we load the `.env` file in `Foundation\Bootstrap\DetectEnvironment`.

The benefit here is that that any developer or package maintainer that wishes to can resolve `Illuminate\Contracts\Foundation\Environment\Loader` (or whatever) and properly `require()` environment variables with an explicit error at boot time, rather than the current solution which is just for the app to throw a cryptic error when something breaks because `env()` returned null.

I believe this change could be made as a minor update (currently against 5.2), because since you can't currently access the instance of `Dotenv` the the framework is using, there's no chance anyone's doing anything with it that could break.

If we think this is a cool idea I'll throw together a PR.

:heart:

**Comment by GrahamCampbell** [comment]
:-1: from me

**Comment by GrahamCampbell** [comment]
Just add a custom bootstrapper.

**Comment by GrahamCampbell** [comment]
You can easily choose the bootstrapper to use the kernel classes.

**Comment by GrahamCampbell** [comment]
Futher more, we don't even load the environment if the config is cached anyway.

**Comment by HipsterJazzbo** [comment]
That's doesn't really address the issue. I can't access the same, already configured instance that Laravel has loaded. The only way is to reload the .env from scratch into a new instance, which seems wasteful and… gross






On Wed, Jan 13, 2016 at 1:38 PM -0800, "Graham Campbell" <notifications@github.com> wrote:












Just add a custom bootstrapper.

**Comment by GrahamCampbell** [comment]
> The only way is to reload the .env from scratch into a new instance, which seems wasteful and… gross

The overhead isn't that large.

**Comment by HipsterJazzbo** [comment]
Hmm okay. I feel like there's value to be had in a framework-supported way for package maintainers to be able to easily and explicitly indicate what their environment variable requirements are, rather than just writing it in the readme and hitting a cryptic error when something's not set correctly.

I suppose the proper way is to use a configuration item and load the environment variable from there.
