### ISSUE TITLE
Querying "has" relationship withTrashed no longer works

### ISSUE THREAD

**Issue by andrewtweber** [laravel/framework#11860]
Seems like the "has" query has been updated to exclude trashed content. In general, a good idea, but I'm specifically looking for users that have deleted content.

My model:

```php
class User extends Eloquent {
    public function deletedVideos() {
        return $this->hasMany(Video::class, 'deleted_by_user_id')
            ->withTrashed();
    }
}
```

Attempting to query users who have deleted videos:

```php
$users = User::has('deletedVideos', '>=', 3)->toSql();
```

This returns:

```sql
select * from `users` where (select count(*) from `videos` where `videos`.`deleted_by_user_id` = `users`.`id` and `videos`.`deleted_at` is null) >= 3
```

Notice that it is ignoring `withTrashed` and adding the check that `deleted_at` is null. This was working previously in 5.1. 

Can be fixed with `whereHas`

```php
$users = User::whereHas('deletedVideos', function ($query) {
    $query->withTrashed();
}, '>=', 3)->get();
```

But this behaves differently in 5.2 so I think it should either be marked as a bug or added to the upgrade documentation

**Comment by acasar** [comment]
@andrewtweber Which minor version of 5.2 are you using? 5.2.8?

**Comment by andrewtweber** [comment]
@acasar  5.2.6

**Comment by acasar** [comment]
@andrewtweber I figured out the problem. I'll send a PR in a minute.

**Comment by andrewtweber** [comment]
Thanks @acasar  and Taylor
