### ISSUE TITLE
Validator gets coupled to translated messages too early

### ISSUE THREAD

**Issue by progmars** [laravel/framework#11869]
This is not a bug but a request or a proposal to improve Validator, so it doesn't do unnecessary work of resolving text translations when it is not asked to.

I understand that this might be not an issue for most of Laravel users, but current Validator behavior seems to me suboptimal also purely from architecture point of view. Therefore I'd like to attract some attention to this bit of information, so maybe more active Laravel maintainers could improve things for next Laravel versions.

The long story.

Validator is so flexible and powerful, that I decided to use it in my business logic layer (BLL). I can create validation rules dynamically and add custom errors and do some fancy stuff with it. 
When BLL is done and detects a validation failure, it returns the validator instance to controller. Now the controller formats the validator errors as nicely formatted JSON and returns the response.

Everything works fine until I add custom error messages and attribute names to the mix. 

There is one important thing to understand before I continue the explanation. I do not store custom error messages and attributes in default validation.php file, mostly to prevent this file from getting huge and to avoid merge commits when working in a team. 
Instead, I put custom messages into individual  translation files for my application pages. Therefore I have to use the following code to point the validator to my messages:

```
$validator->setAttributeNames($customAttributeNames);
$validator->setCustomMessages($customErrorlMessages);
```

I do not want to call the code above inside my BLL - it clearly has nothing to do with translation, and I don't want to polute my BLL with translation key constants. The solution - I call the code inside my controller. 

But this approach does not work because at the point when BLL has returned the Validator instance to the controller, the Validator has already executed its `validate()` method which, unfortunately, (through a long chain of methods) is immediately filling messages array with texts resolved through `$this->translator->trans()`. *And this is the cause of a problem and seems wrong* IMHO.

Essentially, my *desired* code flow is as follows (rough pseudo-code alert)::

```
BLL:

v = Validator::make(input, rules)

if(v->fails())
    return v

Controller:

receives validator
if (count(v->failed()){
   v->setCustomMessages(messagesFromCustomPage)
   return response with nicely formatted v->errors()->getMessages()
}
```

This does not work, my custom messages are ignored because  the validator filled them once during `fails()` call and after that `setCustomMessages` doesn't have any effect on the validator.

So, in my controller I actually have to do it like this:

```
Controller:

receives validator

 v->setCustomMessages(messagesFromCustomPage)

if (->fails()){
   return response with nicely formatted v->errors()->getMessages()
}
```

Then it works, because after setting custom messages I call `fails()` again. This seems wrong and also bad for performance reasons because I already know that the validator has failed, why should I call `fail()` (which in turn runs all the rules again - especially bad for `unique` and `exists` queries which use database) just to make custom messages effective?

In my opinion, Validator should postpone resolving text messages to the moment when it is being rendered, and that is when I call `getMessages()`.

Also, there might be some specific scenarios when I do not need those translated texts at all (maybe some automated service API which returns only raw error keys instead of human-readable messages). Why should Validator do the unnecessary work to translate the messages during validation process if it is not asked to do so?

Again, maybe that's not an issue and I'm using Validator wrong and it is meant to be used only for request validation and error resolving to human-readable translated texts. But then, if I decided to implement a validator for my BLL layer, it, most probably, would turn out to duplicate much of Laravel Validator's code, and I don't want to reinvent the wheel, I'd like to use the existing wheel but make it more round because now it feels a bit angular (hope, this metaphor makes sense).

**Comment by GrahamCampbell** [comment]
We're open to PRs. ;)
