### ISSUE TITLE
Add more details about how Faker is used in Laravel documentation

### ISSUE THREAD

**Issue by meglio** [laravel/framework#11872]
Here is the citation from the [current Laravel documentation](https://laravel.com/docs/5.2/testing#model-factories):

> The Closure will receive an instance of the Faker PHP library, which allows you to conveniently generate various kinds of random data for testing.

However, the [Faker documentation](https://github.com/fzaninotto/Faker) says there are many various providers available: Base, Lorem, Person, ...

Which providers are added by Laravel by default into the generator? How can we use our own providers (suppose one needs a french generator, not an English one), etc.

**Comment by GrahamCampbell** [comment]
You can just customize this stuff yourself in code as and when you need it.
