### ISSUE TITLE
Artisan without mandatory arguments should output usage

### ISSUE THREAD

**Issue by zupolgec** [laravel/framework#11878]
I think that when an Artisan command is used without the mandatory arguments, it should print the usage instead of/with the error.

**Comment by riyuk** [comment]
+1 for that.

`artisan make:migration` should - without further arguments - just act like `artisan make:migration --help`.
While the current implementation is technical correct it should be `more user-friendly` and list a solution to the problem.

**Comment by TiBianMod** [comment]
+1 I like the idea

**Comment by GrahamCampbell** [comment]
We're open to PRs. ;)
