### ISSUE TITLE
Question re artisan conventions: event:generate vs make:migration

### ISSUE THREAD

**Issue by meglio** [laravel/framework#11877]
Hi, would like to find out if there is any reason why generation commands are inconsistent (at least it seems to be so).

The example is this: to generate an event, I'd write `event:generate`
But to generate a migration, I'd write `make:migration`

Why not just
`event:generate` and `migration:generate`
OR
`make:event` and `make:migration`

**Comment by peterpan666** [comment]
Well tell me if I'm wrong but make:event does exists.

`event:generate      Generate the missing events and listeners based on registration`
`make:event          Create a new event class`

**Comment by meglio** [comment]
You mean both exist but their purposes are different, do you?

**Comment by CupOfTea696** [comment]
Yes, the purpose is different. `make:event` will just create a new event by name, while `event:generate` will check your EventServiceProvider and generate any missing Events and Listeners, hence it is under the `event` namespace in artisan.

**Comment by peterpan666** [comment]
@meglio yep, exactly what said @CupOfTea696 ;)
