### ISSUE TITLE
Make paragonie/random_compat an actual dependency

### ISSUE THREAD

**Issue by JordanAdams** [laravel/framework#11880]
We're currently depending on `Illuminate/Support` and using it's `Str::random()` method. Today after a composer update I was hit with the error that `random_bytes` was missing.

`Illuminate/Support` only requires `php >= 5.5.9` however `random_bytes` isn't native in this version. Since `paragonie/random_compat` is needed for `Illuminate/Support` to be fully functional on 5.5.9 wouldn't it be safer to make `paragonie/random_compat` an actual dependency instead of simply a suggested one.

**Comment by GrahamCampbell** [comment]
It is a dependency of laravel/framework, and it's made intentionally optional in illuminate/support.

**Comment by GrahamCampbell** [comment]
People MUST read the suggested dependencies composer prints out on install.

**Comment by GrahamCampbell** [comment]
We don't want to force dependencies on people who aren't even using that part of the package, or who are already on php 7.

**Comment by JordanAdams** [comment]
I think this is a pretty dangerous decision really. This change crippled our registration system and wasn't even versioned as a breaking change from what I can see. I don't think it's fair to say that people should be checking suggested dependencies every time they do a composer update when pinned to a major version. Surely preventing breaking changes like this is the reason we follow semver?

**Comment by JordanAdams** [comment]
I'm also pretty sure making this a full dependency wouldn't affect PHP 7 users.

**Comment by GrahamCampbell** [comment]
> I'm also pretty sure making this a full dependency wouldn't affect PHP 7 users.

Yes it would. It would force them to load a dependency that they don't need.

**Comment by GrahamCampbell** [comment]
> This change crippled our registration system and wasn't even versioned as a breaking change from what I can see.

Yes it was. Laravel does NOT follow semver. MINOR releases are BREAKING.

**Comment by barryvdh** [comment]
I would agree that it should probably be noted somewhere, also for the 'stand alone' packages, a changelog or similar, with these breaking changes..

**Comment by GrahamCampbell** [comment]
> I would agree that it should probably be noted somewhere

It is noted. On `composer update` composer would have printed a warning of a new suggested dependency.

**Comment by JordanAdams** [comment]
> Yes it would. It would force them to load a dependency that they don't need.

It may not be needed, however it wouldn't affect PHP 7 users at all and would allow the package to work on `>= 5.5.9` by default.

> It is noted. On composer update composer would have printed a warning of a new suggested dependency.

It's really not safe to assume suggested packages as warnings. The fact is, they aren't. They're just informational and should not be required for the package to work.

Taken from the composer schema docs:

> Suggested packages that can enhance or work well with this package. **These are just informational** and are displayed after the package is installed, to give your users **a hint** that they could add more packages, even though **they are not strictly required**.

**Comment by GrahamCampbell** [comment]
> They're just informational and should not be required for the package to work.

That's not true at all. The whole point of suggested packages is to allow you to use all the features.

**Comment by GrahamCampbell** [comment]
Take, for example, we don't force you to install redis stuff.

**Comment by JordanAdams** [comment]
Str::random() working on the PHP version listed as supported is not a feature...

Your example of not installing Redis stuff is completely irrelevant here. That would be an enhancement that is not required for the package to work.

**Comment by GrahamCampbell** [comment]
> That would be an enhancement that is not required for the package to work.

How is having redis broken not the same as having the random function broken. Both require suggested dependencies.
