### ISSUE TITLE
[feature request] Add Db::value() to retrieve a single value with using a raw SQL query

### ISSUE THREAD

**Issue by meglio** [laravel/framework#11896]
Unless I've missed it, there is no way to retrieve a single value instantly and directly with running a raw mysql query.

A `value()` method would be convenient in many cases.

**Comment by BraxtonFair** [comment]
This seems like a good idea, but what parameters would be used? Would it be something like DB::value($table, $row, $column) or something like that? I would be more than happy to attempt and make this, but how do you see this? A bit more information?

**Comment by meglio** [comment]
I thought about an extension to raw queries as that's what I missed in a real use-case in my application that's being built on top of Laravel.

Here is an example from Laravel's documentation re raw queries:

`DB::select('select * from users where active = ?', [1]);`

I'd use the same approach for `DB::value()` - it would help in many cases where it's easier to write a raw query quickly and select a count of something, or some ID, or some value, or some calculation:

`DB::value('select max(salary) from users where ...complex condition...', [params]);`
`DB::value('select count(salary) from users where ...complex condition...', [params]);`

I personally love raw queries - they are much more readable than eloquent-based queries: the more complex the queries, the less readables they are when build with using ORM. That's why some of the queries I prefer to express in a raw SQL. But with no way to get a single value, it just take more lines of code to retrieve a row, then a single value.

Hope it makes sense :)

**Comment by bmitch** [comment]
There is `selectOne` which I think is pretty close to what you are looking for:

`DB::selectOne('select count(id) from users where ... complex condition...', [params]);`

Which would return something like:

```
{#1901
  +"count(id)": 564
}
```

Are you thinking the value method would return the raw value like this?

`DB::value('select count(id) from users where ... complex condition...', [params]);`

Returns the integer `543`

**Comment by vlakoff** [comment]
Method `selectOne` is *exactly* what you are looking for.

See [Connection.php](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Connection.php):

    public function selectOne($query, $bindings = [])
    {
        $records = $this->select($query, $bindings);

        return count($records) > 0 ? reset($records) : null;
    }

**Comment by OS16X** [comment]
>Method selectOne is exactly what you are looking for.

 I disagree that the `selectOne` method solves exactly what @meglio was suggesting.

As suggested by @bmitch 
    DB::value('select count(id) from users where ... complex condition...', [params]);
would return the actual value without the need for the key/value pairs

The alternative would always need an extra line of PHP to do the job - for example:
        $max_score = DB::selectOne($q, [$this->section_id]);
        $max_score = reset($max_score);
