### ISSUE TITLE
Directory separator

### ISSUE THREAD

**Issue by paulodealmeida** [laravel/framework#11893]
Hi, I found a problem in the framework, when I try to validate my form I can't show errors.
Reading the code, it is happening because the directory separator is set "/". So when I am running my app on Windows I can't validate it because all the the directory separators are set "/".
I don't know the rules to fix it in all the code, so can anyone tell me how can I do that or fix it replacing "/" to PHP DIRECTORY_SEPARATOR?

**Comment by briedis** [comment]
Windows should not care in paths about /, but nix* on the other hand does.

Probably the problem is elsewhere. Show us your code and error message.

**Comment by GrahamCampbell** [comment]
PHP internally normalizes them anyway.
