### ISSUE TITLE
[Proposal] Extract testing into a separate Illuminate component

### ISSUE THREAD

**Issue by dschniepp** [laravel/framework#11895]
It would be possible to share the testing helpers with ease between Laravel and Lumen.

To achieve this only little work needs to be done:

1. Move all `traits` from `Illuminate/Foundation/Testing/` to `Illuminate/Testing`
2. Extract the Cookie/Session/Redirect related methods from `MakesHttpRequests.php` and move it into a separate `trait`.

Lumen can depend on `Illuminate/Testing` and use only some of the `traits` in its basic `TestCase.php`.

What do you think?

**Comment by GrahamCampbell** [comment]
Thanks, but we don't process proposals on github.
