### ISSUE TITLE
Laravel v5.1.27 - Route:: not working when inside group.

### ISSUE THREAD

**Issue by silverdr** [laravel/framework#11908]
I have a strange situation with one of the routes
```
    Route::get('/v1/user/locks', 'UserLockController@index');
```
When standalone - works as expected.
When I place it inside the group:
```
    Route::group(['prefix' => 'v1/user'], function () {
        ...
        ...
        Route::get('locks', 'UserLockController@index');
        ...
    });
```
I receive 404 back before the controller in question gets a chance to serve the request.
```
    $ php artisan route:list
```
shows correct assignments in both cases. URLs are correct, controller@method as well.

Unfortunately I can't publish the whole route.php file but there is nothing special and all other routes seem to work correctly. It does seem like a kind of a framework bug and I apologise for not providing a truly correct report on that. Is it a known issue?

**Comment by GrahamCampbell** [comment]
Your prefix is missing a slash on the end is it not?

**Comment by GrahamCampbell** [comment]
What does the route list command show for both cases?

**Comment by brunogaspar** [comment]
> Your prefix is missing a slash on the end is it not?

No, it's not required.

--

Doesn't seem a bug on the framework, but rather an issue on your end as i'm not seem to be able to reproduce this.

Without seeing the entire routes file, that's all i can assume, you have an error somewhere.

This is what i tried with a fresh clone of 5.1:

Code

```php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group([ 'prefix' => 'v1/user' ], function () {
    Route::get('locks', function () {
        return 'Hello';
    });
});
```

Output on console: http://d.pr/i/ojs8

When i hit the `/v1/user/locks` i get the `Hello`, which is the expected.

**Comment by GrahamCampbell** [comment]
Thanks @brunogaspar.

**Comment by silverdr** [comment]
Route outside the group:
```
|        | GET|HEAD | v1/user/locks                                                |                                                   | App\Http\Controllers\UserLockController@index               | oauth2     |
|        | GET|HEAD | v1/user/locks/{id}                                           |                                                   | App\Http\Controllers\UserLockController@show                | oauth2     |
```
Route inside the group:
```
|        | GET|HEAD | v1/user/locks                                                |                                                   | App\Http\Controllers\UserLockController@index               | oauth2     |
|        | GET|HEAD | v1/user/locks/{id}                                           |                                                   | App\Http\Controllers\UserLockController@show                | oauth2     |
```
The same (except name) when using:
```
Route::resource('locks', 'UserLockController', ['only' => ['index', 'show']]);
```
inside the group:
```
|        | GET|HEAD | v1/user/locks                                                | v1.user.locks.index                               | App\Http\Controllers\UserLockController@index               | oauth2     |
|        | GET|HEAD | v1/user/locks/{locks}                                        | v1.user.locks.show                                | App\Http\Controllers\UserLockController@show                | oauth2     |
```

**Comment by silverdr** [comment]
@brunogaspar if this is a framework error - it probably is one of those "esoteric" ones, which pop up only in a peculiar combination of other factors, which is why probably not many people experienced it. Note that other routes (even the second one to the same controller) seem to work. I'll try to get the permission to show the whole file (at least with comments stripped).

**Comment by silverdr** [comment]
Here comes the whole routes.php file:

[routes.php.zip](https://github.com/laravel/framework/files/93053/routes.php.zip)

**Comment by brunogaspar** [comment]
> if this is a framework error - it probably is one of those "esoteric" ones, which pop up only in a peculiar combination of other factors, which is why probably not many people experienced it. Note that other routes (even the second one to the same controller) seem to work. I'll try to get the permission to show the whole file (at least with comments stripped).

I don't agree, at all. I use route groups all the time and i never encountered such issues. Just register the routes correctly and it'll work as expected.

> Here comes the whole routes.php file:

Tried your routes file but replaced the `Controller@method(s)` with closures because i don't have those controllers (and don't feel on creating them) and it worked fine, the only thing i would change is to move the `Route::get('{user_id?}', 'UserController@show');` to the bottom (still inside the route group) otherwise routes like that `locks` one will not work, which is expected, because you have that "catch all route" `'{user_id?}'`.

**Comment by silverdr** [comment]
@brunogaspar it is not about agreeing, really. It is about facts. And facts are that I never said that it *IS* a bug in the framework. Only that it looks so, at least to me, after trying many different combinations. And since I use route groups all the time too and never before experienced similar problem - it would have to be something "esoteric" (in case it was a bug). But - thanks a lot for explanation, which I needed. The trick was with the "catch all route", which wasn't meant to be one to catch them all and I didn't realise somehow that the first match wins, rather than the last (which obviously makes sense). Thank you once more - moving the "catch all" to the bottom solved the problem.
