### ISSUE TITLE
Laravel 5.1 queue job marked as failed with php artisan queue:listen --tries=3

### ISSUE THREAD

**Issue by shahidnajam** [laravel/framework#11905]
I am having problem with queue job and marking them as failed.
There is no error or exception with the queue job. When i try to send email using queue. some time it works and some time it is marked as failed job without any exception or error.

Let say,
There are 10 queue jobs to process.

With php artisan queue:listen --tries=3
it fails 3-5 times and rest of them processed successfully.
3-5 are marked as failed and there are no error or exception in log files.

With php artisan queue:listen --tries=10
It processes all successfully. No failed job at all.

Any idea? Why does it behave like this with less tries even there is no error at all?

**Comment by GrahamCampbell** [comment]
I can't replicate this issue.

**Comment by GrahamCampbell** [comment]
Feel free to open a new issue if you're able to provide something much more specific.

**Comment by dennisoderwald** [comment]
You found a solution to solve it @shahidnajam?

We have the same problem: sometimes jobs failing without exception / logging - we see the job run in __construct() - but stop after __construct().

**Comment by bastian-schur** [comment]
Same here.

I use Laravel 5.1 and run some jobs with the laravel queue worker. Sometimes the job would be marked as failed, but the job logic is successfully finished. 
And i have no errors or exceptions too!

**Comment by Bodom78** [comment]
Currently suffering from random silent queue fails after moving an application to a new server.

Really difficult to debug this issue.

**Comment by praveenreddy84** [comment]
I'm facing similar issue with laravel 5.1. anyone found reason?
