### ISSUE TITLE
trans() acts differently than Lang::get() sometimes...

### ISSUE THREAD

**Issue by vladrusu** [laravel/framework#11914]
Please also see:
https://github.com/laravel/framework/issues/2249
This still an issue in 5.2, it was closed but not resolved.

Take this example:
Lang::get('key', [], 'en') gets the translation for key (english locale), but
trans('key', [], 'en') gets the translation for current locale, because the third argument in trans() helper stands for $domain variable (not used), and not locale

Solution: remove the $domain parameter in these helpers:
    public function trans($id, array $parameters = [], $domain = 'messages', $locale = null)
    public function transChoice($id, $number, array $parameters = [], $domain = 'messages', $locale = null)

Theoretically, IMHO, trans and trans_choice should be just "aliases" for Lang::get and Lang::choice and have the same parameters.

**Comment by GrahamCampbell** [comment]
We're open to PRs. ;)
