### ISSUE TITLE
[Proposal] Allow custom email user email field to have a custom name

### ISSUE THREAD

**Issue by deframe** [laravel/framework#11912]
Hey all,

I'm wondering if it's worth allowing the email field used by **Illuminate\Foundation\Auth\ResetsPasswords** to be changeable? It currently assumes a field name of 'email' which this is passed through the reset form, validated then sent through as a credential to *Password::broker($broker)->reset(...)*.

This could be problematic if a user model has more than one email address (e.g. home_email, work_email, etc). Handling the authentication of such a user is easily done by overriding getters in **Illuminate\Auth\Authenticatable** but no such facility exists for resetting passwords.

The **Illuminate\Auth\Passwords\CanResetPassword** trait already has a *getEmailForPasswordReset()* method - could there also be a *getEmailNameForPasswordReset()* or something to that effect which is used throughout?

Thanks for reading, hopefully that makes some sort of sense!

**Comment by GrahamCampbell** [comment]
Thanks, but we don't process proposals on github.
