### ISSUE TITLE
Laravel Array Validate Issue

### ISSUE THREAD

**Issue by mnking** [laravel/framework#11917]
My request input is below
```php
$inputs = [
    'items' => [
        [
            'sku' => 8984884843883,
            'style' => 'NWMS12',
        ],
        [
            'style' => 'NWMS00',
        ]        
    ]
];
```

My rules:

```php
$rules = [
    'items.*.sku' => 'required'
]
```

items.1 is missing sku attribute but the validator does not show any error

**Comment by EliasZ** [comment]
What code are you using to validate?

**Comment by themsaid** [comment]
Missing keys are not supported, I created a pull request to fix this issue:
https://github.com/laravel/framework/pull/11885

However my solution only fixes the `required` rule but neglects the `sometimes` rule, I'll fix it and push again.

**Comment by mnking** [comment]
OK . Thank themsaid
