### ISSUE TITLE
Laravel 5.2 auth validator redirects to wrong page

### ISSUE THREAD

**Issue by ChumburidzeGio** [laravel/framework#11915]
Since I upgraded to laravel 5.2 i had some issue with Auth, validator on fails redirect me to homepage instead of /login or /register.

I tried to display errors on home page and its working !

The only problem was wrong redirect paths

For this problem I found solution: 

changed in **vendor/laravel/framework/src/Illuminate/Foundation/Auth/RegistersUsers.php**
line 58-60 with

            return redirect('register')
                        ->withErrors($validator)
                        ->withInput();

and in **vendor/laravel/framework/src/Illuminate/Foundation/Auth/AuthenticatesUsers.php**   
on line 117 replace `return redirect()->back()` with `return redirect('login')`

is this problem by wrong configuration or its by 5.2 ? 

there is my route.php

    Route::group(['middleware' => 'web'], function () {
        Route::auth();
        Route::get('/soc/{provider}', 'Auth\AuthController@redirectToProvider');
        Route::get('/soccallback/{provider}', 'Auth\AuthController@handleProviderCallback');
        
        
        Route::get('/', 'PostController@index');
        Route::get('/page.index', 'PageController@index');
        Route::get('/page.id/{id}', 'PageController@show');
        
    });

**Comment by lagbox** [comment]
The AuthController uses those 2 traits you modified. You can just override those methods in your AuthController without touching anything in `vendor`.
What version of 5.2 are you using?

**Comment by ChumburidzeGio** [comment]
Yes i know but i prefer changing vendor its more safe i think.. 
5.2.10 is my version

**Comment by EliasZ** [comment]
Heads up: changing files in the vendor directory is not more safe and eliminates most advantages of a using a dependency manager. On a next update of your dependencies, you will face problems.

**Comment by ChumburidzeGio** [comment]
Yeah rigth but why i got that problem?
