### ISSUE TITLE
[5.1] Saving morphTo relation.

### ISSUE THREAD

**Issue by SachinAgarwal1337** [laravel/framework#11918]
When I try to perform `save()` or `create()` on `morphTo` relation of my `User` model. It always gives this error:
```
Call to undefined method Illuminate\Database\Query\Builder::create()
```

Where as if I do the reverse, i.e., If I perform `save()` or `create()` from `morphOne` relation of my `Admin` model. It works perfectly.

Is this a bug? or is it suppose to be like this?

```
// User model:
 public function profile()
 {
    return $this->morphTo('profile', 'profile_type', 'profile_id');
 }

// Admin model:
public function user()
{
    return $this->morphOne(User::class, 'profile', 'profile_type', 'profile_id', 'id');
}

```

**Comment by patrickcarlohickman** [comment]
It's supposed to be like this. `morphTo` relationships are treated as the `belongsTo` side of the relationship. `morphOne`/`morphMany` relationships are treated as the `hasOne`/`hasMany` side of the relationship.

The `belongsTo` side of the relationship does not have the `save()`/`create()` methods. It has the `associate()` method. Only the `hasOne`/`hasMany` side of the relationship has the `save`/`create` methods.

**Comment by SachinAgarwal1337** [comment]
thanks.
