### ISSUE TITLE
required_if error!

### ISSUE THREAD

**Issue by derakoola** [laravel/framework#11925]
And another bug!

this is request array:
![screen shot 2016-01-17 at 2 58 49 pm](https://cloud.githubusercontent.com/assets/5869562/12377218/d8984070-bd2a-11e5-8cd5-8408731fa212.png)

and this is the result!
```answer_type``` equals "image" but an error generated!
```other_image``` filed accept images but when I chose a video it skip ```answer_type```!!!

![screen shot 2016-01-17 at 3 02 36 pm](https://cloud.githubusercontent.com/assets/5869562/12377228/62bcd9b4-bd2b-11e5-9fa5-c6529921653c.png)

**Comment by themsaid** [comment]
@derakoola I think there were a lot of fixes in this area during the past month, can you please check if you still have the same issue after you update to the latest version?

**Comment by derakoola** [comment]
@themsaid You are right, It's ok now. I have already updated that, And I found It fixed.

**Comment by themsaid** [comment]
@GrahamCampbell ^^

**Comment by GrahamCampbell** [comment]
Thanks. ;)

**Comment by themsaid** [comment]
👍
