### ISSUE TITLE
isHttpException() breaks backward compatibility when updating from 5.2.5 to 5.2.10

### ISSUE THREAD

**Issue by halaei** [laravel/framework#11922]
After updating from v5.2.5 to v5.2.10, I found that 
`Illuminate\Foundation\Exceptions\Handler::isHttpException()` does not return true when validations inside http requests are failed. It breaks our custom exception handler which used to work fine:

```php
namespace App\Exceptions;
...
class Handler extends ExceptionHandler
{
    ...
    public function render($request, Exception $e)
    {
        ...
        if ($this->isHttpException($e)) {
            return parent::render($request, $e);
        }
        ...
    }
}
```

**Comment by halaei** [comment]
I guess the problem is somewhere else. Maybe, validation exceptions did not use to reach this code at all. Now they do.

**Comment by GrahamCampbell** [comment]
It was a bug that in earlier 5.2 versions this wasn't happening. The current behaviour is what was meant to be there since 5.2.0.

Hope that makes sense. ;)

**Comment by halaei** [comment]
I also put `HttpResponseException` in `$dontReport` array. I guess you should put it there in laravel/larave project as well for default. Currently, it is not there. Am I right?

```php
    protected $dontReport = [
        AuthorizationException::class,
        HttpException::class,
        ModelNotFoundException::class,
        ValidationException::class,
        HttpResponseException::class,
    ];
```
