### ISSUE TITLE
Move Auth-scaffold routes to routes.stub?

### ISSUE THREAD

**Issue by EliasZ** [laravel/framework#11923]
Maybe the (`Illuminate\Auth`-dependent) `auth` method from `Illuminate\Routing\Router` should be removed - as there is already [a stub file](https://github.com/laravel/framework/blob/master/src/Illuminate/Auth/Console/stubs/make/routes.stub) the auth routes can go in? Right now, the stub calls the `Router::auth()` method.

https://github.com/illuminate/routing/blob/master/Router.php#L256

As removing a method is a breaking change, I suggest marking it as deprecated as of the next minor version bump and removing it in 5.3.

Thoughts?

**Comment by GrahamCampbell** [comment]
Please discuss proposals on slack. We don't process these on github since are issues are here for the community to fix bugs in the framework, and are not a way to communicate with Taylor really.
