### ISSUE TITLE
bindParam() or bindValue() rather than execute()

### ISSUE THREAD

**Issue by scottconnerly** [laravel/framework#11938]
Context: I'm working with MySQL, and don't have deep knowledge about Postgres, SQLite, or SqlServer. So I can't really speak to if this makes sense for all 4 together, or if it's a MySQL-specific problem (I suspect it might be).

In Illuminate\Database\Connection::select()
$statement->execute() is called to apply the bindings and execute the query in one step.

I propose we break that up into two steps. First, looping through each binding individually and then second, executing. What this allows us, is to have the option to bind each parameter in a different way.

As it is, MySQL PDO's execute() binds all parameters as a PDO::PARAM_STR. Normally this is fine.
I'm looking at doing a whereBetween(). In this case, I want the 'BETWEEN' values to be evaluated as integers, therefore PDO::PARAM_INT, and the target column is a varchar. Right now, MySQL is evaluating these as a series of characters, rather than the whole number's value (since both the param and column are characters. more on this later).

So rubber hitting the road, we might pass a new argument to Database\Query\Builder::whereBetween() specifying the data type. That gets passed through to addBinding() (which, yes, would require building the bindings in a slightly more complex way). But this extra info would be brought to bear when doing the bindParam()

So, granted, I'm trying to do numerical comparisons on a column of strings, so you might not care TOO much about this problem. FWIW, the column represents postal codes, which IMHO *should* be stored with the leading 0's preserved, as well as the fact that international postal codes are strings not integers. In the mean time, I'm going to have to have two (nearly identical) columns on the table, one for the postal code, and one for the (if US) integer representation of the zip code. Doing the WHERE BETWEEN clause with a PDO::PARAM_STR on an INT column does produce the desired results.

Raw MySQL queries for reference:
Works: select * from postal_codes where postal_code between 9999 and 10101;
Doesn't: select * from postal_codes where postal_code between '9999' and '10101';

**Comment by themsaid** [comment]
This was modified in 5.3, int & float => PARAM_INTEGER the rest => PARAM_STR

**Comment by y471n** [comment]
I could be wrong, but I don't think it's still fully working as said.
In float column it does take evaluates to integer, but the medium int column still gets evaluated to string in 5.3.
