### ISSUE TITLE
[5.2] Route Reflection error

### ISSUE THREAD

**Issue by MicMonen** [laravel/framework#11939]
In Laravel 5.2 when you use dot seperated names for controller binding in the IOC container like e.g. 'contact.controller' instead of 'Acme\Controllers\Contact' it will throw a PHP Reflection error.

The signatureParameters in Routing/Route.php (257) will search for an concrete class.

**Comment by MicMonen** [comment]
closed?

**Comment by GrahamCampbell** [comment]
We don't support this.

**Comment by MicMonen** [comment]
Why not? It can be used in 5.1 and it's not mentioned in the changelog or docs. You just decided everyone must just the same key in de IOC as the real namespace of the controller class?

**Comment by MicMonen** [comment]
You guys just closing issues without reasons...

**Comment by GrahamCampbell** [comment]
> You guys just closing issues without reasons...

Err, no?

> We don't support this.
