### ISSUE TITLE
Encrypt - Interoperability concerns?

### ISSUE THREAD

**Issue by drowe** [laravel/framework#11931]
The 'encrypt' method serializes data using PHP serialization, with the corresponding 'decrypt' method doing the unserialization.

Is there no expectation if interoperability with platforms outside of Laravel / PHP? Why should a client receiving encrypted data be required to implement PHP unserialization?

If there is reasoning as to why serialize / unserialize are needed, shouldn't this be made more clear?

**Comment by GrahamCampbell** [comment]
Thanks, but we don't process proposals on github.
