### ISSUE TITLE
[5.1] Provide a way to set input stream in artisan (console) command unit tests

### ISSUE THREAD

**Issue by berniegp** [laravel/framework#11946]
In Laravel 4.2 and 5.0, it was possible to provide an input stream when unit testing interactive artisan commands. This seems to be removed in 5.1.

Here is an example of how I tested commands before:
```
use Mockery as m;
use App\Console\Commands\AddClientCommand;
use Symfony\Component\Console\Tester\CommandTester;

public function setUp() {
    parent::setUp();

    $this->store = m::mock('App\Services\Store');

    $this->command = new AddClientCommand($this->store);

    // Taken from laravel/framework artisan command unit tests
    // (e.g. tests/Database/DatabaseMigrationRollbackCommandTest.php)
    $this->command->setLaravel($this->app->make('Illuminate\Contracts\Foundation\Application'));

    // Required to provide input to command questions (provides command->getHelper())
    // Taken from ??? when I first built my command tests in Laravel 4.2
    $this->command->setApplication($this->app->make('Symfony\Component\Console\Application'));
}

public function testAnswerQuestions() {
    $commandTester = new CommandTester($this->command);

    // Simulate keyboard input in console for new client
    $inputs = $this->command->getHelper('question');
    $inputs->setInputStream($this->getInputStream("New Client\n"));
    $result = $commandTester->execute([]);

    $this->assertSame(0, $result);
    $templatePath = $this->testTemplate;

    // Check console output
    $this->assertEquals(1, preg_match('/^Client \'New Client\' was added./m', $commandTester->getDisplay()));
}

protected function getInputStream($input) {
    $stream = fopen('php://memory', 'r+', false);
    fputs($stream, $input);
    rewind($stream);
    return $stream;
}
```
(my related [stackoverflow question](http://stackoverflow.com/questions/34814954/laravel-5-console-artisan-command-unit-tests))

In Laravel 5.1, `Illuminate\Console\Command::run()`, the [Symfony "helperSets"](http://symfony.com/doc/current/components/console/helpers/questionhelper.html#testing-a-command-that-expects-input) are now overridden so this approach doesn't work.

```
    public function run(InputInterface $input, OutputInterface $output)
    {
        $this->input = $input;
        $this->output = new OutputStyle($input, $output);
        return parent::run($input, $output);
    }
```

When a question is asked (from `Symfony\Component\Console\Style\SymfonyStyle`)
```
    public function askQuestion(Question $question)
    {
        // [snip]
        if (!$this->questionHelper) {
            $this->questionHelper = new SymfonyQuestionHelper();
        }

        $answer = $this->questionHelper->ask($this->input, $this, $question);
        // [snip]
        return $answer;
    }
```

The `QuestionHelper` class has a `setInputStream` method which would allow fake input, but it's not accessible from the unit tests.

**Comment by GrahamCampbell** [comment]
We're open to PRs. :)

**Comment by GrahamCampbell** [comment]
5.1 is closed for such changes though.

**Comment by deanmraz** [comment]
@berniegp did you figure this out?

**Comment by berniegp** [comment]
@deanmraz unfortunately, no.

**Comment by lioannou** [comment]
I came across this GitHub repo while googling something similar. A blog post from @themsaid helped me with what I needed : http://themsaid.com/building-testing-interactive-console-20160409/

Might indirectly solved your problem (as you can still test interactivity in the console).

**Comment by markdwhite** [comment]
To summarise the applicable content linked to by @lioannou 

`        // Mock the ask method only`
`        $command = Mockery::mock("\Project\Console\Commands\SomeCommand[ask]");`
`        $command->shouldReceive('ask')`
`           ->once()`
`            ->andReturn('a valid return');`

**Comment by mtvbrianking** [comment]
> I came across this GitHub repo while googling something similar. A blog post from @themsaid helped me with what I needed : http://themsaid.com/building-testing-interactive-console-20160409/
> 
> Might indirectly solved your problem (as you can still test interactivity in the console).

Did you manage to implement this for Laravel 5.2,5.3,5.4!
