### ISSUE TITLE
5.2 str_slug();

### ISSUE THREAD

**Issue by phpuzem** [laravel/framework#11947]
https://github.com/laravel/framework/blob/5.2/src/Illuminate/Support/Str.php#L39-L46

str_slug("ö");
str_slug("ü");

returns => oe ;
returns => ue ;

any suggestions ?

**Comment by GrahamCampbell** [comment]
This is intended.

**Comment by yusufyilmaz** [comment]
@phpuzem You had the same issue with Turkish characters, I suppose. Have you resolved your issue with current framework `str_slug` helper? I could not understand why this is a intended behavior. @GrahamCampbell Can you elaborate more about the intended helper behavior?

**Comment by yusufyilmaz** [comment]
I have found more details on these:
https://github.com/laravel/framework/issues/11619
https://github.com/laravel/framework/issues/16622

Sorry for any inconvenience. Best

**Comment by blackfyre** [comment]
@yusufyilmaz You can refer to my blog article on how to fix this issue: https://blackfyre.ninja/blog/fixing-slug-generation-problems
