### ISSUE TITLE
[5.2] Can't set where condition to Route::resource

### ISSUE THREAD

**Issue by tkawaji** [laravel/framework#11945]
In 5.2, I want to set where condition to Route::resource same as Route:get.
But I couldn't, because return value of Route::resource is null.
Is there any way to do that?

**Comment by phroggyy** [comment]
What exactly is it you want to do with it?

**Comment by tkawaji** [comment]
For example,
when I define routes with 
```php
Route::resource('services', 'ServicesController');
```
I want to add constraint '[0-9]+' on {services} parameter.

**Comment by lagbox** [comment]
This could be added via the options array if we wanted.

```php
Route::resource('services', 'ServiceController', ['where' => [
    'services' => '[0-9]+'
]]);
```
I have a working copy of this.

This has to run those keys through `getResourceWildcard()` to make sure the pattern is applied to what the parameter will actually end up as.

@taylorotwell  @GrahamCampbell any thoughts?

**Comment by lagbox** [comment]
@tkawaji  If you want this feature at the moment I can create a gist with how to extend and bind a new ResourceRegistrar. If there is a need for this I will create a PR to add it.

**Comment by tkawaji** [comment]
@lagbox Thank you for your mension. Because I could resolve this temporarily with my monkey patch, I don't need it immediately. So please create PR.

**Comment by lagbox** [comment]
@tkawaji I was playing around with this as an idea
 https://gist.github.com/lagbox/dcffd8367d51cc52aa85
