### ISSUE TITLE
[5.1] Make CrawlerTrait and InteractsWithPages traits usable in unit tests

### ISSUE THREAD

**Issue by berniegp** [laravel/framework#11948]
`Illuminate\Foundation\Testing\TestCase` uses the `CrawlerTrait ` which in turn uses `InteractsWithPages`. The latter provides methods to query a Symfony DomCrawler which is populated automatically in the `makeRequest()` method.

The different methods of `CrawlerTrait` (e.g. get(), action(), etc.) do not call `makeRequest()` so the methods of `InteractsWithPages` which depend on the crawler fail. It would be nice to have those methods function properly. If this is out of scope, then perhaps those methods should be removed from the trait.

**Comment by GrahamCampbell** [comment]
We're open to PRs. ;)
