### ISSUE TITLE
Image is being thrown as a white blank image

### ISSUE THREAD

**Issue by canfiax** [laravel/framework#11959]
I am experiencing a very strange error that is happening everywhere in my app where I return an image. When a image is being returned in browser, it looks like this white little square:

![image](https://cloud.githubusercontent.com/assets/3786627/12342627/89f79f74-bb2c-11e5-997e-bab9eaaf9814.png)

The code used to return this:

    return response(File::get(public_path().'/images/my-image.png'), 200)->header('Content-Type', 'image/png');

I have ensured the image path is valid, that the image is valid (I can access it without issues if I open it directly from its public path), and checked any error logs (nginx + laravel.log).

If I die and dump the values of `File::get(public_path().'/images/my-image.png')` I get PNG encoded data.

If I cURL to the path, it looks like this:

![image](https://cloud.githubusercontent.com/assets/3786627/12421771/0938b4ea-bec4-11e5-8dc3-0b88d4d4f110.png)

![image](https://cloud.githubusercontent.com/assets/3786627/12421816/2e1b1c62-bec4-11e5-8382-2bb0a8c075e2.png)

It happens on both staging, production and local machine (3x local machines testet - 1 windows, 2x mac osx). It occurred suddenly - it used to work fine previously.

I am stuck with this bug. Any suggestions?

**Comment by GrahamCampbell** [comment]
Please ask on the forums. I don't think this is a bug.

**Comment by canfiax** [comment]
Are you sure? Any ideas how I can debug further? I am not the only one experiencing this.

**Comment by canfiax** [comment]
I have tried removing all vendor service providers to see if anything could conflict, but that does not work either.

**Comment by canfiax** [comment]
If you have any ideas to point me in a direction of debugging further I'd be grateful!
