### ISSUE TITLE
[5.2] DB::transaction ->  PDOException : There is no active transaction

### ISSUE THREAD

**Issue by ethmelly** [laravel/framework#11969]
i have the following code:
```php
$new_models = DB::transaction(function () use ($supplier, $address, $addressDetail) {            
            $new_supplier = $this->setNewSupplier($supplier);
            $new_address = $this->setNewAddress($address);           
            $new_addressDetail = $this->setNewAddressDetail($addressDetail,$new_address->id);           
            $this->syncSupplierAddress($new_supplier->id,$new_address->id);
            $this->updateControlAp($new_supplier->supplier_id);   
            return [$new_supplier, $new_address, $new_addressDetail];
        });
```
the set methods are basically creating the models object with save() at the end;
Now this works perfectly fine if 2nd...nth fails BUT NOT if the first one fails.
 If 
```php
$this->setNewSupplier($supplier);
```
fails than i get
```
 "PDOException in Connection.php line 541:
There is no active transaction"
```
Am i doing something wrong here ? Also if i comment "$this->rollBack();" from the catch in vendor Connection.php it actually gives me the SQL error. Important part here is that this isn't working only if first save() fails

PS. I am using PostgreSQL not MySQL but i don't think its related

**Comment by GrahamCampbell** [comment]
I think this has been fixed now. :)

**Comment by treyerl** [comment]
How did you fix it?

**Comment by mkdesignn** [comment]
I'm still fighting with this problem, When it gets fixed, how and what was the problem?
