### ISSUE TITLE
artisan vendor:publish doesn't work when tag and provider are both used.

### ISSUE THREAD

**Issue by arleslie** [laravel/framework#11966]
If you use --tag and --provider it will respond with: `Nothing to publish for tag [].`

Example of bug: https://gist.github.com/arleslie/9979c62e9f5152edd72c

**Comment by billmn** [comment]
Which version of Laravel are you using?

**Comment by GrahamCampbell** [comment]
Closed due to insufficient information. Please create a new issue if you want to provide enough information, as per our contribution guidelines.

**Comment by arleslie** [comment]
I read the contribution guidelines. Not really seeing what the issue is.
The example is a clear way to reproduce and the title of the issue states what the bug is as well as a code sample. 

The only thing missing is the version of laravel which is 5.1.
