### ISSUE TITLE
Make Model::asDateTime() understand its protected field $dateFormat

### ISSUE THREAD

**Issue by meglio** [laravel/framework#11963]
Currently, asDateTime()` tries to convert user input to a valid Carbon date instance considering the following options:

1. Value is a DateTime
2. Value is numeric
3. Value is in format Y-m-d
4. Value is in format as by current database grammar

However, the `asDateTime()` method should also understand the Model's `$dateFormat` protected field. Chances are, if I output dates in `$dateFormat`, I also ask user to input dates in the same format.

This should go between points 3 and 4, as the generic `Y-m-d` format should have less priority than `$dateFormat`, if the latter is specified.

Without this feature, the mass-assignable date fields need personal mutators to be set up manually.

**Comment by meglio** [comment]
The inconsistency of the `asDateTime()` can also be understood by looking at the following method:

```php
/**
     * Get the format for database stored dates.
     *
     * @return string
     */
    protected function getDateFormat()
    {
        return $this->dateFormat ?: $this->getConnection()->getQueryGrammar()->getDateFormat();
    }
```

So, this means `Model` will use its field `dateFormat` not only for getter formatting, but also for SQL queries. If `dateFormat` is used for queries, this means it should be used when interpreting user input (when mass-assigning values) as well.

**Comment by meglio** [comment]
Also, looking at this citation from Laravel documentation:

> If you need to customize the format of your timestamps, set the $dateFormat property on your model. This property determines how date attributes are stored in the database, as well as their format when the model is serialized to an array or JSON.

May I propose that output formatting and storage formatting are two different settings. If there are many nationalities using the application, every one will have their own formatting rules. Still, in SQL queries there will be still used a single format.

**Comment by GrahamCampbell** [comment]
We're open to PRs. :)

**Comment by malhal** [comment]
I hit this problem today, toArray calls asDateTime which creates a Carbon using the dateFormat, and then afterwards it calls serializeDate which again uses the dateFormat to convert it back again. This makes it impossible to set a dateformat for serialization, e.g.

```
    public function show($id)
    {
        $model = $this->newModel()->findOrFail($id);
        $model->setDateFormat('u');
        return $model;
    }
```

Exceptions with:

```
{
  "error": "InvalidArgumentException",
  "reason": "Trailing data"
}
```

**Comment by malhal** [comment]
I've done the PR and if accepted I'll update the documentation too

**Comment by Illizian** [comment]
> We're open to PRs. :)

Apparently not, as the PR kindly submitted by @malhal was closed by @taylorotwell without much investigation seemingly. Could you help me to understand why? As this still seems to be a problem in 2021!
