### ISSUE TITLE
[5.2] Middleware executing too early

### ISSUE THREAD

**Issue by Lykegenes** [laravel/framework#11962]
Hi,

I have a middleware in a package that depends on the Session and Cookies. In 5.1, I used to push my middleware to the stack from my ServiceProvider.

But now, it is executed before the Route and Group middleware; so the Session has not been started yet.

I think the `pushMiddleware()` method in the Kernel should add the middleware in parameter as the last middleware to be executed; or am I doing something wrong?

**Comment by GrahamCampbell** [comment]
Please discuss on the forums since this is a not a bug.
