### ISSUE TITLE
Allow Gate to resolve interface?

### ISSUE THREAD

**Issue by hiendv** [laravel/framework#11965]
In my case, I'm trying to resolve objects by using interfaces. E.g.

```php
    protected $policies = [
        Acme\Contracts\ItemInterface::class => ItemPolicy::class,
    ];
```
I was expecting that Gate would resolve callbacks with something like `instanceof`, but it turns out to be `get_class`. So, my question is, should Gate implement a **type  checking** resolver besides names?

**Comment by GrahamCampbell** [comment]
Sorry, we don't process questions here. Please ask on the forums.

**Comment by hiendv** [comment]
It's not a question, it's more like a proposal @GrahamCampbell

**Comment by ronlinet** [comment]
@GrahamCampbell  as mentioned by @hiendv  this is not a question but a Legit  Design Improvement proposal
