### ISSUE TITLE
Blade comment issue

### ISSUE THREAD

**Issue by benjam-es** [laravel/framework#11961]
I updated an app I use from 5.0.* to 5.1.* earlier and found one of my routes was completely blank with no errors.

I found a block between 

    {{--
    
    --}}

The page showed content again when I removed the braces - but it wasn't the braces that were the issue because there were various other places I have them. I tried removing all and parts of the code within the braces.

The results seemed to be that once I got to X amount of blade braces within the comment braces it made the page blank again.. {{ url('/') }} for instance.. between 14-18 occurrences.

**Comment by GrahamCampbell** [comment]
You'll probably need to clear out your compiled views on upgrade. We probably need to mention this in the docs if we haven't already.
