### ISSUE TITLE
MethodNotAllowedHttpException in RouteCollection.php line 219:

### ISSUE THREAD

**Issue by roma1004** [laravel/framework#11973]
hi...!   I need your help, this error show me when I generate a pagination,
in my app I build a search-method, when I search a user in my app, and the result are more the 8 user, the app generate a pagination, but when I click en page 2, show me error "MethodNotAllowedHttpException in RouteCollection.php line 219:" .
my code route.php is -> Route::post('search',[ 'as'=>'search','uses'=>'mecontroller@search']);
my form is -> 
<--form action='{{ url("search")}}' method='post'-->
<--input type='hidden' value='{{ csrf_tonken()}}' -->
<--input type='submit' value='Search'-->
<--/form-->
please help.

**Comment by GrahamCampbell** [comment]
Please ask on the forums.
