### ISSUE TITLE
structure of validation exception

### ISSUE THREAD

**Issue by leemason** [laravel/framework#11981]
probably not going to get changed anytime soon but just wanted to see how people feel about the current validation exceptions behavoir under json conditions.

form requests and $this->validates are a great addition to laravel, but in a real world application the implementation seems very underwhelming.

currently if validation fails the user gets a 422 status with a keyed array as the json response.

this might get the job done in the most basic of cases, but could be improved upon dramatically with a few simple changes.

1. nest the returned errors within an "errors" global (i would argue its currently badly formatted): 

```json
{
    "errors":{
        "email": [
            ....
         ]
    }
}
```
2. allow additional data to be appended/returned: ->onError(function($response){$response->dothis();});
3. or instead of 2 allow additional data to be added to the returned json: ->onError([.....]);

to have the actual errors in the global namespace of the returned isnt very structured or well designed, and not being able to provide additional data, set status codes etc is/can be a real shame and at least in my experience tends to mean implementing your own validation is a more structured way.

i know this generally meant for forms and not for apis, etc. but even basic forms submitted over ajax should benefit from structured well implemented responses, just like everything else in the framework already is.

no pull request as im sure many agree (and disagree) so just wanted to see what people think?

**Comment by GrahamCampbell** [comment]
Thanks, but we don't process proposals on github.
