### ISSUE TITLE
Enable custom config options to filesystems

### ISSUE THREAD

**Issue by igorsantos07** [laravel/framework#11994]
I've noticed Flysystem enables us to add custom config items to our filesystem instances... However, when Laravel instanciates them from the `config/filesystem.php` it stripes down any unknown properties, as in [FilesystemManager:242](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Filesystem/FilesystemManager.php#L242).

I was wondering if there's any special reason for that?
I'm using local filesystem for development but S3 for production, and would like to set different base URLs for each driver inside their configuration properties, and I think it would be great if this was possible inside the disk configuration itself.

**Comment by igorsantos07** [comment]
Excerpts from initial discussion on https://github.com/GrahamCampbell/Laravel-Flysystem/issues/69:

> Suggestions:
>
> - simply remove the `only()` call. This would allow for credentials and whatnot be accessible easily, what could be a security breach?
> - use a blacklist approach instead of whitelist, cleaning up credentials and allowing other properties to pass through. This is similar to the current implementation, and would only change the `Arr` method used and properties verified.
> - pass as second argument to the Flysystem constructor a nested "config" array, if there's a "config" key inside the driver parameters. This would turn this ability to add custom config more explicit.
> 
> I'm happy to PR this if we agree with a solution :)

------

> My idea is as follows:
> In config/filesystem.php I have the default as (getenv('APP_ENV') == 'prod')? 's3' : 'local'. Given that, in my local machine I would need the file URLs relative to the server URL (path = '/'), and in production, relative to my bucket URL (path = 'https://aws.com/xyz/bucket/'). I would then, use something like Storage::drive()->getConfig()->get('path') + $user->avatar_path to spit out the user profile picture.
>
> I was able to test this idea by simply commenting out the said line 242 in FilesystemManager.php.

**Comment by laravel-internals** [comment]
Sorry, we don't process requests/proposals here. Please see https://github.com/laravel/internals/issues.
