### ISSUE TITLE
Laravel collection sort not properly sort if there is value

### ISSUE THREAD

**Issue by ssuhat** [laravel/framework#12005]
Hi,

I try to sort my collection using Laravel function.

here is my data for example: 
  
    $collection = 
     [
      {
        "total_earned": "31739",
        "total_spent": "0",
        "total_amount": "317390",
        "date": "2015-10-01"
      }, {
        "total_earned": "212622",
        "total_spent": "86943",
        "total_amount": "2213165",
        "date": "2015-12-01"
      }, {
        "total_earned": 0,
        "total_spent": 0,
        "total_amount": 0,
        "date": "2015-10-29"
      }, {
        "total_earned": 0,
        "total_spent": 0,
        "total_amount": 0,
        "date": "2015-10-30"
      }
    ];

When I try to sort using Laravel `sortBy` function and return it become like this:

    [{
    	"total_earned": 0,
    	"total_spent": 0,
    	"total_amount": 0,
    	"date": "2015-10-29"
    }, {
    	"total_earned": 0,
    	"total_spent": 0,
    	"total_amount": 0,
    	"date": "2015-10-30"
    }, {
    	"total_earned": "212622",
    	"total_spent": "86943",
    	"total_amount": "2213165",
    	"date": "2015-12-01"
    }, {
    	"total_earned": "31739",
    	"total_spent": "0",
    	"total_amount": "317390",
    	"date": "2015-10-01"
    }]

My code to sort:

     return $transaction->sortBy('date')->values()->all();

Is this a bug or the sort suppose to be like that?

**Comment by GrahamCampbell** [comment]
This doesn't look like a bug to me. Thanks though.

**Comment by GrahamCampbell** [comment]
The things you have there aren't really comparable so sortBy makes little sense.

**Comment by NassimRehali15** [comment]
i have the same problem :-1:  how to do ?

**Comment by huguesjoyal** [comment]
Hi,
You might try something like :

```php
$collection->sortBy(function ($transaction, $key) {
    return new Carbon($transaction['date'])->timestamp;
});
```
