### ISSUE TITLE
Add nullable modifier to Eloquent casts

### ISSUE THREAD

**Issue by kwoodfriend** [laravel/framework#12000]
I can do a PR for this. Wanted to get any thoughts before creating.

I came across a situation where I was using Eloquent's casting capabilities to cast an attribute to an integer. In this situation, if the column was null in the DB, I didn't actually want an integer to be returned, as it would result in 0. 0 happened to have a different meaning than null.

This is fixable with mutators, but I thought it might be a nice addition to add a modifier, which specifies null should be returned if the value is null, otherwise, cast as defined.

My initial thought was tacking "?" on to the end of the cast name. Some languages use "?" for features that surround null, e.g. C#.

Example:

```php
protected $casts = [
    'data' => 'array',
    'count' => 'int',
    'row' => 'int?' // will return null if the row is null, otherwise it will cast to an int
    'created_at' => 'date?' // null if null, otherwise, the date
];
```

Thoughts?

**Comment by deefour** [comment]
https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/Model.php#L2870-L2872

**Comment by kwoodfriend** [comment]
Thanks @deefour, must have missed that when reviewing.

**Comment by NicoHood** [comment]
Did the link change? I cannot see that this is implemented now?
