### ISSUE TITLE
v 5.2.10 will not persist sessions.

### ISSUE THREAD

**Issue by jontaylor1985** [laravel/framework#12003]
With a clean install of the latest Laravel 5.2.10 every page refresh results in a new session being created.  They do not seem to persist.

This doesn't seem to be down to the driver being used, both redis and file based suffer from the same issue.

Route::get('/set/{value}', function($value) {
    var_dump(Session::getId());
    Session::set('test', $value);
    return view('welcome');
});

Route::get('/get', function() {
    return 'Get ' . Session::get('test');
});

The code above sucessfully creates a session and I see them appear in redis (and file based depending on driver selected).  However on a page refresh a brand new session is created and a new entry in redis appears.  The /get url never returns anything.

The browser never seems to receive any session ids.

**Comment by fbidu** [comment]
+1

Using a clean install, `file` driver. 

`routes.php`:
``` 
Route::get('/set/{data}', function($data){
	Session::set('test', $data);
	Session::save();
	return Session::get('test');
});

Route::get('/get', function(){
	return Session::get('test');
});

Route::get('/all', function(){
	return Session::all();
});
```
When I `set`, the browser prints the value. When I access `all` or `get`, an empty array. I thought it could be an issue regarding file system permissions but it was not the case. The session files are created.

**Comment by brunogaspar** [comment]
Please [search](https://github.com/laravel/framework/search?q=session+persist&type=Issues&utf8=%E2%9C%93) before creating duplicated issues.

**Comment by jontaylor1985** [comment]
@brunogaspar I believe every one of those issues is different from the one stated.  I did take a look through some, I may have missed an issue which covered this.

From what I can see, the ones that cover `5.2.10` have used functions such as `dd` which kill the application before the session can be created.  This doesn't actually create the session on the back end.

My problem is fundamentally different in that the session itself is created but not passed to the browser, therefore subsequent requests create brand new sessions.

**Comment by brunogaspar** [comment]
@jontaylor1985 Then you probably didn't read them carefully :)

Your routes need to use the `web` middleware, otherwise your routes are stateless.

Check [here](https://github.com/laravel/laravel/blob/master/app/Http/routes.php#L29).

**Comment by jontaylor1985** [comment]
@brunogaspar You are an absolute life saver :), I will close this *non issue*

**Comment by brunogaspar** [comment]
Glad you managed to make it work :)
