### ISSUE TITLE
zh_TW Faker provider has ErrorException in PHP7

### ISSUE THREAD

**Issue by liaosankai** [laravel/framework#12011]
ErrorException: mb_substr() expects parameter 3 to be integer, string given in /home/vagrant/Code/emeibao/vendor/fzaninotto/faker/src/Faker/Provider/zh_TW/Text.php:112

    $last = mb_substr($text, mb_strlen($text)-1, 'UTF-8');

Homestead ENV:
+ Laravel Framework version 5.2.10
+ PHP 7.0.1-1+deb.sury.org~trusty+2 (cli) ( NTS )
+ Ubuntu 14.04.3 LTS (GNU/Linux 3.19.0-25-generic x86_64)

**Comment by GrahamCampbell** [comment]
This is not a bug in our code. Please report this to faker.
