### ISSUE TITLE
Auth::user() returns null on a RouteServiceProvider closure (L5.2)

### ISSUE THREAD

**Issue by zorx** [laravel/framework#12016]
I'm trying to filter user posts like this 

`routes.php`

```PHP
Route::group(['middleware' => 'auth', 'prefix' => 'user'], function () {
  Route::get('preview/{postUser}', ['as' => 'user.post.preview', 'uses' => 'PostController@preview']);
});
```

`RouteServiceProvider.php`

```PHP
public function boot(Router $router) {
  $router->bind('postUser', function($id) {
    Auth::user() //<-- always null
    Auth::check() //<-- always false
  });
}
```

it works on L5.1, any idea how to fix this on 5.2 ?

**Comment by GrahamCampbell** [comment]
This is because the auth middleware is now run AFTER routes are matched.

**Comment by GrahamCampbell** [comment]
To change this, just move the auth middleware and related stuffs back to the global middleware instead of putting it in the web group.
