### ISSUE TITLE
[homestead] php5-fpm: unrecognized service - The SSH command responded with a non-zero exit status

### ISSUE THREAD

**Issue by envision** [laravel/framework#12010]
Box version 0.4.0 and repo 2.1.7. I totally removed and reinstalled Homestead and am still getting this after 'homestead up':

	==> default: Running provisioner: shell...
	    default: Running: inline script
	==> default: Running provisioner: shell...
	    default: Running: /var/folders/hl/bmp2l3z96gj36xc0352m9jv00000gn/T/vagrant-shell20160124-11925-1oyu83w.sh
	==> default: Running provisioner: shell...
	    default: Running: /var/folders/hl/bmp2l3z96gj36xc0352m9jv00000gn/T/vagrant-shell20160124-11925-y0v8ao.sh
	==> default: nginx stop/waiting
	==> default: nginx start/running, process 1861
	==> default: php5-fpm: unrecognized service
	The SSH command responded with a non-zero exit status. Vagrant
	assumes that this means the command failed. The output for this command
	should be in the log above. Please read the output to determine what
	went wrong.

Here someone found a fix by adding an additional escaping in /scripts/homestead.rb on line 107 to read like this:

    s.inline = "echo \"$1\" > /home/vagrant/.ssh/\"$2\" && chmod 600 /home/vagrant/.ssh/\"$2\""

http://stackoverflow.com/questions/25953499/laravel-homestead-provisioning-failing-on-windows-8/25980085?iemail=1&noredirect=1#25980085

However I'm still getting this error?

**Comment by envision** [comment]
Weird, I'm getting the error only when upping the vm with 'homestead up', and not with 'vagrant up'?

**Comment by crynobone** [comment]
You should use repo `v3.0.0` for homestead 0.4.0

**Comment by envision** [comment]
Ah sorry actually I had the newest 6.1.2016 50ced7f ... though I need to revert using old box version 0.3.3 for this project. @crynobone how can I find out which repo version is for which box version, or do I need to manually go thru both's commit logs and get corresponding dates?

**Comment by crynobone** [comment]
If you need to use PHP5.6, lock your composer.json to `"laravel/homestead": "~2.2.0"`

**Comment by envision** [comment]
Thanks @crynobone ! Is there a list where to see which homestead vagrantbox version corresponds to which repo version?

**Comment by envision** [comment]
And how do I vagrant up with specific box version? As I have added two boxes:
laravel/homestead (virtualbox, 0.3.3)
laravel/homestead (virtualbox, 0.4.0)
