### ISSUE TITLE
Not updating view, when AppServiceProvider changes.

### ISSUE THREAD

**Issue by CzajekDC** [laravel/framework#12018]
## Issue

When making changes in `boot()` inside AppService provider as follows:
```php
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Blade::directive('datetime', function($expression) {
            return "<?php echo with{$expression}->format('m/d/Y H:i'); ?>";
        });
    }
```

Changes are not applied to cashed views. For them to apply you need to go to the view itself and re-save  it.

## Solution
Update all views (or at least ones containing the function specified in Blade::directive()) when saving AppServiceProvider (or any ServiceProvider containing Blade::directive()).

**Comment by GrahamCampbell** [comment]
This is NOT a big. You MUST manually clear the cached views after making such changes.

**Comment by GrahamCampbell** [comment]
Your work around is incorrect btw. You should just clear the cached views out. We have an artisan command for that, or you can just delete the files in the view cache folder by hand if you wish.

**Comment by CzajekDC** [comment]
Yes, I know you need to delete cached views. But it's not that intuitive and may cause a big headache for starting developers...

**Comment by CzajekDC** [comment]
At least documentation should at least mention that.

**Comment by veddishant** [comment]
Try to run `php artisan view:cache` to manually clear the view cache after that it will works. In my case i have changed on boot() method.  after view not getting new changes. so i clear the view cache manually and its works

**Comment by linh294** [comment]
"php artisan view:cache" works! Thank you!
