### ISSUE TITLE
New tag on lumen-installer

### ISSUE THREAD

**Issue by iWader** [laravel/framework#12020]
Current tag is 1.0.1 from April 2015, which is incompatible with the latest tag of `laravel/installer` because of the mismatching Symfony components. It appears its been fixed but not tagged since.

Installing `dev-master` solves the conflict, but that might not be obvious to most users considering the docs just say `composer require laravel/lumen-installer`

**Comment by GrahamCampbell** [comment]
Closing since this isn't an issue with the framework. Feel free to request this on slack though.
