### ISSUE TITLE
[L5.1 -> L5.2] Problem with request replace method

### ISSUE THREAD

**Issue by f0und3r** [laravel/framework#12024]
Hello

I use dependency injection in my controllers and i have problem.
If i use method(CustomRequest $req) instead method(Request $req) request lost replaced data.
Data has been replaced in middleware for every request. Data come in JSON format, if i write in my parent request, all works:
```
public function isJson() { return false }
```

Example, what doesn't work:

```
class middleware {
public function handle($request) {
$request->replace(['my data']);
}
}

class controller {
public function index(Request $req) {
echo $req[0]; // 'my data'
}

public function another(MyRequest $req) {
echo $req[0]; // no 'my data' here
}
}
```

**Comment by GrahamCampbell** [comment]
Please ask questions on the forums and I'm sure someone can help you there. ;)
