### ISSUE TITLE
Distorted Basic authorization token in request header

### ISSUE THREAD

**Issue by AlexandreApitic** [laravel/framework#12023]
Hello,

I am having some troubles with basic authorization token which seem to be distorted sometimes when getting it from header with 
$request->header('Authorization');

What I see when I inspect the header of the request with firebug :
Authorization:  Basic h58XCpbP2HL2fF0ZopX7Onvk609oA2

What I can see when I dump the token with dd();
Basic h58XCpbP2HL2fF0ZopX7Onvk609oAw==

**Comment by billmn** [comment]
___"... seem to be distorted sometimes when getting it from header ..."___

Mmmmm, it seems very strange ... can you show us an example of your code?

**Comment by AlexandreApitic** [comment]
Of course ! That's the middleware I use to check session : 

<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Support\Facades\Auth;

class Authenticate
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @param  string|null  $guard
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        $session_token = $request->session()->get('token');

        $basic_access_token = $request->header('Authorization');
        $access_tokenAr     = explode(' ', $basic_access_token); // "Basic token_string"
        $access_token       = $access_tokenAr[1]; // "token_string"

        if ($session_token != $access_token)
        {
            return response('Unauthorized: '.$session_token.' //// '.$access_token.' //// '.$basic_access_token, 401);
        }

        return $next($request);
    }
}

**Comment by billmn** [comment]
Which version of Laravel are you using?

**Comment by AlexandreApitic** [comment]
Laravel Framework version 5.2.7

**Comment by billmn** [comment]
Laravel provide Basic Authentication out of the box ... why you have overwritten the Authenticate Middleware?

However I don't think it can be a problem of Laravel.

You can execute the request using [Postman](https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop) and you can see that the Token is correct (I suppose this is the right one: h58XCpbP2HL2fF0ZopX7Onvk609oAw==)
