### ISSUE TITLE
SQS Class 'Aws\Sqs\SqsClient' not found When trying to use Redis queue, despite SQS not referenced anywhere

### ISSUE THREAD

**Issue by andy1547** [laravel/framework#12029]
When I try to switch my queue driver from Sync to Redis I get this error.

I've tried including the SQS API with composer to get the error "Check your AWS Secret Access Key and signing method.

I've also tried commenting out the SQS array config in config/queue.php for Laravel to complain their is no config for the SQS driver.

This happens on my Centos 7 server, it does not affect Ubuntu 15.10 or Centos 5 (The .env and config/* files are exactly the same on all servers).

I'm using Laravel 5.1

**Comment by andy1547** [comment]
Turns out it's the the documentation being bad.
When you set-up supervisor for queue monitoring it gives the example:

php /home/forge/app.com/artisan queue:work sqs --sleep=3 --tries=3 --daemon

This was causing Laravel to use sqs, I would of thought this option would of and could only be configured in the environment my bad.

**Comment by Dylan-DutchAndBold** [comment]
Just ran into the exact same issue, thanks for answering yourself!

**Comment by Jonathan0wh** [comment]
Still encountered this after 3 years by following Laravel 5.7 documentation... Could it be specified that the sqs option is for Amazon SQS, and if one wants to run the worker locally, he does not need the sqs option?

**Comment by driesvints** [comment]
From the docs:

> You should change the queue:work sqs portion of the command directive to reflect your desired queue connection.

**Comment by Pushkraj19** [comment]
> Turns out it's the the documentation being bad.
> When you set-up supervisor for queue monitoring it gives the example:
> 
> php /home/forge/app.com/artisan queue:work sqs --sleep=3 --tries=3 --daemon
> 
> This was causing Laravel to use sqs, I would of thought this option would of and could only be configured in the environment my bad.

Same situation with me.
Thanks for pointing this out !

**Comment by DockerComposeFiles** [comment]
supervisor settings overwrite conf/queue setting
Thanks for answering yourself!
