### ISSUE TITLE
input('this', 'default'): Check if keyed value is not empty for better default value use?

### ISSUE THREAD

**Issue by rodrigonsh** [laravel/framework#12021]
https://github.com/laravel/framework/blob/5.2/src/Illuminate/Support/Arr.php#L232

public static function get($array, $key, $default = null)
    {
        if (is_null($key)) {
            return $array;
        }
        if (isset($array[$key]) && !empty($array[$key])) {  
            return $array[$key];
        }

**Comment by GrahamCampbell** [comment]
Not sure what you are asking?

**Comment by alexwhitman** [comment]
As a guess, the default value only applies when the input value isn't set.  If it is set but empty then the default value isn't used. @rodrigonsh is suggesting that the default value should be used if the input value is set but empty.

**Comment by GrahamCampbell** [comment]
Just use a ternary statement to get that behaviour.
