### ISSUE TITLE
[4.2.18] Problem with MySqlConnector

### ISSUE THREAD

**Issue by Dimma** [laravel/framework#12039]
I have problem, when updating project from 4.2.17 to 4.2.18. 
We are using Sphinx search engine, and in our database.php config we're connecting to MySQL.
But after updating to new version we have error in this code above:

```
exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 sphinxql: syntax error, unexpected IDENT, expecting '=' near 'sql_mode='''' in /vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php:52
```

It's in MySqlConnector.php in this row: 

```php
$connection->prepare("set session sql_mode=''")->execute();
```

For just a 'hotfix' solution I think you can make like these:

https://github.com/laravel/framework/commit/aa99a37f6ff061328745930cd9275969faeabebd

wrap all block in 

```php
if (isset($config['strict'])) {
```

After commenting these block - all is working. But maybe need some another solution.

Please, can you fix this?

Thank you.

**Comment by GrahamCampbell** [comment]
Stay on 4.2.17 then.

**Comment by GrahamCampbell** [comment]
4.2.x isn't supported anyway.
