### ISSUE TITLE
Different messages type on redirect

### ISSUE THREAD

**Issue by Alexandreh** [laravel/framework#12034]
Hello guys,

I was thinking about having a method for custom messages provider 
on responses and/or if it's possible to do in last stable version.
Having it would be helpful on view messages implementation, which'd require just 
a `MessageProvider` object or a simple array or string (as it is with errors nowadays).
however it seems to be possible only for error messages (correct me if I'm wrong). 
Other message types are a bit harder and out of pattern.

exemplifying:
```php
// setting success and error message nowadays
return redirect()->with(['messages' => ['success' => ['message one', 'message two']]]);
return redirect()->withError('message three');
// getting these messages (out of pattern)
dd($errors->all());
dd(session('messages')['success']);

// what'd be nicer
return redirect()->withSuccess(['message one', 'message two']);
return redirect()->withWarning('message three');

dd($warnings->all());
dd($success->all());
```

So, what do you think?

**Comment by GrahamCampbell** [comment]
Please ask questions on the forums, and discuss proposals on slack.
