### ISSUE TITLE
[5.2] Cookies sent in test are not present in request.

### ISSUE THREAD

**Issue by Asvae** [laravel/framework#12032]
Basically, I'm unable to test if controller accepts cookie no matter what i try. 

Here's my test:
```
public function test_cookie_passed_to_request(){
    $cookie = cookie('name', 'value');
    $this->call('get', 'test', [], [$cookie]);
    $this->assertEquals('value', $this->response->content());
}
```
And here is the route:
```
Route::get('test', [
    'middleware' => 'web',
    function (\Illuminate\Http\Request $request) {
        return $request->cookie('name');
    }
]);
``` 
Test fails: expected `"value"`, got `""`.

[Discussion on laracasts](https://laracasts.com/discuss/channels/testing/phpunit-test-setting-cookies) for reference.

**Comment by vinicius73** [comment]
The route has the `web` middleware?

**Comment by ifpingram** [comment]
This is not a bug, but instead the cookie should be passed as an array of values, not as a Symfony\Component\HttpFoundation\Cookie instance. Test should be changed to read:

```
    public function test_cookie_passed_to_request(){
        $cookie = ['name' => Crypt::encrypt('value')];

        $this->call('GET', 'test', [], $cookie);

        $this->assertEquals('value', $this->response->content());
    }
```

**Comment by GrahamCampbell** [comment]
Top tip. Avoid calling global functions inside tests. ;)

**Comment by Asvae** [comment]
And I did some more digging:
```
$cookie1 = ['name1' => Crypt::encrypt('value1')];
$cookie2 = ['name2' => Crypt::encrypt('value2')];
$this->call('get', 'test', [], [$cookie1, $cookie2]);
$this->assertEquals('value1', $this->response->content());
```
That test fails.
And here is method definition from src:
```
public function call($method, $uri, $parameters = [], $cookies = [], $files = [], $server = [], $content = null)
```
It says `$cookies` and not cookie. Yet it accepts only one cookie and that one should be weirdly parsed.

**Comment by ifpingram** [comment]
as per my answer on the Laracasts thread, the cookies need to be set like:

```
    public function test_cookies_passed_to_request()
    {
        $cookies = [
            'name1' => Crypt::encrypt('value1'),
            'name2' => Crypt::encrypt('value2')
        ];
        $this->call('get', 'test', [], $cookies);
        $this->assertEquals('value1', $this->response->content());
    }
```

**Comment by Asvae** [comment]
Here's the final solution.
The test:
```
public function test_cookie_passed_to_request()
{
    $this->disableCookiesEncryption('name');
    $cookie = [ 'name' => 'value' ];
    $this->call('get', 'test', [ ], $cookie);
    $this->assertEquals('value', $this->response->content());
}
```
The route:
```
Route::get('test', [
    'middleware' => 'web',
    function (\Illuminate\Http\Request $request) {
        return $request->cookie('name');
    }
]);
```
TestCase function to disable cookie encryption:
```
    /**
     * @param array|string $cookies
     * @return $this
     */
protected function disableCookiesEncryption($cookies)
{
    $this->app->resolving(EncryptCookies::class,
        function ($object) use ($cookies) {
            $object->disableFor($cookies);
        });

    return $this;
}
```

**Comment by driade** [comment]
Working in 5.4

**Comment by fgilio** [comment]
Thanks @asvae! Works perfectly in 5.6

**Comment by hemantachhami19** [comment]
Can we do it without creating routes?

**Comment by hivokas** [comment]
This works for me in Laravel 8:

```
$this
    ->withCredentials() // turns out ->withCookies() doesn't work without this call 
    ->withCookies([
        'hello' => 'world',
    ])
    ->postJson('/check')
```

**Comment by Stevemoretz** [comment]
Thank you.

> ->withCredentials(

That's what I needed, how did you figure that out, though?

**Comment by Stevemoretz** [comment]
> Can we do it without creating routes?

Go ahead and use :

```
$_COOKIE["whatever_key"] = "whatever_value"
```

You can use that in your `setup` function and in `teardown` be sure to unset that, some stuff don't have nothing to do with Laravel 👍

**Comment by hengki01** [comment]
> This works for me in Laravel 8:
> 
> ```
> $this
>     ->withCredentials() // turns out ->withCookies() doesn't work without this call 
>     ->withCookies([
>         'hello' => 'world',
>     ])
>     ->postJson('/check')
> ```

thank you, still works in 2024

**Comment by mzarhou** [comment]
> This works for me in Laravel 8:
> 
> ```
> $this
>     ->withCredentials() // turns out ->withCookies() doesn't work without this call 
>     ->withCookies([
>         'hello' => 'world',
>     ])
>     ->postJson('/check')
> ```

Thank you
