### ISSUE TITLE
[5.1] Is Auth::logout() working as intended?

### ISSUE THREAD

**Issue by zprisk** [laravel/framework#12054]
Hello,
I am using Laravel 5.1. I recently started to extend the Auth Guard. I am wondering if the logout functionality is as intended in regards to "remember_token".

Here is current code:
```
        $user = $this->user();

        $this->clearUserDataFromStorage();

        if (! is_null($this->user)) {
            $this->refreshRememberToken($user);
        }

        if (isset($this->events)) {
            $this->events->fire('auth.logout', [$user]);
        }

        $this->user = null;

        $this->loggedOut = true;
```

The part I am curious on is the first check if (! is_null($this->user). Unless I am missing something this will always attempt to refresh the RememberToken even if the model does not have remember me capability.

Here is the slight adjustment I made to make that check
```
        if (! is_null($this->user) && array_key_exists('remember_token', $this->user->getAttributes()))
        {
        	$this->refreshRememberToken($user);
        }
```
I could just be missing something.

**Comment by progmars** [comment]
I too stumbled upon unexpected SQL errors for remember token column in my application which is not using Remember me functionality.

While there is a hacky workaround to disable it using setters for login model (see http://laravel.io/forum/05-21-2014-how-to-disable-remember-token ), I agree with @zprisk - there should be nicer "official" way to disable it.

**Comment by rap2hpoutre** [comment]
@zprisk I tried to implement your solution but unit tests failed :/

**Comment by rap2hpoutre** [comment]
Same problem with Laravel 5.2
