### ISSUE TITLE
Unicode support for Str::slug function

### ISSUE THREAD

**Issue by sajjad-ser** [laravel/framework#12053]
[`slug`](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Support/Str.php#L341:L357) can you add Unicode support for this function?
for example instead of [this](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Support/Str.php#L350:L351):
```php
        // Remove all characters that are not the separator, letters, numbers, or whitespace.
        $title = preg_replace('![^'.preg_quote($separator).'\pL\pN\s]+!u', '', mb_strtolower($title));
```
use this:
```php
        // Encode to Url
        $title = urlencode($title);
```

**Comment by GrahamCampbell** [comment]
We already support unicode in the form of converting to ascii first?

**Comment by sajjad-ser** [comment]
> We already support unicode in the form of converting to ascii first?
the result of `\Str::ascii('تست')` is `"tst"` but it must be `"%D8%AA%D8%B3%D8%AA"` in the url

**Comment by GrahamCampbell** [comment]
> the result of \Str::ascii('تست') is "tst" but it must be "%D8%AA%D8%B3%D8%AA" in the url

No, `"tst"` is the correct output.

**Comment by GrahamCampbell** [comment]
If you don't like our slug function that's fine. Just define your own.
