### ISSUE TITLE
[5.2] Need an option on `Route::resource()` to allow plural resource URLs without breaking implicit route model binding

### ISSUE THREAD

**Issue by ryanmortier** [laravel/framework#12056]
Currently when writing a route like:

    Route::resource('accounts', 'AccountController');

It will generate routes to `accounts/{accounts}` like:
```php
Route::post('accounts', ['as' => 'accounts.store', 'uses' => 'AccountController@store']);
Route::get('accounts', ['as' => 'accounts.index', 'uses' => 'AccountController@index']);
Route::get('accounts/create', ['as' => 'accounts.create', 'uses' => 'AccountController@create']);
Route::get('accounts/{accounts}', ['as' => 'accounts.show', 'uses' => 'AccountController@show']);
Route::match(['put', 'patch'], 'accounts/{accounts}', ['as' => 'accounts.update', 'uses' => 'AccountController@update']);
Route::delete('accounts/{accounts}', ['as' => 'accounts.destroy', 'uses' => 'AccountController@destroy']);
Route::get('accounts/{accounts}/edit', ['as' => 'accounts.edit', 'uses' => 'AccountController@edit']);
```

Which means in the `AccountController`, normally you'd write your method like:
```php
public function show(Account $account)
{
    //
}
```

But to allow implicit route model binding to work, you have to write it like:
```php
public function show(Account $accounts)
{
    //
}
```

Therefore, `Route::resource('accounts', 'AccountController');` should generate routes like `accounts/{account}`:
```php
Route::post('accounts', ['as' => 'accounts.store', 'uses' => 'AccountController@store']);
Route::get('accounts', ['as' => 'accounts.index', 'uses' => 'AccountController@index']);
Route::get('accounts/create', ['as' => 'accounts.create', 'uses' => 'AccountController@create']);
Route::get('accounts/{account}', ['as' => 'accounts.show', 'uses' => 'AccountController@show']);
Route::match(['put', 'patch'], 'accounts/{account}', ['as' => 'accounts.update', 'uses' => 'AccountController@update']);
Route::delete('accounts/{account}', ['as' => 'accounts.destroy', 'uses' => 'AccountController@destroy']);
Route::get('accounts/{account}/edit', ['as' => 'accounts.edit', 'uses' => 'AccountController@edit']);
```

**Question**: Why not use singular URLs?
**Answer**: It's widely accepted that RESTful APIs have plural URLs for resources.

**Question**: Why not use explicit route model binding?
**Answer**: If I have two resources `accounts`, and `contacts`, and I have a third resource `notes` that is a nested resource for both `accounts` and `contacts` , I can only bind `{note}` to one class (assume I'm not using polymorphic relationships)? I.E.:
```php
$router->model('note', 'App\AccountNote');
$router->model('note', 'App\ContactNote');
```

Currently I'm working around this issue by not using `Route::resource()` and instead just explicitly writing out my routes with the pattern I need.

**Comment by lucasmichot** [comment]
Old but related : #5877 & #5556

**Comment by lagbox** [comment]
You can make them singular if you want easily.
#11644

**Comment by ryanmortier** [comment]
Closing this issue because there is a PR #12137.

**Comment by ryanmortier** [comment]
Related: #12061

**Comment by PlushyObject** [comment]
Ermagherd thanks guys.

**Comment by PlushyObject** [comment]
Just in case you find this thread, this has been added:

`Route::singularResourceParameters();`

So keep it plural like this and it will give you singular wildcard:

`Route::resource('projects','ProjectController');`
