### ISSUE TITLE
[Proposal] Migration simulator

### ISSUE THREAD

**Issue by shincoder** [laravel/framework#12050]
As you know, wrapping database migrations in a transaction has no effect in Mysql for table operations.
Which means that if migration fails, you most likely end up with a broken database state which stinks!!!

I made a package that simulates the migrations in a testing database and report back success or failure to the user, leaving the real production database intact.

#### So the main idea behind this is the following:

* We create a testing database for every connection specified by the user (or use the default one).
* We switch the configuration to the new database at runtime, replacing the real database.
* We refresh the connection so that Laravel can use the new configuration.
* We run ```php artisan migrate``` against the testing database.
* When done, we drop the testing database.
* Any eventual errors are displayed to the user.
* The real database stays intact.

This could be a great addition to the framework. I'm sure you can come up with a better implementation.

Working code https://github.com/shincoder/harmless-migration

**Comment by GrahamCampbell** [comment]
Please discuss proposals on slack. We don't process these on github since are issues are here for the community to fix bugs in the framework, and are not a way to communicate with Taylor really.

**Comment by GrahamCampbell** [comment]
Thanks though. :)
