### ISSUE TITLE
Eloquent soft delete inconsistent behaviour

### ISSUE THREAD

**Issue by EvgeniyN** [laravel/framework#12066]
I spent a hour while catch my issue.
There are no notices in docs about this.

Short example:
`class SomeModel extends \Eloquent{`
`use SoftDeletes;`
`public $table = 'some_table_withDeleted_at_column';`
`}`
`SomeModel::find($id)->delete(); // Perform soft delete`
`SomeModel::whereId($id)->delete(); // Actually remove row from database`
`SomeModel::destroy($id); // Perform soft delete`

So why EloquentQueryBuilder don't care about soft delete trait in model?
Maybe we need to change EloquentQueryBuilder::delete() behaviour or at least notice about it in dosc?
Sry for my eng.

**Comment by acasar** [comment]
@EvgeniyN Which Laravel version? As far as I know, all 3 methods should work.

**Comment by EvgeniyN** [comment]
@acasar Composer's installed.json file say
"name": "laravel/framework",
"version": "v5.2.0",
"version_normalized": "5.2.0.0",

**Comment by GrahamCampbell** [comment]
> "version": "v5.2.0",

You need to use `5.2.*`.

**Comment by acasar** [comment]
Yeah that was fixed after 5.2.0. so you should be good after you upgrade.

**Comment by EvgeniyN** [comment]
Yep, it helps, but now I have other issue with the latest update.
guest middleware applied in controller constructor to POST action with custom FormRequest doesn't work and trigger uncought HttpResponseException.
This issue cause only on production machine not on my local env - so I'm frustrated.
When middleware is applied in routes.php all works as expected,
when it applied in controller constructor - not.
It's look like issue.

PHP -v 
PHP 5.6.17-0+deb8u1 (fpm-fcgi)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies

**Comment by acasar** [comment]
I suggest that you open a seperate ticket for that and provide a full exception and a snippet of relevant code, otherwise we can't help.
