### ISSUE TITLE
[5.2] Session not persisting (using web middleware)

### ISSUE THREAD

**Issue by nicgutierrez** [laravel/framework#12063]
I'm manually logging in a user in my controller using `Auth::login($user);` but the session is not persisting and after a new refresh `Auth::check()` always returns false.

My routes are registered within `Route::group( [ 'middleware' => [ 'web' ] ], function (){} );`.

`Laravel Framework version 5.2.12`

Many thanks

**Comment by GrahamCampbell** [comment]
I can't replicate. Please post a new issue if you're able to provide the smallest possible case to replicate this. Otherwise, please seek help on the forums.
