### ISSUE TITLE
Blueprint::timestamps not setup correctly. Update_at doing nothing and created_at doing updated_at

### ISSUE THREAD

**Issue by lukewatts** [laravel/framework#12060]
So basically after you run a migration to create a table with Blueprint::timestamps() method, such as the create_users migration that comes with Laravel, the columns are setup incorrectly. Almost backwards.

### Problem
1. So upon table creation both columns are set to `0000-00.00 00:00:00` 
2. Then, upon an insert the `created_at` column sets the current time. Everything is fine so far...
3. Upon update of the same row however, the `created_at` column updates again to the current time and the `updated_at` column never changes from `0000-00-00 00:00:00`.

### Possible Solution
The correct column attributes for those columns to achieve the desired behavior is:
```sql
created_at TIMESTAMP DEFAULT 0
updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
```

Essentially, `DEFAULT 0` is telling `created_at` to be `NOT NULL`. Therefore, when an `INSERT INTO` query passes `NULL` to it, it gets the current time and won't update again. However, it looks like you have to pass `NULL` to the `created_at` column upon the initial `INSERT INTO` or it will remain `0000-00-00 00:00:00`.

Unfortunatety you can't have `CURRENT_TIMESTAMP` or `NOW()` or any combination of those on two `TIMESTAMP` columns so this is the common work around.

Hope that helps.

**Comment by anishdcruz** [comment]
@GrahamCampbell Is this a bug?

<img width="440" alt="screen shot 2016-02-02 at 8 54 14 am" src="https://cloud.githubusercontent.com/assets/2182620/12741106/9fcbab02-c99f-11e5-86de-59f945736f31.png">

This laravel migration produces the following schema.

<img width="531" alt="screen shot 2016-02-02 at 8 48 12 am" src="https://cloud.githubusercontent.com/assets/2182620/12741105/9f95472e-c99f-11e5-9f28-ca0b7d41fafd.png">

`TIMESTAMP ON UPDATE CURRENT_TIMESTAMP` is currently being added to the first occurrence of the timestamp field i.e the `expired_at` field.

**Comment by devinfd** [comment]
This issue keeps coming up here, on the forums and SO. We need to get a resolution to it or at least better PR to tell people about the risks of using `$table->timestamps();` and `$table->timestamp('fooed_at');`

**Comment by lukewatts** [comment]
My original problem/case had nothing to do with using $table->timestamps() with an additional $table->timestamp() in the same table. The problem might also crop up in that scenario, however the problem is that you can't call CURRENT_TIMESTAMP twice in a table. So it could be the PHP is trying to do that and MySQL will simply refuse to do it and do the next best thing.

From the MySQL5.5 Manual:
>  One TIMESTAMP column in a table can have the current timestamp as the default value for initializing the column, as the auto-update value, or both. It is not possible to have the current timestamp be the default value for one column and the auto-update value for another column.

Also, this excerpt seems to reference the problem mentioned by @anishdcruz:
> It need not be the first TIMESTAMP column in a table that is automatically initialized or updated to the current timestamp. However, to specify automatic initialization or updating for a different TIMESTAMP column, you must suppress the automatic properties for the first one. Then, for the other TIMESTAMP column, the rules for the DEFAULT and ON UPDATE clauses are the same as for the first TIMESTAMP column, except that if you omit both clauses, no automatic initialization or updating occurs.

It also gives possible solutions here: http://dev.mysql.com/doc/refman/5.5/en/timestamp-initialization.html

**Comment by terdelyi** [comment]
I've got the same problem here with using timestamps() in a migration and it was very frustrating when I found out after my application lost (overwrite) some sensitive data in production.

I don't have another TIMESTAMP column in the table. When I update something in the row MySQL always updates to the current time, but doesn't modify the update_at column. This setup just makes no sense on a created_at column, it should be used on updated_at. Please fix the timestamps() method.

**Comment by lukewatts** [comment]
**This is a serious issue**.

I would even go as far as to say the `timestamps` method should be removed completely for now and the documentation be updated to warn people of the current issue. 

As @terdelyi mentioned, if this problem goes unnoticed for a period of time on a production site that may depend on this information bein accurate, it could be very costly to a company or web app.

**Comment by taylorotwell** [comment]
What version of MySQL?

**Comment by taylorotwell** [comment]
Personally I think ->timestamps() should just default to ->nullableTimestamps() to solve this issue.

**Comment by taylorotwell** [comment]
I can tell you 100% for sure we are not **removing** the method.

**Comment by taylorotwell** [comment]
Is anyone else in agreement that `->timestamps()` should just call `->nullableTimestamps()` so that we have a valid default to give to those columns across all versions of MySQL?

**Comment by anishdcruz** [comment]
mysql  Ver 14.14 Distrib 5.6.28, for debian-linux-gnu (x86_64) using  EditLine wrapper

**Comment by taylorotwell** [comment]
On the next 5.2 release `->timestamps()` will just call `->nullableTimetamps()`.

**Comment by terdelyi** [comment]
We have MySQL 5.6.22 (local), MySQL 5.6.27 (production). I didn't ask to remove this method, just check that does created_at column really need a default "on update CURRENT_TIMESTAMP" instead of update_at. Normally you never refresh created_at data, especially when you update the row.

**Comment by taylorotwell** [comment]
That is being added by a MySQL configuration option, not Laravel. Anyways, 5.2.14 will now just make ->timestamps() nullable by default.

**Comment by lukewatts** [comment]
It was on MySQL 5.6 and MariaDB (5.6) and PHP7 I first noticed the issue.

No I asked to remove it seeing as I personally think this behavior is something that can only properly be implemented in MySQL, with Triggers and such.

**Comment by lukewatts** [comment]
Setting the timestamp table to nullable will remove the auto-instantiation of the created_at table, won't it?

**Comment by lukewatts** [comment]
> If the TIMESTAMP column permits NULL values but its definition does not include DEFAULT CURRENT_TIMESTAMP, you must explicitly insert a value corresponding to the current date and time.

**Comment by taylorotwell** [comment]
I don't understand your question. The columns *shouldn't* auto-initialize at the database level. That is handled by Eloquent.

**Comment by lukewatts** [comment]
Ok. I wasn't aware Eloquent inserted values into the timestamps. I figured it was trying to use multiple CURRENT_TIMESTAMP attributes to handle it.

Thanks Taylor!

**Comment by terdelyi** [comment]
@taylorotwell You're right, that makes sense: _"If the first TIMESTAMP column in a table is not specified as NULLable and doesn't have explicit DEFAULT or ON UPDATE value specified, it automatically gets DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP as attributes"_

Sorry for the misunderstanding, I've never heard of that before. I also think `->nullableTimetamps()`put things right, thanks for the quick fix.

**Comment by MartinGacheru** [comment]
my timestamps gives wrong time what should i do?
