### ISSUE TITLE
Uncaught exception 'ReflectionException' with message 'Class log does not exist'

### ISSUE THREAD

**Issue by m-gamal** [laravel/framework#12071]
I got this error when I install an app , so I don't have any idea to solve this error.
This is the detailed error :

> PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class log does not exist' in /var/www/timegrid/bootstrap/cache/compiled.php:1320

**Comment by ddimaria** [comment]
I had this issue as well, and it was related to values with spaces in the .env file (latest phpdotenv enforces this).  If you have spaces, just enclose with quotes.

**Comment by GrahamCampbell** [comment]
This issue happens whenever an exception is thrown before our logger is bound, thus hiding the actual error, which may or may not be phpdotenv related.

**Comment by GrahamCampbell** [comment]
@ddimaria Also, you are technically wrong here. It has always been enforced, but we were just silently failing and discarding the rest of the .env file before. Now we throw an exception.

**Comment by m-gamal** [comment]
Yes , I solved it by commented all unused vars in .env file , thanks to all :)

**Comment by ddimaria** [comment]
Glad it worked out @m-gamal!  Thanks for the correction @GrahamCampbell ...it appears it's been this way since v2 in May 2015, so it's been around for a while.  Happy that Laravel now throws an error on this.

**Comment by GrahamCampbell** [comment]
This was the related fix btw: https://github.com/laravel/framework/pull/11602.

**Comment by msdavid1296** [comment]
You'll probably have a file now generated in bootstrap/cache/config.php which is being referenced for your settings. But this will be broken as you're likely referencing environment variables directly from your app. I'm not sure how the cache works but it seems as if unless you've declared the variables you need in the Laravel PHP config files (which themselves can happily load directly from the .env file) you will run into this problem. So the quick fix would be to remove the config.php (or rename to .backup.php temporarily to test) and see if this fixes things. Then rework the way you are referencing settings in the app, and try caching it again afterwards - you most certainly don't want to encounter this problem on a production environment! Especially when doing this seems to knock out the use of artisan.

**Comment by jeremyquinton** [comment]
I had the same issue with a Laravel 5.2 app. Removing bootstrap/cache/compiled.php and trying again worked for me.
