### ISSUE TITLE
Login username not derived from Authenticatable model

### ISSUE THREAD

**Issue by deframe** [laravel/framework#12074]
While working with the Illuminate\Foundation\Auth\AuthenticatesUsers trait I noticed that a custom login username field must be set as a property of the inheriting class:

    public function loginUsername()
    {
        return property_exists($this, 'username') ? $this->username : 'email';
    }

Is there any reason why this can't use the Guard instance to get the field name from the Authenticatable model? Something like:

    public function loginUsername()
    {
        if (property_exists($this, 'username'))
        {
            return $this->username;
        }

        return Auth::guard($this->getGuard())->getProvider()
            ->createModel()->getAuthIdentifierName();
    }

Instantiating a model to do this may not be ideal but it removes the need to duplicate the auth identifier field name on both the model and the controller.

Another concern is that changing this behavior may result in a BC break if it's not handled correctly.

**Comment by srmklive** [comment]
Its better how it is implemented right now. No real need to change its current behavior.
