### ISSUE TITLE
Behavior change noticed in InteractsWithPages seeInElement

### ISSUE THREAD

**Issue by cat5inthecradle** [laravel/framework#12075]
seeInElement is no longer able to match on html tag attributes. It was able to do this prior to the recent commit: https://github.com/laravel/framework/commit/59530e6cfe693fbe2d19e7d7fddff146d95a9d92

I'm open to better ways of performing the below test, in the meantime we've written a trait to give us back the functionality that was lost. Figured I would report the issue nonetheless.

```
/**
 * Page Source
 */

<div id="mytable">
    <img src="image.jpg">
</div>
```

```
/**
 * Test
 */

// Used to pass, now fails.
$this->seeInElement("#mytable", "image.jpg"
```

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell.

**Comment by taylorotwell** [comment]
https://github.com/laravel/framework/pull/11928

@sileence this PR seems to have broken something. Thoughts?

**Comment by sileence** [comment]
I'll take a look and will answer soon.

**Comment by sileence** [comment]
Sorry about that, there is the fix.

**Comment by cat5inthecradle** [comment]
Awesome, that's what I was just seeing today, nodeValue vs Html seemed to be the significant change.
