### ISSUE TITLE
[5.1] vendor:publish doesn't work when --tag and --provider are used together.

### ISSUE THREAD

**Issue by arleslie** [laravel/framework#12081]
Problem: When using `artisan vendor:publish` with both the `--tag` and `--provider` flags, a message of `Nothing to publish for tag[].` is shown.

Example and code sample: https://gist.github.com/arleslie/9979c62e9f5152edd72c
Laravel Version: 5.1

**Comment by devonzara** [comment]
This was fixed in 5.2 already, see #8498 [here](https://github.com/laravel/framework/commit/2925e486b4c498555782edfb506a727dd5707726).

**Comment by arleslie** [comment]
Confirmed issue is fixed in 5.2. Also appears to be fixed in 5.1.28.

As well tested various versions between 5.1.20-5.1.27 and it appears to be resolved then as well. 
Not really sure how I managed to get this to happen to start with as the project was created from 5.1 last month.
