### ISSUE TITLE
Database: fetch mode issues

### ISSUE THREAD

**Issue by okneloper** [laravel/framework#12080]
Connection::setFetchMode() will allow to any PDO fetch mode, however some are not compatible with the framework. For instance, Query/Builder::get() with FETCH_COLUMN will produce one array of values instead of array of objects, and pluck() will produce an array of nulls. This is confusing and very hard to debug, ie if a fetch mode was changed before - this is more likely to happen when using illuminate/database outside of the framework. 

I propose the Builder is checking if current fetch mode is compatible with the framework.

**Comment by GrahamCampbell** [comment]
We're open to PRs. ;)

**Comment by yanshiba** [comment]
when I write some API for thrid library, e.g HighCharts, a js charts. It required must indexed array. 
and assoc array in php will be a object in js after json_encode.

I suggest can has a method return indexed array

**Comment by okneloper** [comment]
@yanshiba you can use `array_values` to transform the data to an indexed array:

```php
<?php
Model::all()->values()
```
