### ISSUE TITLE
Yet another trailing slash issue

### ISSUE THREAD

**Issue by Arcesilas** [laravel/framework#12090]
Hi,

I've read issues about trailing slashes that were removed from request.
I don't like it, but ok. I can handle my urls like I want with Request::getPathInfo(). So it's fine.

However I cannot understand why when I want to redirect to a URL with a trailing slash, the UrlGenerator `Illuminate\Routing\UrlGenerator` removes the trailing slash? What if the website I'm redirecting to **does not work** if I ommit the trailing slash? Who can consider I'm not redirecting correctly because I use a trailing slash in my target URL? I don't understand...

Ok, I'll use a custom UrlGenerator and pass it manually to a `Illuminate\Routing\Redirector` object, it's so easier and shorter than using the `redirect()` helper.

Sorry for being sarcastic, I just spent half a day to rewrite all my controller logic and many classes when I figured out Laravel was removing trailing slash in Request path and then I figured out it was also removing it in the URL I want to redirect to...

Anyway, in my opinion, when you want to redirect to a url with a trailing slash, you should be able to do it easily (or the `redirect()` helper is just of no use and it should just be dumped).

Thanks for your attention.

**Comment by pascalschwientek** [comment]
I kind go agree, if i want to redirect with a trailing slash the url generator should not just removed it. Maybe a force flag?

**Comment by GrahamCampbell** [comment]
We're open to PRs. :)
