### ISSUE TITLE
Translator method inconsistency

### ISSUE THREAD

**Issue by ehsan2e** [laravel/framework#12092]
Class: Illuminate\Translation\Translator

 /**
     * Retrieve a language line out the loaded array.
     *
     * @param  string  $namespace
     * @param  string  $group
     * @param  string  $locale
     * @param  string  $item
     * @param  array   $replace
     * @return string|array|null
     */
    protected function getLine($namespace, $group, $locale, $item, array $replace);

/**
     * Get the translation for the given key.
     *
     * @param  string  $key
     * @param  array   $replace
     * @param  string|null  $locale
     * @param  bool  $fallback
     * @return string
     */
    public function get($key, array $replace = [], $locale = null, $fallback = true);

The "get" method of this class calls getLine which might return string|array|null it handles null perfectly by retrieving the the key which is a string however if getLine returns an array it does not do anything and returns it; hence the correct documentation for this function should be "string|array".

The problem is not the documentation the problem is that this method can return an array which is an improper input to subsequent htmlentities() call in the view.

`htmlentities() expects parameter 1 to be string, array given`

**Comment by GrahamCampbell** [comment]
We're open to PRs. :)
