### ISSUE TITLE
Query Builder stops putting WHERE clauses in quotes, if skip() is used - causing queries to fail

### ISSUE THREAD

**Issue by JackWH** [laravel/framework#12098]
I wrote a function to get an entry from my `Posts` model, along with the previous entry from the same category and of the same post type too:

```
$post = Post::findOrFail($post);

// Get the previous Post in this category too, if it exists
$previous = Post::where('category_id', $post->category_id)
->where('post_type', $post->post_type)
->orderBy('id', 'DESC')
->skip(1)
->get();
```

In theory, that should fetch the same entry we're currently querying, but then just skip by 1 record to get the next oldest.

Every time that query is run, however, this is the resulting SQL:

```
select * from `posts` where `category_id` = 9 and `post_type` = BlogPost order by `id` desc offset 1
```

There's no surrounding quotes around `BlogPost`, which causes the SQL query to break.

Simply removing the `->skip(1)` clause fixes the bug in the resulting SQL.

**Comment by themsaid** [comment]
I don't think that's the reason why your query won't work, if you use `skip()` you must provide `take()`,  with every offset, a limit must be supplied for mysql to work properly.
