### ISSUE TITLE
Where statement with array feature

### ISSUE THREAD

**Issue by WebNinjrDesign** [laravel/framework#12091]
Hey,

I've only been using Laravel for a couple of weeks, love it. I've noticed a lot of the time when you want multiple things to happen the arguments can be either a string or array.

I was wondering if maybe as an equivalent to

$entity = Entity::where('foo' => 'bar')->orWhere('foo' => 'baz')->orWhere('foo' => 'qux')->get();

You could allow the where statement to do...

$entity = Entity::where('foo' => ['foo', 'baz', 'qux'])->get();

I would do this as a pull request, but I haven't dug into the framework far enough yet sorry.

**Comment by willrowe** [comment]
You can use `whereIn` like so:
```php
$entity = Entity::whereIn('foo', ['foo', 'baz', 'qux'])->get();
```

**Comment by WebNinjrDesign** [comment]
..and that is why I love Laravel. Thanks @willrowe!
