### ISSUE TITLE
Global Middleware does not have access to \Auth::user()

### ISSUE THREAD

**Issue by huglester** [laravel/framework#12108]
Hello!

I am in scenario, where I want to redirect user to profile, if he registered without having an email. (for example Twitter login).

I have tried global middleware with something similar:
```php
if ($user = Auth::guard($guard)->user()) {
            if (! $user->email) {
                return redirect()->route('profiles.edit');
            }
        }
```

but $user is always null in GlobalMIddleware.

But when I moved it to $route middle-wares, and it immediately started working, but this way 
I would need to add this middle-ware to every route.

Maybe you have some ideas on how it could be achieved? Maybe even in different (more robust) way.

Thanks

**Comment by GrahamCampbell** [comment]
Please ask questions on the forums.

**Comment by GrahamCampbell** [comment]
NB, it looks to me like you can't solve this in the way you want.
