### ISSUE TITLE
[5.2] Running config:cache breaks .env variables

### ISSUE THREAD

**Issue by maclof** [laravel/framework#12109]
Due to this commit https://github.com/laravel/framework/commit/90af3becf192e8b28c3c859a8dd3d81723935b55 config:cache breaks any of your .env files from working, they all return null.

This is a breaking change compared to 5.1: https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Bootstrap/DetectEnvironment.php

**Comment by GrahamCampbell** [comment]
This is intended. You are never meant to ever use the env functions outside of the cofig files. This change was also documented in our upgrading guide.
