### ISSUE TITLE
[5.1] File download response with UTF-8 encoded file paths and filenames

### ISSUE THREAD

**Issue by avvertix** [laravel/framework#12103]
For a project I had to use the [File Downloads response](https://laravel.com/docs/5.1/responses#file-downloads) in order to make a PDF preview available to the user.

I've then noticed the warning

> Note: Symfony HttpFoundation, which manages file downloads, requires the file being downloaded to have an ASCII file name.

which gave me a couple of problems because the file where stored on disk with UTF-8 encoding.

Digging into the [download response helper](https://github.com/laravel/framework/blob/7f62d81acb2001faafb21a32544464ebfc92476c/src/Illuminate/Routing/ResponseFactory.php#L129) and in the Symfony [BinaryFileResponse](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/HttpFoundation/BinaryFileResponse.php) class I've found that the IllegalArgumentException raised could be somehow prevented if the BinaryFileResponse class is constructed with the parameter `$disposition` set to `null`. This seemed to prevent the automatic filename addition to the response and so prevented the raise of the error.

This is my solution from the code perspective:

```php
public function download($file, $name = null, array $headers = [], $disposition = 'attachment')
{
        $response = new BinaryFileResponse($file, 200, $headers, true, ( is_null($name) ? $disposition : null ) );

        if (! is_null($name)) {
            return $response->setContentDisposition($disposition, $name, str_replace('%', '', Str::ascii($name)));
        }

        return $response;
}
```

I hope this will enable other developers to prevent the Symfony exception.

**Comment by GrahamCampbell** [comment]
Thanks for letting us know.

**Comment by GrahamCampbell** [comment]
We're open to PRs, but we shouldn't be suppressing an exceptions really imo.
