### ISSUE TITLE
Exclude a route from default authentication

### ISSUE THREAD

**Issue by JValck** [laravel/framework#12106]
It should be nice if it would be easier to exclude a route from the default authentication. Now I need to define all the routes manually if I want to remove for example the register route.

It would be much easier if I could just pass a parameter to the `Route::auth()` method.

**Comment by GrahamCampbell** [comment]
Please discuss proposals on slack. We don't process these on github since are issues are here for the community to fix bugs in the framework, and are not a way to communicate with Taylor really.

**Comment by GrahamCampbell** [comment]
Thank you though. :)
