### ISSUE TITLE
Laravel Freezing Views Blade

### ISSUE THREAD

**Issue by shakee93** [laravel/framework#12100]
I am confused. i have tried all workaround. when i load the page it freezes. if i check on chrome task manager memory keeps increasing (200MB+). can someone point me what is the issue in here ?

My Route :

    Route::get('/', function(){
      return view('index');
    });

My Parent Layout : core.blade.php

    <!DOCTYPE html>
    <html>
    <head>
    </head>
    <body>
    
    <div id="container">
    
        @yield('content')
    
    </div>
    
    </body>
    </html>

My Index View : index.blade.php

    @extends('core')

NOTE : if i remove the extends tag. it runs smoothly.

this is my structure

[![enter image description here][1]][1]

  [1]: http://i.stack.imgur.com/wFapy.png

Can someone point me what is this issue ?
i have posted on stackoverflow no response.

**Comment by GinoPane** [comment]
Can you also show the contents of your core.blade.php?

**Comment by shakee93** [comment]
i have attached it . below here

```
<!DOCTYPE html>
<html>
<head>
</head>
<body>

<div id="container">

    @yield('content')

</div>

</body>
</html>
```

**Comment by GinoPane** [comment]
@shakee93 Yep, sorry, I wanted to say "index.blade.php":)

**Comment by shakee93** [comment]
i have removed all contents and just `@extends('core')` left now. but it freezes

**Comment by GinoPane** [comment]
What version of laravel do you use? Cause the same works fine for me, as it should.

You can also try to change ```@yield('content')``` to ```@yield('content', 'Default')```, or try to define:
`@section('content')
Some data
@endsection` in index.blade.php and see if it helps.

**Comment by shakee93** [comment]
![image](https://cloud.githubusercontent.com/assets/14835725/12712641/c64f601c-c8ef-11e5-9faf-866b6230c7be.png)

just tried with what you have said. no luck... any other suggestions ?

Laravel Version is
Laravel Framework version 5.2.12

**Comment by GinoPane** [comment]
It's really strange, cause I've just tried your views on fresh install of 5.2.12 and everything works fine. Maybe you can provide some additional info?

**Comment by shakee93** [comment]
How can i provide ? i just checked laravel log it is blank..

**Comment by shakee93** [comment]
i have added extra repos 
"xethron/migrations-generator": "dev-l5"
"way/generators": "dev-feature/laravel-five-stable"

i have tried removing them too.. no use.. ill try a fresh install and check

**Comment by GinoPane** [comment]
@shakee93 were you lucky with fresh install?

**Comment by shakee93** [comment]
yeah it was working fine. Thanks. but the one i am using is more likely a fresh install. i have a huge rows in the table. that might be the issue ?

**Comment by shakee93** [comment]
how can i debug that ?

**Comment by shakee93** [comment]
and thank you for your effort

**Comment by GinoPane** [comment]
Maybe it was some kind of fuzzy bug. Your code does not involve any tables, so I think they can not be a reason.

**Comment by shakee93** [comment]
how can i debug that ? is their a way ?

**Comment by GinoPane** [comment]
First of all, report and display all errors while in development. And, of course, use some debugger, like xdebug or zend debugger. Or, another option, you can manually put some output and ```die()``` in your code step-by-step to detect problem place.

**Comment by shakee93** [comment]
Okey i found it !! its a bug in chrome probably. when i right click on a blank space. it started to freeze. i have checked with chrome in incognito it works fine and in firefox too..

Thanks for your help @GinoPane 

i am closing this
