### ISSUE TITLE
[5.1+] Model Observer Documentation Missing

### ISSUE THREAD

**Issue by hackel** [laravel/framework#12113]
Have model observers been deprecated?  All information about them was removed from the documentation in laravel/docs@88b62c8 .  If so, this should be added to the release notes.  If not, we should add this documentation back and update it.

**Comment by GrahamCampbell** [comment]
Thanks for reporting, but we don't process docs issues here really.

I'm not aware of them being deprecated, but they're maybe not the recommended way to do it.

**Comment by GrahamCampbell** [comment]
Maybe ask Taylor in private on slack about this. That way you'll know for sure. Our issues aren't really a communication line to him.
