### ISSUE TITLE
Model::create() not working

### ISSUE THREAD

**Issue by mprandot** [laravel/framework#12110]
Hello!
I 'm trying to do an insert using Model :: create ()  ( and `factory(MyClass::class)->create();`)and this is not working, I'm passing an array with the attributes and values ​​( this array == $ fillable in the model) and only created_at and updated_at is passed to save ...

As I said earlier the fields of the array are the same as $ fillable variable.

The code:

    $conta = new Conta();
    $conta->create([
        'pessoa_i' => 1,
        'vendedor_id' => 1,
        'titulo' => 'testing',
        'data_emissao' => date('d/m/Y'),
        'vlr_total' => 'teste',
        'vlr_restante' => 0,
        'qtd_parcelas' => 0,
        'tipo_operacao' => 'R',
        'tipo_documento' => 'TITULO'
    ]);

Error message: 

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`68711868000133_db`.`contas_receber_pagar`, CONSTRAINT `contas_receber_pagar_pessoa_id_foreign` FOREIGN KEY (`pessoa_id`) REFERENCES `pessoas` (`id`)) (SQL: insert into `contas_receber_pagar` (`updated_at`, `created_at`) values (2016-02-01 19:15:31, 2016-02-01 19:15:31))

My class :

class Conta extends Model {
    use PresentableTrait;
    protected $presenter = ContaPresenter::class;

    protected $fillable = [
        'pessoa_id',
        'vendedor_id',
        'titulo',
        'data_emissao',
        'vlr_total',
        'vlr_restante',
        'qtd_parcelas',
        'observacao',
        'tipo_operacao',
        'tipo_documento', 
        'nro_cheque',
        'nro_conta_cheque',
        'nro_agencia_cheque',
        'banco_cheque',
    ];
    
Can verify?

**Comment by mprandot** [comment]
laravel 5.1

**Comment by GrahamCampbell** [comment]
Please ask questions on the forums.

**Comment by mprandot** [comment]
@GrahamCampbell 
This is not a question , it is a potential problem , when you have foreign key the method Model :: create () does not work, see yourself!

**Comment by GrahamCampbell** [comment]
Ah, right. Sorry. What exact laravel version please?

**Comment by acasar** [comment]
It's either a typo (you are trying to insert pessoa_i instead of pessoa_id) or you are generally missing a pessoa record with an id of 1.

**Comment by mprandot** [comment]
@GrahamCampbell  5.1!

@acasar Really I was wrong, but I tested again with ' pessoa_id ' correct and happens the same error!

@GrahamCampbell  maybe this help you! in the debug process:

 public static function create(array $attributes = []) {
        $model = new static($attributes);  --- this line excluded the attributes
        $model->save();
        return $model;
    }

**Comment by GrahamCampbell** [comment]
> @GrahamCampbell 5.1!

More specific please.

**Comment by acasar** [comment]
@mprandot Do you have any mutators? I still highly doubt that it's a bug in Laravel.

**Comment by GrahamCampbell** [comment]
Feel free to ask on the forums, and post back here in a new issue if you have an isolated bug report for us.
