### ISSUE TITLE
Add parameters to closure of whereHas

### ISSUE THREAD

**Issue by let-aurn** [laravel/framework#12112]
[Docs](https://laravel.com/docs/5.2/eloquent-relationships#querying-relations) says

    // Retrieve all posts with at least one comment containing words like foo%
    $posts = Post::whereHas('comments', function ($query) {
        $query->where('content', 'like', 'foo%');
    })->get();

What if we want to pass args to the closure? Like this

    // Retrieve all posts with at least one comment containing words like given
    $posts = Post::whereHas('comments', function ($query, $search) {
        $query->where('content', 'like', '%$search%');
    })->get();

In `Eloquent\Builder.php#has()` we have

        if ($callback) {
            call_user_func($callback, $query);
        }

which use `$query` as the one and only parameter.

**Comment by acasar** [comment]
```php
$posts = Post::whereHas('comments', function ($query) use ($search) {
    $query->where('content', 'like', '%$search%');
})->get();
```

http://php.net/manual/en/functions.anonymous.php#example-197

**Comment by lagbox** [comment]
```php
Blah::whereHas('relation', function ($q) use ($anyvaryouwant) {
     $q->where('something', $anyvaryouwant);
});
```
