### ISSUE TITLE
Add csrf token input override

### ISSUE THREAD

**Issue by MordiSacks** [laravel/framework#12128]
Is it possible to get in the next update a protected field on this class
[framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php)
that will override "_token"?
"tokenMatch" method will change on line 111 to
`$token = $request->input($this->_token) ?: $request->header('X-CSRF-TOKEN');`

and the default for 
`$this->_token`
will be "_token"

That way, if I don't want to use token, let's say I wanna use "bob"
I could!

Thank's guy's you are doing a great job here.

**Comment by GrahamCampbell** [comment]
Should be possible. Just extend that middleware as you need.
