### ISSUE TITLE
terminate milddleware specified in controller  nerver be called

### ISSUE THREAD

**Issue by ChitaGideon** [laravel/framework#12121]
specify a middleware in controller 
```
    public function __construct(){
        $this->middleware('test.md');
    }
```
If this middleware is terminable middlware ,
the `termiante` method is never be called ,
but `handle` method can be called correctly.

both in lavarel 5.1 & lavarel 5.2

**Comment by GrahamCampbell** [comment]
We don't support terminable middleware from inside controllers, sorry.
