### ISSUE TITLE
Incorrect routes created by Artisan make:auth

### ISSUE THREAD

**Issue by paul-muckypuddle** [laravel/framework#12127]
Not sure if this is a bug or an issue I've had due to a 5.1 -> 5.2 upgrade, but I believe the routes specified in [this file](https://github.com/laravel/framework/blob/78bc6234d337a3e4f1a91b44531c730a988f9091/src/Illuminate/Routing/Router.php) are incorrect. The following:

```
public function auth()
{
    // Authentication Routes...
    $this->get('login', 'Auth\AuthController@showLoginForm');
    $this->post('login', 'Auth\AuthController@login');
    $this->get('logout', 'Auth\AuthController@logout');
    // Registration Routes...
    $this->get('register', 'Auth\AuthController@showRegistrationForm');
    $this->post('register', 'Auth\AuthController@register');
    // Password Reset Routes...
    $this->get('password/reset/{token?}', 'Auth\PasswordController@showResetForm');
    $this->post('password/email', 'Auth\PasswordController@sendResetLinkEmail');
    $this->post('password/reset', 'Auth\PasswordController@reset');
}
```

results in the the `email.blade.php` and `reset.blade.php` views having empty error bags on failed validation. Changing

`$this->post('login', 'Auth\AuthController@login');`

to

`$this->post('login', 'Auth\AuthController@postLogin');`

fixes the issue for login forms, and likewise for the password reset email form, changing:

`$this->post('password/email', 'Auth\PasswordController@sendResetLinkEmail');`

to

`$this->post('password/email', 'Auth\PasswordController@postEmail');`

However, if this is due to something I missed in the upgrade I'd be happy to find out what!

**Comment by GrahamCampbell** [comment]
Thanks, but this isn't a bug, it's just a change that was made in 5.2. Feel free to ask on the forums if you need more advice than what's in our upgrading guide.

**Comment by paul-muckypuddle** [comment]
Thanks for the reply - out of interest, what exactly was the change?

**Comment by GrahamCampbell** [comment]
Some get stuff changed to post, or something like that. I'm sure it was documented though.
