### ISSUE TITLE
[L5.2.12] Auth::check() always use the default guard in multi-auth

### ISSUE THREAD

**Issue by Cyrille37** [laravel/framework#12125]
Hi,
I'm coming back about multi-auth.

I did multi-auth working with 2 `AuthController` by overriding their `$guard` property. It works for access managment via route and middleware like `Route::get(...)->middleware('auth:admin')` or `Route::get(...)->middleware('auth:user')`.

The problem is in Views: call to `Auth::check()` **always use the default guard nor the one used at login**.

**Comment by Cyrille37** [comment]
That a real problem because when user is logged in with **the non default guard**, on route without the auth middleware `Auth::check()` return false and `Auth::guard()->user()` is null.
Those facts are not true when user is logged with the **default guard**.

**Comment by Cyrille37** [comment]
As a *temporay solution* I use a parent controller for all controllers like:
```
class Controller extends BaseController
{
	use AuthorizesRequests, DispatchesJobs, ValidatesRequests;

	public function __construct()
	{
		if( \Auth::guard('admin')->check() )
		{
			\Auth::setDefaultDriver( 'admin' );
		}
		else if( \Auth::guard('user')->check() )
		{
			// Not need because it's the default guard ;-)
			\Auth::setDefaultDriver( 'user' );
		}
	}
        ...
}
```

**Comment by saint-father** [comment]
It's not a bug. You can use the "mergeConfigFrom" (Illuminate\Support\ServiceProvider) and overwrite default guard in the auth config option. But there is another bug :) [array_merge bug in the mergeConfigFrom ](https://github.com/laravel/framework/issues/12159)
