### ISSUE TITLE
Create a combined Route:: method for PUT|PATCH

### ISSUE THREAD

**Issue by joseph-d** [laravel/framework#12122]
In `framework/src/Illuminate/Routing/Router.php` the `resource()` method creates (among other things) a combined `PUT|PATCH` route for the `update` controller method.

However, when creating a route manually, the only option is to do `match(['PUT','PATCH'] ... );`

It would be useful if there was a dedicated method to create `PUT|PATCH`, (like we have with `Route::get()` creating `GET|HEAD`) if only to make it consistent with what `Route::resource` creates.

**Comment by iWader** [comment]
`PUT` and `PATCH` are two different verbs and by definition don't work together.

`PUT` expects the entire resource, `PATCH` on the other hand expects just the attributes that should be updated, if you're following RESTful methods that is. You would then require 2 different sets of validation rules.

I don't think this should be the default and currently using `match()` gives the designed behaviour.
