### ISSUE TITLE
[5.2] validation after when using $this

### ISSUE THREAD

**Issue by tomswinkels** [laravel/framework#12139]
I want validate something after my validation rules.

When i use Validator::make it works, but i want use $this->validate.
Is there any other option how i can do that?

I have try;

`$this->validate( $request, $rules, $messages )->after(function( $validator ) use ( $request )
{
        if ( $request->input('username') == 'tom' )
	{
		$validator->errors()->add('username', 'Something is wrong with this field!');
	}
});`

I get no errors, but it doesn't work.

Thanks!

**Comment by EliasZ** [comment]
@tomswinkels I have added a missing assertion to verify your issue and it passes (aka it works at is supposed to) so there must be something wrong with your userland code.

Try the Laravel forums.

**Comment by tomswinkels** [comment]
Hi @EliasZ 

In your test you use "new Validator" but i want use "$this->validate".

The function "$this->validate" is very nice with return error messages.

When i use "$this->validate()->after()" i get this error "Fatal error: Call to a member function after() on null".

**Comment by JosephSilber** [comment]
The `validate` method doesn't return the validator instance.

If you want to use your own validator instance, use this:

```php
$validator = validator($request->all(), $rules, $messages);

$validator->after(function ($validator) use ($request) {
    if ($request->input('username') == 'tom') {
        $validator->errors()->add('username', 'Something is wrong with this field!');
    }
});

$this->validateWith($validator);
```

[In 5.3 you'll be able to do this](https://github.com/laravel/framework/pull/12380):

```php
validator($request->all(), $rules, $messages)->after(function ($validator) use ($request) {
    if ($request->input('username') == 'tom') {
        $validator->errors()->add('username', 'Something is wrong with this field!');
    }
})->validate();
```

**Comment by tomswinkels** [comment]
@JosephSilber Thanks for you're answer. The first code i use it now, but i want use the second code :dancer:
