### ISSUE TITLE
php artisan make:controller does not change it's output path.

### ISSUE THREAD

**Issue by imanghafoori1** [laravel/framework#12132]
After modifying the $namespace property
```  
class RouteServiceProvider extends ServiceProvider
{
 /**
     * This namespace is applied to the controller routes in your routes file.
     *
     * In addition, it is set as the URL generator's root namespace.
     *
     * @var string
     */
    protected $namespace = 'App\Http\Controllers';
```
and moving the Controllers to somewhere else. (let's say one level up out of the HTTP folder)
protected $namespace = 'App\Controllers'
The 'make:controller ' command still blindly generates the new files in the /Http/Controllers folder !
==========

The problem is on the ControllerMakeCommand class.
On the "getDefaultNamespace" method, it does not read the '\Http\Controllers' part dynamically from anywhere and is using a hard coded default value. (As shown below)
This string should be read from protected $namespace on the RouteServiceProvider class
in the RouteServiceProvider
```
class RouteServiceProvider extends ServiceProvider
{
.
.
.
    protected function getDefaultNamespace($rootNamespace)
    {
        return $rootNamespace.'\Http\Controllers';   <===  hard coded string !
    }

```

Note: The namespace in the generated Controller files should also be set according to the
 protected $namespace value.
```
use App\Http\Controllers\Controller; // I mean this line
```

**Comment by arrilot** [comment]
`protected $namespace = 'App\Http\Controllers';` is only applied to routing, not console generators.
And unfortunately generators aren't really configurable.
They lose a lot of power if you don't follow existing conventions.

**Comment by imanghafoori1** [comment]
I see most people create a models directory and put their models there.
But they have no way to configure Artisan to follow it.
On 18 Feb 2016 11:19 PM, "Nekrasov Ilya" <notifications@github.com> wrote:
>
> protected $namespace = 'App\Http\Controllers'; is only applied to
routing, not console generators.

**Comment by arrilot** [comment]
Well it's not that bad in that case - `php artisan make:model Models/Blog` do the trick.

I had a PR allowing custom generator stubs a year ago #3385 but Taylor rejected it

**Comment by imanghafoori1** [comment]
They are always afraid of accepting people code.

Better to only inform them of the missing needed features and let them to
write the implementation as the like.

You know they have a laravelish way of coding which keep the framework
consistent.

On 19 Feb 2016 12:31 AM, "Nekrasov Ilya" <notifications@github.com> wrote:
>
> Well it's not that bad in that case - php artisan make:model Models/Blog
do the trick.
>
> I had a PR allowing custom generator stubs a year ago #3385 but Taylor
rejected it

**Comment by vlakoff** [comment]
links #12245 which is quite similar, for `make:auth` scaffold.

**Comment by themsaid** [comment]
I don't really think this is a "bug" but rather lack of configuration situation, so based on that and since this is an old issue with no noticeable interest from the community to open a PR, based on all of that I'm going to close this issue, sorry :)

But please feel free to open a PR if you want
