### ISSUE TITLE
$this->dispatch always returns 0

### ISSUE THREAD

**Issue by LasseHaslev** [laravel/framework#12135]
I got this is handler function in TestJob
`public function handle()
    {
        return 'test';
    }`

I run this function in my controller
`$test = $this->dispatch( new TestJob );`

When die and dump i get this:
`echo dd( $test ) // returns 0`

What I would expect is:
`echo dd( $test ) // returns 'test'`

This worked in Laravel 5.1.. is this expected in 5.2 or a bug?

**Comment by GrahamCampbell** [comment]
No, it's a job, so it gets executed by the processor later on. You'll never see the return value of the handle function inline.
