### ISSUE TITLE
auth::guard() behaves incorrectly. (Bug)

### ISSUE THREAD

**Issue by imanghafoori1** [laravel/framework#12130]
```  
  Route::get('/q', function () {

        return (string) Auth::guest();
    });

    Route::group(['middleware' => 'web'], function () {

        Route::get('/a', function () {
            return (string) Auth::guest();
        });
    });
```
In one of them "Auth::guest();" returns true the other returns false !!!
Why is that ?!
Both of the should return false since I am logged in.

**Comment by imanghafoori1** [comment]
I am on version 5.2.12

**Comment by crynobone** [comment]
```php
Route::get('/q', function () {
    return (string) Auth::guest();
});
```

Without the `"web"` middleware, this route doesn't load any session, unless you're authenticating with stateless auth it is going to return `false`.

Not a bug.

**Comment by imanghafoori1** [comment]
Ok, Thanks
