### ISSUE TITLE
[5.2] Route Parameter Constraints removed from documentation

### ISSUE THREAD

**Issue by shssoichiro** [laravel/framework#12131]
I'm posting this here since issues on laravel/docs are closed.

I was searching in the documentation for regular expression constraints on routes and noticed that it's been completely deleted from the documentation on the 5.2 branch, since [this commit](https://github.com/laravel/docs/commit/fa6e3c104238955c53fb37b1173c503d9411f640). The feature is still present in 5.2.12, so I was wondering if it was intentional that this documentation was deleted?

**Comment by thibaultlavoisey** [comment]
+1

**Comment by ctf0** [comment]
same here

**Comment by jacobnijgh** [comment]
+1

**Comment by canfiax** [comment]
+1

**Comment by lagbox** [comment]
Put in a PR to add it back.

**Comment by majimboo** [comment]
+1, also, is it possible to the constraints to a group?

**Comment by ctf0** [comment]
@majimboo maybe this could be achived through a middleware ?
