### ISSUE TITLE
[5.2] Session::flash() doesn't works any more for laravel 5.2

### ISSUE THREAD

**Issue by amranidev** [laravel/framework#12134]
I try to set session message trough Session::flash() does not works for 5.2. instead it works for 5.1.
Thanks.

**Comment by GinoPane** [comment]
What exact problem do you have? I've tested session::flash() on 5.2.13 and it worked fine.

**Comment by GrahamCampbell** [comment]
Please post a new issue if you can provide a concise way to replicate this.

**Comment by avescasio** [comment]
Same here: please check https://github.com/laracasts/flash/issues/60
