### ISSUE TITLE
[5.2] Session::flash() doesn't works any more for laravel 5.2 (USING AJAX)

### ISSUE THREAD

**Issue by amranidev** [laravel/framework#12136]
Well this is the problem.

For example.

Controller side
```php
public function foo()
{
      // do somthing
      Session::flash('status','Foobar');
      
      return URL::to(......);
}
```
javascript 
```javascript
$.ajax({
   .
   .
   .
  success:function(response){
      window.location.replace(response)
  }

})

```
view side 

```html
        @if (session('status'))
           <p>{{ session('status') }}</p>
         @endif
```

for Laravel 5.2.* it's not showing anything . instead it's works using Laravel 5.1

**Comment by mohamedsharaf** [comment]
make sure all routes uses web middleware 
Route::group(['middleware' => 'web'], function () {
// routes here
    Route::get('/login', 'Auth\AuthController@showLoginForm')->name('login');

});

**Comment by amranidev** [comment]
@mohamedsharaf  Thanks

**Comment by mohamedsharaf** [comment]
welcome keep not also auth routes should be within web otherwise u will not be aable to get Auth::user()

this also know as 
laravel 5.2 login not working after redirect

**Comment by amranidev** [comment]
@mohamedsharaf yes you'r right.
but I want to know did middleware (web) by default exist right laravel 5.1 ?
cuz we might got problems when we develop laravel packages supporting (5.1, 5.2)

**Comment by mohamedsharaf** [comment]
groups of middleware  is new in 5.2
open kernal.php for both version and u will get it

**Comment by GrahamCampbell** [comment]
> open kernal.php for both version and u will get it

It's not really the same time of thing though, since the groups are run by the routing layer, but the global middleware wrap around that entire layer from the outside.

**Comment by mohamedsharaf** [comment]
@amranidev 
@GrahamCampbell   sorry for double mention 
https://github.com/laravel/framework/issues/12141

**Comment by Jayaramvenkatanarayanan** [comment]
I am also in same situation, i have request to store the data. My data's are stored but i have tried to show the flash message but i did not get that (also laravel/flash )...

Pl help me

**Comment by amranidev** [comment]
@Jayaramvenkatanarayanan 
make sure all routes uses web middleware 
```php 
Route::group(['middleware' => 'web'], function () {
// routes here

});
```

**Comment by Jayaramvenkatanarayanan** [comment]
Thanks now its work on me !!!!!


Thanks & Regards,
Jayaram Venkatanarayanan.


________________________________

**Comment by kaiyulee** [comment]
strange. even I use `web` middleware, it still not working , no flash data stored in session, then I change middleware to `auth`, it does the work. also strange thing is I can just get one data even I use mutiple chain `with` method.

my routes like this:

```php
Route::group(['namespace' => 'Package', 'prefix' => 'package', 'middleware' => ['auth']], function () {
    Route::get('catelog/new', 'CatelogController@add');
    ....
}
```

set flash data:
```php
return redirect()->back()
                ->with('page_message', 'success')
                ->with('page_code', 0);
```

After I successfully adding. I can only get the `page_code = 0`, with the `auth` middleware.


What I have missed?

**Comment by Jayaramvenkatanarayanan** [comment]
Hi all,

Above laravel 5.2 without using middelware function bootstrap session messages will be work.

Thanks
