### ISSUE TITLE
Permission bug

### ISSUE THREAD

**Issue by mahanhaz** [laravel/framework#12145]
hi everybody. me and my team spent almost 4 hours to findout that why our application shows error 500 on some of our application pages which was super annoying because on some machines it was working perfect and on some other we had problem and laravel doesn't even write anything on any log file.

our problem was wrong permission that we had on the storage directory which was related to caching data.

our problem didn't even solve with composer install or dump-autoload.
and suddenly one guy on the team mentioned something about checking the permission on the storage dir. we did it and it was working perfectly.

now my question is, is there any mecanism for this that atleast shows an error on the error page or log file that we have a permission problem or it's a thing that we should put it in to laravel's framework?

and if the answare is yes, can i spend time on it and create the PR for it or it's not a good idea?
thanks and have a good day or night

**Comment by GrahamCampbell** [comment]
Thanks, but this is just an error in your setup. Make sure your webserver has ownership over the app files.

**Comment by ddimaria** [comment]
This folder permission/ownership is a prerequisite to using Laravel.  But, if you want more info about errors, just hook into the `/app/Exceptions/Handler::report()` method:

```public function report(Exception $e)
{
	// some quick data about the error for local development
	if (\App::environment('local')) {
		
		die(
			"File: " . $e->getFile() . 
			"\nLine: " . $e->getLine() . 
			"\nMessage: " . $e->getMessage() . 
			"\n\nTrace:\n" . substr($e->getTraceAsString(), 0, 25000)
		);
	}

	return parent::report($e);
}```
