### ISSUE TITLE
[5.2] pushMiddleware to the "web" middleware group

### ISSUE THREAD

**Issue by mohamedsharaf** [laravel/framework#12141]
in previous version 5.1 i was able to push and prepend middleware from serviceprovider boot()
     
$this->app->make('Illuminate\Contracts\Http\Kernel')->pushMiddleware('App\Http\Middleware\Localizer');

function pushMiddleware($middleware) accepts only one paramater how to pass the group

**Comment by GrahamCampbell** [comment]
Groups are not at all the same as global middleware. The groups are attached to the router layer.

**Comment by mohamedsharaf** [comment]
$this->app['router']->middlewareGroup('web',[
                    \App\Http\Middleware\EncryptCookies::class,
                    \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
                    \Illuminate\Session\Middleware\StartSession::class,
                    \Illuminate\View\Middleware\ShareErrorsFromSession::class,
                    \App\Http\Middleware\VerifyCsrfToken::class,

                    \Custom\Base\Locale\Http\Middleware\languageDetector::class,

                ]);

i can redeclear all the web group like this 

but what i need is to push my middleware to the end of Middleware group web in  dynamic way


@GrahamCampbell

**Comment by mohamedsharaf** [comment]
@GrahamCampbell
