### ISSUE TITLE
whereIn() missing from Collection

### ISSUE THREAD

**Issue by perdeepOsingh** [laravel/framework#12140]
[https://laravel.com/docs/5.2/collections#method-wherein](url)

Collection missing whereIn().

Is it removed?

Lumen 5.2

**Comment by ThiagoBr91** [comment]
Same problem. Have you found out the reason?

**Comment by perdeepOsingh** [comment]
@ThiagoBr91 it was false alarm, I can find it in Illuminate\Database\Query

**Comment by ThiagoBr91** [comment]
Thanks, @perdeepOsingh, but it didn't work for me. I've used other Collection methods in Laravel 5.2 and they are OK, but whereIn and whereInLoose aren't. I've tried whereIn in Laravel 5.3 and it works properly.
