### ISSUE TITLE
give names for routes that Route::auth() generate

### ISSUE THREAD

**Issue by mohamedsharaf** [laravel/framework#12142]
i suggest it be like this so i can easily call the rout by name also fix stubs for view to use route() instead url()

Route::get('/login', 'Auth\AuthController@showLoginForm')->name('login');
    Route::post('/login', 'Auth\AuthController@login');
    Route::get('/logout', 'Auth\AuthController@logout')->name('logout');

    // Registration Routes...
    Route::get('/register', 'Auth\AuthController@showRegistrationForm')->name('register');
    Route::post('/register', 'Auth\AuthController@register');

    // Password Reset Routes...
    Route::get('/password/reset/{token?}', 'Auth\PasswordController@showResetForm')->name('resetPassword');
    Route::post('/password/email', 'Auth\PasswordController@sendResetLinkEmail')->name('emailPassword');
    Route::post('/password/reset', 'Auth\PasswordController@reset');

**Comment by GrahamCampbell** [comment]
Closing since there is a PR open now.
