### ISSUE TITLE
array_merge bug in the mergeConfigFrom (Illuminate\Support\ServiceProvider)

### ISSUE THREAD

**Issue by saint-father** [laravel/framework#12159]
\Illuminate\Support\ServiceProvider.php line 67 function "mergeConfigFrom"
`$this->app['config']->set($key, array_merge($config, require $path));` 
The bug is `array_merge($config, require $path)` .. need to use the `array_merge(require $path, $config)` instead. 
When I use the "mergeConfigFrom" my config options (same key) should be overwritten. Try to debug this feature with the custom "auth" config (useful for multiauth).

**Comment by GrahamCampbell** [comment]
We intentionally override in the order that we do.

**Comment by GrahamCampbell** [comment]
You need to call the merge config method in the BOOT method, AFTER the user config has loaded.
