### ISSUE TITLE
Database (path-to-my-databes-database.sqlite) does not exist.  In Migration                              

### ISSUE THREAD

**Issue by michaeljcoyne** [laravel/framework#12157]
I can't find any documentation on this so I am asking.

I changed my config to work with sql lite file.

Then ran a migration refresh.

I get the error. Database (path-to-my-databes-database.sqlite) does not exist. 

I read somewhere that laravel will generate the sql lite file if it doesn't exist.

It - isn't in my case. An I want it to.

What is the correct way to do this if isn't a bug?

**Comment by acasar** [comment]
You need to create an empty file yourself:

```
touch path/to/database.sqlite
```

**Comment by kkiernan** [comment]
Yeah I always create the sqlite file myself. Laravel will look for it as specified in the config/database.php file, which by default is database/database.sqlite.
