### ISSUE TITLE
Over-length session payloads (for database MySQL session handler) silently cause session regeneration and dataloss.

### ISSUE THREAD

**Issue by capitaladot** [laravel/framework#12168]
Version: 5.1.8
PHP 5.5.30-1+deb.sury.org~precise

What should happen: when exceeding the maximum length of an allowable session payload, an exception should be thrown to indicate to the developer that the schema for the session store is inadequate.

What actually happens: session payloads that exceed the limits of the default database session migration-created "payload" field cause the session to be regenerated and the values stored in the payload to be lost. Presumably, the over length payload is truncated and cannot be serialized/unserialized correctly on successive requests, thus causing logic in the session handler to create a new, empty session.

Work-around: a migration to change the field definition of "payload" from "text" to "mediumText"; symptom described above vanishes.

**Comment by GrahamCampbell** [comment]
> Work-around: a migration to change the field definition of "payload" from "text" to "mediumText"; symptom described above vanishes.

We'd accept a PR for that please.
