### ISSUE TITLE
Model and Pivot, attribute filling on constructor have different behaviour [L 5.2]

### ISSUE THREAD

**Issue by lcjury** [laravel/framework#12179]
I'm not sure if they should have the same behaviour (and this is or not a real issue, but the docs don't really clarify and I don't completely get the source code), but as Pivot is just a table on the middle I think it should.

I have this:
```
 protected $dates = ['birthday'];
  public function setBirthdayAttribute($birthday) 
{
  if( $birthday == "") return null; // if the user don't want to put his birthday
 return $this->attributes['birthday'] = \Carbon\Carbon::createFromFormat('d/m/Y', $birthday);
}
public function getBirthdayAttribute($birthday)
{
  if( $birthday == "0000-00-00" ) return "";
   return $this->asDateTime($birthday)->format('d/m/Y');
}
```

That code works perfect on a Eloquent/Model, When I echo birthday it print on my format and I can do `$a->birthday = '16/10/1922`.

Now, I have a custom class that extend from `Pivot`, when laravel creates an instance the setters are called, but when using a `Model` class, just the `attribute` array is filled without calling to the setters.

Why their behaviour is different?

bonus question (help please): why I can't use getters on pivot tables? :(? what is the idea of having getters if they are not called when using pivot tables?

**Comment by GrahamCampbell** [comment]
> Model and Pivot, attribute filling on constructor have different behaviour

Laravel minor releases are breaking. Likely we need a breaking change here. I can't remember the fine details, but feel through to have a look through the merged PRs. I always label them all with the target version to make them searchable.

> bonus question (help please)

Unfortunately, we do not process support requests on GitHub. Please ask on the forums.
