### ISSUE TITLE
add an option to enable/disable Query log

### ISSUE THREAD

**Issue by ctf0** [laravel/framework#12170]
when i try to `print_r(DB::getQueryLog())` it always give an empty array unless i changed the settings in 
`src/Illuminate/Database/Connection.php` as in here https://github.com/laravel/framework/commit/e0abfe5c49d225567cb4dfd56df9ef05cc297448

so is there any chance we can enable this option automatically when the user enable the debug mode, or even have a separate option to enable/disable it ?

**Comment by GrahamCampbell** [comment]
This is something you can easily do in your app service provider if you really want it.

**Comment by ctf0** [comment]
@GrahamCampbell can u plz tell me how to enable it through the app service provider ???
