### ISSUE TITLE
[5.2] Login validation must be placed in the Laravel App, not in the framework

### ISSUE THREAD

**Issue by let-aurn** [laravel/framework#12177]
I think Login validation shouldn't be placed in the core

[laravel/framework - Illuminate/Foundation/Auth/AuthenticatesUsers.php](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Auth/AuthenticatesUsers.php#L94)

    /**
     * Validate the user login request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return void
     */
    protected function validateLogin(Request $request)
    {
        $this->validate($request, [
            $this->loginUsername() => 'required',
            'password' => 'required',
        ]);
    }

IMHO it should be done right in the app

[laravel/laravel - Controllers/Auth/AuthController.php](https://github.com/laravel/laravel/blob/master/app/Http/Controllers/Auth/AuthController.php)

---

I am building an app which could handle 2 different types of login ways 
- email / password
- facebook

On the server side Laravel requires a password.. That doesn't make sense in when using Facebook JS SDK (for some reasons, Socialite is not what I need here).

    // ajax post
    'data': {
        'provider' : 'facebook',
        'email' : user.email,
        'oauth_id' : user.id
    }

**Comment by GrahamCampbell** [comment]
> IMHO it should be done right in the app

Then do it in the app? We're not forcing anyone to do anything. We just provide some boilerplate to speed people along.

**Comment by let-aurn** [comment]
When I post my data (without any `password` field), the request is intercepted by this validation. And so exception is thrown.

I don't want to edit Laravel's core (I consider it as a bad practice, even if Laravel lets developers to do it).

For more flexibility please let us handle this the way we want. 

Of course, boilporate are appreciated. But this one should be shipped with [laravel/laravel - Controllers/Auth/AuthController.php](https://github.com/laravel/laravel/blob/master/app/Http/Controllers/Auth/AuthController.php), as it actually is like bellow

    /**
     * Get a validator for an incoming registration request.
     *
     * @param  array  $data
     * @return \Illuminate\Contracts\Validation\Validator
     */
    protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => 'required|max:255',
            'email' => 'required|email|max:255|unique:users',
            'password' => 'required|confirmed|min:6',
        ]);
    }
