### ISSUE TITLE
auth.login event is fired on every Route call

### ISSUE THREAD

**Issue by BlazeNikhilesh** [laravel/framework#12176]
This is my EventServiceProvider

    protected $listen = [
    		'event.name' => [
    			'EventListener',
    		],
    		'auth.login' => [
    			\App\Listeners\UserEventLoginHandler::class,
    		],
    	];

And this is my UserEventLoginHandler

    class UserEventLoginHandler {
     
    	public function handle($event) {
    
    		$user = \Auth::user();
    
    		$user->last_login_at = Carbon::now();
    
    		$user->save();
    
    		$user_login_log = new UserLoginLog;
    
    		$user_login_log->user_id = $user->user_id;
    		$user_login_log->ip_address = $_SERVER['REMOTE_ADDR'];
    		$user_login_log->logged_in_at = Carbon::now();
    
    		$user_login_log->save();
    	}
    }

The problem I am facing is every API call, even if the user is logged in, this event runs. 
Shouldn't it run only when user logins for the first time?

Do I have to make some changes anywhere else? Or is there a mistake in my code somewhere?

Routes.php

    Route::group(['prefix' => 'api/v1/finance', 'middleware' => ['auth', 'sessionExpired']], function () {
        Route::get('/details', ['uses' => '\App\Http\Controllers\Finance\FinanceController@index']);
    });

Now on every API call, two queries which are not needed (Update to user table and Insert to user login log), are executed. 

Can I optimize this process?

**Comment by GrahamCampbell** [comment]
Please ask questions on the forums.
