### ISSUE TITLE
Can make timestamps name by myself?

### ISSUE THREAD

**Issue by jumbycc** [laravel/framework#12188]
i haved some using table in database.
in it timestamps named createtime / updatetime.
in laravel it named create_at /update_at.
i don't want to change the \framework\src\Illuminate\Database\Schema\Blueprint.php file.
so i don't want to change my table field too.
how can i do it , on laravel5?

**Comment by mikerockett** [comment]
This is a support question, and should be asked at either StackOverflow or the forums at [Laracasts](https://laracasts.com/discuss) or [Laravel.io](http://laravel.io/forum).
