### ISSUE TITLE
[5.2] Route with an Array as action being mistaken with closure.

### ISSUE THREAD

**Issue by Milewski** [laravel/framework#12187]
i would like to set up routes like this 

```
$app->get('/', [HomeController::class, 'index']);
//or
$app->get('/')->uses([HomeController::class, 'index']);
//or
$app->get('/', HomeController::class, 'index');
```

So i would get refactoring on my IDE to work properly

However by inspecting the Laravel source code i found out this line

```
// If the action is already a Closure instance, we will just set that instance
// as the "uses" property, because there is nothing else we need to do when
// it is available. Otherwise we will need to find it in the action list.
if (is_callable($action)) {
  return ['uses' => $action];
}
```
On line 536 in **Illuminate\Routing\Route**@parseAction

As i see on the commentaries it is instead to receive a Closure instance... how ever the function is_callable() also returns true if it receives an array [ValidClassPath::class, ValidMethod] so it causes laravel to mistake the action with a Closure.

I feel it just need a fix on this parser... to check again it the action is really a closure or an array. 

underlying the return code of the parser is

```
array:1 [▼
  "uses" => array:2 [▼
    0 => "App\Http\Controllers\HomeController"
    1 => "index"
  ]
]
```

instead of 

```
array:2 [▼
  "uses" => "App\Http\Controllers\HomeController@index"
  "controller" => "App\Http\Controllers\HomeController@index"
]
```

**Comment by jimrubenstein** [comment]
I also need this feature for a project I'm working on. I've got a [simple] solution written, and it works with 5.1.

Should I submit a PR against this issue + back to branch 5.1? Or back to Master?

**Comment by SkysoulDesign** [comment]
a simples solution i found out temporarily was creating a helper function

```
function classie($class, $method)
{
    $namespace = 'App\Http\Controllers\'';
    return str_replace($namespace, "", $class) . '@' . $method;
}
```

then i would use like this

```
Router::get('/', classie(HomeController::class, 'index'))->name('home');
```

**Comment by Milewski** [comment]
a simples solution i found out temporarily was creating a helper function

```
function classie($class, $method)
{
    $namespace = 'App\Http\Controllers\'';
    return str_replace($namespace, "", $class) . '@' . $method;
}
```

then i would use like this

```
Router::get('/', classie(HomeController::class, 'index'))->name('home');
```

**Comment by acasar** [comment]
Just delete the default namespace group: https://github.com/laravel/laravel/blob/master/app/Providers/RouteServiceProvider.php#L40

Then you can use the ``::class`` syntax normally:

```php
Route::get('/', HomeController::class . '@index');
```

**Comment by barryvdh** [comment]
See also https://github.com/laravel/framework/pull/11300

**Comment by Milewski** [comment]
@acasar cant believe that all i had to do was just add '@' in the method.... it did it!
