### ISSUE TITLE
Cannot call Auth::user() in blade layouts without a tweak

### ISSUE THREAD

**Issue by let-aurn** [laravel/framework#12199]
Assuming this route:

    Route::get('/test', function() {
        Auth::login(User::find(1));
        return view('user.profile');
    });

The file `user/profile.blade.php`contains

    @extends('layouts.master')

    @section('content')
         Hello {{ Auth::user()->name }}
    @endsection

Working good.

But if I call `Auth::user()` from file `layouts/master.blade.php`, I have 100 nested level error. So I commented the line bellow in `php.ini`

    zend_extension = "path/to/php_xdebug-xxx.dll

But I don't think it is recommended to comment out this line..

**Comment by GrahamCampbell** [comment]
No bug. Just increase your max nesting level. We need a call stack greater than 100.
