### ISSUE TITLE
Errors no longer logging

### ISSUE THREAD

**Issue by huludini** [laravel/framework#12192]
Just last night the errors were being logged and now today neither on my local machine or a remote host is logging any errors into the `laravel.log` file. I have an app using `5.1` and an app using `5.2` and it's not logging on either of them anywhere. I also tried to erase the files, but laravel still won't create them again.

I did a fresh install of `5.2` and cleared the routes file and still no log file.

**Comment by GrahamCampbell** [comment]
I can't replicate. Please ask on the forums.
