### ISSUE TITLE
Problem when form input is a URL

### ISSUE THREAD

**Issue by miladrahimi** [laravel/framework#12191]
Actually when users enter a URL in form input and click submit, it acts like a "empty" "get" request not post request while form method is post, and the weird part is the will be no errors, nothing will be shown in the page.

I found a question in a forum which is not solved yet but it's like my problem:
http://laravel.io/forum/01-07-2016-l51-form-input-breaks-form

Thanks a lot
#Method #Form #Input

**Comment by bishopm** [comment]
I have this issue too (the forum post referred to above was mine). I've stripped the view right down to a single field to make sure it wasn't something else, but the problem persists:

When a valid url is submitted by the form, the form uses the get method, but submitting a url that is missing the http:// portion (or even just a colon or slash) has it using post as intended.

**Comment by JayBizzle** [comment]
Some sample code would be helpful

**Comment by GrahamCampbell** [comment]
Please discuss on the forums, then if you have an isolated case that you're sure is a bug, please feel free to post a new issue. Otherwise, we can't keep track of everything.
