### ISSUE TITLE
Mandrill emails fail silently if global from/name not set

### ISSUE THREAD

**Issue by flound1129** [laravel/framework#12190]
Looks like if you don't set 'address' and 'name' in config/mail.php,  e-mail messages that don't specifically set these variables will not be sent properly but also will not return an error to the user.

Seems like Mandrill is accepting the messages which is why Laravel thinks they're successful, but I'm wondering if anything can be done on the Laravel side to help with this.

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell.

**Comment by timgws** [comment]
ping @GrahamCampbell, @taylorotwell

Some servers will still be able to send emails without a from address being provided (sendmail default settings come to mind here).

The `from` address is set inside [`Illuminate\Mail\Mailer`](https://github.com/laravel/framework/blob/7f62d81acb2001faafb21a32544464ebfc92476c/src/Illuminate/Mail/Mailer.php#L403-L422), and it never gets sent to [`Illuminate\Mail\Transport\MandrillTransport`](https://github.com/laravel/framework/blob/7f62d81acb2001faafb21a32544464ebfc92476c/src/Illuminate/Mail/Transport/MandrillTransport.php#L36-L58).

That being said, we can run `getFrom()` on `Swift_Message` and see if it has been set.

Do you think it would be a bad idea for us to throw an Exception if the `from` address is not filled in?

**Comment by themsaid** [comment]
In 5.3 `from` is filled with dummy values by default.
