### ISSUE TITLE
Fails to cast timestamp when $dateFormat is set

### ISSUE THREAD

**Issue by neomerx** [laravel/framework#12203]
When `$dateFormat` property is set in a model (e.g. to ISO8601) and `$casts` property has timestamp
```php
    /**@inheritdoc */
    protected $dateFormat = Carbon::ISO8601;

    /**@inheritdoc */
    protected $casts = [
        'created_at' => 'date',
    ];
```
Laravel fails on reading this attribute.

Internally Laravel got a string from database such as '2016-02-07 22:03:19' and from stack `getAttributeValue` -> `castAttribute` -> `asDateTime` it goes to `Carbon::createFromFormat($this->getDateFormat(), $value)` where fails on invalid data.

The problem IMHO is that Laravel tries to use same format for input data (from database) and for output (in format requested by user).

**Comment by neomerx** [comment]
Sorry, another IMHO

function `fromDateTime` accepts not only `DateTime` or `int` but `string` as well as it is called from `setAttribute` as well. In fact it translates from user <-> model format to model <-> database one.

```php

    /**
     * Convert a DateTime to a storable string.
     *
     * @param  \DateTime|int  $value
     * @return string
     */
    public function fromDateTime($value)
    {
        ...
    }
```

**Comment by neomerx** [comment]
I've found a workaround. It doesn't support auto convert to JSON but solves the problems
- data can be read (as Carbon) and written (Carbon or ISO8601 string) to model
- model can read dates from/write to database in format appropriate for database
```php
class MyModel extends Model
{
    ...
    /**
     * @inheritdoc
     */
    public function setAttribute($key, $value)
    {
        if (is_string($value) && (in_array($key, $this->getDates()) || $this->isDateCastable($key))) {
            $value = Carbon::createFromFormat(Carbon::ISO8601, $value);
        }

        return parent::setAttribute($key, $value);
    }
}
```

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell for advice.

**Comment by dschniepp** [comment]
@neomerx thank you for the workaround, did you stick to this solution?

**Comment by neomerx** [comment]
@dschniepp I was using it without changes. However I've been working mostly on non-Laravel projects recently so you'd better to check it on the latest version on your own.
