### ISSUE TITLE
SSL Everywhere

### ISSUE THREAD

**Issue by steverobbins** [laravel/framework#12204]
I'm trying to set my application up to use SSL everywhere.

Is there an easy way to have `url('foo')` return the secure version, always?  I realize that I can set `true` as the 3rd argument to do this, but that's a lot of find/replacing to do.

I'm also curious as to how it would work when developing locally.  Ideally it would be something in `.env` that I could turn on/set the base url.  That way locally it will use `HTTP`, but in production I can set it to use `HTTPS`.

I've tried changing the URL in `config/app.php` but it didn't help.  How can I address this?

**Comment by GrahamCampbell** [comment]
If you have trusted proxies setup correctly, Laravel will already route everything to SSL. No need to mess about with specific code to force it.

**Comment by steverobbins** [comment]
What are trusted proxies and how do I set them up correctly?

**Comment by GrahamCampbell** [comment]
http://bfy.tw/494k

**Comment by steverobbins** [comment]
@GrahamCampbell I've installed and configured trusted proxies but I am getting the same result.  `url('foo')` will still give an HTTP url instead of HTTPS.

Looking at the [plugin](https://github.com/fideloper/TrustedProxy) I don't see any reason why installing it would cause SSL everywhere behavior.  It may fix getting the client IP, but how does that tell Laravel to use only secure links?
