### ISSUE TITLE
see testing methods take HTML into consideration

### ISSUE THREAD

**Issue by sileence** [laravel/framework#12206]
With the current state of the testing content, you can do stuff like:

`$this->see('<image src="my-image.jpg>')` and this works. But sadly if you want to test this:

`$this->see('Laravel PHP Framework')` against this HTML:

`<p>Laravel <strong>PHP</strong> Framework</p>`

The test will fail because of the `<strong>` tag in the middle of the text.

I've found this annoying when trying to assert text with HTML tags. 

At this point, it is hard to change this behaviour because it could break a lot of tests (i.e. issue #12075) of current projects.

So, I'm thinking about adding some extra methods like `seeText` or `seeTextInElement` to test against plain text instead of HTML. Or maybe changing the behaviour of see and seeInElement to test vs plain text and then adding `seeInSource` like Codeception does?

**Comment by GrahamCampbell** [comment]
Thanks, but we don't process proposal issues on GitHub. Feel free to ask on the forums and/or send a partial/full PR.
