### ISSUE TITLE
DB::select with bindings always return empty array

### ISSUE THREAD

**Issue by gordin-mitya** [laravel/framework#12217]
$q = "as";
$res = DB::select(DB::raw("SELECT * FROM `groups` WHERE LOWER(`name`) LIKE LOWER('?%')"), [$q]);
return []
but
$q = "as";
$res = DB::select(DB::raw("SELECT * FROM `groups` WHERE LOWER(`name`) LIKE LOWER('$q%')"));
return [{"id":477,"name":"asd"}]

**Comment by bobbybouwmann** [comment]
The select method doesn't accept a second parameter for bindings. If you want to do this, you need to use the `selectRaw` method
```
DB::selectRaw("SELECT * FROM groups WHERE LOWER(name) LIKE LOWER('?%')", [$q]);
```

**Comment by gordin-mitya** [comment]
MySqlConnection does not have a method 'selectRaw'
Group::selectRaw("SELECT * FROM `groups` WHERE LOWER(`name`) LIKE LOWER('?%')", [$q])->get() generate wrong sql query: select SELECT * FROM `groups` WHERE LOWER(`name`) LIKE LOWER('э%') from `groups` (adds to end 'from groups')
Group - my class extends Model
