### ISSUE TITLE
previous url in session and logins

### ISSUE THREAD

**Issue by leemason** [laravel/framework#12214]
not really a bug but wanted to figure out how to get round it.

i have:

/login

/logout

if a logged in user visits logout, it logs them out, then redirects them to the login page with a logged out message (pretty standard).

now IF a user then logs back in right away the /login route logs them in and does a:

```
return redirect()->intended('/dashboard');
```

problem is there "intended" url seems to be picked up as /logout so it enters a loop and when you login it then redirects you to /logout.

sometimes i can see in the session ```url.intended``` but sometimes its not there. is this the only session variable i need to forget to prevent this from happening on the logout action?

**Comment by GrahamCampbell** [comment]
Please ask questions on the forums.

**Comment by Quixotical** [comment]
Just saying, if OP figured this out, or found an article, or something.. it woulda been cool if he posted a link to it here :( was so excited to finally find someone with my issue, lol
