### ISSUE TITLE
Laravel 5 route groups `prefix and `as` and resource controllers

### ISSUE THREAD

**Issue by charlieprynn** [laravel/framework#12216]
I'm using route groups to try and stop duplication within my Routes file.

I have one main group, `frontend`. This has the namespace `Frontend` and as `frontend`.

Nested within that group, is another group. This group has the `prefix` `account` which appends `/account/` to each route. It also has `as` `account.`.

The routes inside the nested group, I'd expect to be:

1. frontend.account.home
2. frontend.account.order.show
3. frontend.account.order.index

Instead I get:

1. frontend.account.home
2. frontend.account.account.order.index
3. frontend.account.account.order.show

Example:
```
Route::group(['as' => 'frontend.', 'namespace' => 'Frontend'], function () {
        Route::group(['prefix' => 'account', 'as' => 'account.', 'namespace' => 'Account'], function () {
            Route::get('home', [
                'as'   => 'home',
                'uses' => 'Home\Controller@get'
            ]);
    
            Route::resource('order', 'Order\Controller']]);
        });
    });
```

**Comment by GrahamCampbell** [comment]
This isn't a bug. Thanks though. Please see the large quantity of similar issues where people wanted this behaviour over the other, and vice versa.
