### ISSUE TITLE
[5.2] Cookies not persisting.

### ISSUE THREAD

**Issue by nicgutierrez** [laravel/framework#12212]
I'm not sure if this is a bug or it's just me that I don't understand how this should work?

I have a very simple controller method as follows:

    public function write(Request $request)
    {
        Cookie::make('secret.submitted', true, 60);
        dd(Cookie::get('secret.submitted'));
    }

This specific route is running within the "web" middleware.

This always returns null, and if I inspect the result of Cookie::make() I can see that the cookie is always expired. No matter what I use as the third value.

**Comment by bobbybouwmann** [comment]
You need to pass the cookie to the request
```
// When returning a view
return view('welcome')->withCookie(cookie('secret.submitted', true, 60));

// When returning a redirect
return redirect()->route('some.route')->withCookie(cookie('secret.submitted', true, 60));
```

**Comment by nicgutierrez** [comment]
hey @bobbybouwmann.

Thanks for getting back, I guess it's me using this on the wrong way.

Here's what I'm trying to achieve.

1. I submit some data via AJAX, and I respond with some json and also create the cookie
2. On a different route I need to check if that cookie exists.

So, here's my "store" method, the one I'm calling via AJAX:
 
    public function store(Request $request)
    {
        $result = $this->repo->create($request->all());
        $secret = $result['secret'];
        $cookie = cookie('secret.submitted', $secret->code, Config::get('is.minutes_after_new_secret'));

        return response()->json($result)->withCookie($cookie);
    }

And here's my different method where I need to retrieve the value:

    public function write(Request $request)
    {
        return view( 'secrets.write', [
            'submitted' => $request->cookie('secret.submitted')
        ] );
    }

I'm not entirely sure what I'm doing wrong.

**Comment by nicgutierrez** [comment]
So... I finally found the issue here.

The name of my cookie is "secret.submitted" but for some reasons, laravel doesn't like that and it automatically convert this to "secret_submitted"....

Doing Cookie::get('secret_submitted') works just fine...

Is this .. a bug?

**Comment by bobbybouwmann** [comment]
@nicgutierrez I think this is intended. Laravel uses a conversion for almost everything ;)

**Comment by hassankhan** [comment]
Not so sure, @taylorotwell didn't seem to say anything about it on the PR I opened

**Comment by nicgutierrez** [comment]
hey @bobbybouwmann , if this is intended functionality, I believe it should probably be documented. 
What do you think? Shall we include this in the cookies documentation?
