### ISSUE TITLE
DB query with bindings always return empty array

### ISSUE THREAD

**Issue by gordin-mitya** [laravel/framework#12218]
$q = "as";
$res = DB::select(DB::raw("SELECT * FROM groups WHERE LOWER(name) LIKE LOWER('?%')"), [$q]);
return []
but
$q = "as";
$res = DB::select(DB::raw("SELECT * FROM groups WHERE LOWER(name) LIKE LOWER('$q%')"));
return [{"id":477,"name":"asd"}]

DB::selectRaw("SELECT * FROM groups WHERE LOWER(name) LIKE LOWER('?%')", [$q]);
MySqlConnection does not have a method 'selectRaw'

Group::selectRaw("SELECT * FROM groups WHERE LOWER(name) LIKE LOWER('?%')", [$q])->get() generate wrong sql query: select SELECT * FROM groups WHERE LOWER(name) LIKE LOWER('э%') from groups 
(adds to end 'from groups')
Group - my class extends Model

$q = "as";
$res = Group::whereRaw("LOWER(name) LIKE LOWER('?%')", [$q])->get(); return empty array
but
$q = "as";
$res = Group::whereRaw("LOWER(name) LIKE LOWER('$q%')")->get(); return [{"id":477,"name":"asd"}]

**Comment by GrahamCampbell** [comment]
Please ask questions on the forums.
