### ISSUE TITLE
Bug:Deleting an active user creates Maximum Function nesting level error in Grammer.php

### ISSUE THREAD

**Issue by haseebeqx** [laravel/framework#12247]
This is an issue with Auth
When a user is active deleting his account from database redirects to login page on next request. but in login page it shows the error of

> FatalErrorException in Grammar.php line 151: Maximum function nesting level of '100' reached, aborting!

Here are the steps to reproduce this issue:

1. create a blank project
2. using artisan console install auth
3. register a user using registration screen
4. goto database and delete the user
5. reload the page

**Comment by GrahamCampbell** [comment]
Increase your nesting to a number larger than 100, say 512.

**Comment by haseebeqx** [comment]
thanks for the fast reply. this is an issue with how framework handles session
but this issue can be fixed in a better way. 
can i try a PR?
