### ISSUE TITLE
Using two columns in where - ORM

### ISSUE THREAD

**Issue by ventaquil** [laravel/framework#12248]
I have two columns in my table: `max` and `current`. I want to build simple scope

```php
    public function scopeNotMax($query)
    {
        return $query->where('max', '>', 'current');
    }
```

But Laravel gives me that query:

```sql
    SELECT * FROM table WHERE `max` > 'current'
```

I don't want this result and I know that I can use in this place `whereRaw()` or `DB::raw()`. But I can't find another way to say "hey, this is column, not string!'. Can I do it? Or I must use raws? I want to avoid it.

**Comment by GrahamCampbell** [comment]
Please ask questions on the forums.
