### ISSUE TITLE
Let routes be sorted so a route parameter doesn't match before a defined segment

### ISSUE THREAD

**Issue by MaxHumme** [laravel/framework#12253]
At the moment routes are being processed in the order they are added. That means that if we add `/{parameter}` before `/segment` in our routes file like so:

```php
Route::get('/{parameter}', ['uses' => 'SomeController@showSomething']);
Route::get('/segment', ['uses' => 'SomeController@showSomethingElse']);
```
`/segment` will never match.

This is usually not a problem, we just add `/segment` before `/{parameter}` in our routes file. It can become a problem however when we're working with different packages that all have their own route files. You could constrain some parameters with regular expressions, but that only goes so far and in my opinion should only be used to discern between parameters and not between a parameter and a explicitly defined segment.

I would say that an explicitly defined segment should logically always match before a required parameter, and a required parameter should always match before an optional parameter.

For example:
`/profiles/search` should always match before `/profiles/{username}`.
No matter in what order they were added to RouteCollection.

We could let RouteCollection sort its routes when a route is being added, or let it sort the routes once when the app is done booting.

**Comment by crazycodr** [comment]
Your issue makes sense and obviously this would have to be done on booting complete.

**Comment by delatbabel** [comment]
This was already raised as #4121 -- Taylor closed it and suggested using App::before() which has now gone away.

There was a route priority implementation for Laravel 4 by Sleeping Owl, here: https://github.com/sleeping-owl/route-priority however it hasn't been maintained or updated for Laravel 5.

Obviously route priority (explicit or implicit) is an issue that needs to be included in core.  Currently in the latest 5.1 route sorting is kind of b0rked.  If I add routes like this, in this order:

```
Route::group(['prefix' => 'api/v1'], function () {
    // ping START
    Route::resource('ping', 'Api\V1\PingController', ['only' => ['index']]);
    // ping END
});

Route::resource('ping', 'Api\V1\PingController', ['only' => ['index']]);

Route::any('{slug}', [
    'as'    => 'vpage.make',
    'uses'  => '\Delatbabel\ViewPages\Http\Controllers\VpageController@make'
])->where('slug', '.*');
```

... then the {slug} route masks the /api/v1/ping route but not the /ping route.  This makes no sense.
