### ISSUE TITLE
How to get original value for the accessor value ?

### ISSUE THREAD

**Issue by m-gamal** [laravel/framework#12252]
When I used accessor with specific column through whole system, but I need the "original" value for this column in some places in my application ,  how to do that ?

**Comment by GrahamCampbell** [comment]
Please ask questions on the forums.

**Comment by m-gamal** [comment]
I did, but they told me to use getOriginal() and it doesn't works !

**Comment by gchaumont** [comment]
getOriginal() doesn't work on eloquent models that haven't been saved.
One would expect that getOriginal() simply bypasses the getAttributeValue() and return the current attribute's value but it actually points to the model's "original" array.
which means there is no way of accessing original values on a model that hasn't been saved yet.
Feature or Bug?

**Comment by abdalasif** [comment]
> 
> 
> getOriginal() doesn't work on eloquent models that haven't been saved.
> One would expect that getOriginal() simply bypasses the getAttributeValue() and return the current attribute's value but it actually points to the model's "original" array.
> which means there is no way of accessing original values on a model that hasn't been saved yet.
> Feature or Bug?

seems like a bug to me. even calling the getOriginal on saved model doesn't returns the original value;
`
public function edit($request)
    {
        try {
            dd(static::find($this->id)->getOriginal('image'));
            $this->first_name = $request->first_name;
            $this->last_name = $request->last_name;
            $this->phone_number = $request->phone_number;
            $this->whatsapp_number = $request->whatsapp_number;
            $this->address = $request->address;
            $this->country_id = $request->country;
            $this->state_id = $request->state;
            $this->city_id = $request->city;
            $this->other_city = $request->other_city;
            $this->zip_code = $request->zip_code;
            $this->short_bio = $request->short_bio;
            
            if ($request->hasFile('file')) {
                $image = saveFile($request->file, 'images/users')['path'];
                
                if($this->getDefaultImage() != $this->image && $this->image != null) {
                    deleteFile($this->getOriginal('image'));
                }

                $this->image = $image;
            }
            
            return $this->save();
        } catch (\Exception $ex) {
            ExceptionNotify::dispatch($this, $ex, auth()->user());
            return null;
        }
    }

public function getImageAttribute($value)
    {
        return $value ? asset($value) : static::DEFAULT_USER_IMAGE;
    }
`
