### ISSUE TITLE
Illuminate\Validation\PresenceVerifierInterface needs implementation of setConnection() method?

### ISSUE THREAD

**Issue by felipeweb11** [laravel/framework#12250]
I needed my own implementation of the Illuminate\Validation\PresenceVerifierInterface, but when the framework was executed, an exception was launched.

In my controller I did something like:

`$myValidatorInstance->setPresenceVerifier($myVerifierImplementation);`

Then I noticed that the PresenceVerifierInterface does not contain the method setConnection(), but this method is called at the instance verifier in Illuminate\Validation\Validator.php in validateUnique () method, which results in an exception.

I believe that the setConnection () method should not be necessarily implemented, since I do not need it, correct me if I'm mistaken.

**Comment by GrahamCampbell** [comment]
Sorry, but we do not include setters and getters on our interfaces.

**Comment by felipeweb11** [comment]
Yes, this method should not be in the interface, but the problem is that it is called as quoted above.

what happens is that so I am obliged to implement a method that does not need, in this case setConnection(), to solve my problem, had to leave this method unimplemented:

    class MyPresenceVerifier implements Illuminate\Validation\PresenceVerifierInterface  {

        public function getCount($collection, $column, $value, $excludeId = null, $idColumn = null, array $extra = []) 
        {
            //Do something here
        }

        public function getMultiCount($collection, $column, array $values, array $extra = [])
        {
            //Do something here
        }

        public function setConnection()
        {
            //That's the problem, without that an exception is thrown
        }

    }

**Comment by drbyte** [comment]
Agreed. 
The method is not in the interface, but the implementation expects it. 

Implementation:
https://github.com/laravel/framework/blob/5.3/src/Illuminate/Validation/Validator.php#L1393
https://github.com/laravel/framework/blob/5.3/src/Illuminate/Validation/Validator.php#L1486

Interface: 
https://github.com/laravel/framework/blob/5.3/src/Illuminate/Validation/PresenceVerifierInterface.php
