### ISSUE TITLE
[5.2] MassAssignmentException shouldn't occur when param. is not $request->all()

### ISSUE THREAD

**Issue by let-aurn** [laravel/framework#12266]
`MassAssignmentException` shouldn't occur when param. is not result of `$request->all()`.

I mean, this shouldn't fail even w/ the `$fillable` field:

    User::where('email', $request->input('email'))
        ->first()
        ->update(['password' => bcrypt($request->input('password'))]);

**Comment by GrahamCampbell** [comment]
This looks correct to me. Feel free to ask on the forums for advice.

**Comment by let-aurn** [comment]
This code throws MassAssignmentException. It doesn't make sense since I don't expect any maliscious field here.

**Comment by let-aurn** [comment]
In the all() method of $request, we can add a field called "__is_from_request" to the returned array to check then later if the array passed to create() or update() of the model are from request->all(). If this field is missing, we could  MassAssignement won't be thrown.
