### ISSUE TITLE
HHVM: QueryException when using min/max aggregate function on timestamp column

### ISSUE THREAD

**Issue by m-lotze-7o7** [laravel/framework#12268]
When using the following statement on a server with HHVM, a QueryException is thrown. The statement works as expected on the same server when using PHP-FPM.
`DB::table('table')->min('created_at')`
```
QueryException in Connection.php line 653: 

Object of class Illuminate\Database\MySqlConnection 
could not be converted to string (SQL: select min(`created_at`) as aggregate from `table`)
```
To rule out that this is an HHVM issue i created the following php file:
```php
<?php

$db = new PDO('mysql:host=localhost;dbname=database;charset=utf8', 'user', 'password');

$stmt = $db->query('select min(`updated_at`) as aggregate from `table`');

$results = $stmt->fetchAll(PDO::FETCH_ASSOC);

var_dump($results);
```
this results in:
```
array(1) { [0]=> array(1) { ["aggregate"]=> string(19) "2016-01-29 15:08:38" } } 
```
this seems to happen only for `timestamp` columns. when using an integer or char column it works as expected. a workaround is to use DB::raw to cast the column as CHAR:
```
DB::table('table')->min(DB::raw('CAST(created_at AS CHAR)'))
```
this returns the date and no exception occurs.

**Comment by GrahamCampbell** [comment]
Please report this issue to HHVM.
