### ISSUE TITLE
Validation array doesn't work as the docs i guess.

### ISSUE THREAD

**Issue by socieboy** [laravel/framework#12273]
I was trying to validate an array of input like the docs said.
```
    $this->validate($request, [
        'permissions.*' => 'required',
    ]);
```
I make it work until i change to
```
    $this->validate($request, [
        'permissions[]' => 'required',
    ]);
```
This something new in Laravel that you haven't update in the docs? Or it could work with both ways.
Or why my application works with this sintaxis! ?

**Comment by themsaid** [comment]
```
    $this->validate($request, [
        'permissions[]' => 'required',
    ]);
```

This won't work, because the field name would be `permissions` not `permissions[]`.

**Comment by socieboy** [comment]
So do I have to define my fields like that:
```
<input type="checkbox" name="permissions[]" value="1">
<input type="checkbox" name="permissions[]" value="1">
<input type="checkbox" name="permissions[]" value="1">
```
right?

**Comment by themsaid** [comment]
Yes, and then you validate them:

```
    $this->validate($request, [
        'permissions.*' => 'required',
    ]);
```

**Comment by socieboy** [comment]
I did that and still get the validations errors permissions is required... but if i change the validation like:
```
$this->validate($request, [
        'permissions[]' => 'required',
    ])
```
it works fine! so im confused!

**Comment by socieboy** [comment]
well.. im not getting a error it just pass the validation.

**Comment by socieboy** [comment]
if I do that you said, the validation doesn't fail if i don't check anyone!
