### ISSUE TITLE
Redis Cache Tags Still Not Working  5.2.14

### ISSUE THREAD

**Issue by jrking4** [laravel/framework#12272]
When running the following code:
` \Cache::tags( 'people', 'artists')->remember( 'John', 120, function () { return 'test'; });
       \Cache::tags( 'artists' )->flush();
       dd( \Cache::tags( 'people')->get('John'));`

When multiple tags are assigned to a record, shouldn't flushing the cache of one tag flush the record for both tags assigned?
I would expect a null return from the above code. However I still get 'test'. #9967

**Comment by GrahamCampbell** [comment]
This is the correct behaviour. You need to flush both tags in the same order.

**Comment by jrking4** [comment]
Has this behavior changed since 4.2? I don't see the use case for multiple
tags if you have to specify both every time you need to flush the keys for
a tag? Can you provide some clarification?

**Comment by GrahamCampbell** [comment]
Hmmmm. Ping @taylorotwell. This does look a bit odd.

**Comment by jrking4** [comment]
I just confirmed on a 4.2 installation, the code works as I expected and returns NULL.  It seems multiple cache tags in 5.2 are either not working or the behavior has changed.

**Comment by jrking4** [comment]
Hey @GrahamCampbell any update on this?

**Comment by GrahamCampbell** [comment]
Not sure what you want me to do? I'd happily review a PR to fix it.

**Comment by jrking4** [comment]
I just sent a pull request. It seems the has and get methods were removed from TaggedCache class. Adding those methods back in fixes the issue i was experiencing and allows for correct key from taggedItemKey method to be called.

**Comment by ctf0** [comment]
i believe the multiple tags were meant to be used as
```php
Cache::tags(['posts', 'prem'])->put(//somthing);
Cache::tags(['posts', 'gold'])->put(//somthing);
```
so u can either flush a specific tag like `prem` or `gold` or clear the whole thing by flushing `posts` which then will clear the child tags, maybe in order to clear the confusion we would instead use something like
```php
Cache::tags(['posts'])->sub(['prem'])->put(//somthing);
Cache::tags(['posts'])->sub(['gold'])->put(//somthing);
```
and for the flushing it work exactly the same ,except when removeing the parent tag, all the sub_tags are also cleared and u get `null`.

https://github.com/laravel/framework/issues/13100

**Comment by ctf0** [comment]
https://github.com/laravel/framework/issues/13100

**Comment by GrahamCampbell** [comment]
We're open to PRs. Going to close this for now since we don't process proposals on the issue tracker. Thank you though!
