### ISSUE TITLE
route::group prefix append to name

### ISSUE THREAD

**Issue by mohamedsharaf** [laravel/framework#12271]
```
Route::group([
'prefix' => 'adminPrefix', 
'as' => 'adminRoute'
], function () {
    Route::resource('user', 'UserController');
});
```

php artisan route:list
 
```
adminRouteadminPrefix.user.index
adminRouteadminPrefix.user.store
adminRouteadminPrefix.user.create
adminRouteadminPrefix.user.destroy
adminRouteadminPrefix.user.show
adminRouteadminPrefix.user.update
adminRouteadminPrefix.user.edit

```

excpected route name sould be without adminPrefix

adminRoute.user.index

**Comment by GrahamCampbell** [comment]
I don't think this is a bug?

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell for confirmation please.

**Comment by mohamedsharaf** [comment]
@taylorotwell 
i tested in both 5.1 and 5.2

**Comment by mohamedsharaf** [comment]
@GrahamCampbell  can u help me how i do it i dont need the prefix to be appended to route name

what i am doing wrong ?

**Comment by EliasZ** [comment]
@GrahamCampbell @mohamedsharaf prefix/as is horribly inconsistent and does not show expected behavior with resources inside groups. Sadly the framework maintainers think that fixing it is BC-breaking because people are used to the buggy behavior.

Please see #11679 and #12072 and [this explanation](https://github.com/laravel/framework/pull/12072#issuecomment-177548880).

**Comment by mohamedsharaf** [comment]
@EliasZ  
thanks man u saved me i was working on push as fix :)

for other user may come here just pass names to the route:resource it will ignore this problem

```
Route::resource($name, $controller, [
            'names' =>
                [
                    'index' => $name . '.index',
                    'create' => $name . '.create',
                    'store' => $name . '.store',
                    'show' => $name . '.show',
                    'edit' => $name . '.edit',
                    'update' => $name . '.update',
                    'destroy' => $name . '.destroy',
                ]]
    );

```
namespace Illuminate\Routing\ResourceRegistrar;

```
$group = trim(str_replace('/', '.', $this->router->getLastGroupPrefix()), '.');
        $alias = $this->router->getLastGroupAlias();
if(!empty($alias )){
// we should here check to see if alias name has been set then return 
}
```

namespace Illuminate\Routing\Router;
i add this code 
```
 public function getLastGroupAlias()
    {
        if (! empty($this->groupStack)) {
            $last = end($this->groupStack);
            return isset($last['as']) ? $last['as'] : '';
        }

        return '';
    }
```

**Comment by mohamedsharaf** [comment]
@EliasZ do you  think that this should be cleared in the Documentation it wasted me too time 

at least put dont use alias and prefix same time or use with names

**Comment by EliasZ** [comment]
@mohamedsharaf This should definitely be in the documentation. @taylorotwell said he would do that circa a month ago but he's a busy man. You could always try and PR.

See laravel/docs#2041

**Comment by mohamedsharaf** [comment]
@EliasZ 

i think it can be fixed without BC-breaking 

just if user defined 'as' in options consider it
if not consider prefix 

sorry for english 
mean if both defined ['as','prefix'] then go with 'as' otherwise go with 'prefix' as it

review the above reply code 
https://github.com/laravel/framework/issues/12271#issuecomment-183534079
