### ISSUE TITLE
Error with file uploading in Laravel 5.2.15

### ISSUE THREAD

**Issue by vlodkow** [laravel/framework#12275]
Just update to Laravel v5.2.15 and when I try to upload file, receive this error:

FatalErrorException in RedirectResponse.php line 11: Cannot use Symfony\Component\HttpFoundation\File\UploadedFile as UploadedFile because the name is already in use

When return back to Laravel v5.2.14 all work fine.

**Comment by GrahamCampbell** [comment]
Can't replicate.

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/blob/v5.2.15/src/Illuminate/Http/RedirectResponse.php

**Comment by GrahamCampbell** [comment]
Could you elaborate please?

**Comment by angelside** [comment]
I have this error too, on 5.2.15. I use a Trait on controller for upload image and I not call any UploadedFile instance myself. I use `$request->file('image')`

If I use `return redirect()->route('photo.index')` get error, if use `return redirect()->back()` no error.

```
FatalErrorException in RedirectResponse.php line 11:
Cannot use Symfony\Component\HttpFoundation\File\UploadedFile as UploadedFile
because the name is already in use
``

**Comment by thecrypticace** [comment]
This is because there is now an UploadedFile class in the Illuminate\Http namespace. I believe this error was removed on PHP 7. The use of UploadedFile should be aliased with a different name.

**Comment by angelside** [comment]
OK, I am not expert but if I delete or change[ RedirectResponse.php line 11](https://github.com/laravel/framework/blob/v5.2.15/src/Illuminate/Http/RedirectResponse.php#L11), its work without this error. I can't fix this error simple change my app or controller file.

https://github.com/laravel/framework/blob/v5.2.15/src/Illuminate/Http/RedirectResponse.php#L1

```
//use Symfony\Component\HttpFoundation\File\UploadedFile;
use Illuminate\Http\UploadedFile;
```

**Comment by GrahamCampbell** [comment]
That change would be incorrect.

**Comment by GrahamCampbell** [comment]
Fixed.

**Comment by angelside** [comment]
Error is change on 5.2.16

```
FatalThrowableError in UploadedFile.php line 48:
Type error: Argument 1 passed to Illuminate\Http\UploadedFile::createFromBase()
must be an instance of Symfony\Component\HttpFoundation\File\UploadedFile, null given,
called in ..\vendor\laravel\framework\src\Illuminate\Http\Request.php on line 419
```

**Comment by taylorotwell** [comment]
Can you try my latest commit on dev stability and see if that fixes your problem?

**Comment by angelside** [comment]
I've tried, this change fix my empty image upload error.

```
src/Illuminate/Http/Request.php

-            if (is_array($file) && empty(array_filter($file))) {
+            if (is_null($file) || (is_array($file) && empty(array_filter($file)))) {
```
