### ISSUE TITLE
Empty multiple file upload input throws error

### ISSUE THREAD

**Issue by deweller** [laravel/framework#12288]
Given this form:
```html
<form action="/" method="POST" enctype="multipart/form-data">
    <input type="file" name="form_files[]" multiple />
    <button type="submit">Save File</button>
</form>
```

and this route handler:

```php
Route::post('/', function () {
    $data = Input::all();
    // do something with $data...
});
```

the following error is thrown:

`Argument 1 passed to Illuminate\Http\UploadedFile::createFromBase() must be an instance of Symfony\Component\HttpFoundation\File\UploadedFile, null given`

**Comment by GrahamCampbell** [comment]
Thanks for reporting.

**Comment by deweller** [comment]
I submitted another pull request based on the 5.2 branch.  Can you re-open this issue or should I submit a separate issue?

**Comment by GrahamCampbell** [comment]
GitHub doesn't support retargeting PRs.
