### ISSUE TITLE
local.ERROR: exception 'ReflectionException' with message 'Class hash does not exist'

### ISSUE THREAD

**Issue by SylvainMarty** [laravel/framework#12284]
Hi everyone,
I'm expecting an issue with my Laravel 5.1 Project. I haven't worked on my project for 3 weeks and, when I'm come back, nothing work. By nothing, I mean no routes (statics and dynamics routes)... I precise that the project worked fine 3 weeks ago. Nom, my browser display just the 500 error white scree of death, not the laravel 500 error.

First of all, I've tried to update composer but it was not successful...
I have checked the logs files but I dont know what's important. The error returned is **local.ERROR: exception 'ReflectionException' with message 'Class hash does not exist'** but I dont know what I can do to correct the stuff...

I haven't found an issue like this on Google.

Can you help me please ?
Thanks in advance !
I'm stay here if you need more informations.

**Here the last full log of this error :**
<pre>[2016-02-14 10:45:33] local.ERROR: exception 'ReflectionException' with message 'Class hash does not exist' in /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:741
Stack trace:
#0 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(741): ReflectionClass->__construct('hash')
#1 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('hash', Array)
#2 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('hash', Array)
#3 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(1163): Illuminate\Foundation\Application->make('hash')
#4 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(105): Illuminate\Container\Container->offsetGet('hash')
#5 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(91): Illuminate\Auth\AuthManager->createEloquentProvider()
#6 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/Support/Manager.php(87): Illuminate\Auth\AuthManager->createEloquentDriver()
#7 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(18): Illuminate\Support\Manager->createDriver('eloquent')
#8 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/Support/Manager.php(63): Illuminate\Auth\AuthManager->createDriver('eloquent')
#9 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/Support/Manager.php(137): Illuminate\Support\Manager->driver()
#10 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(213): Illuminate\Support\Manager->__call('user', Array)
#11 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(213): Illuminate\Auth\AuthManager->user()
#12 /home/gestboxfkl/www/laravel/storage/framework/views/e02f9a7c775c7b21a257a209b6edd47b(216): Illuminate\Support\Facades\Facade::__callStatic('user', Array)
#13 /home/gestboxfkl/www/laravel/storage/framework/views/e02f9a7c775c7b21a257a209b6edd47b(216): Illuminate\Support\Facades\Auth::user()
#14 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(42): include('/home/gestboxfk...')
#15 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(58): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/gestboxfk...', Array)
#16 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/View/View.php(142): Illuminate\View\Engines\CompilerEngine->get('/home/gestboxfk...', Array)
#17 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/View/View.php(113): Illuminate\View\View->getContents()
#18 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/View/View.php(82): Illuminate\View\View->renderContents()
#19 /home/gestboxfkl/www/laravel/storage/framework/views/125e70a5660e459e34f786f36f2f0edc(5): Illuminate\View\View->render()
#20 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(42): include('/home/gestboxfk...')
#21 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(58): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/gestboxfk...', Array)
#22 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/View/View.php(142): Illuminate\View\Engines\CompilerEngine->get('/home/gestboxfk...', Array)
#23 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/View/View.php(113): Illuminate\View\View->getContents()
#24 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/View/View.php(82): Illuminate\View\View->renderContents()
#25 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/Http/Response.php(51): Illuminate\View\View->render()
#26 /home/gestboxfkl/www/laravel/vendor/symfony/http-foundation/Response.php(198): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#27 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(57): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View), 500, Array)
#28 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(71): Illuminate\Routing\ResponseFactory->make(Object(Illuminate\View\View), 500, Array)
#29 /home/gestboxfkl/www/laravel/app/Exceptions/Handler.php(51): Illuminate\Routing\ResponseFactory->view('errors.500', Array, 500)
#30 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(281): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(ErrorException))
#31 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(91): Illuminate\Foundation\Http\Kernel->renderException(Object(Illuminate\Http\Request), Object(ErrorException))
#32 /home/gestboxfkl/www/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#33 {main}

Next exception 'ErrorException' with message 'Class hash does not exist (View: /home/gestboxfkl/www/laravel/resources/views/templates/navigation.blade.php)' in /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:741
Stack trace:
#0 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ReflectionException), 2)
#1 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(58): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/gestboxfk...', Array)
#2 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/View/View.php(142): Illuminate\View\Engines\CompilerEngine->get('/home/gestboxfk...', Array)
#3 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/View/View.php(113): Illuminate\View\View->getContents()
#4 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/View/View.php(82): Illuminate\View\View->renderContents()
#5 /home/gestboxfkl/www/laravel/storage/framework/views/125e70a5660e459e34f786f36f2f0edc(5): Illuminate\View\View->render()
#6 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(42): include('/home/gestboxfk...')
#7 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(58): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/gestboxfk...', Array)
#8 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/View/View.php(142): Illuminate\View\Engines\CompilerEngine->get('/home/gestboxfk...', Array)
#9 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/View/View.php(113): Illuminate\View\View->getContents()
#10 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/View/View.php(82): Illuminate\View\View->renderContents()
#11 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/Http/Response.php(51): Illuminate\View\View->render()
#12 /home/gestboxfkl/www/laravel/vendor/symfony/http-foundation/Response.php(198): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#13 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(57): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View), 500, Array)
#14 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(71): Illuminate\Routing\ResponseFactory->make(Object(Illuminate\View\View), 500, Array)
#15 /home/gestboxfkl/www/laravel/app/Exceptions/Handler.php(51): Illuminate\Routing\ResponseFactory->view('errors.500', Array, 500)
#16 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(281): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(ErrorException))
#17 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(91): Illuminate\Foundation\Http\Kernel->renderException(Object(Illuminate\Http\Request), Object(ErrorException))
#18 /home/gestboxfkl/www/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#19 {main}

Next exception 'ErrorException' with message 'Class hash does not exist (View: /home/gestboxfkl/www/laravel/resources/views/templates/navigation.blade.php) (View: /home/gestboxfkl/www/laravel/resources/views/templates/navigation.blade.php)' in /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:741
Stack trace:
#0 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(58): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/gestboxfk...', Array)
#2 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/View/View.php(142): Illuminate\View\Engines\CompilerEngine->get('/home/gestboxfk...', Array)
#3 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/View/View.php(113): Illuminate\View\View->getContents()
#4 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/View/View.php(82): Illuminate\View\View->renderContents()
#5 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/Http/Response.php(51): Illuminate\View\View->render()
#6 /home/gestboxfkl/www/laravel/vendor/symfony/http-foundation/Response.php(198): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(57): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View), 500, Array)
#8 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(71): Illuminate\Routing\ResponseFactory->make(Object(Illuminate\View\View), 500, Array)
#9 /home/gestboxfkl/www/laravel/app/Exceptions/Handler.php(51): Illuminate\Routing\ResponseFactory->view('errors.500', Array, 500)
#10 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(281): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(ErrorException))
#11 /home/gestboxfkl/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(91): Illuminate\Foundation\Http\Kernel->renderException(Object(Illuminate\Http\Request), Object(ErrorException))
#12 /home/gestboxfkl/www/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#13 {main}</pre>

**Comment by GrahamCampbell** [comment]
Please ask on the forums.
