### ISSUE TITLE
[5.2] Empty multiple file upload input throws error

### ISSUE THREAD

**Issue by deweller** [laravel/framework#12292]
Given this form:
```html
<form action="/" method="POST" enctype="multipart/form-data">
    <input type="file" name="form_files[]" multiple />
    <button type="submit">Save File</button>
</form>
```

and this route handler:

```php
Route::post('/', function () {
    $data = Input::all();
    // do something with $data...
});
```

the following error is thrown:

`Argument 1 passed to Illuminate\Http\UploadedFile::createFromBase() must be an instance of Symfony\Component\HttpFoundation\File\UploadedFile, null given`

**Comment by GrahamCampbell** [comment]
No need to create a new issue.

**Comment by GrahamCampbell** [comment]
I close them once a PR is present because people have habit of not formatting PRs correctly to close them so we end up with a backlog of old issues.

**Comment by deweller** [comment]
Ahh, got it.  Thanks for the explanation.

**Comment by angelside** [comment]
Error is change on 5.2.16

```
FatalThrowableError in UploadedFile.php line 48:
Type error: Argument 1 passed to Illuminate\Http\UploadedFile::createFromBase()
must be an instance of Symfony\Component\HttpFoundation\File\UploadedFile, null given,
called in ..\vendor\laravel\framework\src\Illuminate\Http\Request.php on line 419
```

**Comment by wayneashleyberry** [comment]
https://github.com/laravel/framework/pull/12293 was closed, so shouldn't this issue still be open?

**Comment by angelside** [comment]
Taylor fix my last error, but I thing it's effect on 5.6.17.

https://github.com/laravel/framework/issues/12275#issuecomment-184413569

**Comment by deweller** [comment]
@GrahamCampbell @taylorotwell 

Since there is no open issue or pull request, just pinging you on this to make sure this is still on the list to get fixed.

I can contribute if you can point me in the right direction on pull request https://github.com/laravel/framework/pull/12293.
