### ISSUE TITLE
Laravel 5.2 + PHP-FPM + NGINX CPU leak

### ISSUE THREAD

**Issue by aginev** [laravel/framework#12291]
Hello guys,

Having a big trouble with CPU leak in Laravel 5.2 fresh install as well as in app in production mode. So the problem is when there are a lot of concurrent requests php-fpm uses 100% of CPUs. 

Tested with Apache Benchmark like so:
ab -n 1000 -c 100 http://l5-fresh.dev/

Server setup:
Host machine: core i7 (4 cores 8 threads) + 8GB RAM
Vagrant + Homestead with PHP v7
2 CPUs
2 Gigs of RAM
Nginx and PHP-FPM default settings 

The main idea of this tests is debugging server failures at documents storage service I've made a month ago which is having same issues when heavy loaded.
The production server (dedicated) setup is:
Nginx v1.8.0
PHP-FPM v5.5.9
CPU 1 with 6 cores and 12 threads
RAM 32GB

Additional settings made there to handle heavy load:
worker_processes 12;
worker_connections 12228;

php artisan optimize
composer dump-autoload --optimize
Nothing changed!

Did someone experienced similar problems?

Nasko

**Comment by GrahamCampbell** [comment]
Thanks, but this is not a laravel bug. Please report this to the PHP team
