### ISSUE TITLE
Laravel 5.2.16 Throttle Request Fatal Throwable Error

### ISSUE THREAD

**Issue by ssuhat** [laravel/framework#12309]
Today I update my laravel version to 5.2.16 and when I access the API it gives me error. Before update everything works perfectly. 

Here is the screenshot of error:

![untitled](https://cloud.githubusercontent.com/assets/10653041/13065370/55325998-d48e-11e5-9158-648553f03928.png)

Here is my middleware setup:

        protected $middlewareGroups = [
            'web' => [
                \App\Http\Middleware\EncryptCookies::class,
                \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
                \Illuminate\Session\Middleware\StartSession::class,
                \Illuminate\View\Middleware\ShareErrorsFromSession::class,
                \App\Http\Middleware\VerifyCsrfToken::class,
            ],

            'api' => [
                'throttle:999999,1',
            ],
        ];
    protected $routeMiddleware = [

        'auth'           => \App\Http\Middleware\Authenticate::class,
        'auth.basic'     => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        'guest'          => \App\Http\Middleware\RedirectIfAuthenticated::class,
        'throttle'       => \Illuminate\Routing\Middleware\ThrottleRequests::class,
        'auth.user'      => \App\Http\Middleware\UserAuthorization::class,
     ];

**Comment by jenky** [comment]
+1 I got this error too. It happened with `Response::json` or `response()->json()`.

**Comment by gianlup** [comment]
The same for me. With 5.2.15 works well

**Comment by lucasmichot** [comment]
Guys feel free to use my temporary middleware: https://gist.github.com/lucasmichot/db42a79854ffe8575443

**Comment by hansvn** [comment]
+1 I also have this error with json responses
