### ISSUE TITLE
No Tag for 5.2 branch

### ISSUE THREAD

**Issue by erayaydin** [laravel/framework#12301]
v5.2.15 Tag
https://github.com/laravel/framework/blob/v5.2.15/src/Illuminate/Http/RedirectResponse.php

5.2 Branch
https://github.com/laravel/framework/blob/5.2/src/Illuminate/Http/RedirectResponse.php

Its changed but not added new tag. We can't update from composer.

**Comment by stevebauman** [comment]
+1, recent commit broke file uploads for me, need the new tag asap :)

**Comment by GrahamCampbell** [comment]
> In the meantime, rolled back to 5.2.14.

That's what I'm doing too. A new tag will be out shortly. Also, you can of course ask composer for `~5.2.16` and it will resolve a dev version for you provided your min stability is such that it can.
