### ISSUE TITLE
Problem with extending Blade templates.

### ISSUE THREAD

**Issue by oliski** [laravel/framework#12318]
How to reproduce:
1. Create three templates:
template1: main.blade.php
```
@include('block')
@include('block')
@include('block')
@include('block')
```
Template 2: block.blade.php
```
@extends('part')
@section('rand')
    {{ rand(1,1000)}}
@endsection
{{ rand(1,1000)}}
```

Template 3: part.blade.php
```
<div>
    My rand is: @yield('rand')
</div>
```
2. Now create route to first template (main) and open it in browser.
3. You would expect that there will be different random number on each line, however, this does not work as expected.

4. My output:
```
460
My rand is: 651
147
My rand is: 651
319
My rand is: 651
255
My rand is: 651
```

 Laravel Framework version 5.1.28 (LTS)

**Comment by arrilot** [comment]
You need to use @parent, right?

**Comment by oliski** [comment]
No, @parent is wrong.

In this approach I get: 
```
585
My rand is: 940
547
My rand is: 545 940
269
My rand is: 822 545 940
83
My rand is: 899 822 545 940
```

However, I want:

460
My rand is: 651
147
My rand is: 123
319
My rand is: 333
255
My rand is: 444

(random numbers in each row)

What I want to accomplish:
In main template I want to include "blocks" of data. Blocks can be around 20, with different html inside, however, there are only 3-4 variations of them (part.blade.php). 
In other words, I want ot call part.blade.php as a function with different parameters. 

How to do that, if this is not bug ?

**Comment by oliski** [comment]
Other approach would be to include file, however, then there is a problem with passing a lot of information to variables:

block.blade.php:
```
@assignToVariable('somevariable')
  {{ rand(1,1000)}}
@endAssign

@assignToVariable('somevariable2')
some other content, for example - couple of tables.
@endAssign

@include('part',{'rand' => $someVariable, 'rand2' => $someVariable2});
```

Of course, this is not working.
