### ISSUE TITLE
Cannot find relations when where() references a $casts['integer'] attribute.  

### ISSUE THREAD

**Issue by moccalotto** [laravel/framework#12316]
Recreate error:

$shoppingCart->lines->where('some_casted_integer', 5); // zero results always
$shoppingCart->lines->where('some_casted_integer', '>', 0); // zero results always

Code that works:

$shoppingCart->lines()->where('some_casted_integer', 5)->get(); // returns expected results
$shoppingCart->lines()->where('some_casted_integer', '>', 0)->get(); // returns expected results

**Comment by moccalotto** [comment]
Only tested on sqlite...

**Comment by morloderex** [comment]
This is not a bug, you must chain get or first after query statements..

**Comment by moccalotto** [comment]
But if I remove the cast, or change the cast to "string", it works as expected. So, if nothing else, it is inconsistent behavior.

**Comment by GrahamCampbell** [comment]
Where queries will not respect equation casting. They are queries. Casting happens afterwards.

**Comment by GrahamCampbell** [comment]
> // zero results always

You forgot to actually execute the query...
