### ISSUE TITLE
php artisan command does not bring the command list 

### ISSUE THREAD

**Issue by asolenzal** [laravel/framework#12329]
Hi I have installed laravel 5.0 on my server, now, after installation I get the following error: 

> post-update-cmd: php artisan clear-compiled
Script php artisan clear-compiled handling the post-update-cmd event returned with an error

                      
  [RuntimeException]  
  Error Output:       
                      

Exception trace:
 () at phar:///var/www/vhosts/entrenamiento.com/httpdocs/es/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:204
 Composer\EventDispatcher\EventDispatcher->doDispatch() at phar:///var/www/vhosts/entrenamiento.com/httpdocs/es/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:94
 Composer\EventDispatcher\EventDispatcher->dispatchScript() at phar:///var/www/vhosts/entrenamiento.com/httpdocs/es/composer.phar/src/Composer/Installer.php:335
 Composer\Installer->run() at phar:///var/www/vhosts/entrenamiento.com/httpdocs/es/composer.phar/src/Composer/Command/UpdateCommand.php:158
 Composer\Command\UpdateCommand->execute() at phar:///var/www/vhosts/entrenamiento.com/httpdocs/es/composer.phar/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at phar:///var/www/vhosts/entrenamiento.com/httpdocs/es/composer.phar/vendor/symfony/console/Application.php:844
 Symfony\Component\Console\Application->doRunCommand() at phar:///var/www/vhosts/entrenamiento.com/httpdocs/es/composer.phar/vendor/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at phar:///var/www/vhosts/entrenamiento.com/httpdocs/es/composer.phar/src/Composer/Console/Application.php:166
 Composer\Console\Application->doRun() at phar:///var/www/vhosts/entrenamiento.com/httpdocs/es/composer.phar/vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at phar:///var/www/vhosts/entrenamiento.com/httpdocs/es/composer.phar/src/Composer/Console/Application.php:99
 Composer\Console\Application->run() at phar:///var/www/vhosts/entrenamiento.com/httpdocs/es/composer.phar/bin/composer:43
 require() at /var/www/vhosts/entrenamiento.com/httpdocs/es/composer.phar:25

Then when I try to open the artisan there is no output.

**Comment by GrahamCampbell** [comment]
5.0 is not supported. Feel free to ask on the forums though.
