### ISSUE TITLE
[5.2] Illuminate\Auth\Access\Gate->deny() returns HTTP 500 error instead of 403

### ISSUE THREAD

**Issue by naerymdan** [laravel/framework#12322]
Documentation (https://laravel.com/docs/5.2/authorization#controller-authorization) indicates that a failed authorization check will generate a HTTP 403 response.

Using 5.2.15, I currently get a HTTP 500 error response instead.

**Comment by GrahamCampbell** [comment]
Is it the latest version, and is your exception handler in sync with laravel/laravel?

**Comment by naerymdan** [comment]
I just updated to latest (5.2.16) and am not using any  custom exception handlers. Debugging through, the Gate throws a "AuthorizationException" which then runs through the "Illuminate\Routing\Pipeline" which then goes to the Dingo Handler... dammit.

Sorry bout that then.
