### ISSUE TITLE
missing provider in services.json

### ISSUE THREAD

**Issue by pabloleone** [laravel/framework#12332]
This is the server services.json file content for providers:

`<?php return array (
  'providers' => 
  array (
    0 => 'Illuminate\\Auth\\AuthServiceProvider',
    1 => 'Illuminate\\Broadcasting\\BroadcastServiceProvider',
    2 => 'Illuminate\\Bus\\BusServiceProvider',
    3 => 'Illuminate\\Cache\\CacheServiceProvider',
    4 => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider',
    5 => 'Illuminate\\Cookie\\CookieServiceProvider',
    6 => 'Illuminate\\Database\\DatabaseServiceProvider',
    7 => 'Illuminate\\Encryption\\EncryptionServiceProvider',
    8 => 'Illuminate\\Filesystem\\FilesystemServiceProvider',
    9 => 'Illuminate\\Foundation\\Providers\\FoundationServiceProvider',
    10 => 'Illuminate\\Hashing\\HashServiceProvider',
    11 => 'Illuminate\\Mail\\MailServiceProvider',
    12 => 'Illuminate\\Pagination\\PaginationServiceProvider',
    13 => 'Illuminate\\Pipeline\\PipelineServiceProvider',
    14 => 'Illuminate\\Queue\\QueueServiceProvider',
    15 => 'Illuminate\\Redis\\RedisServiceProvider',
    16 => 'Illuminate\\Auth\\Passwords\\PasswordResetServiceProvider',
    17 => 'Illuminate\\Session\\SessionServiceProvider',
    18 => 'Illuminate\\Translation\\TranslationServiceProvider',
    19 => 'Illuminate\\Validation\\ValidationServiceProvider',
    20 => 'Illuminate\\View\\ViewServiceProvider',
    21 => 'Appzcoder\\CrudGenerator\\CrudGeneratorServiceProvider',
    22 => 'Collective\\Html\\HtmlServiceProvider',
    23 => 'Davibennun\\LaravelPushNotification\\LaravelPushNotificationServiceProvider',
    24 => 'App\\Providers\\AppServiceProvider',
    25 => 'App\\Providers\\AuthServiceProvider',
    26 => 'App\\Providers\\EventServiceProvider',
    27 => 'App\\Providers\\RouteServiceProvider',
  ),`

And this other is the services.json file for providers in my local:

`<?php return array (
  'providers' =>
  array (
    0 => 'Illuminate\\Auth\\AuthServiceProvider',
    1 => 'Illuminate\\Broadcasting\\BroadcastServiceProvider',
    2 => 'Illuminate\\Bus\\BusServiceProvider',
    3 => 'Illuminate\\Cache\\CacheServiceProvider',
    4 => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider',
    5 => 'Illuminate\\Cookie\\CookieServiceProvider',
    6 => 'Illuminate\\Database\\DatabaseServiceProvider',
    7 => 'Illuminate\\Encryption\\EncryptionServiceProvider',
    8 => 'Illuminate\\Filesystem\\FilesystemServiceProvider',
    9 => 'Illuminate\\Foundation\\Providers\\FoundationServiceProvider',
    10 => 'Illuminate\\Hashing\\HashServiceProvider',
    11 => 'Illuminate\\Mail\\MailServiceProvider',
    12 => 'Illuminate\\Pagination\\PaginationServiceProvider',
    13 => 'Illuminate\\Pipeline\\PipelineServiceProvider',
    14 => 'Illuminate\\Queue\\QueueServiceProvider',
    15 => 'Illuminate\\Redis\\RedisServiceProvider',
    16 => 'Illuminate\\Auth\\Passwords\\PasswordResetServiceProvider',
    17 => 'Illuminate\\Session\\SessionServiceProvider',
    18 => 'Illuminate\\Translation\\TranslationServiceProvider',
    19 => 'Illuminate\\Validation\\ValidationServiceProvider',
    20 => 'Illuminate\\View\\ViewServiceProvider',
    21 => 'Appzcoder\\CrudGenerator\\CrudGeneratorServiceProvider',
    22 => 'Collective\\Html\\HtmlServiceProvider',
    23 => 'Davibennun\\LaravelPushNotification\\LaravelPushNotificationServiceProvider',
    24 => 'Tymon\\JWTAuth\\Providers\\JWTAuthServiceProvider',
    25 => 'App\\Providers\\AppServiceProvider',
    26 => 'App\\Providers\\AuthServiceProvider',
    27 => 'App\\Providers\\EventServiceProvider',
    28 => 'App\\Providers\\RouteServiceProvider',
  ),`

As you can see in the server the project is compiling the same file with different providers, this one is missing on the server:

    24 => 'Tymon\\JWTAuth\\Providers\\JWTAuthServiceProvider',

I presume it´s an issue with the environment as my local and server are at head master using the same composer.lock, but I cannot figure out what´s the problem.

Local PHP version:

PHP 5.6.13 (cli) (built: Sep 21 2015 19:06:46) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans

Server PHP version:

PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

Hope you can drop some ligth on this.

Thank you.

**Comment by GrahamCampbell** [comment]
services.json is no longer used from laravel 5.2 upwards.
