### ISSUE TITLE
[5.3] Explicit route model binding specific to a route group

### ISSUE THREAD

**Issue by hasyimibhar** [laravel/framework#12334]
#### Summary

Currently, explicit route model binding is global: once defined, it applies to all routes. It would be nice to be able to define binding specific to a route group. Something like this:

```php
$router->group(['namespace' => 'Foo'], function (Router $router) {
    $router->get('users/{user}', 'FooController@show');
    // ...
})->bind('user', function($value) {
    // ...
});
```

Or an alternative syntax:

```php
$router->group(['namespace' => 'Foo'], function (Router $router, RouteGroup $group) {
    $group->bind('user', function($value) {
        // ...
    });

    $router->get('users/{user}', 'FooController@show');
    // ...
});
```

#### Use Case
In one of my projects, I'm using soft-delete for one of the models. Using implicit model binding, querying for a soft-deleted entity results in 404, which is intended, because to the end-user, the entity is not there. However, at the same time, I want the soft-deleted entities to be visible to the *admins* (another user of the system.) So for all `/admin/*` routes, querying for a soft-deleted entity should not return 404. Currently, the way I circumvent this issue is by defining a different binding:

```php
$router->bind('entity_all', function($value) {
    // Include soft-deleted entries
    return SomeEntity::withTrashed()->find($value);
});
```

So when I need to include soft-deleted entries, I use `entity_all` instead:

```php
// Route definition
$router->group(['prefix' => 'admin', 'namespace' => 'Admin'], function (Router $router) {
    $router->get('entities/{entitiy_all}', 'EntityController@show');
    // ...
});
```

```php
// Controller method
public function show(SomeEntity $entity_all)
{
    // ...
}
```

The drawback with this approach is that I have to use `$entity_all` for the parameter name. It would be nice to be able to still use `$entity` by overriding the model binding for the admin route group:

```php
// Route definition
$router->group(['prefix' => 'admin', 'namespace' => 'Admin'], function (Router $router, RouteGroup $group) {
    $group->bind('entity', function($value) {
        // Include soft-deleted entries
        return SomeEntity::withTrashed()->find($value);
    });

    $router->get('entities/{entitiy_all}', 'EntityController@show');
    // ...
});
```

**Comment by Milewski** [comment]
+1

**Comment by GrahamCampbell** [comment]
Possible using a custom middleware in 5.3 now that we've moved the implementation out to a middleware instead of having it internal to the middleware.

**Comment by stevelacey** [comment]
I don't know what has changed in the 2 years since this issue was opened, but it seems route bindings are still global-only

I've been using explicit bindings like these so that I can use `uuid` over `api` routes and `slug` over `web` routes:

```php
Route::bind('category', function ($value) {
    if (in_array('api', Route::current()->middleware())) {
        return App\Category::where('uuid', $value)->first() ?? abort(404);
    }

    return App\Category::where('slug', $value)->first() ?? abort(404);
});
```

Also had some success conditionally limiting the results like this, e.g. allow visibility of all teams over API but only allow the user's own teams via web routes (web being for team management) – works pretty well:

```php
Route::bind('team', function ($value) {
    if (in_array('api', Route::current()->middleware())) {
        return App\Team::where('uuid', $value)->first() ?? abort(404);
    }

    return request()->user()->teams()->where('slug', $value)->first() ?? abort(404);
});
```
