### ISSUE TITLE
ldap auth form in laravel 5.2

### ISSUE THREAD

**Issue by st-claude** [laravel/framework#12344]
Hi

i'm noob, so this is an issue only for me :)

i know this is a recurrent question, but i started learning laravel a week ago, and after countless hours of watching tutorials and reading documentation, i can't seem to make this auth thing works :)
i read your comment here : https://github.com/Adldap2/Adldap2-Laravel/issues/7#issuecomment-142293763

and follow the instructions to the letter, but it seems that laravel 5.1 doesn't works exactly as the 5.2, so it's failing somewhere with a cryptic error (for me still)

i was wondering if maybe you could redo this kind of howto from scratch from laravel 5.2 ?

i have to say that i at least succeeded in connecting to my AD server, and dumping user data (i still can't format it properly but at least i see something)

also something else i'm confused in the documentation, this : 
$ad = new Adldap($config);

am i supposed to declare in the controller a $config with everything ? if so, what is config/adldap.php for ? 

thanks for reading me 
regards
Dann

**Comment by GrahamCampbell** [comment]
Please ask on the forums.

**Comment by st-claude** [comment]
what forums ?
is there a dedicated forum for adldap2 ?
i'm asking here because i saw similar questions being answered here, but for previous version of adldap.

i asked on laravel.io (http://laravel.io/forum/02-08-2016-adldap2-and-laravel-52) and they sent me here.

**Comment by jimmerioles** [comment]
@st-claude here [https://laracasts.com/discuss](https://laracasts.com/discuss)

**Comment by st-claude** [comment]
thank you i solved my issue with the help of stevebauman on adldap2
i will post soon an updated howto for noobs like me here : 
https://github.com/Adldap2/Adldap2/issues/188
