### ISSUE TITLE
Factory does not run with a modal with constructor

### ISSUE THREAD

**Issue by minerbog** [laravel/framework#12345]
I'm not sure if this is normal operation or not but it has taken me near 3 hours to pin point the error in my code. It appears that if an Eloquent model has a constructor function then any factory will not run on it. This posses a problem when I need a constructor to collect auth information in the model before processing.

**Comment by squigg** [comment]
Are you correctly accepting the $attributes parameter from the base `Model` constructor into your constructor and passing them up to `parent::__construct()`?
