### ISSUE TITLE
[5.2] After move of uploaded file,  missing temp file error. 

### ISSUE THREAD

**Issue by trwilliams** [laravel/framework#12350]
This will give an error

`public function addPost(ImageAddRequest $request)
    {
if ($request->hasFile('image')){
            $path = base_path()."/public/storage/pages/";
            $image = $request->file('image');
            $image->move($path, $image->getClientOriginalName());
            $name = $request->name;
        }
}
`
any instance of request after move gives and error that the temp file can not be found.

found exactly the line that is causing issue.

laravel/framework/src/Illuminate/Http/UploadedFile.php
Line 50

If I remove instanceof static it works fine.

The function is called from  laravel/framework/src/Illuminate/Http/Request.php 
Line 419

**Comment by taylorotwell** [comment]
Can you give me some code I can use to recreate this in a fresh Laravel application?

**Comment by vinkla** [comment]
This could be related to #12299. I'm also still having problems with this since the `5.2.15+` release.

**Comment by GrahamCampbell** [comment]
@vinkla Is it broken in 5.2.19?

**Comment by vinkla** [comment]
@GrahamCampbell Maybe, or it has at least changed in behaviour. My tests fails in versions `>=5.2.15`.

**Comment by magnetion** [comment]
@GrahamCampbell @vinkla You are correct.  The problem surfaced in 5.2.15.  Rolling back to .14 works.  We can produce this consistently across 20+ sites.

It almost appears that once you upload a file and take any action (in our case sanitize then move), it kind of bombs anything else in the request scope.  For example after moving the file an then using another form variable (non file related one) it throws the error as stated.

A couple more people have reported it here:
https://laracasts.com/discuss/channels/laravel/file-sometimes-got-uploaded-successfully-sometimes-it-disappears-from-the-tmp-directory

**Comment by GrahamCampbell** [comment]
> Can you give me some code I can use to recreate this in a fresh Laravel application?

**Comment by trwilliams** [comment]
## Controller
`class ImageController extends \Illuminate\Routing\Controller{
   public function addPost(ImageAddRequest $request) { 
        $path = base_path()."/public/storage/pages/"; 
         $image = $request->file('image'); 
         $image->move($path, $image->getClientOriginalName()); 
         $name = $request->name; 
         return Redirect::to('/'.$name);
    } 
}`

**Comment by trwilliams** [comment]
## Request

`class ImageAddRequest extends FormRequest {

    public function rules()
    {
        return [
            'name' => 'required',
            'image' => 'image'
        ];
    }

    public function authorize()
    {
        return true;
    }

}`

**Comment by trwilliams** [comment]
## Form

```
{!! Form::open(array('files'=> true)) !!}
      {!! Form::hidden('name', 'test') !!}
      {!! Form::file('image') !!}
      {!! Form::submit('SUBMIT') !!}
{!! Form::close() !!}
```

**Comment by taylorotwell** [comment]
Hmm, I still can't recreate this with this code sample :|

**Comment by taylorotwell** [comment]
What version of Laravel are you on?

**Comment by vinkla** [comment]
I don't know which version @trwilliams but @magnetion and I have issues with `>=5.2.15`.

**Comment by taylorotwell** [comment]
@vinkla does the code snippet above break for you on 5.2.19?

**Comment by magnetion** [comment]
@taylorotwell It started happening in 5.2.15 and was occurring yesterday in 5.2.19.

**Comment by taylorotwell** [comment]
OK, can someone give me maybe a different code snippet you have I might can use to recreate @vinkla or @magnetion ?

**Comment by magnetion** [comment]
@taylorotwell After the following runs, anything that occurs after this will error with the temp file does not exist error.  So after running the code below, if you try and reference $request->anyformfield it errors.

`if (Request::hasFile('image')) :
    $image = Request::file('image');
    $uniqueName = Universal::getUniqueFilename('storage/product', $image->getClientOriginalName());
    Request::file('image')->move('storage/product', $uniqueName);
endif;`

**Comment by taylorotwell** [comment]
But, it doesn't for me. That's why I'm confused. It keeps working fine even after moving the file.

**Comment by trwilliams** [comment]
It happens in any version above 5.2.14.  Also it only happens when getting the file form a request object.
public function addPost(ImageAddRequest $request) {$request->...}

But it works if you get the request like this.
public function addPost() {$request = Input::all(); $request['image']}

Actually everything does go through and upload fine, but it throws the error. If you go to a different page and come back you will see the it did upload correctly, we just can't have the error.

**Comment by vinkla** [comment]
Here is my test and controller: 

The test:
```php
factory(User::class)->create();

Storage::put('test.png', base64_decode('imagedata'));

$path = public_path('images/uploads/test.png');

$finfo = finfo_open(FILEINFO_MIME_TYPE);
$mime = finfo_file($finfo, $path);

$this->call('POST', 'users/1/images', [], [], ['image' => new UploadedFile($path, 'test.png', $mime, null, null, true)]);
$this->seeJson(['type' => 'image']);
$this->assertResponseStatus(201);
exec('rm '.public_path('images/uploads/*.png'));
```

The controller:
```php
$name = strtolower(Uuid::uuid4().'.'.$image->getClientOriginalExtension());

// This is where is fails for me.
$image->move(public_path('images/uploads'), $name); 

return Image::create(['name' => $name]);

**Comment by taylorotwell** [comment]
@vinkla are you using a FormRequest or just the normal Illuminate\Http\Request?

**Comment by taylorotwell** [comment]
Also @vinkla have you looked into the core at all to see where there might be a fix needed?

**Comment by trwilliams** [comment]
In first message. here are the lines that need looked at.

laravel/framework/src/Illuminate/Http/UploadedFile.php
Line 50

If I remove instanceof static it works fine.

The function is called from laravel/framework/src/Illuminate/Http/Request.php 
Line 419

**Comment by vinkla** [comment]
I'm using `Illuminate\Http\Request` and no I've not looked into core to find a solution. Sorry about that, I will try to find a fix soon.

**Comment by taylorotwell** [comment]
@trwilliams so what does your full patched method look like with the instanceof static removed?

Really wish I could recreate this but can't even with a Form Request. @trwilliams is yours triggered from a unit test or web UI?

**Comment by taylorotwell** [comment]
Also what version of PHP?

**Comment by trwilliams** [comment]
PHP 5.6.8

```
public static function createFromBase(SymfonyUploadedFile $file)
    {
        return $file ? $file : new static(
            $file->getPathname(), $file->getClientOriginalName(), $file->getClientMimeType(),
            $file->getClientSize(), $file->getError()
        );
    }
```

**Comment by vinkla** [comment]
I'm using PHP `7.0.3` with Laravel `5.2.19`.

**Comment by magnetion** [comment]
Also happening on 5.5.9

**Comment by taylorotwell** [comment]
@trwilliams that would break other things. I will have to recreate this first I guess before proceeding. I've still not been able to.

**Comment by taylorotwell** [comment]
You don't have cached compiled.php files with old versions  of things do you?

**Comment by taylorotwell** [comment]
Here is my route where I am trying to recreate it:

```php
Route::get('/', function () {
    return view('welcome');
});

Route::post('/', function (App\Http\Requests\TestRequest $request) {
    $image = $request->file('picture');
    $image->move(base_path('another_one'), $image->getClientOriginalName());
    $name = $request->name;
    dd($name);
});
```

**Comment by taylorotwell** [comment]
@vinkla when you do that "new UploadedFile" in your test is it an instance of Illuminate\Http\UploadedFile or a Symfony version?

**Comment by magnetion** [comment]
@taylorotwell Found something interesting.  I used your test case in a fresh install.  Your test works fine.  But, if you add a redirect after everything is done it errors.

```php
Route::post('/', function (App\Http\Requests\TestRequest $request) {
    $image = $request->file('picture');
    $image->move(base_path('another_one'), $image->getClientOriginalName());
    $name = $request->name;
    return Redirect::to('/');
    dd($name);
});
```

**Comment by magnetion** [comment]
@taylorotwell 

FileNotFoundException in File.php line 37: The file "/var/www/temp/phpr6F3Nf" does not exist

**Comment by taylorotwell** [comment]
@magnetion can't recreate that either. it redirects fine for me.

**Comment by vinkla** [comment]
I'm using the Symfony's `UploadedFile` class.

**Comment by taylorotwell** [comment]
@vinkla what happens if you change it to Illuminate\Http\Uploaded file?

**Comment by magnetion** [comment]
It does upload the file with no issue.  But as soon as hits the redirect it errors.  I also confirmed this in another app.

Not sure if the full stack trace will shed any light.  

    in File.php line 37
    at File->__construct('/var/www/temp/phpToPeeZ', true) in UploadedFile.php line 96
    at UploadedFile->__construct('/var/www/temp/phpToPeeZ', 'SR71.jpg', 'image/jpeg', '273879', '0') in UploadedFile.php line 53
    at UploadedFile::createFromBase(object(UploadedFile)) in Request.php line 419
    at Request->Illuminate\Http\{closure}(object(UploadedFile))
    at array_map(object(Closure), array('picture' => object(UploadedFile))) in Request.php line 420
    at Request->convertUploadedFiles(array('picture' => object(UploadedFile))) in Request.php line 401
    at Request->allFiles() in Request.php line 304
    at Request->all() in Request.php line 1015
    at Request->__get('name') in routes.php line 23
    at RouteServiceProvider->{closure}(object(TestRequest))
    at call_user_func_array(object(Closure), array(object(TestRequest))) in Route.php line 158
    at Route->runCallable(object(Request)) in Route.php line 137
    at Route->run(object(Request)) in Router.php line 703
    at Router->Illuminate\Routing\{closure}(object(Request))
    at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
    at Pipeline->Illuminate\Routing\{closure}(object(Request))
    at call_user_func(object(Closure), object(Request)) in Pipeline.php line 103
    at Pipeline->then(object(Closure)) in Router.php line 705
    at Router->runRouteWithinStack(object(Route), object(Request)) in Router.php line 678
    at Router->dispatchToRoute(object(Request)) in Router.php line 654
    at Router->dispatch(object(Request)) in Kernel.php line 282
    at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))
    at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 44
    at CheckForMaintenanceMode->handle(object(Request), object(Closure))
    at call_user_func_array(array(object(CheckForMaintenanceMode), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
    at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
    at Pipeline->Illuminate\Routing\{closure}(object(Request))
    at call_user_func(object(Closure), object(Request)) in Pipeline.php line 103
    at Pipeline->then(object(Closure)) in Kernel.php line 132
    at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 99
    at Kernel->handle(object(Request)) in index.php line 54

**Comment by taylorotwell** [comment]
What operating system is this on? Is this using Homestead?

**Comment by magnetion** [comment]
@taylorotwell Ubuntu 14

**Comment by themsaid** [comment]
Tested this on ` 5.2.[16-19]` - `PHP 7.0.1` - homestead

```
Route::post('test', function (App\Http\Requests\TestRequest $request) {
    $image = $request->file('image');
    $request->file('image')->move( base_path()."/public/storage/", $image->getClientOriginalName());
    $name = $request->name;
    dd($name);
});
```

Working normally.

**Comment by magnetion** [comment]
Problem in our case appears to be something with the createFromBase function in /laravel/framework/src/Illuminate/Http

If I update this to return $file; everything works normally.

**Comment by taylorotwell** [comment]
I'm wondering if this is an issue with some operating systems deleting the /tmp upload files immediately on move whereas Homestead is leaving them in place for the rest of the request?

**Comment by magnetion** [comment]
@taylorotwell I also have some developers on XAMP (Windows) and this same error is happening as well there.  But I do think it has something to do with what you suggested.

**Comment by taylorotwell** [comment]
Can anyone that is having the problem try dev stability of 5.2 with my latest commit and see if that fixes your issues?

@magnetion @vinkla

**Comment by magnetion** [comment]
Had to run out but will check as soon as I return.

**Comment by lucasmichot** [comment]
:+1: @taylorotwell  !!! (that was fast)

**Comment by vinkla** [comment]
@taylorotwell I'll try it asap.

**Comment by trwilliams** [comment]
Yep seems to be fixed in latest dev.

**Comment by vinkla** [comment]
@taylorotwell didn't work for me :disappointed:

**Comment by taylorotwell** [comment]
OK. ill tag this in a bit.

**Comment by taylorotwell** [comment]
@vinkla really? so your unit test is still broken? you dont have a compiled file in the way do you?

**Comment by vinkla** [comment]
@taylorotwell no, I removed it before I tried to run the unit tests again.

**Comment by taylorotwell** [comment]
OK Ill try to recreate your unit test problem.

**Comment by vinkla** [comment]
Cool, let me know if there is anything else I can provide.

**Comment by taylorotwell** [comment]
@vinkla what is the exact error message you receive from your test?

**Comment by taylorotwell** [comment]
@vinkla I think I know your issue. See if passing an instance of `Illuminate\Http\UploadedFile` fixes your problem.

**Comment by vinkla** [comment]
@taylorotwell okay, great. I will try it first thing tomorrow morning.

**Comment by vinkla** [comment]
@taylorotwell now it works. Thanks!

**Comment by CasperLaiTW** [comment]
@vinkla You should create `Illuminate\Http\UploadedFile` after `5.2.15`
because `UploadedFile`  didn't pass `test` argument
https://github.com/laravel/framework/blob/5.2/src/Illuminate/Http/UploadedFile.php#L52

**Comment by vinkla** [comment]
@CasperLaiTW Yeah, that is what made it work. Though, upgrading to `5.2.15` shouldn't break stuff. I know Laravel doesn't follow SemVer but it is quite hard to know when these kind changes happen.

**Comment by kingpabel** [comment]
I was also fall on this problem in ```5.2.16``` and in now i am using ```5.2.29``` and this is solved

**Comment by poizon001** [comment]
string(40) "The file "/tmp/phpABBHzL" does not exist"
string(69) "Symfony\Component\HttpFoundation\File\Exception\FileNotFoundException"
string(4121) "#0 /home/vagrant/www/epicenter-api/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/File/UploadedFile.php(101): Symfony\Component\HttpFoundation\File\File->__construct('/tmp/phpABBHzL', true)
#1 /home/vagrant/www/epicenter-api/app/bootstrap.php.cache(320): Symfony\Component\HttpFoundation\File\UploadedFile->__construct('/tmp/phpABBHzL', 'Screen Shot 201...', 'image/png', 153150, 0)
#2 /home/vagrant/www/epicenter-api/app/bootstrap.php.cache(299): Symfony\Component\HttpFoundation\FileBag->convertFileInformation(Array)
#3 /home/vagrant/www/epicenter-api/app/bootstrap.php.cache(304): Symfony\Component\HttpFoundation\FileBag->set('photo_data', Array)
#4 /home/vagrant/www/epicenter-api/app/bootstrap.php.cache(292): Symfony\Component\HttpFoundation\FileBag->add(Array)
#5 /home/vagrant/www/epicenter-api/app/bootstrap.php.cache(287): Symfony\Component\HttpFoundation\FileBag->replace(Array)
#6 /home/vagrant/www/epicenter-api/app/bootstrap.php.cache(463): Symfony\Component\HttpFoundation\FileBag->__construct(Array)
#7 /home/vagrant/www/epicenter-api/app/bootstrap.php.cache(455): Symfony\Component\HttpFoundation\Request->initialize(Array, Array, Array, Array, Array, Array, NULL)
#8 /home/vagrant/www/epicenter-api/app/bootstrap.php.cache(1287): Symfony\Component\HttpFoundation\Request->__construct(Array, Array, Array, Array, Array, Array, NULL)
#9 /home/vagrant/www/epicenter-api/app/bootstrap.php.cache(489): Symfony\Component\HttpFoundation\Request::createRequestFromFactory(Array, Array, Array, Array, Array, Array)
#10 /home/vagrant/www/epicenter-api/src/Epicenter/ApiBundle/Listener/BuzzRequestListener.php(22): Symfony\Component\HttpFoundation\Request::createFromGlobals()
#11 /home/vagrant/www/epicenter-api/vendor/practo/buzz/lib/Buzz/Browser.php(130): Epicenter\ApiBundle\Listener\BuzzRequestListener->preSend(Object(Buzz\Message\Request))
#12 /home/vagrant/www/epicenter-api/vendor/practo/buzz/lib/Buzz/Browser.php(84): Buzz\Browser->send(Object(Buzz\Message\Request))
#13 /home/vagrant/www/epicenter-api/vendor/practo/buzz/lib/Buzz/Browser.php(48): Buzz\Browser->call('http://www.prac...', 'PATCH', Array, 'practo_account_...')
#14 /home/vagrant/www/epicenter-api/src/Epicenter/ApiBundle/Manager/ScoutEstablishmentManager.php(1492): Buzz\Browser->patch('http://www.prac...', Array, 'practo_account_...')
#15 /home/vagrant/www/epicenter-api/src/Epicenter/ApiBundle/Manager/ScoutEstablishmentPhotoManager.php(233): Epicenter\ApiBundle\Manager\ScoutEstablishmentManager->updateSpacePractice(Object(Epicenter\ApiBundle\Entity\ScoutEstablishment), Object(Symfony\Component\HttpFoundation\Request))
#16 /home/vagrant/www/epicenter-api/src/Epicenter/ApiBundle/Manager/ScoutEstablishmentPhotoManager.php(287): Epicenter\ApiBundle\Manager\ScoutEstablishmentPhotoManager->add('479', '/tmp/ec-uploads...', Object(Symfony\Component\HttpFoundation\Request), true)
#17 /home/vagrant/www/epicenter-api/src/Epicenter/ApiBundle/Controller/ScoutEstablishmentController.php(333): Epicenter\ApiBundle\Manager\ScoutEstablishmentPhotoManager->upload('479', Object(Symfony\Component\HttpFoundation\File\UploadedFile), Object(Symfony\Component\HttpFoundation\Request))
#18 [internal function]: Epicenter\ApiBundle\Controller\ScoutEstablishmentController->postEstablishmentsUploadphotoAction('479')
#19 /home/vagrant/www/epicenter-api/app/bootstrap.php.cache(3109): call_user_func_array(Array, Array)
#20 /home/vagrant/www/epicenter-api/app/bootstrap.php.cache(3071): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#21 /home/vagrant/www/epicenter-api/app/bootstrap.php.cache(3222): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#22 /home/vagrant/www/epicenter-api/app/bootstrap.php.cache(2444): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#23 /home/vagrant/www/epicenter-api/web/app_dev.php(61): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#24 {main}"

I am getting this error while uploading a file in post request which internally uses buzz browser to make another curl request. Which throws this exception.

**Comment by albanafmeti** [comment]
@taylorotwell 
Hey!
This issue is happening to me on Laravel 5.4, PHP 7, Ubuntu 16

After I move the uploaded file to a directory I make a call to a package class, but this package calls `Request::createFromGlobals();` This is throwing the FileNotFoundException.

Example:
`public function postStatus(Request $request)
{
    foreach ($request->allFiles() as $file) {
        $fileName = uniqid() . "_" . $file->getClientOriginalName();
        $file->move(storage_path("uploads/feeds"), $fileName);
    }

    // This line is handling Symfony\Component\HttpFoundation\File\Exception\FileNotFoundException
    // The file "/tmp/phpPQyWGk" does not exist
    $request = Request::createFromGlobals();

    dd($request->all());
}`

Help!

**Comment by jrnmagalhaes** [comment]
I got the same error. I discovered that my php.ini file was limiting my file upload to 2mb. I changed this and solved the error.

**Comment by waqarakbar** [comment]
I recently got same error on laravel 5.4 and php 5.6.4

(1/1) FileNotFoundException
The file "/Applications/MAMP/tmp/php/phpRYjYHA" does not exist
--
in MimeTypeGuesser.php line 116

my controller code looked like this

`foreach ( $request->file( 'files' ) as $file ) {
        $fileName = sha1( $file->getClientOriginalName() ) . "-" . $complaint->id . "." . $file->guessExtension();
        $file->move( public_path( 'complaint_media' ), $fileName );
	$cins = [
		'title'        => $file->getClientOriginalName(),
		'file'         => $fileName,
		'media_type'   => ComplaintMedia::getMediaType( $file->guessExtension() )
	];
						
        $comp_media = ComplaintMedia::create( $cins );
}`

But then I moved all method calls on `$file` (i.e. `getClientOriginalName()` and `guessExtension()`) before `$file->move()` and it works now. My controller code now looks like this

`foreach ( $request->file( 'files' ) as $file ) {
	$original_name = $file->getClientOriginalName();
	$extension = $file->guessExtension();
	$file_name = sha1($original_name)."-" .time().".".$extension;
						
	$file->move(public_path('complaint_media'), $file_name);
						
	$cins = [
		'complaint_id' => $complaint->id,
		'title'        => $original_name,
		'file'         => $file_name,
		'media_type'   => ComplaintMedia::getMediaType($extension)
	];
						
	$comp_media = ComplaintMedia::create($cins);
}`

**Comment by Mokolos** [comment]
think resetting $_FILES before redirecting or Request::createFromGlobals() would work : 

$_FILES = array();    //reset fileBag
$request = Request::createFromGlobals();

**Comment by ekrokowski** [comment]
@Mokolos Thank you, indeed that worked.

**Comment by devflexpro** [comment]
@Mokolos you good man, worked

`$_FILES = array(); //reset fileBag`

**Comment by decadence** [comment]
Best option is just copy file so it will be on place for `Request::createFromGlobals()`

**Comment by loko35387417** [comment]
face same issue, after i check this was caused by http request instance.
My code is $host = Request::capture()->getSchemeAndHttpHost()
I had changed to $request->getSchemeAndHttpHost()
It works fine.

**Comment by hendisantika** [comment]
I am using Laravel 7.8.1.
I am trying to upload the image files. Its uploaded to `public/images`.
But, when I try to retrieve the images it says that the image not found.
BTW, I am using MacOS Catalina.

Any suggestion??
Thanks

**Comment by hemratna** [comment]
@hendisantika I am facing the same issue. After moving a file to S3 not able to read from the `$request->file('file')`
Plz let me know if you found any workaround.

**Comment by ibrhaim13** [comment]
> face same issue, after i check this was caused by http request instance.
> My code is $host = Request::capture()->getSchemeAndHttpHost()
> I had changed to $request->getSchemeAndHttpHost()
> It works fine.

where can i put this line ?

**Comment by ibrhaim13** [comment]
> think resetting $_FILES before redirecting or Request::createFromGlobals() would work :
> 
> $_FILES = array(); //reset fileBag
> $request = Request::createFromGlobals();

put this line inside loop or top of controller ?

**Comment by laratutodotcom** [comment]
How to get file extension from path in Laravel 9? https://laratuto.com/how-to-get-file-extension-from-path-in-laravel/**

Larvel Function

```
$_EXTENSTION = $request->file->extension(); 

dd($_EXTENSTION);
```

**Comment by ARehmanMahi** [comment]
I'm using `spatie/laravel-medialibrary` and the package is causing the issue.

```
// vendor/spatie/laravel-medialibrary/src/MediaCollections/FileAdder.php:545

if (file_exists($fileAdder->pathToFile)) {
    unlink($fileAdder->pathToFile);
}
```
