### ISSUE TITLE
Manually Authenticated Sessions Not Persisting.

### ISSUE THREAD

**Issue by delahappy** [laravel/framework#12351]
I am using laravel 5.2 and having an issue where my manual sessions aren't persisting.  In my Login controller I have this:

`Auth::login($user);`
`$temp = Auth::user();`
`Log::info($temp); //This prints out the user I just logged in`

I have configured my User model to use a "people" table as such:

`protected $table = 'people';`
`public function getAuthIdentifier(){`
  `return $this->email;`
`}`
`protected $primaryKey = 'id'`

I am using email instead of username for the login.  When I hit the subsequent controller the Auth::user() does not exist.  I have a guest session.

I think I have followed the appropriate procedure to customize the model table.  Has anyone else experienced this?

**Comment by GrahamCampbell** [comment]
Please ask on the forums.
