### ISSUE TITLE
[5.2] Deploy on Heroku causes error: failed to open stream: Read-only file system

### ISSUE THREAD

**Issue by ZengineAlex** [laravel/framework#12362]
Hey guys,

I'm setting up a Laravel 5.2 App on Heroku. I deploy using a GH Repo with the App and now I'm getting this error:

```
ErrorException in Filesystem.php line 81: file_put_contents(/8c5dcc4d0403a63e7022d9f3171fa074ff9b989d.php): failed to open stream: Read-only file system
```

As I know Heroku has a read-only filesystem and I have no idea how to move on now. All blog posts or tutorials about setting up a Laravel App on Heroku spend no single word to this problem :(

**Comment by GrahamCampbell** [comment]
Please ask on the forums.
