### ISSUE TITLE
Provide a way to hook `sometimes` validation rules on FormRequest

### ISSUE THREAD

**Issue by Daskul** [laravel/framework#12361]
Is there a way to specify `sometimes` validation on FormRequest like the one below?

// from https://laravel.com/docs/5.2/validation#available-validation-rules
$v->sometimes('reason', 'required|max:500', function($input) {
    return $input->games >= 100;
});

the validator instance in the validate() method is transient.
if I call $v = FormRequest::getValidatorInstance lets say on constructor and do

$v->sometimes('reason', 'required|max:500', function($input) {
    return $input->games >= 100;
});

ill still have fresh validator instance inside validate() method and disregard the above validation.

**Comment by EliasZ** [comment]
http://stackoverflow.com/a/30301533

Though arguably not the prettiest way to do this. Maybe the applicable instance of the validator can be passed to `rules`.

**Comment by huiyang** [comment]
Why is this closed? what is the best practice to achieve this?
