### ISSUE TITLE
Column altering in migration may not apply

### ISSUE THREAD

**Issue by hovsep** [laravel/framework#12363]
I have a text column called "body" . Then I want to alter it to be longText, so I run a migration with 

`$table->longText('body')->change();` (of course I have doctrine/dbal in my composer.json)

So migration runs ok, but actually no modification occurs.

I make some investigation and found that Laravel uses Doctrine\DBAL\Schema\Comparator class to make diffTable. Ok, sounds good, but how it compares columns? I debugged column properties at diffColumn method and see that my "longText" become to Doctrine\DBAL\Types\TextType.

So Doctrine makes no difference between Text and LongText. It is not ok.

**Comment by EliasZ** [comment]
Doctrine can make a difference between the various text sizes. See [mapping matrix](https://doctrine-orm.readthedocs.org/projects/doctrine-dbal/en/latest/reference/types.html#mapping-matrix).

For example. `LONGTEXT` [will be used if](https://doctrine-orm.readthedocs.org/projects/doctrine-dbal/en/latest/reference/types.html#id107)

>column length is less or equal to 2 ^ 32 - 1 = 4294967295 or empty

If your issue is valid, there must be something wrong with [calculateDoctrineTextLength](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Schema/Grammars/Grammar.php#L412). Maybe you can try and validate that.

**Comment by hovsep** [comment]
I investigated deeper and found a problem in vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/MySqlSchemaManager.php  _getPortableTableColumnDefinition method.

For example I create a migration with single mutation `($table->text('body')->change();)`

So i debug $tableColumn var at beginning of the method :

`Array
(
    [Field] => body
    [Type] => longtext
    [Null] => NO
    [Key] => 
    [Default] => 
    [Extra] => 
    [Comment] => 
    [CharacterSet] => utf8
    [Collation] => utf8_unicode_ci
)`


Then I debug result :
`Doctrine\DBAL\Schema\Column Object
(
    [_type:protected] => Doctrine\DBAL\Types\TextType Object
        (
        )

    [_length:protected] => 
    [_precision:protected] => 10
    [_scale:protected] => 0
    [_unsigned:protected] => 
    [_fixed:protected] => 
    [_notnull:protected] => 1
    [_default:protected] => 
    [_autoincrement:protected] => 
    [_platformOptions:protected] => Array
        (
            [collation] => utf8_unicode_ci
        )

    [_columnDefinition:protected] => 
    [_comment:protected] => 
    [_customSchemaOptions:protected] => Array
        (
        )

    [_name:protected] => body
    [_namespace:protected] => 
    [_quoted:protected] => 
)
`

As you can see original longtext became a portable text type. So table diff will not be detected. I think  such a behaviour may be useful when same code should work with different databases, but it is bug when we make a migration.

**Comment by EliasZ** [comment]
https://github.com/doctrine/dbal/issues/ :smiley:
