### ISSUE TITLE
[5.1+] Artisan broken (and therefore cant set the app key) when a console command has Mailer as a dependency and the app key isn't set

### ISSUE THREAD

**Issue by philbates35** [laravel/framework#12374]
When an artisan command has `mailer`, `Illuminate\Mail\Mailer` or `Illuminate\Contracts\Mail\Mailer` as a dependency - either directly, or indirectly (i.e. one of the command's dependencies has it as a dependency), and the `APP_KEY` isn't yet set, it is not possible to use artisan at all due to this error:
```
$ php artisan
[RuntimeException]                                                         
No supported encrypter found. The cipher and / or key length are invalid.
```
This means that I can't actually call `artisan key:generate` to set the key to get around the error - because the error happens before the command is actually executed.

What is happening here is that the artisan application resolved the `mailer` dependency of the command, which results in the `queue.connection` binding being resolved, which results in the `encrypter` binding being resolved, which needs the key to already be set - which in my case it isn't.

This scenario happens when I clone down a fresh version of our company's Laravel application, which contains an artisan command that has a dependency, which in turn has a dependency on `Illuminate\Contracts\Mail\Mailer`. I immediate go to use artisan to set the `APP_KEY`, but I can't because of this error.

To reproduce:

1. A fresh Laravel 5.1 or 5.2 application
2. Set `APP_KEY` to the default (invalid) value of `SomeRandomKey` in `.env`.
3. Enable the default `App\Console\Commands\Inspire` command and amend it to the following:
```
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Foundation\Inspiring;
use Illuminate\Mail\Mailer;

class Inspire extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'inspire';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Display an inspiring quote';

    /**
     * Inspire constructor.
     * @param string $signature
     */
    public function __construct(\Illuminate\Contracts\Mail\Mailer $mailer)
    {
        parent::__construct();

        $this->mailer = $mailer;
    }


    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $this->comment(PHP_EOL.Inspiring::quote().PHP_EOL);
    }
}
```
4. Run `php artisan` and see the error. Importantly, `php artisan key:generate` doesn't work to be able to set the key.

**Comment by GrahamCampbell** [comment]
> Enable the default App\Console\Commands\Inspire command and amend it to the following:

Your amendments are what is breaking this.

**Comment by EliasZ** [comment]
@GrahamCampbell Ehhh?

@philbates35 is explicitly stating that it is an example to reproduce the issue. The issue at hand is explained crystal clear:

>What is happening here is that the artisan application resolved the mailer dependency of the command, which results in the queue.connection binding being resolved, which results in the encrypter binding being resolved, which needs the key to already be set - which in my case it isn't.

**Comment by philbates35** [comment]
As @EliasZ says, amending the Inspire command was just the simplest way of providing reproducible steps.

Of course in the real world you would create a command such as `SendQueuedEmailCommand` that takes the `Mailer` as a dependency in it's constructor - at which point you would get this error so long as the `APP_KEY` isn't set.

**Comment by GrahamCampbell** [comment]
Use the app property on the command to resolve dependencies for the cli command. There is literally no point in using di since you're never going to unit test a cli command, in the same way that you wouldn't a controller because they're not suitable for that style of testing.

**Comment by GrahamCampbell** [comment]
Feel free to continue on the forums, but this isn't a bug in the framework.

**Comment by philbates35** [comment]
You make a valid point, that as you wouldn't unit test the command there might be not be any benefit of using DI so I could just resolve the dependency from the `laravel` property of the command.

That said - why shouldn't I be able to do it? It works everywhere else in the application flawlessly. It also works perfectly in many other commands that have many different dependencies, they just don't have the mailer as a dependency.

In fact, having just had a very quick browse through the Framework source code, many of the Illuminate commands use DI to inject dependencies too. Although I'm aware there are some conventions in the framework that aren't necessarily carried over into the application - in this case though, if I see the framework is doing it DI in a command, I would expect to be able to do it in my application as well with no repercussions.

Having to spend an hour this morning working out that the reason artisan was completely broken and unable to set the app key was because I innocently injected a mailer into a custom command seems like a bug to me IMO.

**Comment by GrahamCampbell** [comment]
It's just a case of learning how the framework works. For example, I'd never inject the mailer like that because I know in order to do that, you need to resolve the queue objects, which will in turn resolve the encryption objects, which require correct configuration.

Laravel will instantiate all commands in order to register them with the application.

Thus, you cannot write code like that. This will never change.

**Comment by GrahamCampbell** [comment]
I personally just would write `app(Mailer::class)->` in my cli apps if i really wanted to do something like that.
