### ISSUE TITLE
[Feature request] Support for Blade @include_block feature ?

### ISSUE THREAD

**Issue by vladrusu** [laravel/framework#12377]
Hello !
I am trying to find a nice, flexbile way to display alerts (and basically insert small html "snippets"/helpers) in my project.

Typically, the code for an alert goes like:
> `<div class="alert alert-info" role="alert">`
> `.... html code .... (several lines of <p>s and stuff)`
> `</div>`

The thing is I'd like to "decouple" my alert html code to something like:
> `@include_block('partials.alerts.info')`
> `... html code ...`
> `@stop`

.... where partials.alert.info.blade.php should be like:
> `<div class="alert alert-info" role="alert">`
> `{{ $html }}`
> `</div>`

Yes, I'd like that Laravel be able to "send" some random html block to a $html variable I use in given view. Something like a section... you get the idea.

But that's not possible now!

How I do things now:
> `@include('partials.info.header')`
> `... html code ...`
> `@include('partials.info.footer')`

Of course, this is a nasty, suboptimal way of doing things.

PS: I know I can send variables to `@include` but I don't like that, because my alerts get very often "messy" and complex, with many html code lines.

Any ideas?
Thank you in advance!

**Comment by EliasZ** [comment]
Doesn't [@include](https://laravel.com/docs/master/blade#control-structures) already do what you want?

For example, in your case you can pass a `message` variable:

    @include('partials.alerts.info', ['message' => 'foo'])

And in your partial you output that message with whatever HTML you want.

**Comment by vladrusu** [comment]
I know that I can "attach" a variable to a view.

I already stated that what I want is to send a whole block of html. What I am trying to do is a mix/hybrid between `@include` and `@section`.

**Comment by EliasZ** [comment]
If you are sending a whole block of html, is there any benefit of not just adding the `<div class="alert alert-info" role="alert"></div>` code too...? Or do you have any more complex partials which is more than just a div?

You can also combine @inlcude and @section by the way:

    @section('content')
        some alert html
    @endsection
    @include('partials.alert.info.blade')

    // partials.alert.info.blade
    <div class="alert alert-info" role="alert">
        @yield('content')
    </div>

Anyway, I don't think feature requests are considered in this issue tracker. Try the Larachat slack or send a PR with skeleton functionality to poke maintainers.

**Comment by GrahamCampbell** [comment]
Sorry, we don't process feature requests on GitHub.

**Comment by vladrusu** [comment]
@GrahamCampbell I understand. Where is the best place to place them?

**Comment by EliasZ** [comment]
@vladrusu https://laravel.com/docs/5.2/contributions#core-development-discussion
