### ISSUE TITLE
The resolving or afterResolving events on Container is not working when model binding is on

### ISSUE THREAD

**Issue by heera** [laravel/framework#12372]
**Laravel Framework version 5.2.16**
When I've a route declared as `Route::get('posts/{post}', 'PostController@edit')` the registered event listener is not firing, for example:
<pre>
$this->app->afterResolving(Model::class, function(Model $model, $app) {
     dd($model); // Not working
});
</pre>

What I want to do is, get the resolved/injected model so I can modify it. Is there any way to get the model in resolving/afterresolving handler?

Motivation: I want to get the bound model in save method of a controller, i.e: `save(Post $post)` but when posting the model for saving I want to override the action so instead of retrieving the model from database, I would like to fill the Model with Request::inputs while referencing the submitted model. What it means that, set the `id` only and fill it with form data.

**Comment by GrahamCampbell** [comment]
Models are not "resolved" from the ioc container.

**Comment by taylorotwell** [comment]
Instead of using the container for this use `Route::bind('post', function () {});`
