### ISSUE TITLE
More RESTful Default Auth Routes and Controllers

### ISSUE THREAD

**Issue by petermichaux** [laravel/framework#12388]
I'd like to propose a change to the organization of the default auth controllers and routes. If there is interest in these ideas then I can invest time in researching the necessary implementation changes.

The following is a snippet from current Laravel showing the login and registration routes also indicating the organization of the controllers.

From https://github.com/laravel/framework/blob/4941882771fb3a2789ba3fabd8af1b0642ecce3f/src/Illuminate/Routing/Router.php#L362

    // Authentication Routes...
    $this->get('login', 'Auth\AuthController@showLoginForm');
    $this->post('login', 'Auth\AuthController@login');
    $this->get('logout', 'Auth\AuthController@logout');
    // Registration Routes...
    $this->get('register', 'Auth\AuthController@showRegistrationForm');
    $this->post('register', 'Auth\AuthController@register');

The above code is not organized in a particularly RESTful way.

When a client makes a `POST /register` request, there is no registration entity created on the server. What is actually being created is a new user in the database. It is that new user entity can be manipulated in the usual REST CRUD ways.

The lack of RESTful organization means there is not a clear, natural location to put routes and controller actions for a user to update his name, email address, and password.

It is possible to organize registration and login more RESTfully. These routes, controllers, and actions are more in line with a resource-based API.

    // Authentication Routes...
    $this->get('login', 'LoginController@create');
    $this->post('logins', 'LoginController@store');
    $this->get('logout', 'LoginController@delete');
    // Registration Routes...
    $this->get('register', 'UserController@create');
    $this->post('users', 'UserController@store');

As an example benefit, the above changes would also give natural places for a user to update his name, email address, and password.

    $this->get('user/edit', 'UserController@edit');
    $this->post('user/update', 'UserController@update');

The above is just the start of making these more RESTful. More changes like, using `201 Created` response status and `Location` headers could also be implemented as continuations of the above suggestions.

It looks like changes to both `laravel/framework` and `laravel/laravel` would be required to be synchronized.

Would a pull request for changes along these lines be seriously considered?

**Comment by GrahamCampbell** [comment]
Sorry, we don't process proposals on GitHub.

**Comment by petermichaux** [comment]
Where do I make the proposal?
