### ISSUE TITLE
[5.2][Database][Question] Commit method can cause negative transactionLevel

### ISSUE THREAD

**Issue by marella** [laravel/framework#12382]
Similar to #6360 but issue is because of commit method.
Calling commit method first will make transactionLevel go below 0.
```php
DB::commit();
echo DB::transactionLevel(); // -1
```
Now calling DB::transaction() will not beginTransaction as transactionLevel is 0 but all changes are updated in database and rollBack is not possible.
```php
DB::transaction(function() {
    echo DB::transactionLevel(); // 0
    DB::delete('DELETE FROM table_name');
    throw new Exception('foo'); // no rollBack happens
});
```

Shouldn't the [commit method](https://github.com/laravel/framework/blob/5.2/src%2FIlluminate%2FDatabase%2FConnection.php#L546) have a check on transactions like [rollBack method](https://github.com/laravel/framework/blob/5.2/src%2FIlluminate%2FDatabase%2FConnection.php#L566)?
```php
--$this->transactions; // instead of this
$this->transactions = max(0, $this->transactions - 1); // use this
```
Or throw exception when trying to commit when there is no transaction?
```php
if ($this->transactions === 0) {
    throw new RuntimeException('There is no active transaction');
}
```

**Comment by GrahamCampbell** [comment]
> $this->transactions = max(0, $this->transactions - 1); // use this

No, that's just a hack that's not actually fixing the real issue.

**Comment by marella** [comment]
Wouldn't it be better to throw an exception when commit and rollBack methods are called with 0 transactionLevel?
