### ISSUE TITLE
Session laravel 5.2 - doc update suggestion

### ISSUE THREAD

**Issue by viniciusgava** [laravel/framework#12387]
Hello, I have some projects in Laravel but they are in old version(5.1) and today I started a new project in 5.2 version, so after a long and long time trying to discover why the session was not working, I discovered that I had to put the routes that use session inside of a group of route which use web middleware. 

So, why this is not informed inside of session doc, I found a lot of people with this problem and the solution for this is in route doc.

**Comment by a-komarev** [comment]
A lot of information provided in [routes documentation](https://laravel.com/docs/5.2/routing#basic-routing)

In [middleware documentation](https://laravel.com/docs/5.2/middleware#registering-middleware)

[And in 5.2 release notes](https://laravel.com/docs/5.2/upgrade#upgrade-5.2.0)

But it will be useful to add this info to [5.2 to 5.1 upgrade guide](https://laravel.com/docs/5.2/upgrade#upgrade-5.2.0)

**Comment by viniciusgava** [comment]
yes, but I think it is good add it some warning in session doc, after all, it is required "setting" to sessions work.

well, it is a suggestion.

**Comment by a-komarev** [comment]
I'm agree with you, just rechecked and noticed that it's missed from upgrade guide, which is very important part of upgrade. Because as I remember my first upgrade from 5.1 taken couple of hours to resolve this issue.

**Comment by GrahamCampbell** [comment]
We're open to PRs. ;)
