### ISSUE TITLE
Paginator 'lastPage' value when 0 results

### ISSUE THREAD

**Issue by danydev** [laravel/framework#12395]
If you use the paginator and you have 0 results, you have the following output
```
[
   'total' => 0,
   'lastPage' => 0,
   'items' => [],
   'perPage' => 15,
   'currentPage' => 1,
]
```
Don't you think that `currentPage` should match `lastPage`? I don't see the point in saying that you are on page 1, but there are 0 pages.
So you should either say "you are in page 1 (`currentPage`) of 1 (`lastPage`), that contains 0 `items`" or "you are in page 0 (`currentPage`) of 0 (`lastPage`)"

@taylorotwell Please let me know, if this is considered an error, I can look in to it.

**Comment by GrahamCampbell** [comment]
Looks correct to me, since the total is 0.

**Comment by GrahamCampbell** [comment]
If we define the total to be 1 for the empty set, then it would be correct to change the last page value.

**Comment by danydev** [comment]
`total` must be 0, since this is the total of the items. I still think `currentPage` and `lastPage` should be either 0 or 1. You can't be at page 1 of 0 pages, but you can be at page 1 of 1 page with 0 items, or you can be at page 0 of 0 pages (if you want to communicate indirectly that there are 0 items)

**Comment by cryode** [comment]
+1 for using 1 as the `lastPage` value, for this exact reason:

> you can be at page 1 of 1 page with 0 items

You are still on the first page, whether it has 0, 1, or the total per-page number of items on it.

**Comment by mark86092** [comment]
Although the term `lastPage`, actually, it works as total pages. I think if the total == 0, the lastPage should be 0, too.
The valid `currentPage` should >= 1, so when total = 0, `currentPage` make no sense, it should be 0, presenting not found or empty.

**Comment by danydev** [comment]
@taylorotwell thoughts?
