### ISSUE TITLE
Failure in middle of migration leaves partial changes in database

### ISSUE THREAD

**Issue by kureci** [laravel/framework#12396]
When you have any issues part-way through a migration, the migration fails but part of it is already applied to the database. `migrate:rollback` doesn't help because the migration row isn't added to the table - but even if it was, rollback would also fail as not all parts of migration was successful. An example is:

```
Schema::create('test_table', function(Blueprint $table) {
            $table->string('a_really_long_field_name');
            $table->string('another_really_long_field_name_to_simulate_issue');

            $table->unique(['a_really_long_field_name', 'another_really_long_field_name_to_simulate_issue']);
        });
```

in the code above, if MySQL throws an error for the unique key name being too long, the migration fails but the table `test_table` is created nonetheless. And doing a rollback isn't an option as the migration row isn't added because of failure. 

I would suggest using database transactions when doing migrations to avoid this scenario.

**Comment by hasyimibhar** [comment]
I'm not sure about other database, but in MySQL, it is not possible due to [implicit commit](http://dev.mysql.com/doc/refman/5.7/en/implicit-commit.html).

**Comment by robclancy** [comment]
Either separate into 2 migrations or don't commit broken migrations. This has been an issue since the early days and there is no simply way to magically revert things that aren't supported by transactions (like creating tables).

**Comment by GrahamCampbell** [comment]
This has come up before, and what we have atm was the best option after some discussion, and attempts at making it transactional.
