### ISSUE TITLE
isDirty() false positive with boolean fields

### ISSUE THREAD

**Issue by kamui545** [laravel/framework#12390]
isDirty() is returning true even if nothing changed.

# How to reproduce

```
$user = User::find(1);

var_dump($user->locked); // false
var_dump($user->isDirty('locked')); // false

$user->locked = false;

var_dump($user->locked); // false
var_dump($user->isDirty('locked')); // true, should be false
```

**Comment by GrahamCampbell** [comment]
I assume this is because you have casts bool on that property. This is a known bug, and an issue already exists for it.

**Comment by GrahamCampbell** [comment]
Thanks though.

**Comment by ArthurGuy** [comment]
I was about to raise this issue but I see it's cropped up a few times already.
@GrahamCampbell do you know where the other issue is, I can't see anything that still open?

**Comment by kamui545** [comment]
Try with this filter https://github.com/laravel/framework/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20cast

It's not only about the boolean but casting in general: dates, etc...

**Comment by ArthurGuy** [comment]
There are a few possible issues there but nothing that seems to have been "accepted"
