### ISSUE TITLE
Request: Ability to author custom stubs

### ISSUE THREAD

**Issue by scottconnerly** [laravel/framework#12399]
Perhaps stored in a new folder in resources with very specific naming conventions, such that if the file exists, it is picked up by the related make command? For example: event-handler.stub or migrations-blank.stub

**Comment by GrahamCampbell** [comment]
Sorry, but we don't process proposals here.

**Comment by scottconnerly** [comment]
Where's the most appropriate place for proposals?

**Comment by GrahamCampbell** [comment]
Probably bring it up on slack and see if anyone has any feedback, or agrees that it belongs in the core.
