### ISSUE TITLE
Flash messages

### ISSUE THREAD

**Issue by Dreaw** [laravel/framework#12404]
Hi everyone,

I have version Laravel 5.1 (now 5.1.30) and now I have problem with Session Flash messages. It worked fine, but now (probably after update - composer update) the flash messages stays over the all requests. So when I set the flash message, I see this message for a long time over the application.

Is problem on my side or somewhere in update?

Thank you for any advice.

**Comment by GrahamCampbell** [comment]
Please provide the last version it worked on.

**Comment by Dreaw** [comment]
I'm not sure, but I think that version 5.1.29 worked.

**Comment by GrahamCampbell** [comment]
Can you please check.

**Comment by vlakoff** [comment]
You might want to have a look at #11117 and #11184.
