### ISSUE TITLE
When using artisan tinker, after an exception, database connection is closed

### ISSUE THREAD

**Issue by donnykurnia** [laravel/framework#12406]
I'm using Laravel 5.1 with Firebird database.

Whenever I get a `FatalErrorException` with stack trace, the database connection is closed and I had to get out from tinker and going in again.

Sample code to reproduce:

    vagrant@vagrant-ubuntu-trusty-64:/vagrant$ php artisan tinker
    Psy Shell v0.6.1 (PHP 5.5.9-1ubuntu4.14 — cli) by Justin Hileman
    >>> App\User::count()
    => 3
    >>> DB::table('users')->find(1);
    => {#1238
         +"id": "1",
         +"username": "xxxxx",
         +"password": "xxxxx",
         +"name": "xxxxx",
         +"phone": "123",
         +"email": "xxxxx",
         +"remember_token": "xxxxx",
         +"last_login_at": null,
         +"employee_id": null,
         +"created_at": "2015-08-31 16:22:33",
         +"updated_at": "2016-02-16 14:03:05",
         +"deleted_at": null,
       }
    >>> DB::table('users')->find(1)->title();
    PHP Fatal error:  Call to undefined method stdClass::title() in /vagrant/vendor/psy/psysh/src/Psy/ExecutionLoop/Loop.php(76) : eval()'d code on line 1
    PHP Stack trace:
    PHP   1. {main}() /vagrant/artisan:0
    PHP   2. Illuminate\Foundation\Console\Kernel->handle() /vagrant/artisan:36
    PHP   3. Symfony\Component\Console\Application->run() /vagrant/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:107
    PHP   4. Symfony\Component\Console\Application->doRun() /vagrant/vendor/symfony/console/Application.php:120
    PHP   5. Symfony\Component\Console\Application->doRunCommand() /vagrant/vendor/symfony/console/Application.php:189
    PHP   6. Illuminate\Console\Command->run() /vagrant/vendor/symfony/console/Application.php:837
    PHP   7. Symfony\Component\Console\Command\Command->run() /vagrant/vendor/laravel/framework/src/Illuminate/Console/Command.php:136
    PHP   8. Illuminate\Console\Command->execute() /vagrant/vendor/symfony/console/Command/Command.php:256
    PHP   9. Illuminate\Container\Container->call() /vagrant/vendor/laravel/framework/src/Illuminate/Console/Command.php:150
    PHP  10. call_user_func_array() /vagrant/vendor/laravel/framework/src/Illuminate/Container/Container.php:507
    PHP  11. Illuminate\Foundation\Console\TinkerCommand->fire() /vagrant/vendor/laravel/framework/src/Illuminate/Container/Container.php:507
    PHP  12. Psy\Shell->run() /vagrant/vendor/laravel/framework/src/Illuminate/Foundation/Console/TinkerCommand.php:54
    PHP  13. Symfony\Component\Console\Application->run() /vagrant/vendor/psy/psysh/src/Psy/Shell.php:283
    PHP  14. Psy\Shell->doRun() /vagrant/vendor/symfony/console/Application.php:120
    PHP  15. Psy\ExecutionLoop\ForkingLoop->run() /vagrant/vendor/psy/psysh/src/Psy/Shell.php:317
    PHP  16. Psy\ExecutionLoop\Loop->run() /vagrant/vendor/psy/psysh/src/Psy/ExecutionLoop/ForkingLoop.php:79
    PHP  17. Psy\ExecutionLoop\{closure}() /vagrant/vendor/psy/psysh/src/Psy/ExecutionLoop/Loop.php:128
    PHP  18. eval() /vagrant/vendor/psy/psysh/src/Psy/ExecutionLoop/Loop.php:76

      [Symfony\Component\Debug\Exception\FatalErrorException]
      Call to undefined method stdClass::title()

    >>> App\User::count()
    Illuminate\Database\QueryException with message 'SQLSTATE[HY000]: General error: -902 Unable to complete network request to host "192.168.2.66". Error writing data to the connection. Broken pipe  (SQL: select count(*) as aggregate from "users")'
    >>> DB::table('users')->find(1)
    Illuminate\Database\QueryException with message 'SQLSTATE[HY000]: General error: -902 Unable to complete network request to host "192.168.2.66". Error writing data to the connection. Broken pipe  (SQL: select first 1 * from "users" where "id" = 1)'

This is similar with #3842

Is there a way to reinitialize the database connection from tinker?

**Comment by GrahamCampbell** [comment]
Thanks for reporting.

**Comment by GrahamCampbell** [comment]
Please confirm that https://github.com/laravel/framework/pull/12409 works for you.

**Comment by donnykurnia** [comment]
@GrahamCampbell it works. Thanks.

**Comment by donnykurnia** [comment]
Is it possible to call reconnect() manually inside tinker?

**Comment by GrahamCampbell** [comment]
Yes.

**Comment by GrahamCampbell** [comment]
`DB::reconnect{}`.
