### ISSUE TITLE
Misunderstanding with Eloquent's `create` method - it should be static only.

### ISSUE THREAD

**Issue by taai** [laravel/framework#12417]
I just spent an hour to figure out why ```$myModel->create()``` doesn't work (no data is being stored in database table). The ```create``` is a static method. I suggest that in Eloquent it is not allowed to call ```create``` method dynamically, so there is no way to misunderstand the functionality of that method. Or fix the problem by making it possible to use that method dynamically (alias it to the ```save``` method).

Or maybe it should be written in docs with big red text, so next time you could just say RTFM... :smile:

**Comment by acasar** [comment]
Create works just fine even if you call it like you did. But you need to provide an array of data, otherwise nothing will happen.

**Comment by taai** [comment]
@acasar Yes, I understand that. But there is no point on doing that ( ```(new Car($dataThatWillBeLostAnyway))->create($request->all())``` vs ```Car::create($request->all())``` ). And in my case I want to add data that is not set as "fillable". :wink:

**Comment by EliasZ** [comment]
@taai There is a difference between passing attribute-value pairs to `create` and passing it to model instantiation.

What you are looking for is `(new Car($dataThatWillBeLostAnyway))->save()`. I think this is sufficiently covered in [the documentation](https://laravel.com/docs/5.2/eloquent#inserting-and-updating-models).

>To create a new record in the database, simply create a new model instance, set attributes on the model, then call the `save` method

and

>You may also use the `create` method to save a new model in a single line. The inserted model instance will be returned to you from the method.
