### ISSUE TITLE
Appveyor CI for Windows

### ISSUE THREAD

**Issue by barryvdh** [laravel/framework#12410]
We currently run phpunit on just Linux. It seems that Appveyor is the popular Travis alternative for Windows CI builds. Should we add that to Laravel? This would prevent edge-cases in Windows, which are not tested by most contributors..
AppVeyor is free for Open Source: https://www.appveyor.com/

See https://github.com/symfony/symfony/pull/15575 for the Symfony issue and https://github.com/symfony/symfony/blob/master/appveyor.yml / https://github.com/composer/composer/blob/master/appveyor.yml for examples

**Comment by GrahamCampbell** [comment]
Thanks for the suggestion. Feel free to take this up on slack, but I'm closing this since our GitHub issue tracker is strictly for bugs only.

**Comment by barryvdh** [comment]
Sorry, don't have the time to hang around on slack all day. Thanks anyways.

**Comment by GrahamCampbell** [comment]
Don't worry about it. I can dump this idea into there for you.
