### ISSUE TITLE
Validation: Exists - Weird behaviour

### ISSUE THREAD

**Issue by SteveEdson** [laravel/framework#12413]
In my request object I have a rule with `'shop_id' => 'required|exists:shops,id'`.

This works fine with legit values, and with incorrect numeric IDs like `12312313123`. However, when I submit a value like `2d34234`, it passes the validation and saves an ID of `2` to the database, `33werwerw34234` saves 33 etc.

Likewise, the ID `123123123d34234` fails.

I'm assuming this isn't intended behaviour?

**Comment by danieliancu** [comment]
I think the behavior is normal. You should also add the integer rule to get the behavior you want. In the current form when it reaches the exists rule it will run the query for the id which will only take integer values from the string.

**Comment by SteveEdson** [comment]
OK thanks, I assumed it would just have been a direct match. 

So using the example in the docs: `'email' => 'exists:staff,email'`, does this suddenly not only take integer values and start doing direct matches?

**Comment by danieliancu** [comment]
@SteveEdson no. Your id field accepts integer values, in the example the email field accepts text.

**Comment by SteveEdson** [comment]
@danieliancu yes, so does the validator first check what the column type is, and then start filtering the input then? Or is there a coded exception for `id` fields? Am I making sense?

**Comment by danieliancu** [comment]
@SteveEdson aha I see what you mean. I don't know, I'll look that up. I think this is done at the database level though.

**Comment by danieliancu** [comment]
@SteveEdson I don't know what database you use, but in MySQL this is expected behavior, you can test it yourself with simple SQL.

```sql
select * from users where id=1
select * from users where id='1'
select * from users where id='1a'
```
will all give the row where id=1

**Comment by SteveEdson** [comment]
Yeah MySQL. Fair enough, I never knew about that quirk, thanks for the help!
