### ISSUE TITLE
PostgresGrammar does not check if table exists in schema

### ISSUE THREAD

**Issue by thierryve** [laravel/framework#12419]
In the MySQLGrammer the method compileTableExists checks if the table exists in the configured schema. this is not the case for PostgresGrammer.

I want to use multiple schemas in one Postgresql database with migrate options but that is impossible because it will no create the migrations table if it already exists in one of the schemas.

**Comment by pelim** [comment]
I have the same Issue @thierryve you can run `php artisan migration:install` as workaround

**Comment by themsaid** [comment]
@GrahamCampbell this is fixed in https://github.com/laravel/framework/pull/13008

**Comment by GrahamCampbell** [comment]
Thanks.
