### ISSUE TITLE
Blade attempting to process 'or' keyword in ternary single quote statements

### ISSUE THREAD

**Issue by ctoma** [laravel/framework#12422]
Seems like the new or keyword is processed even when it's inside of an echo statement. Here is an example:

Works:
```{!! $someValue ? '<a href="test" target="_blank">View</a> <a href="#delete">Delete</a>' : '' !!}```

Works:
```{!! $someValue ? '<a href="test" target="_blank">View</a> orz <a href="#delete">Delete</a>' : '' !!}```

Fails:
```{!! $someValue ? '<a href="test" target="_blank">View</a> or <a href="#delete">Delete</a>' : '' !!}```

With error:

>syntax error, unexpected 'href' (T_STRING)

Because the expression gets evaluated to:

```<?php echo isset($flyer->id ? '<a href="test" target="_blank">View</a>) ? $flyer->id ? '<a href="test" target="_blank">View</a> : <a href="#delete">Delete</a>' : ''; ?>```

**Comment by arrilot** [comment]
Blade uses regular expressions, so it's syntax is limitted.
For such edge cases you need to store a string as a php variable and then echo it out with blade

**Comment by ctoma** [comment]
I wouldn't call it such an edge case, 'or' is a pretty common word

Also Fails:
```{!! $someValue ? 'Some or Something' : '' !!}```

Basically as it stands you can't use the english word or in any of your ternary statements.

**Comment by arrilot** [comment]
For reference: #10135

**Comment by GrahamCampbell** [comment]
Just use the `?:` operator.

**Comment by GrahamCampbell** [comment]
or `??`
