### ISSUE TITLE
Paginator and Bootstrap 4

### ISSUE THREAD

**Issue by kfriend** [laravel/framework#12421]
This is a "so we don't forget" issue.

Bootstrap 4 will likely change the expected markup for the pagination component, requiring additional classes added to child elements. There is no known release date for BS 4, so I'm not sure what Laravel version this would apply to :).

Bootstrap 3 expected markup:

```html
<ul class="pagination">
    <li>
        <a>
            Page number
        </a>
    </li>
    ...
</ul>
```

Bootstrap 4 Alpha 2 markup:

```html
<ul class="pagination">
    <li class="page-item">
        <a class="page-link">
           Page number
        </a>
    </li>
    ...
</ul>
```

**Comment by GrahamCampbell** [comment]
Already possible. Please ask on the forums.

**Comment by kfriend** [comment]
Not sure why this was closed. I wasn't indicating that this was a current issue, but something that will need to be dealt with in the future.

**Comment by GrahamCampbell** [comment]
It has already been dealt with in the laravel core. I can't find the original issues though to link you to them.

**Comment by kfriend** [comment]
Ok, thanks for your effort!
