### ISSUE TITLE
I can't activate sessions in Lumen

### ISSUE THREAD

**Issue by MiguelPazo** [laravel/framework#12420]
Hi, i configured my app with lumen and i want to activate sessión with db. I uncomment next lines:

$app->middleware([
    Illuminate\Session\Middleware\StartSession::class,
    Illuminate\View\Middleware\ShareErrorsFromSession::class
]);

And I added the service provider:

$app->register(Illuminate\Session\SessionServiceProvider::class);

Too add parram in .env file:
SESSION_DRIVER=database

But I get the next error:

Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\Support\Manager

Please help me! my project is versioned in github:

https://github.com/MiguelPazo/ecep_service

**Comment by rtucek** [comment]
You're using Lumen v5.2.
From this version on, views and sessions are no longer included.
[Mind release notes](https://lumen.laravel.com/docs/5.2/releases#5.2.0)

**Comment by GrahamCampbell** [comment]
Views are actually still included in lumen 5.2.

**Comment by GrahamCampbell** [comment]
They got added back in 5.2.1 or something.

**Comment by MiguelPazo** [comment]
rtucek, i change to lumen 5.0, but now i get next error:

Argument 1 passed to Illuminate\Session\Middleware\StartSession::addCookieToResponse() must be an instance of Symfony\Component\HttpFoundation\Response, string given, called in D:\xampp\htdocs\ecep_service\vendor\illuminate\session\Middleware\StartSession.php on line 72 and defined

**Comment by GrahamCampbell** [comment]
lumen 5.0 is not supported

**Comment by MiguelPazo** [comment]
Then, what version should i use?

**Comment by GrahamCampbell** [comment]
5.1.x LTS is currently supported, as is 5.2.x stable.

**Comment by MiguelPazo** [comment]
Ok, thanks you! :+1:

**Comment by maojindao55** [comment]
@GrahamCampbell what is the date of the 5.2.1 release?

**Comment by maojindao55** [comment]
@GrahamCampbell   as you said "They got added back in 5.2.1 or something.", but my lumen version is Lumen (5.2.7) (Laravel Components 5.2.*), it is the same issue `Unresolvable dependency resolving [Parameter #0 [ $app ]] in class Illuminate\Support\Manager`

**Comment by solidevolution** [comment]
Got this, too?! 

What is the special, currently undocumented way to integrate a CSRF Token Validation to an RESTful framework?!

**Comment by pirmax** [comment]
I've the same issue...

**Comment by coderiki** [comment]
I have the same issue, I using 5.8

**Comment by JacksonIV** [comment]
@coderiki Sessions are not included out of the box in Lumen 5.8.

**Comment by deyvisgc** [comment]
@coderiki lo legraste solucionar tengo el mismo error y nose como solucionarlo

**Comment by robinhood05** [comment]
Now I'm upgrading Lumen5.1 to 5.2 and getting the same issue.
"Unresolvable dependency resolving [Parameter #0 [ $app ]] in class Illuminate\Support\Manager"
How did you fix this error?
Thanks.
