### ISSUE TITLE
[5.1.30] Cache does not work within Model classes when running Unit Tests

### ISSUE THREAD

**Issue by heisian** [laravel/framework#12443]
Problem:
During unit tests, Cache neither gets nor sets when being called from within a Model class.

Cache driver: redis

Model example code:
```
<?php namespace App;
use Cache;
use Illuminate\Database\Eloquent\Model;

class MyModel extends Model
{
    protected $table = 'my_model';

    public static function boot()
    {
        parent::boot();

        MyModel::saved(function($model)
        {
            Cache::tags(['my_models'])->put($model->id, json_encode($model), 10080);
        }
    }

    public function getCachedModel($id)
    {
        return json_decode(Cache::tags(['my_models'])->get($id), true);
    }
}
```

Now if I were to run unit tests that included saving `MyModel` and calling `getCachedModel()`, no Cache interaction (getting or setting) seems to happen.

* Please note that in my situation Cache **does** work correctly when running in `dev` and `production` environments.  I only experience this problem when running **unit tests**.

**Comment by GrahamCampbell** [comment]
Boot is only run once for the entire test suite.

**Comment by GrahamCampbell** [comment]
Please ask on the forums.

**Comment by heisian** [comment]
i don't think it's a question of whether Boot runs once or multiple times during the test suite.  It's a matter of no matter where Cache is placed within the model, whether in Boot or in another method, it doesn't work in unit tests.
