### ISSUE TITLE
query builder in laravel 5.1 is confusing

### ISSUE THREAD

**Issue by jerrydev** [laravel/framework#12450]
mysql config:

mysql=>[
    'prefix' => 'hm_',
];

then, I build a sql ,like this:
DB::table('users as u')->get();

the sql will be  :

**select * from `hm_users` as `hm_u`**

Oh, I don't want to the alias name be added the prefix.....

What can I do for this?

Thanks.

**Comment by JeroenVanOort** [comment]
Where is the 'dog' in 'dog_users' coming from?

**Comment by jerrydev** [comment]
I'm sorry. dog_ prefix is my project. I copy the  toSql()  result, but forget change the prefix to the sample's prefix.

**Comment by jerrydev** [comment]
I know. This is a solution. For:

Laravel 4 :
DB::table('users as u')
    ->join('roles as r', DB::raw('r.id'), '=', DB::raw('u.role_id'))
    ->select(DB::raw('u.id'), DB::raw('u.name'), DB::raw('r.name'))
    ->get();

Lravel 5 , can write this :
DB::table('usrs as u')
    ->join('roles as r', 'r.id', '=', 'u.role_id')
    ->select('u.id', 'u.name', 'r.name')
    ->get();

We don't need to use DB::raw().
Thanks.
