### ISSUE TITLE
Feature: Better handling of schedule mutexpath files

### ISSUE THREAD

**Issue by robjbrain** [laravel/framework#12456]
At the moment the handling of the mutexpath files for scheduled commands is very limited.

If you find a mutex file in your storage directory that is a week old (for instance) it's impossible to know which command it is for for debugging purposes (it may be there legitimately, or may be a result of a command having crashed).

In order to get a list of scheduled tasks (for displaying in a dashboard for instance) you need to do the following:

```php
public function index(\Illuminate\Contracts\Console\Kernel $kernel, \Illuminate\Console\Scheduling\Schedule $schedule)
{
    $kernel->schedule($schedule);
    dd($schedule->events());
}
```

But from there there mutexpath() method is protected so there is no way to manually check existence. e.g:

```php
    $kernel->schedule($schedule);
    foreach($schedule->events() as $event) {
         dd(file_exists($event->mutexpath()));
    }
```

Would it be possible to make this more accessible and add more options for clearing/debugging stuck commands. This might involve:

- Allow access to methods such as mutexpath()
- Make mutexpath() files resolvable (find out what command they are from)
- Some means of listing currently running commands

**Comment by GrahamCampbell** [comment]
We're open to PRs. ;)
