### ISSUE TITLE
nullable timestamps not null when in $dates array

### ISSUE THREAD

**Issue by thatbignerdguy** [laravel/framework#12451]
### Issue
Timestamps that appear in a model's `$dates` array are never null. 

### Explanation

This becomes an issue when you have a timestamp that you want to check whether or not it has ever been set **and** you have a user-configurable timezone.

For example, let's say you have a field named `last_processed` on an `Example` model:
~~~
// Migration
Schema::table('examples', function(Blueprint $table) {
	// ...
	$table->timestamp('last_processed')->nullable();
});

// Class
class Example extends Model {
	// ...
	protected $dates = [ /*...*/, 'last_processed'];
	// ...
}

// Config
'timezone' => 'America/Phoenix',

// View
@if ($example->last_processed)
	{{ $example->last_processed }}
@else
	Hasn't been processed!
@endif
~~~

Now, if you have never set the `last_processed` field, you would expect the view output to be `Hasn't been processed!`, but it's actually '`-0001-11-30 00:00:00`'. This can be extremely confusing, especially when you want to distribute the same platform to multiple timezones and only have to change the configuration in one place (or even have it be user-configurable).

### Workaround
The way I've been getting around this is to have a helper function do this:
~~~
/**
 * @param $model \Illuminate\Database\Eloquent\Model The Model instance to check.
 * @param $field string The name of the field to check against.
 * @return bool True if the date has been set, false if not.
 */
function has_date($model, $field) {
    return $model->getOriginal($field) && ($model->getOriginal($field) !== '0000-00-00 00:00:00');
}
~~~

### Why Fix It?

I **love** Laravel. You open up with:
>Love beautiful code?
>We do too.

Unfortunately, having to add in a helper function to determine if a nullable field is null does not sound like beautiful code to me. :(

### My Suggestion

I'm not going to pretend to understand the inner-workings of Laravel. However, there has to come a point where it checks the items that are in the `$dates` array and then convert them into a `Carbon` object. My suggestion is simple: bypass the null fields and leave them as null.

**Comment by Wol** [comment]
What was the conclusion on this issue?

Closed after a week and no description provided!

**Comment by prototorpedo** [comment]
Laravel developers covering up the pitfalls of Carbon dating. Now that's a conspiracy!

**Comment by jeremiross** [comment]
I solved this! Under Model.php, under attributesToArray() function, it looks like they tried to catch this by setting a continue under the foreach to this:

`if (! isset($attributes[$key])) {
continue;
}`

Obviously, this will not catch an empty string.  So, slightly modifying it to this:

`if (! isset($attributes[$key]) || $attributes[$key] == "" || null == $attributes[$key]) {
continue;
}`

Will solve the problem, and I don't think this deviates too much from the intent of the framework in this spot.
