### ISSUE TITLE
illuminate/database not working

### ISSUE THREAD

**Issue by dzona** [laravel/framework#12460]
I use ``"illuminate/database": "5.2.7"`` PHP version ``7.0.0-dev`` and  Slim3 ``v3.1``

capsule component registration in container

```
//database
$container['capsule'] = function ($c) {
    $capsule = new Illuminate\Database\Capsule\Manager;
    $capsule->addConnection($c->get('settings')['db']);
    return $capsule;
};
```

register script

````
$capsule = $app->getContainer()->get('capsule');
$capsule->bootEloquent();

$app->run();
````

If I do something like this, anywhere in code

````
$model = new App\Models\Version();
$model->name = 'some name';
$model->save();
````

I get internal server error, with no trace

While 
````
$model = Version::find(1);
````
does create proper model, with attributes set

**Comment by GrahamCampbell** [comment]
> I get internal server error, with no trace

Please tell us the actual error.

**Comment by GrahamCampbell** [comment]
If it's a white screen, it's likely a php bug. Try upgrading to php 7.0.3.
