### ISSUE TITLE
Eloquent ORM - How to use SQL_CALC_FOUND_ROWS

### ISSUE THREAD

**Issue by msieprawski** [laravel/framework#12469]
Hey,

Let's say that I've got following code:
```php
$users = User::select(['users.id'])
    ->leftJoin('posts', 'users.id', '=', 'posts.author_id')
    ->skip(15)
    ->take(15)
    ->get();
```
And I want to count all available rows (ignoring the limit) so I want to add SQL_CALC_FOUND_ROWS. However when I add it to the select:
```php
$users = User::select([DB::raw('SQL_CALC_FOUND_ROWS'), 'users.id'])
    ->leftJoin('posts', 'users.id', '=', 'posts.author_id')
    ->skip(15)
    ->take(15)
    ->get();
```
Laravel adds "," between columns so it ends with invalid query. Is there any way to mix SQL_CALC_FOUND_ROWS with selected columns? Please advice.

I know that I could use just count statement. But in this specific example I'd rather use SQL_CALC_FOUND_ROWS.

Thanks!

**Comment by JayBizzle** [comment]
This?

```php
$users = User::select([DB::raw('SQL_CALC_FOUND_ROWS users.id')])
    ->leftJoin('posts', 'users.id', '=', 'posts.author_id')
    ->skip(15)
    ->take(15)
    ->get();
```

**Comment by msieprawski** [comment]
Well... KISS. That's a good approach, however I thought that there is a "cleaner" way to do it :)
Anyway, thanks! That worked of course.
