### ISSUE TITLE
Don't rely on helpers (except in user code)

### ISSUE THREAD

**Issue by skyrpex** [laravel/framework#12475]
Laravel helper functions are awesome, but there's a chance that they aren't defined at all (if there's already a function with that name, for example). If that occurs, the framework and packages relying on those helpers won't work, leading to unexpected errors...

My suggestion is to move all the helper code into class helpers, and use those classes inside the laravel source and laravel packages.

The array helper methods were moved to the Illuminate\Support\Arr class, that's nice! Same with the string helpers. But data_get helper is used in Illuminate\Support\Collection, for example...

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. I think our current situation is ok, but if there are any specific cases you are worried about, please do send a PR. That data get thing could be a contender by the sound of it.
