### ISSUE TITLE
NotFoundHttpException duplicate reporting

### ISSUE THREAD

**Issue by coderjeff** [laravel/framework#12477]
I’m trying to write urls resulting in 404 errors to the log.

I’ve added this code to app/Exceptions/Handler.php and it seems to work, but every error is written to the log twice.
```
	public function report(Exception $e)
	{
		if ($e instanceof \Symfony\Component\HttpKernel\Exception\NotFoundHttpException) {
			\Log::info( '404 error: ' . \Request::fullUrl() );
		}

		return parent::report($e);
	}
```

**Comment by GrahamCampbell** [comment]
Of course it is? Your logging it, then you're passing it to the parent who is also logging it.

**Comment by coderjeff** [comment]
So how about being useful instead of a jerk and tell me how to fix it?

If I comment out the parent call or return after I write to the log it still logs it twice.

**Comment by GrahamCampbell** [comment]
> So how about being useful instead of a jerk and tell me how to fix it?

This is not a support forum.

> If I comment out the parent call or return after I write to the log it still logs it twice.

That's probably because the old file was still getting run because it was either "compiled" or "cached" by php in memory.

**Comment by coderjeff** [comment]
I apologize for asking, but don't know where else to ask.  I've tried Larachat on Slack and the Laracasts forum.

If I deploy this via Forge
   ```
    public function report(Exception $e)
    {
        if ($e instanceof \Symfony\Component\HttpKernel\Exception\NotFoundHttpException)
            \Log::info( '404 error: ' . \Request::fullUrl() );
        else
            return parent::report($e);
    }
```
the "404 errror..." message is written to the log twice.

**Comment by GrahamCampbell** [comment]
Please continue on the forums.
