### ISSUE TITLE
Cache miss is fired if Cache::has($key) returns false

### ISSUE THREAD

**Issue by shahidnajam** [laravel/framework#12474]
As for me, Cache miss means if a key exist on the server and was stored previously but retrieved value is null for any reason.
But If key/value is not stored previously or expired so we get from DB and store it in cache for next request. but that doesn't mean cache is missed.
For example

`if ($this->_cache->has($key)) {`
`    // Get from cache`
`    $this->_cache->get($key);`
`} else {`
`    // Get from DB`
`}`

Considering code from above, If cache is not previously stored,  We get it from database and store it in the cache for next request. 
But in this case **Illuminate\Cache\Events\CacheMissed** will be fired **if ($this->_cache->has($key))** condition is false. But this is bad behavior.

In vendor/laravel/framework/src/Illuminate/Cache/Repository.php

`/**`
`* Determine if an item exists in the cache.`
`*`
`* @param  string  $key`
`* @return bool`
`*/`
`public function has($key)`
`{`
`    return ! is_null($this->get($key));`
`}`

In above block of code from Laravel framework, has($key) will fire cache miss event if returned value is false.

**Correct behavior of Cache miss should be**

if Cache::has('test') is **true** but Cache::get('test') is **null**

It would be nice if cache miss should like that.

**Comment by xavadu** [comment]
It would be good that _$cache->has()_ don't fire the _cache missed event_ if the key don't exists

**Comment by squigg** [comment]
The fact you looked for the data in the Cache (whether by `has` or `get` is irrelevant, you still wanted data with a certain key) and it wasn't there, that's a miss. All `has` does is look and see if `get` is null, therefore it has attempted to retrieve the data and missed.

There's no other way of doing it as not every implementation of a Cache will have a separate method to check for existence of a key before obtaining the data. By definition this would require a round-trip to the Cache, which is inefficient and in some cases defeats the primary purpose of using a Cache.

You should really just treat your Cache misses as an indicator to monitor, not as an error condition.

**Comment by GrahamCampbell** [comment]
Doesn't look like a bug to me.

**Comment by GrahamCampbell** [comment]
You did miss the cache.

**Comment by xavadu** [comment]
Nope, isn't a bug could be a improvement but i understand that is hard to implement and could  have some architecture discussion, on my opinion _$cache->has()_ should be removed,  on that case the cache missed event don't make sense.
