### ISSUE TITLE
Hardcoded values for Mailgun service

### ISSUE THREAD

**Issue by ludo237** [laravel/framework#12480]
Hello everyone.

I don't know if this is the right place to open this issue because it's not strictly related to the framework itself.

The problem basically is that if you use the `mandrill` driver inside your `config/mail.php` you have to hardcode the `domain` and `secret` values inside the `mailgun` array in `config/services.php` like this:

```PHP
    "mailgun"  => [
        "domain" => "foo.bar",
        "secret" => "key-kappa123-4567890",
    ],
```

If you try to use the

**Comment by GrahamCampbell** [comment]
No you don't?

**Comment by GrahamCampbell** [comment]
I suggest you seek help on the forums.
