### ISSUE TITLE
[5.2] FilesystemAdapter->append() & prepend() incorrectly add an EOL

### ISSUE THREAD

**Issue by doctor-beat** [laravel/framework#12498]
Refers to branch 5.2.

See these tests:
` 
    public function testAppendAddsDataToFile()
    {
        file_put_contents(__DIR__.'/file.txt', 'foo');
        $files = new FilesystemAdapter(
            new Flysystem(
                new LocalAdapter('/', LOCK_EX, LocalAdapter::DISALLOW_LINKS, []), 
                null
            )
        );
        $bytesWritten = $files->append(__DIR__.'/file.txt', 'bar');
        $this->assertEquals(mb_strlen('bar', '8bit'), $bytesWritten);
        $this->assertFileExists(__DIR__.'/file.txt');
        $this->assertStringEqualsFile(__DIR__.'/file.txt', 'foobar');
        @unlink(__DIR__.'/file.txt');
    }
    public function testPrependExistingFiles()
    {
        $files = new FilesystemAdapter(
            new Flysystem(
                new LocalAdapter('/', LOCK_EX, LocalAdapter::DISALLOW_LINKS, []), 
                null
            )
        );
        $files->put(__DIR__.'/file.txt', 'World');
        $files->prepend(__DIR__.'/file.txt', 'Hello ');
        $this->assertStringEqualsFile(__DIR__.'/file.txt', 'Hello World');
        @unlink(__DIR__.'/file.txt');
    }
`

To solve this we must either change the default value for the seperator param to null (which breaks existing functionality!) or add this parameter to the Illuminate\Contracts\Filesystem\Filesystem (where it is now sadly missing)

**Comment by GrahamCampbell** [comment]
I don't see an issue?

**Comment by doctor-beat** [comment]
Yes, there is an issue: the test fails.
And having unasked for EOL's added to the file is unwanted, i suppose.

**Comment by doctor-beat** [comment]
Please re-open

**Comment by GrahamCampbell** [comment]
You just need to manually pass a 2nd param if you don't like the default.

**Comment by doctor-beat** [comment]
True, but that extra parameter is not defined in the interface.
