### ISSUE TITLE
[5.2] Cannot mock request for testing

### ISSUE THREAD

**Issue by at-vienlm** [laravel/framework#12496]
When I mock request for testing in Laravel 5.2 
```
Request::shouldReceive('input')
            ->once()
            ->andReturn(['key' => 'value']);
```
I got this error:
 `BadMethodCallException: Method Mockery_0_Illuminate_Http_Request::setUserResolver() does not exist on this mock object`.
I already disable Middleware in my test class. 

Is it bug or my code is wrong ?
Please help, thanks

**Comment by GrahamCampbell** [comment]
setUserResolver is getting called on the request by laravel, so your mock is insufficient.

I wouldn't recommend mocking this class anyway.

**Comment by ian-nisbet** [comment]
Not ideal, but works:
`    protected function createRequest(
        $method,
        $content,
        $uri = '/test',
        $server = ['CONTENT_TYPE' => 'application/json'],
        $parameters = [],
        $cookies = [],
        $files = []
    ) {
        $request = new \Illuminate\Http\Request;
        return $request->createFromBase(
            \Symfony\Component\HttpFoundation\Request::create(
                $uri,
                $method,
                $parameters,
                $cookies,
                $files,
                $server,
                $content
            )
        );
    }`
