### ISSUE TITLE
[5.3] Change back preg_replace_sub() to preg_replace_array()

### ISSUE THREAD

**Issue by vlakoff** [laravel/framework#12495]
In support helpers, for consistency with `str_replace_array()`, `preg_replace_sub()` should be renamed back to `preg_replace_array()`, and the reference removed as the user probably doesn't expect it.

Basically, it's about reverting https://github.com/laravel/framework/commit/e87c219d66f93ce48b8644482bd7d0381f290546.

History of this helper:
* added in https://github.com/laravel/framework/commit/d9b3fd47ab32383e3ccae632a86dbd5993772aac
* then modified in https://github.com/laravel/framework/commit/e87c219d66f93ce48b8644482bd7d0381f290546
* then used in https://github.com/laravel/framework/commit/42012bf3bd25c451e30f771ecf98ff56eb67bb5e
* then unused in https://github.com/laravel/framework/commit/cef79d827cc8024ba5c5295adff4e0efafcf4455

<br>(on a related note, refs recent changes about `str_replace_array()`: #12259)

**Comment by vlakoff** [comment]
On another related note, this function should be fixed to leave intact the rest of the matches if the $replacements array has fewer items than the number of matches.

**Comment by vlakoff** [comment]
Another option could be to deprecate/remove these functions if you think they are not worth it. Thoughts?

**Comment by GrahamCampbell** [comment]
We're open to PRs. ;)
