### ISSUE TITLE
MySQL on update current_timestamp

### ISSUE THREAD

**Issue by a-komarev** [laravel/framework#12490]
There is a way to create column `CURRENT_TIMESTAMP` using `useCurrent()` method but not the `CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`.

It's available to set default value as raw DB value:

``` php
$table->timestamp('created_at')->default(DB::raw('CURRENT_TIMESTAMP'));
$table->timestamp('updated_at')->default(DB::raw('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'));
```

But in this case there would be an issue with using SQLite database in unit tests, because there is no support of `ON UPDATE` in it.

The only way I found recently is what @terdelyi described in issue #12060 

> If the first TIMESTAMP column in a table is not specified as NULLable and doesn't have explicit DEFAULT or ON UPDATE value specified, it automatically gets DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP as attributes.

So you can swap `created_at` and `updated_at` columns and receive the hacky solution.

``` php
$table->timestamp('updated_at');
$table->timestamp('created_at')->useCurrent();
```

Will produce:

``` sql
`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
```

I understand that Eloquent is responsive to manage timestamp columns correct values and there were said enough to use `nullable()` and `nullableTimestamps()` but what do you think about adding one more method to set default `CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP` to timestamp columns?

There could be situations when there is a need to create such column, but there would be problems with testing :( And rely on hacky way to solve such task isn't so obvious and could bring mistakes in future.

**Comment by jonahpatriarche** [comment]
I would very much like to have this feature. Or a fix for $table->timestamps that produces the correct created_at and updated_at behaviour.

**Comment by reatang** [comment]
I also met the same problem, I hope to add a `useUpdate()` parameters on time column

**Comment by themsaid** [comment]
Since this is an old issue and there doesn't seem to be any steps to take regarding it I'm going to close it, but please feel free to propose any changes by opening a Pull Request or use the laravel/internals repository to post a proposal.

Thanks.
