### ISSUE TITLE
Add dispatchNow to DisptachesJob Trait

### ISSUE THREAD

**Issue by rodrigopedra** [laravel/framework#12501]
Can we add the  `dispatchNow()` method to the `DispatchesJob` trait? I have some jobs that I queue while on http, but process them in sync while doing batch processing (through console commands). 

It would be convenient to have both methods in the trait but I am afraid of increasing confusion adding more options to it.

If it is ok, I can write a PR for that.

**Comment by GrahamCampbell** [comment]
Sorry, 5.1 is closed for changes, and 5.2 doesn't have this content anymore.

**Comment by rodrigopedra** [comment]
From 5.2 codebase:

Trait:
https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Bus/DispatchesJobs.php

Contract:
https://github.com/laravel/framework/blob/5.2/src/Illuminate/Contracts/Bus/Dispatcher.php#L15-L23

Implementation:
https://github.com/laravel/framework/blob/5.2/src/Illuminate/Bus/Dispatcher.php#L73-L84

**Comment by GrahamCampbell** [comment]
Oh, sorry. I got confused with the self handling stuff that got removed.

**Comment by GrahamCampbell** [comment]
Feel free to send a PR then. In future, please don't create an issue first, as per our contribution guidelines.

**Comment by rodrigopedra** [comment]
No problem, I'll do that. Thanks
