### ISSUE TITLE
[Question] Container afterResolving vs resolving callback

### ISSUE THREAD

**Issue by mark86092** [laravel/framework#12508]
The `afterResolving` and `resolving` function store their callback in different array, and the callbacks are fired when container resolves.

But in function `fireResolvingCallbacks`, which is called by `make`, the resovling callbacks and afterResolving callbacks seem no different.
Two types of callbacks are fired only in `fireResolvingCallbacks`.

```php
    protected function fireResolvingCallbacks($abstract, $object)
    {
        $this->fireCallbackArray($object, $this->globalResolvingCallbacks);
        $this->fireCallbackArray(
            $object, $this->getCallbacksForType(
                $abstract, $object, $this->resolvingCallbacks
            )
        );
        $this->fireCallbackArray($object, $this->globalAfterResolvingCallbacks);
        $this->fireCallbackArray(
            $object, $this->getCallbacksForType(
                $abstract, $object, $this->afterResolvingCallbacks
            )
        );
    }
```

What is the purpose separating `resolving` and `afterResolving`?

**Comment by GrahamCampbell** [comment]
Please ask questions on the forums.

**Comment by mark86092** [comment]
@GrahamCampbell I don't know what is the better title.
The issue is that it seems nothing different between `resolving` and `afterResolving`. The term imply two should trigger in different scenario (or different time).
