### ISSUE TITLE
Follow the same pattern to register route resource as middleware controller

### ISSUE THREAD

**Issue by socieboy** [laravel/framework#12511]
I notice there was a update for controller middleware to exclude or define witch methods would apply the middleware.
```
public function __construct()
{
    $this->middleware('auth', ['only' => 'index']); // Before
    $this->middleware('auth')->only('index'); // Now 
}
```
I think now looks pretty good!
We should do the same for the Route::resource.
```
Route::resource('posts', 'PostController')->only('index', 'store', 'show');
```
instead of
```
Route::resource('posts', 'PostController', ['only' => 'index', 'store', 'show'])
```
I will try to send a PR but before do it! I would like to heard what do you think about that?

**Comment by lagbox** [comment]
By the time `Route::resource` has finished the ResourceRegistrar has already registered those routes.  There is currently nothing of use to return from `Router@resource` or `ResourceRegistrar@register`.

What were you think of as a plan of attack? At first glance I can't see a direct way to go at this, unless we are altering routes that are already registered or some how holding these as a resource (which the router doesn't really have a concept of) and have the router check for 'unregistered'(open) resources at some point and register them.
