### ISSUE TITLE
"replace" Eloquent queries

### ISSUE THREAD

**Issue by jdavidbakr** [laravel/framework#12510]
I've been running into this issue a lot, and this is kind of a stem off of https://github.com/laravel/framework/pull/12059, but it would be really nice to have the ability to perform replace queries via eloquent.  I know you can do it with DB::Raw(), but if you are using insert() with a large array of values where one happens to be a duplicate - but you don't care, you want it to replace it anyway - there really isn't a very easy way to accomplish this.  Further, the Session database driver could use replace instead of insert to fix the issue of the duplicate key error quite easily.

This is my biggest pain point with using Laravel (the session issue is killing me, now I'm on 5.1 because I don't have time to update and test 5.2, but also have a lot of code that I currently have a delete(); insert() pair that, due to quick firing ajax calls, gets caught in a race condition too often.)

**Comment by w4** [comment]
[REPLACE is a MySQL extension, it's not actually a valid SQL statement in the defined standards](https://en.wikipedia.org/wiki/Data_manipulation_language)

**Comment by jdavidbakr** [comment]
Hm, well, I would love to know what the solution should be to accomplish what is a REPLACE query in MySQL.

Because of possible rapid ajax calls, I am getting frequent duplicate key errors in both of the following cases:

```
// This model has a unique constrant between user_id and widget_id

Model::updateOrCreate(['user_id'=>$id, 'widget_id'=>$id]);
```

or...

```
$inserts[] = ['user_id'=>1,'widget_id'=>2];
$inserts[] = ['user_id'=>1,'widget_id'=>4];
...
$inserts[] = ['user_id'=>1,'widget_id'=>n];
Model::whereIn('user_id',$inserts->pluck('user_id'))->delete();
Model::insert($inserts);
```

The best I've come up with is to wrap the updateOrCreate() and insert() calls in a try/catch, but that is cumbersome.  If I was writing raw MySQL I would use REPLACE.

**Comment by w4** [comment]
There's [upsert](https://en.wikipedia.org/wiki/Merge_(SQL))

**Comment by jdavidbakr** [comment]
For others who are having this issue, I have released a package that is just a trait you can apply to your Eloquent models that give you REPLACE and INSERT IGNORE queries where you can currently do insert() queries.  The package is here: https://packagist.org/packages/jdavidbakr/replaceable-model

**Comment by jdavidbakr** [comment]
I'm going to close this issue because I understand why it's not included in Eloquent, my package should solve the problem I was having.

**Comment by jfoliveira** [comment]
@jdavidbakr thanks for this package!

**Comment by driade** [comment]
@jdavidbakr Thanks for the package. As for your comment on "frequent duplicate key errors", why don't you use transactions?

**Comment by jdavidbakr** [comment]
@driade - I did try transactions but ended up getting frequent deadlocks.

**Comment by iambyar** [comment]
My problem is same, Try this dude :

Variable::truncate();
Variable::create(['name' => $variable]);

then my problem has been successed, Good Luck dude!
