### ISSUE TITLE
allow setting of / or move location of bootstrap/cache

### ISSUE THREAD

**Issue by leemason** [laravel/framework#12526]
right now, we need to make /storage AND boostrap/cache folders writable for usage by the framework.

This is fine (a little annoying) for none distributed applications, but when building something for others to consume this is just added complexity which isnt really desired.

I know the config/services cache has moved a few times already, but doesnt it make sense to just have 1 writeable folder for the framework? 

theres two parts to this issue:

1. can i request a method to "set" the config cache path on the application class so i can update it in the bootstrap/app.php file (without needing to extend the class) before the apps passed to a kernel.

2. as a proposal for v5.3 can i suggest the current /boostrap/cache/* files are moved to /storage/bootstrap/* for consistency. this would mean only 1 folder needs write permissions, simpler and more secure.

**Comment by GrahamCampbell** [comment]
We already moved them out of there for consistency.

**Comment by GrahamCampbell** [comment]
This is useful when deploying with zero-downtime.

**Comment by winminsoe** [comment]
Isn't still using it under bootstrap/cache folder? I also come up to this situation when my app is only readable state and have to move out of from app root. 

https://github.com/laravel/framework/blob/eb3b472ae8032c2832fb7476f0319ad62aca8ace/src/Illuminate/Foundation/Application.php#L857

**Comment by hlorofos** [comment]
confirmed, its still under bootstrap/cache in 5.3 and 5.4 versions

**Comment by joeyhub** [comment]
If you symlink then weird things seem to happen as well.

**Comment by adamcameron** [comment]
I hate to drag-up an old issue, but seems to me it was erroneously closed in the first place, given this statement "We already moved them out of there for consistency." doesn't seem to be correct? Certainly my Laravel 8 install still needs to write to `bootstrap/cache`.

Am currently looking at what I need to override to be able to move that, as it's a non-starter for me.

It's pretty poor form to be writing files to an application directory IMO, so would prefer to be able to shift this to something in the `/var` directory or some other more appropriate place.

At the very least all writeable directories should be located in the one subdirectory structure, surely (like the `storage` one you also default to being within the application code's directory structure)?

I guess it's fine to _default_ to having writeable dirs in an application directory (not really, but hey, it is what it is), but it'd be great to be able to move it when server security policies are such that "code directories are read only".

**Comment by nul0op** [comment]
If you want to keep things clean on a laravel docker rollout, adamcameron's solution does the job and you only have one "runtime" folder to manage. neat and clean.
