### ISSUE TITLE
Dependency injection service providers not working

### ISSUE THREAD

**Issue by mallinus** [laravel/framework#12523]
https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/ProviderRepository.php#L146

It seems that the initialisation of service providers is not designed to allow for dependency injection via the container. Is there a specific reason to this?

I can PR a fix if necessary.

**Comment by mallinus** [comment]
To add a context, I'm currently building a package that registers routes in its service provider and I'm DI the Registrar contract in the constructor, which is not working for obvious reasons.

**Comment by GrahamCampbell** [comment]
We don't expect people to want to resolve service providers themselves out of the container.

**Comment by mallinus** [comment]
What is the correct way of dependency injecting service providers?

![](http://i.imgur.com/DwUNO98.png)

**Comment by mallinus** [comment]
@GrahamCampbell Any news?

**Comment by lagbox** [comment]
@mallinus I would say that you don't. You can typehint on the `boot` method that is called after all providers have registered their bindings and will get dep injections.

[Docs - Providers - Boot method](https://laravel.com/docs/5.2/providers#the-boot-method)
