### ISSUE TITLE
Misbehavior after updating

### ISSUE THREAD

**Issue by salarmehr** [laravel/framework#12522]
The `$results = User::select(['id', DB::raw('concat(firstName," ",lastName) as fullName')])` was working, but after a recent update it returns empty string for `fullName`. I have to change it to `$results = User::select(['id','firstName','lastName', DB::raw('concat(firstName," ",lastName) as fullName')])` to work.

**Comment by GrahamCampbell** [comment]
> Misbehavior after updating

?

**Comment by salarmehr** [comment]
`User::select(['id', DB::raw('concat(firstName," ",lastName) as fullName')])` returns empty strings for `fullName` in the last version. Does it work for you?

**Comment by GrahamCampbell** [comment]
> in the last version

?

**Comment by salarmehr** [comment]
@GrahamCampbell  My current version is 5.2.22. I do not know the exact version that the issue appeared afterward. I had  several updates before I found out about the bug.

**Comment by GrahamCampbell** [comment]
> I do not know the exact version that the issue appeared afterward

Please can you find out then.

**Comment by salarmehr** [comment]
The issue  appears in Laravel Framework version 5.2.39 yet. Have it fixed in 5.3?

**Comment by GrahamCampbell** [comment]
Closed pending a response. Please provide the exact patch versions this broke between.

**Comment by salarmehr** [comment]
5.2.21, I guess.

**Comment by GrahamCampbell** [comment]
5.2.21 -> 5.2.22?

**Comment by GrahamCampbell** [comment]
Please can you confirm this, and suggest a possible cause?

**Comment by GrahamCampbell** [comment]
Maybe I should explain better, these issues are here for the community. They're not support. We expect people to investigate their own issues as far as possible. GitHub issues just allow people to communicate.

**Comment by salarmehr** [comment]
I will try to investigate that as soon as possible. I agree with your last comment. However, if there is a bug and the bug reporter for some reason cannot provide more information, I think the issue should be kept open. Closing the issue does not fix that bug! Thanks for your time.

**Comment by GrahamCampbell** [comment]
I closed it after 6 months of inactivity.

**Comment by themsaid** [comment]
This query:

```php
User::select(DB::raw('concat(first," ",last) as fullName'))->get();
```

It works for me on a fresh 5.3 installation, 5.2.21, 5.2.22, and 5.2 latest.

The response contains a model with the following attributes:

```
#attributes: array:1 [▼
        "fullName" => "Beric Dondarrion"
      ]
```

Closing this since the issue cannot be replicated as well as lack of activity, please feel free to ping me if you're still facing such issue using the latest 5.2 release or 5.3.

**Comment by salarmehr** [comment]
@themsaid I has the attribute but when you apply `toArray()` the full name will vanish. 

try this: `dd(User::select([DB::raw('concat(firstName," ",lastName) as fullName')])->limit(2)->get()->toArray());`
