### ISSUE TITLE
Support to aws aurora

### ISSUE THREAD

**Issue by paulocastellano** [laravel/framework#12525]
Hello,

We will have support to aws aurora db?

**Comment by GrahamCampbell** [comment]
Not planned, sorry.

**Comment by csoseman** [comment]
@paulocastellano. I just did some reading on this page and came across your question. According the https://aws.amazon.com/rds/aurora/, Aurora is fully compatible with MySQL 5.6 (as long as you're using InnoDB as a storage engine). From the article it looked like, aside from the connection parameters, all of the commands are the same. Seriously considering moving towards Aurora but have yet to test it out. If you do make the switch, please let us know what you find!

**Comment by the907** [comment]
@paulocastellano  - How did this turn out for you? 

cc: @csoseman
