### ISSUE TITLE
Model.php bootTraits triggering Maximum function nesting level

### ISSUE THREAD

**Issue by alexsup** [laravel/framework#12536]
When I use the bootTraits method it triggers the following error `PHP Fatal error:  Maximum function nesting level of '512' reached, aborting!`

I'm running Laravel 5.2 on Homestead.

**Comment by GrahamCampbell** [comment]
What version please?

**Comment by GrahamCampbell** [comment]
> When I use the bootTraits method

In what context are you calling it?

**Comment by alexsup** [comment]
Hi @GrahamCampbell  :)

It's 5.2.22.

It's actually this: this https://laracasts.com/lessons/build-an-activity-feed-in-laravel-part-2.

I'm recording user activity.


```
namespace App\Traits;

use App\Activity;
use ReflectionClass;

trait RecordsActivityTrait
{
	protected static function boot()
	{
		parent::boot();

		foreach (static::getModelEvents() as $event) {
			
			static::$event(function($model) use($event) {
				$model->recordActivity($event);
			});

		}
	}

	public function recordActivity($event)
	{
		Activity::create([
			'activity_id' => $this->id,
			'activity_type' => get_class($this) ,
			'name' => $this->getActivityName($this,$event),
			'user_id' => $this->user_id
		]);
	}

	protected function getActivityName($model, $action)
	{
		$name = strtolower((new \ReflectionClass($model))->getShortName());

		return "{$action}_{$name}";
	}

	protected static function getModelEvents()
	{
		return [
			'created',
			'deleted'
		];
	}
}
```

Thanks!

AB

**Comment by GrahamCampbell** [comment]
You can't have a trait with a boot method in it. It's reserved for the model only.

**Comment by GrahamCampbell** [comment]
Rename the method to `bootRecordsActivityTrait()` and drop the parent call.

**Comment by alexsup** [comment]
@GrahamCampbell Yep, I was being an idiot. 

Referencing the parent call was causing a loop of death.

Thanks!

AB
