### ISSUE TITLE
[5.2] Global scope "select" not applied

### ISSUE THREAD

**Issue by vlakoff** [laravel/framework#12530]
Encountering this failing test, Laravel 5.2.22. I don't know why Travis CI doesn't get it.
```
1) DatabaseEloquentGlobalScopesTest::testGlobalScopesWithOrWhereConditionsAreNested
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'select "email", "password" from "table" where ("col1" = ? or "col2" = ?) and ("email" = ? or "email" = ?) and "active" = ? order by "name" asc'
+'select * from "table" where ("col1" = ? or "col2" = ?) and ("email" = ? or "email" = ?) and "active" = ? order by "name" asc'

...\tests\Database\DatabaseEloquentGlobalScopesTest.php:80
```
ping @acasar

**Comment by vlakoff** [comment]
Found the cause: in `Eloquent\Model::addGlobalScope`, `uniqid('scope')` gives me the same result twice, so the previous entry in `static::$globalScopes` gets overwritten. Looks like this function has a very bad entropy, especially on some platforms.

**Comment by vlakoff** [comment]
By the way, maybe it would be better to typehint `$implementation` as callable rather than closure?
If so, in what branch should it go?

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell/

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell.

**Comment by vlakoff** [comment]
Submitted a fix for this issue: #12532.

Thoughts about the `$implementation` typehint?

**Comment by acasar** [comment]
@vlakoff Regarding typehints... I think there was once a discussion to replace most of the Closure type-hints with callable for 5.3. I think @GrahamCampbell was thinking about preparing a PR? I'm not sure :)

In this particular case I think it would be nice, but would probably also need to update how scopes are applied: https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/Builder.php#L1095

**Comment by GrahamCampbell** [comment]
> I think @GrahamCampbell was thinking about preparing a PR?

No.

**Comment by acasar** [comment]
My bad :) Probably someone else then.

**Comment by timgws** [comment]
This issue can be closed. A patch was applied in #12532
