### ISSUE TITLE
Service container singleton binding problem

### ISSUE THREAD

**Issue by andaril** [laravel/framework#12543]
I have strange behavior with Service Container. I'm binding singleton with 
```php
$this->app->singleton('service.content', \App\Services\ContentService::class);
```
In php 5.5 all fine. 

But in 5.6 this returns error `'ErrorException' with message 'Class ContentService does not exist` on `app('service.content')` calls. 

Solved by rewriting all to `app('ContentService')` and binding to 
```php
        $this->app->singleton('ContentService', function($app) {
            return new \App\Services\ContentService();
        });
```
But, is it ok?

Laravel v5.1.29

**Comment by GrahamCampbell** [comment]
$this->app->singleton('ContentService', function($app) { needs to be either ContentService::class or App\Services\ContentService.

**Comment by GrahamCampbell** [comment]
I can't replicate any issues of this nature.

**Comment by GrahamCampbell** [comment]
> Solved by rewriting all to app('ContentService') and binding to

That's not a solution since that class doesn't exist either, so it's no different to naming it `service.content` and calling app('service.content').

**Comment by andaril** [comment]
This was my bad.

View cache in production doesn't updated since changes in blade directives. Deploy script rewrited to clean caches.
