### ISSUE TITLE
Polymorphic relations error in SQLite

### ISSUE THREAD

**Issue by johnnymn** [laravel/framework#12544]
Encountered the following issue: when I create the necessary fields for a polymorphic relation using the Blueprint api, eg:

        Schema::create('warehouses', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->text('address');
            $table->string('city');
            $table->string('state');
            $table->string('country');
            $table->morphs('ownable'); // POLY FIELDS
            $table->timestamps();
        });

I get an inconsistent result in SQLite because the resultant  `ownable_type` and `ownable_id`  fields are NOT NULL, but if I run the same migration against a Postgresql or Mysql database the fields are NULLABLE.

**Comment by sebestenyb** [comment]
Same issue here, running the code below in unit tests (SQLite) fails, while using MySQL it works:

```
Schema::create('contents', function (Blueprint $table) {
    $table->increments('id');
    $table->morphs('contentable');
    $table->timestamps();
});

...

$content = factory(Content::class)->create(['node_id' => $node['id']]);
$comment = factory(Comment::class)->create();
$comment->content()->save($content);

PDOException: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: contents.contentable_type
```

**Comment by sebestenyb** [comment]
Hi Graham, is it closed as "Fixed", or "Won't fix"?

**Comment by GrahamCampbell** [comment]
It looks like a no-fix to me. I'm not entirely sure though.
