### ISSUE TITLE
[5.2] ResourceRegistrar changes and packages

### ISSUE THREAD

**Issue by lagbox** [laravel/framework#12549]
There is a possible issue here with this feature and any package that is relying on parameter names to be what they are expected to be (default).

At the moment to keep this resource feature (global parameter state and mapping), one would be required to reset the parameter settings before packages register their routes. (If a package was relying on the consistency of these parameter names, ex: implicit binding or explicit bindings).

Without removing this feature, we would need to add another method to the Router that would reset all these parameters and could add this call after the main routes have been mapped.

`Route::resetResourceParameters()` or something to that degree, or even to stash them to reapply them again later.

This probably hasn't come up as an issue yet, because majority of people use resource names in the singular already out of habit because of the default behavior, or the pacakges aren't using any resouce names that are globally mapped (in the base app) or plural when the user has set them singular globally.

@taylorotwell

**Comment by GrahamCampbell** [comment]
Thanks. Feel free to discuss on the internals repo, or on slack. :)
