### ISSUE TITLE
verifyCsrfToken occurs too frequently

### ISSUE THREAD

**Issue by dhiman252** [laravel/framework#12552]
Hi Team ,

I am using the laravel v5.1 and facing the problem of verifyCsrfToken exception too frequently.

Sometimes the form gets submits and sometimes not.

Not able to figure out what the exact problem is, it happens on both the OS: Windows, Linux

On windows I am using the Wampserver and on linux I am using the Xampp.

Following is my session.php file configuration
`[
'driver' => env('SESSION_DRIVER', 'file'),

'lifetime' => 120,

'expire_on_close' => true,

'encrypt' => false,

'files' => storage_path('framework/sessions'),

'table' => 'sessions',

'lottery' => [2, 100],

'cookie' => 'proj_org',

'path' => '/',

'domain' => null,

'secure' => false,

 ]`

Also I am using the following lines in my view file app.blade.php

`<?php

    header("Expires: Mon, 26 Jul 1997 05:00:00 GMT"); 

    header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");

    header("Cache-Control: no-store, no-cache, must-revalidate");

    header("Cache-Control: post-check=0, pre-check=0", false);

    header("Pragma: no-cache");
?>`

Form submission sometimes work and sometimes not.

**Comment by GrahamCampbell** [comment]
NEVER use the native header functions. The'll break everything.

**Comment by dhiman252** [comment]
Hi GrahamCampbell,

Well thanks for the advice, i also figured out one more thing which i want to share with you.
I was working with the file upload control and i was uploading a file with the size 15MB, and in my wamp settings i have 

```
post_max_size = 2M;
upload_max_filesize = 3M;
```
With these settings uploading a file gives a VerifyCrsfToken exception.

Now what is the best way in laravel 5.1 to stop browser cache like used the native header functions ?
