### ISSUE TITLE
getting error while running forms.

### ISSUE THREAD

**Issue by Shahroon900** [laravel/framework#12554]
FatalErrorException in ProviderRepository.php line 146: Class 'Illuminate\Html\HtmlServiceProvider' not found

    in ProviderRepository.php line 146

===========================
I tried all the solutions mentioned in http://laraveldaily.com/class-form-not-found-in-laravel-5/

**Comment by lagbox** [comment]
Laravel does not provide the HTML/Form package any longer. Also the illuminate/html package is no longer maintained. You should use laravelcollective/html instead.
