### ISSUE TITLE
helpers.php preg_replace(): Parameter mismatch, pattern is a string while replacement is an array

### ISSUE THREAD

**Issue by SpareShade** [laravel/framework#12551]
Hello...
the Illuminate\Support\helpers.php function ```str_replace_array($search, array $replace, $subject) ``` is throwing ```preg_replace(): Parameter mismatch, pattern is a string while replacement is an array ``` when my CrateIo PDO client  (RatkoR/laravel-crate.io) throws an exception. 

This is due to the fact that crateio can have nested arrays in the bindings which QueryException ```formatMessage()``` tries to  convert into a message string, and thus the above error: ```pattern is a string while replacement is an array```.

Would it be possible to add a check if the $value is an array, and if so to cast it as json, ie:
```php
    function str_replace_array($search, array $replace, $subject)
    {
        foreach ($replace as $value) {
            if ( is_array($value) ) {
                $value = json_encode($value);
            }
            $subject = preg_replace('/'.$search.'/', $value, $subject, 1);
        }

        return $subject;
    }
```

**Comment by vlakoff** [comment]
Ouch, no.

`str_replace_array` is not designed to handle nested arrays of replacements.
It is a simple "placeholder to values" replacer, with a simple array of replacements.

And why should it be `json_encode` in particular?

You should write your own helper for this. It's not a long one.
If it may be of inspiration, in Laravel 5.3 `str_replace_array` will make use `Str::replaceFirst` (#12259), which has been added in #12255.

**Comment by gjrdiesel** [comment]
For anyone else interested, I was digging into it and It does prevent a proper exception from being thrown and prevents any helpful error message to the developer.

Maybe we could flatten the array to a string higher, perhaps while formatting the message instead?

```
protected function formatMessage($sql, $bindings, $previous)
    {
        $bindings = array_map(function($value){
            if(! is_array( $value )){
                return $value;
            } else {
                return json_encode($value);
            }
        },$bindings);

        return $previous->getMessage().' (SQL: '.str_replace_array('\?', $bindings, $sql).')';
    }
```
So then you get an exception with the error message as intended?

`Illuminate\Database\QueryException: Array to string conversion (SQL: insert into [...]))`

Not a huge issue though, I only ran into it while writing a seeder with faker that returned an array when I expected a string (doh).
