### ISSUE TITLE
Proposal - Add "tags" ability to migrator

### ISSUE THREAD

**Issue by leemason** [laravel/framework#12558]
The migrations feature of laravel is one of my favorite features, however its tightly coupled to a none extensible application.

Consider an "app" built with the idea of "plugins" (seperate to packages, these could be user installed, not developer), the app wont know anything about these plugins at any point, currently meaning any plugins seperate from the core need to setup there own migrations for db interaction.

what would be great is if we could "tag" migration locations.

this way we "tag" migration locations for anything, not just plugins.

we could turn ```php artisan migrate``` into ```php artisan migrate --tag=1,2,etc, or all```

all we need to do is add a column to the migrations table called "tag", then have a function on the migrator to register a tag location:

```
Migrator::tag('myplugin', __DIR__ . '/migrations');
```

if we run ```php artisan migrate``` it would just run migrations from the current migrations location

but if we run ```php artisan migrate --tag=myplugin``` it would just run migrations from the registered location and add the tag name to db for that migration, or ```php artisan migrate --tags``` to migrate every location.

this way we could have divergent migration history, so if we wanted to delete "myplugin" we could rollback just the plugins migrations without effecting the core apps migrations.

it would also be imo better for current packages, they wouldnt need to "publish" migrations poluting the apps migrations, they could just register a "tagname" and location.

Then when a package is updated instead of:

```php artisan vendor:publish --tag=migrations --force && php artisan migrate"

the command to update the package would just be ```php artisan migrate --tag=tagname```, or more simply: ```php artisan migrate --tags``` to update everything.

happy to work on this if its useful to the core.

If not can i request a contract for ```Illuminate\Database\Migrations\Migrator``` so we can at least overwrite the core implementation?

**Comment by GrahamCampbell** [comment]
Sorry to put a damper on this, but we don't process proposals on GitHub, as per our contribution guidelines.

I also think this has already been proposed and rejected about a year ago, or something.

**Comment by leemason** [comment]
understand the proposal thing, noted for future.

however doesnt the current migrator have effectivley a bug when using the --path option?

say you run ```php artisan migrate --path=.....```

then you run ```php artisan migrate:rollback```

this will fail because it cant find the last migration as it was from a custom path and the rollback command doesnt have a path option, plus even if it did you would have to remmeber the order in which you migrated, nullifying the benefit of migrations?

its a tricky situation i know because to just remove it would cause BC but its current implementation fails with the feature set it has?

**Comment by taylorotwell** [comment]
It really just depends on what the implementation looks like and if it will be a pain to maintain or not. You can give it a shot if you want.

**Comment by lagbox** [comment]
@GrahamCampbell since proposals aren't done on github, where can one go on slack to find all discussion about proposals and their resolutions.

**Comment by GrahamCampbell** [comment]
> @GrahamCampbell since proposals aren't done on github

Taylor has changed this policy now, starting from the day after I closed this. :0

**Comment by GrahamCampbell** [comment]
It's fine to discuss this here, at least for now.

**Comment by lagbox** [comment]
@GrahamCampbell thanks for the info :)

**Comment by laravel-internals** [comment]
Sorry, we don't process requests/proposals here. Please see https://github.com/laravel/internals/issues.

**Comment by GrahamCampbell** [comment]
Just a quick note, that our policy has now changed again.
