### ISSUE TITLE
Cache problems

### ISSUE THREAD

**Issue by todstoychev** [laravel/framework#12560]
Hi Taylor!
I am using Laravel from 2 years. I faced an issue today with the cache. The problem is on the latest 5.1 version. What I am trying is:
```php
try {
    $hasRecord = Cache::tags($tagsArray)->has($key);
   
    if ($hasRecord) {
        return unserialize(Cache::tags($tagsArray)->get($key));
    }   

} catch (\BadMethodCallException $e) {
    $hasRecor = Cache::has($key);
   
    if ($hasRecord) {
        return unserialize(Cache::get($key));
    }
}
```
It seems that we have a record in the cache. I am using Redis by the way. But we can not find it. For some reason the record is entered in some wrong way in the Redis. Also you if can see I am using serialization. It is necessary if you are using objects.

It is good to investigate this one. I think it is an issue.

**Comment by squigg** [comment]
You have a typo:
```
$hasRecor = Cache::has($key);
```
Not sure if this is your code copied/pasted, but that might be your issue.

**Comment by todstoychev** [comment]
No it is not my actual code. I did not copy it from my project. Probably there
was an error while I was writing the code in the email. I am sure that the
problem is not a typo.  The redis creates a record but I can not access it
directly in the redis-cli using KEYS my_key. I am not familiar with the tagged
cache but it worked for me when I used this before half an year I think. Also
when the Cache::tags(['my_tag'])-&gt;get('my_key') is executed it does not
gets the entry.  

I also know that some of the platforms does not support tags. So what I was
trying to do is to make a platform agnostic caching. If the platform does not
support tags as it is whe you are using 'file', trying to call the tags method
raises BadMethodCallException. So then the script uses Cache in the usual way
- without tags.  
I still suspect that it is an possible issue behind this. So please
investigate. If you need more info write me. But I think that this is
everything.

> On Mar 2 2016, at 4:29 pm, Squigg &lt;notifications@github.com&gt; wrote:  

>

> You have a typo:

>  
>  
>     $hasRecor = Cache::has($key);

>  
>

> Not sure if this is your code copied/pasted, but that might be your issue.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/laravel
/framework/issues/12560#issuecomment-191259544).![](https://github.com/notific
ations/beacon/AESmGyQYtsvXHteFlk4FvzkmWCpNtroFks5ppZ7LgaJpZM4HmiTi.gif)

**Comment by todstoychev** [comment]
Also got the same issue with memcached.

> On Mar 2 2016, at 4:40 pm, Todor Todorov &lt;todstoychev@gmail.com&gt;
wrote:  
No it is not my actual code. I did not copy it from my project. Probably there
was an error while I was writing the code in the email. I am sure that the
problem is not a typo.  The redis creates a record but I can not access it
directly in the redis-cli using KEYS my_key. I am not familiar with the tagged
cache but it worked for me when I used this before half an year I think. Also
when the Cache::tags(['my_tag'])-&gt;get('my_key') is executed it does not
gets the entry.  

>

> I also know that some of the platforms does not support tags. So what I was
trying to do is to make a platform agnostic caching. If the platform does not
support tags as it is whe you are using 'file', trying to call the tags method
raises BadMethodCallException. So then the script uses Cache in the usual way
- without tags.  
I still suspect that it is an possible issue behind this. So please
investigate. If you need more info write me. But I think that this is
everything.

>

>> On Mar 2 2016, at 4:29 pm, Squigg &lt;notifications@github.com&gt; wrote:  

>>

>> You have a typo:

>>  
>>  
>>     $hasRecor = Cache::has($key);

>>  
>>

>> Not sure if this is your code copied/pasted, but that might be your issue.

>>

>> —  
Reply to this email directly or [view it on GitHub](https://github.com/laravel
/framework/issues/12560#issuecomment-191259544).![](https://github.com/notific
ations/beacon/AESmGyQYtsvXHteFlk4FvzkmWCpNtroFks5ppZ7LgaJpZM4HmiTi.gif)

**Comment by boynet** [comment]
you know that laravel by default will add a prefix to the Cache Key? maybe this is your problem.
 you can see it in config/cache.php

**Comment by todstoychev** [comment]
But it should work when you are using it with the Cache facade class. Because
the component takes care for the prefix. So there is no reason my code to fail
to get the value stored in the cache.

> On Mar 2 2016, at 4:50 pm, boynet &lt;notifications@github.com&gt; wrote:  

>

> you know that laravel by default will add a prefix to the Cache Key? maybe
this is your problem.  
you can see it in config/cache.php

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/laravel
/framework/issues/12560#issuecomment-191268238).![](https://github.com/notific
ations/beacon/AESmG4VzZ8XxGJFq7ygSH6lHYmpRdiRtks5ppaPTgaJpZM4HmiTi.gif)
