### ISSUE TITLE
Custom size message validation not picking up

### ISSUE THREAD

**Issue by dennysutanto** [laravel/framework#12562]
I have this in my language/en/validation.php

'custom' => [
        'company_name' => [
            'required' => 'Please input Company Name',
            'max'      => ['string' => 'Please input maximum :max characters for Company Name']
        ],
    ],

in my controller i simply call this
$this->validate($request, [
        	'company_name' => 'required|max:10'
    	]);

The max error message never pick my custom message, instead it will always pick the standard one which is 

'max'                  => [
        'numeric' => 'The :attribute may not be greater than :max.',
        'file'    => 'The :attribute may not be greater than :max kilobytes.',
        'string'  => 'The :attribute may not be greater than :max characters.',
        'array'   => 'The :attribute may not have more than :max items.',
    ],

**Comment by rbadillap** [comment]
The workflow are fine, the only thing is that `string` key that you added in your array. 
`max` should have the custom message that you want to display. See attachments for reference.

![screen shot 2016-03-01 at 5 03 36 pm](https://cloud.githubusercontent.com/assets/3170758/13445079/c24a0304-dfcf-11e5-81d7-67ab0c48c865.png)
![screen shot 2016-03-01 at 5 03 45 pm](https://cloud.githubusercontent.com/assets/3170758/13445080/c24b8f12-dfcf-11e5-9332-b68a171cfc37.png)

**Comment by dennysutanto** [comment]
Thanks Ronny, works like a charm
