### ISSUE TITLE
Auth::attempt() showing error in Linux server

### ISSUE THREAD

**Issue by tanvirgaus** [laravel/framework#1257]
Not sure what's wrong, it works in my local dev environment but not in the server. all other DB related function works but not Auth::attempt()
Warning: array_diff() [<a href='function.array-diff'>function.array-diff</a>]: Argument #1 is not an array in .../web/bootstrap/compiled.php line 11346

$user = array(
            'username' => 'myuser',
            'password' => 'abc'
        );
if (Auth::attempt($user)) {
            echo "Here I am : " .Auth::user()->id;
        }

FYI - I'm running xampp 1.8.1 in windows7 with PHP 5.4.7 and my server is Linux bluejays with PHP 5.3.13

I changed the flash() in bootstrap/compiled.php like this 
public function flash($key, $value)
    {
        $this->put($key, $value);
        $this->push('flash.new', $key);
        $old = $this->get('flash.old');
        $old = (empty($old)) ? array() : $old;
        $this->put('flash.old', array_diff($old, array($key)));
    }

Then I managed to make it work and get the "Here I am : 1" but it didn't set anything in the session

**Comment by abosami2000** [comment]
same problem !!!

**Comment by spurdow** [comment]
im having the sample problem, i spent whole freaking day!!!

After saving in Auth::login create or retrieve users function , I print Auth:;users() and isnt empty, but when it redirected its gone!

im using php 5.6

PHP 5.6.4-4ubuntu6.4 (cli) (built: Oct 28 2015 01:21:29) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies

Laravel 5.2

Im using redis on my session then back on file and then back again to redis. no luck!

please help!

**Comment by spurdow** [comment]
My second attempt, Redis is working , but Session is not.

How do I configure Redis as my Session??

```
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync
```

**Comment by GrahamCampbell** [comment]
Feel free to discuss on the forums.
