### ISSUE TITLE
Add timestamp to Illuminate\Queue\CallQueuedHandler@call

### ISSUE THREAD

**Issue by Binternet** [laravel/framework#12589]
When working with queue, sometimes you need to debug/see things and watching the queue:listen in the terminal only outputs 'Processed: Illuminate\Queue\CallQueuedHandler@call', it will be great if it had a timestamp on each call.

**Comment by webpatser** [comment]
That's weird since it was merged in the 5.2 branche a while back:

https://github.com/laravel/framework/pull/10669

Where did it go?

**Comment by Binternet** [comment]
my bad, looks like it really was merged, i'm using 5.0...
