### ISSUE TITLE
Have different name convention & url in case of resourceful route

### ISSUE THREAD

**Issue by narsariamanu** [laravel/framework#12597]
Please add the feature which solves the following problem:-
### In the routes.php file:-
**Route::resource('photos', 'PhotoController', ['as' => 'images']);**

### This is the result:
images.photos.index   | PhotoController@index
images.photos.create  | PhotoController@create
images.photos.store   | PhotoController@store
images.photos.show    | PhotoController@show
images.photos.edit    | PhotoController@edit
images.photos.update  | PhotoController@update
images.photos.destroy | PhotoController@destroy

### Excpected Ouput:
images.index   | PhotoController@index
images.create  | PhotoController@create
images.store   | PhotoController@store
images.show    | PhotoController@show
images.edit    | PhotoController@edit
images.update  | PhotoController@update
images.destroy | PhotoController@destroy

**Comment by GrahamCampbell** [comment]
Please see the existing issues/PRs regarding this.

**Comment by lagbox** [comment]
@narsariamanu if you wanted this feature now you can extend the resource registrar to handle it how the PR that is currently in would.
I can create a gist if needed.
