### ISSUE TITLE
Auth::user($guard = 'api') doesn't work

### ISSUE THREAD

**Issue by ramilexe** [laravel/framework#12606]
Hello!

I am trying to use api and got problem with auth. My routes:

```
Route::group(['middleware' => 'web'], function () {
    //API
    Route::group(['middleware' => 'auth:api'], function () {
        Route::get('/some_api', ['as' => 'home.api', 'uses' => function () {

           var_dump(Auth::user('api')); //<<<<< it show null

            $data = [
                'field_1' => 'gdfgfdg',
                'field_2' => 54642,
            ];

            return response()->json($data);
        }]);
    });
});
```

I pass `api_token` param to url.

I think root cause is in https://github.com/laravel/framework/blob/5.2/src/Illuminate/Auth/AuthManager.php#L282
It call `$this->guard()` and don't pass $guard to it, so it return default guard (SessionGuard).

Temporary solution is: `Auth::guard($guard)->user()`

**Comment by stevebauman** [comment]
I don't see the issue here, the `user()` method accepts no guard parameters. The intended usage is exactly how you specified it, `Auth::guard('api')->user();`.

**Comment by ramilexe** [comment]
User has guard param
3 марта 2016 г. 20:34 пользователь "Steve Bauman" <notifications@github.com>
написал:
