### ISSUE TITLE
Improve looping functionality in blade

### ISSUE THREAD

**Issue by Yannik** [laravel/framework#12601]
It would be great to have functionality similar to what jinja2 provides in blade loops:

Variable   |Description
------------    | ------------
loop.index 	|The current iteration of the loop. (1 indexed)
loop.index0 	|The current iteration of the loop. (0 indexed)
loop.revindex 	|The number of iterations from the end of the loop (1 indexed)
loop.revindex0 	|The number of iterations from the end of the loop (0 indexed)
loop.first 	|True if first iteration.
loop.last 	|True if last iteration.
loop.length 	|The number of items in the sequence.
loop.cycle 	|A helper function to cycle between a list of sequences. See the explanation below.
loop.depth 	|Indicates how deep in deep in a recursive loop the rendering currently is. Starts at level 1
loop.depth0 	|Indicates how deep in deep in a recursive loop the rendering currently is. Starts at level 0

More information on this is in the jinja2 docs: http://jinja.pocoo.org/docs/dev/templates/#for

**Comment by GrahamCampbell** [comment]
Hmm. Interesting. Ping @taylorotwell.

**Comment by Yannik** [comment]
Twig can do this too: http://twig.sensiolabs.org/doc/tags/for.html

**Comment by JayBizzle** [comment]
@Yannik You can already do it using this http://robin.radic.nl/blade-extensions/

**Comment by Yannik** [comment]
Thanks for the link to this blade extensions bundle.
However, the loop control stuff would be really great to see as a feature natively integrated into blade - just as with Twig, Volt, Smarty, Jinja2. It is such a commonly needed feature.

**Comment by garygreen** [comment]
I've always wanted this as well. Another thing I've wanted is some kind of 'safe' variable definition in foreach loops. For instance:

```blade
<?php $user = Auth::user(); ?>

@foreach (User::all() as $user)
	{{ $user->name }}
@endforeach

Welcome, {{ $user->name }} // I want it to output the original one defined.
```

I'm pretty sure twig / jinja and others have 'safe' foreach loops which creates a new context for the variable and won't overwrite the existing one, so it's safe to use after the loop.

**Comment by laravel-internals** [comment]
Sorry, we don't process requests/proposals here. Please see https://github.com/laravel/internals/issues.

**Comment by Yannik** [comment]
@GrahamCampbell I don't know who the account "laravel-internals" belongs to.

Did @taylorotwell have a look at this?

**Comment by GrahamCampbell** [comment]
The account belongs to the laravel core team.

**Comment by GrahamCampbell** [comment]
Taylor tends not to read the issues posted on this repo, so our new internals repo has been created to allow people to discuss proposals. Our issues on the framework repo a strictly for bugs only.

**Comment by themsaid** [comment]
I've submitted a PR that extends Blade's looping functionality https://github.com/laravel/framework/pull/12867
