### ISSUE TITLE
[bug][5.2] Attach after sync inserting data twice

### ISSUE THREAD

**Issue by anggadarkprince** [laravel/framework#12614]
I hope i'm wrong about this, but i tried to sync table between [articles] and [tags] many-to-many relationship, when i updated my article, tags must be synchronized with article, there are some tags must be deleted and new tags must be inserted in [tags] table and inserted in [article_tags] table too. so i try to sync 

`$article->tags()->sync($available_tag);` 
and then insert new tags and attach them
`$article->tags()->attach($tags_id_new);`

i got sync tags data + new tags (but twice),, is it bug or i didn't know how to implement attach laravel method, but i successfully used it on 'create article' not in 'edit article'

**Comment by stevebauman** [comment]
You don't need to use the `attach()` method unless your needing to only attach **new** records. The sync method will add records that don't exist already. This explains why you're most likely getting duplicate records.
