### ISSUE TITLE
[5.1] trans_choice() return empty string.

### ISSUE THREAD

**Issue by iget-esoares** [laravel/framework#12619]
Steps to reproduce the bug:

Create a translation file `test.php`:
```
return [ 'foo' => 'bar:' ]
```

On a controller (or view) do:

```
dump(trans_choice('test.foo', 4));
```

This will dump:
```
""
```

Changing the translation file to:
```
return [ 'foo' => 'bar:foo' ]
```

This will dump:
```
"foo"
```

Looks like any word ending with `:` is being replaced by an empty string.

This problem only happen on `trans_choice()`. Using `trans()` everything works fine.

**Comment by iget-esoares** [comment]
Looking at symfony docs, there's an feature that allows tagging the translation options.

As described on docs:

```
'one: There is one apple|some: There are %count% apples'
```

The tags are really only hints for translators and don't affect the logic used to determine which plural form to use. The tags can be any descriptive string that ends with a colon (:). The tags also do not need to be the same in the original message as in the translated one.

This tag feature are causing this bug.
I'm looking for any way to avoid this, could someone please help-me?

**Comment by iget-esoares** [comment]
I just found an workaround for this: Just add a tag before your string. Only the first tag will be removed.

translation_file.php:
```
return [ 'foo' => 'tag:bar:' ]
```

This will output: `bar:`

**Comment by vlakoff** [comment]
You're right, this behaviour is caused by the Symfony component. See [`MessageSelector`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Translation/MessageSelector.php) class.

I found a workaround at https://github.com/symfony/symfony/issues/15075, but yours seems to be better.
