### ISSUE TITLE
[5.2][Testing] Can't Attach files to a multiple file field

### ISSUE THREAD

**Issue by stevebauman** [laravel/framework#12620]
In `5.2.22` (assuming that this issue exists in previous versions as well) during testing I'm unable to attach files to a `multiple` file field? The field is:

```html
<input class="form-control" id="images" multiple="1" name="images[]" type="file">
```

```php
$guide = Guide::first();

$this->visit(route('resources.guides.images', [$guide->slug]))
    ->attach(base_path('tests/assets/test.jpg'), 'images')
    ->press('Upload')
    ->see('Success!');
```

I receive the error after running `phpunit`:

```php
InvalidArgumentException: Cannot set value on a compound field "images".
```

If I pass in an array I receive `required` validation errors for the `image` field:

```php
$guide = Guide::first();

$this->visit(route('resources.guides.images', [$guide->slug]))
    ->attach([base_path('tests/assets/test.jpg')], 'images')
    ->press('Upload')
    ->see('Success!');
```

I'm not sure if this is a bug or there's an alternate method I'm supposed to be using?

Another example here: https://www.reddit.com/r/laravel/comments/3z21zi/laravel_testing_multiple_file_upload/

**Comment by jessedc** [comment]
In 5.2.22 `Symfony\Component\HttpFoundation\File\UploadedFile` has been replaced/wrapped with `Illuminate\Http\UploadedFile`. I suspect since it doesn't pass on the `test` parameter when using initialised in `createFromBase()` you will lose the testing flag associated with Symfony UploadedFiles.

Looking at the [Illuminate/UploadedFile history](https://github.com/laravel/framework/commits/5.2/src/Illuminate/Http/UploadedFile.php) support for `test` was there but taken away before release. I'd be keen to understand why it was removed as it looks useful.

**Comment by daack** [comment]
My tests with UploadedFile now are all failing because it's not possible to set the test property anymore.

**Comment by mauricius** [comment]
I have the same problem. The code from `illuminate\http\UploadedFile` doesn't consider the `$test` property anymore, therefore our test suite is failing. Is anyone aware of an alternative approach to test file uploads?

**Comment by mnabialek** [comment]
@jessedc @daack  @mauricius This is not really the problem. You should now use:

    \Illuminate\Http\UploadedFile

instead of

    \Symfony\Component\HttpFoundation\File\UploadedFile

For details have a look at http://stackoverflow.com/questions/36857800/laravel-5-2-testing-uploadedfile-misses-the-test-value-after-post-bug

**Comment by kmbt** [comment]
I believe there still is an error in:

framework/src/Illuminate/Foundation/Testing/Concerns/InteractsWithPages.php

as the `convertUploadsForTesting` and `getUploadedFileForTesting` methods don't take into account the possibility of a having a compound file input field. Please take a look, at how `$this->uploads` property is treated throughout in the `attach` method.
