### ISSUE TITLE
can not close auto timestamps by save function  $options

### ISSUE THREAD

**Issue by apollopy** [laravel/framework#12627]
read code: 

https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/Model.php#L1545-L1547

```php
// First we need to create a fresh query instance and touch the creation and
// update timestamp on the model which are maintained by us for developer
// convenience. Then we will just continue saving the model instances.
if ($this->timestamps && Arr::get($options, 'timestamps', true)) {
    $this->updateTimestamps();
}
```

but
```php
$post = Post::find(1);
$post->title = 'aaa';
$post->save(['timestamps' => false]);
// update post title and updated_at
```

Because, after this `if`

https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/Builder.php#L476

```php
public function update(array $values)
{
    return $this->toBase()->update($this->addUpdatedAtColumn($values));
}
```

**Comment by stevebauman** [comment]
Have you tried setting the `timestamps` property **before** saving?

```php
$post = Post::find(1);
$post->title = 'aaa';
$post->timestamps = false;

$post->save();
```

**Comment by vlakoff** [comment]
This feature is broken (in fact it never worked) and will be removed in Laravel 5.3.

Taylor advised to not use Eloquent but the Query Builder for specific cases as this one.

**Comment by apollopy** [comment]
@stevebauman 
yes, I know `timestamps` property, I just think `$options ` is difficult to understand the parameters
