### ISSUE TITLE
[5.2.22] belongsToMany sync failing when only updating pivot data

### ISSUE THREAD

**Issue by mattmcdonald-uk** [laravel/framework#12624]
This issue appears to have occurred (and been fixed) before (#1534)

When you sync a belongsToMany relationship and only the pivot data has changed, nothing is updated.

The problem appears to be that the extra pivot columns aren't compared, only the IDs.

**Comment by GrahamCampbell** [comment]
Thanks for the report. If this issue is still persisting in the latest 5.2.x, please open a new issue.
