### ISSUE TITLE
[5.2] Controller method with optional params issue

### ISSUE THREAD

**Issue by xpert13** [laravel/framework#12630]
Hello.

I have next route:

```
Route::get('/calendar/{user}/{department?}/{year?}/{month?}/{team?}',[ 'as' => 'schedule.show', 'uses' => 'ScheduleController@show' ]);
```

And controller method:

```
public function show(Request $request, User $user, Department $department = null, $year = null, $month = null, Team $team = null)
{
...
}
```

When I open url localhost/calendar/1/5/2016/02/9 or localhost/calendar/1/5/2016/02 (with team and without) - eversyng is ok, but when I try to open  localhost/calendar/1 (without all optional params) - I got empty Team class in variable $year. Example:

```
localhost/calendar/1/5/2016/02/9:
$user -> Object of User with id 1
$department -> Object of Department with id 5
$year -> string 2016
$month -> string 02
$team -> Object of Team with id 9

---

localhost/calendar/1/5/2016/02:
$user -> Object of User with id 1
$department -> Object of Department with id 5
$year -> string 2016
$month -> string 02
$team -> Object of empty (not exists) Team

---

localhost/calendar/1:
$user -> Object of User with id 1
$department -> Object of empty Department
$year -> Object of empty Team
$month -> null
$team -> null
```

I have found just one sollution - remove class name "Team" from method params:

```
public function show(Request $request, User $user, Department $department = null, $year = null, $month = null, $team = null)
{
...
}
```

**Comment by vlakoff** [comment]
Looks like there is a shift because of the unhinted `$year` and `$month` preceding the hinted `$team`.

**Comment by vlakoff** [comment]
I'm suspecting `RouteDependencyResolverTrait::spliceIntoParameters`.

**Comment by milosdakic** [comment]
Have you tried moving `$team` var around?

```
public function show(Request $request, User $user, Department $department = null, Team $team = null, $year = null, $month = null)
{
...
}
```

**Comment by xpert13** [comment]
> Have you tried moving $team var around?

Yes, I have tried. In this case links without team id works fine, but such links as `localhost/calendar/1/5/2016/02/9` create next error:
```
Type error: Argument 4 passed to App\Http\Controllers\ScheduleController::show() must be an instance of App\Team, string given
```

**Comment by mark86092** [comment]
@GrahamCampbell Can you look at this? I think it is explained in #12959 as a bug

**Comment by GrahamCampbell** [comment]
Sorry, I don't have time to personally look into every bug report.

**Comment by mark86092** [comment]
@GrahamCampbell No problem, thank you

**Comment by GrahamCampbell** [comment]
Closing since we now have a PR.
