### ISSUE TITLE
Add support for field.* validation attributes

### ISSUE THREAD

**Issue by shadoWalker89** [laravel/framework#12649]
Hi,

Assuming that we have

```html
<input type="text" name="field[]" />
<input type="text" name="field[]" />
<input type="text" name="field[]" />
```
We should be able to do one of these in the language file validation.php

```php
'attributes' => [
    'field.*' => 'field label'
]
```

or

```php
'attributes' => [
    'field' => [
        '*' => 'field label'
    ]
]
```

Unfortunately both options doesn't work

**Comment by themsaid** [comment]
With this PR merged https://github.com/laravel/framework/pull/12578, you'll be able to apply what you need. You only have to wait until 5.2.23 is released :)
