### ISSUE TITLE
Default route for '/' not in web middleware group after make:auth.

### ISSUE THREAD

**Issue by mace015** [laravel/framework#12650]
After firing `php artisan make:auth` to scaffold a basic authentication system, the route '/' which renders the welcome view, is not placed inside the web middleware group.

This is a problem since without the web middleware group, the sessions aren't started and thus the welcome view can't check if a user is logged in or not, so it will always display the login and registration links, even if the user is logged in!

This can be easily reproduced by installing a new Laravel installation, and then running `php artisan make:auth` & `php artisan migrate`.
Then you register and login with a new account, and then you are logged in at the '/home' page, but not at the '/' page.

**Comment by GrahamCampbell** [comment]
This is intended.
