### ISSUE TITLE
[5.2] key:generate command: write into different env files

### ISSUE THREAD

**Issue by murrant** [laravel/framework#12657]
When running my tests. I set APP_ENV=testing in my phpunit.xml file.
This allows laravel to pull all my .env settings from .env.testing.
.env does not exist in my test environment, only .env.testing. (and I would prefer it not exist)

`php artisan key:generate --env=testing` does not save the APP_KEY into .env.testing.

Can we have that behavior if .env doesn't exist?  Or is there a better solution?

**Comment by vlakoff** [comment]
Submitted #12683 to correct this :)
