### ISSUE TITLE
[5.2]Illuminate\Routing\Route->middleware() only brings up the first middleware

### ISSUE THREAD

**Issue by iceheat** [laravel/framework#12665]
I'm using Laravel 5.2.22 but not using middleware groups. I assign middleware to controllers in the routes.php then assign additional middlewares in the controller. `php artisan route:list ` shows that the middlewares are correctly assigned. However, running middleware() function, only brings up the first middleware attached. any Ideas?

**Comment by themsaid** [comment]
@iceheat can you please share some code?

**Comment by iceheat** [comment]
I have just had a fresh Laravel installation created a new resource controller:

routes.php
```
Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => 'auth'], function () {
    Route::resource('test', 'TestController');
});
```

Kernel.php
```
//....
protected $routeMiddleware = [
        'auth' => \App\Http\Middleware\Authenticate::class,
        'auth2' => \App\Http\Middleware\Authenticate2::class,
        'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
        'throttle' => \Illuminate\Routing\Middleware\ThrottleRequests::class,
    ];
```

TestController.php 
```
..//
 public function __construct(){
        $this->middleware('auth2' , ['except'=>['index','show']]);
    }
..//
```

welcome.blade.php
```
..//
{!! dump(Route::getRoutes()->getByName('test.index')->middleware()) !!}
            {!! dump(Route::getRoutes()->getByName('test.update')->middleware()) !!}
..//
```

running `artisan route:list `
                                                                                                                                   
 Domain | Method    | URI              | Name         | Action                                      | Middleware                                                                                                                                              
-----------|--------------|-----------------|----------------|--------------------------------------|----------------                                                                                                                                         
       | GET¦HEAD  | /                |              | Closure                                     |            |                                                                                                                                             
       | GET¦HEAD  | test             | test.index   | App\Http\Controllers\TestController@index   | auth                                                                                                                                                   
       | POST      | test             | test.store   | App\Http\Controllers\TestController@store   | auth,auth2 |                                                                                                                                             
      | GET¦HEAD  | test/create      | test.create  | App\Http\Controllers\TestController@create  | auth,auth2 |                                                                                                                                             
      | GET¦HEAD  | test/{test}      | test.show    | App\Http\Controllers\TestController@show    | auth                                                                                                                                                   
     | PUT¦PATCH | test/{test}      | test.update  | App\Http\Controllers\TestController@update  | auth,auth2 |                                                                                                                                             
       | DELETE    | test/{test}      | test.destroy | App\Http\Controllers\TestController@destroy | auth,auth2 |                                                                                                                                             
      | GET¦HEAD  | test/{test}/edit | test.edit    | App\Http\Controllers\TestController@edit    | auth,auth2 |                                                                                                                                             
 

However, the dump from the middleware is:

```
array:1 [▼
  0 => "auth"
]
array:1 [▼
  0 => "auth"
]
```

**Comment by themsaid** [comment]
The command merges the middlewares registered in `routes.php` and those registered in the controller.

However `Route::middleware()` will return only those registered in `routes.php`.

What's your use case here? what are you trying to accomplish?

**Comment by iceheat** [comment]
Thank you Mohammed for your very swift reply. As you said, the middleware() is not reflecting the full picture of the middlewares applied to routes. I personally doubt that this is the intended behaviour. 

The simplified scenario of what I need to achieve:

I have a sizable business application with a role management backend. auth middleware is for every logged in user. auth2 would have to match against the user role. 

when the administrator is setting the roles, they  need to select from routes with auth2 so I need a list of all Routes that have auth2 as a middleware.

**Comment by themsaid** [comment]
I don't believe you should rely on middlewares in your business logic, maybe save all resources that require an auth2 in an config array or something, and then add the auth2 middleware to them.

That way you can list these resources via `config('app.protected_resources')` or something.

**Comment by iceheat** [comment]
I like your thinking. This is exactly what I'm doing at the moment. The only problem is with resource controllers where I need to apply additional middlewares to some of the routes. This has to be set within the controller, which means that I have to define these in the controller constructor.  This what forced me to rely on relying to filter by middleware instead of the configuration file.

**Comment by iceheat** [comment]
@GrahamCampbell Can you please confirm if this is the intended behaviour of middleware() function?

**Comment by boynet** [comment]
@iceheat you can always see how the artisan commands got all the controller middleware and do it in your code also
https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Console/RouteListCommand.php#L139

take a look at the methods:  

- getMiddleware() 
- getControllerMiddleware() 
- getControllerMiddlewareFromInstance()

so yes it looks intended that $route->middleware() return only route middlewares

**Comment by iceheat** [comment]
Thanks boynet, I'm investigating this option + finding an alternative way as @themsaid suggested. I figured out that controller middleware is only injected once the controller is constructed. I have to say that it is a bit counterintuitive to have different results from different parts of the framework. But, who cares when you can get the support of such a brilliant community.

Thanks,
