### ISSUE TITLE
Eloquent one to many relation is retrieving limited number of records

### ISSUE THREAD

**Issue by mkwsra** [laravel/framework#12664]
Hey there all,

Is it about eager loading? or am I missing something?

simply I've this code
```
        $article = Article::where("id",121)->first();

        dd(ArticleEntry::where('article_id',121)->count()); // 104
		dd($article->entries->count()); // 102 !!

		if ( $article->entries->count() > 0 ) {
			foreach ( $article->entries as $entry ) {
				// some view render goes here
			}
		}
```
Where the relation inside `Article.php` is:
`return $this->hasMany( ArticleEntry::class );`

Simply I couldn't determine why `->entries` is returning limited values most likely around 100

Since I've solved my issue by using the first line of code above, what I'm doing here is just wondering/reporting this odd issue.

Thanks in advance for any explanation.

**Comment by Decadence** [comment]
Not sure.

Here you call Builder count method
 `ArticleEntry::where('article_id',121)->count()`

Here you call Collection count method
`$article->entries->count()`

I too expect they return equal number, but can you try call it like this:
`$article->entries()->count()`
to call Builder count method and see if it makes any difference.

**Comment by mkwsra** [comment]
It's the same now with parenthesis and without, so you may say it's working!

but I'm sure about that buggy results above and I'd like to flag this as suspicious for future users

**Comment by Decadence** [comment]
I think it was just some kind of inconsistency in your local conditions.

**Comment by mkwsra** [comment]
@Decadence It was all about php configuration the `max_input_vars` it should not commented out and for my own case with value more than `1000`
