### ISSUE TITLE
[5.2][Lumen] Whats the best way to unit tests Task Scheduling methods?

### ISSUE THREAD

**Issue by darkninja462** [laravel/framework#12666]
Hi All, hopefully someone will be able to help or guide me in the right direction, I'm looking to unit test a "Task Schedule" method defined in the Kernel as per the documentation, I was wondering what is the best approach for unit testing this or setting it up to be unit tested?

-Regards
Andrew Townsend

**Comment by GrahamCampbell** [comment]
Please direct questions to the forums.
