### ISSUE TITLE
Auth::guard()->attempt pass but when redirect to client profile, it logged out the client Laravel 5.2.22

### ISSUE THREAD

**Issue by suman315** [laravel/framework#12672]
my auth.php

<?php

return [

    'defaults' => [
        'guard' => 'web',
        'passwords' => 'users',
    ],

    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
        ],

        'clients' => [
            'driver'  => 'session',
            'provider' => 'clients'
        ]
    ],

    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
        ],

        'clients' => [
            'driver' => 'eloquent',
            'model'  => App\Client::class,
        ]

        // 'users' => [
        //     'driver' => 'database',
        //     'table' => 'users',
        // ],
    ],

    'passwords' => [
        'users' => [
            'provider' => 'users',
            'email' => 'auth.emails.password',
            'table' => 'password_resets',
            'expire' => 60,
        ],
        'clients' => [
            'provider' => 'clients',
            'email' => 'auth.emails.password',
            'table' => 'password_resets',
            'expire' => 60,
        ],
    ],

];

------------------------------------------------------------------
Routes.pph

Route::group(['middleware' => ['web']], function () {

	Route::get('/client/login', 'ClientAuth\AuthController@showLoginForm');

	Route::post('/client/login', 'ClientAuth\AuthController@login');

	    Route::auth();
	Route::get('/home', 'HomeController@index');

    
});

Route::group(['middleware' => ['web']], function () {
		 
		Route::get('/client', function () {
		 	
    	if(Auth::guard('clients')->check())
    	{
    		return 'passed';
    	}
    	else
    	{
    		return 'auth failed';
    	}
    });

--------------------------------------------------------------
Karnel.php

added

$routeMiddleware =  'client'  => \App\Http\Middleware\RedirectIfNotClient::class, 

--------------------------------------------------------
ClientAuth\Authcontroller 

<?php

namespace App\Http\Controllers\ClientAuth;

use App\User;
use Auth;
use Validator;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Foundation\Auth\ThrottlesLogins;
use Illuminate\Foundation\Auth\AuthenticatesAndRegistersUsers;

class AuthController extends Controller
{

    use AuthenticatesAndRegistersUsers, ThrottlesLogins;

    /**
     * Where to redirect users after login / registration.
     *
     * @var string
     */
    protected $redirectTo = '/client';

    protected $guard = 'clients';

    protected $username = 'ClientID';

    /**
     * Create a new authentication controller instance.
     *
     * @return void
     */
    // public function __construct()
    // {
    //     //$this->middleware('client');
    // }

    protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => 'required|max:255',
            'ClientID' => 'required|alpha_num|max:255',
            'password' => 'required|confirmed|min:6',
        ]);
    }

    protected function create(array $data)
    {
        return User::create([
            'name' => $data['name'],
            'email' => $data['email'],
            'password' => bcrypt($data['password']),
        ]);
    }

    public function showLoginForm()
    {
        if (Auth::guard('clients')->check())
        {
            return redirect('/admin');
        }
        
        return view('auth.login');
    }
    
    public function showRegistrationForm()
    {
        return view('auth.register');
    }
    
    public function resetPassword()
    {
        return view('auth.passwords.email');
    }
    
    public function logout(){
        Auth::guard('clients')->logout();
        return redirect('/client/login');
    }

}

----------------------------------------------
Mode Client.php

<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class Client extends Authenticatable
{
	/**
	 * Name of the Client table
	 */
   protected $table = 'Client';

   /**
    * Name of primary kay
    */
   protected $primaryKey = 'ClientID';

    protected $fillable = [
        'ClientID', 'password', 'ClientCode', 
    ];

 
    protected $hidden = [
        'password', 'remember_token',
    ];

    public $timestamps = false;

    // public function getAuthIdentifierName()
    // {
    //     return $this->getKeyName();
    // }

    public function getAuthIdentifier()
    {
        return $this->getKey();
    }

}

---------------------------------------------
I have a ClientID as primay key and which is alpha_num

Auth passes dd(Auth::guard('clients')->user()) form auth attempt gives a user object but when  it redirect to /client URL it looses the user information 

been two days hunting aroung the we and coudn't find the solution 

tried http://stackoverflow.com/questions/34614753/can-anyone-explain-laravel-5-2-multi-auth-with-example/34783443#34783443 as well 

-------------------------------------
dd(Session::all()) gives 
array:5 [▼
  "_token" => "6Vb6FnP2XCGNOakOpCK2yS51TEyps3iFutGyIzLb"
  "_previous" => array:1 [▼
    "url" => "http://client.app/client/login"
  ]
  "flash" => array:2 [▼
    "old" => []
    "new" => []
  ]
  "login_clients_59ba36addc2b2f9401580f014c7f58ea4e30989d" => 0
  "url" => []
]

---------------------------------------------------------------------------------------------------
Found the problem but not solution 

the problem is my Client table doesn't have id field.

I copied all the data from Client to clients(test table with id) and same code is working fine. 

Is there a way I can keep Client table ? because our legacy systems depends on Client table 

thanks,
Suman

**Comment by suman315** [comment]
Ok its working now )))
i had to set $incrementing = false

**Comment by arjayads** [comment]
Where did you set $incrementing = false?

**Comment by suman315** [comment]
i had a non incrementing column as a key on table, So i set it on Model.
