### ISSUE TITLE
[5.1] Bug with Artisan command signature?

### ISSUE THREAD

**Issue by baopham** [laravel/framework#12675]
Suppose I have a console command signature like so:

```php
    protected $signature = 'check-foo-bar';
```

Then in the terminal, I run:

```bash
$ php artisan check-
```
It did not error out and still run the command `check-foo-bar`.

It seems that it will run a command that best matches. 

Is this a feature or a bug? I always thought it would check for complete match.

**Comment by themsaid** [comment]
Laravel searches for the command using the following:

```php
preg_grep('{^'.$expr.'}', $allCommands)
```

So yeah providing the first part of the command will run it.
