### ISSUE TITLE
[5.2] AuthController not extending the validation AttributeNames to Login page

### ISSUE THREAD

**Issue by evertramos** [laravel/framework#12674]
I am trying to substitute the login field names as below:

- email to 'E-mail'
- password to 'senha'

So, I have used under the function *validatior(array $data)* in *app/Http/Auth/AuthController.php* the following:

    protected function validator(array $data)
    {
        $validator = Validator::make($data, [
            'name' => 'required|max:255',
            'email' => 'required|email|max:255|unique:users',
            'password' => 'required|confirmed|min:6',
        ]);        
        $correct_names = [
            'name'      => 'Nome',
            'email'     => 'E-mail',
            'password'  => 'Senha',
        ];
        return $validator->setAttributeNames($correct_names);
    }

Working fine for my **user registration form**, but when it comes to the login form... it brings the regular field name *email* and *password*.

I know it´s not the correct way of doing it, but I had to change the core file:

> /vendor/laravel/framework/src/Illuminate/FoundationAuth/AuthenticatesUsers.php

In the funcion *validateLogin(Reqiest $reqiest)* to the following:

    $this->validate($request, [
           $this->loginUsername()  => 'required', 
           'password'              => 'required'
     ], [
           'required'              => 'O campo :attribute é obrigatório!'  
     ], [
           $this->loginUsername()  => 'E-mail',
           'password'              => 'Senha',                
      ]);

In order to have the login page showing the expected field names.

Is that an issue or I am only too newbie?

Thanks in advance!

**Comment by cretueusebiu** [comment]
You should use custom <a href="https://github.com/laravel/laravel/blob/master/resources/lang/en/validation.php#L111">validation attributes</a>.

If you don't want to be globally, override the [validateLogin](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Auth/AuthenticatesUsers.php#L94) method in  in `app/Http/Controllers/Auth/AuthController.php`:

```php
protected function validateLogin(Request $request)
{
    $this->validate($request, 
        [
            $this->loginUsername() => 'required', 'password' => 'required',
        ],
        [
            $this->loginUsername()  => 'E-mail', 'password' => 'Senha',                
        ]
    );
}
```

**Comment by evertramos** [comment]
Hi @cretueusebiu,

Thanks for you reply. In fact, you are right, I can substitute the function (too newbie to get that.... sorry).

Only for future refence, only small fix, the attribute name should be the third parameter, as below:

    protected function validateLogin(Request $request)
    {
        $this->validate($request, [
                $this->loginUsername()  => 'required', 
                'password'              => 'required'
            ],[],[
                $this->loginUsername()  => 'E-mail',
                'password'              => 'Senha',
            ]
        );
    }

And not forgetting the have *use Illuminate\Http\Request;* at the top. Other wise the code below works just fine, I think:

    protected function validateLogin($data)
    {
        $this->validate($data, [
                $this->loginUsername()  => 'required', 
                'password'              => 'required'
            ],[],[
                $this->loginUsername()  => 'E-mail',
                'password'              => 'Senha',
            ]
        );
    }

Thanks for your time!
