### ISSUE TITLE
JoinClause.where works differently of Builder.where

### ISSUE THREAD

**Issue by rentalhost** [laravel/framework#12671]
Hello. 

When I do something like `$joinClause->where('id', 1)` it works differently from `$builder->where('id', 1)`.

The first one will generate a SQL like: `WHERE `id` 1 ?` [null]
The second one will generate a SQL like: `WHERE `id` = ?` [1]

The second one is the correct, and all Eloquent works like it. Basically, the JoinClause's where not uses an equal comparator when it have only two arguments.

**Comment by timgws** [comment]
What is `$joinClause` and `$builder`? How are they initialised?

**Comment by rentalhost** [comment]
You can do it by use something like that:

```
$user = User::leftJoin(function (JoinClause $here) { ... });
```
