### ISSUE TITLE
[5.2] Illuminate\Foundation\Testing\Concerns::notSeeInDatabase() fails for soft-deleted models

### ISSUE THREAD

**Issue by markdwhite** [laravel/framework#12686]
Where a model has soft-deletes enabled, and $model->delete() has been called, it seems unintuitive to "see" it in the database. I can see why it is factually correct, but don't see a simple mechanism in place that can be used to correctly assert that the model has been deleted.

I'm not trying to test Eloquent methods - I have a model method that conditionally deletes related models depending on a date property, and this needs to be tested.

Current workaround is okay, but a bit limited and looking at this raised the issue of whether soft-deleted models should be "seen in database" so I thought I'd ask:         

Workaround where all related models should be deleted:

        $this->assertNotEmpty($book->adverts); // For example
        $result = $book->delete();
        $this->assertTrue($result);
        $book->load('adverts');
        $this->assertEmpty($book->adverts);

On a related theme, is it intentional that Illuminate\Database\Eloquent\Model::fresh() also excludes soft-deletes?

        return static::with($with)->where($key, $this->getKey())->first();

**Comment by GrahamCampbell** [comment]
Hmmm, I'm not convinced this is a bug.

**Comment by w4** [comment]
add ['deleted_at' => null] to your dontSeeInDatabase work around it. there are many instances where you need to seeInDatabase soft deleted records too.

I agree with @GrahamCampbell that this doesn't really need to be fixed.

**Comment by markdwhite** [comment]
I missed the very simple fix of this and agree this is a non-issue.

    add ['deleted_at' => null] to your dontSeeInDatabase
