### ISSUE TITLE
DB::enableQueryLog() doesnt work in 5.2

### ISSUE THREAD

**Issue by ctf0** [laravel/framework#12688]
right now when i use `DB::enableQueryLog();` i still get an empty array , but if i explicitly changed the `protected $loggingQueries` to `true` from the `src/Illuminate/Database/Connection.php` it works :confused: 

https://github.com/laravel/framework/issues/12170

**Comment by GrahamCampbell** [comment]
I can't replicate.

**Comment by GrahamCampbell** [comment]
You're probably calling the method too early.

**Comment by ctf0** [comment]
why u close the issue to early ???

anyhow i tried enabling it through a middleware.
tried to enable it through the app service provider as u noted on the other closed issue.
tried enabling it in the route file b4 and after the routes.

all the above didnt work.

**Comment by lagbox** [comment]
```php
DB::enableQueryLog();
... some queries ...
dump(DB::getQueryLog());
```
I can't get that to not work how I am testing it.

**Comment by GrahamCampbell** [comment]
If it's not working, maybe you're enabling the logs on the wrong db connection.

**Comment by ctf0** [comment]
the above middle wont work because the loggerinterface is not found ,also when should i middle ware, right now am assigning to a route group holding all the routes.

**Comment by GrahamCampbell** [comment]
sounds like your entire install is a bit broken to me

**Comment by ctf0** [comment]
i just ran `composer update` and will give it another try :muscle:

**Comment by ctf0** [comment]
@GrahamCampbell all is working as it should now, many thanx for ur help <3
