### ISSUE TITLE
Webserver crashes at double variable assignation

### ISSUE THREAD

**Issue by 0x1ad2** [laravel/framework#12690]
I was working today and somehow my webserver crashed out of the blue. 

I tried to change my routes, the assigned methods and anything in these methods, after a couple of hours I finally spotted my error. I tried to assign two values to a variable. Most of the time it will throw an syntax error but now it didn't.

`// as expected it will throw an syntax error, unexpected '='`
`$x = 'y' = 'z';`
`$x = 0 = 1;`

when I include the Input class in it it will break my webserver.

`// the webserver crashes`
`$x = \Input::get('video_url') = 'z';`

**Apache Version:** Apache/2.4.10 (Win32) OpenSSL/1.0.1i PHP/5.6.3
**MySQL Version:**	mysqlnd 5.0.11-dev - 20120503

**Comment by cretueusebiu** [comment]
It will thrown a `Symfony\Component\Debug\Exception\FatalErrorException` exception with the message _Can't use function return value in write context_, because you can't assign a value to a method call.

**Comment by GrahamCampbell** [comment]
This is the expected behaviour, and has nothing to do with Laravel. This is merely a property of PHP.
