### ISSUE TITLE
[5.2] Container's contextual binding fails when the abstract is an alias of an instanced class.

### ISSUE THREAD

**Issue by thecrypticace** [laravel/framework#12695]
I’ve encountered what I could see as a bug. The use of aliases inside the DI container prevent contextual binding from working for anything that is:
- Aliased
- And points to an “instanced” concrete

Example:
```
$this->app->when(SomeClass::class)->needs(\Psr\Log\LoggerInterface::class)->give(SomeClassLogger::class);
```

**This will not work.** `SomeClass` will _always_ get the default logger. This is because of the way logging is setup in `ConfigureLogging.php` on lines 41–43 (using `instance`). This issue can be worked around by rebinding the logger like the below but it wasn't obvious why I needed to this or that this would work (until I went through the Container source).
```
$this->app->bind(LoggerInterface::class, function () {
    return $this->app["log"];
});
```

On the face of it, this seems to be the same issue as #12402. However, the workaround provided does not work because `log` is setup as an instance and not a binding like Filesystem is.

I'm aware that this is a quite obscure situation (and that there is indeed a way to workaround it) but it certainly didn't make sense that it wouldn't work and took quite a bit of research to discover why.

Any chance this is indeed a bug and not too obscure to be worth fixing?

**Comment by TheoKouzelis** [comment]
Hi I have also just had a similar issue. 

My use case is I would like different configurations of Monolog to be passed to different parts of my program. I thought I could achieve this by type hinting the Psr\Log\LoggerInterface and setting up a service provider that would use contextual binding to bind the different loggers.

But like you have mentioned the container prioritises bound instances over the contextual bindings and the default logger is a bound instance. 

I think you can overwrite how the default logger is setup by unsetting the ConfigureLogging.php in your Kernal class and writing a new bootstrap class.

Is there any easier way of getting multiple logger instances or would anyone be interested in a alternate to ConfigureLogging.php?

**Comment by thecrypticace** [comment]
The current solution is to rebind the logger instance like I did in the second code block above (just put it in your `AppServiceProvider@register` method). Once you do that contextual binding will work.

**Comment by TheoKouzelis** [comment]
Thanks. Am I right in thinking that rebinding the logger like this unsets the bound instance of the default logger so then the contextual bindings will be checked. 

But to achieve this the "shared" parameter for bind must be false which will mean a new instance of the logger will be created if there are no contextual bindings?

**Comment by thecrypticace** [comment]
Point 1: Yes. You are correct.
Point 2: I'm not sure. I'll have to check on it.

**Comment by themsaid** [comment]
@thecrypticace any chance you're going to suggest a change to fix this issue?

**Comment by thecrypticace** [comment]
Man, I forgot about this issue. I need to check and see if it is still an issue on 5.3. If so, I'll try to take some time in the next few days if I can figure out how to fix it.

**Comment by themsaid** [comment]
Thank you!

Trying to close some of these old issues :)

**Comment by TheoKouzelis** [comment]
I would be happy to help if you want a hand?

**Comment by thecrypticace** [comment]
> Trying to close some of these old issues :)

👍👍

> I would be happy to help if you want a hand?

Any help is good.

**Comment by thecrypticace** [comment]
Here is a repo that reproduces the issue: https://github.com/thecrypticace/contextual-binding-issue

_Note: The repo **contains the vendor folder** to make it simpler to track the changes._

I've fixed _half_ of the bug already but I didn't run tests so I can't guarantee that it's a good one. If you hit the homepage you'll see three links: 

1. Actual: instance (I just fixed this one in that repo)
2. Actual: Instance + Alias (not fixed)
3. Expected

**Comment by thecrypticace** [comment]
I figured it out! The abstract passed to `getContextualConcrete` will be an alias if one is registered to the container. It does a simple lookup which fails because it's looking for a concrete of `log` and not `\Psr\Log\LoggerInterface`.

The way I've gone about fixing this:
- In `getContextualConcrete `
- loop over the aliases (if a concrete wasn't returned)
- Use the abstract from the alias to look for a contextual binding
- Return it if one exists

I'll have a PR incoming soon once I write tests and verify it doesn't break all the things.

**Comment by GrahamCampbell** [comment]
Great. :)

**Comment by TheoKouzelis** [comment]
I have done a bit of a manual test, and the contextual binding now works for my use case (Thanks), which was to inject different configured loggers into targeted classes, like so:

```
//app/Providers/AppServiceProvider.php

public function register()
    {
        $this->app->when('App\Test1')
            ->needs('Psr\Log\LoggerInterface')
            ->give(function () {
                $log = new Logger('test1');
                $log->pushHandler(new StreamHandler(storage_path('logs/test1.log'), Logger::DEBUG));

                return $log;
            });

        $this->app->when('App\Test2')
            ->needs('Psr\Log\LoggerInterface')
            ->give(function () {
                $log = new Logger('test2');
                $log->pushHandler(new StreamHandler(storage_path('logs/test2.log'), Logger::DEBUG));

                return $log;
            });
    }
```

But there is a side effect that (at least to me) wasn't intuitive. In my above example the "test2" logger was also injected into classes that depended on Psr\Log\LoggerInterface, but didn't have a contextual binding. In this case I would expect it to fall back to the logger created from the main Laravel config/app.php L:123

**Comment by thecrypticace** [comment]
Using the latest code from the PR (#15637)? That definitely shouldn't be happening, I'll take a look. Also, can we move the discussion there?

**Comment by TheoKouzelis** [comment]
Oh sorry I might be using old code. I just cloned your repo and I am on commit https://github.com/thecrypticace/contextual-binding-issue/commit/f536f637ca279332a2cf3846ad9cd5aee08867ed. I will clone the PR and make any further comments there

**Comment by thecrypticace** [comment]
Oh, yeah, lemme update that repo real quick.

**Comment by thecrypticace** [comment]
Updated.

**Comment by TheoKouzelis** [comment]
Thanks, I am now on commit c3b090d. But I am still seeing the same behaviour. Maybe I should try and write a test for it. Or commit my manual test to a fork.

**Comment by taylorotwell** [comment]
I believe this should be fixed on latest 5.4 (unreleased master branch).

**Comment by thecrypticace** [comment]
Oh, cool! I'll take a look today and confirm whether or not this is fixed. (If so that's a _significantly_ simpler implementation than I came up with… 👌)

**Comment by TheoKouzelis** [comment]
Brilliant

**Comment by thecrypticace** [comment]
It appears that it is _not_ fixed. A core piece of the issue is that contextual binding is bypassed entirely when a binding has been setup using `instance()` in the container (see: https://github.com/laravel/framework/blob/c99098fc85c9633db578f70fba454184609c515d/src/Illuminate/Container/Container.php#L522)

I have time today so I can re-open the PR to address the issue. I'm prepping it right now. I'm also prepping an answer to your last comment from the old PR. Taking a bit to figure out what it actually means.

**Comment by thecrypticace** [comment]
Opened: #17031
