### ISSUE TITLE
[suggest] Eloquent - hide sensitive information for json

### ISSUE THREAD

**Issue by kocoten1992** [laravel/framework#12691]
Currently if one using eager loading, Eloquent will have something like

```
App\User {
     id: 1,
     name: "Bob",
     email: "Bob@email.com",
     deleted_at: null,
     created_at: "2016-03-09 16:43:11",
     updated_at: "2016-03-09 16:43:11",
     posts: Illuminate\Database\Eloquent\Collection {
       all: [
         App\Post {
           id: 1,
           user_id: 1,
           title: "Some title",
           body: "Some body text, suppose to be long",
           private: 0,
           deleted_at: null,
           created_at: "2016-03-09 16:44:41",
           updated_at: "2016-03-09 16:44:41",
         },
       ],
     },
   }

```

It is all good except when I throw all of that to json, it will throw up some of id, user_id that I don't want (since it eager loading, I can't use select() to get rid of id and user_id ), could there be a way I define what I don't wanna show in model and call hide(), like

```
protected $hide ['id']                      //User model
protected $hide = ['id', 'user_id']         //Post model

User::whereId(1)->hide()->with('posts')->hide(['id', 'user_id'])->get()
```

Right now, when get the return value from Eloquent, I'm check instanceof and unset manually, would be a trouble if it a big collection.

**Comment by browner12** [comment]
https://laravel.com/docs/5.2/eloquent-serialization#hiding-attributes-from-json

**Comment by kocoten1992** [comment]
thx a ton @browner12 :D
