### ISSUE TITLE
Line Breaks in Envoy Output

### ISSUE THREAD

**Issue by JeanLucEsser** [laravel/framework#12705]
This may be a dumb question but if a script outputs a line break, Envoy does not.

Consider the following script:
```
#!/bin/bash
echo "There's a line break after me!"
echo -e "\n"
echo "Or is there?"
```

When calling this script via Envoy, the line break is not outputted.
Worse, in some scenarios, anything after the line break is stripped from the output.

Am i missing something obvious?

**Comment by GrahamCampbell** [comment]
Thanks, but these issues are for the framework core only please.
