### ISSUE TITLE
Route::auth provides the wrong view when in a Route::group with sub-domain routing

### ISSUE THREAD

**Issue by stefanedberg** [laravel/framework#12708]
If I use this code and visit /password/reset/ I get email.blade.php:

```php
Route::group(['middleware' => 'web'], function() {
  Route::auth();
});
```

If I use this code and visit /password/reset/ I get reset.blade.php:
```php
Route::group(['domain' => '{customer}.'. env('DOMAIN'), 'middleware' => 'web'], function() {
  Route::auth();
});
```

Everything else works as expected.

php artisan route:list looks ok:

```php
| | GET|HEAD | password/reset/{token?} | | App\Http\Controllers\Auth\PasswordController@showResetForm      | web,guest                 |
```

```php
| {customer}.domain.dev | GET|HEAD | password/reset/{token?} |  | App\Http\Controllers\Auth\PasswordController@showResetForm      | web,guest
```

Tested on
Homestead 0.4.2
Laravel 5.2

**Comment by vlakoff** [comment]
Looks like in your 2nd example the `{customer}` route parameter is erroneously passed as `$token` parameter to [ResetsPasswords::showResetForm()](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Auth/ResetsPasswords.php).

**Comment by vlakoff** [comment]
@GrahamCampbell This is not the first time I see issues with shifting of route parameters caused by optional parameters (see also #12630 for instance). There should be room for improvement.
