### ISSUE TITLE
[5.2] TokenGuard: make `inputKey` and `storageKey` configurable

### ISSUE THREAD

**Issue by Andreyco** [laravel/framework#12716]
Allow user to configure names of `inputKey` and `storageKey`.  

This allows user to replace 3rd party packages and use built-in token authentication in existing projects without worrying about breaking functionality of (let's say) 3rd party API clients.  

This only affects authentication when token is passed as query string parameter (header based authentication is out of scope)  

_Current state:_
```
/users/me?api_token=...
```
_Proposed state_
```
/users/me?access_token=...
/users/me?token=...
```

Laravel application pull request (config. only) laravel/laravel#3684
Laravel framework pull request laravel/framework#12714

**Comment by laravel-internals** [comment]
Sorry, we don't process requests/proposals here. Please see https://github.com/laravel/internals/issues.
