### ISSUE TITLE
[5.2] Fluent Route Name are ignored in RouteCollection

### ISSUE THREAD

**Issue by vinicius73** [laravel/framework#12712]
I have this code
![route-definition](https://cloud.githubusercontent.com/assets/1561347/13724739/944c350c-e86d-11e5-871c-339b8f5c2421.png)

Consulting the my list of routes I have
![route-list](https://cloud.githubusercontent.com/assets/1561347/13724745/b915fed6-e86d-11e5-82ab-5cc46b368f41.png)

But when trying to use the route I got the following error.
![route-error](https://cloud.githubusercontent.com/assets/1561347/13724758/108d3f26-e86e-11e5-9920-2ce9a28af8c3.png)

Analyzing the list of routes I got it.
![route-debug](https://cloud.githubusercontent.com/assets/1561347/13724762/4034ddce-e86e-11e5-9e3a-9baa20673c73.png)

**Comment by hernandev** [comment]
:+1:

**Comment by Lidbetter** [comment]
When are you trying to call this?

When defining with the array syntax, the name is added to the routeCollection when the route object is created, when defining fluently the name is added when the app has finished booting all service providers.

I don't think issue is a bug. If you need to access routes by name, before the app has finished booting you can either:
 -  Cache your routes `php artisan route:cache`
 - Define a route name with `['as' => 'rRegister.index', 'uses' => 'RegisterController@index']`

**Illuminate\Foundation\Support\Providers\RouteServiceProvider**

```
/**
     * Bootstrap any application services.
     *
     * @param  \Illuminate\Routing\Router  $router
     * @return void
     */
    public function boot(Router $router)
    {
        $this->setRootControllerNamespace();

        if ($this->app->routesAreCached()) {
            $this->loadCachedRoutes();
        } else {
            $this->loadRoutes();

            $this->app->booted(function () use ($router) {
                $router->getRoutes()->refreshNameLookups();
            });
        }
    }
```

Relevant snippet from application:

**Illuminate\Foundation\Application**
```
    /**
     * Register a new "booted" listener.
     *
     * @param  mixed  $callback
     * @return void
     */
    public function booted($callback)
    {
        $this->bootedCallbacks[] = $callback;

        if ($this->isBooted()) {
            $this->fireAppCallbacks([$callback]);
        }
    }

/**
     * Boot the application's service providers.
     *
     * @return void
     */
    public function boot()
    {
        if ($this->booted) {
            return;
        }

        // Once the application has booted we will also fire some "booted" callbacks
        // for any listeners that need to do work after this initial booting gets
        // finished. This is useful when ordering the boot-up processes we run.
        $this->fireAppCallbacks($this->bootingCallbacks);

        array_walk($this->serviceProviders, function ($p) {
            $this->bootProvider($p);
        });

        $this->booted = true;

        $this->fireAppCallbacks($this->bootedCallbacks);
    }
```

**Comment by vinicius73** [comment]
I tried to use this route within the controllers and the views. 
I know the lifecycle and route cache,  but during development it is not feasible to be generating cache routes.

**Comment by vinicius73** [comment]
Thanks @Lidbetter You're right.

I separate my project in more than one service provider, each carries its own routes file.
I forgot to use this code in them

```php
$this->app->booted(function () use ($router) {
                $router->getRoutes()->refreshNameLookups();
            });
````

I did a quick test and it worked, once again thank you for the clarification.
