### ISSUE TITLE
[5.2] Array validation not working properly after using setData on validator

### ISSUE THREAD

**Issue by HolgerW1** [laravel/framework#12717]
The constructor of a ```Illuminate\Validation\Validator``` instance uses the ```explodeRules``` method to add rules for each array element of an array element validation rule.

Calling ```setData``` on the other hand does not refresh/rebuild the needed array element rules. Which may cause array elements to not be validated.

Example:
let's say we instantiate a validator with the rule ```'languages.*' => 'integer|between:1,100'``` and some data ```['languages' => [1, 2]]```. The constructor will then explode the language rules and create and add two additional rules for the array elements ```languages.0``` and ```languages.1```.

If you now call ```setData``` with ```['languages' => [3, 4, 999]]``` on the same validator instance the third element with the value of 999 will never get validated since we still only have the 2 rules for ```languages.0``` and ```languages.1``` but none for ```languages.2```. I.e. the validator instance will not fail but pass upon validation.

**Comment by vlakoff** [comment]
ping @themsaid :)

**Comment by themsaid** [comment]
hmmm, yeah @HolgerW1 is right, I wonder why this method exists `setData()` since the data can be provided in the constructor already. I mean what's the use case of resetting the data after creating the Validator instance.

**Comment by TomKita** [comment]
@themsaid I have a wrapper around the validator. I create the rules and validator and inject it into my controllers. I then want to setData on the validator.

**Comment by themsaid** [comment]
I see, I'm working on a PR to fix that.

**Comment by themsaid** [comment]
@HolgerW1 the two methods should work as expected in the next release.

**Comment by HolgerW1** [comment]
@themsaid that's good news, thanks for the info!
