### ISSUE TITLE
expectsEvents not working according to the documentation

### ISSUE THREAD

**Issue by jcrawford** [laravel/framework#12711]
I have the following test case..

```php
<?php
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class UserEmailNotificationsTest extends \TestCase
{
    use DatabaseTransactions;

    public function testMemberNewCommentEmailNotification()
    {
        $community = factory(Community::class)->create();

        $admin = factory(User::class, 'superadmin')->make();
        $admin->community_id = $community->id;
        $admin->save();

        $asset = factory(Asset\Video::class)->make();
        $asset->community_id = $community->id;
        $asset->user_id = $admin->id;
        $asset->save();

        $user = factory(User::class)->make();
        $user->community_id = $community->id;
        $user->created_by = $admin->id;
        $user->save();

        $group = factory(Group::class)->make();
        $group->created_by = $admin->id;
        $group->community_id = $community->id;
        $group->save();


        $groupMedia = factory(GroupMedia::class)->make();
        $groupMedia->asset_id = $asset->id;
        $groupMedia->user_id = $user->id;
        $groupMedia->group_id = $group->id;

        $this->expectsEvents('eloquent.saving: GroupMedia');
        $groupMedia->save();


        $groupUser = factory(GroupUser::class)->make();
        $groupUser->user_id = $user->id;
        $groupUser->group_id = $group->id;
        $groupUser->created_by = $admin->id;
        $groupUser->save();

        $this->expectsEvents('eloquent.created: GroupUser');

        $comment = factory(Comment::class)->make();
        $comment->media_id = $groupMedia->id;
        $comment->user_id = $user->id;
        $comment->save();

        $this->expectsEvents('eloquent.created: Comment');

    }
}
```

According to the documentation ```$this->expectsEvents()``` should verify that the events are fired but also stop it from running the event handler callback.

I kept getting an error that the event was not being fired so I went to the event handler code and added an echo statement.  I then ran my unit tests again.  This time I saw the echo from the event handler and it still stated the event was not being fired.

```
➜  l5_media_communities git:(laravel-5.2-testing) ✗ phpunit
PHPUnit 5.2.10 by Sebastian Bergmann and contributors.

.E                                                                  2 / 2 (100%)
YES THE EVENT HANDLER HAS BEEN EXECUTED!


Time: 1.07 seconds, Memory: 27.25Mb

There was 1 error:

1) UserEmailNotificationsTest::testMemberNewCommentEmailNotification
Exception: These expected events were not fired: [eloquent.saving: GroupMedia]

/Users/jcrawford/Dropbox/Work/Viddler/Repositories/l5_media_communities/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MocksApplicationServices.php:44
/Users/jcrawford/Dropbox/Work/Viddler/Repositories/l5_media_communities/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php:127

FAILURES!
Tests: 2, Assertions: 1, Errors: 1.
```

As you can see the uppercased string is coming from my event subscriber method that is triggered when the eloquent.saving: GroupMedia event is fired.

The second paragraph in the [documentation](https://laravel.com/docs/5.2/testing#mocking-events) is where I saw that the event handler should not be executed.  

The BIGGER issue I am having is being told that the event did not fire when it actually did, with it reporting like that my tests always fail.

**Comment by jcrawford** [comment]
I have also tried moving the call to ```$this->expectsEvents('eloquent.saving: GroupMedia')``` to be above the ```$groupMedia->save()``` call and it still reports that the event was not fired, and it also still executes the event handler code.

**Comment by jcrawford** [comment]
I was improperly using ```expectsEvents```  as it should only be called once with an array of events being passed into it.  Now the only problem seems to be that ```expectsEvents``` doesn't handle the until method calls.

**Comment by arrilot** [comment]
Are you sure that `'eloquent.saving: GroupMedia'` is the correct event name? I don't quite remember but it seems to me that there should be a FQCN of a model.

**Comment by GrahamCampbell** [comment]
All events were renamed in 5.2. That event name isn't correct.

**Comment by jcrawford** [comment]
That event name is correct, you can see so in the source code..

[Illuminate/Database/Eloquent/Model.php](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/Model.php#L1281)

It is an event thrown by Eloquent.

**Comment by lagbox** [comment]
@GrahamCampbell no, not all events have been renamed in 5.2.

**Comment by lagbox** [comment]
@arrilot In this particular project, his model's are not namespaced.

**Comment by GrahamCampbell** [comment]
I think it only works with the object events then?

**Comment by jcrawford** [comment]
Ok so it is half baked and expectsEvents can only be used to test your own class based events?  Will this method be refactored so that in the future it will support internal string based events or is the plan to get all laravel 5 events moved over to be class based?

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell. This seems like we could definitely improve this for 5.3.

**Comment by taylorotwell** [comment]
I dont think it's a matter of classes vs strings... The mock is just checking for `fire` and not `until`.

**Comment by GrahamCampbell** [comment]
> I dont think it's a matter of classes vs strings

Yeh, that's why I re-opened it.

**Comment by GrahamCampbell** [comment]
I was just making the point that I'd like to see more object events for consistency anyway, but that's unrelated.

**Comment by thiagof** [comment]
http://stackoverflow.com/questions/36090425/laravel-5-2-event-testing-expectsevent-not-seeing-the-event-fired-although-it-i

**Comment by Mastergalen** [comment]
Same thing happened to me, `$this->expectsEvent()` was not detecting that the event was being fired or prevent it from propagating to the event listeners..

Previously, I was firing my events using `Event::fire(new Event())`. I tried changing it to `event(new Event())` and the test suddenly works correctly now, with it detecting that the event has been fired and silencing the event.

**Comment by GrahamCampbell** [comment]
Closing since this has been changed in 5.3.x
