### ISSUE TITLE
Database Config Schema Prefix

### ISSUE THREAD

**Issue by nisaac2fly** [laravel/framework#12724]
I would like to add a schema name to the database configuration. Would it be possible to add the functionality to the prefix configuration section or could we add another configuration option for schema? 

```php
'sqlsrv' => [
    'driver'   => 'sqlsrv',
    //...
    'prefix'   => 'schema_name.',
    // or
    'schema' => 'schema_name'
],
```

# Problems with using prefix

When trying to use the prefix config option it gives me a blank page. When digging into the framework code the error comes from `\Illuminate\Database\Grammar::wrap()` method. Probably around here `$segments = explode('.', $value);`.

I also noticed a few problems in the schema grammar for sql server driver. 

`\Illuminate\Database\Schema\Grammars\SqlServerGrammar::compileTableExists()`

```sql
-- CURRENT METHOD OF CHECKING IF A TABLE EXISTS
select * from sysobjects where type = 'U' and name = 'demo.migrations';
-- SELECT ALL TABLES IN DATABASE WITH THE NAME "migrations"
select * from sysobjects where type = 'U' and name = 'migrations';
-- WILL RETURN EMPTY ROW IF NO TABLE NAME FOUND
select * from sysobjects where type = 'U' and name = 'invalid.migrations';

-- NEW METHOD OF CHECKING IF A TABLE EXISTS
-- SUPPORTS CHECKING FOR TABLE NAME WITH SCHEMAS
select Object_Id('demo.migrations') as name;
-- SELECT THE FIRST OCCURANCE WITH THE TABLE NAME "migrations"
select Object_Id('migrations') as name;
-- WILL RETURN NULL IF NO TABLE NAME IS FOUND
select Object_Id('invalid.migrations') as name;
```

`\Illuminate\Database\Schema\Grammars\SqlServerGrammar::compileColumnExists()`

Still working with my database manager to figure out a good query for this to support both `schema.table_name` and just `table_name`. 

# Reason for adding this feature

The reason I would like to add this feature is because I currently don't know of a good way to switch between schema's and no schema's based on the environment. 

I was almost able to tweak my way to adding the schema in the constructor of the eloquent model, however, the `migrations` config option in the `config/database.php` file doesn't support `schema.migrations` because the `compileTableExists()` function name will return nothing since the `sysobjects` only include the table name with out the schema. So when running `php artisan migrate:reset` it will return `Migration table not found`. 

# Thoughts?

If there is a better way I should be handling this I would be happy to hear it, otherwise, I would be happy to help get this new feature merged in. 

Thanks.

**Comment by GrahamCampbell** [comment]
Please send proposals to https://github.com/laravel/internals.

**Comment by j4kim** [comment]
Any update on this ?
I think this would be a very useful feature
