### ISSUE TITLE
[5.2] Custom Validators on Array validation.

### ISSUE THREAD

**Issue by SachinAgarwal1337** [laravel/framework#12729]
I have a custom validator, which works fine on normal input fields but when I apply it on a array it wont work. 

This is how I am applying it:
```php
'services'     => "service:{$id},{$type}", // Works but sends the whole array as value.

'serivices.*'  => "required|service:{$id},{$type}|exists:services,id", // Does not work. Validator is not even been called.
```

**Comment by themsaid** [comment]
@SachinAgarwal1337 can you share the code for your customer validator?

**Comment by SachinAgarwal1337** [comment]
@themsaid  Here have a look.
```php
public function validate($attribute, $value, $parameters)
    {
        $location_id = $parameters[0];
        $location_type = $parameters[1];
      

     
            if (!is_null(Department::forServiceLocation($value, $location_id, $location_type))) {
                   return true;
            }

        return false;
    }
```

**Comment by themsaid** [comment]
Well things seem to work running some tests, can you please share a failing test from your end?

**Comment by SachinAgarwal1337** [comment]
@themsaid it not even being called. So When I submit the form, it never checks for this validation and just passes on to next validation. 

p.s I haven't wrote a test yet.

**Comment by fryiee** [comment]
Is the original validation code copy pasted? If so, there's a spelling mistake.
See
```php
'serivices.*'  => "required...
```

should be

```php
'services.*' => "required...
```

**Comment by SachinAgarwal1337** [comment]
@fryiee that was it. My Bad. Did not notice the spelling mistake. Thanks for help :D
