### ISSUE TITLE
[5.2] Select date with Eloquent and Carbon

### ISSUE THREAD

**Issue by PheRum** [laravel/framework#12747]
Hey.
There is a need to select records from a table using Carbon.
Entries are selected, but their processing does not reach 100%, and is always interrupted by 50% not depending on the number of records.

Sample code
```php
<?php

namespace App\Console\Commands;

use App\User;
use Carbon\Carbon;
use Illuminate\Console\Command;

class TestChunk extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'test:chunk';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * TestChunk constructor.
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $model = User::where('updated_at', '<', Carbon::now());
        //$model = User::where('updated_at', '<', '2016-03-17 16:00:00');

        $this->output->progressStart($model->count());  // result 1.000 users

        $model->chunk(1, function ($sql)
        {
            foreach ($sql as $row)
            {
                $row->updated_at = Carbon::now()->addSecond(1);

                /** @var User $row */
                $row->save();

                $this->output->progressAdvance();
            }
        });

        $this->output->newLine(2);
    }
}

```

if the sample design uses `where('updated_at', '<', Carbon::now())` execution is interrupted by 50%
However, if the sample is replaced by the structure `where('updated_at', '<', '2016-03-17 16:00:00')` treatment will be 100%

P.S. This code is all-just a demonstration, not a working version of the script.
You do not need to update all records offer one sql query

Ping @taylorotwell

**Comment by pjmartorell** [comment]
@PheRum I have tried your code using `Carbon::now()` and everything is fine for me (100% execution). Print the old and new updated_at timestamps and check if you are updating records that are already updated or if you are firing events that are updating your records in the background.
