### ISSUE TITLE
Envoy server definitions

### ISSUE THREAD

**Issue by cpass78** [laravel/framework#12751]
More a question really. How come multiple envoy servers have to be defined on a single line? It's messy when having to work with up to 12-15 servers?

Is there a solution to having multiple servers defined on multiple lines?

**Comment by cpass78** [comment]
Closed without any real feedback.. Trying to find a solution to what seems like a design flaw.

Thanks

**Comment by mark86092** [comment]
I think you can ask questions on forum, issue is for bug report

**Comment by cpass78** [comment]
Ive asked several places, larachat, laraslack. none seems to know the answer. Might as well goto the source.

This seems like a bug to me

**Comment by arrilot** [comment]
It's quite simple.
```
@setup
    $servers = [
    	'vs1' => '-A www-data@1**.**.**.*1', 
    	'vs2' => '-A www-data@1**.**.**.*2', 
    	'vs3' => '-A www-data@1**.**.**.*3',
	];
@endsetup

@servers($servers)
```

**Comment by cpass78** [comment]
Thank you so much for that super simple answer. That is what i was doing but I didn't set @servers again.  Working now!
