### ISSUE TITLE
Storage: Get only files of certain type from directory

### ISSUE THREAD

**Issue by lukasoppermann** [laravel/framework#12756]
Hey,

I did not find it, so please let me know if it is already possible. I think it would be useful, to get the possibility to retrieve only files of a certain type from a folder.

I see two possibilities, either:

```php
Storage::files('articles', true, ['md','txt'])
```

or with read:

```php
Storage::read('articles/*.md')
```

I think this would be very helpful. Cheers.

**Comment by StefanPrintezis** [comment]
Something like this could work?
```
/**
     * Get an array of all files in a directory.
     *
     * @param  string  $directory
    *  @param  array  $extensions
     * @return array
     */
    public function files($directory, $extensions = [])
    {
        $pattern = $directory.'/*';
        $flags = 0;

        if ($extensions) {
            $pattern .=  '{' . implode(',', $extensions) . '}';
            $flags = GLOB_BRACE;
        }

        $glob = glob($pattern, $flags);
```

**Comment by lukasoppermann** [comment]
Maybe I am getting your wrong @StefanPrintezis  but this is just a method, without using `Storage`, or are suggesting this as an implementation to make this possible with storage?

**Comment by GrahamCampbell** [comment]
The issues here are strictly for bugs only please.
