### ISSUE TITLE
Attach middleware to all method

### ISSUE THREAD

**Issue by furyscript** [laravel/framework#12758]
I have this in Laravel 4.2 `Route::when('*', 'csrf', ['post']);` that insert csrf verification to all post, how can I port to Larevel 5.2 ?

This is my own csrf, without using default provide by Laravel:

```php
<?php
namespace App\Http\Middleware;
use Closure;
use Input;
class VerifyCsrfToken1
{
    public function handle($request, Closure $next)
    {
        $token = $request->ajax() ? $request->header('X-CSRF-Token') : $request->input('_token');
        if ($request->session()->token() === $token) {
            return $next($request);
        }
        throw new TokenMismatchException;
    }
}
```

I created my personal csrf middleware, but I don't know how to attach them on ALL post request

I want to attach it to all post via `Route`'s facade. (file routes.php)

Thanks :)

**Comment by GrahamCampbell** [comment]
> if ($request->session()->token() === $token) {

That is unsafe.

**Comment by furyscript** [comment]
why? @GrahamCampbell
