### ISSUE TITLE
Array Input Validation: Not Validating the "required" Rule

### ISSUE THREAD

**Issue by kozasoft** [laravel/framework#12759]
Hello,
There is an issue with validating array inputs. The "required" rule is not working with array inputs. Even if I do not send any data, the required rule does not produce any error messages. Other rules like "integer", "min", and "max" work very well, but laravel ignores the "required" rule.

**Comment by themsaid** [comment]
@kozasoft please show a code sample.

**Comment by dotuancd** [comment]
I have same issue

Example for my case:

I have custom array `questions`

{
    ...
    "questions": [
        {
            "title": "ABC",
            "required": true
        }
    ]
    ...
}
```

With each question I would like add a required validation for `title` & `required`.

I try:

```
$validator = Validator::make($request->all(), [
    'questions.*.title' => 'required',
    'questions.*.required' => 'required|boolean',
]);
```

But not working.

**Comment by themsaid** [comment]
The following test currently passes, can you please confirm the problem still exists @dotuancd @kozasoft 

```
$data = [
    'questions' => [
        ['title' => 'Jon', 'required' => true],
        ['title' => '', 'required' => null],
    ],
];
$v = new Validator($trans, $data, ['questions.*.title' => 'required', 'questions.*.required' => 'required|boolean']);
$this->assertFalse($v->passes());
```

**Comment by dotuancd** [comment]
@themsaid It working. Thanks so much.
