### ISSUE TITLE
[5.2] Using Cache in unitTest doesn't actually set properly

### ISSUE THREAD

**Issue by J-Katzen** [laravel/framework#12766]
I am trying to use the Cache in a unitTest, however whenever I go to actually grab the value again from the cache, my test shows that the key I tried to set doesn't actually exist and returns null.  My test configuration has the test driver set to array.

```
public function testCache()
{
    Cache::put('test', true);
    $this->assertTrue(Cache::get('test'));
}
```

**Comment by GrahamCampbell** [comment]
Likely the framework hasn't booted. Please make sure your test case extends ours rather than phpunit's default if you want to use facades.

**Comment by J-Katzen** [comment]
ok...is there a way to make sure, because just to double check myself I did the following straight out of the documentation:
```
php artisan make:test CacheTest
```

and then in my tests/CacheTest.php, the only test I am running is the above.  Here's the entire file:
```
<?php

use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Support\Facades\Cache;

class CacheTest extends TestCase
{
    /**
     * A basic test example.
     *
     * @return void
     */
    public function testExample()
    {
        Cache::put('test', true);
        $this->assertTrue(Cache::get('test'));
    }
}
```

**Comment by GrahamCampbell** [comment]
Very odd. Hmm.

**Comment by GrahamCampbell** [comment]
Can you call `Cache::getDefaultDriver()` please?

**Comment by GrahamCampbell** [comment]
and dump the output, or something

**Comment by J-Katzen** [comment]
From php artisan tinker:
```
Cache::getDefaultDriver()
=> "array"
```

**Comment by GrahamCampbell** [comment]
> From php artisan tinker:

No, from your test case please.

**Comment by J-Katzen** [comment]
```
Cache::put('test', true);
var_dump(Cache::getDefaultDriver());
$this->assertTrue(Cache::get('test'));
```
yields: Failed test and `string(5) "array"` from the var_dump

**Comment by sisve** [comment]
`Cache::put` has a nullable $minutes parameter ... but null isn't a valid value. Passing $minutes = null means 
getMinutes return null, and the value isn't stored. Try passing any integer value as a third parameter.

put: https://github.com/laravel/framework/blob/5.2/src/Illuminate/Cache/Repository.php#L197
getMinutes: getMinutes

**Comment by jarischaefer** [comment]
Could this be caused by phpunit.xml? It contains `<env name="CACHE_DRIVER" value="array"/>`. Also, the $minutes = null in getMinutes looks like a bug at first glance.

**Comment by Oyelaking** [comment]
I was having the exact same problem(and nearly pulling my hair out) and setting the minutes in the call to Cache::put solves it. Thanks @sisve.
This definitely looks like a bug.

**Comment by EdgarsK** [comment]
+1

**Comment by surgiie** [comment]
Yeah not sure why this was closed. Passing a integer fixes this when running in tests. Definitely a bug.
