### ISSUE TITLE
[Request] Function to ignore relationship defined in model using $with

### ISSUE THREAD

**Issue by WrongWay** [laravel/framework#12761]
So there is a problem i've encountered while using polymorphic relationship, and getting related model of that relationship #6368. The only way to achieve that is by using `$with` in the model. But this aproach causes laravel to perform an extra query on pages where I already have that relation loaded. For example, I have a page where I load an `Artist` by it's slug from the url, and it's `Song` also by the slug from the url. If I use `$with = ['artist']` in `Song` model, I get an extra query for the `Artist` I already loaded. So my proposal is a `without($relations : array())` method to let me ignore some or all of the relationships defined via `$with`.

**Comment by laravel-internals** [comment]
Sorry, we don't process requests/proposals here. Please see https://github.com/laravel/internals/issues.
