### ISSUE TITLE
response can not be cached

### ISSUE THREAD

**Issue by xujif** [laravel/framework#12770]
laravel send every response with a header of  'set-cookie',so that can not cached by any Reverse Proxy.
I notice that in Illuminate\Session\Middleware\StartSession
`$this->addCookieToResponse($response, $session);` 
on every response to update the lifetimeof cookie.
I suggest:   
1. abandon the lifetime control of cookie,just controlled by session
2. when 'expire_on_close' is true ,check if 'session id' if is changed,then to update

**Comment by daids** [comment]
you should be adding excepts in app/Http/Middleware/EncryptCookies.php:14

**Comment by xujif** [comment]
@daids It still will response a  'set-cookie' header,just not be encrypt。
and a set-cookie response can not be cached

**Comment by daids** [comment]
If not encrypt,that will be skipping.
[EncryptCookies.php](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Cookie/Middleware/EncryptCookies.php#L125-L133)
