### ISSUE TITLE
[5.1] Blueprint, how can I set the field auto increment but not a primary key?

### ISSUE THREAD

**Issue by jerrydev** [laravel/framework#12807]
I create a migration table:

    Schema::create('files', function (Blueprint $table) {
        $table->bigInteger('order', true)->unique();
        $table->char('id', 32)->primary();
        $table->string('url');
    });

> [Illuminate\Database\QueryException]
>  SQLSTATE[42000]: Syntax error or access violation: 1068 Multiple primary key defined (SQL: alter table `files` add primary key `files_id_primary`(`id`))

>  [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1068 Multiple primary key defined

It means : the second parameter `true` of bigInteger will  set the field order to primary key.
But I already have a primary key. :(

How can I solve this problem?  Thanks.

**Comment by GrahamCampbell** [comment]
Please ask on the forums.
