### ISSUE TITLE
maraia db always drop hhvm when flagged both during vagrant up

### ISSUE THREAD

**Issue by masterpowers** [laravel/framework#12806]
I cant find any laravel homestead issue so im posting here at laravel/framework
It seems that when you flagged maria db , 
during deletion of mysql, hhvm will be incompatible thus will be remove in the process..

I hope there is an easier way to spun a new laravel/homestead instance 
with hhvm+mariadb
without having to hhvm manually after your provisioned failed

**Comment by GrahamCampbell** [comment]
Sorry, we only process framework bugs here.
