### ISSUE TITLE
[Feature Request] migrate:reset ignores foreign key constraints

### ISSUE THREAD

**Issue by bkuhl** [laravel/framework#12805]
I've encountered this many times and can't think of a scenario where a `php artisan migrate:reset` should obey foreign keys, at least in the local development environment.  I've cloned the framework repo and am considering a pull request but was hoping to get some feedback on an acceptable implementation within https://github.com/laravel/framework/blob/master/src/Illuminate/Database/Migrations/Migrator.php#L194 before I submitted a PR so I could focus my efforts in the right direction.

It looks like all officially supported database drivers support foreign key implementation and I'm not aware of a database that doesn't.  With that in mind, I was considering adding `disableKeyChecks()` and `reenableKeyChecks()` steps to the reset process.

If implemented across all supported database drivers, would this be a branch that could be a candidate to be merged in?

**Comment by GrahamCampbell** [comment]
Please send proposals to https://github.com/laravel/internals.
