### ISSUE TITLE
$customAttributes for array validation broken since 5.2.23

### ISSUE THREAD

**Issue by stefro** [laravel/framework#12819]
Hi,
As of 5.2.23 I'm not able to set customAttributes for array validation like this:
```
$customAttributes = [
    'title.nl' => 'Titel (Nederlands)',
    'title.en' => 'Title (English)'
]
```
When switching back to 5.2.22 everything works as expected.

**Comment by themsaid** [comment]
Noted, and a fix was proposed in https://github.com/laravel/framework/pull/12822

**Comment by stefro** [comment]
Thanks!
