### ISSUE TITLE
RRD extension rrd_fetch() not found

### ISSUE THREAD

**Issue by JeremyGreaux** [laravel/framework#12816]
Hi, 

I have installed php5-rrd extension on my project. (http://php.net/manual/fr/book.rrd.php)
When I use a function of this lib in a controller, laravel can't find this function.
`Fatal error: Call to undefined function rrd_fetch()`

The extension is installed, and works well with a simple php file.

**Comment by GrahamCampbell** [comment]
Sorry, I don't see how this is related to laravel?

**Comment by JeremyGreaux** [comment]
I think it's related because with laravel, I can't use function of php5-rrd extension

**Comment by GrahamCampbell** [comment]
Laravel has nothing to do with that. It's just the same as any other php code.

**Comment by JeremyGreaux** [comment]
Humm with simple php file outside laravel it's work but not in the controller.
But okay, it's not Laravel ^^

Thank a lot for your reactivity
