### ISSUE TITLE
problems with persisting sessions in laravel 5.2

### ISSUE THREAD

**Issue by lab6net** [laravel/framework#12820]
Hello

I started working on a new project, and i decided that i will give a try new laravel 5.2 (was using 4.x in previous projects).

I was testing sessions and i found out some strange behavior. Sessions are working correctly on chrome browser, but other browsers seems to drop sessions immediatly (tested on firefox and IE 10).

Im using homestead with vagrant on local environment (windows with virtual box). I defined my own test domain in host file and im accessing my project through that domain.

Im using database driver for sessions, and my routes are using "web" middleware. 

Requests from chome maintain one record in session table, but requests from firefox create new entry every time i refresh that page.

Standard php sessions are working fine, this problem appears only when im using laravel sessions.

So anyone solved similar problem ?

**Comment by lab6net** [comment]
Also i just noticed, that i forced session->save() in code, without that chrome also didn't want to remember sessions.

**Comment by danieliancu** [comment]
@lab6net take a look at this issue #13000, it's likely the problem you're having.
