### ISSUE TITLE
[5.2] Periodically getting "array_merge(): Argument #2 is not an array" in loadManifest() method

### ISSUE THREAD

**Issue by swayok** [laravel/framework#12826]
Hi. Sometimes I'm getting an error `array_merge(): Argument #2 is not an array` triggered by 

    public function loadManifest()
    {
        if ($this->files->exists($this->manifestPath)) {
            $manifest = $this->files->getRequire($this->manifestPath);
            return array_merge(array('when' => array()), $manifest);
        }
    }
in complied.php
Error trace in production displys this:

    3. in /var/www/platido/bootstrap/cache/compiled.php line 7537
    at array_merge( array( 'when' => array( ) ), '1' )

    4. in /var/www/platido/bootstrap/cache/compiled.php line 7487
    at Illuminate\Foundation\ProviderRepository->loadManifest( )

In debug this:

    3. in /var/www/platido/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php line 174
    at array_merge( array( 'when' => array( ) ), '1' )

    4. in /var/www/platido/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php line 54
    at Illuminate\Foundation\ProviderRepository->loadManifest( )

Same error happened earlier when site was in debug mode. It happened due to invalid services.json or services.php. In production it seems like the reason of this error too.
Error happens periodically and I do not update anything on server when it happens. It looks like just random situation but happens every day several times. I cannot find what triggers it but it seems like services.json or services.php became corrupted somehow. On forums (https://laracasts.com/discuss/channels/general-discussion/getting-weird-error-in-laravel?page=1) people found possible reason - it seems like 2 requests simultaneously modify services.json or services.php making a mess in it. 
It seems like writing manifest does not lock the file and it is possible to be corrupted:

    public function writeManifest($manifest)
    {
        $this->files->put(
            $this->manifestPath, '<?php return '.var_export($manifest, true).';'
        );

        return array_merge(['when' => []], $manifest);
    }

I'l try to catch this error and post corrupted file's contents here

**Comment by GrahamCampbell** [comment]
Looks like you forgot to clear you compiled files after an upgrade.

**Comment by swayok** [comment]
My composer.json:

     "post-update-cmd": [
            "php artisan clear-compiled",
            "php artisan ide-helper:generate",
            "php artisan vendor:publish --tag=public --force",
            "php artisan optimize",
            "php artisan queue:restart"
    ]

1. Doesn't `php artisan clear-compiled` clean this files?
2. Why this happens long after I have updated any file?

**Comment by ibarral** [comment]
Hello @swayok! did you found a solution to this? I'm having the same problem here.

Thanks!

**Comment by swayok** [comment]
@ibarral This problem never appeared since I upgraded app to Laravel 5.3+

**Comment by ibarral** [comment]
OK, thanks for your help! I suppose that's a bug in Laravel...

**Comment by cgvalayev** [comment]
This happened to me with laravel 5.6 because container ran out of memory and wasn't able to write service.php inside bootstrap/cache
