### ISSUE TITLE
[L5.2] Wrong Auth Driver causes unexpected application end without errors

### ISSUE THREAD

**Issue by iget-esoares** [laravel/framework#12821]
**Framework version:** 5.2.24
**PHP version:** PHP 7.0.4-6+deb.sury.org~trusty+1

If a wrong (unexistent) auth driver is choose on `config/auth.php` setting, running anything that uses auth() facade will cause an unexpected end of execution.

# Reproducing the bug

1. Install a brand new Laravel 5.2.24
2. Change the auth driver on `config/auth.php` to `foobarbiz`
3. Run `php artisan tinker`
4. Run `auth()->attempt([])`
5. The tinker will close without errors. Also anything will close, not only on CLI.

**Comment by GrahamCampbell** [comment]
Sounds like your php config is suppressing the fatal error.

**Comment by iget-esoares** [comment]
@GrahamCampbell Looks like this isn't the problem:

```
esoares@esoares-desktop:~/Code/test$ php artisan tinker -vvv
Psy Shell v0.7.2 (PHP 7.0.4-6+deb.sury.org~trusty+1 — cli) by Justin Hileman
>>> error_reporting()
=> -1
>>> auth()->attempt([]);
esoares@esoares-desktop:~/Code/test$ 
```

**Comment by iget-esoares** [comment]
The same occours using PHP5.6:

```
esoares@esoares-desktop:~/Code$ php5.6 artisan tinker
Psy Shell v0.7.2 (PHP 5.6.19-6+deb.sury.org~trusty+1 — cli) by Justin Hileman
>>> error_reporting()
=> -1
>>> auth()->attempt([]);
esoares@esoares-desktop:~/Code$
```

**Comment by iget-esoares** [comment]
Tracking the issue, I found this piece of code:

**vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php** Method `Resolve($name)` at Line 89:
```
        if (isset($this->customCreators[$config['driver']])) {
            return $this->callCustomCreator($name, $config);
        } else {
            return $this->{'create'.ucfirst($config['driver']).'Driver'}($name, $config);
        }
```

The problem is happening here: 

Since the driver name does not exists, it goes to the `else`, try to call `$this->createWronDriverNameDriver($name, $config)`.

This call will be catch by the `__call` magic method, that will call `$this->guard()`, that will again call `$this->resolve()`, resulting in a infinite loop.

**Comment by iget-esoares** [comment]
@GrahamCampbell I've made a Pull Request to solve this infinite loop bug. Please, take a look.

**Comment by GrahamCampbell** [comment]
Thank you so much!
