### ISSUE TITLE
[5.2] Making Schema Builder in ServiceProvider - schemaGrammar is null

### ISSUE THREAD

**Issue by codingquark** [laravel/framework#12838]
When resolving Builder in service provider:

```php
$schemaBuilder = $application->make(\Illuminate\Database\Schema\Builder::class);
```

`$schemaBuilder`'s `$schemaGrammar` remains `null`.

However, if we make the builder the following way:
```php
$connection = $application->make(\Illuminate\Database\Connection::class);
$connection->useDefaultSchemaGrammar();
$schemaBuilder = $application->make(\Illuminate\Database\Schema\Builder::class, [$connection]);
```
things work as expected.

Is this behavior expected or wrong?

**Comment by GrahamCampbell** [comment]
You can only resolve thing in boot, not register.

**Comment by codingquark** [comment]
Even in boot, it is the same case - $schemaGrammar remains null.

**Comment by GrahamCampbell** [comment]
Is it booted after laravel's native providers have booted?

**Comment by GrahamCampbell** [comment]
Actually, this behaviour looks to be expected.

**Comment by GrahamCampbell** [comment]
You passing through that other param means we don't reuse the previous instance.

**Comment by codingquark** [comment]
Wouldn't that mean the automatic resolution of Connection object is going wrong somewhere while initializing Builder?

**Comment by GrahamCampbell** [comment]
No. You just can't resolve things like that.

**Comment by codingquark** [comment]
Also, the provider is last in the config array, so being booted the last.

Then, what I'm doing for resolution is righ - passing extra argument?

**Comment by GrahamCampbell** [comment]
You need to basically do the equivalent of `DB::connection($name)->getSchemaBuilder();`

**Comment by GrahamCampbell** [comment]
`app(Illuminate\Database\DatabaseManager::class)->connection($name)->getSchemaBuilder();`

**Comment by codingquark** [comment]
Okay. That works. So what you're saying is that I should not use $app->make during register() at all?

**Comment by GrahamCampbell** [comment]
> So what you're saying is that I should not use $app->make during register() at all?

In general, yes. Basically, just be careful when you use it. Laravel's internals take a bit of getting used to. ;)

**Comment by GrahamCampbell** [comment]
You can of course use it inside closures in the register method, because they are not executed in the register phase, if you see what i mean. Laravel will only read config in the boot phase, so if you start resolving stuff too earlier, you could find stuff's not been registered yet, or other stuff's not been hooked up yet.

**Comment by codingquark** [comment]
```php
$this->app->singleton(PostsController::class, function (\Illuminate\Contracts\Foundation\Application $application) {
    $schemaBuilder = app(\Illuminate\Database\DatabaseManager::class)->connection(config('database.default'))->getSchemaBuilder();

    return new PostsController($schemaBuilder);
});
```

I've omitted the details in this snippet, but I think it adheres to what you're saying - using it inside closure, correct?
