### ISSUE TITLE
[5.2] Validation MIME Types (File) vulnerability

### ISSUE THREAD

**Issue by dariusll** [laravel/framework#12834]
```
$rules = array('files' => 'mimes:jpeg,jpg,png,gif,pdf,bmp, zip');
$validator = Validator::make($fileValidator, $rules);
if ($validator->fails()) {
    return "Error";
}
//save file
```
1. Create image with injected PHP or JavaScript code.
2. Use Burp Suite proxy tool to intercept POST request.
3. Change file name parameter from "danger.php.jpg" to "danger.php".
4. Validator sees file as image and allows to upload.
5. File with malicious code executed after opening.

I think this validation "MIME Types (File)" for files shouldn't be in documentation, because its easy to bypass.
https://laravel.com/docs/5.2/validation#rule-mimes

**Comment by w4** [comment]
Please remove your message and email Taylor (see readme)
