### ISSUE TITLE
[5.2] firstOrCreate function skip accent character

### ISSUE THREAD

**Issue by evertramos** [laravel/framework#12833]
When using the function below:

    MyModel::firstOrCreate([
        'name'    =>   'Avô',
    ]);

And in the next one:

    MyModel::firstOrCreate([
        'name'    =>   'Avó',
    ]);

It does not insert a new record (as it should), it brings the prior one. Please note that 'Avô' it´s a different word of 'Avó'.

**Comment by GrahamCampbell** [comment]
This is probably due to misconfiguration of the database to use ascii encoding.

**Comment by evertramos** [comment]
@GrahamCampbell it´s recording correctly in the database... so, how could it be an enconding? I mean, evertyhing is set to utf8, database, html, even the script charset.
