### ISSUE TITLE
Problem laravel 5.2.23 to interact with pages .css .js 

### ISSUE THREAD

**Issue by eliasraf16** [laravel/framework#12836]
i have laravel version 5.2.23 and it doesnt read the .css or the js files i'm pretty much stuck i tagged them according to the laravel 5.2 new rules <link rel="stylesheet" type="text/css" href="{{!! asset('assets/css/style.css')!!}}"> but on the view source u can see it as an active link but when it comes to click them it gives this error ** NotFoundHttpException in RouteCollection.php line 161:** i don't know what to do :(

**Comment by ArjanSchouten** [comment]
That's due to your nginx or apache configuration. This is not an issue for Laravel. Ask on a forum!
