### ISSUE TITLE
BladeCompiler parse error

### ISSUE THREAD

**Issue by vincenzoraco** [laravel/framework#12849]
Line 808 - framework/src/Illuminate/View/Compilers/BladeCompiler.php

Somehow the variable $expression does not put the apostrophe after "layouts.app"

`<?php echo $__env->make('layouts.app, array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>`

but should be

`<?php echo $__env->make('layouts.app', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>`

I solved editing the line 808 adding an apostrophe after $expression but it should not be the way to fix it.

This happens with the extends function only.

**Comment by mark86092** [comment]
You may have typo in your child template. If this is a bug, can you provide more detail?

**Comment by vincenzoraco** [comment]
Yes you were right. When I used `@include('layouts.app')` I forgot to close the quotation marks.

Thank you a lot.
