### ISSUE TITLE
Illuminate\Database\Eloquent\Collection got an "Call to a member function getKey() on a non-object"                                 

### ISSUE THREAD

**Issue by motian** [laravel/framework#12853]
Sample like this,
```
$collection = SomeModel::all();
$list = $collection->lists('an_attribute');
$list->diff($anotherCollection);
```
SomeModel::all() got an instance of  Illuminate\Database\Eloquent\Collection,
howerver, when I use the function $collection->lists()  or some others.
The code downstairs shows that I will get an instance of Illuminate\Database\Eloquent\Collection.
```
    /**
     * Get the values of a given key.
     *
     * @param  string  $value
     * @param  string|null  $key
     * @return static
     */
    public function pluck($value, $key = null)
    {
        return new static(Arr::pluck($this->items, $value, $key));
    }

```
It's the problem, when I lists() the items I got an instance of Illuminate\Database\Eloquent\Collection.
Howerver, the items of the Collection currently is not an instance of Model.

I suggest that check if the $item is an instance of Model, if not, return parent::diff($items); 
```
    /**
     * Diff the collection with the given items.
     *
     * @param  \ArrayAccess|array  $items
     * @return static
     */
    public function diff($items)
    {
        $diff = new static;

        $dictionary = $this->getDictionary($items);

        foreach ($this->items as $item) {
/*
The item may not be an instance of Model, it calls an  
"Call to a member function getKey() on an non-object"
*/
            if (! isset($dictionary[$item->getKey()])) {
                $diff->add($item);
            }
        }

        return $diff;
    }
```

**Comment by GrahamCampbell** [comment]
Thank you. We're open to PRs please. :)

**Comment by alexjose** [comment]
+1

**Comment by zloter** [comment]
This issue is already resolve? In my project, based on 5.3.30 this bug still occurred when I use 'map' function.
