### ISSUE TITLE
Illuminate/Config PHP Version

### ISSUE THREAD

**Issue by VizuaaLOG** [laravel/framework#12858]
Illuminate/Config seems to require php 5.6.x +. Whereas the same component inside the Laravel framework requires 5.5.9. Is this a mistake? Seems strange that the config on its own requires a higher PHP level.

**Comment by GrahamCampbell** [comment]
No, it doesn't. Only 5.3.x will impose that version constraint.

**Comment by GrahamCampbell** [comment]
You're probably looking at the master branch, rather than 5.2.
