### ISSUE TITLE
Routes are not ordered when using request()->segment(1) as a prefix

### ISSUE THREAD

**Issue by FajrAljunaid** [laravel/framework#12862]
This is a code example of the problem:
```
//routes
Route::group(['prefix' =>  request()->segment(1) ], function(){
  //routes
});
//routes
```

Normally, routes are in the order they were written at, but when using group with `request()->segment(1)` routes just get disarranged (not just inside the group itself, but all routes).

Note: This issue is in version 5.1 , don't know about the other versions.

**Comment by GrahamCampbell** [comment]
You can't call the request helper like that when defining routes. It won't refer to the current request.
