### ISSUE TITLE
Laravel 5.2 Auth doesn't give error on wrong credentials or empty form

### ISSUE THREAD

**Issue by M1hai** [laravel/framework#12863]
The errors in red are missing from the login page i created 2 apps one I edited on I didn't both have the same Auth problem. It doesn't happen in my previous 5.2 apps
if i dump the $errors array that usually held the error message I get this:
object(Illuminate\Support\ViewErrorBag)#173 (1) { ["bags":protected]=> array(0) { } }

**Comment by GrahamCampbell** [comment]
Please ask on the forums.

**Comment by sger** [comment]
any solution on this ?

**Comment by M1hai** [comment]
well it appears to be working now...i just created a new laravel app today...and that problem didn't occur anymore...to be honest I don't know what happened
