### ISSUE TITLE
"Web" middleware being assigned to routes twice

### ISSUE THREAD

**Issue by ian-paterson** [laravel/framework#12877]
When routes are added to the "web" middleware group it is assigning the middleware twice.

I haven't made any changes after install other than running `php artisan migrate` and `php artisan make:auth`

![image](https://cloud.githubusercontent.com/assets/8619663/14063346/185cc1d0-f39b-11e5-95bc-177afea47387.png)

**Comment by GrahamCampbell** [comment]
Out of the box, the web group is used by default now. A very recent change.

**Comment by GrahamCampbell** [comment]
The auth:make command never got updated for the new app system. Not sure how we can fix this.

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell.

**Comment by themsaid** [comment]
@GrahamCampbell I removed the middleware registration from the stubs, not sure if they were registered for a reason.

**Comment by GrahamCampbell** [comment]
They are there so it works on 99% of all laravel 5.2 apps out there atm.

**Comment by GrahamCampbell** [comment]
This is only broken on the newest 5.2 apps

**Comment by themsaid** [comment]
The `web` middleware group is registered in the constructor of the generated `HomeController` as well as the generated routes group, so at least it should be removed from the `HomeController` constructor.

**Comment by vlakoff** [comment]
> This is only broken on the newest 5.2 apps.

"only". :trollface:

**Comment by dandart** [comment]
Yep - I made one just yesterday - so removing the web middleware from the added content in routes.php solved it for me - and I added to this SO post to help others that have just created new apps with this issue:
https://stackoverflow.com/questions/34438463/laravel-5-2-errors-not-appearing-in-blade/36253445#36253445

**Comment by GrahamCampbell** [comment]
Closing this since we have Jeffery's PR.
