### ISSUE TITLE
adding remote_port to http\request::fingerprint()

### ISSUE THREAD

**Issue by Cyrille37** [laravel/framework#12872]
Hi,
I know it's impossible to construct a secure fingerprint from http client data but it could be nice to add _SERVER["REMOTE_PORT"] in [Illuminate\Http\fingerprint()](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Http/Request.php) computing.
Effectively this value does not change when normally requesting with internet browser due to keep-alive connection feature. So the remote port is a useful data because of many clients usually share the same IP address.

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. Feel free to send a PR.
