### ISSUE TITLE
redirect() no longer works with non-ascii characters

### ISSUE THREAD

**Issue by zachleigh** [laravel/framework#12891]
Redirecting with routes that contain non-ascii chars breaks after upgrade to v5.2.26. Example:
```
redirect('/é');
```
Redirects to the route `/Ã©`.

**Comment by GrahamCampbell** [comment]
Upgrade from what version please?

**Comment by zachleigh** [comment]
From 5.2.13.

**Comment by GrahamCampbell** [comment]
Could you try and pinpoint the exact version it breaks please.

**Comment by zachleigh** [comment]
Seems to be something on my end. Couldn't track down the version it broke so installed a fresh copy of Laravel 5.2.26. Seems to work. Hmm...
