### ISSUE TITLE
PDO::MYSQL_ATTR_LOCAL_INFILE  not working on 5.2.26

### ISSUE THREAD

**Issue by zofe** [laravel/framework#12893]
I've two projects  one Laravel 5.0  and the other Laravel 5.2 (5.2.26),  the second one is  just a rebuilt of first one.
They both use:
the same db, same user, same db configuration, on the same mysql server / port.
I've a console command again the same on both projects with:

    \DB::connection()->getPdo()->exec("LOAD DATA LOCAL INFILE '" . storage_path('myfile.txt') 
    . "' IGNORE INTO TABLE mytable LINES TERMINATED BY '\\n' IGNORE 1 LINES (mytable)");

the configuration of database.php option on both projects is: 

    'options' => [PDO::MYSQL_ATTR_LOCAL_INFILE => true]

It works  only on the 5.0  project.  On laravel 5.2  it throw:
SQLSTATE[42000]: Syntax error or access violation: 1148 The used command is not allowed with this MySQL version

(note on mysql localinfile is on)
if I debug in tinker  i can see that the options is loaded:

    >>> dd(\DB::connection()->getConfig('options'))
    array:1 [
      1001 => true
    ]

**Comment by GrahamCampbell** [comment]
What MySQL version do you have?

**Comment by GrahamCampbell** [comment]
I know there were a few changes in 5.1 and 5.2 which required newer MySQL versions, but very few.

**Comment by zofe** [comment]
mysql 5.5.38-0ubuntu0.14.04.1

**Comment by zofe** [comment]
I can confirm:

this configuration solve my issue on 5.2:

'mysql' => [
            'driver' => 'mysql',
            ...
            'options' => [\PDO::MYSQL_ATTR_LOCAL_INFILE => true, \PDO::MYSQL_ATTR_READ_DEFAULT_GROUP=>'client'],
        ],
