### ISSUE TITLE
Eloquent Collection's makeVisible method only works when using the 'hidden' property

### ISSUE THREAD

**Issue by marcmascarell** [laravel/framework#12894]
I came to an unexpected result when using **makeVisible** method and not making the attributes I passed visible, so I saw that the reason was that the method will only make visible the fields if them are in the 'hidden' property.

Model.php
```php
    protected $visible = ['remaining', 'restored_at'];
```

```php
    // id not returned
    $model->all()->makeVisible(['id'])->toArray();
```

Instead having Model.php
```php
    protected $hidden = ['id'];
```

```php
    // id returned
    $model->all()->makeVisible(['id'])->toArray();
```

The easy workaround would be using hidden property but I'm making a package and I need to get a full properties toArray() no matter which property the user uses.

Is this the expected behaviour?

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell.

**Comment by tobeorla** [comment]
I was facing the same problem. I ended using the hidden property.

**Comment by toby1991** [comment]
....I've run into this bug too...
debug for a total afternoon!

thks @marcmascarell

**Comment by GrahamCampbell** [comment]
Fix already merged.

**Comment by GrahamCampbell** [comment]
Will be available in the next release.
