### ISSUE TITLE
Nested collection operator 

### ISSUE THREAD

**Issue by deddysetyadi** [laravel/framework#12892]
I have a collection : 

```json
{  
   "datetime_out":"2016-03-29 11:44:47",
   "datetime_in":"2016-03-29 11:43:46",
   "vehicle_id":1,
   "transaction":[  
      {  
         "total":0,
         "transaction_date":"2016-03-29 11:43:46",
         "user_id":56
      },
      {  
         "...":"..."
      }
   ]
}
```
Atttibute "transaction" is a child collection. But, when I call collection method inside collection operation to filter the value in "transaction" attribute, it's not working. 

```php
 $collection->each(function ($item) use ($user) {
        return $item->transaction->reject(function ($tr) use ($user) {
              return $tr->users_id == $user
         });
});
```

Is Laravel support operation like this?

**Comment by GrahamCampbell** [comment]
> Is Laravel support operation like this?

Sorry, we don't process questions here. Please ask on the forums.
