### ISSUE TITLE
502 Gateway - when call ::with() Eloquent

### ISSUE THREAD

**Issue by aios** [laravel/framework#12908]
Hi all.
I catched an 502 error on Nginx + PHP 7.0.4 FPM + MySQL with message:
> recv() failed (104: Connection reset by peer) while reading response header from upstream, client...

How to reproduce?

1. Make two models User and Street (with migration)
2. Make relation hasOne() User to Street like something:

```php
public function street()
{
        return $this->hasOne('App\Street', 'id', 'street_id');
}
```
3. Make some route 
```php
use App\User;
Route::get('/', function () {
    $user = User::with('street')->get();
    return view('index');
});
```
4. Go to PhpMyAdmin - or %your-favorite-db-manager% and remove street_id from users table.
5. Go to http://yourownsite.com/

I think there should be an exception , or at least an error . The fact that the field does not exist .

**Comment by GrahamCampbell** [comment]
Looks like php segfaulted. Please report this to the php core team.

**Comment by GrahamCampbell** [comment]
Or, upgrade php.

**Comment by aios** [comment]
So laravel doesnt control that moment?

**Comment by GrahamCampbell** [comment]
A 502 error is indicating that PHP itself crashed, and that's not a laravel bug, that's a php bug.

**Comment by aios** [comment]
Okey. But laravel can say me when relation has not a field in base. No?

**Comment by GrahamCampbell** [comment]
It will have done. PHP just crashed anyway.

**Comment by aios** [comment]
Moot point , check the field can be transferred to a higher level and to exclude php segfault.

**Comment by mark86092** [comment]
`$this->hasOne('App\Street');`
Please make sure you have column `user_id` in Street table. I think its programmer's responsibility to make sure.

**Comment by aios** [comment]
wow =( i dont know that. sorry - it possible my mistake.

2016-03-29 12:04 GMT+03:00 Yen-chi Chen <notifications@github.com>:

> $this->hasOne('App\Street');
> Please make sure you have column user_id in Street table. I think its
> programmer's responsibility to make sure.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/laravel/framework/issues/12908#issuecomment-202788080>
>



-- 
С уважением, Габриелян Д.М.

ICQ:      *3092095*
Skype:  *gt_fios*
