### ISSUE TITLE
[5.2] Array validation checking for error existence for selected field

### ISSUE THREAD

**Issue by mnabialek** [laravel/framework#12919]
In Laravel 5.2 was added array validation, so we could use simple rules like so:

`'person.*.email' => ['required','email]`

But, assuming we have HTML form with input names `person[0][email]` and `person[1][email]` how could we check if there is error for `person[0][email]` ? 

I think at the moment it's impossible to do this out of the box. Probably `MessageBag` should be rewritten to use instead of simple `$key` value transformed by helper function.

At the moment I have to do something like this:

`
@if ($errors->has($name) || $errors->has(array_str_dot($name))) has-error @endif
`

and have defined `array_str_dot` function like so:

```
function array_str_dot($arrString)
{
    return str_replace(['[', ']',], ['.', ''], $arrString);
}
```

**Comment by mnabialek** [comment]
@themsaid There's nothing wrong with it. But if I use in forms `person[1][email]` notation, I think it would be better for consistency to use same name for verifying if field has any errors. Now In one place we should use `person[1][email]` and in other `person.1.email`

**Comment by themsaid** [comment]
I think the dot format is easier, in terms of less number of characters and as for consistency, array validation is used for arrays in general, sometimes the input is JSON not a form submission.

**Comment by mnabialek** [comment]
@themsaid That's true, but if you use form, you might not know that you have to use dot notation to verify for example `$errors->has`. Dot notation is fine, but if also handling array notation would be added, it would be probably better, so in above example both

```
$errors->has('person.1.email')
```

and

```
$errors->has('person[1][email]')
```
would work same.

**Comment by GrahamCampbell** [comment]
we have no plans to add other notations
