### ISSUE TITLE
[4.2] cannot use queue: 'There was an error parsing the file containing the closure'

### ISSUE THREAD

**Issue by FiloSpaTeam** [laravel/framework#12912]
Hi guys!
We are trying to solve this problem from days, but nothing to do.

We have a system that sends emails when we generate something.
Use send is a bit laggy due to latency and elevated number of emails so we need to port to queue system.

We tried:
* Benstalkd -> does not work on Heroku due to server temporary storage and automatic respawning
* Redis -> bugs with high traffic and closures go in error
* IronMQ -> version 3 not supported with Laravel 4 and heroku use only that
* AWS -> last chance; right configuration but something is not working

If we use send function all works, we change to queue and we have this error:
```
There was an error parsing the file containing the closure
```

Anyone can show me the right way? xD
Thanks in advance.

**Comment by GrahamCampbell** [comment]
4,2 is not supported.

**Comment by FiloSpaTeam** [comment]
4.2 is not supported from community or is not supported by SuperClosure?

**Comment by GrahamCampbell** [comment]
Please upgrade to Laravel 5.1 or greater.

**Comment by FiloSpaTeam** [comment]
I would upgrade, i may have problem from laravel 4.2 to 5.1? I think there are framework's changes.

**Comment by GrahamCampbell** [comment]
Yes, there are some breaking changes, but we do have an upgrading guide.

**Comment by FiloSpaTeam** [comment]
ok thanks for all
