### ISSUE TITLE
Validation - Excel vs Numbers files

### ISSUE THREAD

**Issue by SteveEdson** [laravel/framework#12914]
I have the following rule in my `ImportDocumentRequest` class:

```php
    public function rules()
    {
        return [
            'document' => 'required|mimes:xls,xlsx', // Still doesn't work with `xlm,xla,xlc,xlt,xlw`
        ];
    }
```

When I upload a file saved from Excel, or from the Laravel Excel package, they have the mime type `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet`. This works fine.

When I edit the document and save it from Numbers on a mac, saving as an excel file, it gets the mime type: `application/vnd.ms-excel`. This is listed on http://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types as `xls xlm xla xlc xlt xlw`, however the validation fails.

If I remove the validation rule, the file can still be processed like any other Excel file.

Thanks

**Comment by MalikinSergey** [comment]
https://github.com/laravel/framework/blob/5.2/src/Illuminate/Validation/Validator.php#L1535

**Comment by MalikinSergey** [comment]
Mime type validation based on Symfyny file API, so this issue can't be fixed in Laravel repository.
