### ISSUE TITLE
How to create the migrations for database views using php artisan

### ISSUE THREAD

**Issue by rcadhikari** [laravel/framework#12916]
Hi there,

I would be pleased if anyone could provide me the information about how to create the migration for database(mysql) views  using PHP ARTISAN as could not find any documentation on the Laravel site.

Many thanks
RC

**Comment by GrahamCampbell** [comment]
Sorry, we don't process questions here. Please ask on the forums.

**Comment by rcadhikari** [comment]
No worries! Thanks
