### ISSUE TITLE
L5.1 Authenticate Middleware broken on non-Ajax-request

### ISSUE THREAD

**Issue by Jaspur** [laravel/framework#12917]
The default Authenticate MiddleWare is recognizing normal non-ajax-request as Ajax-request, so it'll show users a plain white page with the text "Unauthorized". This happens on both Safari and Internet Explorer. Didn't see it happen on Firefox nor Chrome.

This untouched method in L5.1: 

```
    public function handle($request, Closure $next)
    {
        if ($this->auth->guest()) {
            if ($request->ajax()) {
                return response('Unauthorized.', 401);
            } else {
                return redirect()->guest('auth/login');
            }
        }

        return $next($request);
    }
```

Tried this:

```
            if ($request->ajax()) {
                if(@strpos($_SERVER["HTTP_USER_AGENT"], 'Safari'))
                {
                    return redirect()->guest('auth/login');
                }
               return response('Unauthorized.', 401);

```
But that results in 414 Request-URI Too Large responses in Safari.

**Comment by GrahamCampbell** [comment]
You can't use $_SERVER["HTTP_USER_AGENT"].

**Comment by Jaspur** [comment]
@GrahamCampbell yea, I figured out, because that wasn't the solution as said. It's Safari/IE that thinks a simple request via direct link is an Ajax-request what gives the plain-page with only "Unauthorized" on it.
