### ISSUE TITLE
Merge two relationships returns 'Method addEagerConstraints does not exist'

### ISSUE THREAD

**Issue by fcaivano** [laravel/framework#12926]
Im getting this error:

> BadMethodCallException in Macroable.php line 81:
> Method addEagerConstraints does not exist.

In my User model im tryng to merge two relationships.

I have the same thing working on a different project but i can't figure out why here it isn't working.

```
public function stories()
{
return $this->hasMany('App\Models\Story')->where('published','=','1')->orderBy('order');
}

public function photos()
{
return $this->hasMany('App\Models\Photo')->where('published','=','1')->orderBy('order');
}

public function content()
{
return $this->stories->union($this->photos);
}
```

Version: Laravel 5.2.*

**Comment by lagbox** [comment]
maybe you intend to call that method on a builder not a collection?
