### ISSUE TITLE
[SQLite] Migration doesn't modify a (single) column.

### ISSUE THREAD

**Issue by arubacao** [laravel/framework#12927]
I am aware that the docs say: 
> Note: Dropping or modifying multiple columns within a single migration while using a SQLite database is not supported.

I've create a single migration file to modify the column:
```
    public function up()
    {
        Schema::table('users', function (Blueprint $table) {
            $table->string('password', 60)->nullable()->change();
        });
    }
```
The initial migration file: `$table->string('password', 60);`

It is working with mysql, but not with sqlite
Sqlite: 
![sqlite](https://cloud.githubusercontent.com/assets/7462542/14126261/faccc5bc-f60f-11e5-9d6b-527cc5b840c7.PNG)

Mysql:
![mysql](https://cloud.githubusercontent.com/assets/7462542/14126260/facc506e-f60f-11e5-845a-f7bad6be82f1.PNG)

Cheers,
Chris

**Comment by sisve** [comment]
When it's not working in sqlite; what happens? Do you get an error message? Or are there no changes in your database?

On a related note, does the docs say that changing one column in a migration is supported? Sqlite has some ... lacking support for ALTER TABLE statements. You can rename tables and add fields, everything else require creating a new table, moving the data, dropping the old table.
Reference: https://www.sqlite.org/lang_altertable.html

**Comment by billmn** [comment]
@arubacao I have tested your code with Laravel 5.2.35 and SQLite 3.8.10.2 ... all works fine here.

After the default migration (**2014_10_12_000000_create_users_table**):
![schermata 2016-06-06 alle 22 31 44](https://cloud.githubusercontent.com/assets/779534/15837335/20d785d0-2c39-11e6-8cb3-b0d58a59d1e1.png)

and after a new migration using your code:
```php
public function up()
{
    Schema::table('users', function (Blueprint $table) {
        $table->string('password', 60)->nullable()->change();
    });
}
```

![schermata 2016-06-06 alle 22 33 25](https://cloud.githubusercontent.com/assets/779534/15836849/1110287a-2c37-11e6-83d9-1740a5c51f1a.png)

***

@GrahamCampbell The strange thing is that fields haven't a size after the first migration (2014_10_12_000000_create_users_table) - Only with SQLite. I have also tried using <code>$table->string('name', 30)</code> but the length is always 0.

**Comment by billmn** [comment]
@GrahamCampbell Nevermind, all ok with SQLite ... seems intentional.
