### ISSUE TITLE
laravel 4.2 ssh

### ISSUE THREAD

**Issue by anothergituser** [laravel/framework#12937]
I was having issues with laravel ssh and newer versions of openssh server. phpseclib had a bug fix for that issue starting with 1.0 versions but laravel 4.2 depends on 3.9.* so it was not applicable and installing a more recent version of phpseclib did not work out ok (ssh command would terminate before completing, maybe some timeout..). Anyhow phplibsec 3.9.10 can be patched easily to fix the issue, see here
http://anothergituser.github.io/laravel/php/2016/03/30/laravel-4.2-ssh.html

Thanks.

**Comment by GrahamCampbell** [comment]
Laravel 4.2 is not supported.

**Comment by anothergituser** [comment]
You can still find laravel 4.2 on laravel.com site, and this is a bugfix not a feature request

**Comment by GrahamCampbell** [comment]
We do not fix bugs in Laravel 4.x, because it's not supported.
