### ISSUE TITLE
Bug : Uploaded file not found when trying to guess the extension

### ISSUE THREAD

**Issue by shadoWalker89** [laravel/framework#12936]
Hi,

So before this commit https://github.com/laravel/framework/commit/87e617527c8246ccfc66536bce4f32359104978f i could get an uploaded file extension by using the Illuminate\Http\UploadedFile::extension() method even if the file has already been moved using the move() method.

But after this commit i get the following error
```
FileNotFoundException in MimeTypeGuesser.php line 123: 

The file "F:\wamp2.5\tmp\phpBD4C.tmp" does not exist
```

The **FileNotFoundException** is Symfony\Component\HttpFoundation\File\Exception\\**FileNotFoundException**

When i changed the **Illuminate\Http\UploadedFile::extension()** back to

```php
    public function extension()
    {
        return $this->guessClientExtension();
    }
```

Once again i could get the uploaded file extension even after it has been moved using the move() method.

**Comment by shadoWalker89** [comment]
Should i make a pull request to revert the change ?

I think i understand why Taylor made the change (guessing the extension from the file mime type will be better then trusting the extension from the client), but as you can see this is a breaking change that can break application as it did to mine.

May be this could be reverted and re applied in the next major version to avoid any inconveniences.

**Comment by taylorotwell** [comment]
Sorry about that. Try using `guessClientExtension` for now.

**Comment by mnrafg** [comment]
`guessClientExtension` returns 'bin' instead of 'mp3'.
