### ISSUE TITLE
make:migration allows line break in the file name

### ISSUE THREAD

**Issue by KonstantinKolodnitsky** [laravel/framework#12932]
Accidentally I put a line break like so

    ./artisan make:migration add_fields_to_table'
    > '

The file was created successfully but when I tried to run migration the error occurred

    [Symfony\Component\Debug\Exception\FatalThrowableError]
    Fatal error: Class 'AddFiledsToTable
    ' not found

There was a line break in the file name.

I think line breaks should be removed automatically.

**Comment by GrahamCampbell** [comment]
Thanks for the report. I'll fix this now.

**Comment by GrahamCampbell** [comment]
@KonstantinKolodnitsky Please confirm that #12933 fixes your issue.

**Comment by KonstantinKolodnitsky** [comment]
@GrahamCampbell Yes, I confirm. Thanks!

**Comment by themsaid** [comment]
@GrahamCampbell maybe this one too?
