### ISSUE TITLE
laravel/laravel missing 5.2 stable branch?

### ISSUE THREAD

**Issue by jurchiks** [laravel/framework#12930]
What's up with that?

**Comment by barryvdh** [comment]
`master` branch is for 5.2. `develop` branch is for 5.3

**Comment by jurchiks** [comment]
Are you saying that your master branch is a production/stable branch?

**Comment by barryvdh** [comment]
Master is the current stable branch, from which new 5.2 tags are created. Stable releases are tagged, eg https://github.com/laravel/laravel/tree/v5.2.0 and https://github.com/laravel/laravel/tree/v5.2.27

If you clone the laravel/laravel repo and run composer install, you will get the latest 5.2, which is expected imho.

Also not an issue. Please use the forums/slack/etc to ask questions.

**Comment by jurchiks** [comment]
Master should be the development branch.

**Comment by GrahamCampbell** [comment]
> Master should be the development branch.

Says who?

**Comment by GrahamCampbell** [comment]
It is the development branch for 5.2 anyway...

**Comment by jurchiks** [comment]
@GrahamCampbell says common conventions.

**Comment by GrahamCampbell** [comment]
As I said, it IS the development branch anyway. 5.2 is under development as well as 5.3.
