### ISSUE TITLE
Eloquent related collection modification

### ISSUE THREAD

**Issue by dhiman252** [laravel/framework#12941]
Hi Team,
I am working with laravel 5.1.* and using the eloquent for fetching the related records and if i try to modify the related records then instead of modifying the related property it sets a new property.

Code Below:
`$travelOpts = RequestFormField::with('activeOptionsList')->where('name','travel_options')->first();`

Refer Image 1

![image 1](https://cloud.githubusercontent.com/assets/8954468/14168282/0fd787a0-f73f-11e5-826a-fe47e56069cd.png)

Code Below:
`$travelOpts = RequestFormField::with('activeOptionsList')->where('name','travel_options')->first();
$travelOpts->activeOptionsList = $travelOpts->activeOptionsList->keyBy('id');`

Refer Image 2

![image 2](https://cloud.githubusercontent.com/assets/8954468/14168283/0fd827d2-f73f-11e5-9818-148c4d636d81.png)

Now see the difference: Instead of modifying the related record parameter 'activeOptionsList' it sets a new property named 'activeOptionsList' in the eloquent class object.

**Comment by jekinney** [comment]
Your overriding (resetting if you will) the data.

**Comment by dhiman252** [comment]
I just wanted the collection to be ordered using KeyBy() function.
How this can be achieved ?
If i write the following:
`$travelOpts = RequestFormField::with('activeOptionsList')->where('name','travel_options')->first(); $travelOpts->activeOptionsList->keyBy('id')`

it does not work

**Comment by GrahamCampbell** [comment]
Feel free to discuss on the forums, since this is not a bug report.

You can still discuss here if you want though. I'm going to unsubscribe from this thread.
