### ISSUE TITLE
Validating array unique:table triggers database column not found error

### ISSUE THREAD

**Issue by njansenNL** [laravel/framework#12947]
Hi,

When we validate an array with the unique:table rule like:

```
$rules = [
    '*.code' => 'required|string|unique:devices',
];
```
`Laravel 5.2.27` triggers a database error that the specified column is not found:

```
Column not found: 1054 Unknown column '0.column_name' in 'where clause' (SQL: select count(*) as aggregate from `table_name` where `0`.`column_name` = value)"
```

I know that there are other issues [#11927](https://github.com/laravel/framework/pull/11927) around this problem, and it was fixed in my installation but now it seems to be back.

Any suggestions are welcome!

**Comment by themsaid** [comment]
@njansenNL this is fixed 5.2.28
