### ISSUE TITLE
php artisan --env=client does not load .env.client file

### ISSUE THREAD

**Issue by di5abled** [laravel/framework#12944]
Hy, I'm using Laravel 5.2.27 and I want to load different .env files based on the current set environment.

This feature is also described in the [Documentation](https://laravel.com/docs/master/configuration#environment-configuration)

But when I use artisan via `php artisan ... --env=client` only the `.env` files is loaded and not the `.env.client` file.

I assume artisan --env does't set the `APP_ENV` key right. When I debug `Illuminate\Foundation\Bootstrap\checkForSpecificEnvironmentFile` I get `null` for `env('APP_ENV')` and so no other file is loaded!?

**Comment by GrahamCampbell** [comment]
Did you clear the config cache?

**Comment by GrahamCampbell** [comment]
We only ever load the env files in order to populate the config cache, or if there's not a config cache.

**Comment by di5abled** [comment]
hy, yes I tried to clear the config cache, nothing changed.

so if I want to use one instance of laravel to run two identical apps but with different configs, this isn't really possible?

The plan is to make subdomains like `client1.app.com` and `client2.app.com` and each subdomain has his own `.env.clienX`file. But only one .env file would be loaded and cached?

What would be the best way so approach such a solution in laravel?

**Comment by GrahamCampbell** [comment]
> hy, yes I tried to clear the config cache, nothing changed.

When I say clear, I really do mean `:clear`, not `:cache`, as in, refreshing the cache. I really mean delete it.

**Comment by GrahamCampbell** [comment]
Please ask on the forums.

**Comment by tam5** [comment]
I am having the same type of issue.

`php artisan --env=testing migrate:refresh` for example is just refreshing the database specified in `.env`. In fact so does `php artisan --env=foo migrate:refresh` so it seems like the `--env` option is not working at all.

**Comment by di5abled** [comment]
yes that's right, seems like `--env=foo` isn't passed right into the laravel app starup and therefore always the `.env` file loads. 

> I assume artisan --env does't set the APP_ENV key right. When I debug Illuminate\Foundation\Bootstrap\checkForSpecificEnvironmentFile I get null for env('APP_ENV') and so no other file is loaded!?

**Comment by tam5** [comment]
@GrahamCampbell why is this closed?

I have done `config:clear` like you said but it does not work.

@di5abled is right that `APP_ENV` is always null which means the env that is loaded will always be the default `.env` file.

**Comment by flashek** [comment]
I can confirm. Got files: `.env .env.testing` and: `php artisan migrate --env=testing` is always executed with settings from `.env`

**Comment by GrahamCampbell** [comment]
@flashek And you definitely cleared the config cache FIRST? Not the same as recaching.

**Comment by flashek** [comment]
`15:42 $ php artisan config:clear
Configuration cache cleared!
15:42 $ php artisan --env=testing migrate
Nothing to migrate.`

**Comment by flashek** [comment]
Started xdebug to find out what is going on. In file https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Bootstrap/DetectEnvironment.php#L39 the condition is true so it ends with just `return`. It should go futher and load proper `.env` file. Somehow optional `--env=testing` wasn't counted in.

**Comment by tam5** [comment]
Well the `.env` file would be loaded correctly with the next few lines there if only the `APP_ENV` was set before hand, but that's not happening.

**Comment by flashek** [comment]
IMHO `APP_ENV` should be set based on `--env=` parameter to continue loading the rest of variables.

**Comment by flashek** [comment]
I did: `export APP_ENV=testing` and it works but anyway it shouldn't work that way?

**Comment by flashek** [comment]
#13351

**Comment by GrahamCampbell** [comment]
Thanks @flashek.

**Comment by tam5** [comment]
Thanks

**Comment by ryancwalsh** [comment]
I just spent so many HOURS on this problem. My head was going to explode. I was so confused. I'm really disappointed that Laravel 5.2 didn't accept the pull request since this was clearly broken functionality.

@nowak-ninja Thank you for the `export APP_ENV=testing` hint and for the pull request.

**Comment by ryancwalsh** [comment]
Dang, this gets me every time. Thanks to Google for bringing me back here. 

I really wish the `--env` option worked. It's weird that sometimes `export APP_ENV=testing` is required instead.

**Comment by brazorf** [comment]
It still doesn't work on Laravel 9.

**Comment by AurumGallente** [comment]
php artisan migrate --env=testing

 INFO  Nothing to migrate.

artisan can see only default .env file

**Comment by kdg-cwood** [comment]
~I am on Laravel 10 (I know, I need to update to 12) and this suddenly started happening recently. It's been working fine (I have .env.testing and am using php artisan db:seed --env=testing), and my coworkers are suddenly starting to get seeders running in their main env instead of the testing one. It still works normally for me though!~

Pay me no mind, it was shenanigans with Docker compose.
