### ISSUE TITLE
Add support for DateTimeInterface when casting objects

### ISSUE THREAD

**Issue by theofidry** [laravel/framework#12951]
If we have the following model:

```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class User extends Model
{
    public $timestamps = false;
    protected $dates = ['created_at'];
}
```

Doing the following will fail:

```php
use App\User;

User::unguard();
$user = User::create([
    'created_at' => new \DateTimeImmutable('now', new \DateTimeZone('UTC')),
]);
```

will fail. I guess this is because `Carbon` has no support for `\DateTimeImmutable` and more generally `\DateTimeInterface`. Although the workaround is easy, it would be nice to support `\DateTimeInterface` instead of just `\DateTime`.

Version used: Laravel 5.1

**Comment by theofidry** [comment]
I see that there is #12478, does it solve the problem? If yes can't it be pack-ported to Laravel 5.1?

**Comment by GrahamCampbell** [comment]
Since this is not a bug, it won't be backported.
