### ISSUE TITLE
[5.2] Bug: php artisan config:cache produces compiled config with invalid 'session.driver' == 'array'

### ISSUE THREAD

**Issue by swayok** [laravel/framework#12967]
Hi. I'm trying to use `php artisan config:cache` but it produces invalid session driver.
While I was tracking the problem I detected that any changes of session driver are ignored.
It doesn't matter if I write `'driver' => env('SESSION_DRIVER', 'file')` of `'driver' => 'file'` - in any case in compiled cache.php i get `'driver' => 'array'`.
As I remember while tinkering with console commands I saw that session driver was forced to be 'array'. And this seems to be a reason of this bug.
Please fix.

**Comment by rsdev000** [comment]
Hi. Tested with 5.2.27 (PHP 7.0.5 Windows 10) and it's working as expected.

In .env I have ```SESSION_DRIVER=redis``` and in config/session.php I have ```'driver' => env('SESSION_DRIVER', 'file')```.

The output in ```bootstrap/cache/config.php``` is ```array ('driver' => 'redis', 'lifetime' => 120, ...)```

You might want to take a look at your ```.env``` file.

Cheers

**Comment by swayok** [comment]
Thanks for testing. In new project it worked ok. 
The problem was in my configuration for API where I set 'session.driver' => 'array' manually (my old attempts to lighten API section of project on laravel 5.1. Later with update in Kernel middleware groups it became useless but surprised me now...)
