### ISSUE TITLE
There is no way to access to validator instance within a FormRequest

### ISSUE THREAD

**Issue by shadoWalker89** [laravel/framework#12977]
Hi,

I'm using FormRequest objects to validate my forms.
I needed to use the **After Validation Hook**, but there is no way i can access the validator instance inside the FormRequest.

I'm aware that i can add a **validator()** method in my form request class and create the validator instance my self, but this seems a little bit messy.

May be it will be better if the user can define a method on the form request where the validator instance will be passed as an argument and then returned after doing what is needed with the validator. (just like we do with rules(), messages() and attributes() )

**Comment by thomasruiz** [comment]
You can use `getValidatorInstance` (https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Http/FormRequest.php#L74).

**Comment by shadoWalker89** [comment]
@thomasruiz The form request objects purpose is to move the validation logic out of the controller.

If you check the source code you will see there is no place where we can call the **getValidatorInstance** method within the form request class, and that is why asked to add a callback just right after the instantiation of the form request object so we can perform any needed actions like the after validation hook.

**Comment by thomasruiz** [comment]
Yes you can, you just need to override the `validate` method. It's definitely possible, you just need to tweak the FormRequest methods.

**Comment by shadoWalker89** [comment]
@thomasruiz @GrahamCampbell Oh my god, man can you please read the issue initial message !
I do not want to override the validate() or validator() method. These two methods contain logic, i do not want to override that logic. I only need a way to access the validator instance within the form request without overriding any methods like the validate() and validator()

What do you think will happen in future laravel versions if one of the previous mentioned methods change ! You must always avoid overriding core methods, only when needed.

@GrahamCampbell can you please stop closing issues like this, i see that you always close issues and don't give people the space to discuss their ideas.
