### ISSUE TITLE
Get translation from language file containing dot

### ISSUE THREAD

**Issue by shahidnajam** [laravel/framework#12974]
Is it possible to get translation from language file that contains (.)dot?

For example, The language directory looks like

    /lang
        /en
            pagination.php
            phone.history.php

        /es
            pagination.php
            phone.history.php

I want to get translation for the key 'name' from phone.history.php file as it contains dot.

    Lang::get('phone.history.name')
This code doesn't work because it looks history and name in phone.php file. How to get from file containing dot?

**Comment by GrahamCampbell** [comment]
Sorry, but file names must not contain a dot.

**Comment by GrahamCampbell** [comment]
They're a reserved character.

**Comment by m-o-s-t-a-f-a** [comment]
How about if the local directory has sub folders. for example:

````

/lang
    /en
      /phone
           history.php

    /es
      /phone
          history.php
````

shouldn't this command work?
`Lang::get('phone.history.name')`

**Comment by GlennBags** [comment]
This assumes multidimensional array. `Lang::get('phone.history.name')` assumes:
_phone.php_
`<?php
    return [
        'history' => [
            'name' => "name",
        ],
    ];`

**Comment by m-o-s-t-a-f-a** [comment]
I know the assumption. I just thought in laravel dot sometimes means directory hierarchy sometimes not. Maybe it's not bad idea in language folder also dot can be directory hierarchy, if there is no technical issue.
