### ISSUE TITLE
Mailer $message variable

### ISSUE THREAD

**Issue by ahmedash95** [laravel/framework#12972]
i know that's laravel documentation danger alert tell's us not to use $message variable "Note: A $message variable is always passed to e-mail views, and allows the inline embedding of attachments. So, you should avoid passing a message variable in your view payload." . i tried to change $message in the Illuminate\Mail\Mailer.php in line 157 from 

```
$data['message'] = $message = $this->createMessage();
```

to 

```
$data['_message'] = $message = $this->createMessage();
```

and made some tests and every thing works good for me using $message as a variable passed to my email view

```php
$message = 'message';
Mail::send('message', ['message'=>$message], function ($message) {
    $message->from('hello@app.com', 'Your Application');
    $message->to('info@laravel.com', 'Laravel')->subject('Test Mail!');
    $message->attach(base_path().'/readme.md');
});
```

so should we change this in mailer class or what ? because it's confuse a lot of laravel juniors developers when they try to send email with $message variable .

**Comment by GrahamCampbell** [comment]
Sorry, but renaming the variable would be breaking.

**Comment by ahmedash95** [comment]
okay, i got it now , but may i ask if the $data['message'] or $data['_message'] doesn't make any issue or deference so why we use it in the mailer ?
