### ISSUE TITLE
Laravel composer update give error

### ISSUE THREAD

**Issue by Harrrrry** [laravel/framework#12982]
I just update the compose and i found below error.

    php artisan clear-compiled PHP Fatal error: Call to undefined method Illuminate\View\Compilers\BladeCompiler::directive() in /var/www/html/innomaid/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 213

    [Symfony\Component\Debug\Exception\FatalErrorException]
    Call to undefined method Illuminate\View\Compilers\BladeCompiler::directive()

Script php artisan clear-compiled handling the post-update-cmd event returned with an error

    [RuntimeException]
    Error Output: PHP Fatal error: Call to undefined method Illuminate\View\Compilers\BladeCompiler::directive() in /var/www/html/innomaid/ve
    ndor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 213

Here is my composer code

{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "laravel/framework": "5.0.*",
        "illuminate/html": "5.*",
        "barryvdh/laravel-dompdf": "0.6.*",
        "tymon/jwt-auth": "0.5.*",
        "gloudemans/shoppingcart": "~1.3",
        "intervention/image": "^2.3"

    },
    "require-dev": {
        "phpunit/phpunit": "~4.0",
        "phpspec/phpspec": "~2.1",
        "zizaco/entrust": "dev-laravel-5"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-install-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "post-create-project-cmd": [
            "php -r \"copy('.env.example', '.env');\"",
            "php artisan key:generate"
        ]
    },
    "config": {
        "preferred-install": "dist"
    }
}

**Comment by ahmedash95** [comment]
try this command

```
$ composer update --no-scripts
```

and check the config/app.php providers array that each provider's package exist

**Comment by GrahamCampbell** [comment]
We don't support Laravel 5.0.x.

**Comment by Harrrrry** [comment]
@GrahamCampbell  Then were i go

**Comment by Harrrrry** [comment]
Its not give the error during composer update but in my application
FatalErrorException in Facade.php line 213: Call to undefined method Illuminate\View\Compilers\BladeCompiler::directive()
error come

**Comment by Harrrrry** [comment]
update "zizaco/entrust": "dev-laravel-5" to "zizaco/entrust": "1.4.1"

Solve my problem.
