### ISSUE TITLE
Session Killed when Accessing /login in browser

### ISSUE THREAD

**Issue by microdevil** [laravel/framework#12988]
Dear All

I am new comer in laravel framework.
I am trying to create authentication in laravel.
I am using php artisan make:auth to generate authentication automatically.
I am happy when everything going well.
However, when i have been login and i access login page with typing 'localhost:8000/login', i still access my login page and my session destroyed.
My problem, why i can access my login page when i have been login ?
Anyone here could fix the problem i have ?

(Sorry for my bad english and my bad grammar)
Thnks.....

**Comment by GrahamCampbell** [comment]
Please direct questions to the forums.
