### ISSUE TITLE
Blade directives don't parse arguments

### ISSUE THREAD

**Issue by riki137** [laravel/framework#12986]
### Case 1
AppServiceProvider->boot()
`Blade::directive("theme", function($arg1) {
            dd($arg1);
        });`
header.blade.php:
`@theme("navigation")`
Expected output:
`"navigation"`
Actual output:
`"("navigation")"`

### Case 2
AppServiceProvider->boot()
`Blade::directive("theme", function($arg1, $arg2) {
            dd($arg1, $arg2);
        });`
header.blade.php:
`@theme("navigation", "foobar")`
Expected output:
`"navigation"`
`"foobar"`
Actual output:
`ErrorException in AppServiceProvider.php line 26: `
`Missing argument 2 for Sail\Providers\AppServiceProvider::Sail\Providers\{closure}() (View: D:\Coding\things\stuff\views\core\header.blade.php) (View: D:\Coding\things\stuff\views\core\header.blade.php) (View: D:\Coding\things\stuff\views\core\header.blade.php)`

**Comment by GrahamCampbell** [comment]
That is the expected behaviour. We match the brackets too.

**Comment by GrahamCampbell** [comment]
In case 2, param 1 will be `("navigation", "foobar")`, and param 2 will not be set.
