### ISSUE TITLE
Laravel Scheduler 5.1 doesn't run in Windows properly

### ISSUE THREAD

**Issue by rmariuzzo** [laravel/framework#13004]
I have a simple command that write a log entry (`\Log::debug('Pulse')`) which is scheduled to be run every minute:

```php
$schedule->command('heartbeat:pulse')
         ->everyMinute()
         ->withoutOverlapping();
```

I can run the command without issue if I type in a terminal the following:

```sh
php artisan heartbeat:pulse
```

But if I try to run:

```sh
php artisan scheduler:run
```

… the command doesn't run. Instead, it outputs something weird. Let me be short on this: 1) it shows the commands that will be run 2) it create some empty files that looks like the commands that should ran.

<img width="1007" src="https://cloud.githubusercontent.com/assets/439839/14238454/76080366-f9ff-11e5-9e8a-9d82df442bf5.png">

```
"heartbeat\357\200\272pulse;"
rm
storage/framework/schedule-7e80c8ef182df7c94116099504c7180e
storage/framework/schedule-7e80c8ef182df7c94116099504c7180e;
```

At this point, I'm still trying to understand what's happening under the hood. If there's any insights or knowledge on this I will be glad to hear/read about it. I'm willing to provide any other information that could be useful.

**Comment by GrahamCampbell** [comment]
Windows is only fully supported by the scheduler starting from `v5.2.22`.

**Comment by GrahamCampbell** [comment]
I'll see if I can get that stuff backported for you though.

**Comment by GrahamCampbell** [comment]
See https://github.com/laravel/framework/pull/13036.
