### ISSUE TITLE
Conditional Validation with "sometimes" fails on empty array

### ISSUE THREAD

**Issue by JeanLucEsser** [laravel/framework#13007]
The title is self-explanatory.

Applying the following rule on an empty array `[]` passes validation:
`sometimes|required`

It should fail as the same rule correctly fails for a null value or an empty string.

**Comment by themsaid** [comment]
Can you share the attribute name?

```
`users.*.username` => 'sometimes|required'
```

**Comment by JeanLucEsser** [comment]
I didn't mean on an array of values, but on an empty array as a value.

Say you test the following attribute: `task => []`

The rule `'task' => 'required'` correctly fails.
The rule `'task' => 'sometimes|required'` passes but should fail.

**Comment by themsaid** [comment]
hmm I'm not sure, I think an empty array can be considered a value.

**Comment by themsaid** [comment]
This test currently passes:

```
$trans = $this->getRealTranslator();
$v = new Validator($trans, ['name' => []], ['name' => 'sometimes|required']);
$this->assertFalse($v->passes());
```

**Comment by JeanLucEsser** [comment]
Fair enough. The plot thickens.

This test currently fails:

```
$trans = $this->getRealTranslator();
$v = new Validator($trans, ['foo' => ['bar' => []]], ['foo.bar' => 'sometimes|required']);
$this->assertFalse($v->passes());
```

Looks like the issue arises only with nested arrays of values.

**Comment by themsaid** [comment]
It's fixed, will be working as expected as of the next patch release.

**Comment by JeanLucEsser** [comment]
Great, thanx, closing the issue then.
Best.
