### ISSUE TITLE
Empty array passes 'string' validation rule (2)

### ISSUE THREAD

**Issue by stefanmajoor** [laravel/framework#13005]
So, I experienced the problem that empty arrays pass the string validation rules, since empty arrays are falsy and thus seen as an empty string. Passing this value in the query builder as string will break it however.

After some searching I found out that it was a known issue (See #10747). A fix has been made in commit 980d098ad091a5087a93202ebd4c091e336f3e58. However, this has been reverted later on in commit a7142dc041eb5a5c0507569817f5e450489c5981.

So two questions: (a) Why was this fix reverted, and (b) does this mean that this is intended behaviour?

**Comment by GrahamCampbell** [comment]
And empty string is a string, so that's fine to pass.

**Comment by GrahamCampbell** [comment]
Maybe you want `string|required`?

**Comment by GrahamCampbell** [comment]
That's accept non-empty strings.

**Comment by stefanmajoor** [comment]
Please read the question more carefull before answering. I am not talking about an empty string, but about an empty array, which is not a string

**Comment by james-funk** [comment]
This still appears to be an issue in 5.4. To iterate, an empty **array** passes the **string** validation rule.
