### ISSUE TITLE
Memcached store producing an error with the "many" method

### ISSUE THREAD

**Issue by nikkiii** [laravel/framework#13002]
Version: 5.2.29
Interpreter: HHVM 3.12.1
Error:
`Fatal error: Cannot pass parameter 2 by reference in /var/www/vendor/laravel/framework/src/Illuminate/Cache/MemcachedStore.php on line 66`

When using `getMulti` in the `Illuminate\Cache\MemcachedStore` class, the second argument is an incorrectly passed reference.

To reproduce:
- Set cache store to Memcached
- Call the `many` method on the store

```php
app('cache')->store('memcached')->many([ 'test1', 'test2' ]);
```

Solution:
Change null to $null, assign `$null = null` above. The [Memcached.getMulti documentation](http://php.net/manual/en/memcached.getmulti.php) does just this in [this example](http://php.net/manual/en/memcached.getmulti.php#example-4956).

I'm not sure if this affects PHP too, or just HHVM, but it should appear in both.

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell.

**Comment by GrahamCampbell** [comment]
> I'm not sure if this affects PHP too, or just HHVM, but it should appear in both.

Could you please check @nikkiii.

**Comment by nikkiii** [comment]
@GrahamCampbell Tested on PHP 5.6, it doesn't cause a fatal error and returns as expected. Not worth an immediate patch release as it's an extremely rare edge case in my opinion, but it would be nice to see a patch combined with other bugfixes/versions none the less.

**Comment by GrahamCampbell** [comment]
Please report this error to HHVM.

**Comment by nikkiii** [comment]
Actually, seems to be affecting PHP, even then it's not specifically an HHVM issue since the cause is an incorrect reference, and strict checking on this doesn't make it something that they need to fix. I'm also not sure if my test correctly covered the issue when using PHP 5.6, as the environment was set for more production usage than debugging, or could've allowed a loose cast within the Memcached library's bindings.

PHP's documentation states that references cannot be primitives/etc, and attempting to pass null/an integer causes it to fail.

This is confirmed by a basic script:

```php
<?php

some_reference(null);
some_reference(1234);

function some_reference(&$var) {
	// nothing
}
```

**Comment by nikkiii** [comment]
@GrahamCampbell Any chance this issue can be re-opened? Not an HHVM issue, but definitely a Laravel one.

**Comment by themsaid** [comment]
Closing since Laravel 5.3 doesn't support hhvm and 5.2 is closed.

**Comment by sisve** [comment]
@themsaid Ignore the HHVM-part; the docs for getMulti indicates it's by-reference, and you cannot pass null directly to it. It must go via a variable, like the example code shows. The issue fails on PHP 5.6 too.

Line: https://github.com/laravel/framework/blob/5.3/src/Illuminate/Cache/MemcachedStore.php#L67
Docs: http://php.net/manual/en/memcached.getmulti.php

**Comment by sisve** [comment]
After a lot of tests it seems to end up as a case of php magic. The internal api (getMulti) allows these kind of things, while userland code doesn't. So ignore my comment. It never happened. *does jedi hand-wave*

**Comment by nikkiii** [comment]
It seems to depend on the Memcached library version, I'm currently looking into it to see where the change causing it to pass/fail is.

**Comment by sisve** [comment]
To add to the fun; the current code will be invalid in the latest release of memcached since the method signature recently. Wordpress has a related issue created only 8 days ago.

Issue: https://github.com/php-memcached-dev/php-memcached/issues/229
Wordpress issue: https://github.com/tollmanz/wordpress-pecl-memcached-object-cache/issues/86

**Comment by lagbox** [comment]
Much fun, that method now only takes 2 arguments and will throw a warning if used as it is currently written in MemcachedStore.

```php
Cache::many(['key1', 'k2']);
```
>PHP warning:  Memcached::getMulti() expects at most 2 parameters, 3 given in /var/www/html/sites/l53/vendor/laravel/framework/src/Illuminate/Cache/MemcachedStore.php on line 66
