### ISSUE TITLE
Validation rule applied to each array element fails with URL rule

### ISSUE THREAD

**Issue by alexpechkarev** [laravel/framework#13013]
Laravel Framework version 5.2.29

```php

$dataToValidate = [ 
   'url' => [
        0 => "http://www.myaddress.co.uk/img/no-property.png"
     ],
];

$rules =[
    'url.*.url' => 'url',
];
...
$validator = Validator::make($dataToValidate, $rules, $messages); 
$validator->each('url', ['url']);

if ($validator->fails()) { // throwing error
  
```
Error
ErrorException in Validator.php line 1497:
preg_match() expects parameter 2 to be string, array given

Please can anyone advice ?

**Comment by themsaid** [comment]
You're calling `each()` wrong, you don't need to call it, make your rules array as:

```
'url.*' => 'url'
```

And remove the call to `each`.

**Comment by alexpechkarev** [comment]
Brilliant, thank you!!!
