### ISSUE TITLE
Error creating project on Laravel 5.1

### ISSUE THREAD

**Issue by donkeysharp** [laravel/framework#13017]
Hello as 5.1 is a LTS version of Laravel at job we decided to use it for internal project, just today I self-updated my composer installation and when trying to create a new Laravel 5.1 project with
`$ composer create-project laravel/laravel blog "5.1.*"`
I had the next error
```
> php -r "copy('.env.example', '.env');"
> php artisan clear-compiled
PHP Warning:  require(/home/donkeysharp/code/foo/vvvv/bootstrap/../vendor/autoload.php): failed to open stream: No such file or direct
ory in /home/donkeysharp/code/foo/vvvv/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/home/donkeysharp/code/foo/vvvv/bootstrap/../vendor/autoload.php' (include_path=
'.:/usr/share/php:/usr/share/pear') in /home/donkeysharp/code/foo/vvvv/bootstrap/autoload.php on line 17
Script php artisan clear-compiled handling the pre-update-cmd event returned with an error
```
I fixed it by removing pre-update-cmd on composer.json and with composer install it finally installed the whole dependencies.

I thought it was a composer problem but there is no problem with Laravel 5.2 so I think the problem is on 5.1
I really love Laravel but as 5.1 is a LTS version and not being able to create a project seems to be bad publicity for the project. 

I wanted to post this issue on https://github.com/laravel/laravel but it seems there isn't the option.

**Comment by vlakoff** [comment]
Known issue, still awaiting for the solution to be backported... 
See notably https://github.com/laravel/framework/pull/12827 and https://github.com/laravel/laravel/pull/3699.

**Comment by GrahamCampbell** [comment]
Thanks for reporting, but we're already aware of this. I'll speak to Taylor again, and see if he's willing to have this backported.

**Comment by Dumzy** [comment]
check there is a file type called .env. check whether your group have it. If not replace that. It will solve. Thanks
