### ISSUE TITLE
Empty array passes 'string' validation rule (2)

### ISSUE THREAD

**Issue by stefanmajoor** [laravel/framework#13011]
I asked this question earlier, but it got closed because the question was misread, and no reaction was given when I pointed this out.

So, I experienced the problem that empty arrays pass the string validation rules, since empty arrays are falsy and thus seen as an empty string. Passing this value in the query builder as string will break it however.

After some searching I found out that it was a known issue (See #10747). A fix has been made in commit 980d098ad091a5087a93202ebd4c091e336f3e58. However, this has been reverted later on in commit a7142dc041eb5a5c0507569817f5e450489c5981.

So two questions: (a) Why was this fix reverted, and (b) does this mean that this is intended behaviour?

**Comment by GrahamCampbell** [comment]
Sorry, we don't process questions here.

**Comment by philbates35** [comment]
To be fair, if an empty array really does pass a string validation rule, then that sounds like a bug to me.
