### ISSUE TITLE
UUID validation

### ISSUE THREAD

**Issue by Lozzano** [laravel/framework#13020]
Hi,
I was thinking of creating a new validation for validating UUID's, however the only way as far as I know is to create a regex.
I can see that there is no other validations using regex validations, sort of like a shortcut. I mean I could simply apply an actual regex, but having a method available to all laravel devs seems faster, but perhaps there is a policy to not do that?
Thank you for any feedback.

**Comment by GrahamCampbell** [comment]
Thanks, but we don't process this sort of thing here. Please check out our contribution guide.
