### ISSUE TITLE
[Question] Were listeners for 'illuminate.log' event removed as of late?

### ISSUE THREAD

**Issue by shehi** [laravel/framework#13022]
@taylorotwell , @GrahamCampbell :

Up until recently, my L-5.1 based app was successfully logging all and every exception that was thrown via unit-tests' exception scenarios. But after I upgraded to L-5.2, all those exceptions stopped being logged in external log-writers (i.e. Monolog handlers, such as Hipchat, Gitter etc). They still are being recorded in laravel.log file of course.

I debugged the case, and ended up in:
https://github.com/laravel/framework/blob/5.2/src/Illuminate/Events/Dispatcher.php#L220

where latest L-5.2 doesn't fetch any listeners for logging. My question is: were any loggers removed from Laravel as of late, as a result of which my custom log-handlers stopped logging any errors, but direct errors in app? Thanks.

**Comment by GrahamCampbell** [comment]
They were renamed in L5.2. Please see the upgrading guide.

**Comment by shehi** [comment]
@GrahamCampbell , by "they", do you mean events? The thing is, I actually don't need events, I never added any custom listeners for log-related events anyway. They were logging both in laravel.log file and in custom handlers. But today, I only see logs in log file, handlers are not publishing exceptions. I have thoroughly read upgrade guidelines. I even emptied Handler::$dontReport property, to report everything. Yet, they are not reported. My question is why? What happened? If you could give me quick summarized answer, I'd appreciate it; otherwise I will have to dig in diffs between tags of 5.1 and 5.2 :(

**Comment by GrahamCampbell** [comment]
Most of our events were converted to objects in 5.2. Eloquent events weren't converted, but I think everything else was.

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/commit/41599959d45016f0280d986f758d414fbee81863 should cover most of it

**Comment by GrahamCampbell** [comment]
The logger code in 5.2 is identical to that in 5.1, near enough. The events were not renamed, and I cannot confirm this bug.

**Comment by shehi** [comment]
I know that @GrahamCampbell . Sorry for consuming more of your time, I know you are already full scheduled. But, with my apologies, please let me add more insight to my problem:

I know your events have been converted. That's not the topic of my concern.

In past, I had logs like these when I ran my unit tests:

![screenshot from 2016-04-05 18-15-29](https://cloud.githubusercontent.com/assets/653569/14287193/80bb9898-fb5a-11e5-866d-12c425c36ba2.png)

You can see them in detail here: https://www.hipchat.com/gLAHU63UL and they belong to March 31st. Actually, these logs **are** L-5.2 logs, and they were logged after I successfully upgraded. 

But today, the same code doesn't log the same exceptions. At the same Hipchat page, the logs belonging to today, as you can see, don't list exceptions, as those of March 31st do.

This can happen only for one reason: Logging system in framework was altered, as a result of which this is happening. I just ask, is this really the case, or am I having a problem related to my code? Because between March 31st and today only one thing is different: laravel/framework version that composer pulls :)

As I said, my laravel.log has all necessary logs:

![screenshot from 2016-04-05 18-20-06](https://cloud.githubusercontent.com/assets/653569/14287349/154b3c34-fb5b-11e5-80e6-8e6fbb2e3dc5.png)

**Comment by shehi** [comment]
Ok, I think I will roll Laravel versions few numbers back and try to find which version changed this behaviour.

**Comment by GrahamCampbell** [comment]
Leaving this open so people can see it.

**Comment by shehi** [comment]
Debugged further... Hipchat response: ```{"error":{"code":400,"type":"Bad Request","message":"Message must be 10000 characters or less."}}``` :)

**Comment by shehi** [comment]
Contacted @Seldaek regarding the issue at Seldaek/monolog#629
