### ISSUE TITLE
Type declaration makes me can't overide it

### ISSUE THREAD

**Issue by MagiCarbon** [laravel/framework#13034]
https://github.com/laravel/framework/blob/master/src/Illuminate/Database/Eloquent/Model.php#L2955

i cant overide this function while trying to use timestamp.

```php
<?php
use Illuminate\Database\Eloquent\Model as Eloquent;

abstract class Model extends Eloquent {

    // ...

    // using timestamp instead of Datetime Object
    protected function serializeDate($value)
    {
        return $value;
    }
}
```

**someone get it back to old version plz...**

**Comment by GrahamCampbell** [comment]
The phpdoc always said that the method only accepted that though.
