### ISSUE TITLE
[5.2.29] Array validation : Required with

### ISSUE THREAD

**Issue by pallmallshow** [laravel/framework#13047]
Hello everybody.

I'm trying to use array validation introduced in Laravel 5.2.
But I think a bug is present. In fact, there is my array received by the request (debugged after my form submission) : 

```
array:2 [▼
  "_token" => "oqsdgfxcGBSmxjaZO40wBmnYHfivaHv3"
  "fields" => array:2 [▼
    "fr" => array:3 [▼
      "name" => ""
      "slug" => ""
      "content" => "qdzd"
    ]
    "es" => array:3 [▼
      "name" => ""
      "slug" => ""
      "content" => ""
    ]
  ]
]
```

In my validation rules, I doing this :
```php
return [
    'fields.*.content' => 'required_with:fields.*.name'
];
```

Normally in this case, the validation failed on the fields[fr][content], because the name was not set yet right ?

I'm so sorry if the bug is provided by between my chair and my desktop ...

**Comment by GrahamCampbell** [comment]
Are you using the very latest version?

**Comment by pallmallshow** [comment]
I'm using the 5.2.29.

**Comment by vlakoff** [comment]
ping @themsaid :)

**Comment by themsaid** [comment]
@pallmallshow 

In your example `fields[fr][content]` is required only if `fields[fr][name]` has a value, I think you are trying to do that:

```
'fields.*.name' => 'required_with:fields.*.content'
```

**Comment by pallmallshow** [comment]
I've tried this rule but I had the same result.
I set content field but I keep the name field empty, and validation passed.
I set name field but I keep the content textarea empty, and validation passed.

**Comment by themsaid** [comment]
@pallmallshow you are right, bug catched and a fix was proposed in https://github.com/laravel/framework/pull/13058

**Comment by themsaid** [comment]
@GrahamCampbell I think this one is resolved.

**Comment by pallmallshow** [comment]
Due to the PR merged yes, technically this one is resolved.
But when I run `composer update`, on a simply fresh install, I had the "old" code of Validation.php.
It's not so important for me for the moment ;)

**Comment by themsaid** [comment]
@pallmallshow it'll be available in the next patch release. 5.2.30

**Comment by pallmallshow** [comment]
Oh right no problem. Thanks ! Maybe I set issue closed when I can test on my case on the next release ?

**Comment by GrahamCampbell** [comment]
You can test the new code at any point. There doesn't have to be a tag.
