### ISSUE TITLE
【bug】blade @push('something') not working after I upgrade Laravel 5.2 to 5.2.27 & 5.2.29

### ISSUE THREAD

**Issue by duruitang** [laravel/framework#13045]
This is NOT working after I upgraded:
```
@push('something')
<script>
...............
</script>
@endpush
```

But this is working:
```
@push('something')

<script>
...............
</script>

@endpush
```

**Comment by duruitang** [comment]
Sorry, It's all working after I clear all views cache...
But I don't know why...

**Comment by GrahamCampbell** [comment]
We introduced a bug in 5.2.27 and then fixed it. Going from 5.2.20 or something to 5.2.29 won't require a cache clear, but 5.2.27 to 5.2.29 might do.
