### ISSUE TITLE
returning a null relation

### ISSUE THREAD

**Issue by browner12** [laravel/framework#13056]
I opened #8830 awhile ago, and then forgot about it. thought about it again today, and was going to submit the PR, but another thought crossed my mind.  Would a `NullRelation` object be something good to create? This way the `getRelationshipFromMethod` method would not need to change, and it may give us the opportunity to do some other things with nulls.

```php
namespace Illuminate\Database\Eloquent\Relations;

class NullRelation extends Relation
{
    public function getResults()
    {
        return null;
    }
}
```

Then in the models you could do

```php
class Game extends Model
{
    public function winningTeam()
    {
        //home team won
        if ( $homeTeamWon )
        {
            return $this->belongsTo('App\Team', 'home_id');
        }
        elseif ( $awayTeamWon )
        {
            return $this->belongsTo('App\Team', 'away_id');
        }

        //game resulted in a tie
        return $this->nullRelation('App\Team');
    }
}
```

This popped into my head as I was writing the PR, so I'm curious about others' thoughts on this. If needed, I can move this over to an internals issue for further discussion.

Thanks.

**Comment by GrahamCampbell** [comment]
Hmmmm, interesting idea. Note that we wouldn't actually need the `return null;` there. An empty method body would do just fine.

**Comment by GrahamCampbell** [comment]
Feel free to discuss this on the internals repo, or slack.
