### ISSUE TITLE
Event listeners definied by a container alias can not be queued

### ISSUE THREAD

**Issue by philbates35** [laravel/framework#13061]
Background: My application imports data from two distinct emails that are POSTed to the same route (`/mandrill/incoming`). I determine which email it is, and therefore how to import from the email, by checking the subject title. I am aware that this isn't ideal, but different customers have their own version of the application, and they have varying numbers of emails to import from, which is why we chose to have a single route responsible for receiving and importing.

So I created a single event listener class that took an `$emailImporter` class and an `$allowedSubject` in the contstructor, which allowed me to use the same event listener class twice. This worked perfectly fine, but now I want to queue the listeners, and in doing so I've realised that defining listeners in this way means that the listeners can not be queued, even though the listener class implements `ShouldQueue`.

```php
namespace App\Listeners;

use App\Contracts\EmailImporter;
use App\Events\EmailWasImported;
use Illuminate\Contracts\Queue\ShouldQueue;

class ImportFromMandrill implements ShouldQueue
{
    private $importer;
    private $allowedSubject;

    public function __construct(EmailImporter $importer, $allowedSubject)
    {
        $this->importer = $importer;
        $this->allowedSubject = $allowedSubject;
    }

    public function handle(EmailWasImported $event)
    {
        if ($event->email()->subject() !== $this->allowedSubject) {
            return;
        }

        $this->importer->importFromEmail($event->email());
    }
}
```
```php
namespace App\Providers;

use App\Listeners\ImportFromMandrill;
use App\Import\ApplesImporter;
use App\Import\PearsImporter;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    public function register()
    {
        $this->app->bind('listener.import-apples', function() {
            return new ImportFromMandrill(new ApplesImporter(), 'Apples Import Email');
        });

        $this->app->bind('listener.import-pears', function() {
            return new ImportFromMandrill(new PearsImporter(), 'Pears Import Email');
        });
    }
}
```
```php
namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class EventServiceProvider extends ServiceProvider
{
    protected $listen = [
        \App\Events\EmailWasImported:class => [
            'listener.import-apples',
            'listener.import-pears',
        ],
    ];
}
```
The reason why they aren't queued is because of the logic [here](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Events/Dispatcher.php#L392): At that point, `$class` is the alias (e.g. `listener.import-apples`). Of course, an exception is thrown and then the method returns `false`.

Would it not make sense to check if `$class` is a container alias, and if so, check if the listener class it resolves to implements `ShouldQueue`?

I will fix this issue by created two separate listener classes (`ImportApplesEmail` and `ImportPearsEmail`) rather than reusing the same class via container aliases, which will result in queuing working properly again.

Maybe this isn't a bug per-se, but IMO it's unexpected behaviour (it took me a while to work out what was going on and why they weren't being queued) so I thought I'd raise it and see what you thought.

**Comment by GrahamCampbell** [comment]
I think this is probably just a no-fix edge case. Thanks though.
