### ISSUE TITLE
[5.2] Session might never timeout with certain handlers

### ISSUE THREAD

**Issue by HolgerW1** [laravel/framework#13064]
The less users use your system and the smaller your session timeout value is the more likely it is for this bug to occur. This bug will **always** occur if only one user uses the system and if your GC lottery is set to 100%.

The actual problem is caused by the `StartSession` middleware and the way the garbage collection and thus the session expiration is triggered. Due to the GC functionality, not all handlers are affected since e.g. the cache handler (redis, ...) doesn't use the internal GC at all.

Steps to reproduce:
1. set the session lifetime to a very low value like 1 minute (`lifetime` config entry) to make tests a little easier
2. set the session driver to `file`
3. set the GC lottery to 100% `[100, 100]`
4. make a request
5. wait more than 1 minute, don't make any other requests with any other user during this time
6. make another request with the same user

The expected behavior would be that your session has expired and that you get a new session.

What actually happens is:
- the session is still valid on the **first** request after the timeout occured. it doesn't matter how long ago the timeout occured (hours, days ...), since the GC (=session invalidation) can only be triggered during request cycles. `StartSession` never checks a session for expiration **before** it reads the session file but only after the `handle` method is complete.
- the session for the requesting user will be renewed even though the timeout occured and was detected (GC was triggered). The `StartSession` middleware calls `collectGarbage` in the `handle` method but also automatically creates a new session file with the current session data in the `terminate` method right after the request cycle is complete. I.e. the current session is read, the session file is deleted and automatically created again with the same session data right after it has been deleted. Which will of course extend the lifetime of the session indefinitely unless another user triggers the GC.

**Comment by HolgerW1** [comment]
Here's my suggested solution for the issue, changing the `handle` method of the `StartSession` middleware:
```php
    public function handle($request, Closure $next)
    {
        $this->sessionHandled = true;

        // If a session driver has been configured, we will need to start the session here
        // so that the data is ready for an application. Note that the Laravel sessions
        // do not make use of PHP "native" sessions in any way since they are crappy.
        if ($this->sessionConfigured()) {
            $session = $this->startSession($request);

            $request->setSession($session);

            // Check if the maximum session idle time has been reached and if the
            // session has not been invalidated yet through the GC. If that's the
            // case invalidate the session now and prevent it from being extended.
            if (time() - $session->getMetadataBag()->getLastUsed() > $this->getSessionLifetimeInSeconds()) {
                $session->invalidate();
            }
        }

        $response = $next($request);
```

Note that this should not affect cache based session handlers since they already invalidate complete sessions on their own after the specificed time by removing the cache entry. File and DB based handlers on the other hand will behave as expected and like the cache based handlers do.
`invalidate` will be called in this solution if a session has expired but the GC has not been called yet on that session for whatever reason. That will prevent a user from extending the lifetime of a session after the session has already expired.

**Comment by GrahamCampbell** [comment]
Thanks, we've patched this.
