### ISSUE TITLE
`php artisan migrate` successfully run, missing entries in migrations table

### ISSUE THREAD

**Issue by j-hernandez** [laravel/framework#13068]
This is a weird one. The replication steps are pretty much:

```
php artisan migrate
```

This was run in our prod environment after pulling down updates from the repo. The updates contained several migrations. The output from these migrations was:

```
Do you really wish to run this command? [y/N] (yes/no) [no]:
> yes

Migrated: 2016_03_31_102831_fix_name_field
Migrated: 2016_04_04_083143_create_core_tables
Migrated: 2016_04_05_183631_seed_core_table
Migrated: 2016_04_06_103137_add_timestamps_fields
Migrated: 2016_04_06_121243_add_activated_flag
Migrated: 2016_04_06_121711_fix_group_name
Migrated: 2016_04_06_165913_add_unique_index
```

Running `php artisan migrate:status` showed every migration except the first as pending. I verified that the migrations had been successfully run (tables existed, fields and indexes created, values changed), but for some reason we only had up through batch 2 (batch 2 === first migration in this list).

Each of these migrations landed in their own batch, nothing special about them. Standard stuff.

No errors, and these migrations have been run in other environments (4 dev and a testing env) without issue. For now, I manually inserted the records and will check again after our next deploy to see if this happens again.

**Comment by j-hernandez** [comment]
Closing this - last couple of deploys wrote to migrations table without issue.

**Comment by chludwig** [comment]
In case someone googles this page, having the same problem as described above.
See https://laracasts.com/discuss/channels/laravel/migrated-migration-files-not-listed-in-migration-table?page=1#reply=506723 for a possible solution.
