### ISSUE TITLE
isset is not working on nested relations 

### ISSUE THREAD

**Issue by alexweb** [laravel/framework#13062]
When I do the next check the result is always false, even when the relations exist:
```php
if(isset($user->profile->photo){
    return true;
}
else{
    return false;
}
```

**Comment by GrahamCampbell** [comment]
not a bug

**Comment by GrahamCampbell** [comment]
you need to instead check for is_null

**Comment by alexweb** [comment]
is_null will give me error (not object) if profile does not exists.

**Comment by GrahamCampbell** [comment]
you need two checks here then

**Comment by alexweb** [comment]
Yes, and it's not convenient for dep relations. Also it's not logical becase $user->profile->photo is set and not empty...
