### ISSUE TITLE
Illuminate\Routing\Route#uses does not parse action correctly if string

### ISSUE THREAD

**Issue by amitailanciano** [laravel/framework#13074]
It seems as though the `uses` method on Illuminate\Routing\Route does not parse string actions correctly if you pass a string, it bails in `findCallable` because it assumes it's already an array of `['uses' => $action]`, however `parseAction` in the same file will always be true on line 549 `elseif (! isset($action['uses'])) {` and so will always run `findCallable`

```
Route::get('login')->name('page.admin.login')->uses('Admin\Auth\AuthController@showLoginForm');
```

Results in
```
Type error: Argument 1 passed to Illuminate\Routing\Route::findCallable() must be of the type array, string given, called in /home/vagrant/bowlathon-web/vendor/laravel/framework/src/Illuminate/Routing/Route.php on line 550
```

**Comment by lagbox** [comment]
@themsaid does 13076 close this?

**Comment by themsaid** [comment]
@lagbox yes, it fixes the issue.

**Comment by lagbox** [comment]
you da man
