### ISSUE TITLE
Polymorphic Owner's Relation Not Getting 

### ISSUE THREAD

**Issue by ziabs** [laravel/framework#13072]
**My Like Model**
```
class Like extends Model
{
public function likeable()
    {
        return $this->morphTo();
    }
}
```
**My Movie Model**
```
class Movie extends Model
{
public function likes()
    {
        return $this->morphMany(Like::class, 'likeable');
    }
public function photos()
    {
        return $this->morphMany(Photo::class, 'imageable');
    }
}
```
**Controller **
`$likes=Like::with('likeable')->where('user_id',1)->get();`
Here I am getting all the likes by the given user with the respective movies, but if I try to access the Movie photos via relation its making so many extra queries (N+1)
`$likes->first()->likeable->photos`
And if I add the photo relation to querying time its not making any difference (Not checking only the relation )  
`$likes=Like::with(['likeable.photos'])->where('user_id',1)->get();`

**Comment by 20TRIES** [comment]
Hey, its been a while since you posted this, but this may help #6368.
