### ISSUE TITLE
[5.1] softDelete and orWhereHas inserts also deleted

### ISSUE THREAD

**Issue by damianopetrungaro** [laravel/framework#13070]
When i try to get data from this query 

    return $query->whereHas('users', function ($q) use ($id) {

                    $q->where('users.id', $id);

                })->orWhereHas('clients.users', function ($q) use($id) {

                        $q->where('users.id', $id);

                });

I must add `->whereNull('deleted_at');`, at the end for get the right data.

Also if i use (as explained in the doc) the advance where clauses, `$q->where('users.id', '=', $id);`, the data i get is wrong.

**Comment by ashleydw** [comment]
I'm pretty sure you'll find, it you print the execute query it'll be:

`WHERE this AND that OR those AND softDelete =  null`

you need to wrap your where's and orWhere: https://laravel.com/docs/5.1/queries#advanced-where-clauses

**Comment by damianopetrungaro** [comment]
Perfect!
Wrapped in a where clause and it works as expected.


         return $query->where(function ($q) use ($id) {

            $q->whereHas('users', function ($q) use ($id) {

                $q->where('users.id', $id);

            })->orWhereHas('clients.users', function ($q) use($id) {

                $q->where('users.id', $id);

            });

        });



Thank you @ashleydw for clarifying!
