### ISSUE TITLE
Do not SELECT * in Auth::attempt() and why password is not checked in SQL?

### ISSUE THREAD

**Issue by Mevrael** [laravel/framework#13085]
**1.** Currently `attempt()` method executes query ```select * from `users` where `email` = ? limit 1 ``` which in some cases where `users` table have many string and text columns ("about me" and whatever else) may take a lot of extra time when it could take much less time.
https://github.com/laravel/framework/blob/5.2/src/Illuminate/Auth/EloquentUserProvider.php#L104

Since we need only to check if user exists in DB I would recommend changing this line of code to something like:
```php
return $query->select('id', 'password')->first();
```

However, I am not sure about full architecture and codebase, probably other peaces of code also could be optimized or it should be done somewhere else.

What I can tell is the only at least id and password should be returned to keep existing code working and not breaking anything.

**2.** By the way why password is not checked in SQL query?
```php
        foreach ($credentials as $key => $value) {
            if (! Str::contains($key, 'password')) {
                $query->where($key, $value);
            }
        }
```

**Comment by GrahamCampbell** [comment]
I assume it is being selected, but when you var_dump a query result, we hide the password field by default.

**Comment by GrahamCampbell** [comment]
Feel free to ask more questions on the forums.

**Comment by GrahamCampbell** [comment]
Oh, I see, you're making a suggestion. Well, we can't do that, because this method is public, and changing that will break everything. Your use case here is only one case for calling that method.

**Comment by thomasruiz** [comment]
@Mevrael `SELECT *` because of `Auth::user`. We need all the information in case of a successful login. Better to do it all at once.
The password is not checked in SQL because of the way the Hasher works.

**Comment by Mevrael** [comment]
@thomasruiz aren't your login logic done in POST handler and aren't you redirecting after successful login?

**Comment by GrahamCampbell** [comment]
Doesn't have to be.

**Comment by Mevrael** [comment]
@GrahamCampbell I am not talking exactly about certain method. As I said I am not sure about the architecture. The main topic is checking for email/username+password which is done in Laravel via Auth::attempt()  returning true/false

Login time same as index page loading time is critical for business applications and when you have millions of users, a lot of columns within users table, probably even SQL server located in another machine but even on localhost MySQL transfers data via network and also when doing requests to social providers (facebook, etc.) total login time for user might take many seconds.

> Doesn't have to be.

View login in MVC also doesn't have to be in template files. Example?

**Comment by robclancy** [comment]
I think you should learn how it works before suggesting changes. It doesn't "just return true or false" it stores the user as the logged in user. A poor way of doing this would be to select few columns then have to select more later, like you suggest.

**Comment by Mevrael** [comment]
@robclancy I think you should learn how web and HTTP works too.

> A poor way of doing this would be to select few columns then have to select more later, like you suggest.

"later" means another HTTP request where you will have to recieve that data anyway.

**Comment by thomasruiz** [comment]
@Mevrael you can always extend `Guard` if you have a such a big `users` table. For 99.9% of the websites, getting all the data for 1 row won't take 1ms more than just taking 2 columns, and it will very probably save a query for the current request.

**Comment by robclancy** [comment]
@Mevrael you just went full retard. Stop while you're behind.

**Comment by GrahamCampbell** [comment]
Locking this because this is getting nowhere, and Rob as resorted to :trollface: again.
