### ISSUE TITLE
about '[5.1] [5.2] Composer update issues #9678'

### ISSUE THREAD

**Issue by thbighead** [laravel/framework#13093]
Sorry to reopen this issue, but I found why my project was getting this error https://github.com/laravel/framework/issues/9678

Basically I generated my .gitignore with https://www.gitignore.io/ using Laravel as keyword. and it gives me this file:

# Created by https://www.gitignore.io/api/laravel

### Laravel ###
vendor/
node_modules/

# Laravel 4 specific
bootstrap/compiled.php
app/storage/

# Laravel 5 & Lumen specific
bootstrap/cache/ <----------
storage/ <----------
.env.*.php
.env.php
.env

# Rocketeer PHP task runner and deployment package. https://github.com/rocketeers/rocketeer
.rocketeer/

As I pointed there, those folders are being ignored by git and that's why php artisan clear-compiled command is returning an error saying that it can't found files or folders...

**Comment by GrahamCampbell** [comment]
What error?

**Comment by GrahamCampbell** [comment]
Looks like a rocketeer bug.
