### ISSUE TITLE
Flash Issue

### ISSUE THREAD

**Issue by shamir92** [laravel/framework#13094]
Dear Sir/ Madam, 

i have a bit problem with session in laravel 5.2.29 

if in the laravel 5.2.14 i use route group with middleware web , the session flash work. But in 5.2.29 with middleware web, the flash did not work. i dont know why, but if i check session::start its return true, and if i use simple route like  below, its work. 

is it a bug in 5.2.29 ? 
thanks 

Route::get('/test',function(){
		
		Session::flash('error','shamir');
		return redirect()->intended('/');

	});

Route::group(['middleware' => ['web']], function () {
    
    //default login
	Route::get('/',['as' => 'login','uses' => 'usermanagement\usermanagement@Login']);
	Route::post('/loginprocess',['as' => 'postLogin','uses' => 'usermanagement\usermanagement@Login_Process']);
	
});

**Comment by GrahamCampbell** [comment]
not a bug, please see the other issues

**Comment by shamir92** [comment]
can you tell me which issue that found like this ? 
thanks

**Comment by shamir92** [comment]
thanks 
this issue solved 
thanks alot 

some changes in RouteServiceProvider
