### ISSUE TITLE
Beanstalk queue Error "[PDOException] could not find driver". when save database eloquent

### ISSUE THREAD

**Issue by rizkyred** [laravel/framework#13092]
Hei guys i got an error "Error [PDOException] could not find driver" like describe on my title. anyone know how to fixed it ??

`namespace Automation\Jobs;

use Automation\Models\UserLog;
use Automation\Models\User;
use Automation\Jobs\Job;
use Illuminate\Queue\SerializesModels;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;

class SendReminderEmail extends Job implements ShouldQueue
{
    use InteractsWithQueue, SerializesModels;

    protected $user;

    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct($id)
    {

      $this->user = $id;
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        echo "start";

        $userlog = new UserLog;
        $userlog->email = $this->user."@test.com";
        $userlog->admin = $this->user;
        $userlog->description = $this->user;
        $userlog->created = date("Y-m-d H:i:s");
        $userlog->save();

        $sleep = mt_rand(1, 10);
        sleep($sleep);

        $userlog = new UserLog;
        $userlog->email = $this->user."@test.com";
        $userlog->admin = $this->user;
        $userlog->description = $this->user;
        $userlog->created = date("Y-m-d H:i:s");
        $userlog->save();

        echo "end";
    }
}`

and i just call with function like this
`$this->dispatch(new SendReminderEmail(7));`

i worked on ubuntu server and the error appears when im using php artisan queue:listen on command line

**Comment by GrahamCampbell** [comment]
please ask on the forums.

**Comment by rizkyred** [comment]
this happens because im not installed sql on linux.
 In linux terminal: sudo apt-get install php5-mysql and that problem gone
