### ISSUE TITLE
[Feature Req] a better implementation of the current cache::tags

### ISSUE THREAD

**Issue by ctf0** [laravel/framework#13100]
right now as stated in the [docs](https://laravel.com/docs/5.2/cache#accessing-tagged-cache-items), u can have something like

```php
Cache::tags(['people', 'artists'])->put('John', $john, $minutes);
Cache::tags(['people', 'authors'])->put('Anne', $anne, $minutes);
```
and when u flush u can simply use

```php
Cache::tags('people')->flush();
```
which will remove both `John & Anne` but this is not what u would expect, because both the `artists` & `authors` still intact.

another issue with the `get()` which u have to call the tags in the same order u did with the `put()` which is ineffective,
cuz u dont go to youtube and call all the tags under_the_sun to get what u want, instead its used for filtering, so something like the below will output `null`

```php
Cache::tags('people')->get();
```
<br>
##### So what i suggest is to use something like 

```php
Cache::tags(['people'])->sub(['artists'])->put('John', $john, $minutes);
Cache::tags(['people'])->sub(['authors'])->put('Anne', $anne, $minutes);
```
- so now it works as u think & u can call either the parent tag or the child/sub_tags 
```php
Cache::tags(['people'])->get()  // ['John','Anne]
// or 
Cache::tags(['artists'])->get() // ['John']
```
- same for flushing, removing the parent tag will then remove all its sub_tags and u get `null`.
```php
Cache::tags(['people'])->flush()  // people , people.artists , people.authors = null
// or 
Cache::tags(['artists'])->flush() // artists , people.artists = null
```

**Comment by GrahamCampbell** [comment]
We're open to PRs. Going to close this for now since we don't process proposals on the issue tracker. Thank you though!

**Comment by ctf0** [comment]
moved to https://github.com/laravel/internals/issues/124
