### ISSUE TITLE
For testing of API request get not working

### ISSUE THREAD

**Issue by arifmahmudrana** [laravel/framework#13101]
My test code

        $this->json('POST', 'posts/' . $post->id . '/likes' . '?access_token=' . $user->access_token, [
            'action' => 'Like',//I pass Like as post params
            'profile_id' => $profile->id,
        ])->seeJsonEquals(json_decode('{"error":{"message":"Already liked","status":"400"}}', true));

But I can't access my post params using `$request->get('action')` where `$request` is an instance of `Illuminate\Http\Request` in fact I can't use  `$request->get('action')` in testing I had to use `$request->input('action')`

When I `dd(get_class_methods($request))` I see `get` method in the object but when I call `$request->get('action')` it returns `null` where else `$request->input('action')` or `$request->action` is returning correct value `Like`

**Comment by GrahamCampbell** [comment]
Thanks for the report, but I can't replicate this. Please try upgrading to the latest Laravel version.

**Comment by jackbutler** [comment]
Hey @arifmahmudrana do you remember if/how you fixed this? Having the exact same issue with testing and using $request->get()

**Comment by arifmahmudrana** [comment]
@jackbutler I used `$request->input()` or directly accessing property like `$request->title`

**Comment by jackbutler** [comment]
@arifmahmudrana ah okay, I considered this but for me it would mean refactoring a lot of code.

For anyone else that has this issue, in my case $this->post() worked just fine rather than explicitly using $this->json(), and meant I avoided having to change all my $request->get() to ->input().
