### ISSUE TITLE
failed job doesn't fail gracefully

### ISSUE THREAD

**Issue by finalight** [laravel/framework#13106]
assuming this code

```
foreach ($results->products as $record) {
				$product_manager->addOrUpdate($record, $this->shopid);
			}

if ($this->attempts() > 1) {
			$this->delete();
		}
```

if there's no such property 'products', the queue will keep indicating that there's no such property.

**Comment by GrahamCampbell** [comment]
That's because you're crashing the server with a fatal error. We can only recover from exceptions, not broken code.
