### ISSUE TITLE
Laravel Authorization: resolveUser returns null for authenticated user

### ISSUE THREAD

**Issue by raghavendra89** [laravel/framework#13104]
I'm using multiauth in Laravel 5.2. I'm not able to get the authorization working.

I've defined the `ability` in the `AuthServiceProvider`:

  
      $gate->define('is-admin', function ($user) {

        if ($user->role_id == 1) {
            return true;
        } else {
            return false;
        }
    
      });
    
And in controller I've this line:

`$this->authorize('is-admin', Auth::guard('operator')->user());`

But this authorization check always returns Unauthorized response.

I tried to trace the issue and found that the `resolveUser` method in the `Gate (Illuminate\Auth\Access\Gate)` class returns null, eventhough the user is logged in. My guess is that this method doesn't determine the right guard to get the authenticated user.

Can any one help me to get the authorization working?

Thanks!

**Comment by GrahamCampbell** [comment]
Please ask on the forums.

**Comment by raghavendra89** [comment]
ok. Thanks!
