### ISSUE TITLE
[5.1] Storage::exists('.hidden_file') returns false

### ISSUE THREAD

**Issue by heisian** [laravel/framework#13119]
Laravel 5.1 running on Fedora 23, with NGINX & PHP7-FPM

### Base class/method call:
```
/* Filesystem config (from base_path/config/filesystem.php)
...
        'app_root' => [
            'driver' => 'local',
            'root'   => base_path(),
        ],
...
*/

if(Storage::disk('app_root')->exists('.hidden_file'))
    echo "OK";

// Does not echo "OK", therefore returns false, even though `.hidden_file` does in fact exist.

$file = Storage::disk('app_root')->get('.hidden_file');
print_r($file);

// Works! Prints contents of file.
```

### So let's examine the Filesystem Driver:

Within `vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php`:
```
    /**
     * Determine if a file exists.
     *
     * @param  string  $path
     * @return bool
     */
    public function exists($path)
    {
        var_dump($this->driver->has($path), $path); // Added to verify returns true
        return $this->driver->has($path);
    }
```
returns:
```
/var/www/root/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php:42:
bool(true)
/var/www/root/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php:42:
string(11) ".hidden_file"
```

I also checked with league/Flysystem, and it is indeed returning `true` for the `.hidden_file`.

### Current workaround:
```
if (file_exists(base_path().'/.hidden_file'))
    echo "OK";
```

**Comment by heisian** [comment]
probably not a very high priority thing but I'll check out how I can make a pull request for this soon.

**Comment by vlakoff** [comment]
Didn't you invert some logic?
```
if (! Storage::disk('app_root')->exists('.hidden_file'))
    echo "OK";

// Does not echo "OK", therefore returns false, even though `.hidden_file` does in fact exist.
```
This code echoes OK if the file doesn't exist.
But the file exists, so the code doesn't echo OK.

**Comment by heisian** [comment]
oh sorry, in my original code it was an exception thrown not an echo "OK".  so the reverse, it would be.  editing the original post.

**Comment by vlakoff** [comment]
With this flysystem and these adapters there are so many goddamn layers rather than just a php function...

**Comment by GrahamCampbell** [comment]
> With this flysystem and these adapters there are so many goddamn layers

I don't see abstraction as a bad thing. Quite the opposite.

**Comment by vlakoff** [comment]
Different points of view, let's not sidetrack with this ;)

@heisian, have you figured out where the bug could be?

**Comment by heisian** [comment]
not yet, at the moment i'm working on a pretty epic deployment script.  will probably take a closer look later this week :]

**Comment by KennedyTedesco** [comment]
@heisian Have you tried this?

```
'app_root' => [
    'driver' => 'local',
    'root'   => base_path() . '/',
],
```

Is missing the directory separator on your config.

Or, if you prefer:

```
Storage::disk('app_root')->exists('/.hidden_file')
```

**Comment by vlakoff** [comment]
This issue really doesn't make sense, as you have tested the inner Flysystem and it is indeed returning the expected result. @heisian are you sure there isn't some mistake in your code?

**Comment by heisian** [comment]
@KennedyTedesco you don't need to add a backslash for the file.  As I said, this works:
```
$file = Storage::disk('app_root')->get('.hidden_file');
print_r($file);
```
As does this:
```
$file = Storage::disk('app_root')->get('NotHiddenFile.php');
print_r($file);
```

**Comment by heisian** [comment]
well, revisiting this it works now:
```
10:28 $ php artisan tinker
Psy Shell v0.7.2 (PHP 7.0.5 — cli) by Justin Hileman
>>> Storage::disk('app_root')->exists('.gitmodules')
=> true
>>> 
```
Not sure what the deal was before or what had caused the discrepancy between the result within Flysystem and the Storage facade.
