### ISSUE TITLE
Cached Eloquent relations not cleared between running acceptance tests.

### ISSUE THREAD

**Issue by mcordingley** [laravel/framework#13115]
If in a controller you have `$someModel->relation;` and in some other controller you have the same, then the cached value of that relation persists between tests run through Laravel's integrated testing facilities. This can cause tests that manipulate those values to fail, even as the code works outside of the test.

**Comment by GrahamCampbell** [comment]
Looks like a bug in your application.

**Comment by mcordingley** [comment]
Found it. Posting here in case anyone else runs into this.

- Nothing that I've seen automatically clears relations. This seems to be by design and is :+1:.
- The request user object is persisted between tests. Therefore, all of its relations stay cached between requests, and so forth as long as there is a chain of references. This may be a bug in the testing system.
- My solution was to call `$request->user()->setRelations([]);` to manually clear its cached relations in `teardown` after each test.
