### ISSUE TITLE
[5.1] Named routes in a group is not working on chainned method

### ISSUE THREAD

**Issue by vluzrmos** [laravel/framework#13118]
Naming routes in a group like below is not working:

```php
Route::group(['as' => 'group.'], function () {
    Route::get('/', 'FooController@foo')->name('route');
});
```
When I try to reference `route('group.route')` I got an error.
    
    Route [group.route] not defined.

If I try:

```php
Route::group(['as' => 'group.'], function () {
    Route::get('/',  [ 'as' => 'route', 'uses' =>'FooController@foo']);
});
```

It will works fine.

**Comment by GrahamCampbell** [comment]
Can you dump the routes using the cli command please in both cases?

**Comment by vluzrmos** [comment]
I don't know why, in my real project it throws that error, but in a new laravel app it works fine.

Sorry for bothering...

**Comment by vluzrmos** [comment]
In my real project, both ways generate the same route:list ...

**Comment by vluzrmos** [comment]
![image](https://cloud.githubusercontent.com/assets/450848/15030290/cd82fbba-1227-11e6-9202-a6b0ff350980.png)

The router is getting both "as" and "prefix" group option as part of the route name.

my group has the following config:

$router->group([
    'prefix' => 'panel',
    'as' => 'panel.'
], closure);

The "front." alias has no prefix.

**Comment by plopinou** [comment]
I also have the same issue with resource route names inside a group getting both prefixes from 'prefix' and 'as'.
The culprit seems to be in the getGroupResourceName function inside \Illuminate\Routing\ResourceRegistrar.php
It will always add the group prefix in the route name if there is one, but by default, every routes inside a group will also pass through the mergeGroup function in \lluminate\Routing\Router.php that will handle the 'as' hierarchy.

A correction attempt would look like that :
```php
// in \Illuminate\Routing\ResourceRegistrar.php
protected function getGroupResourceName($prefix, $resource, $method)
{
    $groupRouteName = $this->router->getLastGroupRouteName();
    $groupPrefix = trim(str_replace('/', '.', $this->router->getLastGroupPrefix()), '.');

    if (empty($groupRouteName) && !empty($groupPrefix)) {
        return trim("{$prefix}{$groupPrefix}.{$resource}.{$method}", '.');
    }

    return trim("{$prefix}{$resource}.{$method}", '.');
}


// in \lluminate\Routing\Router.php
public function getLastGroupRouteName()
{
    if (! empty($this->groupStack)) {
        $last = end($this->groupStack);

        return isset($last['as']) ? $last['as'] : '';
    }

    return '';
}
```

I don't have enough experience with the laravel core code to be sure that this will not break something else, so I'll not do a Pull Rrequest.

**Comment by anishdcruz** [comment]
@vluzrmos @GrahamCampbell I found the issue

https://github.com/laravel/framework/blob/5.2/src/Illuminate/Routing/ResourceRegistrar.php#L236

The method `getGroupResourceName ` is not checking for existing group alias.



```
protected function getGroupResourceName($prefix, $resource, $method)
    {

        $group = trim(str_replace('/', '.', $this->router->getLastGroupPrefix()), '.');


        if (empty($group)) {
            return trim("{$prefix}{$resource}.{$method}", '.');
        }


        // solution: get the last group alias name from the Illuminate/Routing/Router.php
		// getLastGroupAlias() method is currently not defined.
		
        if (!empty($this->router->getLastGroupAlias())) {
            return trim("{$prefix}{$resource}.{$method}", '.');
        }

        return trim("{$prefix}{$group}.{$resource}.{$method}", '.');
    }
```

add the getLastGroupAlias() method to the below file

https://github.com/laravel/framework/blob/5.2/src/Illuminate/Routing/Router.php#L499

```
/**
     * Get the alias name from the last group on the stack.
     *
     * @return string
     */
    public function getLastGroupAlias()
    {
        if (! empty($this->groupStack)) {
            $last = end($this->groupStack);

            return isset($last['as']) ? $last['as'] : '';
        }

        return '';
    }
```

this is dirty solution. 

Thanks

**Comment by anishdcruz** [comment]
@GrahamCampbell can u confirm if this bug is fixed?

**Comment by GrahamCampbell** [comment]
No idea. Feel free to try it out.

**Comment by themsaid** [comment]
Closing since it's working in laravel 5.3 already.
