### ISSUE TITLE
[5.2] Environment variables not overridden by .env

### ISSUE THREAD

**Issue by dandart** [laravel/framework#13116]
Hi, apologies if this has been covered before, I was led to believe that .env would override the builtin environment variable, e.g. REDIS_PORT. However even changing .env makes retrieving this variable still not be overridden, so I get the original version of the environment variable. I expect to see the overridden one. This has caused significant head scratching...

Cheers

**Comment by GrahamCampbell** [comment]
We only load env variables from .env when config is not cached.

**Comment by GrahamCampbell** [comment]
You should never be reading env variables in your apps. Instead, read the env stuff in the config files themselves.

**Comment by dandart** [comment]
Yes, that's what I'm doing. Just using the default config (which presumably uses .env).
Thing is that the .env doesn't override the getenv() call which the config getter makes.

**Comment by GrahamCampbell** [comment]
It should do.

**Comment by dandart** [comment]
That's what it's not doing here for me in the latest pull.
I'm using REDIS_PORT=6379 in my .env for instance, but in config/database.php where it pulls 'port' => env('REDIS_PORT', 6379), this returns the original (non-.env) environment variable on my system.
