### ISSUE TITLE
Illuminate\Support\Collection#toArray assumes I want a deep transformation

### ISSUE THREAD

**Issue by amitailanciano** [laravel/framework#13120]
`toArray` is implemented as follows:

```
    /**
     * Get the collection of items as a plain array.
     *
     * @return array
     */
    public function toArray()
    {
        return array_map(function ($value) {
            return $value instanceof Arrayable ? $value->toArray() : $value;

        }, $this->items);
    }
```

I am working with objects that perform expensive serialization that implement `Arrayable` for other reasons, and I would like to have the option to only convert the top level Collection to an array of those objects -- I propose something like `toArray($deep = true)`

**Comment by GrahamCampbell** [comment]
Sorry, we don't process proposals here. Please read our contribution guide.

**Comment by amitailanciano** [comment]
@GrahamCampbell sorry about that
