### ISSUE TITLE
[5.2] Large payload in database cache table causes corrupt data with decryptor

### ISSUE THREAD

**Issue by Sander-Kastelein** [laravel/framework#13126]
![example_1](https://cloud.githubusercontent.com/assets/9445855/14453478/67cc8668-0095-11e6-8734-001739da6f6a.png)

Using the database as a caching mechanism will crash when trying to store large objects in the cache, the framework will throw a decrypt error when trying to receive from the cache (because the original payload was cut off by MySQL because the datatype used is too small to store the cache object). This causes weird behavior when using Cache::remember(), the first lookup will succeed because it will write to the DB without error, and it will return the original object, however on following lookups it will throw the error seen in the attached image.

Not that much of a bug but maybe there should be some sort of checking mechanism before trying to decrypt data from the database? Or maybe a system which won't write to the cache if the object is to big to fit.

Thanks in advance for looking into this.

-- Edit

This error actually occurred on Laravel 5.1 I was thinking of the wrong project. :sweat_smile:

**Comment by GrahamCampbell** [comment]
How large? What PHP version?

**Comment by GrahamCampbell** [comment]
Not a bug. MySQL is just crap, and truncates data without warning. I'd recommend using Postgresql instead. There's nothing we can really do about MySQL.

**Comment by Sander-Kastelein** [comment]
Using PHP version PHP 7.0.3-5
Longer than the column datatype in the cache database table (default in doc is TEXT which would be 65,535 (216−1) bytes = 64 KiB but this could differ per implementation).

Even though "MySQL is just crap", and people should probably not be using MySQL cache in production, it's useful for development/testing. 

That being said, the MySQL driver could probably add a checksum or at least the object length to the table (extra column, or maybe fixed length prepended to the object blob?), then verify when looking up. This will be slow, but this should probably not be used in production anyways, (for obvious reasons, as well as being prone to this bug).

This should be fixed due to the face that Laravel does support MySQL for caching, if not it should probably drop support for MySQL caching. (and add a warning to the docs).

Thanks again for looking into this.
