### ISSUE TITLE
Why Illuminate\Database\Eloquent\Builder do not use the Macroable trait ?

### ISSUE THREAD

**Issue by Swizz** [laravel/framework#13127]
Hi,

I need to create a macro on the Eloquent Builder. 
I thinked it could be possible to do the same as I do on Query Builder, but all macro logic of the first one, is not base on the rular trait and is not a static api.

Best regards,

**Comment by GrahamCampbell** [comment]
It is macroable?

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/blob/v5.2.29/src/Illuminate/Database/Query/Builder.php#L21

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/blob/v5.2.29/src/Illuminate/Database/Query/Builder.php#L2239

**Comment by Swizz** [comment]
Sorry @GrahamCampbell, I did not understand your answer.

The Eloquent Builder implement some kind of Macro logic but without the Macroable Trait and not on the static way :

https://github.com/laravel/framework/blob/v5.2.29/src/Illuminate/Database/Eloquent/Builder.php#L1301

https://github.com/laravel/framework/blob/v5.2.29/src/Illuminate/Support/Traits/Macroable.php#L24

The purpose of my question is to know more about the choice to use another kind of logic especially for the Eloquent Builder that is not the same as the Query Builder.

And Why Not : a way to implement static macro an the Eloquent Builder as the same as I did it on the Query Builder.

**Comment by GrahamCampbell** [comment]
We don't process proposals to change behaviour here. Please see our contribution guide.

To be brutally honest, I wouldn't bother raising another issue, since this has already been discussed, and a decision already made.

**Comment by Swizz** [comment]
Oh my bad. My english seem poor.

This is not a proposal. This is something more like a curiosity to fix a missed comprehension about two things that seem identical in my mind but implement opposite logics.

With a bonus question about a way to solve my needs.

Sorry to make you to lose your time.
