### ISSUE TITLE
Auth::logout() throwing a timeout error

### ISSUE THREAD

**Issue by Bharat-B** [laravel/framework#13122]
So basically Auth::logout is throwing a timeout error in hasher

FatalErrorException in BcryptHasher.php line 30:
Maximum execution time of 30 seconds exceeded

public function logout(){
       Auth::logout();
}

Also Hash::check is not working properly , I've regenerated the app key and I've tried everything possible but I couldn't figure it out.

**Comment by GrahamCampbell** [comment]
Sounds like a PHP bug.

**Comment by GrahamCampbell** [comment]
What PHP version?

**Comment by Bharat-B** [comment]
5.6.20, 5.6.16
