### ISSUE TITLE
Accidentally selecting from a different ParameterBag than the one validated on

### ISSUE THREAD

**Issue by kmark** [laravel/framework#13138]
When using validation and `Illuminate\Http\Request` I've found it quite easy to accidentally grab from the wrong `ParameterBag`. There are quite a few ways to get the same data from a given Request but at least one of them has very different Laravel-undocumented parameter retrieval logic.

Take the following:
```php
Route::get('validation', function() {
    return '<form action="?foo=get" method="post">'.csrf_field().
    '<input type="text" name="foo" value="post"><input type="submit"></form>';
});

Route::post('validation', function(\Illuminate\Http\Request $request) {
    if (Validator::make($request->all(), [ 'foo' => 'in:post' ])->fails()) {
        dd("Failed");
    };
    dd([
        '->all'        => $request->all()['foo'],           // post
        '->get'        => $request->get('foo'),             // get
        '->query'      => $request->query->get('foo'),      // get
        '->request'    => $request->request->get('foo'),    // post
    ]);
});
```

`$request->all()` uses `$request->input()` which selects the `ParameterBag` to pull from by:
```php
return $this->getMethod() == 'GET' ? $this->query : $this->request;
```

We might expect `$request->get('foo')` to have similar behavior to `$request->all()['foo']` but it does not. It simply selects the bag in this order: GET, PATH, POST. So on a POST request like in the code above, `->get` can select a completely different value than `->all` assuming there is a `$_GET` entry with the same name.

This doesn't sound too terrible but when we add validation into the mix to try and ensure the user's input conforms to a known pattern or state it can be catastrophic. Or at least negate the point of validation. The validator could be selecting from a different bag than say our controller code.

In the above code it's very clear (explicit) that we are validating on `->all` so it's no stretch to assume that we should use that method to retrieve our validated input. In a controller this is not the case. If we call `$this->validate($request, ...` it's not known it uses `->all` underneath unless we check ourselves. When we abstract this further to a "[form request](https://laravel.com/docs/5.1/validation#form-request-validation)" it's even less obvious.

So if we use the normal Laravel controller validation methods and `->get` for actually retrieving what we assume to be our validated parameter we're making a potentially dangerous mistake:

```php
public function somePostMethod(MyFormRequest $request) {
    // If this code even executes we assume validation passed
    // $safe will conform to the rule for 'foo' set in our MyFormRequest
    $safe = $request->all()['foo']; // or $request->input('foo');
    // $notSafe could be anything
    $notSafe = $request->get('foo');
}
```

Perhaps we should add to the documentation somewhere that Symfony's `->get` should never be used along with Laravel validation? The same goes for explicitly selecting a named source (as `->get`'s documentation suggests) since the correct source according to Laravel depends on the request type. My apologies if this is a little long winded for the type of suggestion that it is. I had trouble fleshing out this potential issue on IRC earlier.

**Comment by vlakoff** [comment]
All of these methods make sense on their own, but you are right, using the Symfony one could cause confusion. Symfony `$request->get()` should never be used in place of Laravel `$request->input()`.

**Comment by GrahamCampbell** [comment]
So do you want to change something? Feel free to send a PR, or if you have a specific proposal, please send it to the correct place as per our contribution guidelines.

**Comment by vlakoff** [comment]
There's https://github.com/laravel/docs/pull/2269.
