### ISSUE TITLE
update model after sync relation

### ISSUE THREAD

**Issue by me2bits** [laravel/framework#13133]
Hi
example from Doc:
user has roles with id : 4,5,6

$user = App\User::find(1);
$user->roles()->detach();
$user->toArray();

so if you use $user->toArray() it return an array with all previous roles! 
this behavior is true after  $user->roles()->sync([1,2,3]) too.
Please help me to update my model after sync.
thanks

**Comment by heisian** [comment]
you probably should just do `$user->fresh()`before calling `$user->toArray();`

see: https://laravel.com/api/5.2/Illuminate/Database/Eloquent/Model.html#method_fresh

**Comment by iget-master** [comment]
Remember that `$user->fresh()` does not update the existing model. It returns a new model, so you'll need to do `$user = $user->fresh()` if you will use the $user variable again.

**Comment by heisian** [comment]
good catch!

**Comment by me2bits** [comment]
Thanks :-)
and a question:
Whats parameter of this function? ( array|string $with = array())
thanks a lot

**Comment by heisian** [comment]
from the source:
```
    /**
     * Reload a fresh model instance from the database.
     *
     * @param  array|string  $with
     * @return $this|null
     */
    public function fresh($with = [])
    {
        if (! $this->exists) {
            return;
        }
        $key = $this->getKeyName();
        return static::with($with)->where($key, $this->getKey())->first();
    }
```

It looks like you can pass a relation to reload with the model as well, so for ex. if your `User` has a child model called `Badge`, and in your user model you've specified:
```
public function badges()
{
    return $this->hasMany('App\Badge');
}
```
It *seems* like you can do `$user = $user->fresh('badges');` to load the badges along with a refreshed user model.

**Comment by me2bits** [comment]
It works! Thanks a lot :-)

**Comment by giovannibenussi** [comment]
@heisian and @iget-master are ok, you need to refresh your object and assign to itself, but very important, if you want to retrieve the roles relationship, you have to say that to the fresh method like this:

```$user = App\User::find(1);
$user->roles()->detach();
$user = $user->fresh('roles');
$user->toArray();```

The fresh method can receive an string defining a relationship to retrieve also, or an array with relationships like this:

`$user = $user->fresh('roles');`

Regards!

**Comment by heisian** [comment]
Isn't that exactly what I put in my answer.. already?

**Comment by giovannibenussi** [comment]
I didn't see that ..sorry :-P
