### ISSUE TITLE
Collection Random improvement/bug

### ISSUE THREAD

**Issue by iget-master** [laravel/framework#13135]
Hi,

There is a strange situation on Collection `random` method.

```
$collection = Model::take(10)->get(); // Collection with 10 elements

$randomCollection = $collection->random(3); // Return a collection with 3 elements, fine.

$randomCollection = $collection->random(0); // This will cause an exception as described:
// ErrorException: array_rand(): Second argument has to be between 1 and the number of elements in the array
```

**I know that's strange** calling a random method asking zero elements, but sometimes I need to run the following for some reason:

```
$randomCollection = $collection->random(mt_rand(0, 10));
```

And when the random count be zero, I'll get a unexpected error.

Since this should not brake anything, the Random method shouldn't verify that the `$ammout` parameter is zero and throw an empty collection?

**Comment by GrahamCampbell** [comment]
> mt_rand

That shouldn't be used either. The `random_int` function should be used.

**Comment by GrahamCampbell** [comment]
It is available on php 5.x due to the fact we force require the random_compat package.

**Comment by GrahamCampbell** [comment]
I don't see why this is a bug? This function requires a number equal to or greater than 1.

**Comment by GrahamCampbell** [comment]
Also, note that when you ask for 1 item, you don't get a collection out, you get the actual single item.

**Comment by iget-master** [comment]
@GrahamCampbell 

I agree that this may not be a bug, but allowing that it accept zero as parameter should help users to simplify it usage! Laravel always have a simple solution for everything, when you try to do something, it almost always works. This sittuation is broking this "logic"

It may return an null instead of a Collection, this solves too.
I know that's a rare use case, but it's possible and don't hurt to implement.

If it return a null and I need transform it into a collection, i just wrap it on a `collect()` helper call.

```
$randomCollection = collect($collection->random(mt_rand(0, 10)));
```

The problem here is that the `random` method causes a PHP error when receives zero, but 
though it make no sense, it shouldn't be a problem. If you ask me to sort zero balls in a box, i will do anything, but I will not "crash".

And about the `mt_rand` vs `random_int`, remember that it's only available on PHP > 7.
