### ISSUE TITLE
Illuminate\Foundation\Application method call isLocal() is case sensitive

### ISSUE THREAD

**Issue by ghkdev** [laravel/framework#13144]
isLocal() is case sensitive. Therefore is is important that we set our environment variables to all lowercase otherwise a call to isLocal() will give the wrong result.

APP_ENV = 'local'       isLocal() = true
APP_ENV = 'Local'      isLocal() = false
APP_ENV = 'LOCAL'   isLocal() = false

change...
```
return $this['env'] == 'local';
```
to...
```
return strtolower($this['env']) == 'local';
```
or...
```
return strtoupper($this['env']) == 'LOCAL';
```

**Comment by GrahamCampbell** [comment]
Yes, it is case sensitive.
