### ISSUE TITLE
Maximum execution time of 30 exceeded issue

### ISSUE THREAD

**Issue by shahidnajam** [laravel/framework#13140]
I know we can increase the maximum execution time but it is not just solution.
I see the log file and it happens time to time with different files. Can we determine why it happens?

    'Maximum execution time of 30 seconds exceeded' in /vendor/laravel/framework/src/Illuminate/Database/Grammar.php:58

    'Maximum execution time of 30 seconds exceeded' in /vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:1299

     'Maximum execution time of 30 seconds exceeded' in /vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/MySqlGrammar.php:139

    'Maximum execution time of 30 seconds exceeded' in /bootstrap/cache/compiled.php:0

**Comment by GrahamCampbell** [comment]
What version?

**Comment by shahidnajam** [comment]
Latest version it's Laravel 5.2

**Comment by GrahamCampbell** [comment]
Please provide the patch version, and the full php version.

**Comment by shahidnajam** [comment]
Laravel patch version: 5.2.20
Full php version: PHP 5.5.9-1ubuntu4.11 (cli) (built: Jul  2 2015 15:23:08)

**Comment by GrahamCampbell** [comment]
Upgrade to the latest 5.2.x please. Also, PHP 5.5.9 has known bugs. Try with the latest 5.5.x.

**Comment by shahidnajam** [comment]
Thank you!. I will check with these upgrade.

**Comment by GrahamCampbell** [comment]
I'd actually recommend upgrading to the latest PHP 5.6.x if you can. ;)

**Comment by shahidnajam** [comment]
We are using Ubuntu 14.04 LTS which officially supports this latest version of PHP.

**Comment by GrahamCampbell** [comment]
> We are using Ubuntu 14.04 LTS which officially supports this latest version of PHP.

No it doesn't I'm afraid. It ships with 5.5.9, and does not update it with the latest fixes.

**Comment by shehi** [comment]
@GrahamCampbell, It makes me wonder why in first place Laravel decided to have 5.5.9 as minimum supported version, when that version has potential bad bugs.

**Comment by jesseteal** [comment]
This seems to happen with php 7.0.14 and laravel 5.2.45

`Symfony\Component\Debug\Exception\FatalErrorException: Maximum execution time of 30 seconds exceeded in /var/www/api/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php:51`

**Comment by Jaspur** [comment]
Same here 

`PHP 7.1.7-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jul  7 2017 09:41:45) ( NTS )`

Latest L5.4

**Comment by Enaah** [comment]
Same with:
`PHP 7.1.10-1+ubuntu16.04.1+deb.sury.org+1` (cli) (built: Sep 29 2017 17:04:25) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.10-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies
    with blackfire v1.18.0~linux-x64-non_zts71, https://blackfire.io, by SensioLabs

And:
Laravel Framework `5.6.23`

**Comment by MicroDreamIT** [comment]
Laravel is loading like hell. 
```
[Fri Apr 19 20:36:31 2019] PHP Fatal error:  Maximum execution time of 60 seconds exceeded in C:\wamp64\www\dev\aviationjob\vendor\laravel\framework\src\Illuminate\Events\Dispatcher.php on line 329
[Fri Apr 19 20:38:44 2019] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 2097160 bytes) in C:\wamp64\www\dev\aviationjob\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasRelationships.php on line 554
[Fri Apr 19 20:39:44 2019] PHP Fatal error:  Maximum execution time of 60 seconds exceeded in C:\wamp64\www\dev\aviationjob\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php on line 78
[Fri Apr 19 20:39:53 2019] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in C:\wamp64\www\dev\aviationjob\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasRelationships.php on line 554
```

**Comment by aerilxx** [comment]
same issue with _PHP 7.3.7-2+ubuntu18.04.1, laravel framework 5.8.31_ , have already change `max_execution_time `in php.ini, didn't work.  also tried to modify _.htaccess_ file, still no luck. 
which terminated my process before it finishes, anybody suggestions? 

weird thing is each time the error appears to be at different location...

`[2019-09-13 22:10:55] local.ERROR: Maximum execution time of 30 seconds exceeded {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Maximum execution time of 30 seconds exceeded at xx/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:717)`

**Comment by Adeleye-coder** [comment]
Currently having same issue

PHP Fatal error:  Maximum execution time of 60 seconds exceeded

**Comment by Adeleye-coder** [comment]
PHP Fatal error:  Maximum execution time of 60 seconds exceeded in C:\Users\Administrator\TwilioProjects\vendor\twilio\sdk\Twilio\Http\CurlClient.php on line 41

**Comment by junandia** [comment]
Same issue
 exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Maximum execution time of 30 seconds exceeded' in /bootstrap/cache/compiled.php:11300

**Comment by Kuraj11101** [comment]
Same issue with PHP ^7.3.17 even after increasing the max_execution_time to 300 and set_time_limit at the top of my RegisterController. Have had this issue for over a week now.

**Comment by B14ckP4nd4** [comment]
the same issue is there any solution?

**Comment by driesvints** [comment]
Hey everyone,

I'm locking this issue because it either has gone off-topic, become a dumping ground for things which shouldn't be in an issue tracker or is just too old. Please try to discuss things further on one of the below channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
