### ISSUE TITLE
[5.2] Localization for custom validation are ignored

### ISSUE THREAD

**Issue by gordenfreeman1991** [laravel/framework#13157]
Hi all

I made a ServiceProvider which extend the validation with the new rule "array_max_size". Now I have the problem, that the attribute in this rule isn't translated.

**My ServiceProvider**
```php

<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Validator;

class ExtendedValidatorServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap the application services.
     *
     * @return void
     */
    public function boot()
    {
        Validator::extend('array_max_size', function ($attribute, $value, $parameters) {
            $sizeIsOk = count($value) <= $parameters[0];

            return $sizeIsOk;
        });

        Validator::replacer('array_max_size', function ($message, $attribute, $rule, $parameters) {
            return str_replace([ ':max' ], $parameters, $message);
        });
    }

    /**
     * Register the application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }
}

```

**resources/lang/de/validation.php**

```php
<?php

return [
    'array_max_size'       => ':attribute darf nicht grösser als :max sein.',

    'attributes' => [
        'email'       => 'E-Mail',
        'locations '  => 'Ortschaften',
    ],

];
```

The validation text is always "**locations** darf nicht grösser als 5 sein." but I expect "**Ortschaften** darf nicht grösser als 5 sein."

Currently this is my solution:

```php

<?php

return [
'custom' => [
        'locations' => [
            'array_max_size' => 'Es darf nicht mehr als fünf Ortschaften gewählt werden.',
        ],
    ],
	
```

Thank you and best regards.

**System information**
- Laravel 5.2.29
- PHP 7.0.0
- Apache 2.4.17
- MySQL 10.1.9
- Laragon 1.0.6

**Comment by GrahamCampbell** [comment]
Try upgrading to php 7.0.5 and laravel `5.2.*@dev`.

**Comment by gordenfreeman1991** [comment]
Hi GrahamCampbell. 

I updated to PHP 7.0.5 and Laravel 5.2.dev - the problem still exists. **But** ... oh man, I found it -> 'locations**[space]**'. Yes, the whole afternoon is gone for that.

Thanks for your help and have a nice evening

**Comment by GrahamCampbell** [comment]
Glad you got that sorted. :)
