### ISSUE TITLE
TokenMismatchException random via ajax requests on Chrome

### ISSUE THREAD

**Issue by sebastianvirlan** [laravel/framework#13151]
One from 6 - 7 ajax requests fail on my laravel project. Weird is that happen only in chrome. 

The error is 500,

```
TokenMismatchException in VerifyCsrfToken.php line 67:

```
I use ajaxSetup for headers and post data:

```
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                data: {
                    _token: $('meta[name="csrf-token"]').attr('content')
                }

            });

```

The problem is very random, I don't have a pattern. I recorded a video to show you exactly the problem, so as you can see in firefox the issue does not occur, neither on Edge. You can see the headers in video.

https://www.youtube.com/watch?v=P_M9qf3W1CI

**Comment by GrahamCampbell** [comment]
Thanks for the report, but this is yet another duplicate. Please check existing closed issues.

**Comment by sebastianvirlan** [comment]
I switched to redis but the issue still persist only in chrome.
