### ISSUE TITLE
Model fill() with multidemensional array

### ISSUE THREAD

**Issue by WindSaber** [laravel/framework#13150]
Let's imagine that I recieve a request with a structure like this:
`$_POST = array (
'person' => array (
    'id' => '1',
    'name' => 'John Smith',
    'age' => '45',
    'city' => array (
        'id' => '45',
        'name' => 'London',
        'country' => 'England',
    ),
),
);`

If decide to update my model using `$myModel->fill(Request::get('person'));` I'll get an error due to the **city** key (it's an array not a string)

I know that there are some ways to "manually" assign the city model to my person model (such as manual id assignement, associations etc.) in this example there is no problem, but what if I my model has 20 different relations...then I'll have to "manually" do this task 20 times....

Thanks in advance, Laravel is awesome!

**Comment by GrahamCampbell** [comment]
Sorry, we don't process questions here. Try the forums or something.

**Comment by WindSaber** [comment]
@GrahamCampbell  This was not a question....it was kind of request for supporting multidimensional arrays into fill method.....
