### ISSUE TITLE
[5.2] Using ->change() on a nullable column in a migration results in no schema change

### ISSUE THREAD

**Issue by iWader** [laravel/framework#13153]
When using the `->change()` functionality within a migration on an already nullable column leaves the column still nullable.

Currently using MySQL 5.7.11, PHP 7.0.3-13+deb.sury.org~trusty+1, Laravel 5.2.29

Starting schema

```
        Schema::create('tasks', function (Blueprint $table)
        {
            $table->increments('id');
            $table->nullableTimestamps();
            $table->dateTime('due_at');
        });
```

Alter schema to allow `due_at` column to be nullable. This step works fine

```
        Schema::table('tasks', function (Blueprint $table)
        {
            $table->dateTime('due_at')->nullable()->change();
        });
```

When rolling back this migration using the following the column is still left as nullable.

```
        Schema::table('tasks', function (Blueprint $table)
        {
            $table->dateTime('due_at')->change();
        });
```

**Comment by themsaid** [comment]
You'll have to do `->change()->nullable(false)`
