### ISSUE TITLE
[5.1] Way to do full join ?

### ISSUE THREAD

**Issue by prohalexey** [laravel/framework#13160]
```
SELECT 
	dl.date, 
	operators.id,
	IFNULL(SEC_TO_TIME(SUM(TIME_TO_SEC(TIMEDIFF(oop.end_time, oop.login_time)))), '00:00:00')
FROM date_list AS dl
JOIN operators   <----------------------------------THIS LINE --------------------------
LEFT JOIN operator_online_period AS oop ON date(oop.login_time) = dl.date AND oop.operator_id = operators.id

WHERE dl.date BETWEEN '2016-04-01' AND '2016-04-15'
AND operators.id IN (1, 2, 17)

GROUP BY dl.date, operators.id
ORDER BY dl.date, operators.id
```

How can I made this?
According to "compileJoins" function in Illuminate\Database\Query\Grammars\Grammar.php line 149, this can't be done. This function think what at least one of clause must exist.

I can make patch & commit. Or where is a way to do it clean(without DB::select)?

**Comment by GrahamCampbell** [comment]
Please direct questions to the forums, and proposals to our dedicated place, as per the contribution guidelines.
