### ISSUE TITLE
Defining whole namespace for facades while doing functional tests with Codeception + Laravel 5.2

### ISSUE THREAD

**Issue by williamgomes** [laravel/framework#13163]
For some reason, while i am running functional tests, i had to define whole namespace for facades. Although they are defined in 'aliases' array inside app.php properly. 
For example:
`\Session::has()`
throwing undefined method exception. If i do like:
`Illuminate\Support\Facades\Session::has()`
then it works.

Also, in my middleware, i am setting default country and currency for the application like `\Config::set('app.country','US')` 
and its working like a charm. But whenever i am trying to run functional tests, i have to set these values manually again inside `_before()` method inside my each test class. Because 
`\Config::get('app.country')` somehow returning `null`.

Is there any explanation for these things?

Thanks in advance.

**Comment by GrahamCampbell** [comment]
Sorry, we don't process questions here.
