### ISSUE TITLE
Change '/' for DIRECTORY_SEPARATOR in helpers

### ISSUE THREAD

**Issue by dangret** [laravel/framework#13168]
There's any reason for use **`/`** insteand of php's **`DIRECTORY_SEPARATOR`** in helpers functions, for example `public_path()`?
It's not a problem, but I think is better use constant created for...

**Comment by GrahamCampbell** [comment]
I guess because it's unneeded because when used in any php function calls, the separators are normalized before use.

**Comment by dangret** [comment]
Thanks for reply.
I was creating a function for standardize my own applications paths, working in windows I noticed this behavior (C:\path\to\laravel\public/uploads\). So I just suggest it, Thanks ;)

**Comment by rkgrep** [comment]
Windows handles `/` separators quite good nowadays, so it's ok.
