### ISSUE TITLE
[5.1]When you forget $ router-> model, $task->delete () failure no exception. I want to forget $ router-> model when an exception is thrown.

### ISSUE THREAD

**Issue by GameXG** [laravel/framework#13172]
https://github.com/laravel/quickstart-intermediate

laravel 5.1 

When forget "$ router-> model ( 'task', Task :: class);" when, $ task-> delete (); without any exception failed. This is not a good feeling to achieve, either succeed or fail clear that no abnormal failure is easy to write bad code.

// routes.php
``` php
route::delete('/task/{task}', 'TaskController@destroy');
```

//quickstart-intermediate\app\Providers\RouteServiceProvider.php

``` php
    public function boot(Router $router)
    {
        $router->model('task', Task::class);

        parent::boot($router);
    }
```

//quickstart-intermediate\app\Http\Controllers\TaskController.php

```php
    public function destroy(Request $request, Task $task)
    {
        $this->authorize('destroy', $task);

        $task->delete();  

        return redirect('/tasks');
    }
```

**Comment by VladyslavLifeInMobile** [comment]
If I understand you right, you are saing that if we forget to set 

``` $route->model('taks', Task::class); ```

we will get no exception?

It's realy interesting for me, cause if you send DELETE method to `/task/1` (for exaple) - you shall get exception about typing.
Something like this (written not copied from real error)

```Argument 2 passed to method destroy in TaskController should be type Task, int given```

**Comment by IonutBajescu** [comment]
Makes sense given if he didn't set `$route->model` then the container will think it's just a typehint and create a new instance of the `Task` class. 

Unfortunately I don't see how it could be easily fixed, this is the expected behavior of the DI container. Automatic resolution has its drawbacks.
