### ISSUE TITLE
Feature suggestion: strict mode on Translations

### ISSUE THREAD

**Issue by iget-esoares** [laravel/framework#13176]
Hi,

I have an simple and useful feature suggestion: a strict mode on translations.

When developing a large multi-language system, sometimes we forget to translate some strings, and the software may go to production with something like `client.name_label` on the UI.

My suggestion is to add a option on `app.php` configuration file to enable a *strict mode* on translations, where when some translation key is missing, it throw an exception.

Maybe this can go to 5.2 or either to 5.1 since it's not a breaking change, can be disabled by default.

I appreciate if we can think about it! :+1:

**Comment by GrahamCampbell** [comment]
Will go to either 5.2 or 5.3, but not to 5.1.

**Comment by GrahamCampbell** [comment]
Please review our contribution docs. We don't process proposals here.
