### ISSUE TITLE
[L5.2] Strange behavior when testing with Auth

### ISSUE THREAD

**Issue by iget-esoares** [laravel/framework#13187]
I'm writing down this test:

```
    /** @test */
    public function test_it_can_check_authorization_token()
    {
        $this->json('GET', '/auth', [], [
            'Authorization' => 'token'
        ])->seeStatusCode(200);
    }
```

This controller will make a call to `Auth::check` of my `token-auth` guard.
Internally, this guard have a method `getAuthorizationToken`

```
    /**
     * @return string|null
     */
    protected function getAuthorizationToken()
    {
        return $this->request->header('Authorization');
    }
```

The problem is: At this point, the headers are **empty!**.
If I check for headers on my controller, the `Authorization` header is present.

I didn't read the code yet, but looks like the `Auth` is being called before the test and the Request there does not have headers yet, of course.

Looks like a bug for me: Since i'm testing a HTTP call, everything on the instance that processes this http should be at default state.

**Comment by iget-esoares** [comment]
I'm using `Laravel 5.2.27` with `PHP 7.0.5-2+deb.sury.org~trusty+1`

**Comment by iget-esoares** [comment]
If necessary, my guard code is here:

https://github.com/iget-master/token-auth/blob/master/src/TokenGuard.php

**Comment by iget-esoares** [comment]
I've made this test:

Added this dump on my Guard `__construct` method:
```php dump('Guard constructed'); ```

And this before my test request:
```php dump('Before request'); ```

The result on console running phpunit is:

```php
"Guard contructed"
"Before request"
```

This means that the Auth is being instantiated only one time.
This causes another behaviors when testing with auth:

An `Auth::login()` will persist across other calls (is this desired?)

**Comment by rkgrep** [comment]
The request is being rebound sometimes.
Replace [these lines](https://github.com/iget-master/token-auth/blob/master/src/TokenAuthServiceProvider.php#L16) in your service provider.

```php
$guard = new TokenGuard(
    Auth::createUserProvider($config['provider']),
    $app['request']
);
$app->refresh('request', $guard, 'setRequest');
return $guard;
```

And you also need to implement `setRequest` method in the guard.

check [original Laravel code](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Auth/AuthManager.php#L152)

**Comment by iget-esoares** [comment]
@rkgrep @GrahamCampbell 

The issue continues even with @rkgrep suggestion and I can't understand why!

**Comment by iget-esoares** [comment]
Actually, my test is running two requests in same test, one for getting the Auth token, an another to test it, so, it's different from the test I written on first post. 

```
    /** @test */
    public function test_it_can_check_authorization_token()
    {
        $authUser = $this->getAuthUser();

        $this->json('POST', '/auth', [
            'username' => $authUser->username,
            'password' => 'foobarbiz',
        ]);

        $authorizationToken = json_decode($this->response->getContent())->token;

        $this->json('GET', '/auth', [], [
            'Authorization' => $authorizationToken
        ])->seeStatusCode(200)
        ->seeJson([
            'valid' => true
        ]);
    }
```

Noticed that the Auth is being instanciated once here. How can I solve it?

**Comment by iget-esoares** [comment]
Well, I figured out how to workaround this. I'm doing two requests to get the token, but I can grab the token manually running `Auth::login()` and acessing it by `Auth::token()` then running `Auth::logout` (that does not exists yet)
