### ISSUE TITLE
Can laravel override default connection on the fly?

### ISSUE THREAD

**Issue by martin3zra** [laravel/framework#13190]
I have the following question about Eloquent, just create a package for connections to multiple database. It works this way, create a new model inheriting the model of Eloquent and its method constructor assign the connection depending on the user's account, Laravel creates the new configuration on the fly but although created, still connected to the connection defined in settings database and me not been possible to overwrite with the new connection.

Below I show how I'm working.

New base model

use path\to\eloquent\model as IlluminateMode;
abstract class Model extends IlluminateModel
{
        public function __construct(array $attributes = array())
         {
               parent::__construct($attributes);
         }

         public function makeNewDatabaseConnection($databaseNameToConnect)
         {
                  $config = \App::make('config');
                 
                   //
                   $connections = $config->get('database.connections');
                   $defaultConnection = $connections[$config->get('database.default')];
                   $newConnection = $defaultConnection;
                   $newConnection['database']  = $databaseNameToConnect;
                   \App::make('config')->set('database.connections.' . $databaseNameToConnect, $newConnection);

         }

}

Then in the controller class i do this.
class MyController
{
public function store($data)
{
    $model = new Type(); //any model 

    $model->makeNewDatabaseConnection("databaseNameToConnect");

    $model->firstOrCreate(['Key combined primary' ]);
    $model->fill($data)->save();
}
}
but always saves the data in the default connection, as if calling the method firstOrCreate retook the default connection and not created on fly

**Comment by GrahamCampbell** [comment]
Please ask questions on the forums.
