### ISSUE TITLE
Possible issue with local key in HasManyThrough

### ISSUE THREAD

**Issue by htunlogic** [laravel/framework#13195]
Hi, 
when trying to retrieve relation:
`return $this->hasManyThrough('Yap\Cnq', 'Yap\BusCon', 'business_id', 'id', 'cnq_id');`
`
Fift, or third string key coresponds with $localKey at Illuminate\Database\Eloquent\Relations\HasManyThrough

> __construct( Builder $query, Model $farParent, Model $parent, string $firstKey, string $secondKey, string $localKey)

However, setting that key makes no difference, the key is not passed into query.

So I dug into it a bit and found this line (114) :
[HasManyThrough.php#L114](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/Relations/HasManyThrough.php#L114)

And changed it to this: 

`$query->join($this->parent->getTable(), ((!empty($this->localKey)) ? $this->parent->getTable() . '.' . $this->localKey : $this->getQualifiedParentKeyName()), '=', $foreignKey);`

Maybe I misunderstood the whole thing, but now it does what I need it to do so I thought I might share.

Cheers,
Tibor.

**Comment by MateEke** [comment]
I have the same issue:
return $this->hasManyThrough('App\Purchase', 'App\User', 'partner_id', 'user_id', 'partner_id');

`"select * from `purchases` inner join `users` on `users`.`id` = `purchases`.`user_id` where `users`.`partner_id` in (?)"
array:1 [
  0 => 1
]`

where array should contain `array:1 [
  0 => 12345
]`

**Comment by themsaid** [comment]
The 5th argument should be the column in the parent Model whose value will be used when building the constraint with the second argument.

For example:

Consider Business ->hasMany->branches->hasMany->devices

The query generated for 

```php
$this->hasManyThrough(Device::class, Branch::class, 'business_id', 'branch_id', 'customer_column')
```

is

```sql
select `devices`.*, `branches`.`business_id` from `devices` inner join `branches` on `branches`.`id` = `devices`.`branch_id` 
where `branches`.`business_id` = ?? 
```

`??` will be replaced by the value of `businesses.customer_column`

**Comment by acacha** [comment]
I proposed to add the missing info for fifth argument in laravel docs see https://github.com/laravel/docs/pull/2302 maybe it could help somebody.

**Comment by swissmant** [comment]
@themsaid I am having a very similar issue and if I look at your example above, I would expect the following output:
```
select `devices`.*, `branches`.`business_id` from `devices` inner join `branches` on `branches`.`customer_column` = `devices`.`branch_id` 
where `branches`.`business_id` = ?? 
```
Note that branches is using 'id' in your example rather than 'customer_column'.

**Comment by swissmant** [comment]
If anybody else stumbles across this issue because they are also struggling with it, be sure to set the protected property, $primaryKey, on any relevant models.
