### ISSUE TITLE
[5.2] Model::create() updates nullable timestamp

### ISSUE THREAD

**Issue by misog** [laravel/framework#13201]
Hi, nullable timestamp without useCurrent() should NOT be filled with timestamp on INSERT.
Instead, it should be NULL.
If nullable() and useCurent() are both not present, default value should be 0000-00-00 00:00:00 or ERROR in MySQL with strict mode.
```
$table->increments('id');
$table->timestamp('created_at')->useCurrent();
$table->timestamp('updated_at')->nullable();
```
in controller:
```
$item = Item::create($request->all()); // no data in request
return Item::find($item->getKey());
```
result:
```
{
  "id": 11,
  "created_at": "2016-04-18 13:46:41",
  "updated_at": "2016-04-18 13:46:41"
}
```
DB::table('items')->insert(); behaves correctly.

Laravel 5.2.29

**Comment by GrahamCampbell** [comment]
This is correct.

**Comment by GrahamCampbell** [comment]
> DB::table('items')->insert(); behaves correctly.

No, it just doesn't do anything, because it's not going through eloquent.

**Comment by GrahamCampbell** [comment]
You should get eloquent to fill out the timestamps for you, not have the db do it.

**Comment by misog** [comment]
Ok, I will insert public $timestamps = false; into the Model or extend the Model to allow timestamp configuration. Are there plans to implement timestamp configuration in future versions of Laravel?
