### ISSUE TITLE
Session fail when trans function used in middleware

### ISSUE THREAD

**Issue by muppetkermit** [laravel/framework#13211]
I had a strange reaction on middleware. I have created a middleware and assign it in web group and updated it as below (code cleared to focus problem). The problem is when i use this middleware session and csrf tokens are not created again. If i remove trans function and use a static value it works fine. I have installed a fresh laravel and got same results.

Anyone have a clue what is going on here?

Thanks and Regards...

```
public function handle($request, Closure $next)
{
    $pageTitle = trans('title.for.home');
    $response = $next($request);
    return $response; 
}
```

**Comment by muppetkermit** [comment]
up!

**Comment by GrahamCampbell** [comment]
Sorry, this is not a bug in the framework. Feel free to ask on the forums.
