### ISSUE TITLE
Route prefix (for URl prifix) should not change Route Names of resource controllers in Route::group()

### ISSUE THREAD

**Issue by john5db** [laravel/framework#13219]
when we use route prefix it should only change uri prefix, and not route name while using Route::group.

The whole idea of using named routes is to make them independent of URL's. Adding a prefix to the URL should not add it to the route name

It works fine for individual methods, but if we use it with resources it not work properly (has bug).
if we change prefix from 'admin' to 'backend' all route names also changes and we have to change route names everywhere (So what is the use of named route if you have to change it every time)
ex.
```
Route::group(['prefix'=>'admin'],function(){

    Route::get('dashboard',function(){
        echo "called dashboard";
    })->name('dashboard');

    Route::resource('users','UserController');
});
```

It creates routes 
                       
```
dashboard           
admin.users.index   
admin.users.index 
admin.users.store 
admin.users.create
admin.users.destro
admin.users.update
admin.users.show  
admin.users.edit  
```

If i change prefix to 'backend' all route names of resource controller changes 
```
dashboard          
backend.users.index
backend.users.store
backend.users.creat
backend.users.destr
backend.users.updat
backend.users.show 
backend.users.edit 
```
     
You can see it is working fine with Route::get() ; No change in route name.

we can use 'as' for route name prefix in Route::group() but it is not working for Resource controllers.      

```
Route::group(['prefix'=>'backend', 'as'=>'admin.'],function(){

    Route::get('dashboard',function(){
        echo "called dashboard";
    })->name('dashboard');

    Route::resource('users','UserController');

});
```

Routes
```
admin.dashboard          
admin.backend.users.index
admin.backend.users.store
admin.backend.users.creat
admin.backend.users.destr
admin.backend.users.updat
admin.backend.users.show 
admin.backend.users.edit 
```

This automatic prefixing of route names for resources not only makes named routes useless. It is a bug because adding both 'prefix' and 'as' to the group will result in doubling of the name prefix.   

It should create routes as
`admin.users.index`
not as
`admin.backend.users.index`

**Comment by GrahamCampbell** [comment]
Thanks, but this behaviour is correct, and has already been discussed many times.

**Comment by john5db** [comment]
Thanks for reply @GrahamCampbell . 

**But it is breaking the principle of named routes. (for resourceful Controllers)**

`The whole idea of using named routes is to make them independent of URL's. Adding a prefix to the URL should not add it to the route name`

In last example if i change route prefix (url prefix) 'backend' to 'office' and 'as'=>'admin' (route name prefix)
`Route::group(['prefix'=>'backend', 'as'=>'admin.'],function(){`
to
```
Route::group(['prefix'=>'office', 'as'=>'admin.'],function(){
    Route::get('dashboard',function(){
        echo "called dashboard";
    })->name('dashboard');

    Route::resource('users','UserController');

});
```

As we know already we have to use 'as' key to change name of route.
But it also appends url prifix to route name.

it generates route names as
```
 admin.dashboard           // here it is working fine for get() (No 'office' in route name, so i don't have to change route names everywhere)
 admin.office.users.index  // here office is url prefix : it should not append to route name
admin.office.users.store  
admin.office.users.create  
admin.office.users.destroy 
admin.office.users.update  
admin.office.users.show    
admin.office.users.edit    
```
Due to this misbehave of prefix we have to change route names from 
` admin.backend.users.index  to  admin.office.users.index `
everywhere. (so why we should use named routes? can you explain?)

I think behavior should be uniform for all route methods.
and routes should be
```
admin.dashboard            
admin.users.store  
admin.users.index  
admin.users.create 
admin.users.destroy
admin.users.update 
admin.users.show   
admin.users.edit   
```
whatever method you use.

**Comment by plopinou** [comment]
I also have the same issue with resource route names inside a group getting both prefixes from 'prefix' and 'as'.
The culprit seems to be in the getGroupResourceName function inside \Illuminate\Routing\ResourceRegistrar.php
It will always add the group prefix in the route name if there is one, but by default, every routes inside a group will also pass through the mergeGroup function in \lluminate\Routing\Router.php that will handle the 'as' hierarchy.

I also concur with john5db that this is pretty misleading, so I did a correction attempt that would look like that :
```php
// in \Illuminate\Routing\ResourceRegistrar.php
protected function getGroupResourceName($prefix, $resource, $method)
{
    $groupRouteName = $this->router->getLastGroupRouteName();
    $groupPrefix = trim(str_replace('/', '.', $this->router->getLastGroupPrefix()), '.');

    if (empty($groupRouteName) && !empty($groupPrefix)) {
        return trim("{$prefix}{$groupPrefix}.{$resource}.{$method}", '.');
    }

    return trim("{$prefix}{$resource}.{$method}", '.');
}


// in \lluminate\Routing\Router.php
public function getLastGroupRouteName()
{
    if (! empty($this->groupStack)) {
        $last = end($this->groupStack);

        return isset($last['as']) ? $last['as'] : '';
    }

    return '';
}
```
