### ISSUE TITLE
Array validation doesn't give friendly messages

### ISSUE THREAD

**Issue by w4** [laravel/framework#13220]
Messages are returned in dot notation, giving not very nice messages back to the user.

"The test.0 field is required"
"The array.test field is required"
"The test.0.text is required"

Arrays should be treated specially, possibly via another language key, such as:

    'array' => ':1 field in the :0 group'

or possibly a callback, allowing loops for varying depth inputs:

    'array' => function (array $fields) {
        echo "The {$fields[1]} field in the {$field[0]} group.";
    }

**Comment by GrahamCampbell** [comment]
Please submit proposals to the correct repo. ;)
