### ISSUE TITLE
pagination deletes parameters

### ISSUE THREAD

**Issue by jmarcher** [laravel/framework#13226]
If I use the pagination method from the Query Builder my url parameters disappear.

For example:
My url: http://localhost:8000/api/review/1?page=2&api_token=Yss1RZ9GSaddAG43yDaboKLAN3Xj56lc
But the json result is:
```
{

    "total": ​1,
    "per_page": ​7,
    "current_page": ​2,
    "last_page": ​1,
    "next_page_url": null,
    "prev_page_url": "http://localhost:8000/api/review/1?page=1",
    "from": null,
    "to": null,
    "data": [ ]

}
```

That means i loose my api_token or any other parameter

**Comment by brunogaspar** [comment]
https://laravel.com/docs/5.2/pagination#displaying-results-in-a-view

It's under the `Appending To Pagination Links` section.

> Pretty much the same for the other Laravel versions.

If you're already doing this, provide code.
