### ISSUE TITLE
App::firstOrNew([ 'a '=> 1,'b' => NULL]) return 'b' not null values too

### ISSUE THREAD

**Issue by rbkkbr** [laravel/framework#13239]
`When: App::firstOrNew([ 'a '=> 1,'b'=> NULL]) they return values of 'b' where NOT NULL TOO
Maybe its is on similiary methods like firstOrCreate, findOrNew....

SAME happens if set 'b' => 'NULL' 

the only way that result in success, is:
$row= App::where( 'a', 1)->whereNull( 'b' )->first();
if (empty($row)){
App::Create(.................;
}else{
App::Update(.................;
}

**Comment by GrahamCampbell** [comment]
I don't understand what you're asking?

**Comment by themsaid** [comment]
@rbkkbr what version of laravel are you using?

@GrahamCampbell he's saying that `where([ 'a '=> 1, 'b'=> NULL])` returns rows with `b` not equal to null.

**Comment by GrahamCampbell** [comment]
> what version of laravel are you using?

Yeh, we really need to know that please.

**Comment by themsaid** [comment]
@rbkkbr still an issue?
