### ISSUE TITLE
Laravel 5.2 - Redis - Socket.io publish doesn't work

### ISSUE THREAD

**Issue by ntweb** [laravel/framework#13235]
I've a laravel installation on a windows 10 machine. I've written this simple route

```
Route::get('/event', function(){
    $data = array("key"=>"val");
    Redis::publish('test-channel', json_encode($data));
});
```
then i've this node server.js

```
var server = require('http').Server();
var io = require('socket.io')(server);

var Redis = require('ioredis');
redis = new Redis();
redis.subscribe('test-channel');

redis.on('message', function(channel, message){
  console.log("message retriving..");
});

server.listen(6001, function(){
  console.log('listening on 6001');
});
```
I've an Ubuntu installation on a virtual machine on which i've installed Redis.

My laravel .env file is

```
BROADCAST_DRIVER=redis
REDIS_HOST=192.168.1.14 #ubuntu ip
REDIS_PASSWORD=null
REDIS_PORT=6379
```
The problem is that when the route '/event' is executed (and the node server is listening) .. I don't receive any message on the 'test-channel'

Any idea?

**Comment by GrahamCampbell** [comment]
Please ask for application specific support on the forums.

**Comment by AtomCutter** [comment]
I also face the similar problem when following Node, Redis, and Socket.io tutorial on laracast

**Comment by AtomCutter** [comment]
@ntweb, I found a solution. 
Change redis.subscribe('test-channel') to redis.subscribe('laravel_database_test-channel') in server.js file.
