### ISSUE TITLE
[5.2] query string parameters empty when route parameters is specified

### ISSUE THREAD

**Issue by Snake231088** [laravel/framework#13238]
In Laravel 5.1 i've this code:
```
Route::get('/test/{id}', function(\Illuminate\Http\Request $request, $id) {
    dump($id);
    dd($request->all());
});
```
and the result is with this url .../test/123?p=email
```
"123"
array:1 [▼
  "p" => "email"
]
```
With Laravel 5.2 with same code i obtain only:
```
"123"
[]
```

**Comment by muppetkermit** [comment]
Laravel Framework version 5.2.29

Tested your route and got result below. Seems there is no error.
"123"
array:1 [▼
  "p" => "email"
]

**Comment by GrahamCampbell** [comment]
Possible your nginx/apache configuration is bad. I've see similar issues before where the first query param name is incorrectly set.

**Comment by Snake231088** [comment]
Sorry.
My bad configuration of nginx :(

**Comment by minhnghivn** [comment]
@Snake231088 what was the problem with Nginx and how did you fix it?

**Comment by Snake231088** [comment]
Sorry! I don't remember and i changed my Web Server so i haven't old conf files!

**Comment by minhnghivn** [comment]
Thank you anyway @Snake231088 . For anyone who gets the same issue, this could be the solution: http://stackoverflow.com/questions/14854050/laravel-with-nginx-parameters-are-empty
