### ISSUE TITLE
v5.2.30 blade "stacks" is broken

### ISSUE THREAD

**Issue by tommica** [laravel/framework#13231]
Docs: https://laravel.com/docs/5.2/blade#stacks

When I have:
```
    @push('scripts')
        <script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.2/js/select2.full.min.js"></script>
    @endpush
```
and:
`@stack('scripts')`

it does not echo out what has been set in the stack

**Comment by GrahamCampbell** [comment]
Does clearing the view cache fix this|?

**Comment by tommica** [comment]
@GrahamCampbell Yes it does, didn't realize that cache:clear did not clear the view cache too - thank you very much!
