### ISSUE TITLE
Why doesn't DatabaseTransactions also reset the auto-increment?

### ISSUE THREAD

**Issue by tam5** [laravel/framework#13241]
My understanding was that the `Illuminate\Foundation\Testing\DatabaseTransactions` trait would completely reset the database as if it was untouched, but in truth the auto-increment is changed.

Truncating the table might not be the best solution in case a user is not using a clean testing database and already has an auto-increment set.

However, maybe we could temporarily store all the initial auto-increment values and then save them back afterwards?

**Comment by GrahamCampbell** [comment]
It does what it says on the tin. It makes a transaction, then rolls it back. Nothing more.

**Comment by GrahamCampbell** [comment]
If you want to actually reset the database each time, I suggest you just reset the migrations between tests.
