### ISSUE TITLE
inconsistent 'base' directory between 'artisan migrate' and 'artisan serve'

### ISSUE THREAD

**Issue by oprudkyi** [laravel/framework#13243]
'artisan migrate' and 'artisan serve' uses different root directories ('serve' chroots into public)
as result, use of relative paths in .env doesn't work 
i.e., for example 
DB_DATABASE=storage/database/local.sqlite

works for 'artisan migrate' and doesn't work for 'artisan serve'

**Comment by GrahamCampbell** [comment]
You shouldn't set relative paths.

**Comment by GrahamCampbell** [comment]
@taylorotwell should we not update the default all to wrap the env variable in a call to database_path or something?

**Comment by crynobone** [comment]
how would you declare `:memory:` then?

**Comment by GrahamCampbell** [comment]
That's a problem too. Not sure how we fix this. ;?

**Comment by oprudkyi** [comment]
probably (as from consistency point) , 'artisan migrate' should do chdir  as well
