### ISSUE TITLE
Rename key interger autoincrement column in migrations [L5.1]

### ISSUE THREAD

**Issue by giordanolima** [laravel/framework#13255]
I want rename the key that I use as pk in my table...
Something like this:
```php
Schema::create('my_table', function(Blueprint $table) {
            $table->integer('id', true, true)->primary("my_custom_name_pk");
            $table->string('field', 75);
});
```
But i have this error:
```
[Illuminate\Database\QueryException]
SQLSTATE[42000]: Syntax error or access violation: 1068 Multiple primary key defined (SQL: alter table `my_table` add primary key `my_custom_name_pk`(`id`))
[PDOException]
SQLSTATE[42000]: Syntax error or access violation: 1068 Multiple primary key defined 
````

**Comment by jvleusden** [comment]
What if you remove the PK first?

**Comment by fernandobritofl** [comment]
Why opened again?

**Comment by GrahamCampbell** [comment]
I can't tell if this is a bug. Can someone please verify this?

**Comment by srmklive** [comment]
First of all the query you are writing for modifying the table is wrong. You are actually creating a table not modifying the table.

you need to first disable the foreign key checks. If you are using MySQL.

    DB::statement('SET FOREIGN_KEY_CHECKS=0;');
    Schema::table('my_table', function(Blueprint $table) {
            $table->renameColumn("id", "my_custom_name_pk");
    });
    DB::statement('SET FOREIGN_KEY_CHECKS=1;');   

Remember you then need to update references in other migrations which have used the old primary keyf when creating foreign keys.

**Comment by srmklive** [comment]
@GrahamCampbell there is no way in laravel to enable/disable foreign key checks directly. We sometimes need to use DB facade's statement method to accomplish this.

**Comment by GrahamCampbell** [comment]
Thank you. This is not a bug, but has highlighted a few limitations. Feel free to send proposal issues to the correct place for review.

**Comment by srmklive** [comment]
@GrahamCampbell can we send them as a PR as well?
