### ISSUE TITLE
[4.2] baseUrl bug in symfony 2.5

### ISSUE THREAD

**Issue by violarium** [laravel/framework#13250]
Hello.

In symfony/http-kernel there are a bug with baseUrl: https://github.com/symfony/symfony/pull/14335 and it affects laravel/framework 4.2.

It has been fixed in 2.3, 2.6 and greater versions of Symfony, but they refused to merge this pull request in 2.5 branch because it's old.

Could we update Symfony dependencies from 2.5 to 2.6
I've checked tests - they are passing.

Thank you.

**Comment by GrahamCampbell** [comment]
Sorry, but I can only recommend you upgrade to Laravel 5.1 LTS. Symfony 2.5 and Laravel 4.2 are both EOL.
