### ISSUE TITLE
Accept cost parameter or fail BcryptHasher 

### ISSUE THREAD

**Issue by misog** [laravel/framework#13251]
In PHP, password_hash() and crypt() accept **cost** parameter.

In Laravel, I did

`$hash = bcrypt($password, ['cost' => 11]);`

$hash is $2y$10$... so the cost is 10.

Security related functions should be robust, please throw an exception if **cost** is passed or accept **cost** parameter in addiction to **rounds** parameter, in BcryptHasher:
```
    public function make($value, array $options = [])
    {
        $cost = isset($options['rounds']) ? $options['rounds'] : $this->rounds;

        $hash = password_hash($value, PASSWORD_BCRYPT, ['cost' => $cost]);

        if ($hash === false) {
            throw new RuntimeException('Bcrypt hashing not supported.');
        }

        return $hash;
    }
```

Anyway, this should throw an exception if any unknown parameter is passed. Typo example:

`bcrypt($password, ['round'=>11]); `

Anyway2, the meaning rounds = 10 in context of bcrypt implies pretty low security, as bcrypt in practice does hundreds or thousands of rounds (2^cost where cost is between 4 and 31, but cost default is in this year 10, so 1024 rounds).

Anyway3, **rounds** is specification (bad) and **cost** is abstraction (good).

Ideally, accept **cost** parameter and deprecate the **rounds** parameter, later remove the **rounds** parameter and always throw an exception when unknown parameter is passed.

**Comment by vlakoff** [comment]
`rounds` is different from the PHP option name, and sounds like it's linear, whereas this `cost` option is in fact exponential or so.

On the other hand, changing the option name would be a breaking change, and supporting multiple names for the same option doesn't seem to be a good idea.

**Comment by vlakoff** [comment]
I'd tend to agree with this proposal:
> accept **cost** parameter and deprecate the **rounds** parameter, later remove the **rounds** parameter

<br>Unsure about this part:
> throw an exception when unknown parameter is passed

It would be user-friendly, but complicating the codebase

**Comment by misog** [comment]
Yes, the `rounds` should be definitely changed, because people think this is the `iterations` of bcrypt algo.
But the bcrypt algo is iterated from 16 up to 2147483648 times (2^cost where cost is in 4..31).
