### ISSUE TITLE
[5.1] Storage has(null) returns true

### ISSUE THREAD

**Issue by muihlinn** [laravel/framework#13259]
If have a valid filesystem and if `has()` receives a null value as argument it returns true. It seems to take the root of it as result.

`Storage::disk('mydisk')->has($file)` returns `true` if `$file == null`

**Comment by GrahamCampbell** [comment]
Closing since this issue belongs to flysystem.

**Comment by frankdejonge** [comment]
Upstream notification: This is fixed and tagged as `1.0.21`.

**Comment by GrahamCampbell** [comment]
Thanks @frankdejonge. ;)
