### ISSUE TITLE
Randomly no errors and old input in session after validation fails

### ISSUE THREAD

**Issue by matiazar** [laravel/framework#13261]
Hi all.

I have a form, with a lot of fields.
Im testing validation with only 2 of them, name and code field.

when I access the form view I press enter, and randomly, sometimes, it shows me the validation error and sometimes not.
Sometimes it save my old values, anda sometimes it shows the empty form.

My Laravel version is 5.1
My enviroment Windows 10 with XAMPP

after hours of testing I have found that if I use "php artisan serve" it works fine. But with my apache is randomly.

Thanks in advance for your help !

**Comment by matiazar** [comment]
Now I have another problem with **php artisan serve**
I get always this error !!
TokenMismatchException in VerifyCsrfToken.php line 53

**Comment by GrahamCampbell** [comment]
Thanks, but this is a duplicate, and know race condition.

**Comment by matiazar** [comment]
Can you help me linking any answer? 
I cant find it on this issues

thanks
