### ISSUE TITLE
Pjax request doesn't set session's previous URL

### ISSUE THREAD

**Issue by joelcuevas** [laravel/framework#13263]
When working with pjax, `url()->previous()`, `back()` —and other methods relying on the session's previous URL— points to the last page requested without pjax, ignoring all the pjax requests made subsequently.

This is, basically, because pjax **is an ajax request**, and in StartSession middleware, all the ajax requests are excluded from the session's previous URL storage.

In StartSession middleware:

```
protected function storeCurrentUrl(Request $request, $session)
{
    if ($request->method() === 'GET' && $request->route() && ! $request->ajax()) {
        $session->setPreviousUrl($request->fullUrl());
    }
}
```

I'm not sure if this would be a good solution or could cause unintended side effects, but maybe checking if `(! $request->ajax() || $request->pjax())` solves the issue.

**Comment by srmklive** [comment]
you can filter such requests through a middleware of your own. This is not a bug in my opinion.

**Comment by joelcuevas** [comment]
I neither see this as a bug, but as Laravel includes some basic support for dealing with pjax requests, maybe this is simply an ignored scenario. I wrote this in case of it were the case.

@srmklive, as you addecuatly pointed, I extended the StartSession middleware and solved my problem, but if this were an issue that Larevel wish to address, I gladly could make a PR.

@GrahamCampbell, it is?

**Comment by themsaid** [comment]
Closing since there seem to be no interest in making any changes.
