### ISSUE TITLE
Multiple environments require multiple .env files (performance and other issues)

### ISSUE THREAD

**Issue by ThomasTesla** [laravel/framework#13262]
In Laravel 4.x it was possible to have a development and production environment with one configuration file. The framework would detect automatically what should be used according to the host.

With Laravel 5.x it seems I have to take the following approach:

- On my local machine a .env file in the root directory with "APP_ENV=local" and other config stuff to run locally.

- On my server the same thing with "APP_ENV=production" and the related settings.

So if I deploy my site, I have to watch that I don't overwrite the .env file on the server with my local version.

Is this correct so far or am I missing something here?

The main goal is to keep sensitive data out of version control and have everything in one place.

Following points and questions about this approach are unclear:

- The creator of the .env package recommends to NOT use it in production mode (source: https://github.com/vlucas/phpdotenv). The solution in Laravel for this issue would be to hard code every setting across the framework and to make sure that the .env file is not deployed to the server (could be a huge security hole).

- If the solution in the point above is used, how would you keep the sensitive data out of version control?

- Let's say two different .env files are used (for development and one for the server in production mode), wouldn't that be a performance issue in production since each setting is being called over and over again from the .env file?

This seems like a step back from the 4.x approach where I could have everything configured and done in one place, no need to have two different files with the same name and watch that I don't mix them up or something. And loading one array in .php is also a lot faster than calling one file multiple times.

**Comment by philbates35** [comment]
You should just ensure .env is ignored from your repo and then create the .env file on the server once as part of your initial deployment. I'm not sure how you could end up overriding the production .env with your local .env (I can only imagine that could happen if you're ftping your whole local directory to the production server. But you're not doing that, right? ;)).

The .env file does have to be used in production. You could set the relevant env vars in the virtual host for example, but they aren't loaded when running artisan commands and so everything breaks.

Btw @GrahamCampbell will likely be here in a minute to kindly tell you should be asking questions like this on the forums or slack, for future reference.

**Comment by GrahamCampbell** [comment]
> Btw @GrahamCampbell will likely be here in a minute to kindly tell you should be asking questions like this on the forums or slack, for future reference.

Yes, please do. Due to very high volume, we can only process isolated bug reports here, and nothing else.
