### ISSUE TITLE
Error with Lumen when sending http request

### ISSUE THREAD

**Issue by ShahrokhNiakan** [laravel/framework#13275]
NotFoundHttpException in RoutesRequests.php line 443:

in RoutesRequests.php line 443 at Application->handleDispatcherResponse(array('0')) in RoutesRequests.php line 381
at Application->Laravel\Lumen\Concerns{closure}() in RoutesRequests.php line 629
at Application->sendThroughPipeline(array(), object(Closure)) in RoutesRequests.php line 382
at Application->dispatch(object(Request)) in RoutesRequests.php line 327
at Application->run(object(Request)) in index.php line 28

I added $app->run($app['request']); in bootstrap/app.php

**Comment by anbu369** [comment]
@ShahrokhNiakan Hey! remember how you fixed this? I looked in to every solution, and nothing works. I added $app->run($app['request']); too but still no luck

**Comment by techlinesolutions** [comment]
Hi,
Please help me, whenever i try to access my url for a post in Lumen through the browser i get the below error

Whoops, looks like something went wrong.
 MethodNotAllowedHttpException

in RoutesRequests.php 
at Application->handleDispatcherResponse(array(2, array('POST')))
in RoutesRequests.php 
see code from web.php below

 $router->post('gen','VoucherController@generateVoucherCode');
see code from generateVoucherCode

class VoucherController extends Controller
{


    public function generateVoucherCode(Request $request){
// generate 16 digit random no.
    $random1 = rand(1111, 9999);
    $random2 = rand(1111, 9999);
    $random3 = rand(1111, 9999);
    $random4 = rand(1111, 9999);
    $voucher_code = ($random1."-".$random2."-".$random3."-".$random4);

    $today = date("Y-m-d");
    $use_once = "yes";
    $request->request->add( ['voucher_code' => $voucher_code,
        'use_once' => $use_once,
        'date_used' => $today,
        'date_created' => $today]);

        Voucher_code::create($request->all());

    return response()->json($voucher_code);
    }

Can you pls tell me what I am doing wrongly
