### ISSUE TITLE
Php 7

### ISSUE THREAD

**Issue by aezazi** [laravel/framework#13278]
I Upgrade my Ubuntu Server to 16.04 and Php 7

Composer not work in this php version for get laravel git package.

can i work with laravel in this php version?

**Comment by GrahamCampbell** [comment]
Yes, Laravel will work on Ubuntu 16.04.

**Comment by pavankumarkatakam** [comment]
I have also updated the my ubuntu to 16.04 and php to 7.0, 
all is working fine but some misbehavoiur by `json_encode` , t is working well when given the simple array but if there is any collection it then `json_encode` is failing and returning `false`.

**Comment by GrahamCampbell** [comment]
Sounds like a bug in ubuntu's version of PHP. Please report this to them.
