### ISSUE TITLE
Refactor / redesign Model class

### ISSUE THREAD

**Issue by misog** [laravel/framework#13280]
The first issue is, the Model class uses direct access to protected $attributes array in **public** methods. The second, greater problem is, there is asymmetry in data access in the class:

In public function, //A uses **direct** access, //B uses public setter.
```
    public function replicate(array $except = null)
    {
        $except = $except ?: [
            $this->getKeyName(),
            $this->getCreatedAtColumn(),
            $this->getUpdatedAtColumn(),
        ];

        $attributes = Arr::except($this->attributes, $except); //A

        $instance = new static;

        $instance->setRawAttributes($attributes); //B

        return $instance->setRelations($this->relations);
    }
```
Why is this a problem?

Direct access to protected fields in public methods means that if a child class wants to add some low level functionality, it has to override the big public methods.

The asymmetry is even worse - new non-idempotent functionality in child class is not possible without overriding the high-level and they create great confusion and dangerous edge cases.

Try to think about implementing SecureModel which extends Model, accepts symmetric encryption key in constructor / setter method and does not allow to store unencrypted data (**important!**) and does not allow to retrieve encrypted data.

It is not enough to override getAttribute() and setAttribute() as there are other **public** methods which access $attributes directly, or without use of getAttribute()/setAttribute().

Encryption and decryption are not idempotent operations, the asymmetry of some methods requires to override even them.

**Comment by GrahamCampbell** [comment]
Thanks. Feel free to discuss with internals on github or slack.
