### ISSUE TITLE
Database Session Driver working NOT fine, please check it again!

### ISSUE THREAD

**Issue by duruitang** [laravel/framework#13297]
.env SESSION_DRIVER=database : csrf_token()** always** changes  when refresh my browser and I got TokenMismatchException in VerifyCsrfToken.php line 47

**Once** I set .env SESSION_DRIVER=file, everything OK and csrf_token() **nolonger** changes when refresh my browser!

One more thing, This happens When I use MySql as my SESSION_DRIVER . 

Thank You !

**Comment by GrahamCampbell** [comment]
What version>

**Comment by duruitang** [comment]
Laravel 5.2.29, Please check it ,Thank You !

**Comment by platedodev** [comment]
When using the database session driver, you will need to setup a table to contain the session items.
`Schema::create('sessions', function ($table) {
    $table->string('id')->unique();
    $table->integer('user_id')->nullable();
    $table->string('ip_address', 45)->nullable();
    $table->text('user_agent')->nullable();
    $table->text('payload');
    $table->integer('last_activity');
});`
You may use the session:table Artisan command to generate this migration for you!
```
php artisan session:table

composer dump-autoload

php artisan migrate
```

**Comment by duruitang** [comment]
I am sure that all my configs are OK！And everytime I refresh my browser ，a new session record could be seen on phpmyadmin。
I think the database driver has some reading DB or validate problems。
In fact ，I use MariaDB 10.1.13 ，charset=utf8mb4 connection = utf8mb4 & sessions id varchar（191）



------------------------------------------------------------------发件人：Martin Dos Santos<notifications@github.com>日　期：2016年04月25日 01:00:49收件人：laravel/framework<framework@noreply.github.com>抄　送：duruitang<ruitang.du@aliyun.com>; Author<author@noreply.github.com>主　题：Re: [laravel/framework] Database Session Driver working NOT fine, please check it again! (#13297)When using the database session driver, you will need to setup a table to contain the session items.

Schema::create('sessions', function ($table) {

    $table->string('id')->unique();

    $table->integer('user_id')->nullable();

    $table->string('ip_address', 45)->nullable();

    $table->text('user_agent')->nullable();

    $table->text('payload');

    $table->integer('last_activity');

});

You may use the session:table Artisan command to generate this migration for you!

php artisan session:table

composer dump-autoload

php artisan migrate

**Comment by duruitang** [comment]
And PHP version is 7.0.5 . 
https://www.apachefriends.org/index.html

**Comment by srmklive** [comment]
i myself have used DB session driver on an application with MariaDB 10.1 & php version 7.0.5 on windows. Never faced the issue you are facing. There may be an issue with your configuration. Have you tried changing the encoding of database tables?

**Comment by duruitang** [comment]
OK, may be I was wrong at some where... Thank you very match ! You guys doing very great job~
