### ISSUE TITLE
when php artisan migrate throws error

### ISSUE THREAD

**Issue by prog-rajkamal** [laravel/framework#13295]
so, it happened like this:

1. I created few migrations 
2. ran `php artisan migrate` 
3. `php artisan migrate:rollback` -> threw an error after deleting 2 tables.

so now, `php artisan migrate` believes that my 2 tables were not deleted according to `migrations` table.

I see manually changing entries in database as only option.

so, I delete other tables from recent migration and proceed to delete migration log from `migration` table. as it happens to be ---I am using postgres with pgAdmin (on windows),--- its gui does not allow editing `migration` table because it lacks a primary key. so I have to use sql. I am like *screw it*, I will delete the database and raise an issue on github. 

My issue is if error occurs while `php artisan migrate`ing, then restoring db to a valid state **manually** is a big pain. what is the recommended way to handle it?

PS: I am using laravel 5.1

**Comment by leonardoalifraco** [comment]
The only option available is carefully creating the proper down method for every migration taking into account everything that may break your schema.

**Comment by prog-rajkamal** [comment]
the error came while it was running down method, but it is also possible during up method as well.

The best thing would be, in my opininon, to run migrations in a transaction and roll back in case of exceptions. I don't think mysql supports it. but for other dbs, this is an option. only I don't how to do this with laravel migrations?

**Comment by GrahamCampbell** [comment]
Please ask questions on the forums.
