### ISSUE TITLE
iconv_strpos(): Detected an illegal character in input string

### ISSUE THREAD

**Issue by vesper8** [laravel/framework#13296]
You're probably already aware of this. But I just encountered this error on a Laravel Forge server that's running the latest php (Ubuntu 14.04.4 LTS)

Just out of the blue.. site was working fine few days ago then bam today multiple laravel sites are giving me the error iconv_strpos(): Detected an illegal character in input string

After a bit of searching I found this very recent (few days ago) SO post that offered a solution which was to remove base64 at the beginning of the app_key and then trim the rest down to 32 characters.

No idea why this happened or it's caused by Laravel or what.. but if something can be done so this doesn't cause a big ole mess that would be good...

http://stackoverflow.com/questions/36759564/laravel-php7-debian-7-5-site-deployment-has-illegal-chareters-dont-know-why

**Comment by bobbybouwmann** [comment]
I currently have the same issue was well. It seems to be a Mbstring issue
```
ErrorException in /home/vagrant/Code/humancando/vendor/symfony/polyfill-mbstring/Mbstring.php line 351: iconv_strpos(): Detected an illegal character in input string
```

**Comment by GrahamCampbell** [comment]
Thank you. Please report this to them. In the meanwhile, you can fix this by installing the mb_string extension.
