### ISSUE TITLE
Laravel auth problem.

### ISSUE THREAD

**Issue by Xeroner** [laravel/framework#13319]
I have a big problem, im loging users using laravel auth

    \Auth::login($user, true, 120);

And its logging me out radomlly, i don't know why.
Sometimes is 1 minute and sometimes is 30 minutes, meaby problem is with using Auth::check() to many times per x time ?
Any ida ?

My sessions conf :

    `'lifetime' => 1440,

    'expire_on_close' => false,`

Versions:

     `"require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "GuzzleHttp/guzzle": "^6.1",
        "andywer/js-localization": "dev-laravel-5",
        "invisnik/laravel-steam-auth": "2.*"
    },`

Im using nginx

**Comment by GrahamCampbell** [comment]
Please see the other issues.

**Comment by Xeroner** [comment]
I was looking but they not helping me....

**Comment by GrahamCampbell** [comment]
Try asking on the forums then please. Our issues are for isolated framework bugs only please.
