### ISSUE TITLE
Validation - Errors always Empty

### ISSUE THREAD

**Issue by maratkh** [laravel/framework#13313]
In the View the variable $errors always empty. 
Think becouse 

namespace Illuminate\Foundation\Validation;

protected function throwValidationException(Request $request, $validator)
    {
        throw new  **ValidationException** ($validator, $this->buildFailedValidationResponse(
            $request, $this->formatValidationErrors($validator)
        ));
    }

the ValidationException is Depricated

<?php

namespace Illuminate\Foundation\Validation;

use Illuminate\Validation\ValidationException as BaseException;

/**
 * @deprecated since 5.2.7. Use Illuminate\Validation\ValidationException.
 */
class ValidationException extends BaseException
{
}

Laravel 5.2.* updated

**Comment by Polinicles** [comment]
Same happens to me. The validation rules work but when I get a validation error, the $errors variable of the view it's empty. 

Obv. I have all the routes applying the 'web' middleware.

**Comment by Polinicles** [comment]
Found the response for my case, since the 5.2.27 version, the web middleware it's applied by default to all the routes, so if you apply it again in the routes file, you'll get this damn bug.

**Comment by GrahamCampbell** [comment]
Not a bug I'm afraid. It's a user error.

**Comment by maratkh** [comment]
Yes, if in the route file you use the Middleware=> web then you'll get this bug...

**Comment by GrahamCampbell** [comment]
You can't use that if you've already used it.

**Comment by erlangparasu** [comment]
Any updates?

**Comment by erlangparasu** [comment]
related issue:
- https://laravel.io/forum/03-28-2016-errors-variable-empty-after-failed-validation
- https://laracasts.com/discuss/channels/laravel/errors-is-always-empty-on-login-screen
- https://laravel.io/forum/why-laravel-validation-dont-displaying-errors

**Comment by erlangparasu** [comment]
Related github issues about Validation $errors view empty / not showing:
- https://github.com/laravel/framework/issues/40773
- https://github.com/laravel/framework/issues/31491
- https://github.com/laravel/framework/issues/29764
- https://github.com/laravel/framework/issues/27729
- https://github.com/laravel/framework/issues/27032
- https://github.com/laravel/framework/issues/27032
- https://github.com/laravel/framework/issues/26367
- https://github.com/laravel/framework/issues/26172
- https://github.com/laravel/framework/issues/14083
