### ISSUE TITLE
Laravel 5.2.31 PostgreSQL error

### ISSUE THREAD

**Issue by mirzap** [laravel/framework#13336]
New version just broke my app. I'm getting this error after runing php artisan migrate:

```
  [Illuminate\Database\QueryException]                                                                                                                                                                                             
  SQLSTATE[08P01]: \Unknown error>>: 7 ERROR:  bind message supplies 1 parameters, but prepared statement "pdo_stmt_00000003" requires 2 (SQL: select * from information_schema.tables where table_schema = migrations and table   
  _name = ?)
```

and

```
 [PDOException]                                                                                                                          
  SQLSTATE[08P01]: \Unknown error>>: 7 ERROR:  bind message supplies 1 parameters, but prepared statement "pdo_stmt_00000003" requires 2 
```

I menaged to trace this, and I think this commit broke it:

https://github.com/laravel/framework/commit/0a26661949db13fb3f3c878177f77d8d3a8fa987#diff-576445757ef0e9e3c1f6d8cf56c2767cL31

**Comment by GrahamCampbell** [comment]
@themsaid

**Comment by themsaid** [comment]
Strange, here's my query for `Schema::connection('pgsql')->hasTable('some_table');`

<img width="715" alt="screen shot 2016-04-27 at 4 26 31 pm" src="https://cloud.githubusercontent.com/assets/4332182/14855537/abcf4ba6-0c94-11e6-9a28-70942d0a31d1.png">

**Comment by mirzap** [comment]
I'm getting this for `Schema::hasTable('migrations');` : 

![pg_error](https://cloud.githubusercontent.com/assets/991967/14856492/87dc71d4-0c98-11e6-8c84-27bf6062e0d2.png)

However, if I change this line in your commit:

```
return 'select * from information_schema.tables where table_schema = ? and table_name = ?';
```

to this:
```
return 'select * from information_schema.tables where table_name = ?';
```
everything works fine. I've already tried removing vendor directory and installing deps again, and I'm getting the same result.

**Comment by mirzap** [comment]
I've solved it! 
I've been using the wrong Builder class (since you created a new one for PG connection):

https://github.com/Bosnadev/Database/commit/3f6c4ee5bfe3f1af39f97d7bf7a9f187e693b2c2

**Comment by mgldvlpr** [comment]
Dear mirzap,

I have a same problem but i couldn't fix it. could you help me on it?

  [Illuminate\Database\QueryException]                                                                                                                                                                                             
  SQLSTATE[08P01]: \Unknown error>>: 7 ERROR:  bind message supplies 1 parameters, but prepared statement "pdo_stmt_00000003" requires 2 (SQL: select * from information_schema.tables where table_schema = migrations and table   
  _name = ?)
