### ISSUE TITLE
Laravel schedule switch 'user' combined with 'withoutOverlapping' not working

### ISSUE THREAD

**Issue by pulkitjalan** [laravel/framework#13332]
Tested this on Laravel 5.1 and Lumen 5.1

My command is set to run every minute, change user and without overlapping:

```php
$schedule->command('command')
    ->user('vagrant')
    ->withoutOverlapping();
```

I'm getting the following error when running it as root:

```
$ php artisan schedule:run
Running scheduled command: sudo -u vagrant (touch /web/storage/framework/schedule-2d4441595514912ce98d904112cb2c13; '/usr/bin/php5' 'artisan' command; rm /web/storage/framework/schedule-2d4441595514912ce98d904112cb2c13) > '/dev/null' 2>&1 &
sh: 1: Syntax error: "(" unexpected
```

Thanks in advance.

**Comment by pulkitjalan** [comment]
Running the command manually does not produce any errors.

```
$ php artisan command
test
```

Wonder if this has ever worked?

Running `sudo -u vagrant (ls)` in the terminal also fails

```
$ sudo -u vagrant (ls)
bash: syntax error near unexpected token `('
```

**Comment by pulkitjalan** [comment]
Above PR does not fix the issue, any other suggestions?

**Comment by syaiful6** [comment]
it shoud ```sudo -u vagrant ls``` no need '(' character. am i right? i dont know for window

**Comment by pulkitjalan** [comment]
@syaiful6 Yea for a single command its fine. `sudo -u vagrant (ls)` was just an example i used, Laravel never runs that command, it does however run `sudo -u vagrant (touch /web/storage/framework/schedule-2d4441595514912ce98d904112cb2c13; '/usr/bin/php5' 'artisan' command; rm /web/storage/framework/schedule-2d4441595514912ce98d904112cb2c13)` which is failing.

**Comment by syaiful6** [comment]
ouh, so Laravel want it to kick on subshell, therefor it should also inside parenthesis:

```(sudo -u nobody touch /web/storage/framework/schedule-2d4441595514912ce98d904112cb2c13; '/usr/bin/php5' 'artisan' command; rm /web/storage/framework/schedule-2d4441595514912ce98d904112cb2c13)```

so the switch user command also shoud inside the parenthesis.

**Comment by syaiful6** [comment]
the parenthesis used to execute command on subshell, not to run multiple command at once. if it just want run multiple command then use semicolons  `;`.

**Comment by pulkitjalan** [comment]
But wouldn't the above only run the `touch` command as user `nobody` and the other commands after the `;` as the user running the command (in my case `root`)?

**Comment by syaiful6** [comment]
ah, you are right! maybe the correct one is:
```
sudo -u nobody -- sh -c '(touch /web/storage/framework/schedule-2d4441595514912ce98d904112cb2c13; '/usr/bin/php5' 'artisan' command; rm /web/storage/framework/schedule-2d4441595514912ce98d904112cb2c13)'
```
i try this one my shell
```
sudo -u nobody -- sh -c '(whoami; whoami)'
```
it print nobody two times.

**Comment by pulkitjalan** [comment]
@syaiful6 thanks, ill test it out and make a PR.
