### ISSUE TITLE
[5.2.31] [Illuminate\Contracts\Container\BindingResolutionException] issue

### ISSUE THREAD

**Issue by ConquestMedia** [laravel/framework#13347]
Just ran `composer update`

result was 

Updating dependencies (including require-dev)
  - Removing laravel/framework (v5.2.30)
  - Installing laravel/framework (v5.2.31)
    Downloading: 100%

  - Removing intervention/image (2.3.6)
  - Installing intervention/image (2.3.7)
    Downloading: 100%

Now getting 

>  [Illuminate\Contracts\Container\BindingResolutionException]
>   Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\Support\Manager

on even `artisan list`

**Comment by GrahamCampbell** [comment]
Sounds like you're trying to inject a manager class. You won't be able to do that.
