### ISSUE TITLE
--force option for queue:work --daemon and queue:listen

### ISSUE THREAD

**Issue by halaei** [laravel/framework#13369]
`--force` option does not work for daemon workers and does not exists for `queue:listen` command.

**Comment by halaei** [comment]
Should this option exist at all?

**Comment by GrahamCampbell** [comment]
What would you expect it to do please?

**Comment by halaei** [comment]
Suppose you do `php artisan down` while there are jobs in the queue, and a worker command `php artisan queue:work --daemon --force` is running. According to `php artisan queue:work --help`, the worker should continue processing jobs, but it won't:

>       --force            Force the worker to run even in maintenance mode

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell. Looks like a bug, or oversight here.
