### ISSUE TITLE
Laravel 5.2 Job Queue not processing handle() method

### ISSUE THREAD

**Issue by alizamani** [laravel/framework#13362]
Hi ,

I am trying to make a queued command that collects a listing of data and saving to database. The command has two methods - the constructor and handle().

After the constructor does its thing, the handle() method should be called. In turn it should trigger makeRequest()  which, when complete, should save data to database. I have found that if I place makeRequest() inside the handle() method, it is never called. If I place handle() in the constructor, it called fine but like sync driver (synchronously) .

One other thing to note, it works fine when I set `QUEUE_DRIVER=sync` in `.env` but with `QUEUE_DRIVER=database` does't not work .

here is my code :

```
`class SearchClansFromApi extends Job implements ShouldQueue
{
    use InteractsWithQueue, SerializesModels;
```

    protected $response;
    protected $request;
    protected $requestParams;

    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct($apiResponse, $requestParams)
    {
        $this->response = $apiResponse;
        $this->request = new \Illuminate\Http\Request();
        $this->requestParams = $requestParams;

        Log::info('in construction');
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        //this method never called 
        Log::useFiles(storage_path().'/laravel.log');
        makeRequest();
}`

**Comment by GrahamCampbell** [comment]
> but with QUEUE_DRIVER=database does't not work .

I'm not exactly sure what you mean? You have setup a queue job runner?

**Comment by GrahamCampbell** [comment]
> $this->request = new \Illuminate\Http\Request();

You shouldn't put that in the constructor. Serializing that is probably a bad idea.

**Comment by alizamani** [comment]
Thanks @GrahamCampbell  . When i change `queue_driver` to `database` , then `handle()` method inside Job **never called** and **only `__construct()` method called** in Job . 

When i change `queue_driver` to `sync` ,then both `__construct()` and `handle()` methods called and everything work correctly.

**Comment by GrahamCampbell** [comment]
That is correct. We call only construct, then queue it. You need to process the job off the queue.

**Comment by GrahamCampbell** [comment]
https://laravel.com/docs/5.2/queues#running-the-queue-listener

**Comment by alizamani** [comment]
@GrahamCampbell Thank you, i used supervisor for this and work perfect ! 
also i removed below code from constructor 

> $this->request = new \Illuminate\Http\Request();

Thank you for time!

**Comment by yanlinaung30** [comment]
@alizamani I used supervisor too. But handle method is not called. I use supervisor with `php artisan queue:work --daemon`. handle method is called every time. I called job with `Job::dispatch($model)`. Do you have any idea for it?

**Comment by yanlinaung30** [comment]
@GrahamCampbell If I called Command `php artisan command:foo` from construct, it takes too long to get response from browser. Am I doing something wrong? I use database as queue driver.

**Comment by mirko77** [comment]
Same problem here, 

`php artisan queue:work` just increments the "attemps" column, but the handle method is never called

Laravel 5.4

**Comment by hrabbit** [comment]
A quick thought, and this may or may not work, but the fact that you are using supervisor means that your workers are running in ram the whole time. If you make a change anywhere that your workers need to acess, you will be required to either restart your workers from supervisor, or use 

```./artisan queue:restart```

(make sure your supervisor command is set to handle his properly as it actually tells the workers to quite/restart and doing it too often will cause supervisor to stop trying (or.. set startretries=99999999 :smile:)

**Comment by badrizahra** [comment]
> supervisor

i have same problem.
how can i install supervisor in windows??

**Comment by KuNman** [comment]
I have exactly same issue with `redis` driver.
When I use driver `sync` method `handle()` is executed, when I use `redis` I must call it myself from `constructor`...

**Comment by JorgeAiresJr** [comment]
Using
'default' => env('QUEUE_DRIVER', 'database'), 
instead of  
'default' => env('QUEUE_CONNECTION', 'database'),
on queue.php  worked for me!

**Comment by rizkyarlin** [comment]
I managed to solve by using `block_for`

Quoted from the docs [Laravel Queue](https://laravel.com/docs/6.x/queues)

> When using the Redis queue, you may use the block_for configuration option to specify how long the driver should wait for a job to become available before iterating through the worker loop and re-polling the Redis database.
> 
> Adjusting this value based on your queue load can be more efficient than continually polling the Redis database for new jobs. For instance, you may set the value to 5 to indicate that the driver should block for five seconds while waiting for a job to become available:

```
'redis' => [
    'driver' => 'redis',
    'connection' => 'default',
    'queue' => 'default',
    'retry_after' => 90,
    'block_for' => 5,
],
```

I am using Laravel 6, but it is available since 5.5

**Comment by symbol3382** [comment]
> Using
> 'default' => env('QUEUE_DRIVER', 'database'),
> instead of
> 'default' => env('QUEUE_CONNECTION', 'database'),
> on queue.php worked for me!

Best solution

**Comment by somayajulu** [comment]
Changing this option in queue.php worked for me in laravel 7.x
'default' => env('QUEUE_DRIVER', 'database'),
instead of
'default' => env('QUEUE_CONNECTION', 'database'),

**Comment by Dilshan97** [comment]
> Using
> 'default' => env('QUEUE_DRIVER', 'database'),
> instead of
> 'default' => env('QUEUE_CONNECTION', 'database'),
> on queue.php worked for me!

It's work for me. thanks
