### ISSUE TITLE
Filesystem URL creation for Local driver has a hardcoded path prefix

### ISSUE THREAD

**Issue by briedis** [laravel/framework#13364]
Fetching URLs for local filesystem is conflicting with filesystem configuration option. I've specified where I want my files to be stored (public directory)

```
'root' => public_path('my-storage-directory'),
```

Code assuming that we always store in `storage` directory, no options to override it:

```
} elseif ($adapter instanceof LocalAdapter) {
            return '/storage/'.$path;
} else {
```

[(Source)](https://github.com/laravel/framework/blob/7642f12d7199456e5bf634a3e449023e3ee0160d/src/Illuminate/Filesystem/FilesystemAdapter.php#L240)

Perhaps it would be better if we could specify the prefix (not the full path) in config array, like, in a publicRoot field, or something like that.

**Comment by j3j5** [comment]
This hardcoded path on the FileSystemAdapter actually returns a wrong value for the default config (default is `storage_path('app')` and `Storage::url()` would omit the `app`).

Now in 5.3 there's a _public_ driver and the code is even uglier (looking for _public_ and replacing the occurence) [source](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Filesystem/FilesystemAdapter.php#L284). 

I am not sure what the behaviour should be for `url()` but right now it just returns wrong paths for the local driver with the default settings.

**Comment by thomassjogren** [comment]
Just ran into this problem myself testing generation of a file. I thought it would adhere to the configuration of the used disk but as you say, the prefix is hardcoded as you say.

**Comment by j3j5** [comment]
ATM I am using the much less convenient `config('filesystems.disks.local.root') . DIRECTORY_SEPARATOR . $filename`.

**Comment by briedis** [comment]
@j3j5 I'm doing similiary. Feels like a hack..

```
protected function getUrl($suffix)
    {
        /** @var Filesystem|FilesystemAdapter $app */
        $app = \app('storage.images');

        $adapter = $app->getAdapter();

        if ($adapter instanceof AwsS3Adapter) {
            return $app->url($this->getFilePathname());
        }

        if ($adapter instanceof Local) {
            return url('uploads/images/' . $this->getFilePathname());
        }

        throw new \Exception('Unknown driver, can`t generate URL');
    }
```

**Comment by thomassjogren** [comment]
The `LocalAdapter` also have a `getPathPrefix()` method that returns the root set in the config, so I guess that should be used in the `FilesystemAdapter.php`.

**Comment by masonfox** [comment]
I also had this issue 👍

**Comment by stpangia** [comment]
this works for me: 

Storage::disk('local')->getDriver()->getAdapter()->getPathPrefix()

**Comment by themsaid** [comment]
This should be fixed here: https://github.com/laravel/framework/pull/16281
