### ISSUE TITLE
Unit test fails if config is cached

### ISSUE THREAD

**Issue by shahidnajam** [laravel/framework#13374]
I have written tests for application. there are plenty of test files. but when i cache the config by running command "php artisan config:cache", some of tests fail (like email sending tests and some db transactions related tests). 
when I clear config cache, all tests pass without any problem.

Why it is so? why cached config affect unit testing result?

**Comment by GrahamCampbell** [comment]
Thanks but this is not a bug, just a limitation introduced in L5.2, which allowed us to increase request throughput by 25%.

**Comment by GrahamCampbell** [comment]
You need to delete the cached config in order to have us load the test environment.

**Comment by GrahamCampbell** [comment]
Note that config and route caching are intended for use when deploying to production. Don't use them on local dev, since they'll stop you running the tests with a testing environment.

**Comment by shahidnajam** [comment]
Thanks for information. I guessed the same but just wanted to be sure.

**Comment by GrahamCampbell** [comment]
No problem. :)

**Comment by katzenbaer** [comment]
For anyone who wants an automated worry-free solution to this problem, add this to your `tests/TestCase.php` class:
```
    /**
     * Creates the application.
     *
     * @return \Illuminate\Foundation\Application
     */
    public function createApplication()
    {
        $app = require __DIR__.'/../bootstrap/app.php';

        $app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

        $this->clearCache(); // NEW LINE -- Testing doesn't work properly with cached stuff.

        return $app;
    }

    /**
     * Clears Laravel Cache.
     */
    protected function clearCache()
    {
        $commands = ['clear-compiled', 'cache:clear', 'view:clear', 'config:clear', 'route:clear'];
        foreach ($commands as $command) {
            \Illuminate\Support\Facades\Artisan::call($command);
        }
    }
```

**Comment by Tobiasartz** [comment]
I feel @katzenbaer solution should be the default.
Although this is an opinion I feel most developers do not expect their test configuration to come from previously cached values.
I surely didn't expect it when I accidentaly whacked my own development database 😊

**Comment by moff** [comment]
I've updated solution of @katzenbaer and now my development database won't get wiped out, when cache files exist.

```
     /**
     * Creates the application.
     *
     * @return \Illuminate\Foundation\Application
     */
    public function createApplication()
    {
        $app = require __DIR__.'/../bootstrap/app.php';

        $app->make(Kernel::class)->bootstrap();

        $this->clearCache(); // NEW LINE -- Testing doesn't work properly with cached stuff.
        
        // these are to refresh configs and environment variables, since $app has loaded cache before it was cleared
        $app->make(\Illuminate\Foundation\Bootstrap\LoadConfiguration::class)->bootstrap($app);
        $app->make(\Illuminate\Foundation\Bootstrap\LoadEnvironmentVariables::class)->bootstrap($app);

        return $app;
    }
```

**Comment by StefanPrintezis** [comment]
I tried the suggestion @moff offered, but somehow the first testcase still had the old cache. I had to rebuild my entire application.

`    
/**
 * Creates the application.
 *
 * @return \Illuminate\Foundation\Application
 */
public function createApplication()
{
    $createApp = function() {
        $app = require __DIR__.'/../bootstrap/app.php';
        $app->make(Kernel::class)->bootstrap();
        return $app;
    };

    $app = $createApp();
    if ($app->environment() !== 'testing') {
        $this->clearCache();
        $app = $createApp();
    }

    return $app;
}
`

**Comment by manyasone** [comment]
If you want to recreate the cleared view/config/route cache files, when they were present before running the tests, change your `clearCache()` like this:
 
```
// Clear existing caches and re-cache afterwards.
collect(['config', 'view', 'route'])->each(function ($command) {
    if (file_exists(base_path("bootstrap/cache/$command.php"))) {
        Artisan::call("$command:clear");
        $this->beforeApplicationDestroyed(fn() => Artisan::call("$command:cache"));
    }
});
```

**Comment by manyasone** [comment]
If you want to restore your config files after testing, it should work like this:

```
// Rename existing cache files to `config|view|route.php.tmp` and reverse the renaming before finishing.
collect(['config', 'view', 'route'])->each(function ($command) {

    $file = base_path("bootstrap/cache/$command.php");

    if (file_exists($file)) {
        rename($file, "$file.tmp");
        $this->beforeApplicationDestroyed(fn() => rename("$file.tmp", $file));
    }
});
```

(Using `\Artisan::call('config:clear')` and `\Artisan::call('config:cache')` instead of renaming the files would cache the testing config.)

**Comment by Lukmauu** [comment]
> For anyone who wants an automated worry-free solution to this problem, merge this into to your `tests/TestCase.php` class:
> 
> ```
>     /**
>      * Creates the application.
>      *
>      * @return \Illuminate\Foundation\Application
>      */
>     public function createApplication()
>     {
>         $app = require __DIR__.'/../bootstrap/app.php';
> 
>         $app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();
> 
>         $this->clearCache(); // NEW LINE -- Testing doesn't work properly with cached stuff.
> 
>         return $app;
>     }
> 
>     /**
>      * Clears Laravel Cache.
>      */
>     protected function clearCache()
>     {
>         $commands = ['clear-compiled', 'cache:clear', 'view:clear', 'config:clear', 'route:clear'];
>         foreach ($commands as $command) {
>             \Illuminate\Support\Facades\Artisan::call($command);
>         }
>     }
> ```

Give this man a trophy, this is a genius solution, thank you

**Comment by Lukmauu** [comment]
Following what @StefanPrintezis you can make an improvement by clear cache without Artisan::call() then you do not need the application created before: use sheel_exec and it will make things faster. 

`
    private function clearCache(): void
    {
        $commands = ['clear-compiled', 'cache:clear', 'view:clear', 'config:clear', 'route:clear'];
        foreach ($commands as $command) {
            shell_exec("php artisan {$command}");
        }
    }`
