### ISSUE TITLE
--timeout option for queue:work --daemon

### ISSUE THREAD

**Issue by halaei** [laravel/framework#13372]
I think it is possible to have a `--timeout` option for `queue:work --daemon` that works exactly as it does in `queue:listen` command:

> --timeout[=TIMEOUT]  Seconds a job may run before timing out [default: 60]

One way to implement this feature is to use `pcntl_alarm()` and `pcntl_signal()` functions.

**Comment by GrahamCampbell** [comment]
Sounds fine to me, that is, if those functions are actually enabled on the server. Most distributions disable them out of the box.

**Comment by halaei** [comment]
Sounds like they are enabled in our servers! ;)

**Comment by halaei** [comment]
[laravel/internal issue](https://github.com/laravel/internals/issues/75)
