### ISSUE TITLE
Subscribe listener to ALL events (question)

### ISSUE THREAD

**Issue by KonstantinKolodnitsky** [laravel/framework#13375]
Is it possible to subscribe a listener to handle all events in L5.2?
Something like

    $events->listen(
            '*',
            'App\Listeners\MyListener@handle'
        );

Thanks

**Comment by GrahamCampbell** [comment]
Yes.

**Comment by GrahamCampbell** [comment]
Our github issues are strictly for bug reports though pleaser.

**Comment by KonstantinKolodnitsky** [comment]
Sorry.

**Comment by GrahamCampbell** [comment]
No worries. :)
