### ISSUE TITLE
Proprosal of redesigning csrf protection

### ISSUE THREAD

**Issue by bittenApple** [laravel/framework#13377]
We use Laravel 5.1 and Redis as our session drive on our production environment,  and have randomly came up withTokenMismatchException over last two months, which made us very annoyed.
I know this is a known issue which hasn't been fixed yet, because of session persistence bug. So I refer [Django's solution](https://github.com/django/django/blob/master/django/middleware/csrf.py) to rewrite the csrf middleware, just compare the token in cookie and request header, avoiding dependency with laravel session. It works fine now.
This bypasses the session bug but could be a temporal solution to help people who need csrf protection.
If needed, I am glad to send a pull request.

**Comment by GrahamCampbell** [comment]
Thanks, but as per our contribution guidelines, we don't process proposals here.

**Comment by bittenApple** [comment]
Alright, issues are strictly for bug reports. If I issue it as a session bug, I think you will close it because of duplication.

**Comment by GrahamCampbell** [comment]
I read your title:

> Proprosal of redesigning csrf protection

All proposals need to go to our dedicate repo please.

**Comment by bittenApple** [comment]
Thanks, I will move this issue.
