### ISSUE TITLE
Laravel doesn't follow PSR-0 namespace standard

### ISSUE THREAD

**Issue by ThomasTesla** [laravel/framework#13382]
With PSR-0 the namespace needs to be equivalent to the path, which is not the case:

`
"psr-4": {
            "App\\": "app/"
        }
`

The app directory should be uppercase.

This would resolve problems with the PHP PSR-1 and PSR-2 standard:

https://github.com/benmatselby/sublime-phpcs/issues/133
https://github.com/benmatselby/sublime-phpcs/issues/135

**Comment by ThomasTesla** [comment]
From the PSR-0 specification:

> psr0 [PSR-0]
Classes must be in a path that matches their namespace, be at least one namespace deep, and the class name should match the file name.

**Comment by rephole** [comment]
Who cares PSR? Laravel is following TAYLOR-0 and TAYLOR-4 standarts.

**Comment by JeroenVanOort** [comment]
"Laravel follows the PSR-2 coding standard and the PSR-4 autoloading standard." ([source](https://laravel.com/docs/5.2/contributions#coding-style)).

In the [PSR-4 examples](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-4-autoloader.md), lowercase folder names are used, so I don't think there is a problem with Laravel using them too.

**Comment by GrahamCampbell** [comment]
PSR-0 is deprecated. Laravel follows PSR-4.

**Comment by GrahamCampbell** [comment]
Do not use PSR-0 anymore.

**Comment by ThomasTesla** [comment]
Ok.

If someone is asking how to exclude PSR-0: use "-psr0" in your fixers.

Another solution that @GrahamCampbell mentioned:

> In L5 apps, you are meant to change the namespace to something more appropriate anyway.

_Source: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1161#issuecomment-94146212_

Why are all the root folders lowercase and the subfolders uppercase? What's the reason behind that?

**Comment by valerio-bozzolan** [comment]
> Why are all the root folders lowercase and the subfolders uppercase? What's the reason behind that?

10 years later this question is still useful 😁
