### ISSUE TITLE
Eagerloading hasOne relationships does not limit the results from the query.

### ISSUE THREAD

**Issue by OzanKurt** [laravel/framework#13387]
I noticed a difference between instantly calling the relationship and loading `hasOne` relationships.

Here is how I tested:

``` php
        $user = User::find(1);

        $user->setRelations([]);

//        $user->load(['latestBlogPost']);

//        $user->latestBlogPost;
```

Simply create a `hasOne` relationship and uncomment the commented lines one by one.

The lifecycle of  the first call is:
- `Model::load()`
- `Builder::eagerLoadRelations()`
- `Builder::loadRelation()`
- `Relation::getEager()` // This is where it sends an unnecessary query without `limit = 1`
- `HasOne::match()`
- `HasOneOrMany::matchOne()`
- `HasOneOrMany::matchOneOrMany()`

The lifecycle of  the socond call is:
- `Model::__get()`
- `Model::getAttribute()`
- `Model::getRelationValue()`
- `Model::getRelationshipFromMethod()`
- `HasOne::getResults()`

Instead of calling `getEager` method in line 647 of `Eloquent\Builder` i called `getResults`.

``` php
        // Once we have the results, we just match those back up to their parent models
        // using the relationship instance. Then we just return the finished arrays
        // of models which have been eagerly hydrated and are readied for return.
//        $results = $relation->getEager();
        $results1 = $relation->getResults();

        if (!$results1 instanceof \Illuminate\Database\Eloquent\Collection)
        {
            $results = (new \Illuminate\Database\Eloquent\Collection())->add($results1);
        }
```

By doing this, I avoided calling `get` method on the query builder and instead used the relations query system.

``` php
class HasOne extends HasOneOrMany
{
    /**
     * Get the results of the relationship.
     *
     * @return mixed
     */
    public function getResults()
    {
        return $this->query->first();
    }
```

This way the `getResults` method of the `HasOne` relation has been used. Not just `$this->query->get()`.

PS: The same thing is happening for the `BelongsTo` relationship. (Haven't tried MorphOne but probably it's also like that.)

**Comment by OzanKurt** [comment]
@GrahamCampbell :)

**Comment by JeroenVanOort** [comment]
First of all, I'd like to find out why there is difference in the lifecycles.

**Comment by OzanKurt** [comment]
@JeroenVanOort Seems like nobody cares, it's actually a big issue for people that has many data in their databases.

**Comment by OzanKurt** [comment]
@GrahamCampbell Bump.

**Comment by themsaid** [comment]
I just opened a PR: https://github.com/laravel/framework/pull/21398

Closing this issue and moving the discussion to the PR.

**Comment by staudenmeir** [comment]
There's no simple solution to this problem. You would have to do something like [this](https://softonsofa.com/tweaking-eloquent-relations-how-to-get-n-related-models-per-parent/).

**Comment by OzanKurt** [comment]
Its something hasOne should do by default.

**Comment by staudenmeir** [comment]
As you can see in my package, this requires complex queries that aren't even supported by all databases.
