### ISSUE TITLE
Auth::user() is inaccessible from scopes when retrieving the model through route model binding

### ISSUE THREAD

**Issue by VegardSkui** [laravel/framework#13385]
I have a global scope on a model which adds an extra where clause including the user's ID (No, relations isn't going to work since they are also already in use). Everything worked perfectly until I tried to use model binding on one of my routes to clean it up. Apparently the model binding runs so early during the lifecycle of the request that `Auth::user()` hasn't been set yet and therefore just returns `null`.

**Comment by GrahamCampbell** [comment]
Yes, that is true.

**Comment by GrahamCampbell** [comment]
Sorry, but this is not a bug, it's just how it works.
