### ISSUE TITLE
Cache::flush() removes data that maybe outside the cache prefix

### ISSUE THREAD

**Issue by halaei** [laravel/framework#13386]
Example1: If you set the same Redis database for two laravel applications, with different `cache.prefix` config, flushing cache of one application will erase the other as well. 
Example 2: If you set both cache and queue on the same Redis database, flushing cache will flush queues as well.
I think this is in contradiction with what can be inferred from [this comment](https://github.com/laravel/laravel/blob/master/config/cache.php#L70) in /config/cache.php.
```php
    /*
    |--------------------------------------------------------------------------
    | Cache Key Prefix
    |--------------------------------------------------------------------------
    |
    | When utilizing a RAM based store such as APC or Memcached, there might
    | be other applications utilizing the same cache. So, we'll specify a
    | value to get prefixed to all our keys so we can avoid collisions.
    |
    */
    'prefix' => 'laravel',
```
Maybe in this docblock one should discourage letting "other applications utilize the same cache".

**Comment by GrahamCampbell** [comment]
This is a known behaviour. I'd suggest you use physically different stores to avoid this.

**Comment by GrahamCampbell** [comment]
For example, when using redis, you can connect to physically different databases. By default, redis ships with 32 separate databases, indexed 0->31. Laravel uses `0` by default.

**Comment by halaei** [comment]
That is OK, except a need for update in the docblock. For Redis driver, at
least, it is possible to delete keys matching pattern like `laravel:*`.
Maybe a new function can be introduced like `Cashe::erase($pattern)`?
