### ISSUE TITLE
sendFailedLoginResponse & handleUserWasAuthenticated in AuthenticatesUsers does not care about ajax/want json

### ISSUE THREAD

**Issue by crissi** [laravel/framework#13388]
sendFailedLoginResponse & handleUserWasAuthenticated in AuthenticatesUsers does not care about ajax/want json requests. It redirect back to login view even on ajax requests.

This would solve it for sendFailedLoginResponse:
`   
    protected function sendFailedLoginResponse($request)
    {
        if ($request->ajax() || $request->wantsJson()) {
            return response('Unauthorized.', 401);
        }
        return redirect()->back()
            ->withInput($request->only($this->loginUsername(), 'remember'))
            ->withErrors([
                $this->loginUsername() => $this->getFailedLoginMessage(),
            ]);
    }
`

**Comment by guoyunhe** [comment]
I also think this is something Laravel can improve and it is not so difficult:

```php
protected function sendFailedLoginResponse(Request $request)
{
    if ($request->wantsJson() || $request->ajax()) {
        return response()->json([
            $this->loginUsername() => $this->getFailedLoginMessage(),
        ], 422);
    } else {
        return redirect()->back()
            ->withInput($request->only($this->loginUsername(), 'remember'))
            ->withErrors([
                $this->loginUsername() => $this->getFailedLoginMessage(),
            ]);
    }
}
```
