### ISSUE TITLE
view - last variable from @foreach exists out of the loop

### ISSUE THREAD

**Issue by vincoweb** [laravel/framework#13407]
Hi. When i send only 'sections' variable to view and then i used this view:

```
@foreach ($sections as $section)
		 {{ $section->name }} 
@endforeach

//then last section exists out of scope @foreach loop 
 {{ $section->name }} 

```
Then new $section variable was created out of loop

**Comment by GrahamCampbell** [comment]
What laravel version. Please include the version in full.

**Comment by vlakoff** [comment]
Maybe it is related to PHP's [`foreach`](http://php.net/manual/en/control-structures.foreach.php):

> Warning: Reference of a $value and the last array element remain even after the foreach loop. It is recommended to destroy it by unset().

**Comment by vincoweb** [comment]
i use  version: v5.2.31

**Comment by GrahamCampbell** [comment]
Yeh, this is is expected. PHP doesn't create "variable namespaces" inside loops, unlike java.
