### ISSUE TITLE
How to connect laravel to Qunatum GIS or integrate with quantum gis web version

### ISSUE THREAD

**Issue by mgldvlpr** [laravel/framework#13405]
Hello. I am new to Laravel and developing a web site which must connect to Quantum GIS server for showing and editing GIS data. 
But no idea how to connect it to QGIS. Is there any package can be used for my purpose

**Comment by GrahamCampbell** [comment]
I'd suggest asking on the forums. We only process bug reports here.

**Comment by vasimshk** [comment]
Hi,

Anyone got the answer to this question? OR
Please Suggest some good guides.

**Comment by driesvints** [comment]
@vasimshk Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
