### ISSUE TITLE
[5.2] updated_at column always updated, regardless of 'timestamps' option

### ISSUE THREAD

**Issue by guillemc** [laravel/framework#13400]
Doing something like:

    $user->name = 'user ' . date('H:i:s');
    $user->save(['timestamps' => false]);

Results in:

    'name' => 'user 12:36:35'
    'updated_at' => '2016-05-02 12:36:35'

The reason appears to be that, although in the model's `performUpdate`method the `updated_at` column is discarded,  `Illuminate\Database\Eloquent\Builder` adds it again.

**Comment by themsaid** [comment]
As in https://github.com/laravel/framework/issues/12627 and https://github.com/laravel/framework/issues/10028.

This feature is broken, and was removed in 5.3 https://github.com/laravel/framework/pull/12617.

Use this approach instead:

```php
...
$user->timestamps = false;

$user->save();
```

**Comment by srmklive** [comment]
You can go with @themsaid's solution or you can simply do this in your Eloquent model as well:

```
public $timestamps = false;
```

**Comment by guillemc** [comment]
Oops, sorry for the duplication, and thanks for the response.
