### ISSUE TITLE
MigrateMakeCommand::writeMigration() called with erroneous $create argument

### ISSUE THREAD

**Issue by vlakoff** [laravel/framework#13409]
`Database\Console\Migrations\MigrateMakeCommand::writeMigration($name, $table, $create)` is sometimes called with `$create` equals `null`, whereas it should be `false`. This might lead to future bugs and ideally should be fixed.

This isn't caught by the tests, also because of the loose typing. If you look for example at `DatabaseMigrationMakeCommandTest::testBasicCreateDumpsAutoload`, line 23:

    $creator->shouldReceive('create')->once()->with('create_foo', __DIR__.'/migrations', null, false);

but in fact it receives `(<path>, null, NULL)`.

<br>The bug is because in `Database\Console\Migrations\MigrateMakeCommand::fire`, line 70 gives NULL:

    $create = $this->input->getOption('create');

**Comment by billmn** [comment]
@vlakoff This issue can be closed?

**Comment by vlakoff** [comment]
Yep, has been fixed by #13439 and no issues remaining if I recall correctly. Thanks for pointing out.
