### ISSUE TITLE
[Envoy] The helper "dialog" is not defined.

### ISSUE THREAD

**Issue by Butochnikov** [laravel/framework#13402]
Error in
@task('deploy', ['on' => 'web', 'confirm' => true])

[Symfony\Component\Console\Exception\InvalidArgumentException]
  The helper "dialog" is not defined.

The Dialog Helper was depreciated in Symfony 2.5 and removed in 3.0.

**Comment by GrahamCampbell** [comment]
Sorry, these issues are for bugs in laravel/framework only.

**Comment by Butochnikov** [comment]
where issues for Envoy?
