### ISSUE TITLE
factory function not recognize 1 as amount of objects

### ISSUE THREAD

**Issue by maicoqb** [laravel/framework#13411]
Trying to make a test with random number of factory objects
```php
// Create n references
$references = factory(Reference::class, mt_rand(1,5))->make();
```
When I iterate on objects I getting `true`
```php
// Iterate on references
foreach($references as $reference){
  dump($reference);
}
```
Result: `true`

I suppose that calling factory function with the second argument as a number, the factory should return a Collection of that amount of elements.

**Comment by srmklive** [comment]
This is not really an issue.
