### ISSUE TITLE
get column but set array

### ISSUE THREAD

**Issue by fimdoit** [laravel/framework#13415]
```
protected $casts = [
        'column'   => 'array',
    ];
```

```
public function getColumnAttribute($value)
{
    foreach ($value as $v) {
        $v = 'a'.$v;
    }
    return $value;
}
```

Can't foreach

**Comment by themsaid** [comment]
Mutators receive raw data, for example if your `column` contains a JSON string, `$value` in the mutator will be a JSON string.

**Comment by fimdoit** [comment]
but do like this
```
public function getColumnAttribute($value)
{
    foreach (json_decode($value) as $v) {
        $v = 'a'.$v;
    }
    return json_encode($value);
}
```

get data column was a json not array

**Comment by themsaid** [comment]
Because you're not doing anything to the `$value` here :)

Do something like:

```php
public function getColumnAttribute($value)
{
    return array_map(function($v){
        return 'a'.$v;
    }, json_decode($value));
}
```

I think you need to close this issue as it's not related to laravel, would be glad to help on larachat if you need further assistance.
