### ISSUE TITLE
$request->get() returns null for posted array

### ISSUE THREAD

**Issue by stevenmusumeche** [laravel/framework#13418]
I am posting an array of dates to a controller in a test:

`$this->json('post', '/admin/location/1/closed_dates', ['dates' => ['2015-01-01', '2016-01-01']])`

In the controller, I can see the date array using `$request->all()['dates']`, however, `$request->get('dates')` returns `null`.  

This appears to be a bug.

**Comment by GrahamCampbell** [comment]
That's because the method is called `get`. It won't give you posted variables.

**Comment by GrahamCampbell** [comment]
It'll give you query params only.

**Comment by stevenmusumeche** [comment]
Thank you @GrahamCampbell.  Is there a method for getting requested post data (other than `$request->input()`)?

**Comment by bbashy** [comment]
I tend to use the following but ->get() should return all _POST, _GET and _SERVER?
```
return $request->dates;
```
