### ISSUE TITLE
UpdateOrCreate incomplete instance returned

### ISSUE THREAD

**Issue by danielkesselberg** [laravel/framework#13419]
`$x = Models\Client::find(1);`
`$y = $x->mailJobs()->updateOrCreate(['event' => 'OrderComplete', 'status' => 0]);`

I setup a morph relation between Client and MailJobs. One Client has many MailJobs. We notice that the first instance is returned with some fields missing. Could you explain that issue to us? Its not possible to access attributes like log or data

First call: `$y = $x->mailJobs()->updateOrCreate(['event' => 'OrderComplete', 'status' => 0]);`
```
=> Models\MailJob {#758
    event: "OrderComplete",
    status: 0,
    parent_id: 1,
    parent_type: "Models\Client",
    updated_at: "2016-05-03 18:23:25",
    created_at: "2016-05-03 18:23:25",
    id: 55043,
}
```
Second call: `$y = $x->mailJobs()->updateOrCreate(['event' => 'OrderComplete', 'status' => 0]);`
```
=> Models\MailJob {#753
    id: 55043,
    event: "OrderComplete",
    status: 0,
    fail: null,
    data: null,
    log: null,
    parent_id: 1,
    parent_type: "Models\Client",
    created_at: "2016-05-03 18:23:25",
    updated_at: "2016-05-03 18:23:25",
    deleted_at: null,
}
```

Class: MailJob

```
namespace Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class MailJob extends Model
{
    use SoftDeletes;

    protected $table = 'mail_jobs';

    protected $fillable = ['event', 'status', 'fail', 'data', 'log'];

    protected $dates = ['deleted_at'];

    protected $casts = [
        'data' => 'array',
    ];

    public function setLogAttribute($value)
    {
        $this->attributes['log'] = $this->attributes['log'] . sprintf('<span>%s %s</span><br>', Carbon::now()->format('Y-m-d H:i:s'), $value);
    }

    /* Relations */
    public function parent()
    {
        return $this->morphTo();
    }
}
```

Class: Client

```
public function mailJobs()
{
    return $this->morphMany('Models\MailJob', 'parent');
}

```

Tested with laravel/framework (v5.2.31)

This might be related to https://github.com/laravel/framework/issues/10013 and https://github.com/laravel/framework/issues/10019 but both issues closed without any information.

**Comment by lagbox** [comment]
The first time is ending up with a create since it can't find an existing record matching those attributes. Since you only gave it those attributes, those are the only attributes (besides primary key and timestamps, that are available). `$m = new Model($attributes); $m->fill($secondArg); $m->save();`  This causes an insert query, it isn't selecting * on the table.

The second time it is finding a record by those attributes; `$m = Model::where($attributes)->first(); $m->fill($secondArg); $m->save();`.  That query is returning all the fields from the table as its a `select *`.

`updateOrCreate($atts, $fill) -> firstOrNew($atts) -> fill($fill) & save()`

**Comment by danielkesselberg** [comment]
Thanks for explanation @lagbox. This behaviour is confusing and should be documented somewhere. Is there any way to work around this issue? We need an MailJob instance with all attributes.

**Comment by lagbox** [comment]
Not without another query.

```php
$full = $thecreated->fresh();
```
Reload a fresh model instance from the database.

**Comment by ThaDaVos** [comment]
Run into the same issue today too... it's a weird issue though because on the third-time it does work and I'm getting all the fields back...
https://github.com/laravel/framework/issues/30871
