### ISSUE TITLE
query builder parameter binding not working with FROM clause

### ISSUE THREAD

**Issue by markpurser** [laravel/framework#13427]
DB::select('SELECT * FROM :name', [':name' => 'my_table_name'])

gives error

QueryException in Connection.php line 669:
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?' at line 1 (SQL: SELECT * FROM :name)

(Laravel 5.2)

**Comment by themsaid** [comment]
try `DB::selectRaw()`

**Comment by PlayMa256** [comment]
For what i know the named binding just work for parameters, not table names. Try to do the binding using '?', it may work, if not, the PDO class (what db uses from behind) do not support named binding for table names.

**Comment by markpurser** [comment]
Thanks. Out of interest, how would you protect the inserted table name against SQL injection if you can't use binding?

**Comment by PlayMa256** [comment]
Usually you just protect the input. The table name will be hardcoded by the programmer, the malicious user will be able just to insert data that is comming from the inputs, or so, the values that you  are inserting on the table, getting from the user.

**Comment by Shifterovich** [comment]
@PlayMa256 Thanks, I spent a lot of time debugging this as my other parameters didn't work either.

> Thanks. Out of interest, how would you protect the inserted table name against SQL injection if you can't use binding?

Since there's usually a very small amount of table names, you could do something like this:
```
// SQLi protection (whitelist)
if (!in_array($table_name, ['my_table_name', 'users', 'posts', 'etc'])) {
    return; // Maybe throw an error?
}

DB::select("SELECT * FROM {$table_name}");
