### ISSUE TITLE
[5.1] [5.2] Blade compliation bug when using a ternary statement and the word "or"

### ISSUE THREAD

**Issue by nhowell** [laravel/framework#13426]
As an example of the bug, blade is compiling:
```
{{ $name ? 'First or last' : 'No name' }}
```
into:
```
<?php echo e(isset($name ? 'First) ? $name ? 'First : last' : 'No name'); ?>
```

This is obviously not correct. It's stumbling over the word "or". If you remove the "or" then it correctly leaves the ternary statement alone:
```
{{ $name ? 'First last' : 'No name' }}
```
into:
```
<?php echo e($name ? 'First last' : 'No name'); ?>
```

I've isolated the source of the issue to the `preg_replace` on this line (https://github.com/laravel/framework/blob/5.1/src/Illuminate/View/Compilers/BladeCompiler.php#L348)
```
return preg_replace('/^(?=\$)(.+?)(?:\s+or\s+)(.+?)$/s', 'isset($1) ? $1 : $2', $value);
```

You can see a live example here: http://www.phpliveregex.com/p/fzy (be sure to switch to `preg_replace`)

I would submit a PR with a failing test and a fix for this, but my regex skills are a little lacking.

**Comment by JayBizzle** [comment]
Already mentioned in #10135

**Comment by nhowell** [comment]
@JayBizzle Ah, thanks. That issue was closed and not fixed though.

@GrahamCampbell Explanation? Why close the issue when it's a legitimate bug?

**Comment by JayBizzle** [comment]
All the info as to why it isn't fixed is in that issue I linked to

**Comment by GrahamCampbell** [comment]
We are going to remove the `or` syntax in a later version of Laravel, fixing this bug, since the syntax is replaced by the `??` operator in `php 7.

**Comment by nhowell** [comment]
@JayBizzle That issue did not exactly address how it was going to be fixed. Specifically, it does not outright say that the feature will be dropped and replaced with the `??` operator present in PHP 7.

@GrahamCampbell Okay, thank you for the explanation.
