### ISSUE TITLE
[Request] Array values in Cache

### ISSUE THREAD

**Issue by Max13** [laravel/framework#13422]
I would like to request a feature: Being able to store array values in cache, and retrieve/put them with dot notation.

Here is an example of an associative array to cache:

```
[
    'ab' => [1, 2, 3],
    'cd' => [4, 5, 6],
]
```

I could store it using `Cache::put('myArr', $myArr, 60)` then later do `Cache::put('myArr.ab', [1, 1, 1], 60)` to alter only `$myArr['ab']` without pulling the whole array, modify it then store it again.

**Comment by GrahamCampbell** [comment]
Please submit requests to the correct place as per the docs.

**Comment by Max13** [comment]
Sorry for that, it's done, thanks

**Comment by erdemkeren** [comment]
For anyone coming from google like me, Follow: https://github.com/laravel/internals/issues/80
