### ISSUE TITLE
Subdomain authentication

### ISSUE THREAD

**Issue by rasmusrosengren** [laravel/framework#13420]
Hello, I've got this problem with the `Auth::user()` object not working properly when using subdomains.
I'm running my local development website using XAMPP on **localhost** and I've got the subdomains _admin.localhost_ and _boards.localhost_.
```
/*
    |--------------------------------------------------------------------------
    | Session Cookie Domain
    |--------------------------------------------------------------------------
    |
    | Here you may change the domain of the cookie used to identify a session
    | in your application. This will determine which domains the cookie is
    | available to in your application. A sensible default has been set.
    |
    */

    'domain' => false,
```
I get the error trying to get property of non-object. I've made multiple google searches and looked through various pages but nothing has solved my problem. I've tried these variations:
```
'domain' => 'localhost'
...
'domain' => '.localhost'
...
'domain' => '*.localhost'
```

but no better results from that. Could someone guide me to a proper solution or is a custom solution required?

**Comment by GrahamCampbell** [comment]
Feel free to ask on the forums.

**Comment by rasmusrosengren** [comment]
@GrahamCampbell where is the forums?
