### ISSUE TITLE
[comment error] ConnectionFactory->getWriteConfig

### ISSUE THREAD

**Issue by zuoRambo** [laravel/framework#13424]
the comment for [getWriteConfig] (https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Connectors/ConnectionFactory.php#L113) is confused.
the same question happened on [createReadWriteConnection](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Connectors/ConnectionFactory.php#L68)

**Comment by zuoRambo** [comment]
still feel confused about [setPdoForType](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/DatabaseManager.php#L212-L216), when type is 'write', why setReadPdo?

**Comment by themsaid** [comment]
Please feel free to open a PR in case you think something should be corrected.

Closing this since it sin't actually a big report.
