### ISSUE TITLE
running migrate --pretend executes query if affecting non-default DB

### ISSUE THREAD

**Issue by brianseitel** [laravel/framework#13431]
This seems to be a regression (per: https://github.com/laravel/framework/pull/4362).

I have a migration that like this:

``` php
function up() {
       Schema::create('permission_user', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('user_id');
            $table->integer('permission_id');
            $table->timestamps();
        });

       Schema::create('permissions', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->timestamps();
        });
}
```

I'm trying to create these tables in a different database (not the default connection database) called `users`.

I've tried to run `php artisan migrate --pretend`, and in each case I'm getting undesirable behavior. I've tried mixing up the migration a number of ways (see below):

| Method | Tables Created | Pretend Output? | Migration Logged |
| --- | --- | --- | --- |
| inline: `Schema::create('users.permissions')` | Yes, in correct database (not supposed to create!) | No | No |
| method: `Schema::connection('users')->create(...` | Yes, in correct database (not supposed to create!) | No | No |
| update `protected $connections = 'users'` | Yes but in _default DB_, `$connection` appears to be ignored | Yes | No |
| don't specify database at all | No | Yes | No |

As you can see, only the last case performs as expected. The problem with that is that the live migration would create the tables in the wrong database.

How can I make this migration "pretend" correctly, while still achieving the desired behavior on a live migration? If someone wants to point me in the right direction, I'm happy to look into it and potentially submit a PR to fix.

Thanks.

**Comment by themsaid** [comment]
AFAIK The only way to make this work is to set the `protected $connection = 'connection'` and *also* specify the connection on the `Schema` instance `Schema::connection('connection')`.

If the connection of the migration doesn't match the connection in your schema instance you'll experience this problem you mentioned.

This is because the `pretend` method is called on the migration connection, while in your Schema instance you're running the query on a different connection.

**Comment by brianseitel** [comment]
That worked! Thanks. Still seems kind of buggy. Only one of those should be required, not both at the same time, yeah?

**Comment by themsaid** [comment]
Closing since the issue seems to be a rare edge case that can be solved with a workaround.
