### ISSUE TITLE
Leading slash is lost when redirecting

### ISSUE THREAD

**Issue by odbayar** [laravel/framework#13432]
My Laravel app resides in a subdirectory (https://map.minu.mn/beta/ and beta is a symbolic link to the laravel's "public/" directory in some other place if it matters).

When I redirect using:
return redirect('/?message=some+message');
It returns:
Location: /beta?message=....

So, where is the '/' between "/beta" and "?message" ?

**Comment by GrahamCampbell** [comment]
If beta is the application, you can't move outside that with laravel functions.

**Comment by odbayar** [comment]
Sorry, it seems like I wrote it very vaguely.

I expected /beta**/**?message instead of /beta?message from Laravel?
Is it possible to redirect to  /beta**/**?message ?
