### ISSUE TITLE
The same argument pattern validator twice in one route causes error.

### ISSUE THREAD

**Issue by rudolfdobias** [laravel/framework#13442]
Hello,
I don't know whether this is bug or feature, but I`d appreciate some help or explaination.

I've described this problem [here](http://stackoverflow.com/questions/37040241/multiple-route-argument-patterns-in-one-route-in-laravel-5-2) thoroughly, so long story short:

Let's have a route argument pattern defined
`$router->pattern('uuid', '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}');`

which works for simple routes:
`$router->get('/users/{uuid}', 'Users@get');`

but does not work when I want to validate more uuids in one route:
`$router->get('/resource/{uuid}/subResource/{uuid}', 'Example@get');`

I saw somewhere a notation like `resource/{resId:uuid}/sub/{subId:uuid}`, that would be perfect but does not work here.

How is the proper approach to validate more arguments by the same pattern? Or is it a bug?
Thank you.

**Comment by themsaid** [comment]
What about this?

```php
$uuidPattern = '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}';

$router->get('/resource/{some_uuid}/subResource/{another_uuid}', 'Example@get')->where(['some_uuid' => $uuidPattern, 'another_uuid' => $uuidPattern]);
```

**Comment by rudolfdobias** [comment]
That will absolutely work but I don't find it ellegant. Even when you have grouped routes in lambda function or routes defined elsewhere, you don't want to pass this string everytime through use($uuidPattern) or some function argument.

**Comment by themsaid** [comment]
The thing is this is based on Symfony's router component, I'm not sure if Taylor would want to modify laravel's router component for just this issue, I saw him reject many proposals with `you can use ....`

**Comment by srmklive** [comment]
I agree with @themsaid in this regard. It may end up becoming a headache overall in laravel's router component. Any specific shall be implemented by developer himself & not by the framework maintainer.

**Comment by themsaid** [comment]
Closing since there's a way to achieve the same functionality.

For suggestions and feature requests please use the https://github.com/laravel/internals repo.
