### ISSUE TITLE
empty or isset checks on Eloquent relations fails in PHP 7

### ISSUE THREAD

**Issue by tmiskin** [laravel/framework#13448]
In both PHP 7.0.1 and later, empty and isset checks return improperly on unloaded relations on Eloquent models. For example, if you have a model `$parentModel` that has a related model relation `childModel` where the id of the child model is set on `$parentModel` already and you then check if it's empty with `empty($parentModel->childModel)` it returns `1`.  However, if you then echo out `$parentModel->childModel` it returns with the existing relation.  In PHP 5.6 it worked, and `empty($parentModel->childModel)` returns `0`.  This is obviously a critical bug if you rely on isset or empty for checking for existing relations.  Some references for the fixes in PHP 7 that addressed issues with isset and `ArrayAccess` I have included a few links below on possible issues that may be related, but am not sure:

https://bugs.php.net/bug.php?id=69659
https://bugs.php.net/bug.php?id=72160

**Comment by GrahamCampbell** [comment]
This was fixed in PHP 7.0.6.

**Comment by tmiskin** [comment]
@GrahamCampbell No it wasn't with our examples and the latest laravel framework.  We tested this first in 7.0.6, then 7.0.5, then 7.0.1.  Unloaded relationships will not return the proper result with empty.

**Comment by GrahamCampbell** [comment]
Well, since this is a PHP bug, it's upto PHP to fix it, just like when there are segfaults. Thanks for letting us know though.

**Comment by zachwills** [comment]
We are seeing this issue on a Laravel 4 project running PHP 7.0.16. I'm not 100% sure but it looks like maybe this was patched in 5.2, but since Laravel 4 wasn't patched with the update it is still breaking.

> PHP 7 has fixed a bug with __isset which affects both the native isset and empty methods. This causes specific issues with checking isset or empty on relations in Eloquent. In PHP 7 checking if a property exists on an unloaded relation, for example isset($this->relation->id) is always returning false because unlike PHP 5.6, PHP 7 is now checking the offset of each attribute before chaining to the next one. In PHP 5.6 it would eager load the relation without checking the offset. This change brings back the intended behavior of the core Eloquent model __isset method for PHP 7 so it works like it did in PHP 5.6.

Source: https://allmychanges.com/p/php/framework/
