### ISSUE TITLE
model binding default not found What Exception should be thrown?

### ISSUE THREAD

**Issue by henkpoldergraaf** [laravel/framework#13455]
// https://github.com/laravel/framework/blob/5.2/src/Illuminate/Routing/Router.php

    public function model($key, $class, Closure $callback = null)
    {
        $this->bind($key, function ($value) use ($class, $callback) {
            if (is_null($value)) {
                return;
            }
            // For model binders, we will attempt to retrieve the models using the first
            // method on the model instance. If we cannot retrieve the models we'll
            // throw a not found exception otherwise we will return the instance.
            $instance = $this->container->make($class);

            if ($model = $instance->where($instance->getRouteKeyName(), $value)->first()) {
                return $model;
            }

            // If a callback was supplied to the method we will call that to determine
            // what we should do when the model is not found. This just gives these
            // developer a little greater flexibility to decide what will happen.
            if ($callback instanceof Closure) {
                return call_user_func($callback, $value);
            }

            throw new NotFoundHttpException;
        });
    }

Could return a ModelNotFoundException instead of a NotFoundHTTPException. This can then be converted to a NotFoundHttpException in the render method of the ExceptionHander class if nothing was done with it. 

Why do I think this is better:
this method finds out whether or not the automatic model binding can be resolved to a actual model If NOT (and the user did not specify how to handle this case) it returns a NotFoundHttpException. It makes more sense to throw the error that specifies what went wrong (ModelNotFoundException) instead of the intent Exception (we might want to revere to a 404 http response, which could be the case but must not be the case, for instance in an Api context.)

**Comment by GrahamCampbell** [comment]
Feel free to send a PR to 5.3. ;)

**Comment by malhal** [comment]
I completely agree with this and so have implemented it in PR #14922 for 5.3
