### ISSUE TITLE
unique validation in sqlite.

### ISSUE THREAD

**Issue by AntyRace** [laravel/framework#13454]
Hi.

My validator formula:
`'email'      => ['required', 'email', 'unique:users,email'],`

My .env:
`APP_ENV=local
APP_DEBUG=true
APP_URL=http://localhost

DB_CONNECTION=sqlite`

Error:
`PDOException in Connector.php line 55: SQLSTATE[HY000] [2002] Connection refused

 in Connector.php line 55
at PDO->__construct('mysql:host=127.0.0.1;port=3306;dbname=homestead', 'homestead', 'secret', array('0', '2', '0', false, false)) in Connector.php line 55
at Connector->createConnection('mysql:host=127.0.0.1;port=3306;dbname=homestead', array('driver' => 'mysql', 'host' => '127.0.0.1', 'port' => '3306', 'database' => 'homestead', 'username' => 'homestead', 'password' => 'secret', 'charset' => 'utf8', 'collation' => 'utf8_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => null, 'name' => 'mysql'), array('0', '2', '0', false, false)) in MySqlConnector.php line 24
`
I don't know why, but laravel try to make connection for mysql. I was trying to trace this, but i can't find where validator get this. What i could found is in 'DatabasePresenceVerifier' getCount method. When I dump query in this function i get:

`
Builder {#225 ▼
  #connection: MySqlConnection {#221 ▼
    #pdo: Closure {#220 ▶}
    #readPdo: null
    #reconnector: Closure {#224 ▶}
    #queryGrammar: MySqlGrammar {#222 ▶}
    #schemaGrammar: null
    #postProcessor: MySqlProcessor {#223}
    #events: Dispatcher {#5 ▶}
    #fetchMode: 8
    #fetchArgument: null
    #fetchConstructorArgument: []
    #transactions: 0
    #queryLog: []
    #loggingQueries: false
    #pretending: false
    #database: "homestead"
    #doctrineConnection: null
    #tablePrefix: ""
    #config: array:12 [▼
      "driver" => "mysql"
      "host" => "127.0.0.1"
      "port" => "3306"
      "database" => "homestead"
      "username" => "homestead"
      "password" => "secret"
      "charset" => "utf8"
      "collation" => "utf8_unicode_ci"
      "prefix" => ""
      "strict" => false
      "engine" => null
      "name" => "mysql"
    ]
  }
`

Is it bug, or am I doingo something wrong ?

Regards
Anty

**Comment by GrahamCampbell** [comment]
Sorry, we don't process support requests here. Please try the forums.

**Comment by AntyRace** [comment]
Ok, I understand this. But still, i think, that database_path('database.sqlite') is not parsed in right way.

SQLiteConnector:

$path = realpath($config['database']);
dd(database_path('database.sqlite'), $path, $config['database']);

Gives:

`"/Users/antyrace/projects/test/database/database.sqlite"

false

"database_path('database.sqlite')"`

Regards
Anty

**Comment by AntyRace** [comment]
artisan migrate:refresh
Gives:

"/Users/antyrace/projects/test/database/database.sqlite"
"/Users/antyrace/projects/test/database/database.sqlite"
"/Users/antyrace/projects/test/database/database.sqlite"

Regards
Anty
