### ISSUE TITLE
The given data failed to pass validation

### ISSUE THREAD

**Issue by andrey-helldar** [laravel/framework#13466]
I run the command `php artisan make:auth`.

If you attempt to register a user, I have specially made mistakes in the entry form and get the following message:

> Illuminate \ Foundation \ Validation \ ValidationException
> The given data failed to pass validation.

> \vendor\laravel\framework\src\Illuminate\Foundation\Validation\ValidatesRequests.php
> Line 88: `throw new ValidationException($validator, $this->buildFailedValidationResponse(`

`     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Illuminate\Contracts\Validation\Validator  $validator
     * @return void
     *
     * @throws \Illuminate\Foundation\Validation\ValidationException
     */
    protected function throwValidationException(Request $request, $validator)
    {
        throw new ValidationException($validator, $this->buildFailedValidationResponse(
            $request, $this->formatValidationErrors($validator)
        ));
    }
 
    /**
     * Create the response for when a request fails validation.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  array  $errors
     * @return \Illuminate\Http\Response`

**[Screenshot here](https://yadi.sk/d/7tiZ0Au7rY2bK)**

I using Laravel 5.2.31, cleaning install.

In routes.php:

`Route::auth();`

**Comment by BlueTeck** [comment]
What was the solution?

**Comment by andrey-helldar** [comment]
Using `Auth::routes();`

**Comment by BlueTeck** [comment]
Thanks, unfortunately I have that already.

**Comment by DojoGeekRA** [comment]
Hi @BlueTeck , we faced a similar problem and this might be useful to you: https://github.com/GrahamCampbell/Laravel-Exceptions/issues/80#issuecomment-243487005

**Comment by lgalaz** [comment]
Doesn't this exception package require you to extend some other exception class?
Maybe a class which in turn extends from Laravels class.

At least that's the case with the packages I've used for this.
