### ISSUE TITLE
Envoy: Failed task within macro doesn't stop execution

### ISSUE THREAD

**Issue by ifeltsweet** [laravel/framework#13468]
Macros don't stop execution if one of the tasks returns non-zero code. I'm not sure if this is intended or not but for most of the use cases that I can think of this is not ideal.

If I have a deploy macro that needs to run a few tasks in sequence I would want each task to complete successfully before running the next one. Wouldn't you agree?

**Comment by JeroenVanOort** [comment]
Please provide an example.

**Comment by ifeltsweet** [comment]
How about one from Laravel's documentation:

```
@servers(['web' => '192.168.1.1'])

@macro('deploy')
    git
    composer
@endmacro

@task('git')
    git pull origin master
@endtask

@task('composer')
    composer install
@endtask
```

Composer task should not run if git task fails.

I actually found solution to this problem via:

```
@error
    echo "$task failed";
    exit(1);
@enderror
```

This satisfies my use case and if no one else is interested we can close this for now.
