### ISSUE TITLE
Inconsistent internal casing for classes with capital letters in succession

### ISSUE THREAD

**Issue by ethanclevenger91** [laravel/framework#13470]
Say I create two models in my app, something like `ABCClass` and something like `FooBar`. Next, I set up something like a one-to-many relationship - a `FooBar` has an `ABCClass` and an `ABCClass` may have several `FooBar`s.

Within `FooBar.php`:

```
public function abcClass() {
      return $this->belongsTo(\App\ABCClass::class);
    }
```

And `ABCClass.php`:

```
public function foobars() {
    return $this->hasMany(\App\FooBar::class);
}
```

So then I set up my migration. Note how I've snaked "ABCClass":

```
public function up()
    {
        Schema::create('a_b_c_classes', function (Blueprint $table) {
            $table->increments('id');
        });

        Schema::create('foo_bars', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('a_b_c_class_id')->unsigned();
            $table->foreign('a_b_c_class_id')->references('id')->on('months');
        });
    }
```

So now that I have these, I can make some new ABCClasses. Then create a new FooBar with the intent of assigning it to an ABCClass.

```
$foobar = new \App\FooBar;
$abcClass = \App\ABCClass::firstOrFail();
$abcClass->foobars()->save($foobar);
```

And this will work just fine. However, if I subsequently do:

```
var_dump($foobar->abcClass);
```

I'll get null.

Now in my original migration, let's say I had used an alternate snake case for `ABCClass`'s table:

```
public function up()
    {
        Schema::create('abc_classes', function (Blueprint $table) {
            $table->increments('id');
        });

        Schema::create('foo_bars', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('abc_class_id')->unsigned();
            $table->foreign('abc_class_id')->references('id')->on('months');
        });
    }
```

Set up some instances of `ABCClass` again and this time create a new `FooBar` and instead of using the relation function for assigning it to an `ABCClass`, do it manually so that we can test both:

```
$foobar = new \App\FooBar;
$foobar->abc_class_id = 1; //assuming an ABCClass with this id exists
$foobar->save();
var_dump($foobar->abcClass);
$abcClass = \App\ABCClass::find(2);
$abcClass->foobars()->save($foobar);
```

My var_dump will get me an object, but when I try to reassign my `FooBar` to another `ABCClass` I get:

```
Unknown column 'a_b_c_class_id' in 'field list' (SQL: update `foobars` set `a_b_c_class_id` = 2, `updated_at` = 2016-05-06 18:57:03 where `id` = 1)
```

Seems like the snake casing happening in the magic getter is different than the snake casing happening via the save method. 

If anyone can replicate this or shed some light on it, that'd be awesome. Digging deep enough, I found that `belongsTo` is using `Str::snake()`, but I couldn't manage to backtrace the magic relation methods.

Current workaround is to explicitly declare the name of the foreign key in my `belongsTo` call.

Laravel 5.2.29
PHP 7.0.5

**Comment by robclancy** [comment]
Why would you have a class with a name like that? I thought PSR-2 with acronmyns means you don't and I would assume Laravel does this "magic" guessing of tables etc using PSR-2 -> snake case?
