### ISSUE TITLE
Dont save in database if not in original

### ISSUE THREAD

**Issue by icfr** [laravel/framework#13477]
sometimes i need to store some value in model and if i need to store model in database it's throw an error that column doesn't exist ...

it's will be great to  have a column var and check if attribute exist in column and then save in database without attribute not in column

**Comment by Modelizer** [comment]
Eloquent has functionality to protect user from [Mass Assignment](http://stackoverflow.com/questions/22279435/what-does-mass-assignment-mean-in-laravel). I suggest you to use `fillable`.
