### ISSUE TITLE
Eloquent Update Method return model

### ISSUE THREAD

**Issue by fhb12345** [laravel/framework#13488]
Currently the update() method is returning the result of the save() (Boolean), on the other hand the create method is returning a model, shouldn't  the update method also return a model?

This way the update method keeps the fluent interface, also for a rest app for the put method you could just:

```php
return $model->update($request->all());
```
And the result would be a json of the updated model...

Is this worth changing?

**Comment by GrahamCampbell** [comment]
No, sorry. It also returns `false` is there were no changes made, so the return value has meaning already.

**Comment by fhb12345** [comment]
Actually it is returning ```true```

Get on localhost:8000/client/1

```json
{
  "id": 1,
  "name": "Ashly Lehner",
  "responsible": "Kristy Kuhn",
  "email": "tveum@example.com",
  "phone": "1-717-936-3681",
  "address": "2893 Deonte Inlet\nDevonberg, IL 38054",
  "obs": "Enim et eos voluptatem voluptas.",
  "created_at": "2016-05-09 12:48:13",
  "updated_at": "2016-05-09 12:48:13"
}
```

Content of the update() method:

```php
Client::find($id)->update($request->all());
```

For an empty PUT request (nothing is gonna change) the result is ``` true ```

For a PUT request with (name = current name):
```
name = Ashly Lehner
```
the result is also ``` true ```

For a PUT request with (name != current name):
```
name = Ashly Lehn
```
the result is also ``` true ```

I would expect to get a false on the empty PUT request and maybe a false when the request content is the same as the model content, both cases return true, it does return false if the model doesn't pass on a custom validation. 

Maybe this behavior is not implemented yet?
Also couldn't it return a model on success? (how bad would this be?)
