### ISSUE TITLE
Testing Forms and CSS selector

### ISSUE THREAD

**Issue by huglester** [laravel/framework#13489]
Hello,

is there a way to use CSS selectors white testing?
currently I can only ->press('Login'); 
but when I am, for example at Login form, I have somewhere in the menu also the 'Login' button.. so I need to click, for example ->press('form .submit-btn');

any way to achieve this?

Thank you!

**Comment by GrahamCampbell** [comment]
Please ask questions on the forums. Our GitHub issues are strictly limited to isolated bug reports.
