### ISSUE TITLE
Some weird issue with routes

### ISSUE THREAD

**Issue by omer414** [laravel/framework#13501]
**I have a system with multiple domains and subdomains.**

```
// TLD & Sub Domains Group 
    Route::group(['domain' => '{account}.{domain}.{suffex}'], function () {
        // Redirect to login page
        Route::get('/', function () {
            return redirect()->action('Core\LoginController@showLogin');
        });
        // Authentication links
        Route::get('login', ['middleware' => 'guest', 'uses' => 'Core\LoginController@showLogin']);
        Route::post('login', 'Core\LoginController@doLogin');
    });
```

**Everything works fine, but when i hit the '/' route. I get an error, "Missing required parameters for [Route: ] [URI: login].".**

But If i replace the action with a direct redirect it works fine.

            return redirect()->action('Core\LoginController@showLogin');
with 

            return redirect('login');

**Comment by JeroenVanOort** [comment]
First of all, this issue board is meant for bugs on the Laravel framework only, not for problems in your code. For the latter, you'd use the Laracasts forum.

Second, you should probably provide the account, domains and suffex (sic) variables for your route.
