### ISSUE TITLE
[5.2] artisan down --message

### ISSUE THREAD

**Issue by bsoliveira** [laravel/framework#13508]
https://laravel.com/docs/master/configuration#maintenance-mode

php artisan down --message='Upgrading Database' --retry=60
                                                          
  [Symfony\Component\Console\Exception\RuntimeException]  
**  The "--message" option does not exist.   **

**Comment by GrahamCampbell** [comment]
You are looking at the docs for Laravel 5.3, rather than 5.2. This feature is coming up in Laravel 5.3. ;)
