### ISSUE TITLE
Terminable middleware terminates before response is returned PHP 7

### ISSUE THREAD

**Issue by JornEngelbart** [laravel/framework#13503]
When using a terminable middleware with Laravel v5.2.30 and PHP 7 it seems that the response is returned after the terminate function is called. This shouldn't be the case according to the specification.

**Comment by GrahamCampbell** [comment]
Yes, this is correct.

**Comment by GrahamCampbell** [comment]
It'll be the same on PHP 5 too. Only Laravel 4 worked the other way.

**Comment by JornEngelbart** [comment]
@GrahamCampbell This is correct behaviour?
