### ISSUE TITLE
Passing a primitive parameter in a Policy from a middleware.

### ISSUE THREAD

**Issue by dionysiosarvanitis** [laravel/framework#13516]
Is it possible to pass a route parameter in a Policy when it is resolved via a middleware? As I can see, this is possible only when the whole object is type hinted in the corresponded controller. This could be useful when a `destroy(User user, $id)` policy method should be called, instead of a `destroy(User user, Photo $photo)`, eliminating the need of the extra query.

PhotoController:
```php
public function destroy(Request $request, $id){
  //
}
```
PhotoPolicy:
```php
public function destroy(User $user, $id) {
  $id === 'App\Models\Photo' //true
}
```

routes:
```php
Route::delete('photo/{id}', [
  'middleware' => 'can:destroy,App\Models\Photo',
  'uses' => 'PhotoController@destroy',
  'as' => 'photo.destroy'
]);
```

The code in the example above returns App\Models\Photo for $id. Link below is the point of interest.

https://github.com/laravel/framework/blob/70f75255808ffc96275e6f2f356616dd2e163434/src/Illuminate/Auth/Access/Gate.php#L244

**Comment by GrahamCampbell** [comment]
Thank you, but we politely request that you use the forums for this sort of thing.

**Comment by dionysiosarvanitis** [comment]
Yes, you're right..
