### ISSUE TITLE
[5.1] Usage of view startSection and stopSection

### ISSUE THREAD

**Issue by eusonlito** [laravel/framework#13518]
Code used in Laravel 5.0 controller:

```php
$view->getFactory()->startSection('articles-actions-bar', view()
    ->make('web.pages.sellers._articles-actions-bar-buttons')
    ->with(['user' => $user]));

$view->getFactory()->stopSection();

return $view;
```

Now it doesn't work because stopSection checks a variable called `$this->sectionStack` that is empty when `startSection` has contents:

* startSection: https://github.com/illuminate/view/blob/5.1/Factory.php#L517
* stopSection: https://github.com/illuminate/view/blob/5.1/Factory.php#L561

I know that I can do it from Balde template:

```
@extends('web.layouts.html')

@section ('articles-actions-bar')
    @include('web.pages.sellers._articles-actions-bar-buttons')
@endsection

@section('body')
```

But wow can I do it from Controller? Thanks.

**Comment by GrahamCampbell** [comment]
Please feel free to ask questions on the forums. ;_)

**Comment by eusonlito** [comment]
Ok, wasn't a question, I think that does not work as expect, but ok :)

**Comment by eusonlito** [comment]
Explain my check:

1. `startSection` allow a `$content` as second parameter. If `$content` has a value, next step is `extendSection` and `$this->sectionStack` stay empty.
2. `$this->sectionStack` only can has value if `startSection` does not receive the `$content` parameter.
3. `stopSection` check at first if `$this->sectionStack` has contents. If not, throw an exception.

Resolution: If `startSection` receive a second parameter, `stopSection` can not be called.
