### ISSUE TITLE
Generated Foreign Key name to long.

### ISSUE THREAD

**Issue by chilion** [laravel/framework#13512]
I got the following error while trying to create a foreign key. I can of course give it my own name, but I would like to think that when its auto generated Laravel would come up with a trimmed name when exceeding the maximum length.

```
[Illuminate\Database\QueryException]
 SQLSTATE[42000]: Syntax error or access violation: 1059 Identifier name 'xxxxxx_xxxxxxxxxx_xxxxx_xxxxxxxxxxx_xxxxxxxxxx_xxxxxxxxxx_xx_xxxxxxx' is too long (SQL: alter table `xxxxxx_xxxxxxxxxx_xxxxx` add constraint `xxxxxx_xxxxxxxxxx_xxxxx_xxxxxxxxxxxx_xxxxxxxxx_xxxxxxxxxx_xx_xxxxxxx` foreign key (`xxxxxxxxxxx_xxxxxxxxxx_xxxxxxxxxx_xx`) references `xxxxxxxxxxx_xxxxxxxxxx_xxxxxxxxxx` (`xx`) on update cascade)
```

**Comment by JeroenVanOort** [comment]
I have had this problem too. The thing is, that the key name has to be unique, so it can't be simply trimmed at the required length. What do you think should happen instead?

**Comment by chilion** [comment]
Maybe something with the table names and the microseconds or something like that? I know, fugly, but atleast automated.

**Comment by ameliaikeda** [comment]
This is more of a DBMS error than a Laravel error, i'd say; a 68 character key is pretty impressive to hit and the limit is database-specific.

The solution here is just to provide your own index name; Laravel generates a readable key like so:

```php
/**
 * Create a default index name for the table.
 *
 * @param  string  $type
 * @param  array   $columns
 * @return string
 */
protected function createIndexName($type, array $columns)
{
    $index = strtolower($this->table.'_'.implode('_', $columns).'_'.$type);

    return str_replace(['-', '.'], '_', $index);
}
```

**Comment by chilion** [comment]
As I said, I know Laravel does this. I just want it to not happen when it hits the limit.
