### ISSUE TITLE
Auth::user() is null on 404 exception?

### ISSUE THREAD

**Issue by rummykhan** [laravel/framework#13517]
I was logging the exception when the user is also logged in, but as the exception is thrown i tried to see the logged in user.

```
public function report(Exception $e)
    {
        var_dump(Auth::user());
        return parent::report($e);
    }
```

But it was NULL,
is it by design? if it is then is there any alternative please? or i've to do it my way.?
thanks

**Comment by GrahamCampbell** [comment]
This is happening because you must have the auth middleware processing after routing is processed.

**Comment by GrahamCampbell** [comment]
In other words, what this means is routes are matched (or not), and then we'd check the session and login stuff, so when the not found exception is raised, we've not read the session at that point.

**Comment by GrahamCampbell** [comment]
Since this is not a bug, and merely a usage question, I politely request that you seek advice on the forums.

**Comment by uisumo** [comment]
I solved this with Laravel 5.5 'fallback' route

I added this code in '**routes\web.php**' file

``
Route::fallback(function(){
	return response()->view('errors.404', [], 404);
});
``

**Comment by endrureza** [comment]
@uisumo yours is the working one for me. thanks

**Comment by IndiFFer3nT** [comment]
@uisumo Thank you very much man! I've been searching a lot about this problem and your answer fixes it all!
