### ISSUE TITLE
Artisan::queue not working

### ISSUE THREAD

**Issue by ohid** [laravel/framework#13523]
I have a artisan command signature named 'import:excelfile'

I want to run that command inside my controller. Everything is working fine in my controller. But the Artisan::queue('import:excelfile') is not running from controller. But its running from CLI perfectly. Where's the problem?

Please look at my codes

controller method code 
http://pastebin.com/45dj179H

artisan code
http://pastebin.com/zNCtQKZ0

Thanks

**Comment by JeroenVanOort** [comment]
Please ask your question in one of the support fora like Laracasts. This issue board is meant to be used for Laravel bugs, not for implementation issues.

**Comment by ohid** [comment]
Oh sorry, But I don't have a laracasts account. 
So should I close this issue?
