### ISSUE TITLE
Typehint DateTimeInterface for serializeDate() in Eloquent Model

### ISSUE THREAD

**Issue by kcjpop** [laravel/framework#13528]
Hi, I'm using 5.2 and want to replace Carbon with Chronos. So far I can extend the base `Illuminate\Database\Eloquent\Model` to make the idea work. But then `serializeDate()` typehints the concrete class `DateTime` and therefore it's not possible to use Chronos instances.

I wonder if we could change 

```php
    protected function serializeDate(DateTime $date)
```

into

```php
    protected function serializeDate(DateTimeInterface $date)
```

for better customization?

**Comment by GrahamCampbell** [comment]
Feel free to send a PR to 5.3. ;)

**Comment by kcjpop** [comment]
Will do : )
