### ISSUE TITLE
Inject parent model to childs when loading one-to-many relations

### ISSUE THREAD

**Issue by vedmant** [laravel/framework#13521]
Hi, I'm interested is there a way to keep parent model loaded in child models after loading one-to-many relationship.

What I mean is for example we have Post and Comment models. Post have many comments relationship and Comment has parent belongs to post relationship. When I loop through comments like $post->comments as $comment, and then trying to access $comment->post->some_field it will make new query, if there are many loops like this it generates hundreds of not needed queries.

It will be cool feature if it can inject parent model into child model parent relationship, this can be optional, specified in relation something like:

    /**
     * Get the comments for the blog post.
     */
    public function comments()
    {
        return $this->hasMany('App\Comment')->inject('post', $this);
    }

This also might be used for any other purposes when you need to inject some variable to resulted models collections after some query. Like Post::where('user_id', $user->id)->inject('user', $user);

Thanks!

**Comment by ferrl** [comment]
Since you are in a loop through `$post->comments` and have access to the `$post`, maybe you could try using the `$post` variable itself, instead of `$comment->post`.

**Comment by vedmant** [comment]
It was just an example, sometimes there are more complex things, like when you pass single $comment to some job, event, so on, and then you need to access parent post. Passing additional variable everywhere will make code less readable and beautiful.

**Comment by absolux** [comment]
I think that the injection should be done in `Relation->match()` or `Relation->matchMany()` for eager loading

**Comment by absolux** [comment]
Or you can use `Model->setRelation()` to inject, for example, the user into the post

**Comment by shadoWalker89** [comment]
like @ferrl said if you are in a lopp then you have access to the parent post.

But if you are making the query on the comments, then you can just eager load the posts

```php
Comment::with('post')->get()
```
