### ISSUE TITLE
[5.2] \Log::info() and info() triggered to many times

### ISSUE THREAD

**Issue by rogervila** [laravel/framework#13539]
Hello,

I have an almost fresh install of **lararavel 5.2**.

When I add a `\Log::info()` or an `info()` method at `routes.php` **it logs 5 times in every request**.

We have discussed it in Larachat but nobody seems to find a response to this problem.

Thank you.

**Comment by GrahamCampbell** [comment]
Sorry, but this is an application bug rather than a framework bug, and thus we cannot process it here.

**Comment by rogervila** [comment]
@GrahamCampbell in what repo should I open it? Thank you!

**Comment by GrahamCampbell** [comment]
I can't verify this as a bug in our code, sorry. I'd suggest you seek advice on the forums on how to fix your app code.
