### ISSUE TITLE
Multiple factories not resetting each time

### ISSUE THREAD

**Issue by SteveEdson** [laravel/framework#13534]
In my seeder I'm calling a factory on a class multiple times. Each time, I only create 1 new model, however, my `->each()` function is carrying across models created from the previous calls.

E.g.

```php
factory(App\Team::class, 1)->create([
   'name' => 'Mercedes'
])->each(function($team) {
    echo "Factory 1. Created team " . $team->name . "\n";

    $team->drivers()->create(factory(App\Driver::class)->make(['name' => 'Lewis Hamilton', 'type' => 'primary'])->toArray());
    $team->drivers()->create(factory(App\Driver::class)->make(['name' => 'Nico Rosberg', 'type' => 'primary'])->toArray());
});

factory(App\Team::class, 1)->create([
   'name' => 'McClaren'
])->each(function($team) {
    echo "Factory 2. Created team " . $team->name . "\n";

    $team->drivers()->create(factory(App\Driver::class)->make(['name' => 'Jenson Button', 'type' => 'primary'])->toArray());
    $team->drivers()->create(factory(App\Driver::class)->make(['name' => 'Fernando Alonso', 'type' => 'primary'])->toArray());
});
```

> Factory 1. Created team Mercedes
Factory 2. Created team Mercedes
Factory 2. Created team McClaren

Using v5.2.31

**Comment by GrahamCampbell** [comment]
I don't see how this can be happening. It sounds more like a bug in your code. Feel free to discuss on the forums, and come back here if you have really small case that we can reproduce on a stock app.

**Comment by SteveEdson** [comment]
Just managed to replicate the issue on a fresh install using `laravel new test`:

## Model Factory:

```php
$factory->define(App\Team::class, function (Faker\Generator $faker) {
    return [
        'name' => $faker->word,
        'primary_colour' => $faker->hexColor
    ];
});
```

## DatabaseSeeder.php
```php
    public function run()
    {
        $this->call(TeamSeeder::class);
    }
```

## Migration (SQLite)

```php
        Schema::create('teams', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->string('primary_colour');
            $table->timestamps();
        });
```

## Model

```php
class Team extends Model
{
    //
}
```

## Team Seeder

```php
class TeamSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        factory(Team::class, 1)->create()->each(function() {
            echo "Seeder 1";
        });

        factory(Team::class, 1)->create()->each(function() {
            echo "Seeder 2";
        });
    }
}
```

# Output

> Seeder 1Seeder 2Seeder 2Seeded: TeamSeeder

Also worth noting, each time I run the seeder:

> ~/Repos/ltest  art db:seed
Seeder 1Seeder 1Seeder 1Seeder 2Seeder 2Seeder 2Seeder 2Seeded: TeamSeeder
 ~/Repos/ltest  art db:seed
Seeder 1Seeder 1Seeder 1Seeder 1Seeder 1Seeder 2Seeder 2Seeder 2Seeder 2Seeder 2Seeder 2Seeded: TeamSeeder

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell

**Comment by JosephSilber** [comment]
This is not a bug. Calling `create` witha single model does not return a collection; it return the model instance. A model doesn't have an `each` method, so it delegates to the builder.

Just don't call `each` here. It's wrong.
