### ISSUE TITLE
Model::toArray breaks with nullable timestamps 

### ISSUE THREAD

**Issue by nicolacimmino** [laravel/framework#13530]
If a Model instance has null timestamps converting to array will fail.

The culprit is in Model::asDateTime that end up falling all the way through to return Carbon::createFromFormat($this->getDateFormat(), $value); with $value null.

**Comment by GrahamCampbell** [comment]
> If a Model instance has null timestamps converting to array will fail.

Could you be more specific please. Could you also please provide your laravel version.

**Comment by nicolacimmino** [comment]
Laravel 5.1

If you have a model that has a timestamp field and an instance has that field "null" or "0000-00-00 00:00:00" (both valid datetime field values) calling modelInstance->toArray() will throw an exception.

The problem is in Model::attributesToArray which ends up calling $this->serializeDate(null)

**Comment by billmn** [comment]
Hi @nicolacimmino, I have used this code with Laravel 5.1.37 (LTS):

```php
Route::get('/', function () {
    $user1 = App\User::first();
    $user1->created_at = null;

    $user2 = App\User::find(11);

    dd($user1->toArray(), $user2->toArray());
});
```

This is some example data:
![schermata 2016-06-06 alle 22 04 56](https://cloud.githubusercontent.com/assets/779534/15835948/c348b8d6-2c32-11e6-9d53-3fc9e7b4491a.png)

And this is the result:
![schermata 2016-06-06 alle 22 06 40](https://cloud.githubusercontent.com/assets/779534/15835998/fc965864-2c32-11e6-856a-a827fc551dd3.png)

No exceptions here.

**Comment by Artistan** [comment]
Hey @nicholasruunu .  Thanks for the heads up on the attributesToArray!

I created a trait as a package including 288 testing assurances that allow the date to work properly for many combinations of `->attribute` vs `->toArray` matching against combinations of casts, dates, and mutators for those attributes.  Check it out and let me know what you think.

https://github.com/Artistan/zero-nullable-dates
