### ISSUE TITLE
Method [validateDimensions] does not exist.

### ISSUE THREAD

**Issue by rdehnhardt** [laravel/framework#13541]
I am using laravel 5.2 and this method is not present in the Illuminate \Validation\Validator class.

But I picked up the repository, and the method in this class.

My composer:

"require": {
    "php": ">=5.5.9",
    "laravel/framework": "5.2. *"
},

But even making a lot updates and reinstalling everything is not updating the code.

**Comment by GrahamCampbell** [comment]
This has not been included in a tagged release yet. It'll be available in the next 5.2.x tag.
