### ISSUE TITLE
SparkPost doesn't send attachments

### ISSUE THREAD

**Issue by bobbybouwmann** [laravel/framework#13546]
Hi,

As many other developers I migrated my application from Mandrill to SparkPost. Never had any issues with Mandrill, but I can' t send attachments.

I have a bit of example code here, but that is straight forward with Laravel. This does work with Mandrill, Mailgun, and the SMTP drivers. However SparkPost send the email, but forgets the attachments.
```
Route::get('test/mail', function () {
        Mail::send('emails.test', [], function ($message) {
		$message->to('email@domain.com')
			->subject('Test mail')
			->attach(storage_path('files') . '/' . 'somefile.pdf', ['as' => 'Some File']);
	});

	return 'Done';
});
```

I also have a support ticket open at SparkPost, but this can be an issue with Laravel or SparkPost...

Is this a known issue?

**Comment by Nekudapsik** [comment]
New laravel version (5.4.31) and especially this commit 3d9e502099e5c5ecf32553d280ef1a273103ad71 broke SparkPost driver ability to send attachments. I reverted the changes to old version:
~~~php
                'content' => [
                    'email_rfc822' => $message->toString(),
                    // 'html' => $message->getBody(),
                    // 'from' => $this->getFrom($message),
                    // 'subject' => $message->getSubject(),
                ],
~~~
and it worked well.

My workaround for now is to rollback to previous version of laravel framework 
~~~
composer require "laravel/framework:5.2.30"
~~~

**Comment by GrahamCampbell** [comment]
@taylorotwell

**Comment by bobbybouwmann** [comment]
@Nekudapsik This indeed fixes the issue for now. I will look into this when I have some free time today ;)

**Comment by taylorotwell** [comment]
I don't use SparkPost. I will need the community to maintain that driver by sending a PR to fix the issues.

**Comment by bobbybouwmann** [comment]
@taylorotwell This #13237 PR seems to break the functionality for attachments. I think the best way right now is to revert the changes so it doesn't break current installations and then we can look into a new implementation. What do you think?

**Comment by billmn** [comment]
I'll take a look ...

**Comment by tillkruss** [comment]
This can be closed now.
