### ISSUE TITLE
[REQUEST] ->withSuccesses();

### ISSUE THREAD

**Issue by LasseRafn** [laravel/framework#13545]
Any idea of ever implementing a functionality to allow us to handle success messages the same way errors are dealt with?

Like this:
````
@if($successes->count() > 0)
	@foreach($successes->all() as $success)
		{{ $success }}
	@endforeach
@endif
````

"successes" could have another name though.

I know that you could make your own method for doing so, or even create a similar implementation and use that. There might even be libraries that does this, but I still see it as a thing that the framework could handle by default. Just like you handle errors, you will usually handle successes too. ("You successfully created an account" - for example)

Again, I know that you can do it simply by doing:

Controller
````
...
return Redirect::to('some-site')->with('success', 'Done!');
...
````

View
````
@if( session('success') )
	{{ session('success') }}
@endif
````

But a function like ->withSuccesses([ 'Done!' ]); would be so much easier and way prettier (+ allow autocompletion in the IDE)

———

I **know** that this question has been asked before, but I decided to give it a shot again.
- However, I couldn't find any other "issues" regarding this.

**Comment by fhb12345** [comment]
@LasseRafn 

It would be useful sometimes but you can still achieve the same results currently so i don't think that this will be created unless it adds a feature that is missing today. After all this would just be a different syntax.

We could however create a handler for response messages in general, that would classify them: success, error, warning, info, etc.  And have specific functions for querying through them, like priority or something like that we could even sum up more features to it but this need a deeper look...

**Comment by dwightwatson** [comment]
The redirector actually supports dynamic withs, so you could do `withSuccess('Done')` or `withSuccesses(['Done'])` and access them from the session as `success` and `successes`.

**Comment by LasseRafn** [comment]
What?! How can they have thought of every little detail... I love Laravel.

Thanks! :o)

**Comment by mustafaaloko** [comment]
@GrahamCampbell, if this is solved, why is it open till now?

**Comment by GrahamCampbell** [comment]
@mustafaaloko Because @LasseRafn didn't cose it?
