### ISSUE TITLE
Wildcard subdomains routing doesn't run when accessed as a C Name Record on a different domain

### ISSUE THREAD

**Issue by ChampRay** [laravel/framework#13542]
If I have a application that has wildcard subdomains enabled, the routing for subdomain will not actually trigger if the subdomain is a CName record for the DNS of another domain.

The subdomain routing works fine if i use ray.myapp.com

The subdomain routing does not work if www.rayswebsite.com uses it's "www" record as a cname to ray.myapp.com ( this will just show the page as if there was no subdomain being accessed )

**Comment by sger** [comment]
Please post an example of your code maybe something like the following:

Route::group(array('domain' => '{account}.myapp.com'), function() {
});

**Comment by GrahamCampbell** [comment]
Feel free to discuss on the forums, and post a new issue once you have a small reproducible case.

**Comment by ChampRay** [comment]
I'm pretty sure their is only one way to setup the wildcard domains in laravel, the code is pretty irrelevant I would assume, but anyways.. i'll show you it anyways.

 `
Route::group(['domain'=>'{forum}.mistforums.com'], function($forum) {
    Route::group(['middleware' => ['web', 'admin'], 'namespace' => 'Forum'], function () {
        Route::get('/admin', ['as' => 'admin.index', 'uses' => 'AdminController@index']);

        Route::resource('category', 'CategoryController', ['except'=>'show']);
        Route::resource('bracket', 'BracketController');
        Route::resource('role', 'RoleController');
        Route::resource('theme', 'ThemeController');
        Route::resource('module', 'ModuleController');

        Route::resource('role', 'RoleController');

        Route::get('/thread/{thread}/move/{category}', ['as'=>'thread.move', 'uses'=>'ThreadController@move']);
        Route::get('/thread/{thread}/hide', ['as'=>'thread.hide', 'uses'=>'ThreadController@hide']);
        Route::get('/thread/{thread}/sticky', ['as'=>'thread.sticky', 'uses'=>'ThreadController@sticky']);
        Route::get('/thread/{thread}/locked', ['as'=>'thread.locked', 'uses'=>'ThreadController@locked']);

        Route::put('update', ['as' => 'forum.update', 'uses' => 'ForumController@update']);
    });


    Route::group(['middleware' => ['web', 'api'], 'namespace' => 'Forum'], function () {
        Route::get('api/query', ['as'=>'api.query', 'uses'=>'ApiController@query']);
        Route::get('api/account', ['as'=>'api.account', 'uses'=>'ApiController@account']);
        Route::put('api/update', ['as'=>'api.update', 'uses'=>'ApiController@update']);
        Route::get('api/ban', ['as'=>'api.ban', 'uses'=>'ApiController@ban']);
    });


    Route::group(['middleware' => ['web', 'require-auth'], 'namespace' => 'Forum'], function () {
        Route::get('thread/create/{category}', ['as' => 'thread.create', 'uses' => 'ThreadController@create']);
        Route::post('thread', ['as'=>'thread.store', 'uses'=>'ThreadController@store']);

        Route::get('post/create/{thread}', ['as' => 'post.create', 'uses' => 'PostController@create']);
        Route::post('post', ['as'=>'post.store', 'uses'=>'PostController@store']);

        Route::resource('comment', 'CommentController');
    });

    Route::group(['middleware' => 'web', 'namespace' => 'Forum'], function () {
        Route::get('/', ['as' => 'forum.welcome', 'uses' => 'ForumController@index']);
        Route::get('/members', ['as' => 'forum.members', 'uses' => 'PageController@members']);

        Route::get('/steamlogin', ['as' => 'forum.steamlogin', 'uses' => 'Auth\AuthController@login']);
        Route::get('/login', ['as' => 'forum.login', 'uses' => 'Auth\AuthController@showLoginForm']);
        Route::get('/logout', ['as' => 'forum.logout', 'uses' => 'Auth\AuthController@logout']);

        Route::resource('category', 'CategoryController', ['only'=>'show']);

        Route::resource('user', 'UserController');

        $modules = Module::all();

        foreach ( $modules as $module ) {
            $config = $module->getConfig();

            if ( isset( $config['routes'] ) ) {
                $config['routes']();
            }
        }

        Route::post('module/sync', ['as' => 'module.sync', 'uses' => 'ForumController@moduleSync']);

        Route::resource('thread', 'ThreadController', ['except' => ['create', 'store']]);

        Route::delete('role/{user}/{role}/delete', ['as' => 'role.user.delete', 'uses' => 'RoleController@userDelete']);
        Route::post('role/{role}/add', ['as' => 'role.user.add', 'uses' => 'RoleController@userAdd']);

        Route::put('update', ['as' => 'forum.update', 'uses' => 'ForumController@update']);

        Route::resource('post', 'PostController', ['except' => ['create', 'store']]);

        Route::resource('gameservers', 'GameServerController');
    });
});


// regular

Route::group(['middleware' => 'web'], function () {
    Route::get('/', ['as' => 'welcome', 'uses' => 'PageController@welcome']);
    Route::get('/pricing', ['as' => 'pricing', 'uses' => 'PageController@pricing']);
    Route::get('/contact', ['as' => 'contact', 'uses' => 'PageController@contact']);

    Route::post('email', ['as'=>'email.store', 'uses'=>'EmailController@store']);
    Route::post('email/contact', ['as'=>'email.contact', 'uses'=>'EmailController@contact']);

    Route::get('payment/ipn', ['as' => 'payment.ipn', 'uses' => 'PaymentController@ipn']);
});`

**Comment by sger** [comment]
@ChampRay ask the forum.

**Comment by ChampRay** [comment]
https://laracasts.com/discuss/channels/laravel/wildcard-subdomains-routing-doesnt-run-when-accessed-as-a-c-name-record-on-a-different-domain
