### ISSUE TITLE
laravel 5.2 session/cookie issue

### ISSUE THREAD

**Issue by niculescudragos** [laravel/framework#13543]
Hello,

i'm having a problem with a fresh laravel 5.2 install. When implementing the authentication system (not using Route::auth() - i'm implementing my own Auth controller) i always get a CSRF token mismatch exception.

I disabled the VerifyCsrfToken middleware so i can debug. The error that i'm facing is that after each login POST request (normal HTTP post not AJAX) the cookie data from the request object that contains the session ID is set to null. This causes laravel to start a new session. I am using the database driver for both session and cache.

It seems that the problem lies in the decrypt method of the EncryptCookies middleware. When looping through the request cookies, somehow there are 2 cookies setup on the request object with the same name - both representing the session id cookie) - first one has the correct value, the second one does not and generates this error.

PS: before performing the test i've always cleared the browser cache/cookies, truncated the session and cookie tables in mysql.

Here is the debug sequence and output: http://kopy.io/A4036

**Comment by GrahamCampbell** [comment]
Thanks but this probably isn't a core bug. Feel free to discuss on the forums.

**Comment by niculescudragos** [comment]
Yeap, user problem... 

Figured out what lead to this: the web middleware is included by default for all routes via the RouteServiceProvider and my routes were declared under the web middleware. So the decrypt method was getting called twice, of course the 2nd call failed since the values were already decrypted.
