### ISSUE TITLE
Migration + Eloquent Model naming convention

### ISSUE THREAD

**Issue by jrean** [laravel/framework#13559]
Hi,

By default `php artisan make:model Xxx -m` for `Foo` and `Bar` will create both the migration and the model files:
- xxxx_xx_xx_xxxxxx_create_foos_table.php
- xxxx_xx_xx_xxxxxx_create_bars_table.php
- App\Foo.php
- App\Bar.php

Apply the same logic for a pivot table, `php artisan make:model FooBar -m` will create both the migration and the model files. We can delete the model file. (The purpose of using the php artisan command was just to see how Laravel handles the naming)
- xxxx_xx_xx_xxxxxx_create_foo_bars_table.php

Now, into both `Foo` & `Bar` models if we define a `belongsToMany` relationship it will assume the `pivot table name` is singular `foo_bar` and not `foo_bars` as stated by default into the migration file created by the artisan command.

Of course, into the relationship definition, one can define the table name.

**Why such a behaviour? Is it wanted?**
If by default the relation expect a singular table name why the artisan command creates a plural one? Vice-versa.

**Comment by lagbox** [comment]
Because the command has no clue that you are creating a pivot table. The command you are running is asking it to make a model and a migration, and therefore is doing what it is supposed to be doing.

**Comment by jrean** [comment]
@lagbox you didn't read properly my comment. I know that. I'm talking about default behaviour:

> If by default the relation expect a singular table name why the artisan command creates a plural one? Vice-versa.

**Comment by lagbox** [comment]
Again ... because it doesn't know you are creating a pivot table. Therefore its following the normal naming convention for models and tables. It doesn't know about the relationship you intend on creating or that you are intending on creating a pivot table.

**Comment by jrean** [comment]
I'm not talking to know or to not know about a pivot table. Artisan command makes the table name `foo_bars` plural and the relation method expect the table name to be singular `foo_bar` by default. It's more a question about naming convention and why, out of the box, it won't work (event if as you mention there are plenty of ways to make it works...)

**Comment by lagbox** [comment]
I have already explained why twice.

**Comment by jrean** [comment]
So let me modify my question:
Don't you think the relation method default behavior should expect a plural name? If no, can you please explain as I'm interested to understand the why of the choice.

Thank for explaining "why" twice.
