### ISSUE TITLE
Bug in $this->authorize('store', App\Item::class, $foo);

### ISSUE THREAD

**Issue by misog** [laravel/framework#13550]
Hi, have this method in ItemPolicy:

```
public function store(User $user, $item_class, Foo $foo)
{
```

When called `$this->authorize('store', App\Item::class, $foo);` the last, third parameter Foo $foo is not passed:

```
Argument 3 passed to App\Policies\ItemPolicy::store() must be an instance of App\Foo, none given
...
at ItemPolicy->store(object(User), 'App\Item')
...
```

When called in this form, it works: `$this->authorize('store', [App\Item::class, $foo]);`

I was writing [related issue](https://github.com/laravel/internals/issues/88) at laravel/internals and found this bug.

**Comment by themsaid** [comment]
AFAIK that's how it works, you may pass 1 argument or an array of arguments that'll be passed to the method.

From the docs:
> If your ability needs multiple arguments, simply pass an array of arguments to the Gate methods:

https://laravel.com/docs/5.2/authorization#checking-abilities
