### ISSUE TITLE
Helper e() not behaving properly

### ISSUE THREAD

**Issue by AdamEsterle** [laravel/framework#13552]
e() calls this:
 return htmlentities($value, ENT_QUOTES, 'UTF-8', false);

I think 4th argument should be TRUE (which is the default for htmlentities)

Currently with false: `&lt;` is shown as `<`
With true: `&lt;` displays as `&lt;`

Can someone please inform if I am missing the reason why it is set to false?

Is it preference?
I noticed Facebook chat displays `&lt;` displays as `&lt;`
but GitHub displays `&lt;` is shown as `<`

**Comment by AdamEsterle** [comment]
&lt;

**Comment by GrahamCampbell** [comment]
It's just a preference. Feel free to use a different function if you would like. Feel free to discuss on forums/slack.

**Comment by rudiedirkx** [comment]
It should definitely be TRUE. Unfortunately other packages use this function, which breaks normal HTML.

@AdamEsterle Github uses Markdown, which supports HTML, so `&lt;` is correctly displayed as `<`. For a function that encodes HTML, this is definitely wrong. If this option is neccesary, there's double encoding in other places. Ths is just lazy.
