### ISSUE TITLE
Unexpected behavior from Request::fulUrlWithQuery: Trailing separator

### ISSUE THREAD

**Issue by belisarh** [laravel/framework#13561]
Hello,

Having the following full URL present:

`http://myapp.dev/search?q=something+here`

adding a query parameter vie the fullUrlWithQuery eg. `['page' => 5]` should result in the following:

`http://myapp.dev/search?q=something+here&page=5`

results in:

`http://myapp.dev/search/?q=something+here&page=5`

Notice the trailing path separator after search and before the query string starts.

The expected behavior can be achieved by changing the Request::fulUrlWithQuery from:

```PHP
<?php

    public function fullUrlWithQuery(array $query)
    {
        return count($this->query()) > 0
                        ? $this->url().'/?'.http_build_query(array_merge($this->query(), $query))
                        : $this->fullUrl().'?'.http_build_query($query);
    }
```

to:

```PHP
<?php

    public function fullUrlWithQuery(array $query)
    {
        return count($this->query()) > 0
                        ? $this->url().'?'.http_build_query(array_merge($this->query(), $query))
                        : $this->fullUrl().'?'.http_build_query($query);
    }
```

Is there a specific reason of why the trailing separator is placed there or can this just be changed to get to the expected behavior?

**Comment by GrahamCampbell** [comment]
Thanks, but this is not actually a bug. We have a test to ensure we don't change this behaviour.
