### ISSUE TITLE
Implicit join using relations

### ISSUE THREAD

**Issue by salarmehr** [laravel/framework#13563]
Almost always join methods are around model relations. Is there any change to merge a commit that adds [this ](http://laravel-tricks.com/tricks/automatic-join-on-eloquent-models-with-relations-setup)to core framework? e.i. `User::relate('roles')` similar to `User::with('roles')` but does a real join.

**Comment by GrahamCampbell** [comment]
Thanks, but please direct questions to the forums.

**Comment by salarmehr** [comment]
@GrahamCampbell It's not a question about using laravel. I want to know if I create a commit that add the explained functionality, will it be merged?

**Comment by GrahamCampbell** [comment]
Please read our contribution guidelines regarding the correct place to discuss additions/changes.
