### ISSUE TITLE
Eloquent HasOneOrMany relation update() method not using mass-assignment rules

### ISSUE THREAD

**Issue by yurtesen** [laravel/framework#13568]
I realized that when I run my query with updateOrCreate() method I am getting mass-assignment error which is fine because the array I am trying to assign contains values which are not defined as fillable. ($fillable is an empty array)

However, if I use update() method it updates the row without any complaints, ignoring the fillable/hidden fields. I believe this is because update is not using the fill() method.

I think this is a bug because I can pass an array to the update() function from a form, for example updating user details and the user can put extra fields to it. This is exactly what the mass-assignment rules are but update() method does not obey the rules.

Tested on Laravel 5.2

**Comment by sger** [comment]
@yurtesen update() method is fillable look here https://github.com/illuminate/database/blob/master/Eloquent/Model.php#L436

**Comment by yurtesen** [comment]
You are right, but I think I should have given more info. Because that is never called in my case (as far as I can tell).

I have 2 tables, 'users' and 'activation_tokens', each user can have 1 token. So User model has
```

    public function ActivationToken()
    {
        return $this->hasOne(ActivationToken::class);
    }
```

I am updating the token with the following line of code:

`            $user->ActivationToken()->update(['token' => $this->getNewTokenString()]);`

That line updates the token perfectly but the update fails with mass assignment exception if I use the following:

`            $user->ActivationToken()->updateOrCreate(['token' => $this->getNewTokenString()]);`

I tried to follow what is happening, first Eloquent\Relations\HasOneOrMany,php's update() function is called, this calls update in Eloquent\Builder.php from there it goes to Illuminate\Database\Query\Builder.php's update() method, from there to Connection.php and run the update query and does not do any filling whatsoever.... If I understood it correctly :) on the other hand updateOrCreate() tries to create an instance and fill() it. 

Am I wrong? it does not call fillable in this situation?

**Comment by lagbox** [comment]
Correct, it does not use fillable as you are not updating a 'model instance'. You are calling update on a query builder, which deals with records not models.

**Comment by yurtesen** [comment]
I don't quite get what you mean. Do you mean that even though I am working on a "model" User() and "model" ActivationToken(), I am updating a model instance when I call updateOrCreate()  and then the same thing is all of a sudden query builder when I call update()? What in my code makes you think that I am not updating a model instance? How come my object is all of a sudden a Model and at the same time a query builder object?

It is more like eloquent is making a mistake by not using fillable in update() method in HasOneOrMany,php relation. Shouldn't relationships on Models to begin with?

**Comment by minhchu** [comment]
Could you tried this to see it work or not:
```$user->ActivationToken->updateOrCreate(['token' => $this->getNewTokenString()]);```

**Comment by yurtesen** [comment]
Well the line you put works the same way as the one with ActivationToken()
But if I use:
`$user->ActivationToken->update(['token' => $this->getNewTokenString()]);`
I get:
`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' (SQL: update `activation_tokens` set `token` = LONG_TOKEN_STRING where `id` is null)`
So the result is that there is some discrepancy on how these functions work?

**Comment by lagbox** [comment]
That is `update` on a model and it looks like that model hasn't been told that there isn't an `id` primary key to use.

**Comment by yurtesen** [comment]
@lagbox  I may be mixing up things, you are probably right. But how eloquent is working is very inconsistent, and there is a bug. Maybe my report was not clear due to me mixing things up.

For example:

`$user->ActivationToken->update(...)` -> uses model//instance/fillablable 
from Eloquent\Model but it DOES NOT work at all. (see my previous post above for error)

`$user->ActivationToken->updateOrCreate(...)` -> uses model/instance/fillable
from Database\Eloquent\Builder and it updates the token normally.

`$user->ActivationToken()->update(...)` -> uses query builder
from Relations\HasOneOrMany DOES NOT use fillable

`$user->ActivationToken()->updateOrCreate(...)` -> uses instance/fillable
from Relations\HasOneOrMany


If this is not a bug, can you just explain me the answers to these 2 questions below please?:

- Why $user->ActivationToken->update(...) does not work at all?

If as you say, ActivationToken()->updateOrCreate(...) is using the query builder, can you tell:

- Why is it using fillable? In your own explanation, the fact that it is using query builder should make it exempt from using fillable. No?

Thanks

**Comment by yurtesen** [comment]
@GrahamCampbell Can you please explain why you closed the issue without an explanation?

**Comment by lagbox** [comment]
Because there is no issue here. This is the expected behavior as explained.
