### ISSUE TITLE
[5.2] Session doesn't store the 'user_id' in DB when using multiple user tables

### ISSUE THREAD

**Issue by zlatevbg** [laravel/framework#13560]
The `Illuminate\Session\DatabaseSessionHandler@getDefaultPayload` method doesn't set the 'user_id' when using multiple user tables. It works only with the default users table.

**Comment by themsaid** [comment]
What do you mean by a multiple user tables?

**Comment by zlatevbg** [comment]
I mean a multi-auth setup where you have for example 2 tables: `users` & `customers`.

So in this case the `App\User` is the default Eloquent model shipped with Laravel and the `App\Customer` is my custom Eloquent model. I'm not using custom guards or service providers - just tweaking the auth.php config file like shown [here](https://metricloop.com/blog/setting-up-multi-auth-in-laravel-52).

**Comment by masterwto** [comment]
I think these steps are working fine.
@themsaid
It's time to close this issue now.
