### ISSUE TITLE
Kanye West diss against Taylor Otwell - for no reason at all

### ISSUE THREAD

**Issue by ThomasTesla** [laravel/framework#13574]
This issue is related to the marketing aspect of the framework.

Kanye West dissed Taylor Otwell in his track "Famous"
https://youtu.be/Q821mNXNw-I?t=26s

The related verse begins at 27 seconds.

It's clear that Kanye is talking bs here, because he never promoted Laravel anywhere.

We should make a plan to respond with all the power of the community!

Any ideas?

**Comment by vlakoff** [comment]
Just insufferable. Adding dumb video "for fun" on top of unendurable night club rap doesn't make the result any more bearable…
