### ISSUE TITLE
Database session driver keeps resetting CSRF token

### ISSUE THREAD

**Issue by AnubisTheory** [laravel/framework#13570]
For some reason using framework 5.2.31 when I set session drive to **database**, the CSRF token changes on almost every page refresh. As soon as I set the driver to **file**, it keeps the same token on multiple refreshes (as expected). Currently, all logins are met with TokenExceptionError's because of this.

I use the database driver no issues on 5.2.29.

ANY idea what might be causing this?

**Comment by AnubisTheory** [comment]
Seems I fell victim to the following (annoying) change.

#13000

**Comment by recruit-jp** [comment]
One reason it can happen is if you created sessions table manually and made the mistake of making id column as bigint(20) or any other mismatching column.
Check my detailed answer here https://stackoverflow.com/a/45340647/7260022
