### ISSUE TITLE
ErrorException: file_put_contents(/meta/services.json): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by bpfruin** [laravel/framework#13572]
I'm a novice developer trying to get phpunit set up in an already developed app(Laravel 4.2) but I get the following error on all my tests when I try to run phpunit:
ErrorException: file_put_contents(/meta/services.json): failed to open stream: No such file or directory
I did not develop the app or set any of its configurations and I'm woefully inexperienced so I don't know where to go with this. I DO have a services.json file in app/storage/meta but phpunit seems to be looking for it in the root directory and I have no idea why or how to point it to the right place.
When tracing through the error(in particular, the compiled.php file), it looks like the error is coming from the writing the "manifest", specifically when creating the manifest path. However, I'm pretty lost as to what this implies or how to fix it.

**Comment by GrahamCampbell** [comment]
Sorry, Laravel 4.2 is not supported.
