### ISSUE TITLE
Mail::queue Failing for all requests

### ISSUE THREAD

**Issue by lawrence615** [laravel/framework#13571]
I have this method, which am using to send an email which is queued

```
public function submitEnquiry(LandingPageFormRequest $landingPageFormRequest) {

        $name = $landingPageFormRequest->get('name');
        $email = $landingPageFormRequest->get('email');
        $content = $landingPageFormRequest->get('message');

        Mail::queue('email.landing_contact_us', ['name' => $name, 'content' => $content], function ($message) use($name) {
            $message->from('info@xyz.com', $name);
            $message->to('me@gmail.com', 'Test')->subject('Contact Us');
        });

        return back()->with('success', 'Successfully submitted the enquiry');
    }
```

And this is my template;

```
<!DOCTYPE html>
<html lang="en-US">
<head>
    <meta charset="utf-8">
</head>
<body>

<p>{{ $content }}</p>

<p>{{ $name }}</p>

</body>
</html>
```

For all requests I make, the jobs end up in the failed_jobs table. 

Is there a way I could use to debug the problem or can you kindly point me in the right direction.

Am using Laravel Framework version 5.2.31, on OSX Yosemite version 10.10.5 and am using supevisord to process the jobs.

Thanks

**Comment by sger** [comment]
@lawrence615 what driver are you using? supevisord is running ?

**Comment by lawrence615** [comment]
I am using mysql driver and supevisord is running.

What I have realized is, whenever I restart the supevisor,  by doing 'stop all' and then 'start all', everything works well.

But I also have another job, which sends SMS and which does not fail at all. Mail:send also works well.

**Comment by GrahamCampbell** [comment]
Please ask on the forums.
