### ISSUE TITLE
[Request] More descriptive error message when session db connection is undefined

### ISSUE THREAD

**Issue by DuckThom** [laravel/framework#13578]
Currently if the session database connection is set to an undefined connection (ie. `some_unknown_connection` instead of `default`), you will get an error: 

```
FatalThrowableError in RedisStore.php line 54:
Fatal error: Call to a member function get() on null
```

It took me a while to figure out that I had to change the `connection` setting in `config/session.php`.
I think it should display a message that it's trying to use an undefined connection.
something like:

```
UndefinedConnectionError in session.php on line 73:
Undefined database connection in config/session.php
```

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. We're open to PRs to improve this. :)
