### ISSUE TITLE
The event named 'saved' can not be triggered when "where" with the model

### ISSUE THREAD

**Issue by wefound** [laravel/framework#13584]
I have facing this issue for 3 days.

```
$item = \Model\Article::find(1); 
$item->update(['title' => 'hello world']);//The model will fire event named `saved`.

$item = \Model\Article::where('split_table_id', '=', 1)->first();
$item->update(['title' => 'hello world']);//The Builder query not fire event named `saved`.
```

Like #11777, but the `split_table_id` is required for my database proxy.

I'm trying to extends the Base Model of Eloquent and modify the method `update`, but I think it's not a good idea. So, what do you recommend handling it?

**Comment by themsaid** [comment]
@wefound what laravel version are you using? it looks like the event is being fired for me.

Also watch out, `first()` might return null, calling `update()` on null will throw a fatal error.
