### ISSUE TITLE
Eloquent's pluck ignores casts and dates

### ISSUE THREAD

**Issue by nanaya** [laravel/framework#13582]
[It checks for `hasGetMutator`](/laravel/framework/blob/15071c6e29755d6069d4b98bc4db5cd1de5b1fac/src/Illuminate/Database/Eloquent/Builder.php#L434) but doesn't check for `hasCast` and `$dates`.

The documentation doesn't mention how it is supposed to behave so I'm wondering if it is intentional.

**Comment by GrahamCampbell** [comment]
Thanks for the report. I'll elevate this to Taylor to confirm.

**Comment by taylorotwell** [comment]
Probably not intentional. Probably a bug.

**Comment by themsaid** [comment]
This was fixed in https://github.com/laravel/framework/pull/14150
