### ISSUE TITLE
Parent blade template not found for custom views path

### ISSUE THREAD

**Issue by kwebble** [laravel/framework#13586]
When a custom path is used for views and a blade template references a parent template an error occurs and a message like *View [admin] not found.* is logged.

Situation:
* Laravel 5.2
* a service provider sets a custom path for views with `loadViewsFrom()` in the `boot` method.
* the Blade template `notifications.blade.php` is stored in this custom path. This template references a parent template using `@extends('admin')`
* the template `admin.blade.php` exists in the same configured path.

When rendering the `notifications` view an error is logged: *View [admin] not found.*

When replacing `notifications` with `admin` as the main template to render, the template is found and send to the browser. So it seems the location and name is correct.

I started debugging and it looks to me that in `FileViewFinder->findInPaths()` only the default path, `resources\views`, is searched for the parent path, not the custom path.

**Comment by kwebble** [comment]
In my situation the templates are placed in a separate package. When the parent is referenced as `mypackage::admin` the parent is found.

This was not clear to me from the documentation and I don't know if it is the expected behavior. If it is this issue can be closed.

**Comment by themsaid** [comment]
Yes this is the expected behaviour @kwebble, sorry you had to wait all that time to get an answer :)
