### ISSUE TITLE
Eager loading pivot relations

### ISSUE THREAD

**Issue by PhiloNL** [laravel/framework#13599]
I have the following setup:

**providers table**

id | name
------------ | -------------
1 | Provider one
2 | Provider two

**provider_channels**

id | provider_id | name
------------ | ------------- | -------------
1 | 1 | Channel one
2 | 2 | Channel two

Now we I also have a profile and each profile can have a provider (belongsToMany) and the related channels both with additional pivot data:

**profile_providers table**

id | profile_id | provider_id | selectable
------------ | ------------- | ------------- | -------------
1 | 1 | 1 | 1
2 | 1 | 2 | 0

**profile_channels**

id | profile_id | channel_id | place
------------ | ------------- | ------------- | -------------
1 | 1 | 1 | 1
2 | 1 | 2 | 0

**ProfileProviderPivot**
```php
class ProfileProviderPivot extends Pivot
{
    /**
     * The primary key for the model.
     *
     * @var string
     */
    protected $primaryKey = 'profile_id';

    /**
     * @return mixed
     */
    public function channels()
    {
        return $this->belongsToMany(ProviderChannel::class, 'profile_channels', 'profile_id', 'channel_id')
            ->where('provider_id', $this->getAttribute('provider_id'))
            ->withPivot('place');
    }
}
```

So how I resolved this at the moment:

```php
// Fetch all profile providers which are selectable:
$providers = $profile->providers()->wherePivot('selectable', 1)->get();

// I want to have all providers with channels where the pivot value **place** is equal to one:
$providers = $providers->filter(function ($provider) {

    return $provider->pivot->channels->where('pivot.place', 1)->count() > 0;

});
```

This causes allot of queries to be generated. I would like to eager load these, but that doesn't seem to be possible.

```php
$providers = $profile->providers()->with(['pivot.channels' => function($query) {
   $query->wherePivot('place', 1);
}])->wherePivot('selectable', 1)->get();
```

Is this something that is easy to resolve or is there a better approach to do this?

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. Sorry, but we can't process discussions like this here. Feel free to check out the forums though. :)
