### ISSUE TITLE
[5.2] Shortcut option, in Artisan command creation - Not working

### ISSUE THREAD

**Issue by morwin10** [laravel/framework#13596]
In the example in documentation

https://laravel.com/docs/5.2/artisan

> `email:send {user} {--Q|queue}`

It doesn't work.

 Because if I type:

`php artisan email:send Moti --Q`

I get :

**[Symfony \ Component \ Console \ Exception \ RuntimeException]
The "--Q" option does not exist.**

And only if I type:

`php artisan email:send Moti --queue`

It works

**Comment by JeroenVanLeusden** [comment]
Use a single dash, like `php artisan email:send Moti -Q`.

**Comment by GrahamCampbell** [comment]
You need to actually include the queue name`--Q|queue`, exactly how the docs have it. Not just `--Q`.

**Comment by morwin10** [comment]
Do you mean to type :

`php artisan email:send Moti queue`  ?

It does not work. I get :
**[Symfony\Component\Console\Exception\RuntimeException] 
Too many arguments.**                     

But before there was here an answer saying
Should type only one hyphen :

`php artisan email:send Moti -Q`

And it works
