### ISSUE TITLE
[5.2] No supported encrypter found. The cipher and / or key length are invalid.

### ISSUE THREAD

**Issue by semsphy** [laravel/framework#13598]
When I ran this comamnd, I got error `No supported encrypter found. The cipher and / or key length are invalid.`

```bash
php config:cache --env=production
```

It will be fine, when I ran command `php config:clear`

**Comment by nunomazer** [comment]
Try to run the following command first

    php artisan key:generate

**Comment by GrahamCampbell** [comment]
I don't know why you're reporting an issue? This exception is not a bug, it's intended, and indicates you need to correctly configure the encrypter.
