### ISSUE TITLE
Tag a release for 5.1

### ISSUE THREAD

**Issue by kmfk** [laravel/framework#13594]
Any chance we can have a hotfix / patch release tagged for 5.1.

**Comment by GrahamCampbell** [comment]
All in good time. ;)

**Comment by kmfk** [comment]
@GrahamCampbell out of curiosity, is there a releases schedule or set process for when releases are cut after merging bug fixes?  totally understand if its just a matter of time / resources, was just curious.

**Comment by GrahamCampbell** [comment]
We don't really have a formal process.

**Comment by kmfk** [comment]
@GrahamCampbell Just in case there was any confusion, this was requested due to #13551 being merged - which I'm waiting on to fix an issue for us... I should have mentioned that in the original issue.
