### ISSUE TITLE
Catchable fatal error in artisan

### ISSUE THREAD

**Issue by RobQuistNL** [laravel/framework#13607]
Hey guys,

I've just installed a fresh installation of 5.2.32 but the artisan command is giving me troubles.

```bash
$php artisan
PHP Catchable fatal error:  Argument 2 passed to Illuminate\Routing\UrlGenerator::__construct() must be an instance of Illuminate\Http\Request, null given, called in /vagrant/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php on line 62 and defined in /vagrant/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php on line 103
```

Did I miss something? The application does run though.

EDIT:

I've tried 5.2.31 but that gives me the same problems. The issue is that I cannot work on my application now because I need artisan to run the DB migrations...

**Comment by RobQuistNL** [comment]
My bad... I used an url helper function in the service configuration.

**Comment by diegozarur** [comment]
Hello ! RobQuistNL

can u help me with this problem ??

**Comment by RobQuistNL** [comment]
@diegozarur well, the error actually means that you're using the URLHelper the wrong way. See if you can move it.
