### ISSUE TITLE
Session issue for Unit testing

### ISSUE THREAD

**Issue by martingg88** [laravel/framework#13618]
I have created test case and that have two issues. I would be appreciated if someone can help to solved this issue thanks. 

1. session is not persisted across the multiple calls/routes
2. "assertSessionHasErrors" doesn't work as "errors" key is not stored in $this->app['session.store']. However "errors" key exists in session()->all(). 

 public function testFailSignup(){
    $getResponse = $this->route('GET', 'signup');
    $postResponse = $this->route('POST', 'submitSignup', [], []);
    $this->assertSessionHasErrors();
}

**Comment by GrahamCampbell** [comment]
This is the extended behaviour. You would have to reboot the application to fire another request. Feel free to ask on the forums.

**Comment by martingg88** [comment]
can you give some hints to solve this issue? Do you know any forums to discuss about laravel? Thank You.
