### ISSUE TITLE
Camel case model relationship is returned as snake case property

### ISSUE THREAD

**Issue by klimentLambevski** [laravel/framework#13614]
How can i tell laravel to return the relationship results in same name as the relationship function?
ex. I have relationship called `mediaItem` and when i call $model->with('mediaItem') is is returned as `{media_item: {}}`. Is there a way that it is returned as {mediaItem:{}}?

**Comment by GrahamCampbell** [comment]
No, sorry.

**Comment by stefankorun** [comment]
@GrahamCampbell Isn't `public static $snakeAttributes = false;` attribute the solution to this?

ref: https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/Model.php#L204

**Comment by josemiguelq** [comment]
@klimentLambevski you can solve this using:

Network.php
```php
  public function pointsOfSale()
    {
        return $this->hasMany(PointOfSale::class);
    }
```
PointOfSale.php
```php
 public function network()
    {
        return $this->belongsTo(Network::class, 'networkId');
    }
```

**Comment by DamianSuess** [comment]
I wish this worked for the Factory and Seeder, it still converts it to "`network_Id`". The system doesn't care that our naming conventions don't use `snake_case`

> @klimentLambevski you can solve this using:
> 
> Network.php
> 
> ```
>   public function pointsOfSale()
>     {
>         return $this->hasMany(PointOfSale::class);
>     }
> ```
> 
> PointOfSale.php
> 
> ```
>  public function network()
>     {
>         return $this->belongsTo(Network::class, 'networkId');
>     }
> ```
