### ISSUE TITLE
Throttle custom message

### ISSUE THREAD

**Issue by mehdibahraami** [laravel/framework#13623]
Hi,
I want to use custom message for API Rate Limiter and added this exception in my exception handler:
```
public function render($request, Exception $e)
    {
        if($e instanceof TooManyRequestsHttpException) {
            return response()->json([
                'message' => 'Too many requests. Slow your roll!',
                'code' => 429
            ], 429);
        }

        return parent::render($request, $e);
    }
```
 but it show me again this message "Too Many Attempts."

**Comment by themsaid** [comment]
Laravel doesn't use `TooManyRequestsHttpException`, if you want to use a custom message you can extend `ThrottleRequests` and override `buildResponse()`.

**Comment by GrahamCampbell** [comment]
@themsaid This is probably with reference to my throttle package.

**Comment by GrahamCampbell** [comment]
https://github.com/GrahamCampbell/Laravel-Throttle/issues/44

**Comment by themsaid** [comment]
Oh, I see. Graham's packages everywhere :)

**Comment by GrahamCampbell** [comment]
@mehdibahraami It's likely you forgot to import the correct class. Feel free to ask on the forums for help. We can't process things like this on our GirHub issues.

**Comment by mehdibahraami** [comment]
@GrahamCampbell I was using the Laravel throttle and i thought your package and the Laravel package is the same. For this reason i asked my question in your package issues.
This is not Laravel problem? I can't send personalized response(for my client) directly and must extend a package and changed it? Other people have made this request before:
https://github.com/laravel/framework/pull/13452
At the end, I recently started work with Laravel and i think it is better to be a little kinder to respond to users ;)

@themsaid Thank you so much.

**Comment by sidjoshi001** [comment]
Hello Folks, Recently I've read this article and it works for me...

https://thedevsaddam.gitbooks.io/off-time-story/content/how_to_customize_laravel_throttle_message_response.html

I hope this will help You..!!

**Comment by Last-Order** [comment]
A more simple way:

Just create a new middleware in `app\Http\Middleware` and extend `\Illuminate\Routing\Middleware\ThrottleRequests`, then override the `buildResponse` method.

**Comment by floringavrila** [comment]
use Symfony\Component\HttpKernel\Exception\HttpException;
...
if($exception instanceof HttpException && $exception->getStatusCode() == 429) {
           return response()->json([
                                     'message' => 'Too Many Attempts',
                                     'code' => 429
                                             ], 429)->withHeaders($exception->getHeaders());
}

**Comment by yabasha** [comment]
hi @themsaid I tried to override `buildResponse()` but it is missing in `\Illuminate\Routing\Middleware\ThrottleRequests` I tried to use ` buildException()` instead but it doesn't work.

Please give me the right way to build max throttle custom message.

I'm using `Laravel 5.6`

**Comment by kevincobain2000** [comment]
I have tested this on Laravel 5.6

You can do it by  ThrottleRequestsException for this via ``app/Exceptions/Handler.php``

```
use Illuminate\Http\Exceptions\ThrottleRequestsException;
use Illuminate\Http\Response;
```

and next add it to your ``render()`` function
```
    public function render($request, Exception $e)
    {
        if ($e instanceof ThrottleRequestsException) {
            return $this->response409($e);
        }

        return parent::render($request, $e);
    }
    public function response409(Exception $e)
    {
        $errors = new MessageBag();
        $errors->add("message", "409 Too many requests");
        return response()->make(view('errors.409')->withErrors($errors), Response::HTTP_CONFLICT);
    }
```

**Comment by Manishdreamfolks** [comment]
if($exception instanceof ThrottleRequestsException) {
return response()->json([
'message' => 'Too many requests. Slow your roll!',
'code' => 429
], 429);
return parent::render($request, $exception);
}
add this in render function and use ThrottleRequestsException; in app/Extensions/Handler.php

**Comment by hakkikonu** [comment]
Its very easy.

`in your app/Exceptions/Handler.php` find `register()` method. Then add this. In this example my condition is /api/* endpoints only. You can change whatever you want here.

```
public function register()
    {
        $this->reportable(function (Throwable $e) {
            //
        });

        $this->renderable(function (ThrottleRequestsException $e, $request) {
            if ($request->is('api/*')) {
                return response()->json([
                    'message' => 'TOOOOO many requests'
                ], 429);
            }
        });
    }
```

**Comment by jukeboxplays** [comment]
> Very easy.
> 
> in your `app/Exceptions/Handler.php` find `register()` method. Then add this. In this example my condition is /api/* endpoints only. You can change whatever you want here.
> 
> ```
> public function register()
>     {
>         $this->reportable(function (Throwable $e) {
>             //
>         });
> 
>        //This part will handle ThrottleRequestsException exceptions
>         $this->renderable(function (ThrottleRequestsException $e, $request) {
>             if ($request->is('api/*')) {
>                 return response()->json([
>                     'message' => 'TOOOOO many requests'
>                 ], 429);
>             }
>         });
>     }
> ```
> 
> Reference: https://laravel.com/docs/8.x/errors#rendering-exceptions
> 
> Tested on: Laravel 8.x

That's actually a great idea! Way easier than creating a middleware and use on the routes.

**Comment by deviserops** [comment]
> Very easy.
> 
> in your `app/Exceptions/Handler.php` find `register()` method. Then add this. In this example my condition is /api/* endpoints only. You can change whatever you want here.
> 
> ```
> public function register()
>     {
>         $this->reportable(function (Throwable $e) {
>             //
>         });
> 
>        //This part will handle ThrottleRequestsException exceptions
>         $this->renderable(function (ThrottleRequestsException $e, $request) {
>             if ($request->is('api/*')) {
>                 return response()->json([
>                     'message' => 'TOOOOO many requests'
>                 ], 429);
>             }
>         });
>     }
> ```
> 
> Reference: https://laravel.com/docs/8.x/errors#rendering-exceptions
> 
> Tested on: Laravel 8.x

I have made change to this. If request if from json or web it will show json format data, but when it's from web it will show default page.
```
$this->renderable(function (ThrottleRequestsException $e, $request) {
            if ($request->expectsJson()) {
                return response()->json([
                    'status' => false,
                    'message' => 'Too many request.',
                    'data' => (object)[]
                ], 429);
            }
});
```
You can modify json response.
