### ISSUE TITLE
Hardcoded clases in Optimize command

### ISSUE THREAD

**Issue by iwex** [laravel/framework#13626]
Is it ok to hardcode files https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Console/Optimize/config.php?

For example: Symfony has 'replace' option (https://github.com/symfony/symfony/blob/master/composer.json#L50) in composer file, so any 3rd party package with symfony dependency will broke optimize command.

**Comment by GrahamCampbell** [comment]
No 3rd party package should depend on all of symfony. Tell them to update their dependencies to properly depend on the components.
