### ISSUE TITLE
[5.2] Laravel route cache on custom route files

### ISSUE THREAD

**Issue by dees040** [laravel/framework#13627]
I'm building a project in Laravel 5.2 which had a big routes.php. To make the routes a little cleaner for the eyes, I've split all the route groups intro separated files. In the directory app\Http\Routes.

I require all the files in the RouteServiceProvider which works (correction: worked..) perfectly fine for me. After all this I wanted to cache the routes with php artisan route:cache. Then if you went to a page all you get is a 404 error.

“Long” story short: New route logic is crashing AFTER artisan route cache.

This is my map function in RouteServiceProvider:

```
public function map(Router $router)
{
    $router->group(['namespace' => $this->namespace], function ($router) {
        // Dynamically include all files in the routes directory
        foreach (new \DirectoryIterator(app_path('Http/Routes')) as $file)
        {
            if (!$file->isDot() && !$file->isDir() && $file->getFilename() != '.gitignore')
            {
                require_once app_path('Http/Routes').DS.$file->getFilename();
            }
        }
    });
}
```
Does someone know what the problem is? Or do I just need to put everything back in routes.php if I want to use route caching. Thanks in advance.

**Comment by GrahamCampbell** [comment]
Sorry, this doesn't look like a bug in Laravel. Infact, I do something similar, and it works for me.

It looks like your `require_once` may be the issue though. Change it to `require`.

**Comment by GrahamCampbell** [comment]
Feel free to ask on the forums if you still can't fix this.
