### ISSUE TITLE
strange difference between calling findOrFail using an instance object and calling statically

### ISSUE THREAD

**Issue by Enlightments** [laravel/framework#13629]
Im developing an application on Laravel framework and i noticed something strange.

Version : 
Laravel Framework version 5.2.32

I have a model called "Level" and when i call 'findOrFail' statically, it returns a collection of level instances.

$level = Level::findOrFail($levelId) 
dd($level)

Collection {#360 ▼
  #items: array:1 [▼
    0 => Level {#361 ▶}
     ]
}

But when i instantiate an object or use dependency injection, calling 'findOrFail' returns single model object.

$level = new Level();
dd($level->findOrFail($levelId));

Level {#355 ▼
  #table: "level"
  #fillable: array:8 [▶]
  #connection: null
  #primaryKey: "id"
  #perPage: 15
  +incrementing: true
  +timestamps: true
  #attributes: []
  #original: []
  #relations: []
  #hidden: []
  #visible: []
  #appends: []
  #guarded: array:1 [▶]
  #dates: []
  #dateFormat: null
  #casts: []
  #touches: []
  #observables: []
  #with: []
  #morphClass: null
  +exists: false
  +wasRecentlyCreated: false
}

I think the existence of `findOrFail` method is to return a single model instance based on a unique primary key so it does not need to return a collection.

I was wondering if this is a bug or it is supposed to work like this.

Thanks.

**Comment by lagbox** [comment]
Is $levelId the same for each of those calls, and what type is $levelId?

**Comment by Enlightments** [comment]
@lagbox 
Thanks that was the issue.
I was using "Hashids" package in order to generate safe query strings and when decoding a SINGLE parameter, it returns an ARRAY with a single value :|
