### ISSUE TITLE
Error on running `composer install` (Laravel 5.1)

### ISSUE THREAD

**Issue by EwanValentine** [laravel/framework#13633]
I've been trying to run `composer install` all morning in a Laravel 5.1 project, but I keep getting 

```
  Could not scan for classes inside "/var/www/api/vendor/laravel/framework/src/Illuminate/Queue/IlluminateQueueClosure.php" which does not appear to be a file nor a folder
```

This is using php7, but I've tried it with php 5.6 also. 

I get the same error even after deleting the vendor directory, as well as the `composer.lock` file. I'm completely at a loss.

**Comment by GrahamCampbell** [comment]
Feel free to ask on the forums, or slack, and I'm sure someone can help you there.

**Comment by EwanValentine** [comment]
Right...
