### ISSUE TITLE
Validation errors and session

### ISSUE THREAD

**Issue by leesleefeng** [laravel/framework#13634]
When trying get error messages after a post, I got nothing.
I've encountered this problem before. By adding routes in the web middleware I got it solved.
But this time it's strange, because I'd put all thouse routes in web milldleware already.

This project is powered by laravel 5.2.31 while the other by 5.2.23.
I'ts so weird that  session files in storage/framework/sessions is not one but many, while there is only one user logined(The project is still running on a local server). 
In the ohter project (validation errors cans be displayed normally), only one session file is generated(one user logined olny).

After updating laravel to 5.2.32 and deleting all session files, this problem still exists.

I once doubted that using web middleware in more than one route group leads to this problem.
It proved wrong. Reorganising my routes and only one group using web middleware didn't make any difference.

![session files of onenet 2016-5-21](https://cloud.githubusercontent.com/assets/12124610/15434228/803e8cb6-1ee8-11e6-9044-0ac552b6e5d4.png)

**Comment by shadoWalker89** [comment]
Remove the web middleware from your routes.php file.
The web middleware is added by the application in App\Providers\RouteServiceProvider
Having the web middleware twice is what causes this problem.

**Comment by leesleefeng** [comment]
Thanks a million!
It works.
That's why there is no route groups using the web middleware in the default routes.php file any more.
