### ISSUE TITLE
POST request type is flattened into GET if it is caught by auth middleware

### ISSUE THREAD

**Issue by UnrulyNatives** [laravel/framework#13637]
The below problem is present in all Laravel versions, including current 5.2.31.
 
Consider this case:
1. I have an `Add Comment` form in all my model display templates.
The form is visible for non-logged users.

2. An user fills up the form and clicks "send your comment" button.

3. As in my controller I protected the store method by middleware 

    `public function __construct() {
        $this->middleware('auth', ['only' => array('store', 'update') ]);
    }`

the request is caught by the `auth` middleware and the user is redirected to the login form.

### PROBLEM
4. ... but after successful login the user is redirected to route `comments` as the middleware treats the request as GET, not a POST any more.
As a result, the user is sent to a list of comments, which is restricted to mods only

The expected behavior would be to process the POST request and return user to the URL where they pressed the "Send comment" button.

### to do
make the middleware keep info about request type

Thx

**Comment by jayeshanandani** [comment]
I can replicate this on latest laravel version.

**Comment by vlakoff** [comment]
Looks like you should save the comment in session then grab it back once the user has logged/registered.

You workflow is a bit unusual, most of the time an user can't start commenting/editing/whatever before he has logged in.
