### ISSUE TITLE
Model __isset() returns true for names which are not attributes or relations

### ISSUE THREAD

**Issue by JamesGuthrie** [laravel/framework#13632]
The changes introduced in 45fb88125fc931127804c1da111b72798565e9a7 and  09ea8e2f321195d8518952cdbfa5746c9799cdc1 to the `__isset()` method on Model inadvertently result in `isset($model->name)` being true for any *method* on the model called `name`. The result is that `$model->save`, `$model->update`, etc. are all indicated as being set on the model because of the presence of `save` and `update` methods on Model.

**Comment by themsaid** [comment]
It'll only return true if the method exists AND a relationship could be loaded.

**Comment by xtwoend** [comment]
I also got a similar problem to isset in my model and I tried to fix by changing the order of checks in relation method

```
public function __isset($key)
    {
        if (isset($this->attributes[$key]) || isset($this->relations[$key])) {
            return true;
        }
        
        if (method_exists($this, $key) && isset($this->relations[$key]) && $this->$key) {
            return true;
        }

        return $this->hasGetMutator($key) && ! is_null($this->getAttributeValue($key));
    }
```

**Comment by JamesGuthrie** [comment]
@themsaid That's not quite correct.

I have taken a closer look at what is happening and isolated the problem to this line: https://github.com/laravel/framework/commit/09ea8e2f321195d8518952cdbfa5746c9799cdc1#diff-d8e24a5815a26f7211e66db787be647fR3411

My example scenario is testing for the presence of the `save` attribute on a model.

1. `$this->key` calls `__get()` on the model with the key name (`save`)
2. This results in `$this->getAttribute('save')` being called
3. `getAttribute` checks if an attribute can be loaded (false, no `save` attribute on the model), and then tries to load the `save` relation.
4. LogicException: Relationship method must return an object of type Illuminate\Database\Eloquent\Relations\Relation

**Comment by themsaid** [comment]
@JamesGuthrie you're right, in my comment I meant that this is how the logic supposed to work.

> relationship could be loaded

Will try to come up with a PR for a fix.

**Comment by themsaid** [comment]
There's a PR currently open that will take care of this issue along with other issues related to calling method names as attributes: https://github.com/laravel/framework/pull/15438
