### ISSUE TITLE
GraphQL is something that is getting better and even good than REST API.

### ISSUE THREAD

**Issue by richard457** [laravel/framework#13641]
I wonder if this can be added into laravel in sense that it is very easy, there is already a package for laravel but it can be good if it is shipped with laravel app for better convenience.
Thank you.

**Comment by JeroenVanOort** [comment]
Having a package available is convenient enough for me. Adding it to the Laravel core would just add load for most applications, since I believe the majority of Laravel projects don't use GraphQL.

**Comment by GrahamCampbell** [comment]
Thanks, but we don't process proposals here. Please review our contribution guidelines first.
