### ISSUE TITLE
DB password thrown as plain text in error report - severe security risk

### ISSUE THREAD

**Issue by UnrulyNatives** [laravel/framework#13647]
My app, while in debug=true mode on production server crashed with this error:

`PDOException in Connector.php line 55:
SQLSTATE[28000] [1045] Access denied for user 'XXXXX'@'localhost' (using password: YES)
in Connector.php line 55
at PDO->__construct('mysql:host=127.0.0.1;dbname=XXXXX', 'XXXXX', 'YYYYY', array('0', '2', '0', false, '0')) in Connector.php line 55`

It happened all of a sudden - some glitch in the code which I am still trying to track down.

## the problem
the DB name, DB username and - most importantly - the password was displayed in plain text.
In the above quotation I put XXXXX and YYYYY in place of this data stored in `.env`

It means that in case I forget to set the app to `debug=false`, users would be able to see my credentials without me being aware of it - when on leave or too tired to pay attention.

## to do
**urgent**
make sure the error message WOULD NEVER EVER print the DB credentials.

Thx

**Comment by GrahamCampbell** [comment]
Never enable debug mode in production.

**Comment by UnrulyNatives** [comment]
Then maybe Laravel 5.3 should by design ignore the `debug=` line and assume that for `APP_ENV=remote`the debug is always disabled. 

Sometimes there are issues on production server which cannot be replicated in local environment. 
Besides, as a developer you SHOULD create apps which are foolproof. In this case it means that the code [of your software product] should help users to avoid consequences of erroneous actions.

You should either revise your philosophy for security policies or... contact the author of this repo https://github.com/awslabs/git-secrets and advice him to unpublish the code and put a free advice "never commit your passwords" instead.

An example. After this event
http://wptavern.com/ryan-hellyers-aws-nightmare-leaked-access-keys-result-in-a-6000-bill-overnight
Github should offer an option to withheld commits containing API keys and passwords.
As a **courtesy** to users.

Thank you for your attention.
