### ISSUE TITLE
CORS middleware not getting executed

### ISSUE THREAD

**Issue by jayeshanandani** [laravel/framework#13643]
Hi,

We have a middleware called 'cors' registered in $routeMiddleware. Whenever there is an API request like the GET it does go into middleware.

Apart from that if we try to send POST,  PUT request it doesn't goes to the middleware and instead throws an error:

XMLHttpRequest cannot load xxxx. Response to the preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access.

Related: #13103

**Comment by themsaid** [comment]
@jayeshanandani how do you handle preflight requests?

**Comment by jayeshanandani** [comment]
@themsaid 

Below is the Middleware code written inside a new file called Cors.php

`<?php

namespace App\Http\Middleware;

use Closure;

class Cors
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        header('Access-Control-Allow-Origin: *');
        header('Access-Control-Allow-Methods: GET, POST, PATCH, PUT, DELETE, OPTIONS');
        header('Access-Control-Allow-Headers: Content-Type, Accept, Authorization, X-Requested-With, Application');
        return $next($request);
    }
}
`

and then inside Kernel.php in variable named: protected $routeMiddleware 

`'cors' => \App\Http\Middleware\Cors::class`

and in routes we have something like this:

`Route::group(['prefix' => 'v1/api','middleware'=>=> ['cors']], function()`

**Comment by themsaid** [comment]
This middleware will cover simple requests only, you need to handle pre-flight requests which send an OPTIONS request to the route to check if the actual request will be accepted.

I suggest you use this package: https://github.com/barryvdh/laravel-cors, it's well written and tested, it also handles pre-flight requests for you.

**Comment by jayeshanandani** [comment]
@themsaid 

Any reason why same code used to work in Laravel 5.1 and it's not working in 5.2?

**Comment by themsaid** [comment]
I'm not actually sure, but I don't think it's possible to catch OPTIONS requests out of the box inside a route group.

**Comment by barryvdh** [comment]
AMD please just don't call 'header()', but modify the headers on the response object.

**Comment by jayeshanandani** [comment]
@barryvdh 

```php
<?php 
namespace App\Http\Middleware;

use Closure;

use Illuminate\Contracts\Routing\Middleware;
use Illuminate\Http\Response;

class CORS implements Middleware {

 /**
  * Handle an incoming request.
  *
  * @param \Illuminate\Http\Request $request
  * @param \Closure $next
  * @return mixed
  */
 public function handle($request, Closure $next)
 {
      $response = $next($request);
	   $response->headers->set('Access-Control-Allow-Origin' , '*');
	   $response->headers->set('Access-Control-Allow-Methods', 'POST, GET, OPTIONS, PUT, DELETE');
	   $response->headers->set('Access-Control-Allow-Headers', 'Content-Type, Accept, Authorization, X-Requested-With, Application');
	
	return $response;
 }
}

```

I believe you believed something like this.

**Comment by GrahamCampbell** [comment]
Feel free to discuss on the forums.

**Comment by sergiobelya** [comment]
See also #19938

**Comment by swapnil-chaudhari-1811** [comment]
I have followed this but still getting this error.

` No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.`

**Comment by therealmjk** [comment]
Add this to your index.php file

header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET, POST, PATCH, PUT, DELETE, OPTIONS');
header('Access-Control-Allow-Headers: Origin, Content-Type, X-Auth-Token');

**Comment by crynobone** [comment]
@therealmjk Please don't give out hack solution, it just a bad advise for everyone.

Calling `header()` directly would mess up the Request/Response process which is handled via Symfony Http Foundation. Create a proper middleware to add CORS support on your app.

**Comment by salipro4ever** [comment]
I use laravel 5.5, my CORS middleware, same error but find out my solution. I hope it is useful for someone.
```php
namespace App\Http\Middleware;
use Closure;
class Cors
{
    public function handle($request, Closure $next)
    {
        $response = $next($request);
        $response->header('Access-Control-Allow-Methods', 'HEAD, GET, POST, PUT, DELETE');
        $response->header('Access-Control-Allow-Headers', $request->header('Access-Control-Request-Headers'));
        $response->header('Access-Control-Allow-Origin', '*');
        return $response;
    }
}
```
Solution 1. Init Cors middleware on global HTTP middleware in `Kernel.php`
Solution 2. Still init api group middleware `$middlewareGroups['api']`, must add more options request in route `routes/api.php`. (for me) 
```php
Route::options('{any?}', function (){
    return response('',200);
})->where('any', '.*');
```

Guk luk!

**Comment by sergiobelya** [comment]
My CORS middleware (for method OPTIONS only)
https://github.com/sergiobelya/laravel-options-cors/blob/master/OptionsCorsResponse.php

**Comment by oniseun** [comment]
@salipro4ever  still surprised as to how your solution worked like a charm here.
You just saved my day!!

**Comment by sergiobelya** [comment]
`$response->header('Access-Control-Allow-Methods', 'HEAD, GET, POST, PUT, DELETE');` 
isn't true.
I use 
```php
$allowMethods = $response->headers->get('Allow'); // thanks, Laravel
if ($allowMethods) {
    $response->header('Access-Control-Allow-Methods', $allowMethods);
}
```
for correct definitions of allowed methods in header.
It's working if class `Cors` enabled in `Kernel::$middleware`.
Also,
```php
$response->header('Access-Control-Allow-Headers', $request->header('Access-Control-Request-Headers'));
$response->header('Access-Control-Allow-Origin', '*');
```
isn't safe. Be careful.

**Comment by yu-jinm** [comment]
@jayeshanandani Middleware works already. You just need to create that route ;)

**Comment by marcnewton** [comment]
Old and closed but shows up in google search.

There are Red Herring scenarios that can cause a CORS Access Control error to display and not have anything to with CORS configuration: 
The following can indirectly cause the error:

- A PHP error in a Middleware class.
- **return $next($request);** not being fired in middleware class method **handle**.
- **Route::middleware** in web or api router configs reference a middleware that no longer exists or is miss spelt.
- Same as above point but middleware specified in a Controller with **$this->middleware();**

Any of these can prevent a Cors middleware from ever being fired because the app exits too early and never sets the headers and thus results in a CORS error instead of a 500 Server Header error.

**Comment by ken-elsheezy** [comment]
Create a middleware class, in this case lets assume the class name **CorsMiddleware**, with a handle method
as described by @salipro4ever above.

```
    public function handle($request, Closure $next)
    {
        $response = $next($request);
        $response->header('Access-Control-Allow-Methods', 'HEAD, GET, POST, PUT, DELETE');
        $response->header('Access-Control-Allow-Headers', $request->header('Access-Control-Request-Headers'));
        $response->header('Access-Control-Allow-Origin', '*');
        return $response;
    }
```

Registering the middleware **ONLY** in the global $middleware array of your Kernel.php will be enough to resolve all your CORS middleware issues. i.e

```
    /**
     * The application's global HTTP middleware stack.
     *
     * These middleware are run during every request to your application.
     *
     * @var array
     */
    protected $middleware = [
        ...
        \App\Http\Middleware\CorsMiddleware::class,
    ];
```

Hope this helps someone. Cheers.

**Comment by martin-braun** [comment]
Even if it works, putting your middleware directly into `$middleware` instead of `$routeMiddleware` will expose all endpoints with the new CORS policy. This is an absolute no-go for me. The better solution is only always allow OPTION calls to go through and still redirect other HTTP methods through the `$routeMiddleware`.

So, build two middlewares: 

**Cors.php**
```php
 <?php

namespace App\Http\Middleware;

use Closure;

class Cors
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        return $next($request)
          ->header('Access-Control-Allow-Origin', '*')
          ->header('Access-Control-Allow-Methods', '*')
          ->header('Access-Control-Allow-Headers', '*');
    }
}
```

**OptionsCors.php**
```php
<?php

namespace App\Http\Middleware;

use Closure;

class OptionsCors
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
      if($request->isMethod('OPTIONS')) {
        return $next($request)
          ->header('Access-Control-Allow-Origin', '*')
          ->header('Access-Control-Allow-Methods', '*')
          ->header('Access-Control-Allow-Headers', '*');
      }
      return $next($request);
    }
}
```

**app/Http/Kernel.php**
```php
<?php 
namespace App\Http
{
    class Kernel extends \Illuminate\Foundation\Http\Kernel
    {
        protected $middleware = [
            // ...
            'App\Http\Middleware\OptionsCors',
        ];
        protected $middlewareGroups = [
            'web' => [
                 // ...
            ], 
            'api' => [
                'App\Http\Middleware\UseApiGuard', 
                'throttle:60,1', 
                'bindings'
            ]
        ];
        protected $routeMiddleware = [
            // ...
            'cors' => 'App\Http\Middleware\Cors', 
        ];
    }

}
```

Now in your routes you have full control about what endpoints will be exposed with your tightened CORS policy: 

```php
Route::namespace('Api')->middleware(['cors'])->group(function () {

	Route::get('api/im_open', 'TestController@ping');

});
Route::namespace('Api')->group(function () {

	Route::get('api/im_closed', 'TestController@ping');

});
```

**Comment by sergiobelya** [comment]
```
return $next($request)
          ->header('Access-Control-Allow-Origin', '*')
          ->header('Access-Control-Allow-Methods', '*')
          ->header('Access-Control-Allow-Headers', '*');
```
isn't safe and is not for production.
