### ISSUE TITLE
Automatically Determining Policy Methods not working when there is no instance yet

### ISSUE THREAD

**Issue by lfarkas** [laravel/framework#13649]
first of all it'd useful to expand a little bit the documentation. most of the time i've to google for a few not so advanced stuff and most of the time the same problem happened to be problems for many other people. like with authorization. the last session of the https://laravel.com/docs/master/authorization said that we can check authorization like this:
```
$this->authorize($post);
```
but not mention what about index and create when there is not any model yet. after a long test and search finally look into laravel's code it's turn out only these working:
```
$this->authorize(new Post);
$this->authorize('create', Post::class);
$this->authorize('create', new Post);
policy(Post::class)->create(auth()->user());
```
and even many said that it's ok to call like this:
```
$this->authorize(Post::class);
```
it's not working. the reason for this is the check in line 51 in AuthorizesRequests->parseAbilityAndArguments and in this case $ability is 'App\Post' ie. it's a string even it should have to behave as a class.
I create a short pull request which fix it.

**Comment by GrahamCampbell** [comment]
This looks like a bug in your code, sorry.

**Comment by lfarkas** [comment]
i don't think so. have you ever try anything like this in any controllers create?:
```
$this->authorize(Post::class);
```
the problem is in AuthorizesRequests->parseAbilityAndArguments in the above case php call authorize with 'App\Post' string so it's goes into the if and never reach the tricky magic 'debug_backtrace' line 55. and that's the problem. my proposed fix could be good, but not so. the reason is that laravel override the class loading itself in Illuminate/Foundation/AliasLoader.php and that's the problem since laravel do not simple retrurn flase but drop an exception.
so would you reopen this ticket?

**Comment by GrahamCampbell** [comment]
`$this->authorize(Post::class);` that call is incorrect. You need to actually have to pass through a post object, as the docs say.

**Comment by lfarkas** [comment]
that's the whole issue about. that in case of index and create there is no object instance and would be nice to support, since all other function you shouln't have to give the function name itself like 'create' since it's find by the name of the calling function. it'd be nincs to do so in case of create and index too.
- https://laracasts.com/discuss/channels/laravel/policy-on-create
- https://laracasts.com/discuss/channels/laravel/laravel-511s-new-authorization-doesnt-read-policies?page=2
- http://stackoverflow.com/questions/33745564/laravel-5-1-index-create-authorization

i'm just push a new pull request which fix this problem.
