### ISSUE TITLE
Flush entire session data

### ISSUE THREAD

**Issue by pjebs** [laravel/framework#13640]
It would be useful to clear all session data using a console command (especially for debugging).
Something similar to `cache:clear`.

Probably is `$request->session()->flush();` as per documentation requires a request.
That is not available for console commands.

How can I achieve this?

**Comment by pjebs** [comment]
`session()->flush();` doesn't do anything in console commands.
Currently I'm just using file based sessions and manually deleting out the contents from `storage/framework/sessions`

**Comment by GrahamCampbell** [comment]
Feel free to ask on the forums.
