### ISSUE TITLE
Route model binding is confused when global scope related to auth is applied

### ISSUE THREAD

**Issue by 3amprogrammer** [laravel/framework#13645]
I have a global scope for my Question Model. It is pretty  #straightforward
```
public function apply(Builder $builder, Model $model)
    {
        return $this->guard->guest()
            ? $builder->where('is_login_required', 'true')
            : $builder;
    }
```

When I try to access this question using implicit route model binding it tries to **fetch question before performing authentication**. At least from my point of view. I can access other questions with no problem, but when the flag login required is on I get an Exception (cause of firstOrFail in Router).

When I have dumped `$this->guard->guest()` first in global scope, and than in my controller I got the following results: true, false. So authentication is working but in wrong order (at least combined with route model binding).

**Comment by GrahamCampbell** [comment]
This is the expected behaviour.

**Comment by GrahamCampbell** [comment]
I've changed the implementation in L5.3 to use a middleware though, so you can bind after auth.
