### ISSUE TITLE
[5.2] \URL::to() returning wrong domain

### ISSUE THREAD

**Issue by LasseRafn** [laravel/framework#13659]
Hi,

Okay. A quick overview of my setup:

- Multiple domains (one for each language)
- One instance of Laravel
- Using Beanstalkd for queues

——— My domains — ——
Main: my-site.com
Another: my-site.org
————————————

Great. Now to my issue.

Whenever I call \URL::to('/account') within an queued mail (in the view file) it passes the mail url, even after I did:

````
\URL::forceRootUrl('http://my-site.org');
\Config::set('app.url', 'http://my-site.org');
````

Before the \Mail::queue() method, and within the callback of it too.

How would I go about changing this dynamically? There must be some option.

Thanks.

——

I've also tried to set app.url and root url without the scheme. No change.

**Comment by GrahamCampbell** [comment]
Feel free to discuss on the forums. I would not recommend force overriding like that though. Instead of evaluating URLs on the queue, i'd recommend pre-computing them, then passing them through to your closure to go onto the queue.
