### ISSUE TITLE
Possible performance issue - SessionGuard::check calls SessionGuard::user

### ISSUE THREAD

**Issue by sinall** [laravel/framework#13663]
In GuardHelpers
----
    public function check()
    {
        return ! is_null($this->user());
    }

The function user will try to retrieve user from DB.
Is it a good idea just calling $this->id() instead?

**Comment by vlakoff** [comment]
Isn't user cached in a class property once retrieved for the first time?

**Comment by GrahamCampbell** [comment]
Yes.
