### ISSUE TITLE
/auth/logut url and guest middleware

### ISSUE THREAD

**Issue by leesleefeng** [laravel/framework#13660]
/auth/logut didn't work.

Override the getLogout method in AuthController and print some text, nothing outputed.

I noticed that there is guest middleware about the logout action in the constructor of AuthController.
Comparing the code with another project Scrumwala based on laravel 5.1, I found that except option is defferent.

In Laravel 5.2.32, the constructor of AuthController is:

    public function __construct()
    {
        $this->middleware($this->guestMiddleware(), ['except' => 'logout']);
    }

While in Scrumwala (Laravel 5.1.*):

	public function __construct()
	{
		$this->middleware('guest', ['except' => 'getLogout']);
	}

By using getLogout instead of logout as the value of except option, /auth/logout works in Laravel 5.2.32

I ran aonther test.
In Laravel 5.2.23, ['except' => 'logout'] works fine....  /-_-\

**Comment by GrahamCampbell** [comment]
Feel free to discuss on the forums.
