### ISSUE TITLE
Redis tagged cache using a lot more storage since upgrading from 5.2.12 to 5.2.28

### ISSUE THREAD

**Issue by HughNoble** [laravel/framework#13670]
We use tagged redis cache to power a custom page cache implementation and since upgrading from Laravel 5.2.12 to 5.2.28 our Redis instance has been filling up within a matter of hours (it was previously running for > 6 months without filling up).

Looking within Redis with 5.2.12 it was storing a tag which contained a key which pointed to the content stored under another key. With 5.2.28 it's creating a tag which contains a key which points to another key which then points to the content. So it's adding another key in the middle.

I've looked through the commit history but I'm struggling to narrow down where this change has happened and why.

**Comment by GrahamCampbell** [comment]
We changed the scheme, so you should expect it to double memory usage if you don't clear the old stuff.

**Comment by GrahamCampbell** [comment]
Please open a new issue if the change was more than two fold, as that would indicate another issue.

**Comment by HughNoble** [comment]
It's definitely not because our old data is still in the instance. I've cleared the instance and it still fills up.

I've dug up some more info and added it to a new issue.

https://github.com/laravel/framework/issues/13675
