### ISSUE TITLE
Eloquent Query collection does not provide results

### ISSUE THREAD

**Issue by dhiman252** [laravel/framework#13685]
I am using the framework version 5.2.* and using the following eloquent query:

`$notifications = Notify::with('quote.task.professional','quote.task.user','quote.owner')
                            ->where(function($query) use ($quotes){
                                $query->whereIn('quote_id',[$quotes])
                                    ->where('provider_seen', Notify::UNSEEN);
                            })
                            ->whereNotNull('message_provider')
                            ->orderBy('updated_at', 'desc')
                            ->get();`

It does'nt provide the results but by listening to the db queries the following query is fired:
`select * from `notifications` where (`quote_id` in (?) and `provider_seen` = ?) and `message_provider` is not null order by `updated_at` desc`

Query parameters are also fine, but there is no record in the eloquent collection, but by running the above generated query with parameters the results are retrieved.

**Comment by dhiman252** [comment]
An Update: The DB table query also does not work:

`$notifications = DB::table('notifications')
                            ->where(function($query) use ($quotes){
                                $query->whereIn('quote_id',[$quotes])
                                    ->where('provider_seen', Notify::UNSEEN);
                            })
                            ->whereNotNull('message_provider')
                            ->orderBy('updated_at', 'desc')
                            ->get();`

while the query generated works well in the SQL but not as stated above.

I guess its the parameters bindings which are not working properly.

**Comment by dhiman252** [comment]
![query object](https://cloud.githubusercontent.com/assets/8954468/15536754/60f8cc3a-2290-11e6-8877-6904cac7390d.png)
Refer Query Object

**Comment by Francismori7** [comment]
Try removing the brackets from $quotes since it probably already is an array, you are now giving a double deep array which causes this.
