### ISSUE TITLE
Support for hhvm WholeProgram optimizations (drop facades)?

### ISSUE THREAD

**Issue by dani3l** [laravel/framework#13687]
Hi 
I tried to compile my project (L5.2) using the repo mode in hhvm and got an error:
`Exception: class_alias with non-literal parameters is not allowed when WholeProgram optimizations are turned on`

Is there a way to remove facade's logic which causes this (AliasLoader) since I don't use the facades anyway?

also found this: https://github.com/facebook/hhvm/issues/867

**Comment by iangcarroll** [comment]
While I support the ability to disable it, I assume there are a lot of packages that assume facades exist, so it might not be possible to practically disable facades.

**Comment by GrahamCampbell** [comment]
> Is there a way to remove facade's logic which causes this (AliasLoader) since I don't use the facades anyway?

I doubt this will ever happen. Laravel needs this outside facades too.

>  I assume there are a lot of packages that assume facades exist, so it might not be possible to practically disable facades.

No package should ever use facades, and especially never use facade aliases.

**Comment by GrahamCampbell** [comment]
> No package should ever use facades, and especially never use facade aliases.

Unfortunately, I see a lot of poorly written packages that do use them though. Facades are intended to speed up application development. Libraries and packages are still expected to use proper code.

**Comment by jschlies** [comment]
The quicker we can get rid of Facades, the better.
