### ISSUE TITLE
Route bind not working on POST routes.

### ISSUE THREAD

**Issue by platedodev** [laravel/framework#13681]
I've this on my routes.php:
```
Route::get('/exchange/{from}/to/{to}', 'HomeController@operations_form');
Route::post('/exchange/{from}/to/{to}', 'HomeController@operations');
```
and this on my router providers:
```
public function boot(Router $router)
    {
        //

        parent::boot($router);

        $router->bind('from', function($value) {
            return \App\Currency::where('iso', $value)->firstOrFail();
        });

        $router->bind('to', function($value) {
            return \App\Currency::where('iso', $value)->firstOrFail();
        });
    }
```
Working great on GET, I'm using **from** and **to** on my view. But POST is a different story, I'm trying to use **$request->from** and **$request->to** but I'm getting 

> Trying to get property of non-object

Any idea of how to fix it?

**Comment by platedodev** [comment]
I'm using Laravel 5.2.29.

**Comment by n7olkachev** [comment]
Don't you forget to type hint `request`?

**Comment by platedodev** [comment]
I didn't, I'm using request to validate all the data.

**Comment by lagbox** [comment]
>I'm trying to use $request->from and $request->to but I'm getting

>>    Trying to get property of non-object

Would tell you that `$request` isn't an object. There exists no `$request` var in the current scope that is an object. Thats just PHP.

If you are trying to do this inside a Form Request, it is a Request itself.
```php
$this->param;
$this->route('param');
// etc ...
```

Also if you know you want a route parameter its best to be explicit and use `$request->route('param')`.
