### ISSUE TITLE
[Homestead] Don't run composer with xdebug

### ISSUE THREAD

**Issue by CupOfTea696** [laravel/framework#13690]
Would it be possible to disable xdebug for composer by default in the homestead box? Currently, it'll throw a warning `"You are running composer with xdebug enabled. This has a major impact on runtime performance."` for every composer command.

**Comment by GrahamCampbell** [comment]
Xdebug is very useful for development, which is why it's installed. The actual effect on composer isn't that big on composer. In my testing, I couldn't even notice any change at all by disabling the extension. Only a minor different by actually uninstalling the extension.

**Comment by CupOfTea696** [comment]
I didn't mean disable xdebug entirely, just for composer. Can be done with an alias for php as suggested on the [composer website](https://getcomposer.org/doc/articles/troubleshooting.md#xdebug-impact-on-composer). Alternatively, the warning could be disabled by default by running `export COMPOSER_DISABLE_XDEBUG_WARN=1` somewhere, if the impact of xdebug really is that small.

**Comment by GrahamCampbell** [comment]
Seems fine to me. Feel free to send a PR I guess.

**Comment by CupOfTea696** [comment]
Where would I do that? Because I think the best place to do this may be `/etc/profile` but I have no idea which repo I need to do that.

**Comment by CupOfTea696** [comment]
@GrahamCampbell Could you point me in the right direction? Thanks!
