### ISSUE TITLE
TINYINT value casted as string when using MySQL 5.7

### ISSUE THREAD

**Issue by wout** [laravel/framework#13691]
I noticed a strange issue with illuminate/database 5.2.32 when using MySQL 5.7.11 and PHP 5.5.9. TINYINT values are casted as a string rather than an integer in PHP. On my local development machine with illuminate/database 5.2.32, MySQL 5.6.29 and PHP 5.6.19 this is not the case. I'm not sure if MySQL 5.7 is at the source here but that's the most significant difference between the two environments.

**Comment by lagbox** [comment]
Do you have the mysql native driver installed?

**Comment by billmn** [comment]
@wout Some updates about that?

**Comment by wout** [comment]
Sorry for the delayed response guys.
I'll have to check on that because the MySQL 5.7 has been installed by another party.

**Comment by themsaid** [comment]
@wout @billmn any update about this issue? Was anyone able to replicate the issue on a recent laravel release?

**Comment by wout** [comment]
@themsaid Thanks for the follow-up. The project I'm using it in is currently on hold but will be picked up pretty soon. So when I get to it I'll let you know.

**Comment by themsaid** [comment]
Well I think the problem here can't be related to laravel, it might be a problem with PHP or MySQL.

I'm closing this for now, but please feel free to ping me if you ever got the chance to replicate the problem.
