### ISSUE TITLE
Collection::slice() method should have a 3rd parameter to preserve keys

### ISSUE THREAD

**Issue by mwerezi** [laravel/framework#13692]
According to the documentation for the slice method, there is a 3rd parameter for preserving the keys when using the slice method (https://laravel.com/docs/5.2/collections#method-slice)

However this is not the case and Collection::slice passes true by default to array_slice. Shouldn't there  be a 3rd parameter to pass on to array_slice?

**Comment by billmn** [comment]
I think this issue can be closed.
