### ISSUE TITLE
withTrashed() not setting relations on child relations (hasMany)

### ISSUE THREAD

**Issue by mblarsen** [laravel/framework#13696]
`withTrashed()` is not setting the object on child relations if the parent is deleted. Example:

* Product hasMany('Variant')
* Variant belongsTo('Product')

Normally I would fetch products with variants:

    Product::with('variants')->get();

Then on all of the variants I can access the product object:

    $variant->product

After deleting the product then this is no possible using `withTrashed()` in this case `$variant->product` is `null`.

Note: Setting belongsTo('Product')->withTrashed() on Variant will work. 

Laravel Version: v5.2.32

**Comment by themsaid** [comment]
I don't see a problem here, if the product was trashed then trying to get it via `->product` won't work, you'll need to use with trashed. Don't think it's a bug!

**Comment by mblarsen** [comment]
@themsaid well it is kind of a gray zone isn't it? Because I did use it with `withTrashed()` but on the parent relation. 

So the object that is fetched and I have a reference to in my code only have one part of the relationship set up.

    $first_product = $product = Product::withTrashed()->with('variants')->first()
    $first_variant = $first_product->variants->first();

In this case I would assume that:

    $first_product === $first_variant->product

Otherwise the reverse of the relationship is missing. 

Semantically this is different from setting `withTrashed()` on the the `belongsTo()` relationship:

    public function product()
    {
        return $this->belongsTo('Product')->withTrashed();
    }

Although practically I see that it makes little difference in one-to-many relationships.
