### ISSUE TITLE
array_column on collections

### ISSUE THREAD

**Issue by shopblocks** [laravel/framework#13717]
On a collection, it should be possible to do

```php
$collection->column('id');
```

to get the same result as what 
`array_column($array, 'id');` 

would give you.

Currently, I have had to go by using something like this:

```php
$uuids = $collect->map(function($category) {
    return $category->id;
});
```

Unless i'm missing something, there is no column method on collections?

**Comment by shopblocks** [comment]
Ah, it appears that `pluck` does this.

Would it make sense to have an alias for `pluck` as `column` since thats what the method is called in PHP?

**Comment by morloderex** [comment]
@shopblocks pluck makes perfect sense. 

You are plucking `id` column out of the array and creating a new one.

**Comment by chriscalip** [comment]
For anyone googling around
$collection->terms->pluck('name')->toArray();
