### ISSUE TITLE
Misleading error if a required extension is missing. 

### ISSUE THREAD

**Issue by salarmehr** [laravel/framework#13713]
When one Laravel required php extension is missing, app does not bootstrap correctly and an awkward exception is thrown. `Uncaught ReflectionException: Class log does not exist`. Checking all required extension and returning a better message is necessary.

**Comment by GrahamCampbell** [comment]
This is a known bug. We don't have a fix yet, sorry.

**Comment by GrahamCampbell** [comment]
See https://github.com/laravel/framework/issues/11756.
