### ISSUE TITLE
[5.2] Ignore or reorder route parameters in controllers.

### ISSUE THREAD

**Issue by znck** [laravel/framework#13714]
If unused route parameters can be ignored in controllers, then we have cleaner controllers. 
For example: If route is `{user}.example.com/{lang}/posts/{post}`, then I wish if controller could be just `function(Post $post) {}`.

Found a workaroun: If `Illuminate\Routing\RouteDependencyResolverTrait` [L61](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Routing/RouteDependencyResolverTrait.php#L61) could be replaced with:
```php
if (! is_null($instance)) {
    $this->spliceIntoParameters($parameters, $parameter->getPosition(), $instance);
} else {
    $this->spliceIntoParameters($parameters, $parameter->getPosition(), array_get($parameters, $parameter->getName()));
}
```
Then it works fine.

**Comment by GrahamCampbell** [comment]
Feel free send a PR with a couple of tests, and we'll take a look. Thanks. ;)
