### ISSUE TITLE
Many to many polymorphic with multiple sub-models sync() problem

### ISSUE THREAD

**Issue by reefki** [laravel/framework#13725]
I created two sub-model `Category` and `Tag` which extends the `Term` model. Both sub models are have many-to-many polymorphic relation to `Post` model with pivot table `termables`.

```
// Post.php
class Post extends Model
{
    public function categories()
    {
        return $this->morphToMany(Category::class, 'termable', 'termables', 'termable_id', 'term_id');
    }

    public function tags()
    {
        return $this->morphToMany(Tag::class, 'termable', 'termables', 'termable_id', 'term_id');
    }
}
```

```
// Term.php
class Term extends Model
{

}
```

```
// Category.php
class Category extends Term
{
    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope(new TypeScope('category'));
    }

    public function posts()
    {
        return $this->morphedByMany(Post::class, 'termable', 'termables', 'term_id', 'termable_id')
    }
}
```

```
// Tag.php
class Tag extends Term
{
    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope(new TypeScope('tag'));
    }

    public function posts()
    {
        return $this->morphedByMany(Post::class, 'termable', 'termables', 'term_id', 'termable_id')
    }
}
```

The `attach()` & `detach()` are works but the problem is when using `sync()` method when updating the categories and tags together, either tags got removed when `sync()` the categories or the categories got removed when updating the tags

 Looks like Laravel doesn't check first what is the model of `term_id` that I've actually declared by `$this->morphToMany(Category::class, 'termable', 'termables', 'termable_id', 'term_id');` before removing and just simply remove everything by `termable_type`.

The possible solution that might works is by separate the pivot table for each sub model `categorizables` and `taggables` instead of using single `termables` pivot. But it will makes my database full of pivot tables if I decided to create another set of `Term`'s sub-models.

**Comment by reefki** [comment]
Do you have better ideas? or perhaps I'm do it wrong?

**Comment by GrahamCampbell** [comment]
Thanks for the report. Please can you provide the exact Laravel version you are using?

**Comment by reefki** [comment]
@GrahamCampbell sorry for delay, I'm using Laravel 5.2

**Comment by themsaid** [comment]
@reefki are you still facing the same issue in 5.2 or 5.3?

**Comment by themsaid** [comment]
I'm closing this since it's actually wrong, nothing in the `termables` table says if the term is a Tag or a Column, we can never know this. That's not how Many To Many Polymorphic Relations is intended to work.
