### ISSUE TITLE
Mutator should be applicable while updating 

### ISSUE THREAD

**Issue by umermalik129** [laravel/framework#13735]
I have a scenario I am using calendar for dates and my client want different format on calendar and I store dates as timestamps

While creating new record mutator works and change the time format but when try to update record mutator doesn't called `$model->update(['date' => $date])`

`setAttribute` should also be called inside `performUpdate` method

**Comment by lagbox** [comment]
It should as `update` is filling the model via `fill` then calling `save`. `fill` will call `setAttribute` as it loops through the attributes passed to it.
