### ISSUE TITLE
Documentation Needed: Memcache and Session Lifetime

### ISSUE THREAD

**Issue by pvormittag** [laravel/framework#13745]
When switching from the File session driver to the Memcached session driver, I encountered an issue where no session data would persist across requests. The issue manifested itself in various ways, making debugging difficult. I eventually discovered the issue to be that `lifetime` was set to `604800` in `config/session.php` which causes Memcache to view the value as a Unix timestamp instead of an offset in seconds from current time (http://php.net/manual/en/memcached.expiration.php). Once I set the value to or below `43200` (30 days in minutes), session data persists and works as expected.

It would be helpful to add a note in Laravel's documentation that your configuration for session lifetime cannot exceed `43200` when using the Memcached driver.

**Comment by billmn** [comment]
Can you send a PR to https://github.com/laravel/docs?
