### ISSUE TITLE
Change App name

### ISSUE THREAD

**Issue by KhaledSMQ** [laravel/framework#13748]
Hi, After change Application name using ``` php artisan app:name Foo ``` might face problem if config cached files already exist in the bootstrap cache folder and will start getting error
```
 [Symfony\Component\Debug\Exception\FatalThrowableError]          
  Fatal error: Class 'App\Providers\AppServiceProvider' not found                                                            

```
once remove config cache files from bootstrap folder everything works fine , is it possible to clear the cache before rename the app.
i was thinking to do like 
```
php artisan config:clear 
// then
php artisan app:name Foo
```

**Comment by themsaid** [comment]
I think the `cache:clear` the command is the one you should be using.

**Comment by KhaledSMQ** [comment]
@themsaid 
if the config file already created and you change the name then you tired to clear the cache it will not work the bootstrap class will keep looking to the old namespace service providers.
```
      21 => 'App\\Providers\\AppServiceProvider',
      22 => 'App\\Providers\\AuthServiceProvider',
      23 => 'App\\Providers\\EventServiceProvider',
      24 => 'App\\Providers\\RouteServiceProvider',
          ..............
```
@GrahamCampbell since this close, if there is a tips or something i miss to read the in the documentation please share it.

**Comment by themsaid** [comment]
Th believe the steps should be:

1. Change the app name.
2. Update the calls to the providers.
3. Clear cache.

**Comment by KhaledSMQ** [comment]
I Am talking about cache directory inside the bootstrap folder like this
```
// you need to run "php artisan config:cache" first
myblog/bootstrap/cache/config.php
// then try to change the app name.
```
