### ISSUE TITLE
column biginteger return truncated;

### ISSUE THREAD

**Issue by Litiano** [laravel/framework#13747]
Database: SQLServer 2008
PHP Version 7.0.6
column "od" is biginteger;
$model->od return truncated;

example:
value of od in database is 16137023795;
$model->od return 2147483647;

in dd($model) attributes show normally 16137023795 value;

I'm sorry for English. I am still an apprentice.

**Comment by Litiano** [comment]
solve using:
protected $casts = ["od"=>"float"]; in model

**Comment by GrahamCampbell** [comment]
Casting to a float will NOT fix this. It will just give you an approximation of the integer. You'll loose the last few digits. You can fix this by upgrading to a 64-bit version of PHP.
