### ISSUE TITLE
Queue: (JobProcessed Event) $event->job->getName() returns incorrect ClassName

### ISSUE THREAD

**Issue by AadilC** [laravel/framework#13752]
Hi,

I've come across this issue when while trying to retrieve the __Job Class__ using the __JobProcessed Event__ in the __AppServiceProvider__.

```php
 public function boot() {
    Queue::after(function (JobProcessed $event) {
        
        $class= get_class($event->job);
        echo "class: $class \r\n";
        // class Illuminate\Queue\Jobs\RedisJob

        $name = $event->job->getName();
        echo "name: $name \r\n";
        // name: Illuminate\Queue\CallQueuedHandler@call
        // expected value is App\Jobs\CollectEntries or CollectEntries
        });
}
```
furthermore echoing the ```$event->job->getRawBody()``` indicates the correct class name in the ```data:{"command":"O:42:"App\Job\CollectEntries....``` using```$event->job->getQueue()`` does however return the correct queue. 

Is there another method (i cannot seem to find one in the source or docs) to distinguish between executed jobs.

**Comment by GrahamCampbell** [comment]
Thanks for the report. We made some changes in L5.3. Could you please let us know if this is still incorrect there, and open a new issue if it. Thank you so much!

**Comment by thiagolcks** [comment]
I'm using Laravel 5.5 and getting the same issue, the only difference is that I'm using Queue::failing/JobFailed instead of Queue::after/JobProcessed.

Is there a way to get the Job class name instead of `Illuminate\Queue\CallQueuedHandler@call `?

**Comment by mfn** [comment]
Hmm, in my code I'm calling `$event->job->resolveName()`, does that help?

**Comment by noamanahmed-omniful** [comment]
@mfn 

Yes it does work. Thank you!
