### ISSUE TITLE
Auth Doesnt work inside Policy

### ISSUE THREAD

**Issue by ctf0** [laravel/framework#13753]
its kinda dump but currently i have an app where user can edit his profile info so am checking is 
`Auth::user()->username == $user->username` 

which works well in either **View & Controller** but not in the UserPolicy class, 
not sure if this is intentional or is it a bug on my side only ?

using the latest release v5.2.34

**Comment by lagbox** [comment]
There really is no reason to use Auth inside your policy like that to get the user. The methods receive the currently authed user as the first argument to the ability methods defined in the policy.

**Comment by ctf0** [comment]
@lagbox can u plz give me an example maybe am missing something out.

**Comment by lagbox** [comment]
```php
public function update(User $user, Post $post)
{
    return $user->id === $post->user_id;
}
```
The `User $user` is automatically given to this method as authorization works on the current authenticated user by default.

[Laravel 5.2 Docs - Authorization - Policies - Writing Policies](https://laravel.com/docs/5.2/authorization#policies)

**Comment by ctf0** [comment]
this i understand but the issue is what if u have a user profile page viewd by different "logged in user" how to prevent the logged in user from editing the other user profile, 
thats why i use  `Auth::user()->username == $user->username` but in the policy the `$user` is automatically bind to the logged in user, so how do u distinguish between both ?

**Comment by lagbox** [comment]
You have to pass the 'resource' you want to authorize to what ever method you are calling.
If you are doing this via controller authorization:

```php
// controller
public function edit(User $user)
{
    $this->authorize($user);
    ...
}
```
Policy
```php
public function edit(User $user, User $other)
{
    return $user->id === $other->id;
    // or username == username  how ever you want to compare
    // $user is the current authed user, $other is the one you pass into the authorize method
}
```

**Comment by ctf0** [comment]
oooooh, now it makes much more sense, much appreciated @lagbox :metal:
