### ISSUE TITLE
No supported encrypter found issue

### ISSUE THREAD

**Issue by ubilli** [laravel/framework#13764]
When i post my form on my laravel (5.2) i get this when it has to return some value to the former page.

**MY CONTROLLER**

       class WsRegisterController extends Controller{

       public function register()
       {
       $wsregistration = Input::all();
        $wsUserName = Input::get('name');
       $wsUserEmail = Input::get('email');
       $wsUserPassword = Input::get('password');

    /* Check if user is a bot */

    $wsrules = [
    // 'g-recaptcha-response' => 'required|recaptcha', capthcha
    'name'   => 'required|min:2|max:32',
    'email'  => 'required|email',
    'password' => 'required|alpha_num|min:8'
    ];

    $wsvalidator = Validator::make($wsregistration, $wsrules);

    if ($wsvalidator->passes()) {

        /* Check if the email address exits */

        $wsUser_count = User::where('email', '=', $wsUserEmail)->count();

        // return $wsUser_count; exit;

        if ( $wsUser_count > 1 ) {

            return Redirect::to('/test')->with(array('error_msg' => 'This email address exist, please use another email address.'));

        }
         }
        }
       }
So i tried stackoverflowing it with this link but it is still not working

**CONFIG/APP.PHP FILE**

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| This key is used by the Illuminate encryption service and should be set
| to a random, 32 character string, otherwise these encrypted strings
| will not be safe. Please do this before deploying an application!
|
*/

'key' => env('o/tPhyhKmuLoJMWXZeV8b10OFoCT62z6WKuC3HO5Jbw='),// env('9TSL9BsEjZyoM9BjX9du0XaLnCDi4m4Z'),

'cipher' => 'AES-128-CBC',//'AES-256-CBC',
.ENV FILE

APP_KEY=base64:o/tPhyhKmuLoJMWXZeV8b10OFoCT62z6WKuC3HO5Jbw=
APP_URL=http://localhost
I even did this artisan command to generate new key php artisan key:generate please what did i do wrong @everyone.

**Comment by GrahamCampbell** [comment]
You probably forgot to run `php artisan config:cache`. Make sure you replace that encryption key now that it's public/

**Comment by GrahamCampbell** [comment]
Don't change the cipher from the default unless you really have to.

**Comment by aledmb** [comment]
@GrahamCampbell looks like ```php artisan config:cache``` did it for me!

i had everything configured properly (generated key, cipher on AES-256-CBC, csrf token sent with request), but somehow the server would return a 500 error randomly on an ajax request, sometimes with "no supported encrypter found", other times with "fe_sendauth: no password supplied".

it was really random outcome with an ajax request, but hitting the URL with the browser never returned any errors.

thanks a lot!
