### ISSUE TITLE
[5.1] Eloquent memory issue in v5.1.36

### ISSUE THREAD

**Issue by boonpin** [laravel/framework#13768]
I encounter the memory issue on latest update v5.1.36

> PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 45 bytes) in E:\workspace\phpstrom\hsia-webapp\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php on line 1011

code sample:
`query->get()->load('relations')->toArray()`
when I remove `toArray()` then the memory issue gone.

It is a bug, anyway, I roll back to v5.1.35 and it's running fine on the same code.

**Comment by ctf0** [comment]
same here, but it seems that version was downgraded to v31 https://packagist.org/packages/laravel/laravel , reupdate and see if the issue is solved or not.

**Comment by GrahamCampbell** [comment]
> same here, but it seems that version was downgraded to v31 https://packagist.org/packages/laravel/laravel , reupdate and see if the issue is solved or not.

Not sure what yoyu mean? Laravel tags are found on laravel/framework, not laravel/laravel.

**Comment by ctf0** [comment]
okay, my bad, what i meant is that the version was pumped up then downgraded again so maybe that was the reason behind the error, however let me re-update and get back to u with the changes.

**Comment by GrahamCampbell** [comment]
> pumped up then downgraded again

We have not withdrawn any releases?

**Comment by ctf0** [comment]
i just updated 2 days ago and the version i have is **v5.1.36**, also the version at the main post is **v5.1.35** while the current is **v5.1.34** so ?

**Comment by GrahamCampbell** [comment]
The current LTS version is **v5.1.36** and the current stable is **v5.2.34**.

**Comment by ctf0** [comment]
aha okay, i thought the update should always work on the stable channel unless changed to something else.

**Comment by taylorotwell** [comment]
Can we see the real code a sample of the real model?

**Comment by taylorotwell** [comment]
Also need full stack trace.

**Comment by taylorotwell** [comment]
Basically we need to be able to recreate this.

**Comment by ctf0** [comment]
@GrahamCampbell its kinda dump but i just realised that the post is about 5.1 not 5.2, my bad sorry 😢

**Comment by taylorotwell** [comment]
Any news on this?

**Comment by boonpin** [comment]
@taylorotwell sorry not able to provide the actual code and test data for the moment.

I did check on my code, I believe is cause by too much of relations load on my Model attribute functions.

in my mode class have a functions:
```
protected $appends = ['display_username', 'user_type'];
public function getDisplayUsernameAttribute() {
        if (empty($this->radCheckUserType) == false) {
            $radCheckUserType = null;
            foreach ($this->radCheckUserType as $item) {
                $radCheckUserType = $item["value"];
            }
            if (empty($this->socialUser->userInfo) == false) {
                $displayUsername = $this->socialUser->userInfo->name;
            }
            return $displayUsername;
        }
        return null;
}
....
....
....
//relations
public function socialUser()
{
        return $this->hasOne('\App\Model\SocialUser', 'username', 'username');
}
```

when calling `toArray()`, Model class will call the relation function `socialUser()`, where the `socialUser` Model contains more others relation to load.

I do not have the full stack, the only error found it's from PHP error. (my php memory limit is 128M)

> PHP Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 45 bytes) in E:\workspace\phpstrom\hsia-webapp\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php on line 1011

So far this my observe, I hope this info able to help.

Anyway, thanks for concern on this, I may try upgrade to **v5.2.**

**Comment by GrahamCampbell** [comment]
> Anyway, thanks for concern on this, I may try upgrade to v5.2.

If there is a bug, we need to ensure the latest 5.1 LTS is working.

**Comment by boonpin** [comment]
@GrahamCampbell great, i did try to duplicate the issue, not sure if I'm correct

I got 2 tables (TableA and TableB), i join the TableC & TableA with `username`

below is my TableC mode.
```
class TableC extends Model
{
    protected $table = "table_c";

    protected $appends = ['is_online'];

    public function getIsOnlineAttribute()
    {
        return $this->tableA->isEmpty() == false;
    }
    
    // ------ relations
    public function tableA()
    {
        return $this->hasMany('App\Model\TableA', 'username', 'username');
    }
}
```

I simple query the TableC from my controller

```
class TestingController extends Controller
{
    public function index()
    {
        dd(TableC::all()->toArray());
    }
}
```
I encounter infinite loop when run it.

Then it's working fine when i change the name as below (change the db table column name to `username1`):
```
public function tableA()
{
        return $this->hasMany('App\Model\TableA', 'username1', 'username');
}
```

Is it bug? or I code wrongly?

**Comment by ctf0** [comment]
@GrahamCampbell was any feature added recently that have a limit of `134217728 bytes` cuz am getting the same type of error on something else in v5.2 ? 

my php limit is 128M as well.

**Comment by GrahamCampbell** [comment]
// cc @dietercoopman

**Comment by GrahamCampbell** [comment]
@boonpin or @dietercoopman. Could you please provide us with a full **stack trace** so that we can investigate this.

**Comment by taylorotwell** [comment]
I would want to see full model examples and full code where your calling isset

**Comment by taylorotwell** [comment]
We NEED to recreate this, basically. On a fresh Laravel project.

**Comment by dietercoopman** [comment]
hi , I understand you need to recreate this, but you also understand that it's not so easy to extract some complicated code to a fresh Laravel project ... I'll try to extract it, but - maybe a quick win - if i look at the code we have, i think this two parts could be the "problem".

This code builds aan array of "eenheden" <- dutch for units ( mm,  cm , meter ) , and the possibility to convert the , for example cm to meter , mm to meter.

Repository 

```  /**
     * build basic array of parent and children for a 'eenheidsconversie'
     * @param $eenheidconversies
     * @param null $rootid
     * @param bool $inverse
     */
    private function buildBasic($eenheidconversies, $rootid = null, $inverse = false)
    {
        $to = ($inverse) ? "id_arteenheid_1" : "id_arteenheid_2";

        foreach ($eenheidconversies as $eenheidsconversie) {
            if (!empty($eenheidsconversie->id)) {
                $rootid = $eenheidsconversie->id_arteenheid_1;
            }
            if (!isset($this->convertables[$rootid])) {
                $this->convertables[$rootid] = [$eenheidsconversie->$to, $rootid];
            } else {
                array_push($this->convertables[$rootid], $eenheidsconversie->$to);
            }
            //build convertables for parents
            if (!empty($eenheidsconversie->parents)) {
                $this->buildBasic($eenheidsconversie->parents, $rootid, true);
            }
            //build convertables for children
            if (!empty($eenheidsconversie->children)) {
                $this->buildBasic($eenheidsconversie->children, $rootid);
            }
        }

    }
```

Model 

```
	public function children(){
		return $this->hasMany('\Models\Eenheidconversie', 'id_arteenheid_1', 'id_arteenheid_2')->select(array('id_arteenheid_1','id_arteenheid_2'))->with('children');

	}

	public function parents(){
		return $this->hasMany('\Models\Eenheidconversie', 'id_arteenheid_2', 'id_arteenheid_1')->select(array('id_arteenheid_1','id_arteenheid_2'))->with('parents');

	}
```

**Comment by taylorotwell** [comment]
Which line is actually errroing?

**Comment by dietercoopman** [comment]
This is the full stack trace 

[error.txt](https://github.com/laravel/framework/files/291446/error.txt)

**Comment by dietercoopman** [comment]
line 169 is => $this->buildBasic($eenheidsconversie->parents, $rootid, true);
line 173 is => $this->buildBasic($eenheidsconversie->children, $rootid);

**Comment by taylorotwell** [comment]
Can you describe these model relationships a bit more? It looks like the `children` method also calls `->with('children')`?

**Comment by dietercoopman** [comment]
these relations tell us the possible unit conversions for our system , for example 
cm can be converted to meters , mm to cm , ...  (   children ) 
and the inverse ( parents ) , meters can be converted to cm

i assume the eager loading of children is not the problem, because we do the same for our menu and it works like a charm and saves u tons of sql's , this gets us all submenu's recursively

```/**
	 * @return mixed
	 */
	public function children()
	{
		return $this->hasMany('\Models\Menu', 'MNU_rootid', 'idMenu')->orderBy('MNU_volgorde')->with('children');
	}
```

**Comment by dietercoopman** [comment]
@taylorotwell  , i don't know if you have seen my original post , but if i upgrade to laravel 5.1.36 , and after that i change the Illuminate model.php to its 5.1.35 version everything works again 

this commit changed the model.php https://github.com/laravel/framework/commit/45fb88125fc931127804c1da111b72798565e9a7

**Comment by taylorotwell** [comment]
@dietercoopman what if you just change Eloquent's `isset` method to simple this one line:

```
    public function __isset($key)
    {
        return ! is_null($this->getAttribute($key));
    }
```

Does it work?

**Comment by dietercoopman** [comment]
nope , if i change it to its v5.1.35 than it works , so i have a laravel 5.1.36 with only the __isset part changed to its 5.1.35 equivalent and it works

````
return (isset($this->attributes[$key]) || isset($this->relations[$key])) ||
                 ($this->hasGetMutator($key) && ! is_null($this->getAttributeValue($key)));
```

**Comment by taylorotwell** [comment]
You can the same error when you paste that one line I gave?

**Comment by dietercoopman** [comment]
i can send you the stack trace , it's the same error

**Comment by taylorotwell** [comment]
Somehow the relationships you have defined are spinning into an infinite loop. What version of PHP are you running this on?

**Comment by dietercoopman** [comment]
PHP 5.5.9-1ubuntu4.7 (cli) (built: Mar 16 2015 20:48:03)

**Comment by taylorotwell** [comment]
So those relationships I mentioned earlier: parent and children. What is the name of that model? Is the model referencing itself? I'd like to try to recreate a similar setup.

**Comment by dietercoopman** [comment]
jup they reference theirselves ( will remove some members , little bit security ) 
```
<?php namespace Models;

class EenheidConversie extends BaseModel {

	public function children(){
		return $this->hasMany('\Models\Eenheidconversie', 'id_arteenheid_1', 'id_arteenheid_2')->select(array('id_arteenheid_1','id_arteenheid_2'))->with('children');

	}

	public function parents(){
		return $this->hasMany('\Models\Eenheidconversie', 'id_arteenheid_2', 'id_arteenheid_1')->select(array('id_arteenheid_1','id_arteenheid_2'))->with('parents');

	}
}

```

**Comment by taylorotwell** [comment]
If you are saying ->with(‘children’) on the children method itself, how will that ever stop loading? It will keep eager loading the “children” relationship forever.

**Comment by taylorotwell** [comment]
I can't really proceed with anything until someone can product the problem on a fresh Laravel installation unfortunately.

**Comment by dietercoopman** [comment]
but if it has no children will return NULL ? so stops ? It worked great on laravel 5.1.35 

I'll try to recreate a very simple example with the same data later in the evening

**Comment by taylorotwell** [comment]
What if your `__isset` method is this?

```
    public function __isset($key)
    {
        if (isset($this->attributes[$key]) || isset($this->relations[$key])) {
            return true;
        }

        return ! is_null($this->getAttribute($key));
    }
```

**Comment by dietercoopman** [comment]
nope , 

i'am a little bit confused 


if i extract everything to my route file , than te route "ok" works , and "notok" does not work , and i'm getting exactly the same model , the one with collection the other the model itself

````

function buildBasic($eenheidsconversies)
{
    foreach ($eenheidsconversies as $eenheidsconversie) {

        if (!empty($eenheidsconversie->parents)) {
            buildBasic($eenheidsconversie->parents);
        }
        //build convertables for children
        if (!empty($eenheidsconversie->children)) {
            buildBasic($eenheidsconversie->children);
        }
    }

    return "test";
}


function buildBasicOk($eenheidsconversie)
{
        if (!empty($eenheidsconversie->parents)) {
            buildBasicOk($eenheidsconversie->parents);
        }
        //build convertables for children
        if (!empty($eenheidsconversie->children)) {
            buildBasicOk($eenheidsconversie->children);
        }

    return "test";
}

Route::get('ok',function(\Models\EenheidConversie $eenheidConversie){

    return buildBasicOk($eenheidConversie->first());
});

Route::get('notok',function(\Models\EenheidConversie $eenheidConversie){

    return buildBasic($eenheidConversie->take(1)->get());
});
```

i even changed my model to this 

```
	public function children(){
		return $this->hasMany('\Models\Eenheidconversie', 'id_arteenheid_1', 'id_arteenheid_2')->select(array('id_arteenheid_1','id_arteenheid_2'));

	}

	public function parents(){
		return $this->hasMany('\Models\Eenheidconversie', 'id_arteenheid_2', 'id_arteenheid_1')->select(array('id_arteenheid_1','id_arteenheid_2'));

	}
```

**Comment by dietercoopman** [comment]
table looks like this , very simple  
![schermafbeelding 2016-05-31 om 18 29 46](https://cloud.githubusercontent.com/assets/4672752/15682388/b79097e0-275d-11e6-8155-59d4f6de3de4.png)

**Comment by taylorotwell** [comment]
Yeah, until there is a simple example I can copy and paste into my own routes file it will be hard to say for sure what is happening with your models. I suspect their is a problem internally with your model / relationship definitions that was being hidden by the prior broken behavior of `isset`.

**Comment by dietercoopman** [comment]
i'll make a simple example later in the evening ( it's now +-7pm here ), and provide you a sql file

**Comment by dietercoopman** [comment]
@taylorotwell i made a very simple example 

DDL 

```
CREATE TABLE `eenheidconversie` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `id_arteenheid_1` bigint(20) unsigned NOT NULL,
  `id_arteenheid_2` bigint(20) unsigned NOT NULL,
  `sleutel` double(15,3) unsigned NOT NULL,
  `_aanmaakdatum` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Datum waarop het record aangemaakt is',
  `_aangemaaktdoor` varchar(50) DEFAULT NULL COMMENT 'Persoon die het record aangemaakt heeft',
  `_gewijzigddatum` datetime DEFAULT '0000-00-00 00:00:00' COMMENT 'Datum dat dit record gewijzigd geweest is',
  `_gewijzigddoor` varchar(50) DEFAULT NULL COMMENT 'Persoon die het record aangepast heeft',
  `_gewijzigddoorip` varchar(20) DEFAULT NULL COMMENT 'Ip van de persoon die het record aangepast heeft',
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`),
  UNIQUE KEY `unique` (`id_arteenheid_2`,`id_arteenheid_1`),
  KEY `id_eenheid_1` (`id_arteenheid_1`),
  KEY `id_eenheid_2` (`id_arteenheid_2`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


INSERT INTO `eenheidconversie` (`id`, `id_arteenheid_1`, `id_arteenheid_2`, `sleutel`, `_aanmaakdatum`, `_aangemaaktdoor`, `_gewijzigddatum`, `_gewijzigddoor`, `_gewijzigddoorip`)
VALUES
	(23,26,25,100.000,'2010-10-20 13:57:59',NULL,'2011-01-25 08:45:13','Dieter Coopman',NULL),
	(24,27,28,60.000,'2010-11-22 09:29:15',NULL,'2010-11-22 09:29:15',NULL,NULL),
	(25,28,21,60.000,'2010-11-22 09:29:40',NULL,'2010-11-22 09:29:40',NULL,NULL),
	(26,23,29,10000.000,'2011-01-25 08:41:06',NULL,'2011-01-25 10:19:47','Dieter Coopman',NULL),
	(27,30,26,10.000,'2011-02-08 09:50:46',NULL,'2011-02-08 09:50:46',NULL,NULL),
	(28,25,32,1000.000,'2011-12-07 16:29:42',NULL,'0000-00-00 00:00:00',NULL,NULL);

```

```

class EenheidConversie extends Illuminate\Database\Eloquent\Model
 {

    public $table = "eenheidconversie";

    public $connection = "mysql_erp";


    public function children(){
        return $this->hasMany('Eenheidconversie', 'id_arteenheid_1', 'id_arteenheid_2');

    }

    public function parents(){
        return $this->hasMany('Eenheidconversie', 'id_arteenheid_2', 'id_arteenheid_1');

    }

    public function buildBasic($eenheidsconversies)
    {
        foreach ($eenheidsconversies as $eenheidsconversie) {
            if (sizeof($eenheidsconversie->parents) > 0) {
                $this->buildBasic($eenheidsconversie->parents);
            }

            if (sizeof($eenheidsconversie->children) > 0) {
                $this->buildBasic($eenheidsconversie->children);
            }
        }

    }

    public function buildBasicOk($eenheidsconversie)
    {
        if (!empty($eenheidsconversie->parents)) {
            $this->buildBasicOk($eenheidsconversie->parents);
        }
        
        if (!empty($eenheidsconversie->children)) {
            $this->buildBasicOk($eenheidsconversie->children);
        }

    }
}


Route::get('ok',function(EenheidConversie $eenheidConversie){

    return $eenheidConversie->buildBasicOk($eenheidConversie->first());
});

Route::get('notok',function(EenheidConversie $eenheidConversie){

    return $eenheidConversie->buildBasic($eenheidConversie->take(1)->get());
});

```

**Comment by taylorotwell** [comment]
What do these words mean in English?

**Comment by GrahamCampbell** [comment]
> i made a very simple example

That example is still quite large. An example about half that size would be really useful.

**Comment by taylorotwell** [comment]
The example is fine with me in length I would just prefer it in English so I can reason about it better.

**Comment by RomainLanz** [comment]
@dietercoopman Note that you should use Nested Set pattern to play with parents/children.

[Baum](https://github.com/etrepat/baum) is a package who manage that.

**Comment by dietercoopman** [comment]
eenheid = unit , sleutel = key , it is all about unit conversion  , if we go from unit 26 to 25 we have a key ( factor ) 100.

There will be other possibilities to calculate everything but we are building around an existing database.

**Comment by taylorotwell** [comment]
IMO you already had a some flawed infinite loop logic that was being masked by weird __isset behavior by Eloquent.

**Comment by taylorotwell** [comment]
The current behavior of __isset is the most logical and correct way of determining isset in terms of model attributes and relations. Because the current logic matches the current logic of __get and simply tells you if the returned value is not null, which is what the behavior of __isset should be.

**Comment by taylorotwell** [comment]
And in your case, a bug in Eloquent was masking your infinite loop by returning false on isset when it should have returned true.

**Comment by dietercoopman** [comment]
:( , there was a bug in the version i posted :( , the buildBasic method is wrong.  I will do some further research and i'll post on it later ... thank guys

edited buildBasic
```
public function buildBasic($eenheidsconversies)
    {
        foreach ($eenheidsconversies as $eenheidsconversie) {
            if (!empty($eenheidsconversie->parents)) {
                $this->buildBasic($eenheidsconversie->parents);
            }

            if (!empty($eenheidsconversie->children)) {
                $this->buildBasic($eenheidsconversie->children);
            }
        }

    }
```

**Comment by dietercoopman** [comment]
I am indeed in a logical infinite loop, case closed , good the bug in eloquent is solved in version 3.1.36.  

First time a 🐞 -fix exposed me a bug 👍

**Comment by taylorotwell** [comment]
Just curious how did you fix it on your end?

**Comment by dietercoopman** [comment]
The problem was ( i try to say it in a human readable example ).  I asked a child who's his father , and asked the father who's his child ... and ... asked the child who's his father ... infinite loop 

Now i store the result for an item in a local array and while i loop,  i check => hey , didn't i see you before ? Then i don't have to ask you who's your parent's and children because i allready know it.   So i keep the recursion but dont' repeat what i've allready did ... so called Memoization

**Comment by YiQiZhang** [comment]
The problem is

**Comment by themsaid** [comment]
@YiQiZhang check @dietercoopman latest comment, you're simply replicating the same problem he had, so please follow his steps to stop this recursive behaviour.
