### ISSUE TITLE
[Feature] Get expiration time of a single cache item

### ISSUE THREAD

**Issue by androschukandriy** [laravel/framework#13772]
While developing high-loading project, I need to know the date when cache will be expired, so I could refresh its value using background jobs before the user requests it.

The framework doesn't provide information about expiration of the cache, so I would like to propose to create a method to implement it so the method will return Carbon instance of expiration time.

```php
$expiredAt = app('cache')->expiredAt('some_cache_id');
```

I could implement it for different cache drivers if this feature will helpful for other too.

**Comment by GrahamCampbell** [comment]
Thanks, vt this isn't possible to easily implement everywhere. See our rate limiter class in the cache component for example. It has to implement expiry on top, because it's not possible natively.

**Comment by androschukandriy** [comment]
@GrahamCampbell, the limiter class does not contains any information about the cache lifetime cause it was not intended to.

To implement the lifetime saving feature in every driver we could easily use array on top of the cache item like the `Illuminate\Cache\FileStore` does. So every cache item will look like this:

```php
 $item = ['value' => $value, 'time' => $time]
```

**Comment by GrahamCampbell** [comment]
I'd recommend using laravel's own rate limiter if you want something that specifically targets throttling http requests.

**Comment by jonnywilliamson** [comment]
Did this ever get anywhere? Or was there any similar proposal accepted?

**Comment by andrewmclagan** [comment]
This would be a super useful feature.

**Comment by dakujem** [comment]
I have a need for this feature, exactly as @andrii-androshchuk stated.

Has anyone solved this elegantly? Share your pointers! I can only think of driver-specific hacks. :hammer:

**Comment by andrii-androshchuk** [comment]
@GrahamCampbell, a few more people have asked about this feature. Maybe it makes sense to provide it?

**Comment by alexbiohacker** [comment]
Have this ever been implemented? :-)

**Comment by jmcgrory** [comment]
Throwing my hat into the "I have a use case" ring, Although I realised miday through writing this up that I had an alternative to address my use case, so have included below incase anyone else winds up here with the same problem.

### 🛠 Use Case 

The component I am testing currently sets the cache duration dynamically based on application configuration for variable caching rates.  

### 💔 Issue 

I can't currently test these durations are set across an array of methods that make use of the facility, and as such I cannot guarantee resources are being cached appropriately.  

### 🤔 Alternatives 

1. **Query the driver directly**
    - i.e. directly query `TTL {key}` for a Redis instance
    - I would need a test for _every_ possible queue driver
    - These tests should be implementation agnostic
2. **Manually delay tests**
    - i.e. `sleep` within a function until an expiration is expected
    - This feels extremely hacky
    - This will slow down my test suite significantly, especially as minimum units is `s` not `ms`!
3. **[Mock Facade Methods](https://laravel.com/docs/5.8/mocking)** ✔️ 
    - Replace `Cache::put` etc. with my own Mocks
    - Test that they are called with expected values
    - **This is the best option I see here and what I have settled on**
    - Defers implementation/correct function of delay to `Cache`

**Comment by pobratym** [comment]
Here is a solution with macro method: https://stackoverflow.com/questions/24723331/laravel-cache-forever-with-possible-expiry

Also, it could be solved with additional cache item. This is not very elegant solution, but it works.
```php
if (!Cache::has('item_key_time')) {
    Cache::put('item_key', 'a data', 604800); // a week
    Cache::put('item_key_time', true, 518400); // 6 days
}
```
