### ISSUE TITLE
Model __isset() breaking when relation value is set to null

### ISSUE THREAD

**Issue by satoshipayne** [laravel/framework#13771]
This is breaking my app when I upgrade from 5.1.35 to 5.1.36.

5.1.35 code:
```
public function __isset($key)
{
    return (isset($this->attributes[$key]) || isset($this->relations[$key])) ||
            ($this->hasGetMutator($key) && ! is_null($this->getAttributeValue($key)));
}
```

5.1.36 code:
```
public function __isset($key)
{
    if (isset($this->attributes[$key]) || isset($this->relations[$key])) {
        return true;
    }

    if (method_exists($this, $key) && $this->$key && isset($this->relations[$key])) {
        return true;
    }

    return $this->hasGetMutator($key) && ! is_null($this->getAttributeValue($key));
}
```

My case is, I eager load the relation in the controller, then in view time:

1. $hub->load('gigs.brand') <-- value of brand is **null** (hub -> hasMany(gig) -> belongsTo(brand))
2. @foreach for $hub->gigs, then enter a partial
3. @if(!is_null($gig->brand)) <-- throws exception here; or
4. @if(isset($gig->brand) && !is_null($gig->brand)) <-- throws exception here; or
5. @if(isset($gig->brand)) <-- throws exception here as well

Exception:
`Undefined property: App\Gig::$brand`

Breaks on this specific call on **$this->$key**:
```
if (method_exists($this, $key) && $this->$key && isset($this->relations[$key])) {
    return true;
}
```

Please confirm if this bug can be replicated and it's not anything specific with my app.

PHP Version run: 5.6.12

Commits in question:
https://github.com/laravel/framework/commit/45fb88125fc931127804c1da111b72798565e9a7#diff-d8e24a5815a26f7211e66db787be647f
https://github.com/laravel/framework/commit/09ea8e2f321195d8518952cdbfa5746c9799cdc1#diff-d8e24a5815a26f7211e66db787be647f

Thank you.

**Comment by taylorotwell** [comment]
Can you tell me a bit about your models? Do you have a brand() method on the model as well as a brand column?

**Comment by taylorotwell** [comment]
Secondly, are you overiding `__get` or using any packages with your Eloquent models?

**Comment by satoshipayne** [comment]
Hi Taylor,

The Gig model has a brand() method, which returns a BelongsTo relation to the Brand model. The gig table has no brand column, but a brand_id column based on the primary key of the brand table.

With your second question about __get(), some further testing seems to indicate that this could be a possible reason why I'm getting this error. Will look into this further.

Thanks.

**Comment by taylorotwell** [comment]
OK feel free to share your `__get` method.

**Comment by taylorotwell** [comment]
Any news on this?

**Comment by satoshipayne** [comment]
Hi Taylor,

It looks like it's caused by overriding the __get() method. Will dig deeper
to see how exactly this breaks this.

Thanks.

**Comment by satoshipayne** [comment]
Hi guys,

It looks like overriding the __get() method would cause unexpected
behaviour in this case. Will flag this one again if I experience further
issues.

Cheers,

Satoshi Payne
