### ISSUE TITLE
[5.2.34] MorphTo inside ::with() calls relation inside morphable entity too.

### ISSUE THREAD

**Issue by lelu85** [laravel/framework#13770]
In that upgrade when you call a MorphTo inside the with model parameter like:

`
/**
     * @var array
     */
    protected $with = [
        'OrderMorph'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\MorphTo
     */
    public function OrderMorph()
    {
        return $this->morphTo();
    }

`

and the model is resolved, then it also calls the same relation OrderMorph inside the MorphTo entity so it leads to a Builder::MorphTo() not found.

If you revert to 5.2.33 it works.

**Comment by phroggyy** [comment]
This should be resolved in https://github.com/laravel/framework/pull/13737.

**Comment by phroggyy** [comment]
@lelu85 this is now in the latest tagged version, 5.2.35.
