### ISSUE TITLE
Artisan console database commands

### ISSUE THREAD

**Issue by taviroquai** [laravel/framework#13795]
Hi,

Could we run database commands in artisan console, ie. update, insert, etc... like we have in mongodb?

I know that it is possible to create these commands, but I'm asking something out-of-the-box.

This question arised  because I needed to update a user password, using the Hash helper... something like this:

`update users set password = Hash::make('admin') where email = 'admin@domain.com'`

Or better, if we could use the Eloquent way:

`App\User::where('email', 'admin@domain.com')->update('password', Hash::make('admin'));`

Cheers

**Comment by GrahamCampbell** [comment]
Thanks, but we don't process requests here. Please review the contribution guidelines.

**Comment by fonini** [comment]
You mean an interactive shell like ````php artisan tinker````?

**Comment by taviroquai** [comment]
OMG that's it the Tinker! Thanks fonini! :)
