### ISSUE TITLE
Blade section include stack problem

### ISSUE THREAD

**Issue by Dimonka2** [laravel/framework#13809]
I have a problem with including blade with a @stack  - not sure whether it is a "normal" behavior but in my opinion not. I have two blades: 

nav.page_header blade
```
<h1>
           @stack('page_header_title')
</h1>
  <div class="breadcrumb">
            @stack('breadcrumbs')                           
   </div>
```
page blade 
```
@extends('layouts.app')

@section('content')
    @include('nav.page_header')

    @push('page_header_title') Page title @endpush                            
    @push('breadcrumbs')
           breadcrumb
    @endpush           		
@endsection
```
For some reason stack bits of nav.page_header blade are just ignored by laravel 5.26/5.27. In my opinion this is a bug.

**Comment by GrahamCampbell** [comment]
We made some bug fixes to that recently. Please clear your view cache, and try again with the very latest 5.2.x.

**Comment by Dimonka2** [comment]
Just updated everything and cleared everything - stacks are empty. 
Actually I was wrong with the version: I have updated form 5.2.34 to 5.2.35

**Comment by sisve** [comment]
It looks like you're rendering those stacks before pushing to them. That means that they have no content at the time of rendering. Could you move those `@push` sections up, either above `@include` or above `@section`?

**Comment by ManuDoni** [comment]
I had the same issue, doing a similar thing.
I've managed it in another way but is it correct that i can only use `@push` before `@stack`?
What if I have to push, for example, some css file to the header from a few child views, without manually include it in the layout (and so include it in all childs)?
It's just a thought not a criticism.
