### ISSUE TITLE
Mail::send doesn't read settings from Config::get but rereads values from .env

### ISSUE THREAD

**Issue by DuckThom** [laravel/framework#13800]
I'm creating a setup process for a Laravel app. The setup has a form for mail settings, (driver, credentials, etc.). I'm trying to implement a "Test settings" function like this:

```
$driver = $request->get('driver')       ?: 'log';
$sender = $request->get('sender')       ?: 'test@sometest.nl';
$port   = $request->get('port')         ?: '25';
$host   = $request->get('host')         ?: 'localhost';
$user   = $request->get('username')     ?: 'testuser';
$pass   = $request->get('password')     ?: '';
$enc    = $request->get('encryption')   ?: 'tls';

\Config::set('mail', [
                "driver"    => $driver,
                "host"      => $host,
                "port"      => $port,
                'from'      => ['address' => $sender, 'name' => 'Test'],
                "encryption"=> $enc,
                "username"  => $user,
                "password"  => $pass,
                "sendmail"  => "/usr/sbin/sendmail -bs"
]);

Mail::send('emails.test', [], function ($m) use ($sender) {
               $m->to($sender);

               $m->subject('Test mail');
});
```

The problem is that, even after using \Config::set('mail'), Mail::send will still use the values that are set in `.env` and `config/mail.php` instead of using the values that I just set.

**Comment by GrahamCampbell** [comment]
This is the expected behaviour. You can't change the config after you've already instantiated the mail object. Well, you can, but it'll not affect the mailer.

**Comment by DuckThom** [comment]
As a workaround, I've copied the code from `Illuminate\Mail\MailServiceProvider` and am now recreating the 'mailer' singleton between `Config::set` and `Mail::send`. I know this is not the proper way to do things, but it works for me.
