### ISSUE TITLE
ShouldQueue don't report notice error in error log file

### ISSUE THREAD

**Issue by rikless** [laravel/framework#13815]
I don't really understand why, but using the last laravel version 5.2.35, when I use the ShouldQueue interface on a Job class, or a Listener class, this kind of code don't report any error in laravel.log file : 

```php
public function handle(EventClassStd $event)
{
    $test = 1;
    $test->test;        
}
```

So I have the job in the failed_jobs table, vu without any stacktrace/logging exception in the log file.

If I remove the ShouldQueue implementation, the log file contains all the informations for debug.

Tested with beanstalkd queue driver, on an old Homestead VM, and on a debian staging server.

**Comment by GrahamCampbell** [comment]
`ShouldQueue` doesn't do anything in Laravel 5.2. All commands are queued regardless.

**Comment by GrahamCampbell** [comment]
Given `ShouldQueue` does absolutely nothing, I don't see how this can be related. It must be another bug in your app.

**Comment by GrahamCampbell** [comment]
Your application is probably fatal erroring.

**Comment by rikless** [comment]
Not any fatal error in http logs, I don't think so.
I'm talking about this https://laravel.com/docs/5.2/events#queued-event-listeners

I don't think this is the ShouldQueue interface itself generating this behavior, but when you listen an event using queued jobs (not the sync driver), then, the queue manager don't handle Monolog error reporting.

**Comment by fideloper** [comment]
Could be related to your environment when running `artisan queue:work` - be sure to add the environment flag to an env that had debugging settings you expect (`--env=local` perhaps, if "production" or other defaults have debugging turned off).

**Comment by rikless** [comment]
I use artisan `queue:listen`

The behavior I've describe has been tested in a production and dev/local environnement.

I thought about a permission issue on the log file, so (just to test) I've setting the log file with 777 but nothing to do.

Same thing on the stdout_logfile from supervisor configuration, and I still got the issue.

**Comment by GrahamCampbell** [comment]
Feel free to discuss on the forums. I don't believe this to be a bug in the framework.

**Comment by rikless** [comment]
The commit which fixed the issue is there https://github.com/laravel/framework/commit/d5bbda95a6435fa8cb38b8b640440b38de6b7f83

In fact, before this fix, I think the _exeptions_ property on the _Worker_ class wasn't set. So this condition was false, and did not reported the issue :
https://github.com/laravel/framework/blob/v5.2.34/src/Illuminate/Queue/Worker.php#L160-L161

**Comment by GrahamCampbell** [comment]
Ah yes, thanks @rikless. This does appear to be simply a bug that has been fixed now.
