### ISSUE TITLE
migration column modifier chaining is not working. 

### ISSUE THREAD

**Issue by atapatel** [laravel/framework#13813]
migration column modifier chaining is not working. e.g

$table->string('namespace')->nullable()->comment("namespace for client"); gives an error. comment is not defined.

**Comment by RomainLanz** [comment]
That's because there's no `comment` method on the Blueprint class.

**Comment by atapatel** [comment]
any solution?

**Comment by RomainLanz** [comment]
You cannot comment column with a migration.

Romain Lanz  
CEO, Slynova
079 960 83 25(tel:079%20960%2083%2025) | www.slynova.ch(http://www.slynova.ch)
