### ISSUE TITLE
[Proposal] Eloquent\Builder::find() working with other columns

### ISSUE THREAD

**Issue by KKSzymanowski** [laravel/framework#13836]
Hi.

My idea is to use `Eloquent\Builder::find()` method to retrieve the first record from database that matches provided column and its value eg.
```
$user = User::find('username', $username');
$product = Product::find('serial_number', $serial_number, ['id', 'description']);
```
I think it might be useful when a table has several unique keys, because you wouldn't have to clutter your Models with methods like
```
public function scopeFindByUsername($query, $username)
{
    return $query->where('username', $username)->first();
}
```

Also it improves the beloved Laravel intuitive syntax because what you really want to do is find a record and it doesn't matter if you find it by primary or unique key. Also, you would perform one less function call.

It's kind of tricky in terms of parameter naming but they can be distinguished easily based on the type.
It's the best I could come up with:

```
public function find($id, $columns = ['*'], $columnsIfKeyNameProvided = ['*'])
{
    if (is_array($id)) {
        return $this->findMany($id, $columns);
    }

    $keyName = $this->model->getQualifiedKeyName();

    $keyValue = $id;

    if(is_array($columns) == false) {
        $keyName = $id;

        $keyValue = $columns;

        $columns = $columnsIfKeyNameProvided;
    }

    $this->query->where($keyName, '=', $keyValue);

    return $this->first($columns);
}
```

Obviously there's field for improvement and the `findOrFail` method would have to be changed.as well to match the `find` method argument list.

**Comment by riyuk** [comment]
-1
Find should only look for the primary key.

Maybe it makes sense to implement "magic methods" so findByUsername works out of the box because `username` is a legit column name and you don't have to explicitly define it with `scopeFindByUsername` while overwriting it with a `scopeFindByUsername` should still be possible.

**Comment by KKSzymanowski** [comment]
You have a valid point. I will write this `magic method` handler and get back to you.
