### ISSUE TITLE
Unknown database type enum requested

### ISSUE THREAD

**Issue by maxi032** [laravel/framework#13832]
I get this error when trying to do a migrate refresh --seed. I have seen that the problem occurred when trying to rename an enum field but this is not my case.

I am using Laravel 5.2

**Comment by bkintanar** [comment]
<img width="606" alt="screen shot 2016-06-02 at 11 31 21 pm" src="https://cloud.githubusercontent.com/assets/685928/15750747/2f5d19fc-291a-11e6-89a7-be379570d9ca.png">

source: https://laravel.com/docs/5.2/migrations#modifying-columns

**Comment by james2037** [comment]
It seems doctrine has tagged this issue WONTFIX. Perhaps we should consider replacing the part that is dependent on doctrine altogether? I would be willing to help contribute a pull request if pointed in the right direction.
