### ISSUE TITLE
[4.2] prepend does not work fluently, does not return anything.

### ISSUE THREAD

**Issue by KuenzelIT** [laravel/framework#13837]
Hey,

I hope I am right here with my question/report to Collections of Laravel 4.2 .

I just saw that the "prepend" function doesn't return anything, so it is not possible to use it fluenty. Is this wanted?

Upgrading to 5.X is currently not possible for me.

Thanks!

**Comment by GrahamCampbell** [comment]
Sorry, L4.2 is not supported.
