### ISSUE TITLE
Translations in queued emails

### ISSUE THREAD

**Issue by glennjacobs** [laravel/framework#13830]
We really need a solution to allow queued emails to be translated. A previous thread was opened before, but closed for no apparent reason. So I'm opening a new issue and referencing it (apologies if that's not the done thing, but it needs addressing as lots of people are struggling with this).

Please see previous issue...
https://github.com/laravel/framework/issues/8392

**Comment by GrahamCampbell** [comment]
Thanks, but we don't process feature requests here. Please review our contribution guidelines.

In all honesty, I think the actual best way to approach this would be to render the views before queuing, then only queue the actual sending part. That's what I have in a private application.

Feel free to open an issue in the correct place to that effect, and try to convince Taylor.

**Comment by glennjacobs** [comment]
> In all honesty, I think the actual best way to approach this would be to render the views before queuing, then only queue the actual sending part. That's what I have in a private application.

I think that's a sensible approach, however you could argue that 'Mail::queue' should be doing that as default and this therefore is viewed as a bug in our eyes, because we expect translations to 'just work'.

**Comment by elasticsteve** [comment]
@GrahamCampbell I don't think this is a "feature" request. It's an essential necessity that has been overlooked by American/English developers! :) What is the status on this? Has a feature request been made for this? I hate to develop this for my app now and 2 weeks later you come out with an update implementing it!

In all honesty, I would have assumed that you pass the original locale into any queue/job! Why would anyone NOT want that? I agree with @glennjacobs that this is a bug! Can you please re-open this?
