### ISSUE TITLE
redundant `r` character in json response

### ISSUE THREAD

**Issue by amin101** [laravel/framework#13855]
I've recently updated laravel framework to latest version 5.2.35 and now noticed json responses have been changed to something like : `"r{"status":1,"name":"nina"}"`
before there was a responseJSON   but now only responseText is available. i'm wondering what is that `r` in front of the response? and how should i transform this string to an array?

EDIT: seems this case occurs in validation.i mean inside `if($validator->fails())` closure

**Comment by billmn** [comment]
Can you show us your code?

**Comment by amin101** [comment]
of course. this is validation part:
```
  $validator = \Validator::make($request->all(),$rules);
        if($validator->fails()){
                 return response()->json($validator->errors()->toArray());
               }
```
this will return:
![gg](https://cloud.githubusercontent.com/assets/14128415/15791387/465510b0-29ec-11e6-9d69-69060398a401.png)

look at that `r` in front of responseText,whats the usage of that character? and how should i turn this string to an array?

**Comment by billmn** [comment]
This seems a Firebug output conversion.

I have used this code:
```php
$validator = Validator::make($request->all(), [
    'username' => 'required',
    'password' => 'required',
]);

if ($validator->fails()) {
    return response($validator->errors(), 422);
}
```

And this is the output of Chrome Console:
![schermata 2016-06-03 alle 22 18 20](https://cloud.githubusercontent.com/assets/779534/15791684/2b002d30-29d9-11e6-8dfb-e814531baa73.png)

**Comment by amin101** [comment]
thanks for reply. i made  a try with your code, but no chance!
![ff](https://cloud.githubusercontent.com/assets/14128415/15792153/b3420e5e-29f0-11e6-9f14-f7b8d45f4755.png)
that strange `r` character doesn't leave me.

**Comment by billmn** [comment]
Please check your code, seems you output this character somewhere in your project. This is not a Laravel issue.

**Comment by amin101** [comment]
which version of laravel are you running? my response is different with you . i dont have an `responseJSON` object in my response while before i had that

**Comment by billmn** [comment]
Laravel 5.2.35

You haven't a responseJSON object because your JSON response is malformed with this "r" character. If you find and remove it will work.

**Comment by amin101** [comment]
@billmn you were right. there was a redundant `r` at the very first line of  `lang/validate.php` . thanks for help
