### ISSUE TITLE
Save method of many-to-many relationship

### ISSUE THREAD

**Issue by iNDicat0r** [laravel/framework#13865]
I want to override the Save method and add some functionalities before the saving of the model to the db is done. Basically i have a tree structure implemented within my db and my model, so my model is a folder model and its a many to many relationship to it's self.
This is the Save method:

`public function save(array $options  = array()){

	return $this;
	return $this->parents()->get();
	if($this->hasDupeSibiling(Auth::user()->id)){
		die("has dupe sibiling");
		//$this->name = $this->getNewName(Auth::user()->id);
	} 
	parent::save($options);

}`

and when I run save method, inside the save method i immediately return the scope of $this, and it's not the actual model but the new model given as arguments to this function (new Folder(['name' => 'BCC'])) 

`$this->folders()->save(new Folder(['name' => 'BCC']) , $pivotData );`

any idea what's going on?

**Comment by ntzm** [comment]
If you want to customise the behaviour of the `save` method, take a look at the [Eloquent Events](https://laravel.com/docs/master/eloquent#events) documentation.

**Comment by srmklive** [comment]
you need to use Eloquent Events. Customizing the save method is not right. Technically for your database models, a folder model will have one-to-many relationship with itself not a many-to-many relationship.
