### ISSUE TITLE
Allowed memory size Fatal error

### ISSUE THREAD

**Issue by ctf0** [laravel/framework#13860]
memory_limit = 128m
>PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 123731968 bytes) in Unknown on line 0.

pumped to 500mb
>PHP Fatal error:  Allowed memory size of 524288000 bytes exhausted (tried to allocate 517996544 bytes) in Unknown on line 0

to reproduce, just add `{{ var_dump(url()) }} ` to a view or add `var_dump(url());` to routes.php and browser will crash.

**Comment by GrahamCampbell** [comment]
You cannot call the url function from within that file.

**Comment by ctf0** [comment]
i understand that and even though it makes no sense to use it, however i just made a ticket as this error been popping up quite some time now and i thought it was related only to the multi file upload but apparently its connected to other things aswell.
