### ISSUE TITLE
Undefined Method getTargetUrl()

### ISSUE THREAD

**Issue by stevepop** [laravel/framework#13874]
My tests began breaking with the errors, `[Symfony\Component\Debug\Exception\FatalErrorException]
  Call to undefined method Illuminate\Http\Response::getTargetUrl()` after I migrated to Laravel 5.2.35. 
I began to debug the error until I figured out that the error was caused by a call in the trait `Illuminate\Foundation\Testing\Concerns\InteractsWithPages::followRedirects()`
```
while ($this->response->isRedirect()) {
            $this->makeRequest('GET', $this->response->getTargetUrl());
        }
```

When I reverted to 5.1.36, all my tests ran successfully without the errors above.

**Comment by billmn** [comment]
This method is in "RedirectResponse" class of "symfony/http-foundation": http://api.symfony.com/3.0/Symfony/Component/HttpFoundation/RedirectResponse.html#method_getTargetUrl

Check that all composer packages are updated.
I have tried an upgrade from Laravel 5.1.36 to 5.2.35 and all works fine for me.
