### ISSUE TITLE
queue:listen vs queue:work --daemon

### ISSUE THREAD

**Issue by ctf0** [laravel/framework#13880]
am currently on local machine, all is good except when using
>php artisan queue:listen

non of the queued job gets fired, but having something like 
>php artisan queue:work --daemon --sleep=3 --tries=3

works like charm, not sure if this is a bug on my end of this is the intentional behavior.

the listener have `implements ShouldQueue` and the events gets called with `event()`

**Comment by GrahamCampbell** [comment]
I can't replicate this?

**Comment by awnali** [comment]
you have to mentioned the queue name in case of listen.

**Comment by ctf0** [comment]
@awnali https://laravel.com/docs/5.2/queues#running-the-queue-listener

**Comment by reno1979** [comment]
My jobs (called by dispatch) are only fired when using 
'''
artisan queue:listen
'''

When I try the work method, none of the jobs get picked up. (handle never called) 
''' 
artisan queue:work --sleep=3 --tries=3 --queue=high,default,low --timeout=600
'''
