### ISSUE TITLE
Consistent return annotations?

### ISSUE THREAD

**Issue by acasar** [laravel/framework#13885]
Throughout Laravel codebase, we're mixing two types of return annotations when using ``return $this``.

It's either the short syntax:
```php
/**
 * @return $this
 */
```

Or the fqcn:
```php
/**
 * @return \Full\Class\Path|static
 */
```

Both are valid annotations but which one is the "Laravel recommended" way? Should we clean up all docblocks to only use one?

@GrahamCampbell

**Comment by GrahamCampbell** [comment]
Return this should be used iff it returns the actual same instance. it is not an equivalent syntax.

**Comment by GrahamCampbell** [comment]
`static` is not wrong though, even if it does return the same instance, `$this` is just more specific.

**Comment by acasar** [comment]
@GrahamCampbell Thanks for answer. By these rules there are definitely some wrong annotations in the db component. I'll make a PR when I have some time to clean this up.
