### ISSUE TITLE
str_slug convert my arabic letters into English due to ASCII method

### ISSUE THREAD

**Issue by marwan2** [laravel/framework#13887]
I suggest that you add a param to allow user to choose allow ASCII conversion or not.

```
public static function slug($title, $separator = '-', $enable_ascii=true)
{
       if($enable_ascii) {
            $title = static::ascii($title);
       }
       ...
```

**Comment by GrahamCampbell** [comment]
Feel free to add your own function to your app. We're intentionally forcing ascii in uris.

**Comment by hassanazimi** [comment]
I speak 3 languages. For Farsi use this:
```php
function make_slug($string = null, $separator = '-')
{
	if (is_null($string)) {
		return '';
	}

	$string = trim($string);
	$string = mb_strtolower($string, 'UTF-8');

	// Make alphanumeric (removes all other characters)
	// this makes the string safe especially when used as a part of a URL
	// this keeps latin characters and arabic charactrs as well
	$string = preg_replace("/[^a-z0-9_\s-ءاآؤئبپتثجچحخدذرزژسشصضطظعغفقكگلمنوی]/u", '', $string);

	// Remove multiple dashes or whitespaces
	$string = preg_replace("/[\s-]+/", ' ', $string);

	// Convert whitespaces and underscore to the given separator
	$string = preg_replace("/[\s_]/", $separator, $string);

	return $string;
}
```

**Comment by mhmalekian** [comment]
Thank u very much mr Azimi. I use your code but i  added some character for example other unicode of ک ه and farsi numbers. 

function make_slug($string, $separator = '-')
{
    $string = trim($string);
    $string = mb_strtolower($string, 'UTF-8');

    // Make alphanumeric (removes all other characters)
    // this makes the string safe especially when used as a part of a URL
    // this keeps latin characters and Persian characters as well
    $string = preg_replace("/[^a-z0-9_\s-۰۱۲۳۴۵۶۷۸۹ءاآؤئبپتثجچحخدذرزژسشصضطظعغفقکكگگلمنوهی]/u", '', $string);

    // Remove multiple dashes or whitespaces or underscores
    $string = preg_replace("/[\s-_]+/", ' ', $string);

    // Convert whitespaces and underscore to the given separator
    $string = preg_replace("/[\s_]/", $separator, $string);

    return $string;
}

**Comment by sfdsfdsfdesfdsghefasefs** [comment]
this is amazing

**Comment by waiylgeek** [comment]
Using @hassanazimi 's solution, you may also want to skip punctuation using the following quick fix:


```
//...
$arabic_punct = ['،', '؛', '؟', '⠐', '!'];

foreach ($arabic_punct as $punct) {
	$string = preg_replace("#".mb_strtolower($punct, 'UTF-8')."#", '', $string);
}
//...
```

**Comment by mokhosh** [comment]
@GrahamCampbell since the main purpose of slugs is SEO this doesn't seem like a wise choice, does it?

**Comment by egyleader** [comment]
Thanks @mhmalekian for your function it actually works great at arabic but I noticed that it strips the  " إ , يـ" characters from the string ,, here is slight update to fix this :

    //slugify arabic characters string function
    public function make_slug($string, $separator = '-')
    {
    $string = trim($string);
    $string = mb_strtolower($string, 'UTF-8');

    // Make alphanumeric (removes all other characters)
    // this makes the string safe especially when used as a part of a URL
    // this keeps latin characters and Persian characters as well
    $string = preg_replace("/[^a-z0-9_\s-۰۱۲۳۴۵۶۷۸۹يـءاآؤئبپتثجچحخدذرزژسشصضطظعغفقکكگگلمنوهیإلأ ]/u", '', $string);

    // Remove multiple dashes or whitespaces or underscores
    $string = preg_replace("/[\s-_]+/", ' ', $string);

    // Convert whitespaces and underscore to the given separator
    $string = preg_replace("/[\s_]/", $separator, $string);

    return $string;
    }

}

**Comment by mohammad6006** [comment]
> preg_match(): Compilation failed: invalid range in character class at offset 11
if you get this error and php version is 7.3 use `\-` instead of `- `

`[^a-z0-9_\s\-
`
and

`"/[\s\-_]+/"`

**Comment by mtaraabi** [comment]
Thank you all for your contribution.
and special Thanks, @mohammad6006 you made my day.

**Comment by Null78** [comment]
you can just pass Null as the `$language` parameter to the slug method in Laravel
`Str::slug('بِسْمِ اللَّهِ الرَّحْمَـٰنِ الرَّحِيمِ', '-', Null)`
and the output:
`بسم-الله-الرحمـن-الرحيم`
