### ISSUE TITLE
PHP Error when posting 'JSON' data & 'form-data' to POST route

### ISSUE THREAD

**Issue by MrMashy** [laravel/framework#13883]
When I post this JSON data to my application (via Postman)
`Content-Type:application/json`
as my header with also the body as:
`{"email": "EMAIL HERE" ,"password": "PASSWORD HERE"}`

It shows me this warning, although the code executes and the token is retrievable. Is it laravel's fault PHP's or mine? If you need my code I'll post it in comments but my PHP.ini is set to default settings and I am using WAMP.
```
Deprecated: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0

Warning: Cannot modify header information - headers already sent in Unknown on line 0
{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEwLCJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3RcL01hc2h5aW5kdXN0cmllc1wvcHVibGljX2h0bWxcL2FwaVwvdjFcL2xvZ2luIiwiaWF0IjoxNDY1MTExNjMyLCJleHAiOjE0NjUxMTUyMzIsIm5iZiI6MTQ2NTExMTYzMiwianRpIjoiYjkwMTEwMWEyOTRlNWU3NjFkZmI1OTQ0NzgzZWViYjcifQ.js7kpqZ3UX5KqcU3C72BKwdOwzoZAp9P5fpohw6TLdA"}
```

**Comment by billmn** [comment]
It's not Laravel fault, simply edit your php.ini and set 'always_populate_raw_post_data' to '-1'.
This option is commented out or set to '0' by default probably for backwards compatibility.

**Comment by jamilalrasyid** [comment]
still error even set 'always_populate_raw_post_data' to -1

**Comment by kaushik1994** [comment]
Please use **Content-Type = application/x-www-form-urlencoded** To solve this issue.

thanks,
