### ISSUE TITLE
json_encoding in model's attribute casting

### ISSUE THREAD

**Issue by iv4art** [laravel/framework#13893]
Hello. In the Model's method `asJson` for array casting using PHP function `json_encode`. Without option JSON_UNESCAPED_UNICODE cyrillic chars encoding to strings like `\uXXXX` and it makes unpossible searching with MySQL's `LIKE`. What about adding this option in method `asJson`?
![01](https://cloud.githubusercontent.com/assets/11669099/15822290/8d6162e8-2bfd-11e6-8314-7716c83fc3b1.jpg)
![02](https://cloud.githubusercontent.com/assets/11669099/15822291/8d65eaac-2bfd-11e6-800a-57f9baf4de26.jpg)

Thank you.

**Comment by GrahamCampbell** [comment]
Please review our contribution guidelines regarding proposals. For small things, please don't bother asking, just PR. ;)
