### ISSUE TITLE
return int from any type of filed in mysql 

### ISSUE THREAD

**Issue by bakhtari** [laravel/framework#13902]
if you have a big data (6271403119) and your filed type on mysql  varchar or bigint function model return int only (2147483647)
![l](https://cloud.githubusercontent.com/assets/17001331/15850825/4edd223e-2caf-11e6-893e-96d7189733f8.png)

**Comment by GrahamCampbell** [comment]
Do you have an `int` cast in your model? What if you set that to `string`?

**Comment by bakhtari** [comment]
<?php
namespace App;

use Auth;
use Illuminate\Database\Eloquent\Model;
class Gaw_user extends Model
{
    public function user()
    {
        return $this->belongsTo('App\User');
    }

    static public function gawUser($userid = null, $filed = 'id')
    {
        if (Empty($userid)) $userid = Auth::user()->id;
        $user = Gaw_user::where('user_id', $userid)->first();
       
        if (!empty($user)) return $user->$filed;
        else return false;
    }
}

**Comment by GrahamCampbell** [comment]
Can I see the user class?

**Comment by bakhtari** [comment]
![l2](https://cloud.githubusercontent.com/assets/17001331/15852992/7bfca286-2cb8-11e6-979a-d20bc5e94310.png)

**Comment by GrahamCampbell** [comment]
No, the user class please.

**Comment by bakhtari** [comment]
Laravel Framework version 5.2.35

os: win10 64bit

apache:2.4.9

php:5.5.12

**Comment by GrahamCampbell** [comment]
Can you show me your user class please?

**Comment by bakhtari** [comment]
lass User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

**Comment by GrahamCampbell** [comment]
> Authenticatable

What is that please. Please show me the whole class and all your imports.

**Comment by bakhtari** [comment]
my user class is standard  l5.2
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

**Comment by bakhtari** [comment]
GW_USER IS:
<?php
namespace App;

use Auth;
use Illuminate\Database\Eloquent\Model;
class Gaw_user extends Model
{
    public function user()
    {
        return $this->belongsTo('App\User');
    }

    static public function gawUser($userid = null, $filed = 'id')
    {
        if (Empty($userid)) $userid = Auth::user()->id;
        $user = Gaw_user::where('user_id', $userid)->first();

        if (!empty($user)) return $user->$filed;
        else return false;
    }
}

**Comment by GrahamCampbell** [comment]
You already gave me that. I need the user class.

**Comment by bakhtari** [comment]
public function maxClickStore(GawMaxclickRequest $request)
    {
        $ref=Request::server('HTTP_REFERER');

  
        dump(Gaw_user::gawUser()); >>>>>> **show 2147483647**
        $biddingStrategyService = AdwordsGoogleController::user(Gaw_user::gawUser())->GetService('BiddingStrategyService', 'v201603'); ...................

**Comment by bakhtari** [comment]
in laravel 5.1.xx correct return value :6271403119

**Comment by GrahamCampbell** [comment]
You still haven't provided me with your user class.

**Comment by bakhtari** [comment]
it is USER CLASS:
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    
    protected $fillable = [
        'name', 'email', 'password',
    ];

  
    protected $hidden = [
        'password', 'remember_token',
    ];
}

**Comment by GrahamCampbell** [comment]
There is nothing in your user class that would cause the id to be cast to an integer.

**Comment by GrahamCampbell** [comment]
PHP 5 has known issues with large integers on Windows. Try upgrading to PHP 7.
