### ISSUE TITLE
updated_at not fully qualified, creates ambiguous column errors

### ISSUE THREAD

**Issue by bryceray1121** [laravel/framework#13909]
When attempting to use delete() or update() on an eloquent model you can not use any joins because you will get an ambiguous column name error on updated_at.  This is because the Eloquent/Builder.php does not prefix updated_at with the proper table name.  I attempted to do a pull request for this, but the issue is further complicated by Arr::add (used in addUpdatedAtColumn) doing automatic dot notation exploding.  This prevents me from adding a table.columnName string similar to the operation of SoftDeletes trait.

Laravel 5.2

**Comment by srmklive** [comment]
You can disable $timestamps on specific models by doing this: ```public $timestamps=false```.

One question though, why are you using join when updating or deleting a row? Can you describe in detail  the exact scenario?

**Comment by themsaid** [comment]
There was an attempt to fix a similar issue: https://github.com/laravel/framework/pull/13519
But end up causing problems with Postgres and also sqlite: https://github.com/laravel/framework/issues/13707

So the fix was reverted: https://github.com/laravel/framework/commit/d12c4bbf8b09ff9cf916a8e54b15e43752f31350

**Comment by troygilbert** [comment]
This seems like a pretty major issue. Maybe I'm using Eloquent wrong, but with just a simple use of Eloquent like this: `$model->childRelationship()->update(['some_column' => $value]);` fails.

**Comment by samrap** [comment]
Yeah it is definitely an issue. The commit referenced by @themsaid was mine, and while I haven't had the time to revisit this issue I am going to devote the time to look for a fix regardless. Anyone who wants to work together to find a solution, you can find contact info on my profile. Really determined to get this resolved.

**Comment by samrap** [comment]
The only thing that comes to the top of my head is in the Eloquent Model's `getQualifiedUpdatedAtColumn` method, checking which driver is being used and determine the value that way.

The more long-term way would probably be defining the Eloquent Builder as an abstract class and then each driver has its own implementation of the `addUpdatedAtColumn` method. Of course, that would require Laravel to determine the proper Builder at runtime.

**Comment by themsaid** [comment]
@samrap Did you get the chance to open a PR?

**Comment by samrap** [comment]
@themsaid Unfortunately not but I'd be happy to work together with you in order to develop a solution. From what I've discovered with this bug it's a much larger issue than it sounds.

**Comment by samrap** [comment]
@themsaid I don't have experience outside of MySQL but if I get a list of the different qualified column name rules between drivers I think I can handle fixing this issue on my own.

**Comment by trandaihung** [comment]
This seems to be an edge case and there hasn't been a fix yet.
But we can always attempt to solve with the Query Builder. Join the tables and manually set deleted_at and updated_at.

**Comment by themsaid** [comment]
@trandaihung that's what I personally do, I tried to fix before but every database driver has different rules for the qualified column name which makes this change pretty major.

**Comment by makoru-hikage** [comment]
Aw, I've to use `Carbon::now()`

**Comment by iateadonut** [comment]
Can a method ->withoutTimestamps() be added for this particular case?

**Comment by JordanDalton** [comment]
I've ran into this issue today as well.

**Comment by walterdeboer** [comment]
I noticed the deleted_at column is properly qualified in the delete query, where the updated_at column isn't. Why isn't updated_at qualified the same way as the deleted_at column?

**Comment by samrap** [comment]
@walterdeboer My PR to fix the issue explains what is going on in-depth: https://github.com/laravel/framework/pull/13519

Unfortunately, as @themsaid mentioned above, the PR caused a problem when using the Postgres and Sqlite drivers.

**Comment by decadence** [comment]
Have this issue as well

**Comment by jtwiegand** [comment]
I'm able to sidestep the ambiguity of the updated_at columns in Laravel 5.3 with a toBase() call on the Eloquent builder before doing an update on an Eloquent query.

**Comment by Turaylon** [comment]
Same problem here. As a workaround had to pluck the ids for the result that i want to update with a select and then update the model with the given ids.

```
    $ids = User::filter($filter)->pluck('id'); //in filter i have  a join with an other model that has timestamps
    User::whereIn('id',$ids)->update(['field' => 'value']);
```

**Comment by pr4xx** [comment]
Same issue here

**Comment by iget-esoares** [comment]
This issue also affects the `deleted_at` column when doing a query with softdeletes

```
$query->join(/* join some table with deleted_at */)
->delete()
```

This will bring ambiguous column error on L5.4.36 (I think this affects L5.5 too)

**Comment by samrap** [comment]
We're all well aware this issue exists. Can we refrain from unconstructive comments of the type "same thing happening here" from this point forward? There are lots of people subscribed to these issue threads that don't need to be getting emails every time someone reconfirms this is a bug 😬

**Comment by f4usto** [comment]
I am using the L5.4.36 and the workaround provided from @Turaylon is not feasible as it could get on the millions of ids on the current project and also the update values come from other tables that will be deprecated

I ended up using a ReflectionClass to "disable" the timestamps for the model on the source model for the query builder:
```
$instance = new \App\Models\Model;
$reflection = new ReflectionClass(\App\Models\Model::class);
$reflection->getProperty('timestamps')->setValue($instance, null);

$instance->/* wheres(), joins() and so on */->update([/* update values */])
```
This is not a long term approach or solution, but it bypass the timestamp modification. by not updating that field at all.

A driver aware implementation (or an alternative to the array splitting) of the `addUpdatedAtColumn` would be appreciated.

**Comment by Polokij** [comment]
I've used method toBase() before update 
$someMode->relations()->someScope()->toBase()->update(['relationTable.deleted_at'=> now(), 'relationTable.updated_at' => now()]); 
And it works for me.

**Comment by slaughter550** [comment]
@samrap I'm happy to help you solve this problem if you're still looking to solve it. I would also be hesitant about the function `getUpdatedAtColumn` knowing about the driver as that seems like an implementation detail that each driver should know how to FQ a property. Something that might be of note in this case is how each driver references properties on a join. I could see putting something like the `addUpdatedAtColumn` method a few levels deeper either in the Query Builder or at the Grammar level even. I would have to dig more but I would be keen on solving this issue with you if you're interested?

**Comment by samrap** [comment]
@slaughter550 I would definitely be interested in working together on a solution. I'll shoot you an email.

**Comment by tnatanael** [comment]
Its still happening, with Lumen 5.5 any news?

**Comment by staudenmeir** [comment]
Some of the cases could be solved if users could specify a qualified `UPDATED_AT` column in their model:

```php
class User extends Model
{
    CONST UPDATED_AT = 'users.updated_at';
}
```

This doesn't work at the moment because [`addUpdatedAtColumn()`](https://github.com/laravel/framework/blob/a4fe383b9dd2c7d2da034900f30667e8fce3365a/src/Illuminate/Database/Eloquent/Builder.php#L860) calls `Arr::add()` which uses the "dot" notation (as described in #13519).

If we use `array_merge()` instead, `CONST UPDATED_AT = 'users.updated_at'` works:

```php
return array_merge(
    [$this->model->getUpdatedAtColumn() => $this->model->freshTimestampString()],
    $values
);
```

This still requires action from the user but I think it's cleaner than the `->toBase()` workaround.

**Comment by amenk** [comment]
Sound's good to me, @staudenmeir can you make such a PR ?

**Comment by laurencei** [comment]
Thanks @staudenmeir

**Comment by patieru12** [comment]
> 
> 
> I'm able to sidestep the ambiguity of the updated_at columns in Laravel 5.3 with a toBase() call on the Eloquent builder before doing an update.

This works very nice for

**Comment by robsonvn** [comment]
Keep in mind that `toBase()` only works because it does not update the `updated_at` date
