### ISSUE TITLE
Do something with dotenv finally

### ISSUE THREAD

**Issue by misog** [laravel/framework#13906]
Hi, there is problem with dotenv+windows+apache that .env is sometimes ignored and default configuration is used [https://github.com/laravel/framework/issues/8191](https://github.com/laravel/framework/issues/8191)

The worst thing is there is possible security problem in some Laravel applications, consider encryption key in .dotenv [https://github.com/vlucas/phpdotenv/issues/76](https://github.com/vlucas/phpdotenv/issues/76)

Therefore .env files should not be used for production, even official notes state that:
> phpdotenv is made for development environments, and generally should not be used in production.
https://github.com/vlucas/phpdotenv#usage-notes

However, Laravel documentation implies that .env files should be used for different enviroments (local, production server **!!!**) [https://laravel.com/docs/5.2/configuration#environment-configuration](https://laravel.com/docs/5.2/configuration#environment-configuration)

I know this can be "fixed" with php artisan config:cache which creates .php file with all config options but reliability and security must not depend on one shell command. Another issue is that the command is not mentioned in the docs.

**Comment by GrahamCampbell** [comment]
You need to config cache first. Not a bug.

**Comment by GrahamCampbell** [comment]
We don't expect it to work if you forget to do that.

**Comment by misog** [comment]
> You need to config cache first. Not a bug.

What is the real reason to run artisan command config:cache?
1. Apache/PHP on Windows is flawed?
2. Laravel allows dotenv for production even dotenv is not intended for production?
3. Both above

> We don't expect it to work if you forget to do that.

Then it should be in docs near the dotenv section. With red fat warning that if a programmer does not run "php artisan config:cache" then the app is hackable and sometimes it will response with HTTP 500 which is not handled by ExceptionHandler.

There should be another red warning that states if programmer does not notice the first warning, he/she will spend half a day debugging and thinking whether get rid of dotenv, or get rid of Apache, or get rid of Laravel.
