### ISSUE TITLE
run all jobs regardless of queue name

### ISSUE THREAD

**Issue by amin101** [laravel/framework#13916]
if i define queue for a job then i must specify the queue name in `queue:listen --queue` otherwise that job wont run , is there a way to run all jobs regardless of their queue name?

**Comment by GrahamCampbell** [comment]
No that I know of, sorry.

**Comment by GrahamCampbell** [comment]
We do support multiple queues though. You can just list them comma seperated. :)

**Comment by natsu90** [comment]
We need this thing because we're creating queue name dynamically to distribute processes among different users. Any tricks or workaround?

**Comment by daniel-farina** [comment]
same issue/question here. What if the queues are dynamically created?  @natsu90  were you able to figure this out?

**Comment by nCuXaP** [comment]
I am trying currently this package:
https://github.com/larapack/config-writer
With it I will dynamicly change the config for queue and change through my code the 'queue' for my connection. In this way I will add through my code the new queues and I believe it will work. I will get back here and tell if all works as it should.
