### ISSUE TITLE
Subtree splits are missing tags

### ISSUE THREAD

**Issue by Jalle19** [laravel/framework#13915]
For example the latest tag in `illuminate/mail` is `v5.2.32` while the latest here is `v5.2.36`. The newest version is required for the SparkPost mailer to work at all. I had to fork the repository, tag it and override the source repository in `composer.json` to get it to work at all.

Is there any way the tags could be automatically synced? The commits seem to be since all I had to do was tag the correct commit in the master branch.

**Comment by GrahamCampbell** [comment]
Thanks for the report. We've got v5.2.37 out to all the packages now.

**Comment by Jalle19** [comment]
Thanks!
