### ISSUE TITLE
5.2 ValidatingTrait causes LogicException when rules property is not set

### ISSUE THREAD

**Issue by imelectronick** [laravel/framework#13910]
LogicException: Noticed exception 'LogicException' with message 'Relationship method must return an object of type Illuminate\Database\Eloquent\Relations\Relation'

That's because of model magic in `getRules()` method asking for property `rules` hiddenly calling method `rules()` and expecting it to return Relation for property `rules`. 

Not sure what is `rules()` method made for, so I can't provide a fix :( But solution here is to rename or remove it.

**Comment by GrahamCampbell** [comment]
We don't have a validation trait in the laravel core.
