### ISSUE TITLE
use hungarian notation for laravel

### ISSUE THREAD

**Issue by sliecer** [laravel/framework#13923]
Use the hungarian notation for the Framework. Debugging of web applications would be easier for developers. (https://en.wikibooks.org/wiki/PHP_Programming/Alternative_Hungarian_Notation)

**Comment by RomainLanz** [comment]
Oh my god please, don't... (I know that Laravel will never switch)

This notation is so 80s...

**Comment by irufus** [comment]
I'm in the middle of an investigation.  Whomever references that WikiBook needs to be put in Internet jail.
