### ISSUE TITLE
Eloquent: Serialization error

### ISSUE THREAD

**Issue by AidasK** [laravel/framework#13926]
Hi, 
I have encountered a weird error. In eloquent model, appended attribute is used instead of the table name then creating a query. But this happens only in production server(maybe mysql version is different).

I am receiving an error:

```
Illuminate\Database\QueryException

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'quiz.quiz_url' doesn't exist (SQL: select * from `quiz_url` where `quiz_url`.`quiz_id` = 1 and `quiz_url`.`quiz_id` is not null and `language` = en limit 1)
```

My model is

``` php
class QuizLanguage extends Model
{
    protected $table = 'quiz_language';

    protected $guarded = [];

    protected $appends = [
        'quiz_url',
        'edit_url',
    ];

    public function quiz()
    {
        return $this->belongsTo('App\Models\Quiz');
    }

    public function getEditUrlAttribute()
    {
        return action('QuizLanguageController@edit', [$this]);
    }

    public function getQuizUrlAttribute()
    {
        return action('QuizLanguageController@url', [$this]);
    }
}
```

``` php
class Quiz extends Model
{
    protected $table = 'quiz';
    public function languages()
    {
        return $this->hasMany('App\Models\QuizLanguage');
    }
}
```

Error occurs then I call this:

``` php
$quizLanguage = \Cache::remember('quiz-language', 60, function () {
             return QuizLanguage::with('quiz')->where('id', '=',55)->whereActive(1)->first();
 });
$model = $quizLanguage->quiz->languages()->whereLanguage('en')->first();//Throws an error mentioned above
```

Server specs:
Laravel v5.2.35
PHP 7.0.6
Mysql: Google Cloud SQL 2nd gen.
memcached 1.4.25

Any help is appreciated, thanks.

**Comment by dhamdani666** [comment]
quiz_url not found your field

**Comment by AidasK** [comment]
@dhamdani666 To be clear, error `Base table or view not found: 1146 Table 'quiz.quiz_url' doesn't exist...`  means:  `quiz.quiz_url` is a table `quiz_url` of database `quiz`. Also, I have database called `quiz` and table called `quiz` in database `quiz`.

**Comment by GrahamCampbell** [comment]
Thanks for the report. Please can you provide the exact Laravel version you are using?

**Comment by brazenvoid** [comment]
We faced this issue yesterday on our staging server, we were about to launch a new website thus everything was thrown into disarray... Turned out Rackspace had updated the PHP version, a minor release which was causing the issue. We are using the latest released Laravel 5.2 version, servers are coupled with Envoyer so they consistently get updated.

**Comment by AidasK** [comment]
@brazenvoid Have you solved your issue completely? 
I am using "memcached" cache driver which handles serialization by himself. 

Some more info about memcached:
libmemcached version => 1.0.16
memcached.compression_factor => 1.3 => 1.3
memcached.compression_threshold => 2000 => 2000
memcached.compression_type => fastlz => fastlz
memcached.serializer => igbinary => igbinary

I have also updated php and memcached versions, but error persists: 
memcached 1.4.28
PHP 7.0.8

Memcached config:
memcached -u memcached -p 11212 -m 512 -c 4096 -l 127.0.0.1

**Comment by brazenvoid** [comment]
@AidasK no, we just made Rackspace rollback their PHP update and it started working again.

**Comment by AidasK** [comment]
Error was caused by igbinary serializer used by php. I have changed to basic serializer and errors are gone:
```php
\Cache::getMemcached()->setOption(Memcached::OPT_SERIALIZER, Memcached::SERIALIZER_PHP);
```

**Comment by themsaid** [comment]
@AidasK thank you for updating the issue report.
