### ISSUE TITLE
[5.3] BroadcastEvent loses $socket when broadcastWith()

### ISSUE THREAD

**Issue by pfeiferchristopher** [laravel/framework#13929]
So perhaps I could be wrong but making the fix I list below has completely fixed my issue. So with Laravel Echo and 5.3 in a Broadcast'ed event you use `public $socket` property to stop duplication of events, etc. by adding `$this->dontBroadcastToCurrentUser();` which then sets  the public property for current socket and all.

I believe that when you add a method `broadcastWith()` on an Event that get's broadcasted in this bit of code it skips listing all public properties into the Job's payload, and the payload becomes exclusively whatever `broadcastWith()` returns. 

```
    /**
     * Get the payload for the given event.
     *
     * @param  mixed  $event
     * @return array
     */
    protected function getPayloadFromEvent($event)
    {
        if (method_exists($event, 'broadcastWith')) {
            return $event->broadcastWith();
        }

        $payload = [];

        foreach ((new ReflectionClass($event))->getProperties(ReflectionProperty::IS_PUBLIC) as $property) {
            $payload[$property->getName()] = $this->formatProperty($property->getValue($event));
        }

        return $payload;
    }
```

So perhaps this was intended, but I don't think so. I implemented this fix but it seems rough. 

```
    /**
     * Get the data to broadcast.
     *
     * @return array
     */
    public function broadcastWith()
    {
        return ['socket' => $this->socket, 'comment' => $this->comment];
    }
```

Maybe if the event method exists then it should loop through the public properties, and then wrap them in with the `broadcastWith()` returned array.

**Comment by GrahamCampbell** [comment]
Thanks for the report. Could you send a PR please? :heart:
