### ISSUE TITLE
Database Queue driver assumes default connection with no option to override

### ISSUE THREAD

**Issue by leemason** [laravel/framework#13935]
Just came across an issue with a package that swaps the default connection out and having trouble with queues.

If i swap out the default connection any queued jobs try to get added to the new connections jobs table. In this instance it isnt desired behaviour.

It seems we can configure the failed table to be set to a specific db connection, but not the actual queue handler.

When created its just passed $app['db']; which of course will always happen on the default connection.

Is my assumption right? can we/should we allow database queues to be set to a specific connection (but assume default)?

**Comment by jadjoubran** [comment]
I have a similar issue where `php artisan queue:failed` fails and returns `SQLSTATE[42S02]: Base table or view not found: 1146 Table 'forge.failed_jobs' doesn't exist (SQL: select * from `failed_jobs` order by `id` desc)` although the table does exist.

Note, I am also using a package that swaps the default connection

**Comment by themsaid** [comment]
That looks to me as a feature request more than an a bug report, we're trying to keep this repository for bug reports only.

For suggestions and feature requests please use the https://github.com/laravel/internals repo.

**Comment by patrickcarlohickman** [comment]
This is not tested, and I may be misreading the code, but it looks like you should be able to specify the database connection you want to use in the queue config file.

The `connection` option is not provided in the default `config/queue.php`, and not mentioned in the documentation, but it looks like it is used by the queue `DatabaseConnector` if one is provided:

https://github.com/laravel/framework/blob/v5.3.28/src/Illuminate/Queue/Connectors/DatabaseConnector.php#L38
