### ISSUE TITLE
Soft-deletes onlyTrashed() with where() and orWhere() returns non-deleted results

### ISSUE THREAD

**Issue by reefki** [laravel/framework#13937]
I have a search form to find deleted users who has email or username that matches the search query:

```
$user->onlyTrashed()->where('username', 'like', "%$query%")
    ->orWhere('email', 'like', "%$query%")->get()
```

But the results includes non-deleted users. Is it a bug?

**Comment by amonger** [comment]
I think this ends up coming out as 

```MYSQL
select * from user where trashed == false and username like %query% or email like %query%.
```

You need to put the where in a closure.

**Comment by ahmadshobirin** [comment]
$user->withTrashed()->where('username', 'like', "%$query%")
    ->orWhere('email', 'like', "%$query%")->get();

try this
