### ISSUE TITLE
Array to string conversion error using form field name 'dates'

### ISSUE THREAD

**Issue by devdurbs** [laravel/framework#13931]
I have a textarea form field using the name 'dates' set up this way;
`{!! Form::textarea('dates', isset($notes->dates) ? $notes->dates : null,                                          ['class' => 'form-control', 'rows' => '1']) !!}`

When $notes->dates has a value it works fine. When $notes->dates is not set Laravel generates an array to string conversion error in the form builder.

If I change the code to `isset($notes->dates) ? $notes->dates : '',` it does not generate an error if $notes->dates is not set.

I'm using the latter in my code so I'm good to go but thought I should report this just in case it's not due to my own ignorance.

**Comment by GrahamCampbell** [comment]
We don't have a form class in 5.1.+.
