### ISSUE TITLE
TokenMismatchException RANDOM via ajax requests only on Chrome Windows

### ISSUE THREAD

**Issue by sebastianvirlan** [laravel/framework#13949]
How this can be explained?

1. Clean install Laravel
2. Using redis for session and cache
3. The problem occur only if I start the server on windows and only shows on Chrome.
4. Using a simple js function for ajax call:

```

        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            },
            data: {
                _token: $('meta[name="csrf-token"]').attr('content')
            }
        });

        for(var i = 0; i < 5; i++){

            getUsers();
        }

        function getUsers() {
            $.ajax({
                url: '/users',
                type: 'POST',
                success: function(data) {
                    console.log(data);
                }
            });
        }

```
5. Setting CSRF in meta ``` <meta name="csrf-token" content="{{ csrf_token() }}" /> ```
6. Returning a JSON with data:

```
    public function users() {

        $users = User::all();

        return response()->json([
            'users' => $users,
        ]);
    }
```

7. At the final of the video you can see RANDOM TokenMismatchException even the token never change but sometime error occur.

https://www.youtube.com/watch?v=QDucHoP647g

I know this problem has been discussed from years but why does not exist a solution for this?

**Comment by GrahamCampbell** [comment]
Thanks. This is a known issue. Please see the existing issues. If you make sure you avoid concurrent requests that start a session, you should be fine.

**Comment by sebastianvirlan** [comment]
I don't understand this part:

> If you make sure you avoid concurrent requests that start a session, you should be fine.

Please give me some more details.

**Comment by GrahamCampbell** [comment]
Sorry, but this is not a support forum. Feel free to read the multitude of other replies I've given to similar issue.

**Comment by sebastianvirlan** [comment]
Ok, thank you.

**Comment by sebastianvirlan** [comment]
If this helps you with something, the problem occur only when I login with Remember Me checked.
