### ISSUE TITLE
How to use laravel Auth::user() outside laravel 5.2

### ISSUE THREAD

**Issue by alinasiri1367** [laravel/framework#13947]
I am using this code for use Auth::user() outside Laravel 5.1 and works properly:

`require '../laravel/bootstrap/autoload.php';
$app = require_once '../laravel/bootstrap/app.php';
$app->make('Illuminate\Contracts\Http\Kernel')->handle(Illuminate\Http\Request::capture());`

But in Laravel 5.2 does not work. What is the solution?

**Comment by GrahamCampbell** [comment]
Feel free to ask on the forums. I'm sure someone can help you there.
