### ISSUE TITLE
[5.2] | Model Acces as array not working with boolean

### ISSUE THREAD

**Issue by hitech95** [laravel/framework#13942]
I noticed a strange behavior of the Model class.
I am attaching the problem:

Controller: 
```
 public function edit($id)
    {

        $hardware = Hardware::findOrFail($id);

        var_dump($hardware['name']);
        var_dump($hardware->name);

        var_dump($hardware['hidden']);
        var_dump($hardware->hidden);

        return;
    }
```
The output is equal for the "name" but not for "hidden":
```
/media/vagrant/lede/laravel/app/Http/Controllers/Admin/AHardwareController.php:107:string 'Alice Gate Voip 2 Plus WiFi' (length=27)

/media/vagrant/lede/laravel/app/Http/Controllers/Admin/AHardwareController.php:108:string 'Alice Gate Voip 2 Plus WiFi' (length=27)

/media/vagrant/lede/laravel/app/Http/Controllers/Admin/AHardwareController.php:110:
array (size=0)
  empty

/media/vagrant/lede/laravel/app/Http/Controllers/Admin/AHardwareController.php:111:boolean true

```

This is my model: https://github.com/hitech95/LEDE-Hub/blob/master/laravel/app/Hardware.php
Database entity: https://github.com/hitech95/LEDE-Hub/blob/master/laravel/database/migrations/2016_06_03_142324_create_hardware_table.php

The defect is problematic because I'm using the HTML/Form helper from laravel collective, it uses access as array to load the data from the model but obviously fails.

**Comment by billmn** [comment]
Yep, I have tested it with a new Laravel installation without external packages.

```php
$hardware = App\Hardware::first();

dump(
    $hardware['name'],
    $hardware->name,
    $hardware['hidden'],
    $hardware->hidden
);

die;
```

This is the result:
![schermata 2016-06-10 alle 20 53 01](https://cloud.githubusercontent.com/assets/779534/15975331/563764ea-2f4d-11e6-8c21-7c6ae4d5e01e.png)

Seems that something happen when you have a casted attribute and access to the field as an array

**Comment by hitech95** [comment]
Yes, but I do not understand if it is my mistake or if it is a laravel problem. I lost several hours trying to figure out.
As a workaround I have implemented the method `getFormValue` in my model. (Well at least the form work)

Wow, you've installed my crap just to try, thank you!

**Comment by alxy** [comment]
The problem is probably, that $hidden is an attribute, that is used by Eloquent models itself: https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/Model.php#L106

**Comment by hitech95** [comment]
I had missed that var, I'll try to update the code.

**Comment by lagbox** [comment]
laravel/internals#45 - a reminder to change the array access functionality
