### ISSUE TITLE
Eloquent - skip/offset result

### ISSUE THREAD

**Issue by Daaru00** [laravel/framework#13940]
Hi,
in Laravel (version 5.2.34) I can't perform a custom pagination with skip and take function.
I tried to do:
`$users = App\User::all()->skip($offset)->take($size)->get();`

but method skip does not exist, the method has been deprecated?
I can't found anything about this in the [Eloquent documentation](https://laravel.com/docs/5.0/eloquent).

**Comment by acasar** [comment]
The query should be:
```
$users = App\User::skip($offset)->take($size)->get();
```

**Comment by Daaru00** [comment]
It works! 
Really thanks for your help.

**Comment by GrahamCampbell** [comment]
Yes, `all()` does not start a query. It is the same as just calling `get()` straight away, and returns a collection.
