### ISSUE TITLE
DatabaseTransactions trait does not work

### ISSUE THREAD

**Issue by sunilysk** [laravel/framework#13954]
I used the Illuminate\Foundation\Testing\DatabaseTransactions trait in one of my test and expected it to rollback data after test. But it does not do that. I have checked in both **MySQL** and **PostgreSQL**

Laravel version **5.2.37**
Here is the piece of my code

**ArticleTest.php**
```
<?php

use App\Article;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Foundation\Testing\DatabaseMigrations;

/**
 * Article TestCase
 */
class ArticleTest extends TestCase
{
  use DatabaseTransactions;
  /**
   * @test
   */
public function the_most_popular_articles()
{

  factory(Article::class,2)->create();
  factory(Article::class)->create(['reads' => 10]);
  $mostPopular = factory(Article::class)->create(['reads' => 20]);

  $articles = Article::trending();
  $this->assertEquals($mostPopular->id, $articles->first()->id);
}

}
  
```

**Output after running the test twice**

```
PHPUnit 4.8.26 by Sebastian Bergmann and contributors.

.F....

Time: 4.63 seconds, Memory: 18.00MB

There was 1 failure:

1) ArticleTest::the_most_popular_articles
Failed asserting that 1 matches expected 4.

/var/www/public/phpUnit/tests/Integrations/Models/ArticleTest.php:24
/home/vagrant/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:149
/home/vagrant/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:100

FAILURES!
Tests: 6, Assertions: 10, Failures: 1.



PHPUnit 4.8.26 by Sebastian Bergmann and contributors.

.F....

Time: 4.2 seconds, Memory: 18.00MB

There was 1 failure:

1) ArticleTest::the_most_popular_articles
Failed asserting that 5 matches expected 8.

/var/www/public/phpUnit/tests/Integrations/Models/ArticleTest.php:24
/home/vagrant/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:149
/home/vagrant/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:100

FAILURES!
Tests: 6, Assertions: 10, Failures: 1.

```

**Comment by sisve** [comment]
What piece of your code and output proofs that the DatabaseTransactions trait doesn't work? Are the faked article rows present in the database after the tests? The test only shows that your Article::trending() doesn't work, probably a bad sort.

A transaction rollback, which is used after every test, does not in anyway "release" used auto-increment primary keys. You created four articles in the test, and thus "consumed" four primary key numbers.

**Comment by GrahamCampbell** [comment]
The transaction is only run **once** for the class.

**Comment by GrahamCampbell** [comment]
Did you override the setUp method. What do you mean by run twice?

**Comment by GrahamCampbell** [comment]
Your ID assertion looks incorrect actually. You would need to truncate the table each time to get what you want.

**Comment by sunilysk** [comment]
@sisve @GrahamCampbell  Thank you for the follow up, this issue can be considered closed.
