### ISSUE TITLE
emailOutputTo should only sent latest logs when using appendOutputTo

### ISSUE THREAD

**Issue by dersvenhesse** [laravel/framework#13965]
When using a scheduler and wanting to have an output file containing all logs you can use `appendOutputTo`. I'm thinking when using this method with `emailOutputTo` you'd only like to get the latest output via mail.

Say you're running a job every night. All the results will be appended to one log file, so you have a history and can easily see how long the job took every night. When receiving the mail you'll have a pretty long mail containing data from previous nights but you're basically just interested if all went well the last time.

Therefore I'm suggesting to send only the latest log results when using `emailOutputTo` in combination with `appendOutputTo`.

**Comment by GrahamCampbell** [comment]
Feel free to send a PR if you'd like something changed. If you'd just like to discuss options, please see our contribution guide for the correct place to do that.
