### ISSUE TITLE
[5.1]+ - Join builder - can't create custom SQL JOIN

### ISSUE THREAD

**Issue by pionl** [laravel/framework#13968]
Hi there,
as I mentioned in pull request, when I need to use more complex JOIN statement in 5.1/5.2 the properties one and two build empty ON SQL statement, in 5.2 the grammar fails to build without sending one parameter (Undefined offset: 0), can be empty closure in `$one`.

The builder should allow a custom join without the one parameter or at least let it build without it.

Example of the SQL query

      JOIN
    (SELECT
        object_id
    FROM
        `index_search_objects`
    WHERE
        option_id IN (66,257)
    GROUP BY object_id
    ) AS search_objects3 USING(object_id)

PHP:

     Site::join(\DB::raw("
    (SELECT
        object_id
    FROM
        `index_search_objects`
    WHERE
        option_id IN (66,257)
    GROUP BY object_id
    ) AS search_objects3 USING(object_id)"), function() {})->get();

Error: Undefined offset: 0

If I pass only $one without the $two, the ON 'one' '' is build in the query. 

In a pull request #12955 you can achieve the resulted join. Unfortunately stuck on my repo.

Also would be great to allow $one to be optional (the table must use the \DB::raw).

Thank you and have a great day,

**Comment by acasar** [comment]
@pionl you could work around it by doing something like:

```php
$query->join($rawQuery, DB::raw('1'), '=', DB:raw('1'))
```

Not really sure about the use case here... how does the join work without any join condition?

**Comment by acasar** [comment]
Can't you use ``crossJoin`` for that? https://laravel.com/docs/5.2/queries#joins

**Comment by pionl** [comment]
@acasar 1 comment:
This will create an invalid SQL statement

 ```
SELECT
object_id
FROM
`index_search_objects`
WHERE
option_id I' at line 1 (SQL: select * from `objects` inner join JOIN
(SELECT
object_id
FROM
`index_search_objects`
WHERE
option_id IN (66,257)
GROUP BY object_id
) AS search_objects3 USING(object_id) on 1 = 1
```

Second comment:
- seems to work on the newest update of the 5.2 (in time of developing didn't work), the time of processing is working. With this use case it works, unfortunately in other use cases you can't use a LEFT join.

**Comment by pionl** [comment]
Hi guys,
Unfortunately cross join is not working as mentioned above.

@GrahamCampbell can we make the changes into the code base? I've update the solution for 5.2.

Proposed solution from the PR is to append the $from parameter with the compiled SQL. This partially works. Unfortunately, in my second usage I can't make this change and I need to use `join` method with the on statement. I've update my solution to 5.2 (https://github.com/pionl/framework/tree/5.2-join-raw-table). I can update the code to 5.4 or 5.3 if needed. 

Second solution (if the change can't be make - for other people) is to use the public $joins property of a Builder. Example usage with Eloquent builder
```php
$builder->toBase()->joins[] = new JoinClause($this->mustHavePrice ? "inner" : "left", $statement);
```

Then, if you need to use the on clause you need to call the on method and then register the binding via addBinding.
```php
$join->on(
      $one, $operator, $two, 'and', $where
);
$builder->addBinding($join->bindings, 'join');
```

This solution works, but it depends on the `JoinClause` class.

Best regards and Happy new year,
Martin.
