### ISSUE TITLE
All instantiate of framework services should be with "If" 

### ISSUE THREAD

**Issue by pilot911** [laravel/framework#13969]
Problem: I cant replace "auth.password" in own service provider becouse framework code has deferred service provider for "auth.password"

So, i should create one more deferred service provider in my package just only for replacing framework's code.

It will be better to define all framework core's services with 

singletoneIf
bindIf

and etc function for easy developing packages.

Thank for answer.

**Comment by GrahamCampbell** [comment]
Packages (generally) probably shouldn't be messing with that stuff, and if they are, only one package at a time should be, so you should extend the framework service provider and instruct users to replace the framework provider with the package one.

**Comment by pilot911** [comment]
Thanks for answer
