### ISSUE TITLE
Json query builder for keys with white spaces does not work

### ISSUE THREAD

**Issue by y471n** [laravel/framework#13977]
For JSONS having keys with spaces JSON query builder does not seem to work
eg: 

`$query->orWhere('name->First Name', 'mango');`

mysql states this can work via double quotes
`$query->orWhere('name->""First Name""', 'mango');`

but even this does not seem to work.

**Comment by themsaid** [comment]
afaik JSON keys may not contain a whitespace.

**Comment by GrahamCampbell** [comment]
Hmmm. Why do you need keys with whitespace in them?

**Comment by themsaid** [comment]
@GrahamCampbell well it's valid in MySQL to have spaces in JSON keys, but I personally think it's bad.

**Comment by y471n** [comment]
@GrahamCampbell - My data dump has keys like that. And it's perfectly valid to have those keys in JSON and MySQL

**Comment by GrahamCampbell** [comment]
Sure.

**Comment by y471n** [comment]
My bad.. the above query seems to work.. It was not about whitespace.
The problem was with number's not getting matched in JSON in laravel, mis-debugged it with whitespace.

`$query->where('player->rank', '>', 2);`  

this does not seem to work. will open a separate issue for this.
