### ISSUE TITLE
[5.3] Optional route parameter and type-hinted implicit binding resolves an empty model

### ISSUE THREAD

**Issue by ElfSundae** [laravel/framework#13988]
``` php
Route::get('user/{user?}', function (User $user = null) {
    // 
});
```

`$user` will be an empty model (**not null**) if there is no matching model instance, is this normal?

Now I fix this issue by registering `user` as an explicit binding:

``` php
$router->bind('user', function ($value) {
    return \App\User::find($value);
});

Route::get('user/{user?}', function ($user = null) {
    //
});
```

**Comment by GrahamCampbell** [comment]
> $user will be an empty model (not null) if there is no matching model instance, is this normal?

It is normal, unfortunately, yeh, because it'll fallback to using dependency injection to basically app-make the `App\User`.

Is it a good behaviour? Questionable.

> Now I fix this issue by registering user as an explicit binding:

Yeh, that's probably the best way to do it for the optional params.

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell. I've seen this before, and it would be nice if we could perhaps change the way this works in L5.3.

**Comment by ElfSundae** [comment]
Thank you @GrahamCampbell

**Comment by deframe** [comment]
If it's a model you are passing then you can call `exists()` It might be neater than creating a binding and dropping the type-hint.

```php
Route::get('user/{user?}', function (User $user = null) {
    if ( ! is_null($user) && ! $user->exists) {
        abort(404);
    }
});
```

**Comment by GrahamCampbell** [comment]
> If it's a model you are passing then you can look at exists It might be neater than creating a binding and dropping the type-hint.

That's not brilliantly elegant though.

**Comment by deframe** [comment]
> That's not brilliantly elegant though.

Yeah it's far from clean, plus it's annoying having to add this condition almost every time a binding is used. I might be able to look into this tomorrow if no one objects; if it's a straightforward change then I'll submit a PR to 5.3 and let Taylor decide where to go with it (maybe an empty model is desirable in some cases?)

**Comment by deframe** [comment]
I can't spend any more time on this but I found where the issue(?) occurs.

**Illuminate\Routing\Route::runCallable()** for closures

```php
protected function runCallable(Request $request)
{
    $parameters = $this->resolveMethodDependencies(
        $this->parametersWithoutNulls(), new ReflectionFunction($this->action['uses'])
    );

    return call_user_func_array($this->action['uses'], $parameters);
}
```

**Illuminate\Routing\ControllerDispatcher::call()** for controllers

```php
protected function call($instance, $route, $method)
{
    $parameters = $this->resolveClassMethodDependencies(
        $route->parametersWithoutNulls(), $instance, $method
    );

    return $instance->callAction($method, $parameters);
}
```

Any binding that returns ```null``` will be filtered out of the parameters list by the call to ```Illuminate\Routing\Route::parametersWithoutNulls()```.

```Illuminate\Routing\Route::resolveMethodDependencies()``` and ```Illuminate\Routing\ControllerDispatcher::resolveClassMethodDependencies()``` make subsequent calls to ```Illuminate\Routing\RouteDependencyResolverTrait::transformDependency()``` which cross-references each *reflected* parameter on the closure / controller method against the *filtered* parameter list. If it doesn't exist within that, App::make(...) is run.

A potential way of fixing this might be to give all null-result bindings an temporary interim value so they don't get filtered out by ```parametersWithoutNulls()``` then reset them back again after the dependencies have been resolved.

**Comment by ElfSundae** [comment]
Sadly it has no change in 5.3 😢

**Comment by powelski** [comment]
> $user will be an empty model (not null) if there is no matching model instance, is this normal?

It shouldn't be neither empty model *nor null* in my opinion. It should throw `NotFoundHttpException`. Optional parameter doesn't mean it can be a trash.

**Comment by GrahamCampbell** [comment]
> Optional parameter doesn't mean it can be a trash.

That's not what's happening. It's dependency injecting the class you typehinted. It just happens to be also used for model binding when that's present.

**Comment by powelski** [comment]
I know that. What I mean is that this behavior is inconsistent. For non-optional parameters, it's either model instance assigned to parameter or `ModelNotFoundException`. For optional parameters, it's not throwing `ModelNotFoundException` for unexisting model, it just sets the parameter to null. This is very error-prone behavior.

**Comment by deframe** [comment]
Where would the `ModelNotFoundException` be caught if it needed to be handled in a specific way?

**Comment by powelski** [comment]
In global handler. This is how it works for implicit model binding.

**Comment by taylorotwell** [comment]
I don't really know what the behavior should be in this case. To me it seems more logical that it should be `null` rather than an empty model but I'm not sure how much work it would be to make that happen.

**Comment by powelski** [comment]
@taylorotwell My intuition tells me that if we have a route defined as `/people/{user?}`, `$user` should contain:

1. For model-focused call `function (User $user)`:
  * **Existing User** instance if the User is found.
  * **Empty User model** if User is skipped (when we hit `/people`, but let's don't hit people, people).
  * **Empty User model** if User doesn't exist.
2. For instance-focused call `function (User $user = null)`:
  * **Existing User** instance if the User is found.
  * **null** if User is skipped.
  * `ModelNotFoundException` should be thrown if User doesn't exist.

Current behavior:

1. For model-focused call `function (User $user)`:
  * **Existing User** instance if the User is found. ✔
  * **Empty User model** if User is skipped (when we hit `/people`, but let's don't hit people, people). ✔
  * **ModelNotFoundException** is thrown if User doesn't exist. ✘
2. For instance-focused call `function (User $user = null)`:
  * **Existing User** instance if the User is found. ✔
  * **Empty User model** if User is skipped. ✘
  * **Empty User model** if User doesn't exist. ✘

**Comment by MightyPork** [comment]
Just run into this issue while switching from my own ugly resolution to route-model binding.

I'm in favor of it being null, not "empty model". That's what I expected anyway, before discovering part of my app stopped working.

Checking for ->exists is far from elegant.

**Comment by rorc** [comment]
I have some problem in 5.3
Route: `Route::get('order/{order}/sms/{sms?}', 'OrderController@sms')->name('order.sms');`
Controller method:
```php
    public function sms(Order $order, Sms $sms = null)
    {
        if (is_null($sms)) {
            $sms = $order->status->sms;
        }

        return $this->dispatch(new Replace($order, $sms->template));
    }
```
With request `/order/1/sms` expect `$sms` is null, but got empty Eloquent model (without attributes) :(

**Comment by alepeino** [comment]
I submitted a PR for this: #17521

**Comment by GrahamCampbell** [comment]
Thanks. Discussion can take place on the PR now, if needed.
