### ISSUE TITLE
[laravel] Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by dnetix** [laravel/framework#13984]
I'm currently working on Laravel 5.2.31 with Zend Server, By default, out of the box, just installed with composerm ZRay detects this errors
![laraveloutoftheboxerror](https://cloud.githubusercontent.com/assets/4644865/16046530/63a07a28-3212-11e6-8c84-eb2af73db4c0.png)

**Comment by GrahamCampbell** [comment]
Looks like this but is with ZRay, trying to serialize the entire application whenever an exception is thrown.

**Comment by dnetix** [comment]
And why would Larvel throw an exception out of the box

**Comment by GrahamCampbell** [comment]
Laravel will throw an exception if you don't set it up correctly.
