### ISSUE TITLE
ValidatesRequest does a pjax check te determine the return format, FormRequest doesn't

### ISSUE THREAD

**Issue by sebastiandedeyne** [laravel/framework#13997]
In `Illuminate\Foundation\Validation\ValidatesRequest`:
```php
if (($request->ajax() && ! $request->pjax()) || $request->wantsJson()) {
    return new JsonResponse($errors, 422);
}
```

In `Illuminate\Foundation\Http\FormRequest`:
```php
if ($this->ajax() || $this->wantsJson()) {
    return new JsonResponse($errors, 422);
}
```

Pjax doesn't work with form requests as it is now. I think `ValidatesRequest` has the intended behaviour. Is there a reason for this, or can a `pjax` check be added to `FormRequest` too, to keep it consistent?

**Comment by GrahamCampbell** [comment]
Thanks for the report. Closing since we now have a PR open. :heart:
