### ISSUE TITLE
Customize paginate links()

### ISSUE THREAD

**Issue by yasinkocak** [laravel/framework#13990]
I'm using bootstrap 4, links() method of paginate generate HTML that compatible Bootstrap 3.

How to customize the generated HTML?

**Comment by kamui545** [comment]
You can wait for 5.3, it should not take long before release.

https://twitter.com/taylorotwell/status/738051768072867840

**Comment by sisve** [comment]
The rendering of a paginator is done by a presenter, an implementation of [Illuminate\Contracts\Pagination\Presenter][1]. You can change the current presenter by calling `AbstractPaginator::presenter(function($paginator) { return MyCustomPresenter($paginator); });`. You can call this method in your service provider's boot().

The default is a fallback to SimpleBootstrapThreePresenter, as seen in [Paginator::render][2], or BootstrapThreePresenter in [LengthAwarePaginator::render][3]

There are already a [SimpleBootstrapFourPresenter][4] and a [BootstrapFourPreseter][5] available in Laravel 5.2

[1]: https://github.com/laravel/framework/blob/5.2/src/Illuminate/Contracts/Pagination/Presenter.php
[2]: https://github.com/laravel/framework/blob/5.2/src/Illuminate/Pagination/Paginator.php#L111-L120
[3]: https://github.com/laravel/framework/blob/5.2/src/Illuminate/Pagination/LengthAwarePaginator.php#L128-L137
[4]: https://github.com/laravel/framework/blob/5.2/src/Illuminate/Pagination/SimpleBootstrapFourPresenter.php
[5]: https://github.com/laravel/framework/blob/5.2/src/Illuminate/Pagination/BootstrapFourPresenter.php

**Comment by yasinkocak** [comment]
@sisve how to use SimpleBootstrapFourPresenter and a BootstrapFourPreseter ?

When is the 5.3 release

**Comment by GrahamCampbell** [comment]
> it should not take long before release.

That tweet does not indicate that, and the release date may be slightly further away than you might think. Sorry, but I am not at liberty to release the date. Taylor will do it himself when he's ready.

**Comment by sisve** [comment]
@GrahamCampbell While that tweet doesn't indicate the release date; earlier communication from Otwell has indicated that Laravel is on a 6 month release schedule, which means that the 5.3 release should be in the near future. I would really like to see a public schedule with future functions and focus areas, but that is clearly out of scope of this issue.

@yasinkocak You should be able to just use it. `AbstractPaginator::presenter(function($paginator) { return new BootstrapFourPresenter($paginator); }); ` assuming correct use statements for the namespaces.

**Comment by GrahamCampbell** [comment]
> earlier communication from Otwell has indicated that Laravel is on a 6 month release schedule, which means that the 5.3 release should be in the near future. I would really like to see a public schedule with future functions and focus areas, but that is clearly out of scope of this issue.

Well, if it were on a 6 month cycle, we've missed the release date already. As I said though, it's not for me to say.

**Comment by browner12** [comment]
pagination will be using views in 5.3, not presenters anymore, which will make things much more customizable. here is a link to the [commit](https://github.com/laravel/framework/commit/c8d1b189c581824b18b2ddec6a1d2c225871858b), I can't seem to find the issue or PR again.
