### ISSUE TITLE
$request->input('metadata') converting empty object to empty array

### ISSUE THREAD

**Issue by enVolt** [laravel/framework#13993]
This is the code snippet -

    $metadata = $request->input('metadata', (new \StdClass));

if `metadata` key is not present in request body, an empty object is associated to `$metadata` variabled, but if value is `{}` of this key, it is returning an empty array `[]`, not an empty object. 

Any solution to this. Workaround I've put for now is type casting this `$metadata` to object (`(object) $metadata`), but IMO it's a hack. empty array `[]` and empty object `{}` are two entirely different things.

**Comment by GrahamCampbell** [comment]
Thanks for the report. Please can you provide the exact Laravel version you are using?

**Comment by GrahamCampbell** [comment]
Actually, the input method doesn't belong to us, it's on symfony's class. Feel free to take this up with them. Thanks again. :)
