### ISSUE TITLE
[5.2] Can we give the rate limiter an extra limitation time?

### ISSUE THREAD

**Issue by ElfSundae** [laravel/framework#13991]
The current throttle like `throttle:60,1` will limit clients to 60 attempts per minute, and disable their access for one minute if they hit the limit.

Now I want to add an extra limitation time for the rate limiter, to disable overload-accessed for more than one minute but keep 60 attempts per minute for normal clients.

e.g. `throttle:60,1,120` will limit it to 60 attempts per minute, once clients hit the limit, the rate limiter will disable their access for 120 minutes.

I am new on `RateLimiter`, maybe it can be done like this:

```php
class ThrottleRequests
{
    public function handle($request, Closure $next, $maxAttempts = 60, $retryAfterMinutes = 1, $limitation = 1)
    {
        $key = $this->resolveRequestSignature($request);

        if ($this->limiter->tooManyAttempts($key, $maxAttempts, $limitation)) {
            return $this->buildResponse($key, $maxAttempts);
        }

        // hit limit then return response...
    }
}
```

The `key:lockout` cache will be avaliable for `$limitation` minutes, and the `retryAfter` will be `cache('key:lockout') - time()` just like `RateLimiter::availableIn` does.

**Comment by ElfSundae** [comment]
I would like to use this feature to prevent app from attacking.

**Comment by GrahamCampbell** [comment]
We don't discuss feature proposals here. Please review the contribution guide.
