### ISSUE TITLE
Should the DB_HOST example point to 127.0.0.1?

### ISSUE THREAD

**Issue by timgws** [laravel/framework#13992]
I just recently updated my Laravel install and noticed that `DB_HOST` was changed from `localhost` to `127.0.0.1`.

The change was performed recently on this commit: https://github.com/laravel/laravel/commit/2b1cc83171883af71f3eb073f3e2637887b700d3

The reason why I ask this is because on UNIX platforms, the MySQL library will handle the `localhost` string differently to 127.0.0.1.

As per the [MySQL Documentation](http://dev.mysql.com/doc/refman/5.7/en/connecting.html):

> On Unix, MySQL programs treat the host name localhost specially, in a way that is likely different from what you expect compared to other network-based programs. For connections to `localhost`, MySQL programs attempt to connect to the local server by using a Unix socket file.

**Comment by jaschweder** [comment]
In Unix system the **localhost** host is pointed to 127.0.0.1, you can see the redirect in **/etc/hosts**, in a clean install you see in first line **127.0.0.1 localhost**. All connections to hostnames are convert to ip's underline, and who make this are all the DNS (Domain Name System) out there, and the first of them is on your own machine.

**Comment by GrahamCampbell** [comment]
Thanks for the issue. I think our default is probably best. It is just a default though. Neither option works perfectly for everyone I'm afraid.
