### ISSUE TITLE
is there a way to skip the throttle for some routes like csrf verify?

### ISSUE THREAD

**Issue by steve3d** [laravel/framework#13996]
throttle/rate limit is a very good feature, but when We use some file uploader, for example, jQuery-File-Uploader with chunked upload for a large file, it will fire so many request in a short time(depending on the network speed), the rate will most likely be exceeded.

So, is there a way to skip throttle for some route?

**Comment by GrahamCampbell** [comment]
Just make your own middleware, sure.
