### ISSUE TITLE
php artisan reporting error caused by database.php

### ISSUE THREAD

**Issue by YeeP79** [laravel/framework#14009]
I was creating new env variables in my database.php file and forgot to close a parentesis. This produces an error any time you try and run php artisan. If possible, the errors created should show some kind of "hint" as to the cause of the error itself. 

Cause of error in config/database.php
line:
            'username' => env('MSSQL_DB_USER', 'user',

See error below:
 [RuntimeException]
  Error Output: PHP Fatal error:  Uncaught ReflectionException: Class log does not exist in /vagrant/database_be/vendor/laravel
  /framework/src/Illuminate/Container/Container.php:734
  Stack trace:
  #0 /vagrant/database_be/vendor/laravel/framework/src/Illuminate/Container/Container.php(734): ReflectionClass->__construct('log')
  #1 /vagrant/database_be/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build('log', Array)
  #2 /vagrant/database_be/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('log', Array)
  #3 /vagrant/database_be/vendor/laravel/framework/src/Illuminate/Container/Container.php(849): Illuminate\Foundation\Application->make('log')
  #4 /vagrant/database_be/vendor/laravel/framework/src/Illuminate/Container/Container.php(804): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
  #5 /vagrant/database_be/vendor/laravel/framework/src/Illuminate/Container/Container.php(773): Illuminate\Container\Container->getDe in /vagrant/database_be/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 734

**Comment by sisve** [comment]
Clarification; a configuration file with syntax errors should be detected and an exception should be thrown indicating that an error occurred during loading of the file (including the filename). It looks like `LoadConfiguration` currently silently stop loading all files once a syntax error has been found.

The vague error currently shown is due to the base-class of `app/Exceptions/Handler.php`, `Illuminate\Foundation\Exceptions\Handler`, has a `__construct(LoggerInterface $log)`, and logging is not yet available.

**Comment by GrahamCampbell** [comment]
We have improved the error feedback in L5.3, so it gets raised to the php logging level.

**Comment by sisve** [comment]
Can we backport this to 5.1 and 5.2 to make it easier to debug these things?

**Comment by GrahamCampbell** [comment]
No, because the changes were breaking. We were able to put it into Lumen 5.1+ though, because they weren't breaking there.
