### ISSUE TITLE
Token guard retrieve by related model

### ISSUE THREAD

**Issue by leemason** [laravel/framework#14004]
Currently the token guard simply checks for a user by running $where->('api_token', $token); here: https://github.com/laravel/framework/blob/5.2/src/Illuminate/Auth/EloquentUserProvider.php#L87

considering larger apps and the chances of tokens being stored in different tables how would you suggest implementing this?

I currently have an eloquent relationship which is:

```
public function apiTokens(){
        return $this->hasMany(ApiToken::class);
    }
```

Would you suggest me creating a custom provider extending the eloquent one (only need to override one method) specific for my app.

Or look at how this is handled in the framework and maybe run through a set of callbacks first before finally going to the default method in the provider? kind of like how the new auth works for broadcasting?

Maybe like this:

```
public function retrieveByCredentials(array $credentials)
{
    if (empty($credentials)) {
        return;
    }

    // Loop through registered callbacks and if one returns a result
    // send the result back. If no callbacks or callbacks return nothing
    // proceed with default check. 
    foreach($this->credentialsCallbacks as $callback){
        if($result = $callback($credentials)){
            return $result;
        }
    }

    // First we will add each credential element to the query as a where clause.
    // Then we can execute the query and, if we found a user, return it in a
    // Eloquent User "model" that will be utilized by the Guard instances.
    $query = $this->createModel()->newQuery();
    foreach ($credentials as $key => $value) {
        if (! Str::contains($key, 'password')) {
            $query->where($key, $value);
        }
    }
    return $query->first();
}
```

Then we could register a callback on the eloquent provider and return our own result from credentials.

**Comment by GrahamCampbell** [comment]
Feel free to go straight to PRs please. We don't process proposal issues on this repo.
