### ISSUE TITLE
Eloquent scopes inconsistent return values

### ISSUE THREAD

**Issue by shopblocks** [laravel/framework#14001]
When using a scoped function such as the following:

```php
public function scopeMinPrice(Builder $query)
{
    return $query->select(\DB::raw('0 as min_price'))->value('min_price');
}
```

If the value is Falsy, you end up with an Instance of builder, instead of `0` like you'd expect. 

![image](https://cloud.githubusercontent.com/assets/14819903/16078718/507b8758-32f8-11e6-9143-d8087c92acd8.png)

If it is `1`, faked like so:

```php
public function scopeMinPrice(Builder $query)
{
    return $query->select(\DB::raw('1 as min_price'))->value('min_price');
}
```

It works (as with any value > 0).

Same happens with `null` and `false`.

```php
\DB::raw('false as min_price');
\DB::raw('null as min_price');
```

**Comment by shopblocks** [comment]
Code required to reproduce:

In the routes.php file:

```php
Route::get('/', function () {
    dump(\App\User::testing());
    exit;
});
```

In the User model
```php
public function scopeTesting($query)
{
    return $query->select([
        \DB::raw('0 as value')
    ])->value('value');
}
```

**Comment by shopblocks** [comment]
For some reason, it requires test data to exist in the database for this to happen. It will always return a `Builder` if there is no data.

After seeding the Users table, it happens as reported. Before seeding, it happened regardless of `truthy` value.

**Comment by shopblocks** [comment]
Little more investigation. It appears to happen regardless of a database call. If the response from a `scope` method is `falsy` it returns an instance of `Builder`

**Comment by shopblocks** [comment]
Thus the following replicates the error:

```php
public function scopeTesting($query)
    {
        return 0;
    }
```

**Comment by shopblocks** [comment]
Okay. I think the bug is the opposite to what im saying. The bug is the ability to return something that is *not* an instance of `Builder` since the documentation specifies:

> Scopes should always return a query builder instance

https://laravel.com/docs/5.2/eloquent#query-scopes

**Comment by lagbox** [comment]
#13982 
Scopes should always return Query Builders.

**Comment by shopblocks** [comment]
@GrahamCampbell Wouldn't this inconsistency in behaviour be a bug that needs fixing?

**Comment by GrahamCampbell** [comment]
Feel free to send a PR.

**Comment by shopblocks** [comment]
I'll give it a go this evening. Can this be reopened in the meantime?

**Comment by acasar** [comment]
@shopblocks The problem is in this line: 

https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/Builder.php#L1186

If you're making a PR, this should probably be changed to check for ``null`` explicetly. Right now, any falsy value is ignored and the ``Builder`` is returned.

**Comment by tisuchi** [comment]
In one of my projects, I am using laravel 5.4, but still, this issue exists. 

It would be better if you can resolve in next version.
