### ISSUE TITLE
queue with sqs creates endless loop

### ISSUE THREAD

**Issue by fzhan** [laravel/framework#14018]
I'm sorry this could only be described in a difficult way:
1. Event listener creates a queue job
2. Queue is processed with SQS, tested with redis first
3. when deployed on aws, php7.0.4, queue with SQS will hang and result in a gateway 504, switch back to redis works fine
4. when test locally, the exact same setting except php 7.0.7, queue works fine with both redis/sqs queue setting.

This is SOOOOO strange!

Laravel version 5.2.38

**Comment by GrahamCampbell** [comment]
Looks like a php bug. Upgrade your production server to 7.0.7.

**Comment by fzhan** [comment]
@GrahamCampbell Upgraded to 7.0.7, issue existed.
It created 70,000+ message in sqs. Is there anyway to trace sqs queue process in laravel framework?

Same environment (PHP7.0.7), difference is the one working is MacOS homebrew, and productions is ubuntu 16.04

**Comment by MathSmath** [comment]
If anybody runs across this in the future: make sure you have the PHP zip module installed. I had this exact same symptom (a continuous loop, queueing up endless copies of the same job on SQS), and for some reason installing zip fixed it. Possibly the SQS response is compressed, and the SDK needs zip to expand it? ¯\_(ツ)_/¯
