### ISSUE TITLE
The defect in Log Writer

### ISSUE THREAD

**Issue by ginnerpeace** [laravel/framework#14014]
**file:** framework/src/Illuminate/Log/Writer.php
**line 214:** $this->monolog->pushHandler($handler = new StreamHandler($path, $this->parseLevel($level)));

Pls use param $filePermission when new Monolog\Handler\StreamHandler.
For example, the params for Monolog\Handler\StreamHandler -> __construct, $filePermission default NULL.
At this time, file mod always is 644. And there is a log file created by http user, then console user 'Jam' in a diffrent group , now Jam can't write it, also when he execute 'artisan', that's important.

**Comment by GrahamCampbell** [comment]
We're open to PRs please. :)

**Comment by ginnerpeace** [comment]
@GrahamCampbell 
Emmm....I feel a little embarrassed. _(:3」∠)_
I'm not good at English, what is 'PRs'? 
And I have a suggest... Logfile' mod can defined by config file.

**Comment by ginnerpeace** [comment]
Does that mean ’Pre-release‘ ?

**Comment by GrahamCampbell** [comment]
PR = Pull request. Sorry about that.

**Comment by ginnerpeace** [comment]
Hah hah hah. It's doesn't matter. Thank you.
