### ISSUE TITLE
Laravel JSON Mysql number comparison query does not work

### ISSUE THREAD

**Issue by y471n** [laravel/framework#14011]
`$query->where('player->rank', '>', 2);`  

this does not seem to work.

Laravel creates a mysql query for this like.. 
`select * from from users where `player`->"$.rank" > '2';
`
The single quoted numerical value works in case of normal columns, but not in case of JSON columns.

**Comment by themsaid** [comment]
This is fixed in 5.3 by using the correct PDO_PARAM type, wasn't ported to 5.2 cause it might be a breaking change in some DB drivers other than MySQL, Postgres, and Sqlite.

**Comment by y471n** [comment]
This still does not work in Laravel 5.3. Any suggestions ?
