### ISSUE TITLE
No error for unwritable logs, missing .env

### ISSUE THREAD

**Issue by dandart** [laravel/framework#14012]
I'm getting a white screen for an unwritable log, and two simple "Whoops looks like something went wrong" messages with critically *no details at all* for a missing .env file.

Is it within the realms of possibility to show an understandable error to the screen when one of these occurs?

It would definitely make everything a bit more friendly.

**Comment by GrahamCampbell** [comment]
For a missing .env file, there's nothing we can do, because people might have deleted it on purpose because they are using other means to load the environment variables.
