### ISSUE TITLE
[5.2] Access Gate is not working when using API middleware

### ISSUE THREAD

**Issue by mvpasarel** [laravel/framework#14015]
I've registered some policies to define preferential access to data for some of the users. It works great when using the  `web` middleware (default) but they are not working when using `api` middleware and I always see deny message.

From what I see in `\Illuminate\Auth\AuthServiceProvider`, when the `Access Gate` is registered, `guard` is not sent to the `userResolver`:
 
    protected function registerAccessGate()
    {
        $this->app->singleton(GateContract::class, function ($app) {
            return new Gate($app, function () use ($app) {
                return call_user_func($app['auth']->userResolver());
            });
        });
    }

Is there a way to "guess" the guard and send it here to the AccessGate?

This should do the trick, but I can't find a way to guess current guard:

 
    protected function registerAccessGate()
    {
        $this->app->singleton(GateContract::class, function ($app) {
            return new Gate($app, function () use ($app) {
                $guard = $app['auth']->currentGuard();
                return call_user_func($app['auth']->userResolver(), $guard);
            });
        });
    }

These are my routes:

    Route::group(['prefix' => 'api/v1', 'middleware' => 'auth:api'], function () {
        Route::resource('users', 'UsersController');
    });

And here is how I handle the policies:

    // UsersController
    class UsersController extends Controller
    {
        public function __construct()
        {
            $this->authorizeResource(User::class);
        }
        // ...
    }

    // app/Providers/AuthServiceProvider
    class AuthServiceProvider extends ServiceProvider
    {
        protected $policies = [
            User::class => UserPolicy::class,
        ];
    }

    // app/Policies/UserPolicy
    class UserPolicy
    {
        use HandlesAuthorization;
    
        public function view()
        {
            return true;
        }
    
        public function create()
        {
            return true;
        }
    
        public function update()
        {
            return true
        }
    }

**Comment by GrahamCampbell** [comment]
Please ask on the forums.

**Comment by mvpasarel** [comment]
@GrahamCampbell Should I raise the issue on the forums? Or Laravel gate access is not intended to work with the Token Guard?

**Comment by u01jmg3** [comment]
@mvpasarel: did you get anywhere with this issue?

**Comment by mvpasarel** [comment]
Hi @u01jmg3 To make it work, I set the guard on the fly. Check https://github.com/laravel/framework/issues/13788#issuecomment-229930477
