### ISSUE TITLE
Incorrect insert query

### ISSUE THREAD

**Issue by JILeXanDR** [laravel/framework#14010]
SQL from error:

> SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`online-shop`.`categories`, CONSTRAINT `categories_parent_category_id_foreign` FOREIGN KEY (`parent_category_id`) REFERENCES `categories` (`id`)) (SQL: insert into `categories` (`title`, `parent_category_id`, `updated_at`, `created_at`) values (wef, , 2016-06-15 21:53:09, 2016-06-15 21:53:09))
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`online-shop`.`categories`, CONSTRAINT `categories_parent_category_id_foreign` FOREIGN KEY (`parent_category_id`) REFERENCES `categories` (`id`)) (SQL: insert into `categories` (`title`, `parent_category_id`, `updated_at`, `created_at`) values (wef, , 2016-06-15 21:53:09, 2016-06-15 21:53:09))

Instead of `""` or `NULL` for `parent_category_id` field I got the space `wef, , `

To save model I use code:
```
$category = new Category();
$category->fill(request()->all());
```

![11](http://storage8.static.itmages.com/i/16/0615/h_1466017259_4261403_d63b7465c7.png)

Is there correct way to solve the problem?

**Comment by themsaid** [comment]
You can't pass an empty string to a column with a foreign key constraint, you must pass a valid key or "null" if the column is nullable.

**Comment by JILeXanDR1** [comment]
@themsaid so I can't use `request()->all()`? Because `parent_category_id` is a select input and threre is no null value...

**Comment by JILeXanDR** [comment]
@themsaid so I can't use request()->all()? Because parent_category_id is a select input and threre is no null value...

**Comment by themsaid** [comment]
Yeah I believe you'll need to convert "" to null before passing to the query builder.

**Comment by JILeXanDR** [comment]
I hoped I can use Laravel magic to solve it without convert on my side, thanks)

**Comment by themsaid** [comment]
Well, laravel doesn't know if you need an empty string or null, both values are valid so it depends on your application needs :)
