### ISSUE TITLE
[5.2] Cannot use null value in JSON where clause

### ISSUE THREAD

**Issue by JeroenVanLeusden** [laravel/framework#14016]
When storing a model as JSON it's impossible to select rows based on null values. Both these queries return an empty result.

```php
$q->where('payload->time_spent', 'null');
$q->where('payload->time_spent', null);
```

The `payload` column is of type JSON. Don't have much spare time at the moment but I'll try to figure out why in the next couple of days.

_Based on:_
Laravel v5.2.38
PHP v5.6.21
MySQL v5.7.12

**Comment by reefki** [comment]
It should be:

```
$q->whereNull('payload->time_spent');
```

**Comment by JeroenVanLeusden** [comment]
`$q->where('payload->time_spent', null);` is basically the same as `$q->whereNull('payload->time_spent');` and won't this.

**Comment by themsaid** [comment]
I think it's not possible, I searched into that before but no luck hopefully you might find a solution.

It won't work even with a raw mysql query `where JSON_EXTRACT(payload, "$. time_spent") IS NULL`.

**Comment by ojovent** [comment]
Hi,
Please use:

$q->where('payload->time_spent', 'not like', 'null' );

**Comment by Pytorch-dataloader6** [comment]
@Jeroenll https://jaylonwallpaper.github.io/dietary/
