### ISSUE TITLE
php artisan key:generate generates and writes broken key.

### ISSUE THREAD

**Issue by n1ks2n** [laravel/framework#14027]
It seems that after this commit [https://github.com/laravel/framework/commit/370ae34d41362c3adb61bc5304068fb68e626586](url) command `php artisan key:generate` strated writing broken keys to .env.
The example of broken key:
`php artisan key:generate
Application key [base64:2eFGQ7lCmG4RbyonfwE31yD31GcwSrF2WsdmhRSUQcY=] set successfully.`

**Comment by fonini** [comment]
It's not broken, the key is base64 encoded.
