### ISSUE TITLE
Macros broken

### ISSUE THREAD

**Issue by javalight** [laravel/framework#14022]
All my Builder object macros broke after upgrading from 5.1 to  5.2.

```
//The scope class
class EnumIdScope implements ScopeInterface
{
    public function apply(Builder $builder, Model $model)
    {
        $builder->macro('test', function(Builder $builder) {
            //do stuff
            return $builder;
        });

        return $builder;
    }

    public function remove(Builder $builder,Model $model)
    {
    }
}

//In models:
 public static function boot()
    {
        parent::boot();
        static::addGlobalScope(new EnumIdScope);
    }
```

The macros are not appearing in the builder object anymore. Im getting method does not exist error. In my controller printing out the builder object i can see that the macros array is empty but the scopes array has the EnumIdScope instance.

**Comment by GrahamCampbell** [comment]
The way scopes work was changed in L5.2.

**Comment by javalight** [comment]
@GrahamCampbell My code is identical to the ones in the 5.2 docs. How is the builder object macro function supposed to be used? There is no information about this in the docs.

**Comment by javalight** [comment]
@GrahamCampbell so there is no way to use the builder objects macro function?

**Comment by GrahamCampbell** [comment]
From first observation, it would appear that you are abusing the macro function in order to hack something to work. I'd suggest you ask on the forums please.

**Comment by acasar** [comment]
@javalight To add query macros inside the global scope, you need to add a public method called ``extend()``. It will be called every time the query is initialized. See ``SoftDeletingScope`` for reference:

https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/SoftDeletingScope.php#L32

**Comment by acasar** [comment]
Also, if you have time, please make a PR to the docs :) This is not documented yet.
