### ISSUE TITLE
QueryBuilder paginate method is wrong!

### ISSUE THREAD

**Issue by XingFang** [laravel/framework#14026]
this method accept two core parameters,one is pageSize,another one is columns,when i pass the columns as a array to the method,the Grammar compile sql statement like 
"select count(`column1`,`column2`) from tableName ",but this sql is incorrect.my driver is MySQL.
Is my writing has problem or the code itself has problem?
my calling way
DB::table('city')->paginate(5,['CityId','CityName']);

**Comment by GrahamCampbell** [comment]
Please can you provide the exact Laravel version you are using?

**Comment by XingFang** [comment]
my laravel is 5.2

**Comment by GrahamCampbell** [comment]
Please provide the full version.

**Comment by XingFang** [comment]
l don't know.because I'm not next to the computer at now.You should check whether the latest version is a problem.

**Comment by GrahamCampbell** [comment]
Thanks. We need the exact version to allow us to debug this.

**Comment by XingFang** [comment]
I probably remember it was 5.2.7

**Comment by GrahamCampbell** [comment]
Please try with the very latest, and open a new issue if you are still having issues.
