### ISSUE TITLE
Migrations: make them forgiving at last!

### ISSUE THREAD

**Issue by rulatir** [laravel/framework#14028]
Laravel's migrations engine is built on the false assumption that programmers don't make stupid mistakes.

This assumption must go. It must be finally and permanently discredited and abandoned.

It must be possible to write a migration class with a stupid mistake in it, run artisan migrate, have it fail on the mistake, **AND SUBSEQUENTLY RECOVER FROM THIS SITUATION FULLY AUTOMATICALLY IN EVERY CASE**, bringing the database (including the migrations table) to **EXACTLY IDENTICAL STATE** it had before the failed attempt at migration, **WITHOUT** having to delete tables or rows from the migrations table manually, and **WITHOUT** having to employ a standalone backup/restore tool as a preparation step before every artisan migrate.

**Comment by GrahamCampbell** [comment]
There's a good database package for laravel you could check out. I have it running before I run my migrations.

**Comment by GrahamCampbell** [comment]
Here it is: https://github.com/backup-manager.

**Comment by rulatir** [comment]
@GrahampCampbell It seems you managed to solve this **DREADED AND CURSED** problem for yourself. Would you consider packaging your solution and making it available for others to reuse? I just started looking into backup-manager and found it rather basic. I will still need to write scripts to provide the desired simple command, push/pop interface on top of it. It has no built-in ability to automatically locate the **most recent** backup and restore it - it must always be given a path, so I will essentially have to maintain a "database" of backups in order to provide this function. I assume you have already done it, so would you consider sharing?
