### ISSUE TITLE
No meaningful (or not at all) error message when running artisan CLI with server offline

### ISSUE THREAD

**Issue by laurovalente** [laravel/framework#14034]
When trying to run Artisan CLI with server offline, no error message is shown. 
This makes people wonder what is happening and can be troublesome to people identify.

Steps to reproduce:

1. Make server offline
2. Run the command:
`php artisan` 
3. Nothing is returned, no error message, no error code, nothing

Suggestion:

Create a command to be run on the boot sequence. This needs an environment variable setup, unfortunately. I tried to solve by using URL::get('/'), but I guess Laravel is still not ready to have this value.

File:

`class CheckServer extends Command {

    /**
     * The console command name.
     *
     * @var string
     */
    protected $name = 'check';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Check server is up an running.';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct() {
        parent::__construct();
        $this->fire();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function fire() {
    	$url = (env('APP_URL'));
    	$url = parse_url($url);
    	$server = $url['host'];
    	$port = array_key_exists('port',$url) ? $url['port'] : 80;

		$check = @fsockopen($server, $port);
		if ($check) {
			@fclose($check);
		} else {
			echo PHP_EOL;
			echo PHP_EOL;
			echo 'Server is not running...';
			echo PHP_EOL;
			echo PHP_EOL;
			die;
		}
    }

}
`

**Comment by lagbox** [comment]
Make what server offline?

**Comment by minkbear** [comment]
Do you try this answer?

http://stackoverflow.com/questions/15733262/php-check-if-server-is-offline-and-not-show-a-warning-in-xampp

**Comment by laurovalente** [comment]
Hi @minkbear, this is exactly the solution I'm using.

**Comment by laurovalente** [comment]
@lagbox, I'm using XAMP, so, before running the website, sometimes I get to work on the back end (i.e. artisan commands) and I get frustrated why they do not work. Only then I discover that I hadn't started the server. :(

**Comment by sisve** [comment]
@laurovalente, but how do you "Make server offline"? Are you saying that you turn off Apache? Enable Laravel maintenance mode? Turn off the physical computer in front of you?

**Comment by laurovalente** [comment]
@sisve actually, not that I turn off... But I forgot to turn it on. :)

**Comment by themsaid** [comment]
Closing since it's not really a bug :)
Feel free to open a PR
