### ISSUE TITLE
Conditional Statements in Query Builder Stopped Working

### ISSUE THREAD

**Issue by JCanchor** [laravel/framework#14032]
I am using multiple ->when conditions in a query on rentals table that worked up through v5.2.33 then stopped working in v5.2.34  

I am using PHP 5.6.15

Function that is throwing error beginning in v.5.2.34
public function scopeRentalSearch($query, $community_id, $qData, $records_per_page)

The variables are zip, beds, min, and max price. These are selected by the user as their search parameters.

Here is the data dump for the query placed at the end of the function in v5.2.33 which shows the query works correctly in this build.

[scopeRentalSearch-dd.txt](https://github.com/laravel/framework/files/320802/scopeRentalSearch-dd.txt)

Here is the $qData and query so you do not have to download full data dump unless needed:

-----
full uri:  http://localhost:8000/rentals/mt/billings/zip-59102-beds-2

dd($qData, $offset, $community_id, $query);

array:6 [?
  "zip" => "59102"
  "beds" => "2"
  "min" => ""
  "max" => ""
  "page" => "1"
  "sef" => "Billings MT Rentals, Zip 59102, 2 Bedrooms"
]

Here is the model file with 2 queries using conditional statements. The second is only to get a complete list of all the rental_id's that result from the query. We use this to let the user browse through rentals using prev and next.

-----
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Rental extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'rentals';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = true;
	
    /**
     * These fields are fillable
     * 
     * @var array
     */
	protected $fillable = [
		'title', 'notes', 'featured', 'feature_rank', 'address', 'city', 'state', 'zip', 'neighborhood', 'beds', 'baths', 'sq_feet', 'garage', 'type', 'furniture', 'rental_option', 'price', 'period', 'lease', 'low_inc', 'smoking', 'pets', 'status', 'utilities'
	];

    /**
     * These fields are guarded
     * 
     * @var array
     */
    protected $guarded = [
    	'id', 'user_id', 'mo', 'community_id', 'city_id', 'bid', 'created_at', 'updated_at', 'last_rented', 'inv_to_date', 'cost', 'hitcount'
    ];

    /**
     * Display distinct cities with available rentals on state map
     * @param  array $query cities with rentals in state
     * @param  string $state current state
     * @return array        data set of cities
     */
    public function scopeCitiesWithRentals($query, $state)
    {
    	$query->distinct()
    		  ->select('city')
    		  ->where('state', '=', $state)
    		  ->where('status', '=', 'Available');
    }

    /**
     * Find current cities and zip code pairs available to populate quick search dropdowns
     * @param  array $query        join with city_community table
     * @param  integer $community_id for current community
     * @param  string $field        city-zip displayed as a pair
     * @return array               data set for pull downs
     */
    public function scopeQuickSearchZip($query, $community_id)
    {
        $query->join('city_community', 'rentals.city_id', '=', 'city_community.city_id')
              ->select('rentals.city', 'rentals.zip')
              ->where('city_community.community_id', '=', $community_id)
              ->where('rentals.status', '=', 'Available')
              ->groupBy('rentals.city', 'rentals.zip')
              ->orderBy('rentals.city', 'asc')
              ->orderBy('rentals.zip', 'asc');
    }

    /**
     * Find current beds available to populate quick search dropdowns
     * @param  array $query        join with city_community table
     * @param  integer $community_id for current community
     * @param  string $field       available beds
     * @return array               data set for pull downs
     */
    public function scopeQuickSearchBeds($query, $community_id)
    {
        $query->join('city_community', 'rentals.city_id', '=', 'city_community.city_id')
              ->distinct()
              ->select('rentals.beds')
              ->where('city_community.community_id', '=', $community_id)
              ->where('rentals.status', '=', 'Available')
              ->orderBy('rentals.beds', 'asc');
    }

    /**
     * Find rentals in current community with quick search parameters and offset
     * @param  array $query         join with city_community table
     * @param  integer $community_id for current community
     * @param  array $qData         query parameters selected by user
     * @return array                data set of rentals with offset
     */
    public function scopeRentalSearch($query, $community_id, $qData, $records_per_page)
    {
        if ($qData['page'] == '') { $offset = 0; } else { $offset = ($qData['page'] - 1) * $records_per_page; }
        
        $query->join('city_community', 'rentals.city_id', '=', 'city_community.city_id')
              ->select('rentals.id', 'rentals.title', 'rentals.address', 'rentals.city', 'rentals.state', 'rentals.zip', 'rentals.beds', 'rentals.baths', 'rentals.sq_feet', 'rentals.type', 'rentals.price', 'rentals.period', 'rentals.pets')
              ->where('city_community.community_id', '=', $community_id)
              ->where('rentals.status', '=', 'Available')
              ->when($qData['zip'], function ($query2) use ($qData) {
                  $query2->where('rentals.zip', '=', $qData['zip']);
              })
              ->when($qData['beds'], function ($query3) use ($qData) {
                  $query3->where('rentals.beds', '=', $qData['beds']);
              })
              ->when($qData['min'], function ($query4) use ($qData) {
                  $query4->where('rentals.price', '>=', $qData['min']);
              })
              ->when($qData['max'], function ($query5) use ($qData) {
                  $query5->where('rentals.price', '<=', $qData['max']);
              })
              ->orderBy('rentals.price', 'asc')
              ->skip($offset)->take($records_per_page);
              
              //dd($qData, $offset, $community_id, $query);
    }

    /**
     * Create array of all rentals.id in current community with quick search parameters
     * @param  array $query         join with city_community table
     * @param  integer $community_id for current community
     * @param  array $qData         query parameters selected by user
     * @return array                data set of all rental id's for query
     */
    public function scopeRentalCount($query, $community_id, $qData)
    {
        $query->join('city_community', 'rentals.city_id', '=', 'city_community.city_id')
              ->select('rentals.id')
              ->where('city_community.community_id', '=', $community_id)
              ->where('rentals.status', '=', 'Available')
              ->when($qData['zip'], function ($query2) use ($qData) {
                  $query2->where('rentals.zip', '=', $qData['zip']);
              })
              ->when($qData['beds'], function ($query3) use ($qData) {
                  $query3->where('rentals.beds', '=', $qData['beds']);
              })
              ->when($qData['min'], function ($query4) use ($qData) {
                  $query4->where('rentals.price', '>=', $qData['min']);
              })
              ->when($qData['max'], function ($query5) use ($qData) {
                  $query5->where('rentals.price', '<=', $qData['max']);
              })
              ->orderBy('rentals.price', 'asc');
    }

    /**
     * This rental belongs to a given state
     * @return Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function state()
    {
    	return $this->belongsTo(State::class);
    }

    /**
     * This rental belongs to a given city
     * @return Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function city()
    {
    	return $this->belongsTo(City::class);
    }

    /**
     * This rental has one set of geocoordinates for map location
     * @return Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function geocoordinates()
    {
        return $this->hasOne(GeoCoordinate::class);
    }

    /**
     * This rental has one rentalShow with complete property details
     * @return Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function rentalshow()
    {
        return $this->hasOne(RentalShow::class);
    }

    /**
     * This rental has many rentalImages to display with rental
     * @return Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function rentalimages()
    {
      return $this->hasMany(RentalImage::class);
    }
}

As of v5.2.34 we get the following error log on the file above:

`
 Error log:  [2016-06-14 14:47:50] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function when() on null' in G:\wamp\www\jasnia\app\Rental.php:102
`

I performed a comparison search between v5.2.33 and v5.2.34 - here is a list of the files that were changed:

At a glance

Filename	-> Folder
RedisTaggedCache.php	-> src\Illuminate\Cache
MorphTo.php	-> src\Illuminate\Database\Eloquent\Relations
Builder.php	-> src\Illuminate\Database\Eloquent
Model.php	-> src\Illuminate\Database\Eloquent
MySqlGrammar.php 	-> src\Illuminate\Database\Query\Grammars
Builder.php	-> src\Illuminate\Database\Query
AuthorizesResources.php	-> src\Illuminate\Foundation\Auth\Access
Handler.php	-> src\Illuminate\Foundation\Exceptions
Application.php	-> src\Illuminate\Foundation
TransportManager.php	-> src\Illuminate\Mail
Worker.php	-> src\Illuminate\Queue
DatabasePresenceVerifier.php	-> src\Illuminate\Validation
JsonExpression.php	-> src\Illuminate\Database\Query

I highlighted files in document below that I suspect may have caused loss in functionality.

[changed-files-5-2-34.docx](https://github.com/laravel/framework/files/320844/changed-files-5-2-34.docx)

I do not know enough yet on how to write a usable unit test on this file. I will be happy to furnish any more information needed or requested. Thank you.

**Comment by themsaid** [comment]
@JCanchor  you need to use `return` inside the callback

```
when($qData['zip'], function ($query2) use ($qData) {
    return $query2->where('rentals.zip', '=', $qData['zip']);
})
```

**Comment by JCanchor** [comment]
Thank you @themsaid ! I looked at the documentation again, and realized I am blind to miss that... I corrected all instances and updated to current version of Laravel Framework and works just like it is supposed to. I spent several days on this, helps to have someone look over my shoulder. I so appreciate you feedback!

**Comment by themsaid** [comment]
Glad I could help :)
