### ISSUE TITLE
PHP message: PHP Fatal error:  Uncaught ReflectionException: Class log does not exist

### ISSUE THREAD

**Issue by JILeXanDR** [laravel/framework#14041]
My Laravel version is 5.2

When I use the helper function **route** in file **config/services.php** I get the error

`2016/06/18 14:00:19 [error] 1114#1114: *217 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ReflectionException: Class log does not exist in /var/www/laravel_5.2/vendor/laravel/framework/src/Illuminate/Container/Container.php:734`

What is the problem can be there?

**Comment by GrahamCampbell** [comment]
You cannot use any helper functions in the config files. They get initialized before anything else.
