### ISSUE TITLE
Typo in comment

### ISSUE THREAD

**Issue by gitname** [laravel/framework#14053]
https://github.com/laravel/framework/blob/master/src/Illuminate/Database/Capsule/Manager.php#L138

...currently says:

```php
        // updating "model" instances; however, if it not necessary to operate.
```

I think the author meant to write:

```php
        // updating "model" instances; however, it is not necessary to operate.
```

**Comment by GrahamCampbell** [comment]
@gitname Thank you, yes. Ping @taylorotwell.

**Comment by GrahamCampbell** [comment]
Please see the open PR there. :)
