### ISSUE TITLE
request->has array handling

### ISSUE THREAD

**Issue by Macsch15** [laravel/framework#14056]
Hello,
I have in form two fields with key "key" (for example), and the "key" is an array.
```
... name="key[value1]" ...
```
```
... name="key[value2]" ...
```

Now, request->has can't check if request has "value2", for example:

```php
$request->has('key.value2')
```

Always returns false.

Of course, I can do something like this:
```php
isset($request->get('key')['value2'])
```
but I prefer "has" method.

In my opinion, support for array keys in "has" method in laravel 5.3 will be a nice gesture. :heart:

**Comment by themsaid** [comment]
@Macsch15 but `$request->has('key.value2')` should work! What laravel version are you using?

**Comment by Macsch15** [comment]
Laravel Framework version 5.2.32

**Comment by themsaid** [comment]
This test passes:

```
$request = Request::create('/', 'GET', ['foo' => ['bar' => 'baz']]);
$this->assertTrue($request->has('foo.bar'));
```

Can you please double check?

**Comment by Macsch15** [comment]
Ok, I discover something. It works fine when input passing some value, when we have, for example button with no "value", "has" returns always false.
```html
<button name="key[value1]" type="submit">Action</button>
```
Returns: false

```html
<button name="key[value1]" value="some value..." type="submit">Action</button>
```
Return: true

**Comment by themsaid** [comment]
Well, that's how it's supposed to work :) It returns true on a non-empty value.

**Comment by Macsch15** [comment]
Ok, got it. Thanks for help :+1:
