### ISSUE TITLE
Typo in comment

### ISSUE THREAD

**Issue by gitname** [laravel/framework#14054]
https://github.com/laravel/framework/blob/master/src/Illuminate/Database/Capsule/Manager.php#L36

...currently says:

```php
        // manager behave correctly since all the correct binding are in place.
```

I think the author meant to write:

```php
        // manager behave correctly since all the correct bindings are in place.
```

**Comment by GrahamCampbell** [comment]
@gitname Thank you, yes. Ping @taylorotwell.

**Comment by GrahamCampbell** [comment]
Please see the open PR there. :)
