### ISSUE TITLE
[5.2] VarDumper prevents session cookie from being set

### ISSUE THREAD

**Issue by qevo** [laravel/framework#14069]
### Observation
* If a session cookie has already been set, it will be read upon subsequent requests.
* If no session cookie was previously set, none is set.

#### Session Config
```php
['driver' => 'file',
'lifetime' => 240,
'expire_on_close' => false,
'encrypt' => false,
'files' => '/home/vagrant/Code/new_project/storage/framework/sessions',
'connection' => null,
'table' => 'sessions',
'lottery' => [2, 100],
'cookie' => 'laravel_session',
'path' => '/',
'domain' => null,
'secure' => false,
'http_only' => true];
```

#### Without VarDumper
```php
Route::get('test', function () {
    $session_id = session()->getId();
    return $session_id;
});
```
1. Clear cookies for domain.
2. Request route (e.g. <http://homestead.app/test>)
3. Check cookies, see `laravel_session`.

#### With VarDumper
```php
Route::get('test', function () {
    $session_id = session()->getId();
    dump($session_id);
    return $session_id;
});
```
1. Clear cookies for domain.
2. Request route (e.g. <http://homestead.app/test>)
3. Check cookies, do not see `laravel_session`.

**Comment by GrahamCampbell** [comment]
Yes, this is to be expected, it dumps strait away, so forces php to send the request, so you lose the session header.

**Comment by GrahamCampbell** [comment]
You could put the dump inside a view, and have it render it. That would avoid this problem, or just use the `ob_` functions yourself to buffer the dump.
