### ISSUE TITLE
Allow arguments to be passed to PHP binary when running scheduled tasks

### ISSUE THREAD

**Issue by leewillis77** [laravel/framework#14077]
If you're running HHVM you really don't want it trying to fully compile down your code when you're running one-off processes - there's no benefit since everything will be thrown away at the end of the request.

For scripts I call directly myself, this can be achieved by setting command line arguments when calling hhvm, e.g.
```hhvm -v Eval.Jit=0 /path/to/somescript.php```

Indeed I can pass these in when running the Laravel scheduler from cron, for example my crontab call looks like this:
```hhvm -v Eval.Jit=0 /path/to/artisan schedule:run 2>&1 > /dev/null```

However, the actual job processing tasks are spawned as new processes, and there doesn't seem any way to pass arguments to the binary used for invoking those jobs, so they are run as "standard", e.g.
```'/usr/bin/hhvm' --php 'artisan' app:runjob```

I'd like to be able to specify that "-v Eval.Jit=0" be passed to that binary, e.g.
```'/usr/bin/hhvm' --php -v Eval.Jit=0 'artisan' app:runjob```

For now, I've modified Illuminate/Console/Scheduling/Schedule.php locally and added the arguments into the existing ```if (defined('HHVM_VERSION'))``` block. I don't believe the options should be forced on everyone as I believe there may be circumstances where it should be left enabled, however a way to add arguments to the binary would be useful.

I obviously would prefer a proper solution rather than locally modifying Laravel.

**Comment by leewillis77** [comment]
As context; I have a Laravel app that's running a scheduled job once a minute, this is the before (prior to 14:40) and after (after 14:40) CPU impact of making these changes:

https://www.dropbox.com/s/9tffca9qsmskwrs/Screenshot%202016-06-20%2015.00.44.png?dl=0

**Comment by spencerdeinum** [comment]
You could add a config entry for the Queue that appends those arguments if they exist in the config file?

**Comment by leewillis77** [comment]
Hi; 

Thanks for commenting, but I'm not too sure what you're suggesting? There aren't any Queues involved in what I'm doing, and even if there were I'm not sure what config I could set that would change how PHP is invoked by the scheduler?

**Comment by spencerdeinum** [comment]
https://github.com/laravel/framework/blob/5.2/src/Illuminate/Console/Scheduling/Schedule.php#L52

Is that the line you edited?

I guess there is no config file defined for the Scheduler so if we wanted to add a config for that we would have to create one.

I was thinking either adding a config/scheduler.php and you could define the php args there, or maybe we could define them as a property in `app/Console/Kernel.php`.

I'm not sure which @taylorotwell would prefer.

**Comment by spencerdeinum** [comment]
My issue is that, assuming you are adding this argument for your scheduled tasks, would you not want it to be added to any Queue workers that are launched as well?

**Comment by leewillis77** [comment]
I actually edited https://github.com/laravel/framework/blob/5.2/src/Illuminate/Console/Scheduling/Schedule.php#L43

But the end result is the same. If I was using Queue workers, then yes the same would apply to them, and anything else that invokes PHP. Maybe the right place is in the PhpExecutableFinder?

**Comment by themsaid** [comment]
@leewillis77 any updates on your issue, you know that `hhvm` support is dropped in 5.3 right? Do you think the same problem might exist in supported php versions?

**Comment by leewillis77** [comment]
Hi; 

It's probably not as big an issue if HHVM is no longer supported. It would be *nice* to be able to pass additional arguments when invoking the binary - although the use case is probably less likely with PHP than HHVM. The only flags I could see being required might be -c to specify a specific INI file, or -z to load zend modules. 

However I think if someone has a concrete requirement for those they can raise as a separate feature request - I can't see a strong need for it if HHVM isn't officially supported.

**Comment by themsaid** [comment]
@leewillis77 thank you for following up :)
