### ISSUE TITLE
Bug when putting a max integer value on migration

### ISSUE THREAD

**Issue by jpkontreras** [laravel/framework#14070]
I was doing a migration and i got errors in my console that my integer` fono` was being added as a 
`int not null auto_increment primary key 

This is the migration

```
public function up()
    {
        Schema::create('descripcion_alumnos', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('fono', 30);
            $table->timestamps();
        });
    }
```

If you delete the 30 cap works as expected. That's it. 

Laravel version 5.2.39

**Comment by GrahamCampbell** [comment]
The 30 is treated as a truthy value for auto-increments. The 2nd param is not for the length.
