### ISSUE TITLE
Feature to identify the same jobs and run only once

### ISSUE THREAD

**Issue by dhiman252** [laravel/framework#14084]
Can this feature be available in near future that if using the queues and we insert jobs then multiples job with the same call must be executed only once the latest from the queue ?

For example data being inserted into the elastic server etc.

**Comment by tpaksu** [comment]
+1

**Comment by themsaid** [comment]
It seems like an interesting feature, please open a Pull Request if you have any idea on how we could implement this, or if you wish to continue discussions I suggest you open an issue in the internals repository. Thanks for the suggestion :)
