### ISSUE TITLE
[5.2] Pluck query by json column

### ISSUE THREAD

**Issue by MCMatters** [laravel/framework#14086]
When I make a query with plucking results by json property, I am getting a collection with nulls. For example:
`\App\Entities\User::find(1140)->logins()->pluck('payload->ip')`
Expected result: array with ips
Actually result: 
```
Illuminate\Support\Collection {#1326
     all: [
       null,
       null,
       null,
     ],
   }
```

The results are correct but on a moment of a plucking they break.
`laravel/framework/src/Illuminate/Database/Query/Builder.php`

**Comment by themsaid** [comment]
It's extremely tricky to get this to work with the current way the query builder works :)

**Comment by MCMatters** [comment]
I've found the trick for this issue.
If I am using `pluck('payload->ip AS ip')` then everything is okay.

**Comment by themsaid** [comment]
nice :) Thanks for sharing.

**Comment by Omranic** [comment]
@MCMatters I'm currently in need for similar feature, but after trying both above syntaxes it seems to be not working, can you kindly confirm how you manage to make it work for you? 🙂

**Comment by MCMatters** [comment]
@Omranic, sure. Here is my example http://take.ms/BRQlV

**Comment by Omranic** [comment]
Thanks @MCMatters I see it's working on queries now, that's helpful 👍 
Have you tried to make it work with normal collections?

**Comment by MCMatters** [comment]
@Omranic Yes. Just add casting to the attribute in the model and call `pluck` like this http://take.ms/KHT1i
I hope it will be useful

**Comment by Omranic** [comment]
Awesome, really appreciated 😊 
Thanks @MCMatters

**Comment by gabriel-rod** [comment]
> I've found the trick for this issue.
> If I am using `pluck('payload->ip AS ip')` then everything is okay.

this works for me on localhost, but throws syntax error on shared hosting

**Comment by BasvanH** [comment]
I know it's old, but correct syntax is:

`$model->pluck('json.key.key'));`

Like:
`$books->pluck('details.pages.page');`

**Comment by phpiraste** [comment]
> I've found the trick for this issue.
> If I am using `pluck('payload->ip AS ip')` then everything is okay.

it was good

**Comment by phpiraste** [comment]
> I've found the trick for this issue.
> If I am using `pluck('payload->ip AS ip')` then everything is okay.

it was good
