### ISSUE TITLE
Envoy confirm option on macro cascading down to individual tasks

### ISSUE THREAD

**Issue by hackel** [laravel/framework#14082]
I suspect this is probably related to laravel/envoy@14c4875.  I just upgraded to Envoy 1.2, and suddenly started having to approve every single task within my deploy macro.  This is not ideal.  Either this option should be excluded from cascading (confirm would have to be added to each individual task), or there should be a new macro option like `confirm_all` to achieve this behaviour.

**Comment by themsaid** [comment]
@hackel this doesn't really seems a bug, I think the PR merge was based on the preferences of the community. I'm closing this PR, but please feel free to open a PR and propose a different behaviour.
