### ISSUE TITLE
redirect()->withErrors(); not populating $errors {Context: quickstart-basic, Framework Ver. 5.3.0-Dev}

### ISSUE THREAD

**Issue by sunwukonga** [laravel/framework#14083]
Works with framework ver. 5.2.20.

The validator is failing [good], and the redirect is redirecting to "/" [good], but $errors is not getting the input from withErrors($validator) [bad].   

The `var_dump($errors);` in the view after the validation fail redirect is:
```
object(Illuminate\Support\ViewErrorBag)[172]
  protected 'bags' => 
    array (size=0)
      empty
```
Expecting (xdebug set `xdebug.max_nesting_level = 512` so I don't know why it's truncated):
```
object(Illuminate\Support\ViewErrorBag)[135]
  protected 'bags' => 
    array (size=1)
      'default' => 
        object(Illuminate\Support\MessageBag)[136]
          protected 'messages' => 
            array (size=1)
              ...
          protected 'format' => string ':message' (length=8)
```

**Comment by GrahamCampbell** [comment]
Are you sure you upgraded correctly? Our upgrading docs are still only partial at this stage.

**Comment by sunwukonga** [comment]
The 5.3.0-Dev was a fresh install. The 5.2.20 version I'm contrasting with is a git clone from the quickstart-basic repo. The upgrade guide only mentioned database issues between 5.2 and 5.3.

**Comment by sunwukonga** [comment]
There is actually an oblique mention of this in the quickstart basic. It says:
> Note:
If your copy of Laravel has a RouteServiceProvider that already includes the default routes file within the web middleware group, you do not need to manually add the group to your routes.php file.
> 
It might be helpful to be more specific for people new to the framework. I.e.
> Note:
If your copy of Laravel has an app/Providers/RouteServiceProvider.app that already defines the "web" middleware group routes for the application, you do not need to manually add the group to your routes.php file.
>
