### ISSUE TITLE
File generation with artisan 

### ISSUE THREAD

**Issue by imanghafoori1** [laravel/framework#14096]
I really enjoy the way loopback.io helps to auto-generate a lot of boilerplate code for REST APIs in node.js world.
Implementing the same feature in artisan... ?!
would be wonderful and time saving.(I think)

Visit:
https://loopback.io/
http://code.tutsplus.com/courses/generate-rest-apis-with-loopback

@JeffreyWay maybe it is better to be added to your generators package (and not the framework itself.)

**Comment by GrahamCampbell** [comment]
Thanks for the idea. Feel free to discuss on slack, or whatever. We strictly only process bugs here though. Thanks for you understanding. :)
