### ISSUE TITLE
@extends inside an if - blade

### ISSUE THREAD

**Issue by rafwell** [laravel/framework#14093]
Hello,

When there is a @extends within a @if the compiler translates extends out of the condition.

Sample:

@if(Request::wantsJson())	
	{!!json_encode(['status'=>0, 'msg'=>'lorem ipsum'])!!}	
@else
	@extends('layouts.admin')
	@section('content')
		lorem ipsum inside content...
	@endsection
@endif

In translated view at storage/app/framework/views:

<?php if(Request::wantsJson()): ?>	
	<?php echo json_encode(['status'=>0, 'msg'=>'lorem ipsum']); ?>	
<?php else: ?>
	
	<?php $__env->startSection('content'); ?>
		lorem ipsum inside content...
	<?php $__env->stopSection(); ?>
<?php endif; ?>
<?php echo $__env->make('layouts.admin', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>

This makes my return will be the json the "if" and the text "else"

Sorry for my english. Thanks!

**Comment by n7olkachev** [comment]
Why do you have such kind of logic in View layer?

**Comment by rafwell** [comment]
This is a view for when the user is not allowed to perform an action. The return can be a json (for ajax requests) or html (when a simple get).

However, this problem can occur with any condition, not only in this case.

Thank you!

**Comment by dattz** [comment]
I don't think you have such conditions inside views. This fails the MVC architecture. Why don't you have the condition in the controller itself, and if it's json :  `return response()->json(['status' => 0, 'msg' => 'lorem ipsum']);`, otherwise you `return view('...');`?

**Comment by GrahamCampbell** [comment]
Definitely. Views should have nothing to do with the http layer.

**Comment by rafwell** [comment]
I agree that the layers are mixed, but I discovered this bug accidentally. I modified the view to give a clearer perspective of the situation now without involving another layer of logic.

@if(true)
	<h1>It's true</h1>
@else
	<h1>This should not appear</h1>
	@extends('layouts.admin')
@endif

The result was "It's true" + the contents of layouts.admin: https://s31.postimg.org/ffmjvffpn/Captura_de_tela_de_2016_06_27_11_22_14.png

This is the compiled view in storage/framework/views:

<?php if(true): ?>
	<h1>It's true</h1>
<?php else: ?>
	<h1>This should not appear</h1>
	
<?php endif; ?>
<?php echo $__env->make('layouts.admin', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>

This behavior was expected?

Sry for my english.

**Comment by vsamadian** [comment]
@extends() must be on the first line of a blade template, which is a little weird, but whatever. Used ternary operator like this and it works!

@extends($var ? 'account.base' : 'base.base')
