### ISSUE TITLE
Proper way to build a form

### ISSUE THREAD

**Issue by Spharian** [laravel/framework#14098]
As the `FormBuilder` is no longer supported by Laravel, how are we supposed to build our forms (in a clean, Laravel way) if we don't want to bring an external package like [Laravel Collective](https://laravelcollective.com)? Because using this package brings a lot of headaches as it's not well documented (for working with relationships, for example).

Simple use case: a `create` and `edit` form.
```
@if (isset($model))
    {{ Form::model($model, [
        'action' => ['ModelController@update', $model],
        'method' => 'put'
    ]) }}
@else
    {{ Form::open(['action' => ['ModelController@store']]) }}
@endif
```

It seems a little ugly (compared to the [Rails way](http://guides.rubyonrails.org/form_helpers.html)), but okay.

Let's create a `<select>` for a `belongsTo` relationship:

```{{ Form::select('relationAttribute', $relationAttributes, isset($model) ? $model->relation->getOriginal('attribute') : null) }}```

(gotta use `getOriginal()` as I'm using [accessors](https://laravel.com/docs/master/eloquent-mutators#accessors-and-mutators) and the [builder's form model accessors](https://laravelcollective.com/docs/5.2/html#form-model-accessors) technique isn't working on a relationship).

I could fork the Laravel Collective package, try to make some fixes and improvements, but really, Laravel need to get back a supported and integrated form builder. Am I the only one to think that way?

**Comment by GrahamCampbell** [comment]
There is no official way to do it. Everyone has their own preferences.

**Comment by toledosteve** [comment]
Yet there's an official way to do 'billing'?  Seems there is a far more larger use case for forms than billing?

**Comment by GrahamCampbell** [comment]
That's not an official way as such. It's not included in the core framework, and you don't have to use it.

**Comment by toledosteve** [comment]
I didn't mean to sound confrontational, but I guess my overall point is that you DO have an official way of handling billing as it's officially in the laravel documentation.  There is no documentation on handling forms, yet it's a major use case in really every web application.  It seems like a glaring hole.  It'd even be better if it were just documentation stating to use raw HTML, or LaravelCollective, or etc.

With regard to everyone having their own preferences - that may be true, but other areas of the framework is quite opinionated, right?  Directory structure.  Active Record.  Blade Templates.  Why wouldn't forms be stripped from the core framework, but still maintained by the official team like laravel/cashier?

I understand the teams thought process, and I don't really have a problem using LaravelCollective, but for the beginner how would one handle model binding to form elements?  If a form fails validation, how do I retain the same values in the form elements?  I see in forums you can use the old() function, but why wouldn't that information be readily apparent in documentation?  LaravelCollective works fine for my needs, and I personally don't need to use that to answer my own, rather rhetorical, questions.  But to the user new to the framework, who is used to every other framework highlighting that information in documentation, it's a bit unclear/confusing.

Not trying to change anyone's mind here, just adding my support/agreement to @Spharian comment.
