### ISSUE TITLE
Pass all of Request class to register create method

### ISSUE THREAD

**Issue by bbashy** [laravel/framework#14095]
Just a question;

Why is this line only sending `$request->all()` and not just `$request`?
```php
Auth::guard($this->getGuard())->login($this->create($request->all()));
```
Ref: https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Auth/RegistersUsers.php#L63

This makes it hard to automatically pull in other request data, like user IP etc? Overriding the class is fine but it's nice to not have to do that just to save extra fields.

**Comment by jlem** [comment]
Yep, seems reasonable to me that the whole request object should be given to that method, not just the array of data.

**Comment by themsaid** [comment]
Did you get the chance to open a PR for this?

**Comment by bbashy** [comment]
@themsaid I did not. Wanted to see if it's something that works with everything else related.

**Comment by themsaid** [comment]
Well since it's an old issue and it doesn't really seem like a bug report I'm gonna have to close it ;) but please feel free to open a PR if you have time and are willing to have this changed.
