### ISSUE TITLE
facebook socialite 

### ISSUE THREAD

**Issue by ctf0** [laravel/framework#14091]
for some days now i've been trying to get the facebook to work properly but without any luck, basically the issue am having is that the user profile image doesn't show up, not like google which works perfectly,

the response i get is
> https://graph.facebook.com/v2.6/xxxxxx/picture?width=1920

which doesn't produce anything, tried the graph tester from FB and it gives a totaly different url like
 > https://scontent.xx.fbcdn.net/v/t1.0-1/xxxxxxxxxx_xxxxxxxxx_xxxxxxxx_n.jpg?oh=5c7c175388c66139f309cf030dfce4db&oe=57DA9761

not sure what should i do or what should i change in the FB app settings.

**Comment by GrahamCampbell** [comment]
Thanks, but laravel/framework's issues are only for bugs in the core. Feel free to ask for help on the forums though.
