### ISSUE TITLE
No failed() method in Illuminate\Bus\Queueable\Job (pushing jobs to the failed_table)

### ISSUE THREAD

**Issue by andy1547** [laravel/framework#14092]
I'm aware you can release the job and delete the job inside the Job class, however I need the ability to push the job into the failed table.

Here's some background on why I'd want to handle this myself instead of the queue worker. I'm working against an external API which has a request per min cap and a rolling 24-hour limit (rates refresh hourly). Naturally the Laravel queuing system fits here, you'd place the job onto the queue and if the rolling 24-hour limit is exceeded release/retry the job in a hour.

If the rate is exceeded I'd like to retry the job X amount of times, otherwise I'd like to push the job into the failed_table.

These are some solutions I've come up with:
A). Setup a queue worker with unlimited tries and a delay period of an hour, if a rate exception occurs let it propagate allowing the worker to handle retrying the job, if a generic exception is thrown delete the job as we don't want to keep retrying the job endlessly.
The downside to this approach is that you can't reproduce the errors when generic exceptions are thrown as failed jobs get deleted.

B). Setup a queue worker with X amount of retries and no delay/sleep time, if a rate exception occurs then catch, then delay the job an hour using the release method in the job class, if a generic exception occurs let it propagate, the worker will keep retrying until the max attempts is reached. This will happen quickly (due to the no delay/sleep), then the job will be pushed into the failed_jobs table.

This is my least favoured solution as resources are wasted when a generic exception occurs and rate exceptions shouldn't have a max retries limit, but at least it preserves the failed jobs.

C). Setup a queue worker with 1 retry, no delay/sleep time. Catch rate exceptions and dispatch a fresh new job (with an hour delay) within the same job class, then delete the current job. Generic exceptions get propagated to the queue worker and don't get retried.

The above solution solves my requirements completely, but feels like a hack?

**Comment by themsaid** [comment]
Hello there,

We're trying to keep this repo for bug reporting only, 
For suggestions and feature requests please use the https://github.com/laravel/internals repo.

Thank you for opening the issue and hope you get some feedback in the other repo :)
