### ISSUE TITLE
Eager Loading Polymorphic Nested Relations.

### ISSUE THREAD

**Issue by pvormittag** [laravel/framework#14119]
PR [#13737](https://github.com/laravel/framework/pull/13737) describes the ability to eager load polymorphic nested relations, but the nested relation will still be ignored when using the `with` method.

```php
// This will eager load the `likeable` relation, but not the `likeable.owner` relation.
Foo::with(['likeable.owner'])->get()
```

The above example does work if you place `$with = ['likeable.owner']` on the Foo model, however the relation will always be eager loaded, which is not ideal for all use cases.

**Comment by skovmand** [comment]
+1 for this feature.
