### ISSUE TITLE
[BUG] Incrementing variables in functions doesn't work

### ISSUE THREAD

**Issue by Saibamen** [laravel/framework#14116]
### Code
```
$count = 10;
$decrease_count = function() use (&$count) {
    $count--;
};
$decrease_count();
echo $count;

$added_records = 0;
Excel::filter("chunk")->selectSheetsByIndex(0)->load("storage\XYZ.xls")->chunk(250, function($reader) use (&$added_records, $part_catalogs, $parts, $cars, $car_models, $brands, &$importHelper) {
    $added_records++;
    echo "ADDED RECORDS LOCAL: " . $added_records . "<br>";
});
echo "<h2>Added " . $added_records . " records</h2>";
```

### Results of code

echo $count returns 9, but echo "Added " . $added_records (...) returns 0...
echo ADDED RECORDS LOCAL returns 1, so the $added_records++ works locally

**Comment by GrahamCampbell** [comment]
What version of Laravel please?

**Comment by Saibamen** [comment]
Laravel v5.2.39

**Comment by nilanjan3** [comment]
Have you checked '$count++' in the same function whether it is coming 11 or not?

**Comment by Saibamen** [comment]
@nilanjan3: yes, it prints 11

**Comment by themsaid** [comment]
This doesn't seem to be a problem with the framework.

**Comment by themsaid** [comment]
This doesn't seem to be a problem with the framework.
