### ISSUE TITLE
DateFormat Validator passes with format Y-m-d and value 06-11-27

### ISSUE THREAD

**Issue by fransjooste1** [laravel/framework#14128]
When using a dateformat validator, the following validation passes as year 6, when it should not be allowed to pass in the first place since a full written year value is required which shouldn't lead with a zero.

This is probably caused due to the leading zero on the value 06, since adding more zero values does not change the outcome. It seems leading zeros are removed while being parsed.

```php
$rules = [
    'date' => 'required|date_format:Y-m-d',
];
$validator = validator::make(['date' => '06-11-27'], $rules);
dd($validator->passes()); // returns true
```

**Comment by spencerdeinum** [comment]
Unfortunately Laravel is just wrapping PHP's `date_parse_from_format` and PHP is pretty okay with that being a valid date.

Not really an issue with Laravel itself.

`php -r "var_dump(date_parse_from_format('Y-m-d', '06-11-27'));"`

```
array(12) {
  ["year"]=>
  int(6)
  ["month"]=>
  int(11)
  ["day"]=>
  int(27)
  ["hour"]=>
  bool(false)
  ["minute"]=>
  bool(false)
  ["second"]=>
  bool(false)
  ["fraction"]=>
  bool(false)
  ["warning_count"]=>
  int(0)
  ["warnings"]=>
  array(0) {
  }
  ["error_count"]=>
  int(0)
  ["errors"]=>
  array(0) {
  }
  ["is_localtime"]=>
  bool(false)
}
```

Laravel fails the validation if the error or warning count is non zero.

**Comment by georgeboot** [comment]
But this then seems a PHP bug? I'd say this behaviour is not very strict (and thus useful for validation purposes in Laravel).

**Comment by spencerdeinum** [comment]
Yeah I am not really sure why PHP accepts that date, when the description states "A full numeric representation of a year, 4 digits"

I mean you could write a regex that requires that format as well but that doesn't seem like a very great idea.

Using Carbon is another option I've also done in the past but honestly its so easy to add custom validators that I don't see a reason for it being included in core.

**Comment by georgeboot** [comment]
I agree with you that it can be easy added as a custom validator. However, hassle free validation is something that should be in Laravel, and what is the point on having a dateformat validator if it is not completely strict? That takes away the whole point of it being a validator, and thus the hassle free validation for this particular scenario is also gone.

Since Carbon is already in the core and the Carbon approach has no downsides I can see, why not?

**Comment by spencerdeinum** [comment]
I think it is pretty reasonable for Laravel to just defer to PHP in this case, even if it seems a bit strange.

If anything I think a `date_range` function should be added.

**Comment by themsaid** [comment]
Closing since it doesn't really seem a bug in laravel.
