### ISSUE TITLE
Call to artisan throws error on command line inside custom package

### ISSUE THREAD

**Issue by basherr** [laravel/framework#14125]
I have custom package inside vendor/buildertenant/tenant/src. When I try run command php artisan make:provider TenantServiceProvider I get could not open input file artisan.
Call to the \Artisan::call() also throws The filename, directory name or volume label is incorrect.

**Comment by GrahamCampbell** [comment]
Looks like a bug in your code. Feel free to ask on the forums.

**Comment by basherr** [comment]
I have installed fresh laravel project. Artisan works fine on the root directory. I've asked the question on laravel.io/chat and they have advised to report it. The artisan didn't work in any of the vendor packages.

**Comment by eFrane** [comment]
artisan is always run from the project root.

**Comment by basherr** [comment]
So how will you be creating provider etc inside your package?
