### ISSUE TITLE
 Seeding database after deploying the Laravel app gives error

### ISSUE THREAD

**Issue by rolandtacadena** [laravel/framework#14131]
I successfully deployed a laravel in production in Heroku but when I run 'heroku run php artisan db:seed' I got this error:

[Symfony\Component\Debug\Exception\FatalThrowableError] Fatal error: Class 'Faker\Factory' not found

Does any one of you get the error deploying on heroku?

I use cleardb add ons.

When I run 'heroku run php artisan migrate' in production it all works fine only the heroku run php artisan db:seed' has error. It all works on development side, but in production I got the error.

It seems like in the Faker library id not loaded in the DatabaseSeeder class? Is there a problem on my composer not loading the Faker library? or permission on vendor folder?

**Comment by GrahamCampbell** [comment]
Looks like you forgot to install the faker dependency. Likely you need to run composer without the `--no-dev` flag.

**Comment by rolandtacadena** [comment]
so I will just run heroku run composer update without --no-dev? I already did that but issue still occur.

**Comment by 4sh3** [comment]
I have the same problem
