### ISSUE TITLE
[Proposal] create a view for whoops errors instead of the currently hard coded

### ISSUE THREAD

**Issue by ctf0** [laravel/framework#14137]
can you please 🙏  create a view for the whoops page like the included 503 view instead of the currently hard coded in `vendor/symfony/debug/ExceptionHandler.php` so the user can easily edit it without to much trouble ?

**Comment by spencerdeinum** [comment]
https://mattstauffer.co/blog/laravel-5.0-custom-error-pages

**Comment by ctf0** [comment]
this doesn't fix the issue because most of the errors are handled through that view, so to override it you will have to write the error exception one by one, this error basically handle anything other than the 404.

if am wrong plz correct me 👍

**Comment by spencerdeinum** [comment]
You can write a different error page for each status code.

I thought that was what you wanted.

Otherwise you can just write your own exception handler and decide whether or not to pass it to the base class or handle it yourself, see (https://laravel.com/docs/5.2/errors#the-exception-handler)

**Comment by ctf0** [comment]
what i wanted is to have a default error view that i can modify anyway it fits the app, and if i still need to make something in specific for one type of the errors then am still free to do so, but having that whoops page popping up in each app gets created with the framework is simply non-sense 😞 .

**Comment by stefanoruth** [comment]
you could overrite the decorate function in the exception handler.php in youre app folder

**Comment by stefanoruth** [comment]
How about overwriting the decorate method in the app/exceptions/handler.php?

**Comment by ctf0** [comment]
i believe it wont make a difference because of the original method
> vendor/symfony/debug/ExceptionHandler @ getContent

**Comment by crynobone** [comment]
```php
    /**
     * Convert the given exception into a Response instance.
     *
     * @param \Exception $e
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    protected function convertExceptionToResponse(Exception $e)
    {
        $debug = config('app.debug', false);

        if (!! $debug) {
            $e = FlattenException::create($e);
            $handler = new SymfonyExceptionHandler(config('app.debug'));
            $decorated = $this->decorate($handler->getContent($e), $handler->getStylesheet($e));

            return SymfonyResponse::create($decorated, $e->getStatusCode(), $e->getHeaders());
        }

        return response()->view('errors.error', ['exception' => $e], 500);
    }
```

**Comment by GrahamCampbell** [comment]
You can use something like https://github.com/GrahamCampbell/Laravel-Exceptions.

**Comment by ctf0** [comment]
@GrahamCampbell am already using it in local, but in production am using bug snag which as far as i know doesn't have the same flexibility , or does it ?

**Comment by GrahamCampbell** [comment]
It is very flexible in production too. https://styleci.io/ uses it in production.

**Comment by GrahamCampbell** [comment]
We also use Bugsnag for logging errors.

**Comment by GrahamCampbell** [comment]
In order to use Bugsnag, you don't need to use their laravel package. You can use https://github.com/AltThree/Bugsnag along with https://github.com/AltThree/Logger.

**Comment by GrahamCampbell** [comment]
I'm working on getting their next laravel package to use psr loggers rather than overriding the exception handler actually.

**Comment by GrahamCampbell** [comment]
My exception package is absolutely designed for production use. The fact it has application in development is purely a consequence of the design used. It's transformer and displayer system is very powerful.

**Comment by ctf0** [comment]
actually the only reason am using bugsnag is to get notified when something happens and trace the error from their dashboard, if ur package offers the same i would be extremely happy to go with it instead 👍  , 
actually i thought u were the maintainer of the bugsnag package because of ur last commit,

anyhow can u make a small guide on how to implement the AltThree packages, specially i don't know where i would add the bugsnag key or should i replace the default exception handler with something else or not, etc...

**Comment by GrahamCampbell** [comment]
> actually i thought u were the maintainer of the bugsnag package because of ur last commit,

Well, actually, I am for now. I'm working for Bugsnag for 12 weeks. ;)

**Comment by GrahamCampbell** [comment]
Getting the alt-three logging packages set up is pretty easy. Here is my config from StyleCI itself:

![image](https://cloud.githubusercontent.com/assets/2829600/16361855/8721b6c4-3b95-11e6-9038-1a79dd869a67.png)

![image](https://cloud.githubusercontent.com/assets/2829600/16361857/8b2a4b3c-3b95-11e6-8d65-6af7bb786960.png)

Make sure you regiser the alt-three service providers too. Note that you don't need the "logify" line. That's our private logging system. You'll just need "logger" and "bugsnag".

**Comment by ctf0** [comment]
awesome 💯  and for the exception handler, should i use ur package or go with the default ?

**Comment by GrahamCampbell** [comment]
Yes. :)

**Comment by ctf0** [comment]
sweet, many thanx gc :metal:

**Comment by GrahamCampbell** [comment]
No problem. :)
