### ISSUE TITLE
Laravel queues do not restart properly after a zero downtime deployment

### ISSUE THREAD

**Issue by overint** [laravel/framework#14138]
I use a instant zero downtime deployment system which works by creating a releases folder, with subfolders for each deployment (name with unix timestamp of the deployment time).
The live version folder is then symlinked to `/var/www/current`. Queues operate correctly and supervisor monitors the processes correctly and restarts them if they fail. The following steps occur during a deployment

Updated file are copied to a subfolder in the releases folder
Composer update is called
The new version is symlinked to current, and set as live
`php artisan queue:restart` is called to restart the queues

The problem is that the queues still reference the previous deployment, and any code or environment changes in the new deployment are not available to the queue, because it is restarted in the previous directory.

 **Supervisor configuration:**

```
[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/current/artisan queue:work database --sleep=3 --tries=3 --daemon
autostart=true
autorestart=true
user=www-data
numprocs=8
redirect_stderr=true
stdout_logfile=/var/www/current/worker.log
```

**Comment by crynobone** [comment]
Restarting the queue would end the process and supervisor would then attempt to restart it automatically.

```
autostart=true
autorestart=true
```

The only reason you could get it restarted on the previous release it that you run the restart before symlinking to the new build.
