### ISSUE TITLE
protected $hidden: expected or bug?

### ISSUE THREAD

**Issue by emtudo** [laravel/framework#14136]
When I put a field in hidden, example:

`` `
protected $ hidden = ['number'];
`` `
shurt_number the field is expected also not appear or is it a bug?

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch, but it is not a bug. That will hide the `number` column only, and not anything just has that as a substring in the name.

**Comment by emtudo** [comment]
Thank you for your quick reply.
I have the column "number" and  "product_number" and I my code has:

protected $hidden = ['number']

However, the "product_number" is also getting hidden

**Comment by GrahamCampbell** [comment]
I can't replicate this behaviour, and neither can our tests. Feel free to ask around on the forums.

**Comment by emtudo** [comment]
thanks! I thing I know, thanks!
