### ISSUE TITLE
$request->only($keys) doesn't return real subset

### ISSUE THREAD

**Issue by guoyunhe** [laravel/framework#14140]
If the request only contains name, email, description and I try to get name, email. address, it will return me a null address. The array_only() helper function also has same behavior.

In the API document, it says that only() function gets subset of inputs. But if it fill non-existing keys, it is not subset anymore...

**Comment by GrahamCampbell** [comment]
Yes, that is true. If you treat a subset as only considering the non-empty array values it is correct though. Maybe we need to find better terminology to use, since it's in no way a set given we have keys and the potential for multiple occurrences of the same value.

**Comment by guoyunhe** [comment]
@GrahamCampbell maybe it is better to provide two functions:

1. only() - fill non-existing key to null.
2. filter() - do not fill non-existing key to null.

```php
$request->all(); // ['name'=>'foo bar', 'email' => 'foo@bar']

$request->only(['name', 'address']); // ['name'=>'foo bar', 'address' => null]

$request->filter(['name', 'address']); // ['name'=>'foo bar']
```

Just like we have exists() and has(). People can choose which function they need.

**Comment by themsaid** [comment]
@guoyunhe  A new method was added `Request::intersect()`, it works like your suggested `filter()` method.

**Comment by guoyunhe** [comment]
Thanks!
