### ISSUE TITLE
withInput() and withErrors() not included with session

### ISSUE THREAD

**Issue by thepenguin1** [laravel/framework#14149]
I have to admit, I am truly stumped by this one...

I have a form which submits data via a POST request to a controller like so...

    public function store()
    {
        $result = Validator::make(request() -> all(), $this -> rules);

        if ($result -> fails()) 
        { 
            return back() -> withInput() -> withErrors($result); 
        }
    }

However, when I'm redirected back, accessing input data via the 'old' helper method yields nothing, as does reading data from $errors. I believe the session data is being lost (possibly due to a secondary redirect?).

I've checked my routes file in artisan and the web middleware is only being run once. 

I also tried this in place of the redirect (to test the session):

`return view("account.register") -> with("errors", $result);`

and it worked. Any ideas? I'm using Laravel 5.2.39

**Comment by GrahamCampbell** [comment]
Your code there will put an errors variable in your view. You need to first build a response.

**Comment by GrahamCampbell** [comment]
It will not put anything in the session.

**Comment by GrahamCampbell** [comment]
Feel free to ask for help on the forums.
