### ISSUE TITLE
[Request] Docker-friendly logging

### ISSUE THREAD

**Issue by bkuhl** [laravel/framework#14147]
Docker expects all logs to be sent to `stdout` and `stderr` and Laravel doesn't seem to have the ability to separate logs in such a way, but requires all logs go to either rather than the ability to split them up.  It'd be great if we were able to send `error` logs to `stderr` and the rest of the logs to `stdout`.

**Comment by GrahamCampbell** [comment]
Thanks, but we don't process requests here. Please see the contributing docs.
