### ISSUE TITLE
[Request] Support HasManyThrough for many-to-many relationships

### ISSUE THREAD

**Issue by bkuhl** [laravel/framework#14148]
Currently `hasManyThrough` is only supported for one to many relationships.  It'd be great if many-to-many relationships were supported as well.  There's a [forum thread](http://laravel.io/forum/03-04-2014-hasmanythrough-with-many-to-many?page=1#reply-25585) that has some decent approaches that may serve as a good starting point.

**Comment by GrahamCampbell** [comment]
Thanks, but we don't process requests here. Please see the contributing docs.

**Comment by GrahamCampbell** [comment]
I think this has already been rejected though actually.
