### ISSUE TITLE
Collections need to be reindexed while using the toArray() function

### ISSUE THREAD

**Issue by funyug** [laravel/framework#14154]
As described in my following reddit post:

https://www.reddit.com/r/laravel/comments/4q1wj8/return_statement_converting_array_to_object/

When we call the unique() function on a collection and then convert it to an array using the toArray() function, they need to be reindexed otherwise they will become object while we try to return them.

**Comment by marcvdm** [comment]
You should use `collect($categories['categories'])->unique('catId')->values()->toArray()` if you only want the values.

This because the keys could be something other than integers.

**Comment by vlakoff** [comment]
According to your reddit post, I'm not sure the issue is related to `values()` at all.

Looks like some variables are not replaced by the result of `toArray()`. Could you please double-check your code or provide an expanded example?

**Comment by themsaid** [comment]
I assume by return you mean presenting them as a response, in which case they'll be converted into JSON.

```php
json_encode([0=>1,1=>2,2=>3]);
// Outputs: "[1,2,3]"

json_encode([0=>1,1=>2,3=>3]);
// Outputs: "{"0":1,"1":2,"3":3}"
```

So it seems if the keys aren't zero-indexed with a correct sequence the JSON output will be an object rather than an array, so yes using `values()` would solve your issue.
