### ISSUE TITLE
No way overload `find` model method ?

### ISSUE THREAD

**Issue by totomakers** [laravel/framework#14157]
I want create for my User model a static method `findByHash` for retrive an user by unique hash
I have add the following method in my model

```
    public static function findByHash($hash)
    {
        return static::where('hash', $hash)->first();
    }
```

But didn't work as except :
 `User::findByHash($hash)` : Work
`User::findByHash($hash)->withCount('followers');` : Fail (should work no ?)
 `User::find($id)` : Work
`User::find($id)->withCount('followers');` : Work

If i remove first() like following

```
    public static function findByHash($hash)
    {
        return static::where('hash', $hash);
    }
```
It didn't work as except :
 `User::findByHash($hash)` : Didn't work need to add ->first()
`User::findByHash($hash)->withCount('followers');` : Didn't work need to add ->first()
 `User::find($id)` : Work
`User::find($id)->withCount('followers');` : Work

I try to use the builder method for make this but `query` is protected.

**Comment by ahmedash95** [comment]
i think this might be useful and fit your needs

```php
<?php

function findByHash($hash, $callback == null)
{
    $model = static::where('hash', $hash);
    if(is_callable($callback)){
    	$model = $callback($model);
    }
    return $model->first();
}
```

then you can use it like 

```php
User::findByHash($hash,function($row){
	return $row->withCount('followers');
});
```

**Comment by totomakers** [comment]
Yes it's a possible solution, but why `User::find($id)->withCount('followers');` work properly ?

I would like find a way to make `User::findByHash($id)->withCount('followers');` and `User::findByHash($id);` work together.

```
    /**
     * Find a model by its primary key.
     *
     * @param  mixed  $id
     * @param  array  $columns
     * @return \Illuminate\Database\Eloquent\Model|\Illuminate\Database\Eloquent\Collection|static[]|static|null
     */
    public function find($id, $columns = ['*'])
    {
        if (is_array($id)) {
            return $this->findMany($id, $columns);
        }
        $this->query->where($this->model->getQualifiedKeyName(), '=', $id);
        return $this->first($columns);
    }
```

**Comment by ahmedash95** [comment]
i will try to find a way at  the end of today

**Comment by GrahamCampbell** [comment]
Feel free to discuss on the forums.
