### ISSUE TITLE
Missing session keys on concurrent ajax requests

### ISSUE THREAD

**Issue by gbgkogkas** [laravel/framework#14162]
Hello, I have a question about sessions.

I want to make 3 requests.
All requests on session start do not have session key "test".
The request 2 when reach the proper controller gets the key "test" with value "something".
The execution and termination order of the requests is 1 to 3.
When the last request terminates the session key is lost.
I am using cookies as manager drive.

Is there a way to rectify this problem?

**Comment by GrahamCampbell** [comment]
Thanks, but we don't process questions here. Feel free to look at the related issues though.
