### ISSUE TITLE
Unsafe default configurations for worker commands' --timeout and queue connections' expire

### ISSUE THREAD

**Issue by halaei** [laravel/framework#14160]
### ListenCommand and WorkCommand --timeout option

    --timeout[=TIMEOUT]  Seconds a job may run before timing out [default: 60]

### config/queue.php 
```php
    'connections' => [
        ...
        'database' => [
            ...
            'expire' => 60,
        ],
        'beanstalkd' => [
            ...
            'ttr' => 60,
        ],
        'redis' => [
            ...
            'expire' => 60,
        ],
```

`expire` should always be slightly bigger than `--timeout` because when they are nearly the same, chances are that a job get finished right at the last second, but some worker re-pushes it back to the queue and makes it available to be processed again.

The situation is worse when expire is set to a value smaller than timeout, so some docs and warnings when running the queue:work/listen command with bad configurations is good to have as well.

**Comment by taylorotwell** [comment]
Sounds right. Can you make a PR to fix if you have time?

**Comment by GrahamCampbell** [comment]
We should probably set the defaults to be 90 in the queue config?

**Comment by halaei** [comment]
Sure, I try something. 90s is good I think.
On Jun 28, 2016 5:39 PM, "Taylor Otwell" <notifications@github.com> wrote:

Sounds right. Can you make a PR to fix if you have time?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/laravel/framework/issues/14160#issuecomment-229043501>,
or mute the thread
<https://github.com/notifications/unsubscribe/AGwr9Pc7IisqhxBK0EjgwWOFcn8tIczOks5qQRz4gaJpZM4JAD2m>
.

**Comment by rscafi** [comment]
I guess that this can be closed now 👍
