### ISSUE TITLE
Remember Token bug.

### ISSUE THREAD

**Issue by WongLeslie** [laravel/framework#14171]
I turn off this feature, but the feature is still in progress. My browser closes, users remain on the landing.

![image](https://cloud.githubusercontent.com/assets/15151307/16460755/8fa1f656-3e5b-11e6-8a1b-0649529f777a.png)

**Comment by fei-shen-null** [comment]
Do you mean the session is not cleared when browser is closed?
If so, have you tried to modity config\session.php?
Try`'expire_on_close' => true`
This should work (but not for chrome), for chrome you need to untick `Continue running background apps when Google Chrome is closed` under settings-advanced-system

**Comment by WongLeslie** [comment]
Thank u. I've solved, I hope that this can be specified in the document, I spend a lot of time to find.

**Comment by themsaid** [comment]
@WongLeslie we're open to docs Pull Requests in case you want to add something. Closing since it's resolved.

**Comment by WongLeslie** [comment]
@themsaid Thank u. I can try.
