### ISSUE TITLE
Testing: dontSee method globally replaces "is" with "is not" in message text.

### ISSUE THREAD

**Issue by Nikker** [laravel/framework#14174]
[This text replacement](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Testing/Constraints/ReversePageConstraint.php#L45) will replace not only the text in the error message, but also the text in the quoted search.  For example:

```php
$this->dontSee('is required');
```

Yields the corresponding error message:

> Failed asserting that the page does not contain the HTML [is not required]. Please check the content above.

It appears that this would also apply to the other replacement rules for "contains" and "has."  This is somewhat confusing, as it indicates that a test is checking for a different match than is intended (although the dontSee method functions correctly).

**Comment by GrahamCampbell** [comment]
Feel free to send a PR. Thanks!
