### ISSUE TITLE
Testing: form file uploads don't work property with array-format inputs.

### ISSUE THREAD

**Issue by Nikker** [laravel/framework#14175]
https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Testing/Concerns/InteractsWithPages.php#L668

The `convertUploadsForTesting` method does not create nested arrays when form field names call for it.  For example, attaching a file to a field with the name `test[1][file]` should result in the following structure:

```php
[
    "test" => [
        "1" => [
            "file" => UploadedFile
        ]
    ]
]
```

But instead results in:

```php
[
    "test[1][file]" => UploadedFile
]
```

I was able to implement a fix in my child TestCase class, but it would be nice to see this fixed in the core code.

**Comment by GrahamCampbell** [comment]
> UploadedFile

Is this a laravel uploaded file instance?

**Comment by Nikker** [comment]
Yes.

**Comment by themsaid** [comment]
@Nikker can you please open a PR with the fix?

**Comment by Nikker** [comment]
Yeah, I'll make a fork and do that.
