### ISSUE TITLE
Nasty recipient mixup on Mail::queue() and Queue::failing()

### ISSUE THREAD

**Issue by mspivak** [laravel/framework#14172]
Hi!
Laravel 4.2 here, eCommerce site.
After an order is placed, I queue several summary emails like this:
```
Mail::queue(
	'emails.orders.summary', compact('order'), function ($message) use ($order, $subject, $customer) {
		$message
			->to($customer->email, $customer->email)
			->subject('SupplyOcean order #' . $order->id);
	}
);
```
Then, I wanted to get an email notification if any queue should fail:
```
Queue::failing(function ($connection, $job, $data) {
	Mail::send('emails.error.queue_failed', compact('connection', 'job', 'data'), function ($message) {
		$message
			->to(Config::get('mail.admin.address'), Config::get('mail.admin.name'))
			->subject('Queued Job Failed');
	});
});
```
But somehow, an email got sent to `$customer->email` with a **nasty** array structure in it. I'm thinking that since the email sending failed, the customer email was never deleted from the object addresses array and BOOM, the customer got the debugging email.

Or am I missing something here?

Thanks for your patience.
Mauro

**Comment by GrahamCampbell** [comment]
Feel free to ask on the forums, and I'm sure someone can help you there.
