### ISSUE TITLE
Class 'Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory' not found

### ISSUE THREAD

**Issue by stefanoruth** [laravel/framework#14180]
Laravel version 5.2.39

Just tried to use Mail::raw(); setup with a mailgun configuraion and the mail works fine and i revice it but i still gets the error any idears to whats missing?

**Comment by base-zero** [comment]
I had this same problem and had to pull in the following package in my compose.json.

```
"symfony/psr-http-message-bridge": "0.2",
```

**Comment by GrahamCampbell** [comment]
Please read the suggested dependencies printed on the screen on composer install.

**Comment by barryvdh** [comment]
Why would the message-bridge be needed for raw mail? It doesn't suggest that at all, also the docs don't mention that?

**Comment by GrahamCampbell** [comment]
@barryvdh I doubt it is. I think the error was unrelated.

**Comment by base-zero** [comment]
@GrahamCampbell It's due to the use of Guzzle.

**Comment by GrahamCampbell** [comment]
That's not true. I use guzzle to send emails without this dependency. It sounds like the wrong request class is getting resolved by mistake here.

**Comment by ametad** [comment]
I also  had this error: Class 'Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory' not found

Traced back to:
https://github.com/laravel/framework/blob/5.3/src/Illuminate/Routing/Router.php#L1015
...where the HttpFoundationFactory class is used.

At line 17 in this Router class the HttpFoundationFactory class is imported:
"use Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory;"

But I had to require "symfony/psr-http-message-bridge" first to make it work... is this really a 'suggested' dependency and not a required one?

**Comment by ametad** [comment]
> laravel/framework suggests installing symfony/psr-http-message-bridge (Required to use psr7 bridging features (0.2.*).)

It is suggested indeed after composer install/update. But why is this not a requirement?

**Comment by barryvdh** [comment]
It is: https://laravel.com/docs/5.3/requests#psr7-requests
> The PSR-7 standard specifies interfaces for HTTP messages, including requests and responses. If you would like to obtain an instance of a PSR-7 request instead of a Laravel request, you will first need to install a few libraries. Laravel uses the Symfony HTTP Message Bridge component to convert typical Laravel requests and responses into PSR-7 compatible implementations:

> composer require symfony/psr-http-message-bridge
> composer require zendframework/zend-diactoros

**Comment by ametad** [comment]
Thank's for the clarification!

**Comment by marcellopato** [comment]
> It is: https://laravel.com/docs/5.3/requests#psr7-requests
> 
> > The PSR-7 standard specifies interfaces for HTTP messages, including requests and responses. If you would like to obtain an instance of a PSR-7 request instead of a Laravel request, you will first need to install a few libraries. Laravel uses the Symfony HTTP Message Bridge component to convert typical Laravel requests and responses into PSR-7 compatible implementations:
> > composer require symfony/psr-http-message-bridge
> > composer require zendframework/zend-diactoros

Thanks, @barryvdh! You saved my day. Now I wonder why it not comes installed with Laravel -> Guzzle by default?

**Comment by marcellopato** [comment]
Found the __DIR__ method. It gets the path, but still wrong because i´m inside Lavarels app:

`$response = $client->request('POST', 'http://gedocflex.com.br:8003/api/file', [
            'headers' => [
                'Content-Type' => 'multipart/form-data',
            ],
            'multipart' => [
                [
                    'name' => 'idTematica',
                    'contents' => '202'
                ],
                [
                    'name' => 'f',
                    'contents' => fopen(__DIR__ . $request->file, 'r')
                ],
                [
                    'name' => 'field1',
`

**Comment by amidesfahani** [comment]
problem still exists. i've tried to install required packages and fresh install of laravel 8. still says:
` Class "Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory" not found `
