### ISSUE TITLE
reverse polymorphic-relations eg:$like->post

### ISSUE THREAD

**Issue by fzhan** [laravel/framework#14183]
I'm referring to this feature:

https://laravel.com/docs/5.2/eloquent-relationships#polymorphic-relations

$like->likeable()  will return a relationship without knowing which object it is exactly.

Is there a way to define:
$like->post;
$like->comment;

Because sometimes polymorph is used to bind item->lotsOfObject, would be great if item->obj1, $item->obj2, $item->obj3 etc could co-exists.

Thanks,

**Comment by sede2** [comment]
public function getPostAttribute(){
    return $this->likeable()->where('likeable_type', Post::class);
}

This can help, I think

**Comment by dwightwatson** [comment]
Could do something like this, just be careful to only call it when you know what you're after.

```
public function post()
{
    $this->belongsTo(Post::class, 'likeable_id');
}
```

**Comment by fzhan** [comment]
@sede2 Tried that but it doesn't return a relationship, you see when relationship is helpful other places, such as $like->has('post'), would be perfect.

@dwightwatson What I have tried also, like you said, because which way we use it. Still not a perfect solution

**Comment by themsaid** [comment]
Closing since it doesn't to seem a bug with the framework, however please feel free to discuss the issue further in the internals repository.

**Comment by kamalkhan** [comment]
```php

protected function morphToModel($related)
{
    return $this->belongsTo($related, 'likeable_id', 'id')
        ->join($this->getTable(), $this->getTable().'.likeable_id', ($model = new $related)->getTable().'.'.$model->getKeyName())
        ->where($this->getTable().'.likeable_type', $related);
}

public function post()
{
    return $this->morphToModel(Post::class);
}

public function comment()
{
    return $this->morphToModel(Comment::class);
}
```
