### ISSUE TITLE
Language file array format for translation tools

### ISSUE THREAD

**Issue by guoyunhe** [laravel/framework#14195]
In `resources/lang/en/validation.php`, some messages have sub-array:

```php
return [
    ...
    'between'              => [
        'numeric' => 'The :attribute must be between :min and :max.',
        'file'    => 'The :attribute must be between :min and :max kilobytes.',
        'string'  => 'The :attribute must be between :min and :max characters.',
        'array'   => 'The :attribute must have between :min and :max items.',
    ],
    ...
];
```

This brings problems when we import them to translator tools. For example, we are using [Transifex](https://transifex.com/). It only can recognize plain array like:

```php
return [
    ...
    'between.numeric' => 'The :attribute must be between :min and :max.',
    'between.file'    => 'The :attribute must be between :min and :max kilobytes.',
    'between.string'  => 'The :attribute must be between :min and :max characters.',
    'between.array'   => 'The :attribute must have between :min and :max items.',
    ...
];
```

I want to know if Laravel can support "dot" notation in language files instead of multi-dimensional arrays. Thanks!

**Comment by guoyunhe** [comment]
I have done a basic test and found the dot notation works!

Maybe the document could tell developers they can use dot notation if their translation system requires single dimension array.

**Comment by GrahamCampbell** [comment]
Thanks, but we don't process proposals here.
