### ISSUE TITLE
how to change the storage_path 

### ISSUE THREAD

**Issue by fatihwk** [laravel/framework#14193]
I try to change the storage path  in this way :
add STORAGE_PATH to   .env
register STORAGE_PATH  in  Providers\AppServiceProvider.php 
    $this->app->useStoragePath(env("STORAGE_PATH",storage_path())); 

it works when you use storage_path()  in Controllers, Views . 

but it doesn't work  in config/filesystems.php , i think the register is later than loading config process.

   'task' => [
            'driver' => 'local',
            'root' => env("STORAGE_PATH")."/task", // storage_path('task')    // here storage_path() will get  system default path
        ],

is there other correct way to change the storage path?  I'm using laravel 5.2

**Comment by shadoWalker89** [comment]
Try to change it after new Illuminate\Foundation\Application(realpath(__DIR__.'/../')) in bootstrap/app.php

I know this is not clean, but i hope this solve it for now.
