### ISSUE TITLE
[BUG] Testing API 404

### ISSUE THREAD

**Issue by n7olkachev** [laravel/framework#14206]
Laravel 5.2.39
Consider example
```
public function test1()
{
    $this
            ->json('GET', '/test')
            ->seeJson(['result' => 'success']);
}

public function test2()
{
    $this
            ->json('GET', '/test')
            ->seeJson(['result' => 'success']);
}
```
test1 will pass but test2 will not with 404 error

**Comment by GrahamCampbell** [comment]
Are your tests definitely separate like this. Can I see the whole file pleae?

**Comment by n7olkachev** [comment]
File:
<details>
<?php

use App\SmsCode;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class ApiTest extends TestCase
{
    use DatabaseTransactions;

    public function testStats()
    {
        $this->json('GET', '/api/v1/cities')
            ->seeJsonStructure(['*' => [
                'id',
                'country',
                'latitude',
                'longitude',
            ]]);
    }

    public function testStats2()
    {
        $this->json('GET', '/api/v1/cities')
            ->seeJsonStructure(['*' => [
                'id',
                'country',
                'latitude',
                'longitude',
            ]]);
    }
}
</details>

**Comment by GrahamCampbell** [comment]
Can I see the `TestCase` class please?

**Comment by n7olkachev** [comment]
```php
<?php

class TestCase extends Illuminate\Foundation\Testing\TestCase
{
    /**
     * The base URL to use while testing the application.
     *
     * @var string
     */
    protected $baseUrl = 'http://localhost';

    /**
     * Creates the application.
     *
     * @return \Illuminate\Foundation\Application
     */
    public function createApplication()
    {
        $app = require __DIR__.'/../bootstrap/app.php';

        $app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

        return $app;
    }
}
```

**Comment by GrahamCampbell** [comment]
And are you sure your routes file is required using require, and not require_once?

**Comment by n7olkachev** [comment]
Gotcha! Thx a log!
