### ISSUE TITLE
Eloquent\Model __get() and toArray() not consistent

### ISSUE THREAD

**Issue by fei-shen-null** [laravel/framework#14202]
This is not a bug, and won't cause any problem most of the time. However when it happens, it is sneaky.

The problem is:
I have 3 tables
```
users(id,log_id)
logs(id,user_id,type)
log_type(type,description)
```
And relations
```
User::logs()    hasMany(Log)
Log::type()    belongsTo(LogType)
//reverse relations are not include here
```
To retrive a user's logs with nested eager loading 

    $logs=User::with('logs.type')->find(1)->logs
First time, I returned $logs to an Ajax call, the logs are casted to json and it was perfetcly fine to retrive the log description by `log.type.description` in Javascript (in a foreach loop)

Secone time, I tried to pass $logs to a view, however the call to `$log->type->description` gave an error `Trying to get property of non-object`, and `$log->type` returns int instead of Log model.

If you try to debug with `$log->toJson() or dd($log)`, you will see something like
```json
{"id":1,"user_id":2,"type":{"type":1,"description":"some log type"}}
```
funny right? the _description_ is there, but you can not get it.
After `var_dump($log)` then I see what's causing the problem, the log's protected field _type_ and relation _type_ has same name. When refering _type_ by $log->type, the `getAttribute($key)` method will try to return field or motator before relation. On the other hand, `toArray()` method cause the relation to override field and mutator.

For reference
```
    public function __get($key)
    {
        return $this->getAttribute($key);
    }

    public function getAttribute($key)
    {
        if (array_key_exists($key, $this->attributes) || $this->hasGetMutator($key)) {
            return $this->getAttributeValue($key);
        }

        return $this->getRelationValue($key);
    }

    public function toArray()
    {
        $attributes = $this->attributesToArray();

        return array_merge($attributes, $this->relationsToArray());
    }
```
This problem really should  not be happening, but making the results consistent seems right and easy.

**Comment by fei-shen-null** [comment]
@themsaid yes I would like to name the field to `type_id`, but it's not my db. I end up renaming the relation name

**Comment by themsaid** [comment]
@fei-shen-null that will do.

**Comment by themsaid** [comment]
Closing assuming this is resolved :)
