### ISSUE TITLE
where in leftJoin clause problem

### ISSUE THREAD

**Issue by julianovmartins** [laravel/framework#14219]
```php
...
->leftJoin('clinvar_tab', function ($leftJoin) {
    $leftJoin->on('clinvar_snpsift_grch38.rs', '=', 'clinvar_tab.rs_dbsnp')
    ->where('clinvar_tab.assembly', 'like', 'GRCh38')
    ->whereNotNull('clinvar_tab.rs_dbsnp');
...
})
```
this generate:
```sql
... ON `clinvar_snpsift_grch38`.`rs` = `clinvar_tab`.`rs_dbsnp` AND `clinvar_tab`.`assembly` LIKE ? AND `clinvar_tab`.`rs_dbsnp` IS NOT NULL ...
```
the third parameter from the method 'on' ($second) does not seem to be working properly.

**Comment by julianovmartins** [comment]
I'm sorry, I forgot to mention the version,

Laravel Framework version 5.2.38

**Comment by acasar** [comment]
@julianovmartins Can you describe the problem a bit more? The SQL seems perfectly fine.

**Comment by swalker2** [comment]
Shouldn't you use 
```
 ->where('clinvar_tab.assembly', 'like', '%GRCh38%')
```
or so?

**Comment by julianovmartins** [comment]
@acasar , I'm doing as the code below and it is working perfectly.
```php
return DB::select('SELECT `clinvar_snpsift_grch38`.*, `clinvar_tab`.*, `clinvar_moi`.*
FROM `clinvar_snpsift_grch38`
LEFT JOIN `clinvar_tab`
ON
  `clinvar_snpsift_grch38`.`rs` = `clinvar_tab`.`rs_dbsnp` AND `clinvar_tab`.`assembly` LIKE \'GRCh38\' AND `clinvar_tab`.`rs_dbsnp` IS NOT NULL
LEFT JOIN
  `clinvar_moi`
ON
  `clinvar_snpsift_grch38`.`rs` = `clinvar_moi`.`clinvar_id` AND `clinvar_moi`.`clinvar_id` IS NOT NULL
WHERE
  `clinvar_snpsift_grch38`.`id` = ?', [$id]);
```
@swalker2 , in the clinvar_tab.assembly field can have only two values. 'GRCh38' or 'GRCh37'. No need wildcard.

**Comment by acasar** [comment]
@julianovmartins You are basically saying that this works:

```php
`clinvar_snpsift_grch38`.`rs` = `clinvar_tab`.`rs_dbsnp` AND `clinvar_tab`.`assembly` LIKE ? AND `clinvar_tab`.`rs_dbsnp` IS NOT NULL
```

And this doesn't:

```php
`clinvar_snpsift_grch38`.`rs` = `clinvar_tab`.`rs_dbsnp` AND `clinvar_tab`.`assembly` LIKE ? AND `clinvar_tab`.`rs_dbsnp` IS NOT NULL
```

You will notice that both conditions are the same, so the problem must be something else.

**Comment by julianovmartins** [comment]
@acasar , look this line
```php
->where('clinvar_tab.assembly', 'like', 'GRCh38')
```
This line of code above, is producing this query below and sending literally to the database with the character '?'
```sql
 AND `clinvar_tab`.`assembly` LIKE ?
```
The correct way would be to send this to the database:
```sql
 AND `clinvar_tab`.`assembly` LIKE 'GRCh38'
```
It seems that the method 'where' (or rather, the method 'on') is replacing the third parameter ('GRCh38') by the character '?'.

**Comment by fhb12345** [comment]
@julianovmartins 

Thats a default behaviour of php PDO, he replaces any values with  ?, to avoid sql injections, when you execute it'll replace the ? with your original values and send them to the mysql, so dont be afraid those question marks will be replaced when this query is executed.

You can check this behaviour here: http://php.net/manual/pt_BR/pdo.prepare.php

**Comment by julianovmartins** [comment]
@fhb12345 , I know this behavior, but laravel framework is sending to mysql without replacing the character '?'. As I said earlier, it is literally sending the character '?' for mysql.

**Comment by acasar** [comment]
@julianovmartins This is how PDO works. Query and bindings are sent separately to avoid SQL injection attacks. All PDO queries work this way.
