### ISSUE TITLE
Localization directory structure support

### ISSUE THREAD

**Issue by Herobs** [laravel/framework#14212]
It seem that the localization dont support sub-directory, I think it would be better if the localization structure can be same to the view structure.

In a same view, all localization usually have the same prefix(namespace), new directive required to support it(custom directory cant solve it).

**Comment by Herobs** [comment]
OK, the first problem can be solved with nested array, but I think use separate files will better.

**Comment by brunogaspar** [comment]
It does support nested directories.

You're probably using the dotted syntax to tell it's a directory, which is wrong.

## Example

> resources/lang/en/foo/bar/baz/bat.php

```php
<?php

return [
    'hello' => 'Hello',
];
```


Incorrect:
```php
{{ trans('foo.bar.baz.bat.hello') }}
```

Correct:
```php
{{ trans('foo/bar/baz/bat.hello') }}
```

**Comment by Herobs** [comment]
@brunogaspar thanks, I really used dotted syntax.

I cant find anything about this in document, may be it shoud be updated.

**Comment by brunogaspar** [comment]
Feel free to submit a Pull Request to the docs :)

**Comment by Herobs** [comment]
@brunogaspar how do you think about the second suggestion

**Comment by acasar** [comment]
@Herobs Since localization files can have nested array structure (multi-level arrays) it makes sense to reference nested arrays with a ``.`` and nested directories with a ``/``. Otherwise it's not possible to determine the path to the lang file.
