### ISSUE TITLE
No cache header for auth redirects

### ISSUE THREAD

**Issue by tjomamokrenko** [laravel/framework#14229]
I am using cloudflare and they say that [they cache 301 and 302 redirects](https://support.cloudflare.com/hc/en-us/articles/200168326-Are-301-and-302-redirects-cached-by-CloudFlare-).

Well, according to HTTP standart they are right. But `AuthenticatesAndRegistersUsers` trait stops working properly when 302 redirects are cached. So, I suggest adding a `Cache-Control: private, no-cache or public, max-age=0` header to each redirect there, because this is how it should be according to the standart.

**Comment by tjomamokrenko** [comment]
Or.. A better solution for me and people like me would be to create a middleware which checks if response is instance of `Illuminate\Http\RedirectResponse`, then add such a header. Anyway, PR may help someone. But I see that it's wrong to add that header everywhere just because someone is using cloudflare :)

**Comment by crynobone** [comment]
It does make sense to cache 301 redirect status. As it does indicate permanently moved resource, right?

**Comment by GrahamCampbell** [comment]
Thanks, but we don't process proposals here. Please review the contribution guidelines first.
