### ISSUE TITLE
Unable to Store Image and video file using Storage::put($file , $content) 

### ISSUE THREAD

**Issue by Rahul-Giri** [laravel/framework#14239]
Hi,
Just a simple doubts-

i'm trying to store my image and video file on storage using Storage facade.
but i'm confused because i'm unable to store that file on storage folder.
i'm using intervention image package and when i just try to save my modified $file
```
Storage::put($file); 
```
it's throwing error that 2 argument  missing etc.

i searched everywhere on the net regarding this issue and i found
```
Storage::put($file , $content) 
```
now what is ```$content``` in this case when i'm trying just save an image to my folder ?

and one more thing

How do i return a full path of that file which can be accessible from different domain.
 i'm building an API :)

Thanks for the help in advance

**Comment by GrahamCampbell** [comment]
> now what is $content in this case when i'm trying just save an image to my folder ?

This is the actual file contents.

> How do i return a full path of that file which can be accessible from different domain.

Sorry, but this is not a support forum. There are some forums about though. Feel free to ask on there.
