### ISSUE TITLE
Compound unique validation

### ISSUE THREAD

**Issue by johnwheal** [laravel/framework#14233]
It is common to require a compound unique index e.g. `$table->index(['account_id', 'created_at']);`. Laravel does not, however, support validation of compound unique indexes. It is possible to write a custom rule or use a third party package such as https://github.com/felixkiss/uniquewith-validator.

Is there any reason why this is not included directly in the Laravel Framework? Would a PR for this be potentially accepted?

**Comment by themsaid** [comment]
I think you can do this

```
'account_id' => 'unique:users,account_id,NULL,id, created_at,'.input('created_at')
```

This will only check for a unique account_id in the set of records where the created_at field equal the one given in the form.
