### ISSUE TITLE
artisan scheduler:clear 

### ISSUE THREAD

**Issue by mskenderian** [laravel/framework#14235]
Proposal just for thought.
We need a artisan command to clear/remove all schedule files created when running a scheduler that has a withoutOverlap. if server reboots and we have a long running task. the scheduler file located in /storage/framework doesnt get deleted, after the reboot those scheduled tasks never get run because that file is still there. Then we can make set up that command to run at server boot to clean out any of those files that are still there.
Better... if there is a API that the code can call to update the modified time for the schedule file that was created, that would be better. that way we know that the task is still running and the user can create another schedule task that cleans out any of those files if the modified time has exceeded x min.

**Comment by GrahamCampbell** [comment]
Thanks, but we don't process proposals here. Please review the contribution guidelines first.
