### ISSUE TITLE
Validation problem with "*.name" after update from Laravel 5.2.30 to next versions

### ISSUE THREAD

**Issue by migoca** [laravel/framework#14232]
After upgrading Laravel from 5.2.30 to .31 and next versions I have problem with these types of validations:

```
  public function rules()
    {
        return [
            '*.name' => 'required',
            '*.slug' => 'required|alpha_dash'
        ];
    }
```
I use this to validate for multiple languages: es.name, en.name, it.name, etc. But with the update the result is:

The _token.name  field is required.
The _token.slug  is required.

In my form i have:
```
{!! csrf_field() !!}
### And the inputs:
<input type="text" name="es[name]">
<input type="text" name="en[name]">
<input type="text" name="es[slug]">
<input type="text" name="en[slug]">
```

**Comment by taylorotwell** [comment]
@themsaid any ideas?

**Comment by themsaid** [comment]
@migoca your validation rules here state that for every form field there should be array members with keys `name` and `slug`, this includes the csrf token field `_token`. 

I don't think this behaviour is recent, are you sure it was working differently in 5.2.30?

Anyways I suggest you use a structure like this:

```
<input type="text" name="post_data[es][name]">
<input type="text" name="post_data[es][slug]">
```

```
return [
    'post_data.*.name' => 'required',
    'post_data.*.slug' => 'required|alpha_dash'
];
```

**Comment by themsaid** [comment]
@migoca I'm not sure if that PR caused the change in behaviour, but anyways I think the current behaviour makes sense, when you use `*` at the beginning of the attribute it means `any field` and in this case it includes the csrf token field as well.

**Comment by migoca** [comment]
Thanks @themsaid for your help! You are right, the current behavior makes more sense.
