### ISSUE TITLE
LengthAwarePaginator last page has no links is blank

### ISSUE THREAD

**Issue by MikeOOP** [laravel/framework#14238]
Say you have 152 items to paginate.  
$this->lastPage = (int) ceil(152 / 10);  = 15.2
ceil 15.2 gives 16
so page 16 is blank only need 15 pages to paginate 152 items 

namespace Illuminate\Pagination;

class LengthAwarePaginator extends AbstractPaginator implements ...

Line 49
$this->lastPage = (int) ceil($total / $perPage);

Line 49 change to
$this->lastPage = (int) floor($total / $perPage);

**Comment by fhb12345** [comment]
You need 16 pages to paginate 152 items, the 16 page will have 2 items, since you are showing 10 items per page.

If we change this when you have 12 items you'll get only 1 page instead of 2 pages,

12 / 10 = 1.2 floor would turn to 1 but you need 2 pages for this...

**Comment by MikeOOP** [comment]
Hi Fernando,

I must be working to many hours.

You are right...

oops

Mike

**Comment by Francismori7** [comment]
Cannot find out if this is trolling or not.
