### ISSUE TITLE
Possible bug when trying to drop two (or more) columns from a SQLite database through Migration

### ISSUE THREAD

**Issue by Deleugpn** [laravel/framework#14240]
I think I found a possible bug when trying to drop two columns from a SQLite Database. My experience with major projects are practically non-existent for me to try and report this bug through a pull request, so I'll just try to describe it here and hopefully someone can create a pull request about it.

**If someone do so, please link it here so I can review what you did and learn more about it.**

## The Bug

You cannot have two (or more) `dropColumn` on a `down()` migration file while using SQLite. Ex: 

```
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::table('shop', function (Blueprint $table) {
            $table->dropColumn('anything');
            $table->dropColumn('anything_else');
        });
    }
```

## Impact

Following some of Jeffrey Way's teaching, I was using SQLite `:memory:` to run my Unit Tests when I came across this issue. If you ever make a migration with more than one column to be dropped through `down()` method, you will no longer be able to rely on SQLite `:memory:` to run your tests.

## Reason

The `\Illuminate\Database\Schema\Blueprint::toSql` method is responsible for gathering a list of `statements` to be executed in order to achieve whatever the migration wants to do.
This is done by merging statements returned by `\Illuminate\Database\Schema\Grammars\SQLiteGrammar` **for each command** desired. In this case, we're merging the sequence of statements returned by `SQLiteGrammar::compileDropColumn()`. The method 
`\Doctrine\DBAL\Platforms\SqlitePlatform::getAlterTableSQL()` will give a list of statements that recreates the whole table as follows: 

```
Array
(
    [0] => CREATE TEMPORARY TABLE __temp__shop AS SELECT id, name, anything_else FROM shop
    [1] => DROP TABLE shop
    [2] => CREATE TABLE shop (id INTEGER NOT NULL, name VARCHAR(255) NOT NULL COLLATE BINARY, anything_else INTEGER DEFAULT NULL, PRIMARY KEY(id))
    [3] => INSERT INTO shop (id, name, anything_else) SELECT id, name, anything_else FROM __temp__shop
    [4] => DROP TABLE __temp__shop
)
```

Note that the first column we're dropping is `anything`, so `anything_else` is backed up because we didn't perform any action on it yet. But as the **for each** command moves to the next step, it repeats the process of getting a list of SQL Statements that needs to be executed, which leads to the following list

```
Array(
    [5] => CREATE TEMPORARY TABLE __temp__shop AS SELECT id, name, anything FROM shop
    [6] => DROP TABLE shop
    [7] => CREATE TABLE shop (id INTEGER NOT NULL, name VARCHAR(255) NOT NULL COLLATE BINARY, anything CLOB DEFAULT NULL COLLATE BINARY, PRIMARY KEY(id))
    [8] => INSERT INTO shop (id, name, anything) SELECT id, name, anything FROM __temp__shop
    [9] => DROP TABLE __temp__shop
)
```

Now, notice that we have 9 commands to be executed, but the 6th one (index 5 of array) will give an error because it thinks we still have the `anything` column, which is no longer true.

## Work-around

Never add more than one column per migration if you plan on using SQLite for your Unit Tests. When changing a table through Migration, you should make one migration for each column that you will be adding, so you can have just a single column in the `down()` method.

**Keywords**: dropColumn; Illuminate\Database\QueryException; Migration; SQLite; SQLSTATE[HY000]: General error: 1 no such column: [column name]

------------------------------------

## Reproducing it by cloning my repository

1- Clone my repository: `git clone https://github.com/Deleugpn/sqlite-drop-column-bug.git sqlite-drop-column-bug`
2- `cd sqlite-drop-column-bug`
3- `composer install`
4- `php artisan migrate`
5- `php artisan migrate:reset` --> see error message.

## Reproducing the bug manually

1- Create a new clean project: `composer create-project --prefer-dist laravel/laravel sqlite-drop-column-bug`
2- Require Doctrine DBAL: `composer require doctrine/dbal`
2- Make a table migration: `php artisan make:migration create_some_table`
3- Add `up()` (create table) and `down()` method (drop table): 

```
    public function up() {
        Schema::create('shop', function (Blueprint $table) {
            $table->integer('id', true);
            $table->string('name', 80);
        });
    }

    public function down() {
        Schema::drop('shop');
    }
```

4- Make a new migration: php artisan make:migration alter_same_table
5- add `up()` (add new columns) and `down()` method (remove columns):

```
    public function up() {
        Schema::table('shop', function (Blueprint $table) {
            $table->text('anything')->nullable();
            $table->integer('anything_else')->nullable();
        });
    }

    public function down() {
        Schema::table('shop', function (Blueprint $table) {
            $table->dropColumn('anything');
            $table->dropColumn('anything_else');
        });
    }
```

6- change `.env` to sqlite: `DB_CONNECTION=sqlite`
7- `touch homestead` (or make sure DB_DATABASE points to an existent empty file)
8- run `php artisan migrate`
9- run `php artisan migrate:reset` and see error.

**Comment by crynobone** [comment]
![screenshot_2016-07-07-08-48-20_com android chrome](https://cloud.githubusercontent.com/assets/172966/16639172/a8a73b56-441f-11e6-8bf3-e859de44b864.png)

**Comment by Deleugpn** [comment]
Duplicate of #2979

**Comment by cdarken** [comment]
This happens even with a single column, with or without array notation.
