### ISSUE TITLE
post_max_size validation failing with MethodNotAllowedHttpException

### ISSUE THREAD

**Issue by sujit223** [laravel/framework#14244]
If we make an application that can be used globally on any server. And we don't know what size of files may be tried to be uploaded on a global applications. 

But getting a MethodNotAllowedHttpException is not at all cool instead there could be an exception that could have catched only for file sizes that are uploaded. And by catching this exception we can handle post_max_size exception.

Yes we can catch this exception at the time of upload just by using JS. But i don't rely on JS as js could be disabled in the browser.
Also we can use request to limit the file sizes. But catching an exception would be awesome.

**Comment by efrontsa** [comment]
You could use this middleware `\Illuminate\Foundation\Http\Middleware\VerifyPostSize`

**Comment by fahmilatib** [comment]
I'm having similar problem here. I have a form with file input that submits to a `PUT` route.

@efrontsa What you suggested only works if there's no form method spoofing involved. In my case, when I upload a file that exceeds `post_max_size` value, php will empty out the `$_POST` superglobal so what should have been submitted to a `PUT` route, ends up being `POST` instead thus throwing the `MethodNotAllowedHttpException`.

So even if I apply `VerifyPostSize` middleware to the intended route, it will never run.

Any workaround, or perhaps I missed out something here?

**Comment by themsaid** [comment]
You can solve this by adding `\Illuminate\Foundation\Http\Middleware\VerifyPostSize` to your application global middleware with `CheckForMaintenanceMode::class`, the middleware will throw a `PostTooLargeException` that you can catch and react.
