### ISSUE TITLE
Error on Vagrant Up related to Guest Permissions

### ISSUE THREAD

**Issue by joshuavd** [laravel/framework#14248]
Hello,

I am new to laravel but have successfully installed and setup a few machines.  I ran into my first error that I am not sure about:

> $ vagrant up --provision
> Bringing machine 'default' up with 'virtualbox' provider...
> ==> default: Checking if box 'laravel/homestead' is up to date...
> ==> default: Running provisioner: file...
> Guest-specific operations were attempted on a machine that is not
> ready for guest communication. This should not happen and a bug
> should be reported.

Is this where I should report this bug?  Is there any other file that is needed for me to help contribute to a fix?

**Comment by bickerstoff** [comment]
I think this is more of a vagrant issue and not really centric to Laravel.
Similar vagrant issues:
- https://github.com/mitchellh/vagrant/issues/2251
- https://github.com/mitchellh/vagrant/issues/5732 

And maybe useful:
http://superuser.com/questions/868370/guest-specific-operations-were-attempted-on-a-machine-that-is-not-ready-for-gue
