### ISSUE TITLE
Feature Request: Allow Post (see comment) to accept files when testing

### ISSUE THREAD

**Issue by AdamKyle** [laravel/framework#14242]
So the [following method](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php#L123) doesn't allow you to pass in file's, you have to use `->call( ... )`, which is fine, but then you cant use the awesome features like `seeJsonStructure` and other associated with it.

**Comment by themsaid** [comment]
Thank you for your suggestion, this repository is for Bug reporting, for suggestions and feature requests please use the https://github.com/laravel/internals repo.
