### ISSUE TITLE
Default password reset email causes RFC 5322 not compliant complaint

### ISSUE THREAD

**Issue by CarterZhou** [laravel/framework#14243]
I was testing the password reset feature shipped by Laravel 5.2 today, using Mailgun sandbox domain.
I noticed from Mailgun logs that whenever those emails was going to be sent to my Hotmail account, Mailgun failed to deliver and returned a RFC 5322 not compliant complaint. I think it is from Microsoft mail servers. And whenever those emails was going to be sent to Gmail, I received all the mails but Gmail labelled them as "Unknown sender".

I digged into Laravel source and found in trait Illuminate\Foundation\Auth\ResetsPasswords, on Line 122, when setting up password reset mail, the function resetEmailBuilder() doest not include any "from" or "Application Name" info.

I know I can override the function in the default App\Http\Controllers\Auth\PasswordController, doing something like:

```php
use Illuminate\Mail\Message;
...

protected function resetEmailBuilder()
{
    return function (Message $message) {
        $message->from(env('MAIL_FROM'), env('MAIL_NAME'));
        $message->subject($this->getEmailSubject());
    };
}

```

But I consider why not the Laravel source adds "from" and "application name" when setting up password reset mail, and set two sample environment variables in .env.example in the first place?

**Comment by it-can** [comment]
what happens when you change the "from" section in your ```config/mail.php``` file?

```
'from' => [
        'address' => 'test@test.com',
        'name'    => 'My website',
    ],
```

I tested this and for me this works....

**Comment by CarterZhou** [comment]
@it-can Totally forgot the configuration file. Thank you.
