### ISSUE TITLE
Web middleware by default 

### ISSUE THREAD

**Issue by kdanieladams** [laravel/framework#14250]
In this commit 5c30c98db96459b4cc878d085490e4677b0b67ed web middleware is applied to every route in the routes file by default.  The routes file seems to be the recommended place to put all routes.  At the same time, in the Http Kernel, there's a protected property for defining middleware that's hit on every request.  

It seems to me these are contradictory approaches to solving a similar problem.  Do they both need to happen?  Why don't we apply the web middleware group to all requests using the protected property of the Http Kernel instead of applying any middleware group by default to all routes?  I suggest this because the default middleware group assignment occurs in the RouteServiceProvider...which is something I haven't had to touch in the past.  Consequently, it became quite an adventure to figure out what was wrong with my app...because I hadn't considered the idea of modifying that service provider.

This became an issue for me while I was troubleshooting sessions with Redis.  Laravel kept creating a new session for each request.  It turns out, I was specifying the web middleware group on a set of routes for the app, which was applying the web middleware a *second* time to all those routes, which broke the EncryptCookies middleware, which made the session cookies worthless...so laravel had to reinstantiate the session each request.      

Alternatively, maybe middleware could be handled a bit differently.  Should it be possible to apply a middleware or middleware-group twice to a route?  Maybe if a middleware has already been applied to a route, the middleware assignment could be skipped.

**Comment by GrahamCampbell** [comment]
Thanks, but this isn't the place to discuss things like this. Please review our contribution guide.
