### ISSUE TITLE
Time travel in tests

### ISSUE THREAD

**Issue by dmoreno** [laravel/framework#14253]
Carbon library has a very useful and easy to use feature to travel in time inside your tests:

```javascript
$knownDate = Carbon::create(2001, 5, 21, 12); // create testing date
Carbon::setTestNow($knownDate);               // set the mock (of course this could be a real mock object)
```

This works with Laravel in most pieces of code, but not all. Because php built function `time()` is used 16 times in Laravel code base (I'm having issues with [Cookie expire time generation](https://github.com/laravel/framework/blob/baab230f1c2752a6e17ff3a5e86e0cd4d147a3bf/src/Illuminate/Cookie/CookieJar.php#L55)).

As Carbon is a Laravel dependency, I thinks is possible to replace `time()` calls for Carbon equivalent. This way, time travel would be possible in Laravel tests. I think this would be awesome!

What do you think?

**Comment by themsaid** [comment]
Thank you for posting this, I wish I had known about it earlier in my career :D

**Comment by dmoreno** [comment]
@themsaid, thanks! good work!

**Comment by themsaid** [comment]
@dmoreno :)
