### ISSUE TITLE
Scheduled task output always e-mailed when appending

### ISSUE THREAD

**Issue by drawmyattention** [laravel/framework#14256]
If I set up the following scheduled command, in ```kernel.php```

    $schedule->command('mycommand')
            ->everyMinute()
            ->sendOutputTo('somefile.log', true)
            ->emailOutputTo(['me@email.com'], true);

I will receive an error e-mail every minute, even if the job fails only once. 

This is because the scheduler appends to the ```somefile.log```file the first time the error occurs, (at which point we should receive the e-mail) but then subsequent runs of the task, also trigger an e-mail, even if the task executed successfully and without output, because ```somefile.log``` already has some content (from the previous failure).

This makes it hard to keep a log of the scheduled command, without being bombarded with e-mails every minute.

**Comment by GrahamCampbell** [comment]
Feel free to send a PR. :)
