### ISSUE TITLE
Eloquent and query builder giving only first two characters of id 

### ISSUE THREAD

**Issue by obb12** [laravel/framework#14254]
When I acces Id it's only the first two characters

**Comment by obb12** [comment]
i have id set to varchar

**Comment by obb12** [comment]
it works on raw sql

**Comment by vivekrajr** [comment]
@obb12 Could you please be more specific? How is your model and migration setup? Could you show an example of your use case working with raw sql and not working with Eloquent?

**Comment by obb12** [comment]
Table Has a pk varchar string


Lähetetty iPadista

**Comment by acasar** [comment]
If you're not using autoincrementing integer key, you should set ``public $incrementing = false;`` on your Model class.

From the docs:

> In addition, Eloquent assumes that the primary key is an incrementing integer value, which means that by default the primary key will be cast to an int automatically. If you wish to use a non-incrementing or a non-numeric primary key you must set the public $incrementing property on your model to false.
