### ISSUE TITLE
[5.2 suggestion] Change Command $signature and $description instance variables to constants

### ISSUE THREAD

**Issue by kwebble** [laravel/framework#14257]
When defining a command as a child class of `Command` 2 properties have to be included, `$signature` and `$description`. As I understand their values do not change during execution. 

Since the information is the same for all instances isn't it clearer to use class constants for this:

    /** The command signature. */
    const SIGNATURE = 'do:something';

    /** The command description. */
    const DESCRIPTION = 'It does something.';

This also exposes these values to other places in the code, making it easy to refer to them instead of duplicating string literals, for example when defining a schedule:

    $schedule->command(DoItCommand::SIGNATURE)->everyFiveMinutes();

I haven't investigated the implications of this refactoring, but I think it would improve the code.

**Comment by fhb12345** [comment]
It's like this to keep a default syntax for declaring properties, it's the same syntax used in many other places, so idk if it would be a good change since people are used with the protected $property syntax.

**Comment by kwebble** [comment]
In general I declare literals as constants to:
- give them a descriptive name
- document their meaning
- create a language element you can refer to in code
- prevent duplication

I think it makes code clearer, better understandable and easier to refactor. So why not go for the improvement?

**Comment by themsaid** [comment]
@kwebble did you get the chance to work on a PR for that?

**Comment by kwebble** [comment]
@themsaid  no, I need to work on other stuff. And from what I've seen in Laravel examples and library code it's not common to only put literal strings in constants. So I don't think if such a style change would be applied.

But in my own code it's what I do as much as possible.
