### ISSUE TITLE
Possible bug in constraining eager loads

### ISSUE THREAD

**Issue by SaeedPrez** [laravel/framework#14266]
Hello,

I was expecting the below code to return each parent row with one child row but this query only returns the child of the first parent row. Is this a bug/unexpected behavior or have I understood the constraining wrong?

```
$parentChildren = App\Parent::with(['children' => function ($query) {
    $query->latest()->first();
}])->get();
```

I'm using Laravel 5.2.39 on Windows 10 and Homestead.

Thank you.

**Comment by swalker2** [comment]
Hi, shouldn't your callback return something?
```
return $query->latest()->first();
```

**Comment by SaeedPrez** [comment]
No problem, according to the documentation it shouldn't

https://laravel.com/docs/5.2/eloquent-relationships#constraining-eager-loads

I was expecting Laravel to run N+1 queries on the child table, but in fact Laravel only runs two queries, one on the parent table and one on the child table, so the correct query would be..

```
$parentChildren = App\Parent::with(['children' => function ($query) {
    $query->latest()->groupBy('parent_id');
}])->get();
```

This would return each parent with latest child.
