### ISSUE TITLE
inRandomOrder is terribly inefficient 

### ISSUE THREAD

**Issue by salarmehr** [laravel/framework#14263]
`inRandomOrder` is terribly inefficient when database is not small. For example, if a database has 50000 rows it needs to generate 50000 random numbers and sort all rows without an index. The algorithm need to be changed. Skipping random number of rows is far more efficient as is explained here:
http://akinas.com/pages/en/blog/mysql_random_row/

The method was initially introduced in order to get some random rows not ordering them randomly.

**Comment by dwightwatson** [comment]
The method explained where?

The `inRandomOrder` method is on the query builder, so one would expect it to call the random function of the underlying database driver. If you wanted to use a specific, different sort of randomisation I think that's the sort of thing you'd implement in your own project.

**Comment by barryvdh** [comment]
If you have something that will work more efficient, without configuration, it would probably be accepted as PR.  What do you suggest?

**Comment by salarmehr** [comment]
Skipping random number of rows is far more efficient as is explained here:
http://akinas.com/pages/en/blog/mysql_random_row/

**Comment by barryvdh** [comment]
Yes, for selecting 1 item. But that doesn't work for multiple rows.

**Comment by salarmehr** [comment]
@barryvdh If my memory serve me rightly  that method where initially suggested for choosing a single raw. However, for selecting multiple rows, a multiple row can be selected and be `UNION`ed. Normally the application needs to choose randomly a very tiny proportion of tables rows. And that is yet far more efficient that random sorting.

**Comment by barryvdh** [comment]
So as I said, create a PR ;)

**Comment by HDVinnie** [comment]
@salarmehr any solution you recommend. I am also noticing inRandomOrder() is very slow with large tables.

**Comment by salarmehr** [comment]
@vdhicts I have already suggested something in the above converstaion.
