### ISSUE TITLE
Multiple laravel projects on one server in different directories

### ISSUE THREAD

**Issue by dhiman252** [laravel/framework#14262]
I have configured 2-3 projects on my server in different directories, the problem I am facing is that when I request for one project(http://www.domain.com/project1) in the browser then after some time I request for another project(http://www.domain.com/project2) then abnormal behavior is seen.
Following problems are being observed
1) The user loges out during request
2) "No supported encrypter found. The cipher and / or key length are invalid" - error occurs too frequently, not sure have to run the command "php artisan key:generate" but its a temporary fix.
3) Sometimes the configuration for the project are not loaded, I have set all the parameters for the project in the`.env` file still sometimes unable to load configurations and database error is displayed is some spanish language
4) 'Token mismatch' also but not too frequently.

I don't know whether its the bug with the framework or I need to do something with my configurations.

**Comment by GrahamCampbell** [comment]
Please ask on the forums.

**Comment by lawlietee** [comment]
I have the same issue, did you find out how to solve it?
