### ISSUE TITLE
Sending html email via Mailgun driver corrupts the content.

### ISSUE THREAD

**Issue by mlanin** [laravel/framework#14269]
When I try to send a message via Mailgun, all my message becomes corrupted like so:
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "h=
ttp://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns=3D"h=
ttp://www.w3.org/1999/xhtml">
<head>
  <meta name=3D"viewport" content=
=3D"width=3Ddevice-width"/>
  <meta http-equiv=3D"Content-Type" content=
=3D"text/html; charset=3DUTF-8"/>
  <title>Welcome</title>=

  <style type=3D"text/css">
    * {
      margin: 0;
      padding=
: 0;
      font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, =
sans-serif;
      font-size: 100%;
      line-height: 1.8;
      colo=
r: #1e3948;
    }
```

What is wrong? Is it a problem with Mailgun itself or with Laravel driver?

**Comment by cpiggott** [comment]
@mlanin Did you figure out why this is happening?

**Comment by jmeridth** [comment]
@mlanin did you figure out the issue?

**Comment by mlanin** [comment]
@cpiggott @jmeridth actually yes, but I completely forgot what was the problem :( What I do remember is that it was nothing to do with Laravel, that's why I closed this ticket

**Comment by jmeridth** [comment]
@mlanin I found the following in the new mailgun docs and have yet to test it but believe it is the culprit. :smile:  thank you for response.  :beers:

**Comment by mlanin** [comment]
@jmeridth as far as I recall now, it was something about imported css files. When I switched to inline styling everything becomes right.
