### ISSUE TITLE
Eloquent Events

### ISSUE THREAD

**Issue by mojosef** [laravel/framework#14267]
The update method it doesn't appear to trigger any of the model events.

eg `SomeModel::where('id', 1)->update(['name'=>'Joe']);`

**Comment by themsaid** [comment]
You're calling the `update` method of the Builder here, not the model.

Use this instead:

```
SomeModel::where('id', 1)->first()->update(['name'=>'Joe']);
```

Notice that `SomeModel::where('id', 1)->first()` might return null though.

**Comment by mojosef** [comment]
Ah I see thank you! Would the same work with multiple results? 

`SomeModel::where('id', 1)->get()->update(['name'=>'joe'])`

**Comment by crynobone** [comment]
```php
SomeModel::where('id', 1)->get()->each(function ($model) {
    $model->update(['name' => 'joe']);
});
```

**Comment by caiquecastro** [comment]
Would this code generate N+1 sql query?

**Comment by themsaid** [comment]
1 query to get the models, and 1 for every model.
