### ISSUE TITLE
Authentication to MySQL database fails when password exceeds certain length

### ISSUE THREAD

**Issue by cbj4074** [laravel/framework#14274]
Laravel `v5.1.40`

If I configure a database connection with a password that is 64 characters in length, Laravel is unable to connect to the database:

```
PDOException: SQLSTATE[HY000] [1045] Access denied for user 'user'@'localhost' (using password: YES) 
```

I am able to log into the database as expected from within the terminal, with `mysql -uuser -p`, pasting-in the 64-character password.

If I reduce the password to 32 characters in length, Laravel is able to authenticate to the database successfully.

Is there anything in the framework that would limit the accepted database password length artificially?

I have not tried this with any other database driver as yet.

Thanks for any insight!

**Comment by JayBizzle** [comment]
What version of MySQL are you running?

**Comment by cbj4074** [comment]
Thanks for taking a look. I'm running MariaDB:

`mysql  Ver 15.1 Distrib 10.0.25-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2`

**Comment by huglester** [comment]
Try changing MYSQL_HOST to localhost or 127.0.0.1 ? 

Btw can you connect from cli with:
mysql -hlocalhost -uuser -p
and
mysql -h127.0.0.1 -uuser -p

?

**Comment by cbj4074** [comment]
@huglester Thanks for checking it out.

Yes, I stated in my initial post that I am able to connect from the CLI just fine, and that I'm able to connect from within Laravel just fine when I change the password to be 32 characters (instead of 64).

So, I don't think it's a networking or name-resolution issue.

**Comment by jhdxr** [comment]
I tried to connect to mysql 5.7.11 with `1234567890123456789012345678901234567890123456789012345678901234` (64 chars) and everything is fine (laravel 5.2.41)
I doubt if there is something special character in your password. can you connect to mysql with pdo directly? I mean you can write a simple php script without laravel to test this problem.

**Comment by cbj4074** [comment]
Thanks for looking into it, @jhdxr , and I apologize for the delayed response. When I'm back in the office tomorrow, I'll put it through the paces and provide an update. More soon!

**Comment by cbj4074** [comment]
I just tried to reproduce this and cannot. We must conclude therefor that it's operator error. Shame on me! Thanks for the help here, everyone.
