### ISSUE TITLE
Generates compiled file on root directory when set compiled path doesn't exists

### ISSUE THREAD

**Issue by skys215** [laravel/framework#14271]
I cloned a lumen-based project and changed my storage path.
When I visit the homepage, it comes out with the error:
```
ErrorException in Filesystem.php line 81:
file_put_contents(/f536123a25b04be16752e137caae936b): failed to open stream: Permission denied
```
It's quite weird that cache file is going to store at root directory. I didn't set that kind of thing.
After debugging, I found out that the problem comes from [config/view.php#L31](https://github.com/laravel/laravel/blob/master/config/view.php#L31).
According to the PHP Document of [realpath](http://php.net/realpath) function, it will return false when the directory doesn't exists, which will be convert to empty string `""` when generating the compiled path at [View/Compilers/Compiler.php#44](https://github.com/laravel/framework/blob/5.2/src/Illuminate/View/Compilers/Compiler.php#L44).
I think the compiled path should be created when the application starts or it's better to dump more friendly message rather then compiling on the root directory.

**Comment by GrahamCampbell** [comment]
Thanks for the report.

**Comment by GrahamCampbell** [comment]
See https://github.com/laravel/framework/pull/14277.
