### ISSUE TITLE
Why does Eloquent\Model::hydrate() returns "existing" model instances?

### ISSUE THREAD

**Issue by aguimaraes** [laravel/framework#14288]
```php
    public static function hydrate(array $items, $connection = null)
    {
        $instance = (new static)->setConnection($connection);

        $items = array_map(function ($item) use ($instance) {
            return $instance->newFromBuilder($item);
        }, $items);

        return $instance->newCollection($items);
    }
```

Why is it using newFromBuilder() to create an existing¹ instance instead of newInstance() that would return a normal instance?

Is this the expected behavior? Since I'm creating a collection from a primitive array, I don't see the point of returning existing¹ instances.

[1] instances which public property `exists` is true

/cc @JosephSilber

**Comment by JosephSilber** [comment]
The point of the hydrate method is to hydrate it with records from the database. In fact, it's even used by the Eloquent Query Builder's get method.

Why would you want to hydrate it from an array that didn't come from the DB?

**Comment by aguimaraes** [comment]
I was using hydrate to create a bulk of pre-filled models.
The data was not coming from the database.
Sorry, I was not aware of the meaning for "data hydrators".
Thanks.
