### ISSUE TITLE
[5.2?][Proposal] Collections/Array method proposal...

### ISSUE THREAD

**Issue by superamadeus** [laravel/framework#14303]
# Problem
I'd like to retrieve all of the collection values for a set of keys. What I'd like to perform is  (what I see as) a mixture of a _pluck_ and an _only_ operation. (Perhaps more obviously, it is a repeated _only_ call on each item in a collection.)
#### Given
```php
    $collection = collect([
        ['id' => 'prod-100', 'name' => 'Desk', 'price' => 100, 'description' => 'A desk.'],
        ['id' => 'prod-200', 'name' => 'Chair', 'price' => 200, 'description' => 'A chair.'],
        ['id' => 'prod-300', 'name' => 'Lamp', 'price' => 300, 'description' => 'A lamp.'],
    ]);
```

I'd like to retrieve the following:
```php
    $items = [
        ['id' => 'prod-100', 'name' => 'Desk', 'price' => 100],
        ['id' => 'prod-200', 'name' => 'Chair', 'price' => 200],
        ['id' => 'prod-300', 'name' => 'Desk', 'price' => 300],
    ];
```
___or___ perhaps have them keyed by a certain key value...
```php
    $items = [
        'prod-100' => ['name' => 'Desk', 'price' => 100],
        'prod-200' => ['name' => 'Chair', 'price' => 200],
        'prod-200' => ['name' => 'Desk', 'price' => 300],
    ];
```
__and__ I'd like to be able to do so with an elegant call (_pluckOnly_ is a temporary name).
```php
    $items = $collection->pluckOnly(['name', 'price'], 'id');
```

# Solution
The following function appears to work through my round of testing. I iterate through each item in the collection and call the _only_ function on each of them to obtain only the desired key values. Then I append the item to the resulting array with an optional key. This functions operates on an array, but can be applied to a collection as most of the 'Arr' functions do.
#### framework/Illuminate/Support/Collection.php
```php
    ...
    /**
     * Get the values of several given keys.
     *
     * @param  string|array  $values
     * @param  string|null  $key
     * @return static
     */
    public function pluckOnly($values, $key = null)
    {
        return new static(Arr::pluckOnly($this->items, $values, $key));
    }
    ...
```
#### framework/Illuminate/Support/Arr.php
```php
    ...
    /**
     * Pluck an array of many values from an array.
     *
     * @param  array  $array
     * @param  string|array  $values
     * @param  string|array|null  $key
     * @return array
     */
    public static function pluckOnly($array, $values, $key = null)
    {
        $results = [];
        
        // explode key
        $key = is_null($key) || is_array($key) ? $key : explode('.', $key);

        foreach ($array as $item)
        {
            // obtain desired subset of the array item
            $filteredItem = static::only($item, $values);

            // If the key is "null", we will just append the value to the array and keep
            // looping. Otherwise we will key the array using the value of the key we
            // received from the developer. Then we'll return the final array form.
            if (is_null($key)) {
                $results[] = $filteredItem;
            } else {
                $itemKey = data_get($item, $key);

                $results[$itemKey] = $filteredItem;
            }
        }

        return $results;
    }
    ...
```

# Questions
What should I name this function? Is this function useful enough to be added to the framework? I have found myself needing this on many occasions, but perhaps there is a better implementation or there is a problem with this implementation. Please leave me your thoughts! I intend to make a pull request when I have chosen a name.

**Comment by fernandobandeira** [comment]
Looks like an usefull function, maybe we could also implement a function called pluckExcept? that would call the except function instead of the only...

**Comment by morloderex** [comment]
Proposals shoud go in the internals slack channel or the internal repository here under laravel namespace :)

**Comment by thecrypticace** [comment]
This is a great example of when you can solve a problem by breaking it into smaller pieces. The results you seek can be achieved by combining three operations: `map`, `only`, and either `values` or `keyBy`.

When you say `pluckOnly` you can think of this as "give me a collection where each item has been modified to only have these keys." When you want to return a modified version of every item in a collection you use `map`. When you want to restrict the keys in an array you can use `array_only`/`Arr::only` like you did in your example code above.

So, you can achieve the equivalent of `$collection->pluckOnly(['name', 'price']);` by using `->map` and `array_only`:
```
$collection->values()->map(function ($item) {
    return array_only($item, ['name', 'price']);
});
```

NOTE: If your code doesn't care if the array has been reindexed or not you don't have to call values.

If you want to key the array all you need to do is add keyBy before map like so:

```
$collection->keyBy("id")->map(function ($item) {
    return array_only($item, ['name', 'price']);
});
```

And since the Collection class is `Macroable` you can define a macro that does this if you happen to be using this operation a lot:
```
Collection::macro("pluckOnly", function ($values, $key = null) {
    $collection = $key ? $this->keyBy($key) : $this->values();

    return $collection->map(function ($row) use ($values) {
        return array_only($row, $values);
    });
});
```

All this being said… it would be handy to be able to pass an array to `pluck`

**Comment by GrahamCampbell** [comment]
> Proposals shoud go in the internals slack channel or the internal repository here under laravel namespace :)

**Comment by superamadeus** [comment]
@thecrypticace mind blown. Hella +1 response.
