### ISSUE TITLE
[5.2] artisan route:list returns "Session store not set on request"

### ISSUE THREAD

**Issue by ryrobbo** [laravel/framework#14321]
My routes.php consists solely of route controllers e.g. Route::controller('/admin', 'IndexController');

Some of my routes weren't being found (404) so I decided to troubleshoot and run "php artisan route:list" in the terminal. I get this error in response:

    [RuntimeException]
    Session store not set on request.

My Kernel.php file is pretty much default apart from some custom middleware defined in $routeMiddleware.

I am guessing that this could be related to artisan commands not automatically applying 'web' middleware via the RouteServiceProvider?

**Comment by themsaid** [comment]
Make sure you're not using the `Auth` facade in any of the controller constructors, actually make sure you're not using any session related code in your controller constructors.

**Comment by lmichailian** [comment]
Assuming you use Laravel 5.2: You'll need to use the web middleware if you need session state, CSRF protection, and more. (like the global in 5.1)

`Route::group(['middleware' => ['web']], function () {
    // your routes here
});`

**Comment by ryrobbo** [comment]
@themsaid I am not using Auth anywhere. My controllers use $this->middleware within their constructor for various session checking. Would that be the problem?

@lmichailian I attempted your suggestion but still got the same response. I had also cleared a route caching to be sure.

My app is a closed system hence the use of middleware to prevent access to public visitors. So, you're saying because of this, the route:list command is now useless? Would have been nice to have some mention of this in the docs...

Maybe in a future version we bypass any Middleware when running artisan route commands?

**Comment by themsaid** [comment]
The thing is that the route:list command creates an actual instance of the controllers, thus calling the constructor, the problem seems related to something in any of your constructors that's interacting with the session. 

That's the best I could guess based on your input :)
