### ISSUE TITLE
Validation bug for "same" rule type

### ISSUE THREAD

**Issue by eness** [laravel/framework#14325]
Hey there

Here is a simple validation example : 

```
<?php

        $this->validate($request, [
            'old_password'  => 'required',
            'new_password'  => 'required|same:new_password2',
            'new_password2' => 'required'
        ]);

?>
```

And if user posts the form with values : 

old_password = "blabla"
new_password = "123456 "     >> _notice 1 (one) whitespace at the end_
new_password2 = "123456 "     >> _notice 1 (one) whitespace at the end_

this validation check fails. I think it trims the first value but does not for the value that is used with "same:" rule so it casues the comparsion look like ("123456"  != "123456 ")

Is it some kind of bug?

**Comment by themsaid** [comment]
What version are you using? I tested on `5.2.39` and it seems to be working fine.

**Comment by eness** [comment]
I am using version 5.2.26.

Actually, I've been coding a REST Api with Laravel and this validation fails when I send the request over my rest api test tool named Postman (as a chrome extension)

But when I try that "same:" rule over a HTML form, it works without problems.

I've attached a screenshot of a small debugging when I sent my request to the validator.

![debug](https://cloud.githubusercontent.com/assets/2032225/16880593/a5a1c264-4abe-11e6-866e-145f47e488bb.png)


REQUEST TO CONTROLLER : 

POST /api/v1/website/user/change-password?new_password=123456 &amp;new_password2=123456 &amp;old_password=blabla HTTP/1.1
Host: localhost
Accept: application/json, text/plain, */*
Cache-Control: no-cache
Postman-Token: 87d72dc2-203c-7514-16dc-9b5d97bf2b67
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

**Comment by themsaid** [comment]
Can you plese do `dd($request->all())` inside the controller method and share teh results?

**Comment by eness** [comment]
Hmm, the output looks just interesting.

array:3 [
  "old_password" => "123456"
  "new_password" => "123456 "
  "new_password2" => "123456"
]

I think I've figured out the problem, and it is not related to Laravel. The bug appears on Postman extension. If you put a whitespace at the end of the last value you sent with Postman, the created request code swallows the whitespace before "HTTP/1.1" word.

POST /api/v1/website/user/change-password?old_password=blabla&new_password=123456 &new_password2=**123456 HTTP/1.1**

As Postman misdirect me with the bug I am closing the issue!
