### ISSUE TITLE
Route bindings priority (versus middleware)

### ISSUE THREAD

**Issue by ed-fruty** [laravel/framework#14329]
I want to know your opinion about route bindings priority (versus middleware).

Simple example to understand the problem is:

```php
$router->bind('product', function($product, $route) {
  dd(auth()->user()); // NULL
});
```

So, I can't do someting like:

```php
$router->bind('userArticle', function($userArticle) {
   $userId = auth()->id();

   return \App\Article::where('author_id', $userId)
            ->where('slug', $userArticle)
            ->first();
});
```

So, the question is how do you think, maybe route bindings must be resolved after middleware layer ?
Because it's really unexpected behavior, that I can not access the current user.

Fix it very simple, needs move `Illuminate\Routing\Router::substituteBindings` method from `Illuminate\Routing\Router::findRoute` to **Pipeline** part **then** in the `Illuminate\Routing\Router::runRouteWithinStack` (before call`Illuminate\Routing\Route::run`).

The router logic of execution will be like:
- find route
- run middlewares
- resolve route bindings
- run route

Now the second and third paragraph are swapped.

If you will approve, I can create a pull request for this.

Real world example is the next:

We have  a tracker system and in the user personal cabinet he can create tracker link, invite other user by link, see statistics etc.
In the user personal cabinet i want to show only those items, which were created only by current user or for current user. But we don't want be worried that all queries are have a part to check our current user. So we want this would be automatically.
 
In theory it would be work the next way:
We have a global scope, which would add condition to the interested models and this scope will apply by middleware and middleware would be added to the route group(s) which are interested for us. 

Global scope class example

```php
class CurrentUserGlobalScope implements \Illuminate\Database\Eloquent\Scope
{
    /**
     * @var \Illuminate\Contracts\Auth\Guard
     */
    private $guard;

    /**
     * CurrentUserGlobalScope constructor.
     * @param \Illuminate\Contracts\Auth\Guard $guard
     */
    public function __construct(\Illuminate\Contracts\Auth\Guard $guard)
    {
        $this->guard = $guard;
    }

    /**
     * Apply the scope to a given Eloquent query builder.
     *
     * @param  \Illuminate\Database\Eloquent\Builder $builder
     * @param  \Illuminate\Database\Eloquent\Model $model
     * @return void
     */
    public function apply(\Illuminate\Database\Eloquent\Builder $builder, \Illuminate\Database\Eloquent\Model $model)
    {
        if ($model instanceof HasOwner) {
            $builder->where($model->getOwnerKey(), $this->getCurrentUserId());
        }
    }

    /**
     * Get current user id.
     */
    private function getCurrentUserId()
    {
        return $this->guard->id();
    }
}
```

Middleware class example

```php
class PersonalCabinetMiddleware
{
    /**
     * @var \Illuminate\Contracts\Auth\Guard
     */
    private $guard;

    /**
     * PersonalCabinetMiddleware constructor.
     * @param \Illuminate\Contracts\Auth\Guard $guard
     */
    public function __construct(\Illuminate\Contracts\Auth\Guard $guard)
    {
        $this->guard = $guard;
    }

    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        $this->addGlobalScopes();

        return $next($request);
    }

    /**
     * Add global scopes for needed models.
     */
    private function addGlobalScopes()
    {
        $scope = new CurrentUserGlobalScope($tthis->guard);

        \App\Link::addGlobalScope($scope);
        \App\Statistic::addGlobalScope($scope);
        \App\Referral::addGlobalScope($scope);
        
        // ...
    }
}
```

Link repository class example

```php
class LinkRepository
{
    /**
     * Find link by given id.
     * 
     * @param $id
     * @return mixed
     */
    public function find($id)
    {
        return App\Link::find($id);
    }
}

```

Of course we registered our middleware in the kernel

```php
'cabinet' => \App\Http\Middleware\PersonalCabinetMiddleware::class,
```

Now our `routes.php` looks like:
```php
// Add auth and cabinet middleware to all /cabinet/* requests.
$router->group(['prefix' => 'cabinet', 'middleware' => ['auth', 'cabinet']], function(Router $router) {
   
    $router->get('edit/{userLink}', 'LinksController@edit');

    // ...
});

```

And now it works great in the controllers. For Example:

```php
class LinksController
{
    /**
     * Edit user personal tracker link.
     * 
     * @param $userLink
     * @param LinkRepository $repository
     */
    public function edit($userLink, LinkRepository $repository)
    {
        $link = $repository->find($userLink); // query for finding link would be like: "select * from links where owner_id = 765 and id = 1881 limit 1"
        
        // ...
    }
}
```

But! We know a great tool, like `route bindings` and we want to receive an instance of `App\Link` into controller. 

so if we add route binding

```php
$router->bind('userLink', function($userLink) {

   return app(LinkRepository::class)->find($userLink);
});
```

Whoops, our binding doesn't work as expected. Binding was executed before the middleware, so can't add condition `where owner_id = CURRENT_USER_ID` to the query.

**Comment by GrahamCampbell** [comment]
We already changed this in L5.3. Bindings now actually are implemented using a middleware, so can be executed whenever.
