### ISSUE TITLE
[5.2] No way to do "Complex Conditional Validation" with "Form Request Validation"

### ISSUE THREAD

**Issue by jason-chang** [laravel/framework#14337]
No way to do "Complex Conditional Validation" with "Form Request Validation".

Is there a plan to add this trait ?

Thanks!

**Comment by jason-chang** [comment]
By read the source code I found a way to do this, Add a validator like below.

But i want to know that if this is recommend ?

Am i do right?

Sorry ! My english is so bad.

~~~php
public function validator($factory)
    {
        $validator = $factory->make(
            $this->all(), $this->container->call([$this, 'rules']), $this->messages(), $this->attributes()
        );


        $validator->sometimes('parent_id', 'exists:permissions,id', function($input) {
            return intval($input->parent_id) > 0;
        });

        return $validator;
    }
~~~

**Comment by fahmilatib** [comment]
I'm doing like this also.

**Comment by themsaid** [comment]
Closing since it doesn't look like a bug in the framework :)
