### ISSUE TITLE
not disable Header set-cookie in Laravel 5.2.39

### ISSUE THREAD

**Issue by sajjad-golchin** [laravel/framework#14334]
i use laravel 5.2 and when that not use "web middleware" the header for resetful api
set-cookie and work truly
and recently use laravel 5.2.39 can not disable Header set-cookie for restful 

thanks

**Comment by GrahamCampbell** [comment]
Upgrading from what version please?

**Comment by sajjadgolchin** [comment]
from 5.2.31 to 5.2.39
thanks for ask @GrahamCampbell
