### ISSUE TITLE
attach() method generates wrong sql

### ISSUE THREAD

**Issue by plakhin** [laravel/framework#14353]
Laravel Framework version 5.2.39
As written in docs:

> For convenience, attach and detach also accept arrays of IDs as input:

But when trying:
```php
$post = Post::find(1);
$post->categories()->attach([1,2,3]);
```
actually only first category from array is attached.

I've tried to execute SQL query generated by attach() method: 
```sql
INSERT into `category_post` (`category_id`, `post_id`) values ('1,2,3', '1');
```
but it inserts only one row and shows this warning:

> Data truncated for column 'category_id' at row 1

I think that SQL in this case should be:
```sql
INSERT into `category_post` (`category_id`, `post_id`) values ('1', '1'), ('2', '1'), ('3', '1');`
```

P.S. Not sure, but feel like several days ago everything was working fine.

**Comment by henriquebremenkanp** [comment]
I just checked the same version as you and it works fine here.
Maybe something inside your `categories` function on your `Post` model?

**Comment by plakhin** [comment]
@henriquebremenkanp 
Thanks for response. My `categories` function is
```php
public function categories()
    {
        return $this->belongsToMany(Category::class);
    }
```
Can you please check what SQL query is generated by attach() method?
Can you please check if your MySQL executes this query:
```sql
INSERT into `category_post` (`category_id`, `post_id`) values ('1,2,3', '1');
````?

**Comment by themsaid** [comment]
Here's the generated query form a live project using `5.2.39`.

```sql
insert into `product_tags` (`product_id`, `tag_id`) values (?, ?), (?, ?), (?, ?);
```

As a result of

```php
Product::find(1)->tags()->attach([1,2,3]);
```

**Comment by plakhin** [comment]
@themsaid seems like your query is right, how did you dump it? I need to try the same method to be sure, usually I use Clockwork.

**Comment by henriquebremenkanp** [comment]
https://laravel.com/docs/5.2/database#listening-for-query-events
Here's one way to dump the queries.

Have you tried to delete the vendor folder and do composer install again? Maybe you have some edited files by mistake in there.

**Comment by plakhin** [comment]
@henriquebremenkanp 
I'm sure I didn't edit any files in vendor folder, but also tried to remove it and do composer install again. Didn't help

I've tried to dump query and bindings via DB::listen() method and here is var_dumps:
```
string(70) "insert into `category_post` (`category_id`, `post_id`) values (?, ?)"
array(2) {
  [0]=>
  string(3) "1,2"
  [1]=>
  int(1)
}
```

I'm wondering why I got this wrong query...

**Comment by themsaid** [comment]
@plakhin I did dump the query generated from inside the BelongsToMany class.

Check the packages you're using, maybe one of them is overwriting the core.

**Comment by plakhin** [comment]
I thing I found a problem in bindings. First binding should be an array but not a string, I will double check input parameters.
Thanks everybody.
