### ISSUE TITLE
Form request image validation differences between 5.1 and 5.2

### ISSUE THREAD

**Issue by stevenmusumeche** [laravel/framework#14351]
I'm in the process of upgrading an app from Laravel 5.1 to 5.2. The application is an API and one of the endpoints accepts an image upload named 'avatar'. In Laravel 5.1, the following validation rule works:

    public function rules()
    {
        return [
            'avatar' => 'required|image'
        ];
    }
However, in 5.2, I get the error 'Avatar must be an image'. When dumping $request->avatar, I can see that it is an instance of `Illuminate\Http\UploadedFile` as expected.

**Comment by GrahamCampbell** [comment]
Feel free to ask on the forums, and I'm sure someone can help you there.

**Comment by stevenmusumeche** [comment]
@GrahamCampbell since this is an undocumented BC break between 5.1 and 5.2, it is a legitimate issue to post here as well.

**Comment by stevenmusumeche** [comment]
For anyone else that has this problem, the issue was not in the validator at all. There is a bug in Laravel 5.2 from converting Symfony UploadedFile objects with the "test" attribute as true to Laravel's similar UploadedFile object. In my tests, I was uploading Symfony UploadedFile file objects with "test" = true. By changing these to Illuminate\Http\UploadedFile it works.

**Comment by GrahamCampbell** [comment]
Very odd. Ping @taylorotwell.

**Comment by stevenmusumeche** [comment]
To be clear, our tests were posting Symfony UploadedFile objects. I don't think actual controllers would have this bug.

**Comment by GrahamCampbell** [comment]
Oh, right, yeh. That's not a bug. Does look like we forgot to document this though. I think it was actually a change made in a later 5.2.x patch release to fix a bug caused by some changes in symfony.

**Comment by GrahamCampbell** [comment]
A PR to our docs would be very appreciated. :)

**Comment by stevenmusumeche** [comment]
Gladly. What's the best place for that?

**Comment by philbates35** [comment]
Send a PR here: https://github.com/laravel/docs
