### ISSUE TITLE
Paginate, the backupFieldsForCount method of the parameters in the select all cleared, leading to the query error, which is why? 

### ISSUE THREAD

**Issue by yangw1990** [laravel/framework#14355]
protected function backupFieldsForCount()
    {
        foreach (['orders', 'limit', 'offset', 'columns'] as $field) {
            $this->backups[$field] = $this->{$field};

            $this->{$field} = null;
        }

        foreach (['order', 'select'] as $key) {
            $this->bindingBackups[$key] = $this->bindings[$key];

            $this->bindings[$key] = [];
        }
    }

**Comment by GrahamCampbell** [comment]
Closing due to no community interest.
