### ISSUE TITLE
Modifying a DB table with JSON(B) column also not supported?

### ISSUE THREAD

**Issue by mzur** [laravel/framework#14356]
The documentation [says](https://laravel.com/docs/5.2/migrations#modifying-columns) that "Modifying any column in a table that also has a column of type `enum` is not currently supported."

I've now discovered an issue that makes me suspect this statement may also be true for tables with `json` or `jsonb` columns. Steps to reproduce:

1. Set up a new project: `composer create-project --prefer-dist laravel/laravel blog && cd blog`

2. Install Homestead: `composer require laravel/homestead --dev && php vendor/bin/homestead make`

3. Install DBAL: `composer require doctrine/dbal --dev`

3. Run Vagrant box: `vagrant up` then `vagrant ssh` and `cd blog`

4. Create a new migration: `php artisan make:migration test_json_change_table` with the content:
    ```php
    <?php

    use Illuminate\Database\Schema\Blueprint;
    use Illuminate\Database\Migrations\Migration;

    class TestJsonChangeTable extends Migration
    {
        public function up()
        {
            // create a table with a json column
            Schema::create('test', function ($table) {
                $table->json('json')->nullable();
                $table->string('string')->nullable();
            });
            // try to change another column of the same table
            Schema::table('test', function ($table) {
                $table->string('string')->nullable(false)->change();
            });
        }

        public function down()
        {
            Schema::drop('test');
        }
    }
    ```

5. Run the migration: `php artisan migrate`

This produces the error
```
[Doctrine\DBAL\DBALException]                                                           
Unknown database type json requested, Doctrine\DBAL\Platforms\PostgreSqlPlatform may not support it.
```
or
```
[Doctrine\DBAL\DBALException]                                                           
Unknown database type json requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it.
```
although the Vagrant box runs PostgreSQL version 9.4.7 and MySQL version 5.7.12 which both support `json` and `jsonb`.

I know this is not Laravel's fault but if this is a real bug we should add it to the note in the documentation.

**Comment by mzur** [comment]
Will be continued in #14363.

**Comment by MirilTerolli** [comment]
I have tried the following for POSTGRESS DB and is not working : 
```$table->jsonb('content');```
Any suggestion?

**Comment by mfn** [comment]
Works for me, can you be more specific? Laravel version, specific error/problem you have, etc.?

**Comment by MirilTerolli** [comment]
@mfn , That was happening because of my .env file was not properly configured. I was pointing into another .env but I was not aware of that :D 
Works just fine now! 👍
