### ISSUE TITLE
Database Query Builder support for whereTime

### ISSUE THREAD

**Issue by johnpaulmedina** [laravel/framework#14364]
I noticed that the whereDate, whereYear, whereMonth, whereDay all exist in the builder but there is no support for whereTime to filter columns like timestamps down between a certain time range.

Was this intentionally left out for support on other DB types?

**Comment by srmklive** [comment]
I don't think there is any need for this method. You can simply filter between time range by combining where clauses.

    $query = Order::where('date', '>=', '2016-07-25 00:00:01')
        ->where('date', '<=', '2016-07-25 23:59:59');

You can use Carbon to set the specific time intervals. Also `whereDate, whereYear, whereMonth, whereDay` methods automatically translate the date instances for applying specific filters.

It could be a nice thing to have though.

**Comment by johnpaulmedina** [comment]
Essentially what you are saying is to get all orders where the begin time is `2016-07-25 00:00:01` and BETWEEN `2016-07-25 23:59:59`.

That will get you all the data between, you are correct. What I am proposing is to add the whereTime method so that essentially it would be a query like so

```
$query = Order::whereDate('created_at', '>=', '2016-07-01')
    ->whereDate('created_at', '<=', '2016-07-25')
    ->whereTime('created_at', '>=', '13:00:00')
    ->whereTime('created_at', '<=', '14:00:00');
```

The difference between what you are saying and what I am saying is that I am asking for orders between date A and date B but I am asking for orders that were created between a certain time range as well. These are two different logical queries. In an example where the date is the same sure it is not needed but in an example like I put the date ranges are much greater but allow you to get all orders between that time. 

Does this make sense? The functionality is already built in laravel essentially. They are doing it on whereDate, whereYear... etc... I modified my MySQL Grammar.php and added the function like so:

```
    protected function whereTime(BaseBuilder $query, $where)
    {
        return $this->dateBasedWhere('time', $query, $where);
    }
```

It is leveraging the same logic which already exist in the framework and using the Mysql TIME() to adjust the query. There is no major changes required for this.
