### ISSUE TITLE
Call \Illuminate\\Foundation\\ComposerScripts::postInstall from cli?

### ISSUE THREAD

**Issue by lukasoppermann** [laravel/framework#14365]
Hey,

so I am deploying using capistrano and  my host does not have `php` available via the cli but I need to use a special `php-cli` command.

To get around composer failing when called via capistrano (which does not use the default bash with my alias php=php-cli) I just call composer install in the capistrano with --no-scripts and have capistrano call `php-cli artisan optimize` afterwards.

However I can not figure out how I can call `\Illuminate\\Foundation\\ComposerScripts::postInstall` from the commandline or what I can replace it with. Does it just do a `composer clear-compiled` call? Or is there something special? Thanks for your help.

**Comment by GrahamCampbell** [comment]
Feel free to ask on the forums.
