### ISSUE TITLE
[5.2] Multiple Sessions per user

### ISSUE THREAD

**Issue by Alig96** [laravel/framework#14376]
https://laracasts.com/discuss/channels/laravel/sessions-creating-multiple-sessions-for-the-same-user?page=1#reply-177623

I've been stuck with this problem for about a week now, I have nowhere else to turn to. This issue causes:

- Random logouts during user actions (i.e when uploading files, causing the request to become unauthorised randomly which throws an error because in the method it gets the current user, expecting them to be logged in)
- The CSRF token to not match because the session token doesn't match what the user has.

I haven't touched session variables or done anything with them (that I am aware of, maybe an installed package is doing something?), so I don't know if this something I'm doing or if there is an issue with the framework. I imagine its something I've done, since this is a fairly big issue I would imagine someone else would've encountered it if it was the framework.

Here are the packages:
```
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "laracasts/flash": "~2.0",
        "silber/bouncer": "^0.1.7",
        "vinkla/hashids": "^2.3",
        "davejamesmiller/laravel-breadcrumbs": "^3.0",
        "mews/purifier": "^2.0"
    },
```

I'm exhausted trying to to debug this issue, can anyone point me in the right direction or should I just trash the project and rebuild on 5.1 LTS?

**Comment by johnpaulmedina** [comment]
Does this happen on specific controllers? I am on the current version and I have no issues like this. Maybe a server session config? Are you on a local or production environment? 

If you are using an AuthController or some sort for protected pages using the __construct why don't you Log::debug($sessionData, $request) so you can see the exact session state and request at the time of each page load, maybe find a pattern?

**Comment by Alig96** [comment]
All i can really say is that it is random, there's no pattern. In a multi upload it can go like 1-5 uploads then logout (or create a new session) then cause all subsequent uploads to fail, then when you leave the page you can see you've been logged out and then the cycle continues.

Then when navigating through the pages, it'll occasionally make a new session while leaving the old one in the db. Some actions make it happen then if you try to repeat it, it doesn't happen. 

I added put my server session config on the other thread. Local environment.

I'll try what you've suggested. Thanks for responding

**Comment by johnpaulmedina** [comment]
If its not anything that is private would you mind sharing a repo of the exact setup? I can take a look to see if I see something myself but for the most part it sounds to me like something isn't persisting. Have you tried another browser? It could also be that something is causing the session to check as invalid although you are saying nothing in DB but the one session. Maybe your DB connection is failing or taking too long. Try switching to file based session for a second and see if the same issues happen.

**Comment by Alig96** [comment]
Unfortunately it is a private project with some sensitive stuff, so I can't post it here, is there anything in particular you want to see? However if it is the only way to solve this, is there an email address I can send you?
I am using Chrome, but I guess I can try edge. The issue was happening on the file based setup, its why I switched in the first place. It seemed liked it worked, then after some more testing it started happening again.

**Comment by johnpaulmedina** [comment]
medina.jpaul@ g m a I l . c o m

**Comment by Alig96** [comment]
Sent. Thanks for taking a look.

**Comment by johnpaulmedina** [comment]
Got it. Will try it out a bit later tonight and get back to you.

**Comment by johnpaulmedina** [comment]
Question, do you have that setup on a Git repo? If so rather than the zip can you share with my username? That way if I make changes you can track them.

**Comment by Alig96** [comment]
I have it on local gitlab server so, no unfortunately, otherwise I would've sent you.

**Comment by masterdeduction** [comment]
Usually when you login when the user session is active, it will fail, and errors like token mismatch, solution is to logout first or clear the session.

**Comment by TheShiftExchange** [comment]
Have you run `php artisan config:cache`? That might fix it.

**Comment by Alig96** [comment]
I decided to just scrap it and re-write the project, the issue hasn't arisen again yet.
