### ISSUE TITLE
Wrong @param type for build method?

### ISSUE THREAD

**Issue by belohlavek** [laravel/framework#14379]
See [Container.php line 719 (master)](https://github.com/laravel/framework/blob/774aee9c29ba624812b54b934df42b8d9fa97943/src/Illuminate/Container/Container.php#L719)

It specifies that the method's `$concrete` variable is of type **string**, but if you gettype() you get an **object**.
Also, `$concrete` can be an instance of  `Closure`.

**Comment by jlem** [comment]
Yes, that type should be changed to `mixed` at least, or preferably a pipe delimited list of the argument types that function accepts.

Officially, `ReflectionClass` constructor declares its argument as `mixed`:

http://php.net/manual/en/reflectionclass.construct.php

But does specify `string` or `object` as types. 

IMO it's more valuable to IDE users to see explicit types they are allowed to pass in, so I think

`string|object|closure` would be the most useful to IDE users.

**Comment by GrahamCampbell** [comment]
> string|object|closure would be the most useful to IDE users.

Thanks guys. A PR would be much appreciated whenever you have a moment.
