### ISSUE TITLE
Eloquent - Ability to only have created_at or updated_at

### ISSUE THREAD

**Issue by gabber12** [laravel/framework#14383]
Current implementation only allows either both timestamps created_at and updated_at or to totally disable timestamps. 
Would a feature for allowing only one of them be useful?

The motivation of having this is, there are a lot of use-case where data is immutable so updated_at field is redundant.

**Comment by morloderex** [comment]
You could to this:
1. set timestamps to false
2. set the date property  to ['updated_at']

But then you have to maintain the field on your own. But that shouldn't be an issue, you'll just have to use carbon something like this

Model::save(['updated_at' => Carbon::now()]). 

Or you could use a model event for it there is a lot of choices for doing stuff like this.

**Comment by gabber12** [comment]
Yep , that is what i use currently. Do you think it would be of some worth if the framework handled it out of the box, instead of changing migration and model.

**Comment by srmklive** [comment]
I don't see it really as an issue. I think its better to have these columns available.

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. Feel free to take up proposals on the internals repo as per our contribution guidelines. I think this might have already been discussed though. Feel free to look around for existing issues here.
