### ISSUE TITLE
[5.2] withoutGlobalScope - does it actually work?

### ISSUE THREAD

**Issue by huglester** [laravel/framework#14380]
Hello,

so I have general model - Invoice - which is used by customers,
and InvoiceAdmin - which is used by administrator.

Basicly InvoiceAdmin only extends the Invoice class and disables the global scope, which does not seem to work, example:

```php
use App\Scopes\UserScope;
class Invoice extends Entity
{

    protected $table = 'invoices';
    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope(new UserScope);
    }
}
# -------------------------
use App\Scopes\UserScope;
class InvoiceAdmin extends Invoice
{

    protected static function boot()
    {
        parent::boot();

        static::withoutGlobalScope(new UserScope);
    }
}
```

The problem is, whenever I call the withoutGlobalScope, in the InvoiceAdmin, the SCOPE is still applied, and I can't access all the invoices.

Is the usage syntax correct here? Or maybe I have miss-configured something? 

If I call it like this: InvoiceAdmin::withoutGlobalScope(new UserScope)->get() - then it WORKS..

I have upgraded to laster Laravel 5.2, but also no luck in here.

Thank you

**Comment by ameliaikeda** [comment]
`withoutGlobalScope` creates a new builder instance without that global scope and returns it.

It doesn't remove an active global scope.

**Comment by huglester** [comment]
I am not sure I understand you?

So is there anyway around it? what is then the purpose of removing globalScope if it does not remove it?

I also tries
```php
$items = Invoice::withoutGlobalScope(new UserScope)->getModel()->get();
```
but get 0 results.

**Comment by ameliaikeda** [comment]
You cannot call `static::withoutGlobalScope` in the boot method and have it remove a global scope; it affects the builder instance, not the `InvoiceAdmin` model.

You can possibly do `unset(static::$globalScopes[static::class][UserScope::class])` instead.

**Comment by huglester** [comment]
Thanks @ameliaikeda , this one sollution works:
```php
unset(static::$globalScopes[static::class][UserScope::class]);
```

This one feels hacky and I have a feeling that it can blow up any day! :)

Maybe there are more valid use cases which won't lead to this mess?

**Comment by crynobone** [comment]
Having a `BaseInvoice` and have both `UserInvoice` and `AdminInvoice` seem better to me. It odd to add a global scope and then completely remove it.

**Comment by huglester** [comment]
By default (for security reasons) I want to apply it. So this is why I choose to 'apply' it by default.

while 3 models seems a more correct way. But having so many of them, seems too verbose, no? But probably it would be the way to go..

Thank for ideas

**Comment by acasar** [comment]
@huglester ``withoutGlobalScope`` doesn't work the way you are trying to use it. It's just a query builder helper and should be used as such:

```php
Invoice::where('foo', 'bar')->withoutGlobalScope(User::class)->get()
```

What you are trying to do is actually remove the scope on every query which is a bit odd, but could still be done this way:

```php
class Invoice extends Entity
{
    protected static $applyUserScope = true;

    public static function boot()
    {
        parent::boot();

        if(static::$applyUserScope) {
            static::addGlobalScope(new UserScope);
        }
    }
}
# -------------------------
class InvoiceAdmin extends Invoice
{
    protected static $applyUserScope = false;
}
```

**Comment by huglester** [comment]
Thank everybody. Somehow I did not thing about this, @acasar 
Thank for all the comments. 

Now I  get this :)

Have a great time using great framework!
