### ISSUE TITLE
PasswordBroker::validateNewPassword() "hardcodes" password confirmation

### ISSUE THREAD

**Issue by legshooter** [laravel/framework#14382]
Hey,

So I have a pretty straightforward requirement - to get rid of the whole password confirmation when resetting a password (so 2015).

Seems like all the recent improvements in the `ResetsPasswords` trait haven't addressed this, because even if I remove the `confirmed` validation by overriding `getResetValidationRules()` in my `PasswordController` and remove the `password_confirmation` field by overriding `getResetCredentials()`, it will still fail.

This is due to the fact that the some confirmation stuff is "hardcoded" in `PasswordBroker`:

```php
public function validateNewPassword(array $credentials)
{
    list($password, $confirm) = [
        $credentials['password'],
        $credentials['password_confirmation'],
    ];

    if (isset($this->passwordValidator)) {
        return call_user_func(
            $this->passwordValidator, $credentials) && $password === $confirm;
    }

    return $this->validatePasswordWithDefaults($credentials);
}
```
This seems to have started with the historic https://github.com/laravel/framework/issues/2927.

My way of overriding this in the `PasswordController` was always faking the confirmation:
```php
public function resetWithoutConfirmation(Request $request)
{
    $request->merge(['password_confirmation' => $request->input('password')]);

    return $this->reset($request);
}
```
But this feels kinda hacky. 

Am I missing something or is this a real pain?

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. Feel free to discuss this in the correct place as per our contribution guidelines.

**Comment by legshooter** [comment]
I *guess* you mean internals, although to me this is really borderline and should be discussed here no less than anywhere else.

Anyway, would be nice if you'd be specific about where this should go, instead of implying.

**Comment by GrahamCampbell** [comment]
I do this to make sure that everyone reads the guide.

**Comment by legshooter** [comment]
Well you imply I didn't read it, ignoring the possibility I have, and that it just might be that we are interpreting it differently. Which is exactly the situation.

It wouldn't hurt taking this possibility into account even if you're that keen on education. You could go with something along the lines of: "Thanks for getting in touch. Feel free to discuss this in the [example place](http://www.example.com) as per our [contribution guidelines](https://laravel.com/docs/5.2/contributions)."
