### ISSUE TITLE
[5.2.40] Pagination broken on PHP7.0.8 (Division by 0)

### ISSUE THREAD

**Issue by alexhouse** [laravel/framework#14387]
In the process of updating our composer libraries it seems Laravel 5.2.40 pagination breaks in at least PHP7.0.8.

It appears PHP7 can't handle assigning variables whilst assigning a variable. [Problematic code](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/Builder.php#L489-L492):

        $results = $total ? $this->forPage(
            $page = $page ?: Paginator::resolveCurrentPage($pageName),
            $perPage = $perPage ?: $this->model->getPerPage()
        )->get($columns) : [];

Essentially, `$page` and `$perPage` end up as `null` and `0`, causing `LengthAwarePaginator` to backflip over a division by 0.

This can be demonstrated through Tinker:

```
>>> $page = null;
>>> $perPage = null;
>>> $total = null;
>>> function noop($page, $perPage) {}
>>> $results = $total ? noop($page = $page ?: 1, $perPage = $perPage ?: 20) : [];
=> []
>>> dd($page, $perPage);
null
null
```

I imagine this is more of a PHP7 problem but Laravel could, in the meantime, revert to the [previous implementation](https://github.com/laravel/framework/blob/v5.2.39/src/Illuminate/Database/Eloquent/Builder.php#L483-L498) of `Builder::paginate()` which doesn't have this problem in order to resolve this issue.

**Comment by xuyu** [comment]
Same bug for me.
Use simplePaginate instead and wait it to be fixed.

**Comment by ameliaikeda** [comment]
This was broken by #14188

**Comment by themsaid** [comment]
Why does your `perPage = 0`?

If you call `->paginat(10)`, $perPage will be 10.

if you call `->paginate()`, $perPage will be equal to the model's `perPage` value.

**Comment by alexhouse** [comment]
It shouldn't equal 0. It equals 20. Adding `var_dumps` or `dd`s before the `$results` declaration shows that it *should* equal 20, but the assignment to the `$perPage` variable within the `$results` ternary turns it into 0.

Essentially the `$perPage` and `$page` assignments need to be done before they're then used in the function call.

We call paginate with no arguments.

**Comment by themsaid** [comment]
Fix submitted https://github.com/laravel/framework/pull/14389

**Comment by mnabialek** [comment]
@alexhouse Sorry for that, I've introduced it when adding optimization for pagination, now fix by @themsaid  is already included in latest release
