### ISSUE TITLE
$errors->has() returns true since framework upgrade to 5.2.40

### ISSUE THREAD

**Issue by nickbr5** [laravel/framework#14395]
Hi All,

Since i upgraded my L5 version from 5.2.35 to 5.2.40, the function to check if i have errors in my view doesn't work anymore. $errors->has() now returns true instead of false, if i change this to $errors->any() it returns false.

```
@if ($errors->has())
    <div class='bg-danger alert'>
    @foreach ($errors->all() as $error)
        <p>{{ $error }}</p>
    @endforeach
    </div>
 @endif 

```

Any ideas?

thx

**Comment by MatthewLilley** [comment]
It seems as though you aren't actually checking for a particular error. For example -  $errors->has('name')

**Comment by nickbr5** [comment]
https://laracasts.com/discuss/channels/laravel/errors-has-returns-true-since-framework-upgrade
