### ISSUE TITLE
Inconsistent tagging and out of date CHANGELOG

### ISSUE THREAD

**Issue by leewillis77** [laravel/framework#14406]
My local repo has notified me that laravel framework can be updated from 5.2.39 to 5.2.41. In looking into this upgrade I came across two issues. 

1. The CHANGELOG.md doesn't contain any information about what changes are included in v5.2.40, or 5.2.41 - it only goes up to v5.2.39 making it difficult to review the criticality of the update, or any potential issues upgrading. 

2. The release is tagged as 5.2.41, whereas the convention for other releases is v5.2.41 [Note the additional "v"]. Without this it's easy to miss 5.2.41 in a `git tag -l`. Minor nag, but maybe worth retagging for clarity?

**Comment by GrahamCampbell** [comment]
The changelog is community maintained, and i'll be updated in due course. It's not a prerequisit for us to have a changelog whern we do a release.

Thanks for the heads up about the tag name. Ping @taylorotwell.

**Comment by fernandobandeira** [comment]
Changelog added on PR #14414

**Comment by leewillis77** [comment]
Hi @GrahamCampbell - thanks for the quick response!

From a framework-user point of view it would be great it if the project would reconsider having a change log be a prerequisite for formalising a release.

I understand that the person getting the code ready for release may be different to the people readying documentation such as change logs. However, I don't see why that means that the two can't be coordinated to come together at an appropriate point in time. 

At the minute, not only is the real-time situation confusing by not having documentation ready when code is available, there are also historical problems whereby tagged releases don't contain the information either, even when it actually is available (E.g. viewing v5.2.39 as a tag now still doesn't have the info available, even though it's available on the main 5.2 branch). 

What I'm suggesting is that code release is delayed until *everything* (not just code) is ready. This happens in many large OS projects already for things like translations, documentation, announcement blog posts etc. and Laravel is the only project I've seen where the code is released before the documentation about the release is available. It'd be great to see a move towards that in future releases.

**Comment by leewillis77** [comment]
@fernandobandeira Thanks for the link to the changelog!
