### ISSUE TITLE
[Test][Bug] Authentication services for consecutive requests are not working.

### ISSUE THREAD

**Issue by CurosMJ** [laravel/framework#14402]
When I try to make consecutive requests (in a TestCase), like this : 
```php
public function testMeEndpoint()
{
    $this->post('/authenticate', ['email' => 'email@email.com', 'pass' => '12345']);
    $token = $this->lastResponse()['data']['access_token'];

    $this->get('/users/me', ['Authorization' => "Bearer $token"])
            ->seeStatusCode(200)
            ->see('first_name')
            ->see('created_at');
}
```

The `GET` call to `/users/me` would fail with an 403 (which implies the token was not understood by the application).

If I refresh the application between the calls(`$this->refreshApplication()`), this will work fine. Like this : 

```php
public function testMeEndpoint()
{
    $this->post('/authenticate', ['email' => 'email@email.com', 'pass' => '12345']);
    $token = $this->lastResponse()['data']['access_token'];

    $this->refreshApplication();

    $this->get('/users/me', ['Authorization' => "Bearer $token"])
            ->seeStatusCode(200)
            ->see('first_name')
            ->see('created_at');
}
```

**What I think is going wrong :**

The Application instance is reused for requests, by default. So are the services that are binded inside the Container, including the  _Guard_. 

The Guard that is used for the second `GET` request is the one that was created when the first `POST` was sent. This is where it all goes wrong. It should have created a new instance of Guard, instead of just using the last one.

**Possible solutions :**

 - Refresh / Recreate the application after/before each call.
 - Force the application to generate a new Guard for each call.

This is just about the Guard service, but other services might also be failing in a similar manner. 

From my POV, testing framework should mimic the real-world situation, and re-create the whole application for each request.

**Comment by masterdeduction** [comment]
csrf_token()

**Comment by sisve** [comment]
Do you have a custom tearDown() implementation that forgot to call parent::tearDown()? TestCase::tearDown() does throw away the existing application instance. https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Testing/TestCase.php#L121-L129

**Comment by CurosMJ** [comment]
@masterdeduction I've disabled CSRF middlewares.

@sisve nope, its all as-is.

**Comment by srmklive** [comment]
Why don't you create the application instance for each request for you test case? You can look at the framework test cases if you want on this [link](https://github.com/laravel/framework/blob/5.2/tests/Http/).

**Comment by CurosMJ** [comment]
@srmklive I do that, but this is an unexpected behavior, that's why I am reporting it.

**Comment by GrahamCampbell** [comment]
Thank you for the report, but I don't believe this to be a bug, rather, just a subtlety of how the framework works. Feel free to ask on the forums if you want to discuss this further or get specific advice for your application.

**Comment by GrahamCampbell** [comment]
If you do find that there's something you'd quite like to change in the framework code, we're definitely open to PRs, and you can discuss implementation changes on internals in slack.
