### ISSUE TITLE
Chaining Eloquent relations in view problem - Laravel 5.2

### ISSUE THREAD

**Issue by chilio** [laravel/framework#14416]
I’m little bit struggling to get things to work.
Is there a chance that in l5.2 not all Eloquent models use custom defined $primaryKey respectively?
So far I have experienced problems with some of the plugins, that is why I am asking?
I’m trying to go 3 levels deep to Eloquent relations from view.
No Exceptions, no problems but I get false data (probably because of my db design – low number ids) – currently it is somehow hard for me to investigate further – toSql() produces nothing unusual.
The problem potentially lies in relationships – I Use custom columns since I’m trying to rebuild from legacy app and using custom $primaryKey as stated above.
Everything seems to work great when I’m on root level of things -> but when I try to chain Eloquent relationships, I get non real data responses like count 1 instead of 242 etc. Not able to access DB variables properly.
Anybody experiencing similar problems ?

**Comment by fernandobandeira** [comment]
Please share a small example so we can see which kind of relations you are trying to do and also the exact laravel version, i currently have many projects on production in the latest laravel 5.2.41, and some of them goes even beyond 3 level's deep and so far i had no issues. (even when using tables with custom id's).

**Comment by srmklive** [comment]
Kindly share a code example.

**Comment by chilio** [comment]
Sorry for bothering you and thank you for being so helpful.
I have find out what was the problem.
Due to my custom $primaryKey I had problems in my models relation declarations.
I thought that custom defined primaryKey is automatically injected into relations I was trying to set up and I didn't understood the concept entirely.
Below is my example - maybe it can help someone else - documentation on using custom keys with Eloquent is not so easy to find.
In my model 'Location' I defined relation:

> public function Courts() {
> 		return $this->hasMany('App\Models\Court','id_location','id_court');
> 	}

which was **wrong**, instead I should write:

> public function Courts() {
> 		return $this->hasMany('App\Models\Court','id_location','id_location');
> 	}
My Location table has primaryKey -> id_location, Court primaryKey -> id_court and relation column in Court table is id_location. 
So definitely $primaryKey is indeed properly injected into sql statments, I have no more problems with it at all and can chain relations without any problems.
Thanks again for your time.
