### ISSUE TITLE
$errors->has() always returning true

### ISSUE THREAD

**Issue by TechKat** [laravel/framework#14424]
Since Laravel 5.2.41, the `$errors->has()` method for MessageBag appears to always return true, but `$errors->first()` has nothing in it.

**Comment by GrahamCampbell** [comment]
This bug will be fixed in v5.2.42. Sorry about that!

**Comment by TechKat** [comment]
Using `$errors->any()` seems to work, however I was more comfortable using `$errors->has()`

**Comment by GrahamCampbell** [comment]
As I said, we've already fixed this bug, and i'll be fixed in v5.2.42.

**Comment by TechKat** [comment]
@GrahamCampbell I am glad this hasn't gone unnoticed, and just wanted to make sure I wasn't the only one. :) Will keep an eye out for the next update.
