### ISSUE TITLE
Laravel testing with group prefix problem

### ISSUE THREAD

**Issue by maphongba008** [laravel/framework#14422]
I have a group for api:
```
Route::group(array('prefix' => 'api'), function () {

    Route::get('abc', function () {
        return 'abc';
    });
  );
```
But, when testing use `$this->call('GET', '/api/abc') `or `$this->call('GET', 'path_to_abc')`, I always get 404 error, although I've printed the url and I can visit that link in browser

**Comment by GrahamCampbell** [comment]
Did you remember to run `artisan route:cache`?

**Comment by maphongba008** [comment]
Oh, I found the answer, cause I check the url request
```
if (Request::is('api/*')) {
         require __DIR__ . '/api_routes.php';
}
```
I remove the if condition and it works. Thanks :D

**Comment by GrahamCampbell** [comment]
You should never conditionally requiter routes.
