### ISSUE TITLE
Model Events Not Fired on Delete via Database Builder

### ISSUE THREAD

**Issue by doctorallen** [laravel/framework#14427]
on Laravel 5.2 (didn't test on 5.3)
When deleting an model, you can do it two different ways:
# Via the model class
```php
Model::find($id)->delete();
```
# or Via the query builder
```php
Model::where('id', $id)->delete();
```

In the second scenario, where the delete is actually called on the query builder, and not the model, the model is correctly deleted (even if you are using soft deletes), however the **::deleting** model event is never invoked.

The weirdest part about this whole thing is that if you have soft deletes defined, the query builder correctly soft deletes the model, leading me to believe that it needs to instantiate the model in some way to figure that out. I could be wrong, but if it is doing this, why is not firing the model deleting event?

**Comment by morloderex** [comment]
@doctorallen I think this is expected behaviour. 

Because of the fact that when you are calling the delete method on the builder itself then you'r baypassing the model class which is responsible for trickering the the model events.

**Comment by fernandobandeira** [comment]
If the expected behavior is to bypass the model class it shouldn't soft delete, either way or we should add a call to the deleting event or remove the soft delete to make things consistent.

**Comment by deefour** [comment]
> The weirdest part about this whole thing is that if you have soft deletes defined, the query builder correctly soft deletes the model, leading me to believe that it needs to instantiate the model in some way to figure that out.

Model instances are not instantiated, [This is done through a global scope]( https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/SoftDeletingScope.php#L38-L44) that sets an [`onDelete()` callback on the QueryBuilder](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/Builder.php#L612-L615).

If you **really** must fire the `deleting` model event during a batch delete, consider [chunking the resultset](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/Builder.php#L357-L382), and deleting each model instance one-by-one, all wrapped in a transaction. This will be *way* more resource intensive for large resultsets, so you might consider alternative ways to handle whatever logic listens to that model event.

**Comment by jlem** [comment]
Agreed with @doctorallen and @fernandobandeira. Seems like `Model::where('id', $id)->delete();` would be an easy way to shoot yourself in the foot, as it's just as valid as `Model::find($id)->delete();` or `$model->delete();` for deleting. 

That said, the tricky part here is that when the actual model event fires, it passes through an instance of the model class as an argument. Since `Model::where('id', $id)->delete();` does not instantiate a model, then you can't simply fire the event as it will not have an instance of the model that it requires. This means that `Model::where('id', $id)->delete();` would have to do an implicit `get()-><each>->delete()` behind the scenes, which may have performance issues.

**Comment by doctorallen** [comment]
This really came about as a bug with someone who was not as familiar with Eloquent. I wouldn't really ever _want_ to delete directly from the builder, but I still found it strange that the global scope still worked for soft deleting. I agree with @fernandobandeira about keeping it consistent.

**Comment by doctorallen** [comment]
Furthermore, this issue continues when you batch delete relationships:
```php
        Course::deleting(function($course){
            $course->lessons()->delete();
            $course->units()->delete();
            $course->objectives()->delete();
        });

        Lesson::deleting(function($lesson){
            $lesson->activities()->detach();
            $lesson->standards()->detach();
            $lesson->shares()->delete();
        });

```

When the course is deleted with `$course::find($id)->delete()`, the `deleteing` event is called correctly, but the subsequent deletion of lessons does not call the `lessons::deleting` event. Is the only workaround here to loop over all of the relations and delete them?

**Comment by dsshafer** [comment]
Just ran into the same issue with cascading deletions, @doctorallen. I had to change my code from this:

```php
Plan::deleting(function ($plan) {
    $plan->goals()->delete();
    $plan->values()->delete();
});

Goal::deleting(function ($goal) {
    $goal->objectives()->delete();
    $goal->strategies()->delete();
});

Strategy::deleting(function ($strategy) {
    $strategy->actions()->delete();
});
```
to this:
```php
Plan::deleting(function (Plan $plan) {
    $plan->goals()->each(function (Goal $goal) {
        $goal->delete();
    });

    $plan->values()->each(function (Value $value) {
        $value->delete();
    });
});

Goal::deleting(function (Goal $goal) {
    $goal->objectives()->each(function (Objective $objective) {
        $objective->delete();
    });

    $goal->strategies()->each(function (Strategy $strategy) {
        $strategy->delete();
    });
});

Strategy::deleting(function (Strategy $strategy) {
    $strategy->actions()->each(function (Action $action) {
        $action->delete();
    });
});
```
After reading this issue I understand what was happening, but it took quite a while to stumble onto this issue, and the new code feels less readable and less intuitive than what I started with.

Maybe the fix is simply to document this case? It seems like cascading/batch deletes would be a fairly common need, and a note in the docs could prevent a lot of headaches.

**Comment by GrahamCampbell** [comment]
Yes please.

**Comment by dsshafer** [comment]
Can't tell if that's snark or just comically terse.

**Comment by doctorallen** [comment]
I've created a PR for this issue: https://github.com/laravel/docs/pull/2623
