### ISSUE TITLE
[Question] Why Type hint Closure when callable is supported?

### ISSUE THREAD

**Issue by ThatTomPerson** [laravel/framework#14420]
In places, methods are type hinted to accept Closures where it looks like they could or already support callable

an example of this is Connection::listen()
https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Connection.php#L820-L825

It would make code like
```
\DB::listen(function($sql, $bindings, $time) {
    dump($sql, $bindings, $time);
});
```
into
```
\DB::listen('dump');
```

**Comment by GrahamCampbell** [comment]
Duplicate. I have no objection to us supporting callables more. See the existing internals issue.
