### ISSUE TITLE
Doctrine PODMysql\Driver not found when use getDoctrineColumn

### ISSUE THREAD

**Issue by abkrim** [laravel/framework#14447]
Hi. 

I read https://github.com/laravel/framework/issues/3116 about a similar problem.

Get there by the need to obtain certain data in a field, from [Stackoverflow](http://stackoverflow.com/questions/18562684/how-to-get-database-field-type-in-laravel)

Working with 5.2 laravel

```
...
dd (DB::connection($connection)->getDoctrineColumn($table,$field)->getType()->getName())
...
```
Get error 
`Class 'Doctrine\\DBAL\\Driver\\PDOMySql\\Driver' not found`

Well. When read code for Illuminate/Database\Connection (below) see a error on PhpStorm about DBAL

```
/**
     * Get a Doctrine Schema Column instance.
     *
     * @param  string  $table
     * @param  string  $column
     * @return \Doctrine\DBAL\Schema\Column
     */
    public function getDoctrineColumn($table, $column)
    {
        $schema = $this->getDoctrineSchemaManager();

        return $schema->listTableDetails($table)->getColumn($column);
    }
```

Ok. After reading other issue, install doctrine/dbal, and rerun my command.

```
composer require doctrine/dbal
php artisan migratedb:migrate table --table=cms_users

connection: mysql Tabla: users Campo: email

                                                                                                   
  [Doctrine\DBAL\DBALException]                                                                    
  Unknown database type enum requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it.
```

I'm not an advanced programmer, and my English is quite poor. No where to place it, whether here, or if I should notify the draft Doctrine.

**Comment by srmklive** [comment]
Doctrine doesn't support enum data types. I myself added a [PR](https://github.com/doctrine/dbal/pull/2304) for inclusion of it in Doctrine. Due to this, its also not supported in Laravel.

**Comment by GrahamCampbell** [comment]
Closing since this is a no-fix I'm afraid. Sorry about that.
