### ISSUE TITLE
Call to a member function with() on a non-object error

### ISSUE THREAD

**Issue by M-amir-M** [laravel/framework#14442]

**Comment by M-amir-M** [comment]
Hi
I tired .i don't know what i do about this error.
my function is this:
 `public function viewop($layout,$view,&$data,$div=""){
		if(\Request::ajax()){
			if($div != ""){
				echo "DBArea('".htmlspecialchars($this->sanitize_output( View::make($view, $data) ),ENT_QUOTES)."','".$div."');";
			}else{
				echo "DBArea('".htmlspecialchars($this->sanitize_output( View::make($view, $data) ),ENT_QUOTES)."');";
			}
			exit;
		}else{
			$data['content'] = View::make($view, $data);
			$layout->with('data');
		}
	}`

**Comment by GrahamCampbell** [comment]
Please ask on the forums.
