### ISSUE TITLE
Collection method unique() does not differentiate the strings '0' and '00'

### ISSUE THREAD

**Issue by kristofvandam** [laravel/framework#14449]
With following example I expected to get both arrays back. Only got the first one with 'prefix' => '0'
```
$collect = collect(
[
    [
        'prefix' => '0',
        'trunk'  => 'A'
    ],[
        'prefix' => '00',
        'trunk'  => 'B'
    ]
]);

var_dump($collect->unique('prefix'));
```

I expected that because they are both Strings and therefore should be different.

Nice regards
Kristof

**Comment by fernandobandeira** [comment]
This is caused by the in_array function used in the base unique function.
Heres an example:

```php
$array = ['0', 'a'];
print_r(in_array('00', $array)); //returns true
print_r(in_array('00', $array, true)); //returns false
```

Yet i think that we should'nt enable the strict flag so it's probably the correct behavior for this function...

**Comment by themsaid** [comment]
A new `uniqueStrict()` was added to 5.3 that should resolve the issue. Thanks for reporting :)
