### ISSUE TITLE
problem yes or no ?

### ISSUE THREAD

**Issue by sajjadgolchin** [laravel/framework#14450]
Is the problem was to update the laravel 5.2.31 to 5.2.40  with "composer update" ????

**Comment by Daursu** [comment]
I've updated from 5.2.30 to 5.2.41 without any issues. Just a quick note, if you do run `composer update` all the other dependencies you have in `composer.json` will get updated as well.

**Comment by tomschlick** [comment]
If you're having a trouble updating you should post the command line output here. Most likely something in your app is causing composer to fail when it does the `php artisan optimize` at the end of the process.

**Comment by alexbowers** [comment]
This isn't really the place to look for support with general issues, this is a place for filing issues with the framework itself. I'd suggest either the Laravel Slack channel, IRC or StackOverflow

**Comment by GrahamCampbell** [comment]
Yes, please do ask on the forums, and I'm sure someone can help you there.
