### ISSUE TITLE
BelongsTo returns arbitrary model when foreign key is NULL

### ISSUE THREAD

**Issue by crishoj** [laravel/framework#14453]
Suppose a `A` belongs to `B`, and the relationship is defined on a nullable column of `B` called `no`:

```php
class A extends Model
{
    public function b(): BelongsTo
    {
        return $this->belongsTo(B::class, 'b_no', 'no');
    }
}
```

Now, using the relation on an `A` instance where `b_no` is `NULL` results in a query for `B`s where `no is NULL`:

```php
$a->b()->toSql()
=> "select * from `b` where `b`.`no` is null"
```

In practical terms, accessing `$a->b` when the foreign key is `NULL` returns  an arbitrary instance of `B` where `no is NULL`, and not the expected `NULL`.

**Comment by crishoj** [comment]
Related: #1563

**Comment by srmklive** [comment]
If the relation still returns null, i don't see it really as a bug.

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. I would agree that this does look correct.

**Comment by crishoj** [comment]
Problem is the relation only returns NULL when there are no records in the related table where the referenced key is NULL. 

If the referenced column is nullable, the relation returns an arbitrary instance for which the key field is NULL. This is hardly the expected behaviour.

**Comment by tomgrohl** [comment]
Its a feature in mysql not a bug in Laravel. (Details here: https://bugs.mysql.com/bug.php?id=62402)

Essentially if `sql_auto_is_null` is on in MySql doing a select against an auto increment column with null will return the last inserted row.

e.g:

```INSERT INTO `t1` (`name`) VALUES ('name1');```

```
SELECT COUNT(*) FROM `t1` WHERE `t1`.`id` IS NULL;
+----------+
| COUNT(*) |
+----------+
|        1 |
+----------+
```

Having `sql_auto_is_null` off fixes this issue. Which is the default.

**Comment by crishoj** [comment]
No, this issue is not related to `sql_auto_is_null`, which in any case is off in my installation:

```sql
MariaDB [(none)]> SELECT @@sql_auto_is_null;
+--------------------+
| @@sql_auto_is_null |
+--------------------+
|                  0 |
+--------------------+
1 row in set (0.00 sec)
```

**Comment by crishoj** [comment]
#748 describes the issue concisely.
