### ISSUE TITLE
Auth in Exception Handler

### ISSUE THREAD

**Issue by DemianD** [laravel/framework#14466]
Here is a something I want to do:
 
    public function report(Exception $e)
    {
        // When not logged in, don't log NotFoundHttpExceptions
        if($e instanceof NotFoundHttpException && !auth()->check())
            return;

        parent::report($e);
    }

But when I do the following: dd(auth()->check()) , it's always false.
Is there a way to access the Auth object in the handler?

Edit:
app('auth') is given me the object, but app('auth')->check() is also always false.

**Comment by DemianD** [comment]
app('auth') is given me the object, but app('auth')->check() is also always false.

**Comment by srmklive** [comment]
Can you describe in detail what you are looking to do?

**Comment by DemianD** [comment]
I have a website, and you can access only one page when you aren't logged in. The /login page.

When I'm looking in my logs, I see a lot of bots trying to access URL which not exist.
E.g.
- HNAP1
- phpMyAdmin
- Etc ...

I want to exclude this from my logs, to keep them "clean". 
So I want to only log NotFoundHttpExceptions when a user is logged in.

**Comment by srmklive** [comment]
you can use your .htaccess file to deny theses bots access to the URLs. Normally you do. Or you can simply use robots.txt to not allow any access to your site for bots. 

This [link](http://www.robotstxt.org/robotstxt.html) should help you out further.

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. Please continue this on the forums and I'm sure you can get a lot of help there. We strictly only process isolated bugs in the framework here (at least for now, this might change soon, it's not been decided yet).

**Comment by DemianD** [comment]
Hi, I will try to ask it in the forums.
But maybe it is a bug? I can access the Auth object, but when i do 'check()' it's always false.

@GrahamCampbell

**Comment by GrahamCampbell** [comment]
In my experience, this isn't normally a bug. Do of course feel free to come back here if it's becomes clear from the forums that this is a bug.

**Comment by DemianD** [comment]
Why is this in your experience not a bug (if i may ask)?

When I'm **loggend in**, I access e.g. /urlthatnotexist

Then, in the exception handler i do dd(auth()->check()); it says false.
I would expect "true" ? Or am I missing something

**Comment by kz** [comment]
```
# php artisan tinker
>>> app('auth')->check();
=> false
>>> app('auth')->setUser(App\User::find(1));
=> Illuminate\Auth\SessionGuard {#694}
>>> app('auth')->check();
=> true
```

It's all fine for me. There doesn't look to be a bug. Like Graham said, it would be a good idea to continue this discussion on the forums, and add more code for context.

**Comment by brunogaspar** [comment]
For 404's we can't seem to be able to access any session data on the exception handler, at least for the very quick tests i did.

**Comment by GrahamCampbell** [comment]
Yes, that is because authentication happens after routing.

**Comment by GrahamCampbell** [comment]
That is the expected behaviour. We don't actually read the session until after routing.

**Comment by delmicio** [comment]
where you able to change this behaviour? I want to have the current auth user when a NotFoundHttpException is thrown but I don't know where to do this change.
