### ISSUE TITLE
Proposal: better support for multiple entry scripts in Elixir. 

### ISSUE THREAD

**Issue by jlem** [laravel/framework#14464]
Here is an example of how I structure my applications these days (a structure I swear by, btw)

http://imgur.com/a/5G7r1

Getting the PHP stuff working in Laravel is a cinch thanks to how awesomely flexible Laravel is.

However, the major pain point I had was writing an Elixir extension to automatically handle the importing/minifying/bundling of multiple entry point scripts that happen to be located in different folders. Before writing that extension, I was manually adding each component's script to the gulp file. After 20 or so I was like "there has to be a better way".

To be fair, I'm not well versed in Gulp or the Node API, and maybe there's a super easy way to do this, but for projects where each "component" might have its own JS app or script, I couldn't find a simple straight-forward way to configure Elixir to glob through a directory, do some transformation to the scripts it finds, and output them in a mirrored directory in `/public`. 

To be clear, I deliberately do NOT want to glob all scripts together into a single `app.js` or `build.js` file, because that file would literally be 20mb in size if you combined each component/mdoule's individual scripts together. It's silly to load 99% of JS that a user doesn't need on any given page. 

As such, multiple entry points are needed, and it's quite tedious manually declaring each and every one of those individual scripts in your gulp file. 

So the proposal would be something like this:

    mix.<whateverify>('/some/root/**/*.js', './public/js');

As an example: 

    `/some/root/Account/Registration/registration.js` -> `/public/js/some/root/Account/Registration/registration.js`

Same is true of CSS pre-processors.

**Comment by GrahamCampbell** [comment]
Ping @JeffreyWay.

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch @jlem.
