### ISSUE TITLE
[5.2] Lazy Eager Loading issue in LengthAwarePaginator collection

### ISSUE THREAD

**Issue by vigneshgurusamy** [laravel/framework#14468]
After upgrading to Laravel 5.2.41, I'm getting **Method load does not exist** exception while trying to call **load()** method in **LengthAwarePaginator** collection.

I found out Eloquent Builder.php paginate() method sets empty array if total count of the result set is zero. So LengthAwarePaginator converts the empty array into \Illuminate\Support\Collection which does not have load() method.

```php
public function paginate($perPage = null, $columns = ['*'], $pageName = 'page', $page = null)
    {
        $page = $page ?: Paginator::resolveCurrentPage($pageName);

        $perPage = $perPage ?: $this->model->getPerPage();

        $query = $this->toBase();

        $total = $query->getCountForPagination();

        $results = $total ? $this->forPage($page, $perPage)->get($columns) : [];

        return new LengthAwarePaginator($results, $total, $perPage, $page, [
            'path' => Paginator::resolveCurrentPath(),
            'pageName' => $pageName,
        ]);
    }
```

Kindly return Eloquent empty collection instead of an empty array, so eager loading won't fail.

**Comment by srmklive** [comment]
Can you give a code example for it?

**Comment by vigneshgurusamy** [comment]
@srmklive 

To explain this scenario, I'm going to use posts and comments relationship.
For example, I have to fetch first 10 posts, but there are no posts in the table.

```php
$posts = Post::paginate(10);
```

In Eloquent builder paginate() method,

```php
$total = $query->getCountForPagination();

$results = $total ? $this->forPage($page, $perPage)->get($columns) : [];
```

In this scenario, `$total` will be zero and `$results` will be set as an **empty array** instead of **Eloquent collection**.

In **LengthAwarePaginater**, this empty array got converted into support collection.

My code to load comments for these posts using load() method is like below:

```php
$posts->load('comments');
```

Now load() fails because the given collection is **Support collection** not an **Eloquent collection**.

**Comment by srmklive** [comment]
Have you done it like this?

    $posts = Post::with('comments')->paginate(10);  

What results does the above line gives you?

**Comment by vigneshgurusamy** [comment]
@srmklive I know with() works to load relations. But in some cases, I have to load relations after obtaining the results

**Comment by srmklive** [comment]
My suggestion would be that you utilize with to load relations. You can simply if the related data is empty or not. This is a better approach in my opinion:

    @if (!empty($post->comments))

    @endif

**Comment by vigneshgurusamy** [comment]
@srmklive  By using your way, it defeats the purpose of Eager loading.

**Comment by jlem** [comment]
@vigneshgurusamy without taking a closer look at the code, I tend to agree with you that it should return an Eloquent collection, not a Base collection. That said, you can always wrap the results in an Eloquent collection yourself. 

You can just do `$results = new Illuminate\Database\Eloquent\Collection($posts)`. This will convert it to an Eloquent collection whether it happens to be an array, or another collection.

**Comment by vigneshgurusamy** [comment]
@themsaid I'm getting this issue after your pull request #14389 merged (v5.2.41). This issue was not there until v5.4.39.

Can you take a look?

**Comment by vigneshgurusamy** [comment]
@jlem Thanks for the support.

Am I afraid, I can not do that since I need the results as **LengthAwarePaginator** object with **Eloquent collection** as a paginator collection.

**Comment by themsaid** [comment]
Well the actual change occured in this PR: https://github.com/laravel/framework/pull/14188

Mine was to fix some issue with it but it looks like the original PR has caused another issue, will submit a fix in a minute.
