### ISSUE TITLE
JSON type column didn't changed 

### ISSUE THREAD

**Issue by nahid** [laravel/framework#14472]
I have a table column which type is json but when I want to change this column type to string from migration this error was show

> Unknown database type json requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it. 

Here is my migrations
```php
Schema::table('users_info', function($tbl){
        $tbl->string('social_links', 250)->change();
 });
```

So, what should I do now?

**Comment by ninjaparade** [comment]
@nahid could you tell me what version of  `doctrine/dbal ` you have installed in your app? Check your `composer.lock` file

**Comment by ninjaparade** [comment]
@nahid just curious, could you tell me what version of `MySql` and `doctrine/dbal ` you're using? I've seen a lot of issues around `doctrine/dbal ` and json but nothing to suggest what you're doing shouldn't work.

**Comment by ninjaparade** [comment]
@nahid it looks like this is a `doctrine/dbal` issue, if you check the class where your exception is through, there is no mapping for `json`. https://github.com/doctrine/dbal/blob/2.5/lib/Doctrine/DBAL/Platforms/MySqlPlatform.php#L952

**Comment by themsaid** [comment]
This doesn't seem to be a bug with the framework, closing then :)
