### ISSUE TITLE
[5.2] Incorrect count query in paginate method

### ISSUE THREAD

**Issue by n7olkachev** [laravel/framework#14473]
Simple example:
```php
Categories::withCount('products')->having('product', '>', 0)->paginate(15);
```
I suppose the issue is in the `Query/Builder@getCountForPagination` method.

**Comment by jlem** [comment]
Any chance you could supply more information, or perhaps a seed of your table that others can use to verify the bug? I.e. what you got vs what you expected to get?

**Comment by n7olkachev** [comment]
It just breaks in `paginate` method (no results, exception), because `getCountForPagination` ignores subselect which is done in `withCount`.
