### ISSUE TITLE
Query Builder - passing eloquent model

### ISSUE THREAD

**Issue by davidrushton** [laravel/framework#14495]
Sometimes - granted not very often - I accidentally pass a full eloquent model to a `where` condition on a DB query. 

At the moment this breaks, I think, causing SQL similar to

```
select * from `categories` where `id` = '{\"id\":2,\"title\":\"Category\"}' and `categories`.`deleted_at` is null limit 1
```

Would you accept a PR for adding the following logic to the Query Builder, or is this not really desirable?

```
if ($value instanceof Model) {
	$value = $value->getKey();
}
```

David :)

**Comment by mnabialek** [comment]
I personally don't think it's a good idea, because it can lead to unpredicted results. What in case you have query like this:

```select * from `categories` where `title` = '{\"id\":2,\"title\":\"Category\"}' and `categories`.`deleted_at` is null limit 1```

In above title should be rather used instead of key

**Comment by davidrushton** [comment]
Fair point @mnabialek, thanks.

Would the following get round that?

```
if ($value instanceof Model) {
    $value = $value->getAttributeValue($column);
}
```

**Comment by mnabialek** [comment]
@davidrushton I still don't think it's a good idea, what if you have completely other table:

```
select * from `something` where `title` = '{\"id\":2,\"title\":\"Category\"}' and `categories`.`deleted_at` is null limit 1
```

What should be used here in your opinion? `title`, `id` or maybe something else like `id.title`? I don't think it's a good idea, if you want to get expected result, you should pass valid value and not the whole object

**Comment by ntzm** [comment]
If you are trying to do this, why not just use Eloquent's relationships?

**Comment by davidrushton** [comment]
@ntzm I use Eloquent relationships for querying all the time. This was more just a suggestion of a convenient Laravel fallback, rather than casting a model to it's json representation for the SQL query.

A better example:

```
$owner = $request->user();

// ...

$others = User::where('id','!=',$owner)->get();
```

Of course, that should be

```
$others = User::where('id','!=',$owner->id);
```

But in the very few instances where i've forgotten that `$owner` is a full Model and not just an ID, my thinking was Laravel could get the primary key (or other attribute) behind the scenes.

Happy to close if it's generally not a good idea or makes the query builder too responsible. Just thought it was a little convenient catch :)

**Comment by chrismpettyjohn** [comment]
I don't think it would be a good idea because it'll allow bad practice.  If it throws an error when you accidentally mess up, it'll allow you to realize it and go back and fix it to proper practicing rather than the system going through extra stress to fix it.
