### ISSUE TITLE
QueryBuilder count with subquery and having

### ISSUE THREAD

**Issue by n7olkachev** [laravel/framework#14492]
Example:

We have 2 tables: bills, payments
Bills table:
<table>
<thead>
<tr>
<td><strong>id</strong></td>
</tr>
</thead>
<tbody>
<tr><td>1</td></tr>
<tr><td>2</td></tr>
<tr><td>3</td></tr>
</tbody>
</table>
Payments table:
<table>
<thead>
<tr>
<td><strong>id</strong></td>
<td><strong>bill_id</strong></td>
<td><strong>sum</strong></td>
</tr>
</thead>
<tbody>
<tr><td>1</td><td>1</td><td>100</td></tr>
<tr><td>2</td><td>1</td><td>200</td></tr>
<tr><td>3</td><td>2</td><td>50</td></tr>
</tbody>
</table>
We want to count bills with payments.sum > 100.
I decided to do it like so:
```php
\DB::table('bills')
    ->selectSub(
        \DB::table('payments')
            ->whereColumn('bill_id', 'bills.id')
            ->selectRaw('sum(sum)'), 
        'current_sum')
    ->having('current_sum', '>', 100)
    ->count()
```
As a result I had an Exception: 
```
Column not found: 1054 Unknown column 'current_sum' in 'having clause' (SQL: select count(*) as aggregate from `bills` having `current_sum` > 0)
```
`count` method in `Query\Builder` just removed my subquery, which is obviously incorrect.
Am I doing smth wrong?

**Comment by n7olkachev** [comment]
Found PR for this: #9307

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. Closing this in order to move further discussion to the PR.
