### ISSUE TITLE
redirect is displaying redirect message on page

### ISSUE THREAD

**Issue by dwickander** [laravel/framework#14508]
5.2.39 worked as expected, when I update to 5.2.41 then redirects are displaying redirect message on screen before redirecting.

using "return redirect()->route('route-name')->send(); in a custom php file that the controller calls.

**Comment by sisve** [comment]
Can you show the http response that causes this behavior, including headers and content?

**Comment by dwickander** [comment]
I have narrowed the issue down to \symfony\http-foundation\Response->send()

before composer upgrade ( when it worked as expected and if I manually add it back in it works again ) it was….

    public function send()
    {
        $this->sendHeaders();
        $this->sendContent();

        if (function_exists('fastcgi_finish_request')) {
            fastcgi_finish_request();
        } elseif ('cli' !== PHP_SAPI) {
            static::closeOutputBuffers(0, true);
        }

        return $this;
    }


after composer upgrade ( showing redirect message ) it is…

    public function send()
    {
        $this->sendHeaders();
        $this->sendContent();

        return $this;
    }

it looks like it is the "static::closeOutputBuffers(0, true);” statement that is missing that is causing the issue.

it looks like they have reverted back to the working code in the git repository ( https://github.com/symfony/http-foundation/commit/997cab63d81d61c6421c4dd49cc0fa588662b340 ), but it does not seem to be merged into the released version composer downloads as I just tried upgrading again and it is still not showing.

Thanks!!

**Comment by themsaid** [comment]
This appears to be an issue with Symfony and not laravel.
