### ISSUE TITLE
Wrong Illuminate\Database\Eloquent\Builder->getQuery() @return

### ISSUE THREAD

**Issue by danilcha** [laravel/framework#14506]
This is Illuminate\Database\Eloquent\Builder->getQuery():
```php
    /**
     * Get the underlying query builder instance.
     *
     * @return \Illuminate\Database\Query\Builder|static
     */
    public function getQuery()
    {
        return $this->query;
    }
```
PhpDoc says it returns `Illuminate\Database\Query\Builder` OR `static`. This causes many problems with PhpStorm autocompletion and looks invalid because the field $query is defined like that:
```php
    /**
     * The base query builder instance.
     *
     * @var \Illuminate\Database\Query\Builder
     */
    protected $query;
```
Moreover, the constructor, that fills this field, is defined with strict typing as:
```php
    public function __construct(QueryBuilder $query)
    {
        $this->query = $query;
    }
```

Probably the PhpDoc for `getQuery()` should just specify `@return \Illuminate\Database\Query\Builder`.

**Comment by GrahamCampbell** [comment]
Thanks for the report. We're open to PRs please. :)

**Comment by timbroder** [comment]
@GrahamCampbell shouldn't this stay open until it gets fixed? Unclear what bug reporting process should be. 

IE if someone in the future runs into this issue, and finds this bug, they may assume it's been fixed because the bug is closed.

Thanks!
