### ISSUE TITLE
PDOExceptions shows db password in Exception

### ISSUE THREAD

**Issue by jorenvh** [laravel/framework#14518]
<img width="1320" alt="laravel-db-error" src="https://cloud.githubusercontent.com/assets/8791625/17209440/53735a30-54bd-11e6-805d-070b30c3667f.png">

**Comment by petehouston** [comment]
It looks like you haven't turned on MySQL service.

**Comment by GrahamCampbell** [comment]
Thanks, but there's no bug here. Make sure you turn debug mode off in production.

**Comment by jorenvh** [comment]
@GrahamCampbell Indeed debug has to be false in production. But besides that, a password may never be printed on the screen. It's a security issue.

**Comment by GrahamCampbell** [comment]
It doesn't pose a security issue, and it's nothing really to do with Laravel since PHP itself provides this exception and it's message.

**Comment by jorenvh** [comment]
@GrahamCampbell, In my opinion this still is a security issue, can you explain to me why it's not?

**Comment by GrahamCampbell** [comment]
I don't mean to be stubborn, but could you explain why it is?

**Comment by jorenvh** [comment]
A password should never be printed behind the back of a developer? What if some new ass kid forgets to set debug to false? Then everything is just there for everyone who hits that error?

Maybe it's not really an issue but it's definitely one to think/discuss about, because in my opinion it should just never be printed. And I know that's just my opinion but I thought it was worth opening an issue for this.

**Comment by GrahamCampbell** [comment]
Forgetting to set debug to false is the security issue here.

**Comment by jorenvh** [comment]
yeah but besides that, why is it necessary to print that password on the screen? It doesn't provide anything more to the error?

**Comment by vlakoff** [comment]
Found an interesting topic: about it: [Should passwords be revealed in error message?](http://security.stackexchange.com/questions/15452/should-passwords-be-revealed-in-error-message)
Basically people agree that PHP shouldn't display this password.

**Comment by tback** [comment]
I think it's reasonable to expect that a web framework doesn't expose credentials to users, developers or logging systems by default. I'm quite surprised this was closed without taking further action.

**Comment by mfn** [comment]
I think PRs are welcome?

FWIW, https://github.com/getsentry/sentry-laravel does that before sending data (or to be more correct: it's underlying Raven client library).

**Comment by davefrassoni** [comment]
I was shocked as well when I saw all my .env data was printed online on screen? wtf?

**Comment by mhardz-17** [comment]
I think this is the reason why our server(dev) was hacked.
They see the error on exception where the username and password was shown.
And we are using phpmyadmin, so they used it to enter the database server.
Beware.
