### ISSUE TITLE
Is env function delayed?

### ISSUE THREAD

**Issue by hakuno** [laravel/framework#14511]
Well, whenever I google about this error

> [2016-07-27 15:29:08] local.ERROR: RuntimeException: No supported encrypter found. The cipher and / or key length are invalid. in C:\...\vendor\laravel\framework\src\Illuminate\Encryption\EncryptionServiceProvider.php:29

I found it is needed to regenerate a valid 32-length hash for AES-256-CBC. Okay, it's right.

However, I thought the ENV may be delaying to retrieve the custom data from the `.env` file. Because it appears **again** sometimes. Look at `config/app.php` for:

`'key' => env('APP_KEY', 'someDifferentKeyFromTheDotEnvFile'),`

**Is it possible to decrypt the session with the wrong key at runtime?**

Would OPCACHE improve that `.env` file reading? Is it any to do with config:cache for improvement?

Thanks in advance!

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. You just need to run the `config:cache` command to persist any config updates. :)

**Comment by GrahamCampbell** [comment]
Once the config is cached, we skip reading the `.env` file entirely. As well as improving performance, it also fixes issues with environment variables leaking through threads.

**Comment by hakuno** [comment]
Thank you so, @GrahamCampbell
Whether it's possible... so I'm not crazy :laughing: I'll rely on config:cache to solve the leaking.

**Comment by aledmb** [comment]
Hey guys, I'm having this issue from time to time. It's totally random. Every few requests, it fails reading the key from the .env file, but most of the request go through with no problems.

Running config:cache seems to do the trick, but this is on a development machine.

Is there any other way to get around this than running config:cache periodically?

**Comment by GrahamCampbell** [comment]
No, sorry. This is a bug inherit to the way PHP works. Probably a no-fix. :(

**Comment by aledmb** [comment]
Cool, no problem. Thank you!

What should I search for if I want to learn more about this issue with PHP?
