### ISSUE TITLE
SerializesModels behavior on non-persisted Eloquent Models

### ISSUE THREAD

**Issue by grunjol** [laravel/framework#14526]
When passing a model into a Job with the SerializesModels trait, the serializer checks if the value is an instance of QueueableEntity and transforms it into a ModelIdentifier. 

That works fine for persisted models but if you pass a non-persisted model, all the values are lost because the object is transformed into a ModelIdentifier with a null id.

What do you think about checking if the entity is saved and do a regular serialization on non-saved instances?

Something like this
```
    protected function getSerializedPropertyValue($value)
    {
        if ($value instanceof QueueableEntity && !empty($value->getQueueableId())) {
            return new ModelIdentifier(get_class($value), $value->getQueueableId());
        }

        return $value;
    }
```

This avoids pass all the properties for a model (even related persisted model instances) to the job.

**Comment by sisve** [comment]
I'm seeing issues when the unsaved model references other models; wouldn't that in turn cause issues with serialized pdo objects? How about throwing an exception to highlight the issue to the developer, so it can be saved?

**Comment by themsaid** [comment]
Hey @grunjol @sisve,

looks like you have a suggestion for a better handling of the matter, can you please open a PR? It's always better to discuss implementations.

I'm closing this issue since it's not really a bug, but please feel free to continue discussions if you want.

For suggestions and feature requests please use the https://github.com/laravel/internals repo.

**Comment by RobGordijn** [comment]
This could be a possible bug if you consider dropping a pivot-model into the queue-job. Since the ModelIdentifier uses firstOrFail() and the PK of a pivot usually consist of 2 columns.

**Comment by zlodes** [comment]
Guys 
How about to check Model for `exists`?

Current code tries to query Model if it have the ID. But someone may use pre-defined IDs like a UUID and then Job with SerializeModels trait crashes.
