### ISSUE TITLE
MSSQL Driver Issue - Eloquent save() tries to set identity column on update 

### ISSUE THREAD

**Issue by Kabangi** [laravel/framework#14532]
Am getting this  "Cannot update identity column 'id'" bug when I try to update using eloquent.

Am using Laravel 5.2

**Comment by stevebauman** [comment]
Can you post your model and usage code?

**Comment by chrismpettyjohn** [comment]
He posted this issue on StackOverflow, and said the problem was unsetting the variable before calling ->save()
