### ISSUE TITLE
Logout route is a post method in 5.3

### ISSUE THREAD

**Issue by darwinluague** [laravel/framework#14543]
`/**
     * Register the typical authentication routes for an application.
     *
     * @return void
     */
    public function auth()
    {
        // Authentication Routes...
        $this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
        $this->post('login', 'Auth\LoginController@login');
        $this->post('logout', 'Auth\LoginController@logout');

        // Registration Routes...
        $this->get('register', 'Auth\RegisterController@showRegistrationForm');
        $this->post('register', 'Auth\RegisterController@register');

        // Password Reset Routes...
        $this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
        $this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
        $this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
        $this->post('password/reset', 'Auth\ResetPasswordController@reset');
    }`

**Comment by GrahamCampbell** [comment]
Yes, we made it POST to be properly HTTP compliant. You must not perform non-readonly actions on GET or HEAD requests.

**Comment by darwinluague** [comment]
Any idea how to make this work because I'm getting MethodNotAllowedHttpException.

**Comment by GrahamCampbell** [comment]
You need to POST to that now.

**Comment by darwinluague** [comment]
ahh ok thanks

**Comment by jhoff** [comment]
Alternately, you could just setup a GET route that does the same thing, albeit to @GrahamCampbell's point it's not HTTP compliant:

> Route::get('logout', 'Auth\LoginController@logout');

**Comment by GrahamCampbell** [comment]
@jhoff Adding a GET route is breaking the HTTP spec. It should only be POST.

**Comment by GrahamCampbell** [comment]
Well, technically, it just must not be "safe", so technically you could use any verb you want so long as it's not GET or HEAD.
