### ISSUE TITLE
Eloquent eager loading issue

### ISSUE THREAD

**Issue by callmez** [laravel/framework#14542]
```
$books = App\Book::with('author')->get();

foreach ($books as $book) {
    echo $book->author->name;
}
```
will generator 2 queries.
```
select * from books

select * from authors where id in (1, 2, 3, 4, 5, ...)
```

sometimes i wanna get books with exists user such as

```
$books = App\Book::joinWith(['author'], 'inner join')->get();

foreach ($books as $book) {
    echo $book->author->name;
}
```

```
select * from books inner join authors on books.author_id = authors.id
select * from authors where id in (1, 2, 3, 4, 5, ...)
```
the idea is from Yii2  ActiveRecord [joining-with-relations](https://github.com/yiisoft/yii2/blob/master/docs/guide/db-active-record.md#joining-with-relations-)

Is there any way  to solve this issue? thanks!

**Comment by johnpaulmedina** [comment]
`->join('authors', 'authors.id', '=', 'books.author_id')`?

**Comment by JamesGuthrie** [comment]
While @johnpaulmedina's solution does work, it doesn't answer the actual issue with eager loads not being executed as a single query out-of-the-box by Eloquent. These types of queries are supported in Rails, and SQLAlchemy, as far as I know.

I looked into how this would be achieved a while ago and the answer is that it's definitely non-trivial, but something I would really like to see in Eloquent. When I asked about it, the answers I got mostly said 'why would you need that?', and 'Running joins in the database takes more time than running individual selects sequentially', which I don't really buy.

Unfortunately I'm not sure if it will be possible to implement it in a way that would actually be merged in. The first hindrance is that Eloquent's 'magic' with model attribute loading makes it impossible to automatically build the join query such that you can determine which fields belong to which objects, unless you interrogate the db as to the table structure and keep that on record.

**Comment by themsaid** [comment]
That looks like a feature request more than a bug report.

For suggestions and feature requests please use the https://github.com/laravel/internals repo.
