### ISSUE TITLE
[5.3] phpunit will throw Cannot use Illuminate\Contracts\Mail\Mailer as Mailer because the name is already in use' in Illuminate/Mail/Mailable.php

### ISSUE THREAD

**Issue by darwinluague** [laravel/framework#14556]
When I try to use `Mail::to($event->user->email)->send(new Welcome($event->user));` in my controller and run phpunit it will throws an exception `Cannot use Illuminate\Contracts\Mail\Mailer as Mailer because the name is already in use' in Illuminate/Mail/Mailable.php:10` but works fine in the browser.

Note: I don't have any `use Illuminate\Contracts\Mail\Mailer as Mailer` in my application.

**Comment by lucasmichot** [comment]
This has been fixed by https://github.com/laravel/framework/pull/14539 I think ?
