### ISSUE TITLE
[auth:api ] without api token on request , system allows to login

### ISSUE THREAD

**Issue by subakarank** [laravel/framework#14552]
$credential = [
            'api_token' => $request->input('api_token')
        ];
        if(Auth::guard('api')->validate($credential))
        {
            echo 'logged in ';
        }
        else
        {
            echo 'login failed ';
        }
http://localhost:8080/laravel/user/show. Here I never send api_token=xxxxxx on the request. but system print "logged in " messge

how is it possible?

**Comment by srmklive** [comment]
Never came across this issue. Would need a more concrete example that depicts this issue clearly.

**Comment by mnabialek** [comment]
Is it possible that you authenticate user earlier for example in middleware so it's logged already before running this code?

**Comment by subakarank** [comment]
Auth.php
========

        'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
        ],
    ],

`

I use default auth settings. No any custom settings

If I send **?api_token=(no_value_here)** then system throw login error message. But If I send the request without the key(api_token) system shows  logged in message

**Comment by subakarank** [comment]
Found the issue. I have set  null for api_token in database. So system take null user record and logged in . I set the field to not null and unique..

Anyway thanks for your comment.

**Comment by srmklive** [comment]
@subakarank i tried this with api_token set as null, and tried the following code:

```
    $credential = [
        'api_token' => $request->input('api_token')
    ];

    if(auth()->guard('api')->validate($credential))
    {
        echo 'logged in ';
    }
    else
    {
        echo 'login failed ';
    }
```

If i passed a null `api_token` value, it always showed me the message `login failed`.

**Comment by srmklive** [comment]
@subakarank i didn't do any validation. I can't replicate the issue you are reporting.

**Comment by subakarank** [comment]
Did you set null for any one of the user's api_token?  pls set null then try

**Comment by srmklive** [comment]
@subakarank yep i did.

**Comment by subakarank** [comment]
on request don't send the query name api_token . 
Example : http://localhost:8080/laravel/user/show

then run the  following query 

`$credential = [
               'api_token' => $request->input('api_token')
           ];
    if(auth()->guard('api')->validate($credential))
    {
        echo 'logged in ';
    }
    else
    {
        echo 'login failed ';
    }`

**Comment by subakarank** [comment]
If you think everything are fine, then I close this issue. Am sure that I don't do any additional settings for auth. I found that issue that it is the null value. After I fix validation and null value then it works fine for me.

Anyway thanks for your comments and remark

**Comment by subakarank** [comment]
@srmklive 
Don't even send the name(key) **api_token** on request and then try.
