### ISSUE TITLE
There is no _old_input in session after redirect

### ISSUE THREAD

**Issue by ahmadazimi** [laravel/framework#14554]
Hi there,

I'm using **web** middleware and latest version of laravel.
When I try to redirect back, my session is reseted I think! Because the _old_input available first but after redirect to the page it is gone!

See my screenshots from clockwork:

**form is posted  to this url:**
<img width="1274" alt="screen shot 1395-05-09 at 11 05 26" src="https://cloud.githubusercontent.com/assets/1847191/17268665/70358d5c-5646-11e6-9e87-2f97abb33a62.png">

**after redirect _old_input is gone:**
<img width="1277" alt="screen shot 1395-05-09 at 11 05 35" src="https://cloud.githubusercontent.com/assets/1847191/17268670/9acba074-5646-11e6-83ce-20bd8aec4248.png">

**Comment by themsaid** [comment]
Do you till have the issue? I'm not sure if it's a bug in the framework.

**Comment by ahmadazimi** [comment]
@themsaid Yes the problem still exist with Laravel version 5.2.45

I've found that the login form works correctly with session and old values but in all other forms, there is no session available after redirect.

Should I do something special before redirecting?
