### ISSUE TITLE
5.2 deleted models appear in results

### ISSUE THREAD

**Issue by morenDev** [laravel/framework#14553]
I have all nessesary stuff in my code:
```php
use SoftDeletes;
protected $dates = ['deleted_at'];
```
And I have also a populated deleted_at field in DB;
But when I query this:
```php
$model = Example::find($id);
```
I can get a soft deleted model.

So what I'm doing wrong?

**Comment by johnpaulmedina** [comment]
do you have this on the model?

`use Illuminate\Database\Eloquent\SoftDeletes;`

**Comment by morenDev** [comment]
yes, it deletes as expected by populating deleted_at

**Comment by Rubemlrm** [comment]
2 questions:

1- If you do a Example::all() that entry appears too ?
2 - I've checked the code and dont find any condition in the find method that filters delated_at entrys. You can check there https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/Builder.php#L159

**Comment by morenDev** [comment]
I figured it out! Looks like I forgot to call parent method in boot().
```php
public static function boot(){
    parent::boot()  //forgot to add this
    ....//code
}
```
