### ISSUE TITLE
Laravel 5.3 Logout route making a "POST" request

### ISSUE THREAD

**Issue by makten** [laravel/framework#14567]
When using Auth::routes(), logout routes make a "POST" request which causes MethodNotAllowedHttpException. Is this a bug or was this intentional?

**Comment by n7olkachev** [comment]
Logout must be POST action due to CSRF.

**Comment by Macsch15** [comment]
It's not a bug: https://github.com/laravel/framework/commit/9d3dd66cf8afbd54d7e4a7889e0a7e0d3770fd05

**Comment by mikerockett** [comment]
Further reference: #14543

**Comment by sergiy-lytvyn** [comment]
Route::get('logout', function (){
        Auth::logout();
        return redirect('/');
    });

**Comment by sanketCactus** [comment]
> Logout must be POST action due to CSRF.
@n7olkachev 
Can you please elaborate this ?
