### ISSUE TITLE
[eloquent] Problem with eager loading polymorphic relationship

### ISSUE THREAD

**Issue by Milewski** [laravel/framework#14577]
I think there is a bug within eager loading polymorphic relationship.. consider the following 

```
//Project.php
public function stage()
{
    return $this->morphTo('stageable');
}
```

then somewhere else.. lets assume i do have a project (Project::find(1)...)

```
dd($this->project)

//#relations: []
```

```
$this->project->stage;

dd($this->project);

//#relations: array:1 [▼
    "stage" => Idea {#498 ▶}
  ]
```

```
$this->project->load('stage')
dd($this->project)

//#relations: array:2 [▼
    "stage" => null <--- ???? why does it turned to be stageable instead of just stage?
    "stageable" => Idea {#505 ▶}
  ]
```

**Comment by johnpaulmedina** [comment]
Is the class for the model named Stageable() ?

**Comment by Milewski** [comment]
no its called Idea

**Comment by johnpaulmedina** [comment]
I'm on my phone now. I can't test till tomorrow.

**Comment by Milewski** [comment]
any news?

**Comment by themsaid** [comment]
@Milewski can you please include the laravel version where you had the problem?

**Comment by Milewski** [comment]
@themsaid it exists in all versions... including 5.3 i made a gist with a reproducible steps

https://gist.github.com/Milewski/43a0cae87297b0d37cf19417cb7163f2

**Comment by themsaid** [comment]
You need to do the following:

    public function stage()
    {
        return $this->morphTo(null, 'stageable_type', 'stageable_id');
    }

Using $name will set the relationship name in the model instance causing the behaviour you'r experiencing, when you need to use custom keys do it like above.

The name feature in morphTo is broken though, but that's another issue different thank the one reported here.

Thanks for the reporting :)

**Comment by robclancy** [comment]
@themsaid just had this issue on 5.6, and being explicit instead of using the name feature fixes it still. So needs to be reopened?
