### ISSUE TITLE
[5.3] Incorrect Eloquent serialization when sending emails with queued

### ISSUE THREAD

**Issue by spyric** [laravel/framework#14579]
Here a code that works normal in laravel 5.2

```
$user = \App\Models\User::find(1);
$data = [
    'previewMessage' => 'Your account have been successfully created',
    'user'           => $user,
];


\Mail::queue('emails.new_employee', $data, function ($message) use ($user) {
    $message
        ->subject('Registration completed')
        ->to($user->email);
});
```

in emails/new_employee.blade.php in 5.2 you will get an Eloquent model, but in 5.3 you will get an array with attributes.

Is it normal behaviour? Or I shouldn't to pass eloquent model to email view?

**Comment by GrahamCampbell** [comment]
> Or I shouldn't to pass eloquent model to email view?

Yeh, don't do that. If you don't use the sync queue, you'll get a serialization error surely?

**Comment by spyric** [comment]
I have tried with database driver too... Same result

In database info stores like this: 
![image](https://cloud.githubusercontent.com/assets/2044754/17289486/5ae6ee06-57f3-11e6-94d7-958cbe76994c.png)

So I think it's breaking change and this should eigher be fixed (I tried to do it my self but didn't find a way to fix it) or be mentioned in upgrade docs

**Comment by GrahamCampbell** [comment]
I'm saying why doesn't it crash on L5.2?

**Comment by spyric** [comment]
I think because Taylor has changed way to serialization of data.

Here how task looks in Laravel 5.2

![image](https://cloud.githubusercontent.com/assets/2044754/17289776/97d785a4-57f4-11e6-9082-7b898ba4e2db.png)

So I think that in 5.2 ```::entity::|App\\User|1``` was replaced by object after query to database. In 5.3 we are getting plain object that is not associaded with model

**Comment by spyric** [comment]
In 8952983 were removed functions:

- resolveQueueableEntities
- resolveQueueableEntity
- prepareQueueableEntities
- prepareQueueableEntity

**Comment by huglester** [comment]
Almost all the time we use Eloquent model inside the Email template files. So now we will need to move to arrays (when using queues)? 

thank you

**Comment by spyric** [comment]
@huglester I hope no, and @taylorotwell  will approve my pull request and all will work like before, because I very often use Eloquents mutators in emails and it's very helpfull. 

Also if you will use Mailable way,  models will be serialized. Two similar ways and two different results for one action . It's something strange, imho

**Comment by spyric** [comment]
Fixed by Taylor
