### ISSUE TITLE
Command `cache:clear` has undesired side-effects

### ISSUE THREAD

**Issue by rscafi** [laravel/framework#14582]
Currently, we are using Redis both as our `session` and `cache` driver.
When running `php artisan cache:clear`, our sessions are wiped too.
This is extremely bad, we are attempting to clear the cache only, not the sessions.

We are using Laravel 5.1 but I guess that the problem persists for the later versions.

I guess that this guy is doing it:
https://github.com/laravel/framework/blob/5.1/src/Illuminate/Cache/RedisStore.php#L132

**Comment by GrahamCampbell** [comment]
Thanks, but this is the expected behaviour. You should use separate redis databases. Out of the box redis gives you 16. Laravel connects to database 0 by default, you can add two redis connections so you can connect to database 0 and database 1.

**Comment by rscafi** [comment]
Thanks for the feedback, @GrahamCampbell.
Maybe this should be added to the docs, since it's not so clear/trivial?

**Comment by GrahamCampbell** [comment]
Sure. We're open to PRs. :)
