### ISSUE TITLE
Confusing error when env value have space (quotes are missing)

### ISSUE THREAD

**Issue by isometriq** [laravel/framework#14586]
Since Laravel 5.2 (I think), the `.env` file requires values with spaces to be enclosed with quotes

When a value with spaces is not properly enclosed the error message is confusing. I says "Class log does not exists". This happens when running artisan clear-compiled.

**Comment by jhoff** [comment]
I have experienced this as well. Though it seems like a deficiency in the dotenv library.

**Comment by jhoff** [comment]
According to https://github.com/vlucas/phpdotenv/blob/master/src/Loader.php#L228, the `dotenv` library should throw a warning if a value contains a space as of the 2.0 release.

Laravel 5.1 still used dotenv 1.x and upgraded to 2.x in 5.2 so this shouldn't be an issue any longer.

My guess is that you're using Laravel 5.1 ( or earlier ) or if you've manually upgraded then you need to run `composer update` to update your packages accordingly.

**Comment by isometriq** [comment]
Yes, I was using 5.1 and I've used `composer update --no-scripts`
But I went to use artisan, it failed, but did not see any warning. The easiest way to reproduce is to put a value without quotes and attempt any artisan command.

**Comment by GrahamCampbell** [comment]
All error confusion should be fully resolved in L5.3. We couldn't fix on 5.1 due to BC reasons though, sorry.
