### ISSUE TITLE
View composers and multiple views included

### ISSUE THREAD

**Issue by HassanShojaei** [laravel/framework#14585]
Hi,
I have a view that included 3 another view in it like this:
```
@include('common.nva_top')
@include('common.nav_bottom')
@include('common.footer-categories')
```
And this is my ComposerServiceProvider:
```
public function boot()
    {
        // Using class based composers...
        view()->composer(
            '*', 'App\Http\ViewComposers\HomeComposer'
        );
    }
```
And I have a compose like this:
```
 public function compose(View $view)
    {
        //some another codes
        $this->requirements=new \stdClass;
        $_SESSION['runCount']++;
        $this->requirements->s=$_SESSION['runCount'];
        $view->with('requirements',  $this->requirements);
    }
```
Every time that I refresh the page my session will be +=3 I guess it's a problem that this compose will run as many view that I included! 
I set my view in ComposerServiceProvider to all view that will be included or called, now Composer shouldn't just call my compose once and use the result in another included view!?
Thanks.

**Comment by themsaid** [comment]
This is an expected behaviour, you've set your composer to run on all views, this includes partials as well, every time you call `@include()` the view is rendered which will cause the composer you set to run.

I recommend that you avoid using `*` and create better naming conventions that'll allow you to run the composer while building the main views only.

**Comment by HassanShojaei** [comment]
Thank you themsaid.
I know what are you talking about but what is problem here for me is that, when I have a view that include another view in it and both of them use my defined composer variables, in ideal way I expect that my composer run just once at the start and date share between all views not that Laravel run my composer every time that I use include for just one page with multiple views.

And your recommend about not using * I tried to call just app view that included in all pages to avoid call composer in another includes, then got an error that says "undefined variables" , another view that calls in this main view doesn't have variables that came from composer but both of them are calling in just one page for one route!
Actually I think it's better to call view composer base on routes! because when I wanna use some data in a view it doesn't matter which view I am using it, the important think here is that data just be passed in that routes once for all views.
Maybe I didn't got this part or implementation of Laravel is like this I don't know.
Thank you for your answer :)
