### ISSUE TITLE
Wouldn't be nice to have a @switch directive in Blade?

### ISSUE THREAD

**Issue by marcoskubis** [laravel/framework#14589]
Something like this:

    @switch($var)
        @case('value')
        // html
        @break
    @endswich

This will be much better than a lot of `@if` statements.

**Comment by BrandonSurowiec** [comment]
I'd rather `@if` or if the html blocks are huge, use an `@include("template.$var")` which pulls the right template. Seems shorter and easier to understand IMO.

**Comment by marcoskubis** [comment]
@BrandonSurowiec nice aproach. Thanks!

**Comment by BrandonSurowiec** [comment]
@marcoskubis My pleasure.
