### ISSUE TITLE
route prefix on 5.3

### ISSUE THREAD

**Issue by cargie** [laravel/framework#14593]
route prefix wont prepend on resource name anymore. is it intended? or what is the other workaround for it? Thanks

**Comment by KarimGeiger** [comment]
Yes, this seems to be intended. See the [Upgrade Guide](https://laravel.com/docs/master/upgrade#upgrade-5.3.0) for information about that:

> ## Resource Route Names No Longer Affected By Prefixes
>
> URL prefixes no longer affect the route names assigned to routes when using Route::resource, since this behavior defeated the entire purpose of using route names in the first place.
>
> If your application is using Route::resource within a Route::group call that specified a prefix option, you should examine all of your calls to the route helper and verify that you are no longer appending the URI prefix to the route name.
>
> If this change causes you to have two routes with the same name, you may use the names option when calling Route::resource to specify a custom name for a given route. Refer to the resource routing documentation for more information.

**Comment by cargie** [comment]
Thank you

**Comment by lchogan** [comment]
I don't understand how a prefix defeats the purpose of route resources. I have a number of resources with a superadmin prefix. Now I have to spell out each resource name individually like this?

`Route::resource(user', 'SuperAdmin\UserController', ['names' => [
    'create' => 'superadmin.user.create',
    'edit' => 'superadmin.user.edit',
    'show' => 'superadmin.user.show',
    'update' => 'superadmin.user.update',
    'destroy' => 'superadmin.user.destroy',
]]);`

**Comment by cargie** [comment]
yeah. . prepending route prefix is very well handy

**Comment by paceband** [comment]
Using Laravel 5.3.9
See comment from "john5db commented on 6 Jul • edited" from https://github.com/laravel/framework/issues/13903..
It describes perfectly the problem.
