### ISSUE TITLE
Reuse translations in Laravel 5.2

### ISSUE THREAD

**Issue by JeroenSteen** [laravel/framework#14602]
I'm wondering if it's possible to reuse Localization translations in Laravel 5.2. So something like this:

```
//resources/lang/en/global.php
return [
 'brand' => 'Github',
 'my'    => 'My :attribute',
 'my_brand' => trans('global.my', ['attribute' => trans('global.brand')])
];
```

Hope their is a way to reuse translations with Laravel.

**Comment by CupOfTea696** [comment]
Why not just use `trans('global.my', ['attribute' => trans('global.brand')])` in your code? It's really not that much longer...

You could use a closure for the `my_brand` value, but then you'd have to execute it when you grab it, Laravel doesn't automatically call closures for config values.

```php
//resources/lang/en/global.php
return [
 'brand' => 'Github',
 'my'    => 'My :attribute',
 'my_brand' => function () {
    return trans('global.my', ['attribute' => trans('global.brand')]);
  },
];
```

```html
<!-- resources/views/index.blade.php -->
{{ value(trans('global.my_brand')) }}
```

**Comment by JeroenSteen** [comment]
When I use the closure function, and value() it doesn't show the translation.
It shows only the text `global.my_brand` as output on the screen, what can it be? @CupOfTea696 
I use `{{ value(trans('global.my_brand')) }}` in a blade partial view that I include in a other blade file.

It would be cool if Laravel doesn't need value().

**Comment by CupOfTea696** [comment]
Right, looking some more at the source code, it looks like only string and array values are allowed in the locale files. A little hacky way to get around this is to wrap the closure in an array and then use `{{ value(head(trans('global.my_brand'))) }}`. Which is just needlessly complicated for what you are trying to achieve.

 Regardless, in my opinion Laravel shouldn't resolve Closures for localisation. `{{ trans('global.my', ['attribute' => trans('global.brand')]) }}` seems like a way better approach to your issue. Or you could even remote the attribute from your `global.my` key and just go `{{ trans('global.my')}} {{ trans('global.brand') }}`.
