### ISSUE TITLE
Can I use something else other than PDO with Laravel? [HHVM]

### ISSUE THREAD

**Issue by prime-ralph** [laravel/framework#14606]
Yes, I have heard how PDO is better than using something else, (have seen most saying PDO is better than mysqli) but given this circumstance I want to ask if I can elect to use a different DB driver interface (Um, is that what it is called?)

I tried to migrate our project API made with Laravel into HHVM, only to find that some of my queries from the database were no longer returning as typed.
I figured this might be an issue with HHVM's implementation of json_encode and JSON_NUMERIC_CHECK, but as I outlined in the tests I did [(Laravel's JSON responses > Numeric strings are not automatically encoded as numbers even as JSON_NUMERIC_CHECK was used)](https://github.com/facebook/hhvm/issues/7251), HHVM actually returned the results as typed.

**Comment by GrahamCampbell** [comment]
Laravel recommends using PHP 7.0, not HHVM. Infact, Laravel 5.3 is officially dropping support for HHVM. If there are any HHVM bugs affecting L5.1 or 5.2, it really is up to facebook to fix this.

**Comment by prime-ralph** [comment]
Oh... I understand. Thanks for the info!

**Comment by prime-ralph** [comment]
Oh... I understand. Thanks for the info!
