### ISSUE TITLE
Missing argument 1 for Illuminate\Auth\Notifications\ResetPassword::message()

### ISSUE THREAD

**Issue by CDOLago** [laravel/framework#14603]
Fresh installation of Laravel 5.3, ran `php artisan make:auth`, registered new account, tried to do a password reset and got this error:

> ErrorException in ResetPassword.php line 44:
> Missing argument 1 for Illuminate\Auth\Notifications\ResetPassword::message(), called in MyApp\vendor\laravel\framework\src\Illuminate\Notifications\ChannelManager.php on line 49 and defined

**Comment by srmklive** [comment]
It seems to me you didn't setup the mail credentials properly.

**Comment by srmklive** [comment]
@GrahamCampbell I just tested this for 5.3. I can confirm this issue is occurring.

**Comment by crynobone** [comment]
This issue is valid and are due to https://github.com/laravel/framework/commit/78afcd9959858af68c4fb45c3998c5b267a055de

**Comment by srmklive** [comment]
@crynobone exactly.

**Comment by crynobone** [comment]
The problem right now `$notification->message()` is build for all `$notifiables` (collection of `User`), which going to make it hard to customise message to each user, and for `ResetPassword` example, we would have problem accessing `$notifiable->email` (used to generate reset password URL).

**Comment by srmklive** [comment]
Issue has been fixed in latest update for 5.3
