### ISSUE TITLE
`bootstrap/cache` location

### ISSUE THREAD

**Issue by salarmehr** [laravel/framework#14619]
Isn't `storage` directrory intended to store all files generated by the framework.. So, why `bootstrap/cache` is not placed there? This make installing and configing the framwork more complicate on linux.

**Comment by crynobone** [comment]
If you're looking to have some sort of deployment without downtime, that would mean that storage would be shared between build while `bootstrap/cache` actually isn't. It's similar to your `vendor` folder which is specific to each deployment.

**Comment by salarmehr** [comment]
@crynobone May you please explain more?

**Comment by GrahamCampbell** [comment]
Feel free to discuss on slack/forums. :)
