### ISSUE TITLE
Warning when use Laravel with PHP-Event extension

### ISSUE THREAD

**Issue by Theremsoe** [laravel/framework#14617]
When running **Artisan** with the extension **PHP Event** enabled you can get this problem: 

`````
[ErrorException]
Cannot declare class Event, because the name is already in use 
`````

The problem is a collision of class names. Write this if someone comes to have this problem.

Thanks

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. You just need to rename or remove the alias to `Event` in your `config/app.php` file.
