### ISSUE TITLE
belongsTo relationship returns null

### ISSUE THREAD

**Issue by lordadamson** [laravel/framework#14626]
I have a table called Locins (locations) which has a foreign key to another table called Rgn (regions).

So in my Locin model:
```
class Locin extends Model
{
    protected $table = 'Locin';

    protected $primaryKey = 'Locin_id';

    public $timestamps = false;

    public function Rgn()
    {
        return $this->belongsTo('App\Models\Rgn', 'RgnID', 'RgnID');
    }
}
```
and in my Rgn Model:
```
class Rgn extends Model
{
    protected $table = 'Rgns';

    protected $primaryKey = 'RgnID';

    public $timestamps = false;

    public function Locin()
    {
        return $this->hasOne('App\Models\Locin', 'RgnID', 'RgnID');
    }

}
```
When I say: $location = Locin::find($request->Locin); a location is returned successfully. (I var_dumped it).

But then when I say $location->Rgn it returns null.

Tables structure:

Locins Table: [Locin_id (primary key), RgnID (foreign key), other unrelated fields].

Rgns Table: [RgnID (primary key), other unrelated fields]

I tested the query:
```
\DB::connection()->enableQueryLog();
$location = Locin::find(1);

$region = $location->Rgn;

$query = \DB::getQueryLog();
$lastQuery = end($query);

dd($lastQuery);
```
and this is what I got:
```
array:3 [▼
  "query" => "select * from `Rgns` where `Rgns`.`RgnID` = ? limit 1"
  "bindings" => array:1 [▼
    0 => 0
  ]
  "time" => 3.19
]
```
So a `?` as the RgnID :/

**Comment by morloderex** [comment]
@lordadamson This is because you have set the third parameter wrong :) 
This third parameter is a reference to the primary key on the model you are attaching from is that makes sense.

The secound parameter references to the foreign_key on the other table you are trying to the retrieve. 

If you need anymore help then find me on larachat slack channel :)

**Comment by lordadamson** [comment]
Actually the third parameter was correct. It turns out that the stupid seed in the DB had a foreign key for an entry that does not exist.
I am tired of getting stuck on silly things. Sorry and have a good day.
