### ISSUE TITLE
Problem with JSON Where Clauses

### ISSUE THREAD

**Issue by Milewski** [laravel/framework#14622]
There is a bug fetching JSON in the query builder.. consider the following:

according with the [documentation](https://laravel.com/docs/5.2/queries#json-where-clauses) this should work

```
DB::table('users')->where('options->language', 'en')->get();
```

however on my application
```
Recipe::where("items->id", 1)->get()

//->toSql()
//"select * from `recipes` where `items`->"$.id" = ?"
//Response: [] <-- Empty Array (or empty collection for 5.3 releases :)

```

however the same query using whereRaw works

```
Recipe::whereRaw("items->\"$.id\" = 1")->get()

//->toSql()
//"select * from `game_item_recipes` where items->"$.id" = ?"
//Response: 
array:1 [▼
  0 => {#431 ▼
    +"id": 7
    +"items": "{"id": 1}"
    +"created_at": "2016-08-04 17:14:37"
    +"updated_at": "2016-08-04 17:14:37"
  }
]
```

the only difference between the where and whereRaw if i dump as sql are
```
//->whereRaw("items->\"$.id\" = 1")->toSql()
//->where("items->id", 1)->toSql()

"select * from `recipes` where items->"$.id" = ?"
"select * from `recipes` where `items`->"$.id" = ?"
```

**Comment by themsaid** [comment]
This is because in 5.2 we use `PARAM_STR` for all queries, this is ok for most of the time but in the case of JSON MySQL is type strict.

This is fixed in 5.3 by using the correct binding type.
