### ISSUE TITLE
Error with Illuminate\Foundation\Support\Providers\RouteServiceProvider

### ISSUE THREAD

**Issue by Azirius** [laravel/framework#14621]
```php
[ReflectionException]
Class Illuminate\Foundation\Support\Providers\Router does not exist
```

Simple solution would be to import:

```php
use Illuminate\Routing\Router;
```

Sorry I'm not submitting the bug fix myself, I just fumbled across the issue with using `$this->get` within my `App\Providers\RouteServiceProvider` which forwards a call on to `__call` which then attempts to pass it to the container and instantiate the router.

**Comment by GrahamCampbell** [comment]
A fix for this was recently merged. :)
