### ISSUE TITLE
redirect ->withErrors() from Exception Handler not working

### ISSUE THREAD

**Issue by GamBeaT** [laravel/framework#14634]
Laravel: 5.2
A longer while back I could use redirect()->withErrors() without a problem from Exception Handler. Now, the redirect is passed correctly, but withErrors() is not. I've tried to do dd(Session::all()); in the Exception handler but it returns me an empty array. 

Is it a bug or I simply should not be allowed to do that from exception handler ?

**Comment by GamBeaT** [comment]
There is only one session file in there.

**Comment by chrismpettyjohn** [comment]
I heard of issues where redirect wouldn't keep flashed sessions values (withErrors).  I been using the Redirect fascade in my controllers, and calling it by `Redirect::to('/page')->withMessage('Hey');`


Also, make sure you're using the web middleware for all of your routes as it starts the session handler

**Comment by GrahamCampbell** [comment]
This may not work if your session has not been started yet. This is the expected behaviour. One such case would be for 404s were no web middlewares are executed because the request gets rejected at the routing layer.
