### ISSUE TITLE
Can't retrieve invalid data from Validator

### ISSUE THREAD

**Issue by xxnoobmanxx** [laravel/framework#14646]
I am trying to get data that didn't pass on validation with `Validator->invalid()`

Here is my test:

    $data = [
        ['name' => 'John', 'age' => 30],
        ['name' => 'Robert', 'age' => 'nope'],
        ['name' => ['woops']]
    ];

    $validator = \Validator::make($data, [
        '*.name' => 'required|string|max:200',
        '*.age' => 'required|int'
    ]);

    dd($validator->invalid());

Expected:

    [
        ['name' => 'Robert', 'age' => 'nope'],
        ['name' => ['woops']]
    ]

But instead, I am getting an empty array. Is there something I'm doing wrong?

**Comment by themsaid** [comment]
@xxnoobmanxx I believe you need to submit the PR to this repository not illuminate/validation as it's a READ ONLY repo.

**Comment by xxnoobmanxx** [comment]
Thanks. Didn't notice it.

**Comment by themsaid** [comment]
I think the PR is still submitted to `illuminate/validation` not here.

**Comment by themsaid** [comment]
Oh, got it :) didn't see this one https://github.com/laravel/framework/pull/14651

**Comment by GrahamCampbell** [comment]
Thanks for reporting. :)

**Comment by xxnoobmanxx** [comment]
Hi. I just updated my project to the version released today (5.2.43), and these methods are still buggy. Can you please reopen this issue, or take a look at my [patch](https://github.com/laravel/framework/pull/14651/files), please? @GrahamCampbell

**Comment by themsaid** [comment]
@xxnoobmanxx the PR is not merged yet. If merged you'll be able to have the fix in the release that comes after.
