### ISSUE TITLE
URL not parsed when it starts with double slash

### ISSUE THREAD

**Issue by avirdz** [laravel/framework#14644]
I was trying to generate a URL with the url function sending a param which starts with double slash the url function just return the same param.

`$url = url('//uploads/brand_1/cWWvlh3JBn3k0HqA.mp4');`
`outputs: //uploads/brand_1/cWWvlh3JBn3k0HqA.mp4`

But i think this is not the real problem, cause I was forming that path with the following flow:

`$absolutePath = public_path('/uploads/brand_1/cWWvlh3JBn3k0HqA.mp4');`
`outputs: /home/user/dev/project/public//uploads/brand_1/cWWvlh3JBn3k0HqA.mp4`

Then in another method I move the file to another location and return its http url.

`return url(str_replace(public_path(), '', $absolutePath));`
`outputs: //uploads/brand_1/cWWvlh3JBn3k0HqA.mp4`

It will be nice if public_path(), storage_path(), config_path(), url() generate the path replacing the double slash to just one slash.

By now I'm replacing the public_path() and the double slash like this:

`return url(str_replace([public_path(), '//'], ['', '/'], $absolutePath));`
`outputs: https://localhost/project/uploads/brand_1/cWWvlh3JBn3k0HqA.mp4`

Using Laravel 5.2

**Comment by themsaid** [comment]
Why do you want to add `/` at the beginning of the path?

`public_path('uploads/brand_1/cWWvlh3JBn3k0HqA.mp4')` would solve your problem.

**Comment by avirdz** [comment]
I don't want to, but it came from the src attribute of a video tag, or img in case of an image
`<video src="/uploads/brand_1/cWWvlh3JBn3k0HqA.mp4"></video>`

This is not a big deal I know but in some cases it will helps. 
If the param for the url function starts with double slash and it's an invalid value, should not it throw an exception?

**Comment by fernandobandeira** [comment]
I think that it would be better for you to simply trim the '/' like so:

```php
public_path(trim('/uploads/brand_1/cWWvlh3JBn3k0HqA.mp4', '/'));
```

Because if you have a website that may be under https in some situations you may use the url starting with '//' for external requests so it's not a real 'invalid' url and thus some folks might be using it this way.

**Comment by avirdz** [comment]
You are right @fernandobandeira
