### ISSUE TITLE
Unexpected rules for digits and digits_between

### ISSUE THREAD

**Issue by itised** [laravel/framework#14647]
The digits and digits_between validation rules currently pass even when the value tested against contains characters that are not digits.

For example, if a rule "digits:4" is applied to the value "+1.2" the validation will pass.

I understand this is because the rule simply checks that the value is numeric and has a string length of 4, but that is a bit unintuitive for a rule named "digits" since half of the characters in the value are not digits at all.

If this is actually the intended behavior it would be nice to add a note to the documentation. If not, the fix would be very simple.

**Comment by themsaid** [comment]
A proposed fix was submitted, however it is targeting 5.3 since it might break the validation for some usages.

**Comment by sera527** [comment]
And now how to check the length of the fractional number?
