### ISSUE TITLE
$loop->index starts counting at 1

### ISSUE THREAD

**Issue by crnkovic** [laravel/framework#14674]
Cmon, we programmers start counting at 0 and everything is indexed at 0, why does this start at 1!? 

It's really bugging me!

**Comment by fernandobandeira** [comment]
IDK maybe the intention would be to create something like "1 record out of 15" obviously you could just ++ the index but as this may be created to solve that they preferred to default the start at 1.

**Comment by JayBizzle** [comment]
Yeah, `index` should have started at 0 and then have a variable called `iteration` for the current iteration count IMO, [similar to Smarty](http://www.smarty.net/docs/en/language.function.foreach.tpl#foreach.property.iteration)

**Comment by barryvdh** [comment]
Twig does the same thing; http://twig.sensiolabs.org/doc/tags/for.html
Which is handy for when you're trying to display a list to the user (because: views are for displaying, not logic mostly).
But twig also has a index0 value, which makes it more obvious / less awkward.

**Comment by JayBizzle** [comment]
`index` and `iteration` would have been a better option like [Smarty](http://www.smarty.net/docs/en/language.function.foreach.tpl#foreach.property.iteration)

**Comment by JayBizzle** [comment]
Fixed in #14706
