### ISSUE TITLE
Issue with RouteListCommand.php

### ISSUE THREAD

**Issue by Azirius** [laravel/framework#14679]
As per the documentation you can now have a so-called 'Single Action Controller', works perfectly during normal operations, however, while using Artisans `route:list` command I'm greeted with the error.

```php
[ErrorException]
Undefined offset: 1
```

This is due to the following method on `RouteListCommand`:

```php
    /**
     * Get the middleware for the given Controller@action name.
     *
     * @param  string  $actionName
     * @return array
     */
    protected function getControllerMiddleware($actionName)
    {
        Controller::setRouter($this->laravel['router']);
        $segments = explode('@', $actionName);
        return $this->getControllerMiddlewareFromInstance(
            $this->laravel->make($segments[0]), $segments[1]
        );
    }
```

Seems fairly simple to fix at first instance, but because I'm not familiar with bug-fixing other libraries and such (e.g. pull requests/testing), I thought I'd at least raise the issue, and couldn't find it previously referenced elsewhere.

=]

[hr]

Proposed fix

Replace 

```php
return $this->getControllerMiddlewareFromInstance(
    $this->laravel->make($segments[0]), $segments[1]
);
```

With

```php
return $this->getControllerMiddlewareFromInstance(
    $this->laravel->make($segments[0]),
    isset($segments[1]) ? $segments[1] : ''
);
```

Seems to sort it for me.

**Comment by GrahamCampbell** [comment]
Thanks for reporting. :)
