### ISSUE TITLE
[5.3] No longer able to set custom middleware for broadcast routes

### ISSUE THREAD

**Issue by mattmcdonald-uk** [laravel/framework#14690]
As of https://github.com/laravel/framework/commit/aa11df3a27057e5fdf45b4c1a32faac0f950e83a it's no longer possible to pass an attributes array to the routes method when setting up BroadcastServiceProvider.

This means you can't use a custom middleware group, it has to be the web middleware group.

**Comment by GrahamCampbell** [comment]
It's still possible to add other middleware by grouping first then calling this method.

**Comment by mattmcdonald-uk** [comment]
But what if you wanted to remove the web middleware?

**Comment by GrahamCampbell** [comment]
Yeh, that's why I opened this again. :)
