### ISSUE TITLE
[5.2] MySQL migrations with comments usign ANSI_QUOTES mode

### ISSUE THREAD

**Issue by schleumer** [laravel/framework#14709]
When using ANSI_QUOTES it's impossible to execute a migration that has comments on columns, because they are wrapped with double quotes, not with single quotes.

I made local changes on `Illuminate\Database\Schema\Grammars\MySqlGrammar` just to test my hipotesis, my tests with single quotes in comments worked with and without ANSI_QUOTES, so comments can be wrapped with single quotes.

The code from [`MySqlGrammar.php`](https://github.com/illuminate/database/blob/5.2/Schema/Grammars/MySqlGrammar.php#L778):
```
return ' comment "'.$column->comment.'"';
```

Became:
```
return " comment '".$column->comment."'";
```

I'll make a pull request soon if confirmed.

**Comment by themsaid** [comment]
Please go ahead and make a PR, it's better to discuss implementations and see how tests react to this :)
