### ISSUE TITLE
[5.3] PHP fatal error when launching Queue Worker

### ISSUE THREAD

**Issue by elasticsteve** [laravel/framework#14705]
My dev setup is Windows/XAMPP/PHP5.6/PHPStorm. I prefer the simplicity over PHPstorm + Vagrant/Homestead.

I want to use AWS SQS.

Yesterday I tried ```php artisan queue:work``` on a new Laravel 5.3 project and I received:

```
PHP Fatal error: Call to undefined function Illuminate\Queue\pcntl_fork() in E:\Dropbox\PhpStorm Projects\elastic1\vendor\laravel\framework\src\Illuminate\Queue\Worker.php on line 106

[Symfony\Component\Debug\Exception\FatalErrorException] Call to undefined function Illuminate\Queue\pcntl_fork()
```

These are lines 104-113 \vendor\laravel\framework\src\Illuminate\Queue\Worker.php:

``` 
protected function runNextJobForDaemon($connectionName, $queue, WorkerOptions $options)
    {
        if ($processId = pcntl_fork()) {
            $this->waitForChildProcess($processId, $options->timeout);
        } else {
            $this->runNextJob($connectionName, $queue, $options);

            exit;
        }
    }
```

After some investigation I found out that you can't have pcntl_fork() on PHP for Windows. I was like: What???

This completely broke my functioning dev setup, which took me a while to setup, because I also need SLL/HTTPS on my localhost for AWS/Stripe/Nexmo for testing and had to setup Apache in XAMPP to deal with this because ```php artisan serve``` can't do htpps.

After speaking with a few people and testing it myself, I learned that Laravel 5.2 doesn't use pcntl_fork() and I could launch a queue worker with no problem on my Windows dev setup.

The question is: Why all of a sudden use pcntl_fork() and cut out Windows users from an alternative workflow to Vagrant/Homestead, which honestly is not my preferred way of working? In fact I know nothing about getting PHPstorm/Homstead properly set up and found no proper tutorial anywhere to deal with the issues. It's not something I'm looking forward to, if I don't have to! This move to use a function that breaks Windows dev setups seems very counterproductive, unless you have a very particular reason.

thanks

**Comment by tomschlick** [comment]
pcntl_fork() is much more reliable especially for long running jobs. Homestead is the way to go if you want to mimic what a real production server would be like. Yes it takes a bit of work to get used to but it is well worth it in the end.

**Comment by theother1** [comment]
OFFTOPIC: I wish it would be documented somewhere how to set up Homestead on Windows together with PHPstorm. This is not easy at all!

And the fact that our production servers run Amazon Linux and Apache doesn't mimic what our product is like when running Homestead that runs on Ubuntu/nginx. I don't know Ubuntu nor nginx! Not happy! :-/

**Comment by tomschlick** [comment]
Amazon Linux is more similar to Ubuntu than Windows is though... 

Also there really isn't anything more to setting up PHPStorm & Homestead other than specifying a directory path... Are you looking for a specific thing?

**Comment by theother1** [comment]
thanks Tom!

I just don't understand the whole vagrant/homestead thing...

first ```vagrant box add laravel/homestead``` and then is says in the doc:
"You may install Homestead by simply cloning the repository. "

Might? Is this in option and when yes, what's the alternative? Why do I have to install laravel/homestead and then also clone a repo? This is really overwhelming for a newcomer and doesn't make a lot of sense... The whole concept is totally alien to me of what we are doing here.

Do I declare the PHPstorm project folder as shared folder for Homestead, or how are they synced? How does this work with several projects? I have to research this a little more... Also in terms of PHPstorm, what about the Vagrant options in the Tools menu? Can/should they be used for Homestead?

At the moment I create a new project in PHPstorm by "new composer project" or I copy a default Laravel project/template I already have. Now how would I deal with Homestead in this case?

I will see if I find something on Laracast, but I think it's kind of outdated...

Besides that I found a lot of conflicting ways/instruction how to setup PHPstorm when googling, none of them really convincing and overly complicated.

examples:
https://laracasts.com/discuss/channels/general-discussion/homestead-location-for-remote-php-phpstorm
http://blog.elenakolevska.com/debugging-laravel-on-homestead/

**Comment by morloderex** [comment]
@theother1 are you on larachat slack channel then pm me there i would love to help you out :) (goes under the same username as on github.)

**Comment by tomschlick** [comment]
The box you download is a preconfigured Ubuntu instance. The repo you clone is more of the setup scripts for your local configuration. So you download first, then run the repo config to customize your domain names, file paths, etc

PHPStorm over complicates the setup process because it's thinking you want to upload to a remote server not a local vagrant box. First click new project, then "Empty PHP Project" then select the folder path. You can do this even if you have existing files, it will just confirm that you want to use those. 

From there you tell it the language version you want (5.5/5.6/7.0/7.1) and then choose the Homestead box as the interpreter (you may have to add this first, cant remember).

You can use one vagrant box for multiple sites or you can have multiple boxes that you spin up / down depending on the project you're working on. It really just depends on your workflow and your computer's available resources.

In all, I would just tackle these issues one by one so you don't feel so overwhelmed. Focus on getting vagrant running, then the app displaying, then tackle any issues with PHPStorm after. Once you make some progress it won't feel so crazy.

**Comment by elasticsteve** [comment]
@morloderex thanks! Maybe tomorrow. I going to read up a bit on the subject first. Changed my user to elasticsteve here on github so it's in line with Slack and Laracast.

**Comment by elasticsteve** [comment]
@tomschlick Thanks Tom! does Homestead run out of the box with SSL/HTTPS? I guess not, right? Probably have to create a self-signed certificate for the test domain. This is not often discussed, but I'm wondering how everyone is working with test/Stripe and testing AWS SQS or Nexmo from a dev setup. You need HTTPS to communicate with it.

Would be nice if somebody wrote instructions for it.

**Comment by elasticsteve** [comment]
Got Vagrant/Homestead up and running. Cost me a day or two to figure it all out, but I guess it was worth it. It's actually a very nice workflow with the synced folders and all.

**Comment by tomschlick** [comment]
👍
