### ISSUE TITLE
illuminate/database not synced

### ISSUE THREAD

**Issue by melloc01** [laravel/framework#14713]
Hi,
I'm using `illuminate/database` repository on a project.
I think the illuminate repository is lacking a `git tag` so it can get the right version on `composer update`.

5.2: https://github.com/illuminate/database/blob/5.2/Query/Processors/PostgresProcessor.php 
Tagged: https://github.com/illuminate/database/blob/v5.2.37/Query/Processors/PostgresProcessor.php

I'd tag but I'm not sure the naming convention you're following there.
Thanks! :grin:

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. Yeh, our subsplit tags do lag behind. A new tag will be there at some point.
