### ISSUE TITLE
BootstrapThreePresenter no language file usage

### ISSUE THREAD

**Issue by mmjjb** [laravel/framework#14729]
In Laravel 5.1, render method is not calling the language labels but using build in / forced labels

Illuminate/Pagination/BootstrapThreeNextPreviousButtonRendererTrait.php: & Illuminate/Pagination/BootstrapFourNextPreviousButtonRendererTrait.php

Insert in getPreviousButton 

`
        if (trans('pagination.previous')) {
        	$text = trans('pagination.previous');
        }
`

 getNextButton
`
        if (trans('pagination.next')) {
        	$text = trans('pagination.next');
        }
`

Orginal post: https://stackoverflow.com/questions/32553340/customize-next-and-previous-pagination-button-in-laravel-5

**Comment by themsaid** [comment]
Please feel free to open a Pull Request.

Closing this since it's not really a bug report :)
