### ISSUE TITLE
Could you make it laravel 5.1 support querying JSON column types in databases, please?

### ISSUE THREAD

**Issue by Mahdidridi** [laravel/framework#14737]

**Comment by BrandonSurowiec** [comment]
This won't happen as backporting a feature is not part of the LTS (Long Term Support) policy.

From https://laravel.com/docs/5.1/releases#support-policy
> For LTS releases, such as Laravel 5.1, bug fixes are provided for 2 years and security fixes are provided for 3 years. These releases provide the longest window of support and maintenance. For general releases, bug fixes are provided for 6 months and security fixes are provided for 1 year.

Your only option is to upgrade to 5.2. If you don't want to do most of the upgrade yourself, you can use https://laravelshift.com to handle the majority of the upgrade process.
