### ISSUE TITLE
Model Directory

### ISSUE THREAD

**Issue by finchcn** [laravel/framework#14730]
Please fix laravel project to create model directory in app dir.
And fix framework to create Model in model directory when use artisan make:model
I use 5.2 framework now

**Comment by zaknes** [comment]
This has been requested and answered so many times. I'll just say that this is not going to happen.

Classes that extend Eloquent's base Model class are stored in the `app` directory by default.

If you want to move them, you may.

**Comment by mikerockett** [comment]
See [this pull request](/laravel/laravel/pull/3821) for Taylor's reasoning behind not using a models directory and namespace. And see [this comment](/laravel/laravel/pull/3821#issuecomment-228748576) for how to use a model directory and namespace if you want to do it that way.
