### ISSUE TITLE
Request->only makes up items

### ISSUE THREAD

**Issue by OskarD** [laravel/framework#14734]
The documentation for the `only` method inside `Illuminate\Http\Request` reads: 

> Get a subset of the items from the input data.

This is not true, because if you pass a key that is not present in the request's attributes, it is still returned (Although as `null`).

Example:
```
$request->all(); // ['a' => 1]
$request->only(b); // ['b' => null]
```

Not only is this unintended as far as documentation goes, but it is also confusing as the `Illuminate\Database\Collection` class's `only()` method works differently (As expected). 

It also creates a problem for me when I want to use `$user->fill($request->only(['a', 'b']))` and `b` is only present sometimes. This causes `b` to be set to null when it isn't present in the form.

I propose that the method is altered so it behaves like `Illuminate\Database\Collection` and does not return null values for missing fields.

**Comment by OskarD** [comment]
@GrahamCampbell even though this is intentional (As you explained in the PR), perhaps the documentation should be more clear as to what the method does?

**Comment by GrahamCampbell** [comment]
We're open to PRs to the docs. :heart:
