### ISSUE TITLE
Strict mode true causes QueryException with Eloquent groupBy

### ISSUE THREAD

**Issue by gjrdiesel** [laravel/framework#14755]
```php
\App\User::firstOrCreate(['name'=>'Test1','email'=>'Test1', 'password'=>'12348590']);

$users = \App\User::groupBy('name')->get();

dd($users);
```

Throws an `QueryException`

```sql
SQLSTATE[42000]: Syntax error or access violation: 1055 'ltest.users.id' isn't in GROUP BY (SQL: select * from `users` group by `name`)
```

Easily can negate the message by setting strict mode to false in `config/database.php` but seeing as 5.3 enables it by default I thought I'd bring it to light.

**Comment by thecrypticace** [comment]
This is not a bug. This happens because of a specific and intentional restriction of strict mode in MySQL ≥ 5.7

http://dev.mysql.com/doc/refman/5.7/en/group-by-handling.html

**Comment by gjrdiesel** [comment]
Right I get it, strict mode wants only the columns you're selecting in group by, which you could do with.

```php
User::groupBy('name')->get(['name']);
```

or 

```php
\App\User::groupBy('name','email')->get(['name','email']);
```

Closing the issue.
