### ISSUE TITLE
Auth::user() return Null value after redirection

### ISSUE THREAD

**Issue by romal4u** [laravel/framework#14758]
I am using laravel version 5.1 and I found strange issue in it. I found that after login when my page redirect to another page at that time session has been lost and again redirect it to login page.

**Comment by GrahamCampbell** [comment]
Sounds like a bug in your setup. Please feel free to browse through the other issues and/or ask on the forums. Make sure you have a favicon.ico since browsers will often try to request that and end up starting a new session.
