### ISSUE TITLE
[5.2] Jobs all failing after upgrade

### ISSUE THREAD

**Issue by mcblum** [laravel/framework#14751]
Just updated to the latest 5.2.* and all jobs that were working are now failing. The error message for each is the same:

`[2016-08-10 20:26:13] local.ERROR: InvalidArgumentException: No handler registered for command [App\Jobs\QueueImageForDeletion] in /www/Hoshi/api-hoshi.nationalmachine.co/vendor/laravelcollective/bus/src/Dispatcher.php:348
Stack trace:
#0 /www/Hoshi/api-hoshi.nationalmachine.co/vendor/laravelcollective/bus/src/Dispatcher.php(311): Collective\Bus\Dispatcher->inflectSegment(Object(App\Jobs\QueueImageForDeletion), 0)
#1 /www/Hoshi/api-hoshi.nationalmachine.co/vendor/laravelcollective/bus/src/Dispatcher.php(295): Collective\Bus\Dispatcher->getHandlerClass(Object(App\Jobs\QueueImageForDeletion))
#2 /www/Hoshi/api-hoshi.nationalmachine.co/vendor/laravelcollective/bus/src/Dispatcher.php(203): Collective\Bus\Dispatcher->resolveHandler(Object(App\Jobs\QueueImageForDeletion))
#3 [internal function]: Collective\Bus\Dispatcher->Collective\Bus\{closure}(Object(App\Jobs\QueueImageForDeletion))
#4 /www/Hoshi/api-hoshi.nationalmachine.co/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(150): call_user_func(Object(Closure), Object(App\Jobs\QueueImageForDeletion))
#5 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\QueueImageForDeletion))
#6 /www/Hoshi/api-hoshi.nationalmachine.co/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(App\Jobs\QueueImageForDeletion))
#7 /www/Hoshi/api-hoshi.nationalmachine.co/vendor/laravelcollective/bus/src/Dispatcher.php(212): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#8 /www/Hoshi/api-hoshi.nationalmachine.co/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(41): Collective\Bus\Dispatcher->dispatchNow(Object(App\Jobs\QueueImageForDeletion))
#9 /www/Hoshi/api-hoshi.nationalmachine.co/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(130): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\DatabaseJob), Array)
#10 /www/Hoshi/api-hoshi.nationalmachine.co/vendor/laravel/framework/src/Illuminate/Queue/Jobs/DatabaseJob.php(49): Illuminate\Queue\Jobs\Job->resolveAndFire(Array)
#11 /www/Hoshi/api-hoshi.nationalmachine.co/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(213): Illuminate\Queue\Jobs\DatabaseJob->fire()
#12 /www/Hoshi/api-hoshi.nationalmachine.co/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(156): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), '0', '0')
#13 /www/Hoshi/api-hoshi.nationalmachine.co/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(125): Illuminate\Queue\Worker->pop('', 'default', '0', '3', '0')
#14 /www/Hoshi/api-hoshi.nationalmachine.co/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(78): Illuminate\Queue\Console\WorkCommand->runWorker('', 'default', '0', '128', false)
#15 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#16 /www/Hoshi/api-hoshi.nationalmachine.co/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#17 /www/Hoshi/api-hoshi.nationalmachine.co/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#18 /www/Hoshi/api-hoshi.nationalmachine.co/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /www/Hoshi/api-hoshi.nationalmachine.co/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /www/Hoshi/api-hoshi.nationalmachine.co/vendor/symfony/console/Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /www/Hoshi/api-hoshi.nationalmachine.co/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /www/Hoshi/api-hoshi.nationalmachine.co/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /www/Hoshi/api-hoshi.nationalmachine.co/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /www/Hoshi/api-hoshi.nationalmachine.co/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 {main}  `

Any idea what might be going on?

**Comment by GrahamCampbell** [comment]
Laravel 5.2 dropped support for non-self handling jobs.

**Comment by GrahamCampbell** [comment]
Your stack trace shows laravel collective. Please report this to them. :)

**Comment by mcblum** [comment]
Oh man. Thank you, thank you thank you. Three hours on this. In case anyone else has the same issue, I had installed a different package a bit ago (an Excel import / export package) and it mentioned needed to add collective's bus provider. That's why it wasn't using the new one that was implemented in 5.2. 

Thanks @GrahamCampbell
