### ISSUE TITLE
Deprecate slow Str::quickRandom method

### ISSUE THREAD

**Issue by rimace** [laravel/framework#14762]
I tested the Str::quickRandom and Str::random methods like this:

	$start = new Carbon\Carbon();
	for($i = 0; $i < 1000000; $i++) {
		$val = Illuminate\Support\Str::quickRandom();
	}
	$diffQuickRandom = (new Carbon\Carbon())->diffInSeconds($start);
	
	$start = new Carbon\Carbon();
	for($i = 0; $i < 1000000; $i++) {
		$val = Illuminate\Support\Str::random();
	}
	$diffRandom = (new Carbon\Carbon())->diffInSeconds($start);
	
	echo "Str::quickRandom(): ".$diffQuickRandom." seconds";
	echo " / Str::random(): ".$diffRandom." seconds";

I turns out that the quickRandom method is much slower than the random method. I get the following results on PHP 7: `Str::quickRandom(): 12 seconds / Str::random(): 3 seconds`

Currently I don't see any reason for having a quickRandom method which is actually slower and less secure than the random method, so I propose to deprecate the quickRandom method, as it is not used by the Framework.
Alternatives would be to rename the method (as the current name gives the impression that it would be faster in some way) or to find a way to make it faster.

**Comment by GrahamCampbell** [comment]
I can't replicate this. For me I have:

```
>>> echo "Str::quickRandom(): ".$diffQuickRandom." seconds";
Str::quickRandom(): 9 seconds⏎
=> null
>>> echo " / Str::random(): ".$diffRandom." seconds";
 / Str::random(): 10 seconds⏎
=> null
```

**Comment by GrahamCampbell** [comment]
Maybe we just need to improve the quick random implementation to make it as fast as possible?

**Comment by GrahamCampbell** [comment]
Hmm, but when I ask for 100 characters instead of the default of 16, quick random does appear to be much slower. Quick random at 38 seconds vs 16 seconds from the slow random generator.

**Comment by GrahamCampbell** [comment]
If we replace quickRandom with:

```php
str_shuffle(substr(str_repeat(md5(mt_rand()), ceil($length / 32)), 0, $length));
```

Then it completes in 4 seconds. It doesn't cover the same result space as the original, but it is a strict subset, so is probably good enough. D'no how people feel about this.

**Comment by rimace** [comment]
Yep, it really makes it much faster (about 7 times faster than random on my system now).

**Comment by sisve** [comment]
Are people really calling quickRandom 1 000 000 times in tight loops in actual production code?

**Comment by rimace** [comment]
If so, they're using the slow version anyway and nobody noticed it. The most likely thing I can imagine is creating many models for a test instance (even so one million is really much (I tend to create a few hundreds)). The random method wouldn't be that thing that slows the process down. So I'd really call this a micro-optimization. That's why I proposed to deprecate quickRandom and let them use the random version.

**Comment by GrahamCampbell** [comment]
Well, there's a difference between pseudo random generation and cryptographically secure random generation. For most applications, it does not need to be cryptographically secure. We basically just need to find a fast non-crypto secure generator and use that in quickRandom.

**Comment by GrahamCampbell** [comment]
See https://github.com/laravel/framework/pull/14780.
