### ISSUE TITLE
Add `split`method to collection

### ISSUE THREAD

**Issue by freekmurze** [laravel/framework#14763]
I think [this split macro](https://github.com/spatie/laravel-collection-macros/blob/1.1.0/src/macros.php#L89-L100)  is generic enough to be included as a function in the `Illuminate\Support\Collection` class.

If you agree, I'll whip up a PR.

**Comment by themsaid** [comment]
Seven likes! looks like you could make a PR then :)

Closing this since I have to :D but please create a PR when you have time :)
