### ISSUE TITLE
[5.3] "function_exist" error

### ISSUE THREAD

**Issue by oyed** [laravel/framework#14765]
https://github.com/laravel/framework/commit/5f554dea6833ddc9fa21bc95a0d553b49b2765dc

This is giving an error - I presume it should be "function_exists()"?

`[Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to undefined function Illuminate\Queue\Console\function_exist()`

**Comment by GrahamCampbell** [comment]
Fixed, Sorry about that!
