### ISSUE TITLE
Make laravel validator less monolithic structure

### ISSUE THREAD

**Issue by Skysplit** [laravel/framework#14773]
Currently laravel `Validation` class in my opinion is too monolithic structure.  
This makes it hard to extend/replace single validation rule without replacing `Validator` and `ValidationServiceProvider`.

In my opinion it would be better if validation rules are split into seperate classes that implement `ValidationRule` contract.

I find [Yii2 validation](https://github.com/yiisoft/yii2/blob/b30b5a99ea0a00c0a57839fe88658f0437406dab/framework/validators/Validator.php#L55) class being built in much cleaner way than it currently is in laravel.

**Comment by GrahamCampbell** [comment]
Thanks, but we don't process proposals here. Please see our contribution guidelines. :)

**Comment by Skysplit** [comment]
@GrahamCampbell Sorry for posting in wrong place. I read the contribiution guidelines, but it seems I missed most important part that I was looking there for. Thank you.
