### ISSUE TITLE
Illiminate/database SQLite update fails on selecting column

### ISSUE THREAD

**Issue by JABirchall** [laravel/framework#14784]
In a small project I have been working on I have a rather ugly line of code to check the version of a plugin for the project. before solving my issue by removing the column selector eloquent could not update a row if I was a selecting A column.

example code
Table create

    Manager::schema()->create('plugins', function(Blueprint $table) {
        $table->increments('id');
        $table->text('name');
        $table->text('version');

        $table->timestamps();
    });

Model

    namespace Plugin\Models;
    
    use Illuminate\Database\Eloquent\Model;
    
    class Plugin extends Model
    {
        protected $fillable = ['name', 'version',];
    }

added some data

    Plugin::create([
        'name' => 'Nimda',
        'version' => 0.9.0,
    ]);

Fetching plugin version info to compare and deem if an update is needed.

    if (version_compare(($nimda = Plugin::select('version')->where('name', 'Nimda')->first())->version, 0.9.1, '<')) {
        $nimda->update(['version' => 0.9.1]);
        dd($nimda)

    }

when dumping the model it shows it was updated, when checking the database it was not updated. This was fixed by removing the select(), though I still think this is a bug because i can think of many other sanarios where you may want to fetch specific columns from a database and update them. I do not know if this is limited to just SQlite, or if it effects other drivers.

Version: v5.2.32

**Comment by themsaid** [comment]
The problem here is that by doing `select('version')`, and since the primary key column isn't selected laravel won't be able to target the DB record in the query.

You should always grab the primary key when querying a model in this case where you need to update/delete it later.
