### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by alexvanvliet** [laravel/framework#14796]
First of all, I'm sorry if it shouldn't be posted here but I don't really know where to post this

On the notification doc page : https://laravel.com/docs/master/notifications 
Where it explains Custom Channels

At the start of the first doc block, there is 

```
<?php

use App\Channels;
```

Shouldn't it be : 
```
<?php

namespace App\Channels;
```

**Comment by alexbowers** [comment]
A pull request can be made on the `laravel/docs` repository. 

https://github.com/laravel/docs

**Comment by alexbowers** [comment]
I've made one here: https://github.com/laravel/docs/pull/2490
