### ISSUE TITLE
[5.3] ProcessTimedOutException when calling queue:listen

### ISSUE THREAD

**Issue by ryantbrown** [laravel/framework#14792]
When I run `php artisan queue:listen sqs` I get the following error:

`[Symfony\Component\Process\Exception\ProcessTimedOutException]`                                                                                                                   
`The process "'/usr/bin/php7.0' 'artisan' queue:work 'sqs' --queue='grin-market-1' --delay=0 --memory=128 --sleep=3 --tries=0 --env='local'" exceeded the timeout of 60 seconds.`

The timeout occurs when the process reaches the `--timeout` value, whether any jobs are being fired or not.  Jobs that fire before the timeout are working properly, but the process dies when the `--timeout` is reached. 

I did not see any other issues related to this specifically. Also, its entirely possible I am doing something wrong, but I have used queues many times with Laravel 5.2 and below without incident.

**Comment by GrahamCampbell** [comment]
Does this only happen on sqs please?

**Comment by ryantbrown** [comment]
This is happening with beanstalkd, redis and sync drivers as well. Jobs fire correctly with all 4 drivers when they are processed before the timeout.

![screen shot 2016-08-12 at 11 02 42 am](https://cloud.githubusercontent.com/assets/5937034/17632290/5edd76ec-607c-11e6-8e31-3950cc0da663.png)

**Comment by GrahamCampbell** [comment]
Odd, I can't replicate this. What version of PHP are you using please?

**Comment by GrahamCampbell** [comment]
Wait, isn't this correct. You're meant to call work, not listen.

**Comment by ryantbrown** [comment]
Homestead with PHP PHP 7.0.8-2+deb.sury.org~xenial+1.

The listen command calls work underneath. Running work results in the same issue

**Comment by GrahamCampbell** [comment]
Oh, I see why this is happing. We were meant to pass through `--once` to the work command to make it process exactly one job.

**Comment by ryantbrown** [comment]
Ok so if I call work with --once on my end this will be resolved for now?

**Comment by GrahamCampbell** [comment]
No. It's an internal command we're calling.

**Comment by ryantbrown** [comment]
Never mind I see the problem. I can fix it for now and then update later

**Comment by GrahamCampbell** [comment]
Fixed in https://github.com/laravel/framework/commit/d0bc401b7384ae4b63adcfdaddbd415c4394e3d3. :)

**Comment by ryantbrown** [comment]
Word thanks

**Comment by GrahamCampbell** [comment]
Thanks for reporting! :heart:
