### ISSUE TITLE
[5.3] Facade Auth doesn't work in Controller __construct() method.

### ISSUE THREAD

**Issue by ac1982** [laravel/framework#14825]
Directly follow my codes:
```
class ConsoleController extends Controller
{
    public $user,$role;

    public function __construct(Request $request)
    {
        $this->user = $request->user();
        $this->role='Works';
    }

    public function index(Request $request)
    {
        var_dump($this->user);                //null
        var_dump($this->role);                //string 'Works';
        dd($request->user());                  //instant of the authenticated user
    }
}
```

**Comment by GrahamCampbell** [comment]
You cannot read the user in the constructor.

**Comment by ac1982** [comment]
I think that would be in document.

**Comment by sedhossein** [comment]
hi, the fecades in laravel called after controllers and for this reason, 

` $request->user() `

that is for auth, don not work,

can make inline midlleware or share your variable in boot method in appServiceProviders.
i find an example in below link
[here](https://josephsilber.com/posts/2017/01/23/getting-current-user-in-laravel-controller-constructor)

good luck .
