### ISSUE TITLE
[5.2] Eloquent nests orWhere scopes

### ISSUE THREAD

**Issue by segadora** [laravel/framework#14829]
When calling custom scopes it is expected that the or in the custom scope is used.

Currently it changes the query to `and`.

Call:

```
Model::orIsUp()->orIsDown();
```

Scopes:

```
    public function scopeOrIsDown($query)
    {
        return $query->orWhere('status', 'down');
    }

    public function scopeOrIsUp($query)
    {
        return $query->orWhere('status', 'up');
    }
```

Result:

```
select * from "eloquent_builder_test_scope_stubs" where ("status" = ?) and ("status" = ?)
```

Expected:

```
select * from "eloquent_builder_test_scope_stubs" where "status" = ? or "status" = ?
```

Pull request:
https://github.com/laravel/framework/pull/14828

Commit which makes the issue:
https://github.com/laravel/framework/commit/b5db61cd08bffbb504a45c494650b70ef09119c2

**Comment by acasar** [comment]
@segadora This is expected behavior in 5.2 and has been changed in 5.3 to work as you expect. WE can't change it in 5.2 since it's a breaking change.

Check the upgrade guide: https://www.laravel.com/docs/master/upgrade#upgrade-5.3.0

> Eloquent scopes now respect the leading boolean of scope constraints. For example, if you are starting your scope with an orWhere constraint it will no longer be converted to normal where. If you were relying on this feature (e.g. adding multiple orWhere constraints within a loop), you should verify that the first condition is a normal where to avoid any boolean logic issues.

**Comment by segadora** [comment]
Okay, thank you @acasar
