### ISSUE TITLE
Incorrect database entry with sqlite

### ISSUE THREAD

**Issue by thetodd** [laravel/framework#14843]
I'm using sqlite for testing with Laravel 5.3. When you save a model with a string attribute to the database and the string value starts with a zero, the attribute is saved without this leading zero.

```php
Schema::create('customers', function (Blueprint $table) {
    $table->increments('id');
    $table->string('zipcode', 5);
    $table->timestamps();
});
```

```php
public function testCreateNewCustomer()
{
    $customer = App\Customer::create(['zipcode' => '01234']);
    $this->seeInDatabase('customers', $customer->toArray());
}
```

With a mysql database this creates a valid entry.

**Comment by GrahamCampbell** [comment]
Thanks, but this is a duplicate. I can't remember the original issue off hand, but it is very recent, so you should be able to find it.
