### ISSUE TITLE
TokenMismatchException when uploading a file

### ISSUE THREAD

**Issue by Spharian** [laravel/framework#14842]
Hi,

Whenever I try to upload a file bigger than the `upload_max_filesize` configured into `php.ini`, I get a `TokenMismatchException`. If I disable the `VerifyCsrfToken` middleware, the `$request->file('name')` is `null`.

If I upload a file with a correct size, everything works fine.

**Comment by brunogaspar** [comment]
I believe this is an issue that comes way back since Laravel 4 and probably Laravel 3.

Try to follow what's described here http://stackoverflow.com/a/32294028 and see if the issue is fixed for you, or not.

> Note: This is also a duplicate of other issues that got closed already, but i don't remember if there were any valid solutions, a bit lazy to search.

**Comment by Spharian** [comment]
Increasing the `upload_max_filesize` is surely the working solution, but I think a clean exception should throw.

**Comment by patrickcarlohickman** [comment]
There's a middleware for that, but you have to add it to your kernel yourself. The middleware is at `Illuminate\Foundation\Http\Middleware\VerifyPostSize`, and it throws a `Illuminate\Http\Exception\PostTooLargeException`.
