### ISSUE TITLE
[5.3] Implicit Route Model Binding doesn't work with `Use` statements

### ISSUE THREAD

**Issue by BrandonSurowiec** [laravel/framework#14847]
In a controller, it's not uncommon to import a class up top.

```
use App\Forum\Post;

public function index(Post $post) {
    // returns an empty model
}
```

But currently you have to specify the full class in the call to make it work:

```
public function index(\App\Forum\Post $post) {
    // returns model for id 1
}
```

Is it possible to improve model binding to work nicely with use statements? This controller is being called through the API middleware with the new bindings middleware.

**Comment by GrahamCampbell** [comment]
That doesn't sound right. Please check your code for typos.

**Comment by GrahamCampbell** [comment]
Laravel does nothing in terms of resolving imports. PHP does that.

**Comment by BrandonSurowiec** [comment]
You're absolutely right. Missing `api` middleware. In the middle of upgrading and moving things around. Sorry for the trouble, thanks ;)
