### ISSUE TITLE
Laravel API documentation: mixed return values

### ISSUE THREAD

**Issue by michaeldzjap** [laravel/framework#14845]
I am trying to neatly handle my program control flow in case `Queue::push()` might fail, but to my surprise the Laravel API documentation only says 'return value: mixed'. Now it would be much more helpful if the documentation would give a more descriptive hint about what kind of value is being returned. My guess is it will be either a boolean or an exception, but I am not 100% sure. Is it possible to make this more explicit throughout the documentation?

Thanks in advance.

**Comment by miscbits** [comment]
The docs have returns mixed because the return can be changed based on whatever you push as a job. I don't think it would be possible to write out all the return values that can happen. adding in some example returns might be more misleading than helpful. 

I would suggest reading more about how jobs work or asking for help with your issue in particular.

**Comment by michaeldzjap** [comment]
Thanks for your answer. I'm still not really sure what I can expect to be returned after reading up on jobs some more. I'm developing something for Laravel 4.2, which requires a job that performs some simple things (db manipulations). So in my `run()` I will just have some simple db queries, which could potentially cause an exception to be thrown (they shouldn't, but you never know). So would it be right to assume that if I wrap my `Queue::push()` call in a `try/catch` block I will be able to catch this exception? Or would it be cleaner to use `Queue::failing()` for this?

I suppose my confusion is expressed more clearly if I say that I don't exactly understand where the return values from `Queue::push()` can emanate from. I.e. from `run()`, so that I am in "control" of what is returned, or from somewhere else? I hope my question makes sense...
