### ISSUE TITLE
Issue with compiled cache when upgrading framework to a newer version

### ISSUE THREAD

**Issue by slash686** [laravel/framework#14859]
I've ran into an issue when upgrading Laravel from version 5.1.17 (LTS) to 5.2:

Steps to reproduce:

To replicate issue on local machine you need first to run "php artisan optimize --force" in order for "bootstrap/cache/compiled.php" to be generated

1. Prepare codebase to upgrade using Laravel's upgrade guide and run "composer install"
2. When running post-install composer hook (post-install-cmd) Symfony\Component\Debug\Exception\FatalThrowableError exception is thrown with following error:

The problem is in that when composer runs post install hooks defined in **composer.json** (php artisan clear-compiled and php artisan optimize) these commands fail since they are loading framework classes from compiled.php which was generated using old framework version.

In order to succesfully complete update I had to delete "bootstrap/cache/compiled.php" file manually and rerun "composer install".

The solution would be to clear compiled cache before installation using pre-install-cmd composer hook with simple php script which does not depend on laravel framework itself or add warning/note to framework upgrade guide stating that user should manually remove compiled cache file prior to running update.

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch .This has already been fixed. You'd need to copy over our new scripts stuff into your project. This is not listed in the upgrading guide because it's not required to upgrade.
