### ISSUE TITLE
For OPTIONS request Route::any() not work like Route::match(['OPTIONS'],...)

### ISSUE THREAD

**Issue by Denys-Bushulyak** [laravel/framework#14858]
Found this issue when trying implement CORS response to AJAX fetch.

Route::any() does not handle OPTIONS request as expected, but Route::match(['OPTIONS']) was.

**Comment by themsaid** [comment]
Hello @barryvdh :) 

Do you have any reason why `Route::any()` shouldn't match an OPTIONS verb?

**Comment by barryvdh** [comment]
Yes, `any()` doesn't register the Options route: https://github.com/laravel/framework/blob/c7de016c568c0b1555914487b0944b7298105fbe/src/Illuminate/Routing/Router.php#L208-L213

```php
public function any($uri, $action = null)
    {
        $verbs = ['GET', 'HEAD', 'POST', 'PUT', 'PATCH', 'DELETE'];
        return $this->addRoute($verbs, $uri, $action);
    }
```

In my cors package, I intercept the CORS request in my ServiceProvider:
https://github.com/barryvdh/laravel-cors/blob/7236b8ca722fb404c5f83444eca195ec4ca46d55/src/ServiceProvider.php#L42-L44
And use the Router to detect if it can match the Router for the requested verb (so not OPTIONS, but e.g POST). If so, return a response from the middleware directly:
https://github.com/barryvdh/laravel-cors/blob/master/src/HandlePreflight.php

**Comment by themsaid** [comment]
So do you believe that we should keep it that way and not match OPTIONs?

**Comment by barryvdh** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

> The Cross-Origin Resource Sharing standard works by adding new HTTP headers that allow servers to describe the set of origins that are permitted to read that information using a web browser.  Additionally, for HTTP request methods that can cause side-effects on user data (in particular, for HTTP methods other than GET, or for POST usage with certain MIME types), the specification mandates that browsers "preflight" the request, soliciting supported methods from the server with an HTTP OPTIONS request method, and then, upon "approval" from the server, sending the actual request with the actual HTTP request method.  Servers can also notify clients whether "credentials" (including Cookies and HTTP Authentication data) should be sent with requests.

Matching OPTIONS with `any` would have a side effect of executing the request/action already, so I don't think that is expected behavior.

**Comment by themsaid** [comment]
Oh, that makes sense.

Thank you so much for your help :)

@Denys-Bushulyak please check above.
