### ISSUE TITLE
PhpStorm can't get access property of variable in blade

### ISSUE THREAD

**Issue by alizoj** [laravel/framework#14855]
For example, i want PhpStorm to get access properties of model variable and show them in blade like:
@var \App\User $user
I write $user->
IDE should show all properties.

Generally I make it in this way.
Model class:
<?php
/**
 *@property string email
 *etc..
*/
class user extends Model { .... }
?>

So then I add comment in view like:
<?php
/**
*@var \App\User $user
*/
$user->
           [email, etc...] IDE shows these properties which i defined in model so i choose one
?>
How i can make this with blade template??
![2](https://cloud.githubusercontent.com/assets/8639357/17725460/74358134-646d-11e6-9425-7a36535e2a22.png)
![1](https://cloud.githubusercontent.com/assets/8639357/17725461/7438125a-646d-11e6-8242-791b861dba47.png)

**Comment by srmklive** [comment]
To be honest, this is not a framework issue. I myself use PhpStorm. As far as i know, you can't do it in blade templates.

**Comment by alizoj** [comment]
> To be honest, this is not a framework issue. I myself use PhpStorm. As far as i know, you can't do it in blade templates.

It means that, i should remember all methods, constants, properties and etc. of my object if i want to use blade template? Sounds bad

**Comment by mustafaaloko** [comment]
It means that this has nothing to do with Laravel. This might be an
issue with PHPStorm, you can let them know of this thing.

**Comment by alizoj** [comment]
Okay, so how do you do this thing in your way? Maybe you're using another IDE or something else?

**Comment by mustafaaloko** [comment]
None of the IDEs I know of has this feature. I just type it. I use Sublime
and PHPStorm most of the time.

**Comment by crynobone** [comment]
> i should remember all methods, constants, properties and etc. of my object if i want to use blade template? Sounds bad

Shouldn't you made this report to PHPStorm or whoever building the Blade plugin for PHPStorm (if they have one for this). Laravel didn't build PHPStorm and we can automatically fix their limitation.

**Comment by JGamboa** [comment]
It work ok for me

@php
/**
 * @var \App\Models\Ot $ot
 */
@endphp
