### ISSUE TITLE
[5.3] issue on generating events

### ISSUE THREAD

**Issue by mehranhadidi** [laravel/framework#14861]
When i am going to create an event using artisan command, after generate the event class, it will generate an ``` <?php ``` before the output message. for example : 

``` php artisan generate:event UserRegistered ```

 i will get an output like this :

```
<?phpEvent created successfully.
```

@taylorotwell

**Comment by ahmedash95** [comment]
what's your laravel version ? as i remember laravel 5.1,5.2 don't have any generate namespace commands .. do you use a package ?

**Comment by mehranhadidi** [comment]
its on laravel 5.3 dev branch.

**Comment by mehranhadidi** [comment]
it seems there is a global problem with generating outputs. it may be an CLI output or returning a collection. when i try to return user notifications i get an output like this :
```
<?php[{"id":"987e82e8-fbcd-45e5-a27d-0104f11a7d35","type":"App\\Notifications\\WelcomeMessage","notifiable_id":4,"notifiable_type":"App\\User","data":{"name":"mehran"},"created_at":"2016-08-18 06:25:45","updated_at":"2016-08-18 06:25:45","read_at":"2016-08-18 10:55:45"},{"id":"12f25641-3a6c-4c52-ac04-552e4b44db57","type":"App\\Notifications\\WelcomeMessage","notifiable_id":4,"notifiable_type":"App\\User","data":{"name":"mehran"},"created_at":"2016-08-18 06:25:16","updated_at":"2016-08-18 06:25:16","read_at":"2016-08-18 10:55:16"}]
```

**Comment by DuckThom** [comment]
I just cloned `laravel/laravel` and I'm on the develop branch (which uses 5.3) and I don't have any commands starting with `generate`.
Other commands like `php artisan make:event TestEvent` work as expected.

**Comment by GrahamCampbell** [comment]
Sounds like an issue with a 3rd party package.
