### ISSUE TITLE
[5.3] seeJson() is behaving oddly, check the screen shot of failing test case

### ISSUE THREAD

**Issue by sagarrabadiya** [laravel/framework#14860]
![image](https://cloud.githubusercontent.com/assets/5405403/17734345/458f5220-6499-11e6-87b6-8088a03509bd.png)

though "id": 1, fragment is present in response its saying fragment not found! i debugged it and seems `,` is the issue in `Str::contains` for ex.

$actual has `"id": 1,\n`
$expected has `"id": 1 \n`

because of pretty print and more keys in object I guess

see the debug screenshot
![image](https://cloud.githubusercontent.com/assets/5405403/17734469/f8f6b948-6499-11e6-842f-980d27793bcb.png)

**Comment by fernandobandeira** [comment]
Could you check again with the recent changes? #14886

**Comment by sagarrabadiya** [comment]
yes working perfectly now, closing the issue.
