### ISSUE TITLE
[5.3] notifications wont mark read. 

### ISSUE THREAD

**Issue by mehranhadidi** [laravel/framework#14872]
there is a bug on notifications mark as read. when i create some notifications, i want to mark them read as a collection or an item. it wont work.

**Comment by alexbowers** [comment]
There was a change made recently (pre RC) which changed `read` to `read_at` and to be a timestamp. If you are on a version from before this change, then you will need to update your database accordingly, or rollback and forwards to make it so this change works.

**Comment by mehranhadidi** [comment]
i created a migration to change the read to read_at. seems that the updated generator works fine. thanks
