### ISSUE TITLE
php artisan db:seed  [ReflectionException]  Class DatabaseSeeder does not exist Version [5.2.43 ]

### ISSUE THREAD

**Issue by basherr** [laravel/framework#14875]
![roles](https://cloud.githubusercontent.com/assets/10073316/17765812/88b33e56-6541-11e6-956c-b218e7a371e8.PNG)
![databaseseeder](https://cloud.githubusercontent.com/assets/10073316/17765823/8f921224-6541-11e6-9e5a-a069a023a3d1.PNG)

I've fresh laravel version 5.2.43 and I get error on while seeding db.

**Comment by concept-core** [comment]
did you do a composer dump-autoload ?

**Comment by basherr** [comment]
yup I've already done autoload

**Comment by GrahamCampbell** [comment]
I can't replicate. Feel free to seek advice on the forums, or keep talking here.

**Comment by rajapet** [comment]
Maybe you should import Seeder and Model classes in your DatabaseSeeder.php file.

`use Illuminate\Database\Seeder;`
`use Illuminate\Database\Eloquent\Model`

**Comment by basherr** [comment]
@rajapet I have tried that way as well but no success.

**Comment by SufeeLatif** [comment]
Illuminate\Contracts\Container\BindingResolutionException

  Target class [DatabaseSeeder] does not exist.

  at E:\xampp\htdocs\ecom\vendor\laravel\framework\src\Illuminate\Container\Container.php:811
    807|
    808|         try {
    809|             $reflector = new ReflectionClass($concrete);
    810|         } catch (ReflectionException $e) {
  > 811|             throw new BindingResolutionException("Target class [$concrete] does not exist.", 0, $e);
    812|         }
    813|
    814|         // If the type is not instantiable, the developer is attempting to resolve
    815|         // an abstract type such as an Interface or Abstract Class and there is


This error occurs while am trying to do run this cmd let me know How to solve this
php artisan db:seed

**Comment by Dendi6** [comment]
rename the `seeds` folder name to `seeders`
