### ISSUE TITLE
Sending database notifications to more that one user on multiple channels cause a error

### ISSUE THREAD

**Issue by socieboy** [laravel/framework#14883]
I'm playing with the notifications using, mail, database and broadcast.

I found when I'm notifying with the database and broadcast divers at the same time, on the database the records are saved as the img shows.

<img width="1872" alt="captura de pantalla 2016-08-18 a las 10 23 05 am" src="https://cloud.githubusercontent.com/assets/7442695/17783639/cb5370dc-652d-11e6-95c9-82bc3a29415f.png">

As you see it's the same notification to the different users but only one save the data that i specify on the toDatabase, then it just include the class name and the ID. 

is that the way it should work?

**Comment by themsaid** [comment]
Closing it since the discussion on the [PR](https://github.com/laravel/framework/pull/14884) lead to the issue being resolved.
