### ISSUE TITLE
Calling getSize() method from UploadedFile gives an error

### ISSUE THREAD

**Issue by hiromik** [laravel/framework#14894]
![error1](https://cloud.githubusercontent.com/assets/9575928/17802445/9d196956-65f0-11e6-9b3b-23e7409fd6de.PNG)
![error2](https://cloud.githubusercontent.com/assets/9575928/17802446/9d1d0cd2-65f0-11e6-9e5d-2cb3916b4d26.PNG)

My php.ini settings are fine (post_max_size superior (50M) to max file upload size and memory limit superior to both of them)

Found nothing but this : 
https://github.com/laravel/framework/issues/5221

When not using the move() function getSize() or putting it after the getSize() call works fine.

Any idea ?

![php_version](https://cloud.githubusercontent.com/assets/9575928/17802633/a286a02e-65f1-11e6-9ba6-980bda4eefe9.PNG)

Using Laravel v5.2.43

**Comment by arasmit2453** [comment]
When you move the file the File is not in the previous path anymore so the getSize method access the old path call the size method before the move or store the size in a variable.

**Comment by srmklive** [comment]
I agree with @arasmit2453.

**Comment by themsaid** [comment]
The error makes sense because you already moved the file as @arasmit2453 said. Closing the issue then :)
