### ISSUE TITLE
make:test Automatically append Test to end of test's name

### ISSUE THREAD

**Issue by mstnorris** [laravel/framework#14890]
It seems silly to me to have to write "Test" at the end of a Test class when using the `artisan make:test` command. *It* knows I want to scaffold a test, so why can't it help me generate the name?

**Comment by ntzm** [comment]
All other `make:*` commands don't add their suffixes, it would be inconsistent to do it only for tests

**Comment by mstnorris** [comment]
Then why not add the suffixes for all others then (if it is required).

I only pointed out the Test one, as "Test" is needed. For the others, I don't believe any particular suffix is required.

PhpUnit looks for anything with "Test" at the end, so although I agree it is inconsistent however I don't see anywhere in the docs where you're told that a *test* class **must** have the suffix "Test".

**Comment by Jamesking56** [comment]
Maybe the same for `make:controller` to add `Controller` as a suffix... Still I think some people probably don't add suffixes so why should they be forced to?

**Comment by mstnorris** [comment]
In that case, if we're adverse to appending "Test" automatically, then why does it need to be required? If it is so other classes can exist within the tests directory that aren't executed.I get it. But as each test should be granular, I don't see how this would be the case.

**Comment by fernandobandeira** [comment]
I guess that we could add the Test suffix for the make;test since it's required, the other ones should stay as they are since they aren't required.

Are you willing to submit a PR for this? So we could discuss this further there.

**Comment by mstnorris** [comment]
@fernandobandeira I agree that the others don't need it as it isn't required. I also get that it *could* be confusing, but at the same time, it is just another convention that anyone can get used to following.

I've just submitted a pull request.

**Comment by themsaid** [comment]
Closing the issue since the PR was closed https://github.com/laravel/framework/pull/14902
