### ISSUE TITLE
Paginator query option escapes []

### ISSUE THREAD

**Issue by lukasoppermann** [laravel/framework#14901]
Hey,

so the paginator has an options array with the option to provide a query `array` that will be merged with the page variable. However, while creating this query string, `[` and `]` are escaped.

This means:

```php
new LengthAwarePaginator($result, $result->count(), 5, 1, 
   [
      'query' => [
         'filter[test]' => 'true'
      ]
   ]);`
```

returns a url like `/?filter%5Btest%5D=true&page=2` which is obviously wrong. It would need to be `/?filter[test]=Test&page=2`. 

Adding it in another array like `filter => ['test' => 'true']` does not help either.

This is important, as it is the official json api standard way of adding filters to urls for api calls.

Could you maybe fix this? Thanks.

**Comment by themsaid** [comment]
This encoding is done using the `http_build_query()` native method, the encoding is performed per [RFC 1738](http://www.faqs.org/rfcs/rfc1738.html) which states:

> Other characters are unsafe because
   gateways and other transport agents are known to sometimes modify
   such characters. These characters are "{", "}", "|", "\", "^", "~",
   "[", "]", and "`".

**Comment by lukasoppermann** [comment]
Okay, actually I missed this small section in the json api specs:

> Note: The above example URI shows unencoded [ and ] characters simply for readability. In practice, these characters must be percent-encoded, as noted in the base specification.

So I guess this makes it fine. 😄
