### ISSUE TITLE
[5.3]PHP have to --enable-pcntl if use queue

### ISSUE THREAD

**Issue by ac1982** [laravel/framework#14909]
I tried this under my windows with PHP 7.0 (no way to enable pcntl):
`php artisan queue:work  --timeout=360 --queue=high,low --sleep=3 --tries=3`
Will get this exception.
```
  [RuntimeException]
  The pcntl extension is required in order to specify job timeouts.
```
But same project in my server ( Ubuntu 16.04 with PHP 7.0 enable pcntl), it works fine.
So if it is necessary to add in "Server Requirements" ?

**Comment by gholol** [comment]
Same... Why is it even required, what about windows users? It worked fine in 5.2

**Comment by GrahamCampbell** [comment]
Windows users need to pass `--timeout 0`. We don't want to silently not use the timeout. If you don't want it, explicitly set it to 0 to disable it.

**Comment by gholol** [comment]
Gah! thanks, it works now

**Comment by morloderex** [comment]
@GrahamCampbell @taylorotwell we should maybe at a note on the docs regarding this issue.

**Comment by GrahamCampbell** [comment]
Or we could just update the exception message to say turn the timeout off if you don't want timeouts?

**Comment by morloderex** [comment]
Yeah might be better.

**Comment by wdmtech** [comment]
@gholol - I seem to be getting the same message using either syntax:

![image](https://cloud.githubusercontent.com/assets/7282262/18206266/c735d192-711d-11e6-9817-38a4d60f5747.png)

This is on an 5.2-5.3 upgraded project - I'll try a fresh 5.3 project too.

**Comment by gholol** [comment]
@wdmtech It doesn't work with listener, you have to use worker. 

`php artisan queue:work --daemon --timeout 0`

**Comment by wdmtech** [comment]
@gholol Interesting, any idea why not?

It has `--timeout` as an option

![image](https://cloud.githubusercontent.com/assets/7282262/18213198/e487c6f8-713e-11e6-846f-145a87654bb1.png)

**Comment by gholol** [comment]
@wdmtech Since 5.3, there was a change and pcntl extension is now required to handle  jobs.

There's no Pcntl for windows so Graham did make a partial fix with this pull request https://github.com/laravel/framework/pull/14741 

I suspect he forgot about the listener  :grinning:

**Comment by taylorotwell** [comment]
Yes looks like we just need to handle fix this on the listen command maybe @GrahamCampbell? Can someone send over a PR?

**Comment by GrahamCampbell** [comment]
I didn't forget about it as such. I just didn't expect anyone to want to use it.

**Comment by GrahamCampbell** [comment]
I mean, can can fix it. :P
