### ISSUE TITLE
Eager load problem on paginated data

### ISSUE THREAD

**Issue by Chrysanthos** [laravel/framework#14907]
I am not sure if it is a bug or I am doing something wrong but I have the following code.

```
      // Controller
        $results = Product::where('phone_id', $phone->id)
            ->orderBy('price', 'ASC')
            ->paginate(15)->load('store');

     // View
		@foreach ($results as $product)
                   ....
		@endforeach 

		{!! $results->links() !!}
```

It seems like when the data are paginated, the pagination fails to render the bootstrap html with the links method. 

The same code works fine with the get() instead of paginate().

Laravel: v5.2.43

**Comment by themsaid** [comment]
Use `with()` before calling `paginate()` instead of load.

The result of `get()` is an Eloquent/Collection, which has a `load()` method, on the other hand the result of `paginate()` is a `LengthAwarePaginator` that doesn't have a `load()` method.

**Comment by JayBizzle** [comment]
@themsaid It is totally valid to call`load()` on the `LengthAwarePaginater`. 

The magic `__call` method will call the `load()` method on the results collection...I do this quite regularly. [See here for source](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Pagination/AbstractPaginator.php#L510)

@Chrysanthos Any error, or just no HTML output?

**Comment by themsaid** [comment]
@JayBizzle Really! Didn't know that, thank you!

**Comment by Chrysanthos** [comment]
The error is 

> Method links does not exist. (View: /home/vagrant/Projects/xxxx/resources/views/phones/show.blade.php)

**Comment by themsaid** [comment]
@Chrysanthos because the output of `load()` is an Eloquent Collection which doesn't have the `links()`.

```
$results = Product::where('phone_id', $phone->id)
            ->orderBy('price', 'ASC')
            ->paginate(15);

$results->load('store');

return view('...', compact('results'));
```

**Comment by Chrysanthos** [comment]
I now use the with method which works fine. I just mentioned it so someone can check whether is a bug or not :)
```
        $results = Product::where('phone_id', $phone->id)
            ->orderBy('price', 'ASC')
            ->with('store')
            ->paginate(15);

```

**Comment by themsaid** [comment]
I think using `load()` after the call would work as well.

**Comment by JayBizzle** [comment]
@themsaid Your example is the way to do it (call load on the result set). That is the way i generally do it and it works no problem 👍

**Comment by themsaid** [comment]
Closing since we reached a solution :)
