### ISSUE TITLE
[5.2] Controllers resolution is no longer processed by Service Container

### ISSUE THREAD

**Issue by grey-dev-0** [laravel/framework#14920]
In Laravel 5.1 I was able to provide multiple implementations (Controller Classes) when an Action of a non existing Controller is required, I accomplished that by creating a service provider that gives the corresponding Controller class when a condition applies.

For example when `Route::get('admins', 'UsersController@getAdmins');` is triggered, the `ControllersProvider` which is a service provider resolves the requested `UsersController` that *does not* really exist and gives one of the existing implementations of that class from the service container which is defined like this:

````php
# In ControllersProvider service provider class
public function register(){
    $this->app->singleton('App\Http\Controllers\UsersController', function(){
    # The concrete passed to this function does not exist
    # but it should be resolved with one of the following Classes in the switch construct.
    switch(Auth::user()->role){
       case 'SomeRoleA': return new \App\Http\Controllers\RoleA\UsersController();
       case 'SomeRoleB': return new \App\Http\Controllers\RoleB\UsersController();
       default: throw new NotFoundHttpException();
    }
 });
}
````

In Laravel 5.2 this is impossible to accomplish because, the Controllers are resolved using the ReflectionClass which directly calls the `getAdmins` method from the non existing `UsersController` class without trying to resolve the required implementation for it like Laravel 5.1 did.

**Comment by themsaid** [comment]
Since Laravel 5.3 was release I doubt any change in how controllers are resolved in 5.2 will happen, however in 5.3 you'll be able to register your controller classes in the container like the example you shared, however at this early stage of the application the session won't be ready, and thus calling `Auth::user()` will return null.

**Comment by grey-dev-0** [comment]
@themsaid You're right, and I also found out that `Route::get()`, `Route::post()` and, `Route::any()` will call the requested action using the `ReflectionClass` which of course will trigger an error of trying to call a method in a non-existing class `App\Http\Controllers\UserController`.

The deprecated `Route::controller()` calls the methods automatically associated by Laravel on the provided class resolved in the container though.

Thank you anyway.

**Comment by desbiger** [comment]
@grey-dev-0 How did you resolve it? Your update doesn't work for me on 5.3.18. AuthServiceProvider is above in providers list, but Auth::user() returns null any way.

**Comment by Decadence** [comment]
I have the same problem.
@themsaid @GrahamCampbell is there any workaround to get Auth::user() in ServiceProvider?

**Comment by grey-dev-0** [comment]
@desbiger @Decadence 
I'm on Laravel 5.2 with my current project that's why I could access `Auth::user()` from within the service provider, in 5.3 you can't access session data unless all services have been booted i.e. all `boot` methods are called first which another issue, have a look at laravel/framework#14983 .

The only workaround I could guess is that to develop a custom IoC class that gives the proper implementation of a method when requested, the hiccups you'll face are that you must make sure that custom IoC class is instantiated after all other services is loaded and, you have to call the providing method of that custom class in every controller method you have.

In my case with Laravel 5.2 I could use the normal service provider `register` method to inject the proper implementation into the `UserController` class constructor, then used the methods of that injected implementation in the controller's methods like this.

````php
# In ImplementationProvider service provider class
public function register(){
    # App\CustomContracts\SomeContract is an interface implemented in all classes I'd like to inject.
    $this->app->singleton('App\CustomContracts\SomeContract', function(){
    switch(Auth::user()->role){
       case 'SomeRoleA': return new \App\CustomImplementations\ImplemenationA();
       case 'SomeRoleB': return new \App\CustomImplementations\ImplemenationB();
       default: throw new NotFoundHttpException();
    }
 });
}

# In UserController class
use App\CustomContracts\SomeContract;
class UserController extends Controller{
    private $implementation;
    public function __construct(SomeContract $implementation){
       $this->implementation = $implementation;
    }

    # And that's how to use it.
    public function getSomething(){
       return $this->implementation->getSomething();
    }
}
````

You can figure out a way to automate calling the requested method with the standard `__call` magic method or the `missingMethod` method of the `Controller` class.

**Comment by Decadence** [comment]
@grey-dev-0 That's a problem, in 5.2 I have similar code and it works fine, on 5.3 it doesn't.
Custom IoC is very complicated way, there must be more convenient option.
