### ISSUE TITLE
[5.2] ErrorException in EntityNotFoundException.php line 16

### ISSUE THREAD

**Issue by alfaraj** [laravel/framework#14937]
I have been struggling with this weird error after submitting a form.
The most weird thing is that it occurs 'sometimes'.
I tried to debug the core code with no success.

The error says:
> Missing argument 1 for Illuminate\Contracts\Queue\EntityNotFoundException::__construct(), called in /Users/..../...../app/Core/BaseRepository.php on line 93 and defined

**Comment by GrahamCampbell** [comment]
This is unrelated to form submissions.
