### ISSUE TITLE
for non-increment primary key

### ISSUE THREAD

**Issue by Fenzland** [laravel/framework#14934]
Eloquent will set key attribute as last insert id. But some time our primary key is not auto increment. Even, it may be a string. It will be mistakenly set as 0 in these case.

Please take a little change with Illuminate\Database\Eloquent\Model::insertAndSetId(), so that we can configure whether primary key is auto increment.

**Comment by GrahamCampbell** [comment]
Set the incrementing property to false on your model.

**Comment by GrahamCampbell** [comment]
From our docs:

![image](https://cloud.githubusercontent.com/assets/2829600/17850895/3a45a60a-6857-11e6-8396-8c0e3db210dd.png)

https://laravel.com/docs/master/eloquent
