### ISSUE TITLE
[5.2] Request validations rule unique:table not working on PostgreSQL

### ISSUE THREAD

**Issue by LonnyX** [laravel/framework#14940]
Hi,

I am working with PostgreSQL and when I try to valide an user with these rules:

```php
return [
            'email' =>  'required|email|unique:users',
            'password' =>   'required|min:4|max:32',
            'first_name' => 'required',
            'last_name' => 'required'
        ];
```

when the received email is in lower case, it works as it should. But when the received email has, at least one upper case letter, it will generate an error like :

> SQLSTATE[23505]: Unique violation: 7 ERREUR: la valeur d'une clé dupliquée rompt la contrainte unique « users_email_unique »

The problem is that Laravel will store the email in lowercase and when it try to validate, as pgsql is case sensitive, the email will not be found...

**hello@example.com != Hello@example.com**

**Probable solution:**
- if Request validation is using the "LIKE" operator, it should be replaced with "ILIKE" (pgsql only)
- lowercase the data on the unique method before checking the database
- ...

**Comment by themsaid** [comment]
I don't think we should alter the user input before validation, it should be passed to the DB in the same manner it was entered to avoid confusion that may happen when you enter a string in upper case and find it being compared in lower case.

The query from the validator has a regular where where condition, not sure really how this can be solved.

**Comment by LonnyX** [comment]
I solved this by forcing the lowercase. I think we have to choice because the same mail can't be used multiple time. Even the email provider (gmail, outlook, yahoo...) don't use the case sensitive
