### ISSUE TITLE
[5.3] Eloquent: Should boolean attribute casting apply when updating the DB?

### ISSUE THREAD

**Issue by misenhower** [laravel/framework#14942]
I ran into an issue when testing Laravel 5.3 where, when setting the value of a field for a boolean column, if I set the value to `null` or a string other than "true" or "1" I would receive an integrity constraint violation and the save operation would fail. This was not the case with Laravel 5.2: I could set boolean fields to `null` and save the model successfully.

I ultimately determined that this was caused by a new default setting in the project template that [enables MySQL "strict" mode by default](https://github.com/laravel/laravel/pull/3777).

My first thought was to set up attribute casting for the boolean fields, but this didn't work as expected either. If I set a property to, say, "foo" and read it back it returns a boolean `true`, but it fails upon saving to the database.

For the following demo I have `grant_all_permissions` set up as a boolean-casted property on my model:

``` php
protected $casts = [
    'grant_all_permissions' => 'boolean',
];
```

When modifying an existing record:

```
>>> $r->grant_all_permissions = 'foo' // set the value to a string
=> "foo"
>>> $r->grant_all_permissions // read it back -- it returns a bool
=> true
>>> $r->save() // but saving fails
Illuminate\Database\QueryException with message 'SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'foo' for column 'grant_all_permissions' at row 1 (SQL: update `roles` set `grant_all_permissions` = foo, `updated_at` = 2016-08-22 15:17:26 where `id` = 2)'
>>> $r->grant_all_permissions = null // set the value to null
=> null
>>> $r->grant_all_permissions // read it back -- it returns null
=> null
>>> $r->save() // saving fails
Illuminate\Database\QueryException with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'grant_all_permissions' cannot be null (SQL: update `roles` set `grant_all_permissions` = , `updated_at` = 2016-08-22 15:17:26 where `id` = 2)'
```

I'm not sure what the best behavior would be here. Automatically converting `null` to `false` for boolean-casted fields would break nullable boolean fields since that would make it impossible to actually set the field as null.

It seems like it would be a good idea to automatically convert non-"false" string values to "true", but maybe this is working as intended in the context of a "strict" connection?

**Comment by borovaka** [comment]
I do not think autocasting of not false variable to true is a good idea.
You can do it yourself, but it is more obvious and error preventing behavior to get Exception instead of casting.
In case of null value this is the right behavior  if your field is set as NOT NULL.

**Comment by fernandobandeira** [comment]
I think that this is similar to the issue with GroupBy, now you have to manually add all of your selected columns to your GroupBy, like when working with Postgres.

I guess that if you want to work like before you should just disable the strict mode on your database.php config rather than creating a behavior to bypass the strict mode. Currently i'm working with it disabled too, since for me at least it's creating more issues than actually helping me.

**Comment by misenhower** [comment]
Just to add some context, the issue Fernando is referring to is #14997 (and the PR at laravel/laravel#3905).

I think the null behavior is probably fine (to allow for nullable boolean columns) but the "true" behavior is potentially confusing -- especially since when you read the value back from the model instance it returns as `true` even though that's not what will be written to the DB.
