### ISSUE TITLE
Laravel 5.3 Possible Eloquent Issue...?

### ISSUE THREAD

**Issue by Azirius** [laravel/framework#14947]
I'm not 100% if this is an issue with an incompatible library, however, upon migrating my hobby app to 5.3 to 5.2 reordering a nested list doesn't work, however it can insert perfectly fine, and via `artisan tinker` it seems to update fine, also. The package I am using for the nested-set operations is `lazychaser/laravel-nestedset` and up to now has not failed me in it's functionality.

I was a little concerned I may have broke something during migration, so branched off to test it on 5.2 again, and it worked fine... So, I'm not sure what it is that's causing this issue.

I am also trying outside of the Git community here: http://stackoverflow.com/questions/39068954/laravel-5-3-lazychaser-laravel-nestedset-not-updating to find a solution, and I've spent hours trying to actually find the root cause, but my limited expertise is proving to be a bit of a road block, so have turned to you guys to see if this is either A) Me missing something or B) a slight hiccup/incompatibility or C) something else entirely.

Things I have looked in to are the MySQL logs and the issue _seems_ to stem from after the update:

```
Query    ROLLBACK
```

The operation re-ordering the files is 

```php
Link::rebuildTree($request->order);
```

Where `Link` is a model using the `NodeTrait` trait from `laravel-nestedset` and the method `rebuildTree` is a method of said trait that takes an array of items to 'rebuild' the current tree, and as previously mentioned has worked on 5.2. 

I appreciate any help I can get with the issue, or at the very least a direction to try instead, or something.

Thanks =]

**Comment by GrahamCampbell** [comment]
Looks related to the library. Thanks though.
