### ISSUE TITLE
laravel/laravel release way behind master?

### ISSUE THREAD

**Issue by matthewlenz** [laravel/framework#14943]
Result is considerable difference in using composer (current release) vs laravel/installer (master) (per laravel documentation) in the project scaffolding app/, config/ files etc.  Confusing for new laravel/php developers (aka me).

**Comment by matthewlenz** [comment]
Sorry if this isn't clear.  Maybe this is more detailed:

http://laravel.io/bin/bE9JN

**Comment by GrahamCampbell** [comment]
the installed app is the same as laravel/laravel?

**Comment by matthewlenz** [comment]
Did I invoke composer incorrectly? The laravel documentation shows two methods of creating a new project. Those two methods produce different results. As in the scaffolding code is different. Is that intentional?
