### ISSUE TITLE
Confusing comment inside HasOneOrMany::create

### ISSUE THREAD

**Issue by CthulhuDen** [laravel/framework#14956]
[HasOneOrMay.php#L319](https://github.com/laravel/framework/blob/e86c4a472bae7aeefb7f671c2cd8853fd35f8b82/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php#L319) seem to suggest that the `$instance = $this->related->newInstance($attributes)` line sets the attributes without guarding, which is not the case. Next line of code settings foreign key is also not setting *raw* attributes so I think the whole comment block is misguiding.

**Comment by srmklive** [comment]
The comment clearly states that we are avoiding using the fill method to bypass mass assignment error to fill related model data. I don't think the comment is ambiguous.

**Comment by CthulhuDen** [comment]
That doesn't make any sense. The called method [`newInstance`](https://github.com/laravel/framework/blob/7d116dc5a008e69c97f864af79ac46ab6a8d5895/src/Illuminate/Database/Eloquent/Model.php#L487) calls [`Model::__construct`](https://github.com/laravel/framework/blob/7d116dc5a008e69c97f864af79ac46ab6a8d5895/src/Illuminate/Database/Eloquent/Model.php#L275) which in turn calls `fill`.
