### ISSUE TITLE
[5.3] [bug] SqlServerConnection not compatible with ConnectionInterface

### ISSUE THREAD

**Issue by StevenBock** [laravel/framework#14964]
After upgrading to 5.3., I'm receiving the following error when trying to load my application:

`PHP Fatal error:  Declaration of Illuminate\Database\SqlServerConnection::transaction(Closure $callback) must be compatible with Illuminate\Database\ConnectionInterface::transaction(Closure $callback, $attempts = 1)`

it looks like Illuminate\Database\ConnectionInterface added an $attempts parameter to the transaction method declaration.  This doesn't look to have been added to the Illuminate\Database\SqlServerConnection implementation.

**Comment by GrahamCampbell** [comment]
Thanks for the report. This will be fixed in v5.3.1, due for release in a few hours or so.
