### ISSUE TITLE
Web middleware and __construct() in 5.3

### ISSUE THREAD

**Issue by doctorawesome** [laravel/framework#14968]
Just upgraded laravel 5.2 to 5.3. And here is my problem:

I usually check Sentinel user, get user object in base class Controller. And then pass this with parent::__construct(); to all controllers

In controller class.
5.2 - return user object. Same code in 5.3 return nothing, if insert it below in some method - works ok.
```
public function __construct()
{
    $this->userSession = \Sentinel::check();
}
```
I guess it's somehow could be related to web group. Because Sentinel::check() required web middleware.

**Comment by GrahamCampbell** [comment]
You cannot access auth in the controller constructors in Laravel 5.3. Please see the previous discussion.

**Comment by GrahamCampbell** [comment]
It was never recommended anyway in earlier versions.
