### ISSUE TITLE
5.3 undocumented BC break with EventServiceProvider::boot()

### ISSUE THREAD

**Issue by neclimdul** [laravel/framework#14974]
## Summary
Testing upgrading to 5.3 I immediately ran into the following fatal error (uncaught RuntimeException):
```
Declaration of App\Providers\EventServiceProvider::boot(Illuminate\Contracts\Events\Dispatcher $events) should be compatible with Illuminate\Foundation\Support\Providers\EventServiceProvider::boot()
```

This is caused by the following commit in 5.3 https://github.com/laravel/framework/commit/fa9f3220af499bb1bb6fc7dca03b1da7e0d60986

There doesn't seem to be any documentation of this change in the upgrade documentation or release notes.

## Proposed resolution
The BC fix would be to accept a deprecated argument that is thrown out.
The non-BC fix would be to just provide upgrade documentation.

**Comment by GrahamCampbell** [comment]
Odd that this breaks. Didn't break for me.

**Comment by neclimdul** [comment]
Maybe you're running PHP 5.X? This was a strict standards warning in 5.x.

https://3v4l.org/53c5R

**Comment by GrahamCampbell** [comment]
Gah, php is so stupid for breaking for adding params to functions like this.

**Comment by GrahamCampbell** [comment]
Thanks for catching.

**Comment by GrahamCampbell** [comment]
We just need to update the docs. :)

**Comment by neclimdul** [comment]
Just a note it obviously affects other providers in that commit and any others I haven't seen yet :)
