### ISSUE TITLE
[5.3] [Bug] with accessing the user.

### ISSUE THREAD

**Issue by Radostin** [laravel/framework#14983]
Hello,

I've just started experimenting with L5.3. Basically, it seems that the authentication system is not booted, when resolving a Controller. I know that there have been changes in the way Controllers are being resolved in 5.3, and I hope that is not the issue. So, here's the code.

```php
class Controller extends BaseController
{

    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;

    /**
     * Controller constructor.
     */
    public function __construct()
    {
        view()->share('currentUser', auth()->guard('admin')->user());
        // currentUser = null
    }
}
```

It seems that when resolving the controller, the authentication system doesn't recognize the user. Hence, the ``` auth()->guard('admin')->user() ``` returns null.

But, if I use the same code inside my blade, it works. Consequently, that means that the authentication system gets registered/booted once we start resolving the views.

```
// that is way too verbose
auth()->guard('admin')->user()->profilePicture()

// if I could get away with:
$currentUser->profilePicture();
```

If you wonder, whether I have something weird going on with my service providers, here's an excerpt of my app.php file:

```php
 Illuminate\Auth\AuthServiceProvider::class,
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Bus\BusServiceProvider::class,
        Illuminate\Cache\CacheServiceProvider::class,
        Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
        Illuminate\Cookie\CookieServiceProvider::class,
        Illuminate\Database\DatabaseServiceProvider::class,
        Illuminate\Encryption\EncryptionServiceProvider::class,
        Illuminate\Filesystem\FilesystemServiceProvider::class,
        Illuminate\Foundation\Providers\FoundationServiceProvider::class,
        Illuminate\Hashing\HashServiceProvider::class,
        Illuminate\Mail\MailServiceProvider::class,
        Illuminate\Notifications\NotificationServiceProvider::class,
        Illuminate\Pagination\PaginationServiceProvider::class,
        Illuminate\Pipeline\PipelineServiceProvider::class,
        Illuminate\Queue\QueueServiceProvider::class,
        Illuminate\Redis\RedisServiceProvider::class,
        Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
        Illuminate\Session\SessionServiceProvider::class,
        Illuminate\Translation\TranslationServiceProvider::class,
        Illuminate\Validation\ValidationServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,

        /*
         * Package Service Providers...
         */
        HtmlServiceProvider::class,
        Barryvdh\Debugbar\ServiceProvider::class,
        Laracasts\Flash\FlashServiceProvider::class,
        //        JavaScriptServiceProvider::class,
        Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class,
        
        /*
         * Application Service Providers...
         */
        App\Providers\AppServiceProvider::class,
        // App\Providers\BroadcastServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,
```

I tried moving things around, but nothing seemed to work.

Thanks in advance!

**Comment by narutimateum** [comment]
thank you for this ... having the same problem too..hope there is a solution very very soon.. T.T

**Comment by tzurbaev** [comment]
You have to change this since with Laravel 5.3 you can not access user in Controller constructors.

As an alternative, you can use [`View::share`](https://laravel.com/docs/5.3/views#sharing-data-with-all-views) or [View Composers](https://laravel.com/docs/5.3/views#view-composers) to share variables with views.

**Comment by Radostin** [comment]
That's fine, but I want to share them in bulk. Hence, I would have to declare the share and/or the composer in a service provider. However, that doesn't work either. Plus, I just noticed that I can't do auth()->user() in a middleware as well.

I hope that those changes were not intentional.

**Comment by vniko** [comment]
>You have to change this since with Laravel 5.3 you can not access user in Controller constructors.

Could you give  a link to the doc where such behavior is mentioned?

**Comment by tzurbaev** [comment]
@vniko not documented yet, see #14968

**Comment by narutimateum** [comment]
as OP stated.. i need to share stuffs in bulk too..... any alternative?? my code relies largely on some data of the auth shared in bulk..its used frigging everywhere..lol

**Comment by vniko** [comment]
@tzurbaev  while it's not documented it's a bug, not a feature : ) And it's a really bad change

**Comment by crynobone** [comment]
https://github.com/laravel/framework/pull/14834#issuecomment-241533275

**Comment by doctorawesome** [comment]
I had similar problem. Fix it with middleware class. Put Sentinel::check() and View::share. If I need object in controller,  just get it by $request.

I don't now is it good way, but it's working for me :)
