### ISSUE TITLE
[5.3] Laravel Middleware Request Merge Not Return Any Value

### ISSUE THREAD

**Issue by ssuhat** [laravel/framework#14995]
Hi,

All my code is working on Laravel 5.2. Now I try to upgrade to Laravel 5.3 it breaks on middleware.

    // Verify Middleware
    public function handle($request, Closure $next)
    {
        // I already make sure the data is exists
        $user = User::find('abc');

        if (!$user) {
            return responseHandler()->unauthorized('Unauthorized');
        }

        $request->merge(['user_id' => $user->id, 'device' => $device]);

        return $next($request);
    }

    // User Controller
     public function __construct(Request $request)
    {
        var_dump($request->all());
        $this->user_id = $request->user_id;
        $this->device = $request->device;
    }

    public function getProfile(Request $request)
    {
        $data = User::find($this->user_id);

        $result = Fractal::item($data, new UserTransformer)->getArray();

        return responseHandler()->success(0, $result, 'user');
    }

The problem is `$this->user_id` is always null. But if I request from getProfile function it return correctly. 

`var_dump` result only the login info. it not received any merge request from middleware

On Laravel 5.2 this code is working properly. Any solution?.

**Comment by rs-sliske** [comment]
you cant get the user in the constructor anymore

**Comment by themsaid** [comment]
In 5.3 you can no longer do this, the reason is that the controller class is constructed before running any middleware in the stack, so by the time you code is called that `merge()` method won't be fired yet.

Check the [Upgrade guide](https://laravel.com/docs/5.3/upgrade) for more information about how to use the request object in your controller constructor:

    public function __construct()
    {
        $this->middleware(function ($request, $next) {
            $this->user_id = $request->user_id;
            $this->device = $request->device;

            return $next($request);
        });
    }
