### ISSUE TITLE
function event(...$args)

### ISSUE THREAD

**Issue by ukadev** [laravel/framework#14998]
Can you take a look to /src/Illuminate/Foundation/helpers.php on line 475?

What are doing the three points there?

Looks like a bad copy-paste hehe.

On the last version the arguments were $event, $payload = [], $halt = false for the function and also for its file event

I see the same at this file:
/src/Illuminate/Support/Facades/Facade.php on line 238

**Comment by RomainLanz** [comment]
Welcome to the Splat Operator !

https://secure.php.net/manual/en/migration56.new-features.php

**Comment by ukadev** [comment]
Cool! so perhaps its something about my php config because I'm getting an error 500. Thanks and Closed!
