### ISSUE TITLE
[5.2.44][Bug] firstOrNew will fetch the first user, if unknown id is supplied as attributes

### ISSUE THREAD

**Issue by KarimGeiger** [laravel/framework#14993]
Since the last update from 5.2.43 to 5.2.44 the following test fails, although it should succeed:

    User::create(['name' => 'user1', 'email' => 'test@example.com', 'password' => bcrypt('password')]);
    $this->assertEquals(2, User::firstOrNew(['id' => 2])->id);

Actual result:

    1) ExampleTest::testBasicExample
    Failed asserting that 1 matches expected 2.

As you can see, I'm trying to get the first user having the ID 2. If that user does not exist, I expect it to create a new model with that ID. Sadly, this is not the case and the user with ID 1 gets pulled instead.

Environment:
Newly installed Laravel project on version 5.2.44, with a sqlite test database defined.

**Comment by miscbits** [comment]
This issue was resolved. https://github.com/laravel/framework/pull/15003

fields that were not mass assignable were not being searched.

**Comment by KarimGeiger** [comment]
Hi @miscbits, thanks for the quick fix!
