### ISSUE TITLE
Illuminate\Foundation\Auth\ResetsPasswords::resetPassword() assumes an Eloquent model

### ISSUE THREAD

**Issue by deframe** [laravel/framework#15005]
```php
/**
 * Reset the given user's password.
 *
 * @param  \Illuminate\Contracts\Auth\CanResetPassword  $user
 * @param  string  $password
 * @return void
 */
protected function resetPassword($user, $password)
{
    $user->forceFill([
        'password' => bcrypt($password),
        'remember_token' => Str::random(60),
    ])->save();

    $this->guard()->login($user);
}
```

The $user parameter on this method expects (though is not type-hinted to be) an implementation of **\Illuminate\Contracts\Auth\CanResetPassword** but the method body treats it like an Eloquent model with calls to _$user->forceFill()_, _$user->save()_, etc.

Perhaps the **Illuminate\Contracts\Auth\CanResetPassword** contract and the default implementation should be updated to include a 'resetPassword()' method? Something would also need to be done about the call to _$this->guard()->login($user)_.

**Comment by srmklive** [comment]
Because App\User model implements the *Illuminate\Contracts\Auth\CanResetPassword* contract by default.

**Comment by deframe** [comment]
I'm aware that `App\User` implements the interface but I'm not sure what it has to do with the issue at hand?

`Illuminate\Foundation\Auth\ResetsPasswords::resetPassword($user, $password)` is called by the `reset()` method on the PasswordBroker. The (default) PasswordBroker determines the **$user** property by calling `retrieveByCredentials()` on its associated UserProvider instance. At no point in this chain is **$user** assumed to be an Eloquent model, only that it has to implement the `Illuminate\Contracts\Auth\CanResetPassword` interface.

The model-specific usage of **$user** within `\Illuminate\Foundation\Auth\ResetsPasswords::resetPassword()` appears leaky to me. It even states in the method's docblock that $user should implement `CanResetPassword`, which has absolutely nothing to do with Eloquent. To get around it the password reset behavior from `ResetsPasswords` (i.e. the controller) could be moved `CanResetPassword` (the user).

Regardless of whether that's a good solution or not, I think this was closed prematurely.
