### ISSUE TITLE
[5.2.44][bug] firstOrNew won't working anymore

### ISSUE THREAD

**Issue by jonatascabral** [laravel/framework#15007]
In version 5.2.44, the methods firstOrNew and firstOrCreate aren't working with non mass assignable attributes.

**Comment by GrahamCampbell** [comment]
Fixed on 5.3. :)

**Comment by GrahamCampbell** [comment]
I might backport this to 5.2. I'll have a word with Taylor. It would seem reasonable to do so.

**Comment by GrahamCampbell** [comment]
I've backported that for you. It'll be available in the next release. :)

**Comment by jonatascabral** [comment]
@GrahamCampbell thanks for the quick fix. :-D
