### ISSUE TITLE
Error: $ composer create-project laravel/laravel my_project_name dev-develop

### ISSUE THREAD

**Issue by siarmehri-1stlocate** [laravel/framework#15006]
PHP Fatal error: Uncaught ErrorException: array_merge(): Argument #1 is not an array in /home/vagrant/Code/First_Now_API/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:93 Stack trace: #0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'array_merge(): ...', '/home/vagrant/C...', 93, Array) #1 /home/vagrant/Code/First_Now_API/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(93): array_merge(Array) #2 /home/vagrant/Code/First_Now_API/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(61): Illuminate\Foundation\Exceptions\Handler->shouldntReport(Object(ErrorException)) #3 /home/vagrant/Code/First_Now_API/app/Exceptions/Handler.php(35): Illuminate\Foundation\Exceptions\Handler->report(Object(ErrorException)) #4 /home/vagrant/Code/First_Now_API/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): App\Exceptions\Handler->report(Object(ErrorException)) #5 [internal function]: Illuminate\Fo in /home/vagrant/Code/First_Now_API/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php on line 93 PHP Fatal error: Uncaught ErrorException: array_merge(): Argument #1 is not an array in /home/vagrant/Code/First_Now_API/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:93 Stack trace: #0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'array_merge(): ...', '/home/vagrant/C...', 93, Array) #1 /home/vagrant/Code/First_Now_API/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(93): array_merge(Array) #2 /home/vagrant/Code/First_Now_API/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(61): Illuminate\Foundation\Exceptions\Handler->shouldntReport(Object(Symfony\Component\Debug\Exception\FatalErrorException)) #3 /home/vagrant/Code/First_Now_API/app/Exceptions/Handler.php(35): Illuminate\Foundation\Exceptions\Handler->report(Object(Symfony\Component\Debug\Exception\FatalErrorException)) #4 /home/vagrant/Code/First_Now_API/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): App\Exceptions in /home/vagrant/Code/First_Now_API/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php on line 93

**Comment by GrahamCampbell** [comment]
Please don't use the develop branch. It doesn't work. Use master.
