### ISSUE TITLE
Artisan make:auth boilerplate issue 

### ISSUE THREAD

**Issue by AngryElephant** [laravel/framework#15000]
On laravel 5.2 after generated the authentication boilerplate with 

artisan make:auth

i had a complete working set.

Now i have this error:

    Class 'App\Http\Controllers\Auth' not found

HomeController is using auth middleware without : use auth;

**Comment by RomainLanz** [comment]
You are calling `Auth::` somewhere inside your controller without importing it.

**Comment by fernandobandeira** [comment]
Seems that you are on 5.3, so one heads up, you cant access any middleware inside your construct anymore, check if you are accessing it inside a method like index() instead of the __construct();

**Comment by AngryElephant** [comment]
i'm using 

    $user = Auth::user();

in one of my method.

**Comment by fernandobandeira** [comment]
Try replacing it with:

```php
$user = auth()->user();
```

**Comment by GrahamCampbell** [comment]
You need to import the facade, or escape it with a leading slash.
