### ISSUE TITLE
[5.3] Queues no longer work on Windows

### ISSUE THREAD

**Issue by StevenBock** [laravel/framework#15002]
After upgrading to Windows and trying to run `php artisan queue:work`, I receive the following error:

`[RuntimeException]
The pcntl extension is required in order to specify job timeouts.`

Per the [manual](http://php.net/manual/en/pcntl.installation.php), this extension will not work on Windows.  So Windows users will now be unable to use queued jobs.

**Comment by GrahamCampbell** [comment]
You need to explicitly add `--timeout 0` on windows to say you don't want a timeout. We didn't silently fallback otherwise people might think their timeout was actually working.

**Comment by StevenBock** [comment]
Oh ok.  That might be something helpful to have in the documentation (I couldn't find anything about setting it to 0 and obviously didn't think of that.

Thank you!
