### ISSUE TITLE
updateOrCreate not working in 5.2.44 version

### ISSUE THREAD

**Issue by adilsaeed31** [laravel/framework#15009]
Hi,

I have last stable version is 5.2.39 which was working fine with updateOrCreate method, but after updating to 5.2.44 my updateOrCreate method with same matching $attributes not creating new records only update the current one. 

Any idea how to fix it. 

Thanks
Adil

**Comment by GrahamCampbell** [comment]
Fixed in 5.2.45 when it comes out.

**Comment by adilsaeed31** [comment]
There is no 5.2.45 and what i will do until the release of 5.2.45, man it's serious production project.

Thanks
Adil
