### ISSUE TITLE
User automatic logout after file changes

### ISSUE THREAD

**Issue by ajmerainfo** [laravel/framework#15008]
I am using windows with xammp and Laravel 5.3.0

When change any controller's file then user automatically logout.

Am I doing something wrong or it's who they work?

I am newbie for Laravel.

**Comment by fernandobandeira** [comment]
Changing the file shouldn't logout the user, 

Yet check the session time used, since it'll logout when the session expires, inside your config/sessions.php

```php
'lifetime' => 120, //minutes
```

Also this may be an issue with xampp or your browser generating a new session.

**Comment by ajmerainfo** [comment]
@fernandobandeira  Thank you for quick response.

I have tried with Chrome and FF but still same issue.
And with xammp I am using WordPress but it's working perfectly fine.

Also I have tried to save session on cookie but still same issue.

**Comment by miscbits** [comment]
I've seen this issue with XAMPP before. What we wound up concluding is XAMPP will cache php files when they are used. this means relevant keys, session data, and storage can sit in memory. It then uses a listener to see if a file has been edited and to refresh that cache. If session data is stored in cache it might be refreshing that as well. 

Two things I would do to see if this could potentially also be your issue 
1) try to check out where session data is being stored for your laravel app. If its in memory then that could be your issue. 
2) Try setting up the project with [laravel homstead](https://www.laravel.com/docs/5.3/homestead) and seeing if the issue persists. If so then it more likely is an issue with the code. I dont feel confident that this is a bug that belongs in the framework issues tracker though so I would also recommend joining the[ laravel slack](https://larachat.co/) channel and asking for help in the #questions channel.

**Comment by ajmerainfo** [comment]
I have tried storing session on database, and file and cookies but no luck.

Also one thing need to add CSRF field 80-90% says failed to verify. 
So looks like session changed.

I will ask further question on LaraChat. Thanks for suggestion.
