### ISSUE TITLE
Laravel not Redirecting after manual user Authentication?

### ISSUE THREAD

**Issue by MohitDeshwal** [laravel/framework#15019]
## In LoginController.php I want to redirect user to home page.but it always shows blank page after authenticating user.

```
public function authenticater($data,$request)
    {
        $email=$data['email'];
        $check=User::where('email', '=',$email)->first();
        //if not found means we need to register the user

        if ($check != null) {
            // Authentication passed.....
            $id=intval($check->id);
            Auth::loginUsingId($id,true);
            //echo '<html><script>setTimeout(function(){ window.history.go(-1); }, 3000);</script></html>';
            //echo '<html><script>location.href="/";</script></html>';

             return redirect()->guest(route('home'));

        }
```

**Comment by MohitDeshwal** [comment]
# **However it used to work in 5.2 with**
`echo '<html><script>location.reload();</script></html>';`
## **but now in 5.3:**
![screenshot_7](https://cloud.githubusercontent.com/assets/4270376/17951787/815e0690-6a82-11e6-8e22-2f8b8607023d.png)

**Comment by MohitDeshwal** [comment]
Figured out the solution.

**Comment by omer414** [comment]
@MohitDeshwal what was your solution? I think i am also having a similar issue. Here is the link to my issue https://github.com/laravel/framework/issues/15314.

**Comment by MohitDeshwal** [comment]
I discussed it at [(https://laracasts.com/discuss/channels/laravel/laravel-not-redirecting-after-manual-user-authentication)] @omer414
