### ISSUE TITLE
Dynamic property relationships on Eloquent model from route model binding return null

### ISSUE THREAD

**Issue by WaveHack** [laravel/framework#15013]
This used to work in Laravel 5.2. Ever since I'm working on upgrading my app to 5.3 I've stumbled upon this particular problem.

Forgive me for not writing out an exact minimal test case scenario, because I located the problem down to this point and I think it's clear enough for you guys to understand it with a bit of PHP code made up on the fly.

Let's say I have an app that shows a list of games (like football game matches). Each game belongs into one league.

```PHP
class Game extends Model
{
    public function leagues()
    {
        return $this->hasOne(League::class);
    }
}

class League extends Model
{
    public function games()
    {
        return $this->hasMany(Game::class);
    }
}
```

Simple, right? In the database, `games` has a field `league_id`. Elementary stuff.

The problem I'm having is Eloquent's dynamic properties to access relationships don't work on models injected through (implicit) route model binding anymore since the 5.3 update. In my case, I can't do `$game->league->id` anymore because the league dynamic property is (or returns) null. If I grab the Game object manually through `Game::find($id)`, then I can do the aforementioned action and access `$game->league->id` like normal.

Here's some example code to show you what I mean:

```PHP
// routing
Route::get('games/{game}/status', function (App\Game $game) {
	dd([$game, $game->league]);
});
```

Outputs in 5.3: [Game instance], null
Outputs in 5.2: [Game instance], [League instance]
Expected: [Game instance], [League instance]

If I change the routing to this:

```PHP
Route::get('games/{game}/status', function (App\Game $game) {
	$game = Game::find(1); // disregard the whole injected model, just grab it from the database
	dd([$game, $game->league]);
});
```

Outputs in both 5.3 and 5.2: [Game instance], [League instance]

I hope my explanation is clear enough. :) 

Could be a bug, could be something that I'm doing wrong. It goes without saying that I've read the 5.3 upgrade guide, the updated documentation for both Eloquent relationships and routing and skimmed through a few dozen of commits to see if I missed anything. Alas, I can't seem to find the problem myself.

**Comment by GrahamCampbell** [comment]
Looks like you forgot to add our binding middleware as stated in the upgrading guide.

**Comment by WaveHack** [comment]
Welp, it looks like I did. My apologies and thanks for the swift reply.
