### ISSUE TITLE
[5.3] firstOrNew issues

### ISSUE THREAD

**Issue by arcdigital** [laravel/framework#15017]
Hey, I just switched to 5.3.x-dev (to test out #15003), but it's still only returning the first record.

This always returns the first row in the DB.
`
$user = User::firstOrNew(['external_id' => $externalUser->id]);
`

However, if I do this - it works fine (returns the existing record or a brand new one if it doesn't exist). The external_id attribute is unique in the DB & mass assignable (I tried it with mass assignment on/off on that attribute)
`
$user = User::where('external_id', $externalUser->id)->firstOrNew([]);
`

**Comment by biu0w0** [comment]
firstOrNew() returns a new object of the model when there's no records in database match your condition.
The parameter firstOrNew() is array data to mass-assign when initialize the new object.
So your first code is wrong:
` $user = User::firstOrNew(['external_id' => $externalUser->id]); `
The second one is right:
` $user = User::where('external_id', $externalUser->id)->firstOrNew([]); `

**Comment by arcdigital** [comment]
This is not correct, the attributes are already passed into a where which is called on the model to see if it exists. The reason the first one doesn't work is because an undocumented breaking change was introduced in 5.2. This has now been reverted and everything works as expected.
