### ISSUE TITLE
[5.2] levenshtein(): Argument string(s) too long

### ISSUE THREAD

**Issue by senycorp** [laravel/framework#15027]
There is a problem when calling commands via $this->call() from another command with an extra long parameter list:

``` php
$this->call('ide-helper:models ' . $parameterList . ' --nowrite');
```
ErrorMessage:

```
[ErrorException]                            
  levenshtein(): Argument string(s) too long 
```

levenshtein() allows a maximum length of 255 characters. Maybe similar_text() is an alternative. The PHP documentation does not include any information of limits for it.

The Error-Log shows that a file from symfony/console is calling the function. So i am not sure whether you want to care about this:

```
vendor/symfony/console/Application.php(993): levenshtein('models --dir="m...', 'make')
```

I do not tested it in 5.3.

Thanks and great job!

**Comment by Ifnot** [comment]
This error occurs for me too, but it is a little different on my case.

I simply created a **Console Command signature with more than 255 chars**.

Theses 255 chars include the options descriptions and the indentation (of 4 spaces), so it makes very difficult to document more than 4/5 options well indented on a single command.

My non working signature example :

```
protected $name = 'six:create user
                        {name : The name of the unix account}
                        {--password= : The password of the account}
                        {--home= : Create and assign a home directory to this user}
                        {--group= : Assign a specific group for this user}';
```

Laravel : **5.3.8**
PHP : 7.0.8

**Comment by GrahamCampbell** [comment]
Looks like we just need to document this limitation, or if anyone wants to send a good PR to fix this, that'd be fine too. :)

**Comment by Ifnot** [comment]
I will look for a PR on this, but for now i agree for the doc update limitation.

As 255 chars is a reasonable limit, more can be really useful with big signature indentation / documentation.

**Comment by GrahamCampbell** [comment]
For large sigs, you can still use the other ways to define commands though. :)

**Comment by Ifnot** [comment]
I was digging the problem and just realized that I was using the old `$name` attribute instead of the `$signature` one for the signature ...

Works well with the `$signature` attribute as it parse sections separately. It means that we are only limited to 255 chars for a command **name** ... That is enough :)
