### ISSUE TITLE
[5.2] Laravel's global elixir PHP helper not working

### ISSUE THREAD

**Issue by rohmanmuhamad** [laravel/framework#15028]
Hi guys, i am facing a problem to using elixir for assets versioning in my view, here is the details :

- My project assets directory structure

![selection_069](https://cloud.githubusercontent.com/assets/10384675/17956651/a4c860c0-6ab5-11e6-9dca-6323aac995ad.png)

- My layouts meta style

```
<link href="{{ elixir('assets/css/styles.css') }}" rel="stylesheet">
<link href="{{ elixir('assets/css/theme/theme.css') }}" rel="stylesheet">
<script src="{{ elixir('assets/js/app.js') }}"></script>
```

- rev-manifest.json
```
{
  "assets/css/styles.css": "assets/css/styles-950442a8a4.css",
  "assets/css/theme/theme.css": "assets/css/theme/theme-e0de0f60c4.css",
  "assets/js/app.js": "assets/js/app-bb0a3a2630.js"
}
```

- Error message

![selection_070](https://cloud.githubusercontent.com/assets/10384675/17956785/780ab686-6ab6-11e6-8d2b-fad6b8bdef5c.png)

Any idea? :+1:

**Comment by GrahamCampbell** [comment]
This is not related to those functions. It's telling you your view files are missing.
