### ISSUE TITLE
Validation problem

### ISSUE THREAD

**Issue by nerea91** [laravel/framework#15036]
Hi, I don't now if this is a bug or a new feature but in laravel 5.2 when I do something like that:

$validator = Validator::make(['email' => null], ['email' => 'email']);

It passes but now in laravel 5.3 not. It works if I add the nullable rule but I think that it may be enough without the required rule.

**Comment by GrahamCampbell** [comment]
I don't think there's a bug here. Feel free to ask on the forums and I'm sure someone can help you.
