### ISSUE TITLE
[5.3]Did you remove multi tables auth and multi fields login?

### ISSUE THREAD

**Issue by Alpha2016** [laravel/framework#15037]
In version 5.1.11, laravel can use name, email as the login name, and 5.2, multi tables auth applied, but 5.3 both of them can't use, Why? or I am wrong about using the Laravel5.3?

**Comment by KKSzymanowski** [comment]
You can use any field on your `users` table. Eg.
```php
if (Auth::attempt(['email' => $email, 'password' => $password])) {
    // Authentication passed...
    return redirect()->intended('dashboard');
}
```

**Comment by Alpha2016** [comment]
> You can use any field on your users table. Eg.

I know this function, thanks, and can you help me , how use multi auth in Laravel5.3

**Comment by GrahamCampbell** [comment]
Feel free to ask on the forums.

**Comment by Alpha2016** [comment]
> Feel free to ask on the forums.

which forums you mean? Laravcasts.com?
