### ISSUE TITLE
[5.3] src/Illuminate/Auth/Notifications/ResetPassword.php has hardcode

### ISSUE THREAD

**Issue by garveen** [laravel/framework#15030]
```php
    /**
     * Build the mail representation of the notification.
     *
     * @return \Illuminate\Notifications\Messages\MailMessage
     */
    public function toMail()
    {
        return (new MailMessage)
            ->line([
                'You are receiving this email because we received a password reset request for your account.',
                'Click the button below to reset your password:',
            ])
            ->action('Reset Password', url('password/reset', $this->token))
            ->line('If you did not request a password reset, no further action is required.');
    }
```
Shouldn't the hardcode be move to resources/lang?

**Comment by AdenFraser** [comment]
Would be useful if the url/route is configurable too or at least the trait is documented as being hardcoded (since it's easy enough to replace).

**Comment by TresErres** [comment]
See  [#15024](https://github.com/laravel/framework/pull/15024)

```php artisan vendor:publish --tag=laravel-notifications```

**Comment by AdenFraser** [comment]
What about the url/route?

**Comment by TresErres** [comment]
See in [docs](https://laravel.com/docs/5.3/passwords) under **Reset Email Customization**

**Comment by themsaid** [comment]
Check Taylor's comment on this matter: https://github.com/laravel/framework/pull/15051#issuecomment-242797827

Closing this :)
