### ISSUE TITLE
[5.3] Need to add markAsUnRead() method in DatabaseNotification model

### ISSUE THREAD

**Issue by DesmondPang** [laravel/framework#15035]
There is a markAsRead() method in the DatabaseNotification but I suggest that you can add the markAsUnRead() method to toggle that state. Thanks

**Comment by themsaid** [comment]
We're open to Pull Requests. Closing this since it's not a bug report, but please feel free to continue discussions in the [Internals Repository](https://github.com/laravel/internals)
