### ISSUE TITLE
[5.2.44 Bug]: Infinit execution error handler

### ISSUE THREAD

**Issue by mdmunir** [laravel/framework#15043]
### What steps will reproduce the problem?
* Set not writable for file `storage/logs/laravel.log`.
* Create route
```php
Route::get('test', function(){
    1/0;
});

```
### What is the expected result?
Got error info.

### What do you get instead?
Got nothing/blank page.

### Additional info
Its because infinit execution of error handler. 

| Q                | A
| ---------------- | ---
| Laravel version      | 5.2.x
| PHP version      | 5.6
| Operating system | Debian 7

**Comment by GrahamCampbell** [comment]
What full PHP version and Laravel version please.

**Comment by GrahamCampbell** [comment]
Sounds like a bug in your PHP configuration.

**Comment by mdmunir** [comment]
> Sounds like a bug in your PHP configuration.

 So, what better php configuration you are recommend?
Have you try to reproduce this case to ensure that is not framework bug?

**Comment by GrahamCampbell** [comment]
I can't reproduce this on Ubuntu using PHP 5.6 or 7.0.

**Comment by mdmunir** [comment]
> I can't reproduce this on Ubuntu using PHP 5.6 or 7.0.

With readonly permission on file `storage/logs/laravel.log`?
What error that you get?

**Comment by GrahamCampbell** [comment]
Just an error that I can't write to there.

**Comment by GrahamCampbell** [comment]
As I said, I have tried this out, and seen this many times before too.

**Comment by mdmunir** [comment]
OK, thanks. sorry for wasting your time

**Comment by GrahamCampbell** [comment]
I do get a blank screen, but that's to be expected. Not the same as infinitely looping.

**Comment by mdmunir** [comment]
Blank screen isnot expected result. How we know the error if we got nothing?
Manually debuging is almost imposible with a lot of magical method.

Consider to breaking the  infinit calling error handler and throwing the meaningful message.
Worst text much better than blank page.
