### ISSUE TITLE
[bug] placing more than one DDL command in a closure fails (5.2 & 5.3)

### ISSUE THREAD

**Issue by salarmehr** [laravel/framework#15042]
Running the following migration on a sqlite db fails:

```
Schema::table('t', function (Blueprint $table) {
      $table->renameColumn('foo', 'bar');
      $table->dropColumn('baz');
    });

```
while the following works:

```
Schema::table('t', function (Blueprint $table) {
      $table->renameColumn('foo', 'bar');
        });

Schema::table('t', function (Blueprint $table) {
        $table->dropColumn('baz');
    });


```

`  SQLSTATE[HY000]: General error: 1 no such column: ... (SQL: CREATE TEMPORARY TABLE __temp__meaning AS SELECT ...)
`

**Comment by GrahamCampbell** [comment]
Thanks. This is not a bug though I'm afraid, just a limitation.

**Comment by salarmehr** [comment]
But that works for other DBMSs.

**Comment by GrahamCampbell** [comment]
Yeh, like I said, it's a limitation. It's not great I know.
