### ISSUE TITLE
[5.3] Session not available from a controller __construct() method. 

### ISSUE THREAD

**Issue by RemiCollin** [laravel/framework#15048]
I'm having this issue while porting one of our application from 5.2 to 5.3. 

On one controller, the __construct() method instantiate a dependency which use the Laravel's session to load its data. We noticed that, at this point of the application lifecycle, the session object is simply not available. 

I tried to start it manually, using `session()->start()` and it doesn't work as well. A session is started but with empty attributes. Later in the request the `StartSessionMiddleware` is handled, and at this time the correct attributes are available.

Is there a way to execute the `StartSessionMiddleware` earlier in the request (at least before hitting any of the application code, like Controllers) ?

**Comment by fernandobandeira** [comment]
You can't access any middleware inside the construct anymore, the following piece of code may lead you to your desired solution:

```php
        Event::listen(Authenticated::class, function ($event) {
            $this->currentUser = $event->user;
            view()->share('currentUser', $this->currentUser);  // simple example
            // other code that may need to bootstrap stuff for this user in the base controller
        });
```

This event goes in the __construct and in this case it will get the current logged in user, you should do something similar for your session.

**Comment by RemiCollin** [comment]
I get the idea behind your example, but I'm afraid there is no event I can hook to. I'll simplify the code so I can give you a simple snippet of what isn't working :

```php

class Cart {

    public $cartId;

    public function __construct()
    {
        $this->cartId = session()->get('cart_id');
    }
}

class CartController
{
    protected $cart;

    public function __construct(Cart $cart)
    {
        $this->cart = cart;
        dd($cart->cartId); // null as Session Store isn't available at this time of the request
    }

}  

```

So it's not really a middleware problem, but an issue of session being initialized too late in the application lifecycle.

**Comment by TresErres** [comment]
+1
In ```5.2``` works, not in ```5.3```

**Comment by sudomabider** [comment]
+1. Anyone know if this is intentional?

**Comment by jhdxr** [comment]
I can confirm this issue. I think it should be documented clearly if it's intentional, as it's a huge bc break.

**Comment by GrahamCampbell** [comment]
This was an intentional break. It only ever worked in 5.2 due to the fact that we instantiated the controllers late. Doing logic that depended on the request state was a hack in the first place I'm afraid.

**Comment by RemiCollin** [comment]
I wouldn't call this a hack, as the session is supposed to be avaibable on demand. Does it mean we cannot rely on IoC injected services in the controller in the first place ? This would be a HUGE BC....

**Comment by GrahamCampbell** [comment]
Oh, yeh, you totally can rely on the IOC, BUT you must not ever do anything with the request state. That includes sessions and auth. You can inject those classes for later though.

**Comment by RemiCollin** [comment]
Ok I guess we'll have to live with it. Some suggestion though : 

1) This should really be documented, as it's likely to be encountered in many use cases, and it took me at least 2 hours to really understand what was going on.

2) Using session() when the service's not started should throw an exception, this would make it easier to debug. 

And if you have any idea on how we could view()->share() session variables globally, i'd be really grateful. At this point we didn't come up with a viable workaround.

**Comment by dvlpp** [comment]
My workaround is to use a view composer, but for some reason it wouldn't work when attached to a global layout, like `view()->composer('master', MasterComposer::class)`. I had to list all views, even if they all extend master.

**Comment by gocanto** [comment]
@GrahamCampbell Can you address a little bit more this? Like, why there is not way to access this middleware from controllers construct? I really would like to have a expanded scope of this situation.

thanks

**Comment by swt83** [comment]
I've encountered this issue also.  This article looks helpful:

https://laravel-news.com/controller-construct-session-changes-in-laravel-5-3

**Comment by linkdesu** [comment]
This change is really need to be mentioned in document. 😭

**Comment by devcircus** [comment]
It's in the 5.3 upgrade guide.
https://laravel.com/docs/5.3/upgrade
