### ISSUE TITLE
Issue With Validating Multiple File Uploads

### ISSUE THREAD

**Issue by KayTokyo** [laravel/framework#15044]
Hi,

I have a single input field for multiple uploads.

```
<input type="file" name="attachments[]" multiple>
```

I am trying to validate each file with the same set of rules.

```
'attachments.*'     => 'mimes:pdf,xls,doc,docx,pptx,pps,jpeg,bmp,png|max:20000',
```

I am having some issues with this, i hope someone could address.

1. Although i have not set a required attribute to the validation, the input field is now required.
2. Although i have added .xls to the acceptable mime types, im still unable to upload a .xls file (excel)
3. I do not see any error messages for this input.

Thank you.

**Comment by fernandobandeira** [comment]
Wich version of laravel and php are you using(excatly)?

I guess that you are on PHP7, since thats the most common one when this error occurs.

**Comment by KayTokyo** [comment]
I am but actually i just updated to php 7 on this machine. I was having the same issue on an older version of php.

**Comment by ctf0** [comment]
how do u display the error for this validation ?

**Comment by KayTokyo** [comment]
Ye there maybe something wrong here?
```
	<div class="form-group {{ $errors->has('attachments.*') ? ' has-error' : '' }}">
						@include('errors.validation-message', ['inputName' => 'attachments'])
						{{$errors->first('attachments.*')}}
						<input type="file" name="attachments[]">
					</div>
```
errors.validation-message

```
@if ($errors->has($inputName))
	<span class="help-block">
		<strong>{{ $errors->first($inputName) }}</strong>
	</span>
@endif
```

But i can see them when i use

```
				@if($errors->any())
					@foreach($errors->getMessages() as $this_error)
						<p style="color: red;">{{$this_error[0]}}</p>
					@endforeach
				@endif
```

**Comment by themsaid** [comment]
old office documents are uploaded as `application/vnd.ms-office` (.doc, .xls, .ppt, etc...) based on the server configurations, to validate for an xls extension symfony expects a `application/vnd.ms-excel` instead, that's why your xls files won't pass.

Are you running on nginx?

**Comment by KayTokyo** [comment]
Im running apache. So what mine type do i need to add to my validation rule to get .xls files working and the older ones.

**Comment by ctf0** [comment]
maybe u can try to use `mimetypes` instead https://laravel.com/docs/5.3/validation#rule-mimetypes http://www.freeformatter.com/mime-types-list.html

**Comment by KayTokyo** [comment]
I will try that, but any ideas why the field still throws the error ```The attachments.0 must be a file of type: pdf, xls, doc, docx, pptx, pps, jpeg, bmp, png.``` when the field is not required.

**Comment by ctf0** [comment]
for validation array error msg, still no sign of how exactly to display it https://laravel.com/docs/5.3/validation#validating-arrays which already have like a couple of issues which got closed for no reason and mostly to get the error u cant use `$errors->has('attachments.*')` because the error array comes in numbers `attachments.0, attachments.1, etc..` so u have to use ``$errors->has('attachments.0')` to get it work but again it will fail if the error is related to another index.

**Comment by KayTokyo** [comment]
Yeah i saw those issues closed thats why i decided to open this.

**Comment by KayTokyo** [comment]
@ctfo Because theres so many issues with uploading multiple attachments with a single input field. Do you think it could work if i dynamically add a single file input field for each upload using js and then validate each one individually ? Is that possible

**Comment by ctf0** [comment]
u can ofcourse do so but i have also came up with a solution for displaying the array errors https://github.com/laravel/framework/issues/13779#issuecomment-223787086

**Comment by ctf0** [comment]
as for why u r always getting the error for the upload even when its not required , maybe u can try with a single file and see if u r still getting the same or is it only related to the multi file, showing us the whole form code would be better.

**Comment by KayTokyo** [comment]
I tried with a single file input, it works this issue is only with multiple file upload

**Comment by ctf0** [comment]
r u on v5.2 or v5.3 ? if on latest downgrade to v5.2 and re-test

**Comment by KayTokyo** [comment]
Validation
```
<?php

namespace App\Http\Requests;

use App\Http\Requests\Request;
use Illuminate\Support\Facades\Auth;

class CreateEventRequest extends Request
{

	/**
	 * Determine if the user is authorized to make this request.
	 *
	 * @return bool
	 */
	public function authorize()
	{

		return Auth::user()->role_id == 1;
	}

	/**
	 * Get the validation rules that apply to the request.
	 *
	 * @return array
	 */
	public function rules()
	{

		$rules = [
			'title'             => 'required',
			'live_link'         => 'required',
			'hero_image'        => 'required|image|mimes:jpeg,bmp,png|max:5000',
			'overview'          => 'required',
			'type'              => 'required|',
			'status'            => 'required|',
			'address_name'      => 'required_if:type,conference,',
			'address_line_1'    => 'required_if:type,conference,',
			'address_line_2'    => 'required_if:type,conference,',
			'address_city'      => 'required_if:type,conference,',
			'address_country'   => 'required_if:type,conference,',
			'address_postcode'  => 'required_if:type,conference,',
			'start_date'        => 'required|date',
			'max_users'         => 'numeric',
			'contact_telephone' => 'required',
			'contact_email'     => 'required|email',
			'attachments.*'     => 'mimes:pdf,xls,doc,docx,pptx,pps,jpeg,bmp,png|max:20000',
		];

		return $rules;
	}

	/**
	 * Get the error messages that should be displayed if validation fails.
	 *
	 * @return array
	 */
	public function messages()
	{

		return [
			'hero_image.max' => 'The hero image cannot be greater than 5mb.',
		];

	}
}
```

Html

```

```
	<div class="form-group {{ $errors->has('attachments') ? ' has-error' : '' }}">
						@include('errors.validation-message', ['inputName' => 'attachments'])
						<input type="file" name="attachments[]" multiple>
					</div>
```

```
@if ($errors->has($inputName))
    <span class="help-block">
        <strong>{{ $errors->first($inputName) }}</strong>
    </span>
@endif
```

**Comment by KayTokyo** [comment]
This issue was happening on 5.2 and is still happening on 5.3 after i upgraded

**Comment by ctf0** [comment]
mmmmm, try to make the validation manually https://laravel.com/docs/5.3/validation#manually-creating-validators and only add the attachment to the rules array and see if the error still display.

**Comment by themsaid** [comment]
We're discussing multiple issues here:

> Although i have not set a required attribute to the validation, the input field is now required.

Symfony Request creates a `[0 => null]` as a value of an empty file input that allows multiple files, this causes the validator to fail the check of a valid file even though no files exist, but internally it thinks theres a file with value `null`

>Although i have added .xls to the acceptable mime types, im still unable to upload a .xls file 

old office documents are uploaded as application/vnd.ms-office (.doc, .xls, .ppt, etc...) based on the server configurations, to validate for an xls extension symfony expects a application/vnd.ms-excel instead, that's why your xls files won't pass.

> I do not see any error messages for this input.

That's not related to multiple files in specific actually, it's related to array validation in general, which I think should be solved.

I'm going to check also on how to solve the first matter with symfony returning a null and see how this can be dealt with in laravel.

**Comment by ctf0** [comment]
@themsaid 
> Symfony Request creates a [0 => null] as a value of an empty file input that allows multiple files, this causes the validator to fail the check of a valid file even though no files exist, but internally it thinks theres a file with value null

maybe u r right but i have `'photo.*' => 'sometimes|image|max:3072',` which works as expected and doesn't give errors like the previously mentiond

**Comment by themsaid** [comment]
That's in Laravel 5.2 yes, because `null` would make the field not validatable and thus pass validation. In 5.3 this behaviour has changed. Using `nullable|image` would make the same effect as in 5.2.

**Comment by ctf0** [comment]
is this documented somewhere ?

**Comment by themsaid** [comment]
Check https://laravel.com/docs/5.3/upgrade under Nullable Primitives, it doesn't cover this specific case though, just a general notice that null isn't considered a valid value anymore.

**Comment by themsaid** [comment]
`sometimes` checks for presence, `nullable` checks for null.

**Comment by KayTokyo** [comment]
@themsaid 

```
Symfony Request creates a [0 => null] as a value of an empty file input that allows multiple files, this causes the validator to fail the check of a valid file even though no files exist, but internally it thinks theres a file with value null
```
So this is a known bug then, i assume its being looked into? Im not sure whether i should completely change the way i upload multiple files or wait for the fix...

```
old office documents are uploaded as application/vnd.ms-office (.doc, .xls, .ppt, etc...) based on the server configurations, to validate for an xls extension symfony expects a application/vnd.ms-excel instead, that's why your xls files won't pass.
```

So here i need to use the full mimetypes instead of mimes. So application/vnd.ms-excel instead of xls, Is that right?

```
That's not related to multiple files in specific actually, it's related to array validation in general, which I think should be solved.
```

What do you mean by this, is there a fix being released? or am i outputting the error messages wrong, if so how do i properly output it.

thank you

**Comment by themsaid** [comment]
1. Use `nullable|mimes:...` that'll fix your issue.
2. Use `application/vnd.ms-office` as the type, that'll validate it's a .xls, or .doc, or .ppt.
3. I personally believe this needs a fix yes, will look into that sometime soon. For now you can use [this workaround](https://github.com/laravel/framework/issues/13779#issuecomment-223787086) or similar.

**Comment by KayTokyo** [comment]
@themsaid 

Hi thank you, 1. and 2. are now fixed for me.

3. My final problem is here displaying the error messages. I dont want to declare my validation in my controller just because there is so much going on. How can i integrate @ctf0 solution into my form request class.

thank you.

**Comment by themsaid** [comment]
@KayTokyo please check https://github.com/laravel/framework/pull/15063 and let me know your feedback.

**Comment by KayTokyo** [comment]
@themsaid 

Looks good and it would solve this issue for me.

**Comment by ctf0** [comment]
@themsaid can u also update the docs on how to retrieve the array errors so everyone can party ?

**Comment by ctf0** [comment]
@KayTokyo u dont need to include the validation logic in ur controller https://gist.github.com/ctf0/bb137c135b6d9383184d4deec0b24d56

**Comment by themsaid** [comment]
@ctf0 working on that.

**Comment by KayTokyo** [comment]
@themsaid 

Hey i was 100% that "application/vnd.ms-office" had fixed the issue for me. But ive tested it again today and i can't seem to pass validation on any office files. Ive tried .doc and .xls

Heres my validation once again

```
'attachments.*'     => 'nullable|mimes:application/vnd.ms-office,pdf,jpeg,bmp,png|max:20000'
```

**Comment by themsaid** [comment]
You need to use `mimetypes` instead of `mimes`, `mimes` is used with extensions.

**Comment by KayTokyo** [comment]
Is it possible to use mimetypes validation alongside mime validation?

For example

```
'attachments.*' => 'nullable|mimetypes:application/vnd.ms-office|mimes:pdf,jpeg,bmp,png|max:20000'
```

Though this is returning the error.

```
validation.mimetypes
The attachments.0 must be a file of type: pdf, jpeg, bmp, png.
```

If i remove mimes and just try the validation below i still get the error ```validation.mimetypes```. Still doesn't seem to work.

```
'attachments.*'     => 'nullable|mimetypes:application/vnd.ms-office|max:20000'
```

**Comment by themsaid** [comment]
So office files won't pass with this rule?

```
'attachments.*'     => 'nullable|mimetypes:application/vnd.ms-office|max:20000'
```

**Comment by KayTokyo** [comment]
I just double checked to make sure and with those rules office files don't pass validation. returning the error ```validation.mimetypes``` in the view.

**Comment by KayTokyo** [comment]
Oh weird, .xls actually passes validation but not .doc

**Comment by KayTokyo** [comment]
If i want to validate legacy and new Microsoft extensions i need to write them out fully like below. This will validate ppt/pptx, doc/docx, xls/xlsx. 

```
'attachments.*'     => 'nullable|mimetypes:application/vnd.ms-excel,application/vnd.ms-powerpoint,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.openxmlformats-officedocument.presentationml.presentation,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet|max:20000'
```
https://en.wikipedia.org/wiki/List_of_Microsoft_Office_filename_extensions
http://stackoverflow.com/questions/4212861/what-is-a-correct-mime-type-for-docx-pptx-etc

Now as much as its a pain to list those (not even included mimetypes which contain office macros/scripts).  Along side this how do i add validation for mimes such as pdf/jpg/png. As its returning the error "validation.mimetypes" when selecting a pdf.

**Comment by themsaid** [comment]
Check here: https://www.sitepoint.com/web-foundations/mime-types-complete-list/

**Comment by themsaid** [comment]
You can write a customer validation rule to hide all this behind it, also to be able to use these rules anywhere else.

**Comment by KayTokyo** [comment]
Right, also has the fix the #15063 been released?

**Comment by timgavin** [comment]
I'm having a similar problem with the upload field being required when no file is present. In my case I have a form which consists of `title`, `body` and `photo[]` fields. The user must fill in at least one field in order to submit the form, so using `nullable` doesn't work for me, as it allows for an empty form to be submitted.

If the user fills in the `title` or `body` fields they still receive the mime validation error because `[0 => null]`.  I'm using L5.3.6

```
return [
    'title' => 'required_without_all:body,photo',
    'body' => 'required_without_all:title,photo',
    'price' => 'numeric',
    'photo' => 'array',
    'photo.*' => 'required_without_all:title,body|mimetypes:image/jpeg,image/png,image/gif',
];
```

**Comment by ctf0** [comment]
@timgavin u should have the photo rule as
```php
'photo.*' => 'required_without_all:title,body|mimetypes:image/jpeg,image/png,image/gif',
```
without the photo array one

**Comment by timgavin** [comment]
@ctfo Removing it makes no difference; still receiving the error. Plus, having `'photo' => 'array',` was the only way I could get it to work with `required_without_all`.

**Comment by ctf0** [comment]
if then u should put ur rules as 
```php
'photo' => 'required_without_all:title,body|array|mimetypes:image/jpeg,image/png,image/gif',
```
however this is just another newly introduced issue with the array validation in the 5.3. maybe @themsaid can help

**Comment by timgavin** [comment]
@ctfo Actually, doing that breaks my custom validation messages.

```
public function rules()
{
    return [
        ...
        'photo' => 'array',
        'photo.*' => 'required_without_all:title,body|mimetypes:image/jpeg,image/png,image/gif',
    ];
}
```
returns my custom error message

```
File can only be JPEG, GIF or PNG.
```

But 

```
public function rules()
{
    return [
        ...
        'photo.*' => 'required_without_all:title,body|array|mimetypes:image/jpeg,image/png,image/gif',
    ];
}
```
returns

```
The photo.0 must be an array.
```

**Comment by themsaid** [comment]
@timgavin proposed a fix to the issue: https://github.com/laravel/framework/pull/15250

**Comment by timgavin** [comment]
@themsaid Confirmed; working as expected. Thanks! :)
