### ISSUE TITLE
[5.3] (Revert) Resource Route Names No Longer Affected By Prefixes

### ISSUE THREAD

**Issue by yajra** [laravel/framework#15058]
Given the changes above, how would you group your resource routes on Laravel 5.3?

For instance, I have an application that have frontend & backend panel with same route resource?
In 5.2:
```php
// Backend post resource
$router->group([
    'middleware' => 'administrator',
    'prefix'     => 'administrator',
], function ($router) {
    $router->resource('posts', PostController::class);
});

// Frontend post resource 
$router->resource('posts', PostController::class);
```

This will yield a better grouping on resource route name.
```
administrator.posts.index  => /administrator/posts
administrator.posts.create => /administrator/posts/create
...
posts.index => /posts
posts.create => /posts/create
...
```

But on 5.3, same route will produce duplicate names.
```php
posts.index  => /administrator/posts
posts.create => /administrator/posts/create
...
posts.index => /posts
posts.create => /posts/create
...
```

Hence if you use `route()` helper then your upgrade path to 5.3 is doomed!

I know that we can fix it by manually naming the routes on administrator side (which is what I did on my project) but considering a big project, IMHO, too much code duplications! Imagine that we have to manually write all our administrator resource routes?
```
$router->get('posts', PostsController::class . '@index')->name('administrator.posts.index');
$router->get('posts/create', PostsController::class . '@create')->name('administrator.posts.create');
$router->post('posts', PostsController::class . '@store')->name('administrator.posts.store');
$router->get('posts/{posts}/edit', PostsController::class . '@edit')->name('administrator.posts.edit');
$router->put('posts/{posts}', PostsController::class . '@update')->name('administrator.posts.update');
$router->delete('posts/{posts}', PostsController::class . '@destroy')->name('administrator.posts.destroy');
```

I hope this can be reconsidered. Or if there is better way that I am missing, please enlighten me. Thanks!

**Comment by GrahamCampbell** [comment]
I think this was intended. Feel free to ask around on internals, or search for other issues.

**Comment by yajra** [comment]
@GrahamCampbell yes it was intended as documented. Submitting on internals to get what other thinks about it. Thanks!

**Comment by lchogan** [comment]
Same issue here. I have a superadmin prefix for many of my resources and the same resources without the superadmin. Now that I upgraded to 5.3 I have to write out each superadmin route. This completely negates the advantages of the route resources IMO. Thanks.

**Comment by yajra** [comment]
@GrahamCampbell maybe we can re-open this issue so that others may see and get a feedback from them like the issue thread on #15072?

Got 3 thumbs up on Internal issue + @lchogan so maybe this is worth for reconsideration? Thanks!

**Comment by crynobone** [comment]
@yajra why should resource route name be affected by prefix? 

```
$router->group([
    'middleware' => 'administrator',
    'prefix'     => 'admin',
], function ($router) {
    $router->resource('posts', PostController::class);
});
```

What happen when you need to change the prefix `admin` to domain `admin.laravel.com` as example? You're route name would be doom as well. With what we doing it in Laravel 5.3, such changes doesn't break your route name.

**Comment by yajra** [comment]
@crynobone changing from `prefix` to `domain` use case makes perfect sense. Didn't think of that.

@RDelorier suggested a workaround to use `as` https://github.com/laravel/internals/issues/181 and would give it a shot.

```php
Route::group([
    'as' => 'admin.', // the trailing dot makes me think this is unintended
    'prefix' => 'admin'
], function () {
    Route::resource('users', 'UserController');
});

Route::resource('users', 'UserController');
```

Thanks for feedbacks!

**Comment by lorvent** [comment]
Definitely a breaking change (many breaking ones like this makes 5.3 eligible for 6.0)
but moving forward, if this is the only way....we have no choice than adopt to it.

**Comment by fernandobandeira** [comment]
This changed because before when using ``` as ``` and ``` prefix ``` in the same route would append both of them to your route name, so the ``` prefix ``` appending dropped in place of the ``` as ```.

**Comment by lorvent** [comment]
but adding .(dot) i.e. `'as' => 'admin.'` looks weired

and i guess people were using only `prefix` before as it will do both things.

**Comment by fernandobandeira** [comment]
People were using both actually, there's a lot of issues related to this previous behavior, you can check some of them:

#12216 , #13903

So in the end prefix will affect the generation of your url meanwhile as will affect the name.

**Comment by Skintillion** [comment]
`but adding .(dot) i.e. 'as' => 'admin.' looks weird`

I agree, however it gives some the opportunity to use _ instead I guess. Personally I would prefer the decimal included automatically.

**Comment by templar92** [comment]
`Route::group(['prefix' => 'admin', 'as' => 'admin.'], function() {
    Auth::routes();
});`

will give us:
 POST          | admin/login                               | admin.  |
 POST          | admin/password/email              | admin.  |
 GET|HEAD  | admin/password/reset               | admin.  |
 POST          | admin/password/reset               | admin.  |
 GET|HEAD  | admin/password/reset/{token}  | admin.  |

etc.... How do we fix this?

**Comment by Skintillion** [comment]
Fix what?

**Comment by templar92** [comment]
Various auth routes having the same route name

**Comment by Skintillion** [comment]
Don't do that with auth routes.

**Comment by templar92** [comment]
So how do I do it if I want the following routes: admin.login, admin.logout, admin.resetpassword...etc?

**Comment by Skintillion** [comment]
I'm confused as to why you would need that anyways?

**Comment by templar92** [comment]
Because the project I'm working on has the authentication on the admin only and I want my routes organized that way so that I know which part of the application the routes are for.  I'm just concerned if having those auth related routes having the same 'admin.' name will not have unpredictable effects on the whole auth process...

**Comment by Skintillion** [comment]
Auth Routes command is here:

https://github.com/laravel/framework/blob/5.3/src/Illuminate/Support/Facades/Auth.php#L30

Which runs:

https://github.com/laravel/framework/blob/5.3/src/Illuminate/Routing/Router.php#L287

You could remake them yourself if you like and not use Auth::routes()

**Comment by templar92** [comment]
thanks

**Comment by Skintillion** [comment]
You're welcome!

**Comment by exleedo** [comment]
This worked for me : 

// Backend post resource
$router->group(['middleware' => 'administrator', 'prefix' => 'administrator'], function ($router) {
    $router->resource('posts', 'PostController', ['as' => 'administrator']);
});

// Frontend post resource 
$router->resource('posts', 'PostController');
