### ISSUE TITLE
[5.3] Sharing session variables in views

### ISSUE THREAD

**Issue by RemiCollin** [laravel/framework#15062]
From 5.3 upgrade, it seems impossible to share session variables in views anymore, like in 5.2.

```php

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        View::share('key', session()->get('key'));
    }
    ...
}

```

Is there any knew workaround to this ?

**Comment by mreschke** [comment]
I didn't think session() was even available at the Provider boot() level since laravel 4 ???  I remember it was in L4, but in L5 they changed session to middleware which is definitely NOT ready at a provider level.

**Comment by mreschke** [comment]
In L5.2 session wasn't available until routes or controller __construct.  Not at provider level.  And now in L5.3 its actually NOT even available at the routes or controller __construct level either.  See https://github.com/laravel/framework/issues/15072 for that

**Comment by GrahamCampbell** [comment]
You can use a middleware to do this. :)

**Comment by RishabSwift** [comment]
@GrahamCampbell  can you please explain how one would do so with a middleware? Stuck on the same boat.
