### ISSUE TITLE
[5.3 and below] getDirty() does not handle date columns right

### ISSUE THREAD

**Issue by afraca** [laravel/framework#15060]
Hey, 

When working with the Revisionable package I noticed an odd thing, sometimes fields are marked as 'dirty' while this should not be the case. Steps to reproduce:
- Create a table with a 'date' column and model for it
- Place the 'date' column name in the $dates property for the model
- Have at least one valid row
- With Eloquent retrieve that first row
- use `->fill()` on the instance to fill with the same date information
- **See `->getDirty()` sees the date information as dirty while it has not changed**

I have recreated a repository to showcase this:
https://github.com/afraca/laravel-dirty-date-bug

The home route shows the behaviour I described:
`
Route::get('/', function () {
    $b = App\Bug::firstOrFail();
    $b->fill([
        'foo' => '2016-07-30',
    ]);
    dd($b->getDirty());
});
`

I did some digging around to find the cause:
- `setAttribute` calls `fromDateTime()` [here](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Eloquent/Model.php#L2864)
- This in  turn calls `getDateFormat` and we end up [here](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Eloquent/Model.php#L2987) which has: 

`return $this->dateFormat ?: $this->getConnection()->getQueryGrammar()->getDateFormat();`

Internally, the ->$original holds the original database value, but after the `setAttribute(..)` call, in `->$attributes` it's being filled with datetime value.

It seems what causes this is that there is only 1 format that is being used for both date and datetime, whereas this format should differ depending on the column definition. I did not immediately saw an elegant fix for this. (Well, the `$cast` has some information, but when we end up at `getDateFormat` we lost `$key` information.)

**Comment by afraca** [comment]
We encountered this in Laravel 5.1, and worked around it by overriding `setAttribute`. We check some information in `$this->casts` for `$key` , and do
```
$this->setDateFormat('Y-m-d');
$return = parent::setAttribute($key, $value);
$this->setDateFormat(..old..);
return $return;
```

**Comment by bencromwell** [comment]
Having the same problem with casting booleans. They emerge from the database as `"0"` instead of having been cast.

Just for reference if anyone sees this and has the same issue as me.

**Comment by scs75** [comment]
Same problame here on laravel 5.3.

**Comment by arcanedev-maroc** [comment]
Yeah, i have the same issue and it's frustrating 😱

**Comment by GrahamCampbell** [comment]
Thanks for reporting everyone. This is more a design decision than a bug, though I definitely agree this needs properly discussion for a change proposal. Please either create one on the internals repos, or comment on the existing one if it exists (I've not actually checked if one exists).

**Comment by arcanedev-maroc** [comment]
Found this workaround: https://github.com/laravel/framework/issues/8972#issuecomment-259436230

**Comment by arcanedev-maroc** [comment]
This is my workaround:

```php
abstract class EloquentModel extends \Illuminate\Database\Eloquent\Model
{
    /**
     * Get the attributes that have been changed since last sync.
     *
     * @return array
     */
    public function getDirty()
    {
        $dirty    = [];
        $original = $this->getCastedOriginal();

        foreach ($this->attributes as $key => $value) {
            // cast any of the current attributes to the types they are expected to be
            if ($this->hasCast($key, $value)) {
                $value = $this->castAttribute($key, $value);
            }

            if (
                ! array_key_exists($key, $original) ||
                ($value !== $original[$key] && ! $this->originalIsNumericallyEquivalent($key))
            ) {
                $dirty[$key] = $value;
            }
        }

        return $dirty;
    }

    /**
     * Get the casted original attributes.
     *
     * @return array
     */
    protected function getCastedOriginal()
    {
        $original = [];

        foreach ($this->original as $key => $value) {
            if ($this->hasCast($key)) {
                $original[$key] = $this->castAttribute($key, $value);
            }
        }

        return $original;
    }
}
```
