### ISSUE TITLE
Default app scaffolding is not using the correct asset URLs

### ISSUE THREAD

**Issue by ConsoleTVs** [laravel/framework#15069]
Hello I've noticed that the default scaffolding  for the auth is not using the correct CSS / JS URLs;

As for an example, here's a photo of the actual code generated:
https://i.gyazo.com/502ca4b9770bdc9ef955d8410b97f7be.png

The view should generate by default, an asset() link like the following:
https://i.gyazo.com/0cbe1d4c198758a3515cb8444d200e3d.png

Same applies to the javascript asset.

Original:
```
<link href="/css/app.css" rel="stylesheet" >
<script src="/js/app.js"></script>
```
Correction:
```
<link href="{{ asset('/css/app.css') }}" rel="stylesheet" >
<script src="{{ asset('/js/app.js') }}"></script>
```

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. Please check for existing issues before posting though.
