### ISSUE TITLE
[5.3] Allow overriding of ResetsPasswords validation rules.

### ISSUE THREAD

**Issue by danielbaylis** [laravel/framework#15086]
Hardcoding the validation rules directly in the ResetsPasswords reset method prevents us overriding the rules  in ResetsPasswordController without overriding the entire function.  

**Illuminate\Foundation\Auth\ResetsPasswords** 
`
        $this->validate($request, [
            'token' => 'required', 'email' => 'required|email',
            'password' => 'required|confirmed|min:6',
        ]);
`

It would be nice to revert to the 5.2 approach where there was a separate method of the validation rules that we could simply override in the controller:

`$this->validate($request, $this->getResetValidationRules());`

This allows domain-specific validations to be used without bringing the other framework logic into the controller.

**Comment by srmklive** [comment]
You can simply override this function in your controller, and set it accordingly. I have myself done it to be inline with how it was in 5.2.

**Comment by danielbaylis** [comment]
Thank you.   I had mentioned that as a solution too but was trying avoid having the response logic in my controller in case it changed in the framework in the future.

Seems like we shouldn't really be overriding the lines below.  But then again, testing after framework updates would soon flag if there had been any changes :)  Thanks for taking a look.

```
        $response = $this->broker()->reset(
            $this->credentials($request), function ($user, $password) {
            $this->resetPassword($user, $password);
        }
        );

        return $response == Password::PASSWORD_RESET
            ? $this->sendResetResponse($response)
            : $this->sendResetFailedResponse($request, $response);
```

**Comment by roberthunt** [comment]
I was just about the raise the same issue as I was trying to customise the validation rules for minimum password length and I agree with @danielbaylis that it would be better to not have to copy and paste the response logic into the override.

I think this decision should be reconsidered, the RegisterController provides a validator that can be customised so it seems a bit inconsistent to have to do something different for the password resets.

**Comment by danielbaylis** [comment]
@roberthunt - I understand PRs have a better chance than issues, so am giving it a go with #16060.

**Comment by danielbaylis** [comment]
PR #16060 was merged and resolves this. :)
