### ISSUE TITLE
Abort() in construct shows the error view twice in screen

### ISSUE THREAD

**Issue by ConsoleTVs** [laravel/framework#15082]
Just letting you know

**Comment by themsaid** [comment]
@ConsoleTVs I don't think it's a problem with the framework, calling abort only throws an exception, handling this exception is something you do yourself.

**Comment by ConsoleTVs** [comment]
@themsaid Works fine when abort is thrown in a controller function or route, but double it's result only in the function construct

**Comment by GrahamCampbell** [comment]
Duplicate.

**Comment by GrahamCampbell** [comment]
This bug is related to us constructing the controller twice. You should never call abort in a constructor, or however the fact that an exception for some genuine reason will also cause this is a bug.
