### ISSUE TITLE
[?bug] Nested Relationships error

### ISSUE THREAD

**Issue by lorvent** [laravel/framework#15096]
I Have 
`Item`  model

`ItemCompetitor` model with Item hasMany

`ItemCompetitorSales` model with ItemCompetitor hasMany

now, when showing single item i want to get last 2 rows of ItemCompetitorSales for each ItemCompetitor

so my `ItemCompetitor` looks like this

```
public function sales()
    {
        return  $this->hasMany(ItemCompetitorSaleCount::class)
            ->orderBy('created_at','desc')
            ->take(2);
    }
```

So lets say for item = 1,

there are 10 competetirors,

each competitor has 5 competitor sales

so i want to get 10 x 2 = 20 rows from ItemCompetitorSale model

but i am getting only 2

if i change `take(2)` to `take(20)` it returns 20 rows but again 5 rows from each for first 4 competitors which is not what i want.

Is this a possible bug with laravel or am i doing wrong?

**Comment by GrahamCampbell** [comment]
Take 2 literally just means limit the result size of the whole thing to 2, so this looks correct.

**Comment by lorvent** [comment]
but when we call  take(2),

it should take 2 items for each nested table.

or i should not use take() in this scenario?
