### ISSUE TITLE
Create Laravel version with type hint and strict types

### ISSUE THREAD

**Issue by Lisennk** [laravel/framework#15093]
I think it's time to use PHP 7 features like strict types in new Laravel versions. Also you can transmit code via some compiler, that will produce PHP 5.6 compatible code as alternative.

**Comment by GrahamCampbell** [comment]
I don't think Laravel will ever be going down this route. Not really by decision though.

NB There are plenty of PHP 5 compatible places that could be repainted that aren't already.

**Comment by GrahamCampbell** [comment]
Laravel will probably be moving to PHP 7 soon anyway, so no messing about with backporting needed. (soon as in soon enough this stuff's not going to be a concern)

**Comment by allanlaal** [comment]
@taylorotwell time to reconsider type hints & strict types? :)

**Comment by allanlaal** [comment]
old laravel/ideas tickets linked to this:


 https://github.com/laravel/ideas/issues/2561
 https://github.com/laravel/ideas/issues/1409
 https://github.com/laravel/ideas/issues/1034
 https://github.com/laravel/ideas/issues/284

**Comment by allanlaal** [comment]
for googlers:


discussion here: https://github.com/laravel/framework/discussions/36595
also vote on others:
https://github.com/laravel/framework/discussions?discussions_q=type+hint
