### ISSUE TITLE
Add option to specify columns in Model

### ISSUE THREAD

**Issue by gunzino** [laravel/framework#15099]
Hello,

Actually, during developing my first project in Laravel I've got into situation during the optimazation proccess. The thing I wanted to do and thought it's easily possible was that I wanted to make specific model select only specific columns in the whole project. I mean that Eloquent won't do like "SELECT *..." but he will do like "SELECT column_list"... but in general using method like Model::find(), Model::where() etc..

The reason is that database is shared with more applications and there are blobs sized like 30-40kB that are not used in the web application at all so there is no point of selecting them always from database to the web application. 

I know there are some dirty solutions (using selectRaw) for that problem but I think it would be better to have some clean solution for that.

I would welcome to have variable similiar to $fillable that would specify which columns should be selected using Model and his native functions.

**Comment by GrahamCampbell** [comment]
This is achievable using scopes I think. Feel free to ask on the forums, and/or propose a solution on internals. Going to close this since we only process bug reports here.
