### ISSUE TITLE
controller __construct error

### ISSUE THREAD

**Issue by maniix123** [laravel/framework#15109]
Okay so what's the BIG DEAL with the controller __construct method on the controllers??? L 5.2 I was used to do:
$this->middleware(_my custom middleware_)->only([_some method here_]);

And it gives me this error!!
ReflectionException in Container.php line 734:
Class _my custom middleware class_ does not exist

What's the big deal? Am I missing something?? It's driving me nuts! I read the master docs and everything and I did everything exactly as written on the docs.

**Comment by GrahamCampbell** [comment]
Nothing should have changed with middleware registration.

**Comment by GrahamCampbell** [comment]
Please ask on the forums with your app specific issues.
