### ISSUE TITLE
[5.3] Envoy stories not working

### ISSUE THREAD

**Issue by Jamesking56** [laravel/framework#15107]
Hello,

Just writing my own Envoy deploy script and I noticed I can split up my tasks and run them all under one 'story'.

However, I can't run the story. When I call `envoy run <story>` as the documentation states, I get the following error:

````
 [Exception]                    
 Task "<story>" is not defined. 
````

I'm running Envoy 1.2.0 via a Homestead VM.

**Comment by yushine** [comment]
Same error, anyone can help?

**Comment by willrowe** [comment]
Is the name of the task literally `<story>` with the `<` and `>` at the beginning and end? If the name of the task is simply `story` you should try calling `envoy run story`, with no `<` or `>`.

**Comment by Jamesking56** [comment]
@willrowe No its another name I just used that as the sample, my actual command doesn't include `<` and `>`

**Comment by yushine** [comment]
@Jamesking56    It works well when I used macro instead of story.

**Comment by themsaid** [comment]
Thank you for reporting, looks like the stories syntax was added to the docs but no release was made on the GitHub repo, that's why it's not working :)

I've sent a note to Taylor on that, thanks again :)
