### ISSUE TITLE
Queues: do you need server control to use them?

### ISSUE THREAD

**Issue by GiacomoK** [laravel/framework#15111]
Hi,
I am looking for laravel guide and I am not able to figure out.
Do I need the server controll to use queues?

Are they similar to multithreading?

Thanks.

**Comment by fernandobandeira** [comment]
You'll need to run the command php artisan queue:listen on your server, this command will keep listening for new queues so as long as you can run this command you should be good to go (probably will need the server control), also if you don't have server control but can register cronjobs, via a cpanel then you could also create a workaround.
