### ISSUE TITLE
Creating a new provider using `php artisan make:provider` doesn't execute, but normal file creation works fine.

### ISSUE THREAD

**Issue by nitinsurana** [laravel/framework#15116]
Hi,

I'm using laravel 5.2

http://laravel.io/forum/02-08-2015-laravel-5-service-provider-not-working?page=1#reply-32554

Thanks

**Comment by srmklive** [comment]
You are doing it wrong. Whenever you create a new provider, you can simply register it with Laravel by using the following code block to the `register` method of your `App\Providers\AppServiceProvider.php`:

    $this->app->register(
        App\Providers\MyProvider::class
    );   

It is not an error with `make:provider` command, the error is how you are registering your custom service providers.

**Comment by nitinsurana** [comment]
I'm actually new to laravel. Completed the 18 episodes series from laracasts and the way to register a bean in Container is by using `$app->bind` and registering a service-provider is by adding to `config/app.php providers` array.

@srmklive Can you please provide some documentation or link that shows this new style of registering serviceProviders ? Although, just out of curiosity if adding to `config/app.php` is not the way to register providers, then why are all other providers mentioned in this file ?

**Comment by nitinsurana** [comment]
@srmklive Strangely, when I manually created the file (without using `make:provider`), I never registered the provider in the style you described. Instead, just added it to the `providers` array in `config/app.php` and it worked!

**Comment by srmklive** [comment]
@nitinsurana You can add a service provider either by adding to the `$providers` array in `config/app.php`  or using the method i mentioned. Both methods are fine. I just prefer the latter one.

**Comment by nitinsurana** [comment]
cool.. but the first one - creating the provider using `make:provider` and then registering in `config/app.php` doesn't work & hence, this issue reported.
