### ISSUE TITLE
Model::getForeignKey() could leverage Model::getKeyName()

### ISSUE THREAD

**Issue by PawelMysior** [laravel/framework#15114]
Method `getForeignKey()` of `Illuminate\Database\Eloquent\Model` snake cases the class basename and adds "_id" at the end to get the default foreign key for the relationship.

I think this could be improved and instead of adding the hardcoded string "_id", method `getKeyName()` or just the attribute `primaryKey` could be leveraged.

That way, if you set have a custom primary key set on your model, you don't have to specify a custom foreign key for relationships.

My proposal is to change this:

`Illuminate\Database\Eloquent\Model` line [2063](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Eloquent/Model.php#L2063):

```
    /**
     * Get the default foreign key name for the model.
     *
     * @return string
     */
    public function getForeignKey()
    {
        return Str::snake(class_basename($this)).'_id';
    }
```

To this:

```
    /**
     * Get the default foreign key name for the model.
     *
     * @return string
     */
    public function getForeignKey()
    {
        return Str::snake(class_basename($this)).'_'.$this->getKeyName;
    }
```

**Comment by srmklive** [comment]
I personally think this is good as it is right now.

**Comment by GrahamCampbell** [comment]
Thanks, but I agree this is already good.
