### ISSUE TITLE
Type on DatabaseManager connection() is only respected on first call to method

### ISSUE THREAD

**Issue by rokkamokka** [laravel/framework#15118]
When the `connection()` method on `DatabaseManager` is called for a connection that already exists, the type argument is ignored entirely. For example, if you were to call `DB::connection('mysql::write')->...` on a connection that already had been opened normally, you wouldn't get a write connection back.

It should either be clarified in the code that you cannot change the type of an already existing connection, or it should be changed so that you _can_ change the type of an already existing connection (see #15064).

**Comment by srmklive** [comment]
`DB::connection` simply gives temporary instantiation of a connection. I don't see any reason for it to be persisted.

**Comment by rokkamokka** [comment]
As far as I can tell, it already is persisted (by being saved in $this->connections). This is why subsequent calls to `connection()` with the same name disregards the type (it returns the persisted connection).

**Comment by GrahamCampbell** [comment]
The current code looks correct. This is just a subtlety.
