### ISSUE TITLE
Use Filesystem in Blade Engine

### ISSUE THREAD

**Issue by wayneashleyberry** [laravel/framework#15128]
A big pain point in running Laravel on [App Engine](https://cloud.google.com/appengine/) is that Blade assumes it has write access to a file system. Laravel already has a great filesystem abstraction so why not use that with Blade, defaulting to a local disk? Specifically in [Illuminate/View/Compilers/BladeCompiler](https://github.com/laravel/framework/blob/0066b5da6f009275348ab71904da2376c6c47281/src/Illuminate/View/Compilers/BladeCompiler.php#L116) and [Illuminate/View/Compilers/Compiler](https://github.com/laravel/framework/blob/0066b5da6f009275348ab71904da2376c6c47281/src/Illuminate/View/Compilers/Compiler.php#L73).

**Comment by GrahamCampbell** [comment]
Not possible since we have to be able to "require" those files later, so we can't use an abstraction.

**Comment by wayneashleyberry** [comment]
You could also `eval` the contents, I'm doing that with Memcache and it's great :)
