### ISSUE TITLE
[5.3] $model->save() returns false if the object hasn't changed

### ISSUE THREAD

**Issue by andjelicsasa** [laravel/framework#15126]
Hi,

So far I have used  the following way of determining if the model has been saved:
`if ($model->save())`
I see that with Laravel 5.3, if the object which is being saved has no changes on any attributes, the method returns false.
There are other cases, I assume, when the save method returns false, but in my case, if there are no changes in the object, it should be considered valid.
I use this logic for dynamic models, where attribute names and number is determined at the GUI generation. Also there is a lot of other logic in my code on different levels, so I would like to avoid writing additional logic for checking this outside of my gateway.

Is there a way that I can safely determine if the save() method returned false because it really failed, or because it didn't have anything to update?

Thanks in advance

**Comment by GrahamCampbell** [comment]
False just means there was nothing performed. It it failed, it'll throw an exception,

**Comment by andjelicsasa** [comment]
@GrahamCampbell Thanks for the quick answer.

So I can definitely rely that if the save() method returns false, the object is 100% identical in the DB?
