### ISSUE TITLE
Queued Job with Deleted Model

### ISSUE THREAD

**Issue by diogoazevedos** [laravel/framework#15129]
Imagine the situation. I have a delayed job to do something with the post model, but before the job process I delete the post.

Today I use the trait indicated in this [discuss](https://laracasts.com/discuss/channels/laravel/queue-model-not-found).

But now I'm thinking, this kind of exception should be treated in another place, for example in the `failed` method.

What do you think about this @taylorotwell and @GrahamCampbell?

```php
namespace App\Jobs;

use App\Post;
use Illuminate\Bus\Queueable;
use Illuminate\Support\Facades\Log;
use Illuminate\Queue\{InteractsWithQueue, SerializesModels};
use Illuminate\Contracts\Queue\ShouldQueue;

class Example implements ShouldQueue
{
    use InteractsWithQueue, Queueable, SerializesModels;

    protected $post;

    public function __construct(Post $post)
    {
        $this->post = $post;
    }

    public function handle()
    {
        Log::debug($post->title);
    }

    // The idea sketch
    public function foo(Exception $e)
    {
        if ($e instanceof ModelNotFoundException) {
            // do something
        }
    }
}
```

**Comment by diogoazevedos** [comment]
There is another issue with a similar problem #9347, but with soft deletes.

**Comment by GrahamCampbell** [comment]
Yeh, this is unfortunate, but is the expected behaviour.

**Comment by GrahamCampbell** [comment]
If in your queue jobs you don't actually need to interact with the model, and just needed to read some properties, I'd suggest just passing through those properties instead of a model.

**Comment by GrahamCampbell** [comment]
That's what I do for sending all my mail for example. makes it possible to send account deletion emails!

**Comment by diogoazevedos** [comment]
Thanks @GrahamCampbell.
