### ISSUE TITLE
Eloquent's casted 'date' field disrespects Carbon instance's timezone when saving to database.

### ISSUE THREAD

**Issue by lezhnev74** [laravel/framework#15122]
I faced a problem with saving date fields with Eloquent - it removed the timezone from Carbon instance and saved it in the timezone of the App. 

So here my full note: http://lessthan12ms.com/save-all-dates-in-utc-for-multi-timezone-apps/ 

And to save time this is an example here:
```php
<?php
dump(config('app.timezone'));
// OUTPUT: "UTC"

// We create a Carbon instance with timezone set to "GMT+4"
$date_in_local_timezone = Carbon::now('GMT+4');
// Let's  see the date we had initially
dump($date->toIso8601String())
// OUTPUT: "2015-01-01T12:00:00+0300"

// We then save it as "date" field
$model->some_date = $date_in_local_timezone;
$model->save();

// And then read it back from the model
dump($model->fresh()->some_date->toIso8601String());
// OUTPUT: "2015-01-01T12:00:00+0000"
```

As you can see we have the same datetime string but with timezone stripped.
I have my solution in the full note mentioned above. 

Is it something to make a PR for or am I missing something?

**Comment by GrahamCampbell** [comment]
This is intended. We only want to save to the db as UTC, and then you convert it on the other side.

**Comment by lezhnev74** [comment]
But I do pass Carbon instance with timezone but Eloquent discards it and saves as if I timezone is always UTC. It looks like not normal, no?

**Comment by GrahamCampbell** [comment]
Yes, that's correct. The timezone doesn't reflect how it's saved in the db. That's always UTC, then you need to convert it again when you get it out.

**Comment by lezhnev74** [comment]
I got your point about UTC default timezone.
But If I pass Carbon instsance with timezone - why Eloquent does not correctly transform it to UTC? 
I don't mind storing in UTC, but it should convert my timezone to UTC before saving. 
Why corrupt data stripping given timezone without conversion?

**Comment by thunberg** [comment]
I agree. Why is the timezone supplied simply truncated and ignored when saving it to the database instead of being correctly utilized to create an accurate version of the date & time in UTC?

**Comment by thunberg** [comment]
I propose the following one line fix to the problem, in Illuminate\Database\Eloquent\Model.php line 2904:

```php
    /**
     * Convert a DateTime to a storable string.
     *
     * @param  \DateTime|int  $value
     * @return string
     */
    public function fromDateTime($value)
    {
        $format = $this->getDateFormat();

        $value = $this->asDateTime($value)->copy();

		// ensure that if the datetime or carbon object we were given contained a timezone, we convert to the app timezone (instead of stripping it) before outputting a storable string
		return $value->setTimeZone(config('app.timezone'))->format($format);
    }
```

**Comment by mod3st** [comment]
Why the issue has been closed?

I think the problem is not the Eloquent's date fields, but database query bindings builder.

We can set a default timezone for our database (connection config):

`Illuminate\Database\Connectors\MySqlConnector::connect`
```
        if (isset($config['timezone'])) {
            $connection->prepare(
                'set time_zone="'.$config['timezone'].'"'
            )->execute();
        }
```

Maybe the default timezone for all connections should be `app.timezone` (if not specified)?

The problem is, `Illuminate\Database\Connection::prepareBindings` does not include timezone when parsing `DateTimeInterface` object:

```
            if ($value instanceof DateTimeInterface) {
                $bindings[$key] = $value->format($grammar->getDateFormat());
            }
```
So binding `Carbon` objects with different timezones will cause saving incorrect dates.

I think the general solution would be something like:
```
if ($value instanceof DateTimeInterface) {
    if (isset($config['timezone'])) {
        $value->setTimezone(new DateTimeZone($config['timezone']));
    }
    $bindings[$key] = $value->format($grammar->getDateFormat());
}
```

If `Connection` allows us to bind `Carbon` objects into the query, it should ensure their proper, coherent form while saving to the DB.

**Comment by MatteoOreficeIT** [comment]
**A notable good thing**: Laravel is plenty of "_ways of doing_", it demonstrates as many aspects were well engineered matching the most common / frequent web app requirements and use cases

**A notable bad thing**: I think this is a "_way of NOT doing_" which carries many uncertainties for novice Laravel developers , an artisan needs everything spoon-fed to concentrate on his app business logic
