### ISSUE TITLE
[5.3] Resubstituting model bindings is failing

### ISSUE THREAD

**Issue by garygreen** [laravel/framework#15123]
In the below simplified example the `get` doesn't get called.

```php
Route::pattern('{username}', '[a-zA-Z0-9_]+');

Route::bind('username', function($username) {
    return User::where('username', $username)->firstOrFail();
});

// Worked in 5.2
Route::matched(function($event) {
    $event->route->setParameter('user', $event->route->getParameter('username'));
});

Route::group(['middleware' => 'web'], function() {
    Route::get('{username}', function(User $user) {
        // Doesn't even enter. 404.
        return 'It works! ID: ' . $user->getKey();
    });
});
```

If I rename `$user` to `$user2` then it works.

It seems like the route model bindings are substituted after the router matched event, which makes it difficult to substitute my own bindings. This is also a breaking change from the way 5.2 worked and should be documented.

**Comment by fernandobandeira** [comment]
In your example it does look odd, but if you are using a controller action instead of the callback this behavior makes a little more sense.

**Comment by garygreen** [comment]
@fernandobandeira I've updated the example, it's actually a problem with when the bindings are subsituted. I find it a bit weird how the bindings are substituted in a middleware.... is there any way I can override the bindings?

**Comment by garygreen** [comment]
Hmm seems in 5.3 I don't need to replace the parameter at all, guess it's an easy fix.
