### ISSUE TITLE
Environment variables are null when config file is cached

### ISSUE THREAD

**Issue by DODMax** [laravel/framework#15130]
On Laravel 5.2.41-45, environment variables (.env) are _null_ when config file are cached.

`php artisan config:cache`

```php
class MyController extends Controller
{
    public function index()
    {
        dd(env('APP_ENV'));    //null
    }
}
```

**Comment by GrahamCampbell** [comment]
Yes, that's correct. You must only ever read the env variables from inside the config files. Read the config from inside the app to access the env variables you put in the config.

**Comment by GrahamCampbell** [comment]
If you want to get the application environment in particular, we have a function on the application object to do that.
