### ISSUE TITLE
Paginator total ignores SoftDeleteTrait

### ISSUE THREAD

**Issue by jwohlfert23** [laravel/framework#15139]
SQL query from normal `->count()` method
```select * from `profiles` where `profiles`.`type` = ? `profiles.approved` = ? and `profiles`.`deleted_at` is null```
SQL query from `getCountForPagination()` method
```select * from `profiles` where `profiles`.`type` = ? `profiles.approved` = ?```

**Comment by acasar** [comment]
Which Laravel version?

**Comment by jwohlfert23** [comment]
I'm using 5.3, but I believe the same applies to 5.2.

If I add `applyScopes` before `->paginate()`, then it works

**Comment by acasar** [comment]
Did some tests and works ok on my end.

Can you paste the entire query?

**Comment by jwohlfert23** [comment]
``` public function dashboard(StateRepository $states)
    {
        dd([
            Receipt::paginate()
        ]);
    }```

**Comment by jwohlfert23** [comment]
```
 public function dashboard(StateRepository $states)
    {
        dd([
            Receipt::paginate()
        ]);
    }
```

Should give me:
```select * from `receipts` where `receipts`.`deleted_at` is null```
But it gives me 

```select * from `receipts```` instead

**Comment by acasar** [comment]
That's very strange, I can't replicate this. Works ok for me including the total count. Are you using any package that could cause this?

**Comment by jwohlfert23** [comment]
Looks like I was. Sorry for the false alarm.
