### ISSUE TITLE
Parse error: syntax error, unexpected '.' in: Manager.php, DatabaseManager.php, Model.php, Builder.php

### ISSUE THREAD

**Issue by abr4xas** [laravel/framework#15133]
Hi there, i have a few problems 

> Parse error: syntax error, unexpected '.' in vendor/illuminate/database/[Capsule/Manager.php](https://github.com/illuminate/database/blob/master/Capsule/Manager.php#L199)
Parse error: syntax error, unexpected '.' in vendor/illuminate/database/[DatabaseManager.php](https://github.com/illuminate/database/blob/master/DatabaseManager.php#L317)
Parse error: syntax error, unexpected '.' in  vendor/illuminate/database/[Eloquent/Model.php](https://github.com/illuminate/database/blob/master/Eloquent/Model.php#L3164)
Parse error: syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in vendor/illuminate/database/[Query/Builder.php](https://github.com/illuminate/database/blob/master/Query/Builder.php#L1272)

I'm using: `"illuminate/database": "^5.3",`

**Comment by GrahamCampbell** [comment]
You need to upgrade to PHP 5.6 or higher to use Laravel 5.3.

**Comment by abr4xas** [comment]
@GrahamCampbell 

```bash
$ php -v
PHP 5.6.25 (cli) (built: Aug 29 2016 16:31:56) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```

**Comment by GrahamCampbell** [comment]
Your web server is not running that version though clearly, due to the parse error.

**Comment by GrahamCampbell** [comment]
Only your cli php is using php 5.6.
