### ISSUE TITLE
seeJson in tests shouldn't be order dependant for models

### ISSUE THREAD

**Issue by ThibaudDauce** [laravel/framework#15135]
Hi,

When I have a API endoint like:
```php
Route::get('/', function () {
    $user = new App\User(['name' => 'thibaud', 'email' => 'thibaud@example.com']);

    return compact('user');
});
```

And a test like:
```php
$user = new App\User(['name' => 'thibaud', 'email' => 'thibaud@example.com']);

$this->visit('/')
     ->seeJson([
         'user' => $user
     ]);
```

I should get green but instead I get:
```bash
Unable to find JSON fragment
["user":{"name":"thibaud","email":"thibaud@example.com"}]
within
[{"user":{"email":"thibaud@example.com","name":"thibaud"}}].
Failed asserting that false is true.
```

I think it's because in https://github.com/laravel/framework/blob/5de1561e1f5a0ee9776641108edf690571b05e0b/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php#L228, `Arr::sortRecursive` does not sort the model attributes.

If I test with `$user->toArray()` it's working.

Should I take care of this and try to allow developers to put models in the `seeJson` `$data` parameter or this is not something wanted?

**Comment by themsaid** [comment]
I think converting the model to array in the test makes more sense, in order for you to detect instances of Model and convert them inside `seeJsonEquals` you might complicate the code, specially that a JSON object can be of several nested levels.

**Comment by themsaid** [comment]
Closing this since it's not really a bug report, but please feel free to open a Pull Request with the suggested changes, or for suggestions and feature requests please use the https://github.com/laravel/internals repo.
