### ISSUE TITLE
form requests redirects to home with ajax request

### ISSUE THREAD

**Issue by Nigeltiany** [laravel/framework#15143]
I'm using Laravel 5.3 and form request always redirects to the homepage even when the content type of the request is application/json, when i intentionally omit a field i have set as required.
```php
public function rules(){
        return [
            'title' => 'required',
            'body' => 'required|max:1000',
            'tags' => 'required',
        ];
    }
```
```php
use App\Http\Requests\ArticleRequest;

class ArticleController extends Controller
{
    public function store(ArticleRequest $request){
    }
}
```
The status code returned is 200 in all situations.

**Comment by RDelorier** [comment]
Are you also setting the "Accept" header to json?

**Comment by charlesyapp** [comment]
What is your AJAX request URL? does it contain trailing forward slash?

**Comment by GrahamCampbell** [comment]
Please direct questions to the forums.
