### ISSUE TITLE
PasswordBroker and email attribute

### ISSUE THREAD

**Issue by iwex** [laravel/framework#15140]
Hello! 

Do we really need to pass email to check it with token?

We can search user by it's token in password_reset table.

**Comment by iwex** [comment]
I thought it was created to avoid conflicts, like we can have same tokens simultaneously. 
But then why do we have https://github.com/laravel/framework/blob/5.3/src/Illuminate/Auth/Passwords/DatabaseTokenRepository.php#L139

**Comment by themsaid** [comment]
A token gets deleted only after the reset is done, before that there's no guarantee that no tokens will be identical.
