### ISSUE TITLE
[5.3] Changes in Arr helper are backwards incompatible

### ISSUE THREAD

**Issue by aaemnnosttv** [laravel/framework#15147]
This issue has mostly to do with adherence to semantic versioning, of which I'm not sure how closely Laravel follows it, but I am assuming here that Laravel does not break backwards compatibility in minor version releases.

The problem I noticed is how the order of callback parameters changed in `Arr::first` for 5.3 back in https://github.com/laravel/framework/commit/99ca947f7362a105d61f401d3e45dc928bab783c

I am using the `tightenco/collect` Collection split library in a few projects of mine (but it may as well be `illuminate/support` in this case).  The problem is, my project had required the library in using `^5.2`.  According to semantic versioning, it should be compatible with all new versions up until the next major release, `6.0`.

However, now that 5.3 is released, my tests are failing now when installed with the latest version matching the constraint `v5.3.4`.  This is simply because my code is expecting the first parameter to be the key and the second to be the value (as it was in 5.2), and now that order is switched.

While I wholeheartedly agree that the reversed order is an improvement and more consistent with what is expected, I think that especially for packages which are as trusted as Laravel's it's more important to maintain backwards compatibility until the next major release.

What is the best way to proceed going forward for packages which depend on `illuminate/support` or `tightenco/collect`?

**Comment by crynobone** [comment]
The main issue here is that Laravel doesn't follow SemVer. Therefore you should tag a new major version whenever Laravel release a new 5.x release.

p/s: each 5.x release aren't minor release, it's actually major release.

**Comment by aaemnnosttv** [comment]
Are you sure?  Laravel went from 4.2 to 5.0.  If that was the case, what happened to 4.3-9?
Is that documented anywhere?

**Comment by crynobone** [comment]
> Laravel went from 4.2 to 5.0. If that was the case, what happened to 4.3-9?

x.0.0 = Pragmatic shift
x.y.0  = Major release
x.y.z  = Minor and patch release

> Is that documented anywhere?

https://twitter.com/taylorotwell/status/698103160003399680
https://twitter.com/taylorotwell/status/698146203540664321
https://medium.com/@vinkla/laravel-packages-and-semantic-versioning-f62dc5accee5#.ts3s0zcb7
https://www.lutro.me/posts/laravel-and-semver

**Comment by aaemnnosttv** [comment]
Ah ok, thanks for those links.  Seems strange that it isn't part of the official docs anywhere though.  Would be nice to see that added.

I did find the particular issue I'm having [is documented in the Upgrade Guide](https://laravel.com/docs/5.3/upgrade) right under Arrays.

Like I said, I was assuming that Laravel followed SemVer, but I see that is not the case. Good to know.

**Comment by GrahamCampbell** [comment]
Laravel's releases work like this:

* MAJOR: architectural changes
* MINOR: breaking changes and major new features
* PATCH: small new features and bug fixes
