### ISSUE TITLE
[5.3] Migration Timestamp Invalid Default Value

### ISSUE THREAD

**Issue by ssuhat** [laravel/framework#15144]
Hi, 

After upgrading to laravel 5.3 my migration with `timestamp` on migrate get error

` [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'create
  d_at'`

My migration:

      Schema::create('feedbacks', function (Blueprint $table) {
            $table->increments('id');
            $table->uuid('transaction_id');
            $table->uuid('user_id');
            $table->text('content');
            $table->decimal('rating', 3, 1);
            $table->softDeletes();
            $table->timestamp('created_at');

            $table->foreign('transaction_id')->references('id')->on('transactions');
            $table->foreign('user_id')->references('id')->on('users');

      });

Any solution?

Thanks

**Comment by charlesyapp** [comment]
I found this [article](https://mattstauffer.co/blog/how-to-disable-mysql-strict-mode-on-laravel-forge-ubuntu). It fixes the error by disabling MySQL strict mode, in your laravel config file database.php, set `'strict' => true` to `'strict' => false`.

**Comment by zsimple** [comment]
It is better to write migrate file
> $table->timestamp('created_at')->nullable();

From MySQL 5.7.x，formats like '0000-00-00 00:00:00' are not valid time string.

**Comment by immeyti** [comment]
@yappkahowe what is strict??

**Comment by NwosuCC** [comment]
Or if you even want CURRENT_TIMESTAMP as default value...

`$table->timestamp('created_at')->useCurrent();`

**Comment by gorans93** [comment]
In the case when do not need default value, you can set timestamp to nullable
`$table->timestamp('mycolumn')->nullable();`
