### ISSUE TITLE
Storage::delete does not return accurate result

### ISSUE THREAD

**Issue by thunberg** [laravel/framework#15142]
Storage::delete with the local driver always returns true:

```php
    public function delete($paths)
    {
        $paths = is_array($paths) ? $paths : func_get_args();

        foreach ($paths as $path) {
            try {
                $this->driver->delete($path);
            } catch (FileNotFoundException $e) {
                //
            }
        }

        return true;
    }
```

This is not helpful when attempting to first confirm an object's associated file upload was successfully deleted before deleting the object itself.

Since the local filesystem driver already returns the correct result:

```php
    public function delete($path)
    {
        $location = $this->applyPathPrefix($path);

        return unlink($location);
    }
```

Why can't we change the delete function in FilesystemAdapter to:

```php
    public function delete($paths)
    {
        $paths = is_array($paths) ? $paths : func_get_args();

		$success = true;

        foreach ($paths as $path) {
            try {
                $success = $this->driver->delete($path);
            } catch (FileNotFoundException $e) {
                $success = false;
            }
        }

        return $success;
    }
```

I'm relatively new to Laravel, so apologies if I've missed a more appropriate way to handle this -- thank you either way.

**Comment by srmklive** [comment]
I would suggest that you do it like this:

    if ($this->driver->has($path)) {
        $this->driver->delete($path);
    }

**Comment by thunberg** [comment]
Thank you for the reply, but that doesn't handle the case when a delete fails.

**Comment by thunberg** [comment]
Thank you for the fix.
