### ISSUE TITLE
[5.3] Memcached + Queue + RestartCommand

### ISSUE THREAD

**Issue by Belphemur** [laravel/framework#15155]
Hello,

I uncovered a bug with the Queue Worker when used with Memcached as cache driver (not queue driver).
# Config
- Laravel 5.3
- PHP 7.0
- Memcached 1.4.31
# What happens

When using the queue:restart to tell the queue to stop, the command set in the cache the "illuminate:queue:restart" to the current time. The queue worker detects it and stop.

Now you start the queue again, it stops directly. The condition for the queue worker to stop is met with the "illuminate:queue:restart" still in the cache. And that is only when using Memcached as cache driver. With Redis no problem, neither with File.
# Steps
1. Set Memcached as cache driver
2. Launch the queue
3. run the 'queue:restart' cmd
4. wait for the queue to stop
5. relaunch the queue worker
6. the queue worker stops directly
# Debugging

The Memcached module is sometimes returning "null" for the retrieval of the key "laravel:illuminate:queue:restart" even if the key is present in the Memcache server. To be exact it's returning null 50% of the time. If I call twice the get, the first one will return null and the second one the value.

**Comment by themsaid** [comment]
@Belphemur can you open a PR with a proposed fix?

**Comment by Belphemur** [comment]
@themsaid PR done #16488
