### ISSUE TITLE
[4.2] Auth::attempt() doesn't work when password starts with quotation mark

### ISSUE THREAD

**Issue by envision** [laravel/framework#15151]
Login **Auth::attempt()** method doesn't work with passwords starting with quotation mark (") character.

Could someone verify this with their system?

**Comment by KKSzymanowski** [comment]
On Laravel 4.2.19 it works for me.
```php
Route::get('/', function() {
    var_dump(Auth::attempt(['login' => 'test', 'password' => '"test']));
    Auth::logout();
});
```
outputs
```
bool(true)
```
Same with single quote `'`

**Comment by envision** [comment]
This install is 4.2.17 and just verified...

using password without starting " :

    bool(true)

using password with starting " :

    bool(false)

**Comment by GrahamCampbell** [comment]
Only 5.1 or 5.3 are officially supported here.
