### ISSUE TITLE
Arr::append and array_append suggestion

### ISSUE THREAD

**Issue by jszobody** [laravel/framework#15161]
I often need to append an element to an array. There is an existing helper `array_prepend` but no corresponding `array_append` at the moment.

This would behave like PHP's `array_push` with the difference that it returns the modified array. Just like `array_prepend` today is the equivalent of PHP's `array_unshift` except returning the modified array.

The existing `array_add` helper isn't a good fit for my use case because it requires a key and value. 

I'm happy to submit a PR, just wanted to first ask if this would be well received or not?

**Comment by KKSzymanowski** [comment]
Why is this insufficient?
```php
$array = [
    1, 
    2, 
    3,
];

$array[] = 4;
```

**Comment by jszobody** [comment]
Of course you can use built in array management. That goes for a lot of Laravel's existing helper methods.

If you wanted to add a key/value pair to your array:

```
$array["newelement"] = 4;
```

And yet Laravel provides `array_add`:

```
array_add($array, "newelement", 4);
```
If you want to add an element to the beginning of an array you can always do this:

```
array_unshift($array, 4);
```

And yet Laravel provides `array_prepend`:

```
array_prepend($array, 4);
```

The big difference? Laravel's helper methods _return the modified array_. That can be helpful when you need to modify and array and return it, Laravel's methods let you do that a bit cleaner.

If you want to use native PHP array management, go for it. I'm only suggesting that an `append` method be added, consistent with the existing `prepend` method because I find them useful.

**Comment by GrahamCampbell** [comment]
Thanks, but I don't think there's much demand for this.

**Comment by KKSzymanowski** [comment]
@jszobody Sorry, I tried.
