### ISSUE TITLE
Should returning toJson in a controller have the correct json headers sent

### ISSUE THREAD

**Issue by ChangePlaces** [laravel/framework#15165]
Should there be a difference in a controller method that handles a view between: `return Foo::find(1);`  and `return Foo::find(1)->toJson();`?

It seems only the former sends the correct json headers in 5.2? The latter however is easier to read / understand for other people to read and see what's going on

**Comment by RDelorier** [comment]
I think since toJson returns a string it wouldn't be right to automatically assume it's valid json during content negotiation. On the other hand returning an object that is json serialization puts the responsibility on the object to provide valid json. A better way to show your intent would be to set the header inline with `return response()->json($data)`

**Comment by ChangePlaces** [comment]
Returning ::Find(1)->toJson() still puts the responsibility of providing valid json on the object

**Comment by GrahamCampbell** [comment]
You can use the accepts method I added to the request object to ask the client if it accepts a given content type.

**Comment by ChangePlaces** [comment]
@GrahamCampbell I don't understand what the accepts method has to do with returning a json header when the countroller handler outputs json.

**Comment by GrahamCampbell** [comment]
I don't understand your point?

**Comment by ChangePlaces** [comment]
As nor do I yours. The original question has nothing to do with whether the client accepts JSON content or not

**Comment by crynobone** [comment]
```php
Model::find(1)->toJson();
```

This return a string, correct?

So how on earth would Laravel know that you're returning a string containing `json`, for all it know you might actually want to return `text/html` or `text/plain`. This is where `response()->json()` are use to be clear that you're expecting to return string to be handled as a `json`.

**Comment by ChangePlaces** [comment]
For all Laravel knows, I may want to return an object as XML rather than JSON, so how on Earth does it know I want to return a json object when returning an object. There's no difference between my question and what's actually happening. In answer to *your* question, the `toJson` method could always return an object such as `JsonString` which has the `toString` overloaded to make its use invisible and Laravel can test for that on output as to whether to send the Json headers or not.

**Comment by ChangePlaces** [comment]
thank you for not understanding but just closing this issue.
