### ISSUE TITLE
[5.3] Problem with installed

### ISSUE THREAD

**Issue by dulumao** [laravel/framework#15172]
command: /Applications/MAMP/bin/php/php7.0.0/bin/php /usr/local/bin/composer create-project --prefer-dist laravel/laravel Test

laravel/framework suggests installing pda/pheanstalk (Required to use the beanstalk queue driver (~3.0).)
laravel/framework suggests installing predis/predis (Required to use the redis cache and queue drivers (~1.0).)
laravel/framework suggests installing pusher/pusher-php-server (Required to use the Pusher broadcast driver (~2.0).)
laravel/framework suggests installing symfony/psr-http-message-bridge (Required to psr7 bridging features (0.2.*).)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.4.0)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize

Parse error: parse error, expecting `'&'' or `"variable (T_VARIABLE)"' in /Workspace/Test/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 475
Script php artisan optimize handling the post-update-cmd event returned with an error

  [RuntimeException]
  Error Output:

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

**Comment by GrahamCampbell** [comment]
Upgrade to the latest php 7.0.x please.

**Comment by GrahamCampbell** [comment]
Hmm, actually, looks like composer is not using your php 7 install.
