### ISSUE TITLE
Password Reset (routeNotificationForMail)

### ISSUE THREAD

**Issue by bvelastegui** [laravel/framework#15186]
If using `auht:make` scaffolding, for password reset is necessary add function `ruouteNotificationForMail` in User model

```php
public function ruouteNotificationForMail()
{
    return $this->getEmailForPasswordReset();
}
```
This is correct?

**Comment by themsaid** [comment]
The `email` property will be used by default, so no, you don't have to add the function to the model if you don't want to.

**Comment by bvelastegui** [comment]
if i have custom email property ?

**Comment by themsaid** [comment]
In that case yes.

**Comment by bvelastegui** [comment]
ok ty!
