### ISSUE TITLE
Altering a database table colum in a migration fails, because column names are not escaped

### ISSUE THREAD

**Issue by tueena** [laravel/framework#15195]
I have the following code in a migration:

	Schema::table('users', function (Blueprint $table) {
		$table->string('passwordHash')->nullable()->change();
	});

Thrown exception:

    [Illuminate\Database\QueryException]
    SQLSTATE[42703]: Undefined column: 7 ERROR:  column "passwordhash" of relation "users" does not exist (SQL: ALTER TABLE users ALTER passwordHash DROP NOT NULL)

This sql statement would not fail:

    ALTER TABLE users ALTER "passwordHash" DROP NOT NULL

Database is postgresql.

**Comment by srmklive** [comment]
What exactly are you trying to do when this specific error is thrown?

**Comment by bastianfenske** [comment]
I tried to write a migration, that changes the database column "passwordHash" of the database table "users" of a postgresql database to allow NULL values. Nothing else. Or what exactly do you need to know? I don't understand your question.

**Comment by tueena** [comment]
I tried to write a migration, that alters the "passwordHash" column of the "users" table of a postgresql database that it accepts NULL values. I think, I don't understand your question. What exactly do you want to know beyond that? What the column is for or why I use camel cased database columns in a postgresql database?

**Comment by lasselehtinen** [comment]
Can confirm this. This is something to do with case sensitivity. As you can see from the error message passwordHash !== passwordhash. You can work around this if you change the original column name to "passwordhash" or "password_hash".

Somebody more knowledgeable of the Laravel internals can probably figure out what might be causing this. I know it uses the doctrine/dbal and as [far as I debugged this](https://github.com/doctrine/dbal/blob/b6b247a3c6039f9364d061f15ef6c7aaef08d9c3/lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php#L550), it seems to return the query in correct case.

`string(50) "ALTER TABLE users ALTER passwordHash DROP NOT NULL"`

**Comment by lasselehtinen** [comment]
Only PostgreSQL seems to be affected, this works just fine on MySQL and SQLite.

**Comment by tueena** [comment]
They simply missed to write the table and column names in double quotes. Better "workaround" then to change the database scheme (although underscores are something like a standard in PostgeSQL as far as I know) is to use plain old SQL. Should have done this from the beginning of this project on...

**Comment by themsaid** [comment]
I think this issue is more related to Doctrine than laravel?

**Comment by srmklive** [comment]
To me this is an issue related to Doctrine. Refer to this https://github.com/doctrine/dbal/blob/2.5/lib/Doctrine/DBAL/Schema/Table.php#L667
