### ISSUE TITLE
[5.3] Major bug in redis throttle

### ISSUE THREAD

**Issue by garygreen** [laravel/framework#15197]
The throttle class uses [`->add`](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Cache/RateLimiter.php#L61) when setting the decay time, if you go through to the cache repository for redis it doesn't actually have a `add()` method so instead uses `put()` -- this overwrites the decay time every time. You can test this by https://try.redis.io/

SETEX test 10 "Hello"
GET test // should print "Hello"
SETEX test 500 "Hello"
... wait 15 seconds
GET test // Will print "Hello" - it should print nil.

This is essentially the same commands laravel is running for the redis [`put()`](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Cache/RedisStore.php#L92)

**Comment by GrahamCampbell** [comment]
I've not noticed any issues?

**Comment by garygreen** [comment]
@GrahamCampbell do you use redis?

**Comment by GrahamCampbell** [comment]
Yep. Been using it for months.

**Comment by garygreen** [comment]
My bad if I scrolled down a bit https://github.com/laravel/framework/blob/7d116dc5a008e69c97f864af79ac46ab6a8d5895/src/Illuminate/Cache/Repository.php#L252
