### ISSUE TITLE
SerializesModels should remember the specific collection class

### ISSUE THREAD

**Issue by rudiedirkx** [laravel/framework#15202]
With a custom model collection (e.g. `App\Database\ModelCollection`), when it's empty and you add it to a Queueable, it's serialized without the specific collection class, and unserialized into a `Illuminate\Database\Eloquent\Collection`, because it's empty. `ModelIdentifier` should remember which collection class it was, so it can recreate it exactly.

I think it should even remember the order and doubles, but that might be a step too far.

**Comment by srmklive** [comment]
I think it will automatically your custom collection class if your class extends `Illuminate\Database\Eloquent\Collection`

**Comment by rudiedirkx** [comment]
It doesn't.

It creates an eloquent collection if the collection is empty (wrong), and the model type's default collection if it's not (rarely wrong, but still wrong).

Relevant code: https://github.com/laravel/framework/blob/7d116dc5a008e69c97f864af79ac46ab6a8d5895/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php#L54

There's a simple workaround of course: always expect an eloquent collection, and always convert it to a custom collection, but that seems like a waste.

If I serialize my thing like X, and it's unserialized, I expect X back literally. Doesn't seem irrational.
