### ISSUE TITLE
[Proposal] API Exception Handler

### ISSUE THREAD

**Issue by malhal** [laravel/framework#15210]
Since we now have API support in App\Providers\RouteServiceProvider via the mapWebRoutes and mapApiRoutes methods I believe a great new feature would to also have matching API support in exception handling. Right now all of the handling is designed for websites (inc. form posts and ajax) and it isn't entirely obvious how or where API handling should be implemented. E.g. a developer may try to reuse as much of the built-in handling as possible, may see the calls to expectsJson, however that would be a mistake. Instead, and to keep them on the right track this could be achieved with the following modification to App\Exceptions\Handler

```
public function render($request, Exception $exception)
    {
        // by checking the url and not expectsJson we can differentiate between API requests and form posts, e.g. ajax that might return validation errors, see  convertValidationExceptionToResponse.
        // api/* matches the default implementation of mapApiRoutes
        if($request->is('api/*')){
            return $this->renderForApi($request, $exception);
        }
        return parent::render($request, $exception);
    }

public function renderForApi($request, Exception $exception){
   // some default json returned, see below
}
```

This is my current implementation of this method, some or all of it could be used. It doesn't follow any official spec just what I think is suitable for a default implementation. The spec is that error key will always appear in the case of an exception, with the name of the exception. A validation key will appear if that was the exception and it will contain the error messages array. The message key contains the exception message if it isn't empty, in case of a QueryException it will contain the database error message without including the SQL if not in debug mode. Status codes are the same as the web renderer. Lots of APIs, e.g. Facebooks always return 200 so we could also just do that for the default implementation to keep it simple.

```
   public function renderForApi($request, Exception $exception){
        $statusCode = 500;
        
        if ($exception instanceof HttpExceptionInterface) {
            $statusCode = $exception->getStatusCode();
        }
        
        $error = ['error' => class_basename($exception)];
        $message = $exception->getMessage();

        if($exception instanceof ValidationException){
            $error['validation'] = $exception->validator->errors()->getMessages();
            $statusCode = 422;
        }
        else if($exception instanceof QueryException){
            // hide the sql and bindings if not in debug.
            if(!config('app.debug')) {
                $message = $exception->getPrevious()->getMessage();
            }
        }
        else if($exception instanceof AuthorizationException){
            $statusCode = 403;
        }
        
        if(!empty($message)) {
            $error['reason'] = $message;
        }
        
        return response()->json($error, $statusCode);
    }
```

Note, FlattenException::create used in convertExceptionToResponse does some of this and more so could be reused, e.g. if not an HttpException it uses 500, and it builds a stack trace if app.debug is on. Unfortunately its toArray method isn't suitable for a JSON response because it uses a indexed array instead of the associative we need.

Illuminate\Foundation\Exceptions\Handler could also be refactored to achieve some of this or tidy it up, e.g. the following issues in it could also be fixed on the way:

Doesn't match naming scheme of other methods, convertExceptionToResponse and convertValidationExceptionToResponse:
    protected function unauthenticated($request, AuthenticationException $exception)

    Missing the request param:
protected function convertExceptionToResponse(Exception $e)

Not required in case of an API error since we don't want to lose the info that it was a AuthorizationException:
    protected function prepareException(Exception $e)

**Comment by GrahamCampbell** [comment]
There are already lots of ways people do this, so we've kept the core minimal. Feel free to check out https://github.com/GrahamCampbell/Laravel-Exceptions. It looks like it could do what you want.
