### ISSUE TITLE
[5.3] JSON where clause is not working as expected in Eloquent

### ISSUE THREAD

**Issue by mohd-isa** [laravel/framework#15221]
With the following example, the row record is updated successfully 

```
DB::table('users')
        ->where('id', 1)
        ->update(['meta->col' => true]);
```

But when it comes to Eloquent, it doesn't works as expected, it always fails to update the database.

```
$user = User::find(1);
$user->update(['meta->col' => true]);
```

**Comment by srmklive** [comment]
Is there any error thrown when try to update through eloquent?

**Comment by themsaid** [comment]
Are you using MySQL?

**Comment by mohd-isa** [comment]
> Is there any error thrown when try to update through eloquent?

There is no error. Update method returns "false" and database isn't updated.


> Are you using MySQL?

Yes, MySQL 5.7, using latest Homestead setup.

**Comment by themsaid** [comment]
I can't regenerate this behaviour on a 5.3 installation, are you sure there aren't any eloquent events halting the update?

**Comment by mohd-isa** [comment]
> I can't regenerate this behaviour on a 5.3 installation, are you sure there aren't any eloquent events halting the update?

I'm not using any Eloquent events at all. 

All I am doing is a simple code, created a model with 'meta' as fillable
and 'json' column as a type in migration
then using the above code

**Comment by RomainLanz** [comment]
Hey everyone.

Is it normal that you have single quote mark on your array?

```php
$user->update(['meta->col' => true]);
```

**Comment by themsaid** [comment]
What's the initial value of the field?

**Comment by mohd-isa** [comment]
> What's the initial value of the field?

{"col":false}

**Comment by themsaid** [comment]
I can't reproduce the issue on same setup, you need to debug `Model::save()` and see what data is passed, and what causes the output to be false.

**Comment by themsaid** [comment]
@mohd-isa did you get the chance to debug further?

**Comment by mohd-isa** [comment]
I have tested it on a new Laravel installation and it works fine.

Thanks
