### ISSUE TITLE
Eloquent HasManyThrough

### ISSUE THREAD

**Issue by ryangurn** [laravel/framework#15225]
When creating a HasManyThrough the algorithm in eloquent will force the intermediate model to have an id column which it then matches up with the final model. Please let me know if I am not using eloquent to the standard but I think that there might be a bug here. 

rounds 
-id
-name

entities
-id
-info

rounds_entities
-round_id
-entity_id

**Comment by Shkeats** [comment]
Logically there has to be a unique reference to both your Rounds and Entities model in the intermediate table. As per the docs though you can customise what the field names are when you declare the relationship so if you don't want to the use round_id or entity_id you don't have to.

```

 return $this->hasManyThrough(
            'App\Post', 'App\User',
            'country_id', 'user_id', 'id'
        );
```

https://laravel.com/docs/5.3/eloquent-relationships#has-many-through

**Comment by fernandobandeira** [comment]
You've got the wrong idea of ``` HasManyThrough ``` what you are doing is actually an ``` belongsToMany ```.

``` HasManyThrough ``` requires 3 models, for example

country
id
name

user
id
country_id
name

posts
id
user_id
name
text

So with it you could $country->posts();

**Comment by ryangurn** [comment]
Ok so its just me not understanding... Thanks for helping
