### ISSUE TITLE
When 'create'ing an object, fields with null values are not included in returned object

### ISSUE THREAD

**Issue by ChangePlaces** [laravel/framework#15220]
Passing in an array of attributes to `$obj = Foo::create(['bar' => 4]);` where field `zar` is to be null, therefore not included in the the attributes array means that `zar` will not be included in $obj. I am outputting the object as json by returning the object from the controller

Why not? Zar is a valid field of `Foo` and should show the null value.

To remedy this, I'm having to `find` the object after creation to populate the null fields which is crazy!

**Comment by GrahamCampbell** [comment]
You need to setup the defaults correctly. See the docs.

**Comment by ChangePlaces** [comment]
No, maybe you don't understand again, but - for example - a `useCurrent` on the schema can't be set up on the model as a default.

**Comment by guney** [comment]
@GrahamCampbell @taylorotwell this should be opened again. I'm experiencing the same issue with 5.3. Wasn't happening in older versions with the same codebase.
