### ISSUE TITLE
Adding option to set primary key on modifyIncrement

### ISSUE THREAD

**Issue by IAmJulianAcosta** [laravel/framework#15238]
Currently `modifyIncrement` adds `PRIMARY KEY` by default to column:

https://github.com/laravel/framework/blob/master/src/Illuminate/Database/Schema/Grammars/MySqlGrammar.php#L735

Would be fine if is possible to add an option to NOT add primary key to this column, when adding another primary key.

Example that fails:
```
$table->unsignedInteger ('id', true);
$table->integer('foo')->unsigned ();
$table->primary(array('id', 'foo'));
```

Error: 1068 Multiple primary key defined.

If there is an option to adding an autoincrement index without primary key, like: `$table->unsignedInteger ('id', true, false);`, would help to fix this error. 

References: 

- http://stackoverflow.com/questions/23923148/how-to-create-multiple-primary-key-with-auto-increment-include-in-laravel-migrat
- http://laravel.io/forum/06-21-2014-migration-add-primary-key-to-id-username-email?page=1

**Comment by themsaid** [comment]
Why don't you add a unique index for the id & foo columns and keep the id primary?

**Comment by AmanAgarwal041** [comment]
First Paragraph of the accepted answer in the below link will give you the reason of not having an auto-incremented column as your primary key.
 http://dba.stackexchange.com/questions/3467/mysql-why-is-auto-increment-limited-to-just-primary-keys

**Comment by themsaid** [comment]
I'm closing this since it's not actually a bug report.

For suggestions and feature requests please use the https://github.com/laravel/internals repo.
