### ISSUE TITLE
L5.3 Can I customize the User model field to use for authenticating the "username" in the LoginController?

### ISSUE THREAD

**Issue by scibe** [laravel/framework#15237]
I used to be able to define this in my AuthController in L5.2

`$projected $username = 'username'`

This stopped working when I upgraded to L5.3. Upon inspection it looks like the username function in the Trait \Illuminate\Foundation\Auth\AuthenticatesUsers always returns 'email' as the username field.

`/**
     * Get the login username to be used by the controller.
     *
     * @return string
     */
    public function username()
    {
        return 'email';
    }`

Is it still possible to customize the field to be used while still using the stock LoginController without modifying the Illuminate AuthenticatesUsers.php file?

**Comment by fernandobandeira** [comment]
Check #14819

**Comment by scibe** [comment]
Doh! I didn't search hard enough. That solution in #14819 will work perfectly. Thanks!
