### ISSUE TITLE
date_format validation rule behaving as if required

### ISSUE THREAD

**Issue by andrewtweber** [laravel/framework#15245]
The `date_format` and `after` (probably `before` as well) validation rules are all behaving as if they are required.

If you pass in a `null` value, then all of these rules fail. In 5.2 they would pass.

They **should** pass in my opinion; if you want to disallow `null` values then you should also have the `required` rule.

**Comment by themsaid** [comment]
`null` isn't an accepted value anymore, if you want a field to be nullable you need to pass the `nullable` rule.

```
['date' => 'nullable|after:2016-09-05']
```

**Comment by andrewtweber** [comment]
Thanks, I missed that, my fault.

**Comment by themsaid** [comment]
No worries :)
