### ISSUE TITLE
DatabaseTransactions not working on production

### ISSUE THREAD

**Issue by Thijmen** [laravel/framework#15258]
Hello there,

This is my repository; https://github.com/Thijmen/laravel-bug
I stumbled on this 'bug' because my database was acting weird on production.

When I clone the repo on my Mac, connect with the database, run the tests it works all fine. Yet, on my server it fails after the first run.

# Steps to reproduce
- `git clone https://github.com/Thijmen/laravel-bug.git`
- `composer install`
- Fill in .env with correct credentials
- `php artisan migrate`
- `vendor/bin/phpunit`
Result:
```
 vendor/bin/phpunit
PHPUnit 5.5.4 by Sebastian Bergmann and contributors.

..F                                                                 3 / 3 (100%)

Time: 170 ms, Memory: 10.00MB

There was 1 failure:

1) UserTest::testCreateOther
Failed asserting that 1 matches expected 2.

/home/thijmen/testing/tests/UserTest.php:33

FAILURES!
Tests: 3, Assertions: 3, Failures: 1.
```

# Server info
```
php -v
PHP 7.0.10 (cli) (built: Aug 25 2016 18:04:55) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.10, Copyright (c) 1999-2016, by Zend Technologies
```
```
MySQL:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 54115
Server version: 5.5.50-cll MySQL Community Server (GPL)
```

Anyone has an idea what is going wrong? In my production project I have this in my `TestCase`:

```php
 public function setUp() {
        parent::setUp();
        DB::beginTransaction();
    }

    public function tearDown()
    {
        DB::rollBack();
        parent::tearDown();
    }
```

**Comment by Thijmen** [comment]
Update: I found out that DatabaseTransactions are not working with `MyISAM` but are working with `InnoDB`. Anyone who can confirm this too and is there a way to make `InnoDB` the default engine when creating migrations?

**Comment by thecrypticace** [comment]
iirc if the MySQL server doesn't have it set as the default you can set it globally here:

https://github.com/laravel/laravel/blob/master/config/database.php#L66

**Comment by srmklive** [comment]
As far as i know `MyISAM` doesn't support database transactions. You will need to change the default database engine to `InnoDB`.
