### ISSUE TITLE
Upgrading from 5.2 to 5.3, parse error in Eloquent/Model.php on line 3164

### ISSUE THREAD

**Issue by wout** [laravel/framework#15256]
Hi,
I just upgraded form Eloquent 5.2.x to 5.3.x and I'm getting the following error:

```cli
Parse error: parse error in vendor/illuminate/database/Eloquent/Model.php on line 3164
```

Line `3164` is:

```php
return ! $this->isDirty(...func_get_args());
```

If I remove the three dots, the following error appears:

```cli
parse error, expecting `'&'' or `"variable (T_VARIABLE)"' in vendor/illuminate/database/Query/Builder.php on line 1268
```

Which maps to:

```php
public function groupBy(...$groups)
```

By removing these three dots, the problem is solved.
I'm running `PHP 5.6.25 (cli) (built: Aug 31 2016 10:13:30)`, am I missing something?

**Comment by GrahamCampbell** [comment]
You web server must be running on PHP 5.5, not 5.6.

**Comment by GrahamCampbell** [comment]
Don't remove those dots. You'll break that function.

**Comment by wout** [comment]
Ok, so PHP 5.6 works fine with Eloquent 5.2 but not with 5.3. And PHP 5.5 works fine with Eloquent 5.3. Removing the dots unbreaks the library. A bit of an explanation might be in place here :)
