### ISSUE TITLE
Running php artisan migrate:refresh or reset fails

### ISSUE THREAD

**Issue by evanmalmud** [laravel/framework#15260]
Then running php artisan migrate:reset or refresh I get the following error back:  

```
  [ErrorException]                                                                                                 
  Argument 2 passed to Illuminate\Database\Schema\Builder::create() must be an instance of Closure, none given, c  
  alled in /var/www/html/BBLM/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 238 and   
  defined
```

I could not find any information online and the migrations work, but I need to now drop the database and recreate and then php artisan migrate to have a working database with my new changes. Is there something I'm missing here?

**Comment by GrahamCampbell** [comment]
Please ask on the forums and I'm sure someone can help you there.
