### ISSUE TITLE
OpenSSL dependency for artisan passport:keys and passport:keys in docs

### ISSUE THREAD

**Issue by misog** [laravel/framework#15265]
Hi, docs say nothing about openssl dependency [https://laravel.com/docs/5.3/passport](https://laravel.com/docs/5.3/passport)

```
php artisan passport:install
'openssl' is not recognized as an internal or external command,
operable program or batch file.
'openssl' is not recognized as an internal or external command,
operable program or batch file.
Encryption keys generated successfully.
Personal access client created successfully.
Password grant client created successfully.
```

**Comment by bonzai** [comment]
https://laravel.com/docs/5.3/installation:
> OpenSSL PHP Extension

**Comment by GrahamCampbell** [comment]
This is not talking about the open ssl extension. This error is related to trying to execute openssl on the system itselv.

**Comment by themsaid** [comment]
OpenSSL is required in the laravel/framework composer.json already. This should alert on installation in case it's missing.

**Comment by misog** [comment]
@themsaid I installed Laravel 5.3 via laravel/installer and I do not have ext-openssl included in composer.json - anyway, this is not related to OpenSSL PHP Extention, but OpenSSL itself - Passport needs OpenSSL binary.

**Comment by GrahamCampbell** [comment]
> OpenSSL is required in the laravel/framework composer.json already. This should alert on installation in case it's missing.

As I said, this is nothing to do with the openssl extension.

> this is not related to OpenSSL PHP Extention, but OpenSSL itself - Passport needs OpenSSL binary.

Yeh, exactly.

**Comment by GrahamCampbell** [comment]
We could probably mitigate this by using phpseclib.

**Comment by samgreenwood** [comment]
I've created a pull request for this here https://github.com/laravel/passport/pull/72

**Comment by themsaid** [comment]
Closing since the PR got merged.
