### ISSUE TITLE
Slug not support all allowed chars

### ISSUE THREAD

**Issue by piotrooo** [laravel/framework#15261]
I want to slug some string and when my string contains special chars e.g.: `?` or `!` this chars are removed.

Allowed chars ([RFC 3986](https://tools.ietf.org/html/rfc3986#section-2)):
`ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~:/?#[]@!$&'()*+,;=`
this chars not need to be percent-encoded, but they are removed.

How to reproduce:
==============

```
echo str_slug('Some string ?');
```

Should be:
========

```
some-string-?
```

Now:
====

```
some-string
```

**Comment by Macsch15** [comment]
Use `\Illuminate\Support\Str::ascii('Some string ?')` instead of `str_slug()`.

**Comment by GrahamCampbell** [comment]
Our slug method intentionally drops punctuation since it doesn't add any real meaning for slugs.
