### ISSUE TITLE
[5.3] Notification using database queue storing as a payload of 0 

### ISSUE THREAD

**Issue by DaneEveritt** [laravel/framework#15272]
I'm having a very strange issue that I haven't been able to work out using `5.3.6` and a database queue. I have this [AccountCreated](https://github.com/Pterodactyl/Panel/blob/feature/notifications/app/Notifications/AccountCreated.php) notification that is structurally the same as a [SendPasswordReset](https://github.com/Pterodactyl/Panel/blob/feature/notifications/app/Notifications/SendPasswordReset.php) notification.

The password reset notification works without issues in terms of queueing and then sending by email. However, the account creation notification *only* works if it *does not* get put into a queue. I can receive the notification email just fine if the `implements ShouldQueue` is removed. However, when it does implement `ShouldQueue` I can add a user and not hit any errors, but when the notification is added to the database the `payload` column is simply `0`.

This issue appears to be related to #15235 but coming from the notifications system. The odd thing is that the password reset notification works fine queued or not queued. I attempted a default notification (`php artisan make:notification TestNotification`) and attempted to queue that notification as well and the same `payload = 0` issue occurred.

I should note that the `SendPasswordReset` notification is being handled by Laravel's built-in password reset system, I simply modified the template it was using as indicated by the documentation.

**Comment by kevdotbadger** [comment]
Just tried replicating this and I can't. I started a new project, migrated the jobs table, set the queue to database and added the auth stuff. I copied your AccountCreated notification and changed line 70 on `RegisterController` to `$user->notify(new AccountCreated('token'));`. The payload contains all the data I expect it to contain.

What database you using?

**Comment by themsaid** [comment]
The reason of a 0 payload is that json_encode() failed, the reason of the failure varies from case to case, so you need to investigate the issue more in order for us to understand what went wrong.

Check `/vendor/laravel/framework/src/Illuminate/Queue/Queue.php` and look at method `createPayload()`, this method creates the payload that'll be saved in the DB.

Replace it with the following:

```
protected function createPayload($job, $data = '', $queue = null)
    {
        if (is_object($job)) {
            $output = json_encode([
                'job' => 'Illuminate\Queue\CallQueuedHandler@call',
                'data' => [
                    'commandName' => get_class($job),
                    'command' => serialize(clone $job),
                ],
            ]);

            dd($output, json_last_error(), json_last_error_msg());
        }

        return json_encode($this->createPlainPayload($job, $data));
    }
```

Finally run your code locally to send the notification, now instead of saving the results to the DB the output of the encoding as well as the error message will be dumped on your screen, maybe this will give you more details about why it fails.

Remember to clean the changes once you finish debugging.

**Comment by DaneEveritt** [comment]
Alright, appears to be a UTF-8 issue, but I'm not sure where I'm passing malformed data into the script.

**Comment by DaneEveritt** [comment]
Appears to be a UTF-8 issue, although I can't figure out where that might be occurring if I'm using the `User` model.

```
false
5
"Malformed UTF-8 characters, possibly incorrectly encoded"
```

So when that happened I also did a `dd` of the array that is being run through `json_encode` and got this:

```
array:2 [▼
  "job" => "Illuminate\Queue\CallQueuedHandler@call"
  "data" => array:2 [▼
    "commandName" => "Illuminate\Notifications\SendQueuedNotifications"
    "command" => b"O:48:"Illuminate\Notifications\SendQueuedNotifications":5:{s:14:"\x00*\x00notifiables";a:1:{i:0;O:23:"Pterodactyl\Models\User":23:{s:8:"\x00*\x00table";s:5:"users";s:10:"\x00*\x00guarded";a:4:{i:0;s:2:"id";i:1;s:13:"remeber_token";i:2;s:10:"created_at";i:3;s:10:"updated_at";}s:8:"\x00*\x00casts";a:2:{s:10:"root_admin";s:7:"integer";s:8:"use_totp";s:7:"integer";}s:9:"\x00*\x00hidden";a:3:{i:0;s:8:"password";i:1;s:14:"remember_token";i:2;s:11:"totp_secret";}s:13:"\x00*\x00connection";N;s:13:"\x00*\x00primaryKey";s:2:"id";s:10:"\x00*\x00keyType";s:3:"int";s:10:"\x00*\x00perPage";i:15;s:12:"incrementing";b:1;s:10:"timestamps";b:1;s:13:"\x00*\x00attributes";a:8:{s:4:"uuid";O:19:"Webpatser\Uuid\Uuid":8:{s:8:"\x00*\x00bytes";s:16:"´\x15¯/ÇÇKõ¾Â\x07\x04Y›Îë";s:6:"\x00*\x00hex";N;s:9:"\x00*\x00string";s:36:"b415af2f-c7c7-4bf5-bec2-0704599bceeb";s:6:"\x00*\x00urn";N;s:10:"\x00*\x00version";N;s:10:"\x00*\x00variant";N;s:7:"\x00*\x00node";N;s:7:"\x00*\x00time";N;}s:5:"email";s:20:"dane@daneeveritt.com";s:8:"password";s:60:"$2y$10$ToR7/0hEsc3L.qIZf4VKlObxFkIlgXm.lp72AyFK6xNoKruiYrcZa";s:8:"language";s:2:"en";s:10:"root_admin";i:0;s:10:"updated_at";s:19:"2016-09-05 11:42:44";s:10:"created_at";s:19:"2016-09-05 11:42:44";s:2:"id";i:60;}s:11:"\x00*\x00original";a:8:{s:4:"uuid";r:24;s:5:"email";s:20:"dane@daneeveritt.com";s:8:"password";s:60:"$2y$10$ToR7/0hEsc3L.qIZf4VKlObxFkIlgXm.lp72AyFK6xNoKruiYrcZa";s:8:"language";s:2:"en";s:10:"root_admin";i:0;s:10:"updated_at";s:19:"2016-09-05 11:42:44";s:10:"created_at";s:19:"2016-09-05 11:42:44";s:2:"id";i:60;}s:12:"\x00*\x00relations";a:0:{}s:10:"\x00*\x00visible";a:0:{}s:10:"\x00*\x00appends";a:0:{}s:11:"\x00*\x00fillable";a:0:{}s:8:"\x00*\x00dates";a:0:{}s:13:"\x00*\x00dateFormat";N;s:10:"\x00*\x00touches";a:0:{}s:14:"\x00*\x00observables";a:0:{}s:7:"\x00*\x00with";a:0:{}s:6:"exists";b:1;s:18:"wasRecentlyCreated";b:1;}}s:15:"\x00*\x00notification";O:40:"Pterodactyl\Notifications\AccountCreated":5:{s:5:"token";s:32:"w5bYdInW4cujAN1e1L3nr4gkqjFC55P8";s:2:"id";N;s:10:"connection";N;s:5:"queue";N;s:5:"delay";N;}s:10:"connection";N;s:5:"queue";N;s:5:"delay";N;}"
  ]
]
```

**Comment by DaneEveritt** [comment]
I found the issue, sorry about that!

I was using `Webpatser\Uuid\Uuid` for UUID generation, turns out that was returning something that was not a string (but still ended up being inserted fine as a string).

Thanks for the help!

**Comment by themsaid** [comment]
Welcome :)

**Comment by williamvicary** [comment]
Just ran into this myself, the ticket helped to identify the issue (it was UTF-8 encoding) however would this not be better throwing an exception (and failing the job) rather than silently storing "0"? It is very confusing and a fail -> reason would make it far easier to debug.

**Comment by silasrm** [comment]
What is a solution @DaneEveritt?
