### ISSUE TITLE
Incorrect link to model-factories in docs.

### ISSUE THREAD

**Issue by mcklayin** [laravel/framework#15273]
Incorrect link to anchor model-factories in [application-testing](https://laravel.com/docs/5.3/application-testing#model-factories) . 
Correct is [database-testing](https://laravel.com/docs/5.3/database-testing#model-factories) .

**Comment by bobbybouwmann** [comment]
Fixed with this PR: https://github.com/laravel/docs/pull/2616

**Comment by GrahamCampbell** [comment]
Thanks. :)
