### ISSUE TITLE
[5.3] $table->morphs() returns error with database strict mode 

### ISSUE THREAD

**Issue by dersvenhesse** [laravel/framework#15276]
Hi there,
since 5.3 the database is in strict mode per default. I ran into an issue using the function `morphs` in schema builder.

These are two example models:

    class Vehicle extends Model
    {

        public function car()
        {
            return $this->morphTo('vehicable');
        }
    }

&nbsp;

    class Car extends Model
    {

	    public function vehicable()
        {
            return $this->morphOne('App\Vehicle', 'vehicable');
        }
    }

Here is the function for a migration:

    public function up()
    {
        Schema::create('vehicles', function (Blueprint $table) {
            $table->increments('id');

            $table->string('name');

            $table->morphs('vehicable');

            $table->timestamps();
        });

        Schema::create('cars', function (Blueprint $table) {
            $table->increments('id');

            $table->string('color');

            $table->timestamps();
        });
    }

And here is an example seeder:

    public function run()
    {
        $v = App\Vehicle::create([
            'name' => 'First car',
        ]);

        $c = \App\Car::create([
            'color' => 'red'
        ]);

        $v->car()->associate($c);
        $v->save();
    }

All this put together with `php artisan migrate:refresh --seed` returns the error
    
    SQLSTATE[HY000]: General error: 1364 Field 'vehicable_id' doesn't have a default value  

since the strict mode requires default values for the referenced tables.

Shouldn't there be a way around that other than turning the strict mode off?

**Comment by themsaid** [comment]
The problem here is that you're trying to create a Vehicle and associate a Car to it, to make the example sound more clear, you're trying to create a comment and associate a post to it.

It works the other way around, you create a Post and then associate a comment to it, that way there'll never be a comment that doesn't belong to any Commentable.

**Comment by dersvenhesse** [comment]
You're right. This doesn't occur when saving the car first. 
So it is not an issue at all. Thanks.
