### ISSUE TITLE
Manual logout

### ISSUE THREAD

**Issue by SebastianFix** [laravel/framework#15271]
Hi, when I'm making a scaffolding auth app, I observe an error when i manually hitting the /logout option.

Is this normal? Do i've to built my own exception handling?

![logout-2](https://cloud.githubusercontent.com/assets/10268813/18234459/ea328710-730e-11e6-97fe-fbb632ca3d54.png)

![logout](https://cloud.githubusercontent.com/assets/10268813/18234460/ea63c7f8-730e-11e6-8c6f-ee146068f34f.png)

Thanks for the answer
Sebastian

**Comment by deefour** [comment]
`/logout` is a POST request by default in 5.3: https://github.com/laravel/docs/blob/5.3/upgrade.md#post-to-logout

**Comment by zaknes** [comment]
As @deefour said, 5.3 changed logout from a GET request to a POST request.

So if someone sends you a link that redirects to `example.com/logout`, it will not log you out. A POST request with a proper CSRF token must be submitted.

See the default auth scaffolding for an example of how to make a button submit a form.
