### ISSUE TITLE
mark as read a specific notif in laravel 5.3 Notifications

### ISSUE THREAD

**Issue by ahmadbadpey** [laravel/framework#15277]
I know that there are many ways to mark as read all notifications of an User in L5.3 like this:
```
$user = App\User::find(1);

foreach ($user->unreadNotifications as $notification) {
    $notification->markAsRead();
}
```
Or:
```
$user->unreadNotifications->markAsRead();
```
But suppose I want to mark as read a specific notification with a given ID.

In fact, I have made a list of unread user notifications like this:
```
<ul class="menu">
        @foreach($AuthUser->unreadNotifications as $notif)
            <li>
                <a href="{{$notif->data['action']}}" data-notif-id="{{$notif->id}}">
                    {{$notif->data['message']}}
                </a>
            </li>
        @endforeach
</ul>
```
As you see each a tag have a data-notif-id attribute contain notif ID.

Now I want to send this ID to a script via Ajax (on click event) and mark as read that notification only. for that I wrote this:
```
$('a[data-notif-id]').click(function () {

        var notif_id   = $(this).data('notifId');
        var targetHref = $(this).data('href');

        $.post('/NotifMarkAsRead', {'notif_id': notif_id}, function (data) {
            data.success ? (window.location.href = targetHref) : false;
        }, 'json');

        return false;
});
```
NotifMarkAsRead refers to bellow Controller :
```
class NotificationController extends Controller
    {
        public function MarkAsRead (Request $request)
        {
              //What Do I do Here........
        }
    }
```
How can I do that while there is not any `Notification` Model?

**Comment by themsaid** [comment]
`Illuminate\Notifications\DatabaseNotification` is where the Model for the notification exists, you can use it to grab a notification by ID and delete it. Also if you don't want to use the model you can use a normal DB query.

**Comment by ahmadbadpey** [comment]
solved,thanks @themsaid .

**Comment by frankwaive** [comment]
@ahmadbadpey kindly post your solution please, am having the same problem

**Comment by deliaahm** [comment]
Anoyone can help me?
I use Laravel 5.4 and here my codes for mark read notification :
![image](https://user-images.githubusercontent.com/38059468/40641436-d39884ba-6343-11e8-90f8-c13bec485ae4.png)

When i click one notification, it doesn't change as read. But when i click mark all as read it changed.

and here my route code for mark read notification 
![image](https://user-images.githubusercontent.com/38059468/40641524-2fb9a490-6344-11e8-8587-36feae93495d.png)

**Comment by Siletskiy** [comment]
![image](https://user-images.githubusercontent.com/38152575/106607305-384b4200-6574-11eb-9ec9-d77c30cb9b1a.png)
![image](https://user-images.githubusercontent.com/38152575/106607381-49944e80-6574-11eb-9613-4523d579226d.png)
Method 'markAsRead' not found. 
Please tell me how to add it ???

**Comment by KhairulAzmi21** [comment]
> ![image](https://user-images.githubusercontent.com/38152575/106607305-384b4200-6574-11eb-9ec9-d77c30cb9b1a.png)
> ![image](https://user-images.githubusercontent.com/38152575/106607381-49944e80-6574-11eb-9613-4523d579226d.png)
> Method 'markAsRead' not found.
> Please tell me how to add it ???

just use unreadNotifications , remove () .
