### ISSUE TITLE
Route parameter are not been sent to the callback

### ISSUE THREAD

**Issue by noamcore** [laravel/framework#15294]
- Laravel Version: 5.3.0
- PHP Version: 7.0.10 ZTS
- Database Driver & Version: Sqlite 3.8.10.2

### Description:

The Route parameter are not been sent to the callback function in the `web.php` routes file.

### Steps To Reproduce:

1. Install laravel from composer;
2. Create a new `Route` in `web.php`
```
<?php
Route::get('user/{name?}', function ($user = 'test') {
    return $user;
});
```
3. Run `php artisan serve` and try to catch the name in the browser (localhost/user/?name=aaa).
Always get 'test'.

**Comment by mikerockett** [comment]
This is relevant to the support formums - please post there first as this is not a bug. You are calling the route incorrectly. It should be `localhost/user/joe`. The question mark in the route definition simply makes the `user` optional. Please read the documentation on routing.

**Comment by noamcore** [comment]
God, why? I am ashamed. Sorry for this, I'm currently using another framework and forgot how use Laravel.
