### ISSUE TITLE
Feature: Blade extension for check null and not null

### ISSUE THREAD

**Issue by nmfzone** [laravel/framework#15292]
I think would be nice if blade has an extension to perform a check for null and not null.

The extension maybe like this: 
```
@ifNull ($comments)
@ifNotNull ($comments)
```

I know we can perform it just by using like `@if (! is_null($comments))`, but as I said before, I think would be nice if blade has its feature. Thankyou

**Comment by daison12006013** [comment]
How about create a separate package? a collection of blade extensions. using `is_null()` and `! is_null()` seems to be much more okay for me.

**Comment by GrahamCampbell** [comment]
`@if($foo === null)` is already fine.

**Comment by nmfzone** [comment]
@daison12006013 hmm, what do you mean about a separate package? Do you mean like [this](https://github.com/RobinRadic/blade-extensions) ?
Yes, I can make its extension by myself, but I just think that would be nice if it has been available by default.

**Comment by nmfzone** [comment]
@GrahamCampbell Maybe yes, maybe no. It's okay, it's only my opinion.

**Comment by daison12006013** [comment]
@nmfzone, it is not a good design, imagine you are linking an statement along condition, in which you should need to apply not just the null but all the predefined conditions such as in_array() empty() and so on, they are so many.

**Comment by nmfzone** [comment]
@daison12006013 Aaah, i think there is a misconception in here. The purpose if this extension is only for a condition that only need to perform null check or not null check. So, I give an example that it only performs null or not null check. If there is not only perform null or not null check, we can back to `@if`.
Another topic, in_array() and empty() also could be another extension if we need it. `@ifInArray` and `@ifEmpty`.
I just thinking about the reason behind `is_null()`. We could use like what had been mentioned by @GrahamCampbell, but PHP still gives `is_null()`.

**Comment by daison12006013** [comment]
That's my point @nmfzone, having those condition types would probably take a lot of extensions and yet those native functions is much more better.

How about `@empty()` with `@else` to check if the string/array/null is empty.

**Comment by doyuga** [comment]
Use this
@isset($records)
    // $records is defined and is not null...
@endisset
