### ISSUE TITLE
Is assertSessionHasErrors() useful at all? 

### ISSUE THREAD

**Issue by Kyslik** [laravel/framework#15305]
- Laravel Version: 5.3.6
- PHP Version: 5.6.24
- Database Driver & Version: not relevant

### Description:
Typical update scenario with validation in place. One might want to test that certain errors messages are flashed to session. 

### Steps To Reproduce:

form with input field + Request with validation rule `required` 
if posting fails Laravel makes `redirect()`... so session is not persisted.

#### Test might look like

    <?php
    class ValidationTest extends TestCase
    {
        public function testExample()
        {
            $this->visit('/')->press('Submit');
            $this->assertSessionHasErrors('required');
        }
    }

and test results in failure `Session missing key: errors`

#### All files to reproduce - gist

https://gist.github.com/Kyslik/f603f84011ce72701f0cb0833c10d59c

**Comment by spekkionu** [comment]
It works if you use the call method directly.
`$this->call('POST', "/");`

**Comment by Kyslik** [comment]
@spekkionu isn't this bug then?

Will check `call()` instead of `press()` and report back.

**Comment by themsaid** [comment]
@Kyslik did you get the chance to get more details about the issue?

**Comment by Kyslik** [comment]
Hello @themsaid, well neither of the methods (`call()`,  `press()`, `makeRequest()`) seem to persist session through redirects (because of validation failed - see gist).

I mean I can just crawl page and use `seeText()`... but why is there `assertSessionHasErrors()` at all? Does not make any sense (for now).

**Comment by Jeloo** [comment]
@Kyslik it works with `withoutMiddleware()` usage. Seems like it caused by \Illuminate\Session\Middleware\StartSession::class middleware
