### ISSUE TITLE
There are no commands defined in the "handler" namespace.

### ISSUE THREAD

**Issue by hoaenhancesoft** [laravel/framework#15307]
- Laravel Version: 5.2.43
- PHP Version: 5.5.38
- Database Driver & Version: 

### Description:
I'm trying to create a new event handler for my application in the terminal on my mac.

### Steps To Reproduce:
> Go to terminal
> Went into the application folder
> Type: php artisan handler:event HandleNewStudentAdded --event=StudentAdded
> Received Error: [Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "handler" namespace.

**Comment by hoaenhancesoft** [comment]
@themsaid Why you closed this issue? Can you please help me fix this?

**Comment by themsaid** [comment]
There's no such command as `handler:event` in laravel. You may add the class names in the EventService provider and then run `php artisan event:generate` to create the handlers.

Check https://laravel.com/docs/5.2/events

**Comment by hoaenhancesoft** [comment]
Oh okay. Thanks!

**Comment by DLatty-NJT** [comment]
The laravel documentation is errored (you would think they would've corrected by now) ...

The command is make:listener

php artisan make:listener EmailXXXChanged --event=XXXChanged --queued
