### ISSUE TITLE
migration table column update tinyInteger doesn't work

### ISSUE THREAD

**Issue by Zerotask** [laravel/framework#15309]
- Laravel Version: 5.3
- PHP Version: 7.0.8
- Database Driver & Version: MariaDB 10.1

### Description:
I tried to update a table column within a migration file:

$table->tinyInteger('xyz')->unsigned()->default(1)->change();

and I got the error:

> [Doctrine\DBAL\DBALException]                                                                                                                                                           
  Unknown column type "tinyinteger" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known types   
  with \Doctrine\DBAL\Types\Type::getTypesMap(). If this error occurs during database introspection then you might have forgot to register all database types for a Doctrine Type. Use A  
  bstractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#getMappedDatabaseTypes(). If the type name is empty you might have a problem with the cache or   
  forgot some mapping information.          

When I changed it from tinyInteger to smallInteger, it works.

### Steps To Reproduce:
1. make a migration file and add a tinyInteger field
2. make a second migration file and update this column, e.g. set a default value.

**Comment by srmklive** [comment]
This to me is primarily a doctrine issue not laravel.

**Comment by Manchister** [comment]
if it is still matter, you should use boolean instead tinyInteger in change. like:
$table->boolean('active')->default(1)->change();

**Comment by debiprasad** [comment]
Doctrine\DBAL does not support TinyInt. It looks like you are using TinyInt for a boolean value. So, instead of using `tinyInteger` use `boolean`. 

Or if it's not for boolean, then you can use `smallInteger`.

Use `\Doctrine\DBAL\Types\Type::getTypesMap()` to know the supported datatypes.
