### ISSUE TITLE
How to paginate Laravel 5.3 database Notifications

### ISSUE THREAD

**Issue by ahmadbadpey** [laravel/framework#15315]
We know that Notifications in Laravel 5.3 can sent via many channels and can store in database.

And we know that can fetch all notifications of a User and show them like this :
```
 $user = App\User::find(1);

foreach ($user->notifications as $notification) {
    echo $notification->type;
}
```
But Suppose case that I have a AllNotifications page that show all notifications of a user and I want to paginate that.

Is there any way to paginate notifications ?

**Comment by themsaid** [comment]
You can use `$user->notifications()->paginate()`, the `HasDatabaseNotifications` trait has a regular morphMany relationship.

**Comment by ahmadbadpey** [comment]
I tried your code. 
I have three notif and used `$user->notifications()->paginate(2)`, then pages links show on the first page but it does not show in the second page and in this case I could not navigate to other page. why?

**Comment by themsaid** [comment]
I guess that's an issue with the paginator, there were some changes with it in the past couple of days not sure if that's related.

**Comment by tahiryasin** [comment]
This might help :)
```
$page = $request->page ?: 0; /* Actual page */
$limit = 10; /* Limit per page */
return \Auth::user()->notifications()->offset($page * $limit)->limit($limit)->get();
```

**Comment by leonwong72** [comment]
@tahiryasin 
Hi there,

I would like to ask how can I move to second page in this case? I can only see those notifications in the first page and I have no button to choose which page I wanted to see.

**Comment by jasbin** [comment]
you can do something like this in blade as well
`@foreach (auth()->user()->notifications()->paginate(5) as $notification)
     //show your notification content here
@endforeach
`
and at out of loop use this
`{{auth()->user()->notifications()->paginate(1)->links()}}`
