### ISSUE TITLE
loginUsingId not persistent, only works on the first request

### ISSUE THREAD

**Issue by omer414** [laravel/framework#15314]
- Laravel Version: 5.3.4
- PHP Version: 7.0.10
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.7.13, for Win32 (AMD64)     

### Description:
I am trying to implement a single signon on multiple domains (single instance). The concept is pretty simple i.e to send user from domain1 to domain2 with a unique user tokens and then verify these tokens against user and then if the token is found i manually log him in.

`$loggedInUser = Auth::loginUsingId($user->id, true);`

Now i also have a custom middleware where it checks for a logged in user, and then does some other stuff.

`Auth::Check()`

The above works fine for the first time. But on refresh Auth::check() is not validated. I have done a lot of diedumps and i am pretty sure that some how the login state is not persisting. I also tried using all different session drivers including file, cookie, db, redis but still it doesn't work.

I also came across lots of other users having the same issue. Here is one having an identical problem.
http://laravel.io/forum/10-20-2015-authloginusingid-and-authlogin-not-work-in-middleware

I have used a similar code on laravel 5.2, and it did work fine at the time. But on laravel 5.3 its not validating. My question is, is this how it was ment to be? Or is there something that i might be missing?

Anyhelp would be really appreciated.

**Comment by omer414** [comment]
I also came across lots of other users having the same issue. Here is one having an identical problem.
http://laravel.io/forum/10-20-2015-authloginusingid-and-authlogin-not-work-in-middleware

**Comment by srmklive** [comment]
@omer414 Are you using the same database for login?

**Comment by omer414** [comment]
Well yes both use the same database. Just a different domain.

**Comment by srmklive** [comment]
@omer414 I actually got around to get it working through multiple domains was by using a combination of api & web auth guard. It isn't a good solution, but here is what i did:

* Created a route called `verify` in `routes/web.php` file. On this route, i apply the api middleware. 
* To login from domain A to domain B, i simply created an api token & passed to another URL using:
    
        http://domainB/verify?api_token=token

* In my `verify route code`, i wrote:

        $auth = auth('api')->check();
        if ($auth) {
            $user = $auth->user;

            auth()->loginUsingId($user->id, true);

            return redirect(url('home'));
        }


Let me know if it works for you.

**Comment by omer414** [comment]
@srmklive Well this is exactly what i am doing but instead of the api token to find the user, i am using a custom generated token. Are you using laravel 5.3?

**Comment by srmklive** [comment]
@omer414 yes i am using laravel 5.3.

**Comment by omer414** [comment]
Exactly which version is it?

**Comment by srmklive** [comment]
5.3.6

**Comment by themsaid** [comment]
@srmklive you seem to be able to identify the issue, can you please share what you think is the issue? :)

**Comment by srmklive** [comment]
@themsaid I think that the auth guard implementation by @omer414 is not correct.

**Comment by omer414** [comment]
@srmklive  i mostly use middlewares and no guards. i have not modified AuthServiceProvider or any other guard. let me show you my code.

here is the route that domain1 points to 
**http://domain2.com/{{$role}}/{{$route}}/singlesignon/{{$token}}**

This is then picked up by verifySingleSignOn method inside the loginController which takes in the role, route that the user came in from other domain and the token. The user is then redirected to the same routes, but on domain2. Here i can successfully recieve the user id before manually logging in. 

```
public function verifySingleSignOn($role, $route, $token)
    {
        // Fetch Single Signon
        $userRepository = new UserRepository();
        $user = $userRepository->checkForSingleSignOnToken($token, ['id']);

        // Check if Token Exists
        if (isset($user->id) && is_int($user->id) && $user->id != 0) {

            // Manually Logging a user (Here is successfully recieve the user id)
            $loggedInUser = Auth::loginUsingId($user->id);

            if (!$loggedInUser) {
                // If User not logged in, then Throw exception
                throw new Exception('Single SignOn: User Cannot be Signed In');
            }
            $redirectTo = $role . '/' . $route;
            return redirect($redirectTo);
        } else {
            return Auth::logout();
        }
    }
```

Then i have this GlobalAdminAuth middleware
```
       // Check if logged in
        if( Auth::Check() ){
            $user = Auth::User();

            // Check if user is active and is a globaladmin
            if( !$user->isGlobalAdmin() || !$user->isActive() ){
                return redirect()->guest('login');
            }
        }else{
            return redirect()->guest('login');
        }

        return $next($request);
```
Now the first time everything works fine and the user moves through the middleware successfully . but the second time the else statement is triggered.

**Comment by srmklive** [comment]
@omer414 The issue is with your middleware. Your middleware should simply check if the token being passed is valid or not. If its invalid, it should simply generate an error. You should create a custom auth guard. Refer to laravel documentation [here](https://laravel.com/docs/5.3/authentication#adding-custom-guards).

**Comment by GoodJob** [comment]
issue is still actual in Laravel 9
