### ISSUE TITLE
Migrations Rollback/Reset getting failed for migrations from subfolder or custom path

### ISSUE THREAD

**Issue by furqanaziz** [laravel/framework#15327]
- Laravel Version: 5.3.6
- PHP Version:7.0.9
- Database Driver & Version: Mysql 5.6

### Description:
Migrations Rollback/Reset getting failed for migrations from subfolder or custom path.

### Steps To Reproduce:

1. Create a sub directory under database/migrations lets say xyz and it will looks like database/migrations/xyz/
2. Create a migration into this new sub directory: php artisan make:migration create_user --path database/migrations/xyz/
3. Run migration with path parameter as php artisan migrate --path database/migrations/xyz
4. It will run successfully
5. Next is to rollback or reset with php artisan migrate:reset -v it will through error as follows
                                                                  
 
>  [ErrorException]                                                
>  Undefined index: 2016_09_05_192848_create_user  
>                                                                   
> 
> Exception trace:
>  () at /var/www/smarttrainerlms/app.smarttrainerlms.com/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:252
>  Illuminate\Foundation\Bootstrap\HandleExceptions->handleError() at /var/www/smarttrainerlms/app.smarttrainerlms.com/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:252
>  Illuminate\Database\Migrations\Migrator->reset() at /var/www/smarttrainerlms/app.smarttrainerlms.com/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/ResetCommand.php:68
>  Illuminate\Database\Console\Migrations\ResetCommand->fire() at n/a:n/a
>  call_user_func_array() at /var/www/smarttrainerlms/app.smarttrainerlms.com/vendor/laravel/framework/src/Illuminate/Container/Container.php:507
>  Illuminate\Container\Container->call() at /var/www/smarttrainerlms/app.smarttrainerlms.com/vendor/laravel/framework/src/Illuminate/Console/Command.php:169
>  Illuminate\Console\Command->execute() at /var/www/smarttrainerlms/app.smarttrainerlms.com/vendor/symfony/console/Command/Command.php:256
>  Symfony\Component\Console\Command\Command->run() at /var/www/smarttrainerlms/app.smarttrainerlms.com/vendor/laravel/framework/src/Illuminate/Console/Command.php:155
>  Illuminate\Console\Command->run() at /var/www/smarttrainerlms/app.smarttrainerlms.com/vendor/symfony/console/Application.php:818
>  Symfony\Component\Console\Application->doRunCommand() at /var/www/smarttrainerlms/app.smarttrainerlms.com/vendor/symfony/console/Application.php:186
>  Symfony\Component\Console\Application->doRun() at /var/www/smarttrainerlms/app.smarttrainerlms.com/vendor/symfony/console/Application.php:117
>  Symfony\Component\Console\Application->run() at /var/www/smarttrainerlms/app.smarttrainerlms.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:122
>  Illuminate\Foundation\Console\Kernel->handle() at /var/www/smarttrainerlms/app.smarttrainerlms.com/artisan:35

### My Findings:
I see first parameter is path in Illiminate/Database/Migrations/Migrator.php reset function but it is not passed from console Illiminate/Database/Console/Migrations/RollbackCommand.php and not even accepted from user.

**Comment by srmklive** [comment]
You need to add custom path to custom migrations folder through a service provider.

**Comment by themsaid** [comment]
Use something like this in a service provider:

```
$this->loadMigrationsFrom(base_path('database/migrations/xyz'));
```

Since you're using paths you must define them in a service provider in order for the migrator to load the files in them.

**Comment by Maximus1000** [comment]
using folders for migration table organization and testing.  sorry if duplicate.  spent an hour trying to figure this out / very simple solution.

had undefined index problem on migrate:reset.  composer dump-autload, deleting migrations table, restarting vagrant, lots of other attempts all failed.  

simple solution:  php artisan migrate:rollback --path=/database/migrations/folder

pass the path parameter to the rollback method.  that's the solution if composer dump-autoload doesn't work for you on rollback or reset due to undefined index error.
