### ISSUE TITLE
[5.2] Envoy PHP Notice Undefined variables

### ISSUE THREAD

**Issue by vrubiella** [laravel/framework#15320]
- Laravel Version: 5.2
- PHP Version: 7.0

### Description:

Runing envoy tasks always fails with "Undefined variable" PHP Notice if another tasks has defined variables.

### Steps To Reproduce:
```php
@servers(['server'] => 'localhost'])

@task('taskwithvariables', ['on' => 'server'])
 echo {{$message}}
@endtask

@task('hello', ['on' => 'server'])
 echo "hello"
@endtask
```
Runing from bash
```bash
envoy run hello
```
Runing from controller throws exception:
```php
(new Process("envoy run hello"))->mustRun();
```

**Comment by themsaid** [comment]
This issue is now fixed, will be available in the next release of Envoy.

https://github.com/laravel/envoy/pull/87
