### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by IlyaSavich** [laravel/framework#15338]
- Laravel Version: 5.2.45
- PHP Version: 5.6
- Database Driver & Version: PostgreSQL 9.3

### Description:

I'm trying to create custom config file and meet the problem.
This is my config

```
<?php

return [

    route('admin.admins') => [\App\Models\User\Admin::ROLE_ADMIN],
    route('admin.admins.create') => [\App\Models\User\Admin::ROLE_ADMIN],

];
```

In this case I receive error 

> PHP Fatal error:  Uncaught ReflectionException: Class log does not exist in /home/ilyasavich/PhpstormProjects/breakfastdelivery/vendor/laravel/framework/src/Illuminate/Container/Container.php:734

I;m found out that this error appears when I'm trying to use `route()` function or working with class (if create new instance or getting static fields). Is interesting to notice that I can use `env()` function in file.
Please, may I doing something wrong?

**Comment by themsaid** [comment]
Please don't do that, only use static keys in config files. This won't work.

**Comment by IlyaSavich** [comment]
Many thanks! To be honest, I'm very ashamed now for my attempt! :)

2016-09-08 12:55 GMT+03:00 Mohamed Said <notifications@github.com>:

**Comment by themsaid** [comment]
Man, it's ok :)
