### ISSUE TITLE
Model binding in controller doesn't work properly

### ISSUE THREAD

**Issue by chaot1x** [laravel/framework#15349]
- Laravel Version: 5.3.6
- PHP Version: 5.6.21
- Database Driver & Version: 10.1.13-MariaDB

### Description:
Model binding doesn't work in controllers like it was in 5.2
In 5.2 this code would return model data if found in database, but in 5.3 it returns just it as type of that model

Controller:
```
public function testPage(Post $post)
{
   dd($post);
}
```

Route:
```
Route::get('test/page/{post}', [
   'as' => 'test.page',
   'uses' => 'TestPageController@testPage',
]);
```

**Comment by BrandonSurowiec** [comment]
Make sure:

1. The web middleware has bindings registered:

```
    /**
     * The application's route middleware groups.
     *
     * @var array
     */
    protected $middlewareGroups = [
        'web' => [
           ...
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],
    ];
```

2. Make sure your route is actually using the web middleware and it is using it once, not twice. Run `php artisan route:list` to check.

I had this issue when upgrading, but it was my fault ;)

**Comment by themsaid** [comment]
@chaot1x yes please make sure you followed the upgrade guide in regards to the SubstituteBindings middleware.
