### ISSUE TITLE
Multiple typos(?!) in latest

### ISSUE THREAD

**Issue by andreicon** [laravel/framework#15342]
- Laravel Version: installed latest stable, composer json shows 5.3.*
- PHP Version: 5.5.9-1ubuntu4.11
- Database Driver & Version: didn't connect yet...

### Description:
Trying to move my dev env into docker containers. Just pulled the latest version and found several typos in function arguments. the variables would be passed as function_name(...$args) {}

### Steps To Reproduce:
run `composer create-project laravel/laravel --prefer-dist laravel`

**Comment by themsaid** [comment]
@andreicon what do you mean by several typos?

**Comment by andreicon** [comment]
Excuse the lack of information.

I pulled the 5.3 branch and went straight to the browser which returned a 500.
Checking the apache error log revealed an error in 5.3/src/Illuminate/Foundation/helpers.php:475 in the function definition. Fixing this in my copy then revealed another error in src/Illuminate/Support/Facades/Facade.php:237, the same issue.

First i thought it's because i'm running docker on a windows vm and somewere along the line the encoding broke or smth, but checking the repo confirmed that the function definition line contained `(...$args)`.

**Comment by themsaid** [comment]
Laravel 5.3 requires PHP 5.6.4 or above :)

**Comment by andreicon** [comment]
Thanks, i guess i need to read the underlying manual
