### ISSUE TITLE
[5.3] Auth:api -- Token only as GET Variable?

### ISSUE THREAD

**Issue by stefanmahr** [laravel/framework#15357]
- Laravel Version: 5.3
- PHP Version: 7.0.9

### Description:

Hello!

I have a problem by useing the Auth:Api in Laravel. If I put the token into the URL everythink is working fine. If I put it into the post data, there will be an 401 Unauthorized.

Here are my code:

```
// Working
				
$.ajax({
  url: "https://***.***/api/v1/test?api_token=y1Ctd8pEmbwq4mQHQYlKpmanXEI5vTy8OOgmvCqvu",
  type: "POST",
  data: "value=isworking",
  success: function(result) {
    alert(result);
  },
  error: function() {
   alert("error");	
  }
});

```

```
// Don't Working
				
$.ajax({
  url: "https://***.***/api/v1/test",
  type: "POST",
  data: "api_token=y1Ctd8pEmbwq4mQHQYlKpmanXEI5vTy8OOgmvCqvu&value=isworking",
  success: function(result) {
    alert(result);
  },
  error: function() {
   alert("error");	
  }
});
```

```
Route::group(['middleware' => 'auth:api'], function () {
	
	Route::post('/test', function() {
		
		$user = Auth::guard('api')->user();
		
		return $user->email . " " . $_POST["value"];
		
	});
	
});
```

Maybe I just have a simple error in the js syntax, but I think it is okey.

Can someone help me? 

Best greetings,
Stefan

**Comment by morloderex** [comment]
Helle as a general rule of thum not try to access a variable through the Super globals arrays use the request class for this. 

Now: as for your issue itself its not possible as a post parameter, however it is possible through the authorization header if you prefix it with bearer.

**Comment by srmklive** [comment]
If you send the token through the authorization header by prefixing it as a bearer, it will work fine.

**Comment by stefanmahr** [comment]
>Helle as a general rule of thum do not try to access a variable through the Super globals arrays use the request class for this.

Thanks! Normaly I use the request class for it, but in this time I was just a demo.

>Now: as for your issue itself its not possible as a post parameter, however it is possible through the authorization header if you prefix it with bearer.

Thanks! Everything is working fine now!
