### ISSUE TITLE
[5.3] Unable to use delayed mail sending via Mail facade

### ISSUE THREAD

**Issue by Dru1X** [laravel/framework#15358]
- Laravel Version: 5.3.7
- PHP Version: 7.0.8
- Database Driver & Version: MySQL 5.7.13

### Description:
When using the mail facade as described by the [documentation](https://laravel.com/docs/5.3/mail#queueing-mail), I encounter the following fatal throwable error:

> Call to undefined method Illuminate\Mail\MailableMailer::later()

Sending and non-delayed queueing work as expected.

Am I missing something?

### Steps To Reproduce:
Simply call the following from a controller

`Mail::to($recipient)->later($sendDate, $mailable);`

**Comment by Kunimaru** [comment]
later method isn't defined in Illuminate\Mail\MailableMailer
https://laravel.com/api/5.3/Illuminate/Mail/MailableMailer.html

this method is defined in Illuminate\Mail\Mailer
https://laravel.com/api/5.3/Illuminate/Mail/Mailer.html

**Comment by Dru1X** [comment]
I understand that later() is defined in Illuminate\Mail\Mailer, but when calling `Mail::to($recipient)`, an instance of Illuminate\Mail\MailableMailer is returned which clearly lacks said later() method.

This way of using it is exactly as shown in the documentation:

```
$when = Carbon\Carbon::now()->addMinutes(10);

Mail::to($request->user())
    ->cc($moreUsers)
    ->bcc($evenMoreUsers)
    ->later($when, new OrderShipped($order));
```

**Comment by themsaid** [comment]
The docs seem to be out of date for this part, to send a queued mail you need to do the follwing:

```
$message = (new OrderShipped($order))->delay(60);

Mail::to($request->user())
    ->cc($moreUsers)
    ->bcc($evenMoreUsers)
    ->queue($message);
```

**Comment by themsaid** [comment]
I think we should add it back though :)

**Comment by Dru1X** [comment]
@themsaid Thanks for clarifying. That would also explain why sendNow() isn't documented yet.

I agree with you that later() should be added back in. Given that the goal of this tool was simplicity and clarity, removing it seems like a bit of a step backwards.

**Comment by themsaid** [comment]
Will check if Taylor is ok with bringing it back, since you can do this:

```php
Mail::to($request->user())
    ->cc($moreUsers)
    ->bcc($evenMoreUsers)
    ->queue((new OrderShipped($order))->delay(60));
```

Which is not that bad as well.
