### ISSUE TITLE
catch Exception from TestCase::visit (from InteractsWithPages trait)

### ISSUE THREAD

**Issue by caiquecastro** [laravel/framework#15351]
- Laravel Version: 5.3.6
- PHP Version: 7.0
- Database Driver & Version: 

### Description:
When I $this->visit a non-existent user id on my app like: `$this->visit('users/999)` on my test suite, and there is no user with id 999. my test get failed. So if I do:

```
$this->visit('users/999')->seeStatusCode(404);
```

my tests fails.

### Steps To Reproduce:

Explained above.

Would not be desirable If it catches the model not found exception for the test? Or is it better to use `$this->get()` for this use case?

**Comment by themsaid** [comment]
How does your route definition look like? Also How does the method in the controller look like?

**Comment by caiquecastro** [comment]
On a fresh installation I did:

routes/api.php

Route::get('/users', function(Request $request) {
    return \App\User::all();
});

Route::get('/users/{user}', function(\App\User $user) {
    return $user;
});

**Comment by caiquecastro** [comment]
On the ExampleTest I did:

$this->visit('/api/users/9')->assertResponseStatus(404);

and 

$this->visit('/api/users/9')->seeStatusCode(404);

**Comment by GrahamCampbell** [comment]
Looks like you turned off the middlewares so the route model binding didn't run. Laravel instead injected a new user instance to your controller.
