### ISSUE TITLE
authenticate() method missing from guard contract.

### ISSUE THREAD

**Issue by kevindierkx** [laravel/framework#15365]
- Laravel Version: 5.3.6

### Description:
The Authenticate middleware checks if the user is authenticated in any of the given guards. It does so by calling `authenticate()` on the `AuthManager`. The `authenticate()` method doesn't exist on this class and will pass it through to the default Guard configured in the `auth.php` config.

When creating new Guards the first place to look are the `Guard` and `StatefulGuard` contracts to determine what methods are required. The `authenticate()` method isn't listed in either resulting in a `Call to undefined method` exception when you don't include it.

Since this method is called by default in a new laravel installations (the auth middleware) this method should either be included in one of the contracts or the `Authenticate` middleware shouldn't call the `authenticate()` method in the first place.

The `StatefulGuard` uses the `GuardHelpers` trait to supply the authenticate method.

### Steps To Reproduce:
Create a custom Guard and remove the authenticate method. Make sure you don't use the `GuardHelpers` trait. ;)

**Comment by themsaid** [comment]
Well, you need to implement the GuardHelpers interface then :)

If you have time please consider making a docs PR for that. Thanks for sharing :)

**Comment by kevindierkx** [comment]
@themsaid It's a trait not an interface. :o

For my use case this isn't really a solution, I don't need most of the methods the way they are implemented and would overload them because of that. Also the Auth component checks for the interfaces/contracts and not for this specific 'helpers' trait.

Therefore my problem remains the same, the Auth component expects methods not defined in an interface, on instances that can be interchanged.
