### ISSUE TITLE
Pusher Fails Silently

### ISSUE THREAD

**Issue by nodefortytwo** [laravel/framework#15376]
- Laravel Version: 5.3
- PHP Version: 7.1
- Database Driver & Version:

### Description:
The pusher driver fails silently if there are any errors (in my case the "eu" cluster must be specified)

Laravel should check the result of the pusher trigger method and at least log the failure if not throw an exception.

Happy to submit a PR if everyone agrees.

### Steps To Reproduce:
cause pusher to fail, see no error.

**Comment by themsaid** [comment]
Thank you for reporting, I think submitting a PR is a good idea since it's better we discuss implementations. Closing this since it's not actually a bug report :)
