### ISSUE TITLE
Queue (Beanstalkd) and Pusher Broardcasting problem in 5.3.7 and 5.3.8

### ISSUE THREAD

**Issue by huglester** [laravel/framework#15386]
- Laravel Version: 5.3.8
- PHP Version: 7.0.8
- Database Driver & Version: 5.7

### Description:
When I push notification to the 'broadcast', and I have QUEUE set as 'beantstalkd', I keep getting this error message:
`[2016-09-10 08:32:08] local.ERROR: Pheanstalk\Exception\ServerException: Server reported NOT_FOUND in /home/huglester/Projects/app-vps/vendor/pda/pheanstalk/src/YamlResponseParser.php:36
Stack trace:
#0 /home/huglester/Projects/app-vps/vendor/pda/pheanstalk/src/Connection.php(142): Pheanstalk\YamlResponseParser->parseResponse('NOT_FOUND', NULL)
#1 /home/huglester/Projects/app-vps/vendor/pda/pheanstalk/src/Pheanstalk.php(396): Pheanstalk\Connection->dispatchCommand(Object(Pheanstalk\Command\StatsJobCommand))
#2 /home/huglester/Projects/app-vps/vendor/pda/pheanstalk/src/Pheanstalk.php(312): Pheanstalk\Pheanstalk->_dispatch(Object(Pheanstalk\Command\StatsJobCommand))
#3 /home/huglester/Projects/app-vps/vendor/laravel/framework/src/Illuminate/Queue/Jobs/BeanstalkdJob.php(102): Pheanstalk\Pheanstalk->statsJob(Object(Pheanstalk\Job))`

I see this error with Laravel 5.3.7 and 5.3.8, reverting to 5.3.6 - goes OK.

### Steps To Reproduce:
Just have a notification, like:
InvoiceWasSent()
via() => ['mail', 'database', 'broadcast'];

queue=beanstalkd

And send a notification to the user, when you run the queue:listen command, error will appear.

Thank you

**Comment by themsaid** [comment]
@huglester did you manage to sort it out?

**Comment by huglester** [comment]
hello @themsaid , grats on your new role :)
Well, I just upgraded to 5.3.10 version and there seems to be no problems, I tried 5.3.9 and also could not reproduce :/
Well for now probably closing this!

**Comment by themsaid** [comment]
@huglester thank you :)

Thank you for the follow up on the issue as well :)

**Comment by daison12006013** [comment]
@huglester I'm getting this error on Laravel 5.4.23 same with this error too https://laracasts.com/discuss/channels/forge/queued-events-server-reported-not-found
