### ISSUE TITLE
Alternate logging/error dumping mechanism until the logger is loaded.

### ISSUE THREAD

**Issue by jaesung2061** [laravel/framework#15389]
- Laravel Version: 5.2.43
- PHP Version: 7.0.9
- Database Driver & Version: mysql 5.7

### Description:
Addition information: Environment CentOS 6 on Amazon Ec2

If there is an error during the bootstrap phase and the Laravel Log class isn't loaded, it throws the following error.

    PHP Fatal error:  Uncaught ReflectionException: Class log does not exist in /my-project/vendor/laravel/framework/src/Illuminate/Container/Container.php:734

This is a problem because it doesn't allow us to see what is actually causing the bug. Is it possible to have an alternate form of logging/dumping errors during this phase?

### Steps To Reproduce:

Cause any errors during the bootstrap phase when running certain artisan commands. It seems to only happen when running certain commands, notably `php artisan queue:listen`. `php artisan queue:work` doesn't cause this issue.

### Other Information:

The first time I ran into this issue, I found the issue to be the PDO extension not being loaded and attempting to get `PDO::FETCH_CLASS` in `config/database.php` was causing the error. I fixed this issue, but now I'm running into another issue which is causing the `ReflectionException`.

An interesting quirk with these issues is that if I run the `queue:listen` command with non-elevated privileges, I don't get this error. However, if I run it as `root` or `nginx` (user who owns project directory) I get the `ReflectionException`.

**Comment by sisve** [comment]
I believe this has already been fixed in 5.3.
