### ISSUE TITLE
laravel auth credential attempt check extra field whereIn Array

### ISSUE THREAD

**Issue by baqirmemon** [laravel/framework#15387]
- Laravel Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
    $credentials = [
            'email'       => $request->get('email'),
            'password' =>  $request->get('password'),
            'type'         => ['member', 'school'],
            'status'       =>'1',
    ];
    if (Auth::attempt($credentials, $request->has('remember'))) {
           return redirect('/account')->with('success', 'Login Successfully');
    }
    return redirect()->back()->with('error', 'Invalid Credentials!');

Error Accured Invalid Credentials to Add  'type'         => ['member', 'school'],

**Comment by themsaid** [comment]
That's not supported in laravel atm, please feel free to submit a Pull Request.

Closing since this isn't actually a bug report.

**Comment by VinceG** [comment]
@baqirfarooq See #24620
