### ISSUE TITLE
 Proposal to add two new rule to validation

### ISSUE THREAD

**Issue by muhamad12** [laravel/framework#15398]
- Laravel Version: 5.3.x
- PHP Version: 7.0.x

### Description:
**1.The "unacceptable" rule**

In some projects, depending on the type of users who use the system. It is necessary to use a feature that is in the form of _polymorphism_, for example, fields such as "activated" or "role" in the user interface is unacceptable, but in the "senior manager" should be accepted.
In the current case for it, we use the attribute "fillable" in models for filtering inputs, we can use "only" and "except" in the controller. But the main filtering should to be done at the "validation", is not available!

As is evident, in version 5.3 is a rule called "nullable" added to Laravel.
But more importantly, there should be a rule known as "unacceptable", As its name suggests That is refused entry, "unacceptable" fields. To the principles of validation and controller met in this case.

**2. Polymorphism "unique" rule**

In the current case, validation by "unique" rule, Regardless the type of method is request. One of the common problems of this rule, non-compliance with the Update method. This method needs to be smart. It is not hard. considering methods of "PUT" and "PATCH" a polymorphism "unique" rule to be defined. To meet this suggestion in standard mode or "restFul" only need to "context" and "route".

> The two cases mentioned, is an important option, which unfortunately does not exist in Laravel.

**Comment by themsaid** [comment]
Thank you for the suggestions but please use the https://github.com/laravel/internals repo, it's the place to post suggestions and feature requests :)

**Comment by muhamad12** [comment]
Thanks for response
