### ISSUE TITLE
Eloquent Model with specific property names

### ISSUE THREAD

**Issue by Cratyz** [laravel/framework#15394]
- Laravel Version: 5.2.*
- PHP Version: 5.6.15/7.0
- Database Driver & Version: N/A

### Description:
I'm unsure yet if this is to be regarded as a design flaw or a regular restriction: Lets say we want to create a model with the exact properties named `table` and `append`. You will likely get errors when you try to call `$model->append` since it's some reserved keyword. 

### Steps To Reproduce:
I'm having this exact issue where I'm loading a form coupled to a model ( so the input fields get prefilled):
**SomeView.blade.php**
````
{!! Form::model(new \Models\User(), ['route' => 'admin.currency.store', 'method' => 'POST']) !!}
                {!! Form::text('append', null, ['class' => 'form-control']) !!}
{!! Form::close() !!}
````

In where `Form` denotes "Collective\Html\FormFacade", and `Models\User` is a model extended with "Illuminate\Database\Eloquent\Model".

What happens is that every input inside those Form-tags will get prefilled with data from the model that is passed. However; it throws an error because it calls `$model->append()` behind the scenes apparently.

Any input on this or how to retrieve an attribute in particular and not a default function of the abstract EloquentModel?

**Comment by themsaid** [comment]
Yeah you shouldn't have attributes that has the same names of methods existing in the model class, this is a limitation we can't go around :)

**Comment by Cratyz** [comment]
ok thanks for the response. Im reporting this issue on the LaravelCollective though because I've tested myself that it DOES work when retrieving it with `$model->getValueAttribute('append')`

**Comment by sisve** [comment]
I'm thinking that a workaround would be calling `$model->getAttribute('append')` instead of relying on __get() to handle `$model->append`

**Comment by Cratyz** [comment]
yes good call i've reported this issue in the module it is being used; it seems to solve the issue indeed
