### ISSUE TITLE
Declaration of Illuminate\Database\Eloquent\Collection::unique() should be compatible with Illuminate\Support\Collection::unique($key = NULL, $strict = false)

### ISSUE THREAD

**Issue by singgihmardianto** [laravel/framework#15399]
- Laravel Version: 5.2.45
- PHP Version: 5.6.19
- Database Driver & Version:

### Description:
Getting error when access the Eloquent model. 

### Steps To Reproduce:
I was installing a fresh laravel 5.2, I just run a simple code 

`Page::all()`

And throwing an error

`Declaration of Illuminate\Database\Eloquent\Collection::unique() should be compatible with Illuminate\Support\Collection::unique($key = NULL, $strict = false)`

After do some research and looking the answer from the issues here, I think there is a bug because some changes in illuminate\Support\Collection::unique() and it didn't change the other files Illuminate/Database/Eloquent/Collection

Note:
My code works well on Laravel version 5.2.39

Thanks

**Comment by themsaid** [comment]
Looks like something is wrong with your installation, the `$strict` argument was added in 5.3 and it never existed in 5.2

I suggest you try to install a fresh installation from scratch.

**Comment by crynobone** [comment]
It could be an issue with `illuminate/support` or `illuminate/contracts` installed v5.3 globally while your project is on `laravel/framework` v5.2

**Comment by singgihmardianto** [comment]
@crynobone @themsaid Yes my bad. After double check again, actually my project is on laravel v5.2 but one of my composer libraries install a `illuminate/support` v5.3.

Thanks all :)
