### ISSUE TITLE
[5.3] I can't get authenticated user in constructor.

### ISSUE THREAD

**Issue by pyaehein** [laravel/framework#15406]
- Laravel Version: 5.3.9
- PHP Version: 7.0.1
- Database Driver & Version: mariadb

### Description:
Authenticated user can't call in constructor. It's always return null. 
Constructor don't get 'web' middleware access.

### Steps To Reproduce:
web.php
`Route::get('test', 'testController@test');`

testController.php
```
use Auth;

public function __construct()
{
      dd(auth()->user()); // return null
      //dd(Auth::user()); // return null
      //dd(auth()); // it's show auth() collections but not include 'web' middleware access
}
```

**Comment by BrandonSurowiec** [comment]
It's how the middleware is now loaded in 5.3. Check out the "Controller" section of the 5.3 upgrade guide or the following article for your answer. Either use a method that you call when needed (outside of the constructor), or use a Closure-based middleware in your constructor:

Article:
https://laravel-news.com/2016/08/controller-construct-session-changes-in-laravel-5-3/

Upgrade Guide (Controller Section):
https://laravel.com/docs/5.3/upgrade#upgrade-5.3.0
