### ISSUE TITLE
Session persistence and cookie check conditions are confusing

### ISSUE THREAD

**Issue by progmars** [laravel/framework#15408]
- Laravel Version: latest (master branch)
- PHP Version: does not matter

### Description:

While extending the default session driver to use HTTP header instead of cookie, I noticed suspicious piece of code:
https://github.com/laravel/framework/blob/master/src/Illuminate/Session/Middleware/StartSession.php

```
    protected function addCookieToResponse(Response $response, SessionInterface $session)
    {
        if ($this->usingCookieSessions()) {
            $this->manager->driver()->save();
        }

        if ($this->sessionIsPersistent($config = $this->manager->getSessionConfig())) {
            $response->headers->setCookie(new Cookie(
                $session->getName(), $session->getId(), $this->getCookieExpirationDate(),
                $config['path'], $config['domain'], Arr::get($config, 'secure', false),
                Arr::get($config, 'http_only', true)
            ));
        }
    }
````

From the first look it might seem that sessionIsPersistent and usingCookieSessions conditions should be exchanged - you most probably want to store the session data when sessionIsPersistent and set the response cookie when usingCookieSessions, and not vice versa. Only when diving deeper into the code it becomes more clear why this function is so confusing. I guess, it's just a matter of commenting / refactoring.

**Comment by sisve** [comment]
Could you explain what you find confusing, and in what way you want to change the documentation? Could you submit a PR with the requested changes?

**Comment by progmars** [comment]
As implementing custom Session driver might be required in some use cases, my suggestion would be to comment the code of the default StartSession implementation. Currently the naming of functions and variables seem counterintuitive at first glance.
Look at it from neutral point of view. Imagine that you don't know much about internals of some framework and you see the following combination of expressions in a single function:

```
if(usingCookieSessions) 
driver()->save()

if(sessionIsPersistent)
headers->setCookie()
```

Doesn't it seem confusing and mixed up? Intuitively, it might seem that cookie session checks should go with `setCookie` and persistence with `save`. You have to dig deeper just to see that in this context `usingCookieSessions` is checking for entire session being stored in a cookie (and not just the session ID, which is usually associated with cookies and sessions), and that `sessionIsPersistent` is checking if the session ID should be persisted between requests (and not persistence of actual session data in the storage).

Just some code comments about the context of these condition checks would save time for those who implement custom session driver, to avoid digging deeper in the source code. Answers to "what" and "how" are provided by the code itself, but the code alone almost never gives answers to *why*, which is the most important question when trying to understand the essence of the process.

I'm still somewhat new to Laravel and English is not my native language, so I don't feel competent enough to provide correct comments to clear this confusion. But the issue is closed now and I guess finding this issue in search results will provide enough information for those who might get confused the same way I was.
