### ISSUE TITLE
[5.1][5.2][5.3] Inconsistency between view() helper and View::make facade

### ISSUE THREAD

**Issue by delatbabel** [laravel/framework#15405]
- Laravel Version: 5.1 through 5.3
- PHP Version: 5.6, 7
- Database Driver & Version: N/A

### Description:

There is an inconsistency between the View class (`Illuminate\View\View`) and the `view()` helper in `Foundation\helpers.php`.

In `view()` there is this code:

```php
    $factory = app(ViewFactory::class);
```

This produces whichever instance of the class that the application has bound to the factory contract `Illuminate\Contracts\View\Factory`.  By default this is `Illuminate\View\Factory` but any application can over-ride this with an extension of that class and by adjusting the core container aliases (e.g. in a service provider).

In the constructor of the `Illuminate\View\View` class there is this:

```php
    public function __construct(Factory $factory, EngineInterface $engine, $view, $path, $data = [])
    {
        $this->view = $view;
        $this->path = $path;
        $this->engine = $engine;
        $this->factory = $factory;

        $this->data = $data instanceof Arrayable ? $data->toArray() : (array) $data;
    }
```

This means that the View's class idea of the factory object is always an object of class **Illuminate\View\Factory** and not the class that the application has bound to the interface.  Note that relative to this `Illuminate\View\View` class, `Factory` always means the `Illuminate\View\Factory` class due to namespace resolution rules.

To me it seems that the easiest solution would be to either:

* drop the Factory declaration from the constructor and set $this->factory = app(ViewFactory::class); in the constructor, making it work like the view() helper.
* Replace the Factory declaration of $factory in the class with `Illuminate\Contracts\View\Factory` and ensure that this is appropriately DI'd by the container.

### Steps To Reproduce:

* Override the binding for `Illuminate\Contracts\View\Factory` with a service provider, e.g. one from https://github.com/delatbabel/viewpages
* Create a view that can be found by the overridden factory class but not by the native Laravel View\Factory class (e.g. in the above instance by placing a view in the database).
* `view('myview')` and `Illuminate\Support\Facades\View::make('myview')` now produce inconsistent results.

**Comment by GrahamCampbell** [comment]
The helper is not meant to be a proxy to the facade. They are different.

**Comment by delatbabel** [comment]
That's not the point.  The helper works, the facade does not work. It would be useful to make the facade work properly instead of having it incorrectly use the wrong factory class.

**Comment by delatbabel** [comment]
OK so if closing the ticket implies no further action and that you're happy with broken code sitting in the framework, then perhaps indicate that by adding as a comment (either in the class header or the documentation) that the View class is broken and that the facade should not be used. I consider that a fairly lame response, however.
