### ISSUE TITLE
Collection::mapWithKeys() works incorrectly for keys with integer values

### ISSUE THREAD

**Issue by mikelmi** [laravel/framework#15409]
- Laravel Version: 5.3.9
- PHP Version: 7.0.8
- Database Driver & Version:

### Description:
`Collection::mapWithKeys()` works incorrectly for keys with integer values (and for string values like '1', '2', ...);
It returns a collection with numerical keys starting from zero (0, 1, 2, ...)

### Steps To Reproduce:
Try to run following code:
```
            $collection = collect([
                ['id' => 1, 'name' => 'A'],
                ['id' => 2, 'name' => 'B'],
                ['id' => 3, 'name' => 'C']
            ]);
            
            $collection = $collection->mapWithKeys(function($item) {
                return [$item['id'] => $item];
            });

            dd($collection->keys()->all());
````
The result will be: 
```
array:3 [
  0 => 0
  1 => 1
  2 => 2
]
```
Expected result:
```
array:3 [
  0 => 1
  1 => 2
  2 => 3
]
```

**Comment by themsaid** [comment]
Hello @aguimaraes, what's your input here? I know this issue is more related to `collapse()` but hope you had this case in mind while building `mapWithKeys()` is that intended?

**Comment by aguimaraes** [comment]
Hello @themsaid.

This function was not meant to be used with numeric keys.

This weird behavior was predicted by @adamwathan here:

https://github.com/laravel/framework/pull/14430#discussion_r74266705

The problem arises when `flatMap` calls `collapse` which calls `array_merge` who will renumber numeric keys.

Using the `+ ` operator would avoid that in `collapse`.

I don't know if this change is worth it, because it is a breaking change.

Thanks,
Álvaro.

**Comment by themsaid** [comment]
Thank you @aguilarcarlos using `+` is breaking indeed.

@mikelmi Looks like you'll need to make your own collection macro.

**Comment by aguimaraes** [comment]
You're welcome @themsaid 

@mikelmi take a look here:

https://github.com/spatie/laravel-collection-macros

Talk to @freekmurze about that feature.

**Comment by fernandobandeira** [comment]
Supposing that you need to use ```mapWithKeys``` to format the key and the values thus being not viable to use ```pluck```.
There's two simple fixes for this issue, depending on what return you want.

1) You need to get a key=>single value pair, then  you can combine mapWithKeys and pluck:

```php
$collection = $collection->flatMap(function($item) {
      return [$item['id'] => ['name' => $item['name'], 'key' => $item['id']]];
    })->pluck('name','key');
```

2) You need to get a key => array value pair, then you can combine maWithKeys and keyBy.
```php
$collection = $collection->flatMap(function($item) {
      return [$item['id'] => ['name' => $item['name'], 'key' => $item['id']]];
    })->keyBy('key');

// 1 => ['name' => 'A', 'key' => 1];
```

Both of these are easy workarounds for keeping your integer key.
Not sure if you got the idea but it should be helpful.

**Comment by mikelmi** [comment]
Thanks all
For my case `keyBy()` resolves the problem

**Comment by vissermc** [comment]
why is this issue closed? This has bitten me. It is also undocumented. It should be documented or fixed.

Also 'filter' is broken, i.e. the example given in the documentation fails (it does not return [3,4], but [2=>3, 3=>4])

I'm inclined to stop using Collections altogether because I cannot trust the documentation/behavior.

**Comment by adster13** [comment]
For my use case I was able to just do a simple workaround, by putting them the opposite way then calling `flip()`...

    $collection = $collection->mapWithKeys(function($item) {
        return [$item['name'] => $item['id']];
    })->flip();

**Comment by datune** [comment]
Not sure why this behaviour is not documented, I spend an hour tracing it. In the end I ditched laravel collection methods all together and just:
```php
$keyed = [];
foreach ($items as $item) $keyed[$item->id] = $item;
```

**Comment by adamwathan** [comment]
As far as I know this behavior was corrected for 5.4:

https://github.com/laravel/framework/pull/16564

@datune, try the latest version and see if it behaves the way you want, I think it likely does 👍

**Comment by omarjebari** [comment]
adster13 fix will only work if the $item['name'] values are unique otherwise there's a chance previous values will get overwritten.

**Comment by troygilbert** [comment]
Hey guys, come on, this should be documented! I was pulling my hair out trying to get this to work, it wasn't until I dug into the source code and saw it used `array_merge` and happened to remember from past experience with `array_merge` that it re-indexed integer keys (which is desirable in the case of `array_merge`, but totally unexpected in a method called `mapWithKeys()`). What's the point of having the documentation be versioned if known issues (bugs!) are not called out in old versions?

**Comment by devcircus** [comment]
Sometimes things get missed. Great thing is the docs are open source. Help out the next person.
