### ISSUE TITLE
Ability to override route domain per request

### ISSUE THREAD

**Issue by mstephens** [laravel/framework#15407]
- Laravel Version: 5.3.6
- PHP Version: 7.0.8
- Database Driver & Version: mysql

### Description:

Hi guys,

Is there the possibility of adding a parameter options to the route() and action() methods to allow override the route domain on a single request?

Currently the override can only be achieved by calling `forceRootUrl` on the UrlGenerator facade, and then remembering to unset it afterwards. 

    /**
     * Get model URL.
     *
     * @return string|null
     */
    public function getUrlAttribute()
    {
        // Force the application URL for this route
        URL::forceRootUrl(config('app.url'));
        $url = route('doc.show', [$this->hash]);
        URL::forceRootUrl(null);
        return $url;
    }

I'll try to explain the reason why I feel this functionality would be useful:

Environment:

- Interacting with a Laravel application internally (on the same machine) at `http://test-internal`
- Interacting with the same Laravel application externally via `http://test.com`

Situation:

- You would wish for the above 'getter' attribute to return an external URL (using the URL from the `app/config.php` configuration file) no matter whether accessed internally or externally
- Any other URLs (such as routes, redirects etc.) should continue to honour the currently accessed URL (either `http://test.com` or `http://test-internal` as defined by the HTTP server)
- At present not reverting the `forceRootUrl` method, would mean any subsequent calls to generating routes/actions would result in a posible different route domain being returned.

Hopefully this makes sense.

Cheers
Matt

**Comment by themsaid** [comment]
Hello Matt, I think if you post this question on the forums it's more likely you'll get a fast answer unlike posting it here, "Issues" in this repo are for bug reporting only, for suggestions and feature requests please use the https://github.com/laravel/internals repo, otherwise use the forums.
