### ISSUE TITLE
Can`t use auth()->check() in the __construct function of Controller

### ISSUE THREAD

**Issue by BlueGood** [laravel/framework#15418]
- Laravel Version: 5.3.9
- PHP Version:5.6.23
- Database Driver & Version:mysql 5.6

### Description:
I want to use auth()->check() in the __construct function of file App\Http\Controllers\Controller, but auth()->check() always return false. but this work on versions before 5.3

#### I find out the reason: 
In file Illuminate/Routing/Router.php, function gatherRouteMiddleware() use $route->gatherMiddleware(), and $route->gatherMiddleware() use $this->controllerMiddleware(), function controllerMiddleware() will make the controller class before middleware has been executed, so auth()->check() will always return false in the __construct function of file App\Http\Controllers\Controller.

Sorry, my english is so bad, I don`t know if you understand what I say.

### Steps To Reproduce:
<img width="852" alt="qq20160914-0" src="https://cloud.githubusercontent.com/assets/2684889/18498645/a9703fe8-7a6a-11e6-8ebd-cb32e19c61a5.png">
```
    protected $user;

    public function __construct()
    {
        if (auth()->check()) {
            $this->user = auth()->user();

            view()->share('loginUser', $this->user);
        }
    }
```

**Comment by sisve** [comment]
This is intentional. See Controllers > Session In The Constructor in the [Upgrade Guide][1]

> In previous versions of Laravel, you could access session variables or the authenticated user in your controller's constructor. This was never intended to be an explicit feature of the framework. In Laravel 5.3, you can't access the session or authenticated user in your controller's constructor because the middleware has not run yet.

[1]: https://laravel.com/docs/5.3/upgrade#upgrade-5.3.0
