### ISSUE TITLE
[5.3] pagination not displayed on pages with 1 record

### ISSUE THREAD

**Issue by jozeflambrecht** [laravel/framework#15416]
- Laravel Version: 5.3.9
- PHP Version: tested with 5.6.25 and 7.0.10
- Database Driver & Version: MySql 5.1.73

When paginating eloquent results with 
`$flights = Flight::orderBy('date', 'desc')->simplePaginate(5);`

and having 6 flights in my database -> the pagination is displayed (with 2 pages) and when I click on page 2, the pagination disappears. This was not the case with 5.2

EDIT: after more testing, pagination always disappears when $flights->count() of that page is 1. When I have $flights->count() > 1, I see the pagination.
Note: I also see the navigation when I only have 2 flights in my database..

**Comment by ahmedash95** [comment]
Laravel Framework version 5.3.0-RC1
PHP 7.0.10
Database Driver & Version: MySql 5.6.31

works fine

**Comment by GrahamCampbell** [comment]
Was only a bug in the old 5.3 version. Check you've not published the older broken views please.

**Comment by jozeflambrecht** [comment]
Graham, I did:
```
php artisan vendor:publish 
php artisan cache:clear
php artisan view:clear
```
still the same.. Something else I forgot?

**Comment by jharrvis** [comment]
@jozeflambrecht how do you solve this issue? I do the same php artisan command but still not solve this issue.

**Comment by jozeflambrecht** [comment]
yes I did. Did you use `php artisan vendor:publish --tag=laravel-pagination --force` ?

**Comment by jharrvis** [comment]
```
Copied Directory [/vendor/laravel/framework/src/Illuminate/Pagination/resources/views] To [/resources/views/vendor/pagination]
Publishing complete for tag [laravel-pagination]!
```

yes, I did, but it not solve the problem
Laravel Framework version 5.3.6
PHP Version 5.6.25-2
MySql 5.0.11
