### ISSUE TITLE
Unauthenticated exception handler not configurable

### ISSUE THREAD

**Issue by jnguyen32** [laravel/framework#15419]
It took me a short while to find this as the latest documentation doesn't cover it. 

Effectively, if you implement your own login controllers/routes, there's no configurable method for telling Laravel where your login route is.

The new Auth middleware now throws an exception (good), and then that exception is handled and the 'unauthenticated' method is called.

The unauthenticated method is as follows:

```
protected function unauthenticated($request, AuthenticationException $exception)
    {
        if ($request->expectsJson()) {
            return response()->json(['error' => 'Unauthenticated.'], 401);
        }

        return redirect()->guest('login');
    }
```

The problem with:

```
return redirect()->guest('login')
```

is that it forces the developer to search and discover this implementation if they need to update the login route, which is different than other executions within Laravel.

My recommendation is that in the ~/config/auth.php, allow the developer to specify the redirectTo or some other variable that these types of functions will use.

Thusly,

```
protected function unauthenticated($request, AuthenticationException $exception)
    {
        if ($request->expectsJson()) {
            return response()->json(['error' => 'Unauthenticated.'], 401);
        }

        return redirect()->guest(config('auth.redirectUnauthorized'));
    }
```

**Comment by GrahamCampbell** [comment]
You can just override the methods you want to change.
