### ISSUE TITLE
authorization Callbacks does not work for private channels in laravel

### ISSUE THREAD

**Issue by ahmadbadpey** [laravel/framework#15420]
I succeed to implement a realtime notifications in laravel via Pusher.

For that I follow all instructions described in laravel documentations.

This is my BroadcastServiceProvider :

```
public function boot ()
        {
            Broadcast::routes();


            Broadcast::channel('App.User.*', function ($user, $userId) {
                return (int)$user->user_id === (int)$userId;
            });

        }

```
And below is Javascript codes to fire events:
```

var pusher  = new Pusher("xxxxxxxxxxxxx",{
                auth: {
                    headers: {
                        'X-CSRF-Token': '{{ csrf_token() }}'
                    }
                }
            });
            var channel = pusher.subscribe('private-App.User.{{$AuthUser->user_id}}');
            channel.bind('Illuminate\\Notifications\\Events\\BroadcastNotificationCreated', function (data) {
                alert(data);
            });

```
All things works properly.

But for test I returned false inside `Broadcast::channel('App.User.*',` like this :

```
Broadcast::channel('App.User.*', function ($user, $userId) {
        return false;
});
```
But I do not know what does this part of the Code while return a true or false value Does not have any effect on its performance.

what does exactly here?

**Comment by themsaid** [comment]
The channel name is different `App.User.*` & `private-App.User.*`.

**Comment by ahmadbadpey** [comment]
I changed `Broadcast::channel('App.User.*'` to `Broadcast::channel('private-App.User.*'` with `returning false` But Does not matter.

**Comment by themsaid** [comment]
Oops, sorry about my last comment, it wasn't correct :) You can trim the `private-` part of the channel name.

Please complete the requirements for opening a valid issue:

- Laravel version
- PHP Version

**Comment by themsaid** [comment]
Also to recap, even when you return false you can still listen to that channel, right?

**Comment by ahmadbadpey** [comment]
@themsaid, Yes.

**Comment by themsaid** [comment]
@ahmadbadpey since you're not using echo you need to register your authentication endpoint pusher, please check the documentation here: https://pusher.com/docs/authenticating_users.

Use `/broadcasting/auth` as your endpoint and give it a try.

**Comment by ahmadbadpey** [comment]
this is my PusherController : 
```
		class PusherController extends Controller
	{
		public $pusher;

		public function __construct ()
		{
			$this->pusher = new Pusher(\Config::get('pusher.connections.main.auth_key'), \Config::get('pusher.connections.main.secret'), \Config::get('pusher.connections.main.app_id'));
		}

		public function auth (Request $request)
		{
			$user = Auth::user();
			if (Auth::check()) {
//				$presence_data = array ('name' => $user->name . " " . $user->family);

				return $this->pusher->socket_auth($request->get('channel_name'), $request->get('socket_id'));
			} else {
				return Response::make('Forbidden', 403);
			}
		}
	}
```
and in the web.php I added:
	Route::post('pusher/auth', 'PusherController@auth');
Do you think that this is not true?

**Comment by themsaid** [comment]
Maybe, but your not using `Broadcast::auth()`, so the following code won't executed:

```
Broadcast::channel('App.User.*', function ($user, $userId) {
        return false;
});
```

Closing since it's not actually a bug report. Please feel free to ask in the forums.

**Comment by ahmadbadpey** [comment]
I added : 
`authEndpoint: '/broadcasting/auth',`
to Pusher initialization. 

but each time Pusher requests that , redirected to `403`error page that I have provided.

**Comment by spmsupun** [comment]
@ahmadbadpey  did u get fixed ?

**Comment by tiagomatosweb** [comment]
I am also facing this same issue. Did anybody get it right?

**Comment by spmsupun** [comment]
@tiagomatosweb  i ended up  using laravel echo server with socket.io

**Comment by eyaylagul** [comment]
+ 1
