### ISSUE TITLE
pushMiddlewareToGroup not working on tests but working on app

### ISSUE THREAD

**Issue by acacha** [laravel/framework#15426]
- Laravel Version:  5.3.9
- PHP Version: 7.0.9
- Database Driver & Version: sqlite

### Description:

My tests for package adminlte-laravel are not working because I use pushMiddlewareToGroup in a ServiceProvider to push a Middleware to web group middleware. If I push manually the middleware in App\Http\Kernel.php tests and app works correctly.

### Steps To Reproduce:

In a Laravel fresh installation:

Run:

$ php artisan make:auth

And:
- Configure Laravel to use sqlite
- Create a ServiceProvider that push a new middleware to web group: https://github.com/acacha/demopushMiddlewareToGroupNotWorkingOnTests/blob/master/app/Providers/GuestUserProvider.php
- Create a middleware that share a $user variable (autenticated user) in all views: https://github.com/acacha/demopushMiddlewareToGroupNotWorkingOnTests/blob/master/app/Http/Middleware/GuestUser.php
- Test home page after login: https://github.com/acacha/demopushMiddlewareToGroupNotWorkingOnTests/blob/master/tests/ExampleTest.php . Tests will thrown and exception user variable does not exists. If you put the middleware manually on Kernel.php fill all works correctly.

Check:

https://github.com/acacha/demopushMiddlewareToGroupNotWorkingOnTests

as an example

**Comment by themsaid** [comment]
In your `tests/TestCase.php` you need to build `Http\Kernel` before bootstrapping the application.

    public function createApplication()
    {
        $app = require __DIR__.'/../bootstrap/app.php';

        $app->make('Illuminate\Contracts\Http\Kernel');

        $app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

        return $app;
    }

This will solve your issue, meanwhile I'll check if it's a good idea to have this shipped by default.

**Comment by acacha** [comment]
Thanks @themsaid! It works! For me it seems good idea to ship this by default but I'm not and expert. If you want I can create a PR pointing to this issue to consider this?

**Comment by themsaid** [comment]
yes please :) We'll need to hear from others about what they think.

**Comment by acacha** [comment]
Done
