### ISSUE TITLE
[5.3] bindValues() now binds LONG ints as SIGNED ints in PHP 5.6

### ISSUE THREAD

**Issue by andkom** [laravel/framework#15429]
- Laravel Version: 5.3.9
- PHP Version: 5.6.23
- Database Driver & Version: mysql 5.5.49

### Description:

When i bind LONG INT, number is converted to SIGNED INT

### Steps To Reproduce:

`
DB::select('select ?', [3557138101]);
`

returns:

`
-737829195
`

actual SQL executes:

`
select -737829195;
`

**Comment by ntzm** [comment]
What DB driver?

**Comment by kamui545** [comment]
```
Psy Shell v0.7.2 (PHP 5.6.24-1~dotdeb+7.1 — cli) by Justin Hileman
>>>  DB::select('select ?', [3557138101])
=> [
     {#890
       +"?": 3557138101,
     },
   ]
```

MySQL 5.7 though

**Comment by andkom** [comment]
driver mysql

**Comment by srmklive** [comment]
You need to update the MySQL to v5.6 or later.

**Comment by andkom** [comment]
It was breaking change in 5.3 so i had to update php & mysql.
In 5.2 everything worked fine.
I think Laravel should specify mysql v5.6 as requirement in upgrade guide

**Comment by themsaid** [comment]
Thank you @andkom for your report, please feel free to open a PR in the docs repository with your suggested updates to the upgrade guide.

Closing since it's not actually a bug report. Thanks again :)
