### ISSUE TITLE
[Proposal] Making "where like" statement more robust.

### ISSUE THREAD

**Issue by Modelizer** [laravel/framework#15425]
Hi,
   I was going through API and want to find the best way to make "like statement" easier. In the end, I need to manage it on scope level.
Suppose if a user want to make more then 3 to 4 like statements, so he needs to repeat himself by `$model->where('column', 'LIKE', '%value%')`. To solve this query what I did is
```php
   $model->like([
            'current_designation' => $request['designation'],
            'location'            => $request['location'],
            'gender'              => $request['gender'],
            'contact_number'      => $request['content_number'],
        ], [
            'first_name'          => $request['name'],
            'last_name'           => $request['name'],
        ]);
```
and added like method in model
```php
    public function scopeLike($q, array $andStatement, array ...$orStatements)
    {
        foreach ($andStatement as $key => $value) {
            if (! $value) { continue; }

            $q = $q->where($key, 'LIKE', "%$value%");
        }

        foreach ($orStatements as $orStatement) {
            if (! count($orStatement)) { continue; }

            $q->where(function ($q) use ($orStatement) {
                foreach ($orStatement as $key => $value) {
                    if (! $value) { continue; }

                    $q = $q->orWhere($key, 'LIKE', "%$value%");
                }

                return $q;
            });
        }

        return $q;
    }
```

Note: First parameter of like method will be "and statement" and remaining parameters will be treated as "or statements".

This will be useful in scenarios such as search, multiple "like" bindings and much more.

**Comment by themsaid** [comment]
Hello @Modelizer, thank you for suggestions but that repo is only from bug reports :)

Please feel free to open a PR or use the https://github.com/laravel/internals repo to discuss your proposal.

**Comment by Modelizer** [comment]
Ohh thanks, I made a mistake :sweat_smile:
