### ISSUE TITLE
[5.3] Implicit model bindings not working for api routes by default

### ISSUE THREAD

**Issue by thats4shaw** [laravel/framework#15434]
It appears routes containing model bindings defined in routes/api.php do not work by default.  Currently the model in question will return an empty object.

```
Route::group([
    'prefix' => 'api',
    'middleware' => 'auth:api'
)], function () {
    Route::delete('/item/{item}', 'Api\ItemController@destroy');
});
```

```
public function destroy(Request $request, Item $item)
{
    dd($item)
}
```

If I add 'bindings' to the middleware of the route group it then works.  I would of assumed this wouldn't be required and it would work out of the box?  Apologies if this is not the case.

I'm working off a fresh copy of Laravel 5.3 so my app/Http/Kernel.php is all up to date and model bindings work as expected within routes/web.php.

**Comment by GrahamCampbell** [comment]
Looks like you didn't add the bindings middleware as required in the upgrading docs.

**Comment by thats4shaw** [comment]
I'm experiencing this behaviour with a fresh 5.3 Spark project.  The binding middleware should be present already should it not?

**Comment by rs-sliske** [comment]
i think by default it is only added to the web route group, not api

**Comment by themsaid** [comment]
@thats4shaw @rs-sliske it's there by default on all fresh installations: https://github.com/laravel/laravel/blob/master/app/Providers/RouteServiceProvider.php#L72

**Comment by rs-sliske** [comment]
@themsaid i mean the middleware isnt applied to the api group by default https://github.com/laravel/laravel/blob/master/app/Http/Kernel.php#L35-L38 unless im looking in the wrong place

**Comment by thats4shaw** [comment]
I done some more testing on this again today and I believe this is actually
a Spark issue as it works fine for me on a straight Laravel 5.3 project.

**Comment by themsaid** [comment]
Yeah if you're looking at a spark installation then yes, the `api` group isn't there by default but I submitted a PR this morning to make it a default.
