### ISSUE TITLE
Rename columns in table with ` around name

### ISSUE THREAD

**Issue by dietercoopman** [laravel/framework#15437]
- Laravel Version: 5.1.40
- PHP Version: 5.5.9
- Database Driver & Version: Mysql 5.5.47-0ubuntu

### Description:
Case changes to lowercase when renaming columns ( my columns do have capitals ) , only when adding `around table name.

When i trie to rename a column in my database via the Schema Builder it throws me an error because the source column is not found ( Embossing_id vs embossing_id ) .  It only throws the error ( and changes the case ) when i add a qoute around the table name ( i do this because i have tables with spaces in it ).
When i remove the ` it works fine , but that's not an option for me ( because i get sql errors on tables with spaces on it ).  

**I solved this for my case bij useing plain sql statement like this:** 
```
private function setStatement($statement)
    {
        return \DB::connection('mysql')->statement($statement);
    }
public function rename($tablename,$oldField,$newField){
                $this->setStatement("ALTER TABLE `{$tablename}` CHANGE `{$oldField}` `{$newField}` INT DEFAULT NULL");
}
```

**Her is a piece of the stacktrace where i see the case is changeing :** 
```
at SchemaException::columnDoesNotExist('embossing_id', 'REL_RelCutterguideEmbossing') in Table.php line 671
at Table->getColumn('Embossing_id') in Connection.php line 809
at Connection->getDoctrineColumn('`REL_RelCutterguideEmbossing`', 'Embossing_id') in Grammar.php line 34
```
### Steps To Reproduce:
Rename a column named "ID" to "id" on a table with a space in it via Schema Builder
```
CREATE TABLE `new table` (
  `ID` int(11) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
```
get('test',function(){
    $table = "`new table`";
    \Schema::connection("mysql")->table($table, function($table)
    {
        $table->renameColumn('ID', 'id');
    });

});
```

**Comment by lasselehtinen** [comment]
This is probably related to similar issue #15195 and how Doctrine normalizes the column names?

**Comment by dietercoopman** [comment]
Ok , i understand that this is a Doctrine issue , but wouldn't it be more "friendly" to throw an error when someone tries te make / rename a field with uppercase in it when using the Schema Builder.
