### ISSUE TITLE
DB Schema don't have "bit" value

### ISSUE THREAD

**Issue by mmnharalamov** [laravel/framework#15443]
тhe title EXPLAINS EVERYTHING.
please WRITE APPROPRIATE FRAMEWORK OR 
DO NOT WRITE ANYTHING  ok ?

**Comment by fernandobandeira** [comment]
> тhe title EXPLAINS EVERYTHING.
please WRITE APPROPRIATE FRAMEWORK OR 
DO NOT WRITE ANYTHING ok ?

Well despite your attitude i'll paste this comment from [stackoverflow](http://stackoverflow.com/questions/36225328/laravel-give-data-type-bit-byte-in-migration)

> Instead of trying to use the BIT datatype, which would be a bit of a hassle to work with, you can just use an integer and bitwise operators instead, assuming you don't need more than 32 options for one field (bigint = 8 bytes = 32 bits).

**Comment by mmnharalamov** [comment]
THX :) Actually its an issue :P

**Comment by w3lifer** [comment]
@fernandobandeira, What if I don't have access to edit column types?
