### ISSUE TITLE
Authentication Laravel 5.3

### ISSUE THREAD

**Issue by ito2307** [laravel/framework#15447]
- Laravel Version:  "laravel/framework": "5.3.*",
- PHP Version: 7.0
- Database Driver & Version: Navicat with mariadb

### Description:
I'm trying to implement in my project the active directory similar to windows.
It's called cemaco, first i had have problems with theversion of ldap so update. Now i'm trying to implement it but i get this issue --> Authentication user provider [] is not defined and i changed in cemaco the version o laravel, now i did some configure in my project.

### Steps To Reproduce:
https://laracasts.com/discuss/channels/general-discussion/authentication-user-provider-is-not-defined

**Comment by themsaid** [comment]
I'm sorry but this doesn't look like a bug report, you did the right thing asking on the forums.
