### ISSUE TITLE
[5.3] What is the purpose of "resetNotifier" in "SendsPasswordResetEmails" trait

### ISSUE THREAD

**Issue by ElfSundae** [laravel/framework#15445]
- Laravel Version: 5.3.9

There is a method `resetNotifier` in the `SendsPasswordResetEmails` trait, but it is not called at all. Maybe we should remove it, or add a parameter in `PasswordBroker::sendResetLink` just like `PasswordBroker::reset` does.

From the PHPDoc, I guess this method would be used to return a notification like this:

```php
/**
 * Get the Closure which is used to build the password reset notification.
 *
 * @return \Closure
 */
protected function resetNotifier()
{
    return function ($token) {
        return new ResetPasswordNotification($token);
    };
}
```

Am I right? Then what notification instance will be used if the notifiable object implemented `CanResetPassword` trait?

**Comment by themsaid** [comment]
You're right, this method is not used and should be deleted. Removed in https://github.com/laravel/framework/pull/15446

To use a custom Notification you need to overwrite the `sendPasswordResetNotification` in your User model, this method is coming from the `Illuminate\Auth\Passwords\CanResetPassword` trait.

**Comment by aschwin** [comment]
This used to be the resetEmailBuilder() method. Now our application doesn't work and nowhere is a clear example how to migrate from this method to the Notification method.
