### ISSUE TITLE
Resolving seeder object returns error

### ISSUE THREAD

**Issue by luqmanrom** [laravel/framework#15449]
- Laravel Version: 5.2.X
- PHP Version:
- Database Driver & Version:

### Description:
`app('seeder')` returns error:

```  
Cannot instantiate abstract class Illuminate\Database\Seeder
```
### Steps To Reproduce:

Try to resolve the seeder object: `app('seeder')`

The culprit is here. Seeder is abstract class cannot be constructed with new:

https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/SeedServiceProvider.php#L25

**Comment by themsaid** [comment]
Thank you, submitted a PR to remove this registration line https://github.com/laravel/framework/pull/15450.
