### ISSUE TITLE
[5.3] There is no way to add custom headers to a notification sent via mail

### ISSUE THREAD

**Issue by j3j5** [laravel/framework#15453]
- Laravel Version: 5.3.9
- PHP Version: 7.0.10
- Database Driver & Version: mysql 10.1.17-MariaDB

### Description:
When sending a notification via mail, there is no way to add custom headers to it. 

I understand notifications are meant to be simple messages, but for example, when using Mandrill you need to send a custom header if you want your messages to be sent through one of your subaccounts. This is impossible AFAICS for notification emails and that messes hard with my Mandrill account.

A similar function to the one on the Mailable class (`withSwiftMessage`) allowing to access the SwiftMessage would fix this.

### Steps To Reproduce:
Try to attach custom headers when sending a notification via email.

**Comment by GrahamCampbell** [comment]
Thanks, but this isn't a bug report. Please submit proposals to the internals repo.

**Comment by kedves** [comment]
Did you managed to append the headers?

**Comment by j3j5** [comment]
Yes, you can see the issue (and the solution I found) [here](https://github.com/laravel/internals/issues/214).
