### ISSUE TITLE
Error on return array on controller

### ISSUE THREAD

**Issue by rafwell** [laravel/framework#15452]
- Laravel Version: 5.2.45
- PHP Version: 7
- Database Driver & Version: ODBC  with Access 2013 Database.

### Description:

When i return this array on controller:
![image](https://cloud.githubusercontent.com/assets/2893078/18568653/9650b3ce-7b74-11e6-92c3-646b1eb05f13.png)

Expecting get the json representation, i get this error: 
![image](https://cloud.githubusercontent.com/assets/2893078/18568702/d1f4a444-7b74-11e6-809d-858b32db42b9.png)

Thanks.

**Comment by srmklive** [comment]
Try to do `return response()->json($response);`. This will resolve the error.

**Comment by rafwell** [comment]
Hi! When i changed my code i get this error: `Malformed UTF-8 characters, possibly incorrectly encoded. I don't know why but the field "andar" has a b" preffix, so i did a muttator on model, converting him to utf8. And the problem are solved. Thanks.
