### ISSUE TITLE
Queue with Redis doesn't work as expected

### ISSUE THREAD

**Issue by ahmedash95** [laravel/framework#15457]
- Laravel Version: 5.3.9
- PHP Version: 7.0.10

### Description:

i'm trying to process a ffmpeg command for making a video file , i'm using Redis for queue but 

when i run ``` php artisan queue:listen ``` i get no output even if i dispatch the job many times , i 

tried to monitoring the Redis and i found the job is already pushed to redis but i see at the end of 

json array key { attempts\":41 } and it's keep increasing , but if i edit my env QUEUE_DRIVER to 

sync the job works fine

**Comment by GrahamCampbell** [comment]
If your job runs for more than 60 seconds, you need to increase the expiry time, otherwise the job is assumed to have crashed, and then will be picked up again.

**Comment by ahmedash95** [comment]
>  you need to increase the expiry time

@GrahamCampbell do you mean php or redis ?
