### ISSUE TITLE
Relationship with JSON foreign key

### ISSUE THREAD

**Issue by hafezdivandari** [laravel/framework#15465]
Is it possible to add a feature to make relationships with JSON property as foreign key in Laravel 5.3?

```
class User extends Model
{
    /**
     * Get the users's preferred locale.
    /*
    public function locale()
    {
        return $this->belongsTo('App\Locale', 'preferences->locale_id', 'id');
    }
}
```

**Comment by themsaid** [comment]
I would strongly advise against that :)

**Comment by hafezdivandari** [comment]
Is there any reason for that?

**Comment by themsaid** [comment]
A json structure can easily get changed accidentally which will lead to unclear relationships. Anyway for such suggestions it's better that you open an issue in the internals repository rather than here.

**Comment by wa05** [comment]
Any approach on how to make that relation using the query builder?

**Comment by hafez-bsup** [comment]
@wa05 I haven' tried this but it may work:
```
$users = DB::table('users')
            ->leftJoin('locales', 'users.preferences->locale_id', '=', 'locales.id')
            ->get();
```

**Comment by hafezdivandari** [comment]
@wa05 I haven' tried this but it may work:
```
$users = DB::table('users')
            ->leftJoin('locales', 'users.preferences->locale_id', '=', 'locales.id')
            ->get();
```

**Comment by staudenmeir** [comment]
I created a package for this: https://github.com/staudenmeir/eloquent-json-relations
