### ISSUE TITLE
Artisan::output doesn't capture the commands output after several calls

### ISSUE THREAD

**Issue by johnnymn** [laravel/framework#15467]
- Laravel Version: 5.2.45
- PHP Version: 7
- Database Driver & Version: sqlite

### Description:

When we execute several Artisan Console Commands from other commands with the `Artisan::call()` method and try to capture their output in a successive way with the `Artisan::output()` method after some calls the output starts to show as an empty string instead of the actual command output. This probably has to do with flushing the output stream.

### Steps To Reproduce:

Call an Artisan Console command from another one several times (in my case was about 16) and try to capture the output with the `Artisan::output()` method.

**Comment by srmklive** [comment]
You need to manually capture the output. I normally do it through like this:
```
use Symfony\Component\Console\Output\BufferedOutput;

function runArtisanCommand($command)
{
    $output = new BufferedOutput;

    Artisan::call($command, array(), $output);

    return $output->fetch();
});
```

**Comment by themsaid** [comment]
@srmklive  I don't think the `call()` method takes three parameters.

**Comment by srmklive** [comment]
@themsaid It does. The third parameter is optional.

**Comment by lisurc** [comment]
I also wanted to capture the output of the `Artisan:call()` method. Maybe I'm missing something too, but I can't see a third parameter in version 5.2.45 of the framework.

**Comment by tgiordmaina** [comment]
I think third parameter doesn't exists on this version of laravel 5.2+.

So try this :
```
        ob_start();
        $exitCode = \Artisan::call('refresh:cache', []);
        $output = ob_get_contents();
        ob_end_clean();
        dd($output);

```
