### ISSUE TITLE
Eloquent - different connection vs all() method

### ISSUE THREAD

**Issue by jakubkratina** [laravel/framework#15469]
- Laravel Version 5.3
- PHP Version: 7
- Database Driver & Version: MySQL 14.14

Hi guys,

I have found strange behavior.

I'm working on a development/production database replication.

**Production Database:**
- image ID 1
- image ID 2
- image ID 3

**Development Database:**
- image ID 3

Now to the problem:

I set connection dynamically:
```
$images = new Image;
$images->setConnection($this->development->getName()); // development ===  $manager->connection('mysql_development')

$images->get()->firts()->id // returns corretly ID 3 from development database
$images->all()->first()->id; // returns ID 1 from production database, wtf, why?
```

Is here something wrong or I just don't understand get and all methods?

Jakub

**Comment by GrahamCampbell** [comment]
Looks correct. Your first one isn't ordered, so your database just gets some random row and gives it to you. The same goes for the 2nd one really.

**Comment by GrahamCampbell** [comment]
Look into orderBy. :)

**Comment by jakubkratina** [comment]
But development database contains only one row with the ID 3, how can it returns ID 1? The connection is set to the development database, where is only one row.

**Comment by GrahamCampbell** [comment]
Errr, no idea.

**Comment by jakubkratina** [comment]
Yes, this is why I said it's weird to me :) From me it looks like `all()` method does not work well with changed connection.

**Comment by thecrypticace** [comment]
All is a static method: https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Eloquent/Model.php#L626

PHP let's you call it dynamically but sadly gives no indication of that happening.

**Comment by themsaid** [comment]
Any reason why not just use `get()`? I don't think there's a way to fix this without making a breaking change.

**Comment by jakubkratina** [comment]
@themsaid: There is no reason. At first I used the `all` method. I did not know `get` method works.

**Comment by jarnovanleeuwen** [comment]
I do not know exactly how you change from development to production database, but when you reuse connection names (i.e. keeping the model's `$connection` and changing the config) you should purge the old connection with `DB::purge('connection-name')` after making your changes. Otherwise Laravel will continue to use the other database out of its connection resolver cache.

**Comment by GrahamCampbell** [comment]
Doesn't look like a bug since all isn't a method that respects the object state since it's static by design.
