### ISSUE TITLE
Laravel Echo SocketId

### ISSUE THREAD

**Issue by ZeyadMounir** [laravel/framework#15466]
- Laravel Version: 5.3

In broadcasting Documentation, it's written that I can get the socket id manually though Echo.socketId();
but it gives undefined, I figured out that it takes time to be defined. When I put  Echo.socketId(); in setTimeout after 1000 ms, the socket id becomes defined!

**Comment by morloderex** [comment]
This might be due calling this function before a connection has been made.

**Comment by ZeyadMounir** [comment]
Yes, but I call this function after the call of Echo and the Channel, so I guess the connection takes time.

**Comment by themsaid** [comment]
@ZeyadMounir any suggestions from your side about this? Do you think it's a bug that needs fixing or just require adding some information to the docs?

**Comment by ZeyadMounir** [comment]
I don't really know!
This is how I fixed it and add the header to Ajax:
`      Echo.private("conversation.{{$conversation->id}}").listen('MessageSent', addMessage);
      setTimeout(function()
      {
        var socket_id =  Echo.socketId();
        $.ajaxSetup({
            headers: {'X-Socket-ID': socket_id}
        });
      }, 2000);
`

**Comment by themsaid** [comment]
I'm closing since it doesn't seem to be a bug actually, I think it's the way it works.

**Comment by ZeyadMounir** [comment]
`     var pusher = Echo.private("conversation.{{$conversation->id}}").listen('MessageSent', addMessage);
      pusher.on('pusher:subscription_succeeded', function() {
        var socket_id =  Echo.socketId();
        $.ajaxSetup({
            headers: {'X-Socket-ID': socket_id}
        });
      })
`
Here is a better solution.

**Comment by soynain** [comment]
Zeyad82 solution LGTM, I was having the same issue, no matter if i was declaring the socketId in laravel echo file or directly in front, variable was undefined. Why this happens? it's some sort of bug in the framework? cuz the docs says that 'socketId' is a pre-declared variable.
