### ISSUE TITLE
Contracts of Validator does't work during package development but facade does

### ISSUE THREAD

**Issue by yarcowang** [laravel/framework#15477]
- Laravel Version: 5.3.9
- PHP Version: 7.0

### Description:
I'm doing a package for laravel, for now it is simply a controller with validation in its method as following:
```php
public function someMethod(Request $req)
{
  $validator = Validator::make($req->all(), [
    //...
  ]);
  
  //...
}
```
So, i need to load the class `Validator`. According to the [laravel doc](https://laravel.com/docs/5.3/packages#a-note-on-facades) , it seems i should use `contracts`. So i add:

```php
use Illuminate\Contracts\Validation\Validator;
use Illuminate\Contracts\Validation\Factory;
```
But i'll get error
```
Call to undefined method Illuminate\Contracts\Validation\Validator::make()
```

By using instead of above two
```php
use Validator;
```
it is ok. So i think it might be a bug, contracts should also work.

### Steps To Reproduce:
1. create a package which has a controller
2. use Validator contracts 
```php
use Illuminate\Contracts\Validation\Validator;
use Illuminate\Contracts\Validation\Factory;
```
3. invoke Validator::make in the method of the controller you created in the package

**Comment by GrahamCampbell** [comment]
You can't call a static method on a contract. You need to dependency inject it.

**Comment by yarcowang** [comment]
@GrahamCampbell Not quite understand. It seems i still need to use facade cause the interface can not be instantiable.
```php
use Illuminate\Contracts\Validation\Validator;
use Illuminate\Contracts\Validation\Factory;

	public function edit(Request $req, Validator $validator)
	{
		$validator = Validator::make(...
```
Does't work. Or i miss something?
