### ISSUE TITLE
/broadcasting/auth route does not work to respond to channel authorization requests

### ISSUE THREAD

**Issue by ahmadbadpey** [laravel/framework#15474]
I am using Pusher to Make real-time laravel notifications.

Laravel by default registered `/broadcasting/auth` route to handle authorization requests via `Broadcast::routes();` included in `BroadcastServiceProvider`.

And in initialization of Pusher, there is a authEndpoint option that can use for Setting the Channel Authentication endpoint like this:

```
var pusher  = new Pusher("xxxxxxxxxxxxxxxxxxx", {
                authEndpoint: '/broadcasting/auth',
                auth: {
                    headers: {
                        'X-CSRF-Token': '{{ csrf_token() }}'
                    }
                }
            });
```
As you can see I set it to`/broadcasting/auth` that is declared by laravel.

But when Pusher send a POST request to it , laravel throws a **403** error and redirect to a **403** error page that I created before.

what is Problem and How can I solve that ?

**Comment by themsaid** [comment]
Hello Ahmad,

Please ask questions on the forums, this repository is for bug reporting only. Anyway the 403 response means that it's a private channel while there's no logged in user or laravel is unable to authenticate the request with pusher.
