### ISSUE TITLE
Laravel 4 - Using multiple filters in route is not working.

### ISSUE THREAD

**Issue by Zainulabadeen** [laravel/framework#15489]
- Laravel Version: 4.2.9
- PHP Version: 5.6

Hi guys:

Please help me with the **filter**, only the **first one** is working in route **i.e** birthday filter working but marriage filter don't :-

**In filters.php the code is:**

```
Route::filter('birthday', function ($route, $request, $birthdate) {
   if( $birthdate == '4/12/97')
        return "It's your birthday $birthdate";
});

Route::filter('marriage', function ($route, $request, $marriagedate) {
    if( $marriagedate == '1/1/2017')
        return "It's your marriage anniversary $marriagedate";
});
```

**And in route.php the code is:**

```
Route::get('uniquedates', array('before' => array('birthday:4/12/97', 'marriage:1/1/2017'), function () {
    return View::make('hello');
}));
```
Please help me :(

**Comment by mikerockett** [comment]
Please [ask your question on the forums](https://laracasts.com/discuss/conversations/create).

**Comment by Zainulabadeen** [comment]
I posted it.

**Comment by bobbybouwmann** [comment]
@Zainulabadeen Would be nice if you add a link here as well...

**Comment by GrahamCampbell** [comment]
Only Laravel 5.1 LTS and 5.3 Stable are supported, sorry.

**Comment by bobbybouwmann** [comment]
Here is the thread: https://laracasts.com/discuss/channels/laravel/laravel-4-using-multiple-filters-in-route-is-not-working

**Comment by Zainulabadeen** [comment]
Thanks Bobby and Graham.
