### ISSUE TITLE
Abort function do not set status code in header

### ISSUE THREAD

**Issue by vincoweb** [laravel/framework#15496]
- Laravel Version: 5.2
- PHP Version: 7
- Database Driver & Version:

### Description:
abort() do not set status code in header

### Steps To Reproduce:
abort(404) or abort(505) ....

**Comment by themsaid** [comment]
abort() just throws an `HttpException`, how you handle that exception can be altered by the user. However if no custom handlers defined laravel displays the error view with the status correctly set.

**Comment by vincoweb** [comment]
Thanky you for your replay, but I think it could by set status code in header. It is strange if i set abort() with status code ( for instance abort(500) )  which throw HttpException.  HttpException can set headers in constructor. Why then HttpException do not set headers?  It is misleading that I can set status code in abort function and do not use it for header. 

+ Also abort(404) throw NotFoundHttpException with no status code in header

**Comment by GrahamCampbell** [comment]
There should be no status code header. Http puts the status code before the headers.

For example:

```
HTTP/1.1 404 Not Found
Date: Sun, 18 Oct 2012 10:36:20 GMT
Server: Apache/2.2.14 (Win32)
Content-Length: 230
Connection: Closed
Content-Type: text/html; charset=iso-8859-1
```
