### ISSUE TITLE
GroupBy working fine in 5.2 but not working in 5.3

### ISSUE THREAD

**Issue by whfamily2006** [laravel/framework#15499]
- Laravel Version: 5.3
- PHP Version: 5.6.24
- Database Driver & Version: 5.0
- Local Environment: Windows 10 with Xampp [5.6.24 / PHP 5.6.24]

### GroupBy() usage as follows: 

return $CurrencyPair::with( 'destinationCurrency' )->groupBy( 'destination_currency_id' )->get();

### Error:

> QueryException in Connection.php line 761: SQLSTATE[42000]: Syntax error or access violation: 1055 'paaysay.currency_pairs.id' isn't in GROUP BY (SQL: select * from `currency_pairs` group by `destination_currency_id`)

**Comment by GrahamCampbell** [comment]
Please provide the **full** laravel version.

**Comment by themsaid** [comment]
@whfamily2006 and the database driver please.

**Comment by whfamily2006** [comment]
### Laravel Full version
In my composer.json file  "laravel/framework": "5.3.*"

### Database Driver
In my config/database.php file database drivers is 

> mysql

**Comment by themsaid** [comment]
@whfamily2006 ok, you need to disable strict mode, in `config/database.php` under your mysql connection set `'strict' => false,`.

Strict mode is on by default in laravel 5.3, with strict mode you can't use select *, you'll have to use aggregate functions or select only fields defined in `GROUP BY`.

**Comment by GrahamCampbell** [comment]
> Laravel Full version

That's still not the full version. You can find it by running `composer show -i`.

**Comment by whfamily2006** [comment]
### Laravel Full Version
5.3.9

**Comment by whfamily2006** [comment]
Thanks @themsaid its DONE...
