### ISSUE TITLE
Is documentation about notifications fakes is correct?

### ISSUE THREAD

**Issue by spyric** [laravel/framework#15508]
- Laravel Version: 5.3.9
- PHP Version: 7.0.8

In documentation wrote that I can check is notification sent with that lines:
```
Notification::assertSentTo(
    [$user], OrderShipped::class
);
```

But it fails. And I check the code and there is no lines that responsible for handling of array or collection

**Comment by themsaid** [comment]
Closing since the PR got merged: https://github.com/laravel/framework/pull/15506

**Comment by spyric** [comment]
@themsaid It's not relates issues. I just checeks.  #15506 gives ability to send notification to many users while we use Fake class.

This issue happens when we try to check. So please reopen it.


I can fix it but I need @taylorotwell to tell what is correct behavior when we pass an array: Should tests be failed if we send notification in to 5 users but in check we provide only 4 users (Notification is gotten by more users that we are expecting)

**Comment by themsaid** [comment]
I'd say go ahead and open a PR, it's better to discuss implementations :)
