### ISSUE TITLE
［5.1］Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by djoylove** [laravel/framework#15515]
- Laravel Version:5.1.43
- PHP Version:5.5.26
- Database Driver & Version:
mysql
### Description:
Maximum execution time of 30 seconds exceeded
 
suddenly the four file 
FileTypeFilterIterator,
DateRangeFilterIterator,
ExcludeDirectoryFilterIterator
FilterIterator
occur error:Maximum execution time of 30 seconds exceeded

who know what's wrong with it

**Comment by GrahamCampbell** [comment]
Sounds like a bug in your code.
