### ISSUE TITLE
Route optional parameter doesn't get set or binded

### ISSUE THREAD

**Issue by cristian-stoicescu** [laravel/framework#15517]
- Laravel Version: 4.2.0
- PHP Version: 5.5.9

### Description:
For a given route Route::put('item/{page?}')->defaults('page','home')` and a binding on page
`Route::bind('page',function($value,$route) { return $value + '1' })` the binding itself is not called when the parameter is missing from the url, and the parameter is not set in $route->parameters()

I have found a workaround with a beforeFilter, but still, i'm wondering if there is anything a bit more elegant

### Steps To Reproduce:
Create an route with an optional parameter with a default that has a binding, and see as the binding is not set, and that the optional parameter is not set

**Comment by themsaid** [comment]
`4.2.0` is closed for fixes and enhancements, please consider upgrading.
