### ISSUE TITLE
QueryBuilder when() don't handle var = 0

### ISSUE THREAD

**Issue by honny1990** [laravel/framework#15528]
- Laravel Version: 5.3.10
- PHP Version: 5.6.24

### Description:
If I use the query function when() and my var to be tested is 0, the function don't add the sub query to the main query.
`$state = 0;`
`->when($state, function ($query) use ($state) {
                return $query->where('ships_ui.state', '=', $state);
            })`

I changed when() in Illuminate\Database\Eloquent\Builder and Illuminate\Database\Query\Builder to:
 
`public function when($value, $callback, $default = null)
    {
        $builder = $this;

        if (!is_null($value)) {
            $builder = call_user_func($callback, $builder);
        } elseif (!is_null($default)) {
            $builder = call_user_func($default, $builder);
        }

        return $builder;
    }`
it works.

**Comment by themsaid** [comment]
zero is evaluated as false, so this is an expected behaviour.

**Comment by honny1990** [comment]
i know, but sometimes the var need to be 0.
