### ISSUE TITLE
False redirection.

### ISSUE THREAD

**Issue by Modelizer** [laravel/framework#15523]
- Laravel Version: 5.3.8
- PHP Version: 7.0
- Database Driver & Version: 5.6

### Description:
I reseted `$redirectTo` to `/dashboard` but still after hitting `login` its get redirected to `/home`

### Steps To Reproduce:
1. Run `php artisan make:auth`.
2. Replace `$redirectTo` value to `/dashboard`.
3. Register a user and login.
4. After login manually hit `login` URL.
5. It will be redirected to `/home` URL

**Comment by bobbybouwmann** [comment]
You need to update your `RedirectIfAuthenticated.php` middleware class as well
