### ISSUE TITLE
logout redirect

### ISSUE THREAD

**Issue by hairmenu** [laravel/framework#15525]
- Laravel Version: 5.3

In 5.3 the redirectAfterLogout option seems to be missing. So the is no other way to overwrite the logout method from autehnticatesUsers in order to define another redirect routes (which is the case when you are using multi auth) 

### Steps To Reproduce:
Adding redirectAfterLogout var in loginController is not changing anything

**Comment by themsaid** [comment]
You can just override the logout function and customize the redirect path as you wish.
