### ISSUE TITLE
Builder Update() always updates timestamps

### ISSUE THREAD

**Issue by bretto36** [laravel/framework#15532]
- Laravel Version: 5.3.10
- PHP Version: 5.6.19
- Database Driver & Version: MySql 5.7.11

Description: So is there a way to stop an update query from updating timestamps. I need to run some updates that won't affect the updated_at column but have no way to stop it from updating the timestamp

Steps To Reproduce:

$user->tax_codes()->update(['field' => 1]); 

I'd like to be able to pass either an options array as the second parameter or an alternative someone could suggest. I'd prefer not to use a DB::raw statement to achieve this

**Comment by bretto36** [comment]
I forgot to mention this is for a hasMany relationship

**Comment by caiquecastro** [comment]
Do you want to prevent it from updating the updated_at field on the parent or child class/entity or both?

**Comment by bretto36** [comment]
For me right now all i need is the child class timestamps to be ignored

**Comment by themsaid** [comment]
Convert it to Base Builder:

```
$user->tax_codes()->toBase()->update(['field' => 1]);
```

**Comment by bretto36** [comment]
Thank you @themsaid
