### ISSUE TITLE
Redundant QueryBuilder call

### ISSUE THREAD

**Issue by CnR89** [laravel/framework#15536]
- Laravel Version: 5.*

When we call "updateOrInsert" method laravel runs exists methods to check run insert or update.
Calling "exists" methods already adds where attributes to builder.

So;

https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Query/Builder.php#L2175

`return (bool) $this->where($attributes)->take(1)->update($values);`

  must be 
`return (bool) $this->take(1)->update($values);`

**Comment by themsaid** [comment]
What's wrong with the current implementation?

**Comment by CnR89** [comment]
This implementation causes to duplicate where query.

Like:
`update 'blocks' set blocked_at = '2016-09-21 13:54:10', unblock_at = '' where (blocked_by = '2' and user_id = '1' and performer_id = '1') and (blocked_by = '2' and user_id = '1' and performer_id = '1') limit 1`

**Comment by GrahamCampbell** [comment]
Feel free to PR an improvement if you want.
