### ISSUE TITLE
Missing array attribute in Request from JQuery

### ISSUE THREAD

**Issue by yugidestiny** [laravel/framework#15533]
- Laravel Version: 5.2
- PHP Version: 5.6.20
- Database Driver & Version: MYSQL 
- Server: Linux

### Description:
Hi, I am new and first time create issues post here. Please forgive me if my description of issues is not clear. I am using JQuery Datatable on Laravel, in my linux server I can see the object "search" is generated correctly in console but in my controller I checked the request it only returned 1 attribute ["regex"] and and other attributes was omitted. 

### Steps To Reproduce:
**JQuery Code**
`var d = {
			draw:    settings.iDraw,
			columns: [],
			order:   [],
			start:   displayStart,
			length:  displayLength,
			search:  {
				value: preSearch.sSearch,
				regex: preSearch.bRegex
			},
			srch: {
				value: preSearch.sSearch,
				regex: preSearch.bRegex
			}
		};`
From the console log I can see the variable is correctly populated as from attachment below:
**Console log screenshot**
![console_log](https://cloud.githubusercontent.com/assets/4423085/18697346/e51a974a-7ff2-11e6-921c-dff068d24f12.PNG)

However from controller I captured the request and it only return "regex" in "search" parameter, the "value" was omitted as highlighted in attachment below:
![request_capture](https://cloud.githubusercontent.com/assets/4423085/18697444/ca910e44-7ff3-11e6-85d3-da8796bf8989.PNG)

I have scratched my head for this for a week. Is there some configurations need to be done when parsing data through HTTP Request? I have tried to add some elements in search parameter but everytime it only returned "regex" value. 

Please guide me on this.

**Comment by GrahamCampbell** [comment]
Please ask on the forums.
