### ISSUE TITLE
Session disappears after a few image requests

### ISSUE THREAD

**Issue by frohlfing** [laravel/framework#15551]
- Laravel Version: 5.3.10
- PHP Version: 5.6.25, Not Thread Safety
- Session Driver: file
- OS: SunOS 5.10 (Strato Webhosting) and XAMPP (Mac)

### Description:

When I show a page with a few images and reload the page a few times, the session-data will be lost completely. 

The problem happens on my production system (Linux), and on XAMP (Mac), too. 

### Steps To Reproduce:

The case can be simplified as follows:
Define this routes: 

~~~
Route::get('dummyimage/{i}', function($i) {
    return '';
});

Route::group(['middleware' => 'auth'], function () {
    Route::get('killmysession', function() {
        print_r(Session::all());
        for ($i=0; $i < 500; $i++) {
            echo '<img src="' . url('dummyimage/' . $i) . '"/>';
        }
    });
});
~~~

If you call the url "./killmysession", sometimes your session will be killed. 
When I load the images directly from file, all works fine.

### Workaround: 
I've written "session_start();" on the top of the route file. I know, it is  not the final solution, but it works for me temporarily.

**Comment by GrahamCampbell** [comment]
Doesn't look like a laravel bug, and your session tart hack is really not a good idea. It also has nothing todo with laravel sessions.

**Comment by frohlfing** [comment]
Sorry, don't believe this. If try it without laravel framework, and all works fine:

~~~~
<?php

session_start();

if (isset($_GET['image'])) {
    echo '';
    exit;
}

print_r($_SESSION);

for ($i=0; $i < 500; $i++) {
    echo '<img src="http://localhost/test/kill_my_session.php?image=' . $i . '"/>';
}
~~~

Do you have an idea or a proposal what I can do?

**Comment by frohlfing** [comment]
I can reproduce the issues on this system too:

- Laravel Version: 5.1.33 (LTS)
- PHP Version: 5.5.9
- OS: Ubuntu 14.04

The problem is well know! I found[laravel-locking-session](https://github.com/rairlie/laravel-locking-session).This package addresses the problem where session data will be lost due to concurrent requests.  I have installed it now and it's seems to solve my problem - but I think this is a dirty solution.
What do you think about it?
