### ISSUE TITLE
Troubles after new implementation filterFiles

### ISSUE THREAD

**Issue by chamav** [laravel/framework#15556]
- Laravel Version: 5.3.10
- PHP Version: 7.0.10
- Database Driver & Version:

### Description:
after last changes sometimes we have the error in 

```
class Request extends SymfonyRequest implements Arrayable, ArrayAccess
/**
     * Filter the given array of files, removing any empty values.
     *
     * @param  array  $files
     * @return mixed
     */
    protected function filterFiles($files)
    {
        foreach ($files as $key => $file) {
            if (is_array($file)) {
                $files[$key] = $this->filterFiles($files[$key]);
            }

            if (empty($files[$key])) {
                unset($files[$key]);
            }
        }

        return $files;
    }
```
> vendor/laravel/framework/src/Illuminate/Http/Request.php:878
> Invalid argument supplied for foreach()

incorrect work method duplicates in class Request 
```
/**
     * {@inheritdoc}
     */
    public function duplicate(array $query = null, array $request = null, array $attributes = null, array $cookies = null, array $files = null, array $server = null)
    {
        return parent::duplicate($query, $request, $attributes, $cookies, $this->filterFiles($files), $server);
    }
```

because variable $files  by default is null
I think that need  to change  input parameters on $files = []
or add checks to filterFiles file
 
### Steps To Reproduce:
if i used $request->instance()->duplicate() then i receive error 

> vendor/laravel/framework/src/Illuminate/Http/Request.php:878
> Invalid argument supplied for foreach()

**Comment by themsaid** [comment]
Interested to know why would you use `$request->instance()->duplicate()`?

**Comment by chamav** [comment]
I used batch-request  library for used union few api methods in one batch
https://packagist.org/packages/optimus/batch-request

https://github.com/esbenp/laravel-api-consumer/blob/master/src/Router.php
string 117
In my opinion, it is no mistake of library

**Comment by themsaid** [comment]
Yeah, submitted a fix. Thank you for the report :)

https://github.com/laravel/framework/pull/15558

**Comment by chamav** [comment]
Thank you very mach!
