### ISSUE TITLE
Illuminate\Http\Request fullUrl() does not preserve the original URL's order

### ISSUE THREAD

**Issue by chandrewz** [laravel/framework#15550]
- Laravel Version: 5.2.*
- PHP Version: 5.6.14
- Database Driver & Version:

### Description:

Using `Request`'s `fullUrl()` with an array in the parameter does not preserve the original URL. Looks like alphabetical ordering is taking place.

### Steps To Reproduce:

Add to routes.php:
```php
Route::get('test', function(Illuminate\Http\Request $request) {
	return $request->fullUrl();
});
```

Visit a URL:
```
http://localhost:8000/test?array[b][value1]=value1&array[b][value2]=val2&array[a][value3]=value3&array[a][value4]=value4
```

Array visualized (b is BEFORE a):
```
[
  b: [ value1: "value1", value2: "value2" ],
  a: [ value3: "value3", value4: "value4"]
]
```

Output in browser (note that array[a] came first):
```
http://localhost:8000/test?array%5Ba%5D%5Bvalue3%5D=value3&array%5Ba%5D%5Bvalue4%5D=value4&array%5Bb%5D%5Bvalue1%5D=value1&array%5Bb%5D%5Bvalue2%5D=val2
```

**Comment by GrahamCampbell** [comment]
That looks like the correct behaviour, yes.
