### ISSUE TITLE
paginate

### ISSUE THREAD

**Issue by pujilabkom** [laravel/framework#15568]
- Laravel Version: 5.2.45
- PHP Version: 7.0.2
- Database Driver & Version: mysql

### Description:
$users = \App\Users::paginate(10);
return $users->links();

result " "

**Comment by garygreen** [comment]
Obvious question, have you even got any users in the database? What does `\App\Users::all()` return?

**Comment by pujilabkom** [comment]
$users = \App\User::paginate(1);
return $users->links();

result : 
HtmlString {#180 ▼
  #html: "<ul class="pagination"><li class="disabled"><span>&laquo;</span></li> <li class="active"><span>1</span></li><li><a href="http://localhost:8000/user?page=2">2</a></li> <li><a href="http://localhost:8000/user?page=2" rel="next">&raquo;</a></li></ul>"
}


solved
