### ISSUE TITLE
Paginator prefixing urls with /

### ISSUE THREAD

**Issue by garygreen** [laravel/framework#15562]
The paginator is still prefixing urls with "/" when using the LengthAwarePaginator manually.

Steps to reproduce:

```php
$news = new Illuminate\Pagination\LengthAwarePaginator(['a', 'b', 'c'], 3, 1);
return $news->render();
```

Will render links like:

```html
<li><a href="/?page=1">1</a></li>
<li class="active"><span>2</span></li>
<li><a href="/?page=3">3</a></li>
```

If you did the same with eloquent `->paginate()` it wouldn't output links with `/?`

According to the docs this was fixed:

> Pagination
> To be consistent with other URLs generated by the framework, the paginator URLs no longer contain a trailing slash. This is unlikely to affect your application.
> Ref: https://laravel.com/docs/5.3/upgrade

😕

**Comment by themsaid** [comment]
You'll need to provide a path, e.g.:

```
$news = new Illuminate\Pagination\LengthAwarePaginator(['a', 'b', 'c'], 3, 1, null, [
    'path' => Paginator::resolveCurrentPath()
]);
```

Without a path the paginator will provide relative URIs with a `\` at the beginning.

**Comment by garygreen** [comment]
@themsaid that's not the way it should work according to the upgrade guide.

> To be consistent with other URLs generated by the framework, the paginator URLs no longer contain a trailing slash.

**Comment by themsaid** [comment]
I think the upgrade guide is referring to paginating a collection.

**Comment by garygreen** [comment]
You think? It seems inconsistent behaviour to me. Not sure why a collection should not output a trailing slash but everything else does.... ? 😕

**Comment by themsaid** [comment]
Did further investigation on the issue, to use the length aware paginator manually you'll have to provide a path, otherwise the links won't be correct for internal URLs.

**Comment by garygreen** [comment]
The paginate method uses [`resolveCurrentPath()`](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Eloquent/Builder.php#L484)

Imo if you don't supply a path to the paginator, it should always try and resolve through that method. That would remove the need to pass the `path` - and anyone who does want to supply a custom path they can. That keeps things consistent and makes more use of `resolveCurrentPath()`.

This line: 

https://github.com/laravel/framework/blob/5.3/src/Illuminate/Pagination/LengthAwarePaginator.php#L50

```
$this->path = $this->path != '/' ? rtrim($this->path, '/') : $this->path;
```

Should be:

```
$this->path = is_null($this->path) ? $this->resolveCurrentPath() : $this->path;
```

**Comment by garygreen** [comment]
Still not really fixed. Maybe these improvements should go into 5.4?

**Comment by themsaid** [comment]
Will look into making a new PR for 5.4 soon.

**Comment by garygreen** [comment]
Cheers buddy. 😄
