### ISSUE TITLE
Form::select multiple

### ISSUE THREAD

**Issue by Kirych** [laravel/framework#15577]
- Laravel Version: 4.2.*
- PHP Version: 5.6.12
- Database Driver & Version:

### Description:
Incorrect selection of selected options. Depends on options' values.

### Steps To Reproduce:
{{ Form::select('qwe[]', ['10' => '10', '10_11' => '10_11'], ['10_11'], ['multiple' => 'multiple']) }}

**Comment by themsaid** [comment]
Thank you, but unfortunately 4.2 is closed for bug fixes :)
