### ISSUE TITLE
[Request] Ability to eager load relationship counts

### ISSUE THREAD

**Issue by leewillis77** [laravel/framework#15573]
- Laravel Version: 5.3.10
- PHP Version: 7.0.10

### Description:
Currently, you can retrieve the count of related models without having to retrieve the models themselves using `withCount()`, e.g. for an article that is in multiple categories, you can do:

`$article = Article::withCount('categories')->find($articleId);`

However where you are auto-loading the article model from your route there is no way to specify that you'd like that count to be included in an eager loading manner, e.g.

_**routes/web.php**_
```
Route::get('/article/{article}', 'ArticleController@show');`
```

**_ArticleController.php_**
```
public function show(Article $article)
{
    // $article will not contain the categories_count and there is no way to
    // request that it should.
}
```

You can load the count in the controller

```
public function show(Article $article)
{
    $article = Article::withCount('categories')->find($article->id);
}
```

However, that causes the following queries to be run in the background:

```
// Original query caused by the type hinted model class on the controller callback.
select * from `articles` where `id` = 'e1eebb50-54b2-4b77-81d7-7301ecc65f8f' limit 1

// Query generated by the call to withCount()
select *, (select count(*) from `categories` where `categories`.`article_id` = `articles`.`id`) as `categories_count` from `articles` where `articles`.`id` = 'e1eebb50-54b2-4b77-81d7-7301ecc65f8f' limit 1
```

Note how the article details are being re-loaded by the second query (redundantly really). Any eager loaded relationships will also be re-queried compounding the issue. 

It would be good (within the framework) to be able to either: 

1. specify that the count of a relationship is eager loaded by default, and have the subselect added to the original query when the model is first loaded (suggestions: `protected $with = ['count.categories']` or `protected $with = ['count(categories)']` or similar
2. be able to access a count without having to retrieve the whole model (incl. eager loaded relationships) again (Suggestion: `$model->getCount('categories')`)

I think both of these have their place, and could be supported, although for my use case the former would definitely be the thing I'd want to use.

**Comment by leewillis77** [comment]
As an alternative suggestion for specifying eager loading of relationship counts - we could introduce a new model property, e.g.

```
protected $withCounts = ['categories'];
```

Might be nicer than "magic" interpretation of `count.categories` / `count(categories)` on the existing `$with` property.

**Comment by themsaid** [comment]
Sorry @leewillis77 but we don't look at requests in this repository's issues :) Here we have bug reports only.

For suggestions and feature requests please use the https://github.com/laravel/internals repo.

**Comment by leewillis77** [comment]
@themsaid No worries - I'd missed that note in the contributing doc. I'll head over there!
