### ISSUE TITLE
Artisan call make:controller wrong path

### ISSUE THREAD

**Issue by maki10** [laravel/framework#15570]
- Laravel Version: 5.3.10
- PHP Version: 5.6.20
- Database Driver & Version: redis

### Description:
Today I try to create App namespace under controllers.
Type in console `php artisan make:controller App\AppController` and get success message.

After I searching the controller I see that `AppController` is actually in `App` namespace in the same place where is Models not in `App\Http\Controllers\App\`.

`C:\git\app>php artisan make:controller App\Http\Controllers\App\AppController`
`Controller created successfully.`

`C:\git\app>php artisan make:controller App\Http\Controllers\App\App\AppController`
`Controller already exists!`

`C:\git\app>php artisan make:controller App\Http\Controllers\App\App\App\App\AppController`
`Controller already exists!`

The controllers Are in `App\Http\Controllers\AppController.php`
With `namespace App\Http\Controllers\App;`

**Comment by nammaianh** [comment]
Use should use double back-slash instead of single. Change `\` to `\\`

```
php artisan make:controller App\\AppController
```

**Comment by maki10** [comment]
@nammaianh  No, that doesn't work either...

**Comment by nammaianh** [comment]
Oh, sorry! Didn't see that you are using Windows

**Comment by nammaianh** [comment]
How about using double quote?
```
php artisan make:controller "App\AppController"
```

**Comment by maki10** [comment]
@nammaianh  Same, making the controller under `App` namespace

**Comment by nammaianh** [comment]
I think mr. Otwell wanna do this if the controller start with `App` namespace

**Comment by maki10** [comment]
I still think this is an issue because we know where are our controllers `Namespace` is.

**Comment by maki10** [comment]
@nammaianh you can see that wish path is `\Http\Controllers`  in this link [https://github.com/illuminate/routing/blob/master/Console/ControllerMakeCommand.php#L51](Code)

**Comment by srmklive** [comment]
@maki10 This is not an error with the framework itself. It is how you are creating your controllers. Also the code you referred in not path but actually namespace.

**Comment by maki10** [comment]
@srmklive +1 my bad,
@themsaid For your pull request still not working 'php artisan make:controller App\StoreController', but working with `php artisan make:controller App\Http\Controllers\App\AppController`

**Comment by maki10** [comment]
https://github.com/laravel/framework/pull/15575
Fixed in PR. In order to create controller under `App\Http\Controllers\` in folder and namespace `App`, must be provide full path to controller in my case `App\Http\Controllers\App\AppController`
