### ISSUE TITLE
[5.3] Eloquent : withCount() overrides the $columns on get()

### ISSUE THREAD

**Issue by shadoWalker89** [laravel/framework#15576]
- Laravel Version: 5.3.6
- PHP Version: 5.6.15
- Database Driver & Version: Mysql 5.6.31

### Description:
When using withCount() from eloquent Builder it ignores the $columns passed to the get() method and select all the columns.

### Steps To Reproduce:
````php
User::withCount('someRelation')->get(['id', 'name']);
```

**Comment by themsaid** [comment]
Ping @barryvdh

`withCount()` selects `*` on the parent query, it prevents any further column selection, is there a way around this?

**Comment by barryvdh** [comment]
That is what I mentioned in the PR as possible problem, which I don't have a nice solution for. We need to add a select, if we just add the new column, the default '*' gets ignored (which is more common). See replies from here: https://github.com/laravel/framework/pull/13414#issuecomment-217875410

I think it *should* work when you explicitly use a `select()` call before the count.

```php
User::select(['id', 'name'])->withCount('someRelation')->get();
```

**Comment by themsaid** [comment]
Yes it works this way. 
@shadoWalker89 Check the reply above.

**Comment by shadoWalker89** [comment]
Yes it works the way barryvdh said.
Maybe you could add the fix for this as 5.4 milestone ?

**Comment by barryvdh** [comment]
Or perhaps add this to a note to the withCount docs?

**Comment by Luis-Goncalves-Searchprof** [comment]
You could also use the "addSelect" instead of "select", that way you can put it after the "withCount".

`User::withCount('someRelation')->addSelect(['id', 'name'])->get();`

**Comment by clytras** [comment]
There should be a note regarding this. I spent over an hour trying to figure this out why `get([fields])` isn't working with `withCount`.

@Luis-Goncalves-Searchprof `addSelect` is not working after `withCount`.

**Comment by driesvints** [comment]
@clytras we're always welcoming PR's that improve the docs 👍

**Comment by clytras** [comment]
@driesvints I'm not aware of the Notes Markdown format that I sould use to add one in [Counting Related Models](https://github.com/laravel/docs/blob/8.x/eloquent-relationships.md#counting-related-models).

If you do, please provide it here and I will make a PR for this.

**Comment by rpmcmurphy** [comment]
$query->paginate() overrides the select() method and brings everything. Any way around for paginated results?
