### ISSUE TITLE
Touching Pivot records on sync method

### ISSUE THREAD

**Issue by dbilovd** [laravel/framework#15579]
- Laravel Version: 5.2

### Description:
Not a bug, just being curious. 

There doesn't seem to be a way to touch pivoted models when I use the sync() method.

```$user->roles()->sync([1, 2, 4]);```

I can do this with `attach` and `detach`

```$user->roles()->attach([4], true);```

or 

```$user->roles()->detach([], true);```

*NB:* I don't usually pass the second param because it is true by default

**Comment by themsaid** [comment]
@dbilovd  Do you mean touching the parent timestamp?

**Comment by dbilovd** [comment]
@themsaid I want to update the records in the pivot table (`users_roles`) in this case.

**Comment by themsaid** [comment]
Sorry I don't seem to be able to follow :)

`$user->roles()->sync([1, 2, 4]);` will give the user roles `1,2,3,4`.

`$user->roles()->attach(4);` will add role 4 to the user.

What are you trying to achieve other than this?

**Comment by dbilovd** [comment]
Yeah. If the user already have role 1, 2 and 5, it'll add 4 and delete 5. But unlike attach that'll update the timestamps of 1 and 2 (touch), sync doesn't, and it doesn't provide a way to do so.

**Comment by themsaid** [comment]
Well I guess that's how it should act, since 1 and 2 weren't updated the timestamps shouldn't be touched, no?

**Comment by dbilovd** [comment]
Ideally, yes. But in my situation, I want to keep the time of the last batch of changes. So at least the `updated_at` would be good.

**Comment by themsaid** [comment]
Oh I see, I guess that's not possible with sync then :) Sync only cares about making sure the ids you provide will remain in the DB and the rest is removed.

Not sure what your use case is exactly but I'd say go for a custom query.
