### ISSUE TITLE
Cache FileStore fails flush operation silently

### ISSUE THREAD

**Issue by aedart** [laravel/framework#15578]
- Laravel Version: 5.3.x
- PHP Version: >=5.6.9
- Database Driver & Version: N/A

### Description:
Whenever you flush your cache, using the `FileStore`, the `flush()` methods does not throw any exception nor error, if it is not possible to delete its created directories.

Usually this happens when the OS permissions are not in order. However, this can quickly become very hard to debug in situations where your application is in a production environment and there is no feedback, whatsoever, on what might had gone wrong.

### Steps To Reproduce:

a) Cache some data, using the `FileStore`.

b) Change permissions to read only on the directory where the cache is stored.

c) Flush the cache via the `flush()` method in `FileStore`

**Expected results**: Error or Exception thrown if `FileStore` is unable to perform the flush operation

**Actual results**: Nothing happens, the cache directory is still populated with the cached data

### Possible solution(s):

**Solution A**: The main reason why this is the case, is due to the `Filesystem`'s `delete()` and `deleteDirectory()` methods. Both of them suppress errors and warnings (using `@unlink` and `@rmdir`). The obvious choice is to ensure that both methods can fail. However, this will break backwards compatibility... 

**Solution B**: Both `delete()` and `deleteDirectory()` return a `bool` upon completion; if method has succeeded or not. The `flush()` method could be adapted to return that state. This will allow developers to program around the issue, in whatever way the see fit.
This does, however, require a change in the `Store` interface; `flush()` will change it's return type. All implemented cache stores will have to be adapted as well.

**Solution C**: The same as solution B, yet instead of returning a success state, the `flush()` could throw an exception if it has failed. 
The same consequences are true for this solution as for solution b.

Personally, I like solution C the most, as it gives the most feedback to a developer. Regardless of such, I do consider this to be a design flaw and hope that you will (at some point) come up with an acceptable solution.

In the meantime, I'm "forced" to create my own little custom `FileStore`, which does throw an exception.

**Comment by themsaid** [comment]
@aedart how about you open a PR with the proposed fix? It's time we discuss implementation now since we know about the problem already.

**Comment by aedart** [comment]
Hi @themsaid 

While I would certainly like to solve this problem, I'm not sure which solution would be accepted. Therefore, before I undertake anything, what solution is best suited for Laravel?

Furthermore, while I might be able to create a solution for the `FileStore`, depending upon the chosen solution, someone might have to adapt the other cache stores. E.g. if solution B is chosen, then all other stores must also respect such a change. With that in mind, how do wish for us to proceed?

**Comment by taylorotwell** [comment]
Both B and C are fine with me.

**Comment by aedart** [comment]
@taylorotwell I'll take a look at this as soon as time permits it. Most likely only in the weekend.

**Comment by GrahamCampbell** [comment]
Silent error sounds fine. We don't want cache to break the whole app.

**Comment by aedart** [comment]
@GrahamCampbell In that case, solution B.
