### ISSUE TITLE
[5.3] Limit in eager loading doesn't feel right

### ISSUE THREAD

**Issue by shadoWalker89** [laravel/framework#15585]
- Laravel Version: 5.3.6
- PHP Version:5.6.15
- Database Driver & Version:Mysql 5.6.31

I have this eloquent Query

```php
$themes = DataTheme::withCount('dataSets')
->with([
    'dataSets' => function ($query)
    {
        $query->limit(5);
    }
])
->orderBy('data_sets_count', 'desc')
->get();
```

The `dataSets` on the DataTheme model is belongsToMany()

This is how i understand the eloquent query

Select all data themes
Select the total count of data sets related to each data theme
**For each** data theme select only 5 data sets

And this is the generated sql

```sql
SELECT 
  *,
  (SELECT 
    COUNT(*) 
  FROM
    `data_sets` 
    INNER JOIN `data_set_data_theme` 
      ON `data_sets`.`id` = `data_set_data_theme`.`data_set_id` 
  WHERE `data_set_data_theme`.`data_theme_id` = `data_themes`.`id`) AS `data_sets_count` 
FROM
  `data_themes` 
ORDER BY `data_sets_count` DESC;

SELECT 
  `data_sets`.*,
  `data_set_data_theme`.`data_theme_id` AS `pivot_data_theme_id`,
  `data_set_data_theme`.`data_set_id` AS `pivot_data_set_id` 
FROM
  `data_sets` 
  INNER JOIN `data_set_data_theme` 
    ON `data_sets`.`id` = `data_set_data_theme`.`data_set_id` 
WHERE `data_set_data_theme`.`data_theme_id` IN ('1', '2', '3', '4') 
LIMIT 5 
```

As you can see the Explenation that i provided doesn't match the sql code.

The sql is just selecting 5 datasets and not 5 datasets for each data theme

Is my explenation of the Eloquent query correct ?

**Comment by GrahamCampbell** [comment]
Looks correct. It's just not possible to limit in the way that you want. This has come up before I think.
