### ISSUE TITLE
Sum aggregate query return null instead of 0

### ISSUE THREAD

**Issue by binita-engg89** [laravel/framework#15587]
- Laravel Version: 5.2.0
- PHP Version:5.6.4
- Database Driver & Version:
"jenssegers/mongodb": "^2.2"
### Description:
$qty= $this->makeModel()
           ->where('type', '1')
            ->sum('qty');

returns $qty = null in 5.2 

and return 0 in 5.1  please tell how to solve this issue.

I want 0 in value

**Comment by themsaid** [comment]
That's a known issue in 5.2 but it was fixed in 5.3, you can cast it to integer or double to get the same result.

**Comment by binita-engg89** [comment]
@themsaid i have already casted qty to double but same result

**Comment by themsaid** [comment]
`(double) null == 0.0` Same result how?

**Comment by binita-engg89** [comment]
@themsaid not that way i had casted in model double..that way i m getting..I am using many time i don't want to change everywhere

**Comment by themsaid** [comment]
The thing is 5.2 is technically closed for fixes, are you willing to upgrade to 5.3 ?

**Comment by binita-engg89** [comment]
@themsaid ok will update 5.3

**Comment by themsaid** [comment]
Thanks, or at least upgrade to 5.2 latest, `5.2.0` is too out of date :)

**Comment by binita-engg89** [comment]
@themsaid ok sure..
