### ISSUE TITLE
getting error when trying to table->json('options') in migration

### ISSUE THREAD

**Issue by nermion** [laravel/framework#15581]
- Laravel Version: 5.3.9
- PHP Version: 7.0.9 
- Database Driver & Version: 10.1.16-MariaDB

### Description:
My migration looks like this
```
    Schema::create('reports', function (Blueprint $table) {
        $table->bigincrements('id');
        $table->json('options');
    });
```
I get this error:

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax;
check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null) default character set utf8 collate utf8_unicode_ci' at line 1

If I remove $table->json('options'); no errors. Laravel 5.3 documentation mentions this https://laravel.com/docs/5.3/migrations so I am not doing anything wrong, any ideas why I am getting this error?

I am using MariaDB version 10.1.16 which has support for json type.

**Comment by themsaid** [comment]
I think there's no `JSON` type in MariaDB.

**Comment by nermion** [comment]
https://mariadb.com/kb/en/mariadb/column_json/

COLUMN_JSON was introduced in MariaDB 10.0.1

**Comment by themsaid** [comment]
Does the sql query generated by laravel has wrong syntax? Can you please share the full query from the exception you get?

**Comment by themsaid** [comment]
It looks like `COLUMN_JSON ` is a function not a column type, I don't use MariaDB myself but I know laravel JSON column features doesn't work there cause there's no support.

**Comment by nermion** [comment]
MariaDB is default database driver on Forge, so I thought it would work with json and also since documentation doesn't mention it doesn't work with MariaDB.

**Comment by nermion** [comment]
How can I intercept sql query generated by running migrations?

**Comment by themsaid** [comment]
The only two drivers currently with JSON support are Postgres and MySQL.

**Comment by benyanke** [comment]
MariaDB allows you to run json functions on varchar strings. Why not set json => col type of varchar for mariadb?
