### ISSUE TITLE
[5.3] Blade and vuejs problem

### ISSUE THREAD

**Issue by shadoWalker89** [laravel/framework#15583]
- Laravel Version: 5.3.6
- PHP Version: 5.6.15

### Description:
With vue js we do @{{ }} to tell laravel to ignore that block but the problem occurs when we do

```blade
@{{ someJsMethod( {{ $somePhpVar}} ) }}
```
The following will output `) }}`

So i tried using regular php tags inside @{{ }} like this

```blade
@{{ someJsMethod( <?= $somePhpVar ?> ) }}
```
Saying that the `someJsMethod` will return the value `21`

The output that i got was `@21`

**Comment by themsaid** [comment]
`@{{ someJsMethod( <?= $somePhpVar ?> ) }}` should return `@{{ someJsMethod( 123 ) }}` in the final markup.

Please share the different result you got.

**Comment by GrahamCampbell** [comment]
Yeh, blade will likely have trouble matching nested brackets since it used regular expressions, which by definition can only match regular languages.

**Comment by shadoWalker89** [comment]
@themsaid 

`@{{ someJsMethod( <?= $somePhpVar ?> ) }}` should return `{{ someJsMethod( 123 ) }}` in the final markup (page source code) but when using <?= ?> inside of @{{ }} it returns `@{{ someJsMethod( 123 ) }}`

**Comment by themsaid** [comment]
@shadoWalker89 yeah right, that's weird.

**Comment by ctf0** [comment]
@shadoWalker89 a wild guess , try
```
<?= @{{ someJsMethod( <?= $somePhpVar ?> ) }} ?>
```

**Comment by shadoWalker89** [comment]
@ctf0 That will result in a php error, because the code within the first <?= ?> isn't a valid php code

For now i'm putting my code within `@verbatim`

**Comment by themsaid** [comment]
Yeah that looks like a nofix situation here, the php tags inside the statement prevents blade from reading it as a valid blade statement so it's printed in the view as is.

`@verbatim` is a good solution in this case.

**Comment by deantawonezvi** [comment]
`@verbatim` is not working for me when using AngularJS. Any help with this is.
