### ISSUE TITLE
Route is overridden even when name is different

### ISSUE THREAD

**Issue by simplenotezy** [laravel/framework#15586]
- Laravel Version: 5.2.0
- PHP Version: 7.0

### Description & Steps To Reproduce::
If I have two routes:

	Route::get('/', ['as' => 'something', function () {

	}]);

	Route::get('/', ['as' => 'something-else', function () {

	}]); // this is overriden by the first route

One will overwrite the other, even though it has a different `as` property.

**Comment by themsaid** [comment]
Why would you define 1 route twice with two different names?
