### ISSUE TITLE
Store procedure stopped working with DB facade

### ISSUE THREAD

**Issue by tamaghna91** [laravel/framework#15590]
- Laravel Version: 5.2.44
- PHP Version: > 5.5
- Database Driver & Version: mysql 5.5.30

### Description:
I have tried to access data through my remote database through calling a **store procedure**, I have tried to use laravel's db facade using select query to call like this way - 

```
$batch_code =  (string) DB::table('batches as b')->where('b.id',$batch_id)->value('batch_code');
$sql = 'CALL fetch_valid_student("'.$batch_code.'")';
$get_students_list = DB::select($sql);
```

The above trying return empty array while if try in this way it gives me the result in array -

```
$batch_code =  (string) DB::table('batches as b')->where('b.id',$batch_id)->value('batch_code');
$pdo = new \PDO("mysql:host=XX-YY-XX;dbname=XXXX", "YY-XX", "PP-QQ");
$sql = 'CALL fetch_valid_student("'.$batch_code.'")';
$q = $pdo->query($sql);
$q->setFetchMode(\PDO::FETCH_ASSOC);
$get_students_list = $q->fetchAll();
```

### Steps To Reproduce:
The problem is not understood why the default PDO not returning result, someone's suggestion could help me endeavor.

**Comment by themsaid** [comment]
Couldn't replicate the issue in 5.2 or 5.3 using MySQL 5.7

Can you please check the query log and see what query is being executed while running `DB::select()`?

**Comment by themsaid** [comment]
ping @tamaghna91

**Comment by themsaid** [comment]
Closing for being unable to replicate and lack of activity. Please feel free to ping me if you ever found the exact problem.
