### ISSUE TITLE
Eloquent - set connection name 'statically' during runtime

### ISSUE THREAD

**Issue by kevindierkx** [laravel/framework#15597]
- Laravel Version: 5.x

### Description:
Most 3th party components, like laravel/passport, depend on the default connection set in the `database.php` config. In some cases you don't want these models to connect to default database: for example you might have 2 applications sharing 1 database connection and having their own dedicated database for their specific logic set as default.
It would be helpful in these cases to change the default connection 'statically'.
~~Most of the time these components don't come with custom logic to set the connection name and the only option left is to override all the provided models.~~

It would be a welcome addition if we could set the connection name `statically` on the model. This way we can use a simple oneliner to change the connection instead of using the default connection.

edit: I'm aware that the Eloquent model has a `setConnection` method. This doesn't resolve my use case where I wan't to set the connection name `statically` instead.

**Comment by kevindierkx** [comment]
After some tinkering I came up with the following:
```PHP
// In some kind of service provider

/**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        $connection = $this->app['db']->connection('api');

        $resolver = new ConnectionResolver;
        $resolver->addConnection('api', $connection);
        $resolver->setDefaultConnection('api');

        AuthCode::setConnectionResolver($resolver);
        Client::setConnectionResolver($resolver);
        PersonalAccessClient::setConnectionResolver($resolver);
        Token::setConnectionResolver($resolver);
    }
```

This works, but it seems a bit over complicated. I'll leave this issue open for some suggestions.

**Comment by GrahamCampbell** [comment]
Please ask on the forums.

**Comment by kevindierkx** [comment]
Yeah thought about it. making `$connection` static will also break it for other models depending on the default connection...
