### ISSUE TITLE
Custom User Provider + Authorization gates broken after upgrade

### ISSUE THREAD

**Issue by ligne13** [laravel/framework#15607]
- Laravel Version: 5.3.10
- PHP Version: 7.0.10
- Database Driver & Version: MySQL 5.6.28

### Description:
I just upgraded to 5.3 and do not understand why my Gate::allows always return false now.
I'm using a Custom User Provider for my Authenticationn which is working fine for my login/logout requests.
The code below was working with 5.2.

File: app/Providers/AuthServiceProvider.php

```
<?php

namespace App\Providers;

use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use App\Classes\CustomUserProvider;

class AuthServiceProvider extends ServiceProvider
{
    /**
     * The policy mappings for the application.
     *
     * @var array
     */
    protected $policies = [
        'App\Model' => 'App\Policies\ModelPolicy',
    ];

    /**
     * Register any application authentication / authorization services.
     *
     * @param \Illuminate\Contracts\Auth\Access\Gate $gate
     */
    public function boot()
    {
        $this->registerPolicies();

        Auth::provider('custom', function ($app) {
            $model = $app['config']['auth.providers.users.model'];
            return new CustomUserProvider($this->app['hash'], $model);
        });

        Gate::define('mySpecialAbility', function ($user) {
            return $user->superadmin == 1;
        });
    }
}
```

In my controller:

```
function __construct()
    {
        if (Gate::denies('mySpecialAbility')) {
            // always true ! even if the user has superadmin = 1
            abort(403, 'Access denied');
        }
}
```

thanks

**Comment by MladenJanjetovic** [comment]
Take a look at this one. Probably the default guard issue
https://github.com/laravel/framework/issues/13788

**Comment by ligne13** [comment]
Thanks @MladenJanjetovic but my default guard is 'web' (with my custom provider). I tried the solution given in #13788 (added `Auth::shouldUse('web');` in my app/Providers/AuthServiceProvider.php) but it doesn't work.

**Comment by ligne13** [comment]
I've compared the 5.2 and 5.3 backtrace and the issue seems to come from the Gate->resolveUser method, which signature is:

```
protected function resolveUser()
{
    return call_user_func($this->userResolver);
}
```

In 5.2 the method returns my User model instance, in 5.3 the method returns null.

**Comment by MladenJanjetovic** [comment]
And in Gate::define() the $user object exists?

**Comment by MladenJanjetovic** [comment]
Oh, just saw it, sorry. 

Well that is the issue, userResolver is using guard which is defined with shouldUse().
And it's called multiple times so I couldn't figure out how to get right current guard there.

But didn't try that with custom provider

**Comment by ligne13** [comment]
Actually, the Gate::define() method doesn't seem to be called at all... I tried by adding dd($user) in the callback and nothing is printed and the script goes on.

**Comment by ligne13** [comment]
Very weird. I recreated a Custom User Provider authentication in a fresh Laravel 5.3 installation, with a Gate defined in AuthServiceProvider and it works.

In my upgraded App, after digging a little more in the framework, I found that as soon as I define a Gate and check it in my controller, the session->attributes is null in Illuminate/Auth/SessionGuard (see the attributes array : it's empty) :
```
Store {#354 ▼
  #id: "xq8lrvlrI1cZuYcjdkbiPZfP0CsmjLsL9GwyUeTw"
  #name: "laravel_session"
  #attributes: []
  #bags: []
  #metaBag: MetadataBag {#355 ...}
  #bagData: []
  #handler: FileSessionHandler {#353 ...}
  #started: false
}
```

whereas in my fresh 5.3 app, the attributes property is ok :
```
Store {#160 ▼
  #id: "vzRPwoFuHnKzTRzSbKT3E89qiPUDIve50maRJPFj"
  #name: "laravel_session"
  #attributes: array:4 [▼
    "_token" => "B5LyL1gOfwlUZtiQu3ajnx1gisvL3dcIZzNRGsop"
    "_previous" => array:1 [▶]
    "_flash" => array:2 [▶]
    "login_web_59ba36addc2b2f9401580f014c7f58ea4e30989d" => 1
  ]
  #bags: []
  #metaBag: MetadataBag {#153 ▶}
  #bagData: array:1 [▶]
  #handler: FileSessionHandler {#161 ▶}
  #started: true
}
```

Any idea why my auth session is empty in that specific case ?? Also, it's not empty in controllers in which I don't check a Gate against.

**Comment by ligne13** [comment]
OK, this is because Laravel 5.3 does not allow access to session variables or authenticated user in the constructor of a controller (see https://laravel.com/docs/5.3/upgrade#upgrade-5.3.0, paragraph Controllers > Session In The Constructor).
In my fresh app, that was working because I was checking my Gate ability in the index method of the controller.
