### ISSUE TITLE
migration issue

### ISSUE THREAD

**Issue by mastermind23** [laravel/framework#15606]
- Laravel Version: 5.3
- PHP Version: 7
- Database Driver & Version: 5.7.14

### Description:
well i created a migration and deleted it, then wasn't able to create migration with same name, it throws error
```
C:\wamp64\www\RR>php artisan make:migration accounts


  [ErrorException]
  include(C:\wamp64\www\RR\vendor\composer/../../database/migrations/2016_09_26_092715_accounts.php): failed to open stream: No such file or directory
```

what i dont understand is why is it moving to \vendor\composer/../../database/migrations/ folder ? as i never had same issue in laravel 5.2 and i have repeated this test over and over again both in 5.2 and 5.3 with 5.2 never giving any problems whatsoever, and 5.3 still stuck with the same issue

### Steps To Reproduce:
`php artisan make:migration test`

delete the migration manually, 
then create same migration again

`php artisan make:migration test`

**Comment by mastermind23** [comment]
funny thing,

`composer update`

solves the thing, but for one time, if i delete that migration and create again same issue.

**Comment by srmklive** [comment]
This is not an error.

**Comment by themsaid** [comment]
You need to run `composer dump-autoload` if you delete a migration.
