### ISSUE TITLE
[5.3] dont flat array validation error to one level

### ISSUE THREAD

**Issue by ctf0** [laravel/framework#15604]
- Laravel Version: 5.3.10
- PHP Version: 7.0.9
- Database Driver & Version: NaN

### Description:
atm the array validation will only show one error msg which is bad & wrong, because it doesnt tell what EXACTLY is wrong with the uploaded files,
so now the user will try again to upload the same set of files and will again get the same error but instead, the user should get which file name had an issue and what was the cause of the issue.

### Example
lets say the user should upload images so the rule will be `'image' => 'required|image|max:2048'` , now imagine the user uploaded 3 files

> 1- anything else than an image `abc.txt`
2- an `x.jpg` with size < 2048kb
3- an `xx.jpg` with size > 2048kb

now instead of the user getting something vague like `The image must be an image.` , he should get
> 1- 'abc.txt' have to be an image
2- `xx.jpg` size should be less than 2048kb

now the user understand exactly what went wrong and will help save his sanity.

### Steps To Reproduce:

- route
```php
Route::post('/', [
    'as'   => 'store.files',
    'uses' => 'StoreController@store',
]);
```
- controller
```php
public function store(Request $request)
{
    $this->validate($request, [
        'image' => 'required|image|max:2048',
    ]);

    foreach ($request->image as $one) {
        $one->store('images', 'public');
    }

    return url('/')->with('success', 'done');
}
```

- form
```blade
{{ Form::open(['route' => 'store.files', 'method' => 'POST', 'files'=>true]) }}
    {{ Form::file('image[]',['multiple']) }}
    <hr>
    {{ Form::submit('submit', ['class'=>'btn btn-success']) }}
{{ Form::close() }}

@if (isset($errors))
    <ul>
        @foreach ($errors->all() as $one)
            <li>{{ $one }}</li>
        @endforeach
    </ul>
    {{ dd($errors->all()) }}
@endif
```

**Comment by themsaid** [comment]
Feel free to open a PR with the proposed changes. This isn't actually a bug report. But thank you for the suggestion :)

**Comment by ctf0** [comment]
@themsaid u mean this is made on purpose ?

**Comment by themsaid** [comment]
Nope it's just that how validation works currently, if you have a change to suggest you can open a PR or you can discuss it further on the internals repository.

For suggestions and feature requests please use the https://github.com/laravel/internals repo.

**Comment by ctf0** [comment]
okay, one last req, can u just give me a link or the file name to where i should make the changes ?

**Comment by themsaid** [comment]
I think that goes into Illuminate\Validation\Validator

**Comment by ctf0** [comment]
okay thanx
