### ISSUE TITLE
Impossible to listen console command event(console.command)

### ISSUE THREAD

**Issue by mcklayin** [laravel/framework#15610]
- Laravel Version: 5.2.* & 5.3.*
- PHP Version: 5.6
- Database Driver & Version: mysql

### Description:
I'm trying to listen console commands, subscibed to console.command event, but it doesn't fired.

### Steps To Reproduce:

1. Create some commands, register it
2. Register custom event listener in EventServiceProvider. 
For example:
```
$events->listen('console.command', function ($data) {
            \Log::info('[event] ' . $data->getName());
        });
```
3. Run command  with console.
4. Check laravel.log, and it will not containes "[event]" string.

P.S. Problem in \Symphony\Component\Console\Application\doRunCommand(),  where `$dispatcher is null`

**Comment by themsaid** [comment]
Yes you can't listen to Symfony's console events from within laravel.

You may listen to the `Illuminate\Console\Events` event which is fired while initialising the console application, would that do the trick for you?

**Comment by mcklayin** [comment]
@themsaid I need to get command name which was executed.
With listening` Illuminate\Console\Events\ArtisanStarting` i can listen every command executing, but i cant't get command name. Is it possible?

**Comment by themsaid** [comment]
I doubt that it's possible now, I've opened a PR proposing an event to get fired before running console commands: https://github.com/laravel/framework/pull/15613

**Comment by joelharkes** [comment]
any news on this in 2021?

**Comment by mcklayin** [comment]
@joelharkes It was added here [#20298](https://github.com/laravel/framework/pull/20298/files)

**Comment by joelharkes** [comment]
Thanks, but was still not what I was looking for. I want an instance of command class in the event, that only happens in the symfony events.

**Comment by IlliaBalia** [comment]
@joelharkes Had the same issue, solved by using `Artisan::all()`: it returns an array of all commands with names being keys and instances being values
