### ISSUE TITLE
[5.1] queue:listen no longer logs exceptions

### ISSUE THREAD

**Issue by lukewaite** [laravel/framework#15612]
- Laravel Version: 5.1.44
- PHP Version: 7.0.10
- Database Driver & Version: mysql 5.6

### Description:
Running `artisan queue:listen` without `--daemon` no longer logs exceptions.

### Steps To Reproduce:
* Create a failing job, throw any old `\Exception` inside the `handle()`
* Push your job to a non-sync queue, run the job with `artisan queue:listen`
Expected: `laravel.log` should log your exception
Actual: Nothing is logged
* if you have a `Queue::failing()` that logs in your `AppServiceProvider`, that log shows up, if you have `--tries=x` set.

### Thoughts
This seems to have been introduced by: https://github.com/laravel/framework/commit/5858edc5a776760b51e8cac1cc2759d7fd34d1ff. The `poll()` method now adds it's own `try/catch` which is catching the exception, rather than the `try/catch` in `\Illuminate\Foundation\Console\Kernel::handle()`.

The issue is that the new `poll()` `try/catch` will only log exceptions if `$this->exception` is set. When the `Worker::poll()` is run, the only time it is provided an exception handler is if the user has passed `--daemon` to the `queue:listen` command:
https://github.com/laravel/framework/blob/5.1/src/Illuminate/Queue/Console/WorkCommand.php#L96-L98

The fix should be quite simple, passing the exception handler in regardless of `--daemon`, but I'm not sure if there is another reason that this was previously not provided if not in `--daemon` that I could be overlooking.

**Comment by themsaid** [comment]
Hello @michaeldyrynda :)

Do you think your PR https://github.com/laravel/framework/pull/15167 might have caused the behaviour stated in this issue?

**Comment by lukewaite** [comment]
Updated the issue to properly reflect that the error occurs on `artisan queue:listen`. I had made multiple references to `artisan queue:work` incorrectly.

**Comment by michaeldyrynda** [comment]
Hey @themsaid, yeah, that'd be me.

As per the PR, the fact an exception fell through the excecution at all is probably broken behaviour, given that it causes retries to never be fired.

I'm not sure why the exception handler isn't passed in (or if it is in 5.2 when the `try`/`catch` was added), but I agree it's probably the simplest way to resolve, though I'm not sure if/why this was omitted.

**Comment by themsaid** [comment]
@michaeldyrynda is it possible that you give it a shot and attempt to introduce a fix?

**Comment by wyred** [comment]
Is there any temp fix I can do for this? I'm trying to troubleshoot a problem and it's very difficult without any error logs.

**Comment by lukewaite** [comment]
@wyred I reverted to 5.1.43, as it does not suffer from this issue.

**Comment by taylorotwell** [comment]
We should just pass the exception handler in all the time.

**Comment by taylorotwell** [comment]
I've tagged 5.1.45 to address this. Can you confirm that fixes your problem?

**Comment by lukewaite** [comment]
@taylorotwell `5.1.45` resolves this issue. Thanks!! 👍
