### ISSUE TITLE
Cannot initialize variable within custom directive

### ISSUE THREAD

**Issue by serg6854** [laravel/framework#15611]
- Laravel Version: 5.3.6
- PHP Version:  7.0.8

### Description:
I want to initialize variable within my custom directive.

### Steps To Reproduce:
For example, code:
```
Blade::directive('text', function ($name) {
    return "<?php $customVariable = 1; ?>";
});
```
Throws an exception: 

> ErrorException in AppServiceProvider.php: Undefined variable: customVariable

**Comment by themsaid** [comment]
@serg6854 Use single quotes.
