### ISSUE TITLE
User authenticating but not staying logged in 5.3

### ISSUE THREAD

**Issue by dericcain** [laravel/framework#15621]
- Laravel Version: 5.3.9
- PHP Version: 7.0.8
- Database Driver & Version:
MySQL Ver 14.14 Distrib 5.7.15
- Redis

### Description:
I am using the Laravel `auth:make` scaffolding and when I login I am redirected to the correct page, but when I try to navigate to another page, I am redirected to login. I take a look at the debugbar and for the `web` routes auth, it says that I am logged in as a guest.

I created a route at `test-login` that has this code:

```php
Auth::attempt(['email' => 'deric@tvstuff.com', 'password' => 'password']);
```

and I am logged in. For some reason, the session doesn't seem to be persisting.

### Steps To Reproduce:
1. Login from the `/login` path
2. I am redirected to the correct page upon successful login
3. I try and navigate to another page
4. I am redirected back to login

**Comment by themsaid** [comment]
Is it a fresh installation? are you using redis as a session driver?

**Comment by dericcain** [comment]
This is not a fresh installation. I am using Redis as the session driver. I have switched the session back to `file` and that did not seem to help.

**Comment by themsaid** [comment]
Was it always the case or did you only notice this behaviour recently? after an upgrade maybe? Changing some settings? ...

**Comment by dericcain** [comment]
I installed Redis and got that up and running, but the auth seemed to be working after that. I noticed that it wasn't working when I tried to create a logout link by using `Auth::logout()` and got a method not allowed exception when trying to log out. Maybe that has something to do with it?

**Comment by themsaid** [comment]
Not sure I follow, how did you fix the issue again please? :)

**Comment by dericcain** [comment]
@themsaid Sorry for the confusion but I have not resolved the issue. I was explaining that I did make some changes and that is when I started noticing the issue, but I cannot pinpoint exactly where the issue resides. I know that it was working after I installed Redis but now it is not working and I do not know why. 

I can look at the session and see that tokens are persisting but the user is not staying logged in. Do you have any other things that I can check to narrow it down?

**Comment by themsaid** [comment]
I reopened the issue although I'm not able to replicate the problem, most likely it's a configuration issue at your end. Maybe related to session lifetime.

Anyway will keep the issue open for a while and see if anyone is having the same issue; however, please ping me if you ever managed to solve the issue or knew what's wrong :)

**Comment by dericcain** [comment]
@themsaid I just installed a fresh copy of Laravel and moved my edited files over to it and it is doing the same thing. I uninstalled `predis/predis`, just in case that was the issue, and changed my session driver back to `file` and that did not solve the issue.

**Comment by themsaid** [comment]
What edited files are you referring to? config files? Can you push the test project on GH so that I can take a look?

**Comment by dericcain** [comment]
@themsaid I just added you to the repo as a collaborator. I really appreciate your help with this.

**Comment by themsaid** [comment]
Thank you but I can't test on a full application :) I need you to test using a fresh laravel installation using the default Auth files, if it works on a laravel fresh installation (which is the case on my end) then it's not an issue with laravel thus I suggest you check on the forums.

Using a fresh laravel application I'm unable to replicate this issue, if you do then maybe it's a n issue with PHP at your end.

**Comment by dericcain** [comment]
@themsaid I finally found it... Dumb mistake on my part. For the logout link in my nav partial, I had

`{{ Auth::logout() }}`

Which logged me out since every page included the nav partial.

**Comment by themsaid** [comment]
:D Who said our job isn't funny!

**Comment by tomsihap** [comment]
Fresh install too, didn't succeed to find the problem. I've had the same mistake: href='{{Auth::logout()}}' instead of {{route('logout')}} !

**Comment by ehben83** [comment]
Same mistake too LOL.

**Comment by Konrad29** [comment]
Me too... i swear the god, I almost lost my mind..
