### ISSUE TITLE
Validator->errors()->add('field', 'message') scoping?

### ISSUE THREAD

**Issue by four-eyes-04-04** [laravel/framework#15628]
- Laravel Version: 5.3.10
- PHP Version: 5.6.19
- Database Driver & Version: mysql mariaDB 10.1.10

### Description:
I have a controller that handles Route::post, this controller will do an input validation using **Illuminate\Support\Facades\Validator**. Now I set all the rules and threw the errors to a view via **Redirect()->to('some/path')->withErrors($validator)->withInput($inputs)**. Now I needed to make sure that two fields combined together does not exists on two columns combined together from a database table.

table: test
columns
- title
- subtitle

I must make sure that the title+subtitle inputs does not exists on the title+subtitle columns. So I created an if statement for that and also taking into consideration that  the subtitle is an optional field. If the condition is met I will need to add a new error message along with other existing error messages from the validator::make so from the variable holding that validator instance I will do a **$validator->errors()->add('title', input['title'] . ' ' . input['subtitle'] . ' already exists.');** this wil work ONLY INSIDE THE IF STATEMENT but outside of it this error doesn't seem to exists so if I do:

if (condition) {
  $validator->errors()->add('field', 'error message');
  /*
   * outputs all the errors with the recently added ERROR MESSAGE
  */
  print_r($validator->errors()->all());
}

/*
 * outputs all the errors WITHOUT the recently added ERROR MESSAGE
*/
print_r($validator->errors()->all());

### to get around it

if (condition) {
  $validator->errors()->add('field', 'error message');
  /*
   * outputs all the errors with the recently added ERROR MESSAGE
  */
  $errors = $validator->errors()->all();
}

return Redirect()->to('path')->withErrors($errors)->withInput($inputs);

This will work! but I believe that I don't have to get around this and this should not happen all the errors I added should be accessible later on after I added them.

### Steps To Reproduce:
create a controller that handles post form inputs.
create a variable to handle user input with Input::all()
create a variable that will handle validation rules
do a Validator::make(inputs, rules) and assign it to a variable
make a custom error check with if statement
do a $validator->errors()->add('myField', 'error message') if the condition was met

**You don't need to throw it to a view simply do**
display all errors via $validator->errors()->all() INSIDE THE IF STATEMENT'S BODY using print_r
display all errors via $validator->errors()->all() OUTSIDE THE IF STATEMENT'S BODY using print_r
just return nothing.

**Comment by themsaid** [comment]
@four-eyes-04-04 I'm sorry but I don't seem to understand your issue.

When you do `$validator->errors()->add('field', 'error message');` what do you expect? and what do you get that's different from what you expect?

**Comment by themsaid** [comment]
Please format the code snippets to make them readable https://guides.github.com/features/mastering-markdown/

**Comment by themsaid** [comment]
> this wil work ONLY INSIDE THE IF STATEMENT but outside of it this error doesn't seem to exists

PHP doesn't work like this, there's no scope change inside an if statement, looks like for some reason the condition is false and the message isn't added.

**Comment by four-eyes-04-04** [comment]
> When you do $validator->errors()->add('field', 'error message'); what do you expect? and what do you get that's different from what you expect?

I am expecting that `$validator->errors()->add('field', 'error message')` would add a new error message to the validator instance.

I am also expecting that `$validator->fails()` would return true if the and error is present and that should include the errors I added via `$validator->errors()->add()`.

I am also expecting that `$validator->errors()->all()` would return all the errors **including the error I added via** `$validator->errors()->add()` **but it doesn't**

> PHP doesn't work like this, there's no scope change inside an if statement, looks like for some reason the condition is false and the message isn't added.

I know and I don't need to be reminded, did you managed to replicate the scenario?

**Comment by themsaid** [comment]
@four-eyes-04-04 but you say it works when you're inside the condition, right?

**Comment by joshi1983** [comment]
Was this closed due to a misunderstanding of the question?  

I'm facing the same problem where validator->errors()->add isn't causing the mutation that I want.  I expected the same as @aprilmintacpineda's last comment but found the same results as he mentioned.  It looks like Laravel's Validator class doesn't work that way so I'll have to do some nasty workaround.
