### ISSUE TITLE
Bulk Mail and Queue

### ISSUE THREAD

**Issue by ozldmezot** [laravel/framework#15631]
Would be nice having a batch queue option for Mailer and therefore Queue Drivers

In Database driven Queue's this option would allow to optimize job insert queries from multiple inserts to one, in cases where each recipient is to receive different data (therefore bcc and cc is not possible)

Example of problem at hand (results in n database inserts):
```php
foreach ($recipients as $recipient) {

    Mail::queue('example_view', [ 'addressable' => $recipient->name ], function ($message) use ($recipient) {
        $message->to($recipient->email, $recipient->name)->subject('Example Topic');
    });
}
```
Would prefer something similar to this (which would perform 1 bulk insert query):
```php
$batch = [];
foreach ($recipients as $recipient) {

    $batch[] = [
        'view' => 'example_view',
        'data' => [ 'addressable' => $recipient->name ],
        'callback' => function($message)  use ($recipient) {
            $message->to($recipient->email, $recipient->name)->subject('Example Topic');
        }
    ];
    
}

Mail::queueBatch($batch);
```

**Comment by themsaid** [comment]
@ozldmezot please submit only bug reports to this repository. 
For suggestions and feature requests please use the https://github.com/laravel/internals repo.

Thank you :)
