### ISSUE TITLE
Set model relation on the fly before serialization

### ISSUE THREAD

**Issue by thibaultlavoisey** [laravel/framework#15632]
- Laravel Version: 5.2.41
- PHP Version: 7.0.11
- Database Driver & Version: MariaDB 10.1.17

### Description:

I filter a model relation before returning the model as an array:

```
dump(count($group->events)); // return 1

$group->events = $group->events->reject(function ($event) {
    if (...) {
        return true; 
    }
});

dump(count($group->events)); // return 0

return $group->toArray();
```

I expect the model to be serialized with an empty `events` attribute. However the rejected models are contained in the `events` attribute. 

I fixed this behavior by calling the `setRelation` method before returning the model:

```
$group->setRelation('events', $group->events);
```

Is this the right behavior?

### Steps To Reproduce:

Update a model relation and serialize it.

**Comment by GrahamCampbell** [comment]
Yeh, serializing a model just stores it's id and none of it's state.

**Comment by thibaultlavoisey** [comment]
Tx @GrahamCampbell!
