### ISSUE TITLE
String format change after using json_encode function

### ISSUE THREAD

**Issue by whfamily2006** [laravel/framework#15644]
- Laravel Version: 5.3.9
- PHP Version: 5.6.24
- Database Driver & Version: Mysql

### Steps To Reproduce:
$date = '05/24/1986';
echo 'Date: ' . json_encode($date, JSON_PRETTY_PRINT);

Printed:  05\/24\/1986

**Comment by themsaid** [comment]
That's not laravel related :) Please ask on stackoverflow
