### ISSUE TITLE
[5.3] numeric validation fails on localized float

### ISSUE THREAD

**Issue by mroedel** [laravel/framework#15643]
- Laravel Version: 5.*
- PHP Version: 5.6.23
- Database Driver & Version: NaN

### Description:
The validation takes no regard for the localization of numeric values.
The error occurs on updating models and natural user input.

### Steps To Reproduce:
/bootstrap/app.php
```php
<?php

setlocale(LC_NUMERIC, "de_DE.UTF-8");
```

/routes/web.php
```php
Route::get('test', function () {
    $validator = Validator::make(['lat' => '52,5208618'], [
       'lat' => 'numeric'
    ]);

    if ($validator->fails()) {
        dd($validator->getMessageBag());
    }
});
```

**Comment by themsaid** [comment]
Not sure if there's a PHP way in converting numbers, but I'd suggest that you do something like:

```
str_replace(',', '.', $lat);
```
