### ISSUE TITLE
Date formatted fine in 4.2 but not working in 5.3

### ISSUE THREAD

**Issue by whfamily2006** [laravel/framework#15640]
- Laravel Version: 5.3.9
- PHP Version: 5.6.24
- Database Driver & Version: Mysql

### Description:
Date format:  '24/05/1986' 
and now in 5.3 its converted into '24\/05\/1986'
what is the reason and solution... ?

**Comment by srmklive** [comment]
Are you saving this format in the database? If so, to show to it on view, simply add `stripslashes('24\/05\/1986')` to display it as `'24/05/1986'`

**Comment by whfamily2006** [comment]
but when i use this following function its converted into wrong format.
 ` Log::info('Date: ' . json_encode($date, JSON_PRETTY_PRINT));`
