### ISSUE TITLE
How to override MandrillTransport send message for Templates

### ISSUE THREAD

**Issue by fakharkhan** [laravel/framework#15645]
- Laravel Version: 5.3

### Description:
Hi @taylorotwell 
 i am looking for a solution to modify/override MandrillTransport class send function to use 
"send-template.json" api instead of "send-raw.json"
So that i can keep the notifcation system but just tell laravel to override Mandrill Api Method.

Thanks in advance for helping me.

**Comment by EliasZ** [comment]
This isn't the Laravel support forum.

**Comment by fakharkhan** [comment]
@EliasZ i am looking to use Template for Mandrill, so either some one can help me or we can ask @taylorotwell to add this feature in laravel.
let me know if it makes sense?

**Comment by themsaid** [comment]
Hello @fakharkhan. For suggestions and feature requests please use the https://github.com/laravel/internals repo.

Appreciate your suggestion but this repo is for bug reporting only :)
