### ISSUE TITLE
[5.3] retrieving array validation msgs error

### ISSUE THREAD

**Issue by ctf0** [laravel/framework#15642]
- Laravel Version: 5.3.10 / 5.3.11
- PHP Version: 7.0.9
- Database Driver & Version: NaN

### Description:
![test](https://cloud.githubusercontent.com/assets/7388088/18905426/6dada35c-8563-11e6-9568-2c13d371f8df.jpg)

### Steps To Reproduce:
https://laravel.com/docs/5.3/validation#working-with-error-messages

```blade
{{ Form::open(['route' => 'store.files', 'method' => 'POST', 'files'=>true]) }}
    {{ Form::file('image[]', ['multiple']) }}
    {{ Form::submit('submit') }}
{{ Form::close() }}

@if (isset($errors))
    <ul>
        @foreach ($errors->get('image.*') as $one)
            <li>{{ $one }}</li>
        @endforeach
    </ul>
@endif
```
```php
$this->validate($request, [
    'image.*' => 'required|image|max:2048'
]);
```

**Comment by themsaid** [comment]
The result would be an array not a string. `dd($errors->get('image.*'))` to know what's inside.

**Comment by ctf0** [comment]
this wasn't a question of what the type the prop should return , its a bug because it doesnt work as it was noted in the docs & using a `dd` to return the data is not an answer.

**Comment by ctf0** [comment]
also plz try not to get infected by the old graham where u just close every issue without some further investigation.
