### ISSUE TITLE
[L5.2.45] Laravel throttle with load balancers

### ISSUE THREAD

**Issue by ronnievisser** [laravel/framework#15654]
- Laravel Version: 5.2.45
- PHP Version: 7
- Database Driver & Version:
mysql/redis

Last weekend I have setup a load-balancer on forge with 2 api servers below it. I have a rate limit (throttle) active. since the load balancer is added really weird thing are happening. the "X-RateLimit-Remaining" header is decreased constantly even when there is not even a call to the service.

I have a special forge server spinned up that handles the cache which is currently based on redis.

I'm desperate and hoping to get some answers here.

In the last 10 minutes I have made 4 API calls and the rate limit goes from 1000 to 531.

When decoupling 1 server from the rate limiter ( and add it to the hosts file so I can call it) the same code base works fine. so the limit decreases 1 by 1 by 1.

PS. I post this here since I don't get any feedback on forums.

**Comment by ronnievisser** [comment]
I had an issue with the throttle functionality before since I defined it in the Kernel.php file and on routes which caused limited counted twice. At the moment the throttle middleware is only called on the Route::group

```php
Route::group( [ 'prefix' => 'v1.2', 'middleware' => [ 'throttle:'1000,60' ] ], function() {
// Routes
});
```

**Comment by GrahamCampbell** [comment]
Sounds like trusted proxies are not set up correctly. :)

**Comment by taylorotwell** [comment]
@GrahamCampbell can you explain how trusted proxies affects this particular middleware?

**Comment by GrahamCampbell** [comment]
Because the IP address of your load ballencer is getting used instead of the customer.

**Comment by ronnievisser** [comment]
i'm currently monitoring with this package installed: https://github.com/fideloper/TrustedProxy.

will let you know the outcome.

**Comment by GrahamCampbell** [comment]
I use this stuff behind a load ballancer and it works fine.

**Comment by taylorotwell** [comment]
Interesting, OK. Thanks @GrahamCampbell :)
