### ISSUE TITLE
Blade view engine is not reentrant

### ISSUE THREAD

**Issue by tobia** [laravel/framework#15662]
- Laravel Version: 5.3
- PHP Version: 7.0.11
- Database Driver & Version: none

### Description:

I'm implementing a widget system for my application, where each page contains one or more forms, and each form is made of reusable widgets.

The pages are rendered using Blade views, but the widgets are also rendered using smaller Blade views.

This is what my code is currently doing (simplified):

1. the page controller creates a number of Widget instances, as appropriate for the form to show, and passes control to the page's Blade view;
2. the page's view loops over the widgets and calls a certain method on each widget, without HTML escaping;
3. inside that method, each widget renders itself (lazily) by creating and returning a View object.

Example page view:

    @foreach ($widgets as $widget)
        {!! $widget->render() !!}
    @endforeach

Example widget render method:

    public function render()
    {
        return view('widgets.myWidget', $this->params);
    }
    
So far so good, it works as expected, because the standard View objects returned by the widgets implement `__toString()` by calling `$this->render();` on the View itself.

The issue arises when the Widget views make use of template inheritance. Suppose I have two widgets that both `@extends('baseWidget')` and provide different contents in some `@section('content')`.

**Now the second (and following) widgets display the @section content of the first widget, instead of their own.**

Something is clearly non-reentrant in the Blade engine or in the View class.

I worked around the issue by pre-rendering the widgets to HTML before invoking the page view, so that there is no case where a View's `render()` method is called inside another View's `render()`. But I'm left wondering if this is an actual bug or just a misuse of the view engine on my part.

What could I do differently, to avoid having to pre-render the widgets?

Using `@include` in my page view is not an option, because I would like to hide the view engine used by the widgets (to allow widgets to generate their HTML by other means.)

### Steps To Reproduce:

[Here is a tiny ZIP file](https://www.dropbox.com/s/e4ws3g2f4ihy9wz/laravel_reentrant_view_issue.zip?dl=1) that you can extract into a new 5.3 installation to reproduce the issue. Just launch serve and open the homepage, it should be self-explanatory.

**Comment by themsaid** [comment]
It doesn't sound right to render views inside a view, this might light to unpredictable behaviour specially when it comes to caching.

Can you please explain more why don't you want to use `@include`? That part is not clear.

**Comment by tobia** [comment]
Right now most of my widgets are simple `<input>` or `<select>` tags, with their various attributes handled by their classes and views. So I could in fact expose their view name and data and use `@include` in the main page view.

But thinking ahead, I thought it might be useful to allow widgets to generate their HTML in any other way, say manually in their PHP class, or by loading other resources.

But you're right, I don't really need to call a view inside a view, if it's problematic. I can always use a simple view that says `{!! $html !!}` if I ever need to output pre-rendered HTML.

If that's the case, maybe you could add an exception if someone tries to render a view inside a view?

**Comment by themsaid** [comment]
> If that's the case, maybe you could add an exception if someone tries to render a view inside a view?
I don't think we can catch this, it's not wrong too it's just a problematic approach.

Anyway, rendering the subviews before the main view would give you the results you need.
