### ISSUE TITLE
Cannot @include the same view multiple times if it uses inheritance

### ISSUE THREAD

**Issue by tobia** [laravel/framework#15666]
- Laravel Version: 5.3
- PHP Version: 7.0.11
- Database Driver & Version: none

### Description:

Using `@include` to include the same view multiple times in a page, for example to render many similar parts (many text widgets in a form, many banners, etc.) doesn't work if the included view uses `@extends`: all the instances come out with the contents of the first one.

### Steps To Reproduce:

welcome.blade.php:

    @include('hello', ['name' => 'Town'])
    @include('hello', ['name' => 'World'])

hello.blade.php:

    @extends('greeting')

    @section('content')
        Hello, {{ $name }}!
    @stop

greeting.blade.php:

    <p>@yield('content')</p>

### Expected results:

    <p>Hello, Town!</p>
    <p>Hello, World!</p>

### Actual results:

    <p>Hello, Town!</p>
    <p>Hello, Town!</p>

**Comment by bobbybouwmann** [comment]
I believe you can only have one section called `content` Can you try to give the section another name and see if that works?

**Comment by tobia** [comment]
My use case is composing a form from reusable widgets. If my form has two or more text inputs, they must be rendered with the same view, and only the variables (the view data) differ!

In fact, I can simplify the above example to just use 3 views...

**Comment by themsaid** [comment]
Since this will render section `content` multiple times you need to overwrite the output because instead it'll keep using the first rendering.

```
@extends('greeting')

@section('content')
    Hello, {{ $name }}!
@overwrite
```

This will solve your issue, notice `@overwrite`

**Comment by tobia** [comment]
I'll be damned! I only knew about `@show` and `@stop`, but there's also `@overwrite` and `@append`!

Time to go read the source code. Thanks.

**Comment by themsaid** [comment]
Welcome :)

**Comment by nguyennhattruong** [comment]
Thanks themsaid!
