### ISSUE TITLE
[5.3] Pagination and PDO::ATTR_CASE / PDO::CASE_UPPER

### ISSUE THREAD

**Issue by TWITConsulting** [laravel/framework#15668]
- Laravel Version: 5.3
- PHP Version: 7.0.11
- Database Driver & Version: Oracle PDO 

### Description:

When using this PDO::CASE_UPPER as database connection option all field names in results in upper case letters only. Together with Oracle and Pagination this might lead to an error ($aggregate not found on class stdClass).

### Steps To Reproduce:

1. Use a Oracle configuration in config/database.php (might not only happen on Oracle, but we use it - and the error appeared):

```
 'connections' => [
         'oracle' => [
             'driver' => 'oracle',
             'tns' => env('DB_TNS', ''),
             'host' => env('DB_HOST', ''),
             'port' => env('DB_PORT', '1521'),
             'database' => env('DB_DATABASE', ''),
             'username' => env('DB_USERNAME', ''),
             'password' => env('DB_PASSWORD', ''),
             'charset' => env('DB_CHARSET', 'WE8MSWIN1252'),
             'prefix' => env('DB_PREFIX', ''),
             'prefix_schema' => env('DB_SCHEMA_PREFIX', ''),
             'options' => env('DB_OPTIONS', [
                 PDO::ATTR_CASE => PDO::CASE_UPPER,
             ])
         ],
     ],
```

The important line is the usage of the PDO::CASE_UPPER here

2. Do a query on a model and try to paginate:

`$pagination` = TestModel::paginate(15);

You will retrieve an error:

> Undefined property: stdClass::$aggregate

This appears within the getCountForPagination()-function the the Illuminate\Database\Query\Builder here:

```
if (is_object($item)) {
    return (int) $item->aggregate;
}
```

As the PDO::ATTR_CASE will upper case the fields, the $item will have a field "AGGREGATE" (and not a field "aggregate" as the code assumes).

**Comment by themsaid** [comment]
@TWITConsulting what do you suggest for a fix?

**Comment by srmklive** [comment]
@TWITConsulting Oracle is officially supported in Laravel.

**Comment by TWITConsulting** [comment]
@themsaid As mentioned already in the pull request-discussion: Converting the column names to lowercase if the database driver/PDO is configured to use PDO::CASE_UPPER is the best solution.

Doing this conversion is already done if the result from the aggregate-/count-query is returned as array (in this case all array keys are converted to lower case before evaluating the result).

So applying this fix to the object-related handling of the result will be increase the code consistency within the function.
