### ISSUE TITLE
[5.3] The Mail::to() doesn't accept an array of emails

### ISSUE THREAD

**Issue by atthakorn** [laravel/framework#15673]
- Laravel Version: 5.3.10
- PHP Version: 7

### Description:
The `Mail::to()` doesn't accept an array of emails

### Steps To Reproduce:

```php
$emails =  ['a@a.com', 'b@b.com']
Mail::to($emails)->send(new ContactMail());
```

the result, no email sent to recipients in `$emails` array.

I have looked into code in `\Illuminate\Mail\Mailable->setAddress()` . If `$address` is an array, it will fall into this condition

```php
if ($address instanceof Collection || is_array($address)) {
            foreach ($address as $user) {
                $this->{$property}($user->email, $user->name);
            }
} 
```

as `$address` is array of emails  not `users`, `$address` will not have **email** and **name** properties.  therefore, none of  emails added into `$this->{$property}[]` array, where properties is **to**, **cc**, **bcc**, **replyTo**.

please prioritize to fix!

**Comment by remoblaser** [comment]
I guess you could just create a Object with these E-Mails to fix it for now, the easy solution would be to add an additional if clause to check whether $user is an object.

**Comment by themsaid** [comment]
Please upgrade to latest version.

**Comment by atthakorn** [comment]
thanks guy.
