### ISSUE TITLE
Question about multiple address support of Message#cc,bcc in 5.1 version

### ISSUE THREAD

**Issue by qiuyin** [laravel/framework#15688]
- Laravel Version: 5.1

The document comments in the below say the type of $address is **string**, but actually **array** type also work well, right?
1. https://github.com/laravel/framework/blob/5.1/src/Illuminate/Mail/Message.php#L89
2. https://github.com/laravel/framework/blob/5.1/src/Illuminate/Mail/Message.php#L101

**Comment by themsaid** [comment]
Yeah an array would work, the docblock just needs an update.

**Comment by qiuyin** [comment]
@themsaid  Thank you for your quick reply.
I have opened a Pull request to fix this fault. Thank you.
