### ISSUE TITLE
Ideas for the future: including laravel-pug and BlueBerry

### ISSUE THREAD

**Issue by lazytyper** [laravel/framework#15682]
I am a lazy typer, on my actual project I am using this:

https://github.com/CREEATION/laravel-elixir-jade and CoffeeScript for easier developing my views.

This here might be better:
https://github.com/BKWLD/laravel-pug 

I did not test it yet, but it looks great, maybe it can be included by default.

Another great thing I've found is this here:
https://github.com/gosukiwi/Blueberry
(I've been searching with the keywords `php` and `CoffeeScript`.)

This looks great, too. ;) Maybe it can be included, too, in the future.

Both libs could make developing more easier.

**Comment by themsaid** [comment]
@lazytyper thank you for suggestion but this repo is for bug reporting only :)

For suggestions and feature requests please use the https://github.com/laravel/internals repo.
