### ISSUE TITLE
Soft deletes are not applied in time while testing

### ISSUE THREAD

**Issue by themccallister** [laravel/framework#15680]
- Laravel Version: 5.3.10
- PHP Version: 7.0.5
- Database Driver & Version: Postgres 9.4.7

### Description:
When using soft deletes on a model, the deleted_at attribute does not seem to "fire" in time for the test to successfully asset that the column is not null.

### Steps To Reproduce:

1. Create a model using Soft Deletes
2. Add a resource controller with the endpoint to test the destroy method
3. Write the test

It is also important to note that I removed the use of DatabaseTransactions on the main test to troubleshoot. After the test fails, I check that record in the table and the deleted_at attribute is NOT null.

It appears to set the timestamp after the test has run.

Hopefully this is just a simple user error :)

Thoughts?

#### Model

This is a sample model, nothing specific.

```
<?php
namespace App;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Model;

class County extends Model
{
    use SoftDeletes;
}
```

#### Test

The test that is failing.

````
/** @test */
public function can_delete_an_existing_resource()
{
    $county = \App\County::all()->random(1);
    $this->delete('v2/counties/' . $county->id);
    $this->seeIsSoftDeletedInDatabase('counties', $county->getAttributes());
}
```

#### Helper On TestCase.php

Added this helper on the TestCase class.

```
protected function seeIsSoftDeletedInDatabase($table, array $data, $connection = null)
{
    $database = $this->app->make('db');

    $connection = $connection ?: $database->getDefaultConnection();

    $count = $database->connection($connection)
        ->table($table)
        ->where($data)
        ->whereNotNull('deleted_at')
        ->count();

    $this->assertGreaterThan(0, $count, sprintf(
        'Found unexpected records in database table [%s] that matched attributes [%s].', $table, json_encode($data)
    ));

    return $this;
}
```

**Comment by themsaid** [comment]
`$county->getAttributes()` has `deleted_at = null`, so when you do `where($data)` the model won't be found, that's why the test is failing.

**Comment by themccallister** [comment]
@themsaid thanks for closing this, I realized it was a mistake last night. 

I needed to find the model after the fact and then query that to see the test pass.

```
$deletedModel = \App\County::where('id', $model->id)
            ->withTrashed()
            ->get();
```
