### ISSUE TITLE
Do belongsTo() really have to run a query when foreign key on the parent is null?

### ISSUE THREAD

**Issue by komakino** [laravel/framework#15683]
- Laravel Version: v5.2.43
- PHP Version: PHP 5.5.9-1ubuntu4.19
- Database Driver & Version: mysql 5.6.33

### Description:
I noticed that on some requests in a fairly large project i'm working on, a quarter of the queries run was like: 
```sql
select * from 'some_table' where 'some_table'.'id' is null limit 1;
```
After a bit of digging it seems like `belongsTo()`-relations always runs the query, even if the foreign key is `null`. So the question is: does it really need to?

It might be small queries, but on a request with many models with lots of unset relations, it really adds up.

**Comment by themsaid** [comment]
@komakino Well if you eager load the relation there will be 1 single query that collects all the related models, given your example it seems like you're loading the relation on each model generating 1 query per record.

**Comment by komakino** [comment]
@themsaid Tah doesn't really answer the question though. Does it have to? Wouldn't it be quite simple to just *not* run the query if the foreign key is null?

**Comment by themsaid** [comment]
I think it's doable yes, not quite sure :) Will look into it and open a PR.

The reason why I closed the issue is just that we're trying to keep this repo for bug reporting only 
and have https://github.com/laravel/internals  for suggestions and requests.

**Comment by komakino** [comment]
That sound great! Thanks, and sorry for clogging up the issues board.
