### ISSUE TITLE
VueJS does not pickup JSON props

### ISSUE THREAD

**Issue by Francismori7** [laravel/framework#15698]
- Laravel Version: latest 5.3
- PHP Version: 7.0
- Database Driver & Version: MySQL
- Vue version: 2.0.1

### Description:
So when using curly braces in blade to pass my authenticated user to my Vue instance using props, the Json string has its html entities encoded and so Vue just ignores it.

### Steps To Reproduce:
```
<div id="app" :user='{{ auth()->user() })'>

</div>
```

The user property when looking in the source code now has &quote;'s everywhere and all. The Json shouldn't be encoded

**Comment by thecrypticace** [comment]
Use `{!! auth()->user() !!}`
