### ISSUE TITLE
addWhereExistsQuery method is called but not defined in Illuminate\Database\Eloquent\Builder

### ISSUE THREAD

**Issue by karllhughes** [laravel/framework#15699]
- Laravel Version: 5.3.14
- PHP Version: 7.0.11
- Database Driver & Version: MySQL

### Description:
On [line 940](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Eloquent/Builder.php#L940) of the `Illuminate\Database\Eloquent\Builder` class there is a call to `$this->addWhereExistsQuery($hasQuery->toBase(), $boolean, $not)`. The method `addWhereExistsQuery` is not defined in this class though.

This caused a `Seg Fault 11` for me when testing a model that uses a scope method with a `whereHas` relationship.

### Steps To Reproduce:
This bug is reporting a missing method, so reproducing the symptoms is irrelevant, but I found it while integration testing a model/database relationship that used a scope method with a `whereHas` relationship, eg:

```
    public function scopeTeacherInProgress($query, $userId = null)
    {
        return $query->whereHas('assignment', function($query) use ($userId) {
                return $query->where('teacher_id', $userId);
        });
    }
```

When I ran an integration test on this model with code coverage turned on, I got a Segmentation Fault 11 error, which usually indicates a memory leak. After following the path, I found this missing method.

**Comment by alexweissman** [comment]
`Eloquent\Builder` has a member `Query\Builder` variable, and it uses `__call` to "pass through" a lot of methods called on `Eloquent\Builder` to the underlying `Query\Builder`.  See https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Builder.php#L1217-L1285.

If you check `Query\Builder`, you will see that `addWhereExistsQuery` is defined there.

That being said, I am also encountering segmentation faults when I try to test methods that use an `Eloquent\Builder` instance that ends up calling these underlying `Query\Builder` instances.  Did you ever figure out what is causing this?

**Comment by karllhughes** [comment]
@alexweissman I ended up just skipping this test if code coverage was turned on I think. It doesn't seem like an issue in production code, so it might have something to do with the test setup.

**Comment by alexweissman** [comment]
I have figured this out - it would appear that it was related to a [bug in Mockery prior to version 1.0.0-alpha](https://stackoverflow.com/questions/27925921/segmentation-fault-while-mocking-classes-with-call-in-php/45644000#45644000).
