### ISSUE TITLE
Automatically get "withCount" values

### ISSUE THREAD

**Issue by asdfgasd815f** [laravel/framework#15692]
Referring to this SO question:

http://stackoverflow.com/questions/39784557/automatically-get-withcount

We're currently able to add the following code to a model in order to automatically retrieve relationships:

```
protected $with = [
    'users', 'scores'
];
```

However, we're **not able** to add the following in order to automatically retrieve relationship counts:

```
protected $withCount = [
    'users'
];
```

This should be added as a feature.

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
