### ISSUE TITLE
Daemon Queue Worker

### ISSUE THREAD

**Issue by olga3emes** [laravel/framework#15690]
- Laravel Version: 4.2.*
- PHP Version: 5.6.25 
- Database Driver & Version: 14.14 Distrib 5.5.51, for Linux

### Description:
We have a problem with queues in our server, we use supervisord and the configuration of queues (with queue:work) is correct because they run ok, and any log file (of supervisord and the specific file of each queue) no contain reports of error messages or failed processes. But, when they are running during some time, for one or two of them, the queue not is running and the process is out. Any idea?

Thanks.

We are using a instance with Linux Amazon , Nginx and supervisord . 

### Steps To Reproduce:
This is our supervisord.conf file:

`[supervisord]`

`http_port=/var/tmp/supervisor.sock ; (default is to run a UNIX domain socket server)
;http_port=127.0.0.1:9001  ; (alternately, ip_address:port specifies AF_INET)
;sockchmod=0700              ; AF_UNIX socketmode (AF_INET ignore, default 0700)
;sockchown=nobody.nogroup     ; AF_UNIX socket uid.gid owner (AF_INET ignores)
;umask=022                   ; (process file creation umask;default 022)
logfile=/var/log/supervisor/supervisord.log ; (main log file;default $CWD/supervisord.log)
logfile_maxbytes=50MB       ; (max main logfile bytes b4 rotation;default 50MB)
logfile_backups=10          ; (num of main logfile rotation backups;default 10)
loglevel=info               ; (logging level;default info; others: debug,warn)
pidfile=/var/run/supervisord.pid ; (supervisord pidfile;default supervisord.pid)
nodaemon=false              ; (start in foreground if true;default false)
minfds=1024                 ; (min. avail startup file descriptors;default 1024)
minprocs=200                ; (min. avail process descriptors;default 200)`

`;nocleanup=true              ; (don't clean up tempfiles at start;default false)
;http_username=user          ; (default is no username (open system))
;http_password=123           ; (default is no password (open system))
;childlogdir=/tmp            ; ('AUTO' child log dir, default $TEMP)
;user=chrism                 ; (default is current user, required if root)
;directory=/tmp              ; (default is not to cd during start)
;environment=KEY=value       ; (key value pairs to add to environment)`

`[supervisorctl]
serverurl=unix:///var/tmp/supervisor.sock ; use a unix:// URL  for a unix socket
;serverurl=http://127.0.0.1:9001 ; use an http:// url to specify an inet socket
;username=chris              ; should be same as http_username if set
;password=123                ; should be same as http_password if set
;prompt=mysupervisor         ; cmd line prompt (default "supervisor")`

`; The below sample program section shows all possible program subsection values,
; create one or more 'real' program: sections to be able to control them under
; supervisor.`

`;[program:theprogramname]
;command=/bin/cat            ; the program (relative uses PATH, can take args)
;priority=999                ; the relative start priority (default 999)
;autostart=true              ; start at supervisord start (default: true)
;autorestart=true            ; retstart at unexpected quit (default: true)
;startsecs=10                ; number of secs prog must stay running (def. 10)
;startretries=3              ; max # of serial start failures (default 3)
;exitcodes=0,2               ; 'expected' exit codes for process (default 0,2)
;stopsignal=QUIT             ; signal used to kill process (default TERM)
;stopwaitsecs=10             ; max num secs to wait before SIGKILL (default 10)
;user=chrism                 ; setuid to this UNIX account to run the program
;log_stdout=true             ; if true, log program stdout (default true)
;log_stderr=true             ; if true, log program stderr (def false)
;logfile=/var/log/cat.log    ; child log path, use NONE for none; default AUTO
;logfile_maxbytes=1MB        ; max # logfile bytes b4 rotation (default 50MB)
;logfile_backups=10          ; # of logfile backups (default 10)`

`[program:laravel-worker]
numprocs=2
process_name=QueueEstadisticas
command=php /var/www/html/aula/artisan queue:work --sleep=3 --tries=3
priority=999
autostart=true
autorestart=true
startretries=3
user=root
log_stderr=true
logfile=/var/www/html/aula/worker/worker.log`

`[program:laravel-worker-realizar-reto]
numprocs=2
process_name=QueueRealizarReto
command=php /var/www/html/aula/artisan  queue:work --queue=realizarReto --sleep=3 --tries=3
priority=999
autostart=true
autorestart=true
startretries=3
user=root
log_stderr=true
logfile=/var/www/html/aula/worker/realizarreto.log`

`[program:laravel-worker-retos]
numprocs=2
process_name=QueueRetos
command=php /var/www/html/aula/artisan queue:work --queue=retos --sleep=3 --tries=3
priority=999
autostart=true
autorestart=true
startretries=3
user=root
log_stderr=true
logfile=/var/www/html/aula/worker/retos.log`

`[program:laravel-worker-retostest]
numprocs=2
process_name=QueueRetosTest
command=php /var/www/html/aula/artisan queue:work --queue=retosTest --sleep=3 --tries=3
priority=999
autostart=true
autorestart=true
startretries=3
user=root
log_stderr=true
logfile=/var/www/html/aula/worker/retostest.log`

**Comment by GrahamCampbell** [comment]
Please ask on the forums.
