### ISSUE TITLE
Laravel partial blades giving undefined variable error

### ISSUE THREAD

**Issue by kadnan** [laravel/framework#15707]
- Laravel Version: 5.3.15
- PHP Version: 7.0.8
- Database Driver & Version:

### Description:
I am passing variable in my view partial but in partial it says variable not found. I am doing following:
```
@include('partials._latest',['title' => 'Latest Products','entries' => $entries])
```
and in partial I am calling as `{{$title}}`

I am getting:
```
ErrorException in 4ffcd30ab3dcb337e74cecc7f61f71723f113d8f.php line 3:
Undefined variable: title (View:..
```

### Steps To Reproduce:

Create a parent view and in that call:
- Create a subfolder in your view with name `partials`.
- In that partial just write a single line {{$title}}
- in Parent view write: `@include('partials.subview',['foo' => 'value')`

I also checked compiled view and found it's using `get_defined_vars()` method. I explicitly called in my parent view and turned out that it is not returning `$title` at all. Somehow I think it's a bug in `@include` that it is not passing variable.

**Comment by GrahamCampbell** [comment]
Include only takes one paramater.

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/blob/5.3/src/Illuminate/View/Compilers/BladeCompiler.php#L868-L879

**Comment by GrahamCampbell** [comment]
Oh, actually, you can pass params like that since that variable can have commas in it, but we cannot reproduce this not working. We also have tests for this I think.

**Comment by kadnan** [comment]
>but we cannot reproduce this not working. We also have tests for this I think.

Can't reproduce? means it's working at your end?

**Comment by kadnan** [comment]
Ok Issue was sorted out by Laravel Forum's kind member. I had called `@include('partials._latest')` without parameter and thus it was obvious giving `undefined` error.
