### ISSUE TITLE
env() helper function does not work well in web.php

### ISSUE THREAD

**Issue by Caxvalencia** [laravel/framework#15714]
- Laravel Version: 5.3
- PHP Version: 7

### Description:
The env() helper function not work in **/routes/web.php**, when I call this function, it return me a value of null for any parameter that I pass him. In this case **env( APP_URL )**

### Steps To Reproduce:
my file **.env**
```
APP_URL=http://test.dev
```

**/routes/web.php**
```php
dd( env( 'APP_URL' ) ); // Return null
```

I hope you can help me, thanks and greetings :D (Y)

**Comment by GrahamCampbell** [comment]
You should only ever use the env function inside config files.

**Comment by Caxvalencia** [comment]
I understand, then, do I have no other alternative, for access to the value of APP_URL?

**Comment by seleznevdev** [comment]
@Caxvalencia, `config('app.url')`

**Comment by pkaruga** [comment]
Run php artisan config:clear
