### ISSUE TITLE
Independent packages

### ISSUE THREAD

**Issue by AliFarhoudi** [laravel/framework#15715]
- Laravel Version: 5.3.0
- PHP Version: 5.6.26
- Database Driver & Version: mysql  Ver 15.1 Distrib 10.0.26-MariaDB

### Description:
I need a structure to support completely independent packages. Vendor packages are dependent to composer, but I am going to implement packages that do not need any dependency and run if I copy it in the project and do not run without any problem if I remove it.
I want to do this based on SOA (service oriented architecture).
I didn't find any related issue.
If that's a correct idea, I could develop that and contribute to laravel/framework repository.
Any comment or idea is appreciated.

**Comment by GrahamCampbell** [comment]
Feel free to discuss on the forums.

**Comment by AliFarhoudi** [comment]
Hi.
OK, but what forums?

**Comment by GrahamCampbell** [comment]
Wherever you want.

**Comment by AliFarhoudi** [comment]
I'm not just asking question. I had an idea for that and wanted to contribute.
Before releasing Laravel 5.3 we implemented an complete authentication package just like passport. We even used libraries Laravel has used.
We didn't want this happen again for our new package, then we decided to contribute, so that ourselves and other people use it and our coding wouldn't be useless.
