### ISSUE TITLE
Add atLastDayOfMonth([hh:mm]) option for scheduler (feature suggestion)

### ISSUE THREAD

**Issue by andreasba** [laravel/framework#15712]
Good afternoon,

I would like to propose an additional option for scheduling the execution of commands via the scheduler: an **atLastDayOfMonth([hh:mm])** method with the optional argument of being able to provide an exact time when the command should be executed.

This is especially useful for example if one wants to bill something at the end of the month, send a summary or something like that.

Of course the alternative would be to do it like this (Source: mul14 at [laracasts] (https://laracasts.com/discuss/channels/laravel/how-to-run-scheduler-on-last-day-of-month/replies/283642)):

```$schedule->command('inspire')->when(function () {
    return \Carbon\Carbon::now()->endOfMonth()->isToday();
});```

but then everyone who needs this functionality needs to check if the command has already run etc. (no good to send a summary twice!) 

So IHMO it would be cleaner if this would come out of the box.

Thank you
Andreas

**Comment by GrahamCampbell** [comment]
Feel free to send a PR. :)
