### ISSUE TITLE
session_write_close(): Session callback expects true/false return value

### ISSUE THREAD

**Issue by lcharette** [laravel/framework#15717]
- Laravel Version: 5.3
- PHP Version: 7.0.8

### Description:

Since I upgraded my test server to php7, I get this warning in the logs :

```
PHP Warning:  session_write_close(): Session callback expects true/false return value in Unknown on line 0
PHP Warning:  session_write_close(): Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/var/lib/php/sessions) in Unknown on line 0
```

We use `Illuminate/Session` `FileSessionHandler` ([See here](https://github.com/userfrosting/UserFrosting/blob/dev/app/sprinkles/core/src/ServicesProvider/CoreServicesProvider.php#L379)). 

According to [this thread](http://stackoverflow.com/a/36283874), the `write` method of the session handler needs to return `true`. Adding `return true;` here will fix the warning message : https://github.com/illuminate/session/blob/master/FileSessionHandler.php#L81-L84

This probably apply to other Session handler inside `Illuminate/Session` as well.

**Comment by GrahamCampbell** [comment]
We don't use the session_write_close function.

**Comment by lcharette** [comment]
From what I understand, `session_write_close` is called during a normal shutdown, so when a page is done loading.

See: http://php.net/manual/en/sessionhandlerinterface.write.php

**Comment by lcharette** [comment]
Turns out this warning can also be fired when `session_destroy` and `session_regenerate_id` is called...
