### ISSUE TITLE
Notification fakes don't work for password reset notifications

### ISSUE THREAD

**Issue by zachleigh** [laravel/framework#15721]
- Laravel Version: 5.3.10
- PHP Version: 7.0.8
- Database Driver & Version: MariaDB 10.1.18

### Description:
Faking Notification does nothing when testing built in Laravel password reset notifications. Notifications are still sent and all assertions fail.

### Steps To Reproduce:
This is my test:
```
use App\Notifications\ResetPassword;
use Illuminate\Support\Facades\Notification;

class PasswordResetTest extends SeleniumTestCase
{
    /**
     * @test
     */
    public function user_can_reset_password()
    {
        Notification::fake();

        $this->visit('/')
             ->press('Forgot password?')
             ->type($this->user->email, 'email')
             ->press('Send')
             ->hold(3)
             ->see(trans('general.email_sent'));

        Notification::assertSentTo($this->user, ResetPassword::class);
    }
}
```
Im using phpunit and Selenium. When running this test, a mail is actually being sent to the users email and the assertion fails. Just for fun, I tried faking Mail too, but that also didnt do anything.

**Comment by themsaid** [comment]
@zachleigh this test doesn't look right to me, are you sure this is testing the built in password reset form?

**Comment by themsaid** [comment]
This works:

    public function testBasicExample()
    {
        $user = factory(\App\User::class)->create();

        Notification::fake();

        $this->visit('/password/reset')
            ->type($user->email, 'email')
            ->press('Send Password Reset Link');

        Notification::assertSentTo($user, ResetPassword::class);
    }

**Comment by zachleigh** [comment]
@themsaid I dont use the built in form, but my form points to same route as the built in one so the test should work. Anyway, it works for you so it must be something on my end. Thank you!

**Comment by themsaid** [comment]
@zachleigh keep us updated please if you ever found a bug in this area :)
