### ISSUE TITLE
Migration issue: Table create with index, default value and comment

### ISSUE THREAD

**Issue by dhavalv** [laravel/framework#15726]
- Laravel Version: 5.2.45
- PHP Version: 5.6.20
- Database Driver & Version:
MySql Ver 15.1 Distrib 10.1.13-MariaDB, for Linux (x86_64) using readline 5.1
I've create migration class for shorturls table
### Description:
```
Schema::create('shorturls', function (Blueprint $table) {
   $table->increments('id');
   $table->boolean('generated')->index()->default('0')->comment("test comment");
//$table->index(['generated']);
});
```
and migrate from command-line and it's return error: " vsprintf(): Too few arguments".

**Comment by srmklive** [comment]
@dhavalv Are you facing the same issue in 5.3?

**Comment by dhavalv** [comment]
Yes same as in laravel 5.3

**Comment by srmklive** [comment]
@dhavalv I just checked and couldn't replicate the issue you are facing. I am using:

* Laravel 5.3.14
* PHP 5.6.26
* MySQL 5.6.33

Following is the code with relative screenshots:

![screenshot from 2016-10-03 17 34 20](https://cloud.githubusercontent.com/assets/839335/19037496/013fd592-8990-11e6-8cad-3beb8d75f05d.png)

![screenshot from 2016-10-03 17 34 32](https://cloud.githubusercontent.com/assets/839335/19037503/0a9802d6-8990-11e6-9f39-165f834a5b08.png)

**Comment by dhavalv** [comment]
Thank you @srmklive,  for resolving my issue.
