### ISSUE TITLE
Blueprint's default column lengths could be made collation-aware

### ISSUE THREAD

**Issue by aphofstede** [laravel/framework#15725]
- Laravel Version: 5.3.#
- PHP Version: 7
- Database Driver & Version: MariaDB

### Description:
\Illuminate\Database\Schema\Blueprint's
`public function string($column, $length = 255)` and the like
could calculate the default $length to what the maximum unique key length is, instead of using this fixed function param default. (it's close enough) This prevents some obscure errors from occurring when switching collations.

### Steps To Reproduce:
Switch DB `collation` to `utf8mb4_unicode_ci` and `charset` to `utf8mb4` in the database config and run a migration with `$table->string('test')->unique();` in it.

**Comment by themsaid** [comment]
This sounds like a proposal to me not a bug, we keep this repository for but reports only, 
for suggestions and feature requests please use the https://github.com/laravel/internals repo.

**Comment by aphofstede** [comment]
https://github.com/laravel/internals/issues/239
