### ISSUE TITLE
whereHas not working when has relation with same table

### ISSUE THREAD

**Issue by arifmahmudrana** [laravel/framework#15728]
- Laravel Version: 5.2.45
- PHP Version:5.5.31
- Database Driver & Version: MySQL 5.6.28

### Description:
I have a `Profile` table & a `pivot` table `followers`. I have relation followers in `Profile` table. Now when I am checking find 1 profile who has follower 3 it builds this query

```
SELECT * 
FROM   `profiles` 
WHERE  EXISTS (SELECT * 
               FROM   `profiles` #Here `profiles` table isn't aliased so not returning correct result
                      INNER JOIN `followers` 
                              ON `followers`.`follower_id` = `profiles`.`id` 
               WHERE  `profiles`.`id` = `followers`.`profile_id` 
                      AND `follower_id` = 3) ##replace 3 with your follower id
       AND `profiles`.`id` = 1 ##replace 1 with your profile id
LIMIT  1 
```

But if you alias the query & run e.g

```
SELECT * 
FROM   `profiles`
WHERE  EXISTS 
       ( 
                  SELECT     * 
                  FROM       `profiles`  `p`
                  INNER JOIN `followers` 
                  ON         `followers`.`follower_id` = `p`.`id` 
                  WHERE      `profiles`.`id` = `followers`.`profile_id` 
                  AND        `follower_id` = 3) ##replace 3 with your follower id
AND      `profiles`.`id` = 1 ##replace 1 with your profile id
LIMIT  1 
```

You will get results

[model-migration.zip](https://github.com/laravel/framework/files/505954/model-migration.zip)

### Steps To Reproduce:
1. extract my zip file

2. create a new laravel project

3. add model & migration files to models & migration directory create model folder if not exist

4. add two records to `profiles` table & add one record using both profile in `followers` table

5. then run this in tinker or in any routes replace with your value `App\Models\Profile::whereHas('followers', function($q){ $q->where('follower_id', FOLLOWER_PROFILE_ID); })->find(YOUR_PROFILE_ID_PROFILES_TABLE_WHO_HAS_FOLLOWERS)`

**Comment by srmklive** [comment]
@arifmahmudrana Are you facing the same issue in 5.3? 5.2 is no longer actively supported.

**Comment by themsaid** [comment]
Your relationship is wrong, use:
    
    public function followers()
    {
        return $this->belongsToMany(Profile::class, 'followers', 'profile_id', 'follower_id');
    }
