### ISSUE TITLE
During unit test the Request object returns null on calling route()

### ISSUE THREAD

**Issue by d-lamers** [laravel/framework#15729]
- Laravel Version: 5.3
- PHP Version: 7.05
- Database Driver & Version: Mysql
- Running homestead

### Description:
The request returns null on calling route() during a unit test

### Steps To Reproduce:
Create a unit test to open assert opening a page.
In the controller of that page call $request->route()->getName() for example.
See how this works normally but not during tests.
I believe this is a bug because the unit test should return the same result as the real life test.

**Comment by themsaid** [comment]
I'm unable to replicate this, using `$request->route()->getName()` I'm able to get the route name in tests and in browser.

The laravel version in your bug report is not complete, please make sure you're running the latest release of laravel 5.3 and ping me if you're still facing the issue.

**Comment by d-lamers** [comment]
According to composer.lock I am running: "version": "v5.3.15", I suppose this is the latest since my composer.json requires 5.3.*

The error that is thrown by phpunit is:
    Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function getName() on null in

The function on that line is:
    if (strpos($this->request->route()->getName(), $this->route) !== 0) {

The request is set in the constructor like this
    public function __construct(Request $request,

Which is called in the boot method of a serviceprovider
    new NavItem($this->app['request'],

**Comment by themsaid** [comment]
What if you use `request()` instead? Does that make it work?

**Comment by rtconner** [comment]
`$request->route()->getName()` is probably being called before `$this->get()` is called in the test. That was my issue, anyways. Events were being fired in the setup that make the assumption of a route.
