### ISSUE TITLE
Illuminate packages not being released

### ISSUE THREAD

**Issue by martinssipenko** [laravel/framework#15734]
Hi,

I'm sorry if this has been raised before, but I noticed that the latest version of Illuminate packages currently is `5.3.4`, but laravel-framework is `5.3.15`.

Is it supposed to be like that or something is broken?

**Comment by martinssipenko** [comment]
This also is kind of related to https://github.com/laravel/lumen-framework/issues/494

**Comment by GrahamCampbell** [comment]
Thanks. We'll get them tagged soon. They often lag behind by a week or two. :)

**Comment by martinssipenko** [comment]
Last tag was August 25, that's almost 6 weeks.

@GrahamCampbell @taylorotwell Perhaps there is a way to automate this process?
