### ISSUE TITLE
negative value when 'too many login attempts' happens 

### ISSUE THREAD

**Issue by haheute** [laravel/framework#15738]
- Laravel Version: 5.3.15
- PHP Version: 7.0.11
- Database Driver & Version: mysql  Ver 15.1 Distrib 10.1.17-MariaDB, for Linux (x86_64) using readline 5.1
-  memcached: 1.4.31-1

### Description:
I don't know how this happens. I did a composer update some minutes ago and tested some functions locally, also the login. After 5 attempts with a wrong password I still can not login.

`Too many login attempts. Please try again in -127 seconds.`

### Steps To Reproduce:
Try to login with the same wrong password (i used 'wwww') with 'remember me' checkbox unchecked, until the throttle message appears. 
Try again with correct password, 3 sec before waiting time is over, with 'remember me' checked. And the again with correct password and remember me checked. The I see something like: "Try again after -15 seconds".

`Too many login attempts. Please try again in -684 seconds.`

My cache driver is `memcached`. The `:lockout` value stays in memcached even after 4000 seconds. 'Normal' `Cache::forget()` and other cache functions work in the application. 

When I do `php artisan cache:clear` I can login again, and with cache driver `file` everything seems to be okay.

**Comment by themsaid** [comment]
I don't seem to be able to replicate this using the file driver, so maybe it's only a memcached issue?

**Comment by haheute** [comment]
Thank you. Today, after a reboot, I can't reproduce it, too.

**Comment by themsaid** [comment]
💃 :D

**Comment by pfalsoncup** [comment]
FYI, just duplicated this on 5.4

**Comment by adamgibbins** [comment]
I can reproduce this in 5.6.16 backed by memcached, flip to file cache (or flush memcached) and it's resolved.
