### ISSUE TITLE
Eloquent whereNotIn handles array differently than whereIn

### ISSUE THREAD

**Issue by dericcain** [laravel/framework#15736]
- Laravel Version: 5.3.15
- PHP Version: 7
- Database Driver & Version:
MariaDB 10.1

### Description:
I created a scoped query like so....
```php
public function scopeUsersToTerminate($query, $userIds)
{
    return $query->whereNotIn('id', $userIds)->get();
}
```
... and the results of the query is `null`. `$userIds` is an array and should return all of the users that are not in that array. However, if I change the code to this...
```php
public function scopeUsersToTerminate($query, $userIds)
{
    return $query->whereIn('id', $userIds)->get();
}
```
... it does return all of the users that are in the array. I should mention that the array given does have keys and this may be the cause of the issue, but why do the two handle it differently?

**Comment by JoostK** [comment]
Could you provide the executed SQL statement?

**Comment by dericcain** [comment]
@JoostK I am not using a SQL statement. I am only using collections and Eloquent. Here is how I am gathering the collection.

`$this->employeeList->pluck('id')->unique()->toArray();`

I've tried using `flatten` and `collapse` to no avail. It seems that since there is as key in the array, `whereNotIn` does not like it.

**Comment by JayBizzle** [comment]
@dericcain if you look at the `whereNotIn()` method, you will see that keys will make no difference

https://github.com/laravel/framework/blob/d145a8426aac760d5a1e6a90add656a2d7a1a6b0/src/Illuminate/Database/Query/Builder.php#L892-L934

@JoostK was asking to provide the SQL statements that are generate by Eloquent. Use something like [Debugbar](https://github.com/barryvdh/laravel-debugbar) or use the `->toSql()` method.

**Comment by dericcain** [comment]
@JayBizzle Whoa. Didn't know about `toSql()` and I will be using that. When I look at the query, there is an obvious problem with the statement.

![screen shot 2016-10-03 at 4 18 29 pm](https://cloud.githubusercontent.com/assets/9561913/19054456/128c950c-8985-11e6-9a24-4b8f9f50d021.png)

But, if I just `dd()` out the results of the collection like so..

```php
$this->terminatedEmployees = $this->employeeList->pluck('id')->toArray();
dd($this->terminatedEmployees);
```
I can clearly see the list of `id` that I need.

![screen shot 2016-10-03 at 4 20 51 pm](https://cloud.githubusercontent.com/assets/9561913/19054531/63c9960e-8985-11e6-89cb-33352b129efe.png)

Now, I did manage to get it working by doing this...

```php
User::usersToTerminate(explode(',', $this->terminatedEmployees));
```

... but that feels really hacky. What gives?

**Comment by dericcain** [comment]
@JoostK @JayBizzle Well... apparently I was not saving the file or something because it is working with this:

```php
$this->terminatedEmployees = $this->employeeList->pluck('id')->unique()->flatten();
User::usersToTerminate($this->terminatedEmployees);
```
I just switched from PHPStorm to Sublime and Sublime doesn't autosave like PHPStorm so I'm sure that is what I was doing.... for 2 hours... Not sure how but that's my only theory.

**Comment by JayBizzle** [comment]
Glad you sorted it, at least you learnt a new method (`tosql()`) 👍

**Comment by Ahmed-Aboud** [comment]
whereNotIn will not return a result if the array have a value of null
