### ISSUE TITLE
Timezone (Carbon) error

### ISSUE THREAD

**Issue by jorenvh** [laravel/framework#15742]
- Laravel Version: 5.2.45
- PHP Version: 5.6.11

### Description:

On my production server I keep getting the following error in my log file, on almost every request.

PHP Warning: date_default_timezone_get(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in vendor/nesbot/carbon/src/Carbon/Carbon.php on line 172 

my timezone is set in config/app.php like this:

`'timezone' => 'Europe/Brussels',`

**Comment by it-can** [comment]
easy fix would be to set the date.timezone in your php.ini

**Comment by shockgonewild** [comment]
If you don't have access to php.ini you could as well call **date_default_timezone_set** in your AppServiceProvider

**Comment by jorenvh** [comment]
Thanks for the quick responses. Not really a framework issue I see.
