### ISSUE TITLE
Cron job - withoutOverlapping - Stuck

### ISSUE THREAD

**Issue by PieterScheffers** [laravel/framework#15750]
- Laravel Version: 5.2
- PHP Version: PHP 5.5.9-1ubuntu4.19 (cli) (built: Jul 28 2016 19:31:33)
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.5.52, for debian-linux-gnu (x86_64) using readline 6.3

### Description:
Sometimes the cron jobs don't run anymore. The reason is that the mutex file isn't cleaned after a run, so next runs keep skipping. Now is the temporary solution to just manually remove the mutex file.

https://laracasts.com/discuss/channels/laravel/laravel-task-scheduler-after-fatal-error-when-withoutoverlapping-is-set

Why doesn't Laravel use a file-locking mechanism (flock)? When a process is killed or an exception is thrown the file is automatically unlocked. The next run then will only be blocked when there already is a process running.

For example:
https://gist.github.com/PieterScheffers/8ca62d1e56cf93e03e08df82ca305989

**Comment by srmklive** [comment]
Laravel 5.2 is not officially supported anymore.

**Comment by jpldev** [comment]
It happens to me on Laravel 5.4

everyMinute() works

but

everyFiveMinutes() doesn't

What can I do?

**Comment by decadence** [comment]
Laravel 5.4 is not supported either

**Comment by decadence** [comment]
@andyscraven only LTS releases (5.1, 5.5).
