### ISSUE TITLE
[5.3] BelongsToMany with table prefixes seems not to work

### ISSUE THREAD

**Issue by KKSzymanowski** [laravel/framework#15752]
- Laravel Version: 5.3.16
- PHP Version: 5.6.15
- Database Driver & Version: Sqlite

#### Database schema
```
users:
-id
-name

prefix_roles:
-id
-name

prefix_role_user:
-id
-role_id
-user_id
-foo
```

#### Relationships:
User <- many to many -> Role

#### Connections
1. User utilizes a connection without a prefix(legacy app)
2. Role utilizes a connection with a prefix(new app using the same database)

Code that doesn't work:
```php
$role = Role::first();

$user = $role->users()->first();
$user->pivot->foo = 'bar';
$user->pivot->save();
```

In my example of this bug there are two possible relationship definitions on the `Role` model side.
```php
return $this->belongsToMany(User::class, 'role_user');
// or
return $this->belongsToMany(User::class, 'prefix_role_user');
```

Using first one(or leaving off the second parameter) the code breaks on the first line with error:
```
SQLSTATE[HY000]: General error: 1 no such table: role_user
```
and you think, _oh, it doesn't add the prefix automatically_, so you add the prefix manually. Now it breaks on the last line with error:
```
SQLSTATE[HY000]: General error: 1 no such table: prefix_prefix_role_user
```
and you think, _well, cock_.

### Steps To Reproduce:

1. git clone https://github.com/kkszymanowski/prefix-test
2. cd prefix-test
3. composer update
4. touch database/database.sqlite
5. php artisan migrate --seed
6. php artisan test<br>
Now you should get the first error.
7. Open `app/Role.php`, comment first return and uncomment second one.
8. php artisan test<br>
    Now you should get the second error.

**Comment by themsaid** [comment]
How do you define the table prefix?

**Comment by KKSzymanowski** [comment]
Here:
https://github.com/KKSzymanowski/prefix-test/blob/master/config/database.php#L57

**Comment by themsaid** [comment]
Couldn't regenerate, the prefix is added by default for you.

```
return $this->belongsToMany(User::class, 'role_user');
```

Will result a lockup for `prefix_role_user`

**Comment by KKSzymanowski** [comment]
Are you saying that the command runs successfully?

**Comment by themsaid** [comment]
That's the query I get:

```
select `prefix_roles`.*, `prefix_role_user`.`test_id` as `pivot_test_id` from `prefix_roles` inner join `prefix_role_user` on `prefix_roles`.`id` = `prefix_role_user`.`test_id` where `prefix_role_user`.`test_id` = 1
```

    public function users()
    {
        return $this->belongsToMany(Test::class, 'role_user');
    }

**Comment by KKSzymanowski** [comment]
How does the `Test` class look like?

**Comment by themsaid** [comment]
I'm not using your repo, I'm testing on a test app of mine using the conditions stated, the result query is by using:

```
\App\Test::find(1)->users()->get()
```

**Comment by KKSzymanowski** [comment]
Could you use my repo? It doesn't take long to get it running and I may have forgotten to mention some important parts.

**Comment by themsaid** [comment]
Now I can replicate, but you really have a very problematic situation, the pivot table is shared between two models on two different connections, based on the current codebase I don't think this is supported, the pivot table will be assumes to be on the same connection as the relationship other model.

**Comment by KKSzymanowski** [comment]
Same code worked when the `users` table was in different database then other ones. I think the problem is that the table name isn't prefixed on select but is prefixed on update. Can you look into it?

**Comment by themsaid** [comment]
the real problem is that it's not prefixed when called from within the relation, and that's because the relationship model is on the un-prefixed connection and so the pivot table follows it.

**Comment by themsaid** [comment]
I don't think there's a way to get around this :) Don't think this situation was ever in mind while designing the query builder, having the two models on two different connections laravel would never be able to guess which connection the pivot table is on.

**Comment by KKSzymanowski** [comment]
I know why it worked on two different dbs.
Apparently you can do a JOIN across two databases in MySQL. I suppose I will have to stick with that.
