### ISSUE TITLE
Can't access the 'data' values in the notification table

### ISSUE THREAD

**Issue by haheute** [laravel/framework#15754]
- Laravel Version: 5.3.15
- PHP Version: 7.0.11
- Database Driver & Version: mariadb 10.1.18-1

### Description:
I have tried the half day but can not display the `message` and `action` values from the `data` column in the notifications table. I followed the documentation [here ](https://laravel.com/docs/5.3/notifications#database-notifications)... The json encoded value seems to be an array for PHP, but I always get `index not found`. 
`json_decode()` did not help, because it is an array and the function needs a string.

How do you usually display the json values from the data column in a blade view? 

### Steps To Reproduce:
Follow the documentation, create migration and table. Insert some database notifications with `toArray()`. Try to display them.

        $notifications = Auth::user()->notifications()->paginate(30);

        return view('home.index')->with('notifications',$notifications);

        @forelse($notifications as $n)
            {!! var_dump($n->data) !!}
        @empty
            nothing
        @endforelse

It is a mystery having `var_dump()` telling me it is an array with `["message"]` and `["action"]` keys and then blade saying the indexes are not existent.

**Comment by themsaid** [comment]
Since it's a loop It's possible that 1 record in the collection returned doesn't have these indices, use isset to find the fault record.

**Comment by saeedjhn** [comment]
Just line blow:
$notifications = auth()->user()->notifications->pluck('data')->flatten(1);
