### ISSUE TITLE
Please can you add a tag for illuminate/filesystem 5.3.7

### ISSUE THREAD

**Issue by nedmas** [laravel/framework#15751]
- Laravel Version: 5.3.15
- PHP Version: N/A
- Database Driver & Version: N/A

### Description:
I'm trying to depend on illuminate/filesystem for a disk driver I am writing. Specifically I need a change that was added in 5.3.7 (4bede790264c3ad11771e72ec866cf4c177b4875). Therefore would it be possible to add a tag for 5.3.7 or later to illuminate/filesystem please?

**Comment by GrahamCampbell** [comment]
A v5.3.16 will probably go out when that't tagged on the framework. :)

**Comment by nedmas** [comment]
@GrahamCampbell sorry to be a pain but it looks like v5.3.16 has been released but there's no tag for illuminate/filesystem, any chance of getting one?

**Comment by GrahamCampbell** [comment]
I'll come soon, don't worry. ;)
