### ISSUE TITLE
Unable to Login with Laravel Socialite using Google+

### ISSUE THREAD

**Issue by brunowerneck** [laravel/framework#15769]
- Laravel Version: 5.3.9
- PHP Version: default homestead 0.5.0
- Database Driver & Version: default homestead 0.5.0

### Description:

Everything is configured as it should, Facebook login works fine, but Google+ login is failing saying my scope is invalid:

![image](https://cloud.githubusercontent.com/assets/1532646/19125165/65c6de98-8b0c-11e6-8b0e-247b22179ba7.png)

If I comment line 23 in the file Laravel\Socialite\Two\GoogleProvider, then it works perferctly:

![image](https://cloud.githubusercontent.com/assets/1532646/19125225/a35fc3f0-8b0c-11e6-926d-a9e88f3167a4.png)

![image](https://cloud.githubusercontent.com/assets/1532646/19125270/c8992ac6-8b0c-11e6-8957-ae3d1dadb798.png)

![image](https://cloud.githubusercontent.com/assets/1532646/19125296/f13011de-8b0c-11e6-9e7a-dc5e862a20d3.png)

### Steps To Reproduce:
Create a new Laravel application, setup Socialite to authenticate with your Google+ API  credentials and try to login. 

### Note
I'm sorry for posting this issue here. I didn't find where to post this issue in laravel/socialite repository

**Comment by dwightwatson** [comment]
Did you edit that file yourself? [The current version of the class doesn't have that scope](https://github.com/laravel/socialite/blob/2.0/src/Two/GoogleProvider.php).

Pretty clear that the `profile.vue` scope doesn't exist. It's likely a typo of `view`, but even then I [can't find it in the list of Google OAuth scopes](https://developers.google.com/identity/protocols/googlescopes).
