### ISSUE TITLE
Laravel 5.0 queue memory leak

### ISSUE THREAD

**Issue by hakobsharabkhanyan** [laravel/framework#15765]
- Laravel Version: 5.0.35
- PHP Version: 5.5.33

### Description:
Hi . I am running queues with beanstalked and facing some strange trouble .
After the job finished, its not freeing memory .
Here is my supervisord configuration 
[program:laravel-project-queue]
command=php /var/www/html/project/artisan queue:work --daemon
numprocs=1
autostart=true
autorestart=true

### Steps To Reproduce:
The queue is being called with artisan.
\Artisan::queue('isps:prepare', ['--immediately' => true]);

**Comment by shakisha** [comment]
i have got this problem too, on a similar configuration with beanstalked

**Comment by themsaid** [comment]
@hakobsharabkhanyan will need more details about the problem and maybe something that helps us replicate the problem on a fresh laravel app.

Please not that 5.0 is no longer supported, either use 5.1 or 5.3

**Comment by hakobsharabkhanyan** [comment]
@themsaid Thanks for reply . Actually at this moment my only clue that it can be connected because i am calling Artisan::queue from code . I will move this to the standard queue and try this way . 
Because all other things are standard, there is nothing special . I put log at the end of the function, to be sure its reaching the end and log worked . 
Thanks

**Comment by sisve** [comment]
When you say that memory is not freed; I presume you're getting a "Fatal error: Allowed memory size of ### bytes exhausted (tried to allocate ## bytes)". Correct me if I'm wrong.

A fix may be to check what your memory limit is, and executing your queue worker with `--memory=64` so that it will be automatically terminated once it allocated 64 Mb data. (Instead of your code fatally erroring out when it reaches 128 Mb)

Another simpler fix would be to stop using `--daemon`. PHP isn't meant for long-running tasks.

> There’s several issues that just make PHP the wrong tool for this. Remember, PHP will die, no matter how hard you try. First and foremost, there’s the issue of memory leaks. PHP never cared to free memory once it’s not used anymore, because everything will be freed at the end – by dying. In a continually-running process, that will slowly keep increasing the allocated memory (which is, in fact, wasted memory), until reaching PHP’s memory_limit value and killing your process without a warning.

Quote from https://software-gunslinger.tumblr.com/post/47131406821/php-is-meant-to-die

**Comment by GrahamCampbell** [comment]
We expect it to leak memory. That's why we have the option to restart after memory usage goes over a threshold.

**Comment by hakobsharabkhanyan** [comment]
@GrahamCampbell what about creating a new driver for queues - fork . It will solve this problem , yes?

**Comment by sisve** [comment]
@hakobsharabkhanyan what memory should be freed, but isn't? Do you have an actual problem, or just reporting an observation?

**Comment by hakobsharabkhanyan** [comment]
@sisve Yes its actual problem .
I have a long running job that can take up to 15-20 minutes . I have configured queues with supervisord .
Job is being pushed when i am uploading the file . Before uploading the file RAM usage is 200mb . During the process its going up to 500mb (overall system RAM usage) . Then when the Job is being finished , the memory is staying about 500mb . I tried also to manually unset variables, but was not much helpful . Now i put Artisan::queue('queue:restart'); before return in my job class .
\Artisan::queue('queue:restart');
return;

This way its working fine, but i am not sure if its a good approach .

Also note that i am not pushing command to queue manually . I have an artisan command and i am calling from code Artisan::queue('isps:prepare', ['--immediately' => true]);

Thanks

**Comment by lamboap** [comment]
@hakobsharabkhanyan seeing similar behavior.  Was your solve just to add \Artisan::queue('queue:restart') . to your job class in the handle method?

**Comment by hakobsharabkhanyan** [comment]
@lamboap Yes it was the solution too . But in my case i just created the job as artisan command and manually forked the process .
Something like this - exec('php /rootproject/artisan command');
Actually you can also just put maximum RAM limit and queue will auto restart if after finishing the RAM usage is more than your configured value .

**Comment by NikoNar** [comment]
Hi, I am getting the same problem when trying to run the queue:work .  I'm using QUEUE_CONNECTION=database . 
Any idea how I can solve this problem?
