### ISSUE TITLE
[4.2] Session variables not saved when using JSON response

### ISSUE THREAD

**Issue by tuimz** [laravel/framework#15763]
- Laravel Version: 4.2.19
- PHP Version:  5.6.15

Storing session variables are not saved when returning JSON responses. To reproduce:

```
public function setSession(){
    \Session::put('test', 123);
    return \Response::json(['message' => 'Saved session']);
}
```

Call this function in an AJAX request.

On the next request (after the AJAX has finished) `dd(\Session::all())` shows nothing stored in the session. However if I change the function to this:

````
public function setSession(){
    \Session::put('test', 123);
    return \Redirect::to('/');
}
```

And check the session variables after that call has finished, the variable is stored.

Perhaps it is related to #10331 but I am using the 'native' session driver, and a different Laravel version.

**Comment by GrahamCampbell** [comment]
Sorry, Laravel 4.2 is not supported.
