### ISSUE TITLE
[5.2] Aggregate Function sum()  inconsistent return types

### ISSUE THREAD

**Issue by shockgonewild** [laravel/framework#15762]
- Laravel Version: 5.2.45

### Description:
As seen on this [SO-Question](http://stackoverflow.com/questions/39844699/laravel-5-2-43-vs-5-2-45-eloquent-sum-returns-null-instead-of-0l)  The return value for the sum() aggregate method changed from 0 to NULL in case no database entry is found. 

As this could be a breaking change for some apps I think either the documentation should be updated or the return types should be fixed to match previous versions.

**Comment by srmklive** [comment]
Laravel 5.2 is officially not supported anymore.

**Comment by GrahamCampbell** [comment]
We changed it, but then people complained it was breaking, so that change was reverted.

**Comment by GrahamCampbell** [comment]
We made the breaking change in 5.3

**Comment by shockgonewild** [comment]
Hmm well... sad for the people wo started projects, while you had changed it. ( Now the revert is breaking for them ).

**Comment by GrahamCampbell** [comment]
Yeh, not ideal I know. Sorry.
