### ISSUE TITLE
[5.*]Session Persistance Issues

### ISSUE THREAD

**Issue by qiuyin** [laravel/framework#15760]
- Laravel Version: 5.1, 5.2, 5.3

### Description:
If a request is issued enough fast right after the previous response is received, the session data that was set in the previous request can not be accessed.(can't log in, can't log out etc).
The reason is persisting session data in terminate(this will run after response is sent!), but redirection will probably be sent to server before the previous session is saved.

https://github.com/laravel/framework/blob/5.3/src/Illuminate/Session/Middleware/StartSession.php#L85

One and a half years have been past, [this issue](https://github.com/laravel/framework/issues/8172) is not solved yet. The worst is that the comment from @yoramdelangen is neglected.

**Comment by themsaid** [comment]
@qiuyin the issue you pointed at was closed due to zero progress made, if you can please share easy steps to reproduce the issue maybe we can fix it. Without being able to replicate it'll always be a nofix.

**Comment by qiuyin** [comment]
@themsaid 

The issue happens only when the next request is faster than session saving in **terminate** function.
so it is hard to reproduce by a normal approach. But I have a trick that let the **terminate** function slow down by adding **sleep(2)** in **terminate** function. If you do this, the problems like can't log in issue, can't logout issue, token mismatch issue will happen frequently.

**Comment by GrahamCampbell** [comment]
Probably due to other requests being sent at the same time and overriding the session changes.

**Comment by qiuyin** [comment]
"Probably" what a awesome word!!

**Comment by sisve** [comment]
This is a known issue. Laravel does not support concurrent changes to the same session. https://github.com/laravel/framework/issues/14385
