### ISSUE TITLE
Construct's method controller can't to access the logged user informations

### ISSUE THREAD

**Issue by urameshibr** [laravel/framework#15771]
- Laravel Version: 5.3.?
- PHP Version: 7
- Database Driver & Version:

### Description:
On __construct method from controller i can't to access the logged user informations, only in controller methods...

### Steps To Reproduce:
any Controller

```
public function __construct(){
    dd( auth()->user() )
}
```

**Comment by bobbybouwmann** [comment]
See the upgrade guide under the section Controller

> In previous versions of Laravel, you could access session variables or the authenticated user in your controller's constructor. This was never intended to be an explicit feature of the framework. In Laravel 5.3, you can't access the session or authenticated user in your controller's constructor because the middleware has not run yet.
> As an alternative, you may define a Closure based middleware directly in your controller's constructor. Before using this feature, make sure that your application is running Laravel 5.3.4 or above:

```
public function __construct()
{
    $this->middleware(function ($request, $next) {
        $this->projects = Auth::user()->projects;

        return $next($request);
    });
}
```

https://laravel.com/docs/5.3/upgrade

**Comment by urameshibr** [comment]
Oh, nice, thanks @bobbybouwmann I was migrating from 5.1 to 5.3, i will to read with more calm the upgrades, thank you so much.

**Comment by bobbybouwmann** [comment]
@urameshibr No problem ;)
