### ISSUE TITLE
Unspecified use of a contract in Laravel Validation

### ISSUE THREAD

**Issue by NoMan2000** [laravel/framework#15774]
Laravel 5.3.16,
PHP 7.0.11
DB MySQL 5.7 

### Description:

Laravel throws an error stating:  Call to undefined method cellControl\Translations\TranslationFactory::get(), which is an implementation of Symfony's TranslatorInterface.

    @param  \Symfony\Component\Translation\TranslatorInterface  $translator

There is no method called "get" on the TranslatorInterace, but Illuminate/Validation/Validator:2245 has the following method call:

    $line = Arr::get(
                $this->translator->get('validation.attributes'),
                $expectedAttributeName
            );

So this throws a fatal exception. 

### Steps To Reproduce:

Validate any field which Laravel does not know about.  When it looks at the customAttributes, it will throw an error.

**Comment by GrahamCampbell** [comment]
> So this throws a fatal exception.

You mean, you get a warning from your IDE?

**Comment by GrahamCampbell** [comment]
This was addressed in L5.4 actually, since our the 5.3 system is substandard due to it usiung methods not guarenteed to exist in custom implementations. I guess this can only be considered a but in those implementations, where the requirements are only softly hinted by laravel.

**Comment by NoMan2000** [comment]
" Call to undefined method cellControl\Translations\TranslationFactory::get(), which is an implementation of Symfony's TranslatorInterface."

Your second answer makes sense, but your first one, no.  That's in the realm of "Seriously dude?" 

I mean it throws a fatal exception because when you try to use a method that isn't defined, it's an Exception.  

If the property translator is supposed to have a method, then there needs to be a Laravel Contract/Interface that extends the Interface from Symfony and makes sure the method and return type are explicitly known.  Else revert it to something standard that's part of Symfony's interface.

The older code is standard to the interface using the method trans:

    $key = "validation.attributes.{$expectedAttributeName}";

            // We allow for the developer to specify language lines for each of the
            // attributes allowing for more displayable counterparts of each of
            // the attributes. This provides the ability for simple formats.
            if (($line = $this->translator->trans($key)) !== $key) {
                return $line;
            }

That doesn't throw an error because the method trans is part of the TranslatorInterface.  Which brings up the question why'd you close this?  It's a bug.

Either update the class to the 5.4 style, revert it to the older one that's using a part of the defined Interface, rewrite it to fix/update whatever issue is attached to that particular change, or mark it as won't fix with the message still open so other people won't wonder why they're suddenly getting exceptions.

**Comment by karvannan-thi** [comment]
Laravel 5.3.16,
PHP 5.6.23
DB MySQL 5.7
It throw fatal error after composer update in older version work fine.

<b>Fatal error</b>:  Call to undefined method Symfony\Component\Translation\Translator::get() in <b>/../vendor/illuminate/validation/Validator.php</b> on line <b>2246</b><br />
