### ISSUE TITLE
orderBy relationship?

### ISSUE THREAD

**Issue by g5122053** [laravel/framework#15775]
Here's how I currently order by a relationship table:

```
$users = User::join('stats', 'stats.user_id', '=', 'users.id')
    ->orderBy('stats.likes', 'DESC')
    ->get();
```

Is there no other way to `orderBy` a relationship? I have the following relationship set in my `User.php`:

```
public function stats()
{
    return $this->hasOne('App\Stat');
}
```

**Comment by themsaid** [comment]
as for myself I'd use `join`, please ask on the forums as this repo is for bug reporting only.
