### ISSUE TITLE
Automatic dependency injection support notification class

### ISSUE THREAD

**Issue by chris-rs** [laravel/framework#15781]
- Laravel Version: 5.3.16
- PHP Version: 7.0.8-2
- Database Driver & Version: MySQL 5.0.12-dev

During upgrading my old mailjobs to the brand new notification system I discovered that notification does not support automatic dependency injection (in the constructor).
Although custom classes like services/repositories can be manually injected by using make and resolve helper, it would be cleaner and more consistent if dependencies can be automatically resolved by type-hints (like controllers, events, etc.).
Sometimes you need to use services/repositories to enrich the notification before sending.

Reproduction (for clarity):
- Create Notification class (by using artisan)
- Try to inject a dependency in the constructor like `public function __construct(Service $service)`

**Comment by themsaid** [comment]
Because you call the notification from code yourself

`$user->notify(new NotfiicationClass())`;

Since you create the instance not the container there's no way we can inject dependencies, you'll need to pass them while creating the instance.
