### ISSUE TITLE
[5.3] Notification gets sent out to User N times

### ISSUE THREAD

**Issue by lucadegasperi** [laravel/framework#15787]
After this PR #15681 , If I implement the ```ShouldQueue``` interface on my notifications, the notification gets sent out N times to each ```Notifiable``` object in the collection where N is the number of ```Notifiable``` objects.

Any clue what the problem might be? I'm sending the notification by calling the ```Notification::send()``` facade.

If I cycle through the ```Notifiable``` objects one by one and call the ```notify()``` method, the correct number of notifications gets sent out.

**Comment by themsaid** [comment]
Thank you for the fix: https://github.com/laravel/framework/pull/15789
