### ISSUE TITLE
Event dispatcher doesn't recognise abstract classes

### ISSUE THREAD

**Issue by paulschwarz** [laravel/framework#15792]
- Laravel Version: 5.3

### Description:
An abstract class registered in the listeners in EventServiceProvider are not picked up by the dispatcher.

### Steps To Reproduce:
Examples in tests in [pull request](https://github.com/laravel/framework/pull/15793).

**Comment by GrahamCampbell** [comment]
Event listeners cannot listen for events that extend a class. Only the precise class name.

**Comment by henrypenny** [comment]
Shouldn't this be re-opened as a feature request?

**Comment by devcircus** [comment]
Feature requests go to laravel/internals
