### ISSUE TITLE
Mail config for developing and testing: "Always CC/BCC" is missing

### ISSUE THREAD

**Issue by parusel** [laravel/framework#15803]
Regarding Laravel v5.1:

For testing, I always set the mail config "to" array, so that all emails that are sent, will be send to my email:

```
'to' => [
   'address' => 'text@example.org',
   'name' => 'Adam'
],
```

But what about CC and BCC? Sometimes we have to validate with real customers data and they have CC mail addresses set. I have expected, that when I am using this mail configuration, that **all** mails will only be sent to this address. But that is not the case - mails to CC are still send to the given address. Same applies to BCC addresses.

It would be great if **all** mails are only send to the given address in mail config, or that it is possible to set another configuration for CC and BCC.

Thank you!

**Comment by driade** [comment]
Hello, good night.

When you say "testing" I suppose you mean manually test your application, maybe in the browser, not real "tests", isn't it?

I'd suggest you using the package https://packagist.org/packages/themsaid/laravel-mail-preview by @themsaid . It will help you to debug the mails your application sends, writing them down to your hard drive into a folder.

If you mean by "testing" real tests I'd suggest using "mailcatcher" (https://laracasts.com/lessons/testing-email-in-laravel), or mocking the Mail object.

Hope this helps.

**Comment by parusel** [comment]
Hi @driade,

yes, by "testing" I meant testing it in the browser on my local machine, not a test like PHPUnit or something.

Thank you, I will take a look at the suggested links!

But I would prefer to set a "cc" and "bcc" value in the mail config array, just like I can do so with "to". This is a great feature, but useless, if my system also sends mails to cc/bcc.
