### ISSUE TITLE
Background process

### ISSUE THREAD

**Issue by socieboy** [laravel/framework#15806]
Is currently a way to fire a shell process on background, no queue... execute right in the moment get the process id and check the status if is running and kill it on the future?

**Comment by spyric** [comment]
You might want to use something like this package: http://symfony.com/doc/current/components/process.html

**Comment by socieboy** [comment]
@spyric thanks... would be cool to have something in Laravel like
```
$schedule->inBackground(DoSomething::class);
```
without have to wait the end of the process.

**Comment by GrahamCampbell** [comment]
Feel free to discuss on the forums.

**Comment by socieboy** [comment]
@GrahamCampbell well, if you can tell me the official forum of Laravel i will.
