### ISSUE TITLE
Login is not working when using custom guard and it's using the same driver and provider from 'web' guard

### ISSUE THREAD

**Issue by elitechance** [laravel/framework#15810]
- Laravel Version: 5.3.17
- PHP Version: 5.6.19
- Database Driver & Version: MySql 5.6.27

### Description:
Login is not working when using custom guard and it's using the same driver and provider from *web* guard

### Steps To Reproduce:
1. From a new project ($ laravel new sample-project), install default auth (~sample-project $ php artisan make:auth; php artisan migrate)
2. in config/auth.php add custom guard

~~~
    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
        ],

        'custom' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
    ],
~~~

3. In app/Http/Controllers/Auth/LoginController.php add

~~~
    protected function guard() {
        return Auth::guard('custom');
    }
~~~

Now login will not work even with valid credentials.  You will be redirected back to login page.

**Comment by seanmangar** [comment]
Hey elitechance, have you tried this: https://laravel.com/docs/5.3/authentication#adding-custom-guards?

**Comment by elitechance** [comment]
@seanmangar Thanks for the feedback.  Yes i saw that, but right now i want to add customization slowly and see if things will work using the same driver and provider. Because when i change my override guard function in LoginController and set it like the one below, it works.

~~~
   // This works
    protected function guard() {
        return Auth::guard('web');
    }
~~~

~~~
   //  Even if I'm using the same driver and provider, it doesn't work.
    protected function guard() {
        return Auth::guard('custom');
    }
~~~

Any reason why?

**Comment by srmklive** [comment]
My suggestion would be that you use the global helper like this `auth('custom')`

**Comment by jaketoolson** [comment]
Perhaps "custom" as the name is goofing up, try a different name to confirm your integration is working correctly.

**Comment by elitechance** [comment]
**[SOLVED]**

You need to set default driver in _config/auth.php_ to custom
~~~
    'defaults' => [
        'guard' => 'custom',
        'passwords' => 'users',
    ],
~~~
