### ISSUE TITLE
Eloquent relationship method named "size" bug.

### ISSUE THREAD

**Issue by jaketoolson** [laravel/framework#15814]
- Laravel Version: 5.2.31
- PHP Version: 7.0.10
- Database Driver & Version: MariaDB 10.1.17-MariaDB-1~trusty

### Description:
Created a belongsTo relationship called ```size``` and it is returning null when called as property, however when calling as function, builder object is returned.

### Steps To Reproduce:
```
class Product extends Eloquent {

  //

  function size() 
  {
     return $this->belongsTo(InventorySizes::class, 'inventory_size_id');
  }
}
```

```
$product->size // returns null
$product->size()->first() // returns Size Model as expected
```

**Comment by seanmangar** [comment]
Hey @jaketoolson, could it be because you have a column on the table with the same name as the property?

**Comment by jaketoolson** [comment]
@seanmangar son of a... that was it :o I was going crazy too, checking everything, even my tests yielded the same "bug".  Sigh those damn magic properties ;)
