### ISSUE TITLE
Query Builder changes behavior

### ISSUE THREAD

**Issue by pilot911** [laravel/framework#15812]
- Laravel Version: 5.3.15
- PHP Version: 7
- Database Driver & Version: Mysql 5.5.49-0+deb8u1

### Description:
In Laravel 5.2 integer values in query was quoted.
In Laravel 5.3 integer values in query wont quoted.

### Steps To Reproduce:

Create table with fields

ID : integer
CODE: string

Make query:
```
\App\Type::where('code', 0)->firstOrFail();
```
You'll get all rows in table. That's becouse mysql casts values of string-field "CODE" to integer and compares 0=0.

Really, Laravel should quote all values in query builder besides smth like IN (.....)

**Comment by themsaid** [comment]
This is an issue with the MySQL not laravel, in 5.3 laravel uses the right binding type when querying, before we were using only `PARAM_STR` for all types which was problematic and wrong.

**Comment by pilot911** [comment]
Okey, thanks.
