### ISSUE TITLE
Sending Passport to a separate database connection

### ISSUE THREAD

**Issue by dreferreira** [laravel/framework#15818]
- Laravel Version: 5.3.15
- PHP Version: 7.02
- Database Driver & Version: libmysql - mysqlnd 5.0.12

### Description:
In laravel 5.2.45 I was able to send my oauth 2.0 server to a completely different database and also have JWT running properly. With laravel 5.3 I'm not sure how I can separate the passport out from the rest of the core tables and still keep the JWT functionality. Any guidance is appreciated. Thanks!

Just for further detailed description, I've made a post on StackOverflow about this topic and a few other issues I've come across in what I'm trying to accomplish:

http://stackoverflow.com/questions/39933347/laravel-5-3-passport-migrations-modifying-the-default-users-table

**Comment by GrahamCampbell** [comment]
Sorry, we don't process feature requests or questions on our issue tracker.
