### ISSUE TITLE
service providers called twice

### ISSUE THREAD

**Issue by gdinko** [laravel/framework#15825]
- Laravel Version: 5.2.45
- PHP Version: 5.6
- Database Driver & Version:

### Description:
1. Create View
2. Include another view with @include
3. in included view user asset() or url() helper function
4. in AppServiceProvider boot method use log (Log::info(__CLASS__ . __METHOD__);), to log how many time the boot method is executed | do this with any other service provider
5. view the log logs/laravel.log -> method called 2 times

All service providers is are called twice

This is when you are rendering list of product.

**Comment by arasmit2453** [comment]
You might have a redirect that is being done?. Did you check that?.

Include this in the log:         \Request::fullUrl(); maybe there you can find what is triggering that behaviour

**Comment by sisve** [comment]
Could you show a minimal included view that repeats this issue? The asset()/url() function generates urls for separate queries. It sounds like you issue a second request (image, ajax, ...), where this behavior is normal.

**Comment by gdinko** [comment]
Thanks for the help. Yes, this was the problem second request. If there is a resource (image) that is not available, new request is performed and 404 is returned. So X missing resources X requests. 
Conclusion: before make asset() call, check if the resource is available.
