### ISSUE TITLE
Laravel doesn't allow third party packages to implement wildcards in validator parameters

### ISSUE THREAD

**Issue by amitailanciano** [laravel/framework#15839]
- Laravel Version: 5.2.45
- PHP Version: 7.0.2
- Database Driver & Version: N/A

### Description:

According to this popular laravel package: https://github.com/Propaganistas/Laravel-Phone

Laravel doesn't allow third party packages to implement wildcards in validator parameters, is there a reason for this? It would be great if the author of that package was able to implement this feature.

Here's the issue I posted over there for reference: https://github.com/Propaganistas/Laravel-Phone/issues/34

### Steps To Reproduce:

N/A

**Comment by GrahamCampbell** [comment]
Sorry, we don't process feature requests on our issue tracker. Feel free to send a PR.

**Comment by amitailanciano** [comment]
I posted the issue because I felt like this was by design for a reason and wanted to understand why, would a PR that would allow this actually be reviewed and possibly accepted?

**Comment by Propaganistas** [comment]
@amitailanciano I created a PR for this, but it was rejected...

https://github.com/laravel/framework/pull/14445

**Comment by amitailanciano** [comment]
https://m.reddit.com/r/laravel/comments/4ud6sq/on_contributing_to_laravel/

This was posted to Reddit by @taylorotwell the day after your pull request was rejected with no explanation -- in combination with how quickly this issue was closed without any meaningful response, I can't help but feel like nothing has changed
