### ISSUE TITLE
Logical Error between route implicit model binding & authentication

### ISSUE THREAD

**Issue by Omranic** [laravel/framework#15835]
This is relevant to the **@laravel/laravel** 5.3.x application, not the framework itself..

### Description:
If you're using route implicit model bindings, for a secured area behind authentication (using both `web` & `auth` middleware), in such case Laravel tries to fetch that bound model from DB first before checking permissions, whether the user already logged in or not, which I believe is a logical error in the flow of that process. We must check if user have permissions or not first, before even hitting the DB, right? Or am I missing something?

The other way is to put `auth` middleware before `web` middleware group, in which case it won’t work since it requires sessions, and sessions are instantiated within the `web` middleware group..

So, what do you think?

**Comment by GrahamCampbell** [comment]
You can put the binding middleware wherever you want. That's why we changed it to be implemented a middleware so you can do auth first.
