### ISSUE TITLE
Can't specify a timestamp format for the relationship intermediate table.

### ISSUE THREAD

**Issue by Abel94** [laravel/framework#15833]
- Laravel Version: 5.3

#### Relationship intermediate table
```php
Schema::create('topic_user', function (Blueprint $table) {
    $table->increments('id');
    $table->integer('user_id')->index()->unsigned();
    $table->integer('topic_id')->index()->unsigned();
    $table->integer('created_at');
    $table->integer('updated_at');

    $table->unique(['user_id', 'topic_id']);
});
```

#### Base Model  
```php
use Illuminate\Database\Eloquent\Model;

class Base extends Model
{
    protected $dateFormat = 'U';
}
```

#### TopicUser Model

```php
class TopicUser extends Base
{
    public function topic()
    {
        return $this->belongsTo(Topic::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}
```

After the data was added, it was found that the field type submitted by laravel was still in the string format, not the timestamp.

#### Exmple data
id	user_id	topic_id	created_at	updated_at
1	1	1	2016	2016
2	1	2	2016	2016
3	1	3	2016	2016
4	1	4	2016	2016
5	1	5	2016	2016
6	1	6	2016	2016
7	1	7	2016	2016

**Comment by srmklive** [comment]
You have wrong format for the `created_at` & `updated_at`. Change it to timestamp like:
```
$table->timestamp('created_at');
$table->timestamp('updated_at');
```

**Comment by Abel94** [comment]
@srmklive But I would like to set the dateFormat to the timestamp to integer type of number. This is valid in the topic table. I suspect that laravel may not be able to read the Eloquent model when reading the intermediate table data.
