### ISSUE TITLE
lumen Session store not set on requst

### ISSUE THREAD

**Issue by rdluck** [laravel/framework#15840]
- Laravel Version: #.
- PHP Version:
- Database Driver & Version:

### Description:
I used Lumen 5.2 version,
in .env file ,the SESSION_DRIVER set file ,SESSION_DRIVER=file
in app/Http/routes.php file ,$app->get("/setSession","DemoController@SetSession");
in app/http/Controller/DemoController file the code is 
  public function SetSession(Request $request){
        $request->session()->put('key', 'value');
    }
where request, the error is 
Whoops, looks like something went wrong.

1/1
RuntimeException in Request.php line 870:
Session store not set on request.
this problem how to repair
 Steps To Reproduce:

**Comment by bobbybouwmann** [comment]
>Lumen 5.2 represents a more decided shift towards focusing on stateless APIs. Therefore, sessions have been removed from the framework. If you would like to use these features, you should upgrade your Lumen 5.1 application to Laravel 5.2.
> https://lumen.laravel.com/docs/5.3/upgrade#upgrade-5.2.0

It sounds like you need Laravel instead ;)
