### ISSUE TITLE
[4.2] Routing broken when streaming to iOS10

### ISSUE THREAD

**Issue by web-engineer** [laravel/framework#15845]
- Laravel Version: 4.2.0
- PHP Version:5.6

### Description:
I have a route that responds to a video request from a video tag in a web page, this works fine in iOS9, on the desktop in all browsers, no problem at all - based on http://codesamplez.com/programming/php-html5-video-streaming-tutorial

### Steps To Reproduce:

Just trying to view the video in the page - it fails to play when its routed via laravel. Direct linking to a PHP script *does* work, however only when laravel isn't handling the route.

What I've discovered is that the route is just not being fired when the request is made, I've tried changing this to Route::any but it makes no difference.

I suspect that iOS 10 has sent the request in an odd way but I've yet to work out whats going on.

For example -

Address  http://DOMAIN/media/play/b32b26c6a839a5033a59b03c0c0d3495ecaccd2a/1465917545

Route::any('media/play/{checksum}/{modified}', array('uses' => 'MediaController@mp4'));

The above route doesn't get fired when I view from iOS10 - the address is as per in the page, I've got logging in the method and it's simply not fired.

Any pointers greatly appreciated!

**Comment by web-engineer** [comment]
OK - further info... If I do a check in the routes file for the exact URL and put the videostream class inside the routes file and trigger the stream it works in iOS10. This proves the only issue here is why the route is being ignored otherwise - to be clear this works on all other devices/browsers we've tested...

**Comment by GrahamCampbell** [comment]
Sorry, only 5.1 and 5.3 are supported.

**Comment by web-engineer** [comment]
Will try and reproduce in 5, unfortunately this project is in 4 but we have another on 5 to check.

**Comment by web-engineer** [comment]
I'm now certain this problem is due to the fact that the request has some seek information being sent in the headers by the browser and this is not understood by the 4.2 laravel routing classes. We've had to use a work around for now but its not great - we will test in 5 soon to see if this is a problem in the current release too.
