### ISSUE TITLE
Incomplete helper method event() in Illuminate/Foundation

### ISSUE THREAD

**Issue by thehelvetian** [laravel/framework#15843]
- Laravel Version: 5.3.18
- PHP Version: 7
- Database Driver & Version: MySQL

### Description:

It seems that there is an incomplete method `events()` at `Illuminate/Foundation/helpers.php`. 

Code from https://github.com/laravel/framework/blob/5e92b0527957eee36b48abc0ddc3f5bbb4b03a03/src/Illuminate/Foundation/helpers.php#L475-L478

```
function event(...$args)
{
    return app('events')->fire(...$args);
}
```

Should probably be:

```
function event($event, $payload = [], $halt = false)
{
    return app('events')->fire($event, $payload, $halt);
}
```

**Comment by GrahamCampbell** [comment]
How do you mean that it's incomplete? It takes n arguments and then unpacks them?

**Comment by thehelvetian** [comment]
I swear, earlier today, this was throwing an error when launching:
`php artisan queue:work redis --sleep=3 --tries=3` via `supervisord`. 

Error was: `Parse error: parse error, expecting `'&'' or `"variable (T_VARIABLE)"' in vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 475`

Now it doesn't anymore and runs just fine. ¯\_(ツ)_/¯
