### ISSUE TITLE
Migration error using SQL Server

### ISSUE THREAD

**Issue by Ridlsan** [laravel/framework#15841]
- Laravel Version: 5.3.11
- PHP Version: 7
- Database Driver & Version: SQL Server
### Description:

I am using schemas in my project, so migration down code looks like: 
`Schema::dropIfExists('mdm.tbl_group_user');`
transforms into 
`'if exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = \''.$blueprint->getTable().'\') drop table ['.$blueprint->getTable().']'`

But in 'INFORMATION_SCHEMA.TABLES' schema and table name are separate columns, so this code fails and not droping anything

**Comment by themsaid** [comment]
> But in 'INFORMATION_SCHEMA.TABLES' schema and table name are separate columns, so this code fails and not droping anything

What do you mean by this?

**Comment by themsaid** [comment]
nevermind, I got your point.

**Comment by themsaid** [comment]
I think something is wrong, this sql doesn't look right for sql server, I think this should be the query:

```
select * from sysobjects where type = 'U' and name = ?
```

no?

**Comment by themsaid** [comment]
ping @Ridlsan

**Comment by Ridlsan** [comment]
No, it's not working either. Because in sysobjects tables are not with schema
I think php code should be rewritten to support schemas.
I think splitting by dot would be good enough.

**Comment by Ridlsan** [comment]
No, it's not working either. Because in sysobjects tables are not with schema
I think php code should be rewritten to support schemas.
I think splitting by dot would be good enough.

**Comment by themsaid** [comment]
Can you please open a PR with a suggested fix?

**Comment by Ridlsan** [comment]
Ehm... no... dont know what is it ?

**Comment by PetarDambovaliev** [comment]
What is your version of SQL Server ?

**Comment by Ridlsan** [comment]
2012

**Comment by PetarDambovaliev** [comment]
The Information_Schema views only show objects that are compatible with the SQL-92 standard. This means there is no information schema view for even quite basic constructs such as indexes (These are not defined in the standard and are left as implementation details.) Let alone any SQL Server proprietary features.

**Comment by vlakoff** [comment]
Could you please test this code?
(just temporarily modify your [SqlServerGrammar.php](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Schema/Grammars/SqlServerGrammar.php) file in /vendor)
```php
    public function compileDropIfExists(Blueprint $blueprint, Fluent $command)
    {
        $parts = explode('.', $blueprint->getTable());

        $where = 'TABLE_NAME = \''.$parts[0].'\'';

        if (isset($parts[1]) {
            $where .= ' and TABLE_SCHEMA = \''.$parts[1].'\'';
        }

        return 'if exists (select * from INFORMATION_SCHEMA.TABLES where '.$where.') drop table ['.$blueprint->getTable().']';
    }
```

**Comment by vlakoff** [comment]
Edited code snippet.

**Comment by vlakoff** [comment]
Just to mention SQL Server supports creating tables using the syntax `CREATE TABLE schema.table` (if the schema already exists).

**Comment by vlakoff** [comment]
I have dug a bit into this, and you really shouldn't use the syntax `someMethod('schema.table')` as it is not expected to work.

**Comment by vlakoff** [comment]
So, considering the `schema.table` syntax happens to work in some cases, but only by luck and shouldn't be considered as supported, shall this issue be closed?
