### ISSUE TITLE
factory()->make() should not establish a connection to the database

### ISSUE THREAD

**Issue by KonstantinKolodnitsky** [laravel/framework#15844]
- Laravel Version: 5.2
- PHP Version: 7.0
- Database Driver & Version: mysql 5.5.5

### Description:
In my tests I want to be sure that no tests are touching the database. To check that I disabled the database by putting incorrect password. All is fine until I use factory() helper. It throws and error

    [PDOException] SQLSTATE[HY000] [1045] Access denied for user 'myproject'@'172.18.0.4' (using password: YES)

I believe it shouldn't go to db. Is there any reason for that?
Or maybe it's possible to disable db connection? It'd be helpful to have a trait kind of 'DisableDatabaseConnection' so I don't have to manually disable it.

### Steps To Reproduce:
Disable the database(I've put incorrect password).
Anywhere try to make a class with factory()->make() helper method.

**Comment by srmklive** [comment]
Why would you want `factory` to not establish connection to the database.

**Comment by KonstantinKolodnitsky** [comment]
Because I don't want to save an entity to the database, but MAKE a new instance. That's the difference between create() and make() methods.
Do why so I need a connection at all?

**Comment by srmklive** [comment]
Model factories allow you to generate dummy data for your database models. Yes you need to setup database connection to get it working.

**Comment by browner12** [comment]
model factories also have other uses, including in tests.

In theory, it makes sense to me to not require the database connection if just calling the `make` command. from a technical side, i'm not sure if there are limitations to this.

**Comment by themsaid** [comment]
That doesn't seem to be the case in laravel 5.3, please upgrade to laravel 5.3 since 5.2 is not supported anymore.
