### ISSUE TITLE
Pagination returns an empty set when currentPage > lastPage

### ISSUE THREAD

**Issue by dannoso** [laravel/framework#15857]
- Laravel Version: 5.2.45
- PHP Version: 5.6.25
- Database Driver & Version: MYSQL 5.6.28

### Description:
In paginate when retrieving the items and a wrong current page is set (ie. currentPage > lastPage) an empty set is returned. I think setCurrentPage() should handle this since looks like an expected behavior. 

### Steps To Reproduce:
In a basic CRUD table navigate to a page near the end then click on a link that applies a scope with much less record. An empty page is returned giving the impression something is broken.

### Suggestions
I think when the current page is greater than the last page the latter should be set as current.

**Comment by sisve** [comment]
Shouldn't this be a logical check in your code, and result in either an message or a redirect to the last page? I consider it illogical if `/list?page=1337` return page 2 just because there is only two pages.

Also, clearly relevant commit: https://github.com/laravel/framework/commit/a038a521710050a92f9d53b7a32ebfc433b17b0e

**Comment by themsaid** [comment]
You can handle this in your application as suggested by @sisve, doesn't look like a bug in the framework :)

**Comment by dannoso** [comment]
Is what i've done but IMO this shouldn't be in charge of my code. As average user I expect the system to adjust and show the last page not an empty, not existing, page clearly out of bounds. 

The first time I saw it I thought my scopes don't work. I consider more illogical returning page 1337 in a 2 pages set. 
Also the mentioned commit looks like only a workaround to avoid worst issues as "weird json" is not much a detailed explanation. Plus shows that the @taylorotwell original intention was to make it work that way.

So far the only quick option to me was overriding currentPageResolver() to return lastPage instead and repeat the query. The benefit of this is that when I exit the scope I'm back to my original page 1337.

I think the class should offer a better handling of this scenario because now is confusing and not working out of the box. I would do the fix myself if I had time.

**Comment by themsaid** [comment]
You can always suggest a change by opening a PR, but please make sure your PR doesn't bring this weird JSON thing back.

**Comment by dannoso** [comment]
Thanks, I will as soon as I got spare time.
Could you tell me where I can PR? As the illuminate/pagination is readonly.

**Comment by themsaid** [comment]
PR in this repo, the illuminate repos are read only.

**Comment by dannoso** [comment]
Oki, thanks
