### ISSUE TITLE
migration UUID type error with TestCase DatabaseMigrations trait

### ISSUE THREAD

**Issue by XanManZA** [laravel/framework#15851]
- Laravel Version: 5.3.18
- PHP Version: 5.6.24
- Database Driver & Version: MySQL 5.7

### Description:
I have migrations with the `$table->uuid('id');` statement. When I run a TestCase and it uses the DatabaseMigrations trait I get the exception:
> Doctrine\DBAL\DBALException: Unknown column type "uuid" requested.

I have tried manually adding the type to DBAL in the app bootstrapping code. If I do that I get
> DBAL Type "uuid" already registered

Very confused and frustrated as I am running Unit/Integration tests and don't want to run into trouble with data down the line.

### Steps To Reproduce:
1) Create a migration that makes us of the `$table->uuid()` function on a column.
2) Create a TestCase subclass and use the DatabaseMigrations trait
3) Run the phpunit command which will output the error.

**Comment by themsaid** [comment]
Unable to replicate on a fresh laravel 5.3 installation, here's the migration:

```
class Test extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('users', function($table){
            $table->uuid('test');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('users', function($table){
            $table->dropColumn('test');
        });
    }
}
```

The test runs with no issues.

Also since it already works when you call `php artisan migration` it should work the same from tests.

**Comment by XanManZA** [comment]
Hey @themsaid 
Could you try running the same after installing Doctrine/DBAL?
The package is installed to run the `$column->change()` function on migrations.

**Comment by funerr** [comment]
Happens too when using `->change()` (DBAL)
