### ISSUE TITLE
isValid method not working

### ISSUE THREAD

**Issue by four-eyes-04-04** [laravel/framework#15854]
- Laravel Version: 5.3.15
- PHP Version: 5.6.19
- Database Driver & Version: MySQL Ver 15.1 Distrib 10.1.10-MariaDB

### Description:
`$request->file('photo')->isValid()` which is suppose to determine if there were no problems uploading the file as describe in the [documentation](https://laravel.com/docs/5.3/requests#retrieving-uploaded-files) **is not working**.

### Steps To Reproduce:
- Created a route to receive the `post request` and a controller, generated via `php artisan make:controller GuestController`, to handle the request and accepted the `request object` as a parameter
```
// Routes\web.php
Route::post('/signup', 'GuestController@signup');

// GuestController
namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use Auth;
use Session;
use Validator;

class GuestController extends Controller {
  public function post_handle_signup (Request $request) {
    // ....
  }
}
```
- Grabbed all the inputs via `$inputs = $request->all()`
```
// GuestController
public function post_handle_signup (Request $request) {
  // all inputs
  $inputs = $request->all();
}
```
- Created an associative array of rules and messages for the validator and validated the input
```
// GuestController
public function post_handle_signup (Request $request) {
  // all inputs
  $inputs = $request->all();
  // rules for the validator
  $rules = [
    // some rules....
  ];
  // validation messages
  $messages = [
    // some mesages
  ];
  // validate inputs
  $validator = Validator::make($inputs, $rules, $messages);
}
```
- I needed to validate the uploaded image file so I did a `validator->after(closure)`
```
$validator->after(function () use ($validator, $request) {
  if ($request->hasFile('uploaded_file')) {
    if (count($request->file('uploaded_file')) > 1) {
      $validator->errors()->add('uploaded_file', 'Expected only 1 file.');
    } else if (!$request->file('uploaded_file')->isValid()) {
      $validator->errors()->add('uploaded_file', An error encountered while uploading the file.');
    }
  } else {
    $validator->errors()->add('uploaded_file', 'select a file to upload');
  }
}
```
however, at this point the an error will be thrown saying `Call to a member function isValid() on array` when this is exactly how the documentation told me to do it:
```
if ($request->file('photo')->isValid()) {
    //
}
```

**Comment by jesusto** [comment]
how could you solve it?
I have the same problem
