### ISSUE TITLE
Closure based commands can't be called from code using Artisan::call

### ISSUE THREAD

**Issue by sede2** [laravel/framework#15856]
- Laravel Version: 5.3.18
- PHP Version: 7.0.4
- Database Driver & Version: none

### Description:
If you call a command from routes.console.php using Artisan::call() it throws CommandNotFoundException

### Steps To Reproduce:
Install new laravel and 

```
Route::get('/', function () {
    return Artisan::call('inspire');
});
```

**Comment by uber1337** [comment]
check the documentation:
https://laravel.com/docs/5.3/artisan#closure-commands

I think you are doing a mixing, better read above
