### ISSUE TITLE
正则\w 模板解析的问题 ！

### ISSUE THREAD

**Issue by lychao8** [laravel/framework#15862]
- Laravel Version: 5.2.*
- PHP Version: 5.6.26
- Database Driver & Version: mysql 5.6

### Description:
正则\w的问题 ， 模板解析！

### Steps To Reproduce:
有些blade模板里的语法后面跟着汉字，有的环境可以运行，有的环境下模板编译报错

阅读laravel源码发现：vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php::compileStatements 
用了\w来做正则匹配，有的环境里\w不能匹配汉字，有的环境可以匹配汉字；导致同样的代码运行结果截然不同

demo.php
```
<?php
$str = '@if(1) 1 @else 2 @endif汉字';
$callback = function($match){
    var_export($match); // 有些环境匹配了汉字，有的环境没有匹配汉字；匹配上汉字的环境发生了灾难
};
preg_replace_callback('/\B@(\w+)([ \t]*)(\( ( (?>[^()]+) | (?3) )* \))?/x', $callback, $str);  // 兼容性不好
preg_replace_callback('/\B@([a-zA-Z0-9_]+)([ \t]*)(\( ( (?>[^()]+) | (?3) )* \))?/x', $callback, $str);  // 严谨的写法
```
\w能不能匹配汉字要视你的操作系统和你的应用环境而定

\w 任意一个字母或数字或下划线，也就是 A～Z,a～z,0～9,_ 中任意一个 一般来说，是这样的，但是在某些情况下，\w也会匹配本地字符集，比如中文系统的中文，全角数字等，所以在明确要求是A～Z,a～z,0～9,_ 中的一个的时候，用[A-Za-z0-9_]，而不用\w

判定条件有两个，两个条件是互相制约的：
一是要看你的系统是什么系统，中文系统下是可以匹配汉字的 
二是要看你的应用环境，如果是在C#程序中可以匹配汉字的，在javascript或者php中不可以匹配汉字的

**Comment by themsaid** [comment]
English please :)
