### ISSUE TITLE
[5.2 Models] Cannot get value from numeric-named columns

### ISSUE THREAD

**Issue by Lemolas** [laravel/framework#15864]
- Laravel Version: 5.2
- PHP Version: 7.0.8
- Database Driver & Version: Mysql 14.14 Distrib 5.7.15

### Description:
using laravel models, I'm unable to read values from a number-named table, i opened a thread on stackoverflow with all the information needed, link is here [stackoverflow](http://stackoverflow.com/questions/39995381/get-value-from-a-number-named-column/39995450?noredirect=1#comment67269914_39995450)

### Steps To Reproduce:
Create a table with number-named columns (not all)
Create a model for that table
Try to print out a single field (e.g. $row->{'200'})

**Comment by themsaid** [comment]
just submitted a PR for a fix, but the fix will be available in laravel 5.3 only since 5.2 is not supported anymore, I advise that you start upgrading to 5.3 asap

**Comment by Lemolas** [comment]
no prob, thank you
