### ISSUE TITLE
max image size upload not working

### ISSUE THREAD

**Issue by vigneshmuthukrishnan** [laravel/framework#15861]
- Laravel Version: 5.2.

### Description:
Not working max image size upload
 
### Steps To Reproduce:
ImageController.php
====================

     <?php
    namespace App\Http\Controllers;
     use Illuminate\Http\Request;
     use App\Http\Requests;
       use Image;

      class ImageController extends Controller
      {
    public function resizeImage()
    {
    	return view('resizeImage');
    }
    public function resizeImagePost(Request $request)
    {
        $image = $request->file('image');
        $input['imagename'] = time().'.'.$image->getClientOriginalExtension();
     
        $destinationPath = public_path('/thumbnail');
        $img = Image::make($image->getRealPath());
        $img->resize(200, 200, function ($constraint) {
		    $constraint->aspectRatio();
		})->save($destinationPath.'/'.$input['imagename']);

        $destinationPath = public_path('/images');
        $image->move($destinationPath, $input['imagename']);
		
        return back()
        	->with('success','Image Upload successful')
        	->with('imageName',$input['imagename']);
       }
       }

     

======================
 resizeImage.blade.php

     <div class="container">
     <h1>Resize</h1>
     @if (count($errors) > 0)
	<div class="alert alert-danger">
		<strong>Whoops!</strong> There were some problems with your input.<br><br>
		<ul>
			@foreach ($errors->all() as $error)
				<li>{{ $error }}</li>
			@endforeach
		</ul>
	</div>
     @endif
      @if ($message = Session::get('success'))
     <div class="alert alert-success alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>	
     <strong>{{ $message }}</strong>
      </div>
      <div class="row">
	<div class="col-md-4">
		<strong>Original Image:</strong>
		<br/>
		<img src="images/{{ Session::get('imageName') }}" />
	</div>
	<div class="col-md-4">
		<strong>Thumbnail Image:</strong>
		<br/>
		<img src="thumbnail/{{ Session::get('imageName') }}" />
	</div>
       </div>
       @endif
      {!! Form::open(array('url'=>'resizeimage','method'=>'POST', 'files'=>true)) !!}
      <input type="hidden" name="_token" value="{{ csrf_token() }}">
	<div class="row">
		<div class="col-md-4">
			<br/>
			{!! Form::text('title', null,array('class' => 'form-control','placeholder'=>'Add Title')) !!}
		</div>
		<div class="col-md-12">
			<br/>
			{!! Form::file('image', array('class' => 'image')) !!}
		</div>
		<div class="col-md-12">
			<br/>
			<button type="submit" class="btn btn-success">Upload Image</button>
		</div>
	</div>
       {!! Form::close() !!}
       </div>

Route
===================
  <?php
   Route::get('resizeImage', 'ImageController@resizeImage');
   Route::post('resizeImagePost',['as'=>'resizeImagePost','uses'=>'ImageController@resizeImagePost']);

**Comment by vigneshmuthukrishnan** [comment]
Hi friends this code i have some error  and not working

**Comment by TsvetomirCh** [comment]
Maybe php.ini upload_max_filesize and post_max_size?

**Comment by themsaid** [comment]
I'm sorry but this doesn't look like a bug in the framework, not even sure what the problem you're facing is :)

**Comment by vigneshmuthukrishnan** [comment]
I will fix the php.ini  upload_max_filesize and post_max_size

**Comment by vigneshmuthukrishnan** [comment]
i will fix the php.ini

**Comment by vigneshmuthukrishnan** [comment]
Error is:
NotFoundHttpException in RouteCollection.php line 161
