### ISSUE TITLE
[5.1] backport Job onConnection to 5.1 LTS

### ISSUE THREAD

**Issue by ifduyue** [laravel/framework#15863]
Hello,

onConnection was added to 5.2 & 5.3, but not 5.1

Please consider backport onConnection to 5.1, it's inconvenient that every Job instance goes to the default queue.

**Comment by themsaid** [comment]
5.1 is open for bug fixes only not feature additions.

**Comment by ifduyue** [comment]
@themsaid this is kind of a bug

**Comment by themsaid** [comment]
How?

**Comment by ifduyue** [comment]
@themsaid In 5.1 a job instance can only goes to the default queue, no way to use another queue connection. In my opinion it's a bug, onConnection is more of a bugfix than a feature.

please consider backport onConnection to 5.1.
It's your call of course.

**Comment by ifduyue** [comment]
> 5.1 is open for bug fixes only not feature additions.

Referring to Laravel's release notes, this is not true.

![0801ba4c-5ef8-4a47-977b-7637ce5c9170](https://cloud.githubusercontent.com/assets/568900/19303267/9403781e-909a-11e6-8cd6-b90a20aeb475.png)

**Comment by themsaid** [comment]
That was before 5.2 is released, once 5.2 was release 5.1 became closed for feature additions.

**Comment by ifduyue** [comment]
Fine. Thanks for your replies.
