### ISSUE TITLE
Unexpected behaviour in Queue-> listener

### ISSUE THREAD

**Issue by PetarDambovaliev** [laravel/framework#15871]
- Laravel Version: 5.3.*
- PHP Version: 7.0.3
- Database Driver & Version:
Mysql - 5.7.15

### Description:
If you return false inside a listener, while you are running a Laravel queue, the queue just dies.

### Steps To Reproduce:
1. Create an event
2. Add a listener with a return false line
3. Start the Laravel Queue
4. Trigger the event

**Comment by taylorotwell** [comment]
Can you post the actual code needed to recreate this?

**Comment by themsaid** [comment]
@PetarDambovaliev Unable to replicate, here's my handle method:

    public function handle(TestEvent $event)
    {
        return false;
    }

**Comment by PetarDambovaliev** [comment]
@taylorotwell I will investigate this further tomorrow, the specific code is on my office  machine.

**Comment by PetarDambovaliev** [comment]
It's still unknown what exactly was the cause.
After i changed the code to return $fudgeCount ,it no longer stopped the queue.

`if ($fudgeCount < $stockFudgeMin) {
return false;
} else {
 //do stuff
}
`

**Comment by themsaid** [comment]
@PetarDambovaliev we don't have anything to look at here :) We can't replicate the issue and you seem to be unsure about how it's replicated.

Please close the issue if you think it's just a random act that doesn't exist anymore, otherwise please include correct steps to replicate.

**Comment by PetarDambovaliev** [comment]
@themsaid , yea seems best to close it.
