### ISSUE TITLE
ORM update() and increment()/decrement() can`t auto convert array to string

### ISSUE THREAD

**Issue by BlueGood** [laravel/framework#15880]
- Laravel Version: 5.3.18
- PHP Version:5.6.19
- Database Driver & Version:MySQL 5.6

### Description:
In Test Model, I set `data` is array
```
    protected $casts      = [
        'data' => 'array'
    ];
```
This is ok:
```
$item = Test::find(1);
$item->fill(['data' => ['aaa', 'bbb']])->save();
```
But this is wrong:
```
Test::where('id', '1')->update(['data' => ['aaa', 'bbb']]);
```
Error: Array to string conversion
Can`t auto convert array to string

function increment() is wrong too:
```
Test::where('id', '1')->increment('times', 1, ['data' => ['aaa', 'bbb']]);
```

**Comment by GrahamCampbell** [comment]
You can't use the update function like that. You'll need to fill and then save. Just a subtlety of the implementation.

**Comment by BlueGood** [comment]
But, if I need mass updates, just like:
```
Test::where('active', '1')-> update('times', 1, ['data' => ['aaa', 'bbb']]);
```
