### ISSUE TITLE
Template parsing  of  `\w`

### ISSUE THREAD

**Issue by lychao8** [laravel/framework#15888]
Laravel Version: 5.2.*
PHP Version: 5.6.26
Database Driver & Version: mysql 5.6
Description:

regular `\w`  bug ， Template parsing.

Steps To Reproduce:

read  laravel original code：

`vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php::compileStatements`

find that  use  `\w`  to matching ，but sometimes it cause different Result.

in some blade Template  we use like the following ：

demo.php
```
<?php
$str = '@if(1) 1 @else 2 @endif汉字';
$callback = function($match){
    var_export($match); // some ok,but some not ok
};
preg_replace_callback('/\B@(\w+)([ \t]*)(\( ( (?>[^()]+) | (?3) )* \))?/x', $callback, $str);  // bad 
Compatibility
preg_replace_callback('/\B@([a-zA-Z0-9_]+)([ \t]*)(\( ( (?>[^()]+) | (?3) )* \))?/x', $callback, $str);  // more rigorous，much better

```
`\w` can not match the Chinese characters to see your operating system and your application environment

`\w`  can match a any letters or numbers, or the underscore, which is A ~ Z, a ~ Z, 0 ~ 9, _ in any one。In general, it's like this.  But in some cases,` \w` Will match the local character set，For example, Chinese system Chinese, full digital etc, So the clear requirement is that ` A～Z,a～z,0～9,_  `  should use  `[A-Za-z0-9_] ` ，not `\w`

Decision conditions have two, two conditions are mutually restricted:
First, to see what your system is the system, the Chinese system can match the Chinese characters,
Two is to look at your application environment, if you can match the Chinese characters in the C# program, PHP or JavaScript can not match the Chinese characters

**Comment by themsaid** [comment]
@lychao8 I'm sorry but I don't understand the problem here, can you please share a sample .blade file where I can put into a fresh laravel installation and see a problematic result?

**Comment by miscbits** [comment]
The issue here I believe that for some computers the local character set isn't standard latin characters, so \w will match characters that aren't `A-Z`, `a-z`, `0-9`, or `_`. 

Likely this means you would have to not only run this blade demo, you would also have to change your computer's default character set to something like a Chinese character set. With this demo case I suppose the expected result should be that you do not match characters like `汉字` but if your default character set is Chinese it will. 

Not sure if this is really a bug though. Seems like a non-issue unless I am missing something else.

**Comment by lychao8** [comment]
I use mac system

```
MacBook Pro( Retina, 13-inch,Early 2015)
macOs Sierra 10.12
```

**Comment by lychao8** [comment]
TestController.php

```
public function getBlade()
{
        return view('index')->with('userInfo',array('nickname'=>''));
}
```

view/index.blade.php
```
<span>
    @if($userInfo)
        @if($userInfo['nickname'])
            你好
        @else
            我好
        @endif大家好
    @else
        全部客户
    @endif
</span>

```

when  access this method in the browser, cause this error:

```
FatalErrorException in f1afcce3d111fb3a871559b62819d7f520944e08.php line 8:
syntax error, unexpected 'else' (T_ELSE)

```

storage/framework/views/f1afcce3d111fb3a871559b62819d7f520944e08.php
```
<span>
    <?php if($userInfo): ?>
        <?php if($userInfo['nickname']): ?>
            你好
        <?php else: ?>
            我好
        @endif大家好
    <?php else: ?>
        全部客户
    <?php endif; ?>
</span>
```

**Comment by miscbits** [comment]
oh hmm. Is this an error with Laravel framework or is it an error with blade?

**Comment by lychao8** [comment]
vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php::compileStatements


in laravel 5.1.*
```
 /**
     * Compile Blade statements that start with "@".
     *
     * @param  string  $value
     * @return mixed
     */
    protected function compileStatements($value)
    {
        $callback = function ($match) {
            if (method_exists($this, $method = 'compile'.ucfirst($match[1]))) {
                $match[0] = $this->$method(Arr::get($match, 3));
            } elseif (isset($this->customDirectives[$match[1]])) {
                $match[0] = call_user_func($this->customDirectives[$match[1]], Arr::get($match, 3));
            }
            return isset($match[3]) ? $match[0] : $match[0].$match[2];
        };
        return preg_replace_callback('/\B@(\w+)([ \t]*)(\( ( (?>[^()]+) | (?3) )* \))?/x', $callback, $value);
    }


```
in laravel5.2.*
```
/**
     * Compile Blade statements that start with "@".
     *
     * @param  string  $value
     * @return mixed
     */
    protected function compileStatements($value)
    {
        $callback = function ($match) {
            if (Str::contains($match[1], '@')) {
                $match[0] = isset($match[3]) ? $match[1].$match[3] : $match[1];
            } elseif (isset($this->customDirectives[$match[1]])) {
                $match[0] = call_user_func($this->customDirectives[$match[1]], Arr::get($match, 3));
            } elseif (method_exists($this, $method = 'compile'.ucfirst($match[1]))) {
                $match[0] = $this->$method(Arr::get($match, 3));
            }
            return isset($match[3]) ? $match[0] : $match[0].$match[2];
        };
        return preg_replace_callback('/\B@(@?\w+(?:::\w+)?)([ \t]*)(\( ( (?>[^()]+) | (?3) )* \))?/x', $callback, $value);
    }
```

I find  ` \w `  ，when replace  `\w` into   `[a-zA-Z0-9_]` in laravel 5.1.* ，it will be ok。

**Comment by themsaid** [comment]
`@endif大家好` is invalid, it's what causes the error stated above
