### ISSUE TITLE
Executing a migration during testing changes the default connection to the one used in the migration

### ISSUE THREAD

**Issue by poisa** [laravel/framework#15894]
- Laravel Version: 5.2
- PHP Version: 5.6.26
- Database Driver & Version: sqlite 3
### Description:

Inside `setup()` in my unit tests executing a migration changes the default connection to the one used in the migration.
I was under the impression that the config was read once and could not be changed afterwards as stated by @GrahamCampbell https://github.com/laravel/framework/issues/13109#issuecomment-208392065
### Steps To Reproduce:

``` php
class MyTestCase extends TestCase
{
    public function setup() 
    {
        echo DB::getDefaultConnection() . "\n"; // tenant
        Artisan::call('migrate', ['--database' => 'main', '--path' => 'database/migrations/main']);
        echo DB::getDefaultConnection() . "\n"; // main (but expected "tenant")
    }
}
```

**Comment by properius** [comment]
Had the same problem calling artisan migrate in multi-database app.

This is what solved it for me:

```PHP
$defaultConnection = config('database.default');
Artisan::call('migrate', array('--database' => $databaseName, '--path' => $migrationsPath));
DB::setDefaultConnection($defaultConnection);
```

**Comment by poisa** [comment]
@properius That's the first thing I tried but it didn't work for me. For some reason I couldn't "write" to the config again.

**Comment by Dylan-DPC** [comment]
Does this problem still arise on 5.5? If not you can close this issue

**Comment by poisa** [comment]
@Dylan-DPC I solved this with a -horrible- workaround so I don't know if this is happening in 5.5. I'll close this for now.
