### ISSUE TITLE
[5.3] Request __set method

### ISSUE THREAD

**Issue by KKSzymanowski** [laravel/framework#15893]
- Laravel Version: 5.3.*, I suppose
- PHP Version: irrelevant
- Database Driver & Version: irrelevant

### Description:
Is it possible to add `__set` magic method to the `Illuminate\Http\Request` instance?
It will make something like this possible:
```
$request->foo = 'bar';
```
From what I know the only way to achieve this is to fetch the proper `ParameterBag` and call `set` or `add` method on its instance.

It would look something like this:
```
/**
 * Set an input element of the request.
 * 
 * @param  string  $key
 * @param  $value
 * @return void
 */
public function __set($key, $value)
{
    $this->offsetSet($key, $value);
}
```

The only problem I see is that public properties like `cookies` or `files` can be overwritten by mistake.
I think it doesn't matter because eg. the `files` parameter, if passed in a request, isn't accessible via `$request->files`. You would access it through `$request['files']` so naturally you would set it via `$request['files'] = 'foo';`

**Comment by GrahamCampbell** [comment]
Thanks, but we strictly only process bugs here. Please feel free to discuss on internals.

**Comment by GrahamCampbell** [comment]
Or indeed just skip to a PR for small stuff. ;)
