### ISSUE TITLE
Upgrade to 5.2 breaks Auth in my case

### ISSUE THREAD

**Issue by farhanrahman** [laravel/framework#15904]
- Laravel Version: 5.2.45
- PHP Version: 5.6.28
- Database Driver & Version:

### Description:
I upgraded my laravel version to 5.2 and I have the following structure:
(Assuming app name is TestApp)
app/
----Models/
--------User.php

When I try to make a Auth::attempt() I get an exception in createModel() method (line 128 of EloquentUserProvider.php) which tries to add a prefixed \ to the namespace of the php class. My model code looks like this:

```
<?php

namespace TestApp\Models;

class User ...
```

So the assertion message is this:

`exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'TestApp\Models\User' not found'`

My auth.php config has a section which looks like this:
```
    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => TestApp\Models\User::class,
        ]
    ],
```
### Steps To Reproduce:

Try to use Auth::attempt() with the above mentioned directory structure. (Assuming upgrading from 5.1.*)

**Comment by srmklive** [comment]
Please read the upgrade guide.

**Comment by farhanrahman** [comment]
@srmklive thanks for the really helpful comments -_-. I followed the upgrade guide. I wouldn't comment here if I didn't go through it. The fix for it was to include the Model explicitly like this:

```
<?php

namespace Illuminate\Auth;

use TestApp\Models\User;
use Illuminate\Support\Str;
use Illuminate\Contracts\Auth\UserProvider;
use Illuminate\Contracts\Hashing\Hasher as HasherContract;
use Illuminate\Contracts\Auth\Authenticatable as UserContract;

class EloquentUserProvider implements UserProvider
{
...

    /**
     * Create a new instance of the model.
     *
     * @return \Illuminate\Database\Eloquent\Model
     */
    public function createModel()
    {
        //$class = '\\'.ltrim($this->model, '\\'); <-- Unused

        return new User();
    }
```

I tried flushing the config cache as well. It turns out that it is not available at that point to import the App model.

**Comment by farhanrahman** [comment]
Okay the problem was fixed by clearing the cache.
