### ISSUE TITLE
Can't change column type from Integer to Uuid

### ISSUE THREAD

**Issue by NoFootDancer** [laravel/framework#15903]
- Laravel Version: 5.3.x
- PHP Version: 7.0.0
- Database Driver & Version:MySQL

### Description:
I have a database that uses Id's as integers but the nature of the project will need  those Id's as Uuids instead of integers, sounds really simple; I just need to run a migration that changes the column type from Integer to Uuid, and that's it

Problem is that when i try to run my migration i get a message like this (I'm using Linux):

![selection_010](https://cloud.githubusercontent.com/assets/15345906/19365404/6dcff642-9147-11e6-88db-996c04c71853.png)

### Steps To Reproduce:
Create a table with an integer value to use as an Id, then do a migration to change that column type to Uuid.

**Comment by a-komarev** [comment]
@NoFootDancer What MySQL version are you using?

**Comment by GrahamCampbell** [comment]
Looks like a doctrine issue?

**Comment by srmklive** [comment]
This is a doctrine issue in my opinion.

**Comment by NoFootDancer** [comment]
Db: MySQL Workbench Community (GPL) for Linux/Unix version 6.0.8  revision 11354 build 833
I'll try srmklive's approach and see what happens

**Comment by graphicmist** [comment]
Looks like this is still happening in 2020.
