### ISSUE TITLE
[5.3] Eloquent: Mutators, Array not work sometimes.

### ISSUE THREAD

**Issue by ac1982** [laravel/framework#15906]
- Laravel Version: 5.3.18
- PHP Version:7.0.11
- Database Driver & Version:MySQL 5.7

### Description:
Sometimes Array & JSON Casting doesn't work.

### Steps To Reproduce:
This is my comment class:
```

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class CustomerComment extends Model
{
    protected $table = 'customer_comments';
    protected $guarded = [];
    protected $casts = [
        'images' => 'array',
        'public' => 'boolean'
    ];
}

```
And  this is customer_comments migration
```
$table->json('images')->nullable();        
$table->tinyInteger('public')->default(1);  
```
And cats boolean works fine but array failure.
```
$customerComment=\App\Models\CustomerComment::find(1);
var_dump($customerComment->public);            //bool(true) 
var_dump($customerComment->images);          //string(72)
```

Somebody get the same issue? But it works in other models correctlly. Like:
```
namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    protected $table = 'companies';
    protected $guarded = [];
    protected $casts = [
        'regions' => 'array',
    ];
}                


```

**Comment by shadoWalker89** [comment]
You are casting the `regions` field in your model but in the example, you are using `images` not `regions`.
If you want `images` to be an array then you must add it into the `$casts` attribute

**Comment by ac1982** [comment]
not the same model. regions is in company model.

**Comment by ac1982** [comment]
I think I find out what cause the problem. My mistake, double json_encode data.
