### ISSUE TITLE
policy not exec in laravel 5.3

### ISSUE THREAD

**Issue by erikhu** [laravel/framework#15917]
- Laravel Version: 5.3
- PHP Version:
- Database Driver & Version:

### Description:
hi , i am develop in laravel 5.3 and have this problem , no show error , no show nothing bad in controllers or unit test , it is fine and work but in blade no exec alway showme false or 0, i not know if the problem is mine or the laravel or blade, i no know how can check its , i try use a policy in blade and not work, i register the policies in AuthServiceProvider and work fine in controllers or unit test , but in blade not , some idea? thnks

i use in the blade Auth::user()->can('is_admin',User::class)  or @can('is_admin',User::class) and alway is false or 0 , include if i chage the result of the function so 

public function is_admin(User $user){
   return true;
}

**Comment by ppp999** [comment]
It works fine for me. Did you register the policy in the AuthServiceProvider?

**Comment by themsaid** [comment]
You need to call the User class correctly

```
@can('is_admin', App\User::class)
```
