### ISSUE TITLE
HTML of mail is broken when Attaching files 

### ISSUE THREAD

**Issue by Jaspur** [laravel/framework#15911]
- Laravel Version: 5.2.45 (also happening on 5.1 LTS)
- PHP Version: 7.0
- Database Driver & Version: PostgreSQL

### Description:
When sending an e-mail via Laravel and I add an attachment; the HTML of the e-mail template breaks. The same e-mail without attachment send correctly the HTML. But when having an attachment it shows:
https://www.dropbox.com/s/hhjt3hzjick9ld2/Schermafdruk%202016-10-14%2015.45.26.png?dl=0

### Steps To Reproduce:
Try sending an e-mail with PDF attachment attached 
```
Mail::send('emails.invoice', $data, function ($m) use ($user,) {
            $m->to($user->email, $user->name)->subject('test');
            $m->attach(storage_path('invoice-test.pdf'), 'invoice.pdf', ['mime' => 'application/pdf']);
        });
```

**Comment by PetarDambovaliev** [comment]
@Jaspur From the image you posted i don't quite get what is your problem.
Is it a styling issue or it completely breaks with an error backend/frontend ?

**Comment by Jaspur** [comment]
It messes up the styling @PetarDambovaliev, so probably a parsing error in Laravel somewhere, but mail gets delivered except the styling.

**Comment by PetarDambovaliev** [comment]
@Jaspur try $m->attachData($data, 'invoice-test.pdf']);

**Comment by Jaspur** [comment]
@petardambovaliev tried that already (without the ] 😉), same styling issues.

**Comment by PetarDambovaliev** [comment]
![laravel-pdf-attachment](https://cloud.githubusercontent.com/assets/18395154/19399644/704d7e2c-924a-11e6-98bd-efa9841daf38.png)

**Comment by PetarDambovaliev** [comment]
I could not replicate your problem.

**Comment by Jaspur** [comment]
@PetarDambovaliev yes, that works; sending attachments. the attachment is always added. but the output of the html email thats send is broken. if you send the same html email without attachment, it shows up correctly. send it with attachment, the html is not correctly/missing/broken. mailtrap.io shows correct output. but real mail clients won't show the correct html. that is broken. its happening on multiple projects.

**Comment by themsaid** [comment]
@Jaspur can you share a screenshot that shows that "broken" mail in real HTML clients?

**Comment by Jaspur** [comment]
https://www.dropbox.com/s/hhjt3hzjick9ld2/Schermafdruk%202016-10-14%2015.45.26.png?dl=0

**Comment by tpraxl** [comment]
This may not be your actual problem – however, email layouts can break in some email clients if the email is too large. Fought this problem some time ago, especially on the iPhone when using mobile connections instead of WiFi. You could try to attach a smaller file – say just a few KB. However, as I already mentioned, this might not at all apply to you.

BTW: Your screenshot didn't tell me anything about your problem.

**Comment by themsaid** [comment]
> BTW: Your screenshot didn't tell me anything about your problem.

Does it work as intended in Mailtrap you say? What's the type of the attachment? If it works in Mailtrap that means the HTML is OK, maybe it's an issue with the mail client?

**Comment by tpraxl** [comment]
Can you send the `.eml`?

**Comment by Jaspur** [comment]
New screenshot:
https://www.dropbox.com/s/en2lh8e0e3hgy7h/Schermafdruk%202016-10-14%2021.41.03.png?dl=0
The left is with attachment, the right is the same e-mail without attachment.

@themsaid yes, it is, but with all mail clients. Mailtrap shows the HTML, but all mailclients have their same way of "rendering" this. See the pastebin from the startpost.

Tried with a PDF of 3kb. Same issue. @tpraxl 
Here is the EML: https://we.tl/4hM4XsJKP5

**Comment by tpraxl** [comment]
I know that bug. Has to do with Mac Mail. I believe it had to do with the type of attachment (there are at least two ways to attach it). Wait, I'll research. Hopefully, I can provide you with more information shortly.

**Comment by tpraxl** [comment]
Thunderbird looks OK. See:

![Screenshot eml Thunderbird](http://www.macrominds.de/images/github/thunderbird.png)

**Comment by Jaspur** [comment]
Nice. Also happends in outlook by the way.

**Comment by tpraxl** [comment]
Well.. Outlook is not exactly known for rendering emails standards compliant:) I'm still researching. I'm a bit irritated, because I thought that this problem wouldn't occur with external images. Thought this only happened with inlined images. Maybe I cannot help you then, but I'm not done researching yet.

**Comment by PetarDambovaliev** [comment]
@Jaspur Looks like this is not a Laravel issue.

**Comment by tpraxl** [comment]
Your attachment:

```
Content-Type: application/PDF
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="test.pdf"
```

Try `Content-Disposition: inline; filename=test.pdf`

I know that sounds weird. However, I can tell, that I just struggled with the same problem and that solved it.

Example:
```
Content-Type: text/calendar; charset=utf-8; method=REQUEST; name="Termin.ics"
Content-Transfer-Encoding: base64
Content-ID: <Termin>
Content-Disposition: inline; filename=Termin.ics
```
In order to isolate the problem, would you please attach an image, the same way (Content-Disposition: attachment). Does it still happen? What happens, when you change to Content-Disposition:inline?)

**Comment by Jaspur** [comment]
@tpraxl uhm, how? :p 
```$m->attachData($pdf->output(), 'test.pdf', ['mime' => 'application/pdf', 'Content-Disposition' => 'inline']);``` doesn't do the trick.

**Comment by tpraxl** [comment]
Let's switch to private conversation and share the results afterwards here. I think this gets annoying for the others. I'll send you an email.

**Comment by b4dnewz** [comment]
@tpraxl @Jaspur did you resolved it? just for the records on the conversation can you post here the solution?
I'm trying to do like Jaspur using fpdf:

```php
$this->pdf = new Fpdi\Fpdi();
$this->pdf->AddPage();
$this->pdf->SetFont('Arial','B',16);
$this->pdf->Cell(40,10,'Fattura in pdf.');
$this->pdf->Output();

return $this->view(
        'orders.email.confirm', 
        ['order' => $this->order]
)->attachData($this->pdf, 'test.pdf', [
        'mime' => 'application/pdf',
]);;
```

**Comment by ccennis** [comment]
i am having this exact same issue -- what was the resolution?. For us, contents within the PDF that have markup show in the email download with all html markup while elsewhere using $pdf->download('sample.pdf') shows the html rendered perfectly. What is wrong with the below? 

$pdf = $this->pdfService->getPDF($this->data['id']);
return $this->from('email@sample.com', 'Sample')
                    ->subject(sprintf("Subject line"))
                    ->view('sample.view')
                    ->bcc('email@sample.com')
                    ->bcc($this->creator->email)
       	       	    ->attachData($pdf->output(), 'sample.pdf');
