### ISSUE TITLE
[5.3] Route instance should be available for global middlewares

### ISSUE THREAD

**Issue by shadoWalker89** [laravel/framework#15924]
- Laravel Version: 5.3.18

When a global middleware is triggered, we don't have access to `$request->route()` (still null)
Is it possible that the route is available for these middlewares ?

This is my use case :

I need to be able to access the admin panel of my application even if the app is on maintenance mode.
I swapped the default `CheckForMaintenanceMode` by my implementation where i use `$request->route()` to determine if the request is coming from the admin panel.

The problem is that the route is not yet resolved and i get null instead.
As a temp fix, i moved the middleware from the 

```php
protected $middleware = [];
```

to

```php
protected $middlewareGroups = [
    'web' => [
        \App\Http\Middleware\CheckForMaintenanceMode::class,
        //...
    ]
];
```

**Comment by themsaid** [comment]
Yes global middleware run very early in the request, many parts of the framework won't be ready by then, I think what you did is the best way to go.
