### ISSUE TITLE
checking for non-existent model instance variable throws LogicExpression

### ISSUE THREAD

**Issue by tmaly1980** [laravel/framework#15945]
- Laravel Version: 5.3
- PHP Version: 7.0
- Database Driver & Version:

### Description:

Checking whether an instance variable even exists on a model throws a LogicExpression:

**Comment by sisve** [comment]
Could you provide a simple code snippet to reproduce this? Are you talking about `if(isset($model->property))`?

**Comment by tmaly1980** [comment]
Actually nevermind, the issue was not in Eloquent but in my ValidationTrait itself. It checks isset($this->rules) as a trait for my model, then also declares rules() as a wrapper to getRules(). So Eloquent assumes any method named after an accessor is a relationship. I've filed a bug report with this 3rd party module.
