### ISSUE TITLE
Problem after install laravel 5.3.19 - dont work firstOrFail()?

### ISSUE THREAD

**Issue by vincoweb** [laravel/framework#15969]
- Laravel Version: 5.3.19
- PHP Version: 7
- Database Driver & Version: mysql

### Description:

After composer up

Illuminate\Database\Eloquent\ModelNotFoundException: No query results for model [Kamra\Section]. in C:\wamp64\www\kamra\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php:311

#0 C:\wamp64\www\kamra\app\Providers\RouteServiceProvider.php(34): Illuminate\Database\Eloquent\Builder->firstOrFail()
#1 [internal function]: Kamra\Providers\RouteServiceProvider->Kamra\Providers\{closure}(Object(Kamra\Section), Object(Illuminate\Routing\Route))
#2 C:\wamp64\www\kamra\vendor\laravel\framework\src\Illuminate\Routing\Router.php(817): call_user_func(Object(Closure), Object(Kamra\Section), Object(Illuminate\Routing\Route)) 
....

When i went back to version 5.3.18, all work.

**Comment by themsaid** [comment]
@vincoweb please share how to regenerate the issue, `firstOrFail()` seems to be working fine, need to know your exact case in order to be able to identify the issue.

**Comment by vincoweb** [comment]
I do only this:

try {
	$section = Section::where('slug', $value)->firstOrFail();
} catch (ModelNotFoundException $exception) {
	abort(404);
}


I have more than one database connection, but this is main connection.

**Comment by maki10** [comment]
Try this

```php
Route::bind('section', function($value, $route)
{
    try {
        $section = Section::where('slug', $value)->firstOrFail();
    } catch (\Exception $exception) {
        abort(404);
    }
    return $section;
});
```

Not tested by myself but try...

**Comment by themsaid** [comment]
It still works on my end, are you sure the model exists?

**Comment by themsaid** [comment]
Also double check what's in `$value`

**Comment by vincoweb** [comment]
$value return string "foto". Change to \Exception has same behavior. If I give dd($section),  $section is collection how is expected.

**Comment by themsaid** [comment]
Doing `Section::where('slug', 'foto')->firstOrFail();` do you get an instance of the model or not?

**Comment by vincoweb** [comment]
I get model and maybe that is problem. When I instead return $section try return $section->name it goes further... Can Route::bind return model? Maybe there is problem.

**Comment by vincoweb** [comment]
Now I try use in Handler.php $request->url() and return url with http instead https!

**Comment by themsaid** [comment]
> dont work firstOrFail()?

That's the title of the issue, apparently `firstOrFail()` works just fine although you don't need to do it, just do:

```
Route::bind('section', function($value)
{
    return Section::where('slug', $value)->first();
});
```

Which part that works in 5.3.18 but doesn't work in 5.3.19?

**Comment by vincoweb** [comment]
But I want firstOrFail()

You are right, first() dont crush in that place, but then

Missing argument 2 for Kamra\Http\Controllers\PagesController::section()


I have

Route::group(['domain' => '{section}.' . env('DOMAIN'), 'middleware' => 'web'], function() {
...
Route::get('/{page?}', ['as' => 'section', 'uses' => 'PagesController@section'])
...
}

**Comment by vincoweb** [comment]
I use https and $request->url() always return http

**Comment by themsaid** [comment]
I'm sorry but I don't seem to understand what your issue is, but `firstOrFail` definitely work as intended, please try to check on the forums, I'm sure someone will be able to help you there.

**Comment by vincoweb** [comment]
So... Issue was with web middleware Route::group. From laravel 5.3 web middleware is used automaticly on web.php. But why it worked before 5.3.19. and now crash?
