### ISSUE TITLE
Laravel5.3.19(18) Database transaction is not work.

### ISSUE THREAD

**Issue by hengsoheak** [laravel/framework#15972]
- Laravel Version:5.3.19
- PHP Version: 5.6.19
- Database Mysql & Version:5.7.11

### I've more experience to use Database transaction on Laravel5.0 it work as well after I created new project and install laravel by composer as above system and it version and try with the same code and try to change some ways I have searching in google but finally it really not work as 5.0. I'm really stuck right now

Issue: It always insert all data into data although I deleted commit method or don't use it and some data was insert although some of them is break. 

  if ($this->request->isMethod('post')) {

            //DB::beginTransaction();
            try {

                DB::beginTransaction();
                $cats = new Cat();
                $res = [];
                $cats->parent_id = $this->request->input('category_id');
                $cats->status = ($this->request->input('status')) ? $this->request->input('status') : 0;
                if ($res['cat'] = $cats->save()) {

                    $catD = new CategoryDescriptions();
                    $catD->category_id = $cats->id;
                    $catD->language_id = 1;
                    $catD->name = $this->request->input('en_name');
                    if ($res['cat2'] = $catD->save()) {
                        $catD2 = new CategoryDescriptions();
                        $catD2->category_id = $cats->id;
                        $catD2->language_id = 2;
                        $catD2->name = $this->request->input('kh_name');
                        $res['all'] = $catD2->save();
                    }
                }
                if(!empty($res['all'])) {
                    //DB::commit();
                    return $res;
                }
            } catch (Exception $e) {
                DB::rollback();
                return [false];
            }
        }:

**Comment by themsaid** [comment]
@hengsoheak I couldn't regenerate your issue, here's my trial:

    DB::beginTransaction();

    \App\User::create(['name' => 'asd', 'password' => 'zxcx', 'email' => 'zxc']);

    DB::commit();

If I remove the commit method nothing gets saved to the DB:

    DB::beginTransaction();

    \App\User::create(['name' => 'asd', 'password' => 'zxcx', 'email' => 'zxc']);

Any idea how I can replicate your issue? Anything I need to change?

**Comment by hengsoheak** [comment]
Even use as your logic
But still the same
All everything has updated

   final function edit()
    {

        if ($this->request->isMethod('post')) {

            DB::beginTransaction();

                $update['eng'] = CategoryDescriptions::where('category_id',$this->request->input('category_id'))
                    ->where('language_id',1)
                    ->update([
                        'name'=>$this->request->input('en_name')
                    ]);
                $update['kh'] = CategoryDescriptions::where('category_id',$this->request->input('category_id'))
                    ->where('language_id',2)
                    ->update([
                        'name'=>$this->request->input('kh_name')
                    ]);
            return [$update,DB::beginTransaction()];
        }

        $cat = Cat::with(['CategoryDescriptions', 'children'])->where('status', 1)->get();
        return view('admin.categories.edit', ['cat' => $cat]);
    }

**Comment by themsaid** [comment]
@hengsoheak not sure what's the issue here, also what's this?

```
return [$update, DB::beginTransaction()];
```

**Comment by hengsoheak** [comment]
I've use this->request->input() because I have initial from Constructor
as 
    public function __construct(Request $request)
    {
        parent::__construct();
        $this->middleware('auth');
        $this->request = $request;
    }
so I can use request all method in this class right how ever I just testing to see BeginTransaction whatever this method return any value or not.
Issue as the same as before: I have use as your login and as another tutorial from google and Laravel5.3.19 document but still the same problem (I dont call commit method but data insert to DB when I insert or update,delete).

**Comment by hengsoheak** [comment]
I have asked in stackoverflow 
http://stackoverflow.com/questions/40092302/laravel-5-3-database-transaction-issue

**Comment by hengsoheak** [comment]
and you can see this wold source code here

https://github.com/hengsoheak/personalEcommerce

**Comment by themsaid** [comment]
I'm sorry but this code doesn't look right. Closing this issue since I can't replicate any problem, please feel free to ping me if you ever managed to write a piece of code on a fresh laravel installation that I can use to replicate the issue.

**Comment by hengsoheak** [comment]
OK
