### ISSUE TITLE
[Idea] Make console commands environment "aware"

### ISSUE THREAD

**Issue by tyloo** [laravel/framework#15978]
This is just an idea, but I'll try to explain it well: I think it would be great to have the list of your commands when typing `php artisan` based on the current environment. Indeed, when you are in production, you don't really need the `make` commands and It's in my case sometimes difficult to fetch threw the list (I use `| grep ` to achieve this). I wanted to talk about it with Taylor at the last Laracon EU but couldn't find time ;)

Let me know what you guys think about it.

Cheers!

**Comment by themsaid** [comment]
Thank you, but for suggestions and feature requests please use the https://github.com/laravel/internals repo :)
