### ISSUE TITLE
Illuminate\Http\Response - Attribute "original" contains string instead of View object.

### ISSUE THREAD

**Issue by percymamedy** [laravel/framework#15976]
- Laravel Version: 5.2.45
- Homestead version '3.0.2'

### Description:
I am returning a View from a controller's method as follows:

```php
return view('Main::pages.content-page', compact('content'));
```

View renders correctly however, when I dd the response object I see that the attribute "original" of the response object is a string whereas it should have been the View Object.

```
Response {#385 ▼
  +original: """
    <!DOCTYPE html>\n
    <html lang="en">\n
        <head>\n
        <meta charset="utf-8">\n
        <meta http-equiv="X-UA-Compatible" content="IE=edge">\n
        <meta name="viewport" content="width=device-width, initial-scale=1">\n
        <meta name="author" content="">\n
        <meta name="csrf-token" content="2CQirHnZ7isCBRfkhOYkzPAWOzNIqJISrbb1mfDv">\n
            <meta name="description" content="">\n
        <meta name="keywords" content="">\n
        <title id="page_title">    D&eacute;couvrir\n
    </title>\n
    \n
        <!-- Default CSS -->\n
    <link type="text/css" media="all" rel="stylesheet" href="http://tesdiq.dev/build/main/css/all-5f07666915.css">\n
    \n
    \n
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>\n
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>\n
    \n
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\n
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n
        <!--[if lt IE 9]>\n
.....
```

Is this expected behavior because my tests are actually failing because of it, since in my test am essentially doing 

```php
$this->get(route('main.page', ['content' => $content->slug]))
        ->assertResponseOk()
        ->assertViewHas('content', $content);
```

Am getting the following failure
```php
F                                                                   1 / 1 (100%)

Time: 179 ms, Memory: 20.00MB

There was 1 failure:

1) IndexControllerTest::testGetPageMethod
The response was not a view.
Failed asserting that false is true.

```

Looking at the structure of the ```assertViewHas()``` method we can see why

```php

/**
     * Assert that the response view has a given piece of bound data.
     *
     * @param  string|array  $key
     * @param  mixed  $value
     * @return $this
     */
    public function assertViewHas($key, $value = null)
    {
        if (is_array($key)) {
            return $this->assertViewHasAll($key);
        }

        if (! isset($this->response->original) || ! $this->response->original instanceof View) {
            return PHPUnit::assertTrue(false, 'The response was not a view.');
        }
        ......
```

The condition ```! $this->response->original instanceof View``` fails because original is a string but should have been a View Object.

So am at a lost here. Is this expected behavior if so why the condition in the assertViewHas method ?

```php
I am on Laravel Homestead version '3.0.2'
Laravel 5.2.45
```

### Steps To Reproduce:

- Return a view from a controller.
- Create a test that makes a get request to the controller.
- Use the assertViewHas method in the test.

```php
$this->get(route('main.page', ['content' => $content->slug]))
        ->assertResponseOk()
        ->assertViewHas('content', $content);
```

**Comment by themsaid** [comment]
Please upgrade to laravel 5.3 since 5.2 is not supported anymore, please feel free to ping me if you ever encountered the same issue on a 5.3 instance.

**Comment by percymamedy** [comment]
@themsaid, thank you for your response. This issue does not occur in 5.3. However am a little bit skeptical about upgrading my app to 5.3 yet as I don't feel 5.3 is mature enough for production, I want to wait until next year to change to 5.3. I might be wrong though but it's just my gut feeling.

Thank you anyways for thanking the time to answer my question.

**Comment by RyoIkarashi** [comment]
@themsaid I ran into the same issue above at version `5.6`.
When Controller returns `return response()->view('name');`, `$response->original` will be string as html content in an unit test. How can I get view object instead of string?
