### ISSUE TITLE
session expires randomly when PHP Artisan Serve a host and port remotly 

### ISSUE THREAD

**Issue by jehadja** [laravel/framework#15971]
- Laravel Version: 5.2.*
- PHP Version: PHP 7.0.8
- Database Driver & Version: MYSQL 

### Description:
i am sorry for my english language but i tried to report a bug for development issue
session expires randomly when PHP Artisan Serve a host and port remotly  Chrome

### Steps To Reproduce:
 test enviroment 
 widows 
-- OR --
 ubuntu 16

`composer create-project --prefer-dist laravel/laravel blog "5.2.*"
`
go to blog Directory 

go to blog/resources/views/welcome.blade.php

and put in any viewabel place  ` {{ csrf_token() }}`

`php artisan serve  --host 192.168.*.* --port 80
`
from your work php - server you will not have any problem at all !

from any pc on network open the link on chrome 
refresh the page mannully each 2-4 time session will be changed 

Value locally = kcQ8eiwP5UQRyJaG7euRgusSer1G99PeOmtCp8oo
will not changed how ever time you refresh 

from another pc on network =ccwv79JRE0BKwnSScTgVG4DLRBH419sVBQytNRtS first value 
5 refresh then = WApp3lqbS7pKRlWQYfq6NXRdYF6r6VfxcNHgQdre
one refresh = XGPY9tOTinYg9nS4pk2aNUQZzEbewXEKpoVf3zrd 
some times up to 10-15 refresh
and this behavoir shows only on chrome current test version on chrome 
Mac OS Chrome version : 53.0.2785.143 (64-bit)
Window 8 Chrome  53.0.2785.143M

i test FireFox , IE it doesn't look for me that it have this issue 

.env APP_URL=http://192.168.*.*
session.php domian
`  'domain' => str_replace(['http://', 'https://'], '', config('app.url')),
`

current solution if it will help on windows xampp or ubuntu apache2  i put laravel project in var/www/html on ubuntu for windows on /xampp/htdocs  and run it from its public file 

without `php artisan serve `

http://localhost/blog/public

or from other PCs on network 

http://192.168.*.*/blog/public

depending on apache it self 

problem disappear 

hope it will help you !

`*note if you run vmware Host Pc will not be infected 
`

**Comment by themsaid** [comment]
`5.2.*` is not supported anymore, please upgrade to `5.3` and ping me if the problem still exists.
