### ISSUE TITLE
[proposal] add reverse method for getRouteKey

### ISSUE THREAD

**Issue by ppp999** [laravel/framework#15975]
Sorry if this is not the right place (please redirect me if I wrong), but I have a proposal for Laravel.

In Model there is a `getRouteKey` method, for converting the model key to route key. It is very helpful method, but the reverse way is to make a route binding which is ungainly, because one way wrote in the model and the converts back wrote in the routes file. 

Maybe consider to create `fromRouteKey` in the Model that converts back - from route key to model key. And call it automatically when binding the model.

I think that it make route keys more flexible and convenient.

**Comment by themsaid** [comment]
Thank you but for suggestions and feature requests please use the https://github.com/laravel/internals repo :)
