### ISSUE TITLE
Query Builder REPLACE INTO

### ISSUE THREAD

**Issue by VinceG** [laravel/framework#15989]
- Laravel Version: 5.2/5.3
- PHP Version: 7.0.1
- Database Driver & Version: 5.6.27

### Description:
Are there any plans adding REPLACE INTO as a query builder method? we have insert, update, delete and it'll be nice to have replace into as well.

I understand it's not an actual valid SQL statement but i think the benefit of having it overcomes the fact that it's not.

**Comment by GrahamCampbell** [comment]
Sorry, but we only process bug reports here.

**Comment by VinceG** [comment]
@GrahamCampbell where would be the suitable place to request a feature? slack/twitter?

**Comment by sisve** [comment]
@VinceG Guessing https://github.com/laravel/internals

**Comment by VinceG** [comment]
@sisve thanks.
