### ISSUE TITLE
When testing, Event mock object lacks of listen() method.

### ISSUE THREAD

**Issue by dvlpp** [laravel/framework#15981]
- Laravel Version: 5.3.19
- PHP Version: 7.0.0
- Database Driver & Version: N/A

### Description:
Since the 5.3.19 update, some of my tests which implies events and artisan calls have errors. This appends because the `App\Console\Kernel::commands()` method execute the `base_path('routes/console.php')` file, in which there is an `Artisan::command()` call by default, which leads us to `Illuminate\Foundation\Console\Kernel::command()` in which there is (finally) a `$this->app['events']->listen()` instruction. But when using, in tests, `$this->withoutEvents()` (from the `MockApplicationServices` trait), the mock created here lacks of this `listen()` method.

Adding a `$mock->shouldReceive('listen');` instruction in this method solve the issue. But since I am not sure how deep it can go, so I choose to write an issue instead of creating a PR.

### Steps To Reproduce:
Write a test with `$this->withoutEvents()` and an artisan call, leaving the default `routes/console.php` file content.

**Comment by themsaid** [comment]
Opened a PR to fix that: https://github.com/laravel/framework/pull/16012
