### ISSUE TITLE
`Schedule::compileParameters` does not escape certain arguments

### ISSUE THREAD

**Issue by inxilpro** [laravel/framework#15996]
- Laravel Version: 5.2 and 5.3
- PHP Version: n/a
- Database Driver & Version: n/a

### Description:

The method [Illuminate\Console\Scheduling\Schedule::compileParameters](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Console/Scheduling/Schedule.php#L79) runs:

```php
return collect($parameters)->map(function ($value, $key) {
    return is_numeric($key) ? $value : $key.'='.(is_numeric($value) ? $value : ProcessUtils::escapeArgument($value));
})->implode(' ');
```

That means that if the `$parameters` array is numerically indexed, the scheduler does not escape the values.  See **Steps To Reproduce**.

The fix is very simple, and I'm happy to submit a PR. I just want to make sure this is a bug and not intentional.

### Steps To Reproduce:

```php
// In App\Console\Kernel
protected function schedule(Schedule $schedule)
{
    $schedule->command('my:command', ['first argument'])->everyMinute();
}
```

This results in the command `php artisan my:command first argument` to be run, when my expected behavior is `php artisan my:command 'first argument'` (argument should be quoted).

**Comment by inxilpro** [comment]
Also, this is a backwards-incompatible change. If this is unintentional, should I submit a PR against `master` or against `5.1`?

**Comment by GrahamCampbell** [comment]
5.3 or master please.

**Comment by GrahamCampbell** [comment]
Probably master,
