### ISSUE TITLE
Route not found after adding 'auth:api' middleware Laravel 5.3

### ISSUE THREAD

**Issue by omidahn** [laravel/framework#16008]
- Laravel Version: 5.3.19
- PHP Version: 7.0
- Database Driver & Version:
mongodb  v3
### Description:
I get a NotFoundHttpException after adding auth:api middleware to any route in routes/api.php
http://stackoverflow.com/questions/40040226/route-not-found-after-adding-authapi-middleware-laravel-5-3
### Steps To Reproduce:
1- create a new api route
2- add auth:api middleware

**Comment by themsaid** [comment]
The answer is in the Stackoverflow question you shared.

**Comment by tomasvanrijsse** [comment]
It would be awesome if this middleware for client credentials was mentioned in the docs.
That would save some of us to question our own sanity.
