### ISSUE TITLE
Pagination bug in Laravel 5.3

### ISSUE THREAD

**Issue by lino10** [laravel/framework#16004]
- Laravel Version: 5.3.19
- PHP Version: 7.0.1
- Database Driver & Version: 10.1.9-MariaDB

### Description:
Hi, I'm encountering strange pagination bug. It's working in my previous website(Laravel 5.2).

I tried printing the $_GET variable, the previous website has 'page' variable while the new website does not.
```
array:1 [▼
  "page" => "2"
]
```
ServerBag 
```
      "REQUEST_URI" => "/product?page=2"
      "SCRIPT_NAME" => "/index.php"
      "QUERY_STRING" => "page=2"
      "PHP_SELF" => "/index.php"
```

The $_GET variable only contains the base url of the page in the laravel 5.3
```
array:1 [▼
  "/test/voucher" => ""
]
```
ServerBag
```
      "REQUEST_URI" => "/_web/vcapp/test/voucher?page=2"
      "SCRIPT_NAME" => "/_web/vcapp/index.php"
      "QUERY_STRING" => "/test/voucher"
      "PHP_SELF" => "/_web/vcapp/index.php"
```

### Steps To Reproduce:
Open next page of the result

**Comment by themsaid** [comment]
Never encountered this problem on any 5.3 instance, I think it's an issue with your server configuration. Please use the forums for further assistance.

**Comment by lino10** [comment]
I just did some tests. It's working in Homestead but this is 100% reproducible in XAMPP.
It's not pagination bug, it's $_GET bug. All $_GET parameters are not captured and instead replaced by the page base url.

**Comment by sede2** [comment]
try

`$request->all();`
