### ISSUE TITLE
Support for multiple fields in getRouteKeyName()

### ISSUE THREAD

**Issue by sailingdeveloper** [laravel/framework#16003]
Wouldn't it be nice if `getRouteKeyName` in UrlRoutable can return an array of fields it has to query?

I often find myself implementing 'find by slug or id', and can't get it to work with implicit route-model binding.

```php
public function getRouteKeyName()
{
    return ['id', 'slug'];
}
```

I'd be willing to make a pull request if this is a good idea 🙂

**Comment by Modelizer** [comment]
Please use [laravel/internals](https://github.com/laravel/internals/issues) for proposal :)

**Comment by sailingdeveloper** [comment]
Sorry, I didn't know it belonged there. I will post it there, thank you :)

**Comment by sailingdeveloper** [comment]
Posted here: https://github.com/laravel/internals/issues/260
