### ISSUE TITLE
Casts: date vs. datetime

### ISSUE THREAD

**Issue by powelski** [laravel/framework#16002]
- Laravel Version: 5.3.19
- PHP Version: N/A
- Database Driver & Version: N/A

What is the difference between those two?

```php
protected $casts = [
    'hired_at' => 'date',
];
```
And:
```php
protected $casts = [
    'hired_at' => 'datetime',
];
```

They both seem to just return Carbon instance, including time information. I've made a test using `date` and `datetime` columns and all 4 combinations create exactly the same results.

If so, why does this ambiguity exist?

UPDATE

I checked it out in the code and they in fact do the exact same thing, just serve as an alias. How about setting up time information to `00:00:00` for `date` mutator? That could be useful for comparisons if we want to store time information  in the database, but skip it in our model. Otherwise, it's a little confusing to have both `date` and `datetime` behaving the same way.

**Comment by sailingdeveloper** [comment]
There are many aliases that do the same thing in Laravel, just for usability.

**Comment by powelski** [comment]
Usability leads to usefulness. What is useful about naming ambiguity? In my opinion it's closer to confusion factor than usefulness.

**Comment by themsaid** [comment]
Thank you @powelski but I really don't think this can be considered as a bug report, if you'd like to continue discussing the topic I suggest that you use the https://github.com/laravel/internals repo.

**Comment by powelski** [comment]
Thanks, I didn't know such thing exists.

**Comment by themsaid** [comment]
welcome :)

**Comment by Angelinsky7** [comment]
i came here for the same reason, i was not comfortable why $casts/date and $casts/datetime has the same behavior and was wandering what i was not doing correctly...
It still would like to be able to $casts as date only and not having my json have unused `00:00:00.000000Z` for nothing
