### ISSUE TITLE
duplicate enableHttpMethodParameterOverride calls

### ISSUE THREAD

**Issue by alewiahmed** [laravel/framework#16010]
- Laravel Version: 5.3
- PHP Version:
- Database Driver & Version:

### Description:
I was just researching the request life cycle of a laravel application when I saw the duplicate enableHttpMethodParameterOverride() calls in the $request->capture method & kernel handle Method. The problem is that in the public\index.php of the laravel application the kernel handle method is called with the parameter of $request::capture. The $request::capture method calls enableHttpMethodParameterOverride() and returns a $request. The kernel handle also calls $request->enableHttpMethodParameterOverride(). I see duplicate function calls. Am I wrong.

**Comment by themsaid** [comment]
Thank you for reporting, I've made a PR that removes it from capture, let's see if it was there to handle a case we don't know about :)

https://github.com/laravel/framework/pull/16013
