### ISSUE TITLE
DatabaseMigrations: Why only rollback single migration?

### ISSUE THREAD

**Issue by Blizzke** [laravel/framework#16014]
- Laravel Version: 5.3.15

### Description:

In the [DatabaseMigrations](
https://github.com/laravel/framework/blob/5.3/src/Illuminate/Foundation/Testing/DatabaseMigrations.php#L21)-trait the call at the end is `migrate:rollback`. This only rolls back the last migration.
Is there any specific reason to migrate up all the way but undo only a single migration? Makes little sense to me, I would expect the call to be to `migrate:reset`

**Comment by themsaid** [comment]
Because we migrate everything in one patch, so using `rollback` will undo that 1 patch.
