### ISSUE TITLE
Custom Relationship Serializer [suggestion]

### ISSUE THREAD

**Issue by leandrogehlen** [laravel/framework#16029]
- Laravel Version: 5.3

### Description:

My suggestion is to be possible to change the default relationship json serialization,

Currently, i changed this method https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Eloquent/Model.php#L2523

to

```php

public function relationsToArray()
{
    $attributes = [];
   
    foreach ($this->getArrayableRelations() as $key => $value) {
        $definition = call_user_func([$this, $key]);
        
        $transformed = $this->transformRelation($definition, $value);
         if ($transformed !== false)  {
             $value = $transformed;
         } 
         
         //same code of parent 
          ...
}

public function transformRelation($definition, $value)
{
    if ($definition instanceof BelongsToMany) {
         $key = $definition->getRelated()->getKeyName();
         return  $value->pluck($key);
     }
     
     return false;
}

```
This way, is easier change default behavior in descendent class;

**Comment by themsaid** [comment]
Thank you but this repo is for bug reporting only, for suggestions and feature requests please use the https://github.com/laravel/internals repo.

**Comment by themsaid** [comment]
Or maybe open a PR with your changes so that we can discuss implementation.
