### ISSUE TITLE
Rewrite of middleware sorting returns duplicates

### ISSUE THREAD

**Issue by SuperlativeEntity** [laravel/framework#16027]
- Laravel Version: 5.3.19
- PHP Version: PHP 5.6.25 (cli) (built: Aug 18 2016 11:40:20)
- Database Driver & Version: Server version: 10.1.9-MariaDB-log mariadb.org binary distribution

### Description: 
framework/src/Illuminate/Routing/Router.php - function sortMiddleware returns an array with duplicates

### Steps To Reproduce: 
Debug or log output of function

**Laravel Version: 5.3.18**
sortMiddleware {"sorted":[
"Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse",
"Illuminate\\Session\\Middleware\\StartSession",
"Illuminate\\View\\Middleware\\ShareErrorsFromSession",
"App\\Http\\Middleware\\VerifyCsrfToken",
"App\\Http\\Middleware\\FilterIfPjax",
"App\\Http\\Middleware\\ForceHttps",
"App\\Http\\Middleware\\JSONRequest"]}

**Laravel Version: 5.3.19**
[2016-10-20 20:17:48] local.INFO: sortMiddleware {"wtf":[
"Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse",
"Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse",
"Illuminate\\Session\\Middleware\\StartSession",
"Illuminate\\Session\\Middleware\\StartSession",
"Illuminate\\View\\Middleware\\ShareErrorsFromSession",
"App\\Http\\Middleware\\VerifyCsrfToken",
"App\\Http\\Middleware\\FilterIfPjax",
"App\\Http\\Middleware\\ForceHttps",
"App\\Http\\Middleware\\JSONRequest",
"Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse",
"Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse",
"Illuminate\\View\\Middleware\\ShareErrorsFromSession",
"App\\Http\\Middleware\\VerifyCsrfToken",
"App\\Http\\Middleware\\FilterIfPjax",
"App\\Http\\Middleware\\ForceHttps",
"App\\Http\\Middleware\\JSONRequest",
"App\\Http\\Middleware\\SentinelCheck",
"App\\Http\\Middleware\\SentinelHasAccess",
"App\\Http\\Middleware\\SessionExpired",
"App\\Http\\Middleware\\UserActivity",
"App\\Http\\Middleware\\JSONRequest"]}

**Comment by SuperlativeEntity** [comment]
Update: The issue seems to be that the array returned from the sortMiddleware function has duplicates. array_unique seems to sort it out.

**Comment by SuperlativeEntity** [comment]
Fix: return array_unique((new SortedMiddleware($this->middlewarePriority, $middlewares))->all());

**Comment by themsaid** [comment]
Fixed in the PR linked with the issue.
