### ISSUE TITLE
Exceptions Handler report doesn't abide by APP_DEBUG by default

### ISSUE THREAD

**Issue by shallot** [laravel/framework#16022]
- Laravel Version: 5.2
- PHP Version: 5.5
- Database Driver & Version: PostgreSQL 9

### Description:

The default reporter just passes the exception object into the logger error method, cf.
https://github.com/laravel/framework/blob/5.3/src/Illuminate/Foundation/Exceptions/Handler.php#L71

This in turn, on my Laravel 5.2 installation, went into Monolog which cast the variable into string, which in turn called PHP's default exception __toString handling. This expanded into the exception's message as well as a stack trace.

Now, I see that in the meantime Monolog changed to remove that cast:
https://github.com/Seldaek/monolog/commit/6c424f851cf5732e648a898e16e68bc2a35ee639
I'll have to test that.

But regardless, it does seem more reasonable that Laravel should explicate its parsing of that information, in order to enforce the general app debug rule set by APP_DEBUG etc.
For example, if debug is off, don't log the full trace, just the immediate caller.

I'm currently doing it manually in the app exception handler with e.g.

        if (php_sapi_name() == "cli" && ! config('app.debug')) {
            $e= sprintf('PID=%d: exception %s code %s with message %s, called from %s:%d',
                         getmypid(), get_class($e), $e->getCode(), $e->getMessage(), $e->getFile(), $e->getLine());
        }

### Steps To Reproduce:

See https://github.com/laravel/framework/issues/16021 This large amount of log output per exception made the effects of that bug much worse.

Please fix this. TIA.

**Comment by themsaid** [comment]
Without the full trace how would you debug your app when problems happen?

**Comment by shallot** [comment]
I agree the trace is useful, but not necessarily all the time and at full length - if that weren't so, what would be the point of having a debug mode variable?

**Comment by themsaid** [comment]
It's to show the error information to the end user, if dev mode is on the information is visible otherwise it's hidden. But internally the complete stack trace must be logged, otherwise you'll have no way to fix the issues.

**Comment by shallot** [comment]
Sure. But if you have something in production, and the user finds a code path that consistently generates an exception, they get an easy DoS vector on your production.

Is it reasonable to have a default behavior that prioritizes debugging over basic stability when you run with APP_DEBUG=false?

I'm fairly certain that you will find real-world users who will find this completely unintuitive.

**Comment by sisve** [comment]
In what way is the logging your easy DoS vector? Are you thinking about consuming all disk space?

**Comment by shallot** [comment]
@sisve yes. Whenever the user can generate a (relatively short) request which by default results in an inordinate amount of log data, that's going to be frowned upon, because of the amplification.
