### ISSUE TITLE
database-backed Queue Worker does not enforce its minimum resolution of 1s

### ISSUE THREAD

**Issue by shallot** [laravel/framework#16021]
- Laravel Version: 5.2, 5.3
- PHP Version: 5.5
- Database Driver & Version: PostgreSQL

### Description:

The queue worker has an implicit limit on its queue sleep variable in that it can't be specified in non-integer seconds.

getSeconds() calls getTimestamp(), which returns an integer, and the database table column is an integer:
https://github.com/laravel/framework/blob/5.3/src/Illuminate/Queue/Queue.php#L144
http://php.net/manual/en/datetime.gettimestamp.php
https://github.com/illuminate/queue/blob/5.3/Console/stubs/jobs.stub

This is not documented at https://laravel.com/docs/5.2/queues "Specifying Queue Sleep Duration" - that section should say you can't go below 1.0 in this case.
Confusingly enough, that whole section is missing from https://laravel.com/docs/5.3/queues

Furthermore, there's another bug in 5.2 caused by this: in case the worker throws an exception, the loop code doesn't actually handle that, it just runs the generic exception handler's report method and continues with the next iteration immediately.
This bug was fixed in 5.3 by adding the configured sleep inside the method that processes a job in daemons, cf.
https://github.com/laravel/framework/blob/5.2/src/Illuminate/Queue/Worker.php#L108
https://github.com/laravel/framework/blob/5.3/src/Illuminate/Queue/Worker.php#L139

It would be good if this was fixed in 5.2 or at least documented in 5.2 docs, because the consequences can be serious.

### Steps To Reproduce:

For example, start a queue worker with sleep 0.5 and see how it doesn't actually process jobs problem.  Or break the worker's connection to the database server, and watch storage/logs/ disk quickly fill up with an endless stream of error messages (that by default have long stack traces).

Please fix this. TIA.

**Comment by themsaid** [comment]
5.2 is not supported anymore and I don't seem to be able to replicate the problem on a 5.3 instance.

Please upgrade to 5.3 and report back if you have any problems.

**Comment by shallot** [comment]
I have already linked to specific code points from the 5.3 branch that say in no uncertain terms how the minimum resolution still exists in 5.3...

I see https://github.com/laravel/framework/blob/5.3/src/Illuminate/Queue/Console/WorkCommand.php has changed from 5.2, but I don't quite see any rule that would prevent one from specifying a float as sleep.

When you run artisan queue:work --queue=something --sleep=0.75, do you get an error?
