### ISSUE TITLE
storeAs no save (bug)

### ISSUE THREAD

**Issue by netdragoon** [laravel/framework#16037]
- Laravel Version: 5.3.0
- PHP Version:
- Database Driver & Version:

### storeAs no save files

Please, o method storeAs of request->files no save!!!

**Comment by sisve** [comment]
Could you provide us with your php version and minimal test case to reproduce the problem?

**Comment by netdragoon** [comment]
**Yes**

Laravel Version: 5.3.*
PHP Version: 7.0.9
Database Driver & Version: MySQL 5.5.27

**_Code:_**

```
if ($request->file('picture'))
{
            $p = $request->file('picture');            
            $newModel = $model->create([
                        'name' => 'pic_'.uniqid(),
                        'mimetype' => $p->getClientMimeType(),
                        'extension' => $p->extension(),
                        'length' => $p->getClientSize(),
                        'state' => 1
            ]);
           //Error - Exception
            $p->storeAs('images', $newModel->name.'.'.$newModel->extension);            
}
```

**_Exception:_**

In the line: `$p->storeAs('images', $newModel->name.'.'.$newModel->extension); `

![erroestranho](https://cloud.githubusercontent.com/assets/15145509/19597998/e3fb197a-9776-11e6-809b-950edc0a71c3.png)

@sisve

**Comment by themsaid** [comment]
@netdragoon looks like you're trying to upload a corrupted file, can you check using another file?

**Comment by netdragoon** [comment]
@themsaid 

I made dozens of test, with dozens of files and no success, I did the same test with the same code in version 5.2. * And it worked, also has a problem in "FilesystemAdapter" file. I'm sure it's a bug!

**Comment by themsaid** [comment]
It seems to be working fine on a fresh laravel 5.3 installation, check `$p->getRealPath()` in your controller, this value shouldn't be empty, if it's empty start debugging here http://php.net/manual/en/splfileinfo.getrealpath.php

**Comment by netdragoon** [comment]
@themsaid in the controller not empty

![save00](https://cloud.githubusercontent.com/assets/15145509/19628692/5dc44e76-9942-11e6-80fe-32ccb85c74a3.png)

but still does not write in the folder. 


Remains the problem !!!

**Comment by themsaid** [comment]
Track it down to the putFileAs method and see if there's a value there, the value shoulf be similar to the one in tour controller since it's the same instance

**Comment by themsaid** [comment]
The error you shared means that the value is false which indicates an upload failure, all my assumptions are based on the screenshot of the error you shared.

**Comment by netdragoon** [comment]
`var_dump($request->file('picture'))`


`object(Illuminate\Http\UploadedFile)#195 (7) { ["test":"Symfony\Component\HttpFoundation\File\UploadedFile":private]=> bool(false) ["originalName":"Symfony\Component\HttpFoundation\File\UploadedFile":private]=> string(39) "1619132_549452645174228_481817119_n.jpg" ["mimeType":"Symfony\Component\HttpFoundation\File\UploadedFile":private]=> string(10) "image/jpeg" ["size":"Symfony\Component\HttpFoundation\File\UploadedFile":private]=> int(24322) ["error":"Symfony\Component\HttpFoundation\File\UploadedFile":private]=> int(0) ["pathName":"SplFileInfo":private]=> string(27) "C:\Windows\Temp\php7963.tmp" ["fileName":"SplFileInfo":private]=> string(11) "php7963.tmp" }`

What is invalid?

**Comment by netdragoon** [comment]
Using the command `\Storage::putFile('images', $request->file('picture'));` was also not recorded the image, just remembering that the previous version works perfectly (5.2. *).


It's been three days of unsuccessful tests, please re-open the issue!

**Comment by sisve** [comment]
@netdragoon You are using Windows, right? There were recently another Windows-only issue with flysystem, could you try updating it with `composer update league/flysystem`?

The other issue: https://github.com/laravel/framework/issues/15991

**Comment by netdragoon** [comment]
The current version is `1.0.32`, but run the command `composer update league/flysystem` and on the console said that is already updated. 

**_Continues with the same problem_** 

@sisve 

Do you have any application running you can do an upload photos?

**Comment by sisve** [comment]
@netdragoon I'm on 5.1 LTS and havn't tried to reproduce this issue. I do not have the Pictures model and cannot use the code you provided to reproduce the issue. 

As other have mentioned, getRealPath() returns null here: https://github.com/laravel/framework/blob/5.3/src/Illuminate/Filesystem/FilesystemAdapter.php#L119
This happens if the file does not exist, according to https://secure.php.net/manual/en/splfileinfo.getrealpath.php

**Comment by netdragoon** [comment]
@sisve e @themsaid 

I prepared a test on the Linux OS (UBUNTU 16.04.1) but also no success, below the code unsuccessfully


**_HTML_**

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,600"
               rel="stylesheet" type="text/css">
    <script src="/js/jquery-2.2.4.min.js"></script>
    <title>Laravel</title>
</head>
<body>
<form action="{{route('pictures.store')}}" method="post" enctype="multipart/form-data">
    {{ csrf_field() }}
    <label>Picture/Photo:
        <input type="file" name="picture" id="picture" accept="image/*"/>
    </label>
    <button>Send</button>
</form>
</body>
</html>
```

**_Controller_**

```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;

class SavePictureController extends Controller
{
   
    public function index()
    {
        return view('pictures');
    }
    public function store(Request $request)
    {
      //test 1 unsuccessfully 
       return $request->file('picture')->store('images'); //unsuccessfully 
       //test 2 successfully
       //move_upload_file($_FILE['picture']['tmp_name'], 'images/0001.jpg'); //successfully
    }
}
```

**_Route_**

```
Route::get('pictures', ['as' => 'pictures.index', 'uses'=>'SavePictureController@index']);
Route::post('pictures/store', ['as' => 'pictures.store', 'uses'=>'SavePictureController@store']);
```

**_Obs:_** `move_upload_file($_FILE['picture']['tmp_name'], 'images/0001.jpg')`; successfully

**Comment by netdragoon** [comment]
@sisve e @themsaid

`storeAs` save file in the folder **"storage"**
`move `save file in the folder **"public"**

Problem Solved
