### ISSUE TITLE
Illuminate\Support\Arr.php  bug introduced in recent versions 5.3

### ISSUE THREAD

**Issue by SunChero** [laravel/framework#16031]
- Laravel Version: 5.3.18-19
- PHP Version:
- Database Driver & Version:

### Description:
this function return $key instead of $value !
call_user_func($callback, $value, $key)  should be call_user_func($callback, $key, $value)

`
**public static function first($array, callable $callback = null, $default = null)
    {
        if (is_null($callback)) {
            if (empty($array)) {
                return value($default);
            }

            foreach ($array as $item) {
                return $item;
            }
        }

        foreach ($array as $key => $value) {
            if (call_user_func($callback, $value, $key)) {
                return $value;
            }
        }

        return value($default);
    }**`

**Comment by themsaid** [comment]
Check the upgrade guide https://laravel.com/docs/5.3/upgrade

**Comment by themsaid** [comment]
> Key / Value Order Change
>The first, last, and where methods on the Arr class now pass the "value" as the first parameter to the given callback Closure. For example:

**Comment by SunChero** [comment]
my bad .. i should then submit a bug to the laravel\cashier package since they still use the old config

thanks
