### ISSUE TITLE
Setting query builder orders to empty array throws sql exception

### ISSUE THREAD

**Issue by EspadaV8** [laravel/framework#16035]
- Laravel Version: 5.1.35
- PHP Version: 7.0.12
- Database Driver & Version: pgsql 9.4
### Description:

Attempting to clear the `orders` property on a query builder by setting it to an empty array throws a database exception.
### Steps To Reproduce:

Create a query and call `$query->orders = []` before trying to run it.

This is because the compile methods don't check for empty arrays and assume that they will be `null`. This isn't what the PHPDocs say for the `orders` property though (they list it as `@var array`). I'm assuming that this will also be an issue for the other properties on the class too. The `compile` methods should probably check that their arrays aren't empty before processing them.

**Comment by EspadaV8** [comment]
I believe the following 3 line change inside `Grammar.php` (the `compileOrders` method) will fix the issue

```php
        if (!is_array($orders) || count($orders) === 0) {
            return '';
        }
```

**Comment by vlakoff** [comment]
This change might be incomplete, in various places there are `is_null` or `isset` checks.

**Comment by EspadaV8** [comment]
Yeah, I thought that might be the case. The property shouldn't ever be allowed to be set to `null` and instead only allow array values. It'd simplify a lot of the checks and make things more consistent. That would require re-writing a load of code though (and at the same time should probably be done with the other public properties too) and would be a BC change.

**Comment by vlakoff** [comment]
Just to point out some easily missed parts:
* `orders` is checked for `!is_null` in Grammar `compileComponents`, amongst many other properties…
* also it is checked for `!isset` in SqlServer Grammar `compileAnsiOffset`
