### ISSUE TITLE
Reopening Issue: Laravel JSON Mysql number comparison query does not work #14011

### ISSUE THREAD

**Issue by y471n** [laravel/framework#16042]
- Laravel Version: 5.3 
- PHP Version: 7
- Database Driver & Version: mysql 5.7

**Description:**
$query->where('player->rank', '>', 2);

this does not seem to work.

Laravel creates a mysql query for this like.. 
select * from from users whereplayer->"$.rank" > '2'; 
The single quoted numerical value works in case of normal columns, but not in case of JSON columns.

This was said to have been cleared in 5.3 but still the case.

**Comment by themsaid** [comment]
The generated sql based on your example is `select * from `users` where `player`->"$.rank" > 2` which is correct, here's the check we use:

```
is_int($value) ? PDO::PARAM_INT : PDO::PARAM_STR
```

So `is_int(2)` will return `true` leading to the use of `PDO::PARAM_INT`.

Please provide the full laravel version you're using, use `php artisan --version`

**Comment by y471n** [comment]
Thanks for such a quick response and so sorry, actually my query is of **float**

$query->where('player->rank', '>', 2.0);

This does not work in case of floats but does in case of integers. Could you help as to how solve this in case of floats.
