### ISSUE TITLE
CookieJar not working in 5.3.19

### ISSUE THREAD

**Issue by litan1106** [laravel/framework#16047]
- Laravel Version: 5.3.19
- PHP Version: 7.0
- Database Driver & Version:

### Description:
Cookie queue not working in Laravel Version 5.3.19
`Cookie::queue('voted', true, 2628000);`

I reverted back to Laravel Version 5.3.18, everything works fine.

**Comment by themsaid** [comment]
How does it not work? Please show a complete example we can use to replicate the issue.

**Comment by JC5** [comment]
I have similar issues. I cannot flash data, it doesn't arrive. Can't reproduce it yet though.

**Comment by GrahamCampbell** [comment]
What driver?

**Comment by JC5** [comment]
Memcached, PHP7.0.8, memcached 1.4.25 Ubuntu

**Comment by amrelnaggar** [comment]
Same issue here, I cannot flash data and cannot reproduce it. 
I reverted back to 5.3.18 and it works fine.

Laravel version: 5.3.19
Session driver: Cookie
PHP Version: 5.6.10

**Comment by GrahamCampbell** [comment]
5.3.18's session and cookie components are identical to 5.3.19.

**Comment by themsaid** [comment]
ping @litan1106

**Comment by sunscreem** [comment]
Not sure if related but my `error`'s were empty, and `old` was empty until I went back to 5.3.18.

**Comment by litan1106** [comment]
I couldn't reproduce it with a fresh install either.

**Comment by sunscreem** [comment]
Could it be something like bugsnag or clockwork causing it?

**Comment by themsaid** [comment]
> I couldn't reproduce it with a fresh install either.

Closing then, for other commenters please open new issues stating the problem in details with a simple example that would help others replicate the problem.
