### ISSUE TITLE
Query Params in request object for Resource Controllers

### ISSUE THREAD

**Issue by SolStis86** [laravel/framework#16040]
- Laravel Version: 5.2.x
- PHP Version: 70
- Database Driver & Version: MariaDB

### Description:
When trying to draw query string data from resource routes, the Request object injected into the method does not seem to work properly....

### Steps To Reproduce:

e.g. GET /api/v1/resource?foo=bar -> index action on controller 

.....

public function index (Request $request) {
    $request->has('foo') // false - should be true no?
}

i can work around with:

parse_str(parse_url($request->fullUrl(), PHP_URL_QUERY));

to draw the params into vars however using the Request object would be tidier...
....

**Comment by themsaid** [comment]
Can't reproduce the issue on a fresh 5.3 instance, please upgrade to 5.3 as 5.2 is not supported anymore.

Feel free to ping me if you could reproduce the issue on a 5.3 instance.

**Comment by lagbox** [comment]
what webserver btw?

**Comment by SolStis86** [comment]
Nginx from - homestead 4 box
