### ISSUE TITLE
Table left behind on QueryException

### ISSUE THREAD

**Issue by Someweb** [laravel/framework#16045]
- Laravel Version: 5.3
- PHP Version: 5.6.4
- Database Driver & Version: Mysql

### Description:
When a migration gets run that has an QueryException error the table gets created and left behind rather then rolled back. Causing you to manually go into the database and remove the table.
Rerunning the migrations would cause another error because the table already exists.

### Steps To Reproduce:
1) Create 2 migrations
2) Have the first migration add a foreign key constraint to the second table
3) run migrations

**Comment by themsaid** [comment]
This is a known issue, in case of errors you'll need to handle cleaning by yourself.
