### ISSUE TITLE
Blade compliation bug when using the word "or"  with relation property

### ISSUE THREAD

**Issue by elbakly** [laravel/framework#16053]
- Laravel Version: 5.2 didn't try it in other versions
- PHP Version: 7
- Database Driver & Version: MariaDB

### Description & Steps To Reproduce:
when using the blade` {{ $user->post->title or ''}}` works in earlier version of php but in php7 it deals with it as logical expression `||` instead.
though if you used `{{$user->name or ''}}` it will work normally even in php7

**Comment by GrahamCampbell** [comment]
Thanks for the report. This is a known bug marked as no-fix. The plan is to just remove this syntax in favour of php 7's `??` syntax once we drop PHP 5.
