### ISSUE TITLE
Create Quickstart tutorial for 5.3

### ISSUE THREAD

**Issue by akoper** [laravel/framework#16058]
- Laravel Version: 5.3
- PHP Version: na
- Database Driver & Version: na

### Description:
I am trying to teach myself "Laravel 5" - the current version of Laravel (Larvel 5.3).  I am using the Quickstart tutorial: https://laravel.com/docs/5.2/quickstart.  The most recent Quickstart tutorial is for 5.2.  Laravel's tutorial breaks at routing - https://laravel.com/docs/5.2/quickstart#routing - because routes.php has gone away.  This kind of screws anyone trying to learn Laravel 5.  Please create a Quickstart tutorial  for 5.3.

**Comment by danielbaylis** [comment]
You might want to check out [Laracasts](https://laracasts.com/series/whats-new-in-laravel-5-3) in the meantime.

**Comment by themsaid** [comment]
@akoper laracasts.com is a good place to start with :)
