### ISSUE TITLE
Autocomplete for Laravel

### ISSUE THREAD

**Issue by akoper** [laravel/framework#16065]
I use autocompletes a lot when I am making an application.  There is a form, and the user needs to enter a value for one of the form fields from a list of values that are in the database table (foreign key relationship).  Laravel makes text, radio, checkbox, etc. inputs.  Can Laravel make an autocomplete input, too?  This is becoming a very basic type of form field.  The next-best, normal of way making autocompletes with jQuery UI autocomplete is messy and inelegant, with hidden form fields for the id, and hacking it so the name shows in the input field, etc.  If Laravel had some elegant, beautiful, native way to make form field autocompletes, this would be a powerful selling point for developers; save a lot of work; be a great, legitimate use of the framework; and increase Laravel's adoptions and use.

**Comment by themsaid** [comment]
The Forms aren't maintained by Laravel core team anymore, please send your suggestion to the Laravel Collective repository, you can find it here https://laravelcollective.com/docs/5.3/html

**Comment by akoper** [comment]
Thanks for mentioning the Laravel Collective.  This seems to be so new, I - and I bet a lot of developers - had not heard of it before.  (Also, Form helper crashed my view in L 5.3.  Why is in the API for 5.3?)
