### ISSUE TITLE
Mysql json float number comparison doesn't work

### ISSUE THREAD

**Issue by y471n** [laravel/framework#16063]
- Laravel Version: 5.3.9
- PHP Version: 7.0.11
- Database Driver & Version: Mysql, Mysql version: 5.7.15

$query->where('player->rank', '>', 2.0); 

This does not compare since, Laravel code checks for integer else converts the mysql query for string comparison which does not work in JSON columns.

Thanks.

**Comment by themsaid** [comment]
Fix submitted https://github.com/laravel/framework/pull/16069
