### ISSUE TITLE
[5.3] Validator optimization

### ISSUE THREAD

**Issue by PetarDambovaliev** [laravel/framework#16071]
Long operation is the current code and short operation is my optimization.

Mine is searching in a hash table which is O(n)
the current code uses array_unique which uses O(n·log n)

My optimization is exponentially faster the bigger the load gets. 

https://postimg.org/image/j77vv9q8n/

**Comment by GrahamCampbell** [comment]
> My optimization is exponentially faster the bigger the load gets.

Not exponentially faster. Faster by at best a factor of O(log(n)). We're open to PRs please. :)
