### ISSUE TITLE
Validation error with "Exists" rule

### ISSUE THREAD

**Issue by Milewski** [laravel/framework#16078]
- **Working Version**: Illuminate/Validation: **5.3.4**
- **Broke Version**: Illuminate/Validation: **5.3.16** (probably any above 5.3.4 i didn't test all)
- PHP Version: PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.7.15, for Linux (x86_64)

### Description:

Something happened with this validation... it was working suddenly on the latest version everything broke

i get this error message

```
Fatal error:  Uncaught Error: Call to undefined method Symfony\Component\Translation\Translator::get() in /var/www/housekeeper/vendor/illuminate/validation/Validator.php:2246
Stack trace:
#0 /var/www/housekeeper/vendor/illuminate/validation/Validator.php(2188): Illuminate\Validation\Validator->getAttribute('room_id')
#1 /var/www/housekeeper/vendor/illuminate/validation/Validator.php(732): Illuminate\Validation\Validator->doReplacements(':attribute \xE4\xB8\x8D\xE5...', 'room_id', 'Exists', Array)
#2 /var/www/housekeeper/vendor/illuminate/validation/Validator.php(715): Illuminate\Validation\Validator->addError('room_id', 'Exists', Array)
#3 /var/www/housekeeper/vendor/illuminate/validation/Validator.php(546): Illuminate\Validation\Validator->addFailure('room_id', 'Exists', Array)
#4 /var/www/housekeeper/vendor/illuminate/validation/Validator.php(461): Illuminate\Validation\Validator->validateAttribute('room_id', 'Exists')
#5 /var/www/housekeeper/vendor/illuminate/validation/Validator.php(486): Illuminate\Validation\Validato in /var/www/housekeeper/vendor/illuminate/validation/Validator.php on line 2246
```

### Steps To Reproduce:

validate something using these rules

```
$rules = [
  'user_id' => 'required|users,id,deleted_at,NULL'
]
```

The problem here is with the "deleted_at,NULL" which previously was working... 

as laravel will validate even if the user has been trashed... so its important to add deleted_at check on the validation...

**The error will occur if you do have a trashed entry on the database**

### Additional info...

im using the validation out of laravel using this package 

```
"Illuminate/Validation": "^5.3",
```

and i am using it like 

```
$translator = new \Symfony\Component\Translation\Translator('cn');
$translator->addLoader('json', new \Symfony\Component\Translation\Loader\JsonFileLoader());
$translator->addResource('json', __DIR__.'/validation.json', 'cn');

$validator = new \Illuminate\Validation\Factory(
  $translator, new \Illuminate\Container\Container()
);

$validator->setPresenceVerifier(
  new DatabasePresenceVerifier(.......)
);

$validator->make(.....);
```

**Comment by sisve** [comment]
Uhm. Well, the [TranslatorInterface](https://github.com/symfony/translation/blob/v3.1.5/TranslatorInterface.php) doesn't expose a get() method and Symfony's Translator does not have one. Wonder if that code has ever worked.

Anyhow, related PR: https://github.com/laravel/framework/pull/15563

**Comment by Milewski** [comment]
well... it do works.. and i made a repository reproducing the error.. all u need to do is run the code even with a local php on your machine... 

then change the composer version from `"Illuminate/Validation": "5.3.4" `to `"Illuminate/Validation": "5.3.16"`

and you will see the bug...

[https://github.com/Milewski/ValidationBUG](https://github.com/Milewski/ValidationBUG)

**Comment by themsaid** [comment]
Yes we started using the `get()` method recently which doesn't exist in Symfony's Translator, I agree this is a breaking change but it was introduced really long time ago not sure if we should revert this change after 1 month.

Anyway we are completely abandoning Symfony's translator in 5.4 which is planned for next month so I really recommend that you start using Laravel's Translator from now.

**Comment by Milewski** [comment]
my project haven't being touch for a month too... then i come to update some things on it.. i faced this issue... its no i have tried to migrate to the new Illuminate/Translation ... but seems things didn't worked with json.. looks i need to make my own implementation on this one.

**Comment by ebisbe** [comment]
@themsaid I had the same error and finally arrive to this thread. Can you link Laravel's Translator or explain how to switch it?

thanks

**Comment by themsaid** [comment]
Don't pass the Symfony Translator, use Laravel's translator instead.

**Comment by Milewski** [comment]
@ebisbe now you would go with something like this

```

use Illuminate\Filesystem\Filesystem;
use Illuminate\Translation\FileLoader;
use Illuminate\Translation\Translator;
use Illuminate\Validation\Factory;
use Illuminate\Container\Container;

$loader = new FileLoader(
  new Filesystem(),'/Translations'
);

$translator = new Translator($loader, 'cn');

$translator->setLocale('cn');
$translator->setFallback('cn');

$validator = new Factory(
 $translator, new Container()
);

```

the impact it had in my code was that now i need to keep my translations files inside a "laravel structured way" **/translations/cn/validation.php** which is different from what i was using before... even the file type.. was json.. now php array...

**Comment by ebisbe** [comment]
Thanks @Milewski ! I've updated the code an all tests are passing.
