### ISSUE TITLE
Memory Leak from Queues / Crons

### ISSUE THREAD

**Issue by JoelGross** [laravel/framework#16074]
- Laravel Version: 5.3
- PHP Version: 5.6.15
- Database Driver & Version: MySQL

### Description: 

When upgrading a Laravel 5.0 platform up through 5.3, if you use the old Queue::push method instead of dispath(), the CRON job for some reason ends up continuously growing and eating all the memory on the system.  The upgrade guide https://laravel.com/docs/5.3/upgrade#upgrade-5.3.0 should be updated to indicate that you must update the Queue::push to dispatch(). That seems to have fixed my memory leak issue.

See comment below - this did not actually work.

**Comment by JoelGross** [comment]
Actually, that seems to not have been the issue. I still have the memory leak, but when I manually do "php artisan queue:restart", it clears the entire memory (7 GB). Any idea why this would be occurring? Do I need to set crontab to run that command every two hours or something? Or how can I actually fix the issue?

**Comment by sisve** [comment]
The queue system has changed in 5.3 to use daemon-mode per default, while it was an opt-in in 5.0. The daemon mode has a default memory limit of 128 MB, if the amount of allocated memory exceeds this the queue:work process shuts down and it's up to supervisor to start it again. Your description implies that this doesn't work.

Can you show us your supervisor configuration?

**Comment by themsaid** [comment]
@JoelGross please share the queue driver you use

**Comment by JoelGross** [comment]
Thank you! I was using cron to the queue:work every minute. I disabled that and enabled forge to manage the queue. 

My fault :).
