### ISSUE TITLE
[5.2] PostgreSQL pagination with where

### ISSUE THREAD

**Issue by schleumer** [laravel/framework#16086]
- Laravel Version: 5.2.45
- PHP Version: 7.0.12
- Database Driver & Version: PostgreSQL 9.5

### Description:

When using pagination within `where` clauses i'm getting the following error:

```
SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "ABC" (SQL: select count(*) as aggregate from "table" where "column" = ABC)
```

### Steps To Reproduce:

Use the following code:

```
MyModel::where('column', '=', 'ABC')
            ->paginate(3)
```

**Comment by themsaid** [comment]
Please upgrade to Laravel 5.3 as 5.2 is no longer supported.

**Comment by schleumer** [comment]
Thanks, i think there's no other way, ehe.

![9f9](https://cloud.githubusercontent.com/assets/2557681/19656825/49129c1c-9a00-11e6-93cd-4c327184db60.png)

**Comment by schleumer** [comment]
Upgraded to 5.3 and the bug still there.

**Comment by schleumer** [comment]
Kinda was my fault, PostgreSQL fails when some value is not castable to the column type, i will find a way to work around it.
