### ISSUE TITLE
Laravel view cache and custom blade directive

### ISSUE THREAD

**Issue by harish-php** [laravel/framework#16084]
- Laravel Version: 5.3
- PHP Version: 5
- Database Driver & Version:

### Description:

 I have developed custom blade directive and i am returning something dynamic html string (rendering a specific view with DB data ). Now what happens the blade-layout where i have added my custom directive does not reflects new values from DB , Unless i clear compiled view for that blade-layout ( which contains custom directive ) , I think it would not be good idea to clear compiled views for each request.

I want to achieve the reusable components across my application ( widgets )

**Comment by themsaid** [comment]
You can't do that, this approach means you'll have to abandon cache completely since the view to be rendered can change anytime and there will be no way to notify the View factory that this view was changed.

I suggest that you change how you approach this, save HTML in the DB maybe but not blade syntax, that way you won't need to recompile.

**Comment by harish-php** [comment]
Thanks for confirming.

**Comment by stront90** [comment]
The easiest way is to delete cached file. But how to determine which?

**Comment by tannerntannern** [comment]
I know this is an old discussion, but I found a possible workaround.  In my case, I wanted a `@pagecontent(blockname)` directive that would load page content from the database, identified by the page url and name of the content block.

My Blade directive looks like this:
```php
Blade::directive('pagecontent', function($blockname) {
      $path = Request::path();
      return
          "<?php echo \"<div data-editable data-name='$blockname'>"
          . "\" . \\App\\PageContent::find(['page' => '$path', 'block_name' => '$blockname'])->content . \""
          . "</div>\"; ?>";
});
```

So now when I use `@pagecontent(main)` in my `index.blade.php` file, the directive renders as,
```php
<?php echo "<div data-editable data-name='main'>" . \App\PageContent::find(['page' => '/', 'block_name' => 'main'])->content . "</div>"; ?>
```
which __does__ update when the database changes.

Hope this can be useful to somebody!

**Comment by bderubinat** [comment]
I came across same misunderstanding of how custom blade works.

**Wrong**:
```
Blade::directive('your_blade', function () {
  return your_function();
});
```
Because this would cache the result of `your_function()`.

**Do this**:
```
Blade::directive('your_blade', function () {
  return "<?php your_function(); ?>";
});
```
This would just cache `<?php your_function(); ?>` without calling it

**Comment by mfth12** [comment]
hai
