### ISSUE TITLE
Getting JSON Data From Request Isn't Intuitive

### ISSUE THREAD

**Issue by mdavis1982** [laravel/framework#16082]
- Laravel Version: 5.3.19
- PHP Version: 7.0.0
- Database Driver & Version: n/a

### Description:
When sending a JSON request to a controller, it's not intuitive to get the JSON data out from the `$request` parameter.

For example, assuming I've sent a JSON payload that contains:

```json
{
    "name": "Foo"
}
```

Then the following is what happens:

```php
<?php

...

public function store(Request $request)
{
    var_dump($request->has('name')); // True
    var_dump($request->get('name')); // null
    var_dump($request->name)); // "Foo"
    var_dump($request->json('name')); // "Foo"
}
```

I understand what's going on here, but if `->has('name')` returns `true`, I would expect `->get('name')` to return the value, rather than `null`.

Could this be improved by reimplementing `get()` on the `Illuminate\Http\Request` class, rather than using the Symfony provided one to make it JSON-aware? Or is there a reason that that shouldn't happen?

### Steps To Reproduce:
Send a JSON payload to a controller action, and attempt to access a parameter as above.

**Comment by themsaid** [comment]
Here's the reason from the docblock of the Symfony's methods:

```
* This method is mainly useful for libraries that want to provide some flexibility. If you don't need the
* flexibility in controllers, it is better to explicitly get request parameters from the appropriate
* public property instead (attributes, query, request).
```

Use `Request::input()` instead of `Request::get()`, it's the laravel method for retrieving an input from the request.
