### ISSUE TITLE
Eloquent accessors that return a Carbon object are not properly cast to string when the model is serialized

### ISSUE THREAD

**Issue by ArondeParon** [laravel/framework#16083]
My model looks something like this:

```
protected $dates = ['date', 'delayed_date', 'real_date'];
protected $appends = ['real_date'];
[...]
public function getRealDateAttribute()
{
    if ($this->isDelayed()) {
        return $this->delayed_date;
    } else {
        return $this->date;
    }
}
```

This works fine. However, when the model is cast to an array, it looks like this:

```
"date" => "2011-01-01 00:00:00",
"delayed_date" => "2012-11-02 00:00:00",
"real_execution_date" => Carbon\Carbon {
    "date": "2012-11-02 00:00:00.000000",
    "timezone_type": 3,
    "timezone": "Europe/Amsterdam",
}
```

In this case, I would expect `real_date` to be of a string type as well. 

Alternative solutions to my problem are insufficient:
- Returning and serializing the Carbon object would make APIs confusing: the date would have to be parsed
- Returning ONLY a string type would break my application, since I would need to convert my string back to a Carbon object in my controllers/views.

The _solution_ to this problem would be to respect the `$dates` property for accessors as well, so that we can have more control over the way these properties are handled.

Would love some feedback on this.

**Comment by sisve** [comment]
This sounds like a major breaking change and would also break how php how works. On the other hand, I do not know of any magical method in php you can use to catch the cast-to-array operation to convert the values.

Is this an attempt to let your database model build api results? Don't do that, add a separate layer that builds the arrays/json _from_ the database models. This means that you can rename columns and do other database changes and just adjust this layer to fix any [otherwise] breaking changes.

> If an object is converted to an array, the result is an array whose elements are the object's properties. The keys are the member variable names, [...]

Source: https://secure.php.net/manual/en/language.types.array.php#language.types.array.casting

**Comment by seanmangar** [comment]
Sisve is right. If this is for an API, you should introduce a transformation layer for the following reasons:

1. Prevent database schema changes from breaking your API
2. Perform type-casting
3. Include relationships
4. Support pagination of data results
5. Any other processing you need to do. In your case this would be to convert the real execution date to a JSON date.

There is a great package that lets you do this:
http://fractal.thephpleague.com/

**Comment by ArondeParon** [comment]
Good points, thanks for the feedback! Adding a separate transformation layer looks like a good idea.

In this case, however, I am still not entirely convinced about whether this would be a breaking change. All I suggest is to have the `$dates` property apply to accessors as well. Since it is already possible to add database columns to `$dates`, resulting in automagical type conversions (string to Carbon, Carbon to string), I don't really see why it would be such a bad idea to make this behaviour apply to accessors as well.

Would love some feedback.

**Comment by themsaid** [comment]
Having a mutator Eloquent assumes you want to have full control over the attribute, thus why we skip it from further date casting: https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Eloquent/Model.php#L2440

You need to use a transformation layer as mentioned to have better control over what your API returns.
