### ISSUE TITLE
middleware sorting rewrite killed ValidatesRequest::validate for me

### ISSUE THREAD

**Issue by apreiml** [laravel/framework#16096]
- Laravel Version: 5.3.19
- PHP Version: 7

### Description:

I use the validate method from ValidatesRequest to validate my input. In case of validation errors i use the MessageBag stored in $errors in my blade views to give the user some feedback.

Upgrading from 5.3.18 to 5.3.19 broke this behavior. I found out that this commit may have broken it:

https://github.com/laravel/framework/commit/6b69fb81fc7c36e9e129a0ce2e56a824cc907859
 
If I revert only the sortMiddleware method, it works again.

**Comment by apreiml** [comment]
It turned out that I accidentally used the same middle ware group twice on some routes. The old sorting algorithm got rid of the duplicate The new one doesn't get rid of the duplicates and also sorts it incorrectly.

**Comment by themsaid** [comment]
Regarding the unique middleware filtration, that was fixed and will be available in the next release.

> also sorts it incorrectly.

Can you share more details please?

**Comment by apreiml** [comment]
I have this middleware priority setup: 
```
array:5 [▼
  0 => "Illuminate\Session\Middleware\StartSession"
  1 => "Illuminate\View\Middleware\ShareErrorsFromSession"
  2 => "Illuminate\Auth\Middleware\Authenticate"
  3 => "Illuminate\Routing\Middleware\SubstituteBindings"
  4 => "Illuminate\Auth\Middleware\Authorize"
]
```
After sorting with the new SortedMiddleware plus duplicate middlewares I got this:

```
array:16 [▼
  0 => "Illuminate\Cookie\Middleware\EncryptCookies"
  1 => "Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse"
  2 => "Illuminate\Session\Middleware\StartSession"
  3 => "Illuminate\Session\Middleware\StartSession"
  4 => "Illuminate\View\Middleware\ShareErrorsFromSession"
  5 => "App\Http\Middleware\VerifyCsrfToken"
  6 => "App\Http\Middleware\LanguageMiddleware"
  7 => "Illuminate\View\Middleware\ShareErrorsFromSession"
  8 => "Illuminate\Routing\Middleware\SubstituteBindings"
  9 => "Illuminate\Cookie\Middleware\EncryptCookies"
  10 => "Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse"
  11 => "App\Http\Middleware\VerifyCsrfToken"
  12 => "App\Http\Middleware\LanguageMiddleware"
  13 => "Illuminate\Routing\Middleware\SubstituteBindings"
  14 => "App\Http\Middleware\Authenticate"
  15 => "App\Http\Middleware\ModuleCheck"
]
```
Take a look at the Authenticate Middleware. It's located after SubstituteBindings.

**Comment by themsaid** [comment]
Can you please share your route & middleware definitions?

**Comment by apreiml** [comment]
Ah, of course I didn't alter the priority to use my own Authenticate middleware.

Thanks!
