### ISSUE TITLE
How to display errors for multiple files array validation properly?

### ISSUE THREAD

**Issue by yammadev** [laravel/framework#16093]
I've been stuck in a kind of bug for 2 days so far and I'm really desperate. I'm trying to validate a multiple input file with others fields, the validation works as expected, but the problem is when I want to know in which field the error was in order to display the proper message.

I'm using something like: 

```
      $rules = [
        'field_1'      => 'rule',
       ....
       ....
        'images.*' => 'required|mimes:jpeg,bmp,png,gif|max:20000'
      ];

    $messages = [
        'field_1.required'         => 'message',
       ....
       ....
        'images.*.required'         => 'message_required',
        'images.*.mimes'            => 'message_required',
        'images.*.max'              => 'message_required'
      ];

      $validator = Validator::make($request->all(), $rules, $messages);

      if ($validator->fails()) {
        return Redirect::back()                                                 
                       ->withErrors($validator)                                
                       ->withInput();                                          
      }
```

Which is the correct way to display errors for the multiple files in blade template? I hope you could help me (I'm not used to ask for help, but I could not make it work).  PS. Nice work with the framework, let me know if you're receiving donations :smile: 

- Laravel Version: 5.2.*
- PHP Version: 5.5.9

**Comment by themsaid** [comment]
That was taken care of in 5.3, please upgrade as 5.2 is no longer supported :)

**Comment by yammadev** [comment]
It doesn't seem to work yet! I've already upgrade to version 5.3. And I'm getting the same issue!

thanks,
