### ISSUE TITLE
Iluminate/Mail sending batch email using Mailgun SMTP

### ISSUE THREAD

**Issue by oxy-code** [laravel/framework#16099]
I am trying to get Batch Sending to work over SMTP, but even though I'm sending to multiple recipients and I've specified user variables (and the variables are getting replaced successfully in the email that is sent), every single recipient shows up in the To: field of the resulting messages at the receiver.

**Email code (below):**
```

Mail::send('emails', ['body'=> $bodyMsg], function($message) use ($fromAddr, $fromName, $toAddr, $subject, $recipientVariables){
                $message
                    ->from($fromAddr, "Coach %recipient.lead_coach%")
                    ->to(['velmurugan@proisc.com', 'bright@proisc.com'])
                    ->subject($subject);
                $message->getSwiftMessage()->getHeaders()->addTextHeader('X-Mailgun-Recipient-Variables', $recipientVariables); // json encoded string
            });


```

I'm sure that 'X-Mailgun-Recipient-Variables' value is added to the header. For your reference see below

```
Message-ID: <8dd9d6bbfdac3bd97b6d134d1c073303@127.0.0.1>
Date: Mon, 24 Oct 2016 10:47:58 -0400
Subject: Testing Mailgun
From: "Coach %recipient.lead_coach%" 
To: velmurugan@proisc.com, bright@proisc.com
MIME-Version: 1.0
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable
X-Mailgun-Recipient-Variables: {"velmurugan@proisc.com": {"first_name":
 "alana","email": "velmurugan@proisc.com","lead_coach": "Merle","unique_id":
 213701},"bright@proisc.com": {"first_name": "al","email":
 "bright@proisc.com","lead_coach": "Chris","unique_id": 213702}}
```

I put in a mailgun trouble ticket yesterday (after 24 hours) still there is no reply from them. I got another resource from here (http://stackoverflow.com/questions/37948729/mailgun-smtp-batch-sending-with-recipient-variables-shows-all-recipients-in-to-f?rq=1) and it also not worked for me.

So please anyone can help out on this.

**Comment by themsaid** [comment]
Please try on the forums, this repo is for bug reporting only.

**Comment by oxy-code** [comment]
Since I'm a new user of laravel, can you please share forum url?
