### ISSUE TITLE
"php artisan make:model Models/Post -m -c" creates controller starting with lower-case

### ISSUE THREAD

**Issue by yusufyilmaz** [laravel/framework#16097]
- Laravel Version: 5.3.19
- PHP Version: 7.0.8

### Description: 
I have been trying new controller command on artisan. I have seen all controllers start with "CapitalLetterController". But this command creates lower-case "capitalLetterController" I believe it is not a bug but the convention is not persisting anymore which controllers start with capital letters.

### Steps To Reproduce: 
1. `php artisan make:model Models/Post -m -c `
2. Checkout the controller. 
3. you will see **p**ostController instead of **P**ostController (starts with lower-case leter)

**Comment by themsaid** [comment]
Just tested, a `PostController` was created. Can't regenerate your issue, are you sure that's the exact test case?

**Comment by yusufyilmaz** [comment]
That's interesting @themsaid I have retried the command and still creates `postController` using homestead.

**Comment by caiquecastro** [comment]
I'm having the same issue.

**Comment by caiquecastro** [comment]
`$controller = Str::camel(class_basename($this->argument('name')));`
on `ModelMakeCommand.php`

camel case retorna a primeira letra minúscula.

**Comment by themsaid** [comment]
That was fixed and will be available in the next release.

**Comment by caiquecastro** [comment]
I'd just checked the class and I saw it's now studly case. But I didn't find the commit that fixed it.

But it's fixed, so no more issue! Thank you!

**Comment by browner12** [comment]
https://github.com/laravel/framework/pull/15988
