### ISSUE TITLE
BUG? session()->pull() returning NULL instead of default value

### ISSUE THREAD

**Issue by theTrip73** [laravel/framework#16102]
- Laravel Version: 5.1.45
- PHP Version: 5.6.26
- Database Driver & Version: PostgreSQL 9.3.2

### Description:

As the subject line says, I was attempting a session pull with a default value, but instead of returning the default value, it was returning NULL.

I dug into the guts behind this functionality and wound up here -- https://github.com/laravel/framework/blob/v5.1.45/src/Illuminate/Support/Arr.php#L246 -- where the ```pull()``` method call ultimately winds up.

You can see there that once it gets into that foreach loop, it will simply return the ```$array[$segment]``` without regard for whether there is actually a value there, as long as that array key exists. This appears to be a bug, but I don't know what the original intent is. It seems to me that a default value should override a stored NULL value.

Does anyone else have thoughts on this?

### Steps To Reproduce:

Incredibly simple:

On first request, $session_uri winds up NULL, then:

```
session()->set('session_uri', $session_uri);
```

On second request, retrieve that session value, which is known to be NULL (and is shown as NULL in Laravel DebugBar's session tab), with a default:

```
dd( session()->pull('session_uri', '/') );
// outputs 'null'
```

**Comment by vlakoff** [comment]
Doesn't look like a bug to me. `null` is just handled as a possible value.

**Comment by theTrip73** [comment]
If there weren't an ```isset()``` check right above that ```foreach()``` loop, I'd be inclined to agree with you; however, if the intended goal of the default value is to replace NULL values, then it's definitely a bug.

**Comment by vlakoff** [comment]
Got it, you are talking about Laravel 5.1. There was indeed an inconsistency, that I had fixed for Laravel 5.2 with #12596 (in particular commit https://github.com/laravel/framework/pull/12596/commits/41aec8abcc86e1bee4d72c3bb86173368458df11).

There have been a handful of changes in Arr class at the epoch, with have made the class more consistent ultimately, but that had been quite a headache.

Because of BC, I'm confident nothing will be changed in Laravel 5.1 concerning this. You should consider null values to be inconsistently handled in Laravel 5.1 and be careful using them.

**Comment by theTrip73** [comment]
I should have posted this as an ```Arr``` issue, then I would have found that issue in my search! We're upgrading to 5.3 soon on this project, so I guess it will have that commit when we do.

It looks like your solution still returns ```null``` in this situation, though. Am I reading that correctly?

If so, that means that my code needs to look like this to solve for explicit ```null``` values:

```
$session_uri = session()->pull('session_uri', '/');

if ( ! $session_uri )
{
    $session_uri = '/';
}
```

Doesn't that seem silly/wrong?

**Comment by vlakoff** [comment]
In your case, null is handled as expected, even in Laravel 5.1.

You should avoid setting to null as you are doing here. I'm pretty sure you can write the code differently.

**Comment by theTrip73** [comment]
Yes, the code can be written differently, obviously, but that doesn't mean that Laravel shouldn't make more sense in the way this is handled.

What you are saying here is that we (Laravel users) are expected to avoid inadvertently storing explicit null values inside of arrays/session/etc. What that actually requires, if we want our ```session()->get()``` and session()->pull()``` default values to work properly is to either...

(1) Wrap any ```session()->set()``` or ```session()->put()``` call with an ```is_null()```:

```
if ( ! is_null($value) )
{
    session()->put('key', $value);
}
```

; or (2) Just assign our default when we set the value:

```
session()->put('key', ! is_null($value) ? $value : 'default');
```

Neither of those options seems to be the best way to handle this.

**Comment by vlakoff** [comment]
As I said, `null` is just treated as a valid value here; it is not handled as a "not set" value.

**Comment by theTrip73** [comment]
I'm not misunderstanding you. I'm asking for an explanation.

Can you tell me the benefit here of respecting an explicit ```null``` as opposed to treating it the same as an implicit ```null```, and allowing a cascade to the default?

**Comment by vlakoff** [comment]
I'm not the architect of this, but:
* That's simply how it has been designed from the beginning.
* There is a great benefit: you have one more state. You can explictly store `null` in session, there are use cases for this.

**Comment by theTrip73** [comment]
Your second bullet point indicates that you don't understand my position.

I am not arguing that ```null``` values should be ignored or excluded in these situations. I am arguing that if I set a default value in my retrieval call and the stored value is ```null```, it does not make sense to return anything other than the default value.

If you want the ```null``` state, don't set a default value in the retrieval call. I mean, that's why the default-less version of those calls exists, right?
