### ISSUE TITLE
JSON defualt value

### ISSUE THREAD

**Issue by hafezdivandari** [laravel/framework#16107]
- Laravel Version: 5.3.19
- PHP Version: 7.0.8
- Database Driver & Version: Mysql 5.7.15

### Description:
I have `documents` table with `parameters` JSON column and a model like this:

```
class Document extends Model {

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'parameters' => 'array',
    ];

}
```
JSON columns cannot have a default value in Mysql and no update will happen if the value of the column is NULL or empty, so according to [this](https://github.com/laravel/framework/issues/15433#issuecomment-247387178) suggestion, I use `stdClass` when create.

But It doesn't make sense to set JSON column to `stdClasss` on every single insertion and there should be a way to give it a default value of empty object `{}`.

I tried to use this mutator to set default value when empty but no chance:
```
    /**
     * Set the parameters.
     *
     * @param  string  $value
     * @return string
     */
    public function setParametersAttribute($value)
    {
        $this->attributes['parameters'] = empty($value) ? new stdClass() : $this->asJson($value);
    }


SQLSTATE[HY000]: General error: 1364 Field 'parameters' doesn't have a default value
````

I think Eloquent Model should set an empty object for JSON column types during creation.

### Steps To Reproduce:
1. JSON column doesn't accept default value.
2. Updating null JSON column is not possible.

**Comment by themsaid** [comment]
This is a MySQL thing :)

However if you have any suggested approaches to deal with the matter please feel free to open a PR.

**Comment by arctic-ice-cool** [comment]
> The workaround I'm going to use (reluctantly) is to add this to the Model with the JSON field:
> 
> ```
> protected $attributes = array(
>         'json' => '{}'
>     );
> ```

#15433 - [**arctic-ice-cool** commented](https://github.com/laravel/framework/issues/15433#issuecomment-262831450)

**Comment by ctrlaltdylan** [comment]
Oh the joy of little hacks. Here's a simple accessor that solved the issue for me (like @hafezdivandari I too have a `parameters` attribute on my model):

```
    /**
      * Silly accessor to make MySQL's JSON default value of 'null' place nice
      */
    public function getParametersAttribute($attributes) {
        if($attributes == 'null') {
            return [];
        }

        return $attributes;
    }
```

**Comment by dimer22zhc** [comment]
u can just do 
``` protected $casts = ['json']; ``` in your modal
