### ISSUE TITLE
Mass assignment not working with custom requests

### ISSUE THREAD

**Issue by mariaczi** [laravel/framework#16117]
- Laravel Version: 5.3.19
- PHP Version: 7
- Database Driver & Version: MySQL

### Description:

Mass assignment is not working with custom request. `$variable = new ModelName($request->input())`
giving no input to $variable and also even trying to return `$request->input()` is giving null.
It is working perfectly fine with out of the box request, but does not work with custom request.
### Steps To Reproduce:
Create custom request and try to use 
```
$variable = new ModelName($request->input())
```

**Comment by themsaid** [comment]
This is unrelated, it'll never work if `$request->input() = null` as you said. Check why it's null.

**Comment by themsaid** [comment]
Please ask for help on the forums as we keep this repo for bug reporting only.

**Comment by themsaid** [comment]
as a Hint, use `$request->all()` that's what you're looking for.
