### ISSUE TITLE
sort() on Collection grouped does not works

### ISSUE THREAD

**Issue by thematrix999** [laravel/framework#16126]
- Laravel Version: 5.3.21
- PHP Version: 7.0.10
- Database Driver & Version: MySQL 5.6.28

### Description:
sort() on Collection does not works

### STEP 1
this is my collection - $project->documents->toArray()
<pre>
Array
(
    [0] => Array
        (
            [id] => 2
            [revision] => 0
            [category] => other
            [name] => nome
            [pivot] => Array
                (
                    [project_id] => 1
                    [document_id] => 2
                    [created_at] => 2016-10-26 13:23:04
                    [updated_at] => 2016-10-26 13:23:04
                )
        )
    [1] => Array
        (
            [id] => 3
            [revision] => 0
            [category] => electrical
            [name] => nome del documento
            [pivot] => Array
                (
                    [project_id] => 1
                    [document_id] => 3
                    [created_at] => 2016-10-26 13:23:40
                    [updated_at] => 2016-10-26 13:23:40
                )
        )
    [2] => Array
        (
            [id] => 4
            [revision] => 0
            [category] => mechanical
            [name] => nome doc
            [pivot] => Array
                (
                    [project_id] => 1
                    [document_id] => 4
                    [created_at] => 2016-10-26 13:24:32
                    [updated_at] => 2016-10-26 13:24:32
                )
        )
    [3] => Array
        (
            [id] => 5
            [revision] => 0
            [category] => specs
            [name] => nome specs
            [pivot] => Array
                (
                    [project_id] => 1
                    [document_id] => 5
                    [created_at] => 2016-10-26 13:25:59
                    [updated_at] => 2016-10-26 13:25:59
                )
        )
)
</pre>

### STEP 2
this is my collection grouped - $project->documents->groupBy('category')->toArray()
<pre>
Array
(
    [other] => Array
        (
            [0] => Array
                (
                    [id] => 2
                    [revision] => 0
                    [category] => other
                    [name] => nome
                    [pivot] => Array
                        (
                            [project_id] => 1
                            [document_id] => 2
                            [created_at] => 2016-10-26 13:23:04
                            [updated_at] => 2016-10-26 13:23:04
                        )
                )
        )
    [electrical] => Array
        (
            [0] => Array
                (
                    [id] => 3
                    [revision] => 0
                    [category] => electrical
                    [name] => nome del documento
                    [pivot] => Array
                        (
                            [project_id] => 1
                            [document_id] => 3
                            [created_at] => 2016-10-26 13:23:40
                            [updated_at] => 2016-10-26 13:23:40
                        )
                )
        )
    [mechanical] => Array
        (
            [0] => Array
                (
                    [id] => 4
                    [revision] => 0
                    [category] => mechanical
                    [name] => nome doc
                    [pivot] => Array
                        (
                            [project_id] => 1
                            [document_id] => 4
                            [created_at] => 2016-10-26 13:24:32
                            [updated_at] => 2016-10-26 13:24:32
                        )
                )
        )
    [specs] => Array
        (
            [0] => Array
                (
                    [id] => 5
                    [revision] => 0
                    [category] => specs
                    [name] => nome specs
                    [pivot] => Array
                        (
                            [project_id] => 1
                            [document_id] => 5
                            [created_at] => 2016-10-26 13:25:59
                            [updated_at] => 2016-10-26 13:25:59
                        )
                )
        )
)
</pre>

### STEP 3
this is my collection grouped and sorted - $project->documents->groupBy('category')->sort()->toArray()
<pre>
Array
(
    [other] => Array
        (
            [0] => Array
                (
                    [id] => 2
                    [revision] => 0
                    [category] => other
                    [name] => nome
                    [pivot] => Array
                        (
                            [project_id] => 1
                            [document_id] => 2
                            [created_at] => 2016-10-26 13:23:04
                            [updated_at] => 2016-10-26 13:23:04
                        )
                )
        )
    [electrical] => Array
        (
            [0] => Array
                (
                    [id] => 3
                    [revision] => 0
                    [category] => electrical
                    [name] => nome del documento
                    [pivot] => Array
                        (
                            [project_id] => 1
                            [document_id] => 3
                            [created_at] => 2016-10-26 13:23:40
                            [updated_at] => 2016-10-26 13:23:40
                        )
                )
        )
    [mechanical] => Array
        (
            [0] => Array
                (
                    [id] => 4
                    [revision] => 0
                    [category] => mechanical
                    [name] => nome doc
                    [pivot] => Array
                        (
                            [project_id] => 1
                            [document_id] => 4
                            [created_at] => 2016-10-26 13:24:32
                            [updated_at] => 2016-10-26 13:24:32
                        )
                )
        )
    [specs] => Array
        (
            [0] => Array
                (
                    [id] => 5
                    [revision] => 0
                    [category] => specs
                    [name] => nome specs
                    [pivot] => Array
                        (
                            [project_id] => 1
                            [document_id] => 5
                            [created_at] => 2016-10-26 13:25:59
                            [updated_at] => 2016-10-26 13:25:59
                        )
                )
        )
)
</pre>

The sorting has no effects.

**Comment by themsaid** [comment]
Yes you need to map and sort inside each group:

```
$project->documents->groupBy('category')->map(function($groupItems){
    return $groupItems->sort(...);
})->toArray()
```

Also I think you need to sort by something, using `sort()` without parameters won't have effects as well.

**Comment by thematrix999** [comment]
I want order by category name.
"eletrical" first and "specs" last

<pre>
Array
(
    [electrical] => Array ( ... )
    [mechanical] => Array ( ... )
    [other] => Array ( ... )
    [specs] => Array ( ... )
)
</pre>

**Comment by thematrix999** [comment]
sort() without parameters HAVE effects!!!
https://laravel.com/docs/5.3/collections#method-sort

sort()

The sort method sorts the collection. The sorted collection keeps the original array keys, so in this example we'll use the values method to reset the keys to consecutively numbered indexes:
<pre>
$collection = collect([5, 3, 1, 2, 4]);
$sorted = $collection->sort();
$sorted->values()->all();
// [1, 2, 3, 4, 5]
</pre>

My keys are strings.

**Comment by thematrix999** [comment]
I have partially resolved with this: `$project->documents->sortBy('category')->groupBy('category')`
