### ISSUE TITLE
How to login with username or email or both and password in laravel 5.3 . 

### ISSUE THREAD

**Issue by jahid56** [laravel/framework#16128]
- Laravel Version: #.#.#
- PHP Version:
- Database Driver & Version:

**Comment by jahid56** [comment]
![12231](https://cloud.githubusercontent.com/assets/18249715/19766348/1a3cfc68-9c6f-11e6-826a-712bda853a4c.png)
I want to login with username or email. How can I achieve this.

**Comment by themsaid** [comment]
Please ask on the forums, we try to keep this repo for bug reporting only :)
