### ISSUE TITLE
[4.2.20] New PHP7 support does not work properly, Whoops must be updated.

### ISSUE THREAD

**Issue by bcalik** [laravel/framework#16123]
With the new v4.2.20 version with PHP7 support, error pages does not work properly because the old version Whoops itself does not support PHP7.

Here is the error I get:

```
Type error: Argument 1 passed to Whoops\Exception\Inspector::__construct()
must be an instance of Exception, instance of Error given, called in
/Volumes/data/www/bfy/dev/vendor/filp/whoops/src/Whoops/Exception/Inspector.php on line 80
```

@themsaid you should be responsible for this update, what do you think?
Maybe you should check this one: https://github.com/jadz/laravel-framework-4.2.18-php7
It is a laravel 4.2 fork with proper php7 support.

**Comment by morloderex** [comment]
@bcalik I don't think laravel 4 is supported any longer unfortunatly for you.

**Comment by bcalik** [comment]
@morloderex Laravel 4.2.20 is just released with PHP7 support.

**Comment by themsaid** [comment]
@bcalik how can I replicate this issue on a 4.2 installation? Also please show the full stack trace of the error, something doesn't look right here.

**Comment by bcalik** [comment]
Stack trace is completely different from what I see in Whoops.

Here is my stack trace.
And [this screenshot](https://cloud.githubusercontent.com/assets/9222368/19766144/eadc6f0e-9c54-11e6-91a3-6d1e026aaec5.png) is what i see in whoops.

```
[2016-10-27 14:49:45] development.ERROR: ErrorException: Access to undeclared static property: Arac::$field (View: /Volumes/data/www/bfy/dev/app/views/araclar/liste.blade.php) in /Volumes/data/www/bfy/dev/app/storage/views/f1d73a0a8941b6d2f9585308217d94bc:569
Stack trace:
#0 /Volumes/data/www/bfy/dev/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(45): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(Error), 1)
#1 /Volumes/data/www/bfy/dev/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/Volumes/data/w...', Array)
#2 /Volumes/data/www/bfy/dev/vendor/laravel/framework/src/Illuminate/View/View.php(140): Illuminate\View\Engines\CompilerEngine->get('/Volumes/data/w...', Array)
#3 /Volumes/data/www/bfy/dev/vendor/laravel/framework/src/Illuminate/View/View.php(109): Illuminate\View\View->getContents()
#4 /Volumes/data/www/bfy/dev/vendor/laravel/framework/src/Illuminate/View/View.php(78): Illuminate\View\View->renderContents()
#5 /Volumes/data/www/bfy/dev/vendor/laravel/framework/src/Illuminate/Http/Response.php(43): Illuminate\View\View->render()
#6 /Volumes/data/www/bfy/dev/vendor/symfony/http-foundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /Volumes/data/www/bfy/dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1501): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /Volumes/data/www/bfy/dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1036): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#9 /Volumes/data/www/bfy/dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 /Volumes/data/www/bfy/dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /Volumes/data/www/bfy/dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /Volumes/data/www/bfy/dev/vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/ClockworkLegacyMiddleware.php(20): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 /Volumes/data/www/bfy/dev/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Clockwork\Support\Laravel\ClockworkLegacyMiddleware->handle(Object(Illuminate\Http\Request), 1, true)
#14 /Volumes/data/www/bfy/dev/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#15 /Volumes/data/www/bfy/dev/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#16 /Volumes/data/www/bfy/dev/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#17 /Volumes/data/www/bfy/dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#18 /Volumes/data/www/bfy/dev/public/index.php(49): Illuminate\Foundation\Application->run()
#19 {main} [] []
```


--

I tried updating Whoops version to 2.*.
Now I get it working properly, but UI is broken. [Screenshot](https://cloud.githubusercontent.com/assets/9222368/19766291/bc143bce-9c55-11e6-9868-a7bcea88e93f.png).

**Comment by themsaid** [comment]
I'm sorry but I can't replicate this issue, if I throw an `ErrorException` the exception will be swapped with Symfony's `FatalThrowableException`:

		if (! $exception instanceof \Exception) {
			$exception = new FatalThrowableError($exception);
		}

Which then passed to Whoops and gets handled correctly cause by that time it's an `Exception`, from what I see in the stacktrace the passed instance is not of type Exception which means our code never ran in your application, please take a look at `Illuminate\Exception\Handler::displayException()` and make sure the above code exists.

**Comment by themsaid** [comment]
Please notice that if you're using a library that's not using Laravel's own exception handler you might have issues, since the library is not ready for PHP7. However Laravel 4.2.20 itself should run smoothly on PHP, that's why the stacktrace you shared doesn't look right, it looks like it's coming from a different library.

**Comment by bcalik** [comment]
I will try to make an example project that replicates the issue, in a few hours.

**Comment by themsaid** [comment]
In a fresh 4.2 installation, throw an `Error`.

**Comment by bcalik** [comment]
@themsaid Here a fresh 4.2 installation, this is how to reproduce.
https://github.com/bcalik/laravel-issue-16123-reproduce/blob/master/app/views/hello.blade.php#L9

Throw an `Error` on a blade view. It only happens in a **blade** view.

**Comment by themsaid** [comment]
Yeah i can replicate now, checking for a fix.

**Comment by themsaid** [comment]
Fixed in the attached PR.
