### ISSUE TITLE
Broadcasting localhost; broadcasting complex objects with pivot table entries; broadcasting softdeleted data

### ISSUE THREAD

**Issue by JCLengeling** [laravel/framework#16129]
- Laravel Version: 5.3.16
- PHP Version: 7.0.11
- Database Driver & Version: My main Database is Postgres 9.6, I also use Redis on windows to do my Broadcasting
### Description:

I am not sure if I am posting my issue at the right place; should there be a better place, feel free to point me to that place.

I have 3 odd Braodcasting related issues and for 2 of them kind of dirty solutions.

Right now I am developing on a Windows System. On the Server side I am using Laravel Echo Server (socket.io and redis ..... => without pusher https://github.com/tlaverdure/laravel-echo-server), the MSOpen version of Redis for microsoft (https://github.com/MSOpenTech/redis), Laravel 5.3 and Postgres 9.6. 
On my client side I am using Laravel Echo for the broadcasting and some other typical JS libraries for client side stuff. I am not using Vue though.

My first issue is related to using the laravel development server (php artisan serve) to test my application on my windows system. When I run that command I am able to use the application fine on localhost:8000. The localhost ip adress variant (127.0.0.1:8000) doesn't work. Because of this issue the laravel-echo-server is not able to authenticate my users. It will automatically change localhost:8000 to the ip adress variant and thus fail to connect. I am able to fix this by running: php artisan serve --host 127.0.0.1  This feels kind of dirty though. Is there a way to setup the laravel development server on windows so that I can use the localhost ip adress variant/ why is 127.0.0.1:8000 not available?

My second issue is related to the data I am broadcasting. Within my application I have a projects table. This table has a n:m relationship with my users table.  In the user-project pivot table I am storing which user is currently doing what in which project.  Within my broadcast I want to broadcast to all users in my application  what the users which are part of the project are currently doing in the project . My broadcastevent is setup in a way that the constructor receives the project as well as the pivot table data inside of it.  If I broadcast the project without doing anything else my clients will receive the project but will not receive the pivot table data. If I iterate over the entries in my pivot table within the broadcastOn method, my clients will receive the project data as well as the pivot table data. This "solution" feels super dirty and wrong. Why does it happen and what is the proper solution.

``` php
 $project = Project::with('users')->findOrFail($projectId);
 broadcast(new XYZ($project))->toOthers();
```

``` php
class XYZ implements ShouldBroadcast
{
 use InteractsWithSockets, SerializesModels;
 public $project;

 public function __construct(Project $p)
    {
        $this->project = $p;
    }

 public function broadcastOn()
    {
        $channels = array();
        foreach ($this->project->users as $u) {
          //without this loop the pivot table (->users) is not broadcasted
        }
        $users = User::all();
        foreach ($users as $user) {
          array_push($channels, new PrivateChannel('App.User.'. $user->id));
        }
        return $channels;
    }
}
```

The third issue occurs when I try to delete a project. Projects in my application are using soft delete functionality. If a project is deleted I want to basically broadcast to all members in that project that it got deleted.  This doesn't seem the work (my logging in the broadcastOn method of this event indicates that the broadcastOn method is not called).  I asume it doesn't work because of the softdelete (it works if I comment out the  $project->delete(); ); are there any special rules for broadcasting softdeleted objects?

``` php
 $project = Project::with('users')->findOrFail($projectId);
 broadcast(new XYZ2($project))->toOthers();
 $project->delete();
```

``` php
class XYZ2 implements ShouldBroadcast
{
 use InteractsWithSockets, SerializesModels;
 public $project;

 public function __construct(Project $p)
    {
        $this->project = $p;
    }

   public function broadcastOn()
    {
        $channels = array();
        Log::info('broadcastOn $this->project: '.$this->project); // nothing is written in Log file
        foreach ($this->project->users as $u) {
          array_push($channels, new PrivateChannel('App.User.'. $u->id));
        }
        return $channels;
    }
}
```

**Comment by sisve** [comment]
Have you tried using [Homestead](https://laravel.com/docs/5.3/homestead)?

**Comment by JCLengeling** [comment]
> Have you tried using Homestead?

Sadly using a vm is currently not an option for me.

**Comment by themsaid** [comment]
@JCLengeling still having this issue?

**Comment by JCLengeling** [comment]
I am still solving my first 2 problems in the described (as I feel dirty) way and I kind of solved the broadcasting softdeleted data issue.

I solved this issue by using the ShouldBroadcastNow interface instead of the ShouldBroadcast interface. So the issue might be that my event instances get put on a queue and as soon as it is the turn of the queued event some error occurs. 

I am kind of new to PHP and if I understand correctly PHP [should work in a “pass-by-value" way](http://stackoverflow.com/questions/879/are-php-variables-passed-by-value-or-by-reference). So
 in the construction of the event broadcast: `broadcast(new XYZ2($project))->toOthers();` the project should be passed as a value (not a reference) and thus deleting the original $project after basically creating a "copy" of the $project in the Broadcast Event instance shouldn't influence the copied value in the Broadcast Event instance.  

The outcome of my code (what I am seeing when I run my web application) kind of indicates that this understanding of mine is wrong or that there is a bigger issue. An indication that my understanding is wrong is actually my second issue. If it truly would be “pass-by-value" I shouldn't need to reiterate trough the previously (eager) loaded data.

**Comment by themsaid** [comment]
For your second issue, I think you need to load the relationship, when you run `$this->project->users` the relationship gets loaded and that's why it becomes available, try:

```
$this->project->load('users');
```

For your third issue, it's related to how we unserialize models, I'm checking if we can safely change this behaviour. For your first issue, I think the solution you came to is the trick :)

**Comment by JCLengeling** [comment]
Thanks for the reply. I succesfully replaced the ugly foreach loop with the suggested code :D

**Comment by themsaid** [comment]
👍 

This was merged today as well: https://github.com/laravel/framework/pull/16301#event-851900629

This will allow for unserializing soft deleted models, which will solve your 3rd issue.

As for the first issue I highly recommend that you use Homestead on Windows, it solves a lot of issues.
