### ISSUE TITLE
Bindings order during model update with join

### ISSUE THREAD

**Issue by tomdegoede** [laravel/framework#16131]
- Laravel Version: 5.1.45
- PHP Version: 5.6.3
- Database Driver & Version: MySql

### Description:
When updating a model with a join statement the update bindings are listed before the join bindings even though the join statement is before the set statement. See: \Illuminate\Database\Query\Builder::update

### Steps To Reproduce:
See above.

**Comment by sisve** [comment]
Can you show us the problem, describe _why_ it is a problem and a piece of PHP code we can use to reproduce the problem?

**Comment by tomdegoede** [comment]
`Model::join(...)->where(something that joined)->update([...])`

We worked around the issue by overwriting  \Illuminate\Database\Query\Builder::update with:
```
        $bindings = $this->bindings;
        $join = $bindings['join'];
        $bindings['join'] = [];

        $bindings = array_values(array_merge($join, $values, Arr::flatten($bindings)));

        $sql = $this->grammar->compileUpdate($this, $values);

        return $this->connection->update($sql, $this->cleanBindings($bindings));
```
