### ISSUE TITLE
Outdated illuminate/validation

### ISSUE THREAD

**Issue by Milewski** [laravel/framework#16132]
[**Illuminate/Validation** on the main branch is on the version **5.3.21**](https://github.com/laravel/framework/tree/v5.3.21/src/Illuminate/Validation)

however [illuminate/validation](https://github.com/illuminate/validation/tree/v5.3.16) still on **5.3.16**

[ **5.3.17**](https://github.com/laravel/framework/tree/v5.3.17/src/Illuminate/Validation) has been released nearly a month now.... and packagist still didn't get this version.. 

and the [documentation](https://laravel.com/docs/5.3/validation#rule-unique) already includes the new Rule class(that was introduced on the version [5.3.18](https://github.com/laravel/framework/tree/v5.3.18/src/Illuminate/Validation), however it is not available yet....

> Probably not only this package.. but all illuminate packages may be the same.. as i see all stuck at the version 5.3.16 in my composer.json file...  and at [https://packagist.org/packages/Illuminate](https://packagist.org/packages/Illuminate)

![image](https://cloud.githubusercontent.com/assets/2874967/19773547/860f8f0a-9c9c-11e6-833f-f06d08a132ba.png)

**Comment by GrahamCampbell** [comment]
Thanks, we know. :)

The packages all lag behind. They'll be updated all in good time.

**Comment by Milewski** [comment]
how about the documentation is talking about something that is currently not available then? 

[https://laravel.com/docs/5.3/validation#rule-unique](https://laravel.com/docs/5.3/validation#rule-unique)

```php
Validator::make($data, [
    'email' => [
        'required',
        Rule::unique('users')->ignore($user->id),
    ],
]);
```
