### ISSUE TITLE
Issues and considerations about dealing with deadlocks and retries

### ISSUE THREAD

**Issue by halaei** [laravel/framework#16140]
When a deadlock happens inside a transaction, the transaction is rolled back by DBMS and normally it is OK to retry. How to retry and what other kinds of errors means to retry, may depends on DBMS and its configurations. Here is what I understood from reading some refs - which may be not 100% correct. But it seems to me that `Connection::transaction()` and `Connection::causedByDeadlock()` has room for improvements.
- After deadlock detection, it depends on the DBMS whether or not we should call rollback for the first transaction level. As far as I know, we have to call rollback for MySQL if we don't want to retry, but should not do that for SQL Server:

``` php
public function transaction(Closure $callback, $attempts = 1)
{
   ...
    try {
        ...
    } catch (Exception $e) {
        //If $e is caused by deadlock, to call the next line depends on DBMS:
        $this->rollBack();
}
```
- To call rollback outside any transaction is OK for MySQL, PostgreSQL, and Oracle but MS SQL Server and sqlite throw exceptions.
- MySQL may or may not rollback the entire transaction on lock wait timeout, which is different from deadlock. The default configurations says not to rollback the entire transaction on lock wait timeout.
- At least for MySQL driver, the following code is enough to find if the exception caused by deadlock - no need to look at `$e->getMessage()`:

``` php
function causedByDeadlock(Exception $e) {
    return $e->getCode() === '40001';
}
```

It is a little hard to consider all the DBMS with all the possible configurations and all the supported versions for dealing with issues like that. Maybe having integration tests for MySQL, Postgres and SQLServer as well as SQLite makes things more clear.
#### MySQL Refs
- https://dev.mysql.com/doc/refman/5.7/en/innodb-error-handling.html
- https://dev.mysql.com/doc/refman/5.5/en/error-messages-server.html

**Comment by GrahamCampbell** [comment]
This was changed again in L5.3.22 (not released yet).
