### ISSUE TITLE
Collection mapWithKeys cannot handle number or even string casted numeric keys

### ISSUE THREAD

**Issue by theHarvester** [laravel/framework#16142]
- Laravel Version: 5.3
- PHP Version: 7
- Database Driver & Version: Not important

### Description:
Collection mapWithKeys cannot handle number or even string casted numeric keys.

### Steps To Reproduce:
This code is straight out of the unit test except I've used idx instead of a string based key.

```
$data = new Collection([
    ['name' => 'Blastoise', 'type' => 'Water', 'idx' => 9],
    ['name' => 'Charmander', 'type' => 'Fire', 'idx' => 4],
    ['name' => 'Dragonair', 'type' => 'Dragon', 'idx' => 148],
]);
$data = $data->mapWithKeys(function ($pokemon) {
    return [(string)$pokemon['idx'] => $pokemon['type']];
});
```

**Comment by themsaid** [comment]
see https://github.com/laravel/framework/issues/15409
