### ISSUE TITLE
problem with phpunit  with model relation on diferrent database

### ISSUE THREAD

**Issue by icfr** [laravel/framework#16143]
- Laravel Version: 5.1.45
- PHP Version:7.0.8, 5.6.27
- Database Driver & Version: mysql v5.7.16

### Description:
i have two model like [this](https://gist.github.com/icfr/967e9bd51282fe27dbbcb421eddb5b41)

the function that store relation is
```php
$secondModel = SecondModel::where(...)->first();
$firstModel = FirstModel::create([...]);
$secondModel->firstModels()->attach($firstModel);
```
when i try to test this function it block 

output with phpdbg when canceling the test:
```
[Current opline: in internal function execute]
>00390:             return $me->getPdo()->prepare($query)->execute($bindings);
 00391:         });
 00392:     }

```

**Comment by themsaid** [comment]
Please provide steps to reproduce, I don't actually understand what the issue is.

**Comment by themsaid** [comment]
ping @icfr

**Comment by icfr** [comment]
i've tried to create a project to show the problem  but it work fine on an empty project ...

so i have to search what goes wrong
