### ISSUE TITLE
Can't use $variable_name->links() while using pagination

### ISSUE THREAD

**Issue by zeeshanu** [laravel/framework#16153]
- Laravel Version: 5.3
- PHP Version: 7.0.9
- Database Driver & Version: mysql 5.0.12

### Description:
I am getting all the comments of a user and paginate them. But problem is that when I try to get links() on view of pagination it throws exception:
```
Call to undefined method Illuminate\Database\Query\Builder::links()
```

### Here is my Code;
```
$query = $this;
$query = $query->where('id', '=', $userId)
                       ->with([
                            'comments' => function($query) {
                                $query->paginate(2);
                            }
                        ])
                        ->get();
```

**Comment by themsaid** [comment]
Replace `->get();` with `->paginate()`

**Comment by zeeshanu** [comment]
I just want to paginate comment's not the whole query result.

**Comment by themsaid** [comment]
and how do you call the links method?

**Comment by zeeshanu** [comment]
$user->comments->links()

**Comment by themsaid** [comment]
this won't work, actually it doesn't make much sense to have multiple paginated entities, what's the use case?

**Comment by zeeshanu** [comment]
I am currently working on a project in which  a user can have multiple organizations and tasks. On a task I want to paginate the comments for some reasons.

**Comment by zeeshanu** [comment]
In my first comment i paginated wikis that is generating following result. 
![image](https://cloud.githubusercontent.com/assets/16267321/19808322/c993dd70-9d3d-11e6-9491-c6967cf6de03.png)
Why there is not total, per_page, current_page, last_page keys in wikis array.

**Comment by themsaid** [comment]
Because pagination won't work with eager loading, that's not supported.

**Comment by zeeshanu** [comment]
I think it would be great if Laravel have this functionality. :expressionless:
