### ISSUE TITLE
Dots in cookie name being replaced to underscores

### ISSUE THREAD

**Issue by pun-ky** [laravel/framework#16167]
- Laravel Version: 5.3.1
- PHP Version: 7.0.8
- Database Driver & Version:  not related
### Description:

Dots in cookie names are replaced by underscores, so using same name in creating and getting cookie is not possible in that case.
### Steps To Reproduce:

Assume following code:

`\Cookie::queue('adm::system.update', 'test', 10)` 

Then on next request:

`\Cookie::get('ers::system.update'` == null, but
`\Cookie::get('ers::system_update'` == 'test'

**Comment by PleaseDontKillMe** [comment]
I could make a fix for that

**Comment by KryDos** [comment]
I don't think it is Laravel issue...
Laravel in this case use Symfony `Cookie` component. BUT it is also not the Symfony issue. 

[As it mention on php.net](http://php.net/variables.external#language.variables.external.dot-in-names)  `PHP will automatically replace any dots in incoming variable names with underscores.`

I think it is also related to how PHP itself is working with cookies.

**Comment by michaeldyrynda** [comment]
It's a limitation of the cookie spec ([RFC6265](https://tools.ietf.org/html/rfc6265#section-4)) and HTTP/1.1 ([RFC2616](https://tools.ietf.org/html/rfc2616#section-2.2)). This applies to most header fields, and doesn't appear to have changed with HTTP/2.

Essentially, you can't use control characters in the `cookie-name` component, of which the `.` character is one.

**Comment by GrahamCampbell** [comment]
Looks like an incorrect usage then. Perhaps we should add some validation inside to throw an exception on invalid usage?

---

Thanks @michaeldyrynda. :)

**Comment by michaeldyrynda** [comment]
Either that, or maybe just add a note to docs to highlight valid characters.

**Comment by GrahamCampbell** [comment]
Note to self: do this. :P

**Comment by pun-ky** [comment]
Assuming that Laravel is developer friendly, exception will be nice if name is incorrect. ☺ shorter way while debugging... It is not clear enough. I was thinking that Laravel is converting any name to be valid underneath.

**Comment by GrahamCampbell** [comment]
Maybe this is something symfony is doing under the hood with bad input? I've not checked. Perhapse their implementation is safest, and this is one for the docs.

**Comment by michaeldyrynda** [comment]
As @KryDos pointed out above, it's PHP handling the conversion, so it's silently happening at the language level. I wouldn't change the handling as it's going to break any code using it as-is currently, which you'd have to add to the changelog. If you're documenting the behaviour, i'd just document the conversion, pointing to the PHP docs if necessary.

**Comment by powelski** [comment]
PHP's `$_COOKIE` array contains underscores as well, but in Chrome's dev tools you can see that the dots have been set in the name.

**Comment by CurosMJ** [comment]
@michaeldyrynda The RFC does not prevent using `.` in cookie names, what it does prevent is any control characters (escape, backspace, etc) and these characters : `(`, `)`, `<`, `>`, `@`, `,`, `;`, `:`, `\`, `<`, `>`, `/`, `[`, `]`, `?`, `=`, `{`, `}`, space and horizontal tab. 

The conversion of dots (and spaces) to underscores is for sure done by PHP, similar to how it does that with $_GET and $_POST. Adding this as a note to docs.
