### ISSUE TITLE
https after cache:config and routes

### ISSUE THREAD

**Issue by galamz** [laravel/framework#16160]
- Laravel Version: 5.4.21
- PHP Version: 5.6

hey guys. 
i need some help 
i have new trouble with php artisan after using 
route:cache and config:cache 
all urls and routes on website changed to http

i use url('url') or route('name') or href or src

**Comment by GrahamCampbell** [comment]
That won't be related to those commands I think. Please ask on the forums, and I'm sure someone will help you there.

**Comment by sisve** [comment]
Does everything work again if you execute `php artisan route:clear` and `php artisan config:clear` to remove the caches?

**Comment by galamz** [comment]
yes @sisve 
when i execute `php artisan route:clear` and `php artisan config:clear `

https back
