### ISSUE TITLE
NotFoundHttpException :80 in URLs

### ISSUE THREAD

**Issue by marcoflorian** [laravel/framework#16162]
- Laravel Version: Laravel Framework version 5.2.45
- PHP Version: PHP 7.0.11 (cli) (built: Sep 30 2016 21:22:34) ( NTS )
- Database Driver & Version: none

### Description:

Recently, I am continuously receiving NotFoundHttpException errors in my Laravel error log for URLs with this pattern `http://example.com/:80/a/b/c` where `/a/b/c` is a valid query for a single page.

Since I use the URL facade for every link in my site, I think that maybe I'm doing something wrong somewhere that is affecting a group of my visitors. Does anyone have any idea what might be happening?

### Steps To Reproduce:

I haven't found a way on how to reproduce this error.

**Comment by GrahamCampbell** [comment]
This is an invalid URL. You must put the port and the colon before that slash.

**Comment by GrahamCampbell** [comment]
I assume some kind of bot is messing up crawling your site perhapse. Feel free to ask on the forums.
