### ISSUE TITLE
[5.3] phpunit Strange behavior

### ISSUE THREAD

**Issue by maki10** [laravel/framework#16189]
- Laravel Version: 5.3.21
- PHP Version: 7 (Homestead)
- Database Driver & Version: Mysql (Sqlite for test)

### Description:

Currently, I have 115 tests written for my app, and in some point of testing when I had 112 and 113 number of tests, my test start to fail.

From some reason, fails were on next file(`Controller`) that `phpunit` start to crawl, and `assertResponseStatus(401)` was `400`. 

I ignored that issue and write a new test that fails from same errors and in some point of testing my test won't fail anymore for that error. Everything seems to be normal now.

Because is API I try to reproduce the error with Postman, and everything is working like expected.

### Steps To Reproduce:

This test is for the controller I have 30 similar requests and all tests are green, the only method is changed i.e `get` or `post`.

```php

    public function test_add_employed_for_business()
    {
        $apiKey = factory(ApiKey::class)->create();
    	$business = factory(Business::class)->create();

    	$response = $this->post('/api/business/edit/'.$business->id.'/add-employed',[
			  'email' => 'johndoe@example.com',
			  'name' => 'John Doe',
			  'password' => 'pass123',
			  'user_role_id' => '1'
    		], ['Authorization' => 'Bearer '.$apiKey->api_token, 'secret' => $business->business_token])
	    	->assertResponseStatus(200);
    }
```
```php
// DEBAG
dd($response); //Return status code 200
```

**Comment by maki10** [comment]
I notice that, if is on end of my class method that check is `assertResponseStatus(400)` i.e method that tests bad request, few next tests will fail. Otherwise, all tests are good.

**Comment by sisve** [comment]
Execute phpunit with --debug to see which tests execute just before the errors are occurring.

**Comment by maki10** [comment]
@sisve I do that, and test above is executing. And 2 next test fails, if I continue to write test error disappeared and everything is normal

**Comment by themsaid** [comment]
Please continue on the forums, we keep this repo for laravel bug reporting only.
