### ISSUE TITLE
Custom Validation For Required With & Fields as Parameters

### ISSUE THREAD

**Issue by prateekkathal** [laravel/framework#16183]
- Laravel Version: 5.3.16
- PHP Version: 5.6.26
- Database Driver & Version: 5.7.15
### Issue 1:

So, I have been trying to make a custom validation rule in cases like `require_with_not_empty`. Laravel's `require_with` method checks only if the field inside is present or not, but I also need to check if the field is present and not empty.

In cases like - 

``` php
$rules = [
  'post.*.description' => 'required_with_not_empty:post.*.name,post.*.date|min:1|max:2000',
];
```

I am adding this to my ValidationServiceProvider

``` php
Validator::extend('required_with_not_empty', function($attribute, $value, $parameters, $validator) {
  dd($attribute, $parameters);
});
```

Output in this case is

``` php
"post.0.description"

array => [
  0 => "post.*.name"
]
```

The **main question** here is... how is it possible to convert `post.*.name` to `post.0.name` ? 

We can get the value of the attribute by doing 

``` php
array_get($validator->getData(), $attribute, null)
```

but getting the value of **parameter** here doesn't seem possible. 
### Issue 2:

If we go into `resources -> lang -> validation.php` , We get an option to add custom messages for custom attributes.

So, here my custom attribute is `required_with_not_empty`. And my current array looks like 

``` php
'custom' => [
  'education.*.description' => [
    'required_with_not_empty' => 'The :attribute field must be present and not empty with :values.',
  ],
],
```

But what I get as an output is

``` php
The post descriptions must be present and not empty with :values
```

Here... _description_ for some reason is given as **plural** and :values is **not getting translated** to the **parameters** provided in the validation rule.

**Comment by themsaid** [comment]
For your first issue, where's how we do it in the Validator: https://github.com/laravel/framework/blob/5a11fb13d7023e05911559c99902e68f3cb95ed9/src/Illuminate/Validation/Validator.php#L489

For issue two: you need a replacer https://github.com/laravel/framework/blob/5a11fb13d7023e05911559c99902e68f3cb95ed9/src/Illuminate/Validation/Validator.php#L2469

Please continue on the forums as we keep this repo for bug reporting only :)

**Comment by prateekkathal** [comment]
Hi @themsaid , thanks for the reply,

I had already got into laravel's code to understand what function you might be calling, but then again..... 

For the first issue,  `getExplicitKeys` and `replaceAsterisksInParameters` are both *protected* methods... they can not be called like `$validator->getExplicitKeys($attribute)` ... It will result in a **BadMethodCallException**

And for the second issue as well - `getAttributeList` is *protected* .... 

Are you asking me to copy the exact same functions to my `ValidationServiceProvider` to make this work? The code will get really *messy* that way.... Can't you make those function public? Or you could also make another function which would call the rest of those functions... But that is completely your decision.... 😄

**Comment by themsaid** [comment]
I guess they can be set to public yes, but this can be a breaking change so it'll be done in 5.4

**Comment by prateekkathal** [comment]
In that case, how should I go about coding it in 5.3? 

Also, I have a suggestion for validation and would like to get your views on it. I'll be creating a pull request and hope u'll consider it in 5.3 or the next release... ☺ 

Waiting for your answer, so I can make changes to my current code... :)

**Comment by themsaid** [comment]
Maybe you'll have to extend the validator and add your new rule as a method.

**Comment by prateekkathal** [comment]
@themsaid Well, as given in the code posted in the question above, I am using the `Validator::extend` method to run my own validation, but if possible, please add this rule as well in 5.4... Since, the presence of an attribute in the input can not always be considered valid. 😄 

Thanks for the support otherwise... I am going to create a pull request for the new validation methods which I believe will really turn out helpful in some cases. 👍 Will tag you on it since you are the validation champ here... 😛

**Comment by Ken-vdE** [comment]
I experienced the same issue and using getExplicitKeys() and replaceAsterisksInParameters() allowed me to fix it. I had to manually set both methods to public.

**Comment by prateekkathal** [comment]
@Ken-vdE You shouldn't change any code in vendor folder. 

Whatever changes you do in that folder will be overwritten whenever the package is updated.
