### ISSUE TITLE
XSRF-TOKEN cookie not securely set as httpOnly

### ISSUE THREAD

**Issue by ametad** [laravel/framework#16191]
- Laravel Version: 5.3.19
- PHP Version: 7.0.8
- Database Driver & Version: MySQL 

### Description:

The XSRF-TOKEN cookie explicitly is set as httpOnly=false, but should be set to true imho.

### Steps To Reproduce:

The XSRF-TOKEN cookie explicitly is set as httpOnly=false. See https://github.com/laravel/framework/blob/5.3/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php#L139

The very last parameter is hardcoded set to false and is used for the httpOnly flag.

I think it is more secure to flag this cookie as httpOnly. The XSRF-TOKEN is already accessible in JS through the Laravel object: Laravel.csrfToken, if set in the header like so:

```
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
```

Fresh installation of Laravel 5.3 with Passport scaffolding shows cookies as follows, when you log into the application. Please pay attention to the HTTP attribute of the XSRF-TOKEN cookie.

![image](https://cloud.githubusercontent.com/assets/1582541/19857521/3d78b052-9f7e-11e6-8b4c-1cd11b321190.png)

Thank you for Laravel, it's great!

**Comment by themsaid** [comment]
Feel free to open a PR :)

**Comment by ametad** [comment]
Here you are :)

**Comment by umer-448** [comment]
XSRF token and Laravel session can decode for base64 algorithm . 
after decode :
{"iv":"h3+O3H421A5OSLU8DF43tA==","value":"c9YNMmwBIdkkKin2Z4C7FqZJu13Mk1xPz0NiOSfhiPk=","mac":"7a03cb1f0b3b246bc9cdbc573c070dc7e7fad15f1da27014e899a89fc6b0c0ce"}


i am trying to prevent this decoding .. could not show iv , value and mac... anyone can help?
