### ISSUE TITLE
Documentation for Validation out of date?

### ISSUE THREAD

**Issue by baseten** [laravel/framework#16194]
- Laravel Version: 5.2.41
- PHP Version: 7.0.8-2+deb.sury.org~xenial+1

### Description:
According to the [docs](https://laravel.com/docs/5.3/validation#validation-quickstart) when using the `validate` helper method with an AJAX request, if validation fails, a JSON response should be returned detailing all of the errors. However it seems like a `ValidationException` is thrown instead. According to [this post](http://stackoverflow.com/questions/34610845/laravel-validator-throws-an-exception-instead-of-redirecting-back), this is a deliberate design change. If that is true, then the documentation is out of date. If not, what is going wrong?

### Steps To Reproduce:
- Use the `validate` helper function to test user input to a controller action invoked via AJAX
- Post to this route with invalid data

**Comment by sisve** [comment]
A ValidationException is thrown, but your exception handler converts it to a json result. https://github.com/laravel/framework/blob/5.3/src/Illuminate/Foundation/Exceptions/Handler.php#L221-L223

**Comment by baseten** [comment]
Ah, I'm using Dingo to create the API routes. It seems like it replaces the Laravel Exception Handler with it's own, which is why I'm not seeing any errors
