### ISSUE TITLE
Why are fillables for Models non-static?

### ISSUE THREAD

**Issue by StefanPrintezis** [laravel/framework#16190]
- Laravel Version: 5.2.39
- PHP Version: 5.6.20

### Description:
What led me to this question:

I was creating a function that checks if the model exists based on attributes, but I wanted to check if the given attributes exist in the model. In this case I only want my function to check attributes that are fillables, but i'd have to instantiate the model to access the fillables array.
```
public static function exists($attributes) {
    if ($attributes) {
      return self::wheres($attributes)->count('id');
    }
 }
```

I know the find function exists, but i do not require the data itself, only the `count('%') as aggregate`

This question could also apply for these properties: $attributes, $guarded ... basically anything that shouldn't be changed in an instance of the model.

**Comment by themsaid** [comment]
Please use the forums to post questions, we try to keep this repo for bug reporting only. Thank you :)
