### ISSUE TITLE
Considering PHP 7's new features

### ISSUE THREAD

**Issue by khooz** [laravel/framework#16192]
- Laravel Version: 5.3.#
- PHP Version: 7.0.12
- Database Driver & Version: (php_oci8 12.1)

### Description:
This is more of a feature suggestion. Since the PHP 7 (and maybe a branch for 7.1) is out and stable, It will be good if new practices emerge. like the use of strict type hinting (Both type injection as is, and scalar type hinting), static initialization, fixed-size arrays, etc. how little may be, They may lead to an increase in performance.
Here's the [link to official feature list](http://php.net/manual/en/migration70.new-features.php) for PHP 7.0.x

As always, Thanks for the awesomeness.

**Comment by themsaid** [comment]
Thank you, but laravel still supports PHP 5.6 so we can't use PHP7 only features yet :)
