### ISSUE TITLE
[5.3] Sessions are not being set when authentication attempt is made

### ISSUE THREAD

**Issue by Libbux** [laravel/framework#16202]
- Laravel Version: 5.3.21
- PHP Version: 7.0.6-13 (running on homestead)
- Database Driver & Version: mysql
- Session Driver: file (`storage/framework/sessions` is writable by webserver user)

### Description:
When an authentication attempt is made on a user instance (via ``Auth::login()`` or ``Auth::attempt()``) and session data is set in one route, the login is not persisted when accessing another route and the session data is not available. Note that setting session data in one route and retrieving it in another without attempting authentication works as expected.

### Steps To Reproduce:
Create a fresh Laravel project. Run database migrations and add a user (with `id=1`) to the default ``users`` table. Implement a test login route, as per below, and a test authentication check route, as per below, in the `web.php` routes file. Note that even after hitting the first route, the second route returns false for authentication and does not display the previously set session data.

Example login route:
```php
Route::get('/test/signin', function(Request $request) {

    $user = \App\User::find(1);
    Auth::guard('web')->login($user);

    // Set a test value in the session
    session(['test_key' => 'test_value');

    // Print all data in the session, including test_key => test_value
    print_r($request->session()->all());

    // Returns true
    return var_dump(Auth::check());
});
```

Example auth check route:
```php
Route::get('/test/checkauth', function(Illuminate\Http\Request $request) {

    // Print all data in the session (does not show test_key => test_value)
    print_r($request->session()->all());

    // Try to get the current authenticated user instance (prints null)
    echo var_dump(Auth::guard('web')->user());

    // Try to get the authenticated user instance in a different way (also prints null)
    echo var_dump($request->user());

    // Returns false
    return var_dump(Auth::guard('web')->check());
});
```

**Comment by srmklive** [comment]
@Libbux The code you have written has a few mistakes:

* In your `test/signup` route callback, you are setting the session as:

`session(['test_key' => 'test_value')` 

whereas you should be doing it like:

`$request->session(['test' => 'test_key']);`

That's why you are not getting the session value in your other route.

* `$request->user` will always return `null` in my opinion if you don't provide a guard parameter. Try to do it like this:

`$request->user('web')


Lastly, i would suggest that you use `auth` global helper function instead of the `Auth` facade. Its much easier to use like:

`auth('web')->check()` or `auth('web')->user()`

**Comment by sisve** [comment]
Are you calling these two routes concurrently? Concurrent session activity is not supported. https://github.com/laravel/framework/issues/14385

**Comment by themsaid** [comment]
I can't replicate your issue on a fresh installation, can anyone?

**Comment by themsaid** [comment]
@Libbux are you able to replicate this on a fresh installation?

**Comment by Libbux** [comment]
@themsaid This bug turned out not to be with sessions, but with some kind of string to integer conversion happening (on a 20+ character numeric Google ID string) when searching the user model. I'm going to look into that specific behaviour further and then file as a new bug if it turns out to be one. Many thanks for everyone's help anyway.
