### ISSUE TITLE
Illuminate\Http\Request\Request $request->only() makes up missing attributes

### ISSUE THREAD

**Issue by DSpeichert** [laravel/framework#16203]
- Laravel Version: v5.3.21
- PHP Version: 7.0.12
- Database Driver & Version: 10.1.18-MariaDB

### Description:
Assume the user passes the following request input:
```
[
     "name" => "Desk",
     "price" => 100,
]
```

When you execute: 
```php
$request->only(['name', 'price', 'count']);
```
you would get:
```
[
     "name" => "Desk",
     "price"  => 100,
     "count" => NULL,
]
```

However, if you do the following instead:
```php
array_only($request->all(), ['name', 'price', 'count'])
```

You now get:
```
[
     "name" => "Desk",
     "price" => 100,
]
```

For me, the second behavior makes much more sense when using it together with `$model->fill(...)`. Validation rules can tolerate not specifying attributes you don't want to edit (actually that works very well with `sometimes` filter) but it totally does not work when the attributes that are NOT in the original request now appear as `NULL`.

### Steps To Reproduce:
Above.

**Comment by themsaid** [comment]
Use intersect()

**Comment by DSpeichert** [comment]
@themsaid Thanks, that's the first time I hear about that function. It's nowhere in the docs and I don't usually look for things in the API docs.
