### ISSUE TITLE
Min validator not working properly

### ISSUE THREAD

**Issue by andjelicsasa** [laravel/framework#16209]
- Laravel Version: 5.3.21
- PHP Version: 7.0
- Database Driver & Version: MySQL

### Description:
When I use "alpha|min:2" validator doesn't fail with an empty string, but fails if string has length of 1 character.

### Steps To Reproduce:
In the following example:
- first_name='' passes
- first_name='d' fails

```php
$validator = \Validator::make(
        [
                'first_name' => \Request::get('first_name')
        ],
        [
                'first_name' => 'alpha|min:2'
        ]
);
if ($validator->fails()) {
        // some handling
}
```

**Comment by GrahamCampbell** [comment]
What if you mark the field as "required"?

**Comment by andjelicsasa** [comment]
I need this for the field update, so the field is not required, it just needs to be limited to min 2 characters if the field is to be updated.
Required causes the validator to fail, but in this case it is not an option for me, I just need the min validator.

**Comment by themsaid** [comment]
The thing is that we can't fail on an empty string since form submission will result an empty string as value if you leave the field empty, so if the field is empty we skip validation unless there's a rule that states that the field is required.

For this you need to do something like:

```
$validator->sometimes('first_name', 'required|alpha|min:2', function ($value) {
        return $value->first_name !== null;
    });
```

This will validate the field only if there's a value, if the field isn't there the required rule won't fail which is what you want, but if the field is there with an empty string as value the required rule will fail.

**Comment by andjelicsasa** [comment]
Thanks @themsaid I will try to implement this solution. Fields are not hard-coded in the application I am working with, so hopefully there is a safe way to implement this patch.

It's a shame this is developed for HTML forms. Seems now that any complex applications as API-s need to patch like this..
Perhaps having some kind of a base validation, and then extending it for form validation specifically would leave more room for extendibility to other applications.
For example, I have tried to make a custom validation rule hoping I would go under the hood to have this done straight, and figured out the validation rule is never checked if the field is an empty value of a type.
Let's say that instead of 'required' rule having multiple responsibilities, perhaps an additional validation rule like 'notnull' would have solved the problem for HTML forms and cast input empty values of different types just like 'boolean' rule does, rather than crippling the complete validation system.

**Comment by themsaid** [comment]
I think we need a separation between data incoming from forms and API payloads yes, but I can't decide the degree of separation needed, like what exactly needs to be changed, only this empty value thing?

**Comment by andjelicsasa** [comment]
Lets say for example, remove the 'required' rule, add a rule 'not_empty' and let any rule be validated regardless if the sent attribute is empty. For HTML forms you can use a combination of 'present|not_empty', and API-s would not use 'the not_empty' rule.

Also, using Request facade, get() method returns null if a parameter is null or if it is not sent. This uses the isset() logic rather than array_key_exists(), which is convenient for HTML forms, but is dangerous for API-s.

I understand that perhaps 90% of people using Laravel use validation as well and need to refactor, so I guess this is kind of a big issue to alter right now.

**Comment by themsaid** [comment]
yeah, huge 
Anyway will look into that sometime soon, thank you :)

**Comment by andjelicsasa** [comment]
Thanks for your time, cheers :)
