### ISSUE TITLE
Filter on arrays does not work as documented

### ISSUE THREAD

**Issue by vissermc** [laravel/framework#16208]
- Laravel Version: 5.3-dev
- PHP Version: 7.0
- Database Driver & Version:

### Description:

Taken the literal example for the documentation:
$collection = collect([1, 2, 3, 4]);

$filtered = $collection->filter(function ($value, $key) {
    return $value > 2;
});

$filtered->all();

This returns [2=>3, 3=>4] instead of [3, 4] as documented
### Steps To Reproduce:
See above

**Comment by themsaid** [comment]
This is how `array_filter` of PHP works, you cna use `$filtered->values()` to re-index.

**Comment by vissermc** [comment]
may I ask why the documentation is not updated?
