### ISSUE TITLE
Suggestion: artisan routes:list should not include prefix App\Http\Controllers

### ISSUE THREAD

**Issue by eberkund** [laravel/framework#16219]
When you use the console command `php artisan route:list` you get a long path for the method name in the controller a particular route is mapped to. For larger projects a few subdirectories this can get long, sometimes to long to fit the width of a full screen terminal window.

I am proposing that the Controller class path be shortened by removing the `App\Http\Controllers\` portion of the file path. Since all Controllers will likely be in this directory it is redundant and takes up valuable screen real estate.

**Comment by jhoff** [comment]
`route:list` could use some formatting love, but Laravel doesn't care where your controllers live. App\Http\Controllers is only a suggestion.

**Comment by GrahamCampbell** [comment]
Routes can be based from there, and indeed from anywhere else as well, so we need the full name.

**Comment by eberkund** [comment]
What if instead there were some additional command line parameters to hide certain columns or display only the classname and not the full namespace?
