### ISSUE TITLE
published notification templates aren't used if the notification is queued with beanstalkd

### ISSUE THREAD

**Issue by coedycode** [laravel/framework#16210]
- Laravel Version: 5.3.21
- PHP Version: 7.0.8
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.7.16, for Linux (x86_64)

### Description:

After using: php artisan vendor:publish --tag=laravel-notifications
and making sure all configs and caches are flushed.
The published templates aren't used if the notification is queued and processed by beanstalkd.
Also it doesn't read the app name from config/app.php

### Steps To Reproduce:
1, have beanstalkd  setup for queues.
2. create a simple notification for emailing
3. publish the notification templates
4. Modify the published resources/views/vendor/notifications/email.blade.php template.
5. Send the notification from a controller action.
6. Check the email and it wont be using the published modified template.
7. Open the notification  class and comment out: //implements ShouldQueue and //use Queueable;
8. Send the notification from a controller action.
9. Check the email and it will be using the published modified template.

**Comment by themsaid** [comment]
https://laravel.com/docs/5.3/queues

> Remember, queue workers are long-lived processes and store the booted application state in memory. As a result, they will not notice changes in your code base after they have been started. So, during your deployment process, be sure to restart your queue workers.

**Comment by coedycode** [comment]
Thanks for the comment, I was hoping that might be the answer, but I've tried a:

php artisan queue:restart

and it's made no difference, the published templates still aren't used when the notification is queued.

**Comment by themsaid** [comment]
Well the only explanation I have in mind is that the files aren't published on the instance the worker is running, so you might need to go from there.

**Comment by themsaid** [comment]
glad it finally works :)

**Comment by coedycode** [comment]
In case it helps anyone else finding this:

`sudo supervisorctl update`

That brings in changes to queueable event listeners and templates
