### ISSUE TITLE
[5.3] Updating JSON returns data as "meta->area" instead of meta : {area : ...}

### ISSUE THREAD

**Issue by lukepolo** [laravel/framework#16213]
- Laravel Version: 5.3.21
- PHP Version: 7.0.12
- Database Driver & Version: MySQL / 5.7.13-0ubuntu0.16.04.2

### Description:

When updating JSON 

```
    public function update(Request $request, $id)
    {
        $program = Program::findOrFail($id)->fill([
            'meta->area' => 'new value'
        ]);

        $program->save();

        return response()->json($program);
    }
```

Returns 
```
    {
        ....
        meta : {area : 'old value'},
        meta->area : "new area"
        ....
    }
```

It is correctly updating just not replacing the value correctly upon return. 

### Steps To Reproduce:

```
    public function update(Request $request, $id)
    {
        $program = Program::findOrFail($id)->fill([
            'meta->area' => 'new value'
        ]);

        $program->save();

        return response()->json($program);
    }
```

Look at the json value returning .

**Comment by jhoff** [comment]
I'm pretty sure that `meta->area` is the wrong syntax. Are you meaning to use dot notation? `meta.area` ?

**Comment by lukepolo** [comment]
https://laravel.com/docs/5.3/queries#updating-json-columns

Docs say otherwise

**Comment by themsaid** [comment]
@lukepolo working on a fix.

**Comment by jhoff** [comment]
Huh... TIL. Apologies.
