### ISSUE TITLE
Laravel 5.3 Nested Collection methods cause CLI to crash?? Error Handler might be needed.

### ISSUE THREAD

**Issue by dreferreira** [laravel/framework#16220]
- Laravel Version: 5.3.15
- PHP Version: 7.0.3
- Database Driver & Version: MySql

### Description:
Hello, I may have just discovered an issue that needs an Exception Handler developed for it. I've been using laravel collections to assist in data format, however, in one situation I'm using a prepend method with daisy-chained put methods. This, for some reason, is causing the CLI to crash as shown below.

**The Code:**

![trapcode](https://cloud.githubusercontent.com/assets/7734800/19914557/f2e7fd7c-a081-11e6-9df2-b9b3d7dedd27.PNG)

I'm working on a different way to achieve my desired output but I'm still curious about why this is happening. Steps to reproduce are shown below. 
Thank you in advance. 

### Steps To Reproduce:

1. Create a "GET" request to a route on your server like below:
(Example)
      `Route::get('/showlights','Lights@getPower');`

**Dummy data to use in collection:**
```
Collection {#297
  #items: array:9 [
    "light_one" => 0
    "light_two" => 0
    "light_three" => 0
    "light_five" => 0
    "light_six" => 0
    "light_seven" => 0
    "light_eight" => 0
    "light_nine" => 0
    "light_ten" => 0
  ]
}
```

2. Assign the above array to a '$lights' variable

3. Pass the above dummy data array into the code below

```
...
...
Class Lights  extends Controller {
...
...
      public function getPower(Request $request) {
              
               $model = null;
               $model = collect($model);  
               $storage = null;
               $storage = collect($storage);
               $x=0;

               foreach ($lights as $key => $value) {
            
                           $model = $model->prepend($model->put('name',$key)
                                                       ->put('reference',$key)
                                                       ->put('enabled',$value));
                           $storage = $storage->push($model->get($x)->toJson());   

                           $x++;
                }
      }
}
```

I understand there is definitely a syntactically better way to perform the above code however, it's more for the sake of other's and the projects they're working on.

4. Send Get request to your '/showlights' route

The result I get is shown below:

![clistopped](https://cloud.githubusercontent.com/assets/7734800/19915089/3b0a5eac-a086-11e6-85af-e42179ffe47a.PNG)

The primary focus of this is the use of this kind of syntax and how it causes the CLI to crash:
```
$var->prepend($var->put()
                 ->put()
                 ->put());
```

Shouldn't there be a check or handler in place to address this?

**Comment by jhoff** [comment]
I'm not really sure what you're trying to do here, but Look at $model after the prepend. It looks like this:

<img width="246" alt="screen shot 2016-11-02 at 12 35 59 am" src="https://cloud.githubusercontent.com/assets/627060/19917810/74a34c88-a094-11e6-89f5-1685282cc5d0.png">

Why you're trying to prepend $model onto itself... That doesn't make sense to me. You're effectively doing this:

```
$model->prepend($model);
```

The failure actually happens when you call the `toJson` method.

Apache is throwing a segmentation fault:

```
[Wed Nov 02 00:39:05.708641 2016] [core:notice] [pid 50142] AH00052: child pid 99063 exit signal Segmentation fault (11)
```

TBH I'm not really comprehending what you're attempting to do based on the given example, so I wish I could help more.

**Comment by GrahamCampbell** [comment]
Segfaults are a bug in php. It's possible for it to have been caused by an infinte loop (causing the call stack to overflow). Please instead the xdebug extension. It'll limit the call stack by default, so you can see if it was caused by a loop of recursive calls.

**Comment by dreferreira** [comment]
I'll investigate a little more.
@jhoff This was more just a sudden discovery that I wasn't sure of. I know there are more syntactically proper ways to do what I originally want and I have found some but I was just bringing up this issue because it resulted in the CLI crashing.

**Comment by DuckThom** [comment]
I've tried it with this:
```
$ php artisan tinker
Psy Shell v0.7.2 (PHP 5.6.28-1+deb.sury.org~xenial+1 — cli) by Justin Hileman
>>> $var = collect();
=> Illuminate\Support\Collection {#663
     all: [],
   }
>>> $var->prepend($var);
=> Illuminate\Support\Collection {#663
     all: [
       Illuminate\Support\Collection {#663},
     ],
   }
>>> $var->toJson();
```
Which also causes a segfault:
`php[27607]: segfault at 7ffe6e32fff8 ip 000055cffc1a1aa2 sp 00007ffe6e330000 error 6 in php5.6[55cffbf45000+3be000]`

I believe this is infinitely looping because you are storing a reference of `$model` inside `$model` which will cause `toJson()` to loop.
