### ISSUE TITLE
Problem using eloquent

### ISSUE THREAD

**Issue by zeeshanu** [laravel/framework#16226]
- Laravel Version: 5.3.10
- PHP Version: 7.0.9
- Database Driver & Version: mysql 5.0.12

### Description:
Why eloquent guarding all the attributes of a table I think that's why I can't create any new resource. 

![pasted_image_at_2016_11_02_03_40_pm](https://cloud.githubusercontent.com/assets/16267321/19926457/748aa962-a116-11e6-80ac-f60a5c02988f.png)

Here is my fillable array in model:
```
protected $fillable = [
        'name',
        'description',
        'parent_id',
        'user_id',
        'wiki_id',
        'created_at',
        'updated_at',
];
```

**Comment by themsaid** [comment]
Eloquent checks the `$fillable` attribute first, so if you have the field in your `fillables` the update should work fine.
