### ISSUE TITLE
[Laravel 5.3] insert null numeric column throw exception with postgress

### ISSUE THREAD

**Issue by IdenGit** [laravel/framework#16230]
- Laravel Version: 5.3.21
- PHP Version:  7.0
- Database Driver & Version: PostgreSQL 9.5.4

### Description:
When i fill numeric nullable column in eloquent model i have exception
```
$data=>[
   'name' => 'test',
   'title' => 'test',       
   'description' => 'test',
   'group' => 'test',
   'priority' => null    
];

...

$model->fill($data);

...

// throw exception, but if priority = 0 all is ok
$model->save();

```
```
QueryException in Connection.php line 763: 

SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "" 

(SQL: insert into "product_fields" 
  ("active", "title", "name", "priority", "description", "group", "product_field_type_id", "updated_at", "created_at") 
  values 
  (true, test, test, , test, test, 1, 2016-11-02 13:18:40, 2016-11-02 13:18:40) 
  returning "id"
)
```

looks like when Illuminate\Database\Query\Grammars\PostgresGrammar compile insert params, it skipp null value but postgress didn't convert empty string to integer and i get exception.

All details in my [gist](https://gist.github.com/IdenGit/9d240ef5440f91030856ccabefc9890d)

**Comment by themsaid** [comment]
But the field in't nullable https://gist.github.com/IdenGit/9d240ef5440f91030856ccabefc9890d#file-migration-L19

**Comment by IdenGit** [comment]
> But the field in't nullable
Ow, sorry i paste code from old branch. 

Tomorrow i create repo which will emulate that issue. I cant't share company repo - nda.

**Comment by IdenGit** [comment]
Thx i found throuble
