### ISSUE TITLE
validation not working after update 5.3.1*

### ISSUE THREAD

**Issue by karvannan-thi** [laravel/framework#16232]
Laravel 5.3.16,
PHP 5.6.23
DB MySQL 5.7
It throw fatal error after composer update in older version work fine.

Fatal error: Call to undefined method Symfony\Component\Translation\Translator::get() in /../vendor/illuminate/validation/Validator.php on line 2246

**Comment by themsaid** [comment]
Related to https://github.com/laravel/framework/issues/16078

We're dropping Symfony's translator in 5.4, please use laravel's translator instead since Symfony's one doesn't have this get() method.
