### ISSUE TITLE
Collection groupBy method not working with special characters in keys

### ISSUE THREAD

**Issue by hansvn** [laravel/framework#16231]
- Laravel Version: 5.3.21
- PHP Version: 5.6.13

### Description:
When using the Collection method 'groupBy' on a value that has special (hidden) characters the methods result gives duplicate keys.

Maybe this doesn't deserve highest priority but I came across the issue because of user generated input in the database (e.g. a users firstname or username).
(In my case the data came from the Google Location address api - so no user interaction at all).

### Steps To Reproduce:
```
$collection = collect([
    ['testval' => 'key'.chr(194).chr(143)],
    ['testval' => 'key'],
    ['testval' => ''],
    ['testval' => 'anotherkey'],
]);
$grouped = $collection->groupBy('testval');

//returns
[
  "key" => array:1 [
    0 => array:1 [
      "testval" => "key"
    ]
  ]
  "key" => array:1 [
    0 => array:1 [
      "testval" => "key"
    ]
  ]
  "" => array:1 [
    0 => array:1 [
      "testval" => ""
    ]
  ]
  "anotherkey" => array:1 [
    0 => array:1 [
      "testval" => "anotherkey"
    ]
  ]
]
```

Note that in the above result the first element actually is "key", but when displayed this always seems like a perfectly normal string. However the string length and content is actually different.
I came to this by splitting the string (str_split function) and then displaying the ascii character codes (ord function).

This behavior can be countered by adding a simple line to the [Collection](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Support/Collection.php) class:
`preg_replace('/[\x00-\x1F\x80-\xFF]/', '', $value)` (credit: [stackoverflow](http://stackoverflow.com/a/1176923/1114204))

I would suggest adding the line to the [valueRetriever($value)](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Support/Collection.php#L1152) function in the Collection class so other functions suffering from this behaviour (keyBy, sortBy) would be fixed as well.

**Comment by vlakoff** [comment]
It's perfectly fine behaviour. Why should the strings be altered?
Not to mention it would break *many* things.

If you need to trim, remove characters, etc. you have to do it your code.

**Comment by sisve** [comment]
@hansvn your suggestion solution will only work with the ASCII encoding, while breaking all strings that are ISO-8859-x (western, central and eastern Europe), all Unicode-related encodings (UTF-8, UTF-16, ...) and probably all other encodings...

**Comment by hansvn** [comment]
@sisve Thats true, didn't consider that. Thats also why I didn't create a pull request and just mentioned the issue.
I'ts just an inconvenience that a mysql (in my case) database does not take the special characters in account when running a query... I'll write some checks at the DB inserts :)

**Comment by sisve** [comment]
Mysql does take collations into account on all string operations. Maybe you're just using a collation that's wrong for your purpose?

https://dev.mysql.com/doc/refman/5.7/en/charset.html
