### ISSUE TITLE
Tests not triggering Token Mismatch Exception

### ISSUE THREAD

**Issue by caiquecastro** [laravel/framework#16249]
- Laravel Version: 5.3.22
- PHP Version: 7.0

### Description:
When I write a test that interacts with a form, even if the form doesn't have a csrf field, the form submission succeeds. But if I manually submit the form, it throws a Token Mismatch Exception.

### Steps To Reproduce:

**Comment by GrahamCampbell** [comment]
Probably because you're running with middleware disabled.

**Comment by caiquecastro** [comment]
No, I'm not using the WithoutMiddleware trait.

**Comment by GrahamCampbell** [comment]
Oh, yeh, that middleware is disabled during tests. Please check the source code, then it'll all make sense.

**Comment by caiquecastro** [comment]
You're right! I saw the middleware, where it has a check if it's running a test.
