### ISSUE TITLE
blade forelse's empty case true if a variable isn't passed

### ISSUE THREAD

**Issue by BartHuis** [laravel/framework#16245]
- Laravel Version: 5.3.22
- PHP Version:
- Database Driver & Version:

### Description:
Please let de empty case of a forelse be true when a certain variable isn't passed so you don't have to put an if(!empty( function around your forelse.

### Steps To Reproduce:
When i do this:

```
                @forelse ($category->categoryGallery as $image)
                    <img src="{{$image["thumb_link"]}}" />
                @empty
                @endforelse
```

i get the error:
Invalid argument supplied for foreach() (View: /......../category.blade.php)

but when i do:
```
            @if(! empty($category->categoryGallery))
                @forelse ($category->categoryGallery as $image)
                    <img src="{{$image["thumb_link"]}}" />
                @empty
                @endforelse
            @endif
```

it works, while the whole idea about forelse should be that you don't have to use an if empty check anymore.

Bart

**Comment by BartHuis** [comment]
see https://laracasts.com/discuss/channels/general-discussion/forelse-doesnt-seem-to-work

**Comment by BartHuis** [comment]
Why not @brunogaspar ?

**Comment by brunogaspar** [comment]
@BartHuis If i understood your request correctly, it means that if no variable is defined it'll silently fail, which is bad and will lead to developers wonder why the foreach doesn't work as sometimes a simple typo can lead to this type of situations and if it silently fails you have no clue where to look first.

If i understood it incorrectly, my apologies.

**Comment by BartHuis** [comment]
only if you use a forelse, not with foreach. when defining it as forelse you're choosing to go through when something isn't passed. now the behavior is strange in my opinion, because when the blade isn't getting one of the variables i want it to not do anything with it, as i explained in the laracasts topic.

**Comment by brunogaspar** [comment]
So your `$category->categoryGallery` is null at that time,  but you still want the forelse to evaluate properly?

**Comment by themsaid** [comment]
forelse uses a regular php `foreach` loop under the hood, you should put this in mind while passing data to this directive.

Closing since this isn't actually a bug report but rather a feature request, please continue on the internals repo.

For suggestions and feature requests please use the https://github.com/laravel/internals repo.

**Comment by brunogaspar** [comment]
A simple fix for your issue, since your `$category->categoryGallery` returns `null`

```
@forelse ($category->categoryGallery ?: [] as $image)
    <img src="{{$image["thumb_link"]}}" />
@empty
Nothing to show here
@endforelse
```

But either way this type of logic belongs on the app level not on the framework side.

**Comment by BartHuis** [comment]
> So your $category->categoryGallery is null at that time, but you still want the forelse to evaluate properly?

Yes, because when i fill category with 20 different items if they excist, you'll want to show them if they excist...

> @forelse ($category->categoryGallery ?: [] as $image)

yeah, thats a way too...
