### ISSUE TITLE
Use .gitkeep instead of .gitignore to keep empty folders in Git

### ISSUE THREAD

**Issue by mastertinner** [laravel/framework#16243]
- Laravel Version: 5.3.\*
- PHP Version: 7.0.11
- Database Driver & Version: \*

### Description:

Using `.gitignore` files as placeholders to keep empty folders in Git breaks Laravel apps on platforms like [Cloud Foundry](https://www.cloudfoundry.org/). The `cf push` command of the Cloud Foundry CLI ignores `.gitignore` files and also empty folders so folders like https://github.com/laravel/laravel/tree/master/bootstrap/cache don't get `cf push`ed. I think we should replace the `.gitignore` files in the following folders of Laravel with an empty `.gitkeep` file:

* `laravel/bootstrap/cache`
* `laravel/storage/framework/cache`
* `laravel/storage/framework/sessions`
* `laravel/storage/framework/views`

### Steps To Reproduce:

1. Run `composer create-project laravel/laravel your-project-name`
1. Install the [Cloud Foundry CLI](https://docs.cloudfoundry.org/cf-cli/install-go-cli.html)
1. Add a `.bp-config/options.json` file with the following content to your project:

  ```json
  {
    "WEBDIR": "public",
    "COMPOSER_VENDOR_DIR": "vendor",
    "PHP_VERSION": "{PHP_70_LATEST}",
    "PHP_EXTENSIONS": [ "bz2", "zlib", "openssl", "fpm", "tokenizer", "curl", "mcrypt", "mbstring", "pdo", "pdo_mysql"]
  }
  ```
1. Run `cf push`
1. The app fails to run with the exception `InvalidArgumentException in Compiler.php line 36:
Please provide a valid cache path.`

If you guys agree, I'll happily provide a pull request for that.

**Comment by ntzm** [comment]
But we need to ignore files in those directories? We don't want cache files to be pushed

**Comment by mastertinner** [comment]
I see... In that case, maybe there should be both?

**Comment by ntzm** [comment]
It's working as intended with git, I think this is more of a Cloud Foundry issue that you should bring up with them instead

**Comment by themsaid** [comment]
> I think this is more of a Cloud Foundry issue that you should bring up with them instead

Agreed
