### ISSUE TITLE
Eloquent find returns more than one record

### ISSUE THREAD

**Issue by BossOfGames** [laravel/framework#16240]
- Laravel Version: 5.3
- PHP Version: 5.6.4
- Database Driver & Version: MySQL

### Steps To Reproduce:

Setup Models with a relationship.

Then query the model. Ex: $template = ScheduleTemplate::find($id)->with('depapt')->with('arrapt')->with('airline')->with('aircraft_group');

This returns multiple records instead of just one.

**Comment by sisve** [comment]
Try ::find() without adding those ->with() invocations. They do not work as you think they do.

`$template = ScheduleTemplate::find($id)`

**Comment by themsaid** [comment]
This is wrong, `with()` will return an instance of Builder not results, if you want to lazy load you need to use `load()` instead of `with()`
