### ISSUE TITLE
Enhancement request -> Dotenv implementation

### ISSUE THREAD

**Issue by jasonhebert** [laravel/framework#16253]
### Description:

I would like to suggest making available within the bootstrapping process the instance of Dotenv used to load environment variables and provide a mechanism to add and enforce validations on the .env file.

Currently the environment variables are loaded within the `bootstrap()` method of the `Illuminate/Foundation/Bootstrap/DetectEnvironment.php` class using `(new Dotenv($app->environmentPath(), $app->environmentFile()))->load();`. The object instance is thrown away and doesn't give developers an easy opportunity to enforce environment variable validations such as `required()`, `notEmpty()`, `isInteger()` or `allowedValues()`.

**Comment by themsaid** [comment]
I know you've opened the feature request on the forums and you got redirected to posting it here, we keep this repo for bug reporting only :) For suggestions and feature requests please use the https://github.com/laravel/internals repo.

Regarding the idea of the request, I wonder why would you need to validate the dot env variables? you can have defaults in your config & thus validation won't be necessary right?

**Comment by jasonhebert** [comment]
Thanks @themsaid I'll add the request where suggested.
As to your question: We have a need to be able to enforce the existence and validation of a number of properties in the env file. These properties change for local, QA and production environments. We've run into issues with the enforcement in the past and have included a number of different mechanisms within our applications but none are as clean and tidy as that which is provided already with the `Dotenv` library. It would be nice to have the ability to enforce those validations as the application is being bootstrapped.

**Comment by themsaid** [comment]
that's interesting, let's see what the community thinks of this matter :)
