### ISSUE TITLE
artisan route:cache not working in some cases

### ISSUE THREAD

**Issue by lozovoyv** [laravel/framework#16256]
- Laravel Version: 5.3.21
- PHP Version: 7.0.11
- Database Driver & Version: MySQL 5.7.15

### Description:
I wanted to register routes in controller classes. Routes is stored as array of parameters in separate files related to controller. In general it works fine. `artisan route:list` shows list of routes as expected. But `artisan route:cache` says what I have no routes in my application if there is no `bootstrap/cache/routes.php` file. If I create it manually or write `Route::get(...)` in usual way `route:cache` works as expected.

### Steps To Reproduce:
RouteServiceProvider
```
    protected function mapWebRoutes()
    {
        Route::group([
            'middleware' => 'web',
            'namespace' => $this->namespace,
        ], function ($router) {
            $modules = config('modules.modules'); //array of classes I want to route
            foreach ($modules as $module) {
                app($module)->registerSystemRoutes();
            }
            //require base_path('routes/web.php');
        });
    }
```

```
class Module extends Controller //parent class for controllers
{
	protected $routes;

public function __construct()
{
	\App::singleton(get_class($this), function () {return $this;});
	if(file_exists($this->getModulePath().DIRECTORY_SEPARATOR.'Routes.php')) {
		$this->routes = require_once $this->getModulePath().DIRECTORY_SEPARATOR.'Routes.php';
	}
}

public function registerSystemRoutes()
{
	$this->map('system');
}

public function map($section)
{
	if(isset($this->routes[$section]) && is_array($this->routes[$section])){
		foreach($this->routes[$section] as $route){
			$method = $route['method'];
			$path = $route['path'];
			$action = $route['action'];
			$name = $route['name'];
				
			if ($method == 'get') {
				Route::get($path, $action)->name($name);
			}
			if ($method == 'post') {
				Route::post($path, $action)->name($name);
			}
		}
	}
}

}
```

**Comment by themsaid** [comment]
>  If I create it manually or write Route::get(...) in usual way route:cache works as expected.

Can you please elaborate more?

**Comment by lozovoyv** [comment]
@themsaid, simpliest way is `touch routes.php`

**Comment by lozovoyv** [comment]
@themsaid I found more interesting example.
If I write `RouteServiceProvider` like this:
```
    protected function mapWebRoutes()
    {
        Route::group([
            'middleware' => 'web',
            'namespace' => $this->namespace,
        ], function ($router) {
            $modules = config('modules.modules');
            foreach ($modules as $module) {
                app($module)->registerSystemRoutes();
                app($module)->registerPublicRoutes();
                app($module)->registerBackendRoutes();
            }
            Route::get('/', '\Modules\HomePage\Controllers\HomePageController@showHomePage')->name('another_homepage');
            //require base_path('routes/web.php');
        });
    }
```
I have this:
```
> php artisan route:clear
Route cache cleared!
> php artisan route:list
+--------+----------+------------------------+---------------------------+----------------------------------------------------------------------------+------------+
| Domain | Method   | URI                    | Name                      | Action                                                                     | Middleware |
+--------+----------+------------------------+---------------------------+----------------------------------------------------------------------------+------------+
|        | GET|HEAD | /                      | another_homepage          | \Modules\HomePage\Controllers\HomePageController@showHomePage              | web        |
|        | POST     | email/confirm          | auth_confirm_email        | \Modules\Auth\Controllers\EmailConfirmController@sendConfirmationLinkEmail | web,auth   |
|        | GET|HEAD | email/confirm          | auth_confirm_email        | \Modules\Auth\Controllers\EmailConfirmController@showLinkRequestForm       | web,auth   |
|        | GET|HEAD | email/confirm/{token}  | auth_confirm_email_check  | \Modules\Auth\Controllers\EmailConfirmController@confirm                   | web        |
|        | GET|HEAD | login                  | auth_login                | \Modules\Auth\Controllers\LoginController@showLoginForm                    | web,guest  |
|        | POST     | login                  | auth_login                | \Modules\Auth\Controllers\LoginController@login                            | web,guest  |
|        | POST     | logout                 | auth_logout               | \Modules\Auth\Controllers\LoginController@logout                           | web        |
|        | POST     | password/email         | auth_email_reset_link     | \Modules\Auth\Controllers\ForgotPasswordController@sendResetLinkEmail      | web,guest  |
|        | GET|HEAD | password/reset         | auth_reset_password       | \Modules\Auth\Controllers\ForgotPasswordController@showLinkRequestForm     | web,guest  |
|        | POST     | password/reset         | auth_reset_password       | \Modules\Auth\Controllers\ResetPasswordController@reset                    | web,guest  |
|        | GET|HEAD | password/reset/{token} | auth_reset_password_token | \Modules\Auth\Controllers\ResetPasswordController@showResetForm            | web,guest  |
|        | GET|HEAD | register               | auth_register             | \Modules\Auth\Controllers\RegisterController@showRegistrationForm          | web,guest  |
|        | POST     | register               | auth_register             | \Modules\Auth\Controllers\RegisterController@register                      | web,guest  |
+--------+----------+------------------------+---------------------------+----------------------------------------------------------------------------+------------+
> php artisan route:cache
Route cache cleared!
Routes cached successfully!
> php artisan route:list
+--------+----------+-----+------------------+---------------------------------------------------------------+------------+
| Domain | Method   | URI | Name             | Action                                                        | Middleware |
+--------+----------+-----+------------------+---------------------------------------------------------------+------------+
|        | GET|HEAD | /   | another_homepage | \Modules\HomePage\Controllers\HomePageController@showHomePage | web        |
+--------+----------+-----+------------------+---------------------------------------------------------------+------------+
```

**Comment by themsaid** [comment]
I can't replicate the issue by registering the routes inside the service provider instead of the routes file,

```
    protected function mapWebRoutes()
    {
        Route::group([
            'middleware' => 'web',
            'namespace' => $this->namespace,
        ], function ($router) {
            $router->get('one', 'Controller@method');
            $router->post('two', 'Controller@method');
        });
    }
```

You seem to be doing a lot behind the scenes that I won't be able to replicate since it's a lot of custom code, but registering routes in the web.php or directly inside the service provider, or even using a class that have something like this:

```
        $this->routes = [
            'system' => [
                [
                    'method' => 'get',
                    'path' => 'one',
                    'action' => 'Controller@method',
                    'name' => 'asd',
                ],
                [
                    'method' => 'post',
                    'path' => 'two',
                    'action' => 'Controller@method',
                    'name' => 'asd',
                ]
            ]
        ];

public function map($section)
    {
        if (isset($this->routes[$section]) && is_array($this->routes[$section])) {
            foreach ($this->routes[$section] as $route) {
                $method = $route['method'];
                $path = $route['path'];
                $action = $route['action'];
                $name = $route['name'];

                if ($method == 'get') {
                    Route::get($path, $action)->name($name);
                }
                if ($method == 'post') {
                    Route::post($path, $action)->name($name);
                }
            }
        }
    }
```

All of this works fine on my end, it's hard to tell what your issue is since there's a lot of custom code involved, so please continue the discussion on the forums and I'm sure someone will be able to help you there, but I can't really consider this as a bug report :) You'r doing too much behind the scenes.

**Comment by chilio** [comment]
@lozovoyv I'm experiencing similar behaviour, on L5.5, PHP 7.1, MySQL 5.7.
I am also using MapWebRoutes to organize routes to certain directory structure.
Last thing is I call `\Artisan::call('route:cache', [], $output);` in my deploy script.
It goes smooth without any errors, but sometimes routes are created and sometimes not.
If I call artisan route:cache manually, after deploy script, all caches properly.
Strange behavior so I wonder, if you managed around this issue ?

**Comment by lozovoyv** [comment]
@chilio Can't tell you anything without code. =)
My problem was assigned with storing arrays in separate files. In `php artisan route:cache` command these arrays wasn't properly loaded for some reasons. I did it another way and another logic.

**Comment by chilio** [comment]
Hi again @lozovoyv 
I'm using RouteServiceProvider with:
```
public function map(Router $router)
    {
        $this->mapApi($router);
        $this->mapWebRoutes();
    }
```
And then 
```
protected function mapApi(Router $router){
        $router->group(['namespace' => $this->namespace], function ($router) {
            foreach (glob(base_path('routes/api/*.php')) as $eachRoute) {
                include_once $eachRoute;
            }
        });
    }
```
And then in route file for example...
```
Route::group(array('prefix' => 'tests'), function () {
    Route::get('test1','TestController@test1');
});
```
So basically, no closures in any of the routes.
And because I'm using bunch of files for defining routes, I'm more then sure, that all my routes should be cached.
`artisan route:cache` works fine, the only problem is that, when I call it from my custom artisan Command, it only works sometimes, or only sometimes doesn't work (with no error unfortunately).
Maybe you see something odd in my approach, or have some suggestions, on how to organize my routes in a better way, or with another logic :). Thanks in advance...

**Comment by crynobone** [comment]
Don't use require or include once.

**Comment by crynobone** [comment]
You can perfectly use `include` or `require`.

* Laravel uses `require` internally, see [Illuminate\Routing\Router](https://github.com/laravel/framework/blob/v5.6.2/src/Illuminate/Routing/Router.php#L387-L396)
* Artisan command `route:cache` create a sub-app to build routing, when you do `require_once` or `include_once` the sub-app wouldn't load your routes again,
 see [Illuminate\Foundation\Console\RouteCacheCommand](https://github.com/laravel/framework/blob/v5.6.2/src/Illuminate/Foundation/Console/RouteCacheCommand.php#L77-L95)
* You want to use `route:cache`, the routes wouldn't even be loaded when the cached file is available, see [Illuminate\Foundation\Support\Providers\RouteServiceProvider](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Foundation/Support/Providers/RouteServiceProvider.php#L30-L39)

**Comment by chilio** [comment]
@crynobone really appreciated your detailed explanation.
You are perfectly fine, about that....
I've already changed my `include_once` to `require`.
And all works fine for now...
So far I haven't seen any problems (tested at least 10 times)
BTW, I think it should also work, with php base functions. like require_once, or am I missing something...
I still thank you again, for solving my problem....
My final question is, why does this not bring **totally nothing** in output, from my custom artisan command ....
```
$output = new BufferedOutput();
\Artisan::call('route:cache',['-vvv' => true], $output);
$this->info(\Artisan::output());
```
Do you have any idea about that? 
This one actually happen always, although really implying changes, by `artisan route:cache`
