### ISSUE TITLE
imap expunge errors cause segfault (b/c of errorHandler)

### ISSUE THREAD

**Issue by Blizzke** [laravel/framework#16252]
- Laravel Version: 5.3.22
- PHP Version: 7.0.12

### Description:
Tbh, I don't know what can be done about this (if anything), but it took me quite some time to track down. Just wanted to create a record of it in case other people encounter it. 

I have an artisan command that uses the `imap_*` functionality to enumerate emails and then delete them when it's done. 

The connection is closed at the end of the command (`imap_close()` with expunge enabled). The code then continues up to the `exit($status);`-statement in the `artisan` file.

Apparently - even though that connection should be closed already - the actual expunging (and I assume closing) happens "as part" of that last statement. With some malformed emails, the expunging generates a bunch of `E_NOTICE`s (8). 

Because this is still done as part of the regular php process, it is caught by `HandleExceptions::handleError()`, which turns it into an `ErrorException`. My testdata generates about 30 of these, but the first throw is enough to have php produce a segfault.

What I did at this point is override the error handler - right before the exit statement - with a function that just `error_log()`'s the messages to avert this. 

Perhaps some kind of "`isShuttingDown`"-state can be introduced where the error handler switches from throwing exceptions to messages? Pretty rare situation, so I don't know if it warrants action. Up to you guys. 

FYI: Some of the actual error messages, for google-indexing purposes:

```TEXT
"Unknown: Unexpected characters at end of parameters: 8476-20190.zip (errflg=3)" @ "Unknown#0"
"Unknown: Ignoring nested encoding of multipart contents (errflg=3)" @ "Unknown#0"
"Unknown: Unexpected characters at end of parameters: 48372-2500.zip (errflg=3)" @ "Unknown#0"
"Unknown: Warning: MIME header encountered in non-MIME message (errflg=3)" @ "Unknown#0"
"Unknown: Missing parameter (errflg=3)" @ "Unknown#0"
```

**Comment by taylorotwell** [comment]
Can you share more about how you fixed it by overriding the error handler?

**Comment by Blizzke** [comment]
<img width="800" alt="screen shot 2016-11-14 at 16 08 21" src="https://cloud.githubusercontent.com/assets/231572/20269698/9f05c056-aa84-11e6-942f-2830a756f4fc.png">

Basically, i changed the end of the `artisan` file:

```php
// Override error handler during shutdown (mainly for issues with IMAP Mailboxes starting to throw fatal errors when the expunge goes wrong
// Laravel does not see these as "during shutdown" ('cause they aren't) and just tries throwing ErrorExceptions around, causing a Segmentation Fault
set_error_handler(function($level, $message, $file = '', $line = 0, $context = []) {
    if (error_reporting() & $level) {
        error_log('Error caught during shutdown: "' . $message . '" @ "' . $file . '#' . $line . '"');
    }
});
```

**Comment by deleugpn** [comment]
I think I experienced this after forking [barbushin/php-imap](https://github.com/barbushin/php-imap/) project and my work-around was to add `imap_errors();` and `imap_alerts();` call before `imap_close`. My result was something like this:
```
    protected function disconnect() {
        $imapStream = $this->getImapStream(false);
        if ($imapStream && is_resource($imapStream)) {
            imap_errors();
            imap_alerts();
            imap_close($imapStream, $this->expungeOnDisconnect ? CL_EXPUNGE : 0);
        }
    }
```

Sadly, I don't remember from where I got this idea, it might have been from this [StackOverflow Question](http://stackoverflow.com/questions/14410430/trying-to-parse-imap-email-with-php-fatal-error-exception-thrown-without-a-st).
