### ISSUE TITLE
unauthenticated() method is not defined

### ISSUE THREAD

**Issue by andkom** [laravel/framework#16258]
Default laravel exception handler calls to undefined method unauthenticated()

file: Illuminate/Foundation/Exceptions/Handler.php:135

`
            return $this->unauthenticated($request, $e);
`

**Comment by GrahamCampbell** [comment]
It's defined here: https://github.com/laravel/laravel/blob/master/app/Exceptions/Handler.php#L57.

**Comment by andkom** [comment]
i know but you want make it empty or abstract in the base class

**Comment by juanvillegas** [comment]
@andkom is right, the base class should be abstract if the method is missing.
