### ISSUE TITLE
Builder::withCount() ignores HAVING condition

### ISSUE THREAD

**Issue by mrpiatek** [laravel/framework#16266]
- Laravel Version: 5.3.22
- PHP Version: PHP 7.0.8-0ubuntu0.16.04.3
- Database Driver & Version: MySQL Ver 14.14 Distrib 5.7.15, for Linux (x86_64) using  EditLine wrapper

### Description:

Hello,

I've encountered an issue with `withCount()` function in QueryBuilder. It ignores `HAVING` conditions.

I have a one-to-many relationship between User and Projects. Each project has their own status log, where most recent entry from the status log determines project's current status. I need to get all users with open projects count (not all of the projects) in a query to allow sorting and filtering.

My User Model (simplified):

```php
class User extends Model {
    public function projects()
    {
        return $this->hasMany(Project::class);
    }

    public function open_projects()
    {
        $tPrefix = DB::getTablePrefix();
        return $this->projects()
            ->select(['id', 'user_id', 'name', DB::raw("(select status from {$tPrefix}project_statuses where project_id={$tPrefix}projects.id order by created_at desc limit 1) as status")])
            ->having('status','=', 'open');
    }
}
```

The problem is that when I use `User::with('open_projects')` it attaches open projects list to each user as expected (only those projects that most recent status is `open`), but when I use `withCount('open_projects')` it counts *all* projects instead of just opened. It works exactly as if I used `withCount('projects')` even though `open_projects` relation has additional condition.

It works as expected when using `where()` in the extended (`open_projects`) relation, but ignores `having()` condition.

Sorry if I'm doing something wrong, any help will be much appreciated :)

### Steps To Reproduce:

1. Create relationship that has a `HAVING` condition
2. Use `withCount()` on that relationship

**Comment by themsaid** [comment]
Only were conditions are supported atm, I'm not even sure if we can support having, looks like it'll require big changes.

**Comment by sdawka** [comment]
> * Laravel Version: 5.3.22
> * PHP Version: PHP 7.0.8-0ubuntu0.16.04.3
> * Database Driver & Version: MySQL Ver 14.14 Distrib 5.7.15, for Linux (x86_64) using  EditLine wrapper
> 
> ### Description:
> Hello,
> 
> I've encountered an issue with `withCount()` function in QueryBuilder. It ignores `HAVING` conditions.
> 
> I have a one-to-many relationship between User and Projects. Each project has their own status log, where most recent entry from the status log determines project's current status. I need to get all users with open projects count (not all of the projects) in a query to allow sorting and filtering.
> 
> My User Model (simplified):
> 
> ```
> class User extends Model {
>     public function projects()
>     {
>         return $this->hasMany(Project::class);
>     }
> 
>     public function open_projects()
>     {
>         $tPrefix = DB::getTablePrefix();
>         return $this->projects()
>             ->select(['id', 'user_id', 'name', DB::raw("(select status from {$tPrefix}project_statuses where project_id={$tPrefix}projects.id order by created_at desc limit 1) as status")])
>             ->having('status','=', 'open');
>     }
> }
> ```
> 
> The problem is that when I use `User::with('open_projects')` it attaches open projects list to each user as expected (only those projects that most recent status is `open`), but when I use `withCount('open_projects')` it counts _all_ projects instead of just opened. It works exactly as if I used `withCount('projects')` even though `open_projects` relation has additional condition.
> 
> It works as expected when using `where()` in the extended (`open_projects`) relation, but ignores `having()` condition.
> 
> Sorry if I'm doing something wrong, any help will be much appreciated :)
> 
> ### Steps To Reproduce:
> 1. Create relationship that has a `HAVING` condition
> 2. Use `withCount()` on that relationship

you can put the having inside withCount
