### ISSUE TITLE
[5.3] [Testing] attach() problem

### ISSUE THREAD

**Issue by shadoWalker89** [laravel/framework#16264]
- Laravel Version: 5.3.22
- PHP Version: 5.6.15

### Description:

I have a 5.2 project with a test where i use attach() to upload a file.

After upgrading to 5.3, the test start failing.

I tracked down the problem to `Illuminate/Validation/Validator.php` line `503`.
`$value->isValid()` method on `Symfony\Component\HttpFoundation\File` returns `false` because `is_uploaded_file($this->getPathname())` is returning `false`.

This is a screen shot from the test

![image](https://cloud.githubusercontent.com/assets/1449151/20000667/f34ff028-a278-11e6-875f-1b4618f089d9.png)

And this is the screen shot from the browser when submitting the form

![image](https://cloud.githubusercontent.com/assets/1449151/20000698/1e33648c-a279-11e6-8b11-2d0b2fb3a884.png)

The form it self is working fine.
As you can see the path on the second screen shot is under wampserver which is why `is_uploaded_file($this->getPathname())` returns true.
But in the first screen shot the path is under `C:`, which indicates that the file was stored there without being uploaded from the form using http.

**Comment by shadoWalker89** [comment]
As you can see in the screenshot from the console the `test` attribute is false

I narrowed it down to `Illuminate\Foundation\Testing\Concerns::convertUploadsForTesting()` line 699, the file is not being created using `getUploadedFileForTesting()`.

Maybe all uploads should be created using `getUploadedFileForTesting()` in order for the `test` attribute to be true.

**Comment by shadoWalker89** [comment]
This is my test

```php
->attach(base_path('tests/_data/student/student_import.xlsx'), '#file')
```

I'm using the field `id` to target the input. If i use the name attribute `file` instead of the id `#file` the test passes.

The problem is at this check

`Illuminate\Foundation\Testing\Concerns::convertUploadsForTesting()` line `699`

```php
$files = array_map(function (array $file, $name) use ($uploads) {
    return isset($uploads[$name])
                ? $this->getUploadedFileForTesting($file, $uploads, $name)
                : $file;
}, $files, $names);
```

`$uploads` value 

![image](https://cloud.githubusercontent.com/assets/1449151/20002189/0167c4a4-a280-11e6-8a13-219b689a8ce8.png)

`$name` value is `file`

And the 
```php 
isset($uploads[$name])
``` 
will return false which explains why `$this->getUploadedFileForTesting()` never gets triggered and the uploaded file has the `test` attribute set to `false`

**Comment by themsaid** [comment]
Hello there,

Can you please share a sample form and test that fails, your PR has breaking changes that's why it was closed, let's continue the discussion here and see if it's something that needs to be fixed or just an undocumented 5.3 change, we changed some parts in this area during the past couple of months.

**Comment by shadoWalker89** [comment]
This is my test

```php
/** @test */
    public function it_imports_students()
    {
        $importer = Mockery::mock(Importer::class);
        $importer->shouldReceive('import')->once()->withAnyArgs();

        $this->app->instance(Importer::class, $importer);

        $this->visit('/student/import')
            ->attach(base_path('tests/_data/student/student_import.xlsx'), '#file')
            ->pressSubmitButton();

        $this->seePageIs('/student');
    }
```

------------------------------------------------------------------------------------------
The test is failing because the `$test` attribute on the `Illuminate\Http\UploadedFile` is being false.
In order for it to be `true` the `Illuminate\Http\UploadedFile` should be created using this method `Illuminate\Foundation\Testing\Concerns\InteractsWithPages::getUploadedFileForTesting()`
This happens only when using the file input `id` instead of the `name`

Saying that we have this form.

```html
<input type="file" name="source" id="source" />
```

When using `attach('file.xlsx', '#source')` the attributes within Illuminate\Foundation\Testing\Concerns\InteractsWithPages will have this values.

$inputs attribute
```php
['source' => 'full_path/file.xlsx']
```

$uploads attribute
```php
['#source' => 'full_path/file.xlsx']
```

The `$uploads` variable in `convertUploadsForTesting()` is equal to `$uploads` Trait's attribute, so the following check `isset($uploads[$name])` at the line `699` will return `false` because the `$name` variable will have the value `source`.
Due to the `isset($uploads[$name])` being false the `getUploadedFileForTesting()` will not be triggered.

To fix this i'm passing `$this->inputs` attribute instead of the `$this->uploads`.
This way, the keys of the `$uploads` variable in the `convertUploadsForTesting()` method will be always the input file `name` attribute value even if the user uses an `id` when calling the `attach()` method on his test.

-------------------------------------------------------------------------------------

it's true that the docs are saying to use the name attribute but i didn't pay attention to it before, and i have been using the id with my tests passing.
So i think maybe it's easier that i update my tests then to go on with this changes.

**Comment by themsaid** [comment]
yes I think we solved some inconsistency issue earlier, it might have been working in the past due to a bug, after the fix it stopped working, but the input name is what should be used.
