### ISSUE TITLE
FactoryBuilder::make() returns Eloquent Model instance when amount is 1

### ISSUE THREAD

**Issue by dotZoki** [laravel/framework#16269]
- Laravel Version: 5.3.19
- PHP Version: 7.0.8
- Database Driver & Version: /

### Description:
FactoryBuilder::make() comment/description says "Create a collection of models." I'm having a case where I choose random amount number (e.g. 0-5) and then loop through returned Collection. When amount is 1 it returns Eloquent Model instance and thus each is not working. Shouldn't it return Collection of 1 also? Wouldn't that be more consistent?

### Steps To Reproduce:
I used code like this:
```
factory('App\Client', 20)->create()->each(function($client) {
    factory('App\Contact', Faker\Factory::create()->numberBetween(0, 5))->make()->each(function($contact) use($client) {
        $client->contacts()->save($contact);
    });
});
```

**Comment by themsaid** [comment]
Please upgrade to latest `5.3` version, I think that was fixed sometime ago.

**Comment by dotZoki** [comment]
Not a bug, more of a wrong implementation. But I wonder will it be changed?

**Comment by themsaid** [comment]
That was fixed I'm sure, please upgrade your laravel installation `v5.3.22 `, ping me if you're still facing issues there.

Closing since that was fixed.

**Comment by dotZoki** [comment]
Updated to 5.3.22 and doesn't seem to be "fixed".

FactoryBuilder:make() still contains:
```
if ($this->amount === 1) {
    return $this->makeInstance($attributes);
}
```
and  thus this doesn't go through each
```
factory('App\Contact', 1)->make()->each(function($contact) use($client) {
    $client->contacts()->save($contact);
});
```

**Comment by themsaid** [comment]
Yes right, my fix for that wasn't accepted, check here https://github.com/laravel/framework/pull/13540

**Comment by dotZoki** [comment]
Can't say that #13540 contains any strong arguments why it was implemented in that way as it is now.
