### ISSUE TITLE
Don't use ::class

### ISSUE THREAD

**Issue by allowing** [laravel/framework#16270]
I think, Don't use ::class, should use sring class name.

Why? because ::class will trigger auto load the class.sometimes we never no use it.

**Comment by brunogaspar** [comment]
From the PHP Manual

> The class name resolution using ::class is a compile time transformation. That means at the time the class name string is created no autoloading has happened yet. As a consequence, class names are expanded even if the class does not exist. No error is issued in that case.

http://php.net/manual/en/language.oop5.basic.php#language.oop5.basic.class.class
