### ISSUE TITLE
[5.3] Migration - nullable not working

### ISSUE THREAD

**Issue by rmff** [laravel/framework#16276]
- Laravel Version: 5.3.22
- PHP Version: 7.0.12
- Database Driver & Version: Mysql  5.7.12-0ubuntu1.1

### Description:
Set column to nullable not working

### Steps To Reproduce:
```
    public function up()
    {
        Schema::create('test_nullable', function(Blueprint $table) {
            $table->string('normal');
            $table->string('nullable')->nulable();
            $table->string('nullableTrue')->nulable(true);
            $table->string('nullableFalse')->nulable(false);
            $table->timestamps();
        });
    }
```
Query logged:

```
create table `test_nullable` (
`normal` varchar(255) not null, 
`nullable` varchar(255) not null, 
`nullableTrue` varchar(255) not null, 
`nullableFalse` varchar(255) not null, 
`created_at` timestamp null, 
`updated_at` timestamp null
) default character set utf8 collate utf8_unicode_ci
```

Nullable only worked for timestamps...

**Comment by rs-sliske** [comment]
if thats a c+p you missed an 'L' from the method

```    public function up()
    {
        Schema::create('test_nullable', function(Blueprint $table) {
            $table->string('normal');
            $table->string('nullable')->nulable();
            $table->string('nullableTrue')->nulable(true);
            $table->string('nullableFalse')->nulable(false);
            $table->timestamps();
        });
    }```

**Comment by rmff** [comment]
OMG @rs-sliske I need back to English classes! 

Do you know why this call didn't throw some execution exception? 
They are suppressed or query builder ignored wrong calls?

I had only notice this error because L 5.3 uses as default MySQL in strict mode, on no-strict mode, MySQL acepets null values even if the column was set as not nullable.

Thanks and sorry for this lack of attention!

**Comment by rs-sliske** [comment]
tbh im not sure why it wouldnt show an error, i guess its just ignoring any methods it doesnt recognize

**Comment by Pezhvak** [comment]
something is wrong with nullable(), I'm using 5.4 and every time I refresh my migrations it seems that I ignores nullable() completely

**Comment by memordial** [comment]
@Pezhvak yeah it also happens to me.

**Comment by adriangrahl** [comment]
@Pezhvak same here. In 5.5 after changing nullable('false') and rolled back nullable() didn't changed anymore.

**Comment by FrancescoMussi** [comment]
Same here in 5.7

Making `php artisan migrate:fresh` doesn't take into account the `nullable`.
I have to delete all tables and run `php artisan migrate`.

**Comment by shark0der** [comment]
I can confirm that when altering the table the nullable flag doesn't change. Code:

```
    public function up() {
        Schema::table('ticket_types', function (Blueprint $table) {
            $table->string('text_on_ticket')
                  ->default('')
                  ->nullable(true) // the parameter is optional if true, specified it just in case.
                  ->change();
        });
    }

    public function down() {
        Schema::table('ticket_types', function (Blueprint $table) {
            $table->string('text_on_ticket')
                  ->default('')
                  ->nullable(false)
                  ->change();
        });
    }
```

Ran and rolled back the migration a couple of times - nothing changed.
