### ISSUE TITLE
Validating array where keys contain forward slashes

### ISSUE THREAD

**Issue by niekvanderkooy** [laravel/framework#16287]
- Laravel Version: 5.2.45 (Issue seems to have been introduced starting 5.2)
- PHP Version: 7.0.10

### Description:
When running validator on an array key which contains a forward slash, I run into an error exception in Validator.php line 2716 (`Validator::getExplicitKeys($attribute)`, where `preg_match` is run on `$pattern` generated from the attribute.

I have not found the proper way (if there is any) to escape this forward slash, and note that in my use case the data comes in a pre-specified format which I cannot change. I realise I could change the key before validation, but I am wondering if there is a way to make the validator work as-is, or if the validator is even intended to work in this case.

### Steps To Reproduce:
The following code does not work, since calling `$validator->fails()` generates the ErrorException.
```
		$arr = [
			'fine' => 'foo',
		        'not/fine' => 'bar'
		];

		$validator = Validator::make($arr, [
			'fine' => 'required',
		        'not/fine' => 'required',
		]);

		if($validator->fails()) {
			dd('uh-oh');
		}
```

**Comment by themsaid** [comment]
Thank you for reporting this, a PR was submitted to handle the issue: https://github.com/laravel/framework/pull/16309
