### ISSUE TITLE
Failed to set namespaced invokable controller as route action using ::class notation

### ISSUE THREAD

**Issue by pinepain** [laravel/framework#16288]
- Laravel Version: 5.3.22
- PHP Version: 7.0
- Database Driver & Version: any

### Description:

As description said:  setting namespaced invokable controller as route action using ::class notation causes `Invalid route action` exception when that controller class imported in `routes.php` using `use` statement and then controller name retrieved using `::class notation.`

To keep track classes usage and to enable type analysis in IDE to be able to utilizing IDE refactoring features (rename/move) in PHPStorm we import controller classes and use `::class` notation. Having `App\Http\Controllers\Test` controller but referencing it as `Test` breaks this approach, as well as IDE types analysis (but not limited to IDEs only). While there are a lot of nice workarounds from swapping with own Route facade root to patching laravel/framework and using own fork, I decided to discuss it here as I'm pretty sure I'm not the one who faces with this issue (I hit it with 5.1 initially, if I recall it right).

### Steps To Reproduce:

1. Create namespaced controller with `__invoke()` method.
2. Set controller as route action, e.g. `Route::get('/login', App\Http\Controllers\Test::class)`.
3. Request any http url or run any artiasn command to see the error.

**Comment by pinepain** [comment]
The issue reside in `\Illuminate\Routing\Router::prependGroupUses()` method when we doubl-prepend controllers namespace specified in `\App\Providers\RouteServiceProvider::$namespace`.

**Comment by pinepain** [comment]
It looks like probing whether controller name already namespaced before appending it with `strpos($uses, $group['namespace'].'\\') !== 0` condition solves the issue.

```php
    /**
     * Prepend the last group uses onto the use clause.
     *
     * @param  string  $uses
     * @return string
     */
    protected function prependGroupUses($uses)
    {
        $group = end($this->groupStack);

        return isset($group['namespace']) && strpos($uses, '\\') !== 0 && strpos($uses, $group['namespace'].'\\') !== 0 ? $group['namespace'].'\\'.$uses : $uses;
    }
```
Are we OK with this sort of changes? If so, I will PR immediately.

**Comment by brunogaspar** [comment]
I tested here and it works as expected:

Laravel 5.3.21
PHP 7.0.8

```php
Route::get('/', HomeController::class)->name('home');
```

You're most likely defining that route inside the default Route group which already has a namespace `App\Http\Controllers` defined, try to pass only `Test::class` instead of `App\Http\Controllers\Test::class`:

```php
Route::get('/login', Test::class);
```

**Comment by pinepain** [comment]
@brunogaspar to keep track on classes usage I explicitly import class and use ::class notation. Having `App\Http\Controllers\Test` controller but referencing it as `Test` breaks type analysis in IDE which leads to issues during utilizing IDE refactoring features (rename/move) in PHPStorm at least. While there are a lot of nice workarounds from swapping with own `Route` facade root to patching laravel/framework and using own fork, I decided to discuss it here as I'm pretty sure I'm not the one who faces with this issue (I hit it with 5.1 initially, if I recall it right).

**Comment by brunogaspar** [comment]
Ah makes sense. But you should mentioned that on the OP :)

But seems a bug though, nice catch.

**Comment by taylorotwell** [comment]
Meh, it's really a bug in the route registration. The web.php routes file is *already* loaded with a namespace prefix but you are still passing the full controller class name. Fixing this "bug" would just open up another one where I can't have a controller with a namespace that matches the root namespace.
