### ISSUE TITLE
[5.2.45] Losing https in public/subfolder

### ISSUE THREAD

**Issue by ilvalerione** [laravel/framework#16299]
- Laravel Version: 5.2.45
- PHP Version: 7
- Database Driver & Version: MySQL

### Description:
1. I access to my application by an HTTPS address. (Let's Encrypt is installed)
2. I want to point a static HTML page in public/subfolder always with https.

I generate a link for /subfolder using `{{ url('/subfolder') }}` and in HREF i see the link is generated with https prefix correctly using "inspect" tool of Chrome. `https/www.mydomain.com/subfolder`

When i click on this link I have redirected to this /subfolder but I lose the https prefix. The link is opened with normal http.

### Steps To Reproduce:
1. You need a web server with a SSL certificate installed

2. Create a subfolder under public/ and put a static index.html with simple "Hello world"

3. Into welcome.blade.php insert a link to this subfolder with a simple line of code
`<a href="{{ url('/subfolder') }}">Go to subfolder</a>`

4. Access to your laravel welcome page using https:// prefix

5. Click on the link for /subfolder and you verify in your address bar on browser that you've been redirected losing https prefix.

### Notes
Laravel manage redirection to subfolders if there isn't any route that match the given path. 

Do you may need to add a fix to the .htaccess file?

Thanks for your support

**Comment by sisve** [comment]
A static `public/something/index.html` is not handled by Laravel. This sounds like a webserver configuration issue.

**Comment by themsaid** [comment]
Please ask on the forums, we keep this repo for bug reporting only. Moreover I strongly recommend that you upgrade to the latest 5.3 release, down the road we've introduced many fixes to the core.
