### ISSUE TITLE
Where query if JSON name have dashes

### ISSUE THREAD

**Issue by sebestenyb** [laravel/framework#16307]
- Laravel Version: 5.3.22
- PHP Version: 7.0.8
- Database Driver & Version: MySQL 5.7

### Description:
If the name fields in a JSON field have dash in it, for example
```json
{"cache-size": 5}
```
then Eloquent can't find it:
```php
dd(PanelField::where('value->cache-size', 5)->get());
```

```
Collection {#421 ▼
  #items: []
}
```

According to the MySql documentation: 

> Names of keys must be double-quoted strings or valid ECMAScript identifiers (see http://www.ecma-international.org/ecma-262/5.1/#sec-7.6)

But if I try that:

```php
dd(PanelField::where('value->"cache-size"', 5)->get());
```

Eloquent generates an incorrect query:

```
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'cache-size"" = ?' at line 1 (SQL: select * from `panel_fields` where `value`->"$."cache-size"" = 5)
```

As far as I understand, the reason is:

[MySqlGrammar](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Query/Grammars/MySqlGrammar.php#L155)

[MySqlGrammar](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Query/Grammars/MySqlGrammar.php#L245)

If I swap around the single and double quotes, it seems to work:

```php
 -       return $field.'->'.'"$.'.implode('.', $path).'"';
 +       return $field.'->'."'$.".implode('.', $path)."'";
```

Cheers, Sebi

**Comment by themsaid** [comment]
Thank you for reporting this, a PR was opened to fix the issue: https://github.com/laravel/framework/pull/16308
