### ISSUE TITLE
[5.3.X] Issue with big integer and json_encoding/response()->json()

### ISSUE THREAD

**Issue by darkgoldblade01** [laravel/framework#16304]
- Laravel Version: 5.3.x
- PHP Version: 5.x and 7.x
- Database Driver & Version: MySQL

### Description:

When using integers that are larger than 9,007,199,254,740,992 (the largest allowed integer in JS), `response()->json($response);` gives back incorrect numbers.

### Steps To Reproduce:

Table: Test with id, name, int

`Test::create(['name' => 'test1', 'int' => 23842515550750742]);`

new route with:
`return response()->json(Test::find(1));`, and view it in a browser, for whatever reason it changes to 23842515550750744. It does this with all numbers larger than 9,007,199,254,740,992. 

This creates an issue for people like me, where we are tied into Facebook's system, and their IDs are even larger than this one.

**Comment by sisve** [comment]
This can be reproduced in Chrome's javascript console by just pasting "23842515550750742" into it, and seeing "23842515550750744" returned. This looks like you've been hit with the Floating Point Monster. The problem seems to me that you're treating Facebook's identifiers as numbers instead of opaque strings.

Interesting read: https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html

**Comment by themsaid** [comment]
Yes consider a facebook ID as string not a number, this will solve your issue. Please continue on the forums since it's not a laravel related bug report :)

**Comment by childeYin** [comment]
I have this problem too, and I solved it by change big integer to string type; thanks

**Comment by phpboyza** [comment]
I don't know if this has been resolved in Laravel.
If you have BIGINT in your DB and you're returning it in JSON from your Controller then you need to use the JSON_BIGINT_AS_STRING option in json_encode... I don't think you can do this directly in Laravel so you'll have to json_encode it manually and return the data from your controller.
e.g.

return json_encode($data,JSON_BIGINT_AS_STRING);
