### ISSUE TITLE
Laravel 5.1 Access to session data from AppServiceProvider

### ISSUE THREAD

**Issue by taviroquai** [laravel/framework#16316]
- Laravel Version: 5.1
- PHP Version: 5.5.9

### Description:
Following the discussion in here https://laracasts.com/discuss/channels/laravel/set-default-database-connection-before-bind-model-on-routes

I could only set default database connection dynamically before any model is loaded, using DB::setDefaultConnection on AppServiceProvider::boot.

Although, I also need to access the session, ie. user A connects to database A, user B connects to database B.

In AppServiceProvider I don't have access to session data(?).

Questions:
1. Is there a way to set default database dynamically, before any model is loaded AND access to session data?
2. Is there another way of doing this?

Thanks!

**Comment by GrahamCampbell** [comment]
Please ask on the forums.
