### ISSUE TITLE
Laravel 5.3 request->file()->store() resets mime types for S3 storage

### ISSUE THREAD

**Issue by aleemb** [laravel/framework#16319]
- Laravel Version: 5.3
- PHP Version: 5.6

### Description:

I am trying to store a file via `request()->file(...)->store(...)` which shows up in S3 with `Content-Type` as `application/octet-stream`. The workaround is having to do `Storage::disk('S3')->getDriver()->put(..., ..., ['ContentType': $mime])`

Life would be much easier if `store()` passed along the mime type which are already available in the `UploadedFile` object.

**Comment by srmklive** [comment]
@aleemb this is the default behavior. You need to specify custom mime type on your own.

**Comment by sisve** [comment]
@srmklive How are we supposed to do that? Should we always use `Storage::disk($disk)->getDriver()->put(...)` instead of `Storage::disk($disk)->put(...)` in case in case $disk changes (like the difference between development and production)?

**Comment by GrahamCampbell** [comment]
Please ask on the forums.

**Comment by srmklive** [comment]
@sisve I use [s3cmd](http://s3tools.org/s3cmd) tool to uploading content to Amazon S3. As the AWS PHP SDK will cause timeout issues when you are uploading large files over 100MB in size. What i do is upload the file on a local folder, and have the s3cmd tool automatically upload it on S3 instantly through this command:

```
/usr/local/bin/s3cmd put --acl-private --verbose --guess-mime-type /path/to/file s3://s3-bucket/file
```

**Comment by aleemb** [comment]
@taylorotwell thoughts on this?

I suspect nearly every use case will require setting the mime type so why not just set it by default, especially since that info is readily available and the ground work is already done.

It doesn't make any sense to `store()` everything as a `octet-stream` by default. It also doesn't make sense to force users to go the `getDriver()` route which is cumbersome.

**Comment by jodiedunlop** [comment]
@aleemb just noticed your issue, i did submit a PR for this addition: #16416

**Comment by micropulp** [comment]
@jodiedunlop that should make things super convenient with the `true` option. Thank you!

**Comment by aleemb** [comment]
@jodiedunlop that should make things super convenient with the true option. Thank you!
