### ISSUE TITLE
Auth keeps all users logged in after password change

### ISSUE THREAD

**Issue by donnysim** [laravel/framework#16311]
Let's say someone saw my password and logged in, strange activity starts happening, I changed my password, strange activity continues to happen because the culprit is still logged in. Then he changes the password, I use password reset form, strange activity continues to happen - he's still logged in.

This is considered a security issue, no? especially if someone get to know admin panels password

**Comment by donnysim** [comment]
The only way to make that user logout is to delete the database entry. BUT if you create an entry with the same ID, it can contain other email/password, does not matter - the culprit will be logged in again.

**Comment by hulkur** [comment]
Delete all sessions with this user id.

**Comment by donnysim** [comment]
And how do you do that? I have no control over the sessions.

**Comment by RomainLanz** [comment]
Hey @donnysim !

It's up to you to decide if you want to logout the user when the password is changed.
You only need to add `auth()->logout()` after patching your user.

**Comment by donnysim** [comment]
The problem is not loggin out the current user, but the UNKNOWN user that is logged in with the current account.

**Comment by donnysim** [comment]
Even wordpress has fixed this issue from v3 :|

**Comment by RomainLanz** [comment]
Oh you're right!

It should exists something like `auth()->logoutAll()` to logout all user using the current account.

**Comment by themsaid** [comment]
How would laravel know the `current account` to log it out? I think this is something to be handled in every app based on the use case.

**Comment by donnysim** [comment]
Shouldn't it at least store a hash of email and password in session, and on session login check if they were changed? If they were, your session is invalid?

**Comment by themsaid** [comment]
This behaviour might not be desired in all applications afaik.

**Comment by donnysim** [comment]
But this poses a security problem afaik :\ if at least an options is added to enable this behavior, I won't mind.

**Comment by donnysim** [comment]
Let's put it this way, you have a paid service, you give your friend your password for one day and say check it out, then change your password, thinking that he doesn't have access anymore, but in reality he has a lifetime access until you delete your account or sessions is cleared. We wouldn't want that now, would we.

**Comment by srmklive** [comment]
@donnysim as @themsaid pointed out this is something that needs to be handled on case-by-case basis. The case you are describing is something you need to handle on your own.

**Comment by donnysim** [comment]
@srmklive then please state this in the documentation with big red letters that this is the case.

**Comment by taylorotwell** [comment]
You can do this using the database session driver since you can query for all sessions by user_id and log out that user across all sessions.

**Comment by donnysim** [comment]
@taylorotwell how does the guard handle session restore? does it call any event I can catch to handle this case?

**Comment by donnysim** [comment]
Nwm, found one, `Events\Authenticated`

**Comment by donnysim** [comment]
If it's not held as security issue then you can close it.

**Comment by themsaid** [comment]
Actually I'll be looking into the matter today, hopefully come up with a PR if things look clean enough.

**Comment by taylorotwell** [comment]
I think it’s worth fixing. @themsaid is looking into it today.

**Comment by themsaid** [comment]
Moving the discussion to the PR https://github.com/laravel/framework/pull/16323

**Comment by srmklive** [comment]
@donnysim As i said before, the use case you are mentioning can be handled on your own. For this you may need to create a custom auth guard which implements all the functionality you are looking for. Glad that such feature is being considered to be implemented in 5.4

**Comment by themsaid** [comment]
A new Middleware was added to 5.3 `\Illuminate\Session\Middleware\AuthenticateSession` that should handle this functionality, it works by setting a `password_hash`  session key on user authentication and checks for its existence in all future requests.

**Comment by thewebartisan7** [comment]
I have uncommented the middleware in web group, ` \Illuminate\Session\Middleware\AuthenticateSession::class`and logoutOthersDevices()  works fine after enabling this.

However since I am using multi guard, if I try to login with second guard, then first guard get log-out by this middeware.

Checking the middleare handle() method I see that I was loggout here:

```
        if ($request->session()->get('password_hash') !== $request->user()->getAuthPassword()) {
            $this->logout($request);
        }
```

How to make this new middleware in multi guard scenario? I am not sure how to handle this.

Thanks

**Comment by djurovicigoor** [comment]
@thewebartisan7 Did you find a proper way to handle a multi guard scenario?

**Comment by thewebartisan7** [comment]
No sorry. And as I understand there is not a way.
I simple stop use multi auth time ago as it introduce too much complexity, and now handle via roles and permissions everything.

Cao
