### ISSUE TITLE
the laravel not access in nginx

### ISSUE THREAD

**Issue by rdluck** [laravel/framework#16314]
- Laravel Version: #5.#5.#
- PHP Version:5.6.23
- Database Driver & Version:
mysql 5.6
### Description:
in the nginx,To configure for：

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;
    server {
            listen       80;
            server_name  yuming.com;

            **location / {
                root   /usr/local/nginx/html/laravel/public/;
                try_files $uri $uri/ /index.php?$query_string;
            }**

            location ~ \.php$ {
                   root   /usr/local/nginx/html/laravel/public/;
                   fastcgi_pass   127.0.0.1:9000;
                   fastcgi_index  index.php;
                   fastcgi_param  SCRIPT_FILENAME  $document_root/$fastcgi_script_name;
                   include        fastcgi_params;
            }
        }
}

access have no problem.
but when To configure for:
http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;
    server {
            listen       80;
            server_name  yuming.com;

            **location /juweb/ {
                root   /usr/local/nginx/html/laravel/public/;
                try_files $uri $uri/ /index.php?$query_string;
            }**

            location ~ \.php$ {
                   root   /usr/local/nginx/html/laravel/public/;
                   fastcgi_pass   127.0.0.1:9000;
                   fastcgi_index  index.php;
                   fastcgi_param  SCRIPT_FILENAME  $document_root/$fastcgi_script_name;
                   include        fastcgi_params;
            }
        }
}
access 404 NotFoundHttpException in RouteCollection.php line 161:

**Comment by themsaid** [comment]
please use the forums to post questions, we try to keep this repo for bug reporting only.
