### ISSUE TITLE
DB Notifications dont delete on user delete

### ISSUE THREAD

**Issue by arctic-ice-cool** [laravel/framework#16321]
- Laravel Version: 5.3.21
- PHP Version: Any
- Database Driver & Version: Any

### Description:
Not sure if this is a bug, or something you'd expect users to implement themselves, but on delete of a notifiable user, the notifications don't delete. I appreciate this can't be a simple cascade delete as there are different notifiable types.

### Steps To Reproduce:
Create user migration,
Make 'user' notifiable,
Send DB notification to user
Delete user
DB notification remains

**Comment by arctic-ice-cool** [comment]
For any users wanting to resolve this quickly BTW, just place this in your EventServiceProvider.php boot() method:

```
        User::deleting(function ($user) {
            return $user->notifications()->delete();
        });
```

**Comment by themsaid** [comment]
yes this is something you need to handle on your own :)

**Comment by arctic-ice-cool** [comment]
Fair enough, maybe worth sticking the above example in the notifications comments? As it is something I only thought about nearing entering production :)

**Comment by themsaid** [comment]
Not sure if that belongs to the docs honstly :)
