### ISSUE TITLE
Pass @each an array of data

### ISSUE THREAD

**Issue by jbrooksuk** [laravel/framework#16324]
How about adding another parameter to `@each` which allows us to pass an array of include data, similar to `@include`.

A use case for this would be including a partial, but needing an extra condition within it, which may not usually occur.

**Comment by themsaid** [comment]
Check this issue: https://github.com/laravel/framework/issues/13090

> Have been discussing the matter with Taylor, passing a fifth argument to @each seems too much, and allowing each to inherit variables from the parent view looks very complicated.

**Comment by jbrooksuk** [comment]
What about if Blade tags could be chained? 👀 🙈 

It's a shame that `@each` doesn't quite reach a real-world use case.

**Comment by themsaid** [comment]
Well feel free to PR, but from what I can see 5 arguments is considered too much :)
