### ISSUE TITLE
Routing slug error

### ISSUE THREAD

**Issue by KonstantinFilin** [laravel/framework#16326]
- Laravel Version: 5.2.45
- PHP Version: 5.6.18-pl0-gentoo
- Database Driver & Version: mysqli + libmysql - 5.6.28-76.1
- Database column charset:  	utf8_unicode_ci 	

### Description:
My website have a product with name "RDA-125-15/30/45m³/h CAV" and it is has autoproduced slug 
<a href="/good/rda-125-153045m³h-cav">RDA-125-15/30/45m³/h CAV</a> (from name)

When click this link server answers with error 404 - this product 

In hex codes it looks like this (test string):
![screenshot-3](https://cloud.githubusercontent.com/assets/2811794/20113390/b8a860d8-a609-11e6-89dd-a15b06bee09e.png)

1) number 3 (code 33)
2) the bug symbol ³ (code C2 B3)
3) number 3 again (code 33)
4) Ending 0A

(UTF-8 charset)

### Steps To Reproduce:

To create an item with slug "rda-125-153045m³h-cav" and try to find it by Laravel default routing engine

**Comment by themsaid** [comment]
This is a problem with the plugin you use?

**Comment by KonstantinFilin** [comment]
There are two problems
1) Slug generation (it is a problem of a slug generation program and there is a number of such a libraries) - I don't know about slug restrictions, but it must be previously defined range of characters and all libraries must played by one score or something like this

2) Slug search in existing records (and there are slugs created in a different ways - maybe somebody just print it by hands) - all ways must be handled correctly - handled by routing engine

I don't know the correct answer, just asking the question, but see it this way

**Comment by themsaid** [comment]
I don't think this is laravel related, check the query generated by the plugin.

**Comment by KonstantinFilin** [comment]
Lets pretend we have a situation, when a project has: 
1) Route ("/{slug}")
2) An item with slug "abc"
3) Query "/abc"

So it must work, because "abc" == "abc"

And if there are situation, when 
a) item with slug "ab*z"
b) query "ab*z"

Where * is any symbol in both cases

And now we have a situation where "ab*z" != "ab*z" in some cases, or "*" != "*".

This is not the case how this symbol went to the database - we don't believe the data.
We can have this situation for example
1) Database seed ($item->slug = "ab*z")
2) Manually through the dbms
3) Mistake in slug forming library (there are a number of libraries and functions)
4) other ways

**Comment by themsaid** [comment]
Can you please share the query used by the package :) It is the kernel of the issue.

**Comment by KonstantinFilin** [comment]
Don't quite understand what query do you mean. Slightly changed previous comment - some symbols were missed.
