### ISSUE TITLE
/api/user redirection issue

### ISSUE THREAD

**Issue by prabhashkutti** [laravel/framework#16335]
- Laravel Version: 5.3.*
- PHP Version:  7
- Database Driver & Version:

### Description:
When I hit **/api/user** it is responding correctly with correct personal access token. But if I give wrong personal access token, it gets redirected to login page in the browser and postman client. It should give Unauthorised access error

### Steps To Reproduce:
1. Installed fresh latest laravel
2. Followed the passport doc steps
3. Create personal access token
3. Hit the **/api/user** endpoint with wrong personal access token

**Comment by themsaid** [comment]
You need to have the `Accept: application/json` set on the request for Laravel to know that the request expects a JSON response.
