### ISSUE TITLE
.vtt format validation & storage error

### ISSUE THREAD

**Issue by khaninejad** [laravel/framework#16332]
- Laravel Version: 5.3.0
- PHP Version: 5.6
- Database Driver & Version:

### Description:
Hi,

I want to upload .vtt format using Laravel Storage facade.
with validation, I can't do this because Laravel couldn't recognize .vtt format.
without validation, it is uploaded but extension changed to .txt
https://www.w3.org/TR/webvtt1/

**Comment by GrahamCampbell** [comment]
Laravel itself doesn't deal with filetype detection. Please report this upstream.

**Comment by barryvdh** [comment]
Upstream would be https://github.com/symfony/symfony

**Comment by khaninejad** [comment]
I tried to report a bug, and i don't want to waste my time to figure out laravel issue tracking system.
it's not related to symfony.
Validation & Storage are Laravel components.
Thank you :)

**Comment by barryvdh** [comment]
Laravel uses the UploadFile from Symfony to guess the extension (http://api.symfony.com/2.3/Symfony/Component/HttpFoundation/File/UploadedFile.html)
That uses the MimeType guesser I think: https://github.com/symfony/symfony/blob/3.1/src/Symfony/Component/HttpFoundation/File/MimeType/MimeTypeExtensionGuesser.php

So yes, Laravel uses this, but the guessing of the extension is done by Symfony

**Comment by khaninejad** [comment]
OK, I will report to Symfony
