### ISSUE TITLE
Collection object can not cast to array.

### ISSUE THREAD

**Issue by yaquawa** [laravel/framework#16343]
- Laravel Version: 5.3.22
- PHP Version: 7.0.12
- Database Driver & Version: mysql 5.6

### Description:
`\Illuminate\Support\Collection` object can not **cast to array**.
Please consider extending the `ArrayObject` class, that will solve this problem.

### Steps To Reproduce:
```php
$collection = new \Illuminate\Support\Collection ([1,2,3]);
dd( (array) $collection ); // this won't give me `[1,2,3]`
```

**Comment by TsvetomirCh** [comment]
$collection = new \Illuminate\Support\Collection ([1,2,3]);
dd($collection->toArray());

**Comment by yaquawa** [comment]
@TsvetomirCh 

Yes, I understand I could get the array by calling the `all` or `toArray`.
But it would be nice to have the ability to cast to array.

**Comment by shadoWalker89** [comment]
From php docs

> If an object is converted to an array, the result is an array whose elements are the object's properties.

http://www.php.net/manual/en/language.types.array.php#language.types.array.casting

**Comment by themsaid** [comment]
Yes it'll be something like:

```
[
     "items" => [
       1,
       2,
       3,
     ],
   ]
```

**Comment by yaquawa** [comment]
@shadoWalker89

Ok... Looks like the current implementation is the right way to do it.
But you can cast an object to an array by extending the `ArrayObject` class.
What's the best solution do you guys think?
