### ISSUE TITLE
Homestead - SSL: Connection reset by peer

### ISSUE THREAD

**Issue by eggnaube** [laravel/framework#16347]
Homestead V3

We have an application using reCAPTCHA, the application works without problems on the production environment, but on Homestead machine, I get the following error:

    file_get_contents(): SSL: Connection reset by peer

I also have troubles using composer, there I get the following error:

    [ErrorException]
    zlib_decode(): data error

I think both errors are related to SSL.

Do I miss something, do I have to configure the CACERTS by hand? Or is there a problem with the Vagrant box?

**Comment by themsaid** [comment]
Please use the forums to post questions, we try to keep this repo for bug reporting only :)

**Comment by eggnaube** [comment]
Yes I agree. It is a bug related to VirtualBox as mentioned [here](https://github.com/mitchellh/vagrant/issues/7946).

After a downgrade of VirtualBox, the problem was solved.
