### ISSUE TITLE
Database DateTime binding - incorrect timezone

### ISSUE THREAD

**Issue by mod3st** [laravel/framework#16356]
- Laravel Version: 5.*

This is a expanding of #15122 issue.

In short - binding Carbon (DateTime) objects into DB query causes parsing dates without DB timezone conversion.
I think this is not only a problem of Eloquent's dates, but also the database query bindings builder.

Ex:
We have an app, DB with UTC timezone as a deafult.

Binding `Carbon::parse('2015-01-01T12:00:00+0300')` will be parsed by the query builder as `2015-01-01 12:00:00` instead of `2015-01-01 09:00:00` .
I think, if `Connection` allows us to bind `Carbon` objects into the query, it should ensure their proper, coherent form while saving to the DB.

We can set a default timezone for our database (connection config):

`Illuminate\Database\Connectors\MySqlConnector::connect`
```
        if (isset($config['timezone'])) {
            $connection->prepare(
                'set time_zone="'.$config['timezone'].'"'
            )->execute();
        }
```

Maybe the default timezone for all connections should be `app.timezone` (if not specified)?

The problem is, `Illuminate\Database\Connection::prepareBindings` does not include timezone when parsing `DateTimeInterface` object:

```
            if ($value instanceof DateTimeInterface) {
                $bindings[$key] = $value->format($grammar->getDateFormat());
            }
```
So binding `Carbon` objects with different timezones will cause saving incorrect dates.

I think the general solution would be something like:
```
if ($value instanceof DateTimeInterface) {
    if (isset($config['timezone'])) {
        $value->setTimezone(new DateTimeZone($config['timezone']));
    }
    $bindings[$key] = $value->format($grammar->getDateFormat());
}
```

**Comment by GrahamCampbell** [comment]
Feel free to send a PR and we can discuss it there. Thanks for looking into this. :)

**Comment by danvim** [comment]
I just encountered this issue today. I am in awe of this inconsistency. Especially when an application may use `$table->timestampTz()` in specifying a Postgres `timestamp(0) with time zone`. It is quite frustrating to need to normalize the time zones before binding the `Carbon` instance to a query.
