### ISSUE TITLE
PDO::prepare(): MySQL server has gone away

### ISSUE THREAD

**Issue by wanfeiyy** [laravel/framework#16357]
- Laravel Version: 5.1
- PHP Version:5.6
- Database Driver & Version:mysql5.7

### Description:
when create mysql connetion driver,error with PDO::prepare(): MySQL server has gone away 
strace:$connection->prepare("set session sql_mode=''")->execute();

**Comment by GrahamCampbell** [comment]
Please upgrade to the latest version of 5.1 and confirm this is still broken.

**Comment by GrahamCampbell** [comment]
If it is, please provide the exact error message you get.

**Comment by themsaid** [comment]
ping @wanfeiyy
