### ISSUE TITLE
SES Transport not firing sendPerformed, and not getting MessageID

### ISSUE THREAD

**Issue by jdavidbakr** [laravel/framework#16364]
- Laravel Version: 5.3.10
- PHP Version: 7.0
- Database Driver & Version: N/A

### Description:
I have a package jdavidbakr/mail-tracker that uses a Swift plugin to record sent emails in the database and inject tracking data for opens and cilcks.  I use the beforeSendPerformed() call in the plugin to modify the message body.  This has worked great, but I want to extend it to be able to receive messages from Amazon's SES about the delivery of the messages.  In order to do this, I need to get the Message-ID from the message after it's been sent to SES because that is the only identifier I have available to me at the point of the webhook.

The problem in 2-fold: first, I wanted to add a sendPerformed() call to my Swift plugin.  However, this is not called by the SesTransport.  Second, the SesTransport is not storing the Message-ID from AWS anywhere to allow me to retrieve it.

**Comment by GrahamCampbell** [comment]
Thanks. :)
