### ISSUE TITLE
Variables persists when testing

### ISSUE THREAD

**Issue by shadoWalker89** [laravel/framework#16362]
- Laravel Version: 5.3.22
- PHP Version: 5.6.15

### Description:
Controller
```php
class StudentTheseRequestController
{
	protected $user;

	public function __construct()
	{
        $this->middleware(function ($request, $next) {
            $this->user = auth()->user();

            return $next($request);
        });
	}

	public function create()
	{
		//Show the form
	}

	public function store()
	{
		//Store in the database

		return redirect()->route('these-request.show');
	}

	public function show()
	{
		$deposit = $this->user->student->theseRequest;
	}
}
```

When i write a test like this

```php
$this->be($student->user);

$this->visitRoute('these-request.create');

//Fill form and presse submit

$this->seeInDatabase('these_requests', [
    'student_id' => $student->id
    ...
]);

$this->seeRouteIs('these-request.show');

// Some other assertions like: see the subject of his submission ...
```

When manually from the browser everything works fine.
When i run the test from command line, i keep getting `null` for the variable `$this->user->student->theseRequest` but if i change it with `$this->user->student->theseRequest()->first()` the test pass.

What is happening is that the `$user` attribute in the controller is the same. But as you can see the test has three requests.
One for showing the form (create method)
One for submitting the form (store method)
One for showing the submitted data (show method)

**Comment by themsaid** [comment]
all models on the same connection?

**Comment by shadoWalker89** [comment]
Yes.

Also i if i do `$user->name = 'bar'` without saving the user Model in the `store()` of the controller and then do `dd($user->name)` in the `show()` method, i get the value `bar`

BTW the `seeInDatabase()` in the test pass.
The problem isn't in the data not being saved in the database, but in the Models not refreshing.

**Comment by KarimGeiger** [comment]
Yes, I can confirm this. I'd expect the controller to be re-built on each request, but it stays the same object. I've build a test case for it:

Let the controller return its object hash:
https://github.com/KarimGeiger/LaravelTestCase16362/blob/master/app/Http/Controllers/Controller.php

And then call it twice and expect the hashes to differ:
https://github.com/KarimGeiger/LaravelTestCase16362/blob/master/tests/ExampleTest.php

The result will be:

```
$ phpunit
PHPUnit 5.1.0 by Sebastian Bergmann and contributors.

F                                                                   1 / 1 (100%)

Time: 209 ms, Memory: 16.00Mb

There was 1 failure:

1) ExampleTest::testBasicExample
Failed asserting that '0000000035c79906000000002e0bb7c1' is not equal to <string:0000000035c79906000000002e0bb7c1>.

tests/ExampleTest.php:26

FAILURES!
Tests: 1, Assertions: 3, Failures: 1.
```

Feel free to [clone this repository](https://github.com/KarimGeiger/LaravelTestCase16362).

**Comment by GrahamCampbell** [comment]
I think this is the expected behaviour. Perhaps ask on the forums. There are some subtleties with sending more than one request in the same test method.

**Comment by shadoWalker89** [comment]
@GrahamCampbell How is this expected behavior ? 
Do you really think that variables should persist on different requests ?

**Comment by KarimGeiger** [comment]
Yes, why should this be expected behaviour? In my opinion, tests should try to simulate the real world as good as possible. This doesn't even remotely simulate it as in the real world, a controller will always be different across requests.

For everyone having the same issue: A workaround - although ugly - would be, in your TestCase class. `makeRequest` will be called by the `InteractsWithPages` trait when calling `get`, `visit`, etc.

```php
    use InteractsWithPages {
        makeRequest as traitMakeRequest;
    }

    protected function makeRequest($method, $uri, $parameters = [], $cookies = [], $files = [])
    {
        if ($currentRoute = Route::getCurrentRoute()) {
            // Looks like this is the second request, as a current route was defined.
            // Go ahead and reset the 'controller' attribute on this route. Now it has to be recreated.
            $reflection = new ReflectionClass($currentRoute);
            $property = $reflection->getProperty('controller');
            $property->setAccessible(true);
            $property->setValue($currentRoute, null);
        }

        // Pass the original call to the original trait method and run the request.
        return $this->traitMakeRequest($method, $uri, $parameters, $cookies, $files);
    }
```

**Comment by shadoWalker89** [comment]
@KarimGeiger Your solution is nice when it comes to visiting the same controller twice, but for me as you can see in my examples i don't visit the same route twice, and still i have the problem.

What i think is causing the problem is the Kernel 
https://github.com/laravel/framework/blob/0a9e23a2bfb5028c79b6ff26e89fc8b783b33c8a/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php#L569

The Kernel is bound as a singleton in the container.
What should really happen is that for each request, we get new fresh instance of the Kernel.
