### ISSUE TITLE
Symfony\Component\Finder\Iterator\FileTypeFilterIterator contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (FilterIterator::arcfour) in \vendor\symfony\finder\Iterator\FileTypeFilterIterator.php on line 19

### ISSUE THREAD

**Issue by mimrank** [laravel/framework#16361]
- Laravel Version: 5.3
- PHP Version: 7
- Database Driver & Version:
Hi, Today i face some issue in laravel core code, my product not run its showing this error Fatal error: Class Symfony\Component\Finder\Iterator\FileTypeFilterIterator contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (FilterIterator::arcfour) in \vendor\symfony\finder\Iterator\FileTypeFilterIterator.php on line 19

Any soultion for it and why this happend? i update composer but issue still exist.:

**Comment by themsaid** [comment]
Please use the forums to post questions, we try to keep this repo for bug reporting only.

**Comment by yousafsyed** [comment]
I am getting the exact same error with following

* Laravel Version: 5.1
* PHP Version: 7

PHP Fatal error:  Class Symfony\\Component\\Finder\\Iterator\\PathFilterIterator contains 1 abstract method and must, therefore, be declared abstract or implement the remaining methods 

@themsaid If you are saying that this is not a bug please explain why it's not a bug? 

In my case problem resolves by simply restarting the Apache server.

**Comment by AdeelBaloch** [comment]
Dear Yousafsyed 
Thank you very much for help my problem solved

**Comment by mmubasharsheikh** [comment]
@yousafsyed Thankyou. It really helped me out.
