### ISSUE TITLE
Blade @include generates users table query for no apparent reason

### ISSUE THREAD

**Issue by sunnyjayjay** [laravel/framework#16378]
- Laravel Version: 5.3
- PHP Version: 7.0
- Database Driver & Version: Maria DB 10.1.9

### Description:
A Blade file in my app (index.blade.php) calls several partials (mostly modals) using @include. These are simple partials with no db calls or even references to model variables. And yet each one triggers a select * from users where id=x limit 1 query. 

One example is alert.blade.php and I show it here.

```
<div class="modal fade" id="{{ $modal_id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">@lang('headings.info'):</h4>
            </div>
            <div class="modal-body">
                {{ $message }}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">OK</button>
            </div>
        </div>
    </div>
</div>
```
This is resulting in a huge number of additional and unnecessary queries. Any ideas why this might be happening?

**Comment by arrilot** [comment]
Most likely there is a badly written view composer or view creator somewhere in your app or any of 3rd party packages
https://laravel.com/docs/5.3/views

**Comment by sunnyjayjay** [comment]
My app only has two view composers and when I disable them it makes no difference to this problem. Have you any idea where I could start looking to find where this problem might be coming from?

**Comment by themsaid** [comment]
Please continue on the forums, we're trying to keep this repo for bug reporting only :)

I'm sure you'll find more answers there.
