### ISSUE TITLE
Collection::map

### ISSUE THREAD

**Issue by dukhanin** [laravel/framework#16376]
- Laravel Version: 5.3.4
- PHP Version: 7.0.6

### Description:

Invalid array handling with Collection->map() method:

The problem is in third argument $keys for array_map() function. It works as supposed to when i remove $keys argument. 

Actually i cant understand why $keys argument is set there for.

Illuminate/Support/Collection.php
```
public function map(callable $callback)
{
    $keys = array_keys($this->items);

    $items = array_map($callback, $this->items, **$keys**);

    return new static(array_combine($keys, $items));
}
```

### Steps To Reproduce:

```
$stringItems = collect( ['6', '7'] );

$integerItems = $stringItems->map('intval');

print_r($integerItems); // object( ... Array([0] => 6, [1] => 0) )

// expecting object( ... Array([0] => 6, [1] => 7) )


```

**Comment by bmitch** [comment]
I _think_ it is there because the $callback provided may contain 2 parameters:

```
$data = collect(['foo' => 'bar']);
$data = $data->map(function ($item, $key) {
    return $key .' '. $item;
});
```

So without the $keys as the 3rd parameter to the `array_map` call the above would not work.

**Comment by bmitch** [comment]
@dukhanin if you are willing, I believe you could change your code to:
```
$integerItems = $stringItems->map(function ($item, $key) {
    return intval($item);
});
```

and get your desired result.

If there is a requirement for the $callback provided to map() to have 2 parameters perhaps a note in the documentation should be added if not already there. But I am not sure if that is a requirement or if you've discovered a bug. I'd be happy to provide a pull request for this documentation change if needed.
