### ISSUE TITLE
getForeignKey on Model does not depend on Primary Key

### ISSUE THREAD

**Issue by ElMatella** [laravel/framework#16370]
- Laravel Version: 5.3.20
- PHP Version: 7.0

### Description:

When setting the primary key on a model like that:

```
class Category extends Model
{
	protected $primaryKey = 'hash';
}
```

And then calling the `getForeignKey()` method still returns `category_id`. For the moment, the method is implemented like that:

```
public function getForeignKey()
{
    return Str::snake(class_basename($this)).'_id';
}
```

My proposition would just to make:

```
public function getForeignKey()
{
    return Str::snake(class_basename($this)).'_' . $this->primaryKey;
}
```

Is their a particular reason the foreign key does not depend on the primary one? 

If not, I would be very happy to make a pull request...

**Comment by ntzm** [comment]
Makes sense to me! Can imagine this would break a few builds though

**Comment by srmklive** [comment]
@ElMatella Added the PR for this.

**Comment by themsaid** [comment]
Moving the discussion to the PR.
