### ISSUE TITLE
Incorrect config/broadcasting.php should produce errors

### ISSUE THREAD

**Issue by scottgrayson** [laravel/framework#16379]
- Laravel Version: 5.3.22
- PHP Version: 7.1
- Database Driver & Version: mysql

### Description: 
I spent a long time trying to figure out why my broadcast events were not being received by pusher. I received no errors laravel.log file.

Solution was i needed `'encrypted' => true` in my options. I'm not sure why i needed this. I did not select any special settings when i signed up for pusher.
```
        'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_KEY'),
            'secret' => env('PUSHER_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'encrypted' => true,
            ],
        ],
```
Is it possible for Laravel to log errors when it fails to connect to pusher? When i was searching for solutions, I saw that others have also had a similar problem (not connecting, no errors). Most of them needed to specify the `cluster` option and did not realize it.

**Comment by scottgrayson** [comment]
This might have to do with why i needed `'encrypted' => true`. I am using valet with this php SSL config
`php -i | grep "SSL Version"` 
returns
`SSL Version => OpenSSL/1.0.2j`

I had a friend run the same code on his machine with valet and `SSL Version => SecureTransport`

Irregardless, it would help to see errors if the connection to the broadcast provider fails

**Comment by themsaid** [comment]
A PR was submitted that should handle this situation https://github.com/laravel/framework/pull/16398
