### ISSUE TITLE
.htaccess | rewriteRule - Everything worked before on godaddy.com web hosting! 

### ISSUE THREAD

**Issue by lyfe1337** [laravel/framework#16388]
- Laravel Version: #.#.# Unable to locate
- PHP Version: 7
- Database Driver & Version:

### Description:
Server/Request Data
REDIRECT_STATUS	200
HTTP_HOST	www.anizeo.com
HTTP_USER_AGENT	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0
HTTP_ACCEPT	text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
HTTP_ACCEPT_LANGUAGE	en-US,en;q=0.5
HTTP_ACCEPT_ENCODING	gzip, deflate
HTTP_REFERER	http://www.anizeo.com/account/design
HTTP_COOKIE	laravel_session=eyJpdiI6IjR1Y0gwUFNcL1M2Y0hnaEY2MThpTjJldFdyU1lYclpoeVQwM1JrTjg2RWJFPSIsInZhbHVlIjoiVDBKZFEwS0xReVRwQ0pUeTN2OHNJa1dnWTQ2d0kySE1Bb3BrRlY0bmJqMEdcL3pTSnV1QVJscXVaMHUyYkM1Q0ErUTIxeW5GMTlmOW9VcnhPS3NpQnhRPT0iLCJtYWMiOiJkNzk4YTE2MDg4ZWY0YzZhY2MyOTFmMjE0MDM4MWJlMmM1YWE4YTMzNjg4Njc5ZjVmYzcxNGU0YzRlMzRlOTE3In0%3D; PHPSESSID=4gm17gm5vadtckplk81h7bc1r5
HTTP_CONNECTION	keep-alive
CONTENT_TYPE	multipart/form-data; boundary=---------------------------2091151999705
CONTENT_LENGTH	120972
PATH	/sbin:/usr/sbin:/bin:/usr/bin
SERVER_SIGNATURE	<address>Apache/2.2.15 (CentOS) DAV/2 Server at www.anizeo.com Port 80</address>
SERVER_SOFTWARE	Apache/2.2.15 (CentOS) DAV/2
SERVER_NAME	www.anizeo.com
SERVER_ADDR	66.172.11.142
SERVER_PORT	80
REMOTE_ADDR	196.46.245.132
DOCUMENT_ROOT	/var/zpanel/hostdata/zadmin/public_html/anizeo_com
SERVER_ADMIN	zadmin@localhost
SCRIPT_FILENAME	/var/zpanel/hostdata/zadmin/public_html/anizeo_com/index.php
REMOTE_PORT	2991
REDIRECT_URL	/account/design/bg
GATEWAY_INTERFACE	CGI/1.1
SERVER_PROTOCOL	HTTP/1.1
REQUEST_METHOD	POST
QUERY_STRING	
REQUEST_URI	/account/design/bg
SCRIPT_NAME	/index.php
PHP_SELF	/index.php
REQUEST_TIME_FLOAT	1417975667.868
REQUEST_TIME	1417975667
GET Data
empty
POST Data
val	Array ( [theme] => [type] => profile [bg_image] => [bg_color] => [bg_position] => [bg_attachment] => scroll [bg_repeat] => no-repeat [link_color] => [content_bg_color] => )
current	
Files
image	Array ( [name] => 181137_507005165992850_2047426737_n.jpg [type] => image/jpeg [tmp_name] => /var/zpanel/temp/phpVVmTAT [error] => 0 [size] => 119706 )
Cookies
laravel_session	eyJpdiI6IjR1Y0gwUFNcL1M2Y0hnaEY2MThpTjJldFdyU1lYclpoeVQwM1JrTjg2RWJFPSIsInZhbHVlIjoiVDBKZFEwS0xReVRwQ0pUeTN2OHNJa1dnWTQ2d0kySE1Bb3BrRlY0bmJqMEdcL3pTSnV1QVJscXVaMHUyYkM1Q0ErUTIxeW5GMTlmOW9VcnhPS3NpQnhRPT0iLCJtYWMiOiJkNzk4YTE2MDg4ZWY0YzZhY2MyOTFmMjE0MDM4MWJlMmM1YWE4YTMzNjg4Njc5ZjVmYzcxNGU0YzRlMzRlOTE3In0=
PHPSESSID	4gm17gm5vadtckplk81h7bc1r5
Session
empty
Environment Variables
empty
Registered Handlers
0. Whoops\Handler\PrettyPageHandler

### Steps To Reproduce: ( .htaccess ) on 1&1 Hosting server

#AddType application/x-httpd-php54 .php .htm .html

#IndexIgnore *

<IfModule mod_rewrite.c>
    Options +FollowSymLinks
    
    RewriteEngine On
    
    RewriteBase /
    
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    
    # ORIGINAL CAUSING 500 ERROR
    # RewriteRule ^index\.php$ - [L]
    
    # MODIFIED BY (1&1 TECHSUPPORT) 11/10/2016
    # RewriteRule ^ index.php [L]
    # | Fix worked half way / noticed error uploading images 
    
    # ANOTHER ALTERNATIVE
    # http://stackoverflow.com/questions/5061880/this-is-the-htaccess-code-in-wordpress-can-someone-explain-how-it-works
    # MODIFIED 11/12/2016
    RewriteRule . /index.php [L]
    # | Fix worked half way / noticed error uoloading images 

    # REDIRECT SITE TO HTTPS 
    # MODIFIED 11/11/2016
    RewriteCond %{SERVER_PORT} 80 
    RewriteRule ^(.*)$ https://www.mysite.com/$1 [R,L]
</IfModule>

<IfModule mod_deflate.c>
#AddOutputFilterByType DEFLATE text/text text/html text/plain text/xml text/css application/x-javascript application/javascript
</IfModule>

**Comment by sisve** [comment]
You can find your Laravel version in the composer.lock file. Search for "laravel/framework" and it should be the version-information just next to it.

Regarding this issue; it's a mess. You will have a higher success of getting help if you clear up the formatting. We would also need how to reproduce the exact error ourselves, we will not buy a webhosting package at 1&1 just to see what you are talking about.
