### ISSUE TITLE
Fix "artisan optimize" command for custom setups (v5.2, v5.3)

### ISSUE THREAD

**Issue by dmitrijs** [laravel/framework#16380]
- Laravel Version: 5.3.22

### Description:
Please merge these changes to 5.2/5.3 branch: https://github.com/laravel/framework/pull/10763/files

### Steps To Reproduce:
Run "php artisan optimize" in an environment, where "vendor" directory path is customised.

**Comment by GrahamCampbell** [comment]
Laravel doesn't support custom vendor folders due to the fact there's no use case we can think of. If you really need to do this, then you'd probably need to do the equivalent of editing the framework.
