### ISSUE TITLE
[Laravel API] Missing protected(?) methods from Laravel API.

### ISSUE THREAD

**Issue by Kyslik** [laravel/framework#16383]
- Laravel Version: 5.3.22

### Description:
Why are protected(?) methods missing from API documentation?

Example:

https://laravel.com/api/5.3/Illuminate/Foundation/Auth/AuthenticatesUsers.html
https://github.com/laravel/framework/blob/5.3/src/Illuminate/Foundation/Auth/AuthenticatesUsers.php#L114

`authenticated()` method is clearly empty for one reason only: to let user know that one can influence login flow (after credentials are correct). **Why is it not listed in API Documentation?**

For example I check if user is banned or verified - AFTER credentials are checked so no other person with knowledge of `username()` can get that information.

#16385 might fix this

**Comment by sisve** [comment]
I believe it's the default setting of the api documentation generator ([Sami][1]) to only generate docs for public methods.

[1]: https://github.com/FriendsOfPHP/Sami

**Comment by Kyslik** [comment]
Yes I figured out that fact, and I find it annoying (kind of?).

I use "offline" [API Documentation](http://devdocs.io/laravel~5.3/api/5.3/illuminate/foundation/auth/authenticatesusers) quiet a lot, why is `username()` method visibility set as public but not one I am talking about `authenticated()`.

Please continue on PR #16385.

**Comment by GrahamCampbell** [comment]
Closing since no a bug in framework code.

**Comment by sisve** [comment]
@GrahamCampbell Could you tell us the correct place to report this? The https://github.com/laravel/docs repository seems to be for the manually written docs, and I am unable to find the repository that contains the code for generating the api docs.
