### ISSUE TITLE
updateOrCreate

### ISSUE THREAD

**Issue by mmjjb** [laravel/framework#16387]
- Laravel Version: latest
- PHP Version: 7+

### Description:
When using "updateOrCreate" it returns only "int(1)". 

### Steps To Reproduce:
Console:
```$result = ModelA::updateOrCreate(['name'] => 'test');```

Src:
```   /**
     * Create or update a record matching the attributes, and fill it with values.
     *
     * @param  array  $attributes
     * @param  array  $values
     * @return \Illuminate\Database\Eloquent\Model
     */
    public function updateOrCreate(array $attributes, array $values = [])
    {
        $instance = $this->firstOrNew($attributes);
        $instance->fill($values)->save();
        return $instance;
    }```

**Comment by MannyMannyManny** [comment]
`$result = ModelA::updateOrCreate(['name'] => 'test');`
You have to go this way:
`$result = ModelA::updateOrCreate(['name' => 'test']);`
Work just fine - returning object.
