### ISSUE TITLE
Site fails www to non-www reroute from StopTheWWW

### ISSUE THREAD

**Issue by JtLively** [laravel/framework#16390]
Instructions on site. Not sure how important this is for you.
https://stopthewww.com/

**Comment by JtLively** [comment]
Deos this mean its not important to you?

**Comment by GrahamCampbell** [comment]
It's not really of any relevance to the framework code. If people want www redirecting, it's trival to do, and in real world apps, it probably doesn't happen at the app server level, more likely at the load balancer (or equivalent/higher - eg CloudFlare) level.
