### ISSUE TITLE
artisan make:auth on laravel 5.3.22

### ISSUE THREAD

**Issue by mexcoder** [laravel/framework#16393]
- Laravel Version: 5.3.22
- PHP Version: 5.6.15
- Database Driver & Version: mariaDB 10.1.8-MariaDB 

### Description:
the make:auth artisan command produces a broken login controller, the system can manage register just fine but when trying to log in, it impossible, as you can see in this [SO Post](http://stackoverflow.com/questions/40568717/artisan-makeauth-login-failing) i have done some troubleshooting to no avail, also I tested the same steeps with Laravel 5.2 and it worked right

### Steps To Reproduce:
 1. composer create-project --prefer-dist laravel/laravel blog
 2. cd blog
 3. edit .env to set the database conection
 4. artisan make:auth
 5. artisan migrate
 6. artisan serve
 7. register a new user using the generated `/register` page
 8. log out
 9. try to log in
10. log in will fail with a `These credentials do not match our records.` error

**Comment by KKSzymanowski** [comment]
- Laravel 5.3.22
- PHP 5.6.15
- MariaDB 10.1.9

Couldn't reproduce this issue.
I had a `TokenMismatchException` when tried this with `php artisan serve` but when tested on a classic Apache server it worked fine.

Do you have an entry in your database for the new user? Does the hash match the password?
If you haven't checked, try placing this:
```php
Artisan::command('test', function () {
    dd(Hash::check('secret', \App\User::first()->password));
});
```
in `routes/console.php` file and run `php artisan test`.

Did you try authenticating manually?
```php
public function index(\Illuminate\Contracts\Auth\Guard $auth, \Illuminate\Http\Request $request)
{
    if($auth->attempt(['email' => $request->email, 'password' => $request->password])) {
        return 'Yup';
    }

    return 'Nope';
}
```

**Comment by mexcoder** [comment]
how strange, i just tested again and it worked, first i thought that it was because i was using power shell instead of cmd, but tested it on cmd and it also worked, so i guess is a moon phase bug, anyway i'll make a unit test and come back if ti repeats again

**Comment by KKSzymanowski** [comment]
Probably you just typed the wrong password :)

Besides, PowerShell FTW!

**Comment by mexcoder** [comment]
hi it, just happened again, i have started to think the directory is haunted or something
the only change is that in this moment im conected via a cellsphone hotspot,, il try again at my home to rule this out

**Comment by mexcoder** [comment]
i figured out the problem, i'm an idiot, in the migrations i wrote "Password" instead of "password" (Capital P), sorry for wasting your time
