### ISSUE TITLE
ServerRequestInterface compliant Request classes

### ISSUE THREAD

**Issue by vswarte** [laravel/framework#16397]
- Laravel Version: 5.3.x
- PHP Version: 7.0.8
- Database Driver & Version: Eloquent (PDO MySQL)

### Description:
I have a bunch of request classes for which I need to determine the hostname. Taking a quick glance at the docs reveals that I can typehint ServerRequestInterface and get a PSR-7 compliant object. However it'll throw a fit if I try doing just that with my Request classes.
Simply typehinting the class doesn't work as it obviously doesn't implement the correct interface. However, implementing that interfaces throws an error about some missing methods.

Am I missing something?

### Steps To Reproduce:
Keyboard mash until you get something like:
```php
class XXXFormRequest extends FormRequest implements ServerRequestInterface
{
  // blah
}
```
Receive error:
```
Class App\Http\Requests\XXX\XXXFormRequest contains 27 abstract methods and must therefore be declared abstract or implement the remaining methods (Psr\Http\Message\ServerRequestInterface::getServerParams, Psr\Http\Message\ServerRequestInterface::getCookieParams, Psr\Http\Message\ServerRequestInterface::withCookieParams, ...)
```

**Comment by vswarte** [comment]
I just realized that it's actually the IoC container that turns the Request into a PSR-7 compliant object. However is there any way to "cast" it after the fact? The real issue is that I'm bucketbrigading it down to a different object and try to cast it there.

My bad if questions like these don't belong here :-)..

**Comment by GrahamCampbell** [comment]
Please ask on the forums.
