### ISSUE TITLE
[5.3] nested many to many relationship loading

### ISSUE THREAD

**Issue by PetarDambovaliev** [laravel/framework#16401]
- Laravel Version: 5.3.*
- PHP Version: 7.0
- Database Driver & Version: mysql

### Description:
The query builder returns a inner join with a IN statement with all the ids from many to many relationship.
In my case this results with a IN statement that has 11 thousand ids inside of it.
As you can image that is so slow that crashes.

Is that the way it is suppose to work or am i misusing the ORM?

To me the proper way to do that is a join on the pivot table which the relationship instead of doing a IN statement.

**Comment by themsaid** [comment]
Please as on the forums, we try to keep the repo for bug reporting only :)
