### ISSUE TITLE
FormRequest::setContainer bound to Implementation instead of Interface.

### ISSUE THREAD

**Issue by jgadrow** [laravel/framework#16403]
- Laravel Version: 5.3.15
- PHP Version: N/A
- Database Driver & Version: N/A

### Description:
The Illuminate\Foundation\Http\FormRequest::setContainer() method is bound to the actual Container implementation (Illuminate\Container\Container) rather than to the interface for that implementation (Illuminate\Contracts\Container\Container).

### Steps To Reproduce:
Open up the Illuminate\Foundation\Http\FormRequest class and verify.

**Comment by themsaid** [comment]
And what's wrong about that?

**Comment by GrahamCampbell** [comment]
I don't think @jgadrow meant "bound", rather, actually typehinted to the wrong type perhaps?

**Comment by GrahamCampbell** [comment]
I've not actually checked the code though. If not, then I'd agree this needs more clarification.

**Comment by jgadrow** [comment]
Yes, the method is type-hinted for the specific implementation as opposed to the interface. I ran into this as I was mocking the container interface for unit testing some of my code. Temporarily, I have just changed my testing trait to mock the actual container instance instead, However, I figured this is very likely a simple change that could be made and thought I would report it.

**Comment by jerguslejko** [comment]
@jgadrow this is implemented in `5.4`.
