### ISSUE TITLE
Updating JSON model with sub JSON objects 

### ISSUE THREAD

**Issue by lukepolo** [laravel/framework#16404]
- Laravel Version: v5.3.22
- PHP Version: PHP 7.0.12-1+deb.sury.org~xenial+1 (cli) ( NTS )
- Database Driver & Version: 5.7.13

### Description:
When trying to update a JSON casted column , and using sub JSON objects will produce an error

`{type: "ErrorException", message: "Array to string conversion",…}
file
:
"/home/vagrant/Code/pm/vendor/laravel/framework/src/Illuminate/Support/Str.php"
line
:
289
message
:
"Array to string conversion"
type
:
"ErrorException"`

### Steps To Reproduce:
  ```
// Where `meta->tracking_numbers` are multiple JSON objects 
  $program->update($request->get(['meta->tracking_numbers']));
```

![screen shot 2016-11-14 at 10 37 24 am](https://cloud.githubusercontent.com/assets/2066668/20270764/6b4a3f54-aa56-11e6-9ebc-55adc2c4ab51.png)

**Comment by themsaid** [comment]
You need to do something like:

```
$program->update(['meta->tracking_number' => $request->get('meta->tracking_numbers')]);
```

**Comment by lukepolo** [comment]
Thats what Im doing currently, was hoping there would be an easier way is all

**Comment by lukepolo** [comment]
Is there a specific reason why we shouldn't be allowed todo this ? If not I can look at it tonight after my work hours.

**Comment by themsaid** [comment]
The update method accepts an array of columns with the new values, it's just how it was structured to work :)

**Comment by themsaid** [comment]
We try to keep this repo for bug reporting only, 
For suggestions and feature requests please use the https://github.com/laravel/internals repo.

**Comment by lukepolo** [comment]
@themsaid acutally 

  ```
 $program->update([
            'meta->tracking_numbers' => $request->get('meta->tracking_numbers')
        ]);
```

Fails with the same error above, to do it I have todo 

```
        $meta =$program->meta;
        $meta['tracking_numbers'] = $request->get('meta->tracking_numbers');

        $program->fill([
            'meta' => $meta
        ]);

        $program->save();
```

**Comment by themsaid** [comment]
If you cast this to JSON, does it work?

```
$request->get('meta->tracking_numbers')
```

**Comment by lukepolo** [comment]
Yup, im an idiot , sorry to bother you

**Comment by lukepolo** [comment]
No, it does not , it then gets double encoded , when retrieving from the database then it will no longer be a json object .

![screen shot 2016-11-14 at 11 21 14 am](https://cloud.githubusercontent.com/assets/2066668/20272625/79e70988-aa5c-11e6-9493-b0f170a7a3a4.png)

if done the "long" way, it looks like 

![screen shot 2016-11-14 at 11 21 41 am](https://cloud.githubusercontent.com/assets/2066668/20272639/8724232e-aa5c-11e6-9a76-43f56891e418.png)

**Comment by themsaid** [comment]
Re-opening the issue then, will take a deeper look in a few hours and get back to you :)

**Comment by lukepolo** [comment]
Appreciate it~

**Comment by themsaid** [comment]
The following example works as expected:

```
App\User::find(1)->update([
    'meta->tracking_numbers' => [(object) ['key' => 'value']]
]);
```

Also works if you try to save a JSON string `json_encode([(object) ['key' => 'value']])`.

All this with meta casted to JSON:

```
    protected $casts = [
        'meta' => 'json'
    ];
``

---

Please send steps to reproduce using sample data I can copy and paste into a fresh laravel application.

**Comment by lukepolo** [comment]
I had to upgrade my MySQL version to the newest version from 5.7.13 to 5.7.16

**Comment by liu-yuhuan** [comment]
Laravel Version: v5.3.29
PHP Version: PHP 7.0.8
Database Driver & Version: Mysql 5.7.16

i got a similar problem
when i was trying to update json column then it will occur error message as below
and i don't know how to fix it
detect_photo is JSON column and init value is {"door": {}}
and i do set detect_photo as JSON

```
protected $casts = [
        'detect_photo' => 'json',
];
```

```
DB::table('cars')->where('id', 11)->update(["detect_photo->door" =>  json_encode((object) ['key' => 'value']) ]);
```

SQLSTATE[22018]: Invalid character value for cast specification: 3156 Invalid JSON value for CAST to INTEGER from column json_extract at row 1 (SQL: update `cars` set `detect_photo` = json_set(`detect_photo`, "$.door", {"key":"value"}) where `id` = 11)
