### ISSUE TITLE
Schedule::call documentation has a missing parameter type for $callback

### ISSUE THREAD

**Issue by Seldar** [laravel/framework#16400]
- Laravel Version: 5.2.45

The parameter $callback can either be a string or a callback function. PHPDoc block only states string which produces a warning on uses of callback functions. 
This line:
* @param  string  $callback
should be changed to this:
* @param  string|callable  $callback
for the sake of correctness and coding standards.

**Comment by themsaid** [comment]
Thank you :)

Please feel free to open a PR on the 5.3 branch.
