### ISSUE TITLE
env() returns first value in two laravel apps while doing curl from one to another on the same server

### ISSUE THREAD

**Issue by alexjose** [laravel/framework#16407]
- Laravel Version: 5.3.23
- PHP Version: 5.6.23

### Description:
I am working on micro-services based project in which I am using multiple Laravel/Lumen Apps which communicate to each other using GuzzleHttp. I am using XAMPP in Windows 8.

My issue is when I call an API on one of the app, in which another server side request is made to the second app is showing error that requested db table is not found. When I checked the DB used in the second app is the DB defined for the first app, not the DB defined for the second app.

I have verified that the issue is env method in second app is returning the configuration set for the first app.

#### Laravel App 1 ####
*.env*
`DB_DATABASE=laravel1`

*web.php*
```php
Route::get('/', function () {
    $response = file_get_contents('http://localhost/labs/laravel2/public/');
    $result = [
        'local' => env('DB_DATABASE'),
        'remote' => $response
    ];
    return $result;
});
```

#### Laravel App 2 ####
*.env*
`DB_DATABASE=laravel2`

*web.php*
```php
Route::get('/', function () {
    return env('DB_DATABASE');
});
```
#### Output ####
*http://localhost/labs/laravel1/public/*
`{"local":"laravel1","remote":"laravel1"}`

*http://localhost/labs/laravel2/public/*
`laravel2`

This issue happens only in Windows and is working fine in Linux. Not sure what is causing this issue.

**Comment by alexjose** [comment]
This is due to a [php bug](https://bugs.php.net/bug.php?id=71607) with the putenv which is used by the [vlucas/phpdotenv](https://github.com/vlucas/phpdotenv). This happens in the thread safe version since the subrequest made from first app is still under the same process.

This php bug is marked as won't fix. But I think this will be a major issue in Lumen when different microservices are deployed on the same server.

**Comment by GrahamCampbell** [comment]
When using laravel you can use the config cache feature to mitigate all issues like this. I imagine we'll at some point implement something similar for lumen.
