### ISSUE TITLE
Using find() in a HasManyThrough relation

### ISSUE THREAD

**Issue by neronmoon** [laravel/framework#16411]
Reference to #3553

- Laravel Version: 5.3.23
- PHP Version: 7.0

### Description:
I'm getting
```
Column 'id' in where clause is ambiguous (SQL: select `projects`.*, `project_user`.`user_id` as `pivot_user_id`, `project_user`.`project_id` as `pivot_project_id` from `projects` inner join `project_user` on `projects`.`id` = `project_user`.`project_id` where `project_user`.`user_id` = 1 and `id` = 1)
```
on `$user->projects()->where('id', $id)->firstOrFail()`
Yeah, i can use projects.id, but if eloquent claims to its name this issue should be resolved.

**Comment by srmklive** [comment]
@neronmoon why don't you try this If you are trying to get list of projects where `user_id=1`.

```
$user = App\User::with(['projects'])->where('id', 1)->firstOrFail();
$projects = $user->projects;
```

**Comment by themsaid** [comment]
You need to provide a fully qualified column name `->where('projects.id', $id)`
