### ISSUE TITLE
Account Enumeration Issue

### ISSUE THREAD

**Issue by restored18** [laravel/framework#16414]
- Laravel Version: 5.3.16
- PHP Version: 7.0.9
- Database Driver & Version: MariaDB 10.0.25

### Description:
Looks like the default session authentication setup is vulnerable to account enumeration through timing attacks. Trying to log in using an account that exists in the database takes a good deal longer than trying to log in with an account that is not in the database since `password_verify()` is never run. The easy, but not perfect solution would be to run `password_verify()` even if no user was found in the database. 

I know that many will consider this a non-issue since usernames/emails are considered public information. Even so, I'm all for increased security and developers in audited environments may find it helpful.

### Steps To Reproduce:
I set up a fresh copy of 5.3 and ran the scaffold for authentication. I registered one user. Then I tried to log in with the registered user's email and a bad password. Afterwards I tried to log in with a bad email and a bad password. The second request ran much quicker than the first. I repeated the process several times to make sure my web server was warm and not giving bad results.

Hope this helps!

**Comment by iget-master** [comment]
The issue make sense.

Deeping into the problem, I found on `SessionGuard` this method:

```
    /**
     * Determine if the user matches the credentials.
     *
     * @param  mixed  $user
     * @param  array  $credentials
     * @return bool
     */
    protected function hasValidCredentials($user, $credentials)
    {
        return ! is_null($user) && $this->provider->validateCredentials($user, $credentials);
    }
```

Note that if the `$user` is `null` (if email didn't match), the validate credentials do not run, so the `Hash::check` do not run.

Not sure if this is a critical issue, but, every security improvement is welcome for me.

**Comment by themsaid** [comment]
Thank you but this was discussed before and wasn't considered a security threat, the framework provides a convention that you can override in your app as you wish, so if you see it a security threat then just handle it in your application the way you see fit :)
