### ISSUE TITLE
Task Scheduling - thenPing uncaught error when destination fail 

### ISSUE THREAD

**Issue by iget-master** [laravel/framework#16413]
- Laravel Version: 5.2.45
- PHP Version: PHP 7.0.8-0ubuntu0.16.04.3
- Database Driver & Version: Not relevant

### Description:

`thenPing` is a tool to monitor if your Scheduled Tasks are running fine, right?
It's just a tool, right?

The problem is, if the destination url is offline, or return any error, the exception caused
by GuzzleHttp isn't caught, so any other scheduled will not run.

#### 1st - Setup following schedule commands

```
    protected function schedule(Schedule $schedule)
    {
         $schedule->call(function() {
             dump('First command.');
         })
                  ->everyMinute()->thenPing('http://invaliddomain.com');

         $schedule->call(function() {
             dump('Seccond command.');
         })
                  ->everyMinute()->thenPing('http://invaliddomain.com');
    }
```

#### 2nd - Run `php artisan schedule:run` on project root

This will be the output:

```
$ php artisan schedule:run
Running scheduled command: Closure
"First command."

                                                                                                                   
  [GuzzleHttp\Exception\ConnectException]                                                                          
  cURL error 6: Could not resolve host: invaliddomain.com (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)  
                                                                                                                                          
```

Note that in this case, the host is invalid. But a very common situation is the ping server be at maintenance or busy.

Since this error should not be critical to application, I think that it should not prevent execution.
Looks like the exception should be caught, and a Warning message should be logged.

**Edited to be more specific on steps to reproduce**

**Comment by GrahamCampbell** [comment]
Yes, the error is intended to be uncaught. It shouldn't silently fail.
