### ISSUE TITLE
PhPUnit env not working

### ISSUE THREAD

**Issue by loiclavoie** [laravel/framework#16412]
- Laravel Version: 5.2 and 5.3
- PHP Version: 7.0.8

### Description:
When running the phpunit command (either with the -c parameter or not), the segment of <php><env> is completely ignore. For instance, changing the APP_ENV value within the file doesn't change the environment within the run.

### Steps To Reproduce:
- Add a test dd(App::environment());
- Change the value within the phpunit.xml
- Run phpunit

cache:clear and config:clear didn't change anything to this.

**Comment by themsaid** [comment]
only `APP_ENV` is overridden in the test case, you don't really need to change it to anything other than "testing", however for the rest of the environment variables you can change them in `phpunit.xml` as you wish.

**Comment by loiclavoie** [comment]
@themsaid Shouldn't the system let the parameter be set in the file?

**Comment by srmklive** [comment]
@loiclavoie you need to override these parameters in `phpunit.xml` first.

**Comment by loiclavoie** [comment]
@srmklive I'm talking about the APP_ENV. themsaid seems to  say that it's hardcoded in Laravel when the run happen, it's overriden and ignore completely the APP_ENV set in the PHPunit.xml.

**Comment by sisve** [comment]
[Totally relevant line of code](https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Testing/TestCase.php#L89)

**Comment by taylorotwell** [comment]
What do you want to change it to?

**Comment by fernandobandeira** [comment]
Not sure why you need to change it but keep in mind that it's hard coded because of [this](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php#L39) and [this](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Foundation/Application.php#L527).

If som1 is creating a PR keep in mind that you should also change those accordingly.

**Comment by loiclavoie** [comment]
I'll close the issue for now, I've come up with another solution for the problem.

**Comment by AbdelkaderBah** [comment]
Are you using phpunit tests through Editor? editors might use the default phpunit configuration. make sure you select the path of phpunit.xml

Sorry to open this back 😅
