### ISSUE TITLE
Model $incrementing property multi-purposed

### ISSUE THREAD

**Issue by bryanashley** [laravel/framework#16427]
### Description:
The `incrementing` attribute is made to represent when a model is using an incrementing id as its primary key. Currently, I believe it is used to handle two different behaviors which might not always be what is desired, and would be better broken up into two different checks. I am more than willing to make a pull request to showcase these changes, but I thought it'd be valuable to have this conversation first. 

The two locations `incrementing` is currently used are: 
  - When eager loading a belongsTo relationship where the keys are null, if incrementing is false, use `null` instead of `0` for model keys ([seen here](https://github.com/laravel/framework/blob/6cf003ae02582cf716c10a723ef6bc19690969e7/src/Illuminate/Database/Eloquent/Relations/BelongsTo.php#L177)) 
  - When inserting a new row into the database, if incrementing is false, do not use the database to set the id on the new row ([seen here](https://github.com/laravel/framework/blob/73b324a7c6bcbbc041557decc128adb507f86417/src/Illuminate/Database/Eloquent/Model.php#L1574-L1576)

I do not believe both of those checks should rely on the same property. There are times, at least within my experience, where I want one without the other. My application is using uuids. When using uuids, I do not want `0` to returned as the eager loaded model key because `0` is not a valid uuid and I will receive a fatal error [noted in this issue](https://github.com/laravel/framework/issues/12051). But, when using uuids, and a database that generates my uuids for me like psql, I do want the ids to be set on the model after insert. Right now, because both checks utilize the same property, I cannot have both. 

### Proposed Solutions

I have two possible solutions that I can implement in a PR after some discussion.

#### Solution 1:

Change the eager loading check on BelongsTo, to check that related model's `keyType === 'int'` instead of whether or not its incrementing, as that is more accurate check for when to return `0` or `null` for the eager loaded keys. Then when a user is using uuid's they can simply change their keyType to better describe their primary key type. 

#### Solution 2 

Implement two different properties, `$incrementing` and something else and have these checks be exclusive from each other.

**Comment by jmk1ng** [comment]
It's true the current implementation seems biased towards the idea of numerically incremented IDs. Perhaps a more agnostic solution would be to have those calls be `getGenerated` instead of `getIncrementing` so that different kinds of auto-generated IDs can be handled with different expectations.

**Comment by bryanashley** [comment]
PR for proposed solution here: https://github.com/laravel/framework/pull/16440
