### ISSUE TITLE
Intended url after registering isn't redirected to.

### ISSUE THREAD

**Issue by regal2157** [laravel/framework#16423]
- Laravel Version: 5.3
- PHP Version: 7.0.8
- Database Driver & Version: n/a

### Description:
Laravel offers the session.url.intended redirect after logging in, but after registering - the user is redirected to the default $redirectTo variable.

### Steps To Reproduce:
Have a guest go to a route with auth middleware
User get's redirected to /login.
Navigate to /register
After registration, user is redirected to /home or whatever $redirectTo is set to.

### Suggestion:
This is my suggested fix, but not sure if it's the best option.

/Illuminate/Foundation/Auth/RegisterUsers.php:37-38

Change
```php
return $this->registered($request, $user)
            ?: redirect($this->redirectPath());
```

to:
```php
return $this->registered($request, $user)
            ?: redirect()->intended($this->redirectPath());
```

**Comment by GrahamCampbell** [comment]
Feel free to submit a PR. ;)

**Comment by jacobzlogar** [comment]
Thanks @regal2157

**Comment by lorisleiva** [comment]
This issue is a bit old now but still relevant. I've made a PR just in case this is still welcomed.

In the meantime, you can easily achieve this by implementing the `registered` method on the `RegisterController` like this:

```php
use Illuminate\Http\Request;

class RegisterController extends Controller
{
    // ...

    protected function registered(Request $request, $user)
    {
        return redirect()->intended($this->redirectPath());
    }
}
```

I hope this helps someone. 🍀
