### ISSUE TITLE
Can't trigger the right error when uploading files bigger that upload_max_filesize and the file field is optional

### ISSUE THREAD

**Issue by ivanhalen** [laravel/framework#16434]
- Laravel Version: 5.3.22
- PHP Version: 7.0.2
- Database Driver & Version: //

### Description:
Seems there's no way to catch the right error if an uploaded file has a bigger file size than upload_max_filesize and the upload field is not required (aka it's optional).

### Steps To Reproduce:

1. create an upload form:
```
<form action="{{ action('DummyController@dummyMethod') }}" method="post" enctype="multipart/form-data">
    <input type="file" name="picture" id="picture" accept="image/*">
    <button type="submit">Upload</button>
</form>
```
2. create a controller and a method:
```
class DummyController extends Controller
{
    public function dummyMethod(Request $request)
        {
            if (request()->hasFile('picture')){
                $file = request()->file('picture');
                if (!$file->isValid()){
                    return back()->with('error', $file->getErrorMessage());
                }
            }

            // validation
            $this->validate($request, [
                'picture' => 'mimes:jpeg,bmp,png'
            ]);

        }
}
```
3. I cannot simply use `if (!$file->isValid())` because file is not required and field could be empty (resulting in a `Call to a member function isValid() on null` error; so I have to wrap it in a `if (request()->hasFile('picture'))`, but if uploaded image is bigger than upload_max_filesize then `request()->hasFile('picture')` returns `false`.
The subsequent validation works and returns a dummy 'The :attribute failed to upload.' message that doesn't give a clue to the users about what happened, instead of the much more useful information that would have been returned by `$file->getErrorMessage()`

I don't know if there's a way to bypass or solve this problem, I'm stuck with this
Thanks

**Comment by themsaid** [comment]
It's done from inside the validator already, if the file isn't valid it fails with "Failed to upload" message.

**Comment by ivanhalen** [comment]
I see, but user has no clue of what happened (a message like `'The file "%s" exceeds your upload_max_filesize ini directive (limit is %d KiB).'`, that is in the `getErrorMessage()` method of `Symfony\Component\HttpFoundation\File\UploadedFile.php` class would be more useful, so user can choose a scaled down image)

**Comment by themsaid** [comment]
This doesn't look like a validation error message we should present to an end user, the validator fails with a "Failed to upload" message, which is enough for an end user.

You can use the `Illuminate\Foundation\Http\Middleware\VerifyPostSize` middleware to protect your forms, this will throw a `PostTooLargeException` exception depending on your `post_max_size`.

**Comment by prafful-panwar** [comment]
```
 public function rules()
    {
        return [
            'description' => ['required', 'min:10', 'max:2000'],
            'channel' => ['required', new ValidateChannel],
            'media' => 'sometimes|array',
            'media.*' => 'mimes:jpg,jpeg,png,avi,flv,wmv,mov,mp4|max:50000',
            'user_role' => ['required', 'exists:mongodb.roles,name', new ValidateUserRole],
            'campaign_id' => 'sometimes|exists:mongodb.campaigns,_id',
        ];
    }
```

**Note :**   I already change the value of post_max_size to 125M, upload_max_filesize to 100M and max_file_uploads to 20.

I am able to upload the larger file in local but when I try on the server side with around 10 MB size file, I am getting below error message
**Error Message :** 
```
{
    "message": "The given data was invalid.",
    "errors": {
        "media.0": [
            "The media.0 failed to upload."
        ]
    }
}
```
and when I try to upload larger than 10 MB file than i am getting **413 Payload Too Large** error.

Can anyone help me, please?

**Comment by muhammad-hamdi** [comment]
@prafful-panwar I'm facing the same problem

**Comment by victormacedo** [comment]
@prafful-panwar and @muhammad-hamdi I'm facing the same problem, did you find a solution?

**Comment by Ravikumar37728** [comment]
@victormacedo @prafful-panwar @muhammad-hamdi i'm also facing similar typr of err pls provide sol.if any one get.

**Comment by anthony0000** [comment]
here is what I did. just to emphasize, I am using wamp. The solution is to edit the php.ini file or phpmyadmin.conf .
if you are using wamp this solution is for you
**SOLUTION 1**
1. open this file **phpmyadmin.conf** either by VS code or notepad, it is probably in this location too on your computer **"C:\wamp64\alias\phpmyadmin.conf"**
2. Once opened you would see something like this
**php_admin_value upload_max_filesize 1024M**
**php_admin_value post_max_size 1024M**
once seen, increase the 1024 to as high as possible based on your file upload requirement, save and restart your wamp

**If this doesn't solve it then try solution 2**

**SOLUTION 2**
1. open your wamp folder then the **bin/php** folder, you will see a list of php version folders like so "**php7.4.33, php8.0.26, php8.1.13, php8.2.0**" respectively
2. edit **"upload_max_filesize = 2M"** to **"upload_max_filesize = 20M"** or something higher based on your file upload requirements in each of the **php.ini** in all the 4 folders 
3. Once done with the editing ensure you save then restart your wamp and try again.
4. That's it
