### ISSUE TITLE
app->singleton or app aliases not working

### ISSUE THREAD

**Issue by ferrisbuellers** [laravel/framework#16431]
- Laravel Version: 4.2.22
- PHP Version: 5.6
- Database Driver & Version: MySQL

### Description:
I updated laravel from 4.2.19 to 4.2.22, after doing so one of my service providers stopped working.
I am unsure if the app->singleton or the alias is the cause.
```
$this->app->singleton('error', function() {
	return new ErrorManager;
});
```
`'Error'  => 'SiteNamespace\Errors\Error',`

Calling Error::add etc.. in view or controller breaks in 4.2.22 but worked fine in 4.2.19 and all previous versions

**Comment by themsaid** [comment]
Please ask on the forums, we try to keep this repo for bug reporting only :)

**Comment by ferrisbuellers** [comment]
Is this not a bug?
It has been working fine for over a year.

I composer updated the site today and it has now broken (when on version 4.2.22), I reverted back to the last known working version (4.2.19) and it works fine again.

Thanks for the quick reply :)

**Comment by ferrisbuellers** [comment]
Please can you reopen.

**Comment by sisve** [comment]
@ferrisbuellers could you include your stack trace or tell us what happens, preferably more than "stopped working" and "breaks"?

**Comment by ferrisbuellers** [comment]
What happens is that when calling Error::hasErrors() in a controller or view it will error:
`production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method xxxxxx\Errors\ErrorManager::hasError()'`

I have checked the class and Error is not returning the class defined in the alias. however reverting back to 4.2.19 works... this looks like a bug to me.

**Comment by ferrisbuellers** [comment]
Ok so I have created a github repo with an example of this issue:

https://github.com/ferrisbuellers/laravelbug
This example is set to 4.2.20 (Its broken in this version+)

To see it working edit the laravel version in the composer.json to 4.2.19 or lower (tested on v4.2.5):
https://github.com/ferrisbuellers/laravelbug/blob/master/composer.json#L7

Please can this be re-reviewed and opened if it's a bug.

Many thanks.

**Comment by themsaid** [comment]
@ferrisbuellers please share the complete stack trace of the exception.

**Comment by krve** [comment]
Importing the Error facade at the top works.

```php
use laravelbug\Errors\Error;
```

@themsaid Here's the stacktrace:
![image](https://cloud.githubusercontent.com/assets/5139119/20474107/2cb6c4aa-afc5-11e6-8d0a-94272443970e.png)

**Comment by themsaid** [comment]
We upgraded Symfony components to 2.7, one of the dependencies of Symfony creates a class named Error, that's why laravel couldn't alias your class with the same name, so yes explicitly importing the facade path will make it work.

**Comment by themsaid** [comment]
Here's the line causing the issue: https://github.com/paragonie/random_compat/blob/master/lib/error_polyfill.php#L29

**Comment by themsaid** [comment]
So the only way around this is to rename the alias to something else other than Error

**Comment by ferrisbuellers** [comment]
Many thanks, will updated the class and let you know.
