### ISSUE TITLE
I get error messages while installing laravel by the composer

### ISSUE THREAD

**Issue by zvermafia** [laravel/framework#16439]
- Laravel Version: 5.3.*
- PHP Version: 7.0
- Database Driver & Version: not used

### Description:
I get error messages below while installing laravel by the composer:
```
...
Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
PHP Parse error:  syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in /home/laptop/Dev/tasix.app/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 475

Parse error: syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in /home/laptop/Dev/tasix.app/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 475
Script php artisan optimize handling the post-update-cmd event returned with error code 255
```

In the `vendor/.../helpers.php` file I found those lines of broken code [475-478]:

```
// ...
    function event(...$args)
    {
        return app('events')->fire(...$args);
    }
// ...
```

### Steps To Reproduce:
I just executed only one command:
``php7.0 /usr/local/bin/composer create-project --prefer-dist laravel/laravel test.app``

**Comment by shadoWalker89** [comment]
You must have PHP >= 5.6.4

**Comment by nmfzone** [comment]
I just believe the composer doesn't use your php7.0 version when installing, although you run it using php7.0 command. Do you use multiple php versions?

**Comment by zvermafia** [comment]
Problem isn't in PHP versions! Please, look at broken code.

What do you think, code written correctly?

_P.S. I'll try to install through homestead (v0.5.0)..._

**Comment by fernandobandeira** [comment]
> Problem isn't in PHP versions! Please, look at broken code.
> What do you think, code written correctly?
> P.S. I'll try to install through homestead (v0.5.0)...

```php
// ...
    function event(...$args)
    {
        return app('events')->fire(...$args);
    }
// ...
```

If you're refering to the ```... ``` that's the [splat operator](https://wiki.php.net/rfc/argument_unpacking) and it's correctly wrritten.

**Comment by themsaid** [comment]
You need to make sure you're using a proper version of PHP, please continue on the forums as we try to keep this repo for bug reporting only.

**Comment by zvermafia** [comment]
I'm sorry :(
I didn't know about of the **splat operator** (thanks @fernandobandeira), I thought it a bug/typo...

**Comment by Gedeonnibango1** [comment]
Hi there, I got the same problem, 
> php artisan
**Parse error: parse error in /Users/g../Documents/websites/New/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 233**

I installed php 7.1 but after installing composer then laravel, checking the php version using _php -v_ in Terminal, 
![screen shot 2017-12-05 at 23 01 12](https://user-images.githubusercontent.com/33984739/33630503-40036c54-da10-11e7-87a8-5bea1d3ecdcd.png) php 5.5.38 
Is there anyone who knows how to install php in this case?

**Comment by CupOfTea696** [comment]
@Gedeonnibango1 https://php-osx.liip.ch/ should work. If you have any more issues regarding running the correct PHP version, please refer to the forums, since this is intended for bug reports only.

**Comment by Gedeonnibango1** [comment]
@CupOfTea696 Than you so much indeed. PHP https://php-osx.liip.ch/ Worked.

**Comment by SopheakSem** [comment]
How about window, how to resolve?
