### ISSUE TITLE
Missing Route Feature

### ISSUE THREAD

**Issue by imanghafoori1** [laravel/framework#16437]
- Laravel Version:5.3.11
- PHP Version: 7.0
- Database Driver & Version:

### Description:
I know it is a feature request... and not a bug. 💃 

Route::get('my-web-url', 'UserCtrl@following')->view('my-html-template');
Route::get('my-webapp-api-url', 'UserCtrl@following')->json('vuejs-json-serializer');
Route::get('my-mobile-api-url', 'UserCtrl@following')->json('mobile-json-serializer');

and the controller just returns data which should be injected into the view or serializer.

### Steps To Reproduce:
I know it is a feature request... and not a bug.

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo. 👍
