### ISSUE TITLE
Unexpected behaviour in validation with value containing only spaces and a regex rule

### ISSUE THREAD

**Issue by unculture** [laravel/framework#16448]
- Laravel Version: 5.2.45
- PHP Version: PHP 7.0.5-2+deb.sury.org~trusty+1
- Database Driver & Version: Not relevant

### Description:
Attributes that have values where `trim($value) === ""` are not passed through the Regex validator, leading to a value eg. `"  "` passing validation, when I would expect that it should fail.

See: [isValidatable calls $this->presentOrRuleIsImplicit in Validator](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Validation/Validator.php#L563)

### Steps To Reproduce:
```php
$v = Validator::make(
    [
        "name" => "  "
    ], 
    [
        "name" => "regex:/^\S.*/"
    ]
);

$v->passes(); // returns true, I expect false because preg_match("/^\S.*/", "  ") === 0;
```

**Comment by fernandobandeira** [comment]
You should use required if you want to force this string to pass through the regex.

For example:

```php
$v = Validator::make(
    [
        "name" => "  "
    ], 
    [
        "name" => "required" // or "name" => "required|regex:/^\S.*/"
    ]
);

$v->passes(); // returns false for both cases
```

Seems that when ``` trim($value) === "" ``` it consider's as if the field isn't present, since using only required also returns false...

So it's not just regex actually any validation (file, etc) that you put in there will be ignored if ``` trim($value) === "" ```.

**Comment by themsaid** [comment]
Yes validation is skipped for empty fields unless you have a rule that would fail if the field is empty, also please upgrade to 5.3 since 5.2 is not supported any longer, there has been some changes in how the validator work in 5.3.

**Comment by unculture** [comment]
Thanks, yes I see. All I would say is that the field is explicitly not required and that values with spaces in are not empty in PHP, so there is a bit of a loophole here. I solved it with an after hook. 

A version upgrade is on it's way for us.
