### ISSUE TITLE
Calling update method on Eloquent Model does not perform "fillable check"

### ISSUE THREAD

**Issue by c00p3r** [laravel/framework#16447]
- Laravel Version: 5.2.45
- PHP Version: 5.6.23
- Database Driver & Version: mySQL 5.6

### Description:
I got that Eloquent model called 'Portfolio' and `$fillable` property filled.
Also, I have a form for updating my Portfolio.

So when I get request to update the DB record by id, I process incoming data and try to update my DB record like that:
```
Portfolio::where('id', $id)->update($request_data);
```
where `$request_data = $request->all();` so I have _unneeded data_ in it like `_token` and such...

_but_

I know that my Eloquent model is mass assignment protected and I don't worry about that _unneeded data_ to cause me some troubles....

_but it does!_

It won't go through 'fillable' check and the app will throw exception 'Illuminate\Database\QueryException' 
with message `SQLSTATE[42S22]: Column not found: 1054 Unknown column '_token' in 'field list' 
in ...\vendor\laravel\framework\src\Illuminate\Database\Connection.php:729`

I debugged my code and investigated that it calls for 'update' method of \Illuminate\Database\Query\Builder class instead of \Illuminate\Database\Eloquent\Model class as I expected.

And that's becase `where` method I use returns an instance of \Illuminate\Database\Query\Builder class wich has a diferrent implementation of `update` than `update` method of \Illuminate\Database\Eloquent\Model class  (particularly has NO 'fillable check')

In _my case_ I can just use `find` method (that returns Eloquent\Model instance) and by good with it...

_but_

What if I need to update a record NOT by primary key but by 'author' or 'date' property for example?
That means I have to use `where` clause... and my `update` method call won't be mass asignment protected...

That's my thought and I'm sorry if I misunderstood the way Eloquent models should be used.
So I ask for some clearafication on this matter, please

**Comment by sisve** [comment]
So, to summarize your text; you're wondering if $fillable should be used when doing `Model::where(...)->update($data)` like it is when doing `$model->update($data)`?

**Comment by c00p3r** [comment]
by the way, as far as I know, you can't call `update` method on Collection like `$model->update($data)`

**Comment by themsaid** [comment]
@c00p3r yes it won't work that way, update of the Eloquent builder won't check for fillable fields you'll need to use the update method of each model alone:

```
$users->where()->each(function($user){
    $user->update([...]);
});
```

**Comment by c00p3r** [comment]
I got it
Here's question: is it difficult to implement 'fillable check' to Query Builder?
As for me it would be cool and convenient feature

**Comment by themsaid** [comment]
Better use the update each method when updating models as it will fire model events, to get the full Eloquent experience you need to use this method.

**Comment by c00p3r** [comment]
Ok, I see
But there's one significate difference left to keep in mind (as I guess):

Qeury Builder method makes one big DB `UPDATE` query
whereas `each()` method makes many `UPDATE` queries to DB

Or am I wrong?

**Comment by themsaid** [comment]
Yes that's the difference.

**Comment by amitshahc** [comment]
I came here by finding the same reason. This is very obvious,. While performing mass  `::update($data)` the $fillable should perform the same duty as it is working while `::create` to neglect unlisted fields. if the `::find($id)` returning a single record of model then what it is stopping to follow the same. I didn't find any convincing answer or reason with the above thread.

**Comment by elanclarkson** [comment]
+1 I agree model::where()->update() should be guarded too. 

This is really easy to use without realising it isn't respecting the fillable property, which could lead to some really bad unintentional security holes...

**Comment by crazyabdul** [comment]
I really wish we didn't have to use workarounds to achieve something like this; but here we are. When I'm updating a single record I use the `first` method like this:

```
Portfolio::where('name', 'Akosua')->first()->update($request_data);
```

For multiple records, @themsaid 's solution is the way to go, unfortunately. Let me repost it here for convenience:
```
$users->where()->each(function($user){
    $user->update([...]);
});
```

**Comment by Verhoeckx** [comment]
Why is this closed? Shouldn't this be fixed (IMHO)?

I'm using Laravel 9 and I when I use the function [model name]::where('[column]', '[value]')-->update([​]) the array $fillable is not checked. Shouldn't that be the default? It's only checked when I call the function _first()_ first (as described above).
