### ISSUE TITLE
Use route() helper instead of url() helper in scaffolded views such as Auth

### ISSUE THREAD

**Issue by visyon360** [laravel/framework#16449]
Perhaps it's a bit subjective, but is there any major issue (or is it the correct way) to use the `route()` helper in scaffolded views, instead of the current `url()` one?
Just wondering it would give more flexibility if you decide to let's say, change the default routes for the scaffolded `Auth` package, or not messing it up if you just add a prefix to these routes.

Please label this as proposal/enhancement.

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.

Thanks anyway :)

**Comment by visyon360** [comment]
Great. will do. Thanks!
