### ISSUE TITLE
Validator doesn't work at all. Can't validate mimes also mimetypes.

### ISSUE THREAD

**Issue by xscence** [laravel/framework#16456]
- Laravel Version: 5.3
- PHP Version: 5.5.35

### Description:
Im trying to validate my video files but even if i pass correct mime/mimetype always returns error...
`<input type="file" name="video-file" />`

```
protected $validationRules = [
        'video-file' => 'mimes:mp4'
];
$validator = Validator::make($request->all(), $this->validationRules);
      
if(!$validator->passes()){
           var_dump($validator->messages()); // The video-file must be an mp4 file
}
```

**Comment by ntzm** [comment]
Going to sound obvious but have you made sure that the video you are trying to upload is a valid MP4 file?

**Comment by xscence** [comment]
Yes, it is.

**Comment by themsaid** [comment]
Your PHP version is not supported, please notice that mime guessing is dependent on your environment, please upgrade your PHP version and ask the question on the forums, we try to keep this repo for bug reporting only.

**Comment by xscence** [comment]
The issue is not from the php version!

**Comment by themsaid** [comment]
@xscence then what was the issue? can you sharE?

**Comment by xscence** [comment]
I will debug it later, but i'm using PHP 5.6 with enabled fileinfo extension and the result is the same every time. This  doesn't work also with mimes: jpg, png, gif etc.

```
MessageBag {#171 ▼
  #messages: array:1 [▼
    "file" => array:1 [▼
      0 => "The file must be a file of type: mp4."
    ]
  ]
  #format: ":message"
}
```

**Comment by xscence** [comment]
The Validator expects $value to be instance of UploadedFile but the $value returns only the name of the file in this case "myvideo.mp4"
```
 protected function validateMimes($attribute, $value, $parameters)
    {
        if (! $this->isAValidFileInstance($value)) {
            return false;
        }

        return $value->getPath() != '' && in_array($value->guessExtension(), $parameters);
    }
```

**Comment by craigpaul** [comment]
@xscense did you include the following as an attribute on your form tag?

enctype="multipart/form-data"

**Comment by xscence** [comment]
@craigpaul
Yes i saw now that's the problem. Amateur mistake ;< sorry guys. Long time no work with forms. Thanks and sorry for the lost time. Cheers.

**Comment by craigpaul** [comment]
You're welcome @xscense! Don't forget to close the issue! Thanks

**Comment by themsaid** [comment]
@craigpaul ♥️
