### ISSUE TITLE
5.2 basic auth no prompt

### ISSUE THREAD

**Issue by hung0** [laravel/framework#16459]
- Laravel Version: 5.2.41
- PHP Version: 5.6.11
- Database Driver & Version: mysql

### Description:
Trying to use basic authentication - update my route as per below however I do not get any prompt just the 'Invalid credentials' message...

// ROOT ROUTE
Route::get('/', array(
    'uses' => 'MyController@index',
    'as' => 'index',
    'middleware' => 'auth.basic'
));

Please help/advise - thanks!!!!

**Comment by srmklive** [comment]
5.2 is out of support. Is the same issue happening on 5.3?

**Comment by hung0** [comment]
Have not tried - I will shortly...

**Comment by hung0** [comment]
Worked through the 5.2 to 5.3 upgrade guide...finished the upgrade unfortunately still not getting the prompt. hhrrrmmm...sort of stuck here - not sure what to do next...not seeing anything useful in logs...

:cat .htaccess
<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On

    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)/$ /$1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]

    # Handle Authorization Header
#    RewriteCond %{HTTP:Authorization} .
#    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteCond %{HTTP:Authorization} ^(.+)$
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
</IfModule>

#AuthUserFile /var/www/portaExtensionManager/.htpasswd
#AuthType Basic
#AuthName "Extension Manager"
#Require valid-user

**Comment by themsaid** [comment]
@hung0 it seems to be working normally in 5.3 on Valet and nginx, not sure about apache though as Id on't have experience with it. I think that's not a bug in the framework but rather some apache configuration needs alteration, no?
