### ISSUE TITLE
Error 500 - Laravel in Shared hosting

### ISSUE THREAD

**Issue by MadaSociety** [laravel/framework#16464]
- Laravel Version: 5.3.16
- PHP Version: 5.6.27
- Database Driver & Version: Mysql Ver 15.1 Distrib 10.1.19-MariaDB
- Panel : ISPConfig 3.1.1p1

### Description:
In shared hosting, I can't run two Laravel projects. After edit vhost and restart apache, the first website loaded work correctly but others Laravel projects get "**Error 500**"

### Steps To Reproduce:
I have installed two Laravel into two different domains with **composer create-project**. 
- domain1.tld => Laravel 1
- domain2.tld => Laravel 2

After installation, I added Apache Directives from ISPConfig and apache reload the new configuration.

If I open **Laravel 1** at the first time, I get Error 500 in **Laravel 2** (Vice versa) after restart apache.

### Error log for the website getting Error 500
- bootstrap/autoload.php on line 32 : **### _PHP Warning:  file_exists(): open_basedir restriction in effect. File(site_that_works/bootstrap/cache/compiled.php) ..._**
`if (file_exists($compiledPath))`

- bootstrap/app.php on line 15 : **_### realpath(): open_basedir restriction in effect. File(site_that_works) ..._**
`realpath(__DIR__.'/../')`

### Edit two file
Edit **bootstrap/autoload.php** on line 30 : I added space before and after the point.
`$compiledPath = __DIR__.'/cache/compiled.php';` to `$compiledPath = __DIR__ . '/cache/compiled.php';`

Edit **bootstrap/app.php** on line 15 : I added space before and after the point.
`realpath(__DIR__.'/../')` to `realpath(__DIR__ . '/../')`

After editing two files all Laravel projects works correctly.

**Comment by concept-core** [comment]
It tells you, you haven an error.
Did you look into the open_basedir error ? 

If not please read this : http://stackoverflow.com/questions/1846882/open-basedir-restriction-in-effect-file-is-not-within-the-allowed-paths

**Comment by MadaSociety** [comment]
Yes I have read this, but I don't understand, why the first website work correctly and others Laravel projects get file on the first website and generate error 500.

**Comment by themsaid** [comment]
Please ask on the forums, we try to keep this repo for bug reporting only.

**Comment by MadaSociety** [comment]
The bug is fixed, I edited the first post. Thank you.

**Comment by ademola25** [comment]
@iwebroot  i  am having the same issue.  which post did you edit to fix it? can you tell
