### ISSUE TITLE
Vendor translations do not load properly

### ISSUE THREAD

**Issue by gocanto** [laravel/framework#16471]
- Laravel Version: v5.3.23
- PHP Version: 7

### Description:

Hi, I am trying to load translations from ```resources/lang/vendor```, but I just get as result the string related to their keys.

This is what I have so far:

***Translations folder***
```resources/lang/vendor/gocanto/en/globals.php``` whithin this file, I have something similar to this ```'foo' => 'bar'```

***How I am trying to load this key***
```php
trans('gocanto::globals.foo')
```

***Result***
```
gocanto::globals.foo
```

I referred to the <a href="https://laravel.com/docs/5.3/packages#translations">doc</a> before placing this in here, as well as laracas forum.

**Comment by themsaid** [comment]
Have you registered the vendor namespace properly?

```
$this->loadTranslationsFrom(__DIR__.'/path/to/translations', 'gocanto');
```

**Comment by gocanto** [comment]
Yes sir, I actually did.

This is what I have in my service provider:

```php
 $this->loadTranslationsFrom(__DIR__ . '/../resources/lang', 'gocanto');
```

this is my package folder structure

```
/resources/lang/
src/servicesprovider.php
```

**Comment by themsaid** [comment]
@gocanto can you share what the issue was?

**Comment by gocanto** [comment]
I still have and relly do not know what the problem is. This is my scenario. I have a package that provides translations. Within it, I have all the settings needed to publish them under a custom namespace, as showed above.

Now, it happens to be that I do not have access to these translations calling them as so ```php trans('gocanto::foo.bar)``` from my package. But, I do when I call them from the app which implements the package. 

I do not know if you understand what I just said.

**Comment by themsaid** [comment]
Well a package alone doesn't work :) It needs an application.

**Comment by gocanto** [comment]
So, what's the best way to call these trans from the package?
