### ISSUE TITLE
Why cache::put()  set $minutes default null ?

### ISSUE THREAD

**Issue by heavenmirror** [laravel/framework#16474]
- Laravel Version: 5.3

### Description:
https://github.com/laravel/framework/blob/5.3/src/Illuminate/Cache/Repository.php#L197
why set default null of $minutes?
I'm not sure if it successed.

**Comment by vlakoff** [comment]
It is needed to support the following syntax, note there is no 3rd argument:
```php
Cache::put([
    'key1' => 'value1',
    'key2' => 'value2',
], 60);
```

**Comment by heavenmirror** [comment]
But in this case, no 3rd argument will failure.

```
Cache::put('key', 'value');
```

**Comment by fernandobandeira** [comment]
@heavenmirror Because you always need to pass the $minutes, if you pass an array the $minutes are passed as the second parameter since you will have both your 'key' and 'value' inside your array so you skip one parameter...
