### ISSUE TITLE
Migration not atomic

### ISSUE THREAD

**Issue by Fenzland** [laravel/framework#16487]
- Laravel Version: 5.3.22
- PHP Version: 7.0.8
- Database Driver & Version: MariaDB 10.0.27

### Description:
Migration is not atomic, so when my migration run failed, the migration will not be treated as active, but some effects are active.  Especially, one of my migration creates a table and add some foreign key. With some exception, foreign key adding failed, but the table exists. Then, I can't migrate anymore, I can't rollback either, because the migration is not in migrations table.

### Steps To Reproduce:

****_create_foos_table.php
```php
# ...
class CreateFoosTable extends Migration
{
	public function up()
	{
		Schema::create('companies', function (Blueprint $table) {
			# ...
			$table->integer('bar_id');
			$table->foreign('bar_id')->references('id')->on('bars')->onDelete('CASCADE')->onUpdate('CASCADE');
			// As bars not exists, the foreign key will be not added successful.
			# ...
		}
	}
	# ...
}
```

**Comment by fernandobandeira** [comment]
This is a duplicated issue, #15788
Also this is quite an old issue, too #302
