### ISSUE TITLE
Inappropriate migration file 'people' created instead of 'person'

### ISSUE THREAD

**Issue by mnrahimi** [laravel/framework#16491]
- Laravel Version: 5.3.23
- PHP Version: 5.6.26

### Description:
While I tried to make a new model `Person` and let laravel to produce its migration file for me it produced a file `2016_11_21_190948_create_people_table.php` for table `people` which is incompatible with my new model `Person`.

### Steps To Reproduce:
Run the following command from within a fresh installed Laravel project directory: `php artisan make:model Person -m` then look at the file `database/migrations/#_#_#_#_create_people_table.php`.

**Comment by fernandobandeira** [comment]
Yep Laravel pluralizes the table and leaves your model on singular thats the default behavior and your model should be working as expected.

**Comment by mnrahimi** [comment]
@fernandobandeira Thank you I got it and I will close it.

**Comment by HelissonMS** [comment]
What about the foreign key?
"person_id" or "people_id"?

**Comment by mnrafg** [comment]
Thank you but the problem was solved, and it was caused by as @fernandobandeira replied.
