### ISSUE TITLE
[5.3] Auth Gate : Throwing an error when no ability match

### ISSUE THREAD

**Issue by abellion** [laravel/framework#16496]
- Laravel Version: 5.3.23
- PHP Version: 7

### Description:

When the `authorize` method of the `Gate` class is called with an undefined ability / policy, no error is thrown, it's just considered as unauthorized. Is it intentional or not ?

What do you think of throwing an error instead of just returning false ? I think it could save some debug time considering making a typo is common (even in the policies namespaces). 

FYI I can provide a PR for that, if needed.

Regards.

**Comment by themsaid** [comment]
I don't think we should throw an exception here, abilities can be stored in a DB for example and its possible that developers decide to remove this ability from the app, the end user should just get "Unauthorized", he shouldn't get a 500 exception in this case.

**Comment by abellion** [comment]
Yeah but the method in the policy, and the policy itself should exist anyway, don't you think ?

The thrown error should send a 401 "Unauthorized" status code for the end user I agree, but by throwing an error of type "GateException" for example it could be very useful for debugging tools like Bugsnag, Sentry, ...

**Comment by themsaid** [comment]
Not sure if that belongs to the core, feel free to open a PR though :)

**Comment by themsaid** [comment]
To not waste your time, you can ping Taylor on Larachat and propose the idea, or use 
use the https://github.com/laravel/internals repo to gather feedback.
