### ISSUE TITLE
Using `SQL_CALC_FOUND_ROWS` with eager-loaded relationship returns wrong count

### ISSUE THREAD

**Issue by martincarlin87** [laravel/framework#16499]
- Laravel Version: 5.1.45
- PHP Version: 7.0.12
- Database Driver & Version: MySQL 5.7.15

### Description:

In my Laravel app I was doing an ordinary query on a model (`ModelA`) whilst making use of `SQL_CALC_FOUND_ROWS` and then performing `SELECT FOUND_ROWS()` afterwards to retrieve the count of all records since the first query used `LIMIT` and `OFFSET`.

This worked perfectly fine, but now that I've added a relationship to the model I was querying above, if I do the same query but using `with->('modelB')`, this query is performed after the initial query and before `SELECT FOUND_ROWS()` so I get the count of the `ModelB` results instead of `ModelA` as I was expecting.

Is there a way to make this work as desired where I get the count of the first (main) query and not the relationship?

e.g. This works fine:

    $query = ModelA::select([DB::raw("SQL_CALC_FOUND_ROWS *")])
        ->where('active', 1);

    // conditional ->where()'s

    $query->skip(intval($skip))
        ->take(intval($take))
  	    ->orderBy($column, $dir);

    $results = $query->get();

    $total = DB::select(DB::raw("SELECT FOUND_ROWS() AS 'total';"))[0]->total;

but changing the first line to this doesn't:

    $query = ModelA::with('modelB')
        ->select([DB::raw("SQL_CALC_FOUND_ROWS *")])
        ->where('active', 1);

A workaround is to just do it without eager-loading and fetch each relationship individually but then I'd have one query per result when I loop through the results later in the code.

**Comment by themsaid** [comment]
That makes sense because with eager loading you're running a second query, so the results of SQL_CALC_FOUND_ROWS is presented with regards to the second query because it's the latest query.

Not sure what's an alternative way for that since it depends on your case; however, I suggest that you ask this question on the forums since this repo is for bug reporting only, maybe there you'll find more help :)

**Comment by richardDobron** [comment]
You can also use [Constraining Eager Loads](https://laravel.com/docs/8.x/eloquent-relationships#constraining-eager-loads) for first relation.

```
$total = 0;

$query = ModelA::with([
    'modelB' => function () use (&$total) {
        $total = (int)DB::select("SELECT FOUND_ROWS() as `row_count`")[0]->row_count;
    },
    'modelC',
])
->select([DB::raw("SQL_CALC_FOUND_ROWS *")])
->where('active', 1);

$rows = $query->get();

echo $total;
```
