### ISSUE TITLE
POSTing to non-existent URL throws TokenMismatchException instead of 404 or 405 error

### ISSUE THREAD

**Issue by EspadaV8** [laravel/framework#16497]
- Laravel Version: 5.1.35
- PHP Version: 7.0.12

### Description:

This feels like an issue but could be as intended. Attempting to submit a POST request to a URL that doesn't handle POSTs will throw a TokenMismatchException instead of 405 Method Not Allowed or 404 Not Found response.

Should CSRF be checked for routes that aren't configured to handle POST requests? And is there any way to change this behaviour?

**Comment by srmklive** [comment]
FIrst of all, it is first checked whether the CSRF token is sent with the POST request. If that check passes, then it is checked, whether that route actually exists.

This in my view is not a bug within the framework.

**Comment by EspadaV8** [comment]
Yeah, that's why I wasn't sure if it is a bug or not. To me it feels like it should check to see if it's a valid route first and then check CSRF token. If the route isn't valid then there's no point checking anything else and there could be an early return.

**Comment by themsaid** [comment]
Well since this is in 5.1 then there's nothing we can do about it, it's an LTS version so a change in behaviour might break something and we don't want that to happen.

**Comment by mstnorris** [comment]
Has this been addressed at all in later versions? I too would expect a 405 response when making a POST request to a route if it only supports GET requests for example.

In the same manner I'd expect a 404 response if the route didn't exist altogether.

And **only** when the route exists, and it _does_ accept POST requests, then it should through a TokenMismatchException if the tokens don't match.
