### ISSUE TITLE
Why does Laravel not allow access to get parameters with a post request?

### ISSUE THREAD

**Issue by stephan-v** [laravel/framework#16504]
- Laravel Version: 5.3
- PHP Version: 7.0

I have been checking out the Laravel source code a bit and I found this bit of code:

```PHP
return $this->getRealMethod() == 'GET' ? $this->query : $this->request;
```

From:

https://github.com/illuminate/http/blob/master/Request.php#L668

This basically specifies that if the request method for a request is a 'GET' that the ```input``` method returns the query string parameters and otherwise gives you access to the POST variables.

This means that whenever I would make a post request I can not do the following to get a query string parameter named "date" for example:

```PHP
$request->input('date')
```

I know it is useful to not merge POST and GET data since you get the possibility of overriding them but what is the exact motivation behind not allowing a user access to the query parameters when you make a POST request?

The way I see it, the input could have been split up into ```postInput(or simply post)``` and ```getInput(or simply get)``` for example to allow access to both without merging them. Of course you lose the ability that a generic input method gives you, but you gain a lot of flexibility.

Any thoughts on this? (I am still wondering if it's alright to ask questions like this via an issue. Let me know if this is incorrect behavior. Somebody from stackoverflow directed me over here to ask my question.)

**Comment by themsaid** [comment]
You can use `get()` instead of `input()`.

**Comment by sisve** [comment]
Just a quick reminder; we've been told not to use get().

https://github.com/laravel/internals/issues/114
https://github.com/laravel/framework/issues/13138
https://github.com/laravel/docs/pull/2269

**Comment by themsaid** [comment]
Yes it's not recommended, same as the case mentioned. But it gets the job done :)

**Comment by crynobone** [comment]
> we've been told not to use get()

Told not to use vs not recommended is totally different. `Request::get()` came from Symfony, not Laravel. While you can use it as you can use many of Symfony available method for Request is not advertise and documented, but doesn't mean you are told not to use it when it's exactly what you need.

**Comment by lagbox** [comment]
I have access to my query string params on POST requests via the `input` method; did I miss something?
