### ISSUE TITLE
JSON Fillable Columns

### ISSUE THREAD

**Issue by lukepolo** [laravel/framework#16505]
- Laravel Version: 5.3.24
- PHP Version: 7.0.13
- Database Driver & Version: MySQL 5.7.16

### Description:
Fillable not respecting json columns 

### Steps To Reproduce:

Add a JSON column to fillable array , then try to update 

$fillable = ['foo'];

`FooBar::findOrFail($id)->update(['foo->bar']);`

May not be a bug , may be intentional that you have to write out exactly what properties are fillable , but would be nice if we could do 'foo*'

**Comment by fernandobandeira** [comment]
Refs #15433

> it's expected that you need to add all fillable fields including the JSON ones, that way you can decide what JSON attributes you want to guard and what may be left fillable.

And your suggestion also is a closed PR #15464

Basically this has been discussed before...

**Comment by lukepolo** [comment]
Thanks for finding that ~ will close
