### ISSUE TITLE
Array casting does not work with PgSQL native arrays

### ISSUE THREAD

**Issue by martimarkov** [laravel/framework#16515]
- Laravel Version: 5.2.45
- PHP Version: 7.0.13
- Database Driver & Version: PostgresSQL 9.5 pdo_psql

### Description:

When trying to save a casted array in PgSQL Laravel fails with an error:

>   [PDOException]                                                                                
  SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  malformed array literal: "[3,4,5,6]"  
  DETAIL:  Missing "]" after array dimensions.      

This only happens with native PgSQL array types.

### Steps To Reproduce:

1. Setup your application with PosgreSQL DB engine.
2. Create a table in the DB with one column `testing` being `integer[]`
3. Create a model that has an attribute `testing` and in `$casts` has a type `'array'`
4. Instantiate your model and assign `testing` an integer array: `$model->testing = array(1,3,4,5);`
5. Save the model `$model->save`.
6. Observe the SQL error.

### Solution
 Add custom support for PgSQL for array casting?

**Comment by themsaid** [comment]
@martimarkov 5.2 is not supported anymore, please check if the error still exists in 5.3
