### ISSUE TITLE
add only created_at timestamp to the table

### ISSUE THREAD

**Issue by nagavinodcse** [laravel/framework#16516]
- Laravel Version: 5.3.0
- PHP Version: 5.6.25
- Database Driver & Version: MySql 5.0.11
### Description:
I want to set only the created_at timestamp in my notification table instead of both the timestamps
is it possible

**Comment by themsaid** [comment]
you can use `$table->timestamp('created_at');` Check https://laravel.com/docs/5.3/migrations#columns

Please ask questions in the forums, this repo is for bug reporting only.
