### ISSUE TITLE
SQLSTATE[42000]: Syntax error when using ->after() function

### ISSUE THREAD

**Issue by axelitus** [laravel/framework#16512]
- Laravel Version: 5.3.23
- PHP Version: 7.0.8
- Database Driver & Version: MySQL 5.7.16
- Homestead: 0.6.0

### Description:
When trying to create a migration with some column with `->after()` function the QueryBuilder throws invalid SQL code to generate the table.

### Steps To Reproduce:
On the migration `up()` function try to set this table:
```
public function up()
{
    Schema::create('users', function (Blueprint $table) {
        $table->bigIncrements('id');
        $table->string('email')->unique();
        $table->string('password');
        $table->string('name');
        $table->timestamps();
        $table->string('created_by')->nullable()->after('created_at');
        $table->string('updated_by')->nullable()->after('updated_at');
    });
}
```

This code generates the following SQL code:
```
create table `users` (
   `id` bigint unsigned not null auto_increment primary key,
    `email` varchar(255) not null,
    `password` varchar(255) not null,
    `name` varchar(255) not null,
    `created_at` timestamp null,
    `updated_at` timestamp null,
    `created_by` varchar(255) null after `created_at`,
    `updated_by` varchar(255) null after `updated_at`
) default character set utf8 collate utf8_unicode_ci
```

The `after` keyword is not valid in the create table statement as per the MySQL reference page: http://dev.mysql.com/doc/refman/5.7/en/create-table.html although it is valid in the alter table statement: http://dev.mysql.com/doc/refman/5.7/en/alter-table.html

This should be achievable in two steps (create table then alter reordering columns) unless I'm missing something...

**Comment by srmklive** [comment]
This will always throw an error. Its a mistake on our part :laughing:, because `created_at` & `updated_at` columns haven't been created yet, and you are directing that two new columns are created immediately.

**Comment by themsaid** [comment]
Yeah you need to do it in two steps.

**Comment by axelitus** [comment]
Would it be useful to have aliases to created_at and updated_at timestamp functions? Like so:

```
public function timestamp_created()
{
    return $this->timestamp('created_at')->nullable();
}

public function timestamp_updated()
{
    return $this->timestamp('updated_at')->nullable();
}

public function timestamps()
{
    $this->timestamp_created();

    $this->timestamp_updated();
}
```

Or would this be overkill and better use the `$this->timestamp('column_name')` function **manually**?
