### ISSUE TITLE
PHP Artisan migrate doesn't seem to handle package migrations

### ISSUE THREAD

**Issue by natenator** [laravel/framework#16517]
- Laravel Version: 5.3.*
- PHP Version: >5.6.4
- Database Driver & Version: MySQL 5.7.16

### Description:
Hey. I've been looking around the existing issue tickets, but I'm failing to find a solution to my problem. I'm probably doing something wrong, but here is my problem:

I just installed the `venturecraft/revisionable` package to my new Laravel installation, and I noticed that it comes with its own migration. To get it up and running, I ran the migration. Later, I thought to myself "Self, how will fresh installations of my project work if `php artisan migrate` doesn't run package migrations?" So now I ask this of you. I've thought about copying the migration to my main migrations folder, but this feels hacky and doesn't work for new migrations of new versions of my packages on `composer update`.

Also, if I ever run `php artisan migrate:reset`, it complains about the table from the package migration saying "Undefined index: 2013_04_09_062329_create_revisions_table".

Sorry if this has already been resolved. If it has, I haven't found it.

### Steps To Reproduce:
`composer require venturecraft/revisionable`
`php artisan migrate --path=vendor/venturecraft/revisionable/src/migrations`
`php artisan migrate:reset`

**Comment by crynobone** [comment]
Laravel already allows options for package developer to include custom migration path. https://laravel.com/docs/5.3/packages#migrations

If the package developer choose not to use this feature, there nothing we can do about it.

**Comment by themsaid** [comment]
Contact the package maintainer and suggest having a Service Provider where he can register the path to the package migrations instead of having to run `php artisan migrate --path=vendor/venturecraft/revisionable/src/migrations`

**Comment by natenator** [comment]
Thanks for getting back with my so quickly! Sorry, I'm still pretty new to the framework. THank you for pointing this out, I'll definitely nudge them about it :)

Thank you again.

**Comment by junioro12** [comment]
If you copy the revisions table migration into the folder with the other migrations you should be fine...
