### ISSUE TITLE
Too many includes when rendering collections with partial blade views

### ISSUE THREAD

**Issue by reshadman** [laravel/framework#16525]
- Laravel Version: 5.1.*

### Description:
Too much `include` directives inside a for loop affects render time significantly, that's because every time the loop iterates the native php `include` is used. 

The Purpose of a directive like `@each('collection_item_renderer', $collection, 'item')` is to satisfy the *don't repeat yourself* principle, but it heavily increases render time on large collections. something like *twig macros* would help a lot in these situations. the compiler would simply copy/paste the partial blade inside the loop. If the scoped data is a concern the final output can be wrapped around self-invokable function something like the following:

```php
// contents of main view file
@for($i=0; $i<1000; $i++)
    @render_macro('index_renderer', $i)
@endfor

// contents of index_renderer.blade.php
{{$i}}

// Final compiled output
<?php for($i =0; $i<1000; $i++) {  ;?>

// If partial variable scope is not important
<?php echo $i ;?>

// If partial variable scope is important
<?php $function = function ($i) { ;?>
     <?php ob_start() ;?>
     <?php echo $i ;?>

<?php } ;?>

<?php call_user_func($function);?>

<?php } ;?>
```

**Comment by themsaid** [comment]
please feel free to open a PR.
