### ISSUE TITLE
Event for "increment" method on Model class

### ISSUE THREAD

**Issue by jcescala** [laravel/framework#16527]
- Laravel Version: 5.2.45
- PHP Version: 5.6.23
- Database Driver & Version: Mysql 5.5.52

### Description:
The "increment" method of Model class doesn't trigger either a saved or updated event.

### Steps To Reproduce:
Extend boot method in a trait or directly on the model

**Comment by GrahamCampbell** [comment]
This is the expected behaviour I'm afraid, due to the nature of the implementation. Please see previous reports for details.

**Comment by rorc** [comment]
So, how i can fire event updated after increment?
