### ISSUE TITLE
Builder backwards incompatible

### ISSUE THREAD

**Issue by piotrtheis** [laravel/framework#16528]
- Laravel Version: #.#.#
- PHP Version: 7.0.8
- Database Driver & Version:

### Description:
@taylorotwell LengthAwarePaginator should use custom model collection from newCollection not Collection, even if query result is empty.

 [from docs](https://laravel.com/docs/5.3/eloquent-collections#custom-collections)

[from](https://github.com/illuminate/database/commit/2d6555ce1a1d56668a2210f5c16fe390acd7217a)
[to](https://github.com/illuminate/database/commit/0e541c58ec4ced7246d239071c40fd9bb088f7b5)

### Steps To Reproduce:

```
$results = $this->forPage($page, $perPage)->get($columns);
```
instead of
```
$results = $total ? $this->forPage($page, $perPage)->get($columns) : new Collection;
```

[in](https://github.com/illuminate/database/blob/master/Eloquent/Builder.php#L533)

**Comment by vlakoff** [comment]
Makes sense to transmit the same class, whether results are empty or not.

If you want to keep the optimization from #14188:
```php
$results = $total
    ? $this->forPage($page, $perPage)->get($columns)
    : $this->model->newCollection();
```

**Comment by GrahamCampbell** [comment]
We're open to PRs. :)

**Comment by vlakoff** [comment]
Submitted #16547.

Though may I suggest to close issues *after* a PR has been opened? If an issue is worth fixing but is closed, it's easy to forget about it…
