### ISSUE TITLE
[Envoy] A tasks user is not being used with ParallelSSH

### ISSUE THREAD

**Issue by bretrzaun** [laravel/framework#16529]
- Laravel Version: "laravel/envoy" : "~1.2"
- PHP Version: 7
- Database Driver & Version: n/a

### Description:
When setting the username in a Task it is not being used when executing that task.

### Steps To Reproduce:
```php
$task = new Laravel\Envoy\Task($nodes, $username, $cmd, true);
$ssh = new Laravel\Envoy\ParallelSSH();
$ssh->run($task);
```

**Comment by GrahamCampbell** [comment]
This issue tracker is for the framework only, sorry.
