### ISSUE TITLE
Method hint for ServiceProvider register()

### ISSUE THREAD

**Issue by fetzi** [laravel/framework#16520]
- Laravel Version: 5.3.x
- PHP Version: 7.0
- Database Driver & Version: mysql 5.6

### Description:
It is a bit misleading that the abstract method `register` was removed from the `ServiceProvider` class, but it is referenced in the docs.

Solution would be a method hint on the abstract class.

### Steps To Reproduce:
Manually extend the `ServiceProvider` Class

**Comment by themsaid** [comment]
feel free to open a PR :)
