### ISSUE TITLE
Unknown column type "timestamp" requested

### ISSUE THREAD

**Issue by marktopper** [laravel/framework#16526]
- Laravel Version: 5.3.24
- PHP Version: 7.0.12
- Database Driver & Version: 10.1.19-MariaDB

### Description:
When trying to update a column with the type of `timestamp`, it fails with this exception:
```
[Doctrine\DBAL\DBALException]
  Unknown column type "timestamp" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known types with \Doctrine\DB
  AL\Types\Type::getTypesMap(). If this error occurs during database introspection then you might have forgot to register all database types for a Doctrine Type. Use AbstractPlatform#registerDoctrine
  TypeMapping() or have your custom types implement Type#getMappedDatabaseTypes(). If the type name is empty you might have a problem with the cache or forgot some mapping information.
```

### Steps To Reproduce:

1. Get clean install of Laravel running `laravel new migration-test`
2. Make new migration file `php artisan make:migration test --table=users`
3. Add this line of code to it: `$table->timestamp('created_at')->change();`
4. Run `php artisan migrate`

**Comment by themsaid** [comment]
This is an issue with doctrine, if you check the issues history in this repo you'll find many similar reports, it all depends on what doctrine supported/haven't supported yet/won't support.

**Comment by JTallis** [comment]
I wanted to change all timestamps to nullable as due to the change in how the timestamp column type acts, I'm unable to perform migrations. I decided to attempt to change the columns but I'm told that I need to install doctrine/dbal. After doing so, it tells me timestamp isn't a valid column type.

So as a result, I have to change each column manually as I can't use a migration to do so.

What's the deal with this? I need to take a break because I'm fuming that not only did MySQL implement a breaking change but Laravel won't even let you rectify the issue.

**Comment by ArtbyArjan** [comment]
@JTallis As @themsaid says, this is an issue with doctrine/dbal, not with Laravel itself.

**Comment by yurikorolov** [comment]
#https://github.com/doctrine/dbal/issues/2558

**Comment by darklightblue** [comment]
For those who installed the [Package](https://github.com/marktopper/doctrine-dbal-timestamp-type) created by OP and wanted to change a timestamp into nullable (just like I did) like:

```
$table->timestamp('ClaimedAt')->nullable()->change();
```

and encountered this error:
```
Syntax error or access violation: 1067 Invalid default value for 'ClaimedAt' (SQL: ALTER TABLE my_table CHANGE ClaimedAt ClaimedAt TIMESTAMP NULL DEFAULT 'CURRENT_TIMESTAMP')
```

All you have to do is add a default value:
```
 $table->timestamp('ClaimedAt')->nullable()->default(null)->change();
```

and it should work.

Reverting it from nullable to use the current timestamp doesn't need to call `default` tho:
```
$table->timestamp('ClaimedAt')->nullable(false)->change();
```

should work.

Just sharing it here just in case someone is searching for the same question.

**Comment by ralphjsmit** [comment]
For everyone who is still coming across this issue via Google or something, there currently is an official way to support this. See [this part of the docs](https://github.com/laravel/docs/blob/master/migrations.md#prerequisites).

Basically, you need to add the following to your `config/database.php` file:

```php
'dbal' => [
    'types' => [
        'timestamp' => TimestampType::class,
    ],
],
```

**Comment by smartens80** [comment]
> For everyone who is still coming across this issue via Google or something, there currently is an official way to support this. See [this part of the docs](https://github.com/laravel/docs/blob/master/migrations.md#prerequisites).
> 
> Basically, you need to add the following to your `config/database.php` file:
> 
> ```
> 'dbal' => [
>     'types' => [
>         'timestamp' => TimestampType::class,
>     ],
> ],
> ```

Make sure you add `use Illuminate\Database\DBAL\TimestampType;` as well ;)

**Comment by qzw881130** [comment]
use Illuminate\Database\DBAL\TimestampType;

'dbal' => [
    'types' => [
        'timestamp' => TimestampType::class,
    ],
],

**Comment by qzw881130** [comment]
```
use Illuminate\Database\DBAL\TimestampType;

'dbal' => [
    'types' => [
        'timestamp' => TimestampType::class,
    ],
],
```

**Comment by tjodalv** [comment]
I am wondering why this hasn't been added by default in the config file?!?

**Comment by ralphjsmit** [comment]
@tjodalv Likely because Laravel 11 removed the dependency on DBAL by default.

**Comment by Denisok94** [comment]
It's strange what I was able to do a year ago:

```php
$table->timestamp('start_at')->withoutTz()->nullable();
```
But I can't do it now:
```php
$table->timestamp('start_at')->nullable(true)->default(null)->change();
```
I don't think I've been updated, though🤔...
