### ISSUE TITLE
POST /models/ calls GET /models method while POST /models works properly

### ISSUE THREAD

**Issue by AntwaneB** [laravel/framework#16534]
- Laravel Version: 5.3.21
- PHP Version: 7.0.0
- Database Driver & Version: MySQL 5.7.9

### Description:

_Before describing the issue, I just want to say that I'm not sure if this should be posted here since it seems related to the Router and I believe it's a Symfony package (not sure tho) and it might also be a normal behavior, but it seems weird anyway. Sorry if it doesn't belong here._

If you have a route `GET /models` that calls `ModelController@index` and a route `POST /models` that calls `ModelController@store` and execute a `POST` request on `/models/`, the method that will be called is `ModelController@index` and not `ModelController@store`.

But, if you execute a `POST` request on `/models` (without the trailing `/`), it will properly call `ModelController@store`.

The issue is also present if you use a resource controller, and it is also present without controller by directly using anonymous functions. I have only tested it for routes in `api.php`.

### Steps To Reproduce:

Register the following routes in `routes/api.php`:

```
Route::get('/test', function(){
	return "index";
});

Route::post('/test', function() {
	return "store";
});
```

Try to make a `POST` request to `/test/`, the result will be "index", while a `POST` request to `/test` will return "store".

**Comment by CurosMJ** [comment]
Can't recreate this issue in the unit tests. Are you sure this is not browser cache or other problem? How do you make POST requests? curl, postman ?

**Comment by AntwaneB** [comment]
I had the issue with Postman but I cannot reproduce it with CURL either.

The issue seems to be that Postman follows the redirect from `/test/` to `/test` but does not keep the verb and changes it to a `GET`.

I will forward the problem to Postman.

Thank you :)

**Comment by kamui545** [comment]
Hey, I remember having the same issue, I did not remember until you mentioned Postman.

This may be due to a redirection. Maybe you have a www/non-www redirect or http/https, something like that and it fallbacks to the GET method.

https://github.com/postmanlabs/postman-app-support/issues/710

**Comment by AntwaneB** [comment]
Yes, this is indeed the issue, Laravel sends a 301 redirecting `/test/` to `/test`, I was able to see it when making the request with CURL:

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="http://localhost/api/test">here</a>.</p>
<hr>
<address>Apache/2.4.17 (Win64) PHP/7.0.0 Server at localhost Port 80</address>
</body></html>
```

**Comment by sisve** [comment]
A HTTP 301 (permanent) or 302 (temporary) redirect may change a POST to a GET (all browsers I know of does this). Use HTTP 308 (permanent) or 307 (temporary) redirects if you want to keep the HTTP method in the redirection.
