### ISSUE TITLE
CookieSession - Cannot put binary value in it else the session data is lost

### ISSUE THREAD

**Issue by gervye** [laravel/framework#16536]
- Laravel Version: 5.3.24
- PHP Version: 7.0.13

### Description:
Hello, (french speaking guy from Belgium here, sorry for my english)

I use UUIDs (BINARY(16)) as user IDs. And I store sessions in cookies.
Everything was ok with laravel 5.2. 

In Laravel 5.3 the Auth login does not work anymore with cookie sessions. But it works well with file sessions. And it works well with encrypted cookie sessions too.

So, I searched in the code and I see that between 5.2 and 5.3 there is a change in the  Illuminate\Session\CookieSessionHandler.php file.
V5.2:
```
public function write($sessionId, $data)
{
        $this->cookie->queue($sessionId, $data, $this->minutes);
}
```

V5.3:

```
public function write($sessionId, $data)
{
        $this->cookie->queue($sessionId, json_encode([
            'data' => $data,
            'expires' => Carbon::now()->addMinutes($this->minutes)->getTimestamp(),
        ]), $this->minutes);
        return true;
}
```
And, as said in the PHP.net doc : "**json_encode($binary) problem: it results in an empty string "" without error.**" 

See that the change between 5.2 and 5.3 contains a "json_encode" command. So  the cookie will store an empty string (no data anymore) if the session data contains a binary item (like a UUID).

It is recommanded to use utf8_encode first:

```
    $data = 'éáíúűóüöäÍÓ';
    $json = json_encode( utf8_encode($data) );

    // [..]

    $data = utf8_decode( json_decode($json) );

```

Regards,
Emmanuel Gervy

**Comment by vlakoff** [comment]
You should not UTF8-encode binary data, that's nonsense.
The comment on php.net is wrong. Use [base64](http://php.net/manual/en/function.base64-encode.php) instead.

Also refs https://github.com/laravel/framework/commit/453f504c449af9aa77b8b5a13fb065a7d7f06952

**Comment by gervye** [comment]
Hum, indeed, you are right. I put too much trust on php.net comments. :-)

But in any case I cannot fix the problem in my code as the user ID is put in the session by the Laravel code that manages Auth sessions.
Laravel automatically uses the key that is defined in my User model. Which is a UUID (BINARY(16)).

**Comment by lucasff** [comment]
My input is that I have the same problem. Say in a middleware that creates an arbitrary UUID using `Uuid` package and tries to save this UUID in the user session, I have as a result an always regenerating UUID. This was not happening on Laravel 5.2. Also is seems to have a strong influence over `EncryptCookies` middleware.

**Comment by iwex** [comment]
@gervye try to add accessors/mutators to your User model
```php
public function setIdAttribute($value)
    {
        $this->attributes['id'] = hex2bin(str_replace('-', '', $value));
    }

    public function getIdAttribute($value)
    {
        return bin2hex($value);
    }
```

to read - https://gist.github.com/ratiw/f528c13a8c69c06d9cfd

@taylorotwell can be closed, I guess

**Comment by DCzajkowski** [comment]
Seems it can be closed.
