### ISSUE TITLE
Redis connection failure causes an exception storm into the log file and does not kill the worker.

### ISSUE THREAD

**Issue by cooperaj** [laravel/framework#16537]
- Laravel Version: 5.2.45
- PHP Version: 7.0.12
- Database Driver & Version:
Redis (predis 1.1.1)

### Description:
When a Redis connection fails (server goes down, container migration etc) a daemon worker continues to try to connect to the original IP address. This fails and an Exception is thrown complaining about a server not being available at this address. Rather than failing it exits the task and returns to the while loop, whereupon it tries again unsuccessfully. It continues to do this until manually killed by a sysadmin. 

If the daemon were to die (and consequently be restarted by supervisor or the container orchestration) it would be given a new address to try, and would therefore work. I realise this is probably specific to our implementation but the worker should not try infinitely to connect. Before hard log rotation was introduced to our containers this error caused the hard drive to be filled overnight (all 50GB of it) on three separate container hosts. Although now we don't have the space filling issue we do find that our workers occasionally stop working on jobs.

It looks like #13682 reported a similar issue and a potential fix.

### Steps To Reproduce:
Use Redis as a Queue driver.
Have Redis stop or failover to a slave whilst a worker is running.
Watch the worker log the same exception ad-infinitum.

**Comment by themsaid** [comment]
Please upgrade to 5.3, 5.2 is not supported anymore.

**Comment by maxbrokman** [comment]
@themsaid this is not a 5.2 specific issue and will still cause problems on 5.3

**Comment by themsaid** [comment]
@maxbrokman do you have any suggestions?

**Comment by maxbrokman** [comment]
@themsaid I'm having a headscratch at the moment and will maybe open a new issue this afternoon with a fix outlined.

**Comment by themsaid** [comment]
if you have a fix it's better that you do a PR rather than open an issue, it's better that we discuss implementation :)
