### ISSUE TITLE
Twig thinks Builder attributes are functions

### ISSUE THREAD

**Issue by kevinburke** [laravel/framework#16530]
- Laravel Version: 5.3.23
- PHP Version: 7.0.13
- Database Driver & Version: Postgres, 9.6 (don't think this matters)

### Description:

This has been raised previously as #9644 and #8366; I was a little confused reading through those about the suggested solution, and I'm hoping to get a definitive answer. I'm trying to do something like this:

```php
$member = Member::find(1);
$this->view->render($response, 'template.html', ['member' => $member]);
```

where the template is

```
{% if member.email %}
{{ member.email }}
{% else %}
No email
{% endif %}
```

If `member.email` is null, I get the following stack trace:

```
Type: Twig_Error_Runtime
Message: An exception has been thrown during the rendering of a template ("Call to undefined method Illuminate\Database\Query\Builder::email()") in "template.html" at line 36.
File: /path/to/project/vendor/twig/twig/lib/Twig/Template.php
Line: 443
```

It seems to want to call `$member->email()` as a function, instead of accessing it as a property. Here are the solutions I've tried:

1. `{% if member.email is defined %}` or `{% if member.email is not null %}` - Both throw the same stack trace.
2. @taylorotwell suggested `array_key_exists` in #9644, but I don't have access to this from Twig?
3. I could override `__isset` in each Model ? I'm not amazingly familiar with PHP, the consequences of doing so or the behavior change. 
4. This was suggested: https://github.com/laravel-auto-presenter/laravel-auto-presenter. It's not clear, though, which parts of that I need - is it enough to implement `$fillable`? or do I need to add `implements Presenter` and figure that out, as well?
5. I suppose I could also just copy everything manually into an object, though this seems cumbersome.

**Comment by themsaid** [comment]
In 5.3 we call array_key_exists already: https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Eloquent/Model.php#L2612

I'm not sure how Twig works, can you check how `member.email` is compiled? does it call `$member->email` or what?

**Comment by kevinburke** [comment]
I'm not sure - I'll try to look it up

**Comment by themsaid** [comment]
@kevinburke any news?

**Comment by kevinburke** [comment]
Sorry - I'm not super sure how to check how templates are compiled, I'll try again on Monday.

**Comment by themsaid** [comment]
Please continue on the forums, Twig is not supported by default in Laravel and thus all Twig related issues shouldn't be discussed in laravel's core repository.

On the forums you'll find many others who use Twig that are able to help you.

Thanks :)
