### ISSUE TITLE
Add resourcePath method to Foundation/Application.php

### ISSUE THREAD

**Issue by sijad** [laravel/framework#16549]
`illuminate/support` [uses this method](https://github.com/illuminate/support/blob/master/ServiceProvider.php#L84) to allow override third-party views, but it's not part of application implement which is`Foundation/Application.php`

**Comment by felipsmartins** [comment]
What you want to do, specifically?

**Comment by themsaid** [comment]
@sijad yes share more details please.

**Comment by GrahamCampbell** [comment]
All the path methods are omitted from the application contract by design. I personally think we should get rid of the application contract tbh, and instead have a few interfaces that it implements.
