### ISSUE TITLE
An alias (traitBoot) was defined for method boot(), but this method does not exist

### ISSUE THREAD

**Issue by ssuhat** [laravel/framework#16548]
- Laravel Version: 5.3.24
- PHP Version: 7.0
- Database Driver & Version: Maria DB 10.1

### Description:
Failed on set alias after upgrading to latest laravel

### Steps To Reproduce:
Before I update to 5.3.24 (from 5.3.22) all my model is working perfectly. After upgrade it now everything is broken. Here is my code:

    class Merchant extends Model
    {
        use UuidModelTrait, Sluggable {
            boot as traitBoot;
        }

        protected static function boot()
        {
            self::traitBoot();

            static::addGlobalScope('follows_count', function (Builder $builder) {
                $builder->withCount('follows');
            });
         }
     }

Any changes I should make after upgrade to 5.3.24?. I read the changelog but seems like it doesn't have a problem with my current model.

**Comment by themsaid** [comment]
> everything is broken

Please share more details, exceptions you receive with full stack trace please.

**Comment by ssuhat** [comment]
@themsaid hi. looks like the eloquent-uuid package make this broke after last update. will close this.
