### ISSUE TITLE
Force index for join in Query Builder

### ISSUE THREAD

**Issue by sredXNY** [laravel/framework#16542]
Hey there! I'm looking for a way to use `FORCE INDEX FOR JOIN` clause using the Query Builder,

Basically, this is a part of the native SQL that I need to implement:
`
LEFT JOIN myTable AS t FORCE INDEX FOR JOIN (myindex) ON (myconditions)`

By now, I have the main structure of the SQL Query but now I want to add that clause. How can I achieve this? thanks

**Comment by GrahamCampbell** [comment]
Please direct questions to the forums.
