### ISSUE TITLE
[4.2.22] Errors like a "Call to undefined function" is not logged in storage/logs.

### ISSUE THREAD

**Issue by hoRacy** [laravel/framework#16554]
- Laravel Version: 4.2.22
- PHP Version: 7.0.12
- Database Driver & Version:
mariaDb 10.1.9

### Description:
Errors like a "Call to undefined function" is not logged in storage/logs.
Everything works fine on php 5.*

### Steps To Reproduce:
1. go to routes.php
2. Add for example:
xxxx::fasfasfasfas();
to run unexisting function.
3. run laravel any page
4. go to storage/logs and check that nothing is logged.

**Comment by GrahamCampbell** [comment]
Depends how early in the bootstrap process this is. Not necessarily a bug.
