### ISSUE TITLE
Laravel Authentication auth() logout route http method issue.

### ISSUE THREAD

**Issue by ahmedmaazin** [laravel/framework#16556]
- Laravel Version: 5.3.24
- PHP Version: 7.0.11
- Database Driver & Version: MySQL 5.7.15

### Description:
Laravel Authentication auth() logout route http method issue. Currently it is HTTP POST method, which leads to MethodNotAllowedHttpException. It is calling the /logout on click from the browser, change the HTTP GET method, it works.

### Steps To Reproduce:
laravel new someapp
php artisan make:auth
-- then setup mysql, migrate users, seed db and log in with the credentials.
-- log in
-- log out
-- boom crash.

<img width="985" alt="screen shot 2016-11-26 at 07 31 11" src="https://cloud.githubusercontent.com/assets/4073159/20637360/8e86f56c-b3ab-11e6-9476-7ade45ffdc71.png">

<img width="665" alt="screen shot 2016-11-26 at 07 40 48" src="https://cloud.githubusercontent.com/assets/4073159/20637371/bd62be98-b3ab-11e6-9612-ff28c0e9f74b.png">

**Comment by crynobone** [comment]
`/logout` route is supposed to be `POST`. Even the default stub using `POST` now.

https://github.com/laravel/framework/blob/5.3/src/Illuminate/Auth/Console/stubs/make/views/layouts/app.stub#L61-L73

**Comment by sisve** [comment]
Anyone can call a GET route in any hidden way. I can add a <img src="http://other-laravel-site/logout"> and have you logged out if you use GET. That's why you do not use GET for logouts. A POST requires, in combination with the CSRF token, a form that only your server has the power to render.
