### ISSUE TITLE
Empty session using response()

### ISSUE THREAD

**Issue by dann95** [laravel/framework#16555]
- Laravel Version: Laravel Framework version 5.3.18

- PHP Version: PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )

- Database Driver & Version: mysql  Ver 14.14 Distrib 5.7.16, for Linux (x86_64) using  EditLine wrapper

### Description:
I know the implementation of session (Helpers and Factory) depends on middleware, more specific the web:
```php
    protected $middlewareGroups = [
        'web' => [
            \Nptunnel\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \Nptunnel\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
            \Nptunnel\Http\Middleware\TranslateMiddleware::class, //ignore this
            \Nptunnel\Http\Middleware\ReferenceMiddleware::class, //ignore this
        ],

        'api' => [
            'throttle:60,1',
            'bindings',
        ],
    ];
```

Today im trying to implement a 404 error using the default template of my application, so i changed the Exception Handler 

```php
    /**
     * Render an exception into an HTTP response.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Exception  $exception
     * @return \Illuminate\Http\Response
     */
    public function render($request, Exception $exception)
    {
        if($exception instanceof  NotFoundHttpException){
            return response()->view('errors.404', [], 404);
        }
        return parent::render($request, $exception);
    }
```
Ok, so that must stop propagation of app and return a response with the view errors/404.blade.php, but in my 404.blade.php i extend the templates/default.blade.php that uses the function "session()" for some things, example:
```blade
<img src="{{ config('lang.flags')[session()->get('lang')]['img'] }}">
```

but any use of session() helper on view file returns "null", and i didnt find any way to attach session for response();

### Steps To Reproduce:

1. Create a blade view and use session() for get a value from session
2. Render this view outside of a controller, using response()
3. Watch that any session() call returns an null value.

i guess that all, sorry for bad english and i hope all this helps to describe this problem.

thanks, Daniel

**Comment by dann95** [comment]
Also if i comment that line of return a response (in case of NotFoundHttpException) 
```php
        if($exception instanceof  NotFoundHttpException){
            return response()->view('errors.404', [], 404);
        }
``` 
and just give a 404.blade.php that extends default.blade.php, the same.

**Comment by GrahamCampbell** [comment]
This is the expected error. Any error 404s that occur due to missmatched routes won't start the session.

**Comment by dann95** [comment]
Yeah @GrahamCampbell , but how is possible to use session into this situation? as i explain my template needs some Session information, no way to attach the session to a response() ?

**Comment by dann95** [comment]
Cause in this specific situation, for a friendly user interface i must use the same layout, but layout needs session information :disappointed:

**Comment by dann95** [comment]
@taylorotwell No way to handle this exception in a frendly way to user displaying a layout with session data?

**Comment by yooouuri** [comment]
Same issue over here,

The result of ```var_dump($request->session->all()``` is null after using a redirect or response...

Example:
After my login method I do a ```return response()->redirectToAction('...')``` and the session is just gone..

**Comment by dann95** [comment]
@yooouuri you can solve it by transforming this:
```php
    /**
     * The application's global HTTP middleware stack.
     *
     * These middleware are run during every request to your application.
     *
     * @var array
     */
    protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
    ];
    /**
     * The application's route middleware groups.
     *
     * @var array
     */
    protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],
        'api' => [
            'throttle:60,1',
            'bindings',
        ],
    ];
```
into this:
```php
    /**
     * The application's global HTTP middleware stack.
     *
     * These middleware are run during every request to your application.
     *
     * @var array
     */
    protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        \Illuminate\Session\Middleware\StartSession::class,
        \Illuminate\View\Middleware\ShareErrorsFromSession::class,
    ];
    /**
     * The application's route middleware groups.
     *
     * @var array
     */
    protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],
        'api' => [
            'throttle:60,1',
            'bindings',
        ],
    ];
```

adding Session middleware as Application, and not route.

but my really question for @taylorotwell and @GrahamCampbell is why session have to only be booted by a middleware, why not create another method to handle exceptions like 404, and etc to be able to use Session, lets have in mind a quick example, lets say that i want to handle that exception making a stats about Who tried to access, and which page tried to access, it seems a little weird transform a route middleware into global, so thats my ask, if is not possible create another way to get it.

**Comment by yooouuri** [comment]
@dann95 do i need to perform a command or something? But it still doesn't work and the session is null.

**Comment by dann95** [comment]
@yooouuri 
Session is started by following middleware:
```php
\Illuminate\Session\Middleware\StartSession::class,
```
remove it from $middlewareGroups web and put it into $middleware, to make it global, and not just of group web, so alaways when application is executed, it will be run.

**Comment by dann95** [comment]
when you use response method, it is not hiting any Route, and so never will execute the session middleware =/
