### ISSUE TITLE
minor issue regarding Bitbucket

### ISSUE THREAD

**Issue by Quezler** [laravel/framework#16553]
- Laravel Version: 5.3+

In the bitbucket readme.md preview html is not supported

![screen shot 2016-11-25 at 16 56 06](https://cloud.githubusercontent.com/assets/3179271/20630240/21557584-b330-11e6-9caf-49c8c05188fa.png)

Not that anyone has died because of this, but I'm just making sure you guys are aware of this 🎁

**Comment by Quezler** [comment]
Commit that changed it: 172f9d63fa9787ad785f2e8358c952b001e5c893

**Comment by themsaid** [comment]
Well laravel is hosted on GitHub, so I now reason why we should check other providers. But thanks for letting us know :)

**Comment by Quezler** [comment]
The main audience it concerns is people hosting their brand new Laravel project there (or never updated the readme.md file), and are greeted by the html @themsaid

**Comment by sisve** [comment]
Shouldn't said audience replace the readme.md with their own content, explaining their own application?
