### ISSUE TITLE
Eloquent orm strong dependency

### ISSUE THREAD

**Issue by Cyrille37** [laravel/framework#16566]
- Laravel Version: 5.3
- PHP Version: n/a
- Database Driver & Version: n/a

### Description:

Is there a plan to make Laravel orm independant like thrid party packages can be used with any orm, like doctrine ?
Thanks

**Comment by sisve** [comment]
There is already a package for running Doctrine with Laravel. Are you asking about this, or how to use Eloquent in other projects? http://www.laraveldoctrine.org/

**Comment by nunomaduro** [comment]
I think the question was: Is possible to use Laravel ORM outside of Laravel. If that was the question, that is already possible. Checkout the following video in Laracast: 

[https://laracasts.com/lessons/how-to-use-eloquent-outside-of-laravel](https://laracasts.com/lessons/how-to-use-eloquent-outside-of-laravel)

**Comment by Cyrille37** [comment]
@nunomaduro No.

@sisve Yes, this package is the origin of my question. I would like to use laraveldoctrine, but I'm afraid that many Laravel's packages won't work, like Passeport, because of orm strong dependency.

**Comment by GrahamCampbell** [comment]
It is possible to use it outside. I do.

**Comment by sisve** [comment]
@GrahamCampbell I believe you answered the question that wasn't asked.

**Comment by GrahamCampbell** [comment]
You can already use other ORMs in laravel. Just because eloquent is included in the core, it doesn 't mean you have to use it.

**Comment by Cyrille37** [comment]
@GrahamCampbell Not shure ... I can read that when using [Laraveldoctrine](http://www.laraveldoctrine.org/) other Lavarel third party packages will use Eloquent nor LaravelDoctrine that can be a source of problems.
