### ISSUE TITLE
[5.2] QueryException when using database session driver

### ISSUE THREAD

**Issue by drawmyattention** [laravel/framework#16569]
- Laravel Version: 5.2.45
- PHP Version: 7.0.8
- Database Driver & Version: MySQL 5.7.12

### Description:

When using the database session driver, I'm frequently getting QueryExceptions thrown because a duplicate session id is trying to be inserted. A simple check to see if the session id exists in the database, before inserting would fix this. Alternatively, a better way of the id being generated would remove the need for an extra query.

I've seen this issue in my logs a few hundred times over the past week so it seems to be significant.

### Steps To Reproduce:

N/a

**Comment by GrahamCampbell** [comment]
Session driver was refactored in 5.3. 5.2 isn't supported, sorry.

**Comment by drawmyattention** [comment]
There's no real change in the code for DatabaseSessionHandler between 5.2 and 5.3. See [the diff](https://www.diffchecker.com/zaR2J78y) (only small docblock changes, and rather than using ```time()```, the new code uses ```Carbon``` to get a timestamp.

In that case, this bug applies equally to 5.3 and should be reopened.

**Comment by themsaid** [comment]
@drawmyattention We have this issue reported already: https://github.com/laravel/framework/issues/9251

**Comment by drawmyattention** [comment]
Thanks @themsaid I'll pick up from that thread. Eek, the bug's over a year old. I'll see if I can figure out the issue and submit a PR.
