### ISSUE TITLE
all() eloquent function not use setConnection function 

### ISSUE THREAD

**Issue by alirezavalipour** [laravel/framework#16562]
- Laravel Version: 5.3.*
- PHP Version:5.6
- Database Driver & Version: mysql and sqlite

### Description:
in eloquent object when you use for example setConnection('sqlite') and use all() helper to get all result 
it returns collection of mysql database instead of sqlite

**Comment by GrahamCampbell** [comment]
The all function is static, not instance.

**Comment by marktopper** [comment]
Use `get` instead for this.
