### ISSUE TITLE
Changing app name can leave app / artisan in a non-working state

### ISSUE THREAD

**Issue by jimbojsb** [laravel/framework#16575]
- Laravel Version: 5.3.x
- PHP Version: 7.0.x

### Description:
If you delete the database/ folder from a Laravel app created by using `composer create-project laravel/laravel` (for any reason, but lets assume it's because your app has no DB), later using `artisan app:name MyApp` can't update the database factory namespaces. This causes the command to fail, which means the composer calls to regenerate autoloaders never get run, thus leaving your app in a non-working state. Manually running composer can be used to fix this issue, but it seems reasonable that this should fail more gracefully.

**Comment by themsaid** [comment]
What do you suggest?
