### ISSUE TITLE
failed Method not got any exception

### ISSUE THREAD

**Issue by IgorDePaula** [laravel/framework#16572]
- Laravel Version: 5.3
- PHP Version: 5.6
- Database Driver & Version: mysql - 5.6

### Description:
I have a job that execut a guzzle request. In a moment this request can fails. I tried got this fail on failed method from job, but all exceptions captured was from laravel framework, and dont from guzzle. (Like descripted on docs)

### Steps To Reproduce:
Create a job, on his handler method, do a guzzle request, and this request need fails, put on this classe too the failed method receiving an exception. You will see that guzzle exception dont will captured by failed method, need do try catch on handler method.

**Comment by themsaid** [comment]
It actually calls the method on any exception, just make sure the max attempts are exceeded because the method is not called unless the max. attempts are consumed.

**Comment by IgorDePaula** [comment]
You tried?

**Comment by themsaid** [comment]
No, but the code catches all exceptions, not only laravel specific exceptions.

**Comment by IgorDePaula** [comment]
If you not tried, your response is not valid.

**Comment by themsaid** [comment]
What exactly the exception that doesn't trigger the method?

**Comment by IgorDePaula** [comment]
```Description:

I have a job that execut a guzzle request. In a moment this request can fails. I tried got this fail on failed method from job, but all exceptions captured was from laravel framework, and dont from guzzle. (Like descripted on docs)
Steps To Reproduce:

Create a job, on his handler method, do a guzzle request, and this request need fails, put on this classe too the failed method receiving an exception. You will see that guzzle exception dont will captured by failed method, need do try catch on handler method.```

**Comment by themsaid** [comment]
Please share the exception class, what exception is thrown?

**Comment by IgorDePaula** [comment]
My friend, the exception is of guzzle, I trying access to an api by authentication, where a moment can fails, I want capture this fails...

**Comment by IgorDePaula** [comment]
https://gist.github.com/IgorDePaula/7b0b6af335e095ed015504f37b07c67f

**Comment by themsaid** [comment]
Using this, the method gets called successfully.

```
class TestJob implements ShouldQueue
{
    use InteractsWithQueue, Queueable, SerializesModels;
    
    public function handle()
    {
        (new Client())->request('GET', 'https://api.github.com/user', [
            'auth' => ['user', 'pass']
        ]);
    }

    public function failed($exception)
    {
        Log::info('failed');
    }
}
```

Please use a simple `Log::info('failed');` to test since the code inside failed might be failing itself giving you the impression the method isn't being called.

**Comment by IgorDePaula** [comment]
Ok, closed. Yesteday, not work.

**Comment by IgorDePaula** [comment]
I doing new tests, and really, he not capture any exceptions

**Comment by IgorDePaula** [comment]
The jobs are inserting into failed_jobs table, but not in failed method from class
