### ISSUE TITLE
Namespace received from composer.json in \Illuminate\Foundation\Application

### ISSUE THREAD

**Issue by HDsign** [laravel/framework#16570]
- Laravel Version: 5.3.*
- PHP Version: 7.0.12

### Description:
I have a problem where the composer.json file is not placed in the same folder as the project it self.

My folder structure:

```
/composer.json
/lara/app/*
/lara/bootstrap/*
/lara/config/*
...
```

So when the `getNamespace()` methode is used on the `\Illumintate\Foundation\Application` class it will not find my composer.json file:

```php
$composer = json_decode(file_get_contents(base_path('composer.json')), true);

foreach ((array) data_get($composer, 'autoload.psr-4') as $namespace => $path) {
    foreach ((array) $path as $pathChoice) {
        if (realpath(app_path()) == realpath(base_path().'/'.$pathChoice)) {
            return $this->namespace = $namespace;
        }
    }
}
```

This can of course be solved easily by adding a `setNamespace` methode to the application class or perhaps add the possibility to add it to the config files. Right now the only way to fix this without changing everything drastically is by adding a `composer.json` file to the 'lara' folder.

**Comment by themsaid** [comment]
Feel free to propose a PR.
