### ISSUE TITLE
Explicit Route Binding and old() validation on the create method

### ISSUE THREAD

**Issue by 760524mkfa00** [laravel/framework#16574]
- Laravel Version: 5.3.24
- PHP Version: 7.0
- Database Driver & Version: MySql 5.7.16

### Description:
When using Route Model Binding it is unable to find the default value. To over come this problem I am having to use the null value in the forms value.

### Steps To Reproduce:
Set up Explicit Route Binding
add  {{ old($key,  $default) }} to a forms value

On the create method it cannot find the $default value as nothing is passed.

I have found using the following fixes my issue
value="{{ old('address', $employee->address ?? null) }}"

However, can it be part for the old function to check for $default?

**Comment by themsaid** [comment]
What is `$default`? Where do you define this variable and how?

**Comment by 760524mkfa00** [comment]
Using route model binding, I am sharing the same form for creating an employee and editing an employee. I also want the functionality of it returning the Old Values (the values entered on create) when there is a validation error, so the user does not have to type all their information again.

To do this I use the function value="{{ old('key') }}" as part of the input boxes element, where the 'key' identifies the name of the input field, i.e. first_name, address, postal_code etc. 

This all works really well for the create employee form, however, I also want to display the values from the database on the edit employee form, we can do this by adding a second value to the value="{{ old('key', 'database value') }}" to the input box.

My form would look like this:
```
<input type="text" class="form-control" id="last_name" name="last_name" placeholder="Last name..." value="{{ old('last_name', $employee->last_name) }}" required>
<input type="text" class="form-control" id="address" name="address" placeholder="Address..." value="{{ old('address', $employee->address) }}">
<input type="text" class="form-control" id="postal_code" name="postal_code" placeholder="Postal Code..." value="{{ old('postal_code', $employee->postal_code) }}">
```

This works great on the Edit employee form, however, when I open create employee form it gives me an undefined variable $employee because the employee object does not get passed to the create form.

To fix the problem I alter
`value="{{ old('postal_code', $employee->postal_code) }}"`
to
`value="{{ old('postal_code', $employee->postal_code ?? null) }}"`
for all my input boxes.

I'm not sure if this is a bug per se, but should this not be handled within the old() function? Or, is this more a feature request? Or, is this something that can be added to the docs?

**Comment by themsaid** [comment]
It makes sense yeah, you're simply passing  a variable that isn't defined, `value="{{ old('postal_code', $employee->postal_code ?? null) }}"` is the correct way :)
