### ISSUE TITLE
fromJSON(): reverse of Eloquent model's toJSON() missing

### ISSUE THREAD

**Issue by andrisi** [laravel/framework#16586]
- Laravel Version: 5.3

### Description:

The reverse of toJSON() is missing on Eloquent models. The toJSON() method works well when serialising models with relations to JSON, but there is no method to do the opposite, recreate a model, with it's relations from JSON. The create method seems to work for flat arrays (single records) only. It would be very helpful to have this, and then in turn be able to save it to the db.

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.

Thank you :)

**Comment by andrisi** [comment]
Thanks, done: https://github.com/laravel/internals/issues/321 - will use that from now on.
