### ISSUE TITLE
Awkward error reporting by laravel

### ISSUE THREAD

**Issue by deep88** [laravel/framework#16588]
- Laravel Version: #5.3#.#
- PHP Version: 7.0
- Database Driver & Version: Mysql

### Description:
can anybody explain this i cannot find place where role class is being called

`[2016-11-29 12:51:56] local.ERROR: ReflectionException: Class role does not exist in G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Container\Container.php:749
Stack trace:
#0 G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Container\Container.php(749): ReflectionClass->__construct('role')
#1 G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Container\Container.php(644): Illuminate\Container\Container->build('role', Array)
#2 G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(709): Illuminate\Container\Container->make('role', Array)
#3 G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(127): Illuminate\Foundation\Application->make('role')
#4 G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#5 G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#6 G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(137): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#7 G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#8 G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(137): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#10 G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(137): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#13 G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(137): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(137): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(137): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Routing\Router.php(644): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#25 G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Routing\Router.php(618): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#26 G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Routing\Router.php(596): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#27 G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(268): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#28 G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#29 G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(137): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(150): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#34 G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(117): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#35 G:\Dropbox\websites\quickadmin\public\index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#36 {main}  
[2016-11-29 12:51:56] local.ERROR: ReflectionException: Class role does not exist in G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Container\Container.php:749
Stack trace:
#0 G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Container\Container.php(749): ReflectionClass->__construct('role')
#1 G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Container\Container.php(644): Illuminate\Container\Container->build('role', Array)
#2 G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(709): Illuminate\Container\Container->make('role', Array)
#3 G:\Dropbox\websites\quickadmin\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(174): Illuminate\Foundation\Application->make('role')
#4 G:\Dropbox\websites\quickadmin\public\index.php(58): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#5 {main}  `

**Comment by themsaid** [comment]
VERY hard to tell without being able to look at your code :)

Please use the forums to post questions as this repo is for bug reporting only.

Thanks :)
