### ISSUE TITLE
Model.php $exists property

### ISSUE THREAD

**Issue by mavsan** [laravel/framework#16597]
- Laravel Version: 5.3.25
- PHP Version: 5.6
- Database Driver & Version: MySql 5.5

### Description:
Illuminate/Database/Eloquent/Model.php propefty $exists is public. Anyone from outside the model can change the property.

**Comment by themsaid** [comment]
feel free to open a PR on master since it's a breaking change, however I don't really think we need to change this.

**Comment by mavsan** [comment]
I am developing a library and I have to be sure that the model is not just been created, and such a record does exist in the database.
~~~
$model = new User();
$model->exists = true;
function someMethod($model)
{
      if($model->exists)
      {
      // wrong!
      }
}
~~~
