### ISSUE TITLE
[5.3] 'Sometimes‘ validation rule doesn't have an error message

### ISSUE THREAD

**Issue by mbaeuerle** [laravel/framework#16609]
- Laravel Version: 5.3.24
- PHP Version: 7.0.13
- Database Driver & Version: -

### Description:
There is no way to specify a custom error message for the `sometimes` rule. I understand that technically the field is required, but in this case it doesn't make sense to use the message from `required` because for the user the field is not required, it just has to match the date format.

I see two possibilities: 
Either the `date` validation has to be executed although the `field1` contains only whitespace 
 or there should be a `sometimes` error message which can be customized to explain that the issue lies in an empty field / field containing only whitespace 

### Steps To Reproduce:

If I have a validation rule like this: 
```
'field1' => 'sometimes|required|date`
```
and someone just sends whitespace:
```
'field1': '   '
```
the `required` error message is shown:
```
"The field1 field is required."
```

**Comment by themsaid** [comment]
Sometimes is not actually a rule, it's just a flag for the Validator to skip validation if the key doesn't exist in the input array.

**Comment by mbaeuerle** [comment]
Technically that may be true, but the error message is nevertheless not right in the given case. So is there another way of making fields optional wich behaves properly?

**Comment by themsaid** [comment]
Do you consider empty space as a valid value?

**Comment by mbaeuerle** [comment]
No, surely there should be an error message. But the contents of the message are not right.
The shown error message suggests, that field1 is required, but it is not.
So the error message should rather be something like:
```
"The field1 has spaces in it"
```
or even better:
```
"The field1 is no valid date"
```
Which I only can do when it's possible to customize the error message for `sometimes`

**Comment by fernandobandeira** [comment]
Nops because the validation message that is shown is for the field1.required, so even if you could customize the error message for ``` sometimes ``` it wouldn't be the one used in this case...

You can customize this message for this specific field and rule:
Add this to your lang file:

```php
'custom'               => [
        'field1' => [
            'required' => 'The field1 is no valid date',
        ],
    ],
```

This should solve your issue...

**Comment by mbaeuerle** [comment]
Well thanks, I see it's not easy to get the behavior I want. 
The problem is, that I have quite some PATCH routes where obviously none of the fields is required. So customizing the error message for each and every attribute is not feasible. 

I wonder if there are no other people facing the same problem, because it should pop up as soon as implementing true PATCH routes where more than one attribute can be changed.

**Comment by mbaeuerle** [comment]
As there is no further progress, it seems I have to stick to the rather odd error message of required. Hopefully some day there will be a replacement for 'sometimes' which better suits the needs of PATCH routes.
