### ISSUE TITLE
Validation custom attributes dot-notation

### ISSUE THREAD

**Issue by sweet-greg** [laravel/framework#16615]
- Laravel Version: 5.3.23
- PHP Version: 7.0

### Description:
Using dot-notation in validation.php Custom Validation Attributes does not work.
ex: `'attributes.mailchimp_list_id' => 'Mailchimp list',`

Dot-notation does work for Custom Validation Language Lines and all other lang files.
This seems like a bug to me.

**Comment by themsaid** [comment]
$v = validator([
        'attributes' => [
            'mailchimp_list_id' => null
        ]
    ], ['attributes.mailchimp_list_id' => 'required']);

    $v->passes();

    'attributes' => [
        'attributes.mailchimp_list_id' => 'Mailchimp list',
    ],

Works fine, please share more details and steps to reproduce.

**Comment by sweet-greg** [comment]
I'm sorry, I mean when using a FormRequest

    <?php namespace App\Http\Requests;
    use Illuminate\Foundation\Http\FormRequest;
    class MailchimpCampaignRequest extends FormRequest {
        /**
         * Determine if the user is authorized to make this request.
         *
         * @return bool
         */
        public function authorize() {
            return true;
        }
        /**
         * Get the validation rules that apply to the request.
         *
         * @return array
         */
        public function rules() {
            return [
                'mailchimp_list_id' => 'required',
            ];
        }
    }

/lang/en/validation.php

     ...
    /*
    |--------------------------------------------------------------------------
    | Custom Validation Language Lines
    |--------------------------------------------------------------------------
    |
    | Here you may specify custom validation messages for attributes using the
    | convention "attribute.rule" to name the lines. This makes it quick to
    | specify a specific custom language line for a given attribute rule.
    |
    */

    'custom.mailchimp_list_id.required' => 'Mailchimp list is required', // works

    /*
    |--------------------------------------------------------------------------
    | Custom Validation Attributes
    |--------------------------------------------------------------------------
    |
    | The following language lines are used to swap attribute place-holders
    | with something more reader friendly such as E-Mail Address instead
    | of "email". This simply helps us make messages a little cleaner.
    |
    */
    'attributes.mailchimp_list_id' => 'Mailchimp list', // does not work
     ...

**Comment by themsaid** [comment]
You need to provide the attributes under the `attributes` key like so:

    'attributes' => [
        'attributes.mailchimp_list_id' => 'Mailchimp list',
    ],
