### ISSUE TITLE
Hey guys am I know there's been alot of chatter about using custom tables with laravel auth but here's my issue below, despite there being no email column I and I tried specifying in the post Login its still not working

### ISSUE THREAD

**Issue by NightravenJames** [laravel/framework#16619]
<?php
// heres my `model`
namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /* Table to user_accounts */
    protected $table = 'user_accounts';

    public function getAuthIdentifier() {
      return $this->getKey();
    }

    public function getAuthPassword() {
      return $this->passwd;
    }

    public function getReminderEmail() {
      return $this->email_address;
    }

    public static function validate($data) {
      return Validator::make($data,static::$rules);
    }

//my postLogin

public function postLogin(Request $request)
      {
          $this->validate($request, [
              'useEmail' => 'required|email', 'password' => 'required',
          ]);

          $credentials = $request->only('useEmail', 'password');

          if ($this->auth->attempt($credentials, $request->has('remember')))
          {
              return redirect()->intended($this->redirectPath());
          }

          return redirect($this->loginPath())
              ->withInput($request->only('useEmail', 'remember'))
              ->withErrors([
                  'useEmail' => $this->getFailedLoginMessage(),
              ]);
      }

}

**Comment by themsaid** [comment]
Sorry, but please ask questions on the forum, this repo is for bug reporting only.
