### ISSUE TITLE
touch has no effect on eloquent update method

### ISSUE THREAD

**Issue by Jermim** [laravel/framework#16621]
$user->update(['field' => 'value'], ['touch' => false])

- Laravel Version: 5.3.*
- PHP Version: 7.0.13

**Comment by lagbox** [comment]
What are you expecting to happen, what is happening?

**Comment by bobbybouwmann** [comment]
It will only work when the following check is failing
```
// Illuminate\Database\Eloquent\Model.php@performUpdate
if ($this->timestamps && Arr::get($options, 'touch', true)) {
    $this->updateTimestamps();
}
```
So the code looks good, but somehow it's still updating the timestamps of your model. Am I right?

**Comment by Jermim** [comment]
@bobbybouwmann yeah, setting touch to false should make it avoid updating updated_at column

**Comment by lagbox** [comment]
Can you put a `DB::enableQueryLog()`  before that and a  `dd(DB::getQueryLog())`  after to see what sql is generated?

**Comment by Jermim** [comment]
@lagbox it includes `and updated_at = ?`

**Comment by Jermim** [comment]
in `Model::performUpdate` this is what happens:
`
            $this->setKeysForSaveQuery($query)->update($dirty);
`
so update($dirty) ignores options.

**Comment by lagbox** [comment]
That timestamp is already set before it gets to that update call.  That `update` call you are highlighting there isn't `Model@update` that is the call to the actual builder to do the update, it only takes 1 arg. It has nothing to do with these options.

**Comment by Jermim** [comment]
@lagbox  that's the issue, the query builder adds `updated_at` by calling `$this->addUpdatedAtColumn($values)`

**Comment by lagbox** [comment]
Nice work :) .. Could you try this  `$model->timestamps = false;` before calling `$model->update(..., ['touch' => false]);` and see if it helps.

**Comment by bobbybouwmann** [comment]
Setting `$timestamps` to `false` should not fix this issue, since it's a feature of the update method. If you set the timestamps to false, you basically say you don't have timestamps at all!

**Comment by themsaid** [comment]
Check https://github.com/laravel/framework/issues/13400

This feature is broken and was removed before, however it found its way back somehow but still never works, I opened a PR to remove it again: https://github.com/laravel/framework/pull/16660

Use this instead of `update()` if you want it to work:

```php
$user->timestamps = false;

$user->save();
```

**Comment by lagbox** [comment]
You can still call `update`, `update` is just `fill` and `save`.

**Comment by matrad** [comment]
I can reproduce this behaviour if I use this translation package and make no updates on the main table; only on the translation table.
I added "touches" variable to the translation model, but no update on save.

https://github.com/dimsav/laravel-translatable
