### ISSUE TITLE
[5.3] Method shuffle does not exist

### ISSUE THREAD

**Issue by PheRum** [laravel/framework#16623]
- Laravel Version: #.#.# 5.3.26
- PHP Version: 5.6.27
- Database Driver & Version: 10.1.19-MariaDB - Homebrew 

### Description:
``
Illuminate\Database\QueryException thrown with message "Method shuffle does not exist. (SQL: select * from `users` where `id` = 2 and `remember_token` = t1aJR6RYJH limit 1)"
``

**Comment by sisve** [comment]
There is a [Collection::shuffle](https://laravel.com/api/5.3/Illuminate/Support/Collection.html#method_shuffle), are you attempting to call it? Then `$collection = Model::your()->query()->here()->get()->shuffle()`.
