### ISSUE TITLE
Call to undefined method Illuminate\Database\Schema\Blueprint::string()

### ISSUE THREAD

**Issue by Chintan7027** [laravel/framework#16620]
- Laravel Version: 5.2.45
- PHP Version: 5.6
- Database Driver & Version: Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: 241ae00989d1995ffcbbf63d579943635faf9972 $

### Description:
File `/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php`
Missing function
```
public function string($column, $length = 255)
{
        return $this->addColumn('string', $column, compact('length'));
}

```

### Steps To Reproduce:

`php artisan queue:table`

**Comment by GrahamCampbell** [comment]
Sorry, 5.2 is not supported.
