### ISSUE TITLE
str_slug() and the Hungarian language

### ISSUE THREAD

**Issue by blackfyre** [laravel/framework#16622]
- Laravel Version: 5.2.41 upwards

### Description:
The problem with the Hungarian diacritics that they get transformed wrongly during the slug generation.
`Ö,Ő` gets transformed to `OE` and `ÜŰ` gets transformed to `UE`, while these should be `o` and `u` respectively.
This was introduced in ee8dde1e013960ea65887c3c55e8555cc38a2033 with the `charsArray()` protected function.

**Comment by GrahamCampbell** [comment]
Please submit bug reports to the stringy library. We always used them in the first place, so that change to the chars array would have happened anyway, we just removed the dependency on them, and now directly copy the small part of the codebase we need.

**Comment by blackfyre** [comment]
If some one is looking for a "quick" solution, [voku/Stringy](https://github.com/voku/Stringy)'s methods can be used as a replacement.
```php
$stringy = Stringy\Stringy::create('fö fü fófőfúféfáfű'); 
echo $stringy->toAscii()->dasherize(); // will result in: fo-fu-fofofufefafu
```

**Comment by GrahamCampbell** [comment]
@blackfyre Please send a PR to danielstjules/Stringy, then everyone can get this fix, including Laravel, rather than just fixing this on your own app.

**Comment by blackfyre** [comment]
@GrahamCampbell This is an on-going problem since the 2nd of January, 2016, please see danielstjules/Stringy#116 for the details.

**Comment by GrahamCampbell** [comment]
We need to encourage them to fix it then, for the benefit of everyone.:)

**Comment by GrahamCampbell** [comment]
It doesn't seem like anyone has actually PRed a fix to stringy, unless I missed it?

**Comment by blackfyre** [comment]
Actually, in Daniel's last comment, he said, that he'll do something in the holidays :smile:

**Comment by blackfyre** [comment]
Daniel released a new version of danielstjules/Stringy](https://github.com/danielstjules/Stringy/releases).

**Comment by fernandobandeira** [comment]
I've synced with the new version, check #18974 this shouldn't be a problem anymore on 5.5. 👍
