### ISSUE TITLE
seeJsonStructure cannot properly see structure of empty array

### ISSUE THREAD

**Issue by miklcct** [laravel/framework#16626]
- Laravel Version: 5.3
- PHP Version: 7.0

### Description:
When writing tests with seeJsonStructure, it will try to decode the response even the response exists and is empty.

### Steps To Reproduce:

    class Test extends TestCase
    {
        public function testExample()
        {
            $this->seeJsonStructure(['*' => ['a', 'b', 'c']], []);
        }
    }

### Expected result
The test passes

### Actual result
    1) Test\Test::testExample
    Error: Call to a member function getContent() on null

The problem is in Illuminate\Foundation\Testing\Concerns\MakeHttpRequests::seeJsonStructure:354
`if (! $responseData)` should be changed to `if ($responseData === null)` because the former also matches empty array.

**Comment by srmklive** [comment]
Just tested to verify the issue. Just added a PR for this as per your suggestion.

**Comment by GrahamCampbell** [comment]
Thanks. :)
