### ISSUE TITLE
5.2 remember me not working?) I think it doesn't decrypt the cookie content.

### ISSUE THREAD

**Issue by ekaitzastiz** [laravel/framework#16632]
- Laravel Version: 5.2.45
- PHP Version: 5.6.20
- Session driver: redis

I did a login with remember checked. 

(expire_on_close = false)   lifetime=240, But I understand that I have the remeber_web_xxxxxx cookie set, It should be logged in when I come back next day...  right? But it doesn't keep logged, but I see that cookie is on the browser (expiration date 2021...). 

I dig in to Illuminate\Auth\SessionGuard  I debugged and I don't know why, but cookie value it's setting well, ID.'|'. rememberToken . But when it tries to read next time, cookie format is never valid, because I see that is passing the value encrypted. So It never passes the condition.

I tried to decrypt, and know works!! I am doing something wrong or is there a bug and forget to decrypt? 

```
    protected function getUserByRecaller($recaller)
    {
        $recaller = \Crypt::decrypt($recaller);

        if ($this->validRecaller($recaller) && ! $this->tokenRetrievalAttempted) {
            $this->tokenRetrievalAttempted = true;

            list($id, $token) = explode('|', $recaller, 2);

            \Log::info("bai");
            \Log::info($id);

            $this->viaRemember = ! is_null($user = $this->provider->retrieveByToken($id, $token));

            return $user;
        }
    }
```

**Comment by themsaid** [comment]
Please ask on the forums, also I recommend that you upgrade to 5.3 since 5.2 is not supported anymore.

**Comment by ekaitzastiz** [comment]
Ok. But I asked in laracasts, laravel.io,  in stackoverflow....  and no answers... 

Thank you
