### ISSUE TITLE
[5.3.26] BelongsToMany withCount selects incorrect id.

### ISSUE THREAD

**Issue by cabalopolis** [laravel/framework#16645]
- Laravel Version: 5.3.26
- PHP Version: 7.0.13
- Database Driver & Version: MariaDB-10.1.19

### Description:
With a belongsToMany => belongsToMany, using the Builder::withCount() causes the incorrect `id` to be selected, it appears the `id` from the pivot table is being selected rather than the table itself.

Here are the models:

- **User** (`users`) 
```php
class User extends Model {
   ...
   public function roles() {
      return $this->belongsToMany(Role::class);
   }
   ...
}
```

`users`

| id | name | email |
|---|-------|------|
| 9 | Some Name | name@example.com | 

- **Role** (`roles`)(`role_user`)(`permission_role`)
```php
class Role extends Model {
   ...
   public function permissions() {
      return $this->belongsToMany(Permission::class);
   }
   ...
}
```

`roles`

| id | name | description |
|---|-------|------|
| 2 | Administrator | Some description here | 

`role_user`

| id | role_id | user_id |
|---|--------|--------|
| 4 | 2 | 9 |

`permission_role`

| id | permission_id | role_id |
|---|---------------|--------|
| 12 | 19 | 2 |
| 13 | 20 | 2 |
| 14 | 17 | 2 |
| 15 | 21 | 2 |

- **Permission** (`permissions`)
```php
class Permission extends Model {
   ...
}
```

### Steps To Reproduce:

1. Grab the roles for the user with the permission count.

```php
$roles = $user->roles()->withCount('permissions')->get()
```

2. Check the first role id.
```php
$role_id = $roles->first()->id;
```

3. The given`id` is **4** (from the `role_user` table), when it should be **2** (from the `roles` table).

```php
array(
   "id" => 4, // this should be 2.
   "name" => "Administrator",
   "description" => "Some description here",
   "role_id" => 2,
   "user_id" => 9,
   "permissions_count" => 4,
)
```
*Additionally:* the `role_id` and the `user_id` should be in a `pivot` key.

**Comment by KKSzymanowski** [comment]
You are correct.

The generated query looks like this:
```sql
SELECT *,

  (SELECT count(*)
   FROM `permissions`
   INNER JOIN `permission_role` ON `permissions`.`id` = `permission_role`.`permission_id`
   WHERE `permission_role`.`role_id` = `roles`.`id`) AS `permissions_count`
FROM `roles`
INNER JOIN `role_user` ON `roles`.`id` = `role_user`.`role_id`
WHERE `role_user`.`user_id` = 9
```

And it's result is:

| id | name          | description           | created_at          | updated_at          | id | role_id | user_id | permissions_count |
|----|---------------|-----------------------|---------------------|---------------------|----|---------|---------|-------------------|
| 2  | Administrator | Some description here | 2016-12-04 17:17:01 | 2016-12-04 17:17:01 | 4  | 2       | 9       | 4                 |

As you can see, the `id` is here twice. Because PHP arrays don't allow for duplicate keys, the `id` field will first hold `2` and then it'll be overwritten by `4`.

> Additionally: the role_id and the user_id should be in a pivot key.

They are. Try this:
```php
$user = \App\User::first();

$pivot = $user->roles()
              ->withCount('permissions')
              ->get()
              ->first()
              ->pivot;

dd($pivot->toArray());
```

For me, its output is:
```
array:2 [
  "user_id" => 9
  "role_id" => 2
]
```

Therefore you should probably use this value to get the role id.

Nevertheless, this is a bug in my opinion.

**Comment by themsaid** [comment]
@KKSzymanowski do you think you can open a PR with a fix?

**Comment by KKSzymanowski** [comment]
I'm not really sure what to do with this.
I suppose one way to go about it is to prefix columns from the pivot table to avoid name conflicts.

I would need to take a look how it's done in other parts of the Eloquent engine, because I'm not that familiar with relationship logic. Give me a day or two, maybe you'll come up with something in the meantime. If so, please share any ideas.

**Comment by srmklive** [comment]
@cabalopolis have you tried it like this as well:

   ```
   public function roles() {
      return $this->belongsToMany(Role::class, 'role_id');
   }
   ```

   ```
   public function permissions() {
      return $this->belongsToMany(Permission::class);
   }
   ```

**Comment by srmklive** [comment]
For permissions:

   ```
   public function permissions() {
      return $this->belongsToMany(Permission::class);
   }
   ```

**Comment by KKSzymanowski** [comment]
I haven't tested but it but I wouldn't expect it to work because these are the default values for belongsToMany relationship.

**Comment by srmklive** [comment]
@cabalopolis @KKSzymanowski What you guys have described here, i haven't been able to replicate.  My view is that you guys haven't done your due diligence in this regard. I have exactly the table structure as well described by @cabalopolis. This just doesn't happen. I am attaching screenshots of what i did through `php artisan tinker`:

![screenshot from 2016-12-06 12 14 21](https://cloud.githubusercontent.com/assets/839335/20916749/2ba190b8-bbaf-11e6-8d72-2f3bc4290f4d.png)
![screenshot from 2016-12-06 12 20 11](https://cloud.githubusercontent.com/assets/839335/20916753/302dc3ea-bbaf-11e6-93b4-8a61649ba2b8.png)
![screenshot from 2016-12-06 12 21 40](https://cloud.githubusercontent.com/assets/839335/20916756/32b7eb36-bbaf-11e6-9f1c-69cb43f91f6a.png)

**Comment by cabalopolis** [comment]
@srmklive I'm not 100% sure you have understood the issue / performed that steps correctly. I have set up a repository with the issue outlined, feel free to clone it and observe the issue: https://github.com/cabalopolis/with-count-bug.

**Comment by srmklive** [comment]
@cabalopolis I have done it correctly. You in my view are not doing it right. I have cloned your repo, performed the exact steps you mentioned and couldn't replicate the issue you are facing. Please find below screenshots of steps i did on your repo:

![screenshot from 2016-12-06 15 00 20](https://cloud.githubusercontent.com/assets/839335/20921336/6935ac64-bbc5-11e6-977b-78f59f7b9c26.png)
![screenshot from 2016-12-06 15 05 11](https://cloud.githubusercontent.com/assets/839335/20921337/6ac7d7aa-bbc5-11e6-9264-bc8c2aa957d4.png)

**Comment by srmklive** [comment]
Furthermore if such a issue was happening, i am sure the issue section would have flooded with this, and fix would have been issued instantly.

**Comment by cabalopolis** [comment]
@srmklive you cannot see the issue as it is being masked by the fact that the pivot table entry has an ID of 1 and the roles table as and ID of 1. If the entry in the pivot table were to have an ID of 2 then you would see the issue.

**Comment by srmklive** [comment]
@cabalopolis here you then :wink:

![screenshot from 2016-12-06 15 17 53](https://cloud.githubusercontent.com/assets/839335/20921737/4264d536-bbc7-11e6-96c6-e6a085e32360.png)

**Comment by cabalopolis** [comment]
@srmklive Run the migrations + seeds in the repo and perform the same as I have done in tinker.
<img width="955" alt="screen shot 2016-12-06 at 11 24 23 pm" src="https://cloud.githubusercontent.com/assets/5028055/20921955/4b0e15fa-bc0b-11e6-8a4c-e52d40829e22.png">
The role ID is definitely not correct.

**Comment by fernandobandeira** [comment]
@cabalopolis 

I can reproduce it too, with your repo...

![reproduce](https://cloud.githubusercontent.com/assets/8373980/20922164/49e7b7f8-bb8e-11e6-8c5f-f38736ac5d13.png)

Reproduced with sqlite...

**Comment by KKSzymanowski** [comment]
@srmklive You didn't see the bug because you created a role with an id of 1 and the pivot table had the id of 1. Then you created a second role(id = 2) and when you attached to the user the pivot table once again had the same id.

**Comment by srmklive** [comment]
@KKSzymanowski It doesn't matter which id i attach it in the pivot table, i always got the data with correct id. What @cabalopolis is referring to an issue with a single entity i guess.

**Comment by cabalopolis** [comment]
@stmklive the issue is not limited to any single entry. @KKSzymanowski is correct, the behaviour of php and the generated query is what is causing the bug. It appears that the pivot table and the roles table are being merged, which is why the role_id and the user_id is appearing twice (once in the array and once in the pivot key of the array).

**Comment by srmklive** [comment]
@cabalopolis The issue which @KKSzymanowski alluded to was that eloquent shouldn't select the pivot table id column, I agree with that. The reason I went back & forth with you was the issue with data representation you listed, which I couldn't replicate.
