### ISSUE TITLE
[5.3] Query Builder::insert() doesn't handle different columns

### ISSUE THREAD

**Issue by shadoWalker89** [laravel/framework#16641]
- Laravel Version: 5.3.26

### Description:

So i have a batch insert where the two first rows have this columns `a` and `b`
the third row has `a`, `b` and `c`
`c` is nullable, so i'm not going to pass it to all rows.

I get this error `SQLSTATE[21S01]: Insert value list does not match column list: 1136 Column count doesn't match value count at row 3`

I saw that a similar issue has been brought up before and closed
https://github.com/laravel/framework/pull/15689

But please @taylorotwell consider fixing this. Other then the fact that this is a bug, Laravel is known for making things easier and less complex.
Fixing this manually before passing data to `Builder::insert()` isn't a pleasant thing to do and neither the expected behavior.

Graham please don't close it :D and give this issue a chance so taylor can see it.

**Comment by GrahamCampbell** [comment]
> Graham please don't close it :D and give this issue a chance so taylor can see it.

Taylor doesn't normally read the issues here. It looks like from the other PR, that this is more of a feature request, than a bug, given Taylor's comment was:

> Just prefer to specify the keys explicitly.

---

Perhaps the best plan of action here is to open a proposal issue on the internals repo so you can get a discussion going. The issue tracker on this repo isn't geared towards that. Hope this makes sense. :)

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/internals/issues
