### ISSUE TITLE
Locale (re)set again after Middlewares

### ISSUE THREAD

**Issue by elasticsteve** [laravel/framework#16659]
- Laravel Version: 5.3.26
- PHP Version: 7
- Database Driver & Version:

Created a web middlewareGroup to set the Locale. Added it last (after `SubstituteBindings`) in the `Kernel.php`.

When I check the Locale in the Middleware with ` dd(App::getLocale());` I can see it already has read the `.env` file. (changed it to `nl` to check)

In the Middleware I then set the Locale to something different than it was in `.env` for example `App::setLocale('de');`

When hitting the Route in `web.php` the Locale has been reset again to what it was in the `.env` file. Why? I spend many hours yesterday, but couldn't find a solution of how I'm supposed to set the Locale in a Middleware. Sorry if this is the wrong place to post!

**Comment by themsaid** [comment]
Well, it should work, I assume something is overriding your Middleware `setLocale`. 

You can try the forums since we keep this repo for bug reporting only.
