### ISSUE TITLE
[5.3] Custom rule name with dashes and underscores ('-', '_')

### ISSUE THREAD

**Issue by LittleBigDev** [laravel/framework#16656]
- Laravel Version: 5.3.24
- PHP Version: 5.6.27

### Description:
Cannot create a custom validation rule with a keyword containing **dashes** or **underscores**.

### Steps To Reproduce:
- Create a new class (extending nothing) used as validator class. Let's call it MyValidator.
- Create validateMyField() function in MyValidator. It should return a boolean as validation result.
- In a service provider, bind this class so it can easily be called as callback.
- In a service provider, register your validation rule by extension : `Validator::extend('my-keyword', 'MyValidator@validateMyField', 'damn this is a bad value');`
- Try to use the new validation rule

Result : BadMethodCallException is thrown. It's trying to call validateMyKeyword on Validator class.
What is expected : MyValidator@validateMyKeyword callback should be called.

Just to verify everything was correctly setup, just change rule keyword from "my-keyword" to "mykeyword" (it's working fine without dashes or underscores)...

[The thread on Laracasts](https://laracasts.com/discuss/channels/general-discussion/l5-troubleshooting-my-custom-validation-rule)

**Comment by KKSzymanowski** [comment]
Dashes won't work because Validator converts the rule name to snake case [here](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Validation/Validator.php#L3383), but underscores work fine for me:

AppServiceProvider::boot()
```php
Validator::extend('must_be_foo', function($attribute, $value, $parameters) {
    return $value == 'foo';
});
```

web.php
```php
$rules = ['a' => 'must_be_foo'];
dd(Validator::make(['a' => 'bar'], $rules)->errors()->all());
```
gives 
```
array:1 [
  0 => "validation.must_be_foo"
]
```

**Comment by LittleBigDev** [comment]
Ok. As dashes are nicely converted into function calls, I assumed it would work with custom rules too.
I had another issue in my code with namespaces : I used `app\` instead of `App\`. This is why underscores didn't work either. 
Underscores work fine for me too after I fixed my namespaces mistakes...
Thank you @KKSzymanowski for pointing me in the right direction :)
