### ISSUE TITLE
Get a same user with different api_token

### ISSUE THREAD

**Issue by NimaGhaedsharafi** [laravel/framework#16651]
- Laravel Version: 5.2

https://github.com/laravel/framework/blob/5.3/src/Illuminate/Auth/TokenGuard.php#L59

### Description:
The condition in line 59 at TokenGuard makes some difficulties in testing webservice. when a test passes a api_token to a `Call()`, Auth retrieves the related user. some lines after in test context, there's another `Call()` with a different api_token but Auth driver thinks this user is retrieved before and return the old user. 

## Test
```
public function testA() {
    $this->route('POST', 'foo.route.name', [], ['api_token' => $user->getApiToken()]);
    $this->route('POST', 'foo.route.name', [], ['api_token' => $newUser->getApiToken()]);
}

```
## Controller 

```
public function foo(Request $request) {
    \Log::info(var_dump(Auth::guard('api')->user()->getApiToken() == $request->get('api_token')));
}
```

## Results
Call0 -> True
Call1 -> False

**Comment by KKSzymanowski** [comment]
I think you can split each test which require multiple users to be authenticated into separate methods. That way you will always have a clear Laravel instance and would not have to worry about the data left from previous route call.
Would that work for you?

**Comment by NimaGhaedsharafi** [comment]
I need to test them together, I can't spilt them out

**Comment by srmklive** [comment]
5.2 is not supported anymore. Can you confirm the same issue is happening for 5.3?

**Comment by NimaGhaedsharafi** [comment]
@srmklive I linked the 5.3 version of TokenGaurd in description, it's totally identical in both .

**Comment by srmklive** [comment]
In the second test case for controller, you are checking whether the current logged in user api token matches the passed api token. This will always return false, because there is no session maintained for api guard.

**Comment by themsaid** [comment]
Split the tests as @KKSzymanowski says, Laravel doesn't expect you to switch the user on the go, you'll need a fresh instance of the application since it's a separate request.

**Comment by NimaGhaedsharafi** [comment]
@srmklive TokenGaurd is totally stateless, it doesn't make sense to store the user,

I can't split the test, it's in some sort of social network test. Test expects `UserA` to send follow request to `UserB` then `UserB` should response to the request! how should I separate them? 

we might use a simple api_token check before try to retrieve the stored user.

**Comment by themsaid** [comment]
You can use PHPUnit's @depends

**Comment by NimaGhaedsharafi** [comment]
@themsaid it's a bad practice

**Comment by srmklive** [comment]
@NimaGhaedsharafi In my reply, where am i saying that you store the user. I would concur with @themsaid here. You need to split the tests. In your case, you may need to send some encrypted token containing the followed user id, then your tests may work.

**Comment by KKSzymanowski** [comment]
In my opinion the `$user` property on TokenGuard just serves as a cache(to prevent hitting the DB multiple times).

If we think of it as of a cache, I suppose there is no harm in adding a method for clearing it.

**Comment by NimaGhaedsharafi** [comment]
@KKSzymanowski 
what method do you think of? please give me an example
> I suppose there is no harm in adding a method for clearing it.

**Comment by KKSzymanowski** [comment]
```php
public function flushUser()
{
    $this->user = null;
    
    return $this;
}
```

😃

**Comment by NimaGhaedsharafi** [comment]
@KKSzymanowski this is is not about this helper method 😐

**Comment by srmklive** [comment]
@NimaGhaedsharafi I would suggest we move this issue over to laravel/internals and discuss it furthermore there.

**Comment by KKSzymanowski** [comment]
@NimaGhaedsharafi Why wouldn't it solve this problem. You can flush the cached user between requests.

It doesn't necessarily think of the user as a cache. It can be called `reauthenticate`.
