### ISSUE TITLE
Migation: creation of timestampTz returns Invalid default value

### ISSUE THREAD

**Issue by khooz** [laravel/framework#16653]
- Laravel Version: 5.3.24
- PHP Version: 7.0.9
- Database Driver & Version: 10.1.18-MariaDB

### Description:

When creating a new migration, upon creation of a new `timestampTz` or `timestamp`, not nullable column; an error is raised. But when I call `nullable()` against them or try the query shown in the error directly, the table is created without an error.

### Steps To Reproduce:

In `create_certificates_table`:

    public function up()
    {
        Schema::create('certificates', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('cert_id');
            $table->unsignedBigInteger('user_id');
            $table->timestampTz('start_time');
            $table->timestampTz('expiration_time');
            $table->timestampsTz();

            $table->foreign('cert_id')->references('id')->on('certificates_pool')->onDelete('cascade')->onUpdate('cascade');
	        $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade')->onUpdate('cascade');
        });
    }

And the error:

    [Illuminate\Database\QueryException]
    SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'expiration_ti
    me' (SQL: create table `certificates` (`id` int unsigned not null auto_increment primary key, `c
    ert_id` int unsigned not null, `user_id` bigint unsigned not null, `start_time` timestamp not nu
    ll, `expiration_time` timestamp not null, `created_at` timestamp null, `updated_at` timestamp nu
    ll) default character set utf8 collate utf8_unicode_ci)

    [PDOException]
    SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'expiration_ti
    me'

**Comment by KKSzymanowski** [comment]
You can say:
```php
$table->timestampTz('start_time')->nullable();
$table->timestampTz('expiration_time')->nullable();
```

Wouldn't that work for you?

MySQL tries to assign a default value of `CURRENT_TIMESTAMP` to every non-nullable timestamp(or without an explicit default value), but it can be done only once per table, that's why you get the error. If you take a look at what's generated from  `$table->timestampsTz();` you'll see it's
```
`created_at` timestamp null, 
`updated_at` timestamp null
```
