### ISSUE TITLE
Use "callable" typehint instead of "\Closure"

### ISSUE THREAD

**Issue by foglcz** [laravel/framework#16662]
- Laravel Version: 5.1, 5.2, 5.3, master
- PHP Version: 5.6, 7.0, 7.1
- Database Driver & Version: n/a

### Description:
Real world use-case. I'm building flexible models in Lumen framework, while using `Illuminate\Database` - and I have a base model, which returns a query builder.

This query builder does some basic mapping between column names in database, and column names in entities, so I wanted to generate the schema from within the model itself:

```php
// SomeMigration.php
use App\Domain\Models;
class MyMigration extends Migration
{
    public function up()
    {
        Schema::create('some_table', [Models\SomeModel::class, 'generateSchema']);
    }
}

// App\Domain\Models\SomeModel.php
namespace App\Domain\Models;
class SomeModel extends Base
{
    /**
     * @param Blueprint $table
     */
    public static function buildSchema(Blueprint $table)
    {
        $table->charset = 'utf8mb4';
        $table->collation = 'utf8mb4_general_ci';

        $table->increments('id');
        $table->integer('number');
        $table->char('code', 4);
        $table->char('type', 1);
        $table->string('full_name');
        $table->timestamps();

        $table->unique(['number']);
        $table->index(['code']);
    }
}
```

This throws an exception:
```                                                                                                                            
  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Type error: Argument 2 passed to Illuminate\Database\Schema\Builder::create() must be
  an instance of Closure, array given, called in
  /var/www/someproject/vendor/illuminate/support/Facades/Facade.php on line 237
                                        
```

## Why it doesn't work
It doesn't work. because `\Illuminate\Database\Schema\Builder::create` expects type of `\Closure`. However, as of PHP 5.4 you can use typehint `callable`. So the fix, in this case, would be to fix `illuminate/database/Schema/Builder.php`, **line 140**:

```php
    /**
     * Create a new table on the schema.
     *
     * @param  string    $table
     * @param  callable  $callback
     * @return void
     */
    public function create($table, callable $callback) // <-- note the different typehint
    {
        $blueprint = $this->createBlueprint($table);

        $blueprint->create();

        $callback($blueprint);

        $this->build($blueprint);
    }
```

This will allow the user to submit anything, that is invokable - whereas `\Closure` **requires** anonymous function.

see https://secure.php.net/manual/en/functions.anonymous.php

> Anonymous functions, also known as closures, allow the creation of functions which have no specified name. **They are most useful as the value of callback parameters**, but they have many other uses.

Callback is a pre-5.4 pseudo type https://secure.php.net/manual/en/language.pseudo-types.php#language.types.callback

5.4 introduces `callable` as a correct typehint.

yay or nay?

**Comment by vlakoff** [comment]
Refs some previous PRs : #10450, #9565,
and the "current" discussion on internals: https://github.com/laravel/internals/issues/25.

**Comment by foglcz** [comment]
oh, sorry, didn't search :(

closing

**Comment by vlakoff** [comment]
Still, good to bring this up.
