### ISSUE TITLE
Allow username and email for authentication

### ISSUE THREAD

**Issue by mstnorris** [laravel/framework#16663]
- Laravel Version: 5.3.18
- PHP Version: 7.1.0RC5
- Database Driver & Version: 5.7.12-0ubuntu1.1

### Description:

https://laravel.com/docs/5.3/authentication - Username customisation: would it be possible to use an array so to allow multiple options for authentication? For example:

```php
public function username()
{
    return ['username', 'email']; // this will allow either username & password, or email & password.
}
```

### Steps To Reproduce: NA

I apologise if it has been asked before but I couldn't find any official reference to it.

Cheers

**Comment by srmklive** [comment]
There is no need for it. This is something you need to modify on your own. You should override the implementation in `AuthenticatesUsers` trait accordingly to your own requirements.

**Comment by crynobone** [comment]
You could use https://github.com/laravie/authen
