### ISSUE TITLE
Validator: Throw exception when callback definition is invalid

### ISSUE THREAD

**Issue by cweiske** [laravel/framework#16672]
- Laravel Version: 5.3.22
- PHP Version: 7.0.8

### Description:
I wanted to register a custom validation rule in my AppServiceProvider, using a callback. I used the PHP's classic array callback syntax:

        \Illuminate\Support\Facades\Validator::extendImplicit(
            'nonestedobjects',
            [\Foo::class, 'checkNoNestedObjects']
        );

This did not work, and I did not get an error.

Reason for this is that `\Illuminate\Validation\Validator::callExtension()` only supports closures and strings, but not arrays.

Please:
a) add an `else` clause that throws an exception and
b) support array callback definitions.

**Comment by themsaid** [comment]
Well, you can use a string definition: `Foo::class.'@checkNoNestedObjects'`, this is consistent with many other parts of the framework.

**Comment by cweiske** [comment]
> you can use a string definition: Foo::class.'@checkNoNestedObjects'

This dismisses point b, which is ok.

What you do not address is point a - not telling anyone that they made an error. Why shall that stay so?

**Comment by themsaid** [comment]
I assume it's because no array form is mentioned in the docs, only closure or class based extension, however feel free to open a PR with the proposed changes.
