### ISSUE TITLE
Feature for model class to automatically get the table name

### ISSUE THREAD

**Issue by dhiman252** [laravel/framework#16671]
-Feature Request

### Description:
Since Laravel has the support for the database validations, so for example we have the follwing validation:
exists:table,column
so here instead of passing the table name can there be a support for passing the Model class name
exists:App\User::class,column
The basic idea is to automatically retrieve the table name from the model class.

**Comment by themsaid** [comment]
Thank you for suggesting this, but we keep this repo for bug reporting only, can you post your suggestions on the https://github.com/laravel/internals repo?
