### ISSUE TITLE
Blank pagination page when going to non-existent page #

### ISSUE THREAD

**Issue by depthbomb** [laravel/framework#16670]
- Laravel Version: 5.3.26
- PHP Version: 7.0.8
- Database Driver & Version: MySQL 14.14

### Description:
What I mean by the title is if you have 12 results per page, but only have 5 items in total, attempting to go to page 2 (or any number) manually will result in a blank page with pagination buttons below. I was able to reproduce this on two of my sites, one uses chunks and the other does not. Both also use extremely simple methods of pagination such as `$users = Users::paginate(12)` and both sites use the same Laravel version, PHP version, and database version as listed above.

### Steps To Reproduce:
1. Manually add ?page=**#** to the URL where the number is greater than the last page. For example, if you have 4 pages, set it to 5.

I couldn't find this while searching issues, yet it is late here at the time of posting so I might have just not noticed.

---

You can see this bug reproduced [here.](http://staging.cyan.tf/laravel/bug) where there is only 1 item, but there is a 5 item per page limit. As you can see, it shows a blank page with pagination buttons despite there not being any need for it. The buttons look broken because I am not using Bootstrap and I haven't created a template to fit my application yet.

**Comment by sisve** [comment]
And what do you expect to happen?

**Comment by themsaid** [comment]
To me that makes more sense than throwing a 404 or something.

**Comment by garygreen** [comment]
This is currently the expected behaviour. I created a suggestion which can be discussed here: https://github.com/laravel/internals/issues/273

**Comment by GrahamCampbell** [comment]
Yeh, a 404 is wrong because it says the resource doesn't exist, which isn't true.

**Comment by GrahamCampbell** [comment]
A resource is defined without any query string paramaters.
