### ISSUE TITLE
Changing column to nullable having no affect

### ISSUE THREAD

**Issue by garygreen** [laravel/framework#16677]
- Laravel Version: 5.3.26
- PHP Version: 5.6
- MySQL Version: 10.1.13-MariaDB

### Description:

Attempting to change a column from non-nullable to nullable has no affect.

### Steps To Reproduce:

```php
Schema::create('users', function($table) {
    $table->integer('deleted_by')->default(0);
});

Schema::table('users', function($table) {
    $table->integer('deleted_by')->nullable()->change();
});
```

Also tried:

```php
Schema::table('users', function($table) {
    $table->integer('deleted_by')->change()->nullable(true);
});
```

**Comment by Georift** [comment]
I've tested both of the steps you listed, it's working for me even with the exact same versions.

**Comment by themsaid** [comment]
ping @garygreen 

Is it still not working or you managed to get it to work?

**Comment by garygreen** [comment]
@themsaid yes it's still a problem, not sure why Georift can't replicate.

This is what you get when you run the code:

![image](https://cloud.githubusercontent.com/assets/1702638/21345782/6ab78466-c699-11e6-97b2-ffac2d758ccf.png)

Expected result:

![image](https://cloud.githubusercontent.com/assets/1702638/21345798/8278ed1a-c699-11e6-8643-c1e7859c965e.png)

**Comment by cgoosey1** [comment]
In your code you are modifying the table to allow nullable, you aren't changing the default to be null (if you see the distinction).

This code should do the job:
```
Schema::create('users', function($table) {
    $table->integer('deleted_by')->default(0);
});

Schema::table('users', function($table) {
    $table->integer('deleted_by')->nullable()->default(null)->change();
});
```

**Comment by cgoosey1** [comment]
Using this specific example, you are defining a column default in the Schema::create., later on you are setting that column to nullable, not specifying anything about default. 

Using nullable you are just allowing null values, maybe theres a reason you wanted the column default to be 0 in the first place, if nullable changed the default it might lead to undesired and unforeseen consequences. 

Though this is probably one of those things that can be argued both ways, but I think how it currently is is the simpler solution.

**Comment by garygreen** [comment]
Yeah it's not a biggie now I know to specify `default(null)` explicitly. It is inconsistent but like you say it could be argued both ways.
