### ISSUE TITLE
[5.3] Cannot run withTrashed on Laravel Relationship

### ISSUE THREAD

**Issue by miendinh** [laravel/framework#16676]
- Laravel Version: 5.3.-dev
- PHP Version: 7.0.8
- Database Driver & Version: mysql 5.7.16

### Description:
I implement SoftDelete like 
instruction at https://laravel.com/docs/5.3/eloquent#soft-deleting.

```
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Model 
{
     	use SoftDeletes;
        protected $table = 'user';

	protected $dates = ['deleted_at'];
```

table 'user' has column 'deleted_at'.

but I get issue : 

`Call to undefined method Illuminate\Database\Query\Builder::withTrashed()`

### Steps To Reproduce:

`$user = User::withTrashed()->first();`

Please help me solve this.
Thank you :-)

**Comment by brunogaspar** [comment]
What's the code to reproduce your issue?

**Comment by miendinh** [comment]
Dear @brunogaspar 
here is my code :

`$user = User::withTrashed()->first();`

:-)

**Comment by brunogaspar** [comment]
Not being able to reproduce.

Make sure that you're calling the correct User class and that the class itself is indeed saved with the changes above.

**Comment by miendinh** [comment]
Hi @brunogaspar 

I have checked my code.
Here is exactly my problem,  I use  child class inherited from 'User' ( with SoftDeletes capability )
such as : 

```
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Model 
{
     	use SoftDeletes;
        protected $table = 'user';

.....
}

abstract class OptimizedBaseModel extends User implements OptimizedModelInterface {
	...............
}

class UserExtension extends OptimizedBaseModel implements WorkInterface, LogInterface, AdminInterface
{
	...............
}
```

this call run ok

`$user = User::withTrashed()->first();
`
but this call 
`$user = UserExtension::withTrashed()->first();`

reproduce issue : ` Call to undefined method Illuminate\Database\Query\Builder::withTrashed()`

Plz help me check !
thank in advance :-)

**Comment by GrahamCampbell** [comment]
Please ask on the forums.
