### ISSUE TITLE
Collection::filter() needs $flag

### ISSUE THREAD

**Issue by josephzidell** [laravel/framework#16685]
- Laravel Version: all
- PHP Version: all
- Database Driver & Version: n/a

### Description:
Fact # 1: The `Illuminate\Support\Collection` class is awesome, like the rest of Laravel.
Fact # 2: the `filter()` method needs a `$flag` param to match [`array_filter`](http://php.net/array_filter)
https://github.com/laravel/framework/blob/5.3/src/Illuminate/Support/Collection.php#L279

### Steps To Reproduce:
Try to use `Collection::filter()` with `ARRAY_FILTER_USE_BOTH` and it's not possible.

**Comment by thecrypticace** [comment]
You already get the keys during filter, it is the 2nd parameter. See: https://github.com/laravel/framework/blob/5.3/src/Illuminate/Support/Arr.php#L517
which is used by `filter()`

e.x.
```php
collect(["a" => 1, "b" => 2])->filter(function ($value, $key) {
    return $key === "a";
});
```

returns:
```php
[
    "a" => 1,
]
```

**Comment by themsaid** [comment]
Check @thecrypticace's answer.

**Comment by josephzidell** [comment]
Thanks guys. You rock!
