### ISSUE TITLE
Blade Extends Bug

### ISSUE THREAD

**Issue by alexbowers** [laravel/framework#16688]
- Laravel Version: 5.3
- PHP Version: 7.0

### Description:
When you have a commented out @extends it still evaluates the variable

### Steps To Reproduce:

```php
{{-- @extends('layouts.master') --}}
```

Will still processes the @extends

**Comment by GrahamCampbell** [comment]
Yeh, blade comments are very limited, they're intended for adding textual comments. Blade inside them will still get parsed.

**Comment by CupOfTea696** [comment]
@GrahamCampbell couldn't this be easily fixed by processing comments as the very first thing, before compiling any of the other directives?

**Comment by GrahamCampbell** [comment]
In this case, no, because I think extends isn't handled by the "compiler", but at runtime. We'd be

**Comment by alexbowers** [comment]
@GrahamCampbell I'll take a look into how Blade works this evening.
