### ISSUE TITLE
How set updated_at as null in default?

### ISSUE THREAD

**Issue by musaev-haybulla** [laravel/framework#16695]
- Laravel Version: 5.2
- PHP Version: 5.6
- Database Driver & Version: 5.2

### Description:
Hello. When i install laravel database and getting started with eloquent, i'm use created_at and updated_at field. In $user->save() action created_at field set current timestamp and updated_at set as null. If i'm updated $user, updated_at set current timestamp.

But today i'm use eloquent and create $user. In this action field created_at and updated_at set same value. This is bug or i'm early doing something wrong?..
And how i can set updated_at null value when create (not update) model object?..

Thank you.

**Comment by GrahamCampbell** [comment]
Please ask questions on the forums.
