### ISSUE TITLE
Model fetches soft deletes record on timestamp set to false

### ISSUE THREAD

**Issue by basherr** [laravel/framework#16691]
- Laravel Version: 5.2.45
#.#
- PHP Version: 5.6
- Database Driver & Version: Mysql

### Description:
The following model uses soft deletes. On delete attachment the row is `deleted_at` column is updated but while fetching it return all the rows including deleted rows.

```
class Attachment extends Model
{
     use SoftDeletes, ModelEventLogger;

     protected $fillable = ['file_name', 'display_name', 'file_url', 'reference_id', 'reference_type', 'uploaded_by'];
     protected $dates = ['deleted_at'];
     public $timestamps = false;
}
```
Controller

`Attachment::all();//
 select * from attachments`

**Comment by themsaid** [comment]
Please upgrade to 5.3 and try, 5.2 is not supported anymore.

**Comment by lagbox** [comment]
Most likely you are overriding `boot` and not calling `parent::boot()` from it to boot the traits.
