### ISSUE TITLE
[5.3] QueryException when inserting multiple records w/ different columns.

### ISSUE THREAD

**Issue by JadoJodo** [laravel/framework#16698]
- Laravel Version: 5.3.26
- PHP Version: PHP 7.1.0 (cli) (built: Dec  2 2016 11:32:42) ( NTS )
- Database Driver & Version: mysql  Ver 15.1 Distrib 10.1.19-MariaDB, for osx10.12 (x86_64) using readline 5.1

### Description:

When attempting to insert multiple records with different column sets, a QueryException is thrown:

`
SQLSTATE[21S01]: Insert value list does not match column list: 1136 Column count doesn't match value count at row 2 (SQL: insert into 'users' ('device_id', 'first_name', 'id') values (1, Jared, 1), (Jordan, 2, JadoJodo)
`

This seems to stem from `\Grammars/Grammar.php:657`:

`$columns = $this->columnize(array_keys(reset($values)));`

wherein the keys of the first array are used as the columns to insert for ALL arrays passed to `\Illuminate\Database\Query\Builder`'s insert function. I'll admit there aren't a huge number of cases (that I can think of) where one would insert multiple records with differing column/value pairs, but the fact that the insert() function accepts multiple arrays, each with key/value pairs of column/value entries, implies that this is possible.

### Steps To Reproduce:

```php
<?php

use App\Models\User;

class UserSeeder extends Seeder
{
    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {
        DB::connection('default')->table('users')->insert(
            // User with a device.
            [
                'id'                 => 1,
                'first_name'   => 'Jared',
                'device_id'     => 1,
            ],
            // User without a device, who has Twitter account.
            [
                'id'                         => 2,
                'first_name'           => 'Jordan',
                'twitter_username => 'JadoJodo',
            ]
        )
    }
}

```

**Comment by lagbox** [comment]
No, it does not imply its possible. Its a 'single' prepared statement. Its not a new statement for each 'row'. 
If you wanted that behavior you would have to actually create new insert statements for each 'row'.

**Comment by lagbox** [comment]
It doesn't imply its possible. It is a 'single' prepared statement. One statement, it just passes many sets of values to the db.
To not have it this way, would require a new sql statement for each row.

**Comment by themsaid** [comment]
check @lagbox comment, closing this since there are not intentions to support otherwise. If you want to use different columns you can just execute as many insert queries as you want.
