### ISSUE TITLE
TokenMismatchException in VerifyCsrfToken.php line 68

### ISSUE THREAD

**Issue by GNSubrahmanyam** [laravel/framework#16700]
- Laravel Version: 5.3.26
- PHP Version: 5.6.28
- Database Driver & Version: MySQL

### Description: Some times this exception shows at the time of.
1. Login or
2. Register or
3. Logout or
4. Form Submit

What is the main logic behind the scene of this Exception?
How to remove this Exception? 

Thank in Advance

**Comment by CurosMJ** [comment]
Please google before opening an issue :) : http://laravel.io/forum/01-30-2015-laravel5-tokenmismatchexception-in-verifycsrftoken 

Read docs also : https://laravel.com/docs/5.3/csrf

**Comment by GNSubrahmanyam** [comment]
@CurosMJ I always use {{ csrf_field() }} in my form.

**Comment by themsaid** [comment]
Please read more about CSRF protection https://laravel.com/docs/5.3/csrf

**Comment by GNSubrahmanyam** [comment]
@themsaid i use {{ csrf_field()}} and this exception gives some times only not every time

**Comment by GNSubrahmanyam** [comment]
@CurosMJ I have experiencing this Exception in Only Chrome Browser. Please Open this issue.

**Comment by gumplei** [comment]
Dear All, I had the same problem and I found out that it only happen with php 5.6

I dump the variable $sessionToken and $token in vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php in the tokenMatch method. The result is if the application running in php7.0, $sessionToken is equal to $token. but if it is running in php5.6, they are not the same.

Should we consider it is a bug in Laravel 5.3?

**Comment by gumplei** [comment]
Finally, I found out what was happening on my problem. This is a configuration problem related to our web server which will add the Secure in all Set-Cookie header. so that only the application with https can send back the cookie to server. I just remove this setting and everything work properly again.

**Comment by iasheyam** [comment]
In your storage/cache folder you will find a session file. Delete it.
