### ISSUE TITLE
Form input lack string //avvv//

### ISSUE THREAD

**Issue by thanhtungka91** [laravel/framework#16701]
- Laravel Version: 5.0
- PHP Version:5.4
- Database Driver & Version:

### Description:
in Input of form if value = //abbb/// -> it doesnt show all the full of value-> not save correct data to db. 
example: 
 {!! Form::text('patternCode', , ['id' => 'pattern_code',  //abbb///,'class' => 'ag__input']) !!}

### Steps To Reproduce:
{!! Form::text('patternCode', , ['id' => 'pattern_code',  //abbb///,'class' => 'ag__input']) !!}
![image](https://cloud.githubusercontent.com/assets/3795067/21000508/a4b4b452-bd5e-11e6-9c17-93a6ed8016ff.png)

**Comment by sisve** [comment]
Did you mean to file a bug report at https://github.com/LaravelCollective/html ?

**Comment by themsaid** [comment]
Yes please, report the issue there, these classes are not in Laravel core anymore.
