### ISSUE TITLE
Adding observer boots model before request is run through middleware

### ISSUE THREAD

**Issue by torkiljohnsen** [laravel/framework#16715]
- Laravel Version: 5.3.26
- PHP Version: 7.0

### Description:

**Observers make models boot before request runs through middleware.**

In my Service Provider's `boot` method, I am registering an observer like this:
`User::observe(UserObserver::class)`.

This `User` model also has a trait that registers a global scope for the class, and this global scope is depending on a request variable set by a global middleware. Specifically, this is using the [Landlord package](https://github.com/HipsterJazzbo/Landlord) for multi-tenancy. The middleware sets the `tenant_id`, the models should then use this `tenant_id` in their global scopes. But that's an implementation detail and besides the point.

My problem is that the observer is registered when the service provider boots, and this is before the request is passed through the middleware. When calling `User::observe`, a new instance of the class is instantiated so we can call `$instance->getObservableEvents`. Instantiating the class effectively also calls `boot` on it, before middleware is run.

Not sure if this is intended but I think this behavior is inconsistent with how the other model event listeners work. It is possible to add listeners to all the default model events without booting the model. `User::creating` for instance.

My workaround currently looks like this:

```php
Event::listen('eloquent.booted: ' . User::class, function () {
    User::observe(UserObserver::class);
});
```

This ensures that the observer is not registered until after the model has been booted, instead of having the process of registering the observer actually boot the model.

A possible solution would be to make `Model->getObservableEvents()` static, but that would in turn cause problems for manually setting custom observable events.

**Comment by aaronsnyder** [comment]
Just ran into this last night, same version of Laravel. I was setting up observers in a service provider, and then adding a global scope based on Request::route() values. 

I ended up setting up my observers inside of my eloquent models in the boot function, which seemed like an ok workaround at the time (as it becomes very verbose that this model has an observer), but definitely feels like one shouldn't be forced to avoid service providers.

**Comment by ronlobo** [comment]
I noticed when hooking into a models saving event with an observer while attaching a relation, the relation won't get attached if it is accessed within the observer's saving method. Might be related to this issue.

**Comment by laurencei** [comment]
This looks like intended behavior to me. If you think of it in reverse, if the model did not `boot` when it was created, that would create unexpected behaviour as well. So it has to be one or the other.

The workaround listed seems perfectly valid when you need this functionality.

Please let me know if you think there is something I have not considered in relation to this.
