### ISSUE TITLE
Wrap eloquent event in a static method like "getEvent"

### ISSUE THREAD

**Issue by bubasuma** [laravel/framework#16718]
I found that this line is repeated in many places in `Illuminate\Database\Eloquent\Model`
```php
"eloquent.{$event}: ".static::class
```
I suggest to wrap it in a static method like the following
```php
    public static function getEvent($event)
    {
        return "eloquent.{$event}: " . static::class;
    }
```
so we can use it outside the model like the following
```php
    public function subscribe($events)
    {
        $events->listen(
            User::getEvent('created'),
            static::getListener('onUserCreated')
        );
    }
```

**Comment by fernandobandeira** [comment]
> I would really prefer people just transition to using class based Eloquent events with Laravel 5.4 so am going to hold on this.

So this wont get into core...

**Comment by GrahamCampbell** [comment]
I guess not. Not a bad thing though, given the solution with classes should end up ultimately more elegant I hope.
