### ISSUE TITLE
Error in vendor>composer>autoload_static.php - Laravel 5.3.26

### ISSUE THREAD

**Issue by GNSubrahmanyam** [laravel/framework#16714]
- Laravel Version: 5.3.26
- PHP Version:  5.6.28
- Database Driver & Version: MySQl

### Description: Error in vendor>composer>autoload_static.php - Laravel 5.3.26

```
public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit03e973073eea0174c457e95793a7c992::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit03e973073eea0174c457e95793a7c992::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit03e973073eea0174c457e95793a7c992::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit03e973073eea0174c457e95793a7c992::$classMap;

        }, null, ClassLoader::class);
    }

```
![15326254_1909838442586240_8481580461390228856_o](https://cloud.githubusercontent.com/assets/18217008/21039838/e4d5c60e-be06-11e6-81e2-7a6ed78ad3dd.jpg)

How to fix this issues.

**Comment by dwightwatson** [comment]
What's the actual error you're getting?

Delete your `vendor` folder and run `composer install` again to start fresh and see if this issue persists.

**Comment by GNSubrahmanyam** [comment]
@dwightwatson  I have included the screen shot

**Comment by GNSubrahmanyam** [comment]
@dwightwatson  several times i ran composer dump-autoload command then also the error remains same

**Comment by srmklive** [comment]
kindly remove your `vendor` folder and run `composer install` again. Also you would need to run the `composer install` as Administrator in Windows.

**Comment by sisve** [comment]
The warning says "Member has private access" since those properties are private. However, they are accessed within a closure that's bound to the ClassLoader type, making it valid. 

This isn't Laravel's code, it's part of composer and autoloading. Configure your IDE to ignore the vendor folder (or just ignore code inspections within it)

**Comment by moe70** [comment]
File >> Invalidate Caches/Restart >> Invalidate and Restart

**Comment by kjdion84** [comment]
@moe70 has the correct answer. Deleting the `vendor` folder is not necessary.

**Comment by Oto9717** [comment]
@moe70 Thank you! :D

**Comment by lucas-marciano** [comment]
@moe70 what local I like this stesp?

**Comment by Silassiai** [comment]
> The warning says "Member has private access" since those properties are private. However, they are accessed within a closure that's bound to the ClassLoader type, making it valid.
> 
> This isn't Laravel's code, it's part of composer and autoloading. Configure your IDE to ignore the vendor folder (or just ignore code inspections within it)

remove the vendor and composer install again.
Do not open the file again is a better options instead of ignoring the vendor folder
