### ISSUE TITLE
ViewCompiler should expire views more often

### ISSUE THREAD

**Issue by CupOfTea696** [laravel/framework#16724]
- Laravel Version: 5.3.*

### Description:

Blade should expire views when custom directives or Blade itself has changed. This way, a view that got compiled before a Blade directive changed will get recompiled rather than use the cached view that got compiled with a different blade directive.

### Steps To Reproduce:
- Add custom Blade directive
- Create view that uses said directive
- Add the view to a route & browse to that route
- Change or remove the custom blade directive
- Browse to the test route again

**Comment by themsaid** [comment]
I don't think there's a way to detect this, you'll need to refresh the cache if you ever make a change to a blade directive or after a laravel version upgrade.

**Comment by CupOfTea696** [comment]
Wouldn't it be possible to generate a Blade version hash, that incorporates the version of `illuminate/view` and a hash of the custom directives using Reflection or something?

**Comment by GrahamCampbell** [comment]
Possibly, but it won't be particularly fast to compute something like that.

**Comment by CupOfTea696** [comment]
Hmm, that's fair enough.
