### ISSUE TITLE
[5.3] Model route with default value

### ISSUE THREAD

**Issue by segadora** [laravel/framework#16727]
- Laravel Version: 5.3
- PHP Version: any
- Database Driver & Version: any

### Description:

I expect that 'hello world' should be returned, because a default value for name is set.

Exception is thrown instead

### Steps To Reproduce:

https://github.com/laravel/framework/pull/16726

**Comment by segadora** [comment]
@themsaid Is there a reason you wont support it even when its supported in implicit bindings?

You are just closing the issue without any reason.

**Comment by themsaid** [comment]
Closed because the PR was rejected, I don't think the idea behind it was clear enough, so please open a new PR describing in more detail the feature you're trying to add with implementation we can look at

**Comment by segadora** [comment]
@themsaid I think the pull request was closed due to I created a issue and a pull request. Is this the wrong approch?

**Comment by themsaid** [comment]
It's a feature request, right? Feature requests go to https://github.com/laravel/internals repo.

If you have implementation that we can look at then open a PR, it's always better to discuss implementation, but if you just want to see if the idea is acceptable by community use the repo I shared as it's where we look at and discuss feature requests.

**Comment by segadora** [comment]
@themsaid I think it's a behaviour bug/feature

As I stated. It works with implicit binding and not with bindings using aliases. I would expect the difference to work structually the same way.

The issue is about

In implicit bindings it is possible to bind a default value, which results in the controller does not throw a ModelNotFound exception, if the model is not found.

This is not possible in bindings with a alias. It will always throw an exception, if the model is not found.

A snippet showing the issue is here

https://github.com/laravel/framework/pull/16726/files

I think its possible that I was too fast writing the issues and pull request without detailing it enough.
