### ISSUE TITLE
How to add reply-to in email notification

### ISSUE THREAD

**Issue by whfamily2006** [laravel/framework#16735]
- Laravel Version: 5.3.25
- PHP Version: 7.0.9
- Database Driver & Version: xampp

### Description:
How can i set reply-to with Laravel notification package....

![image](https://cloud.githubusercontent.com/assets/9881496/21072024/165601d8-bed6-11e6-8c12-db1357ab2c74.png)

**Comment by GrahamCampbell** [comment]
> How can i set reply-to with Laravel notification package

Please ask questions on the forums.
