### ISSUE TITLE
preg_match problem in controller

### ISSUE THREAD

**Issue by jimmydong** [laravel/framework#16734]
- Laravel Version: 5.3.*
- PHP Version:5.6
- Database Driver & Version:mysql & 5.5

### Description:
code:  preg_match('/\\test\\(.*)\\slash/','\test\my\slash')

Exception:
preg_match(): Compilation failed

change to : preg_match('/\\\\test\\\\(.*)\\\\slash/','\test\my\slash')

It works ok.

**Comment by GrahamCampbell** [comment]
Please send a PR. :)
