### ISSUE TITLE
[5.3] Where year type issue

### ISSUE THREAD

**Issue by vinkla** [laravel/framework#16737]
- Laravel Version: 5.3.26
- PHP Version: 7.1
- Database Driver & Version: MySQL 14.14 Distrib 5.7.16

### Description:

I've database table of orders. I fetch the orders with `whereYear`. If the year argument is a integer it wont find any orders but if I typecast the year to a string it works.

This might be something on my end but I found it odd so I thought it was best to report it.

Also, this worked fine on PHP 7.0 without any issues.

Edit: I double checked the documentation and the examples are using strings. Maybe we should typecast all integers to strings for `whereYear`, `whereDay` and `whereMonth`? Or maybe force developers to pass strings? 

### Steps To Reproduce:

This **wont** work since the year is an integer.

```php
Order::whereYear('created_at', Carbon::now()->year)->get();
```

This **will** work since the year is a string.

```php
Order::whereYear('created_at', (string) Carbon::now()->year)->get();
```

**Comment by Rojtjo** [comment]
I was unable to reproduce this issue.
Do you see any difference between the executed queries besides the datatype of the year?

**Comment by vinkla** [comment]
None that I can find at least. Both cases prints the same SQL query.

```
select * from "orders" where strftime('%Y', "created_at") = ? and "orders"."deleted_at" is null
```

**Comment by billmn** [comment]
All works fine for me ... I have tried to use string and integer but the result is the same.

- Laravel 5.3.28
- PHP 7.1
- MySQL 5.7.15

**Comment by themsaid** [comment]
Can't generate this either, @vinkla did you manage to get around it by any means?

**Comment by vinkla** [comment]
@themsaid no, it only works if I typecast the integers to strings. Maybe it is something on my machine and setup. Closing this for now. Thanks for getting back.
