### ISSUE TITLE
TokenMismatchException Only in Chrome Browser

### ISSUE THREAD

**Issue by GNSubrahmanyam** [laravel/framework#16733]
- Laravel Version: 5.3.26
- PHP Version: 5.6.28
- Database Driver & Version: MySQL

### Description:  I am experiencing this exception only in Chrome Browser. I have tested in all other browser. 

![image](https://cloud.githubusercontent.com/assets/18217008/21071266/895035c4-bec1-11e6-818a-bc38190090f5.png)

Thanks in Advance.

**Comment by GrahamCampbell** [comment]
Doesn't look like a framework bug. Please ask questions on the forums. Common causes are missing favicons causing browsers to start two sessions.
