### ISSUE TITLE
getenv() and env() returns different results on string

### ISSUE THREAD

**Issue by sylwit** [laravel/framework#16743]
- Laravel Version: 5.3
- PHP Version: 5.6
- Database Driver & Version:

### Description:

It looks like env() should returns the same value as getenv() but in some case it doesn't
https://github.com/laravel/framework/pull/16742

### Steps To Reproduce:

in .env file add `TEST="\"123 456\""`

Then check output of :

```
getenv('TEST') => "123 456" 
env('TEST') => 123 456
```

**Comment by GrahamCampbell** [comment]
Yes. They are different functions.

**Comment by GrahamCampbell** [comment]
getenv is laravel's one

**Comment by sylwit** [comment]
getenv() is native PHP, env() is laravel's one.

Description of env() is 
/**
 * Gets the value of an environment variable. Supports boolean, empty and null.
 **/

`env()` is good because it is an improved function built on top of `getenv()`, it also supports a default value, Output should be different in case of bool, empty and null but strings should be the same or maybe better explain if it is voluntary.

**Comment by GrahamCampbell** [comment]
Right, yeh, but laravel's is intentionally not the same, and intentionally does not enforce it's changes in the other function.

**Comment by assunluis80** [comment]
@GrahamCampbell the same shitty answer as always. What the heck this kid is doing?!

**Comment by pablorsk** [comment]
On some scenarios, like `php:7.4-fpm` docker machine, [getenv() !== env() gives problems with phpunit](https://github.com/sebastianbergmann/phpunit/issues/4540#issuecomment-840064880).

On `.env` file you have
```
SOME_VAR=env_value
```

And you do, on bash:
```bash
export SOME_VAR=from_bash
```

You can see the problem doing this:
```php
echo getenv('SOME_VAR'); // from_bash
echo env('SOME_VAR'); // from_bash
```

**Comment by GrahamCampbell** [comment]
> On some scenarios, like php:7.4-fpm docker machine, getenv() !== env() gives problems with phpunit.

This is not a bug. Look at the source code of env.
