### ISSUE TITLE
laravel 5.3 php artisan queue:work console command can't work in redis cluster 3.0 && solve it

### ISSUE THREAD

**Issue by hongjh** [laravel/framework#16754]
- Laravel Version: 5.3.*
- PHP Version: 5.6
- Database Driver & Version: Redis Cluster 3.0

### Description:
` php artisan queue:work `  console command can't work in redis cluster 3.0

### Steps To Reproduce:
1. config config/database.php, make it support redis-cluster
```
    'redis' => [

        'cluster' => true,

        'default' => [
            'host' => env('REDIS_HOST', 'localhost'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => 0,
        ],
        
        'redis1' => [
            'host' => env('REDIS_HOST_1', 'localhost'),
            'password' => env('REDIS_PASSWORD_1', null),
            'port' => env('REDIS_PORT_1', 6379),
            'database' => 0,
        ],        
        
        'options' => [
            'cluster' => 'redis'
        ]
    ],
```

2. make a app jobs, like

```
namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Queue\SerializesModels;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;

class SendReminderEmail implements ShouldQueue
{
    use InteractsWithQueue, Queueable, SerializesModels;

    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        file_put_contents('/tmp/job.txt', "test\n", 8);
    }
}
```

3. dispatch job in controller and run
```
class HomeController extends Controller
{

    public function index(Request $request)
    {
        dispatch(new SendReminderEmail());
        echo "dispatch";
//        return view('welcome');
    }
}
```

4. run `php artisan queue:work`, it didn't work.

**Comment by hongjh** [comment]
Reason：
in redis cluster, the KEYS call must be in same hash slot.
see:
[keys-hash-tags] https://redis.io/topics/cluster-spec#keys-hash-tags

**Comment by hongjh** [comment]
How to resolve ?

we only need to do is , change Illuminate\Queue\RedisQueue

add '{}' to queue key, make the redis keys hash tags same in redis-cluster

also, you can write new class, binding Illuminate\Queue\RedisQueue, and rewrite the getQueue function
```
    // line 224
    protected function getQueue($queue)
    {
        return '{queues}:'.($queue ?: $this->default);
    }
```

**Comment by halaei** [comment]
Sorry, I was not aware of this Redis limitation.
Is this bug new to Laravel 5.3? I think transactions with access to multiple keys was used in Laravel < 5.2. According to https://redis.io/topics/cluster-tutorial, maybe this bug exists for all the Laravel versions?

> Redis Cluster supports multiple key operations as long as all the keys involved into a single command execution (or whole transaction, or Lua script execution) all belong to the same hash slot. The user can force multiple keys to be part of the same hash slot by using a concept called hash tags.

**Comment by halaei** [comment]
Will this be a more appropriate change?

```php
    protected function getQueue($queue)
    {
        return '{queues:'.($queue ?: $this->default).'}';
    }
```

**Comment by hongjh** [comment]
@halaei only add {} to queues words, like 
```
return '{queues}:'.($queue ?: $this->default);
```
so that will make {queues}:delayed  {queues}:reserved  in the same slots.

i had write a module to fix it. see:

https://github.com/cutv/queue
composer require cutv/queue=dev-master

**Comment by hongjh** [comment]
@halaei Yes, this bug exists for all the Laravel versions, but only when you use redis-cluster queue.
if you didn't use redis-cluster, the queue will work fine.

**Comment by halaei** [comment]
This (`return '{queues}:'.($queue ?: $this->default);`) imposes a more than necessary restriction. The complete key names are like this:

    queue:default  queue:default:delayed  queue:default:reserved

And if I got it right, they should be converted into:

    {queue:default}  {queue:default}:delayed  {queue:default}:reserved

**Comment by halaei** [comment]
Than aside, I have questions. If all the keys related to the same queue should be on the same hash slot, then what is the point of using Redis clusters for laravel queues?
If it is just for having redundancy, isn't the current code compatible with a cluster with only one master node and the rest of nodes being slaves?

**Comment by hongjh** [comment]
Yes, {queue:default}  {queue:default}:delayed  {queue:default}:reserved is better.

**Comment by hongjh** [comment]
sometime we also use another queue name, like  {queue:email}, 
so it will point to another slot , it's differnt form {queue:defalut).

**Comment by halaei** [comment]
Another easy fix? Will it be a fix if you set the name of you queues to `{default}` or `{email}` instead of `default` or `email`. There will be no need to change the code if you do that?

**Comment by hongjh** [comment]
Yes, it compatible with.  You can run more than one redis port, like 7000, 7001 in you mathine,
and remove the options config
```
        'options' => [
            'cluster' => 'redis'
        ]
```

**Comment by halaei** [comment]
```php
        'redis' => [
            'driver'      => 'redis',
            'connection'  => 'default',
            'queue'       => '{default}',
            'retry_after' => 90,
        ],
```

**Comment by hongjh** [comment]
i just update it, thanks for your help.

**Comment by hongjh** [comment]
wow, cool!  and now the queue name is queue:{default} queue:{default}:delayed, it work fine

**Comment by halaei** [comment]
Great. Maybe we need to document this restriction somewhere @taylorotwell :
If you use Redis queue driver over connections to a Redis cluster with more than one master nodes, the names of the queues should follow this pattern: {queue-name}

**Comment by hongjh** [comment]
there has another question, if we didn't change the code, we need add {} by hands
```
dispatch((new SendReminderEmail)->onQueue('{emails}'));
```
and run 
```
php artisan queue:work --queue={emails}
```

but if we change the code, we only need the name
```
dispatch((new SendReminderEmail)->onQueue('emails'));
php artisan queue:work --queue=emails
```

**Comment by halaei** [comment]
@hongjh yes you are right. But unfortunately, this change will be breaking. It may be OK to submit a PR for 5.4.

**Comment by hongjh** [comment]
OK. expect 5.4
