### ISSUE TITLE
bail and required_if don't work as one would assume

### ISSUE THREAD

**Issue by AndreasElia** [laravel/framework#16751]
- Laravel Version: 5.3.24

### Description:
`bail` doesn't seem to work as one would assume alongside `required_if`

### Steps To Reproduce:

Please see this PR comment...

https://github.com/laravel/framework/pull/11986#issuecomment-189345190

```
$data = [
    'start_date' => '11-11-11',
    'end_date' => null,
    'showEndDate' => false
];

$validator = \Validator::make($data, [
    'start_date' => 'required|date',
    'end_date' => 'bail|required_if:showEndDate,true|date|after:start_date'
]);

if ($validator->fails()) {
    return $validator->errors();
}
```

**Comment by themsaid** [comment]
@AndreasElia what is the issue please? What do you expect from the validator with the case you shared?

**Comment by AndreasElia** [comment]
@themsaid I'd expect the validation to `bail` if `required_if` comes back as false, but instead the validator continues running and I receive a validation messaged from `date`.

**Comment by themsaid** [comment]
`required_if:showEndDate,true` while the given value is false, so the rule will be skipped and the validator will do the date check. SO it skips, not fails, bail only works on failing rules not skipped rules.

**Comment by themsaid** [comment]
You need to use `sometimes()` to only validate the value if showEndDate is true.

**Comment by AndreasElia** [comment]
Thanks @themsaid 👍

**Comment by AndreasElia** [comment]
@themsaid how would that abandon the validation in my example code?

**Comment by dillingham** [comment]
`exclude_if` worked for me in this situation (for anyone else who lands here)
