### ISSUE TITLE
Global Function instead of Facade

### ISSUE THREAD

**Issue by AliFarhoudi** [laravel/framework#16755]
- Laravel Version: 5.3.#
- PHP Version:
- Database Driver & Version:

### Description:
In all of editors it's hard to use functions that are not directly related to class. Instead we could use global functions that makes programming easier (specially in modern editors).
For example we can use ```form()->open``` instead of ```Form::open```. (I know Form package is in laravel-collective, it was just an example)
And ```form``` function would be something like this:
```
function form() {
    return Form::getInstance();
}
```
And ```Form``` class has codes like this:
```
class Form {
    private static $instance;
    public static function getInstance() {
        if (is_null(self::$instance)) {
            self::$instance = new self();
        }
        return self::$instance;
    }
}
```

**Comment by vlakoff** [comment]
You can easily create custom helpers like:
```php
function foo() {
    static $instance;
    $instance || $instance = new Foo;

    return $instance;
}
```

**Comment by AliFarhoudi** [comment]
Nice tip. Thanks.

**Comment by AliFarhoudi** [comment]
@GrahamCampbell Why closed?
Aren't you going to answer my question?

**Comment by GrahamCampbell** [comment]
The current version of laravel doesn't have a form class, and there is a tip provided by @vlakoff, although I wouldn't recommend it. Instead, I'd recommend resolving a singleton from the ioc using the app helper.

**Comment by AliFarhoudi** [comment]
I mean the Facade idea hasn't been so good. Instead of Facades it's better to use helpers. It's more easier to use in editors and has better looking.
