### ISSUE TITLE
Problem using js libraries with Laravel elixir

### ISSUE THREAD

**Issue by minedun6** [laravel/framework#16750]
- Laravel Version: 5.3
- PHP Version: 7

### Description:
I know this might be a bit dump to ask but using Laravel 5.3 I want to import jquery-ui in my bootstrap.js file, I used this syntax trying to acheive so but with no much luck,

bootstrap.js
`
window.$ = window.jquery = require('jquery');
// my code
window.$ = $.extend(require('jqueryui')); or window.$ = $.extend(require('jquery-ui'));
`
later when I use 
`$('.selector').sortable()`
this returns that $('...').sortable is not a function.

**Comment by themsaid** [comment]
Please report here https://github.com/laravel/elixir
