### ISSUE TITLE
Inconsistency in mocking Cache

### ISSUE THREAD

**Issue by phanan** [laravel/framework#16753]
- Laravel Version: 5.3.x
- PHP Version: 7.0
- Database Driver & Version: Irrelevant

### Description:
The lately added `cache()` helper is extremely helpfully, but also apparently created some inconsistencies when testing with mocks. Considering this simple example:

```php
public function testCache()
{
    Cache::shouldReceive('get')->once()->with('key');
}
```

This test will pass with `Cache::get('key')` but fail with `cache('key')`, with the following error:

```
Mockery\Exception\NoMatchingExpectationException: No matching handler found for Mockery_12_Illuminate_Cache_CacheManager::get('key', NULL)
```

Correct me if I'm wrong, but given that `cache()` is (or at the very least, widely considered to be) a mere shortcut to `Cache::get()` and `Cache::put()`, one would expect their behaviors to be the same, regardless of how the helper is implemented under the hood.

### Steps To Reproduce:
As above.

**Comment by GrahamCampbell** [comment]
looks correct to me, due to the way __call works

**Comment by GrahamCampbell** [comment]
the global function passes through arg 2 because it is set as a default
