### ISSUE TITLE
Bug in Eloquent and uniqid querys

### ISSUE THREAD

**Issue by KAAF030191** [laravel/framework#16759]
- Laravel Version: 5.3.x
- PHP Version: 5.6
- MySQL & 5.1:

I want to report a bug; Failure to perform database queries, specifically when working PHP uniqid. It happens that when you query with Eloquent it does not bring the value of that field completely, but if I use QueryBuilder it works normally. It happens for all cases with Eloquent and uniqid of PHP. Greetings.

**Comment by themsaid** [comment]
check https://github.com/laravel/framework/issues/16576

**Comment by KAAF030191** [comment]
Thanks, I see that it already has a way of giving solution and the problem is because it does not correctly identify the type, as I assumed, although I did not know that in the model you could define the type of the primary key. Greetings.

**Comment by jairodealmeida** [comment]
Including the $ incrementing = false property in your Model can already solve the problem

class MyModel extends Model
{
    protected $fillable = [
        'id', //uuid <-- autoincrement fail
        'name',
    ];
    **public $incrementing = false;** //<-- solution
}
