### ISSUE TITLE
updateOrCreate on hasManyThrough relationship not working as expected

### ISSUE THREAD

**Issue by strebl** [laravel/framework#16758]
- Laravel Version: 5.3.26
- PHP Version: 7.1.0
- Database Driver & Version: mysql, MariaDB 10.1.19

### Description:
Hi all 👋🏻
Maybe I'm doing something wrong, sorry if that is the case!

I have 3 tables: `user_surveys`, `answer_metadata` and `answers`
and I have 3 models: `UserSurvey`, `AnswerMetadata` and `Answer`

On the `UserSurvey` model, I defined a hasManyThrough relationship:
```php
public function answers()
    {
        return $this->hasManyThrough(Answer::class, AnswerMetadata::class, 'user_survey_id', 'answer_metadata_id', 'id');
    }
```

Now I'm trying to create an answer with the `updateOrCreate` method:
```php
public function addAnswer($answer, $questionId, $user)
    {
        $answerType = Question::find($questionId)->answerType;

        $this->answers()->updateOrCreate([
            'question_id' => $questionId,
        ], [
            $this->typeField($answerType) => $answer,
            'answer_metadata_id' => $this->answerMetadata->id,
        ]);
    }
```
If it is a new answer, everything works as intended. But if I'll try to update a answer, it doesn't work because it tries to update the wrong answer.
The resulting query is:
```sql
update `answers` set `answer_option_id` = ?, `updated_at` = ? where `id` = ?
-- answer_option_id --> correct
-- updated_at --> correct
-- id --> wrong
```
The id it tries to update is the value of the `$this->answerMetadata->id`.

If I change the call to `$this->answerMetadata->answers()->...` (after setting up the relationships), it works.

### Steps To Reproduce:
- Create the 3 tables: `user_surveys`, `answer_metadata` and `answers`
- Create the 3 models: `UserSurvey`, `AnswerMetadata` and `Answer`
- Add some dummy data
- Set up the `answers()` relationship (hasManyThrough) on the UserSurvey model
- create the addAnswer method which uses the updateOrCreate method on the relationship
- call it

I have very very limited experience reporting bugs and my english is bad too! Therefore sorry if I messed something up. Just tell me if I can provide more information or clarify something better.

**Thanks for your hard work!**

**Comment by themsaid** [comment]
AFAIK `HasManyThrough` doesn't have an `updateOrCreate` method.

**Comment by strebl** [comment]
Hmm but shouldn't I get an error then? As I said, it is working for creation. It also updates, just the wrong record.

**Comment by lagbox** [comment]
@strebl no error because that method call is causing `__call` to be hit (as the method doesn't exist) which is calling `updateOrCreate` on the `Illuminate\Database\Eloquent\Builder` for that relation object.

**Comment by themsaid** [comment]
Submitted a PR with a fix https://github.com/laravel/framework/pull/17105
