### ISSUE TITLE
Commenting the @extends directive doesn't work

### ISSUE THREAD

**Issue by xandrw** [laravel/framework#16764]
- Laravel Version: 5.3.*
- PHP Version: 7.0.10
- Database Driver & Version: Irrelevant

### Description:
In a blade template, when trying to comment an `@extends` directive, the current template still extends it.

### Steps To Reproduce:
1. Create a base layout template;
2. Create a child template that extends the base one;
3. Comment the `@extends` directive;

Example:
```
{{-- @extends('layouts.app') --}}

@section('content')
<div class="col-md-10">
    <div class="panel panel-default">
        <div class="panel-heading">@lang('Dashboard::admin.module')</div>

        <div class="panel-body">
            Use this module to showcase statistics for your website.
        </div>
    </div>
</div>
@endsection
```

**Comment by themsaid** [comment]
refer to https://github.com/laravel/framework/issues/16688
