### ISSUE TITLE
update psysh to v0.8 on v5.1

### ISSUE THREAD

**Issue by icfr** [laravel/framework#16773]
- Laravel Version: 5.1.*
- PHP Version:all

### Description:
many package require nikic/php-parser v3 and on v5.1 we cant install pacakge that need it 

v0.8 of psy/psysh support v3 (v5.3 allready support v0.8)

**Comment by GrahamCampbell** [comment]
> many package require nikic/php-parser v3

Packages should attempt to support multiple versions of php parser instead of just mindlessly upgrading.

> v0.8 of psy/psysh support v3 (v5.3 allready support v0.8)

Yeh, though that's technically a new feature, and 5.1 is "LTS". We could technically support it I guess, but we don't want people complaining that stuff broke.

**Comment by icfr** [comment]
psysh is used for tinker so used in dev environment i think there is no problem in production environment

**Comment by crynobone** [comment]
> psysh is used for tinker so used in dev environment i think there is no problem in production environment

But niche developer might have other requirement to use `psysh` in their project, which still could cause issues.

**Comment by GrahamCampbell** [comment]
I wouldn't recommend starting a project on Laravel 5.1 LTS. It's designed to give slow moving apps bug fixes and security assurance. It's not designed for people to be moving quickly with brand new packages. For these reasons, it's important that we do not brake the 5.1 branch with unneeded upgrades.

---

Disclaimer, these words are my own, and do not necessarily reflect the views of Taylor.
