### ISSUE TITLE
Lang::has('posts.title', 'ar', false) return true when it should not.

### ISSUE THREAD

**Issue by malhayek2014** [laravel/framework#16774]
- Laravel Version: 5.3.26
- PHP Version: 5.6.24
- Database Driver & Version: NA

### Description:

I am trying to determine if a specific language has a giving key or not. In this case I don't want to fail over to the default language. so if the default language does not have a specific key `false` should be returned.

Based on the data I have in my files, the following should return true "as it should"

    Lang::has('posts.title', 'en', false);

However, the following should return `false` but is returning true instead.

    Lang::has('posts.title', 'ar', false);

### Steps To Reproduce:
Create a file called posts.php in the following path \resources\lang\ar. In this file, place the following content

    <?php

    return [
        'no_title' => 'Some Value',
    ];

Then, create a file called posts.php in the following path \resources\lang\en. In this file, place the following content

    <?php

    return [
         'title' => 'Some Other Value',
    ];

Here is a screenshot of the file I have in my `lang` folder

Finally, I suggest you name the folder `lang` to `languages` or `langs` since it can contains more than one language.

![screenshot_13](https://cloud.githubusercontent.com/assets/6562258/21121707/ba700c2a-c082-11e6-9c4b-580ac8d8f1b2.png)

**Comment by arcanedev-maroc** [comment]
Hi @malhayek2014, you need to use same key. 

Try `title` instead of `no_title` in your `resources\lang\ar\posts.php` file.

**Comment by fernandobandeira** [comment]
IDK why this was closed, OP is describing a bug with the

```php
Lang::has('posts.title', 'ar', false); //returns true, should return false
```

Related old issue #2607

@malhayek2014 What do you get when running:

```php
Lang::get('posts.title',[], 'ar', false);
```
