### ISSUE TITLE
[5.3] No exception thrown on reference to missing column

### ISSUE THREAD

**Issue by archfrog** [laravel/framework#16789]
- Laravel Version: 5.3.26
- PHP Version: 7.0.8-3ubuntu3
- Database Driver & Version: MariaDB/10.0.28

### Description:
I occasionally get bitten by incorrect select clauses to Eloquent:

    $found = Message::select('col1', 'col2')->where('cheese', '<>', 'cake')->first();
    dd($found->col3);

The problem here being that there's no col3 in the select statement.  Laravel v5.3.26 returns NULL for col3 instead of throwing an exception to indicate that there's something seriously wrong with the code.

I **love** Laravel but this particular "feature" I hate intensely.  If you rename a database column, you're in for a tough ride trying to figure out if you succesfully corrected all code that referenced the column.

In general, I think Laravel should fail with an exception if an attempt is made to read a column not implicitly or explicitly assigned.
    
### Steps To Reproduce:
I believe you can do any first()/get() query on any table and after that reference a non-existing field and the operation will succeed, yielding NULL, instead of throwing an exception.

**Comment by lagbox** [comment]
You might think you are adding some 'sanity' type check but you actually have added a ton of extra work. Every single attribute EVER would have to be 'checked' some how to see if it exists before it could be accessed. You can't 'assume' they will be there, so they have to be checked, BEFORE accessing them.

So you just added some type of conditional/try-catch around every possible place an attribute needs to be accessed.

**Comment by archfrog** [comment]
I think you are misunderstanding me :-)  

As it is now, you are always at risk at writing some code that APPEARS to work, but doesn't work at all.  If you make a migration that removes a database column, or renames it, your code will happily appear to work until you realize that it doesn't work at all.

If Laravel threw an exception, you'd at least know that there was some serious issue to take care of.

I don't care if it is a Laravel exception that is thrown or not.  If coded correctly, PHP will report the error at no extra cost.

**Comment by themsaid** [comment]
Models has accessors that aren't database columns & also relations. Throwing an exception if the column doesn't exist doesn't make any sense.

For suggestions and feature requests please use the https://github.com/laravel/internals repo, this repo is for bug reporting only.

Thanks anyway :)
