### ISSUE TITLE
Proposal: Add Queue::dispatch callback

### ISSUE THREAD

**Issue by dcro** [laravel/framework#16784]
Currently, in the latest Laravel version (5.3) the Queue does not have any ability to catch a job when it's dispatched so it can be altered or logged.

My proposal would be to introduce a new `Queue::dispatch` callback that's similar to `Queue::before` and `Queue:after`. The callback code should be allowed to modify the connection on which the job should be dispatched, the job itself as well as any job payload metadata.

Although this callback could have multiple applications in both logging as well as altering the job, my specific use case is this: In a multi-tenant application I need to be able to add additional tenant specific metadata to the job payload so that I can access that metadata later in the `Queue::before` and `Queue:after` callbacks to figure out the tenant which dispatched the job (the app runs a single queue worker for all the tenants).

The above can't be achieved by simply adding some fields to the job itself as the solution needs to be able to work for jobs dispatched by any third-party package (e.g. by Laravel Scout) not just by the app's code. Right now the only solution seems to be to override the Queue driver Connector class and the Queue class for each driver used in the app, to get access to the `createPayload` method.

Looking forward to hear your thoughts on this. If this does seem like something that would be accepted in a future version, I can look into putting together a pull request with the required changes.

**Comment by themsaid** [comment]
Thank you but for suggestions and feature requests please use the https://github.com/laravel/internals repo.

Sorry :) We try to keep this repo for bug reporting only.
