### ISSUE TITLE
Throttle middleware counting wrong when using it multiple times

### ISSUE THREAD

**Issue by Sopamo** [laravel/framework#16786]
- Laravel Version: 5.3.x (I think 5.2 as well)

### Description:
When using the throttle middleware more than once it decreases the remaining limit by one for each throttle middleware that is used. This is because the middleware doesn't check if a request already has been throttled.
I'm using the throttle middleware multiple times because I have a global one and another one which is less forgiving for specific routes which are prone to be abused.

### Steps To Reproduce:
 - Setup a global throttle middleware
 - Setup a route group with another throttle middleware
 - Call a route in the route group, the X-RateLimit-Remaining will decrease by two instead of one every time

I think the fix is rather simple by adding a list of already throttled request signatures and checking against it before checking the limiter. I can create a pull request if you want.

**Comment by GrahamCampbell** [comment]
The bug is that you're using the middleware twice. I'd say this is definitely the expected behaviour, having two hits.

**Comment by GrahamCampbell** [comment]
You're free to of course extend the middleware in your app, for whatever works for you. Our default one won't be what everyone wants.

**Comment by saifuldhaka** [comment]
i used to to protect login attempts more then limit, my question is when this count reset again. is it like if i login successfully it reset the previous failed login attempts ?
