### ISSUE TITLE
Congratulations on being in top most active Github communities!

### ISSUE THREAD

**Issue by buger** [laravel/framework#16785]
Hello there!

It's been a damn good year!

Last month laravel project had over 480 active community members, which is higher than node, rails or even react. Especially remarkable considering the fact that you have no too much stars!

You can see your stats here:
https://ossmetrics.com/leaderboard
https://ossmetrics.com/laravel/framework

Wish you a happy new year and continue to be awesome!

**Comment by GrahamCampbell** [comment]
:+1:
