### ISSUE TITLE
save() and create() not working as expected

### ISSUE THREAD

**Issue by allok** [laravel/framework#16782]
- Laravel Version: 5.3.26
- PHP Version: 5.6.12
- Database Driver & Version: MySQL 5.6.26

### Description:
'**exists**' property on model wrong indicates if the model exists.
We need to know if a model really created.
**You can check example**: https://github.com/allok/laravel/commit/c3ad907f7f9b9a0118326ebe3d2eede9ec3241a6
:1234: Config db, migrate and run  'php artisan test'

### Steps To Reproduce:
Example migration for model buyer_users (user - default model):
```php
        Schema::create('buyer_users', function (Blueprint $table) {
            $table->unsignedInteger('user_id')->primary();
            $table->text('favorite_json')->nullable();
        });
```
Model should be with:
```php   
    protected $primaryKey = 'user_id';
    public $incrementing = false;
```
And if we try to create a model through save():
```php
            $buyer = new BuyerUser;
            $result = $buyer->save();
            var_dump($buyer->exists, $result); // both values will be 'true'
```
or create():
```php
            $buyer = BuyerUser::create();
            var_dump($buyer->exists, !!$buyer); // both values will be 'true'
```
But the real row does not exists in DB.

**Comment by sagarrabadiya** [comment]
i think if you don't have given default values to your db table columns it will throw `SQLSTATE` exception and if you have assigned default values to your db table columns row will be created with that default value.

**Comment by allok** [comment]
@sagarrabadiya 
You can see thay I have:
 **$table->unsignedInteger('user_id')->primary();**
It has not default value.

**Comment by sagarrabadiya** [comment]
in that case it should throw `SQLSTATE` exception

**Comment by allok** [comment]
@sagarrabadiya No. I don't have exception.

**Comment by allok** [comment]
**Check please my example** commit https://github.com/allok/laravel/commit/c3ad907f7f9b9a0118326ebe3d2eede9ec3241a6

**Comment by themsaid** [comment]
Unable to reproduce, please provide a simple example I can use on a fresh laravel 5.3 installation.

**Comment by themsaid** [comment]
ping @allok

**Comment by allok** [comment]
Look example in my repository https://github.com/allok/laravel

**Comment by themsaid** [comment]
Submitted a PR with a fix https://github.com/laravel/framework/pull/16864

Thank you so much :)
