### ISSUE TITLE
Tests: `->seeJson()` breaks when not json is returned

### ISSUE THREAD

**Issue by cweiske** [laravel/framework#16793]
- Laravel Version: 5.3.22
- PHP Version: 7.0.8

### Description:
When non-json data is returned, the `->seeJson()` method breaks and outputs a non-helpful warning:

> There was 1 error:
> 
> 1) Api_ProducerDb_ProducerTest::testCreate
> ErrorException: Invalid argument supplied for foreach()
> 
> /var/www/vendor/laravel/framework/src/Illuminate/Support/Arr.php:480
> /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:297
> /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:323
> /var/www/tests/Api_ProducerDb_ProducerTest.php:24

It should be tested if the returned content is really json, or at least if it's an array/object.

### Steps To Reproduce:
Create an API that returns a "401 Unauthorized" status code with body content "Unauthorized" and try to unit-test it:

```
$this->json('POST, '/api/foo', ['foo' => 'bar'])->seeJson(['foo' => 'bar'])
```

**Comment by lasselehtinen** [comment]
I've bumped in to same issue. It tries to pass the response to validation even though it is not JSON. If you look at the [current implementation of seeJson](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php#L313) you can see that there is actually check in place but it is only done if the if you use seeJson without passing any data.

Could this be changed to something where Laravel would always check that the response is JSON before continuing with the validation? This would provide a bit more meaningful error message.

**Comment by srmklive** [comment]
I have added a PR for this [here](https://github.com/laravel/framework/pull/16816).

**Comment by cweiske** [comment]
@GrahamCampbell: could you please explain why you closed this bug report?

**Comment by GrahamCampbell** [comment]
Closed once there is an open pr.

**Comment by cweiske** [comment]
The PR has been closed in the meantime, without being merged. Could you please reopen this issue?
