### ISSUE TITLE
Cannot adjust/disable login attempts

### ISSUE THREAD

**Issue by shrimpwagon** [laravel/framework#16801]
- Laravel Version: 5.3.16
- PHP Version: 5.6.28
- Database Driver & Version: MySQL 5.5.53

### Description:
Just can't seem to adjust or disable max login attempts. I've look all over and there seems to be no way to disable. It looks like it is hard-coded at 5, see: https://github.com/laravel/framework/blob/5.3/src/Illuminate/Foundation/Auth/ThrottlesLogins.php#L22

Can this be a config.auth setting? Like set to 0 to disabled max logins?

### Steps To Reproduce:
Simply try to log in too many times.

**Comment by srmklive** [comment]
If you want to disable login throttling, then you can remove the `ThrottleLogins` trait. However if you want to  increase max login attempts, then you need to override the function you mentioned in your `LoginController`.
