### ISSUE TITLE
php-cs-fixer 2.0.0 gives a fatal error 

### ISSUE THREAD

**Issue by jsq937** [laravel/framework#16811]
- Laravel Version: 5.3.26
- PHP Version: 7.1.0
- Database Driver & Version: MySQL 5.7.16
- php-cs-fixer: 2.0.0

### Description:
`php-cs-fixer fix` gives a fatal error when `php-cs-fixer` >= `2.0.0`.

### Steps To Reproduce:
1. `php-cs-fixer fix`

**Comment by GrahamCampbell** [comment]
The config we have doesn't work for php-cs-fixer 2.x. I'm in favour of just removing the config. We don't care if PRs pass cs checks, because StyleCI automatically commits the fixes on merge.

**Comment by GrahamCampbell** [comment]
Our php-cs-fixer config is outdated anyway, and doesn't match the current rules.
