### ISSUE TITLE
Call to undefined function sisventas\Http\Controllers\public_patch()

### ISSUE THREAD

**Issue by vhngroup** [laravel/framework#16820]
- Laravel Version: 5.3.26
- PHP Version: 5.6.28
- Database Driver & Version:
Apache/2.4.23 (Win32) OpenSSL/1.0.2h PHP/5.6.28
Versión del cliente de base de datos: libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: 76b08b24596e12d4553bd41fc93cccd5bac2fe7a $
extensión PHP: mysqli

### Description:

Hello, a few days ago my module of registering articles worked perfectly, in the options of creating and editing.
Now, when I try to assign a product image to a product, I get the following error.
FatalErrorException in ArticoController.php line 80:
Call to undefined function sisventas \ Http \ Controllers \ public_patch ()

I attach the code of the view and the controller, thank you, can give me the lights of this error.
Thank you very much.

File ArticuloController.php

File View Edit.B
[ArticuloController.php.txt](https://github.com/laravel/framework/files/655388/ArticuloController.php.txt)
[edit.blade.php.txt](https://github.com/laravel/framework/files/655395/edit.blade.php.txt)

lade.php

**Comment by GrahamCampbell** [comment]
That's php's way of saying the global function `public_patch` doesn't exist (and it also checked in the current namespace, hence that error message).

**Comment by GrahamCampbell** [comment]
Did you mean `public_path`, rather than `public_patch`?

https://github.com/laravel/framework/blob/v5.3.26/src/Illuminate/Foundation/helpers.php#L580-L589

**Comment by vhngroup** [comment]
Hi, is public_patch
The solution, remove:
use Validator;
Thanks @GrahamCampbell
