### ISSUE TITLE
Rule validator wont pass

### ISSUE THREAD

**Issue by oriceon** [laravel/framework#16828]
- Laravel Version: 5.3.28
- PHP Version: 7.0.12

### Description:
Validator rule date_format:H:i wont pass.

**Comment by GrahamCampbell** [comment]
Please provide more information.

**Comment by oriceon** [comment]
@GrahamCampbell i send an input with value 8:00 and trying to validate using rule date_format:H:i and now with last version wont pass validator. With oldest 5.3 works at is should.

**Comment by GrahamCampbell** [comment]
Please can you find the version it broke in?

**Comment by oriceon** [comment]
It is in first comment. It is about last one, laravel 5.3.28

**Comment by themsaid** [comment]
This seems to work:

```
Validator::make(
        [
            "time" => '06:23'
        ],
        [
            'time' => 'date_format:H:i'
        ])
```

Please share the broken case.

**Comment by oriceon** [comment]
@themsaid Thanks for your comment. I`ve tested again and see that doesn`t work with time like am/pm: 9:00 only with 24 h format 09:00 ..

**Comment by themsaid** [comment]
`9:00` should fail for `H:i` yes, it's expected.

**Comment by oriceon** [comment]
Ya, maibe i'll try G:i :)

**Comment by themsaid** [comment]
Yup http://php.net/manual/en/function.date.php :)
