### ISSUE TITLE
Error when using before validation for negative timestamps (generated by strtotime)

### ISSUE THREAD

**Issue by laurovalente** [laravel/framework#16832]
- Laravel Version: 5.3
- PHP Version: 7
- Database Driver & Version: N/A

### Description:
When using negative timestamps generated by strtotime, the before rule cannot validate correctly.
Solution suggestion is below.

### Steps To Reproduce:

```
    $validator = Validator::make($data, [
        'birthday' => sprintf('required|date_format:Y-m-d|after:%s|before:%s',
                                     strtotime('-100 years'),
                                     strtotime('today'))
        ]);
    $validator->fails();
```

### Possible fix

In this line https://github.com/laravel/framework/blob/5.3/src/Illuminate/Validation/Validator.php#L1973

Try to build a DateTime with this code:

```
    $dt = new DateTime();
    $dt->setTimestamp($value);
    return $dt;
```

**Comment by GrahamCampbell** [comment]
Thanks for reporting. Discussion can continue in one place on the PR. :)
