### ISSUE TITLE
[5.3] Performance issue when calling Eloquent model getAttribute() thousands times

### ISSUE THREAD

**Issue by cedricdo** [laravel/framework#16836]
- Laravel Version: 5.3
- PHP Version: 5.5
- Database Driver & Version: MySQL 5.5, using PDO Mysql

### Description:
Hi,

It's not really an issue i've but a question. Unfortunately i've to deal with old server in hardware as well as php version. Upgrading is not really an option.
I'm using eloquent and on a large page, i fetch about 1 000 eloquent models and also have a very huge view which calls a lot of attributes of these models. The performance are not that terrible, about 1.4s to load, but could be improved. When profiling the page, i found that most of the execution time is spent on Illuminate\Database\Eloquent\Model::__get() (and others method behind such as hasCast(), ...) which is called about 11 0000 times. 
Behind __get(), a lot of method are called much more such as hasCasts(), hasMutator(), ... and here relies the bottleneck.

Is it necessary to call these method each time we want to get an attribute ?
Cast, mutator, accessor and others stuff checked by __get() method are defined once on the class and are never redefined if i'm correct. So is there any potentiel issue to cache the result of __get() the first time and remove the attribute from the cache when calling __set() ?

This very simple trick reduced the numebr of method call and the page load time (between 30 and 40%) :
```php
use Illuminate\Database\Eloquent\Model;

class CachedModel extends Model
{
    protected $cache = [];
    public function __get($name)
    {
        if (!isset($this->cache[$name])) {
            $this->cache[$name] = parent::__get($name);
        }

        return $this->cache[$name];
    }

    public function __set($name, $value)
    {
        if (isset($this->cache[$name])) {
            unset($this->cache[$name]);
        }

        parent::__set($name, $value);
    }
}
```

Thanks for your response.

**Comment by themsaid** [comment]
That depends on how you use it, if you simply call the property 1 time then caching is meaningless. Anyway, feel free to propose a PR with the changes proposed and for performance issues like this I recommend that you attach some profiling information.
