### ISSUE TITLE
v5.1.33  app_path function returns wrong path after change psr4

### ISSUE THREAD

**Issue by elrufoelrufo** [laravel/framework#16833]
Hello,

I'm having the following error after change psr4 path, in composer.json in a fresh laravel 5.1.* installation. Looks like app_path function is returning a wrong path. I've been searching but I don't find anything about it. Can anyone help me? Thanks!!

**RouteServiceProvider.php**
```
    /**
     * Define the routes for the application.
     *
     * @param  \Illuminate\Routing\Router  $router
     * @return void
     */
    public function map(Router $router)
    {
        $router->group(['namespace' => $this->namespace], function ($router) {
            require app_path('Http/routes.php');
        });
    }
}
```

**Error Log :** 
PHP Warning:  Uncaught exception 'ErrorException' with message 'require(/var/www/Radio/app/Http/routes.php): failed to open stream: No such file or directory' in /var/www/Radio/api/Providers/RouteServiceProvider.php:41
Stack trace:
#0 /var/www/Radio/api/Providers/RouteServiceProvider.php(41): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'require(/var/ww...', '/var/www/Radio/...', 41, Array)
#1 /var/www/Radio/api/Providers/RouteServiceProvider.php(41): App\Providers\RouteServiceProvider::App\Providers\{closure}()
#2 [internal function]: App\Providers\RouteServiceProvider->App\Providers\{closure}(Object(Illuminate\Routing\Router))
#3 /var/www/Radio/vendor/laravel/framework/src/Illuminate/Routing/Router.php(354): call_user_func(Object(Closure), Object(Illuminate\Routing\Router))
#4 /var/www/Radio/api/Providers/RouteServiceProvider.php(42): Illuminate\Routing\Router->group(Array, Object(Closure))
#5 [internal function]: App\Providers\RouteServiceProvider->map(Object(Illuminate\Routing\Router))
#6 /var/www/R in /var/www/Radio/api/Providers/RouteServiceProvider.php on line 41
PHP Fatal error:  App\Providers\RouteServiceProvider::App\Providers\{closure}(): Failed opening required '/var/www/Radio/app/Http/routes.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/Radio/api/Providers/RouteServiceProvider.php on line 41

                                                                                                                                                                                 
  [Symfony\Component\Debug\Exception\FatalErrorException]                                                                                                                        
  App\Providers\RouteServiceProvider::App\Providers\{closure}(): Failed opening required '/var/www/Radio/app/Http/routes.php' (include_path='.:/usr/share/php:/usr/share/pear')  
                                                                                                                                                                                 

**Steps To Reproduce:**

In the terminal use the following command to create the fresh project : 
`composer create-project laravel/laravel Radio "5.1.*"`
Go to project folder : 
`cd Radio/`
Rename app to api : 
`mv app api`
Edit composer.json
`nano composer.json `
```
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "api/"
        }
    },
```
Reload the changes : 
`composer dump-autoload`
Test the changes : 
`php artisan route:list`

And get the error log above.

**Comment by GrahamCampbell** [comment]
> Rename app to api

We don't support renaming that folder, sorry.

**Comment by AAJoelle** [comment]
check. you might have deleted your routes folder

**Comment by pavinthan** [comment]
Because app not excites in your project, you can change the RouteServiceProvider.php with
`
    /**
     * Define the routes for the application.
     *
     * @param  \Illuminate\Routing\Router  $router
     * @return void
     */
    public function map(Router $router)
    {
        $router->group(['namespace' => $this->namespace], function ($router) {
            require base_path('api/Http/routes.php');
        });
    }
}
` 
but it's not a best practices.
