### ISSUE TITLE
[5.3] Notification - Unable to  BroadcastNow

### ISSUE THREAD

**Issue by lukepolo** [laravel/framework#16844]
- Laravel Version: 5.3.28
- PHP Version:7.0
- Database Driver & Version: N/A

### Description:
I need to broadcast the event now rather than through the queue. There is currently no way to say it should broadcast now.

### Steps To Reproduce:
Create a new notification , looked through the api saw 

`class BroadcastNotificationCreated implements ShouldBroadcast`

### Suggested Solution (may write a PR for it depending if you think its the right way) :

Would need to make another class saying it should implement `ShouldBroadcastNow`, unless reflection classes can add interfaces?

**Comment by themsaid** [comment]
Submitted a PR for that https://github.com/laravel/framework/pull/16867

Let's continue the discussion there

Thank you :)
