### ISSUE TITLE
Target [Illuminate\\Contracts\\Debug\\ExceptionHandler] is not instantiable.

### ISSUE THREAD

**Issue by Milewski** [laravel/framework#16856]
i Keep getting this error, when trying to do anything related to the database like... `User::first()`. i don't seen to figure out what is wrong.

```
Target [Illuminate\\Contracts\\Debug\\ExceptionHandler] is not instantiable.
```

and the interesting thing is i am using docker for building my production/dev server.. On my Dev i only `docker-compose up` and everything just works... however on the production server using the exactly same formula to build my containers... it keeps throwing that exception which i have no idea the reason it is being throw. 

i did some testing like

- [x] Mysql is working? and properly configured?
- [x] Are all the the packages version matching?
- [x] Php includes all dependencies laravel needs?

The real only difference between my dev and prod server is.... my **Dev host is a MAC OS** and my **Prod host is a Linux Ubuntu**.. however i don't think this would impact in anything as i am running both on the same linux machine architecture inside a docker container. 

in shorts... this is falling

```
$capsule = new Capsule;

$capsule->addConnection([...]);
$capsule->setAsGlobal();
$capsule->bootEloquent();

$users = $capsule->table('users')->get(); // <- throw exception..
```

Note*

Im using the eloquent outside of laravel.. and booting it up as advised [here](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/README.md)

**Comment by sisve** [comment]
Do you get a complete stack trace? This happens when an exception occurs, and for some reason the ExceptionHandler is unavailable. Could it be wrong database credentials or a missing database table?

**Comment by Milewski** [comment]
This is the stack trace, i have tested using the same code from my local connecting to my remote host database, user, pass, ip, port connects successfully also insert/delete/create works perfectly, however moving the whole code to the server seems throw this exception... 

as i am not using the entire laravel framework so i don't have the ExceptionHandler registered.

```
BindingResolutionException {#96 ▼
  #message: "Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable."
  #code: 0
  #file: "/var/www/housekeeper/vendor/illuminate/container/Container.php"
  #line: 763
  -trace: {▼
    /var/www/housekeeper/vendor/illuminate/container/Container.php:763: {▼
      : 
      :     throw new BindingResolutionException($message);
      : }
    }
    /var/www/housekeeper/vendor/illuminate/container/Container.php:644: {▼
      : if ($this->isBuildable($concrete, $abstract)) {
      :     $object = $this->build($concrete, $parameters);
      : } else {
      arguments: {▶}
    }
    /var/www/housekeeper/vendor/illuminate/database/Connectors/ConnectionFactory.php:130: {▼
      : if (count($hosts) - 1 === $key) {
      :     $this->container->make(ExceptionHandler::class)->report($e);
      : }
      arguments: {▶}
    }
    Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}(): {}
    /var/www/housekeeper/vendor/illuminate/database/Connection.php:964: {▼
      : if ($this->pdo instanceof Closure) {
      :     return $this->pdo = call_user_func($this->pdo);
      : }
      arguments: {▶}
    }
    /var/www/housekeeper/vendor/illuminate/database/Connection.php:832: {▼
      : {
      :     if (is_null($this->getPdo()) || is_null($this->getReadPdo())) {
      :         $this->reconnect();
    }
    /var/www/housekeeper/vendor/illuminate/database/Connection.php:717: {▼
      : {
      :     $this->reconnectIfMissingConnection();
      : 
    }
    /var/www/housekeeper/vendor/illuminate/database/Connection.php:350: {▼
      :             : $statement->fetchAll($fetchMode);
      :     });
      : }
      arguments: {▶}
    }
    /var/www/housekeeper/vendor/illuminate/database/Query/Builder.php:1648: {▼
      : {
      :     return $this->connection->select($this->toSql(), $this->getBindings(), ! $this->useWritePdo);
      : }
      arguments: {▶}
    }
    /var/www/housekeeper/vendor/illuminate/database/Query/Builder.php:1634: {▼
      : 
      : $results = $this->processor->processSelect($this, $this->runSelect());
      : 
    }
    /var/www/housekeeper/apps/Api/Controllers/ControllerBase.php:31: {▼
      : 
      : dd($capsule->table('users')->get());
      : 
    }
    HouseKeeper\Api\Controllers\ControllerBase->initialize(): {}
    Phalcon\Dispatcher->_dispatch(): {}
    Phalcon\Dispatcher->dispatch(): {}
    /var/www/housekeeper/public/index.php:33: {▼
      : 
      : echo $application->handle()->getContent();
      : 
    }
  }
}
```

**Comment by themsaid** [comment]
@Milewski IMO it's better that you post on forums, it doesn't seem to be a problem with the framework as far as I can tell.

**Comment by Milewski** [comment]
Okay i found the reason of the issue... some bug was introduced in the version [5.3.23](https://github.com/laravel/framework/blob/v5.3.23/src/Illuminate/Database/Connectors/ConnectionFactory.php) rolling back to or going to 5.3.28 solved the issue
