### ISSUE TITLE
Validator date_format:U always fails

### ISSUE THREAD

**Issue by neurogas** [laravel/framework#16859]
- Laravel Version: 5.3.28
- PHP Version: 7.0
- Database Driver & Version: MariaDB 10.1.16

### Description:
After updating laravel via composer:
  - Updating nikic/php-parser (v2.1.1 => v3.0.2)
  - Updating psy/psysh (v0.7.2 => v0.8.0)
  - Updating laravel/framework (v5.3.26 => v5.3.28)

Validator date_format:U always fails

### How to reproduce:
```
    $validator = \Validator::make(["start" => 1482143579], [
        'start' => 'required|date_format:U'
    ]);

    if ($validator->fails()) {
        $errors = array_map(function($items) {
            return implode(" - ", $items);
        }, array_values($validator->errors()->getMessages()));

        var_dump($errors);
    }
```

**Comment by themsaid** [comment]
```
$validator = Validator::make(
        [
            "start" => '1482143579'
        ],
        [
            'start' => 'date_format:U'
        ]);
```

I don't seem to be able to reproduce.

**Comment by themsaid** [comment]
It's probably because you're passing an integer instead of a string. Anyway the change was reverted on 5.3 and re-submitted to 5.4. Your issue will be cleared on the next 5.3 patch.

**Comment by neurogas** [comment]
Thank you for the clarification!

Il 19 dic 2016 1:46 PM, "Mohamed Said" <notifications@github.com> ha
scritto:
