### ISSUE TITLE
Laravel 5.3 Error: Unauthenticated Guard issue, could be an easy fix

### ISSUE THREAD

**Issue by dreferreira** [laravel/framework#16855]
- Laravel Version: 5.3.28
- PHP Version: 7.0.2
- Database Driver & Version: mysql

I've come across an interesting issue with our system. I'm running Laravel 5.3.28 and am successfully using the initial authentication routes that come with laravel out-of-the-box. In addition I've successfully set up and am using passport as well. A person is able to both log in and/or register onto the system and receive an access token in both cases, however:

**The problem**

The GET /user route keeps returning an 401 unauthenticated error.

**What I've done**

Inside of my App/Http/Middleware/Authenticate.php file I have a method authenticate(array $guards).

        /**
         * Determine if the user is logged in to any of the given guards.
         *
         * @param  array  $guards
         * @return void
         *
         *  @throws \Illuminate\Auth\AuthenticationException
         */
         protected function authenticate(array $guards)
         {
         if (empty($guards)) {
         return $this->auth->authenticate();
         }

         foreach ($guards as $guard) {

         if ($this->auth->guard($guard)->check()) {
            return $this->auth->shouldUse($guard);
         }
         }
         //Error Thrown on line below
         throw new AuthenticationException;
         }

As noted above in the comment, the error is thrown there. What I'm confused about is that the $guard variable contains the guard string: 'api'. When it's ran through the check() method the $this->user() (used inside of check()) returns null which then makes $this->auth->guard($guard)->check() return false.

**Note**

$this->user() is used in check() which is a method found in vendor/laravel/framework/src/Illuminate/Auth/RequestGuard.php.

In the end, I'm a little stuck here and in need of some assistance. If more information is needed please ask and I will provide as much as I can. Is there something specific I may have missed here? Maybe in the Login or registration?

Thank you in advance.

**Update 1**

Diving a bit further I went into the vendor\illuminate\auth\RequestGuard.php file and found that the attempt to get the user for the check method mentioned above was returning null:

**RequestGuard.php Class**

        namespace Illuminate\Auth;

        use Illuminate\Http\Request;
        use Illuminate\Contracts\Auth\Guard;

        class RequestGuard implements Guard
        {
        /**
         * Get the currently authenticated user.
         *
         * @return \Illuminate\Contracts\Auth\Authenticatable|null
         */
        public function user()
        {
            // If we've already retrieved the user for the current request we can just
            // return it back immediately. We do not want to fetch the user data on
            // every call to this method because that would be tremendously slow.
            if (! is_null($this->user)) {
                return $this->user;
            }

            return $this->user = call_user_func($this->callback, $this->request); <-- returns null here
            }

**Comment by themsaid** [comment]
> method the $this->user() (used inside of check()) returns null

It means the user isn't authenticated, make sure you pass a valid token while attempting the request.
