### ISSUE TITLE
[5.3.28] morphMany "has" methods not working on self relation

### ISSUE THREAD

**Issue by team5ru** [laravel/framework#16861]
- Laravel Version: 5.3.28
- PHP Version: 7.0
- Database Driver & Version: mysql

### Description:
I have "Comment" Eloquent with morphMany and morphTo "comments".
This relation not working for methods "has", "whereHas" and other.
For example:
```
Comment::has('comments')->toSql()
```
gives query
```
select * from `comments` 
	where exists
		(select * from `comments` as `laravel_reserved_3`
			where `laravel_reserved_3`.`commentable_id` = `comments`.`id`
			and `comments`.`commentable_type` = ?)
```
In the last line should be **laravel_reserved_3** instead **comments**
### Steps To Reproduce:
1. Create eloquent 
```
class Comment extends Model
{
    public function comments()
    {
        return $this->morphMany('App\Comment', 'commentable');
    }
    public function commentable () {
        return $this->morphTo();
    }
}
```
2. Try
```
Comment::has('comments')->toSql()
```

**Comment by fernandobandeira** [comment]
Check #5429, currently was closed down as a ``` no-fix ```

**Comment by team5ru** [comment]
I am completely disagree. All we need, rewrite a little `Illuminate\Database\Eloquent\Relations\HasOneOrMany.php`
line 89 `getRelationQueryForSelfRelation`.
There should be `laravel_reserved_` for morp type column. I think it is possible.

**Comment by themsaid** [comment]
@team5ru can you submit a PR with some tests that shows the issue and how to fix?

**Comment by team5ru** [comment]
Not in working time. On weekends.

**Comment by themsaid** [comment]
Closing this then since it was marked as no-fix before, but please submit a PR if you have a fix.
