### ISSUE TITLE
Should elixir() helper function return full URL?

### ISSUE THREAD

**Issue by phy25** [laravel/framework#16862]
The current elixir() only returns `/build/dist/...` without site prefix. Improper use of this (directly use `elixir()` in style HTML tag) in blade templates leads to wrong URL in cases where Laravel is not installed at the root of the website.

I don't know whether the default behavior of this helper function should change (to `url(elixir())`), because I don't know whether there are any other use cases rather than in blade templates.

**Comment by GrahamCampbell** [comment]
Thanks, but this was already proposed. Please see the previous issues/PRs.

**Comment by phy25** [comment]
Sorry about that, I have searched but did not read through years... #8565
