### ISSUE TITLE
[5.2] throttle , restricted number of visits is wrong

### ISSUE THREAD

**Issue by agclqq** [laravel/framework#16860]
- Laravel Version: 5.2.*
- PHP Version:5.6
- Database Driver & Version:

### Description:
Default throttle middleware。

The same IP access to different addresses, a total of more than 60 times, the page displays "Too Many Attempts."

This should not be desirable。

#### step1
```
Route::group(['middleware' => ['api']], function () {
    Route::resource("test", "TestController");
});
```
#### step2
http://mytest.com/test/a   access  31 times
http://mytest.com/test/b   access  30 times

the page displays "Too Many Attempts."  This is not what I want.
#### step3
I found the following code seems to be a problem.

Illuminate/Http/Request.php
```
    public function fingerprint()
    {
        if (! $this->route()) {
            throw new RuntimeException('Unable to generate fingerprint. Route unavailable.');
        }
        return sha1(
            implode('|', $this->route()->methods()).
            '|'.$this->route()->domain().
            '|'.$this->route()->uri().
            '|'.$this->ip()
        );
    }
```
After debugging I found:
- `$this->route()->domain()` is null;
- `$this->route()->uri()` is test/{test};

Why is this?

**Comment by themsaid** [comment]
Please upgrade to 5.3 as 5.2 is not supported anymore.

**Comment by mbaeuerle** [comment]
@agclqq did you solve the issue by upgrading? Because I have the same issue in Laravel 5.4. The `$route->uri()` returns the uri with placeholders. In my opinion this should rather be replaced with `$this->decodedPath()` where the actual id is used.
