### ISSUE TITLE
failed scheduled tasks with withoutOverlapping() prevent further execution.

### ISSUE THREAD

**Issue by ovp87** [laravel/framework#16863]
If a task fails with the withoutOverlapping() method used, it will not cleanup the storage/framework/schedule-xxx file, thus preventing further execution of this task.

### Steps To Reproduce:
- Schedule a task that fails with withoutOverlapping() used.

**Comment by trip-somers** [comment]
If you don't mind my asking, why was this closed?

I came to investigate this problem before reporting it myself. I know this was an issue in 5.1, and I don't see any commits on 5.2 or 5.3 that would fix this. Did I miss something?

**Comment by HipsterJazzbo** [comment]
I've re-opened this issue: #18626
