### ISSUE TITLE
[5.2.32] specific attribute as input names causing instance to call methods 

### ISSUE THREAD

**Issue by VinceG** [laravel/framework#16874]
- Laravel Version: 5.2.32
- PHP Version: 7.0.8
- Database Driver & Version: MySQL 5.6

### Description:

This is something that happened as soon as we upgraded to Laravel 5.2.32 from 5.2.31 so the breaking change code is the following:

Model.php 5.2.31:
```
/**
     * Determine if an attribute exists on the model.
     *
     * @param  string  $key
     * @return bool
     */
    public function __isset($key)
    {
        return (isset($this->attributes[$key]) || isset($this->relations[$key])) ||
                ($this->hasGetMutator($key) && ! is_null($this->getAttributeValue($key)));
    }
```

Model.php 5.2.32
```
    /**
     * Determine if an attribute or relation exists on the model.
     *
     * @param  string  $key
     * @return bool
     */
    public function __isset($key)
    {
        if (isset($this->attributes[$key]) || isset($this->relations[$key])) {
            return true;
        }

        if (method_exists($this, $key) && $this->$key && isset($this->relations[$key])) {
            return true;
        }

        return $this->hasGetMutator($key) && ! is_null($this->getAttributeValue($key));
    }
```

What happens is, if we add an input, lets say a checkbox field

```
{{ Form::model((new \App\Article), [], ['class' => 'form-horizontal']) }}
{{ Form::checkbox('delete[1]', 1, false) }}
{{ Form::close() }}
```

This will only work when Form::model is used. if we use Form::open it wont happen.

And we have the following model as an example:

```
<?php

namespace App;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
  /**
   * The table associated with the model.
   *
   * @var string
   */
  protected $table = 'article';
}
```

The above code when executed will result in the following error:

```
ErrorException in Model.php line 2691:
Relationship method must return an object of type Illuminate\Database\Eloquent\Relations\Relation (View: /Users/vincentgabriel/Sites/app/resources/views/welcome.blade.php)
```

I kept trying and trying to see if this was something specific to our setup, but i just installed a new project, followed the above steps and was able to reproduce. it seems the change to the model to call methods if the attribute matches a method causing this issue.

If you change the checkbox name to 'find' 'get' etc. it'll do the same.

Can anyone confirm?

**Comment by GrahamCampbell** [comment]
This was changed again in a later version.

**Comment by VinceG** [comment]
@GrahamCampbell do you know which one? is there a change log between versions somewhere?

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/blob/5.3/CHANGELOG-5.2.md

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/commits/5.2/src/Illuminate/Database/Eloquent/Model.php

**Comment by VinceG** [comment]
@GrahamCampbell Thank You. However, i can still confirm this is happening on 5.2.45 (anything above 5.2.32) it does not happen on 5.3.28 (latest) since there is a return statement under getAttribute method if the method exists on the class itself.

This is still a bug.

**Comment by VinceG** [comment]
@GrahamCampbell This is the change that fixes it in 5.3.x
https://github.com/laravel/framework/commit/7ce97bec546d607ca207082722ceecabfbcc11a9#diff-d8e24a5815a26f7211e66db787be647f

**Comment by themsaid** [comment]
Well 5.2 is actually not supported any more, please upgrade to 5.3.

**Comment by VinceG** [comment]
@themsaid last 5.2 branch release was in late August. where can we see the branch support timeline?

**Comment by themsaid** [comment]
We dropped support for 5.2 shortly after 5.3 was released.

**Comment by fernandobandeira** [comment]
> For general releases, bug fixes are provided for 6 months and security fixes are provided for 1 year.

5.2 was released on 21 Dec 2015 so this week is the last one for security fixes if we follow that strictly, more info on https://laravel.com/docs/5.3/releases#support-policy

**Comment by VinceG** [comment]
@themsaid I see. Thanks.
