### ISSUE TITLE
Traits Issue's

### ISSUE THREAD

**Issue by azeem478** [laravel/framework#16886]
- Laravel Version: 5.3.2
- PHP Version:5.6.4
- Database Driver & Version:any

### Description: The New Fault in laravel 5.3 in my new installed project 

FatalErrorException in AuthController.php line 12:
Trait 'Illuminate\Foundation\Auth\AuthenticatesAndRegistersUsers' not found

so how can i fix this isse i update composer Illuminate folder files but same ! error

### Steps To Reproduce:
```
<?php

namespace App\Http\Controllers\Adminauth;

use App\User;
use Validator;
use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\ThrottlesLogins;
use Illuminate\Foundation\Auth\AuthenticatesAndRegistersUsers;
class AuthController extends Controller
{
    use AuthenticatesAndRegistersUsers, ThrottlesLogins;
    protected $redirectTo = '/dashboard';
    protected $guard='admin';
    public function showLoginForm()
    {
        if(Auth::guard('admin')->check())
        {
            return redirect('/dashboard');
        }
            return view('login');
    }
    // public function login(){
    //     Auth::guard('admin')->login();
    //     return view('/dashboard');
   //}
    public function logout()
    {
        Auth::guard('admin')->logout();
        return redirect('/');
    }
}

```

**Comment by lagbox** [comment]
In 5.3 by default the AuthController is now broken up into multiple controllers. That trait doesn't exist any more.

Check https://github.com/laravel/laravel/tree/master/app/Http/Controllers/Auth for reference.
