### ISSUE TITLE
[4.2] Support for php 7.1 - opensll extension for encyption

### ISSUE THREAD

**Issue by hoRacy** [laravel/framework#16884]
- Laravel Version: 4.2.22
- PHP Version: 7.1

### Description:
After upgading to PHP 7.1 site stops working with error:
Function mcrypt_get_iv_size() is deprecated

In  Laravel 4.2, encryption was handled by the mcrypt PHP extension which is deprecated in php 7.1
In Laravel 5.1, encryption is handled by the openssl extension. 

Maybe there's possibility to add openssl encrpytion handling to php 4.2?

**Comment by themsaid** [comment]
I don't think there are any plans to do this at the moment since 4.2 is not supported anymore :)

**Comment by hoRacy** [comment]
Ok, thx.
So - quick fix for any people who must use legacy laravel 4.2 :)
Just add on the beginning of \app\config\app.php 
**error_reporting(E_ALL ^ E_DEPRECATED);**

to override default laravel error catching, which interprets deprecated as ErrorException with all the whoops stuff.

**Comment by robclancy** [comment]
> I don't think there are any plans to do this at the moment since 4.2 is not supported anymore :)

This is exactly what was said about 7.0 and then a year later (too late) 7.0 support was added. Now there is an issue for 7.1 but back to "no support"? 

These deprecations should be suppressed.
