### ISSUE TITLE
Documentation for token auth driver

### ISSUE THREAD

**Issue by tjomamokrenko** [laravel/framework#16897]
- Laravel Version: 5.3

### Description:

Can't find docs for `Illuminate\Auth\TokenDriver`. Are there any at all?

_OAuth with it's refreshing sucks for most apps._ 

_Also: the old docs navigation was better._

**Comment by GrahamCampbell** [comment]
Please try asking on the forums. This isn't a good way to ask questions I'm afraid. Our issues on this repo are strictly to report bugs for the community at large to fix.
