### ISSUE TITLE
Laravel generating different tokens if multiple tabs are opened at same time

### ISSUE THREAD

**Issue by mgoebelm** [laravel/framework#16907]
- Laravel Version: 5.2
- nginx + laravel (file session driver and redis session driver)
- Local with vagrant (ubuntu) and Digital Ocean also.

### Description:
When open multiple tabs simultaneously there are different tokens generated, not a token to each tab, but if opens 8 tabs, normally generates 2 different tokens.

### Steps To Reproduce:
I cleared all cache, opened multiple tabs AT SAME TIME of https://laracasts.com/login and had two different tokens in the csrf field

![captura de tela 2016-12-21 17 31 13](https://cloud.githubusercontent.com/assets/1482604/21404563/f3c137ec-c7a8-11e6-8ad1-f25c55e222b8.png)

**Comment by GrahamCampbell** [comment]
This would be the expected behaviour I'm afraid.

**Comment by mgoebelm** [comment]
So why if I wait 2 seconds to open another tab it generates the same token? 

Why if tabs are opened at same time the token is different and if I open another tab one second after the token are equals?

**Comment by mgoebelm** [comment]
Isn't it per session token?  So how could I get two different tokens?

I didn't understand why this would be the expected behaviour. 

Or maybe I could'nt explain what is happening.

**Comment by crynobone** [comment]
> Isn't it per session token? So how could I get two different tokens?

Request A and Request B check for session token, and doesn't exist. Both decide to create a new token, both decide to store the token, while both succeed, only the latter request would be stored. 

Any subsequent request check for session token, and it now existed, it would used whichever session stored by either A or B.

**Comment by crynobone** [comment]
> This would be the expected behaviour I'm afraid.

I don't know if you have a good idea to solved this behaviour without causing any impact to the performance. So it is expected at the moment.

**Comment by mgoebelm** [comment]
Could laravel identify both generated tokens as valid?

**Comment by sisve** [comment]
I believe this to be the a relevant issue; Laravel does not (did not?) support two concurrent requests using the same session. https://github.com/laravel/framework/issues/14385
