### ISSUE TITLE
[BUG] PHP Version and Location  in /etc/nginx/sites-enabled/homestead.app

### ISSUE THREAD

**Issue by j-jmdk** [laravel/framework#16904]
- Laravel Version: 1.0.1
- PHP Version: 7.1
- Database Driver & Version:

### Description:
The currently released version created 16 days ago (as of this post) in the "virtualbox" provider contains a bug in the homstead.app file.
This bug shows when running "vagrant up", whereby it is told that php-7.1 is not found.
Fix is posted below.

### Steps To Reproduce:
In this file: /run/php/php7.1-fpm.sock
It is written:

`
...
 fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
...
`

Modify it to:

`...
 fastcgi_pass unix:/run/php/php7.1-fpm.sock;
...
`

 And then manually restart:
`sudo service nginx restart`
`sudo service php7.1-fpm reload`

However every time I provision the bug reappears.
Please release an update to fix this issue.

**Comment by caiquecastro** [comment]
I suppose it's a homestead related bug.

**Comment by svpernova09** [comment]
This can be closed, we confirmed it was an issue with the OP's version of Homestead.

**Comment by lucasmichot** [comment]
It's a misconfiguration issue.

The constraint for `laravel/homestead:~3` just indicates that your box version should be `>= 0.4`.
Now that the box `version >= 1.0.0` (with PHP 7.1) is available it will use it as the default version.

So if you want to go on using `laravel/homestead:~3` with PHP a box `>=0.4 & <1.0.0` (up to `0.6.1`with PHP 7.0), you have to update your `version` constraint in your `Homestead.yaml` file.

```yaml
ip: "192.168.10.10"
memory: 2048
cpus: 1
hostname: foobar
name: foobar
provider: virtualbox
version: "~> 0.4"
```

This should be documented somewhere. Ping @themsaid

**Comment by svpernova09** [comment]
@lucasmichot I'm writing a blog post right now that details how to use old versions of Homestead. probably not right for it to go into official docs since that would indicated "official support"
