### ISSUE TITLE
helpers.php on line 476 wrong php code not working on linux but working on windows

### ISSUE THREAD

**Issue by flik** [laravel/framework#16901]
- Laravel Version: 5.3
- PHP Version: 5.6
- Database Driver & Version: mysql 5.x

### Description:
I am surprising code is working on windows machine:
vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 476
if (! function_exists('event')) {
    /**
     * Fire an event and call the listeners.
     *
     * @param  string|object  $event
     * @param  mixed  $payload
     * @param  bool  $halt
     * @return array|null
     */
    function event(...$args)
    {
        return app('events')->fire(...$args);
    }
}

### Steps To Reproduce:
Just check your vendors folder and code: vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 476

but linux is returning error: 
 PHP Parse error:  syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in /home/xxxxxxx/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 476

**Comment by Skysplit** [comment]
Your PHP version on linux must be lower than 5.6 as this error refers to [Variadic functions](http://php.net/manual/en/functions.arguments.php#functions.variable-arg-list)

Check again your php version on linux.

**Comment by themsaid** [comment]
Check @Skysplit comment.

**Comment by flik** [comment]
Now, I have downgraded php version: PHP Version 5.5.9-1ubuntu4.20
and composer update is giving these errors:
Problem 1
    - This package requires php >=5.6.4 but your PHP version (5.5.9) does not satisfy that requirement.
  Problem 2
    - laravel/framework v5.3.9 requires php >=5.6.4 -> your PHP version (5.5.9) does not satisfy that requirement.
    - laravel/framework v5.3.8 requires php >=5.6.4 -> your PHP version (5.5.9) does not satisfy that requirement.

**Comment by crynobone** [comment]
Why would you downgrade your PHP when Laravel requires min `>=5.6.4`.

**Comment by flik** [comment]
check the above messages

**Comment by sisve** [comment]
@flik You were told the problem, not the solution. You must have a php version _above or equal to_ 5.6.4 for the code to work. You probably had a newer version of php-cli, and an older version of php-fpm/mod_php

**Comment by flik** [comment]
I have removed all php versions and reinstalled then Issue resolved. but I could not understand the wrong php syntex in laravel framework. Maybe it is with a strategy. 

function event(...$args) in helper file.

It must be: function event($args)
