### ISSUE TITLE
Laravel Exceptions have empty getMessage()

### ISSUE THREAD

**Issue by gillmaus** [laravel/framework#16902]
- Laravel Version: v5.3.26
- PHP Version: 7.0.10
- Database Driver & Version: mysql:5.7

Hi,
I am trying to implement an api implementation using laravel. For this I want all Exceptions to return their value as JSON to my frontend. The right place seemed to be function **render** in **Handler.php** in **App\Exceptions**. But Exceptions thrown by laravel/symfony never seem to provide the readable message. They seem to add the corresponding message later. This is basicly what I want to implement in Handler.php:
```
public function render($request, Exception $exception) {
    $error_response = [
        'error' => $exception->getMessage(),
        'error_code' => $exception->getStatusCode(),
    ];
    return response()->json($error_response, $exception->getStatusCode());
}
```
When I now route to a non-existant page, I have the following result:
```
HTTP/1.0 404 Not Found
Cache-Control: no-cache
Connection: close
Content-Length: 29
Content-Type: application/json
Date: Wed, 21 Dec 2016 12:25:23 GMT
Server: Apache/2.4.10 (Debian)
Vary: Authorization
X-Powered-By: PHP/7.0.10

{
    "error": "", 
    "error_code": 404
}
```
I want the "Not Found" - Response to be in JSON. The code is already right, but getMessage() always seem to be empty within builtin Exceptions.  If I raise my own Exception:
```
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
throw new NotFoundHttpException("Pageee not found");
```
I have the Message set correctly:
```
HTTP/1.0 404 Not Found
Cache-Control: no-cache
Connection: close
Content-Length: 45
Content-Type: application/json
Date: Wed, 21 Dec 2016 12:29:51 GMT
Server: Apache/2.4.10 (Debian)
Vary: Authorization
X-Powered-By: PHP/7.0.10

{
    "error": "Pageee not found", 
    "error_code": 404
}
```

It seems that the code is provided but the Response-text is set later. Is there a way to find out the HTTP Response Message in a "laravel way", so I can give it back in my JSON? I tried all dumping of the Excpetion.

**Comment by themsaid** [comment]
Please ask on the forums, we try to keep this repo for bug reporting only. Thanks for understanding :)
