### ISSUE TITLE
How is it possible to group a collection 2 by 2

### ISSUE THREAD

**Issue by minedun6** [laravel/framework#16915]
Is it possible to group a collection 2 by 2 and do some logic on it and reappend it back to the sale collection, here's an example to illustrate what I mean. Let's say you have 59 users, you want to group them by the user[0] and user[1] creating a new collection for them, resulting in a collection of 30 items within it another collection with only 2 items and a last collection with only 1 item.
What I did was kinda dump to be honest,
       ```$users = User::all();
       $bigCollection = collect();
       foreach ($users as $key => $user)
       {
           $bigCollection->push(collect($users->get($key), $users->get($key + 1)));
       }
       return $bigCollection;```

the problem is it just returns the same collection with the 59 items inside and no idea why.

**Comment by caiquecastro** [comment]
You should ask on the forums!

**Comment by minedun6** [comment]
it takes some to do, I need this to be able to move on a project that needs to be done for saturday but you are right if this isn't the right place for it, sorry.

**Comment by mike-grinspan** [comment]
This probably isn't the use-case for a foreach-loop. Use a for-loop and skip every other iteration.

**Comment by sisve** [comment]
What you're asking for isn't grouping, it's chunking. https://laravel.com/api/5.3/Illuminate/Support/Collection.html#method_chunk
