### ISSUE TITLE
Redis Store has no unserializer.

### ISSUE THREAD

**Issue by chrishalbert** [laravel/framework#16927]
- Laravel Version: 5.2.x
- PHP Version: 7
- Database Driver & Version: Redis Version: 2.8.24 on OS: Amazon Elasticache

**Comment by GrahamCampbell** [comment]
Thank you for the report. Please send a PR to the 5.1 branch of this very repo, and then we'll merge it up into 5.3 and master automatically. Please close any other issues/PRs you have on any of the read-only illuminate subscripts.
