### ISSUE TITLE
Wrong dependency definition

### ISSUE THREAD

**Issue by okneloper** [laravel/framework#16933]
- Laravel Version: 5.3.23
- PHP Version: 5.6

### Description:
The \Illuminate\Validation\Validator class has a property translator of type \Symfony\Component\Translation\TranslatorInterface
    /**
     * The Translator implementation.
     *
     * @var \Symfony\Component\Translation\TranslatorInterface
     */
    protected $translator;

In the same class
illuminate/validation/Validator.php:2228
it calls a `get()` method on the translator

    $this->translator->get('validation.attributes')

But there is no `get()` method on the \Symfony\Component\Translation\TranslatorInterface

### Steps To Reproduce:
Kind of tricky to replicate, but essentially somthign like this (when using standalone Validation component)

        $app->singleton('translator', function ($app) {
            return new \Symfony\Component\Translation\IdentityTranslator();
        });

        // register validation components
        (new \Illuminate\Validation\ValidationServiceProvider($app))->register();

        \Illuminate\Support\Facades\Validator::make(['name' => ''], ['name' => 'required'])->passes();

Result: 

> Fatal error: Call to undefined method Symfony\Component\Translation\IdentityTranslator::get() in D:\dev\involveme.co.uk\packages-validation\vendor\illuminate\validation\Validator.php on line 2228

**Comment by themsaid** [comment]
This was already fixed, it'll be available in the next release.
