### ISSUE TITLE
Queue workers don't stop gracefully on SIGTERM

### ISSUE THREAD

**Issue by omanizer** [laravel/framework#16935]
- Laravel Version: 5.3.25
- PHP Version: 7.0
- Database Driver & Version: jenssegers/laravel-mongodb 3.1.3

### Description:
I frequently use "autoscaling" features of AWS to start/stop worker instances when I need to deliver large numbers of transactional messages in a small timeframe.  In the interest of speed I often group up to 10 messages into a single job that I push onto the queue which can take 10-20 seconds to complete.  Being that a lot of these can be emails, some of which take more than 64k, I use a database to store the payload and use Beanstalk to manage what jobs are executed.

I've observed occasional messages left over in the database whose times correspond with autoscaling events.

To address this issue in the past I utilized the `pcntl_signal(SIGTERM, ....)` method with an empty function to prevent the process from being immediately killed on a SIGTERM.  This worked well with queue:listen since queue:listen would be restarted entirely after each processed event, merely catching the SIGTERM signal in an empty function would cause the script to wait until it's completion before stopping, and Supervisor is designed to not restart a process after receiving a sigterm. 

After switching to daemon mode (of which I am quite fond of the increased speed) it's now not working so well.  There should be some good way of automatically performing a queue:restart when a SIGTERM is received.  Is something like this worth my time pursuing or is there another effective way that my hours of searching on this did not find?

I could just extend the worker class for my own purposes but I think this is an important enough issue that is probably affecting many more people than just myself.

I'm happy to take the ball and run with this if it hasn't already been done or there's not a better way.

### Steps To Reproduce:
1) Start up a queue worker from the command line (php artisan queue:work)
2) Ensure the jobs passed to the queue worker are long-running.  The `sleep` function is vulnerable to termination so perhaps using some code like this:
```
for ($q = 0; $q < 5; $q++) {
    for ($i = 0; $i < 300000000; $i++) {
    }
    print $q . "\n";
}
```
3) Get the process id of the worker command you started in (1)
4) Run `kill -15 YOURPID`
5) Observe that the process is killed immediately.  The above script should count from 0 to 4 before terminating.

### Noteworthy code
Here's a demonstration of making the above code not exit after a SIGTERM.  I'd like to implement something like this inside of a queue worker.
```
<?php
declare(ticks=1);
$GLOBALS['___queue_terminated'] = false;
var_dump(pcntl_signal(SIGTERM, function () {
    echo "Tried to terminate\n";
    $GLOBALS['___queue_terminated'] = true;
}));
print "Running\n";
while (1) {
    for ($q = 0; $q < 5; $q++) {
        for ($i = 0; $i < 300000000; $i++) {
        }
        print $q . "\n";
    }
    if ($GLOBALS['___queue_terminated']) {
        break;
    }
}
```

Rock on!

**Comment by taylorotwell** [comment]
Yeah we just need to handle that signal in the Worker class. I had planned to implement better signal handling soon anyways to make room for some queue improvements I'm planning for Laravel 5.5. I would welcome a PR to handle this signal properly.

**Comment by taylorotwell** [comment]
Note I already have pcntl_async_signals setup in the Worker class on 5.4 so adding support is fairly straight-forward.

**Comment by omanizer** [comment]
Great, I will get started on this in the next little while.

**Comment by jaylinski** [comment]
I'm curious if your issue also occurs in version <= 5.3.9.

This version is using `pcntl_fork()`.

See related issue #16694.

**Comment by themsaid** [comment]
Fixed in https://github.com/laravel/framework/commit/819888ca1776581225d57e00fdc4ba709cbcc5d0
