### ISSUE TITLE
[5.3] MessageBag `has()` `first()` and wildcards

### ISSUE THREAD

**Issue by tillkruss** [laravel/framework#16941]
It doesn't look like `MessageBag::has()` and `MessageBag::first()` support wildcards at all. Is there a best practise for that, or worth a PR? Ping @themsaid.

**Comment by themsaid** [comment]
hmmm, it should work. they both call `MessageBag::get()` which has support for wildcards.

Please include a case where it fails to work.

**Comment by themsaid** [comment]
Gotcha, PR here: https://github.com/laravel/framework/pull/16993

**Comment by tillkruss** [comment]
You're the best! ❤️
