### ISSUE TITLE
Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable.

### ISSUE THREAD

**Issue by wout** [laravel/framework#16947]
- Eloquent Version: **5.3.23**
- PHP Version: **5.6.28**
- Database Driver & Version: MySQL **5.7.16**

### Description:
`Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable.`

```
/var/web/vd4377/uilabs/shared/vendor/illuminate/container/Container.php:644 
Illuminate\Container\Container -> make 
/var/web/vd4377/uilabs/shared/vendor/illuminate/database/Connectors/ConnectionFactory.php:130 
call_user_func 
/var/web/vd4377/uilabs/shared/vendor/illuminate/database/Connection.php:964 
Illuminate\Database\Connection -> getPdo 
/var/web/vd4377/uilabs/shared/vendor/illuminate/database/Connection.php:832 
Illuminate\Database\Connection -> reconnectIfMissingConnection 
/var/web/vd4377/uilabs/shared/vendor/illuminate/database/Connection.php:717 
Illuminate\Database\Connection -> run 
/var/web/vd4377/uilabs/shared/vendor/illuminate/database/Connection.php:350 
Illuminate\Database\Connection -> select 
/var/web/vd4377/uilabs/shared/vendor/illuminate/database/Query/Builder.php:1648 
Illuminate\Database\Query\Builder -> runSelect 
/var/web/vd4377/uilabs/shared/vendor/illuminate/database/Query/Builder.php:1634 
Illuminate\Database\Query\Builder -> get 
/var/web/vd4377/uilabs/shared/vendor/illuminate/database/Eloquent/Builder.php:632 
Illuminate\Database\Eloquent\Builder -> getModels 
/var/web/vd4377/uilabs/shared/vendor/illuminate/database/Eloquent/Builder.php:327 
Illuminate\Database\Eloquent\Builder -> get 
/var/web/vd4377/uilabs/shared/vendor/illuminate/database/Eloquent/Builder.php:297 
Illuminate\Database\Eloquent\Builder -> first 
...
```

I'm using Eloquent in combination with Slim Framework to build a small API. For some reason I am getting this error and I can't locate the problem. Database settings are correct. This error is thrown in my staging environment on the server. Locally, with MySQL 5.6.29, it works perfectly. Although I don't think it's related to MySQL 5.7 because I have another app running on the same server with the same version of Eloquent.

Can anyone point me in the right direction?

### Steps To Reproduce:
If only I'd know.

**Comment by sisve** [comment]
You do not have a ExceptionHandler registered in your $app. 

https://github.com/laravel/laravel/blob/master/bootstrap/app.php#L39-L42

**Comment by wout** [comment]
I'm using Laravel, just Eloquent in combination with Slim Framework. But since this might indeed be the issue, how can I register the custom error handler when not using Laravel?

**Comment by GrahamCampbell** [comment]
Please ask on the forums.
