### ISSUE TITLE
Base64 Image array request issue

### ISSUE THREAD

**Issue by RendyTan** [laravel/framework#16959]
- Laravel Version: 5.2
- PHP Version: 5.6.19
- Database Driver & Version: 10.1.10-MariaD

### Description:
Uploading base64 image array result in the array combining into just one entry. So from array containing multiple entry of base64 string, it became just an array with single entry of all base64 string combined.

### Steps To Reproduce:
implement a file upload page by using HTML5 file api to convert the upload image to base64 strings.
var files = [];
var id = 0;
var handleFile = function(event) {
      $.each(event.target.files, function(index, file) {
        var reader = new FileReader();
        reader.onload = function(event) {
          files[id++] = event.target.result;
        };
        reader.readAsDataURL(file);
      });
    }
You can use this script to convert the image to base64 strings. Attach the handleFile function to image upload button.

After that just try and return the array from your controller, it will show an array with single entry combining all of the array entry.

**Comment by Edgpaez** [comment]
Please try and use the code format so it's easier to read the issue :)

I don't think JS is sending the request you think it is. Try using Chrome Dev Tools to see how it's formatted. 

If the base64 data is reaching Laravel perhaps you are not properly formatting the request. I think the easy thing would be to `stringify` the files array and sending the request with a `Content-Type: application/json` header so Laravel knows what it's getting
