### ISSUE TITLE
Queueing mails makes them lose their order

### ISSUE THREAD

**Issue by Jossnaz** [laravel/framework#16953]
- Laravel Version: 5.3
- PHP Version: 7
- Database Driver & Version:

from here: http://stackoverflow.com/questions/41302476/laravel-changing-sorting-of-collection-when-sending-mail-between-constructor-an/

### Description:
this is laravel 5.3

when I preview the email using this:

        $wantsheet_products = WantsheetProduct::orderByRaw(EmailService::WANTSHEET_PRODUCT_ORDER_SQL)->get();
        View::make('email.wantsheet.email_wantsheet_to_supplier', ['wantsheet_products' => $wantsheet_products]);

the sorting is correct. that is, sorting is ['a','b','c'] the way i want it.

**EDIT** see note at the bottom

now when actually sending out the mails (i queue them), the sorting changed and is unsorted again, magic?! the change happens between the constructor and the build function

    class WantsheetToSuppliersMail extends Mailable
    {
    
      public $wantsheet_products;
      public $to_email;
      /** @var  WantsheetContact  $wantsheetcontact*/
      public $wantsheetcontact;
      use Queueable, SerializesModels;
    
        /**
         * Create a new message instance.
         *
         * @return void
         */
        public function __construct($wantsheet_products)
        {
    //$wantsheet_products is a standard eloquent model collection, e.g. i get it like this:  WantsheetProduct::orderByRaw(self::WANTSHEET_PRODUCT_ORDER_SQL)->get()
          $this->wantsheet_products = $wantsheet_products; //is ['a','b','c']
        }
    
    
        /**
         * Build the message.
         *
         * @return $this
         */
        public function build()
        {
    
    //      $this->wantsheet_products is ['b','a','c'];
          $subject = 'abc';
            return $this->from('me@myapp.com')->view('email.wantsheet.email_wantsheet_to_supplier', [])->subject($subject);
        }
    }

**EDIT contd.**
Now when i do

`WantsheetProduct::orderByRaw(EmailService::WANTSHEET_PRODUCT_ORDER_SQL)->get()->toArray();`

it doesn't break the sorting any longer (so it works). But that is stupid, isn't it?

**Comment by GrahamCampbell** [comment]
Fixed in 5.4.
