### ISSUE TITLE
Illuminate Container share() method is not defined in Contract Container

### ISSUE THREAD

**Issue by Cyrille37** [laravel/framework#16969]
- Laravel Version: 5.*.*
- PHP Version: n/a
- Database Driver & Version: n/a

### Description:

The Container implementation [`Illuminate\Container\Container`](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Container/Container.php) define the `share()` method that is not defined in the Container interface [`Illuminate\Contracts\Container\Container`](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Contracts/Container/Container.php), nor explained in [Service Container](https://laravel.com/docs/5.3/container) documentation.

But this method is called in several classes like in [`Illuminate\Routing\RoutingServiceProvider`](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Routing/RoutingServiceProvider.php#L38) and [`Illuminate\Mail\MailServiceProvider`](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Mail/MailServiceProvider.php#L92).

Is it an oblivion or is there a reason ?
Cheers, Cyrille.

**Comment by crynobone** [comment]
It is removed for the next 5.4 release.

**Comment by MuriithiCharles** [comment]
so how can this be solved @crynobone ?

**Comment by a-komarev** [comment]
@MuriithiCharles @Cyrille37 You can use `singleton` method instead.
