### ISSUE TITLE
Elixir helper appears to not work for Laravel installations in a subdirectory of webroot

### ISSUE THREAD

**Issue by arborrow** [laravel/framework#16966]
- Laravel Version: v5.2.45
- PHP Version: PHP 7.0.8
- Database Driver & Version: MySQL  5.7.16

### Description:

I was following the documentation for using the elixir helper at: 
https://laravel.com/docs/5.2/elixir#versioning-and-cache-busting 
which suggests using {{ elixir('css/all.css') }} in the blade; however, when I did so the style sheet was not loading. On my development machine (Ubuntu 16.10), I have Apache configured to use /var/www as the web root and Laravel installed as a subdirectory - in this case polanco. In my app.php file I declare: 
    'url' => 'http://localhost/polanco/public',
In looking at the code, the elixir helper seems to assume that Laravel is installed at webroot. As a result it tries to find the versioned css file at http://localhost/build/css/all-{hash}.css rather than where it is located, namely, http://localhost/polanco/public/build/css/all-{hash}.css. 
I am somewhat new to Laravel and realize I may well be overlooking some obvious setting  

### Steps To Reproduce:
1) Install laravel in a subdirectory of wwwroot
2) set app url in config/app.php to the subdirectory
3) install elixir with version
4) attempt to use the elixir helper in a blade
5) observe that the all.css file is not found

### Proposed improvement and rationale
My proposed fix is to replace:
    return '/'.trim($buildDirectory.'/'.$manifest[$file], '/');
with:
    return config('app.url').'/'.(trim($buildDirectory.'/'.$manifest[$file], '/'));
This make explicit the web path rather than assuming laravel is installed at webroot. 

Looking at the latest version of the elixir function in Laravel 5.3  there is a new check introduced in:
https://github.com/laravel/framework/commit/d7303d997729a28dd3e19ffab9b88999692006b9 
to allow for an unversioned file to be used that has a similar return that assumes wwwroot so I would propose prepending both of those lines with config('app.url') so that the elixir helper will work on web installs when they are installed in a subdirectory of web root. 

If you would like a proper patch file kindly let me know and I'll submit a pull request or add a diff file. If there is some other way in which I should be handling this to avoid the issue then kindly let me know and this issue can be resolved as not a bug (and just a sign that I am new to some of the intricacies of Laravel)

Peace - Anthony

**Comment by GrahamCampbell** [comment]
Thank you, but this is the expected behaviour. Please see the other issues. :)

I'd quite like to change this behaviour to the other one you suggested though, in 5.4, since it's more intuitive.

**Comment by arborrow** [comment]
Graham,

Many thanks for the speedy reply. Sorry I was not familiar with the other issues but searching closed issue I did find a reasonable workaround {{ asset(elixir('css/all.css')) }} so I can see where it would not necessarily be a priority but as you say it would be more intuitive. If there were an open issue for it as feature request it would certainly have my +1 but I do not see it as all that important as it likely impacts a small set of users in a particular situation with a pretty easy workaround. Since it continues to come up, might it be helpful to update the docs to mention that in some environments passing the elixir function through the asset function resolves the issue? 

For those interested in some of the history:

https://github.com/laravel/framework/issues/8565
https://github.com/laravel/framework/issues/13490
https://github.com/laravel/framework/issues/16862

Peace -Anthony
