### ISSUE TITLE
Use pcntl_exec() instead of passthru() for artisan's serve command

### ISSUE THREAD

**Issue by squarefractal** [laravel/framework#16979]
`artisan`'s serve command currently uses `passthru()` for running PHP's built-in web server. However, this kills the ability of have color output on the terminal, and most importantly, it also prevents PsySH from properly working when an `eval(\Psy\sh())` is put into the code.

This can be prevented by using `pcntl_exec()` instead of `passthru()`.

**Comment by GrahamCampbell** [comment]
Please send a PR to 5.4. :)
