### ISSUE TITLE
Eloquent / Support Collection only() inconsistency

### ISSUE THREAD

**Issue by aambrozkiewicz** [laravel/framework#16976]
- Laravel Version: v5.3.28
- PHP Version: 7.1
- Database Driver & Version:

### Description:
I'm trying to retrieve grouped models from related field, using collection returned by eloquent.
I have a one to many relation between `Role` and `Field`, to get them I use:
`Role::find(1)->fields->keyBy('name')->only('phone')`
which returns empty collection. On the other hand, this:
`collect(Role::find(1)->fields)->keyBy('name')->only('phone')`
returns what I expected. Is that on purpose? I suppose `getDictionary` should be somehow aware of key change?

**Comment by GrahamCampbell** [comment]
> returns what I expected

What did you expect? "collect" will give a collection from the support component, vs a db collection. The db collection extends the support collection.

**Comment by aambrozkiewicz** [comment]
I expect to get all of the Eloquent models that name property is equal to `phone`, just like with the collect(). For eloquent is doesn't work.

**Comment by themsaid** [comment]
@aambrozkiewicz Please feel free to present the change you suggest by opening a PR, closing this since it's not an issue in the framework.

Notice also that you need to submit your suggestion to the 5.4 branch since this a breaking change.
