### ISSUE TITLE
Problem with Available Size validation rule

### ISSUE THREAD

**Issue by utechs** [laravel/framework#16971]
- Laravel Version: 5.3.#
- PHP Version:5.6.24
- Database Driver & Version: MariaDB 10.1.16

### Description:
Hello

I got a problem with "size:value" when I try to validate my input but it always threw error about length of input even if the input length size value.

### Steps To Reproduce:
I validate my request input with validate method but the size:value always throw an error that the size must be :value
```
$this->validate($request,[
            'Phone' => 'required|numeric|size:16',
]);
```

**Comment by sisve** [comment]
The `numeric` validation rule tells validateSize that the number is numeric, and docs then "clarify" that, with my emphasis, ...

> The field under validation must have a size matching the given value. For string data, value corresponds to the number of characters. **For numeric data, value corresponds to a given integer value.** For an array, size corresponds to the count of the array. For files, size corresponds to the file size in kilobytes.

This basically means that you're require the phone-number to be 16, if I read the source correctly.

validateSize: https://github.com/laravel/framework/blob/359b7c3b2e5648ef2ad289a464a384785e991e20/src/Illuminate/Validation/Validator.php#L1205-L1210
docs: https://laravel.com/docs/5.3/validation#rule-size

**Comment by themsaid** [comment]
Please check on the forums since this is not actually a bug in the core.
