### ISSUE TITLE
Mutator field_{int}

### ISSUE THREAD

**Issue by egorsgor** [laravel/framework#16972]
- Laravel Version:  5.3.28
- PHP Version: 7.0.9
- Database Driver & Version: 5.7.16

### Description:

Mutators not working for fields with int in name

### Steps To Reproduce:

```
Schema::create('tests', function (Blueprint $table) {
    $table->increments('id');
    $table->string('field_100');
    $table->string('field_200');
    $table->timestamps();
});

class Test extends Model
{
    public function getField100Attribute($value) {
        return 'qweqwewq';
    }
    public function getField200Attribute($value) {
        return 'qweqweqweqweqw';
    }
}
```

\App\Test::get() output

[
{
"id": 1,
"field_100": "123",
"field_200": "123",
"created_at": null,
"updated_at": null
}
]

**Comment by themsaid** [comment]
There's no way we can guess if the mutator is for `field100` or `field_100`, the current implementation assumes it's `field100` and that's why it won't work in your case.

I believe this will continue to be a limitation.

**Comment by themsaid** [comment]
@egorsgor closing since there are no plans to change this behaviour.
