### ISSUE TITLE
Laravel Error at localhost/laravel/public

### ISSUE THREAD

**Issue by vyomsrivastava** [laravel/framework#16975]
- Laravel Version: 5.3.28
- PHP Version:7.0.10
- Database Driver & Version:5.7.14

### Description:
I am new to Laravel and Composer. I don't understand why I'm getting this error.
![untitled](https://cloud.githubusercontent.com/assets/18082634/21472440/0953d966-cb00-11e6-97ef-88f71e931210.png)

**Comment by GrahamCampbell** [comment]
Because you're not using one of the supported ciphers?

**Comment by GrahamCampbell** [comment]
Please feel free to ask for help on the forums.

**Comment by vyomsrivastava** [comment]
Thanks
