### ISSUE TITLE
Calling Eloquent's create() method on a Postgres INET field throws a SQL "Not null violation" exception

### ISSUE THREAD

**Issue by nicklaw5** [laravel/framework#16977]
- Laravel Version: 5.3.28
- PHP Version: 7.0.5
- Database Driver & Version: PostgresSQL v9.3.11

### Description:
When using Eloquent's `create()` method on a PostgresSQL INET field, it would seem that the IP address that is passed as a string is not converted to a valid INET datatype, and instead is passed into the query as `null`. This causes the below SQL exception to be thrown when running the query.

```txt
SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "ip_address" violates not-null constraint
DETAIL:  Failing row contains (1, null, 2016-12-25 21:26:50, 2016-12-25 21:26:50). (SQL: insert into "users" ("updated_at", "created_at") values (2016-12-25 21:26:50, 2016-12-25 21:26:50) returning "id")
```

### Steps To Reproduce:
1. Set `pgsql` as default database driver (make sure you have Postgres configured correctly)
2. Create a migration that uses the `ipAddress()` method:
```php
Schema::create('users', function (Blueprint $table) {
    $table->increments('id');
    $table->ipAddress('ip_address');
    $table->timestamps();
});
```
3. Run the migration `php artisan migrate`

4. Attempt to insert a new table row using Eloquent's `create()` method
```php
\App\User::create([
    'ip_address' => $request->ip(),
]);
```
Running this query generates the before stated SQL exception.

### Other Information:
Running a `dd($request->ip());` shows that the IP address passed through the request is not NULL.

Furthermore, the query resolves fine if not using the `Model::create()` method. For example:
```php
$user = new \App\User;
$user->ip_address = $request->ip();
$user->save();
```

**Comment by themsaid** [comment]
`create()` calls `setAttribute()` which is same as doing `$user->ip_address`, under the hood it also calls `setAttribute()` inside `__set()`.

So if it works sometimes and others not I assume it's not an issue with the DB driver but rather `$request->ip()` actually returns null sometimes.

Please double check.

**Comment by nicklaw5** [comment]
@themsaid 

I've just committed a fresh install of Laravel v5.3.28. I've added `TestController.php` with a method called `test`, which provides the minimal code to replicate the issue presented above. See [here](https://github.com/nicklaw5/laravel-issue-16977/blob/master/app/Http/Controllers/TestController.php).

I'm using Homestead and have included my [`.env`](https://github.com/nicklaw5/laravel-issue-16977/blob/master/.env) file to show my database configurations.

**Comment by themsaid** [comment]
Instead of `$request->ip()` can you just pass a string?

**Comment by themsaid** [comment]
Oops, the attribute is not fillable: https://github.com/nicklaw5/laravel-issue-16977/blob/master/app/User.php#L17

**Comment by nicklaw5** [comment]
Ahhh :disappointed: 

I haven't used Laravel in a while. That one slipped my mind.

Thanks for your help.
