### ISSUE TITLE
Validating arrays with distinct rule involves attributes in nested arrays

### ISSUE THREAD

**Issue by denho** [laravel/framework#16987]
- Laravel Version: 5.3.22
- PHP Version: 7.0.10

### Description:
In docs for distinct validation rule it is written: "When working with arrays, the field under validation must not have any duplicate values.". But it checks not only the exactly the matching field, but all nested fields with the same attribute name. E.g. `'foo.*.id' => 'distinct'` will check not only foo.0.id, foo.1.id,.. but also foo.0.nested.id.
The reason is that [`Str::is($attributeName, $key)`](https://github.com/laravel/framework/blob/359b7c3b2e5648ef2ad289a464a384785e991e20/src/Illuminate/Validation/Validator.php#L1342) matches not only foo.0.id or foo.1.id, but also foo.0.whatever.id

### Steps To Reproduce:
```
$array = [
 'foo' => [
    ['id' => 1, 'nested' => ['id' => 2]],
    ['id' => 2],
  ]
];

$validator = Validator::make($array, [
  'foo.*.id' => 'distinct'
]);

if($validator->fails())
 dd($validator->errors());
```

will fail and return "The foo.1.id field has a duplicate value."

**Comment by themsaid** [comment]
Thank you, submitted a fix in this PR: https://github.com/laravel/framework/pull/17102
