### ISSUE TITLE
microsoft sqlsrv driver

### ISSUE THREAD

**Issue by hamidparchami** [laravel/framework#16985]
- Laravel Version: 5.2.3
- PHP Version: 7.0
- Database Driver & Version:

### Description:
Microsoft has released official driver for php developers and linux distributions.
Current version of database connector replaces "sqlsrv" wtih "dblib" and does not have "sqlsrv" connection string so we can not use "sqlsrv" as database driver. Please change this behavior in next version of the framework.
Thanks

**Comment by GrahamCampbell** [comment]
5.2 is not supported I'm afraid. Feel free to send a PR to 5.4. :)
