### ISSUE TITLE
[5.3] Absolute path to sqlite file in .env only working with artisan CLI

### ISSUE THREAD

**Issue by juukie** [laravel/framework#16996]
- Laravel Version: 5.3.28
- PHP Version: 7.0.6
- Database Driver & Version: SQLite
- Laravel Valet

### Description:
According to the SQLite Configuration referenced in the [Laravel documentation](https://laravel.com/docs/5.3/database#configuration), an absolute path should be used in your `.env` file.
All is fine when using artisan commands, however when I access the website via the browser, I have to change the path to `../database/database.sqlite` to make it work.

### Steps To Reproduce:
- Install fresh Laravel installation
- Create the /database/database.sqlite file
- Update .env; set `DB_DATABASE=/database/database.sqlite`
- Add route:
```
Route::get('/', function () {
    return App\User::first();
});
```
- Visit the url in the browser, you'll see this error:
`Database (/database/database.sqlite) does not exist. (SQL: select * from "users" limit 1)`

### Solution
One way to solve this problem is by changing the `DB_DATABASE=` to `#DB_DATABASE=` but that would make it impossible to use a different named file.

I think there is a better solution to deal with this by changing the [SQLite Connector](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Connectors/SQLiteConnector.php#L28). I'm willing to create a PR for this but I'm not sure how to solve this the best way.

**Comment by themsaid** [comment]
This is not the absolute path: `DB_DATABASE=/database/database.sqlite`

An absolute path is something like `/Users/Mohamed/sites/laravel/database/database.sqlite`.

**Comment by juukie** [comment]
@themsaid How could I miss that. A full path works indeed, thanks!
