### ISSUE TITLE
mergeConfigFrom does not respect multi-dimensional config arrays

### ISSUE THREAD

**Issue by lioannou** [laravel/framework#16991]
- Laravel Version: 5.3
- PHP Version: 7.1

### Description:
Whilst I was developing a package, I added a new config variable to my package config.

I didnt think it would be an issue - since I was using `mergeConfigFrom()` in package Service Provider, and from the documents I assumed all missing config from the published package config file would be cascaded from the packaged config - so it would be included.

Whilst that is true for first level config variables - it is not true when a mutli-dimensional config variable is missing.

### Steps To Reproduce:
In your `app/config/package.php`

```
<?php

return [
    'example1' => true,
    'other' => [
         'config1' => true,
         'config2' => true,
    ]
];
```

Then in your vendor package config file `package.php`

```
<?php

return [
    'example1' => false,
    'example2' => false,
    'other' => [
         'config1' => false,
         'config2' => false,
         'config3' => false,
    ]
];
```

In your app service provider you run

```
$this->mergeConfigFrom(__DIR__.'/config/package.php', 'package');
dd(config('package'));
```

This is the output you get:

```
array:3 [▼
  "example1" => true
  "example2" => false
  "other" => array:2 [▼
    "config1" => true
    "config2" => true
  ]
]
```

You can see that `example2` was merged in - but `config3` is missing.

As mentioned - the way this can easily occur is during a package upgrade. If you add a new option to a multidimensional config array in a "new" version of your package - then you must have users re-publish the config (or manually add the config). I would have thought `mergeConfigFrom()` would protect from this - but it does not.

It might be considered a bug? But at the minimum it is an undocumented limitation of the package config framework. I propose either we look to see if this issue can be fixed, if not, then I'm happy to do a PR to the docs to highlight the limitation.

**Comment by GrahamCampbell** [comment]
This is not a bug, but is the expected behaviour, to allow packages to have examples like cache connections, but to allow users to totally override these.

**Comment by djkarimi** [comment]
You can see , and edit change source :
vendor\laravel\framework\src\Illuminate\Config\Repository.php

```
 public function set($key, $value = null)
    {
        $keys = is_array($key) ? $key : [$key => $value];

        foreach ($keys as $key => $value) {
            Arr::set($this->items, $key, $value);
        }
    }
```

Call collection mian :

vendor\laravel\framework\src\Illuminate\Support\Arr.php
