### ISSUE TITLE
Date time validator:  equal to or after

### ISSUE THREAD

**Issue by pzheng64** [laravel/framework#16995]
- Laravel Version: 5.3
- PHP Version: 7.0
- Database Driver & Version:
MySQL 5.5

### Description:
http://stackoverflow.com/questions/41342818/laravel-5-3-date-validator-equal-to-or-after-start-date

### Steps To Reproduce:
$validator = Validator::make($data, [
    'start_date'    => 'required|date',
    'end_date'      => 'required|date|after:start_date',
]);

**Comment by GrahamCampbell** [comment]
Please keep questions on the forums.
