### ISSUE TITLE
Error page showing only the whoops thing even if the debugger is on

### ISSUE THREAD

**Issue by siempay** [laravel/framework#17026]
- Laravel Version: 5.2
- PHP Version:5.6.25
- Database Driver & Version: mysql 5.7.14

### Description:
the error shows up randomly and sometimes on ajax requests returning 500, when i use the dev tools of chrome to see the error, it gives me only the whoops but after I used `tail -f storage/logs/laravel.log`
I got this
`[2016-12-28 14:54:04] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in D:\shop\tess\vendor\laravel\framework\src\Illuminate\Encryption\EncryptionServiceProvider.php:45
Stack trace:
#0 D:\shop\tess\vendor\laravel\framework\src\Illuminate\Encryption\EncryptionServiceProvider.php(25): Illuminate\Encryption\EncryptionServiceProvider->getEncrypterForKeyAndCipher(NULL, 'AES-256-CBC')
#1 D:\shop\tess\vendor\laravel\framework\src\Illuminate\Container\Container.php(731): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)`

### Steps To Reproduce:
Why am I seeing this errors ? and how to escape from it for ever

**Comment by GrahamCampbell** [comment]
Please set an encryption key.

**Comment by siempay** [comment]
the app is working fine and I did key:generate once; but still seeing that error from time to time

**Comment by sisve** [comment]
@siempay I would guess that you have no run "php artisan config:cache". That's required in some scenarios; the default Apache configuration on Windows is one of those scenarios.

**Comment by siempay** [comment]
@sisve thanks man! Do I have to run it from time to time ? Can you explain me more what are these scenarios please

**Comment by sisve** [comment]
@siempay Always do it during deploys. Always do it when you have one process executing several php requests. (Apache on Windows does this per default.)

This is one of those public secrets; it's known but not clearly documented.

https://github.com/vlucas/phpdotenv/issues/76#issuecomment-224899197
