### ISSUE TITLE
Laravel 5.3 Route Names append prefix on forge based ubuntu server

### ISSUE THREAD

**Issue by fakharkhan** [laravel/framework#17021]
- Laravel Version: Laravel 5.3 
- PHP Version: PHP 7

I am using Laravel 5.3 and i have written following code for routes, and the routes names are created on forge based server with prefix appended in route names, which breaks my whole application, please find the details below:

**Source code for routes:**
`
Route::group(['prefix' => 'admin'], function () {
     Route::resource('users', 'UsersController');
});

Route::group(['prefix' => 'agent','as'=>'agent.'], function () {
     Route::resource('users', 'UsersController');
});

Route::group(['prefix' => 'staff','as'=>'staff.'], function () {
     Route::resource('users', 'UsersController');
});

`
**My Development Machine Details:**
OS : macOS Sierra
PHP: PHP 7.0.6 
Laravel: Laravel Framework version 5.3.28

_Out Put of Routes:_
php artisan route:list | grep users.create

| admin/users/create   | users.create  
| agent/users/create   | agent.users.create 
| staff/users/create   | staff.users.create 

**Forge Maintained Digital Ocean Machine Details:**
OS : Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-57-generic x86_64)
PHP: PHP 7.1.0-5+deb.sury.org~xenial+1 (cli) ( NTS )
Laravel: Laravel Framework version 5.3.28

_Out Put of Routes:_
php artisan route:list | grep users.create

| admin/users/create   | admin.users.create   
| agent/users/create   | agent.agent.users.create
| staff/users/create   | staff.staff.users.create

**Comment by fakharkhan** [comment]
After lot of digging i found that when i add a custom validator in my AppServiceProvider, it produces the problem i posted in my last comment:
`
namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\Validator;
class AppServiceProvider extends ServiceProvider
{
    public function boot()
    {
        Validator::extend('foo', function ($attribute, $value, $parameters, $validator) {
            return $value == 'foo';
        });
    }

`
So i just removed this from code and it is now working, but i am still not sure how to dd my custom validators in Laravel 5.3

**Comment by themsaid** [comment]
Cannot replicate on latest 5.3:

```
| admin/users/create      | users.create
| agent/users/create      | agent.users.create
| staff/users/create      | staff.users.create
```

Extending the validator is not related, also I wonder why you're using the same resource controller with different names?

**Comment by fakharkhan** [comment]
@themsaid, You need to have php 7.0 or higher with laravel 5.3 and then you can put the Validator::extend in app service to reproduce the error, i tried it on 3 machines and same results.
For the multiple resources usage we need this for app requirement.

**Comment by Whyounes** [comment]
@themsaid I have the same problem. A resource inside a group doesn't add the prefix attribute.
@fakharkhan I don't think this has something to do with the validator extension.

**Comment by Whyounes** [comment]
Can we re-open this until it's confirmed?
