### ISSUE TITLE
Model returns empty primary key, if is called inside of collection.

### ISSUE THREAD

**Issue by ddctd143** [laravel/framework#17039]
- Laravel Version: 5.3.28
- PHP Version: 7.0.14
- Database Driver & Version: mysql, 5.7

### Description:

I have model called "Advert" that has relationship "views", that are stored in polymorph relationship.

If I get single instance of Advert model, then inside of that model I can receive model's ID and successfully count views. If that model is inside collection, then model's method $this->getKey() returns always null. Better explanation is in example.

### Steps To Reproduce:

If I try to fetch single model, then I can successfully retrieve views count, because inside model, method $this->getKey() will return ID of a model

**_Successful scenario:_**

```php
$advert = Advert::with('views')->find(1);

dd($advert->views->count()) // Returns "4"
```

**_Failing scenario:_**

```php
$adverts = Advert::with('views')->get();

foreach($adverts as $advert) {
    dd($advert->views->count()) // Will always return "0" because in collection, model's internal method $this->getKey() will always return null.
}
```

Model class:

```php
<?php namespace App\Models\Advert;

class Advert extends Model
{
    public function views()
    {
        return $this->morphMany(\App\Models\User\Activity::class, 'subject')
            ->where('event', 'request')
            ->where('subject_type', 'App\Models\Advert\Advert')
            ->where('subject_id', $this->getKey()); // $this->id   <- This is failing if called in collection, because always will be null.
    }
}
```

**Comment by themsaid** [comment]
To simplify the check I did this:

```
foreach (App\User::all() as $user) {
    dd($user->getKey());
}
```

But it does seem to return the key successfully, can you check this exact case without using `with` and see if the model returns a value?

**Comment by ddctd143** [comment]
@themsaid, try to dump not a $user->getKey() but dump it inside of Model, so that model references its own method from the inside. $this->getKey().

I'll try to create simplified example, to show failing scenario.

**Comment by themsaid** [comment]
It makes no difference if you put it inside a method, it's still working. Even with eager loading it works, I think you need to dig deeper into it, not sure it's a framework related issue though.

**Comment by ddctd143** [comment]
I have tried. If dumping in foreach. Like so:

```
dd($advert->getKey()); // I see "2232"
```

If i'm doing same dump inside views() function in Advert model class, i see null

```php
class Advert extends Model
{
    public function views()
    {
        dd($this->getKey()); // null
        // ....
    }
}
```

I will try to prepare example with default Users model in clean laravel installation.

**Comment by ddctd143** [comment]
@themsaid I have created failing scenario gist and tried with fresh laravel install.

https://gist.github.com/ddctd143/6907eaa17623d873e23f98a0e118fb30

**Comment by themsaid** [comment]
Looks to me that your relationship method is wrong, you may use something like this:

```
    public function views()
    {
        return $this->morphMany(\App\Activity::class, 'subject')->where('event', 'request');
    }
```

This will automatically check the `subject_id` and `subject_type` for you, you also don't need a `user_id` field since the subject is the user.

Please refer to the docs: https://laravel.com/docs/5.3/eloquent-relationships#polymorphic-relations to know more about polymorphic relations.

Digging deep into the code I realised that the model isn't fully loaded while loading the relationship functions that's why you get null from within the relationship method. Relationship methods are means to do all this matching stuff under the hood.

Closing this since it's not an issue in the core, please feel free to ping me if you need any further assistance.
