### ISSUE TITLE
ErrorException in ManagesLoops.php

### ISSUE THREAD

**Issue by arthurkirkosa** [laravel/framework#17036]
- Laravel Version: 5.4.0-Dev (60afc37)
- PHP Version: 7.1.0
- Database Driver & Version: mysql 5.7.16

### Description:
For some time now I keep getting this error
```
ErrorException in ManagesLoops.php line 76:
Undefined variable: last
```

### Steps To Reproduce:
In a new installation, add to the `welcome.blade.php` file and view it in the borowser
```
@foreach (['a', 'b', 'c'] as $x)
{{ $x }}
@endforeach
```

**Comment by themsaid** [comment]
Thank you, got that fixed :)
