### ISSUE TITLE
[5.3.3] Routing Basic Routing Doesn't work on php 7.0.8

### ISSUE THREAD

**Issue by inlinex** [laravel/framework#17041]
- Laravel Version: 5.3.3
- PHP Version: 7.0.8
- OS: ubuntu 16.04.1 LTS (XENIAL)

### Description:
basic routing on this version of lumen doen't work

### Steps To Reproduce:
First I go to root_proj/public/index.php & modify $app->run(); to **$app->($app['request']);**, to get version the I have and was success
Second: I modified the **web.php** located on routes, and set a dummy route but doesn't work, only the default work...
I keep looking for any suggest to solve this problem...

**Comment by themsaid** [comment]
What is not working? and why are you altering the index.php file?

**Comment by GrahamCampbell** [comment]
This repo is laravel/framework. Unrelated to lumen routing.

**Comment by themsaid** [comment]
Didn't even notice it's a lumen issue :D

**Comment by inlinex** [comment]
lol uppsss sorry... my mistake @GrahamCampbell
