### ISSUE TITLE
Possible feature: AMQP 0.9, 1.0 and ØMQ drivers

### ISSUE THREAD

**Issue by khooz** [laravel/framework#17050]
Hi,

As of Laravel 5, it supports push notification support and far better queue support; but there is one drawback to this approach and that is the lack of support for free and open source protocols/products.

It will be great if more drivers become available for queues and push, such as AMQP 0.9 (for mainly RabbitMQ), AMQP 1.0 (for mainly Apache's Apollo) and ØMQ (for ZeroMQ protocol based servers).

Cheers!

**Comment by GrahamCampbell** [comment]
I think there's already a package for rabitmq for queue.

Feel free to open a proposal issue on the internals repo. We don't process things like that here.

**Comment by makasim** [comment]
https://github.com/laravel/framework/pull/20148
