### ISSUE TITLE
nested same component

### ISSUE THREAD

**Issue by parweb** [laravel/framework#17055]
- Laravel Version: 5.4.x-dev
- PHP Version: 7.1.0RC3
- Database Driver & Version: none

### Description:
When I try to nest the same component I've go an error
```
ErrorException in ManagesComponents.php line 79:
Undefined index: components.card (View: /path/to/laravel-54/resources/views/welcome.blade.php)
```
### Steps To Reproduce:
```
@component('components.card')
	@slot('title')
		ma box 1
	@endslot

	<div>
		@component('components.card')
			@slot('title')
				ma box 3
			@endslot

			plop 3
		@endcomponent
	</div>
@endcomponent
```

**Comment by GrahamCampbell** [comment]
Does this happen on 5.3.x too please?

**Comment by GrahamCampbell** [comment]
Does clearing the view cache fix it?

**Comment by parweb** [comment]
If I'm not wrong, the "component system" is new to laravel 5.4, right ?

Anyway I just tested on Laravel 5.4.

I started a fresh install of laravel and tried the exemple above right away

**Comment by caiquecastro** [comment]
How is your components card component file?

**Comment by parweb** [comment]
Component card

```
<div class="card">
	<h1>{{ $title }}</h1>
	<div>
		{{ $slot }}
	</div>
</div>
```

**Comment by Modelizer** [comment]
Ideally, I guess it should throw exception `components.card already declared or is been in use`.

**Comment by themsaid** [comment]
This doesn't seem to happen in latest 5.4.

**Comment by parweb** [comment]
thank you @themsaid (if you are the savior)  it's working perfectly now !

**Comment by themsaid** [comment]
Nope, I just pulled to test and found it working :D
