### ISSUE TITLE
[5.1] missing the namespace 'SymfonyUploadedFile' in the redirectResponse

### ISSUE THREAD

**Issue by davin-bao** [laravel/framework#17053]
- Laravel Version: 5.1
- PHP Version: 5.6 

it's same in #12335, this is very cleared issue,  the class Illuminate\Http\RedirectResponse missing SymfonyUploadedFile class's namespace, I think this is because merged #16295 [4d4eb4c](https://github.com/laravel/framework/commit/4d4eb4c258be3b48624215638a455602b8b43df1)

**Comment by GrahamCampbell** [comment]
Thanks.
