### ISSUE TITLE
Session not working in laravel 5.3

### ISSUE THREAD

**Issue by umairali** [laravel/framework#17056]
- Laravel Version: 5.3
- PHP Version: 5.6

### Description:
I am trying to create session like below code but session not working please sussgest me any soluton.

**Save** 
```
$data = array(
   "id" => $row->id,
   "name" => $row->name
);

Session($data);
```

**Fetch**
`Session('id');`

I also tried web middleware but till the same session not working

```
Route::group(['middleware' => ['web']], function ()
{

});
```

**Comment by GrahamCampbell** [comment]
Please ask on the fourms.

**Comment by Modelizer** [comment]
@umairali why this is capital? `Session($data);` it should be `session($data)`

**Comment by umairali** [comment]
I already tried with session but same issue session not working
