### ISSUE TITLE
[5.4] Form Request issue

### ISSUE THREAD

**Issue by brunogaspar** [laravel/framework#17062]
- Laravel Version: dev-master dbd20f2
- PHP Version: 7.1.0
- Database Driver & Version: _not relevant_

### Description:

Issue when submitting a form and the controller method use a form request.

### Steps To Reproduce:

When a form is submitted and the controller method is using a form request an exception is thrown.

### Exception thrown

```php
Type error: Argument 1 passed to Symfony\Component\HttpFoundation\Request::setSession() must be an instance of Symfony\Component\HttpFoundation\Session\SessionInterface, instance of Illuminate\Session\Store given, called in /app/vendor/laravel/framework/src/Illuminate/Foundation/Providers/FormRequestServiceProvider.php on line 60
```

**Comment by GrahamCampbell** [comment]
The method you need is now called `setIlluminateSession`. Also, note that `dev-master` is now Laravel 5.5, not 5.4. :)

**Comment by GrahamCampbell** [comment]
> The method you need is now called setIlluminateSession.

Looking at the framework code, looks like Taylor missed a few places when he did the refactoring. Thanks for the report. :)

**Comment by GrahamCampbell** [comment]
EDIT: `setLaravelSession`

**Comment by GrahamCampbell** [comment]
@brunogaspar Please let me know if https://github.com/laravel/framework/pull/17064 fixes your issue.
