### ISSUE TITLE
Weird situation with a table column's value fetching

### ISSUE THREAD

**Issue by rsm23** [laravel/framework#17069]
- Laravel Version: 5.4
- PHP Version: PHP 7.1.0
- Database Driver & Version: MariaDB

I'm retrieving data from **Database** like everyone else, but I'm facing a weird issue.
I'm using the slug in my table to retrieve the element's data but but I display the slug it gives me `null`and using the famous `dd()`famous it shows up here is an example :

    dd($element);

##Result
![gitbits dev](https://cloud.githubusercontent.com/assets/2084708/21579932/04f369e0-cfce-11e6-931d-d481445be868.png)

    dd($snippets->toArray());

##Result
![gitbits dev](https://cloud.githubusercontent.com/assets/2084708/21579935/3fb4f922-cfce-11e6-80d3-0ee5596d2446.png)

##Table

    Schema::create('elements', function (Blueprint $table) {
        $table->increments('id');
        $table->integer('user_id');
        $table->string('title');
        $table->string('slug')->unique();
        $table->text('body');
        $table->timestamps();
    });

##Eloquent

    $snippets = Snippet::latest()->with('owner')->get();

##Snippet Model

    protected $primaryKey = 'slug';

    public function owner()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

Is there any one who knows what is going on?

**Comment by lagbox** [comment]
You set 'slug' as primary key and have not set `incrementing` to false which is causing it to 'cast' it by the `keyType`.  The `keyType` is set to 'int' unless set otherwise.

**Comment by rsm23** [comment]
Yes, I've figured it out and I forgot to close the issue.
Thank you so much
