### ISSUE TITLE
Queues stopping half the code

### ISSUE THREAD

**Issue by MaximeDawn** [laravel/framework#17077]
- Laravel Version: 5.3.28
- PHP Version: 5.6.19
- Database Driver & Version: MySQL 5.7.11

### Description:
Ok i really must be missing something.. I created my job following the steps, configured my database driver and all of that seems to work. The process I have create 2 pdf files, and send them by mail. When I execute this code in the controller, everything is great, but when I decide to dispatch it to my job, it generates the first pdf, and them the code stops. Plus another issue is that I have to run `php artisan queue:work` everytime I want the queue to trigger.. Can't it just handle itself ?

Here's my job :

```
<?php
namespace App\Jobs;

use App\Jobs\Job;
use Illuminate\Queue\SerializesModels;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Contracts\Bus\SelfHandling;
use App\Models\ReportBoiler as Boiler;
use Mail;

class sendEmail extends Job implements SelfHandling, ShouldQueue
{
  use InteractsWithQueue, SerializesModels;
  protected $orderId;
  /**
  * Create a new job instance.
  *
  * @return void
  */
  public function __construct($order_id)
  {
    $this->orderId = $order_id;
  }

  /**
  * Execute the job.
  *
  * @return void
  */
  public function handle()
  {
Some code that works in the controller
  }
}
```

**Comment by GrahamCampbell** [comment]
Please ask on the forums.

**Comment by MaximeDawn** [comment]
Ok i'll do, thanks
