### ISSUE TITLE
Laravel 5.2 and Angular 2 set up.

### ISSUE THREAD

**Issue by abdul-khaliq** [laravel/framework#17082]
> Hi All,
> I want to Develop a website local search engine. 

### Points

* Front-End will be Angular 2
* API response Laravel 5.2
* Database MySql

### Help

* I've 3 database on different servers (Country wise).
* I want to Develop only 1 front-end so user can select county and can search query.
* So please help me how to start? I know Laravel and Angular but i never integrated these 2.

> Thank you.
> and sorry for bad English.

**Comment by Modelizer** [comment]
I think forums or blog will be more appropriate to get help :)
