### ISSUE TITLE
[Question] - How to push a raw message into queues

### ISSUE THREAD

**Issue by amandiobm** [laravel/framework#17083]
- Laravel Version: 5.3.16
- PHP Version: 7.0.11 (Windows)
- Database Driver & Version: MySQL | 5.6.21

How to add a simple raw message into queues?

**Comment by GrahamCampbell** [comment]
> How to add a simple raw message into queues?

Not supported by design, sorry.

**Comment by GrahamCampbell** [comment]
If you need this, just interact with your queue in a more direct way, bypassing the framework queue system.

**Comment by GrahamCampbell** [comment]
If you need any help with that, feel free to ask around on the forums.
