### ISSUE TITLE
redirectTo method not working

### ISSUE THREAD

**Issue by kentlee87** [laravel/framework#17092]
- Laravel Version: 5.3.28
- PHP Version: 5.7.6
- Database Driver & Version: MySQL

### Description:
In the documentation mentioned using the redirectTo method in the Authentication controller can do custom logic redirection. However, that doesn't work.

### Steps To Reproduce:
1. In your LoginController, create a method name redirectTo() and return the path string.
2. Login your application. It will always point to /home.

### Work Around:
This is the workaround and should be fix on the next version.
1. /vendor/laravel/framework/src/Illuminate/Foundation/Auth/RedirectsUser.php
2. Modify the redirectPath method:
```
    public function redirectPath()
    {
    	if ( method_exists($this, 'redirectTo') ) {
    		return $this->redirectTo();
    	} else {
    		return property_exists($this, 'redirectTo') ? $this->redirectTo : '/home';
    	}
    }
```

**Comment by themsaid** [comment]
I don't see where's the problem, the original implementation works fine:

    public function redirectPath()
    {
        if (method_exists($this, 'redirectTo')) {
            return $this->redirectTo();
        }

        return property_exists($this, 'redirectTo') ? $this->redirectTo : '/home';
    }

If a method exists it'll use it other wise the property will be used.

**Comment by RichieMcMullen** [comment]
I'm having this same issue:

In your LoginController, create a method name redirectTo() and return the path string.
Login your application. It will always point to /home

**Comment by NAIJULU** [comment]
The problem is with documentation, because show this: 

> If the redirect path needs custom generation logic you may define a redirectTo method instead of a redirectTo property:
> 
> protected function redirectTo()
> {
>     //
> }
> redirectTo method has higher priority than redirectTo attribute.
> 
> Source: [https://laravel.com/docs/5.3/authentication](https://laravel.com/docs/5.3/authentication)


But you need define redirectPath() method actually.

**Comment by maengkom** [comment]
Have same issue with 5.4.13, and the problem solved by @RichieMcMullen solution above.

**Comment by at-dungnguyen2** [comment]
just use return "/home"; for example do not use redirectTo('home');

**Comment by EmadAdly** [comment]
If you need more robust customization of the response returned when a user is authenticated, Laravel provides an empty `authenticated(Request $request, $user)` method that may be overwritten if desired:

So put this method in `LoginController.php`

```
protected function authenticated(Request $request, $user)
{
        return redirect()->route('displayNew');
}
```

**Comment by tgeorgel** [comment]
Solution from @EmadAdly was the good one for me.  

When having a look at `AuthenticatesUsers` trait, we can see that the `redirectPath()` method is called as a parameter to the the `Redirector::intended()` method : 

```
protected function sendLoginResponse(Request $request)
{
    // ...
    
    return redirect()->intended($this->redirectPath());
}
```

So, if the user got disconnected from a previous page, it would take precedence over our defined redirect path.
Better implementing the authenticated method if you need to force it.
