### ISSUE TITLE
Wrong Controller used by routes file - backup file

### ISSUE THREAD

**Issue by alessandrobelli** [laravel/framework#17094]
- Laravel Version: 5.1.43
- PHP Version: 5.5.9
- Database Driver & Version: mySQL

### Description:
I just found something totally weird.
The project is in production.
I had a checkbox not working, not updating the value in the database. Problems started 2 days ago, before that it was working.
The value is always updated and never stored. And the funny thing was locally on multiple devices it was working correctly.

After 2 hours of checking, I found that I had a backup file of the controller used for the update.
I deleted the file and then in the view I got an error like: "controllername_backup.php not found". I'm sorry I couldn't make a screenshot or exactly know the error name, I had to fix the issue as fast as I could.

I just ran composer dump-autoload and PHP artisan optimize and then everything worked.

I probably know the error: I had 2 classes with the same name, so the command just got the wrong one. If it's like that, may I ask if I can see some errors on php artisan optimize like "multiple class name in the same namespace"?

Anyway it's weird because it worked for months before this error showed, the backup file was there since October.

Just to be clear: I make a backup file because the project is in production and used by many users, so if there are some issues with the update I can switch back easily.

### Steps To Reproduce:

1. create a simple form with a checkbox.
2. create a controller to update a checkbox.
3. create a controllername_backup file.
4. in the backup file don't update the checkbox.
5. check which controller file is used.

**Comment by GrahamCampbell** [comment]
You must use PSR-4. No extra files lying around please.

**Comment by alessandrobelli** [comment]
> You must use PSR-4

Just to be clear, I'm using PSR-4.
Ok, won't leave any extra file...
