### ISSUE TITLE
Blade include inheritance issue

### ISSUE THREAD

**Issue by amonger** [laravel/framework#17100]
- Laravel Version: 5.3
- PHP Version: 7
- Database Driver & Version: n/a

### Description:

I noticed when using inheritance for a card module, that variables are not being correctly assigned.

For example, if you have 

extend.blade.php
```PHP
<h1>{{ $title }}</h1>
@yield('content')
```

include.blade.php
```PHP
@extends('extend')
    
@section('content')
    {{ $content }}
@endsection
```

page.blade.php
```PHP
@foreach([['title' => 'foo', 'content' => 'foocontent'], ['title' => 'bar', 'content' => 'barcontent']] as $item)
    @include('include', $item)
@endforeach
```

You'd expect:

```
foo

foocontent
bar

barcontent
```

You actually get:

```
foo

foocontent
bar

foocontent
```

I'll have a look tonight an see if I can come up with a fix.

**Comment by themsaid** [comment]
Use @overwrite

```
@section('content')
    {{ $content }}
@overwrite
```
