### ISSUE TITLE
Problem with updating Mysql JSON fields

### ISSUE THREAD

**Issue by sl0wik** [laravel/framework#17108]
- Laravel Version: 5.3.26
- PHP Version: 7.0
- Database Driver & Version: MySQL 5.7.9

### Description:
In my mysql database I have json column (`$table->json('custom')`), casted to object (`protected $casts = ['custom' => 'object'];`). In database field got value equal to '{}' (empty json object).

I can update this property only by updating entire row (->custom= [...]), and not by updating single property (->custom->variable = 1);

### Steps To Reproduce:
`php artisan tinker`
```
...
>>> $model->custom->value = 100;
=> 100
>>> echo $model->custom->value;
PHP error:  Undefined property: stdClass::$value on line 1
>>> $custom = $model->custom;
=> {#761
   }
>>> $custom->value = 100;
=> 100
>>> $model->custom = $custom;
=> {#761
     +"value": 100,
   }
>>> echo $model->custom->value;
100ΓÅÄ
=> null
>>>
```

This behavior seems weird. Better handling of json columns would be very helpful.

**Comment by themsaid** [comment]
You can't update a JSON attribute like this `$model->custom->value`, you need to use `update()` to update the whole field `custom` or a portion `custom=>value`.

Please check on the forums for more information.
