### ISSUE TITLE
Model->save() not trowing an exception when insert fail

### ISSUE THREAD

**Issue by rafwell** [laravel/framework#17104]
- Laravel Version: 5.3.28
- PHP Version: 7
- Database Driver & Version: SQL Server 2008

### Description:
When my insert fail (because the key is duplicated, for example) i've expected get an exception, but the execution stop like and "die". The server response is an error 500 but i cant catch the exception. 

### Steps To Reproduce:
1) Create a block try~catch.
2) load an model and try insert an register with duplicated key.

**Comment by themsaid** [comment]
A `QueryException` is thrown successfully in this case, just tested. Please test on a fresh laravel installation and include more information in `Steps To Reproduce` on how I can replicate the issue on a fresh laravel installation.

**Comment by rafwell** [comment]
Lol, i have a problem here. In fresh installation work fine. I'll investigate this case. I'm sorry for wasting your time.
