### ISSUE TITLE
PUSHER_APP_KEY .env

### ISSUE THREAD

**Issue by Francismori7** [laravel/framework#17140]
- Laravel Version: 5.4 dev
- PHP Version: 7.1
- Database Driver & Version:

### Description:
It appears that the new default .env file containing APP_KEY and PUSHER_APP_KEY gets a double generated APP_KEY upon installation.

### Steps To Reproduce:
`laravel new demo --dev`
See .env file containing: 

```
APP_KEY=base64:xWiu0LfiJsvKXxzDq6YgqL4mPqd3SapixvYkuRbT2cw=
# [redacted]
PUSHER_APP_KEY=base64:xWiu0LfiJsvKXxzDq6YgqL4mPqd3SapixvYkuRbT2cw=
```

**Comment by themsaid** [comment]
Closing since the PR was reverted already.
