### ISSUE TITLE
[5.3] queue fail() does not work correctly inside a queued command

### ISSUE THREAD

**Issue by laurencei** [laravel/framework#17155]
- Laravel Version: 5.3.28
- PHP Version: 7.1.0-3
- Database Driver & Version: Redis Queue

### Description:

The `InteractsWithQueue` has a public function `fail()` that states "Fail the job from the queue".

It is not not documented if this should permanently fail the job (regardless of the number of `--tries` set) and insert itself as a failed job on the `failed_jobs` table - or if it should fail this single attempt and allow more `tries` to occur.

Either way - neither of these occur - meaning you can have a queue job fail without a database record and/or more tries.

### Steps To Reproduce:

    public function handle()
    {
        Log::info('I am running: '.$this->attempts());
        $this->fail();
    }

    public function failed(Exception $exception)
    {
        Log::info('failed: '.$this->attempts());
    }

When I run `php artisan queue:work --tries=3` I get the following output (notice the green processed text):

![image](https://cloud.githubusercontent.com/assets/1210658/21665890/56e024da-d2e6-11e6-8af6-8a86b9ec2716.png)

And this is in my log file:

    [2017-01-05 01:20:00] local.INFO: I am running: 1  
    [2017-01-05 01:20:00] local.INFO: failed: 1  

And my `failed_jobs` is empty.

To show that everything else works - if I do this:

    public function handle()
    {
        Log::info('I am running: '.$this->attempts());
        throw new Exception;
    }

    public function failed(Exception $exception)
    {
        Log::info('failed: '.$this->attempts());
    }

I then get this console output (notice the red failed text):

![image](https://cloud.githubusercontent.com/assets/1210658/21665920/6c785772-d2e6-11e6-8b14-0e1d7101d8eb.png)

And this is in my log file:

```
[2017-01-05 01:22:49] local.INFO: I am running: 1  
[2017-01-05 01:22:49] local.ERROR: Exception in .... {full exception stack}
[2017-01-05 01:22:52] local.INFO: I am running: 2  
[2017-01-05 01:22:52] local.ERROR: Exception in .... {full exception stack}
[2017-01-05 01:22:55] local.INFO: I am running: 3  
[2017-01-05 01:22:55] local.INFO: failed: 1  
[2017-01-05 01:22:55] local.ERROR: Exception in .... {full exception stack}
```

And I also get an entry in my `failed_jobs` as normal.

So I would expect calling `$this->fail()` to *either* push back onto the queues for more `tries` - or at least formally fail (with the console output correct & a job in my `failed_jobs` queue).

I'll try and dig into the code to find the cause of error tomorrow if I get some time...

**Comment by lioannou** [comment]
Just noticed - there might be a second bug (or maybe related).

Why does `Log::info('failed: '.$this->attempts());` give `1` in the last log dump above? It should be `3`?

**Comment by themsaid** [comment]
This isn't the case in 5.4, closing until someone could regenerate this in 5.4

**Comment by tim0991** [comment]
i have the same error in laravel 5.6.28

**Description**
when i `throw new Exception` in job,  it will retry immediately and it didn't call `failed()`, unless it is reached the max retry number

**Expect**
After a job catch an exception, i expect the job would calling `failed()` method
Let me to decide whether it is continue to retry or discarded in `failed()`method
