### ISSUE TITLE
[5.3] - [Validation Rule] Checking the size for multiple files does not work

### ISSUE THREAD

**Issue by lukepolo** [laravel/framework#17167]
- Laravel Version: 5.3.28
- PHP Version: 7.0.13
- Database Driver & Version: N/A

### Description:
When using the `size` validation on multiple files it will always say 

```
{files.0: ["The files.0 must be max:20000 kilobytes."],…}
files.0
:
["The files.0 must be max:20000 kilobytes."]
files.1
:
["The files.1 must be max:20000 kilobytes."]
....
```

### Steps To Reproduce:
Upload multiple files and use the validation rule 

`'files.*' => 'nullable|size:max:20000'`

**Comment by themsaid** [comment]
I can't see the issue in the messages you shared, I see that 0 and 1 exceeded the maximum limit so errors here make sense, please share more information.

**Comment by lukepolo** [comment]
The files were not over 20,000, infact they were only 4kb

**Comment by themsaid** [comment]
`size:max:20000` this isn't a valid rule definition, is that what you actually used?

**Comment by lukepolo** [comment]
🤦‍♂️
