### ISSUE TITLE
QueueNotification clones notification in wrong order

### ISSUE THREAD

**Issue by MithrandirDK** [laravel/framework#17171]
- Laravel Version: 5.3.*
- PHP Version: 7.0.4-5
- Database Driver & Version:
MySQL 5.6

### Description:
Illuminate\Notifications\ChannelManager::queueNotification() clones the notification to send inside the $notification->via($notifiable) loop.
_However_ this is also inside a loop of foreach ($notifiables as $notifiable) which can end up calling $notification->via($notifiable) with a $notification object that potentially has been altered in the queueing process.

### Steps To Reproduce:
In my case, I had an App\Content object in my notification class property and after the first run of the queueing loop, this property would be a ModelIdentifier object instead.

So to boil down the situation:
```
<?php

namespace App\Notifications;

use App\Content;
use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Notification;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Queue\SerializesModels;

class DebatePublished extends Notification implements FirebaseNotification, ShouldQueue
{
    use Queueable, SerializesModels;

    protected $item;

    /**
     * Create a new notification instance.
     *
     * @param \App\Content $content
     */
    public function __construct(Content $content)
    {
        $this->item = $content;
    }

    /**
     * Get the notification's delivery channels.
     *
     * @param  mixed  $notifiable
     * @return array
     */
    public function via($notifiable)
    {
        $ret = ['database'];
        // Use $this->item->someProperty here
       var_dump(get_class($this->item)); // Will be App\Content on first notifiable, ModelIdentifier on later

        return $ret;
    }

    /**
     * Get the array representation of the notification.
     *
     * @return array
     */
    public function toArray()
    {
        return [
          'id' => $this->item->id,
          'title' => $this->item->title,
        ];
    }
}

```

Sending this notification to multiple notifiables should show different outputs in the var_dump()'s

### Suggested Fix:
Move the line
$notification = clone $original; 
AFTER
$bus->dispatch()
to make it re-set the $notification object after queueing rather than before

**Comment by themsaid** [comment]
Thank you for reporting this, a PR was opened with a proposed fix https://github.com/laravel/framework/pull/17182

**Comment by themsaid** [comment]
@MithrandirDK can you please share what problems does this cause?

**Comment by MithrandirDK** [comment]
@themsaid Fatal errors due to calling member functions or properties not in the ModelIdentifier class.

In my above code example, if I expect $this->item to be of type App\Content, I also expect to be able to use the object in the via() method - it could be that App\Content has a category and I want to look up the notification channels, the user wants to use for that category.
In that case, I would probably call something like 
```
$preferences = $this->item->getCategoryPreferences($notifiable);
```
which only works on the first run, since $this->item will be a ModelIdentifier on second run that does not have getCategoryPreferences function.

### Alternative solution
Instead of moving the $notification = clone $original; line, you could just add another identical line at the top of the outside loop to ensure that $notification == $original before calling the via() method.
