### ISSUE TITLE
[5.3/5.4] Default value for explicit bindings proposal 

### ISSUE THREAD

**Issue by segadora** [laravel/framework#17172]
- Laravel Version: 5.3 or 5.4
- PHP Version: any
- Database Driver & Version: any

### Description:

I wish to have a change to **Explicit bindings** in [routes](https://laravel.com/docs/5.3/routing#route-model-binding).

If I understand it correctly. Implicit bindings hits the following code, which results in a **first** or **firstOrFail**, which means if I set a default value. I would expect to hit the method no matter, if the model is found or not.

https://github.com/laravel/framework/blob/f880e093dfbfc80a2ab0797d2056580e47e6888d/src/Illuminate/Routing/Router.php#L805

On route bindings (explicit bindings) it hits somewhere else, where it does not check if the method has a default value. This means it always will throw a 404 exception, if the model is not found.

https://github.com/laravel/framework/blob/f880e093dfbfc80a2ab0797d2056580e47e6888d/src/Illuminate/Routing/Router.php#L949

### Steps To Reproduce:

Create a explicit binding with a default value.

RouteServiceProvider.php
```
public function boot()
{
    parent::boot();

    Route::model('user', App\User::class);
}
```

routes.php
```
Route::get('profile/{user}', function (App\User $user = null) {
    //
});
```
**Notice:** ` = null`

I would expect it to hit the route, and not throw a 404 exception (ModelNotFound), because ` = null` is set.

**Comment by themsaid** [comment]
Thank you, but for suggestions and feature requests please use the https://github.com/laravel/internals repo.

**Comment by segadora** [comment]
Sorry
