### ISSUE TITLE
php artisan make:migration and php artisan migrate commands stopped working.

### ISSUE THREAD

**Issue by tahirwaseer** [laravel/framework#17175]
- Laravel Version: 5.1.27
- PHP Version: 5.5.29
- Database Driver & Version:

### Description:
I've an existing project which was working fine. But I don't know what has happened but my `php artisan make:migration` command stopped working. I checked directory permissions as well, I've read & wright permissions on directory. 
After this issue I started to create migration file manually and migrated them using `php artisan migrate` command and it worked fine, it displayed info message that migration is migrated and changes were reflected in db as well. NOW this command also stopped working. 
I've tried some solutions;

- Re-install laravel/framework
- Tried to re-assign permissions some guys suggested on stackoverflow
- Cloned my repo in separate location and then tried again by installing all packages again
Nothing seems to be working. I've other projects it is working there. 
I've posted this question on stackoverflow as well with some additional info. [Stackoverflow Question](http://stackoverflow.com/questions/41480576/laravel-cannot-generate-migration-file-with-makemigration-command)

Any work around or suggestions to debug it would be appreciated. Did someone else face this issue may be point out some issue.

**Comment by DanielKeeble** [comment]
How has it stopped working? Are you seeing an error message?

**Comment by tahirwaseer** [comment]
Closing it. I don't really get why it was behaving like this. I've just tried some solutions mentioned above. And also cleared all cache and configs;

- `php artisan cache:clear`     # clear all cached files.
- `php artisan config:clear`    # clear application config cache
- `composer dump-autoload` # reload all autoload classes
And quit the "TERMINAL" and reopen it, hope it should be working now.

**Comment by Hemrajawasthi** [comment]
hem-Inspiron-3443:/opt/lampp/htdocs/shremadlv$ php artisan migrate

   Illuminate\Database\QueryException  : could not find driver (SQL: select * from information_schema.tables where table_schema = shreemad and table_name = migrations and table_type = 'BASE TABLE')

  at /opt/lampp/htdocs/shremadlv/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673| 

  Exception trace:

  1   PDOException::("could not find driver")
      /opt/lampp/htdocs/shremadlv/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70

  2   PDO::__construct()
      /opt/lampp/htdocs/shremadlv/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70

  Please use the argument -v to see more details.

Problem not solved !!
