### ISSUE TITLE
[5.4] Laravel cache does not support false as a cached value anymore

### ISSUE THREAD

**Issue by halaei** [laravel/framework#17188]
- Laravel Version: 5.4

### Description:
I think https://github.com/laravel/framework/pull/15160 has an unnecessary change that should be undone, unless there is a reason for that:

> `Illuminate/Cache/RedisStore` and Illuminate/Cache/Repository now check key existence using null or false.

In the code, all the checks for `if (is_null($value))` are converted to `if (is_null($value) || $value === false)`. IMHO, it adds an unnecessary limitation to the Laravel Cache.

@tillkruss do you agree?

### Steps To Reproduce:
```php
\Cache::put('x', false, 60);
var_dump(\Cache::has('x'));
```

#### Expected output:
`true`

#### Actual output:
`false`

**Comment by tillkruss** [comment]
Predis returns `null` when a cache key doesn't exists. PhpRedis and HHVM usually return `false`.

Laravel uses a strict comparison, so you'ldo need to use  something like `"false"` or `0` or `"no"` from 5.4 onwards.

**Comment by GrahamCampbell** [comment]
To get around this, we could get each connector to throw an exception for a miss?

**Comment by halaei** [comment]
@tillkruss 
I think laravel is not supposed to support HHVM anymore? I have no idea about returning false instead of null by PhpRedis. If it is true, then maybe the redis driver should handle false itself. Moreove, maybe Redis Queue driver needs fixes for that as well?

```php
    public function get($key)
    {
        $value = $this->connection()->get($this->prefix.$key);
        if (! is_null($value) && $value !== false) {
            return $this->unserialize($value);
        }
    }
```

**Comment by GrahamCampbell** [comment]
Indeed, HHVM support has been dropped.

**Comment by taylorotwell** [comment]
It's probably indeed true we need a PR to normalize this across the drivers so that null is returned for miss from both.

**Comment by tillkruss** [comment]
I don't think storing PHP types like booleans in Redis is a good idea in general.

- `true` is stored as `1`.
- `false` is stored as an empty string

However the root problem seems to be that `Illuminate\Cache\Repository::has()` is using a `GET` call to check a keys existents and it should really be using an `EXISTS` call.

**Comment by halaei** [comment]
@tillkruss true is not stored as 1 and false is not stored as empty string
in the current code. true and false (as well as everything except numbers)
are php-serialized into strings before being stored.

On Jan 7, 2017 10:36 PM, "Till Krüss" <notifications@github.com> wrote:

I don't think storing PHP types like booleans in Redis is a good idea in
general.

   - true is stored as 1.
   - false is stored as an empty string

However the root problem seems to be that Illuminate\Cache\Repository::has()
is using a GET call to check a keys existents and it should really be using
an EXISTS call.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/laravel/framework/issues/17188#issuecomment-271103124>,
or mute the thread

**Comment by tillkruss** [comment]
Right, when using Laravel's cache, not when using Redis directly.

**Comment by tillkruss** [comment]
See https://github.com/laravel/framework/pull/17196#issuecomment-271731155

**Comment by casperbakker** [comment]
> It's probably indeed true we need a PR to normalize this across the drivers so that null is returned for miss from both.

That's it. I am done with Laravel. What is this for a reason? Cache::has() should only check if the key exists and nothing more. Why even check the inner results?

**Comment by tillkruss** [comment]
@casperbakker: Feel free to open a discussion on https://github.com/laravel/internals.
