### ISSUE TITLE
[5.1] Laravel Jobs using empty() have different behavior in PHP7

### ISSUE THREAD

**Issue by peterjdev** [laravel/framework#17184]
#- Laravel Version: 5.1
- PHP Version: PHP7
- Database Driver & Version: MySql

### Description:

We are seeing different behavior when using Laravel 5.1 with PHP7 then we were with PHP5 when using the empty() function in Jobs

### Steps To Reproduce:

We have a User model and a Terminal model.

Terminal model belongs to User.

We are calling this query in a Job.

$userTimezone = User::where('id',1)->first();

empty($userTimezone->terminal->timezone); // PHP5 returns true

empty($userTimezone->terminal->timezone); // PHP7 returns false
  

There's workarounds, but we found this to be odd. Anyone else seeing this challenge? I couldn't find anything in the PHP7 documents about empty() changing.

Thank you for looking.

**Comment by GrahamCampbell** [comment]
Sounds like a bug in your app code, since no code there you've quoted belongs to laravel. You're just reporting that calling the empty function provided by php, on a datetime object, then it behaves differently on different php versions.

**Comment by peterjdev** [comment]
Thanks for commenting @GrahamCampbell. I'll try a different forum.
