### ISSUE TITLE
[5.3] redirectPath() on RedirectUsersTrait is not looking for redirectTo method 

### ISSUE THREAD

**Issue by ateszki** [laravel/framework#17190]
- Laravel Version: 5.3.28
- PHP Version: 5.6.24
- Database Driver & Version: Mysql 5.7.11

### Description:

The RedirectUsersTrait has a public method redirectPath, this method looks for the existence of the property redirectTo and returns that or defaults to '/home'.

On the laravel docs https://laravel.com/docs/5.3/authentication#included-authenticating it says that if you need redirection login you can define a redirectTo method instead.

But the redirectPath method is not taking that in account.

### Steps To Reproduce:

Edit App/Http/Controllers/LoginController.php and comment $redirectTo and create a redirectTo function to domething like

`protected function redirectTo()
    {
      return \Auth::user()->roles()->count() > 1 ? '/role-selector' : '/home';
    }`

**Comment by themsaid** [comment]
Here's how the redirect path is computed:

```php
    public function redirectPath()
    {
        if (method_exists($this, 'redirectTo')) {
            return $this->redirectTo();
        }

        return property_exists($this, 'redirectTo') ? $this->redirectTo : '/home';
    }
```

So it surely checks for a `redirectTo` method first before using the property.

**Comment by sisve** [comment]
Note that this functionality was added in 5.3.29, you are using 5.3.28.

https://github.com/laravel/framework/commit/794b260746d7a3bdf8b691bb1e5187716bb21685

**Comment by themsaid** [comment]
Thank you @sisve, good catch :)

**Comment by ateszki** [comment]
Thanks, I was reading the 5.3 docs and It said that this functionality was available, I wasn't aware that was in a newer version than mine. Thanks!
