### ISSUE TITLE
Field validation 'confirmed' should not implies 'required'

### ISSUE THREAD

**Issue by Cyrille37** [laravel/framework#17192]
- Laravel Version: 5.3.16
- PHP Version: 5.6
- Database Driver & Version: mysql

### Description:

The validation rule "confirmed" implicitly implies "required", but it should not !

### Steps To Reproduce:

when a field with "confirmed" but NOT "required" is NOT in input the "confirmed" validation failed and say does not match.

**Comment by Cyrille37** [comment]
Perhaps `Illuminate\Validation\Validator::validateConfirmed()` should test `Validator::hasAttribute()|` before test `Validator::validateSame()` ?

**Comment by themsaid** [comment]
I don't seem to understand, can you please share a failing scenario?

**Comment by manniL** [comment]
@Cyrille37 Have you tried `sometimes|confirmed` as validation rule?

**Comment by Cyrille37** [comment]
@manniL The `sometimes` does not change, the `confirmed' validation fail with "The password confirmation does not match."
I right a failed demo and post it here quickly

**Comment by themsaid** [comment]
ping @Cyrille37 please provide sample code to test against

**Comment by Cyrille37** [comment]
@themsaid I wrote a test case and can discover that **the issue does not comes from Illuminate Validation**.
While I opened this issue from a Model validation issue managed with Esensi ValidatingModelTrait I will investigate in that way.
Thanks for support, and sorry for noise :-)

A route:
```php
Route::post('/essais/ValidationConfirmedIssue', [
	'uses' => 'Essais\ConfirmedIssueDemo@post'
]);
```
A Controller:
```php
namespace App\Http\Controllers\Essais;
use Illuminate\Http\Request;
use Illuminate\Foundation\Validation\ValidationException ;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;

class ConfirmedIssueDemo extends BaseController
{
	use ValidatesRequests;

	public function post(Request $request) {
		try {
			$this->validate($request, [
				'password' => 'confirmed',
			]);
		} catch(ValidationException $ex) {
			return 'Validation failed';
		}
		return 'Validation ok';
	}
}
```

A TestCase:
```php
class ConfirmedIssueDemoTest extends \TestCase
{
	/**
	 * @return void
	 */
	public function testConfirmedValidation()
	{	
		$response = $this->post('/essais/ConfirmedIssueDemo', [
			'password' => 'shuuut!',
			'password_confirmation'=> 'shuuut!'
		])
		->see('Validation ok');

		$response = $this->post('/essais/ConfirmedIssueDemo', [
			'password' => 'shuuut!',
		])
		->see('Validation failed');

		$response = $this->post('/essais/ConfirmedIssueDemo', [
		])
		->see('Validation ok');
	}
}
```

**Comment by Cyrille37** [comment]
Really not a software bug, just a brain's bug.
Very sorry for noise !
Cheers, Cyrille.
