### ISSUE TITLE
[5.1] Factory $factory->define() method executes create() functions of related records even if the foreign key is overwritten.

### ISSUE THREAD

**Issue by mchekin** [laravel/framework#17197]
- Laravel Version: 5.1.45
- PHP Version: 5.6.22
- Database Driver & Version:

### Description:
Factory $factory->define() method executes create() functions of related records even if the foreign key is overwritten.

### Steps To Reproduce:

Let say we use the default User factory and we add a related field 'createdById', which references another related user record:
```
$factory->define(App\User::class, function (Faker\Generator $faker) {
    return [
        'name' => $faker->name,
        'email' => $faker->safeEmail,
        'password' => bcrypt(str_random(10)),
        'remember_token' => str_random(10),
        'createdById' => factory(App\User::class)->create(),
    ];
});
```

Now if we call ```factory(App\User::class)->create()``` without passing any overwriting parameters it would create a non-stopping loop of creation and eventually fail with 
```Maximum function nesting level of '256' reached, aborting!```
and that is expected.

But, if I overwrite the 'createdById' when calling create()
```
factory(App\User::class)->create([
     'createdById'  => 1,
]);
```
It seems it should not go into this loop, because there is no reason creating the related user record if it's immediately overwritten.
Still it calls the inner create() method inside the define() function, just like before, and goes into the same loop of failure.

I know this example seems far fetched, but it isn't because it always creates redundant records when you are overwrite calls to create() by passing foreign key to it 
Usually, you just don't notice it because foreign keys mostly refer to other tables. So it uses all the related factory create() calls silently thus creating all those useless records. 
And if you have a big system with many interconnected tables with many relationships, your tests can run for a long time creating all the superfluous records and thus creating artifacts in the system. 
For example when you expect only 3 users but you have 12 instead , because some of them were created unintentionally under the hood.

**Comment by Crinsane** [comment]
Like it says in the docs, define the relationship as a closure:

```
$factory->define(App\Post::class, function ($faker) {
    return [
        'title' => $faker->title,
        'content' => $faker->paragraph,
        'user_id' => function () {
            return factory(App\User::class)->create()->id;
        }
    ];
});
```

**Comment by mchekin** [comment]
@Crinsane 
Can you post a link to the specific docs section you are talking about?
I think the closure option works from Laravel 5.2 on.
Anyway I found old issue related to this problem exactly. Unfortunately I've lost the link :rofl: .

So a possible solution for Laravel 5.1 would be using the second parameter, which is an array of overwriting parameters, on $factory->define() closure and only using related object factory if the field wasn't passed in to the closure. Like so:
```
$factory->define(App\Post::class, function ($faker, array $params) {
    return [
        'title' => $faker->title,
        'content' => $faker->paragraph,
        'user_id' => isset($params['user_id']) ? $params['user_id'] : factory(App\User::class)->create()->id,
    ];
});
```
