### ISSUE TITLE
Make API throttling throw an exception

### ISSUE THREAD

**Issue by michaelcullum** [laravel/framework#17208]
Current behaviour is that if you have hit the rate limit it will simply return a response built in the controller. https://github.com/illuminate/routing/blob/master/Middleware/ThrottleRequests.php#L44

It would be nice if this response was customisable (for example to return JSON when `Accept-type: application/json` is used) in applications but this isn't possible in the current state so either an event could be added or this could be converted to an exception (Similarly to how validation is carried out).

Symfony has a TooManyRequestsHttpException that could be extended?

Component: Routing

**Comment by GrahamCampbell** [comment]
You could just make you own midd,leware?

**Comment by GrahamCampbell** [comment]
Infact, there's one here: https://github.com/AltThree/Throttle.
