### ISSUE TITLE
Usage of broadcastAs as alternative to get_class

### ISSUE THREAD

**Issue by webmake** [laravel/framework#17200]
Hello to all,

Wouldn't it better to use [aliases](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Events/Dispatcher.php#L202) for all events within this place:
```
if (is_object($event)) {
    $name = method_exists($event, 'broadcastAs') ? $event->broadcastAs() : get_class($event);
    list($payload, $event) = [[$event], $name];
}
```
Like it was done in [BroadcastEvent](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Broadcasting/BroadcastEvent.php#L42)

What was the reason to use only `get_class($event)`?

I know there is several ways to dispatch event:
`app('events')->fire('string_event', [$payload])` and `event('string_event', [$payload])` propose to use named event to stream for listeners, that is good.
But using event objects, is better approach from OOP perspective: `event(new UpdateRecordEvent())`

Here comes the trick:
* I have to define full path as string of the event to listener,
```
------------------------------------------------------------
App\Modules\X\Providers\EventServiceProvider.php:
------------------------------------------------------------
    protected $listen = [
        'App\Modules\Y\Events\UpdateRecordEvent' => [
            UpdateRecordListener::class,
        ],
    ];
```
* either use App\Modules\Y\Events\UpdateRecordEvent::class and include usage of that event, and more over having modular project, it becomes tied up both modules.

After my suggested broadcastAs alias, it would become:
```
------------------------------------------------------------
App\Modules\Y\Events\UpdateRecordEvent.php:
------------------------------------------------------------
namespace App\Modules\Y\Events;

class UpdateRecordEvent
{
    public function broadcastAs()
    {
        return 'update_record';
    }
}
------------------------------------------------------------
App\Modules\X\Providers\EventServiceProvider.php:
------------------------------------------------------------
    protected $listen = [
        'update_record' => [
            UpdateRecordListener::class,
        ],
    ];
```
There is no need to know for module X about Y event, neither opposite direction.

Thanks

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
