### ISSUE TITLE
Custom request binding

### ISSUE THREAD

**Issue by mnabialek** [laravel/framework#17203]
- Laravel Version: 5.3.29
- PHP Version: 7.0.14

### Description:

I have difficulty to rebind request to my custom implementation of Request class and I'm not sure if it's issue in Framework or maybe I'm doing it in wrong way.

### Steps To Reproduce:

In my `AppServiceProvider` class in `boot` method I use the following code:

```php
$myRequest =  $this->app->make(MyRequest::class);
$this->app->instance('request', $myRequest);
$this->app->instance(Request::class, $myRequest);
```

When I add here:

```php 
dd(get_class($this->app['request']));
```

or 

```php
dd(get_class($this->app[Request::class));
```

in both cases I'm getting my custom implementation here:

> App\Http\Requests\MyRequest

what seems to be fine.

But when I try to use it in controller it's not working like this any more.

When I use 

```php
dd(get_class($app->make(Request::class)));
```

I'm getting same as previous, so 

> App\Http\Requests\MyRequest

and this is what I expect.

However when I use:

```php
dd(get_class(app()->make('request')));
```

now I'm getting

> Illuminate\Http\Request

so I'm getting the original class instead of custom one.

Is it the expected behaviour or I'm doing something wrong or maybe it's a bug?

**Comment by sisve** [comment]
Modify your `public/index.php` to capture your instance type instead of the builtin.

```
$response = $kernel->handle(
    $request = \App\Http\Requests\MyRequest::capture()
);
```

**Comment by mnabialek** [comment]
@sisve Thank for your suggestion but it seems it might be not complete. When running application it's in fact fine using this solution, but when running tests, I'm getting again:

> Illuminate\Http\Request

both with commented and unccomented changes in AppServiceProvider I showed above.

Also this is quite odd that in AppServiceProvider without your solution I'm getting expected value when but in controller I don't.

**Comment by sisve** [comment]
In your service provider, replace the request factory before any Request object is created.

```
Request::setFactory(function(array $query = array(), array $request = array(), array $attributes = array(), array $cookies = array(), array $files = array(), array $server = array(), $content = null) {
    return new MyRequest($query, $request, $attributes, $cookies, $files, $server, $content);
});
```

**Comment by sisve** [comment]
Looks like you need to set the request factory way early in your tests, in the refreshApplication() method before calling parent::refreshApplication(). However, this issue is not a bug report, and should be moved over to the forums.
