### ISSUE TITLE
[5.3] Request add a non form field

### ISSUE THREAD

**Issue by RicardoRamirezR** [laravel/framework#17224]
- Laravel Version: 5.3.29
- PHP Version: 7.0 / 7.1.0
- Database Driver & Version: mariaDB 10.0.24

### Description:
I just change the hosting provider where the app was running without any issue (PHP 5.6) and I noticed that sending a POST request with:
```
$('form#queryForm').serialize()
"from=express&user_id=wzJ6v357mE23&exam=&last_vaccine=23%2F06%2F2016&last_desp=&appealling=1&dieta=&temp=&pv=&fc=&fr=&mucosas=&mental=&remarks="
``` 
the ```request()->all()``` has and additional field ```q```
```
array:15 [
  "from" => "express"
  "user_id" => "wzJ6v357mE23"
  "exam" => ""
  "last_vaccine" => "23/06/2016"
  "last_desp" => ""
  "appealling" => "1"
  "dieta" => ""
  "temp" => ""
  "pv" => ""
  "fc" => ""
  "fr" => ""
  "mucosas" => ""
  "mental" => ""
  "remarks" => ""
  "q" => "/histories/storeExpress/y2X8YpoN7woL"
]
```
Any clue?

**Comment by themsaid** [comment]
Sorry but please ask questions on the forum, I'm sure someone will help you there. We keep this repo for bug reporting only :)

**Comment by RicardoRamirezR** [comment]
Thanks for you attention, and sorry I thought  it 'may be' was a bug. Going to forums.

**Comment by RicardoRamirezR** [comment]
@themsaid I posted the issue on forums without any response, so:

I dig down til ```Illuminate/Foundation/Http/Kernel.php```, in line 129 and event is fired, so the listener: 

```
public function handle($request)
{
    if (auth()->check() && auth()->user()->id == 1) {
        dd([
            'request' => $request->all(),
            'POST' => $_POST
        ]);
    }
}
```

The ```dd``` output:
```
array:2 [▼
  "request" => array:1 [▼
    "q" => "/users/gB57NM03eoDw/colors"
  ]
  "POST" => []
]
```
Have compassion on me and give me a clue where to go

**Comment by RicardoRamirezR** [comment]
@themsaid if I put ```var_dump($_GET);``` at the top of public/index.php I got:
```
array(1) { ["q"]=> string(26) "/users/gB57NM03eoDw/colors" }
```
So is a php issue, for sure in some config. I'll research this.

Thank you.

**Comment by RicardoRamirezR** [comment]
Finally a nginx misconfiguration
