### ISSUE TITLE
Login throttling not working with array as cache

### ISSUE THREAD

**Issue by dimahali** [laravel/framework#17239]
- Laravel Version: 5.3.*
- PHP Version: 7.0.4
- Database Driver & Version:

### Description:
Laravel default login throttling is not working when the cache is set to array, everything works fine when I set the cache to file... but the problem is with Zizaco Entrust as I am using Entrust which is not supporting file and database cache...

### Steps To Reproduce:

Laravel installation
generate auth
set cache to array
check login throttle by attempting

**Comment by themsaid** [comment]
Array driver doesn't retain cached values between requests, it's not an actual cache driver.
