### ISSUE TITLE
 Call to a member function make() on null 

### ISSUE THREAD

**Issue by kamitori** [laravel/framework#17233]
- Laravel Version: 4.2.*
- PHP Version: 5.6
- Database Driver & Version:

### Description:
I run php artisan, it's error " PHP Fatal error:  Call to a member function make() on null in /***/vendor/laravel/framework/src/Illuminate/Support/helpers.php on line 382
i try remove all file in vendor and re-composer, but it still error.
I try var_dump(app()) in function base_path, it's NULL

**Comment by GrahamCampbell** [comment]
Sorry, 4.2 is not supported.

**Comment by nicgordon** [comment]
@kamitori Did you ever figure this out?

**Comment by kamitori** [comment]
thanks, i fixed it.

2017-03-22 4:53 GMT+07:00 Nic Gordon <notifications@github.com>:
