### ISSUE TITLE
Cannot setPrimaryKey on BelongsToMany relationship

### ISSUE THREAD

**Issue by aleemb** [laravel/framework#17240]
- Laravel Version: 5.3.22

### Description:

Unable to setPrimaryKey for related models in `BelongToMany` etc.

### Steps To Reproduce:

In the following code, I would have expected the `primaryKey` to be used as set:

```
$comment = new \App\Models\Comment();
$comment = $comment->setKeyName('story_id');
$relation = $this->belongsToMany($comment, 'author_story', 'author_id', 'story_id', 'story_id');
```

However, the generated query doesn't use the `primaryKey` as defined and instead defaults to `id` which is the default `primaryKey`:

```
`comments`.*, `author_story`.`author_id` as `pivot_author_id`, `author_story`.`story_id` as `pivot_story_id` from `comments` inner join `author_story` on `comments`.`id` = `author_story`.`story_id` where `author_story`.`author_id` in ('4929', '4930')
```

The desired output is
```
`comments`.*, `author_story`.`author_id` as `pivot_author_id`, `author_story`.`story_id` as `pivot_story_id` from `comments` inner join `author_story` on `comments`.`story_id` = `author_story`.`story_id` where `author_story`.`author_id` in ('4929', '4930')
```

Basically `comments.id = author_story.story_id` should be `comments.story_id = author_story.story_id`.

A fix would be great, a proposed workaround would be welcome too.

**Comment by themsaid** [comment]
Can you please upgrade to `v5.3.29` and re-check?

**Comment by aleemb** [comment]
@themsaid Upgraded to `5.3.29`. Same issue.

**Comment by bozhkos** [comment]
@aleemb, can you show your `Comment` model source?

**Comment by aleemb** [comment]
@bozhkos

The result I am after is `user->withCount('comments')` which gets the counts across all of the user's stories. The query will work if I change the `primaryKey` class variable to `story_id` but not if the primary key is `id`.

`belongsToMany` does not allow changing the primary key, so before I call `belongsToMany` I want to change the primary key, setup the relationship (and later reset the primary key to the original).

The relationship is basically:

```
author: id, name
author_story: id, author_id, story_id
comments: id, story_id, content
```

So the join happens from author to author_story to comments. This avoid the `N+1` problem.

#### A vague guess

I suspect it has something to do with the behaviour in [Relation.php#L60](https://github.com/laravel/framework/blob/c43e7a6f6a9defe40046bc7601a494cfcc267e5d/src/Illuminate/Database/Eloquent/Relations/Relation.php#L60) which has

    public function __construct(Builder $query, Model $parent)
    {
        $this->query = $query;
        $this->parent = $parent;
        $this->related = $query->getModel();
        $this->addConstraints();
    }

where `$this->related` uses Query Builder as opposed to the `$parent` model.

The `setPrimaryKey` in my case will setup the primary key on the model instance (`$parent` above?):

```
$comment = new \App\Models\Comment(); // create instance
$comment = $comment->setKeyName('story_id'); // set primary key on instance

// the $comment model gets passed to relations.php constructor as Model $parent (2nd arg)
$relation = $this->belongsToMany($comment, 'author_story', 'author_id', 'story_id', 'story_id');
```

**Comment by Dylan-DPC** [comment]
@aleemb are you still having this issue? Can you try it out on 5.5 and report it?

**Comment by aleemb** [comment]
@Dylan-DPC not sure, the code is very different from what it was back then. I suppose you can close this. If the bug still exists, am pretty sure it will be reported again at some point.

**Comment by Dylan-DPC** [comment]
I can't close it. Since you are the creator of the issue you can do it as well :+1:

**Comment by bognix** [comment]
@aleemb I use laravel  version v5.5.13 and I'm still experiencing this issue.

The passed foreign key is ignored in belongsToMany relationship and the primary key from the model is used.

Here is my code setup:
User Model
```
user
  id: primaryKey
```
User Profile Model
```
user_profile
  id: primaryKey
  user_id: foreignKey
```
Role User Model
```
role_user
  user_id: foreignKey
  role_id: foreignKey
```

And this is how the relation inside `UserProfile.php` Model looks like:
```
public function roles() {
  return $this->belongsToMany('App\Models\Role', 'role_user', 'user_id', 'role_id');
}
```
instead of using foreign key `user_id` the primary key is taken.
I can fix that by adding `$this->primaryKey = 'user_id';` inside relation however base on the documentation it should work without this line (docs: https://laravel.com/docs/5.5/eloquent-relationships#many-to-many)

**Comment by 36864** [comment]
The third parameter of `belongsToMany()` is the foreign key on the pivot element, not the parent key.

https://laravel.com/api/5.5/Illuminate/Database/Eloquent/Relations/BelongsToMany.html#method___construct

Try this:
```
public function roles() {
  return $this->belongsToMany('App\Models\Role', 'role_user', 'user_id', 'role_id', 'user_id');
}
```

**Comment by bognix** [comment]
It still uses `id` from `UserProfile` instead of `user_id`

**Comment by hadi77makkawi** [comment]
@bognix  Same issue here, Laravel (5.5) totaly ignores the custom primary key for the 3rd table on belongstomany relation. And the only way to solve it is to add the below to the model which you are linking with:

protected $primaryKey = "YOUR_CUSTOM_PRIMARY_KEY";
public $incrementing = false;

But according to my app structure I can not change the primary key for the model but I need to customize it in the relationship :(

Any other workaround ?

**Comment by driesvints** [comment]
Think this is fixed by now. There's now a `$relatedKey` argument.
