### ISSUE TITLE
Event broadcasting not working on touched elements when using $touches variable in models

### ISSUE THREAD

**Issue by swinyx** [laravel/framework#17259]
- Laravel Version: 5.3
- PHP Version: 7
- Database Driver & Version:

### Description:

When implementing the functionality to update parent object timestamps using the $touches variable in models. It seems that Event broadcasting would not work on the object specified in the $touches array event though the timestamp change is reflected in the database. However Event broadcasting works when using the touch function directly on models.
( $post->touch(); will broadcast an event if specified in the boot() function )
(No event would be broadcasted for Posts if $comment is updated (with post added to the $touches variable in the Comment model))

Could it be possible to have it integrated so that when an object is updated via touches ( $touches), Event could be triggered on update ?

### Steps To Reproduce:
1) Create a model called Comment and another one called Post
where Comment belongsTo Post

2) Add the following to the Comment model     protected $touches = ['post'];

![screen shot 2017-01-10 at 5 45 28 pm](https://cloud.githubusercontent.com/assets/193893/21828089/9f44424a-d75c-11e6-80f7-dfc7513124d0.png)
![screen shot 2017-01-10 at 5 34 58 pm](https://cloud.githubusercontent.com/assets/193893/21828090/9f4a3704-d75c-11e6-9c63-7a8305b60cff.png)

3) Update the AppServiceProvider.php to broadcast an event if any Post is updated.

4) Configure Pusher to broadcast events

5) No event gets broadcasted for the touched objects (posts) when comments are added or updated

**Comment by morloderex** [comment]
Instead of looking at the touches property why don't you look on the updated event on the post model instead?

**Comment by Dylan-DPC** [comment]
@swinyx you an close this issue due to lack of activity (cc @themsaid )

**Comment by themsaid** [comment]
Thanks @Dylan-DPC the issue is inactive for a while now indeed.

**Comment by codefocus** [comment]
Why was this closed?
I would assume that adding a relation to the `$touches` array would cause model events to be broadcasted for the touched models.

This is especially an issue when relying on Eloquent model events for cache invalidation.

**Comment by devcircus** [comment]
Probably because the issue is two years old and the op stopped communicating. If you feel this is a big, open an issue with details and instructions on how to reproduce.
