### ISSUE TITLE
FatalThrowableError in HasEvents.php line 143

### ISSUE THREAD

**Issue by arthurkirkosa** [laravel/framework#17256]
- Laravel Version: 5.4.x-dev ee71fb2
- PHP Version: 7.1.0
- Database Driver & Version:

### Description:
```
FatalThrowableError in HasEvents.php line 143:
Call to undefined method Illuminate\Events\Dispatcher::until()
```

### Steps To Reproduce:
There is no `until` method in https://github.com/laravel/framework/blob/5.4/src/Illuminate/Events/Dispatcher.php

**Comment by themsaid** [comment]
It was put back later on :) thanks
