### ISSUE TITLE
Failed opening required swift_required.php in /vendor/composer/autoload_real.php on line 66

### ISSUE THREAD

**Issue by andrey-helldar** [laravel/framework#17261]
- Laravel Version: 5.3.29
- PHP Version: 7.0.8
- Database Driver & Version: _Not relevant_

### Description:

> $ composer update
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Nothing to install or update
> Generating autoload files
> > Illuminate\Foundation\ComposerScripts::postUpdate
> 
> Warning: Uncaught ErrorException: require(D:\OpenServer\domains\trans.dev\vendor\composer/../swiftmailer/swiftmailer/lib/swift_required.php): failed to open stream: No such file or directory in D:\OpenServer\domains\trans.dev\vendor\composer\autoload_real.php:66
> Stack trace:
> #0 D:\OpenServer\domains\trans.dev\vendor\composer\autoload_real.php(66): Composer\Util\ErrorHandler::handle(2, 'require(D:\\Open...', 'D:\\OpenServer\\d...', 66, Array)
> #1 D:\OpenServer\domains\trans.dev\vendor\composer\autoload_real.php(66): require()
> #2 D:\OpenServer\domains\trans.dev\vendor\composer\autoload_real.php(56): composerRequiref708c6e9603f4dc223ededc738105b42('2c102faa651ef8e...', 'D:\\OpenServer\\d...')
> #3 D:\OpenServer\domains\trans.dev\vendor\autoload.php(7): ComposerAutoloaderInitf708c6e9603f4dc223ededc738105b42::getLoader()
> #4 D:\OpenServer\domains\trans.dev\vendor\laravel\framework\src\Illuminate\Foundation\ComposerScripts.php(30): require_once('D:\\OpenServer\\d...')
> #5 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src in D:\OpenServer\domains\trans.dev\vendor\composer\autoload_real.php on line 66
> 
> Fatal error: composerRequiref708c6e9603f4dc223ededc738105b42(): Failed opening required 'D:\OpenServer\domains\trans.dev\vendor\composer/../swiftmailer/swiftmailer/lib/swift_required.php' (include_path='.;d:/openserver/modules/php/PHP-7-x64;d:/openserver/modules/php/PHP-7-x64/PEAR/pear') in D:\OpenServer\domains\trans.dev\vendor\composer\autoload_real.php on line 66

### Steps To Reproduce:
`composer create-project --prefer-dist laravel/laravel trans.dev`
or
`composer update`

**Comment by andrey-helldar** [comment]
In vagrant too:

> vagrant@homestead:~/Code/trans.dev$ composer update
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Nothing to install or update
> Generating autoload files
> > Illuminate\Foundation\ComposerScripts::postUpdate
> PHP Warning:  Uncaught ErrorException: require(/home/vagrant/Code/trans.dev/vendor/composer/../swiftmailer/swiftmailer/lib/swift_required.php): failed to open stream: No such file or directory in /home/vagrant/Code/trans.dev/vendor/composer/autoload_real.php:66
> Stack trace:
> #0 /home/vagrant/Code/trans.dev/vendor/composer/autoload_real.php(66): Composer\Util\ErrorHandler::handle(2, 'require(/home/v...', '/home/vagrant/C...', 66, Array)
> #1 /home/vagrant/Code/trans.dev/vendor/composer/autoload_real.php(66): require()
> #2 /home/vagrant/Code/trans.dev/vendor/composer/autoload_real.php(56): composerRequiref708c6e9603f4dc223ededc738105b42('2c102faa651ef8e...', '/home/vagrant/C...')
> #3 /home/vagrant/Code/trans.dev/vendor/autoload.php(7): ComposerAutoloaderInitf708c6e9603f4dc223ededc738105b42::getLoader()
> #4 /home/vagrant/Code/trans.dev/vendor/laravel/framework/src/Illuminate/Foundation/ComposerScripts.php(30): require_once('/home/vagrant/C...')
> #5 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(277): in /home/vagrant/Code/trans.dev/vendor/composer/autoload_real.php on line 66
> 
> Warning: Uncaught ErrorException: require(/home/vagrant/Code/trans.dev/vendor/composer/../swiftmailer/swiftmailer/lib/swift_required.php): failed to open stream: No such file or directory in /home/vagrant/Code/trans.dev/vendor/composer/autoload_real.php:66
> Stack trace:
> #0 /home/vagrant/Code/trans.dev/vendor/composer/autoload_real.php(66): Composer\Util\ErrorHandler::handle(2, 'require(/home/v...', '/home/vagrant/C...', 66, Array)
> #1 /home/vagrant/Code/trans.dev/vendor/composer/autoload_real.php(66): require()
> #2 /home/vagrant/Code/trans.dev/vendor/composer/autoload_real.php(56): composerRequiref708c6e9603f4dc223ededc738105b42('2c102faa651ef8e...', '/home/vagrant/C...')
> #3 /home/vagrant/Code/trans.dev/vendor/autoload.php(7): ComposerAutoloaderInitf708c6e9603f4dc223ededc738105b42::getLoader()
> #4 /home/vagrant/Code/trans.dev/vendor/laravel/framework/src/Illuminate/Foundation/ComposerScripts.php(30): require_once('/home/vagrant/C...')
> #5 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(277): in /home/vagrant/Code/trans.dev/vendor/composer/autoload_real.php on line 66
PHP Fatal error:  composerRequiref708c6e9603f4dc223ededc738105b42(): Failed opening required '/home/vagrant/Code/trans.dev/vendor/composer/../swiftmailer/swiftmailer/lib/swift_required.php' (include_path='.:/usr/share/php') in /home/vagrant/Code/trans.dev/vendor/composer/autoload_real.php on line 66
> 
> Fatal error: composerRequiref708c6e9603f4dc223ededc738105b42(): Failed opening required '/home/vagrant/Code/trans.dev/vendor/composer/../swiftmailer/swiftmailer/lib/swift_required.php' (include_path='.:/usr/share/php') in /home/vagrant/Code/trans.dev/vendor/composer/autoload_real.php on line 66

**Comment by andrey-helldar** [comment]
Folder `~/Code/trans.dev/vendor/swiftmailer/swiftmailer/` is empty.

**Comment by andrey-helldar** [comment]
Today, January 12, the problem disappeared.
Yesterday, this problem was not only "clean" applications, but also on the projects already running the command `composer update`.

**Comment by celorodovalho** [comment]
@andrey-helldar could solve it?

**Comment by andrey-helldar** [comment]
@celorodovalho, I did not find the reason. The problem disappeared on its own and no longer appeared.
