### ISSUE TITLE
if the type of JSON value is INT, then params binding will fail

### ISSUE THREAD

**Issue by huoding** [laravel/framework#17262]
- Laravel Version: 5.2.39
- PHP Version: 7.0.11
- Database Driver & Version: mysql 5.7

### Description:
if the type of JSON value is INT, then params binding will fail

### Steps To Reproduce:
`\DB::table('articles')->where('id', 1)->update(['data1->aaa' => 111]);`

###  Result:
`at Connection->runQueryCallback('update `articles` set `data1` = json_set(`data1`, "$.aaa", 111) where `id` = ?', array('111', '1'), object(Closure)) in Connection.php line 669`

FAIL: 'where id = ?', array('111', '1') // **ONE ?, TWO params**

**Comment by huoding** [comment]
OK?

`
    public function prepareBindingsForUpdate(array $bindings, array $values)
    {
        $index = 0;

        foreach ($values as $column => $value) {
            if ($this->isJsonSelector($column) && is_bool($value) **&& is_int($value)** ) {
                unset($bindings[$index]);
            }

            $index++;
        }

        return $bindings;
    }
`

**Comment by huoding** [comment]
`
public function prepareBindingsForUpdate(array $bindings, array $values)
{
    $index = 0;

    foreach ($values as $column => $value) {
        if ($this->isJsonSelector($column) && is_bool($value)) {
            unset($bindings[$index]);
        }

        $index++;
    }

    return $bindings;
}
`

**Comment by srmklive** [comment]
Does the same issue happens in 5.3 too?

**Comment by themsaid** [comment]
I think this was fixed in 5.3, I can't find the PR though.
