### ISSUE TITLE
Can't redirect to named routes with an optional paramer using other different parameters

### ISSUE THREAD

**Issue by TeRMiNaTe** [laravel/framework#17263]
If i have a route such as:  
```
Route::get('feedback/{department?}', array('as' => 'feedback', 'uses' => 'SomeController@handleFedback'));
```
This redirect will not work:  
```
return redirect()->route('feedback, [
	'related_order_id' => $order->id
]);
```
It redirects to `/feedback/{order_id}` instead of `/feedback?related_order_id={order_id}`  
Shouldn't I be able to redirect to the route with different GET variables without having to specify the optional parameter?

**Comment by stuartmccord** [comment]
I think the order is what matters, so try this

`return redirect()->route('feedback', [
	'department' => null,
	'related_order_id' => $order->id
]);`

think it should get what you are after but its a bit ugly
