### ISSUE TITLE
X-XSRF-TOKEN cookie expiration configuration

### ISSUE THREAD

**Issue by kslimani** [laravel/framework#17267]
- Laravel Version: 5.3.29
- PHP Version: not relevant
- Database Driver & Version: not relevant

### Description:

Hello,

In the  `Illuminate\Foundation\Http\Middleware\VerifyCsrfToken` middleware, the `X-XSRF-TOKEN` cookie expiration [is calculated using of session 'lifetime' configuration key](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php#L138).

But if we set `expire_on_close` session configuration key to ~~false~~ true, then the Laravel session cookie become "Browser Session" and expire as soon as browser is closed.

Do you think it would be a nice enchancement to also check `expire_on_close` session configuration key to also set `X-XSRF-TOKEN` expiration to "Browser session" ? (_to match with session cookie expiration_) Or does it introduce a security issue ?

**Comment by GrahamCampbell** [comment]
Please ask on the forums. :)
