### ISSUE TITLE
[REQUEST] Add URL/CLI Path to Logging by Default

### ISSUE THREAD

**Issue by agentfour** [laravel/framework#17279]
- Laravel Version: 5.3.0
- PHP Version: 5.3
- Database Driver & Version: -

### Description:
When having to dig through the logs, and seeing random errors being thrown (which isn't nice, but hey, it happens), it is currently not so straight-forward to reproduce the steps an end-user took to create that error.

That's why I think it would be phenomenally useful to have at the very start of any log entry the "Executable Command" that was used to generate that error, be it a FQDN, IP, CLI Command etc.

I hope this suggestion makes sense and thanks for the awesome work!

**Comment by sisve** [comment]
Laravel uses Monolog, and Monolog can do anything [related to logging]. This includes formatting of the log files. Have you found an actual bug in [this part of the system](https://laravel.com/docs/5.3/errors#custom-monolog-configuration), or is this a feature request?

**Comment by agentfour** [comment]
It's absolutely a feature request, sorry I wasn't clear on that..

Thanks for that, but just figured it might be nice to have that out of the box along with the stack-trace without having to make a custom tweak to the logging.
