### ISSUE TITLE
Migration issue

### ISSUE THREAD

**Issue by philmeadows** [laravel/framework#17270]
- Laravel Version: 5.2.22
- PHP Version: 5.5.34
- Database Driver & Version: MySQL 5.6.34

### Description:
Noticed some, not all, foreign keys NOT being added when viewing DB in phpMyAdmin
Eventually noticed some tables had been allocated more than 1 primary key!
Consequently, this makes relationships freak out

### Steps To Reproduce:
Issue only occurs when migration file contains a "text" field i.e. "$table->text('foo');"

**Comment by philmeadows** [comment]
![migration-issue-1](https://cloud.githubusercontent.com/assets/7361067/21855962/207bdc04-d818-11e6-9f96-455f62116ad2.jpg)

![migration-issue-2](https://cloud.githubusercontent.com/assets/7361067/21855975/2917e484-d818-11e6-8de1-725a4c139d7f.jpg)

**Comment by themsaid** [comment]
Sorry but 5.2 is not supported anymore, please upgrade to 5.3 and re-check.

**Comment by philmeadows** [comment]
Thanks
