### ISSUE TITLE
Index remains after foreign key deletion using migrate:rollback

### ISSUE THREAD

**Issue by chimit** [laravel/framework#17287]
- Laravel Version: 5.3
- PHP Version: 7.0
- Database Driver & Version:

### Description:

I have a migration which adds a foreign key in MySQL table:

```php
public function up()
{
    Schema::table('client_permission', function (Blueprint $table) {
        $table->foreign('client_id')->references('id')->on('clients')->onDelete('cascade');
    });
}

public function down()
{
    Schema::table('client_permission', function (Blueprint $table) {
        $table->dropForeign(['client_id']);
    });
}
```

After I run this migration I get a foreign key:

![2017-01-12 16 24 22](https://cloud.githubusercontent.com/assets/839349/21882190/51382ccc-d8e4-11e6-9c31-4b5af10feeaa.png)

If I rollback this migration the foreign key is removed but the index still remains:

![2017-01-12 16 24 52](https://cloud.githubusercontent.com/assets/839349/21882210/73c428f4-d8e4-11e6-93fa-83c1dc62bbed.png)

Is it a bug?

Another example:

```php
public function up()
{
    Schema::create('client_product', function (Blueprint $table) {
        $table->integer('client_id')->unsigned();
        $table->foreign('client_id')->references('id')->on('clients')->onDelete('cascade');

        $table->integer('product_id')->unsigned();
        $table->foreign('product_id')->references('id')->on('products')->onDelete('cascade');
        $table->timestamps();

        $table->unique(['client_id', 'product_id']);
    });
}
```

Result:

![mysql workbench 2017-01-12 16-59-41](https://cloud.githubusercontent.com/assets/839349/21883139/a3c714ae-d8e8-11e6-84a4-d2e88d708f6b.png)

One unwanted index `client_product_product_id_foreign`. If the foreign key creation also creates an index where is the second index `client_product_client_id_foreign`?

**Comment by fernandobandeira** [comment]
For your first example I think we could delete the index...

Four your second example, it's normal behavior of Mysql, from the docs:

> index_name represents a foreign key ID. The index_name value is ignored if there is already an explicitly defined index on the child table that can support the foreign key. Otherwise, MySQL implicitly creates a foreign key index

http://dev.mysql.com/doc/refman/5.7/en/create-table-foreign-keys.html

So actually it creates the index just if it's needed, if it isn't necessary it won't create one, this explains why it didn't create the index for ``` client_product_client_id_foreign ```.
