### ISSUE TITLE
[5.3] Callbacks not being made serializable in Illuminate\Mail\Mailable Class

### ISSUE THREAD

**Issue by rishi-ramawat** [laravel/framework#17283]
- Laravel Version: 5.3.22
- PHP Version: 7.0.8
- Database Driver & Version: MariaDB 10.1.18

### Description:
I am trying to use the `withSwiftMessage()` function of the `Illuminate\Mail\Mailable` class to add some headers to the mail message before queuing the mail. But, the process fails with the error:
`local.ERROR: Exception: Serialization of 'Closure' is not allowed in /data/vendor/laravel/framework/src/Illuminate/Queue/Queue.php:86`

### Steps To Reproduce:
```php
$order = Order::findOrFail($orderId);
// Ship order...
$mail = (new OrderShipped($order))
             ->onConnection('emails')
             ->onQueue('emails');

$mail->withSwiftMessage(function ($message)  {
    // some logic here
});
Mail::to($to)->queue($mail);
```
This fails with the following error:
```php
[2017-01-12 05:31:16] local.ERROR: Exception: Serialization of 'Closure' is not allowed in /data/vendor/laravel/framework/src/Illuminate/Queue/Queue.php:86
Stack trace:
#0 /data/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(86): serialize(Object(Illuminate\Mail\SendQueuedMailable))
#1 /data/vendor/laravel/framework/src/Illuminate/Queue/RedisQueue.php(202): Illuminate\Queue\Queue->createPayload(Object(Illuminate\Mail\SendQueuedMailable), '')
#2 /data/vendor/laravel/framework/src/Illuminate/Queue/RedisQueue.php(82): Illuminate\Queue\RedisQueue->createPayload(Object(Illuminate\Mail\SendQueuedMailable), '')
#3 /data/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(37): Illuminate\Queue\RedisQueue->push(Object(Illuminate\Mail\SendQueuedMailable), '', 'emails')
#4 /data/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(136): Illuminate\Queue\Queue->pushOn('emails', Object(Illuminate\Mail\SendQueuedMailable))
```

### Fix:
In the function `withSwiftMessage()` of `Illuminate\Mail\Mailable` class the following can be done to fix it:
```php
/**
 * Register a callback to be called with the Swift message instance.
 *
 * @param  callable  $callback
 * @return $this
 */
 public function withSwiftMessage($callback)
 {
     $this->callbacks[] = new SerializableClosure($callback);

     return $this;
 }
```

**Comment by rishi-ramawat** [comment]
@taylorotwell Why was my PR [#17824](https://github.com/laravel/framework/pull/17284) closed?
You should have at-least left some close comments.

**Comment by guysmilez** [comment]
Unfortunately @rishi-ramawat it appears that the `SerializableClosure` is no longer supported in the latest version of Laravel.

My problem is similar: I'd like to take advantage of queued messages, but to do so, I need to create `Mailable` objects. This is fine, except that I'd also like to add various headers to outgoing emails, _per email_, but since we cannot serialize closures (via the `withSwiftMessage()` method), then I am left to only affect the outgoing message from the event that is fired right before the message is actually sent (via `Illuminate\Mail\Events\MessageSending`). However, this gives me a `Swift_Message` object via the event, and I don't have a reference to the original `Mailable` any longer to get the data I need for my custom headers.

Any thoughts or recommendations here, without using a custom `Mailer` service? Any solutions on your end?

**Comment by rishi-ramawat** [comment]
Hello @guysmilez 
On **Laravel 5.4**, I pulled in `SerializableClosure` class and related functionalities from packagist via composer using the following command
```shell
composer require jeremeamia/superclosure
``` 
Then I created my own `CustomMailable` Class something like this:
```php
namespace App\Mail;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;
use SuperClosure\SerializableClosure;

abstract class CustomMailable extends Mailable implements ShouldQueue
{
    use Queueable, SerializesModels;
   
    /**
     * Fixes a laravel bug. (#17823 on laravel/framework)
     * Makes all the callbacks serializable.
     *
     * @return $this
     */
    public function makeCallbacksSerializable()
    {
        $callbacks = [];
        foreach ($this->callbacks as $callback) {
            if (!($callback instanceof SerializableClosure)) {
                $callback = new SerializableClosure($callback);
            }
            $callbacks[] = $callback;
        }
        $this->callbacks = $callbacks;
        return $this;
    }
}
```
with the function `makeCallbacksSerializable()` which you can also find in my PR [#17824](https://github.com/laravel/framework/pull/17284) and made all my `Mailable` classes to extend this `CustomMailable` class instead.
Then I call the `makeCallbacksSerializable()` function just before queuing the mail.

**Comment by guysmilez** [comment]
@rishi-ramawat though not solving the underlying problem of serializing a closure, one could just extend the `Mailable` class and override the `send()` method to execute any desired functionality through a protected or private class method. That's the route I went: serialize the `Mailable` class for queuing, then when the `send()` method is called by the job handler, have it execute an additional method on my extended `Mailable` class to add the headers that I was looking to add to the `Swift_Message`.

Thanks for the idea, I'll keep this one in my back pocket as well.

**Comment by themsaid** [comment]
Closing as no-fix.
