### ISSUE TITLE
firstOrNew/firstOrCreate not working with json data type.

### ISSUE THREAD

**Issue by John-Ciuchea** [laravel/framework#17282]
- Laravel Version: 5.3.28
- PHP Version: 7.1.0
- Database Driver & Version: mysql 5.7.11

### Description:
firstOrNew/firstOrCreate not working on tables containing json data type fields.

### Steps To Reproduce:
Migration:
```php
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class Test extends Migration
{
    public function up()
    {
        Schema::create('tests', function (Blueprint $table) {
            $table->increments('id');
            $table->char('title', 50);
            $table->json('lines')->nullable();
        });
    }
    public function down()
    {
        Schema::drop('tests');
    }
}
```
Model:
```php
namespace App;

use Illuminate\Database\Eloquent\Model;
class Test extends Model
{
    public $timestamps = false;
    protected $casts = [
        'lines' => 'array',
    ];
}
```
Seeder:
```php
use Illuminate\Database\Seeder;

class TestTableSeeder extends Seeder
{
    public function run()
    {
        \App\Test::firstOrCreate([
            'title' => 'title',
            'lines' => ['line1', 'line2'],
        ]);
    }
}
```

Running `TestTableSeeder` multiple times will produce duplicates.

**Comment by Mircea-Ciuchea** [comment]
Looks like the problem goes down to `where` method that is not able to search json.

**Comment by simonhamp** [comment]
If you've got data that could be used for uniquely identifying rows, it would probably be better placing that either in its own columns (for better indexing and faster searching) or in its own table and forming a relationship between your models.

I know this is more traditional perspective on your data structure, but the MySQL JSON column is pretty new, so if it's critical, it's probably best to just use it for storage and retrieval instead of row identification at this point in time.

**Comment by Mircea-Ciuchea** [comment]
It's not about my data structure, it's about this methods that doesn't work as expected when we have a json field. 
I know I should write some tests and create a pull request to report a bug but I'm not familiar with database testing (I know that laravel makes it easy) and I didn't have much time.

**Comment by huuuk** [comment]
Do you propose leave this issue unresolved?

**Comment by andrewmclagan** [comment]
Closed without a resolution?

**Comment by John-Ciuchea** [comment]
@andrewmclagan I closed this issue because not many people seem to be bother by this. I changed my data structure to avoid this issue. Feel free to reopen this is you consider that is relevant.

**Comment by duongtdvn** [comment]
I am facing the same issue like this and would like to know if anyone got this problem solved?

**Comment by chaicai333** [comment]
im facing this issue as well pls reopen this

**Comment by akkivaghasiya5** [comment]
im facing this issue as well pls reopen this

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.

Thanks!

**Comment by davidlomidze** [comment]
@ThaDaVos I think I found a better solution for your example (when json field property has a simple value but not array or object as in the initial example of @John-Ciuchea)

`Something::firstOrCreate(
            [ 
                'some_identifier' => 'XXX', 
                'some_json->a' => 1
            ],
            [
                'some_json' => [
                    'a' => 1
                ]
            ]
        );`

Tested on Laravel Version 8.x

Unfortunately the same example with array as a value doesn't seem to be working

`Something::firstOrCreate(
            [
                'some_identifier' => 'XXX',
                'some_json->a' => ['line1', 'line2']
            ],
            [
                'some_json' => [
                    'a' => ['line1', 'line2']
                ]
            ]
        );`

**Comment by abkrim** [comment]
Same for me.

- I've create a test for some action. 
- On this create a factory Model
- On class and method for test I needs use a Model::where for get model and after update json column, and after save,

## Below not work
```php
private function saveValidation(string $email, array $validation): bool
    {
        $subscriber = Subscriber::firstOrCreate(
            ['email' => $email],
            ['validation' => $validation]  
        );    

        dd($subscriber);

        return true;
    }
```

dd dump ->
```
"id" => "1"
    "email" => "fenzen@gmail.com"
    "name" => "Ángela Rincón"
    "extra_data" => null
    "status" => "2"
    "verified_at" => "2022-01-29 08:15:31"
    "created_at" => "2022-01-29 08:15:31"
    "updated_at" => "2022-01-29 08:15:31"
    "is_faker" => "0"
     "validation" => null  //wrong
```

## This work

```php
private function saveValidation(string $email, array $validation): bool
{
    $subscriber = Subscriber::where(
        ['email' => $email],
    );

    $subscriber->validation = $validation;
    $subscriber->save();

    dd($subscriber);

    return true;
}
```php
"id" => 1
  "email" => "fenzen@gmail.com"
  "name" => "Gael Ruiz"
  "extra_data" => null
  "status" => "2"
  "verified_at" => "2022-01-29T08:17:13.000000Z"
  "created_at" => "2022-01-29T08:17:13.000000Z"
  "updated_at" => "2022-01-29T08:17:14.000000Z"
  "is_faker" => "0"
  "validation" => array:12 [▼
    "email" => "fenzen@gmail.com"
    "verdict" => "Valid"
    "score" => 0.71214,0
    "local" => "fenzen"
    "host" => "gmail.com"
    "checks__domain__has_valid_address_syntax" => null
    "checks__domain__has_mx_or_a_record" => null
    "checks__domain__has_is_suspected_disposable_address" => null
    "checks__local_part__is_suspected_role_address" => null
    "checks__additional__has_known_bounces" => null
    "checks__additional__has_suspected_bounces" => null
    "ip_address" => "92.59.240.169"
  ]
]
```

**Comment by JexPY** [comment]
Why is this issue closed?

Have the same issue "firstOrCreate" is not able to detect array object and creates a new entry.

**Comment by ArthurYdalgo** [comment]
> @ThaDaVos I think I found a better solution for your example (when json field property has a simple value but not array or object as in the initial example of @John-Ciuchea)
> 
> ```
> Something::firstOrCreate(
>     [
>         'some_identifier' => 'XXX',
>         'some_json->a' => 1
>     ],
>     [
>         'some_json' => [
>             'a' => 1
>         ]
>     ]
> );
> ```
> 
> Tested on Laravel Version 8.x
> 
> Unfortunately the same example with array as a value doesn't seem to be working
> 
> ```
> Something::firstOrCreate(
>     [
>         'some_identifier' => 'XXX',
>         'some_json->a' => ['line1', 'line2']
>     ],
>     [
>         'some_json' => [
>             'a' => ['line1', 'line2']
>         ]
>     ]
> );
> ```

This was really helpfull, and it worked. You mentioned that "Unfortunately the same example with array as a value doesn't seem to be working", but actually you'd have to recursively do the same "arrowing" (sorry if this is not a verb) for the the inner values.

To do so, you can create another App\Helpers\Arr class that extends the [Illuminate\Support\Arr](https://laravel.com/docs/9.x/helpers#method-array-dot)
```
<?php

namespace App\Helpers;

use Illuminate\Support\Arr as SupportArr;

class Arr extends SupportArr{
    /**
     * Flatten a multi-dimensional associative array with a separator.
     *
     * @param  iterable  $array
     * @param  string  $separator
     * @param  string  $prepend
     * @return array
     */
    public static function flattenWith($array, $separator , $prepend = '')
    {
        $results = [];

        foreach ($array as $key => $value) {
            if (is_array($value) && ! empty($value)) {
                $results = array_merge($results, static::flattenWith($value, $separator ,$prepend.$key.$separator));
            } else {
                $results[$prepend.$key] = $value;
            }
        }

        return $results;
    }

    /**
     * Flatten a multi-dimensional associative array with an arrow separator.
     *
     * @param  iterable  $array
     * @param  string  $prepend
     * @return array
     */
    public static function arrow($array , $prepend = '')
    {
        return self::flattenWith($array, '->', $prepend);
    }
}
```

then, do:

```

     use App\Helpers\Arr;

     ...

     $metadata = [
          'foo' => 'bar',
          'other_foo' => [
              'dummy' => 'data',
              "another_foo" => [
                  "luke" => "skywalker"
              ]
          ]
      ];

      $arrowed_metadata =  Arr::arrow(compact('metadata'));

      return Something::firstOrCreate(array_merge([
          'some_identifier' => 'XXX',
      ], $arrowed_metadata), compact('metadata'));
```

make sure you sent the original "unarrowed" metadata as the second argument of the "firstOrCreate" method, or the json field will not be set.

**Comment by ArthurYdalgo** [comment]
> Why is this issue closed?
> 
> Have the same issue "firstOrCreate" is not able to detect array object and creates a new entry.
> 
> Here I want to check if keyword has already been created:
> 
> ```
>   public function store($data)
>   {
>       return Keywords::firstOrCreate(
>           [
>               'name' => $data['name'],
>           ],
>           [
>               'created_by' => $data['created_by'],
>           ]
>       );
>   }
> ```
> 
> ```
> //$data looks like this
> array:3 [
>   "name" => array:2 [
>     "en" => "Italian Pizza 6"
>     "de" => "Italienische Pizza 6"
>   ]
>   "created_by" => 1
> ]
> ```
> 
> **Workaround for me looks like this:**
> 
> ```
>   public function store($data)
>   {
>       $query = Keywords::query();
> 
>       return ($query->where('name->en', $data['name']['en'])
>       ->orWhere('name->de', $data['name']['de'])->first()) ?? $query->create($data);
>   }
> ```

Hello, @JexPY . In case you're still interested in the sollution and want to check mine, [here is the link](https://github.com/laravel/framework/issues/17282#issuecomment-1152354198)

**Comment by krunal202** [comment]
Same issue, it will be really helpful if you can reopen it.

**Comment by Paxton0222** [comment]
same issue
