### ISSUE TITLE
make::migration:pivot   fails for complex names

### ISSUE THREAD

**Issue by cs-abdulwahab** [laravel/framework#17291]
- Laravel Version: 5.3.#
- PHP Version:
- Database Driver & Version:

### Description:
error found when trying to migrate 
make:migration:pivot table1 table2 
following error pops up
![lara migrate](https://cloud.githubusercontent.com/assets/5089848/21887615/6f2d5902-d8e2-11e6-9372-675668565eda.png)

however when you run the same command for simpler model names  mostly singular  it works fine 

### Steps To Reproduce:
Create a table 1 with complexName  e.g  SkillsDomain  and table2  with  let say  SoftwareHouse
it will migrations with  the name of  skill_domains and software_houses 

now try to run make:migration:pivot  
and error appears that class not found

![lara migrate](https://cloud.githubusercontent.com/assets/5089848/21887588/58b6b614-d8e2-11e6-862e-fee6a2818b63.png)

**Comment by themsaid** [comment]
There's no such command `make:migration:pivot`, please refer to the package you use that adds this command .
