### ISSUE TITLE
Grammar@getChangedDiff returns false when changing enum options

### ISSUE THREAD

**Issue by marktopper** [laravel/framework#17305]
- Laravel Version: 5.3.29
- PHP Version: 7.0.12
- Database Driver & Version: MySQL

### Description:
Changing values of a `enum` column, does not seem to actually view as a change in `Illuminate\Database\Schema\Grammars\Grammar@getChangedDiff`.
So it will turn up as there was no changes in the column, meaning that I can not use my custom added type for handing `enum`, since the Grammar believes there are no changes.

### Steps To Reproduce:
Add the following migration file:
```
public function up()
{
    Schema::create('products', function (Blueprint $table) {
        $table->increments('id');

        $table->enum('status', ['AVAILABLE', 'SOLD_OUT']);

        $table->timestamps();
    });

    Schema::table('products', function (Blueprint $table) {
        $table->enum('status', ['FOO', 'BAR'])->change();
    });
}
```

**Comment by srmklive** [comment]
You can't directly edit the `enum` column. Laravel uses `Doctrine/DBAL` which doesn't allow modification of `enum` column types. Laravel explicity mentions this in the documentation as well [here](https://laravel.com/docs/5.3/migrations#modifying-columns)

**Comment by marktopper** [comment]
I have added my own type to `Doctrine\DBAL`.

> So it will turn up as there was no changes in the column, meaning that I can not use my custom added type for handing `enum`, since the Grammar believes there are no changes.

**Comment by marktopper** [comment]
I however managed to fix this. You can see the package I created: https://github.com/larapack/doctrine-support

/closing since this might not ever be supported by the Laravel core

**Comment by srmklive** [comment]
@marktopper  If you can come up with a way to have it merged into Laravel core that will be awesome 👍 .

**Comment by marktopper** [comment]
I'm not sure that Laravel wish to do that. It might be waste of time to build a RP.

But I can of cause give it a try, and also make some pulls to Doctrine.

However for now you can always use the package, since it adds the support.

**Comment by srmklive** [comment]
For Doctrine i did that. But it wasn't included. doctrine/dbal#2304
