### ISSUE TITLE
Illuminate\Foundation\Testing\Concerns\MakesHttpRequests::decodeResponseJson() phpDoc is wrong

### ISSUE THREAD

**Issue by miklcct** [laravel/framework#17310]
Apart from array, the titled method can return other types such as int, string, bool etc., if the returned JSON from the request is not an array or object, for example, the literals false, true, 0, etc., themselves are all valid JSON documents.

Therefore, the @return type should be changed to mixed.

**Comment by GrahamCampbell** [comment]
Please send a PR.
