### ISSUE TITLE
Method whereDate does not exist.

### ISSUE THREAD

**Issue by ThunderBirdsX3** [laravel/framework#17311]
- Laravel Version: 5.3.29
- PHP Version: 7.0.10
- Database Driver & Version: MySQL 5.7.14

### Description:
I got an error ,When i try to use whereDate in my view page.

>  1/2 BadMethodCallException in Macroable.php line 74: Method whereDate does not exist. 
>  2/2 ErrorException in Macroable.php line 74: Method whereDate does not exist. (View: C:\wamp\www\2_Work\dashboard\resources\views\pdf\user.blade.php) 

My model relationship is work, But why i can't use whereDate function.

```
@extends('layouts.pdf')

@section('content')
  <table border="1" cellspacing="0" cellpadding="0" width="545">
    <tr>
      <th>ชื่อผู้ใช้งาน</th>
      <th>เข้าใช้ล่าสุด</th>
      <th>จำนวนการเข้าใช้งานใน 7 วัน</th>
      <th>จำนวนงานที่ทำในวันที่ 13/01/2560</th>
    </tr>
    @foreach ($users as $user)
      <tr>
        <td><span class="td-text">{{$user->user_detail}}</span></td>
        <td align="center">{{$user->ual->first()->created_at ?? NULL}}</td>
        <td align="center">{{$user->ual->where('created_at', '>=', '(CURDATE() - INTERVAL 7 DAY)')->count()}}</td>
        <td align="left"><?php var_dump( $user->dataDetail->whereDate('created_at', '2017-01-13')->toArray() ); ?></td>
      </tr>
    @endforeach
  </table>
@endsection
```
And i try another query builder in my view page is not work, Or it's can't use in view page.
I can use only where. And I try `where('Date(created_at)', '2017-01-13')` or `where('Date(created_at)', 'LIKE', '2017-01-13%')` . It not work.

**Comment by bozhkos** [comment]
@ThunderBirdsX3 try this one.
` $user->dataDetail()->whereDate('created_at', '2017-01-13')->toArray()`

**Comment by chrismotari** [comment]
Am now getting  Method Illuminate\Database\Eloquent\Collection::dataDetail does not exist
