### ISSUE TITLE
The "get()" function when fetchAll() returns string instead of numeric values

### ISSUE THREAD

**Issue by FranLara** [laravel/framework#17321]
- Laravel Version: 5.2.45
- PHP Version: 7.0.11
- Database Driver & Version: mysql 5.0.12-dev

### Description:
In the lines 346, 347 and 348 of \Illuminate\Database\Connection the functions "fetchAll" sometimes return the type of the value properly (float when is a float or int when is a integer) but sometimes return a string instead of the type that should be (string instead of float or string instead of integer).

### Steps To Reproduce:
I can't send exactly how reproduce it, but I can copy the "queries" that behave like that:

1.- The query with a normal behaviour:

`$list = DB::table("transactions")->select("transactions.project_id as ".self::COLUMN_ID)->addSelect("projects.name as ".self::COLUMN_NAME)->addSelect(DB::raw("(round(sum((if(transactions.status in ('validated','received'), ". "transactions.commission, 0) / currencies.rate)))/100) as ".self::COLUMN_COMMISSION))->addSelect(DB::raw("(round(sum(transactions.commission / currencies.rate))/100)  as ". self::COLUMN_TOTAL_COMMISSION))->join("currencies", "currencies.short_name", "=", "transactions.currency")->join("projects", "projects.id", "=", "transactions.project_id")->where("transactions.merchant_id", $params["filter"]["merchant_id"])->whereBetween("transactions.transaction_date", [$startDate, $endDate])->groupBy("transactions.project_id")->orderBy(self::COLUMN_COMMISSION, 'desc')->get();`

2.- The query with strings instead of numeric values:

`$list = DB::table("project_merchant_clicks_per_day")->select("project_merchant_clicks_per_day.id as " . self::COLUMN_ID)->addSelect("projects.name as ".self::COLUMN_NAME)->addSelect(DB::raw("CAST(SUM(project_merchant_clicks_per_day.click_count) AS UNSIGNED) as ". self::COLUMN_TOTAL))->addSelect(DB::raw("SUM(project_merchant_clicks_per_day.click_count) / 142  AS ".self::COLUMN_CLICKS))->join("projects", "projects.id", "=", "project_merchant_clicks_per_day.project_id")->where("project_merchant_clicks_per_day.id", $request->getFilter()["id"])->whereBetween("project_merchant_clicks_per_day.date", [$startDate, $endDate])->groupBy("project_merchant_clicks_per_day.project_id")->orderBy(self::COLUMN_CLICKS, 'desc')->get();`

As you can see in the code, the queries are quite similar but:

- In the first one: the result is an array of objects and the variables "self::COLUMN_COMMISSION" and "self::COLUMN_TOTAL_COMMISSION" have float values. e.g. 
`stdClass Object
(
    [id] => 198
    [name] => "company name"
    [commission] => 78.5
    [total_commission] => 552.82
)`
 
- However, in the second one: the result is an array of objects (as well), but the value of the variable "self::COLUMN_CLICKS" is a decimal value casted to string. e.g.
`stdClass Object
(
    [id] => 155
    [name] => "company name"
    [total_clicks] => 785
    [clicks_day] => "5.5282"
)
`

**Comment by themsaid** [comment]
Please test on 5.3 since 5.2 is not longer supported.

**Comment by themsaid** [comment]
Also please try to simplify the steps to reproduce in order for us to be able to test it on a fresh application.
