### ISSUE TITLE
[Issue] Factory Seeder throws Integrity constraint violation

### ISSUE THREAD

**Issue by penteleq** [laravel/framework#17342]
- Laravel Version: 5.3
- PHP Version: 5.6
- Database Driver & Version: MySQL

### Description:
I'm using database with transactions for data seeder. Even though I have some data in database (was performing stress tests) and using seeder it throws me duplicate entry SQLSTATE[23000]: event though I'm creating new object it seems that it's being loaded.

### Reproduce:
Add few rows to users table, replicate like this:

```
$result = factory(App\User::class, 2)->create()
                    ->each(function ($u) {
                        dd($u->id);
                    });
```
will display next autoincrement value

```
$result = factory(App\User::class, 1)->create()
                    ->each(function ($u) {
                        dd($u->id);
                    });
```
will display first row's ID

**Comment by srmklive** [comment]
Can you provide more explanation to the issue you are facing?

**Comment by themsaid** [comment]
duplicate entry errors is caused by how you built the user fake and how your unique keys are configured, please take a deeper look at how the fake is defined and continue the discussion in the forums since this is not a bug with the framework.
