### ISSUE TITLE
Unique validation rule is bypassed when submitting multiple requests.

### ISSUE THREAD

**Issue by rdok-linkwise** [laravel/framework#17370]
- Laravel Version: 5.1 LTS
- PHP Version: 5.5.9
- Database Driver & Version: mysql  14.14 Distrib 5.5.50, for debian-linux-gnu (x86_64) 
 

### Description:
We have around ~ 5 user registration validation requests per months that are bypassed. This results in SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry. 

Those are all user registrations (email). Averaging 2500 registrations per month. 

### Steps To Reproduce:
After a lot of thinking, and months of happening, I realized, some users probably click many times at the submit  button. Resulting in multiple requests for registering. I attempted this, and true enough. This bypasses the unique rule for the email, thus reaching the Integrity constraint exception. 

I'm adding a front-end check to stop this. Back-end I won't do so, since I don't see any security issue. 

Yet, I'm still a little confused. **Wouldn't the system stop the user from using the same form csr token for multiple requests?**

- Relevant validation rule. `required|email|max:100|unique:users,email`
- No jobs are used for this behavior. 
- Signup requests uses default csrf middleware.

**Comment by ntzm** [comment]
Could you set up a repo with the issue so we can try it ourselves?

**Comment by rdok-linkwise** [comment]
You're right.

I'll also have to setup relevant integration tests.

Thanks for the reply @ntzm

**Comment by themsaid** [comment]
> Resulting in multiple requests for registering

This isn't an issue with the core, by the time the validator looks at the DB a record won't be existing and that's why the rule passes.

Protecting your app against such behaviour is something you need to consider, like for example disabling the button once it's clicked for the first time.

Closing this since it's not an issue with the core.

**Comment by rdok-linkwise** [comment]
Thank you for the clarification @themsaid That was my main question/verification: That indeed we'll have to protect our apps for such behaviors. 

Cheers.
