### ISSUE TITLE
[5.4] Call to undefined method Illuminate\View\Factory::getFirstLoop()

### ISSUE THREAD

**Issue by arthurkirkosa** [laravel/framework#17377]
- Laravel Version: 5.4.0-Dev
- PHP Version: 7.1
- Database Driver & Version:

### Description:
`getFirstLoop()` method is missing from `Illuminate\View\Concerns\ManagesLoops`

### Steps To Reproduce:
```
Symfony\Component\Debug\Exception\FatalThrowableError
Illuminate\Mail\SendQueuedMailable
```

I was sending a queued mailable

**Comment by themsaid** [comment]
Yeah that method was removed, please pull in the latest commits and refresh your views cache.

**Comment by apex39** [comment]
And refreshing your views' cache means deleting all php files in storage/framework/views

**Comment by RonMelkhior** [comment]
@apex39 Or running `php artisan view:clear`

**Comment by IJack** [comment]
Get the same error after updating from 5.3 to 5.4. Also running with PHP 7

```
Call to undefined method Illuminate\View\Factory::getFirstLoop() 
```

clearing cache had no effect

**Comment by arthurkirkosa** [comment]
Crear view cache, read the above ansewer

**Comment by IJack** [comment]
Oh yes, 
```php artisan view:clear``` is the right answer! Just read ```php artisan cache:clear```

Thank you!

**Comment by Koussay** [comment]
`php artisan view:clear` worked like a charm !!

**Comment by vinayakkulkarni** [comment]
`The Mix manifest does not exist. (View: /home/vagrant/platform/resources/views/layouts/master.blade.php) (View: /home/vagrant/platform/resources/views/layouts/master.blade.php)`

**Comment by eliooses** [comment]
`php artisan view:clear` rules !!!

Thanks a lot for sharing the correct answer.

**Comment by gitbunsin** [comment]
it's deosn't work Plz help

**Comment by AdamReece-WebBox** [comment]
I needed `php artisan config:clear`.

You can clear all 4 caches with this one liner:

`php artisan cache:clear && php artisan config:clear && php artisan route:clear && php artisan view:clear`
