### ISSUE TITLE
Testing data types issue

### ISSUE THREAD

**Issue by SamyOteroGlez** [laravel/framework#17380]
- Laravel Version: 5.1.39
- PHP Version: 5.5.9
- Database Driver & Version: 

### Description:
I'm trying to create some tests for my app. I'm acceding a form, filling the fields and submitting the form but the test fails because an authorisation issue. At some point in the AuthServiceProvider class I'm checking if the `$user->patient_id` is the same as the `$patient->id`. $patient is the result of a query using `findOrFails()` function. All the db is populated using fakers and factories. 

When I compare `$user->patient_id === $patient->id` it returns false just because the type of the first is integer and the type of the second is string (made totally sense the result until now). But in the DB those values are INT and if I debug in the real app (not runing the test) the types for both are the same.

Why the results of the `findOrFail()` function is returning values as string when the test is running and is returning integer in the site?

### Steps To Reproduce:
In the AuthServiceProvider class check for an integer value type on the result of a query using the `findOrFail()` function using laravel testCase, phpunit, ...

```
class AuthServiceProvider extends ServiceProvider{
.
.
.

    $gate->define('manage-patients', function ($user, $patientID) {

        $patient = ($patientID) ? $patientModel->findOrFail($patientID) : null;
    
        if ($user->role === 'patient') {

                if ($user->patient_id === $patient->id) {
                    return true;
                } else {
                    return false;
                }
        }
    }
}
```

**Comment by jerguslejko** [comment]
It seems that in `v5.1`, this is an intended behaviour.

However, you can solve it by using [Attribute casting](https://laravel.com/docs/5.1/eloquent-mutators#attribute-casting). Hope that helps

**Comment by SamyOteroGlez** [comment]
Thanks jerguslejko for your answer.

I agreed with you, that could be a work around, but then I will need to cast every `int` value in the app if I want to test an `if` statement using `===`.

I am not 100% sure yet but this could be a phpunit way of doing instead of a laravel issue.

**Comment by jerguslejko** [comment]
Yeah, I suppose this is not a bug, but a missing feature. Fresh Laravel 5.1 installation seems to behave like that.
