### ISSUE TITLE
Name of Exception(s) folder

### ISSUE THREAD

**Issue by gizburdt** [laravel/framework#17394]
Hi, I was looking at the source code (sometimes I do that, just to learn from it) and I saw in some Laravel "sub-packages" the Exception folder is called "Exception", and in other packages it's called "Exceptions". I can create a PR, but I don't know if this is done on purpose, and what the right name is (plural or singular).

Called "Exception" in:
- Http

Called "Exceptions" in:
- Foundation
- Routing

**Comment by themsaid** [comment]
I'd say go ahead and create a PR to make the one in HTTP same as the rest. Please notice that this is a breaking change though, so 5.4 branch is the branch for it.
