### ISSUE TITLE
Slack duplication

### ISSUE THREAD

**Issue by mojosef** [laravel/framework#17393]
- Laravel Version: 5.3
- PHP Version:
- Database Driver & Version:

### Description:
If sending to a collection of users, slack notifications duplicate which doesn't make sense as it is posting to a channel?

### Steps To Reproduce:
Add slack to a notification and send to a collection of users.

**Comment by themsaid** [comment]
@freekmurze Any thoughts on this?

**Comment by freekmurze** [comment]
I haven't sent a notification to a collection of users before, so haven't come across this bug yet.

**Comment by GrahamCampbell** [comment]
More likely your queue job is throwing another exception, or you've set the timeout too low, so it gets run more than once.

**Comment by mojosef** [comment]
@grahamcampbell surely that would send the other notifications multiple times? Which it isn't in this case.

**Comment by GrahamCampbell** [comment]
Nom, only ones that have lots of users to notify, so the timeout is exceeded, so the job is picked up by another worker and run again, even know the other job has not finished. (This timeout is different to the one passed as an argument to the cli command. This is defined in the queue config.)

**Comment by mojosef** [comment]
Oh I see, that makes sense. In this instance it's only to 3 users however it's a part of a job that sends the notification. Would it be considered bad practice to have the notification be triggered by the job?

**Comment by GrahamCampbell** [comment]
> Would it be considered bad practice to have the notification be triggered by the job?

No, you can do what you want, but, just be careful if you expect things to be more than a few seconds running, when setting timeout configuration. :)

**Comment by mojosef** [comment]
Really appreciate the advice, thank you.

**Comment by mojosef** [comment]
I've tested with the timeout configuration and it's definitely sending one slack notification to each user in the collection. 

The slack notifications are always the exact amount to what is in the user collection?

**Comment by jamesbhatta** [comment]
Yes it seems to be a issue.  I am experiencing the same problem as well till now in laravel 7. I want to ONE single slack notification as well as database notifications to multiple users. But the slack notification is equal to the count of database notifications being sent to multiple user.

**Comment by krtcom** [comment]
I am experiencing the same problem. Can this issue be reopened?
