### ISSUE TITLE
[5.3] Auth::user() returns null in some cases

### ISSUE THREAD

**Issue by ES-Vodoo** [laravel/framework#17402]
- Laravel Version: 5.3.28
- PHP Version: 7.0.10
- Database Driver & Version: sqlite3 (3.13.0)

### Description:

> FatalThrowableError in CheckForBan.php line 19:
> Call to a member function isBanned() on null
> in CheckForBan.php line 19
> at CheckForBan->handle(object(Request), object(Closure)) in Pipeline.php line 137
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 27
> at CheckForMaintenanceMode->handle(object(Request), object(Closure)) in Pipeline.php line 137
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 104
> at Pipeline->then(object(Closure)) in Kernel.php line 150
> at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 117
> at Kernel->handle(object(Request)) in index.php line 53

Auth::user() returns null in middleware that redirects user if he is banned. Similar middleware (check for admin) works great.

Tested on fresh project.

CheckForBan.php (Auth::check() in statement removed for reproduction)
```
    public function handle($request, Closure $next)
    {
        if (Auth::user()->isBanned())
        {
            redirect('home');
        }

        return $next($request);
    }
```

Admin.php
```
    public function handle($request, Closure $next)
    {
        if (Auth::check() && Auth::user()->isAdmin())
        {
            return $next($request);
        }

        return redirect('home');
    }
```

### Steps To Reproduce:

1. Create middleware CheckForBan
2. Create isBanned function in User.php which returns true (for test)
3. Add middleware to middleware array in Kernel.php (App\Http\Kernel)
4. Refresh website

**Comment by GrahamCampbell** [comment]
This is absolutely the expected behaviour. If you throw an exception from a middleware, BEFORE routing has happened, then none of your middleware attached to the routes (such as auth), will be run.
