### ISSUE TITLE
Artisan Command for make:seeder failes to properly construct class name

### ISSUE THREAD

**Issue by roni-estein** [laravel/framework#17407]
- Laravel Version: 5.3.29
- PHP Version: 7.0.6
- Database Driver & Version: sqlite

### Description:
when using namespaces for models and controllers per the docs you can use the command
php artisan make:model /namespace/model

Or 

php artisan make:controller /namespace/controller

However, if you are making a Seeder, it puts the file in the correct place but errors out on the class name

### Steps To Reproduce:
php artisan make:seeder TestName/TestNameTableSeeder

This will yield
Seeder Created Successfully
The file can be found in the correct place but looks like this:

/database/seed/TestName/TestNameTableSeeder.php

```
<?php

use Illuminate\Database\Seeder;

class TestName/TestNameTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
    }

```

**Comment by martinbean** [comment]
@roni-estein I don’t think seed classes were intended to be name-spaced.

**Comment by GrahamCampbell** [comment]
Because you used the wrong slash.

**Comment by roni-estein** [comment]
@martinbean It's not name spaced, it's organizational. Sometimes, when working on something particularly large in terms of parts, like medical or pharmaceutical system, or any number of packages you can get tremendous re-use out of organized seeding. Especially during development and end to end visual testing. It is documented for Controllers and Models for name spacing and organizational purposes using the forward slash. Seems like it would be beneficial to have it carried out through the other commands in the same fashion. 

@GrahamCampbell, that doesn't repair it, it strips out the directory and dumps it in the base seeder directory not the subdirectory where it belongs.

**Comment by devcircus** [comment]
```
php artisan make:seeder Users//UsersSeeder 
```
This will correctly create the seeder and produces no errors.

**Comment by roni-estein** [comment]
@devcircus 

yup, exactly as the original post points out :)
Thanks for the interest though. I've been seeding out test patterns for half a day for a new module. It's not the biggest deal in the world manually updating it but it would be nice if it just worked.

**Comment by devcircus** [comment]
I have it working perfectly in a test repo. May submit a pull request after I run some tests.
