### ISSUE TITLE
Nested @foreach bug

### ISSUE THREAD

**Issue by aleemb** [laravel/framework#17415]
- Laravel Version: 5.3.29

### Description:

Adding a nested loop breaks the `$loop->iteration` and `$loop->last`, etc in parent loop.

### Steps To Reproduce:

```
<?php
$foo = ['a', 'b', 'c'];
$bar = ['d', 'e', 'f'];
?>
@foreach ($foo as $f)
  {{ $loop->iteration }}
@endforeach

// prints 1 2 3

@foreach ($foo as $f)
  {{ $loop->iteration }}
  @foreach ($bar as $b) @endforeach
@endforeach

// print 1 4 4
```

Also breaks `$loop->last` etc.

**Comment by GrahamCampbell** [comment]
Is this also the case in 5.4?

**Comment by themsaid** [comment]
Actually I can't replicate on 5.3, copied the exact example to a fresh 5.3 installation and the output is:

`1 2 3 1 2 3`

**Comment by GrahamCampbell** [comment]
Try clearing your compiled view cache perhapse?

**Comment by aleemb** [comment]
Agh! I had `radic/blade-extensions` left over from a while back which also provided the `$loop->iteration` so the two came into in conflict. Didn't hit the issue until today.

Sorry for the false alarm.
