### ISSUE TITLE
Validation of array with empty key does not validate correctly

### ISSUE THREAD

**Issue by mbaeuerle** [laravel/framework#17423]
- Laravel Version: 5.3.29
- PHP Version: 7.1.0
- Database Driver & Version: --

### Description:
Validating an array with an empty key leads to validation rules not being applied under the empty key. 

### Steps To Reproduce:
Say I have a bunch of properties, each of them must have a type:

``` json
{
    "properties": {
      "prop1": {
        "type":"integer"
      },
      "prop2": {
        "type":"string"
      }
}
```

Now I have the validation rules like so:

```
'properties'        => 'required|array',
'properties.*.type' => 'required|in:integer,string,numeric'
```

A wrong type fails: 

``` json
{
    "properties": {
      "prop2": {
        "type":"wrong_type"
      }
}
```

--> fails

It is possible to add an empty string as property key (I am not sure if this is intended):

``` json
{
    "properties": {
      "": {
        "type":"integer"
      }
}
```

--> passes

But now the type is not checked any more:

``` json
{
    "properties": {
      "": {
        "type":"wrong_type"
      }
}
```

--> also passes

Which is unexpected behavior

**Comment by themsaid** [comment]
PR submitted: https://github.com/laravel/framework/pull/17426

Thanks :)
