### ISSUE TITLE
$loop variable not available when rendering views for collections

### ISSUE THREAD

**Issue by mattems** [laravel/framework#17437]
- Laravel Version: 5.3.29
- PHP Version: 7.0.14
- Database Driver & Version:

### Description:
When using the @each loop the $loop variable is not available in the subview. Thoughts would be that it is the same as @foreach 

### Steps To Reproduce:

`@each('blog.partial.post', $posts, 'post')`

blog/partial/post.blade.php
`<div class="post {{ $loop->first ? 'first' : ''}}">{{ $post->title }}</div>`

result is: Undefined variable: loop

**Comment by themsaid** [comment]
only @foreach and @forelse is supported currently, feel free to open a PR to implement it to @each if you think it's useful.

Thanks anyway :)
