### ISSUE TITLE
Ajax Searh To Complex

### ISSUE THREAD

**Issue by srj9651** [laravel/framework#17448]
- Laravel Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
Ajax search method is complex in laravel 5.3 . Still laravel is not handy in live search and live crud system !

### Steps To Reproduce:
Include handy method of live crud in laravel with ajax and Json

**Comment by themsaid** [comment]
If you have any specific suggestions feel free to open a PR.
