### ISSUE TITLE
Polymorphic relation fails due to namespace backslashes

### ISSUE THREAD

**Issue by matbeard** [laravel/framework#17446]
- Laravel Version: 5.3
- PHP Version: 7.0
- Database Driver & Version: MySQL 5.7

### Description:
I've created a polymorphic relationship which works as expected. However, it fails as soon as I do anything 'advanced' with the `morphMany` definition.

For example, this works and returns the appropriate records:
`return $this->morphMany('App\Models\Attachment', 'attachmentable');`

However, if I add additional query builder methods, it fails and returns no records. For example:
`return $this->morphMany('App\Models\Attachment', 'attachmentable')->selectRaw("file_name, file_ext, file_size");`

This is just a very simple example. I also need to add groupBy and additional where clauses.

I think the issue lies in the namespace backslashes not being escaped. If I copy/paste the generated query (from DebugBar) into MySQL Workbench and manually escape the namespace, the query works.

UPDATE: It gets more bizarre. If I try to get the related records using eager loading, for example: `$employees = Employee::with('attachments')->get()`, it fails, no related models are returned.

But, if I get the employee first and then get the attachments, it works: `$attachments = $employee->attachments;`
I can even paginate: `$attachments = $employee->attachments()->paginate(10);`

**Comment by andrewpillar** [comment]
Have you tried escaping the backslashes when using the `morphMany` method yourself like this:

    $this->morphMany('App\\Models\\Attachment', 'attachmentable')->selectRaw("file_name, file_ext, file_size");

Since you said the query works fine when you escape the namespace manually in MySQL Workbench, I reckon its worth giving it a shot.

**Comment by matbeard** [comment]
I'm afraid escaping the backslashes in the `morphMany` makes no difference.

**Comment by andrewpillar** [comment]
Hmm, just tried what you're doing with a polymorphic relation in an application of mine, and everything seems to work as expected, I'll post code below.

    public function comments()
    {
        return $this->morphMany('App\Models\Comment', 'commentable')->selectRaw('id. user_id');
    }

And when I call the method directly from a related model it returns a collection of Comment models populated only with the given columns specified in the `selectRaw` method.

    // This works for me.
    $post->comments()->get();

I also tried it with the shorthand class notation, and it works.

    return $this->morphMany(Comment::class, 'commentable')->selectRaw('id, user_id');

I'm using Laravel 5.3, PHP 7.0, and MySQL 5.7.17 server.

**Comment by matbeard** [comment]
Yes.. in my case `$employee->attachments()->get();` works (loading attachments for a single record).

But, `Employee::with('attachments')->get()` doesn't work (eager loading attachments for multiple records).

The generated query for the second example works when pasted into Workbench, but only after escaping the backslashes.

**Comment by andrewpillar** [comment]
Ok I think I know why, I dug through some of the Eloquent code base and basically when Eloquent starts eager loading relations it builds up a key-value array of the related models to add to the parent model,, as you can see here from the code base:

[buildDictionary]:(https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php#L199)

```php
protected function buildDictionary(Collection $results)
{
    $dictionary = [];
    $foreign = $this->getPlainForeignKey();
    // First we will create a dictionary of models keyed by the foreign key of the
    // relationship as this will allow us to quickly access all of the related
    // models without having to do nested looping which will be quite slow.
    foreach ($results as $result) {
        $dictionary[$result->{$foreign}][] = $result;
    }
    return $dictionary;
}
```

As you can see it tries getting the foreign key for the related model, however if that foreign key doesn't exist then it uses an empty string. This is the problem that's occurring with you, in the `selectRaw` method you don't appear to be selecting the foreign key of the model, which is why when you eager load them you get an empty collection.

Passing the foreign key column name to the `selectRaw` method should fix this issue. Hopefully it works.

**Comment by matbeard** [comment]
Brilliant. Thanks andrew. A very simple solution and it's working fine now.

It was just the fact that it worked in certain circumstances that was confusing me.
