### ISSUE TITLE
[5.4] ConvertEmptyStringsToNull Middleware causes date Validation to fail

### ISSUE THREAD

**Issue by kubacode** [laravel/framework#17442]
- Laravel Version: 5.4.0-Dev
- PHP Version: 7.0.17
- Database Driver & Version: N/A

### Description:
When the new ConvertEmptyStringsToNull middleware is applied, optional date validation (IE when the field is not marked as required) fails, as a null value does not parse the same as an empty string in the validateDate Validation method.

### Steps To Reproduce:
Enable the ConvertEmptyStringsToNull middleware and validate a not-required date input.

**Comment by themsaid** [comment]
Well, that's the point of the middleware, if you still want to keep empty strings then don't use it, otherwise you'll need to use the `nullable` rule to instruct the validator to accept null as a value.

**Comment by taylorotwell** [comment]
Indeed, use the `nullable` middleware if you want to allow nulls during validation.

**Comment by kubacode** [comment]
I don't want to keep an empty value, I'd like to keep a null value. I hadn't thought of using the `nullable` rule and will give this a go, but should the behaviour of the validateDate method be different when a null value is passed rather than an empty string? I would have expected the behaviour to be the same in both cases.
