### ISSUE TITLE
Empty Deferred Service Providers cause the app to fail

### ISSUE THREAD

**Issue by lsiebert** [laravel/framework#17454]
- Laravel Version: 5.3.29
- PHP Version:5.6.5
- Database Driver & Version: Mysql 5.7.15

### Description:
A class that extends the ServiceProvider and is added under providers in config/app.php, where $defer is true and the provides method returns null, will error on load

### Steps To Reproduce:
create a new provider using `php artisan make:provider TestServiceProvider`
add a provides() method and set protected $defer to true
run app.

An easy fix would be testing for return values that can't be used as associative array keys in ProviderRepository, and log a warning if this happens.  Alternatively, a more descriptive fatal error could be raised.

**Comment by themsaid** [comment]
Can't replicate:

```
class TestProvider extends ServiceProvider
{
    protected $defer = true;

    public function provides()
    {
        return null;
    }
}
```

I believe the problem is something in the custom code of your provider, please investigate further and ping me if you found better explanation of the issue.
