### ISSUE TITLE
Soft delete not works when boot method is declared in Model.

### ISSUE THREAD

**Issue by rslhdyt** [laravel/framework#17462]
- Laravel Version: 5.3.x-dev
- PHP Version: 5.6.21
- Database Driver & Version: mysql 14.14

### Description:
Soft delete not works when boot method is declared in Model.

### Steps To Reproduce:

1. add method boot in Model

````
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Team extends Model
{
    use SoftDeletes;

    protected $dates = [
        'deleted_at'
    ];

    ....

    public static function boot()
    {
        Team::created(function ($team) {
            $team->members()->create([
                'user_id' => $team->created_by_id,
                'is_admin' => true,
            ]);
        });
    }

   ....

````

2. Load all data with `Team::all()` or `Team::paginate` or `Team::where('anything', $anything)->get()`
3. Deleted data will be loaded in query collection, the global scope of softDeleted overided by method boot in Model.

**Comment by GrahamCampbell** [comment]
You forgot to call `parent::boot()`.
