### ISSUE TITLE
Error while running composer install on fresh laravel install

### ISSUE THREAD

**Issue by Rndwiga** [laravel/framework#17482]
- Laravel Version: 5.4.*
- PHP Version: 5.6.4
- Database Driver & Version:

### Description:

whenever i try to spin up a new project, i composer throws ErrorException

### Steps To Reproduce:
1. git clone -b develop https://github.com/laravel/laravel.git
2. cd laravel
3. composer install
![image](https://cloud.githubusercontent.com/assets/4418418/22184874/9ec228b2-e0eb-11e6-9668-5d9397985f7b.png)

**Comment by GrahamCampbell** [comment]
Thanks, but this doesn't look like a bug with the laravel framework itself.
