### ISSUE TITLE
Can't update with Composer

### ISSUE THREAD

**Issue by voinearob** [laravel/framework#17501]
- Laravel Version: 5.3.27
- PHP Version: 7.1

### Description:
Hello,

Ever since I've installed the latest PHP, I can't update my packages with Composer anymore. It gives an error on updating **_symfony/var-dumper (v3.1.7 => v3.1.9)_**.

**[ErrorException]
A non-numeric value encountered**

So it's been a couple of months and I had hoped to see this fixed in the meantime, but I see the composer.json file on your master branch is still using symfony 3.1.*.

When will it be updated to 3.2.* ? Also, until then, is there any way to bypass this error so I can install the other things ?

Thanks.

**Comment by sisve** [comment]
That is indeed a PHP 7.1 error messages. Some package isn't compatible with PHP 7.1. Check the stack trace (should be in your logs) and file a bug report at their git repo. Meanwhile, keep using PHP 7.0.

**Comment by voinearob** [comment]
@sisve I suppose version 3.2.* of Symfony is compatible with PHP 7.1, so that will fix it.

**Comment by GrahamCampbell** [comment]
Please report this bug to symfony. 3.1.x SHOULD work on php7.1.
