### ISSUE TITLE
[5.4] Undocummented breaking change for eloquent relationship foreign key name

### ISSUE THREAD

**Issue by CyrilMazur** [laravel/framework#17503]
When omitting the foreign key name in the definition of a relationship, like so

```php
    public function profile()
    {
        return $this->belongsTo(Profile::class);
    }
```

the foreign key name is automatically generated by Laravel, but the way it generates has changed between 5.3 and 5.4.

In 5.3:
```php
$foreignKey = Str::snake($relation).'_id';
```
(https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Eloquent/Model.php#L776)

In 5.4:
```php
$foreignKey = Str::snake($relation).'_'.$instance->getKeyName();
```
(https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php#L112)

This breaks when a table is using a primary key different from "id".

**Comment by fernandobandeira** [comment]
Refs #16847

**Comment by ntzm** [comment]
You can submit a PR for the docs [here](https://github.com/laravel/docs)

**Comment by GrahamCampbell** [comment]
Thanks for reporting.

**Comment by taylorotwell** [comment]
Documented.
