### ISSUE TITLE
[5.1] Login not working in Chrome when config.session.domain isn't null

### ISSUE THREAD

**Issue by Jaspur** [laravel/framework#17505]
- Laravel Version: 5.1.45
- PHP Version: 7
- Database Driver & Version: PgSQL

### Description:
Since the last Chrome update I had trouble logging in the application. It was redirected back to the login page when trying to login. No errors were given. I set ```config.session.domain``` to ```nulll``` and it worked again. 
Strange because it worked for months like I had before. And this only occurs on Chrome. Probably since last update, because a few days ago it worked fine.

### Steps To Reproduce:
Fill in ```config.session.domain=yourdomain.com``` and try to login with latest Chrome

**Comment by it-can** [comment]
Try to wipe all your cookies?

**Comment by Jaspur** [comment]
That didn't work. Tried on multiple computers. All users on Chrome experienced the same.

**Comment by it-can** [comment]
And if you try '''.yourdomain.com'''

**Comment by Jaspur** [comment]
Tried that too. Same issue.

**Comment by GrahamCampbell** [comment]
Please ask on the forums.

**Comment by pedramre** [comment]
I had a lot of research about this subject and test anyway but I didn't get any good result, but I understood This problem can be caused by confusing the names of the sessions by chrome or any browser, so I changed the session name in `config/session.php` by adding a random string to cookie my problem resolved.

my old code

    'cookie' => env(
            'SESSION_COOKIE',
            Str::slug(env('APP_NAME', 'laravel'), '_').'_session'
        ),

my new code

    'cookie' => env(
            'SESSION_COOKIE',
            Str::slug(env('APP_NAME', 'laravel'), '_').'_newsession'
        ),

**Comment by xbensommo** [comment]
I am experiencing the issue with amazon ec2 instance and google chrome browser, but when using opera browser all seems to work accordingly

**Comment by xbensommo** [comment]
I tried most of the recommended methods and nothing I know seems to be working, anyone with a different strategy on how to approach this kind of issue
