### ISSUE TITLE
[5.4] Name for Notifiables

### ISSUE THREAD

**Issue by manticorp** [laravel/framework#17506]
- Laravel Version: 5.4
- PHP Version: 7.1
- Database Driver & Version: irrelevant

### Description:

Notifiables should have an option to present a 'name' field to be notified by.

```
public function routeNotificationForMail()
{
    return $this->email;
}

public function nameForNotifications()
{
    return $this->name;
}
```

And then in the Mail channel for example, we could have:

```
// Illuminate\Notifications\Channels\MailChannel


    protected method send() {
        $this->mailer->send($message->view, $message->data(), function ($m) use ($notifiable, $notification, $message) {
            $recipients = empty($message->to) ? $notifiable->routeNotificationFor('mail') : $message->to;

            $toName = method_exists($notifiable, 'nameForNotifications') ? $notifiable->nameForNotifications() : null;

            if (is_array($recipients)) {
                $m->bcc($recipients);
            } else {
                $m->to($recipients, $toName);
            }

            // ... etc
        });
    }
```

At the moment, emails are sent with no 'to' name on the mail channel, which means having to completely override it if that's something you need!

**Comment by themsaid** [comment]
Mail notifications in 5.4 is sent via BCC not TO, that's why you won't find anything in the to parameter if you look at it in MailTrap.
