### ISSUE TITLE
Easiest way to change config/* programmatically?

### ISSUE THREAD

**Issue by warriorkitty** [laravel/framework#17513]
I don't know if this is the right place to ask so sorry if I made a mistake. Let me explain the case:

I have an application used by few clients. Whenever I'm getting another client I need to do N tasks for preparing the application so I'm creating a script.

1. clone and download all dependencies
2. prepare DB (migrations, initial seeders)
...

One of the tasks is editing config/* files. For example: global Redis namespace, username and password to the database, etc.

What is the easiest way to read some config/* file, change it, and write it back 'as-is'? I would like to preserve the whole, clean structure of the file. I think that regex search-and-replace I was thinking about is kind of an overkill.

**Comment by jerguslejko** [comment]
The best solution would be to store _per client_ data in the `.env` file and reference it from the config files.

`.env`
```
REDIS_NAMESPACE=client1
```

`config/redis.php`
```
[
    'namespace' => env('REDIS_NAMESPACE', 'default') // if default value is not provided, it fallbacks to null
]
```

**Comment by warriorkitty** [comment]
OK, seems reasonable. Here is a subquestion:

A lot of configuration depends on the client's name: database name, Redis namespace, etc.
Would you change .env file programmatically with Regex or is there a more _Laravel_ way?

**Comment by jerguslejko** [comment]
Personally, I would do it by hand. If you really need to do it that regularly, I'd go for a shell script using regex. Or a php script, it does not really matter.

And nope, I do not think there is a more _Laravel way_.

**Comment by warriorkitty** [comment]
OK, great. Thank you! I'll also look at artisan key:generate to see how artisan does that.
