### ISSUE TITLE
[5.4] Tests breaks when upgrading from 5.3 to 5.4 due to incorrect namespaces

### ISSUE THREAD

**Issue by kfirba** [laravel/framework#17516]
- Laravel Version: 5.4.0
- PHP Version: 7.0.12
- Database Driver & Version: 10.1.19-MariaDB Homebrew

### Description:
When upgrading a Laravel 5.3 application to 5.4, as the upgrade guide mentions, we need to use the `laravel/browser-kit-testing` package in order to have our browser testing work as they did in 5.3.
The upgrade guide mentions that we need to make our default `TestCase` extend `Laravel\BrowserKitTesting\TestCase` in order to everything to work.

However, there is still an issue. Assuming we have a test class that uses the `DatabaseTrasactions` trait, the trait won't actually take effect. If we take a look at the `Laravel\BrowserKitTesting\TestCase` class at the `setUp()` method, we can see that there is a call to `$this->setUpTraits();`. The `setUpTraits()` method is really simple, it checks to see which traits the current class is using, and if it happens to use, for example, the `DatabaseTransactions` trait, it will call the `beginDatabaseTransaction` method on that trait. 

So this is where it gets interesting. Since we upgrade from 5.3 to 5.4, our test classes are using the `Illuminate\Foundation\Testing\DatabaseTransactions` trait. However, the `setUpTraits` method defined in `Laravel\BrowserKitTesting\TestCase` is checking for the  `Laravel\BrowserKitTesting\DatabaseTransactions` trait, hence resulting the current test classes to break.

As I see it there are 2 solutions:

1. Change the `use` statement in every test class from the "old" namespace to the "new" namespace. For example, change `use Illuminate\Foundation\Testing\DatabaseTransactions;` to `use Laravel\BrowserKitTesting\DatabaseTransactions;` which is a pain.
2. Modify the `setUpTraits` method on `Laravel\BrowserKitTesting\TestCase` to also check for the "old" traits - will make the upgrade seamless.

### Steps To Reproduce:
Upgrade Laravel 5.3 app which has browser tests that utilizes some built-in trait to 5.4 and run the tests.

**Comment by themsaid** [comment]
Thank you for reporting this, I believe it's better that you update the traits to point to the ones in the package, that way we isolate the old traits from the ones existing in the core, which may change in the future. So if you want your tests not to be affected then I suggest that you update the namespace of the traits used to point to the package.

Maybe you can do that easily with a code editor.

**Comment by kfirba** [comment]
@themsaid That can work. However, I think the upgrade guide should mention that.

**Comment by themsaid** [comment]
We end up doing the opposite: https://github.com/laravel/browser-kit-testing/commit/a0380837f7cf4520e22d0b0c00b868cf5988e231

Now you can use the traits from the core as usual.

**Comment by kfirba** [comment]
@themsaid Glad it got resolved :) Keep up the good work!
