### ISSUE TITLE
[5.4] illuminate/contracts 5.4 release needed for testing 

### ISSUE THREAD

**Issue by lukepolo** [laravel/framework#17510]
- Laravel Version: 5.4.0
- PHP Version: PHP7
- Database Driver & Version:

### Description:

```
 Problem 1
    - Installation request for laravel/socialite ~3.0 -> satisfiable by laravel/socialite[v3.0.0].
    - laravel/socialite v3.0.0 requires illuminate/contracts ~5.4 -> satisfiable by illuminate/contracts[5.4.x-dev, 5.5.x-dev] but these conflict with your requirements or minimum-stability.
```

### Steps To Reproduce:
https://travis-ci.org/SocialiteProviders/Manager/jobs/194913667

**Comment by themsaid** [comment]
Everything seems fine on my end, can you share your composer.json file?

**Comment by lukepolo** [comment]
Yup

https://github.com/lukepolo/Manager/blob/18b3cb46b50ac9120909d024c9a295c2a69ed541/composer.json

This is not my package but trying to make a PR to make it work with 5.4.

**Comment by brunogaspar** [comment]
Same for all the other sub components like `illuminate/support` needs to be tagged.

**Comment by tillkruss** [comment]
Should happening in the next couple of minutes.

**Comment by themsaid** [comment]
yeah it takes a little while :)

**Comment by lukepolo** [comment]
No problem! Figured id report it . thanks again for another great release!
