### ISSUE TITLE
[5.4] Cross-connection eager loading not working

### ISSUE THREAD

**Issue by KKSzymanowski** [laravel/framework#17515]
- Laravel Version: 5.3.29 versus 5.4.0-Dev
- PHP Version: 7.1.0
- Database Driver & Version: MariaDB 10.1.9

### Description:
Let's assume we have two models: User and Post. Users table is on `test_1` database(default), posts table on `test_2` database.

User model is the default one shipped with any fresh Laravel installation, Post model looks like this:
```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model 
{
    protected $connection = 'test_2';

    public function user() 
    {
        return $this->belongsTo(User::class);
    }
}
```

With Laravel 5.3 following query worked:
```php
App\Post::with('user')->get();
```
however with 5.4 this produces a following error:
```
Illuminate\Database\QueryException with message 
'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'test_2.users' doesn't exist (SQL: select * from `users` where `users`.`id` in (1))'
```

### Explanation

In 5.3 when `belongsTo` is called, it creates a related instance like this:
```php
$instance = new $related;
```
Couldn't be simpler.
In 5.4 it goes through `HasRelationships` trait which calls `newRelatedInstance`:
```php
$instance = $this->newRelatedInstance($related);
```
which essentially overrides the default connection with one specified on a Model calling `belongsTo`:
```php
return tap(new $class, function ($instance) {
    if (!$instance->getConnectionName()) {
        $instance->setConnection($this->connection);
    }
});
```
This means, when User model doesn't specify any connection(because the table is on the default database), it gets hijacked by this vicious trait.

### Solution

I suggest going back to the previous instantiation procedure because:
- If a table isn't on the default database I know I have to specify the connection.
- If a table **is** on the default database I know I can leave it off.

This new behavior essentially forces me to specify the connection, even if it's the default one, when I want to use relationships. This kinda breaks our beloved "convention over configuration" principle in my opinion.

If this solution doen't suit you, please mention this incompatibility in the upgrade guide.

**Comment by themsaid** [comment]
You need to explicitly set the connection name on the User model, if you're using multiple connections it's important to explicitly say that a certain model should be queried on X connection.

Otherwise the connection of the parent model will be used.

**Comment by KKSzymanowski** [comment]
Yes, I know it now works that way, but I think it's wrong.

I can't imagine any situation when I want to use a different connection for `User::get()` and `Post::with('user')->get()`. When I don't specify a connection, I expect the default one to be used every time and that's how it worked before.

If it's a *wontfix*, least you can do is mention it in the docs - it can save someone an hour of digging through the source code.

**Comment by KKSzymanowski** [comment]
@themsaid 
I see you updated the docs, I suppose I can close it now.
Thanks.
