### ISSUE TITLE
[5.4] Related model connection after upgrade to 5.4

### ISSUE THREAD

**Issue by RidgeA** [laravel/framework#17511]
- Laravel Version: 5.4.0
- PHP Version: 7.0.14
- Database Driver & Version: mysql 5.7.17

### Description:
Hello. I have a simple application based on Laravel to provide OAuth2 service. User's table maintained by another application and stored in another database.

So, I use 2 database connections - default connection for Laravel application  (where applied migrations from laravel/passport) and secondary connection, where stored user's table.

In User model I specified custom database connection and on Laravel 5.3.x version it works properly.

After updating to 5.4 version, when I try to get acces to user's tokens (``oauth/tokens`` endpoint) I see an error - application trying to find ``oauth_access_tokens`` table in secondary connection, while this table on primary connection.

I think the problem is that parent's model connection settings obtained by related model.

**Comment by themsaid** [comment]
In 5.4 related models are queried based on the parent's connection, do you use Passport for this or a custom implementation?

**Comment by RidgeA** [comment]
Yeap, I just found https://github.com/laravel/framework/pull/16103.

I use Passport.

As I understand, I should clearly setup connection for passport's models?

**Comment by themsaid** [comment]
Yes you need to set a connection for passport models if the parent model is on a non-default connection.

**Comment by RidgeA** [comment]
Thanks.
