### ISSUE TITLE
Call to undefined method Illuminate\Foundation\Application::share()?

### ISSUE THREAD

**Issue by vipin733** [laravel/framework#17526]
I try to upgrade my app L5.3 to L5.4 its giving errors
    `FatalThrowableError in TNTSearchServiceProvider.php line 13:
     Call to undefined method Illuminate\Foundation\Application::share()`

**Comment by stefanoruth** [comment]
https://laravel.com/docs/5.4/upgrade the share method has been removed

**Comment by vipin733** [comment]
i solved it thanks

**Comment by fsasvari** [comment]
Every 2nd package that I'm using have this kind of error. Everyone was using Application::share() so now I must wait for all of these packages to update first so I can update my app to Laravel 5.4 version...

**Comment by GrahamCampbell** [comment]
> Every 2nd package that I'm using have this kind of error

It's not like this change as been knew though tbh. Packages should have been using the newer (still like 3 years old) method.
