### ISSUE TITLE
[5.4] "Npm run" commands don't work on windows.

### ISSUE THREAD

**Issue by Frondor** [laravel/framework#17528]
- Laravel Version: 5.4.1
- PHP Version: 7.0.4
- node v6.9.4
- npm  v3.10.5
### Description:
npm commands are completely broken on windows (windows 7 in this case), whenever I run `npm run dev` I get the following error:
```
'node_modules' is not recognized as an internal or external command,
operable program or batch file.
```

[node-debug.log](https://hastebin.com/xacuxapeje.tex)

I tried 

```
  "scripts": {
    "dev": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "hot": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "production": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
```
It ran but without success: 
```
> @ dev c:\wamp\www\web
> node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.co
nfig.js

path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.parse (path.js:950:5)
    at new File (c:\wamp\www\web\node_modules\laravel-mix\src\File.js:14:30)
    at Object.module.exports.preprocess (c:\wamp\www\web\node_modules\laravel-mix\src\index.js:108:14)
    at Object.module.exports.sass (c:\wamp\www\web\node_modules\laravel-mix\src\index.js:84:27)
    at Object.<anonymous> (c:\wamp\www\web\webpack.mix.js:17:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Mix.initialize (c:\wamp\www\flores\node_modules\laravel-mix\src\Mix.js:38:9)
    at Object.<anonymous> (c:\wamp\www\flores\node_modules\laravel-mix\setup\webpack.config.js:18:5)
    at Module._compile (module.js:570:32)

```
### Steps To Reproduce:
Run `npm run dev` command on windows.

**Comment by PascaleBeier** [comment]
These are the scripts as they are meant to be:

```json
  "scripts": {
    "dev": "cross-env NODE_ENV=development webpack --progress --hide-modules",
    "watch": "cross-env NODE_ENV=development webpack --watch --progress --hide-modules",
    "hmr": "cross-env NODE_ENV=development webpack-dev-server --inline --hot",
    "production": "cross-env NODE_ENV=production webpack --progress --hide-modules"
  }
```

**Comment by Frondor** [comment]
@PascaleBeier No.
Just installed the latest version. I'm pretty sure that's the `package.json` installed for Mac users.
Also, this is the master branch: https://github.com/laravel/laravel/blob/master/package.json

**Comment by PascaleBeier** [comment]
@Frondor Did you try these? Taken from [laravel-mix](https://github.com/JeffreyWay/laravel-mix/).

**Comment by ac1982** [comment]
I have tried @PascaleBeier 's suggestion, but same issue.
Fresh installed Laravel 5.4.2 with npm 4.12, then npm install.
`npm run production`

[npm-debug.txt](https://github.com/laravel/framework/files/729958/npm-debug.txt)

**Comment by taylorotwell** [comment]
Looks like I may have to get my PC out of the closet :) ... can anyone confirm a working resolution that works on both mac and Windows?

**Comment by JeffreyWay** [comment]
@Frondor Please paste in your webpack.mix.js file.

**Comment by bajro17** [comment]
change from this:
"dev": "node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
to this:
"dev": "cross-env NODE_ENV=development webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",

for other commands same

**Comment by bajro17** [comment]
I dont know is this work for Mac but for me on Windows work

**Comment by JeffreyWay** [comment]
@bajro17 - But then it doesn't work if you're using Yarn. :/

**Comment by bajro17** [comment]
I don't know  than we need to find universal solution 😢

**Comment by jagadeshanh** [comment]
Just installed Laravel 5.4.3 on my windows machine and then ran

npm install

and then tried

npm run dev, npm run watch and it works perfectly fine for me.

**Comment by Frondor** [comment]
Changes like `cross-env NODE_ENV=development webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js` don't work because it assumes you have `cross-env` added you your `PATH` environment variable.

Appending the `node` command to the string should do the trick, but the error I shared before is still there. Debug logs are pointing to `c:\wamp\www\web\node_modules\laravel-mix\src\File.js:14:30`.

I didn't try any other version than L5.4.1, I'll check the 5.4.3 once I get back in home.

**Comment by JeffreyWay** [comment]
That's why we need to see what your webpack.mix.js file looks like. I'm wondering if there's an method argument there that isn't correct.

**Comment by Frondor** [comment]
@JeffreyWay everything is default, I didn't touch a single.

```
const { mix } = require('laravel-mix');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css');
```

**Comment by devcircus** [comment]
Win 8, node 7.4.0, npm 4.0.5 Laravel 5.4.3 everything works perfectly. Thanks for all the work put into this.

**Comment by a-wenzel** [comment]
I updated Node from 5.x.x to 7.4.0 and then it works on Windows (same error before).

```
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
```

**Comment by JeffreyWay** [comment]
@Frondor - At this point, your question is specifically related to Laravel Mix. It doesn't have anything to do with the framework code. I'm going to port this question over there.

https://github.com/JeffreyWay/laravel-mix/issues/185

**Comment by eduardoarandah** [comment]
Same problem
win 10 64bits
wampserver php7

Solution: 
Update windows npm with installer
https://nodejs.org/en/download/

**Comment by GabrielApG** [comment]
Same problem

MacOs Sierra
Laravel Framework 5.4.10
Valet - PHP 7.1.1
NPM 4.0.5

//Terminal 
$ npm run dev

> @ dev /Users/gabrielap/Sites/projectX
> node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

module.js:472
    throw err;
    ^

Error: Cannot find module '/Users/gabrielap/Sites/projectX/node_modules/cross-env/bin/cross-env.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! @ dev: `node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script 'node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/gabrielap/Sites/changingmybooking/npm-debug.log

**Comment by MiladAheshmeh** [comment]
I have same problem

I only upgrade my node 

its fixed

**Comment by AttaUrRehman24** [comment]
You can solve this problem 100%
https://github.com/AttaUrRehman24/laravel-mix

**Comment by kevosomi** [comment]
In WIndows (currently testing on Windows 10 X64), CD to your project root using the CMD/Powershell(or press SHIFT+F10 to open extended options window and click on CMD) and run `npm install` then `npm run development` and finally `npm run watch`. Goodluck!

**Comment by ssnatu** [comment]
Same problem when I run below

$ npm run dev

> node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

'node_modules' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules
--config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


Tried **cross-env** and  **node** but nothing is working for me.
I use integrated terminal MINGW64

**My versions:**

NPM - 5.6.0
Node - v8.11.2
Laravel - 5.4.36
Windows 8.1, 64-bit

**My package.json:**

{
  "private": true,
  "scripts": {
    "dev": "node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "hot": "node_modules/cross-env/bin/cross-env.js NODE_ENV=development webpack-dev-server --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "production": "node_modules/cross-env/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
  "devDependencies": {
    "axios": "^0.15.2",
    "bootstrap-sass": "^3.3.7",
    "jquery": "^3.1.0",
    "laravel-mix": "^0.5.0",
    "lodash": "^4.16.2",
    "vue": "^2.0.1"
  }
}

Please somebody help me with this. Thanks

**Comment by alipajand** [comment]
Any updates here?
Scripts that work in mac and windows???

**Comment by devcircus** [comment]
Maybe best to ask on the mix repo. I have a dev environment on Mac, Ubuntu and Windows and all work as expected.

**Comment by jasonbaciulis** [comment]
Here is what worked for me on Win 10.
```
  "scripts": {
    "dev": "npm run env NODE_ENV=development&&webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "npm run env NODE_ENV=developmen&&webpack --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "hot": "npm run env NODE_ENV=development&&webpack-dev-server --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "production": "npm run env NODE_ENV=production&&webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
```
