### ISSUE TITLE
[5.4] illuminate/container outdated on Packagist

### ISSUE THREAD

**Issue by ellisio** [laravel/framework#17522]
- Laravel Version: 5.4.x

### Description:

The Packagist version of [illuminate/container](https://packagist.org/packages/illuminate/container) is missing the `v5.4.0` tag.

This is causing any packages that reference this as a dependency to require the following in `composer.json`:

```
"minimum-stability": "dev",
"prefer-stable": true
```

Can we please get this bumped so we can properly reference this package?

**Comment by themsaid** [comment]
It should be pumped by now

**Comment by LKDevelopment** [comment]
@themsaid no it is still 5.4.x-dev.

**Comment by themsaid** [comment]
https://packagist.org/packages/illuminate/container#v5.4.0
