### ISSUE TITLE
[5.4] Database migrations in fresh install do not work

### ISSUE THREAD

**Issue by david-ridgeonnet** [laravel/framework#17530]
- Laravel Version: 5.4.0
- PHP Version: 5.6.14
- Database Driver & Version: MariaDB (MySQL) 10.1.8

### Description:
I freshly installed Laravel 5.4 and ran the commands to generate the sessions, failed_jobs, notifications tables in the database.

The following migrations all **fail** to run due to the recent change from UTF8 charsetto utf8mb4. This is due to the column length on these migrations not being defined **by default** in a new install.

- create_users
- password_resets
- notifications
- sessions

The `string` call in these migrations doesn't specify a length, so it uses `Builder::$defaultStringLength` which is currently still set to 255 causing this error and making migrations not migratable from the start without changing this value via `defaultStringLength()` method on the Builder class.

The following errors are produced when running migrations:
```
[Illuminate\Database\QueryException]
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `users` add unique `users_email_unique`(`email`))
[PDOException]
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
```

### Steps To Reproduce:

1. Install laravel 5.4
2. Set up configuration for database connection (no changes needed otherwise)
3. Try to migrate
4. See the failure

Thank you.

**Comment by coolynx** [comment]
Can you add another line in `config/database.php` file:

`'engine' => 'InnoDB ROW_FORMAT=DYNAMIC',`

And try again.

**Comment by david-ridgeonnet** [comment]
Apologies if I was not clear - this isn't something I _need_ a solution to for myself, but something that is broken within the framework without first changing something.

If the above fix is what is **recommended** then it should be in the configuration by default for new installs. However it would make more sense for something that uses `utf8mb4` by default to change the default string length to 191 instead of the 255 it currently has.

**Comment by coolynx** [comment]
You did not provide the error message. So, my guess was based on my experience with similar case.

If this solution worked then there are two things to consider:

1. Laravel 5.4 works out of box
2. Laravel 5.4 does not work out of box in specific conditions, i.e., when used with older MySQL/MariaDB versions and configurations. In those conditions you should specify this extra line.

And yes - it probably should be mentioned in documentation.

But before that we should find out if this is the case.

**Comment by a-komarev** [comment]
Add this to your `AppServiceProvider` if you have MySQL lower than 5.7.7:

```php
use Illuminate\Support\Facades\Schema;

public function boot()
{
    Schema::defaultStringLength(191);
}
```

**Comment by fernandobandeira** [comment]
Laravel supports officially only Mysql 5.7, it should work with < 5.7 anyways...
On 5.7 it is working out of the box because on 5.7 the innodb_large_prefix is enabled by default, if you are using MySQL 5.5 or 5.6 you should manually enable it since it is disabled by default... I agree that we could add a warning on the docs, but we don't need to change the 255 to 191 since that's an issue related to older versions of the RDBMS...

**Comment by david-ridgeonnet** [comment]
Thank you all, I see the version of MariaDB I am on is slightly behind the one where the defaults have changed (10.2.2). My file format for databases is still on Antelope so I had to adjust it to allow Barracuda, and turn on `innodb_large_prefix`. Apologies for the misunderstanding :)
