### ISSUE TITLE
pushMiddlewareToGroup not working on tests but working on app

### ISSUE THREAD

**Issue by acacha** [laravel/framework#17533]
- Laravel Version: Laravel 5.3 and 5.4
- PHP Version: PHP 7.0.9-1+deb.sury.org~wily+1
- Database Driver & Version: sqlite

### Description:

Please consider reopening this issue: See https://github.com/laravel/framework/issues/15426

The issue was closed because Pull Request is not accepted as a solution but the problem is still there. Proposed solution by @themsaid nows not works with Laravel 5.4 so maybe anybody could propose another solution or a refactor for my tests. Thanks!

### Steps To Reproduce:

See https://github.com/laravel/framework/issues/15426

**Comment by acacha** [comment]
In class pushMiddlewareToGroup on file Illuminate\Routing\Router.php property $this->middlewareGroups is and empty array so middleware is not added

**Comment by taylorotwell** [comment]
Have you found a solution?

**Comment by taylorotwell** [comment]
Should be fixed with this commit: https://github.com/laravel/framework/commit/1054fd2523913e59e980553b5411a22f16ecf817
