### ISSUE TITLE
[5.4] Breaking the way to register the middleware via the RouteServiceProvider

### ISSUE THREAD

**Issue by arcanedev-maroc** [laravel/framework#17532]
- Laravel Version: 5.4.0
- PHP Version: 7.1
- Database Driver & Version: none

### Description:

A breaking change appeared in my app that stops the usage of `$this->middleware()` in my external package's RouteServiceProvider `extends \Illuminate\Foundation\Support\Providers\RouteServiceProvider`.

This is the code i used to register the middleware.

```php
/**
 * Define the routes for the application.
 *
 * @return void
 */
public function map()
{
    $this->middleware('admin', \Vendor\Package\Http\Middleware\CheckAdministrators::class);
    //...
}
```

I fixed the issue by using the new method `aliasMiddleware`:

```php
/**
 * Define the routes for the application.
 *
 * @return void
 */
public function map()
{
    $this->aliasMiddleware('admin', \Vendor\Package\Http\Middleware\CheckAdministrators::class);
    //...
}
```

Is that a correct way to do it ? Why is not mentioned in the `Upgrade Guide` or `Middleware` doc section ?

**Comment by barryvdh** [comment]
Having the same issue; https://github.com/barryvdh/laravel-cors/pull/171
Should probably be documented.

**Comment by themsaid** [comment]
Thank you for pointing this out, PRed an update to the upgrade docs :)

**Comment by arcanedev-maroc** [comment]
PR: https://github.com/laravel/docs/pull/3028
