### ISSUE TITLE
Route model binding for pivots

### ISSUE THREAD

**Issue by Whyounes** [laravel/framework#17531]
- Laravel Version: 5.3
- PHP Version: 7
- Database Driver & Version: 

### Description:
 When we have sub-resource routing, and the second resource is a pivot model Laravel can't do the model binding and throw an error that the pivot model cannot be instantiated.
I guess the Eloquent can guess the relation based on the first resource, and then resolve it using the URL query parameter!

```
api/admin/faculties/{faculty}/departments/{department}
```

From the above example, we can take the faculty and look for the `departments` relation (which may be a pivot) and then query it with the route key name defined in the model. If not a `ModelNotFoundException` can be thrown normally. Is that possible?

**Comment by themsaid** [comment]
Sorry for not getting back to you earlier :) but please ask on the forums, this repo is for bug reporting only.
