### ISSUE TITLE
 Fatal error: Allowed memory size ?

### ISSUE THREAD

**Issue by vipin733** [laravel/framework#17537]
after upgraded to 5.4 I'm getting this on my local server I have 10k record but one more I have app which is L5.3  where in this I have 1lac record its working smooth. I just updated my app 5.3 to 5.4
Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 262144 bytes) in C:\laragon\www\gsms\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 621

**Comment by themsaid** [comment]
You'll have to provide more details, check what actions are causing this high memory consumption, and make sure that same app works fine on 5.3

**Comment by GrahamCampbell** [comment]
Exceeding memory limits is often caused by an infinite recursion.

**Comment by GrahamCampbell** [comment]
Please provide the full stack trace.

**Comment by vipin733** [comment]
i have same code in both app

**Comment by GrahamCampbell** [comment]
Please provide the full stack trace.

**Comment by vipin733** [comment]
Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 262144 bytes) in C:\laragon\www\gsms\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 621

**Comment by themsaid** [comment]
Full stack trace please.

**Comment by vipin733** [comment]
I just got this error

**Comment by GrahamCampbell** [comment]
Nothing we can do without any more information.

**Comment by GrahamCampbell** [comment]
Please feel free to open a new issue if you can provide something we can reproduce.

**Comment by vipin733** [comment]
https://www.dropbox.com/s/68240v5bfvv8xqs/1.PNG?dl=0

**Comment by GrahamCampbell** [comment]
That is not a full stack trace I'm afraid.

**Comment by vipin733** [comment]
even i checked my log file there is nothing

**Comment by vipin733** [comment]
even php artisan not working its throwing same errors "Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 262144 bytes) in C:\laragon\www\gsms\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 621"

**Comment by GrahamCampbell** [comment]
Looks like you have a cyclic dependency resolution perhaps. You still have not provided a stack trace. Once you have a stack trace we might be able to help, but this is not a forum I'm afraid.
