### ISSUE TITLE
Laravel Echo Private and Presence Channel Authentication

### ISSUE THREAD

**Issue by darshan199** [laravel/framework#17547]
- Laravel Version: 5.3
- PHP Version: 7
- Database Driver & Version: Mysql

### Description:
In my application i have two separated sections for users and admins for which i used Auth::guard() to authenticate them.
in my application i used Laravel Echo (pusher) for chatting purpose. The private and presence channel authentication is working fine for my users section.
but when i trying to authenticate for private and presence channel from my admins section it generates the error "authentication fail".
so in my application i want to subscribe private and presence channel from my admins section and also want to send a messages to users and get the users data from presence channel.
how can i achieve this please help me.

**Comment by themsaid** [comment]
Sorry but please ask on the forums, we try to keep this repo for bug reporting only :)
