### ISSUE TITLE
[5.4] Can't register a custom database connection using DB::resolverFor

### ISSUE THREAD

**Issue by aivish** [laravel/framework#17548]
- Laravel Version: 5.4.0
- PHP Version: 7.0.8
- Database Driver & Version: 10.0.28-MariaDB

### Description:
I'm having some trouble using custom DB connections in Laravel 5.4.
According to 5.4 upgrade guide, I now have to use `DB::resolverFor`, so I changed the `register` method in `AppServiceProvider` to:
```php
public function register()
{
    // Instead of $this->app->bind('db.connection.mysql', CustomMySqlConnection::class);
    \DB::resolverFor('mysql', function ($connection, $database, $prefix, $config) {
        return new CustomMySqlConnection($connection, $database, $prefix, $config);
    });
}
```

I'm using the CustomMySqlConnection to provide a different schema grammar, but for testing purposes it's just `dump`ing stuff, this is the CustomMySqlConnection class:
```php
<?php

namespace App\Extensions\Database;

use Illuminate\Database\MySqlConnection as IlluminateMySqlConnection;

class CustomMySqlConnection extends IlluminateMySqlConnection
{
    protected function getDefaultSchemaGrammar()
    {
        dump("Using custom grammar...");

        return parent::getDefaultSchemaGrammar();
    }
}
```

So when I run `php artisan migrate` I should see the dumped text. But I can't get this to work.

What seems to be the problem is because the `resolverFor` method is defined in the `Iluminate\Database\Connection` class, heres my interpretation of whats happening when `DB::resolverFor` is called: 
- using `DB` we get a singleton instance of `DatabaseManager`, since this class doesn't have a `resolverFor` method it's passed to the connection using `$this->connection()->$method(...$parameters);`
- since there is no existing `mysql` connection, the `connection` method makes a new `mysql` connection instance and stores it in the `$this->connections` array
- the connection is made by the `Connectors\ConnectionFactory` class - it checks if there is a resolver defined for the `mysql` driver using `Connection::getResolver($driver)`. At this point the resolver has not yet been added to `Connection`, so we get nothing from `getResolver` and the Laravel's `MySqlConnection` is returned.
- the `connection` method has finished and finally `resolverFor` is called and a resolver for `mysql` is added.
- I guess when the migrations are run the same `DatabaseManager` is used to retrieve a connection for `mysql`. Since a `mysql` connection has already been created, the existing connection is returned.

Couldn't the resolver stuff be handled by `DatabaseManager` so that a new connection wouldn't be created when `resolverFor` is called?

### Steps To Reproduce:
Install Laravel 5.4, create a custom MySqlConnection and use `DB::resolverFor` to resolve a different connection for mysql.

**Comment by themsaid** [comment]
Thank you for reporting this, the docs were updated now with the right way to do it:

```
use Illuminate\Database\Connection;

Connection::resolverFor('driver-name', function ($connection, $database, $prefix, $config) {
    //
});
```

**Comment by aivish** [comment]
Ooh right, the resolver stuff on `Connection` is static so the resolvers can be set directly on the `Connection` class without actually creating a new connection.. didn't thought of that, thanks!
