### ISSUE TITLE
[5.4] After middleware doesn't works when an exception is thrown

### ISSUE THREAD

**Issue by abellion** [laravel/framework#17542]
- Laravel Version: 5.4
- PHP Version: 7.0

### Description:

When an exception is thrown during the request processing (i.e. in controllers, or by the router) the middleware ```handle``` method is aborted ; what's after the ```$next``` closure call is never executed. 

It worked well in 5.3.

**Comment by GrahamCampbell** [comment]
Hmm, are you sure this is the case, or did the middleware order change in your upgrade?

**Comment by abellion** [comment]
Nothing changed during the upgrade except the Laravel version !

But even with a middleware order change the response should pass through all of them right ?

**Comment by GrahamCampbell** [comment]
No, it stops as soon as there's an exception.

**Comment by GrahamCampbell** [comment]
> Nothing changed during the upgrade except the Laravel version !

Probably you need to complete the rest of the upgrading steps.

I can't confirm this issue on my side.

**Comment by GrahamCampbell** [comment]
Please open a new issue if you can demonstrate a way to replicate this on a fresh 5.4 app.

**Comment by abellion** [comment]
> No, it stops as soon as there's an exception.

So, how to add headers to a response ? For CORS for example. They should be sent even if an exception occur.

**Comment by GrahamCampbell** [comment]
As long as your middleware runs before the exception happens it's fine.

**Comment by GrahamCampbell** [comment]
We still "back out" through the middleware if there's an exception, but any not "gone through" when an exception is thrown, will not get walked back though on the way out.

Kinda hard to explain middleware.

**Comment by abellion** [comment]
Okay so this is a Lumen issue because as you say in Laravel it's working fine.
I'll open an issue in the Lumen repo.

Thanks for your time.
