### ISSUE TITLE
[5.4] HasOneOrMany breaking change undocumented?

### ISSUE THREAD

**Issue by yajra** [laravel/framework#17559]
Laravel Version: 5.4.0
PHP Version: 7.1
Database Driver & Version: none

### Description:
`HasOneOrMany` method `getForeignKey()` was renamed to `getForeignKeyName()` and I think should be documented? Just a heads up for someone else who might bump on same issue. Thanks!

**Comment by yajra** [comment]
An example breaking change as stated in this issue https://github.com/yajra/laravel-datatables/issues/942. Thanks!

**Comment by themsaid** [comment]
It think it was renamed to `getQualifiedForeignKeyName`, `getForeignKeyName` returns only a segment of the foreign key, no?

**Comment by yajra** [comment]
@themsaid you are right, it was `getQualifiedForeignKeyName` and not `getForeignKeyName`. I was looking at the wrong commit on my repo. 

BTW, found a duplicate issue https://github.com/laravel/docs/issues/3017. Thanks!
