### ISSUE TITLE
Laravel flash messages

### ISSUE THREAD

**Issue by stephan-v** [laravel/framework#17569]
I know Laravel keeps track of flash messages with an flash array in the session which holds old and new arrays of flash data.

Example of what I am talking about.

```php
[
    '_flash' => [
        'new' => [],
        'old' => []
    ]
];
```

This is done because the distinction can now be made between flash data that has just been inserted and old flash data which has been displayed and can be discarded.

On save of the session data at the end of the request the new data is moved to the old array, but what happens if an ajax request is made or a redirect?

Wouldn't this trigger the process of moving flash data from new to old and possibly mess with the actual page which would need this flash data?

What prevents this from happening? I know the session is used as middleware I guess you could check the request type there but I don't see that being done either.

Hopefully somebody could tell me a bit more about this. I am sorry about asking this question here but I don't seem to be getting a reply anywhere else(even Laravel related communities) because this is pretty specific.

**Comment by ockle** [comment]
@stephan-v I don't think anything stops it from happening other than the developer anticipating it will/might and reflashing the data. See [here](https://laravel.com/docs/5.4/session#flash-data) and [here](https://laravel.com/docs/5.4/requests#old-input).

**Comment by stephan-v** [comment]
@ockle wouldn't it be better in that case to have a method to read from the session's flash data and unset the value that has been read?

Otherwise other requests might prompt the session flash data that will be moved from `_flash.new` to `_flash.old` to immediately get unset from the `_flash.old` array.

Thus if you have
**request** - **ajax request** - **request**(where you actually want to flash data)

You would lose your flash data you might intend for your request.

I guess normally you wouldn't bother with this because you might re-direct immediately when you are using flash messages because they usually mean a notice/error/update etc. But I feel like this could lead to some dodgy behavior.

**Comment by pfalsoncup** [comment]
I just found an problem (5.3) which relates to this issue. 

I have a redirect('/')->with('key', 'value');

If the user is not authorised at this point the flashes are aged without being used and the subsequent page after login doesn't not have the session values.

No ajax involved.
