### ISSUE TITLE
Container attempt to resolve instance even with null default argument

### ISSUE THREAD

**Issue by miklcct** [laravel/framework#17563]
Laravel: 5.3

When making an object out the container, the container will try to resolve an instance even it has null default argument specified. This fails in the case of an unresolvable optional dependency, e.g.

```
namespace App;
class Foo {
    public function __construct (SomeDataClass $config = NULL) {}
}
```
```
namespace App;
class SomeDataClass {
    public function __construct($primitive) {}
}
```

Foo is unresolvable without configuration by doing the following:

1. Install laravel
2. Create the two classes above
3. Attempt to call `app(Foo::class)` inside the application

**Comment by themsaid** [comment]
Missing laravel version, missing steps to reproduce.

Please make sure you submit all the requested data.

**Comment by miklcct** [comment]
Laravel: 5.3
