### ISSUE TITLE
Relationship queries

### ISSUE THREAD

**Issue by Yorkii** [laravel/framework#17567]
- Laravel Version: 5.4
- PHP Version: 7.0
- Database Driver & Version: postgresql

### Description:
Why does laravel adds extra condition when querying relationship? In some cases (if not most) it is unwanted behaviour lowering database performance. It always check if foreign key is not null. To be more precise it happens in `Illuminate/Database/Eloquent/Relations/HasOneOrMany.php` on line `60`. We should have more control over this.

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
