### ISSUE TITLE
[5.4] Mix .extract() still includes packages in main JS file

### ISSUE THREAD

**Issue by joeldbirch** [laravel/framework#17564]
- Laravel Version: 5.4
- PHP Version: 5.6.28
- Database Driver & Version: MySQL 5.6.34

All dependencies are up to date.

### Description:
The `.extract()` feature doesn't seem to work properly. It splits out the specified packages and creates separate JS files, but still includes them in main file. For example, the following code:
```JS
mix.js('resources/assets/js/app.js', 'public/js')
    .extract(['vue'])
    .sass('resources/assets/sass/app.scss', 'public/css');
```
Results in the following voutput when running `npm run dev` (image attached). I have confirmed that the vue.js package is included in both vendor.js and app.js. My uncombined app.js currently contains less than 1KB of code but is ending up even larger than the vendor.js file, as you can see.

<img width="435" alt="mix" src="https://cloud.githubusercontent.com/assets/75602/22322354/8234c072-e3ef-11e6-8bc2-bf91a850a313.png">

### Steps To Reproduce:
1. Enter the supplied code into webpack.mix.js
1. run `npm run dev`.

**Comment by JeffreyWay** [comment]
This should be filed with the Laravel Mix repo instead.

Anyway, this was fixed in a recent patch. Update your Laravel Mix dependency.

**Comment by joeldbirch** [comment]
Thanks Jeffrey! I looked but failed to find the Laravel Mix repo.
