### ISSUE TITLE
[5.4] mix.copy() directory -- files are copied without directories

### ISSUE THREAD

**Issue by komirad** [laravel/framework#17568]
- Laravel Version: 5.4
- PHP Version: 7

### Description:
**When executing mix.copy() on a directory, only files are copied.** 

Reading the [documentation](https://laravel.com/docs/5.4/mix#copying-files-and-directories) one would expect that the whole directory structure is copied, but I only get the files without directories.

All the files, including those in sub-directories, are copied into the target directory.

### Steps To Reproduce:
```
// webpack.mix.js
mix.copy(<source directory>, <target directory>);

// console
npm run dev
```

**Comment by JeffreyWay** [comment]
This should be filed in the Laravel Mix repo.

But the answer is because Mix flattens the directory structure when copying. You can disabled this by passing `false` as the third argument (flatten = false) to the `mix.copy()` method.
