### ISSUE TITLE
Get all available translations from translator

### ISSUE THREAD

**Issue by antoine-pous** [laravel/framework#17572]
- Laravel Version: 5.3
- PHP Version: 7.0.9

### Description:
Sometime for debugging reason or for accessibility from API i need to get all translations available from one or all languages files.

Add `Lang::getAll($group, $locale);` method would be pretty usefull.

Currently i use my own method, but this should be natively supported.

**Comment by themsaid** [comment]
thank you for your suggestion, feel free to open a PR if you want :)
