### ISSUE TITLE
[5.4] Eager loading on other than default connection

### ISSUE THREAD

**Issue by reno1979** [laravel/framework#17579]
- Laravel Version: 5.4 
- PHP Version: 7.1
- Database Driver & Version: Mysql 

We have multiple databases, all with the same tables. 
Retrieving related data of an eloquent instance, now works great in 5.4. 
But when using eager loading, it combines data from the given other connection and the default connection. 

### Steps To Reproduce:
```
$product = \App\Product::on('otherConnection')->getModel()->with('categories','brand')->first();
// the result is the productdata from connection 'otherConnection
// and the categories plus brand data is retrieved from the default connected database.
```

What kind of works is this 
```
$product = Product::on('otherConnection')->getModel()->join('brands','brands.id','=', 'products.brand_id')->select(['brands.name AS brand','products.*'])->first();

```

But this lacks the nested Model data in its response, and its a lot harder when dealing with pivot tables

**Comment by tomschlick** [comment]
Is this really on 5.3? or is it 5.4?

I ask because there seems to be a lot of issues related to caching of connections in 5.4 and I wonder if this is related.

**Comment by reno1979** [comment]
@tomschlick 

I just updated to 5.4 and our manual test still fails to combine data from the requested connection.

**Comment by themsaid** [comment]
From the docs:

> `User::on('example')->with('posts');`
> Eloquent will query the posts table on the example connection instead of the default database connection. If you want to read the posts relationship from the default connection, you should to explicitly set the model's connection to your application's default connection.

If you set the connection of the related models explicitly to read from a connection It'll always read from that connection no matter what connection you set while calling `on()`. 

@reno1979 please make sure you don't specify a connection on those related models to make it work.

**Comment by themsaid** [comment]
The behaviour you described originally was in 5.3, it has changed in 5.4 and your case should work only if you don't set a specific connection on the models.

**Comment by reno1979** [comment]
@themsaid 

Thank you for looking in to this. The models I use to test with do not have a $connection specified. 

And with 5.4 the relations are working fine, so 

```
\App\Product::on('otherConnection')->find(1)->categories()
```
 and 
```
\App\Product::on('otherConnection')->find(1)->brand();
``` 

Deliver the data we expext from the otherConnection database. (Thank you for this) :) 

But eager loading does not seem to work, I'm still getting data from the default database.

**Comment by hawkleaf** [comment]
I've actually stumbled across this issue aswell, I've set connection properties on both models to their corresponding databases and I'm not using the on() chain at all.
`$dataloggers = Datalogger::with('channels')->get();`
Where datalogger is getting from a different connection than the default (like specified on the model itself) and channels is should be retreiving from the default connection as no connection is specified on it's model.
https://puu.sh/tJy70/6c7f74c5e6.png

**Comment by hawkleaf** [comment]
I just tinkered around with my code and this seems to work just fine, 
`
$dataloggers = Datalogger::get()->each(function ($datalogger) {
            return $datalogger->on('mysql')->with('channels');
        });
`

I'm by no means an expert so I can't go snooping around in the source code for answers as I don't really understand what is happening.

**Comment by reno1979** [comment]
@hawkleaf Thank you for testing. Your example however is not exactly what I mean with eager loading on a different connection.

We will do some additional tests in tinker.

**Comment by IkRookG** [comment]
I've tried to replicate this issue myself and I've run into the same problem as @reno1979. When I use the `with('relation')` function it returns data from my default connection, instead of my specified connection. When I exclude the `with('relation')` functionality it does give me the proper database data. 

-----------
@hawkleaf 

> I've set connection properties on both models to their corresponding database ...

This unfortunately would not work for models that need to get information from multiple databases (for comparing i.e.) and thus a statically set connection is not viable here.

> $dataloggers = Datalogger::get()->each(function ($datalogger) { return $datalogger->on('mysql')->with('channels'); });

This code might indeed work, but it is not following the principles of eager loading unfortunately, as you use more than 1 query. Not really optimal to use with importing lots of data.

**Comment by hawkleaf** [comment]
Alright, this means that the behaviour I'm getting is definately not correct right? As in, when fixed my code will work after a fix?

**Comment by reno1979** [comment]
@themsaid 

Did you find the time testing this issue? I am 'eager' to know ;)

**Comment by themsaid** [comment]
`App\User::on('mysql2')->with('posts')->first()` seems to bring users and posts from `mysql2` connection to me. Can you upgrade your laravel installation to latest 5.4 and test again? @reno1979

**Comment by IkRookG** [comment]
It works properly for me now, thanks for the fix. @themsaid
