### ISSUE TITLE
Class session does not exist

### ISSUE THREAD

**Issue by mariosvasiliou** [laravel/framework#17583]
- Laravel Version: 5.3.30
- PHP Version:  v7.0.11
- Database Driver & Version: MySQL 5.6.17

### Description:
Hello Guys,
I am going crazy and i need desperate your help.
I have upgraded to laravel 5.3 from 5.2 manually.
I followed all the procedure and im getting a strange error that i cannot find anywhere why...

> Uncaught ReflectionException: Class session does not exist in \vendor\laravel\framework\src\Illuminate\Container\Container.php:749

Is driving me crazy....
Anyone knows how to fix that?
Thank you in advance

### Steps To Reproduce:
Update laravel from 5.2 to 5.3.
Composer update...
Any artisan command...

**Comment by shawnlindstrom** [comment]
Check your config files in app/config to ensure each is formatted correctly. Usually missing a trailing comma.

**Comment by mariosvasiliou** [comment]
I found the solution after a day ..it was not a trailing comma or something...
The problem was the encrypt flag  in session.php config file.
I set it to false and everything works ok.
>     'encrypt' => false,
I suppose that was cause because the cipher i was using was not supported in php 7 or new laravel and when it was trying to encrypt session to boot framework was failing ...
So for reference in the future...
Change flag to false.....Clear session files...Add support package for mcrypt (see Laravel documentation) and change your data and will be OK...

Thanks anyways...

**Comment by Adesubomi** [comment]
Someone might find this useful,
I was trying return `csrf_token` from a config array in **config/app.php** file.
I resorted to using a helper function instead

**Comment by mariosvasiliou** [comment]
Also for future reference...I noticed that if you use helper functions (Laravel or your own) in config files then you have the above error....

**Comment by Lewiscowles1986** [comment]
@mariosvasiliou 
> if you use helper functions (Laravel or your own) in config files then you have the above error....

Is there a way around that?

**Comment by pablorsk** [comment]
Another possible solution. On `config/app.php` check if you have have `Illuminate\Session\SessionServiceProvider::class` on `providers` section.

**Comment by Raja-Omer-Mustafa** [comment]
solution that work for me is composer update and php artisan cache:clear && php artisan route:clear && php artisan config:clear && php artisan view:clear hope this may help someone

**Comment by rezasrk** [comment]
hi 
tanks @Raja-Omer-Mustafa 
I use  this command     **php artisan chache:clear**      and solved

**Comment by ayahaceh** [comment]
> hi tanks @Raja-Omer-Mustafa I use this command **php artisan cache:clear** and solved

You saved my time!

**Comment by zakblacki** [comment]
This also can occurs because of laravel version if you have downgraded for example from 10 to 8

**Comment by hashimaziz1** [comment]
In my case this was happening after I switched to a Git branch that's still on an older version of Laravel. Doing `composer install` (*not* `composer upgrade`, which will update the dependencies in your lockfile and potentially break your app) and `npm run dev` was enough to solve the issue for me.
