### ISSUE TITLE
ip_address and user_agent columns in sessions table always NULL since upgrade to 5.4.*

### ISSUE THREAD

**Issue by haheute** [laravel/framework#17581]
- Laravel Version: 5.4.4
- PHP Version: 7.1.1
- Database Driver & Version: mysql  Ver 15.1 Distrib 10.1.21-MariaDB, for Linux (x86_64) using readline 5.1

### Description:
Since the upgrade to laravel 5.4.*, the `ip_address` and `user_agent` columns in my `sessions` table are only filled with `null`. I did not change any code of my application or database or php configuration. I don't know which part of laravel is responsible for inserting these values, so I don't know where to search the reason for this beaviour.

I have also asked this question on [stackoverflow](http://stackoverflow.com/questions/41855878).

Thanks for any help.

### Steps To Reproduce:

Upgrade from 5.3.* to 5.4.* and look into the sessions table.

**Comment by devcircus** [comment]
Confirmed. #17584 should fix
