### ISSUE TITLE
[5.4] Blade @extends() new ordering system harder to reason about

### ISSUE THREAD

**Issue by mjason4x** [laravel/framework#17592]
- Laravel Version: 5.4.4
- PHP Version: 7.1.0
- Database Driver & Version: MySQL 5.7.17

### Description:

The new blade @extends() ordering system introduced in version 5.4 has made it harder to reason about view files and also made it almost impossible (to my knowledge) to implement a few hierarchical functionalities enjoyed in previous versions...

### Steps To Reproduce:

Using this setup

###### global-layout.blade.php
```html
<html>
<head>
@stack('scripts')
@section('scripts')@show
</head>
<body>

</body>
</html>
```

###### app-layout.blade.php
```html
@extends('global-layout')

@push('scripts')
<script src="/js/jquery.js"></script>
@endpush

@section('scripts')
<script src="js/jquery.js"></script>
@endsection
```

###### some-view.blade.php
```html
@extends('app-layout')

@push('scripts')
<script src="js/some-view.js"></script>
@endpush

@section('scripts')
    @parent
    <script src="js/some-view.js"></script>
@endsection
```

##### Using the @stack directive,

Expected 'jquery' to render before 'some-view.js' 
but  'some-view.js' is rendered before 'jquery'

Reason: Child view executed first before parent view (extended view)

##### Using the @section method

This should work right?? But NO.. it doesn't but instead displays a `##parent-placeholder-3880b9413975c06b32c01851bbe852c1198bf003##` in the HTML output...

The reason being that Calling the `@parent` directive would try to load the section content of the extended layout.. but this doesn't exist as the child view is executed first before the parent view..

**Comment by devcircus** [comment]
See #17541 where this was discussed in detail. Taylor also spoke directly to this in the #internals slack channel yesterday.

**Comment by sisve** [comment]
The `##parent-placeholder-3880b9413975c06b32c01851bbe852c1198bf003##` should not be shwon in the html output. Can you verify that you really are on 5.4.4 and try a `php artisan view:clear`?

**Comment by mjason4x** [comment]
@sisve @devcircus  

Yea.. I do understand the ordering and it seems right since when the view is compiled the @extends is moved to the bottom of the generated php file....

But my issue is how do I achieve what I want using the arrangement above.... in a sane way....

** Thought ** I am thinking of creating a custom @prepends() directive that prepends the content to the stack instead.

**Comment by tylercubell** [comment]
I copied the [Blade Template Inheritance example](https://laravel.com/docs/5.4/blade#template-inheritance) verbatim and I'm also getting `##parent-placeholder-...##` in the output.

`php artisan view:clear` seems to allow the template to be rendered correctly but subsequent requests cause `##parent-placeholder-...##`. to come back.

**Comment by GrahamCampbell** [comment]
There are no plans to change the new behaviour. It's already been discussed at length.

**Comment by tylercubell** [comment]
@GrahamCampbell Forget what's been said previously for a moment -- are you saying that the official example in the documentation should produce placeholder garbage as the intended result?

I'm getting:

```
##parent-placeholder-19bd1503d9bad449304cc6b4e977b74bac6cc771##
This is appended to the master sidebar.

This is my body content.
```

**Comment by GrahamCampbell** [comment]
Errrr. Ping @taylorotwell.

**Comment by morrelinko** [comment]
@GrahamCampbell @taylorotwell Just updated to version 5.4.6 of the framework and I am still getting the ##parent-placeholder--xxxx##

**Comment by morrelinko** [comment]
Also, if you have discussed this new behavior at length, can you suggest the way to go forward in achieving  what i want?

I have a `template.blade.php` layout and a few other layouts that extends the template layout...  `app.blade.php`  and `auth.blade.php`.... controller views extends from each of these say `login.blade.php` extends `auth.blade.php`.... I don't really care about the execution order that was discussed... But content inserted in the auth layout have to be rendered before those defined in the login view extending the auth layout...

So how to go about this? 

Asked this in forums and no response....

**Comment by mjason4x** [comment]
Also, if you have discussed this new behavior at length, can you suggest the way to go forward in achieving what i want?

I have a `template.blade.php` layout and a few other layouts... `app.blade.php` layout and `auth.blade.php` layouts that extend the template layout.... controller views extends from each of these say `login.blade.php` extends `auth.blade.php`.... I don't really care about the execution order that was discussed... In my situation, content inserted in the auth layout have to be rendered before those defined in the login view extending the auth layout...

So how to go about this?

Asked this in forums and no response....

**Comment by tylercubell** [comment]
@mjason4x Throw the baby out with the bathwater and switch to [Twig](https://github.com/rcrowe/TwigBridge). I'm not going to waste any more time with this when there exists a viable alternative that works. Sometimes it's better in the long run to cut your losses.

**Comment by sisve** [comment]
@morrelinko Did you `php artisan view:clear` after upgrading Laravel version?

**Comment by mjason4x** [comment]
@sisve @taylorotwell @GrahamCampbell 

Cleared it all yet no way forward... ** NOTE ** already upgraded to 5.4.6
I had to duplicate my global layout just to move forward.. 

It seems when you discussed this new behavior, multiple nested layouts, @parent directive and PARENT  -> CHILD order content injection were not considered... 

Makes no logical sense why core team thinks content from child views should display first... 

I would really like to see the thread where this was discussed to understand the reasoning behind it, probably they also discussed a way out of my issue...

**Comment by themsaid** [comment]
I can't replicate this placeholder thing on latest 5.4, followed the steps to replicate stated in the original issue and `@parent` successfully displayed the content of the parent section.

Replacing the scripts loaded with some strings to be able to debug, the output I get is:

```
child stack content
parent stack content
parent section content
child section content
```

**Comment by sisve** [comment]
@themsaid I think the parent placeholders are from old cached 5.4.0 views, and should be fixed with an upgrade to 5.4.1 and a `php artisan view:clear`.

@mjason4x The view:clear would fix the "##parent-placeholder--xxxx##" issue mentioned earlier, not anything related to the order of the output.

Views are rendered before layouts so they can push content into stacks and sections that are contained within the layout. Imagine that the layout is executed first; the @stack would be empty when rendered, before the @push has executed by the view.

The blade-examples in this issue use several chained/nested layouts which further complicates the issue, they are all executed in reverse order so that the topmost is executed last and have the full @stack result.

**Comment by themsaid** [comment]
If you think that the starting point of a view render is the top most parent then you'll find this as a bug, however the starting point is the view being rendered, in this case it's `some-view.blade.php` not `global-layout.blade.php`.

**Comment by themsaid** [comment]
The `@push` issue is fixed a few days ago, I've submitted a PR to introduce a `@reversestack` that people who prefer the 5.3 behaviour can use. https://github.com/laravel/framework/pull/17675
