### ISSUE TITLE
Need documentation for upgrade 5.4 tests

### ISSUE THREAD

**Issue by webmake** [laravel/framework#17595]
- Laravel Version: 5.4

### Description:
There is no mention about test functions deletion in laravel 5.4 [doc](https://laravel.com/docs/5.4/upgrade#upgrade-5.3.0).
Now all tests containing `seeJson`, `seeStatusCode` and other methods is failing due this [PR](https://github.com/laravel/framework/pull/16667) with this commit 
https://github.com/laravel/framework/pull/16667/commits/bbf280a9c58c59fc6dd5723cdaafc3c3ba130162

How can I change my tests according 5.4 laravel? Or was it deleted accidentally?

**Comment by GrahamCampbell** [comment]
This is documented.

![image](https://cloud.githubusercontent.com/assets/2829600/22369030/925b8fd4-e481-11e6-8572-63a4f0d36129.png)

**Comment by webmake** [comment]
Thanks a lot, I didn't even tried to look at kit source :) Seems all methods are there
