### ISSUE TITLE
[5.4] event:generate throws fatal error if events/listeners already exist

### ISSUE THREAD

**Issue by rawcreative** [laravel/framework#17599]
- Laravel Version: 5.4.5
- PHP Version: 7.0.11
- Database Driver & Version: MariaDB 10.1.16

### Description:

After updating to 5.4 I added a new event and listener to my app, when I went to run ```artisan event:generate``` it throws a fatal error saying 'Cannot declare class App\Listeners\SettingUpdated because the name is already in use', which happens to be the first event in my listeners array. Thinking there might've just been an issue with the upgrade, I tested on a fresh 5.4 install with the same results.

### Steps To Reproduce:
1. Create fresh install (or use existing app)
2. Add an event & listener to ```$listeners``` in EventServiceProvider
3. Run ```artisan event:generate``` to generate events & listeners then run again (same behavior whether new events are added or not).

**Comment by devcircus** [comment]
I tried to reproduce on a fresh 5.45 install to no avail. Everything works as it should.

**Comment by rawcreative** [comment]
@devcircus try using the values below, I just tried again with another fresh install and things worked ok just using the default boilerplate that is there, but then if I switch to the values below it'll run once and then start throwing errors everytime.

```php
 protected $listen = [
        'App\Events\SettingUpdated' => [
            'App\Listeners\SettingUpdated',
        ],
        'App\Events\SettingCreated' => [
            'App\Listeners\SettingCreated',
        ],
         'App\Events\SettingDeleted' => [
            'App\Listeners\SettingDeleted',
        ]
    ];
```

**Comment by GrahamCampbell** [comment]
Can't replicate.

**Comment by GrahamCampbell** [comment]
This will happen because you have a typo in the filename of one of your php files, or a typo in a class name in the definition. Unrelated to the framework. It happens because the typo makes your code violate psr-4, so the autoloader requires a file twice.

**Comment by rawcreative** [comment]
@GrahamCampbell Not sure how it can be unrelated to the framework, if the framework is the one creating the files with the original event:generate command.

**Comment by rawcreative** [comment]
I just tried a fresh install on two different machines and get the same behavior on both, the only value I changed from a default install is the name of the listener. Here's a < 30s recording showing this. The error happens anytime the event and listener share the same name. 

http://jmp.sh/J7UuQzl
