### ISSUE TITLE
[5.4] Validation with 'email' or 'date' is now also 'required'?

### ISSUE THREAD

**Issue by patrickbergman** [laravel/framework#17609]
- Laravel Version: 5.4.5
- PHP Version: 7.0.11
- Database Driver & Version: MySQL 5.7.16

### Description:
When validating form input with the validation rule 'email' or 'date', the validation won't allow empty fields while 'required' is not a validation option.

'email' => 'email'

and 

'birthday' => 'date'

are giving errors when the fields are empty

### Steps To Reproduce:
1) Create a form with a field for either an emailaddress or date
2) validate with aformentioned rules
3) See error that an email needs to be a valid emailaddress or the error that the datefield needs to be a valid date.

**Comment by brunogaspar** [comment]
I believe it's related to #17558

**Comment by patrickbergman** [comment]
Thanks for the useful answer. I believe this will solve it temporary, but still a suggestion to 'fix' (can't come up with the appropriate word, but I hope you know what I mean) the issue.
