### ISSUE TITLE
Collection->random($n) shouldn't throw exception when asking for more

### ISSUE THREAD

**Issue by tmaly1980** [laravel/framework#17605]
I am trying to get a random subset of records via $this->ModelName->all()->random(3), and if there are less than what I ask for, I get an exception. It would make MUCH more sense IMO to take however many are actually in the database if there's less. I have to call $collection->random(min($collection->count(),3)) to work around this. Here's the error I got:

InvalidArgumentException in Collection.php line 846:
You requested 3 items, but there are only 2 items in the collection

**Comment by GrahamCampbell** [comment]
The current behaviour is fine.

**Comment by jartaud** [comment]
@tmaly1980 thanks for the min thing.
