### ISSUE TITLE
[5.4] - post_max_size of 0 throws PostTooLargeException for POST requests of any size

### ISSUE THREAD

**Issue by prurigro** [laravel/framework#17602]
- Laravel Version: 5.4.5
- PHP Version: 7.0.10
- Database Driver & Version: N/A

### Description:

Setting `post_max_size` to `0` should disable the post size limit, but `getPostMaxSize` in https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php treats it as a maximum post size of 0 bytes and throws the `PostTooLargeException` exception for POST requests of any size.

### Steps To Reproduce:

Set `post_max_size` to `0` in `php.ini` and attempt to send a POST request to trigger this check (eg: log in using Laravel's native authentication)

**Comment by GrahamCampbell** [comment]
Thanks for reporting. See https://github.com/laravel/framework/pull/17607. :)

**Comment by prurigro** [comment]
Awesome- thanks for fixing!
