### ISSUE TITLE
[5.4] - Blade @parent directive clarification

### ISSUE THREAD

**Issue by mjason4x** [laravel/framework#17601]
- Laravel Version: 5.4.4
- PHP Version: 7.1.0
- Database Driver & Version: MySQL 5.7.17

### Description:

What is the expected behavior when you call the @parent directive in a child view?????

With the new @extend parent child execution order, since the child view is executed first, which of the sections in both views in the hierarchy is considered parent section that will replace the ---parent--placeholder---?

**Comment by Marky291** [comment]
Don't think this is a new blade directive.

**Comment by GrahamCampbell** [comment]
> What is the expected behavior when you

Please ask questions on the forums.
