### ISSUE TITLE
npm run dev fails Windows OS

### ISSUE THREAD

**Issue by jagadeshanh** [laravel/framework#17608]
- Laravel Version: 5.4.6
- PHP Version: 7.0.10
- Database Driver & Version:

### Description:

npm run dev fails on fresh installation

ERROR  Failed to compile with 1 errors

This dependency was not found in node_modules:

* C:wamp64wwwhome
                 orum
ode_modules
           ue-loaderlibcomponent-normalizer

Did you forget to run npm install --save for it?                                                                                                             A                                                                   sset      Size  Chunks                    Chunk Names
       /js/app.js   1.16 MB       0  [emitted]  [big]  /js/app
mix-manifest.json  32 bytes          [emitted]

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ dev: `node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node                                                                   _modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ dev script 'node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-m                                                                   odules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_mod                                                                   ules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\wamp64\www\home\forum\npm-debug.log

### Steps To Reproduce:

Just install laravel new project
cd project
npm install
npm run dev

**Comment by JeffreyWay** [comment]
File this with the Laravel Mix repo instead.

http://github.com/jeffreyway/laravel-mix

**Comment by jagadeshanh** [comment]
Problem was not that!
When I install using CYGWIN this problem occurs,
When I install using GITBASH it works fine.
