### ISSUE TITLE
Hi Guys. Problem with new laravel 5.4

### ISSUE THREAD

**Issue by IrsyadAdl** [laravel/framework#17617]
I have installed new laravel project. So when I do php artisan. I got this error.
```
PHP Fatal error:  Allowed memory size of 2097152 bytes exhausted (tried to allocate 4096 bytes) in C:\Users\Irsyad\Code\hape\vendor\symfony\finder\Finder.php on line 70
```
I see the php.ini file by default 128MB. So I change 2048MB. But I am still got same issue. Anyone can help me ? Or have same error with me but has been solved ? Anybody ?

**Comment by manzwebdesigns** [comment]
Hi IrsyadAdl,

Did you restart your webserver after making that change?

**Comment by movingSone** [comment]
Ok so basically you probably changed on the wrong place that memory limit. If you are using "php artisan"  check the cli/php.ini. I recreated the same error and changed "memory_limit", and it worked. Just double check what php.ini file you are changing.

**Comment by IrsyadAdl** [comment]
Thanks all for the response. All has been solve. The problem is about my composer is not inheritanced by my PHP setup.

**Comment by luongvupc** [comment]
I have had the same issue, how could you resolve this problem? Please help

**Comment by luongvupc** [comment]
Hi I resolved this problem, it caused because of the unique email field, it should be set the string length, so in the default user migration file:
$table->string('email')->unique();  => $table->string('email', 100)->unique();
