### ISSUE TITLE
Token Mismatch issue with Iframes on Safari Browser Only

### ISSUE THREAD

**Issue by msherax** [laravel/framework#17615]
- Laravel Version: 5.3.28
- PHP Version:  5.6.25
- Database Driver & Version:

### Description:

Hi, i have created few forms in laravel, now i am using those forms on another site using IFrame. Those forms  works in all browsers except Safari, When i try to submit/post data in the forms, i get error
"Token Mismatch", I dont know what the issue here, csrf token is also being created and sent. This is only happening in case of safari browser. The safari version i am using is 5.1.7.

Can someone guide me that how i can get rid of this issue??

### Steps To Reproduce:
create a form and then use it via IFrame.
after form is submitted, CSRF Token Mismatch error is generated.

**Comment by GrahamCampbell** [comment]
Please ask on the forums.

**Comment by shinvdu** [comment]
I have the same issue.

**Comment by msherax** [comment]
i asked this question on the forum and got zero replies. i am unable to understand that what kind of bug it is that it works on all browsers except safari and IE.

**Comment by msherax** [comment]
However, i was able to resolve it by changing the php.ini configuration

; http://php.net/session.gc-maxlifetime
session.gc_maxlifetime=1440   

its set to 24 mins. 
i set it to 24 hours and for me it started working.
i hope it will resolve your issue.

**Comment by shinvdu** [comment]
@msherax thanks for your replay. I also get the answer, it is caused by cookie not saving on safari in iframe. 

http://stackoverflow.com/questions/408582/setting-cross-domain-cookies-in-safari

and my soluction is http://blog.csdn.net/fdipzone/article/details/43205961.

**Comment by RaiserWeb** [comment]
@shinvdu I have the same issue. I can't understand the language of your solution link. Are you aware of an English article resolving the issue?

**Comment by bahmanyaghoobi** [comment]
RaiserWeb 
You can copy the link of any page in any language and paste it in Google Translate and click the translate button. It will give you a machine translation of that page which is not as good as a human translated one, but pretty much understandable. I hope that helps.
