### ISSUE TITLE
[5.4] Cannot run Dusk tests

### ISSUE THREAD

**Issue by mnabialek** [laravel/framework#17628]
### Description:

I don't know why but I cannot run Dusk tests. I'm using docker container on Windows machine.

When running `phpunit` I'm getting:

```
PHPUnit 5.7.9 by Sebastian Bergmann and contributors.

..                                                                  2 / 2 (100%)

Time: 1.37 seconds, Memory: 10.00MB

OK (2 tests, 2 assertions)
```

so everything is fine for phpunit.

However when I run  `php artisan dusk` command. I'm getting in console:

```
dir=$(d=${0%[/\\]*}; cd "$d"; cd '../phpunit/phpunit' && pwd)

# See if we are running in Cygwin by checking for cygpath program
if command -v 'cygpath' >/dev/null 2>&1; then
        # Cygwin paths start with /cygdrive/ which will break windows PHP,
        # so we need to translate the dir path to windows format. However
        # we could be using cygwin PHP which does not require this, so we
        # test if the path to PHP starts with /cygdrive/ rather than /usr/bin
        if [[ $(which php) == /cygdrive/* ]]; then
                dir=$(cygpath -m "$dir");
        fi
fi

dir=$(echo $dir | sed 's/ /\ /g')
"${dir}/phpunit" "$@"
```

what is probably the content of `vendor/bin/phpunit` file

Edit. I see someone has exact same problem here - https://github.com/laravel/dusk/issues/50

**Comment by GrahamCampbell** [comment]
Same as https://github.com/laravel/framework/issues/17620 perhapse?

**Comment by GrahamCampbell** [comment]
Closing this since laravel/dusk is not laravel/framework. The issue tracker here is for the framework repo only. :)
