### ISSUE TITLE
After run phpunit tool, throw exception

### ISSUE THREAD

**Issue by valiknet18** [laravel/framework#17626]
- Laravel Version: 5.4.6
- PHP Version: 5.6.23
- Database Driver & Version:
mysql  Ver 15.1 Distrib 10.1.19-MariaDB,

### Description:
Hello, i have some problem. After run phpunit tool, i receive next exception
```
PHP Fatal error:  Class 'PHPUnit\Framework\TestCase' not found in /var/www/distance-learning-backend/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php on line 12
``` 
In vendor directory, isset phpunit package with this file.
![image](https://cloud.githubusercontent.com/assets/5772019/22399131/265fe9e6-e59f-11e6-9ce2-7521475c5d80.png)

**Comment by GrahamCampbell** [comment]
Your PHPUnit version is too old. You need 5.7.x for Laravel 5.4.
