### ISSUE TITLE
Error when upgrade form 5.3 to 5.4

### ISSUE THREAD

**Issue by ThunderBirdsX3** [laravel/framework#17638]
- Laravel Version: 5.4.#
- PHP Version: 7.0.10
- Database Driver & Version:

### Description:
Found this error after upgrade to 5.4, I upgrade with suggestion in Upgrade Guide.

And I try to remove folder vender/ and used cammand `composer install` but it didn't work.

Why.

```
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in C:\wamp\www\2_Work\servicedesk\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 549
Script php artisan optimize handling the post-update-cmd event returned with error code 255

```

**Comment by bbashy** [comment]
Need more than 128MB PHP memory by the looks of it.

Try updating it to 256 or 512 in php.ini

**Comment by GrahamCampbell** [comment]
Looks more like an infinite loop.

**Comment by ThunderBirdsX3** [comment]
@bbashy I already try it.

**Comment by movingSone** [comment]
Have you tried using as  development mode, without WAMP?

**Comment by themsaid** [comment]
@ThunderBirdsX3 any progress?

**Comment by kariolos** [comment]
Looks like an infinite loop. 
Check if there is a var without double quotes or lower/upper case error

**Comment by eberharterm** [comment]
I'm getting the same issue, but I'm on PHP 7.1 and Valet

**Comment by DanielHudson** [comment]
In my case I had a missing comma after a service provider, in the config/app.php providers array.

**Comment by thachp** [comment]
I had similar problem after upgrading to Laravel 5.4.  I had a missing ::class and a comma in config/app.php
