### ISSUE TITLE
 TransformsRequest doesn't apply to Request class

### ISSUE THREAD

**Issue by andershagbard** [laravel/framework#17635]
- Laravel Version: 5.4
- PHP Version: 7.1

### Description:
Laravel 5.4 added the following middleware to the global stack:
```
\App\Http\Middleware\TrimStrings::class
\Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
```
But the middleware doesn't apply changes to the Request class. I am not sure if this is intended behavior, but it is definitely weird.
```
// SomeController@store
public function store(\App\Http\Requests\SomeRequest $request)
{
    $request->input('string'); // 'untrimmed         '
    request('string') // 'untrimmed'
}
```
Is this intended behavior?

**Comment by andershagbard** [comment]
Narrowed this down to my own Request handlers. If i use Illuminate\Http\Request it works. Closing this issue for now.

**Comment by sisve** [comment]
This sounds related to https://github.com/laravel/framework/issues/10791 - the form-request is copied from the original Request early in the lifecycle, and changes to either instance does not affect the other.

**Comment by andershagbard** [comment]
As sisve mentioned, this issue is old and is related to #10791. Fixed it by adding this function to my request:
```
public function all()
{
    $this->merge( $this->request->all() );

    return parent::all();
}
```

**Comment by sisve** [comment]
@andershagbard You probably meant https://github.com/laravel/framework/commit/9a1c5f3ab4ed75279ef3d09cf5dc9ded2578c58d but I do not see the relevance to this issue.

Both this issue, and _all_ the related (linked and not linked), indicate that people expect middlewares that execute on a Request to also affect the generated FormRequest object.
