### ISSUE TITLE
[5.4] Database setFetchMode not working

### ISSUE THREAD

**Issue by youkyll** [laravel/framework#17639]
- Laravel Version: 5.4
- PHP Version: 5.6

### Description:
Illuminate\Database\Capsule\Manager SetFetchMode method has not working.
but version 5.3 has working.

I consider the commit below causes this bug.
https://github.com/laravel/framework/commit/7ddb6fe9780459a2f02ea7e246dc7f644bf7ea58

### Steps To Reproduce:

```php

    use Illuminate\Database\Capsule\Manager as Capsule;

    $capsule = new Capsule;

    $capsule->addConnection(
      // database setting array
    );

    $capsule->setFetchMode(PDO::FETCH_ASSOC);
    $db = $capsule->getConnection();
```

**Comment by bbashy** [comment]
You mean this?


> #### Fetch Mode
> Laravel no longer includes the ability to customise the PDO "fetch mode" from your configuration files. Instead, PDO::FETCH_OBJ is always used. If you will still like to customise the fetch mode for your application you may listen for the new Illuminate\Database\Events\StatementPrepared event:
```
Event::listen(StatementPrepared::class, function ($event) {
    $event->statement->setFetchMode(...);
});
```
Ref: https://laravel.com/docs/5.4/upgrade

**Comment by mariomka** [comment]
Related #17557

**Comment by diagowang** [comment]
Event::listen(StatementPrepared::class, function ($event) {
    $event->statement->setFetchMode(...);
});

$queryBuilder->get()->all();//return PDO FETCH MODEL

**Comment by connor11528** [comment]
Will that event listener apply to all queries? Is there a way to set the fetch mode for only certain queries?

Thank you!
