### ISSUE TITLE
[5.4] Reset password loses old input

### ISSUE THREAD

**Issue by tylercubell** [laravel/framework#17644]
- Laravel Version: 5.4.0
- PHP Version: 7.1
- Database Driver & Version: N/A

### Description:

Old input data isn't being preserved.

[`SendsPasswordResetEmails@sendResetLinkFailedResponse`](https://github.com/laravel/framework/blob/7212b1e9620c36bf806e444f6931cf5f379c68ff/src/Illuminate/Foundation/Auth/SendsPasswordResetEmails.php#L60) should match [`ResetsPasswords@sendResetFailedResponse`](https://github.com/laravel/framework/blob/7212b1e9620c36bf806e444f6931cf5f379c68ff/src/Illuminate/Foundation/Auth/ResetsPasswords.php#L130) and use:

```php
return redirect()->back()
            ->withInput($request->only('email'))
            ->withErrors(['email' => trans($response)]);
```

instead of this:

```php
return back()->withErrors(
    ['email' => trans($response)]
);
```

Also, I don't understand how [`ResetsPasswords@showResetForm`](https://github.com/laravel/framework/blob/7212b1e9620c36bf806e444f6931cf5f379c68ff/src/Illuminate/Foundation/Auth/ResetsPasswords.php#L23) gets `email` when [the route](https://github.com/laravel/framework/blob/f82abab6a3e50c17082ec399170894ae63c64e1a/src/Illuminate/Routing/Router.php#L1008) looks like:

```php
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
```
```php
public function showResetForm(Request $request, $token = null)
{
    return view('auth.passwords.reset')->with(
        ['token' => $token, 'email' => $request->email]
    );
}
```

Also, `ForgotPasswordController` should have:

```php
protected $redirectTo = '/home';
```

since it also redirects like `LoginController` and `RegisterController`.

Also, the [password reset email](https://github.com/laravel/framework/blob/0435cfcf171908432d88e447fe4021998e515b9f/src/Illuminate/Notifications/resources/views/email.blade.php) escapes `<br>` after `Regards,`.

I don't know exactly what's happening with #17499 so I didn't make a PR for this.

**Comment by tillkruss** [comment]
If this is merged, I'll adjust #17499.

**Comment by jerguslejko** [comment]
It's usually better to submit these things as a PR.

Also, you can access query string params through the request object.

```
/password/reset/XXXXX?email=hello 
```

can be accessed like this:

```php
$request->email
```

**Comment by jafar690** [comment]
@tylercubell just overide the `sendResetLinkFailedResponse` function in the `ForgotPasswordController` like this 

```
    /**
     * Get the response for a failed password reset link.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  string  $response
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Http\JsonResponse
     */
    protected function sendResetLinkFailedResponse(Request $request, $response)
    {
        return back()->withErrors(
            ['email' => trans($response)]
        )->withInput(\Input::all());
    }
```
