### ISSUE TITLE
[5.4] Mix manifest file path error.

### ISSUE THREAD

**Issue by youmingdot** [laravel/framework#17647]
- Laravel Version: 5.4.6

### Description:
Mix manifest file `mix-manifest.json` created at base path of project, But the mix function find it at public path (helpers.php line 566). As the result of it, the file never be found.

In addition, the mix function use the source map by `mix-manifest.json` wasn't right, the `mix-manifest.json` will include the name of public directory which is not need in HTML rendering.

**Comment by JeffreyWay** [comment]
This is a Laravel Mix question. Please elaborate here: https://github.com/JeffreyWay/laravel-mix/issues/237
