### ISSUE TITLE
File:makeDirectory() setting permission not working [5.3]

### ISSUE THREAD

**Issue by ezekel** [laravel/framework#17658]
I have this code File::makeDirectory(public_path('uploadimg', 0777, true)); but when I upload it says, permission denied cannot write etc ...

Thank you in advance..

**Comment by movingSone** [comment]
Hi, @ezekel . Check permissions of the parent folder meaning "public"  you don't have permission to write there

**Comment by datashaman** [comment]
And consider using this instead: https://laravel.com/docs/5.4/filesystem#the-public-disk
