### ISSUE TITLE
[5.4] Customizing the mail components isn't possible

### ISSUE THREAD

**Issue by hohl** [laravel/framework#17650]
- Laravel Version: 5.4.6
- PHP Version: 7.1.0

### Description:

I followed the [Customizing the components](https://laravel.com/docs/5.4/mail#customizing-the-components) guide in the [Mail](https://laravel.com/docs/5.4/mail) documentation page of Laravel 5.4. However, all changes I made to the CSS and the components are ignored.

### Steps To Reproduce:

Run `php artisan vendor:publish --tag=laravel-mail` as described in the documentation and change the generate files in `resources\view\vendor\mail` and try sending mails. As you will see, nothing changed, so I guess it still uses the original sources. (And yes, I also tried `view:clear`.)

**Comment by themsaid** [comment]
hmmm Can't replicate, when I publish the assets and make changes to any of the HTML files the changes reflect on emails being sent.

Test on a fresh laravel installation, say using the password reset email.

**Comment by hohl** [comment]
Well, that's strange. I'll give it a try and if I can reproduce that with a clean project, I'll share it of course.

**Comment by hohl** [comment]
Are you able to changes properties in the CSS files too? Like font family?

**Comment by hohl** [comment]
Doh! I tried creating a new blank project and it worked, of course. Then I checked the upgrade guide again and just saw that I missed the markdown config part. Now it works. Sorry for bothering you!

**Comment by hohl** [comment]
But the plain-text counterparts of each mail still contains markdown tags. Just curios, is this the intended behavior?
