### ISSUE TITLE
[5.4] role middleware example has error

### ISSUE THREAD

**Issue by w1n78** [laravel/framework#17657]
- Laravel Version: 5.4.5
- PHP Version: 7.1.1
- Database Driver & Version: MySQL 5.7.16

### Description:
the middleware parameter example found in https://laravel.com/docs/5.4/middleware#middleware-parameters is generating an error.

```
Type error: Too few arguments to function App\Http\Middleware\RoleMiddleware::handle(), 2 passed in /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php on line 148 and exactly 3 expected
```

### Steps To Reproduce:
copy and paste the code to create a new middleware class. add it to kernel.php. run any page and it will generate the error.

**Comment by themsaid** [comment]
You need to provide 1 parameter exactly as in the docs:

```
->middleware('role:editor')
```

you can't do:

```
->middleware('role')
```

**Comment by w1n78** [comment]
@themsaid the thing is as soon as I add it to kernel, I get the error. I have yet to even use the middleware anywhere.

**Comment by themsaid** [comment]
How do you add it to Kernel?

**Comment by w1n78** [comment]
\App\Http\Middleware\RoleMiddleware::class,

It worked in previous versions of laravel now it just gives me an error. I even did a fresh empty project, create a new middleware, then add it to kernel. Haven't used it yet just get the error.  Do I not longer need to add to kernel?

**Comment by themsaid** [comment]
Looks like you've added it to the global middleware or web middleware groups, it won't work since it requires a parameter to be given.

**Comment by w1n78** [comment]
Yes I added it there. That's where I had it in the past and the examples I've seen also done it that way. Is it no longer necessary for it to be part of the kernel?

**Comment by w1n78** [comment]
i just removed it from the kernel. when i try to use it in route it gives me this error

```
Call to a member function middleware() on string
```

i've been at this for days. not sure why it's not working like it did before. only difference is laravel 5.4. i checked the Pipeline file to see if any changes. there was a commit called clean up but i'm not familiar with the class to trace how the changes affected the old way of it doing things.

**Comment by w1n78** [comment]
@themsaid so what do I need to do? It used to work. I may end up creating middlewares for each role so I don't have to pass a parameter. I don't want to do that because it's not how it's supposed to be. But until someone can show me that this works in 5.4 I it's my only solution. Could you open the issue again? I don't believe it's solved. Thanks

**Comment by themsaid** [comment]
> Looks like you've added it to the global middleware or web middleware groups, it won't work since it requires a parameter to be given.

You need to register the middleware in the `$routeMiddleware` and then use it in your routes file as you wish, you can't use it as a global middleware because you have to pass a role.

**Comment by w1n78** [comment]
@themsaid you sir are awesome! i feel embarrassed. i can't believe that i missed it lol. thank you very much. you are correct, i had it in the global. geez, so noob of me. thanks again.

**Comment by themsaid** [comment]
No worries :)
