### ISSUE TITLE
[issue] Manual login failed on laravel 5.3

### ISSUE THREAD

**Issue by gbenga504** [laravel/framework#17659]
- Laravel Version: #.#.#5.3
- PHP Version: 7
- Database Driver & Version:

### Description:
I am having problems manually login admins after registering them.. First i get a \APP\Admin not found in the eloquentprovider.php file which i resolved by editing the laravel code and i also get an error in the same file which fails probably because Query() is not attached to the model.... Is there a bug with multi auth in laravel 5.3

**Comment by lioannou** [comment]
Are you sure it is `\APP\Admin` and not `\App\Admin`. Sounds like you might have your config file incorrectly set somewhere.

This sounds like an issue for the forums though - not for here.
