### ISSUE TITLE
[5.3] Attaching file to array element in test does not set $test = true

### ISSUE THREAD

**Issue by nowak-ninja** [laravel/framework#17665]
- Laravel Version: 5.3.29
- PHP Version: 7.0.13
- Database Driver & Version: mysql, 5.7

### Description:
I am writing tests for files upload. I am using `attach()` method to send files with request.

### Steps To Reproduce:
When I attach a single file to non-array element:

`$this->attach($file, 'file');`

the resulting `UploadedFile` in controller has parameter `$test = true`, which is desirable:

`Illuminate\Http\UploadedFile Object
(
    [test:Symfony\Component\HttpFoundation\File\UploadedFile:private] => 1
    [originalName:Symfony\Component\HttpFoundation\File\UploadedFile:private] => valid-image.jpg
    [mimeType:Symfony\Component\HttpFoundation\File\UploadedFile:private] => application/octet-stream
    [size:Symfony\Component\HttpFoundation\File\UploadedFile:private] => 87150
    [error:Symfony\Component\HttpFoundation\File\UploadedFile:private] => 0
    [pathName:SplFileInfo:private] => /tmp/b7286b1a286aeb066e727f846cbec091b8e2a057.jpg
    [fileName:SplFileInfo:private] => b7286b1a286aeb066e727f846cbec091b8e2a057.jpg
)`

In case when I want to send multiple files in request using array `files[]` element:

`$this->attach([$file], 'files[]');`

the resulting element in array: `$request->file('files')` has `$test = false`:

`Illuminate\Http\UploadedFile Object
(
    [test:Symfony\Component\HttpFoundation\File\UploadedFile:private] => 0
    [originalName:Symfony\Component\HttpFoundation\File\UploadedFile:private] => valid-image.jpg
    [mimeType:Symfony\Component\HttpFoundation\File\UploadedFile:private] => application/octet-stream
    [size:Symfony\Component\HttpFoundation\File\UploadedFile:private] => 87150
    [error:Symfony\Component\HttpFoundation\File\UploadedFile:private] => 0
    [pathName:SplFileInfo:private] => /tmp/0bea2e8e6eb51d983fa7a03a25be60fbb17ccc56.jpg
    [fileName:SplFileInfo:private] => 0bea2e8e6eb51d983fa7a03a25be60fbb17ccc56.jpg
)`

Even if I prepare UploadedFile object and use it in test with $test set to true:

`$uploadedFile = new \Illuminate\Http\UploadedFile($file, $fileName, 'image/jpeg', null, null, true);`

the result contains `$test = false`:

`Illuminate\Http\UploadedFile Object
(
    [test:Symfony\Component\HttpFoundation\File\UploadedFile:private] => 0
    [originalName:Symfony\Component\HttpFoundation\File\UploadedFile:private] => valid-image.jpg
    [mimeType:Symfony\Component\HttpFoundation\File\UploadedFile:private] => application/octet-stream
    [size:Symfony\Component\HttpFoundation\File\UploadedFile:private] => 87150
    [error:Symfony\Component\HttpFoundation\File\UploadedFile:private] => 0
    [pathName:SplFileInfo:private] => /tmp/9932754c2951fe092590567d43d41bac38ec7d47.jpg
    [fileName:SplFileInfo:private] => 9932754c2951fe092590567d43d41bac38ec7d47.jpg
)`

Also, the `Content-Type` is being changed to `application/octet-stream`.

Am I doing the something wrong? How to properly test multiple files upload?

**Comment by GrahamCampbell** [comment]
Probably best to ask on the forums please. :)
