### ISSUE TITLE
[5.4] MySQL Charset

### ISSUE THREAD

**Issue by nueko** [laravel/framework#17673]
- Laravel Version: 5.4.3
- PHP Version:7.0
- Database Driver & Version: MariaDB 10.1

### Description:
utf8mb4 is up to 4 bytes, 4 * 255 (default length of migration string) exceed the 767.
current solution is change the `utf8mb4_unicode_ci` collation to `utf8_unicode_ci` and 
`utf8mb4` charset to `utf8`, thanks.
```
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `password_resets` add index `password_resets_email_index`(`email`))
```

### Steps To Reproduce:
```sh
php artisan migrate
```

**Comment by devcircus** [comment]
see issue #17508

**Comment by nueko** [comment]
Thanks @devcircus,
