### ISSUE TITLE
[5.4] Blade's @parent won't work if @section name is defined between double quotes

### ISSUE THREAD

**Issue by dvlpp** [laravel/framework#17670]
- Laravel Version: 5.4.6
- PHP Version: 7.0
- Database Driver & Version: N/A

### Description:
Oddly, the `@parent` Blade directive won't work (meaning parent placeholder remains) if the `@section` directive is defined with double quotes. 

So this code works:

```
@section('header')
    @parent
    header
@endsection
```

And this one don't:

```
@section("header")
    @parent
    header
@endsection
```

Seems that the quotes make a difference in the `ManagesLayouts::$parentPlaceholder` array.

### Steps To Reproduce:

Just create a layout with some `@section`  and let it be extended by a view, and try to put single and double quotes around its name.

**Comment by themsaid** [comment]
Thank you, PR submitted with a fix https://github.com/laravel/framework/pull/17677
