### ISSUE TITLE
[5.4][Eloquent]Incorrect key string if primary key is not "id" 

### ISSUE THREAD

**Issue by andrewfreddin** [laravel/framework#17674]
- Laravel Version: 5.4.6
- PHP Version: 5.6
- Database Driver & Version: MySQL 5.7.14

### Description:
This may be by design, but In Laravel 5.4, if you have overridden the $primaryKey of an Eloquent model to the name of what would be expected as the foreign key in an relationship, Eloquent will duplicate the model name in the foreign key effectively adding the same string twice.  This behaviour did not happen in Laravel 5.3 or earlier versions. 

Example: If you have a database table called clients, and inside this table, instead of an auto-incrementing column called "id", the auto-increment column is named "client_id". 
*********
clients 
---
client_id (auto increment)
name (string)
address (string)
*********

Clients interacts with a device of some sort. Again, instead of an auto-increment called "id" the auto increment column has the convention {{table}}_id meaning in this case it's "device_id".
*********
devices
---
device_id (auto increment)
client_id (int)
name (string)
*********

Since we have a "non Laravel" naming convention, When we make a "Client" model we have to override the $primaryKey variable with the new column name. 
`protected $primaryKey = "client_id";`

We do the same with devices and can then add a relationship between clients and devices 
```
    public function device()
    {
        return $this->hasOne('App\Device');
    }

```
This relationship would work fine in 5.3, but in 5.4 Eloquent will add the name of the model to the relationship regardless of what exists in the $primaryKey variable resulting in the duplication of the foreign key and the following error:
`Unknown column 'device.client_client_id'`
**_Note the "doubled" client\_ string which does not exist in our database._** 

We can fix this error by simply specifying the foreign key in the hasOne call but in my experience this database naming convention is very common in legacy PHP code, so this change seems like it might be unintentional and could be something that affects many Laravel based systems. 

### Steps To Reproduce:

Follow the example above but if this is unclear I would be happy to create a sample repository that demonstrates this issue.

**Comment by srmklive** [comment]
You can do it like this:

```
    public function device()
    {
        return $this->hasOne('App\Device', 'client_id');
    }
```

**Comment by andrewfreddin** [comment]
Thanks for the reply srmklive. I did mention in my ticket that you can work around this issue by specifying the foreign key, but this naming convention is pretty common in legacy PHP code so I wanted to ensure this is by design before taking the time to update all of the relationships in my system.

**Comment by fernandobandeira** [comment]
It's a very common naming convention as you stated but keep in mind that ppl can use something like:
"hash", "key", "uniqueid" or anything like that as their primary key and the way it is now is the correct one for these usecases so removing the table from the name always doesn't seems right since you might just want to change the "id" part of the string...

**Comment by andrewfreddin** [comment]
Another demonstration of why I think this is a bug (ignore syntax if i screwed that up):
```
    public function device()
    {
        $this->primaryKey = "hello";
        return $this->hasOne('App\Device');
    }
```

will give you the error 
`Unknown column 'device.client_hello'`

**Comment by srmklive** [comment]
@andrewfreddin It's not a bug in my opinion. As @fernandobandeira stated that people use different conventions for primary keys. So the implemented solution in Laravel is the right one considering those naming patterns.

**Comment by themsaid** [comment]
In 5.3 the foreign key was generated using:

```
Str::snake(class_basename($this)).'_id'
```

In 5.4 it's now:

```
Str::snake(class_basename($this)).'_'.$this->primaryKey;
```

That's a convention that you can easily override by providing a key name to the method.

**Comment by andrewfreddin** [comment]
Thanks themsaid that sounds like a good solution. Where can I find this code snippet?

**Comment by themsaid** [comment]
```
public function device()
    {
        return $this->hasOne('App\Device', 'client_id');
    }
```

**Comment by andrewfreddin** [comment]
Ahh okay I thought you were referring to a place where I can override the snippet above.  I was hoping to avoid having to update all of the relationships on this platform in that way but thanks for the answer.

**Comment by themsaid** [comment]
If you extend a custom Model class in all your models you may override the `getForeignKey()` method to reflect the behaviour you prefer.
