### ISSUE TITLE
Form validation with empty json field

### ISSUE THREAD

**Issue by samber** [laravel/framework#17689]
Hi guys,

I am using Laravel 5.3 and Dingo to make an api.
I wrote a FormRequest validator with nested json field:

```php
class TestRequest extends FormRequest
{
    public function rules()
    {
        return [
            ...
            'complex_json' => 'sometimes|json',
            ...
        ];
    }
}
```

If I send my POST request with an empty ("{}") json field, Laravel reply with a validation error: "The complex json must be a valid JSON string."

How to make it valid ?

**Comment by themsaid** [comment]
Send a JSON string instead of an object, as I said in the other issue, I don't think `{}` is valid JSON.

Closing this issue since the other one is related.

**Comment by it4need** [comment]
@themsaid Are you sure, that `{}` is not a valid JSON string, because `json_decode("{}")` return an empty php object, which bring me to the conclusion that, `{}` is valid JSON.
