### ISSUE TITLE
Array helper docblock

### ISSUE THREAD

**Issue by stephan-v** [laravel/framework#17691]
- Laravel Version: 5.4
- PHP Version: 7.0
- Database Driver & Version:

I am wondering why is there an is_null check when the documentations param explicitly specifies a string should be given. Shouldn't this be changed to mixed in this case?

I am also trying to think of a situation where you would want to perform a get with a null key. This would never be the case unless you would put a return value of something else in there?

Code in question:

https://github.com/illuminate/support/blob/master/Arr.php#L252

**Comment by themsaid** [comment]
Thank you, feel free to open a PR to update the docblock if you want, but changing the behaviour would be considered a breaking change.
