### ISSUE TITLE
[5.4] Error in internal class TestResponse when running Feature Test.

### ISSUE THREAD

**Issue by thiagoaos** [laravel/framework#17699]
- Laravel Version: 5.4 - Laravel Framework 5.4.7
- PHP Version: 7.0.8
- Database Driver & Version: postgres

### Description:

I migrate from laravel 5.3 to laravel 5.4 and now my tests are show this error.

1) Tests\Unit\LoginTest::testLoginInvalidCredentials
Error: Class 'PHPUnit\Framework\Assert' not found

/home/thiagoaos/workspace/projects/php/base/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestResponse.php:49
/home/thiagoaos/workspace/projects/php/base/tests/Feature/LoginTest.php:22

### Steps To Reproduce:

I write a regular rest that use any assert, when i run vendor/bin/phpunit the error happened.

**Comment by Sepix** [comment]
Did you install the browser-kit-testing package as mentioned in the upgrade guide and extend your old test classes with BrowserKitTest instead of TestCase? https://laravel.com/docs/5.4/upgrade

**Comment by crynobone** [comment]
> Tests\Unit\LoginTest::testLoginInvalidCredentials Error: Class 'PHPUnit\Framework\Assert' not found

This is a clear sign that you're using phpunit lower than 5.7, do update to `phpunit/phpunit=~5.7` (probably need to mention this on the upgrade guide?)

**Comment by thiagoaos** [comment]
In the oficial package json has "phpunit/phpunit": "~5.0"

But i fix that in another way. I installed phpunit as global with compose.

Now when i run phpunit in root project directoy works but if i run with vendor/bin/phpunit appear this error.

**Comment by themsaid** [comment]
Thank you for pointing this out :)
