### ISSUE TITLE
[Feature Request] Read Only Model

### ISSUE THREAD

**Issue by jbruni** [laravel/framework#17692]
This feature request comes from project requirements I'm actually working on. We have created Eloquent models and relationships to be able to play with a legacy database. But we are not supposed to change data in any way (create / update / delete).

I believe this is a trivial change to be implemented by someone acquainted of Eloquent internal details.

We just need a `readonly` property which defaults to `true`, keeping current normal behaviour, but which can be set to `false`, enabling the read-only behaviour.

I believe performance impact is minimal, if only the necessary `if`condition to verify the `readonly` boolean is placed in the proper strategic place inside the Eloquent Model class.

Thank you.

P.S.: we can do as people out there and [override Eloquent methods](https://github.com/michaelachrisco/ReadOnlyTraitLaravel), but a simple and framework-supported solution would be much more appropriate. Thanks.

**Comment by fernandobandeira** [comment]
Usually we open proposals like this one on https://github.com/laravel/internals/issues

That being said it seems like a good feature I can create a PR for it...

**Comment by jbruni** [comment]
Oh, sorry. I didn't know about this "internals" repository.

While the feature request still valid, this is what I've just done for our project: https://gist.github.com/jbruni/3f6de84d8b6ca96cf574bb2b41671916

Of course, the PR is welcome, as it is better to have such feature out-of-the-box, handled internally and in a safer way.

**Comment by themsaid** [comment]
Thank you, but let's move the discussion to the internals repo :)

**Comment by fernandobandeira** [comment]
Moved it to laravel/internals#396
