### ISSUE TITLE
[5.4] possible bug with pivot class

### ISSUE THREAD

**Issue by unstoppablecarl** [laravel/framework#17702]
Looking at the new pivot class functionality in 5.4
shouldn’t this function https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Relations/MorphToMany.php#L129
be updated to return pivot model objects via $this->uses like it does here
https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php#L378

**Comment by themsaid** [comment]
this was fixed
