### ISSUE TITLE
Illuminate\View\Engines\PhpEngine::main(): The script tried to execute a method or access a property of an incomplete object. 

### ISSUE THREAD

**Issue by basosneo** [laravel/framework#17701]
- Laravel Version: 5.5
- Database: mysql
-SO: debian8

i dont understand this problem, any idea?

the error-

<a target="_blank" href="https://imageshack.com/i/pnBt3ESTp"><img src="http://imagizer.imageshack.us/v2/xq90/923/Bt3EST.png" border="0"></a>

cart.blade-

<a target="_blank" href="https://imageshack.com/i/pmwEQFbRp"><img src="http://imagizer.imageshack.us/v2/xq90/922/wEQFbR.png" border="0"></a>

cart.blade2-
<a target="_blank" href="https://imageshack.com/i/po155L9yp"><img src="http://imagizer.imageshack.us/v2/xq90/924/155L9y.png" border="0"></a>

Route-

<a target="_blank" href="https://imageshack.com/i/pofjCb8ep"><img src="http://imagizer.imageshack.us/v2/xq90/924/fjCb8e.png" border="0"></a>

controller-

<a target="_blank" href="https://imageshack.com/i/pmRFYmCIp"><img src="http://imagizer.imageshack.us/v2/xq90/922/RFYmCI.png" border="0"></a>

**Comment by themsaid** [comment]
Please ask on the forums.
