### ISSUE TITLE
[5.4] Where is seeJsonStructure in test?

### ISSUE THREAD

**Issue by thiagoaos** [laravel/framework#17706]
- Laravel Version: 5.4
- PHP Version: 7.0.8
- Database Driver & Version: postgres

### Description:

I used seeJsonStructure to test json response. Now i upgrade to 5.4 and i won't see this method and any other with similar behavior.

Neither in the changelog nor in the documentation say anything https://github.com/laravel/framework/blob/5.4/CHANGELOG-5.4.md

The method wasn't marked as deprecated.

Now how can i test the json structure. Many of my test use that method.

The new assertJson uses phpunit assertArraySubsetmethod that has a strange ('bug') behavior. And it require that a set the key and the value.

https://github.com/sebastianbergmann/phpunit/issues/2069

**Comment by themsaid** [comment]
Check the upgrade docs, the old test suite was moved to https://github.com/laravel/browser-kit-testing

**Comment by alandrees** [comment]
The package provides backwards compatibility, is there a canonical way of doing json structure testing post 5.4?
