### ISSUE TITLE
Error while running default migrations

### ISSUE THREAD

**Issue by evandojunior** [laravel/framework#17714]
- Laravel Version: 5.4.*
- PHP Version: 7.0.14
- Database Driver & Version:
MySQL 5.5.42
### Description:
When you run the php artisan migrate command, the following error occurs:
```sh
[Illuminate\Database\QueryException]                                             
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too l  
  ong; max key length is 767 bytes (SQL: alter table `users` add unique `users_em  
  ail_unique`(`email`)) 
```
```sh
[PDOException]                                                                   
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too l  
  ong; max key length is 767 bytes                                                 
                                  
```
### Steps To Reproduce:

```sh 
$ php artisan migrate
```

**Comment by RikSomers** [comment]
This has been reported several times:
https://github.com/laravel/framework/issues/17530 https://github.com/laravel/framework/issues/17508 https://github.com/laravel/framework/issues/17337

It's also documented in the Migration Guide: https://laravel.com/docs/5.4/migrations#indexes

Adding this in your boot method of the `AppServiceProvider` should do the trick: 
```
Schema::defaultStringLength(191);
```

like so:

```
use Illuminate\Support\Facades\Schema;

/**
 * Bootstrap any application services.
 *
 * @return void
 */
public function boot()
{
    Schema::defaultStringLength(191);
}
```

**Comment by evandojunior** [comment]
@RikSomers It worked, thank you!

**Comment by vinayakkulkarni** [comment]
sweet thanks @RikSomers

**Comment by RikSomers** [comment]
No problem, we're here to help eachother :)
