### ISSUE TITLE
updateExistingPivot() with bool touch = false seems to still update the updated_at field.

### ISSUE THREAD

**Issue by jbreuer95** [laravel/framework#17712]
- Laravel Version: 5.3.30
- PHP Version: 7.1.1
- Database Driver & Version: MySQL, 14.14

### Description:
updateExistingPivot() with bool touch = false seems to still update the updated_at field.

### Steps To Reproduce:
- Create a many to many relation with a pivot table containing extra data
- run $class->relation()->updateExistingPivot($id, ['extra_field', 'value'], false)
- Check if updated_at property was changed in db.

**Comment by themsaid** [comment]
This was fixed in latest 5.4.
