### ISSUE TITLE
[5.4] Laravel mix not interpreting Vue components watchers as intended

### ISSUE THREAD

**Issue by vTripes** [laravel/framework#17710]
- Laravel Version: 5.4.6
- Vue Version: 2.1.10
- npm Version: 4.1.2

### Description:
Since Laravel 5.4, it is recommended to use Laravel mix (config layer of webpack) to compile assets, including Vue files.
However, it seems to be interpreting code quite badly since it make components that were working dysfunctional.
It seems that setting a preset function as a component watcher's handler changes the scope and then translate `this.prop` in the handler function's parameters to `undefined.prop`.
As for information, I was using Gulp to transpile assets before Laravel 5.4.

### Steps To Reproduce:
- Create a vue single file component with these required :
```
props: {
  myObjectProp: {
    type: Object
  }
},
computed: {
  debounceTime () {
    return (condition == expected) ? 500 : 0
  }
},
watch: {
  myObjectProp: {
    handler: _.debounce(function (val) {
      // Do some stuff here
    }, this.debounceTime),
    deep: true
  }
}
```
- Then compile by running `npm run dev`

**Comment by themsaid** [comment]
Thank you, but please report on https://github.com/JeffreyWay/laravel-mix
