### ISSUE TITLE
Improvements custom stubs

### ISSUE THREAD

**Issue by Grummfy** [laravel/framework#17711]
- Laravel Version: latest 5.4 version
- PHP Version: - 
- Database Driver & Version: -

### Description:
When you use the make command that generates stuff, after a while, you sometimes want to have some customised generated files. To do that we could have several ways:
* Giving a parameter (see https://github.com/laravel/framework/pull/16486)
* Having a stub directory in the resource directory
* Any other way.
But in all case, we should have the possibility to customise it. 

Today we need to create a command that overrides the existing one, just to choose a different file. This is not simple at all.

So anyone have other suggestions to improve this? 
Thanks,

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
