### ISSUE TITLE
[5.3] deleted_at field is not created, sqlite and soft delete on testing env

### ISSUE THREAD

**Issue by franckysolo** [laravel/framework#17721]
- Laravel Version: 5.3.29
- PHP Version:  7.1
- Database Driver & Version: Sqlite 3.11.0

### Description: 
hello, 
I'm testing a model with soft delete, the deleted_at field is not create when running migration on sqlite database

### Steps To Reproduce:
- Create a model MyModel and a migration  with some fields
- add  $table->softDeletes();  to the migration model file
- add trait softDeletes to MyModel
- run php artisan:migrate --env=testing
- Create a model test using MyModel::create method
- Create a test method testMyModellCreateInstance return the instance
- Create a test method testVerifyMyModelAttributes with @depends previous method
- create an assertion assertArrayHasKey with key delete_at and value $model->getAttributes()
-> run phpunit

The test fail :   
`Failed asserting that an array has the key 'deleted_at'.`

This only append with sqlite, when using tinker or mysql the deleted_at field is created but not with sqlite 
Any ideas?

```php
class MyModelTest extends TestCase {
use DatabaseMigrations;
    public function testCreateMyModel() {
      // create an model
      $model = MyModel::create(['value' => 1 ]);
      $this->assertInstanceOf(MyModel::class, MyModel::find(1));
      return $model;
    }
    /**
     * @depends testCreateMyModel
     */
    public function testVerifyModelAttributes($model) {
      $array = $model->getAttributes();
      $this->assertArrayHasKey('id', $array);
      $this->assertArrayHasKey('value', $array);
      $this->assertArrayHasKey('created_at', $array);
      $this->assertArrayHasKey('updated_at', $array);
      $this->assertArrayHasKey('deleted_at', $array);
    }
}
```

**Comment by themsaid** [comment]
can you manually check that the field isn't created in the sqlite DB?

**Comment by GrahamCampbell** [comment]
Please ask on the forums.
