### ISSUE TITLE
[5.4] Artisan queue:listen does not obey 'tries' parameter

### ISSUE THREAD

**Issue by Stolz** [laravel/framework#17725]
- Laravel Version: 5.4.8
- PHP Version: 7.1.1
- Database Driver & Version: PostgreSQL 9.5.5

### Description:

Artisan command `queue:listen` does not obey the `--tries` parameter. It's easy to reproduce by simply checking the command in the system process list:

    $ php artisan queue:listen --tries=1 &
    $ ps a | grep artisan
    18696 pts/1    S      0:00 php artisan queue:listen --tries=3
    19473 pts/1    S      0:00 /usr/lib64/php7.1/bin/php artisan queue:work  --once --queue=default --delay=0 --memory=128 --sleep=3 --tries=

As a consequence, failed jobs are retried forever. When using the database queue driver you can see the `attempts` column growing very fast while the queue worker is running.

Artisan command `queue:work` shows same behavior

    $ php artisan queue:work --tries 2
    $ ps a |g artisan
    19871 pts/1    S+     0:00 php artisan queue:work --tries 2
    19876 pts/1    S      0:00 /usr/lib64/php7.1/bin/php artisan queue:work  --once --queue=default --delay=0 --memory=128 --sleep=3 --tries=

All my queue jobs are still in the 5.3 format, that is, they do not have the `tries` property on them and they rely on the one provided as command line parameter.

### Steps To Reproduce:

- Set a fixed number of tries when running the  `queue:listen` artisan command.
- Make a queue job to fail

**Comment by minkbear** [comment]
Fixed in v5.4.8

ref: #17687 and https://github.com/laravel/framework/blob/5.4/CHANGELOG-5.4.md

**Comment by Stolz** [comment]
I'm already using v5.4.8. For clarification, I'm not reporting the option is missing. I'm reporting the option is ignored

**Comment by minkbear** [comment]
sorry my mistake.

**Comment by themsaid** [comment]
I just fixed that for the listen command, but the work command works fine, can you re-check the work command?

**Comment by Stolz** [comment]
Using Laravel Version 5.4.x-dev both 'listen' and 'work' command seem to be working fine. Thanks!

**Comment by tadeu390** [comment]
laravel version 6.2.

problem persists

help-me
