### ISSUE TITLE
Driver does not support this function: driver does not support lastInsertId()

### ISSUE THREAD

**Issue by ghost** [laravel/framework#17724]
- Laravel Version: 5.4
- PHP Version: 7.0
- Database Driver & Version: Sql Server 2008 r2

### Description:
Creating a record using eloquent
### Steps To Reproduce:
after execute this code
`$user = App\User::create([..]);`

 **ErrorException in Processor.php line 34:
PDO::lastInsertId(): SQLSTATE[IM001]: Driver does not support this function: driver does not support lastInsertId()**

![1485944082085 remmina-2017-2-2-7 2 32 743157](https://cloud.githubusercontent.com/assets/24750114/22540021/b6514d22-e943-11e6-98d2-73931eca2b64.png)

**Comment by geekcom** [comment]
@gagansday  I'll do exactly what you did and see what happens.

**Comment by astierler** [comment]
@ghost, can you try using the `insertGetId` function on the Query Builder? (Note that I don't think this will trigger events/backend Laravel stuff).

ie. 
```php
$inserted_id = \App\User::insertGetId(['name' => '...', 'email' => '...']);
```

But simpler yet, if you are calling `::create()` why can't you just pull the ID off the Model?

```php
$user = \App\User::create([..]);
$inserted_id = $user->id;
```

**Comment by emfrigo** [comment]
i have the same issue when execute $user->save();

**Comment by cocuba** [comment]
hi, how do you solve this?, im having this issue

**Comment by laurencei** [comment]
There were some PDO changes in 5.5 or 5.6 from memory.

Please check if this issue occurs on 5.7 and if so let me know.

**Comment by JuanPSH** [comment]
Try this:

https://github.com/jacquestvanzuydam/laravel-firebird/issues/25#issuecomment-216392037
