### ISSUE TITLE
[5.4] Testing Mailable - no way to access body of email

### ISSUE THREAD

**Issue by adamthehutt** [laravel/framework#17731]
- Laravel Version: 5.4
- PHP Version: 7.1
- Database Driver & Version: Mysql 5.7

### Description:
I'm using Mail::fake() and Mail::assertSent() to test emails sent by the application. It's important that I be able to test the body of the email (i.e. search for a specific string). There are calls for things like hasTo() and hasCc(), and there is a public property for $subject, but there is no way to access the message body.

I concede I may be doing this the wrong way, in which case I would welcome advice on how to do it correctly. If this is just missing functionality, then I can try to put together a pull request if this is a feature you'd like to have

### Steps To Reproduce:
````
Mail::fake()
// Do stuff that sends email
Mail::assertSent(TheMailableThing::class, function($mail) {
    // Nothing like $mail->hasBodyContents($string) exists
});
````

**Comment by themsaid** [comment]
can you please open an issue in https://github.com/laravel/internals repo? It's the place we keep suggestions and requests.
