### ISSUE TITLE
Wrong triggering validation rules

### ISSUE THREAD

**Issue by rorc** [laravel/framework#17738]
- Laravel Version: 5.4.7
- PHP Version: 7.1.0
- Database Driver & Version: MySql 5.7.16

### Steps to reproduce
1. Make validator with rules `[ 'email' => 'email' ]`;
2. Submit form with empty value of email.

### What is Expected?
Validation passes successfuly.

### What is actually happening?
Validator throws error `The email must be a valid email address.`

**Comment by kestutisj** [comment]
> In some situations, you may wish to run validation checks against a field only if that field is present in the input array. To quickly accomplish this, add the sometimes rule to your rule list.

https://laravel.com/docs/5.4/validation#conditionally-adding-rules

`[ 'email' => 'sometimes|email' ];`

**Comment by rorc** [comment]
@kestutisj Yea, i tried, but not working anyway...

**Comment by fernandobandeira** [comment]
The field is present but with a null value, add nullable

**Comment by fernandobandeira** [comment]
Also check this article:

http://themsaid.com/laravel-convert-empty-strings-to-null-20170130/

**Comment by rorc** [comment]
@fernandobandeira Yes, thanks.
Now need all time add `nullable` rule =(
