### ISSUE TITLE
Support  for PHPUnit 6.0

### ISSUE THREAD

**Issue by Zwaen91** [laravel/framework#17745]
- Laravel Version: 5.3.*
- PHP Version: 7.0
- Database Driver & Version:

### Description:
A new PHPUnit version is released and has some changes that has to be updated in laravel. For example https://github.com/sebastianbergmann/phpunit/commit/ba2241e6e0a634dc333b6e1d2fd6d0e8c16c2f57

**Comment by themsaid** [comment]
5.4 already supports the new namespaced phpunit version. Thank you anyways :)

**Comment by GrahamCampbell** [comment]
Laravel 5.3 is closed for features and minor bug fixes now.
