### ISSUE TITLE
Transliteration with str_slug for oriental languages

### ISSUE THREAD

**Issue by fabiopenagoli** [laravel/framework#17749]
- Laravel Version: 5.2
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7

### Description:
The helper str_slug returns an empty string when the param contains oriental languages such Japanese or Chinese chars.

**Comment by themsaid** [comment]
Check `Str::charsArray()`, it's how we convert characters to be URI friendly, not all scripts are supported, so feel free to contribute if you want.
