### ISSUE TITLE
Responce json return 14 digit

### ISSUE THREAD

**Issue by koss-shtukert** [laravel/framework#17744]
- Laravel Version: 5.2.45
- PHP Version:
PHP 7.1.1-1+deb.sury.org-xenial+1 (cli) (built: Jan 20 2017 09:20:20) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.1-1+deb.sury.org~xenial+1, Copyright (c) 1999-2017, by Zend Technologies
- Database Driver & Version: -

### Description:
When i am try return json with floating number i see float with 14 decimals

### Steps To Reproduce:
Exaple:
```
Route::get('test', function() {
   return response()->json(['test' => 123.32]);
});
```

Expected:
`{"test":123.32}`

Received:
`{"test":123.31999999999999}`

**Comment by koss-shtukert** [comment]
Sotty. It's config in my php-fpm.

serialize_precision = 17

but must be 

serialize_precision = -1

**Comment by StancuFlorin** [comment]
I have the same problem, but in in my php.ini file I can see 

; When floats & doubles are serialized store serialize_precision significant
; digits after the floating point. The default value ensures that when floats
; are decoded with unserialize, the data will remain the same.
; The value is also used for json_encode when encoding double values.
; If -1 is used, then dtoa mode 0 is used which automatically select the best
; precision.
serialize_precision=-1
