### ISSUE TITLE
[5.3] Illuminate\Database\Query\Builder::count() return 0 when offset is enabled.

### ISSUE THREAD

**Issue by ordentid** [laravel/framework#17740]
- Laravel Version: 5.3 
- PHP Version: 7.0
- Database Driver & Version:
PostgreSQL 9.2
### Description:

Illuminate\Database\Query\Builder::count() return as expected when offset = 0. But if we setup the offset, the count return 0 (not expected).

### Steps To Reproduce:
use the query builder and set the offset, get the value of Builder::count().

**Comment by GrahamCampbell** [comment]
Please try with Laravel 5.4 and open a new issue if this remains.

**Comment by druu** [comment]
@ordentid also, this is the correct behaviour.
I'm not sure what oyu expect, but the standard does exactly expect not to return any rows if rowcount < offset

see: http://sqlfiddle.com/#!15/9eecb7db59d16c80417c72d1e1f4fbf1/14934

SELECT COUNT returns only ONE row. offsetting by 15 results in 0 rows as expected
