### ISSUE TITLE
[5.4] Are you planning to implement `assertDontJson` ?

### ISSUE THREAD

**Issue by komatzz** [laravel/framework#17743]
- Laravel Version: 5.4.8
- PHP Version: 7
- Database Driver & Version:

### Description:
[5.3] `seeJson` → [5.4] `assertJson`
[5.3]`dontSeeJson` → [5.4] ?

**Comment by GrahamCampbell** [comment]
Closing since this stuff isn't in the framework core anymore as far as I recall.

**Comment by yyc1217** [comment]
I think the negative of `assertJson` (or other testing utility methods) is required. We need a way to test **DELETE** http entrypoint is actually deleting something.
