### ISSUE TITLE
ErrorException: Undefined index: sendmail

### ISSUE THREAD

**Issue by jwhulette** [laravel/framework#17751]
- Laravel Version: 5.4
- PHP Version: 7.0.15
- Database Driver & Version: NA

### Description:
When trying use send mail for email sending the error ErrorException: Undefined index: sendmail occurs.

### Steps To Reproduce:
Try using send mail to send an email

### Resolution:
In config/mail.php the section
    /*
    |--------------------------------------------------------------------------
    | Sendmail System Path
    |--------------------------------------------------------------------------
    |
    | When using the "sendmail" driver to send e-mails, we will need to know
    | the path to where Sendmail lives on this server. A default path has
    | been provided here, which will work well on most of your systems.
    |
    */
    'sendmail' => '/usr/sbin/sendmail -bs',

is missing.

**Comment by themsaid** [comment]
Thank you, just fixed that :)

https://github.com/laravel/laravel/commit/a6fdc9472f2619cdc7b41b089157fb74e462e9d7
