### ISSUE TITLE
or behaving unexpectedly in blade

### ISSUE THREAD

**Issue by SaeedPrez** [laravel/framework#17754]
- Laravel Version: 5.3.30
- PHP Version: 7.1.1
- Database Driver & Version: MySQL driver (MariaDB 10.1.19-win32)

### Description:
When using `{{ auth()->user()->name or 'No name' }}` the output is `1` instead of the user's name.

Same happens with `{{ \App\User::first()->name or 'No name' }}`.. 

However, if you send the data from a controller, it works as expected:
```
$user = auth()->user();
return view('someView')->with('user', $user);
```
```
{{ $user->name or 'No name' }} 
```

### Steps To Reproduce:
Put `{{ auth()->user()->name or 'No name' }}` in your blade template.

**Comment by themsaid** [comment]
Looking at the regex it's explicitly meant to be used with variables as the first character must be `$`, I suggest you use `{{ auth()->user()->name ?? 'No name' }}` since you're on PHP 7.1 already.

**Comment by SaeedPrez** [comment]
@themsaid

I do usually use `??` but I did not know `or` was only for variables. 

Thank you for your reply and I appreciate the quick response.
