### ISSUE TITLE
passing value in get api request error

### ISSUE THREAD

**Issue by yadavaditya0** [laravel/framework#17769]
- Laravel Version: 5.4
- PHP Version: 7.1
- Database Driver & Version: MySQL

### Description: 
I am trying to get value using passing variable in api.php file. this is a short test code. Not working in api.php file

### Steps To Reproduce:
Route::get('/man/{$id}', function () {
    echo $id;
});

**Comment by yazfield** [comment]
You have a bug there, this should be like this:
```php
Route::get('/man/{id}', function ($id) {
   echo $id;
});
```

Check [Laravel Routing](https://laravel.com/docs/5.4/routing#route-parameters) documentation

**Comment by GrahamCampbell** [comment]
You should `return` instead of `echo`. You shouldn't be directly writing to the output like that.

**Comment by GrahamCampbell** [comment]
Suitable code would be:

```php
Route::get('/man/{id}', function ($id) {
    return (string) $id;
});
```

**Comment by GrahamCampbell** [comment]
It'll be a miracle if the echo actually works at all and doesn't screw up everything.

**Comment by yazfield** [comment]
Didn't pay attention to the echo

**Comment by yadavaditya0** [comment]
Thanks @GrahamCampbell ,
Thanks @yazfield
