### ISSUE TITLE
single and double quotation marks in printing variable value in blade

### ISSUE THREAD

**Issue by mutazhameed** [laravel/framework#17765]
- Laravel Version: 4.2.19
- PHP Version: 5.5.9-1
- Database Driver & Version: MySQL v5.5.49

### Description:
the single quotation dosnt act same as double quotation when trying to print a value stored in defined variable.
### Steps To Reproduce:
assume:
<?php $id=1; ?>
{{ Form::text('name_fr$id', null, array('class' => 'form-control')) }}
this will not print the value in $id
BUT:
{{ Form::text("name_fr$id", null, array('class' => 'form-control')) }}
will work just fine.

**Comment by marky291** [comment]
Then why not use double quotes? 

("name_fr {$id}")

**Comment by marky291** [comment]
Here's the documentation to prove valid PHP.

http://www.php.net/manual/en/language.types.string.php#language.types.string.syntax.single

**Comment by mariomka** [comment]
It's a standard PHP behavior.

**Comment by mutazhameed** [comment]
thank you guys, much appreciated
