### ISSUE TITLE
Doctrine/dbal missing interface methods.

### ISSUE THREAD

**Issue by marky291** [laravel/framework#17767]
- Laravel Version: 5.4.9
- PHP Version 7:
- Database Driver & Version: N/A

https://github.com/doctrine/dbal/issues/2628#issuecomment-277457050

Unable to use the `change()` method for migrations.

**Comment by themsaid** [comment]
Works fine here, please share an example that doesn't work for you with the error you get.

**Comment by marky291** [comment]
Using change () to rename a column on migrations.

**Comment by marky291** [comment]
$table->unsignedInteger('creator_id')->default(1)->change();

**Comment by marky291** [comment]
Looks to be trying to change the table to make a default value for new entries.

**Comment by themsaid** [comment]
Can you please share more details? what do you mean by can't use? Does it error? does it not work at all? does it do something other than what you want?

**Comment by marky291** [comment]
Sorry, I was using a phone, no edit options, I was also half asleep.

The issue refers to the above link.

```
I have out of nowhere received this error using laravel 5.4, windows 10.

I am using the latest version of dbal, but issue occured on version, "doctrine/dbal": "~2.3",

Class Doctrine\DBAL\Driver\PDOStatement contains 3 abstract methods and must therefore be declared abstract or implement the remaining methods (Doctrine\DBAL\Driver\Statement::errorCode, Doctrine\DBAL\Driver\ResultStatement::closeCursor, Doctrine\DBAL\Driver\ResultStatement::columnCount)

The problem seems to be with the package?
```

I cannot use the change() method to make a table default as one.

**Comment by themsaid** [comment]
Can't replicate the issue here, `change()` seems to be working fine. Please share a migration file I can copy and test on a fresh laravel installation.

**Comment by kushal555** [comment]
Hi @themsaid 
I also having the same issue with my project. Its working fine but suddenly I am getting an error.

- Laravel 5.3
- DBAL 2.3
- Server WINDOW 2008 R2
- PHP 5.9
- XAMPP 

Error :- 

> FatalErrorException in PDOStatement.php line 28:
> Class Doctrine\DBAL\Driver\PDOStatement contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Doctrine\DBAL\Driver\Statement::errorInfo)

Please give me some solution. I really stuck in mid of my project.

**Comment by turtlegood** [comment]
Hi, the same problem here. Any solutions?

**Comment by marky291** [comment]
I fixed the issue by not using dbal.

**Comment by jasekiw** [comment]
My laravel install just randomly started throwing this error: 

(1/1)                                        FatalErrorException                                                                        Class Doctrine\DBAL\Driver\PDOStatement contains 3 abstract methods and must therefore be declared abstract or implement the remaining methods (Doctrine\DBAL\Driver\Statement::errorCode, Doctrine\DBAL\Driver\Statement::errorInfo, Doctrine\DBAL\Driver\Statement::rowCount)
--
in PDOStatement.php (line 28)

I was doing edits on the front end. I didn't touch the backend.

**Comment by reganjohnson** [comment]
Seeing this error after upgrading to PHP 7.1 - not sure if related to a recent Laravel bump in minor version.

```
Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)
Class Doctrine\DBAL\Driver\PDOStatement contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Doctrine\DBAL\Driver\ResultStatement::columnCount)
```

**Comment by jasekiw** [comment]
After restarting my local development Apache server, it fixed it. It's seems php itself is having problems because I completely wiped and cloned my app from source and it was still running in the issue until I restarted Apache.

**Comment by turtlegood** [comment]
Similar solution to @jasekiw 's.
I set my production server to **reboot every midnight** and now it seldom have this error.

**Comment by ccLaravel** [comment]
Similar solution to @jasekiw 's.
I've use **Laragon** just restart
