### ISSUE TITLE
[5.3] An error or an expected: request->has()?

### ISSUE THREAD

**Issue by emtudo** [laravel/framework#17782]
- Laravel Version: 5.3.30
- PHP Version: 7.1
- Database Driver & Version: mysql 5.7

### Description:

I do not know if this is a bug or if it is expected so.

### Steps To Reproduce:
```
<?php

namespace App\Http\Requests;

use App\Http\Requests\Request;

class StoreRequest extends Request
{
    public function all() {
        $input = parent::all();
        $input['teste'] = true;

        return $input;
    }   
}
```

.....

(controller)
....
```
public function store(StoreRequest $request)
{
   $data = $request->all(); // array('teste' => true);
   if ($request->has('teste') { // false
   ....
   }
   if ($request->get('teste') { // null
   ....
   }
   dd($data); // array('teste' => true);
}
```

**Comment by kamui545** [comment]
Try with `$this->replace()` instead (https://github.com/kamui545/framework/blob/master/src/Illuminate/Http/Request.php#L280).

But overwriting the `all` method seems hacky, what is your use case? Are you trying to sanitize your inputs? Take a look at http://www.easylaravelbook.com/blog/2015/03/31/sanitizing-input-using-laravel-5-form-requests/

**Comment by emtudo** [comment]
I just wanted to set a default value for a given action. But okay about that, I was just left wondering if the "request-> has" should work as it did, or if it's a bug. It even makes a little sense to be the way it is.
