### ISSUE TITLE
Possible bug in Illuminate\Log\Writer\useSyslog()

### ISSUE THREAD

**Issue by peterkeri** [laravel/framework#17788]
- Laravel Version: 5.3.30
- PHP Version: 7.1.1

### Possible bug in Illuminate\Log\Writer\useSyslog()
Can't set facility parameter when try to call useSyslog function. I would like to use LOG_ LOCAL4 but there is no way to set this parameter, the default parameter is LOG_ USER.

**Comment by fernandobandeira** [comment]
@peterkeri I've created a PR for 5.4, if it get's merged you can upgrade and use it, 5.3 won't get it =/

**Comment by peterkeri** [comment]
Thanks a lot.
