### ISSUE TITLE
Cache information schema queries

### ISSUE THREAD

**Issue by davo3** [laravel/framework#17781]
- Laravel Version: 5.3.30
- PHP Version: PHP 5.6.27
- Database Driver & Version: MySQL 5.6.34
- Type: feature request

### Description:
When making `Schema::hasColumn` checks for the `my_table` table every time it makes a request to the database
```
select column_name from information_schema.columns where table_schema = 'my_db_name' and table_name = 'my_table'
```

Instead I think it should cache the query after first time and read from cache. If debug is enabled, cache time can be minutes or seconds (to not create issues during development) and some long period (months ?) for production

I admit that this can be easily implemented manually (I just asked a question in SO - http://stackoverflow.com/q/42056536/932473) , but I think this kind of internal things should be built-in features in the framework and by default would provide great boast on performance

### Steps To Reproduce:
if we have these 2 lines
```
Schema::hasColumn('some_table', 'some_column');
Schema::hasColumn('some_table', 'some_column');
```
we will have the above query run twice - and during each page load

**Comment by mariomka** [comment]
Looks good.

An idea: The cache could be cleared when running the migrations.

**Comment by kamui545** [comment]
I agree with **Paras** from S.O, you should define a variable in your model or a config to handle this instead of running a query every time.

I don't think this should be part of the framework, at least, not for this use case.

**Comment by sisve** [comment]
Multiple calls to Schema::hasColumn can probably be cached during the current http request or artisan command; but accessing them for longer than that sounds bad. It assumes we're in full control of the database, and no other process is modifying it. It would also cause issues for all the developers that does manual changes to their database (even if it's not considered a good practice).

**Comment by mariomka** [comment]
It can be an option (disabled by default) for projects that has full control of the database.

**Comment by davo3** [comment]
@kamui545 defining does not solve the part of the problem of making the same query on every page load

> but accessing them for longer than that sounds bad

@sisve I do not share your point, how often in production mode the table's schema is changed ? I think in 99 % cases only when you apply some update (and we can delete the cache, when running migration as @mariomka suggested, or have some command to delete it), if the user manually changes the database, then its his responsibility to manually delete the cache as well. In development mode as I mentioned we can put the cache time the smallest (or disable at all), so it wont be an issue

for the last resort, as @mariomka sad, it can be disabled by default, but I think this option should exist. I think with easiness of development the framework should have at least basic optimization things built-in, well, even if disabled by default...

**Comment by themsaid** [comment]
5.3 is closed for new features, feel free to open a PR on 5.4 if you want. However, in my opinion this needs to be handled in the app code, not in the core.
