### ISSUE TITLE
[5.3+] Soft deletes / unique validation race condition

### ISSUE THREAD

**Issue by ashleigh-hopkins** [laravel/framework#17790]
- Laravel Version: 5.3.30
- PHP Version: 7.0.14
- Database Driver & Version: MySQL - 5.6.35

### Description:

My Laravel application is a REST API for consumption through a smart phone app.

When using the SoftDeletes trait on a user model, and unique validation on the email field, it is possible (assuming a fast enough server / collection of servers) to add multiple table rows with the same email field to a table. A classic TOC-TOU problem.

I mentioned SoftDeletes, because if I wasn't using soft deletes then a unique index on the email field would save the day. Adding a unique index for both email and deleted_at will not work, because in MySQL a NULL is not treated as a unique value - see https://bugs.mysql.com/bug.php?id=8173

There also doesn't seem to be any way to force MySQL to treat it as a unique value.

A user was able to send parallel requests to my authentication API and register 9 user accounts with the exact same details, before enough time had elapsed that the validation failed.

### Steps to reproduce:

1. Install a stock Laravel system.
2. Follow instructions in documentation to add Authentication support (i.e. php artisan make:auth then php artisan migrate).
3. Add SoftDeletes trait to the new User model 
4. Modify users table adding a `deleted_at` timestamp field
5. Modify RegisterController validator to:
```
        return Validator::make($data, [
            'name' => 'required|max:255',
            'email' => ['required', 'email', 'max:255', \Illuminate\Validation\Rule::unique('users', 'email')->whereNull('deleted_at')],
            'password' => 'required|min:6|confirmed',
        ]);
```
6. Add route to api.php routes file:
`Route::post('register', 'Auth\RegisterController@register');`
7. Fire several valid POST at api/register in parallel.
8. Check database for duplicates!

The only obvious solution I can see to this issue is to stop using soft deletes, which would be less than ideal.

There are some more complex solutions (force CSRF token request before allowing POST, add additional field to database, move deleted user records to secondary table, etc) but most of these "solutions" drastically complicate the workflow.

It's always possible that I'm just doing something stupid, but I suspect this is a limitation of what can be done without adding lots of complexity.

**Comment by themsaid** [comment]
Protection against such behaviour has to be done inside the application itself, it's not something that can be handled in the core since there are different scenarios.

I suggest that you post your question on the forum, I'm sure someone can help you with some ideas on how to get around this.
