### ISSUE TITLE
config/database.php isn't recognized if symlink

### ISSUE THREAD

**Issue by calina-c** [laravel/framework#17791]
- Laravel Version: 5.1
- PHP Version: 5.5
- Database Driver & Version: -

### Description:
Same file contents for `config/database.php` is not properly recognized by Laravel. Instead it seems the database is not configured. This happens for me when deploying with Capistrano and adding the file as shared, instead of copy-ing it.

### Steps To Reproduce:
<img width="1256" alt="screen shot 2017-02-06 at 15 32 41" src="https://cloud.githubusercontent.com/assets/4101015/22649135/5acbc08a-ec82-11e6-8fe6-17f5b1410880.png">

**Comment by GrahamCampbell** [comment]
I don't think this is a bug. We don't support symlinking like that. One thing you could do is symlink the whole config folder though.

**Comment by calina-c** [comment]
thank you for the reply @GrahamCampbell :) I fixed this by copying the files during deploy. Not the most elegant solution but it did the trick.
