### ISSUE TITLE
[5.*] PHPUnit hangs on artisan's ask

### ISSUE THREAD

**Issue by Quezler** [laravel/framework#17794]
- Laravel Version: 5.*

### Description:
PHPUnit hangs on artisan's ask

### Steps To Reproduce:
- make an artisan command that ask for input
- call that command in a newly created test
- run test
- notice it hangs indefinitely

**Comment by GrahamCampbell** [comment]
You need to run the command with `--no-interaction` in your test.

**Comment by Quezler** [comment]
It still gets easily overlooked when using the facade.

**Comment by tvillafane** [comment]
Can we put this in the docs please?
