### ISSUE TITLE
[5.4] Session::getMetadataBag() alternative

### ISSUE THREAD

**Issue by juanpscotto** [laravel/framework#17796]
- Laravel Version: 5.4.9
- PHP Version: 7.0

### Description:
After upgrating from laravel 5.3 to laravel 5.4 I cannot use anymore Session::getMetadataBag(). This is the error that appears:

Call to undefined method Illuminate\Session\Store::getMetadataBag().

Session::all()

`
array:4 [
    "_token" => "SQjQpOxCec5lal5tzFgW1FMtrcOaaIqjoii2fuCb"
    "_previous" => array:1 [
        "url" => "http://my-url"
    ]
    "_flash" => array:2 [
        "old" => []
        "new" => []
    ]
    "lang" => "en"
]
`

getMetaDataBag()

`
MetadataBag {#582
    -name: "__metadata"
    -storageKey: "_sf2_meta"
    #meta: & array:3 [
        "u" => 1485527838
        "c" => 1485527838
        "l" => "0"
    ]
    -lastUsed: 1485527838
    -updateThreshold: 0
}
`

I know it was removed, but how can I get the lastUsed know ?

Session::all() does not return this value.

Thanks

**Comment by GrahamCampbell** [comment]
Please ask questions on the forums. :)

**Comment by raulidavid** [comment]
I have the same problem and I can not find a solution
