### ISSUE TITLE
create manytomany relation about two table with column not id

### ISSUE THREAD

**Issue by finchcn** [laravel/framework#17799]
- Laravel Version: any
- PHP Version:  7.0
- Database Driver & Version: mysql/pgsql

### Description:
how to create manytomany relation about two table with column not id
for example:
user table has id, uid, and other columns
prop table has id, name and other columns
user table's uid column is passport id
i want have an table prop_user has id, uid, prop_id to record relation about users and props
but i can do that use laravel

**Comment by themsaid** [comment]
Please use the forums for posting questions, we try to keep this repo for bug reporting only.

Thank you :)
