### ISSUE TITLE
Mix can not compiling the React (jsx) file

### ISSUE THREAD

**Issue by nuocgansoi** [laravel/framework#17798]
- Laravel Version: 5.4

I can not compile React file by default webpack.config.js.

Please fix **node_modules\laravel-mix\setup\webpack.config.js** lines 92-96 to:

```
{
     test: /\.jsx?$/,
     exclude: /(node_modules|bower_components)/,
     loader: 'babel-loader' + Mix.babelConfig(),
     query: {
         presets: ['react', 'es2015']
     }
}
```

Thanks.

**Comment by themsaid** [comment]
Please report on https://github.com/jeffreyWay/laravel-mix
