### ISSUE TITLE
[5.4] Issue with ConvertEmptyStringsToNull and Validation

### ISSUE THREAD

**Issue by kayrunm** [laravel/framework#17802]
- Laravel Version: 5.4.x
- PHP Version: 7.0.8
- Database Driver & Version: N/A

### Description:

The new `ConvertEmptyStringsToNull` middleware in 5.4 causes non-required fields to fail in validation.

### Steps To Reproduce:

1. Run `php artisan tinker` in the console.
2. `Validator::make(['field' => null], ['field' => 'url'])->passes();` and press return.
3. The return value will be `false`

**Comment by fernandobandeira** [comment]
Check http://themsaid.com/laravel-convert-empty-strings-to-null-20170130/

**Comment by kayrunm** [comment]
Thank you, never knew this.

**Comment by themsaid** [comment]
it's confusing for many I know :)
