### ISSUE TITLE
[RFC/Issue] Add "name" as one of the Validation Rules

### ISSUE THREAD

**Issue by gabbydgab** [laravel/framework#17800]
### Description:
Odd issue in validating a name string which causes _**"may only contain letters"**_ validation error

Try this command in tinker: _**`(Validator::make(['name'=> "Given Name"], ['name' => 'alpha|string|min:1']))->fails();`**_

It returns _**true**_ because of the space on the name value.

### Proposal: 

Allow **_space_** and **_dash_** for a given "name" string. Let **_name_** be the alias for **_"alpha_dash|string|min:1"_** rule.

 Validation | Output 
--- | --- 
 `Validator::make(['name'=> "Bob"], ['name' => 'name'])` | true 
 `Validator::make(['name'=> "Uncle Bob"], ['name' => 'name'])` | true 
 `Validator::make(['name'=> "A-aron"], ['name' => 'name'])` | true 
 `Validator::make(['name'=> "A-aron John"], ['name' => 'name'])` | true 
 `Validator::make(['name'=> "A4tech"], ['name' => 'name'])` | false 
 `Validator::make(['name'=> "A-4tech"], ['name' => 'name'])` | false 
 `Validator::make(['name'=> "A-4tech"], ['name' => 'name|alpha_num'])` | true 
 `Validator::make(['name'=> "A4tech"], ['name' => 'name|alpha_num'])` | true

**Comment by mariomka** [comment]
There are not differences between "alpha_dash|string|min:1" and only "alpha_dash" rule.

I think you are searching something like alpha_space, check it: http://blog.elenakolevska.com/laravel-alpha-validator-that-allows-spaces

Maybe add alpha_space would be a good idea...

**Comment by themsaid** [comment]
This sound like a rule you can add in your own application, however you dan open a PR to suggest a new rule if you feel like.
