### ISSUE TITLE
Validation rule bail not working

### ISSUE THREAD

**Issue by rorc** [laravel/framework#17805]
- Laravel Version: 5.4.7
- PHP Version: 7.1.0
- Database Driver & Version: 5.7.16

### Steps to reproduce
1. Make validator with rules `[ 'email' => 'bail|required_if:status_id,2|email' ]`;
2. Submit form with status_id = 3 and wrong format email

### What is Expected?
Validation passes succesfully.

### What is actually happening?
Validator throws error `The email must be a valid email address.`

**Comment by themsaid** [comment]
Why do you think the validator should pass? Bail stops further validation if the first rule fails, in your example the first rule was skipped because status_id <> 2, so the actual first rule hit was email since the required_if was skipped.

**Comment by rorc** [comment]
But, how i can check email only if previous rules passed, i.e i want to check email only if status_id = 2?

**Comment by themsaid** [comment]
take a look at: http://themsaid.com/laravel-advanced-validation-conditionally-adding-rules-20170110/

;)

**Comment by rorc** [comment]
@themsaid Thanks, but if i use FormRequest, how i can apply `sometimes` extended rule?
