### ISSUE TITLE
Add Builder methods "orWhereYear" and "orWhereMonth" for convenience

### ISSUE THREAD

**Issue by jlmmns** [laravel/framework#17801]
- Laravel Version: 5.3.28
- PHP Version: 7.0.13
- Database Driver & Version: MariaDB - 10.1.19 

### Description:

It would be helpful to have methods like `orWhereYear` and `orWhereMonth` for convenience.

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
