### ISSUE TITLE
[5.4] Plurals of many languages has been missed

### ISSUE THREAD

**Issue by cjmaxik** [laravel/framework#17816]
- Laravel Version: 5.4.*

### Description:
Since PR https://github.com/laravel/framework/pull/15563 was introduced, Laravel has been missed a major feature for translators - **plurals**. While English and other langs with `one|many` plural scheme is working great, another languages (like Russian with more complex plural scheme) is broken right now.

### Steps To Reproduce:
English locale
```php
'apples' => ':count apple|:count apples',
```
1 apple | 2 apples | 24 apples | 2657 apples

Russian locale
```php
'apples' => ':count яблоко|:count яблока|:count яблок',
```
Should be 1 яблоко | 2 яблока | 24 яблока | 2657 яблок
Returns 1 яблоко | 2 яблока | 24 яблока | 2657 яблок**а**

**Comment by themsaid** [comment]
Looking into fixing this today.

**Comment by themsaid** [comment]
https://github.com/laravel/framework/pull/17826
