### ISSUE TITLE
Is there anyway to get event(eloquent.creating ,eloquent.saved ..etc) with query builder

### ISSUE THREAD

**Issue by deathkel** [laravel/framework#17819]
- Laravel Version: 5.3.*
- PHP Version:7.0
- Database Driver & Version:

### Description:
Is there anyway to get event(eloquent.creating ,eloquent.saved ..etc) with query builder function.
not Model function

**Comment by themsaid** [comment]
please post your question on the forums, we try to keep this repo for bug reporting only.
