### ISSUE TITLE
whereBetween and DB::raw() bug

### ISSUE THREAD

**Issue by garygreen** [laravel/framework#17810]
- Laravel Version: 5.3
- Database: MySQL
- PHP Version: 5.6

### Description:

Using `whereBetween` with the query build and `DB::raw()` doesn't filter properly.

### Steps To Reproduce:

```php
Schema::dropIfExists('tickets');
Schema::create('tickets', function($table) {
    $table->increments('id');
    $table->date('start_date');
    $table->date('end_date');
});

DB::table('tickets')->insert([
    [
        'start_date' => '2017-02-06',
        'end_date' => '2017-02-08',
    ],
]);


$ticket = DB::table('tickets')->whereBetween(DB::raw("'2017-02-07'"), [DB::raw('start_date'), DB::raw('end_date')])->first();

// Expected result: 1 row.
// Actual result: null
```

The SQL which should be generated for the above is below. When queried in phpmyadmin it returns the result.

```mysql
select * from tickets where '2017-02-07' between start_date and end_date;
```

**Comment by themsaid** [comment]
Check the query generated from laravel using the query logger & please share it.

**Comment by themsaid** [comment]
Here's the query generated on a fresh laravel 5.3 installation:

```
select * from `tickets` where '2017-02-07' between start_date and end_date limit 1
```

The query is correct, try to copy and paste it in phpmyadmin and see if you'll get any results.

Closing since it's not an issue in the framework.

**Comment by garygreen** [comment]
@themsaid sure, but did you test the code I put? Laravel doesn't return anything yet that query is correct.

**Comment by garygreen** [comment]
@themsaid you closed this one too quickly without resolution. I just tested on 5.4 and experience the same problem (issues exist both in 5.3 and 5.4).

**Comment by themsaid** [comment]
Have you tried `whereRaw`?

**Comment by garygreen** [comment]
Yup I did, and whereRaw works....

**Comment by themsaid** [comment]
It's an edge case that I tracked back to 2013, and whereRaw is recommended in such cases where the comparison value is an expression.

**Comment by arjasco** [comment]
I tested on 5.3.30 and latest 5.4 got this:

```
select * from `tickets` where 2017-02-07 between ? and ?
```

Appears maybe whereBetween doesn't allow raw expressions when binding the params??

**Comment by vitordm** [comment]
this issue still happens on Laravel 5.6.

**Comment by bhargavraviya** [comment]
please try like this 
```
$recordQuery->whereRaw("DATE(datetime) BETWEEN ? AND ?", [$validatedData['start_date'], $validatedData['end_date']]);
```
