### ISSUE TITLE
Queue Delay Proposal - Parse DateTime *Strings*

### ISSUE THREAD

**Issue by johnpaulmedina** [laravel/framework#17815]
- Laravel Version: 5.x.x
- PHP Version: 7.0.12
- Database Driver & Version: MySQL 5.6.33/Beanstalkd 1.10

### Description:
When pushing a job on to ``Queue::laterOn`` the function on the documentation expects the $delay to be a DateTime object or integer which will be converted to seconds on the getSeconds function. I had unintentionally been passing a DateTime string in 'Y-m-d H:i:s' format. Since this was a string and not a DateTime object it was skipping the if statement:

```
     /**
     * Calculate the number of seconds with the given delay.
     *
     * @param  \DateTime|int  $delay
     * @return int
     */
    protected function getSeconds($delay)
    {
        if ($delay instanceof DateTime) {
            return max(0, $delay->getTimestamp() - $this->getTime());
        }

       // @todo implement Carbon::parse ?

        return (int) $delay;
    }
```

I think that here at this level we can possibly implement the ability to check if the delay is a string that matches a DateTime string format and if so then getting the difference from current DateTime.

I was seeing unexpected behavior where it was just pushing the job out 1800 seconds by default when the request of delay was only suppose to be 2 minutes (120 seconds) but was not properly parsing the string. 

What are your thoughts on this?

**Comment by themsaid** [comment]
Thanks but for suggestions and feature requests please use the https://github.com/laravel/internals repo.
