### ISSUE TITLE
[5.4] input vaildation 'required_if' along with 'min' is not working correctly

### ISSUE THREAD

**Issue by arunvkumarkc** [laravel/framework#17817]
- Laravel Version: 5.4.8
- PHP Version: 7.1.0
- Database Driver & Version:

### Description:
I have used min validation condition along with required_if, as per laravel doc its expected to trigger min validation only if required_if input filed is equal to some value.  I have given rules in following order 
`'name' => 'required_if:check_required,"1"|min:3'` 
But its giving validation error for min even if check_required field is not equal to 1

### Steps To Reproduce:
clone this repo
https://github.com/arunvkumarkc/required_if_validation_bug
and access /test route. Validation rules are in TestController.php

**Comment by themsaid** [comment]
You got that wrong I'm afraid :)

check http://themsaid.com/laravel-advanced-validation-conditionally-adding-rules-20170110/

**Comment by arunvkumarkc** [comment]
I have changed the rule to 
 `'name' => 'required_if:check_required,1|min:3', `
still its not working

**Comment by arunvkumarkc** [comment]
its was working in l 5.3 but not in 5.4

**Comment by themsaid** [comment]
It could be related to empty strings being converted to null in 5.4, but it's not related to the required if rule, the rule doesn't have effect on any other rules, it simply states that the field is required only if this equal that, but the rest of the rules will run anyways.

Try removing the ComvertEmptyStringsToNull middleware.

**Comment by arunvkumarkc** [comment]
Okay. Its working without that.  What if I want to use this validation along with ComvertEmptyStringsToNull middleware ?

**Comment by arunvkumarkc** [comment]
Is there any way to use required_if & and min along with ComvertEmptyStringsToNull middleware ?

**Comment by arunvkumarkc** [comment]
Do I have to report this as a new issue ?

**Comment by Joel-James** [comment]
@arunvkumarkc, have you tried `bail` rule? `bail` rule can be used if you want to stop validating other rules on first validation failure (Related [pull request](https://github.com/laravel/framework/pull/11986)).

**Comment by arunvkumarkc** [comment]
No I did not!

**Comment by arunvkumarkc** [comment]
But everything was fine in 5.3, but its not working in 5.4 
`'name' => 'required_if:check_required,1|min:3'`
is there anything wrong in the above code?

**Comment by Joel-James** [comment]
I don't think there is anything wrong. But just try using `bail`.
