### ISSUE TITLE
[5.4] No tests found in class "BrowserKitTest"

### ISSUE THREAD

**Issue by poisa** [laravel/framework#17811]
- Laravel Version: 5.4.9

I've just upgraded an existing app to 5.4. Since I have hundreds of tests I used the suggested package `laravel/browser-kit-testing` to make my old tests functional again.

In the documentation, it is suggested to extend the `BrowserKitTest` class for all 5.3 tests. I think this is not a good suggestion for the class name as PHPUnit thinks it should have tests inside it (which it doesn't and shouldn't) and exits with a warning. This makes any CI pipelines that depend on phpunit's exit code halt as they think something is wrong when in fact it isn't.

Maybe it would be wiser to suggest `BrowserKit` instead of `BrowserKitTest` so that PHPUnit ignores the file.

**Comment by GrahamCampbell** [comment]
There's a typo here. Should say `BrowserKitTestCase` I think. That would be the convention.

**Comment by poisa** [comment]
That's exactly what I ended up calling mine.

**Comment by themsaid** [comment]
Thank you, docs updated.
