### ISSUE TITLE
Parsing @foreach in code comments 

### ISSUE THREAD

**Issue by mapodev** [laravel/framework#17813]
- Laravel Version: 5.3.1
- PHP Version: 5.6
- Database Driver & Version: MySQL

### Description:

If leaving foreach() without parameters in blade comments 

`{{-- foreach() --}}`

 is causing a parsing Fatal Error.

**Comment by mikromika** [comment]
```
{{--*/         @foreach ()     /*--}}
{{--*/         @endforeach     /*--}}

```
try this way, works for me.

**Comment by mapodev** [comment]
That's not the point. It should not eval the code inside blade comments. So doesn't PHP.

**Comment by devcircus** [comment]
See explanation in #16688
[Blade Extends Bug](https://github.com/laravel/framework/issues/16688)
