### ISSUE TITLE
Session shutdown handler

### ISSUE THREAD

**Issue by stephan-v** [laravel/framework#17820]
Normally with a `session_set_save_handler` you would also register a shutdown handler with `session_register_shutdown`.

Although Laravel implements the `SessionHandlerInterface` I see no mention of something that looks like a shutdown handler for when something goes wrong in the controller. This would mean that if you ultimately don't reach the middleware again to call a save on the session you are screwed.

Is there a legitimate reason for this? I would love to know since I am building something alike and I feel like Laravel might be missing out here by not implementing something like this.

Then again I don't know if it even would be possible at this point so I am hoping somebody might provide me with some knowledge on why this is not done.

**Comment by GrahamCampbell** [comment]
Please ask on the forums.
