### ISSUE TITLE
Laravel 5.2 Session is not persistent, its weird 

### ISSUE THREAD

**Issue by twob-shahid** [laravel/framework#17825]
- Laravel Version: 5.2
- PHP Version: 5.6
- Database Driver & Version:

### Description:
Session is not persistent. I can't get session created from one controller action to another.

**Comment by srmklive** [comment]
5.2 is not officially supported anymore. Does the same thing happens in 5.4?

**Comment by GrahamCampbell** [comment]
Please open a new issue if you have this issue on the very latest 5.4.x.
