### ISSUE TITLE
Caching Bug with different Server Users

### ISSUE THREAD

**Issue by VarnishingJam** [laravel/framework#17823]
- Laravel Version: 5.2.41
- PHP Version: 7.0.8

### Description:
I have a view dynamically created by Server User A (www-data). So the Blade File gets written and created by that user. I preview the View in the browser, so the cache file is generated with Server User A beeing the owner.
Now i use this View to email it via a cronjob which is running under Server User B. Everything is fine.
Now i edit the View and dont preview it in the browser, meaning the cached file is not getting updated.
When I try to email the View now, the Server User B is trying to update the cached file beeing owned by Server User A, leading to "file_put_contents permission denied" error.

This is fixed, if you preview the edited view as Server User A so the cached File is getting updated by his owner.

Is this intended, or is there any Possibility to force the cached File getting renewed without opening/previewing it?
Something like Artisan::call('view:cache') beeing called from a controller after editing the view?

We know that you shouldnt dynamically create php files, but this is in a safe environment.

**Comment by huglester** [comment]
Hello,

this by no means is bound to framework.
This are problems are server miss-configuration.

often people try to use their 'user1' to run CLI commands,
they create directories using this user,
and later www-data comes in and does not have permission to write to directories, etc.

You should try to make everything from 'single' user, that way you will omit those problems ever.

I don't have some 'guide' on what needs to be done, probably you can just google for 'setfacl' package- it  can solve solve these types of problem. But I myselv try to run project stuff all from single - www-data user and never met this problem

(same applies to php-fpm, this also needs to run from this user as well as CLI)

**Comment by VarnishingJam** [comment]
Yes, and I fully agree with you there!
But, pretending we can't change the executing users, I'd still have to go for an ugly workaround (previewing in browser or even something like this http://stackoverflow.com/questions/17079369/is-that-possible-to-use-laravel-blade-outside-the-view-folder , what i am currently trying to get going) in order to renew the cached file from the right owner.
Why isn't there something like View::compile('myView') which does the exact same thing as laravel does internally when viewing a view in the browser?

**Comment by srmklive** [comment]
5.2 is not officially supported anymore. Does the same issue occurs in 5.4?

**Comment by themsaid** [comment]
You need to set proper permission configurations for the storage folder or for your user B to be able to write to A's files.

Closing since it's not framework related, you can post the question on the forums though, we try to keep this repo for bug reporting only.

**Comment by VarnishingJam** [comment]
For those who are looking for a workaround:

$fs   = new \Illuminate\Filesystem\Filesystem;
$CacheFolder = storage_path('framework/views');
$comp = new Illuminate\View\Compilers\BladeCompiler($fs, $CacheFolder); 
$comp->compile('path/to/your/view.blade.php');

This forces the compiled file to recompile with the currently active user.
