### ISSUE TITLE
Documentation issue - Blade Templates

### ISSUE THREAD

**Issue by dvLden** [laravel/framework#17829]
### Description:
I am going through documentation completely. So far I am at Blade Templates and I noticed one issue, which I assume might be just typed by mistake?

### Steps To Reproduce:
Visit one of following:
https://laravel.com/docs/5.0/templates#blade-templating
https://laravel.com/docs/5.1/blade#template-inheritance
https://laravel.com/docs/5.2/blade#template-inheritance
https://laravel.com/docs/5.3/blade#template-inheritance
https://laravel.com/docs/5.4/blade#template-inheritance

In the Defining a Layout snippet sample, there's this:
```blade
@section('sidebar')
    This is the master sidebar.
@show
```

So as I learned so far, to open and close section, it'd be like this:
```blade
@section('name')
    Stuff inside...
@endsection
```

But in the snippet it ends with `@show`. Am I unfamiliar with that and what it represents, or it's an mistake?

**Comment by themsaid** [comment]
- `@endsection` and `@stop` stops adding more content to the section.
- `@show` stops adding more content and immediately return the section content.
- `@overwrite` sets the content of the section and overwrites any previous content that was set.

You can find more details about the different uses cases if you search online :)
