### ISSUE TITLE
[5.4] Nullable Validation Rules & required_...

### ISSUE THREAD

**Issue by set0x** [laravel/framework#17837]
If a field has a **`required_with`** validation and is present the other field should not be **`nullable`** the other field, should not be invalid a null?

```php
'n_brothers'=> 'required_with:brothers_place_of|numeric|nullable',
'brothers_place_of'=> 'required_with:n_brothers|numeric|nullable',
```
How to validate this?

**Comment by themsaid** [comment]
I don't understand :) Can you share sample data that should pass the validation?

**Comment by set0x** [comment]
The field **`type_of_food`** should be **null**  only if  `lunch`or `meal` or `snack` are false.

```php
'lunch'=> 'required|boolean',
'meal'=> 'required|boolean',
'snack'=> 'required|boolean',
'type_of_food'=> 'in:crushed,whole|required_if:lunch,1|required_if:meal,1|required_if:snack,1|nullable',
```

My English is not very good. Sorry

**Comment by themsaid** [comment]
That looks to me like a complex rule that you can use `sometimes()` for, check http://themsaid.com/laravel-advanced-validation-conditionally-adding-rules-20170110/.

**Comment by set0x** [comment]
But, if the rule required_if is activated,  the value `null` should not be valid.

**required**

The field under validation must be present in the input data and not empty. A field is considered "empty" if one of the following conditions are true:

* The value is null.

`required_ ... ` should works the same way.

**Comment by borex** [comment]
I have the same problem and can't find a way to setup proper rules.
I have a dropdown where user can select from different options and a textbox where an url can be entered. The textbox value is only required if 'url' option is selected in the dropdown, but for any other selection textbox's value is not required and will have null as value.
I have setup the following rules:
'dropdown' => 'required',
'textbox' => 'required_if:dropdown,url|url',

If dropdown value is different then 'url' value, the textbox's **url** validation rule is triggered and returns a failed result.
I have tried **sometimes** and **nullable** rules on textbox without success.
If I add **nullable** rule to textbox then the **required_if** rule doesn't validate when dropdown's value is 'url' and textbox's value is null.

I'm thinking of creating a new rule for url that doesn't validate null or empty string. I did this with the **exists** rule (same problem), I wrote my own exists_or_null rule for similar scenario but I don't think this is a good approach to replace current rules just to handle null values.

Is there a better way or does anybody have a suggestion for rules setup?

**Comment by rolandas-valantinas** [comment]
```
            'order_product_id' => 'nullable|uuid',
            'description'      => 'required_without:order_product_id|string',
```
`order_product_id === 1`
`description === null`

```
"description" => array:1 [
    0 => "validation.string"
  ]
```
This is ridiculous bug!

**Comment by thecodemill** [comment]
I'm finding this also in 5.4. Adding `nullable` negates the `required_with` rule. In my use case, it's when dealing with array fields:

```
$rules = [
    'email_address.2' => ['email'],
    'required_with_email_address.2' => ['nullable', 'required_with:email_address.2']
];
```

Submitting a value in `email_address[2]` field and leaving `required_with_email_address[2]` blank does not trigger the `required_with` error for me.
