### ISSUE TITLE
[5.4] Plurals in __() JSON translation

### ISSUE THREAD

**Issue by cjmaxik** [laravel/framework#17836]
Is there any chance to use plurals in JSON translations with `__()` helper?

https://github.com/laravel/framework/pull/16424 https://github.com/laravel/framework/pull/16470 https://github.com/laravel/framework/commit/94372447b9de48f5c174db2cf7c81dffb3c0c692

**Comment by themsaid** [comment]
I don't think it's planned, anyways you can post on the https://github.com/laravel/internals repo. That's where we keep track of feature requests.

**Comment by niksumeiko** [comment]
@themsaid, I'm a bit confused with this and feel like you're best at making it clear.

We use your [`__()` helper](https://github.com/laravel/framework/pull/16424) with single `.json` file everywhere. 

```php
// In views:
__('Product :product was saved successfully.', [
  'product' => 'My product'
])

// And in `resources/lang/de.json`, obviously:
{ "Product :product was saved successfully.": "German translation" }
```
It just works. However, if we wish plural translation there's no way to avoid translation string in `trans_choise()`? We can't do something like this, right?

```php
trans_choice('[1,4] See all photos|[5,*] See all :photos photos', $photos, [
  'photos' => $photos
])
```
Does this mean for plural translations we have to use `resources/lang/de/messages.php` with `trans_choice()` and for others `resources/lang/de.json` with `__()` helper?

**Comment by bestmomo** [comment]
I'm a bit confused too for this point. It'd be easy to make transChoice method use json, something like this (I didn't dig deeper):

`public function transChoice($key, $number, array $replace = [], $locale = null)
{
    return $this->choice($this->getFromJson ($key), $number, $replace, $locale);
}`

So we can use choice in JSON files:

`"comment|comments": "commentaire|commentaires",`

Because what I have to do now is not very clean:

`trans_choice(__('comment|comments'), $number)`

**Comment by niksumeiko** [comment]
@bestmomo, `trans_choice(__('comment|comments'), $number)` works for me as well. And this way actually eliminates a need of storing plural (and any other) translations inside `resources/lang/en/*.php` file. All in JSON now.

I think, would be just awesome to introduce something like `_n()` helper for plural translations stored in JSON:
```php
function _n($id, $number, $replace = [], $locale = null) {}
```

**Comment by sebastiaanluca** [comment]
Added a very simple wrapper in our project based on @bestmomo's findings (thanks btw!):

```php
if (! function_exists('__choice')) {
    /**
     * @param string $key
     * @param int $count
     *
     * @return string
     */
    function __choice(string $key, int $count) : string
    {
        return trans_choice(__($key), $count);
    }
}
```

so you can do

```Blade
{{ __choice('results for', $total) }}
```

In your JSON translations, you can still use all default parameters and constructions:

```json
{
    "results for": "{0} Geen resultaten voor|{1} Eén resultaat voor|[2,*] :count resultaten voor"
}
```

**Comment by OzanKurt** [comment]
Sometimes you might need variables in these `$key` strings so it's okay to pass an array as well.
```php
if (! function_exists('__choice')) {
    /**
     * @param string|array $key
     * @param int $count
     *
     * @return string
     */
    function __choice($key, int $count) : string
    {
        if (is_array($key)) {
            return trans_choice(__($key[0], $key[1]), $count);
        }

        return trans_choice(__($key), $count);
    }
}
```

**Comment by MatLeRock** [comment]
I think it needs to be the following syntax:
`trans_choice(__($key, $replace, $locale), $number);`

Otherwise `$locale` wont work. Tested with Laravel 5.4.
