### ISSUE TITLE
Mail markdown config not working, memory issues

### ISSUE THREAD

**Issue by c0h1b4** [laravel/framework#17849]
- Laravel Version: 5.4.10
- PHP Version: 7.1.1 (ubuntu linux)
- Database Driver & Version:

MongoDB (jenssegers/laravel-mongodb)

### Description:

I have an updated Laravel project (initially 5.3) and I was following some of the Laracasts tutorials for Markdown emails when I found that on the config/mail.php there is no 'markdown' section. I tried to hardcode the markdown section manually like this:

    'markdown' => [
        'theme' => 'default',
        'paths' => [
            resouce_path('views/vendor/mail'),
        ]
    ],

After I save, artisan is not working anymore - I type php artisan and the prompt just hangs. And when I try to send an email I get a memory error from PHP-FPM:

Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 262144 bytes) in .../vendor/laravel/framework/src/Illuminate/Container/Container.php on line 621

### Steps To Reproduce:

Make a fresh 5.3 laravel project, upgrade to 5.4.
On the config/mail.php, insert the 'markdown' config code.
Everything goes crazy.
php artisan not working anymore and can't send emails.

**Comment by themsaid** [comment]
Sorry but that appears to be a problem with your application somewhere, I've upgraded a number of apps so far and no problem exists.

Please try to dig more and only open a new issue if you found an actual bug in the framework.

**Comment by c0h1b4** [comment]
Dear Mohamed,

I am reopening the issue because I just reproduced this issue on a fresh install.

Do I need to send you a video???

**Comment by hairmenu** [comment]
resouce_path should be resource_path
