### ISSUE TITLE
FilesystemAdapter : Why using the `url` configuration instead of `root` on LocalAdapter

### ISSUE THREAD

**Issue by shulard** [laravel/framework#17847]
- Laravel Version: 5.x
- PHP Version: all

### Description:

I'm currently using the filesystem feature in Laravel and I'm facing a problem/question. I want to be able to generate the path to a file using a `LocalAdapter`.

This can be done using the `Storage::url($path)` method. When I look in the code it seems that this method is relying on a `url` configuration to generate the "url". I think it can be useful to fallback on `root` if `url` is not defined because the local path is just starting by `root`...

This behaviour is the same on all the 5.x Laravel versions, I wanted to make a PR but can't find the right branch to start on...

**Comment by themsaid** [comment]
It's a breaking change, so 5.5 is the right branch.
