### ISSUE TITLE
[5.4]Carbon miss data when date-time column without seconds

### ISSUE THREAD

**Issue by ac1982** [laravel/framework#17846]
- Laravel Version: 5.4.*
- PHP Version:7.1.1
- Database Driver & Version:MySQL 5.7 

### Description:
if input datetime without seconds will be failure when creating a new record.

### Steps To Reproduce:
migration:
`$table->dateTime('action_time');`

controller:
`$request->input('action_time'); //2017-02-09 11:00  momentjs format it as "YYYY-MM-D H:mm"`

eloquent:
```
Actions::create(['action_time'=>$request->input('action_time')]);
//error  Carbon miss data.
```

I noticed asDateTime class doesn't have method to treat `Carbon::createFromFormat` if input without seconds.

**Comment by themsaid** [comment]
Well the convention assumes it's a date or a dateTime value, you'll have to handle any other forms yourself before passing the value to Eloquent.
