### ISSUE TITLE
Mail Markdown/memory issue after upgrading from 5.3 to 5.4.

### ISSUE THREAD

**Issue by c0h1b4** [laravel/framework#17851]
- Laravel Version: 5.4.10
- PHP Version: 7.1.1 (ubuntu linux)
- Database Driver & Version:

MongoDB (jenssegers/laravel-mongodb)

### Description:

I have an updated Laravel project (initially 5.3) and I was following some of the Laracasts tutorials for Markdown emails when I found that on the config/mail.php there is no 'markdown' section. I tried to hardcode the markdown section manually like this:

    'markdown' => [
        'theme' => 'default',
        'paths' => [
            resouce_path('views/vendor/mail'),
        ]
    ],

After I save, artisan is not working anymore - I type php artisan and the prompt just hangs. And when I try to send an email I get a memory error from PHP-FPM:

Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 262144 bytes) in .../vendor/laravel/framework/src/Illuminate/Container/Container.php on line 621

### Steps To Reproduce:

Make a fresh 5.3 laravel project, upgrade to 5.4.
On the config/mail.php, insert the 'markdown' config code, the upgrade didn't inserted this.
Everything goes crazy.
php artisan not working anymore and can't send emails.

**Comment by devcircus** [comment]
Are you pasting in your above config code exactly as you've pasted it here? If so, "resource_path" is misspelled. Artisan and composer will both throw errors with it spelled wrong.

**Comment by deleugpn** [comment]
How did you fix this?

**Comment by rationalthinker1** [comment]
Hello, I have this problem too.

**Comment by deleugpn** [comment]
@rationalthinker1 check all your Service Providers. You might have `$this->register()` where you're suppose to call `$this->app->register()`, which leads to infinite recursion.
