### ISSUE TITLE
Pivot key present despite hidden attribute

### ISSUE THREAD

**Issue by rorc** [laravel/framework#17854]
Laravel Version: 5.4.7

### Description:
With belongsToMany relation if i add `protected $hidden = ['pivot']`, key `pivot` are present after json serializing.

### Steps To Reproduce:
1. Create two models with belongsToMany relation
2. Add property `protected $hidden = ['pivot'];`
3. Call  `$model->with('relation')->toJson()`

### Expected behavior
Key `pivot` are not visible.

### Current behavior
Key `pivot` are present in result despite `$hidden = ['pivot']` 😕

**Comment by srmklive** [comment]
@rorc Laravel 5.5 :laughing:.

**Comment by srmklive** [comment]
Anyhow to your question, when you are writing any column names in the model `$hidden` array, this means that there should be a field called `pivot` in the actual database table.

**Comment by fernandobandeira** [comment]
It used to work like this on L4...

Could you try instead using the visible property?
```php
    protected $visible = ['first_name', 'last_name'];
```
Just add the fields that you want to see, anything that isn't there will be removed from the serialization...

**Comment by rorc** [comment]
Sry, i wrote `$visible` not on related model 😄
