### ISSUE TITLE
php artisan serve throws segmentation fault

### ISSUE THREAD

**Issue by gbrunacci** [laravel/framework#17850]
- Laravel Version: 5.4.10
- PHP Version: 7.0.9 on OSX
- Database Driver & Version: n/a

### Description: 

When adding a provider incorrectly, running `php artisan serve` throws `Segmentation fault: 11` with not enough debug information.

This usually happen when, in `config/app.php`, you miss the `::class` on an element in the 'providers' list.

Maybe we should catch the error and show a proper Exception?

### Steps To Reproduce:

1. Checkout a fresh Laravel,
2. In `/config/app.php` remove `::class` from any item in the providers array, for instance `Illuminate\View\ViewServiceProvider`
3. Run `php artisan serve`

**Comment by themsaid** [comment]
No plan to have something like this in the core, these silly mistakes are annoying but it's hard to catch them internally :)
