### ISSUE TITLE
Mail: Customizing The Components

### ISSUE THREAD

**Issue by cesargb** [laravel/framework#17857]
- Laravel Version: 5.4.10
- PHP Version: 7.0.15
- Database Driver & Version: mysql 5.5.52

### Description

In my case, I can not customize the CSS, after vendor:publish, in file resources/views/vendor/mail/html/themes/default.css and any template

This work well if I try modify de real source: vendor/laravel/framework/src/Illuminate/Mail/resources/views/html/themes/default.css

### Steps To Reproduce:

Steps describe in https://laravel.com/docs/5.4/mail#customizing-the-components

Thanks

**Comment by themsaid** [comment]
It appears to be working fine, can you please make sure you're editing the correct files?

**Comment by cesargb** [comment]
Thanks for your time, but I think that i change the correct file, this is the diff

`diff vendor/laravel/framework/src/Illuminate/Mail/resources/views/html/themes/default.css  resources/views/vendor/mail/html/themes/default.css
4c4
<     font-family: Avenir, Helvetica, sans-serif;
---
>     font-family: Helvetica,sans-serif;`

But the email arrive with font-family: Avenir, Helvetica, sans-serif; instead Helvetica,sans-serif. Don't overwrite the vendor file.

I dont understand why.

**Comment by themsaid** [comment]
We need a solid test, not based on a css property. Remove all content from the default.css in your `views/vendor/mail/html/themes/default.css` and see if the original css file is still loaded.

**Comment by cesargb** [comment]
I remove all content from default.css, now this file have 0 bytes sizes:

```
stat  resources/views/vendor/mail/html/themes/default.css
  File: «resources/views/vendor/mail/html/themes/default.css»
  Size: 0         	Blocks: 0          IO Block: 4096   fichero regular vacío
Device: ca31h/51761d	Inode: 26216482    Links: 1
Access: (0644/-rw-r--r--)  Uid: (10335/g54540604)   Gid: (  503/  psacln)
Access: 2017-02-10 17:04:07.404618671 +0100
Modify: 2017-02-10 17:04:07.404618671 +0100
Change: 2017-02-10 17:04:07.406618645 +0100
```

But the email arrive with original css files.

**Comment by cesargb** [comment]
Its my error, in the upgrade i forgot ad this section un config mail:

```
'markdown' => [
    'theme' => 'default',

    'paths' => [
        resource_path('views/vendor/mail'),
    ],
],
```
Im sorry Mohamed

**Comment by themsaid** [comment]
It's ok, no worries :)
