### ISSUE TITLE
SQLite QueryException with unionAll

### ISSUE THREAD

**Issue by ivanignat** [laravel/framework#17856]
- Laravel Version: 5.4.6
- PHP Version: 7.0.12
- Database Driver & Version: MySQL 5.7.16

### Description:
I'm getting different SQL queries on MySQL and SQLite when I use "unionAll" method of Query\Builder. I see that MySQLGrammar.php has it's own compileUnion method, however I'm getting following error when I'm trying to unit test query scope with SQLite:

**Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1 LIMIT clause should come after UNION ALL not before (SQL: select * from "members" where "region_id" = 11f440c4-ea9f-46ad-a27d-86414261b605 limit 10 union all select * from "members" where "region_id" = 1e20ceea-e32d-4a99-86ec-9da7b2e6a0ec limit 40)**

### Queries that I get:

- With MySQL

**`
(select * from `members` where `region_id` = ? limit 10) union all (select * from `members` where `region_id` = ? limit 40)
`**

- With SQLite

**`
select * from "members" where "region_id" = ? limit 10 union all select * from "members" where "region_id" = ? limit 40
`**

**Comment by arjasco** [comment]
Submitted a PR for this. 

SQLite doesn't support the same syntax as MySQL for instance. If you didn't have your limit clauses then it would work as expected. So the solution which most agree upon is to wrap the main query in a sub select.

**Comment by ivanignat** [comment]
@arjasco thanks for the PR and explanation!
