### ISSUE TITLE
laravel TokenMismatchException in VerifyCsrfToken.php line 67:

### ISSUE THREAD

**Issue by siempay** [laravel/framework#17863]
- Laravel Version: 5.2
- PHP Version: 5.5
- Database Driver & Version:mysql

### Description:
I'am getting this error randomly, In ajax requests and even when I want to login. If I had logged in, the session ends so fast like in some minutes even if I set 'lifetime' => 1200,. I dont know why I have to refresh page every time there is a ajax request.

### Steps To Reproduce:
 I know about the csrftoken, I have it in my form as `<input type="hidden" name="_token" value="{{csrf_token()}}">` , and I have `<meta name="_token" content="{{csrf_token()}}">` , and

            $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': '{{$encrypted_token}}'
            }
        });
but yet I dont know why I'am getting this error TokenMismatchException in VerifyCsrfToken.php line 67: a lot on my local and sometimes on my server

**Comment by marky291** [comment]
Did you apply the the web middleware to the route ?

**Comment by siempay** [comment]
yes I did, I just noticed that in my remote server if I add https it works fine, I checked my config file and I got this `   

    'secure' => false,


    'http_only' => true,
`

in my local but in my server I have the `  'secure' => true, 'http_only' => false,`

what do I do to make it work also on my local because it is useless to add http to local `(http://local:8000) `

**Comment by themsaid** [comment]
Please ask on the forums, we try to keep this repo for bug reporting only.
