### ISSUE TITLE
Name of uploaded file should stay the same

### ISSUE THREAD

**Issue by jubi4dition** [laravel/framework#17866]
- Laravel Version: 5.4.10

### Description:
You changed the hashName function in FileHelpers.
You will get a different name every time you call hashName()

### Steps To Reproduce:
This code would make problems.

```
        $uploadedFile = $request->file('file');
        
        if (Storagefile::where('filename', $uploadedFile->hashName())->first() !== null) {
            return view('upload')->withInfo('File already exists.');
        }
        
        $uploadedFile->store(Auth::user()->foldername);
        
        $file = Storagefile::create([
            'filename' => $uploadedFile->hashName(),
            'mime' => $uploadedFile->getClientMimeType(),
            'original_filename' => $uploadedFile->getClientOriginalName(),
            'size' => $uploadedFile->getClientSize(),
            'user_id' => Auth::id()
        ]);
```

**Comment by themsaid** [comment]
Yes that was changed in laravel 5.4, you'll need to handle deleting the old file yourself.

**Comment by jubi4dition** [comment]
The deleting of the old file is not my problem yet.

The problem is, that i store the file, but when i call $uploadedFile->hashName() afterwards again, then i get a different file name. I think, that it is very confusing.

**Comment by themsaid** [comment]
I've proposed caching the generated hash for later use, if merged that should solve your issue: https://github.com/laravel/framework/pull/17879

Thanks :)
