### ISSUE TITLE
ErrorException' with message 'Argument 2 passed to Illuminate\Mail\Message::attach() must be of the type array

### ISSUE THREAD

**Issue by ezekel** [laravel/framework#17861]
I'm having difficulties in attaching file using Mailable in Laravel 5.3, I have folder resides in public folder 'attachment'. it always threw exception

`ErrorException' with message 'Argument 2 passed to Illuminate\Mail\Message::attach() must be of the type array`

but in laravel5.3 docs it says `->attach('/path/to/file');`

```
namespace App\Mail;



use Illuminate\Bus\Queueable;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\URL;

class PoattachmentEmail extends Mailable
{
    use Queueable, SerializesModels;
     public function __construct()
    {
       //
    }
public function build()
{
    $subject = 'Attention';

    return $this->view('emails.myview')
         ->attach(URL::to('/attachment/'.'newdata.xls'))
         ->subject($subject);
}

```

**Comment by themsaid** [comment]
I can't replicate your issue, are you sure you call attach with only a single parameter?

**Comment by ezekel** [comment]
@themsaid..yes onky 1 parameter..i just followed what the docs says

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/blob/5.4/src/Illuminate/Mail/Message.php#L197

**Comment by GrahamCampbell** [comment]
That function has remained the same for years.

**Comment by ezekel** [comment]
@GrahamCampbell , 

Too fast to close, I did not test yet...so what do you mean  ? is my code ok  or there is something missing ?

Thank you in advance.

**Comment by GrahamCampbell** [comment]
Please ask on the forums. This issue tracker is for bugs in the framework only please.

**Comment by Mustafa-Tanim** [comment]
Too few arguments to function Illuminate\Routing\Router::view(), 1 passed in C:\Users\Asus\blog5.8\vendor\laravel\f
  ramework\src\Illuminate\Support\Facades\Facade.php on line 237 and at least 2 expected
.
.
What is the solution of this problem??

**Comment by BrandonSurowiec** [comment]
Ran across this today. One cause of this error is if you assign `$this->attachments = ` in the Mailable constructor. You will be overriding the mailable's internal `$attachments` variable and it will trigger this exception. The solution is to rename your `$attachments` variable to something else.
