### ISSUE TITLE
Ability to tell if relations have been loaded with additional constraints or not

### ISSUE THREAD

**Issue by rokkamokka** [laravel/framework#17872]
- Laravel Version: 5.4
- PHP Version: 7.1

### Description:

We have a problem that arises where we have helper functions or service methods that would like to take advantage of pre-loaded relations to reduce the number of queries, but where we cannot be sure if the relationship has been pre-loaded with constraints or not.

Example (made up, but hopefully you get the point):

    function getUnreadNews(User $user) {
        return $user->news()->where('read', 0)->get();
    }

This works fine, but we will always make a query for each user. If we run this on 100 users, that's 100 extra queries. So we rewrite it to take advantage of pre-loaded relations:

    function getUnreadNews(User $user) {
        return $user->news->where('read', 0);
    }

This will not do any additional queries, assuming we've already pre-loaded the news() relation on each user. However, if we've pre-loaded the relationship with constraints:

    $users->load(['news' => function($q) {
        $q->where('read', 1);
    }])

**getUnreadNews()** will no longer work correctly, since the pre-loaded relationship already filtered out the unread news. Our helper function cannot know if the relationship is "tainted" (constrained) or not, so we cannot trust it.

We could work around this if we had something like the **relationLoaded()** method on **Model**, but which could tell us if the relation is loaded with constraints or not.

    function getUnreadNews(User $user) {
        if ($user->relationLoaded('news') && !$user->relationConstrained('news')) {
            return $user->news->where('read', 0);
        } else {
            return $user->news()->where('read', 0)->get();
        }
    }

or perhaps

    function getUnreadNews(User $user) {
        if ($user->pureRelationLoaded('news')) {
            return $user->news->where('read', 0);
        } else {
            return $user->news()->where('read', 0)->get();
        }
    }

This would avoid doing additional queries if the unconstrained relation is loaded, and would fall back to doing new queries if the loaded relation is tainted (or if no relation was loaded).

Thoughts? I admit the made up example above is forced, but we have run into this scenario a few times in our code base where we've "tainted" relations by pre-loading them with constraints, causing unforeseen consequences elsewhere when we've assumed a relation isn't loaded or is only loaded without constraints. Perhaps there's some other way of working around this?

**Comment by themsaid** [comment]
I think the forums is a better place for such question :) We try to keep this repo for bug reporting only.

Solution to this depends on the use case imo, if you're displaying all records for an HTML table or API or something I'd say load without constrains and then filter whatever results you added the constrain for later.
