### ISSUE TITLE
AuthenticatesUsers logout redirects to / 

### ISSUE THREAD

**Issue by VinceG** [laravel/framework#17881]
- Laravel Version: 5.4 / master
- PHP Version: 7.0.8
- Database Driver & Version: MySQL 5.6

### Description:

AuthenticatesUsers trait does not allow to override the logout redirect route/location

It's hardcoded to / which in a lot of cases does not work, it should be a property on the trait that we can override in order to redirect to a different location. we have multiple authentication sections with different guards that should redirect to different locations after the user logs out, right now we are forced to override the entire logout method.

https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Auth/AuthenticatesUsers.php#L161

I can create a pull request to add the 'redirectAfterLogout' property we used to have.

5.2 branch
https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Auth/AuthenticatesUsers.php#L178

Thank You.

**Comment by srmklive** [comment]
I don't think there is a need to have a separate variable for default functionality.  You can override the function in your `LoginController` and use a variable to set a route after logout.

**Comment by VinceG** [comment]
@srmklive Yeah, we all understand that. but the idea of overriding an entire method to just set the redirect property beats the purpose of OOP. We can't just override core methods and expect everything to just work magically when we upgrade, hence this change which changed the logout method signature, if we would've overrode the method we wouldn't get the latest changes for that method.

I truly believe this is just an oversight since this is something that was there and was useful. I'll submit a PR to make it easier to fix this.

Also, this wasn't documented in the upgrade guide so in essence a small breaking change for us once we upgraded.
