### ISSUE TITLE
ConvertEmptyStringsToNull not working for nested items

### ISSUE THREAD

**Issue by rorc** [laravel/framework#17886]
Laravel Version: 5.4.7

### Description:
Middleware `ConvertEmptyStringsToNull` not save `null` value for nested keys.

### Example
`fio === ''` => after middleware `fio === null`, but `someEntity.fio === ''` => after middleware `someEntity.fio` keeps  `''` (empty string)

**Comment by arjasco** [comment]
Can we see and example of input data?

Tested nesting and I'm getting expected nulls here.

**Comment by rorc** [comment]
@arjasco This fixed in 5.4.11, thx 😄
