### ISSUE TITLE
Echoing Data If It Exists operation returns 1

### ISSUE THREAD

**Issue by raymyid** [laravel/framework#17884]
- Laravel Version: 5.3.*
- PHP Version: 7.0
- Database Driver & Version: 5.7

### Description:
`{{ isset(Auth::user()->name) ? Auth::user()->name : 'default name' }}` is ok.
`{{ Auth::user()->name or 'default name' }}` returns 1
I don't know the operation is wrong?

### Steps To Reproduce:
`{{ Auth::user()->name or 'default name' }}`

**Comment by devcircus** [comment]
I thought 'or' was just a logical 'or' '||' for blade.

**Comment by mariomka** [comment]
@devcircus Blade provides a shortcut to writing ternary operations.

Seems to this shortcut only works with simple variables like ``$name``.

Test the following codes on tinker:

```php
Blade::compileString('{{ $name or \'default name\' }}');
// Returns: <?php echo e(isset($name) ? $name : 'default name'); ?>
```

```php
Blade::compileString('{{ Auth::user()->name or \'default name\' }}');
// Returns: <?php echo e(Auth::user()->name or 'default name'); ?>

```

**Comment by mariomka** [comment]
By the way, in PHP 7.0 you can use [null coalescing operator](http://php.net/manual/en/language.operators.comparison.php#language.operators.comparison.coalesce).

@taylorotwell As the 5.5 release will require PHP 7.0 the 'or' blade operator can be removed and start using null coalescing operator instead.

**Comment by GrahamCampbell** [comment]
Yes, the `??` operator is recommended over `or`, but `or` is not getting removed from the framework yet. It will be removed from the docs in Laravel 5.5 though.
