### ISSUE TITLE
LoginController's $redirectTo got nullified by the session's "url.intended"

### ISSUE THREAD

**Issue by cirdog** [laravel/framework#17891]
- Laravel Version: 5.4.11
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7

### Description:
LoginController's **$redirectTo** got nullified by the session's **url.intended** (set by the previous "post-logout redirect as guest"). The "url.intended" actually **took precedence** over $redirectTo **everytime** under the "redirect to intended" logic below:

\Illuminate\Foundation\Auth\ **AuthenticatesUsers** :96
```
protected function sendLoginResponse(Request $request)
    {
        $request->session()->regenerate();

        $this->clearLoginAttempts($request);

        return $this->authenticated($request, $this->guard()->user())
                ?: redirect()->intended($this->redirectPath());
    }
```

### Steps To Reproduce:
1) Say App\Http\Controllers\Auth\LoginController's **$redirectTo** is set to "**/home**".
2) Login once, then Logout, then go check the session's "**url.intended**" value. It's being set to "http://blah.com" (root path, hardcoded) by the Logout process since the **guest** tried to access the "root path" right before it got redirected back to "/login", then this path is being **stuck** as "url.intended" as long as the session lives.
3) Then try to login successfully again, but it won't ever be redirected to "/home" **as configured**, because the 'url.intended' **overpowered** the '/home' (redirectTo) **every time**.

I've checked AuthenticatesUsers' commit history but sorry I have not pinpointed the purpose of that "redirect()->**intended**($this->redirectPath())", would anyone please shed some light on it? **EDIT: I know what it does now, it's the "intended path" right before you got kicked for not being authenticated.**

And I think it's better to find a way to **keep the purpose** of that "redirect to intended url" while letting "redirectTo" **working properly**, right?

Thanks for looking into it.

**Comment by mariomka** [comment]
I got the same issue. "url.intended" is set when load a protected route (to back again after login). When root path is protected it always set the parameter in the session.

Don't save the parameter if it is the root path can be a solution.

**Comment by cirdog** [comment]
```
Me: I know what it does now, it's the "intended path" right before you got kicked for not being authenticated.
```
Yes, besides excluding the "root path", we could also **not set** the session's "url.intended" when it's **logging out** since it's hardcoded to "/" for the time being (#17881), so without the hardcoding it could be any path we set as **$logoutRedirectTo** (if it becomes configurable).

Actually I think the core logic here is to **exclude** ANY **non-user-intended path** from being set as "url.intended", since it's in fact NOT **explicitly intended** by the users, but by the system automatically, even if these internal-redirects are configured by the users.

**Comment by srmklive** [comment]
you need to override the `authenticated` function in your `LoginController` to set a proper redirect path after successful login. This is the better method in my opinion.

**Comment by cirdog** [comment]
```
protected function sendLoginResponse(Request $request)
    {
        $request->session()->regenerate();

        $this->clearLoginAttempts($request);

        return $this->authenticated($request, $this->guard()->user())
                ?: redirect()->intended($this->redirectPath());
    }
```
Overriding `authenticated` certainly is an option, but it's more like a "workaround" to me.

The reason is that `LoginController@$redirectTo` is **STILL** being nullified under the current "post-successful-login-redirect" logic, no matter I work it around or not. The **real point** is not really about whether or not I can make it work by any means, but more of whether the current logic is **sound** or not.

The current logic allows the "unintended path" `/` to be **registered** & **overpowering** the actual "intended path" `/home`, that's why I vouch against it since it's not at all "intended" by the users.

Excluding "system redirects" from being registered as "intended url" is more of a sound solution to me.
