### ISSUE TITLE
Question: localization helper and namespaced lang.json files?

### ISSUE THREAD

**Issue by cjaoude** [laravel/framework#17909]
does the translation helper `__(...)` work with namespaces?

for example...
`$this->loadTranslationsFrom(__DIR__.'/path/to/translations', 'courier');`

so this doesn't work as far as i can tell:   `__('courier::I love programming')`

it'll work just fine with `trans()` or `@lang`

Not supported or am I goofing it up?

Tnx!

**Comment by themsaid** [comment]
That's not supported no, it only works for regular array translations.
