### ISSUE TITLE
Route order with resource controller

### ISSUE THREAD

**Issue by martin-heralecky** [laravel/framework#17900]
- Laravel Version: 5.4.0
- PHP Version: 7.0.13

### Description:
I have a resource route from which I exclude the "create" route and make it manually, because I need to add an optional parameter:
```
Route::resource('invoices', InvoiceController::class, ['except' => 'create']);
Route::get('invoices/create/{customer?}', 'InvoiceController@create')->name('invoices.create');
```
This gives me an error: __No query results for model [App\Models\Invoice].__

However, if I reverse the order of these two statements like this:
```
Route::get('invoices/create/{customer?}', 'InvoiceController@create')->name('invoices.create');
Route::resource('invoices', InvoiceController::class, ['except' => 'create']);
```
It works well.

I don't know why does it do that but I think this behavior isn't correct.

**Comment by rs-sliske** [comment]
Route::resource will register the route Route::get('invoices/{invoice} behind the scenes

if this comes before your custom create, then when you try to navigate to /invoices/create, it will go through the list and use the first one it gets to which matches the pattern, in this case it would be Route::get('invoices/{invoice} and try to find one with an id of 'create'

**Comment by martin-heralecky** [comment]
Haven't thought of that :) Thanks!
