### ISSUE TITLE
Laravel 5.4 container->make() no longer accepts params

### ISSUE THREAD

**Issue by lougreenwood** [laravel/framework#17901]
- Laravel Version: 5.4
- PHP Version: 7.1.1
- Database Driver & Version:

### Description:

container->make() can no longer accept params. I moved from PHP-DI to illuminate container and it was a drop-in replacement with Laravel 5.3.

I've now upgraded my project to Laravel 5.4 and make no longer can be used to create new instances where the params need to be defined.

See http://php-di.org/doc/container.html#make for info on how it is implemented there.

### Steps To Reproduce:

$something = $app->container->make( 'someClass', ['someParam' => $someValue] );

**Comment by GrahamCampbell** [comment]
Yes, this feature was dropped from Laravel 5.4.

**Comment by GrahamCampbell** [comment]
We can't process issues with other packages here I'm afraid.

**Comment by lougreenwood** [comment]
Yeah, I just noticed it in the upgrade guide... Thanks
