### ISSUE TITLE
Issue with HasManyThrough when far model has a column with same name as intermediate model key

### ISSUE THREAD

**Issue by olibar** [laravel/framework#17918]
- Laravel Version: 5.3
- PHP Version:  7.0.11
- Database Driver & Version: MySQL

### Description:
When using a HasManyThrough relationship, if the far model has a property that has the same name as the intermediary model's foreign key, the value of the property in the result is overwritten with the value of the foreign key

### Steps To Reproduce:

Consider the following models:

Company
   id 
   name

Product
   id
   company_id

ProductAssignment
  id
  product_id
  company_id 

The case is that a Company HasMany Product and each Products can be assigned for distribution to many other companies. The assignments are stored in the ProductAssignment model
example
company A has 2 product AA and AB
AA is assigned to company B and D
AB is assigned to company C

Relationships defined:
`
Class Company{
   public function products() {
    return this->hasMany('Product')
}
  public function product_assignments(){
 return this->hasManyThrough('ProductAssignment','Product','company_id','product_id','id'
}

}
Class Company{
   public function product_assignments() {
    return this->hasMany('ProductAssignment')
}

}
`
when retrieving a company's product_assignments, the company_id of the related ProductAssignment are overwritten with the value found in the intermediary table

this is due to function getSelectColumns in Eloquent\HasManyThrough class:
`
    protected function getSelectColumns(array $columns = ['*'])
    {
        if ($columns == ['*']) {
            $columns = [$this->related->getTable().'.*'];
        }

        return array_merge($columns, [$this->parent->getTable().'.'.$this->firstKey]);
    }
`
 [$this->parent->getTable().'.'.$this->firstKey] shouldnt be added or should have an alias

**Comment by themsaid** [comment]
> when retrieving a company's product_assignments, the company_id of the related ProductAssignment are overwritten with the value found in the intermediary table

Shouldn't the company_id in the two table be the same? Overriding won't be an issue then. no?

**Comment by farwel** [comment]
We have a similar problem with this, adding $this->firstKey to the select on the query overwrites the $this->related->getTable() field that has the same name in the two tables (in our case the firstKey is "id", so the values are diferent).

The question here is: why is necessary to add [$this->parent->getTable().'.'.$this->firstKey] to the select? Whithout this, the queries and relations will work perfectly.

**Comment by themsaid** [comment]
Can you @farwel  this but make sure tests will pass with your change.

**Comment by olibar** [comment]
agreed with  @farwel when removing the [$this->parent->getTable().'.'.$this->firstKey] it works like a charm. What is the intention for adding this ?

**Comment by staudenmeir** [comment]
`$this->parent->getTable().'.'.$this->firstKey` is necessary for eager loading.

**Comment by wamilomarov** [comment]
Is there any other solution without touching vendor files? At least aliasing could be added.

**Comment by staudenmeir** [comment]
Will be fixed in Laravel 5.8 (#25812).

**Comment by budhajeewa** [comment]
Thank you @staudenmeir ! :+1:

**Comment by staudenmeir** [comment]
@olibar Please close the issue.

**Comment by olibar** [comment]
Thanks @staudenmeir ! I am closing the issue.

**Comment by hexiaodong2010** [comment]
mark
