### ISSUE TITLE
[5.4] Migration issues after upgrading from 5.2 (Given SQL cannot run inside a transaction block)

### ISSUE THREAD

**Issue by eduacostam** [laravel/framework#17914]
- Laravel Version: 5.3.30
- PHP Version: 7.1.1
- Database Driver & Version: PostgreSQL 9.6.1

### Description:
I use postgres enumerations in several places https://www.postgresql.org/docs/9.6/static/datatype-enum.html and have migrations to alter them. The issue arises that Postgresql supports schema transactions in a lot of DDL actions but on some it does not. In particular the `ALTER TYPE name ADD VALUE 'value';` is not supported so running the migration results in an exception.

The case in older versions of Laravel was that I myself choose when to use a transaction inside a migration, instead of having the whole migration automatically run inside a transaction. The file and line in question is https://github.com/laravel/framework/blob/9d7d87c15debca58b8430cb2fe319a09f89adbde/src/Illuminate/Database/Migrations/Migrator.php#L324

### Steps To Reproduce:
Create a migration with up code:
```php
public function up()
{
    DB::statement("CREATE TYPE mood AS ENUM ('sad', 'ok');");
}
```
And then another one with:
```php
public function up()
{
    DB::statement("ALTER TYPE mood ADD VALUE 'happy';");
}
```

**Comment by eduacostam** [comment]
Just in case anyone else happens to run into this problem, you can bypass the transaction inside the migration by doing:
```php
public function up()
{
	DB::commit();
	
	DB::statement("ALTER TYPE mood ADD VALUE 'happy';");
	
	DB::beginTransaction();
}
```

Of course this is a horribly hacky way of solving this, but it works for the time being until a better fix is available.

**Comment by srmklive** [comment]
If you look at Laravel [documentation](https://laravel.com/docs/5.4/migrations#column-modifiers) here, you can't modify or rename columns of type `enum`. That's because Laravel utilizes `doctrine/dbal` for modifying database columns.

**Comment by eduacostam** [comment]
@srmklive thanks for answering, but I think that has nothing to do with the issue at hand. What you are linking is about the Schema generator of Laravel, but when working with migrations you are not obligated to use that, in fact I almost always use strait SQL so that I can take advantage of the many data types that PostgreSQL provides. 

In this case the Schema builder might not be able to alter enums once created, but Postgres most certainly does; with the condition that you can't alter them inside a transaction. The issue is that this was a non-issue in older versions of Laravel as the transaction was not implicit in the migration (which I think is a good change because most people don't realize that some databases have support for schema transactions) but in this particular case (and I imagine it's not the only case) there's a need to be able to mark a migration in such a way that Laravel does not run it inside a transaction block.

**Comment by eduacostam** [comment]
Issue is present in Laravel 5.4 as well.

**Comment by Dylan-DPC** [comment]
I don't think this is a laravel issue. And can be closed if you don't want to pursue it.
