### ISSUE TITLE
[5.4] Scout - get() not filtering columns

### ISSUE THREAD

**Issue by c0h1b4** [laravel/framework#17913]
- Laravel Version: 5.4.10
- PHP Version: 7.1
- Database Driver & Version: Mongodb (jenssegers/laravel-mongodb)

### Description:

When I use the scout search function and perform a get() command, it is getting all the columns. Even if I add a array of columns I wish my collection to have and add to the get(array) it doesn't filter the columns.

### Steps To Reproduce:

My model is called Item, and has the following attributes:

id
name
price
img_url
date_added

$collection = App\Item::search('pencil')->get(['id', 'name']);

I want a collection of items with only id and name attributes.

I get a collection with all attributes.

As I checked the laravel\scout\builder class, the get() method doesn't has the column filtering implemented...

**Comment by bozhkos** [comment]
@c0h1b4 , u can use pluck method after fetching results from Scout. $collection = App\Item::search('pencil')->get()->pluck('id', 'name');

**Comment by bozhkos** [comment]
@c0h1b4 , use `only()` method, to get what you want. 
```php
$collection = App\Item::search('pencil')->get()->only(['id', 'name']);

```

**Comment by c0h1b4** [comment]
@bozhkos, I tried but I'm getting an empty collection.

**Comment by GrahamCampbell** [comment]
Bug is with that mongo package.
