### ISSUE TITLE
Laravel 5.4 php artisan migrate displays errors

### ISSUE THREAD

**Issue by luongvupc** [laravel/framework#17916]
- Laravel Version: 5.4
- PHP Version: 7.1
- Database Driver & Version: MySQL

### Description:
I ran the command "php artisan migrate" on MAC OS X and recived errors:
php(2301,0x7fff756d0000) malloc: *** mach_vm_map(size=18446744071562067968) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
Segmentation fault: 11

Please help!

**Comment by huglester** [comment]
is it a vm? do you have enough ram? is RAM ok at all? seems more like os/soft/hw issues :|

**Comment by luongvupc** [comment]
Hi huglester, thanks for your feedback, I have resolved this problem. It caused because the default migration file

Schema::create('users', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->string('email')->unique();
            $table->string('password');
            $table->rememberToken();
            $table->timestamps();
        });
See the unique email field does not have any default string length. I fixed by adding the default value to it $table->string('email', 100)->unique();

**Comment by ortho23** [comment]
I agree with @luongvupc , however newer version of laravel contains error in migration for password_reset migration, make sure that if you use ->index() on either email or token, to set the default lenght as well e.g:
 Schema::create('password_resets', function (Blueprint $table) {
            $table->string('email', 60)->index();
            $table->string('token');
            $table->timestamp('created_at')->nullable();
        });
