### ISSUE TITLE
[5.4] How to use __('hello world') with package specific translations

### ISSUE THREAD

**Issue by marktopper** [laravel/framework#17923]
- Laravel Version: 5.4.11
- PHP Version: 7.0.15
- Database Driver & Version: N/A

### Description:
How can we have package specific translations to support the use of the new translation method in Laravel 5.4.
```
__('Hello world!')
```

**Comment by themsaid** [comment]
Actually there isn't a way to read package translations using the JSON loader since the loader is not namespaced, do you have a suggested solution for this?

**Comment by marktopper** [comment]
Maybe it could work like this:

#### Adding translations (like normall)
```
    public function boot()
    {
        $this->loadTranslationsFrom(__DIR__.'/translations', 'namespace');
    }
```
> Then it could also look for `*.json` files in that directory.

#### Getting name-spaced translation:
```
__('namepace::Hello world!');
```
> If not exists, it could look for `__('Hello world!')`.
> If that does not exists rather, then it could fallback to the text `Hello world!`.

**Comment by marktopper** [comment]
Or to make it simple it should just be possible to load translations json files via the service provider.

Then the JSON could look like this:
```
{
    "namespace::Hello world!": "Hello world!"
}
```

Or even
```
{
    "namespace": {
        "Hello world!": "Hello world!"
    }
}
```

**Comment by themsaid** [comment]
I think it's better not to namespace JSON translations, like __("Hello") is hello everywhere, the whole point is to make the translation keys natural so that you can use them without having to manage namespaces and keys.

For cases like you mentioned I think it's better to use the other loader, the array loader, rather than the JSON one.

**Comment by marktopper** [comment]
I am cool with using it without a namespace. But would it become possible to load JSON translations from a package then, like if a package have some predefined translations for specific languages that a user can always overwrite by making their own translations.

**Comment by themsaid** [comment]
Yes that seems like a good idea, I'll look into that :)

**Comment by marktopper** [comment]
Any progress @themsaid 😄

**Comment by akazorg** [comment]
Hello @themsaid, what's the status on this?
This is a great feature, please make it happen!! :)
Thanks

**Comment by abdgad** [comment]
Ideas:
- Ability to set a loader on the translator.
- Ability to set translations path on the loader.

**Comment by sangnguyenplus** [comment]
I hope this feature can update soon. I'm developing packages too. JSON translation should be namespaced because the language can differ with the same key.

**Comment by vibrantBits** [comment]
Maybe in L5.5? That would be a nice surprise.

**Comment by themsaid** [comment]
Here you go: https://github.com/laravel/framework/pull/20599
