### ISSUE TITLE
min validation rule fails when ConvertEmptyStringsToNull middleware is enabled

### ISSUE THREAD

**Issue by bkuhl** [laravel/framework#17926]
- Laravel Version: 5.4.11
- PHP Version: 7.1.1
- Database Driver & Version: n/a

### Description:

When `\Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class` is in use, https://laravel.com/docs/5.4/validation#rule-min doesn't see the initial field as empty.  So for instance, `password` needs to be at least 6 characters after the middleware has converted it to null.

### Steps To Reproduce:

 * Get a fresh Laravel project with a password (or really any other) field with a minimum value
 * Add the rule `'password'      => 'confirmed|min:6|max:60',`
 * Submit the form
 * You'll see "The password field must be at least 6 characters".

**Comment by instanceofmatt** [comment]
You need to add the ```nullable``` rule to allow nullable fields or a minimum length.  Refs: http://themsaid.com/laravel-convert-empty-strings-to-null-20170130/
