### ISSUE TITLE
Error on validator unique on secondary connection

### ISSUE THREAD

**Issue by rafwell** [laravel/framework#17922]
- Laravel Version: v5.3.30
- PHP Version: 7
- Database Driver & Version: SQL SERVER 2008

### Description:
When i have a unique validation for another database the validator throw an exception:

```
Whoops, looks like something went wrong.

1/1
ErrorException in Validator.php line 1527:
Undefined offset: 1

```

### Steps To Reproduce:
Create 2 databases. Default database is "teste", secondary is "teste2".
Create a validator unique like this: `unique:connection.teste2,users,login`
When submit a form, the exception's throwed

**Comment by KKSzymanowski** [comment]
As stated in the docs:

> #### Custom Database Connection
>
> Occasionally, you may need to set a custom connection for database queries made by the Validator. As seen above, setting unique:users as a validation rule will use the default database connection to query the database. To override this, specify the connection and the table name using "dot" syntax:
> 
> `'email' => 'unique:connection.users,email_address'`

Therefore you should say `unique:teste2.users,login`.
I haven't tested it in 5.3, only 5.4, but check if this solves your problem.

**Comment by rafwell** [comment]
Thanks, it solved my issue. Bad interpretation of text because my english is poor.
