### ISSUE TITLE
[5.4.11] Session store not set on request.

### ISSUE THREAD

**Issue by ryrobbo** [laravel/framework#17927]
- Laravel Version: 5.4.11
- PHP Version: 7.1.1
- Database Driver & Version: MySQL 14.4

### Description:

In my routes/web.php file I have a route:

    Route::match(['get', 'post'], 'profile/speaker', 'Profile\SpeakerProfileController@edit');

For the controller, I have this in its constructor:

``` php
public function __construct(Request $request)
    {
        parent::__construct();
        $this->currentUser = $request->session()->get('user');
    }
```

When requesting the route endpoint, I am getting a runtime exception of "Session store not set on request.". This is because the session hasn't started. To get the session to load I moved the StartSession middleware within Http/Kernel.php from the $middlewareGroups['web'] array to the $middleware property.

This is despite the fact that the docs (https://laravel.com/docs/5.4/middleware#middleware-groups) state that all routes within web.php execute the middleware in the 'web' group via the RouteServiceProvider.

### Steps To Reproduce:

See above.

**Comment by themsaid** [comment]
Check: https://laravel-news.com/controller-construct-session-changes-in-laravel-5-3
