### ISSUE TITLE
[5.3] {!! ... !!} blade syntax turning "or" in strings into ternary if statement.

### ISSUE THREAD

**Issue by r3oath** [laravel/framework#17934]
- Laravel Version: v5.3.30
- PHP Version: PHP 7.0.11-1+deb.sury.org~trusty+1

### Description:
When using the `{!! ... !!}` blade syntax and a string within a function argument contains the word `or`, the rendered view turns the statement into a ternary if.

### Steps To Reproduce:
Create a helper class, e.g. `Form`;

```php
<?php

namespace App\Helpers;

class Form
{
    public static function foo($a, $b)
    {
        $str = $a;
        $str .= $b;
        return $str;
    }
}
```

Inject it into the view;

`@inject('form_helper', 'App\Helpers\Form')`

Use the static function within the `{!! ... !!}` blade syntax;

`{!! $form_helper->foo('question', 'Do I like php or does php like me?') !!}`

Look at the resulting cached view source;

`<?php echo isset($form_helper->foo('question', 'Do I like php) ? $form_helper->foo('question', 'Do I like php : does php like me?'); ?>`

**Comment by themsaid** [comment]
I'm afraid it's a nofix, you'll need to store that string with `or` in a variable and pass it to the view.
