### ISSUE TITLE
[L5.4] Sync Model with other ->Integrity constraint violation

### ISSUE THREAD

**Issue by leclercJulien** [laravel/framework#17930]
- Laravel Version: 5.4.10
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7.17

### Description:
I have this issue "SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '21' for key 'PRIMARY'.
I understand the problem, but after inspection, I have found the variable "exists" in Model was not  "true" but "false" when i save my model and with a mutator who save this model before add sync with an other model. 
It's a bug, or i do something bad ?

PS: i don't have this issue with Laravel 5.2.

### Steps To Reproduce:
Controller
```
public function store(EstablishmentRequest $request)
    {
        $establishment = Establishment::create($request->all());
        return redirect(...);
    }
```

Model
```
Public function setCardsListAttribute($value)
    {
        if ($this->id == NULL)
            $this->save();
        return $this->cards()->sync($value);
    }
```

To solve this issue, I have found this option : (Illuminate\Database\Eloquent\Model - L500), but it's not a good solution, works only if there is an 'Id'
```
if ($this->exists || $this->id)
```

**Comment by themsaid** [comment]
It's very odd that you're trying to save the model while mutating one of its attributes, mutators aren't meant to be used to set relationships as well.

Save the model and then save the relations, I can imagine your approach causing many issues, maybe duplicate model creation is one of the problems you'll face, because you save the model while in the middle of an operation that should actually save the model !!

**Comment by devcircus** [comment]
Like @themsaid stated, you will indeed get very strange behavior using a mutator this way. A mutator is responsible for setting the value of an attribute on the model. Calling 'save' and performing a 'sync' operation inside a mutator, will definitely cause problems. Not sure exactly what you're trying to accomplish but if you need to make decisions and perform operations when 'saving', maybe hook into the 'saving' event? Or just save the model and then perform any sync operations.

**Comment by leclercJulien** [comment]
Ok, I do something mal ;)
Thx for your comments.
