### ISSUE TITLE
Feature Request: ON DUPLICATE KEY UPDATE

### ISSUE THREAD

**Issue by reno1979** [laravel/framework#17938]
- Laravel Version: 5.4
- PHP Version:  #7.1
- Database Driver & Version: Mysql 

### Description:
The plugin https://github.com/yadakhov/insert-on-duplicate-key is bringing additional import enhancements to our product, but the plugin needs some work. 

The given functionality is for the MYSQL databases. But I can imagine that this could be rewritten to also address the other engines.

**Comment by themsaid** [comment]
Not sure if it's available in all supported drivers, anyway please pot to the internals repo 
the https://github.com/laravel/internals repo, it's where we keep feature requests.
