### ISSUE TITLE
[5.4]Only define a post route URI, "get" mehtod will throw exception without 404 not found.

### ISSUE THREAD

**Issue by ac1982** [laravel/framework#17936]
- Laravel Version: 5.4.*
- PHP Version:7.1.1
- Database Driver & Version:MySQL 5.7

### Description:

But most of the time, without define the route, throw 404 would be better.
I have to define a get method and throw a 404 not found.

### Steps To Reproduce:
```
Route::post('/abc', 'HomeController@index');
// http://demo.dev/abc will throw exception and terminate.
```

**Comment by themsaid** [comment]
Yes it'll throw a HTTP Error 405 "Method not allowed", if you add a `views/errors/405` view it'll render a response of your choice.

**Comment by srmklive** [comment]
you need to create a view file `resources/views/405.blade.php` and write appropriate error messages there.
