### ISSUE TITLE
[5.4] Very strange behaviour with routes containing dot character

### ISSUE THREAD

**Issue by alberto-bottarini** [laravel/framework#17939]
- Laravel Version: 5.4.9 + previous versions
- PHP Version: 7.0.15-1+deb.sury.org~trusty+1

### Description:
It seems that route parameters containing one or more dot (.) collide if the character just after the binding is a dot. 
By default, dots are accepted into route bindings. But when route contains an extension (separated by a dot) something weird occurs.

### Steps To Reproduce:

Create two routes:
````php
Route::get('/test-route-without-extension/{first}-{second}', function ($first, $second) {
    dd($first, $second);
});

Route::get('/test-route-with-extension/{first}-{second}.html', function ($first, $second) {
    dd($first, $second);
});

Route::get('/test-route-with-extension-and-pattern/{first}-{second}.html', function ($first, $second) {
    dd($first, $second);
})->where('second', '.*');
````

And then try to call them using these urls:

    http://localhost:8000/test-route-without-extension/aaa-bbb

It does match. `$first` is `aaa` while `$second` is `bbb`. 
_my thought: ok, everything is working well_

    http://localhost:8000/test-route-without-extension/aaa.aaa-bbb

It does match. `$first` is `aaa.aaa` while `$second` is `bbb`. 
_my thought: ok, dot is accepted as a binding character_

    http://localhost:8000/test-route-without-extension/aaa.aaa-bbb.bbb

It does match. `$first` is `aaa.aaa` while `$second` is `bbb.bbb`. 
_my thought: ok, dot is accepted as a binding character_

    http://localhost:8000/test-route-with-extension/aaa-bbb.html

It does match. `$first` is `aaa` while `$second` is `bbb`. 
_my thought: ok, everything is working well_

    http://localhost:8000/test-route-with-extension/aaa.aaa-bbb.html

It does match. `$first` is `aaa.aaa` while `$second` is `bbb`.
_my thought: ok, dot is accepted as a binding character_

    http://localhost:8000/test-route-with-extension/aaa.aaa-bbb.bbb.html

It doesn't match (return 404)
_my thought: wtf? why?? why if `$first` accepts dot, why `$second` doesn't accept? why the `.html` extension change the binding behaviour?_

    http://localhost:8000/test-route-with-extension-and-pattern/aaa-bbb.html

It does match. `$first` is `aaa` while `$second` is `bbb`. 
_my thought: ok, everything is working well_

    http://localhost:8000/test-route-with-extension-and-pattern/aaa.aaa-bbb.html

It does match. `$first` is `aaa.aaa` while `$second` is `bbb`. 
_my thought: ok, dot is accepted as a binding character_

    http://localhost:8000/test-route-with-extension-and-pattern/aaa.aaa-bbb.bbb.html

It does match. `$first` is `aaa.aaa` while `$second` is `bbb.bbb`. 
_my thought: wtf? why?? why where clause is mandatory only for `{second}`? why the `.html` extension change the binding behaviour?_

**Comment by themsaid** [comment]
Route parameters matching uses Symfony's Route compiler, I think it's better that you report this behaviour there since it's not in Laravel's core code.
