### ISSUE TITLE
Mail in Queue jobs: Unable to open file for reading attachment path

### ISSUE THREAD

**Issue by runbing** [laravel/framework#17935]
- Laravel Version: 5.3.28
- PHP Version: 7.0.8
- Database Driver & Version: MySQL & 5.7.13

### Description:

Use Mail class of Laravel (```$message->attach( $file )```) to send a attachment with Queue jobs( database ), if $file equal absolute path ```/home/vagrant/Code/test.io/storage/app/test.jpg```, it does not work, but when I do that with Queue jobs( sync ) It's worked. 

when I change $file to ```storage/app/test.jpg``` Queue jobs( database ) worked but Queue jobs( sync ) does not work. 

### Steps To Reproduce:

In my project, I need use Mail class of Laravel to send an attachment, for example: ```$message->attach( $file )```, the variable $file is a absolute path ```storage_path('app/test.jpg')```, the problem is when I push the task to queue jobs ( database ), it notice me "**Unable to open file for reading**" the file, but when I change the $file to ```'storage/app/test.jpg'``` or use queue jobs ( sync ) it works fine. 

Anybody tell me why? Thanks! and forgive my poor English. XD

**Comment by kindlefere** [comment]
This problem was not caused by Mail class. I should not run command ```php artisan queue:listen``` on my local machine, it's wrong, I need do it within the shell of homestead.

**Comment by runbing** [comment]
This problem was not caused by Mail class. I should not run command php artisan queue:listen on my local machine, it's wrong, I need do it within the shell of homestead.
