### ISSUE TITLE
[5.4] Where is the trans directive?

### ISSUE THREAD

**Issue by yusufyilmaz** [laravel/framework#17942]
- Laravel Version: 5.4.11
- PHP Version: 7.0.15

### Description:

I have been trying to work with new "awesome" json based translations. However, I have come up with an issue which I mentioned [here](https://github.com/laravel/framework/pull/17919) As @taylorotwell suggested using trans directive, but I cannot see trans directive in L5.4 documentation. And When I try to test trans directive in L5.4.11, blade is not picking up the directive, rather it just prints @ trans.....  Any suggestion with that?

**Comment by ntzm** [comment]
I can't find a `@trans` directive [here](https://github.com/laravel/framework/blob/5.4/src/Illuminate/View/Compilers/Concerns/CompilesTranslations.php) but maybe Taylor meant `{{ trans('foo.bar') }}`? See here: https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/helpers.php#L804

**Comment by yusufyilmaz** [comment]
@ntzm Thanks for the reply.

As I linked in my PR [here](https://github.com/laravel/framework/pull/17919), I have attached laravel-news article from [here](https://laravel-news.com/json-based-translations) You can see the trans "directive" at article. I also suggested another PR about "trans helper" which was rejected since "__ helper" is first using json based translations while "trans helper" is not using json based language files. 

So now in L5.4 we have different directives and helpers:

@ lang directive: This directive is not using json based language files. 
@ trans directive: There is no such directive in L5.4
trans helper: This helper is not using json based langauge files.
__ helper: This helper first using json based language. If not exists, it fallbacks to the default keyed language arrays.

It is obvious that there is a need to clarify these localization methods :)

**Comment by themsaid** [comment]
https://github.com/laravel/framework/pull/17919 was merged. Thanks for your efforts :)
