### ISSUE TITLE
Validation: Add Cross-Site Scripting Prevent rules

### ISSUE THREAD

**Issue by AbdelkaderBah** [laravel/framework#17950]
- Laravel Version: 5.4
- PHP Version: 7.1
- Database Driver & Version:

### Description:
There's no rule to prevent Cross-Site Scripting Prevention. Inputs dumped with scripts 

### Steps To Reproduce:
Rule: bind:script|bind:html
Error Message: ....

**Comment by themsaid** [comment]
No idea what you mean.

However for suggestions and feature requests please use the https://github.com/laravel/internals repo.
