### ISSUE TITLE
[5.4] Call to a member function isEmpty() on array

### ISSUE THREAD

**Issue by arcanedev-maroc** [laravel/framework#17959]
- Laravel Version: 5.4.12
- PHP Version: 7.1.0
- Database Driver & Version: MySQL 5.7.14

### Description:

I got a weird exception thrown because of my relation name.

I have an `events()` relationship with the `Speaker` model.

When i do something like this inside the `Speaker` Model:

```php
public function hasEvents()
{
    return ! $this->events->isEmpty()
}
```

I got this error: `Call to a member function isEmpty() on array`

When i checked the code, i found this [property that caused this issue](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php#L16) with my case.

**Suggestion:** Is there any chance that you change the `events` property name in that trait (`HasEvents`) to avoid any conflicts.

#### Models
```php
class Speaker extend Model {
    public function events() 
    {
        return $this->hasMany(Event::class);
    }

    public function hasEvents()
    {
        return ! $this->events->isEmpty()
    }
}

class Event extend Model {
    public function speaker() 
    {
        return $this->belongsTo(Speaker::class);
    }
}
```

#### Controller

```php
// SpeakersController

public function index()
{
    $speakers = Speaker::with(['events'])->paginate(50);

    return view('admin.speakers.list', compact('speakers'));
}
```

#### View

```blade
@foreach ($speakers as $speaker)
    <!-- Other stuff here -->
    @unless ($speaker->hasEvents())
    <a href="#deleteSpeakerModal" class="btn btn-xs btn-danger" data-toggle="tooltip" data-original-title="DELETE">
        <i class="fa fa-fw fa-trash-o"></i>
    </a>
    @endunless
@endforeach
```

**Comment by themsaid** [comment]
I'm closing this since it's not actually a bug, the opened PR is enough to show the problem.

Thanks :)
