### ISSUE TITLE
[5.4] Not Required but always check mimes 

### ISSUE THREAD

**Issue by vietdien2005** [laravel/framework#17951]
- Laravel Version: 5.4.12
- PHP Version: 5.6.29
- Database Driver & Version: MariaDB-10.1.21

### Description:
This's my code:
```
$rules = [ 'event_image'  => 'max:3000|mimes:jpeg,jpg,png'  ];

$messages = [
        'event_image.max'  => 'Pleae ensure the image is not larger then 3MB',
        'event_image.mimes'  => 'Please ensure you are uploading an image (JPG, PNG, JPEG)',
    ];

Validator::make(Request::all(), $rules, $messages);

```

I'm not require event_image but it always return 'Please ensure you are uploading an image (JPG, PNG, JPEG)'. I thought it must ignore mimes check

**Comment by salomoni** [comment]
https://laravel.com/docs/5.4/validation#conditionally-adding-rules

> In some situations, you may wish to run validation checks against a field only if that field is present in the input array. To quickly accomplish this, add the sometimes rule to your rule list:

**Comment by themsaid** [comment]
Take a look at http://themsaid.com/laravel-advanced-validation-conditionally-adding-rules-20170110/

It might be useful too.

**Comment by vietdien2005** [comment]
thank @themsaid @salomoni
