### ISSUE TITLE
[5.4] required_without validator is not working anymore

### ISSUE THREAD

**Issue by ghdoergeloh** [laravel/framework#17956]
- Laravel Version: 5.4.12
- PHP Version: 7.0.13

### Description:
Since my last Upgrade (5.2 to 5.4) my validation also needed an upgrade. I recognized that not required input form fields are not valid anymore, if they are empty. Of cause there was the nullable validator. So I fixed every broken validation. Now I tried to use the `required_without` validator. The problem with it:
## Goal 
(As a Sponsor you can either fill one or the other or both)
1. _should not be valid_
```
donation_per_lap = NULL
donation_static_max = NULL
```
2. _should be valid_
```
donation_per_lap = NULL
donation_static_max = 50
```
3. _should be valid_
```
donation_per_lap = 3
donation_static_max = NULL
```
4. _should be valid_
```
donation_per_lap = 3
donation_static_max = 50
```
That sounded for me as a typical example for `required_without`
So I tried:
## Case 1
```
Validator::make($data, [
'donation_per_lap' => ['required_without:donation_static_max', 'numeric'],
'donation_static_max' => ['required_without:donation_per_lap', 'numeric']
]);
```
In this case there is a problem with 2. and 3. because a NULL value is not a valid value, even when it is not required. (sounds logical seeing the change mentioned above).

## Case 2
```
Validator::make($data, [
'donation_per_lap' => ['nullable', 'required_without:donation_static_max', 'numeric'],
'donation_static_max' => ['nullable', 'required_without:donation_per_lap', 'numeric']
]);
```
In this case there is a problem with 1. because a NULL value is then a valid value.
So for one field (e.g. donation_per_lap) the validator is checking the other field (donation_static_max) for a valid value. The validator finds that there is a valid value (which is NULL) and so this field (donation_per_lap) is not required anymore.

Now for me there is no possible way to use `required_without` in the way it should work. Correct me if I'm wrong.

**Comment by devcircus** [comment]
Looks like a good use-case for 'sometimes'. Checkout [this post](http://themsaid.com/laravel-advanced-validation-conditionally-adding-rules-20170110/) by @themsaid.

**Comment by themsaid** [comment]
Yes you need more advanced validation conditions, I suggest you look at the post shared in @devcircus comment.

**Comment by ghdoergeloh** [comment]
Okay, thanks, I'll try that. So just to understand this: what is `required_without` for?
