### ISSUE TITLE
Illuminate Request class has inconsistent values when using dot syntax

### ISSUE THREAD

**Issue by spamoom** [laravel/framework#17968]
- Laravel Version: 5.0+
- PHP Version: Any
- Database Driver & Version: N/A

### Description:
Keeping inline with the rest of the Laravel classes, I would expect `$request->get('item')` to return the same value as `$request->item` and `$request->input('item')`.

When dealing with array items, it is apparent that the get() method comes straight from Symfony and has not been overridden by the Laravel Request class.

### Steps To Reproduce:

Post a multidimensional form array.

```php
var_dump(
    $request->all(), // ['items' => [1 => 'hello', 2 => 'laravel']]
    $request->has('items.1'), // true
    $request->input('items.1'), // 'hello'
    $request->get('items.1') // null
);
```

**Comment by themsaid** [comment]
Don't use get, always use input.

Here's from the docblock of get() inside Symfony's Request:

```
     * This method is mainly useful for libraries that want to provide some flexibility. If you don't need the
     * flexibility in controllers, it is better to explicitly get request parameters from the appropriate
     * public property instead (attributes, query, request).
```
