### ISSUE TITLE
Illuminate\Console\Command doesn't support variable number of arguments

### ISSUE THREAD

**Issue by zmorris** [laravel/framework#17962]
- Laravel Version: 5.x.x
- PHP Version: 7
- Database Driver & Version: MySQL 5

### Description:

Not sure if this is an issue or feature request.

Currently there is no way to specify an arbitrary number of arguments for console commands.  The closest we can get is something like:

```
protected $signature = 'my:command {path?}';
```

But that limits us to N hardcoded commands.  It would be nice to have a syntax like one of the following:

```
protected $signature = 'my:command {}';
protected $signature = 'my:command {?}';
protected $signature = 'my:command {*}';
protected $signature = 'my:command {...}';
```

Then we could look in `$this->argument()` to see the additional arguments, perhaps represented as an array under the corresponding key ('', '*', '...' etc) or something.

### Steps To Reproduce:

Try creating a command with the example $signature above.  Then feed it `php artisan my:command *` which causes the shell glob to pass all of the files in the current directory in as individual arguments.  You will see:

```
  [Symfony\Component\Console\Exception\RuntimeException]    
  Too many arguments, expected arguments "command" "path".  
```

**Comment by themsaid** [comment]
You can use the array format `my:command {files*}`

Check the docs under "Input Arrays", https://laravel.com/docs/5.4/artisan

**Comment by hpaknia** [comment]
Yet it's not possible to pass any type of parameters, like `--myparam` or `--param=yes`, any idea?
