### ISSUE TITLE
Queued Mailables don't work

### ISSUE THREAD

**Issue by arthurkirkosa** [laravel/framework#17964]
- Laravel Version: 5.4.12
- PHP Version: 7.0.15
- Database Driver & Version: mysql 5.7.17
- **Queue Driver: Database**

### Description:
This works on 5.4.11 (downgraded to test)

Trying to queue a mailable and the job fails

[Log Data](http://pastebin.com/d730e7Zz)
[Mailable](http://pastebin.com/iRvLJTun)

And I use it like `Mail::to($customer->email)->queue(new OrderCreated($order));`

If I do `Mail::to($customer->email)->send(new OrderCreated($order));` it work

Job Payload

`{"displayName":"App\\Mail\\OrderCreated","job":"Illuminate\\Queue\\CallQueuedHandler@call","maxTries":null,"timeout":null,"data":{"commandName":"Illuminate\\Mail\\SendQueuedMailable","command":"O:34:\"Illuminate\\Mail\\SendQueuedMailable\":1:{s:8:\"mailable\";O:21:\"App\\Mail\\OrderCreated\":17:{s:5:\"order\";O:45:\"Illuminate\\Contracts\\Database\\ModelIdentifier\":2:{s:5:\"class\";s:9:\"App\\Order\";s:2:\"id\";i:5;}s:4:\"from\";a:0:{}s:2:\"to\";a:1:{i:0;a:2:{s:4:\"name\";N;s:7:\"address\";s:21:\"arthur.kirkosa@me.com\";}}s:2:\"cc\";a:0:{}s:3:\"bcc\";a:0:{}s:7:\"replyTo\";a:0:{}s:7:\"subject\";N;s:11:\"\u0000*\u0000markdown\";N;s:4:\"view\";N;s:8:\"textView\";N;s:8:\"viewData\";a:0:{}s:11:\"attachments\";a:0:{}s:14:\"rawAttachments\";a:0:{}s:9:\"callbacks\";a:0:{}s:10:\"connection\";N;s:5:\"queue\";N;s:5:\"delay\";N;}}"}}`

**Comment by themsaid** [comment]
It appears to be working for me, please double check that you pass the view name correctly.

**Comment by arthurkirkosa** [comment]
It works with `->send()` and fails with `->queue()`

**Comment by themsaid** [comment]
I can't replicate it here so maybe you can try to dig into it since you can, check the value passed to `parseView` in Illuminate\Mail\Mailer.

**Comment by arthurkirkosa** [comment]
I've restarted my supervisor and it's working now.

Should I restart it each time I do a composer update?

**Comment by themsaid** [comment]
@arthurkirkosa not advertising here but use Forge if you can, it takes care of all this hassle :)

**Comment by arthurkirkosa** [comment]
👍
