### ISSUE TITLE
Change text for reset user password email

### ISSUE THREAD

**Issue by caiquecastro** [laravel/framework#17978]
- Laravel Version: 5.4.12

### Description:
It would be interesting if it's possible to change the text (translate) from the reset password e-mail. Instead of inheriting the sendPasswordResetNotification($token) from Illuminate\Auth\Passwords\CanResetPassword trait on User model.

**Comment by themsaid** [comment]
Can you please post this in the https://github.com/laravel/internals repo? It's where we keep suggestions and feature requests.

**Comment by devcircus** [comment]
Isn't the entire password reset process changing in 5.5?
