### ISSUE TITLE
[5.4] Unclear documentation about how to modify markdown mailable templates

### ISSUE THREAD

**Issue by pixelpeter** [laravel/framework#17970]
- Laravel Version: 5.4
- PHP Version: 7.0
- Database Driver & Version:

### Description:
I have the problem that my modifications from the published templates do not show up in my send emails using `markdown mailable`

### Steps To Reproduce:
1. I published the templates
```
php artisan vendor:publish --tag=laravel-mail
```

2. I modified `resources/views/vendor/mail/markdown/message.blade.html` 

3. The `mailable` uses markdown

```php
`App\Mail\OrdersShipped`

...

class OrderShipped extends Mailable
{
    ... 

    public function build()
    {
        return $this->markdown('emails.orders.shipped');
    }
}
```

4. My template `emails.ordered.shipped` looks like the one from the documentation
```php
@component('mail::message')
# Introduction

The body of your message

@component('mail::button', ['url' => ''])
Button Text
@endcomponent

Thanks,<br>
{{ config('app.name') }}
@endcomponent
```

This does not work.
If I want to have the modifications from `message.blade.html` my template `emails.ordered.shipped` needs to look like this:
```php
@component('vendor.mail.markdown.message')
...
``` 

I don't know if this is the wanted behaviour.
If so, than the documentation is not clear enough about this.

**Comment by themsaid** [comment]
When you extend `'vendor.mail.markdown.message'` you explicitly say that the rendered mail will use this view only, which is markdown, and you completely ignore the HTML email that'll be sent.

Markdown emails have an HTML version and a raw text version, you don't see the changes you made to the markdown files because you're looking at the HTML version of your email, so see those changes you have to update `/resources/views/vendor/mail/html/message.blade.php` not only the markdown one.

**Comment by jpgnz** [comment]
@themsaid while that explanation is correct I think the point that @pixelpeter is calling out is that's not documented well.

Even if you don't want to modify the html, you just want to modify the blade templates, it's not clear in the documentation that you need to change the @component.

**Comment by jonaseberledmind** [comment]
I think this should be reopened. The point is that the `resources/views/vendor/mail` - directory is completely ignored for `@component('mail::message') ` - so the only workaround  is like the OP described by setting `@component('')` (which, as you pointed out correctly, strips the automatic multipart html/markup-functionality).

I am quite new to Laravel and could not figure out a way to customize templates.

The [documentation](https://laravel.com/docs/5.4/mail) says 

> You are free to customize these components however you like.

**Comment by vcmattp** [comment]
I've spent a far amount of time looking at the same issue. Eventually I found out that there is some expected configuration that is missing. Try adding the following to your config/mail.php
` 'markdown' => [
		'theme' => 'default',

		'paths' => [
			resource_path('views/vendor/mail'),
		],
	],`

**Comment by mattsims** [comment]
Thank you @vcmattp, I was banging my head against the wall!

@themsaid – this should really be in the [docs](documentation) under the **Customizing The Components** section :)

**Comment by rusjoan** [comment]
@themsaid please explain why `mail preview` library exports `.eml` from markdown but `.html` from html template? Confusing...

**Comment by infronte** [comment]
@mattsims It is in Laravel Upgrade from 5.3 to 5.4 docs.

**Comment by brobey8** [comment]
I'm on Laravel 5.4 and I had to do the same thing...

Steps to reproduce:

`php artisan vendor:publish --tag=laravel-mail`

I've checked my mail config:

```
'markdown' => [
        'theme' => 'default',
        'paths' => [
            resource_path('views/vendor/mail'),
        ]
    ],
```

Wouldn't pull through the changes - had to do what the OP suggested and namespace to the view files like this

 `vendor.mail.markdown.message`

Would be nice if this worked as per the docs

**Comment by dustinalan** [comment]
@brobey8 did you upgrade from 5.x to 5.4? @mattsims is right.

I think this should be closed since the new code here has the correct config and it is in the upgrade docs: 

https://github.com/laravel/laravel/blob/master/config/mail.php#L115-L121

**Comment by pixelpeter** [comment]
I think my stupidity caused some confusion here.

By reading the documentation I assumed that when sending email I can choose to write my templates with normal HTML **or** Markdown syntax (and both version will generate HTML emails as output)

I suppose this was wrong!

When using Markdown emails you'll still need to modify the HTML templates for HTML email output because the Markdown templates only generate the plain text emails.

That confused me

If anybody wants to follow my twisted brain ;-) here are the steps to reproduce

1. Generate markdown email
```
php artisan make:mail OrderShipped --markdown=emails.orders.shipped
```

2. Export Maarkdown mail components to application
```
php artisan vendor:publish --tag=laravel-mail
```
 
3. Customizing the templates
The Markdown template
```
// MyApplication/resources/views/vendor/mail/markdown/message.blade.php
@component('mail::layout')
    {{-- Header --}}
    @slot('header')
        @component('mail::header', ['url' => config('app.url')])
            {{ config('app.name') }}
        @endcomponent
    @endslot

    {{-- Body --}}
    {{ $slot }}

    {{-- Subcopy --}}
    @isset($subcopy)
        @slot('subcopy')
            @component('mail::subcopy')
                {{ $subcopy }}
            @endcomponent
        @endslot
    @endisset

    {{-- Footer --}}
    @slot('footer')
        @component('mail::footer')
            © {{ date('Y') }} {{ config('app.name') }}. All rights reserved markdown.
        @endcomponent
    @endslot
@endcomponent

```
The HTML template
```
// MyApplication/resources/views/vendor/mail/html/message.blade.php
@component('mail::layout')
    {{-- Header --}}
    @slot('header')
        @component('mail::header', ['url' => config('app.url')])
            {{ config('app.name') }}
        @endcomponent
    @endslot

    {{-- Body --}}
    {{ $slot }}

    {{-- Subcopy --}}
    @isset($subcopy)
        @slot('subcopy')
            @component('mail::subcopy')
                {{ $subcopy }}
            @endcomponent
        @endslot
    @endisset

    {{-- Footer --}}
    @slot('footer')
        @component('mail::footer')
            &copy; {{ date('Y') }} {{ config('app.name') }}. All rights reserved HTML.
        @endcomponent
    @endslot
@endcomponent
```

4. Sending the Markdown email
```
// App/Mail/OrderShipped
...
    public function build()
    {
        return $this->from('john@example.org')
                    ->markdown('emails.orders.shipped');
    }
...
```

```
// App/Http/Controllers/Orders
...
    public function mail()
    {
        Mail::to('jane@example.org')->send(new OrderShipped([]));
    }
...
```

5. The result
I assumed HTML and plain text email would display 
```
© 2017 Laravel. All rights reserved markdown.
```

But only the plain text will display
```
© 2017 Laravel. All rights reserved markdown.
```
The rendered HTML email will show 
```
© 2017 Laravel. All rights reserved HTML.
```

**Comment by brobey8** [comment]
@dustinalan I'm not 100% sure of the laravel version I started with - I was on 5.4 but some weird stuff was missing like laravel-mix. I did have to run a composer update though. 

I've ran `php artisan config:cache` - still having the same issue though.. :(

**Comment by dustinalan** [comment]
Keep in mind if you change the config values then run the config:cache call, you're caching what is in the config files. Depending on your cache settings, you might be running into something there but sounds unlikely from your comment. Good luck... there's always a fresh install and migrate your code into a new repo.

**Comment by pixelpeter** [comment]
The short conclusion is:

For *HTML* emails update your `@component` reference in your email view from
```
@component('mail::message')
```

to

```
@component('vendor.mail.html.message')
```

For *Markdown* emails change it to
```
@component('vendor.mail.markdown.message')
```

I did a pull request for the documentation
https://github.com/laravel/docs/pull/3370

**Comment by aarondfrancis** [comment]
I'm still having the issue where Laravel doesn't pick up my newly published views after calling `vendor:publish` and `config:cache`. I'd really not like to change all my mail views to point to `vendor.mail.markdown.message`. Anyone have a definitive fix?

**Comment by kennith** [comment]
@aarondfrancis, you do not need to point to vendor.mail.markdown.message specifically. 

In mailable template, /vendor/mail/html/message is to view an email in HTML and /vendor/mail/markdown/message to to view an email in plain text. 

By default, Laravels send an email including [both HTML and plain text version](https://tools.ietf.org/html/rfc2046#section-5.1.4) in order to support email clients that prefers to view email in plain text or in HTML. Therefore, if you change the HTML layout in /vendor/mail/html/message.blade.php, you also need to update the plain text layout in /vendor/mail/markdown/message.blade.php to make your email consistent between HTML view and plain text view.

**Comment by pandy06269** [comment]
@kennith your explanation just helped me out massively - it suddenly all made sense.

For me, because the two templates it generates are called "markdown" and "html" - I assumed "markdown" is used when using `$this->markdown` in your mailable (i.e. the mail template is written in Markdown) and "html" is used when using `$this->view` (i.e. the mail template is written in HTML.)

Had they been called "html" and "plaintext" or something, it would have been much more obvious much quicker than it was!

**Comment by anaisabel19886** [comment]
Hi, i think it may be related to this. 

I am not able to render the css from my custom theme. The only way i've got this to work was to put my custom.css on the vendor folder (witch i know is wrong). Even if i edit the default.css on my resources/views folder it does not work. The only used css is on the vendor folder..

(I upgraded from 5.3 -> 5.4 -> 5.5 and added the  
   'markdown' => [
        'theme' => 'custom',
        'paths' => [
            resource_path('views/vendor/mail'),
        ],
    ],
and did the vendor publish
)

**Comment by kennith** [comment]
@anaisabel19886 You can [customize the component](https://laravel.com/docs/5.5/mail) (see the Customizing The Components section) with `php artisan vendor:publish --tag=laravel-mail`

**Comment by anaisabel19886** [comment]
@kennith the thing is I did that, and my installation only gets the views and css from the vendor files..

**Comment by cartbeforehorse** [comment]
@kennith Thanks buddy.  More attention needs to be brought to your answer.  And as is too often the case with Laravel, the documentation is very much lacking in this area.

**Comment by devcircus** [comment]
Docs are open source too. If there's something you feel needs improvement, submit a pr.

**Comment by b4dnewz** [comment]
this is the most unclear thing ever.. also you can not create Mailable classes that use the default template, or if is possible is not documented anywhere..
one simple thing as having all emails looking the same is taking me a tons of time, it is true that I get paid to work but I rather prefer to eat rocks instead of doing this, is a total waste of time.

How does the Notification class works? Which template does it use? How can other emails made with the Mailable class use the same template?

Why the $view property on the notification class is NULL when a notification is created?
Why this f**cking 5 line of codes would not work?

```php
$message = (new MailMessage())
  ->subject("Invitation to join team {$invite->team->name}.")
  ->line("You have been invited to join the team {$team->name}.");

// Send email to user
Mail::send($message->view, $message->data(), function ($m) use ($invite) {
  $m->to($invite->email);
});
```

How is possible to send a simple email using the "built-in" template?
Am I missing something or what? I've read the Mail and Notifications page on the reference 100times also looked at the source code without success.

**Comment by vcmattp** [comment]
Hi @b4dnewz

First of all the easiest way to use notification class is by adding the trait to your model.

This will then allow you to call `$invite->notify(new MyNotificationClass())`

The notification class knows nothing about views and is only used as a handler, which you can then send to your mailable (which can use views), sms, slack, etc. Using the notification class you can use the via method to set the method of communication. $notifiable will be an instance of your model.

Something like this should work:

MyNotificationClass:
```php
use Illuminate\Notifications\Notification;
use Illuminate\Notifications\Messages\MailMessage;

class MyNotificationClass extends Notification
{

    /**
     * Get the notification's delivery channels.
     *
     * @param  mixed  $notifiable
     * @return array
     */
    public function via($notifiable)
    {
        return ['mail'];
    }

    /**
     * Get the mail representation of the notification.
     *
     * @param  mixed  $notifiable
     * @return \Illuminate\Notifications\Messages\MailMessage
     */
    public function toMail($notifiable)
    {
    	return (new MyMailableClass($notifiable))
    		->subject("Invitation to join team {$notifiable->team->name}.")
    		->to([$notifiable->email]);
    }
}
```

MyMailableClass:
```php
use Illuminate\Mail\Mailable;

use App\Invite;

class MyMailableClass extends Mailable
{
	/**
     * Create a new message instance.
     *
     * @return void
     */
    public function __construct(Invite $invite)
    {
		$this->invite = $invite;
    }

    /**
     * Build the message.
     *
     * @return $this
     */
    public function build()
    {
    	$invite = $this->invite;
    	return $this->view('emails.invitation')->with(compact('invite'));
    	// or if you want to use markdown: return $this->markdown('emails.invitation')->with(compact('invite'));
    }
}

```

**Comment by b4dnewz** [comment]
thanks @vcmattp I resolved using another method but __your is cleaner__, since I'm extending a existing laravel plugin I want to write less code possible, what I came up with after looking to [MailChannel.php](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Notifications/Channels/MailChannel.php) source code was this:
```php

$this->renderer = Container::getInstance()->make(Markdown::class);

$message = (new MailMessage())
  ->subject("bla bla")
  ->line("bla bla bla")
  ->action('Accept', 'some/url');

$mailData = $message->data();
$mailView = [
  'html' => $this->renderer->render('notifications::email', $mailData),
  'text' => $this->renderer->renderText('notifications::email', $mailData)
];

Mail::send($mailView, $mailData, function ($m) use ($invite) {
  $m->to($invite->email);
});
```

but for me the problem still remains, or is not documented or is not possible to use the same template   `'notifications::email'` for mail notifications and Mailable classes, this cause confusion and penalize maintainability.

**Comment by vcmattp** [comment]
Your code appears to work for me. What is not working? Are you getting any errors or is it doing something different to what you expect?

**Comment by b4dnewz** [comment]
@vcmattp the code is working, I haven't said it wasn't, I said I will use your suggestion (Traits) to make it less intrusive, I was referring about the "problem" to nave to do custom things to archive a standard email template between notifications and mailables

**Comment by lewayotte** [comment]
Holy crap, thank you, OP! I was going insane!

**Comment by sahilofficial671** [comment]
> I've spent a far amount of time looking at the same issue. Eventually I found out that there is some expected configuration that I missed. Try adding the following to your config/mail.php
> 
> ```
> 'markdown' => [
>     'theme' => 'default',
>     'paths' => [
>         resource_path('views/vendor/mail'),
>     ]
> ],
> ```

Thank you so much dude.

**Comment by gilles6** [comment]
Is it possible to have package specific `views/vendor/mail` ? I mean specific to a custom package.
