### ISSUE TITLE
Fatal error: Call to undefined method stdClass::__set_state()

### ISSUE THREAD

**Issue by macdabby** [laravel/framework#17975]
- Laravel Version: 5.4
- PHP Version: HHVM 3.14.6
- Database Driver & Version:

### Description:
running `artisan config:cache` builds a file in `bootstrap/cache/config.php` using var_export(). If there are objects in the config tree, they will be written as `stdClass::__set_state([ ... ])`. This is fine for objects where `__set_state()` can be added, but it can't be added to`stdClass`. This causes the site to fail, but only when that is cached.

**Comment by themsaid** [comment]
Why would you add an object in config files?

**Comment by macdabby** [comment]
To meet a dependency requirement. That requirement is to provide data that will be encoded to json and transmitted to an API. that API requires that the value be presented as a dictionary, even if it's empty. PHP json_encode() automatically converts an empty array into a list instead of an empty dictionary, unless it is provided as a stdClass.

**Comment by themsaid** [comment]
I don't think using a config value for this is the best way, probably a helper method would be better.

**Comment by macdabby** [comment]
Well there is a non-breaking PR in, i'll just leave it at that. Worst case scenario it's adds a new feature 😄
