### ISSUE TITLE
Redirect::back()->withInput([]) redirect with all input

### ISSUE THREAD

**Issue by dantonel** [laravel/framework#17977]
- Laravel Version: 5.2.45
- PHP Version: PHP 5.5.9-1ubuntu4.20
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.5.53, for debian-linux-gnu (x86_64) 

### Description:
"return Redirect::back()->withInput([]);" causes the redirect to include all of the previous input, instead of none of it.

This means, that if one does Redirect::back()->withInput(Input::except('all', 'the', 'inputs', 'that', 'just', 'HAPPEN', 'to', 'be', 'in', 'this', 'request')); that rather than redirecting back with none of the input, you get ALL of it.

### Steps To Reproduce:
This can be shown really quick in route closures as follows:
Navigating to this /redirecttest route *should* cause an infinite redirect loop, since the first route redirects to the second, and the second should redirect back to the first WITHOUT old('foo') being set.  Instead it will display "whoops".
Route::get('/redirecttest', function () {
    if (old('foo')) {
        dd('whoops');
    }
    return Redirect::to('redirecttest2?foo=bad');
});

Route::get('/redirecttest2', function () {
    return Redirect::back()->withInput(Input::except('foo'));
});

However, this second example works as expect (by outputting "yay"):
Route::get('/redirecttest', function () {
    if (old('foo')) {
        dd('whoops');
    }
    if (old('bar')) {
        dd('yay');
    }
    return Redirect::to('redirecttest2?foo=bad&bar=good');
});

Route::get('/redirecttest2', function () {
    return Redirect::back()->withInput(Input::except('foo'));
});

By simplying adding an additional query parameter, we completely change the functionality of withInput(Input::Except()).

Note:  The same problem occurs when passing the parameters via form fields.

**Comment by themsaid** [comment]
Since 5.2 i not supported anymore we can't fix it there, so use `null` instead of an empty array. Will look into fixing it in 5.4 though.

**Comment by dantonel** [comment]
I can't directly use null since I'm using Input::except(...), but I will have to add a check for empty array.

**Comment by themsaid** [comment]
Yes check if it's an empty array and pass null in this case. I've submitted a PR to fix it on 5.4

**Comment by dantonel** [comment]
Awesome!  Thanks!
