### ISSUE TITLE
Blade rendering @parent with error

### ISSUE THREAD

**Issue by rpopuc** [laravel/framework#17987]
- Laravel Version: 5.4.12
- PHP Version:
- Blade @parent

### Description:
Blade rendering @parent with errors when has spaces in @section() declarations.

### Steps To Reproduce:
This code
```
@section( "parts" )
    @parent
    <p>
        A
    </p>
@endsection

@section( "parts" )
    @parent
    <p>
        B
    </p>
@endsection

@yield( "parts" )
```

Will produce something like

```
##parent-placeholder-c9beb22d58f6eec2a53f49b975c1d5806cd735e0##
A
```

However, this code (section names without spaces):

```
@section("parts")
    @parent
    <p>
        A
    </p>
@endsection

@section("parts")
    @parent
    <p>
        B
    </p>
@endsection

@yield( "parts" )
```

Will produce:

```
B

A
```

**Comment by themsaid** [comment]
Thank you, a PR with a fix was submitted: https://github.com/laravel/framework/pull/18012
