### ISSUE TITLE
[Suggestion] Password Reset notification method override

### ISSUE THREAD

**Issue by dherran** [laravel/framework#17988]
- Laravel Version: 5.4
- PHP Version: 7

Since Notifications were implemented, the Auth module comes equipped with an embedded Notification template for password resets. However, the logic is so deeply embedded in the PasswordBroker that changing the notification method is way more complicated than it should.

For instance, I wanted to not use notifications, but instead use another mailing class that we had already developed for this application. The easiest solution was to override the sendPasswordResetNotification() method in the User model, which something tells me shouldn't be there.

Shouldn't there be a way to override a method in the SendsPasswordResetEmails trait so you can implement your own notification/email system, instead of dealing with the User Model?

**Comment by themsaid** [comment]
I don't see it a bad practise to do the override in the User model.
