### ISSUE TITLE
[5.3] Performance Issues with Polymorphic Relations

### ISSUE THREAD

**Issue by moessimple** [laravel/framework#17981]
- Laravel Version: 5.3.30
- PHP Version: 7.1
- Database Driver & Version: MySql 5.7.17

### Description:
There seems to be significant differences in the query time between the query builder and an eloquent query.

### Steps To Reproduce:

I have set up a brand new project.
I have about 350,000 media records. 

One product has several media. My product model looks as follows.

```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    public function media()
    {
        return $this->morphMany(\App\Media::class, 'model');
    }
}
```

My media model as follows:

```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Media extends Model
{
    public function model()
    {
        return $this->morphTo();
    }
}
```

The following indices are set:

<img width="1146" alt="index" src="https://cloud.githubusercontent.com/assets/18553190/23084977/52fdc326-f565-11e6-9d1e-ab9aef98890e.png">

When I make the query with the query builder, there are significant differences in time too
the Eloquent query.

I run the identical queries.

```php
\DB::table('media')
    ->where('media.model_id', '173')
    ->whereNotNull('media.model_id')
    ->where('media.model_type', 'product')
    ->get();

App\Product::first()->media()->get();
```

Result

<img width="1785" alt="query" src="https://cloud.githubusercontent.com/assets/18553190/23084878/eb3a6e38-f564-11e6-9f60-8c9eae28ef01.png">

There are only 10 media entries

<img width="231" alt="result" src="https://cloud.githubusercontent.com/assets/18553190/23085039/9f237750-f565-11e6-9094-b8eef98dfff6.png">

**Comment by jmarcher** [comment]
I think that time represents the overhead needed to first get the product and then the media I don't remember how Debugbar measures time for a query.

**Comment by moessimple** [comment]
I know that Eloquent has an overhead, but such a big time difference?

I would not like to use the Query Builder or a Custom Query with Eloquent, if it's possible.

Blackfire gives me similar results, but I do not know how I have to read this.
https://blackfire.io/profiles/11b169e7-38dc-41b2-a2b0-1a5d57d4471b/graph

**Comment by jmarcher** [comment]
It looks like most of the time is consumed on I/O (see attached picture)

Can you please excecute the sql query isolated directly in MySQL?

![Time](http://i.imgur.com/xL54KD5.png)

**Comment by moessimple** [comment]
I noticed that as well. It is clear to me as I said it is an overhead, but why is it so slow. Thank you in advance.

# Direct MySql queries.

## SQL
<img width="400" alt="sql" src="https://cloud.githubusercontent.com/assets/18553190/23092864/768af812-f5d4-11e6-8020-dcb2c08ddb62.png">

## Explain
<img width="400" alt="explain" src="https://cloud.githubusercontent.com/assets/18553190/23092866/79ec9718-f5d4-11e6-8734-89015cd58c68.png">

**Comment by moessimple** [comment]
It is not a bug. The model_id is declared as varchar (255) because we also have mongo models.

<img width="399" alt="structure" src="https://cloud.githubusercontent.com/assets/18553190/23138604/a4af6c52-f7a8-11e6-9015-e6be54c2ddea.png">


```php
\DB::table('media')
    ->where('media.model_id', '173')
    ->where('media.model_type', 'product')
    ->get();

// SELECT * FROM media WHERE media.model_id = '173' AND model_type = 'product' // faster

App\Product::first()->media()->get();

// SELECT * FROM media WHERE media.model_id = 173 AND model_type = 'product' // slower
```
