### ISSUE TITLE
"Synchronous XMLHttpRequest on the main thread is deprecated..." message

### ISSUE THREAD

**Issue by evertramos** [laravel/framework#17984]
- Laravel Version: 5.4.12
- PHP Version: 7.0.9
- Database Driver & Version: MariaDB 10.1.16

### Description:
I am receiving the following message in the console:
```
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
rapport_nikko_send_focus_event @ VM769:61
rapport_nikko_on_focus @ VM769:72
```

and a couple of:

```
GET http://nikkomsgchannel/e?006b0055005c002600330042006e0051005a0052002b005600…5f0052002c005d00620055005c0037002b000c005f005b00590058002a005f002d005f005f 
rapport_nikko_send_focus_event @ VM769:62
rapport_nikko_on_focus @ VM769:72
```

### Steps To Reproduce:
I installed a fresh Laravel under windows using 'laravel new app-name', run the 'make:auth' and as soon as I hit the login input field it shows me the message.

**Comment by thecrypticace** [comment]
This is not a Laravel issue. Your computer has Trusteer Rapport installed which is causing the error messages to be thrown in the console.

**Comment by evertramos** [comment]
@thecrypticace well noticed, thank you very much and sorry to take your time @themsaid.

**Comment by thecrypticace** [comment]
👍
