### ISSUE TITLE
5.4.12 syntax error, unexpected '<', expecting end of file

### ISSUE THREAD

**Issue by qadirpervez** [laravel/framework#17989]
- Laravel Version: 5.4.12
- PHP Version: 7.0.13
- Database Driver & Version:

php artisan not running:

php artisan --versionPHP Parse error:  syntax error, unexpected '<', expecting end of file in pathToProject/ProjectName/vendor/composer/ClassLoader.php on line 28

**Comment by whoan** [comment]
It seems like a user error. Please try the following:

- `composer dump-autoload`
- Delete **vendor** folder and run `composer install`

**Comment by GrahamCampbell** [comment]
If you're still having trouble, please ask on the forums.

**Comment by qadirpervez** [comment]
Thanks.. this worked😊
