### ISSUE TITLE
Unable to create new records. 

### ISSUE THREAD

**Issue by ps92** [laravel/framework#17999]
- Laravel Version: 5.4.12
- PHP Version: 5.6.25
- Database Driver & Version: MySQL 5.6.31

### Description:
Currently, it is featured that you cannot create a new record unless you create a new instance of the model. So if you would like to create the class once and use it again and again to create new records, it is not possible, since it updates the old records based on the ID present in the model object itself. 

### Steps To Reproduce:
`<?php

/**
 * Created by PhpStorm.
 * User: Gary
 * Date: 19/02/17
 * Time: 9:11 AM
 */

namespace  App\Repositories\SHRD;

use App\Models\FormResponse;

class formResonsesData {
    private $modelPipeline = null;

    function __construct(FormResponse $formResponse) {
        $this -> modelPipeline = $formResponse;
    }

    function getCounts() {
        return $this -> modelPipeline -> all() -> count();
    }

    function insertResponseData ($responseArray) {
        $failedInsertions = false;
        foreach ($responseArray as $resonseSubmission) {
            $modelPipeline = $this -> modelPipeline;
            $modelPipeline -> email_address =  $resonseSubmission -> hidden -> email;
            foreach ($resonseSubmission -> answers as $item => $value) {
                $modelPipeline [(string)$item] = $value;
            }
            $failedInsertions = $failedInsertions && $modelPipeline -> save();
        }
        return !$failedInsertions;
    }
}`

**Comment by ps92** [comment]
`$failedInsertions = $failedInsertions && $modelPipeline -> save(['create' => true]);`

**Comment by ps92** [comment]
@taylorotwell The closed issue #18000 has it's description here. Could you please let me know if I need to describe it more?

**Comment by fernandobandeira** [comment]
Well this is the intended behavior

I'd suggest that you change your code to something like:

```php
        $modelPipeline = $this -> modelPipeline;
        $data = $resonseSubmission -> answers;
        $data['email_address'] = $resonseSubmission -> hidden -> email;
        $failedInsertions = $failedInsertions && $modelPipeline :: create($data);
```

Remember to add this to your FormResponse model:

```php
protected $guarded = ['id'];
```

Id is your primary key, everything else will be mass assigned, this should do what you want and you won't need the foreach anymore..

**Comment by ps92** [comment]
Oh, I didn't know that.Thanks!
