### ISSUE TITLE
How to Conditionally validate an array form request

### ISSUE THREAD

**Issue by gduffy100** [laravel/framework#17993]
- Laravel Version: 5.4.*
- PHP Version:
- Database Driver & Version:

### Description:
I have a form request that includes an array. I want a field within the array to be required if another field within the array has a certain value. 

so I need to use the sometimes rule, but in the callback, how do I refer to the conditional field in the current loop of the array:

### Steps To Reproduce:
within my form request:

$rules = [
....
lines.*.type = 'required|string|exists...',
lines.*.item_number = 'required_if:lines.*.type = 'STOCK',
....]
protected function getValidatorInstance(){
   
 $validator = parent::getValidatorInstance();

	$validator->sometimes('lines.*.item_number',|integer|exists..., function($input)
    {
		{
			if($input->lines.*.invoice_type === 'STOCK';    // this is the bit that doesn't work
		}
    });

**Comment by gduffy100** [comment]
**UPDATE**

I have overwritten the base validator functions to allow nulls and empty strings e.g. 

	 protected function validateInteger($attribute, $value)
    {
        return (filter_var($value, FILTER_VALIDATE_INT) !== false || empty($value));
    }

As long as I use this with required or required_if, I can't have a null value or empty string when I shouldn't have one

**Comment by ankurk91** [comment]
Have you tried this in your form request class - 

```php

/**
 * Configure the validator instance.
 *
 * @param  \Illuminate\Validation\Validator  $validator
 * @return void
 */
public function withValidator( $validator )
{
$validator ->after ( function ( $validator ) {
if ( $this ->somethingElseIsInvalid ()) {
$validator ->errors () ->add ( 'field' , 'Something is wrong with this field!' );
}
});
}
```
Copied from
https://laravel.com/docs/5.4/validation

**Comment by deleugpn** [comment]
Two step validation may also work.

https://medium.com/@deleugpn/chain-validation-with-form-requests-laravel-c0bc8fb1b30e

**Comment by tylik1** [comment]
It would really be great to be able conditionally validate arrays. Currently it is not possible, as callback is fired only once.
