### ISSUE TITLE
Localization Translation Strings - breaks if comma added in last pair

### ISSUE THREAD

**Issue by qerim** [laravel/framework#17995]
- Laravel Version:  5.4.12
- PHP Version: 7.1.0
- Database Driver & Version: MySQL 5.7.16

### Description:
Adding a **comma** for the last key/value pair strings breaks all translation.

I have 2 languages: _en.json_ and _sq.json_ in the _resources/lang_ directory.

In my view:
`<h1>{{ __("Welcome") }}</h1>`

### Steps To Reproduce:

_en.json_ example

Doesn't work:

```
{
  "Hello": "Hello there",
  "Welcome": "Welcome to our site",
}
```

By '_Does't work_', it just returns the keys "Welcome" and "Hello".

Works:

```
{
  "Hello": "Hello there",
  "Welcome": "Welcome to our site"
}
```

**Comment by brunogaspar** [comment]
It might be because that's not considered a valid JSON format.

**Comment by qerim** [comment]
@brunogaspar you're right. I got carried away when adding '_providers_' in _config/app.php_, always ending with a comma has become a habit, which I carried on to this.
