### ISSUE TITLE
[Testing] Run migration until specified datetime

### ISSUE THREAD

**Issue by rentalhost** [laravel/framework#17996]
- Laravel Version: 5.4
- PHP Version: 7.1 (_irrelevant_)
- Database Driver & Version: MariaDB 10.1 (_irrelevant_)

### Description:

I think that should have a method for you controls how much you wants to run migrations when you are making tests. I think that the best method is you controls it by run `Carbon::setTest($datetime)`, then only migrations until this date will be run,

### Why it is important to general public:

Currently you can trait a testing class with `DatabaseMigrations`, and it will run `migrate` command, then will run `migrate:rollback` automatically, but in some cases you need to limit how much you like to migrate.

For instance: imagine that on version `1.0` you have a table called `users` that have a column called `fullname`, that stores obviously the user fullname. But on `1.1` you will need to split it in `firstname` and `lastname`, and with that you need run a update process to split all current database to new structure. This is currently possible by doing that on migration process, but you have no way to check if it is working like expected.

Then I thinking in something like that:

*My migrations:*

> 2017_02_18_100000_v010000 (fullname definition)
> 2017_03_36_100000_v010100 (fullname splitted into firstname and lastname)

*How test should do in cases like that*:

```php
class UserTest extends TestCase {
    public function testSplittingProcess () {
         // In this point, we are simulation the original structure.
         Carbon::setTest('2017-02-18 10:00:00');
         $this->artisan('migrate');

         $user = new User;
         $user->fullname = 'John Doe';
         $user->save();
         static::assertNull($user->firstname); // Currently not supported.
         static::assertNull($user->lastname); // Currently not supported.
         static::assertSame('John Doe', $user->fullname);

         // In this point we remove the fake date to run all migrations until now.
         Carbon::setTest();
         $this->artisan('migrate');

         // Then it should check if user update run without problems.
         $user = User::find($user->id);
         static::assertSame('John', $user->firstname);
         static::assertSame('Doe', $user->lastname);
         static::assertSame('John Doe', $user->fullname); // Mutator.
    }
}
```

**Comment by Kyslik** [comment]
This should be in [internals](https://github.com/laravel/internals).

**Comment by rentalhost** [comment]
@Kyslik Thanks a lot!
