### ISSUE TITLE
Running PHPUnit Tests Service Provider Persists Between Http Requests

### ISSUE THREAD

**Issue by mtpultz** [laravel/framework#17997]
- Laravel Version: 5.3.*
- PHP Version: 7
- Database Driver & Version: Using Homestead 3.1.0

### Description:
Running a test that loops over a collection that on each iteration creates a new user, logs the user in, performs an authenticated action, logs the user out appears to preserve a previously instantiated service provider.  Through logs and stubs the service provider that we created only gets instantiated on the first request made to the server, and all subsequent requests reuse it and its stored content.  I tested several variants of the statements to simply, and added 3 of them below.

We're using JWT tokens (JWTAuth) for authentication, and I've verified that logout is invoked, is blacklisting tokens, and does not allow access to endpoints if blacklisted.  That the next user created in the loop is authenticated correctly and has a different token.  They only difference is the service provider on subsequent authentications already exists and has stored information on the first user preventing the test from passing though it passes in the production application.

**Test Using Loop - Original Test**

```php
public function applicant_can_prequalify_if_age_of_majority_for_province_or_older()
{
    // Arrange
    $this->runPrequalifySeeders();

    $provinces = Province::select('id', 'name', 'majority_age')->get();
    $provinces->each(function ($province) {

        // Act
        $provinceName = str_replace(' ', '', strtolower($province->name));
        $username = "{$provinceName}@example.com";

        $applicant = $this->createApplicant($username);
        $this->login($applicant->username);

        Log::info($applicant->username); // correct username: yes
        Log::info($this->token); // different token each time: yes

        // Applicants can only have one open application at a time hence the
        // new user for each iteration per province, which fails on the second
        // iteration as service provider is persisted and provides the first user
        $application = $this->createNewApplication()->decodeResponseJson();

        // Removed for brevity...

        $this->logout();
    });
}
```

**Test Not Using Loop**

```php
public function applicant_can_prequalify_if_age_of_majority_for_province_or_older()
{
    // Arrange
    $this->runPrequalifySeeders();

    $provinces = Province::select('id', 'name', 'majority_age')->get();
    $provinces->each(function ($province) {

    // Act 1
    $province = $provinces->shift();
    $provinceName = str_replace(' ', '', strtolower($province->name));
    $username = "{$provinceName}@example.com";

    $this->createApplicant($username)->login($username);
    $application = $this->createNewApplication()->decodeJson();

    // Removed for brevity

    $this->logout();

    // Act 2
    $province = $provinces->shift();
    $provinceName = str_replace(' ', '', strtolower($province->name));
    $username = "{$provinceName}@example.com";

    $this->createApplicant($username)->login($username);

    // Still fails based on the service provider being persisted between requests and
    // providing the first user 
    $application = $this->createNewApplication()->decodeJson();

    // Removed for brevity

    $this->logout();
}
```

**Test Verifying User Is Logged Out Properly**

```php
public function applicant_can_prequalify_if_age_of_majority_for_province_or_older()
{
    // Arrange
    $this->runPrequalifySeeders();

    $provinces = Province::select('id', 'name', 'majority_age')->get();
    $provinces->each(function ($province) {

    // Act
    $province = $provinces->shift();
    $provinceName = str_replace(' ', '', strtolower($province->name));
    $username = "{$provinceName}@example.com";

    $this->createApplicant($username)->login($username);
    $application = $this->createNewApplication()->decodeJson();

    $this->logout();

    // 401 server response since token was successfully blacklisted: yes
    $application = $this->createNewApplication()->decodeJson();
}
```

**Comment by CurosMJ** [comment]
Application instance is reused for all the requests in unit tests. You need to use $this->refreshApplication(); between requests to achieve proper functionality.

**Comment by CurosMJ** [comment]
https://github.com/laravel/framework/issues/14402

**Comment by mtpultz** [comment]
@CurosMJ I actually tried that, but it blows away everything.  So the next error if I take the seed and place it in `setUp` and add `$this->refreshApplication()` at the end of the loop is the users table doesn't exist.

**Comment by mtpultz** [comment]
According to that post this is a "subtlety of the framework", but now I'm confused on how to test a collection of items (in this case provinces) that each need to be tested that they respect the varying age of majority without adding 13 separate tests.

**Comment by CurosMJ** [comment]
@mtpultz Refreshing the Laravel application instance during a test should have an impact on what is stored in database. You dont need to modify `setUp`, just call `$this->refreshApplication()` whenever you want to login a user.

**Comment by mtpultz** [comment]
@CurosMJ If I use `$this->refreshApplication()` I get this error:

```
Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1 no such table: users (SQL: insert into "users" ("username", "password", "status", "type", "modified", "created") values (alberta@example.com, $2y$10$Roh7FjnREjgS2qKTKa4zDed5ii6839DuH8qpmgzBV8cuSWtHhGtqO, 1, applicant, 2017-02-19 03:21:18, 2017-02-19 03:21:18))
```

**Comment by GrahamCampbell** [comment]
This is because you're using an in-memory database, that gets deleted when you refresh the application.

**Comment by mtpultz** [comment]
Thanks @GrahamCampbell , that makes sense.  To solve this I just run each loop and now delete the application that was created after each assertion.

**Comment by tylerssn** [comment]
Is there a workaround to this for my use case?

In my service provider I have a method called `isMainApp()` that tests the host found in the `APP_URL` matches the host found in `url()->current()`. This behaves appropriately in the browser but, because of the issue reported here, does not work in tests because the service provider is not refreshed on `$this->get(...)` requests.
