### ISSUE TITLE
[5.4] How to add package language file without group?

### ISSUE THREAD

**Issue by marktopper** [laravel/framework#18002]
- Laravel Version: 5.4.12
- PHP Version: 7.1.1

### Description:
How can I add a language file that includes a key like this `trans('package::key')`.
Currently it loads the file a structure like this:
```
lang/en/strings.php
```
with the content
```
<?php return ['key' => 'test'];
```
Makes it be `trans('package::strings.key')` and not `trans('package::key')`.

How can I use it like `trans('package::key')`?

**Comment by GrahamCampbell** [comment]
Please direct questions to the forums, we only process framework bug reports here I'm afraid. :)

**Comment by marktopper** [comment]
It seems impossible to do at the current state.
So how about adding this feature?
