### ISSUE TITLE
Is symfony/process actually a production dependency? Can it be removed or moved to require-dev?

### ISSUE THREAD

**Issue by phpguru** [laravel/framework#18015]
- Laravel Version: 5.3.#
- PHP Version: 7.0.15
- Database Driver & Version: MySQL 5.7

### Description:
[symfony/http-kernel](https://github.com/symfony/http-kernel/blob/master/composer.json#L35) has `symfony/process` listed as a `require-dev`, but laravel/framework lists it [in composer.json](https://github.com/laravel/framework/blob/5.4/composer.json#L35) under `require`. It is therefore getting built with our production code release process, with `composer install --production`. 

Can `symfony/process` be moved to `require-dev` or removed as a dependency altogether? It seems that it would still be included in dev, since `laravel/framework` lists "symfony/http-kernel" as a `require` dependency, and `symfony/http-kernel` lists `symfony/process` as a `require-dev` dependency.

The reason this came up is `symfony/process` was identified by our security scan as having 4 critical security flaws, and it's unclear if Laravel actually uses it, or how to go about getting it fixed, if these are in fact flaws and it is actually required in production by Laravel.

### Steps To Reproduce:
Build your dependencies with `composer install --production` and see the `symfony/process` library is included.

**Comment by devcircus** [comment]
looks to have an important role in 
https://github.com/laravel/framework/blob/5.4/src/Illuminate/Queue/Listener.php
and also used in
https://github.com/laravel/framework/blob/5.4/src/Illuminate/Console/Application.php
https://github.com/laravel/framework/blob/5.4/src/Illuminate/Console/Scheduling/CommandBuilder.php
https://github.com/laravel/framework/blob/5.4/src/Illuminate/Console/Scheduling/Event.php
https://github.com/laravel/framework/blob/5.4/src/Illuminate/Console/Scheduling/Schedule.php
https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/Console/ServeCommand.php
https://github.com/laravel/framework/blob/5.4/src/Illuminate/Support/Composer.php

**Comment by phpguru** [comment]
I was afraid of that. Thanks.

**Comment by lioannou** [comment]
@phpguru - saying `symfony/process` was identified by our security scan as having 4 critical security flaws" implies that both Symfony, and Laravel would be affected by these "flaws".

I checked the known security advisories for Symfony here - and there are none known for `symfony/process` that I could see - https://github.com/FriendsOfPHP/security-advisories/tree/master/symfony

So have you found some new issues?

"...or how to go about getting it fixed"
You could post an issue at https://github.com/symfony/symfony. Or email Symfony.

**Comment by phpguru** [comment]
@lioannou - yep, I emailed security at symfony dot com - their docs clearly state to not post them online for obvious reasons.
