### ISSUE TITLE
Documentation: Fail to illustrate multiple middlewares in routes file.

### ISSUE THREAD

**Issue by edgreenberg** [laravel/framework#18018]
- Laravel Version: 5.3, 5.4
- PHP Version: n/a
- Database Driver & Version: n/a

### Description:

In documentation page ```https://laravel.com/docs/5.3/routing#route-group-middleware```  it is stated:

> To assign middleware to all routes within a group, you may use the middleware key in the group attribute array. Middleware are executed in the order they are listed in the array:

The page then presents this code:
```
Route::group(['middleware' => 'auth'], function () {
    Route::get('/', function ()    {
        // Uses Auth Middleware
    });

    Route::get('user/profile', function () {
        // Uses Auth Middleware
    });
});
```
It would be nice, given the documentation statement about order of execution, if the example presented two or more middlewares being assigned to the group.   For instance, auth and web.  Does one assign these a quoted string with commas? As an array being assigned to the middleware key? Or what. 

Many thanks.

**Comment by arcanedev-maroc** [comment]
Hi @edgreenberg, 

Did you checked the Middleware section : https://laravel.com/docs/5.3/middleware ?

**Comment by devcircus** [comment]
The '[Middleware Groups](https://laravel.com/docs/5.3/middleware#middleware-groups)' section shows the array syntax used for multiple middleware.
