### ISSUE TITLE
Blade @parent not replaced in inline @section definition

### ISSUE THREAD

**Issue by vitnasinec** [laravel/framework#18010]
- Laravel Version: 5.4.12
- PHP Version: 5.6.10
- Blade **@parent**

### Description:
Blade **@parent** not replaced in inline **@section** definition

### Steps To Reproduce:
this code
```
@section('parts')
    @parent
    Baz
@endsection

@section('parts', '@parent Bar')

@section('parts')
    @parent
    Foo
@endsection

@yield('parts')
```
will produce
```
@parent Bar Baz
```
however this
```
@section('parts')
    @parent
    Baz
@endsection

@section('parts')
    @parent
    Bar
@endsection

@section('parts')
    @parent
    Foo
@endsection

@yield('parts')
```
will produce
```
Foo Bar Baz
```

**Comment by ntzm** [comment]
I believe this is intentional to stop users being able to input `@parent` and mess up the templates. Was changed around here: #16033 but I think a more robust solution has been put in place recently to do with randomly generated strings

**Comment by themsaid** [comment]
Yes blade directives aren't compiled in inline section content.
