### ISSUE TITLE
PostgreSQL Grammar: compileColumnExists does not check the schema

### ISSUE THREAD

**Issue by phackwer** [laravel/framework#18025]
- Laravel Version: all
- PHP Version: any
- Database Driver & Version: PostgreSQL any version

### Description:

The current compileColumnExists does not check the schema name for the table, giving a wrong result in cases you have two tables with the same name on different schemas and with different columns.

### Steps To Reproduce:

Create tables with same name and different columns, the first one found on the information_schema with that column will always get you a true result, even when it's not.

**Comment by themsaid** [comment]
@phackwer you submitted a PR earlier to fix this, am I wrong?

**Comment by fernandobandeira** [comment]
I think the PR was to #18026, this seems a different issue.
