### ISSUE TITLE
Attach xls file

### ISSUE THREAD

**Issue by luisfmelo** [laravel/framework#18028]
- Laravel Version: 504
- PHP Version: 7.0
- Database Driver & Version: -

### Description:

When I try to send an email with dropbox file attached, the file received is 

### Steps To Reproduce:
class extends from Mailable
```
$this->subject('Order Update')
            ->to($this->mail_to)
            ->markdown('emails.email_to_customer')
            ->attach('https://www.dropbox.com/s/ywp3oplt0o7qzzq/excel-examples.xls')
            ->with('content', $this->content);
```

**Comment by lioannou** [comment]
The `attach()` url you are using is wrong. I just tried it - and that takes you to the dropbox excel "page" - not the actual file.

It would need to be something like this:
https://dl.dropboxusercontent.com/content_link/FU6rvJE5GwuO2mYY7QeeegED76qwohPX5LO5BumIS5eSW9fmhcHzmHKzXUWoLSy6/file?dl=1

Either way - it is not a bug in Laravel - please ask for further help on the forums.

**Comment by themsaid** [comment]
Thanks @lioannou
