### ISSUE TITLE
$request->hasFile() not working

### ISSUE THREAD

**Issue by leewillis77** [laravel/framework#18030]
- Laravel Version: 5.4.12
- PHP Version: 7.1.1
- Database Driver & Version: n/a

### Description:
`$request->hasFile()` returns `false` even when the file has been provided.

### Steps To Reproduce:
Add the following routes to your `routes/web.php` file:

```php
Route::get('/test', function() {
        $output = '<html><body><form method="POST" action="/test" accept-charset="UTF-8" enctype="multipart/form-data">';
        $output .= csrf_field();
        $output .= '<input name="image" type="file" id="image">';
        $output .= '<input type="submit" value="Test">';
        $output .= '</form></body></html>';
        return $output;
});

Route::post('/test', function(Illuminate\Http\Request $request) {
        dump('hasFile(image)');
        dump($request->hasFile('image'));
        dump('request->image');
        dump($request->image);
        dump('request->file(image)');
        dump($request->file('image'));
        return '';
});
```

Visit the `/test` route, upload a file, and submit the form. 

### Expected output:

```
"hasFile(image)"
true
"request->image"
UploadedFile {
...
}
"request->file(image)"
UploadedFile {
...
}
```

### Actual output

```
"hasFile(image)"
false
"request->image"
UploadedFile {
...
}
"request->file(image)"
UploadedFile {
...
}
```

Note that the call to `hasFile()` return `false`, even though `request->image` and `request->file('image')` both correctly return the UploadedFile object.

**Comment by leewillis77** [comment]
Closing for now. Looks like this is a local config issue. The UploadedFile objects are actually empty.

**Comment by david-j-davis** [comment]
Hey @leewillis77, what was the local config change? I have this same problem right now. Dumping out the request supposedly containing the FormData is empty. Thanks.

**Comment by leewillis77** [comment]
I can't recall exactly unfortunately :(   However there's a strong chance it may have been related to PHPs post-size (post_max_size) or upload size settings (upload_max_filesize). Hope that helps!

**Comment by david-j-davis** [comment]
That would explain alot actually. Ok thanks Lee.

**Comment by nikulnayi** [comment]
Use filled() function if you are using laravel 5.8+

**Comment by Fiatinnovations** [comment]
Worked for 5.8. Thanks. @nikulnayi
