### ISSUE TITLE
Queue::after method is not being called

### ISSUE THREAD

**Issue by garima-goyal** [laravel/framework#18033]
- Laravel Version: 5.2
- PHP Version:
- Database Driver & Version:

### Description:  Queue is processing successfully but the Queue:after method is not being called.
I need to send mail to the user for informing about the process completion and need to update the status. 

I am testing with log Info but not working 
My code is 
 Queue::after(function (JobProcessed $event) {
             Log::info("JobProcessed");
            $data = $event->data['data']['command'];
             Log::info($data);
  });

Please help

**Comment by themsaid** [comment]
Please upgrade to 5.4 as 5.2 is not supported anymore :)
