### ISSUE TITLE
Merge .env.dusk instead of replace when running Dusk tests

### ISSUE THREAD

**Issue by sahibalejandro** [laravel/framework#18048]
- Laravel Version: 5.4.*

### Description:
I know this is a Dusk related issue, but I think the changes need to be made into the Laravel Framework and the Dusk package as well.

It would be nice to detect when Dusk tests are running and **merge** the variables in `.env.dusk` and `.env`.

This is helpfull when you only need to change a few variables when running Dusk tests.

Let's say I have this `.env` file:

```
APP_ENV=local
DB_CONNECTION=mysql
DB_DATABASE=my_awesome_app
```

When running Dusks tests I want to **only** use a diferente database, would be nice to define **only** that variable in my `.env.dusk.local` file, like this:

```
DB_DATABASE=my_awesome_app_testing
```

And the resulting environment variables when running Dusk tests in the browser should be:

```
APP_ENV=local
DB_CONNECTION=mysql
DB_DATABASE=my_awesome_app_testing
```

Is that make sense?

At this time, you need to make a entire copy of your `.env` file to `.env.dusk` and then change only a few values, but leaving all the others same as the original `.env` file.

The related Dusk issue is here: https://github.com/laravel/dusk/issues/96

**Comment by themsaid** [comment]
Thanks but for suggestions and feature requests please use the https://github.com/laravel/internals repo.
