### ISSUE TITLE
Predifined $message variable in blade

### ISSUE THREAD

**Issue by JCarlosR** [laravel/framework#18044]
- Laravel Version: 5.2.45
- PHP Version: 7.0.10
- Database Driver: MySQL

### Description:

It is not possible to use a variable named $message in a view sent via mail, right?
I was using the next lines in my blade:
```
<li>
    <b>Mensaje:</b> {{ $message }}
</li>
```

In my contact form I had a textarea with ```name="message"``` and I was using ```$request->all()``` in my controller.
After change ```message``` for ```content```, it works perfectly.

It is just a suggestion. There is a way to exclude the predifined ```$message``` variable from the blade that will be used? Or probably change the name.

I found the next with a quick search, but as I remember I had this problem some times before.
![image](https://cloud.githubusercontent.com/assets/3101238/23169967/aeff92fe-f81b-11e6-8c68-7fe643ddab3d.png)

Thank you.

**Comment by themsaid** [comment]
yes `$message` is a reserved variable inside email views. You need to give your variables other names.

It's mentioned in the docs:

> Note: A $message variable is always passed to e-mail views, and allows the inline embedding of attachments. So, you should avoid passing a message variable in your view payload.

https://laravel.com/docs/5.2/mail
