### ISSUE TITLE
[5.4] HTTP Test download and stream responses

### ISSUE THREAD

**Issue by nisaac2fly** [laravel/framework#18049]
- Laravel Version: 5.4.12
- PHP Version: 7.0

### Description:

Is testing a download or stream possible with HTTP Tests or is this type of test only possible with Browser Tests (Laravel Dusk)? 

### Steps To Reproduce:

Route:

```php
Route::get('download', function () {
    return response()->download(resource_path('/assets/js/app.js'));
});
```

Feature test:

```php
/** @test */
public function it_can_download_js_file()
{
    $this->get('download');
}
```

Test output:

```
UnexpectedValueException: The Response content must be a string or object implementing __toString(), "boolean" given.
```

**Comment by ohnotnow** [comment]
Just to say I've hit this today too.  There doesn't seem to be [anything in Dusk](https://laravel.com/docs/5.4/dusk#available-assertions) that would replicate what we used to be able to do either (e.g., test the response filename/size were correct etc).

**Comment by martonbaranyai** [comment]
I think I found a workaround based on @adamwathan's testing course, using a Fake:

https://gist.github.com/martonbaranyai/74210e8377f5f13e475d2649d099061a

Maybe not the nicest ever, but could be a starting point

(“File” is a model, we store files in the db not on disk, the rest should be self-explaining I hope)
