### ISSUE TITLE
[5.4] Query Builder proposal: allow insert and insertGetId to accept ArrayObject / ArrayAccess

### ISSUE THREAD

**Issue by franksl** [laravel/framework#18057]
- PHP Version: 7.0

Hello,
I often use ArrayObject objects in my code. When I want to pass a structure to the insert methods of the Query Builder I receive the error: "TypeError: Argument 1 passed to Illuminate\Database\Query\Builder::insertGetId() must be of the type array, object given".

I think it's safe to also allow at least ArrayAccess implementations to call these methods.
Thanks,
Frank

**Comment by themsaid** [comment]
Thanks for your suggestion but please use  the https://github.com/laravel/internals repo, it's where we keep suggestions and requests to look into them later.
