### ISSUE TITLE
[5.3] Uncaught ReflectionException: Class view does not exist

### ISSUE THREAD

**Issue by xxlv** [laravel/framework#18053]
- Laravel Version: 5.3
- PHP Version: 7.0
- Database Driver & Version: Mysql 

### Description:
When run the project,Laravel give me this exception  "Class view does not exist" .
But why ?  

### Steps To Reproduce:
```
Stack trace:
#0 /var/lib/php/composer_package/vendor/laravel/framework/src/Illuminate/Container/Container.php(749): ReflectionClass->__construct('view')
#1 /var/lib/php/composer_package/vendor/laravel/framework/src/Illuminate/Container/Container.php(644): Illuminate\Container\Container->build('view', Array)
#2 /var/lib/php/composer_package/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(709): Illuminate\Container\Container->make('view', Array)
#3 /var/lib/php/composer_package/vendor/laravel/framework/src/Illuminate/Container/Container.php(1203): Illuminate\Foundation\Application->make('view')
#4 /var/lib/php/composer_package/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php(144): Illuminate\Container\Container->offsetGet('Illuminate\\Cont...')
#5 /var/lib/php/composer_package/vendor/laravel/framework/src/Illumin in /var/lib/php/composer_package/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 749
[22-Feb-2017 01:52:33 UTC] PHP Fatal error:  Uncaught ReflectionException: Class view does not exist in /var/lib/php/composer_package/vendor/laravel/framework/src/Illuminate/Conta

```

**Comment by xxlv** [comment]
I fixed this by modifying project dir's  permissions

**Comment by ChristianTheMinery** [comment]
By modifying them to..?

**Comment by Kyslik** [comment]
@ChristianTheMinery  https://stackoverflow.com/a/37266353/1564365

**Comment by epileftro85** [comment]
in my case was a comma missing in the config/app providers array, or like i read in another post an space in the .env file

**Comment by shrikanth003** [comment]
Whenever i receive these kind of errors, i try to run php artisan in the command line as it shows where the error lies. Mostly due to errors in env file

**Comment by krisan012** [comment]
@epileftro85 thank you. it's work now. i just found a word on my .env file.

**Comment by simonhamp** [comment]
In case anyone else exhausts the other options above, for me it was because I was throwing an exception in a package-overriding config file.

Lesson: don't throw exceptions from your config files.

**Comment by mfissehaye** [comment]
In my case I had to run `composer update` and then `composer dump-autoload`.
There was change in my dependencies.

**Comment by Tim-TOTO** [comment]
in my case it was the .env file went awol throwing this error

**Comment by chrissound** [comment]
I fixed this by formatting my pc and replacing the AC system in the office.

**Comment by brian-lamb-software-engineer** [comment]
Check SELinux.  that was the problem for me. 
```semanage fcontext -a -t httpd_sys_rw_content_t "/var/www/site/laravel/storage(/.*)?"
semanage fcontext -a -t httpd_sys_rw_content_t "/var/www/site/laravel/bootstrap/cache(/.*)?"
semanage fcontext -a -t httpd_sys_rw_content_t "/var/www/site/laravel/config(/.*)?"
restorecon -Rv /var/www/tsite/```
Particularly the config one..

**Comment by AlOdes** [comment]
Create .env file with your params.

**Comment by xpfans** [comment]
in my case:i had deleted the  folder of vendor,reinstall all dependencies,the problem solved.

**Comment by imnd** [comment]
check php version. it must be >= 7.2.

**Comment by musamamasood** [comment]
Solved this issue after removing space in the **.env file** (_view .env in sublime because vi editor doesn't show space at end of the .env file._) and run below commands. 

### Commands:
`php artisan config:clear`
`php artisan cache:clear`
`composer dump-autoload`
`php artisan clear-compiled`

**Comment by dylanglockler** [comment]
Had the same issue, after running composer dump-autoload, I discovered it was because I had forgotten to install a package (Laravel Excel) I had setup on my dev server that wasn't yet loaded on the production server.

**Comment by rajucs** [comment]
Same Problem like @dylanglockler  fix it

**Comment by driesvints** [comment]
I'm locking this issue because it either has gone off-topic, become a dumping ground for things which shouldn't be in an issue tracker or is just too old.
