### ISSUE TITLE
Resetting namespace in nested group namespace?

### ISSUE THREAD

**Issue by MrMashy** [laravel/framework#18054]
- Laravel Version: 5.4
- PHP Version: 5.6
- Database Driver & Version: mySQL

### Description: 

I'm creating an API and the API is in the `http/controllers/api` namespace. however I need to use the Passport::routes(); function. When I do route list, it comes up with:
```
[ReflectionException]
Class App\Http\Controllers\Laravel\Passport\Http\Controllers\AuthorizationController does not exist
```

**Comment by MrMashy** [comment]
How can I stop the namespace from repeating?

**Comment by MrMashy** [comment]
And I don't want to enter `Passport::routes()` in the AuthServiceProvider.

**Comment by themsaid** [comment]
Please ask on the forums.
