### ISSUE TITLE
[5.3] View sections blank in extending templates

### ISSUE THREAD

**Issue by martinbean** [laravel/framework#18064]
- Laravel Version: 5.3.30
- PHP Version: 7.1.0
- Database Driver & Version: MySQL (5.7.16)

### Description:

Hard to describe, but sections have stopped working in templates extending more than one level deep in the hierarchy tree.

### Steps To Reproduce:

I have the following template hierarchy:

- **layouts/master.blade.php**
- **layouts/app.blade.php** extends **layouts/master.blade.php**
- **layouts/channel.blade.php** extends **layouts/app.blade.php**

I have sections defined in **layouts/app.blade.php**. But in any views that extend **layouts/channel.blade.php**, these sections stop appearing.

My **layouts/app.blade.php** file looks like this:

```php
@extends('layouts.master')

@section('navbar.nav.left')
    <!-- Navbar left content -->
@endsection

@section('navbar.nav.right')
    <!-- Navbar right content -->
@endsection
```

And my **layouts/channel.blade.php** template looks like this:

```php
@extends('layouts.app')
```

Screen-shot of a view that extends **layouts/app.blade.php** (navbar content visible):

![screen shot 2017-02-22 at 22 01 58](https://cloud.githubusercontent.com/assets/167312/23234643/a3bc8124-f94a-11e6-8462-faa9e920e9bd.png)

Screen-shot of a view that extends **layouts/channel.blade.php** (navbar content blank):

![screen shot 2017-02-22 at 22 02 11](https://cloud.githubusercontent.com/assets/167312/23234676/b83cc29e-f94a-11e6-88e5-195899ec395c.png)

My **layouts/channel.blade.php** template _isn’t_ re-defining or overwriting these sections. And the navbar _used_ to work on these pages. So this seems like a Blade processing issue that’s recently been introduced.

**Comment by themsaid** [comment]
The issue doesn't seem to exist in latest 5.4, please upgrade your application and ping me if the issue still exists.

Or you can upload a test app on a public repo that I can clone and see if I can replicate the issue using your setup.
