### ISSUE TITLE
Invalid class name is generated if migration name contains "dummy_table"

### ISSUE THREAD

**Issue by slimtim** [laravel/framework#18067]
- Laravel Version: 5.4.12
- PHP Version: 7.0.15
- Database Driver & Version: MySQL 5.6.32

### Description:
When using make:migration with either the --create or --table flags, if "dummy_table" is in the migration name the generated class has the wrong class name.
 
I recently started playing around with Laravel and tried to create my first test migration. I used this command taken from the documentation as a guide:
php artisan make:migration create_users_table --create=users
At this point I had gone through the Authentication section of the docs and so already had a users table in my db. I instead decided to name the new table dummy. So I ran:
php artisan make:migration create_dummy_table --create=dummy  

When I ran the auto-generated migration I got a fatal "class not found" error:
php artisan migrate
  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'CreateDummyTable' not found

In this case, the placeholders in the migration stub are not being properly substituted in this method:
https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Migrations/MigrationCreator.php#L115-L127

As a result, the class name in the migration is incorrectly declared as:
class Createdummy extends Migration
Instead of:
class CreateDummyTable extends Migration

This is a rare edge case that will affect very few people but it could be better handled.

### Steps To Reproduce:
Run:
php artisan make:migration create_dummy_table --create=dummy 

Try to run the migration; a fatal error will occur:
php artisan migrate
  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'CreateDummyTable' not found

In the migration file the class name is "Createdummy" instead of "CreateDummyTable".

This will occur any time the migration name contains the string "dummy_table" and the --create or --table flag is used. For example:
php artisan make:migration update_some_dummy_table --table=some_dummy
php artisan make:migration update_some_dummy_table --table=foobar

**Comment by themsaid** [comment]
Closing for now, will look into updating the stubs in the core today. thanks :)
