### ISSUE TITLE
Read Only illuminate package versions not up to date with laravel/framework

### ISSUE THREAD

**Issue by RemiCollin** [laravel/framework#18061]
- Laravel Version: 5.4
- PHP Version: 7.0
- Database Driver & Version: ? N/A

### Description:

See : https://github.com/laravel/internals/issues/422

When requiring illuminate packages separately from `laravel/framework` the resolved version is not up to date with the latest release. Right now, framework version is `5.4.12`, and requiring a package results in composer resolving it to `5.4.9`. 

### Steps To Reproduce:

Create an empty composer project : `composer init`

Require any illuminate component: `composer require illuminate\database`

**Comment by devcircus** [comment]
Looks like all of the current illuminate packages were brought up-to-date a couple of hours ago and tagged for 5.4.13.
