### ISSUE TITLE
[5.4] Interacts with Queue on Mail

### ISSUE THREAD

**Issue by ssuhat** [laravel/framework#18065]
- Laravel Version: 5.4.13
- PHP Version: 7.1
- Database Driver & Version: Maria DB 10

### Description:
Cannot Interacts with Queue on Mail for example: `tries` , `timeout` like on Jobs

### Steps To Reproduce:
on my Mail\PasswordReset.php:
 
        class PasswordReset extends Mailable implements ShouldQueue
	{
	    use Queueable, SerializesModels, InteractsWithQueue;

	    public $tries = 1;

	    public $email, $token;

	    /**
	     * Create a new message instance.
	     *
	     * @param $email
	     * @param $token
	     */
	    public function __construct($email, $token)
	    {
	        $this->email = $email;
	        $this->token = $token;
	    }

	    /**
	     * Build the message.
	     *
	     * @return $this
	     */
	    public function build()
	    {
	        return $this->markdown('front.emails.auth.password-reset');
	    }
	}

**Comment by themsaid** [comment]
> Cannot

Please share more details, what's not working?

**Comment by ssuhat** [comment]
` public $tries = 1;` function is not working. I still need to command `art queue:work --tries=1`.

**Comment by tomcoonen** [comment]
I seem to have a similiar issue, I implemented ShouldQueue but setting the queue in the constructor doesn't have any effect. The mail isn't even queued.
```
    public function __construct()
    {
        $this->queue = 'email';
    }
```

**Comment by themsaid** [comment]
Are you using `ShouldQueue`? @tomcoonen

**Comment by tomcoonen** [comment]
@themsaid I got an email notification but don't see your post here, I added some extra info to my original comment.

**Comment by themsaid** [comment]
@tomcoonen I think this is something else, I just tested your scenario and it works fine please double check your `email` queue.

**Comment by themsaid** [comment]
@ssuhat opened a PR to add this feature: https://github.com/laravel/framework/pull/18103

Thanks

**Comment by tomcoonen** [comment]
@themsaid found it: https://github.com/laravel/framework/issues/18147
