### ISSUE TITLE
Add log event when session drops value

### ISSUE THREAD

**Issue by apokryfos** [laravel/framework#18076]
- Laravel Version: 5.3.0
- PHP Version: 7.0
- Database Driver & Version: MySQL 5.7

### Description: 
I would suggest to raise a logging event (possibly a debug level event) when a session is about to drop a value because it is unable to serialize it. 
Relates to StackOverflow question : http://stackoverflow.com/questions/42413061/redirect-with-exception-variable 
Adding logging to this would make it easier to diagnose issues with session variables not being passed correctly. 

### Steps To Reproduce:

(Since this is a new feature request it's not currently reproducible).

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
