### ISSUE TITLE
@parent function keeps placeholder in view

### ISSUE THREAD

**Issue by Thorazine** [laravel/framework#18073]
- Laravel Version: 5.4.13
- PHP Version: 5.6.15
- Database Driver & Version: mysql 5.6

### Description:
@parent function keeps placeholder in view

### Steps To Reproduce:
Create 2 views:

```
@include('testa')
@yield('a')
```

```
test A
@parent
```

results in
```
test A
##parent-placeholder-da39a3ee5e6b4b0d3255bfef95601890afd80709##
```

**Comment by themsaid** [comment]
That's because there's no parent to the view as far as I can tell, you shouldn't use @parent unless you're inside a section that has a parent.

**Comment by Thorazine** [comment]
Ah yes, sorry. My use case totally blows. I did some more digging and found where the problem lies. I opened a new ticket for it. 
You the man, thanks!
