### ISSUE TITLE
Route::any() does not include OPTIONS method

### ISSUE THREAD

**Issue by SamuraiJack** [laravel/framework#18070]
Route::any()  - does not work for OPTIONS request

Route::match([ 'get', 'post', 'put', 'patch', 'delete', 'options' ], ... - does work.

**Comment by SamuraiJack** [comment]
Laravel 5.3

**Comment by SamuraiJack** [comment]
It seems OPTIONS is just forgotten:

```
    /**
     * Register a new route responding to all verbs.
     *
     * @param  string  $uri
     * @param  \Closure|array|string|null  $action
     * @return \Illuminate\Routing\Route
     */
    public function any($uri, $action = null)
    {
        $verbs = ['GET', 'HEAD', 'POST', 'PUT', 'PATCH', 'DELETE'];

        return $this->addRoute($verbs, $uri, $action);
    }
```

**Comment by dbonner1987** [comment]
@SamuraiJack see this thread: https://github.com/laravel/framework/issues/14858

Are you pre-flighting CORS or trying to return something else entirely? 

I'd advise using https://github.com/barryvdh/laravel-cors if you want to handle CORS pre-flighting.

**Comment by themsaid** [comment]
Yes it won't work, use https://github.com/barryvdh/laravel-cors

**Comment by SamuraiJack** [comment]
At least the docs should say:

```
    /**
     * Register a new route responding to all verbs, except OPTIONS.
     */
```
Otherwise for the user, its mystical behavior - docs says "OPTIONS" is included and in fact its not.

**Comment by SamuraiJack** [comment]
And the guide at https://laravel.com/docs/5.3/routing should be updated as well.

**Comment by SamuraiJack** [comment]
Ehm.. So you think everything is correct, both in behavior and in documentation?

**Comment by fernandobandeira** [comment]
Yes that's intentional because matching OPTIONS with any would execute the request/action which is not intended, OPTIONS is used to describe what you can do and not execute an action so it's intentionally not matching it...

So why would you use OPTIONS with any?

**Comment by themsaid** [comment]
Check here: https://github.com/laravel/framework/issues/14858#issuecomment-246364751

**Comment by SamuraiJack** [comment]
Well, I'm working on converting "legacy" php application into Laravel one. In legacy code, we have a single CORS "handler", that is reacting on both "OPTIONS" and "POST". The requests to legacy codebase goes through the Laravel routing. 

I could explain it in more details if you want, my point is just that documentation should explicitly mention, that verb OPTIONS is not included - it took me couple of hours to find why Route::any() does not pass through the OPTIONS requests..

**Comment by SamuraiJack** [comment]
Still think you should update the docs properly guys, up to you of course.

**Comment by fernandobandeira** [comment]
You can create an issue for that on laravel/docs or suggest a PR, I didn't create one because i'm not sure where would be a good place for it...
