### ISSUE TITLE
Laravel Route parameter whereIn

### ISSUE THREAD

**Issue by LSDx** [laravel/framework#18097]
- Laravel Version: 5.4
- PHP Version:  7.1
- Database Driver & Version: MySQL

### Description:
I have route: /{locale}/{page?}
Is it possible to match {page?} with something like ->whereIn('{page}', ['articles', 'contacts', ...]) ?

**Comment by themsaid** [comment]
You can use regex for that.

Closing since it's not a bug report.

**Comment by sdeav** [comment]
I think, now you can do it...
