### ISSUE TITLE
5.4 - present rule behaving differently

### ISSUE THREAD

**Issue by gauravmak** [laravel/framework#18093]
- Laravel Version: 5.4.12
- PHP Version: 7.0

### Description:
I just upgraded from 5.3 and facing failures with 'present' validation rules which were passing in 5.3.
If an input could be empty, I was using that rule. Now, I am replacing them with 'nullable' rule.
Is there any specific change regarding its behavior?

**Comment by themsaid** [comment]
Please share example of a failing case.

**Comment by gauravmak** [comment]
Sure. Here are 2 attachments. One is errors generated by validator and other is my code change today to prevent that. Note that there were no validation issues while we were at Laravel 5.3

![errors](https://cloud.githubusercontent.com/assets/11887260/23300967/00b4e42a-faae-11e6-8dec-1efd2b290e1a.jpeg)
![code_change](https://cloud.githubusercontent.com/assets/11887260/23301081/668bcf2a-faae-11e6-92c1-f6f39a570ab2.png)

**Comment by themsaid** [comment]
I meant a simple case where present fails :) Given this data and these rules I expect present to pass but it fails. something like that.

**Comment by gauravmak** [comment]
No problem. I will make one today evening.

**Comment by themsaid** [comment]
Please open a new issue when you're ready :)
