### ISSUE TITLE
phalcon changes the behavior of __call, it'll make artisan command failed.

### ISSUE THREAD

**Issue by huturen** [laravel/framework#18095]
- Laravel Version: 5.4.12
- PHP Version: 5.6.5  5.6.30
- Database Driver & Version:

### Description:
phalcon changes the behavior of __call, it'll make artisan command failed.
  [ErrorException]     
  Undefined offset: 0

### Steps To Reproduce:

1. phpbrew switch 5.6.30 
2. phpbrew ext install github:phalcon/cphalcon 1.3.5
3. php artisan optimize

### Source
./vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php
```
    public static function __callStatic($method, $args)
    {
        $instance = static::getFacadeRoot();

        if (! $instance) {
            throw new RuntimeException('A facade root has not been set.');
        }

        return $instance->$method(...$args);
    }
```

->

./vendor/laravel/framework/src/Illuminate/Routing/Router.php
```
    public function __call($method, $parameters)
    {
        if (static::hasMacro($method)) {
            return $this->macroCall($method, $parameters);
        }

        return (new RouteRegistrar($this))->attribute($method, $parameters[0]);
    }
   $parameters would be an empty array after enabling phalcon extension, 
   and it throws an exception "Undefined offset: 0"
```

**Comment by huturen** [comment]
My system is Debain, and php is installed with phpbrew.

**Comment by srmklive** [comment]
This shouldn't be happening. I myself have installed Phalcon for multiple php versions on my dev machine. I think this might be an issue with phpbrew.

**Comment by crynobone** [comment]
Either way this isn't Laravel bug.

**Comment by themsaid** [comment]
I agree with @crynobone, this is not a Laravel bug.

**Comment by huturen** [comment]
the screenshots as below: 
it's not a Laravel bug, but it has a potential problem on some platforms.

./vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php
```
    public static function __callStatic($method, $args)
    {
        $instance = static::getFacadeRoot();

        if (! $instance) {
            throw new RuntimeException('A facade root has not been set.');
        }

        return $instance->$method(...$args);
    }
```
maybe ... operator is not perform good with phalcon extension on special platforms
or maybe just an issue with phpbrew @srmklive 


![abc](https://cloud.githubusercontent.com/assets/5173298/23301524/4d9cdbdc-fac5-11e6-9443-77009a37e8bf.png)
![undefined](https://cloud.githubusercontent.com/assets/5173298/23301530/52dc475e-fac5-11e6-97c3-e11222dd6138.png)

**Comment by srmklive** [comment]
@huturen This could be due to the fact you may be trying to use some Phalcon library in your Laravel application. Otherwise it just doesn't happen. @crynobone is right in this regard, that it is not a Laravel bug.

**Comment by crynobone** [comment]
> maybe ... operator is not perform good with phalcon extension on special platforms
or maybe just an issue with phpbrew

```php
$instance->$method(...$args);
```

`...$args` is a standard PHP 5.6 features, if for some reason phalcon or phpbrew doesn't support it it's should be reported to respective projects. 

See: http://php.net/manual/en/migration56.new-features.php#migration56.new-features.variadics
