### ISSUE TITLE
Middleware API

### ISSUE THREAD

**Issue by rdehnhardt** [laravel/framework#18100]
- Laravel Version: 5.4

### Description:
It would be very cool if we used the middleware API the errors were reported in JSON format

**Comment by themsaid** [comment]
Validation errors are already transformed to JSON when the request is AJAX or wants JSON as a content type.

For other exceptions you need to explicitly decide how to display them, you can do that in the exception handler, something like:

```
$request->ajax() && ! $request->pjax()) || $request->wantsJson()
```
