### ISSUE TITLE
security validator bug

### ISSUE THREAD

**Issue by LuttyYang** [laravel/framework#18102]
- Laravel Version: 5.3-5.4
- PHP Version: any
- Database Driver & Version: any

### Description:

if I need test a input is a positive integer, I alaway use the `integer|min:1`, but it has a security issue, if input has space, the validator result is incorrect...

I think the problem is very serious.

Maybe I use the validator in the wrong way?

### Steps To Reproduce:

you can reproduce by this code:

```
                $v = \Validator::make([
			'test' => ' -100 '
		], [
			'test' => 'required|integer|min:1'
		]);

		if (!$v->fails()){
			die('pass');
		}else{
			dump($v->failed());
			die('error');
		}
```

**Comment by fernandobandeira** [comment]
It's not a security bug, I'll explain why:

In your example min will be testing '-100 ' as a string thus it'll pass since it has more than 1 char.
The space problem is easily solved by using the TrimSpaces middleware on 5.4 so it'll handle it as a number without any issues...

**Comment by LuttyYang** [comment]
@fernandobandeira 

Thank you for your solution, but what are the good solutions on laravel 5.3?

**Comment by LuttyYang** [comment]
but I think, If we specify the validation rule "integer", is the "min" validation rule that does not treat the input as a number?

**Comment by fernandobandeira** [comment]
Probably create the 5.4 middleware on 5.3 and register it:

\App\Http\Middleware\TrimStrings
```php
<?php

namespace Illuminate\Foundation\Http\Middleware;

class TrimStrings extends TransformsRequest
{
    /**
     * The attributes that should not be trimmed.
     *
     * @var array
     */
    protected $except = [
        'password',
        'password_confirmation',
    ];

    /**
     * Transform the given value.
     *
     * @param  string  $key
     * @param  mixed  $value
     * @return mixed
     */
    protected function transform($key, $value)
    {
        if (in_array($key, $this->except, true)) {
            return $value;
        }
        return is_string($value) ? trim($value) : $value;
    }
}
```

Then register it on your Kernel.php file:
```php
protected $middleware = [
    ...   
    \App\Http\Middleware\TrimStrings::class,
    ...
];
```

**Comment by fernandobandeira** [comment]
Also regarding you second comment, the rules are independent so it doesn't affect each other behavior, integer isn't failing because if you run ``` filter_var($value, FILTER_VALIDATE_INT) ``` on your value it'll return a filtered value, since it's not an integer but it can filter the value to be an integer.

However indeed it's an odd behavior, maybe we could change how min checks if the value is a number or string perhaps trying to filter it first any ideas @themsaid ?

**Comment by LuttyYang** [comment]
@fernandobandeira 

This code also returns pass:

```
        $v = \Validator::make([
		'test' => -100
	], [
		'test' => 'required|min:1'
	]);

	if (!$v->fails()){
		die('pass');
	}else{
		dump($v->failed());
		die('error');
	}
```

**Comment by LuttyYang** [comment]
In Laravel 5.3 ,I see this code in validate farmework:

```
/**
     * Get the size of an attribute.
     *
     * @param  string  $attribute
     * @param  mixed   $value
     * @return mixed
     */
    protected function getSize($attribute, $value)
    {
        $hasNumeric = $this->hasRule($attribute, $this->numericRules);

        // This method will determine if the attribute is a number, string, or file and
        // return the proper size accordingly. If it is a number, then number itself
        // is the size. If it is a file, we take kilobytes, and for a string the
        // entire length of the string will be considered the attribute size.
        if (is_numeric($value) && $hasNumeric) {
            return $value;
        } elseif (is_array($value)) {
            return count($value);
        } elseif ($value instanceof File) {
            return $value->getSize() / 1024;
        }

        return mb_strlen($value);
    }
```

The code `is_numeric($value) && $hasNumeric` proving that they are interdependent, but I think this code the designer's meaning is `is_numeric($value) || $hasNumeric`

Maybe it is a mistakes?



PS. My English is very bad, please forgive me for the inconvenience brought to you.

**Comment by fernandobandeira** [comment]
Yes you're right i were testing it right now and saw it too, however this may be breaking i can't assure this will go to 5.3 or even 5.4...

**Comment by themsaid** [comment]
`is_numeric($value) || $hasNumeric` makes more sense yes, checking to see if using this might break other cases.

**Comment by themsaid** [comment]
I can confirm it's a breaking change and can't go to 5.3 or even 5.4, using `is_numeric($value) || $hasNumeric` breaks the case when the input passed is string `"12345"` and you want to validate it as a string `min:5`, so here you want to say that this input should have 5 characters.

I don't think this change will ever going to happen, better use `integer|min:` but clean your input before passing to the validator.

**Comment by LuttyYang** [comment]
try this code: `$hasNumeric || (is_numeric($value) && $hasNumeric)`, maybe ok?

**Comment by LuttyYang** [comment]
maybe can try this code:

```
/**
     * Get the size of an attribute.
     *
     * @param  string  $attribute
     * @param  mixed   $value
     * @return mixed
     */
    protected function getSize($attribute, $value)
    {
        $hasNumeric = $this->hasRule($attribute, $this->numericRules);

        // This method will determine if the attribute is a number, string, or file and
        // return the proper size accordingly. If it is a number, then number itself
        // is the size. If it is a file, we take kilobytes, and for a string the
        // entire length of the string will be considered the attribute size.
        if (is_numeric($value) && $hasNumeric) {
            return $value;
        } elseif ($hasNumeric) {
            return filter_var($value, FILTER_VALIDATE_INT);
        } elseif (is_array($value)) {
            return count($value);
        } elseif ($value instanceof File) {
            return $value->getSize() / 1024;
        }

        return mb_strlen($value);
    }
```

**Comment by LuttyYang** [comment]
@fernandobandeira @themsaid 

I test this code, it work fine:
```
    /**
     * Get the size of an attribute.
     *
     * @param  string  $attribute
     * @param  mixed   $value
     * @return mixed
     */
    protected function getSize($attribute, $value)
    {
        $hasNumeric = $this->hasRule($attribute, $this->numericRules);

        // This method will determine if the attribute is a number, string, or file and
        // return the proper size accordingly. If it is a number, then number itself
        // is the size. If it is a file, we take kilobytes, and for a string the
        // entire length of the string will be considered the attribute size.
	    if (is_string($value) && !$hasNumeric){
		    return mb_strlen($value);
	    }else if (is_numeric($value) || $hasNumeric) {
            return $value;
        } elseif (is_array($value)) {
            return count($value);
        } elseif ($value instanceof File) {
            return $value->getSize() / 1024;
        }

        return mb_strlen($value);
    }
```

this is test code:
```
	$v = \Validator::make([
		'testNumber'       => -100,
		'testString'       => "-100",
		'testNumberString' => " -100 ",
	], [
		'testNumber'       => 'required|min:1',
		'testString'       => 'required|min:1',
		'testNumberString' => 'required|integer|min:1',
	]);

	if (!$v->fails()) {
		die('pass');
	} else {
		dump($v->failed());
		die('error');
	}
```

**Comment by themsaid** [comment]
@LuttyYang feel free to open a PR then :)

**Comment by GrahamCampbell** [comment]
Thanks everyone.
