### ISSUE TITLE
[5.3][5.4] APP_ENV in phpunit.xml has no effect

### ISSUE THREAD

**Issue by pixelpeter** [laravel/framework#18101]
- Laravel Version: 5.3, 5.4
- PHP Version: 7.0
- Database Driver & Version: unrelated

### Description:
In `phpunit.xml` you can find this entry
```xml
...
<env name="APP_ENV" value="testing"/>
...
```
So I assume we should be able to set `APP_ENV` when running `./vendor/bin/phpunit`.

But this won't work because in `\Illuminate\Foundation\Testing\TestCase\refreshApplication()` the environment is hard coded like this:
```php
...
putenv('APP_ENV=testing')
...
```

So as far as I can see this line doesn't make any sense because it has no effect.

Is this the wanted behavior or am I missing something?
In my current (given) set-up I would need to be able to overwrite APP_ENV while running `phpunit` in/on different environments (e.g. teamcity) where I'm not able to store a environment specific `.env.testing` file

**Comment by themsaid** [comment]
Check https://github.com/laravel/framework/issues/16412
