### ISSUE TITLE
withCount is slow with large models

### ISSUE THREAD

**Issue by brianwozeniak** [laravel/framework#18109]
- Laravel Version: 5.4.13
- PHP Version: 7.0
- Database Driver & Version: MySQL 5.7.9

### Description:
Counting related models with withCount is awesome, however, once the number of rows in the related tables get high it is really slow. In my situation it is taking around 10 seconds. As an example, I have a posts, tags, and post_tag table. Here are the number of rows in each table:

posts: 541289
tags: 58
post_tag: 80144

When using withCount the SQL query that gets generated is:

```
select tags.*, (select count(*) from posts inner join post_tag on posts.id = post_tag.post_id where tags.id = post_tag.tag_id) as posts_count from tags
```

This query takes 10.3063 seconds, even with proper indexes in place on InnoDB. Since this would be unacceptable for my users, I have (for now), got around this by creating a model called:

PostTag

and then creating a hasMany relation in the Tags model to the PostTag pivot table:

```
return $this->hasMany(PostTag::class, 'tag_id');
```

From there I call the same withCount() on this relation:

```
$tags->withCount(['postTag'])->get()
```

This achieves the same results, but the query is much faster at 0.0113 seconds. By creating a relation directly with the post_tag table the query that gets generated instead looks like this:

```
select tags.*, (select count(*) from post_tag where tags.id = post_tag.tag_id) as post_tag_count from tags
```

The part that is slow with the current `withCount` is the fact that it does a join with the posts table when that table is not needed to get a simple count. All that is needed is the pivot table, and this should be the same for all circumstances for withCount. I am not sure what complexities would be involved in making withCount create that more optimized query, but if it is possible this would greatly achieve the performance in getting the counts of the related models.

**Comment by Nacoma** [comment]
It's not the same for all circumstances. Your suggestion ignores the possibility of soft deleted records.

**Comment by brianwozeniak** [comment]
You are correct, my solution would only work with deleted models from one side in this scenario. Maybe an optimization can only be made if soft deletes aren't being used then.
