### ISSUE TITLE
Invalid dependency resolving

### ISSUE THREAD

**Issue by mbm-rafal** [laravel/framework#18110]
- Laravel Version: 5.3.30
- PHP Version: 5.6.26

### Description:
Invalid parameter resolving while using make function.
When using ```app()->make(Test::class, ["parameter1"]);```

I expect that second parameter will be NULL instead of that it's resolved for provided Class/Interface. NULL will be as expected only if ```app()->make(Test::class, ["parameter1", null]);``` is done.

### Steps To Reproduce:

1. Setup

```
class Test {

    private $param;
    private $request;

    public function __construct($param, Request $request = null)
    {
        $this->param = $param;
        $this->request = $request;
    }

}
```

2. Execute

```$object = app()->make(Test::class, ["parameter1"]); dd($object); ```

**Comment by themsaid** [comment]
Closing since 5.3 is not supported anymore, please upgrade to laravel 5.4.
