### ISSUE TITLE
Storing image using Storage facade creates duplicate UUID

### ISSUE THREAD

**Issue by ingageco** [laravel/framework#18118]
- Laravel Version: 5.3
- PHP Version: 5.6.14
- Database Driver & Version: n/a

### Description:
Brief - uploading the same image to multiple resources creates the same File UUID / name.

I'm using the Storage facade to upload to S3. I've used the same image on a few created resources and all 3 now have the same file name. This is an issue because if one resource is deleted, so is the image -- thus leaving the other 2 with a broken link. 

### Steps To Reproduce:

Upload an image using Storage facade and use: 

$request->file('fileinput')->storePublicly($foldername, 's3');

At least that's what produces the same UUID for me. Thanks!

**Comment by ingageco** [comment]
I'm using the term UDID per the Laravel File Storage documentation: 

 _By default, the putFile method will generate a UUID to serve as the file name. The path to the file will be returned by the putFile method so you can store the path, including the generated file name, in your database._

**Comment by themsaid** [comment]
That was fixed in 5.4, I recommend that you upgrade since 5.3 support is very limited and will stop next month.
