### ISSUE TITLE
$with property on models can cause an infinite loop

### ISSUE THREAD

**Issue by rs-sliske** [laravel/framework#18111]
- Laravel Version: 5.4.13
- PHP Version: 7.0.15
- Database Driver & Version: sqlite

### Description:
basically if you have 2 models related to each other, and set $with on both, you will end up in an infinite loop

ill look into it a bit more tomorrow if i get chance, but first thought is whether it would be possible to remember models we have already retrieved, and to avoid trying to build them again

### Steps To Reproduce:
create 2 models, in my case i have Order and OrderLine, order has many orderlines

set $with property on order model to orderlines

set $with property on orderline model to order

attempt to get an order model which has lines

**Comment by themsaid** [comment]
Yes, don't do that use it only when it makes sense.
