### ISSUE TITLE
Image validation

### ISSUE THREAD

**Issue by simoebenhida** [laravel/framework#18120]
- Laravel Version: 5.4
- PHP Version:7
- Database Driver & Version:

When i use image validation and i add a file .php extension and content image it is accepted.

The php file have a image content and a php code that can allow you to run commands on server.
(I GOT HACKED BY THIS WAY)

**Comment by joshmanders** [comment]
> When i use image validation and i add a file .php extension 

You should probably not have `.php` as a valid image extension...

**Comment by edenreich** [comment]
you should add another validation of mime types, please refer to the documentation: https://laravel.com/docs/5.4/validation#rule-mimes

**Comment by simoebenhida** [comment]
@edenreich Thank you didnt see that it's my bad :P
