### ISSUE TITLE
Running Unit Tests with PHPDBG

### ISSUE THREAD

**Issue by REBELinBLUE** [laravel/framework#18121]
- Laravel Version:  5.4.13
- PHP Version: 7.0.15
- Database Driver & Version: N/A

### Description:

If you use phpdbg to generate code coverage instead of xdebug you can't test code which triggers the VerifyCsrfToken code.

It will fail with

```json
{"error":{"type":"Illuminate\\Session\\TokenMismatchException","message":"","file":"\/path\/to\/project\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/VerifyCsrfToken.php","line":68}}
```

This is because in the `runningUnitTests` method it uses the `runningInConsole` method of the Application, which checks that the php_sapi_name is `cli` but when using phpdbg it is `phpdbg`

### Steps To Reproduce:

Test a controller which uses the CSRF middleware

`$ phpdbg -qrr vendor/bin/phpunit --no-coverage tests/Features/MyControllerTest.php`

**Comment by REBELinBLUE** [comment]
You can get the tests actually run using

`$ phpdbg -S cli -qrr vendor/bin/phpunit --no-coverage tests/Features/MyControllerTest.php`

to overwrite the SAPI. However, then it doesn't collect code coverage as `sebastianbergmann/environment` depends on the SAPI being `phpdbg` https://github.com/sebastianbergmann/environment/blob/master/src/Runtime.php#L179-L193

**Comment by REBELinBLUE** [comment]
Uh, what? @themsaid why is this closed? Laravel clearly has code to determine if it is running in a unit test and it doesn't work correctly using PHP's built in debugger

**Comment by themsaid** [comment]
Sorry thought it was resolved!

**Comment by REBELinBLUE** [comment]
No worries, was a bit confused there 😂 I mean it is easy to patch https://www.phpdeployment.org/patches/0001-Support-PHPDBG.patch I just don't want to do a PR myself as I don't know Laravel well enough to know what else that method is used for so what knock on affects it might have

**Comment by GrahamCampbell** [comment]
That patch won't work, since we have now broken the case when you **not** using phpdbg in the context of the console.

**Comment by REBELinBLUE** [comment]
Exactly what I was expecting hence not doing a PR as I am unsure of what else it would impact ;)

**Comment by GrahamCampbell** [comment]
Yeh. I d'no what's least worse. Maybe we could just make this change on master if nobody can think of a better way. :P

**Comment by REBELinBLUE** [comment]
Just reading a bit more about PHPDBG... sounds like it is only ever in the CLI context not used for debugging web server process (although of course that could have changed since then) https://github.com/bwoebi/phpdbg-docs/issues/1#issuecomment-163872806

**Comment by GrahamCampbell** [comment]
Ok. Please send a PR then. :)

**Comment by courtney-miles** [comment]
For anyone who might find this when looking for a solution for `phpdbg` being reported from `php_sapi_name()` rather than `cli`, note that you do not have to change your code to suit your debugger as was done for Laravel.

Rather, you can call `phpdbg` with the `-S` option to override the SAPI. For example, `phpdbg -Scli`. I would suggest this is the more correct solution.

You can find mention of this option, and other options, in the phpdbg help.

```bash
$ phpdbg
prompt> help options

Below are the command line options supported by phpdbg

Command Line Options and Flags
  Option  Example Argument    Description
  -c      -c/my/php.ini       Set php.ini file to load
  -d      -dmemory_limit=4G   Set a php.ini directive
  -n                          Disable default php.ini
  -q                          Suppress welcome banner
  -v                          Enable oplog output
  -b                          Disable colour
  -i      -imy.init           Set .phpdbginit file
  -I                          Ignore default .phpdbginit
  -O      -Omy.oplog          Sets oplog output file
  -r                          Run execution context
  -rr                         Run execution context and quit after execution (not respecting
breakpoints)
  -e                          Generate extended information for debugger/profiler
  -E                          Enable step through eval, careful!
  -s      -s=, -s=foo         Read code to execute from stdin with an optional delimiter
  -S      -Scli               Override SAPI name, careful!
  -l      -l4000              Setup remote console ports
  -a      -a192.168.0.3       Setup remote console bind address
  -x                          Enable xml output (instead of normal text output)
  -p      -p, -p=func, -p*    Output opcodes and quit
  -h                          Print the help overview
  -V                          Print version number
  --      -- arg1 arg2        Use to delimit phpdbg arguments and php $argv; append any $argv
argument after it
```

**Comment by REBELinBLUE** [comment]
@courtney-miles See the second comment, if you do that code coverage is then not collected

**Comment by courtney-miles** [comment]
> See the second comment, if you do that code coverage is then not collected

Ah, I had misunderstood what was being pointed out in the second comment.

Thanks for taking the time to clarify.
