### ISSUE TITLE
@section + @parent with variable as section name leaves placeholder in view

### ISSUE THREAD

**Issue by Thorazine** [laravel/framework#18132]
- Laravel Version: 5.4.13
- PHP Version: 5.6.15
- Database Driver & Version: mysql 5.6

### Description:
When using a variable instead of quoted string in a section with an ```@parent```, the placeholder stays in view.
Remove the ```@parent``` and the section works as expected. 
Replace the ```$bar``` with ```'main'``` and the section works as expected.

### Steps To Reproduce:

Create two views:

```
@include('foo')
@yield('main')
```

```
<?php $bar = 'main'; ?>
@section($bar)
    foo
    @parent
@stop
```

### Expected result:

```
foo
```

### But get:

```
foo
##parent-placeholder-f0966c2583047438f7a8106aa6cddc5ba5926cfb##
```

**Comment by themsaid** [comment]
Section names are not meant to be dynamic.

**Comment by Thorazine** [comment]
This is a change I do not agree with. Cause in 5.3 and before this works. And if sections are not supposed to be dynamic, why would it work when not using ```@parent```.

**Comment by themsaid** [comment]
The problem is specifically with @parent, we had to fix an issue related to it that was present in 5.3 and that lead to a change where we need to know the section name before compilation, and that's why using variables will cause @parent not to be replaced properly.

**Comment by Thorazine** [comment]
Good point. 
Found a workaround that works for the ones looking:

- Create a blade for all the types of yields you want to push in to. 
- Include that blade by variable with ```@parent```
- Include the view you want in the new blade.
