### ISSUE TITLE
FirstOrFail on relation throwing with wrong model class name

### ISSUE THREAD

**Issue by neronmoon** [laravel/framework#18130]
- Laravel Version: 5.4
- PHP Version: 7.1
- Database Driver & Version: mysql

### Description:
I'm getting wrong error message in ModelNotFound exception. 

### Steps To Reproduce:
Create model User:
```
class User extends Model
{
	public function websites()
	{
		return $this->belongsToMany(Website::class, 'website_users');
	}
}
```

Create model Website:
```

class Website extends Model
{

}

```
Try to get non-existent website from user's relation
```
$user = User::first();
$user->websites()->where('website_id', 101010)->firstOrFail();
```

You getting `No query results for model [App\\User].`, however `No query results for model [App\\Website].` should be thrown

**Comment by themsaid** [comment]
Thank you, opened a PR with a fix: https://github.com/laravel/framework/pull/18138
