### ISSUE TITLE
Eloquent eager load camel case name behavior

### ISSUE THREAD

**Issue by komirad** [laravel/framework#18133]
- Laravel Version: 5.4
- PHP Version: 7
- Database Driver & Version: MySQL

### Description:
For example, with 2 models `Book` and `BookGroup` where `Book` belongs to `BookGroup`. One would eager load `BookGroup` like this: `Book::with('bookGroup')->findOrFail(1);`

The problem is the returned resource puts the `BookGroup` in an attribute called `book_group`.

But I can also NOT use camel case like this: `Book::with('bookgroup')->findOrFail(1);` and it'll still work except that the resulting attribute is `bookgroup`. (Yes, PHP methods are case insensitive.)

Either way, I cannot get back a attribute named `bookGroup` which is what I need. 

This is problematic when working with other libraries. Using Fractal library's includes, for example:
```
// Camel cased
Book::with('bookGroup')->findOrFail(1);
// But must use snake cased. There's no way to use a camel cased include!
$fractal->parseIncludes(['book_group`]);
```

The expected behaviour should be having the resulting attribute follow the naming convention used in the argument. i.e. `bookGroup => bookGroup`. `book_group => book_group` and `bookgroup => bookgroup`.

**Comment by themsaid** [comment]
You can set `$snakeAttributes` to false if you want.

`Model::$snakeAttributes = false`, this will stop converting attributes to snake case.

**Comment by komirad** [comment]
@themsaid 

No. It's not just that.

When the relation method is named as `bookGroups()`. Lazy loaded `$book->bookGroup` still works. It's only when eager loaded via `with('bookGroups')` that this becomes `$book->book_groups`. 

In the end both are accessed the same way using `__get()` but they are using different properties.

`$snakeAttributes` or not, this is still a problem.

Also `$snakeAttributes` affects other attributes whereas this issue is about relationships only.

**Comment by themsaid** [comment]
Using `->load('bookGroup')` and `->with('bookGroup')` has the same result, which is a snake cased attribute.

That's the convention Eloquent follows on serialising a model, you easier snake case attributes or not, they're snake-case-ed by default.

**Comment by komirad** [comment]
@themsaid 

As far as I know there's no explicit convention for relation naming. Only an unspoken one. Documentation makes no mention of it.

One also does not lazy load with `->load('bookGroup')`. As in the documentation, one would expect to do `$book->book_group` or `$book->bookGroup`. However, `$book->book_group` lazy loading does not work. `$book->bookGroup` does, but within the model itself it is serialized to `book_group` -- which is also unexpected.

**Comment by themsaid** [comment]
Well, feel free to send a PR to the docs :) I'll put it on my list though.

**Comment by komirad** [comment]
Ok. Can you clarify what's the current convention to lazy load a multi-word relationship? As I said `$book->book_group` does not work unless the relationship is already loaded.

Why don't we just not snake case relationships by default? Seems like this would avoid a whole lot of problems.

On another note, currently db columns which are camel cased also remain camel cased. (Not saying there's anything wrong with that) 

I did a cursory search of the use of `Str::snake()` in Eloquent. Seems the only 2 places where it applies to attributes are relationships and mutators.

**Comment by themsaid** [comment]
You can use the method name `$book->bookGroup` to get the group, but if you do so why are you concerned about the serialised version?

Let's make it a bit clear, what are you trying to achieve?

**Comment by komirad** [comment]
I am just trying to have a consistent behaviour across my models and transformers. I am resorting to `with('bookgroup')` whereas I would like `with('bookGroup')`. My transformer include has to be `bookgroup` too. The only way I can have `bookGroup` for both is to have `$snakeAttributes=false`. That seems sub-optimal as `$snakeAttributes` is not specific to only relationships.

It's not directly related, but if it doesn't convert the case by default, both problems will be solved. Either that, or a less optimal `$snakeRelationshipAttributes`.

**Comment by komirad** [comment]
To add on on what I am trying to achieve and why it's a problem:

In Transformer include method, after eager loading via `bookgroup`, I have to use the lowercase property `bookgroup`. Using the camel case property `bookGroup` will just cause it to load all over again as Laravel thinks it's not loaded.

Now, in my class, I am using PHPDoc `@property BookGroup $bookGroup`. The variable name is case sensitive, so code hinting stops working. I use PHPDoc code hint to aid in refactoring. With that I can rename and find usages throughout my whole application.
