### ISSUE TITLE
[5.4] Mail not queued when using no 'to' on the Facade

### ISSUE THREAD

**Issue by tomcoonen** [laravel/framework#18147]
- Laravel Version: 5.4.13
- PHP Version: 7.0
- Database Driver & Version:

### Description:
Mail is not queued when using no 'to' on the Facade, setting a 'to' on the Facade doesn't make sense when the recipient is always dependent on the data sent to the Mailable class like in the example below.

### Steps To Reproduce:
Mail::send(new OrderPicked(Order::find(10000)));

**Comment by tomcoonen** [comment]
I'm solving it now by putting a Notification in between, and for some e-mails that makes sense since they will probably get more channels than e-mail.
But from my point of view it would be good to fix the issue so you can only send an e-mail like described.

**Comment by KennedyTedesco** [comment]
I believe it was fixed on this PR? https://github.com/laravel/framework/pull/18144

**Comment by tomcoonen** [comment]
@KennedyTedesco yes, closing.
