### ISSUE TITLE
Changing unsigned int to unsigned decimal loses signing

### ISSUE THREAD

**Issue by jamesgraham** [laravel/framework#18148]
- Laravel Version: 5.4.10
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7.16

### Description:
Migrating an existing column from unsigned integer to unsigned decimal fails to retain the signing. Creating a new unsigned decimal works correctly.

### Steps To Reproduce:
```
        Schema::create('test', function (Blueprint $table) {
            $table->unsignedInteger('duration');
            $table->decimal('test_duration', 11, 6)->unsigned();
        });

        Schema::table('test', function (Blueprint $table) {
            $table->decimal('duration', 11, 6)->unsigned()->change();
        });
```

**Comment by emcarson** [comment]
Same problem. Changing an unsigned tinyInteger to unsigned decimal in L5.4 fails to retain signing:

```
        Schema::create('offer_path', function (Blueprint $table) {
            //
            $table->tinyInteger('chance')->unsigned();
        });

        Schema::table('offer_path', function (Blueprint $table) {
            $table->decimal('chance', 5, 2)->unsigned()->change();
        });

```

**Comment by Dylan-DPC** [comment]
I don't see this as a laravel issue. It could be issue with MySQL or Doctrine/DBAL stuff

**Comment by GrahamCampbell** [comment]
I don't think this is a bug. It's just what your database server has decided what the semantics should be.

**Comment by selik44** [comment]
you have enum type column in table, so first you need remove enum column, and then you can change other column  types
