### ISSUE TITLE
 php artisan fails when ServiceProvider uses View::share with a database lookup

### ISSUE THREAD

**Issue by Janghou** [laravel/framework#18151]
- Laravel Version: 5.1-5.4
- PHP Version: 7-7.1, any
- Database Driver & Version: Mysql 5.7 - any

### Description:
Running `php artisan` fails when ServiceProvider uses View::share with a database lookup. Somehow `php artisan` runs share() in the boot function of the provider.

### Steps To Reproduce:
If you follow this example [Sharing Data With All Views](https://laravel.com/docs/5.4/views#sharing-data-with-all-views), and modify it a little:

     public function boot()
     {
       View::share('amount_users', \App\User::count()); 
     }

php artisan fails to run on developing machine, you can only run it on the (Homestead) virtual machine, which is not wanted behaviour IMHO.
Workaround is to not use share, but view->composer(*)

**Comment by sisve** [comment]
The word "Somehow" in your report scares me. Would it have been less of a surprise if you had written `performSurgery('amount_users', \App\Users::count());`? Of course the call to User::count() is executed from the service provider, that is exactly how the code is written.

The solution is to use a class-based composer, as you note, or a closure-based composer.

    View::composer('*', function ($view) {
        $view->with('amount_users', \App\User::count());
    });

Both solutions means that the call to User::count() is done when the view is rendered, not when the service provider executes. This also means that there wont be any database calls for this count when you use artisan commands (assuming they never render any views).

**Comment by Janghou** [comment]
I wrote somehow because I don't see the need for a cli command like `php artisan list` or `php artisan make:controller` to render any views. 
It is supposed to be  a console/cli command.

**Comment by themsaid** [comment]
Yes, service providers `boot()` methods are called on application bootstrap. Check @sisve suggestion.

**Comment by Janghou** [comment]
Don't agree:
`php artisan` is a major functionality, users should not run into this trouble following an example in the docs and tweaking it a little. 

So
- view::share should return void when no views are rendered
or
- the docs should be revised or at least get a warning,

**Comment by sisve** [comment]
@Janghou View::share() doesn't know if any view will be rendered; it executes _before_ any views are rendered. In this case, it executes in your service provider without any views every being rendered.

We've pointed out the issue, and provided you with accepted work-arounds (some may even consider it to be the correct way to do it begin with). What's left in this issue?

**Comment by Janghou** [comment]
Thx. It's not that I don't know how to solve it, the workaround was in my OP.

When it is all wanted behaviour, the documentation gives a poor first example for sharing data to views.  What's wrong with a warning?

But I guess I should open an issue for that at laravel/docs
