### ISSUE TITLE
php artisan up no error when no permission

### ISSUE THREAD

**Issue by xoryo** [laravel/framework#18158]
- Laravel Version: 5.4
- PHP Version: 7.1
- Database Driver & Version: MySQL

### Description:
No error is thrown when you run "php artisan up" and you don't have permissions to delete the file.

### Steps To Reproduce:
"php artisan up" as a user without permission

https://github.com/laravel/framework/blob/7212b1e9620c36bf806e444f6931cf5f379c68ff/src/Illuminate/Foundation/Console/UpCommand.php#L30

Is this done on purpose if so why?

**Comment by GrahamCampbell** [comment]
Ah, I think the purpose of this was to suppress the case when the file already existed. (We don't acquire a lock on it, so checking if it existed won't cut it, because another process could delete the file in between our check, and our attempt.
