### ISSUE TITLE
Should we include fzaninotto/faker under composer.json require packages?

### ISSUE THREAD

**Issue by renaldi1982** [laravel/framework#18163]
- Laravel Version: 5.4.13
- PHP Version:7.0
- Database Driver & Version: MySql, 5.7.16

### Description:
out of the box laravel 5.4 composer.json has fzazzinoto/faker under require-dev yet the package is required by core framework, DatabaseServiceProvider to be precise, this cause composer install failed when deploying the application under production environment where no dev packages get installed

### Steps To Reproduce:
run composer install --no-dev

**Comment by srmklive** [comment]
its an optional package. There is no need in my view to put it under require.

**Comment by renaldi1982** [comment]
Sorry i just had time to check this. 

srmklive: i agree it's an optional package yet deploying the app in production environment without having fzazzinoto/faker in composer.json require would fail the deployment because DatabaseServiceProvider require this package. 

i'm not sure if this is an issue or not, but i had to circumvented this issue on my end by including fzazzinoto/faker on require in composer.json, so it might be me not fully understanding how composer.json work and if i do i apologize for wasting anyone's time.

GrahamCampbell: could you elaborate as why this does not considered as an issue? i'm sorry if it sounds dumb, but id rather ask than not knowing the problem(or lack of thereis) and acted like i understand why this issue is being closed.
