### ISSUE TITLE
How to use Contextual binding with parameters

### ISSUE THREAD

**Issue by mbm-rafal** [laravel/framework#18168]
I want to resolve context binding with parameters like this:

```
$this->app->when(ParticipantAddedToWaitingList::class)
            ->needs(NotificationParamsResolverInterface::class)
            ->give(function ($event_id, $params = []) {
                return new EventNotificationParamsResolver($event_id, $params);
            });
```

```
app()->make(NotificationParamsResolverInterface::class, [123, [1,2,3]]);
```

is this possible? Or how could I achieve this ? I know that contextual binding is only resolveable from constructor which does not allows to put params, am I right ? Is there any workaround for that ?

**Comment by themsaid** [comment]
That was removed in Laravel 5.4, quoting from the upgrade guide:

> The container's make method no longer accepts a second array of parameters. This feature typically indicates a code smell. Typically, you can always construct the object in another way that is more intuitive.
