### ISSUE TITLE
Confliction default users table migration and documentation for old mysql and mariaDB.

### ISSUE THREAD

**Issue by HiroKws** [laravel/framework#18169]
- Laravel Version: 5.4
- PHP Version: -
- Database Driver & Version: mysql driver with MySQL < 5.7.7 or MariaDB < 10.2.2 (However, not related with any drivers.)

### Description:

Releases and Migration documentations mentioned about using 'Schema::defaultStringLength(191);' for MySQL < 5.7.7 or MariaDB < 10.2.2.

By this instruction, all omitted length 'string' method, like '$table->string('field_name');', generated 'VARCHAR(191)'.

And default migration for 'users' table in laravel/laravel repository, included '$table->string('email')->unique();'. This code make a field max 191 characters.

However, App\Http\Controllers\Auth\RegisterController validate email field by '|max:255' rule.

This will make a trouble when a user used long mail address that longer than 191 characters.

### Steps To Reproduce:

Follow Releases and Migration official documentations, and use default resources with fresh installed Laravel environment.

**Comment by HiroKws** [comment]
It needed add more explains to two documentation, or correct default migration file.

**Comment by sisve** [comment]
Just a though; we could start telling people how to actually configure their older database instances to still work.

1. Set `innodb_file_format=Barracuda` in my.cnf
2. Set `innodb_large_prefix=1` in my.cnf
3. Set `$table->engine = 'innodb row_format=dynamic';` in the migration.

That is all that is needed. This will keep migrations that generated 255 character long fields a year ago to keep generating 255 character long fields today.

Whoever made up the `Schema::defaultStringLength(191);` solution should be punished with the Whip of Migration Sadness; the migrations I wrote a year ago should not suddenly start generating different columns when I run them today, compared to when I ran them originally a year ago.

Relevant: https://github.com/laravel/framework/pull/18001

**Comment by HiroKws** [comment]
Or simply add 'charset' and 'collate' for email and other indexed field.

'utf8mb4 for email address' is meaningless for me.

```
        Schema::create('users', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->string('email')
                ->unique()
                ->charset('latin1')
                ->collate('latin1_general_ci');
            $table->string('password')
                ->unique()
                ->charset('latin1')
                ->collate('latin1_general_ci');
            $table->timestamps();
            $table->rememberToken();
        });
```

```
    public function up()
    {
        Schema::create('password_resets', function (Blueprint $table) {
            $table->string('email')->index()
                ->charset('latin1')
                ->collate('latin1_general_ci');
            $table->string('token')->index()
                ->charset('latin1')
                ->collate('latin1_general_ci');
            $table->timestamp('created_at')->nullable();
        });
    }
```

```
    public function up(){
        Schema::create('jobs', function (Blueprint $table){
            $table->bigIncrements('id');
            $table->string('queue')
                ->charset('latin1')
                ->collate('latin1_general_ci');
            $table->longText('payload');
            $table->tinyInteger('attempts')->unsigned();
            $table->unsignedInteger('reserved_at')->nullable();
            $table->unsignedInteger('available_at');
            $table->unsignedInteger('created_at');

            $table->index(['queue', 'reserved_at']);
        });
    }
```

Mabey more...

**Comment by HiroKws** [comment]
Maybe...

```
$table->string('email')
                ->unique()
                ->charset('utf8')
                ->collate('utf8_general_ci');
```

When charset is UTF8, then it is possible to use 255 characters when put index.

**Comment by HiroKws** [comment]
Yes! It works well.

I think it is best solution now. Put `->charset('latin1')->collate('latin1_general_ci')` to email field when users table migrated.

**Comment by themsaid** [comment]
Feel free to open a PR, although I think you could just update the rules in your project.

**Comment by HiroKws** [comment]
No.

This is bug. 

When a user used an email address longer than 191 characters, db engine will make an error. Or will truncate mail address if set that behavior on to email field.

We are engineers, call this as "system  inconsistent". :)

Add more explains to official documents? Or correct migrations? Which is better for Laravel and Taylor??

**Comment by themsaid** [comment]
Can you open a PR with your proposed fix then?

**Comment by sisve** [comment]
Would a migration containing `->charset('latin1')->collate('latin1_general_ci')` work on non-mysql databases?
