### ISSUE TITLE
dd crash

### ISSUE THREAD

**Issue by kamil-kielczewski** [laravel/framework#18165]
- Laravel Version: 5.3.x
- PHP Version: 5.6
- Database Driver & Version: ?

### Description:
Calling below function fill crash dd command:

```
public function ddBug() {
        $sex = new stdClass;
        $sex->{"1"} = 'yes';
        $sex = (array) $sex;
        dd($sex);
    }
```

ErrorException in VarCloner.php line 74:
Undefined offset: 1

### Steps To Reproduce:
ddBug();

**Comment by GrahamCampbell** [comment]
Please report this to Symfony.
