### ISSUE TITLE
Validation: nullable overrides present and required_with rule

### ISSUE THREAD

**Issue by SchwarzOliver** [laravel/framework#18171]
(Laravel) Lumen Version: 5.4.4
- PHP Version: 7.0.14
- Database Driver & Version: MariaDB 10.1.21 

### Description:

My application runs with the Lumen framework.
I integrated both the TrimStrings and ConvertEmptyStringsToNull middlewares from Laravel 5.4 which is working fine so far.

I also followed the instructions noted here: https://laravel.com/docs/5.4/validation#a-note-on-optional-fields

The Validation now ignores following rules:

- present
- required_with

in the following example validation string:
`'items.*.attribute' => 'present|nullable|integer|required_with:items.*.otherAttribute'`

### Steps To Reproduce:

1. Controller function:

```
public function create(Request $request)
    {
        $this->validate(
            $request, [
                        'items.*.attribute' => 'present|integer|nullable|required_with:items.*.otherAttribute',
                        'items.*.otherAttribute' => 'present|integer|nullable|required_with:items.*.attribute'
                    ]
        );

        return $request;
}
```

2. JSON in POST Request:

```
{
  "items": [ 
    {
"attribute": "",
"otherAttribute": ""
    }
  ]
}
```

If you delete one of the attributes in the JSON, the validation still passes, so it ignores the present validation rule.

```
{
  "items": [ 
    {
"attribute": "2"
    }
  ]
}
```

If you enter a value in one of the fields, the other should be required to contain a value as well. But the validation still passes, if only one of the fields hold a value.

```
{
  "items": [ 
    {
"attribute": "2",
"otherAttribute": ""
    }
  ]
}
```

Please have a look at this.
Thank you.

**Comment by themsaid** [comment]
Thank you for reporting this, it was fixed in a recent commit :)

**Comment by SchwarzOliver** [comment]
Could you point me to the commit please?
I just updated the lumen framework to 5.4.5 and so far there is no difference.
