### ISSUE TITLE
Storage put times out when hosted on Docker

### ISSUE THREAD

**Issue by Vishal0203** [laravel/framework#18185]
- Laravel Version: 5.4
- PHP Version: 7.0
- Database Driver & Version: MySQL 5.7

### Description:
Laravel when hosted in docker, fails to upload files to s3 when using s3 as storage driver. It works fine when hosted outside docker. 

### Steps To Reproduce:
```
touch test.txt
php artisan tinker
use Storage;
Storage::put('test.txt', file_get_contents('text.txt'))

# times out
```

#### On local
<img width="1269" alt="screen shot 2017-03-02 at 5 15 48 pm" src="https://cloud.githubusercontent.com/assets/8856973/23506022/15da87b6-ff6c-11e6-829a-3e70ae084827.png">

#### On docker
hangs!
<img width="1268" alt="screen shot 2017-03-02 at 5 15 29 pm" src="https://cloud.githubusercontent.com/assets/8856973/23506032/207d99f6-ff6c-11e6-90eb-7173da47cf64.png">

**Comment by Vishal0203** [comment]
Anything on this? I'm using the same package suggested in laravel documentation.

**Comment by themsaid** [comment]
Closing since it doesn't seem laravel specific, please continue the discussions here https://github.com/thephpleague/flysystem-aws-s3-v3/issues/94

Hopefully you'll find a solution :)
