### ISSUE TITLE
emailOutputTo(x, true) sends email to '1'

### ISSUE THREAD

**Issue by bennoz** [laravel/framework#18189]
- Laravel Version: 5.4.*
- PHP Version: 7.1.0
- Database Driver & Version: SQLite 3.17

### Description:
When the method is called like `->emailOutputTo('admin@example.com', true)`  it will result in the following Exception:
```
  [Swift_RfcComplianceException]
  Address in mailbox given [1] does not comply with RFC 2822, 3.6.2.
```

I made a pull request [#18179](https://github.com/laravel/framework/pull/18179) to fix it, but apparently my proposed fix isn't in line with how it's meant to function.

### Steps To Reproduce:
Call `->emailOutputTo('admin@example.com', true)` .

**Comment by GrahamCampbell** [comment]
You need to write `['admin@example.com']` if you want to be able to use that second boolean parameter.
