### ISSUE TITLE
Can't run test when mocking events due to missing class

### ISSUE THREAD

**Issue by clearlymedia** [laravel/framework#18192]
- Laravel Version: 5.4.
- PHP Version: 7.0.15
- Database Driver & Version: Latest Homestead version

### Description:

I cannot run a PHPUnit unit test due to a missing class error. I traced it back to there not being a `PHPUnit_Framework_Assert` class for the `EventFake.php` file to refer to.

### Steps To Reproduce:

Use `Event::assertDispatched()` in a unit test.

### Possible Fix

I was able to get around this, by rename the class in `EventFake.php` to `PHPUnit\Framework\Assert` as this is the actual class an namespace.

**Comment by clearlymedia** [comment]
If this can be verified, I don't mind doing a pull request.

**Comment by themsaid** [comment]
Please run composer update and clear the cache.
