### ISSUE TITLE
"<?php" prints before each request when adding an empty routes file with only the open php block

### ISSUE THREAD

**Issue by filljoyner** [laravel/framework#18190]
- Laravel Version: 5.4
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7.17

### Description:
Sorry if this isn't the proper place to put this. My bad!

When adding and including new routes file in the /routes directory, if the file opens a php block ("<?php" but does not contain anything after the opening tag (no routes, comments, characters, etc), then "<?php" will be sent along with all requests (in the console, visiting a url and looking at the source, etc).

### Steps To Reproduce:
On a clean version of Laravel, add a new routes file and add only the opening "<?php" block. No extra lines or spaces:

/routes/client_credentials.php
```php
<?php
```

Next add the new route file to the routes service provider. This is abbreviated to show only the method for map and the method adding new routes.

/app/Providers/RouteServiceProvider.php
```php
<?php

class RouteServiceProvider extends ServiceProvider
{

    // existing map method
    public function map()
    {
        $this->mapApiRoutes();

        $this->mapWebRoutes();
    
        // ref new method for adding client credentials
        $this->mapClientCredentialRoutes();
    }

    // new client credentials method
    protected function mapClientCredentialRoutes()
    {
        Route::prefix('api')
            ->middleware('client_credentials')
            ->namespace($this->namespace)
            ->group(base_path('routes/client_credentials.php'));
    }
}
```

Visit the homepage, view source and you'll see "<?php" before the HTML prints out.

**Comment by stefanoruth** [comment]
You need to add a new line after the <?php

**Comment by devcircus** [comment]
yes, from the PHP docs:
>>In PHP 5.2 and earlier, the parser does not allow the <?php opening tag to be the only thing in a file. This is allowed as of PHP 5.3 **provided there are one or more whitespace characters after the opening tag**.

**Comment by filljoyner** [comment]
Thanks response and link to the PHP docs. I didn't know that was a feature ;) in the language. Thanks again!
