### ISSUE TITLE
Handle deadlocks in laravel 4.2

### ISSUE THREAD

**Issue by warroyo** [laravel/framework#18191]
- Laravel Version: 4.2.22
- PHP Version: 5.6
- Database Driver & Version: Mariadb galera cluster

### Description:

I have run into an scenario where a PDO exception is thrown `PDOException: SQLSTATE[HY000]: General error: 1180 Got error 35 "Resource deadlock avoided" during COMMIT` 

it looks like this has been addressed in laravel 5.1 (https://github.com/laravel/framework/pull/12814/files) however one of my projects is stuck on 4.2 . Is there a fix that I could implement  for this in 4.2 ?  I noticed in 4.2 the retry logic only checks for one string(https://github.com/laravel/framework/blob/4.2/src/Illuminate/Database/Connection.php#L670) 

I have attempted to extend the `Connection` class using this tutorial http://blog.stidges.com/post/extending-the-connection-class-in-laravel. However whenever the `reconnect` function is run the new Database connection object that is returned has a `null` value for the PDO object which causing all further queries to fail. Any idea what could be going on here? 

or is there any way these extra strings could be backfilled into 4.2?

**Comment by GrahamCampbell** [comment]
Sorry, laravel 4.2 is not supported anymore.
