### ISSUE TITLE
It seams i cannot use $tries and $timeout properties on my queued listener class?

### ISSUE THREAD

**Issue by peyobr** [laravel/framework#18199]
- Laravel Version: 5.4.15
- PHP Version: 7.0
- Database Driver & Version: yajra/laravel-pdo-via-oci8
- Queue Driver: Beanstalkd

### Description:

It seams i cannot use $tries and $timeout properties on my queued listener class?

I'm doing something wrong?

Thank you.

peyobr

**Comment by sisve** [comment]
We're missing steps to reproduce and an actual error description. Do you get an error message?

**Comment by peyobr** [comment]
Hi, no error message. Simply:

1) generate an event-listener pair
2) add ShouldQueue  interface on listener
3) add $tries and $timeout properties on listener
4) fire the event with the event() helper

Inspect queued listener using beanstalkd conole and you'll notice that 'timeout' and 'maxTries' are stored as null.

If i use queued Job instead everything is ok!

Thanks.

**Comment by sisve** [comment]
I see nothing in the code that states that events should support $tries or $timeout. Reference: https://github.com/laravel/framework/blob/35f0bb188479e469c86326ae269a2965d2f2f73a/src/Illuminate/Events/Dispatcher.php#L434-L462

Are you saying that something in the docs says they should; or are you asking for a new feature?

**Comment by peyobr** [comment]
You are right. I have assumed that new granular approach would be available in listener too.

I hope this will be in the near future!

Thank you!

**Comment by themsaid** [comment]
Just submitted a PR that should add the functionality https://github.com/laravel/framework/pull/18375

**Comment by peyobr** [comment]
Thank you 1K!

**Comment by bmchan81** [comment]
Hi,
The changes for #18375 was overwritten and is lost in the succeeding commits. 
For your info.
