### ISSUE TITLE
 Unable to access web application rest service from ionic app

### ISSUE THREAD

**Issue by kalyankumars07** [laravel/framework#18194]
Getting preflight issue, when accessing a php web app rest service using http.post from ionic app, but http.post is working from postman client. http.get is working from ionic app. Please help me to figure out the issue.

Please find the console error.

> XMLHttpRequest cannot load https://domain/api/vehicle. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access.

My back end API application is laravel. Which is hosted in Heroku server. http.get is returns the response properly.

**Comment by GrahamCampbell** [comment]
Please ask on the fourms.
