### ISSUE TITLE
Request json() inconsistencies with scalar values like false, true and null

### ISSUE THREAD

**Issue by Blizzke** [laravel/framework#18193]
- Laravel Version: 5.4.8
- PHP Version: 7.1.1

PHPs `json_decode()` decodes keywords like "true", "false" and "null" into `true`, `false` and `null`. 

The creating of the json ParameterBag simply casts the decode result into an array
(`$this->json = new ParameterBag((array) json_decode($this->getContent(), true));`), which produces some inconsistent results:

<img width="367" alt="screen shot 2017-03-03 at 09 46 17" src="https://cloud.githubusercontent.com/assets/231572/23544204/4a1c5204-fff6-11e6-8d0a-d1dd0ab73db1.png">

As you can see, both "true" and "false" result in a "json request" while "null" does not (even though it should if we want consistency). 

So either all should yield json parameters, or none of them should (which is my personal preference)

**Comment by themsaid** [comment]
What's the issue that you're trying to fix? can you share a use case?

**Comment by Blizzke** [comment]
I've encountered it with API functionality to save frontend user settings. 
I was initially just saving flags (true/false - the name of the flag is specified in the URL). The backend used the json parameterbag (as in take the first value out of it). Later on simple text values were added and that didn't work with the existing code. Took be a bit to figure out the difference.

It's not an issue per sé if you are aware of the difference in behavior, but I can imagine it being confusing in some cases. 
The `null` not resulting in json data is a bug imo, especially if laravel wants to follow the `json_decode`-behavior

**Comment by themsaid** [comment]
If the payload is not JSON why would you use `request()->json()` in the first place?

**Comment by themsaid** [comment]
'true', 'false', 'null' are strings.

**Comment by Blizzke** [comment]
Which is my initial point, so I can pretty much bounce the ball back in your direction: If `true`, `false` and `null` are to be considered strings, there should be no available data returned when `json()` is called. That makes it a bug.

For someone trying to automate detection between "was it a json object" that was posted or a regular value, this causes weird failures if they simply base themselves on the count() of that parameter bag.

**Comment by themsaid** [comment]
I see your point now, I agree that it shouldn't return anything if the payload is not a JSON structure. Sorry it took me a while to get it :)

**Comment by passionInfinite** [comment]
@Blizzke Unable to reproduce what you are saying. I have checked with postman using JSON as application/content and also with form-data. Parameter bag returns all the parameters whether it is null, true or false.

Using Form-Data:

![form-data](https://user-images.githubusercontent.com/16861318/28015995-2b2e8038-6590-11e7-943f-a3d04dd67cd6.png)

Using as form-urlencode-data

![form-urlencode](https://user-images.githubusercontent.com/16861318/28016016-361fa62a-6590-11e7-9cad-c63756f49d06.png)

Using as JSON-data:

![json-data](https://user-images.githubusercontent.com/16861318/28016029-4098e0b2-6590-11e7-815d-1a0a09f6f7f0.png)

**Comment by morloderex** [comment]
@passionInfinite I guess he is only sending a single value like false. Not all of them as an object. Like you do.

**Comment by Blizzke** [comment]
The entire idea is that there is no returning of json data at all, just a string (as @morloderex already concluded). That resulting in a the json attribute being filled in is an error, it isn't json.
