### ISSUE TITLE
Models should be updated when their relations are changed

### ISSUE THREAD

**Issue by Ettapp** [laravel/framework#18207]
- Laravel Version: 5.3.30
- PHP Version: 7.1.2

### Description:
When updating relations of a model, neither the model or the related models are updated.
I saw [here](https://github.com/laravel/framework/issues/13133) that it wasn't considered as a bug and I dont understand with (see below)...

### Steps To Reproduce:
`$a = ModelA::create(['stuff']);
$b = $a->relationWithB()->create(['stuff']);

// Why this act like this ?!
$a->relationWithB;// the related 'b' isn't there
$b->relationWithA;// the related 'a' isn't there`

**Comment by GrahamCampbell** [comment]
I don't think this is a bug. Thanks though. Feel free to discuss on the forums though.

**Comment by KFan95** [comment]
@GrahamCampbell Why it isn't a bug?
