### ISSUE TITLE
Weird behaviour of Connection class

### ISSUE THREAD

**Issue by vikkio88** [laravel/framework#18209]
- Laravel Version: >4.x.x
- PHP Version: >5.6
- Database Driver & Version: does not matter

### Description:
I am using the standalone Eloquent in one small project, and to re-use the same db connection configuration I used ```Connection::getConfig($option)``` method (https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Connection.php#L963), passing a void instead of the $option.
And it returned the whole config array (which is what I originally wanted to be honest), but if you put the errors on you will get some warnings related to the call this object does to ```Arr::get()``` method, since ```$key``` is null.
Is this a wanted behaviour? 
I was thinking to open a PR to change this piece of code to be a avoid throwing errors, something like:

```php
    public function getConfig($option = null)
    {
       if (empty($option)){
           return $this->config;
       }
        return Arr::get($this->config, $option);
    }
```
Can I do that? Or would be better to create another getter
```php
    public function getConfigs()
    {
        return $this->config;
    }
```

### Steps To Reproduce:
Just call this method without parameter
```php
$dbConfig = Capsule::connection()->getConfig();
```

```$dbConfig``` will have your config array, but some errors related to the way ```Arr::get``` handles the null value of key will be thrown

**Comment by ntzm** [comment]
What warnings are you getting? If you are passing `null` to `getConfig` it shouldn't even get to `Arr::get`

**Comment by vikkio88** [comment]
I am getting "wrong argument number" warning not passing any, but I get the whole configuration, or if I pass null I don't get the warning and I still get all the configuration array. 
I was just wondering if this behaviour was normal or not, it is useful for me, but probably for consistency would be better to create a ```getConfigs()``` method?

**Comment by themsaid** [comment]
Sorry but Laravel 4 is not supported anymore, please use the forums to post such questions.

**Comment by vikkio88** [comment]
@themsaid wasnt really about laravel 4, I am using 5.3, I was reporting that this weird behaviour is happening since laravel 4.*
