### ISSUE TITLE
Unespected behavior when saving entity through relationship

### ISSUE THREAD

**Issue by diegopso** [laravel/framework#18219]
- Laravel Version: 5.2.*
- PHP Version: 7
- Database Driver & Version: pgsql 9.6

### Description:

I overrided the method save for all my entity models, I have a `BaseEntity` class that extends `\Illuminate\Database\Eloquent\Model` and is extended by all my entities. However, when saving some objects through a relationship I realized they are not passing in my method, but instead they are going to the original `\Illuminate\Database\Eloquent\Model` method. It's been caused probably by this line in the src, that forces my object to become an instance of `\Illuminate\Database\Eloquent\Model`.

https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/Relations/BelongsToMany.php#L599

This way I can only override some of the save calls, but not all. Is this an expected behavior? I checked and the line has not changed in the latest versions too.

### Steps To Reproduce:

Create an entity that extends `\Illuminate\Database\Eloquent\Model`, lets say `\App\Entity\Role`.
Override the method save and ad some logic there, in my case I was using it to log purpouses.
Try to create an entity via a relationship, like:

    $user->roles()->create($role);

The method called to save the `$role` is `\Illuminate\Database\Eloquent\Model::save` and not `\App\Entity\Role::save`.

### Obs:

Something simillar happens when you use Observers. I tried it first and faced this issue, then I changed to the approach of overriding. I did not check deeply what happens with the observers, but the events are not triggered if you are creating entities via relatioships.

**Comment by themsaid** [comment]
5.2 is not supported anymore, please upgrade and open a new issue if the problem still exists in a most recent version.
