### ISSUE TITLE
Global scoping users with data from the authenticated user crashes server

### ISSUE THREAD

**Issue by lasseal** [laravel/framework#18218]
- Laravel Version: 5.4.15
- PHP Version: 7.1.2
- Database Driver & Version: MariaDb 10.1.21

### Description:
Creating a global scope on the `User` model requiring data from the currently authenticated user crashes the web server (white screen of death due to reached memory limit).

### Steps To Reproduce:

Add anonymous global scope to the `User` model requiring data from the authenticated user.

```
    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope('tenant', function (Builder $builder) {
            if (auth()->check()) {
                $builder->whereTenantId(auth()->user()->tenant_id);
            }
        });
    }
```

Try to view any page in a browser.

**Comment by devcircus** [comment]
Seems like the logic here is flawed. Since a global scope is applied to every query, you're creating an infinite loop by querying within the scope definition.

**Comment by lasseal** [comment]
Ahh off course, you're right. Would this mean it's impossible to perform this kind of scoping at all, or am I just placing the logic in the wrong location?

**Comment by devcircus** [comment]
is it possible to pull the info related to querying the user out of the scope and maybe pass it in as a parameter? Check stackoverflow.com or Google tenant global scope in laravel and there should be some good info available

**Comment by eumanito** [comment]
I have this problem too, did someone solved it?

**Comment by eumanito** [comment]
I was able to solve it by creating a new module that extends from User module:
`<?php

namespace App;

class NewUser extends User
{
    protected $table = 'user';
    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope('tenant', function (Builder $builder) {
           if(Auth::check()){
                $builder->where('tenant_id', Auth::user()->tenant_id);
            }
        });
    }`
Use NewUser to work with data (list, write and delete), but use the User module for authentication.

**Comment by EmilMoe** [comment]
@eumanito  then you could just have used a local scope?

**Comment by rs-sliske** [comment]
@EmilMoe 
local scopes have to be explicitly used on every query.

that example would apply the condition to every query as long as there is a logged in user, which for single database multi-tennant applications is closer to the desired situation.

personally i implemented something like this recently, however i used the url to identify the tennant, rather than the authenticated user, and then had a global scope which checked if that was set

**Comment by lizeshakya** [comment]
Are there any other alternatives to implement the scope of auth()->user()->id inside User model besides creating a NewModel?

**Comment by lasseeee** [comment]
I ended up using the url to identify the tenant, and global query `where` with that as the parameter, much like @rs-sliske did.
