### ISSUE TITLE
Pusher : Couldn't get auth info from your webapp : 403

### ISSUE THREAD

**Issue by DeadMoras** [laravel/framework#18214]
- Laravel Version: 5.4
- PHP Version: 7.1
- Database Driver & Version mysql & 5.7:

### Description:
I'm use broadcasting with vue.
When i send request i have error (first request only, later i have no errors and data):
Pusher : Couldn't get auth info from your webapp : 403
And HttpException in RedisBroadcaster.php line 49: 

I use only api, me dont need check user on auth and... how i can solve this problem?

**Comment by derslo** [comment]
And what was your solution? I'm struggling at the same point...

**Comment by krisnaw** [comment]
Hi, any update about this? I'm having the same problem after upgrading to Laravel 5.4 from Laravel 5.2.

**Comment by iadambrown** [comment]
In my case, I was running an identical comparison on my arguments, but $teamId was coming in as a string

```
Broadcast::channel('chat-room.{teamId}', function ($user, $teamId) {
    if ($user->team_id === $teamId) {
        return $user;
    }

    return null;
});
```

I'm not sure when it started coming in as a string, as that code hasn't changed in months.

Anyways, type casting it seems to have worked, though I'm wondering if there's a better place to fix the issue...
`if ((int) $user->team_id === (int) $teamId) { ... }`

This also seems to stop the error, but I haven't really looked into it - I wanted to fix my existing code first:
https://laracasts.com/discuss/channels/laravel/pusher-couldnt-get-auth-info-from-your-webapp-403/replies/338696
