### ISSUE TITLE
Validator required_with bug

### ISSUE THREAD

**Issue by LuttyYang** [laravel/framework#18224]
- Laravel Version: 5.4
- PHP Version: any
- Database Driver & Version: any

### Description:
required_with means `The field under validation must be present and not empty only if any of the other specified fields are present.`

but this code is failed
```
	$v = Validator::make([
		'test2' => null,
	], [
		'test1' => 'sometimes|string',
		'test2' => 'required_with:test1|string',
	]);

	if ($v->fails()){
		dd($v->failed());
	}
```

**Comment by themsaid** [comment]
`null` is not a `string`, that's why it fails.

**Comment by LuttyYang** [comment]
@themsaid  but the test1 is not exists, so test2 is not need verification

**Comment by themsaid** [comment]
They are completely two different rules :) check this post: http://themsaid.com/laravel-advanced-validation-conditionally-adding-rules-20170110/

**Comment by LuttyYang** [comment]
@themsaid ok, thanks
