### ISSUE TITLE
No error, just a thank you

### ISSUE THREAD

**Issue by Thorazine** [laravel/framework#18225]
- Laravel Version: any
- PHP Version: any
- Database Driver & Version: any

### Description:
Thank you

### Steps To Reproduce:
I don't know if this is the proper way to thank you, but as you can can see I'm doing it anyways.
I have been coding for years in PHP now, but there was a time I started to hate PHP in particular. Luckily I was introduced to Laravel which brought back the love for me again. 

But the trade off for that love is your work and dedication: Uncountable hours, the shit you get from the ones you try to help, the general issues you guys (and girls) solve to make everybody's day a lot easier. And I believe there is to little recognition for that. So for once I thought I'd just send in a big nice thank you in the middle of your daily ticket grind, hoping to make your day a bit better like you do mine everyday.

# Thank you!
I can honestly say you make a massive positive difference in my life each day just by (I hope) doing what you love.
Just wanted to let you know your work is more than appreciated.

**Comment by GrahamCampbell** [comment]
Thanks. :)

**Comment by joshmanders** [comment]
👍  here too, I left PHP 2 years ago for Node, and recently came back purely because of Laravel and the work put into it. Thanks!

**Comment by GrahamCampbell** [comment]
🚀
