### ISSUE TITLE
Failed retrieve pivot field values after model update

### ISSUE THREAD

**Issue by ppalmeida** [laravel/framework#18228]
- Laravel Version: 5.4.15
- PHP Version: 7.0.8
- Database Driver & Version: MySQL 5.6.25

### Description:
In a relationship many-to-many: if there is a column in the pivot table, the values of the model are not udpated after "save()" method is called.

### Steps To Reproduce:

I have three tables in my system: procedures, scripts, procedure_scripts. A "procedure" is made by many "scripts". Each "script" can be attached/associated to many "procedures". So, it is a "many to many" relationship. So, procedure_script is the pivot table. 

Tables are something like this:

procedures table:
id (primary)
title (varchar)
etc

scripts table:
id (primary)
title (varchar)
etc

procedure_script table:
id (primary)
procedure_id (foreign key to procedures.id)
script_id (foreign key to scripts.id)
sequence (int 10 unsigned)

In pivot table, I have that extra column, "sequence". It is used to save the ordering of the attached scripts.

So:
```php
// \App\Script.php

// Procedure relationship:
public function procedures() {
    return $this->belongsToMany('\App\Procedures')->withPivot('sequence')->orderBy('sequence');
}
```

```php
// \App\Procedure.php

// Scritps relationship:
public function scripts() {
	return $this->belongsToMany('\App\Script', 'procedure_script')->withPivot('sequence')->orderBy('sequence');
}

// Update method:
public function updateOrNew($fields, $id = NULL) {
    $procedure = ($id == NULL) ? new Procedure() : Procedure::find($id);
    // (....) other stuffs like $procedure->fill($fields) to simple fields like title, description,etc...

    // Now the scripts update:
    $fields["scripts"] = isset($fields["scripts"]) ? $fields["scripts"] : [];
    $procedure->scripts()->sync($fields["scripts"]);

    // Ordering Scripts: looking in the DB, it is perfect. "sequence" column is well filled up
    $procedure->scripts->each(function($sc, $i) use(&$procedure, &$fields) {
        $procedure->scripts()->updateExistingPivot(
            $sc->id,
                [
                    "sequence" => array_search($sc->id, $fields["scripts"])
                ]
        );
    });

    $procedure->save();

    // Here it is!! IF I just return $procedure, then $procedure->scritps->pivot->sequence will all be 0, (zero integer), despite the ordering udpate above.
    // return $procedure; // -> this is buggy, all "sequence" fields returns with "0" values

    // OR
    
   // So, to update my model, I need to look for it again like so:
   return Procedure::find($procedure->id); // -> this is correct: the "sequece" from pivot table are ok, but should it be necessary query DB again?
}
```

So: after update the "sequence" in my pivot table, I can only see the "sequence" column udpated when I "find" my model again. Should it not be available and updated right after the "save()" method?

Here are the results from my integration tests with and without the last "Procedure::find" retrieve:

```php
// TestProcedure.php
public function test_create_procedure() {
    $scripts = factory(Script::class, 5)->create(); // create 5 scripts, ids from 1 to 5
    $categories = factory(Category::class, 3)->create();
    $keywords = factory(Keyword::class, 4)->create();

    $data = [
        "title" => "Título do Procedimento",
        "preview_token" => NULL,
        "description_raw" => "Descrição do Procedimento",
        "description_html" =>"<div><h1>Descrição do Procedimento<h1></div>",
        "isPublished" => 1,
        "categories" => $categories->pluck('id')->toArray(),
        "scripts" => [4,3,2,1,5], // attach these scripts by ID, sorting them as IDs [4, 3, 2, 1, 5]
        "keywords" => $keywords->pluck('id')->toArray(),
        "operations" => [1, 2, 3],
        "products" => [4, 5, 6],
    ];
    $procedure = new Procedure();
    $p = $procedure->updateOrNew($data);

    $r = $p->scripts->pluck('id')->toArray();

    $this->assertEquals([4,3,2,1,5], $r);

    $this->assertEquals($p->title, $data["title"]);
    $this->assertEquals($p->isPublished, $data["isPublished"]);
    $this->assertEquals($p->categories()->first()->name, $categories[0]->name);

    $this->assertEquals(4, $p->keywords()->count());
    $this->assertEquals(3, $p->operations()->count());
    $this->assertEquals(3, $p->products()->count());
}
```

With ```return $procedure``` it traces back like this:

<img width="407" alt="screen shot 2017-03-06 at 14 44 25" src="https://cloud.githubusercontent.com/assets/197936/23622083/f7477148-027b-11e7-83a8-587ce1fcc694.png">

BUT, if in Procedure.php I do the find... like I said before:  ```return Procedure::find($procedure->id);``` the test will pass.

Should not the Model updates itself after a ```"$procedure->save()"``` call? And the ```$procedure->scripts``` accessor should not return the "pivot sequence" field updated also?

**Comment by marconi1992** [comment]
I think the problem is the test, in the method updateOrNew you load the relation in the line

```php
$procedure->scripts->each(function($sc, $i) use(&$procedure, &$fields) {
        $procedure->scripts()->updateExistingPivot(
            $sc->id,
                [
                    "sequence" => array_search($sc->id, $fields["scripts"])
                ]
        );
    });
```
Therefore in the current Procedure instance the relation is loaded, then in the test you get the ids using the next sentence,
```php
 $r = $p->scripts->pluck('id')->toArray();
````
So that you're assert the old records when the lazing loading was called the first time, then you need to reload the scripts relation

```php
 $r = $p->scripts()->get()->pluck('id')->toArray();
````
