### ISSUE TITLE
Where clause seemingly ignored on relation

### ISSUE THREAD

**Issue by samcambridge** [laravel/framework#18226]
- Laravel Version: 5.1.16 / 5.3.30
- PHP Version: 7
- Database Driver & Version: 10.1.19-MariaDB Homebrew, MySQL

### Description:

I added some where clauses to my User model relationship:

```php
$this->hasMany(Credit::class)->where("expires_at", "=", null)->orWhere("expires_at", ">=", $date)
```

I noticed that this started brining back credit records that didn't belong to the user, a credit has a status, if I then added an extra where clause on to find credits of a specific status:

```php
$credits = $user->credits()->where("status", "=", "available")
```

`$credits` would have instances of the Credit model where the status was different to that of the where clause

### Steps To Reproduce:
model Credit belongs to User
model User has many credits

And the above where/orWhere clause to the model, subsequent where clauses have no effect.

Please note, changing the model relationship where to be:

```php
return $this->hasMany('Quuu\Credit')
    ->where(function($query) {
      $query->where("expires_at", "=", null)
      ->orWhere("expires_at", ">=", \Carbon\Carbon::today());
    });
```

seems to fix the issue, but it seems like an easy trap to fall in and it's super confusing as to why the secondary where clause of status took no effect, is this an issue or my understanding of the way laravel retrieves records?

**Comment by themsaid** [comment]
Yes you need to use closure to add extra OR conditions or you'll end up having records wher eonly the conditions after OR applied.

**Comment by samcambridge** [comment]
@themsaid thanks for that, I noticed and fixed the issue... shouldn't other where conditions added after the query had been built restrict it further though?
