### ISSUE TITLE
How to define session with multi auth

### ISSUE THREAD

**Issue by SieuNT** [laravel/framework#18222]
- Laravel Version: 5.4
- PHP Version: 7.0
- Database Driver & Version: MySQL 5.7

### Description:

I use multi auth. I login /admin and /home then logout one in two. It logout both.

I want config /admin - 1 session and /home - 1 another session.

**Comment by alexsoft** [comment]
@SieuNT I think this is because default out-of-box logout method regenerates session id and that's why you are logged out in all guards. https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/Auth/AuthenticatesUsers.php#L159

**Comment by cjaoude** [comment]
maybe it's just me, but seems odd to be logged in to both in the first place. kind of defeats the point. use roles/privileges instead if that is the case

**Comment by alexsoft** [comment]
@cjaoude I don't. For example in one of my projects I use a second guard for reserving my personal account while I'm impersonating other user. Very handy, I think

**Comment by Fenzland** [comment]
I think to regenerate session when logout is a bad design. For session guards, it cause 'logout one, logout all' bug. For other guards, we don't need do anything with session when logout.
