### ISSUE TITLE
Route forgetParameter isn't working

### ISSUE THREAD

**Issue by fernandobandeira** [laravel/framework#18232]
- Laravel Version: 5.4.15
- PHP Version: 7.0.15
- Database Driver & Version: Mysql 5.7

### Description:
Currently the function forgetParameter from the Route isn't working.

### Steps To Reproduce:
Create a route, for example:
```php
Route::group(['domain' => '{subdomain}.myapp.com'], function () {
    Route::get('user/{id}', function ($account, $id) {
        //
    });
});
```

Create a middleware and apply to this route, on the handle of the middleware try to use:
```php
$route = $request->route();
$route->forgetParameter('subdomain');
```

An exception will be thrown:
```
ReflectionException
Internal error: Failed to retrieve the default value
```

[Line that raises the exception](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Routing/RouteDependencyResolverTrait.php#L57)

Edit:
This is a fresh install of Laravel 5.4, also it throws this exception after the middleware returns the next request, before hitting the action on a controller...

**Comment by floreean** [comment]
I have the same problem. How did you solve it?

**Comment by fernandobandeira** [comment]
I've refactored my middlewares, and cleaned up them, after that I couldn't reproduce it anymore, it's working now...

If you can find a way to reproduce it you can open an issue about it...
