### ISSUE TITLE
Validation requests not using "replaced" data

### ISSUE THREAD

**Issue by nathanpurcell** [laravel/framework#18239]
- Laravel Version: 5.3
- PHP Version: 7

### Description:
When attempting to sanitize input as per [this article](http://www.easylaravelbook.com/blog/2015/03/31/sanitizing-input-using-laravel-5-form-requests/), it does not appear that the new replaced data is being passed. 

#### Background
I've got a standard Form Validation Request running when storing a Project model.   
The Project model requires the user to enter a numeric value - decimals are not important.  
There is a small JS function running to format the entered data with commas as the user types.  
So if you typed in "15000000" the string would be formatted as "15,000,000".   
The form validation for this field states the value much be `numeric`.  
If you submitted the `value` with commas, the validation would fail - this is expected and understandable. 

### Steps To Reproduce:
*Request class*: 
```
<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class StoreProjectRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $this->sanitize();
        
        return [
            'value' => 'required|numeric', 
        ];
    }
    
    private function sanitize()
    {
        $input = $this->all();
        
        // float only
        $input['value'] = filter_var($input['value'], FILTER_SANITIZE_NUMBER_FLOAT);
        
        $this->replace( $input );
    }
}

```

If you dump before and after the call to sanitize() you can see the `value` field is being formatted, replace and returned as expected.  
The data is then passed to the Validator and if you dump the `$value` attribute on `Illuminate\Validation\Validator@validateNumeric` you can see it is in fact the *original* value being passed, not the sanitized version that was meant to be replaced.  

This causes the validator to fail where it should not.  
I couldn't find where, but it appears that the Validator class is simply receiving the original POST data.

**Comment by devcircus** [comment]
Looking through the parent FormRequest class, it looks like the input is passed to the validator before the 'rules' method gets called, so anything you do to change the input inside the 'rules' method, will be ignored. It does appear, however, that you can define a 'validator' method in your CustomFormRequest class, and manipulate your input there. e.g.:
```
    public function validator(ValidationFactory $factory)
    {
        $input = $this->all();
        $input['value'] = filter_var($input['value'], FILTER_SANITIZE_NUMBER_FLOAT);
        $this->replace($input);

        return $factory->make(
            $this->all(), $this->container->call([$this, 'rules']),
            $this->messages(), $this->attributes()
        );
    }
```
at the top of your CustomFormRequest class, be sure to add:
```
use Illuminate\Contracts\Validation\Factory as ValidationFactory;
```
now, you can leave your 'rules' method untouched. 
I believe there were some changes to Form Requests between when the tutorial was released and the current version. So the tutorial was probably valid at some point.
