### ISSUE TITLE
Could not establish Memcached connection

### ISSUE THREAD

**Issue by demonhunterunderdarkness** [laravel/framework#18233]
- Laravel Version: 5.0.32
- PHP Version:5.4.39-0+deb7u2
- Database Driver & Version:mysql  Ver 14.14 Distrib 5.5.31
- Server&Version :Debian:7.1.
-memcached:1.4.13-0.2
-php5-memcached:2.0.1-6
### Description:
My application log offen catches exception 'RuntimeException' with message 'Could not establish Memcached connection.'
There is "memcached is running" after execute "service memcached status" command.
please give me a favor, thanks in advance~

**Comment by demonhunterunderdarkness** [comment]
missed some infos
I have two servers where my project is running on.
on server is ubuntu and has memcached:2.1.0 installed
the second is debian and has memcached:2.0.1 installed.
is versions conflicted?

**Comment by themsaid** [comment]
Please ask on the forums, we try to keep this repo for bug reporting only.

Thanks
