### ISSUE TITLE
Possible bug with @includeWhen

### ISSUE THREAD

**Issue by kevinkhill** [laravel/framework#18231]
- Laravel Version: 5.4.15
- PHP Version: 7.1.1 with Xdebug 2.5.1
- Database Driver & Version: _N/A_

### Description:
Parse error: syntax error, unexpected ','

### Steps To Reproduce:
I added this statement to my view:
```
@includeWhen($product->isCategorized, 'shared.panels.footer-category-crumbs', ['product' => $product])
```
which compiles to:
```
<?php if ($product->isCategorized, 'shared.panels.footer-category-crumbs') echo $__env->make(['product' => $product], array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>
```

I can see that the expression is being split at the wrong comma.

### Desired output
```
<?php if ($product->isCategorized) echo $__env->make('shared.panels.footer-category-crumbs', ['product' => $product], array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>
```
When I put the above corrected line in the compiled view, it works.

### To wrap up my findings...
Would this be a better regex to use? (probably not, I hack away at them until they work)

```/^([^,]+)\s?,\s?(.*)$/is```

This way the expression is split at the first comma, and the correct line of compiled output is produced.

**Comment by kevinkhill** [comment]
If I am way off base and missing something obvious, please let me know as sometimes I get code blind over otherwise glaring issues.

**Comment by devcircus** [comment]
Looks like a similar issue was reported a few days ago. #18195

**Comment by themsaid** [comment]
Thanks, a fix was submitted here: https://github.com/laravel/framework/pull/18285
