### ISSUE TITLE
cannot prevent sending email in Illuminate\Mail\Events\MessageSending listener.

### ISSUE THREAD

**Issue by bubasuma** [laravel/framework#18244]
I cannot prevent sending email in **Illuminate\Mail\Events\MessageSending** listener. But I can prevent sending notification in **Illuminate\Notifications\Events\NotificationSending** listener.
<img width="756" alt="screen shot 2017-03-07 at 7 14 55 pm" src="https://cloud.githubusercontent.com/assets/8973208/23669115/d3e6834c-036b-11e7-9b52-4d5054406b58.png">
<img width="592" alt="screen shot 2017-03-07 at 7 15 07 pm" src="https://cloud.githubusercontent.com/assets/8973208/23669116/d410f49c-036b-11e7-827e-5174cc699443.png">

I also suggest to add events like **Illuminate\Mail\Events\MessageSent** and **Illuminate\Mail\Events\MessageFailed** like it is for **Notifications**

thanks.

**Comment by themsaid** [comment]
Thank you, opened a PR for that: https://github.com/laravel/framework/pull/18245
