### ISSUE TITLE
Can't attach PDF file via attchData() in notification

### ISSUE THREAD

**Issue by adam-boduch** [laravel/framework#18240]
- Laravel Version: 5.4.15
- PHP Version: 7.0.15

### Description:

Ąttaching PDF file content via `attachData()` throws `InvalidPayloadException` in file `Illuminate\Queue\InvalidPayloadException` (line 89).

To be specific in `createPayload()` method:

```php
    protected function createPayload($job, $data = '', $queue = null)
    {
        $payload = json_encode($this->createPayloadArray($job, $data, $queue));

        if (JSON_ERROR_NONE !== json_last_error()) {
            throw new InvalidPayloadException;
        }

        return $payload;
    }
```

`json_last_error()` returns `5` which means *Malformed UTF-8 characters, possibly incorrectly encoded*.

### Steps To Reproduce:

1. Create simple notification class:

```php
<?php

namespace App\Notifications;

use Illuminate\Notifications\Notification;
use Illuminate\Notifications\Messages\MailMessage;
use Mpdf\Mpdf;

class PdfNotification extends Notification
{
    /**
     * Get the notification's delivery channels.
     *
     * @param  mixed  $notifiable
     * @return array
     */
    public function via($notifiable)
    {
        return ['mail'];
    }

    /**
     * Get the mail representation of the notification.
     *
     * @param  mixed  $notifiable
     * @return \Illuminate\Notifications\Messages\MailMessage
     */
    public function toMail($notifiable)
    {
        $mpdf = new Mpdf();
        $mpdf->WriteHTML('My first PDF');

        $data = $mpdf->Output('', 'S');

        return (new MailMessage)
            ->line('Hello.')
            ->attachData($data, 'test.pdf', [
                'mime' => 'application/pdf',
            ]);
    }
}
```

(keep in mind I DO NOT implement `ShouldQueue` interface). 

2. `$user->notify(new PdfNotification());` (`$user` is instance of `User` model).

**Comment by themsaid** [comment]
Method `createPayload` is never called unless you queue a job, moreover you generate and attach the file in a method, which means it's not serialized, the method is called after the class is unserialized.

Looks like something else in your code is causing the error.

**Comment by adam-boduch** [comment]
You're right. I feel stupid ;)

**Comment by ArondeParon** [comment]
@adam-boduch what was actually causing this issue? I'm experiencing the same thing right now.
