### ISSUE TITLE
Can't get replaced input with "only" method

### ISSUE THREAD

**Issue by olcaytanrikulu** [laravel/framework#18254]
- Laravel Version: 5.3.30
- PHP Version: 5.6.4
- Database Driver & Version: MySQL & MariaDB 10.1.17 

### Description:
When trying to get replaced input with $request->only() method it returns the original value.

### Steps To Reproduce:
In form request.
```
public function all()
{
        $input = parent::all();
        $input['birthday'] = 'Replaced Value';       
        $this->replace($input);
        return parent::all();
}
```

In controller.
```
$request->input('birthday'); // returns replaced value, works fine
$request->only('birthday'); // returns original value

```

**Comment by themsaid** [comment]
Because you return `return parent::all();` at the end of your overridden `all()`.

Please ask on the forums, this repo is for bug reporting only.

**Comment by olcaytanrikulu** [comment]
All right. Sorry for bothering you but what about this?

The original all() method of Illuminate\Http\Request is below.

```
public function all()
{
        return array_replace_recursive($this->input(), $this->allFiles());
}

```
If we are talking about inheritance. This override should work as I expected. Bu it is not.

```
public function all()
{
        $input = array_replace_recursive($this->input(), $this->allFiles());
        $input['birthday'] = 'Replaced Value';       
        $this->replace($input);
        return array_replace_recursive($this->input(), $this->allFiles());
}
```
This seem odd to me. Anyway, I ve done it differently.  Peace :v:
