### ISSUE TITLE
php artisan storage:link destorys storage folder and content

### ISSUE THREAD

**Issue by marco-aa** [laravel/framework#18251]
- Laravel Version: 5.4.15
- PHP Version: 7.1.0
- Database Driver & Version: not needed

### Description:
On our forge development server we use in our deployment script
`php artisan storage:link `
if we deploy more than once we got. (This script worked for weeks without problems)

```
  [ErrorException]
  symlink(): No such file or directory
```
if i look at  _/home/forge/dev.myside.com/storage/app/_ the symlink is pointing to it self !
_public -> /home/forge/dev.myside.com/storage/app/public_
an it killed all user content inside the public folder !  

 in _/home/forge/dev.myside.com/pulic_ the symlink is pointing to
 _storage -> /home/forge/dev.myside.com/storage/app/public_

### Steps To Reproduce:
on a laravel forge server use `php artisan storage:link ` 2 times 

If this is a local problem - ok 
If not i can destroy user content inside storage folder ... please have a look

**Comment by marco-aa** [comment]
We had a closure look into the problem:

we useed (to bypass a git problem)
```
#NEVER USE ON PROD
git fetch origin master
git reset --hard FETCH_HEAD
git clean -df
```
instad of 

`git pull origin master`

This caused that the content _home/forge/dev.myside.com/storage/app/_ public was deletet by git clean

With a second deploy the `php artisan storage:link` gave the error from my inital posting an we found inside _home/forge/dev.myside.com/storage/app/_ a link pointing to itself.

So i think 80% of the problem are self made - but we are not clear why `php artisan storage:link` causes a link wich is pointing to itself

**Comment by themsaid** [comment]
Looks to me as an environment/setup related issue, please use the forums to post your question and I suggest you add as much details as possible so that people can help you.

**Comment by marco-aa** [comment]
Thanks themsaid - we found the reason the _storage/app/public_ folder was mistakenly removed from the gid repository and caused this strange effect - readded and every thing is running fine
Sorry and thanks for having a look :-)
