### ISSUE TITLE
Eloquent ordering not natural

### ISSUE THREAD

**Issue by arctic-ice-cool** [laravel/framework#18257]
- Laravel Version: 5.3.22
- PHP Version: PHP 5.6.27 & 7.0
- Database Driver & Version:

### Description:
`Posts::orderBy('title', 'asc')->get();`
returns the following order:

> 1 - My first post
> 10 - My Tenth post
> 2 - My Second post
> 3 - My Third post

Should Laravel assume natural ordering when using Eloquent? Rather than file storage ordering?

### Steps To Reproduce:
Create any Collection / Model
Order by a column that has the following titles:

> 1 - My first post
> 10 - My Tenth post
> 2 - My Second post
> 3 - My Third post

**Comment by cirdog** [comment]
My 2 cents:

That's the natural ordering for "text-based" columns when the data is treated as "strings".

One way is that you can split away the "numeric index" into another column & sort by that, then concat them with a hyphen right before displaying.

**Comment by samiles** [comment]
That is sorted correctly in PHP, no? If you store them as strings that's how they sort, unless you store `1` as `01`.

**Comment by themsaid** [comment]
Nothing wrong with that, that's how strings are supposed to be sorted. You can always save strings in the form of `01`, `02`, that way `02` will come before `10`
