### ISSUE TITLE
return of render is wrong in documentation

### ISSUE THREAD

**Issue by gemal** [laravel/framework#18269]
- Laravel Version: 5.4.15
- PHP Version:
- Database Driver & Version:

### Description:
https://laravel.com/docs/5.4/errors#render-method

it says:
`@return \Illuminate\Http\Response`

but I think it should be:
`\Symfony\Component\HttpKernel\Exception`

**Comment by Kyslik** [comment]
If this is documentation related move it to [docs](https://github.com/laravel/docs) repo.

**Comment by themsaid** [comment]
The render method returns a response, don't think there's something wrong about the docblock.
