### ISSUE TITLE
Auth::attempt

### ISSUE THREAD

**Issue by mustafaabduljalil** [laravel/framework#18260]
- Laravel Version: 5.4
- PHP Version:5.6
- Database Driver & Version:

### Description:
Auth::attempt() always return false

**Comment by masterwto** [comment]
Please show me your LoginController.

**Comment by mustafaabduljalil** [comment]
![screenshot from 2017-03-08 16-56-27](https://cloud.githubusercontent.com/assets/14807431/23708874/329531ae-0420-11e7-8d47-ced4de2c9b7b.png)

**Comment by mustafaabduljalil** [comment]
![screenshot from 2017-03-08 16-57-43](https://cloud.githubusercontent.com/assets/14807431/23708934/631c5db6-0420-11e7-87df-c510da809c09.png)

**Comment by mustafaabduljalil** [comment]
![screenshot from 2017-03-08 16-58-58](https://cloud.githubusercontent.com/assets/14807431/23708994/9858a106-0420-11e7-9815-cf5026d9870e.png)

**Comment by mustafaabduljalil** [comment]
@masterwto ]there every thing i wish to help me

**Comment by ankurk91** [comment]
I do think why you are using MD5 hashing.
Use inbuilt laravel hashing.
You no need to pass hashed password to ```Auth:: attempt``` method.

https://laravel.com/docs/5.4/hashing

**Comment by mustafaabduljalil** [comment]
i used hash and give me false too !!!!!!!!!!!!

**Comment by masterwto** [comment]
@mustafaabduljalil Your users table should store password as bcrypt($password) instead of md5(password).

You may then auth your account with
Auth::attemp(['id' => $id, 'password' => $password]);

NEVER HASH PASSWORDS WITH YOUR OWN algorithms! USE bcrypt OR PBKDF!

**Comment by mustafaabduljalil** [comment]
@masterwto i wanr auth account by name not id

**Comment by masterwto** [comment]
@mustafaabduljalil

You may then auth your account with
Auth::attemp(['name' => $name, 'password' => $password]);

**Comment by mustafaabduljalil** [comment]
why not use email instead of name ? :D 

i want email because i will use it in another table :D

**Comment by masterwto** [comment]
...
It's up to you.

**Comment by mustafaabduljalil** [comment]
i did everthing u said but not work too :(

**Comment by mustafaabduljalil** [comment]
when i use Hash::make(password) created password in database is different if i print it when i login
example if i enter password 123456 laravel put in database $2y$10$DcutrliGf//wzVwfcd9kjutWw0p.AcYjJTqKt72qrGgq7luf63bYe

if i login and print password he print another string is this ok ?

**Comment by masterwto** [comment]
Bcrypt uses a random string as initial salt. Different salt causes different password hashes.

**Comment by mustafaabduljalil** [comment]
aha u mean at the end after he decrypt that return original password right ??

**Comment by masterwto** [comment]
Your SignIn function, you should replace your line

$password = md5(...)

with

$password = $request->password

The framework automatically chechs the hash with php function password_verify

**Comment by mustafaabduljalil** [comment]
really thaaaaaaaaaaaaaaaaaaaaaaaaaaaaank u 
u save my life :D :D :D

**Comment by mustafaabduljalil** [comment]
can u give me ur facebook account i will proud of u if u r my friend :D ?

**Comment by masterwto** [comment]
bcrypt is NOT decryptable.

When

$password = bcrypt('secret')
$password = bcrypt('secret', $password)

**Comment by mustafaabduljalil** [comment]
i use Hash::make it's working good :)

**Comment by masterwto** [comment]
I'm sorry but I don't have a facebook account.......

**Comment by mustafaabduljalil** [comment]
no problem :D but really thank u
