### ISSUE TITLE
orWhereHas() requires Closure as an argument

### ISSUE THREAD

**Issue by Kwapi** [laravel/framework#18262]
- Laravel Version: 5.3.30
- PHP Version: 7.0
- Database Driver & Version: MySQL 5.7.16

### Description:

I'm not sure why `orWhereHas()` requires Closure as an argument when `whereHas()` doesn't.
It seems consistent. If there is no argument passed this error is thrown:

_TypeError: Argument 2 passed to Illuminate\Database\Eloquent\Builder::orWhereHas() must be an instance of Closure, none given on line 3_

You can easily circumvent the issue by putting an empty Closure in:

`Model::whereHas('thing)->orWhereHas('other_thing', function($query){})->get();`

Is that the desired behaviour?

### Steps To Reproduce:
Perform an Eloquent query on a model which has at least two relations. Get a collection of models that has either one relationship or the other using:
`Model::whereHas('thing')->orWhereHas('other_thing')->get()`

This will result in an error:
_TypeError: Argument 2 passed to Illuminate\Database\Eloquent\Builder::orWhereHas() must be an instance of Closure, none given on line 3_

**Comment by themsaid** [comment]
Moving the discussion to the PR. Thank you!
