### ISSUE TITLE
Able to bypass Image validation

### ISSUE THREAD

**Issue by akaamitgupta** [laravel/framework#18299]
- Laravel Version: 5.4
- PHP Version: 5.6.24

I have wrapped an executable inside an image which has the following content -
```php
GIF89a<?php
echo 'hacked';
?>
```
and saved it as filename _image.gif_.

Now when I upload this image then it's able to bypass the **image** and **dimension** validation.

`'photo' => 'required|image|dimensions:min_width=20,min_height=20',`

Is there a way to validate this kind of images?

A workaround I have tried -

Used PHP function `getimagesize()` but it returns

```
array:6 [▼
  0 => 16188
  1 => 26736
  2 => 1
  3 => "width="16188" height="26736""
  "channels" => 3
  "mime" => "image/gif"
]
```
although image is not valid but still it has valid _width_ and _height_.

**Comment by KKSzymanowski** [comment]
I'm afraid there isn't a built-in way to check if an image is corrupted. `getimagesize`, `exif_imagetype` and `finfo_file` all think the file you provided is correct.

For `jpg`, `png` and `gif` you can use `imagecreatefrom*` and it will throw an exception when the file is invalid. For `svg` and `bmp` you would need to perform the check manually.

I'd suggest creating a custom validation rule for that and reporting the issue to the PHP interpreter developers as is it a problem with PHP itself, not Laravel in my opinion.

**Comment by akaamitgupta** [comment]
@KKSzymanowski  Yes, I agree with you that there is no built-in way and `imagecreatefrom*` can be a workaround. [Intervention/image](https://github.com/Intervention/image) uses the same [approach](https://github.com/Intervention/image/blob/c9a162592dda7ae4ad3b49305da41e82155f9b9a/src/Intervention/Image/Gd/Decoder.php#L15-L59) to validate the image.

But what I think is that framework should support this type of validation in the core otherwise, anyone can say that framework has a loophole in image validation. I have tried the same image to upload on different services on the web and all of them detect it as a harmful content. So why not Laravel do it by default?

And also I didn't get you on 

> For svg and bmp you would need to perform the check manually.

What type of manual check?

**Comment by KKSzymanowski** [comment]
You are right. If the language's standard library doesn't provide this functionality, a framework should fill that gap, but more importantly `getimagesize` shouldn't return random numbers for width and height when the file is corrupt, it should raise an error.

For `bmp` validation I think the simplest way would be to check the [file header](https://en.wikipedia.org/wiki/BMP_file_format#Bitmap_file_header) to see if what is specified at 0x02 offset is equal to the file size. I'm not sure though how this would behave when the file as a whole is ok but the width and height don't match the `Pixel array` size. To verify this case you'd need to calculate the expected `Pixel array` size based on bits/pixel and taking the row padding into account and see if it equals the actual size. You can find the exact equations on the referenced Wikipedia page.

As for `svg` I suppose you could try to parse it as if it was a classic XML file and raise an error if the syntax is incorrect. On the other hand consider whether you can exclude `svg`. Not all browsers support it fully, and anyone who knows how to create one also knows how to export it to PNG, so I think that wouldn't be a problem. Github for example allows only PNG, JPG, and GIF images for a profile picture.

**Comment by akaamitgupta** [comment]
@KKSzymanowski  I have reported the bug to PHP and for the meanwhile, I hope the framework come up with an elegant solution.

**Comment by themsaid** [comment]
@akaamitgupta can you submit a PR with a proper fix?

**Comment by akaamitgupta** [comment]
@themsaid  Right now I don't have a proper fix for this but will submit a PR when I have an acceptable solution.

**Comment by akaamitgupta** [comment]
@KKSzymanowski Just FYI,  I had tried to submit the issue to the PHP but they closed it by saying what you have said earlier -  

> From the manual[1]:
> 
> | This function expects filename to be a valid image file. If a
> | non-image file is supplied, it may be incorrectly detected as an
> | image and the function will return successfully.
> 
> This notice should better be moved to a more prominent place, and be
> improved. So I'm changing to doc-bug.

https://bugs.php.net/bug.php?id=74239&edit=2

**Comment by themsaid** [comment]
Then I'll have to close the issue since it appears to be more related to how PHP works, don't think any further discussions will lead to something here.

Please feel free to ping me if you have any more ideas on that.
