### ISSUE TITLE
View::composer on layout only loads after the view extending the layout does

### ISSUE THREAD

**Issue by vesper8** [laravel/framework#18297]
I'm on Laravel 5.4 by the way

Ok I'm really confused because I've found many answers around that claim that something like this

```
View::composer('layouts.master', 'App\Http\Composers\MasterComposer');
```

Is a solution to not having to use 

```
View::composer('*', 'App\Http\Composers\MasterComposer');
```

The latter is not desirable because then the composer is applied multiple times when all I want is to make it available to the parent layout so that my global variables are available on all the child blade partials

My MasterComposer:

```
<?php

namespace App\Http\Composers;

use Illuminate\Contracts\View\View;

class MasterComposer
{
    public function compose(View $view)
    {
        $view->test = "hello";
    }
}
```

and my home.blade.php:
```
@extends("layouts.master")

@section('content')

 {{ $test }}

@endsection
```

With the wildcard composer this works but if I apply it to layouts.master, the composer still fires but it fires after the home.blade is rendered and it throws a Undefined Variable error

What am I doing wrong?

I DON'T want to use the wildcard because it will load data where it shouldn't be.

**Comment by edenreich** [comment]
$view->test 

Not really sure how compse working in laravel but it seems like syntax mistake you have there maybe?

**Comment by edenreich** [comment]
Compose*

**Comment by vesper8** [comment]
yes just a typo as I was writing out the example code. I have it correct in my application.

I did get workaround this by using View::share() in my service provider, however there are still instances where I would like this to work and I believe this is supposed to work since I found many threads, such as this one http://stackoverflow.com/questions/28647137/laravel-5-view-composer-service-provider-exclude-prefix-from-wildcard that suggest using a View Composer on the layout file to avoid having to use the wildcard

**Comment by devcircus** [comment]
The "children" templates render before layouts, so I would assume, since composers are called when a template renders, then you are correct in assuming the order the composers run. You may just have to share the variable with the views that any need it. Or come at it from another direction all together.

**Comment by marconi1992** [comment]
Like the documentation said the view compose goal is provide data to a view when is rendered
https://laravel.com/docs/5.4/views#view-composers. 

Therefore the data should be accessible only in the master layout scope, if you want to provide data or logic in all the views that extends of your master layout I think is better use a service injection in the master layout. 

 https://laravel.com/docs/5.4/blade#service-injection

**Comment by kminek** [comment]
@marconi1992 i dont think injected services variables in layout template are inherited in child templates...
