### ISSUE TITLE
Find->first()

### ISSUE THREAD

**Issue by terror2012** [laravel/framework#18306]
- Laravel Version: 5.3.30
- PHP Version: 5.6.25
- Database Driver & Version: 5.7.14

### Description:

I'm not sure if it's a bug, or this is how it should work, but I accidentally used mode::find($id)->first() (though it's the same stuff as where, but instead of giving 3 options, you just give the primary key value), but I just re-read it and it also gives it as a model, not collection. 
The problem is simple, when you use find('3'); you get the row where id is 3. If you use ::find('3')->first() you get first record in the database. I know find is not supposed to work with first, but it's a kind of issue when you work in a large app and by accident (aftering using a lot of wheres), you also include a find with first :(.

### Steps To Reproduce:

$test -> model::find('5')->first();
dd($test);

**Comment by mg-freelancer** [comment]
you shouldn't use first with find because find give specific **one** record

**Comment by srmklive** [comment]
@terror2012 It's not a bug,  you are simply doing it wrong. As @mg-freelancer pointed out, you shouldn't use `first()` with `find()` as `find()` already gives you a single record. Also refer to Laravel documentation as well.
