### ISSUE TITLE
Validation required array

### ISSUE THREAD

**Issue by ZeyadMounir** [laravel/framework#18308]
- Laravel Version: 5.4

### Description:
When I am using required on array and it has elements but they are null, it should filter them and give error, right? It doesn't work like that. It just checks whether the array has elements even if they are null.

**Comment by akaamitgupta** [comment]
You can use `'photos.*' => 'required|image',` to check if all the element is not null.

**Comment by marconi1992** [comment]
Like said @akaamitgupta  you should use the wildcard notation to evaluate each element inside of the array, for more information check the documentation
https://laravel.com/docs/master/validation#validating-arrays

**Comment by ZeyadMounir** [comment]
Yes, I am aware of it but I don't need to check all the elements! I just need to check the array as whole and that's what "required validation" on an array should do.

**Comment by marconi1992** [comment]
```php
$data = [
    "things" => [
        null,
        [
            "name" => "the thing"
        ]
    ]    
];

Validator::make($data, [
    "things" => "required|array"
]);
```
Following the example, Do you suggest that the validator should know if the array contains a null value without check any element into the array? This not is possible, How will you know what is the index of the array where you sending a null value? Using only the "required" , It would be ambigous to handle validation errors.

**Comment by ZeyadMounir** [comment]
[http://php.net/manual/en/function.array-filter.php](array_filter) does that! :)
"If no callback is supplied, all entries of array equal to FALSE will be removed."

**Comment by marconi1992** [comment]
@ZeyadMounir  I got it, following the example. The filtered array will be empty therefore it shouldn't pass the "required" rule.
```php
$things = [
    null,
    null
];

$things = array_filter($things);
```

**Comment by ZeyadMounir** [comment]
Exactly!

**Comment by themsaid** [comment]
Sometimes `null` is an acceptable value, so using `array_filter` by default is not an option, I suggest that you filter the data before passing to the validator if you want the behaviour you're referring to.

**Comment by ZeyadMounir** [comment]
Using required in other cases doesn't pass null value so as it should be with using required on an array! It's just logical.

**Comment by themsaid** [comment]
```
[
   "sku" : null,
   "barcode": null
]
```

The above should pass, you say an array must be provided and an array was provided, if you want to say that the array members must be with a value that's another thing.

**Comment by ZeyadMounir** [comment]
In this case we could use min:(count) which validates the presence not the value.
