### ISSUE TITLE
php artisan make:auth command overrides the existing views by default

### ISSUE THREAD

**Issue by CrestApps** [laravel/framework#18309]
- Laravel Version: v5.4.15
- PHP Version: 5.6.24
- Database Driver & Version: MySQL 5.7.17

### Description:
Where I issue `php artisan make:auth` command to use the authorization setup. The command overrode my `layout/app.blade.php` file. This caused me to lose my work!

The command should check if the files already exists before overriding the file. Instead of overriding, it should throw a warning and if the use wishes to override the files he/she can run the command with the `--force` option.

### Steps To Reproduce:
create a file called app.blade.php in the `views/layouts` folder and write some code

Then execute `php artisan make:auth` command

**Comment by mg-freelancer** [comment]
``layout/app.blade.php`` is generated for authorization system only

**Comment by CrestApps** [comment]
@mg-freelancer well I happened to be using a layout with the same name. Since the file existing at the time the command was executed, the command should not assume that it can just override all my work just because there is a naming conflict. It is best to let the use make that decision.

**Comment by marconi1992** [comment]
@CrestApps  I also think that is important check if already exist the views because in this case the name of the layout is very common in applications

**Comment by srmklive** [comment]
`php artisan make:auth` is to be used only when you create a new laravel application. I would not recommend that you run this command on an already created application.

**Comment by ntzm** [comment]
That's true @srmklive, but it should definitely show an error if those files already exist and **not** overwrite them.

**Comment by GrahamCampbell** [comment]
Feel free to send a PR.

**Comment by OllyTeam** [comment]
I've already created the app file in layouts,
but still after running the "php artisan make:auth" command it shows me the following message
The [auth/register.blade.php] view already exists. Do you want to replace it? (yes/no) [no]: >


help plz

**Comment by samimetoui** [comment]
artisan **make:auth** has completely overwritten my **HomeController** with emty controller content
