### ISSUE TITLE
Add contracts around the `Notifiable` trait

### ISSUE THREAD

**Issue by shulard** [laravel/framework#18318]
- Laravel Version: 5.*
- PHP Version: *
- Database Driver & Version: n/a

### Description:

I'm facing problems on the global notification behaviour. Actually there are "only" some traits which encapsulate the `Notifiable` logic and it can be a little tricky to ensure what data are actually processed inside a `$notifiable` variable...

I think it can be more solid to integrate a `Notifiable` contracts that can be bound every where a `Notifiable` instance is awaited. Traits are very useful for DRY but I think they don't replace global contract structure 😄.

If you are open to integrate it, I can work on a PR.

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.

**Comment by shulard** [comment]
Thanks, I've opened laravel/internals#468.
