### ISSUE TITLE
Laravel5.4 AJAX file upload

### ISSUE THREAD

**Issue by leozim** [laravel/framework#18311]
- Laravel Version: 5.4
- PHP Version: 5.6
- Database Driver & Version:

### Description:
When I upload file by ajax, the $_FILES array contains the info of the file
but file  in the $request->all() is null
How to solve it?

**Comment by marconi1992** [comment]
You must to use the file method.
```php
$request->file("doc");
```
https://laravel.com/docs/5.4/requests#files

**Comment by leozim** [comment]
Thank you，But it is null too

**Comment by marconi1992** [comment]
@leozim Maybe the multipart/form-data ContentType is missing in the ajax request. I recommend you ask in stackoverflow or laracasts.
https://stackoverflow.com/questions/tagged/laravel+laravel-5
https://laracasts.com/discuss

**Comment by leozim** [comment]
@marconi1992 Ok, Thank you

**Comment by Dylan-DPC** [comment]
@leozim either ask there or on the Larachat slack channel. Whichever one you prefer :)

**Comment by leozim** [comment]
@marconi1992 @Dylan-DPC  I got it 
I use a upload plugin called webupload，it can;t work well with laravel
when I use swfupload，It works.
Thank all of you
