### ISSUE TITLE
Authenticate middleware use an invalid method on AuthManager

### ISSUE THREAD

**Issue by shulard** [laravel/framework#18315]
- Laravel Version: 5.*
- PHP Version: *
- Database Driver & Version: n/a

### Description:

I found that `Illuminate\Contracts\Auth\Guard` interface does not define the `authenticate` method. 
This method is directly used inside the `Illuminate\Auth\Middleware\Authenticate` middleware. 

This method is defined in the `Illuminate\Auth\GuardHelper` trait but what if I don't need it ?

### Steps To Reproduce:

If you create your own application guard by implementing `Illuminate\Contracts\Auth\Guard` interface, you get an `Unknown method error` when the `Authenticate` middleware is applied.

### Possible solution

Maybe the best solution is to use an existing Guard method instead of adding `authenticate` method signature to Guard interface.

**Comment by roquie** [comment]
I have a same error...
