### ISSUE TITLE
PHP Fatal error if dusk tests run longer than 3 minutes.

### ISSUE THREAD

**Issue by masterwto** [laravel/framework#18316]
- Laravel Version: 5.4.*
- PHP Version: 7.1.1
- Database Driver & Version: MariaDB 10.1.21

### Description:

I was using selenium and running tests with firefox 43.

when I run the tests separately, every test results OK, when I run a group of tests that total execution time is less than 3 minutes, tests are also successful, However, when I run all tests, I will get some errors like this:

..........EEEEEEEEEEEEEEEE

PHP Fatal error: Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target Illuminate\Contracts\Debug\ExceptionHandler is not instantiable. in....

What's wrong with this？

Thanks for reading.

### Steps To Reproduce:
using multiple laravel tests to run longer than 3 minutes and run artisan dusk.

**Comment by themsaid** [comment]
Please reports on the dusk repo: https://github.com/laravel/dusk
