### ISSUE TITLE
Error 500 when outputting the resized images in laravel

### ISSUE THREAD

**Issue by hamzaali00001** [laravel/framework#18324]
- Laravel Version: 5.4.15
- PHP Version: 7.0.10
- Database Driver & Version: Mysql v5.7.14

### Description:
I am resizing the uploaded images using a class resizeImages. It takes an array of images and loops over them to create resize images. Once I go to the page where code for outputting images is placed, 500 error code is returned. NO data is available in the laravel logs. Error shown is:

The localhost page isn’t working

localhost is currently unable to handle this request.
HTTP ERROR 500

I checked this code outside of the laravel and it works fine. Error 500 code is only returned once. As soon as I refreshed this page it works exactly fine. I have no idea why laravel returns 500 error code on first time the request is sent. Please resolve this problem because this only gives error inside laravel. There are no errors when testing this code outside laravel.

I debugged this problem exists on the line where I am outputting images. Anyone with some solution, please help me

**Comment by Kyslik** [comment]
If there is nothing in Laravel log file well, stop right there, **500** error has nothing to do with Laravel what so ever; it clearly says **Internal Server Error**, is Laravel server? You need to check your Apache logs / NGINX logs.

I am betting on permissions :)

**Comment by themsaid** [comment]
Please ask on the forums, we keep this repo for bug reporting only.

**Comment by hamzaali00001** [comment]
But the point is that if I test this code on the same web server but outside of the laravel, it makes no errors. Then why is that. Error 500 is also returned when htaccess is not working properly. But as I reload code works perfectly. Have you ever worked with resizing images in laravel without getting any error, if so there might be some problem with my pc. I will keep on developing and my website will be fine in deployment. Thanks
