### ISSUE TITLE
Empty request Vue.js ajax upload

### ISSUE THREAD

**Issue by behind-design** [laravel/framework#18326]
- Laravel Version: 5.3.*
- PHP Version: 7.1.1
- Database Driver & Version: mysql v5.7.17

### Description:
I've been working on a backend app where the user has to be able to upload a video, and set a few attributes to it, like title and stuff like that. For the file handling and uploading I'm using Vue.js due that it allows me to do it with ajax. I'm sending the request as a `multipart/form-data`. Where I'm sending the file as well as some attributes to setup everything correctly in the server.
If I take a look in the `network tab`, I can see that the request is being send with the data as expected. But once it get to the server, in Laravel's side, the request is empty, and I cannot figure out why is that.

Any help?

Thanks!!!

**Comment by themsaid** [comment]
Sorry, but please ask on the forums, we try to keep this repo for bug reporting only.
