### ISSUE TITLE
[5.4] Allow Modifying Auth Routes

### ISSUE THREAD

**Issue by CupOfTea696** [laravel/framework#18321]
Laravel should allow (some) customisation of the Auth routes, similar to how you can do it for [Resource Controllers](https://laravel.com/docs/5.4/controllers#resource-controllers). Parameters could be added to change the route verbs (useful for l10n), excluding certain routes form being added (useful for disabling registration for example), not sure if the route names can be customised since they may be used internally.

**Comment by Dylan-DPC** [comment]
You can create your own Auth routes.

**Comment by themsaid** [comment]
Yes, it's just a convention that you can completely ignore and create your own.
