### ISSUE TITLE
Some thoughts on extending Illuminate\Database\Eloquent\Relations\Relation?

### ISSUE THREAD

**Issue by Mevrael** [laravel/framework#18334]
For many to many I need to join 2 tables without junction table. 1st table stores related IDs in JSON array in separate column.

Here is example how it can be done via MySQL:
```sql
SELECT posts.id AS post_id, users.id AS liked_by_user_id FROM posts JOIN users ON JSON_CONTAINS(posts.liked, CAST(users.id AS CHAR))
```

The problem is how to make a manual raw join in Laravel and bigger problem is how to extend Relation class to make it working with eager loading. Right now I am trying to write BelongsToManyJson class and without much success. In model I just return it in relationship method and so far it works but I can't understand whole internal architecture of Illuminate\Database\Eloquent\Relations\Relation and all classes on top of it to make the join itself and to retrieve data, right now I have empty Model without a related key with collection. Any ideas on how I could achieve the goal? What is difference between addConstraints() and addEagerConstraints()? What initRelation(), match(), getResults() should do and return?

```php
class Post
{
    ...

   function users()
   {
      $class = new App\User;
      return new BelongsToManyJson($this->newQuery(), new $class);
   }
```

**Comment by themsaid** [comment]
Please use the forums to post question :)

Thank you!
