### ISSUE TITLE
ShouldQueue  and Queueable in Listeners

### ISSUE THREAD

**Issue by mb-programmer** [laravel/framework#18339]
- Laravel Version: 5.3
- PHP Version: 7.1
- Redis Queue

### Description:
Hello to everyone.
I have an event with several Listeners. The ShouldQueue interface work well on Listeners, but the listeners can't work with Queueable trait (delay, different queue), is this a bug or a feature?

I know that I can use jobs for delaying. But in my perspective, every class that allows to implement ShouldQueue should also work with Queueable (the ability to be delayed).

**Comment by Kyslik** [comment]
Is this the case? https://github.com/laravel/framework/pull/18235

**Comment by sisve** [comment]
The linked issue is about moving scheduled jobs to the queue, not event listeners.

Related: https://github.com/laravel/framework/issues/18199

**Comment by mb-programmer** [comment]
Sorry I didn't find the issue before. 
Thanks @sisve 
It would be good to have this feature.

**Comment by themsaid** [comment]
`Queueable` can be used while dispatching a job since you have access to the job object to call Queueable's methods on, but listeners are created internally.

I Just submitted a PR that should add the functionality https://github.com/laravel/framework/pull/18375

**Comment by mb-programmer** [comment]
Thanks, @themsaid
