### ISSUE TITLE
Artisan issues with incorrect timezone

### ISSUE THREAD

**Issue by RhubarbLeaves** [laravel/framework#18333]
- Laravel Version: 5.4.15
- PHP Version: 5.6.28

### Description:

When timezone in `app.php` is incorrect, `artisan` cannot make a migration (both `php artisan make:migration` and `php artisan make:model Model -m` do not succeed), with no errors displayed. Even trying to execute a non existent command like `php artisan qwerty` doesn't produce an error.

### Steps To Reproduce:
1. Set an incorrect timezone in `app.php`: `'timezone' => 'asdf',`
2. Type an incorrect command: `php artisan asdf`, or try to make a migration: `php artisan make:migration test`.

**Comment by Dylan-DPC** [comment]
Tried on Laravel  5.4.13  (PHP 7.0.16)  
I do get: 
```
PHP Notice:  date_default_timezone_set(): Timezone ID 'farara' is invalid in /home/dpc/Code/zero.institute/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php on line 48
PHP Stack trace:
PHP   1. {main}() /home/dpc/Code/zero.institute/artisan:0
PHP   2. Illuminate\Foundation\Console\Kernel->handle() /home/dpc/Code/zero.institute/artisan:35
PHP   3. Illuminate\Foundation\Console\Kernel->bootstrap() /home/dpc/Code/zero.institute/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:115
PHP   4. Illuminate\Foundation\Application->bootstrapWith() /home/dpc/Code/zero.institute/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:270
PHP   5. Illuminate\Foundation\Bootstrap\LoadConfiguration->bootstrap() /home/dpc/Code/zero.institute/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:208
PHP   6. date_default_timezone_set() /home/dpc/Code/zero.institute/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php:48
```

**Comment by themsaid** [comment]
Set a correct timezone.

**Comment by RhubarbLeaves** [comment]
@themsaid So absence of error messages considered a correct behaviour? Or should I check my PHP settings?

**Comment by Dylan-DPC** [comment]
@RhubarbLeaves As I showed above I am getting the proper error message. The issue might be elsewhere.
