### ISSUE TITLE
Paginator's setPageName() not working

### ISSUE THREAD

**Issue by poisa** [laravel/framework#18342]
- Laravel Version: 5.3.30
- PHP Version: 7.0.13

### Description:
Paginator creates links as expected with whatever is passed to `setPageName()` but all pages show the first paginator page.

### Steps To Reproduce:
```php
public function noticias(Request $request)
    {
        $news = News::where('enabled', 1)
            ->orderBy('date', 'desc')
            ->paginate(5)
            ->setPageName('foo');

        return view('news', [
            'title' => 'Latest News',
            'news' => $news
        ]);
    }
```

Generated links
> http://test.dev/news?foo=1
> http://test.dev/news?foo=2
> http://test.dev/news?foo=3  // etc, etc

### Expectation
That each link pulls the correct rows from the database, thus, all pages should have different results.

### Actual result
All pages show the same results (the first 5 results in the paginator)

### Notes
Removing `setPageName('foo')` makes links to be named `page` and paginator works as expected.

### Why I want to do this:
I need to change the word `page` to whatever language the visitor is in.

**Comment by marconi1992** [comment]
Is because you are using the setPageName in the LenghtAwarePaginator that is the result from the paginate query, therefore you need to pass the page name to the Builder object in order to to let you know the page name is "foo".

```php
 public function noticias(Request $request)
    {
        $news = News::where('enabled', 1)
            ->orderBy('date', 'desc')
            ->paginate(5, ["*"], "foo");

        return view('news', [
            'title' => 'Latest News',
            'news' => $news
        ]);
    }

For more information https://laravel.com/api/5.3/Illuminate/Database/Eloquent/Builder.html#method_paginate

**Comment by yosualb** [comment]
@marconi1992 
I have searched other solution

> `Paginator::setPageName('p');`
> You can place that in `app/start/global.php`

I don't know how to use them in Laravel 5.3 or higher. Can you please tell me?

**Comment by marcelogarbin** [comment]
@yosualb any news?
