### ISSUE TITLE
The store method in $request is not working

### ISSUE THREAD

**Issue by davidpmtz** [laravel/framework#18341]
- Laravel Version: 5.4.15
- PHP Version:5.6.30
- SO: W10 with Laragon

The store method in $request is not working;

`$request->avatar->store('avatars');`

![image](https://cloud.githubusercontent.com/assets/12993637/23927476/93e61bbc-08df-11e7-966e-080c88dcd1a1.png)

**Comment by devcircus** [comment]
Sounds like that error is saying that your avatar file is not valid. "Store" is a method on the UploadedFile class. So try to dump avatar and see if it is an instance of UploadedFile.
```
dd($request->avatar);
```

**Comment by themsaid** [comment]
Yes that's an indication that the file is not valid, try validating the value of avatar as @devcircus explained.

**Comment by davidpmtz** [comment]
Here is the `dd($request->avatar)`

![image](https://cloud.githubusercontent.com/assets/12993637/23959128/ec4cb11e-0969-11e7-875d-05b94a006a36.png)

And here is the code:

```
if ($request->hasFile('avatar') && $request->file('avatar')->isValid()) {
//            dd($request->avatar->store('avatares'));
            dd($request->avatar);
        }
```

This code in the FilesystemAdapter is the reason of the exception.

`$stream = fopen($file->getRealPath(), 'r+');`

And if I do

`dd($request->file('avatar')->getRealPath());`

The result is `false`

This occurre with all types of files.

So, what is the problem?, is there another config to store a file?

**Comment by pavlov80** [comment]
I have this problem too. The uploading files are valid. This is for sure. The problem is when the webserver is IIS. The line 146 in FilesystemAdapter.php, which use:
`$stream = fopen($file->getRealPath(), 'r+');`
is always returning false. This will work if you change it to:
`$stream = fopen($file->getPathName(), 'r+');  // Windows`

But then on laravel update, this will be overwriten.

**Comment by decadence** [comment]
@pavlov80 then consider to make PR
