### ISSUE TITLE
Blade: Wrong data used when repeatedly including a template that extends another

### ISSUE THREAD

**Issue by andyvenus** [laravel/framework#18348]
- Laravel Version: 5.4.15
- PHP Version: 7.1
- Database Driver & Version: n/a

### Description:
It seems when including a template that extends another, the data rendered is always the data given to the first include of the template.

### Steps To Reproduce:

These are my 3 templates for testing:

index.blade.php:
```
@include('inherits', ['var' => 'First Include'])
@include('inherits', ['var' => 'Second Include'])
```

inherits.blade.php:
```
@extends('base')

@section('a', $var)
```

base.blade.php:
```
@yield('a')
```

When rendering index.blade.php the output should be "First IncludeSecond Include". Instead you see "First IncludeFirst Include".

**Comment by themsaid** [comment]
Instead of `@section('a', $var)` use:

```
@section('a')
   {{ $var }}
@overwrite
```

**Comment by andyvenus** [comment]
@themsaid Thanks!
