### ISSUE TITLE
Call to a member function all() on null

### ISSUE THREAD

**Issue by mirbatworks** [laravel/framework#18346]
- Laravel Version: 5.4.15
- PHP Version: PHP 7.0.3
- Composer 1.4.1

I want to select pages from database
PagesController:
```php
$pages = $this->pages->all();
return view('pages.index', compact('pages'));
```

in index blade page:
```php
<tbody>
	@if($pages->isEmpty())
	<tr>
		<td colspan="6" align="center">{{ trans('page.no_page') }}</td>
	</tr>
	@else
		@foreach($pages as $page)
			<tr>
				<td>{{ $page->title }}</td>
				<td>{{ $page->uri }}</td>
				<td>{{ $page->name }}</td>
				<td>{{ $page->icon }}</td>
				<td><a href="#"><i class="fa fa-edit"></i></a></td>
				<td><a href="#"><i class="fa fa-remove"></i></a></td>
			</tr>
		@endforeach
	@endif
</tbody>
```
This should return translated message that there are no pages in database, but I'm getting error

> FatalThrowableError in PagesController.php line 25: Call to a member function all() on null

**Comment by jerguslejko** [comment]
`$this->pages` is not set properly in the `PagesController`.

This is not an issue with the framework.

**Comment by mirbatworks** [comment]
It is set properly. I didn't wrote complete code.
```php
class PagesController extends Controller
{
    protected $pages;

    public function __constructor(Page $pages)
    {
        $this->pages = $pages;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pages = $this->pages->all();
        return view('admin.pages.index', compact('pages'));
    }
```

**Comment by jerguslejko** [comment]
Does `__constructor(Page $pages)` refer do `Page` model? If so, you need to use it like this:

```php
$pages = Page::all();
```

**Comment by mirbatworks** [comment]
It's working on that way. But, I use $page = $this->pages->all() method in my projects in Laravel 5.2 with injected model and property in __construction method and it works fine.

**Comment by jerguslejko** [comment]
`__constructor` => `__construct`

**Comment by mirbatworks** [comment]
That's the problem. Thanks.
