### ISSUE TITLE
I can't get the insertGetId When I execute SQL by commit transaction.

### ISSUE THREAD

**Issue by cw1997** [laravel/framework#18344]
- Laravel Version: 5.3
- PHP Version: 5.6
- Database Driver & Version: MySQL 5.1

### Steps To Reproduce: 
         try {
            DB::transaction(function () use ($request, $ip, $now) {
                $insert_data =
                    [
                        'email' => $request->input('email'),
                        'username' => $request->input('username'),
                        'password' => $request->input('password'),
                        'reg_time' => $now,
                        'reg_ip' => $ip
                    ];
                $uid = DB::table(__tablePrefix__.'users')->insertGetId($insert_data);
                $insert_data =
                    [
                        'uid' => $uid,
                        'father_id' => 0,
                        'floder_name' => $uid,
                        'create_time' => $now
                    ];
                // execute failed baceuse $uid is null
                $folder_id = DB::table(__tablePrefix__.'folders')->insertGetId($insert_data);
            });
        } catch (\Illuminate\Database\QueryException $e) {
            var_dump($e);
        }

**Comment by themsaid** [comment]
> can't get

Please share more details, what errors do you get and with full stack trace. Also 5.3 is not supported anymore, please upgrade your application to 5.4 and try again then open a new issue with more details.
