### ISSUE TITLE
__() function already defined conflict with other code

### ISSUE THREAD

**Issue by owl27** [laravel/framework#18358]
- Laravel Version: 5.4.15
- PHP Version: 7.1.0
- Database Driver & Version: MySQL

Hi,

Does anyone know of a workaround for how to fix an issue where Laravel's __() function is conflicting with other third party code?

If I edit both libraries, the problem can be resolved, however I assume this to be a very bad workaround in practice.

I have never experienced such an issue and am running out of ideas for how it could be solved.

**Comment by stefanoruth** [comment]
The Laravel version of the function is wrapper with `! function_exists('__')` so that should not conflict but what about the other library?

**Comment by owl27** [comment]
The other library does not. Furthermore, the other library uses a string parameter and not an array, so both would have to be altered if Laravel's __() is first.

**Comment by owl27** [comment]
Please note, this problem was introduced in Laravel 5.4. In Laravel 5.3, this issue does not exist.

Wouldn't it make more sense to have a unique function name for this?

**Comment by ntzm** [comment]
The library `__()` should be namespaced. This isn't a Laravel issue.
