### ISSUE TITLE
An empty string validates as an integer

### ISSUE THREAD

**Issue by jarednipper** [laravel/framework#18352]
- Laravel Version: 5.3.30
- PHP Version: 7.0
- Database Driver & Version: n/a

### Description:

An empty string validates as an integer. A string consisting of one or more blank spaces validates as an integer.

### Steps To Reproduce:

```
Psy Shell v0.8.2 (PHP 7.0.15 — cli) by Justin Hileman
>>> $v = \Validator::make(['id'=>''], ['id'=>'integer'])
=> Illuminate\Validation\Validator {#806}
>>> $v->fails()
=> false
```

### Expected Behavior:

`is_int()` handles this correctly:

```
>>> is_int('')
=> false
```

```
>>> is_int('   ')
=> false
```

```
>>> is_int(4)
=> true
```

**Comment by themsaid** [comment]
An empty string is skipped during validation so it'll pass any rule given except those that imply the field is required rules.

**Comment by jarednipper** [comment]
Why? This isn't explained anywhere. It doesn't make sense.

**Comment by themsaid** [comment]
The main reason is HTML forms, if you leave the field empty it'll submit an empty string, without skipping empty strings you'll start seeing errors while the field is not provided and not required.

**Comment by taylorotwell** [comment]
The correct answer is to use `filled|integer` as your rule.
