### ISSUE TITLE
Eloquent abstract Model is missing setKeyType method

### ISSUE THREAD

**Issue by tdondich** [laravel/framework#18353]
- Laravel Version: 5.4
- PHP Version: 7.0+
- Database Driver & Version: MySQL 5.7

### Description:
The Eloquent Model class has various public methods to set the protected properties used to match characteristics of the underlying table, such as table name, primary key and primary key type.  Eloquent documentation states to overwrite these protected properties in classes that extends Model.  However, there are public methods provided to overwrite these values during runtime which are extremely useful if you have Eloquent Models that need to operate on multiple tables.  There is setTable and setKeyName and setIncrementing, however, there is no setKeyType method to change the primary key type.

### Steps To Reproduce:
Implement a new Eloquent model and attempt to modify it's table characteristics during runtime.  setTable works, setKeyName works and setIncrement works, but working on a table that does not have a int primary key cannot be used when using setTable to point to a table without a int primary key (such as char(16) guid)

**Comment by themsaid** [comment]
I find it odd to do that, but I personally don't have problems with adding such setters, anyways please feel free to open a PR with your proposed changes.

**Comment by tdondich** [comment]
@themsaid The use case is absolutely in dynamic environments where you may want to use a Eloquent model which has utility methods you've written that work across multiple tables, but you want to use the same Model class to operate on them.  The fact that we have setters for the other protected properties validates this kind of use case.

**Comment by themsaid** [comment]
Oh I see, ok let me know if u need any help submitting the PR :)

**Comment by tdondich** [comment]
PR is in: https://github.com/laravel/framework/pull/18354  .  Can we please re-open?  I don't understand why this issue would be closed?

**Comment by themsaid** [comment]
I copied the description into the PR: https://github.com/laravel/framework/pull/18354

Having a PR is enough, no need for a PR and an issue.
