### ISSUE TITLE
Auth::attempt params

### ISSUE THREAD

**Issue by mizansyed** [laravel/framework#18366]
- Laravel Version: 5.4
- PHP Version: 5.6
- Database Driver & Version: MySql

In version 5.3 you could check credentials without logging in, this no longer works in 5.4, i.e. the 3rd param ($login=false) is no longer in use or removed.
`Auth::attempt(['email' => $email, 'password' => $password], false, false);`

According to the comments in the class Illuminate\Support\Facades\Auth, it is still there but underlining class does not seem to support.

**Comment by crynobone** [comment]
Shouldn't you use `Auth::validate()` for this use case?
