### ISSUE TITLE
[Validation] Optional Nullable Fields

### ISSUE THREAD

**Issue by mdavis1982** [laravel/framework#18374]
- Laravel Version: 5.4.x
- PHP Version: 7.1.2
- Database Driver & Version: n/a

### Description:
In my application I have an address form that includes `address_one`, `town` and `postcode`. In Laravel 5.3 I had the following validation rules in my form request class:

```
'address_one' => ['required_with:town,postcode', 'min:6', 'max:64'],
'town'        => ['min:3', 'max:32'],
'postcode'    => ['required_with:address_one,town', 'min:6', 'max:16'],
```

The aim of this set of validation was the following:

- Not entering anything into any of the fields is valid
- Entering just an `address_one` and a `postcode` is valid as the `town` field is not required
- Entering just a `town` is invalid because the `address_one` and `postcode` are required when the town is present
- Entering `address_one` and `town` is invalid because `postcode` is required with either of those fields
- Entering `town` and `postcode` is invalid because `address_one` is required with either of those fields

Essentially, it should be possible to submit the form with nothing entered, `address_one` and `postcode`, or all three fields.

This has been working fine in Laravel 5.3 for a few months. I'm currently rewriting my application in 5.4 and came to add this yesterday, but the above validation no longer works.

I believe this is because of the `nullable` rule requirement for optional fields due to the `ConvertEmptyStringsToNull` middleware, but adding this to `address_one` and `postcode` causes them to not respect the `required_with` rule. If I don't add the `nullable` rule then `address_one` and `postcode` apply the `min` and `max` validation even when there is no value present.

Of course, this makes perfect sense - the framework is doing what it should with the rules it's been given... It's just not what I want and I think it's a slight regression 😄 

It almost seems like we need a new `nullable_without` rule that would set the field to be `nullable` if the other fields were not present, or `required_with` should set the value to `nullable` if the fields that it checks are not present.

This feels like an edge case that has been missed... I've successfully got a workaround working using `withValidator()` and adding `sometimes()` rules, but it seems like that's quite messy and not as clean as the 5.3 version.

### Steps To Reproduce:

- Create a form with `address_one`, `town`, `postcode`
- Add the above validation rules in a Form Request object
- Submit the form and watch the rules work (un)expectedly.

**Comment by themsaid** [comment]
`ConvertEmptyStringsToNull` is completely optional, you can drop it if you want and that will give you the same effect as in 5.3.

**Comment by codemonkeynorth** [comment]
Note: `ConvertEmptyStringsToNull` middleware also breaks the 'sometimes' rule

eg if I submit an empty form field and my rule is eg
`'sometimes|numeric'`
or
`'sometimes|min:3'`
then the validation kicks in and rejects the field, ignoring the `sometimes` part

**Comment by themsaid** [comment]
I've submitted a PR trying to get around this edge case, check https://github.com/laravel/framework/pull/18376

**Comment by mdavis1982** [comment]
@themsaid It's optional, but it's highly desirable for me in the rest of the application because I want to store `null` in the database rather than empty strings. But I also want this ability to be able to mark a field as `nullable` depending on the presence (or not) of other fields in the submitted data.

**Comment by themsaid** [comment]
Ok I think the PR that was just merged will handle this case for you, closing this issue but feel free to ping me if you have any other edge cases that the PR doesn't cover.

**Comment by mdavis1982** [comment]
Brilliant... Thank you so much @themsaid 😄
