### ISSUE TITLE
Why is the hidden field in the Laravel Model not working when set dynamically?

### ISSUE THREAD

**Issue by ps92** [laravel/framework#18372]
- Laravel Version: 5.4
- PHP Version: 7.0
- Database Driver & Version: MySQL 5.7

### Description:
Please refer the [stackoverflow link](https://stackoverflow.com/questions/42827731/why-is-the-hidden-field-in-the-laravel-model-not-working-when-set-dynamically)

### Steps To Reproduce:
Described in [this link](https://stackoverflow.com/questions/42827731/why-is-the-hidden-field-in-the-laravel-model-not-working-when-set-dynamically).

**Comment by ps92** [comment]
I see the hidden is actually applied in 
Illuminate\Database\Eloquent\Concerns\Hasttribute trait, which is called eventually when __toString in Model is called, which is after I call get() in the query. So, why I am not able to produce a result without the hidden field?

**Comment by themsaid** [comment]
Because when you use `with()` an new instance of the model is created `return (new static)->newQuery()->....`, that's why hidden won't work if dynamically set.

Better do the hiding when you get the results collection.
