### ISSUE TITLE
Cannot set NULL value for Property of JSON Column

### ISSUE THREAD

**Issue by ozanakman** [laravel/framework#18370]
- Laravel Version: 5.4.*

### Description: 
I'm getting an error when I'm trying to update json column like this:
`Model::update(['fields->photo' => null])`

Error:

> InvalidArgumentException in JsonExpression.php line 48:
> JSON value is of illegal type: NULL

**Comment by Mevrael** [comment]
At least in MySQL JSON can NOT be NULL. You have to put empty string or if it is array empty "[]"

**Comment by ozanakman** [comment]
@Mevrael so we have to do bad practise. Then I have a question. How can I delete property of json column with eloquent?

**Comment by themsaid** [comment]
> Then I have a question, how can I delete property of json column with eloquent?
> Should I get column and unset property with php then update? Any quick way to do that?

Yes, it's currently not supported via Eloquent.

**Comment by SerikK** [comment]
@ozanakman how did you solved?
