### ISSUE TITLE
container method injection is incorrect

### ISSUE THREAD

**Issue by yb199478** [laravel/framework#18371]
- Laravel Version: 5.4
- PHP Version:
- Database Driver & Version:

### Description:

container method injection is incorrect.
demo see: https://github.com/yb199478/BugList/blob/master/bug.zip

**Comment by yb199478** [comment]
If there is a context, the method that calls the specified class is not bound by the context.
Is it better to use contextual relationships first?

**Comment by themsaid** [comment]
Can you please add more details to the issue? It's pretty hard to just read through your code to try to find the issue.

Include the code here in the issue with comments describing what you expect vs. what the current implementation gives you.

**Comment by yb199478** [comment]
`interface ITalk{ function talk(); }

    class TalkMessage1 implements ITalk{ 
        public function talk(){ echo "this is message1\n"; }
    }

    class TalkMessage2 implements ITalk{
        public function talk(){ echo "this is message2\n"; }
    }

    class Player{

        public function __construct(ITalk $talk){
            echo "__construct:";
            $talk->talk();
        }

        public function talk(ITalk $talk){
            echo "talk():";
            $talk->talk();
        }

    }

    $container = new Container();
    $container->bind("player", Player::class);
    $container->bind("message1", TalkMessage1::class);
    $container->bind(ITalk::class, TalkMessage2::class);
    $container->when(Player::class)->needs(ITalk::class)->give("message1");
    $container->call("player@talk"); 

    // run code echo : 
    __construct:this is message1
    talk():this is message2
`

When I call the method when the context, the method call is not injected in accordance with the context.
Is it better to use context in the presence of a context?(use default injections when there is no context) this is just a suggestion.

**Comment by themsaid** [comment]
Contextual binding only works for class dependencies not methods, I wonder why don't you request your dependencies in the class constructor instead?
