### ISSUE TITLE
Port all of Laravel to TypeScript

### ISSUE THREAD

**Issue by rhyek** [laravel/framework#18382]
I love Laravel, but hate PHP. Please fix. Please don't suggest Adonis.

**Comment by joshmanders** [comment]
Please keep such comments on Reddit or something. You're blowing up 843 people's notifications and emails with nonesense.

**Comment by rhyek** [comment]
@joshmanders I think I love Laravel a bit less now thanks to you.

**Comment by Dylan-DPC** [comment]
Great to hear that :) Also plenty of people will love Github a bit less now thanks to you

**Comment by jordyvandomselaar** [comment]
What the actual ....

**Comment by base-zero** [comment]
@GrahamCampbell Time to flex your locking powers 💪

**Comment by koenhoeijmakers** [comment]
I have already started working on this, you can find the repo [here](github.com/koenhoeijmakers/laravel-typescript-port)

**Comment by GrahamCampbell** [comment]
Hahaha. I don't think there are any plans to change the language that Laravel is written in, however, it would be interesting to see other projects inspired by Laravel, in other languages. :)

**Comment by rhyek** [comment]
A man can dream. Also, a man has no name. 

But seriously, a framework with people like Taylor and the rest of yus behind it written in TS could rule the world. That's all everybody wants to do, so I've heard.
