### ISSUE TITLE
[5.4] Can't use API guard as default

### ISSUE THREAD

**Issue by Ramonlord** [laravel/framework#18388]
- Laravel Version: 5.4
- PHP Version: 7.1.0
- Database Driver & Version: MySQL

### Description:
Can't use Api guard by default in config/auth.php
Throws error 
> Call to undefined method Illuminate\Auth\TokenGuard::attempt()
### Steps To Reproduce:
1. Install laravel 5.4
2. Setup DB, migrate
3. Change  `defaults.guard` to 'api' in auth.php
4. Add `Auth::routes()` to `routes\api.php`
5. Create test user
6. run `php artisan serv`
7. make `curl -X POST -H "Accept: application/json" -F "email=test@test.com" -F "password=123456" "http://127.0.0.1:8000/api/login"`

**Comment by lagbox** [comment]
That `guard` doesn't have an `attempt`. That guard is not for this purpose. It is for use with tokens.

**Comment by Ramonlord** [comment]
Thanks for the reply @lagbox 
Okay, but how then i should implement "login thru API"? I need to have method which take login credentials and return API key, should i implement it manually?

**Comment by lagbox** [comment]
Pretty much just need an end point that can return a token. So you could implement that yourself which would be similar to what the `SessionGuard@attempt` is doing internally, being the checking the credentials with the UserProvider. If the user is validated you could assign a token on the User and return that token.

Thats like the basic idea, but you would probably want to look into something that can handle all of this for you. Oauth might be overkill depending on your needs but we have Laravel Passport if you wanted to look into that.

**Comment by Ramonlord** [comment]
For now i just overwrite `authenticated` and `logout` methods in `LoginController` and check inside if request want json then change behaviour otherwise call standart method.
I worked with the Laravel Passport and JWTAuth pack, but both are qute big for this simple task, i just needed just login(even without chechk for ttl)
Thanks a lot for your help

**Comment by lagbox** [comment]
Clever ;)
