### ISSUE TITLE
withCount method and camel-cased relationships

### ISSUE THREAD

**Issue by ryrobbo** [laravel/framework#18381]
- Laravel Version: 5.4.15
- PHP Version: 7.1
- Database Driver & Version: MySQL

### Description:

QueriesRelationships withCount method does not work with camel-cased relationship names.

### Steps To Reproduce:

Model:

```php
public function userMemberships()
{
    return $this->hasMany('App\Models\Entities\UserMembership', 'membership_guid', 'guid');
}
```

Query:

```php
$memberships = Membership::withCount('userMemberships')->get()
```

View:

```php
{{ $membership->userMemberships_count }} // outputs NULL
```

```php
{{ $membership->userMemberships->count() }} // outputs value
```

Changing the relationship name on the model and in the query to "user_memberships" and then in the view to "$membership->user_memberships_count" fixes the issue. If camel-cased relationships aren't going to work and this is intended behaviour, could be worth updating the documentation with this caveat.

**Comment by devcircus** [comment]
you only need to change the way you are referencing the count in the view. 
```
$membership->user_memberships_count;
```
This works, while still allowing your relationship to be named ```userMemberships``` and your query can still be ```$memberships = Membership::withCount('userMemberships')->get();```

Just tested on fresh install of 5.4
