### ISSUE TITLE
Controller authorizeResource doesn't work for index method

### ISSUE THREAD

**Issue by chanafdo** [laravel/framework#18387]
- Laravel Version: 5.4
- PHP Version: 7

### Description:
When using `authorizeResource` does not add the `can` middleware to `index` method.

In [https://github.com/laravel/framework/commit/d2a41e46949b4cdd45bf0fe3f0fd63dac2ee4858#diff-bb6f96b7b90070077db82955aac3b8a2](https://github.com/laravel/framework/commit/d2a41e46949b4cdd45bf0fe3f0fd63dac2ee4858#diff-bb6f96b7b90070077db82955aac3b8a2) `index` method was removed from `resourceAbilityMap` 

Is there another way to authorize other than calling `authorize` inside the `index` method.

**Comment by mrliptontea** [comment]
In your controller, override `resourceAbilityMap` method to include 'index'.

If you need it for all your resource controllers, add it to `app/Http/Controllers/Controller` which all your controllers should extend by default.
