### ISSUE TITLE
Issue with DB::unprepared()

### ISSUE THREAD

**Issue by santoshachari** [laravel/framework#18390]
- Laravel Version: 5.4.0
- PHP Version: 7
- Database Driver & Version: MySQL 5.7.12

### Description:
I am trying to seed using a .sql file.

### Steps To Reproduce:
While running `DB::unprepared(file_get_content(storage_path('import/1.sql')));`, it throws error, irrespective of what is 1.sql. e.g.

> [Illuminate\Database\QueryException]
> SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to  your MySQL server version for the right syntax to use near 'select now()' at line 1 (SQL: select now();)

**Comment by edenreich** [comment]
Can you share the file?

**Comment by santoshachari** [comment]
1.sql has one line: 
`select now();`

**Comment by edenreich** [comment]
for me when I run it with tinker it returns false. Just curious why dont you use php now() ?

![1](https://cloud.githubusercontent.com/assets/16985712/24057959/a7b155be-0b49-11e7-8115-c21535267643.jpg)

**Comment by santoshachari** [comment]
![screen shot 2017-03-18 at 12 43 03 am](https://cloud.githubusercontent.com/assets/4654290/24059144/e5f66d44-0b73-11e7-8e3c-7aa448bed0d3.png)

The purpose was to run queries. However, since the issue was happening, I was seeing if any other queries would work.

**Comment by santoshachari** [comment]
I see that the codes been modified from 5.3. 

5.4: 
```
 /**
     * Run a raw, unprepared query against the PDO connection.
     *
     * @param  string  $query
     * @return bool
     */
    public function unprepared($query)
    {
        return $this->run($query, [], function ($query) {
            if ($this->pretending()) {
                return true;
            }

            return (bool) $this->getPdo()->exec($query);
        });
    }
```

5.3
```
/**
     * Run a raw, unprepared query against the PDO connection.
     *
     * @param  string  $query
     * @return bool
     */
    public function unprepared($query)
    {
        return $this->run($query, [], function ($**me**, $query) {
            if ($**me**->pretending()) {
                return true;
            }

            return (bool) $**me**->getPdo()->exec($query);
        });
    }
```

**Comment by edenreich** [comment]
It is weird thought:

expected results should be like this..

![1](https://cloud.githubusercontent.com/assets/16985712/24059116/1672ef86-0b4e-11e7-8287-5fec7a783e31.jpg)

I've tried also running DB::raw('Select now();');

I've tried also running DB::connection('mysql')->unprepared('Select now();');

it just returns false :) should actually return the time

**Comment by santoshachari** [comment]
@taylorotwell Sir, big fan. 
I see that DB::unprepared() doesn't work in importing SQL files... Do you recommend another way?

**Comment by edenreich** [comment]
@santoshachari hey santos its not that its not working with sql files, its just returns false or true:

if you for instance change the return of the unprepared() method to:

return $this->getPdo()->query($query)->fetchObject();
or
return $this->getPdo()->query($query)->fetchAll();
or
return $this->getPdo()->query($query)->fetch();

you will actually get results rather than true or false.

Not really sure if there is a demand for this or if its a breaking change, as far as I know this method is not used very often.

**Comment by santoshachari** [comment]
@edenreich, It still seems to be not working.  I am able to import the sql file through mysql command line directly. 

Do you suggest perhaps another way to import .sql

```
>>> DB::unprepared(file_get_contents(storage_path('import/countries.sql')));
Illuminate\Database\QueryException with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '﻿INSERT INTO `countries` (`id`, `enabled`, `code3l`, `code2l`, `name`, `name_o' at line 1 (SQL: ﻿INSERT INTO `countries` (`id`, `enabled`, `code3l`, `code2l`, `name`, `name_official`, `flag_32`, `flag_128`, `latitude`, `longitude`, `zoom`)
VALUES
	(1,1,'AFG','AF','Afghanistan','The Islamic Republic of Afghanistan','AF-32.png','AF-128.png',33.98299275,66.39159363,6)
```

**Comment by edenreich** [comment]
@santoshachari hard to tell if you make a screenshot I can check what you did wrong but according to the error message you have syntax error from MySQL.

is it only this query ? does other queries runs ok?

**Comment by edenreich** [comment]
@santoshachari replace this with with the code from before and you should be able to read and insert aswell
```
if(preg_match('/^select/', $query)) {
	return $this->getPdo()->query($query)->fetchObject();
} else {
	return (bool) $this->getPdo()->exec($query);
}
```

**Comment by santoshachari** [comment]
@edenreich Thanks for this. There was not issue in syntax, and I was able to run the same queries with in myqsl command. 

I can modify the package code. Just to clarify, so there isn't a way one can run sql import directly through the framework?

**Comment by pilot911** [comment]
As i know - in Laravel you can run one SELECT at time with $this->getPdo()->query($query).
