### ISSUE TITLE
 php artisan command getting error

### ISSUE THREAD

**Issue by animeshsa** [laravel/framework#18396]
- Laravel Version: 5.2.45
- PHP Version:5.5.9
- Database Driver & Version: mysql 5.0.11

### Description:
running > php artisan command getting this error
PHP Parse error:  syntax error, unexpected '->' (T_OBJECT_OPERATOR) in C:\xampp\htdocs\ctw-portal\vendor\ignasbernotas\laravel-model-generator\src\Commands\MakeModelsCommand.php on line 121

  [Symfony\Component\Debug\Exception\FatalErrorException]
  syntax error, unexpected '->' (T_OBJECT_OPERATOR)

## Steps To Reproduce:

* after running composer update getting this error
* checkout older version of code running that running fine also get this error, I have tried with removing entire db, vendor, composer.lock,bootstrap cache folder files, but nothing solve this. lase tried composer update --no-dev, composer update --no-script, composer dumpautoload every thing

**Comment by salomoni** [comment]
This is issue with https://github.com/ignasbernotas/laravel-model-generator not with Laravel

Update PHP version to 7 fixes it

**Comment by lagbox** [comment]
This isn't even Laravel. This is a 3rd party package.

**Comment by animeshsa** [comment]
thanks

**Comment by lagbox** [comment]
Good luck, hopefully the package author can help you out. :-)

**Comment by lagbox** [comment]
@animeshsa You would need a higher php version to use that it would seem.
