### ISSUE TITLE
Bug generating listeners

### ISSUE THREAD

**Issue by jhoopes** [laravel/framework#18392]
- Laravel Version: 5.4.x-dev
- PHP Version: PHP 7

### Description:

Working with the dev version and ran into a bug introduced yesterday: d767c876f1813ade3973757f64bfe464bd5d5e03

adding a short 'q' option overlaps with the already present 'q' option for running the command quietly.  This causes the command to fail, as well as the event:generate command as it makes use of that.

### Steps To Reproduce:

add events to EventServiceProvider, run php artisan event:generate or run php artisan make:listener directly

I'd make a PR, but not sure what we'd want the short option to become.

**Comment by themsaid** [comment]
Thank you, that was reverted in https://github.com/laravel/framework/commit/74cd4cd1f4458fcc1c6ad1f526025c2a5aab01
