### ISSUE TITLE
Queue: Instance variables not available from failed() function

### ISSUE THREAD

**Issue by codeaken** [laravel/framework#18398]
- Laravel Version: 5.3.30
- PHP Version: 7.0.11

### Description:
I have a job that communicates with servers and also creates a database row in its handle() method. If something goes wrong with the server communication I want to remove the row from the failed() method.

I store the created database row as an instance variable in the job class. But when failed() gets called this variable is set to null. Any instance variables created in the construct() function is available but not any created inside handle().

### Steps To Reproduce:

Here is a small job that demonstrates what I mean:

```php
class MyJobClass extends Job implements ShouldQueue
{
    use InteractsWithQueue, SerializesModels;

    private $fromConstruct;
    private $fromHandle;

    public function __construct()
    {
        Log::info('Construct');

        $this->fromConstruct = 'From Construct';
    }

    public function handle()
    {
        Log::info('Handle');

        $this->fromHandle = 'From Handle';
        
        // Will print From Handle to the log
        Log::debug($this->fromHandle);  
    }

    public function failed(\Exception $exception)
    {
        Log::info('Failed');

        // Will print From Construct to the log
        Log::debug($this->fromConstruct);  
        
        // Will print empty value (null) to the log
        Log::debug($this->fromHandle);  
    }
}
```

**Comment by sisve** [comment]
It sounds like you should be using database transactions to either persist all your changes, or roll them back in case of exceptions.

**Comment by themsaid** [comment]
When the job fails, Laravel unserializes the job class and calls the `failed` method directly, `handle()` will not be executed.

**Comment by lucasctd** [comment]
It would be good if the job gets updated when it fails thus you don't need to the whole task again.
In my case, I was passing a collection with some texts I would like to analyze through Google Natural Language API. If I get 100 texts and in the 50th one, the job fails, when I retry the job it will reanalyze the first 50 texts again. The only way I found to not do the same thing again was failing the job and dispatching a new one with the updated list (with the text I haven't analyzed yet).

**Comment by nagaralsomesh** [comment]
@codeaken did you find any solution for this?...I also got the same issue for me i also wanted to access global variable from the job in the failed function as you are doing....Can you please tell me did you find any solution for this?

**Comment by ZawHtettnaing** [comment]
If someone got solution for this. Please share :). I am also facing the same issue.
