### ISSUE TITLE
Tag new 5.3 patch version with bugfixes

### ISSUE THREAD

**Issue by ModernArtisan** [laravel/framework#18405]
Can you update 5.3 branch to new patch version with these bugfixes - https://github.com/laravel/framework/commit/666a752dd9679448905a38f2a975a881060c4178

**Comment by vlakoff** [comment]
Issue should be renamed to "support 5.3 if it is allegedly still supported (or tell people that yeah, they'll have to migrate their applications every 6 months)".

**Comment by vlakoff** [comment]
As a matter of fact, 5.3 has been released on 23 Aug 2016, that's seven months...

So technically, it's already on "extended support" (security fixes only) and it shouldn't be expected to receive bugfixes such as those you referenced (#17983)...

(and yeah, I'm tired of constantly migrating)

**Comment by vlakoff** [comment]
Though, #17983 had been made in the six-month main support window.

(it's already fugacious, don't make it shorter :trollface:)

**Comment by themsaid** [comment]
Thanks, will tag a release soon.
