### ISSUE TITLE
Blade escape htmlspecialchars in pluck()->toArray() function in select field

### ISSUE THREAD

**Issue by mirbatworks** [laravel/framework#18402]
- Laravel Version: 5.4.15
- PHP Version: 7.03
- Database Driver & Version: MySQL
- Mccool auto presenter
- Baum packages for ordering: 1.1.1

I want to nested my subpage inside select option field. I'm using presenter for this:
Method in presenter:
```php
public function paddedTitle()
	{
		return str_repeat('&nbsp;', $this->wrappedObject->depth * 4).$this->wrappedObject->title;

	}
```
In controller I select page for ordering - $orderPages variable:
```php
public function create(Page $page)
    {
        $templates = $this->getPageTemplates();

        $orderPages = $this->pages->all();

        return view('admin.pages.form', compact('page', 'templates', 'orderPages'));
    }
```
Than in form using laravel/collective I create select field:
```php
{!! Form::select('orderPage', ['' => ''] + $orderPages->pluck('paddedTitle', 'id')->toArray(), null, ['class' => 'form-control', 'id' => 'orderpages'], ['aria-label' => 'orderPage-addon'])  !!}
```
In pluck() function 'paddedTitle' is title retrieved from Presenter
Result is this:
![screenshot from 2017-03-18 13-20-23](https://cloud.githubusercontent.com/assets/16490966/24072041/e0b7b25e-0bdf-11e7-8e7a-9363c696f559.png)
Page source:
```html
<option value="3">&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;Sub Page</option>
```
I use similar method on displaying nested list of pages where everything is fine. Function from Presenter:
```php
public function linkToPaddedTitle($link)
	{
		$padding = str_repeat('&nbsp;', $this->wrappedObject->depth * 4);

		return $padding.link_to($link, $this->wrappedObject->title);
	}
```
Displaying ordered Pages in Blade:
```php
@foreach($pages as $page)
  <tr>
	 <td>{!! $page->linkToPaddedTitle(route('pages.edit', $page->id)) !!}</td>
  </tr>
@endforeach
```
Result nested Sub Page as expected:
![screenshot from 2017-03-18 13-49-03](https://cloud.githubusercontent.com/assets/16490966/24072154/98b14d96-0be2-11e7-8030-0401977ee6e9.png)
I older version of Laravel (5.2) I use lists() function instead of pluck() and everything is works fine so I think pluck() is a problem.
Is anybody have idea how to solve this problem with nesting pages in select option field?

**Comment by lagbox** [comment]
Why would `pluck` be the problem? 
The `Form` package isn't Laravel. That is your problem. It escapes the values. It calls `escapeAll` which calls `htmlentities`.
