### ISSUE TITLE
ConvertEmptyStringsToNull

### ISSUE THREAD

**Issue by ZeyadMounir** [laravel/framework#18414]
- Laravel Version: 5.4

### Description:
I am facing an annoying issue. When I am using required_if and string validation, if required_if is false, it doesn't pass string validation, because of the null value. If I add nullable to the validation, it passes required_if, even if the condition is true.
I think we need to add attribute "except" to ConvertEmptyStringsToNull like with TrimStrings.

**Comment by ankurk91** [comment]
See #17663

**Comment by ZeyadMounir** [comment]
I haven't seen a good solution there.
I overrode the ConvertEmptyStringsToNull Class and it worked fine.
![image](https://cloud.githubusercontent.com/assets/16030521/24089606/a92e38ba-0d49-11e7-9d64-14618526b3c1.png)

**Comment by themsaid** [comment]
That was fixed in https://github.com/laravel/framework/pull/18376
