### ISSUE TITLE
Middleware ConvertEmptyStringsToNull have problem

### ISSUE THREAD

**Issue by quoclong5** [laravel/framework#18428]
- Laravel Version: 5.4.15
- PHP Version: 7
- Database Driver & Version: N/A

### Description:
Create a rules
Rules: [ 'link' => 'url' ]

Case 1:
Input: [ 'link' => null ]
Result: fail, The link format is invalid.
Expect: pass

Case 2:
Input: [ 'link' => '' ]
Result: pass
Expect: pass

### Notes
Maybe problem with the \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull

**Comment by ankurk91** [comment]
See #17663
