### ISSUE TITLE
Cannot set recipient name in notification mail

### ISSUE THREAD

**Issue by SteffenTallieu** [laravel/framework#18439]
According to the L5.3 documentation [here](https://laravel.com/api/5.3/Illuminate/Notifications/Messages/MailMessage.html), it is only possible to set the recipient email address of a notification mail, and not the recipient name.
In the L5.4 documentation [here](https://laravel.com/api/5.4/Illuminate/Notifications/Messages/MailMessage.html), the to() method has even disappeared completely.

You would expect to be able to set the name of the recipient in the mail header, similar as with the old Mail::to($address, $name).

**Comment by devcircus** [comment]
If you use [mailables for your notification emails](https://laravel.com/docs/5.4/notifications#mail-notifications), you can specify the name using the "to" method of the mailable:
```
    public function toMail($notifiable)
    {
        return (new Mailable())->to($this->user->email, 'John Doe');
    }
```
![email_with_name](https://cloud.githubusercontent.com/assets/18542852/24158627/d7d1f60c-0e2a-11e7-9225-d75fd4d714d9.jpg)

I guess it's just a workaround, but thought it may help.

**Comment by tpraxl** [comment]
You can also do this:

```
Mail::to([['name' => $model->to->name, 'email'=> $model->to->email]])->send(
                (new MyMailable($content))
            );
```

This was a PITA to find out. Mail::to expects an array of to recipients and furthermore it expects the key (or object property) 'email' instead of 'address'.

**Comment by moreirapontocom** [comment]
Thank you @tpraxl. It helps a lot.

**Comment by danmichaelo** [comment]
Another option is to set the receiver in the Mailable, I find that syntax a bit less confusing:

```php
    /**
     * Build the message.
     *
     * @return $this
     */
    public function build()
    {
        $sender = ...
        $receiver = ...

        return $this
            ->from($sender->email, $sender->name)
            ->to($receiver->email, $receiver->name)
            ...
            ;
    }
}
```

and then just do `Mail::send(new MyMailable(...))`

**Comment by highstrike** [comment]
Just want to point out, after wasting 1 hour on this, and in Laravel 6 at least, the method `routeNotificationForMail` on the model which is used [to customise the recipient](https://laravel.com/docs/6.x/notifications#customizing-the-recipient) can, in fact, be an array (not only a string as seen in the documentation)

Therefore, you can specify the field responsible for the recipient email as key and field responsible for the recipient name as value like so

```
    /**
     * Route notifications for the mail channel.
     *
     * @param Notification $notification
     * @return array
     */
    public function routeNotificationForMail($notification) : array {
        return [
            $this->the_email => $this->the_name
        ];
    }
```

where `the_email` and `the_name` are fields on the model (and in a table)

![image](https://user-images.githubusercontent.com/2379538/71091521-edbf0880-21ad-11ea-968e-5ebeb149f8c0.png)
