### ISSUE TITLE
Some issue with redirect in authentication

### ISSUE THREAD

**Issue by sausin** [laravel/framework#18436]
- Laravel Version: 5.4.15
- PHP Version: 7.0.15
- Database Driver & Version:
pdo_mysql, mysql-5.7.17

### Description:
redirectTo property has some trouble

### Steps To Reproduce:
1. Change 'redirectTo' to something other than '/home' in LoginController.php
2. Make sure user is logged out and go to '/login' page
3. Attempt login with credentials, you should be redirected properly
4. Logout again and this time set your user to auto login via the routes page. So something like
```Auth::loginUsingId(xxx)```
5. Go to '/login' page again and this time get redirected to '/home' instead

I do understand that authenticating via routes file is only convenience during development, but the concern is if this improper redirection could potentially occur in other unforeseen but desirable scenarios.

**Comment by devcircus** [comment]
These are 2 completely unrelated things. The redirect in the login controller is where to redirect a user after they login. The other redirect you're talking about deals with where to send a logged in user if they try to access a page that is only for guests. This second redirect is in App\Http\Middleware\RedirectIfAuthenticated. 
Again, these have 2 different use cases. If you want them to match, you'll need to make the necessary changes.

**Comment by sausin** [comment]
@devcircus Thanks, that does make sense. I will close the issue
