### ISSUE TITLE
Illuminate\Auth\Access\AuthorizationException always returns HTML responses even if the request wants json in return

### ISSUE THREAD

**Issue by morloderex** [laravel/framework#18431]
- Laravel Version: 5.4.15
- PHP Version: 7.1.2
- Database Driver & Version: Not relavent 

### Description:
I would expect `\Illuminate\Auth\Access\AuthorizationException` to return a json response if the request wants JSON but a regular HTML response is always returned.

What I would expect of this response is a JSON structure looking something like the fallowing:

```
{
    "error": [
        "This action is unauthorized."
    ]
}
``` 

### Steps To Reproduce:
Create any route and throw a new \Illuminate\Auth\Access\AuthorizationException exception.

**Comment by edenreich** [comment]
You can use the report method in App\Exceptions just before the exception is registered in laravel build-in exceptions and do the following:

if($e instance of Illuminate\Auth\Access\AuthorizationException) {
 // return what whatever you want
}

I think that should work

**Comment by morloderex** [comment]
I have done this myself. But it just feels messy.. :)
