### ISSUE TITLE
Soft Delete not working when Using Accessor to Hash the Column ID

### ISSUE THREAD

**Issue by osroflo** [laravel/framework#18443]
- Laravel Version: 5.4
- PHP Version: 5.6.23
- Database Driver & Version:

### Description:
The soft delete is taking the hashid value instead the real column id, causing this error:

```
QueryException in Connection.php line 647:

SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "37KgBnyp" 

(SQL: update "test" set "deleted_at" = 2017-03-21 14:59:45 where "id" = 37KgBnyp)
```

### Steps To Reproduce:
I have a requirement to hash the id.  I should not expose the real integer id. For example the hashed value for the id=2 will be 37KgBnyp.

I am using a model accessor to format the integer id to a string hashid (using php hashids library): 

```php

<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Lib\HashId;

class Test extends Model
{
    use SoftDeletes;

    protected $table = "test";
    protected $dates = ['deleted_at'];
 
    public function getIdAttribute($value)
    {
        return HashId::encode($value);
    }
}
```

To update a record I am passing the encoded id using a route then decoded it in the controller and then update any value (It is working great):
```php
public function update(Request $request, $id)
    {
        $decoded_id = HashId::decode($id);

        $test= Test::find($decoded_id);
        $test->name = $request->input('name');
        $test->description = $request->input('description');
        $test->save();

        return $test;

    }
```

The problem is when I try to soft delete the record:

```php
    public function delete($id)
    {
        $decoded_id = HashId::decode($id);

        $test = Test::find($decoded_id);
        $test->delete();
    }

```

Also, I tried to use destroy:
```php
    public function delete($id)
    {
        $decoded_id = HashId::decode($id);
        Test::destroy($decoded_id);
    }

```

Either by using delete() or destroy(id), I get the following ERROR:

```
QueryException in Connection.php line 647:

SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "37KgBnyp" 

(SQL: update "test" set "deleted_at" = 2017-03-21 14:59:45 where "id" = 37KgBnyp)
```

NOTE:

I am sure that the decode() is working properly, because I am using the same method to update the record and to do hard delete:
```php 
Test::destroy(HashId::decode($id));
```

Looks like the soft delete is doing 2 queries:
```sql
-- query #1 to grab the row by passing the decoded id
SELECT name FROM test WHERE id=2

-- query #2 to update the row updated_at = date time.
UPDATE test SET deleted_at='2017-03-21 14:59:45' WHERE id=37KgBnyp 
```

In some way the Laravel SoftDelete is grabbing the ID returned by the accessor instead to use the ID passed through the find() or destroy()  method.

When I am updating a record it is taking the ID passed by find(). If normal hard delete is used instead soft delete, everything works great.

Is this a bug in soft delete? Or why it is not using the id that I am passing using find(id) or destroy(id).

**Comment by Dylan-DPC** [comment]
How will it know how to get your id from a hashed ID?

**Comment by osroflo** [comment]
I am decoding the the hashid to get the real id
```
$decoded_id = HashId::decode($id);
Test::destroy($decoded_id);
```

As I said, everything works if I am not using the soft delete. I can update, delete (hard delete) but the only problem is with the soft delete.

**Comment by Dylan-DPC** [comment]
This isn't a bug. Laravel won't be aware of how to go back from your hashed Id to your normal ID stored in the database. 

Just curious: Why you didn't use the hashed IDs as your primary key directly? 

If you want to solve this problem try asking in laravel forums or Larachat slack channel

**Comment by themsaid** [comment]
@osroflo I don't recommend mutating the id like this, you're hiding your actual ID forever from Eloquent, instead try using the hashed id as the primary key or use another property name `hashed_id` to access the hashed version.
