### ISSUE TITLE
Unable to softdelete pivot tables

### ISSUE THREAD

**Issue by emabusi** [laravel/framework#18444]
- Laravel Version:  5.4.15
- PHP Version: 7.0.9
- Database Driver & Version: 5.0.12

### Description:
When detaching a model with many to many relationship with both models using soft delete, and the pivot table has softdeletes column. The pivot row column is completely deleted instead of being soft deleted. This issue was once mentioned here https://github.com/laravel/framework/issues/14008

**Comment by Dylan-DPC** [comment]
I don't see this option being added into the framework based on discussion in the linked issue

**Comment by themsaid** [comment]
Going to point to the comment I wrote on the issue: https://github.com/laravel/framework/issues/14008#issuecomment-226899679

However feel free to open an issue on laravel/internals since it's the place where we keep suggestions and feature requests:https://github.com/laravel/internals
