### ISSUE TITLE
artisan migrate --pretend creates migrations table

### ISSUE THREAD

**Issue by bram1028** [laravel/framework#18453]
- Laravel Version: 5.4.15
- PHP Version: 7.0.15
- Database Driver & Version: MS SQL 2016

### Description:
When you run ``artisan migrate --pretend``, it generates an empty ``migrations`` table.

### Steps To Reproduce:
1. Delete the ``migrations`` table.
2. Run ``artisan migrate --pretend``

**Comment by fernandobandeira** [comment]
Even when pretending to run migrations the migrator will need to connect to the database and check the migrations table to see which migrations already ran, so I don't see this as a bug since this table is needed to serve as a repository for the migrations it's a basic setup...

**Comment by bram1028** [comment]
Just seems like if the table doesn't exist, ``getRan()`` should simply return an empty array so that all migrations are generated. It's not really "pretend" otherwise.

For my use case I'm not using Laravel's migrations, so I guess I could make my own console command to generate the SQL and bypass this.

**Comment by shyce** [comment]
Why was this closed? I literally only use Laravel to make database tables. I don't want to have to start a database with docker just to have a blank migrations table. Just return [] ?!
