### ISSUE TITLE
[5.3] Auth session lost on non local machine

### ISSUE THREAD

**Issue by samfrjn11** [laravel/framework#18461]
- Laravel Version: 5.3.30
- PHP Version: 7.0.1
- Session driver: file

### Description:
Hi,

I've been developing a CRM application for a couple of months now. I upgraded from L5.2 to 5.3 (currently 5.3.30 installed) a couple of months ago. Now I wanted to show the CRM to one of my collegues on their computer, but when I try to login, it redirects to the /dashboard, but then get's 302 redirected (unauthenticated) back to the login form. After a few tries I finally get to the /dashboard.

Then when I browse the application, I randomly get logged out and redirected to the login page.

I'm hosting on a Mac MINI using php -S 192.168.1.20:8888 -t public. If I use the app on this Mac Mini, everything works fine. But as soon as I try on another computer I'm having issues.

Any ideas? Been searching the internet for a week now, I'm out of ideas and out of energy...

Thanks in advance!

**Comment by edenreich** [comment]
Hard to troubleshooting this without source code, my guess would be you have some kind of middleware setup.
does your routes accepts 'auth' or 'guest' middleware ?

https://laravel.com/docs/5.4/middleware

**Comment by themsaid** [comment]
Sorry but this doesn't look laravel-related, I suggest you try asking on the forums.

**Comment by samfrjn11** [comment]
From what I already read on the internet and from my point of view this is session-related, so it is laravel-related, isn't it?

@edenreich Yes, they use auth middleware
