### ISSUE TITLE
$_ENV conflict, can we prefix?

### ISSUE THREAD

**Issue by axeloz** [laravel/framework#18470]
- Laravel Version: 5.4
- PHP Version: 7.1

### Description:

I just came across an issue with the Laravel settings being set into the environment variables. 
My Laravel instance (using its own .env file) has to run a PHP exec() command (let's say `php artisan migrate`) on an other Laravel instance (with its own .env file). 

The destination Laravel is using the source Laravel variable and therefore runs the migration into the source database. I'm looking for a way to unset temporarily  the env variables but I was thinking: 
wouldn't it be a good idea for Laravel to prefix automatically all the env variables? 
In the .env:
`DB_HOST = localhost`
In the $_ENV:
`LARAVEL_DB_HOST = localhost`
This makes it easier to unset all Laravel variables, not ALL env variables.

Thanks

**Comment by iget-master** [comment]
Just change you config files to use the env that you want. 

Eg.:

update `config/database.php` look for

```
'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
```

Note that the `DB_HOST` env variable is being used. You can replace it by whatever you want.

**Comment by themsaid** [comment]
Yes you may replace the values any way you want

**Comment by axeloz** [comment]
Hello, 

thanks for the reply. I know I can rename the values but there may be quite a lot of things to rename. My point was to include this mechanism in Laravel core when saving into $_ENV
Cheer

**Comment by mosaferkarbala** [comment]
i faced same issue and temporarily solve it by changing the name in .env and all config files. i also search and find some way of rewriting getEnv() helper function but it doesn't work on laravel9.
i appreciate if any one has any solution to share with us
