### ISSUE TITLE
[Feature] Better management of subfactories than closure

### ISSUE THREAD

**Issue by ThibaudDauce** [laravel/framework#18472]
One very common way to use subfactories in Laravel is to make a Closure and call the factory inside:

```php
$factory->define(App\Phone::class, function (Faker\Generator $faker) {
    return [
        'user_id' => function() {
            return factory(App\User::class)->create()->id;
        },
        'phone' => $faker->phoneNumber,
    ];
});
```

The main disadvantage of this approach is that the `create()` method is hard-coded. If I want to use this factory without the `DatabaseMigrations` and a call to `make()` my testing database will be polluted.

```php
factory(App\Phone::class)->make();
$this->assertEquals(0, App\User::count()); // fail, there is one user in my database
```

I think the best API for the users is to use the same key as the name of the relation:

```php
$factory->define(App\Phone::class, function (Faker\Generator $faker) {
    return [
        'user' => factory(App\User::class),
        'phone' => $faker->phoneNumber,
    ];
});
```

```php
$phone = factory(App\Phone::class)->make();
$this->assertEquals(0, App\User::count()); // success, the make function is called on the factory
$this->assertInstanceOf(App\User::class, $phone->user); // success, the relation is populated with `setRelation`
$this->assertNull($phone->user_id); // success, this is the only drawback
```

It will not work well with the `raw()` method. The array will not contain neither a `user` key, nor a `user_id` key.

If it's a wanted feature, *I can submit a pull request*. The `FactoryBuilder` will inspect the model to get the `Relation`, create or make a new model and set the appropriate keys (with `getOwnerKey()`, `getForeignKey()`…). 

PS: I noticed there is no test for the `Factory` and `FactoryBuilder`… :-(

PS2: it could also work with Collection for `HasMany` relationships:

```php
$factory->define(App\User::class, function (Faker\Generator $faker) {
    return [
        'phones' => factory(App\Phone::class, 3),
    ];
});
```

PS3: it could also work with suboverride attributes:

```php
$phone = factory(App\Phone::class)->make([
    'user' => [
        'email' => 'john@example.com',
    ]
]);
$this->assertEquals('john@example.com', $phone->user->email); // success
```

**Comment by Dylan-DPC** [comment]
Sounds more complicated than the the intial way

**Comment by ThibaudDauce** [comment]
@Dylan-DPC 

This:

```php
$factory->define(App\Phone::class, function (Faker\Generator $faker) {
    return [
        'user' => factory(App\User::class),
        'phone' => $faker->phoneNumber,
    ];
});
```

is more complicated than this:

```php
$factory->define(App\Phone::class, function (Faker\Generator $faker) {
    return [
        'user_id' => function() {
            return factory(App\User::class)->create()->id;
        },
        'phone' => $faker->phoneNumber,
    ];
});
```

Yes it's more complicated in the implementation but not for the public API. And it's still possible to use the old way…

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.

**Comment by ThibaudDauce** [comment]
Thanks, it's done here https://github.com/laravel/internals/issues/485 :-)
