### ISSUE TITLE
Laravel-Mix NPM Package Update

### ISSUE THREAD

**Issue by AbbyJanke** [laravel/framework#18479]
- Laravel Version: 5.4.16
- Mac OS 10.12.4 Beta

### Description:

It looks like package.json was just updated a few days ago on laravel/laravel to have laravel-mix 0.8.3 however it seems that version is outdated and causing errors among a new install of Laravel. I updated my package.json to be 0.9.2 and now I am having no issues.

### Steps To Reproduce:
1. create new laravel application
2. npm install
3. npm run dev

**Comment by themsaid** [comment]
https://github.com/laravel/laravel/pull/4188

Thank you.
