### ISSUE TITLE
New helper when

### ISSUE THREAD

**Issue by rorc** [laravel/framework#18477]
For output html, often need to add classname depending of different terms, for example:
```
<div class="{{ Request::has('param') ? 'has-success' : '' }}">some html</div>
```
New helper function will do this more clearly and conveniently:
```
<div class="{{ when(Request::has('param'), 'has-success') }}">some html</div>
```

**Comment by Dylan-DPC** [comment]
@rorc we discuss proposals in https://github.com/laravel/internals/ repo. Create an issue there.

**Comment by rorc** [comment]
@Dylan-DPC Done, thx)
https://github.com/laravel/internals/issues/487
