### ISSUE TITLE
New method whereBetweenDate for QueryBuilder

### ISSUE THREAD

**Issue by rorc** [laravel/framework#18480]
Will be good convert:
```php
$builder->whereBetween(DB::raw('date(created_at)'), ['2017-01-03', '2017-02-10']);
```
into:
```php
$builder->whereBetweenDate('created_at', ['2017-01-03', '2017-02-10']);
```

**Comment by mg-freelancer** [comment]
@taylorotwell  may I work in this feature ?

**Comment by Dylan-DPC** [comment]
@mg-freelancer we discuss proposals in the internals repo. You shold create the issue there: https://github.com/laravel/internals

**Comment by eskrano** [comment]
So how about this

`
$date= Carbon::now()->addDays(10);

SomeModel::whereBetween('created_at',[
    $date->copy()->startOfDay(),
    $date->copy()->endOfDay()
])->get()` ?

**Comment by Dylan-DPC** [comment]
@eskrano better to discuss on the issue in internals or the PR

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.

Thanks anyways :)

**Comment by rorc** [comment]
@themsaid Done)
