### ISSUE TITLE
Foreign keys based on the final table name not the class name

### ISSUE THREAD

**Issue by meNESS** [laravel/framework#18500]
- Laravel Version: 5.4.16
- PHP Version: 7.1.2
- Database Driver & Version: MySQL 5.7.17

### Description:
```php
     /**
     * Get the default foreign key name for the model.
     *
     * @return string
     */
    public function getForeignKey()
    {
        return Str::snake(class_basename($this)).'_'.$this->primaryKey;
    }
```
Above method makes foreign keys based on the model name, the problem here is models names are not always the tables names (I mean the user has the ability to define different names by modifying `$table` property), so it should make those based on the final table name, not the class name.

**Comment by themsaid** [comment]
It's just a convention for the foreign key name of the model, if you want something different you can change that while declaring the relationship.
