### ISSUE TITLE
[5.4] Different validation fails when compared attribute not set

### ISSUE THREAD

**Issue by amochohan** [laravel/framework#18514]
- Laravel Version: 5.4
- PHP Version: 7.0
- Database Driver & Version: MySQL 5.6

### Description:

When using the `different` validation rule, validation fails when the compare attribute does not exist. For example:

```
    'name' => 'different:surname',
    'surname' => 'different:name',
```

The following example works as expected:

```
    $trans = $this->getIlluminateArrayTranslator();
    $v = new Validator($trans, ['name' => 'Taylor', 'surname' => 'Otwell'], ['name' => 'different:surname', 'surname' => 'different:name]);
    $this->assertTrue($v->passes());
```

However, If I only provide a name (and not a surname) this validation fails:

```
    $trans = $this->getIlluminateArrayTranslator();
    $v = new Validator($trans, ['name' => 'Taylor'], ['name' => 'different:surname', 'surname' => 'different:name]);
    $this->assertTrue($v->passes()); //This fails
```

Technically, the name (Taylor) is different to the surname in both cases (Otwell, and `null`) so I would expect this to pass.

Changing line 380 of `ValidatesAttributes` from:

    return isset($other) && $value !== $other;

to 

    return $value !== $other;

fixes this issue.

I can send a PR and update the docs but want to confirm whether this change in behaviour is the accepted consensus, first.

**Comment by Dylan-DPC** [comment]
@amochohan maybe your value you are comparing with is null?

**Comment by Dylan-DPC** [comment]
@amochohan update on this?

**Comment by hulkur** [comment]
+1, for my own app I created `different_if_present` filter. I use it together with `required_without` filter.

not existing is different to anything else

**Comment by themsaid** [comment]
Feel free to PR the proposed change, personally I don' see it as a bug, so please submit to 5.5 since this might break people apps.
