### ISSUE TITLE
[5.4] postgresql where greater than not work on float values with jsonb colums

### ISSUE THREAD

**Issue by lkmadushan** [laravel/framework#18524]
- Laravel Version: 5.4
- PHP Version: 7.1
- Database Driver & Version: PostgreSQL 9.5

### Description:
| id |     data     |
|----|:------------:|
| 1  | {value: 7.1} |
| 2  | {value: 7.2} |
| 3  | {value: 7.3} |
| 4  | {value: 7.4} |
| 5  | {value: 6.1} |
| 6  | {value: 6.2} |
| 7  | {value: 6.3} |

```
Example::where('data->value', '>', 7.2)->get(); 
```
doesn't return records, value greater than 7.2 only, it also return values containing 6

## To fix this, 

Need to change the query based on the value passed
```
select * from example where ("data"->>'value')::float > 7.2
```
But I don't know how to do this.

**Comment by tillkruss** [comment]
Try using `whereRaw(...)` or `DB::raw(...)`.
