### ISSUE TITLE
MigrateCommand clobbers default DB connection config

### ISSUE THREAD

**Issue by cgwyllie** [laravel/framework#18522]
- Laravel Version: 5.2.x (from looking at sources, seems to still affect in 5.4.x)
- PHP Version: 7.0
- Database Driver & Version: MySQL 5.7.17 (PDO)

### Description:

When running migrations through the `Artisan::call` facade with the `--database` option, the `database.default` connection is overridden after the migrations have completed.

For example:

```php
config('database.default'); // 'mysql'
Artisan::call('migrate', ['--database' => 'foo']);
config('database.default'); // 'foo'
```

Looks like this happens because the `MigrationCommand::fire()` method doesn't reset the connection config after it has been clobbered by https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Migrations/Migrator.php#L379.

### Steps To Reproduce:

- Run migrations programmatically with the Artisan facade on an alternate database connection
- Attempt to continue using the default database connection for other queries

### Expected Behaviour:

I would expect the `database.default` connection to be left exactly as it was configured prior to running the migration command with Artisan.

**Comment by legshooter** [comment]
Hey, what's the reason for closing this? I'm on Laravel 5.6 and was hit with this exact issue.

**Comment by legshooter** [comment]
Hey @themsaid, can you elaborate on what's the reason for closing this? I'm on Laravel 5.6 and was hit with this exact issue.

**Comment by devcircus** [comment]
The issue was reported on 5.2 & 5.4 which are no longer supported. If an issue exists on a currently supported version, please submit an up-to-date bug report with details so it can be tracked properly.
