### ISSUE TITLE
Request object mutability issue

### ISSUE THREAD

**Issue by MartanLV** [laravel/framework#18531]
- Laravel Version: 5.1 and 5.4 (both has this issue)
- PHP Version: 7
- Database Driver & Version: 5.7 mysql

### Description:
Hard to modify request. I wanted to intercept any request having some value of *callback* and continue via redirect headers. Function `fullUrl()` of a modified request returns original value which is unexpected.

### Steps To Reproduce:
Try out this middleware. 
```PHP
namespace App\Http\Middleware;
use Closure;
class Test
{
    public function handle($request, Closure $next, $guard = null)
    {
        // so request is http://laravel.com?foo=bar&callback=123
        if ($callback = $request->get('callback')) {
            $request->query->remove('callback');
            $qp = $request->query->all();
            // an array as expected! count($qp) == 1
            $requestAsIf = $request->duplicate($qp);
            // duplicate all but set new queryBag
            
            $stillTheRequestOriginalUrl = $requestAsIf->fullUrl();
            // would expect http://laravel.com?foo=bar, right?!
            $resp = $next($requestAsIf);
            // ..
            #! $resp->headers->set('Location:' , 'foo');
            #! $resp->withCookie('callback' , $callback, 4200);
            return $resp;
        }
        return $next($request);
    }
}
```

**Comment by themsaid** [comment]
`fullUrl()` builds the URL query string using server's `QUERY_STRING` and that's why `$request->query->remove('callback')` won't take effect on the URL.

I don't think there's a way to mutate the request URL.

Anyways this all happens inside the Symphony HTTP component and Laravel is based on that, so I'd say this is not a laravel issue, maybe try the forums for some ideas on how to achieve what you need.

**Comment by devcircus** [comment]
See [this issue](https://github.com/symfony/symfony/issues/11935) on the symfony repo.

**Comment by MartanLV** [comment]
All clear. I see, Symfony wouldn't admit.

**Comment by themsaid** [comment]
Closing this issue then :)
