### ISSUE TITLE
[L5.4] Eloquent Builder getModels() function bug

### ISSUE THREAD

**Issue by overg** [laravel/framework#18538]
https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Builder.php#L461

Most likely **$this->hydrate()** should be used, instead of **$this->model->hydrate()**

**Comment by Dylan-DPC** [comment]
@overg can you make a PR that rectifies the bug?

**Comment by themsaid** [comment]
I guess it was done that way to allow you to define a `hydrate` method in your model if you want to change behaviour.

Closing since it's not a bug in the core, feel free to ping me though.
