### ISSUE TITLE
Certain iPhone photos fail Laravel validation

### ISSUE THREAD

**Issue by bhartvigsen** [laravel/framework#18541]
- Laravel Version: 5.4.15
- PHP Version: 7.0.15-0ubuntu0.16.04.4
- Database Driver & Version: N/A

### Steps To Reproduce:
Use this validation string:
                $validator = Validator::make($request->all(), [
                        'image' => 'required|mimes:jpeg,png,jpg,gif,pdf,tiff,svg,ai,psd'
                ]);

Then attempt to upload/validate these two files:

![works](https://cloud.githubusercontent.com/assets/694196/24409808/4f3e5a68-139f-11e7-92f5-8451a6d83f46.jpg)

![fails](https://cloud.githubusercontent.com/assets/694196/24409809/518acd2e-139f-11e7-84dd-c182a531471e.jpg)

The first one passes validation, the second one fails.

**Comment by devcircus** [comment]
Check your php.ini 'upload_max_size' and 'post_max_size'. I think the 'upload_max_size' may default to 2M. The second photo is bigger than that. See [this post](https://laracasts.com/discuss/channels/general-discussion/file-validation-failing-on-larger-files?page=1) on Laracasts.

**Comment by bhartvigsen** [comment]
Oh wow, good catch. I had actually checked that, but your post made me
revisit this and I realized our development server did not have the same
50MB limit that our production webserver has. Thanks for pointing this out!

**Comment by kasvukuutiot** [comment]
Did this get resolved? I have the same problem atm.

**Comment by Geezter** [comment]
Did this get resolved? I have the same problem atm.
