### ISSUE TITLE
Validation Bail issue

### ISSUE THREAD

**Issue by ispyinternet** [laravel/framework#18546]
- Laravel Version: 5.4
- PHP Version: 5.6.19
- Database Driver & Version: Mysql

Validation Bail is not honoured when a Rule::exists() is being used.

according to the docs:

**Stopping On First Validation Failure**

Sometimes you may wish to stop running validation rules on an attribute after the first validation failure. To do so, assign the bail rule to the attribute:

```
$this->validate($request, [
    'title' => 'bail|required|unique:posts|max:255',
    'body' => 'required',
]);
```
In this example, if the required rule on the title attribute fails, the unique rule will not be checked. Rules will be validated in the order they are assigned.

However I am finding that If for example 'body' uses a Rule::exists() rule the bail is not honoured, e.g.

```
$this->validate($request, [
    'title' => 'bail|required|unique:posts|max:255',
    'body' => [
        'required',
        Rule::exists('body')
    ]
]);
```

**Comment by Dylan-DPC** [comment]
@ispyinternet bail property will work only for title not for any other validation rule. It bails out from the validation of that particular key. Not a bug :+1:

**Comment by themsaid** [comment]
@ispyinternet you haven't used bail on `body`, that's why it's not working :)

**Comment by ispyinternet** [comment]
What I was hoping for was if title validation failed in away then there would be no validation checks whatsoever on body. In not 100% sure now, but I think when Rule::exists wasn't present this was the observed behaviour, i.e. the required on body was not being tested?
