### ISSUE TITLE
Trait 'Illuminate\Database\Concerns\BuildsQueries' not found

### ISSUE THREAD

**Issue by sirBobz** [laravel/framework#18554]
- Laravel Version: 5.4.*
- PHP Version: 7.0.17
- Database Driver & Version: Ver 14.14 Distrib 5.5.54, for debian-linux-gnu (x86_64) using readline 6.3

### Description:
I am trying to login to my platform but getting this error, **Trait 'Illuminate\Database\Concerns\BuildsQueries' not found**

I have not done any changes on the file **/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:23** as from the logs the exception is; 
_local.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Trait 'Illuminate\Database\Concerns\BuildsQueries' not found in /var/www/html/project_name/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:23
Stack trace:
#0 {main}_   

I can not interpret any further as that is the information I get from the logs. 

Kindly someone advice.

Regards.
Bob Mwenda.

### Steps To Reproduce:

I tried submitting my login form; then got the error **FatalErrorException in Builder.php line 23:
Trait 'Illuminate\Database\Concerns\BuildsQueries' not found** on the screen. 

I can not figure out how to solve this.

**Comment by edenreich** [comment]
just try to add that trait it if its not presented in your file

**Comment by sirBobz** [comment]
@edenreich  thank you for  the response;

**Please Note:** 
I did not edit **Builder.php** file 
use Illuminate\Database\Concerns\BuildsQueries;  is on the file.

use BuildsQueries, Macroable {
        __call as macroCall;
    } //is on the file as well.

I can not think of any other way.

Regards,

**Comment by edenreich** [comment]
@sirBobz try clearing all of your cache:

php artisan config:clear
php artisan cache:clear

let me know if there is any progress

**Comment by sirBobz** [comment]
@edenreich 
I tried that and I am afraid it has not been a success.

**Comment by Dylan-DPC** [comment]
Steps to reproduce? @sirBobz

**Comment by sirBobz** [comment]
@Dylan-DPC I it is a shared repository. When I cloned the repo I could not work as I could not login...

@edenreich Here is the fix. 
Sorry I can not explain why but here it is

**FIX**

1. I deleted /vendor with all it's files 
2. composer install

It worked. I am not sure but I think git ignored /vendor on gitignore all along?

Regards.

**Comment by Dylan-DPC** [comment]
@sirBobz close the issue if it is fixed. :+1:
