### ISSUE TITLE
Could not establish Memcached connection

### ISSUE THREAD

**Issue by vocanic-saumini** [laravel/framework#18553]
- Laravel Version: 5.4.*
- PHP Version: 7.0.3-5
- Memcache Driver & Version: memcached 2.2.0

### Description:
It is not an issue, It is a help wanted

I'm getting following error `RuntimeException: Could not establish Memcached connection` once in a while, not always. This been happening last couple of months, I noticed the error somewhere this month only.

I posted question in stackoverflow with more details about the memcached instance. http://stackoverflow.com/questions/42949733/runtime-execption-could-not-establish-memcached-connection

I'm not sure from where do I start debugging. Appreciate any guidance / thoughts to help me investigating this issue.

Thanks

**Comment by kimsan42** [comment]
Do you see the error through error log? Or does it take down the whole request when it happens?

**Comment by themsaid** [comment]
@vocanic-saumini can you please try the forums? we try to keep this repo for bug reporting only, I'm sure someone will be able to help you there.

**Comment by vocanic-saumini** [comment]
@kimsan42 I'm seeing in log file
