### ISSUE TITLE
Validation is not accepting octals and hexadecimals for Integer rule

### ISSUE THREAD

**Issue by nielsenmg** [laravel/framework#18560]
The Validator is not accepting octals and hexadecimals for Integer rule. 

This is an important fix because some front-end validation libraries identify octals as integers and let the data submission and when the data arrives at the server an error is raised.

**Current:**
```
// will be evaluated to false
(new Validator($trans, ['foo' => '020'], ['foo' => 'Integer']))->passes();

// will also be evaluated to false
(new Validator($trans, ['foo' => '0x25'], ['foo' => 'Integer']))->passes();
```

**Solution:**

Just need to add the flags that allow octals and hexadecimals to `ValidateAttributes->validateInteger` method:
```
...
 protected function validateInteger($attribute, $value)
{
    return filter_var($value, FILTER_VALIDATE_INT, FILTER_FLAG_ALLOW_OCTAL | FILTER_FLAG_ALLOW_HEX) !== false;
}
...
```

**Comment by Dylan-DPC** [comment]
@nielsenmg or maybe a separate validation method so that only those who want it can use it?

**Comment by nielsenmg** [comment]
@Dylan-DPC yes, its an alternative too. Thats what I did to solve my problem, but I have not found a good rule name. Do you have a suggestion?

**Comment by Dylan-DPC** [comment]
octal, hex, or maybe a generic base validation that takes the base as an input?

**Comment by scrwdnet** [comment]
This should 100% be separate rule, this could cause some issues for people already using this current validation as they are currently expecting anything that passes to be a 'true' integer (as opposed to an 'integer' starting with a 0).

**Comment by nielsenmg** [comment]
@scrwdnet Yes, it's a breaking change. I think about add some property to integer rule to allow octals or hexadecimals and keep the behavior. This approach will not cause issues for people that is already using it. The another approach, as you said, is to create a separated rule.

**Comment by themsaid** [comment]
@nielsenmg you can add a new rule to your app for that as suggested. Going to close this since it's not an actual bug, but please feel free to open a PR if you want.
