### ISSUE TITLE
Login Throttling time delay not working and shows negative seconds

### ISSUE THREAD

**Issue by slakbal** [laravel/framework#18565]
- Laravel Version: 5.4.16
- PHP Version: 7.1
- Database Driver & Version: Mysql
- Latest Homestead Box
- Caching with Memcached

### Description: 
When I force a lockout the error message states I should wait 60s. After the 60s when I do again an incorrect login the error message now states that I should wait -380 (minus) seconds. I did not tamper with any of the login code it is straight from the installer.

### Steps To Reproduce:
* force a loging lockout by loggin in with incorrect password
* wait 60s and do again a wrong login
* you should then see the above explained behaviiour.

**Comment by themsaid** [comment]
I'm unable to replicate this using Memcached & PHP 7.1, looks like the cached value never expires on your machine for some reason.

**Comment by slakbal** [comment]
@themsaid - let me checkout a brand new fresh laravel and retry and document exact steps. I'll feedback a bit later. Thanks!

**Comment by slakbal** [comment]
@themsaid - sigh... I've destroyed the homestead box and upped a new one. Now it's working.... must have been a memcached hick-up. So sorry if I wasted your time too much.
