### ISSUE TITLE
Eager load - Segfault

### ISSUE THREAD

**Issue by vlopes11** [laravel/framework#18579]
- Laravel Version: 5.4.16
- PHP Version: 7.0.15
- Database Driver & Version: mysql Ver 14.14 Distrib 5.7.17

### Description:
Hello,

I'm receiving a SegFault when I have 2 distinct models with Eloquent relationship and eager load established by the protected array "$with"

On this example, when I get either Father or Son, Eloquent recurrently tries to fetch a relation Father -> Son -> Father -> Son until SegFault

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Father extends Model
{
    protected $with = ['son'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function sons()
    {
        return $this->hasMany(Son::class);
    }
}

class Son extends Model
{
    protected $with = ['father'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function father()
    {
        return $this->belongsTo(Father::class);
    }
}
```

### Steps To Reproduce:

```
$ php artisan tinker
\App\Son::create(['father_id', \App\Father::create([])->id])->get()
```

**Comment by themsaid** [comment]
Because laravel will try to load the relationships infinitely since they both load each other, you need to use a different approach to avoid that.

Please continue on the forums since it's the place for such questions, we try to keep this repo for bug reporting only.

**Comment by vlopes11** [comment]
I understand what caused the issue but thought about a Pull Request in order to avoid loading repeated instances of the same model when using Eager Loading operation.

It can be easily avoided by another modeling approach, tho.

**Comment by themsaid** [comment]
Well, feel free to open a PR then :)
