### ISSUE TITLE
[5.4] Validation Rule nullable with required failed (not expected)

### ISSUE THREAD

**Issue by rokde** [laravel/framework#18577]
- Laravel Version: 5.4.16
- PHP Version: 7.0.15
- Database Driver & Version: -

### Description:
In Laravel 5.4.15 the following test is valid:
```php
$rules = ['id' => 'required|nullable'];
$data = ['id' => null];
$this->validate($data, $rules);
```

In Laravel 5.4.16 the same code is invalid - so all my unit tests failed. I think this is not the correct behaviour, because the key `id` is in the data and the ruleset needs a key `id` and allows being null - that it is.

### Steps To Reproduce:
```php
$rules = ['id' => 'required|nullable'];
$data = ['id' => null];
$this->validate($data, $rules);
```

in unit test or in command line (tinker)

**Comment by rokde** [comment]
I have no middleware for changing the values of a request or something like that

**Comment by themsaid** [comment]
In a recent change we made `null` invalid in a `required` rule, the old behaviour was reported multiple times as a bug, when you say a field is required then it doesn't really make sense to accept `null` as a value for that field. May I ask what's the use case?

**Comment by rokde** [comment]
In my use case I have to have a field in the data with a key. But null is a valid value, like an integer too.

**Comment by themsaid** [comment]
Sorry but we had to change this since people reporting it as a bug was happening on daily basis :) My suggestion is that you filter the data before passing to the validator and remove the nullable fields.

**Comment by rokde** [comment]
Ok, but technically I think your decision is wrong. I will change my code.

**Comment by LasseHaslev** [comment]
@themsaid I do not agree that this decision is the most logical.

I have an API endpoint that only accepts one attribute and the value can be null.
I want the validation errors to guide the users to know which attribute is available. 

### Why I think this decision not logical

```php
request()->validate([
    'data' => 'required|nullable',
]);
```
I think this scenario should throw a validation error if the key `data` does not exists. This will force the use of a key named `data`, but the value chould be `null`.

### The suggested alternative

Removing the `required` rule as suggested, will not pick up up if the user is using the wrong attribute.

```php
$this->post('store', [
    'not-right-attribute'=>'my value',
])->assertStatus(201);
```

### Workaround
This is a workaround, but it feels dirty.

```php
if (! request()->has('data')) {
    request()->validate([
        'data' => 'required',
    ]);
}

request()->validate([
    'data' => 'nullable',
]);
```

**Comment by brandonferens** [comment]
@LasseHaslev I am having this same issue. However, I discovered that there is a `present` validation rule that checks the field exists in the input data, but can be empty.

**Comment by LasseHaslev** [comment]
@brandonferens Thank you!

Changed my code from this

```php
if (! request()->has('data')) {
    request()->validate([
        'data' => 'required',
    ]);
}

request()->validate([
    'data' => 'nullable',
]);
```
To this
```php
request()->validate([
    'data' => 'present',
]);
```

And all my test are still working! 👍

**Comment by overwise** [comment]
> In a recent change we made `null` invalid in a `required` rule, the old behaviour was reported multiple times as a bug, when you say a field is required then it doesn't really make sense to accept `null` as a value for that field. May I ask what's the use case?

In a case of nullifying required nullable field, in other words updating its value to NULL, it is very useful to have option to have both rules available in combination. I wonder in which case these two rules look like a bug. Combined they clearly say: "Field must have value or be null". Null is a value too, unknown, but a value. To me, it sounds much more like a bug to specify that a field is nullable, and have that ignored.

**Comment by ElteHupkes** [comment]
Arriving here through Google several years later, I'm wondering if there is any combination of validation rules to express a rule that a field should be present, and either `null` or not empty. In my testing (Laravel 9):

- `nullable|required` fails on `null`, which is the original issue here.
- `nullable|present` passes on `null`, but also passes on an empty string - which is indeed what the rule expresses, but .
- The workaround I thought of, `nullable|present|min:1`, **also passes on an empty string**, because `min` is not an [implicit rule](https://laravel.com/docs/9.x/validation#implicit-rules).

So, without inventing a custom rule, I'm at a loss. Any takers?

**Comment by brandonferens** [comment]
Hey @ElteHupkes, I'll try taking it.

If we are talking about params in a query string, here is the routing method and result:

```php
// Route call.
route('some.path', ['foo' => null, 'bar' => '']);

// Output.
https://my.site/some/path&bar=
```

As you can see it will remove the null value from the query params. I have a feeling you are talking about a post payload, however.

Here is what I found when posting the same values as a payload:

```php
// Using the post method inside of the test suite, but should result in the same data.
$this->post('/some/path', ['foo' => null, 'bar' => ''])
// or
$this->postJson('/some/path', ['foo' => null, 'bar' => ''])

// Inside of the controller or form request, the resulting values.
[
    'foo' => null,
    'bar' => null,
]
```

Based on this, I'm assuming that if you pass an empty string, it becomes null. So checking if it is null but not empty isn't possible. However, I haven't attempted this by passing actual data from a Vue or React app. Perhaps that data does something different if handled that way, but I'm guessing not. 

Hope that helps or points you in the right direction!

**Comment by ElteHupkes** [comment]
@brandonferens This is true if you use the `TrimStrings` and `ConvertEmptyStringsToNull` middleware. I'm not really a big fan of those in all contexts, but indeed it took disabling them to run into these issues in the first place. Without those middleware, empty strings will just pass through verbatim. A rule like `min:10` will not fail on input like `    `, because it is an "empty" string, and any rule that isn't implicit is ignored for empty strings.

Looking through the validation source code over the past few days I get the impression it was mostly built for HTML form data. It basically assumes everything comes in as strings (there isn't even a built-in validation rule that checks if something is of a number or boolean **type**, for instance). I can see where this is coming from historically, but for building a JSON API it doesn't always make that much sense.

**Comment by odaiderawi** [comment]
Using sometimes validation rule may solve your issue.

`$request->validate([
'data' => 'sometimes|required|string'
])`

It means the data will only be validated if it is present in the request .

**Comment by ElteHupkes** [comment]
@odaiderawi That will pass on `['data' => 'abc']` and `[]`, which is good, but it will fail on `['data' => null]`, which I want to allow.

**Comment by gavin-lhs** [comment]
@ElteHupkes Try using rule like:

```php
'data' => ['present', 'nullable', 'array']
```

This should allow both `['data' => 'abc']` and `['data' => null]` to pass validation (it will fail on `[]` though).

**Comment by ElteHupkes** [comment]
@gavin-lhs Assuming you mean the `string` variant

```
'data' => ['present', 'nullable', 'string']
```

it will pass validation on an empty string, `['data' => '']`.

**Comment by Lloople** [comment]
Since I need to check that the field exists on database or it's null, this worked for me

```php
'booking_id' => ['present', 'nullable', 'integer', Rule::exists(Booking::class, 'id')],
```
