### ISSUE TITLE
Switching mail provider but continues to use previous

### ISSUE THREAD

**Issue by davidpiesse** [laravel/framework#18588]
- Laravel Version: 5.3 ^
- PHP Version: 7.0
- Database Driver & Version: Not Applicable
- Mail Providers: Mailgun & Mailtrap

### Description:
Whilst testing locally with Mailtrap (SMTP) and then switching drivers to another (in this instance Mailgun) sending mails still uses the Mailgun settings.
Even an artisan clear config does not fix the issue.
Currently only way found to get it to recognise the change is to restart the server / local machine.

### Steps To Reproduce:
- Build basic Laravel App
- Setup SMTP credentials for Mailtrap, and configure Mailgun service credentials.
- Set smtp/mailtrap as the mail driver in config
- Test Sending a mail (received at Mailtrap)
- Change driver to mailgun
- Test sending mail (still received at Mailtrap)

#### Laracasts Discussion Link
https://laracasts.com/discuss/channels/laravel/mail-not-sending-with-mailgun-but-sends-with-mailtrap

**Comment by nowak-ninja** [comment]
@davidpiesse How do You serve the app locally?

**Comment by davidpiesse** [comment]
Valet - but also tried with artisan serve
Live server is your bog standard DO, 16.04, PHP 7 box - using Forge.

**Comment by nowak-ninja** [comment]
@davidpiesse I do not know how the Valet works but if You are using `artisan serve` or php built-it server, then You need to restart it on every change in .env file because all entries are read only once on the start.

**Comment by davidpiesse** [comment]
I get that sort of local issue (I assume valet may have a similar
limitation) - but I have had the issue in prod as well..

**Comment by Dylan-DPC** [comment]
have you tried clearing the config cache?

**Comment by davidpiesse** [comment]
I did - I gradually escalated the changes - clearing caches, etc. but they
only thing that eventually worded was a system reboot.

**Comment by themsaid** [comment]
Looks to me as a system caching issue or something, closing this issue then.

Anyone please feel free to ping me if you can replicate.
