### ISSUE TITLE
Container @ alias 

### ISSUE THREAD

**Issue by zhyswan** [laravel/framework#18595]
- Laravel Version: 5.4.16
- PHP Version:5.6
- Database Driver & Version:mysql

### Description:
Parameter name is not reasonable

### Steps To Reproduce:
Class  Illuminate\Container\Container   
Method alias
    
     /**
     * old method
     */
    /*
    public function alias($abstract, $alias)
    {
        $this->aliases[$alias] = $abstract;

        $this->abstractAliases[$abstract][] = $alias;
    }*/
     

    /**
     * new
     */
    public function alias($alias, $abstract)
    {
        $this->aliases[$abstract] = $alias;

        $this->abstractAliases[$alias][] = $abstract;
    }

**Comment by Dylan-DPC** [comment]
Reason why it is not reasonable?

**Comment by themsaid** [comment]
This is not a bug.

**Comment by zhyswan** [comment]
Of course, it's not a bug, but it will make the reader misunderstand
