### ISSUE TITLE
Better Eloquent boolean attribute cast

### ISSUE THREAD

**Issue by matbeard** [laravel/framework#18599]
- Laravel Version: 5.4.16
- PHP Version: 7
- Database Driver & Version: MySQL 5.6

### Description:
Boolean attribute casting could be better.

I'm having to create a mutator for all my boolean fields because the JavaScript framework I'm using sends 'true'/'false' for checkboxes, which are received as strings.

If Eloquent used something like:
`bool = filter_var($value, FILTER_VALIDATE_BOOLEAN);`
this would return TRUE for "1", "true", "on" and "yes". Returns FALSE otherwise.

Is there a way I can override the default boolean attribute cast?

**Comment by Dylan-DPC** [comment]
This isn't a bug. Open an issue on the laravel/internals repo :)

**Comment by matbeard** [comment]
Done. Thx.
