### ISSUE TITLE
TokenMismatchException - Laravel + AWS EC2 Ubuntu Server

### ISSUE THREAD

**Issue by acignarella3** [laravel/framework#18607]
- Laravel Version: 5.4
- PHP Version: 7.0.15
- Ubuntu Version: 16.04.4

### Description:

I am trying to test connecting Laravel to an AWS EC2 Ubuntu server by using the sample project provided in Laravel's documentation. However, when I try to create a new user via the Registration page it is hitting a "TokenMismatchException in VerifyCsrfToken.php" error. This is despite the fact that the {{ csrf_field() }} token is still present (in fact, register.blade.php hasn't been touched at all), and that the project still works fine on a local server (Windows, Ubuntu local, and Mac).

### Steps to Reproduce:

1) composer create-project --prefer-dist laravel/laravel blog
2) php artisan key:generate
3) In the .env file
    APP_ENV = production
    SESSION_DOMAIN = domainname.com
    APP_URL = http://domainname.com
    DB_* = (configured for personal database)
4) php artisan make:auth
5) php artisan migrate

**Comment by sisve** [comment]
One possible reason would be a broken session. For example, wrong domain on the session cookie, a session driver that doesn't do anything, or in the case of the file-based session driver, bad permissions on storage/framework/sessions. Can you verify that the domain and permissions are correct, and that you're not using the array session driver?

**Comment by acignarella3** [comment]
I have the following set up on my .ENV file, in addition to the above:

SESSION_SECURE_COOKIE=domainname.com
APP_DEBUG=true
APP_LOG_LEVEL=debug

777 permissions have been set in the storage/framework/sessions folder, and I am only using the database driver, not an array session driver. Unfortunately, I'm still facing issues.

**Comment by themsaid** [comment]
Please ask on the forums, we keep this repo for bug reporting only.
