### ISSUE TITLE
Unable to connect to remote server.

### ISSUE THREAD

**Issue by bunlongheng** [laravel/framework#18624]
I’m trying to upload files to my staging server running Linux Ubuntu.

I tried follow everything in this post = https://laravelcollective.com/docs/5.1/ssh . I am on Laravel 5.1.

I configured my `remote.php` like this :

    'connections' => [
            'production' => [
                'host'      => '45.55.88.88',
                'username'  => 'root',
                'password'  => '',
                'key'       => '/Users/bheng/.ssh/id_rsa', //Try : public | private
                'keytext'   => '',
                'keyphrase' => '******',
                'agent'     => '', //Try : empty | enabled | disabled,
                'timeout'   => 10,
            ],
        ],

I tried test it like this in my project :

    SSH::run('date', function($line) {dd($line); });

I kept getting :

>Unable to connect to remote server.

____

I tried it on my Mac OS Terminal

    sftp root@45.55.88.88

It’s working fine, I got

    sftp> ls
    Desktop       Documents     Downloads     Music         Pictures      Public        Templates     Videos        dead.letter

____

What did I do wrong or forget ? What elses should I try ? 

Do I need to do anything on my `/etc/ssh/sshd_config` ?

Can someone please help me out if you’re done this before ?

**Comment by lagbox** [comment]
You should probably bring this up on their repository as this isn't a Laravel package and its not part of the framework.

**Comment by srmklive** [comment]
Its better that you post this issue in LaravelCollective repo

**Comment by qannoufoualid** [comment]
@bunlongheng! Please have you found a solution for this problem? i'm stuck on it too and i have no clue
