### ISSUE TITLE
[5.3][5.4]Queue:work always fails after the first job

### ISSUE THREAD

**Issue by wouthoekstra** [laravel/framework#18632]
- Laravel Version: 5.3.11
- PHP Version: 7.1.1-1+deb.sury.org~xenial+1
- Database Driver & Version: 5.7.17
- Queue Driver: Beanstalkd

### Description:
Only a first job succeeds when using queue:work. Queue:listen poses no problems, as does manually starting and stopping queue:work for every single job. I've pinpointed the issue to laravel framework 5.3.11, or to be more precise: https://github.com/laravel/framework/commit/23c12765557ebc5e3c35ad024d645620f7b907d6

My situation is the following: Each job is handled by a Job class. This Job class creates a Command class which is dispatched through Laravel's command bus.

**First job:**

- Handle on the Job class is called.
- Command class is created, as well as a pipeline (Laravel's command bus) to put the command through.
- Command is dispatched through the pipeline.
- All is well, Job successful.

**Second job**

- Handle on the Job class is called.
- No new Command is created.
- The Job class is dispatched through the command bus, instead of the lacking Command class. Resulting in fatal errors.

### Steps To Reproduce:

I've simplified my classes to look like the following:

```
class Job implements ShouldQueue 
{
  public function handle()
  {
    $command = new Command();

    Bus::pipeThrough(['stuff']);
    Bus::dispatch($command);
  }
}

class Command
{
   public function __construct()
   {
     dump("Command created");
   }
}
```

This should output: 

> "Command created"
> 
> [2017-04-02 19:16:58] Failed: App\Jobs\Job
> 
> "Command created"
>
> [2017-04-02 19:16:58] Failed: App\Jobs\Job
>
> "Command created"
> 
> [2017-04-02 19:16:58] Failed: App\Jobs\Job

But it doesn't, it outputs:

> "Command created"
> 
> [2017-04-02 19:16:58] Failed: App\Jobs\Job
> 
> [2017-04-02 19:16:58] Failed: App\Jobs\Job
> 
> [2017-04-02 19:16:58] Failed: App\Jobs\Job

(note only one command created).

If I comment ``return $this->runNextJob($connectionName, $queue, $options);`` in ``framework/src/Illuminate/Queue/Worker.php:runNextJobForDaemon()`` it works as expected again. The comment below this line suggests it is added because of compatibilty with SQS, but now i'm experiencing issues when using Beanstalkd.

**Comment by themsaid** [comment]
Please upgrade to 5.4 and try to replicate the issue there, 5.3 is not supported anymore.

**Comment by wouthoekstra** [comment]
I've reverted from Laravel 5.4 back to 5.3 because of this issue. Issue still applies. Thought it might be helpful to pinpoint were the issue started.

**Comment by wouthoekstra** [comment]
Opened new issue for Laravel 5.4.17 https://github.com/laravel/framework/issues/18640. Will make sure I use supported Laravel version in issue next time.
