### ISSUE TITLE
AbstractPaginator opens XSS vulnerability with query parameters

### ISSUE THREAD

**Issue by nsnyder** [laravel/framework#18639]
- Laravel Version: 5.1.30
- PHP Version: 7.0
- Database Driver & Version: N/A

### Description:
The `Illuminate\Pagination\AbstractPaginator` calls `urldecode()` on the query string. This results in the possibility that dummy parameters can be added to the query string, and then displayed on the page, unencoded.

### Steps To Reproduce:
```
public function show(Request $request) {
    // Create the paginator, and append get parameters
    $users= User::paginate(10)->appends($request->get());
    return ('users.index', compact('users'));
}
```

`users\index.blade.php`
```
@foreach ($users as $user)
    <li>{{ $user->name }}</li>
@endforeach
{!! $users->render() !!}
```

If a malicious user enters into the string, say: `&maldata="></a><IMG%20SRC="l.png"%20onerror="alert(104);">`

They can cause an XSS attack.

**Comment by nsnyder** [comment]
I've identified a place in the AbstractPaginator that I think could fix the issue:

In the function `url($page)`
```
return $this->path.'?'
                        .urldecode(http_build_query($parameters, null, '&'))
                        .$this->buildFragment();
```
I believe that by removing the `urldecode()` this could be solved. Alternatively, in the same class:

The function `addQuery($key, $value)`
```
        if ($key !== $this->pageName) {
            $this->query[$key] = $value;
        }

        return $this;
```
I think you could fix it by adding `urlencode()` around `$value`

**Comment by edenreich** [comment]
@nsyder yup I think that issue was fixed already...

 return $this->path
                        .(Str::contains($this->path, '?') ? '&' : '?')
                        .http_build_query($parameters, '', '&')
                        .$this->buildFragment();

this is the current code on laravel 5.4

**Comment by nsnyder** [comment]
@edenreich Could we get this on 5.1 since it's an LTS release?

**Comment by edenreich** [comment]
@nsnyder Your solution seems ok to me, just remove the decode thing there, does it solve the xss attack?

**Comment by nsnyder** [comment]
It does. Do I need to submit a pull request on the 5.1 branch, or can the previous fix be added without me creating a pull request?

**Comment by deleugpn** [comment]
I think this will require a new pull request.

**Comment by nsnyder** [comment]
Ok, I'll put one together.

**Comment by nsnyder** [comment]
Nevermind, looks like this is already fixed. We just need to update our framework. Thanks for helping a n00b everyone :)
