### ISSUE TITLE
pipeline function issue using phpredis extension through redis facade

### ISSUE THREAD

**Issue by TsuiJie** [laravel/framework#18633]
- Laravel Version: 5.4.12
- PHP Version: 7.0.16
- Database Driver & Version:
redis 3.2.0

### Description:
Redis::pipeline() expects exactly 0 parameters, 1 given

### Steps To Reproduce:
1. install phpredis extension
2. switch database redis config to use phpredis instead of default predis
3. change facade alias to 'PhpRedis' according to documentation
4. OK with predis, and fine using other methods with phpredis

**Comment by tillkruss** [comment]
Couls you post a code sample?

**Comment by TsuiJie** [comment]
confirmed, fixed at v5.4.16
