### ISSUE TITLE
Filesystem / Cloud Storage: append to a file will exhausted memory

### ISSUE THREAD

**Issue by cstoehr** [laravel/framework#18634]
- Laravel Version: 5.3
- PHP Version: 7.1
- Database Driver & Version:
not relevant 

Description:

If you use the storage-class to append a string to a local file who bigger as the memory limit it will exhausted the memory.

In my opinion it is because it doesn't only append to the file, the Storage-Class will read the file into the memory and put the string to the end. 

Steps To Reproduce:

Append a string to a local file in a loop. And finish the loop after if the file bigger than the memory limit.

**Comment by kudm761** [comment]
Yes, It reads the whole file into the memory, then rewrites the file.
It is better to use fopen + fwrite at the end.

**Comment by jhdxr** [comment]
`Storage` is based on the `flysystem`, which is not supportting append for now. see thephpleague/flysystem#696
