### ISSUE TITLE
When using Model::WhereAttribute(false)->get() returns all objects

### ISSUE THREAD

**Issue by compynerds** [laravel/framework#18638]
- Laravel Version: 5.4.15
- PHP Version: 7.0.15
- Database Driver & Version:
MySQL Ver 14.14 Distrib 5.7.17
### Description:
When using Model::whereId(false)->get() will return all objects of the Model specified.
Also when using Model::find(false) will return the first Model object in the DB.
Model::find(false)->all() returns all Model objects in the DB.

Ex: User::whereId(false)->get() returns all users in the DB.
Ex: User::whereId(false)->first() returns the first user in the DB.

This also works for all other non-boolean attributes not just ID.
Ex: User::whereEmail(false)->get()
/*Edit: this seems to reproducible on most where conditions whereHas, whereDoesntHave, etc*/

### Steps To Reproduce:
php artisan tinker(also reproducible in production code not just tinker)
namespace <namespace>
User::whereId(false)->get() or User::whereId(false)->first()

**Comment by themsaid** [comment]
Unable to replicate:

```php
App\User::whereId(false)->get();
```

<img width="469" alt="screen shot 2017-04-03 at 8 36 05 pm" src="https://cloud.githubusercontent.com/assets/4332182/24624482/4f055f08-18ac-11e7-963a-3e18266e5491.png">

**Comment by compynerds** [comment]
Your table has user stored in the database?

**Comment by themsaid** [comment]
yes

**Comment by compynerds** [comment]
User::find(false) acts the same way?

**Comment by themsaid** [comment]
Yes, and returns `null`

**Comment by compynerds** [comment]
It appears that one of our dependencies is creating this vulnerability sorry to have wasted your time. I appreciate the help though.
Thank you.

**Comment by themsaid** [comment]
No worries :)
