### ISSUE TITLE
Why RedisStore#forever (and Cache contract) return void instead of bool/object?

### ISSUE THREAD

**Issue by aledelgo** [laravel/framework#18631]
- Laravel Version: 5.3
- PHP Version: 7.1
- Database Driver & Version: not-important

### Description:
I'm using Laravel-Doctrine and issuing the command to clear the doctrine cache i've noticed the result is ever "No cache entries were deleted." also if it effectively cleared all items in cache. Exploring the code i've discovered the bug is linked to this source code in the RedisStore
https://github.com/laravel/framework/blob/5.4/src/Illuminate/Cache/RedisStore.php#L161

as you can see the method return void also if the sub storage return some kind of result.
executing the inner-line in a console i get something like this, that is a confirmation of command executed

![image](https://cloud.githubusercontent.com/assets/1503438/24602949/42f14d1e-185f-11e7-85ab-f36319b18c1d.png)

I'm wondering why in the contract, the add method return a bool, while put and forever return void
https://github.com/laravel/framework/blob/5.4/src/Illuminate/Cache/RedisStore.php#L121

PS. Yes, i know the bug should be fixed in the Laravel-Doctrine code so that it respect the Laravel contracts but i'm just curious of the reason the Cache contract is so defined.

Thanks

**Comment by tillkruss** [comment]
I think one of the supported cache implementations can't do it, but if you can manage to return a definite `true` for APC, APCu, Redis, Memcached, etc., I'd make a PR for v5.5.
