### ISSUE TITLE
Queue:work always fails after the first job

### ISSUE THREAD

**Issue by wouthoekstra** [laravel/framework#18640]
- Laravel Version: 5.4.17
- PHP Version: 7.1.1-1+deb.sury.org~xenial+1
- Database Driver & Version: 5.7.17
- Queue Driver: Beanstalkd

### Description:
Only a first job succeeds when using queue:work. Queue:listen poses no problems, as does manually starting and stopping queue:work for every single job. I've pinpointed the issue to laravel framework 5.3.11, or to be more precise: https://github.com/laravel/framework/commit/23c12765557ebc5e3c35ad024d645620f7b907d6. However, the issue is still there in 5.4.17.

My situation is the following: Each job is handled by a Job class. This Job class creates a Command class which is dispatched through Laravel's command bus.

**First job:**

- Handle on the Job class is called.
- Command class is created, as well as a pipeline (Laravel's command bus) to put the command through.
- Command is dispatched through the pipeline.
- All is well, Job successful.

**Second job**

- Handle on the Job class is called.
- No new Command is created.
- The Job class is dispatched through the command bus, instead of the lacking Command class. Resulting in fatal errors.

### Steps To Reproduce:

I've simplified my classes to look like the following:

```
class Job implements ShouldQueue 
{
  public function handle()
  {
    $command = new Command();

    Bus::pipeThrough(['stuff']);
    Bus::dispatch($command);
  }
}

class Command
{
   public function __construct()
   {
     dump("Command created");
   }
}
```

This should output: 

> "Command created"
> 
> [2017-04-02 19:16:58] Failed: App\Jobs\Job
> 
> "Command created"
>
> [2017-04-02 19:16:58] Failed: App\Jobs\Job
>
> "Command created"
> 
> [2017-04-02 19:16:58] Failed: App\Jobs\Job

But it doesn't, it outputs:

> "Command created"
> 
> [2017-04-02 19:16:58] Failed: App\Jobs\Job
> 
> [2017-04-02 19:16:58] Failed: App\Jobs\Job
> 
> [2017-04-02 19:16:58] Failed: App\Jobs\Job

(note only one command created).

In Laravel 5.3.11 (the first version in which the issue occurs) I could remove ``return $this->runNextJob($connectionName, $queue, $options);`` in ``framework/src/Illuminate/Queue/Worker.php:runNextJobForDaemon()`` and have it work as expected again. In Laravel 5.4 the original conditional is removed, including the ``waitForChildProcess()`` method which is somehow needed in my case.

**Comment by themsaid** [comment]
In `Bus::pipeThrough(['stuff'])` you're adding a non existing pipe, so the next time the command is attempted it tries to run it through this pipe so it fails before even calling the `handle()` method again, if you use `pipeThrough()` all the jobs will run though the given pipes so you better be sure it works.

**Comment by wouthoekstra** [comment]
Sorry, I'll make a better example soon. I've tested the above with an existing pipe as well; the same pipe with which the first job succeeds.

**Comment by wouthoekstra** [comment]
I've created a gist which should make it easier to reproduce the problem. It includes a route to push the job to a queue named '1', and the artisan command I use to run the job. https://gist.github.com/wouthoekstra/6f839a9646731fa015bc02eaea59278f

The output in my case is the following:

> "handle job"
> "testcommand created"
> "testpipeline created"
> "handling..."
> "App\Jobs\TestCommand"
> [2017-04-06 12:19:06] Processed: App\Jobs\Sync\TestJob
> "handling..."
> **"App\Jobs\TestJob"**
> [2017-04-06 12:19:12] Processed: App\Jobs\Sync\TestJob

The problem is the second time the command runs, it receives the **job**, not the **command** My code obviously fails on this unexpected object. 

Maybe useful information, i've upgrade Pheanstalk to: ``"pda/pheanstalk": "~3.1.0"``

If more info is needed, let me know :)

**Comment by themsaid** [comment]
Simple because the worker is listening to the `1` queue while you're pushing the command on the `default` queue.

Going to close this issue since apparently it's something in your code. Please feel free to ping me on the forums if you need assistance.

**Comment by themsaid** [comment]
@wouthoekstra `Bus::dispatch($command);` here you're pushing the command on the default queue while the job is dispatched to the `1` queue.

**Comment by wouthoekstra** [comment]
You are right according to the docs. However, I do monitor all my queues (with beanstalk console) and the default queue remains empty. If I use the ``dispatchToQueue($command)`` the command indeed gets pushed to the default queue like you say.

If I push everything to the default queue, my issues remain: no new commands are created after the first job.

My code worked unaltered up untill in Laravel 5.3.11 where a pcntl_fork() line is removed (https://github.com/laravel/framework/commit/23c12765557ebc5e3c35ad024d645620f7b907d6), which is why I am not only looking for mistakes in my code. Note: everything i've tried in this topic I used Laravel 5.4.17.

**Comment by wouthoekstra** [comment]
I would also not explain (not to me at least) why the ``php artisan queue:listen`` with the exact same parameters does work with the same code.

**Comment by themsaid** [comment]
```
class TestJob implements ShouldQueue
{
    use Queueable;
    use InteractsWithQueue;
    protected $job;

    public function handle()
    {
        \Log::info('handle job');
        $command = new TestCommand();
        $pipeline = new TestPipeline();
        Bus::pipeThrough([$pipeline]);
        Bus::dispatch($command);
        $this->job->delete();
    }
}

class TestCommand
{
    public function __construct()
    {
        \Log::info('testcommand created.');
    }

    public function handle()
    {
        \Log::info('testcommand handled.');
    }
}

class TestPipeline
{
    public function __construct()
    {
        \Log::info('testpipeline created');
    }

    public function handle($command, $next)
    {
        \Log::info('handling pipeline...');
        \Log::info(get_class($command));

        return $next($command);
    }
}
```

Running the job twice I get:

```
[2017-04-06 16:28:10] local.INFO: handle job  
[2017-04-06 16:28:10] local.INFO: testcommand created.  
[2017-04-06 16:28:10] local.INFO: testpipeline created  
[2017-04-06 16:28:10] local.INFO: handling pipeline...  
[2017-04-06 16:28:10] local.INFO: App\Jobs\TestCommand  
[2017-04-06 16:28:10] local.INFO: testcommand handled.  
[2017-04-06 16:31:52] local.INFO: handling pipeline...  
[2017-04-06 16:31:52] local.INFO: App\Jobs\TestJob  
[2017-04-06 16:31:52] local.INFO: handle job  
[2017-04-06 16:31:52] local.INFO: testcommand created.  
[2017-04-06 16:31:52] local.INFO: testpipeline created  
[2017-04-06 16:31:52] local.INFO: handling pipeline...  
[2017-04-06 16:31:52] local.INFO: App\Jobs\TestCommand  
[2017-04-06 16:31:52] local.INFO: testcommand handled.  
```

using 

```
php artisan queue:work --tries=1 --queue=1
```

**Comment by wouthoekstra** [comment]
Ok, then it must be something in my configuration I guess.

One last question though, might be a clue for me; what is the "App\Jobs\TestJob" output doing in your logs? Is is the job supposed to be passed in the pipeline handle() as a command?

**Comment by themsaid** [comment]
First time it runs without the pipeline, but once you added TestPipeline all future jobs will run though this pipeline.

**Comment by wouthoekstra** [comment]
That was it! Before 5.3.11 a job was put into its own process with `pcnt_fork()`. Because this is removed since then, the pipethrough remains the same for all jobs, failing the jobs in my case.

Putting this in my TestJob handle() fixed it for me:

```
if($pid = pcntl_fork()) {
    sleep(1);
} else {

    $command = new TestCommand();
    $pipeline = new TestPipeline();
    Bus::pipeThrough([$pipeline]);
    Bus::dispatch($command);
    $this->job->delete();
}
```

Ofcourse the `sleep(1) ` is not a very neat solution, but I will have to do something like Laravel did before.

Thanks for your time!
