### ISSUE TITLE
Class queue.listener does not exist  

### ISSUE THREAD

**Issue by rkhaslarov** [laravel/framework#18655]
- Laravel Version: 5.4.17
- PHP Version: 7
- Database Driver & Version: MySQL 5.7

### Description:
I updated my laravel 5.3 to 5.4 everything is worked but php artisan give me this error
[2017-04-04 18:43:34] local.ERROR: ReflectionException: Class queue.listener does not exist in /vendor/laravel/framework/src/Illuminate/Container/Container.php:719

**Comment by themsaid** [comment]
Make sure the `Illuminate\Queue\QueueServiceProvider::class` provider is loaded in your `config/app.php` file and recheck your project files, looks like laravel is not fully booted for some reason.

**Comment by noge075** [comment]
Hi!

I have the same issue. I checked my app.php and the the Illuminate\Queue\QueueServiceProvider::class is exists.

**Comment by gazatem** [comment]
I'm using Laravel 5.5 and facing the same issue

**Comment by mkosmen** [comment]
delete cache files in bootstrap folder
