### ISSUE TITLE
how to display storage content in laravel 5.3 from storage folder

### ISSUE THREAD

**Issue by JDamour** [laravel/framework#18666]
- Laravel Version:  5.3.30
- PHP Version:5.6
- Database Driver & Version:MySQL 5.6

### Description:
i can't display image or playing mp3 file ,i have been struggling for this issue for hours on my localhost all files images,mp3 works fine in symbolic link at public/storage when i moved to the share hosting can't work this is sample code for image tag

tag img src="{{asset($track->image)}}" alt="{{$track->Name}}" data-toggle="tooltip" data-placement="bottom" title="{{$track->Name}}"

the value of $track->image
is a path :storage/images/avatars/artists/f9dc92344b57ec6b0bcb3ce601f9d‌​134.jpeg

### Steps To Reproduce:
NotReadableException in AbstractDecoder.php line 335:
Image source not readable

**Comment by Dylan-DPC** [comment]
This doesn't seem to be a bug. You can use the forums or the slack channel to get your problem solved

**Comment by JDamour** [comment]
I have been using defferent forums, I didn't find a solution that is why I used this channel

**Comment by themsaid** [comment]
I think this is more related to `Intervention\Image`, please ask on their repository.

**Comment by JDamour** [comment]
thanks let me check on Intervention\Image repository
