### ISSUE TITLE
Request and Server variables are not available in routes while unit testing

### ISSUE THREAD

**Issue by KristofMorva** [laravel/framework#18678]
- Laravel Version: 5.4.17
- PHP Version: 7.1

Sorry if just I'm not getting something. In the `routes/web.php` file we are accessing the `Request::segments()` for multi-lingual support. It's all great, except if we want to HTTP test it with `$this->get('...')`. Then in the routes file, `REQUEST_URI` is empty, `segments` is empty, everything is empty, but in the controller method everything is fine. Is this the expected behavior? If so, is there a general solution?

**Comment by deleugpn** [comment]
I think this happens because Laravel is bootstrapped by CLI when running tests and, therefore, no HTTP Request.

**Comment by edenreich** [comment]
@KristofMorva hey Kristof I've tried to replicate this issue, yet I get the segments just fine:

![1](https://cloud.githubusercontent.com/assets/16985712/24777609/6ba8b8a4-1b26-11e7-842a-217f32e78c3f.jpg)

This is the test file:

![3](https://cloud.githubusercontent.com/assets/16985712/24777647/a5693b4a-1b26-11e7-85f6-856338907649.jpg)


This is the tests output:

![2](https://cloud.githubusercontent.com/assets/16985712/24777615/74382b94-1b26-11e7-83ef-35b57ddef7a5.jpg)

This is the browser output:

![4](https://cloud.githubusercontent.com/assets/16985712/24777724/fa24872a-1b26-11e7-8f68-7cdcd71a5e84.jpg)

is that what you meant ?

**Comment by KristofMorva** [comment]
Hey @edenreich, thanks for checking this out. In the Controller methods (and therefore in the route methods also) the `segments` are really available, however, they are not when building the routes, for example in our case:

`Route::group(['prefix' => LanguageService::getRoutePrefix(Request::segment(1)), ...)`

**Comment by edenreich** [comment]
@KristofMorva ahh I see what you mean, I will take a look

**Comment by edenreich** [comment]
@KristofMorva well the issue is that the routes while being registered in `Illuminate\Routing\Router.php on line 364` are not yet aware of the current request. To fix this, or rather saying to allow this, it will require to set the current request before the routes are being registered. I will take a look at this a bit more later...but not sure yet if this is expected behavior too we need to ask taylor

**Comment by meyer59** [comment]
Hi guys,
Any solution for this issue ?

**Comment by zohaibhassan156** [comment]
I am facing same issue for api requests from different domain 

With Illuminate\Http\Request $request its returning empty $request object 

With request() helper request object is fine 

sharing screen shot for difference in both

Its weird the difference in request() and $request of (Illuminate\Http\Request)

![Annotation 2020-10-07 225407](https://user-images.githubusercontent.com/19224021/95368805-0c82bd00-08f0-11eb-9a44-ce1b741beaa3.png)
![Annotation 2020-10-07 225259](https://user-images.githubusercontent.com/19224021/95368809-0db3ea00-08f0-11eb-8c50-d04234f2b3d9.png)

**Comment by zohaibhassan156** [comment]
Now I have to replace $request with request(), I don't what's causing this issue, I event try laravel-cors plugin.

**Comment by zohaibhassan156** [comment]
My issue is resolved There was a typo in "use Illuminate\Http\Request;" 

I was using "use Illuminate\http\Request;" instead 

Hope it helps someone
