### ISSUE TITLE
[Eloquent] Polymorphic M2M Detach detaches all entries on passing an empty array

### ISSUE THREAD

**Issue by sreeram-boyapati** [laravel/framework#18670]
- Laravel Version: 5.2.45
- PHP Version: 7.0
- Database Driver & Version: MySQL

### Description:
Eloquent M2M detach function detaches the records when we pass Ids of the entities from the pivot table.
By that logic, If we pass an empty array to detach, It detaches all records in the pivot table.

### Steps To Reproduce:
1. Create a polymorphic relationship. For example, Tags, Post, User. The user can have tags and post can have tags.
2. Add entries to the user <-> tags pivot table using sync or attach.
```php
$user->tags()->sync($ids);
```
3. Pass an empty array to detach tags. 
```php
$user->tags()->detach([]);
```
It detaches all the tags for the user.

**Comment by themsaid** [comment]
5.2 is out of support, please upgrade to a new version and test again.
