### ISSUE TITLE
Model::with() miss when foreign key length gt 9223372036854775807

### ISSUE THREAD

**Issue by lanyanguang32** [laravel/framework#18676]
- Laravel Version: 5.4
- PHP Version: 7.1
- Database Driver & Version:

### Description:

model relations customer->merged_trade  foreign key  len 20 string
ex:  customer_id : 13469135782229932224

Customer::with('orders')->get();

dd(querylog)

array:3 [
  0 => array:3 [
    "query" => "select * from `customer` where `customer`.`customer_id` = ? limit 1"
    "bindings" => array:1 [
      0 => "13469135782229932224"
    ]
    "time" => 2.89
  ]
  1 => array:3 [
    "query" => "select * from `merged_trade` where `merged_trade`.`customer_id` in (?)"
    "bindings" => array:1 [
      0 => 9223372036854775807
    ]
    "time" => 0.9
  ]
  2 => array:3 [
    "query" => "select * from `customer`"
    "bindings" => []
    "time" => 0.68
  ]
]

**Comment by themsaid** [comment]
What do you mean by `miss`?

**Comment by lanyanguang32** [comment]
no result collection,  the "query" => "select * from merged_trade where merged_trade.customer_id in (?)"
"bindings" => array:1 [
0 => 9223372036854775807
]
customer_id should be the same value 13469135782229932224, 
but with() merged_trade table bindings param convert to 9223372036854775807, this value(9223372036854775807) is out of int value

**Comment by sisve** [comment]
The customer_id `13 469 135 782 229 932 224` is larger than a 64 bit signed value `PHP_INT_MAX = 2^63 - 1 = 9 223 372 036 854 775 807`, thus it cannot be treated as an integer in php. It will automatically convert that value into a floating point number, losing precision in the process.

> If the float is beyond the boundaries of integer (usually +/- 2.15e+9 = 2^31 on 32-bit platforms and +/- 9.22e+18 = 2^63 on 64-bit platforms other than Windows), the result is undefined, since the float doesn't have enough precision to give an exact integer result. No warning, not even a notice will be issued when this happens!
Source: https://secure.php.net/manual/en/language.types.integer.php

    $x = 13469135782229932224;
    var_dump($x);      // float(1.346913578223E+19)
    var_dump((int)$x); // int(-4977608291479619584)

Is this number really an auto incrementing value? Do you really have one billion times more customers that there are living humans on earth?

If this values comes from an external system, then treat it as a string and natural key. Add it into another column with an index, and add a normal primary key to your table instead.
