### ISSUE TITLE
MakesHttpRequests::Call() makes `+` to spaces.

### ISSUE THREAD

**Issue by uruloke** [laravel/framework#18688]
- Laravel Version: 5.3.31 | 5.4
- PHP Version: 7.1.0 
- PHPUnit Version: 4.8.35

### Description:
When testing an API, the query parameters are not being encoded correctly, as `parse_str` decodes an url, which turns symbols like `+` into a ` `(space). 

This means when testing query data which has `+`, you get unexpected behaviour.
This issue might be Symfony related, as this is from [Symfony Request line 417](https://github.com/symfony/http-foundation/blob/master/Request.php#L417)

A small test shows this is also related to current version of Laravel, as [Call method](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php#L228) is working the same way in 5.4 as in 5.3.

### Steps To Reproduce:
- Create a route and a test for it.
- `$this->getJson('route?filter=data+cool')`.
- Look at the query parameters and see the `+` is now a ` `(space).

**Comment by themsaid** [comment]
`+` in a query string represents a space, if you want a literal + you need to use `%2B`, I don't see how this is a bug.
