### ISSUE TITLE
Make use of redirectTo property or method and finaly remove hardcoded '/home' path

### ISSUE THREAD

**Issue by coolynx** [laravel/framework#18681]
- Laravel Version: 5.4.17
- PHP Version: 7.0.16
- Database Driver & Version: mysqld 10.1.21-MariaDB

### Description:
Current Laravel 5.4 documentation explains how to use Authentification with [Path customization](https://laravel.com/docs/5.4/authentication#authentication-quickstart).

> When a user is successfully authenticated, they will be redirected to the `/home` URI. You can customize the post-authentication redirect location by defining a `redirectTo` property on the `LoginController`, `RegisterController`, and `ResetPasswordController`:
>
> `protected $redirectTo = '/';`

If you do like it says and define your home URI different than `/home` you have a problem.

The last place where this URI is left hardcoded is in the [`RedirectIfAuthenticated` middleware](https://github.com/laravel/laravel/blob/master/app/Http/Middleware/RedirectIfAuthenticated.php).

As we can see from [history](https://github.com/laravel/laravel/commits/master/app/Http/Middleware/RedirectIfAuthenticated.php), it was change from one location to another but none is going to be good while it is hardcoded.

```php
        if (Auth::guard($guard)->check()) {
            return redirect('/home');
        }
```
Previous mentions of this issue: #17092, #15523, #9634

### Steps To Reproduce:

1. Install Laravel Authentification
2. Set `protected $redirectTo = '/dashboard';` in all Controllers `LoginController`, `RegisterController`, and `ResetPasswordController`.
3. Log in

#### Case Nr.1 - Reset password

4. Click browser back button
5. Click on forgot password link
6. Page not found '/home'

#### Case Nr.2 - Email with reset password information

4. Open email with password reset information
5. Click on Reset password link
6. Page not found '/home'

#### Case Nr.3 - Log in

4. Click browser back button
5. Click on Log in link
6. Page not found '/home'

#### Case Nr.4 - Register

4. Click browser back button
5. Click on Sign up link
6. Page not found '/home'

### Possible solution:

1. Make it clear in documentation that you need to manually change the URI in `RedirectIfAuthenticated` middleware as well.
2. Make use of `redirectTo` property or method in `RedirectIfAuthenticated` middleware as it is currently written in documentation. 👍

**Comment by Dylan-DPC** [comment]
The `RedirectIfAuthenticated` middleware is in App namespace. You have full control over it and can modify. 

Since you are suggesting a change in the docs, you should create an issue (and possible PR) in the laravel/docs repo
