### ISSUE TITLE
Laravel 5.4 DatabaseMigrations trait should seed the database

### ISSUE THREAD

**Issue by Kyosfonica** [laravel/framework#18691]
- Laravel Version: 5.4.17
- PHP Version: 7.1.3
- Database Driver & Version: mysql

### Description:
When runing tests using the DatabaseMigration trait the database is recreated for each test group but it is not seeded.

### Steps To Reproduce:
Just use the tool.

### Resolution
I have modified the class with the following:
        $this->artisan('migrate');
        $this->artisan('db:seed');

And after this change all my tests use a clean and seeded database.

**Comment by themsaid** [comment]
It might not suit every application needs :) You can do that in your own project.
