### ISSUE TITLE
Migration / Artisan::call('db:seed'.....) not working when APP_ENV=production

### ISSUE THREAD

**Issue by xxRockOnxx** [laravel/framework#18692]
- Laravel Version: 5.3.31
- PHP Version: 7.1.2
- Database Driver & Version: MariaDB 10.1-22

### Description: This snippet doesn't work when migrating: https://www.hastebin.com/etapejuhuj.php

I have a minimal `.env` file on my production. It contains some API key only and DB credentials. It doesn't work whatever I do. Tried `--force` when migrating but still not working. I logged the queries being run I thought it was just slow but it's not. It doesn't proceed to next migration.

It does work tho if I put `APP_ENV=local` or `APP_ENV=development`. Doesn't work if it's `production`. And to double-check I even tried `APP_ENV=production` and yes. Confirmed.

### Steps To Reproduce:
1 - Try making migration using my snippet.
2 - Have no `APP_ENV` in `.env` file or set it to `production`
3 - `php artisan migrate`
4 - get stucked.

BTW, Seeder file is just `DB::table('provinces')` inserts. So try making even a simple one.

**Comment by brunogaspar** [comment]
Don't you also need to pass the force into the Artisan db:seed call as well?

**Comment by xxRockOnxx** [comment]
It worked. How could I not think of that?

**Comment by jamesexperts** [comment]
Perfect it works

**Comment by premmohantyagi** [comment]
Perfect it works
