### ISSUE TITLE
Auth middleware "Authorize" call authenticate() method which is not in contracts

### ISSUE THREAD

**Issue by roquie** [laravel/framework#18693]
- Laravel Version: 5.4.17
- PHP Version: 7.1

### Description:

Contract `\Illuminate\Contracts\Auth\Factory` have two methods `guard` and `shouldUse`. This middleware call `authenticate()` method in `handle()` from concrete object ignoring interface. 
I'm got this error `Call to undefined method App\Guards\SentinelGuard::authenticate()` when use another guard with `can:*` middleware`->middleware('can:create,\App\User')`.

https://github.com/laravel/framework/blob/5.4/src/Illuminate/Auth/Middleware/Authorize.php#L53
https://github.com/illuminate/contracts/search?utf8=%E2%9C%93&q=authenticate&type=

### Steps To Reproduce:

* register a custom driver
```php
\Auth::extend('sentinel', function ($app) {
     return new SentinelGuard($app['sentinel']);
});
```
* implement it
* edit `auth.php` config
```php
'guards' => [
   'web' => [
       'driver' => 'sentinel',
       'provider' => 'users',
   ],
  // ...
],
```
* register route
```php
$router->post('users', 'UserController@create')
    ->name('user.create')
    ->middleware('can:create,App\User');
```
* send post request to `http://localhost:8000/users` for get an error.

**Comment by lagbox** [comment]
#18315 another issue related to contracts and `authenticate` method
