### ISSUE TITLE
Change default password column error.

### ISSUE THREAD

**Issue by webwizo** [laravel/framework#18696]
- Laravel Version: 5.4.17
- PHP Version: 7.1.1
- Database Driver & Version: MySQL 5.5.42

### Description:
I am using Auth and trying to change the Password column which is by default "password".
Whenever I try to login it gives me an error from following file and line
[EloquentUserProvider](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Auth/EloquentUserProvider.php#L105)
I think it is define hardcoded a password column, i guess.

Can anyone look into please?

### Steps To Reproduce:
N/A

**Comment by themsaid** [comment]
Yes there has to be a password column if you tend to use EloquentUserProvider

**Comment by laurencei** [comment]
@themsaid - he is saying that "password" is hardcoded as the name of the column.

What happens if you are using a different column name?

**Comment by fonini** [comment]
I would like to be able to override the `password` column name, as we can do with the `username`.

**Comment by lagbox** [comment]
The password for the model is known via the `Authenticatable` Contract (`getAuthPassword`). The field in the credentials has to be `password` when passed to `attempt` so the provider knows which field it is going to do the hash check upon and which field to not search against with the query. 

You can override the `credentials` and `validateLogin` to make this adjustment if needed. Example:

```php
public function credentials(Request $request)
{
    return $request->only($this->username()) + ['password' => $request->input('your_form_field')];
}
```

**Comment by laurencei** [comment]
I suppose a better question is why does anyone even need to change the column from the name `password`?

i.e. what is a use case that warrants a change to the framework to support it?

**Comment by lagbox** [comment]
You don't need to change what is passed to `attempt`.
This issue seems to be about the 'form field name'.

**Comment by mcklayin** [comment]
Will be good if in next  commits will be method to getting password field name like username:
```
Illuminate\Foundation\Auth\AuthenticatesUsers.php

  /**
     * Get the login username to be used by the controller.
     *
     * @return string
     */
    public function username()
    {
        return 'email';
    }
   public function password()
    {
        return 'password';
    }

```

**Comment by lagbox** [comment]
@mcklayin with the fact a PR( #18723 ) to do just that was closed and the answer is usually to 'override' what you need, I dont see that happening ;-)
