### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by afabros** [laravel/framework#18702]
- Laravel Version: #.#.#
- PHP Version:
- Database Driver & Version:

**Comment by afabros** [comment]
{{trans('file.word',[],null,'en')}},

before 5.4, this code will force a translation in english.
after 5.4, the translation used is the setting on App::setLocale.

The forced translation is needed in case of email notifications where the receiver has a different language.

How to force translate in 5.4?

**Comment by themsaid** [comment]
`{{trans('file.word',[],'en')}}`

**Comment by afabros** [comment]
worked! thank you!^^

**Comment by themsaid** [comment]
welcome :)
