### ISSUE TITLE
Token mismatch on inactive application

### ISSUE THREAD

**Issue by yadavaditya0** [laravel/framework#18704]
- Laravel Version: 5.2
- PHP Version: 7.0
- Database Driver & Version: MySQL

### Description:
Token mismatch error in inactive application, every time when I get back after a long time get token mismatch error.
### Steps To Reproduce:
Create a form leave this form for a while and then submit it. You will get token miss match error.

**Comment by Dylan-DPC** [comment]
Not a bug. You can change the token duration. Use the forums or the slack channel to solve your issue

**Comment by ThunderBirdsX3** [comment]
Try this.
http://stackoverflow.com/questions/31846788/handle-tokenmismatchexception-in-laravel-5
