### ISSUE TITLE
validation rules of "email" and "email|same" should be case insenstive?

### ISSUE THREAD

**Issue by codemonkeynorth** [laravel/framework#18714]
- Laravel Version: 5.4

probably this may counts as a specific use case, but really would be standard... email addresses are presumably the same if the lowercase version matches. I guess I could just put in custom validation rule in the providers etc. 

Would be useful to be able to pass a "same:email(insensitive)" rule or something like that though

thanks
j

**Comment by Dylan-DPC** [comment]
Kindly post this proposal in the laravel/internals repo. This repo is for bug tracking. Thanks :)

**Comment by codemonkeynorth** [comment]
will do thanks
