### ISSUE TITLE
Error with email components

### ISSUE THREAD

**Issue by rorc** [laravel/framework#18727]
- Laravel Version: 5.4.17

### Description:

I send mail:
```php
    public function build()
    {
        return $this->to($this->recipients[$this->svertka->status_id])
            ->view('admin.emails.svertka.status-changed')
            ->with('comment', $this->svertka->comments()->latest()->first()->body);
    }
```

And have a view:
```php
@component('mail::message')

    <h1>{{ $svertka->status->name }}</h1>

    <blockquote>{{ nl2br($comment) }}</blockquote>

    @component('mail::button', ['url' => route('svertka.show', $svertka)])
        Открыть в админке
    @endcomponent

@endcomponent
```

But on send mail i got error `No hint path defined for [mail]. (View: D:\WEB\domains\gb\resources\views\admin\emails\svertka\status-changed.blade.php)`

I guess, script cant find default template for components, but template is here http://joxi.ru/brR8PzGcKzbL21

**Comment by themsaid** [comment]
You need to use `-> markdown()` instead of `->view()`, these components are not available unless you use markdown emails.

https://laravel.com/docs/5.4/mail#markdown-mailables

**Comment by racay** [comment]
> You need to use `-> markdown()` instead of `->view()`, these components are not available unless you use markdown emails.
> 
> https://laravel.com/docs/5.4/mail#markdown-mailables

oh my God, thanks a lot man. i looking everywhere for this simple solution.
