### ISSUE TITLE
$request->has('photo') returns false when uploading a file.

### ISSUE THREAD

**Issue by CrestApps** [laravel/framework#18735]
- Laravel Version: v5.3.31
- PHP Version: 5.6.24
- Database Driver & Version: N/A

### Description:
When I check to see if a request has an uploaded file, the method `request->has('photo');` returns `false` even when the request has a file.

I created a form with few inputs. One of the inputs, allows uploading file. In the method that handles the request, I did this following

`dd($request->all(), $request->has('photo'));`

The first output shows 'photo' but the second output returns false. Here is a screenshot.
![screenshot_1](https://cloud.githubusercontent.com/assets/24724371/24831756/0c056994-1c55-11e7-8c92-e31a51e5c9e2.png)

Not sure if this is a bug or intended to work this way. But this is what I have done instead

    $file = Input::file('photo');

    if( $file && $file->isValid() )
    {
        .....
    }

**Comment by caiquecastro** [comment]
Try $request->hasFile('photo')

**Comment by caiquecastro** [comment]
You should read the docs: https://laravel.com/docs/5.4/requests#files

**Comment by srmklive** [comment]
First read the docs. The correct method to do this is" `$request->hasFile('photo')`.

**Comment by lcardosozago** [comment]
I have the same problem... $request->hasFile('whatever') returning false

**Comment by lcardosozago** [comment]
I have the same problem... $request->hasFile('file') returning false

**Comment by jonaswebdev** [comment]
Maybe can be the "PHP max upload file size", I had this here ;)

**Comment by nanyKuzola** [comment]
i'm getting the same error

**Comment by joscript** [comment]
getting the same error $request->hasFile('file') returning false

**Comment by rjruiz-dev** [comment]
Tengo el mismo error he cambiado el tamaño maximo a 2mb, incluso verificando dd($request-> hasFile ('user_photo'));
y devuelve false
alguna sugerencia?

**Comment by zerobity** [comment]
Igual, tengo configurado 20mb y no puedo cargar mas pequeñas.
