### ISSUE TITLE
laravel webpack run related

### ISSUE THREAD

**Issue by tejomayonline** [laravel/framework#18747]
- Laravel Version: 5.4.16
- PHP Version:7.0.17
- Database Driver & Version:5.5.54

### Description:

With  a fresh *laravel 5.4* install when I install npm locally to the project,webpack (npm run dev/prduction) gives me error.I have find it multiple times.here is the error description.

```
> @ dev /var/www/html/oo
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js


/var/www/html/oo/node_modules/cross-env/dist/index.js:30
roc = (0, _crossSpawn.spawn)(command, commandArgs, { stdio: 'inherit', env });
                                                                           ^
SyntaxError: Unexpected token }
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/html/oo/node_modules/cross-env/dist/bin/cross-env.js:4:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0
```

### Steps To Reproduce:
please install a fresh laravel then npm install,after that run webpack ,may get that error. Thank you.

**Comment by tejomayonline** [comment]
I have google it about the issue.I have got some point to implement.After that the bug is  there ,no change.And online I have found that many windows user faced that problem.I'm using ubuntu 14.04 LTS with php 7.0

**Comment by themsaid** [comment]
Can you remove `node_modules` and try tor un `yarn` and then try again?

**Comment by srmklive** [comment]
I got the same error but i fixed by removing `node_modules` and then ran command `yarn install`.

**Comment by ankurk91** [comment]
Laravel mix related issues should be reported on [Laravel-mix](https://github.com/JeffreyWay/laravel-mix) repo.
What is your node-js version BTW ?

**Comment by ilhamdoanggg** [comment]
i using yarn and some not found laravel mix

this is output 
`info No lockfile found.
[1/4] Resolving packages...
warning laravel-mix > browser-sync > localtunnel > request > node-uuid@1.4.8: Use uuid module instead
[2/4] Fetching packages...
warning fsevents@1.1.2: The platform "linux" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/5] ⠄ gifsicle
[2/5] ⠄ mozjpeg
[3/5] ⠄ optipng-bin
[4/5] ⠄ pngquant-bin
error /home/user/project/laravel/node_modules/node-sass: Command failed.
Exit code: 127
Command: sh
Arguments: -c node scripts/install.js
Directory: /home/user/project/laravel/node_modules/node-sass
Output:
sh: 1: node: not found`


what should i do
