### ISSUE TITLE
Artisan error

### ISSUE THREAD

**Issue by m1guelpf** [laravel/framework#18759]
- Laravel Version: v5.4.17
- PHP Version: 7.1
- Database Driver & Version: MySQL 14.14

### Description:
Every time I run an artisan command, I get this error:
```
[Symfony\Component\Debug\Exception\FatalThrowableError]                      
  Type error: Argument 2 passed to Illuminate\Routing\UrlGenerator::__constru  
  ct() must be an instance of Illuminate\Http\Request, null given, called in   
  /home/m1guelpiedrafita/www/composer-ci/vendor/laravel/framework/src/Illumin  
  ate/Routing/RoutingServiceProvider.php on line 64
```

### Steps To Reproduce:
Clone my proyect (semi-fresh laravel install) https://github.com/m1guelpf/laravel-quickstart, composer update && php artisan list

**Comment by m1guelpf** [comment]
Fixed

**Comment by MohamedELSerag88** [comment]
how did you solve it?
