### ISSUE TITLE
Validate string contain '|' character using FormRequest

### ISSUE THREAD

**Issue by hoangquanghuy** [laravel/framework#18751]
- Laravel Version: 5.4.#
- PHP Version: 7.0.#
- Database Driver & Version: 5.7.#

### Description:
validate string contain '|' character.

### Steps To Reproduce:

I'm validate form request such as input name="group_name".
Form request:
```
return [
'group_name'    => "unique:groups,group_name,NULL,id,name,".$this->request->get('name')
]
```

For example, input `group_name` submit is '|demoString'

And error:
```
Whoops, looks like something went wrong.

1/1
BadMethodCallException in Validator.php line 1067:
Method [validateDemoString'] does not exist.
in Validator.php line 1067
at Validator->__call('validateDaksud\'', array('group_name', 'aasdsdasd', array(), object(Validator))) in Validator.php line 338
at Validator->validateAttribute('group_name', 'Daksud\'') in Validator.php line 253
at Validator->passes() in ValidatesWhenResolvedTrait.php line 23
at FormRequest->validate() in FormRequestServiceProvider.php line 31
```

**Comment by sisve** [comment]
The | has special meaning when passing rules as strings, as a separator between rules, but I believe it wouldn't be used for that purpose if you passed in a array instead.

    return [
        'group_name'    => [
            "unique:groups,group_name,NULL,id,name,".$this->request->get('name')
        ]
    ]

**Comment by laurencei** [comment]
You could also use the new `Rule::unique()` method as well: https://laravel.com/docs/5.4/validation#rule-unique
