### ISSUE TITLE
create soap and wsdl

### ISSUE THREAD

**Issue by blueblazerchrist** [laravel/framework#18761]
- Laravel Version: 5.4.*
- PHP Version: 7
- Database Driver & Version: 

### Description:

I want to know if it is possible to create a soap server with wsdl

**Comment by deleugpn** [comment]
Yes.

**Comment by blueblazerchrist** [comment]
alugna sugeerencia..?
Any suggestion..?

**Comment by Dylan-DPC** [comment]
@blueblazerchrist this repo is for bug tracking. Use the forums or the slack channel to solve your issues

**Comment by srmklive** [comment]
Use the forums for such issues.

**Comment by vchiarello** [comment]
Sorry @blueblazerchrist did you find a solution for your issue? I'm trying to create a soap web service with laravel but with no success.
Thanks in advance.
