### ISSUE TITLE
Migration - float() creates DOUBLE instead of FLOAT

### ISSUE THREAD

**Issue by steveheinsch** [laravel/framework#18776]
- Laravel Version: 5.4.16
- PHP Version: PHP 7.1.1-1+deb.sury.org~xenial+1 (cli) (built: Jan 20 2017 09:20:20) ( NTS )
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.7.17, for Linux (x86_64) using  EditLine wrapper

### Description:
In a migration, using the float() type actually creates a double()

### Steps To Reproduce:
```
public function up()
{
    Schema::create('test_table', function (Blueprint $table) {
        $table->increments('id');
        $table->float('test', 5, 2);
        $table->timestamps();
    });
}
```
<img width="605" alt="screen shot 2017-04-11 at 9 02 18 am" src="https://cloud.githubusercontent.com/assets/8584497/24918605/ccc736ca-1e95-11e7-830e-d4bcdd637746.png">

**Comment by themsaid** [comment]
Check https://github.com/laravel/framework/issues/9103

**Comment by joeyfrich** [comment]
What should I put in my migration to get an actual MySQL float rather than a double?  The linked issue #9103 is not helpful

**Comment by olivierr91** [comment]
@themsaid I and many people on the Internet are having the same issue with no answers. Please clarify the docs for this highly unintuitive function or tell us what we need to put to get a float. `$table->float('abc', 4)` still creates a double.

**Comment by slowestwind** [comment]
Best solution I will suggest : https://stackoverflow.com/a/69282017/16897541...
