### ISSUE TITLE
.env is not loaded when .env.testing is

### ISSUE THREAD

**Issue by KristofMorva** [laravel/framework#18772]
- Laravel Version: 5.4.17
- PHP Version: 7

### Description:
According to the documentation 
> You may also create a .env.testing file. This file will override values from the .env file when running PHPUnit tests or executing Artisan commands with the --env=testing option.

However, as it seems for me, it's not how it works. It's loaded **INSTEAD OF** `.env`, but it should just override the values.

### Steps To Reproduce:
Copy your valid `.env` file as `.env.testing`. The unit testing should work as expected. Now remove the `APP_KEY` from `.env.testing`. Unit testing breaks now.

**Comment by m1guelpf** [comment]
@KristofMorva 
> Create a valid .env file with APP_KEY, and an empty .env.**example**. The unit testing should break. Now copy the APP_KEY to .env.**example**. Now everything should be fine.

You meant `.env.testing`, rigth?

**Comment by KristofMorva** [comment]
@m1guelpf yes, sorry for that, fixed! :)

**Comment by srmklive** [comment]
When you are creating a new `.env` file, all the configuration you need to generate should  be specific to that file. Since `.env.testing` is for testing only, you should always a `APP_KEY` for `.env.testing` like:

```
php artisan key:generate --env=testing
```

**Comment by KristofMorva** [comment]
@srmklive my problem is not the `APP_KEY`, that's just for reproducing. My problem is, it's not working as stated in the documentation. In my scenario for example I have ~10 private keys, which are used for various services - certainly both locale and testing environment use the sandbox keys, so currently I have to manage the keys in two configs, always copying one to another - it wouldn't be necessary, if handling `.env.testing` was working as stated.

**Comment by srmklive** [comment]
It is not necessarily an error in my opinion with the framework. My opinion is that `env` files are for development purposes only. 

@themsaid @GrahamCampbell  Your thoughts?

**Comment by KristofMorva** [comment]
`.env` files are present on production environments too, it's not only for development. And you may still miss the point: if that's the way it works, the documentation shouldn't say it otherwise.

**Comment by themsaid** [comment]
Yes only 1 file is loaded, and by `override values` we mean it'll load the values from that file not the `.env` file.

**Comment by reinink** [comment]
FWIW, it would be really nice if these additional environment variables _did_ override values from the main .env file. Quite often locally I have all my environment variables defined, and then only tweak on or two values for the unit tests or Dusk tests.

It would mean loading more than one .env file though.

**Comment by reinink** [comment]
You could even add some crazy extends features. :feelsgood:

```
@extends(.env)

DB_DATABASE=testing
```

**Comment by KristofMorva** [comment]
@reinink or just an ENV_PARENT or something like that, which does not involve altering the .env loading package. But even without it, just loading .env file as a parent default would make env files less boilerplate.

**Comment by trevorgehman** [comment]
Man the documentation is really confusing on this point. 

> This file will override values from the .env file when running PHPUnit tests

In fact it doesn't override values from the .env file. It doesn't depend on the .env file at all. Am I missing something?

**Comment by reinink** [comment]
Doesn't it use `.env` unless `.env.testing` is present? In that case it sort of does "override" them, in that it uses a totally different file instead, if present. That said, I totally agree, this threw me off as well.

**Comment by reinink** [comment]
Might be best for someone to simply craft a PR to make this documentation a little more clear?

**Comment by trevorgehman** [comment]
Yeah I think "This file will override the .env file when running PHPUnit tests..." would be much clearer.

**Comment by reinink** [comment]
Sounds like a great PR. :)

![proceed](https://user-images.githubusercontent.com/882133/33083978-c39d5ee8-ceae-11e7-8237-68d641d95b94.gif)

**Comment by amcsi** [comment]
So how are we supposed to override values that are in `.env.testing` when running tests?

I know that in `phpunit.xml` you can have testing defaults and override those with an unversioned `.env.testing` file. But that only works for PHPUnit.

I would rather have `.env.testing` versioned so that I could run a fresh migration of the test db just by running `APP_ENV=testing php artisan migrate:fresh`.

But then that brings about the problem that I could only have a single set of test db credentials there, and my colleagues wouldn't have any simple way to override them if their local db is using a different username, password or db name.
