### ISSUE TITLE
unreadNotifications limit and count without getting.

### ISSUE THREAD

**Issue by mediaceh** [laravel/framework#18789]
- Laravel Version: 5.3.23
- PHP Version:
- Database Driver & Version:

I have issue with users which not read his own notifications. They have more than 1000 unread notifications.
In result i have error with 'Allowed memory size of 134217728 bytes exhausted'. Not, I don't want increase my memory limit. I want get count a unread notifications and ten or twenty last notifications.
How i can do it?

**Comment by themsaid** [comment]
This is something you need to fix in your application, find out what query is consuming all this memory and try to handle it in a better way.

**Comment by mediaceh** [comment]
What? It is standard framework functional described in the docs:

"If you want to retrieve only the "unread" notifications, you may use the unreadNotifications relationship. Again, these notifications will be sorted by the created_at timestamp"

It is not provide getting count and limit. 

For me I can use any way. Though raw sql and other. 

In described case it is framework bug. To fix it me need don't use framework functional in my application.

**Comment by mediaceh** [comment]
I try get count of records as `auth()->user()->unreadNotifications()->count()` and have error: 

`SQLSTATE[42000]: Syntax error or access violation: 1140 Mixing of GROUP columns (MIN(),MAX(),COUNT(),...) with no GROUP columns is illegal if there is no GROUP BY clause (SQL: select count(*) as aggregate from `notifications` where `notifications`.`notifiable_id` = 1 and `notifications`.`notifiable_id` is not null and `notifications`.`notifiable_type` = App\User and `read_at` is null order by `created_at` desc) `

For limit now i use: 
`auth()->user()->unreadNotifications()->take(10)->get()` 
and it work.

**Comment by mediaceh** [comment]
oK, I got count unread notifications as `auth()->user()->unreadNotifications()->groupBy('notifiable_type')->count()`

**Comment by deliaahm** [comment]
I use this code for limit notifications :
auth()->user()->unreadNotifications->take(4)->get()

but i get this error :
![image](https://user-images.githubusercontent.com/38059468/38654096-e8312638-3e37-11e8-8993-0091f2394de2.png)

Laravel version : 5.4
Anyone can help me? :(

**Comment by waseem7582** [comment]
fsgggdf

**Comment by waseem7582** [comment]
oK, I got count unread notifications as auth()->user()->unreadNotifications()->groupBy('notifiable_type')->count()
