### ISSUE TITLE
Update to 5.4, package middleware not working

### ISSUE THREAD

**Issue by isomis** [laravel/framework#18787]
- Laravel Version: 5.4
- PHP Version: 5.6.14
- Database Driver & Version: mysql

in 5.3 everything works great:

    public function boot(\Illuminate\Routing\Router $router)
    {
        $this->loadRoutesFrom(__DIR__.'/Routes/backend.php');

        $router->middlewareGroup('hideyobackend', array(
                \App\Http\Middleware\EncryptCookies::class,
                \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
                \Illuminate\Session\Middleware\StartSession::class,
                \Illuminate\View\Middleware\ShareErrorsFromSession::class,
                \App\Http\Middleware\VerifyCsrfToken::class,
                \Illuminate\Routing\Middleware\SubstituteBindings::class,
                \Krucas\Notification\Middleware\NotificationMiddleware::class
            )
        );

        $router->middleware('auth.test.backend', \Test\Backend\Middleware\AuthenticateAdmin::class);
    
In 5.4 i get this error from routes:

Class auth.test.backend does not exist

Is there a change in pushing middleware?

I found this ticket: https://github.com/laravel/framework/issues/6211 and it works in 5.3, but not in 5.4

**Comment by isomis** [comment]
I used: $router->aliasMiddleware, that works. 

I think it will be great to make this documentation better: https://laravel.com/docs/5.4/packages 

Telling something about middlewares.

**Comment by themsaid** [comment]
Yes it was renamed to `aliasMiddleware`, it's mentioned in the upgrade guide https://laravel.com/docs/5.4/upgrade
