### ISSUE TITLE
Laravel migrate postgres comment() don't work

### ISSUE THREAD

**Issue by HaroldV** [laravel/framework#18782]
- Laravel Version: 5.4
- PHP Version: 7.0
- Database Driver & Version: Postgresql

### Description:
Do not work function comment in the migration with postgresql

### Steps To Reproduce:
this is in the migrate = $table->string('name',35)->nullable(false)->comment('Status Name');
I execute migrate and nothing

**Comment by Dylan-DPC** [comment]
@HaroldV steps to reproduce?

**Comment by HaroldV** [comment]
this is in the migrate = $table->string('name',35)->nullable(false)->comment('Status Name');
I execute migrate and nothing

**Comment by andrey-helldar** [comment]
Maybe, `There is no COMMENT command in the SQL standard.`
https://www.postgresql.org/docs/9.5/static/sql-comment.html

**Comment by marcelogarbin** [comment]
Did you find any solution?

**Comment by HaroldV** [comment]
no marcelogarbin :(

**Comment by ghunti** [comment]
I have the same issue.
For now I'm issuing a new command just for the command: `DB::select("COMMENT ON COLUMN table_name.column_name IS 'the comment'");`

**Comment by diego0037** [comment]
I made a project with the versions that you wrote, i think is a problem with your postgres version, test with 9.4 version or later.
I made in the migration:   
public function up()
    {
      Schema::create('table_name', function (Blueprint $table) {
          $table-> string('name', 35)->nullable(false)->comment('Status Name');
        });
    }

**Comment by ghunti** [comment]
@diego0037 The command you wrote creates the column but it doesn't create the comment. Did you check if you have the comment on that column with a postgresl client?? Looking at Laravel source code I don't think it supports comments for Postgresql but I might be wrong.
I'm using Postgres 9.6 and I had to do the manual comment with a `DB::statement`.

**Comment by vaughany** [comment]
I can confirm that in Postgres 9.5.7, the following snippet creates a `char` column but without a comment:

```
$table->char('char')->default('some default')->comment('this is a comment');
```
`\d+ test` command in `psql`:

```
Column  |      Type      |                 Modifiers                 | Storage  | Stats target | Description 
--------+----------------+-------------------------------------------+----------+--------------+-------------
char    | character(255) | not null default 'some default'::bpchar   | extended |              | 
```

**Comment by bardrotzer** [comment]
I'm not sure how to implement this, but looking at the documentation for postgres it implements a different syntax for adding comments. As of today only MySql comments are supported for Laravel.

Something along this line would be needed to get comments working in PostgresGrammar.php

```php
    protected function modifyComment(Blueprint $blueprint, Fluent $column)
    {
        if (! is_null($column->comment)) {
            return " COMMENT ON COLUMN ". getColumnNameMethod()." '".addslashes($column->comment)."';"
        }
    }
```

I have not tested this as I am quite new with laravel. 

Any ideas if this may work?

**Comment by mfn** [comment]
I believe this issue can be closed; the references PR implements this for postgres.
