### ISSUE TITLE
[5.4]Request::hasFile work wrong when check twice

### ISSUE THREAD

**Issue by aegeansea** [laravel/framework#18785]
- Laravel Version: 5.4.17
- PHP Version:7.0.10 
- Database Driver & Version:

### Description:
Request::hasFile work wrong when check twice,
not work with Request::duplicate() (when change the files parameter ) and $request->files->add(),
because the Request::convertedFiles attribute was cached by Request::allFiles() method

### Steps To Reproduce:
Route::get('/check', function (\Illuminate\Http\Request $request) {
    $request->files->add(
        [
            'doc' => [
                "name" => "upload.log",
                "type" => "text/plain",
                "tmp_name" => "/home/vagrant/test/storage/app/upload.log",
                "error" => 0,
                "size" => 7,
            ]
        ]);
    //check
    $request->hasFile('doc'); //true

    $request->files->add(
        [
            'doc1' => [
                "name" => "upload.log",
                "type" => "text/plain",
                "tmp_name" => "/home/vagrant/test/storage/app/upload.log",
                "error" => 0,
                "size" => 7,
            ]
        ]);

    $request->files->add(
        [
            'doc2' => $request->file('doc')
        ]);

    dd(
        $request->hasFile('doc'), //true
        $request->hasFile('doc1'), //false
        $request->hasFile('doc2') //false
    );
});

Route::get('/not_check', function (\Illuminate\Http\Request $request) {
    $request->files->add(
        [
            'doc' => [
                "name" => "upload.log",
                "type" => "text/plain",
                "tmp_name" => "/home/vagrant/test/storage/app/upload.log",
                "error" => 0,
                "size" => 7,
            ]
        ]);
    //not check
    //$request->hasFile('doc');

    $request->files->add(
        [
            'doc1' => [
                "name" => "upload.log",
                "type" => "text/plain",
                "tmp_name" => "/home/vagrant/test/storage/app/upload.log",
                "error" => 0,
                "size" => 7,
            ]
        ]);

    $request->files->add(
        [
            'doc2' => $request->file('doc')
        ]);

    dd(
        $request->hasFile('doc'), //true
        $request->hasFile('doc1'), //true
        $request->hasFile('doc2') //false
    );
});

**Comment by morloderex** [comment]
Why are you manipulating the files array in the request directly anyway?
What is your reasoning behind this?

**Comment by themsaid** [comment]
Yes the request object is not intended to be manipulated this way, please share your use case on the forums so that people can help you find a better alternative to what you want to achieve.

**Comment by aegeansea** [comment]
thank for help,I have worked out this problem before submit the issue.
And the problem is when I transmit a request with multi files uploaded to single renamed key file uploaded request, 
use the request:: duplicate() method, so when I use new request I duplicate to check whether the file exists by hasFile() method, it returns false.
I thought it maybe a bug so I report it.
