### ISSUE TITLE
[5.4] Authorizing Channel

### ISSUE THREAD

**Issue by kvnbai** [laravel/framework#18784]
- Laravel Version: 5.4
- PHP Version: 7.1
- Database Driver & Version: (doesnt matter. lol)

As per docu (https://laravel.com/docs/5.4/broadcasting#broadcast-queue):

> Remember, users must be authorized to listen on private channels. We may define our channel authorization rules in the routes/channels.php file

I have implemented the real-time functionality by tracing the framework's flow during event fire (to know what is the exact channel and namespace to subscribe) then just use nodejs as a subscriber of redis's published events (through laravel's broadcaster) then forward the data to the front-end. However I can't find where `Illuminate\Broadcasting\Broadcasters\Broadcaster@verifyUserCanAccessChannel` or `Illuminate\Broadcasting\Broadcasters\RedisBroadcaster@auth` is triggered. Tho you can check the authorization anywhere (node, controller, acl or even view lol) in some ways, for the sake of separation I would like to know where does the authorization in `channels.php` get triggered. To add a note, I don't use laravel echo, pusher, vue or laravel packages in github for this feature. Thanks!

channels.php
```
// this doesnt fire
Broadcast::channel('test-channel', function ($user, $id) {
    return false;
});
```

Look a-like event:
```
<?php

namespace App\Events;

use Illuminate\Broadcasting\Channel;
use Illuminate\Queue\SerializesModels;
use Illuminate\Broadcasting\PrivateChannel;
use Illuminate\Broadcasting\PresenceChannel;
use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Broadcasting\InteractsWithSockets;
use Illuminate\Contracts\Broadcasting\ShouldBroadcast;
use App\Models\Post;

class PostEvent implements ShouldBroadcast
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public $post;

    /**
     * Create a new event instance.
     *
     * @return void
     */
    public function __construct(Post $post)
    {
        $this->post = $post;
    }

    /**
     * Get the channels the event should broadcast on.
     *
     * @return Channel|array
     */
    public function broadcastOn()
    {
        return new PrivateChannel('test-channel');
    }

    public function broadcastAs()
    {
        return 'post.created';
    }
}

```

The trigger
`event(new PostEvent($post))`

**Comment by themsaid** [comment]
You can find all the places in the code where a method was called using GitHub search box, check: https://github.com/laravel/framework/search?utf8=%E2%9C%93&q=verifyUserCanAccessChannel&type=

Not quite sure I understand what you're trying to do, but feel free to share your thoughts on the forums so that others can help, we keep this repo for bug reporting only.

**Comment by kvnbai** [comment]
@themsaid Yes, I've seen this but for some reason `verifyUserCanAccessChannel` or `auth` was not called (using Redis), tho `Broadcast::channel();` registered the channel the closure is not fired upon broadcasting. If ever my description was confusing, Actually I didn't hack the framework, I just did what the documentation said and trace what channel should I subscribe to in my Node server. Just asking when is the authorization is triggered upon broadcasting the event. Tho I cant achieve the same security by adding something anywhere the function `Broadcast::channel();` might give me better separation of concerns. By the way do you have other forums beside from Laracast?
