### ISSUE TITLE
Question about adding guard and provider in auth.php trough serviceprovider

### ISSUE THREAD

**Issue by matthijs-neijenhuijs** [laravel/framework#18799]
- Laravel Version: 5.4
- PHP Version: 7
- Database Driver & Version:

### Description:
I making a custom package and i'am wondering if it's possible to add a guard and provider in my ServiceProvider. I don't want that other developer need to put manually things in auth.php when they install the custom package. 

I tried to ask it on laravel.io chat, but i never get a answer. Second question: where can i find a active community? Getting answers in 24 hours?

**Comment by ntzm** [comment]
If you want quick answers I would recommend the larachat slack community or stackoverflow

**Comment by tillkruss** [comment]
larachat.co
