### ISSUE TITLE
[low-priority] Support / roadmap for typed Collections

### ISSUE THREAD

**Issue by holtkamp** [laravel/framework#18795]
Are there any plans to provide initial support for typed Collections? 

https://github.com/phpsafari/typed-collections seems like an effort. 

When the minimum requirement reaches PHP 7.0, an approach as described in https://github.com/phpsafari/typed-collections/issues/1 becomes available. A limitation of that approach would be that arrays/collections using a string as key are not supported by variadic parameters.

**Comment by Dylan-DPC** [comment]
this repo is for bug tracking. Use the `laravel/internals` repo instead :+1:

**Comment by holtkamp** [comment]
Oops, already had this feeling, not very familiar with the Laravel organization/structure. 

Sorry, closing and re-opened here: https://github.com/laravel/internals/issues/529
