### ISSUE TITLE
Should Eloquent\Collection::map() call toBase() on empty collections?

### ISSUE THREAD

**Issue by troygilbert** [laravel/framework#18794]
See line 133 of [Database\Eloquent\Collection.php](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Collection.php#L133):

```
return $result->contains(function ($item) {
            return ! $item instanceof Model;
        }) ? $result->toBase() : $result;
```

With the logic written this way an empty collection will remain an `Eloquent\Collection`. This can lead to unexpected behavior if an `Eloquent\Collection`-specific method is called, such as `merge()`, which then expects to call `getKey()` on the merged items, which may not be possible if the merged collection was automagically converted `toBase()` because it was non-empty.

Example:

```
$emptyCollection = DB::table('my_table')->where(...)->get()->map(...);
$nonEmptyCollection = DB::table('my_table')->where(...)->get()->map(...);
$combinedCollection = $emptyCollection->merge($nonEmptyCollection);
```

This code works when the first two queries return results (because `toBase()` gets called automatically by `map()`). If either of the queries returns no results, then you get a hard-to-decipher exception in the call to `merge()`.

Maybe the correct fix for this scenario is to always call `toBase()` after `map()`. But I think it could also be fixed by making the logic inside `Eloquent\Collection` exhaustive, i.e. if no model is in the collection, convert to base, instead of the current logic, which is if there's anything in the collection that's not a model, convert to base.

**Comment by vlakoff** [comment]
Your example uses Query Builder, not Eloquent, therefore it calls the base `map` method, not Eloquent's.

Though, I see your point, but returning an Eloquent collection if there are no results makes sense too. It returns a base collection iif it cannot do otherwise, i.e. if some results are not Models.

**Comment by troygilbert** [comment]
Good point, I wrote the example that way to keep my own models out of the example, but it does slightly muddy the point. 

It still stands, though: if you have an empty Eloquent collection and attempt to merge it with a regular collection it crashes.

**Comment by vlakoff** [comment]
I think the current code makes more sense. Your proposed change would fix your use case, but break others. As you are starting from an Eloquent collection to generate a base collection, you should just explictly add a `toBase` after your `map`.

(actually, I'm more concerned about the performances of that `contains` check, as the whole collection is iterated a second time… but that's another story.)

**Comment by troygilbert** [comment]
Yeah, I added `toBase()` after `map()` to fix it. Consider it more of a heads up to the maintainers that it's an easy bug to hit with a non-obvious cause -- though, I did suss it out, so maybe it is pretty easy to sort out? ;-)

**Comment by vlakoff** [comment]
Shall this be closed?

**Comment by pdbreen** [comment]
I just hit this as well in a similar scenario - merge throwing an error.  At first, it definitely seemed a bit inconsistent.  But I now realize there could never be a correct answer to handling what map should do with an empty collection.  Retaining the eloquent flavor does seem like the better option. 

In any case, I've added the explicit `toBase()` to resolve my issue.
