### ISSUE TITLE
ResponseFactory missing file()

### ISSUE THREAD

**Issue by sambenne** [laravel/framework#18792]
- Laravel Version: 5.4.*
- PHP Version: 7

### Description:
ResponseFactory seems to be missing file()

### Steps To Reproduce:
Do something like response()->file('myfile.txt'). The interface is missing the file method.

**Comment by morloderex** [comment]
You can use `response->download()` for this. :)

**Comment by Dylan-DPC** [comment]
Not a bug. Can be closed

**Comment by mosinve** [comment]
This is a bug, as `Illuminate\Routing\ResponseFactory` itself has `file()` method, but `Illuminate\Contracts\Routing\ResponseFactory` hasn't.
And there is info in docs about the difference between `download()` and `file()` methods.
