### ISSUE TITLE
hasManyThrough requires relevant table's name

### ISSUE THREAD

**Issue by srph** [laravel/framework#18791]
- Laravel Version: 5.4
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.6 InnoDB

### Description
For `hasManyThrough` relationships, you need to provide the relevant table's name like the following:

```php
$country->posts->where('posts.name', 'LIKE', "%{$query}")->get();
```
Otherwise, a SQL error will be thrown:

> `SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'name' in where clause is ambiguous`

### Suggestion
I think the documentation should mention this for clarity.

-----

Putting this up because I didn't find any related issues, and a way of asking for approval if I can send a PR for this. Let me know if I missed anything.

**Comment by Dylan-DPC** [comment]
@srph we have a docs repo for suggestions for the doc. Kindly post it there. (laravel/docs)

**Comment by srph** [comment]
Thank you, will do!
