### ISSUE TITLE
[Eloquent] [5.3] Incorrect usage of UPDATE and ORDER BY

### ISSUE THREAD

**Issue by shadoWalker89** [laravel/framework#18805]
- Laravel Version: 5.3.31
- PHP Version: 5.6.15
- Database Driver & Version: MySQL 5.6.31

### Description:
I have this model

```php
Meeting extends Model
{
    public function invitedTeachers()
    {
        return $this->belongsToMany(Teacher::class, 'meeting_teacher_invitations')
            ->orderBy('as_president', 'DESC')
            ->withPivot(['as_president', 'is_present']);
    }
}
```

When i do

```php
$meeting->invitedTeachers()->where('teacher_id', 232)->update(['as_president' => true]);
```

I get this error

```
'SQLSTATE[HY000]: General error: 1221 Incorrect usage of UPDATE and ORDER BY (SQL: update `teachers` inner join `meeting_teacher_invitations` on `teachers`.`id` = `meeting_teacher_invitations`.`teacher_id` set `as_president` = 1, `updated_at` = 2017-04-14 11:05:53 where `meeting_teacher_invitations`.`meeting_id` = 4 and `teacher_id` = 232 order by `as_president` desc)'
```

**Comment by Dylan-DPC** [comment]
Two things: 
1) Laravel 5.3 is no longer supported. 
2) this doesn't look like a bug. Since the error is coming straight from SQL. Use the forums or the slack channel to resolve it.

**Comment by shadoWalker89** [comment]
> Laravel 5.3 is no longer supported.

5.3 still have bug fixes.


> this doesn't look like a bug. Since the error is coming straight from SQL. Use the forums or the slack channel to resolve it.

Eloquent builder and database query builder are responsible for putting together the sql that will be executed, this looks like the builder is not taking into consideration when updating the pivot and an order by is defined on the relation.

**Comment by m1guelpf** [comment]
> 5.3 still have bug fixes.

**Security** patches

**Comment by shadoWalker89** [comment]
@m1guelpf From the docs

For general releases, bug fixes are provided for 6 months and security fixes are provided for 1 year.

**Comment by mcklayin** [comment]
It's not a framework bug. You can't use your like in your example, see mysql update doc below.
[https://dev.mysql.com/doc/refman/5.7/en/update.html](url)
Use orderBy in some another place instead of relation.

**Comment by Dylan-DPC** [comment]
@shadoWalker89 @m1guelpf yes.. and if you check your nice colourful calendar you will realise that 5.3 was launched in August 2016. If I can calculate properly, its long past 6 months :)

**Comment by shadoWalker89** [comment]
@Dylan-DPC OMG, i really didn't realize that it's past 6 months, wow :D time flies by

I'm closing this issue for now.

**Comment by Dylan-DPC** [comment]
@shadoWalker89 haha sure.. better to upgrade o 5.4 if possible ;)
