### ISSUE TITLE
Logic of belongsTo function

### ISSUE THREAD

**Issue by lazicstefan** [laravel/framework#18804]
Even tho I am beginner in PHP world and Laravel, to me, logic about belongsTo function in Eloquent Model is a bit wrong.
For example, name of method inside one model could be anything for 'hasMany()':
```
public function anything()
{
return $this->hasMany('App\Something');
}
```
And 'Model->anything' will return collection of models.
In that case 'belongsTo', as documentation says, it determine foreign key by method name, so it MUST BE:
```
public function something()
{
return $this->belongsTo('App\Something');
}
```
**Which means, if I am not wrong, method name is always EXACTLY SAME as MODEL NAME passed to belongsTo() function.** 
In my logic, that's not right, belongsTo should take passed model name for determining foreign key if other is not specified as 2nd argument.
Maybe you think, wtf I am talking about but in some situation where table name contain 3 words 'first_second_third' (model of course FirstSecondThird), its not funny to return belongsTo with: 
`Model->first_second_third`
Shouldn't that be:
`Model->anything`

Sorry if my language is bad, or if I didn't understand something, or if there was already topic about this.

**Comment by Dylan-DPC** [comment]
this repo is for bug fixes. You can open this as a "proposal" in the laravel/internals repo

**Comment by lazicstefan** [comment]
Sorry, didn't know that.
Delete this one, I will post there.

Thanks

**Comment by Dylan-DPC** [comment]
I can't delete it. You can close the issue yourself :)
