### ISSUE TITLE
Do not assume primary keys are necessarily integers

### ISSUE THREAD

**Issue by supriyo-biswas** [laravel/framework#18801]
(This bug is specifically with the illuminate/database component, but I'm reporting it here since the bug tracker there is disabled.)

illuminate/database version: 5.4.17

It seems that the database component assumes that the 'primaryKey' property is an integer, which may not be always the case (e.g. usernames).

This can be reproduced by running any database query and then trying to retrieve the primary key value which is stored as a non-integer.

Are there any plans to change this behaviour?

**Comment by ludo237** [comment]
You can change that inside your eloquent model.
