### ISSUE TITLE
routes not working after upgrading from 5.2 to 5.4

### ISSUE THREAD

**Issue by manojsharma20** [laravel/framework#18800]
- Laravel Version: 5.2.X
- PHP Version: 7
- Database Driver & Version: mongodb 3.4.3

### Description:
I have upgraded my laravel 5.2 application into 5.3, i have also remove boot parameter from the providers. When i tried to run application, i am getting 404 not found. my all routes working fine with previous version, but after upgrade none of them working. i have also customized auth in my way too.

### Steps To Reproduce:

1) take laravel 5.2 app with auth.
2) change composer.json laravel/framework version too 5.3
3) run composer update
4) remove boot parameter.
5) check all routes.

not here i am getting 404 error.

**Comment by ConnorVG** [comment]
>i have also remove boot parameter from the providers

I wonder why your routes might not be working... 🤔 

*It's hard to tell what you mean by `remove boot parameter`.*

**Comment by Dylan-DPC** [comment]
Your issue says 5.3 but title says 5.4 :thinking: 
Also your "Steps To Reproduce" is too generic at this point.

**Comment by byCedric** [comment]
Have you followed the exact steps as described in the upgrade guide? https://laravel.com/docs/5.3/upgrade

**Comment by themsaid** [comment]
Please ask on the forums.
