### ISSUE TITLE
Nesting relationship returns null on using select

### ISSUE THREAD

**Issue by ZeyadMounir** [laravel/framework#18809]
- Laravel Version: 5.4

### Description:
![image](https://cloud.githubusercontent.com/assets/16030521/25062795/a7d0132e-21dc-11e7-8082-0f2a8016c20e.png)

When I select only the user name or any other column without id, the users relationship returns null. 
It took too long until I noticed that when I add the id with the name or any other column, it returns value! What if I want to hide the id? And is that a normal behavior? It's not mentioned anywhere in the documentation.

**Comment by lagbox** [comment]
It needs what ever field the keys for the relationship are so it can actually match up the records to their parents after they are eager loaded.

**Comment by ZeyadMounir** [comment]
So why did it then work with the winners relationship without the id? The only different that it's not nesting!

**Comment by Dylan-DPC** [comment]
This is not a bug.
