### ISSUE TITLE
Schema builder not removing unsigned flag from column.

### ISSUE THREAD

**Issue by ryanmortier** [laravel/framework#18803]
- Laravel Version: 5.4.16
- PHP Version: 7.1.3-3
- Database Driver & Version: MySQL 5.7.17

### Description:
I've added the `doctrine/dbal` package and created the migration below. It doesn't seem to want to remove the `unsigned` flag from the column though. My column is still unsigned after the migration completes.

### Steps To Reproduce:

Create the following migration for a table and run it.
```php
    public function up()
    {
        Schema::table('sales', function (Blueprint $table) {
            $table->decimal('amount', 19, 4)->change();
        });
    }

    public function down()
    {
        Schema::table('sales', function (Blueprint $table) {
            $table->decimal('amount', 19, 4)->unsigned()->change();
        });
    }
```

**Comment by sisve** [comment]
I believe that the first line doesn't change the unsigned flag at all, and the second one sets it. Try `->unsigned(false)` to disable it.

**Comment by ryanmortier** [comment]
Interesting, I just did some more testing and by omitting `unsigned()` on an integer field, it'll remove the unsigned from the field. However, if you omit it on a decimal field like above, it does not remove it. Now sure if that's intended behaviour or a bug.

However, using `unsigned(false)` does in fact remove the unsigned from both field types, so thank you for that.

I'll close this but I'll ping @taylorotwell @themsaid in case that is in fact a bug.
