### ISSUE TITLE
Can't use queue's fake method and artisan's call in same test

### ISSUE THREAD

**Issue by ImJustToNy** [laravel/framework#18818]
- Laravel Version: 5.4.19
- PHP Version: 7.1.3
- Database Driver & Version: MariaDB 10.1.19

### Description:
The problem is - when we use [queue's fake method](https://laravel.com/docs/5.4/mocking#queue-fake) and [artisan's call method](https://laravel.com/docs/5.4/artisan#programmatically-executing-commands) we gonna end up with this kind of error:

> TypeError: Argument 1 passed to Illuminate\Queue\Worker::__construct() must be an instance of Illuminate\Queue\QueueManager, instance of Illuminate\Support\Testing\Fakes\QueueFake given

Which I believe is issue with Laravel itself. If I'm wrong, please correct me. I found simple workaround for this - I've created seperate unit test for this particular feature, which doesn't include fake method, but I think it's worth to mention this problem there.

### Steps To Reproduce:
Simply use this example code:
```php
    public function setUp()
    {
        parent::setUp();

        Queue::fake();
    }

    public function testExample()
    {
        Artisan::call('schedule:run'); // Can be literally any command
    }

**Comment by themsaid** [comment]
Fixed in https://github.com/laravel/framework/pull/18831
