### ISSUE TITLE
[5.4] Failed insertion due to invalid ENUM is reported as successful save

### ISSUE THREAD

**Issue by adamthehutt** [laravel/framework#18811]
- Laravel Version: 5.4.16
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7

### Description:
If MySQL is in STRICT_TRANS_TABLES mode, an attempted insert with an invalid ENUM value will fail, and the row is not inserted. However, Laravel believes the insertion has succeeded and even assigns an auto-incremented ID to the model. This is possibly a bug in the underlying Doctrine driver, rather than in Laravel itself. It may also be because the error occurs on the statement execution, not when the statement is prepared. 

### Steps To Reproduce:
Create a mode class, Foo, with the columns:
* id
* type ENUM('a','b','c')

````
$foo = new Foo();
$foo->type = 'd';
$result = $foo->save();

$result == true; // true
$foo->id;          // 1 (or whatever the auto-inc value is)

$fooRedux = Foo::find($foo->id); // null
````

**Comment by webmake** [comment]
Do you use strict flag as true in database.php file? By default it is false, so it suppress errors arising from database

**Comment by adamthehutt** [comment]
@webmake Good catch! I wasn't aware of that setting. I had it set to false, but when I changed it to true, the correct behavior happens - an exception is thrown. 

IMHO it's still a bug when the other scenario is possible, since Laravel shouldn't ever think a record has been saved when it hasn't. But at least it's easy to fix by making sure your code and database configurations are in sync.

**Comment by themsaid** [comment]
> Make sure your code and database configurations are in sync.

I'd say that's all you need to do :)
