### ISSUE TITLE
array_diff in expectsEvents requires string values, proposal to use contract for events to compare objects

### ISSUE THREAD

**Issue by webmake** [laravel/framework#18821]
- Laravel Version: 5.4.18
- PHP Version: 7.1

### Description:
Passing non string argument to `expectsEvents` method, occurs an error:
`Object of class Illuminate\Log\Events\MessageLogged could not be converted to string`, but there need only small fix, to require in all events `__toString` method:
```
    public function __toString()
    {
        return serialize($this);
    }
```
And as you can see the image below, both objects are the same, only array_diff cannot properly cast object.
![image](https://cloud.githubusercontent.com/assets/5016464/25086751/b93c0c66-2372-11e7-9a73-80e3368da756.png)

It could be contract for events, to require this method.

### Steps To Reproduce:
```
    public function test_logger(): void
    {
        $message = new MessageLogged('warning', 'Invalid token');
        $this->expectsEvents($message);
        $this->app->make(TestingLogger::class)->loggerMethod();
    }
```
```
class TestingLogger {
    public function __construct(Log $logger) {
        $this->logger = $logger;
    }
    public function loggerMethod()
    {
            $this->logger->warning('Invalid token');
     }
}
```

**Comment by webmake** [comment]
Problem is, how to test that particular event dispatched with some arguments, so this `__toString` would solve that.

**Comment by themsaid** [comment]
That's how `expectsEvents` is supposed to work, it only checks for an event name being fired or not.

Please continue on the forums for further assistance.
