### ISSUE TITLE
I believe QueueFake push() method wrong

### ISSUE THREAD

**Issue by lordemanonsr** [laravel/framework#18832]
- Laravel Version: 5.4.18
- PHP Version: 7.1.2

### Description:

The push() method in QueueFake assumes an object for the $job parameter. It does not accept a string for the job. It then attempts to do a get_class on a string and fails.

As in the require Queue class createPayloadArray method it needs to first determine if $job is an object and only use get_class if it an object and just use the $job value if it is a string.

```
public function push($job, $data = '', $queue = null)
    {
        $jobName = is_object($job)
            ? get_class($job) 
            : $job;
        
        $this->jobs[$jobName][] = [
            'job' => $job,
            'queue' => $queue,
        ];
    }

```

**Comment by Aven30** [comment]
Yeah I see that issue. 

Also it seems like you may want to include $data as well

```
$this->jobs[$jobName][] = [
            'job' => $job,
            'queue' => $queue,
            'data'=>$data
        ];
```

**Comment by themsaid** [comment]
Thanks, opened a PR here https://github.com/laravel/framework/pull/19575
