### ISSUE TITLE
Call validation rule in custom validation rule

### ISSUE THREAD

**Issue by deividaspetraitis** [laravel/framework#18839]
- Laravel Version: 5.4.18
- PHP Version: 7.1
- Database Driver & Version: -

### Description:

`$validator->validateXXX($attribute, $value);` produces `Method [validateXXX]` does not exist. because of `Validator` __call overloading. How I can call validation rule in my defined custom rule?

### Steps To Reproduce:

I have some custom validation rule:

`$validator->extend('dob', 'Modules\Users\Services\User\UserValidationService@validateDob');`

And now in in this custom rule I would like to call and use already defined rule. For example:

```
    /**
     * Validate date of birth year
     *
     * @param  string      $attribute
     * @param  mixed       $value
     * @param  mixed       $parameters
     * @param  Validator   $validator
     *
     * @return bool
     */
    public function validateDob($attribute, $value, $parameters, Validator $validator)
    {
        $date = $validator->validateDateFormat($attribute, $value, array('Y-m-d'));

        if ($date == false) {
            return false;
        }

        // at least 18 years old
        if (intval(date('Y', strtotime($value))) > (date("Y") - 18)) {
            return false;
        }

        return true;
    }
```
Problem: ` $validator->validateDateFormat($attribute, $value, array('Y-m-d'));` produces `Method [validateDateFormat] does not exist.` because of `Validator` __call overloading. Also I cannot use `ValidatesAttributes` trait since class `UserValidationService` cannot extend `Validator` and don't inherit it's functions that are required for successfull trait usage.

**Comment by deividaspetraitis** [comment]
Temp solution main idea: override current `Validator` class `__call` method.

## Create Validation Service:

Let's creat a validation service, a class that actual extends and from now changes currenly used `Validator` class. Copy original magic method and modify it a little bit:

```
<?php namespace App\Services;

use Illuminate\Support\Str;
use Illuminate\Validation\Validator;

class ValidationService extends Validator
{
    public function __call($method, $parameters)
    {
        $rule = Str::snake(substr($method, 8));

        if (isset($this->extensions[$rule])) {
            return $this->callExtension($rule, $parameters);
        }

        return call_user_func_array([$this, $method], $parameters); // TODO: Change the autogenerated stub
    }
}
```

## Create Validation Service Provider:

When we have our new `Validator` class now we need to set it as our new  actual validator:

```
<?php namespace App\Providers;

use App\Services\ValidationService;
use Illuminate\Support\ServiceProvider;

class ValidationServiceProvider extends ServiceProvider
{
    /**
     * Indicates if loading of the provider is deferred.
     *
     * @var bool
     */
    protected $defer = false;

    /**
     * Boot the application events.
     *
     * @return void
     */
    public function boot()
    {
        $this->app['validator']->resolver(function($translator, $data, $rules, $messages)
        {
            return new ValidationService($translator, $data, $rules, $messages);
        });
    }

    /**
     * Register the service provider.
     *
     * @return void
     */
    public function register()
    {
        //
    }

    /**
     * Get the services provided by the provider.
     *
     * @return array
     */
    public function provides()
    {
        return array();
    }
}
```
## Test to make sure we doesn't break anything

According this topic description let's take `validateDob` method and dump `$validator` and you will see that it's `ValidationService` from now and not `Validation`. Also we are capable to call any original `Validator` methods including pre-defined rules like `validateDateFormat`.

**Comment by tylernathanreed** [comment]
My way around this has always been to just create a new Validator within the rule.

**Example:**

    use Validator as Factory;

   /**
     * Validate date of birth year
     *
     * @param  string      $attribute
     * @param  mixed       $value
     * @param  mixed       $parameters
     * @param  Validator   $validator
     *
     * @return bool
     */
    public function validateDob($attribute, $value, $parameters, Validator $validator)
    {
        $v = Factory::make([$attribute => $value], [
            $attribute => 'required|date_format:Y-m-d|after:-18 years''
        ]);

        if($v->fails()) {
            return false;
        }

        return true;
    }

Would that work for you?

**Comment by themsaid** [comment]
Since it's not actually a bug I'm going to close it, but feel free to open a PR or suggest this feature on the internals repository.
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
