### ISSUE TITLE
Middleware terminate() not wokring

### ISSUE THREAD

**Issue by saikatdutta1991** [laravel/framework#18849]
hi,
i am using laravel 5.1 with apache2(ubuntu 16.4)

i want to send response and then continue process with terminable middleware..
but it blocking the response.. 

    public function terminate($request, $response)
    {
    	for($i=1;$i<=5;$i++){
			\Log::info('After shutdown: ', [$i]);
			sleep(1);
		}
    }

but in controller itself its working with core php. But i want it in terminate() function and dont want to use fastcgi_finish_request() .. i dont know how to install.

here is my core php code

ob_start();
	echo response()->json('Hello world');
	header("Content-Encoding: none");
	header("Connection: close");
	$size = ob_get_length(); 
	header("Content-Length: $size");
	ob_end_flush();
	ob_flush();
	flush();

this is working fine
Email : saikatdutta1991@gmail.com

**Comment by laurencei** [comment]
I've tested this on a couple of 5.1 apps - and it works fine.

The response is returned immediately, but the `sleep()` occurs and more commands are processed after the fact.

Must be something in your implementation. Probably best to ask on the forums.

**Comment by saikatdutta1991** [comment]
apache2 needs any extra module for this ??

**Comment by lucasmichot** [comment]
Works for me too

**Comment by saikatdutta1991** [comment]
can you guys show me a video of working code you made?? it would be very usefully
@lucasmichot @laurencei
