### ISSUE TITLE
[5.4] withDefault on HasOne always calls getDefaultFor before query executes.

### ISSUE THREAD

**Issue by kevindierkx** [laravel/framework#18857]
- Laravel Version: 5.4.x
- PHP Version: ~
- Database Driver & Version: ~

### Description:

The Eloquent `HasOne` relationship always calls the `getDefaultFor` method inside the `initRelation` method even before the query has been executed.

The `getResults` method has the `getDefaultFor` method as fallback when the query results in null. However this doesn't actually do anything interesting since this same method is already called when the relationship is initialised.

This results in some problems when you try to 'save' a default model when it doesn't exist.

### Steps To Reproduce:

Create a relationship and add the `withDefault` method using a closure:

```
    /**
     * Returns the 'wallet' relationship.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function wallet()
    {
        return $this->hasOne(Wallet::class, 'account_id', 'id')
             ->withDefault(function ($model) {
                 return $model->save();
             });
    }
```

Every time you eager load this relationship an extra wallet entry is saved.

### Suggestion:

Since this actually differs from other relationships my suggestion is to use `null` instead of `getDefaultFor` during init, other relationships like `HasManyThrough` use empty collections for example.

```
    /**
     * Initialize the relation on a set of models.
     *
     * @param  array   $models
     * @param  string  $relation
     * @return array
     */
    public function initRelation(array $models, $relation)
    {
        foreach ($models as $model) {
            $model->setRelation($relation, null);
        }

        return $models;
    }
```

**Comment by themsaid** [comment]
It doesn't make any sense to have this:

```
->withDefault(function ($model) {
    return $model->save();
});
```

Not sure I get your point

**Comment by kevindierkx** [comment]
@themsaid I have some model events that add a uuid and other on save related data. Also I always want that model to be saved when it doesn't exist yet. The `withDefault` works like a charm in those cases since I'm working with [thephpleague/fractal](https://github.com/thephpleague/fractal) based transformers.

However I might not have been very clear about the inconsistency part, before the relation is actually loaded the `initRelation` method eagerly loads the `withDefault` in a later stage when there is no relation matched it does this again. Compared with the normal behaviour of `find` where you get null when a model doesn't exist or `get` where you get an empty collection this 'eager' behaviour doesn't match. Also the `HasManyThrough` inits the relation with an empty collection, not the result of the `withDefault`.

Example `HasManyThrough`:
```
    public function initRelation(array $models, $relation)
    {
        foreach ($models as $model) {
            $model->setRelation($relation, $this->related->newCollection());
        }

        return $models;
    }
```

Example `BelongsTo`:
```
    public function initRelation(array $models, $relation)
    {
        foreach ($models as $model) {
            $model->setRelation($relation, null);
        }

        return $models;
    }
```

So in the end my only problem is the 'premature' execution of the `getDefaultFor` in the `initRelation` method, only found in the `HasOne` relation.

The saving of the model in the `withDefault` is a whole different discussion.
_I currently use something like this instead:_
```
return $this->hasOne(Wallet::class, 'account_id', 'id')
     ->withDefault(function ($model) {
         return Payments::wallets()->findByAccountIdOrNew($model->getAccountId());
     });
```

**Comment by themsaid** [comment]
Giving this issue another thought, I think what you require is a change in how the code executes, it's not actually a bug in the framework, so please open an issue on https://github.com/laravel/internals repo, it's where we keep such change requests.
