### ISSUE TITLE
[5.4] Route parameter being bound to `/` when there is actually no parameter (using custom parameter regex)

### ISSUE THREAD

**Issue by jimrubenstein** [laravel/framework#18854]
- Laravel Version: 5.4

### Description:

The Laravel RouteParameterBinder prepends an extra `/` onto the request path when the site root is requested.

This becomes an issue if in some cases when you attempt to modify the parameter matching regex for a route to use something other than a forward slash as a parameter delimiter (or, in the case shown below, try to use the entire parameter string as a single argument).

This issue is, admittedly, nuanced and will mostly only be noticed in edge cases. However, the bug itself (and it's fix) is very simple and I think the Router/RouteBinder manages to work despite itself, due to the special nature of the forward slash in URLs and how they're typically used in most applications.

### Explanation:

The issue is happening in the [Routing/RouteParameterBinder@bindPathParameters](https://github.com/laravel/framework/blob/51cad04a923bf22c9ae96d77e4cb07767d634c17/src/Illuminate/Routing/RouteParameterBinder.php#L60) method.

The string that gets passed to `preg_match` ends up being `"//"` when a request is made to the root of the application. In most cases, this is okay, since the default parameter regex pattern is essentially `[^/]++`.

However, if you change the router parameter regex to something like `(.+)`, you start getting undesired behavior on the controller action.

### Example

```php
<?php

// writing this in the context of a Route test, I think it's easier to
// wrap your head around that way

// tests/Routing/RoutingRouteTest.php
public function testLeadingParamDoesntReceiveForwardSlashOnEmptyPath() {
	$router = $this->getRouter();
	$outer_one = 'abc1234'; // a string that is not one we're testing
	$router->get('{one?}', [
		'uses' => function($one = null) uses (&$outer_one) {
			$outer_one = $one;
			return $one;
		},
		'where' => ['one' => '(.+)'],
	]);

	$this->assertEquals('', $router->dispatch(Request::create(''))->getContent());
	$this->assertNull($outer_one);
	
	// Expects: '' ($outer_one === null)
	// Actual: '/' ($outer_one === '/')
}

**Comment by themsaid** [comment]
Closing since there's a PR opened already.
