### ISSUE TITLE
[5.4] Laravel still using PHPUnit old classnames, leading to errors with PHPUnit 6 and up

### ISSUE THREAD

**Issue by stemis** [laravel/framework#18864]
- Laravel Version: 5.4.19
- PHP Version: 7.0.17
- Database Driver & Version: N/A
- PHPUnit: 6.0.8

### Description:
When using `Mail::fake();` and `Mail::assertSent(EmailBookingOrders::class);`
The assertSent statement throws the following error:
`Error: Class 'PHPUnit_Framework_Assert' not found`

**When doing a search to : "PHPUnit\Framework\Assert" in the Iluminate folder I get 2 results:**
TestResponse.php
FilesystemAdapter.php

**When doing a search to : "PHPUnit_Framework_Assert" in the Iluminate folder I get 5 results:**
BusFake.php
QueueFake.php
MailFake.php
NotificationFake.php
EventFake.php

It seems that Laravel does not yet have implemented the namespaced version for all files.

### Steps To Reproduce:
Install PHPUnit 6.0.8
Write a test that uses MailFake and assertSent

### Fix:
Change all use statements to use the namespaced version of PHPUnit

For example:
Replace this line:
`use PHPUnit_Framework_Assert as PHPUnit;`
With this line:
`use PHPUnit\Framework\Assert as PHPUnit;`

**Comment by themsaid** [comment]
PR submitted: https://github.com/laravel/framework/pull/18867
