### ISSUE TITLE
vendor/illuminate/database/Eloquent/Builder.php support except method

### ISSUE THREAD

**Issue by yanyandenuonuo** [laravel/framework#18862]
- Laravel Version: 5.4.16
- PHP Version: 7.1
- Database Driver & Version: Mysql 5.6.30

### Description:
I want use except method to define the fields which I didn't select in each select. Now, I can only use get(['field_1', 'field_2', 'field_3', 'field_4', ...]). If I had 10 fields and I just want select 9 of those, I need to write 9, but if support except method, I just need to write 1

### Steps To Reproduce:
1. create a table
2. create a model to operate the table
3. write $this->where($filter)->except(['the filed which I didn't want'])->toArray();

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
