### ISSUE TITLE
Rule::exists() - Bug

### ISSUE THREAD

**Issue by tnguyen16816** [laravel/framework#18876]
- Laravel Version: 5.4
- PHP Version: 7
- Database Driver & Version:

### Steps To Reproduce:
WORKS:
Rule::exists('borrowers')->where('investor_borrower_id', $borrower['bid'])->where('investor_id', $investor->id);

DOES NOT WORK:
Per docs this should work.  https://laravel.com/docs/5.4/validation

Rule::exists('borrowers')->where(function($query) {
                    $query->where('investor_borrower_id', $borrower['bid']);
                    $query->where('investor_id', $investor->id);
                }),

**Comment by themsaid** [comment]
I'm unable to replicate your issue, the described scenario seems to work just fine.

Please describe what you mean by `DOES NOT WORK`.

**Comment by pns2050** [comment]
It seems that you did not pass the $borrower,investor variables to the closure's scope.

**Comment by pankajvashisht-ucreate** [comment]
The callable method does not accept the variable directly so you need to use `use` to pass the parameter
 For example : -
Rule::exists('borrowers')->where(function($query) use ($borrower,$investor->id) {
$query->where('investor_borrower_id', $borrower['bid']);
$query->where('investor_id', $investor->id);
}),
