### ISSUE TITLE
Bug when creating UUID columns with Schema Builder

### ISSUE THREAD

**Issue by montelco** [laravel/framework#18889]
- Laravel Version: 5.3.30
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7.17-0ubuntu0.16.04.1

### Description:
When using Schema Builder there is a column that is named `uuid`. This column is, as one may expect, a UUID4 value. However, using the `$table->uuid('uuid')->index();` will create the column as a 16 character length varchar field in the database. Do note that there is a second column, `user_id`, which is created using the same Schema Builder line (`$table->uuid('user_id')->index();`. When the migration is run, the `user_id` column is properly formed as a CHAR column with 36 length.

### Steps To Reproduce:

- Create a migration and create a UUID column and attempt setting the column name to `uuid`
- In the same migration create another UUID column with a name other than `uuid` and it should create the column as described

**Comment by sisve** [comment]
I am unable to reproduce this on Laravel 5.4. Can you confirm that you have issue with this code on Laravel 5.3?

    \Schema::create('issue18889', function(Blueprint $table) {
        $table->uuid('uuid')->index();
        $table->uuid('user_id')->index();
    });

Results in ...

    create table `issue18889` (
        `uuid` char(36) not null,
        `user_id` char(36) not null
    ) default character set utf8mb4 collate utf8mb4_unicode_ci engine = innodb;

    alter table `issue18889` add index `issue18889_uuid_index`(`uuid`);
    alter table `issue18889` add index `issue18889_user_id_index`(`user_id`);

**Comment by acgfbr** [comment]
im facing the same issue, how do you solve buddy?
