### ISSUE TITLE
Exists method in validation doesn't care about soft-deletes

### ISSUE THREAD

**Issue by Jaspur** [laravel/framework#18885]
- Laravel Version: 5.4.19
- PHP Version: 7.1
- Database Driver & Version: PgSQL

### Description:
When having this validation, it'll check if the coupon exists in the discounts table in the "code" column:
```
$this->validate($request, [
  'coupon'  => 'required|exists:discounts,code',
]);
```
That works fine, but when a code is soft-deleted already in the table, it still thinks that it exists... but it doesn't.

### Steps To Reproduce:
Make an exists-validation, add a value in the database, soft delete it and run the validation.

**Comment by themsaid** [comment]
You can use `Rule::exists('discounts', 'code')->whereNull('deleted_at')` to check for only undeleted items.

**Comment by Jaspur** [comment]
@themsaid why close it? it's a bug.

**Comment by themsaid** [comment]
No it's not, the Validator knows nothing about Eloquent, you need to instruct it about soft deletion if you support soft deletion.

**Comment by themsaid** [comment]
Think of the Validator as a separate component from Eloquent, it just looks into a DB table that's all it knows. Happy to help if you need any further assistance :)
