### ISSUE TITLE
I can't catch exception by code if fire abort(404)

### ISSUE THREAD

**Issue by orangeShadow** [laravel/framework#18884]
- Laravel Version: 5.2

### Description:
Hi. 
If I run in code `abort(404,'Some message')`
I can't equal error code with 404, because status of code is 0.
The same problem with test this status! 

I go through call stack and go to this [line](https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Application.php#L903)

May be anyone change to `NotFoundHttpException($message,null,404)`;

**Comment by Dylan-DPC** [comment]
I just checked it on the latest release and It does give me an status of 404

**Comment by orangeShadow** [comment]
I'm sorry, it's because a get `$exception->getCode()` instead `$exception->statusCode()`
