### ISSUE TITLE
Laravel 5.1.46 Middleware weird behaviour

### ISSUE THREAD

**Issue by shiroamada** [laravel/framework#18881]
- Laravel Version: 5.1.42
- PHP Version:7.0.6
- Database Driver & Version: MySQL 5.6

### Description:
This is my middleware I would like to run clear the session variable in every page except login page. Below is my middleware file. It works if I add an echo on the "else" statement which is definitely not needed. However, if I remove the echo "login page", once I refresh in login page, the session variable will be cleared. 

I tried different session variable name also same result. eg. urlredirect, url_redirect, redirect.

I monitor with debugbar.

```
<?php namespace App\Http\Middleware;

use Closure;


class ClearUrlIntendedSessionExceptLogin  {

	public function handle($request, Closure $next)
	{

        if ( !$request->is('login')) {
            echo 'not login page';
           //I tried different session name also same, eg. urlredirect, url_redirect, redirect all is same result
            $request->session()->remove('url.intended');
        }
        else
        {
            echo 'login page'; //if I remove this one, once I refresh in login page, the url.intended will be removed..
            //some how if not include the else, the session will be removed.
        }

        return $next($request);
	}

}
```

Here is the video demo:
[Session Video](https://www.youtube.com/watch?v=lzYUh6CJLjo&feature=youtu.be)

###Excepted:
The problem is I do not have it to be removed in login page. Now the issue, if I did not echo out something. The second time I refresh the page, or I click login redirect the session variable is flushed / removed. I can't redirect to the page I want. 

I hope I explained my question correctly.

**Comment by shiroamada** [comment]
After I do a testing with fresh Laravel project. It is not related the framework bug. However, please help me to understand my project please... 

I used XDebug in PHPStorm to debug my code, to understand how does my code work.


When I run my new Laravel fresh project, It end at

`/laravel51lts/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php`

```
    public function __destruct()
    {
        try {
            $this->stop();
        } catch (Exception $e) {
        }
    }
```
Then no more activity.

However, my own project also end the same end point. But it goes to the breakpoint (which is in the middleware) and it repeated 3 times. I have no idea why it keeps repeating the whole process, and my middleware also hit 3 times. Any idea what will course the whole index run multiple?

Below is a log file I create when it hit my middleware file.
```
[21 Apr 2017 21:40:09] [] {"XDEBUG_SESSION_START":"15240"}

[21 Apr 2017 21:40:10] [] {"v":"1484813989"} | http://myproject.dev/business

[21 Apr 2017 21:40:10] [] []
```
And the last request it removes all the session. How do I debug it? And how I know why it is repeated?

**Comment by GrahamCampbell** [comment]
This is not a bug. As soon as you call echo, you send the headers to the server, so laravel has no opportunity to add the session cookie.

**Comment by GrahamCampbell** [comment]
Please ask on the forums for advice on debugging apps.
