### ISSUE TITLE
Supports anonymous jobs

### ISSUE THREAD

**Issue by abellion** [laravel/framework#18883]
- Laravel Version: 5.4
- PHP Version: 7.1
- Database Driver & Version: NA

### Description:

Anonymous jobs are not supported because PHP doesn't allow the serialization of this kind of classes. 

> Exception in Queue.php line 125:
Serialization of 'class@anonymous' is not allowed

For testing it would be convenient to support them.

### Steps To Reproduce:

```php
$dispatcher->dispatch(new class extends Job {
    public function __construct()
    {
    }

    public function handle()
    {
    }
});
```

**Comment by ntzm** [comment]
Don't think it's possible, even with an 3rd party library, see https://github.com/jeremeamia/super_closure/issues/50

**Comment by Dylan-DPC** [comment]
@abellion this repo is for bug fixes. Use the laravel/internals repo for proposals :)

**Comment by abellion** [comment]
@Dylan-DPC, as the doc says : 

>The only argument you need to pass to the dispatch helper is an instance of the job

An anonymous class is an instance of a job.

**Comment by ntzm** [comment]
The docs need updating then

**Comment by Dylan-DPC** [comment]
@abellion if you want to update the docs use the laravel/docs repo

**Comment by themsaid** [comment]
Yes that's not supported atm.
