### ISSUE TITLE
inconsistency between loading relationship "normally" and eager loading it

### ISSUE THREAD

**Issue by rs-sliske** [laravel/framework#18892]
- Laravel Version: 5.4.19
- PHP Version: 7.0.15-0ubuntu0.16.04.4 (my tests are in artisan tinker)
- Database Driver & Version: sqlite

### Description:
i have a belongsToMany relationship, with a union (my goal was using belongsToMany to override a default value via a left join)

it gives the result i expect when called "normally" (ie get the model and call the relationship). but when i try to eager load the relationship it ignores the union

```   
public function rules() {
    	$game = $this;
    	$nonMatches = Rule::whereNull('game_rule.value')->leftJoin('game_rule', function($join) use ($game){
    		$join->on('rules.id', '=', 'rule_id')->where('game_id', $game->id);
    	});
    	return $this->belongsToMany(Rule::class)->withPivot('value')->withTimestamps()->union($nonMatches)->orderBy('id');
}
```

![results in artisan tinker](https://sliske.uk/img/captures/d3763b99749632c.png)

I realize my use case is beyond what belongsToMany was designed for, but as far as im aware eager loading should give the same results, just with "normally" less queries

**Comment by Dylan-DPC** [comment]
This is not a bug. Use the forums or the slack channel to get your issue resolved. :)
