### ISSUE TITLE
Why doesn't the method 'contains' work if the collection has relations?

### ISSUE THREAD

**Issue by DanVeira** [laravel/framework#18902]
- Laravel Version: 5.4.18
- PHP Version: 7.1.1
- Database Driver & Version: MariaDB 10.2.3

### Description:
Shouldn't the `contains` method return true even if one collection has relations and the other doesn't?

### Steps To Reproduce:
````
$users = User::all();

$user = User::find(1)->get();

$sameUser = User::find(1)->with('roles')->get();

$user->is($sameUser) // true

$users->contains($user) // true

$users->contains($sameUser) // false
````

Or:
````
$users = User::all();

$user = User::find(1)->get();

$sameUser = User::find(1)->get();

$user->is($sameUser) // true

$users->contains($user) // true

$users->contains($sameUser->load('roles')) // false
````

**Comment by browner12** [comment]
technically the objects are not the same if one has eager loaded relationships, and the other doesn't.  while they may represent the same row in the database, PHP has no way of knowing that.

in this situation you may have do it based on your primary keys.

**Comment by DanVeira** [comment]
@browner12 Shouldn't `$user->is($sameUser)` also return `false` then?

**Comment by browner12** [comment]
because `is` only checks the ID and table

```php
/**
     * Determine if two models have the same ID and belong to the same table.
     *
     * @param  \Illuminate\Database\Eloquent\Model  $model
     * @return bool
     */
    public function is(Model $model)
    {
        return $this->getKey() === $model->getKey() &&
               $this->getTable() === $model->getTable() &&
               $this->getConnectionName() === $model->getConnectionName();
    }
```
