### ISSUE TITLE
Bug with "whereDate" methods

### ISSUE THREAD

**Issue by rorc** [laravel/framework#18904]
- Laravel Version: 5.4.19

### Description:
```php
$builder->whereTime('remind_at', 'between', [10, 12]);
```
This not working, because generates this sql: `... and time(remind_at) between 10`
Of couse, we can add methods `whereDateBetween`, `whereTimeBetween`, etc)

**Comment by Dylan-DPC** [comment]
@rorc can you take the resulting query and run the query to see if you are getting your desired result?

**Comment by rorc** [comment]
@Dylan-DPC As u can see above, result query is `and time(remind_at) between 10` (without 12)
Actual result must be `and time(remind_at) between 10 and 12`

**Comment by Dylan-DPC** [comment]
what happens with `whereBetween`?

**Comment by stemis** [comment]
@rorc According to the laravel docs, whereTime only accepts an int as the third parameter, it seems like whereTime was never designed to be used with the between operator

https://laravel.com/api/5.4/Illuminate/Database/Query/Builder.html#method_whereTime

**Comment by rorc** [comment]
@stemis Yea, and we can improve this, adding `between` to `$operator`?

**Comment by Dylan-DPC** [comment]
@rorc you can use `whereBetween('time', 10, 12);`
