### ISSUE TITLE
Camel case helper on Upper string not working

### ISSUE THREAD

**Issue by gmsergiov** [laravel/framework#18903]
- Laravel Version: #.#.# 5.4
- PHP Version: 7.0
- Database Driver & Version:

### Description: I'm not sure what should be the result of applying camel case helper camel_case over a Upper case string.
The result i get from string ABC is aBC, i'm wondering if that is the expected result.

### Steps To Reproduce:
Use camel_case function over an Upper case string.

**Comment by mohd-isa** [comment]
that's expected

Here is how Laravel convert strings to camel case:
1. replaces - and _ with a space
2. uppercase the first character of every word.
3. removes spaces between every word.
4. lower case the first letter

so in your case you have only one word, all letters are caps, only the first letter will be lowered.

you can look into the source code of camel case conversion here: https://github.com/laravel/framework/blob/5.4/src/Illuminate/Support/Str.php#L53

**Comment by Dylan-DPC** [comment]
Not a bug. That is expected behaviour. If you type ABC it considers ABC to be 3 separate words
