### ISSUE TITLE
Log naming

### ISSUE THREAD

**Issue by iwex** [laravel/framework#18905]
What if you add php_sapi_name() to larave log file name?

Or add filePermission to RotatingFileHandler creating? 

Ref: http://stackoverflow.com/questions/27674597/laravel-daily-log-created-with-wrong-permissions

**Comment by Dylan-DPC** [comment]
Not a bug. If you want to make proposal create an issue in laravel/internals repo

**Comment by iwex** [comment]
@Dylan-DPC okey, thanks
