### ISSUE TITLE
Adding data to session after flashing it in previous request won't work

### ISSUE THREAD

**Issue by arturowczarek** [laravel/framework#18909]
- Laravel Version: 5.4.0

### Description:
When you flash data under some key and in another request try to put data using the same key (not reflash) the method `Store->ageFlashData()` will find the key in `flash.old` and will clean the newly put data since it's stored under the same key.
When `Store` puts data, it should remove the key from `flash.old` array.

### Steps To Reproduce:
In first request flash some variable:
```request()->session()->flash('variableName', 'variableValue');```
In second request put variable with the same name
```request()->session()->put('variableName', 'variableValue');```
In the next request the variable won't be available since it was cleaned in `Store->ageFlashData()` method

**Comment by themsaid** [comment]
This is the intended behaviour.
