### ISSUE TITLE
[Bug] Decrement/Increment affeting all rows instead of selected one

### ISSUE THREAD

**Issue by timersys** [laravel/framework#18926]
- Laravel Version: 5.4
- PHP Version: 7.1

### Description:
If I choose an User and try to decrement , it affects all the users in the database.

### Steps To Reproduce:
Open tinker or in your code and try
$user = \App\User::find(1);
$user::decrement('credits');

Instead of just decrementing user with id 1, it decrements all users in table.

**Comment by bonzai** [comment]
Replace `::` with `->`.

**Comment by timersys** [comment]
(facepalm)
Thanks @bonzai
