### ISSUE TITLE
Arr::isAssoc returning true when numerical indexed not starting at 0.

### ISSUE THREAD

**Issue by uruloke** [laravel/framework#18929]
- Laravel Version: 5.4
- PHP Version: 7.1

### Description:
The `Arr:isAssoc` function returns true when you input an array like this `[1 => 'a', 2 => 'b']`.

### Steps To Reproduce:
`Arr::isAssoc([1 => 'a', 2 => 'b'])`

**Comment by m1guelpf** [comment]
Reference: https://github.com/laravel/framework/blob/master/src/Illuminate/Support/Arr.php#L321

**Comment by uruloke** [comment]
@m1guelpf yes I can see that they write in the phpDoc
`An array is "associative" if it doesn't have sequential numerical keys beginning with zero.`

But however Taylor said otherwise in a commit I made a while ago. [link](https://github.com/laravel/framework/pull/18293#issuecomment-285683364)

**Comment by m1guelpf** [comment]
@uruloke Then ping @taylorotwell

**Comment by devcircus** [comment]
Seems like his comment is saying ~with the array_values approach, you could possibly end up with an indexed array that doesn't start with zero~ thus giving a false positive on `isAssoc`, since an associative array is being defined as having sequential numerical keys starting at zero.
So the docblock seems to mirror his comment.

**Comment by ntzm** [comment]
This is the intended behaviour

**Comment by uruloke** [comment]
@devcircus but that is not correct, with the `array_values`approach, it will still say it's associative when an indexed array does not start with zero.  This test [SupportArrTest#L283](https://github.com/laravel/framework/blob/5.4/tests/Support/SupportArrTest.php#L283) checks for this scenario, and the commit I made passed all the test when using `array_values` instead.

**Comment by sisve** [comment]
@uruloke The test is correct. It checks if it is an associative array, which it is because the keys does not start with 0.

**Comment by uruloke** [comment]
Okay, if all the test are correct, then I do not understand why `array_values` approach is not valid, as it passes all the test.

**Comment by sisve** [comment]
@uruloke Can you clarify what you want to change, how you want to change it, and what is wrong with the current solution? Can you provide an example where your solution would correctly handle input, and the current way doesn't?

The distinction between associative and indexed arrays is based on the keys alone, never the values. It does not make sense to use array_values for this.

**Comment by uruloke** [comment]
@sisve The reason I opened this issue was because I understood Taylors comment to my commit, that if the array was numerical and not starting at 0, then it was non-associative, however I get now that this is not what he meant.

Both solutions will return true in all scenarios. So both solutions is correct, however `array_values` is faster. 

The reason `array_values` makes sense is because when you take the `array_values` of an array, it will make an indexed array of the values, therefor when we compare the array with the array_values result, if they are equal, then it's non-associative.

Example:
`a = [1 => 'a', 2 => 'b']`
Then the `array_values` of this would be 
`b = [0 => 'a', 1 => 'b']`
Comparing these with a not identical compare would give us
`a !== b // true`

**Comment by Dylan-DPC** [comment]
Why do you say that is faster?

**Comment by uruloke** [comment]
They are both O(n) ofc. ([ref](http://stackoverflow.com/a/2484455/2304480))

But here you can see a [benchmark](https://gist.github.com/Thinkscape/1965669) showing it is faster.

**Comment by Dylan-DPC** [comment]
Microtime isn't accurate enough for a benchmark.
