### ISSUE TITLE
Bug Validation Rules in - The first of given list of values never match

### ISSUE THREAD

**Issue by Xationch** [laravel/framework#18927]
- Laravel Version: 5.4
- PHP Version: 7.1

### Description:
When you try to validate a field must be included in the given list of values. The first value of the array list never match. The validation always returns that the first value of the array list does not match.

### Steps To Reproduce:
If you add a new value at the begining of the array, the first one will never match.
` 'canton' => 'sometimes|required|size:2|in:' . Rule::in(['zh','zg','vs','vd','ur','ti']),`

if you change the first value like this : 
`['fr','zh','zg','vs','vd','ur','ti']`

the 'zh' working, but not the first 'fr'

**Comment by bonzai** [comment]
If you use the `Rule` class to define the rule, don't use `in:` prefix.

https://laravel.com/docs/5.4/validation#rule-in

**Comment by Xationch** [comment]
@bonzai Correct, I do not know how I could miss it ...
