### ISSUE TITLE
Having a compatible PSR-11 container instance.

### ISSUE THREAD

**Issue by bweston92** [laravel/framework#18931]
- Laravel Version: 5.x

### Description:

After [this comment](https://github.com/prooph/laravel-package/pull/1#issuecomment-178617825) I want to get started a plan to allow for a [PSR-11](https://github.com/container-interop/fig-standards/blob/master/proposed/container.md) compliant wrapper around the Illuminate container.

As there is an increase in the number of packages I've seen being developed which make use of PSR-11, 450 of them registered on packagist as a dependant. I think it would be a good time for Laravel to have a wrapper implemented in the framework.

Other projects such as Zend Service Manager have this built into there service manager. I my self have had to make a [temporary patch](https://github.com/prooph/laravel-package/pull/14/files#diff-e8de58fd14d9d019615264b7c973fe20) to a project in order to satisfy this requirement when using Laravel.

**Comment by Dylan-DPC** [comment]
This is not a bug. Open an issue in the laravel/internals repo

**Comment by bweston92** [comment]
Thanks @Dylan-DPC I was unaware of this. laravel/internals#550
