### ISSUE TITLE
Reguard model in seeding not working

### ISSUE THREAD

**Issue by rorc** [laravel/framework#18932]
- Laravel Version: 5.4.19

### Description:
- Trying to enable `$fillable` and `$guard` attributes on all model in seeding.
- For that, trying to write `Illuminate\Database\Eloquent\Model::reguard()` in method `run` before start seeding in main class `DatabaseSeeder`.
- And occur exception `Illuminate\Database\Eloquent\MassAssignmentException` on field, which present on `$fillable` attribute.

**Comment by tillkruss** [comment]
Code to reproduce?

**Comment by rorc** [comment]
### Code to reproduce
```php
class SomeModel extends Illuminate\Database\Eloquent\Model
{
    protected $fillable = ['name'];
}

class DatabaseSeeder extends Illuminate\Database\Seeder
{
    public function run()
    {
        Illuminate\Database\Eloquent\Model::reguard();
        
        App\SomeModel::create([ 'id' => 100, 'name' => 'Foo' ]);
    }
}
```

After run `php artisan db:seed` i have exception `Illuminate\Database\Eloquent\MassAssignmentException (name)`

**Comment by devcircus** [comment]
You're setting 'name' to be the only attribute that you want to allow to be mass assigned, then setting $unguarded to false, which means mass assignment will be checked. Then you try to mass assign 'id', which throws a mass assignment exception. Seems everything is working properly.
Maybe Model::unguard() is what you're looking for?

**Comment by rorc** [comment]
I just want to enable MassAssignment protection, that disabled by default in seeding.

**Comment by Dylan-DPC** [comment]
@rorc https://github.com/laravel/framework/issues/736

**Comment by rorc** [comment]
@Dylan-DPC Its not working...

**Comment by Dylan-DPC** [comment]
can you share some code that you have tried with `Model::unguard()`?

**Comment by rorc** [comment]
Dude, see example above)

**Comment by rorc** [comment]
I use `Model::reguard()` method to enable mass assignment restrictions http://joxi.ru/l2ZVP4EHKDb42J

**Comment by Dylan-DPC** [comment]
My bad. Can you try it with another test case?

**Comment by rorc** [comment]
For what? This example describe main meaning.
Try to use and u will see )

**Comment by Dylan-DPC** [comment]
I have just tried the same and it works as expected.

**Comment by rorc** [comment]
I have error http://joxi.ru/nAyXNvoT8gZk2Z 😭

**Comment by devcircus** [comment]
Looks like the core code actually wraps the call to each seeder in a closure that automatically unguards the seeding. So if you need to unguard each seeder, then your reguard method would need to be called just inside the run method of each seeder class that you want guarded. Just a guess, but scanning over the code for db:seed, it seems plausible.

**Comment by devcircus** [comment]
Your code is working exactly like it should. Mass assignment is enabled and working properly when you call 'reguard'. What do you expect to happen? By default, in seeders, mass-assignment is bypassed. When you add 'reguard', then an exception will be thrown if you try to assign a property that is not listed in your 'fillable' fields. Seems like you're not understanding what mass-assignment protection is.

**Comment by rorc** [comment]
But attribute `name` exists in property `$fillable` on model!

**Comment by devcircus** [comment]
Can't reproduce. Hopefully someone will come along with some insight.

**Comment by rorc** [comment]
@devcircus Thanks for assistance 🙂

**Comment by RikSomers** [comment]
https://github.com/RikSomers/SeederTest

I followed your steps:
- Make the model (php artisan make:model SomeModel)
- Fill the fillable array
- Run migrations (php artisan migrate)
- Run seeder (php artisan db:seed)

Can't reproduce the error you're getting.

**Comment by rorc** [comment]
Big sorry for all, my fault, i was looking on different model, where not present `$fillable` property 🤓

**Comment by RikSomers** [comment]
No worries. We all make mistakes!

Best you can do in these cases is try to create the most simple testcase (like I did) and see if you can reproduce the error. If not, it's probably something in your own code you missed.

**Comment by rorc** [comment]
Yea, i understand, thanks dude 😃
