### ISSUE TITLE
Docblocks and code style problems.

### ISSUE THREAD

**Issue by prohalexey** [laravel/framework#18936]
- Laravel Version: 5.4
- PHP Version: 7.0.8

### Description:

Hello! I was made review for some files(1/10) of **laravel/framework** repository. 
I found what many function has outdated or broken docblocks like **@throw** properties what are absent. 
Functions can throw up to 5 or even more different exceptions, but there is no records about it. 
In some functions variables wait an object what implements an interface, and later you call functions on these objects what does not exist in this interface. 

Another problem is "return null" problem.
By default if return statement doesn't exists in a function, return value is null, but in a function docblock 
 we can see **@return void**. Or  in a function docblock **@return string|null** but code is like this:
```
/** 
* @return void
*/
public function something1()
{
     return;
}

/** 
* @return string|null
*/
public function something2($str)
{
    return $this->something1($str);
}
```

What we can do with this ?

### Steps To Reproduce:

Look at this commit: https://github.com/prohalexey/framework/commit/6a80c56ea2a4fa885f5d19188e02666fcb05c3a5

**Comment by m1guelpf** [comment]
@prohalexey https://github.com/laravel/framework/pull/18939

**Comment by Dylan-DPC** [comment]
Its better to create this issue on laravel/internals repo

**Comment by prohalexey** [comment]
Issue https://github.com/laravel/internals/issues/554
