### ISSUE TITLE
Laravel ignores 0 as value of the key in a collection

### ISSUE THREAD

**Issue by Ivorra** [laravel/framework#18935]
- Laravel Version: 5.4.15
- PHP Version: 7.0.15
- Database Driver & Version:

### Description: 
When pushing a key-value element into a collectio, if the key is 0, it will be ignored and only the value will be stored.

### Steps To Reproduce:

$collection = collect(); 
  foreach ([1,2,3,4] as $key) { //Collection works fine
     $collection->push([$key => "value"]);
}
echo $collection; //Will print
 [
  {"1":"value"},
  {"2":"value"},
  {"3":"value"},
  {"4":"value"}
]

$collection = collect();  
foreach ([1,0,3,4,0,5] as $key) {  //Collection ignores key
     $collection->push([$key => "value"]);
}
echo $collection;  //Will print 
[
  {"1":"value"},
  ["value"],
  {"3":"value"},
  {"4":"value"},
  ["value"],
  {"5":"value"}
]

**Comment by fonini** [comment]
Not a Laravel bug.

`<?php
$items = array(array(1 => "first"), array(0 => "second"));

print json_encode($items); // [{"1":"first"},["second"]]`

**Comment by Ivorra** [comment]
Oh, sorry, I did not knew it.
Is there any known workaround? 
Thank you.

**Comment by fonini** [comment]
See this [question](http://stackoverflow.com/questions/15290811/php-json-encode-issue-with-array-0-key).

**Comment by Ivorra** [comment]
Ok, thanks!, this solves my problem.
