### ISSUE TITLE
Pivot model can't be restored by SerializesModels

### ISSUE THREAD

**Issue by yateric** [laravel/framework#18947]
- Laravel Version: 5.4
- PHP Version: 7

### Description:
Sometimes you need to inject Pivot model into a Job or Notification object, if it is queueable, SerializesModels can't restore the Pivot during the queue job because Pivot required construct variables.

_SerializesAndRestoresModelIdentifiers.php_
```
protected function getRestoredPropertyValue($value)
{
    if (! $value instanceof ModelIdentifier) {
        return $value;
    }

    return is_array($value->id)
            ? $this->restoreCollection($value)
            : $this->getQueryForModelRestoration(new $value->class)
                        ->useWritePdo()->findOrFail($value->id);
}
```

_Pivot.php_
```
public function __construct(Model $parent, $attributes, $table, $exists = false){
  //
}
```

### Steps To Reproduce:
```
$pivotModel = $parentModel->pivot;

$notification = new ExampleNotification($pivotModel);

auth()->user()->notify($notification);
```

If ExampleNotification is queueable, it will get error because SerializesAndRestoresModelIdentifiers can't restore the pivot model.

**Comment by sisve** [comment]
A workaround would be to use a "real" model instead of a pivot model.
