### ISSUE TITLE
Bug Don`t match route parameters 

### ISSUE THREAD

**Issue by oteroweb** [laravel/framework#18940]
- Laravel Version: 5.4.17
- PHP Version: 7.0.15-0ubuntu0.16.04.4
- Database Driver & Version:

### Description:
I have Two Routes 

Route::get('/{category}', 'HomeController@category')->name('category');
and 
 Route::get('/tienda/{shop}/{category}', 'HomeController@category')->name('shop.category');

this is my controller:

    public function category($shop = null, $category)
    { (is_null($shop)){ // LOGIC      }
        else { // LOGIC  }
        return view('category',...PARAMETERS);
    }

when i enter to app.dev/my-category trows this error:
ReflectionException in RouteDependencyResolverTrait.php line 56:
Internal error: Failed to retrieve the default value

i solution it changing the order of parameters of function category() in my controller like this
    public function category($category,$shop = null)
    { (is_null($shop)){ // LOGIC      }
        else { // LOGIC  }
        return view('category',...PARAMETERS);
    }
then the error "its solved" 

but i enter to Route::get('/tienda/{shop}/{category}', 'HomeController@category')->name('shop.category');

in my controller, the shop parameter shows me with value of category parameter and conversely, when i put the function category with shop first, works fine, but trow the error in route('category') 
is it a bug?

note: with $request->route() function work fine.

**Comment by themsaid** [comment]
Please ask on the forums.

**Comment by oteroweb** [comment]
which forum?, link please

**Comment by devcircus** [comment]
[Laracasts](laracasts.com)
[larachat slack](larachat.co)
[laravel.io](laravel.io/forum)


All three of these stay quite busy. You'll usually get answers quickly.
