### ISSUE TITLE
how i can user that created in setup laravel

### ISSUE THREAD

**Issue by developerMerna** [laravel/framework#18945]
this is my setup php file of  

     public function setUp()
     {
        parent::setUp();
        $this->createApplication();

        $this->user = factory(App\User::class)->create([
	            'email' => 'testuser@email.com',
	            'password' => bcrypt($this->password),
	            'type' => 'admin'
        		]);
    }

   	/** @test */
	public function createTest()
	{	
		$this->actingAs($user);
		$this->visit('/client/ocp/profile/247/data')
			 ->click('New button')
        	 ->seePageIs('/client/ocp/profile/247/data/create')
	   		 ->see(' name')
	   		 ->see(' speed');
    }
	public function tearDown(){
        parent::tearDown();
        $this->user->delete();
    }
}
how i can use the user that created in setup function use it  in create function?

**Comment by devcircus** [comment]
If you're going to create the user in that way, $this->user = factory..., then you'll have to refer to it as ```$this->actingAs($this->user);```

The repo is for bug reporting though. Checkout some of the forums available:
- [laracasts](laracasts.com/discuss)
- [larachat](larachat.co)
- [laravel.io](laravel.io/forum)
