### ISSUE TITLE
Eloquent create method ignore the fillable attributes in laravel 5.4

### ISSUE THREAD

**Issue by mohamedryan** [laravel/framework#18951]
- Laravel Version: 5.4
- PHP Version:

### Description:
i face a problem when i register a user through web service API project, and it was working but suddenly this problem appeared ..

there an error appeared when create the user:
```
QueryException in Connection.php line 647:
SQLSTATE[HY000]: General error: 1364 Field 'name' doesn't have a default value (SQL: insert into `users` (`updated_at`, `created_at`) values (2017-04-26 23:09:20, 2017-04-26 23:09:20))
```
and what is showed to me that the eloquent create method ignore the fillable attributes.

### What i did in my code :
i have a method that do the registration for a user : 

```
public function register()
    {
        $userData  = request()->all();

        $validator = \Validator::make($userData, [
            'name'                  => 'required|alpha_spaces|max:255',
            'email'                 => 'required|email|max:255|unique:users',
            'phone'                 => 'required|phone_number',
            'password'              => 'required|min:6',
            // 'img'                   => 'required'
            // 'address_coordinates'   => 'required'
        ]);

        if ($validator->fails())
        {
            $errors = $validator->failed();
            return response()->json([
                    'message'   => 'validation error',
                    'errors'    => $errors,
                    'code'      => getMsgCode('validationErrors')
            ]);
        }

        $api_token                      = str_random(60);
        while ( count( User::where('api_token',$api_token)->first()) != 0 ) {                    
            $api_token = str_random(60);
        }

        $userData['api_token']            = $api_token;
        $userData['status']               = 1;
        $userData['dashboard_access']     = 0;
        $userData['role']                 = 'member';

        try {
            $user               = User::createUser($userData);
            $user['auth_token'] = $api_token;

        } catch (Exception $e) {
            
            return response()->json([
                    'message'   => 'something went wrong',
                    'code'      => getMsgCode('somethingWrong')
            ]);
        }

        return response()->json([
                'data'      => [
                        'user'        => $user,
                ],
                'message'   => 'success',
                'code'      => getMsgCode()
        ]);
    }
```
The code above in the **try/catch** block has the **createUser** method which it is in the **User** model :

```
public static function createUser($userData)
    {
        if( request()->hasFile('img') ) $userData['img'] = User::uploadImage($userData['img']);

        $userData['password']                       = bcrypt($userData['password']);
        $createdUser                                = User::create($userData);

        return $createdUser;
    }
```

and of course i made the **fillable** attributes for the **User** model :

```
    protected $fillable = [
         'name','email', 'password','img','gender','phone','address_ar','address_en','address_coordinates','role','dashboard_access','status','confirmed','confirmation_code','api_token','membership_id'
    ];

    protected $hidden = [
        'password', 'remember_token','confirmation_code','api_token',
        'membership_id', 'dashboard_access', 'confirmed',
        'membership_start_date'
    ];

    protected $appends = [
                    'waiting_products',
                    'waiting_services',
                ];
```
and there is some [Accessors](https://laravel.com/docs/5.4/eloquent-mutators#defining-an-accessor) that i did recently in the **User** model and i don't if they are related to this issue or not :
```
    protected function getArrayableAttributes()
    {
        if(request()->segment(1) == 'api'){

            foreach ($this->attributes as $key => $value) {
                if ($key == 'deleted_at') continue;

                if ( is_null($value) ) {
                    $this->attributes[$key] = '';
                }
            }
        }

        return $this->getArrayableItems($this->attributes);
    }
    public function getImgAttribute($value)
    {
        if(request()->segment(1) == 'api')
            return $value ? '/images/normal/'.$value : '';

        return $value;
    }

    public function getWaitingProductsAttribute($value)
    {
        return $this->products()->where('status',0)->where('product_type','product')->count();
    }

    public function getWaitingServicesAttribute($value)
    {
        return $this->products()->where('status',0)->where('product_type','service')->count();
    }
```
i saw some solution of making the **strict** mode of mysql to **false** in the _/config/database.php_ file :
```
'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true, // ========> make it to false <========
            'engine' => null,
        ],
```
but when i did it , there is **no value** entered the database except the **timestamp** values !!

- So anyone can tell me what happened here, where the problem and how can i solve it ?!
- and what this  **strict** mode in mysql ?

and thanks :)

**Comment by ankurk91** [comment]
Try to 
```php
dd($userData);
``
Just before ```User::create``` call, and see if ```name``` exists in this array.

**Comment by sisve** [comment]
That's a lot of code. Can you remove the unnecessary code; do we really need a validator and an accessor that calls route() and 8 hidden attributes and ...

Basically, can you give us an empty Model with just that one attribute you have a problem with, and an minimal hardcoded way to reproduce the problem? Would `User::create(array('name' => 'sisve'))` be enough, for example?

Regarding the strict mode; it should be enabled for any new development. The only way you get to disable it when you have an old legacy application with code you cannot understand or fix. This is not the case in this example. Always have strict mode enabled. 

To clarify what strict mode is; it forces mysql to care about you, your data and your queries. It will throw errors if your data is truncated on insert, if you divide by zero, if you use invalid dates (0000-00-00) or if your queries are vague and forces mysql to guess what you want. 

More reading: https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sql-mode-strict

**Comment by themsaid** [comment]
Please use the forums for questions, we keep this repo for bug reporting only. Thanks.

**Comment by mohamedryan** [comment]
@ankurk91 : this is some dd() test :

- in the **createUser** method in the **User** model i **dd()** the **userData** variable :

```
array:9 [
  "email" => "user12@admin.com"
  "password" => "123456"
  "phone" => "0321561235"
  "name" => "ryan"
  "api_token" => "Q3kphRxwQzcdah55yZUS9Ip6Vjt8qi09EkgrlDaRTd8jpYLGwOpqhANcW5Ce"
  "status" => 1
  "dashboard_access" => 0
  "role" => "member"
]
```

- and i **dd()** the **fillable** attributes of a new instance of the **User** model :

```
array:16 [
  0 => "name"
  1 => "email"
  2 => "password"
  3 => "img"
  4 => "gender"
  5 => "phone"
  6 => "address_ar"
  7 => "address_en"
  8 => "address_coordinates"
  9 => "role"
  10 => "dashboard_access"
  11 => "status"
  12 => "confirmed"
  13 => "confirmation_code"
  14 => "api_token"
  15 => "membership_id"
]
```
@sisve : i know this is a lot of code, but because i don't know why the problem caused, i did this .. and to make everything obvious to you, thanks :)

@themsaid : sorry, i forget about that as after i remember this i used the forums :)

**Comment by mohamedryan** [comment]
@ankurk91 , @sisve , @themsaid   : 

in my **User** model i made a construct to make dynamically hidden attributes :

and when i comment this construct, it worked again .. but idk why this cause this problem : 

```
public function __construct()
    {
        // to hide unused properties in the returned josn api.
        if(request()->segment(1) == 'api'){
            $this->addHidden(['membership_allowed_days']);
        }
        
    }
```

**Comment by ankurk91** [comment]
I am not sure if you need to call parent construct in your construct.

Do you know there is method called ```makeVisible()```.

**Comment by mohamedryan** [comment]
@ankurk91 : 

no i don't know this method ?
how its work and how can i perform it in my **User** model ? :) 

and why my construct make this problem ?

and thanks ..

**Comment by ankurk91** [comment]
Here we go
https://laravel.com/docs/5.4/eloquent-serialization

You can make any hidden property visible on demand.

**Comment by mohamedryan** [comment]
@ankurk91 : Thank you .. i called the parent construct as you said and it work :) :+1: 

i guess that i was overriding the existing mass assignment attributes .. :100:
