### ISSUE TITLE
Limited passing second param in orWhereRaw

### ISSUE THREAD

**Issue by rorc** [laravel/framework#18952]
- Laravel Version: 5.4.19

### Description:
Why in method `whereRaw` second param is not strict array (`$bindings = []`), and in method `orWhereRaw` second param is strict array (`array $bindings = []`)?

**Comment by ntzm** [comment]
Feel free to submit a PR 😄

**Comment by Alex131089** [comment]
This is an actual bug, why was this closed ? o_O
Leading to 
```
FatalThrowableError
Type error: Argument 2 passed to Illuminate\Database\Query\Builder::orWhereRaw() must be of the type array, string given
```
