### ISSUE TITLE
New eloquent model function propose: execute view, stored procedures and functions

### ISSUE THREAD

**Issue by carusogabriel** [laravel/framework#18950]
For new release of Laravel, is viable to have some Eloquent functions in `Model` class that facilitates the use of views, stored procedures and functions in database?

For example:

- `view()`;
- `procedure()`;
- `function()`;

**Comment by browner12** [comment]
please use https://github.com/laravel/internals to discuss new proposals.

**Comment by carusogabriel** [comment]
@Browner12 thanks, didn't know about that
