### ISSUE TITLE
Notification delay does not work?

### ISSUE THREAD

**Issue by adrian999999** [laravel/framework#18958]
- Laravel Version: 5.4.*
- PHP Version: 7.1
- Database Driver & Version: All up to date

### Description:
I am trying to make a mail Notification with delay.
But it seems email has been sent out immediately. 

I have `php artisan queue:worker` running. and `QUEUE_DRIVER=database`
I run `$message->recipient->notify((new MessageEmailNotification($message))->delay($when));`
in controller

in `MessageEmailNotification`
```
public function toMail($notifiable)
{
  if ($this->message->isUnread()) {

    return (new MailMessage)->line('Hello!');
  }
}
```
How do I do it locally?

**Comment by themsaid** [comment]
I'm unable to replicate your issue, please share a complete example. What's in your `$when` variable?

**Comment by adrian999999** [comment]
`$when = Carbon::now()->addMinutes(10);`
Same on the laravel docs

**Comment by rvanbaalen** [comment]
What was your solution @adrian999999 I seem to be running into the same issue.

**Comment by adrian999999** [comment]
So instead just delay the message, I use job to despatch it.
```
$this->dispatch(
  (new MessageEmailNotification($message))->delay(Carbon::now()->addMinutes(5))
);

**Comment by adrian999999** [comment]
It's been a long time, I kind of lost the context of this solution. Hopefully this helps. @rvanbaalen

**Comment by nivanmorgan** [comment]
it doesn't work... I tried it and it didn't work for me either

**Comment by joegarbett** [comment]
Just tried using ->delay($when) and it isn't delaying the message, they are being sent immediately.

**Comment by adrian999999** [comment]
@joegarbett Use job(which sends the notification) dispatch delay, not notification delay.

**Comment by joegarbett** [comment]
I've also just worked it out, it's because I did not implement ShouldQueue

`class NewWidget extends Notification implements ShouldQueue
{
    use Queueable;

}`

**Comment by trijulio** [comment]
Works for mi @joegarbett  thanks a lot!!
