### ISSUE TITLE
Middleware and CSRF Token

### ISSUE THREAD

**Issue by pjebs** [laravel/framework#18969]
- Laravel Version: 5.2
- PHP Version:
- Database Driver & Version:

### Description:
I have a middleware for a particular route that returns a view under certain situations (ie. if google crawler).

If the view IS returned, then laravel produces an error: 

```
FatalThrowableError in VerifyCsrfToken.php line 135:
Call to a member function setCookie() on null
```

### Steps To Reproduce:

route.php:

$router->group(['middleware' => ['web']], function () use ($router) {
   $router->get('/', 'IndexController@displayHomePage')->name('home')->middleware(['google']);
}

In middleware:

return view('X');

**Comment by pjebs** [comment]
The error (line 134 of VerifyCsrfToken.php) is:
```
    protected function addCookieToResponse($request, $response)
    {
        $config = config('session');

        $response->headers->setCookie(
            new Cookie(
                'XSRF-TOKEN', $request->session()->token(), time() + 60 * $config['lifetime'],
                $config['path'], $config['domain'], $config['secure'], false
            )
        );

        return $response;
    }
```

**Comment by themsaid** [comment]
Please use the forums to ask questions, forums are a more active than the repo and it's the best place to ask this kind of questions.
