### ISSUE TITLE
"artisan optimize" removes optimized class file

### ISSUE THREAD

**Issue by erkanarslan** [laravel/framework#18968]
- Laravel Version: 5.3.31
- PHP Version: 7.0.15
- Database Driver & Version: Unrelated

### Description:
`php artisan optimize` command returns this message and removes compiled files:

    > php artisan optimize
    Generating optimized class loader
    The compiled class file has been removed.

After this operation `app/bootstrap/cache` directory contains no php files.

### Steps To Reproduce:

Run `php artisan optimize` on command line.

**Comment by ankurk91** [comment]
I think this is the expected behaviour. They are going to completely remove it in v5.5

**Comment by erkanarslan** [comment]
But whrn I try to run unit tests, it says TestCase class cannot be found. I
thought that the reason is these compiled autoload files don't exist. How
is autoload handled in this case? And won't it be slower if these files are
removed because their purpose was to speed up bootstraping the app?

**Comment by erkanarslan** [comment]
Application works without problem even though those compiled files do not exist. Closing the issue.
