### ISSUE TITLE
Expected behavior of first() on a model

### ISSUE THREAD

**Issue by dericcain** [laravel/framework#18966]
If I am searching for a record in a DB and I call `first()` like so...

```php
 return $query->where('email', $email)
            ->orWhere('username', $email)
            ->orWhere('home_email', $email)
            ->orWhere('other_email', $email)
            ->first();
```

... and there is not a record, I am returned back in instance of the Query builder opposed to `null`. I looked at the API and it does say that it can return `null` but that is not what I am getting back: [Laravel API](https://laravel.com/api/5.3/Illuminate/Database/Eloquent/Builder.html#method_first) 

Why am I getting the builder instance returned? It seems like I should get `null` when there are no records so that I can easily check to see if something was returned. 

My question is, why is it created this way? What are the cons to returning `null` instead of a builder instance? I may be missing something, but it seems like that would be a better idea.

**Comment by ntzm** [comment]
I can't replicate this issue, do you have a demo repo I could check out?

**Comment by Dylan-DPC** [comment]
I tried the same and I'm getting `null`. Not sure what you have missed

**Comment by astierler** [comment]
@dericcain what version of Laravel are you on?

**Comment by themsaid** [comment]
Sorry but please ask on the forums, `first()` seems to work fine for all of us so it's most likely that you have something different in your setup, please include more details on the forums so that you can get help faster.
