### ISSUE TITLE
Clear the session cache manually 

### ISSUE THREAD

**Issue by meriemMat** [laravel/framework#18961]
hi everybody, am using laravel 5.0 with file session driver ,   I am having a  problem while trying to clear the session cache upon request (on demand), more precisely, how to make a manual call  to the function gc() of the class 'FileSessionHandler.php' in order to clear expired sessions , thx in advance .

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue
