### ISSUE TITLE
Big error when i change the publicPath option of Mix.

### ISSUE THREAD

**Issue by pierreneter** [laravel/framework#18976]
- Laravel Version: 5.4
- PHP Version:  7.1.2
- Database Driver & Version: MySQL Ver 14.14 Distrib 8.0.0-dmr

### Description:
File: `webpack.mix.js`
```
mix.options({
    publicPath: 'public/static'
});
```
Path for Images, Fonts has errors.

**Comment by ntzm** [comment]
What error do you get?

**Comment by pierreneter** [comment]
wrong path in CSS file, it keep: `public/fonts/abc.abc` in CSS file, true path is: `public/static/fonts/abc.abc`

**Comment by themsaid** [comment]
Please use the correct repo: https://github.com/JeffreyWay/laravel-mix

**Comment by pierreneter** [comment]
i used this. :) You dont understand. lol. File copied to static but, in CSS: `backgound: url('/images/...');` this is wrong.

**Comment by ntzm** [comment]
He means make an issue there, not here
