### ISSUE TITLE
Cache::many returns incorrect defaults

### ISSUE THREAD

**Issue by Dadibom** [laravel/framework#18981]
- Laravel Version: 5.4.19
- PHP Version: 7.0.15
- Database Driver & Version: phpredis

### Description:
Default values are only applied to null keys, not non-existing keys

### Steps To Reproduce:
```
Cache::put('keyThatIsNull', null, 1);
dd(Cache::many([
    'keyThatIsNull' => 'You will see this string',
    'keyThatDoesNotExist' => 'But this default value does not work, you\'ll get false instead',
]));
```

output:
```
array:2 [
  "keyThatIsNull" => "You will see this string"
  "keyThatDoesNotExist" => false
]
```

**Comment by themsaid** [comment]
Where did you get this? `many()` accepts an array of keys with no default values.

**Comment by Dadibom** [comment]
since it wasn't in the docs for cache, I had to look through the source. Check out line 124:
https://github.com/illuminate/cache/blob/master/Repository.php

**Comment by themsaid** [comment]
I see now, but I can't replicate your issue:

```
\Cache::put('keyThatIsNull', null, 1);
    
    dd(\Cache::many([
        'keyThatIsNull' => 'You will see this string',
        'keyThatDoesNotExist' => 'But this default value does not work, you\'ll get false instead',
    ]));
```

The results is:

``
array:2 [▼
  "keyThatIsNull" => "You will see this string"
  "keyThatDoesNotExist" => "But this default value does not work, you'll get false instead"
]
```

**Comment by Dadibom** [comment]
Are you using phpredis?

**Comment by themsaid** [comment]
Ok I've opened a PR with a fix: https://github.com/laravel/framework/pull/18984

Thanks :)

**Comment by Dadibom** [comment]
Thanks!
