### ISSUE TITLE
Authentication on 5.4.20 version is brake

### ISSUE THREAD

**Issue by carlospalacin** [laravel/framework#18983]
- Laravel Version: 5.4.20
- PHP Version: 7.0.13
- Database Driver & Version: MySql 5.6.34

### Description:
After update Laravel Framework  from 5.4.19 version, our authentication is brake!

When I try to get auth('crm')->user() get the follow error:
`
SQLSTATE[42S22]: Column not found: 1054 Unknown column '' in 'where clause' (SQL: select * from `dev_customer` where `` = 1 limit 1)
`
Attach migration file, customer model and auth config

anybody having the same issue?

[code.zip](https://github.com/laravel/framework/files/964480/code.zip)

**Comment by iwex** [comment]
You have wrong function 
```
    public function getAuthIdentifierName()
    {
        return $this->user;
    }
```
Remove it.
https://github.com/laravel/framework/compare/v5.4.19...v5.4.20#diff-ceca79cf09206355275774a65c622367R50

**Comment by themsaid** [comment]
Yes remove this method, its return value is wrong.
