### ISSUE TITLE
Can I get job information after LogSentMessage event fired?

### ISSUE THREAD

**Issue by larryu** [laravel/framework#18980]
- Laravel Version: 5.4.2
- PHP Version: 7
- Database Driver & Version: SQL Server 2012

### Description:
I use queue to send email.
After mail is sent, SentMessage event is fired.
The question is that can I get the job information from the MessageSent event?

I know there is another way to get the job information, which is in the Queue::failing and Queue::after event. Just wondering that whether it is also possible to get the job information in this MessageSent event if using queue to send mails.

Another thought is that usually we send emails and store them in the database at the same time.Therefore if there is a way or trigger to let the user log all emails to the database, that would be good. Thanks.

**Comment by themsaid** [comment]
Please ask on the forums, we keep this repo for bug reporting only.
