### ISSUE TITLE
Php Artisan commands throw an error after composer update

### ISSUE THREAD

**Issue by esiona** [laravel/framework#18999]
- Laravel Version: 5.4.21
- PHP Version: 7.0.10
- Database Driver & Version:

### Description:
hello, 
i would like to run locally a repository using laravel and wamp server. I have installed composer in windows and whenever I try to run either composer install or update I get the error which is displayed in the image below. As a result I am not able to run php artisan commands. Do you have any idea what is the cause of this problem?

### Steps To Reproduce:
![image](https://cloud.githubusercontent.com/assets/10435256/25555924/0dda84c8-2cfb-11e7-8ea5-79217f268724.png)

**Comment by themsaid** [comment]
There's a syntax error in one of your project files, you need to check the error log for more details.
