### ISSUE TITLE
Route Resource Bug under Group Prefix

### ISSUE THREAD

**Issue by daison12006013** [laravel/framework#18992]
- Laravel Version: 5.4.20
- PHP Version: 7.1

### Description:
API Bug when using prefix and inside the closure is a Route Resource, the resource for PUT/DELETE methods are not working, it throws an error `NotFoundHttpException`.

This might be caused by the prefix, upon running `artisan route:list`, the `URI` contains like this `api/post/{}` for PUT and DELETE method.

But putting back the `Route::resource()` outside the group prefix, the thing works well.

### Steps To Reproduce:
```
# buggy
Route::group(['prefix' => 'post'], function () {
    Route::resource('/', 'PostController');
    Route::resource('vote', 'PostVoteController');
});

# working
Route::resource('post/', 'PostController');
Route::resource('post/vote', 'PostVoteController');
// Route::group(['prefix' => 'post'], function () {
// });
```

**Comment by lagbox** [comment]
That isn't how you use `Route::resource`.  The first argument to it is a 'resource name', not a path. `/` is not a resource. Its not a general method for registering routes for a random controller. It specifically is meant for dealing with resources and needs a 'resource' to use.
The resource is how it knows how to name the route parameters. Not sure why people keep trying to do this.

**Comment by daison12006013** [comment]
But that's how the router of Laravel designed right, then there must be thrown error telling us the Route resources must not be injected inside a prefix, So from Route resource itself, we can't group them to handle a single middleware "auth:api" you mean?

```
Route::get('accounts/create', [...]);
Route::get('accounts/edit, [...]);
Route::post('accounts/edit, [...]);
```

But we could make that route something like these

```
Route::group(['prefix' => 'accounts'], function () { ... });
```

If you will imagine, the resource must be along the prefix itself, else throw an error instead, I just wasted my whole time, so this is not a bug at all, a magic again?

**Comment by lagbox** [comment]
It has nothing to do with the prefix ... again ... You are not passing it a resource name.

**Comment by daison12006013** [comment]
Huh?, can't you imagine the route sequence?

```
Route::group(['prefix' => 'users'], function () {
	Route::get('/', 'UserController@xAction');              # /users
	Route::get('/{id}/edit', 'UserController@editAction'); # /users/1/edit
});
```

The above code is a normal routing, but simple route method can inherit the prefix 'users' as '/users' uri.

```
Route::group(['prefix' => 'users'], function () {
	Route::resource('/', 'UserController');              # /users
        Route::resource('/posts', 'UserPostsController');      # /users/posts
});
```

So the above code, can't we inherit the prefix from the resource it self @lagbox? since it is confusing if we can't comparing the structure of basic routing.

**Comment by lagbox** [comment]
You can put them in groups. It doesn't matter. 
`Route::resource` uses that name as part of the URI and for the route parameters. That is what it is for.
Im not sure what part of this you are having trouble with.

The prefix is applied to the generated routes.

```php
Route::group(['prefix' => 'test'], function () {
    Route::resource('blah', ...);
});
```
`test/blah/{blah}` - show
`test/blah` - index

It uses the `name` of the resource as part of the URI and the parameter. The docs example should make this apparent.

It literally defines specific routes for you in a specific way. If you don't want that, don't use it.  This is not a general way to register routes. It is a specific thing for resources.

**Comment by daison12006013** [comment]
It was ACTUALLY/LITERALLY/ABSOLUTELY WORKING BEFORE,, you must try it out from other old versions, if this is not a bug at all, atleast throw an error if they are under the prefix, since the case now is that resources must be outside a prefix already to summarize your opinion @lagbox. Isn't it good to have runtime error with those things, rather than debugging/wasting time for those magic things happening inside the routes.

**Comment by lagbox** [comment]
It uses the 'resource name' as the parameter name. No resource name, no parameter name. What do you think the route parameter is going to be?
