### ISSUE TITLE
SQL Server Date Format incorrect

### ISSUE THREAD

**Issue by neclimdul** [laravel/framework#18991]
- Laravel Version: 5.4.X
- PHP Version: 7.1.4, 7.0.18, 5.6.30
- Database Driver & Version: sqlsrv(freetds)

### Description:

Similar to #653 but I think this might be a newish bug maybe caused by this change: https://github.com/php/php-src/commit/53c036b30bdabedf841fb8716a7cd722bbab09a3.

My guess is that the releases in ubuntu 14.04 and maybe 16.04 don't include this patch since its newish and changes and is not entirely BC as we see here. Its possible though this is some other arcane combination of configurations, its hard to bisect.

Example trace:
```
in Carbon.php line 582
at Carbon::createFromFormat('Y-m-d H:i:s.000', '2017-04-28 17:23:08') in HasAttributes.php line 709
at Model->asDateTime('2017-04-28 17:23:08') in HasAttributes.php line 122
at Model->addDateAttributesToArray(array('id' => 1, 'name' => 'ab', 'email' => 'keyon.purdy@renner.com', 'created_at' => '2017-04-28 17:23:08', 'updated_at' => '2017-04-28 17:23:08')) in HasAttributes.php line 84
at Model->attributesToArray() in Model.php line 887
at Model->toArray() in Model.php line 916
at Model->jsonSerialize() in Model.php line 900
at Model->toJson() in Response.php line 67
```

### Steps To Reproduce:
Convert a timestamp field from the database to a string. Any interaction with the timestamps that trigger `toString()` throws a fatal error and trigger this bug so a simple `print $user->created_at` or probably even trying to save back to the database would do the trick too.

Getting sqlserver setup can be tricky but luckily we've got a sqlserver docker image now. Even then getting php configured with it isn't easy so I've created a repo with a docker-compose script to easily demonstrate the error.
https://github.com/neclimdul/laravel_sqlserver

Its mostly some a Dockerfile, docker-compose.yml, and some entrypoint scripts to setup a functional site with data so you don't have to fiddle with running commands in docker images.

Additionally there is a controller that returns a user object obviously which is the worst site design ever but its a concise example of the bug. This return triggers the the error as soon as the created_at timestamp is converted to a string to be serialized.

**Comment by neclimdul** [comment]
Thinking about it more, the old issue and the non-standard format is almost certainly caused by the PHP bug. The previous reporter was getting that format not because of the SQL Server edition but because the client's locale was triggering http://www.freetds.org/userguide/locales.htm to use a different format. They could have just as easily modified that file to have it return the format Laravel expected.

I'm guessing the non-standard format in the grammar is there to work around this exact same bug and have it match the default or common locale format.

Unfortunately, now that PHP fixed the bug and there is hard coded value inside of PHP there is no way on current versions of PHP to get the format Laravel expects.

**Comment by themsaid** [comment]
Any updates on this?

**Comment by neclimdul** [comment]
I use `cweagans/composer-patches` to deploy this patch into our app today. Past that I think we're waiting on the laravel team to review/approve the change. :(

**Comment by aisartag** [comment]
propose change from datetime to datetime2. this type is indipendent from default language et dateformat.Majority language have format dmy,
Visit https://docs.microsoft.com/en-us/sql/t-sql/data-types/datetime-transact-sql

**Comment by aisartag** [comment]
changes in sqlserver class
- in  schema grammars  return 'datetime2' substitute 'datetime'
in query grammars  
public function getDateFormat()
    {
        return 'Y-m-d H:i:s.0000000';
    }

**Comment by neclimdul** [comment]
I should provide an update I guess since this is filed against 5.4. I still patch 5.6 and basically roll back the "fix" with `.v` and remove the getDateFormat() method entirely so it correctly respects my locale settings.

**Comment by laurencei** [comment]
@neclimdul - with your update, are you saying this is fixed or not?

And is this a bug with PHP or Laravel? Your original post implies it is a problem with PHP?

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by neclimdul** [comment]
Yeah, I still patch to fix this issue.

**Comment by mgutierrez-ei** [comment]
Hello there, I just came across this problem on my laravel (passport) - sqlserver configuration and I noticed the problem was that when running "php artisan migrate:refresh --seed" or "php artisan passport:install" the error "SQLSTATE[22007]:" appeared for the reason that laravel sends this date format "Y-m-d H:m:s.v" but sqlserver recevies "Y-d-m H:m:s.v" so I change the order of the format from 'Y-m-d H:m:s.v' to 'Y-d-m H:m:s.v' on SqlServerGrammar.php file

public function getDateFormat()
{
return 'Y-d-m H:m:s.v';
}

Worked from me!

greetings!

**Comment by neclimdul** [comment]
I expect there is some sort of customization or localization on the date format SqlServer expects. I've not found any documentation on this and its only based on the fact that I and handful of others don't seem to match laravel's support and I was never able to get any CI using MS's SqlServer containers to work the same as our production systems.

I don't manage these database servers and I'm not familiar with the subtleties of managing SqlServer instances so if someone does land here and has pointers it would be great to some documentation links people can use to get their systems setup consistently.
