### ISSUE TITLE
A bug in Eloquent relations

### ISSUE THREAD

**Issue by mhemrg** [laravel/framework#19006]
- Laravel Version: 5.3.*
- PHP Version: 7
- Database Driver & Version: MySQL 5.7

### Description:
Hi, I faced a problem in Eloquent. When I tried to make a query and add where and orWhere on the relations, it returns a same record multiple times because either side of the where clause returns true.

### Steps To Reproduce:

Query:
```
$product = App\Model\Product::find(1);
$product['tags'] = $product->tags()->where('tags.id', 1)->orWhere('tags.tag', 'like', 'Blue%');
```

Products table:
```
+----+-----------------------+
| id   | name                   |
+----+-----------------------+
|  1  | My first product    |
+----+-----------------------+
```
Tags table:
```
+----+----------------------------+
| id | tag                        |
+----+----------------------------+
|  1 | BlueViolet58e8ae5228025    |
|  2 | DarkTurquoise58e8ae522807c |
|  3 | Red58e8ae52280c4           |
|  4 | Peru58e8ae5228107          |
+----+----------------------------+
```

It might return first record of the tags table multiple times.

**Comment by mhemrg** [comment]
If I use:
```
App\Model\Product::with(['tags' => function ($query) {
            $query->where('tags.id', 1)->orWhere('tags.tag', 'like', 'Blue%');
        }])->find(1);
```
instead of previous code, it will work correctly!

**Comment by jarektkaczyk** [comment]
Not a bug, just a feature ;)

Here you'll find detailed info http://stackoverflow.com/a/23625759/784588 while this in short tells you what to do:

```php
$product->tags()->where(function ($query) {
   $query->where('tags.id', 1)->orWhere('tags.tag', 'like', 'Blue%');
})->get();
```
