### ISSUE TITLE
public_path helper hardcoded to 'public'

### ISSUE THREAD

**Issue by snapey** [laravel/framework#19000]
- Laravel Version: 5.4
- PHP Version: n/a
- Database Driver & Version: n/a

### Description:
It should be possible to change the target for public_path helper.

Application.php contains hardcoded 'public' 

    public function publicPath()
    {
        return $this->basePath.DIRECTORY_SEPARATOR.'public';
    }

This should come from config for people that have the name of their public folder mandated by the service provider.

**Comment by Dylan-DPC** [comment]
This is not a bug. Open an issue in the laravel/internals repo

**Comment by laurencei** [comment]
@Dylan-DPC - how is this not a bug?

You can change the application public path using the IoC container:

```
App::bind('path.public', function() {
    return base_path().'/public_html';
});
```

So the helper should not be hardcoded to return the wrong path - it should resolve it like all the other helpers?

**Comment by Dylan-DPC** [comment]
The way he explained it above, I assumed he was adding some flexibility
