### ISSUE TITLE
No means to pause queues when using Redis (and perhaps others)

### ISSUE THREAD

**Issue by omanizer** [laravel/framework#19014]
- Laravel Version: 5.3.31
- PHP Version: n/a
- Database Driver & Version: n/a

### Description:
I used to use Beanstalk for queues however I switched as AWS Elasticache offered easy Redis redundancy, and since I was already using Redis for my cache, why not also use it for queues and have one less server in my cloud setup?  TL:DR; I'm using Redis for Queues.

I have an auto-scaling group of queue worker instances that increases as number of tasks in the queue grows.  Typically there are 2 worker instances scaling up from there.  I usually process about 5M jobs per day, many of them transactional HTTP requests, DB aggregation tasks, etc.  Suffice it to say that it's very difficult (if not impossible) to quickly pause or stop all of these workers in the event of an emergency (a customer needing to cancel a message they just sent to 500k people or...though this would never ever happen...some bad code was pushed).

Beanstalk has a nice feature of being able to pause a queue (tube) and it just stops making jobs available.  Unfortunately Redis doesn't have the same ability.  I'm guessing that if I have this problem it's likely somebody else has it as well, so either there's something I'm not seeing or there's an opportunity for me to contribute, which has thinking how this could actually happen.  I see a couple possible solutions:

1) Implement a flag inside of Redis that a queue worker checks before requesting a job.  If that flag says the queue is currently paused, the worker would go to sleep as if there were no jobs in the queue and try again after that interval.
2) It appears that when I call php artisan queue:restart it adds a flag that workers on all other instances listen to.  If there were some sort of "stop" flag that worked the same way...  Being that all my workers are backed up by Supervisor, it would be difficult to actually stop them unless Supervisor listens to a specific type of Kill signal.  Haven't researched this option much, and frankly it's starting to sound a lot like (1) if Supervisor doesn't respond this way.

So, would it be a logical thing to have every worker check a flag (in redis only) to determine if a queue has been paused?

### Steps To Reproduce:
Exist.

**Comment by themsaid** [comment]
Thanks for your suggestion, I find it quite interesting and will be discussing it with Taylor for sure, but for suggestions and feature requests please use the https://github.com/laravel/internals repo.

We try to keep this repo for bug reporting only, thanks again :)

**Comment by omanizer** [comment]
Thanks for your response.  I'm happy to add this post there.  Would it be beneficial to?

As far as implementation, it would be quite easy to modify the pop method of Illuminate\Queue\RedisQueue to check for a pause flag for that queue.

**Comment by themsaid** [comment]
I believe it's pretty useful, but we'll need to apply it for all drivers if possible.

So yeah might be good to add it there so people look into it and start discussing ideas, and maybe it'll make it to the core :)
