### ISSUE TITLE
Processor::processInsertGetId Casting with overflow [PHPx86]

### ISSUE THREAD

**Issue by Arekusei** [laravel/framework#19035]
- Laravel Version: 5.4 - Possible all 5.x versions
- PHP Version: 7.1x86
- Database Driver & Version: MySQL 5.7

### Description:
This cast is incorrect for x86 interpreter
```php
    public function processInsertGetId(Builder $query, $sql, $values, $sequence = null)
    {
        $query->getConnection()->insert($sql, $values);
        $id = $query->getConnection()->getPdo()->lastInsertId($sequence);
        return is_numeric($id) ? (int) $id : $id;
    }
```
If autoincrementing field is `BIGINT`, we'll get to overflow int type when value will be great then `PHP_INT_MAX`.

### Steps To Reproduce:
I don't know, but does it make sense to fill this for this case?

**Comment by Arekusei** [comment]
Eg.
```

php -r "$posNum = '2472615623'; var_dump(is_numeric($posNum)? (int)$posNum : $posNum);"
int(2147483647)

```

**Comment by masterwto** [comment]
I agree with @Arekusei.
The last line 
'''return is_numeric($id) ? (int) $id : $id;'''
makes no sense. Why do you want the id to be an integer ?

**Comment by Arekusei** [comment]
I propose replace it by this
```php
return filter_var($id, FILTER_VALIDATE_INT) !== false ? (int)$id : $id;
```

**Comment by Arekusei** [comment]
@themsaid @tillkruss @taylorotwell  
Where's the answer? Can anyone answer? 
In the pull-request, the last messages were ignored.

**Comment by mharkrollen2** [comment]
I have the same problem. The last line breaks my application.

**Comment by tillkruss** [comment]
Is this issue still present in 5.6?
