### ISSUE TITLE
distinct , join with paginate  dose not work properly due to missing column parameter

### ISSUE THREAD

**Issue by alhad15** [laravel/framework#19039]
- Laravel Version: 5.4.#
- PHP Version:
- Database Driver & Version:

### Description:
distinct , join with paginate  dose not work properly 
file framework/src/Illuminate/Database/Eloquent/Builder.php 
line 690 getCountForPagination() function has column parameter is missing

**Comment by Dylan-DPC** [comment]
can you share some code?

**Comment by alhad15** [comment]
https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Builder.php
line 690 
$results = ($total = $this->toBase()->getCountForPagination())
i think be should be
$results = ($total = $this->toBase()->getCountForPagination($columns))

**Comment by themsaid** [comment]
Duplicate of: https://github.com/laravel/framework/pull/18186
