### ISSUE TITLE
Whatsapp Plugin

### ISSUE THREAD

**Issue by wassimhattab** [laravel/framework#19044]
Hello,

i'm using Laravel 5.4.X,

I was searching if i can find whatsapp library to use in my laravel project i found two but when i try to request a code i got old_version i guess the libraries stopped working...

Have anyone tried a whatsapp library recently and it's working?

Thank you,

**Comment by browner12** [comment]
issues are for bug reports only. please ask this question on a forum or the laravel slack channel
