### ISSUE TITLE
Routes stopped working in 5.4.21

### ISSUE THREAD

**Issue by leeniu** [laravel/framework#19051]
- Laravel Version: 5.4.21
- PHP Version: 7.1 (Homestead)
- Database Driver & Version: Not sure (Homestead)

### Description:
With updating the laravel framework from 5.4.19 to 5.4.21 via composer-update, suddenly the routes stop working.

`NotFoundHttpException in Application.php line 903:`

We have the following code in our HomeController, that checks every url request:

    
```/**
     * Show the application start page.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($url_slug = null)
    {
        $page = Page::where([
            'url_slug' => $url_slug
        ])->first();
        if(!$page) abort(404);

        return view('home', compact("page"));
    }
```

This worked fine in Version 5.4.19 and stopped working with 4.5.21. Reverting back to 5.4.19 does make the application work again.

**Comment by themsaid** [comment]
Check the value of `$url_slug` and let us know what difference do you see from what you expect?

**Comment by leeniu** [comment]
it actually provides the respective slug like 'dashboard', when I try to access 'dev.app/dashboard'. So it seems more to be that the 'Page::where...' portion stopped working, because it always returns null. 'Page' btw. is a valid model class that is used within this controller.

**Comment by leeniu** [comment]
And oh yeah, there is actually a database entry that has the url_slug value 'dashboard'

**Comment by themsaid** [comment]
Try:

```
Page::where([
            'url_slug' => 'dashboard'
        ])->first();
```

And make sure there's an entry in the database, because I don't seem to be able to replicate your issue, you need to provide more details.

**Comment by Aven30** [comment]
@leeniu Can you output the sql query and its binding, like so

```
$query = Page::where([
            'url_slug' => $url_slug
        ]);
Log::info(var_dump($query->toSql()));
Log::info(var_dump($query->getBindings()));
```
