### ISSUE TITLE
No way to customize confirmation postfix in validatior

### ISSUE THREAD

**Issue by sartatpdev999** [laravel/framework#19050]
- Laravel Version: 5.4.19

### Description:
There is no way to customize confirmation postfix in validatior. For example, it's impossible to use `password-confirmation` instead of `password_confirmation` because `_confirmation` string is inside `validateConfirmed` method.

### Steps To Reproduce:
1. Add `$confirmation_postfix` parameter to `validateConfirmed` method in `Illuminate\Validation\Concerns\ValidatesAttributes`
2. And something else...

**Comment by Dylan-DPC** [comment]
This is not a bug. Open an issue in the laravel/internals repo

**Comment by sartatpdev999** [comment]
Thanks. Moved to [laravel/internals/#565](https://github.com/laravel/internals/issues/565)
