### ISSUE TITLE
Add ability to listen to events once (Event::listenOnce)

### ISSUE THREAD

**Issue by tpetry** [laravel/framework#19056]
In some cases you want to register Event listeners which only listen to an event once.
Take the following example:

1. A user http requests puts a job in the queue
2. The worker is dispatched and calls some encapsulated logic which is doing a database operation
3. the encapsulated logic is finished and wants to publish another event to the queue to do something wit the data

Problem: The encapsulated logic can't queue the job because the database transaction of the surrounding code may not be committed yet. Any other worker can't see the new data. Therefore the encapsulated logic listens for the successful database commit:
```php
Event::listen(TransactionCommitted::class, function() {
  if(DB::transactionLevel() > 0)
    return; // some inner-transaction (safe-point) finished

  // ... now do something
});
``` 

This works perfectly, BUT the closure will be stored within the dispatcher until the script may end some time (memory-leak) and notified for every committed database transaction of worker jobs running later.
A method like `Event::listenOnce` would be really useful. Even complicated schemes like listening for 15 events would be possible by re-listening 14 more times.

**Comment by Dylan-DPC** [comment]
This is not a bug. Open an issue in the laravel/internals repo

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
