### ISSUE TITLE
Factories broken probably after a patch change.

### ISSUE THREAD

**Issue by FedericoBiccheddu** [laravel/framework#19054]
- Laravel Version: ^5.4.17
- PHP Version: 7.1
- Database Driver & Version:

### Description:
We were using Laravel 5.4.21 and noticed that all version >=5.4.17 has a change that breaks the factory usage.
Returning to 5.4.16 the problem is solved so we are thinking about a probably patch change that breaks something we don't know about it.

### Steps To Reproduce:
Try this pseudo code:
```php
# app/database/factories/Factory.php

$factory->define(\App\Foo::class, function(\Faker\Generator $generator) {
    return [
        'id' => $generator->randomNumber(),
        'relationship' => factory(\App\Bar::class)->make()
    ];
});

$factory->define(\App\Bar::class, function(\Faker\Generator $generator) {
    return [
        'id' => $generator->randomNumber()
    ];
});
```
Even using closures in the factory with something like this:

```php
# app/database/factories/Factory.php

$factory->define(\App\Foo::class, function(\Faker\Generator $generator) {
    return [
        'id' => $generator->randomNumber(),
        'relationship' => function() {
                return factory(\App\Bar::class)->make();
        }
    ];
});

$factory->define(\App\Bar::class, function(\Faker\Generator $generator) {
    return [
        'id' => $generator->randomNumber()
    ];
});
```

While testing you will receive the following error:
`TypeError: Argument 1 passed to App\Foo::myMethod() must be an instance of App\Bar, integer given, called in ...`

**Comment by themsaid** [comment]
Can't replicate either, factories seem to work fine.

**Comment by themsaid** [comment]
What is `myMethod()`? Please share a simple test that uses the factories you presented.
