### ISSUE TITLE
everything after domain is stripped in APP_URL

### ISSUE THREAD

**Issue by henritoivar** [laravel/framework#19068]
- Laravel Version: 5.2.45
- PHP Version: 7.0.3
- Database Driver & Version: MySQL 5.7.11

### Description:
When using asset() from console, the url property in config/app.php is used as the root to generate a valid url.
The issue is that when using a url like http://my-app.dev/main/ as the application url (APP_URL) then everything after the domain gets stripped.

Not all applications live on the root of a domain, so this should not be stripped.

### Steps To Reproduce:
set `APP_URL=http://my-app.dev/main/` in .env
run `asset('my-route')` from `php artisan tinker`
result is http://my-app.dev/my-route
should be http://my-app.dev/main/my-route

**Comment by themsaid** [comment]
Check https://medium.com/@kunalnagar/deploying-laravel-5-on-godaddy-shared-hosting-888ec96f64cd

**Comment by henritoivar** [comment]
@themsaid Hey, i still consider this a bug because the generated url is different when script is run from console vs browser. The suggested solution you mentioned is only a workaround for some cases. I cannot serve my api from root as root is already used for the main website.

All the links in my emails are broken after moving some functionality to be triggered from cron tasks and queue.

I think the issue should be reopened.

**Comment by whereisaaron** [comment]
I agree with you @henritoivar `APP_URL` should do that same thing at run-time as in the console. I wondered by `APP_URL` wasn't working for deployments and this explains why.

You shouldn't need to physically copy an application in directory 'foo' just to serve it as `/foo/`. It should be able to live in the root of a application server and be served via the loadbalancer/proxy as `/foo/` and generate URLs containing `/foo/`. That is how I expected `APP_URL` to behave. If not it would be better renamed `APP_CONSOLE_URL` which is all it really is right now 😢
