### ISSUE TITLE
Migration error: 1071 Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by whfamily2006** [laravel/framework#19065]
- Laravel Version: 5.4.21
- PHP Version: 7.0.9
- Database Driver & Version: mysql (xampp windows)

### Description:

Migration working in 5.3 but not in 5.4 in the same development environment.
error: 

> 1071 Specified key was too long; max key length is 767 bytes

### Steps To Reproduce:
clone 5.3 and run migration, its working fine.
and clone 5.4 and run migration, it's not working.

**Comment by themsaid** [comment]
Please check the upgrade guide.

**Comment by whfamily2006** [comment]
@themsaid please have a look on **steps to reproduce**.
I am clone latest version of 5.4 and separately 5.3, not upgrading the 5.3 into 5.4.

**Comment by themsaid** [comment]
https://laravel-news.com/laravel-5-4-key-too-long-error

**Comment by whfamily2006** [comment]
Thank you very much @themsaid.

**Comment by hultberg** [comment]
@themsaid Excuse me, but where in the upgrade guide 5.4 from 5.3 is this specified? I can't find any mention of a character set change in the migrations, as the laravel-news article is pointing out. Thou, the fix is in the migration docs.
