### ISSUE TITLE
Mail::send callback ignored for mailables

### ISSUE THREAD

**Issue by tpetry** [laravel/framework#19066]
- Laravel Version: 5.4.21

### Description:
The callback of `Mail::send($view, array $data = [], $callback = null)` is ignored when sending a `Mailable` because the callback is not passed to `sendMailable` function and back to the mailer:
```php
    public function send($view, array $data = [], $callback = null)
    {
        if ($view instanceof MailableContract) {
            return $this->sendMailable($view);
        }

        // ...
    }

```
For a mailable which is not queued the callback should be called.

### Steps To Reproduce:
```php
Mail::send(new SomeMailable(), [], function() {
    var_dump('callback called');
});
```

**Comment by themsaid** [comment]
It wasn't supposed to be used like this in the original implementation, but feel free to open a PR with your suggestion.

Or for suggestions and feature requests please use the https://github.com/laravel/internals repo.
