### ISSUE TITLE
OnlyTrashed reset when using orWhere

### ISSUE THREAD

**Issue by simonmeusel** [laravel/framework#19070]
- Laravel Version: 5.3.31
- PHP Version: 7.0.13
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.7.13, for osx10.11 (x86_64) using  EditLine wrapper

### Description:

When using the `onlyTrashed` method only trashed items get shown. This breaks if you use the `orWhere()` method. That behavior might cause data loss!

This behavior might be indended, but I think that the `orWhere` method should not reset the `onlyTrashed`  effect.

Some examples:

`::onlyTrashed()->get()`
Shows only trashed items: correct

`::onlyTrashed()->where('id', '<', '10000')->orWhere('id', '>', '-1')->get()`
Shows trashed and not trashed items with id > -1: incorrect in my opinion

`::onlyTrashed()->where('id', '<', '10000')->orWhere('id', '>', '-1')->onlyTrashed()->get()`
Shows only trashed items: correct

### Steps To Reproduce:

Create a migration and model with SoftDelete trait and incrementing id column (for example).

**Comment by Dylan-DPC** [comment]
```
::onlyTrashed()->orWhere('id', '>', '-1')->get()
Shows trashed and not trashed items with id > -1: incorrect in my opinion
```

How is this incorrect? 

You are asking the Eloquent kings to provide you either with trashed ones *OR* the ones which have an ID more than 1.

**Comment by simonmeusel** [comment]
Ok, i removed that example because thats makes it unclear.

But what about the second last example? I think the `orWhere` should only overwrite the `where` and not the `onlyTrashed`.

`::onlyTrashed()->where('id', '<', '10000')->orWhere('id', '>', '-1')->get()`

**Comment by sebdesign** [comment]
You should wrap the two `where`s in a closure `where`:

```php
::onlyTrashed()->where(function ($query) {
    $query->where('id', '<', 10000)->orWhere('id', '>', -1);
})->get();
```

**Comment by simonmeusel** [comment]
Ok THANK YOU

**Comment by devcircus** [comment]
or append the call to 'onlyTrashed()'
```
Model::where('name', 'iphone')->orWhere('price', '>', 300)->onlyTrashed()->get();
```
