### ISSUE TITLE
Automatic Model Eager-Loading Failing on Polymorphic Relationships

### ISSUE THREAD

**Issue by C1aymore** [laravel/framework#19076]
- Laravel Version: 5.2 (Suspect bug is present in later versions, but haven't confirmed)
- PHP Version: 5.6

### Description:
If you have a Model class that leverages the $with array within it, and a morphTo relationship defined, the relationship will not work when eager-loading it.  (Haven't tried lazy-loading yet, but given what I've discovered, I doubt the bug would be present then.) I believe the problem is in how the MorphTo class handles the Builder query and Model parent.  In every other relationship-type, the Relation class' query-model is the related model, and the parent is the source.  But in a MorphTo, they're the very same object.

This makes sense when you consider the fact that a MorphTo relationship needs to execute a query before even knowing what the related model _really_ is.  I almost wonder if the query-model is just incidental in this context.  That the real purpose of that object is just to record any eager-loads you add later, using the more common "$model->with('stuff.moreStuff')".  So using the original parent Model is just a placeholder to reach functionality in an otherwise-abstract Model class.

The problem is, if the Model within the Builder object *already* has eager-loads defined via the $with property, it will try to execute those against the related one as well, and fail.  That instance of the Model doesn't know it's just a placeholder, whose eager-loads are going to be forwarded on to another Model.

The solution seems simple enough though.  In MorphTo::__construct, just call "$query->setEagerLoads([]);" before doing anything with the $query object.  Those eager-loads will have already been applied to the $parent model anyway, so even if the call didn't fail, it'd be redundant.

### Steps To Reproduce:

```
class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Relation::morphMap([
            'item_type1' => ItemTypeOne::class,
            'item_type_2' => ItemTypeTwo::class
        ]);
    }
}
```

```
class Catalog extends Model
{
    protected $with = ['name'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function name()
    {
        return $this->belongsTo(NameLookup::class, 'name_id');
    }
    
    /**
     * @return \Illuminate\Database\Eloquent\Relations\MorphTo
     */
    public function item()
    {
        return $this->morphTo(null, 'item_type', 'item_id');
    }
}
```

```
$results = app(Catalog::class)->with('item')->first();
```

An error will appear in the log stating that there is no 'name' method on the given Builder object.  And the stack trace will indicate that this is because Eloquent is attempting to execute the type() method on ItemTypeOne or ItemTypeTwo, rather than just Catalog.

The reason I think this bug is present in more than just version 5.2 is because I had attempted to patch this by grafting on methods from a 5.4 version of the MorphTo class into an override class within my 5.2 app, and the problem was still present.  I will update this issue later though, when I get time to more thoroughly try to actually reproduce it in a 5.4 environment.  And after I make sure that my proposed fix doesn't break any Framework unit tests.

**Comment by Dylan-DPC** [comment]
I am suspecting that 
```
  Relation::morphMap([
            'item_type1' => ItemTypeOne::class,
            'item_type_2' => ItemTypeTwo::class
        ]);
```
this could be a reason why you are not getting the expected answer. Can you try with a different example?

**Comment by themsaid** [comment]
Please test on a 5.4 version since 5.2 is not supported anymore.
