### ISSUE TITLE
Collection not merge with another collection

### ISSUE THREAD

**Issue by IgorDePaula** [laravel/framework#19074]
- Laravel Version: #.#.#
- PHP Version: 5.6
- Database Driver & Version: Mysql 5.6

### Description:
Collection not merge with another collection

### Steps To Reproduce:
Create 2 collections, try use a merge method by collection 1 with collection 2.

I using with a zend framework, for facility my work, its great, its fantastic, but has this bug.

**Comment by Dylan-DPC** [comment]
Some code please?

**Comment by IgorDePaula** [comment]
https://gist.github.com/IgorDePaula/6dfdecc236f2b068e27ed7073bae6086

**Comment by sede2** [comment]
`$merged = $col1->merge($col2);`

**Comment by IgorDePaula** [comment]
I'll try.

2017-05-05 12:17 GMT-03:00 Sergio Bonito <notifications@github.com>:

**Comment by IgorDePaula** [comment]
This col has multidimensional array, by form above, some elements are
destructed.

2017-05-05 12:20 GMT-03:00 principe.borodin@gmail.com <
principe.borodin@gmail.com>:

**Comment by Dylan-DPC** [comment]
if indices are same it will overwrite them

**Comment by sede2** [comment]
I've used the code in your example

**Comment by Dylan-DPC** [comment]
... and?

**Comment by IgorDePaula** [comment]
In this case, yes, it will overwrite, but was not.
