### ISSUE TITLE
[5.3] Router::auth() Route for password reset do not have a name

### ISSUE THREAD

**Issue by Cyrille37** [laravel/framework#19085]
- Laravel Version: 5.3.31
- PHP Version: 7
- Database Driver & Version: Mysql

### Description:

Route for password reset do not have a name. But routes for "login", "logout" and "register" have a name.

### Proposal:

`$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('passwordreset');`

**Comment by Cyrille37** [comment]
Fixed on Dec 26, 2016 in L5.4 https://github.com/laravel/framework/commit/04d17a75bdea036a613fb0baba9a59119d6f41fd

**Comment by Dylan-DPC** [comment]
5.3 is no longer supported.

**Comment by Cyrille37** [comment]
I do not see L5.3 support is closed in [CHANGELOG-5.3](https://github.com/laravel/framework/blob/5.3/CHANGELOG-5.3.md). I'll try to create a PR :-)

**Comment by Dylan-DPC** [comment]
It is. Every non LTS version of Laravel is supported for 6 months and a grace period of 1 month or something similar. L5.3 was out of life in February 2017 if i remember correctly

**Comment by Cyrille37** [comment]
I created a PR #19103. Perhaps it will be lost in history :-)
Thanks for discussion. Cheers.

**Comment by bbashy** [comment]
And the PR was closed. Looks like you can close this issue as well.

Try upgrade to 5.4, add the routes yourself or wait for 5.5
