### ISSUE TITLE
FatalThrowableError in PhpRedisConnector.php line 95: Call to undefined method Illuminate\Support\Facades\Redis::connect()

### ISSUE THREAD

**Issue by gfd6th** [laravel/framework#19089]
- Laravel Version: "5.4.*",
- PHP Version: php7.1.4,  phpredis --> homebrew/php/php71-redis: stable 3.1.1
- Database Driver & Version: 

### Description:
```
in PhpRedisConnector.php line 95
at PhpRedisConnector->establishConnection(object(Redis), array('host' => '127.0.0.1', 'password' => null, 'port' => '6379', 'database' => 0)) in PhpRedisConnector.php line 66
```

It seems Redis facade doesn't work in this environment.

I test it in in tinker,

```
// the following code will throw an error
use Redis;
Redis::keys('*')

// the following code will work
Illuminate\Support\Facades\Redis::keys('*')

```

**Comment by it-can** [comment]
Try renaming the Redis facade in your config/app.php. Redis is the name of the phpredis library, so it will not work, unless you rename it...

**Comment by themsaid** [comment]
Please continue on the forums.
