### ISSUE TITLE
New laravel install with per project homestead setup problem

### ISSUE THREAD

**Issue by juslintek** [laravel/framework#19088]
- Laravel Version: 5.4.21
- PHP Version: 7.1
- Database Driver & Version: mysql 5.7.4
- OS: Windows 10 x64 Home Edition
- Bash platform: Github based bash for Windows.

### Description:

Its actually more laravel/setter problem I guess, but I report here, because if I go to https://github.com/laravel/settler I have no issues section there.
![Screenshot](https://snag.gy/pMW9xh.jpg)
So I'm getting this:
```

$ vendor\\bin\\homestead make

Strict Standards: Static function Laravel\Homestead\Settings\HomesteadSettings::fromFile() should not be abstract in D:\www\youtube_task\vendor\laravel\homestead\src\Settings\HomesteadSettings.php on line 30
Homestead Installed!
```
problem when trying to run
vendor\\bin\\homestead make

### Steps To Reproduce:
1. laravel new project
2. composer require laravel/homestead --dev
3. vendor\\bin\\homestead make

**Comment by devcircus** [comment]
The Homestead repo accepts issue reports.
https://github.com/laravel/homestead/issues

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by vmarle** [comment]
@juslintek just experienced this issue as well and felt sad this issue wasn't answered in this thread: the fix is to set homestead to the latest stable version instead of master:
```
composer require laravel/homestead ^5.3.2 --dev
```

**Comment by namgivu** [comment]
@vincentmarle You are my savior - picking [lower release version](https://github.com/laravel/homestead/releases) for homestead works for me
https://github.com/laravel/framework/issues/19088#issuecomment-304554295

**Comment by emaalouf** [comment]
I Was able to reproduce the problem and found out the solution.
The problem still persists on the newest Laravel/Homestead package.

Here you go:
On a Mac: Open Finder and navigate to /Users/user/.composer/vendor/laravel/homestead/src/MakeCommand.php
I used sublime text on this step, open the MakeCommand.php in sublime, click on find and replace, type in default and click replace all, this will replace all the defaultname variables with name only.
Now type homestead in the terminal, it should work like a charm.
