### ISSUE TITLE
php artisan error

### ISSUE THREAD

**Issue by ezekel** [laravel/framework#19096]
when using command `php artisan`  . I get this error. I don't know how to fix this.

``
Catchable fatal error: Argument 1 passed to Illuminate\Config\Repository::__construct() must be of the type array, integer given integer given, called in /var/www/mysite/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php on line 32 and defined in /var/www/mysite/vendor/laravel/framework/src/Illuminate/Config/Repository.php on line 24``

**Comment by themsaid** [comment]
Looks like one of your keys is corrupted, please ask on the forums.

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by michaeltansy** [comment]
Hi i got the same error. how do you solve it?

**Comment by Dylan-DPC** [comment]
@michaeltansy please ask in the forums or slack channel

**Comment by childeYin** [comment]
del storage/bootstrap/[files], this resovle my problem

**Comment by bhavdip111** [comment]
Rename your **cache.php**** file. Located bootstrap/cache/.
After run **php artisan config:cache** command if still not working

**Comment by osbre** [comment]
I got similar:

```
In Repository.php line 24:
Argument 1 passed to Illuminate\Config\Repository::__construct() must be of the type array, null g  
  iven, called in /Users/ostap/Sites/site/vendor/larapack/hooks/src/Composer.php on line 84          
```

**_Fixed_** by removing syntax error in `composer.json`
