### ISSUE TITLE
How to avoid duplicate entry in database using insert in Laravel?

### ISSUE THREAD

**Issue by rizwanmcs** [laravel/framework#19100]
hi i have developed my project in Laravel 4.2 version and i have an array of record and i want to insert this data into database using built-in insert() function but i want to update those entries which are already inserted otherwise insert the record. Can anyone help me here is my sample code
`public static function followAllUsers($user_data) {
$responce = array();
$data = array();
foreach ($user_data['following_id'] as $key => $value) {
    $following = UserBussinessLogic::checkAndValidateUser($value);
    if ($following != true) {
        $responce = Utility::Responce('invalid_user', FALSE, $value);
        break;
    } else {
        if (FriendBussinessLogic::isAlreadyFollowed($user_data['id'], $value)) {
            continue;
        }
        $data[] = array('follower_id' => $user_data['id'], 'following_id' => $value, 'created_at' => date('Y-m-d H:i:s'));
        $followData['notifyAbleUsers'][] = $value;
    }
}
if ($following) {
    if (!empty($data)) {
        if (Friend::insert($data)) {
            $followData['created_at'] = date('Y-m-d H:i:s');
            $followData['follower_id'] = $user_data['id'];
            $responce = Utility::Responce('friend_followed', TRUE, $followData);
        } else {
            $responce = Utility::Responce('general_error', FALSE);
        }
    } else {
        $responce = Utility::Responce('already_followed', TRUE);
    }
}
return $responce;
}`

i want to do this in Laravel eloquent and without looping

Thank you

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only.
