### ISSUE TITLE
JQuery Error "Uncaught TypeError: a.indexOf is not a function"

### ISSUE THREAD

**Issue by mailnike** [laravel/framework#19107]
- Laravel Version: 5.4.*
- PHP Version: 7.*
- Database Driver & Version: mysql

### Description:
My webpage works perfectly when not using Laravel (blade templates). However, it generates Jquery error "Uncaught TypeError: a.indexOf is not a function" whenever I display it using Laravel 5.4. I tried all permutations and combinations but absolutely no success. Also, this is not JQuery version issue, as I already checked, tried CDN also. **This is definitely LARAVEL problem.**

This is a plain HTML and JS. No complex logic.

![image](https://cloud.githubusercontent.com/assets/22786232/25821698/c15fcc74-3453-11e7-9fcb-9e5350cc9a10.png)

### Steps To Reproduce:

You can check my page here https://www.pi.team . In the console window it will display error.

**Comment by ludo237** [comment]
How is this a problem related with the framework?

**Comment by mailnike** [comment]
because if I just copy the source code view-source:https://www.pi.team/ and create .html file in the public directory then it works perfectly without an error. There has to be something LARAVEL framework messing up here. Either blade is not loading files in sequence (??).

There was an existing issue for the jQuery error (not exactly similar) (https://github.com/laravel/framework/issues/17634) but I don't think it was officially resolved.

**Comment by ankurk91** [comment]
Are you using Laravel mix ? Then please report it [here ](https://github.com/JeffreyWay/laravel-mix/)
