### ISSUE TITLE
Laravel | Eloquent does not support where($field, 'IN', $valueArr)

### ISSUE THREAD

**Issue by roynes2012** [laravel/framework#19102]
- Laravel Version: 5.4, 5.3, 5.2
- PHP Version: 5.6
- Database Driver & Version:

### Description
`Laravel/Eloquent` does not support a simple db query using `where` `in`

### Steps to reproduce
`php artisan tinker`
`App\User::where('id', 'IN', [1,2])->toSql();`
and it results to
`select * from users where id = ? and users.deleted_at is null` 

Is there any PR fix for it in any versions?

**Comment by JayBizzle** [comment]
I presume you realise you can do this...

```php
App\User::whereIn('id', [1,2])->toSql();
```

**Comment by roynes2012** [comment]
@JayBizzle Yes that can, but... how about the plain old `where`? I mean since it can almost do `=` to the `regexp`.. why not include the `in`?

**Comment by Dylan-DPC** [comment]
This is not a bug. Open an issue in the laravel/internals repo

**Comment by roynes2012** [comment]
Should I close this one?

**Comment by Dylan-DPC** [comment]
yep
