### ISSUE TITLE
Laravel Log not writting any text on queue:work process

### ISSUE THREAD

**Issue by vafrcor** [laravel/framework#19116]
- Laravel Version: `5.4.15`
- PHP Version: `7.0.18-1~dotdeb+8.1`
- Database Driver & Version: `MariaDB 10.1.22`
- Queue Driver: `database` or `redis`

### Description:
Laravel Log service not writting any text if too many worker work at the same time.
After I restart the supervisor worker manually, Log service would wrote text as normally.
Any help about this issue? 
Thank you

### Steps To Reproduce:
- I using Laravel to process data using `queue:work`  (as `daemon`) 
- Using Supervisord with `10` workers
- APP_DEBUG: `true`
- APP_LOG: `daily`
- APP_LOG_LEVEL: `debug`
- directory permission (`/storage/logs`: `777`)
- directory owner (`/storage/logs`: `www-data:www-data`)

**Comment by themsaid** [comment]
Sorry but please ask on the forums.
