### ISSUE TITLE
Migration quoting default column when used with change()

### ISSUE THREAD

**Issue by VinceG** [laravel/framework#19111]
- Laravel Version: 5.4.21
- PHP Version: 7.0.8
- Database Driver & Version: MySQL 5.7

### Description:

Inside a migration this:

```
Schema::table('test', function ($table) {
    $table->datetime('test')->default(DB::raw("CURRENT_TIMESTAMP"));
});
```

will produce
`ALTER TABLE test ADD test datetime DEFAULT CURRENT_TIMESTAMP;`

While this:

```
Schema::table('test', function ($table) {
    $table->datetime('test')->default(DB::raw('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP')))->change();
});
```

will produce

`ALTER TABLE test CHANGE test test datetime DEFAULT 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP';`

This results in an error:

```
SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'test' (SQL: ALTER TABLE test CHANGE test test DATETIME DEFAULT 'CURRENT_TIMESTAMP ON UPD
  ATE CURRENT_TIMESTAMP')
```

**Comment by themsaid** [comment]
That's a mysql error not laravel specific, please ask on the forums.

**Comment by VinceG** [comment]
@themsaid maybe i didn't explain it right. the error is caused due to the default being quoted, that default value is being quoted when using in a combination with change().

You can easily reproduce this in a fresh install by creating a migration and having the following code in it:

```
Schema::table('test', function ($table) {
    $table->datetime('test')->default(DB::raw('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP')))->change();
});
```

This is not a mysql error, but rather a laravel (or maybe docrine specific) since that default value is being quoted through the Laravel migration code.

**Comment by staudenmeir** [comment]
The SQL is generated by the `doctrine/dbal` package which doesn't know about Laravel's raw expressions.

For `CURRENT_TIMESTAMP`, you can use a string:

```php
$table->dateTime('test')->default('CURRENT_TIMESTAMP')->change();
```

For `CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`, you have to use raw SQL:

```php
DB::statement('ALTER TABLE `test` CHANGE `test` `test` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
```
