### ISSUE TITLE
[5.3]lumen use queue with redis

### ISSUE THREAD

**Issue by luzhuqun** [laravel/framework#19117]
- Laravel Version: 5.3.#
- PHP Version:7.0.1
- Database Driver & Version:

### Description:
I want use queue in my lumen 5.3 project.  

### Steps To Reproduce:

1. `composer require illuminate/Redis 5.3.*`
 the error is `{"message":"Type error: Argument 1 passed to Illuminate\\Queue\\Connectors\\RedisConnector::__construct() must be an instance of Illuminate\\Redis\\Database, instance of Redis given, called in \/home\/wwwroot\/KMS_api\/vendor\/illuminate\/queue\/QueueServiceProvider.php on line 217","status_code":500}`
2.  then I add `$app->register(Illuminate\Redis\Database::class);` to app.php
the error is `Type error: Argument 1 passed to Illuminate\Redis\Database::__construct() must be of the type array, object given, called in /home/wwwroot/KMS_api/vendor/laravel/lumen-framework/src/Application.php on line 164`
3. if I run `php artisan queue:table` or ` php artisan queue:failed-table`
the error is ` Command "queue:table" is not defined.`

What can I do？I am so desperate ah!

**Comment by themsaid** [comment]
Please use Lumen repo
