### ISSUE TITLE
Eloquent shows no property $post = Post::find(1); then $post->id;

### ISSUE THREAD

**Issue by sicaboy** [laravel/framework#19113]
- Laravel Version: 5.4.22
- PHP Version: 7.1.4
- Database Driver & Version: MySQL 14.14

### Description:
After upgrading from v5.4.19 to v5.4.22.
Eloquent shows no property after Post::find(1)
then $post->id will reproduce this error.
p.s.
dd($post) lists the right data set

**Comment by sicaboy** [comment]
after rolling back from v5.4.22 => v5.4.19 , everything back to normal

**Comment by themsaid** [comment]
what error?

**Comment by bbashy** [comment]
v5.4.22 => v5.4.19

That's 4 versions...

**Comment by sicaboy** [comment]
@themsaid  Property [id] does not exist on this collection instance

**Comment by sicaboy** [comment]
@bbashy but they are sharing the same documentation of v5.4. It shouldn't have different results.

**Comment by bbashy** [comment]
@sicaboy Yes, I meant narrowing down what version the issue happens in. You have .22 then downgrade to .19, so it happened in that version.

Have you checked changes from tag .18 -> .19?
Maybe also https://laraver.xyz when it's updated.

**Comment by jeffersonlicet** [comment]
Seems like Photo::find(1) is returning a boolean (true) in my case

**Comment by themsaid** [comment]
Make sure you're not passing multiple keys to `find()`, from the error your find returns a Collection so it looks like it was fed multiple ids.
