### ISSUE TITLE
[5.1 LTS] Strange session behavior

### ISSUE THREAD

**Issue by emkays2000** [laravel/framework#19129]
- Laravel Version: 5.1.46
- PHP Version: 5.5.9
- Database Driver & Version: NA

I am setting few session variables in my search controller as below:
```php
        // Add the search form values to session too
        session()->put('search-keyword', $keyword);
        session()->put('search-geolocation', $geoLocation);
```
Later,
```php
        return view('search.index', compact('profiles'));
```
In my search blade template, have this line:
```.blade.php
        <div style="background-image:url( '{{ $profile['_source']['picture'] }}' )"></div>
```
I am using 'file' session driver and the above works very well until `$profile['_source']['picture']` is null. When it is null, for some reason session variable `search-geolocation` is never set! As checked in the session file at storage/framework/sessions: ...."search-geolocation";N;s:9....

If I change the `<div>` above to `<img>`, everything again works beautifully, regardless of whether `$profile['_source']['picture']` is null or not null:
```.blade.php
        <img src="{{ $profile['_source']['picture'] }}" alt="">
```
This same problem never happens with the session variable `search-keyword`, whether `$profile['_source']['picture']` is null or not null; `search-keyword` appears as it should in the session file.

Right after setting the session in the controller, I get correct value when I echo:
```php
        echo session()->get('search-geolocation');
```
Also, this problem goes away when I debug the code (XDebug) and all the values are stored correctly in the session file as expected. So, debug is not of much help.

I have already worked around this problem but I am not confident about session anymore. Therefore, want to understand what's going on here. Have tried changing the session driver without any difference.

**Comment by sisve** [comment]
I have no clue what you're saying. Is the <img> important to reproduce the problem? Do you have to send data to the view? Are you chanting dark magic while doing this?

Can you write a small and concise way to reproduce this issue, without any other code present?

**Comment by bbashy** [comment]
So `search-geolocation` in the session gets removed if a variable is `null`?

Have you tried using a different name for the session? Have you tried switching them?

**Comment by emkays2000** [comment]
sisve, indeed it is strange because I find no connection in php code and html syntax! I haven't written a test case yet to reproduce this issue, will try and get to that later in my day. This problem is currently happening in my product's codebase.

bbashy, you are right with your interpretation. The problem remained as it is with different variable names and switching. What I realize is that for some reason a resultant output like `<div style="background-image:url(  )"></div>` is tripping something (it shouldn't, but looks like it is), because the following works - `<div style="background-image:url( {{ empty($profile['_source']['picture']) ? 'Test' : $profile['_source']['picture'] }} )"></div>` (which in the end results into `<div style="background-image:url( Test )"></div>` for the null values).

I read somewhere that helpers like dd interrupts the session storage. Could it be something similar happening when the blade is being compiled? I don't see any errors though in the logs or otherwise, and rightly so (perhaps that's why I am finding this issue strange).

Let me first try and get some reproducible code in place here. Many Thanks.

**Comment by astierler** [comment]
@emkays2000  I'll point out that you use `compact('profiles')` but then later reference `$profile` instead of `$profiles` .. was this a typo in the ticket, or in your code? (could explain your issue)

**Comment by emkays2000** [comment]
@astierler you are right, the blade code is inside foreach of $profiles -> $profile but thanks; still stretched with multiple things but yes, will try and put some reproducible code here soon.

**Comment by themsaid** [comment]
Please ping me when you include more details about the issue with steps to reproduce. Closing for now.
