### ISSUE TITLE
Laravel Eloquent Join problem with same column names

### ISSUE THREAD

**Issue by hosnayensiddiquee** [laravel/framework#19125]
- Laravel Version: 5.3.31
- PHP Version: 7.0.8
- Database Driver & Version: MySQL 5.7.18

### Description: 
Eloquent overwrites left table column name with right hand side column while joining unless explicitly writing column names inside select(). 

### Steps To Reproduce:

I have 2 tables ('users' and 'role_user') with same column ('created_at', 'updated_at') in both tables. When I am doing an Eloquent Join like --

Query -- 

User::join('role_user', 'role_user.user_id', '=', 'users.id')
                ->where('role_user.role_id', 4)
                ->get();

Output -- 

App\Models\User {#2098
  #table: "users"
  #guarded: []
  #primaryKey: "id"
  #revisionCreationsEnabled: true
  #dates: array:3 [
    0 => "xxx"
    1 => "xxx"
  ]
  #encryptable: array:3 [
    0 => "xxx"
    1 => "xxx"
  ]
  #hidden: array:2 [
    0 => "password"
    1 => "remember_token"
  ]
  #fillable: array:43 [
    0 => "xxx"
    1 => "created_at"
    2 => "updated_at"
  ]
  #connection: null
  #keyType: "int"
  #perPage: 15
  +incrementing: true
  +timestamps: true
  #attributes: array:5 [
    "id" => 1
    "created_at" => (wrong value) // overwritten by 2nd table column value
    "updated_at" => (wrong value) // overwritten by 2nd table column value
    "role_id" => 4
    "user_id" => 1
  ]
  #original: array:5 [
    "id" => 1
     "created_at" => (wrong value) // overwritten by 2nd table column value
    "updated_at" => (wrong value) // overwritten by 2nd table column value
    "role_id" => 4
    "user_id" => 1
  ]
  #relations: []
  #visible: []
  #appends: []
  #dateFormat: null
  #casts: []
  #touches: []
  #observables: []
  #with: []
  +exists: true
  +wasRecentlyCreated: false
  #rememberTokenName: "remember_token"
  #forceDeleting: false
  -originalData: []
  -updatedData: []
  -updating: false
  -dontKeep: []
  -doKeep: []
  #dirtyData: []
}

Output from DB::getQueryLog() -- 

select * from `users` left join `role_user` on `role_user`.`user_id` = `users`.`id` where `role_user`.`role_id` = 4 and `users`.`deleted_at` is null 

which is ok. 

But If I execute the above query with explicitly writing columns in select() then I am getting the correct output. 

User::join('role_user', 'role_user.user_id', '=', 'users.id')
                ->where('role_user.role_id', 4)
                ->select('users.created_at as userCreatedAt', 'users.updated_at as userUpdatedAt', 
                               'role_user.created_at as ruCreatedAt', 'role_user.updated_at as ruUpdatedAt')
                ->get();

**Comment by thihakyaw** [comment]
Oh I just solved this issue by doing 
`select(DB::raw('table1.created_at as some_column_name),'table1.other_column', 'table2.another_column')` (I tested created_at column name but it doesn't work)
this resolve the issue I faced on Laravel 8 though.
