### ISSUE TITLE
Validation issue

### ISSUE THREAD

**Issue by alexbowers** [laravel/framework#19136]
- Laravel Version: 5.4
- PHP Version: 7.1

### Description:
On the documentation page: https://laravel.com/docs/5.4/validation "Implicit Extensions" section, the code as displayed does not run.

### Steps To Reproduce:

```php
Validator::make(['name' => null], ['name' => 'unique'])->passes();
```

Should return `true`, but it instead throws an error: 

```
InvalidArgumentException with message 'Validation rule unique requires at least 1 parameters.'
```

**Comment by alexbowers** [comment]
@themsaid This stems on from a discussion on the `#internals` channel.

In Lumen 5.2, a rule such as `['id' => 'integer|positive']` would be fine being passed `null`. In Laravel 5.4, it no longer passes the validation.

The conclusion there was that this change was made intentionally, but my understanding of Implicit Extensions, would be that some types of rules allow nullable implicitly.

Can I get some clarification on how this is supposed to work, and which rules are implicitly allowed?

**Comment by themsaid** [comment]
The rules run if:

- Field is present
- Field is `null` and doesn't have a `nullable` modifier
- Rule is implicit

So the example in the docs is wrong and needs to be updated, the Validator only skips empty strings `` but `null` is considered.

**Comment by alexbowers** [comment]
Okay, great. If its intentional, and just a broken doc example, i'm happy for this to close.
