### ISSUE TITLE
why function `e` turns off the `double_encode` parameter of `htmlspecialchars`

### ISSUE THREAD

**Issue by leo108** [laravel/framework#19132]
https://github.com/laravel/framework/blob/5.4/src/Illuminate/Support/helpers.php#L533

the original string is 

```
<span style="font-family: &quot;Microsoft YaHei&quot;;">11111</span>
```

after `e($str)`

```
&lt;span style=&quot;font-family: &quot;Microsoft YaHei&quot;;&quot;&gt;11111&lt;/span&gt;
```

and then decode, it becomes

```
<span style="font-family: "Microsoft YaHei";">11111</span>
```

the quote is wrong after decode

**Comment by devcircus** [comment]
Probably best to just use the htmlspecialchars function in your case. I think the 'e' helper has had the same functionality since the 4.0.0 beta.
Or
A pull request adding an optional ```$double_encode``` parameter which defaults to false, may be a reasonable way to solve?


```
    function e($value, $double_encode = false)
    {
        if ($value instanceof Htmlable) {
            return $value->toHtml();
        }
        return htmlspecialchars($value, ENT_QUOTES, 'UTF-8', $double_encode);
    }
```

**Comment by ntzm** [comment]
@devcircus I disagree with adding boolean flags onto methods, could get messy very quickly

**Comment by devcircus** [comment]
Definitely could and is usually avoided, which is why I posed it as a question. Doesn't seem reasonable to change the behavior of a helper that's been around for over 4 years nor does it seem reasonable to add an additional helper in which the only difference is a boolean flag. So probably best to just use htmlspecialchars in this case.

**Comment by leo108** [comment]
@devcircus it doesn't make sense because we cannot pass `false` to the second parameter to `e` when we using braces in blade engine to render strings.

It's a 4-year-old code, but we can make changes to it when it causes problems.

**Comment by wajrou** [comment]
I got same problem with `<textarea>{{ $html }}</textarea>` after form saving & re-rendering.

Solved with `<textarea>{!! htmlspecialchars($html, ENT_QUOTES, 'UTF-8') !!}</textarea>` (with htmlspecialchars() default behaviour `double_encoded = true`).

I think there should be double_encoded param (shorter usage: `{!! e($html, true) !!}`), another escaping helper (eg: `{!! ee($html) !!}`) or other way for that in Blade Templates too.
