### ISSUE TITLE
Question regarding mix() helper

### ISSUE THREAD

**Issue by ruchern** [laravel/framework#19133]
- Laravel Version: 5.4.22
- PHP Version: 7.1

### Description:
`mix()` helper currently sets the url to the root directory rather than the full path as seen in `asset()`, `url()`. For projects that are deployed in subdirectories, this results in broken links.

May I know if there is a special reason for this?

In addition to that, is `url(mix())` recommended as a good practice to set the full path should the project be deployed in subdirectories?

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by ruchern** [comment]
@Dylan-DPC If you get the nature of my question, this is intended here. This is not a personal question. In fact, as per you stated, this could potentially be a bug.

Just look into `asset()` and `url()` and the difference in `mix()`. There is clearly full paths for `asset()` and `url()` but not in `mix()`.

**Comment by Dylan-DPC** [comment]
maybe then you should write your title in a better way. Anyway this isn't a bug but a proposal and can be made in laravel/internals repo :)

**Comment by ruchern** [comment]
>can be made in laravel/internals repo :)

How do I go about doing that. Sorry I am not sure where to propose such stuff other than an issue in Github which I know is actually kind of wrong place to do so.

**Comment by brunogaspar** [comment]
Just create an issue as a proposal on the [Laravel Internal repository](https://github.com/laravel/internals).

By the way, [this issue/proposal](https://github.com/laravel/internals/issues/392) is **somewhat** related to this, maybe it can be discussed there.

**Comment by ruchern** [comment]
Created a proposal request for this issue in https://github.com/laravel/internals/issues/581
