### ISSUE TITLE
assertSessionHasErrors doesn't work with named MessageBag (only with "default")

### ISSUE THREAD

**Issue by pl78** [laravel/framework#19134]
- Laravel Version: 5.4.21
- PHP Version: 7.1.1

### Description:
When doing test using `assertSessionHasErrors` method the test will fail if you validate the request using MessageBag with your own name (not "default") even thought the validation rules are set and validation works in browser.  

### Steps To Reproduce:
In my controller in `store` method I have:
```
$this->validateWithBag('answer', request(), [
    'body' => 'required'
]);
```
When I do assert in my test file like this:

`$response->assertSessionHasErrors('body');`

it fails with message "Session missing error: body". 

It pass when in controller I change to:
```
$this->validate(request(), [
    'body' => 'required'
]);
```
I am using named MessageBag as I have two forms on one page with textarea field (both called "body").

**Comment by pl78** [comment]
As for now I've solved this issue with the below solution but propably there is a better way.

In `Illuminate\Foundation\Testing\TestResponse.php` I changed the line 544 (in `assertSessionHasErrors` method) from:

`PHPUnit::assertTrue($errors->has($value), "Session missing error: $value");`

to:

`PHPUnit::assertTrue(collect($errors->getBags())->first()->has($value), "Session missing error: $value");`

**Comment by themsaid** [comment]
Added this as a feature in a PR for 5.5: https://github.com/laravel/framework/pull/19172
