### ISSUE TITLE
Access user in AppServiceProvider?

### ISSUE THREAD

**Issue by user6841322** [laravel/framework#19142]
- Laravel Version: 5.3

I need to be able to pass data to all views when the user is logged in.

Here is what my `AppServiceProvider` currently looks like:

    class AppServiceProvider extends ServiceProvider
    {
        public function boot()
        {
            if (Auth::check())
            {
                View::share('key', 'value');
            }
        }
    }

However, the data is never passed to the view because I can't use `Auth` (for some reason) in `AppServiceProvider` so the if statement condition is never met.

Following a [previous solution][1] I found, I tried doing this:

    class AppServiceProvider extends ServiceProvider
    {
        public function boot()
        {
            View::composer('*', function ($view)
            {
                if (Auth::check())
                {
                    View::share('key', 'value');
                }
            }
        }
    }

This worked, but the problem is that the closure is called whenever a view is rendered. For example, if my blade template includes 3 other blade templates (which it does), then the closure above will be called 4 times. [Explained further here][2].

So how can I access the user correctly in `AppServiceProvider`?

  [1]: http://stackoverflow.com/a/37373424/7971549
  [2]: https://laracasts.com/discuss/channels/laravel/using-auth-in-service-provider-to-get-user-object/replies/79555

**Comment by browner12** [comment]
Thanks for your interest in Laravel.

please ask questions like this on a forum ([StackOverflow](https://stackoverflow.com), or [Laracasts](https://laracasts.com)).

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by androschukandriy** [comment]
@user6841322,

AuthServiceProvider is booting after AppServiceProvider. An authorized user will be available after booting the AuthServiceProvider.
