### ISSUE TITLE
Illuminate\Http\Request only() - wildcard gives unexpected result

### ISSUE THREAD

**Issue by scrwdnet** [laravel/framework#19147]
- Laravel Version: 5.4.*
- PHP Version: 7.1
- Database Driver & Version: 

### Description:
The `only` method on a request doesn't play well when trying to get multidimensional post data using the `*` wildcard accessor.

e.g `$request->only('data.*.id');`

I'd expect the above to return something like this:
```
[
    "data" => [
        [
            "id" => 1
        ],
        [
            "id" => 2
        ],
    ]
]
```

What I I'd actually get is this:
```
[
    "data" => [
        "*" => [
            "id" => [1, 2]
        ]
    ]
]
```

As a side note trying the same thing on a Illuminate\Support\Collection yields an empty collection.

**Comment by Dylan-DPC** [comment]
This doesn't seem to be a bug. I would prefer the expected result as it is easier to work with. If you want a change you can make a proposal in the internals repo
