### ISSUE TITLE
Breaking change in version 5.4.19 --- Column 'id' in where clause is ambiguous

### ISSUE THREAD

**Issue by zbiller** [laravel/framework#19141]
- Laravel Version: 5.4.19
- PHP Version: 7.0
- Database Driver & Version: MySQL 5.6

Hi guys,

When updating the Laravel framework to the latest 5.4.x (which is now 5.4.22) version, I'm getting the following error.

> Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous (SQL: select `users`.*, `persons`.`first_name` as `first_name`, `persons`.`last_name` as `last_name`, `persons`.`email` as `email`, `persons`.`phone` as `phone` from `users` inner join `persons` on `users`.`id` = `persons`.`user_id` where `id` = 3 limit 1)

Now, I know what the error means, but after some digging I've discovered that this error will start appearing after and including Laravel's version 5.4.19, which leads me to think there is something fishy with that update.

One thing to note, though, is that this error triggers only once in my entire application.
It triggers on a Global Scope which is assigned on the User model inside the boot method (like in the docs).

My use case is the following:
- I'm using the same column for both front and admin users
- Each user has it's own "person" and that person belongs to user (one to one).
- To avoid using eager loading of persons for users, I chose to create a global scope and attaching it to the user model. The global scope only contains this code inside the "apply" method:

`$builder->join('persons', 'users.id', '=', 'persons.user_id')->addSelect([
            'persons.first_name as first_name',
            'persons.last_name as last_name',
            'persons.email as email',
            'persons.phone as phone',
        ]);`

As you can see, no complex logic here.

After some debugging I've noticed that the error in discussion is triggered from inside the **Illuminate\Session\Middleware\AuthenticateSession** file, line 38: **$request->user()**

Also, please note that I'm not manually adding that where clause **where `id` = 3 limit 1** which means that most probably it's composed by the Laravel's **getUserResolver** method.

Hope I was clear enough. If not, please let me know.

Any thoughts one this?

Thank you!

**Comment by morloderex** [comment]
I think you have been caught by this https://github.com/laravel/framework/commit/a54cfa11fa93466f21979e7c585eedf7ee243ae4, But I'm not sure.

**Comment by zbiller** [comment]
@morloderex You're right.
After overwriting the Authenticatable trait's method called getAuthIdentifierName, to include the table name also, it works.

That said, I would say this is actually not an issue.

Thank you for your help!
