### ISSUE TITLE
Wrong redirect to www-root instead of laravel root when removing trailing slashes

### ISSUE THREAD

**Issue by nolimitdev** [laravel/framework#19153]
- Laravel Version: 5.x
- PHP Version: any
- Database Driver & Version: any

### Description:
When Laravel app is located in subdirectory and is served with Apache (public/.htaccess is used) an you request URL with trailing slash(es) you will be incorrectly redirected to www-root instead of laravel root.

### Steps To Reproduce:
Install laravel to subdirectory of your www-root (e.g /var/www-root/laravel). Request URL with trailing slash e.g. http://localhost/laravel/public/about/ and after removing trailing slash you will be incorrectly redirected to www-root http://localhost/about instead of laravel root http://localhost/laravel/public/about

It can be fixed by this change in public/.htaccess
    
    -    RewriteRule ^(.*)/$ /$1 [L,R=301]
    +    RewriteCond %{REQUEST_URI} (.+?)/+$
    +    RewriteRule ^ %1 [L,R=301]

**Comment by Dylan-DPC** [comment]
First of all things you shouldn't be using public in your routes (url). It should be configured in your vhost

**Comment by nolimitdev** [comment]
Of course, it was just example. The same problem is in vhost situation.... example.com/laravel/about/ is redirected to wrong URL example.com/about (omited "laravel" dir)

**Comment by bbashy** [comment]
And this is framework repo not laravel. No .htaccess here.
