### ISSUE TITLE
Laravel/Configure cronjobs

### ISSUE THREAD

**Issue by devikafr** [laravel/framework#19151]
- Laravel Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:I am trying to setup task every hour.
I executed command : vagrant@vagrant-ubuntu-trusty-64:/var/www/html/shop$ 30 * * * * php /var/www/html/shop/artisan aimeos:jobs "customer/email/watch order/cleanup/unfinished order/service/async order/service/payment"

I got this result: 30: command not found

Please help. Thanks

**Comment by emielmolenaar** [comment]
You are pasting the cron schedule in your shell, and so the command "30" does not exist. Setup "30 * * * * php /var/www/html/shop/artisan aimeos:jobs customer/email/watch order/cleanup/unfinished" in your cronjob. Learn more about that [here](https://help.ubuntu.com/community/CronHowto).

**Comment by devikafr** [comment]
Thanks a lot, much appriciated.
