### ISSUE TITLE
Prevent Laravel API from processing the token if it comes in the URL as querystring

### ISSUE THREAD

**Issue by nisevi** [laravel/framework#19169]
- Laravel Version: 5.3
- PHP Version: 7.1
- Database Driver & Version: pgsql

### Description:
Before all, sorry if this is not the place for asking but I'm trying to prevent laravel from processing the token if it comes in the url as querystring and I'm not being able to do it.

This is my `config/cors.php` file:
```
<?php

return [
   'defaults' => [
       'supportsCredentials' => false,
       'allowedOrigins' => [],
       'allowedHeaders' => [],
       'allowedMethods' => [],
       'exposedHeaders' => [],
       'maxAge' => 0,
       'hosts' => [],
   ],

   'paths' => [
       'v1/*' => [
           'allowedOrigins' => ['*'],
           'allowedHeaders' => [
               'Origin',
               'Content-Type',
               'Accept',
               'Authorization',
               'X-Request-With'
           ],
           'allowedMethods' => ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'],
           'exposedHeaders' => ['Authorization'],
           'maxAge' => 3600,
       ],
   ],
];
```

And here you what I want to avoid:
![url](https://cloud.githubusercontent.com/assets/3024789/25996988/4b635116-371a-11e7-9705-1a8cbce8d092.png)

And this is the only behavior that I want:
![header](https://cloud.githubusercontent.com/assets/3024789/25997006/5bdc272a-371a-11e7-9902-d3c323dcc7c7.png)

Sorry again if this is not the place but I'm trying to figure this out since last week and I think I'm not even close. Thank you for your time!

**Comment by themsaid** [comment]
You can use the forums to ask questions, I'm sure someone will be able to help you there: https://laracasts.com/discuss

**Comment by nisevi** [comment]
Hi @themsaid, I already did last week, here https://laracasts.com/discuss/channels/laravel/prevent-laravel-api-from-processing-the-token-if-it-comes-in-the-url-as-querystring and here http://stackoverflow.com/questions/43764919/prevent-laravel-api-from-processing-the-token-if-it-comes-in-the-url-as-querystr , if you know the answer you will get my bounty in stackoverflow :+1:

**Comment by Dylan-DPC** [comment]
you can join is in the slack channel and throw your question there so we can discuss it and find a solution for you if forums don't work out

**Comment by nisevi** [comment]
@Dylan-DPC that would be nice! could you invite me? or tell me the slack team name, please.

**Comment by nisevi** [comment]
@Dylan-DPC I'm in :+1:
