### ISSUE TITLE
Eloquent find on collection with relationship query

### ISSUE THREAD

**Issue by lomby** [laravel/framework#19171]
- Laravel Version: 5.4.23
- PHP Version: 7.1
- Database Driver & Version:

### Description:

Since upgrading to Laravel 5.4.23 from 5.4.21 running  a query with Eloquent find on a collection and chaining a relationship is now throwing a method not found error.

### Steps To Reproduce:

`$imageCollection = Service::find($serviceCollection)->images()->pluck('id');`

resulting in:

_BadMethodCallException in Macroable.php line 74:
Method images does not exist._

running the same with a single id still works with no issues:

`$imageCollection = Service::find(1)->images()->pluck('id');`

**Comment by themsaid** [comment]
`Service::find($serviceCollection)` returns a Eloquent Collection, so yes it makes since that you see this error.
