### ISSUE TITLE
Collection chunk method doesn't work as expected

### ISSUE THREAD

**Issue by hafezdivandari** [laravel/framework#19182]
- Laravel Version: 5.4.22
- PHP Version: 7.0.15
- Database Driver & Version: MySQL 5.7.18

### Description:
Using chunk method on arrays without keys makes the result have unexpected keys.

### Steps To Reproduce:
Running this code:
```
Public function test()
    {
        $test = [1,2,3,4];
        return response()->json(collect($test)->chunk(2)->all());
    }
```
will output:
```
[[1,2],{"2":3,"3":4}]
```
But I expect to get this:
```
[[1,2],[3,4]]
```

**Comment by themsaid** [comment]
It's not an issue with the chunk method, it's that when you convert an array to JSON if the array is not keyed in a correct sequence starting from 0 PHP will convert it to a JSON object instead.

**Comment by hafezdivandari** [comment]
@themsaid The array in the example doesn't have key (So it'is keyed in a correct sequence automatically) 

```
return response()->json(array_chunk([1,2,3,4], 2, true)); //outputs: [[1,2],{"2":3,"3":4}]
```
but
```
return response()->json(array_chunk([1,2,3,4], 2)); //outputs: [[1,2],[3,4]]
```
