### ISSUE TITLE
Cannot add Unique Key to TEXT/BLOB column

### ISSUE THREAD

**Issue by deleugpn** [laravel/framework#19199]
- Laravel Version: 5.4.23
- PHP Version: 7.0.16
- Database Driver & Version: MySQL 5.7.15

### Description:
When adding a `text` or `binary` column (which gets converted to BLOB), we are unable to make it a `unique` column. The MySQL Grammar will translate it into:

```
alter table `users` add unique `users_foo_unique`(`foo`)
```

[And MySQL will fail because the size of the index have not been specified.](http://stackoverflow.com/a/1827099/1014588)

The appropriate Query would be something like: 

```
alter table `users` add unique `users_foo_unique`(`foo(64)`)
```

Unfortunately, [MySQL Grammer](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Schema/Grammars/MySqlGrammar.php#L211) have no easy way to receive data about what size it should use. Also, `columnize` wouldn't be able to correctly compile the array of columns and their individual size. 

### Error Message (indexing)

```
[Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'sensitive_string' used in key specification without a key length
```

### Steps To Reproduce:

Run the following Migration

```
        Schema::create('test_table', function (Blueprint $table) {
            $table->increments('id');
            $table->string('normal_string', 255);
            $table->text('sensitive_string')->unique();
        });
```

### Possible Failing Test

```
    public function testAddingUniqueBinary()
    {
        $blueprint = new Blueprint('users');
        $blueprint->binary('foo')->unique();
        $statements = $blueprint->toSql($this->getConnection(), $this->getGrammar());
        $size = 64; // Ideally, the developer would provide this

        $this->assertEquals(2, count($statements));
        $this->assertEquals("alter table `users` add unique `users_foo_unique`(`foo`({$size}))", $statements[1]);
    }
```

**Comment by ThunderBirdsX3** [comment]
In my remember. You can't make `text` to `unique`. Can it be `text`.

**Comment by deleugpn** [comment]
@ThunderBirdsX3 the problem with `string` is that I cannot make it case-sensitive.

**Comment by sisve** [comment]
@themsaid Could you perhaps add a reason why was this closed? This is fully supported in mysql.

> For string columns, indexes can be created that use only the leading part of column values, using col_name(length) syntax to specify an index prefix length:
> * Prefixes can be specified for CHAR, VARCHAR, BINARY, and VARBINARY column indexes.
> * Prefixes must be specified for BLOB and TEXT column indexes.

... and ...

> If you specify a prefix value for a column in a UNIQUE index, the column values must be unique within the prefix.

Source: https://dev.mysql.com/doc/refman/5.7/en/create-index.html

**Comment by themsaid** [comment]
Feel free to open a PR, It does look like it needs special handling to create such syntax which is currently not supported, so a PR with code we can discuss would be great, if not I believe this should be submitted to the internals repo as a feature request.

**Comment by sisve** [comment]
@deleugpn Are you using the utf8mb4_bin collation? It should be _extremely_ case sensitive. I do not see any case-sensitive utf*-collations except the binary ones.

**Comment by bloggervista** [comment]
@sisve yes if it is supported by leading driver like mysql i guess laravel also support it :)

**Comment by wojcikcp** [comment]
So what is the solution for that? I still want to have `text` and `unique` column. Does Laravel support it?

**Comment by bloggervista** [comment]
@wojcikcp  as of now laravel don't support it and i guess laravel 5.6 will also not support it as it is really minor issue. If possible use string and use unique column.

**Comment by wojcikcp** [comment]
Unfortunately `string` is too small For me. I will have then use raw query to create table I suppose

**Comment by npapratovic** [comment]
So.. 

$table->string  is same as VARCHAR and can have lenght between 1 and 65536 characters
$table->text is same as TEXT and has fixed lenght of 65536 characters

Also, you can set $table->string as unique and with $table->text you can't set as unique.  

If you are looking from perspective to optimize data size, it would be better to use string(VARCHAR) instead of text(TEXT)
