### ISSUE TITLE
[5.4] Strange code of instance in container

### ISSUE THREAD

**Issue by LeoYang90** [laravel/framework#19194]
- Laravel Version: 5.4.23
- PHP Version:7.1
- Database Driver & Version:NA

### Description:
I am learning the source code of container, there is something that  confused me :
file: /illuminate/Container/Container.php-line356
```php
public function instance($abstract, $instance)
{
    $this->removeAbstractAlias($abstract);

    unset($this->aliases[$abstract]);        
    $this->instances[$abstract] = $instance;//this is problem

    if ($this->bound($abstract)) {
        $this->rebound($abstract);
    }
}
```
file: /illuminate/Container/Container.php-line151
```php
public function bound($abstract)
{
    return isset($this->bindings[$abstract]) ||
           isset($this->instances[$abstract]) || ////this is problem
           $this->isAlias($abstract);
}
```
In instance() function, the code set the array of instances[$abstract]. And next, the code check to determine if type has been bound before,.However in bound(),  this->instances[$abstract]) always be true because it is set just in last line.
so the code:
```php
 if ($this->bound($abstract))
```
is true forever.
Am I wrong with somewhere?

**Comment by Dylan-DPC** [comment]
This is not a bug. Open an issue in the laravel/internals repo

**Comment by laurencei** [comment]
@Dylan-DPC  - this is a bug in the container - it incorrectly always fires `rebound()`
