### ISSUE TITLE
Bad request on chrome when accessing through Virtual Host

### ISSUE THREAD

**Issue by akash-dangal** [laravel/framework#19198]
- Laravel Version: 5.4.1
- PHP Version:7.0.0
- Database Driver & Version: Mysql

### Description:
I have laravel project for which I created virtual host. Everything working fine with FireFox, but the virtual host didn't work with Chrome on posting data.. It always return 400[bad request]. Same project working fine when directly accessing i.e localhost/projectname/public  in chrome too.. however the same project with app.projectname.local is not working. What can be the issue.. I have struggled a lot to get it solved but nothing works.. Urgent help with be heartily appreciated.

I have attached Compsor.docx for referance Composer

[Compsor.docx](https://github.com/laravel/framework/files/999493/Compsor.docx)

**Comment by hardikdangar** [comment]
Did you try to remove cookies and test again?  Have seen this in one of the projects. Also what happens when you open app.projectname.local in chrome? does it work and only causes issue when you submit form ? if its case can you disable your chrome extensions and test again?

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by akash-dangal** [comment]
The issue was actually due to ` \Neomerx\CorsIlluminate\CorsMiddleware ` which block post request from chrome and make it bad request[400] . So I thought of disabling the Cors for normal request and enabling it for the request from api. Thanks guys for your concerns
