### ISSUE TITLE
Pusher chat: Couldn't get auth info from your webapp : 404

### ISSUE THREAD

**Issue by orijmm** [laravel/framework#19204]
- Laravel Version: 5.3
- PHP Version: 7
- Database Driver & Version: mysql 5.7.13
### Description:
I am doing a chat with pusher in laravel 5.3 and when I upload the page, I get this error in f12 debug console: 

Couldn't get auth info from your webapp : 404

**Comment by laurencei** [comment]
@orijmm - please ask on Slack (https://larachat.co/) or the forums (https://laravel.io/forum or https://laracasts.com/discuss)

This is not a support area.

Thanks.

**Comment by orijmm** [comment]
Thanks!
