### ISSUE TITLE
[5.4] Custom upload validation rule does not run

### ISSUE THREAD

**Issue by imbrish** [laravel/framework#19208]
- Laravel Version: 5.4.19
- PHP Version: 5.6.4
- Database Driver & Version: Mysql 5.6.17

### Description:

Back on Laravel 5.2 I've created custom upload validator `upload:max-size`, that checks if file uploaded correctly, and if not and error is either `UPLOAD_ERR_INI_SIZE` or `UPLOAD_ERR_FORM_SIZE` reports to the user not only that upload failed, but also that maximum handled filesize is:

```php
ini_get_bytes('upload_max_filesize') ?: ini_get_bytes('post_max_size') ?: PHP_INT_MAX
```

However due to change below introduced in Laravel 5.3:

```php
if ($value instanceof UploadedFile && ! $value->isValid() &&
     $this->hasRule($attribute, array_merge($this->fileRules, $this->implicitRules))
) {
     return $this->addFailure($attribute, 'uploaded', []);
}
```
My validation rule is never executed despite being implicit and user gets only default, generic `validation.uploaded` message.

Here are the validation rules:

```php
'pictures' => 'required|array|min:1',
'pictures.*' => "required|upload:2048|mimes:jpeg,png,gif|dimensions:min_width=$width,min_height=$height",
```

Can I somehow ensure my custom upload validator gets executed? Or only way is to use two separated validators, one for `upload` and another for `mimes`, `dimensions` etc?

### Steps To Reproduce:

Try to validate uploaded file via custom rule, when any of `$fileRules` or `$implicitRules` is defined.

**Comment by themsaid** [comment]
If the uploaded file failed to upload laravel fails with an `uploaded` failure since 5.3, your rule won't run if this failure happened, so you're already safe from a failed file upload.

**Comment by imbrish** [comment]
@themsaid that's true, however when uploaded file exceeds `upload_max_filesize` user would be informed only that `The :attribute failed to upload.`, while my custom rule would give more feedback `The :attribute may not be greater than :max kilobytes.`.

Is there a way to disable this default functionality, or I have to live with workarounds?

**Comment by themsaid** [comment]
Well at least on 5.4 it's not possible to make changes since it'd be considered breaking

**Comment by TomKo1** [comment]
Somebody managed to come up with a solution?

**Comment by Gildo-Sargi-Neto** [comment]
> @themsaid that's true, however when uploaded file exceeds `upload_max_filesize` user would be informed only that `The :attribute failed to upload.`, while my custom rule would give more feedback `The :attribute may not be greater than :max kilobytes.`.
> 
> Is there a way to disable this default functionality, or I have to live with workarounds?

I lost a couple hours searching for this yesterday and it was kinda obvious, but i was not finding it, so there it is :)

At least in laravel 5.8(i dont know if this works in lower versions) there is a validation.php file with all default error messages located in resources/lang/{language} you can add the custom message there like below

'uploaded' => 'The :attribute may not be greater than :max kilobytes.',
