### ISSUE TITLE
GET request parameters space behavior

### ISSUE THREAD

**Issue by totomakers** [laravel/framework#19206]
- Laravel Version: v5.4.20
- PHP Version: x
- Database Driver & Version: x

### Description:
I have comment in `Kernel.php` the middleware `\App\Http\Middleware\TrimStrings::class`

GET `api/job/41AB010A/tasks?Job+Task+No_=1` 
Excepting `$request->all()` return `[ 'Job Task No_' => "1"]`

Currently return : 
`array:1 ["Job_Task_No_" => "1"]`

### Steps To Reproduce:

Just make a GET request with space in parameters

**Comment by decadence** [comment]
It's intended by PHP itself. It replaces dots and spaces by "_" in $_GET / $_POST arrays.

**Comment by totomakers** [comment]
Thanks :) for help i didn't know \o/
