### ISSUE TITLE
[Request] Sort & Filter eager load results

### ISSUE THREAD

**Issue by jwong1123** [laravel/framework#19214]
- Laravel Version: 5.4.21
- PHP Version: 5.6.29
- Database Driver & Version: Mysql 14.14

### Description:
We wanted to sort & filter entire entry basing on relationship values (fetched using eager load).
Current scenario, we have to convert it to join statements instead of using eager load to be able to sort & filter results. 
We have to implement sort & filter directly for eager load results.. 

Syntax suggestion: 
`Staff::with('user.roles')->orderBy('user.email', 'desc')->get();`

### Steps To Reproduce:
Code:
`Staff::with('user.roles')->get();`

Example:
if sorted by user.email_address, result should be by order of: _id: 6, 8, 7, 1_ (id refers to the outermost id key) basing from result below. 
`{
      "id": 1,
      "first_name": "testesttest22",
      "last_name": "tetetsetse22",
      "team_id": 1,
      "remarks": null,
      "updated_by": null,
      "user": {
        "id": 3,
        "username": "testStaff11",
        "email_address": "staff+10@gmail.com22",
        "name": "Staff User",
        "roles": []
      }
    },
    {
      "id": 6,
      "first_name": "testesttestqwe1112221",
      "last_name": "tetetsetse1111",
      "team_id": null,
      "remarks": null,
      "updated_by": null,
      "user": {
        "id": 6,
        "username": "testStaff101",
        "email_address": "d@w.a",
        "name": "FirstNameTest LastNameTest",
        "roles": [
          {
            "id": 3,
            "name": "sales",
            "display_name": "Sales"
          },
          {
            "id": 4,
            "name": "management",
            "display_name": "Management"
          },
          {
            "id": 5,
            "name": "logistic",
            "display_name": "Logistic"
          },
          {
            "id": 6,
            "name": "coach",
            "display_name": "Coach"
          }
        ]
      }
    },
    {
      "id": 7,
      "first_name": "FirstNameTest2311",
      "last_name": "LastNameTest2311",
      "team_id": null,
      "remarks": null,
      "updated_by": null,
      "user": {
        "id": 7,
        "username": "master123",
        "email_address": "masterStaff+4@gmail.com",
        "name": "FirstNameTest1 LastNameTest1",
        "roles": [
          {
            "id": 3,
            "name": "sales",
            "display_name": "Sales"
          },
          {
            "id": 5,
            "name": "logistic",
            "display_name": "Logistic"
          }
        ]
      }
    },
    {
      "id": 8,
      "first_name": "FirstNameTest",
      "last_name": "LastNameTest",
      "team_id": null,
      "remarks": null,
      "updated_by": null,
      "user": {
        "id": 8,
        "username": "masterStaff+3",
        "email_address": "masterStaff+3@gmail.com",
        "name": "FirstNameTest LastNameTest",
        "roles": [
          {
            "id": 3,
            "name": "sales",
            "display_name": "Sales"
          },
          {
            "id": 4,
            "name": "management",
            "display_name": "Management"
          },
          {
            "id": 5,
            "name": "logistic",
            "display_name": "Logistic"
          },
          {
            "id": 6,
            "name": "coach",
            "display_name": "Coach"
          }
        ]
      }
    }`

**Comment by lukepolo** [comment]
Why not just do : `User::has("staff")->orderBy('email')->get()`

**Comment by jwong1123** [comment]
@lukepolo we need the sort & filter column should be dynamic while maintaining output structure.

**Comment by themsaid** [comment]
Please ask on the forums, we keep this repo for bug reporting only :)
