### ISSUE TITLE
[5.4] Container:Alias and Context bug or feature?

### ISSUE THREAD

**Issue by LeoYang90** [laravel/framework#19225]
- Laravel Version: 5.4.23
- PHP Version: 7,1
- Database Driver & Version: NA

### Description:
Hi，
  Recently, I am learning the source code of container, there is something that I can not figure out whether it is a bug or a feature:
### Steps To Reproduce:
This is necessary class:
```php
class ConcreteClass
{
}

Interface ContextInterface
{
    public function test();
}

class ContextConcrete implements ContextInterface
{
    public function test()
    {
        echo 'ContextConcrete';
    }
}

class TestContext{
    public $t;

    function __construct(ContextInterface $t)
    {
        $this->t = $t;
    }
}
```
So here is my test code:
```php
public function testBindContext_bind_a()
{
    App::alias(ContextInterface::class,'a');
    App::bind('a', ConcreteClass::class);//bind to another uncorrelated class

    App::when(TestContext::class)->needs('a')->give(ContextConcrete::class);

    $obj_context = App::make(TestContext::class);
    $obj_context->t->test();
}
```
The result is  'ContextConcrete', so does it work well?
next:
```php
public function testBindContext_bind_c()
{
    App::alias('a','b');
    App::alias('b','c');
    App::alias(ContextInterface::class,'a');

    App::bind('c', ConcreteClass::class);//bind to another uncorrelated class
    App::when(TestContext::class)->needs('c')->give(ContextConcrete::class);

    $obj_context = App::make(TestContext::class);
    $obj_context->t->test();
}
```
It will throw a error "ContextInterface can not be initialized while building TestContext". so does it work well?
next:
```php
public function testBindContext_bind_back()
{
    App::alias('a','b');
    App::alias('b','c');
    App::alias(ContextInterface::class,'a');

    App::when(TestContext::class)->needs('c')->give(ContextConcrete::class);
    App::bind('c', ConcreteClass::class);//bind to another uncorrelated class

    $obj_context = App::make(TestContext::class);
    $obj_context->t->test();
}
```
the result is  'ContextConcrete'. So does it work well?

So the problem is:
- Before contextual binding, when bind() function called on alias of interface, should container allow user use this alias as interface in the contextual binding? In testBindContext_bind_a(), container allows; While in testBindContext_bind_c(), container does not allow. So what do we really need?
- In testBindContext_bind_back(), after contextual binding using alias of interface, bind() function is called on alias of interface, and the contextual binding continues to work. I think it is right, but I am not sure.

thanks!

**Comment by themsaid** [comment]
Can you please simplify the case? I don't understand what you're testing!

**Comment by LeoYang90** [comment]
Sorry, maybe my description is not clear enough, I will give a more simple case.
```php
class ConcreteClass
{
}

Interface ContextInterface
{
    public function test();
}

class ContextConcrete implements ContextInterface
{
    public function test()
    {
        echo 'ContextConcrete';
    }
}

class TestContext{
    public $t;

    function __construct(ContextInterface $t)
    {
        $this->t = $t;
    }
}
```
In generate, if we want to use contextual bind to class TestContext, we can write this:
```php
App::when(TestContext::class)->needs(ContextInterface::class)->give(ContextConcrete::class);
```
But if we want to use alias, we can also write:
```php
App::alias(ContextInterface::class,'alias');
App::when(TestContext::class)->needs('alias')->give(ContextConcrete::class);
```
So if alias bind to another concrete class:
```php
App::alias(ContextInterface::class,'alias');
App::bind('alias', ConcreteClass::class);

App::when(TestContext::class)->needs('alias')->give(ContextConcrete::class);

$obj_context = App::make(TestContext::class);
$obj_context->t->test();
```
The result is 'ContextConcrete'.
It can still work! According to my understanding, if ‘alias’ is bound to another class, it can not alias to or represent the class 'ContextInterface' anymore. However, in that case, 'alias' can still work in contextual binding in needs().
@themsaid

**Comment by LeoYang90** [comment]
If above case is a feature, the next case is interesting:
```php
public function testBindContext_bind_c()
{
    App::alias('a','b');
    App::alias('b','c');
    App::alias(ContextInterface::class,'a');

    App::bind('c', ConcreteClass::class);//bind to another uncorrelated class
    App::when(TestContext::class)->needs('c')->give(ConcreteContext::class);

    $obj_context = App::make(TestContext::class);
    $obj_context->t->test();
}
```
It will throw a exception 'ContextInterface can not be initialized while building TestContext'.  So recursive alias does not work on contextual binding. I think something is wrong with the situation.
@themsaid

**Comment by laurencei** [comment]
@LeoYang90 - there is an error your last example.

`App::when(TestContext::class)->needs('c')->give(ConcreteContext::class);` is wrong. It should be `App::when(TestContext::class)->needs('c')->give(ContextConcrete::class);`

Which when you run it gives the error

> Target [Tests\Tests\ContextInterface] is not instantiable while building [Tests\Tests\TestContext].

Which is probably correct? You are simultaneously telling the container to bind `C` to `ConcreteClass` AND to alias `C` to `B` to `A` to `ContextInterface`

It is conflicting.

What would you expect the outcome to be?

**Comment by LeoYang90** [comment]
@laurencei 
sorry, it is my mistake in writing.It should be ContextConcrete::class, but it wont work either.

**Comment by themsaid** [comment]
I'm sorry but this is not the right place for such questions, please use the forums, I'm sure people will help you there.

**Comment by LeoYang90** [comment]
@themsaid Could you tell me what is the address of forums?

**Comment by laurencei** [comment]
- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

**Comment by LeoYang90** [comment]
@laurencei thanks!

**Comment by LeoYang90** [comment]
I found a test similar to my example:
```php
    public function testContextualBindingWorksOnNewAliasedBindings()
    {
        $container = new Container;

        $container->when('Illuminate\Tests\Container\ContainerTestContextInjectOne')->needs('Illuminate\Tests\Container\IContainerContractStub')->give('Illuminate\Tests\Container\ContainerImplementationStubTwo');

        $container->bind('stub', ContainerImplementationStub::class);
        $container->alias('stub', 'Illuminate\Tests\Container\IContainerContractStub');

        $this->assertInstanceOf(
            'Illuminate\Tests\Container\ContainerImplementationStubTwo',
            $container->make('Illuminate\Tests\Container\ContainerTestContextInjectOne')->impl
        );
    }
```

**Comment by LeoYang90** [comment]
So my example can be:
```php
    public function testContextualBindingWorksOnNewAliasedBindings()
    {
        $container = new Container;

        $container->bind('stub', ContainerImplementationStub::class);
        $container->alias('stub', 'Illuminate\Tests\Container\IContainerContractStub');

        $container->when('Illuminate\Tests\Container\ContainerTestContextInjectOne')->needs('Illuminate\Tests\Container\IContainerContractStub')->give('Illuminate\Tests\Container\ContainerImplementationStubTwo');

        $this->assertInstanceOf(
            'Illuminate\Tests\Container\ContainerImplementationStubTwo',
            $container->make('Illuminate\Tests\Container\ContainerTestContextInjectOne')->impl
        );
    }
```
