### ISSUE TITLE
Laravel 5.4 Validation not always work. 

### ISSUE THREAD

**Issue by chelkaz** [laravel/framework#19229]
- Laravel Version: 5.4.23
- PHP Version: 7.1.4
- Database Driver & Version: 5.7.18

### Description:
Validation not always work. Example:
i have rules:
`'category' => 'required|exists:categories,code',
'title' => 'required|between:15,150',
'text' => 'required|between:30,5000',`
### Steps To Reproduce all route web middleware:

1. If **category** and **title** and **text** == null, my blade gets **$validator->errors()** true. **It's good!**

2. If **category** NULL, but **title** and **text** == йцукен (Cyrillic - RU lang), my blade gets **$validator->errors()** null. **It's it is not right!**
in blade `{{ var_dump($errors) `}}
`object(Illuminate\Support\ViewErrorBag)#233 (1) { ["bags":protected]=> array(0) { } }`

3. 2. If **category** NULL, but **title** and **text** == qwerty, my blade gets **$validator->errors()** true. **It's good!**

- But in the controller, all 3 attempts If check dd($validator->errors()) Show true. **It's good!**
### Why skip and not display in blade?
`@if(count($errors) > 0)
    <p id="errors" class="errors">
        @foreach ($errors->all() as $message)
            <span>{!! $message !!}</span>
        @endforeach
    </p>
@endif`

**Comment by bbashy** [comment]
What code are you using in your view?

**Comment by chelkaz** [comment]
Standard of documentation `@foreach ($errors->all() as $message) `

**Comment by bbashy** [comment]
@chelkaz Sorry, I saw you said "my blade gets $validator->errors() true" which confused me.

Just tested it and seems to work for me.

**Comment by themsaid** [comment]
Please ask on the forums.

**Comment by bbashy** [comment]
@themsaid What exactly is the 'forum'? https://laravel.com/forum 404

**Comment by themsaid** [comment]
There's https://laracasts.com/discuss for instance, the thing is we won't answer questions on this repo, we keep it for bug reporting only.

On the forums there's a larger group of community members who are willing to help, we try to make this repo only focused on actual framework bugs.
