### ISSUE TITLE
Markdown Images not working

### ISSUE THREAD

**Issue by pcfutures** [laravel/framework#19231]
Using Markdown Mailables, Images do not render at all, but other markdown works fine.

```markdown
![{{ $app_name }}]({{ asset('/assets/img/logo.png') }})
```
should compile to
```markdown
![laravel app](http://laravel.dev/assets/img/logo.png')
```
and then render as an image with the alt text 'laravel app'.
Instead, it just outputs the markdown string on its own:
```markdown
![laravel app](http://laravel.dev/assets/img/logo.png')
```

Note that I am using lumen with Mail packages added in on top, but that shouldn't be the problem as far as I can tell.

I had someone suggest that maybe the Markdown is rendered before blade/variable substitution, which kind of makes sense.

I've decided to just not use images until a fix is found.

**Comment by themsaid** [comment]
Image rendering is working as expected, make sure you're using the correct path to your image.

**Comment by pcfutures** [comment]
Yes, the path is right. This shouldn't be closed.

**Comment by pcfutures** [comment]
Even if the path was wrong, it would render an image but just a broken one? This doesn't render to anything at all.

@themsaid

**Comment by themsaid** [comment]
Copying this `![{{ $app_name }}]({{ asset('/assets/img/logo.png') }})` in my markdown email works fine, please share something I can copy into my laravel app to replicate the issue.

**Comment by pcfutures** [comment]
Not sure what else to share. That simply doesn't render for me. Is it because I'm using Lumen not Laravel?

**Comment by themsaid** [comment]
Using mailtrap check the underlaying HTML to see what's wrong.

**Comment by pcfutures** [comment]
Ah. Found the problem.

You can't use extra markdown within the `mail::header` component, as it renders that as a URL.

```
@component('mail::header', ['url' => '...'])
    {{ $app_name }}
    ![{{ $app_name }}]({{ asset('/assets/img/logo.png') }})
@endcomponent
```
compiles to (assume $app_name = 'test', asset('..') = 'img')
```
[test ![test](img)]
```
which is obviously invalid.

However, removing the `mail::header` component and just using
```
![{{ $app_name }}]({{ asset('/assets/img/logo.png') }})
```
doesn't work either.

**Comment by jjboostability** [comment]
I had the same issue of the email displaying something like:
`![Explanation of Image](https://url/to/image.jpg)`

Until I realized that indentation is a big part of Markdown. I had indented my image tag and Markdown was rendering it as code instead of parsing the image tag. All I had to do was de-indent my img tag and it worked as intended.

**Comment by azzic** [comment]
@jjboostability would you please share your code, I have the same problem. (I'm using laravel 5.6)

here's my blade file: ( the image does not show here)
@component('mail::layout')
    {{-- Header --}}
    @slot('header')
        @component('mail::header', ['url' => ''])
           [An awesome example image]: http://via.placeholder.com/350x150
            {{ $header }}
        @endcomponent
    @endslot

    @foreach ($body as $bodyLine)
        {{ $bodyLine }} <br> <br>
    @endforeach
@endcomponent

However, having an image tag in the header shows the image:

@component('mail::layout')
    {{-- Header --}}
    @slot('header')
        @component('mail::header', ['url' => ''])
               <img src="http://via.placeholder.com/350x150" alt="Smiley face">
            {{ $header }}
        @endcomponent
    @endslot
@endcomponent

is there anything i'm missing related to Markdown email? do I need to publish it?
(e.g. php artisan vendor:publish --tag=laravel-mail)

**Comment by Erkebulan69** [comment]
@ghost do the following:

for your `message.blade.php` layout
```
@component('mail::header', ['url' => '...'])
    ![{{ $app_name }}]({{ asset('/assets/img/logo.png') }})
@endcomponent
```

and in your `header.blade.php` view add markdown parsing
```
<tr>
    <td class="header">
        <a href="{{ $url }}">
            {{ Illuminate\Mail\Markdown::parse($slot) }}
        </a>
    </td>
</tr>
```

**Comment by mdeprezzo** [comment]
@Erkebulan69 stil not work for me

**Comment by masoud-codes** [comment]
undefined variable: app_name 
please help me 

> @ghost do the following:
> 
> for your `message.blade.php` layout
> 
> ```
> @component('mail::header', ['url' => '...'])
>     ![{{ $app_name }}]({{ asset('/assets/img/logo.png') }})
> @endcomponent
> ```
> 
> and in your `header.blade.php` view add markdown parsing
> 
> ```
> <tr>
>     <td class="header">
>         <a href="{{ $url }}">
>             {{ Illuminate\Mail\Markdown::parse($slot) }}
>         </a>
>     </td>
> </tr>
> ```

**Comment by dsturm** [comment]
Hej @masoud-codes,

you should use `config('app.name')` instead of `$app_name`.

**Comment by simonelepore** [comment]
> I had the same issue of the email displaying something like: `![Explanation of Image](https://url/to/image.jpg)`
> 
> Until I realized that indentation is a big part of Markdown. I had indented my image tag and Markdown was rendering it as code instead of parsing the image tag. All I had to do was de-indent my img tag and it worked as intended.

I can't believe it took me hours to finally find the solution and it was as simple 😅 I also indented my code and that's why it wasn't working. Thanks [jjboostability](https://github.com/jjboostability)
