### ISSUE TITLE
PHP inconsistency in collection sort between PHP 5.6.30 and 7.1.4

### ISSUE THREAD

**Issue by EmanueleCoppola** [laravel/framework#19237]
- Laravel Version: 5.3.*
- PHP Version: 5.6.30
- Database Driver & Version: MySql - 10.1.21-MariaDB

### Description:
Using the function sortBy of a collections, will get different results in PHP 5.6.30 rather then PHP 7.1.4.

### Steps To Reproduce:
I have made an array like this:
`
$quizzes['scores'] = [
    [
        'user_id' => 1,
        'score' => 50,
        'timespan' => 5000
    ],
 [
        'user_id' => 2,
        'score' => 70,
        'timespan' => 6000
    ]
];
`
But when i run this code:
`$quizzes['scores'] = collect($quizzes['scores'])->sortBy('score')->toArray();`

what I get on PHP 5.6.30 is:
1) User id 2, score, 70, timespan 5000
2) User id 1, score 50, timespan 6000

but what I get on PHP 7.1.4 is:
1) User id 1, score 50, timespan 6000
2) User id 2, score, 70, timespan 5000
This one should be the correct, since if I run sortByDesc i get them in descendant sequence.

**Comment by themsaid** [comment]
Testing on both versions the results are the same as your PHP 7.1 example.

Closing since it doesn't look like a bug in the framework, also please upgrade your application since laravel 5.3 is not supported anymore.
