### ISSUE TITLE
Please can we get laravel framework as phar archive 

### ISSUE THREAD

**Issue by drnkwati** [laravel/framework#19246]
Hi can we get an phar achieve of laravel framework with every release.

**Comment by m1guelpf** [comment]
@drnkwati Why would you need that?

**Comment by drnkwati** [comment]
Faster and easier to import a phar and use on some shared hosting rather than copying individual files.
I have use conveniently with nette framework

**Comment by themsaid** [comment]
Sorry but there are no plans for this.
