### ISSUE TITLE
[5.4] Clarification queue serialization

### ISSUE THREAD

**Issue by JValck** [laravel/framework#19252]
- Laravel Version: 5.4
- PHP Version:7.0.15
- Database Driver & Version: MySQL 5.7.18

### Description:
Since I upgraded from 5.3 to version 5.4, I notice issues with adding models to the queue.
I know this is caused by my binairy Id's, as I also had a similar issue in 5.3

I solved it in 5.3 by overriding the ```toArray``` method in my models.
Unfortunately this method is no longer called when adding the model to the queue.

I noticed that the payload is now created by [serialization](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Queue/Queue.php#L125).
Why is this changed? How can I solve my binary issue?

### Steps To Reproduce:
1. Use binary UUIDs as ID
2. Add the model to the queue (for example with a mailable).

**Comment by themsaid** [comment]
That wasn't changed between 5.3 and 5.4, it was always like that.

**Comment by JValck** [comment]
Maybe I looked over something.
The strange thing is that when I overrode the `toArray()` method in 5.3 it solved the problem.

Apparently now I need to make each model implement `Serializable` because the model is serialized.
For my case it would be handy if the models could implement the `Serializable` by default.

**Comment by themsaid** [comment]
No need to hack into model serialization, use the `SerializesModels` trait, check:

https://laravel.com/docs/5.4/queues

**Comment by JValck** [comment]
So I can just add `use SerializesModels` in my models and the conversion of the binary UUID will be okay?

**Comment by JValck** [comment]
Ping @themsaid

**Comment by themsaid** [comment]
How did you override the model to array method?

**Comment by themsaid** [comment]
I mean what changes did you have to apply?

**Comment by JValck** [comment]
My models use a trait. In that trait I overrode the `toArray()` method some months ago.
I'm using a third party implementation for the binary UUIDs. You can see the overridden method at [line 93](https://github.com/alsofronie/eloquent-uuid/blob/master/src/UuidBinaryModelTrait.php#L93).

**Comment by JValck** [comment]
Ping @themsaid

**Comment by themsaid** [comment]
Sorry I don't seem to be able to relate your issue to the current code, please continue the followup on the package at https://github.com/alsofronie/eloquent-uuid/issues/29

Please also read about how laravel serializes models for querying, and feel free to ping me if you have specific questions in the flow.
