### ISSUE TITLE
Copy is not flattening folder structure when using wildcard

### ISSUE THREAD

**Issue by RicLeP** [laravel/framework#19253]
- Laravel Version: Latest

### Description:
I’m working on a package that has some public assets so as part of my development build process I want to copy the compiled assets from my package to a Laravel project using the project.

I compile my sass and js into a a dist folder in the package. Then I copy these to the Laravel project.

```
mix.sass('resources/assets/sass/rare.scss', 'resources/assets/dist/css')
	.js('resources/assets/js/app.js', 'resources/assets/dist/js')

	// dev only
	.copy('resources/assets/dist/css/*.css', '../../../rare.dev/public/css')
	.copy('resources/assets/dist/js/*.js', '../../../rare.dev/public/js')
;
```

However the entire folder structure from the package is created in the destination. I’ve tried explicitly setting the third argument to true, and also tried false and copyDirectory(). Each has the same result.

If I specify a filename in the destination argument then the directories are flattened
`.copy('resources/assets/dist/js/*.js', '../../../rare.dev/public/js/app.js')`
but this will not work with a wild card *.

![image](https://cloud.githubusercontent.com/assets/19726976/26198144/df10868a-3bbc-11e7-9c55-e5fcbfb2d5bd.png)

**Comment by ankurk91** [comment]
Report such issues on [laravel-mix](https://github.com/JeffreyWay/laravel-mix) repo, read [docs](https://github.com/JeffreyWay/laravel-mix/blob/master/docs/copying-files.md) before
