### ISSUE TITLE
Factory create uses global scopes

### ISSUE THREAD

**Issue by andybeesee** [laravel/framework#19254]
- Laravel Version: >= 5.4.20
- PHP Version: 7.0.18
- Database Driver & Version: MariaDB 10

### Description:
https://github.com/laravel/framework/commit/1f5822c06a934487e57b5df844ee93b5aed2b435 changed behavior of factories so that global scopes are called when running `factory(User::class)->create()`. If you have a global scope on User that depends on the User being authenticated user `factory(User::class)->create()` throws `ErrorException: trying to get property of non-object`.

I recognize that it is a weird circular dependency (need to have a User to make a User), but it is a breaking change. On version 5.4.19 the exact same code works perfectly.

I will work around if you feel the change is not worth addressing.

### Steps To Reproduce:
New Laravel installation with latest version. Add global scope to User that depends on Auth, use `factory` to create User.

[Example Repo](https://github.com/andybeesee/factory-scope-problem)

[Example user File](https://github.com/andybeesee/factory-scope-problem/blob/master/app/User.php)
```php
static::addGlobalScope('something', function(Builder $builder) {

    if(Auth::user()->admin) {
        //Admin can see everyone
        return $builder;
    }

    // Only return public users
    return $builder->where('private', false);
});
```

[Example failing test](https://github.com/andybeesee/factory-scope-problem/blob/master/tests/Feature/FactoryCreateCallGlobalScopeTest.php)
```php
public function test_that_factory_create_method_doesnt_call_global_scope()
{
    $this->doesntExpectEvents(\ErrorException::class);
    factory(User::class)->create();
}
```

**Comment by themsaid** [comment]
I don't see how this change affects global scopes?

**Comment by andybeesee** [comment]
The problem I am seeing is that the factory builder now applies global scopes when persisting. It did not do so before 5.4.20.

Current version applies scopes....
```php
$model->setConnection($model->query()->getConnection()->getName());
```

Possible change to current so that it doesn't apply scopes
```php
$model->setConnection($model->newQueryWithoutScopes()->getConnection()->getName());
```

**Comment by themsaid** [comment]
Fixed in: https://github.com/laravel/framework/pull/19258

Thanks :)
