### ISSUE TITLE
Artisan console colors have gone

### ISSUE THREAD

**Issue by 1e4** [laravel/framework#19264]
- Laravel Version: 5.4.21
- PHP Version: 7.1
- Database Driver & Version: 

### Description:
Colors are no longer showing up in console

Using `php artisan` http://i.imgur.com/xbgan5A.png
Running composer http://i.imgur.com/p77iAmx.png

I am using Git Bash on Win10

### Steps To Reproduce:
Open Git Bash on Windows 10
Run php artisan on a Laravel install.

**Comment by themsaid** [comment]
Doesn't look like an issue in the core, please ask on the forums.
