### ISSUE TITLE
[4.2] Problems with controllers in subfolder

### ISSUE THREAD

**Issue by FiloSpaTeam** [laravel/framework#19260]
- Laravel Version: 4.2.11
- PHP Version: 5.6.30
- Database Driver & Version: PostgreSQL 9.5.7

### Description:
Since 1 week (i think later a composer update or some change) our subfolder full of Admin controllers doesn work with Session and Input Facade. It's impossible to flash something or redirect back with Input or Errors.
Same code works in controllers folder.

### Steps To Reproduce:
app/controllers -> TestController with a index function and simple redirect to /test with Errors(['test'])
app/controllers/admin/TestController -> with an index function and simple redirect to admin/test with Errors(['test'])

First works and i'm able to see in view and print $errors, second i cannot see.

Thanks in advance.

**Comment by m1guelpf** [comment]
@FiloSpaTeam May be related to updating dependencies in Laravel 5.2 (not supported)

**Comment by themsaid** [comment]
Sorry but that's not the right place for questions, try the forums and I'm sure you'll find help there, sorry again :)

**Comment by FiloSpaTeam** [comment]
Ok Thanks :+1:
