### ISSUE TITLE
Broadcast to private/presence channels with custom user_id

### ISSUE THREAD

**Issue by jamesgraham** [laravel/framework#19261]
- Laravel Version: 5.4.22
- PHP Version: 7.1

### Description:

```
        Broadcast::channel('user.{userId}', function ($user, $userId) {
            return $user->uuid === $userId;
        });
```

Firstly the `Broadcast::channel` method abstracts which type of channel we are listening on. If I have a `presence-channel-name` and `private-channel-name` they both get handled by the same method. Is there a way to get the raw channel name? For presence channels we might wish to use a different mechanism to authorize.

Secondly, the `user_id` is returned as whatever the `$user->id` value is. This should be overridable, for example we may wish to use a uuid or other value such as email address.

**Comment by Dylan-DPC** [comment]
This is not a bug. Open an issue in the laravel/internals repo

**Comment by jiahong96** [comment]
any solution for custom user_id?

**Comment by tobischulz** [comment]
would be awesome to use uuid´s instead of int for the channel names, like:

```
private-notifications.b7dac8ac-c57f-40a0-a27e-55a6c4b97944
```
