### ISSUE TITLE
Error installing Passport on Laravel

### ISSUE THREAD

**Issue by AdriWild** [laravel/framework#19265]
- Laravel Version: 5.4
- PHP Version: 5.6

On a clean installation of Laravel 5.4 I proceed to install passport ( ignoring migrations ).

```
C:\xampp\htdocs\AdrianSilvestre>php artisan passport:install
PHP Fatal error:  Call to undefined method Laravel\Passport\Passport::isDeferred() in C:\xampp\htdocs\AdrianSilvestre\vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php on line 149


  [Symfony\Component\Debug\Exception\FatalErrorException]
  Call to undefined method Laravel\Passport\Passport::isDeferred()
```

**Comment by marcvdm** [comment]
Do you have the correct serviceprovider in your `config/app.php`?

It should be `Laravel\Passport\PassportServiceProvider::class`

I am guessing you have `Laravel\Passport\Passport::class`

**Comment by themsaid** [comment]
Please report on the correct repository.
