### ISSUE TITLE
[5.4] Contextual binding throw a exception on a existing aliased instance

### ISSUE THREAD

**Issue by LeoYang90** [laravel/framework#19268]
- Laravel Version: 5.4.23
- PHP Version:7.1
- Database Driver & Version:NA

### Description:
Hi,
    Contextual binding does not work on a existing aliased instance, it will throw a exception "Target [Illuminate\Tests\Container\IContainerContractStub] is not instantiable while building [Illuminate\Tests\Container\ContainerTestContextInjectOne]."

### Steps To Reproduce
```php
public function testContextualBindingWorksOnExistingAliasedInstances()
{
    $container = new Container;

    $container->alias('Illuminate\Tests\Container\IContainerContractStub','stub');
    $container->instance('stub', new ContainerImplementationStub);

    $container->when('Illuminate\Tests\Container\ContainerTestContextInjectOne')->needs('stub')->give('Illuminate\Tests\Container\ContainerImplementationStubTwo');

    $this->assertInstanceOf(
        'Illuminate\Tests\Container\ContainerImplementationStubTwo',
        $container->make('Illuminate\Tests\Container\ContainerTestContextInjectOne')->impl
    ); 
}

class ContainerTestContextInjectOne
{
    public $impl;

    public function __construct(IContainerContractStub $impl)
    {
        $this->impl = $impl;
    }
}

interface IContainerContractStub
{
}

class ContainerImplementationStub implements IContainerContractStub
{
}

class ContainerImplementationStubTwo implements IContainerContractStub
{
}
```

**Comment by thecrypticace** [comment]
The test for this method is not identical to the above.

Also, your argument order to `->alias` is backwards. The first argument is the bound instance name, not the alias name. This will cause a test failure because the alias is keyed on the wrong thing.

**Comment by LeoYang90** [comment]
@thecrypticace 
Taylor Otwell says it is ok:
```php
public function testContextualBindingWorksOnBoundAlias()
{
    $container = new Container;

    $container->alias('Illuminate\Tests\Container\IContainerContractStub','stub');
    $container->bind('stub', ContainerImplementationStub::class);

    $container->when('Illuminate\Tests\Container\ContainerTestContextInjectOne')->needs('stub')->give('Illuminate\Tests\Container\ContainerImplementationStubTwo');

    $this->assertInstanceOf(
        'Illuminate\Tests\Container\ContainerImplementationStubTwo',
        $container->make('Illuminate\Tests\Container\ContainerTestContextInjectOne')->impl
    ); 
}
```
Why bind is ok, and instance is wrong?

**Comment by thecrypticace** [comment]
I feel like the fact that bind works with the alias arguments flipped is a bug. I'm looking into this though.

**Comment by LeoYang90** [comment]
@thecrypticace 
Yesterday, I do a PR about bind(). But Taylor Otwell close it, and says it is ok. So I am confused.
The test  is new, not in the ContainerTest

**Comment by thecrypticace** [comment]
I'm trying to grok what you're getting at on the PR. (for reference: I'm the one who added the feature for contextual bindings against instances)

**Comment by LeoYang90** [comment]
@thecrypticace 
#19259

**Comment by thecrypticace** [comment]
Something does seem off here but I can't quite track down what. I'll see if I can discover more in the morning.

**Comment by LeoYang90** [comment]
@thecrypticace 
Thank you! I am confused by such questions recently.

**Comment by thecrypticace** [comment]
So, I know why: instance calls `$this->removeAbstractAlias($abstract);`

I remember adding this but I don't know why it was needed and the tests don't seem to cover it. I'll have to write a test to discover what the need for it was.

**Comment by LeoYang90** [comment]
@thecrypticace 
I know it. I came up with the test just because removeAbstractAlias() in instance.
