### ISSUE TITLE
Loop varaiable undefined inside @each of blade

### ISSUE THREAD

**Issue by rorc** [laravel/framework#19272]
- Laravel Version: 5.4.23

**Comment by RikSomers** [comment]
Steps to reproduce?
Any additional info?

**Comment by rorc** [comment]
No, just try use `$loop` variable inside `admin.comments.list-item` template:
```php
@each('admin.comments.list-item', $item->comments, 'comment')
```

**Comment by RikSomers** [comment]
That's because $loop is only added in the `@foreach` directive according to the docs:
https://laravel.com/docs/5.4/blade

**Comment by rorc** [comment]
Yea, but reasonable use `$loop` variable in `@each` directive too.

**Comment by themsaid** [comment]
Yes loop isn't supported in @each

**Comment by rorc** [comment]
Can we improve it?

**Comment by RikSomers** [comment]
You can try to create an issue on the [Laravel Internals](https://github.com/laravel/internals/issues) repo to see if more people need this behaviour, and make a PR for it.

**Comment by rorc** [comment]
Ok, ty.
