### ISSUE TITLE
validate atLeast one field must be required

### ISSUE THREAD

**Issue by whfamily2006** [laravel/framework#19274]
- Laravel Version: 5.4
- PHP Version: 7.0
- Database Driver & Version: Xampp

### Description:
I have 4 or 5 fields of checkboxes and I want to validationRule 
`at_least_required:field1,field2,field3,field4`

### Steps To Reproduce:

<input type = "checkbox" name="field1"  >
<input type = "checkbox" name="another-field" >
<input type = "checkbox" name="is-valid" >
<input type = "checkbox" name="field-valid" >

and these fields are not a group of fields.

**Comment by laurencei** [comment]
Hi there,

Unfortunately this is not a support area for application issues. This is only for issues/bugs with the framework code itself.

Please close your issue ticket here.

You can instead ask your question on one of the many great support areas:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.

**Comment by laurencei** [comment]
This will probably solve what you need anyway: http://stackoverflow.com/q/23401365/1317935

**Comment by themsaid** [comment]
Thanks @laurencei :)

**Comment by decadence** [comment]
@laurencei not a solution if I have 10 fields. Too long to enumerate all of them.
But anyway it's proposal not bug.
