### ISSUE TITLE
FileSystemAdapter::put()-function parameters do not comply with FileSystem interface

### ISSUE THREAD

**Issue by soderluk** [laravel/framework#19270]
- Laravel Version: 5.4.5
- PHP Version: 7.0
- Database Driver & Version: doctrine/mongodb-odm 1.1.3 with alcaeus/mongo-php-adapter 1.0.9

### Description:
The FileSystem interface says that `function put()` takes as third parameter `$visibility = null`, https://github.com/laravel/framework/blob/5.4/src/Illuminate/Contracts/Filesystem/Filesystem.php#L47,
but FileSystemAdapter which implements the interface says that the third parameter is an array https://github.com/laravel/framework/blob/5.4/src/Illuminate/Filesystem/FilesystemAdapter.php#L103.

This is somewhat confusing, and should be fixed. Using League\Flysystem\Filesystem as the driver will end up in a `FatalThrowableError` with a message `Type error: Argument 3 passed to League\\Flysystem\\Filesystem::putStream() must be of the type array, null given, called in /src/api/vendor/illuminate/filesystem/FilesystemAdapter.php on line 118`

### Steps To Reproduce:
Using the `League\Flysystem\Filesystem` as driver pass `$visibility` as `null` in `$filesystem->put('/path/to/dir', 'contents of the file', null);`

**Comment by themsaid** [comment]
Thanks, a fix was submitted to https://github.com/laravel/framework/pull/19389

**Comment by hugovk** [comment]
PR https://github.com/laravel/framework/pull/19389 has been merged, can this be closed?
