### ISSUE TITLE
Error when vendor:publish executed command

### ISSUE THREAD

**Issue by pirmax** [laravel/framework#19271]
- Laravel Version: 5.4.*
- PHP Version: 7.1.5

### Description:
I just installed Laravel 5.4.* and I have error when I execute this command:

**php artisan vendor:publish**

> vagrant@homestead:~/projects/xxxx_com$ php artisan vendor:publish
> 
> 
>   [Symfony\Component\Debug\Exception\FatalThrowableError]
>   Class 'League\Flysystem\MountManager' not found
> 
> 
> vagrant@homestead:~/projects/xxxx_com$

Have you got an idea?

**Comment by laurencei** [comment]
Hi there,

Unfortunately this is not a support area for application issues. This is only for issues/bugs with the framework code itself.

Please close your issue ticket here.

You can instead ask your question on one of the many great support areas:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.

**Comment by pirmax** [comment]
It's an issue with the framework.

Framework is freshly installed and I have this error...

**Comment by laurencei** [comment]
I just tried a fresh install and it works with no issue.

It is probably an issue with your configuration and/or your composer install. Try removing the vendor directory and installing again.

Otherwise best to ask on the forums...
