### ISSUE TITLE
Blade @extends not injecting variables properly

### ISSUE THREAD

**Issue by mikefrancis** [laravel/framework#19277]
- Laravel Version: 5.4.23
- PHP Version: PHP 7.1.5-1+deb.sury.org~xenial+1 (cli) (built: May 11 2017 14:07:52) ( NTS )
- Database Driver & Version: n/a

### Description:

I have created the following short Gist to illustrate the problem:

https://gist.github.com/mikefrancis/e49f6f26247e390a7be74b8eb2985c8d

In the example I am using Blade to extend a template and then pass some variables to it. You would expect the example to output the following:

```
one
two
three
```

But instead, it outputs the following:

```
one
one
one
```

~Strangely enough, I am doing the same in a 5.3 app and this seems to work as expected, so may be a regression?~

Doesn't work in 5.3 either.

### Steps To Reproduce:

* Create a new Laravel install
* Add 3x views from Gist
* View site in browser

**Comment by kdoichinov** [comment]
I'm on version 5.1.45 and see the same behavior, however after some digging in the code I found that writing the partial this way produces the expected result:
```blade
@extends('partial-template')

@section('content')
    <h2>{{ $number }}</h2>
@overwrite
```
Note the use of `@overwrite` instead of stop. I'm not sure if this is by design.

**Comment by mikefrancis** [comment]
@kdoichinov I have just done the exact same, `@overwrite` seems to save the day but I have no idea why.

**Comment by themsaid** [comment]
Yes `@overwrite` is what you need to get a clean version of the buffer current content.
