### ISSUE TITLE
[5.4] Queues listen class timeout

### ISSUE THREAD

**Issue by doreto** [laravel/framework#19280]
- Laravel Version: 5.4.22
- PHP Version: 7.0.13 & 7.1.5

### Description:
When variable **public $timeout = 5;** is placed in the job class, then running the **queue:work** or **queue:listen** and processing the job with timeout variable doesn't affect the job. If timeout is set as option _(queue:listen database --timeout=5)_ it affects the job and timeout. Basically, ignore **timeout** variable in the job class.

### Steps To Reproduce:

- php artisan make:job NameJob
- add **public $timeout = 5;** variable to created job class
- php artisan queue:listen database

When the job is to begin processing, it does not timeout as it should be.
Looking at the [code](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Queue/Listener.php#L110), it doesn't read that variable anywhere.

**Comment by KKSzymanowski** [comment]
As far as I know, the public `$timeout` property works only in PHP 7.1+ with Process Control extension(pcntl) and for `queue:work` command(not `queue:listen`).

**Comment by sisve** [comment]
That is correct, timeouts in Laravel 5.4 are based on async signals introduced in PHP 7.1. The check is done in [Worker::supportsAsyncSignals](https://github.com/laravel/framework/blob/7dbe8fd7f86c049baa92cba67960218625bacc7f/src/Illuminate/Queue/Worker.php#L529-L533) and the handling of timeouts in [Worker::registerTimeoutHandler](https://github.com/laravel/framework/blob/7dbe8fd7f86c049baa92cba67960218625bacc7f/src/Illuminate/Queue/Worker.php#L132-L144).

**Comment by doreto** [comment]
I've upgraded PHP Version => 7.1.5 and the result is the same. It should timeout in 5 seconds, but instead, it continues to work when it reach 60 seconds timeout.
![php7](https://cloud.githubusercontent.com/assets/4704339/26273885/b3f920b4-3d43-11e7-9fec-3953762e6b09.PNG)
![timeout](https://cloud.githubusercontent.com/assets/4704339/26273886/b3fdbdd6-3d43-11e7-8f58-f8f56ed0aacc.PNG)

**Comment by sisve** [comment]
First guess would be that Windows does not support pcntl. Laravel checks for support for pcntl in Worker::supportsAsyncSignals, can you tell us what `extension_loaded('pcntl')` returns?

**Comment by doreto** [comment]
You are right. Windows is not supported
> Note:
> Currently, this module will not function on non-Unix platforms (Windows).

I guess I should keep in mind that on local development (windows) it won't work, but it will be fine on Linux host. Anyway `extension_loaded('pcntl')` return `false`.
