### ISSUE TITLE
Queue worker logs - no daily or cleanup options

### ISSUE THREAD

**Issue by nhtahoe** [laravel/framework#19299]
- Laravel Version: 5.4.23
- PHP Version: 7.1.5
- Database Driver & Version: MySQL 5.7.18

### Description:
There are no options for configuring queue worker logging. Everything just gets dumped into the single worker.log file. That file gets incredibly huge and unworkable when running a lot of queue jobs. Can there be an queue worker logging option like the other logging that I can configure to be broken into daily logs and cleaned up automatically? See: https://laravel.com/docs/5.4/errors#log-storage

### Steps To Reproduce:
Run a lot of queue jobs and watch your worker.log get out of control.

**Comment by sisve** [comment]
Just to clarify; the worker.log file you mention, is that the stdout_logfile in your [supervisor configuration](https://laravel.com/docs/5.4/queues#supervisor-configuration)?

Do you really have to log stdout? Actual errors should still be logged to the default log and handled by the configuration rotation settings.

**Comment by nhtahoe** [comment]
Yes, it is the stdout_logfile in supervisor config.

Good point - in production, I can't see a good reason to log stdout. So
sounds like my issue can be solved by simply removing the line "
stdout_logfile=/home/forge/app.com/worker.log" which will result in only
errors being logged to my default log.

Thanks :)

**Comment by nhtahoe** [comment]
If modifying supervisor is the fix for this issue, how do you go about that to stop logging stdout? I tried removing the "stdout_logfile=/home/forge/app.com/worker.log" line and tried setting it to just "
stdout_logfile=" but both resulted in my queues not processing anymore.

**Comment by marcvdm** [comment]
You could run your queues in production with the `-q, --quiet` flag.

This disables messages in the console or in supervisord logs.

**Comment by Froxz** [comment]
Hi @marcvdm `-q, --quiet` is part of Laravel queues functionality or Supervisor?

**Comment by marcvdm** [comment]
Yes, its a functionality from Laravel

**Comment by Froxz** [comment]
Hi @marcvdm  thank you for your reply, I just can't find any reference to this option in source code.

**Comment by marcvdm** [comment]
Under the hood laravel uses the symfony/console package https://symfony.com/doc/current/console/verbosity.html. Here you can find the verbosity levels of the output.
