### ISSUE TITLE
Validating Arrays not working

### ISSUE THREAD

**Issue by phambinh217** [laravel/framework#19294]
- Laravel Version: 5.4.23
- PHP Version:5.6.24
- Database Driver & Version:mysqli

### Description:
I have a code
```
protected function validatorStore(array $data)
{
    return Validator::make($data, [
        'product_description.*1.name' => 'required|max:255',
        'product_description.*.description' => '',
        'product_description.*.meta_title' => 'required|max:255',
        'product_description.*.meta_description' => '',
        'product_description.*.meta_keyword' => '',
        'product_description.*.tag' => '',
    ]);
}

public function store(Request $request)
{
    $validator = $this->validatorStore($request->all());

    if ($validator->fails()) { // false when i send a emty data
       dd('fails'); // not display
    }
}

```
the code above to validate form, and somes fields is array. But when I send empty data form, it pass to validate. am I doing wrong or may be issues.
ps: my english is not good

**Comment by themsaid** [comment]
You need to validate that the data is an array, all your rules above are related to the array key but not the main array itself, something like `'product_description' => 'required|array'`
