### ISSUE TITLE
[SQL Server] Incorrect row count and pagination when using distinct 

### ISSUE THREAD

**Issue by larryu** [laravel/framework#19298]
Laravel Version: 5.4.18
PHP Version: 7.1
Database Driver & Version: SQL Server 2012

### Description:
Very simple use case, when using distinct with pagination on sql server, there are two issues.
1) Row count is incorrect.
The sql statement that laravel converted is 
[select count(*) as aggregate from table]
Obviously, there is no distinct applied here which causes the problem.

2) First page works perfectly, because laravel converts sql statement to 
[ select distinct top 20 field1, field2 .....] . However from the second page, the duplicated data are got from the database, because laravel converts the sql statement to 
[select * from (
select distinct field1, field2, row_number() over (order by id asc) as row_num from tables ) as temp_table 
where row_num between 21 and 40
]. Apparently, the sub query here is incorrect.

**Comment by larryu** [comment]
#18896 the same as this one.

**Comment by sisve** [comment]
Can you provide code to reproduce the problem? As in a migration, two models, basic seeding and the problematic query?

**Comment by themsaid** [comment]
@larryu please provide a code to reproduce the problem and also check the underlaying queries that occur during execution using the query logger.

**Comment by larryu** [comment]
@sisve @themsaid 
I have three tables(a,b,c) and three models. I wanna get distinct data from table a, which has relation with b and c. The code is as below.
`        $perPage = $request->per_page;
        $orderId = $request->orderId;
        $serviceId = $request->serviceId;

        $query = $this->model->distinct()->select([
            'a.order_id',
            'a.service_id',
            'a.activity_id',
            'a.start_date',
            'a.end_date',
            'a.duration',
            'a.status_id',
        ])
            ->join('b', 'b.id', '=',  'a.activity_id')
            ->where('a.active', 1)
            ->where('a.order_id', $orderId)
            ->where('a.service_id', $serviceId)
            ->with('activity')
            ->orderBy($sortBy, $sortDirection);

	return $query->paginate($perPage);`

It's very simple. I haven't checked with MySQL or other DBs. I use SQL Server. Maybe this is the cause. As @flavio-alves mentioned in his issue https://github.com/laravel/framework/issues/18896, if I changed row_number() to dense_rank(), the pagination problem(duplicated data from second page) will be solved. However, the count problem is still there.

**Comment by sisve** [comment]
Do I have to have the columns order_id, service_id, activity_id, ...? Do I have to filter the query with `->where(...)`? Do I have to sort the query with `->orderBy(...)` or eager-load a relation with `->with(...)` to reproduce this issue? Where are the model definitions?

I already know the answer to these questions, I am merely pointing out that we could use a _minimal reproducible_ test case. Not just the query, but the basic models and everything required to reproduce the issue.

**Comment by larryu** [comment]
@sisve Thanks for the reply and Sorry for the improper additional information provided before.

Actually I thought this is an issue that can be easily reproduced. 
You  can use any table with duplicated data.
The table structure can be like as below.
`        Schema::create('TableA', function (Blueprint $table) {
            $table->increments('id');
            $table->string('column1', 30);
            $table->string('column2', 30);
        });`
id is the primary key.
Assume you have 10 records.
      id column1 column2
1)    1  1 1
2)    2  1 1
3)    3  2 1
4)    4  2 1
5)    5  3 1
6)    6  4 1
7)    7  5 1
8)    8  6 1
9)    9  7 1
10) 10  8 1

`
$perPage = 5;
$query = $this->model->distinct()->select([
        'column1',
        'column2',
    ])
return $query->paginate($perPage);`

As you can see, we expect that the total count that Laravel gives us is 8 rows, but actually it gives back 10 rows.

**Comment by themsaid** [comment]
@sisve see anything broken here?

**Comment by ifaniqbal** [comment]
> First page works perfectly, because laravel converts sql statement to
[ select distinct top 20 field1, field2 .....] . However from the second page, the duplicated data are got from the database, because laravel converts the sql statement to
[select * from (
select distinct field1, field2, row_number() over (order by id asc) as row_num from tables ) as temp_table
where row_num between 21 and 40
]. Apparently, the sub query here is incorrect.

This is what happen to me too.

**Comment by ifaniqbal** [comment]
Just created step by step to produce this error. Please help us to fix this.

Step by step codes are all in [this simple, fresh, new project](https://github.com/ifaniqbal/laravel-sql-server-pagination-query-error/tree/5.1.0). You only need to run **php artisan migrate** and **php artisan db:seed**, then open root route/url.

### Code

Migration:
```
Schema::create('alphabets', function (Blueprint $table) {
    $table->increments('id');
    $table->string('symbol');
    $table->timestamps();
});
Schema::create('numbers', function (Blueprint $table) {
    $table->increments('id');
    $table->string('value');
    $table->timestamps();
});
Schema::create('alphabet_number', function (Blueprint $table) {
    $table->unsignedInteger('alphabet_id');
    $table->unsignedInteger('number_id');
});
```

Seeder:
```
$alphabets = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'w', 'z'];
$numbers   = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

foreach ($alphabets as $alphabet) {
    $a = Alphabet::firstOrCreate(['symbol' => $alphabet]);
}

foreach ($numbers as $number) {
    $n = Number::firstOrCreate(['value' => $number]);
    $alphabets = Alphabet::get();
    foreach ($alphabets as $alphabet) {
        $n->alphabets()->attach($alphabet);
    }
}
```

Main query example:
```
$query = App\Alphabet::join('alphabet_number', 'alphabets.id', '=', 'alphabet_number.alphabet_id')
    ->join('numbers', 'numbers.id', '=', 'alphabet_number.number_id')
    ->select('alphabets.*')
    ->distinct();

$perPage = 5;

$firstPageQuery = $query->take($perPage);
$firstPageResults = $query->take($perPage)->get();
dump($firstPageQuery->toSql(), $firstPageResults->pluck('symbol')->toArray());

$secondPageQuery = $query->skip($perPage)->take($perPage);
$secondPageResults = $query->skip($perPage)->take($perPage)->get();
dump($secondPageQuery->toSql(), $secondPageResults->pluck('symbol')->toArray());

$thirdPageQuery = $query->skip($perPage*2)->take($perPage);
$thirdPageResults = $query->skip($perPage*2)->take($perPage)->get();
dump($thirdPageQuery->toSql(), $thirdPageResults->pluck('symbol')->toArray());
```

### Output

First page:
```
"select distinct top 5 [alphabets].* from [alphabets] inner join [alphabet_number] on [alphabets].[id] = [alphabet_number].[alphabet_id] inner join [numbers] on [numbers].[id] = [alphabet_number].[number_id]"
array:5 [▼
  0 => "a"
  1 => "b"
  2 => "c"
  3 => "d"
  4 => "e"
]
```

Second page:
```
"select * from (select distinct [alphabets].*, row_number() over (order by (select 0)) as row_num from [alphabets] inner join [alphabet_number] on [alphabets].[id] = [alphabet_number].[alphabet_id] inner join [numbers] on [numbers].[id] = [alphabet_number].[number_id]) as temp_table where row_num between 6 and 10"
array:5 [▼
  0 => "a"
  1 => "a"
  2 => "a"
  3 => "a"
  4 => "a"
]
```

Third page:
```
"select * from (select distinct [alphabets].*, row_number() over (order by (select 0)) as row_num from [alphabets] inner join [alphabet_number] on [alphabets].[id] = [alphabet_number].[alphabet_id] inner join [numbers] on [numbers].[id] = [alphabet_number].[number_id]) as temp_table where row_num between 11 and 15"
array:5 [▼
  0 => "b"
  1 => "b"
  2 => "b"
  3 => "b"
  4 => "b"
]
```

**Comment by Tob0t** [comment]
This fixed my problem (using SQLServer): 

> The right way to get this working right would be using dense_rank() instead of row_number() in compileOver() method of Illuminate\Database\Query\Grammars\SqlServerGrammar.

Taken from https://github.com/laravel/framework/issues/18896
