### ISSUE TITLE
Usage when() method  on model relationships

### ISSUE THREAD

**Issue by atayahmet** [laravel/framework#19295]
- Laravel Version: 5.4.23
- PHP Version: 7.1.5
- Database Driver & Version: Postgresql & 9.6.2

### Description:
When i want to use when() method in relationships, i getting the following errors:

`SQLSTATE[42703]: Undefined column: 7 ERROR: column "pivot_in" does not exist`

Usage: (Product model)

```php
return $this->belongsToMany(Category::class, 'category_products')
    ->when(count($personsIds), function($person) {
        return $person->wherePivotIn('category_id', $personsIds);
    })
    ->whereType(Category::PERSON);
```

This is a bug?

**Comment by themsaid** [comment]
The value passed to the closure is an instance of Builder, the `wherePivotIn ` doesn't exist in the builder instance but rather the instance.
