### ISSUE TITLE
Default value for $blueprint->nullableMorphs()

### ISSUE THREAD

**Issue by meNESS** [laravel/framework#19292]
Hi,

`$blueprint->nullableMorphs()` returns `void`, the problem here is, how should I set default `null` value?

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by meNESS** [comment]
@Dylan-DPC This's actually an issue because there's no way provided for solving it.

**Comment by devcircus** [comment]
That's just a helper for the most simple case for defining both the morph id and morph type columns. If you need more control, they can be assigned individually.
