### ISSUE TITLE
Middleware except with passport

### ISSUE THREAD

**Issue by s4uron** [laravel/framework#19302]
- Laravel Version: 5.4.0
- PHP Version: 5.6.28
- Database Driver & Version: mySQL

### Description:
The exception from a middleware does not work anymore with **mapApiRoutes()** (and passport)

If i call **api/v1/announcements** i get:
```
{
  "error": "Unauthenticated."
}
```
even though it should be excepted from middleware auth:api

### Steps To Reproduce:
Install laravel + passport, create a model (Announcement)

in **RouteServiceProvider.php** modify the _mapApiRoutes()_
```
protected function mapApiRoutes()
    {
        Route::prefix('api/v1')
             ->middleware(['auth:api','throttle:60','bindings'])
             ->namespace($this->namespace)
             ->group(base_path('routes/api.php'));
    }
```

in your resource controller (**AnnouncementController.php**) add a _contructor_:

```
    /**
     * Instantiate a new AnnouncementController instance.
     */
    public function __construct(Request $request)
    {
        $this->request = $request;
        // Even guests can view announcements
        if($request->ajax()) {
            $this->middleware('auth:api', ['except' => ['index','show']]);
        } else {
            $this->middleware('auth', ['except' => ['index','show']]);
        }
    }
```

in your **routes/api.php** add
```
Route::resource('announcements','AnnouncementController',['only' => [
    'index', 'show'
]]);
```

**Comment by themsaid** [comment]
Please report on the correct repo: https://github.com/laravel/passport
