### ISSUE TITLE
[PROPOSAL] Include $elements variable in pagination instance

### ISSUE THREAD

**Issue by VisualTrauma** [laravel/framework#19308]
- Laravel Version: 5.4.23
- PHP Version: 5.6.4

### Description:
I am using VueJs in my front-end, I stumbled upon pagination and noticed something after I published the paginator.

```
{{-- Pagination Elements --}}
        @foreach ($elements as $element)
            {{-- "Three Dots" Separator --}}
            @if (is_string($element))
                <li class="uk-disabled"><span>{{ $element }}</span></li>
            @endif 
```

Notice that the `$elements` variable that is the responsible for the elipsis `...` and the `pagination urls` in the pagination buttons, I dug into the classes associated with the `Paginator class` and saw that `$elements` variable is only available in the `view` that called the `Paginator instance` ie. 

```
\App\Controllers\SomeController@show

$things = Model::paginate();
```

In my case, I created an `api` that returns only the `Paginator instance` to be accessed via ajax, and because of that I lost my access to the `$elements` variable. Is there any chance that they include it the the `Paginator instance's json response` for easy access? Right  now I edited
`Illuminate\Pagination\LengthAwarePaginator.php`'s public method `toArray` and added 

```
'elements` => $this->elements()
```

I know changing files in the `vendor` is not good.
But just to have an access to the `$elements` variable, is it okay to make a new class and extend it to the `Illuminate\Pagination\LengthAwarePaginator.php`?

**Comment by ntzm** [comment]
Proposals should go in laravel/internals

**Comment by VisualTrauma** [comment]
My apologies sir.
