### ISSUE TITLE
[Question / Feature request] How to implement Laravel's jobs duplication management?

### ISSUE THREAD

**Issue by mbm-rafal** [laravel/framework#19313]
How to implement Laravel's jobs duplication management?

I feel like this feature should be implemented by default since 

Case: 

I have multiple same jobs, with the same payload added to queue in term of application processing. Let's say UpdateProfiletoElasticsearch while different job is processing this update profile is stacked which laravel does not handle this by design - so job will be processed multiple times, which is unnecessary

Is there any laravel implementation or feature request due to this problem?

I'm going to implement job's checksum based on the payload to represent it's identity so that no duplicate will be added.

Please advise!

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue.

**Comment by mbm-rafal** [comment]
https://laravel.io/forum/05-25-2017-how-to-implement-laravels-jobs-duplication-management
