### ISSUE TITLE
Unable to update an eloquent model in the database when incrementing is false

### ISSUE THREAD

**Issue by sbenskin** [laravel/framework#19317]
- Laravel Version: 5.4.22
- PHP Version: 7.1.3
- Database Driver & Version: MySQL 5.7.15

### Description:

First time contributing so let me know if I've done something wrong.

If you create a new eloquent model with $incrementing set to false and save it, all the values are saved to the database.  If you then change something on that model and call saveOrFail, there is no error, the model updates to the new version, it's marked as clean but the database is not updated.

I haven't done a pull request as I'm unsure what the actual behaviour should be.  I'm assuming because the id is not meant to be an auto increment, it can't update the model, which might be correct, but shouldn't it throw an error if you call update without some way for eloquent to know what to update? At the moment it fails silently

### Steps To Reproduce:

See this gist: https://gist.github.com/sbenskin/aa5ff7babed21fa2394cfa410104637a

**Comment by themsaid** [comment]
Check the comment on your gist.

**Comment by sbenskin** [comment]
Sorry if I didn't make it clear but I know what the incrementing variable does.

My point still stands, if you set the incrementing variable to false, you can save a model once, but if you make a change then try to save again, the model is updated, the dirty/clean flags are set to false and true respectively and the saveOrFail method succeeds, but the database is not updated. Clearly it looks like everything has worked, but it hasn't if the db is not updated.  I think it needs to throw an error if it can't update the database.

Also just closing the issue is a bit rude without allowing me to reply.

**Comment by themsaid** [comment]
Sorry but it's a bit hard to differentiate between actual bugs and people just misconfiguring their code.

Can you please enable the query logger and see what query is getting executed?

**Comment by themsaid** [comment]
Also don't call `$testingModel->saveOrFail();` after you update, the `update()` method persists already.

**Comment by sbenskin** [comment]
Here is the output from the query log.  Just to be clear, I can see it's trying to update a model with a null id, my problem is that it's not throwing an exception, or failing in some manner, but still updating the model, making it look like the update has succeeded without any problems when the database hasn't been updated.

Array
(
    [0] => Array
        (
            [query] => CREATE TABLE IF NOT EXISTS `testing_models` (
      `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
      `test` char(11) DEFAULT '',
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8
            [bindings] => Array
                (
                )

            [time] => 17.13
        )

    [1] => Array
        (
            [query] => TRUNCATE TABLE testing_models;
            [bindings] => Array
                (
                )

            [time] => 4.27
        )

    [2] => Array
        (
            [query] => insert into `testing_models` (`test`) values (?)
            [bindings] => Array
                (
                    [0] => a
                )

            [time] => 1.08
        )

    [3] => Array
        (
            [query] => update `testing_models` set `test` = ? where `id` is null
            [bindings] => Array
                (
                    [0] => b
                )

            [time] => 0.47
        )

    [4] => Array
        (
            [query] => select * from `testing_models` where `testing_models`.`id` = ? limit 1
            [bindings] => Array
                (
                    [0] => 1
                )

            [time] => 0.8
        )

)

**Comment by sbenskin** [comment]
Could you reopen this ticket please?

**Comment by gokure** [comment]
If you disable the `incrementing` property, you should take the primary key by yourself.

```php
$testingModel->fill(['id' => 1, 'test' => 'a']);
```

see [Model.php](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Model.php#L648) file. 😄

**Comment by sbenskin** [comment]
Hi @gokure,

Yes I did know that you have to provide the id for it to update, but there's no error being thrown here.  If you try to create a model, it creates it fine in the database.  Try and change a value and save it, it saves and updates the data on the model and everything looks fine, but the database call failed as can be seen by the SQL it tried to run: "update `testing_models` set `test` = ? where `id` is null".  I think it needs to fail at this point as it's misleading to update the model when the database has not been updated.

**Comment by themsaid** [comment]
Your model have no primary key, how would it update then? the entire scenario here feels wrong, I really suggest that you move this discussion to the forums. I don't believe you'll get any help here, this repo is for bug reporting only.

**Comment by themsaid** [comment]
> there's no error being thrown here. If you try to create a model

Feel free to make a PR for that if you want, meanwhile I'm closing this issue since it's not an actual bug in the core.

**Comment by sbenskin** [comment]
Sorry but I'm not sure I follow. The model is marked as dirty following the data being changed. Calling save tries to update the database but silently fails and the model is marked as clean. The model and the database are now out of sync and the model thinks everything is ok so isn't that a bug?
