### ISSUE TITLE
Facades in ServiceProviders in online documentation

### ISSUE THREAD

**Issue by mtils** [laravel/framework#19322]
- Laravel Version: any
- PHP Version: any
- Database Driver & Version: any

### Description:
In many places inside the documentation facades are used inside service providers. This is like a recommendation for people to do that.
In my experience this is a very bad habit. While facades are great to read, they should be used only in the very upper levels of an application (like in views or if it makes you happy also in Controllers or Commands).

ServiceProviders are something like the opposite of a high level place inside an application. I tend to use only the resolving and afterResolving hooks inside ServiceProviders if I use stuff bound in other or the same ServiceProviders.
If you resolve bindings in ServiceProviders there are three main problems:

- You have to know the extact dependency chain of that binding (is the cache system completely bound while i asking for its bindings)
- You are resolving classes you do not need. See for example [here](https://laravel.com/docs/5.4/passport#configurationl) , If you dont need oauth your service provider will register it anyway.
- You are calling Facade::__callStatic(), Facade::getFacadeRoot(), Facade::resolveFacadeInstance(), Application::offsetGet(), Application::make() while you having a reference to the application in $this->app.

I cant count how often my devs resolving Blade and trapped into the cache errors which are occuring because of a dependency chain they do not completely know.

So perhaps because of readability it is not an option to you to use afterResolving or resolving in docs but $this->app->make() would be a good start.

### Steps To Reproduce:
Read the docs ;-)

**Comment by Dylan-DPC** [comment]
this doesn't belong here. Create a PR in the laravel/docs repo

**Comment by mtils** [comment]
Ok thanks
