### ISSUE TITLE
attachNew() always sets $changes['updated']

### ISSUE THREAD

**Issue by Kyslik** [laravel/framework#19326]
- Laravel Version: 5.4.23
- PHP Version: 7.1.4
- Database Driver & Version: n/a

### Description:
[`attachNew()`](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php#L151)method in interactsWithPivot always sets `$changes['updated']` if updating (syncing) with pivot value.

### Steps To Reproduce:
Have M-M relation (belongsToMany) **with timestamps on pivot enabled**:

    public function members()
    {
        return $this->belongsToMany(User::class, 'project_user', 'project_id', 'user_id')
                    ->withPivot('is_leader')
                    ->withTimestamps(); // without timestamps $changes['updated'] is empty (on succession sync)
    }

```
$model->relationName()->sync([1 => ['pivot_attribute' => 'value']])
```
See screenshot

<img width="662" alt="screen shot 2017-05-24 at 2 29 58 pm" src="https://cloud.githubusercontent.com/assets/2067589/26403242/d01c2410-408d-11e7-8aac-b834da285004.PNG">

**Comment by themsaid** [comment]
Yes because you actually update an existing pivot record, `updated` only implies that the field already exists.

**Comment by Kyslik** [comment]
@themsaid Yes, but when I do not use `withTimestamps`, $changes['updated'] returns empty (as nothing got updated), its kind of not consistent right?

**Comment by Kyslik** [comment]
Ping @themsaid; any comments on my comment?

**Comment by Kyslik** [comment]
I am so sorry for pinging...

Ping @themsaid; any comments on my comment?

**Comment by Kyslik** [comment]
@themsaid Could you please take a look again (I edited and added new response) and write back/re-open?

**Comment by themsaid** [comment]
using `withTimestamps` you touch the record, which makes it updated, yes?

**Comment by Kyslik** [comment]
I guess I miss-understood the logic behind `withTimestamps`, so in order to do what I want to do I need to define relationship without "with timestamps". 

Thanks.

**Comment by Kyslik** [comment]
>If you want your pivot table to have automatically maintained created_at and updated_at timestamps, use the withTimestamps method on the relationship definition:
