### ISSUE TITLE
How do I set the size of an integer(migrate)?

### ISSUE THREAD

**Issue by codingcn** [laravel/framework#19331]
- Laravel Version: 5.4.19
- PHP Version:7.0.1
- Database Driver & Version:mysql 5.7.12

### Description:
I want to know how to set the migrate integer size. The following code is invalid.
```
$table->addColumn('integer', 'updated_time',
                [
                    'length' => 32,
                    'default' => '0',
                    'comment'=>'updated time stamp '
                ]
            );
```

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue
