### ISSUE TITLE
validation not_in for array input

### ISSUE THREAD

**Issue by ibrahimcougar** [laravel/framework#19332]
- Laravel Version: 5.4
- PHP Version: 7
- Database Driver & Version: MySql

### Description:
i have to validate an array input (select2) where i use not_in it dont work for array its work for one item
 
### Steps To Reproduce:

`$this->rules['related_posts'] = 'required|array|min:1|exists:post,id|not_in:'.$this->post->id;`

Thanks

**Comment by mg-freelancer** [comment]
``` $this->post->id ``` is one item not array

**Comment by ibrahimcougar** [comment]
yes but the related_posts is array and i want to except post->id from related_posts

**Comment by themsaid** [comment]
You need something like:

```
$this->rules['related_posts.*'] = 'not_in:'.$this->post->id
```
