### ISSUE TITLE
Notification getting duplicate error.

### ISSUE THREAD

**Issue by daison12006013** [laravel/framework#19339]
- Laravel Version: 5.4.16
- PHP Version: 7.1
- Database Driver & Version: MySQL
- Queue Driver: Beanstalkd

### Description:
Laravel notification getting duplicate error when using queue along batch notification to atleast ~100 users

### Steps To Reproduce:
- Create a notification with **toDatabase**
- Make it ShouldQueue
- Execute atleast ~100 users into that notification
- You will get Duplicate entry in the notifications table

### Attached Error in the **notifications[exception]** table
[error.txt](https://github.com/laravel/framework/files/1028501/error.txt)

**Comment by themsaid** [comment]
Can't replicate your issue, a unique ID is always generated.

**Comment by themsaid** [comment]
Make sure the notifiables list has unique entities and that you're not sending to the database channel multiple times.

**Comment by apbassi89** [comment]
I have the exact same issue happening on a production site. Still investigating what happened, but I've never experienced this until last week. It's happened multiple times on my queue, I'd say about 10 times total so far. If I come up with anything else I'll reply back.

**Comment by dariuszjastrzebski** [comment]
Hi @apbassi89,

Did you solve it? I run into similar issue using code below:

```
$users->each(function($user) use($object){
    $result = $user->user_id === $object->user_id ? $object->xxx : $object->yyy;
    Notification::send($user, new SampleNotification($object,$result)); //SampleNotification implements ShouldQueue
});
```
3 users
2 have the same $result

**Comment by apbassi89** [comment]
@dariuszjastrzebski Unfortunately I spent several days on it and could not figure it out. I ended up writing a custom integration with Nexmo to send my SMS notifications, and replaced all the locations where I queued a notification with a queuing of my new SMS Job.

That solved the problem for me, but obviously that doesn't help anyone who relies on the built in notifications... Sorry about that.

**Comment by alvibd** [comment]
I think, I am having the same issue with this error message
`PDOException: SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "notifications_pkey"`
I am using postgres and my laravel verison is 5.6. I think the uuid generated by the system is not checking existence of 'id' before trying to insert it.

**Comment by bigbharatjain** [comment]
I am also getting the same issue. What is the solution so the we don't get duplicate notification error?
Attached screenshot for the same.
![duplicateentry](https://user-images.githubusercontent.com/26894966/56418666-3c31a580-62b5-11e9-9818-dc80cf52beed.png)

**Comment by MaherSaleem** [comment]
I have faced the same problem, the solution was to change the type of "id" column in notifications migration file from ` $table->increments('id');` to `$table->uuid('id')->primary();`. and after that you have to refresh migrations.

another way is to change the column from database directly to type "char" with Length=36

**Comment by SaundersB** [comment]
I experienced this issue as well. When I used a single notification object with three channels (database, apple push notification, google push notification), I was getting duplicate notifications. When I split the three notifications out into three different notifications I no longer got duplicate notifications.

**Comment by chemoral87** [comment]
> I experienced this issue as well. When I used a single notification object with three channels (database, apple push notification, google push notification), I was getting duplicate notifications. When I split the three notifications out into three different notifications I no longer got duplicate notifications.

do you have an example, how to split and call three notifications?

**Comment by uyab** [comment]
Having this error in production as well
```
[2021-05-22 22:26:25] production.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '707d4e26-af4e-4dc7-927f-6e414dbed562' for key 'PRIMARY' (SQL: insert into `notifications` (`id`, `type`, `data`, `read_at`, `notifiable_id`, `notifiable_type`, `updated_at`, `created_at`) values...
``` 

Anyone has a clue?

**Comment by SaundersB** [comment]
Here is how I split them into three instead of a single with all three in one `via` method array.

`
use NotificationChannels\Fcm\FcmChannel;
class EventAndroidPushNotification extends Notification{   
...
public function via($notifiable): array    {        return [FcmChannel::class];    }
...
}
`


`
use NotificationChannels\Apn\ApnChannel;

class EventApplePushNotification extends Notification{
...
public function via($notifiable): array    {        return [ApnChannel::class];    }
...
}
`



`
class EventDatabaseNotification extends Notification{
...
public function via($notifiable): array    {        return ['database'];    }
...
}
`

**Comment by dev7612** [comment]
I am facing same issue in May 2022. Is there any solution?

**Comment by amrography** [comment]
The issue is because ID is not getting a value. It only happens on a project recently updated to Laravel 8. A fresh installation doesn't have this issue. @themsaid 

![Screen Shot 2022-05-17 at 10 43 46 AM](https://user-images.githubusercontent.com/9614340/168769575-b0a79823-da33-4565-ab08-c4186ab19c7e.png)

**Comment by daison12006013** [comment]
It's been a long time and no one in the core team checking on this.

The solution for this is to use uuid, uuid is much more unique when running on the same micro time, concurrent process is inevitable and surely will occur a duplicated id.

Extend the model and replace the id as uuid and create an auto generated uuid on create event inside the model, that should solve your problem.
