### ISSUE TITLE
Problems with finding user in EloquentUserProvider

### ISSUE THREAD

**Issue by naneri** [laravel/framework#19338]
- Lumen Version: 5.4.#
- PHP Version: 5.6 / 7.0
- Database Driver & Version:

### Description:
I am using a 3rd party package - tymondesigns/jwt-auth for authenticating users in my lumen project. The problem that I get is that it works fine on my local machine and on one remote machine, but not on another one. The difference is that php 5.6 is on the machine that does not work. I have investigated and found out that the in file vendor\illuminate\auth\EloquentUserProvider.php inside the method retrieveByCredentials the user is not found, even though the query does show that it is searching for a user by email. When I run php artisan tinker and search a user manually by email like App\User::where('email','someemail@mail.com')->first() it does return the user correctly.  

### Steps To Reproduce:
install this package https://github.com/krisanalfa/lumen-jwt on 5.6 hosting (I am not sure). Maybe there will be the problem as well. I don't know how to reproduce actually.

**Comment by themsaid** [comment]
Please report on the Lumen repository.

**Comment by naneri** [comment]
I found the problem is with AWS Aurora engine. When I change to 'MySQL' it works fine
