### ISSUE TITLE
Route model binding do not trigger booted event

### ISSUE THREAD

**Issue by rorc** [laravel/framework#19343]
- Laravel Version: 5.4.23

### Description:
```php
trait Reportable
{
    protected static function bootReportable()
    {
        static::registerModelEvent('booted', function(Model $model) {
            $model->setIncrementing(false);
            $model->fillable[] = 'number';
            $model->fillable[] = 'status_id';
        });
    }
}

class Invoice extends Model
{
    use Reportable;

    protected $fillable = ['purpose_of_payment', 'payment_method', 'datetime_of_payment', 'date_of_invoicing'];
}

class InvoiceController extends Controller
{
    public function update(Invoice $invoice, Request $request)
    {
        dump($invoice->getFillable()); //without number and status_id
    }
}
```

**Comment by themsaid** [comment]
You don't call `bootReportable ` anywhere.

**Comment by themsaid** [comment]
The event is triggered but you can't change the values of fillable like this.

**Comment by rorc** [comment]
Why?
In other all situations `$fillable` changing...

**Comment by rorc** [comment]
@themsaid Can you explain please, why if i use `(new Invoice)->getFillable()`, or `Invoice::all()`, etc - `$fillable` changes. But with route model binding - no 😕

**Comment by themsaid** [comment]
Because they are two different instances, the binder first creates an instance of the Model class without loading an actual model from the DB, while creating that instance a model is booted and your listener is fired, then later it retrieves the model value from the DB but by this point your model was booted already so we won't boot it again.

**Comment by rorc** [comment]
Thanks)
What i can do for fix this problem (that my trait works with route model binding) ?

**Comment by rorc** [comment]
@themsaid Sigh, but method `Invoice::find($id)` are not modifying `$fillable` too...
How i can append values to `$fillable` attribute?

**Comment by rorc** [comment]
@themsaid Also i cant modify other fields:
```php
            $model->setIncrementing(false);
            $model->timestamps = false;
```
In general it is possible? I mean modifying model properties not in inside model?

**Comment by themsaid** [comment]
Yes it's not possible, because the model was already booted before.

**Comment by rorc** [comment]
@themsaid Can i reboot model for triggering my changes in trait? 😄
