### ISSUE TITLE
Fatal Error when using 'Default' in namespace

### ISSUE THREAD

**Issue by tagnull** [laravel/framework#19358]
- Laravel Version: 5.4.23
- PHP Version: 7.1.0-2+deb.sury.org~xenial+1

### Description:
I'm getting an error when I namespace my Controllers with the word 'Default' like below:
 
```php
<?php

namespace App\Http\Controllers\Tagnull\ERP\Default\Financial\Accounting;
```

For my own organization, I use to use the word ...\\**Default**\\... when it refers to a default code behavior and ...\\**client_name**\\... when it refers to some specific code.

However, when I run a Controller with the **Default** word in the namespace, I get:
```
FatalThrowableError in TransactionsController.php line 3:
Parse error: syntax error, unexpected 'Default' (T_DEFAULT), expecting identifier (T_STRING)
```

### Steps To Reproduce:
My controller:
`app/Http/Controllers/Tagnull/ERP/Default/Financial/Accounting/TransactionsController.php`

Regarding the used namespace, it's the same of above.

### Quick note
I've noted that this 'Fatal Error' just happens for the Controllers. Everywhere else where I use the word **Default**, it's working perfectly.

E.g.:
```php
<?php

namespace App\Repositories\Tagnull\ERP\Default\Financial\Accounting;
```
```php
<?php

namespace App\Models\Tagnull\ERP\Default\Financial\Accounting;
```

**Comment by Kyslik** [comment]
Try namespace with **Default** in it and do `composer dump-autoload -o`

**Comment by tagnull** [comment]
@Kyslik thank you for your answer. I've checked before regarding this Stackoverflow issue, but it's related to another problem.

Even if I try to **dump-autoload**, it doesn't happen anything.

For me, it's something related to the Laravel's Controller namespacing, as if I try to import a namespace like
```php
...
use App\Repositories\Interfaces\Tagnull\ERP\Default\Financial\Accounting\TransactionRepository;
use App\Validators\Tagnull\ERP\Default\Financial\Accounting\TransactionValidator;
...
```
I get the very same problem.

Outside the controller, the **Default** word is fine for a namespace.

**Comment by themsaid** [comment]
The error is pure PHP, it has nothing to do with Laravel.

**Comment by tagnull** [comment]
Apparently, someone had the same issue using **Phalcon** framework, and it was fixed.

It can be checked here: https://github.com/phalcon/phalcon-devtools/issues/184

**Comment by joshmanders** [comment]
@tagnull it was fixed by renaming the class namespace to something like `FactoryDefault` instead of `Default`.
