### ISSUE TITLE
Connection header in response is always set to 'close' by response handler

### ISSUE THREAD

**Issue by khageshsaini** [laravel/framework#19364]
- Laravel Version: 5.2
- PHP Version: 5.6

### Description:
The response header 'Connection' is always set to 'close' by response handler. If the header set function is called to manually assign 'Connection' header to 'keep-alive', then response contains comma separated string 'keep-alive, close' which browser/client interprets as 'close'.

### Steps To Reproduce:
use response()->json($array, 200, ['Connection' => 'keep-alive']) to set the keep-alive header.

**Comment by themsaid** [comment]
5.2 is not supported anymore, please post on the forums and I'm sure somebody will be able to help you.
