### ISSUE TITLE
Error when use Eloquent+where+pluck.

### ISSUE THREAD

**Issue by ThunderBirdsX3** [laravel/framework#19365]
- Laravel Version: 5.4.23
- PHP Version: 7.1.5
- Database Driver & Version: MySQL 5.7.18

### Description:
I use `pluck` to get array `key` with `null` value.

`$ext_form = ExtForm::where([ [ 'srt_id', $srt_id ], [ 'key', $form ] ])->first();`

`ExtForm` Model.
```
  public function extFormConfig()
  {
    return $this->hasMany(ExtFormConfig::class);
  }
```
Now i found some problem.
```
$ext_input = $ext_form->extFormConfig->where('input_type', '!=', 'file')->pluck(null , 'key')->toArray();
```
When i use `extFormConfig` and `pluck` data, I got what I want. Array `key` with `null` value.

```
$ext_input = $ext_form->extFormConfig()->where('input_type', '!=', 'file')->pluck(null , 'key')->toArray();
```
But if I use `extFormConfig()` and `pluck` data. I got an error.

> 3/3
> QueryException in Connection.php line 647: 
> SQLSTATE[42S22]: Column not found: 1054 Unknown column '' in 'field list' (SQL: select ``, `key` from `ext_form_configs` where `ext_form_configs`.`ext_form_id` = 1 and `ext_form_configs`.`ext_form_id` is not null and `input_type` != file)

> 2/3
> PDOException in PDOConnection.php line 79: 
> SQLSTATE[42S22]: Column not found: 1054 Unknown column '' in 'field list'

> 1/3
> PDOException in PDOConnection.php line 77: 
> SQLSTATE[42S22]: Column not found: 1054 Unknown column '' in 'field list'

### Steps To Reproduce:
I think array `key` with `null` value, It was a great result.

**Comment by themsaid** [comment]
Please ask on the forums, this is no bug with the framework.
