### ISSUE TITLE
Redirect in middleware "auth"

### ISSUE THREAD

**Issue by ConsoleTVs** [laravel/framework#19370]
I think it would be better to redirect to the login page ```route('login')``` rather than throwing an Exception.

Rather than that, I have no clue why this middleware is not by default in \App\Middlewares namespace rather than in the laravel core, other people might prefer redirects or other stuff imo.

Any ideas?

**Comment by Kyslik** [comment]
You can always just make new middleware and name it Auth and use it as you wish.

**Comment by ConsoleTVs** [comment]
This preference is not just something you wish to do, it's a feature most sites use when you're not authed. Yes, I can create a new middleware and do it there, but this will loose all the fun of Laravel making this middleware for you and just changing some thing in there. It's a middleware that works the same way as RedirectIfGuest middleware stored in App\Middlewares by default, (the "guest middleware) where you can modify where you get redirected if you're a guest. It's just the inverse, but the inversed middleware is not stored in the Middlewares folder, it's on the core... Just curious if there's a reason for this...

**Comment by Kyslik** [comment]
Its not simple "inverse" function as you stated, in many of my cases I check following:

is user banned? 
is user confirmed (can user log in: did he/she confirm the registration email?)
...

Wheres while "testing" for guest middleware you simply want to know is user logged in or not (boolean).

**Comment by ConsoleTVs** [comment]
That's why I'm saying it would be better to push this middleware into App\Middlewares to edit it, rather than keeping it in the core and making us creating a new middleware for checking features like mail confirmation, banning, etc.

**Comment by Kyslik** [comment]
I guess you are right.

This should be in internals.
