### ISSUE TITLE
Possible bug passing relationship to notification class?

### ISSUE THREAD

**Issue by applestopears** [laravel/framework#19379]
- Laravel Version: 5.3
- PHP Version: 5.6.23
- Database Driver & Version: MySQL

I created a notification that I am passing a model to:

    class NewMessage extends Notification implements ShouldQueue
    {
        use Queueable;
    
        protected $message;
    
        public function __construct(Message $message)
        {
            $this->message = $message;
        }
    
        public function via()
        {
            return ['database'];
        }
    
        public function toArray()
        {
            Log::info($this->message);
    
            return [
                'message_id' => $this->message->id,
            ];
        }
    }

And this is how I call the notification:

    $message = Message::where('user_id', Auth::user()->id)
        ->where('message_id', $message_id)
        ->with('topic')
        ->get();

    $user->notify(new NewMessage($message));

The problem is that when the notification prints the log (`Log::info($this->message);`), the `topic` relationship doesn't show up.

However, I found that if I change the `toArray()` function in the nofitication class to this, it prints out fine:

    public function toArray()
    {
        $this->message->topic;

        Log::info($this->message);
    
        return [
            'message_id' => $this->message->id,
        ];
    }

What's going on?

**Comment by Kyslik** [comment]
No bug, read this https://laravel.com/docs/5.4/eloquent-relationships#relationship-methods-vs-dynamic-properties
