### ISSUE TITLE
Implement @times into Blade

### ISSUE THREAD

**Issue by DevDaveo** [laravel/framework#19377]
Laravel Version: 5.4 / 5.5

It would be nice to have something similar to Collection::times which is basically a @for but loops n times, for example:
```
@times(4)
    {{ $loop->iteration }} // output: 1 2 3 4
@endtimes
```

I expect this a common pattern among many developers so it would be a neat little helper!

**Comment by Dylan-DPC** [comment]
This is not a bug. Open an issue in the laravel/internals repo

**Comment by DevDaveo** [comment]
Done: https://github.com/laravel/internals/issues/615
