### ISSUE TITLE
Laravel Collections "intersectByKeys" method does not exist

### ISSUE THREAD

**Issue by jakubkratina** [laravel/framework#19376]
- Laravel Version: 5.4

Hi guys,

in the documentation is shown the [intersectByKeys](https://laravel.com/docs/5.4/collections#method-intersectbykeys) method, 

but there only is the `intersect` method in the the `Illuminate\Support\Collection` class.

Has it been removed?

Thanks for the clarification.

Jakub

**Comment by decadence** [comment]
It has been added recently. Make sure you're using latest 5.4.* version.

**Comment by jakubkratina** [comment]
Great :) I updated versions exactly a week ago. Thank you.

**Comment by decadence** [comment]
Looks like it's available only for 5.5 but it's in 5.4 documentation which is wrong.

**Comment by jakubkratina** [comment]
Yep, it has been merged here: https://github.com/laravel/docs/pull/3340
