### ISSUE TITLE
Explicit Model Binding fails by using routes with keywords

### ISSUE THREAD

**Issue by nkaeming** [laravel/framework#19373]
- Laravel Version: 5.4.23
- PHP Version: 7.1.4
- Database Driver & Version: sqlite

### Description:
By using explicit model binding i discovered an issue by using routes that include the keyword defined in the boot function of the RouteServiceProvider. By defining a route  that include only the keyword without {} after some routes which use the {keyword} a NotFoundException (No query results for model [App\User].) is thrown. 

### Steps To Reproduce:
I added this to RouteServiceProvider's boot function:
`Route::model('user', \App\User::class);`

In the web routes i have:
```
Route::group(['prefix' => 'verwaltung'], function () {
    Route::patch('user/{user}/update', 'UserController@update')->name('verwaltung.user.update');
    Route::get('user/{user}', 'UserController@show')->name('verwaltung.user.show');
    Route::get('user/{user}/edit', 'UserController@showEditForm')->name('verwaltung.user.edit');
    Route::patch('user/{user}/setPassword', 'UserController@updatePassword')->name('verwaltung.user.password');
    Route::patch('user/{user}/setRoles', 'UserController@setRoles')->name('verwaltung.user.setRoles');
    Route::get('user/search', 'UserController@search');
}
```
which fails with NotFoundHttpException in Handler.php line 131:
No query results for model [App\User].

This version actually works fine:
```
Route::group(['prefix' => 'verwaltung'], function () {
    Route::get('user/search', 'UserController@search');

    Route::patch('user/{user}/update', 'UserController@update')->name('verwaltung.user.update');
    Route::get('user/{user}', 'UserController@show')->name('verwaltung.user.show');
    Route::get('user/{user}/edit', 'UserController@showEditForm')->name('verwaltung.user.edit');
    Route::patch('user/{user}/setPassword', 'UserController@updatePassword')->name('verwaltung.user.password');
    Route::patch('user/{user}/setRoles', 'UserController@setRoles')->name('verwaltung.user.setRoles');
}
```

It's a fixable issue but i think this is not the expected behaviour.

There is a reason for using explicit model binding because i have some requests that need explicit binding.

Best Regards,
Niklas

**Comment by devcircus** [comment]
With ```Route::get('user/{user}')``` defined before ```Route::get('user/search')```, then you will get the "no query results" error anytime you visit 'user/search'. Thats normal, expected behavior.

**Comment by nkaeming** [comment]
I see your point, but shouldn't {user} only accept integers? Is defining the search route before the other ones with {user} the "right" way to do it, or is there a way to bind {user} to integers?

**Comment by themsaid** [comment]
The order of the routes matter, you need the search route to catch the search URL before the model binding catches it. Hope it's resolved at your end :)
