### ISSUE TITLE
Converting Only Eloquent Collection to Array

### ISSUE THREAD

**Issue by motammem** [laravel/framework#19384]
- Laravel Version: 5.4
- PHP Version: 5.6
- Database Driver & Version: MySQL

### Description:
Consider we have `post` and `author` models and we can access author posts like `$author->posts`
mentioned expression returns `Illuminate\Database\Eloquent\Collection` instance which is not usable by array functions like `array_chunk`  also when use `$collection->toArray()` method  it converts all included objects to associative array. If we need to convert only collection to array ( not included objects ) what shall we do?

**Comment by Kyslik** [comment]
Collections are superset of array functions try to read docs about it https://laravel.com/docs/5.4/collections
