### ISSUE TITLE
Database error with MongoDB

### ISSUE THREAD

**Issue by msankar1991** [laravel/framework#19385]
- Laravel Version: 5.4
- PHP Version: 5.6.30
- Database Driver & Version: MongoDB & MongoDB 3.4

I'm getting error always while loading list view with yajra/datatables version 7.2

```
InvalidArgumentException in DatabaseManager.php line 137:
Database [pgsql] not configured.
in \vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php line 137
```

I've checked the .env & database file having default connection as MongoDB only. 

**.env file**
```
DB_CONNECTION=mongodb
DB_HOST=localhost
DB_PORT=27017
DB_DATABASE=firstapp
DB_USERNAME=mongouser
DB_PASSWORD=xxxxxx
```

**database.php file**

```
'mongodb' => [
            'driver'   => 'mongodb',
            'host'     => env('DB_HOST', 'localhost'),
            'port'     => env('DB_PORT', 27017),
            'database' => env('DB_DATABASE','firstapp'),
            'username' => env('DB_USERNAME','mongouser'),
            'password' => env('DB_PASSWORD','xxxxxx'),
            'options'  => [
                'database' => 'firstapp' // sets the authentication database required by mongo 3
            ]
        ],
```

**Comment by Kyslik** [comment]
> Database [pgsql] not configured.

Is that somehow MongoDB?

**Comment by msankar1991** [comment]
@Kyslik : I'm not get your question. I've updated my question with database config files.

**Comment by themsaid** [comment]
Sorry but looks like the config is cached somewhere or the environment is missed-up, please post on the forums so that people can help, this repo is for bug reporting only.

**Comment by vahidalvandi** [comment]
https://github.com/jenssegers/laravel-mongodb
