### ISSUE TITLE
Eloquent method whereHas works regardless of method with

### ISSUE THREAD

**Issue by rorc** [laravel/framework#19392]
- Laravel Version: 5.4.23

### Description:
```php
User::whereHas('posts', function ($builder) {
    $builder->where('title', 'Foo');
})->with('posts')->get();
```
Now all users have all post (constraint are not apply to `with` method).

If this not bug, can we add new method `whereHasAndWith`? Discussion about this: https://github.com/laravel/internals/issues/606

**Comment by themsaid** [comment]
Yeah it's not a bug, feel free to open a PR or keep the issue opened on internals for discussion.
