### ISSUE TITLE
Add At Least Size Validater

### ISSUE THREAD

**Issue by meysampg** [laravel/framework#19390]
- Laravel Version: 5.4
- PHP Version: 7.1.5
- Database Driver & Version: mysql  Ver 15.1 Distrib 10.1.23-MariaDB

### Description:
There is a `size` validate rule which for which check that size of `number`, `file` or `array` is the same as required value or not. It's a good idea (and ofcourse  necessary) if there's a validate method for checking that the minimum requirements are satisfied about size or not.

### Suggestion:
It easily can be done if something like this be added to core:

    /**
     * Validate the size of an attribute satisfies the minimum requirements.
     *
     * @param  string  $attribute
     * @param  mixed   $value
     * @param  array   $parameters
     * @return bool
     */
    protected function validateAtLeastSize($attribute, $value, $parameters)
    {
        $this->requireParameterCount(1, $parameters, 'size');
        return $this->getSize($attribute, $value) >= $parameters[0];
    }

**Comment by themsaid** [comment]
There's already `min` and `max` rules, check the docs.

If it's not the desired behaviour then please post to the  https://github.com/laravel/internals repo, its where we keep suggestions.
