### ISSUE TITLE
 [InvalidArgumentException]   Database [blog] not configured.

### ISSUE THREAD

**Issue by BekturMuratov** [laravel/framework#19395]
- Laravel Version: 5.4.
- PHP Version: 7
- Database Driver & Version: mysql 5.6

### Description:
how to fix this problem?
 [InvalidArgumentException]
  Database [] not configured.
i can't make migrate

**Comment by themsaid** [comment]
Looks like the database isn't configured in your `config/database.php` file.

**Comment by wessRibeiro** [comment]
Você deve colocar TENANCY_SYSTEM_CONNECTION_NAME=mysql no seu .env e rodar o comando php artisan tenancy:install. Note que mysql é o nome da sua connection no config/database.php

**Comment by wadleo** [comment]
check if the file exists

**Comment by micstudent** [comment]
![database](https://user-images.githubusercontent.com/57383005/88048200-eb27f580-cb78-11ea-8a15-f3a734296c78.jpg)

database.php file is hex file because I use sqlite.

**Comment by micstudent** [comment]
> Looks like the database isn't configured in your `config/database.php` file.

![Care](https://user-images.githubusercontent.com/57383005/88048679-c6804d80-cb79-11ea-9d36-776d2c6b35be.JPG)

because I use sqlite.

**Comment by micstudent** [comment]
Shit! After Debugging the whole day, I solve the problem just run this piece of code.
`php artisan config:cache`
