### ISSUE TITLE
Validation Rule will not allow combining "numeric" with "min"

### ISSUE THREAD

**Issue by chrisblackwell** [laravel/framework#19394]
- Laravel Version: 5.4.23
- PHP Version: 7.1.5
- Database Driver & Version:
SQLite

### Description:
When setting up validation rules, using `'field' => 'numeric|min:5'` doesn't seem to work. It will validate that's it's numeric, but not go on to validate that the number is at least 5 digits long.

### Steps To Reproduce:

Won't validate length of 5
```
public functiion rules()
{
    return [
        'zipcode' => 'numeric|min:5'
    ];
}
```

WILL validate length of 5
```
public functiion rules()
{
    return [
        'zipcode' => 'required|min:5'
    ];
}
```

**Comment by sede2** [comment]
It will validate that the numerical value is greater than 5, you can try min:10000

**Comment by Dylan-DPC** [comment]
This is not a bug. Open an issue in the laravel/internals repo

**Comment by themsaid** [comment]
Yes when combined with numeric it will validate that the field is a number greater than 5. That's the expected behaviour.

**Comment by chrisblackwell** [comment]
@sede2 @themsaid Guys...read the question before closing the issue, or you're not doing any service to the community. I clearly said that's what it's **NOT DOING**.

**Comment by Riari** [comment]
The behaviour of min/size/max rules depends on the type. `numeric|min:5` will check for a minimum numeric value of 5, not a minimum of 5 digits. If you need the latter, you should specify a range with `between` instead.

**Comment by themsaid** [comment]
@chrisblackwell 

```
validator([
    'zipcode' => '3',
], [
    'zipcode' => 'numeric|min:5'
]);
```

Validates fails with the following:

```
array:1 [▼
  0 => "The zipcode must be at least 5."
]
```

On the other hand this passes:

```
validator([
    'zipcode' => 5,
], [
    'zipcode' => 'numeric|min:5'
]);
```

So that's the expected behaviour.

**Comment by themsaid** [comment]
> It will validate that's it's numeric, but not go on to validate that the number is at least 5 digits long.

That's the behaviour you stated you expect in the issue description, that's why the issue was closed, but having it closed doesn't mean the discussion is over :)

**Comment by chrisblackwell** [comment]
Let's say we are trying to pass the number `123`

Right now, this will return valid for both **numberic** and **min:5**

Should it not return valid for numeric and invalid for min:5?

**Comment by themsaid** [comment]
Why not?

**Comment by chrisblackwell** [comment]
Because then people will confuse `size` with `min`. I think `min` should correspond to the **length** of the value, and **size** as the actual size. If we keep `min` as numeric value size, then we actually will never have a way to verify a number of digits.

For example; we could use digits_between to verify that it's 5 - 12 or something, but never just **minimum 5 digits**.

**Comment by Riari** [comment]
That doesn't make any sense. `size` is for specifying a value that must be matched (i.e. not less than, nor greater than) and it totally makes sense that it behaves in the same way as `max` and `min` in the way types are handled.

Also, you _can_ validate the number of digits. Use `between`. In your case, `between:10000,99999`. Admittedly that's not perfect for your exact case, but it does what you're asking for and you could always implement your own validation rule if it's not acceptable.

**Comment by Dylan-DPC** [comment]
I don't see why "min" would relate to minimum number of digits. In any scale where you have to pick of range of values (imagine a slider), the lowest allowed number is always called the "min". It is a common convention

**Comment by markdza** [comment]
Looks like the confusion lies between what "min" is.

According to the Laravel docs, "min" is referring to the **value** of the field (field is greater than X). However, in the OP's case he wants "min" to be the **length** of the field (field of XXXXX is valid, XXXX is not). He doesn't want a range, as suggested, just a single "min" length.

Looks like Laravel doesn't have that option (yet)

**Comment by Riari** [comment]
I know OP doesn't want a range, I only suggested it because it's the closest possible solution at the moment and changing the behaviour of `min` isn't an option. I think a PR or issue to introduce `digits_min` and `digits_max` would be a good idea (I searched the repo; seems it hasn't been suggested before).
