### ISSUE TITLE
joined table using eloquent returns soft deleted rows

### ISSUE THREAD

**Issue by manoj-infrasssist** [laravel/framework#19400]
- Laravel Version: 5.3
- PHP Version: 7.0.8
- Database Driver & Version: Mariadb

### Description:
When I try to fetch rows from multiple tables using eloquent query, it also returns the soft deleted rows from the second joined table. Is there any option which can results only the non-deleted rows for joined query?

**Comment by themsaid** [comment]
Please share a code example.

**Comment by manoj-infrasssist** [comment]
I am using eloquent as below: 
$result = SubcontractorDepartment::join('subcontractors as sc','sc.id','subcontractor_departments.subcontractor_id')->get();

Its also returning the rows which are softdeleted in the subcontractors table. Its working fine for subcontractor_departments table.

Is there any solution without using whereNull('deleted_at') ?

**Comment by themsaid** [comment]
Yes because while joining you're not applying Eloquent constraints, if you decide to use joins you need to adjust the query manually and not rely on eloquent.
