### ISSUE TITLE
[5.4] Nested transactions in sql server not rolling back properly

### ISSUE THREAD

**Issue by RikSomers** [laravel/framework#19415]
- Laravel Version: 5.4.24
- PHP Version: 7.0.9
- Database Driver & Version: SQL Server 2012 / mssql

### Description:
At the place I work, I was working on changing some tests to make sure the feature was properly tested by not mocking all the calls, and I found this weird bug.

When using nested transactions (for example when using the DatabaseTransactions-trait and testing a piece of software that uses it's own transactions), the (to be tested) transaction seems to be committed prematurely and can't be rolled back by calling `->rollBack()` on the connection.

### Steps To Reproduce:
(optional) Composer install `orchestra/testbench`
Use either `DatabaseTransactions` or paste the following into your (orchestra) TestCase file:
```php
    /**
     * Setup the test environment.
     */
    public function setUp()
    {
        parent::setUp();

        $this->app->make('db')->connection('your_sqlserv_db')->beginTransaction();

        $this->beforeApplicationDestroyed(function () {
            $this->app->make('db')->connection('your_sqlserv_db')->rollBack();
        });
    }
```
This makes sure the whole test is encapsulated in a transaction.

Create a model and provide it the sql server connection ("your_sqlserv_db") and create a model factory for it. In the testfile, I chose to use the User model.

Next, run the following testfile:
```php
class TransactionTest extends TestCase
{
    /** @test */
    public function it_works()
    {
        // We should have zero users at this point
        $this->assertCount(0, User::all());

        // Begin another transaction
        DB::connection('your_sqlserv_db')->beginTransaction();

        // Create a user
        factory(User::class)->create();

        // Rollback creating the user
        DB::connection('your_sqlserv_db')->rollBack();

        // Assert the user is properly discarded of
        $this->assertCount(0, User::all()); // This will error and tell us there is 1 user
    }
}
```

Then run the testcase with phpunit

Results in:
![image](https://cloud.githubusercontent.com/assets/3490201/26623336/ac5a67b6-45ed-11e7-9fb4-b9aa179619c4.png)

**Comment by themsaid** [comment]
Fixed in https://github.com/laravel/framework/pull/19439
