### ISSUE TITLE
Cookie array values no longer allowed

### ISSUE THREAD

**Issue by ciaranmaher** [laravel/framework#19417]
- Laravel Version: v5.4.24
- PHP Version: 7.0.15
- Database Driver & Version: N/A

### Description:
Laravel framework requires a number of symfony packages, within composer.json are required as ~3.2. I've seen some strange behaviours within Laravel since symfony released their 3.3 version. 

One such issue is that I am no longer able to create a cookie from an array. 

```
$cookie = cookie()->forever('cookie', [
    'a' => '1',
    'b' => '2'
]);
return redirect('/')->withCookie($cookie);
```

This now throws an array to string conversion exception error. The work around is to json encode the array before setting the cookie and decode on the other side but is this now the expected behaviour from here on in?

### Steps To Reproduce:

Add routes to `/routes/web.php`

```
Route::get('/page1', function () {
    $cookie = cookie()->forever('cookie', [
        'a' => '1',
        'b' => '2',
    ]);
    return redirect('/page2')->withCookie($cookie);
});

Route::get('/page2', function () {
    dd(Cookie::get('cookie'));
});
```

**Comment by ciaranmaher** [comment]
Just to add to above.. 

On a fresh Laravel install, if you override the `symfony/http-foundation` dependancy in `composer.json` by pulling in the latest 3.2 version the above example works as expected.

```
>>composer.json

"require": {
    "php": ">=5.6.4",
    "laravel/framework": "5.4.*",
    "laravel/tinker": "~1.0",
    "symfony/http-foundation": "3.2.*"
},
```

**Comment by themsaid** [comment]
yes looks like another breaking change in 3.3, however it was never documented in Laravel that you may pass an array, even the method docblock indicates that the value is a `string`.

Closing this since it's not related to laravel core.

**Comment by ciaranmaher** [comment]
@themsaid Cool, will just encode/decode from here on. Frustrating all the same.. need to do some refactoring now!

**Comment by Darkyn** [comment]
Damn, this one biting me in the a$$ too. *sigh*
