### ISSUE TITLE
DatabaseMigrations in tests does not rollback

### ISSUE THREAD

**Issue by asivaneswaran** [laravel/framework#19413]
- Laravel Version: 5.4.12
- PHP Version: 7.1.3
- Database Driver & Version: MYSQL 5.7.17

### Description:
My tests table is not being migrated after every tests. The data just keeps piling up without being reset.

### Steps To Reproduce:
Add these lines in `phpunit.xml`: 
```
<env name="DB_CONNECTION" value="mysql"/>
<env name="DB_DATABASE" value="kin-ball-v4-testing"/>
```
And then use the trait: `use DatabaseMigrations;` in your tests.

I don't even have an setup method in this test like this thread was saying:
https://laracasts.com/discuss/channels/testing/databasetransactions-databasemigrations-have-no-effect

Thanks,

**Comment by brunogaspar** [comment]
Don't you also need to use `Illuminate\Foundation\Testing\DatabaseTransactions` trait for the migrations to rollback?

**Comment by asivaneswaran** [comment]
@brunogaspar Yeah, I import that and then use the trait in my class.

```
<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Tests\TestCase;

class SeasonTest extends TestCase
{
    use DatabaseMigrations;
```

**Comment by devcircus** [comment]
@brunogaspar no, the migrations trait is sufficient on its own

**Comment by brunogaspar** [comment]
Oh my bad, i need some sleep lol, thought it was not rolling back when something failed.

**Comment by asivaneswaran** [comment]
I found another thread with the same kind of error:
https://github.com/laravel/framework/issues/12161

But it was supposed to be fixed...

**Comment by asivaneswaran** [comment]
I think I found the issue.

Here is the code for DatabaseMigrations:

```
 public function runDatabaseMigrations()
    {
        $this->artisan('migrate');


        $this->app[Kernel::class]->setArtisan(null);

        $this->beforeApplicationDestroyed(function () {
            $this->artisan('migrate:rollback');
        });
    }
```

As you can see, it runs `migrate:rollback` instead of `migrate:refresh`

**Comment by devcircus** [comment]
It migrates before and rolls back afterwards. Next time it migrates before and rolls back afterwards. I use it currently with two of my test suites with over 1000 tests.

**Comment by asivaneswaran** [comment]
Yeah your right. I don't know what I was thinking. For some reason I was thinking about my prod DB I guess.

But yeah, I know that that trait function gets called... I just don't know why it's not getting rolled back...

**Comment by themsaid** [comment]
hmmm It looks like I can't replicate the issue, it runs rollback as normal, I suggest that you create a new fresh laravel app and test there, if it works then check if you made any changes to the migrator via a service provider or something in your project.

**Comment by asivaneswaran** [comment]
Hi,

I think I found out why. Homestead sets an local env variable which doesn't get overriden... so the APP_ENV never gets changed to testing.

**Comment by ryancwalsh** [comment]
@asivaneswaran I'm having this same problem with the DatabaseMigrations trait not working in Laravel 5.4.30.  I'm using Homestead, too.  Can you please elaborate on what you mean the fix is when you say "Homestead sets an local env variable which doesn't get overriden... so the APP_ENV never gets changed to testing."?  Thank you so much.
