### ISSUE TITLE
If auth.basic set, can't logout

### ISSUE THREAD

**Issue by AdrianKuriata** [laravel/framework#19418]
- Laravel Version: Newest
- PHP Version: 7.0
- Database Driver & Version: Newest

### Description: 
Hi, when you try do whole page with access just for login users, you can't log out when you will set auth.basic like a middleware for whole page. I testing it with clear installed laravel project.
When i changes on auth middleware, everything working perfecly.

### Steps To Reproduce:
1. Set auth.basic for HomeController.
2. Login to your account.
3. When you try logout, you will be just redirect to the main page, but you will be login on your account.

**Comment by themsaid** [comment]
Please ask on the forums.

**Comment by themsaid** [comment]
I also advise that you include code samples so people can better help.
