### ISSUE TITLE
[5.4] Adding non-nullable JSON fields doesn't work on sqlite

### ISSUE THREAD

**Issue by sebastiandedeyne** [laravel/framework#19416]
- Laravel Version: 5.4.23
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7.18 & sqlite 3

### Description:

Adding non-nullable JSON fields doesn't work on sqlite, but does on MySQL.

### Steps To Reproduce:

Write a migration that adds a non-nullable JSON field. This works in MySQL, not in sqlite. Needs an if-statement to work around the issue.

```php
Schema::table('posts', function (Blueprint $table) {
    if (config('database.default') === 'sqlite') {
        $table->json('tags')->nullable();
    } else {
        $table->json('tags');
    }
});
```

Can we have sqlite make these nullable under the hood, so the frameworks takes care of that, or would that be a bad idea?

**Comment by ntzm** [comment]
It's a feature of SQLite, because you are modifying a table, it will have data in already. If the new column isn't nullable and you add a new column, what is it supposed to do with the rows that currently exist? See this answer: https://stackoverflow.com/a/3170700

**Comment by sebastiandedeyne** [comment]
I realise this is an SQLite feature, but since Laravel's Schema builder is database agnostic, I think it'd be more interesting to have this inconsistency between drivers managed by Laravel.

**Comment by themsaid** [comment]
PR submitted in https://github.com/laravel/framework/pull/19422

Moving the discussion to there :)
