### ISSUE TITLE
Reordering Middleware in Http Kernel to avoid token Csrf Mismatch Exception

### ISSUE THREAD

**Issue by antoine1302** [laravel/framework#19424]
- Laravel Version: 5.4.23
- PHP Version: 7.0
- PostGreSql 9.5.6:

Hello everyone !

Does it make sense to reorder middleware  in App\Http\Kernel.php to avoid the token csrf mismatch exception and be redirected instead ? Since the session cookie is expired anyway ?

**Comment by Dylan-DPC** [comment]
This is not a bug. Open an issue in the laravel/internals repo

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by antoine1302** [comment]
This not my personnal issue, lot of people been through this issue. So ease up.

**Comment by Dylan-DPC** [comment]
Doesn't matter. Souds more like you are asking a question. Whether it is 1 person or a million people

**Comment by antoine1302** [comment]
I hope someone who understand this issue will jump into this thread

**Comment by themsaid** [comment]
If you don't want to use that middleware you can just remove it from your HTTP Kernel configs, I don't really get why you want to **re-order**.

**Comment by Dylan-DPC** [comment]
If its a bug present it as a bug with steps to reproduce.

**Comment by antoine1302** [comment]
Let's say that you're currently authenticated (no remember token) in your app with a 120 minutes timeout settings.

If you stay idle for more than 120 min (session is expired) and try to logout or try to submit a form you've been idle, you'll get a 500 response from the server instead of logout/redirect. The session is expired anyway so why send an exception ? 

I think verfiyCsrfToken is almost mandatory middleware preventing any unattended behaviour, but it shouldn't get in the way of UX.

**Comment by laurencei** [comment]
This has already been fixed for 5.5: https://github.com/laravel/framework/pull/18728

**Comment by themsaid** [comment]
@antoine1302 now I got it, please try to make the issue description is useful as possible to make it easier to discuss :)

I believe @laurencei PR solves your issue?

**Comment by antoine1302** [comment]
Oh that's exactly it. Thanks a bunch @laurencei ! Sorry all for the duplicate. I'm closing.
