### ISSUE TITLE
Consider to update npm packages

### ISSUE THREAD

**Issue by yammadev** [laravel/framework#19431]
- Laravel Version: 5.4
- PHP Version: 7.0
- NPM: 5.0.0

### Description:
Hi there everyone, this is not an issue properly, but devDepencies in `package.json` seems to have a few versions outdated, could be possible to update them? The npm-check-updates `ncu -a` command do the job. 

Laravel is such an amazing framework.

Thanks

**Comment by m1guelpf** [comment]
An integration like Greenkeeper could be installed to automate this, but seeml like @GrahamCampbell  (I don't know @taylorotwell's opinion) doesn't like this kind of tools

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. Discussing on the forums is probably the best way forward. :)
