### ISSUE TITLE
Not possible to use database/table names with dot in it

### ISSUE THREAD

**Issue by morloderex** [laravel/framework#19434]
- Laravel Version: relevant to all versions 4.0 and above
- PHP Version: not relevant
- Database Driver & Version: 
     `mysql` version is not relavent.
     However i haven't tested all drivers yet. 

### Description:
While working on a legacy project i came across an issue with how the query grammer formats the tablenames/databasenames and column names for the query. 

The issue here is that i have a database with a `.` in it's name. 
the query grammer would format this as ``` `database/table`.`name`.`columnname` ``` instead of the correct value of ``` `tablename/database`.`columnname` ```

However i'm not sure if this a bug or a limitation to the database component. 

### Steps To Reproduce:

Create a database with a `.` in it's name.
Run a query against it using the query builder.

**Comment by Dylan-DPC** [comment]
I am not sure this will be fixed. Will cause a major change in query structure

**Comment by rambo666** [comment]
will this ever be solved? I am not a fan of dot in table name. But my client has this database and I need to reproduce a product based on his already made tables. It works while using plain PHP why not in Laravel?

**Comment by bAngerman** [comment]
https://github.com/laravel/framework/issues/28307#issuecomment-1622328456 - this solution worked for me
