### ISSUE TITLE
Cannot use with :memory: sqlite database?

### ISSUE THREAD

**Issue by nehero** [laravel/framework#19430]
- Laravel Version: 5.4.23
- PHP Version: 7.0.18
- Database Driver & Version: 
Sqlite `3.14.0 2016-07-26 15:17:14 91e811f51e611a37372875e96a4c51bbed2dfdea`

### Description:

I think this may be an issue with sqlite but thought I would try here first.

**Note everything works fine when I use mysql as the db**.

I'm using the `laravel/browser-kit-testing` package and trying to use `:memory:` as the database with sqlite. 

When I add `use DatabaseMigrations` to the test, I get the following error when tests are run 

```
1) Tests\Feature\integration\OrganizationTest::an_organization_can_be_created
Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL (SQL: alter table "seasons" add column "division_id" integer not null)
```

This is the relevant migration

```php
Schema::table('seasons', function (Blueprint $table) {
    $table->dropForeign(['league_id']);
    $table->dropColumn(['league_id']);
    $table->integer('division_id')->unsigned();
    $table->foreign('division_id')->references('id')->on('divisions')->onDelete('cascade');
});
```

I understand this is usually an error when you have existing rows in the database and you try to add a NOT NULL column without a default, but these are fresh migrations w/o seeders (and it works fine when the `env` is set to `mysql`).

**Comment by ntzm** [comment]
Related issue: #19416

**Comment by themsaid** [comment]
Yes sqlite will throw that on every Alter commands even if the DB is empty, more details in https://stackoverflow.com/questions/3170634/how-to-solve-cannot-add-a-not-null-column-with-default-value-null-in-sqlite3/3170700#3170700
