### ISSUE TITLE
$columns isn't passed in paginate function on eloquent model

### ISSUE THREAD

**Issue by pimski** [laravel/framework#19444]
- Laravel Version: 5.4.23
- PHP Version: 7.0.13
- Database Driver & Version: 10.1.19-MariaDB

### Description:
Changing paginate's $columns variabele from ['*'] to something else has no effect on the count query. I think this variable should be passed through in ``getCountForPagination()`` when determining the count query (\Illuminate\Database\Eloquent\Builder.php around line 690):
```
$results = ($total = $this->toBase()->getCountForPagination())
                                    ? $this->forPage($page, $perPage)->get($columns)
                                    : $this->model->newCollection();
```

### Steps To Reproduce:
```
SomeModel::select()->paginate(50, ['id']);
```

Small bug, but it prevents me from creating ``select count(distinct id)...``

**Comment by themsaid** [comment]
This was attempted multiple times, feel free to open a PR if you know a fix :)

Otherwise, a discussion is ongoing here already: https://github.com/laravel/framework/issues/15675
