### ISSUE TITLE
[5.4] - Validate 'date' with 'milliseconds' (not 'microseconds')

### ISSUE THREAD

**Issue by vlauciani** [laravel/framework#19445]
- Laravel Version: 5.4.23
- PHP Version: 7.0.19
- Database Driver & Version: MySQL 5.6

### Description:
I'm trying to validate an input date field that contains milliseconds; something like this: 
`2017-03-20 23:48:52.243`.
but it doesn't work.

### Steps To Reproduce:
    $validator = Validator::make($myArray, [
        'mytime' => 'date_format:"Y-m-d H:i:s.v"|required'
    ]);

Please, note that I need to validate `milliseconds` (`v`) and not `microseconds` (`u`). The `v` option was implemented on PHP7.0 (http://php.net/manual/en/function.date.php).

**Comment by haakym** [comment]
I didn't see any failing tests for this bug report so I wrote one: https://github.com/laravel/framework/pull/19460

Please provide guidance if I made any mistakes on contributing with this PR as I'm a newb to the process.

Thanks!

**Comment by vlauciani** [comment]
Hi 

Thank you for your support.

I provided a Test that fails for me:
```
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Support\Facades\Validator;

class MyValidatorTest extends TestCase
{
    public function testValidateMicroseconds()
    {
        // Set input params
        $myArray = [ 
            'x' => '2016-06-22 16:52:06.321321', 
        ];
        
        // Validate microseconds
        $validator = Validator::make($myArray, [
            'x' => 'date_format:Y-m-d H:i:s.u',
        ]);
        $this->assertTrue($validator->passes());
    }
    
    public function testValidateMilliseconds()
    {
        // Set input params
        $myArray = [ 
            'y' => '2016-06-22 16:52:06.321' 
        ];
        
        // Validate milliseconds
        $validator = Validator::make($myArray, [
            'y' => 'date_format:Y-m-d H:i:s.v',
        ]);
        $this->assertTrue($validator->passes());
    }    
}
```
As you can see, I validating `microseconds` and `milliseconds`; the "microseconds" pass the test but the "milliseconds" fails:
```
PHPUnit 5.7.20 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.0.19
Configuration: /Users/valentino/Desktop/gitwork/group__caravel/dante/phpunit.xml

.F                                                                  2 / 2 (100%)

Time: 84 ms, Memory: 10.00MB

There was 1 failure:

1) App\Api\V1\Tests\MyValidatorTest::testValidateMilliseconds
Failed asserting that false is true.

/Users/valentino/Desktop/gitwork/group__caravel/dante/app/Api/V1/Tests/Eventdb/MyValidatorTest.php:38

FAILURES!
Tests: 2, Assertions: 2, Failures: 1.
```

Any idea?

**Comment by jn-jairo** [comment]
Looking at the code I found in `\Illuminate\Validation\Concerns\ValidatesAttributes.php`

```
      /**  
       * Validate that an attribute matches a date format.
       *
       * @param  string  $attribute
       * @param  mixed   $value
       * @param  array   $parameters
       * @return bool
       */
      protected function validateDateFormat($attribute, $value, $parameters)
      {    
          $this->requireParameterCount(1, $parameters, 'date_format');
  
          if (! is_string($value) && ! is_numeric($value)) {
              return false;
          }    
  
          $date = DateTime::createFromFormat($parameters[0], $value);
  
          return $date && $date->format($parameters[0]) == $value;
      }
```
As you can see the `date_format` validation uses `DateTime::createFromFormat` to validate the date.

In the php documentation (http://php.net/manual/en/datetime.createfromformat.php) you can see that this method does not accepts the `v` parameter like the `date()` function.

**Comment by haakym** [comment]
Hey guys, I managed to modify the method to use a combination of the `date()` method (which supports `v`/milliseconds) and the `DateTime` object to get it passing for `v`/milliseconds (perhaps a bit hacky?):

```
protected function validateDateFormat($attribute, $value, $parameters)
{
    $this->requireParameterCount(1, $parameters, 'date_format');

    if (! is_string($value) && ! is_numeric($value)) {
        return false;
    }

    // create date string with given format
    $dateString = date($parameters[0], strtotime($value));
    
     // create DateTime object with $dateString var
    $date = new DateTime($dateString);

    // DateTime->format() method outputs the result of 'v'
    return $date && $date->format($parameters[0]) == $value;
}
```

See the following code to see how this works:

```
>>> $dateString = date('Y-m-d H:i:s.v', strtotime('2000-01-01 00:00:00.000'));
=> "2000-01-01 00:00:00.000"
>>> $date = new DateTime($dateString);
=> DateTime {#809
     +"date": "2000-01-01 00:00:00.000000",
     +"timezone_type": 3,
     +"timezone": "UTC",
   }
>>> $date->format('Y-m-d H:i:s.v')
=> "2000-01-01 00:00:00.000"
```

However, this breaks three other tests which I believe are related to timezone. If I have understood things correctly this is because the `date()` method appears to rely on the timezone set at the beginning of the test: `date_default_timezone_set('UTC');`, rather than what the timezone was passed into the test. E.g. Instead of `Atlantic/Azores` it will return `UTC`.

The three failing tests are as follows:

```
// e - Timezone identifier
$v = new Validator($trans, ['x' => '2000-01-01T00:00:00Atlantic/Azores'], ['x' => 'date_format:Y-m-d\TH:i:se']);
$this->assertTrue($v->passes());

// T - Timezone abbreviation
$v = new Validator($trans, ['x' => '2000-01-01T00:00:00Z'], ['x' => 'date_format:Y-m-d\TH:i:sT']);
$this->assertTrue($v->passes());

// P - Difference to Greenwich time (GMT) with colon between hours and minutes
$v = new Validator($trans, ['x' => '2000-01-01T00:00:00+00:30'], ['x' => 'date_format:Y-m-d\TH:i:sP']);
$this->assertTrue($v->passes());
```

The only way I can think to get it passing right now is to check if the format string has a `v` in it and to use the original logic if it doesn't and then to alternatively use the logic I have written above if it does. Again, a bit hacky, but it gets the tests passing.

```
protected function validateDateFormat($attribute, $value, $parameters)
{
    $this->requireParameterCount(1, $parameters, 'date_format');

    if (! is_string($value) && ! is_numeric($value)) {
        return false;
    }

    if (!preg_match('/v/', $parameters[0])) {
        $date = DateTime::createFromFormat($parameters[0], $value);
    } else {
        $dateString = date($parameters[0], strtotime($value));
        $date = new DateTime($dateString);
    }

    return $date && $date->format($parameters[0]) == $value;
}
```

Any thoughts on this?

Another thought I had was that `v`/millisecond is only supported in PHP 7.0, so I'm guessing it would need to be added to Laravel 5.5 which I've read will require PHP 7.0? - https://laravel-news.com/laravel-5-5-php-7-0

**Comment by themsaid** [comment]
Closing and moving the discussion to the opened PR.
