### ISSUE TITLE
Unable to retrieve $exception itself in view sent within Exception Handler.

### ISSUE THREAD

**Issue by berkantipek** [laravel/framework#19478]
- Laravel Version: 5.4.* Latest Stable
- PHP Version: 7.1.5

### Description:
I try to send ```$exception``` variable itself as flash data in Exception Handler's ```render``` method.
```php
public function render($request, Exception $exception)
    {
        if($this->isHttpException($exception))
        {
            if($exception instanceof NotFoundHttpException)
            {
                return redirect('/404')->with('exception', $exception);
            }
        }

        return parent::render($request, $exception);
    }
```
But it comes ```NULL``` in view page.
```php
Route::get('/404', function(){
      dd(session('exception'));
});
```
However, it works properly if I send ```$exception->getStatusCode()```. I can get ```404``` in this occasion.
### Steps To Reproduce:
1) Try to send ```$exception``` var to any view within Exception Handler.
2) It arrives ```NULL``` there.
3) Try to send ```$exception->getStatusCode()``` or ```$exception->getHeaders()```.
4) They come normally.

**Comment by themsaid** [comment]
The exception is a large expensive object, I don't see why you try to add it to the session!! My advice is to send only the parts you want.

**Comment by berkantipek** [comment]
Then I'd have to parse the things I want (5-6) from $exception for several times for each one of my custom pages. If I reset the "render" method in Exception Handler, I can directly access $exception within all error pages in errors/ folder. I just want the $exception to be at my command ready like every built-in error page.

**Comment by stefanoruth** [comment]
Why not just render a view there instead of a redirect?

**Comment by themsaid** [comment]
Yes because I do putting the whole exception with the whole backtrace into the session is not a good idea.

**Comment by berkantipek** [comment]
@stefanoruth That works. But I'd rather having seperated error views and controllers to handle them.

**Comment by stefanoruth** [comment]
Okay i have an idear for you

If you want some custom functions on your exceptions i would each time the come ind wrap them within a new exception class that has the functionalitet you need.

Else from what i can see in the source code [link](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/Exceptions/Handler.php#L185)

```
    protected function renderHttpException(HttpException $e)
    {
        $status = $e->getStatusCode();
        view()->replaceNamespace('errors', [
            resource_path('views/errors'),
            __DIR__.'/views',
        ]);
        if (view()->exists("errors::{$status}")) {
            return response()->view("errors::{$status}", ['exception' => $e], $status, $e->getHeaders());
        } else {
            return $this->convertExceptionToResponse($e);
        }
    }
```
You have the full exception available in each of the views, just under the name $e. And if you want do do a lot of extra calculations for all the error pages I would guide you to using the [view composers](https://laravel.com/docs/5.4/views#view-composers) where you can do something line this:

```
View::composer('errors.*, function ($view) {
            //
});
```
And add the data to all the error view, as well as designing a custom class to generating the view data.

Hope it helps a bit :)

**Comment by berkantipek** [comment]
@stefanoruth I see `parent::render()` line in `Exception.php` file follows to the `renderHttpException()` method. I can directly call it using `$this->renderHttpException()` in there but that method does render the current page into the error page. Despite, I need to navigate the `$exception` variable by **redirecting** to a certain page.

For view composers, I really want to know if [this line](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/Exceptions/Handler.php#L195) passes through Route Service Provider first or last? Can we access to vars defined there in service providers?

**Comment by stefanoruth** [comment]
Yeah okay redirecting to a specific page with the exception. Not sure how that is going to work well.

No from what i know of the view composers you can't pass variables into them, you can only fetch new stuff and set values.

**Comment by themsaid** [comment]
I'm closing this since it's not really an issue with the framework, please feel free to continue the discussion if you want.

**Comment by berkantipek** [comment]
Yes, you can think so but nobody didn't examine why Laravel can't handle $exception as flash data. What is the factor that causes this?
