### ISSUE TITLE
[PHP-FPM] 503 Service unavailable

### ISSUE THREAD

**Issue by smartdevth** [laravel/framework#19484]
- Laravel Version: 5.3
- PHP Version: PHP-FPM 7
- Database Driver & Version:
MySQL 5.5.31
### Description:
I use php-fpm 7 as main service, everything is fine (with anonymous user) until I logged in and redirect to some controller and get 503 service unavailable. I've found the cause, it is because of using Eloquent. when I remove the line which use eloquent model(such as Post::find(1)), everything goes fine again. Even the expression DB::select(DB:raw('...')) has no problem too.

Does eloquent use function or method which relate to login system or have I missed something ?

Thank you in advance.

**and here's the log from the server:**

```
php-fcm.log:
[05-Jun-2017 21:15:45] WARNING: [pool xxx] child 26096 exited on signal 11 (SIGSEGV) after 0.086954 seconds from start
[05-Jun-2017 21:15:45] NOTICE: [pool xxx] child 26098 started
[05-Jun-2017 21:15:45] WARNING: [pool xxx] child 26098 exited on signal 11 (SIGSEGV) after 0.085434 seconds from start
[05-Jun-2017 21:15:45] NOTICE: [pool xxx] child 26101 started

system message:
Jun  5 21:15:45 ns1 kernel: php-fpm70[26096]: segfault at xxxxxxxx ip 0000000000xxxxxx sp xxxxxxxxxxx error 6 in php-fpm70[400000+ac8000]
Jun  5 21:15:45 ns1 kernel: php-fpm70[26098]: segfault at xxxxxxxx ip 0000000000xxxxxx sp xxxxxxxxxxx error 6 in php-fpm70[400000+ac8000]

error log:
[Mon Jun 05 21:15:45.388275 2017] [proxy_fcgi:error] [pid 4552:tid 140202519xxxxxx] [client xxxxx] AH01067: Failed to read FastCGI header
```

### Steps To Reproduce:
1. Log user in
2. Redirect to some controller
3. Only controller with Eloquent usage will be shown 503 service unavailable

**Comment by themsaid** [comment]
Sorry but 5.3 is not supported anymore and this seems like a question more than a bug report, so please use the forums, I'm sure someone will be able to help you there.

**Comment by shojaeix** [comment]
i had this problem.and it's fixed after debug.
i had a limitless self-recall function. like this: 
`public function Test() {
       return $this->Test() ;
}`
