### ISSUE TITLE
Confusing Logic Hidden Properties Serializing Object

### ISSUE THREAD

**Issue by shrimpwagon** [laravel/framework#19482]
- Laravel Version: 5.2
- PHP Version: 5.6.30
- Database Driver & Version:

### Description:
A boolean property isn't being shown when serializing using toArray or toJson.

### Steps To Reproduce:
Nothing is being hidden or guarded in the object class.

    $obj = Eloquent::create(['boolean_field' => 1]);
    $obj->toArray();

**Comment by themsaid** [comment]
Sorry but 5.2 is not supported anymore, please upgrade to 5.4 and see if an issue still exists, if so please include more details so we can help fix if it's an actual issue.
