### ISSUE TITLE
buildMarkdownText() gives error Undefined variable: markdown in Mailable.php (line 226)

### ISSUE THREAD

**Issue by MPaap** [laravel/framework#19503]
- Laravel Version: 5.4.x latest
- PHP Version: 5.6.23

### Description:
buildMarkdownText() gives error Undefined variable: markdown in Mailable.php (line 226).
I follow the instructions to make a markdown mail like documented in the documentation and gives the above error.
I looked at the function and it looks broken, the markdown variable is not set before use.
`
protected function buildMarkdownText()
{
        return isset($this->textView)
                ? $this->textView
                : $markdown->renderText($this->markdown, $data);
    }
`

### Steps To Reproduce:
Fresh install
Try to send mailable

**Comment by MPaap** [comment]
#19504 Made a pull request

**Comment by themsaid** [comment]
Thanks :)
