### ISSUE TITLE
Handler::convertValidationExceptionToResponse: Call to method not covered by Validator interface

### ISSUE THREAD

**Issue by agi--** [laravel/framework#19502]
- Laravel Version: 5.4.24 and later
- PHP Version: 7.0 and above
- Database Driver & Version: not an issue here

### Description:
_Method_: \Illuminate\Foundation\Exceptions\Handler::convertValidationExceptionToResponse()
_Line_:

    $errors = $e->validator->errors()->getMessages();

_Should be_:

    $errors = $e->validator->getMessageBag()->getMessages();

_Why?_
ValidationException expects an instance implementing \Illuminate\Contracts\Validation\Validator (that is what at least the doc-block describes). But the above method calls  _errors()_ that is not covered by the interface, i.e. you can't use ValidationException for your own classes where only the methods requested by the interface are implemented. 

Either you add _errors()_ to the MessageProvider or you change the line as described above or you change the doc-block expecting a concrete instance of \Illuminate\Validation\Validator.

**Comment by themsaid** [comment]
There's little we can do about that at the moment since we don't want to break people apps, but in 5.5 we're going to check for this kind of stuff, I'm keep track of it.

Thank you :)

**Comment by agi--** [comment]
You know, I've made three suggestion how to fix this issue and truly one of them will break apps. For the other two I don't see any problem, but nevertheless, I'm thankful that you're considering to fix this in 5.5.
