### ISSUE TITLE
Allow multiple $dateFormat

### ISSUE THREAD

**Issue by bdsoha** [laravel/framework#19509]
- Laravel Version: 5.4
- PHP Version: 7.1

### Feature:
Wouldn't it be great if models would allow different date formats for different attributes. The `$dates` array can be rewritten to support attribute names as `keys` and formats as `values`.

```php
class MultipleDateFormats extends Model
{
    protected $dates = [
        'expiration' => 'm-y',
        'birthday'   => 'm-d-Y',
        'default_date'
    ];
}
```

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo. 

Thanks :)
