### ISSUE TITLE
Typecast not working on Relationships

### ISSUE THREAD

**Issue by maxgaurav** [laravel/framework#19510]
- Laravel Version: 5.4.24
- PHP Version: 5.6.30
- Database Driver & Version: MySql & 5.7

### Description:
In eloquent, when trying to typecast, I am unable to typecast a relationship. All dedicated columns and accessors are being typecasted but not the relationship content. 

The model has a **hasOne** relationship. If no relationship is found then the result is null but the content is not typecasted as an object when response is sent as JSON response from controller

### Steps To Reproduce:
Create a model of user and setup type casting for dedicated columns in database like is_admin and typecast a relationship 
````php
Class User extends Model
{
    use HasApiTokens, SoftDeletes;

    protected $casts = [
         'is_admin' => 'boolean',
         'user_profile' => 'object' //relatioship
       
    ];

    public function user_profile() 
    {
            return $this->hasOne(UserProfile::class);
    }
}
````

Return models response as JSON

````php
//in routes/web.php

Route::get('user/{id}', function($id) {
   $user = \App\User::with('user_profile')->find($id);
   return response()->json([
        'user' => $user
   ]);
});

````

### Expected behavior
The expected behavior I think should be that the null value returned from relationship should be typecasted as an object when received.
#### Result
Here is the actual result sent in response
````javascript
{
 "user": {
      "id": 1,
      "email": "user@email.com",
      "is_admin": true,
      "status": 1,
      "email_verified": true,
      "deleted_at": null,
      "created_at": "2017-06-07 09:26:18",
      "updated_at": "2017-06-07 09:26:18",
      "user_profile": null //getting null when no relation is found
    }
}
````

Expected Result when no relationship is found with typecasting
````javascript
{
 "user": {
      "id": 1,
      "email": "user@email.com",
      "is_admin": true,
      "status": 1,
      "email_verified": true,
      "deleted_at": null,
      "created_at": "2017-06-07 09:26:18",
      "updated_at": "2017-06-07 09:26:18",
      "user_profile": {}
    }
}
````

**Comment by Kunimaru** [comment]
json() returns json build by Symfony\Component\HttpFoundation\JsonResponse and passing data will be modified only by json_encode().
So, it is agenda about whether empty eloquent model's relations return object or not.
How do you think? @taylorotwell

**Comment by Dylan-DPC** [comment]
with returns `null` if relation is not found. This is intended behaviour and not a bug

**Comment by themsaid** [comment]
Casting is only applied to model attributes, not model relations. If you wish to cast null to an empty posted in a response you should use some kind of a transformer.

Check this out: https://github.com/spatie/laravel-fractal
