### ISSUE TITLE
Schema Builder, dropForeign method Inconsistency with documentation. 

### ISSUE THREAD

**Issue by lgalaz** [laravel/framework#19517]
- Laravel Version: 5.4
- PHP Version: 7.1
- Database Driver & Version: Mysql 5.7
(Using Homestead 5.3.2

###Description:
When in a migration, if you add a foreign key to an existing table you must drop the foreign key in the "down" method. 
In the Laravel documentation https://laravel.com/docs/5.0/schema#foreign-keys it specifies that you need to pass a string name to the dropForeign method: 
```$table->dropForeign('posts_user_id_foreign');```

However, this will fail.

### Steps To Reproduce:

In a migration, try to drop an index passing in a string.

you need to pass an array with the index name: 
```$table->dropForeign(['currency_id']);```

Also, it seems you can't pass an array of indexes to drop, but you need to execute "dropForeign" for each index.
It seems that Schema/Blueprint dropIndexCommand is used for dropping indexes too, and in other places.

**Comment by themsaid** [comment]
You can pass a string that represents the name of the foreign key, or an array that represents the column and Laravel will try to guess the name for you under the hood.

This works:

```
$table->dropForeign('posts_user_id_foreign');
```

But you need to make sure you pass the correct name for the foreign key.

**Comment by lgalaz** [comment]
:O

So sorry about that. I was positive that i was looking at the foreign key name -_-.

Thanks.
