### ISSUE TITLE
Auth::user()->all() return all records from users table.

### ISSUE THREAD

**Issue by Zedex7** [laravel/framework#19526]
- Laravel Version: 5.4
- PHP Version: 7
- Database Driver & Version: Mysql 5.7

### Description:
`Auth::user()->field_name` is supposed to give data of current logged in user, and its working fine. Today when tried to execute method `Auth::user()->all()` it returned me all records of users table. This is what I think might be issue for data security.

Output:
![screenshot from 2017-06-08 14-03-51](https://user-images.githubusercontent.com/14003108/26919446-59cad2d0-4c53-11e7-8a24-dbe28618c853.png)

### Steps To Reproduce:
I don't know as I am a beginner in Laravel, and don't have that much understanding of core framework.

**Comment by dotuancd** [comment]
I think it is ok.

**Comment by decadence** [comment]
It's intended: when you call on model instance method that doesn't exist it calls `Builder` method.
Therefore it's equals to `User::all()`

**Comment by Zedex7** [comment]
Thanks for all replies. As its only concerned at development side, it won't make any data security issue. Front End & End User doesn't have anything to do with this, so it can not be used to manipulate method for harmful objective. Closing Issue.
