### ISSUE TITLE
Eloquent weird bug or behaviour

### ISSUE THREAD

**Issue by ejlocop** [laravel/framework#19528]
- Laravel Version: 5.3.31
- PHP Version: 7.0.9
- Database Driver & Version: Ver 14.14 Distrib 5.7.12, for Win64 (x86_64)

### Description:
Guys i've got a question.
is this the default laravel behaviour to revert back to original `keyType` and `setkeyname` of the model after the first successful setting??

look at my relation code . oh and btw. i extended the laravel's default `belongsToMany` to change the related model's primaryKey. (notice the uid).
```
    public function conditions()
    {
        $this->setIncrementing(false);
        $this->setKeyType('string');
        $this->setKeyName('uid');

        $rel = $this->belongsToMany(\App\Models\MedCondition::class, 'condition_symptom', 'symptom_id', 'condition_id', null, 'uid')
                    ->withPivot('tags')
                    ->withTimestamps();
        // $this->setIncrementing(true);
        // $this->setKeyName('id');
        return $rel;
    }

```

so when i tried to use it.
```
$symp = MedSymptom::whereUid('1qMepFlgaV');
dd ($symp->get()->load('conditions')->get(1));
// of course, the expected result is correct and it loaded the `MedCondition`.
```

but when i tried to do it like this
```
$symp = MedSymptom::with('conditions')->whereUid('1qMepFlgaV'); // no results either.
// or in the model directly
protected $with = [
  'conditions',
]; // no results at all
// or 
$symp = MedSymptom::whereUid('1qMepFlgaV'); // has two results.
return $symp->get()->load('conditions'); // result is unexpected. (see screenshot)
```

[![blob](https://files.gitter.im/laravel/laravel/RplS/thumb/blob.png)](https://files.gitter.im/laravel/laravel/RplS/blob)

Thanks!

PS: i just extended the `Model` to add `setKeyType` method

**Comment by crynobone** [comment]
Don't see how this is not the expected behaviour.

When model fetch a collection of result, it need to pass each of the result to `new Model()`, since `$primaryKey` is not set globally then this is not pass down to each of the result.
