### ISSUE TITLE
Password requirements during registration should be applied during password reset

### ISSUE THREAD

**Issue by jhoff** [laravel/framework#19524]
In a default Laravel application, [RegisterController::validator](https://github.com/laravel/laravel/blob/master/app/Http/Controllers/Auth/RegisterController.php#L53) is defined in the "user-land" controller. It seems that the intention is to make it somewhat obvious to the developer how to change those requirements to suit their needs. For example, you might want to increase your password requirements ( currently min:6 ).

The password reset flow however has [PasswordResetController::rules](https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Auth/ResetsPasswords.php#L63) defined in the `ResetsPassword` trait, using a separately defined set of requirements for password ( same by default though ).

I imagine that most developers won't realize that if they change the password requirements in  `RegisterController`, that the end user will not have those same requirements applied during password reset by default.

As far as I can tell this isn't documented anywhere, but I feel like it might fall under the category of "potential security issue". At a minimum, maybe the `rules` method should be lifted out of the `ResetsPassword` trait and into `PasswordResetController` with possibly some notes in the docblocks and / or authentication documentation.

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.

**Comment by jhoff** [comment]
Thanks @themsaid :+1:
