### ISSUE TITLE
How to change the Laravel log file name???

### ISSUE THREAD

**Issue by juanpscotto** [laravel/framework#19523]
- Laravel Version: 5.4.25
- PHP Version: 7.0
- Database Driver & Version: 

### Description:

`
I can't use the \Illuminate\Foundation\Bootstrap\ConfigureLogging anymore. I want to override this function:

protected function configureDailyHandler(Application $app, Writer $log)
    {

        $log->useDailyFiles(
            $app->storagePath() . '/logs/customLogName.log',
            $app->make('config')->get('app.log_max_files', 5)
        );
    }

`

Can you help me please?

Thanks!

**Comment by juanpscotto** [comment]
Finally, I've got the answer. Add this in your app/bootstrap/app.php file:


```
$app->configureMonologUsing(function($monolog) use ($app) {
    $monolog->pushHandler(
        (new Monolog\Handler\RotatingFileHandler(
        // Set the log path
            $app->storagePath().'/logs/customLogName.log',
            // Set the number of daily files you want to keep
            $app->make('config')->get('app.log_max_files', 5)
        ))->setFormatter(new Monolog\Formatter\LineFormatter(null, null, true, true))
    );
});

```

That did the trick.

**Comment by themsaid** [comment]
Glad you figured it out, please post questions on the forums in the future, there's more chance you get answers there than here :)
