### ISSUE TITLE
route helper method with prefix

### ISSUE THREAD

**Issue by shyandsy** [laravel/framework#19534]
- Laravel Version: 5.4.25
- PHP Version:7.1
- Database Driver & Version:MYSQL 5.6

### Description:
```
$url = route('routeName', $params);
```
this function can be used to get the url of route

problem is what if i wanna get a route name under a group prefix?

for example : 
```
Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function () {
    Route::get('/', 'HomeController@index')->middleware("admin");
    //Route::get('/home', 'HomeController@index');
    Route::get('login', 'Auth\LoginController@showLoginForm');
    Route::post('login', 'Auth\LoginController@login');
```

how can I  get url of login? and how  can i get url of /?

**Comment by ahmadaljazzar** [comment]
I don't know If I got you right, but you can name the **login** route, and call it using the `route` helper function.

```
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
```

And then 

```
$url = route('login');
```

**Comment by shyandsy** [comment]
so what if i use group route with prefix？

发自我的 iPhone

**Comment by joshmanders** [comment]
Prefix doesn't matter on the group. You can name a group and if I am correct it'll prefix your routes with that name.

```php
Route::group(['name' => 'api'], function() {
  Route::get('/', 'MyController@method')->name('home');
});
```

Would be accessible via `route('api.home');`

**Comment by themsaid** [comment]
Thanks @ahmadaljazzar and @joshmanders, hope this is sorted out now

**Comment by shyandsy** [comment]
@joshforbes 
it still not working in 5.4.25
```
Route::group(['name' => 'admin', 'prefix' => 'admin'], function () {
    Route::get('/', 'HomeController@index')->middleware("admin")->name('home');
    Route::post('calculate',  'HomeController@calculate')->name('calculate');     //计算器api

    //Route::get('/home', 'HomeController@index');
    Route::get('login', 'Admin\Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login')->name('login');
});
```

it  generates the route name without admin. prefix
![image](https://user-images.githubusercontent.com/5271457/26987829-a0fd1cfc-4d12-11e7-8b40-8c10308c7656.png)

obviously, it make no sense

**Comment by niksumeiko** [comment]
@joshmanders, @shyandsy, in Laravel 5.4 instead of `name` for a Group, we shall use `as` property. Then named routes will be prefixed:

```php
Route::group([
  'as' => 'api.' // Notice trailing dot, it's on purpose.

], function() {
  Route::get('/', 'MyController@method')->name('home');
});
```

Child route now shall be accessible via `route('api.home')` helper.

Route names are also visible in `php artisan route:list` after clearing its cache (via `php artisan route:clear`).
