### ISSUE TITLE
Collections don't support whereNotIn

### ISSUE THREAD

**Issue by kevinfoley** [laravel/framework#19535]
- Laravel Version: 5.4.11
- PHP Version: 5.6.30

### Description:
The [Laravel 5.4 documentation ](https://laravel.com/docs/5.4/collections#method-wherenotin)says that Collections support `whereNotIn`, but calling `whereNotIn()` on a collection produces 

> exception 'BadMethodCallException' with message 'Method whereNotIn does not exist.'

### Steps To Reproduce:

    $collection = collect($array);
    $rowsToUpdate = $collection->whereIn('id', $existingIDs); //works
    $rowsToInsert = $collection->whereNotIn('id', $existingIDs); //throws BadMethodCallException

**Comment by guidocella** [comment]
It was added in v5.4.14.

**Comment by kevinfoley** [comment]
@guidocella  Since that isn't mentioned in the [release notes](https://laravel.com/docs/5.4/releases) or in the documentation itself, where would we go to find that kind of information? I'm not used to new features being added in patch versions.

**Comment by decadence** [comment]
It's mentioned it laravel/framework repo.
https://github.com/laravel/framework/blob/5.4/CHANGELOG-5.4.md#v5414-2017-03-01
