### ISSUE TITLE
Two broadcasting auth routes for different middleware

### ISSUE THREAD

**Issue by mediaceh** [laravel/framework#19548]
- Laravel Version: 5.3.#
- PHP Version:
- Database Driver & Version:

How i can define two broadcasting auth routes for web middleware and api middleware?

I can define  `Broadcast::routes();` for web or  `Broadcast::routes( [ 'middleware' => [ 'api', 'jwt.auth' ] ] );` for api. But it doesn't work common.

**Comment by mediaceh** [comment]
For what it add default web middleware to broadcasting auth route? 

`public function routes(array $attributes = null)
    {
        if ($this->app->routesAreCached()) {
            return;
        }

        $attributes = $attributes ?: ['middleware' => ['web']];

        $this->app['router']->group($attributes, function ($router) {
            $router->post('/broadcasting/auth', BroadcastController::class.'@authenticate');
        });
    }`

**Comment by mediaceh** [comment]
oK, i deleted default web middleware and added parse user from token to broadcast auth callback.
`
	Broadcast::channel('App.User.*', function ($request, $userId) {

            $result = (int) $request->user()->id === (int) $userId;
			
			if($result) {
			
				return $result;
				
			}
			else {
			
				$user = \Tymon\JWTAuth::parseToken()->authenticate();
				
				if($user) {
					
					$request->setUserResolver(function () use ($user) {
						return $user;
					});
					
					return (int) $user->id === (int) $userId;;
				
				}
			
			}
			
			return false;
			
        });
`

`public function routes(array $attributes = null)
{
if ($this->app->routesAreCached()) {
return;
}

    $attributes = [];

    $this->app['router']->group($attributes, function ($router) {
        $router->post('/broadcasting/auth', BroadcastController::class.'@authenticate');
    });
}`

**Comment by Kyslik** [comment]
This is not StackOverflow, this will get closed ASAP.

>**Note**: you can edit your posts on GH so no need to post multiple times.

**Comment by mediaceh** [comment]
Oh really? The fact that I can not use Broadcasting for Api and the Web at the same time is not a bug? So it's planned?
This information is for other users. If you do not like it, do not read it.

**Comment by joshmanders** [comment]
You should ask this on the forums.
