### ISSUE TITLE
Cannot mock laravel contracts in constructor of commands using mockery

### ISSUE THREAD

**Issue by darcyrush** [laravel/framework#19544]
- Laravel Version: 5.4.24
- PHP Version: 7.1.5
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.7.18

### Description:

Not sure if I am making a basic mistake. I can mock Laravel contracts and facades that are resolved by the Laravel container in the `handle()` method but not the constructor of a class that extends Laravel's `Illuminate\Console\Command` class. 

### Steps To Reproduce:

Basic mockery mock;

```
use Mockery as m;
use Illuminate\Contracts\Filesystem\Factory as File;

class myClassTest
{
    public function my_test()
    {
        $mock = m::mock(File::class);
        $mock->shouldReceive('put')->once();
        $this->app->instance(File::class, $mock);

        $this->artisan('call-my-command');
    }
}
```

Using the code below and inspecting `$file` in the constructor gives `Illuminate\Config\Repository`

```
use Illuminate\Console\Command;
use Illuminate\Contracts\Filesystem\Factory as File;

class MyClass extends Command
{
    public function __construct(File $file)
    {
        parent::__construct();
        $this->file = $file;
    }

    public function handle()
    {
        $this->file->put('/here.txt', 'stuff');
    }
}
```

Using the code below and inspecting `$file` in the `handle()` method gives `Mockery_3_Illuminate_Contracts_Config_Repository` as expected

```
use Illuminate\Console\Command;
use Illuminate\Contracts\Filesystem\Factory as File;

class MyClass extends Command
{
    public function handle(File $file)
    {
        $file->put('/here.txt', 'stuff');
    }
}
```

I am injecting other classes into `handle()` so I would like to keep the Laravel contracts being injected into the constructor. It works when running the command - its just the mocks that are not working in the constructor.

What am I missing?

**Comment by themsaid** [comment]
Please ask on the forums. This repo is for bug reporting only.
