### ISSUE TITLE
php artisan key:generat worked...

### ISSUE THREAD

**Issue by xyluz** [laravel/framework#19549]
- Laravel Version: 5.4.25
- PHP Version: PHP 7.1.3-2+deb.sury.org~xenial+1 (cli)
- Database Driver & Version: PHP 7.1.3-2+deb.sury.org~xenial+1 (cli)

### Description:
Is this supposed to happen? php artisan key:generat worked.
![selection_033](https://user-images.githubusercontent.com/13081285/26998241-5b109450-4d79-11e7-9407-3f217b5c9989.png)

### Steps To Reproduce:
Run php artisan key:generat

**Comment by gmsantos** [comment]
Yes, symfony console allow shorting command names.

This also works too:

```
key:gen
ke:genen
```

An so on...

**Comment by eskrano** [comment]
You can use `php artisan k:g` too :)

**Comment by xyluz** [comment]
Awesome. :laughing:  now everyone knows I am still a learner...

**Comment by gmsantos** [comment]
You can close this issue now @xyluz

**Comment by m1guelpf** [comment]
Wait, why isn't this documented?

**Comment by gmsantos** [comment]
It is [documented on Symfony ](http://symfony.com/doc/current/components/console/usage.html#shortcut-syntax)
