### ISSUE TITLE
asset helper function bug

### ISSUE THREAD

**Issue by mohamadnorouzi20** [laravel/framework#19556]
- Laravel Version: 5.4.25

### Description:
I'm trying to share my application via [ngrok.io](http://ngrok.io). I'm using `asset` helper function in my templates and it returns the urls based on my local domain (which cannot be reached by other people) even though I've set `APP_URL` value in my .env file to another address on ngrok. What's interesting is when i use `artisan tinker` the `asset` function returns the correct url based on `APP_URL` value.

**Comment by themsaid** [comment]
Please ask on the forums, sharing with ngrok works fine with me, might be a mis-configuration in any of your files, so better use the forums as you'll have a better chance being answered there, this repo is for bug reporting only.
