### ISSUE TITLE
Mix exceptions during tests

### ISSUE THREAD

**Issue by mathieutu** [laravel/framework#19552]
Hi guys,

I have a problem with the `mix()` function.
When I'm executing my tests, especially with travis I don't run all the webpack stuff: I don't need it, as I'm just testing controllers, services, etc. 

Not Js and css things.

BUT, when I'm trying to make a `get` on a route which return a view, I always have a an exception from the mix() helper method.

Example : 

```php
Route::get(/foo, function () { return view('bar'); }

$response = $this->get('/foo');
$response->assertViewIs('bar');
```

Will throw a `The Mix manifest does not exist.` exception.

This is really annoying to have to compile assets we don't need..!

And we can't overwrite, or mock, or anything, because this is not part of the container or something like that, but just a basic function.

Maybe we can make a service for that, and just do:
```php
function mix($path, $manifestDirectory = '')
{
    return app('mix')->mix($path, $manifestDirectory);
}
```
in helpers.php

It will permit to mock it in tests:
```php
app()->bind('mix', function () {
    return Mockery::mock(Mix::class)->shouldReceive('mix')->andReturn('')->getMock();
});
```
or something like that.

I can make a PR if you want.

For now, I've just made this bad thing to fix it:
```php
// New function which is called instead of mix in my views...
function mix_except_in_tests($path, $manifestDirectory = '') {
    if  (app()->runningUnitTests()){
        return '';
    }

    return mix($path, $manifestDirectory);
}
```
This is also a (quickest and dirtiest) option, but I think it may create conflict with Dusk, no? (I don't use it personnally.)

Thx,
Matt'
- Laravel Version: 5.4.25

**Comment by themsaid** [comment]
feel free to open a PR or for suggestions and feature requests please use the https://github.com/laravel/internals repo.
