### ISSUE TITLE
Filtered relationships creation

### ISSUE THREAD

**Issue by chimit** [laravel/framework#19558]
- Laravel Version: 5.4
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7

### Description:
I have a "Many to Many" relationships with a pivot table. This pivot table has an additional field (`flag` in my case). Relationships have conditions based on this `flag` field:

Device model:
```php
public function users()
{
    return $this->belongsToMany('App\User')
                ->wherePivot('flag', 1)
                ->withTimestamps();
}
```
I create new relationships between Device and User:
```php
$device->users()->syncWithoutDetaching([$user->id]);
```
After that I'm expecting a new row in the pivot table with `flag=1`, but I get the default value `flag=NULL`.

So the only way to reach this is to specify `flag=1` explicitly:
```php
$device->invitedUsers()->syncWithoutDetaching([
    $user->id => [
        'flag' => 1,
    ]
]);
```
I'm not sure it's a bug, but it works not as user may expect.

**Comment by themsaid** [comment]
Yes the condition on a fetch query doesn't automatically be used on insert/update queries, you need to handle that yourself.
