### ISSUE TITLE
Order of Middleware Issue

### ISSUE THREAD

**Issue by cham11ng** [laravel/framework#19565]
In **web.php** I've switched Postgres schemas in middleware as the subdomain type of HTTP request is made. This way:

    Route::group(
        [
            'domain'     => '{tenant}.' . config('app.url'),
            'middleware' => 'select-schema'
        ],
        function () {
            $this->get('/', 'HomeController@index')->middleware('auth');
        }
    );

In **select-schema** middleware, I do something like this. This works correctly. (don't worry)

    DB::select('SET search_path TO ' . {tenant});

My main problem is that: I've different `migrations` for `public` schema and for any `individual tenant`. In `individual tenant` I have `users` table. As soon I'm logged in it pop up this error.

> SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "users" does not exist

**The main issue is**

    $this->get('/', 'HomeController@index')->middleware('auth');

The model works well but middleware `auth` execute first before  `select-schema`

**How do I order?** `select-schema` then `auth`

**Comment by themsaid** [comment]
You can update the `$middlewarePriority` in your App\Kernel.

Check the original order in `Illuminate\Foundation\Http\Kernel` before you proceed.

**Comment by cham11ng** [comment]
I didn't knew its existence. Thank you so much.

**Comment by juan-cortes** [comment]
This has since moved to `Router.php` in case someone is looking

**Comment by javierojeda94** [comment]
I think this should be in the docs, it is very helpful

**Comment by majuansari** [comment]
$middlewarePriority seems to be not used in laravel 5.5 . Do we have any other solutions here ?

**Comment by ArthurRM** [comment]
@majuansari it works for me in 5.7 and 5.8
