### ISSUE TITLE
SQLite is prefixing the table prefix twice when calling `Schema::hasColumn('donation' ,'id');`

### ISSUE THREAD

**Issue by Jossnaz** [laravel/framework#19564]
- Laravel Version: 5.3.31
- PHP Version: 7.0

- Database Driver & Version:
sqlite 3

### Description:

public/caup_laravel/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php

Line 115 ish in function

`getColumnListing()`

I debugged like this:

`dd($this->grammar->compileColumnExists($table));`

result

pragma table_info("prfx_prfx_donation")

### Steps To Reproduce:

be sure to set a prefix in database.php config

**Comment by themsaid** [comment]
5.3 is not supported anymore, please upgrade.

**Comment by Jossnaz** [comment]
Is it fixed in 5.4?
