### ISSUE TITLE
Queue not working (L 5.4)

### ISSUE THREAD

**Issue by mitajunior** [laravel/framework#19577]
- Laravel Version: 5.4
- PHP Version: 7
- Database Driver & Version: psql (PostgreSQL) 9.3.16

### Description
Trying to get jobs to queue with database driver, in sync everything works well but you know, that's not what we want.

If I switch to database queue driver (cache clear and everything) nothing happens, the jobs table is empty

What could be the issue?

### Steps To Reproduce:

- Change queue driver to 'database'

- Clear config cache

- Run `php artisan queue:table`

- Run `php artisan migrate`

- Create a queued job and dispatch

Voila!! Nothing happens, job is not queued, table empty etc

What could be the issue?

**Comment by themsaid** [comment]
The queue system works fine, please ask on the forums, you might get better help there.

**Comment by JohanIskandar** [comment]
if you are using laravel 5.7 or above
in your .env
QUEUE_CONNECTION=database
