### ISSUE TITLE
Storage::URL() returns the URL with '/storage/' appended in front.

### ISSUE THREAD

**Issue by alexandruantochi** [laravel/framework#19571]
- Laravel Version:  5.4
- PHP Version: 7
- Database Driver & Version: 

### Description:

Calling Storage::URL returns the path of the file with '/storage/' appended in front, but only in artisan tinker

### Steps To Reproduce:

Storage::URL(config('constants.PROJECT_LIST')."myfile"))

returns 

/storage/C:\path\to\my\file\myfile

only in artisan tinker; doesn't work while the app is running (debug shows /storage/myfile only)

**Comment by themsaid** [comment]
Please share more information about your issue, nobody can guess what's stored in your `config('constants.PROJECT_LIST')`, please share an example we can copy and paste in a fresh laravel installation to understand your issue.

**Comment by alexandruantochi** [comment]
Looks like it was some weird behavior from artisan tinker as I can not reproduce it.
