### ISSUE TITLE
Queue:work failed job not being pushed to failed jobs table

### ISSUE THREAD

**Issue by ArtSintop** [laravel/framework#19576]
- Laravel Version: 5.4.23
- PHP Version: 7.1.0
- Database Driver & Version:

### Description:
When I use laravel Queue:work with a limited amount of tries, with a failing job, it does not write to the failed jobs table. The CLI shows Processing of the job x amount of times. 

### Steps To Reproduce:
1.run php artisan queue:work --env=queue --tries=10 --memory=512
2. Queue an event listener.
3.Throw an exception on the event.
4. Dispatch the event

**Comment by themsaid** [comment]
Sorry but my worker seems to work as expected, you need to debug further into your application error logs to see why it failed to write to the database table.

**Comment by ArtSintop** [comment]
When i changed the static::events()->fire to static::events()->dispatch inside lluminate\Queue\FailingJob, this seemed to solve my issue.

**Comment by themsaid** [comment]
`fire()` is just an alias for `dispatch()`, it doesn't make any sense.
