### ISSUE TITLE
Left join select issue

### ISSUE THREAD

**Issue by maciejbuchert** [laravel/framework#19572]
- Laravel Version: 5.4.25
- PHP Version: 5.6.4
- Database Driver & Version: MySQL 5.5.55

### Description:
I've got mysql query:

```
$tournaments = DB::table('tournaments')->select(DB::raw('tournaments.id, name, start_date, end_date, slots, registration_end_date, registration_start_date, opened, count(tournament_id) AS occ'))->leftJoin('tournament_registrations', 'tournaments.id', '=', 'tournament_registrations.tournament_id')->get();
```

but I getting this error:

`Syntax error or access violation: 1140 Mixing of GROUP columns (MIN(),MAX(),COUNT(),...) with no GROUP columns is illegal if there is no GROUP BY clause`

**Comment by themsaid** [comment]
Please ask on the forums.
