### ISSUE TITLE
Timeout settings not kill job in queue Laravel 5.4

### ISSUE THREAD

**Issue by uapixart** [laravel/framework#19584]
- Laravel Version: 5.4.25
- PHP Version: 7.0.15
- Database Driver & Version:

### Description:
Timeout settings not kill job in queue:
```shell
# php artisan queue:work --queue=sms --timeout=10 --delay=60 --tries=3
[2017-06-13 16:04:11] Processing: App\Jobs\SendAction
[2017-06-13 16:04:28] Processed:  App\Jobs\SendAction
```
I also pass timeout in Job:
```php
class SendAction implements ShouldQueue
{
    ....
    public $timeout = 5;
    ....
    public function handle()
    {
        for ($x = 0; $x <= 1000000000; $x++) {
            $b = 1+1;
     } // time for execution 16-18 sec
     ....
}
```
My config for queue:
```php
	'database' => [
            'driver' => 'database',
            'table' => 'jobs',
            'queue' => 'default',
            'retry_after' => 60,
        ],
```

**Comment by dbpolito** [comment]
You need `pcntl` php module for this to work... To confirm you have it run:

````bash
$ php -m | grep pcntl
````

You should receive `pcntl` as return.

**Comment by dbpolito** [comment]
There is no mention of this on the docs, might be a good addition there.

**Comment by sisve** [comment]
Timeouts _also_ require PHP 7.1 to work. 

Ref: [Worker::registerTimeoutHandler](https://github.com/laravel/framework/blob/bd858cc8b18d26ce00a6c5dbf893c4e4f20d7b9b/src/Illuminate/Queue/Worker.php#L132-L146)
Ref: [Worker::supportsAsyncSignals](https://github.com/laravel/framework/blob/bd858cc8b18d26ce00a6c5dbf893c4e4f20d7b9b/src/Illuminate/Queue/Worker.php#L531-L535)

**Comment by uapixart** [comment]
Thanks!!! Work fine I have already installed pcntl, update php to PHP 7.1.6 and now it works fine, proccess kill and I restart it by Supervisor!

**Comment by themsaid** [comment]
Please open a PR in the docs repo, thanks everyone.
