### ISSUE TITLE
Route::auth is not working in Route::group how can i fix it?

### ISSUE THREAD

**Issue by dev10calypso** [laravel/framework#19581]
- Laravel Version: 5.4
- PHP Version: 7
- Database Driver & Version: mysql

### Description:
i got problem with Route::auth is not working in Route::group

`Route::group(['domain' => '{slug}.mydomain.com', 'middleware' => ['systemConfig']], function () {
    Auth::routes();
});`
in systemConfig middle i've config new database connection then i've change connection in user model after use Auth in group is not working then showing Error

(1/1) UrlGenerationException
`Missing required parameters for [Route: login] [URI: login].
help me fix this problem please`

**Comment by themsaid** [comment]
Please ask on the forums.
