### ISSUE TITLE
Please add intersect method to Request

### ISSUE THREAD

**Issue by papi83dm** [laravel/framework#19585]
- Laravel Version: 5.5.dev
- PHP Version:
- Database Driver & Version:

### Description:
The intersect method was removed from framework/src/Illuminate/Http/Concerns/InteractsWithInput.php 

### Steps To Reproduce:
$request = New Request();
$request->intersect($arraydata);

**Comment by devcircus** [comment]
Make a request macro that takes the keys then does:
```php
return array_filter($this->only(is_array($keys) ? $keys : func_get_args()));
```

**Comment by devcircus** [comment]
Looks like a lot of thought and discussion went into its removal.
https://github.com/laravel/framework/pull/18695

**Comment by themsaid** [comment]
Check https://github.com/laravel/framework/pull/18695

**Comment by intpro** [comment]
A fluid validation method can be used in some cases as an intersection:
$article->fill($request->validate([
            'release' => 'date',
            'category_id' => 'exists:categories,id',
            'title' => 'string|max:255',
            'preview' => 'string'
        ]));
