### ISSUE TITLE
validator "required" leads to ERR_TOO_MANY_REDIRECTS error 

### ISSUE THREAD

**Issue by shyandsy** [laravel/framework#19589]
- Laravel Version: 5.4.25
- PHP Version:7.1
- Database Driver & Version:mysql

### Description:
the validator "required" leads to ERR_TOO_MANY_REDIRECTS error if the parameter doesnt exists

### Steps To Reproduce:
1.create a controller with index action (such as SearchController)
2.add route for that action (such as /search)
3.add the following validate code to the index action
```
$this->validate($request, [
            'new' => 'required|boolean',
]);
```
GET /search?new=1     its fine, no problem
GET /search                  it leads to ERR_TOO_MANY_REDIRECTS error

**Comment by themsaid** [comment]
Please ask on the forums, `validate()` throws a `ValidationException` which is handled in the exception handler and converted to a redirect response:

```
return redirect()->back()->withInput(
            $request->input()
        )->withErrors($errors);
```

You can read more about rendering exceptions in https://divinglaravel.com/exception-handler/rendering-exceptions

**Comment by shyandsy** [comment]
@themsaid 
yes,  i would use try catch to figure out that. but i still amazing
1.why the exception leads ERR_TOO_MANY_REDIRECTS
2.why "required" rule make exception? rather than error message like "boolean"

**Comment by danielleplatt95** [comment]
@shyandsy did you ever get to the bottom of this?
