### ISSUE TITLE
Migration error when changing a column while a JSON column exists in a table

### ISSUE THREAD

**Issue by adrielpdeguzman** [laravel/framework#19580]
- Laravel Version: 5.4.17
- PHP Version: 7.1.5 (cli)
- Database Driver & Version: mysqlnd 5.0.12-dev - 20150407

### Description:
I am aware that JSON columns cannot be "changed()", as mentioned on the documentation. However, it seems that when a table contains at least 1 JSON column, "change()ing" other columns produces the error below:

`[Doctrine\DBAL\DBALException]
  Unknown database type json requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.`

Is this behavior intended, or is there something that I can do to fix this?
### Steps To Reproduce:

1. Create a migration to create a table with an integer and a json column
2. Create a migration to add nullable()->change() to the integer column
3. Run php artisan migrate

**Comment by themsaid** [comment]
Same as in https://github.com/laravel/framework/issues/1186, it's a doctrine issue unfortunately.

**Comment by imrealashu** [comment]
any workaround so far ?
