### ISSUE TITLE
supervised queue:work , Storage::delete($paths) always return false

### ISSUE THREAD

**Issue by sureshamk** [laravel/framework#19583]
- Laravel Version: 5.4.*
- PHP Version: 5.6.21
- Storage Disk : Rackspace
- OS : Red Hat Enterprise Linux Server release 6.9 (Santiago)

### Description:
I'm running the queue work process via the following supervisor config (I'm using Database queue)
```
[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/myApp/artisan queue:work  --sleep=3 --tries=3
autostart=true
autorestart=true
user=apache
numprocs=8
redirect_stderr=true
stdout_logfile=/var/www/myApp/storage/logs/worker.log
```
I’ve created job , which will remove files from rackspace container. Job class will utilise the following method which will receive a array contains paths of files,  for example `$param =  [ 'path/to/file/1.pdf', 'path/to2/file/2.pdf'];`

   ```
    /**
     * @param an array of files to remove from the disk:
     */
    public function deleteImage($param)
    {
        Log::debug('DELETE_IMAGE => Entering with data ', $param);

        if (is_array($param)) {
            //------------------------------------------------------
            $result = Storage::delete($param);
           //-------------------------------------------------------
             Log::debug('DELETE_IMAGE => Delete Result ', [$result]);
            if ($result) {
                 Log::debug('DELETE_IMAGE => Delete DONE ', [$result]);
                return true;
            } else {
                 Log::debug('DELETE_IMAGE => Delete Failed , Gonna retry ', [$result]);
                throw  new UnknownError();
            }
        }
        
    }

```
When i dispatch the job, its start executing by the supervisor's created php process, 
I am able to see the _debug logs_ in _laravel.log_ file.
I am sure files are presented in rackspace container as per given path. If I run `php artisan queue:work` files are getting deleted from rackspace, but when I start from supervisord its keep on failing.

#### Log file reference 

_

> local	 Debug	13:07:34	
> DELETE_IMAGE => Delete Failed , Gonna retry [false]
> 
> local	 Debug	13:07:34	
> DELETE_IMAGE => Delete Result [false]
> 
> local	 Debug	13:07:31	
> DELETE_IMAGE => Entering with data ["/path/to/file/1.pdf","path/to2/file/2.pdf"]

_

### Assurance 
- Files are available in rackspace as paths given in array input
- If I restart supervisor ~1day it was worked well , after  `Storage::delete($param)` always returns `false`
- `php artisan queue:work` - this command processing perfectly when I do it manually in terminal

**Comment by themsaid** [comment]
Sorry but please ask on the forums, this repo is for bug reporting only.
