### ISSUE TITLE
php artisan Option Shortcuts issue `The "--L" option does not exist.`

### ISSUE THREAD

**Issue by fbens** [laravel/framework#19594]
- Laravel Version: 5.4.23
- PHP Version: 7.1.4
- Database Driver & Version: MySQL 5.7

### Description:
When I use `Option Shortcuts` in my artisan console `$signature`，it tips like below
```php
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class BaiduPush extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'baidu:push {id?} {--L|limit=2000}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Push the url to Baidu Webmaster';


    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        dd($this->options());
    }
}

```

run `php artisan baidu:push --L=2000`, output:

```

[Symfony\Component\Console\Exception\RuntimeException]
  The "--L" option does not exist.

```
but the offical document show this method 
 link https://laravel.com/docs/5.4/artisan#registering-commands (see section `Option Shortcuts` )

**Comment by themsaid** [comment]
should be `php artisan baidu:push -L=2000`

**Comment by fbens** [comment]
@themsaid 
Thank you very much, but the official documentation does not mention that.
Hope will be mentioned in the official documentation

**Comment by decadence** [comment]
@fbens it won't be mentioned unless you make PR to docs next time.

**Comment by decadence** [comment]
Actually it won't be mentioned anyway :D

**Comment by decadence** [comment]
Looks like people are supposed to know everything about Symfony Console while reading docs about Artisan

**Comment by NisalG** [comment]
Yes, same with: `php artisan migrate -–database=sqlite_testing`

**Comment by nickpoulos** [comment]
No need for '=' sign in the option values either, they will get included in $this->option('key'). I would use the following: 

`php artisan baidu:push -L 2000`

**Comment by Hostname47** [comment]
When I define a shortcut with more than character like the following:
`protected $signature = 'quote:display {quote=This is default quote} {--opt|option_A="default option value"}';`
and run the command using the following command: 
`php artisan quote:display "The quote That I had" -opt="Doamn it !"`
I get an error : 

> The "-o" option does not exist.

I just want to know why ? is that because I only have to name my shortcuts with one character or the artisan take it from cache !!
Thanks.
