### ISSUE TITLE
Why Route::any didn't have "OPTIONS".

### ISSUE THREAD

**Issue by ThunderBirdsX3** [laravel/framework#19605]
- Laravel Version: 5.4.26
- PHP Version: 7.1.5
- Database Driver & Version: MySQL 5.7.18

### Description:
I use `Route::any` and  try to see Method with `php artisan route:list` .

It has only `GET|HEAD|POST|PUT|PATCH|DELETE`. Why not have `OPTIONS`?

**Comment by themsaid** [comment]
this repo is not for question, please use the forums instead.

Also a quick search before posting questions can help :)

check https://github.com/laravel/framework/issues/18070
