### ISSUE TITLE
Auth password reset expects $request->email

### ISSUE THREAD

**Issue by TerrePorter** [laravel/framework#19617]
- Laravel Version: 5.4.23
- PHP Version: PHP 7.1.2-3+deb.sury.org~xenial+1 (homestead 2.0.0)
- Database Driver & Version: default

### Description:

I have a brand new install of Laravel with the auth installed.

I'm getting an error when using the auth password reset link. The route expects only a token, https://github.com/laravel/framework/blob/5.4/src/Illuminate/Routing/Router.php#L1023, but the controller function expects $request->email, https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/Auth/ResetsPasswords.php#L26

The reset link in the email that is sent returns a error: ErrorException in ResetPasswordController.php line 68: Undefined property: Illuminate\Support\Facades\Request::$email

### Steps To Reproduce:
Install Laravel, Install auth. Create account. Send reset password. Click link in email

**Comment by themsaid** [comment]
> ResetPasswordController.php line 68

Laravel auth scaffold doesn't use the Request facade, looks like it's some code customization on your end, the password reset form works fine on a fresh installation, please check your code.
