### ISSUE TITLE
Laravel Eloquent doesn't delete model

### ISSUE THREAD

**Issue by luizguilhermefr** [laravel/framework#19626]
- Laravel Version: 5.3.*
- PHP Version: 7.0
- Database Driver & Version: MySQL Ver 14.14 Distrib 5.7.18, for Linux (x86_64)

### Description:
I have a table known as identifier table, which has the primary key as a foreign key to another table:

```
[TABLE 1] id (PK) ..attributes
[TABLE 2] table1_id (PK, FK) ...attributes
```

I already defined on "TABLE 2" model the attribute $primaryKey = table1_id.

When I try to delete table 2 record, the return value is true, but nothing happens.

I've tried it three ways:

`$table1->table2()->delete()`

`Table2::where('table1_id', $table1_id)->delete()`

`Table2::find($table1_id)->delete()`

and

`DB::table('table2')->where('table1_id', $table1_id)->delete()`

And both three return true, but nothing really happens.

**Comment by themsaid** [comment]
5.3 is not supported anymore, please upgrade to 5.4.

**Comment by luizguilhermefr** [comment]
Just updated and still reproducible. Please reopen.

**Comment by themsaid** [comment]
Use the query log to see what queries are running behind the scenes, cause deleting models seems to be working fine.

**Comment by luizguilhermefr** [comment]
Seems like the `id` passed to the query is `?`.

**Comment by luizguilhermefr** [comment]
Even if I pass the id directly, on the query it is replaced by `?`.

e.g:

`Table1::where('table1_id', 2)->delete();`

**Comment by themsaid** [comment]
No it's just the prepared query string, can you please share it here?

**Comment by themsaid** [comment]
Also can you please share the table schema?

**Comment by luizguilhermefr** [comment]
Sure.

Trying with `$deleted = $store->ftp->delete();`

The latest query entry is:

```
Object {query: "delete from `ftp_users` where `store_id` = ?", bindings: Array(1), time: 3.9}.
```

Trying with directly passed id: `$deleted = FtpUser::find(2)->delete();`

The latest query entry is pretty much the same:

```
Object {query: "delete from `ftp_users` where `store_id` = ?", bindings: Array(1), time: 4.6`
```

**Comment by luizguilhermefr** [comment]
The schema is like:

```
[stores]
id int (PK)
... etc
```

```
[ftp_users]
store_id int (PK, FK)
... etc
```

**Comment by luizguilhermefr** [comment]
Additional information: I have other cases like this working perfectly on deletion.

**Comment by devcircus** [comment]
The ? is just a placeholder for the value. The actual values passed are in the bindings.

**Comment by luizguilhermefr** [comment]
The binding value is correct. The passed id. All seems like the laravel is doing the trick. But the database doesn't get affected.

**Comment by themsaid** [comment]
I don't think this is laravel related, deleting seems to be fine and the query coming out of laravel seems to be fine, can't replicate your issue in the most recent 5.4 installation using the same schema you shared, looks like something might be wrong in your environment.
