### ISSUE TITLE
Soft deletes failing without updated_at column

### ISSUE THREAD

**Issue by mcblum** [laravel/framework#19620]
- Laravel Version: 5.4.26
- PHP Version: 7.1
- Database Driver & Version: MySql 5.7

### Description:
After updating to 5.4.26 one test began failing because we don't have timestamps in the table in which we are soft deleting. Appears to be because of:

```
  protected function runSoftDelete()
    {
        $query = $this->newQueryWithoutScopes()->where($this->getKeyName(), $this->getKey());

        $time = $this->freshTimestamp();

        $this->{$this->getDeletedAtColumn()} = $time;
        $this->{$this->getUpdatedAtColumn()} = $time;

        $query->update([
            $this->getDeletedAtColumn() => $this->fromDateTime($time),
            $this->getUpdatedAtColumn() => $this->fromDateTime($time),
        ]);
    }
```

### Steps To Reproduce:
- Create a table with no timestamps but soft deletes
- Try to soft delete something

Thanks all!

**Comment by themsaid** [comment]
Thanks, I've pushed a fix in https://github.com/laravel/framework/pull/19627

**Comment by mcblum** [comment]
Thanks @themsaid and @taylorotwell

**Comment by themsaid** [comment]
:) welcome
