### ISSUE TITLE
Storage::copy doesn`t work with external links 

### ISSUE THREAD

**Issue by Malin88** [laravel/framework#19625]
- Laravel Version: 5.4.26
- PHP Version: 7.1

### Description:

I want to copy images from remote address. In previous laravel version `Storage::copy` method works properly. After update my packages and laravel to newest versions, copy method stopped working for me.
The issue is in package `league/filesystem` directly in method `normalizeRelativePath` in `Util.php` file.
When I want copy files from remote address and paste url like `http://some_urle_to_image.jpg`, the 'normalizeRelativePath' method returns `http:/some_urle_to_image.jpg`

**Comment by themsaid** [comment]
Please report on `league/filesystem` then :)

**Comment by Malin88** [comment]
I've already done this but, maybe, this should be fixed by changing the laravel `copy` method ?
