### ISSUE TITLE
FormRequest's withValidator() $validator->after(...) does not seem to be called for each rule

### ISSUE THREAD

**Issue by Hell4Ge** [laravel/framework#19630]
- Laravel Version: 5.4.27
- PHP Version: PHP 7.1.4-
- Database Driver & Version: pgsql 9.5

### Description:
I just tried to write a function that will log form validation results on the fly (inside class that extends FormRequest). The following code:

	public function withValidator($validator)
	{
		$validator->after(function ($validator) {
			foreach($validator->failed() as $field => $rules) {
				foreach(array_keys($rules) as $rule) {
					Log::warning("NO: ".$field.' ['.$rule.']');
				}
			}
			$passed = array_diff(array_keys($validator->getData()), array_keys($validator->failed()));
			foreach($passed as $pass) {
				Log::info("OK: ".$pass);
			}
		});
	}

Will execute for each rule only if a 'required' rule is placed at the end.
So for given examples:

      1.  'cat_name'	=> 'numeric|min:2|unique:category|required',
      2.  'cat_name'	=> '|min:2|required|numeric|unique:category',
      3.  'cat_name'	=> 'requirednumeric|min:2|unique:category',

It will print logs for rules:

    1. numeric, min, unique, required
    2. min, required
    3. required

### Steps To Reproduce:
Insert this code into some custom request class, and check logs

**Comment by themsaid** [comment]
It's called on every request, also after is called, but looks like you're not passing anything to the validator so only when you pass required it fails.
