### ISSUE TITLE
detach(id, $attr) has different behavior than attach(id, $attr)

### ISSUE THREAD

**Issue by iateadonut** [laravel/framework#19632]
- Laravel Version: 5.4
- PHP Version:7.0
- Database Driver & Version: mysql 5.7.18

### Description:
If you have a ->belongsToMany() relationship, let's say $user and $role with a pivot table role_user that has the fields: user_id, role_id, company_id
you can add a relation with an extra field like this:
$user->roles()->attach( 1 , ['company_id' =>2 ] );

But if you do the same with detach:
$user->roles()->attach( 1 , ['company_id' =>1 ] );
you will delete the record ( user_id, 1, 2 ) as well as ( user_id, 1, 2 )

I don't know if this is a bug or a feature, but I think the second parameter of detach should be $attributes, and those attributes should be used in a 'where' statement.

**Comment by mathieutu** [comment]
Guy, I don't know if it's only me, but I didn't really understand your problem...
You should re-read your post, and use code blocs:
>with **detach**:
>$user->roles()->**attach**( 1 , ['company_id' =>1 ] );

>**( user_id, 1, 2 )** as well as **( user_id, 1, 2 )**

The second argument of `detach` method is just a boolean which will decide if you want to touch (update the timestamp of) the parent model.

**Comment by themsaid** [comment]
Yes with detach you only pass the ID, it assumes you don't have duplicate records for your user_id<->role_id
