### ISSUE TITLE
Fresh command exception when using the sqlite driver

### ISSUE THREAD

**Issue by JeffreyWay** [laravel/framework#19634]
- Laravel Version: 5.5
- PHP Version: 7.1
- Database Driver & Version: Sqlite 

### Description:

I noticed that the new `php artisan migrate:fresh` command throws an error when using the sqlite driver. 

https://www.dropbox.com/s/oiqzmzqgv9ogv1a/Screenshot%202017-06-16%2009.47.10.png?dl=0

### Steps To Reproduce:

1. Install fresh Laravel app
2. Set DB driver to sqlite
3. `touch database/database.sqlite`
4. `php artisan migrate && php artisan migrate:fresh`

This will produce:

```
  [Illuminate\Database\QueryException]
  SQLSTATE[HY000]: General error: 1 table "migrations" already exists (SQL: create table "migrations" ("id" integer not null primary key autoincrement, "migration" varchar not null, "batch" integer not null))



  [PDOException]
  SQLSTATE[HY000]: General error: 1 table "migrations" already exists
```

**Comment by themsaid** [comment]
Hello :)

Fixed in https://github.com/laravel/framework/pull/19644
