### ISSUE TITLE
Issue with artisan commands on fresh install on Windows 10

### ISSUE THREAD

**Issue by coxy121** [laravel/framework#19640]
- Laravel Version: 5.4.23 & 5.5 dev branch
- PHP Version: 7.0
- Database Driver & Version: MySQL

- Using Windows 10

### Description:
Creating a new project with a fresh install using ```laravel new project-name``` or ```composer create-project laravel/laravel project-name``` hits the following issue when using artisan:

```Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize

  [ErrorException]
  The Symfony\Component\Process\ProcessUtils::escapeArgument() method is deprecated since version 3.3 and will be removed in 4.0. Use a command line array or give env vars to the Process::start/run() method instead.

Script php artisan optimize handling the post-install-cmd event returned with an error

[RuntimeException]
Error Output:
```
Running any php artisan commands returns the same error.

### Steps To Reproduce:
1. Install fresh Laravel app on windows 10. - ```laravel new project-name```
2. This Should hit the error when php artisan optimize is run.

This will produce:

```Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize

  [ErrorException]
  The Symfony\Component\Process\ProcessUtils::escapeArgument() method is deprecated since version 3.3 and will be removed in 4.0. Use a command line array or give env vars to the Process::start/run() method instead.

Script php artisan optimize handling the post-install-cmd event returned with an error

[RuntimeException]
Error Output:
```
3. Running any artisan command with ```php artisan <command>``` will return the above error.

**Comment by themsaid** [comment]
Check your php.ini file and find this:

```
scream.enabled=1
```

If found change it to:

```
scream.enabled=0
```

restart and let me know if it works

**Comment by coxy121** [comment]
Perfect, thanks! It was my xdebug settings I had:

```xdebug.scream = 1```

Based on your example I changed it to:

```xdebug.scream = 0```

Now it runs as expected.

**Comment by themsaid** [comment]
great :)

**Comment by ismailansari** [comment]
Hi,
I am using vagrant with php 7.1 and I tried to found
```
scream.enabled=1
```
and 
```
xdebug.scream = 1
```
but not found

**Comment by DanielFurmanov** [comment]
For those who will stumble here, the path to the file folks are talking about: `/etc/php/7.1/fpm/conf.d/20-xdebug.ini`
(tested on Ubuntu)

**Comment by chaunci** [comment]
Hi,
I am using laradock，I can,t find the `php.ini`。what should i do？
My Laravel version is on 5.4.36

**Comment by chaunci** [comment]
There is something wrong with my schedule may be cause by this problem：
```
[mesage_from]error:[level]3=>LOG_ERR: [message_body]错误码16384=>The Symfony\Component\Process\ProcessUtils::escapeArgument() method is deprecated since Symfony 3.3 and will be removed in 4.0. Use a command line array or give env vars to the Process::start/run() method instead
```
I set withoutOverlapping,  but seems not work.

**schedule file**
```
$schedule->command('produce:email')->everyFiveMinutes()->withoutOverlapping();
```

**command file**

`
 public function handle()
    {
        $name = mt_rand(10000,99999);

        Log::info($name . ':开始运行时间'.date('Y-m-d H:i:s'));

        $this->parseAppName();

        $this->createQueue();


        if(count($this->queue) <= 0){
            return ;
        }

        foreach ($this->queue as $key => $queue) {

            $this->getHistoryId($key,$queue['filter']);

            $this->executeAdd($key,$queue);
        }

        Log::info($name .':结束运行时间'.date('Y-m-d H:i:s'));
    }
`

**Log File** 
`
[2018-07-10 09:21:08] local.INFO: 91991:开始运行时间2018-07-10 09:21:08 

[2018-07-10 09:22:03] local.INFO: 51228:开始运行时间2018-07-10 09:22:03  
[2018-07-10 09:23:03] local.INFO: 77517:开始运行时间2018-07-10 09:23:03  
[2018-07-10 09:23:06] local.INFO: 91991:结束运行时间2018-07-10 09:23:06
`

The 51228 and 77517 run before the 91991 ended
