### ISSUE TITLE
Why does a select statement make a write and a read connection?

### ISSUE THREAD

**Issue by mrfrodo24** [laravel/framework#19641]
- Laravel Version: 5.0.*
- PHP Version: 5.4.45
- Database Driver & Version: Aurora(MySQL-Compatible) 5.6.10a

### Description:

This is more of a question than a bug I think.  I've setup an Amazon Aurora cluster, which provides a cluster endpoint and a reader endpoint.  I've set the cluster endpoint to be the write host in database/config and the reader endpoint to be the read host.

The reader endpoint goes to a load balancer in Amazon Aurora which chooses a reader node to receive the connection.

When I was testing, I noticed in the AWS RDS console that the master DB was getting hit with a ton of connections, as were the reader nodes, but there were no selects being run on the master DB.  Only the reader nodes had Select Throughput activity, as expected.

When I looked at the revision made to allow for read/write hosts in database/config (https://github.com/laravel/framework/commit/a3b0e87ae50b22a517c6daea85e824ae2f0e27c0), I did find that it's actually creating both a read and a write connection when there is a select statement being made.

Is there a reason that it's making both of these connections?  This was not the functionality I expected when I found Laravel awesomely supported this.  It's causing issues since the master DB is getting unnecessarily flooded with connections.

Thanks!  And I do apologize if the way this issue is submitted doesn't follow the guidelines.

**Comment by browner12** [comment]
this definitely may be something that needs to be addressed.

the Slack channel is a great place to discuss this, or the [Laravel Internals Repo](https://github.com/laravel/internals).

**Comment by adamgoose** [comment]
@mrfrodo24 Did you ever open another issue on this? I'm running into the same issue, and its proving to be quite a problem. Would love to hear more about your solution.

**Comment by spencerr-carimus** [comment]
Hey @adamgoose, I actually got side-tracked submitting the other issue for this.  I just did in Laravel Internals: https://github.com/laravel/internals/issues/713

Thanks for reminding me!  I definitely would like to see this fixed, and also the added feature I mentioned in that Laravel Internals issue would be an even bigger bonus.
