### ISSUE TITLE
Running Migration with fresh Laravel installation causing Syntax error

### ISSUE THREAD

**Issue by hnucleo** [laravel/framework#19649]
- Laravel Version: 5.4.27
- PHP Version: 7.1.5
- Database Driver & Version: MySQL & 5.7.18

After create new Laravel app, i run migration command php artisan migrate. All using default migration file and i got error telling 

> 
  [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1071  (SQL: alter table
   `password_resets` add index `password_resets_email_index`(`email`))

Users table was created even error persist, but password reset table didn't, may i know if someone get some error like mine & how to resolve this?

Thanks,
![service](https://user-images.githubusercontent.com/28716259/27249316-7738a1cc-533c-11e7-8a0a-a9f6ab02b4cf.png)

**Comment by aheinzm** [comment]
What storage engine, encoding, and collation are you using?

**Comment by hnucleo** [comment]
@aheinzm 

Storage Engine created by migration is: MyISAM
Collation: utf8mb4_unicode_ci

**Comment by aheinzm** [comment]
I'm assuming the users.email field is varchar(255). Unfortunately with MyISAM and utf8mb4_unicode_ci, the key length is too long. You should be able to either use InnoDB, or change the email field to varchar(250).

**Comment by hnucleo** [comment]
Hi @aheinzm thank you for referencing it. Now the error was fixed with just change the config under "config/database.php" using `engine => 'InnoDB'`.

Many thanks.
