### ISSUE TITLE
Add support for optimized binary UUID keys?

### ISSUE THREAD

**Issue by sauladam** [laravel/framework#19655]
I wanted to use UUIDs as primary keys in a project and did some research on that. In short, here's what I found out (https://mariadb.com/kb/en/mariadb/guiduuid-performance/ explains it in more detail):

**The problem:** Using raw UUIDs as primary keys in tables can be challenging, because 1. they are not technically sequential so INSERTing into an index means jumping around a lot, and 2. the 36 characters of a UUID result in a pretty big index footprint, especially in InnoDB where every secondary key also includes the primary key. And the Laravel default of utf8mb4-encoding makes this even worse, making the 36 character string 146bytes big.

**The solution:** UUID v1 is time-based, so some parts of it are kind of sequential. If we rearrange the UUID and put those parts in the front we can allow for better indexing. And if we strip out the dashes and encode it to binary, we end up with 16bytes instead of 146.

I thought it would be awesome if Laravel / Eloquent offered this functionality out of the box. So I started hacking on it and realized that it's quite a heavy change. I want to query the model with the original UUID, but I want it to to be optimized and binary-encoded automatically before going into the DB and then decoded and rearranged back to the original UUID when coming back from the DB as a model. So far, this works great for `$model->find()` but it gets trickier when it comes to relationships. But I already got it working for `belongsTo()` and eager loads.

So, my question especially towards @taylorotwell is: Is this something you would consider for Laravel and should I keep working on it in a way that makes a good PR or is there maybe a reason why it's not supported?

**Comment by Dylan-DPC** [comment]
This is not a bug. Open an issue in the laravel/internals repo

**Comment by sauladam** [comment]
@Dylan-DPC Sorry, I didn't know about laravel/internals. I'll post it there, thanks!
