### ISSUE TITLE
Blade function does not accept parameters when default value is set

### ISSUE THREAD

**Issue by yorickdewid** [laravel/framework#19658]
- Laravel Version: 5.4.27
- PHP Version: 7.0.18
- Database Driver & Version: PostgreSQL 9.5.7

### Description:
Seems like commit a05e9e2f4dff97adc2fa51aee9822b0562f8c98a broke the passing of multiple vars to blade functions.

### Steps To Reproduce:
```php
        Blade::directive('money', function ($expression, $symbol = true) {
            // Here $symbol is always true, regardless of what is passed
        });
```

**Comment by sisve** [comment]
Uhm. Are you sure? The linked commit does a change for the default value in `@yield('optional-section', 'default-value')`, it does not seem relevant at all for custom directives.

The invocation of custom directives only passes one parameter. See [BladeCompiler::callCustomDirective](https://github.com/laravel/framework/blob/05060b183dd09cee6dce498da5afde9e66fd1a29/src/Illuminate/View/Compilers/BladeCompiler.php#L303-L310). The $expression you get is a string containing everything within the parantheses, which in the case of `@money(13.37, false)` would be the _string_ `"13.37, false"`.

A common (I've seen two occurrences of this where one is mine...) is to have your directive just return a static invocation of actual implementation.

    class MoneyDirective {
        public function boot() {
            Blade::directive('money', function ($expression) {
                $class = self::class;
                return "<?php echo $class::render(\$__env, $expression) ?>";
            });
        }

        public function render($env, $amount, $symbol = true) {
            return "Someone should implement MoneyDirective::render...";
        }
    }

    // Call MoneyDirective::boot() in your service provider's boot()

**Comment by yorickdewid** [comment]
No I am not sure, I'll check this and report back. Thanks anyway.

**Comment by yorickdewid** [comment]
That fixed it, thanks
