### ISSUE TITLE
Update json field not working

### ISSUE THREAD

**Issue by rorc** [laravel/framework#19664]
- Laravel Version: 5.4.26

### Description:
I have json `settings` column in MySQL with value `{"buh": {"admins": ["12", "13"]}}`
This update not working `$model->update(['settings->buh->admins' => [12]]);`

**Comment by themsaid** [comment]
Make sure you add the json attributes to the `fillable` array of the mode.

**Comment by rorc** [comment]
@themsaid For shure i added `settings` field into `$fillable`!

**Comment by rorc** [comment]
@themsaid Why you closed issue?

**Comment by themsaid** [comment]
Now you'll need to add the field attributes as well.
