### ISSUE TITLE
Resource Controller return Empty Object without other advice

### ISSUE THREAD

**Issue by luisbch9** [laravel/framework#19662]
- Laravel Version: 5.4.27
- PHP Version: 7.0
- Database Driver & Version: MySql

### Description:
The resource controller was returning an empty object when I used the Model Binding, but after I read this was caused by the "singularized" version of the resource name. However I didn't way to kwnow why I was getting an empty object. I think when a model it's not found should return an error or advice.

### Steps To Reproduce:
`Route::resource('presentaciones','PresentacionesController');`

```
public function show(Presentacion $presentacion)
    {
        dd($presentacion);
    }
```
![image](https://user-images.githubusercontent.com/15067649/27262669-42c03b86-5421-11e7-849a-8b96be3a7cdf.png)

I know it can be fixed adding parameters. But seriously I think it should show an error or advice.

**Comment by naoufal1** [comment]
you have an error there:

$presentacion in show(Presentacion $presentacion) is not presentacione(s) int the Route::resource() method 

![image](https://user-images.githubusercontent.com/11160251/27265157-e77edea8-547f-11e7-9771-65a879c2c457.png)

**Comment by LeoYang90** [comment]
Route::resource('presentaciones','PresentacionesController')
show(Presentacione $presentacione)
or
Route::resource('presentacions','PresentacionsController')
show(Presentacion $presentacion)
