### ISSUE TITLE
The form cannot be submitted if the form tags are located in 2 different html sections

### ISSUE THREAD

**Issue by GordanaP** [laravel/framework#19661]
- Laravel Version: 5.4.24
- PHP Version: 7.1
- Database Driver & Version: MySql

### Description:
In the previous versions (i.e 5.4.9) I could open the form tag in one html section (i.e modal body) and close in another (i.e.modal footer). In the 5.4.25 it is impossible.   

### Steps To Reproduce:
```
<div class="modal-body">
    <form action="{{route('foo')}}" method="post">
        <input type="text" name="foo" id="foo" />
</div>
<div class="modal-footer">
        <button type="submit">Submit</button>
    </form>
</div>
```
The same references to the blade components - the form cannot be submitted if the form tags are located in two different components.

**Comment by sisve** [comment]
This isn't a Laravel issue, but a browser/html issue. It's invalid html to nest elements in that way, just as `<div><span></div></span>` is invalid. You've perhaps been lucky in the html structure/browser/something on how the browser has parsed the html and generated the missing closing tag.
