### ISSUE TITLE
'2017-06-06' vs. '2017-06-06 00:00:00', marks object as dirty

### ISSUE THREAD

**Issue by naoufal1** [laravel/framework#19665]
- Laravel Version: latest
- PHP Version:7.0.10
- Database Driver & Version:5.7.14

### Description:

Hello
I'm trying to use updating function in the observer class to handle 'Post' model updates, and in the post, I'm setting 2 properties as dates 
![image](https://user-images.githubusercontent.com/11160251/27265062-cfbba7c6-547d-11e7-9fbf-307b791b317b.png)

And when I update the object, with the same data, laravel mark it as a dirty, and fires the updated function on the observer.
when I tried to figure what happens, I found :
I set the date in this format : `2017-06-06` , 
and laravel compare it with this format : `2017-06-06 00:00:00` .
event I'm using this format: '2017-06-06' in the database , 
![image](https://user-images.githubusercontent.com/11160251/27265043-64edd914-547d-11e7-96f1-adebe28e5d7e.png)

So, is there any way to use the simple format '2016-06-06', in the database and the model

**Comment by jn-jairo** [comment]
The `dirty` function is with bug, I had the same problem, I made a pull request for that but was rejected (https://github.com/laravel/framework/pull/19648), so I extend the `getDirty` in my `Model` to fix that.

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model as BaseModel;

class Model extends BaseModel
{
    /**
     * Get the attributes that have been changed since last sync.
     *
     * @return array
     */
    public function getDirty()
    {
        $dirty = [];

        foreach ($this->attributes as $key => $value) {
            if (! array_key_exists($key, $this->original)) {
                $dirty[$key] = $value;
            } elseif ($value !== $this->original[$key] &&
                ! $this->originalIsEquivalent($key)
            ) {
                $dirty[$key] = $value;
            }
        }

        return $dirty;
    }

    /**
     * Determine if the new and old values for a given key are equivalent.
     *
     * @param  string  $key
     * @return bool
     */
    public function originalIsEquivalent($key)
    {
        $current = $this->attributes[$key];

        $original = $this->original[$key];

        if ($current === $original) {
            return true;
        }

        if (is_null($current) || is_null($original)) {
            return false;
        }

        if (in_array($key, $this->getDates()) || $this->isDateCastable($key)) {
            return $this->asDateTime($current)->eq($this->asDateTime($original));
        } elseif ($this->hasCast($key)) {
            return $this->castAttribute($key, $current) == $this->castAttribute($key, $original);
        } else {
            return is_numeric($current) && is_numeric($original) && strcmp((string) $current, (string) $original) === 0;
        }
    }
}
```

While there is no definitive solution you can use that like me, and the `dirty` will work as it should.

**Comment by stevebauman** [comment]
> I set the date in this format : 2017-06-06 ,
and laravel compare it with this format : 2017-06-06 00:00:00 .
event I'm using this format: '2017-06-06' in the database ,

Are you sure this is the actual format inside your SQL table? It should be a `date` column and not a `datetime` / `timestamp` column.

**Comment by themsaid** [comment]
I can't replicate your issue, please share more details about the scenario.

**Comment by themsaid** [comment]
If value in DB is `2016-10-10` and I do the following:

```
$model->fill([
    'date' => '2016-10-10'
]);
```

I get an empty array out of `getDirty()`, which means it's working fine.

**Comment by naoufal1** [comment]
ok
I created a new project, and I used this schema:
![image](https://user-images.githubusercontent.com/11160251/27304621-2deae1da-552e-11e7-8341-0daabc94b849.png)
the result => 
![image](https://user-images.githubusercontent.com/11160251/27304801-c2233a14-552e-11e7-92a4-efc46387471c.png)
the model's class :
![image](https://user-images.githubusercontent.com/11160251/27304941-50d548ba-552f-11e7-9b4f-c10aa88e7f6b.png)

and this what happens when I use the eloquent to update the update the object :
![image](https://user-images.githubusercontent.com/11160251/27305147-02a5247a-5530-11e7-9b28-e8611ee7def4.png)

@themsaid

**Comment by themsaid** [comment]
That's because the default date format is `Y-m-d H:i:S`. You need to change that format:

```
protected $dateFormat = 'Y-m-d';
```

That's the format used to cast the date object before putting it in comparison, this was slightly changed in 5.5, but can't introduce any change in 5.4 since it might be a breaking change.

**Comment by naoufal1** [comment]
but If I have 2 dates with different format in the same model , I think it's impossible ?

**Comment by themsaid** [comment]
Yes unfortunately it's not supported at the moment

**Comment by naoufal1** [comment]
Oky
thanks
