### ISSUE TITLE
[5.5] $model->getDirty() wont return booleans

### ISSUE THREAD

**Issue by swalker2** [laravel/framework#19678]
- Laravel Version: 5.5-dev
- PHP Version: 7.0
- Database Driver & Version: sqlite3 in memory
### Description:
$model->isDirty() wont return booleans

### Steps To Reproduce:
Fresh install
laravel new laravel-getdirty --dev

```php
// database/migrations/XXXXXXXXXXX_create_users_table.php
$table->integer('active')->default(false);
```
```php
// database/migrations/XXXXXXXXXXX_create_change_logs_table.php
Schema::create('change_logs', function (Blueprint $table) {
    $table->increments('id');
    $table->integer('loggable_id');
    $table->string('loggable_type');
    $table->json('changes')->nullable();
    $table->timestamps();
});
```
```php
// app/User.php
use Notifiable, Loggable;
protected $guarded = [];
protected $casts = ['active'=>'bool'];
```
```php
// phpunit.xml
<env name="DB_CONNECTION" value="sqlite"/>
<env name="DB_DATABASE" value=":memory:"/>
```
```php
// app/Loggable.php
protected static function bootLoggable()
{
    static::updating(function ($model) {
        if ( ! $model->isDirty()) {
            return;
        }

        $changes = $model->getDirty();

        $model->logs()->create(compact($changes));
    });
}
public function logs()
{
    return $this->morphMany(ChangeLog::class, 'loggable');
}
```
```php
// tests/Unit/LoggableTest.php
use DatabaseMigrations;

/** @test */
function logging_a_boolean_change()
{
    //given we have an user (active is default false)
    $user = factory('App\User')->create();

    //when we update the user status
    $user->update(['active' => true]);

    //then we whould have a log reccord with the status change
    $this->assertDatabaseHas('change_logs', [
        'id' => 1,
        'changes' => json_encode(['active' => true]),
    ]);
}
```

```bash
vagrant@homestead:~/Code/laravel-getdirty$ phpunit
PHPUnit 6.2.2 by Sebastian Bergmann and contributors.

F                                                                   1 / 1 (100%)

Time: 1.72 seconds, Memory: 14.00MB

There was 1 failure:

1) Tests\Unit\LoggableTest::logging_a_boolean_change
Failed asserting that a row in the table [change_logs] matches the attributes {
    "id": 1,
    "changes": "{\"active\":true}"
}.

Found: [
    {
        "id": "1",
        "loggable_id": "1",
        "loggable_type": "App\\User",
        "changes": null,
        "created_at": "2017-06-19 21:53:44",
        "updated_at": "2017-06-19 21:53:44"
    }
].

/home/vagrant/Code/laravel-getdirty/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/InteractsWithDatabase.php:22
/home/vagrant/Code/laravel-getdirty/tests/Unit/LoggableTest.php:22

FAILURES!
Tests: 1, Assertions: 1, Failures: 1.
```

As you can see, $model->isDirty() returned true, but there was nothing in $model->getDirty()

**Comment by themsaid** [comment]
Works fine to me, an attribute casted as boolean can be updated and appears in the dirt array.

please share more information on how to regenerate.

**Comment by swalker2** [comment]
I'm sorry it is the getDirty() method that does not return boolean changes, I will create a new application and a test just for reproducing this and then I will update this issue asap

**Comment by swalker2** [comment]
@themsaid I could replicate this in a fresh installation, just updated all the the steps

**Comment by themsaid** [comment]
Still can't replicate, and `isDirty` just reads data from `getDirty`, it appears to me that something is wrong with your setup.

Please submit a PR with a failing test in order to be able to investigate more, right now it works just fine on latest master branch:

```
$model->fill([
    'active => true
]);
```

`isDirt('active')` returns true only if the DB has a value opposite to the one you're providing.

**Comment by themsaid** [comment]
Your example here is doing a lot of stuff out of the scope of the issue, you just need to see if `isDirty()` is returning the correct value.

**Comment by swalker2** [comment]
Well, it proves that `getDirty()` doesn't returns booleans changes but `isDirty()` returns true, including everything I did so you can point me where I am doing it wrong

**Comment by themsaid** [comment]
Sorry but I really don't can't see the issue, both isDirty and getDirty works fine for me, that's why I'm asking for a failing test, that will pinpoint the issue so it's easy to understand :)

**Comment by swalker2** [comment]
Strangely, I couldn't replicate this issue in a test. It only happens in 5.5, 5.4 works fine, When the upgrade comes I will compare it manually no worries
