### ISSUE TITLE
Illuminate\Database\DetectLostConnections

### ISSUE THREAD

**Issue by Mark1Z** [laravel/framework#19685]
- Laravel Version: #.#.#
- PHP Version:
- Database Driver & Version:
- Illuminate version: 5.4.27

### Description:
Hello team! Some issue with new illuminate version after update: http://joxi.ru/823pEJRFJl398A
Seems that trait is gone (with all "database" namespace) and not added to composer.json requirements

**Comment by themsaid** [comment]
Looks like your IDE is not picking up those classes for some reason, they weren't removed though,

**Comment by Mark1Z** [comment]
Yes, you didn't remove anything, but, I'm using only illuminate queue in my project and seems that someone added in 5.4.27 (https://github.com/illuminate/queue) DetectsLostConnections trait from Illuminate\Database\DetectsLostConnections in Illuminate\Queue\Worker. But https://github.com/illuminate/database is another vendor package, which not included in illuminate/queue composer.json as requred package and I started to catch 500 errors. You can check this using github links listed before in Worker class. Thanks.

**Comment by themsaid** [comment]
Ah thanks, I added illuminate/database to queue's composer.json.

In the meantime you can add `"illuminate/database": "5.4.*",` to your project's composer.json until the changes take effect.

**Comment by Mark1Z** [comment]
I did this, thank you for your time:)
