### ISSUE TITLE
Discussion about Storage, response()->download() and Storage::fake() 

### ISSUE THREAD

**Issue by ThibaudDauce** [laravel/framework#19686]
- Laravel Version: 5.4
- PHP Version: 7.1

### Description:

I have some trouble to understand how to download files created by the Storage facade. The `response()->download()` is expecting a full path and not a relative path from the storage root. To get the full path, I only found `Storage::url()`. `Storage::url()` can return the full path if we specify in the config the root path as URL. If the URL is not specified with a local driver, the default one is a weird "/storage" URL ( https://github.com/laravel/framework/blob/452d7e0afb5740d204b6e078a24a14fb7270c4f3/src/Illuminate/Filesystem/FilesystemAdapter.php#L357 ).

Moreover, if we fake the Storage adapter, only the 'root' config is set ( https://github.com/laravel/framework/blob/504bcffdb0b8ca23c5382067633318a699868ab5/src/Illuminate/Support/Facades/Storage.php#L24 ). So the URL default to "/storage" which doesn't exists so a FileNotFound exception is thrown by the controller.

### Steps To Reproduce:

I push a sample demo to my Github to reproduce some of the problems with this management of Storage full paths.
https://github.com/ThibaudDauce/fake-storage/commit/dec491cccbf89589e88bde99c8bafb1e20cc38bd

### Solution

https://github.com/ThibaudDauce/fake-storage/commit/dec491cccbf89589e88bde99c8bafb1e20cc38bd?diff=unified#diff-7e3ce459dfcc113722bdf4667ceffc11R30

I think the `Storage::url()` is not the right way to get the full path of a local adapter but I couldn't find another one. I often need to get the absolute path (mail attachment, response download, shell exec to create PDF…), maybe add a method (if it's not already here…) could be a fix (I can make a PR).

Something like `Storage::fullPath('file')` instead of `Storage::getDriver()->getAdapter()->applyPathPrefix('file')`

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
