### ISSUE TITLE
[5.4] Laravel collection support array_intersect_key

### ISSUE THREAD

**Issue by VinceG** [laravel/framework#19682]
- Laravel Version: 5.4.23
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7

### Description:

This just adds a new method to the Collection object to use 'array_intersect_key' like we do with 'array_intersect'.

I added the exact same method as well as the tests we currently have for 'intersect'.

**Comment by Dylan-DPC** [comment]
Proposals should be made in laravel/internals repo

**Comment by VinceG** [comment]
@Dylan-DPC this was merely a reference issue for the PR #19683 not a request nor an actual bug.
