### ISSUE TITLE
MySqlConnector `use database` statement

### ISSUE THREAD

**Issue by NItaMII** [laravel/framework#19684]
- Laravel Version: 5.2.45
- PHP Version:5.6.29
- Database Driver & Version:MySQL 5.7.16

### Description:
in my old project, i use the laravel  5.2.22
and  the `Illuminate\Database\Connectors\MySqlConnector` `connect` function

```
...
    public function connect(array $config)
    {
        $dsn = $this->getDsn($config);
...
        if (isset($config['unix_socket'])) {
            $connection->exec("use `{$config['database']}`;");
        }
...
    }
...
```
in my new project, i use the laravel 5.2.45
and  the `Illuminate\Database\Connectors\MySqlConnector` `connect` function
```
...
    public function connect(array $config)
    {
        $dsn = $this->getDsn($config);
...
        if (! empty($config['database'])) {
            $connection->exec("use `{$config['database']}`;");
        }
...
    }
...
```

And i use the same (default) database configuration in both project
```
            'driver' => 'mysql',
            'host' => env('DB_HOST', 'localhost'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'collation' => 'utf8_general_ci',
            'prefix' => 'v3_',
            'strict' => false,
            'engine' => null,
```
the issue is  in laravel 5.2.45 it exec `use my_database`, i doubt if it's necessay.Because in my condition, i connect a proxy rather than connect mysql server directly,and it don't allow me to do such `use database` statements.

**Comment by Dylan-DPC** [comment]
Sorry. but our time machine is broken so we can't go back to 5.2 and fix issues. 5.2 is end of life. Do try this in 5.4 or 5.5-dev versions and let us know what happens

**Comment by themsaid** [comment]
Yes please upgrade since 5.2 is not supported anymore.
