### ISSUE TITLE
\Illuminate\Mail\Events\MessageSent is triggered regardless whether the message has been sent or  not

### ISSUE THREAD

**Issue by bubasuma** [laravel/framework#19689]
- Laravel Version: ~5.4
- PHP Version: ~7.0

I am listening \Illuminate\Mail\Events\MessageSending to prevent sending some messages. It does, but \Illuminate\Mail\Events\MessageSent is triggered.   

<img width="609" alt="screen shot 2017-06-20 at 1 42 40 pm" src="https://user-images.githubusercontent.com/8973208/27329782-8fe6ef46-55bf-11e7-8259-5315dddb7ec0.png">

I would do it as following
```php
if ($this->sendSwiftMessage($message->getSwiftMessage())) {
    $this->dispatchSentEvent($message);
}
```

**Comment by themsaid** [comment]
Submitted a fix here https://github.com/laravel/framework/pull/19690

thanks
