### ISSUE TITLE
WhereIn with subquery inside join clause

### ISSUE THREAD

**Issue by brunoti** [laravel/framework#19695]
- Laravel Version: 5.3.31
- PHP Version: 5.6.30
- Database Driver & Version: Mysql 5.6

### Description:
The subquery generated by this code (inside a join closure):

```php
            $join->whereIn('ordem_de_compra_itens.id', function($query) {
                $query->from('oc_item_qc_item')
                    ->select('oc_item_qc_item.ordem_de_compra_item_id')
                    ->whereColumn(
                        'oc_item_qc_item.qc_item_id',
                        'contrato_itens.qc_item_id'
                    );
            });
```

Is:

```sql
	AND `ordem_de_compra_itens`.`id` IN (
		SELECT
			`oc_item_qc_item`.`ordem_de_compra_item_id`
		FROM
			`oc_item_qc_item` ON
			`oc_item_qc_item`.`qc_item_id` = `contrato_itens`.`qc_item_id`
	)
```

Instead of:

```sql
	AND `ordem_de_compra_itens`.`id` IN (
		SELECT
			`oc_item_qc_item`.`ordem_de_compra_item_id`
		FROM
			`oc_item_qc_item` WHERE
			`oc_item_qc_item`.`qc_item_id` = `contrato_itens`.`qc_item_id`
	)
```

Observe that instead of using a WHERE clause it is trying to use an ON clause.

### Steps To Reproduce:

Described above.

Is this right? There is another option besides remove the query builder and use the whole query string inside a ``DB::raw``? It is sad to do that just because a join doesn't work 😞 

The worst part is that i can't use Laravel paginator properly.

**Comment by Dylan-DPC** [comment]
5.3 is no longer supported. So kindly test this on 5.4 and let us know (issue expected in 5.4 but just in case :P )

**Comment by themsaid** [comment]
yes please test on 5.4 and ping me if the issue still exists there, lots of things were fixed in 5.4

**Comment by rodrigopedra** [comment]
Hi @themsaid, this is still an issue on 5.5

Example using built-in tables:

~~~php
<?php

\Route::get( '/test', function () {
    $builder = \DB::table( 'users' )
        ->join( 'password_resets', function ( JoinClause $join ) {
            $join->on( 'users.email', '=', 'password_resets.email' );
            $join->whereIn( 'email', function ( $query ) {
                // dummy example just to demonstrate issue
                $query->select( 'email' )
                    ->from( 'users' )
                    ->where( 'id', '>', 1 );
            } );
        } );

    return $builder->toSql();
} );
~~~

It outputs:

~~~sql
select * 
from 
    `users` 
    inner join `password_resets` 
        on `users`.`email` = `password_resets`.`email` 
        and `email` in (select `email` from `users` on `id` > ?)
~~~

instead of

~~~sql
select * 
from 
    `users` 
    inner join `password_resets` 
        on `users`.`email` = `password_resets`.`email` 
        and `email` in (select `email` from `users` WHERE `id` > ?)
~~~

I actually found this issue because I am having the very same problem with a `whereExists()` inside a join clause. The query builder also uses a `on` instead of a `where`

**Comment by rodrigopedra** [comment]
For me changing line 98 of `JoinClause` class 

https://github.com/laravel/framework/blob/5.5/src/Illuminate/Database/Query/JoinClause.php#L98

from 

```
    public function newQuery()
    {
        return new static($this->parentQuery, $this->type, $this->table);
    }
```
to:

```
    public function newQuery()
    {
        return $this->parentQuery->newQuery();
    }
```

Seems to solve the problem. I don't have the time to run all the tests today and check if this does not break anything. But I can check over the weekend.

**Comment by rodrigopedra** [comment]
@brunoti I made a pull-request #21008 to address this issue. Hope it gets merged.

**Comment by brunoti** [comment]
Nice @rodrigopedra!
