### ISSUE TITLE
[Request] Pluckables

### ISSUE THREAD

**Issue by nhuebnereagle** [laravel/framework#19718]
- Laravel Version: 5.4.x
- PHP Version:   7.x
- Database Driver & Version:   Any

### Description:

Create a method that can provide a list of `pluck` possibilities. 

### Steps To Reproduce:

```
array_pluckables([
'my' => 
   [
   'nested' => 
      [
          'array' => 'is here'
       ]
   ]
]);
```

The array is iterated and can provide a basic array containing all `pluck possibilities` which could be used against the array.

**Result**
```
[
   0 => 'my',
   1 => 'my.nested',
   2 => 'my.nested.array',
]
```
Perhaps the same functionality for Collections if possible.

Thanks for all your hard work, Laravel is my life's breath <3

**Comment by devcircus** [comment]
It's best to make proposals and/or feature requests on the internals repo:
https://github.com/laravel/internals/issues

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
