### ISSUE TITLE
SqlServerProcessor::processInsertGetIdForOdbc() does not support bigint identity field

### ISSUE THREAD

**Issue by vedmant** [laravel/framework#19710]
- Laravel Version: 5.4.22
- PHP Version: 7.1.1
- Database Driver & Version: MS SQL 14.0.600

### Description:
SqlServerProcessor::processInsertGetIdForOdbc() does not support bigint identity field. To fix this I had to override SqlServerProcessor and replace:

        $result = $connection->selectFromWriteConnection(
            'SELECT CAST(COALESCE(SCOPE_IDENTITY(), @@IDENTITY) AS int) AS insertid'
        );

with  

        $result = $connection->selectFromWriteConnection(
            'SELECT CAST(COALESCE(SCOPE_IDENTITY(), @@IDENTITY) AS bigint) AS insertid'
        );

For this I also had to copy SqlServerConnection and set it with Connection::resolverFor().
I think it makes sense to use `bigint` or make it changeable with an option.

### Steps To Reproduce:
Use pdo_sqlsrv php extension with MS SQL server, it requires to add `'odbc' => true,` to connection configuration. Try to insert into table with bigint identity field that has ids bigger than 2147483647. In my case there is just a prefix for ids that makes up large numbers.

**Comment by themsaid** [comment]
feel free to open a PR so that we discuss the implementation right away.
