### ISSUE TITLE
Cookie disappears on refreshing

### ISSUE THREAD

**Issue by Hiroki1116** [laravel/framework#19719]
- Laravel Version: 5.3.0
- PHP Version:7
- Database Driver & Version: MySQl

### Description:
I'm trying to create a token in cookie, so that the token will persist for a certain period of time.

public function tokenAuth(Request $request)
{
     try {
         //$token, a random string, is created from input values
     } catch (MyCustomException $e) {
        //Return with a warning message
    }
    $minutes  = time() +  60 * 24 * 30;
    $https    = false;
    $httpOnly = true;
    return response('Hello World')->cookie("MY_JWT", $token, $minutes, '/', env('APP_URL'), $https, $httpOnly);
}

This is an excerpt of a controller class, creating a token with [a third party library](https://github.com/tymondesigns/jwt-auth)

As described in Laravel's documentation, this `cookie( )` function works and I can see the `MY_JWT` cookie after running this function.
However, this cookie disappears after I refresh the page.

I also tried `setcookie( )` function, which resulted in the same situation.

Does anyone know how to keep cookies?

**Comment by themsaid** [comment]
5.3 is not supported anymore, please upgrade to 5.4
