### ISSUE TITLE
Validation Error

### ISSUE THREAD

**Issue by Alejpf** [laravel/framework#19717]
- Laravel Version: 5.3.*
- PHP Version: PHP 7.0.9-1+deb.sury.org~xenial+1 (cli) ( NTS )
- Database Driver & Version: MySql 5.7.18

### Description:
Laravel is updating a database column that it is not supposed to. It should throw a validation exception because `informative_type` is not a valid option.

### Steps To Reproduce:
First obtain the data:
`$data = [
    "informative_type" => "",
    "type" => "Direct"
];`

Then run the validation with the following rules:
`$rules = [`
 `   "type" => "required|in:Commission Tracking,Direct,Informative",`
 `   "informative_type" => "required_if:type,Informative|in:Excursion,Transfer,Other"`
`]`

Then save the model
$myModel->fill($data)->save();

At this point Laravel updates the database column and sets its value to an empty string, which is then given some problems because the database column is an enum where an empty string is not an  option

**Comment by devcircus** [comment]
Based on those rules, it is expected to save.
