### ISSUE TITLE
Ability to change the /config directory

### ISSUE THREAD

**Issue by cedricve** [laravel/framework#19716]
- Laravel Version: 5.4.27
- PHP Version: 7.0.0
- Database Driver & Version: none

### Description:

For my use case we store configuration files on a writable partition, and all other non-changing core functionality goes on a read-only partition. Therefore it would be useful to have the possibility to change the configuration directory.

### Steps To Reproduce:

Similar to useStoragePath, we should have a useConfigPath.

https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/Application.php#L327-L336

A possible solution would be adding this to the `bootstrap/app.php` file.

    /*
    |--------------------------------------------------------------------------
    | Check if running on KiOS
    |--------------------------------------------------------------------------
    |
    | If running on KiOS, data folders are on a different partition.
    |
    */

    $kios = '/data/etc/kios.conf';
    if(file_exists($kios))
    {
        $app->useStoragePath('/data/web/storage');
        //$app->useConfigPath('/data/web/config/');
    }

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
