### ISSUE TITLE
Global Scopes remain on models within testing

### ISSUE THREAD

**Issue by philcross** [laravel/framework#19721]
- Laravel Version: 5.4.27
- PHP Version: 7.1.0
- Database Driver & Version: mysql 5.7.16

### Description:

When making HTTP requests for testing as [described here](https://laravel.com/docs/5.4/http-tests#introduction) if your application makes use of global scopes, then the scopes will remain active outside of the application, within testing.

For example, within my application, I may want to add a global scope which restricts retrieving user modals based on a field. 

I only want this scope to be added inside my application, and not outside the application (IE in the test environment).

I would expect, that after the request has finished, that global scopes that were added within the request, are removed.

Additional reasoning is that the `$this->call()` method in testing is emulating a Guzzle type request. If we were to actually use guzzle, the scope would never be applied in the test environment, and would only live for as long as the request took.

I'm happy to close this, is this is the intended behaviour.

### Steps To Reproduce:

- Within a controller, add a global scope to a modal, and add the route etc `/users/{user}`

```php
public function __construct()
{
    User::addGlobalScope('username', function ($builder) {
        $builder->where('username', '=', 'phil');
    });
}

public function show($user)
{
    // The global scope should be applied because it is within the application
    var_dump((new User)->getGlobalScopes());
}
```

- In your test, run:

```php
function test_scopes()
{
    $response = $this->get('/users/1');
    
    // This shouldn't have the global scope still attached, because it is outside of
    // the application (In the test environment), but it does still have the scope attached
    var_dump((new User)->getGlobalScopes());

    // This won't work:
    User::where('username', '=', 'Brody')->first(); // Doesn't work because username=phil scope is still applied

    // Instead, you need to run:
    Model::clearBootedModels();
    User::where('username', '=', 'Brody')->first(); // Works because scope is now removed

    // or
    User::withoutGlobalScopes()->where('username', '=', 'Brody')->first();
}
```

My thoughts are you shouldn't need to clear global scopes within the test because they should only live within the application.

**Comment by devcircus** [comment]
If your application uses global scopes and you're testing that your application works like it should, why wouldn't you want global scopes? I use global scopes on many applications and absolutely expect them to be applied while testing. If I need a case without them, they're easily removed.
