### ISSUE TITLE
Blade parsing error on closing mustache

### ISSUE THREAD

**Issue by gbaumeister** [laravel/framework#19727]
- Laravel Version: 5.4.25
- PHP Version: 7.0.15

### Description:
Blade fails to parse double closing curly-braces if they are contained within a string.
#### Example-Template
```
{{ '}}' }}
```

Expected behavior would be a compiled template with the following content:
```
<?php echo e('}}'); ?>
```

Instead the compiled template results in the following content, which raises a PHP-Error:
```
<?php echo e('); ?>' }}
```

### Steps To Reproduce:
Create a view with the following content: 
```
{{ '}}' }}
```

**Comment by themsaid** [comment]
Yes there are a few edge cases that are marked as no-fix, you just need to avoid.

Thanks for reporting though :)
