### ISSUE TITLE
Laravel 5.3 Auth not working after disable browser cookies

### ISSUE THREAD

**Issue by thecopt** [laravel/framework#19722]
- Laravel Version: 5.3.31
- PHP Version: 7.0.15
- Database Driver & Version:

### Description:
I use laravel 5.3 Auth system for user authenticate. But I have a problem after disable browser cookie. I can't login to the system. And session delete value after refresh page.

Should you have a holution solve this problem?

**Comment by decadence** [comment]
Session uses cookies. You can't login on any site without cookies I suppose.

**Comment by phpfalcon** [comment]
https://en.wikipedia.org/wiki/HTTP_cookie 🤔
