### ISSUE TITLE
Translate value of validation rule required_if:...

### ISSUE THREAD

**Issue by yopop666** [laravel/framework#19725]
Hello,
I have next configuration:
- Laravel Version: 5.4.27
- PHP Version: 7.1.3
- Database Driver & Version: MariaDB 10.1.23

I want to translate value from  **required_if** validation rule.

In my form request I have 
```
public function rules()
{
    return [
        'encashment.type' => [
            'required',
        ],
        'encashment.series_and_number_id' => [
            'required_if:encashment.type, Receipt',
        ],
    ];
}

```
resources/lang/ro/validation.php
```
...
'required_if'          => 'Câmpul :attribute este necesar când :other este :value .',
...
```
Request
```
[
    'encashment' => [
        'type' => 'Receipt'
    ],
];

```
I get error
_Câmpul Numărul seriei este necesar când Tipul este Receipt ._

The **attribute** and **other** are translated but **value** isn't even if i have `"Receipt": "Chitanţă",` in ro.json. 

I found [#4037](https://github.com/laravel/framework/pull/4037) and i tried to put  in
resources/lang/ro/validation.php
```
...
'value' => array(
    'encashment_type' =>[
        'Receipt' => 'Chitanţă',
    ],
    'encashment[type]' =>[
        'Receipt' => 'Chitanţă',
    ],
    'Receipt' => 'Chitanţă',
),
'values' => array(
    'encashment_type' =>[
        'Receipt' => 'Chitanţă',
    ],
    'encashment[type]' =>[
        'Receipt' => 'Chitanţă',
    ],
    'Receipt' => 'Chitanţă',
),
...
```

Even with this changes the **value** isn't translated.

How can i handle this issue?

**Comment by themsaid** [comment]
The validator doesn't handle values validation, `Receipt` is an input from your user you should display it as is, not sure why you'd want to translate a user input in the validation error.

Anyways, please ask on the forums, this repo is for bug reporting only.

**Comment by Kyslik** [comment]
@themsaid I guess, since page is in different language than English **but** code of the page is in English OP wants to translate input "name" (Receipt) to whatever language site uses, thats why OP wants to translate it.

I would mark this as limitation.

**Comment by yopop666** [comment]
@themsaid 
If I have an select input then in English look like
```
<select name="encashment[type]">
    ...
    <option value="Receipt">Receipt</option>
    ...
</select>
```
and validation message will be 

> The **Series and number** field is required when **type** is **Receipt**.

But in Romanian for example the select will look like:
```
<select name="encashment[type]">
    ...
    <option value="Receipt">Chitanţă</option>
    ...
</select>
```
That mean that the submitted data will be the same, but the displayed "label" will be the one of the language.

And validation message must be 
> Câmpul **Numărul seriei** este necesar când **Tipul** este **Chitanţă**.

Instead of 

> Câmpul **Numărul seriei** este necesar când **Tipul** este **Receipt**. 

Because user see in select option **Chitanţă** not **Receipt**.
