### ISSUE TITLE
[5.4] Validation rule date_format fails when using the # format delimiter

### ISSUE THREAD

**Issue by ziabice** [laravel/framework#19728]
- Laravel Version: 5.4.23
- PHP Version: 7.1.6
- Database Driver & Version: mysql

### Description:

The `date_format` validation rule fails if into the format string is used the _valid_ character `#` (which means "a generic separator char" ).
In Italian language you usually define dates using day-month-year format, using `-` or `/` as separator. Trying to check this kind of dates implies the use of the `#' in the date format string.

The problem is in the file `Illuminate/Validation/Concerns/ValidatesAttributes.php`, the method `validateDateFormat`, the last line is:

    return $date && $date->format($parameters[0]) == $value;

Which causes the problem: when running the `DateTime::format`the expected format is the one accepted by the builtin PHP function `date()`, while when parsing a date the expected format is the one specific to `DateTime::createFromFormat`.

My suggestion is to remove the `$date->format...` part from the last check: this will let even the more exotic formats to be validated (in a way or another).

### Steps To Reproduce:

Using tinker:

    $data = ['date' => '22-03-2017' ];
    $validator = Validator::make($data, ['date' => 'date_format:d#m#Y'] );
    $validator->fails();
    => true
    
    $validator = Validator::make($data, ['date' => 'date_format:d-m-Y'] );
    $validator->fails();
    => false

**Comment by Dylan-DPC** [comment]
Any updates of this? I don't feel it is a bug. You can send in a PR or open a proposal on laravel/internals

**Comment by ziabice** [comment]
It's definitely a bug if you live in a country where dates expressed in a way different than the english one are used.

**Comment by themsaid** [comment]
Feel free to open a PR, I don't see this as an issue with the validator, it uses internal PHP function to validate the format.

**Comment by themsaid** [comment]
Or you can open an issue on https://github.com/laravel/internals repo.
