### ISSUE TITLE
Email Validation of Laravel 5.4 failed

### ISSUE THREAD

**Issue by akbansa** [laravel/framework#19724]
While using laravel validation I found a minor issue that it does not validate emails properly. It means validation do not fails on some emails which are not compliant with IETF standards.

Basically, it passes the emails as **user-name@company-name.x**

So here x is not an acceptable domain name extension.

Have a look into this and fix!

**Comment by decadence** [comment]
Duplicate
https://github.com/laravel/internals/issues/640

**Comment by akbansa** [comment]
@decadence I was waiting there for a long time, but didn't received any response from team

**Comment by decadence** [comment]
Here it will be just closed because this is not a bug.

**Comment by Kyslik** [comment]
@akbansa you need to make your own validation rule and apply your own email validation logic.

**Comment by akbansa** [comment]
@Kyslik That is what I already did
Now I am trying to add that validation in framework

**Comment by themsaid** [comment]
Yes you can define your own validation rule, or feel free to open a PR with a proposed change.

**Comment by Kyslik** [comment]
@akbansa oh I see, my bad, sorry.
