### ISSUE TITLE
Query builder exists not returning boolean

### ISSUE THREAD

**Issue by dericcain** [laravel/framework#19739]
- Laravel Version: 5.4
- PHP Version: 7
- Database Driver & Version: MySQL/sqlite

### Description:
I described an issue #18966 and didn't have the time to reproduce it at the time. When I create a scoped query that uses the method `exists`, it is not returning a boolean when empty but instead an instance of the query builder, which returns true.

### Steps To Reproduce:
```
git clone git@github.com:dericcain/laravel-issue.git
cd laravel-issue && composer install
phpunit
```
To break it down, here is my scoped query:
```
public function scopeAlreadyExists($query, $params)
{
    return $query->where([
          'first_name' => $params['first_name'],
          'last_name' => $params['last_name'],
    ])->exists(); 
}
```

And when I test it with:
```
factory(\App\User::class, 2)->create();

$noUser = User::alreadyExists([
        'first_name' => 'Thomason',
        'last_name' => 'Wilbersonsmithson'
]);

// $noUser = QueryBuilder instead of false
```
Also, when I do `count()` it is the same thing if the count is `0`;

Is there something that I am missing about this?

**Comment by decadence** [comment]
Scope should only add query conditions but not calling get / count / exists and other similar methods.
Laravel expects `Builder` from scope and not query result.

**Comment by dericcain** [comment]
@decadence Interesting, because I can call `get` and get back results so this seems a bit inconsistent. Do you know if it is this way for a reason?

**Comment by decadence** [comment]
Reason is scope is for scoping, not for querying.

You can create static method which calls scope and then exists. Or move wheres in this method if scope isn't used anywhere else.

**Comment by decadence** [comment]
If it would work you can't reuse your scope if you need get or count query because scope would already call query method.

**Comment by dericcain** [comment]
> Reason is scope is for scoping, not for querying.

I see what you are saying, but I must disagree. If that is the intended behavior, then why can I call `get`, `first`, etc? Those are clearly query methods and not scoping methods. 

> You can create static method which calls scope and then exists. Or move wheres in this method if scope isn't used anywhere else.

I understand how to solve the problem, but that isn't the issue at hand. The main point is that it is confusing to allow for some methods and not others. It just isn't consistent and I would love for it to be consistent one way or the other, preferably allowing `count`, `exists`, etc.

> If it would work you can't reuse your scope if you need get or count query because scope would already call query method.

This is a bit irrelevant because I understand the method that I am creating and it would be performing as intended. If I wanted to call another query method on it then I would have created the method to allow another query method to be called.  

Please know that I am not trying to argue for the sake of arguing. I truly want to see this become consistent because I have been bitten by this a couple of times and I'm sure others have as well.

I would gladly make a PR if I thought that it would be accepted. 

@themsaid @taylorotwell Would you consider this?

**Comment by decadence** [comment]
You can call it because you operate with Builder and it doesn't separate methods on scoping or querying.
Laravel should check scope doesn't call query methods I agree.
I got your point but I believe this behavior won't be changed.

**Comment by decadence** [comment]
By the way we have in docs this note:
`Scopes should always return a query builder instance` which is not fully true. AFAIK you can just apply methods on Builder, returning is not necessary. Anyway it says you can't return result of `exists` method.

**Comment by dericcain** [comment]
@decadence I see that now. Hmm... I feel that it would be pretty powerful to have the ability to do both. The only downside is the wording **scope**, which wouldn't really describe what is being done at that point. You may be right - this may not be changed but I know it has left me confused on more than one occasion.

**Comment by decadence** [comment]
You also can extend Builder with `macro` method but it applies on every Model not just Users.

I want to hear @taylorotwell opinion about quering possibility in scopes in future too. But I still don't think it will be changed anyhow.

**Comment by dericcain** [comment]
I would love for him to chime in as well. Thanks for your input and insight on this issue.

**Comment by themsaid** [comment]
Yes your use case is not right, scopes are for adjusting the underlaying query.

Anyways, feel free to open a PR with a proposed change or 
for suggestions and feature requests please use the https://github.com/laravel/internals repo.

**Comment by Bipeen123Kumar** [comment]
status  active and inactive laravel code need me
