### ISSUE TITLE
[5.4] Blade: ##parent-placeholder-...## not replaced for @parent directive if section name is a function call, a variable or a constant

### ISSUE THREAD

**Issue by bradacjan** [laravel/framework#19736]
- Laravel Version: 5.4.27
- PHP Version: 5.6.7
- Database Driver & Version: MySQL 5.7, but that is irrelevant

### Description:
If an expression (fucntion call, variable, etc.) is used to define the name of blade section (e.g. `@section(Sections::content())`), then the name of the parent placeholder for the `@parent` blade directive (e.g. `##parent-placeholder-46d6d7b020c50d2d69b1e49da3947a60dd12054f##`) at _compile time_ does not match the one at _evaluation time_ .

_An example is provided below._

That is because during the compilation the static method `Illuminate\View\Concerns\ ManagesLayouts::parentPlaceholder` is called with the literal function call string (e.g. `Sections::content()`) in `Illuminate\View\Compilers\BladeCompiler::compile`.
But then during the evaluation it is called with the function's evaluated value (e.g. `content`)  in `Illuminate\View\Engines\PhpEngine::evaluatePath` .

That is a change from 5.3, where the `@parent` directive evaluation was handled differently and the provided example would work fine.

This is not just an issue with function calls - constants or variables used to define the section name will cause the same issue. _Yes, string literal is technically also an expression, but my point should be clear now._

#### Solution proposal:
I have spent some time trying to resolve this issue and I would like to submit a PR to fix this, but I believe that it is a fundamental flaw of the new `@parent` compilation mechanism (via a placeholder) and cannot be simply hotfixed. 

If the `$__env->startSection(...)` method could somehow pass along the literal `Sections::content()` along with it's evaluated value (`content`), then the problem could easily be resolved by using the same literal form for the resolution of parent-placeholder during the evaluation (i.e., the evaluation would know the section's "name" used during compilation and therefore be able to recreate the section name's hash). 

But that would require compiling into a bit different form, i.e. `$__env->startSection(Sections::content(), 'Sections::content()')`  and then passing the second argument further on.

That might be the way to go, but it seems less than optimal to me. So I'd expect we might need to look for a different, more elegant solution.

#### Blade templates:
`the-template.blade.php` - The main template, simillar to Laravel's default app.blade.php .
```

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
    </head>
    <body>
        <div>
            <section class="content">
                @yield(\App\Sections::content())
            </section>
        </div>
    </body>
</html>
```

`the-parent.blade.php` - The parent template, provides some part of the content.
```
@extends('the-template')

@section(\App\Sections::content())
    The parent part.
@endsection
```

`the-child.blade.php` - The child. Adds some content to the parent template's content, but cannot simply `@append` it, has to use `@parent` (the example is simplified).
```
@extends('the-parent')

@section(\App\Sections::content())
    @parent
    The child part.
@overwrite
```

#### PHP Class:
A super-simple example, could have some more complex logic (we use a facade for this in our application).

```
<?php
namespace App;


class Sections
{
    public static function content()
    {
        return 'content';
    }
}
```
#### Desired output:
`The parent part. The child part.`
#### Actual output:
`##parent-placeholder-46d6d7b020c50d2d69b1e49da3947a60dd12054f## The child part.`

**Comment by themsaid** [comment]
That's a limitation that you have to consider, section name has to be static not dynamic. Not a function call or a variable.

**Comment by bradacjan** [comment]
If a constant (in the sense of MyClass::MY_CONSTANT) is not static enough, then what is? ☺

I do understand the limitations and I did manage to accomodate our project to this change (hopefuly only temporarily), but the fact that this feature (dynamic section names) is only broken by this new way of resolving the `@parent` directive, seems quite unfortunate to me. 

Also, dynamic section names are sometimes the only way of implementing certain usecases. If I am not mistaken, I recall reading Taylor's reply in a certain issue here on github regarding to how yields and sections should work. He or another moderator specifically mentioned that you actually HAVE to use dynamic section names.

For example, our real usecase:
Imagine that you have a button component, that is rendered multiple times on the page. And imagine, that multiple button types share the same basic template, but override certain sections (we basically have multiple classes of buttons, simillar to Laravel's own Form::button() ). But then, if you want multiple instances of the same button on the same page, you have to provide each instance with it's own unique section id, because otherwise the sections yielded by other button instances would be written into by other button instances (and for N buttons you would end up with N versions inside each yielded section, instead of 1 version per each of the N yields).

I.e., you cannot define the section as `@section('button-body')`, you have to define it as `@section('button-body-' . $buttonId)`, otherwise it would just straight up not work. 

I am quite lucky that we never use this mechanism along with `@parent` in our application, so I could in fact hotfix this for myself.

But dynamic section names are, according to the example I have given, a necessary feature for Blade templates.

Did I convince you, or should I look for the aforementioned issue for reference?

**Comment by themsaid** [comment]
I'd just use conditions in your case, but this is a known limitation. We hope one day it'll get fixed, feel free to propose a solution if you have any :)

Thanks for the follow up

**Comment by ay232** [comment]
Try to write in the end of 
@section('XXX')
@parent
    ------------- your content here ------------
@stop

If you write stop you can decide you probleb in some sutuations.
