### ISSUE TITLE
Mix Freakout

### ISSUE THREAD

**Issue by timgavin** [laravel/framework#19744]
- Laravel Version: 5.4.27
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7.17

### Description:
Was working on a SASS file using `npm run watch`, hit save and started receiving well over a 150 messages from the `terminal-notifier`; it's as if Mix was stuck in a loop.

![screen shot 2017-06-23 at 8 28 09 pm](https://user-images.githubusercontent.com/1012049/27504257-5f32fbdc-5854-11e7-96ab-8270f30939fb.jpg)

This message printed out over 150 times until I halted it.

```
 WAIT  Compiling...
 95% emitting
 DONE  Compiled successfully in 31ms
```

### Steps To Reproduce:

I ran `npm run watch` again and it started all over. Have no idea what could be causing this or how to reproduce, other than just running `npm run watch`

**Comment by devcircus** [comment]
Sounds like you're watching a compiled file, so it notices a change and recompile, notices a change and recompiles....ad infinitum

**Comment by timgavin** [comment]
I don't know about that. Mix was working just fine for hours and then all of a sudden went bananas.

This is my `webpack.mix.js` file

```
let mix = require('laravel-mix');

mix.js('resources/assets/js/app.js', 'public/js')
    .sass('resources/assets/sass/app.scss', 'public/css');
    
mix.styles([
    'resources/assets/css/jquery-anyslider.css',
    'resources/assets/css/bootstrap-datetimepicker.min.css'
], 'public/css/all.css');

mix.copy('resources/assets/js/bootstrap-datetimepicker.min.js', 'public/js/bootstrap-datetimepicker.min.js');
```

**Comment by devcircus** [comment]
Maybe not, but the same thing has happened to me and it turned out that I was referencing a file in my app.js that I was later manipulating in another way and it kept recompile get forever because it was watching a compiled file. Tough to say without seeing your setup. 
I'd start at the bottom of my mix file and remove one line at a time until something changes.

**Comment by Dylan-DPC** [comment]
I think its better to create an issue on https://github.com/JeffreyWay/laravel-mix

**Comment by timgavin** [comment]
Figured it out.

In my SASS file I'm referencing images in the `public` folder like so

```
background-image: url('../images/slide6.jpg');
```

Changing it to the following stopped Mix from going cuckoo bananas.

```
background-image: url('/images/slide6.jpg');
```

I'll open this on Jeffrey's repo.
