### ISSUE TITLE
Updating a model without primay key causes an error.

### ISSUE THREAD

**Issue by krecebli** [laravel/framework#19748]
- Laravel Version: 5.24.27
- PHP Version: 7.0.20-2
- Database Driver & Version: MySQL 5.7.18

### Description:
I have some models that have composite primary keys. Since Laravel doesn't support composite primary keys, I set the `primaryKey` property to `null`. Now, I got this error:

`Unknown column '' in 'where clause' (SQL: update `table` set `column` = lorem where `` is null)`

So, what should I do? Thanks in advance!

### Steps To Reproduce:
Just set the `primaryKey` property to `null` and try to update a model.

**Comment by themsaid** [comment]
You can't set primaryKey to null on an eloquent model, I suggest that you use the query builder for this use case or add a primary key for eloquent to work.

**Comment by krecebli** [comment]
I have a primary key, but it is composite. And when I assign one of primary keys to the `primaryKey`, it updates all rows with that value.
