### ISSUE TITLE
can not use `push([ ... ])` in column `$cast` as `collection` when null

### ISSUE THREAD

**Issue by ninjaparade** [laravel/framework#19743]
- Laravel Version: 5.4.19
- PHP Version: 7.1.4
- Database Driver & Version: Not required.

### Description:
Working with a model that has a column `$cast` as `collection` when trying to save an initial value, ie the `$zmodel->column = null`, I can not `->push([ ... ])` any values.

Instead I need to do  

```
$zmodel->column = $zmodel->column->push(['Adam' => 'Wathan']);
```

expected
```
$zmodel->column->push(['Adam' => 'Wathan']);
```

**Comment by paulredmond** [comment]
@ninjaparade I wanted to cast attributes recently too.

I noticed in the documentation (and source diving) that you have to set the property back. There's really no way around it with dynamic attributes, unless I am missing something obvious (happens all the time 😄 )

```
$user = App\User::find(1);
$options = $user->options;
$options['key'] = 'value';
$user->options = $options;
$user->save();
```

That's the very last code example in the [documentation](https://laravel.com/docs/5.4/eloquent-mutators#attribute-casting).

**Comment by robjbrain** [comment]
+1 seeing this too. Very confusing at first.

**Comment by darron1217** [comment]
There was conversation about this issue on internal repo https://github.com/laravel/ideas/issues/460

And I created some PRs and got rejected...
https://github.com/laravel/framework/pull/24508
https://github.com/laravel/framework/pull/24527

**Comment by ThomasRitter75** [comment]
As a general question to the main developers regarding this issue: Laravel casts the attribute on every access. It would make *much* more sense to instead cast on Model load/save only. That way, casted attributes would be modifiable and if the dirty check before save is done after casting (on a copy of the attributes array with all attributes casted to how they belong into the database), this would not need much changes in existing Eloquent code. Would this be a welcome change in Laravel or not?

**Comment by driesvints** [comment]
Heya. Thanks for sending this in. Gonna close this in favor for https://github.com/laravel/ideas/issues/460 so please continue the discussion there.
