### ISSUE TITLE
Foreign Key Constraint Raises Issue

### ISSUE THREAD

**Issue by xyrintech** [laravel/framework#19751]
- Laravel Version: 5.4
- PHP Version: 7.0
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.5.54, for debian-linux-gnu (x86_64) using readline 6.3

Getting this error when trying to create migration.
SQLSTATE[HY000]: General error: 1005 Can't create table '#sql-3723_165' 

### Steps To Reproduce:

       Schema::table('customer_addresses', function (Blueprint $table) {
            $table->foreign('customer_id')->references('id')->on('customers')->onDelete('cascade');
        });

**Comment by sisve** [comment]
Can you verify that both tables (customer_address and customers) use innodb, and both columns (customer_address.customer_id and customers.id) are of the same type (usually unsigned int)?

**Comment by themsaid** [comment]
Please ask on the forums, this doesn't seem like  a bug in the core.
