### ISSUE TITLE
causedByDeadlock() assumes MySQL returns errors in English.

### ISSUE THREAD

**Issue by connerbw** [laravel/framework#19752]
### Description:

I was checking out the automatic deadlock detection code and I noticed that instead of checking for an error number or exception type, it checks if the string contains text?

[FYI MySQL errors are not always in English](https://dev.mysql.com/doc/refman/5.5/en/error-message-language.html).

If the underlying DB is PDO then I would propose checking for something like:

```
     $e instanceof PDOException &&
     $pdo->getAttribute(PDO::ATTR_DRIVER_NAME) == 'mysql' &&
     $e->errorInfo[0] == 40001 &&
     $e->errorInfo[1] == 1213
```

PS: Awesome feature!

### Steps To Reproduce:

Current code in master branch:

https://github.com/laravel/framework/blob/master/src/Illuminate/Database/DetectsDeadlocks.php

    protected function causedByDeadlock(Exception $e)
    {
        $message = $e->getMessage();
        return Str::contains($message, [
            'Deadlock found when trying to get lock',
            'deadlock detected',
            'The database file is locked',
            'database is locked',
            'database table is locked',
            'A table in the database is locked',
            'has been chosen as the deadlock victim',
            'Lock wait timeout exceeded; try restarting transaction',
        ]);
    }

**Comment by connerbw** [comment]
PS: SQLite error codes are `SQLITE_BUSY (5), SQLITE_LOCKED (6)`

https://sqlite.org/rescode.html

**Comment by connerbw** [comment]
The Microsft SQL Server-specific error code for a deadlock is 1205

https://www.codeproject.com/Articles/42547/SQL-SERVER-How-To-Handle-Deadlock

**Comment by connerbw** [comment]
PostgreSQL deadlock codes are 40P01 and 55P03

https://www.postgresql.org/docs/9.4/static/errcodes-appendix.html

**Comment by laurencei** [comment]
This would also apply to detecting a lost connection - it also looks for english string errors there.

**Comment by themsaid** [comment]
I don't think this will work for all DB engines Laravel supports.

**Comment by connerbw** [comment]
> I don't think this will work for all DB engines Laravel supports.

Oh? I posted links to the error codes for MySQL, Postgresql, SQLite, and SQL Server in the comments. Which other DB engines does Laravel support?

**Comment by connerbw** [comment]
Todo: Tests, peer review, improve code:

```php
protected function causedByDeadlock(Exception $e)
{
    $driver = $this->getDriverName();
    if ($e instanceof \PDOException && in_array($driver, ['mysql', 'pgsql', 'sqlsrv', 'sqllite'])) {
        foreach ($e->errorInfo as $errorInfo) {
            if ($driver == 'mysql' && $errorInfo == 1213) {
                // @see https://dev.mysql.com/doc/refman/5.7/en/innodb-deadlock-example.html
                return true;
            }
            if ($driver == 'pgsql' && $errorInfo == '40P01') {
                // @see https://www.postgresql.org/docs/9.4/static/errcodes-appendix.html
                return true;
            }
            if ($driver == 'sqlsrv' && $errorInfo == 1205) {
                // @see https://www.codeproject.com/Articles/42547/SQL-SERVER-How-To-Handle-Deadlock
                return true;
            }
            if ($driver == 'sqllite' && $errorInfo == 6) {
                // @see https://sqlite.org/rescode.html#locked
                return true;
            }
        }
    } else {
        // Fallback to english language string detection
        $message = $e->getMessage();
        return Str::contains(
            $message, [
                'Deadlock found when trying to get lock',
                'deadlock detected',
                'The database file is locked',
                'database is locked',
                'database table is locked',
                'A table in the database is locked',
                'has been chosen as the deadlock victim',
            ]
        );
    }
    return false;
}
```

**Comment by themsaid** [comment]
For suggestions and feature requests let's use the https://github.com/laravel/internals repo, we'll check this again by the release of 5.6 and see if there's something we can do about it that's solid enough.

Meanwhile, use english as your DB language.
