### ISSUE TITLE
PHPUnit: Trait 'Illuminate\Foundation\Testing\FreshDatabase' not found

### ISSUE THREAD

**Issue by alex996** [laravel/framework#19754]
- Laravel Version: 5.5.* (master)
- PHP Version: 7.1.5
- Database Driver & Version:  MariaDB 10.2.5

### Description:
In the latest version of Laravel, when you make a new test with the artisan console command, the test class will import a non-existing trait called `FreshDatabase`:

```php
use Illuminate\Foundation\Testing\FreshDatabase
```

The proper name should be **RefreshDatabase** instead. The steps below demonstrate that PHPUnit will throw a fatal error because `FreshDatabase` trait does not exist.

### Steps To Reproduce:

_Prepping_:
- Pull in the latest dev release `laravel new app --dev`
- Run `php artisan key:generate`

_Actual steps_:
1. Make a sample feature test: `php artisan make:test SampleTest`
2. Use the `FreshDatabase` trait which is auto-imported at the top: `use FreshDatabase;`
3. Run the test: `phpunit tests/Feature/SampleTest.php`
4. Get an error (or similar):

```
Fatal error: Trait 'Illuminate\Foundation\Testing\FreshDatabase' not found in
C:\laragon\www\forum\tests\Feature\SampleTest.php on line 10
```

**Comment by Douglasdc3** [comment]
Since the PR has been merged this issue can be closed
