### ISSUE TITLE
[ErrorException]   mb_strpos(): Argument is empty

### ISSUE THREAD

**Issue by recrypto** [laravel/framework#19763]
- Laravel Version: 5.4.23
- PHP Version: PHP 7.1.6-1~ubuntu16.04.1+deb.sury.org+1 
- Database Driver & Version: 5.7.18-0ubuntu0.16.04.1 

### Description:
For some odd reasons, I'm getting this issue.

### Steps To Reproduce:
\Illuminate\Support\Str::contains('author', '.');

**Comment by recrypto** [comment]
Oh, sorry for the incomple info. I've traced it down to $key = $this->removeTableFromKey($key); on Eloquent Model. I don't know for some odd reasons why its occurring this when I'm doing mass assignment creation of models. :(

**Comment by recrypto** [comment]
My hotfix I ended was I created a Trait that disables the removeTableFromKey method to one of the models I used.

trait HasDisabledRemoveTableFromKey
{

    /**
     * Fill the model with an array of attributes.
     *
     * @param  array  $attributes
     * @return $this
     *
     * @throws \Illuminate\Database\Eloquent\MassAssignmentException
     */
    public function fill(array $attributes)
    {
        $totallyGuarded = $this->totallyGuarded();

        foreach ($this->fillableFromArray($attributes) as $key => $value) {
            // $key = $this->removeTableFromKey($key);

            // The developers may choose to place some attributes in the "fillable" array
            // which means only those attributes may be set through mass assignment to
            // the model, and all others will just get ignored for security reasons.
            if ($this->isFillable($key)) {
                $this->setAttribute($key, $value);
            } elseif ($totallyGuarded) {
                throw new MassAssignmentException($key);
            }
        }

        return $this;
    }
}
`

-----

My model is called "App\Posts" with table name = "re_posts" with an attribute "author"

**Comment by themsaid** [comment]
Please ask on the forums.

**Comment by themsaid** [comment]
This repo is for bug reporting only, and I can't seem to find a proper bug report here. Sorry :)

**Comment by recrypto** [comment]
No problem about that. Thanks. :)
