### ISSUE TITLE
NotFoundHttpException in RouteCollection.php (line 179)

### ISSUE THREAD

**Issue by Chathula** [laravel/framework#19766]
- Laravel Version: 5.4.*
- PHP Version:  PHP 7.0.19-1~dotdeb+8.1
- Database Mysql & 14.14 Distrib 5.5.55:

### Description:
i put laravel on nginx.
but it always show me this error. it works well on localhost
i tried everything...

set permissions to 777..
added a test route /, but the same error.

added a custom index.php file to public folder,  then it works well on / route. but it doesn't work on index.php route. is it an issue? 

i created a fresh project. i got the same error. 

This is my nginx conf

```
       server_name my_server_name;
        root /var/www/html/iconic/public;
        index index.html index.htm index.php;
       location /iconic {
                try_files $uri $uri/ /index.php?$query_string;
       }
        location ~ \.php$ {
                include snippets/fastcgi-php.conf;
                fastcgi_pass unix:/run/php/php7.0-fpm.sock;
                fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
       }
        location ~ /\.ht {
                deny all;
        }
```

Screenshot of error...

![Route Issuet](http://i.imgur.com/6ta11KA.png)

**Note: i am running another nodejs servers on nginx via reverse proxy. all of them are working well.**

**Comment by Chathula** [comment]
Index route only works on my HOST url.(/)

**Comment by Dylan-DPC** [comment]
You could be having nginx issues. I would suggest try the Laravel forums or slack channel to resolve your issue

**Comment by Chathula** [comment]
@Dylan-DPC , i tried ! i couldn't.. it works well on root / path, but doesn't work on subfolder.. i will close this!!

**Comment by cgrwllc** [comment]
Anyone have the resolving way for this?

**Comment by lucaslz** [comment]
Try:

location /iconic {
                rewrite ^/iconic/?(.*)$ /$1 break;
                try_files $uri $uri/ /index.php?$query_string;
}
