### ISSUE TITLE
@parent being stripped out of string by blade

### ISSUE THREAD

**Issue by samcambridge** [laravel/framework#19776]
- Laravel Version: 5.3.30
- PHP Version: 7
- Database Driver & Version:  mysql

### Description:
The string `@parent` is being stripped out of strings when used within `@section`, I think this is a blade bug. Usually this wouldn't be a problem (well it's a problem but it's an edge case), however I have a user with an email containing `@parent` and my system involves emailing these users via a web form.

The `@parent` part of the email is stripped out meaning unless the admins know of this issue they don't know why there isn't a valid email address.

This seems to have be recognised a while ago: https://www.reddit.com/r/laravel/comments/2y0iuu/beginner_blade_question/

This happens from within `{{ "xyz@parent.com" }}`, `{!! "xyz@parent.com" !!}` and `<?php echo "xyz@parent.com"; ?>`

### Steps To Reproduce:

Using blade echo out "xyz@parent.com" within an `@section` closure, you will see "xyz.com".

**Comment by sisve** [comment]
A note; `@parent` is a Blade keyword, and it's not being stripped, it's being replaced with a previously rendered section. I just happens to be blank in your case. There's an example of `@parent` at https://laravel.com/docs/5.4/blade under the section Extending A Layout.

**Comment by themsaid** [comment]
Please upgrade to 5.4, 5.3 is not supported.
