### ISSUE TITLE
Index Methods for Eloquent - Would PR Be Accepted?

### ISSUE THREAD

**Issue by BrandonSurowiec** [laravel/framework#19772]
I saw this talk last month "RailsConf 2017: The Secret Life of SQL: How to Optimize Database Performance by Bryana Knight": https://www.youtube.com/watch?v=BuDWWadCqIw

Bryana is an engineer at Github and shows how to optimize your database with indexes and even denormalization if necessary. I learned a lot and it would be useful to have an easy way in eloquent to use the following methods:

* FORCE INDEX() 
* USE INDEX() 
* IGNORE INDEX()

(From my understanding these commands are not supported in PostgreSQL.)

This is an old issue request from a few years ago to ask whether a PR would be accepted which Taylor felt at the time was unnecessary. https://github.com/laravel/framework/issues/4625

Would it be accepted now? Don't want to waste my time if not.

Currently we can't do something nice like `Post::forceIndex('index_to_use')->...` and need to do `Post::from(DB::raw('posts FORCE INDEX(index_to_use)')->...` 

Thoughts?

**Comment by browner12** [comment]
looks interesting.

suggestions and discussion should be moved into https://github.com/laravel/internals or the Slack channel.

**Comment by BrandonSurowiec** [comment]
Sure, I can close this and post over there.

**Comment by BrandonSurowiec** [comment]
Posted here: https://github.com/laravel/internals/issues/652
