### ISSUE TITLE
comment() method for migrations doesn't escape the string correctly

### ISSUE THREAD

**Issue by StygianTraveler** [laravel/framework#19779]
- Laravel Version: 5.4.27
- PHP Version:  7.1.2
- Database Driver & Version: MySQL 5.7

### Description:

If you set a comment on a column during a migration using the comment() method, an exception is thrown if the comment string contains an apostrophe. Obviously, it's very easy to escape it manually, but still, that should be taken care of by the framework, I feel.

### Steps To Reproduce:

Run the following migration class:

```
<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class TestCommentBug extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('test_table', function (Blueprint $table) {
            $table->string('test')->comment("this doesn't work");
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('test_table');
    }
}
```

**Comment by Douglasdc3** [comment]
I have identified the issue in `Illuminate\Database\Schema\Grammars\MySqlGrammar`

```
    protected function modifyComment(Blueprint $blueprint, Fluent $column)
    {
        if (! is_null($column->comment)) {
            return " comment '".$column->comment."'";
        }
    }
```

I could write a test & fix for this issue by using `addslashes` php function. I want to make sure this is the best place and way to fix the issue before creating a PR.
