### ISSUE TITLE
Wrong Route defaults method behaviour

### ISSUE THREAD

**Issue by decadence** [laravel/framework#19796]
- Laravel Version: 5.4.27
- PHP Version: 7.0.4
- Database Driver & Version: MySQL 5.6 (Not Relevant)

### Description:
AFAIK route params are passed to action from left to right order.
But method `defaults` on `Route` instance works wrongly when URL have no optional params values and when you pass params to `defaults` in other order.

### Steps To Reproduce:
```php
Route::get("test/{foo?}/{bar?}", function ($foo, $bar) {
    echo "foo is {$foo}<br>";
    echo "bar is {$bar}";
})->defaults("bar", "bar")
    ->defaults("foo", "foo");
```
URL `test` outputs:
```
foo is bar
bar is foo
```
while it should be:
```
foo is foo
bar is bar
```

if we have URL `test/foo` it works normal.

**Comment by themsaid** [comment]
I've got the correct values in a fresh 5.4 installation:

```
foo is foo
bar is bar
```

```
Route::get("test/{foo?}/{bar?}", function ($foo, $bar) {
    echo "foo is {$foo}<br>";
    echo "bar is {$bar}";
})->defaults("bar", "bar")
    ->defaults("foo", "foo");
```

**Comment by decadence** [comment]
It's strange.
I installed fresh Laravel 5.4.28 and still have this.
Maybe it's relevant: I'm on Windows 10, Apache.

Do you hit `test/` URL?

Will try test on Linux.
![screenshot_1](https://user-images.githubusercontent.com/1434668/27795756-f8ceddde-600f-11e7-94ea-0be993abfda3.png)

**Comment by decadence** [comment]
Same on Linux

**Comment by themsaid** [comment]
Ah, looks like the order of declaring defaults matter, you need to declare in the same order of the parameters in the method signature.

```
Route::get("test/{foo?}/{bar?}", function ($foo, $bar) {
    echo "foo is {$foo}<br>";
    echo "bar is {$bar}";
})->defaults("foo", "foo")->defaults("bar", "bar");
```

**Comment by decadence** [comment]
Of course order is important. This is all about this bug. Do I need specify correct order or maybe Laravel should check it for me? I think second more appropriate.

**Comment by themsaid** [comment]
Yes you need to specify the correct order while declaring defaults.

**Comment by decadence** [comment]
Ok I see you don't consider this as a bug.
