### ISSUE TITLE
[Request] chunkForDelete()

### ISSUE THREAD

**Issue by rafis** [laravel/framework#19810]
We have `chunk()` method in two `Builder` classes. But it doesn't work for `delete()`. Can we add similar method which would support `delete()`?
Issue is described [here](http://www.krucas.com/2015/11/database-chunk-delete/).

Here is preliminary pull request: https://github.com/laravel/framework/pull/19816
The only issue that I see is that it can lead to infinte loop if a developer will forget to call delete in the callback. We can count how much delete event was triggered on the `$results`, if it differes from `$countResults` then trigger an error.

**Comment by vlakoff** [comment]
Agree with Taylor in #19816, this use case is too specific to add such a flag.

For the case described in your linked article, if you want to write the query only once, you can do:
```php
do {
    $items = Advertisement::take(50)->get();

    foreach ($items as $item) {
        // pre-delete actions, that can't be handled by events
        $item->delete();
        // post-delete actions, that can't be handled by events
    }

} while (count($items) > 0);
```

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
