### ISSUE TITLE
\Illuminate\Http\Response::isRedirection() and 304 Not Modified

### ISSUE THREAD

**Issue by mingalevme** [laravel/framework#19819]
- Lumen Version: 5.4.6
- PHP Version: 7.1.x
- Database Driver & Version:

### Description:
I think that 304 Not Modified is not a redirection response, is not so?
```
public function isRedirection()
{
    return $this->statusCode >= 300 && $this->statusCode < 400;
}
```

**Comment by themsaid** [comment]
Based on https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

3xx statuses are all considered redirection.
