### ISSUE TITLE
[5.4] Possible issue with overriding middleware 😥

### ISSUE THREAD

**Issue by itsash--** [laravel/framework#19813]
- Laravel Version: 5.4
- PHP Version: 7.1.4

### Description:

When a middleware is configured in `Http\Kernel.php` under `$middlewareGroup`, it appears the middleware is not properly overwritten.

For example I am currently using the `throttle:30,1` middleware inside of the `api` group, however on specific end-points I wish to override this, for example:

```php
$router->post('thing')->middleware('throttle:3,30');
```

I expect to be able to successfully send 3 of these requests every 30 minutes, in fact it only runs 2 times before the '429 Too many requests' error.  Once I get more time i'd happily look into it a bit more... For now my work around was to use `throttle:4,30` and commented a todo 😅 🤘

**Comment by sisve** [comment]
A quick thought; wouldn't this add the middleware twice to the pipeline? So you end up having the first one (`throttle:30,1`) block requests early in the chain, without ever asking `throttle:3,30`?

**Comment by itsash--** [comment]
@sisve That's what I suspect to be the problem... I briefly looked in the code and whilst it does merge the middleware arrays, being within a group it doesn't actually replace the original and like you say adds a second middleware call.

Hopefully next week, onceI get a chance I can look into it/make a PR.

**Comment by themsaid** [comment]
There's no guarantee that middleware is unique and applied only once, you need to take care of that in your app, this is no bug, if you're willing to propose a change please do that on the master branch since it's a breaking change.
