### ISSUE TITLE
[5.4] Bug in model.

### ISSUE THREAD

**Issue by ThunderBirdsX3** [laravel/framework#19817]
- Laravel Version: 5.4.27
- PHP Version: 7.1.5
- Database Driver & Version: 5.7.18

### Description:
I got error when store data to database.

> (2/2) QueryException
> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mcautobot.data' doesn't exist (SQL: insert into `data` (`source_type`, `source_data`, `message`, `created_at`) values (user, {"userId":"U206d25c2ea6bd87c17655609a1c37cb8"}, Hello, world, 2017-06-29 05:21:39))
> (1/2) PDOException
> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mcautobot.data' doesn't exist

My model is `Data`;

```
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Data extends Model
{
  protected $fillable = ['source_type', 'source_data', 'message'];

  protected $casts = [
    'source_data' => 'array'
  ];

  const UPDATED_AT = null;
}
```

Call from controller `Data::create($data);`.

It must to add `protected $table = 'datas';` to Model to make it work.

### Steps To Reproduce:
In usual it should call to database table `datas` right? With `class Data extends Model` right?

**Comment by vlakoff** [comment]
I guess that's because Laravel uses a pluralizer class, and "data" is invariant.

**Comment by ntzm** [comment]
https://en.wikipedia.org/wiki/Data_(word)

> The word data has generated considerable controversy on if it is a singular, uncountable noun, or should be treated as the plural of the now-rarely-used datum.

The library Laravel uses for pluralising words (doctrine/inflector) says the plural of 'data' is 'data'

**Comment by vlakoff** [comment]
I'm not a native speaker, but "datas" looks very strange to me.

Long story short, the solution is simply to add `protected $table = 'datas';`

**Comment by themsaid** [comment]
> The library Laravel uses for pluralising words (doctrine/inflector) says the plural of 'data' is 'data'

That's it
