### ISSUE TITLE
Raw data attachment was sent as email body when body is blank

### ISSUE THREAD

**Issue by hthuong09** [laravel/framework#19837]
- Laravel Version: 5.3
- PHP Version: 5.6
- Database Driver & Version: MariaDB 5.5

### Description:
Raw data attachment was sent as email body when body is blank.

### Steps To Reproduce:
```php
Mail::send([], [], function($message) use($data) {
    $message->attachData('hello', 'request.txt', ['mime' => 'text/plain']);
    $message->to('myemail@gmail.com');
    $message->subject('Testing');
    $message->setBody('', 'text/html');
});
```

Messsage I received:
```
--_=_swift_v4_1498809084_f9f505b29d1834688f3a38b120dbf08a_=_ Content-Type: text/plain; name=request.txt Content-Transfer-Encoding: base64 Content-Disposition: attachment; filename=request.txt aGVsbG8= --_=_swift_v4_1498809084_f9f505b29d1834688f3a38b120dbf08a_=_--
```

**Comment by themsaid** [comment]
Sorry but 5.3 is not supported anymore, please test on 5.4 and report back if the issue still present.

**Comment by hthuong09** [comment]
@Corys8646 please create new issue.

**Comment by Zanark** [comment]
@hthuong09 I got the same issue. Do you have a reference to an issue that might have an answer unlike this one.

**Comment by bbashy** [comment]
Having the same issue on latest Laravel (5.7.12). Was working in previous versions fine.

**Comment by pierreberchtold** [comment]
Having the issue with Laravel 5.7

**Comment by konohanaruto** [comment]
> Mail::send([], [], function($message){ $message->attachData('hello', 'request.txt', ['mime' => 'text/plain']); $message->to('myemail@gmail.com'); $message->subject('Testing'); $message->setBody('', 'text/html'); });

It doesn't seem to support the setBody method, I solved this problem by forcing the use of the view mail template.It looks like the following:
```
// emails.example  => resource/views/emails/example.blade.php 
Mail::send(['html' => 'emails.example'], [], function($message){
    message->from('fromMail'); // It's a must
    $message->to('myemail@gmail.com');
    $message->subject('Testing');
});
```
hope this helps...

**Comment by sushilthapa98** [comment]
> I just ran into this on 5.6. Had a mailable that was working great in 5.5, after upgrading to 5.6 when sending an attachment to an email with a blank body, it was putting the attachment in the body. Using the same code as above.
> 
> Laravel version: v5.6.17
> 
> ```
> Mail::send([], [], function($message){
>     $message->attachData('hello', 'request.txt', ['mime' => 'text/plain']);
>     $message->to('myemail@gmail.com');
>     $message->subject('Testing');
>     $message->setBody('', 'text/html');
> });
> ```
> 
> results in this in the body
> 
> ```
> --_=_swift_1524068407_2401445d42a99f78596c7130ace3de39_=_ Content-Type: text/plain; name=request.txt Content-Transfer-Encoding: base64 Content-Disposition: attachment; filename=request.txt aGVsbG8= --_=_swift_1524068407_2401445d42a99f78596c7130ace3de39_=_--
> ```
> 
> putting a string in the body, fixes the problem.

Solved my issue by adding text in body. Thanks a lot.
