### ISSUE TITLE
withoutOverlapping do not create mutex file.

### ISSUE THREAD

**Issue by Litiano** [laravel/framework#19833]
- Laravel Version: v5.4.27
- PHP Version: 7.0.15
- Database Driver & Version: SQLServer 2008

### Description:
withoutOverlapping do not create mutex file.

### Steps To Reproduce:
        $schedule->call(function (){
           sleep(90); 
        })->name("teste")->withoutOverlapping();

**Comment by Litiano** [comment]
https://github.com/laravel/framework/pull/19466/commits/948eabf8c56b2512224435dd5baff6bee112d2c2


Reverting this commit will solve the problem.

**Comment by Litiano** [comment]
$this->withoutOverlapping is false and break if.

**Comment by themsaid** [comment]
thanks :)

**Comment by Litiano** [comment]
Will not you create a version?

**Comment by themsaid** [comment]
will do
