### ISSUE TITLE
I had my Laravel 5.3 working well, I was happy.

### ISSUE THREAD

**Issue by trunghauvt191994** [laravel/framework#19830]
Fatal error: Uncaught ReflectionException: Class config does not exist in /home/u912734456/public_html/local/vendor/laravel/framework/src/Illuminate/Container/Container.php:729 Stack trace: #0 /home/u912734456/public_html/local/vendor/laravel/framework/src/Illuminate/Container/Container.php(729): ReflectionClass->__construct('config') #1 /home/u912734456/public_html/local/vendor/laravel/framework/src/Illuminate/Container/Container.php(608): Illuminate\Container\Container->build('config') #2 /home/u912734456/public_html/local/vendor/laravel/framework/src/Illuminate/Container/Container.php(575): Illuminate\Container\Container->resolve('config') #3 /home/u912734456/public_html/local/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(728): Illuminate\Container\Container->make('config') #4 /home/u912734456/public_html/local/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(106): Illuminate\Foundation\Application->make('config') #5 /home/u912734456/public_html/local/vendor/laravel/framework/src/Illu in /home/u912734456/public_html/local/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 729
I try to clear cache in bootstrap and composer dump-autoload and composer upload

**Comment by browner12** [comment]
please ask in either the Slack channel or on a forum site like StackOverflow
