### ISSUE TITLE
Eloquent: Saving Carbon as date attribute in a different timezone saves wrong value

### ISSUE THREAD

**Issue by DSpeichert** [laravel/framework#19865]
- Laravel Version: 5.4.28
- PHP Version: 7.1.6
- Database Driver & Version: mysqlnd 5.0.12-dev - 20150407 - $Id: b396954eeb2d1d9ed7902b8bae237b287f21ad9e $

### Description:
Eloquent is assuming all datetime/timezone-type fields from MySQL to be in app.timezone timezone (that's the default timezone being set on Carbon object).
However, when saving those same fields back to DB, it doesn't convert them into the app.timezone timezone.

Therefore, when the model is set with a Carbon object in a different timezone than the default one, upon saving the timezone is stripped and the stored value is incorrect

### Steps To Reproduce:
1. Create a model with `$table->datetime('ex_date')`
1. Have `app.timezone` set to `UTC`
1. Set the model's attribute: `$m->ex_date = Carbon::createFromFormat('Y-m-d\TH:i', $request->get('ex_date'), 'Europe/Warsaw')` (this example is for a standard HTML5 datetime-local field format)
1. Save the model, the saved attribute now appears to have exact same value but different timezone (UTC is now set). Therefore, upon converting manually back to `Europe/Warsaw`, a different time is obtained.

### Temporary fix applied:
Override `fromDateTime` on the model: https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L724-L735 adding `->setTimezone(config('app.timezone'))`:

```php
    /**
     * Convert a DateTime to a storable string.
     *
     * @param  \DateTime|int $value
     * @return string
     */
    public function fromDateTime($value)
    {
        return $this->asDateTime($value)->setTimezone(config('app.timezone'))->format(
            $this->getDateFormat()
        );
    }
```

**Comment by themsaid** [comment]
Same as in https://github.com/laravel/framework/issues/19737

Eloquent doesn't do any timezone conversion for you, you have to deal with that yourself, forcing a conversion will cause complains from thousands of others who are already doing their own conversion.

**Comment by DSpeichert** [comment]
I haven't actually seen #19737 but I've seen other issues similar also closed. I think this is actually a bug, because of how data is lost, for the following reasons:

1. Laravel/Eloquent promote the use of Carbon objects which support timezones very prominently, yet there is no warning that it is entirely useless when used with Eloquent.
1. The `config/app.php` has a very vaguely explained `timezone` setting, which used to say something like "It better be UTC" and that it affects created_at timestamps. Having it affect db-saved dates only one way (when reading) doesn't make sense - that's why I think it's a bug.
1. There is a column type in Eloquent `dateTimeTz` which in MySQL doesn't really have anything more than `dateTime` AFAIK, yet adds to the confusion hinting that there might be some solution to the timezone issue.

I think the proper way would be to allow for customization of the timezone in which dates are stored in addition to the default timezone in which Carbon dates are instantiated. Currently there is just `app.timezone` for reading stored timezones and nothing to affect the writing.

Having two config parameters (with the one for storage ideally being UTC all the time) would allow for storage with conversion to UTC and for having Carbon objects by default in a wanted timezone.

**Comment by themsaid** [comment]
The approach I currently use in my apps is:

1. Convert date to UTC
2. Store to the DB in UTC format
3. Restore data from DB
4. Convert it back to whatever time zone needed

This approach gives me the flexibility of being able to store in different timezones as I wish, some fields store the date in a specific tiemzone other than UTC, other fields needs to be converted to UTC.

Also conversion from/to UTC doesn't always depend on app.timezone, it might return on a user preference based on the app logic, that's why I'm a big fan of how this works at the moment, it give s you 100% control over what you want, and in an app I used to work on that uses this a lot I really wouldn't want Eloquent to force the conversion like this under the hood.

**Comment by DSpeichert** [comment]
In your approach, however, you must perform conversion while saving to the `app.timezone` timezone, so that when you restore it back, it's still correct. You are right that it may be needed to dynamically change the timezone for the user and then you want to do that manually.

However, my point is that for the dates restored from DB to be correct, you MUST convert it to UTC (or whatever `app.timezone` is set to) before saving. This is something that can be easily automated by the framework. When you read the date back, it already IS in the `app.timezone` timezone, so the conversion you do later is really yours to do, but interpreting the data in a DB column that doesn't actually store timezone information is currently dependent on `app.timezone`  setting.

**Comment by themsaid** [comment]
> you MUST convert it to UTC 

What if I don't want to store it in UTC? for a specific field I need to store it in a specific timezone.

**Comment by DSpeichert** [comment]
> What if I don't want to store it in UTC? for a specific field I need to store it in a specific timezone.
Then you can manually override the function like I did to undo this default behavior that I believe makes more sense. Of course, if you want to store ALL your dates in a specific timezone, you can change the setting that defines the storage-timezone (currently it's `app.timezone` but like I said before it could be a separate setting).

I am not disputing the fact that being able to manually control the behavior is not necessary. I recognize you have a good use case for it.
What I want is to make the default behavior make more sense and be less surprising by ensuring half of the date is not lost upon save without the developer doing extra work. Principle of least surprise should apply here.

**Comment by themsaid** [comment]
Well a framework being used by millions, it's hard to decide what's a **better** default behaviour :)

I suggest that you propose this change in https://github.com/laravel/internals repo, that's where we keep such stuff and discuss it before being able to decide if it's good or not.

Meanwhile I'm closing this issue since it's not really a bug but rather a request to change the default behaviour.

Looking forward to discussing it further on the internals repo.

Thanks :)

**Comment by miking7** [comment]
The issue raise here is valid.  We've just spent a whole morning trying to figure out why Laravel was exhibiting inconsistent behaviour on data store through our API.  @DSpeichert is correct - Laravel is unnecessarily throwing away timezone information here, and is exhibiting inconsistent behaviour between retrieving and storing information to Eloquent Models.  

Thanks @DSpeichert for your "Temporary Fix" code.  Here's a slightly updated version that's been updated for Laravel 7:

### Temporary Fix - Code for Laravel 7:
```php
    /**
     * Convert a DateTime to a storable string.  (Override Laravel Default - which inconsistently throws away timezone information - see: https://github.com/laravel/framework/issues/19865 )
     *
     * @param  mixed  $value
     * @return string|null
     */
    public function fromDateTime($value)
    {
        return empty($value) ? $value : $this->asDateTime($value)->setTimezone(config('app.timezone'))->format(
            $this->getDateFormat()
        );
    }
```

(Insert this code into your models to fix Eloquent's inconsistent handling of timezones when storing vs retrieving from a model.)
