### ISSUE TITLE
[5.4] Response - Wrong HTTP status code returned

### ISSUE THREAD

**Issue by MarceauKa** [laravel/framework#19869]
- Laravel Version: 5.4.24
- PHP Version: 7.0.15
- Database Driver & Version: MySQL 5.6

### Description:

Hi! I'm building a RESTful API with Laravel 5.4. All's fine with my tests, my API returns the good HTTP response code (200, 422, 404, ...) but when I'm trying to use it in a real case, the HTTP code 200 is always returned.
 
### Steps To Reproduce:

1. My controller
```php
return response()->json([
   'name' => ['The field name is required']]
], 422);
```

2. My test
```php
// Works
$this->postJson(route('api.users.create'))
        ->assertStatus(422)
```

3. My real request
```bash
curl --request POST \
  --url http://my-endpoint.rest \
  --header 'accept: application/json' \
  --header 'content-type: multipart/form-data' \
```

It's cURL but I have the same problem with Axios and [Insomnia](https://insomnia.rest/)
My request always returns 200. And it's the same for all of my controllers.

I've tried with `Response::make()` and `abort()` this is the same thing. Routes are in the "api" group and the `Content-Type` returned is always `text/html`.

**Comment by tghpow** [comment]
+1

**Comment by themsaid** [comment]
I can't replicate your issue, response codes are returned correctly.

**Comment by themsaid** [comment]
```
Route::get('/user', function (Request $request) {
    return response()->json(123, 422);
});
```

Returns a response code 422.

**Comment by MarceauKa** [comment]
Found the error in `routes/api.php`.

<img width="491" alt="capture d ecran 2017-07-03 a 13 45 58" src="https://user-images.githubusercontent.com/1665333/27791585-12398e14-5ff6-11e7-8dc0-5e0cf27ad054.png">

The empty line converts all request to `HTTP 200`.

**Comment by stefanpl** [comment]
Can confirm, empty line before opening `<?php` leads to wrong (always 200) status code and content type

**Comment by salomoni** [comment]
Happened here too. VS Code warns about this only if you happen to have a namespace statement in the file.

Without the namespace you get no warnings.

<img width="582" alt="screen shot 2018-04-13 at 3 31 54 pm" src="https://user-images.githubusercontent.com/10659247/38734890-d542df50-3f2f-11e8-8a84-57271d534d69.png">

**Comment by yourlenar** [comment]
Hi, I have a similar problem, but with routes.php all okay. What else could be the problem?

**Comment by salomoni** [comment]
@yourlenar I think it's not only the routing files, can you check all the other project files too?
