### ISSUE TITLE
Replaced hard coded string in welcome.blade.php file

### ISSUE THREAD

**Issue by BenSaud-CS** [laravel/framework#19872]
- Laravel Version: 5.4.*
- PHP Version: >=5.6.4
- Database Driver & Version:

### Description:

- Replace the laravel text at the file welcome.blade.php 
```html
<title>Laravel</title>
```
### Steps To Reproduce:
- To be like this: 
```html
<title>{{config('app.name')}}</title>
```

**Comment by m1guelpf** [comment]
@BenSaud-CS Taylor has already rejected this many times.

**Comment by BenSaud-CS** [comment]
why??

**Comment by m1guelpf** [comment]
@BenSaud-CS That view is an starting point for your application, and also Taylor doesn't like to change things in the laravel/laravel repo.

**Comment by themsaid** [comment]
sorry no plans for this
