### ISSUE TITLE
Default and comment does NOT work together in migration

### ISSUE THREAD

**Issue by masterwto** [laravel/framework#19878]
- Laravel Version: 5.4.27
- PHP Version: 7.1
- Database Driver & Version: mariadb 10.2

### Steps To Reproduce:
Make a migration:
$table->

**Comment by ankurk91** [comment]
Does laravel supports madiadb officially ?

**Comment by masterwto** [comment]
@ankurk91
mariadb has almost the same api and SQL grammer as mysql.

**Comment by ankurk91** [comment]
@masterwto 

Actually it is woking fine on MySql 5.7, Laravel 5.4.28, php 7.0
```php
// users table migration
$table->string('password')->nullable()->default(null)->comment('null when sign-up via oauth');
```
![screenshot from 2017-07-04 12-01-23](https://user-images.githubusercontent.com/6111524/27817788-852de39c-60b0-11e7-811b-4791bcc8b738.png)

Can you share your migration class code here ?

**Comment by themsaid** [comment]
Please provide more information, share your migration code.

**Comment by masterwto** [comment]
This is the migration:
    4
cleverUtd   2016-02-04 10:29:37 +08:00
我用 markdown 都是 

```
// This line is working fine.
$table->string('password')->nullable()->default(null)->comment('null when sign-up via oauth');

// The problem occurs here...
$table->integer('message')->default(0)->comment('Id of the last 
message that has been read');
``` 

My database is MariaDB 10.2.
Is this problem of MariaDB?

**Comment by ankurk91** [comment]
@masterwto 
You given code works fine on MySql 5.7.18

**Comment by masterwto** [comment]
@ankurk91
Maybe it's a bug of mariadb. I'll report it to mariadb.

**Comment by themsaid** [comment]
closing since it works in MySQL which is the driver supported in Laravel.

**Comment by masterwto** [comment]
Reported to mariadb:
https://jira.mariadb.org/browse/MDEV-13244?page=com.atlassian.jira.plugin.system.issuetabpanels:all-tabpanel
