### ISSUE TITLE
Blade compiles the first }} instead of the last, and produce syntax error

### ISSUE THREAD

**Issue by svolenszki** [laravel/framework#19877]
- Laravel Version: 5.3.31
- PHP Version: 5.6.30
- Database Driver & Version: MariaDB 10.1.21

Description:

Using }} in text context occurs fatal error, because blade uses the first }} occurence to close php tag, not the last.

Use case:

`{{ Form::text('name', '@{{person.name}}') }}` where the input value will be the name attribute of person JS object, after compiled client side (Handlebar).

`{{ 'foo' }}` => compiled to `<?php echo e('foo'); ?>` => output foo
`{{ '@{{foo}}' }}` => compiled to `<?php echo e('foo); ?>' }} `=> fatal error unexpected '}'

Steps To Reproduce:

`{{ 'foo' }}` => output foo
`{{ '@{{foo}}' }}` => fatal error unexpected '}'

**Comment by themsaid** [comment]
yes this is a limitation you have to deal with, unfortunately the current way Blade is written using regex makes it very hard to handle some cases.

**Comment by svolenszki** [comment]
Thank you Mohamed, I did the deal and with this replacement in BladeCompiler.php compileRegularEchos and compileEscapedEchos function works well:

```
//$pattern = sprintf('/(@)?%s\s*(.+?)\s*%s(\r?\n)?/s', $this->contentTags[0], $this->contentTags[1]);
$pattern = sprintf('/(@)?%s(([^%s%s]*|(?R))*)%s/s', $this->contentTags[0], $this->contentTags[0], $this->contentTags[1], $this->contentTags[1]);
```
What do you think for implementing? Write my own service provider and runtime I overwrite this functions, or is there any way to test it and change in the repository?
