### ISSUE TITLE
Current middleware order causes route model binding + subdomain global scoping to fail

### ISSUE THREAD

**Issue by lasseal** [laravel/framework#19885]
- Laravel Version: 5.4.27
- PHP Version: 7.1.6
- Database Driver & Version: MySQL 5.7.18

### Description:

In a multi-tenant application depending on subdomains and global scopes for tenancy, the global tenant scope works with objects and expects subdomain model binding to have taken place. Since `SubstituteBindings` happens after `Authenticate`, any globally scoped queries related to the `auth` middleware would receive a string instead of an object and the scoping fail.

By dumping the output of `Request::Route('tenant')` from the global middleware when visiting a route inside of a route group with the `auth`middleware applied, this is what we get:

![screen shot 2017-07-04 at 09 46 15](https://user-images.githubusercontent.com/1869424/27820148-b44d510c-609d-11e7-8a14-365affda7b19.png)

It would be possible to solve this by rerordering middlewares in the `$middlewarePriority` in the App\Kernel, but would this create any implications for the framework as a whole?

Is there a reason the authentication happens before the binding?

The new order would look like this:

    /**
     * The priority-sorted list of middleware.
     *
     * Forces the listed middleware to always be in the given order.
     *
     * @var array
     */
    protected $middlewarePriority = [
        \Illuminate\Session\Middleware\StartSession::class,
        \Illuminate\View\Middleware\ShareErrorsFromSession::class,
        \Illuminate\Routing\Middleware\SubstituteBindings::class,
        \Illuminate\Auth\Middleware\Authenticate::class,
        \Illuminate\Session\Middleware\AuthenticateSession::class,
        \Illuminate\Auth\Middleware\Authorize::class,
    ];

**Comment by themsaid** [comment]
Sorry but your report seems pretty tied to your application with no clear steps to replicate. Feel free to re-order the `$middlewarePriority` in your app as needed by extending it in your app's HTTP Kernel class.

**Comment by lasseal** [comment]
Ok. Works for me. Would there be any implications of reordering the middlewares in a fresh Laravel install which you would know of @themsaid ?

**Comment by themsaid** [comment]
Well the order is preserved like this for multiple reasons, so if you want to change the order you better know what you're doing :)

**Comment by lasseal** [comment]
In this case I really don't understand the underlaying reason, but would love to learn. Would you be able to explain the reasoning behind this or point me to a resource where I can learn about the reasons for this order? 

L
