### ISSUE TITLE
Eloquent pagination method ignoring columns for the query count

### ISSUE THREAD

**Issue by zeraphie** [laravel/framework#19882]
- Laravel Version: 5.2.45
- PHP Version: 5.5.9
- Database Driver & Version: MySQL v5.5.55

### Description:
I'm using the model paginate method, and it doesn't pass in the `$columns` parameter into the `$query->getCountForPagination()` line, where I reckon that it should, seeing that I want to pass a single value as the $columns (an id) and it's just ignored :) (Sorry for my poor explanation, I'll paste the code below, might be easier to understand!)

*Note: `This is in \Illuminate\Database\Eloquent\Builder`*

```php
/**
 * Paginate the given query.
 *
 * @param  int  $perPage
 * @param  array  $columns
 * @param  string  $pageName
 * @param  int|null  $page
 * @return \Illuminate\Contracts\Pagination\LengthAwarePaginator
 *
 * @throws \InvalidArgumentException
 */
public function paginate($perPage = null, $columns = ['*'], $pageName = 'page', $page = null)
{
    $page = $page ?: Paginator::resolveCurrentPage($pageName);

    $perPage = $perPage ?: $this->model->getPerPage();

    $query = $this->toBase();

    // This line should be $total = $query->getCountForPagination($columns);
    $total = $query->getCountForPagination();

    $results = $total ? $this->forPage($page, $perPage)->get($columns) : new Collection;

    return new LengthAwarePaginator($results, $total, $perPage, $page, [
        'path' => Paginator::resolveCurrentPath(),
        'pageName' => $pageName,
    ]);
}
```

### Steps To Reproduce:
```php
DB::enableQueryLog();
$query = \App\Models\Jobs::paginate(15, ['jobs.id']);

dd(DB::getQueryLog());
```

Result:
```html
array:2 [▼
  0 => array:3 [▼
    "query" => "select count(*) as aggregate from `jobs` where `jobs`.`deleted_at` is null"
    "bindings" => []
    "time" => 0.16
  ]
  1 => array:3 [▼
    "query" => "select `jobs`.`id` from `jobs` where `jobs`.`deleted_at` is null limit 15 offset 0"
    "bindings" => []
    "time" => 0.25
  ]
]
```

### Suggested Fix
Add the $columns variable into the `getCountForPagination` function for the model pagination, and/or make it a string instead of an array

### Current Workaround
My current workaround is almost a copy paste of the actual paginate method inside my own paginate method, with the $columns variable added in, but this seems like so much overkill!

**Comment by themsaid** [comment]
5.2 is not supported anymore, please upgrade to the latest release.
