### ISSUE TITLE
Add pagination methods to Collection class

### ISSUE THREAD

**Issue by freekmurze** [laravel/framework#19889]
Recently [these two pagination macros](https://github.com/spatie/laravel-collection-macros/blob/7467d75/src/macros.php#L314-L346) were PR'ed to our [laravel-collection-macro](https://github.com/spatie/laravel-collection-macros) package.

I feel like they're generic and useful enough to warrant a place in `Illuminate\Support\Collection`. Do you agree? If so, I'll whip up a PR.

**Comment by Dylan-DPC** [comment]
hey

kindly open this is laravel/internals repo :)
