### ISSUE TITLE
$loop variables to @each directive

### ISSUE THREAD

**Issue by atayahmet** [laravel/framework#19891]
- Laravel Version: 5.4.26
- PHP Version: 7.1.5

Are not loop variables sent to `@each` directive in Blade?

**Example:** 

```php
@each('partials.job', $jobs, 'job')
```
**job.blade.php**
```php
$loop->index
```

**Comment by themsaid** [comment]
No this is not supported at the moment. 
For suggestions and feature requests please use the https://github.com/laravel/internals repo.

**Comment by FatBoyXPC** [comment]
This feels like a bug to me as well. I would expect `@each` to be syntactic sugar for `@forelse`, but that's clearly not the case here.

**Comment by Garbee** [comment]
The [docs](https://laravel.com/docs/5.6/blade#rendering-views-for-collections) also say here:

> You may combine loops and includes into one line with Blade's `@each` directive

Ergo, it should have the loop variable.

**Comment by ERROPiX** [comment]
+1 for this
