### ISSUE TITLE
DatabaseTransactions conflicts with PHPUnit @depends

### ISSUE THREAD

**Issue by ArondeParon** [laravel/framework#19892]
- Laravel Version: 5.4.23
- PHP Version: 7.1
- Database Driver & Version: MariaDB 10.0.29

### Description:

I'm not entirely sure whether this is a bug or simply something I have to deal with, but I recently discovered that combining PHPUnit test dependencies with the `DatabaseTransactions` trait can cause unexpected behavior. 

Using the `@depends` annotation, it is possible to pass data from one test to another. This is also the case for `Eloquent` models. It seems, however, that after passing the data to the dependent test, the database connection is lost and the rollback has already happened.

In this scenario, one would still be able to access the full `Eloquent` model, but not not it's relations (unless eager-loaded in the parent).

A solution, for now is to eager-load the relations before returning the data. A side-effect of this solution is that it is only possible to perform a `count()` test on the collection, and not on the relation itself. IE, an `$invoice->notifications()->count()` would return 0, while a `$invoice->notifications->count()` would return 1.

### Steps To Reproduce:

```php
public function test_this_is_my_parent_test()
{
    $invoice = $this->createInvoice();
    // underneath, this would create an `InvoiceNotification` model, attached via a `HasMany`
    $invoice->send();

    // will show the model
    dump($invoice->fresh());
    // will show 1
    dump($invoice->notifications()->count());
    // pass the model to the child tests
    return $invoice->fresh();
}

/** @depends test_this_is_my_parent_test */
public function test_some_dependent_test(Invoice $invoice)
{
    // Will show the Eloquent model
    dump($invoice);
    // Will show null
    dump($invoice->fresh();
    // Will show 0
    dump($invoice->notifications()->count());
}
```

**Comment by themsaid** [comment]
Yes that makes sense, the DB transaction trait doesn't support dependent tests, each test is run inside a separate transaction that's rolled back after the test is done.

**Comment by deleugpn** [comment]
Makes sense to not use the trait in test classes that will have dependency of each other.

**Comment by spmsupun-certscanner** [comment]
any workarounds?
