### ISSUE TITLE
$message variable not available in extended view when using Mailables

### ISSUE THREAD

**Issue by ArondeParon** [laravel/framework#19908]
- Laravel Version: 5.4.23
- PHP Version: 7.1
- Database Driver & Version: MariaDB 10

### Description:

I recently tried to use the `$message->embed()` ([ref](https://laravel.com/docs/5.4/mail#inline-attachments)) functionality and stumbled upon this problem. It seems that the `$message` variable is only available in the directly referenced view, but not in any extended views.

### Steps To Reproduce:

Mailable:

```php
public function build()
{
    return $this->view('some.view');
}
```

view.blade.php:

```php
@extends('layouts.email')
@section('content')
    {{ $message->embed('derp.jpg') }} 
    {{-- works fine :) --}}
@endsection
```

email.blade.php:

```
{{ $message->embed('foo.gif') }}
```

The last would result in an "undefined variable" notice.

**Comment by decadence** [comment]
https://github.com/laravel/framework/issues/19046
https://github.com/laravel/docs/pull/3378

**Comment by themsaid** [comment]
It's a normal blade rendering so the variable exists in the extended view, I can't replicate your issue using your code, you'll need to debug more in your app to try to find what changes you made that caused this behaviour.
