### ISSUE TITLE
Validation Rule issue

### ISSUE THREAD

**Issue by alex-dan18** [laravel/framework#19919]
- Laravel Version: 5.4
- PHP Version: 5.6.30
- Database Driver & Version: Mysql 5.7.18

### Description:
When I try to validate something with the rule Rule class in an API (I am using AJAX to make the request, and I set JSON as dataType) and I get the error.

I have an array like this: 

$rules = [
    'something' => [Rule::unique('sometable')]
];

Validator::make($data, $rules, $messages)
        ->validate(); 

And I get the next error

![screenshot from 2017-07-05 12-15-41](https://user-images.githubusercontent.com/16368594/27876198-d240cae8-617b-11e7-9d8d-36f945ff7541.png)

This does't happen if I make the rule like this:

$rules = [
    'something' => ['unique:sometable']
];

It seems that it works in a normal request, but not in an AJAX request because I used it in a normal form i it works, but I'm trying to validate something with AJAX and it doesn't, 

### Steps To Reproduce:

**Comment by themsaid** [comment]
I can't replicate your issue using:

    Validator::make([
        'something' => 1
    ], [
        'something' => [Rule::unique('sometable')]
    ])
        ->validate();

**Comment by alex-dan18** [comment]
Ok, the problem is that I get the ErrorException in the screenshot above when I use the Rule class instead of a string in the rules array of the Validator::make method. For example, 'unique:users,email' (this works), but Rule::unique('users,email') doesn't work. 

Here is the documentation example:
![screenshot from 2017-07-06 09-17-56](https://user-images.githubusercontent.com/16368594/27915491-2b733348-622c-11e7-88cb-8d2ab36ea95d.png)

As I said, this doesn't work when I make an AJAX call with dataType JSON.

Sorry about my english.

**Comment by themsaid** [comment]
The validator doesn't differentiate between an AJAX request or a normal one, I can't replicate your issue even using an AJAX request, please try the exact following code:

```
Validator::make([
    'something' => 1
], [
    'something' => [Rule::unique('sometable')]
])
    ->validate();
```

**Comment by passionInfinite** [comment]
@alex-dan18  You are writing in wrong way. the unique function of Rule class takes two parameters first one is the name of the table and the second one is the name of the column that you want to check against.

` Rule::unique('tablename', 'column_name'); ` not like this ` Rule::unique('tablename,column_name'); `

Then you will get rid of the undefined offset exception.

Also, @themsaid is also correct you can use it that way also.

**Comment by alex-dan18** [comment]
Rule::unique('tablename', 'column_name'); worked perfectly. well I will look for
a solution before post an issue. Thank you very much.
