### ISSUE TITLE
Validation with an array of files

### ISSUE THREAD

**Issue by sausin** [laravel/framework#19918]
- Laravel Version: 5.4.28
- PHP Version: 7.1
- Database Driver & Version: mysql

### Description:
Usage of an `array` type input with `required` and `file` rule specified without a `*` doesn't seem to work correctly.

### Steps To Reproduce:
1. Create a form request or validation with a controller to accept files using the following rule for validation:
```
'files' => 'bail|required|file'
```
2. Make a post request to the controller _without_ the `files` field and the result should be a validation error with a message something like `files is required`, confirming that the `required` rule works
3. Post an array of files _with_ the `files` field and this time it should again result in a validation error with a message like `files should be a file`
4. Modify the rule to be like:
```
'files.*' => 'bail|required|file'
```
and make the same post request as step 3 and this time it should go through just fine
5. Make a request like step 2 and it will still go through.

Alternatively, 
In the tests of the framework under the `ValidationValidatorTest` class is the method to validate `required` rule.

Near the last assertion of the method, if the following modification is performed:
```
$v = new Validator($trans, [], ['files.*' => 'Required']);
$this->assertTrue($v->passes());
```
The assert does not fail, which basically suggests the same behavior as described in steps 1 through 5.

### Expected Behavior

The expected behavior here would've been that the `required` validation error should've been thrown with the `files.*` but it wasn't.

In case this is expected behavior, suggestions on doing validation of input files which are tied to one array field using `file` rule are appreciated :+1:

**Comment by themsaid** [comment]
5.2 is not supported anymore, please upgrade your application, lots of stuff has been fixed since 5.2 :)

**Comment by sausin** [comment]
Brain says type 5.4.28 and fingers go, meh.. 

@themsaid The reported issue is for 5.4.28. Could you please open it again?

**Comment by sausin** [comment]
updated the description

**Comment by themsaid** [comment]
An you please post the final state that we should check? I don't seem to understand the issue.

**Comment by sausin** [comment]
Thanks for reopening it!

Summary of the issue:
- If `'documents.*' => 'bail|required|file'` kind of validation is used, and an array of files field `documents`  is submitted, validation works correctly for the `file` rule but the `required` rule is ignored (so if there is no `documents` field in the input, validation still passes)
- If `'documents' => 'bail|required|file'` kind of validation is used, and an array of files field `documents`  is submitted, validation for the `file` rule doesn't pass but the `required` rule works. The `file` rule does not seem to understand that it should check an array of files (if there is no `documents` field in the input, validation does not pass, as expected)

I believe the `required` rule should work in the first scenario. 

A workaround to get the intended functionality is to go with the second method and have a `$request->document->isValid()` inside a foreach for `$request->documents` instead of the `file` validation rule.

However, the first method working correctly with `required` rule is ideal and the current implementation feels like a bug.

The `ValidationValidatorTest` modification explained above in the original report might a better explanation in itself.

In case my explanation is woefully lacking, I can try to make a gif explaining the issue.

**Comment by themsaid** [comment]
You need both rules:

```
'documents' => 'bail|required',
'documents.*' => 'bail|required|file',
```

**Comment by sausin** [comment]
@themsaid Thanks for your feedback! I will go with this for now.

Is there a reason why it needs to work like this or is it possible for the `required` rule to work together with the `file` with some modifications ?

If this is open for implementation I can give it an attempt (if I can!) and try to submit a PR
