### ISSUE TITLE
[5.4]  Redirect url after login got wrong.

### ISSUE THREAD

**Issue by ThunderBirdsX3** [laravel/framework#19910]
- Laravel Version: 5.4.28
- PHP Version: 7.1.5
- Database Driver & Version: MySQL 5.7.18

### Description:
I found this problem in production server.

This problem about redirect after login (Success).

I use middle ware to force Schema and URL.

```
<?php namespace App\Http\Middleware;

use Closure;

use Illuminate\Http\Request;

class ForceHttps
{
  /**
  * Handle an incoming request.
  *
  * @param  \Illuminate\Http\Request $request
  * @param  \Closure $next
  * @return mixed
  */
  public function handle($request, Closure $next)
  {
    if (app()->environment('production'))
    {
      // /** @var \Illuminate\Routing\UrlGenerator $url */
      $url = app()->url;
      // Force the application URL
      $url->forceRootUrl(config('app.url'));
      $url->forceScheme('https');
    }

    return $next($request);
  }
}
```

After post to route login, Application will redirect to `protected $redirectTo = '/home';` right.

In `Response Headers` you will got `Location : "{{ Redirect to URL }}"`;

EX. If your website URL is "https://someapp.yourdomain.com".

When you login they should return location "https://someapp.yourdomain.com/home" after you login success.

But application return location "http://someapp.yourdomain.com/home", Not a SSL.

In case your application access with a port "https://someapp.yourdomain.com:1234"

After you login they also return location "http://someapp.yourdomain.com/home";

I found this problem only login function other form in application return location in right URL.

**Comment by themsaid** [comment]
can't replicate your issue.

**Comment by ThunderBirdsX3** [comment]
@themsaid Could you explain, What is "replicate" and "Steps To Reproduce"  in this case. I didn't understand.

**Comment by srmklive** [comment]
@ThunderBirdsX3 I myself can't replicate the issue you have mentioned. I have tried all scenarios you mentioned, couldn't replicate all. 

To force HTTPS i would suggest you do something like this:

```
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\RedirectResponse;

class ForceHttps
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        if(app()->environment('production') && ! $request->secure()) {
            return redirect()->secure($request->path());
        }

        return $next($request);
    }
}
```

**Comment by ThunderBirdsX3** [comment]
@srmklive I think is not what a right answer.

Hmmmm, OK. @themsaid  May be this trouble about function `sendLoginResponse` in `Illuminate\Foundation\Auth\AuthenticatesUsers`.

```
/**
   * Send the response after the user was authenticated.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  protected function sendLoginResponse(Request $request)
  {
      $request->session()->regenerate();

      $this->clearLoginAttempts($request);

      return $this->authenticated($request, $this->guard()->user())
              ?: redirect()->intended($this->redirectPath());
  }
```

I try to copy this code to `App\Http\Controllers\Auth;`, Then change 
``` 
protected $redirectTo = '/home';
...
?: redirect()->intended($this->redirectPath());
```
 to 
```
protected $redirectTo = 'home';
...
 ?: redirect()->route($this->redirectPath());
```
And i got a right response.

This screenshot from my PROD server. And this is response before i change function `sendLoginResponse`.
![screen shot 2017-07-06 at 3 40 04 pm](https://user-images.githubusercontent.com/6513358/27903684-5b7ef9d6-6264-11e7-8f45-c18bd85374c6.png)

This is my server redirect URL again to get right URL.
![screen shot 2017-07-06 at 3 45 45 pm](https://user-images.githubusercontent.com/6513358/27903775-ba73a766-6264-11e7-84dc-ea803191c19c.png)

This screenshot  after I change  function `sendLoginResponse`.
![screen shot 2017-07-06 at 3 49 16 pm](https://user-images.githubusercontent.com/6513358/27903812-d9f6e1de-6264-11e7-8379-8d36af9f7ad5.png)

**Comment by themsaid** [comment]
The original code works for me, it redirects to an https version of the home screen with no issues, could be something in your server.

**Comment by themsaid** [comment]
closing for being unable to replicate. please use the forums to get better assistance with your issue.
