### ISSUE TITLE
Creating related models in model factories

### ISSUE THREAD

**Issue by joshforbes** [laravel/framework#19916]
- Laravel Version: 5.4.20
- PHP Version: 7.0.18
- Database Driver & Version: MySQL 5.7

### Description:
When defining relationships in model factories using either the lazy method or closures you can end up with extra models created if you try to use the factory in the save() method off of a relationship

### Steps To Reproduce:
Create a model factory:
```
$factory->define(Profile::class, function (Faker\Generator $faker) {
    return [
        'user_id' => factory(User::class)->lazy()
    ];
});
```
Use the model factory in the save method:
```
$user->profile()->save(factory(Profile::class)->make());
```
The profile will be saved with the correct user_id but you will end up with an additional user saved to the database that does not have a profile.

**Comment by Dylan-DPC** [comment]
Possible duplicate: https://github.com/laravel/framework/issues/19230

**Comment by devcircus** [comment]
Pretty sure that's the intended behavior.

**Comment by themsaid** [comment]
Yes cause you simply said for every profile created, create a new user. and that's what you get :)

**Comment by joshforbes** [comment]
@themsaid but that's not true.  What I actually said was that for every profile created where I am not providing the user_id to create a new user. But in this instance I AM providing a user_id by way of the save method. 

This just feels un-laravel like:
``` 
$user->profile()->save(factory(Profile::class)->make(['user_id' => $user->id]));
```

**Comment by devcircus** [comment]
The profile factory is an independent factory with no knowledge of an existing user entity unless you specifically pass an existing id value. 
Wanting the factory to be aware of an existing user without passing that information to the factory, is a strange expectation IMO.

**Comment by joshforbes** [comment]
I don't agree that this is a strange expectation at all. The default behavior of the factory, when the relationship is not defined as a another factory, works this way.  Consider this, if I instead define the profile factory as follows:

```
$factory->define(Profile::class, function (Faker\Generator $faker) {
    return [
        'user_id' => rand(1, 10)
    ];
});
```

And call it as:

```
factory(Profile::class)->create();
```

This will do what you expect and create a profile with a random user id. 

But if I call it as:

``` 
$user->profile()->save(factory(Profile::class)->make());
```

It will instead not use the random number but instead assign the user_id as the id of the $user.

If you were to say this is not technically possible to implement because save is called after the factory has already created the association, I would understand that. But I disagree completely that the way it works now is ideal or intuitive.

**Comment by themsaid** [comment]
well, feel free to open a PR with a proposed solution. Better to discuss implementation at this point :)
