### ISSUE TITLE
Using relational to create a model, and then does not feedback to relations

### ISSUE THREAD

**Issue by liubusian** [laravel/framework#19926]
- Laravel Version: 5.4.27
- PHP Version: 5.6.25
- Database Driver & Version: Mysql 5.7

### Description:
Create a model using relational expressions, and then read the relational model to get a null value

### Steps To Reproduce:
```
$Person = Person::first();
$Person->Car()->create($CarInfo);
dd($Person->Car);
```
I got a null
------------------------------------------------------
I try it

```
$Person = Person::first();
$Car = $Person->Car()->create($CarInfo);
dd($Person, $Person->Car, $Car);
```
$Person ->relations -> Car is null 
$Car has created
-----------------------------------------------------
Now, I can only write this 
```
$Person = Person::first();
$Car = $Person->Car()->create($CarInfo);
$Person->setRelation('Car', $Car);
dd($Person->Car);
```
So...Whether it is missing?

**Comment by srmklive** [comment]
First of all, this repo is for bug reporting only. As for your issue, try this:

`Person->fresh()->car`

**Comment by liubusian** [comment]
I tried before
`Person->refresh()->car`
but no effect, still get the null

You are right !

Solved, Thanks
