### ISSUE TITLE
[FEATURE] Validate max length (also integers and similar)

### ISSUE THREAD

**Issue by LasseRafn** [laravel/framework#19927]
### Description:

I'd argue that validating that a integer is 10 (example) characters of length, should be core functionality. Sure, it can be done by looking at e.g. digits, and having it be between 0 and 9999999999.. but that seems excessive.

So, I propose `maxlength` validation. Something like this:

```php
protected function validateMaxLength($attribute, $value, $parameters)
{
    $this->requireParameterCount(1, $parameters, 'maxlength');
        
    return mb_strlen($value) <= (int) $parameters[0];
}
```

### Usage

```php
'number' => 'integer|maxlength:10',
'name' => 'string|maxlength:10' // Yes, you should use max here, but its just to show that it can be used here as well
```

It's mostly useful for integers/digits, as specifying "integer" in the rules, will make `max` validate the value, not the length.

I've also written a short article about it, showing how it works using custom rules: https://lasserafn.com/validating-max-length-laravel-strings-integers-digits/

I think this could improve the experience of validation, especially for newcomers. I remember being confused with `max` and `integers`. Providing a `maxlength` makes it quite straightforward and easy to understand and remember (as its the same parameter used for HTML inputs)

I'd submit a PR; but first let me know if this could potentially be merged.

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
