### ISSUE TITLE
Calling twice times in TransformsRequest middleware.

### ISSUE THREAD

**Issue by ptsilva** [laravel/framework#19920]
- Laravel Version: 5.4.24
- PHP Version: 7.0.18
- Database Driver & Version: N/A

### Description:
 I create a custom request transform GET parameters... But, the transformation has called twice times for each parameter, then i check the ```\Illuminate\Foundation\Http\Middleware\TransformsRequest@clean``` method... this apply the transformation in ``` $request->query ``` and ``` $request->request```, calling twice times.

Other detail about this issue.. The ``` \Illuminate\Http\Request::$request ``` is used only to POST parameters in symfony. But laravel set `` \Illuminate\Http\Request::$request `` using GET parameters. This is a expected behavior ?

```\Illuminate\Http\Request ``` line 351
```php
$request->request = $request->getInputSource();
```

in ```\Illuminate\Http\Request::getInputSource()```

```php
protected function getInputSource()
{
    if ($this->isJson()) {
        return $this->json();
    }

    return $this->getRealMethod() == 'GET' ? $this->query : $this->request;
}
```
### Steps To Reproduce:
Add any GET parameter and add dump in Illuminate\Foundation\Http\Middleware\TrimStrings::transform. This probably will print the parameter added twice times. Because ```$request->query``` and ```$request->request``` are duplicated

**Comment by sisve** [comment]
What is the actual _problem_?

**Comment by ptsilva** [comment]
The ```\Illuminate\Foundation\Http\Middleware\TransformsRequest``` apply the transformation twice times

**Comment by ptsilva** [comment]
```TransformsRequest@clean``` apply the transformation in ```$request->query``` and ```$request->request```, but in ```Illuminate\Http\Request@createFromBase``` laravel duplicate ```$request``` property using the ```$query``` property then GET

```\Illuminate\Foundation\Http\Middleware\TransformsRequest@clean```

```php
/**
     * Clean the request's data.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return void
     */
    protected function clean($request)
    {
        $this->cleanParameterBag($request->query);

        if ($request->isJson()) {
            $this->cleanParameterBag($request->json());
        } else {
            $this->cleanParameterBag($request->request);
        }
    }
```

**Comment by srmklive** [comment]
Can you provide a working example for it?

**Comment by sisve** [comment]
Okay, so the actual problem is `$request->request = $request->getInputSource();` in Request::createFromBase.

https://github.com/laravel/framework/blob/231119b846aa975988d39707b5d404d36be710f2/src/Illuminate/Http/Request.php#L351

**Comment by ptsilva** [comment]
Register this in your kernel... and
make a GET request to

```/?parameter=abc```

```php
<?php

namespace App\Http\Middleware;

use Illuminate\Foundation\Http\Middleware\TransformsRequest;
use Closure;

class Test extends TransformsRequest
{
    protected function transform($key, $value) {

        // In second execution, this will be "bc"
        if($value === 'bc') {
            // Why this is executed ?
            dd('Input already transformed. This should not be executed');
        }

        // input abc, result ab
        $transformedValue = str_replace('a', '', $value);

        return $transformedValue;
    }
}

```
@srmklive, did you understand the problem?

**Comment by ptsilva** [comment]
@themsaid
Removing https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php#L41,

this issue will be solved..
what you think about it ?

**Comment by ptsilva** [comment]
Complementing... make sense that ```\Illuminate\Foundation\Http\Middleware\TransformsRequest@clean``` do transformation only in ```$request->request```, because ```\Illuminate\Http\Request::getInputSource()``` Already checks  if source is json, or get, or post.

**Comment by sisve** [comment]
A fully valid scenario is to clean both query- and postdata. So you need to call cleanParameterBag twice, once with each parameter bag. The problem is that the request bag is replaced with the query bag for get requests, causing the double invocation to cleanParameterBag to clean same bag twice.

**Comment by ptsilva** [comment]
But the replacement in request bag using query bag, is a expected behavior ?
