### ISSUE TITLE
Issue in default @yield laravel 5.4.28

### ISSUE THREAD

**Issue by kossa** [laravel/framework#19930]
- Laravel Version: 5.4.28
- PHP Version: 7.0
- Database Driver & Version: MySQL 

### Description:
I updated laravel to 5.4.28 from 5.4.27, I get a strange thing in my web page, in the head of my page I'm using : 
```
@yield('meta', 'some default meta tags like title, description ...etc')
```
### Steps To Reproduce:
* install new fresh app
* Goto welcome.blade.php
* Replace `<title>Laravel</title>` by `@yield('meta', '<title>Laravel</title>')`
* Go to your page and you'll see : https://screencast.com/t/LBrrT08K

I changed to version of laravel to 5.4.27 and it works fine

Is it a bug, or a change to laravel ?

**Comment by devcircus** [comment]
See #19643

**Comment by kossa** [comment]
Thank you @devcircus
