### ISSUE TITLE
Eager load relations that have a mirrored 'with' property causes php crash

### ISSUE THREAD

**Issue by pet1330** [laravel/framework#19936]
- Laravel Version: 5.3.24
- PHP Version: 7.1.6
- Database Driver & Version: MySQL 5.6.33

### Description:

If you have a model that uses the `with` property to eager load a relation by default which in turn contains a `with` property for the requesting model then php crashes. I can only assume it recursive loads each model until it crashes. Unfortunately, there is no log in laravel as php seems to crash.

### Steps To Reproduce:

Create two models that have a `with` property for each other. One being a belongsTo and the other has a hasMany relationship. For example:
```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Group extends Model
{
    protected $fillable = [ 'name' ];
    protected $table = 'groups';
    protected $with = ['users'];

    public function users()
    {
        return $this->hasMany(User::class, 'group_id', 'id');
    }
}

```

```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class User extends Model
{
    protected $fillable = [ 'name', 'group_id' ];
    protected $table = 'users';
    protected $with = ['group'];

    public function group()
    {
        return $this->belongsTo(Group::class);
    }
}

```

I'm not sure if this is a bug, as I think it is expected behaviour, but it might be worth having a check somewhere to see if a model has already been eager loaded.

**Comment by haakym** [comment]
I've written up your code into a blank laravel app and wrote a test creating the models in question:

```
public function testEagerLoadWithUserAndGroup()
{
  $groups = factory(App\Group::class, 3)
    ->create()
    ->each(function ($g) {
        $g->users()->save(factory(App\User::class)->make());
    });

  $this->assertNotNull(App\User::first());
}
```

 When running the test I got the following in my console:

```
[Symfony\Component\Debug\Exception\FatalErrorException]
Allowed memory size of 536870912 bytes exhausted (tried to allocate 4096 bytes)
```

the following also showed up in my `laravel.log` file:

```
[2017-07-07 09:13:24] testing.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: 
Allowed memory size of 536870912 bytes exhausted (tried to allocate 4096 bytes) 
in C:\laragon\www\laravel-with-crash\vendor\laravel\framework\src\Illuminate\Support\Str.php:71
Stack trace:
#0 {main}  
```

Side point to anyone copy pasting the code from the **Steps To Reproduce**, small change required in the `User` class' `group()` method, `Groups::class` passed to the `belongsTo()` method should be changed to `Group`.

**Comment by RikSomers** [comment]
This is pretty much expected behaviour becuase, indeed, the relations get loaded recursively and PHP runs out of memory soon after.

Might be nice to have some sort of check to see if you aren't loading relationship recursively.

**Comment by pet1330** [comment]
@haakym Thanks for writing the test. I have also corrected the typo. 

I have tried this on a different machine, but I am still unable to get any log from Laravel as PHP still  crashes.

@RikSomers I agree. I cannot think of a reason that recursive eager loading would be useful, so a check would make sense. Unfortunately I don't know the internals of the framework very well as I just use it like a black box, could someone point me in the right direction to try to implement this fix?

**Comment by haakym** [comment]
@RikSomers 

Thanks. All eloquent models in your app extend `Illuminate/Database/Eloquent/Model`, so I'm guessing you would want to start there. The `with()` method which I'm guessing is of importance can be found here: https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Model.php#L353

I have been digging around Eloquent myself to see where the check could be added, but probably need to start using a step-through debugger like xdebug to understand what's going on a bit better. I'm currently using tinker to stop at a given point, but unsure how to get it to continue once it stops. You might find it useful to set up a test and add `eval(\Psy\sh());` in the framework's code to inspect what's going on, more info here if you're interested https://tighten.co/blog/supercharge-your-laravel-tinker-workflow

If you're a Laracasts subscriber there are some good videos on Eloquent here: https://laracasts.com/series/advanced-eloquent

Found this also in Google in a somewhat related discussion: https://laracasts.com/discuss/channels/eloquent/eager-loading-both-forward-and-inverse-relationship
