### ISSUE TITLE
routeMiddleware not working for request method OPTIONS

### ISSUE THREAD

**Issue by sergiobelya** [laravel/framework#19938]
- Laravel Version: 5.4.21
- PHP Version: 7.0

### Description:
App\Http\Kernel::$routeMiddleware not working in Laravel 5.4 (may be in 5.3) for request method OPTIONS.
Because https://github.com/laravel/framework/blob/v5.4.21/src/Illuminate/Routing/RouteCollection.php#L232
But I'm not have elegant solution for this problem.

### Steps To Reproduce:
1. Add my middleware (for example OptionsCorsMiddleware) to App\Http\Kernel::$routeMiddleware array.
2. Send OPTIONS request - middleware not handle.
3. Add my middleware to App\Http\Kernel::$middleware array.
4. Send OPTIONS request - middleware was handle, but I don't want run my middleware (or middleware from https://github.com/barryvdh/laravel-cors) for all requests.

**Comment by themsaid** [comment]
The thing is the `OPTIONS` request won't match any of your routes so the router will error before running any of your route middleware, that's why it **has to be** a global middleware.

**Comment by sergiobelya** [comment]
@themsaid Thanks. I will know that it impossible and that register global middleware for OPTIONS method is good solution.
I hope this information will be useful to somebody.
