### ISSUE TITLE
[Feature Request] Pluck value with array;

### ISSUE THREAD

**Issue by ThunderBirdsX3** [laravel/framework#19942]
In usually, When you `Model::pluck('value', 'id');` you will get result like this right.
```
[
  1 => 'value1',
  2 => 'value2',
  3 => 'value3',
]
```

But if you can pluck value with array. I think it will useful `Model::pluck(['value1', 'value2', 'value3'], 'id');`. You can get result like this.
```
[
  1 => ['value1' => 'test1', 'value2' => 'test2', 'value3' => 'test3'],
  2 => ['value1' => 'test4', 'value2' => 'test5', 'value3' => 'test6'],
  3 => ['value1' => 'test7', 'value2' => 'test8', 'value3' => 'test9'],
]
```

**Comment by Dylan-DPC** [comment]
This is not a bug. Open an issue in the laravel/internals repo
