### ISSUE TITLE
Laravel query builder left join alias issue, alias will be wrap with tablePrefix

### ISSUE THREAD

**Issue by fbens** [laravel/framework#19941]
- Laravel Version: 5.4.23
- PHP Version: 7.1.4
- Database Driver & Version: 5.7.16

### Description:
When I used laravel query builder with `leftJoin`, the table alias will be prefixed with $tablePrefix automatically, It is so inconvenient bcs I need to write more code, especially I must specify the tablePrefix  `DB::getTablePrefix()` like below.

```
$d1s = DB::table('area as a')
	->select('a.*', DB::raw(' count(' . DB::getTablePrefix() . 'b.d1) as num '))
	->leftJoin('article as b', 'a.id', '=', 'b.d1')
	->where(['a.level' => 1])
	->groupBy('a.id')
	->orderBy('a.level', 'ASC')
	->orderBy('a.sortid', 'ASC')
	->get();
```

Why dont Laravel allow like this?
```
$d1s = DB::table('area as a')
	->select('a.*', DB::raw(' count(b.d1) as num '))
	->leftJoin('article as b', 'a.id', '=', 'b.d1')
	->where(['a.level' => 1])
	->groupBy('a.id')
	->orderBy('a.level', 'ASC')
	->orderBy('a.sortid', 'ASC')
	->get();
```

**Comment by themsaid** [comment]
Because you're building the query yourself, Laravel can't decide how to append the table prefix in such query on its own.
