### ISSUE TITLE
Session dot notation and Response setExpires()

### ISSUE THREAD

**Issue by jay-shah-rushiinfotech** [laravel/framework#19954]
- Laravel Version: 5.3.30
- PHP Version: 7.0
- Database Driver & Version:

### Description:
-------------------------------------------------------------------------------------------------------
Session with dot notation
session()->exists($key,$value);
session()->has($key,$value);
IT PRODUCE WRONG VALUE WHEN DOT NOTATION ARRAY USED
-------------------------------------------------------------------------------------------------------
Response setExpires() TimeZone can be from config timezone rather GLOBAL UTC timezone

### Steps To Reproduce:

session()->exists('main.one',$value);
session()->has('main.one',$value);

$response->setExpires($time)

**Comment by themsaid** [comment]
5.3 is not supported anymore, please upgrade.
