### ISSUE TITLE
Unable to read key/secret from AWS S3 instance profiles

### ISSUE THREAD

**Issue by eteubert** [laravel/framework#19953]
- Laravel Version: v5.4.19
- PHP Version: 7.1

### Description:

My S3 config looks like this:

```
        's3' => [
            'driver' => 's3',
            // 'key'    => null, // provided by instance profile
            // 'secret' => null, // provided by instance profile
            'region' => env('S3_REGION'),
            'bucket' => env('S3_BUCKET'),
        ],
```

I verified that region and bucket are correct. `"league/flysystem-aws-s3-v3": "^1.0"` is installed. However, I get this error when trying to access S3 (upload a file):

```
ErrorException in FilesystemManager.php line 207:
Undefined index: key
```

Reading https://github.com/laravel/framework/pull/9558 I thought Laravel can get key/secret from the instance profile. Am I doing it wrong or is there a bug?

**Comment by themsaid** [comment]
You can't comment the config keys, they must exist, you can use environment variable to set those keys though.
