### ISSUE TITLE
MorphMany relationship with Laravel 5.4.27 generates Error with mysql

### ISSUE THREAD

**Issue by jackengine** [laravel/framework#19963]
- Laravel Version: 5.4.27
- PHP Version: 5.6.25
- Database Driver & Version: mysql 5.7.14

### **Description: Simplest morphTo - morphMany throws error :** 

**SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'commentable_id' cannot be null**

Note that it works well with Laravel 5.4.13

**Comment Model**
```
class Comment extends Model
{
protected $fillable = [
    'body',
    'user_id',
    'commentable_id',
    'commentable_type'
 ];

  public function commentable(){
      $this->morphTo();
    }
}
```

**Post Model**
```
class Post extends Model
{
    protected $fillable = [
      'uid',
      'title',
      'subject',
      'description',
      'image_filename',
      'user_id'
  ];
}

public function comments(){
    return $this->morphMany(Comment::class, 'commentable');
}
```

Controller method post

```
$post->comments()->create([
        'body' => $request->body,
        'user_id' => $request->user()->id,
]);

```

**Comment by sausin** [comment]
Does it work if you use `save` instead of `create` ?

**Comment by jackengine** [comment]
You mean ...
```
    $comment = new Comment();
    $comment->body = $request->body;
    $comment->user_id = $request->user()->id;
    $post->comments()->save($comment);
```
This also produce same error

**Comment by themsaid** [comment]
I can't replicate your issue, MorphMany seems to be working fine.

**Comment by themsaid** [comment]
You need to check the underlaying query generated and try to find why your app behaves in this way.

**Comment by jackengine** [comment]
I am checking. Did you tried it with Laravel Version: 5.4.27?

**Comment by jackengine** [comment]
Fixed. $post was unable to get id from request, so it was generating null for commentable_id. Not issue with laravel.

**Comment by MorezDev** [comment]
> Fixed. $post was unable to get id from request, so it was generating null for commentable_id. Not issue with laravel.

Can you explain how did you solved the "get id" problem. I have the exact same problem but could not solve it.
