### ISSUE TITLE
Illuminate\Http\Request doesn't work as expected when request contains url-encoded characters like %F3

### ISSUE THREAD

**Issue by d3ce1t** [laravel/framework#19961]
- Laravel Version:
5.4.28

- PHP Version:
PHP 7.1.6 (cli) (built: Jun 11 2017 10:21:34) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

- Database Driver & Version:
No database related

### Description:
I have a route that allows POST method. This route only logs the request it receives. If it receives a request with `Content-Type: application/x-www-form-urlencoded` with one or more fields containing url-encoded characters like %F3, then a call to `$request->all()` or `$request->input('something')` returns nothing.

### Steps To Reproduce:
I have created a Git repository just to reproduce this issue -> https://github.com/d3ce1t/laravel-request-bug

**Comment by sisve** [comment]
Your first working example sends `%C3%B3` which is UTF-8 for `ó`. This looks correct since it forms a valid spanish word.

Your second example using `%F3` is invalid UTF-8. I presume you're attempting to use a single-byte encoding, but you don't mention which one. Your input can probably not be decoded, and is silently dropped.

Can you show us your complete request headers?

**Comment by sisve** [comment]
@d3ce1t We've been waiting for a few days on updates from you. Do you still have a problem?

**Comment by d3ce1t** [comment]
I apologise for my delay. Regarding the header of the request, I only set `Content-Type: application/x-www-form-urlencoded`. in Postman. This is the complete POST request:

POST /api/test-bug HTTP/1.1
cache-control: no-cache
Postman-Token: 9370bb5a-dedc-4f3c-9d40-e7489f3f03af
Content-Type: application/x-www-form-urlencoded
User-Agent: PostmanRuntime/6.1.6
Accept: */*
Host: localhost:8000
accept-encoding: gzip, deflate
content-length: 20
Connection: keep-alive

TestField=Comisi%F3n

**Comment by anilcancakir** [comment]
![image](https://user-images.githubusercontent.com/21953173/29418061-0391a792-8374-11e7-862c-4b14f78d43fc.png)

This bug about the PHP json_encode function. I debugged your repository and i found the `json_encode` function is returning false for this request body. If you are use the `utf8_encode` before the logging or using the request body, you can use see working.
