### ISSUE TITLE
Unable to render errors if reporting throws an exception

### ISSUE THREAD

**Issue by Lavoaster** [laravel/framework#19973]
- Laravel Version: Irrelevant
- PHP Version: Irrelevant
- Database Driver & Version: Irrelevant 

### Description:

I had an issue where something was logging to `laravel.log` but it couldn't write to it, so when the exception handler caught it and attempted to log the exception, by also writing to laravel.log, it errored out without logging anything or showing on screen.

So, if the exception handler report throws an exception, there is no way of reporting the exception

### Steps To Reproduce:

Make your log file unwritable: (ug+r, User/Group Add Read permission, ug-w, User/Group Revoke Write permission
```
touch storage/logs/laravel.log
chmod ug+r,ug-w storage/logs/laravel.log
```

Throw an exception anywhere in the application.

### Possible Fix:

In [here](https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php#L80) at line 80.

```
// Global catch all so we can still render errors if we're unable to report them.
try {
    $this->getExceptionHandler()->report($e);
} catch (\Exception $e) {}
```

I can submit this as a PR, or you could make the change yourself. I just want to ensure that this is something you want to pursue first.

**Comment by themsaid** [comment]
Thank you, a PR was submitted here: https://github.com/laravel/framework/pull/19977

**Comment by Lavoaster** [comment]
🎉 Thanks @themsaid
