### ISSUE TITLE
File not found error when retrieving file stored in s3 from artisan command

### ISSUE THREAD

**Issue by Awophil91** [laravel/framework#19982]
- Laravel Version: 5.4
- PHP Version: 5.6

Accessing a file stored in s3 using the storage facade from a controller action returns the file but retrieving the same file from s3 using an artisan command always results in file not found.

### Steps To Reproduce:
s3 settings in .env is:
AWS_KEY=AK...
AWS_SECRET=5P...
AWS_REGION=us-east-1
AWS_BUCKET=pymta

In a controller action, save a file in s3 this way:
$path = 'test.txt'
Storage::disk('s3')->put($path, 'hello');

In a controller action, verify that the file was stored this way:
$path = 'test.txt';
dd(Storage::disk('s3')->get($path));

Create an artisan command and try retrieving the same file using the same s3 settings in the command's handle method with the same code snippet above:
 $path = 'test.txt';
 dd(Storage::disk('s3')->get($path));

Execute the command from the command line using php artisan.

**Comment by Awophil91** [comment]
In an artisan command, try retrieving a file that exists in s3 using the laravel storage facade.

**Comment by passionInfinite** [comment]
Can you show what you are trying to do? As I am not getting what is your issue. @Awophil91

**Comment by Awophil91** [comment]
Ok . In a controller action, save a file in s3 these way:
$path = 'test.txt'
Storage::disk('s3')->put($path, 'hello');
Storage::disk('s3')->delete($path);

Retrieving the same file in a controller action works fine:
 $path = 'test.txt';
dd(Storage::disk('s3')->get($path));

But retrieving the same file from an Artisan command using the same s3 settings and the same code above always results in a 
[Illuminate\Contracts\Filesystem\FileNotFoundException]
test.txt
[League\Flysystem\FileNotFoundException]
File not found at path: test.txt

**Comment by themsaid** [comment]
I can't replicate your issue and nobody else seems to be able to, you'll need to debug into your app to find out why it's working this way.

**Comment by Awophil91** [comment]
@passionInfinite and @themsaid Thanks. I tried again after reading your comment. I restarted the server, cleared configuration and somehow, the error doesn't occur again.

**Comment by themsaid** [comment]
glad it works :)
