### ISSUE TITLE
Why container rebound event is after resolved not bound

### ISSUE THREAD

**Issue by FreedomKnight** [laravel/framework#19987]
- Laravel Version: 5.4.*
- PHP Version: php71
- Database Driver & Version:

### Description:
I want to rebind my class to overwrite MigrationRepository singleton
but I found I should make it first to let rebind singleton work.

### Steps To Reproduce:
I just write singleton in service provider not work
```php
       $this->app->singleton('migration.repository', function ($app) {
            $table = $app['config']['database.migrations'];

            return new DatabaseMigrationRepository($app['db'], $table);
        });
```

I need to make it first to let it work

```php
        $this->app->make('migration.repository');
        $this->app->singleton('migration.repository', function ($app) {
            $table = $app['config']['database.migrations'];

            return new DatabaseMigrationRepository($app['db'], $table);
        });
```

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
