### ISSUE TITLE
env() not working in bootstrap/app.php

### ISSUE THREAD

**Issue by jeremy-smith-maco** [laravel/framework#19986]
- Laravel Version: 5.3.31
- PHP Version: 7.1.6

### Description:
Using `env()` helper method inside of `bootstrap/app.php` does not return the environment variable from the `.env` file. This works in our Lumen projects but not our Laravel projects. Not sure why it is different between the two. Not sure if it is a bug or it's not supposed to work?

### Steps To Reproduce:
**bootstrap/app.php**

```
if (env('LOG_OUTPUT', 'stdout') === 'stdout')
{
    $app->configureMonologUsing(function(Monolog\Logger $monolog)
    {
        $handler = new Monolog\Handler\StreamHandler('php://stdout', Monolog\Logger::DEBUG);
        $handler->setFormatter(new Monolog\Formatter\LineFormatter(null, null, true, true));
        $monolog->setHandlers([$handler]);
        return $monolog;
    });
}
```

**Comment by ngyikp** [comment]
`env()` should not be used outside of config files. Only use the `config()`. 

See https://github.com/laravel/framework/issues/19820#issuecomment-311942958 and https://github.com/laravel/framework/issues/19454#issuecomment-305955056

**Comment by jeremy-smith-maco** [comment]
`config()` does not work in `bootstrap/app.php`. I just don't understand why this works in a Lumen project but not a Laravel project since Lumen is just a minified version of Laravel basically.

**Comment by sisve** [comment]
> ... since Lumen is just a minified version of Laravel basically

This is a bad comparison. There are no guarantees about compatibility between code running on Lumen and Laravel. This issue is just one example on how Laravel and Lumen works differently.

One of the first things Lumen does in `bootstrap/app.php` is booting up dotenv. That is done in a later stage in Laravel, during bootstrapping, which happens after the request is captured. Thus Laravel does not make the environment variables available until a later stage. Another relevant different is that Laravel will not boot dotenv if you're using cached configuration files.

There are many differences between Laravel and Lumen; never assume they are identical or work identically.

**Comment by jeremy-smith-maco** [comment]
Ah, I see. You can just boot up dotenv at the beginning of `bootstrap/app.php` in a Laravel project to get it working. Works now.

```
try
{
    (new Dotenv\Dotenv(__DIR__.'/../'))->load();
}
catch (Dotenv\Exception\InvalidPathException $ignored) { }
```

Thank you.

**Comment by crynobone** [comment]
> Ah, I see. You can just boot up dotenv at the beginning of bootstrap/app.php in a Laravel project to get it working. Works now.

This is a hack, use it with caution.

**Comment by jeremy-smith-maco** [comment]
I had originally moved the code to `AppServiceProvider` and accessed `env('LOG_OUTPUT')` in a config file and then in the service provider access `config('app.log_output')` and then set the logger but seems easier to just boot up dotenv in `bootstrap/app.php`.

**Comment by sisve** [comment]
Make sure you document this somewhere. You have just introduced a large security issue if you host your application on Apache+Windows. All other applications on the same host can see your secret database credentials.

Have fun.

**Comment by jeremy-smith-maco** [comment]
So should I do what I originally was going to do to fix it by moving the code in the original post to the `AppServiceProvider` and using `config()` instead of `env()`?

**Comment by jeremy-smith-maco** [comment]
@sisve

**Comment by mnpenner** [comment]
Bump.

Where *should* we be putting startup code that depends on env vars?

**Comment by omitobi** [comment]
@jeremy-smith-maco Did you find a solution to this?

**Comment by jeremy-smith-maco** [comment]
Nope. In the latest version they have changed how the logging works so you can just make your own stdout logger class and use that in the config instead.
