### ISSUE TITLE
Two different projects under one server, happen .env conflict

### ISSUE THREAD

**Issue by liubusian** [laravel/framework#19990]
- Laravel Version: 5.*.*
- PHP Version: 5.6.25
- Database Driver & Version: MySQL 5.7

### Description:
I have two different projects under one server. [Project1, Project2]

Now, I use CURL to call Project2 from Project1

A magical, Project2 throw a PDOException

I try debug it

I found
Project2 PDO's connect setting is load from Project1 (two project is same setting and is Project1's)

### Steps To Reproduce:
1. Set Project1 .env
```
DB_HOST=localhost
DB_DATABASE=db1
DB_USERNAME=user1
DB_PASSWORD=pwd1
```
2. Set Project2 .env
```
DB_HOST=localhost
DB_DATABASE=db2
DB_USERNAME=user2
DB_PASSWORD=pwd2
```
3. In Project1 welcome
```
class WelcomeController extends Controller {
      public function test(){
             Curl::to('http://localhost/Project2/test')
                     ->post();
      }
}
```

4. In Project2 welcome
```
class WelcomeController extends Controller {
      public function test(){
             return User::first();
      }
}
```

5. In Project2 Illuminate\Database\Connectors\Connector
```
public function createConnection($dsn, array $config, array $options)
    {
        $username = Arr::get($config, 'username');

        $password = Arr::get($config, 'password');

        try {
            \Log::info([$dsn, $username, $password, $options]);
            $pdo = new PDO($dsn, $username, $password, $options);
```
The results obtained:
     `exception 'PDOException' with message 'SQLSTATE[HY000] [2002]`

And Project2 laravel.log:
```
[2017-07-11 16:52:06] local.INFO: array (
  0 => 'mysql:host=localhost;port=3306;dbname=db1',
  1 => 'user1',
  2 => 'pwd1',
  3 => 
  array (
    8 => 0,
    3 => 2,
    11 => 0,
    17 => false,
    20 => false,
  ),
)
```

Why is that so?

**Comment by sisve** [comment]
You are using Apache on Windows and have forgotten to cache your configuration files. Run `php config:cache` to fix this.
