### ISSUE TITLE
Global Scope and addSelect not working

### ISSUE THREAD

**Issue by xxRockOnxx** [laravel/framework#20007]
- Laravel Version: 5.4.27
- PHP Version: 7.0.18
- Database Driver & Version: psql 9.6.3

### Description:
set `static::addGlobalScope` with `select` predefined.

On future reference. I tried `select` and `addSelect` but columns are not being called. `Joins` and `groupby` and `where` works. Googled and found out `addSelect` should be used when future referencing.

Not sure if it's intended and just do it without scope (which I think defeats its purpose) and reselect, rejoin, regroup, etc.

### Steps To Reproduce:

Use this scope (or anything as long as its global): https://gist.github.com/xxRockOnxx/f3afeebf7589fa55a6a4309fb6f90f6e

Future reference and add select like:
https://gist.github.com/xxRockOnxx/be20cf41b2c8f790e22d5b1e56b1af9e

Run.

**Comment by xxRockOnxx** [comment]
**SOLVED but not sure**

I instead added `addSelect` on `addGlobalScope` on the thought of it replaces my `select`

I said not sure because I'm not sure if scopes are meant to be applied last. Maybe this should be noted at the docs?

**Comment by themsaid** [comment]
Good point, please feel free to send a PR to the docs repository :)

**Comment by xxRockOnxx** [comment]
https://github.com/laravel/docs/pull/3435
