### ISSUE TITLE
[5.4] Problem configuring Pusher

### ISSUE THREAD

**Issue by santigarcor** [laravel/framework#20009]
- Laravel Version: 5.4.28
- PHP Version: 7.1

### Description:
I'm trying to configure the pusher broadcast driver, but after following the documentation guide, when i try to do anything i get: `Class 'Pusher' not found`.

### Steps To Reproduce:
- Create a new laravel aplication.
- Run `composer require pusher/pusher-php-server`.
- Enable the BroadcastServiceProvider in the `config/app.php` file.
- Change the `BROADCAST_DRIVER` value to `pusher` in the `.env` file.
- Run `php artisan` and you will see the error.

**Comment by okmkey45** [comment]
Hello, I was able to reproduce this with the same exact steps

**Comment by it-can** [comment]
Seems Pusher v3 added a namespace...

**Comment by themsaid** [comment]
Yes for now use `^2.6`, 5.5 will support Pusher v3
