### ISSUE TITLE
I want to report a serious security issue, 

### ISSUE THREAD

**Issue by Shinkurt** [laravel/framework#20015]
Hello,

I want to report a serious security issue in laravel. however emailing the listed emails got me no response, I am wondering if I should publish it here or elsewhere

**Comment by it-can** [comment]
Maybe taylor@laravel.com ?

**Comment by themsaid** [comment]
@Shinkurt you can email me themsaid@gmail.com if you want

**Comment by Shinkurt** [comment]
@themsaid : done! :)

**Comment by Kyslik** [comment]
Whatever it is, just out of curiosity, I would like to know more if its possible (I mean after the issue is confirmed & resolved).
