### ISSUE TITLE
"php artisan migrate" causes error by default.

### ISSUE THREAD

**Issue by Kunimaru** [laravel/framework#20012]
- Laravel Version: 5.4
- PHP Version: 7.0.19-1
- Database Driver & Version:
10.1.23-MariaDB

### Description:

When you run the php artisan migrate command, the following error occurs:

```
[Illuminate\Database\QueryException]                                             
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too l  
  ong; max key length is 767 bytes (SQL: alter table `users` add unique `users_em  
  ail_unique`(`email`)) 
[PDOException]                                                                   
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too l  
  ong; max key length is 767 bytes  
```

### Related issues:

#17714 #17530 #17508 #17337

### Proposal:

Occurring the error by default is very frustrating. Why don't we add to the project the equivalent to `defaultStringLength()` solution? (changing length by an environment variable or one sql or etc.)
Generating such error by default is no match for the sophisticated framework. If desirable to change, I 
can create a pull request.

**Comment by ankurk91** [comment]
vanilla files ?

#### Solution 1
```php
// config/database.php
 'mysql' => [
            // ...
            // Lets stick to utf-8 until we get MySql 5.7.x on server
            'charset' => 'utf8',
            'collation' => 'utf8_unicode_ci',
        ],
```
Just change the charset, dont go with **mb4**.

#### Solution 2
https://laravel-news.com/laravel-5-4-key-too-long-error

**Comment by Kunimaru** [comment]
Then why don't you specify that mysql 5.6 is unsupported in document or support it?

**Comment by devcircus** [comment]
Per the documentation:
> Index Lengths & MySQL / MariaDB
Laravel uses the utf8mb4 character set by default, which includes support for storing "emojis" in the database. If you are running a version of MySQL older than the 5.7.7 release or MariaDB older than the 10.2.2 release, you may need to manually configure the default string length generated by migrations in order for MySQL to create indexes for them. You may configure this by calling the  Schema::defaultStringLength method within your AppServiceProvider:
///php
use Illuminate\Support\Facades\Schema;

/**
 * Bootstrap any application services.
 *
 * @return void
 */
public function boot()
{
    Schema::defaultStringLength(191);
}
///
> Alternatively, you may enable the innodb_large_prefix option for your database. Refer to your database's documentation for instructions on how to properly enable this option.

**Comment by Kunimaru** [comment]
oh i'm sorry to miss it :(
i thought doc is in Server Requirements.

**Comment by FaizanNoor** [comment]
File: config/database.php
change the following
FROM ->
'charset' => 'utf8mb4',
'collation' => 'utf8mb4_unicode_ci',

TO ->
'charset' => 'utf8',
'collation' => 'utf8_unicode_ci',

**Comment by MarrefRa** [comment]
I'm having this issue whith SQL SERVER :
  SQLSTATE[42000]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Incorrect syntax near ','. (SQL: ALTER TABLE
   products ADD FULLTEXT fulltext_index (name, reference, ean13, description))
In Connection.php line 458:

  SQLSTATE[42000]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Incorrect syntax near ','.

please help

**Comment by strellymbaya** [comment]
> File: config/database.php
> change the following
> FROM ->
> 'charset' => 'utf8mb4',
> 'collation' => 'utf8mb4_unicode_ci',
> 
> TO ->
> 'charset' => 'utf8',
> 'collation' => 'utf8_unicode_ci',

Thank you @FaizanNoor [ commented on Jul 3, 2018 ]

For your answer ! This just fixed the Bug
