### ISSUE TITLE
Laravel 5.4 - Issue with Jobs after move model

### ISSUE THREAD

**Issue by pirmax** [laravel/framework#20028]
I have this error on my console. I use Jobs from Laravel 5.4 and I have move the **Feed Model** in **App\Models\Feed**. Since two days, I have this error because **Laravel** doesn't find the **Feed Model**. I have restart my Jobs with **php artisan queue:restart**.

> [2017-07-13 10:45:33] staging.ERROR:
> Symfony\Component\Debug\Exception\FatalThrowableError: Class
> 'App\Feed' not found in
> /home/site_com/http/www/vendor/laravel/framework/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php:45

    <?php
    
    namespace App\Jobs;
    
    use App\Models\Feed;
    use Illuminate\Bus\Queueable;
    use Illuminate\Queue\SerializesModels;
    use Illuminate\Queue\InteractsWithQueue;
    use Illuminate\Contracts\Queue\ShouldQueue;
    use Illuminate\Foundation\Bus\Dispatchable;
    
    class FetchFeeds implements ShouldQueue {
    	protected $feed;
    	public function __construct(Feed $feed)
        {
            $this->feed = $feed;
        }
    }

**Comment by laurencei** [comment]
This is expected behavior. It is because you didnt restart the queue after making changes.

You should always restart the queue during your deployment process.

**Comment by sisve** [comment]
Assuming you've actually restarted the workers; can you confirm that this is a newly dispatched job, and not an old job that is serialized with the old Feed class?

**Comment by pirmax** [comment]
I have already restart the Job with **php artisan queue:restart**.
