### ISSUE TITLE
Use Hash::make() instead of bcrypt directly in ResetsPasswords.php

### ISSUE THREAD

**Issue by ArondeParon** [laravel/framework#20027]
In `ResetsPasswords.php` there is a direct call to `bcrypt` on [line 104](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/Auth/ResetsPasswords.php#L104). This in itself is not really a problem since `Hash::make()` acts as a wrapper for `bcrypt`, but would it not be more elegant to use `Hash::make()`, as this is also the [recommended way](https://laravel.com/docs/5.4/hashing) to create password hashes?

**Comment by Dylan-DPC** [comment]
This is not a bug. Open an issue in the laravel/internals repo
