### ISSUE TITLE
Wrongly generated query on relationship

### ISSUE THREAD

**Issue by rienheuver** [laravel/framework#20033]
- Laravel Version: 5.4.28
- PHP Version: 7.0.18
- Database Driver & Version: mysql 5.7.18

### Description:
Building a chained query on a relationship results in the wrong builded query when using 'orWhere.'

### Steps To Reproduce:
Say have a model User with a hasMany relation Posts and posts have an attribute 'status' which is an integer. We want to get all posts with status 1 or 2 from user Peter (with user_id = 1):
`$peterPosts = $peter->posts()->where('status', 1)->orWhere('status', 2)->get();`

This will retrieve all posts by Peter with status 1 and all posts (whether or not belonging to Peter) with status 2. The query generated will be much like:
`SELECT * FROM posts WHERE user_id = 1 AND status = 1 OR status = 2`
As a developer I would intuitively have thought the query to be much like:
`SELECT * FROM posts WHERE user_id = 1 AND (status = 1 OR status = 2)`

The latter would refrain any chained query to find models not belonging to the relationship on which it is queried.

**Comment by themsaid** [comment]
yes you need to use `where(function($query){....})` and add both conditions inside the closure.

**Comment by rienheuver** [comment]
Yes, that's the fix I used. But isn't it counter-intuitive to do that? As a developer you'd assume the results only to be based on the related relationship. Putting brackets around consecutive where-statements after the relation_id = x would solve it, not cause any new problems (as far as I can see) and make it more intuitive.

**Comment by themsaid** [comment]
well yes what you say makes sense but not easy to implement, if you have the time to open a PR that would be great :)

**Comment by rienheuver** [comment]
Can you point me in the right direction where this query exactly is build? I'll take a look at it next week.
