### ISSUE TITLE
Pagination speed

### ISSUE THREAD

**Issue by aleksejjj** [laravel/framework#20036]
- Laravel Version: 5.4.28
- PHP Version: 7.1.1
- Database Driver & Version: PDO for MySQL

### Description:
Generated queries:

`SELECT COUNT(*) as aggregate FROM table_name` 
`WHERE id IN ('1', '2', '3'.... lots of Ids here) `
`AND table_name.deleted_at IS NULL `

`SELECT * FROM table_name`
`WHERE id IN ('1', '2', '3'.... lots of Ids here) `
`AND table_name.deleted_at IS NULL `
`LIMIT 60 OFFSET 0;`

Timelines:
In MySQL Workbench it took 0.12 sec
In MySQL Workbench it took 0.015 sec.

Laravel Debugbar - Queries tab 0.18 sec.
Laravel Debugbar - Queries tab 0.1 sec.

BUT: full request take 1.5 sec, and if I try

`\Debugbar::startMeasure('render', 'Request time');`
`$myItems = MyModel::whereIn('id', $ids)->paginate(60);`
`\Debugbar::stopMeasure('render');`

I see `Request time (1.3s)` in timeline.

### Steps To Reproduce:

1. Table with 100K records in DB.

2. $ids - array with 10K items.

3. Paginate - `MyModel::whereIn('id', $ids)->paginate(60);`

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only.
