### ISSUE TITLE
Data too long for column 'payload'

### ISSUE THREAD

**Issue by haheute** [laravel/framework#20042]
- Laravel Version: 5.4.28
- PHP Version: PHP 7.0.18-0ubuntu0.16.04.1
- Database Driver & Version: Ver 15.1 Distrib 10.0.29-MariaDB

### Description:
I found that crawlers/bots produced lots of errors in my laravel log:

22M	./laravel-2017-07-09.log
220M	./laravel-2017-07-11.log
276M	./laravel-2017-07-12.log
221M	./laravel-2017-07-13.log

The message was: 

`Illuminate\Database\QueryException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'payload' at row 1 (SQL: update `sessions` set `payload` = YTo0OntzOjY6Il90b2t.....`  

followed by a long payload string. Seemed to come from 'SEOkicks-Robot'.

I changed the session driver to memcached, and the errors stopped.

I am not sure if this could be the result of a mistake I made or if something changed with laravel. Maybe somebody knows more.

### Steps To Reproduce:
Change session driver to database and watch the log.

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by sisve** [comment]
The default migration that creates the sessions table creates a payload column that can hold 64kb of session data. Sure, the payload if encoded and mangled, so it's less, but still a lot of data. So, why are you storing huge amounts of data in your session?

A solution would be to change your payload column into a longtext which supports 2gb data.

**Comment by haheute** [comment]
I don't want to store something there. This just happens when a bot visits the site. It gets an entry in the sessions table. I don't know where this payload comes from - if laravel creates the payload then or the bot..

**Comment by haheute** [comment]
Ok. Maybe I'm wrong. Visited photo ids are stored in the session to prevent repeated view counting. Perhaps the crawler has viewed too many photos. So this is not a laravel bug.

**Comment by irpanrain** [comment]
@haheute maybe you can tell me how to fix it? cause I found same issue after action import data, I don't know why

**Comment by eskiesirius** [comment]
> > @haheute maybe you can tell me how to fix it? cause I found same issue after action import data, I don't know why
> 
> I faced same problem during bulk data import using csv. I don't have exact idea about that problem. If you have found solution then please explain me problem solution...
> 
> thanks in advance

im experiencing this.. any solution?

**Comment by eskiesirius** [comment]
> > > > @haheute maybe you can tell me how to fix it? cause I found same issue after action import data, I don't know why
> > > 
> > > 
> > > I faced same problem during bulk data import using csv. I don't have exact idea about that problem. If you have found solution then please explain me problem solution...
> > > thanks in advance
> > 
> > 
> > im experiencing this.. any solution?
> 
> Laravel stores all session data like Old Inputs, Session Flash messages etc. many more. now when we tries to stores bigger array data in session, when our request processes to much long time like Bulk Data Import at that time we get this error. because **datatype of payload** column is a **`text`**.
> 
> I solved this error during Data Import Request using [Laravel Queue](https://laravel.com/docs/9.x/queues) for your reference I share blog post about [Data Import using Queue](https://www.codecheef.org/article/upload-large-csv-file-using-queue-job-batching-in-laravel)

That is what I thought using laravel queue but I don't like to use that service yet.. im currently using Laravel Excel to upload excel files.. maybe chunk can fix this? not sure

**Comment by harshpatel147** [comment]
you used any third party package for Excel Import? I was do the data import from CSV file manually  Because I already solve this issue using Queue during Data import using CSV file.  I make Data Import as a Synchronous Queue using `dispatchSync` method. [read it](https://laravel.com/docs/9.x/queues#synchronous-dispatching) & try once

**Comment by eskiesirius** [comment]
> you used any third party package for Excel Import? I was do the data import from CSV file manually Because I already solve this issue using Queue during Data import using CSV file. I make Data Import as a Synchronous Queue using `dispatchSync` method. [read it](https://laravel.com/docs/9.x/queues#synchronous-dispatching) & try once

yes i know queue already.. im using Maatwebsite\Excel for my import
