### ISSUE TITLE
removeExistingOrdersFor bug

### ISSUE THREAD

**Issue by xakzona** [laravel/framework#20057]
- Laravel Version: 5.4.28
- PHP Version: 7.1
- Database Driver & Version:
There is a bug in chunkById function:
When I use in sql with orderByRaw chunkById calls method removeExistingOrdersFor in Query/Builder.php
`Collection::make($this->orders)
                    ->reject(function ($order) use ($column) {
                        **return $order['column'] === $column;**
                    })->values()->all()
`
As I use raw order, callback function doesnt have 'column' index in array $order:
`array (
  'type' => 'Raw',
  'sql' => 'firstColumn desc, lastColumn asc',
)`

**Comment by themsaid** [comment]
Sorry but I don't understand your issue, please share more details.

**Comment by xakzona** [comment]
\Clients::orderByRaw('(select 1)')->chunkById(...)
will cause exception:
callback function doesnt have 'column' index in array

**Comment by themsaid** [comment]
Fix sent to https://github.com/laravel/framework/compare/5.4...themsaid:Builder/removeExistingOrdersFor?expand=1
