### ISSUE TITLE
Bug with groupBy and database strict mode

### ISSUE THREAD

**Issue by projct1** [laravel/framework#20066]
- Laravel version: 5.4.28
- MySQL version: 5.7.16

### Description
Have this simple structure:
```php
class Report extends Model
{
    public function invoice()
    {
        return $this->hasOne('App\Invoice');
    }
}

class Invoice extends Model
{
    const STATUS_WAIT_PAYMENT = 42;

    public function scopeUnpaid($Q)
    {
        $Q->where('status_id', self::STATUS_WAIT_PAYMENT);
    }
}

class Bar extends Model
{
    public function reports()
    {
        return $this->hasMany('App\Report');
    }
}

Report::where('sum', '>', 0)->whereHas('invoice', function($Q) {
    $Q->unpaid();
})->select('bar_id')->groupBy('bar_id')->havingRaw('count(bar_id) >= 1')->paginate(20);
```
This code generates two queries:
```sql
select count(*) as aggregate from `reports`
    where `sum` > '0' and exists (select * from `invoices` where `reports`.`id` = `invoices`.`report_id` and `status_id` = '42')
    group by `bar_id` having count(bar_id) >= 1

select `bar_id` from `reports`
    where `sum` > '23' and exists (select * from `invoices` where `reports`.`id` = `invoices`.`report_id` and `status_id` = '25')
    group by `bar_id` having count(bar_id) >= 1 limit 20 offset 0
```
Why `sum > 0` replaced to `sum > 23` and `status_id = 42` to `status_id = 25`?

If disable `strict_mode` in `config/database.php` and remove `->select('bar_id')` all works fine.

P.S. If replace `status_id = 42` to unexisting `status_id = 9999`, then second query will not execute.

**Comment by sisve** [comment]
A quick comment, your issue does not mention the actual problem. I presume you get an error message. You also mention that you can solve it by "disable strict_mode in config/database.php and remove ->select('bar_id')", which implies that both any of those two actions will cause the error. 

Is the problem about pagination with `GROUP BY` or `HAVING`? If so it is a known issue; [Pagination does not work when use having in query builder](https://github.com/laravel/framework/issues/16320)

**Comment by rorc** [comment]
@sisve MySQL version is 5.7.16.
I have no errors. I just look in Debugbar on result of queries and dont understand this:
> Why sum > 0 replaced to sum > 23 and status_id = 42 to status_id = 25?

**Comment by rorc** [comment]
Another query with `groupBy` and `having` works fine even with `->paginate(20)`
```mysql
select count(*) as aggregate from `reports`
    where exists (select * from `bars` where `reports`.`bar_id` = `bars`.`id`) and `sum` > '0'
               and exists (select * from `invoices` where `reports`.`id` = `invoices`.`report_id` and `status_id` = '42') group by `id` having sum(`sum`) <= 1500
```

**Comment by rorc** [comment]
@sisve 
> You also mention that you can solve it by "disable strict_mode in config/database.php and remove ->select('bar_id')", which implies that any of those two actions will cause the error.

I have not error if i switch strict mode to false and remove `->select('bar_id')`, because in this mode set select to only one field, which will be using in `groupBy`. So, MySQL just ignore this error.

**Comment by rorc** [comment]
New values for `sum` and `status_id` gets from previous binding.
Before query above i use many `withCount`, one of which this:
```php
$builder->withCount([
    'revises as revise_success' => function($Q) {
        $Q->where('status_id', 42);
    }
]);
```
And after reset selects (`->select('bar_id')`) previous bindings replacing to `sum`, etc...
