### ISSUE TITLE
the parameter with simplePaginate method in Illuminate/Database/Query/Builder.php

### ISSUE THREAD

**Issue by kylesean** [laravel/framework#20063]
- Laravel Version: 5.3.31
- PHP Version: 7.0.1
- Database Driver & Version: 5.7.14

### Description:
As the documentation says, Laravel provides two paging methods，`paginate()` and `simplePaginate()`，but the simplePaginate method seems to make parameter plus 1. is it a bug or I'm wrong?

### Steps To Reproduce:
![qq 20170714184821](https://user-images.githubusercontent.com/19353263/28209483-3f306924-68c5-11e7-8cd5-b70187c96955.png)

![qq 20170714184826](https://user-images.githubusercontent.com/19353263/28209469-31853c14-68c5-11e7-8bf3-d4e1119115f9.png)
![qq 20170714184830](https://user-images.githubusercontent.com/19353263/28209497-4b39f8d4-68c5-11e7-9720-008e03f74a80.png)

Hope to reply,thanks.

**Comment by kylesean** [comment]
sorry，that's my fault.

**Comment by sisve** [comment]
`simplePaginate` takes one extra row to be able to determinate that there are more rows, so it can render a "go to next page" link. This is used to calculate `Paginator::$hasMore`. The extra item is trimmed away in [Paginator::setItems](https://github.com/laravel/framework/blob/f94fc026c64471ca5a5b42919c9b5795021d783c/src/Illuminate/Pagination/Paginator.php#L65-L72)

**Comment by kylesean** [comment]
@sisve Yes,you are absolutely right.
When I realized that,I closed this issue immediately.haha,thanks for your   expanation.
