### ISSUE TITLE
Blade block comment {{-- with <?php     ?> --}} not working

### ISSUE THREAD

**Issue by radoslavv** [laravel/framework#20060]
- Laravel Version: 5.4.25
- PHP Version: PHP 7.1.4 (cli) (built: Apr 11 2017 20:08:12)
- Database Driver & Version: does not matter

### Description:
blade block comment does not work

### Steps To Reproduce:
Code like test.blade.php with:
```
    {{-- comment 1
        <?php
            echo 'comment 1'
        ?>
    --}}
    {{-- comment 2
        <?php
            echo 'comment 2'
        ?>
    --}}
    {{-- comment 3
        <?php
            echo 'comment 3'
        ?>
    --}}
    {{-- comment 4
        <?php
            echo 'comment 4'
        ?>
    --}}
```
results into HTML code like comment completely ignored and everything inside executed:
```
    {{-- comment 1
        comment 1    --}}
    {{-- comment 2
        comment 2    --}}
    {{-- comment 3
        comment 3    --}}
    {{-- comment 4
        comment 4    --}}
```

**Comment by sileence** [comment]
Please try using the `@php` `@endphp`tags instead. These should be ignored by Blade.

**Comment by sileence** [comment]
This works as expected: 

```
                {{--
                @php

                    echo "Hello world!";

                @endphp
                --}}
```

`echo "Hello world!";` is not printed here.

**Comment by sileence** [comment]
I have another possible solution for this issue, in case https://github.com/laravel/framework/pull/20065 is merged :)

**Comment by radoslavv** [comment]
@php
@endphp
is a working workaround :-)

**Comment by trainoasis** [comment]
`@php @endphp` is not ok with i18n tools like poedit or certain built-in tools (which you cant edit) that scan only php tags for i18n strings. It was bad enough I had to change all my `{{}}` with `__() `strings to be inside `<?php  ?>`. I guess no other options here?
