### ISSUE TITLE
Validation Rule 'same' Always Return False When Has Space

### ISSUE THREAD

**Issue by yosualb** [laravel/framework#20064]
- Laravel Version: 5.4.27
- PHP Version: 7.1.1
- Database Driver & Version: 

### Description:
Validation rule 'same' needs parameter, but it has strict format (not allowing space between : and parameter) but regex, min, max, and other rules which has parameter can use space.

### Steps To Reproduce:
`$this->validate($req, [
  'password' => ['required', 'string', 'min: 6', 'same:conf_password'],
  'conf_password' => ['required', 'string', 'min: 6', 'same:password'],
]);`

to 

`$this->validate($req, [
  'password' => ['required', 'string', 'min: 6', 'same: conf_password'],
  'conf_password' => ['required', 'string', 'min: 6', 'same: password'],
]);`

`same:parameter` to `same:<SPACE>parameter`

**Comment by devcircus** [comment]
Its not that 'same' has a stricter format, it's just that some of the rules can evaluate their parameters correctly despite the empty space. Everything after the ':' is considered the parameter, so you shouldn't include a space.

**Comment by systemovich** [comment]
@devcircus, isn't that the bug?

**Comment by devcircus** [comment]
It's default php behavior. ' 3' becomes 3 just like '3' becomes 3, however when referring to another field, 
' password' doesn't equal 'password'. It could probably be accounted for, but don't think it should be considered a bug.

**Comment by systemovich** [comment]
@devcircus, that makes sense. Thanks.
