### ISSUE TITLE
Universal To using CC and BCC, ends up with 3 mails

### ISSUE THREAD

**Issue by empresarrollo** [laravel/framework#20075]
- Laravel Version: 5.4.26
- PHP Version:  7.0.2
- Database Driver & Version: MySQL 5.7.28

### Description:
When using "Universal TO" in config/mail.php:

```
    'to' => [
        'address' => 'myuser@mymail.com',
        'name' => 'Testing Dude'
    ],
```

and using MAIL_DRIVER=log, or smtp, or sparkpost, Laravel put your "universal to" also on the CC and BCC fields of the email. Then you end up with 3 copies of the same mail.

### Steps To Reproduce:

1. php artisan make:notification InvoicePaid --markdown=mail.invoice.paid
2. create view for mail.invoice.paid
3. modifiy toMail() in InvoicePaid:   `return (new MailMessage)->subject('Invoice Paid')->markdown('mail.invoice.paid');`
3. `$user = App\User->create(...........)`
4. `$user->notify((new InvoicePaid($invoice));`

using MAIL_DRIVER=log you would see the folowing in laravel.log:

```
[2017-07-14 17:31:12] local.DEBUG: Message-ID: <d4764c5f1436236c5460ae97b0bbb686@myapp.dev>
Date: Fri, 14 Jul 2017 17:31:12 -0300
Subject: Invoice Paid
From: MyApp <noresponse@email.myapp.com>
To: Testing Dude <myuser@mymail.com>
Cc: Testing Dude <myuser@mymail.com>
Bcc: Testing Dude <myuser@mymail.com>
MIME-Version: 1.0
Content-Type: multipart/alternative;
```

with log everything is OK, but if you use smtp or sparkpost to test the emails you and up with triple the mails.

**Comment by Douglasdc3** [comment]
Setting a global `to` in your config will override any other mail address already send before. According to the code you should only use this for local development.

```
        // If a global "to" address has been set, we will set that address on the mail
        // message. This is primarily useful during local development in which each
        // message should be delivered into a single mail address for inspection.
        if (isset($this->to['address'])) {
            $this->setGlobalTo($message);
        }
```

**Comment by devcircus** [comment]
#16705

**Comment by empresarrollo** [comment]
> Setting a global to in your config will override any other mail address already set before. According to the code you should only use this for local development.

Yeah, I'm using for development, and testing that sparkpost works ok. But setting `to` also put that address in CC and BCC (although I'm not using that).

**Comment by themsaid** [comment]
Check https://github.com/laravel/framework/pull/16705
