### ISSUE TITLE
Gate::resource should merge extra habilites

### ISSUE THREAD

**Issue by wlepinski** [laravel/framework#20081]
- Laravel Version: v5.4.28
- PHP Version: 7.1.4-1+deb.sury.org~xenial+1
- Database Driver & Version: Irrelevant

### Description:
Using the method `Gate::resource()` and defining the last attribute `array $abilities = null` as described on the documentation:

> By default, the view, create, update, and delete abilities will be defined. *You may define additional abilities by passing an array as the third argument to the resource method*. The key of the array defines the name of the ability while the value defines the method name:

Currently, if you define the third argument it is overriding the default abilities on the resource method.

### Steps To Reproduce:
Use the method `Gate::resource()` passing the third attribute as an array of extra abilities.

**Comment by browner12** [comment]
i agree with you, the wording on the documentation suggests that they will merge, but personally i would prefer to keep the existing functionality, and just change the docs.

by overriding, you still have the ability to define extra methods by something like

```
Gate::resource('blogs', 'BlogController', ['index', 'create', 'store', 'edit', 'update', 'destroy', 'foo', 'bar']);
```

granted, it is a little verbose, but if we switch to a merging functionality, we lose the ability to only define our custom methods, and get rid of the default ones.

```
Gate::resource('blogs', 'BlogController', ['foo', 'bar']);
```

**Comment by wlepinski** [comment]
@browner12 Sounds reasonable to just update the docs with the correct information.

**Comment by themsaid** [comment]
Thanks for https://github.com/wlepinski/docs/pull/1 :)
