### ISSUE TITLE
[Question] How To Test The Preset Before Submitting For Pull Request

### ISSUE THREAD

**Issue by Laraveldeep** [laravel/framework#20091]
I think I have done the preset for Zurb Foundation but I have no idea how to test it. 
or should I just submit the pull request and you guys will test and integrate?
Sorry bit new in this process.
Thanks!

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by laurencei** [comment]
Hi @Laraveldeep - thanks for your first time contribution on the other PR.

Contribution guidelines can be found here: https://laravel.com/docs/5.4/contributions

There is also a guide by @JeffreyWay on Laracasts here: https://laracasts.com/series/how-do-i/episodes/20

Unfortunately as @Dylan-DPC mentioned - this area is reservered for bug reports. If you need further assistance, you can get further assistance on your question on one of the many great support areas:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.
