### ISSUE TITLE
Url query string

### ISSUE THREAD

**Issue by liubusian** [laravel/framework#20117]
First, I have a url:
`www.example.com/site?param1=value1&param2=value2&param3=value3`
when: 
    `dd(request->all())`
get:
```
array:3 [
  "param1" => "value1"
  "param2" => "value2"
  "param3" => "value3"
]

```

After, I use `http_build_query` to build query
I get:
`www.example.com/site?param1=value1&amp;param2=value2&amp;param3=value3`

Print:
```
array:3 [
  "param1" => "value1"
  "amp;param2" => "value2"
  "amp;param3" => "value3"
]
```

How to avoid `param2` becomes `amp;param2`

**Comment by bobbybouwmann** [comment]
Look at your url, you have a double `&` in the form of `&amp;`

**Comment by devcircus** [comment]
Show your http_build_query call.

**Comment by srmklive** [comment]
Don't think its a laravel issue. Its primarily an issue with symfony component.

**Comment by srmklive** [comment]
I think you should do something like this:

```
http_build_query([
  "param1" => "value1"
  "param2" => "value2"
  "param3" => "value3"
], '', '&');
```

**Comment by ttomdewit** [comment]
For some reason Safari on Mac (10.1.1 on Mac 10.12.5) doesn't work with the answer @srmklive mentioned. Works fine on Google Chrome, though ¯\_(ツ)_/¯.
