### ISSUE TITLE
Function does not exist

### ISSUE THREAD

**Issue by tabuna** [laravel/framework#20125]
- Laravel Version: 5.4.28
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7.12

### Description:
![2017-07-18 15 00 01](https://user-images.githubusercontent.com/5102591/28316056-ccb00e60-6bc9-11e7-83f7-7db9bd4164e4.png)

The [documentation](https://laravel.com/docs/5.4/helpers#method-str-before) says that `str_before` exists
But neither in the helper, nor in the class[ `Illuminate/Support/Str.php`](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Support/Str.php) it does not exist.

[Pull Requests not accepted](https://github.com/laravel/framework/pull/19592)

### Steps To Reproduce:

Call function `str_before`

**Comment by tabuna** [comment]
Will it be supported or deleted from the documentation?

**Comment by kamui545** [comment]
It looks like the helper is only available on dev-master (5.5).

**Comment by ntzm** [comment]
It's been removed from the docs laravel/docs#3448

**Comment by ManuelSamudio12** [comment]
FYI - This helper still in the docs [https://laravel.com/docs/5.6/helpers#method-str-before](url)

**Comment by devcircus** [comment]
The helper indeed exists in 5.6 which is why it is in the 5.6 docs.
