### ISSUE TITLE
5.4 Login Throttling - missing directories ?

### ISSUE THREAD

**Issue by mslindow** [laravel/framework#20136]
- Laravel Version: 5.4.?
- PHP Version: 7.1.6
- Database Driver & Version: ?

### Description: When I attempt to login with an incorrect password, Laravel tries to record the attempt for login throttling, but it fails because the temp directories (in the data directory) don't exist. What would cause them to not be created? We have already set the rights as 777 all the way down. No change.
The error I get is:
![image](https://user-images.githubusercontent.com/17485413/28333303-be61b774-6bb4-11e7-9970-38f35d5a9511.png)

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by mslindow** [comment]
Dylan,

Thank you for your response.

Where do I find the forums or slack channel ?

Shawn

**Comment by Dylan-DPC** [comment]
@mslindow slack channel: larachat.co
