### ISSUE TITLE
remove use of == and != from the framework

### ISSUE THREAD

**Issue by xcombelle** [laravel/framework#20141]
#20111 Looks like the use of == or != leads to bugs which would be easily avoided by using only strict comparison

A simple search show that they are lot of them

```
$ egrep "([^']!=[^=])" . -R |wc -l
46
$ egrep "([^=!']==[^='])" . -R|wc -l
166

```
A good thing to do would be, once these occurrence removed would be to add a pre or post commit hook to avoid future insertions.

**Comment by browner12** [comment]
that's a pretty broad statement, and not always applicable IMO.

they should be dealt with on a case-by-case basis.

**Comment by xcombelle** [comment]
I quickly looks on the result and found zero case it should not be applicable. If conversion is needed, it should be explicitly made. So implicit conversion should not  be used.

**Comment by koenhoeijmakers** [comment]
Although i'm for strict comparison, but i'm not that much for regexing the whole project and expecting nothing to break.

**Comment by xcombelle** [comment]
I agree, that some change will break things, that's why I did not proposed an automatic replacement. It should be considered as a long term aim. At the very least, a warning should be raised if new occurrences are introduced by some commit.

**Comment by Dylan-DPC** [comment]
This is not a bug. Open an issue in the laravel/internals repo

**Comment by xcombelle** [comment]
migrated to the right bug tracker.
