### ISSUE TITLE
Bug with chunk method in collections

### ISSUE THREAD

**Issue by wideivan** [laravel/framework#20145]
- Laravel Version: 5.4.28
- PHP Version: 7.1.6
- Database Driver & Version: MySQL 5.7.17

### Description:
Sorry for my bad english, but I will try explain this problem.
I put index array (with 6 int numbers) to collection.
Then I use chunk method for get two collections with 3 items in each collection.
So, in first collection I got index array, but in second collection, I got associative array.
That is wrong for me. I expect to get index array in second collection too.

### Steps To Reproduce:
<img width="430" alt="2017-07-19 11 17 03" src="https://user-images.githubusercontent.com/1703419/28357748-222a27bc-6c75-11e7-8715-9156464b7c54.png">

**Comment by ntzm** [comment]
This isn't a bug, the `preserve_keys` argument on `array_chunk` is set to true: https://github.com/laravel/framework/blob/5.4/src/Illuminate/Support/Collection.php#L1234

My suggestion would be to call `->values()` on each collection to get a non-associative array

**Comment by wideivan** [comment]
Wow, the same behavior for the array_chunk function.
<img width="404" alt="2017-07-19 11 44 55" src="https://user-images.githubusercontent.com/1703419/28358492-b945fb24-6c77-11e7-9da6-bece4d551bdd.png">
So, you are right, it is not a laravel issue.

**Comment by decadence** [comment]
You have 0,1,2 indexes in first case (tinker just doesn't show them), 3,4,5 in second case. Everything is fine.
![screenshot_1](https://user-images.githubusercontent.com/1434668/28367905-39670d5c-6c9b-11e7-9e69-5c54b5106041.png)

**Comment by wideivan** [comment]
If you will encoded chunked collections to json you can see that in first case you will get array, but in second case it will be object.
<img width="706" alt="2017-07-19 16 04 08" src="https://user-images.githubusercontent.com/1703419/28368226-5155f4c2-6c9c-11e7-9aa8-4c5ed716b2ab.png">

**Comment by decadence** [comment]
Again it's normal behaviour for json_encode for case when array has keys from 0 to N consequently.
