### ISSUE TITLE
The increment in ArrayStore

### ISSUE THREAD

**Issue by LaoQi** [laravel/framework#20153]
- Laravel Version: lastest
- PHP Version:7.0
- Database Driver & Version:

### Description:
The method `increment` in `cache\ArrayStore` has a bug that array index out of range 

```
 public function increment($key, $value = 1)
    {
        // $key not exist
        // if (!isset($this->storage[$key])) $this->storage[$key] = 0;
        $this->storage[$key] = ((int) $this->storage[$key]) + $value;

        return $this->storage[$key];
    }
```
https://github.com/laravel/framework/blob/5.4/src/Illuminate/Cache/ArrayStore.php#L53

**Comment by themsaid** [comment]
handled in https://github.com/laravel/framework/pull/20156

Thanks :)
