### ISSUE TITLE
Нету свойства username в трейте AuthenticatesUsers

### ISSUE THREAD

**Issue by userbq201** [laravel/framework#20154]
- Laravel Version: 5.4.0
### Нету свойства username 
В ларе 5.2 оно было и мы могли менять обязательное поле email, а теперь как это делать?

**Comment by Dylan-DPC** [comment]
Hey.. would recommend posting this issue in English (though Google Translate does a good job)

**Comment by themsaid** [comment]
english please

**Comment by m1guelpf** [comment]
@themsaid 
![screen shot 2017-07-19 at 14 51 55](https://user-images.githubusercontent.com/23558090/28371264-c18bebca-6c9c-11e7-9ef2-a8478d5ffcec.png)

**Comment by devcircus** [comment]
Override the username method in authenticatesUsers trait and return the string representing the attribute you want to use.
```
public function username()
{
    return 'email';
}
```
