### ISSUE TITLE
Database Connection Issue

### ISSUE THREAD

**Issue by xyrintech** [laravel/framework#20159]
- Laravel Version: 5.4
- PHP Version: 7.1
- Database Driver & Version: Mysql

### Description:
There has been an issue with database connection, let's say we add new option in migrate command for a requirement like multi-tenant. Further run the same with switching the database connections before we run the command then the framework is still picking up the previous database connection rather than the new connection which we created dynamically. Please see the code:

This function takes care of the tenant and command - php artisan migrate --tenant=*

protected function registerConsoleTerminateEvent()
    {
        $this->getConsoleDispatcher()->addListener(ConsoleEvents::TERMINATE, function(ConsoleTerminateEvent $event)
        {
            $tenant = $event->getInput()->getParameterOption('--tenant', null);
            
            if( ! is_null($tenant))
            {
                if ($tenant == '*' || $tenant == 'all')
                {
                    $command = $event->getCommand();
                    $input = $event->getInput();
                    $output = $event->getOutput();
                    $exitCode = $event->getExitCode();

                    $tenants = $this->getAllTenants();

                    foreach($tenants as $tenant)
                    {   
                       
$connection = $tenant->connection
config()->set('database.default', $connection);
        config()->set('database.connections.' . $tenant->connection . '.database', $tenant->databasePrefix . $tenant->databaseName);
    
        if ($hasConnection)
        {   
            config()->set('tenant', $tenant->toArray());
            $this->app['db']->purge($this->defaultConnection); 
        }
        
        $this->app['db']->setDefaultConnection($connection);

                        
                        $event->getOutput()->writeln('<info>Running command for ' . $this->getActiveTenant()->name . '</info>');

                        try
                        {  
                            $exitCode = $command->run($input, $output);
                        }
                        catch (\Exception $e)
                        {
                            
                            $event = new ConsoleExceptionEvent($command, $input, $output, $e, $e->getCode());

                            $this->getConsoleDispatcher()->dispatch(ConsoleEvents::EXCEPTION, $event);

                            $e = $event->getException();

                            throw $e;
                        }
                    }

                    $event->setExitCode($exitCode);
                }
            }
        });
    }

### Steps To Reproduce:

Well, please try review the code. Lemme help you to understand this in a better way in simple words:
1) We have added option to specify --tenant=* for running migration for different connections. 
2) We are changing the config settings for database connection  and further setting the defaultConnection as this connection. When we set this defaultConnection, we always purge the previous connection. 
3) Now lets say we have 2 tenants in system - tenant_a, tenant_b with different database db_a and db_b
4) When we run the migration then we change the database using config() function and further we run the command with event inputs and outputs. 
5) Issue is that once we set the first database connection then even we set the other database connection this does get the pending migrations from the another database. Ex. first we execute command with database - db_a and then we change this to db_b Now, framework is not recognising the pending migrations from db_b

**Comment by themsaid** [comment]
Such questions should be asked on the forums, please post here a to-the-point bug report, one that we can reproduce on a fresh laravel installation. Your comments looks to me like a question on how to do this or that.
