### ISSUE TITLE
Bug with guard in new Blade Directives

### ISSUE THREAD

**Issue by khanhvu14** [laravel/framework#20162]
- Laravel Version: 5.4.29
- PHP Version: 7.1
- Database Driver & Version:

### Description:
@auth
logged
@endauth

I have a error with $guard is null

### Steps To Reproduce:

In my project I fixed:
@auth('web')
logged
@endauth

In new Blade Directives, set default $guard = 'web'.

**Comment by m1guelpf** [comment]
@khanhvu14 What do you mean by 
> In new Blade Directives, set default $guard = 'web'.

**Comment by it-can** [comment]
Same error I described here: https://github.com/laravel/framework/pull/20114

**Comment by joshmanders** [comment]
You are using it wrong.

```
@auth()
logged
@endauth
```

This is the correct way.

**Comment by m1guelpf** [comment]
@joshmanders I can make it work the other way

**Comment by m1guelpf** [comment]
@khanhvu14 @joshmanders @it-can Opened https://github.com/laravel/framework/pull/20166
