### ISSUE TITLE
[5.4] Mix helper returns full path breaking change

### ISSUE THREAD

**Issue by it-can** [laravel/framework#20164]
- Laravel Version: 5.4.29
- PHP Version: 7.1.6
- Database Driver & Version: MySQL

### Description:
Breaking change introduced here:  #19968 

The filepath is passed to the ```asset()``` helper, so it will return a full url. In the previous version the ```mix()``` function only returned the file path.

This prevents a way to prepend a custom domain, for example a custom domain or CDN.

### Steps To Reproduce:
```
mix('js/app.js');
```
Laravel 5.4.29: Returns ```http://www.example.com/js/app.js```

Laravel 5.4.28 and lower: Returns ```/js/app.js```

### Solution:
Remove the asset() helper from this line: https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/helpers.php#L563

Or merge PR #20165

**Comment by mathieutu** [comment]
No time to explain for now, but it prevents nothing at all if you read the code of asset method.

**Comment by it-can** [comment]
Could be, but it is a breaking change I think...

**Comment by themsaid** [comment]
Check Taylor's comment: https://github.com/laravel/framework/pull/20165#issuecomment-316492009
