### ISSUE TITLE
Eloquent ORM in first method toArray report errors

### ISSUE THREAD

**Issue by emtalk-qf** [laravel/framework#20187]
- Laravel Version: 5.4.*
- PHP Version:5.6
- Database Driver & Version: mysql 5.7

### Description:
Execution code：self::first()->toArray();
If the data in the data table is empty, then the error is reported：Call to a member function toArray() on null

**Comment by themsaid** [comment]
Yes `first()` might return null.

**Comment by emtalk-qf** [comment]
@themsaid 
`
//  self::first() Can an array be compatible only in the following manner ?
$_data = self::first();
if ( $_data ){
    $_data = $_data->toArray();
}
`
