### ISSUE TITLE
 Middlewares don't get the correct Request type 

### ISSUE THREAD

**Issue by ThibaudDauce** [laravel/framework#20186]
- Laravel Version: 5.4.30
- PHP Version: 7.1.7

### Description:

When I build a middleware, I expect to get the correct `FormRequest` type requested by the controller. But the request given to the middlewares is the standard `Illuminate\Http\Request`. 

### Steps To Reproduce:

I built a small demonstration project https://github.com/ThibaudDauce/form-request/commit/1d2f011ac6d7f42116cb34b630b8307ad3547a82

You just have to create a controller with a `FormRequest` and dump the `get_class($request)` in a middleware.

My specific problem is how to filter request arguments. If my `FormRequest` has a `filters` method, I want to call this method and execute the filters. But this doesn't work because the `FormRequest` is never passed to the middleware. https://github.com/ThibaudDauce/form-request/commit/6fb6c313ee68e5d718653b19f9d1d6477d644676

**Comment by themsaid** [comment]
This is the intended behaviour at the moment, please move your change proposal to 
https://github.com/laravel/internals repo, that's where we keep feature requests and proposals.
