### ISSUE TITLE
Adding a new column and its reference in one go fails silently. 

### ISSUE THREAD

**Issue by salarmehr** [laravel/framework#20184]
- Laravel Version: 5.3.31 
- PHP Version: 7
- Database Driver & Version: mysql 5.7.12

### Description:

SQL allows adding a column and its reference in one statement. 

```
column_definition:
    data_type [NOT NULL | NULL] [DEFAULT default_value]
      [AUTO_INCREMENT] [UNIQUE [KEY] | [PRIMARY] KEY]
      [COMMENT 'string']
      [COLUMN_FORMAT {FIXED|DYNAMIC|DEFAULT}]
      [STORAGE {DISK|MEMORY|DEFAULT}]
      [reference_definition]
  | data_type [GENERATED ALWAYS] AS (expression)
      [VIRTUAL | STORED] [UNIQUE [KEY]] [COMMENT comment]
      [NOT NULL | NULL] [[PRIMARY] KEY]

reference_definition:
    REFERENCES tbl_name (index_col_name,...)
      [MATCH FULL | MATCH PARTIAL | MATCH SIMPLE]
      [ON DELETE reference_option]
      [ON UPDATE reference_option]
```

Following this, a user may try to run the following statement: 

```
    public function up()
    {
        Schema::table('orders', function (Blueprint $table) {
            $table->addColumn('integer', 'planId')->references('id')->on('plans');
        });
    }
```
This will run without error  so user assume that it works as intended while it creates the column without the reference.

**Comment by themsaid** [comment]
Nothing in the docs state that you could do this, please read the docs to see what's possible.

**Comment by salarmehr** [comment]
Thanks for your comment. Obviously I have already read the doc. The doc does not provide all possibilities. The mentioned method chain is logically valid and I think if it was not intended to work an exception should be thrown.  I belive @taylorotwell  has tried to design Laravel in a consistent way.
