### ISSUE TITLE
Undefined property: stdClass::$column_name when generating a model

### ISSUE THREAD

**Issue by metaodi** [laravel/framework#20190]
- Laravel Version: 5.1
- PHP Version: 7.1
- Database Driver & Version: mysqlnd 5.0.12-dev 

### Description:

The `MySqlProcessor` assumes that the result from MySQL contains a [lowercase column called `column_name`](https://github.com/laravel/framework/blob/7f1710a88399feba16aea18f1ed4f9ae76c00183/src/Illuminate/Database/Query/Processors/MySqlProcessor.php#L16).

On my installation, if I run the query from [`compileColumnListing` of MySqlGrammar](https://github.com/laravel/framework/blob/7f1710a88399feba16aea18f1ed4f9ae76c00183/src/Illuminate/Database/Schema/Grammars/MySqlGrammar.php#L35)

```sql
select * from information_schema.tables where table_schema = ? and table_name = ?
```

The result contains the column `COLUMN_NAME` in uppercase.

I don't really know where this is changed. In the driver? Maybe it makes sense to change the query in `MySqlGrammar` to ensure the correct case of the result:

```sql
select column_name as "column_name" from information_schema.tables where table_schema = ? and table_name = ?
```

### Steps To Reproduce:

If I try to create a new model using the [builder-plugin for OctoberCMS](https://github.com/rainlab/builder-plugin), I get the following error:

```
"Undefined property: stdClass::$column_name" on line 18 of /var/www/public/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/MySqlProcessor.php
```

There is already an issue in that repo: https://github.com/rainlab/builder-plugin/issues/161

**Comment by codejam1024** [comment]
In Laradock:
![laradock1](https://user-images.githubusercontent.com/5414233/28497944-fd27fe68-6fc5-11e7-9b4c-bcf72fffb28e.png)
In Debian Mysql Server
![debian-mysql-server](https://user-images.githubusercontent.com/5414233/28497946-083a4112-6fc6-11e7-8b3c-7819bfece02c.png)

**Comment by hyubs** [comment]
Also encountered this in Laravel 5.4.28. Environment is PHP 7 and MySQL 8.0 using Laradock.

The fix suggested above by @metaodi worked. 

Changed the query found in `Illuminate\Database\Schema\Grammars\MySqlGrammar@compileColumnListing`:

```sql
select column_name from information_schema.columns ...
```

...to...

```sql
select column_name as `column_name` from information_schema.columns ...
```

**Comment by Desseres** [comment]
@hyubs Thanks! It works!

PHP 7.0.21, MySQL 8.0.1-dmr
Error: Undefined property: stdClass::$column_name 
Example: Schema::connection('mysql2')->hasColumn('pharmacy', 'id')

**Comment by lkmadushan** [comment]
Is this ok?

**Comment by laurenkt** [comment]
Is there a solution to this problem that doesn't involve patching something in `/vendor` pulled in by composer? Otherwise the patch is going to have to be applied every time the project dependencies are pulled in.

**Comment by metaodi** [comment]
@themsaid why did you close this? Shouldn't the fix mentioned above by @hyubs be implemented?

**Comment by themsaid** [comment]
@metaodi feel free to open a PR

**Comment by laurenkt** [comment]
Opened a PR #21037

**Comment by laurenkt** [comment]
In the meantime if someone wants to automate patching this in `vendor/` the command I used is

```
sed -i 's/select column_name from information_schema/select column_name as `column_name` from information_schema/g' 'vendor/laravel/framework/src/Illuminate/Database/Schema/Grammars/MySqlGrammar.php'
```

I've put this as a post-update-cmd hook in composer.json to apply it automatically.

**Comment by loren-garcia** [comment]
> Also encountered this in Laravel 5.4.28. Environment is PHP 7 and MySQL 8.0 using Laradock.
> 
> The fix suggested above by @metaodi worked.
> 
> Changed the query found in `Illuminate\Database\Schema\Grammars\MySqlGrammar@compileColumnListing`:
> 
> ```sql
> select column_name from information_schema.columns ...
> ```
> 
> ...to...
> 
> ```sql
> select column_name as `column_name` from information_schema.columns ...
> ```

Totally works! Thanks"
