### ISSUE TITLE
Storage::delete not work because Util::normalizePath remove first backslash

### ISSUE THREAD

**Issue by 1dnmr** [laravel/framework#20202]
- Laravel Version: 5.4.27
- PHP Version: 5.6.30

### Description:

When call Storage::delete() it calls inside Util::normalizePath which return path without staring backslash. 

### Steps To Reproduce:

If is pass something like "\Users\username\..." normalizePath returns "Users\username\..." and Storage::delete() not work.

**Comment by haakym** [comment]
I am not sure you should be passing the leading slash.

What is your config for the file system?

Please note the following from the Flysystem docs:

> Relative Paths
> Portability is a very important concept within Flysystem. In order to roll out this aspect to the fullest, all paths in Flysystem are relative. File system root paths, whether remote or local, are viewed as endpoints. Because of this, file systems are movable independently. This allows parts of the application file handling to move to other storage types, while the majority is in a centralized location.
> Like the storage type, root paths are an implementation detail. When root paths are defined as configuration, the stability of your code improves.
**source**: https://flysystem.thephpleague.com/core-concepts/#relative-paths

See this resolved issue on the flysystem repo, it could be related: https://github.com/thephpleague/flysystem/issues/477

**Comment by sisve** [comment]
"\Users\username..." indicates that you want to work with the local filesystem and the File facade, not the Storage facade.
