### ISSUE TITLE
Other Laravel projects get failure when one of them calls an API

### ISSUE THREAD

**Issue by martinrios95** [laravel/framework#20207]
- Laravel Version: 5.0.35
- PHP Version: 5.6.30
- Database Driver & Version: MySQL 5.7.17-log (Windows 10 64-bit)

### Description:
When I was running a function on routes section on my Laravel project (_path-to-project_/app/Http/routes.php), my developer partner, working in another project but in the same framework and host (we're using the same development-web-server to work on distinct projects), had a syntax error on a query my partner had to get, referencing my database I was working.

The function calls Google Maps API to search and update geographic coordinates, the HTTP-request makes it on JSON.
 
Then, when the script finished, my partner could continue working as well.

### Steps to Reproduce:

- Start working on a Laravel project and make a script on routes.php:
`
Route::get('home', function(){
    // Put your database code or call an API...
});
`
- Then, run it on your browser...
- In another browser tab, get into another Laravel project and run it. It'll display a message.

**Comment by morloderex** [comment]
@martinrios95 This is a server configuration problem on your end.

**Comment by martinrios95** [comment]
But neither Apache Server or PHP made me a fatal error, only MySQL-related. All the projects we work are on my dev-server.

**Comment by sisve** [comment]
Two sites on Apache on Windows? Upgrade to Laravel 5.4 (since 5.0 is no longer supported) and run `php artisan config:cache` on both sites.

**Comment by martinrios95** [comment]
Thank you! I've found the problem... It was related from PHP-dotenv issue [here](https://github.com/vlucas/phpdotenv/issues/219).

So, I'll try upgrading Laravel and see if this problem disappears from the sites.
