### ISSUE TITLE
@yield supports prefix

### ISSUE THREAD

**Issue by meness** [laravel/framework#20211]
- Laravel Version: 5.4.30
- PHP Version: 7.1
- Database Driver & Version: MySQL 

### Description:
`@yield` directive supports default value currently. It's good to make it supports a prefix if the value or the default value exists. It would help in cases like defining page title with this format: `Laravel - Welcome!`.

**Comment by lk77** [comment]
why do you need a prefix ? 

it seems to me that it needs to be included in the value or the default value. And you can add it before the yield directive i think.

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
