### ISSUE TITLE
skip and take does not work with appends

### ISSUE THREAD

**Issue by jimgwhit** [laravel/framework#20218]
- Laravel Version: 5.4.30
- PHP Version:5.6.22
- Database Driver & Version:Client API version | mysqlnd 5.0.11-dev
-- | --

### Steps To Reproduce:
```
public function indexTake(Request $request)
    {
        If (!empty($request->input('page'))) {
            $page = $request->input('page');
        } else {
            $page = "1";
        }
        If (!empty($request->input('adopted'))) {
            $adopted = $request->input('adopted');
        } else {
            $adopted = "0";
        }
        $perpage = "5";
        $offset = ($page - 1) * $perpage;
        $krows = DB::select('select COUNT(dogid) as count from dc_dogs where adopted = :adpt', ['adpt' => 0]);
        $numrows = $krows[0]->count;
        $paglinks = ['adopted' => $adopted];
        $dogs = DB::table('dc_dogs')
                        ->where('adopted', '=', $adopted)
                        ->skip($offset)->take($perpage)->get();
        return view('dog/index2')->with(compact('dogs', 'pagelinks'));
    }
```
and view
```
<?php echo $dogs->appends($pagelinks)->links(); ?>
```
gives error, here is some of the error

(1/1)                                         BadMethodCallException                                                                          Method appends does not exist.
--
in Macroable.php (line 74)
at Collection->__call('appends', array(array('adopted' => '0')))in index2.php (line 28)
at Collection->appends(array('adopted' => '0'))in index2.php (line 28)
at include('C:\\Bitnami\\wampstack-5.6.22-0\\apache2\\laravel54up\\resources\\views\\dog\\index2.php')in PhpEngine.php (line 42)
at PhpEngine->evaluatePath('C:\\Bitnami\\wampstack-5.6.22-0\\apache2\\laravel54up\\resources\\views/dog/index2.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'dogs' => object(Collection), 'pagelinks' => array('adopted' => '0')))in PhpEngine.php (line 20)
at PhpEngine->get('C:\\Bitnami\\wampstack-5.6.22-0\\apache2\\laravel54up\\resources\\views/dog/index2.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'dogs' => object(Collection), 'pagelinks' => array('adopted' => '0')))in View.php (line 137)
at View->getContents()in View.php (line 120)
at View->renderContents()in View.php (line 85)
at View->render()in Response.php (line 38)

However appends with skip and take worked in ver 5.1

If I change this part:
```
$dogs = DB::table('dc_dogs')
                        ->where('adopted', '=', $adopted)->paginate(5);
                        //->skip($offset)->take($perpage)->get();
        return view('dog/index2')->with(compact('dogs', 'pagelinks'));
```
To paginate(5); then the appends also works.  Please fix this issue.

**Comment by decadence** [comment]
appends is method of Paginator. You call it on Collection. That's wrong.
paginate returns Paginator, get returns Collection.

**Comment by jimgwhit** [comment]
@decadence what in the World are you talking about? I have a "resultset" using skip and take, appends doesn't work.  This worked in ver 5.1.

**Comment by decadence** [comment]
Collection is the result set. And this class has no appends method. Did you even read error message?
It never worked and it doesn't have to work this way and it's definitely not a bug.
I repeat: appends exists only on Paginator class which is returned by paginate, get returns Collection class, which you call result set.

**Comment by jimgwhit** [comment]
I just created a lenthaware and it works
```
public function indexTest(Request $request)
    {
        If (!empty($request->input('page'))) {
            $page = $request->input('page');
        } else {
            $page = "1";
        }
        $perpage = "5";
        $offset = ($page - 1) * $perpage;
        $krows = DB::select('select COUNT(dogid) as count from dc_dogs where adopted = :adpt', ['adpt' => 0]);
        $numrows = $krows[0]->count;
        echo $numrows;
        $t1 = "b";   // just test for querystring
        $dogs = DB::table('dc_dogs')
                        ->where('adopted', '=', 0)
                        ->skip($offset)->take($perpage)->get();
        $pagelinks = LengthPager::makeLengthAware($dogs, $numrows, $perpage, ['t1' => $t1]);
        return view('dog/index')
                ->with('dogs', $dogs)
                ->with('pagelinks', $pagelinks);
    }
```
and view
```
<?php

foreach ($dogs as $dog) {
    echo $dog->dogname . "<br>";
}
echo $pagelinks;
```
Just had to load the css, but that works.
