### ISSUE TITLE
assertDatabaseHas fails on valid JSON assertion

### ISSUE THREAD

**Issue by edbentinck** [laravel/framework#20237]
- Laravel Version: 5.4.30
- PHP Version: 7.1.3
- Database Driver & Version: MySQL 5.7.17

### Description:
`assertDatabaseHas` throws an error when asserting that a `JSON` string matches, despite the values clearly matching in the error log.

### Steps To Reproduce:
Example Schema:
```
Schema::create('user_settings', function (Blueprint $table) {
    $table->increments('id');
    $table->unsignedInteger('user_id');
    $table->json('settings');
});
```

PHPUnit test:
```
$data = [
    'user_id'  => 1,
    'settings' => '{"foo": "bar"}'
];

$this->post('/user_settings', $data);

$this->assertDatabaseHas('user_settings', [
    'id'       => 1,
    'user_id'  => 1,
    'settings' => '{"foo": "bar"}'
]);
```

Returns:
```
Failed asserting that a row in the table [user_settings] matches the attributes {
    "id": 1,
    "settings": "{\"foo\": \"bar\"}"
}.

Found: [
    {
        "id": 1,
        "user_id": 1,
        "settings": "{\"foo\": \"bar\"}",
        "created_at": "2017-07-22 17:04:35",
        "updated_at": "2017-07-22 17:04:35",
        "deleted_at": null
    }
].
```

As you can see they appear to match, but the assertion fails. Is there a way to assert the database value directly without having to fall back to testing the value from the model?
```
$model = \App\UserSettings::first();
$this->assertEquals('{"foo": "bar"}', $model->settings);
```

**Comment by BostjanOb** [comment]
I think this is not a problem with `assertDatabaseHas` function. It is how MySQL treats JSON field.
Function will run query as `WHERE id = 1 AND user_id = 1 AND settings = '{"foo": "bar"}'` which will not match json field. You must cast string to json.

To make this test pass you should write assertion as:
```php
$this->assertDatabaseHas('user_settings', [
            'id'       => 1,
            'user_id'  => 1,
            'settings' => \DB::raw('CAST(\'{"foo": "bar"}\' AS JSON)')
        ]);
```

**Comment by edbentinck** [comment]
Awesome. I had a feeling it would be something obscure like that. Thanks!
