### ISSUE TITLE
Comments of some eloquent functions confuse IDE autocomplete

### ISSUE THREAD

**Issue by atlas-wong** [laravel/framework#20246]
- Laravel Version: 5.4.30
- PHP Version: 7.0.13
- Database Driver & Version: MariaDB 10.1.19

### Description:
Some eloquent function (eg. first(), all()) comment confuse IDE, autocomplete cannot recognise
In laravel 5.3, the return value in comment of first() is:
"\Illuminate\Database\Eloquent\Model|static|null"
and the autocomplete (i am using ide-helper and phpstorm) work well
and in laravel 5.4, the comment become "mixed" and the IDE cannot recognize the type of the return object

### Steps To Reproduce:
1. Use phpstorm and install ide-helper repo (https://github.com/barryvdh/laravel-ide-helper)
2. Run "php artisan ide-helper:generate" or "php artisan ide-helper:model"
3. Calling first() function of an eloquent object and nothing will popup

self-fix for the issue:
1. Go to ./vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php
2. Go to first() function return part, in my case is line 71 (also applicable for other function that should return a model object)
3. Change the word "mixed" to static (in Laravel 5.3, it is \Illuminate\Database\Eloquent\Model|static|null)
4. Run "php artisan ide-helper:generate" or "php artisan ide-helper:model"
5. Calling first() function of an eloquent object and now autocomplete work well

**Comment by srmklive** [comment]
This is not a laravel error in my opinion. You can also `first` in a non-static way i believe.
 
```
App\User::select(['id','name'])->where('status',1)->first();
```

You should post this issue in ide-helper repo.

**Comment by atlas-wong** [comment]
Yes, this is not any error, but the new comment "mixed" make the IDE cannot distinguish the possible return object so I just want the comment revert to original (i.e. "\Illuminate\Database\Eloquent\Model|static|null").
The self-fix is just for making the IDE work only, I believe the autocomplete function is quite important and convenient for developers.

**Comment by srmklive** [comment]
Hi,

I have added a PR for this #20254.
