### ISSUE TITLE
In the helper file type hinting is not working showing error

### ISSUE THREAD

**Issue by asmshaon** [laravel/framework#20245]
- Laravel Version: 5.4.15
- PHP Version:7.0.21
- Database Driver & Version: mysql, 5.6.33
### Description:
> php artisan optimize
    PHP Parse error:  syntax error, unexpected ':', expecting '{' in /build/bootstrap/helpers.php on line 89
    
    Parse error: syntax error, unexpected ':', expecting '{' in /build/bootstrap/helpers.php on line 89
    Script php artisan optimize handling the post-install-cmd event returned with error code 255
    FAILED: php composer.phar install

**Comment by sisve** [comment]
I'm not sure how this is related to Laravel. What project does the file `/build/bootstrap/helpers.php` belong to? The path doesn't match anything in Laravel.

**Comment by srmklive** [comment]
I agree with @sisve on how this is related to Laravel. Might be that composer is not installed properly.

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue
