### ISSUE TITLE
Problem with Doctrine instantiator

### ISSUE THREAD

**Issue by GertjanRoke** [laravel/framework#20255]
- Laravel Version: 5.4.30
- PHP Version: 7.0.15
- Database Driver & Version:  mysql 5.5

### Description:
When trying to update with composer the following error occurs:
```
Problem 1
    - Installation request for doctrine/instantiator 1.1.0 -> satisfiable by doctrine/instantiator[1.1.0].
    - doctrine/instantiator 1.1.0 requires php ^7.1 -> your PHP version (7.0.15) does not satisfy that requirement.
```

It looks like this bug was introduced with the following PR: #20227  

### Steps To Reproduce:
run composer update

**Comment by RamonSmit** [comment]
Same happens with my composer at the moment

**Comment by Dylan-DPC** [comment]
has been fixed in: https://github.com/laravel/framework/pull/20227 which hasn't been tagged yet

**Comment by lk77** [comment]
no it's not fixed yet.

**Comment by themsaid** [comment]
@lk77 How does it introduce a new one?

**Comment by lk77** [comment]
@themsaid 1.1 requie php 7.1 at least

**Comment by themsaid** [comment]
@lk77 that PR was to update doctrine/inflector not doctrine/instantiator, and doctrine/inflector 1.1 doesn't require php7.1

**Comment by lk77** [comment]
sorry my bad, this issue is not related with the PR

**Comment by themsaid** [comment]
@GertjanRoke I don't see any vendor or laravel itself requiring doctrine/instantiator 1.1, could be a package you installed. A fresh laravel 5.4 application with my latest PR works on php 5.6, just tried it.

**Comment by xitude** [comment]
Im getting this with a fresh install of laravel when I run `composer install` on a production `nginx` `amazon linux ec2` php 7.0.* installed.

**Comment by GertjanRoke** [comment]
@themsiad or really? Sorry then, I will check it today and if I find it I will let you know or close this issue.

**Comment by Dylan-DPC** [comment]
>  I don't see any vendor or laravel itself requiring doctrine/instantiator 1.1, could be a package you installed. A fresh laravel 5.4 application with my latest PR works on php 5.6, just tried it.

@themsaid 
![image](https://user-images.githubusercontent.com/12371125/28605280-63bbd454-71ee-11e7-9f35-00690ccffb71.png)

**Comment by themsaid** [comment]
The problem is that doctrine decided to increase the minimum version in a minor release, all packages using the doctrine affected packages need to fix their version requirement on the previous minor to avoid such problems, we've done that for Laravel so far. Closing this since there's nothing more we can do, all other packages has to do the same.

**Comment by RamonSmit** [comment]
Well, I guess the blame is on Doctrine in this case. They really need to get semver in the rigth way

**Comment by Dylan-DPC** [comment]
@RamonSmit not really. Its a : http://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api

**Comment by Dylan-DPC** [comment]
@GertjanRoke you can check both the PRs. Both libraries didn't have any issues.

**Comment by GertjanRoke** [comment]
@Dylan-DPC I saw your PRs, Thanks for that.

**Comment by MarcTroesken** [comment]
What about 5.3 ?

Still can't deploy on envoyer:

Problem 1
- Installation request for doctrine/instantiator 1.1.0 -> satisfiable by doctrine/instantiator[1.1.0].
- doctrine/instantiator 1.1.0 requires php ^7.1 -> your PHP version (7.0.12) does not satisfy that requirement.

Problem 2
- doctrine/instantiator 1.1.0 requires php ^7.1 -> your PHP version (7.0.12) does not satisfy that requirement.
- phpunit/phpunit-mock-objects 3.4.4 requires doctrine/instantiator ^1.0.2 -> satisfiable by doctrine/instantiator[1.1.0].
- Installation request for phpunit/phpunit-mock-objects 3.4.4 -> satisfiable by phpunit/phpunit-mock-objects[3.4.4].

**Comment by lk77** [comment]
Try to use phpunit ~5.3

**Comment by MarcTroesken** [comment]
No chance ... deploy fails with the same errors. I set phpunit to 5.6 updated composer and ran your 2 commands. No effects.
When running your first composer require I get:
Dependency "doctrine/instantiator" is also a root requirement, but is not explicitly whitelisted. Ignoring.

**Comment by Dylan-DPC** [comment]
Meh you didn't need to do all that:
just read this [link](http://doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html)

**Comment by MarcTroesken** [comment]
@Dylan-DPC yeah that did it for me! Thanks a lot.

**Comment by gopal-g** [comment]
I started a Laravel 5.4 project yesterday on my home pc with php 7.1 and checked out same on laptop with php 7.0. I ran into same error.
I read the link but I am still not sure what is fix here, What should I add to my composer.json in order to just stick with php 7.0 please suggest.

**Comment by lk77** [comment]
you can use platform.config to override your php version.
but i don't undertand why it's still working for me on php 7.0 without it.

**Comment by lk77** [comment]
you can use platform.config to override your phpversion.
delete old composer.lock if you have one or do composer update.

**Comment by Dylan-DPC** [comment]
If you are using PHP 7.0 you don't need to do anything. Since new minor version of doctrine package is PHP 7.1+, composer shouuld pick the earlier version directly unless there is a conflict with another dependency. Would advise you to seek help either on forums or slack channel.

**Comment by adampatterson** [comment]
I wish people would be sensitive to what platforms officially support PHP 7.1, forcing people to install unofficial repositories for LTS versions of Ubuntu.

**Comment by Dylan-DPC** [comment]
You don't have to force people to upgrade 7.1. The folks using 7.0 or below can still use the previous minor version (if there is no conflict with other packages). 

Also do remember that PHP 7.0 has 3 months left of active support (which will mean it will recieve only security fixes for a year) so its high time vendors or whoever concerned should look into releasing official packages

**Comment by adampatterson** [comment]
@Dylan-DPC Agreed! Perhaps the PHP community should work on official releases for different distributions.

**Comment by kgwebsites** [comment]
The simple temporary solution until you update your server interpreted from http://doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html :

1. In your development folder, go to your composer.json. At the bottom of the file is a "config" option. Change it to this: 
"config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true,
        "platform": {"php": "[WHATEVER YOUR SERVER PHP VERSION IS]"}
    }
2. Save file and run composer update
3. Push new composer.lock file to your server
4. Run composer install on your server

**Comment by forevertga** [comment]
Thanks @lk77 , you saved me. I ran the second command and the problem was fixed.

**Comment by donsantana** [comment]
Thanks @lk77, it saved my friday's afternoon.

**Comment by prince-mfour** [comment]
@kgwebsites is the boss! Your post just saved me hours :-)
