### ISSUE TITLE
Feature: Eloquent load default values after insert

### ISSUE THREAD

**Issue by jwz104** [laravel/framework#20250]
I am using UUIDs as primary keys. I generate the UUID with `postgresql`, so it is a default value. The problem is that eloquent doesn't receive the id so the id in the model will be `null` after the insert.

I can't load the id with the `fresh()` function because that function requires the id...

I know that `mysql` doesn't have a function that returns all values after the insert. But `postgresql` and oracle do have the `RETURNING` function.

example:
```
INSERT INTO test(name, description) VALUES ('test', 'test') RETURNING *;
                  id                  | name | description |
--------------------------------------+------+-------------+
 6dcf37d6-712d-11e7-98d2-0f2cbe61cab6 | test | test        |
(1 row)
```

I think this feature would be very nice because eloquent will work much better with default values.  
The only problem is that `mysql` and `sqlite` don't support `RETURNING`

Is there any way this could be implemented into eloquent?

**Comment by Dylan-DPC** [comment]
This is not a bug. Open an issue in the laravel/internals repo

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
