### ISSUE TITLE
Problem on testing (Laravel - PhpUnit) element Select on Form.

### ISSUE THREAD

**Issue by AdriWild** [laravel/framework#20256]
- Laravel Version: 5.0
- PHP Version: 5.6
- Database Driver & Version: Mysql

### Description:
I have a Select wich sends automatically this form with the function onChange=(this.form.submit()),
when I try to test the functionallity doesn't work.

How can I test a submit form without "submit" button?
 
### Steps To Reproduce:

On Tests:

```
$this->visit('projects)
        ->select('Bloggs & Co. Ltd', 'localization_account')
        ->click ('Bloggs & Co. Ltd')
        ->seePageIs('projects')
        ->('Current User: Bloggs & Co. Ltd')
```

On Blade:

```
<select id="localization_account" class="form-control select-organization" onchange="this.form.submit()" name="localization_account">
    <option value="0">--Choose account--</option>
    <option value="1">Bloggs & Co. Ltd</option>
</select>
```

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by AdriWild** [comment]
Thank you so much!

2017-07-26 11:39 GMT+02:00 Ian Torres <notifications@github.com>:
