### ISSUE TITLE
env() returns null when config is cached

### ISSUE THREAD

**Issue by alkin** [laravel/framework#20260]
- Laravel Version: 5.4.28
- PHP Version: 7.0.18
- Cache Driver: file

### Description:
env() function returns null when config is cached

### Steps To Reproduce:
> user@laravel:/var/www$ php artisan tinker
> Psy Shell v0.8.9 (PHP 7.0.18-0ubuntu0.16.04.1 — cli) by Justin Hileman
> => env('APP_DEBUG');
> => true
> 
> user@laravel:/var/www$ php artisan config:cache
> Configuration cache cleared!
> Configuration cached successfully!
> user@laravel:/var/www$ php artisan tinker
> Psy Shell v0.8.9 (PHP 7.0.18-0ubuntu0.16.04.1 — cli) by Justin Hileman
> => env('APP_DEBUG');
> => null
> 
> user@laravel:/var/www$ php artisan config:clear
> Configuration cache cleared!
> user@laravel:/var/www$ php artisan tinker
> Psy Shell v0.8.9 (PHP 7.0.18-0ubuntu0.16.04.1 — cli) by Justin Hileman
> => env('APP_DEBUG');
> => true

**Comment by alkin** [comment]
Apparently the .env file is not loaded if the configs are cached and thats the desired behavior. Even though this is not mentioned in the docs.

Maybe we could improve the documentation by saying that env files should be used only to load configs.

```php
class LoadEnvironmentVariables
{
...
    public function bootstrap(Application $app)
    {
        if ($app->configurationIsCached()) {
            return;
        }
```

**Comment by brunogaspar** [comment]
It's already on the [documentation](https://laravel.com/docs/5.4/configuration#configuration-caching).

**Comment by alkin** [comment]
You are right. Closing the issue.
