### ISSUE TITLE
[5.4] Migrations run to target

### ISSUE THREAD

**Issue by naugrimus** [laravel/framework#20277]
- Laravel Version: 5.4.2
- PHP Version:
- Database Driver & Version:

### Description:

Hello,

i would like to have to option to run migrations to a single point. the only option i have now is to run all migrations with:
php artisan migrate --step=1
this runs all migrations, just with another batch number.

If i could run to a single point, i could test the migration until that one  correct, make corrections, and run the migrations further.
i do not want to skip a migration.

why not have an option like phinx ?
phinx migrate -e development -t 20110103081132

or .net
(`update-database -t {version}`)

add an option in 
Illuminate\Database\Migrations\Migrator.php
method runPending();

$target = Arr::get($options, 'target', false);

if($target) -> remove all the migrations from $migrations after this target

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. Appreciate your understanding :)
