### ISSUE TITLE
Model on api server return data from client table

### ISSUE THREAD

**Issue by tuandinhvu** [laravel/framework#20278]
- Laravel Version: 5.4
- PHP Version: 7.0
- Database Driver & Version:

### Steps To Reproduce:
I have 2 website, one is api server, one is client.
On server i have simple code, example: DB::table('table_name')->get().
When i call request from client to server, server return data of table_name in client, not server.
If i try to change table_name to other table exist in server but not in client, laravel return error table not exist.

Sorry my bad English

**Comment by deleugpn** [comment]
You probably have wrong `.env` settings for your database in one of your applications. Anyway, this does not look like a Laravel bug. You may want to try StackOverflow, Laravel Forums or some other helper channel.

**Comment by tuandinhvu** [comment]
@deleugpn no, if wrong db name why my app still work? 
And i check sure my env is right. :(

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue
