### ISSUE TITLE
Laravel 5.4 testing very different from 5.3

### ISSUE THREAD

**Issue by piercemcgeough** [laravel/framework#20276]
- Laravel Version: 5.4

### Description:
I recently restarted the course but using Laravel 5.4 and looking to see how to get the missing controller and controller method errors without the browser-kit-testing package.

Why is:
`$response = $this->get('/concerts/'.$concert->id);` so different from 
`$this->visit('/concerts/'.$concert->id);`

If I don't assert 200 it doesn't tell me anything and goes straight to "SOME TEST" isn't found.
Asserting 200 gives the following with no further details "Expected status code 200 but received 500."

I can see `NotFoundHttpException` and `ReflectionException - Class App\Http\Controllers\ConcertsController does not exist` and `View [concerts.show] not found.` in the browser alright but nothing in the tests.

### Steps To Reproduce:
Restart course with Laravel 5.4

**Comment by thecrypticace** [comment]
It looks like you're talking about @adamwathan's testing course. This is the wrong place to open issues. There's an issue tracker on the TicketBeast repo you can use.

**Comment by piercemcgeough** [comment]
@thecrypticace Balls that was a late night. Didn't even realise I was in the wrong place. Sorry folks.

**Comment by themsaid** [comment]
No worries :)
