### ISSUE TITLE
@viewExist and @view

### ISSUE THREAD

**Issue by pierreneter** [laravel/framework#20274]
Can we add Blade `@viewExist` and `@view` directive?

`@view` will be `@include`'s alias.
And `@viewExist` will check if the view exists or not.

`@view` will feel similar to the `view` in main code.
And `@viewExist` is necessary to customize the template as desired.

**Example:**
```
@if(@viewExist('view.name'))
    @includeWhen(true, 'view.name')
@endif
```
It solves the problem of checking whether the view exists for includeWhen.
And `@viewExist` Can also do a similar situation as `@includeIf`
```
@if(@viewExist('view.name'))
   @view('view.name')
@endif
```
Or other situations, for example, check whether a `view` exists named `comment` to call a `container` which will have a task each `comment`s.

File `container`:
```
@foreach($comments as $c_key => $comment)
    @view('comment', [$comment])
@endforeach
```
Then
```
@if(@viewExist('comment'))
    @view('container', [$comments]);
@endif
```
.
or more...

**Comment by lk77** [comment]
i don't think it's very useful, views always exist, after all you are coding them, and if one is missing, create it.
I don't see the use case, unless it's for exception rendering, and you want to know if a custom template exists for that exception.

**Comment by Douglasdc3** [comment]
Isn't this something for the [https://github.com/laravel/internals](laravel/internals) repo to discuss feature requests?

**Comment by pierreneter** [comment]
@lk77 so what is the effect of `includeIf` for?
@Douglasdc3 yes. it's not.

**Comment by lk77** [comment]
@pierreneter i don't think it's useful either, for me, views should always exists, i don't see the point of non existing views.

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
