### ISSUE TITLE
Increment Fields with Accessor

### ISSUE THREAD

**Issue by SuNflOw1991** [laravel/framework#20270]
- Laravel Version: 5.4.30
- PHP Version: 7.0.4
- Database Driver & Version: MySQL 5.7

### Description:
If you want to increment or decrement a field, the accessor is called. This causes the error `A non well formed numeric value encountered` if you for example `number_format()` the field. This is because `Illuminate\Database\Eloquent\Model` says in Line 441:
```php
$this->{$column} = $this->{$column} + ($method == 'increment' ? $amount : $amount * -1);
```
If you would change the second `$this->{$column}` to `$this->attributes[$column]` this error should not come up anymore.
```php
$this->{$column} = $this->attributes[$column] + ($method == 'increment' ? $amount : $amount * -1);
```

### Steps To Reproduce:
* Create a database table (let's call it `foo`) with model (let's call it `Foo`) where a integer field (let's call it `integer_field`) is present.
* Within the Model create an Accessor as described in the documentation:
```php
public function getIntegerFieldAttribute($value) 
{
    return number_format($value, 0, ',', '.');
}
```
* Store a value > 1000000 into the `integer_field`.
* now try to increment that field:
```php
$model = Foo::all()->first();
$model->increment('integer_field');
```
* Now you get the error `A non well formed numeric value encountered`.
* Now remove the accessor and try again.
* Error is gone!

---
__Edit__: Previously I wrote mutator but meant accessor. I have corrected that.

**Comment by lk77** [comment]
I think we should call the mutator first, check if it's incrementable, and if not use the attribute directly,
but if we get rid of the mutator, it can lead to strange behaviour to some users because they will expect a call to the mutator, and it will not be the case.

**Comment by SuNflOw1991** [comment]
Yeah, I see, that makes sense.  
Would it be sufficient to check whether the variable is a number after the mutation?  
I would make a PR for this then.

**Comment by Dylan-DPC** [comment]
Btw you spoke about a mutator but defined an accessor :grin:

**Comment by SuNflOw1991** [comment]
Oh, I'm sorry if I confused this.
I'll fix this in my Issue.

**Comment by Dylan-DPC** [comment]
I have tried the exact same thing as your issue has stated but i'm not getting the error. Things are working as expected.

**Comment by SuNflOw1991** [comment]
Okay, I have to add that the integer in the database must be > 1000. Because 999 will not be changed by format number.

**Comment by devcircus** [comment]
Just do it in tinker without using 'decrement' or 'increment'. You get the same error. There's another problem happening here:
```php
//tinker
>>> $number = 2000216;
=> 2000216
>>> $number = number_format($number, 0, ',', '.');
=> "2.000.216"
>>> $number = $number +1;
PHP error:  A non well formed numeric value encountered on line 1
```

**Comment by lk77** [comment]
it's not related to accessor, you just can't increment a string.

**Comment by SuNflOw1991** [comment]
> it's not related to accessor, you just can't increment a string.

Yeah, that is the point. Not the accessor itself is the problem. 
The problem is that the accessor will be called if you want to increment a database field. I think it is a common use case that large numbers will be formatted for better reading.

As @lk77 [suggested](https://github.com/laravel/framework/issues/20270#issuecomment-318268674) we could check if the accessor returns a number and only increment if it is surely a number.

**Comment by devcircus** [comment]
Yes. If you will sometimes need the exact contents of the attribute from the db and sometimes need a modified version, name your accessor differently and call it by name when needed.

**Comment by lk77** [comment]
create a method, not an accessor or mutator, like getFormatedNumber of something like that, and call it in your veiw.

**Comment by SuNflOw1991** [comment]
Okay, then we don't change anything I'll create a other named method as work around.
