### ISSUE TITLE
Resetting password does not clear login lockout

### ISSUE THREAD

**Issue by trevorgehman** [laravel/framework#20285]
- Laravel Version: 5.4.23
- PHP Version: 7.0
- Database Driver & Version: MariaDB 10.2

### Description:
Resetting your password via the forgot password functionality (using `ResetPasswordController`) does not clear a login lockout. This is not typically encountered due to the default "5 attempts in 1 minute" rate, but if you change that to a longer time interval, it could definitely cause problems.

### Steps To Reproduce:
1) Attempt too many invalid logins and force a lockout.
2) Go through password reset email process.
3) Logout of account.
4) Try to login again.

**Comment by lk77** [comment]
i think it's the expected behaviour, if you are lockout you need to wait, password reset or not.

**Comment by trevorgehman** [comment]
I don't think it's intended, because after you reset your password, you're automatically logged in. 

    // trait ResetsPassword

    protected function resetPassword($user, $password)
    {
        $user->forceFill([
            'password' => bcrypt($password),
            'remember_token' => Str::random(60),
        ])->save();

        $this->guard()->login($user);
    }

**Comment by kevmt** [comment]
In Addition to @lk77; it is best not to ignore the lockout process.  The resetPassword should respect the lockout process and best if possible should not allow the user last used password, so It is a bug. And it is a security and infra alert;

- aha!?! I can automate this process to spam there mailer server infrastructure; 
- cause spam to that random or specific target account;

Both parties can however agree, that this can be passed to user-land.

**Comment by trevorgehman** [comment]
I disagree. A common scenario is:

1. Someone forgets their password, tries too many passwords and gets locked out.  
2. They go to reset their password.

The login lockout shouldn't hinder this. There's no reason to prevent them from resetting their password at that point.

Once their password has been successfully reset (which automatically logs the user in), the lockout should be cleared. The only reason I can figure that it isn't is because this was an oversight, since the default settings are so low that no one probably noticed this.

Spamming password reset emails is a separate issue, which I agree should be throttled. But that can be accomplished with a simple route throttle middleware.

**Comment by devcircus** [comment]
This has happened to me on a few occasions on various sites and has worked this way. This is what I expect.

Laravel comes with a base auth scaffold that is meant to be customized according to your security needs. The defaults are sensible. If you need something different, the code is accessible for this purpose

**Comment by trevorgehman** [comment]
@devcircus I'm curious which part of this behavior do you find sensible?

**Comment by devcircus** [comment]
The part about being locked out of your account for a specified time period. The auto-login on reset is indeed unexpected and should be fixed. The lockout time should be respected. The reset functionality should also be locked.

My apologies, I was focused on whether or not you should be able to get around the lock by resetting your password and didn't catch this issue.

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
