### ISSUE TITLE
Mailable later() not working with MailFake

### ISSUE THREAD

**Issue by dryror** [laravel/framework#20286]
- Laravel Version: 5.4
- PHP Version: 7.1

### Description:
Testing (with MailFake) a Mailable that is sent with the later method produces this error:

`Call to undefined method Illuminate\Support\Testing\Fakes\MailFake::later()`

If MailFake is intended to only work with Mailable objects, and Mailable has the later() method (https://github.com/laravel/framework/blob/5.4/src/Illuminate/Mail/Mailable.php#L151), shouldn't the MailFake accomodate that?

Related to #20180. I tried to discuss in the PR after closed, but didn't get a response. Apologies for creating another issue, and I don't think I explained well enough in the initial PR.

**Comment by lk77** [comment]
it's not needed to fake later, because it's released onto the queue via the scheduling system,
so it's out of the scope of the tests.

**Comment by devcircus** [comment]
https://github.com/laravel/framework/pull/20180#issuecomment-316577750
