### ISSUE TITLE
publicPath() not able change new location 

### ISSUE THREAD

**Issue by Qh0stM4N** [laravel/framework#20293]
```
$ php artisan --version && php --version
Laravel Framework 5.4.19
PHP 5.6.30 (cli) (built: Jan 18 2017 19:48:22)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

```
### Description:
I have change public path. my server default www symbolink public_html folder.
I thought it would be easier to install this way. I will not even need ssh access.

ref discuss url:  https://laracasts.com/discuss/channels/general-discussion/where-do-you-set-public-directory-laravel-5

owerwrited ok but this not worked why public_path() function still using 'public' folder.
`dd(public_path());` in controller works but config files not effected.
but change new file system disk in config/filesystems.php
```
'public' => [
            'driver' => 'local',
            'root' => public_path('folders'),
        ],
```
test any controllers 
i see 
```
public function publicPath()
    {
        return $this->basePath.DIRECTORY_SEPARATOR.'public';
    }
```
ref line 379:0 url: https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/Application.php

**Comment by laurencei** [comment]
You can override it and set it to anything you want: https://github.com/laravel/framework/issues/18550

**Comment by Qh0stM4N** [comment]
@laurencei allready use it me. It was a mistake I ran into while trying to make an elfinder connection just because of this in the config/filesystems.php file in fixed 'root' => base_path('public_html/someFolder').

I will try to repeat the error in a way that anyone can see.

**Comment by srmklive** [comment]
You can override the `publicPath` in `AppServiceProvider` as mentioned in #18550 like this:

```
        $this->app->bind('path.public', function() {
            return base_path().DIRECTORY_SEPARATOR.'public_html';
        });
```

**Comment by Qh0stM4N** [comment]
change config/filesystem.php
```
'disks' => [
    'public' => [
            'driver' => 'local',
            'root'   => public_path('files'),

        ],
]
```
add appServiceProvider.php
```
public function register()
    {
        $this->app->bind('path.public', function() {
            return base_path().DIRECTORY_SEPARATOR.'public_html';
        });
    }
```
yes ready try it bug in any controller. 
```
        dd(public_path());
//result 
//"C:\xampp\htdocs\kimweb-release/public_html"

        dd(app('filesystem')->disk('public')->getDriver());
//result
//Filesystem {#645 ▼
  #adapter: Local {#646 ▼
    #pathSeparator: "\"
    #permissionMap: array:2 [▼
      "file" => array:2 [▼
        "public" => 420
        "private" => 384
      ]
      "dir" => array:2 [▼
        "public" => 493
        "private" => 448
      ]
    ]
    #writeFlags: 2
    -linkHandling: 2
    #pathPrefix: "C:\xampp\htdocs\kimweb-release\public\files\"
  }
  #plugins: []
  #config: Config {#647 ▼
    #settings: []
    #fallback: null
  }
}

```
I think public_path() should be everywhere for portability but
this problem can only be specific to my project. I do not know. You can control your own laravel project.

**Comment by laurencei** [comment]
The problem is your config is set before the `AppServiceProvider`, so that is why it has the old value.

You could override the setting for the filesystem in your AppServiceProvider as well. Or just hard code it in your config - do you really need it to be dynamic?

**Comment by Qh0stM4N** [comment]
@srmklive I'm sorry my's english level, you have not been able to tell the problem exactly how the problem will not be done; I will already use this method but this overwriting inactive in configs or filesystem.

**Comment by srmklive** [comment]
As @laurencei suggested you need to override the setting for filesystem in your AppServiceProvider as well.

**Comment by Qh0stM4N** [comment]
Thank you @laurencei  I used static. But it is difficult to understand that writing the source of the problem is overwriting the invalid. I realized I had difficulty in understanding it, so I think that someone else would have difficulty with such a problem. It is not so important that it is completely dynamic
