### ISSUE TITLE
Nested Factories no longer return full object, only Primary Keys

### ISSUE THREAD

**Issue by patrickc91** [laravel/framework#20309]
- Laravel Version: 5.4.24+
- PHP Version: 7.0
- Database Driver & Version: ODBC 13 for Linux
- Running in Docker

### Description:
In Laravel 5.4.16 and below, nested factories for testing would return entire objects. Now I'm only seeing the nested object's primary key being returned. Below is an example of some example code from a caller application, what I used to expect, and what I get now.

##### First Factory
```
$factory->define(Phonecall::class, function($faker)
{
	$startTime = $faker->dateTimeBetween('-1 day', '+2 day');

	return [
		'id' => strtoupper($faker->uuid),
		'subject' => $faker->randomElement(
			[
				'Call Back: No Answer/AM',
				'Call back',
				'Reschedule',
				'Call Back: Busy',
				'Call Back: Not Interested',
			]),
		'lead_closed_at' => null
	];
});
```
##### Second Factory
```
$factory->define(Lead::class, function($faker)
{
	$firstName = $faker->firstName();
	$lastName = $faker->lastName();

	return [
		'id' => strtoupper($faker->uuid),
		'first_name' => $firstName,
		'last_name' => $lastName,
		'full_name' => "$lastName, $firstName",
		'primary_phone' => $faker->optional(.95)->phoneNumber,
		'primary_email' => $faker->optional(.1)->email,
		'address_line1' => $faker->streetAddress,
		'city' => $faker->city,
		'state' => $faker->stateAbbr
        ];
});
```
##### Nested Factory Use
```
	private function makePhonecall()
	{
		return factory(Phonecall::class)->make(
			[
				'id' => $this->phonecallId,
				'subject' => 'FPC Follow-up',
				'lead_closed_at' => new Carbon('2016-10-24 13:26:15'),
				'lead' => factory(Lead::class)->make()
			]);
	}
```

#### Expected Return Value:
```
 [
    "id" => "4AD33440-9604-4EE8-9DA5-F9982E724CB5"
    "subject" => "FPC Follow-up"
    "lead_closed_at" => "2016-10-24 13:26:15"
    "lead" => 
       [
        "id" => "CACB9750-388F-34DE-85D9-FB6295EC21F6"
        "first_name" => "Hillary"
        "last_name" => "Yundt"
        "full_name" => "Yundt, Hillary"
        "primary_phone" => "548.730.3688 x221"
        "primary_email" => null
        "address_line1" => "9938 Hartmann Ramp"
        "city" => "Cassinberg"
        "state" => "CA"
      ]
```

#### Actual Return Value:
```
 [
    "id" => "4AD33440-9604-4EE8-9DA5-F9982E724CB5"
    "subject" => "FPC Follow-up"
    "lead_closed_at" => "2016-10-24 13:26:15"
    "lead" => "CACB9750-388F-34DE-85D9-FB6295EC21F6"
 ]
```

### Steps To Reproduce:
I'm always bad at this part...

1. Set up codeception or PHPUnit
2. Make a couple factories
3. Use a factory's `make()` function to create an object with another factory's `make()` function nested inside to represent a relationship (as shown in the code examples above)

### My Question
Was this change made by design? Perhaps to make DB seeding easier? It's a pretty easy change on my end to account for this. I just didn't see anything about this in any of the change logs.

Sorry if this isn't enough information or anything. Or irrelevant information. I just don't have much experience posting to issue boards on GitHub yet.

**Comment by Dylan-DPC** [comment]
It is intended behaviour. As normally you just need an ID for the foreign key right?

**Comment by devcircus** [comment]
If you need more info, search the pull requests. There was a lot of discussion about this change.

**Comment by patrickc91** [comment]
@Dylan-DPC Correct. I assumed this was the case, I just couldn't find anything referencing the change. @devcircus Of course the one place I didn't look was in the Pull Request section. I'll make sure to look there next time.

Thanks everyone!
