### ISSUE TITLE
Recover password with ajax

### ISSUE THREAD

**Issue by zishanj** [laravel/framework#20304]
With Laravel 5.4 I have successfully implemented Ajax with `login` and `register` form but with `forgot password` I have seen that it does not send 422 error response if there is any form error , instead it reloads page. If it's successful then it does not send Ajax JSON supported response.

Is there any way to make this work with ajax like login and register are already supporting Ajax.

**Comment by laurencei** [comment]
Hi there,

Unfortunately this is not a support area for application issues. This is only for issues/bugs with the framework code itself.

Please close your issue ticket here.

You can instead ask your question on one of the many great support areas:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.

**Comment by zishanj** [comment]
I thought it to be bug/incomplete module because as expected it should work with Ajax like login and register do. But this recover password even does not developed to throw error 422 on incorrect data input, instead its developed to redirect the user. 
-- 
Sent from my Android phone. Please excuse my brevity.
