### ISSUE TITLE
Calling dropColumn when using SQLite causes table to lose autoincrement ID

### ISSUE THREAD

**Issue by voveson** [laravel/framework#20310]
- Laravel Version: 5.1.45
- PHP Version: 7.1.3
- Database Driver: sqlite

### Description:
When dropping a column from a table with an auto-incrementing ID, the column is successfully dropped, but the table loses the `AUTOINCREMENT` property from its ID column.

I have read the docs on [dropping columns](https://laravel.com/docs/5.1/migrations#dropping-columns) and the proposed solution of adding `doctrine/dbal` dependency is not solving this issue.

### Steps To Reproduce:
Create a table using a migration:

```
Schema::create('categories', function(Blueprint $table) {
    $table->engine = 'InnoDB';
    $table->increments('id');
    $table->string('name');
    $table->string('slug');
    $table->string('delete_me');
    $table->timestamps();
});
```
Run `php artisan migrate` and verify that the table was created successfully and has an auto-incrementing ID.

Drop the `delete_me` column from the table using a migration:

```
Schema::table('categories', function(Blueprint $table) {
    $table->dropColumn('delete_me');
});
```
Run `php artisan migrate` and verify that the `delete_me` column has been deleted, but the ID is no longer set to `AUTOINCREMENT`.

**Comment by miscbits** [comment]
I believe this might help a bit here. It seems that the process to drop a column in sqlite is not exactly correct in the Blueprint class.
 
http://www.sqlitetutorial.net/sqlite-alter-table/

Sqlite does not actually support drop column according to this link, so to do this, you must copy the table into a temp table, drop the original table, and recreate it with the ddl minus the column you no longer want. It would appear that the ddl isn't being copied with auto increment. 

I'm testing this now. I'm also testing it to see if I can reproduce it. I'm also going to see if it behaves the same way with other keywords

**Comment by miscbits** [comment]
hmmm. whenever I try to drop the column in sqlite, I get this error. 

```
  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'Doctrine\DBAL\Driver\PDOSqlite\Driver' not found
```

**Comment by voveson** [comment]
@miscbits per the docs (see link in my original comment), prior to dropping columns from an SQLite database, you must add `doctrine/dbal` to your `composer.json` dependencies.  The autoincrement issue I described happens in spite of including this dependency.

**Comment by miscbits** [comment]
BEFORE DROPPING
```
CREATE TABLE "topics" (
	"id" integer not null primary key autoincrement, 
	"drop_me" varchar not null, 
	"created_at" datetime not null, 
	"updated_at" datetime not null
)
```

AFTER DROPPING 
```
CREATE TABLE topics (
	id INTEGER NOT NULL, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY(id)
)
```

Ok so in an attempt to recreate the sql, doctrine is just setting id as the primary key which already autoincrements. It shouldn't cause any bugs in your project. it just removes a little redundancy, but both of these ddl's besides the drop_me column are the same.

**Comment by voveson** [comment]
The reason we noticed this issue is because the ID of a deleted entry was reused for the next entry. 
 In other words, after running a migration that calls `dropColumn`, if you delete the most recently inserted entry, then create a new entry, the new one gets the same ID as the deleted entry.  This is definitely undesirable behavior that can cause issues.  

I'm not sure if anything can be done, due to the limitations of SQLite, but if it can't be solved, it should probably be added to the documentation.

**Comment by miscbits** [comment]
Im not sure how you would solve it, but it is isn't an issue with Laravel. I disagree that it should be noted in Laravel's documentation even because it is something that doctrine could one day fix somehow and that would immediately make Laravel's documentation incorrect. 

If you don't want this behavior, then I would suggest just using mysql or postgres. sqlite is too trivial for even basic production implementation.

**Comment by voveson** [comment]
Thank you for taking the time to look into this.

With respect, it **is** an issue with Laravel's SQLite driver.  They have tried to support dropping columns which isn't natively supported by SQLite.  The Laravel docs note certain limitations of the SQLite driver, and this should be one of them.  Saying "it might get fixed and then the docs would be wrong" is backwards logic.  The docs are wrong **_now_**.  They indicate that `dropColumn` is supported by the SQLite driver, when in fact it is not entirely supported and results in undesirable and unexpected behavior.

Your suggestion to use something else has been noted, but that doesn't mean this shouldn't be addressed, whether it be with a fix or simply with improved documentation.

**Comment by miscbits** [comment]
Ok that is entirely fair. Feel free to open a PR on this. The file that would have to be changed I believe is SQLiteGrammar the `compileDropColumn()` method.

**Comment by lk77** [comment]
so it's more like a hack and should be noted on the docs, as a disclaimer ?

**Comment by srmklive** [comment]
I honestly don't think its an bug within the framework. Laravel itself utilizes `doctrine/dbal` for sqlite support. So its better that you post the issue there. Also, if you have a solution in mind, then you should open a PR for this.
