### ISSUE TITLE
decimal 10,2 on db, laravel returns incorrect values

### ISSUE THREAD

**Issue by slife80** [laravel/framework#20311]
- Laravel Version: 5.4.30
- PHP Version: 5.6.30
- Database Driver & Version: mysql 5.6.35

### Description:
Hello, I don't know what's happening, i need an help to understand.
I have a database (invoices) with some decimal(10,2) columns.
I've noticed an issue when i try to call them inside an if into the invoice model.

### Steps To Reproduce:

public function invoiceStatusGenerator()
        {
//$this->total value is 131.22 stored in decimal format and retrieved in string format (i don't know why)
//$this->paid value is 131.22 stored in decimal format and retrieved in string format (i don't know why)
            $array = [];
            if ($this->paid == 0) {
                $array['status'] = 'unpaid';
            }
            elseif ($this->paid < $this->total) {
                $array['status'] = 'partiallypaid';
            }
            elseif ($this->paid == $this->total) {
                $array['status'] = 'paid';
            }
            elseif ($this->paid > $this->total') {
                $array['status'] = 'overpaid';
//the statement enters here
                dd($this->total); <------ THE VALUE OF THE TOTAL COLUMN HERE IS 131.216 in decimal format
            }
            else {
                $array['status'] = 'draft';
            }
        }

if i write again with another dd at the end of the method happens another strange thing:
public function invoiceStatusGenerator()
        {
//$this->total value is 131.22 stored in decimal format and retrieved in string format (i don't know why)
//$this->paid value is 131.22 stored in decimal format and retrieved in string format (i don't know why)
            $array = [];
            if ($this->paid == 0) {
                $array['status'] = 'unpaid';
            }
            elseif ($this->paid < $this->total) {
                $array['status'] = 'partiallypaid';
            }
            elseif ($this->paid == $this->total) {
                $array['status'] = 'paid';
            }
            elseif ($this->paid > $this->total') {
                $array['status'] = 'overpaid';
                dd($this->total); 
//the statement doesn't enter here anymore so no dd is shown and the method goes on
            }
            else {
                $array['status'] = 'draft';
            }
            dd($this->total); <------ THE VALUE OF THE TOTAL COLUMN HERE IS 131.22 in string format and i can see this dd
        }
this thing is making me crazy. please let me know if there is an issue with the framework or something similar. i need just to work with decimal values, i don't know what else I need to try.
thank you

**Comment by miscbits** [comment]
Heya. This is an issue with Mysql most likely. If you just need to work with money, the best way I have found is to just store the money as an integer value and divide it by 100 when you call it from the db. this way you get nice integers in your database.

**Comment by rs-sliske** [comment]
https://laravel.com/docs/5.4/eloquent-mutators#attribute-casting

**Comment by Litiano** [comment]
# Do not compare float
read http://php.net/manual/pt_BR/language.types.float.php and use http://php.net/manual/pt_BR/ref.bc.php to compare.

**Comment by slife80** [comment]
solved....it was my fault, i was manipulating data before retrieving values.....i think it's time to better refactor my code :)
thanks to everyone
