### ISSUE TITLE
doctrine/inflector v1.2.0 requires PHP 7 but Laravel 5.4 requires PHP 5.6.4

### ISSUE THREAD

**Issue by geekcom** [laravel/framework#20328]
- Laravel Version: 5.4.30
- PHP Version: 5.6.26
- Database Driver & Version: 

### Description:
Error when trying to install laravel with PHP Version: 5.6.26

### Steps To Reproduce:
1. New installation of Laravel framework  with PHP 5.6.26, **laravel new app**
2. run **composer install**

**Comment by gmsantos** [comment]
Remove your composer.lock and try again. This will stop to happen when https://github.com/laravel/framework/issues/20227 is tagged.

Related: https://github.com/laravel/framework/issues/20214

**Comment by andrey-helldar** [comment]
Laravel 5.4.36 installed 1.3.0 version of `doctrine/inflector`.
`doctrine/inflector:1.2.*` requires PHP 7.0 or higher
`doctrine/inflector:1.1.*` requires PHP 5.3 or higher
