### ISSUE TITLE
No way to specify column to be referenced in belongsToMany

### ISSUE THREAD

**Issue by shalvah** [laravel/framework#20324]
- Laravel Version: 5.4.30
- PHP Version: 5.6.4
- Database Driver & Version: MySQL 5.6.35

### Description:
I have a `Room` model and table, and a `Watchlist` model and table with the following structure:

```
rooms
  id
  name
  spree_id

watchlists
  id
  name

room_watchlist
  spree_id
  watchlist_id
```

Also, I have:
```php
// in Watchlist model
 public function rooms()
    {
        return $this->belongsToMany(Room::class, 'room_watchlist',  'watchlist_id', 'spree_id');
    }

// in Room model
 public function watchlists()
    {
        return $this->belongsToMany(Watchlist::class, 'room_watchlist',  'spree_id', 'watchlist_id', 'spree_id');
    }
```

Whenever I try to access `$watchlist->rooms`, this is the SQL that gets executed: 
```sql
SELECT `rooms`.*, `room_watchlist`.`watchlist_id` as `pivot_watchlist_id`, `room_watchlist`.`spree_id` as `pivot_spree_id` 
FROM `rooms` 
INNER JOIN `room_watchlist` on `rooms`.`id` = `room_watchlist`.`spree_id` 
WHERE `room_watchlist`.`watchlist_id` = {$watchlistId}
```
No matter what I try, I have not been able to tell the framework that the corresponding key in the `rooms` table is the `spree_id`, not the `id`. I think I might be able to do this by using `hasManyThrough`, but I don't want to create a model for the pivot table. I think this is something that needs to be fixed. Or if there's something I'm missing, please do point me to it. Thanks.

**Comment by Dylan-DPC** [comment]
This is not a bug. Open an issue in the laravel/internals repo

**Comment by NtwariJoshua** [comment]
this is the method signature of the belongs to method
`public function belongsToMany($related, $table = null, $foreignKey = null, $otherKey = null, $relation = null)`

seems to be running ok.

**Comment by sausin** [comment]
Is that a typo in only your description or also in your code?
```
// in Watchlist model
 public function rooms()
    {
        return $this->belongsToMany(Room::class, 'hotel_watchlist',  'watchlist_id', 'spree_id');
    }
```

you have `hotel_watchlist` instead of `room_watchlist`

**Comment by shalvah** [comment]
Lol...typo. Was testing out something, forgot to change it. Thanks
