### ISSUE TITLE
Whoops, looks like something went wrong

### ISSUE THREAD

**Issue by tomchang11** [laravel/framework#20320]
- Laravel Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:

Hi, could someone help solve this problem. I have no experience with Laravel before. I recently bought this movies website from a guy and once I uploaded the tables and files to my shared hosting. It shows "Whoops, looks like something went wrong". I already repaired all my sql tables and tried some solutions on web but not lucky yet.

website : seriesonlinesubtituladas.com

**Comment by vinterskogen** [comment]
Typically Laravel put a record containing a full call stack (backtrace), that helps to understand the cause of the error to the end of `storage/logs/laravel.log` file. This log file can contain thousands of lines, so `tail` or `tailf` command can help you. Or you can move/rename it, then hit the request, that causes "Whoops" error, and then examine it's contents again (Laravel will recreate this file automatically).

Hope it helps.

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only.
