### ISSUE TITLE
updateOrCreate not working?

### ISSUE THREAD

**Issue by iamvitali** [laravel/framework#20347]
- Laravel Version: 5.4.28
- PHP Version: 7.0.20
- Database Driver & Version: 10.1.24-MariaDB

### Description:
`updateOrCreate()` for some reason doesn't do the trick for me ...
For some reason it only tries to create a row with the `email` column and ignores the rest (my strings & uuid)...

### Steps To Reproduce:
```
Schema::create('users', function (Blueprint $table) {
	$table->increments('id');
	$table->uuid('ms_ad_uuid')->unique();
	$table->string('display_name')->nullable();
	$table->string('email')->unique();

	$table->rememberToken();
	$table->timestamps();
});
```

```
$currentUser = User::updateOrCreate(
	[
		'ms_ad_uuid' => '2b22985a-af6d-4d21-9c3e-4c3682397b50',
	],
	[
		'display_name' => 'test name',
		'email' => 'test@email.com',
	]
);
```

Screenshot with the error:
![screen shot 2017-07-31 at 17 08 45-fullpage](https://user-images.githubusercontent.com/8069264/28787038-fcf5d912-7612-11e7-97d5-75ee274d0362.png)

**Comment by lk77** [comment]
it's not related with fillable or something ?

**Comment by stefanoruth** [comment]
Is it a clean model or have you done some customization to the model?

**Comment by iamvitali** [comment]
Oh yeah, good point!

It's the 

```
    protected $fillable = [
        'name', 'email', 'password',
    ];
```
that was there.
So I guess it's the customatisation to the model that I needed to make, i.e adding all the columns that I want to use to that array!

**Comment by Dylan-DPC** [comment]
@iamvitali if this is solved kindly close the issue :)
