### ISSUE TITLE
'Too many connections' Error thrown during testing with DatabaseTransactions trait.

### ISSUE THREAD

**Issue by twig1337** [laravel/framework#20341]
- Laravel Version: 5.4.23
- PHP Version: 7.0.19
- Database Driver & Version: MySql 5.6.36

### Description:
Error "PDOException: SQLSTATE[08004] [1040] Too many connections" is being thrown while running a PHPUnit test suite that uses the `DatabaseTransactions` trait with the `$connectionsToTransact` variable defined.

### Steps To Reproduce:
Create a PHPUnit test suite with the `DatabaseTransactions` trait that references multiple database connections within the `$connectionsToTransact` variable. Determine what your maximum connections variable is set to for your MySql instance then run enough tests to make sure you would exceed said number.

### Pull Request
https://github.com/laravel/framework/pull/20340

**Comment by themsaid** [comment]
Moving the discussion to the PR.
