### ISSUE TITLE
Cannot use "filters" as a fonction name in a model

### ISSUE THREAD

**Issue by sirber** [laravel/framework#20350]
- Laravel Version: 5.4
- PHP Version: 7.1

### Description:
Cannot use "filters" as a fonction name in a model

### Steps To Reproduce:
class Template extends Model
{
    public function filters() {
    	return $this->hasMany('App\Filter');
    }
}

class RapportsController extends Controller
{
public function edit(Template $rapport)
{
        dd($rapport->filters);
}
}

null

**Comment by sirber** [comment]
If I name the function "filter" or "filterz", it works and I get a collection.

**Comment by sisve** [comment]
Can you provide exact Laravel version and the complete Template model?

**Comment by sirber** [comment]
Laravel Framework 5.4.28

<?php
namespace App;
use Illuminate\Database\Eloquent\Model;

class Template extends Model
{
    //
    protected $fillable = ['name'];

    public function charts() {
    	return $this->hasMany('App\Chart');
    }

    public function filters() {
    	return $this->hasMany('App\Filter');
    }
}

<?php
namespace App;
use Illuminate\Database\Eloquent\Model;

class Filter extends Model
{
    //
    function template() {
    	return $this->belongTo("App\Template");
    }
}

**Comment by themsaid** [comment]
Can't replicate, you need to look into your code to identify what's going wrong.
