### ISSUE TITLE
POST method $request->all() always return empty [] array when sending base64 encoded Image JSON

### ISSUE THREAD

**Issue by michaeltansy** [laravel/framework#20356]
- Laravel Version: #.#.#
- PHP Version: 5.4
- Database Driver & Version: MySQL

### Description:
Hi, i have problem on my staging server in which the code works fine on my production server as well as local. the problem is when I try sending base64 encoded image to server, when it goes to the validation it always says that the parameter is empty. I tried to dd($request->all()) and resulting an empty array.

so here are my request and i also already add Content-Type: application/json to the header:
{
  "userID":79,
  "image": *base64 encode image (very long string)
}

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by sisve** [comment]
What Laravel version are you using? How long is "very long"? Is it more than max allowed post size configured in nginx and php.ini?

**Comment by themsaid** [comment]
Please continue on the forums.

**Comment by jackbaron** [comment]
@michaeltansy have you got a solution?

**Comment by RaminBgrn** [comment]
I had the same issus
I had both Accept application/json and Content-Type application/json in request header. Once I removed Content-Type, all is fixed.
