### ISSUE TITLE
Cant save model without fire event

### ISSUE THREAD

**Issue by rorc** [laravel/framework#20362]
- Laravel Version: 5.4.29

### Description:
In model:
```php
protected $events = [
    'saved' => Saved::class
];
```
In listener:
```php
if ($event->selection->phone == $event->source->phone) {
    $event->selection->phone = null;
}

if ($event->selection->date == $event->source->date) {
    $event->selection->date = null;
}

$event->selection->save();
```
This will call recursion...

**Comment by themsaid** [comment]
Of course it will, you're re firing the event from the listener. You shouldn't.

**Comment by rorc** [comment]
@themsaid How i can save model without fire event?

**Comment by devcircus** [comment]
If you want to use an event in this situation, you'll need to opt for a custom event, not an Eloquent event. The 'saved' event fires every time a model is saved. If that's not the behavior you want, create a custom event that is fired only when you need it.

**Comment by rs-sliske** [comment]
i was trying to do something similar in a project i was working on recently, and the solution i ended up with was to use the saving event rather than saved. that allows you to manipulate values whenever the object is saved, without having to call save again
