### ISSUE TITLE
PHPUnit assertion count is not right

### ISSUE THREAD

**Issue by DCzajkowski** [laravel/framework#20363]
- Laravel Version: 5.5-dev (most likely 5.4.* too)
- PHP Version: 7.1.4

### Description:
When you use Laravel's `$response->assertStatus()` for example, the assertion is not counted in, ie you may have ten assertions agains `TestResponse` and none of them will be counted in the final print of PHPUnit.

### Steps To Reproduce:
1. In your ExampleTest:
```php
$response = $this->get('/');
$response->assertStatus(200);
```
2. Run that file with `phpunit`
3. **visible:** `OK (1 test, 0 assertions)`, **expected:** `OK (1 test, 1 assertion)`

### What have I noticed
If in your test file (or Laravel's TestCase) you add this snippet:
```php
public function __destruct()
{
    dump(\PHPUnit\Framework\Assert::getCount()); // This will print 1 (as expected)
    dump(self::getCount()); // This will print 0
}
```

**Comment by themsaid** [comment]
Can't replicate, I get `OK (1 test, 1 assertion)`

**Comment by DCzajkowski** [comment]
Ok, new steps to reproduce:
```bash
laravel new test --dev
cd test
php -r "file_exists('.env') || copy('.env.example', '.env');"
php artisan key:generate
phpunit
```

It will return you:
```
OK (2 tests, 1 assertion)
```
whereas 2 assertions are by default.

---

When you change in `Illuminate\Foundation\Testing\TestResponse` 10th line from `use PHPUnit\Framework\Assert as PHPUnit;` to `use Illuminate\Foundation\Testing\TestCase as PHPUnit;` it will produce
```
OK (2 tests, 2 assertions)
```

**Comment by DCzajkowski** [comment]
It seems like only 5.5 is affected

**Comment by themsaid** [comment]
Still can't replicate, sorry :)

**Comment by DCzajkowski** [comment]
Really?

**Comment by DCzajkowski** [comment]
So you get `OK (2 tests, 2 assertions)` then?

**Comment by themsaid** [comment]
<img width="952" alt="screen shot 2017-08-01 at 3 34 54 pm" src="https://user-images.githubusercontent.com/4332182/28827796-f4c2723e-76ce-11e7-880d-6d1ab48fb2ca.png">

**Comment by DCzajkowski** [comment]
![](http://i.imgur.com/rFNiaK1.png)

**Comment by DCzajkowski** [comment]
Let me maybe create a repo with the bug. Weird...

**Comment by themsaid** [comment]
Notice the difference in your PHPUnit version, laravel 5.5 uses v6:

https://github.com/laravel/laravel/blob/develop/composer.json#L16

**Comment by DCzajkowski** [comment]
That solved that, thanks! I am surprised composer or something didn't shout at me, that `~6.0` is required. Oh well. Thank you again :)

**Comment by themsaid** [comment]
Welcome :)
