### ISSUE TITLE
Simple function names cause redeclare issues when using other code bases

### ISSUE THREAD

**Issue by Artistan** [laravel/framework#20370]
- Laravel Version: 5.4.30
- PHP Version: 7.1
- Database Driver & Version: N/A

### Description:
"Fatal error: Cannot redeclare" due to simple naming convention.
The

### Steps To Reproduce:
try to use a code base (like adminer.php) with function declarations that are defined in helpers.php
Illuminate/Foundation/helpers.php Causes a fatal error

Example of one of the collisions in adminer.php
https://github.com/vrana/adminer/pull/220#issuecomment-319259935
Example of using adminer.php with laravel: https://github.com/leung0826/adminer-for-laravel
Example of forced fix to prevent collisions: https://github.com/leung0826/adminer-for-laravel/blob/master/src/Console/UpdateCommand.php#L120

### Suggested Solutions future compatibility
- don't use functions... use classes, namespaced?
- deprecate the use of functions as helpers

### Suggested Solutions 1 (class)
- create a **lf** (laravel/framework) helpers class
- implements each of the helper functions as static functions in the lf helper class

#### lf helpers class
- `lf::abort()`
- `lf::abort_if()`
- `lf::abort_unless()`
- `lf::action()`
- `lf::app()`
- `lf::app_path()`
- `lf::asset()`
- `lf::auth()`
- `lf::back()`
- `lf::base_path()`
- `lf::bcrypt()`
- `lf::broadcast()`
- `lf::cache()`
- `lf::config()`
- `lf::config_path()`
- `lf::cookie()`
- `lf::csrf_field()`
- `lf::database_path()`
- `lf::decrypt()`
- `lf::dispatch()`
- `lf::elixir()`
- `lf::encrypt()`
- `lf::event()`
- `lf::factory()`
- `lf::info()`
- `lf::logger()`
- `lf::method_field()`
- `lf::mix()`
- `lf::old()`
- `lf::policy()`
- `lf::path()`
- `lf::public_path()`
- `lf::redirect()`
- `lf::request()`
- `lf::resolve()`
- `lf::resource_path()`
- `lf::response()`
- `lf::route()`
- `lf::secure_asset()`
- `lf::secure_url()`
- `lf::session()`
- `lf::storage_path()`
- `lf::trans()`
- `lf::trans_choice()`
- `lf::__()`
- `lf::url()`
- `lf::validator()`
- `lf::view()`

### Suggested Solutions 2 (namespace)
- namespace the helpers functions **lf**
- implements each of the helper functions as static functions in the lf helper class

#### lf helper functions in namespace
- `lf\abort()`
- `lf\abort_if()`
- `lf\abort_unless()`
- `lf\action()`
- `lf\app()`
- `lf\app_path()`
- `lf\asset()`
- `lf\auth()`
- `lf\back()`
- `lf\base_path()`
- `lf\bcrypt()`
- `lf\broadcast()`
- `lf\cache()`
- `lf\config()`
- `lf\config_path()`
- `lf\cookie()`
- `lf\csrf_field()`
- `lf\database_path()`
- `lf\decrypt()`
- `lf\dispatch()`
- `lf\elixir()`
- `lf\encrypt()`
- `lf\event()`
- `lf\factory()`
- `lf\info()`
- `lf\logger()`
- `lf\method_field()`
- `lf\mix()`
- `lf\old()`
- `lf\policy()`
- `lf\path()`
- `lf\public_path()`
- `lf\redirect()`
- `lf\request()`
- `lf\resolve()`
- `lf\resource_path()`
- `lf\response()`
- `lf\route()`
- `lf\secure_asset()`
- `lf\secure_url()`
- `lf\session()`
- `lf\storage_path()`
- `lf\trans()`
- `lf\trans_choice()`
- `lf\__()`
- `lf\url()`
- `lf\validator()`
- `lf\view()`

**Comment by themsaid** [comment]
Yes these functions are reserved for Laravel.

**Comment by kenorb** [comment]
Same here. The `url()` in `helpers.php` conflicts with Drupal's [`url()`](https://api.drupal.org/url).

```
$ drush composer-manager show
Drush command terminated abnormally due to an unrecoverable error.                                                                                             [error]
Error: Cannot redeclare url() (previously declared in
docroot/sites/all/libraries/composer/illuminate/support/Illuminate/Support/helpers.php:1001) in
docroot/includes/common.inc, line 2343

Fatal error: Cannot redeclare url() (previously declared in docroot/sites/all/libraries/composer/illuminate/support/Illuminate/Support/helpers.php:1001) in docroot/includes/common.inc on line 2343

Call Stack:
    0.0027     358456   1. {main}() /usr/local/bin/drush8:0
    0.0202    1030872   2. require('phar:///usr/local/bin/drush8/drush') /usr/local/bin/drush8:10
    0.0207    1081736   3. drush_startup($argv = array (0 => '/usr/local/bin/drush8', 1 => 'composer-manager', 2 => 'show')) phar:///usr/local/bin/drush8/drush:114
    0.0212    1082424   4. drush_run_main($DEBUG = FALSE, $sep = '/', $msg = 'Phar detected. Proceeding to drush_main().') phar:///usr/local/bin/drush8/includes/startup.inc:365
    0.0220    1227504   5. drush_main() phar:///usr/local/bin/drush8/includes/startup.inc:458
    0.5745   10914032   6. Drush\Boot\DrupalBoot7->bootstrap_and_dispatch() phar:///usr/local/bin/drush8/includes/preflight.inc:66
    0.8631   11377048   7. drush_bootstrap_to_phase($max_phase_index = 5) phar:///usr/local/bin/drush8/lib/Drush/Boot/BaseBoot.php:53
    0.9874   10251728   8. drush_bootstrap($phase = 5, $phase_max = 5) phar:///usr/local/bin/drush8/includes/bootstrap.inc:473
    0.9877   10252560   9. Drush\Boot\DrupalBoot7->bootstrap_drupal_full() phar:///usr/local/bin/drush8/includes/bootstrap.inc:354
    0.9877   10269152  10. drupal_bootstrap($phase = 7, $new_phase = ???) phar:///usr/local/bin/drush8/lib/Drush/Boot/DrupalBoot7.php:91
```

I'm using `Underscore` ([`radic/tmp-underscore-php`](https://packagist.org/packages/radic/tmp-underscore-php)) library which depends on `illuminate/support`, once upgraded, everything started to crash.

**Comment by kenorb** [comment]
Follow-up: laravel/internals/issues/709
