### ISSUE TITLE
Eloquent Toutches recursive

### ISSUE THREAD

**Issue by warrio4** [laravel/framework#20377]
- Laravel Version: 5.4
- PHP Version: 7.1.1
- Database Driver & Version: MySql 10.2.3

**Question**: how to touch a model from the same model?

**Details:**
I'm building an application for renting books between people.
In each transaction there are 2 parts: information concerning the owner VS information concerning the person who is renting the book.

Because the the 2 sides, I chose to use only one table named `rents` for both sides. To distinguish which is which I added a field `rent_side` that contains 'owner' or 'borrower'.
This makes it easy if I want to show/search a history of a person. If had 2 ore more tables, I would have to make a UNION to select all the data needed to show the history.

These two sides are coupled together thanks to common id called `couple_id`.

From each side, I can see the opposed side thanks to method located in the model `App\Rent` I named `reverse`, where I do the following:

    class Rent extends Model {
        protected $touches = ['reverse'];
        
        public function reverse()
        {
            return $this->hasOne('App\Rent', 'couple_id', 'couple_id')
                ->where('id', '!=', $this->id);
        }
    }

    

**Problem** this touching affects the same model. So when I update/insert a record, the request takes up to 4min before sending an error. As if it went into an endless loop.

Is there a way to touch a model from the same model?

Manually updating the timestamps of the reversed side didn't help since I'm using the [Plastic package](https://github.com/sleimanx2/plastic). It works great with touches.

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by warrio4** [comment]
I thought that this case was a bug. Since Eloquent doesn't consider a model that touches itself.

**Comment by themsaid** [comment]
> And an infinite loop is a bug

In this case it isn't a bug, you explicitly say whenever I update the Rent, update the Rent.
