### ISSUE TITLE
Different formats for table names between creating tables & establishing relationships

### ISSUE THREAD

**Issue by regal2157** [laravel/framework#20380]
- Laravel Version: 5.4, 5.*
- PHP Version: 5/7
- Database Driver & Version:

### Description:
Different behavior when grabbing the names of relationship tables.
Migration will create the plural version (UserRole => user_roles)
Eloquent->belongsToMany will grab singular version (user_role).

The fix would result in a breaking change, modifying Database/Eloquent/Concerns/HasRelationships.php@joiningTables to grab plural by default.

### Steps To Reproduce:
New laravel install, create a model & migration with:
```
php artisan make:model UserRole -m
```
Populate / Run migration

Then create the "belongsToMany" relationships via User/Role models.
```
class User extends Eloquent {
	public function roles()
    {
    	return $this->belongsToMany('App\Role');
    }
}
```

This will error on default when the method is called since belongsToMany will look for by default for table user_role and not user_roles (which was made by the migration command).

**Comment by Dylan-DPC** [comment]
Yes i see the cause. The Make Command doesn't know whether its a pivot or not and follows standard laravel conventions.

**Comment by srmklive** [comment]
To me this is not an error. The stub will simply generate a migration with an auto-generated table name. It's up to you to update the migration or model accordingly.

**Comment by themsaid** [comment]
yeah you need to provide the table name explicitly in such case.
