### ISSUE TITLE
doctrine/inflector ~1.1.0 -> no matching package found.

### ISSUE THREAD

**Issue by jubairsaidi** [laravel/framework#20381]
- Laravel Version: 5.4.x-dev
- PHP Version: 7.1.2
- Database Driver & Version: pgsql 9.6.2 

### Description:
On `composer update` (and on deletion of `composer.lock` and running `composer install`) we get the following:
```


  [Composer\DependencyResolver\SolverProblemsException]
    Problem 1
      - Installation request for laravel/framework 5.4.* -> satisfiable by laravel/framework[5.4.x-dev].
      - laravel/framework 5.4.x-dev requires doctrine/inflector ~1.1.0 -> no matching package found.
    Problem 2
      - laravel/framework 5.4.x-dev requires doctrine/inflector ~1.1.0 -> no matching package found.
      - laravel/tinker 1.0.x-dev requires illuminate/console ~5.1 -> satisfiable by laravel/framework[5.4.x-dev].
      - Installation request for laravel/tinker ~1.0 -> satisfiable by laravel/tinker[1.0.x-dev].
  Potential causes:
   - A typo in the package name
   - The package is not available in a stable-enough version according to your minimum-stability setting
     see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
  Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

### Steps To Reproduce:
1. run `composer update` 
2. or run `composer install` after deleting `composer.lock`

**Comment by Dylan-DPC** [comment]
This is not a bug. Why are using 5.4-dev when there is a stable version? Use the forums or slack channel to get your issue solved

**Comment by Dylan-DPC** [comment]
Do check #20328 and #20255

**Comment by lk77** [comment]
the dev version is working properly
on php 7.1.7 i can install :
`doctrine/inflector                    1.1.x-dev 90b2128`

**Comment by jubairsaidi** [comment]
have a few packages that need the the min stability set to dev, adding `@stable` to laravel seems to have fixed that issue
```
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize
PHP Fatal error:  Trait 'Illuminate\Database\Concerns\BuildsQueries' not found in /path/to/project/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php on line 22
PHP Stack trace:
```
Deleting `vendor/laravel` and re-running `composer update` fixed that though.

**Comment by Dylan-DPC** [comment]
You should try and avoid changing your minimum stability. If you change it to dev it will pull unstable versions of every dependency which can cause issues.
