### ISSUE TITLE
[Feature] Add custom storage:link path (optional parameter) ?

### ISSUE THREAD

**Issue by fsasvari** [laravel/framework#20383]
Is there any way to create custom storage:link path ?

Now, when we run `storage:link` in terminal, it links "public/storage" with "storage/app/public". Is there any way to create optional parameter in `storage:link` artisan command like `storage:link {path=storage}`.

Code:
https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Console/StorageLinkCommand.php

**Comment by Dylan-DPC** [comment]
This is not a bug. Open an issue in the laravel/internals repo

**Comment by fsasvari** [comment]
Sorry and thank you
