### ISSUE TITLE
Eloquent has and doesntHave functions ignore related connection

### ISSUE THREAD

**Issue by rtroost** [laravel/framework#20387]
- Laravel Version: 5.4.30
- PHP Version: 7.1
- Database Driver & Version: MariaDB

### Description:
I noticed this bug when trying to call the `has` and `doesntHave` functions on a model. These two functions don't seem to incorporate the connection that the relationship that is being called, has.

### Steps To Reproduce:
What I tried to do is this:
I have an Employee model and an Account model. The Employee model `belongsTo` the Account model. These two models have different connections because account's are stored in the general database and employees are stored per client database. 

Next, I try to retrieve all employees that don't have an account:
`Employee::doesntHave('account')->get()`

This results in a query being generated that uses the same connection the Employee model has, for the account relationship. It uses the wrong prefix, the wrong database credentials and doesn't include any database name in the query. This seems to mostly be an issue that is caused by the way the query is generated because the query `Builder` does include the right connections in its components.

I've currently worked around this issue by modifying the generated query by using `str_replace` to explicitly define the correct database.

Also: Eager loading the account relationship on Employee does work without any problems.

**Comment by themsaid** [comment]
Yes it won't work since has generates a single query that has to run on a single question, it won't work if you have multiple connections like this.
