### ISSUE TITLE
Throw an error if a model's $primaryKey is an array

### ISSUE THREAD

**Issue by andrechalom** [laravel/framework#20393]
- Laravel Version: 5.4

### Description:
There are lots of closed issues regarding the use of composite primary keys, and all of them have been closed by the dev team. However, the documentation does not clearly mention that composite keys are not supported, and even has an example for generating a migration with a composite primary key. 

I understand the reason why this feature will not be implemented, but can you provide a check to provide the application developers with a clear error when they try to implement a composite primary? As it stands, when I tried to use a composite key in one of my models everything started to fail with an "illegal offset type" error, which is not helpful at all.

**Comment by Dylan-DPC** [comment]
This is not a bug. Open an issue in the laravel/internals repo

**Comment by andrechalom** [comment]
Migrated to https://github.com/laravel/internals/issues/712
