### ISSUE TITLE
TokenMismatchException should extends HttpException

### ISSUE THREAD

**Issue by kamui545** [laravel/framework#20409]
Hi everyone,

The `TokenMismatchException` has been bothering me for a long time now...

Is there any reason that this exception extends `\Exception` instead of `\Symfony\Component\HttpKernel\Exception\HttpException` ?

If we **extends** the `HttpException` from Symfony, we should be able to benefits from the custom error pages thanks to the `\Illuminate\Foundation\Exceptions\Handler::renderHttpException()` method, instead of having to catch it in `\App\Exceptions\Handler::render()` which feel more of a hack.

I'm not sure if my description is clear enough...

**To make it simple:**

`abort(500)` does not have the same behavior as `throw new TokenMismatchException()`.

`abort(500)` renders my custom 500 page, the later **not**.

**Comment by themsaid** [comment]
I'd say because `TokenMismatchException` is special, you need to handle it in your own way.

**Comment by kamui545** [comment]
I totally agree with you on this.

However, I think it would be a better "default" behavior and would be more consistent.

I don't really see any drawback to implement this?
It should not be really a breaking change and we could change this for the 5.5 release.

**Comment by laurencei** [comment]
Already done for 5.5:

https://github.com/laravel/framework/pull/18728

**Comment by kamui545** [comment]
Oh that's weird, I'm currently using 5.5 and this did not work until I created my own `419.blade.php`, I must have break something as it works on a fresh install!

Thank you 👍
