### ISSUE TITLE
Named route inconsistency

### ISSUE THREAD

**Issue by adifaidz** [laravel/framework#20417]
- Laravel Version: 5.4.30
- PHP Version: 7.1.1

### Description:

Named routes not recognized when named fluently  in provider. I placed my provider after the route provider and it was still not working. Only after changing fluent calls to the old way (using 'as') of setting names to routes that I got it working.

### Steps To Reproduce:

- Create new project
- Add named route 'home' :
```php
Route::get('/', function () {
    return view('welcome');
})->name('home');
```
- Create and register provider
- Add to boot method :

```php
    public function boot()
    {
        route('home');
    }
```
- Run artisan command  e.g : `artisan route:list` 
- Error : `Route [home] not defined.`
- Change 'home' route to:

```php
Route::get('/', [
  'uses' => 'Auth\LoginController@index',
  'as' => 'home'
]);
```

- Retry artisan command, no problem.

**Comment by themsaid** [comment]
The `RouteServiceProvider` is booted after the rest of providers, it's the last one in order, so you can't really interact with routes in any of your service providers since they won't be loaded yet.

**Comment by adifaidz** [comment]
I already put my serviceprovider after the `RouteServiceProvider`, plus that doesn't explain why when I call using `route('home')` it works when I registered using

```php
Route::get('/', [
  'uses' => 'Auth\LoginController@index',
  'as' => 'home'
]);
```

and not when I'm using

```php
Route::get('/', function () {
    return view('welcome');
})->name('home');
```
