### ISSUE TITLE
GateAbility wont get registered with facade

### ISSUE THREAD

**Issue by TheNuclearCat** [laravel/framework#20415]
- Laravel Version: 5.4.28
- PHP Version: 7.1
- Database Driver & Version: MySQL

### Description:
When using the Gate Facade gates are not working because the define method in Illuminate\Contracts\Auth\Access\Gate
never gets called.
If I resolve the class its working, see the workaround below.

### Steps To Reproduce:
Add to the AuthServiceProvider.php boot() method following code:
` Gate::define('isAdmin', function ($user) {
            return $user->is_admin;
        });`

Call in a controller $this->authorize('isAdmin');

(In this example is_admin is true, but it can be a simple boolean, because the method gets anyway never called)

### My Workaround:
` 
$gate = resolve('Illuminate\Contracts\Auth\Access\Gate');

        $gate->define('isAdmin', function ($user) {
            return $user->is_admin;
        });`

**Comment by UncertaintyP** [comment]
So I've tested this with Laravel v5.4.30 and PHP 7.0.7.

The error was not reproducible. The Gate facade and authorization working as expected.

**Comment by TheNuclearCat** [comment]
I´ve checked the user in gate.php with a dd and its resolved propely. 
Like I said the Abilitys array is empty for me because it never gets registered.

**Comment by themsaid** [comment]
I can't replicate your issue, everything seems to be working fine for me.
