### ISSUE TITLE
Scope function cannot be used in a sub-query: BadMethodCallException

### ISSUE THREAD

**Issue by danielefavi** [laravel/framework#20420]
- Laravel Version: 5.4.28
- PHP Version: 5.6.30
- Database Driver & Version: libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: 76b08b24596e12d4553bd41fc93cccd5bac2fe7a $ 

### Description:
When I try to use a scope function in a subquery I get the error **BadMethodCallException**
This issue is not a big deal (low priority); but it could be helpful to use a scope function in subqueries.

### Steps To Reproduce:
Here a simple example. Write this two functions in a model:
```
public static function mainQuery()
{
    return User::where(function($query) {
        $query->myScopeSubquery();
    })->get();
}

public function scopeMyScopeSubquery($query)
{
    return $query;
}
```
And then call the function 

```
MyModel::mainQuery();
```

You will get the error

**(1/1) BadMethodCallException**

**Call to undefined method Illuminate\Database\Query\Builder::myScopeSubquery()**

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
