### ISSUE TITLE
PHP ARTISAN Tinker triggers PHP Fatal error: Allowed memory size is exhausted.

### ISSUE THREAD

**Issue by jemmy-i-teck-global-net** [laravel/framework#20428]
- Laravel Version: 5.4.32
- PHP Version: 5.6.31 CLI
- Database Driver & Version: 10.1.25-MariaDB mariadb.org binary distribution

### Description:
Initiate a model get, for example, App\Models\OrderInfo::get() will trigger the following:
>>> App\Models\OrderInfo::get();
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 47 bytes) in D:\xampp\htdocs\test-project
\vendor\laravel\framework\src\Illuminate\Database\Connection.php on line 325

### Steps To Reproduce:
1. Create an empty project 
2. add database model 'e-commerce' files into app\Models directory
2.5 Generated app\Models\OrderInfo.php Model class 
3. add table OrderInfo and populate 46000 records
4. verify PHP.ini memory_limit = 256M
5. enter 'php artisan tinker'
6. call "App\Models\OrderInfo::get()
7. PHP Fatal Error of Allowed memory size is exhausted.

### My Workaround:
1. Exit Tinker
2. Adjust PHP.ini memory_limit = -1
3. Re-do Steps
4. Records are shown to be okay.

Is adjusting memory_limit to -1 a feasible thing to do on PRODUCTION?

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this github area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I please suggestion closing your issue ticket here. Instead trying asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.

**Comment by jemmy-i-teck-global-net** [comment]
Got it, first time to join, sorry about that.

**Comment by laurencei** [comment]
no dramas - happy to help point you in the right direction 👍
