### ISSUE TITLE
Migration rollback silently fails if migration file is missing

### ISSUE THREAD

**Issue by PantherDD** [laravel/framework#20436]
- Laravel Version: `Laravel Framework 5.4.32`
- PHP Version: `PHP 7.1.3-3+deb.sury.org~xenial+1 (cli) (built: Mar 25 2017 14:00:03) ( NTS )`
- Database Driver & Version: `mysqlnd 5.0.12-dev - 20150407 - $Id: b396954eeb2d1d9ed7902b8bae237b287f21ad9e $`

### Description:

I ran into an issue after upgrading `laravel/framework` from `v5.4.27` to `v5.4.32`, and it is probably caused by #19922 ([merged into `v5.4.29`](https://github.com/laravel/framework/blob/5.4/CHANGELOG-5.4.md#v5429-2017-07-19)).

Until now, if I tried to run `php artisan migrate:rollback`, and a migration file was missing (because I changed my Git branch for example), I got a nice error message telling me that rollback was impossible because of this.

Now, what happens instead is that:
- the untouched migrations of the batch are rolled back, but
- migrations with missing files are not, and
- I get no error at all.

Everything looks fine from the output, but some migrations silently fail to run. And further migration rollbacks become impossible at this point, because the highest numbered batch is still in the database, and it never gets rolled back; you get stuck, without an explanation.

We should, at the very least, report the skipped migrations (in red?) to the user at the end of the command. Even better would be to also add a flag for users to enable this skipping behavior (disabled by default).

### Steps To Reproduce:

1. Create a few migrations and run `php artisan migrate` 🡺 `batch #1`.
2. Create a few more migrations and run `php artisan migrate` 🡺 `batch #2`.
3. Delete one of the migration files that were used in `batch #2`.
4. `php artisan migrate:rollback` 🡺 No error, even though the migration whose file was deleted:
    - wasn't rolled back, and
    - its entry is still in the `migrations` table.
5. To see that you're stuck at this point, run `php artisan migrate:rollback` again a number of times.

**Comment by srmklive** [comment]
I think skipping over the migration is the best option.

**Comment by PantherDD** [comment]
This, in its current form, is pretty much "error hiding" (or "exception swallowing"); an anti-pattern.
https://en.wikipedia.org/wiki/Error_hiding

If I issue a command to roll back the last batch, that last batch contained 3 migrations, and one of them isn't be rolled back, then the command has failed. First, I need to be told that it failed; second, I need to be told "why". It's like ordering a 3-course meal at a restaurant and then (silently) not getting the main course. Not a good experience.

**Comment by srmklive** [comment]
@PantherDD I would suggest you review the `migrate:rollback` code. No error hiding is done. Laravel compiles list of files which are available and runs operations on them. This is a relevant approach in my opinion.

Your notion regarding it being anti-pattern is a whole other discussion.

**Comment by PantherDD** [comment]
I don't think it really makes a difference how the code does this internally: whether it tries to just do it and then swallows the potential exception, or it checks before doing and voluntarily skips over the part that would fail.
What matters is that it can't fulfill the user's request 100%, but hides the fact from them that some of the requested work hasn't been done.
