### ISSUE TITLE
[5.4] TestResponse::assertJsonMissing() not working for nested keys

### ISSUE THREAD

**Issue by behzadsh** [laravel/framework#20431]
- Laravel Version: 5.4.28
- PHP Version: 7.1.5

### Description:
Let's say we have an API that would return a json like this:
```json
{
    "foo": "bar",
    "baz": {
        "qux": "quux",
        "corge": "uier"
    }
}
```
and we want to test that `corge` inside `baz` object is missing

```php
<?php

class ExampleTest extends TestCase
{

    public function testJsonMissing()
    {
        $response = $this->json('GET', "/api/foobar");
        $response->assertJsonMissing(['foo'])                // this is ok and will be failed
                 ->assertJsonMissing(['baz' => ['corge']]);  // this should fail but will pass
    }

}
```

The test should fail but it will pass!

**Comment by behzadsh** [comment]
Ok I found that `assertJsonMissing` is opposite of `assertJsonFragment`. Laravel has very poor documentation on testing section.

I will add an assertion function that do opposite of `assertJsonStructure` in a PR.

**Comment by markwalet** [comment]
Why is this issue closed? I am still having the same issue. Why isn't there an opposite of just `assertJson`?

This is very poorly named..

**Comment by behzadsh** [comment]
@markwalet take a look at PR #20435. unfortunately PR is also closed by owner, but you can use code as macro in your code

**Comment by pedzed** [comment]
Apparently not many people use this function.

_...and for a good reason. It doesn't do what you expect._

**Comment by pedrosancao** [comment]
Came across this issue and made a workaround using PHPUnit assertion:

```php
<?php
class ExampleTest extends TestCase
{
    public function testJsonMissing()
    {
        // get response as array
        $data = $this->get('/api/foobar')->json();
        // use PHPUnit assertion
        $this->assertArrayNotHasKey('foo', $data);
        // ensure key exists before check nested key
        $this->assertArrayHasKey('baz', $data);
        $this->assertArrayNotHasKey('corge', $data['baz']);
    }
}
```

**Comment by markwalet** [comment]
I still think the naming of those assert methods could be improved.

**Comment by osbre** [comment]
Alternative at the moment:

`missing()` method from AssertableJson
```php
public function test_fluent_json()
{
    $response = $this->json('GET', '/users/1');

    $response
        ->assertJson(fn (AssertableJson $json) =>
            $json->where('id', 1)
                 ->where('name', 'Victoria Faith')
                 ->missing('password')
                 ->etc()
        );
}
```

https://laravel.com/docs/8.x/http-tests#fluent-json-testing

**Comment by MaryRabinovich** [comment]
The same issue in 2022:

$response
->assertJson(['data' => [ ThingWithRelations::first()->toArray() ])
->assertJsonMissing(['data' => [ ThingWithRelations::first()->toArray() ]);

it passes:)
And yeah, the thingWithRelations is the same in both lines.

So, maybe really it's just a problem of naming.

Rename it, please, to something like assertJsonMissingPlaneFragment()
