### ISSUE TITLE
Array to string conversion error in some custom messages when extending FormRequest

### ISSUE THREAD

**Issue by Aridez** [laravel/framework#20449]
- Laravel Version: 5.4.31
- PHP Version:      PHP 7.0.15 (cli) (built: Jan 17 2017 13:57:33) ( NTS )
                             Copyright (c) 1997-2017 The PHP Group
                             Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies

- Database Driver & Version: -

### Description:

When creating custom messages as objects in order to get a specific JSON object response, some of them return an ```ErrorException: Array to string conversion``` while others allow this kind of message.

### Steps To Reproduce:

Using the following bits of code to test:

```php
class CustomRequest extends FormRequest {

    public function rules()
    {
        return [
        'email' => 'required|email|unique:users,email',
    ...
        ];
    }

    public function messages()
    {
        return [
            'email.unique' => ['error' => 'message', 'code' => '409'],
            'email.email' => ['error' => 'message', 'code' => '400'],
            ...
        ];
    }

    public function response(array $errors) {
            return Response::create($errors, 400);
    }
...
}
```

- When triggering the 'email.unique' rule the expected JSON object is returned correctly
- When triggering the 'email.email' rule the following error shows up:

>ErrorExceptionArray to string conversion
--
in MessageBag.php (line 246)
>
>at HandleExceptions->handleError(8, 'Array to string conversion', 'I:\\API\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\MessageBag.php', 246, array('message' => array('error' => 'message'), 'format' => ':message', 'messageKey' => 'email'))
>
>at str_replace(array(':message', ':key'), array(array('error' => 'message'), 'email'), ':message')in MessageBag.php (line 246)

**Comment by Aridez** [comment]
Seems like in the file *vendor\laravel\framework\src\Illuminate\Support\MessageBag.php*, the following  function crashed because the message is an array.

```php
    protected function transform($messages, $format, $messageKey)
    { 
        return collect((array) $messages)
            ->map(function ($message) use ($format, $messageKey) {
                // We will simply spin through the given messages and transform each one
                // replacing the :message place holder with the real message allowing
                // the messages to be easily formatted to each developer's desires.
                return str_replace([':message', ':key'], [$message, $messageKey], $format);
            })->all();
    }
```

It could be solved to take into account the cases where it received an array adding ```if (is_array($message)) $message = json_encode($message);```:

```php
    protected function transform($messages, $format, $messageKey)
    { 
        return collect((array) $messages)
            ->map(function ($message) use ($format, $messageKey) {
                if (is_array($message)) $message = json_encode($message);
                // We will simply spin through the given messages and transform each one
                // replacing the :message place holder with the real message allowing
                // the messages to be easily formatted to each developer's desires.
                return str_replace([':message', ':key'], [$message, $messageKey], $format);
            })->all();
    }
```

**Comment by themsaid** [comment]
I don't think that's the correct use case, custom validation messages are used to describe why a certain field in your request body won't pass validation, you can't use it as a response to your request.

**Comment by Aridez** [comment]
Continuing with this discussion, I believe that attaching a code to the message can be useful in the case of APIs. An "email" validation error seems that should return a 400 error code, but a 409 error code suits more the "unique user" error. This error is then passed to the ```response``` function, so it seemed natural to create a more complex message object there, but if that's not the correct use case: 

How would be the best way to return a different error code depending on the validation triggered?

**Comment by themsaid** [comment]
A single request can trigger multiple validation errors for different input fields.

**Comment by Aridez** [comment]
Thank you for your answers.

I am aware that multiple errors are returned. Right now I want to add an error code to each error to identify it more easily in the front end, the ```messages()``` function looks like:

```php
    public function messages()
    {
        return [
            'username.required' => $this->AttributeMissing(),
            'email.required' => $this->AttributeMissing(),
            'email.email' => $this->AttributeNotWellFormed(),
            'password.required'  => $this->AttributeMissing(),
            'username.unique'  => $this->AttributeNotUnique(),
            'email.unique' => $this->AttributeNotUnique(),
        ];
    }
```
And the errors are packed all packed in an array that outputs:

```json
{"errors":[
	{"status":"409",
	"code":"not_unique",
	"message":"This username is already taken"},
	{"status":"409",
	"code":"not_unique",
	"message":"This email is already taken"}
	]
}
```
This is to provide a more standardized error structure (following http://jsonapi.org/format/#errors) since some endpoints of the API will be available to third parties, but I don't want a solution that enters in conflict with Laravel itself.

Any suggestions would be appreciated!

**Comment by whiterook6** [comment]
I am getting the same error. Our use case for printing errors is for logging what failed validation. In some cases we use some conditional logic so these rules aren't always present. Why not allow a way to flatten the message bag somehow?
