### ISSUE TITLE
[5.3] Creating an Auto Incrementing Unsigned TINYINT through migrations

### ISSUE THREAD

**Issue by hari03** [laravel/framework#20459]
- Laravel Version: 5.3.31
- PHP Version: 5.6.25
- Database Driver & Version: MySQL 5.7.14

### Description:
I have a few tables where I need `tinyint` fields which have to be `unsigned` and set to `auto_increment`.

The [L5.3 Database : Migrations documentation][1] **does not** have a method to define `unsigned auto-incrementing tinyint`.

I have tried to implement it using the `DB::update()`. My migration file for the table looks like:

    public function up()
    {
        Schema::create('table_name', function (Blueprint $table) 
        {
            $table->unsignedTinyInteger('field1');
            $table->string('field2', 255);
            $table->primary('field1');
            $table->index('field2');

            $field = "field1";
        });

        $this->addAutoIncrements($field);    
        
    }

    public function addAutoIncrements($field)
    {
        DB::update('ALTER TABLE table_name MODIFY $field TINYINT UNSIGNED NOT NULL AUTO_INCREMENT');
    }

When I try `php artisan migrate` with such a migration file, it migrates *without* any errors but **is not assigning** `auto-increment`.

How do I resolved this? Should I do the update as a complete new migration? Has anyone done it before?

  [1]: https://laravel.com/docs/5.3/migrations

### Steps To Reproduce:
1. Install laravel version 5.3.31.
2. Setup MySql and include the DB into your laravel project.
3. Create the migration table using php artisan.
4. Create a new migration to create a table with any table name.
5. Copy Paste the above code inside `up()` function of migration class file.
6. Run migrations and check your db table's property to see the column not set to `auto-increment`.

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only.

**Comment by hari03** [comment]
@themsaid Correct me if I'm wrong, isn't this a bug since all other types of `int` data-type **have a method** to declare but `unsigned tinyint` doesn't?

**Comment by hari03** [comment]
Just in case, someone lands here in future, I found a way to include `auto-increment` by writing : 

`$table->unsignedTinyInteger('field1', true);`

Setting the second parameter to true makes the field `primary` and `auto-increment`.
