### ISSUE TITLE
Separate $dateFormat per attribute for toJSON()

### ISSUE THREAD

**Issue by stevendesu** [laravel/framework#20450]
- Laravel Version: 5.4.0
- PHP Version: 7.0
- Database Driver & Version: MySQL 5.7

### Description:
I have a model which contains both `date`s and `datetime`s in the database. I access this model primarily through a REST API, using VueJS on the front-end. Therefore it's extremely convenient to, in my controller, simply return the model like so:

```php
public function show($id)
{
    return Model::find($id);
}
```

The issue I run into is that the returned JSON looks something like this:

```json
{"id": 123, "datetime_field": "2017-08-06 01:23:45", "date_field": "2017-08-06 00:00:00"}
```

I then try to use this in VueJS like so:

```html
<input type="date" name="date_field" v-model="date_field" />
```

But the field doesn't get filled in. This is because VueJS expects a string of the form "Y-m-d" for date fields, and expects "Y-m-d H:i:s" for datetime fields.

I cannot use Laravel's `protected $dateFormat` property to fix this, as it similarly breaks the `datetime_field`

### Feature Recommendation:
Extend the `$dateFormat` to allow a map from attribute to format. For instance:

```php
protected $dateFormat = [
    "datetime_field" => "Y-m-d H:i:s",
    "date_field" => "Y-m-d"
];
```

**Comment by stevendesu** [comment]
Looking through the Eloquent code briefly, it looks like this would require extending the `getDateFormat()` method to take a parameter (the field for which we want the format), then any calls to `getDateFormat()` would need to be updated to pass this parameter.

**Comment by Douglasdc3** [comment]
@stevendesu answer would be the best way to incorporate this into the framework. A workaround for your current issue would be adding the following code to your model

    public function getDateFieldAttribute()
    {
        return (new Carbon($this->attributes['date_field']))->format('Y-m-d');
    }

or even using some of the native php string functions. Make sure you also check for `null` values if your field is nullable.

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.

**Comment by stevendesu** [comment]
@Douglasdc3 Using an accessor to cast to a string actually doesn't fully solve my issue, as it hides the underlying Carbon entity. So then I'm unable to perform any logic in my controllers:

```php
public function doSomething($model)
{
    if ($model->date_field->isToday())
    {
        // do stuff...
    }
}
```

This will throw an error because "string" has no method "isToday".

Of course this can be further worked around by using `Carbon::parse()` literally everywhere I want to perform logic on the field, but that just feels... gross.

**Comment by stevendesu** [comment]
For reference, the new issue opened in `laravel/internals`: https://github.com/laravel/internals/issues/719

**Comment by themsaid** [comment]
Here's a suggested PR https://github.com/laravel/framework/pull/20463
