### ISSUE TITLE
JoinClause whereIn existing query is not supported

### ISSUE THREAD

**Issue by rtheunissen** [laravel/framework#20451]
- Laravel Version: 5.4
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7

### Description:

You should be able to pass an existing Builder to `whereIn` of a `JoinClause`, but this doesn't work because the [`if ($values instanceof static)`](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Query/Builder.php#L731) doesn't catch the expected case when you pass a `Builder` because it's not an instance of `JoinClause`. 

It should be `if ($values instanceof Builder)`, potentially also a case for `Eloquent\Builder`.

`TypeError: Argument 1 passed to Illuminate\Database\Grammar::parameterize() must be of the type array, object given`

### Steps To Reproduce:

```php

/** @var Illuminate\Database\Query $query */
$query = $this->getFieldQuery(); 

Account::join('other_table', function (JoinClause $join) use ($query) {
    return $join->on('other_table.field', '=', 'accounts.field')
                ->whereIn('other_table.field', $query);
});
```

**Comment by rtheunissen** [comment]
PR #20453 20453

**Comment by Dylan-DPC** [comment]
You can pass a closure to `whereIn` as the second argument.

**Comment by rtheunissen** [comment]
@Dylan-DPC that doesn't apply here. We have an existing query builder that we want to use as the subquery. Passing a closure provides us with a new builder.

**Comment by themsaid** [comment]
Moving discussion to PR.
