### ISSUE TITLE
Missing observer class exception

### ISSUE THREAD

**Issue by routegroup** [laravel/framework#20455]
- Laravel Version: ```5.4.32```
- PHP Version: ```PHP 7.1.0-2+deb.sury.org~xenial+1 (cli) ( NTS )```
- Database Driver & Version: ```mysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $```

### Description:
It's more like a thing to a discussion. Should we let know developer that given observer to a class, while is registering observers, is missing? Something like to check if class exists before running ```registerModelEvent```.

### Steps To Reproduce:
1. Register observer for a class (in a boot or service provider).
2. Give it a wrong namespace. (ex. App\UserObserver instead of App\Observers\UserObserver).
3. Run anything that would run event in observer.
4. No exception for a missing class.

**Comment by ntzm** [comment]
Discussion should be done in laravel/internals

**Comment by routegroup** [comment]
Continued in https://github.com/laravel/internals/issues/718
