### ISSUE TITLE
Process component of Symfony has a bug on version < 3.3.4

### ISSUE THREAD

**Issue by abkrim** [laravel/framework#20462]
- Laravel Version: 5.4.32
- PHP Version: 7.0.18-0ubuntu0.16.04.1
- Database Driver & Version: Not applicable

### Description:
Process converts an empty string argument to `"` sometimes 

### Steps To Reproduce:

```
$forSearch = 'some process';

$ps = new Process('ps aux|grep '.$process.'| grep -v grep');
$ps->run();

 if ( ! $ps->isSuccessful()) {
     Log::error("search process failed by Process command");
    dd($ps->getOutput());  // Not show anything. It's empty
 } else {
     // DO something for process $ps->getOutput()
}
```

After hours,  try search... and get--> https://github.com/symfony/symfony/pull/23477

I've tried update Process component but I don't know well to do.
After several tests, I see

- Sometimes, code work and return string with process filtered
- Sometimes, not work and return empty

Laarvel uses 3.2 version of Process

**Comment by nicolas-grekas** [comment]
@abkrim unless you're doing something else before, the code above may have a serious security issue: by concatenating the unescaped $process, one might inject any command here.
If you're using Process 3.3, I encourage you to use the new way for creating them, see description here:
https://github.com/symfony/symfony/issues/23778 (not the RFC itself, but the hint give in the description about how it works today.)
On 3.2, you have to use `escaleshellarg()` or `ProcessUtils::escapeArgument()`.
Not doing so is unsupported I'd say.

**Comment by themsaid** [comment]
This is not a laravel issue.
