### ISSUE TITLE
clear orderby

### ISSUE THREAD

**Issue by phpfalcon** [laravel/framework#20469]
- Laravel Version: 5.4
- PHP Version: php 7
- Database Driver & Version:

### Description:

I want to clear builder orders

I know you can do this :
`$builder->orders = null`
but it's not working

I did implanted my own method to laravel builder and worked perfectly

```php
    public function clearOrderBy()
    {
        $this->{$this->unions ? 'unionOrders' : 'orders'} = null;

        return $this;
    }
```

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by phpfalcon** [comment]
i'm not looking for solution  i've already solved it did you saw the snippet it would be nice that feature implanted inside the framework ... 

since I know Taylor won't accept it as new method any time soon  .. I have created a small package for anyone interested : 

https://github.com/phpfalcon/laravel-clear-orders-by
