### ISSUE TITLE
default "/" route not work with post. unable to send json param

### ISSUE THREAD

**Issue by flik** [laravel/framework#20478]
- Laravel Version: 5.4.*
- PHP Version: 5.6.4
- Database Driver & Version: not needed

### Description:
 default "/" route not work with post. We are unable to send json params. not working. 
Route::post('/', 'VehicleController@vehiclex');	

### Steps To Reproduce:
add a post route on '/' and try to post any param. You will never receive.

**Comment by decadence** [comment]
Everything is ok:

```php
Route::post("/", "Index@postIndex");

public function postIndex()
{
    dd(request()->all());
}
```
prints POST data.

**Comment by themsaid** [comment]
Can't replicate as well.

**Comment by flik** [comment]
@decadence  No. Just post some params as JSON. It will never work.

**Comment by decadence** [comment]
@flik maybe it's because Laravel redirects trailing slashes and your POST data resets after redirect.
See https://github.com/laravel/framework/issues/1438#issuecomment-321431734
