### ISSUE TITLE
ShareErrorsFromSession not called when NotFoundHttpException is thrown

### ISSUE THREAD

**Issue by s4uron** [laravel/framework#20477]
- Laravel Version: 5.4.0
- PHP Version: 5.6.28
- Database Driver & Version:

### Description:
The ShareErrorsFromSession middleware does not get called when a NotFoundHttpException is thrown.
Thats why I get:
 ErrorException
Undefined variable: errors

### Steps To Reproduce:
Produce a NotFoundHttpException
Use:
```
@if($errors->any())
    <div class="alert alert-danger fade in alert-dismissible" role="alert">
        <h4><button type="button" class="close" data-dismiss="alert" aria-label="{{ trans('global.errors_close') }}"><span aria-hidden="true">&times;</span></button>
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span> {{ trans('global.error_following_errors_occurred') }}</h4>
        <ul>
            @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
```

in your custom 404.blade.php

**Comment by themsaid** [comment]
Why would you display validation errors in a 404 response screen?

**Comment by Rattone** [comment]
@themsaid I know this is an old issue, but I encountered the same problem today. I might have a 404 page with a login form in the site header, and then a validation.
