### ISSUE TITLE
Illuminate\Contracts\Routing\ResponseFactory missing file() method

### ISSUE THREAD

**Issue by mosinve** [laravel/framework#20472]
- Laravel Version: 5.4.*
- PHP Version: 7.1

### Description:
`Illuminate\Contracts\Routing\ResponseFactory` missing file() method

### Steps To Reproduce:
Check and compare `Illuminate\Routing\ResponseFactory` class and `Illuminate\Contracts\Routing\ResponseFactory` contract.
Illuminate\Routing\ResponseFactory itself has file() method, but Illuminate\Contracts\Routing\ResponseFactory hasn't. 
And there is info in official docs about the using both download() and file() methods https://laravel.com/docs/5.4/responses#file-downloads and https://laravel.com/docs/5.4/responses#file-responses.

**Comment by mosinve** [comment]
I think that when file() methods was added by this commit https://github.com/laravel/framework/commit/a96ea3c8c95657832f3d534d42db4b5efc7b8515, the author just forget to add same method to corresponding contract.

**Comment by themsaid** [comment]
Adding a new method to the contract would be considered a breaking change, that's why it wasn't added.

**Comment by mosinve** [comment]
But then file method needed to be removed isn't it?

**Comment by themsaid** [comment]
why removed? You can use it or not use it.

**Comment by mosinve** [comment]
Even if it not defined in contract?  Then, it seems, 
} don't understand contracts right)
