### ISSUE TITLE
Cache::add always return false (Redis, use phpredis extension)

### ISSUE THREAD

**Issue by Except10n** [laravel/framework#20476]
- Laravel Version: 5.4
- PHP Version:7.1
- Database Driver & Version:

### Description:
use predis, Cache::add is work fine, but phpredis always return false

This leads to Scheduler CacheMutex error

**Comment by themsaid** [comment]
Works fine with me:

```
Cache::add('key', 'value', \Carbon\Carbon::now()->addDays(2))
```

Return true the first time, running it again returns false, using `phpredis`.

**Comment by Except10n** [comment]
What phpredis version are you using?

**Comment by themsaid** [comment]
3.1.2

**Comment by Except10n** [comment]
Thanks, I find it's my problem
in production environment the redis version does not support lua
