### ISSUE TITLE
Model Accessor not working on Join

### ISSUE THREAD

**Issue by imranali1** [laravel/framework#20474]
- Laravel Version: 5.4.*
- PHP Version: 7.1
- Database Driver & Version: MySql 5.6

### Description:
I'm not sure if its a bug or its the normal behavior.

Model Accessor & Mutator are not working with query join. 

Example:
```
class User extends Model
{
    /**
     * Get the user's first name.
     *
     * @param  string  $value
     * @return string
     */
    public function getFirstNameAttribute($value)
    {
        return ucfirst($value);
    }
}
````

When you join User Model with some other Model Accessor wont work. 
For Example:
```
$userOrders = Orders::join('users', 'users.id', '=', 'orders.user_id')->get();
```
Above query will not execute "getFirstNameAttribute($value)" Accessor because of join.

Thanks.

**Comment by themsaid** [comment]
yes because here you're loading the row from the db via a raw query, not via ELoquent.

**Comment by themsaid** [comment]
You can use eager loading to load Users attached to Orders

**Comment by jeff-browne** [comment]
> * Laravel Version: 5.4.*
> * PHP Version: 7.1
> * Database Driver & Version: MySql 5.6
> 
> ### Description:
> I'm not sure if its a bug or its the normal behavior.
> 
> Model Accessor & Mutator are not working with query join.
> 
> Example:
> 
> ```
> class User extends Model
> {
>     /**
>      * Get the user's first name.
>      *
>      * @param  string  $value
>      * @return string
>      */
>     public function getFirstNameAttribute($value)
>     {
>         return ucfirst($value);
>     }
> }
> ```
> 
> When you join User Model with some other Model Accessor wont work.
> For Example:
> 
> ```
> $userOrders = Orders::join('users', 'users.id', '=', 'orders.user_id')->get();
> ```
> 
> Above query will not execute "getFirstNameAttribute($value)" Accessor because of join.
> 
> Thanks.

@imranalii have you any solution plz send me i have same problem

**Comment by imranalii** [comment]
@jeff-browne If you want to use Mutators then you should not use  any raw query. 
You can only use Laravel's eloquent relations instead.

**Comment by BeKnowDo** [comment]
I'm not using relationships in my model and I was able to run a query against a model with a "manual" join:

`$lots = ItemLot::select(
          'qty_on_hand',
          'qty_alloc',
          'qty_trans_alloc',
          'qty_alloc_odd',
          'qty_trans_alloc_odd',
          'itmlot.gauged_ind',
          'lotmst.origin_code',
          'invrej.plating_ok'
        )
          ->leftJoin('lotmst', function ($join) {
            $join
              ->on('lotmst.lot_suffix', '=', 'itmlot.lot_suffix')
              ->on('lotmst.lot_no', '=', 'itmlot.lot_no');
          })
          ->leftJoin('invrej', function ($join) {
            $join
              ->on('itmlot.lot_suffix', '=', 'invrej.lot_suffix')
              ->on('itmlot.lot_no', '=', 'invrej.lot_no');
          })
          ->where('itmlot.item_no', $this->item)
          ->where('itmlot.branch', $branch)
          ->where('lotmst.origin_code', '<>', 'TW')
          ->where('lotmst.origin_code', '<>', 'CN')
          ->where('itmlot.invent', 'R')
          ->get();`

Model:

`
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class ItemLot extends Model
{
  protected $connection = 'attunity';
  protected $table = 'itmlot';
  public $timestamps = false;

  public function getLotNoAttribute($value)
  {
    return trim($value);
  }

  public function getLotSuffixAttribute($value)
  {
    return trim($value);
  }

  public function getOriginCountryAttribute($value)
  {
    return trim($value);
  }

  public function getItemNoAttribute($value)
  {
    return trim($value);
  }

  public function getGaugedIndAttribute($value)
  {
    return trim($value);
  }
}

`
