### ISSUE TITLE
Laravel 5.4 queues storing the data in jobs table but not sending the queues emails on server

### ISSUE THREAD

**Issue by usamamashkoor** [laravel/framework#20481]
For Laravel Queue to run in background i have installed supervisor on Ubuntu so that i can run queue:work command on Ubuntu as a service 24 h so that i can send emails to user using email Queue.

for that i have created a file a file in 

**/etc/supervisor/conf.d**

to monitor the process queue:work.

here is my file
```
[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/laravel/artisan queue:work database --sleep=3 --tries=3
autostart=true
autorestart=true
user=ubuntu
numprocs=4
redirect_stderr=true
stdout_logfile=/var/www/html/laravel/storage/logs/laravel-worker.log
```
and here is my laravel Mail Queue code

`Mail::to($email)->queue(new SubscriberEmail($name));`

when i run this code the laravel store the data in jobs table but don't send the emails to users

i have also checked the failed jobs table but their is no data in that table.

i have run this command on server

`sudo supervisorctl status`

it shows me this detail

 

>    laravel-worker:laravel-worker_00 FATAL Exited too quickly (process log may have details)
> 
>     laravel-worker:laravel-worker_01 FATAL Exited too quickly (process log may have details)
> 
>     laravel-worker:laravel-worker_02 FATAL Exited too quickly (process log may have details)
> 
>     laravel-worker:laravel-worker_03 FATAL Exited too quickly (process log may have details)

i have gone to logs folder but their no log file has been generated.

Kindly help me on this issue please.

Thanks

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this github area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I please suggestion closing your issue ticket here. Instead trying asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.

**Comment by usamamashkoor** [comment]
Thanks.
