### ISSUE TITLE
Elixir watch doesn't do anything

### ISSUE THREAD

**Issue by fabis94** [laravel/framework#20486]
Using the latest version of laravel-elixir. When running 'gulp', it executes correctly - outputs the changes in the terminal and writes them to the filesystem. When running 'gulp watch' and doing changes, the changes appear in the terminal, but nothing is actually done (the resulting files stay unchanged).

I'm on a pretty large codebase, maybe it has something to do with that (lots of JS and SASS files). Any ideas?

**Comment by themsaid** [comment]
Please report on the correct repo: https://github.com/laravel/elixir

**Comment by mertenhanisch** [comment]
I have the same problem. But there appears to be no "Issues" menu in the elixir repo.
@fabis94 did you find out more?

**Comment by fabis94** [comment]
@mertenhanisch nope, the problem just disappeared by itself. have no idea how to fix it.

**Comment by mertenhanisch** [comment]
@fabis94 may I ask, which node version do you use in that project?
