### ISSUE TITLE
Min and max validation rules don't work without a numeric rule

### ISSUE THREAD

**Issue by sartatpdev999** [laravel/framework#20483]
- Laravel Version: 5.4.30
- PHP Version: 5.6.30

### Description:
Min and max validation rules don't work without a numeric rule. Here is simple example:
```
$validator = \Validator::make(
  ['test' => 150], 
  ['test' => 'min:100|max:200']
);
dd($validator->passes());

// Expected: true
// Actual: false

```

But if i change validation rule to ```['test' => 'numeric|min:100|max:200']``` it works as expected. Is it a bug or a feature?

**Comment by decadence** [comment]
Can be a feature because size is evaluated depends on value type which is string by default. Can be string, numeric, file or array.

**Comment by djh101** [comment]
For strings _min_ and _max_ refer to the length of the string.

**Comment by sartatpdev999** [comment]
Thanks for answers. Closed

**Comment by VoBichTo** [comment]
Can I help you ?error same you . I don't know to fix it :(

**Comment by AlphaWeb1** [comment]
thanks this doc  trace really

> For strings _min_ and _max_ refer to the length of the string.

Thanks it worked for me too
