### ISSUE TITLE
snake_case doesn't convert kebab-case strings

### ISSUE THREAD

**Issue by AustP** [laravel/framework#20482]
- Laravel Version: 5.4.28
- PHP Version: 7.1.3

### Description:
See Title

### Steps To Reproduce:

1. Start with a string in kebab-case.
2. Pass it to the `snake_case` helper function.
3. Notice that nothing happened.

```
$str = 'inquiry-types';
echo($str); // inquiry-types

$str2 = snake_case($str);
echo($str2); // inquiry-types
```

### Workaround
Use `str_slug`

```
$str = 'inquiry-types';
echo($str); // inquiry-types

$str2 = str_slug($str, '_');
echo($str2); // inquiry_types
```

**Comment by themsaid** [comment]
yes it's purpose is to convert camleCase to snakeCase

**Comment by laurencei** [comment]
I'm not entirely sure if `-` should be converted to `_` anyway? I googled around - and there doesnt seem to be a consensus (that I could find)...

**Comment by AustP** [comment]
Yeah I couldn't find anything on it either. I assumed that all of the case functions would work interoperably with each other, but that could be an incorrect assumption.

I figured I'd open an issue in case it was an oversight rather than by design.

**Comment by Dylan-DPC** [comment]
@AustP you can create a proposal on laravel/internals repo.

**Comment by AustP** [comment]
No thanks. I don't care that much. :smile:

**Comment by maxanstey** [comment]
Incredible that this is still like this!

**Comment by bradacjan** [comment]
@themsaid If a proposal and PR were prepared, as @Dylan-DPC suggested, do you think there is a chance that such a request would be accepted?

I firmly believe that the consensus is that `Str::snake('inquiry-types')` _should_ return `inquiry_types` (as the documentation also suggests, by saying "Convert a string to snake case."). But I am also afraid that change might be problematic as `Str` is a core support class and some (potentially many) people may rely on it actually working in this, arguably broken, way.

The change would be very simple, though, and I would gladly prepare a PR if there is a chance that it would get accepted, possibly into a later major version of Laravel as not to break compatibility on a minor release.

**Comment by laurencei** [comment]
@bradacjan - the issue would be its a breaking change, and the question has to be whats the gain for the potential errors it might cause.

**Comment by cjmcdonn** [comment]
It seems like this should be the expected behavior, after all camelCase('start-with-kebab') converts to 'startWithKebab', just as you would expect. The fact that snake case doesn't seems to be the outlier. The requirement to "stack" helpers seems excessive.

```
>>> $str = 'start-with-kebab';
=> "start-with-kebab"
>>> Illuminate\Support\Str::camel($str);
=> "startWithKebab"
>>> Illuminate\Support\Str::snake($str);
=> "start-with-kebab"
>>> Illuminate\Support\Str::snake(Illuminate\Support\Str::camel($str));
=> "start_with_kebab"
```

**Comment by RicLeP** [comment]
If you’re passing a second argument of `_` should it convert hyphens to underscores as you’re explicit asking for that? Or does this seem a bit inconsistent as the ‘default’ is `_` even if it’s not used.

**Comment by forsvunnet** [comment]
I was looking for how to convert between kebab and snake in Laravel and found this issue.
@cjmcdonn's solution to stack string helpers worked for me, and since Laravel 9.x it can be shortened to this `str('start-with-kebab')->camel()->snake();`
