### ISSUE TITLE
laravel/framework v5.4.32 require php 7.1.x

### ISSUE THREAD

**Issue by sirber** [laravel/framework#20490]
- Laravel Version: 5.4.32
- PHP Version: 5.6.30

### Description:
laravel/framework v5.4.32 ask for doctrine/instantiator 1.1.0 which ask for php 7.1.x

### Steps To Reproduce:
run composer install on a php 5.6 server

**Comment by sirber** [comment]
fix: composer require "phpunit/php-token-stream:1.4.11" "doctrine/instantiator:1.0.5" "laravel/framework:5.4.20"

**Comment by sirber** [comment]
latest working version on php 5.6.30 would be laravel 5.4.30

**Comment by gmsantos** [comment]
@sirber delete your composer.lock an try again

**Comment by gmsantos** [comment]
related #20328

**Comment by sirber** [comment]
worked!

I removed the two packages from composer.json (aka "doctrine/instantiator:1.0.5" and 
"laravel/framework:5.4.20"), set laravel/framework:^5.4, deleted composer.lock. 

Thank you!

# composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)                      
Package operations: 0 installs, 1 update, 0 removals
  - Updating laravel/framework (v5.4.30 => v5.4.32): Downloading (100%)         
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
Generating optimized class loader
The compiled services file has been removed.

**Comment by sirber** [comment]
my dev machine is in php 7.1 but not the dev server

**Comment by gmsantos** [comment]
You can configure your dev machine to emulate the server version (https://github.com/laravel/installer/pull/69)

https://getcomposer.org/doc/06-config.md#platform
