### ISSUE TITLE
Eloquent doesn't use joins for querying relations, it could be more efficient

### ISSUE THREAD

**Issue by kasperpeulen** [laravel/framework#20497]
If I do the following code:
`$threads = Thread::with('user')->latest()->get();`

I see that Eloquent using the following sql query:
![image](https://user-images.githubusercontent.com/1035299/29162398-9b6c5d34-7db9-11e7-9bd8-5b58f4d1c2dd.png)

This could be optimised by using the following query, and mapping that to the object:

![image](https://user-images.githubusercontent.com/1035299/29162375-86938608-7db9-11e7-9c5f-4f4ad1d26564.png)

The performance win for this very simple query seems here around 1-2ms in development. I guess in real world situation sending to request to the mysql server is even worse for performance.

I understand that not for all kind of relations this would be feasible, but for eager loading belongsTo relations it seems like the obvious choice to do a join instead of sending two queries to the server.

**Comment by Dylan-DPC** [comment]
This is not a bug. Kindly open an issue in laravel/internals repo :)

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
