### ISSUE TITLE
Early Route->getController() could leads to Fatal error on mb_strpos()

### ISSUE THREAD

**Issue by Tybaze** [laravel/framework#20507]
- Laravel Version: 5.4.32 and dev-master

### Description:
I'm sorry I'm new to Laravel

If you try to call getController() on a Illuminate\Routing\Route which has not this handler already set.

It will try to call : 
1. Route->parseControllerCallback();
2. Str::parseCallback($this->action['uses']);

But $this->action['uses'] is currently an Object(Closure) and not a string, which will result in :

**Fatal error: Uncaught ErrorException: mb_strpos() expects parameter 1 to be string, object given in ./vendor/laravel/framework/src/Illuminate/Support/Str.php on line 103**

Fix proporsal : I'm too beginner with Laravel to provide a patch. some ideas : 
getController() should : 
- return NULL 
- throw \Exception('Route has no handler');
- (renaming getController() to getControllerAction() but it won't avoid the Fatal)

### Steps To Reproduce:

Add in your App\Exceptions\Handler

>     public function render($request, Exception $exception)  { 
>     
>         $request->route()->getController();
>     
>     }    

Then made your laravel.log not writeable, it will throw an Exception while the Handler is used but the Controller is not initialized in the Route.

**Comment by Tybaze** [comment]
Sorry, Route->isControllerAction is protected so we couldn't use it.

We need to use a  Route->getActionName() which return "Closure" if it's not initlialized.

**Comment by Dylan-DPC** [comment]
@Tybaze close the issue if you have solved your problem

**Comment by Tybaze** [comment]
Thanks Dylan, 

but I do not ask some help to solve my problem, I just give a workaround but this is not a fix.

I don't think that getting a Fatal Error is a normal behavior for a framework like Laravel.

**Comment by Dylan-DPC** [comment]
using a protected method isn't a bug. You can use the forums or slack channels to solve your problem.

**Comment by Tybaze** [comment]
I must be wrong in my explains.

Route->getController() is not a protected method and it's generating a Fatal Error.

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only.

**Comment by Tybaze** [comment]
Your both quite sympatic, but your answers looks like a bot "ask forums" => I do NOT need your help at all. and I have nothing to ask. 

I just report a bug that calling Route()->getController() can result in php Fatal Error because the variable is wrongly handled by the framework. 

You can close the issue, by answering "OK we won't fix" but do NOT said "ask on the forums", because it means that you do not understand the Issue.

**Comment by anthonyblazejack** [comment]
I'm encountering the exact same behavior described by @Tybaze.  It is clearly a bug.

**Comment by 181** [comment]
> 
> 
> Sorry, Route->isControllerAction is protected so we couldn't use it.
> 
> We need to use a Route->getActionName() which return "Closure" if it's not initlialized.

Just met with this issue, today, think it could be convenient for others, there is another public function called getActionMethod(), which returns 'Closure' too if it's calling from a route closure.

**Comment by alanzhaonys** [comment]
Encountered the same error today. This is still a bug!

**Comment by awaisalrehman** [comment]
I am facing the same issue.
