### ISSUE TITLE
Current user becomes null if error 40* occurred

### ISSUE THREAD

**Issue by rorc** [laravel/framework#20508]
- Laravel Version: 5.4.32

### Description:
1. I have route `Route::post('/save', callback);`
2. I have template `views/errors/405.blade.php`, which uses `Auth::user();`

When i open url `/save` in browser (get method), i got `null` in `Auth::user()` in my `405.blade.php` template.

**Comment by decadence** [comment]
Same for 404.blade.php.
It's because session is not started for that pages.

**Comment by rorc** [comment]
Why? Can we fix it?

**Comment by decadence** [comment]
It's known issue, you can find discussion.
You can move `\Illuminate\Session\Middleware\StartSession` middleware to global `$middleware` array.

**Comment by decadence** [comment]
https://github.com/laravel/framework/issues/13517

**Comment by rorc** [comment]
Anyway, if i set `StartSession` in `Kernel.php` as first, user still `null`
```php
    protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        \Illuminate\Session\Middleware\StartSession::class,
        \Illuminate\Session\Middleware\AuthenticateSession::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
    ];
```

**Comment by decadence** [comment]
Yeah seems like it doesn't work anymore in 5.4.

**Comment by themsaid** [comment]
please refer to https://github.com/laravel/framework/issues/13517

**Comment by decadence** [comment]
@themsaid em... And what? We found that issue but its solution doesn't work on the latest Laravel so there is no workaround now.

**Comment by themsaid** [comment]
To get it to work move these 3 middleware to the global one:

```
\App\Http\Middleware\EncryptCookies::class,
\Illuminate\Session\Middleware\StartSession::class,
\Illuminate\View\Middleware\ShareErrorsFromSession::class,
```

But then sessions will start while your app is processing API endpoints.

**Comment by rorc** [comment]
Yea, its bad solution: do this 3 middlewares alltime even in api
Really not other solutions?

**Comment by devcircus** [comment]
Its a workaround because if the resource isn't found or served, the session technically shouldn't be reachable, so most solutions will be hacky.

**Comment by browner12** [comment]
a good solution (IMHO) that I proposed a ***long*** time ago was to have the ability to route the HTTP error pages to a Controller.

That way these pages would behave identical to how all your other pages behaved.

**Comment by decadence** [comment]
@browner12 maybe it's worth raising this question one more time? This limitation is annoying.

**Comment by decadence** [comment]
@themsaid thanks for sharing solution

**Comment by abhishek-pokhriyal** [comment]
any new update on this problem?
