### ISSUE TITLE
Illuminate components can work with carbon 1.17. and above.

### ISSUE THREAD

**Issue by drnkwati** [laravel/framework#20502]
- Laravel Version: 5.4.
Laravel and illuminate  components as of version 5.4 
depend on carbon package version 1.20. 
I found out that versions of carbon including 1.17 still work without any issues.
The problem here is carbon 1.20 depends on symphony translation which is no longer required by 
Laravel as of version 5.4
Please can Taylor update the composer.json file for those packages requiring carbon, to support carbon as of 1.7 Which does not need symphony translation but still works ok.
Thanks

**Comment by themsaid** [comment]
It'll just be pulled into your vendor directory, you don't have to use it in your project, it'll only be used by carbon.

**Comment by drnkwati** [comment]
I don't like to have unused packages increasing the weight of my projects.

**Comment by drnkwati** [comment]
Please Taylor should update carbon in composer.json to ~1.17
Don't close my issue
