### ISSUE TITLE
DB before query hook

### ISSUE THREAD

**Issue by OzairP** [laravel/framework#20504]
- Laravel Version: 5.4.x

### Description:
This is more for discussion; but what are thoughts on having a database hook that is called before the query is called. This could be useful for caching database calls that are called from third party libraries or global caching queries.

Not sure how this could be incorporated or designed within the system but this is an example I was thinking of.

```PHP
function(Builder $builder, callable $continue) {
    if(Cache::has($builder->getQuery()->toSql()) {
        return Cache::get($builder->getQuery()->toSql());
    } else {
        return $continue();
    }
}
```

Continue does not need to be called, it can be removed altogether and the hook's parent can just check if anything was returned.

**Comment by Dylan-DPC** [comment]
This is not a bug. Open an issue in the laravel/internals repo

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
