### ISSUE TITLE
Contract violation

### ISSUE THREAD

**Issue by Nommyde** [laravel/framework#20509]
- Laravel Version: 5.4.27

### Description:

`illuminate/console` component declares `\Illuminate\Console\Command::$laravel` as implementation of `\Illuminate\Contracts\Foundation\Application` contract. But in `illuminate/database` component method `\Illuminate\Database\Console\Migrations\BaseCommand::getMigrationPath` calls `\Illuminate\Foundation\Application::databasePath` that is not a part of the contract.

### Steps To Reproduce:

Try to use migration commands outside of laravel framework with your own implementation of `\Illuminate\Contracts\Foundation\Application` but without implementing that noncontract method.

**Comment by Dylan-DPC** [comment]
I have made the PR as linked above but I will consider it a breaking change. Your solution would be to define this functions in your concrete classes (which i assume you already did). :smile:
