### ISSUE TITLE
Route Namespace prefix behaviour break consistency with uses

### ISSUE THREAD

**Issue by vinodraut** [laravel/framework#20515]
- Laravel Version: 5.4.x

### Description:
we use controllers at different folders like components we use route like given below so it can treat namespace from the beginning like so

`Route::get('/xyz', [
    'uses' => '\App\Xyz\ControllerClass@index',
]);`

While it works good but if we have lot of controllers which we want to have under the group it won't work as uses do, so we felt this should follow consistency with **uses**.

`Route::group(['namespace' => '\App\Xyz\'], function () {
   Route::get('/xyz', [
        'uses' => 'ControllerClass@index',
    ]);
});`

This will not work.

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.

**Comment by vinodraut** [comment]
Done!! https://github.com/laravel/internals/issues/731

Thanks
