### ISSUE TITLE
ambiguous column when using scope and belongsToMany back to same Model

### ISSUE THREAD

**Issue by pietheinstrengholt** [laravel/framework#20527]
- Laravel Version: 5.4.32
- PHP Version: 7.0
- Database Driver & Version: MySQL 5.5

### Description:
I'm encountering an issue when using a Model scope and a belongsToMany relation back to the same Model. The result is a "Integrity constraint violation: 1052 Column 'archived' in where clause is ambiguous". 

### Steps To Reproduce:

Create a Model with:

	protected static function boot()
	{
		parent::boot();
		static::addGlobalScope('archived', function(Builder $builder) {
			$builder->where('archived', 0);
		});
	}

	public function objects()
	{
		return $this->belongsToMany('App\Example', 'ontologies', 'subject_id', 'object_id');
	}

- Create Model called Example. Add a field archived.
- A table like ontologies with a id, subject_id and object_id. 
- Create two records (e.g. id 1,2) and add a record in the ontologies table with subject=1 and object_id=2
- Use a eager load or try to load the objects.

**Comment by themsaid** [comment]
Yeah the column now exists in the two instances of the table, SQL is confused which instance you mean. I don't believe there's much we can do from our side since we don't know either which instance you expect.

**Comment by pietheinstrengholt** [comment]
Using an table alias can be considered as an option. To make the field selection more explicit. I cannot oversee the complexity of how difficult this is to implement.

**Comment by Dylan-DPC** [comment]
This isn't a laravel bug. When you self join you will have columns duplicated and thus SQL will throw an error cause it will not know which column to pick. If you are doing a self join, you need t

**Comment by themsaid** [comment]
I'm not sure but feel free to submit a PR :).

For suggestions and feature requests please use the https://github.com/laravel/internals repo.
