### ISSUE TITLE
Notification duplication

### ISSUE THREAD

**Issue by elhelaly** [laravel/framework#20538]
- Laravel Version: 5.4
- PHP Version: 7.1
- Database Driver & Version: mysql & v 5.7.11

### Description:
Is there any way to prevent duplication for notification data?

### Steps To Reproduce:
In my case, I was using the notification via database, I had sent notification to user. Then user didn't read it. So if the same notification has been called again the notification sent again. So when user show his notifications he will see a duplicated notification. 
I handled it manually, before I send notification I checked if user has read_at with null or not for the same notification data.

But I hope to see it as feature in notification to prevent message duplication.

**Comment by Dylan-DPC** [comment]
This is not a bug. Open an issue in the laravel/internals repo
