### ISSUE TITLE
Bug compiling query, Illegal operator and value combination.

### ISSUE THREAD

**Issue by webmake** [laravel/framework#20530]
- Laravel Version: 5.4, (5.2 also reproducible)
- Database Driver & Version: 5.7

### Description:
Bug while compiling query, because building orWhere
https://github.com/laravel/framework/blob/d1378af9c95043e78452cab0ff2fe7579ce73f3b/src/Illuminate/Database/Eloquent/Builder.php#L227
passing 4arguments, so any given value is treated as operator and in https://github.com/laravel/framework/blob/4ce8d7af82c4398c86b0d1ef79825aae3683de7c/src/Illuminate/Database/Query/Builder.php#L500.
And then instead of expected https://github.com/laravel/framework/blob/4ce8d7af82c4398c86b0d1ef79825aae3683de7c/src/Illuminate/Database/Query/Builder.php#L587 to be `useDefault` as true, was passed false, and `prepareValueAndOperator` method is executed https://github.com/laravel/framework/blob/4ce8d7af82c4398c86b0d1ef79825aae3683de7c/src/Illuminate/Database/Query/Builder.php#L589 `invalidOperatorAndValue` method, which rises error.

### Steps To Reproduce:
> php artisan tinker
\DB::table('a')->whereId(1)->orWhere('id', 'like')->first();
InvalidArgumentException with message 'Illegal operator and value combination.'

causes message "Illegal operator and value combination." and rises `InvalidArgumentException` in application.
works with all words of https://github.com/laravel/framework/blob/4ce8d7af82c4398c86b0d1ef79825aae3683de7c/src/Illuminate/Database/Query/Builder.php#L180

**Comment by themsaid** [comment]
`orWhere('id', 'like')` This is not valid, you have to provide a 3rd argument for it to work.

**Comment by webmake** [comment]
Yes, but your documentation tells, that second parameter is fully valid, https://laravel.com/docs/5.4/queries, Or Statements.

**Comment by themsaid** [comment]
Consider these as reserved words:

```
'like', 'like binary', 'not like', 'between', 'ilike'
```

**Comment by webmake** [comment]
Well, you could never know what user writes in, you cannot filter these reserved keywords, if searching nickname in database, and nickname is "like", everything works fine with where, but orWhere has negative consequences, such as InvalidArgumentException.

**Comment by devcircus** [comment]
If there's a chance of that, then these convenience methods shouldn't be used. This is true in many situations dealing with reserved words.
