### ISSUE TITLE
[phpdoc] Missing `array` as @param type in Builder::orWhere

### ISSUE THREAD

**Issue by xfrenette** [laravel/framework#20546]
- Laravel Version: 5.4.28

### Description:
In [`Illuminate/Database/Query/Builder::orWhere()`](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Query/Builder.php#L626), the PHPDoc for the `$column` param does not specify `array` as a valid type, while `where()` accepts array.

**Comment by ntzm** [comment]
Feel free to submit a PR to fix :)

**Comment by themsaid** [comment]
fixed, thanks :)
