### ISSUE TITLE
Problem with ndbcluster engine

### ISSUE THREAD

**Issue by sobhanattar** [laravel/framework#20540]
- Laravel Version: 5.4.30
- PHP Version: 7.1.x
- Database Driver & Version: MySql 5.7

### Description:
transactions fails on `ndbcluster` engine with this error: ```SQLSTATE[42000]: Syntax error or access violation: 1178 The storage engine for the table doesn't support SAVEPOINT```. As I searched, found this [link](https://dev.mysql.com/doc/refman/5.7/en/mysql-cluster-limitations-unsupported.html) which points out mysql cluster limitations and unsupporting features which states: 
```Savepoints and rollbacks to savepoints are ignored as in MyISAM.```

Now I want to know if there is any workaround solutions for this problem in Laravel?

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by sobhanattar** [comment]
Thanks @Dylan-DPC

**Comment by Dylan-DPC** [comment]
@sobhanattar kindly close the issue :)
