### ISSUE TITLE
Route group namespace function breaks migrate

### ISSUE THREAD

**Issue by roverv** [laravel/framework#20549]
- Laravel Version: 5.4.30
- PHP Version: 7.0.10

### Description:
https://laravel.com/docs/5.4/routing#route-group-namespaces
When you add the example code from the page above, 
```
Route::namespace('Admin')->group(function () {
    // Controllers Within The "App\Http\Controllers\Admin" Namespace
});
```

php artisan migrate will return an error:
[Symfony\Component\Debug\Exception\FatalErrorException]
  syntax error, unexpected 'namespace' (T_NAMESPACE)

As far as i can tell, there is no namespace function. However, the namespace functionality it self does work.

 Using the 5.3 method returns no error on php artisan migrate:
https://laravel.com/docs/5.3/routing#route-group-namespaces
```
Route::group(['namespace' => 'Admin'], function () {
    // Controllers Within The "App\Http\Controllers\Admin" Namespace
});
```

**Comment by jakebathman** [comment]
Good catch, looks like it was changed in some docs formatting a few months back, and got sucked in with some other Route:: changes that `do` have shorthand methods.

Here's the change: https://github.com/laravel/docs/commit/9a778e299ce1b39f57a306aba65714cca45f9eef

And as far as I can tell, there were a few other methods change in the docs like that without the corresponding methods in `Router.php`.
 
I'll submit a PR for that right now to get it fixed. Thanks!

**Comment by jakebathman** [comment]
Huh, as far as I can tell, the ability to call `Route::namespace` has existed in the 5.4 codebase since 5.4.0, so it shouldn't be an issue with upgrading your version.

Are you _super sure_ you're on 5.4?

**Comment by themsaid** [comment]
Sorry but it looks like it's something in your code, follow the stack trace and you'll have a better idea on what was missing.

**Comment by roverv** [comment]
Yes im sure, its a clean, new install.

php artisan --version
Laravel Framework 5.4.30

Composer.json:
"name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0"
    },

**Comment by jakebathman** [comment]
Looks like using PHP 5.x won't allow for `namespace` as a method name, but that's now allowed in PHP 7. Can you check your PHP version @roverv ?

**Comment by roverv** [comment]
Yup, running PHP 7.0.10. 
Same issue can be found here, no solution however:
https://github.com/rappasoft/laravel-5-boilerplate/issues/622

@themsaid i have no idea which file i should trace, its a fatal error specific for the namespace in web.php

**Comment by ejstavares** [comment]
Hi, I had same installation as yours, add prefix ('') before namespace.

`Route::prefix('')->namespace('Api')->group( function () {
    //
});`
