### ISSUE TITLE
Please bump down carbon version to 1.17 as it does not depend on symphony translation

### ISSUE THREAD

**Issue by drnkwati** [laravel/framework#20556]
- Laravel Version: 5.4 does not require symphony translation, but carbon 1.20 does 
However i have checked and laravel can still perfectly work with carbon 1.17
Please set the main carbon required to 1.17 to reduce the framework size and git rid of unused packages.
Thanks

**Comment by Dylan-DPC** [comment]
This is not a bug. You can open a proposal in the laravel/internals repo

**Comment by themsaid** [comment]
Sorry we don't control what other packages require, and we can't lock package versions like this, people might need the new functionalities introduced in the recent versions.

**Comment by drnkwati** [comment]
I never said you should lock anyone on a package.
You have completely misunderstood me. Or maybe you just want to close the issue.
Good luck.

**Comment by Dylan-DPC** [comment]
> Please set the main carbon required to 1.17 to reduce the framework size and git rid of unused packages.

This means locking :lock: a package :package: :stuck_out_tongue:
