### ISSUE TITLE
Typecasting differs in Eloquent sum()

### ISSUE THREAD

**Issue by NiclasHedam** [laravel/framework#20554]
- Laravel Version: 5.4.32
- PHP Version: 7.1.8
- Database Driver & Version: MySQL 5.7.16

### Description:
Eloquent seemingly forgets to typecast, when I run sum() on a query/relationship. If I run get() first, the type is correct. Ideally, these two statements should give the exact same result.
![image](https://user-images.githubusercontent.com/770169/29266222-422b08dc-80e4-11e7-970c-f7ad23180b1c.png)

In the model, discount_amount is cast to float.

**Comment by themsaid** [comment]
In your second example, `sum()` is a query Builder method, no casting is applied when you do this, it'll be a pure sql query so you'll need to cast the results yourself.
