### ISSUE TITLE
i have an error method not allowed when i send post request through ajax

### ISSUE THREAD

**Issue by aamirkhan37557** [laravel/framework#20557]
- Laravel Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:

i have an error when i send post request in ajax when i click on the button click i get method not allowed 404 error and 405 error in console as well as on website
below is my code  name
![a](https://user-images.githubusercontent.com/24594319/29271227-51ef5258-80af-11e7-9577-bfb0db841350.png)
 a.blade.php

this is my routes
![routes](https://user-images.githubusercontent.com/24594319/29271279-77d241ce-80af-11e7-8f54-5f8156f005c6.png)

this is my controller
![controller](https://user-images.githubusercontent.com/24594319/29271285-80b556a0-80af-11e7-8136-5d2f8b5666b5.png)

this is my main page before clicking on the button

![before](https://user-images.githubusercontent.com/24594319/29271331-b1dfa956-80af-11e7-816b-3e017a1d4d95.png)

here is error when i click on the button
 
![after](https://user-images.githubusercontent.com/24594319/29271316-a49246b4-80af-11e7-912e-9155bda6103a.png)

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this github area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I please suggestion closing your issue ticket here. Instead trying asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.

**Comment by aamirkhan37557** [comment]
okay
