### ISSUE TITLE
bug in the blade - multiple leading white spaces produce an error

### ISSUE THREAD

**Issue by xokaido** [laravel/framework#20558]
- Laravel Version: 5.4
- PHP Version: *

### Description:

`{{  config( 'assets.goodThing' ) }}` will produce an error because of multiple leading whitespaces...

Thanks

**Comment by decadence** [comment]
What error?

```php
{{ config(                            'app.name'                         ) }}
```
works fine.

**Comment by xokaido** [comment]
now, the leading space aferter the curly braces and the "config" word....
{{          config( 'assets.goodThing' ) }}

**Comment by jakebathman** [comment]
Not seeing this issue, this works just fine, too:

`            {{          config('app.name')          }} `

What error are you seeing, specifically?

**Comment by themsaid** [comment]
`{{ config( 'assets.goodThing' ) }}` works fine with me as well, closing since no body can replicate.

Flush your cached views and try to run it again, if still having issues check the cached views to see how the compiled output looks like.
