### ISSUE TITLE
[5.5] Fatal error during package discovering

### ISSUE THREAD

**Issue by ptournet** [laravel/framework#20574]
- Laravel Version: 5.5-dev
- PHP Version: 7.0

### Description:
During:
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

Get:
> Fatal error: Uncaught ReflectionException: Class App\Console\Kernel does not exist in D:\PHP\MariVrac\vendor\laravel\framework\src\Illuminate\Container\Container.php:752

### Steps To Reproduce:
In composer.json modify
```
"autoload": {
    "psr-4": {
        "App\\": "app/"
    }
},
```
by
```
"autoload": {
    "psr-4": {
        "AnythingButApp\\": "app/"
    }
},
```

And run `composer update`

**Comment by themsaid** [comment]
This is wrong, you can't update the namespace in your composer.json without updating the namespace in your files.

**Comment by ptournet** [comment]
That's the definitive proof that I'm no good just out of bed and before breakfast ! Still I'm ashamed of missing out that obvious reason !

**Comment by themsaid** [comment]
Haha, It happens 😀
