### ISSUE TITLE
collection method forget doest remove property of a hasMany relation

### ISSUE THREAD

**Issue by acidfilez** [laravel/framework#20589]
- Laravel Version: 5.4.0
- PHP Version:7.1
- Database Driver & Version:
MariaDB

### Description:
Cant remove a column using forget with a columan using hasMany relation

### Steps To Reproduce:

Model
`
public function qualifications()
    {
        return $this->hasMany('App\Qualification');
    }
`
Now in the controller
`$collection->forget("qualifications")`

forget doesnt work, but if used agains a string it works.

Thanks

**Comment by Dylan-DPC** [comment]
I think the understood what the problem is. It may be forgetting the relation but when you do `$foo->relation`, it will query it again.

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only.
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
