### ISSUE TITLE
Session removes after Auth::onceUsingId()

### ISSUE THREAD

**Issue by rorc** [laravel/framework#20584]
- Laravel Version: 5.4.33

### Description:
```php
class ProfileController extends Controller
{
    public function impersonate(User $user)
    {
        \Session::put('impersonate', $user->id);

        return redirect()->home();
    }
}

//middleware
class Impersonate
{
    public function handle($request, Closure $next)
    {
        if (\Session::has('impersonate')) {
            \Auth::onceUsingId(\Session::get('impersonate'));
        }

        return $next($request);
    }
}
```
Now, if go to url `profile/impersonate` i will redirect to home with login by another user, epic good!
But if i press F5, i will redirect to login form...

**Comment by Dylan-DPC** [comment]
You are combining a technique of checking the sessions with a login method that doesn't require a session. I don't see this as a bug. Would recommend asking in the forums or slack channel.

**Comment by rorc** [comment]
If i just use anywhere `\Session::put('anykey', 'anyvalue');`, after F5 i just logout and redirect to login page...
Probably, my session mechanism is broken 😕

**Comment by mushketer888** [comment]
I don't think there is strange behaviour here...
Do you use \Illuminate\Session\Middleware\AuthenticateSession ?
PS
I use https://github.com/404labfr/laravel-impersonate and it it fine

**Comment by themsaid** [comment]
That's expected, `onceUsingId` logs you in in the current request only.

**Comment by rorc** [comment]
@themsaid Yes, but why destroying general auth session?

**Comment by rorc** [comment]
@themsaid In my case, session key `impersonate` destroying...

**Comment by themsaid** [comment]
It doesn't even touch the session, something else must have flushed your session.

**Comment by rorc** [comment]
That's it! I do nothing for remove my session key `impersonate`...

**Comment by rorc** [comment]
@themsaid All ok after first page load http://joxi.ru/gmveypzUxBn40r
After middleware hits:
```php
    public function handle($request, \Closure $next)
    {
        if (\Session::has('impersonate')) {
            \Auth::onceUsingId(\Session::get('impersonate'));
        }

        return $next($request);
    }
```
But after F5. again login form http://joxi.ru/Vm6b8Zlcx0bM8m

**Comment by kielabokkie** [comment]
I know this is a super old issue but for anyone finding this through a Google search (like I did). This behaviour is most likely caused by having the `\Illuminate\Session\Middleware\AuthenticateSession::class,` line in the `app/Http/Kernel.php` uncommented. If this middleware is enabled it executes a check if the `password_hash` in the session matches the password hash of the current user, if not it will logout and destroy the session.
