### ISSUE TITLE
how to store json data in laravel using http request 

### ISSUE THREAD

**Issue by aamirkhan37557** [laravel/framework#20583]
- Laravel Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:

how to store json data in laravel using http request  i want to store json data in my data base using request can somebody can help me

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only.
