### ISSUE TITLE
Laravel 5.4 may require doctrine/dbal which requires PHP ^7.1

### ISSUE THREAD

**Issue by jrean** [laravel/framework#20591]
- Laravel Version: 5.4.*
- PHP Version: 7.0

### Description:

https://laravel.com/docs/5.4/migrations#changing-columns
> Before modifying a column, be sure to add the `doctrine/dbal` dependency...

`doctrine/dbal` requires `doctrine/common` which requires `doctrine/annotations 1.*` `doctrine/cache 1.*` `doctrine/collections 1.*` `doctrine/inflector 1.*` `doctrine/lexer 1.*` which require **PHP ^7.1**

```
name     : doctrine/dbal
versions : * v2.5.13

requires
doctrine/common >=2.4,<2.8-dev
php >=5.3.2
```

```
name     : doctrine/common
descrip. : Common Library for Doctrine projects
versions : * v2.7.3

requires
doctrine/annotations 1.*
doctrine/cache 1.*
doctrine/collections 1.*
doctrine/inflector 1.*
doctrine/lexer 1.*
php ~5.6|~7.0
```

```
name     : doctrine/annotations
descrip. : Docblock Annotations Parser
versions : * v1.5.0

requires
doctrine/lexer 1.*
php ^7.1
```

```
name     : doctrine/cache
descrip. : Caching library offering an object-oriented API for many cache backends
versions : * v1.7.0

requires
php ~7.1
```
And so on...

**Comment by themsaid** [comment]
Pick the version that works with your PHP version, this is not a laravel issue.

**Comment by jrean** [comment]
@themsaid Thank you. I know.
It is not a direct / related / core Laravel issue but there is a lack of details in the documentation.
What about adding a note?

**Comment by cgarnier** [comment]
It s a laravel issue. 
https://laravel.com/docs/5.3
Requirement: php >= 5.6

You mess with the deps.

**Comment by AlexanderKochetkov** [comment]
Same issue. Fit requirements (php >= 5.6.4) and receive error.
It is expected to have php >= 7.1 on development environment and 5.6 on production?

vendor/laravel/framework/composer.json
in "require-dev"
"doctrine/dbal": "~2.5"

vendor/doctrine/dbal/composer.json
in "require"
"php": "^7.1"

**Comment by cgarnier** [comment]
I mess with the phone version. It s appening when you install vendors with
7 and run with5. My bad.

**Comment by AlexanderKochetkov** [comment]
True, if composer run on php5 it's work right.

**Comment by MichaelHoughton** [comment]
Thanks for the tip @cgarnier.

The issue can be fixed easily by updating your composer.json file configuration.

Simply add the following into your config part of your composer.json file:

```
"config": {
    "platform": {
        "php": "5.6.24"
    }
}
```

Obviously, set the specific version of PHP that you want. Composer will now install, taking into account the PHP version specified here!

**Comment by victor-ponamariov** [comment]
After I modified the composer.json file it said:

doctrine/dbal v2.6.2 requires php ^7.1 -> your PHP version (7.0.22-0ubuntu0.16.04.1) overridden by "config.platform.php" version (7.0.22) does not satisfy that requirement.

**Comment by MichaelHoughton** [comment]
@victor-ponamariov - if you follow my fix mentioned above, this should fix this issue.

**Comment by victor-ponamariov** [comment]
Oh, you're so fast :) Yes, exactly, I tried your fix. I put "php": "7.0.22" version, and composer displayed this message =(

So before modifying composer.json:
  Problem 1
    - doctrine/dbal v2.6.2 requires php ^7.1 -> your PHP version (7.0.22) does not satisfy that requirement.
    - doctrine/dbal v2.6.1 requires php ^7.1 -> your PHP version (7.0.22) does not satisfy that requirement.
    - doctrine/dbal v2.6.0 requires php ^7.1 -> your PHP version (7.0.22) does not satisfy that requirement.
    - Installation request for doctrine/dbal ^2.6 -> satisfiable by doctrine/dbal[v2.6.0, v2.6.1, v2.6.2].

After modifying:
  Problem 1
    - doctrine/dbal v2.6.2 requires php ^7.1 -> your PHP version (7.0.22-0ubuntu0.16.04.1) overridden by "config.platform.php" version (7.0.22) does not satisfy that requirement.
    - doctrine/dbal v2.6.1 requires php ^7.1 -> your PHP version (7.0.22-0ubuntu0.16.04.1) overridden by "config.platform.php" version (7.0.22) does not satisfy that requirement.
    - doctrine/dbal v2.6.0 requires php ^7.1 -> your PHP version (7.0.22-0ubuntu0.16.04.1) overridden by "config.platform.php" version (7.0.22) does not satisfy that requirement.
    - Installation request for doctrine/dbal ^2.6 -> satisfiable by doctrine/dbal[v2.6.0, v2.6.1, v2.6.2].

**Comment by MichaelHoughton** [comment]
The version of doctine that you have might be too high.  Try this version:

`"doctrine/dbal": "^2.5",`

That should solve it!

**Comment by victor-ponamariov** [comment]
Thank you Michael!

Btw, Love New Zealand & Ireland  =)

**Comment by a1tem** [comment]
Thank you, it really works.

**Comment by misheki** [comment]
Thank you Michael!  It works.
As for my version, I changed config platform php to 7.0.22 and doctrine/dbal to ^2.5.

**Comment by jamesaspence** [comment]
Just came across this after some digging. I agree with the assessment that the docs could mention something to the effect of:

"Please ensure you use the correct version of doctrine/dbal for your version of PHP!"

In my case, we only discovered this issue when deploying to PROD after STG (STG is a newer environment running 7.1, while PROD uses 7.0). I agree it's not your responsibility to make doctrine/dbal compatible, but it'd be very helpful to just have a quite warning / note in that section of the docs re: migrations.

**Comment by GrahamCampbell** [comment]
> "Please ensure you use the correct version of doctrine/dbal for your version of PHP!"

Not necessary actually. Just make sure you set the platform version in your composer file.

**Comment by rs-sliske** [comment]
isnt the solution here to use the same php version across different environments?

doctrine / laravel arent the issue here, they just give an obvious symptom.

**Comment by jamesaspence** [comment]
@rs-sliske fersure, I completely agree, that will definitely resolve our issue specifically (and in fact is something we have since addressed)

I still think, however, that a small note in this section would be very helpful to people like myself who wonder why composer is failing to run on prod. I don't think you have to even list the relevant version - just having a note saying that might change your PHP requirements would be immensely helpful IMO.

**Comment by kusaasira** [comment]
@MichaelHoughton some good work. Your input here has really saved me a lot. I appreciate!
