### ISSUE TITLE
exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1180 Got error 35 "Resource deadlock avoided" during COMMIT'  in /home/pay/vendor/laravel/framework/src/Illuminate/Database/Connection.php:457

### ISSUE THREAD

**Issue by saeedvaziry** [laravel/framework#20598]
I am getting this error in mariadb galera cluster with laravel 5.2

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this github area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I please suggestion closing your issue ticket here. Instead trying asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.

**Comment by saeedvaziry** [comment]
Thanks

**Comment by saeedvaziry** [comment]
Thanks
