### ISSUE TITLE
phpstan showing errors

### ISSUE THREAD

**Issue by vijaysebastian** [laravel/framework#20592]
- Laravel Version: 5.4
- PHP Version:7.0
- Database Driver & Version:MySql

### Description:
I am using phpstan to analyze my code. I saw 250 errors while analysing framework folder. May I know why it is happening and is it negligible issues?
Because in my application also has some issues similar to that.

Please help me,

`php -d memory_limit=-1 vendor/bin/phpstan analyse vendor/laravel`

**Comment by themsaid** [comment]
Don't analyze the framework code, it's fine :)

**Comment by vijaysebastian** [comment]
@themsaid I know framework is working fine :-) but my question why it is showing errors? is it negligible?

How can we configure phpstan to get same quality which framework has?
