### ISSUE TITLE
How to up or down a specific migration ? I came from rails framework i want to down a specific migration without creating another migration.

### ISSUE THREAD

**Issue by naveen1336** [laravel/framework#20604]
like in rails:
rails db:migrate:down verison={Timestamp}
I know this is a feature request.

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
