### ISSUE TITLE
Variable prefixed with MIX_ in .env file is not available for use

### ISSUE THREAD

**Issue by paradox37** [laravel/framework#20607]
- Laravel Version: 5.4.33
- PHP Version: 5.6.18
- Database Driver & Version: mysql 5.6.17

### Description:
Variable prefixed with MIX_ in .env file is not available for use. 

### Steps To Reproduce:
Set up project and define host using WAMP. Define MIX_SENTRY_DSN_PUBLIC in .env.

When using mix.browserSync(process.env.MIX_SENTRY_DSN_PUBLIC) it will not work. 
When I use console.log(process.env.MIX_SENTRY_DSN_PUBLIC) it shows undefined in console.
If I use mix.browserSync('http://example.com') then it works.

**Comment by Dylan-DPC** [comment]
It is better to create this issue on the laravel-mix repo
