### ISSUE TITLE
Laravel for exception and error display 500

### ISSUE THREAD

**Issue by xiaofeng-ling** [laravel/framework#20605]
- Laravel Version: 5.4.33
- PHP Version: 7.0.22
- Database Driver & Version: did not use

### Description:
php-fpm + nginx

When I use the composer to install laravel, I use **_throw new \Exception_** in the code or intentionally wrong grammar, the system directly reported 500 errors, after I check, I found in **Illuminate\Foundation\Bootstrap\HandleExceptions** **_set_exception_handler_** does not work, the **_handleException_** no work, But the laravel.log normal record, after tracking, **_HandleExceptions_** in the constructor is the normal implementation, and now my solution is in **_App\Exceptions\render_** **_echo_** output error display, and I used in other places using the **_set_exception_handler_** function Did not take effect, but I directly use php to write a single file to test the function is no problem, so I would like to know what the reasons

my .env the 
APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:zBtKxMNj8k/Xbo8bfn6fiephkCvoM7S+aHEs9vjW4r0=
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=http://localhost

### Steps To Reproduce:
use composer to install laravel, in **_routes\web.php_** file, add **_throw new \Exception_** in the code or intentionally wrong grammar, the system directly reported 500 errors

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.

**Comment by xiaofeng-ling** [comment]
ok, thanks
