### ISSUE TITLE
Cannot use more than one request ?

### ISSUE THREAD

**Issue by lukaisailovic** [laravel/framework#20601]
- Laravel Version: 5.5
- PHP Version: 7

### Description:
I'm using Laravel's request class to validate my request. I've done that for my register post method and trying to do it for Login Post but it wont work. I'm now using 5.5 but **this happened to me in 5.4 also**. I would just ignore it and try to write my validation logic in controller but it's ugly.

### Steps To Reproduce:
I've created RegisterRequest with `php artisan make:request` command and used it in my controller like this:
```
public function RegisterPost(\App\Http\Requests\RegisterRequest $request)
    {
      $request->persist();
      return $this->RegisterShowMnemonic();
    }
```
Now I'm trying to do the same for my LoginPost. Used same command just replaced **RegisterRequest** with **LoginRequest** , and used it in my method but I get Class `App\Http\Requests\LoginRequest does not exist` like i haven't included it.

My method:
```
public function LoginPost(\App\Http\Requests\LoginRequest $request)
    {

    }
```

I've also try to include it on the top with **Use** and and then try it like that but same thing happens. I've manually check if file is there, if class match and it looks right to me. Weird thing is that everything just works with **RegisterRequest**

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this github area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I please suggestion closing your issue ticket here. Instead trying asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.
