### ISSUE TITLE
[5.4.33] Delayed Jobs are not fired to Redis 

### ISSUE THREAD

**Issue by manfield** [laravel/framework#20619]
- Laravel Version: 5.4.33
- PHP Version: 7.0.17

### Description:
We're experiencing a bug:
when dispatching a delayed job (thus, after calling delay method on a job object) the job is not passed (or written) to the Redis database.
We use redis driver to enqueue jobs.

_Using database driver for queues makes it work as expected._

### Steps To Reproduce:
- Enable Redis 
- Configure Laravel in order to use Redis as queue driver
- Create a delayed job and call dispatch method to pass it to the queue manager
- You won't find the record in Redis database

If the line, that calls "delay", is commented, job is written in Redis db correclty:

```
 $jobPromemoria= new InviaMessaggioPromemoriaColloquioJob($event->colloquioSlot,$event->iscritto);
//$jobPromemoria->delay(Carbon::now()->addMinutes(10));
dispatch($jobPromemoria);
```

**Comment by manfield** [comment]
Not valid.
Queues are stored in queue:default:delayed. That's why we did not find them.

**Comment by manfield** [comment]
Ok queues are stored there, but php artisan queue:work never fire them.
I've a php artisan queue:work running with supervisor.
All jobs in the "default" queue are fired correclty.
All delayed jobs in the "default:delayed" queue are never fired.

I reopen the issue.

**Comment by themsaid** [comment]
I can't replicate your issue, delayed jobs are fired on my redis queue.

**Comment by manfield** [comment]
Let me re-test from scratch and I will be back to you.
THank you.

**Comment by manfield** [comment]
I retried.

The job remained in the queue.
This is the job stored in the Redis _default:delayed_ queue:


```
{\"displayName\":\"App\\\\Jobs\\\\InviaMessaggioPromemoriaColloquioJob\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"timeout\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\InviaMessaggioPromemoriaColloquioJob\",\"command\":\"O:45:\\\"App\\\\Jobs\\\\InviaMessaggioPromemoriaColloquioJob\\\":5:{s:60:\\\"\\u0000App\\\\Jobs\\\\InviaMessaggioPromemoriaColloquioJob\\u0000colloquioSlot\\\";O:45:\\\"Illuminate\\\\Contracts\\\\Database\\\\ModelIdentifier\\\":2:{s:5:\\\"class\\\";s:39:\\\"App\\\\Modules\\\\Common\\\\Models\\\\ColloquioSlot\\\";s:2:\\\"id\\\";s:36:\\\"6f816022-8663-11e7-89b3-f23c911f4fcf\\\";}s:6:\\\"\\u0000*\\u0000job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:5:\\\"delay\\\";i:1503315300;}\"},\"id\":\"nZVlKbobAvgDxcCgtMtZ5kKty32MO5x8\",\"attempts\":0}
```
The delay value is an integer (1503315300) whose CEST translation is:
**Monday August 21, 2017 13:35:00 (pm) in time zone Europe/Rome (CEST)**

System date at that moment was:
`$server>  Mon Aug 21 13:35:00 CEST 2017`

php `datetime.zone` is set (both for cli and fpm) to **Europe/Rome**

I really cannot see where the issue is.

Question: all delayed jobs should be fired if "now() >= $delayed_datetime" or only now() == $delayed_datetime"?

**Comment by themsaid** [comment]
```
dispatch(
        (new \App\Jobs\TestJob())->delay(\Carbon\Carbon::now()->addMinutes(1))
    );
```

Using predis on mac, the job is run exactly 1 minute after dispatching it, to me it looks like a problem with your machine :)

**Comment by manfield** [comment]
Ok will test on a different server.
Thank you

**Comment by manfield** [comment]
Confirmed.
It was a server misconfiguration.
Sorry and thanks a lot.

**Comment by davidsielert** [comment]
What was the problem ? I have the same issue happening. My delayed jobs just randomly disappear

**Comment by manfield** [comment]
I don't know exaclty, but according to solution I may say it was the laravel version.
After updating to the next version the problem was definitely solved.
I struck my head for days on this issue, checking everything quite everything: communication to redis, our procedures, etc..
At the end was a trivial issue.

**Comment by aqeeqabbas12** [comment]
I want to get specific delayed job from redis queue and release it instantly? 
Can you guys help me out?

**Comment by joni2back** [comment]
Same issue on my end, using [5.8]

After adding a job with a delay of 5 minutes 
I am able to see it by running

```php
\Queue::getRedis()
        ->connection(null)
        ->zrange('queues:default:delayed', 0, -1)
...
array(3) { [0]=>
string(1410)
"{"uuid":"73ba314a-7ba1-4570-a996-480538d53b01","displayName":"App\\Jobs\\DifusionPostJob","job":"Illuminate\\Queue\\Cal
lQueuedHandler@call","maxTries":null,"maxExceptions":null,"failOnTimeout":false,"backoff":null,"timeout":null,"retryUnti
l":null,"data":{"commandName":"App\\Jobs\\DifusionPostJob","command":"O:24:\"App\\Jobs\\DifusionPostJob\":13:{s:16:\"\u0
000*\u0000propertiesIds\";a:1:{i:0;i:388481;}s:15:\"\u0000*\u0000handlerClass\";s:57:\"App\\Services\\Difusions\\Handler
s\\EnlaceinmobiliarioHandler\";s:8:\"\u0000*\u0000force\";b:0;s:3:\"job\";N;s:10:\"connection\";N;s:5:\"queue\";N;s:15:\
"chainConnection\";N;s:10:\"chainQueue\";N;s:19:\"chainCatchCallbacks\";N;s:5:\"delay\";O:25:\"Illuminate\\Support\\Carb
on\":3:{s:4:\"date\";s:26:\"2025-02-19
12:09:20.589553\";s:13:\"timezone_type\";i:3;s:8:\"timezone\";s:30:\"America\/Argentina\/Buenos_aires\";}s:11:\"afterCom
mit\";N;s:10:\"middleware\";a:0:{}s:7:\"chained\";a:0:{}}"},"sentry_baggage_data":"sentry-trace_id=7c578e7811fc444eb8347
4aaadea8059,sentry-sample_rate=1,sentry-transaction=%2Fadmin%2Fnetworks%2F%7Bnid%7D%2Fproperty%2Fclone,sentry-public_key
=98cff17b2e8c46fb8183544c63bdaa33,sentry-environment=production,sentry-sampled=true","sentry_trace_parent_data":"7c578e7
811fc444eb83474aaadea8059-2bb502e9424a4708-1","id":"73ba314a-7ba1-4570-a996-480538d53b01","attempts":0,"type":"job","tag
s":[],"silenced":false,"pushedAt":"1739977460.5906"}"
.....
```

But suddenly it dissapear (not instantanly but, some seconds or minutes later)


Supervisord command:
```
php -d memory_limit=-1 artisan --no-ansi queue:work --verbose --queue=high,default --tries=8 --max-jobs=1 --sleep=1 --timeout=10000
```

I tried switching `after_commit` to true/false... but the issue persists (theres no exception or error enqueuing the command or with the rest of the code

**Comment by Fallsleep** [comment]
My experience : dont't reuse  Carbon object in loop if you add different time to the object!

my wrong code like:
```php
DB::beginTransaction();
$now = Carbon::now();
for ($i = 0; $i <= 23; ++$i) {
    TestJob::dispatch($id)->delay($now->addSeconds(20));
}
DB::commit();
```
I use [laravel 8], `redis` for queue driver, and set `after_commit`, so it cause all job's delay was set the same with the last job. 

But in `horizon/jobs/pending` page, the `Delayed Until` is equal to the time in each loop.This makes me think there's no mistake in the job. Util I found out all jobs were fired in last job's delay time.

I don't know how it worked like this, but solution is use different Carbon object in loop:
```php
DB::beginTransaction();
for ($i = 0; $i <= 23; ++$i) {
    TestJob::dispatch($id)->delay(Carbon::now()->addSeconds($i * 20));
}
DB::commit();
```
or
```php
DB::beginTransaction();
$now = Carbon::now();
for ($i = 0; $i <= 23; ++$i) {
    TestJob::dispatch($id)->delay($now->addSeconds(20));
    $now = $now->copy();
}
DB::commit();
```

**Comment by joni2back** [comment]
In my experience with this issue, in our particular case it was caused by a Redis cache flush that unintentionally affected the Redis database used for queues/scheduling.

We were using Redis both as cache and queue driver, with scheduled jobs being stored in a specific Redis database (e.g. database 1). At some point, a `FLUSHDB`/`FLUSHALL` operation (triggered from the cache layer) ended up clearing that database as well.

As a result, all pending/scheduled jobs were silently lost, since Redis is an in-memory store and there was no persistence or backup mechanism in place for those jobs.

From the application perspective, it looked like Laravel simply stopped running scheduled jobs or that they "disappeared", but the root cause was actually external: the Redis data holding the scheduled jobs had been wiped.

So if anyone is experiencing similar behavior (scheduled jobs missing or not being executed), it's worth checking:
- whether Redis is shared between cache and queue
- which Redis database index is being used for each
- and whether any cache clearing operation could be impacting the queue database

In our case, isolating cache and queue into different Redis databases (and avoiding global flush commands) resolved the issue.
