### ISSUE TITLE
Factory model issue using create method with each method concatenated

### ISSUE THREAD

**Issue by pabloleone** [laravel/framework#20615]
- Laravel Version: 5.2.0
- PHP Version: 7.1.5
- Database Driver & Version: mysql 5.6

### Description:

Writing tests I found that model factory `create` method has two different behaviours depending on what you concatenate to it.

### Steps To Reproduce:

Doing the following:

```
factory(Service::class)->create([
    'status_inheritance' => false
])->each(function ($service) use ($data) {
	factory(Status::class)->create(['service_id' => $service->id]);
});
```

The var `$service` inside the closure gets an instance of the service created by the factory, but the instance doesn't take into account the array passed to the `create` method, so the service is stored based on what the factory is set up to.

While doing the following:

```
$s3 = factory(Service::class)->create([
    'status_inheritance' => false
]);
factory(Status::class)->create(['service_id' => $s3->id]);
```

Works as expected. Now the `$s3` var contains a service instance, but this time with the `status_inheritance` set to `false`.

This is the factory:

```
$factory->define(Service::class, function ($faker) {
    return [
        'name'                   => $faker->name,
        'subscription_available' => $faker->boolean(50),
        'status_inheritance'     => rand(0, 1)
    ];
});
```

Because the `status_inheritance` was set to a random value, the tests passed randomly, which made it harder to debug.

### Conclusion

I take this as a bug because the `create` method behaves differently based on what you concatenate to it.

**Comment by themsaid** [comment]
5.2 is not supported anymore, please upgrade to 5.4 and test again.
