### ISSUE TITLE
Dispatch a delayed job to redis

### ISSUE THREAD

**Issue by manfield** [laravel/framework#20612]
- Laravel Version: 5.3.31
- PHP Version: 7.0.17

### Description:
We're experiencing a bug:
when dispatching a delayed job (thus, after calling delay method on a job object), and we use redis driver to enqueue jobs, the job is not passed (or written) to the Redis database.
Using database driver for queues makes it work as expected.

### Steps To Reproduce:
- Enable Redis 
- Configure Laravel in order to use Redis as queue driver
- Create a delayed job and call dispatch method to pass it to the queue manager
- You won't find the record in Redis database

**Comment by themsaid** [comment]
5.3 is not supported anymore, please upgrade to 5.4 and test again.

**Comment by abbood** [comment]
@themsaid are you saying that laravel 5.3 _doesn't_ support delayed jobs on a redis queue?
