### ISSUE TITLE
Error when including sub-view with specific variable value / Blade

### ISSUE THREAD

**Issue by scofield-ua** [laravel/framework#20621]
- Laravel Version: 5.4.30
- PHP Version: 7.1.0

### Description:
Hello. I'm getting error when I'm trying to include sub-view with variable value that contains `:)` string.
Error message:
```
FatalErrorException
Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: Parse 
error: syntax error, unexpected '__data' (T_STRING), expecting ']' (View: home.blade.php)
```

### Steps To Reproduce:
Just inlcuded some sub-view:
```
@include("parts.hello", ["text" => "Hello :)"])
```

Workaround it's to replace `)` with `&#41;`, but still.

**Comment by ntzm** [comment]
Duplicate of #18317
