### ISSUE TITLE
Many To Many relation load all not related data, when calling from boot method

### ISSUE THREAD

**Issue by kprovorov** [laravel/framework#20622]
- Laravel Version: 5.4.33
- PHP Version: 7.1.1
- Database Driver & Version: mysql 5.6.35

### Description:
I have a next models in my app: User, Role, Article and Comment
User and Roles are related by Many To Many relation
Article is related to Comment by Has Many relation

I create example user and attach him one of a few roles.

Then in model Comment in boot method i add the next code (i was need my logic to depends from user role):
```php
    protected static function boot()
    {
        parent::boot();

        $user = User::find(1);

        dd($user->roles);
    }
```
and when i call something like `Article::with('comments')->get();` it show **all roles**, exists in database, except of show **only one** role, that is attached to my user.

### Steps To Reproduce:
I make some example app to reproduce: https://github.com/kprovorov/laravel-boot-relation
install as usual, and run migration with seed. Then go to mainpage

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.

**Comment by themsaid** [comment]
hint: while the model is booting up, don't attempt to use it since it's not ready yet.
