### ISSUE TITLE
Cannot Delete Model Records 

### ISSUE THREAD

**Issue by lukepolo** [laravel/framework#20637]
- Laravel Version: 5.4.33
- PHP Version: 7.1.8
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.7.18

### Description:

I am unable to delete records with a Eloquent Model

### Steps To Reproduce:

Create a model , and try to delete

```
My Code : 
  $serverCommands = ServerCommand::whereIn('server_id', $site->servers->pluck('id'))
            ->where('started', false)
            ->where('failed', false)
            ->where('completed', false)
            ->get(); // i've tried using delete here too (fails as well)

  foreach($serverCommands as $serverCommand) {
            dump('Deleting '.$serverCommand->id);
            dd('Results : '.$serverCommand->delete());
        }
```

I placed some dumps  so I could see whats actually happening  : `vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php`

![image](https://user-images.githubusercontent.com/2066668/29487204-a7057610-84c3-11e7-8d4e-1cb8312ecf8f.png)

Here are the Results : 

![image](https://user-images.githubusercontent.com/2066668/29487205-ac2f9300-84c3-11e7-94ba-7b3ee4cbd70b.png)

I've also tried doing something like 

`\DB::table('server_commands')->where('id',18)->delete();`

Which also fails.

Any advise would be gratefully appreciated

**Comment by n7olkachev** [comment]
Maybe you recreate this model somehow?

**Comment by brunogaspar** [comment]
Seems to be working perfectly fine for me.

PHP 7.1.8
Laravel 5.4.33
MySQL 5.7.19

@lukepolo Have you tried a fresh Laravel 5.4 project to see if you could reproduce the issue there?

**Comment by lukepolo** [comment]
Yah I figured as much. But have no idea what could be wrong, as manually
running the query work fine. I will try on another computer to see what
happens.

**Comment by lukepolo** [comment]
Yah its my machine. Will see if I can find the issue.  and post back here~
