### ISSUE TITLE
Cache memory leak and false positive in RateLimiter

### ISSUE THREAD

**Issue by halaei** [laravel/framework#20641]
- Laravel Version: 5.4
- Cache Drivers: Redis / APC

### Description:
```php
class RateLimiter
{
    /**
     * Increment the counter for a given key for a given decay time.
     *
     * @param  string  $key
     * @param  float|int  $decayMinutes
     * @return int
     */
    public function hit($key, $decayMinutes = 1)
    {
        //step 1: add
        $this->cache->add($key, 1, $decayMinutes);
        //step 2: increment
        return (int) $this->cache->increment($key);
    }
}
```
Consider this scenario when RateLimiter::hit() is called, 
1. Step 1 of the code above is executed, the key already exists in the cache store, but it is going to get expired in half a second.
2. One second is passed before execution of step 2. Hence the key is now expired.
3. Step 2 of the code is executed. Since the key is not present, the key will be added back with value 1, and most importantly infinite time to live.

As a result:
1. If hit with the same key get called enough, eventually (maybe after a year!) a "too many attempt" will get detected, possibly a false positive. As a result the key will be removed from the cache by `resetAttempts()` function.
2. Otherwise, the key will be inside the cache server forever. This can be a serious memory leak depending on the cache server configurations.

**Comment by halaei** [comment]
For one specific high traffic application, this bug added 800 forever persistent keys into Redis in 2 weeks.

**Comment by halaei** [comment]
Regarding #20643 I think of changing increment() and decrement() signature by adding a third argument:
```php
    /**
     * Increment the value of an item in the cache.
     *
     * @param  string  $key
     * @param  mixed  $value
     * @param int $seconds
     * @return int|bool
     */
    public function increment($key, $value = 1, $seconds = 0)
    {
    }
```
$seconds to expire is already supported in memcached. For other drivers, implementation seems to be possible.

**Comment by themsaid** [comment]
> One second is passed before execution of step 2. Hence the key is now expired.

One minute you mean? why would 1 whole minute pass between the two lines?

**Comment by halaei** [comment]
@themsaid No. 1 second.

**Comment by halaei** [comment]
Please also note that `$decayMinutes` can be as small as 1/60, representing 1 seconds. The lower the value of `$decayMinutes` the higher the chance of memory leak.

**Comment by themsaid** [comment]
i see your point now, thanks :)

**Comment by laurencei** [comment]
So it sounds like we need an option for "increment" to have a configurable expiring time, rather than defaulting to forver?

**Comment by n7olkachev** [comment]
And also we need to make `Database` and `Memcached` `increment` method behave like `Redis` and other ones (`increment` should create a key if it doesn't exist).
