### ISSUE TITLE
[5.4] Eloquent save-query with protected $withCount eager load on polymorphic relation fails

### ISSUE THREAD

**Issue by patrickbrouwers** [laravel/framework#20640]
- Laravel Version: 5.4.33 (but also in 5.5-dev)
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7.19

### Description:

Updating an Eloquent model with a default withCount eager load on a polymorphic relation fails. 

### Steps To Reproduce:

```
class Post extends Model
{
    protected $withCount = ['photos']);

    public function photos()
    {
         return $this->morphMany(Photo::class, 'imageable');
    }
}
```

```
class Photo extends Model 
{
    public function imageable()
    {
        return $this->morphTo();
    }
}
```

```
$post = Post::find(1);

// Dumps "Old name"
dump($post->name);

$post->update(['name' => 'New name']);

$post->fresh();

// expected: New name
// actual: Old name
dump($post->name);
```

MYSQL query:

`UPDATE ... where `id` = App\Post`

### Failing Test:

(I'm happy to PR a failing test if it makes things easier)

In DatabaseEloquentIntegrationTest:

Add a withCount to the model: photos relation is polymorphic.

```
class EloquentTestPostWithPhotosCount extends EloquentTestPost
{
    protected $withCount = ['photos'];
}
```

Try to update any attribute of that model.
```
public function testCanUpdateWhenModelHasWithCountEagerLoad()
    {
        $post = EloquentTestPostWithPhotosCount::create(['name' => 'Some Post', 'user_id' => 1]);
        $post->photos()->create(['name' => 'Hero 1']);
        $post->photos()->create(['name' => 'Hero 2']);

        $post = EloquentTestPostWithPhotosCount::find($post->getKey());

        $post->update([
            'name' => 'New Name',
        ]);

        $databasePost = EloquentTestPostWithPhotosCount::find($post->getKey());

        $this->assertEquals($post->name, $databasePost->name);
    }
```

MySQL will give the following error:

```
Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 25 bind or column index out of range (SQL: update "posts" set "name" = New Name, "updated_at" = 2017-08-19 17:44:37 where "id" = Illuminate\Tests\Database\EloquentTestPostWithPhotosCount)
```

The query contains a strange condition:

`where "id" = Illuminate\Tests\Database\EloquentTestPostWithPhotosCount`

### Steps To Work Around The Problem:

By not using  `protected $withCount = ['photos'];` and only calling it via `$query->withCount('photos')`. 

However as this `$withDefault` property exists on the model class, I would assume it would work with updating the model as well. For my specific use-case I can work around it, but it toke me a while to figure out why my model didn't update.

### Possible solution

Remove the `->with()` and `->withCount()` when it's a `save()` query: this fixes this use-case.

I tried doing this as a PR, but a lot of tests fail; I'm not sure of the impact of this.

```
    public function save(array $options = [])
    {
         $builder = $this->newEloquentBuilder($this->newBaseQueryBuilder());

        // Once we have the query builders, we will set the model instances so the
        // builder can easily access any information it may need from the model
        // while it is constructing and executing various queries against it.
        $query = $builder->setModel($this)

}
```

**Comment by brunogaspar** [comment]
Having the exact same issue.

**Comment by atehnix** [comment]
Me too.

**Comment by brunogaspar** [comment]
@themsaid Any chance to look into this issue please?

**Comment by themsaid** [comment]
This is fixed in a recent PR

**Comment by brunogaspar** [comment]
Awesome, thanks @themsaid !
