### ISSUE TITLE
cache:clear flushes redis db

### ISSUE THREAD

**Issue by n7olkachev** [laravel/framework#20655]
`cache:clear` command flushes redis db completely, including sessions, while it's supposed to clear just cache.
Could we change default keys prefix for cache and sessions, something like `laravel:cache` and `laravel:sessions`?

**Comment by themsaid** [comment]
It's advised to use different redis databases for different cases, sessions, cache, queue, etc...

**Comment by n7olkachev** [comment]
Can't find this advise anywhere in docs.
Anyways, I think that there should be some separation by default. Just one more thing not to think about :)

**Comment by themsaid** [comment]
Yeah we'll mention this by the release of 5.5, since Horizon queue must be housed in a separate DB.

**Comment by n7olkachev** [comment]
Nice, thanks!

**Comment by barryvdh** [comment]
So is it mentioned now? I see this:
https://laravel.com/docs/5.5/cache#removing-items-from-the-cache
> Flushing the cache does not respect the cache prefix and will remove all entries from the cache. Consider this carefully when clearing a cache which is shared by other applications.

It doesn't mention this. Also, the CacheManager etc uses the same connection by default, so it is a bit confusing. Especially when deployments usually clear the cache for a new release, but that would drop all queues?
