### ISSUE TITLE
Hash::check isnt working as it should

### ISSUE THREAD

**Issue by ScooterSam** [laravel/framework#20659]
- Laravel Version: 5.4.?
- PHP Version: 7.1
- Database Driver & Version: MySQL

### Description:
I'm using default Laravel auth, I registered, it auto logged in. I then logged out, and went to login again. It was saying invalid credentials. 
I have APP_KEY set in my .env. 

When I try to run Hash::check on the user password, it returns false. 
But when I try to do Hash::make, then Hash::check on that hash, it returns true.  I'm 100% using the function correctly.
From what I know, nothing has been changed with the default Auth. I feel like this started happening after coding password changing for users. However... I did comment out all routes other than auth to ensure nothing was impacting this. 
I've searched a tonne, and tried lots of different things, but nothing has helped.

EDIT: 
Just tried something else; Generating a Hash, then force setting it into my database, then logging in. This works fine.

### Steps To Reproduce:
I'm unsure.
Register, Logout, Login?

**Comment by n7olkachev** [comment]
Maybe there is a problem in a way how you store hash?

**Comment by Dylan-DPC** [comment]
Can you provide some more information? Like steps to reproduce?

**Comment by ScooterSam** [comment]
@n7olkachev It's default Laravel Auth, I don't store the hash personally.

@Dylan-DPC Unfortunately not, I don't know how the issue started to happen. As I say, I registered, logged out, then attempted to login again, password no longer works :/

**Comment by ScooterSam** [comment]
Ahhh I feel like such a tool. 

When i setup password changing, I added this to my user Model

`
	public function setPasswordAttribute($value)
	{
		$this->attributes['password'] = Hash::make($value);
	}
`

So when a user registers, the password is hashed twice... Sorry for any wasted time!
