### ISSUE TITLE
Make Markdown emails testable.

### ISSUE THREAD

**Issue by markwalet** [laravel/framework#20665]
I am following the test driven laravel course of Adam Wathan. He is using normal email templates and those are testable.

It is almost impossible to render markdown views in a test. 

For testing purposes it would be great if the `markdown` property could also be public. Just like the `view` property.

So I could use the following code:

```
$email = new ResetPasswordEmail();
$markdown = new Markdown(view(), config('mail.markdown'));

return $markdown->render($email->markdown);
```

This is only a example. ~~Maybe~~ Probably there is a better way to solve this.

**Comment by markwalet** [comment]
Something like a public `render()` method would probably work better.

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
