### ISSUE TITLE
NotificationFake should trigger event NotificationSent

### ISSUE THREAD

**Issue by jschlies** [laravel/framework#20675]
- Laravel Version: 5.4.*
- PHP Version:7.1.2
- Database Driver & Version: mysql 5.7.17

Description:

Illuminate\Support\Testing\Fakes\NotificationFake->sendNow() should trigger \Illuminate\Notifications\Events\NotificationSent()

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
