### ISSUE TITLE
NotificationFake->sendNow() should offer a way to change/inject the event triggered. 

### ISSUE THREAD

**Issue by jschlies** [laravel/framework#20676]
Laravel Version: 5.4.*
PHP Version:7.1.2
Database Driver & Version: mysql 5.7.17
Description:

Illuminate\Support\Testing\Fakes\NotificationFake->sendNow() should offer a way to change/inject the event triggered. Currently triggers a hardcoded \Illuminate\Notifications\Events\NotificationSent()

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.

**Comment by jschlies** [comment]
thanks
