### ISSUE TITLE
useStoragePath in AppServiceProvider

### ISSUE THREAD

**Issue by TechKat** [laravel/framework#20686]
- Laravel Version: 5.4.33
- PHP Version: 7.0.22-0ubuntu0.16.04.1
- Database Driver & Version: 10.1.25-MariaDB-1~xenial

### Description:
I've been reading different ways of doing this, but none of the solutions seem to be working.
At some point in my app, I want to be able to add an .env editor, and in my .env is a path to my preferred storage location. (e.g /data/dev/storage)

What is the best way to use the useStoragePath method, but to also call the .env value that is the path? (e.g env('APP_STORAGE'))

### Steps To Reproduce:
Tried `$this->app->useStoragePath(env('APP_STORAGE'));` in `AppServiceProvider::register` - no changes
Tried `$app->useStoragePath(env('APP_STORAGE'));` in `bootstrap/app.php` - can't pull env value
Tried `$app->useStoragePath('/my/preferred/path');` in `bootstrap/app.php` - this worked, but was not my preferred option.

Any ideas?

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
