### ISSUE TITLE
[5.4] url() function doesn't remove index.php in generated url

### ISSUE THREAD

**Issue by LordApo** [laravel/framework#20687]
- Laravel Version: 5.4 (latest)
- PHP Version: 7.0 & 7.0
- Database Driver & Version: No DB

### Description:

If access my website normally ( http://www.exemple.com ), the following url is generated:
http://www.exemple.com/contact Wich is good.

But if access my website with a index.php at the end ( http://www.exemple.com/index.php ) , I have this:
http://www.exemple.com/index.php/contact Resulting in 404 errors and CSS not loading

I tried on my main server (Apache2 + PHP7.0) and on a second server with Scaleway's ImageHub LEMP Stack (Nginx + PHP7.1).

### Steps To Reproduce:

- Install Laravel.
- Put a link with url() function (egg: `{{ url('cart/checkout') }}`).
- Access the website both normally and with an index.php in the end and see the difference.

**Comment by themsaid** [comment]
You can add this to your nginx file to prevent access on index.php

```
if ($request_uri ~* "^(.*/)index\.php/?(.*)") {		
    return 301 "\$1\$2";		
}
```

Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
