### ISSUE TITLE
[5.x] Missing OPTIONS HTTP verb in Route::any

### ISSUE THREAD

**Issue by Sanfra1407** [laravel/framework#20697]
#### Affected versions:
- 5.1
- 5.2
- 5.3
- 5.4
- 5.5

#### Description:
OPTIONS verb is missing from `Route::any()` and it's not handled by `any()`.

To do that you have to write:
`Route::match(['get', 'head', 'options', 'post', 'put', 'patch', 'delete'], 'orders/{customer_id}', 'OrdersController@getOrders');`

instead of

`Route::any('orders/{customer_id}', 'OrdersController@getOrders');`

#### Files:
`vendor/laravel/framework/src/Illuminate/Routing/Router.php`

**Comment by themsaid** [comment]
This was discussed many times, please search the issues history.
