### ISSUE TITLE
clean session before new login

### ISSUE THREAD

**Issue by RafaelKr** [laravel/framework#20703]
- Laravel Version: 5.4

I hope this is the correct place to post this.

I had a look at the `login`-method of `auth()`. https://github.com/illuminate/auth/blob/master/SessionGuard.php#L409
In theory it's possible to call this method while another user is still signed in. I think this should be checked when `login` is called and if this is the case then logout should be called to clean up the session before proceeding with the login.

If I missed something, please notify me and close this issue, thanks.

**Comment by Kyslik** [comment]
>In theory it's possible to call this method while another user is still signed in.

What does that mean?

---

I think application should handle this not Guard. Did user ever logged out - clear session, did he not? let session invalidate itself after X amount of time (config setting).

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
