### ISSUE TITLE
[5.5] Releasing Lock correctly

### ISSUE THREAD

**Issue by alibo** [laravel/framework#20709]
- Laravel Version: 5.5.0-dev

### Description:

If process A acquires a lock and takes longer than usual (longer than `Lock::$seconds`), the acquired lock will be expired and process B can acquire another lock. when process A is finished, it will remove the lock which has been already acquired by process B.

**More info & Solutions:**

Redis:

- https://redis.io/topics/distlock (Section: `Correct implementation with a single instance`)
- https://github.com/symfony/lock/blob/master/Store/RedisStore.php

Memcached:

- http://php.net/manual/en/memcached.cas.php
- https://github.com/symfony/lock/blob/master/Store/MemcachedStore.php

### Steps To Reproduce:

```php
// process A
$lock = new RedisLock($redis, 'lock', 1);
$lock->block();

// A heavy process/request timeout > 1 second

$lock->release();
```

```php
// process B

$lock = new RedisLock($redis, 'lock', 1);
$lock->block();

// unsafe

```

### Changes

- The abstract class `Lock` should be changed because method `acquire` should return a unique value and also, method `release` should accept an argument for this unique value. Or we can use another class like [`Symfony\Component\Lock\Key`](https://github.com/symfony/lock/blob/master/Key.php) to keep the token.

So WDYT?

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.

**Comment by themsaid** [comment]
Basically the point here is that you should pick your lock timeout based on the process estimate maximum execution time.
