### ISSUE TITLE
artisan key:generate claims key set successfully when it has not been written to .env file

### ISSUE THREAD

**Issue by pwaring** [laravel/framework#20719]
- Laravel Version: 5.4.33
- PHP Version: 7.0.22-0ubuntu0.16.04.1
- Database Driver & Version: MySQL/MariaDB 10.0.31

### Description:

Running `php artisan key:generate` in a Laravel project where the `.env` file does not contain an `APP_KEY=` line results in the following output:

`Application key [base64:KEY_HERE=] set successfully.`

However, the key is not written to the `.env` file, so the status message is incorrect.

### Steps To Reproduce:

 1. Create a `.env` file without an `APP_KEY=` line.
 1. Run `php artisan key:generate`
 1. Run `grep APP_KEY .env` - no output.

### Possible fixes

I can think of two ways to improve this for the user:

 1. Have `key:generate` check whether `APP_KEY` exists after generating the key, and display an error message if it does not exist or match the key which was generated.
 1. Append the relevant `APP_KEY` to `.env` if the line does not already exist, perhaps with a slightly different output message to make it clear that this has happened.

Unfortunately I'm new to Laravel so don't feel confident providing a patch to a piece of core functionality.

**Comment by themsaid** [comment]
It assumes a .env `APP_KEY=` line exists, since the shipped .env.example file contains it.

**Comment by pwaring** [comment]
The reason I opened this issue though is that `key:generate` shouldn't make that assumption, as it's not guaranteed to be true. Making a false assumption results in a incorrect status message to the user.

**Comment by themsaid** [comment]
https://laravel.com/docs/5.4/installation

<img width="686" alt="screen shot 2017-08-24 at 8 59 27 pm" src="https://user-images.githubusercontent.com/4332182/29683468-c64e76e4-890e-11e7-9042-3b769c749832.png">

This is mentioned in the installation guide.

However I see your point, feel free to open a PR if you want.

**Comment by melvinmt** [comment]
In my case, there was no .env.example file (I created the project with `laravel new <app-name>`) so I had to figure out the APP_KEY thing myself.

**Comment by devcircus** [comment]
"laravel new" creates the .env file and sets the key automatically. The only time you should ever have to deal with this manually, is if you clone(or otherwise copy) an existing project.

**Comment by Smyja** [comment]
> "laravel new" creates the .env file and sets the key automatically. The only time you should ever have to deal with this manually, is if you clone(or otherwise copy) an existing project.

In which case what happens? Which directory exactly would the command be ran

**Comment by shubham-agr** [comment]
I generated the key.
It is in .env file. 
**APP_KEY=base64:{value}**
But still the application says 
**RuntimeException
No application encryption key has been specified..**

**Comment by shubham-agr** [comment]
> I generated the key.
> It is in .env file.
> **APP_KEY=base64:{value}**
> But still the application says
> **RuntimeException No application encryption key has been specified..**

I solved this by cache command.
php artisan config:cache

**Comment by 0length** [comment]
> 
> 
> > I generated the key.
> > It is in .env file.
> > **APP_KEY=base64:{value}**
> > But still the application says
> > **RuntimeException No application encryption key has been specified..**
> 
> I solved this by cache command.
> php artisan config:cache

i have same problem.. but this comand not working for me .. and I was frustrated then i hardcode the key in config / app.php

**Comment by bobylito** [comment]
Hi there,

I was going to create a new issue for that :) Hopefully GitHub hinted me to this issue. I have stumbled into the same issue. The main problem is DX: the message is misleading and a warning message in the doc is simply not enough since we're not likely to read it...

I'm having a look at the code right now, and I hope I can contribute something here 👍

**Comment by f4z3k4s** [comment]
This message is still totally misleading and it should generate APP_KEY even if key had not pre-existed in .env file.

**Comment by TobbyBlaze** [comment]
If it still does not generate the app key,rename the .env.example to something else, delete the APP_KEY line from your .env file and just run `php artisan optimize`, your cache will be cleared. Then run `php artisan key:generate` again. Check your .env file afterwards, you should definitely get your APP_KEY set to your new app key now.

You are facing that problem because php has already cached your app key in the system and unable to append your new app key to your .env file.

I hope this helps you.

**Comment by emads3** [comment]
Still have the same issue and tried all the solutions

**Comment by zavre-c** [comment]
> If it still does not generate the app key,rename the .env.example to something else, delete the APP_KEY value in your .env file and just run `php artisan optimize`, your cache will be cleared. Then run `php artisan key:generate` again. Check your .env file afterwards, you should definitely get your APP_KEY set to your new app key now.
> 
> You are facing that problem because php has already cached your app key in the system and unable to append your new app key to your .env file.
> 
> I hope this helps you.

Hey
I didn't understand why or how this happens
how php has cached key already
