### ISSUE TITLE
Recent change for callables in model factories attributes breaks existing factories

### ISSUE THREAD

**Issue by Crinsane** [laravel/framework#20718]
- Laravel Version: 5.4.34
- PHP Version: 7.0.8
- Database Driver & Version: SQL server

### Description:
The recent change to add support for callables in model factories attributes broke our testsuite. https://github.com/laravel/framework/pull/20692
I filtered the problem down to the change made in this commit https://github.com/laravel/framework/commit/91765f5a35a6410d6315042638721242ed0e9c5f where it checks if the attribute you give the factory is a callable.
In one of our factories, a possible value of an attribute is `DIR`, and it PHP will tell you this is callable (the `dir()` global function). So it will try to call `dir()` and pass it the attributes array, which will result in an exception: `dir() expects parameter 1 to be a valid path, array given`

### Steps To Reproduce:
1) Create a model factory
2) Set one of the attributes to some global function name
3) Try to use the factory and see it fail

**Comment by themsaid** [comment]
fixed

**Comment by Crinsane** [comment]
Thanks a lot!
