### ISSUE TITLE
Auth::onceUsingId destroying session

### ISSUE THREAD

**Issue by rorc** [laravel/framework#20722]
- Laravel Version: 5.4.33

### Description:
Have a simple controller:
```php
class ProfileController extends Controller
{
    public function impersonate(User $user)
    {
        \Session::put('impersonate', $user->id);

        return redirect()->home();
    }
}
```
And simple middleware:
```php
class Impersonate
{
    public function handle($request, Closure $next)
    {
        if (\Session::has('impersonate')) {
            \Auth::onceUsingId(\Session::get('impersonate'));
        }

        return $next($request);
    }
}
```
After visit `impersonate` action, `Impersonate` middleware hits and i see proper result (data for user from `Session::get('impersonate')`). Its work http://joxi.ru/gmveypzUxBn40r 😃
But after press F5, my session key `impersonate` dissapear, i tottaly logout and redirect to login form http://joxi.ru/Vm6b8Zlcx0bM8m 😕

**Comment by Dylan-DPC** [comment]
You already made this issue in #20584 and it was closed with a valid reason. Why did you create a new issue with same stuff?

**Comment by rorc** [comment]
In this issue i formulated problem clearly.
> It doesn't even touch the session, something else must have flushed your session.

Its not valid readon.

**Comment by Dylan-DPC** [comment]
no this was the reason given:

> That's expected, onceUsingId logs you in in the current request only.

**Comment by rorc** [comment]
Yea, but why `onceUsingId` removes my custom session key?
I will not delete it manually.

**Comment by themsaid** [comment]
@rorc please don't duplicate issues, I couldn't replicate your issue and neither do @Dylan-DPC. My sessions are not flushed when I use `onceUsingId`. Since no body can duplicate the issue using the given steps it's most probably a misconfiguration on your side.

Please try in a fresh laravel application to make sure it's not something in your project.
