### ISSUE TITLE
WhereIn JSON

### ISSUE THREAD

**Issue by CrixuAMG** [laravel/framework#20721]
- Laravel Version: v5.4.30
- PHP Version:7.1
- Database Driver & Version:MySQL 5.7

In the documentation is written that we can use something like `Table::where('name->en', 'test')->get();`.
I want to do this basically: `Table::whereIn('name->en', ['test_1', 'test_2'])->get();`, however, this does not yield any results.
If I do `toSql()` and run the query with and without the whereIn section, I can see that without I get results as expected (though of course not filtered), but I get nothing when using the whereIn part of the query.
I also get an error stating: `Invalid JSON path expression. The error is around character position 1.`.
The data in the tables is valid JSON.

**Comment by themsaid** [comment]
Yes it doesn't work with whereIn at the moment :)

**Comment by CrixuAMG** [comment]
`and `categories`.`name`->'en' in ('Mari Cruz', 'Sacha Mccoy', 'Ramona Berry', 'Alice Buckley');`
Using `spatie/laravel-translatable` for the name, the column has data something like `{"en":"Alice Buckley"}`

**Comment by morloderex** [comment]
I don't think that json columns is supported with the IN operator [See this for reference](https://dev.mysql.com/doc/refman/5.7/en/json.html)

**Comment by CrixuAMG** [comment]
@morloderex please read this section: [https://laravel.com/docs/5.4/queries#json-where-clauses](https://laravel.com/docs/5.4/queries#json-where-clauses) :)

**Comment by Omranic** [comment]
Just encountered the same issue yesterday, and was looking for some hope but not much mentioned on this issue. It seems to be something related to **MySQL** itself since running the raw query directly in MySQL server doesn't return any result set.

**Comment by fede91it** [comment]
What about changing the whereIn behavior surrounding each value with double quotes?
That will work for our purposes until MySQL solves its issue.
