### ISSUE TITLE
Route::resource overrides already defined Route::resource for given Model

### ISSUE THREAD

**Issue by eithed** [laravel/framework#20728]
- Laravel Version: 5.3
- PHP Version: 7.1

### Description:

I'm in the middle of separating routes in already existing system - so far the resource groups were separated by route files (all following routes are defined within `routes/admin.php`, so they don't clash with frontend routes), though we're moving towards additional separation via URL as well. To illustrate - route for URL: `/admin/journeys/123/show/` exists as:

```
Route::group(['prefix' => 'admin'], function(){
Route::resource('journeys', '\App\Http\Controllers\Admin\JourneyController');
});
```

which generates defined routes, amongst them `journeys.show`. Additionally, for time being, I'm adding:

```
Route::group(['as' => 'admin.', 'prefix' => 'admin'], function(){
Route::resource('journeys', '\App\Http\Controllers\Admin\JourneyController');
});
```

which generates defined routes, amongst them `admin.journeys.show`. The problem is that it overrides already existing resource routes - route list shows that my `journeys.show` doesn't exist anymore. The desired behaviour is to have them exist alongside.

### Steps To Reproduce:

1. Create `resource` route for given model
2. Create another `resource` route for given model within `'as' => 'prefix.'` group

**Comment by rgehan** [comment]
I can't reproduce your issue on a fresh install of Laravel 5.3.

I created a `Car` model and two resources controller:
- `\App\Http\Controller\CarsController`
- `\App\Http\Controller\Admin\CarsController`

I've then created the routes like so:
```php
<?php

Route::resource('cars', '\App\Http\Controllers\CarsController');

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function() {
    Route::resource('cars', '\App\Http\Controllers\Admin\CarsController');
});
```

Routes list:
![capture d ecran 2017-08-26 a 05 54 48](https://user-images.githubusercontent.com/793402/29738452-1b14754c-8a23-11e7-85e4-401caeaaf016.png)

**Comment by eithed** [comment]
That's because you're creating two routes that point to two different controllers that handle the same Model. As in OP, I'm generating routes as so:

```
Route::group(['prefix' => 'admin'], function(){
	Route::resource('journeys', '\App\Http\Controllers\Admin\JourneyController');
});

Route::group(['as' => 'admin.', 'prefix' => 'admin'], function(){
	Route::resource('journeys', '\App\Http\Controllers\Admin\JourneyController');
});
```

Route list:
[img]http://i.imgur.com/hcYI4E2.png[/img]

I can't go through all existing controllers and template files and change `route('journeys.show')` to `route('admin.journeys.show')` (it will happen at some point though), and hope there's a functionality that enables me to do so.

**Comment by rgehan** [comment]
You're using the same prefix two times, which generates two times the same URI.
You can't have the same URI pointing to two different things (even though in your case it seems to be the same thing: the same method on the same controller).

If I'm following you, you just have duplicate routes. 

Did I miss something in your initial explanation ?

**Comment by eithed** [comment]
Let me try to explain one more time - there's a named route `journeys.show` that is generated by:

```
Route::group(['prefix' => 'admin'], function(){
	Route::resource('journeys', '\App\Http\Controllers\Admin\JourneyController');
});
```

used in unknown number of places in both templates and controllers; it resolves to `admin/journeys/123/`.

I want to add `admin.journeys.show` and use it per `route('admin.journeys.show', $whatever)` and resolve to `admin/journeys/123/`. However, if I'll add it to existing route list, per:

```
Route::group(['prefix' => 'admin'], function(){
	Route::resource('journeys', '\App\Http\Controllers\Admin\JourneyController');
});

Route::group(['as' => 'admin.', 'prefix' => 'admin'], function(){
	Route::resource('journeys', '\App\Http\Controllers\Admin\JourneyController');
});
```

the second declaration will overshadow the first one. I want to be able to use both `journeys.show` and `admin.journeys.show` to point to the same controller, and resolve to the same URL.

**Comment by rgehan** [comment]
So you basically need some kind of way to alias a route ?

**Comment by eithed** [comment]
Yes indeed :)

**Comment by themsaid** [comment]
Laravel 5.3 is not supported, please test on 5.5 and report if your issue still exists.

Thanks
