### ISSUE TITLE
SyncJob does not increment attempts counter

### ISSUE THREAD

**Issue by vyuldashev** [laravel/framework#20734]
- Laravel Version: 5.4
- PHP Version: 7.1

### Description:
[SyncJob](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Queue/Jobs/SyncJob.php#L59) always returns 1 for attempts. Hence, it does not increment when release method is called. 

### Steps To Reproduce:

In any test class:

```
$job = new ExampleJob();

dispatch($job);
$job->attempts(); // returns 1

dispatch($job); // or $job->release()

$job->attempts(); // returns 1, but it it’s not correct
```

### Why do I need it

In my job there is some logic that checks that job attempts === 1, then code x is run, if attempts > 1 it is required to run another code. You should get the point. 

Tests are being executed using sync queue driver and the only solution now to make it work is to create class in tests that extends required Job and has public attempts property which in tests is overridden to desired value. Looks like a dirty solution. 

Also, release method should execute SyncJob again. 

### Conclusion

If this feature can be accepted I will make a PR. Waiting for a feedback.

**Comment by laurencei** [comment]
You can easily simulate this with database jobs. In your tests, insert a raw job directly into the database with `attempts = 2` or something - then process the job in your test.

I do this all the time to simulate different "states" of queues during tests.

I dont like the idea of sync jobs trying to re-run themselves. It's likely to lead to all sorts of unintended side effects in current code - I can just see it breaking things...

**Comment by laurencei** [comment]
Either way - this is probably a better discussion for https://github.com/laravel/internals - open a ticket there for further discussion...

**Comment by vyuldashev** [comment]
@laurencei If I use RabbitMQ for my queue, why do I need a database driver and migration itself?

**Comment by laurencei** [comment]
You said it was for testing. For testing it is common to use mock/alternative drivers to simplify testing.

Anyway - as mentioned - lets move the discussion to  https://github.com/laravel/internals

**Comment by vyuldashev** [comment]
Moved to https://github.com/laravel/internals/issues/754.
