### ISSUE TITLE
Migration failure in SQLite when adding timestamp column to existing table with ->useCurrent().

### ISSUE THREAD

**Issue by davidbankes** [laravel/framework#20747]
- Laravel Version: 5.4.35
- PHP Version: 7.1.8
- Database Driver: SQLite

### Description:
On a migration, when adding a new timestamp column to an already existing table, `->useCurrent()` causes failure of the migration.

Error message in the console: Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1 Cannot add a column with non-constant default (SQL: alter table "pages" add column "published_at" datetime default CURRENT_TIMESTAMP not null).

This seems to be break the rules of the ALTER TABLE syntax for adding columns. See https://www.sqlite.org/lang_altertable.html. Also, https://stackoverflow.com/questions/3642786/doctrine-2-migrations-how-to-alter-a-table-with-a-sqlite-db

It seems like there are a few possibilities:
1. There's a bug in the SQLite grammar that allows it to compile to an invalid SQL statement.
2. The useCurrent should fire a better error when it's used in an ALTER TABLE statement, so that it's easier for the write of the migration to realize what they did wrong.
3. The migration should get around the SQLite limitation somehow.

### Steps To Reproduce:
Use something like the following migration in SQLite on a table that already exists (probably from a previous migration). In my case, I'm doing it in a test with the `DatabaseMigrations` trait in the test. The migration works fine in non-test mode (using MySQL), but fails when I'm running the test. Below is a migration:

```php
<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class ModifyPagesTableAddStatus extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('pages', function (Blueprint $table) {
            $table->timestamp('published_at')->nullable()->useCurrent();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('pages', function (Blueprint $table) {
            $table->dropColumn([
                'published_at',
            ]);
        });
    }
}
```

**Comment by srmklive** [comment]
Laravel uses `doctrine/dbal` to modify sqlite columns. `doctrine/dbal` doesn't support modifying timestamp columns, hence Laravel also doesn't support it. https://laravel.com/docs/5.4/migrations#modifying-columns

**Comment by davidbankes** [comment]
This isn't modifying a column, it's adding a (new) column to an existing table.

From the Laravel documentation, this appears to be a valid use-case that creates invalid code.

**Comment by rs-sliske** [comment]
sqlite doesnt support adding a column with a default value of CURRENT_TIMESTAMP (which useCurrent() will try to do)

 The ADD COLUMN syntax is used to add a new column to an existing table. The new column is always appended to the end of the list of existing columns. The column-def rule defines the characteristics of the new column. The new column may take any of the forms permissible in a CREATE TABLE statement, with the following restrictions:

   * The column may not have a PRIMARY KEY or UNIQUE constraint.
   * The column may not have a default value of CURRENT_TIME, CURRENT_DATE, CURRENT_TIMESTAMP, or an expression in parentheses.
  *  If a NOT NULL constraint is specified, then the column must have a default value other than NULL.
  *  If foreign key constraints are enabled and a column with a REFERENCES clause is added, the column must have a default value of NULL.

**Comment by davidbankes** [comment]
The documentation that I linked to says that. My issue isn't with the limitations of SQLite, per se.

The Laravel documentation makes it sound as if this is a perfectly valid migration. Although I did dig into the SQLite implementation myself (as you can see, I linked to the above documentation), the Laravel documentation caused me to think that the community has worked around the SQLite limitation. If we have not, I think this should documented as an invalid migration. Half the point of the database abstraction is to be able to swap out the implementation, but this means that I cannot. Should we consider documenting the "gotchas" better, or should we find a way around the limitations?

I guess I have an expectation that I can do whatever is in the Laravel documentation without worrying to much about certain implementation details. If I write valid "Laravel" code, shouldn't it work? And so, either this should work, or it should be documented as an invalid use of the migration system? Perhaps my expectation is wrong; I'm open to that, but the foregoing comments haven't addressed my expectations of Laravel; they've pointed to an unrelated doctrine issue, and quoted documentation I already linked to (and read). My issue is with expectations of a presumably valid Laravel migration. Should it be documented as invalid? Or should there be a workaround? Or is my expectation off base?

**Comment by rs-sliske** [comment]
Half the point of the database abstraction is to be able to swap out the implementation, but this means that I cannot

maybe a mention of it in the docs could be useful. but this is one of the places where you run into issues of different vendors which have different functionalities

sqlite has a lot of limitations compared to other drivers, especially when it comes to modifying tables. should laravel stop people setting default values in migrations because sqlite cant handle that in certain situations?

**Comment by themsaid** [comment]
For suggestions and feature requests let's use the https://github.com/laravel/internals repo.
