### ISSUE TITLE
Inconsistent "find" eloquent function operation

### ISSUE THREAD

**Issue by ginzunza** [laravel/framework#20740]
- Laravel Version: 5.4.35
- PHP Version: 7.0.15
- Database Driver & Version: "yajra/laravel-oci8": "^5.4.9"

### Description:
When I create queries like this: "Model::find(1)" it returns one result with all my model's columns, which is fine. When I try the next query: "Model::find(1)->with("another_model")" the behavior is equivalent to "select * from model", but I expect a behavior equivalent to "select * from model where id = 1", apparently the result doesn't consider the previous filter (find).
If I try to do the same thing with the following query: "Model::where("id",1)->with("another_model")" it returns what I expect. ¿What is wrong with the concatenation when I'm using "find"?. ¿Is there an explanation about this behavior?.
I attached an image with my evidence
![2017-08-24](https://user-images.githubusercontent.com/12944088/29686740-7fa7e4aa-88f0-11e7-83d8-1d3c01ea3dea.png)

Thanks in advance

**Comment by rs-sliske** [comment]
The difference is that find returns a model, where returns a query builder.

With should only be called on the query builder (use load instead of with for model instances)

Because of how eloquent works if you call builder methods against a model instance it will create a new query builder instance

**Comment by Dylan-DPC** [comment]
This place is for bug tracking only. This isn't a bug so would recommend closing this issue :)
