### ISSUE TITLE
Upgrade to 5.5 composer issue

### ISSUE THREAD

**Issue by iamvitali** [laravel/framework#20752]
- Laravel Version: 5.4.35
- PHP Version: 7.0.21
- Database Driver & Version: 10.1.25-MariaDB (5.6.36-82.0)

### Description:
Getting error during update:
> - The requested package laravel/framework 5.5.* is satisfiable by laravel/framework[5.5.x-dev] but these conflict with your requirements or minimum-stability.
### Steps To Reproduce:
Have Laravel 5.4.35 installed.
Change in composer: `"laravel/framework": "5.4.*" ` to ` "laravel/framework": "5.5.*",`
Change in composer: `"phpunit/phpunit": "~5.7"` to `"phpunit/phpunit": "~6.0" `
Run: `composer update`

**Comment by browner12** [comment]
it says it right there in the error message.  you have a minimum stability in your `composer.json` that is higher than `dev`.

either change your minimum stability or don't install dev packages.

**Comment by iamvitali** [comment]
Hi @browner12, thanks for the reply!

I didn't think that I was installing `dev` packages! As Laravel 5.5 is mention in the official docs (the same way 5.4, 5.3, 5.2... are mentioned). So surely it's not classified as a `dev` release and is `stable`? Otherwise, I'm pretty sure that would be mentioned in the docs?

Thanks.

**Comment by RikSomers** [comment]
Laravel 5.5 is not released officially yet. It will be released (probably) during Laracon EU 28th / 29th of August. So it is indeed still a dev release.

**Comment by iamvitali** [comment]
Wow... Well, at least it's in a few days time, so not much longer left!

But still surprised that's not mentioned in the docs. :confused:

**Comment by RikSomers** [comment]
It's because the laravel docs were made up-to-date to be ready on release I suppose.
