### ISSUE TITLE
FileNotFound Excaption fire when move file using ftp driver and file exist and filename contain [ ] (square bracket).

### ISSUE THREAD

**Issue by msdev20** [laravel/framework#20756]
- Laravel Version: 5.4.32
- PHP Version: 7.0
- Database Driver & Version:

### Description:
FileNotFound Excaption fire when file exist and filename contain [ (square bracket).

For Example:

$file_name: "/dir/file [name].ext"
Storage::disk('ftp')->move($file_name, $new_file_name) throw "FileNotFoundException"

I could not escape [ ] bracket beacuse of "normalizeRelativePath" in vendor/league/flysystem/src/Util.php:98

**Comment by srmklive** [comment]
This is not a framework error. You need to apply escape sequences to the filename before you copy it

**Comment by msdev20** [comment]
Hi, srmlive

I have uploaded files by ftp. I had try to apply escape on filename in file search args. but "normalizeRelativePath" function replace all escape "\" to path "/". So, FileNotFoundException fire.

Is there any way to search file without renaming it?

**Comment by msdev20** [comment]
Hi, srmlive
I have uploaded files by ftp. I had try to apply escape on filename in file search args. but "normalizeRelativePath" function replace all escape "\" to path "/". So, FileNotFoundException fire.
Is there any way to search file without renaming it?
Thanks,
Manish

Sent from Mail for Windows 10
