### ISSUE TITLE
Ability to add middleware to resource controller

### ISSUE THREAD

**Issue by arvanoid** [laravel/framework#20750]
It would be useful for Router to support adding middleware for specific routes. Then we could just use it in the following way:

```
    Route::resource('issues', 'IssueController', ['middleware' => [
        'index' => 'can:index',
        'create' => 'can:store',
        'edit' => 'can:store',
        'store' => 'can:store',
        'update' => 'can:update,issue',
        'destroy' => 'can:destroy,issue'
    ]]);
```

Something similar has already be implemented for Naming Resource Routes

```
Route::resource('photo', 'PhotoController', ['names' => [
    'create' => 'photo.build'
]]);
```

**Comment by Dylan-DPC** [comment]
This is not a bug. You can open a proposal in the laravel/internals repo

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
