### ISSUE TITLE
Interface 'Throwable' not found

### ISSUE THREAD

**Issue by devolper102** [laravel/framework#20765]
![screenshot_5](https://user-images.githubusercontent.com/8087388/29737149-b4d3867e-8a22-11e7-81ab-edbd032162d9.png)
- Laravel Version: 5.4
- PHP Version: 7.1.5
- Database Driver & Version:

### Description:
I am facing this issue when I have added doctrine/dbal package for migrations.

**Comment by patrickbrouwers** [comment]
Are you sure you are on PHP 7.1.5 ? Throwable interface was added in PHP7. I'm sure this isn't a Laravel issue. I would suggest asking for helping on laracast-forum or stackoverflow.

**Comment by Dylan-DPC** [comment]
Yeah this doesn't seem to be a laravel bug. Use the forums or the slack channel or check your PHP version. Also it is recommend to provide other details in your issue like versions and steps to reproduce the next time
