### ISSUE TITLE
[5.5] Optimize command deprecation

### ISSUE THREAD

**Issue by DCzajkowski** [laravel/framework#20767]
Since the `php artisan optimize` command is deprecated (the file is pretty much empty and does nothing), shouldn't it be deleted permanently?

https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Console/OptimizeCommand.php

**Comment by Dylan-DPC** [comment]
This is not a bug. You can open a proposal in the laravel/internals repo

**Comment by DCzajkowski** [comment]
This is not a proposal of a new feature. This is a deprecation and removal notice.
