### ISSUE TITLE
undefined variable uprofile

### ISSUE THREAD

**Issue by muazzamazaz** [laravel/framework#20782]
- Laravel Version: #5.4#.#
- PHP Version:
- Database Driver & Version:

I am using laravel framework 5.4 and write following controller class:

    class ProfileController extends Controller
    {
     public function index(){
          $uprofile = DB::table('user_profile')->find(Auth::id()); 
       return view('folder.profile')->with('uprofile',$uprofile);
     }

route is:

    Route::get('/','ProfileController@index');

At view I have tried

   
`"$uprofile->mobileno"` showing nothing

`"{{$uprofile->mobileno}}"` showing error of undefined variable

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this github area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I please suggestion closing your issue ticket here. Instead trying asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.
