### ISSUE TITLE
how can i append content to a big file?

### ISSUE THREAD

**Issue by lopn** [laravel/framework#20780]
https://github.com/laravel/framework/blob/603ed4a73f926e2a94fb39a01ac1d1dbaf5255d1/src/Illuminate/Filesystem/FilesystemAdapter.php#L228

I update data , all file content will be loaded the memory ， when my file is big  then Out of Memory

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this github area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I please suggestion closing your issue ticket here. Instead trying asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.
