### ISSUE TITLE
OrderBy enumeration in phpunit issue

### ISSUE THREAD

**Issue by kikky7** [laravel/framework#20787]
- Laravel Version: 5.4.32
- PHP Version: 7.1.8
- Database Driver & Version: mysql 5.7.14

### Description:
Ordering by enumeration fields works as expected in browser environment; my enum field looks like this:
```
$table->enum('type', ['regular', 'featured', 'premium'])->default('regular');
```
If I order by type (ascending) it sorts the fields as expected, by enumeration index.
Inside the phpunit tests, this same code orders the fields alphabetically, not by enum index.

### Steps To Reproduce:
This line of code returns the expected result in the browser (sorted by enum field index, so sorting goes: regular, featured, premium), but alphabetically sorts the results by enum fields in tests (sorting: featured, premium, regular):
```
return self::orderBy('type', 'asc')->get();
```

Those lines of code return error: General error: 1 no such function FIELD
```
return self::orderByRaw(DB::raw("FIELD(type, 'regular', 'featured', 'premiuim') asc"))->get();
return self::orderByRaw("FIELD(type, 'regular', 'featured', 'premiuim') asc")->get();
```

This line of code returns the expected result, but it's an ugly piece of code for such simple task:
```
return self::orderByRaw("CASE WHEN type='regular' THEN 0 WHEN type='featured' THEN 1 WHEN type='premium' THEN 2 ELSE 0 END")->get();
```

Why the behavior is different in tests and is there more elegant way to solve this issue?

**Comment by rs-sliske** [comment]
are your tests using a different database?

**Comment by kikky7** [comment]
I am using memory for testing, but the same migration and seeders

**Comment by rs-sliske** [comment]
that is your issue.

in memory database doesnt really pay attention to field types, it will just treat it as a string.

**Comment by kikky7** [comment]
So, I should just stick with the above working query if I want that fraction of a test?

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
