### ISSUE TITLE
The `artisan make:model -fa` flag creates everything instead of just a factory

### ISSUE THREAD

**Issue by paulredmond** [laravel/framework#20793]
- Laravel Version: 5.5-dev
- PHP Version: 7.1.5
- Database Driver & Version: n/a

### Description:

When I try to use `php artisan make:model -fa` flag to create a factory for a model, it creates everything (--all), but I expect it to only create a factory.

```
php artisan make:model -fa Foo
Model created successfully.
Factory created successfully.
Created Migration: 2017_08_28_084844_create_foos_table
Controller created successfully.
```

Here's the `php artisan make:model --help` (abbreviated):

```
php artisan make:model --help
Usage:
  make:model [options] [--] <name>

Arguments:
  name                  The name of the class

Options:
  -a, --all             Generate a migration, factory, and resource controller for the model
  -c, --controller      Create a new controller for the model
  -f, --force           Create the class even if the model already exists.
  -m, --migration       Create a new migration file for the model.
  -r, --resource        Indicates if the generated controller should be a resource controller.
  ...
  -fa, --factory        Create a new factory for the model
```

### Steps To Reproduce:

Run `php artisan make:model -fa Foo` and you will see that it creates a model, factory, migration, and controller, but I expect that it should only create a factory based on the help.

**Comment by arjasco** [comment]
Good spot. I believe this will occur because you are actually running `--force` and `--all` by using `-fa`. Symfony Console supports 1 letter short codes. 

Like other CLI applications you can combine multiple options by defining them one after the other eg. `ls -lah`. See here: http://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html

The factory option will need a different 1 letter short code, or removed in favour of just having `--factory` to create a factory.

Would make a PR but `-f` is already being used for the force option. I think a decision needs to be made amongst contributors.

**Comment by browner12** [comment]
is there an order precedence we can take advantage of? or will it always assume `-fa` is shorthand for `--force` and `--all`?

**Comment by arjasco** [comment]
It will always assume that unfortunately. Looks like the force flag was added recently too which resulted in a conflict, hence this commit https://github.com/laravel/framework/pull/19939 which introduced the 2 letter short code.

**Comment by paulredmond** [comment]
I don't mind looking into this a little closer, or at least submitting a PR removing the `-fa` option. I'll check back in and see if my PR is needed.

**Comment by paulredmond** [comment]
I noticed this while creative a quick "what's new in 5.5" video, and it threw me off at first 😄

**Comment by browner12** [comment]
yah, i was the one who added the force option to 5.4, and when it was merged into 5.5, that's when the conflict arose.

**Comment by paulredmond** [comment]
In general though, you can't have two-letter options right? I'm submitting a PR that just removes `-fa`.

**Comment by browner12** [comment]
i don't think we should remove it. why not just come up with a different one letter code for it?

maybe `-y`

**Comment by srmklive** [comment]
I think the `factory` flag should create only `Model`, `factory` only.

**Comment by srmklive** [comment]
Added #20798 for inclusion.

**Comment by themsaid** [comment]
Thanks for the report and fix :)

**Comment by paulredmond** [comment]
@themsaid you're welcome 👍
