### ISSUE TITLE
[5.5] New Route::view() method does not set route name

### ISSUE THREAD

**Issue by sebastiaanluca** [laravel/framework#20797]
- Laravel Version: 5.5 (dev-master 3d8ae04)
- PHP Version: 7.1

### Description:

When creating a named route that immediately returns a view using the built-in ViewController, the name is ignored and not set on the route. This is probably also the case for the new `Route::redirect()` method.

Not sure if this is a bug or just not supported. [The release notes](https://laravel.com/docs/5.5/releases) don't mention it, but as it's a regular route, people will suppose it is supported.

### Steps To Reproduce:

```php
\Route::view('home', 'pages.home')->name('home');
```

The following should return the URL to the route:

```php
route('home');
```

But produces an `ErrorException`

```
Route [home] not defined.
```

### Temporary workaround

Passing the name and controller as an array does work.

```php
\Route::match(['GET', 'HEAD'], $uri, ['as' => $name, 'uses' => ViewController::class])
            ->defaults('view', $view)
            ->defaults('data', $data);
```

**Comment by rgehan** [comment]
I can't reproduce your issue (Laravel 5.5 3d8ae04; PHP `7.1.3 (cli)`).

I have the following routes:
```php
\Route::get('/', function() {
    echo route('home');
});

\Route::view('home', 'pages.home')->name('home');
```

When browsing to `/`, it displays `127.0.0.1:8000/home`.
Same thing when using `route('home')` from inside a blade template.

**Comment by devcircus** [comment]
Works perfectly for me as well, using your exact "reproduce" steps.

5.5 dev 
PHP 7.1.7

**Comment by sebastiaanluca** [comment]
Very odd, the most basic example isn't working in my project. It is however shown in the route list (`php artisan route:list`).

Thanks for the feedback though, will investigate. Closing for now.

**Comment by sebastiaanluca** [comment]
Figured it out. My route service provider wasn't registered because I have no need for it, but the parent framework provider does a lot of stuff behinds the scenes (which it didn't do in earlier versions?) to refresh named lookups, etc. Re-added and works flawlessly now!
