### ISSUE TITLE
Error in helpers.php on line 233

### ISSUE THREAD

**Issue by VerzatileTom** [laravel/framework#20807]
- Laravel Version: 5.5.* (5.5-dev)
- PHP Version: 7.1.8
- Database Driver & Version: mysql (mariadb 10.2.3)

### Description:
PHP Parse error:  syntax error, unexpected '?' in /path/to/project/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 233

I don't know if this is a compatibility issue on the php version in our server. I was uploading a project to our dev server and this error shows on my error log. We are using Ubuntu 14.04.5 LTS as our server (if this information helps).

**Comment by ntzm** [comment]
5.5 requires at least PHP 7

**Comment by themsaid** [comment]
Make sure you are on the correct PHP version.

**Comment by VerzatileTom** [comment]
oh, I really thought we are using 7.1 in our server cause it is the version showing when you do `php -v` but `phpinfo()` is telling we are using 5.6. Sorry about this.
