### ISSUE TITLE
Error on npm install --no-bin-links

### ISSUE THREAD

**Issue by inquisitive-stha** [laravel/framework#20808]
[npm-debug.log.txt](https://github.com/laravel/framework/files/1258911/npm-debug.log.txt)
- Laravel Version: 5.4
- PHP Version: 7.0.1
- windows 10

I am trying to install dependencies Laravel-mix. But, I want to exclude axioms, loadash, and vue.js. So, I removed these lines from package.json. Also, removed vue.js require line from app.js. Similarly, removed  lodash and axioms require line from bootstrap.js inside resource assets.

After these, i tried to run "npm install --no-bin-links".

But ended up on following error: 

$ npm install --no-bin-links
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--no-bin-links"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10

npm ERR! Maximum call stack size exceeded
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\wamp64\www\mp_project\npm-debug.log

**Comment by themsaid** [comment]
Please report in the Laravel Mix repo.
