### ISSUE TITLE
Please tag a new release version on illuminate/database

### ISSUE THREAD

**Issue by deleugpn** [laravel/framework#20818]
- PHP Version: 5.6.30

### Description:
On a legacy project where I'm using `illuminate/database`, I tried to use `withDefault()` on a relationship and then I started getting undefined relationship. I ended up on [this question](https://stackoverflow.com/questions/45046389/using-withdefault-on-belongsto-results-in-error) which indicates that `withDefault` is only available after `5.4.28`. Unfortunately, `illuminate/database` is stuck in `5.4.27` (https://github.com/illuminate/database/releases)

### Steps To Reproduce:

`composer require illuminate/database`

Create a model with a `belongsTo` that has a `withDefault`.

**Comment by srmklive** [comment]
You can simply run this command instead:

```
composer require illuminate/database:5.4.x-dev
```

**Comment by Dylan-DPC** [comment]
@srmklive not everyone is happy in including an "unstable" version as a depedency

**Comment by ntzm** [comment]
Yeah this is annoying as someone who uses the components in non-laravel applications. I don't understand why a release can't be made for each version of the framework for each component?

**Comment by srmklive** [comment]
@ntzm Because a sub-tree split of the framework might have been performed, but tags might not have been updated.

**Comment by themsaid** [comment]
done :)

**Comment by deleugpn** [comment]
Thank you very much @themsaid s2 s2
