### ISSUE TITLE
Is it possible for a BelongsToMany sync fail for some records?

### ISSUE THREAD

**Issue by vjoao** [laravel/framework#20822]
- Laravel Version: 5.4
- PHP Version: 7.1.8
- Database Driver & Version: MySql

### Description:
I see that the `sync` method doesnt occur on a `DB::transaction` and runs many queries on a `foreach` loop. Is it possible for one of the many queries to fail?

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by vjoao** [comment]
What I want to know is whether the `sync` implementation can lead to integrity failure. This might be considered a bug.

**Comment by themsaid** [comment]
yes a query might fail but I won't really consider it as a bug, if you want you can wrap your call to sync inside a transaction.

**Comment by vjoao** [comment]
Shouldn't this be clearly stated in the docs? Because when one sees a method called `sync`, would never imagine there is no guarantee a `sync` will occur.
