### ISSUE TITLE
Laravel 5.5 with MongoDB

### ISSUE THREAD

**Issue by elanvans** [laravel/framework#20836]
- Laravel Version: 5.5.0
- PHP Version:7.1
- Database Driver & Version:MongoDB

### Description:
Started a new project with Laravel 5.5 and I am running into this issue.

ErrorException thrown with message "Declaration of Jenssegers\Mongodb\Eloquent\HybridRelations::belongsToMany($related, $collection = NULL, $foreignKey = NULL, $otherKey = NULL, $relation = NULL) should be compatible with Illuminate\Database\Eloquent\Model::belongsToMany($related, $table = NULL, $foreignPivotKey = NULL, $relatedPivotKey = NULL, $parentKey = NULL, $relatedKey = NULL, $relation = NULL)"

**Comment by danieluyo** [comment]
Hi @elanvans i think this issue should was in in https://github.com/jenssegers/laravel-mongodb/issues

**Comment by elanvans** [comment]
Yes, Thank you.

**Comment by Dylan-DPC** [comment]
@elanvans kindly close this issue :)
