### ISSUE TITLE
[InvalidArgumentException] Script "post-install-cmd" is not defined in this package

### ISSUE THREAD

**Issue by rodrigoroma** [laravel/framework#20831]
- Laravel Version: 5.5.0
- PHP Version: 7.1.7 (Homestead)
- Database Driver & Version: MySQL (Homestead)

### Description:
I'm using Homestead and since 5.5 when I run `laravel new app` it gives the following error:

```
 [InvalidArgumentException]
  Script "post-install-cmd" is not defined in this package
```

A related issue is that it's not automatically generating the application encryption key when I do a fresh install.

### Steps To Reproduce:
Just run `laravel new app`

**Comment by maldechavda** [comment]
Hello @rodrigoroma 

please update your composer global dependency packages,  using `composer global update`, it will solve your issue.

**Comment by themsaid** [comment]
Please upgrade your installer. Your version is not the latest :)

**Comment by rodrigoroma** [comment]
Thanks @maldechavda and @themsaid !

In fact, it was on the documentation.
