### ISSUE TITLE
Laravel 5.5 and changes to Storage::files() method

### ISSUE THREAD

**Issue by lasselehtinen** [laravel/framework#20834]
- Laravel Version: 5.5.0
- PHP Version: 7.1.0
- Database Driver & Version:

### Description:

I was going through the upgrade process to 5.5 and noticed in the upgrade guide that the files method should be returning SplFileInfo objects instead of array of file names. I am using this on my app and noticed that nothing is actually changed, it still returns an array of the file names. Same thing with allFiles. Am I missing something here?

https://laravel.com/docs/5.5/upgrade#upgrade-5.5.0

_The files method now returns an array of SplFileInfo objects, similar to the allFiles method. Previously, the files method returned an array of string path names._

### Steps To Reproduce:

```sh
$ php artisan -V                                                                                    
Laravel Framework 5.5.0                                                                             
                                                                                                    
$ php artisan tinker                                                                                
Psy Shell v0.8.11 (PHP 7.1.0 — cli) by Justin Hileman                                               
>>> Storage::disk('local')->files();
=> [
     ".gitignore",
   ]
>>> Storage::disk('local')->allFiles();
=> [
     ".gitignore",
     "public/.gitignore",
   ]
```

**Comment by Dylan-DPC** [comment]
> should be returning instead of array of file names.

i think you missed an important word here :P

**Comment by lasselehtinen** [comment]
Forgot to mention SplFileInfo, fixed. Well for me the current functionality was fine, since I hadn't to do anything to the existing code. But if this is documentation error, this probably should be fixed?

**Comment by paulofreitas** [comment]
Here's the PR that changed this: https://github.com/laravel/framework/pull/18874

Note that this change modified the behavior of [`Illuminate\Filesystem\Filesystem`](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Filesystem/Filesystem.php) class, not the [`Illuminate\Filesystem\FilesystemAdapter`](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Filesystem/FilesystemAdapter.php) - when you use the `Storage` disks you are using the `FilesystemAdapter` class.

Look this:

```
$ php artisan tinker                                                      
Psy Shell v0.8.11 (PHP 7.1.4 — cli) by Justin Hileman
>>> use Illuminate\Filesystem\Filesystem;
>>> (new Filesystem)->files(storage_path('app'), true)[0]->getBasename();
=> ".gitignore"
>>> (new Filesystem)->allFiles(storage_path('app'), true)[0]->getBasename();
=> ".gitignore"
```

Previously the `Filesystem->files()` method just returned the files pathnames as strings and didn't included hidden files. This behavior changed and now the `Filesystem->files()` method works exactly as the `Filesystem->allFiles()` method.

Anyhow the upgrade guide needs some adjustments to make the behavior changes more clear - hidden files are now returned by default and previously they weren't. 👍

**Comment by themsaid** [comment]
> Anyhow I guess the upgrade guide needs some adjustments to make these behavior changes even more clear.

Feel free to PR the docs repository, I agree it need a bit of explanation. 

Appreciate if you do @paulofreitas :)

**Comment by paulofreitas** [comment]
Done on https://github.com/laravel/docs/pull/3603. 😃  🍻
