### ISSUE TITLE
Progressive Integration for React Components

### ISSUE THREAD

**Issue by aleemb** [laravel/framework#20839]
- Laravel Version: 5.5
- PHP Version: 7.x

### Description:

The great thing about Vue is that it you can integrate it progressively, unlike React which is all or nothing. It would be great to allow convert just a single page of the Laravel app over to React while keeping the rest the same. Or integrate a React component into an existing page without moving toward SPA or converting that entire page into a JS component just to be able to include a single React component.

This requires some plumbing but is achievable and can up the ante for React developers. It would require a blade directive `@react('MyComponent', [$arg1, $arg2, ...])` which could generate the proper markup with `data-*` tags which into React would render the component. The `react` and `react-dom` libs would need to be loaded separately as dependencies so they aren't bundled with each component.

**Comment by Dylan-DPC** [comment]
This is not a bug. You can open a proposal in the laravel/internals repo
