### ISSUE TITLE
[5.5] MailFake not working with MailMessage

### ISSUE THREAD

**Issue by Dewstar** [laravel/framework#20842]
- Laravel Version: 5.5
- PHP Version: 7.1.7
- Database Driver & Version:-

### Description:
When sending a queued mail via the MailMessage class with QUEUE_DRIVER set to "sync" the MailFake "send" method will reject the mail because view is not instance of Mailable.
$view is in this case an array containing the html and text part as Illuminate\Support\HtmlString

### Steps To Reproduce:
- Set QUEUE_DRIVER to sync for examle via phpunit.xml
- Send a queued MailMessage()
- observe $view parameter in send function in vendor/laravel/framework/src/Illuminate/Support/Testing/Fakes/MailFake.php

**Comment by themsaid** [comment]
https://github.com/laravel/framework/pull/20857#issuecomment-326189755
