### ISSUE TITLE
[5.5] Command loader tries to instantiate abstract classes

### ISSUE THREAD

**Issue by DuckThom** [laravel/framework#20841]
- Laravel Version: 5.5.0
- PHP Version: 7.1.8
- Database Driver & Version: n.a.

### Description:
`$this->load(__DIR__.'/Commands');` tries to resolve abstract classes that are also in the commands directory (or sub directories).

### The error

```
# luna @ Leusinia in ~/Git/wtg/app on git:task/redesign-and-rewrite x [18:52:49]
$ php artisan


  [Illuminate\Contracts\Container\BindingResolutionException]
  Target [WTG\Console\Commands\Convert\AbstractTableCommand] is not instantiable.
```

### Steps To Reproduce:
1. Create an abstract class in `app/Console/Commands`
2. Use the `$this->load(__DIR__.'/Commands');` command loader
3. Call `php artisan` in a terminal

### Possible solution

Adding `!(new \ReflectionClass($command))->isAbstract()` to the if statement on line 222 in `Illuminate\Foundation\Console\Kernel` will prevent abstract classes being resolved.
However, I am not sure if this will have any negative side effects.

**Comment by devcircus** [comment]
See #20742

**Comment by DuckThom** [comment]
Dang it, why can I never find stuff when I search for similar issues...
