### ISSUE TITLE
laravel installer not working with 5.5,0?

### ISSUE THREAD

**Issue by ajthinking** [laravel/framework#20843]
- Laravel Version: 5.5.0
- PHP Version: PHP 7.0.22-0ubuntu0.16.04.1

### Description:
I usually do
```
laravel new blog
```
to create a new app including the .env file with a generated key. When testing today to check out 5.5 it does not complete the env creation. But there is no error. This is how it usually work, or have I bad memory? I have updated the installer. Running on ubuntu 16.04.

### Steps To Reproduce:
laravel new blog

**Comment by browner12** [comment]
`composer global update`

**Comment by jordonbaade** [comment]
Try running a `composer self-update` to update to the latest version of Composer.

**Comment by ajthinking** [comment]
I didnt have access to composer self-update but old composer was indeed the issue. I used the following process to make it work.
```
sudo apt-get remove composer
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('SHA384', 'composer-setup.php') === '669656bab3166a7aff8a7506b8cb2d1c292f042046c5a994c43155c0be6190fa0355160742ab2e1c88d40d5be660b410') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
mv composer.phar /usr/bin/composer
laravel new blog
```
Thanks to all!

**Comment by balping** [comment]
While @ajthinking 's answer solved the issue for me as well, it's better to follow install instructions from the original source: https://getcomposer.org/download/

> WARNING: Please do not redistribute the install code. It will change with every version of the installer. Instead, please link to this page [...]

**Comment by samfrjn11** [comment]
I found running `composer global update` as solution for this issue, but actually running `composer global self-update
` solved the issue for me
