### ISSUE TITLE
Valet's helper overrides Laravel's helper

### ISSUE THREAD

**Issue by rway7** [laravel/framework#20861]
- Laravel Version: 5.5.0
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7

### Description:
The `tap` method of Laravel 5.5 cannot be called from unit test, it will use the method that in Valet's helpers.
  
The problem only exists when Laravel Valet is installed. 
But It works well when I call `tap` from tinker.

### Steps To Reproduce:
- Create a fresh Laravel 5.5 project.
- Install Laravel Valet.
- Call the `tap` method from unit tests with no parameters.
- Get the following exceptions that says 2 parameters expected.

```
PHPUnit 6.3.0 by Sebastian Bergmann and contributors.

.E                                                                  2 / 2 (100%)

Time: 90 ms, Memory: 10.00MB

There was 1 error:

1) Tests\Unit\ExampleTest::testBasicTest
ArgumentCountError: Too few arguments to function tap(), 0 passed in /Users/rway7/Projects/laravel55/tests/Unit/ExampleTest.php on line 17 and exactly 2 expected

/Users/rway7/.composer/vendor/laravel/valet/cli/includes/helpers.php:143
/Users/rway7/Projects/laravel55/tests/Unit/ExampleTest.php:17
/Users/rway7/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:212
/Users/rway7/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:141

ERRORS!
Tests: 2, Assertions: 1, Errors: 1.
```

**Comment by themsaid** [comment]
I'd suggest that you don't use a global PHPUnit binary, use the one per project since different phpunit versions might be required for each app.

Maybe add an alias in your .bashrc file like so:

```
phpunit=vendor/bin/phpunit
```
