### ISSUE TITLE
Why laravel 5.5 is using this code AMP_ECID_GOOGLE

### ISSUE THREAD

**Issue by yokesharun** [laravel/framework#20862]
- Laravel Version: 5.5.0
- PHP Version: 7.1.5
- Database Driver & Version: mysql & 5.7.18

### Description:
why laravel 5.5 is using this code **AMP_ECID_GOOGLE**. the whoops error page is good but in the whoops error page i have seen this code and i need to know why you are using this google amp code. and whats the need here.

**Comment by themsaid** [comment]
This isn't used in Laravel code base, could be something in your project.
