### ISSUE TITLE
BelongsToMany missing getQualifiedRelatedKeyName() method in 5.5?

### ISSUE THREAD

**Issue by cviebrock** [laravel/framework#20869]
- Laravel Version: 5.5.0
- PHP Version: 7.0.20

### Description:

The `getQualifiedRelatedKeyName()` method on `Illuminate\Database\Eloquent\Relations\BelongsToMany` seems to have disappeared as of Laravel 5.5.  I'm using it (technically, on the `MorphToMany` which extends `BelongsToMany`) and looking for it's replacement, or the reason it was dropped.

Alternatively, a method to read the protected `$relatedKey` property would be helpful to have.

**Comment by cviebrock** [comment]
Ah ... I think I see what happened:

| Laravel 5.4 | Laravel 5.5 |
|:--------------------------:|:-------------------------------:|
| `getQualifiedRelatedKeyName()` | `getQualifiedRelatedPivotKeyName()` |
| `getQualifiedForeignKeyName()` | `getQualifiedForeignPivotKeyName()` |

Is that right?

**Comment by Dylan-DPC** [comment]
@cviebrock can you close this?

**Comment by yemenifree** [comment]
this is breaking change undocumented in upgrade Guide
