### ISSUE TITLE
FatalThrowableError Call to undefined method 

### ISSUE THREAD

**Issue by fachreza73** [laravel/framework#20875]
i got this error after deploying my project laravel to server (linux). this error not happen locally (localhost).

any solution for this ? thanks (i m using laravel 5.4)

FatalThrowableErrorCall to undefined method rizalafani\rajaongkirlaravel\RajaOngkir::Cost()
--
in Facade.php (line 221)
at Facade::__callStatic('Cost', array(array('origin' => 501, 'destination' => 114, 'weight' => 1700, 'courier' => 'jne')))in apiOngkirController.php (line 13)
at apiOngkirController->index()

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
