### ISSUE TITLE
Refactoring issue - Unused parameter

### ISSUE THREAD

**Issue by BenSaud-CS** [laravel/framework#20870]
Unused parameter $name! The value of the parameter is not used anywhere. 

https://github.com/laravel/framework/blob/2cc93b3b631cbc3d211a3304a2878388ea2770f0/src/Illuminate/Auth/AuthManager.php#L145-L165

Best regards [M. Saud](https://twitter.com/BenSaud_CS) :)

**Comment by themsaid** [comment]
Yeah that's fine, the manager calls a group of methods with a unified signature so we keep the variable to mind this.
