### ISSUE TITLE
"Whoops, looks like something went wrong." on brand new project

### ISSUE THREAD

**Issue by mattl** [laravel/framework#20874]
- Laravel Version: 5.5
- PHP Version: PHP 7.0.22-0ubuntu0.17.04.1

### Description:

Updated laravel to 5.5 via ``composer global update``. Created a new project using ``laravel new foo``

Ran ``php artisan foo``

Moving .env.example to .env and running ``php artisan key:generate`` makes the error go away.

And when creating a new project I see the following in my terminal:

```
Generating optimized autoload files
You made a reference to a non-existent script @php -r "file_exists('.env') || copy('.env.example', '.env');"
You made a reference to a non-existent script @php artisan key:generate
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
You made a reference to a non-existent script @php artisan package:discover
Application ready! Build something amazing.
```

**Comment by devcircus** [comment]
Browse the issues. Same question has been asked several times in the last 24 hours.

**Comment by mattl** [comment]
Thanks for the quick response, friend. I'm sorry :) I did, but didn't see one. Can you point me at one?

**Comment by devcircus** [comment]
#20864
#20831
#20843

Looks like you just need to update your global composer dependencies so that laravel installer gets updated.

**Comment by themsaid** [comment]
Thanks @devcircus

**Comment by mattl** [comment]
I did that. The issue was resolved by removing composer from dpkg and updating composer. https://github.com/laravel/framework/issues/20843#issuecomment-326100763 has a solution.

**Comment by samfrjn11** [comment]
I found running `composer global update` as solution for this issue, but actually running `composer global self-update
` solved the issue for me

**Comment by itskawsar** [comment]
This is because of your **Laravel Installer** or **Composer** version. I have faced the same problem and found following *2 different solutions*:

1. Generally you can solve with by running `composer global update` command and then run `composer update` command from your project directory. This solution basically updates your installer and then your project.

2. If still, you have this issue, you need to run `composer self-update` command first and then run `composer update` command from your project directory. Here your composer will update and then your project.

Hope this answer will help you.

**Comment by ikayyuddie** [comment]
@itskawsar I have tried all you said, but the problem still persists. I am using Windows 10 and PHP 7.
Just dont seem to figure this out.

**Comment by madun** [comment]
Hey @ikayyuddie try to find file .env in your project laravel. I have the same problem, thats the problem why its still doesn't work. Because .env file just gone, i don't know how it's gone. you just copy .env file from another project, and change .env file as you need

**Comment by nkossy** [comment]
this helped

**Comment by superwillz** [comment]
I had the same problem. @madun solution worked well

**Comment by malakhiwe** [comment]
@madun Thanks, your solution helped.

**Comment by david95thinkcode** [comment]
I've tried a lot of solutions found on the Web, but none works. I've tried something just 5 min ago and It works like a charm.
That's what I've done : 
- remove my **.env** file from **gitignore** file.
- Save the commit
- Run : `git push heroku master`

**Comment by VinnyLima** [comment]
Thanks for you help!

**Comment by devcircus** [comment]
Looks like you need to set your environment variables on heroku. You shouldn't commit your .env file.

**Comment by Azmeer-crescent** [comment]
rename ```.env.example``` as ```.env```. Open it and update the data (especially Database config)

**Comment by kayyyy** [comment]
I had the same issue. I got the error because the missing **.env** file

**Comment by muhamuttaqien** [comment]
It worked for env solution. Thanks for your kind guidance!

**Comment by georgemsonge** [comment]
For me, it worked after doing changes in .env file...
