### ISSUE TITLE
ModelNotFoundException->getModel() returns ReflectionClass instead of string

### ISSUE THREAD

**Issue by frdrk** [laravel/framework#20888]
- Laravel Version: 5.5.0
- PHP Version: 7.1.0
- Database Driver & Version: MySQL 5.5.42

### Description: 
In 5.4 $exception->getModel() on an error of type ModelNotFoundException would return a string as per the documentation. Now a ReflectionClass containing a bunch of stuff I don't quite understand is returned instead.

**Comment by devcircus** [comment]
Should be fixed via #20896
