### ISSUE TITLE
Can't define route contains parameter string

### ISSUE THREAD

**Issue by ozanakman** [laravel/framework#20906]
### Description:
I want to define a route that contains parameters, for example:
```
Route::get('/index.php?p=about', function() {

})
```
It shows 404 when i hit the page.

Reason of this definition is redirecting old urls to new ones. 

I guess Laravel thinks route is just index.php and remaining ?param=value part is regular http parameters. 

Is there any way to define a route like this? I know it's kinda weird but I need to do that.

**Comment by webdevhacks** [comment]
It looks like you're trying to pass in a parameter using the 'get' form method. I would suggest you review the [Route Parameter section](https://laravel.com/docs/5.0/routing#route-parameters) of the documentation. You should be defining your parameter using the correct methodology as outlined in the docs. See example below.

```
Route::get('/{p}', function($p) {
    return 'Parameter Value: ' . $p;
});
```

Hope this helps. For future questions pertaining how to use the laravel framework, refer questions to StackOverflow. This isn't an issue with Laravel, but rather user error. 😃  👍

**Comment by ozanakman** [comment]
Yes @webdevhacks It isn't logical to me also. Just asked for getting information since we're redirecting all requests to public/index.php . Thank you :)

**Comment by decadence** [comment]
You can't do that. Laravel can't register multiple routes based on $_GET-params.

You can try:
```php
Route::get('/index.php', function() {

})->name("index");

route("index", ["p" => "about"]); // "index.php?p=about
```
and make logic depends on "p" variable.

**Comment by ozanakman** [comment]
@decadence I was creating very similar logic. Redirecting everything to index.php -> SomeController@index and then resolve parameters.

Probably this is the only valid solution besides editing web server config files
