### ISSUE TITLE
[5.5] Model->getAttributes() override may cause inconsistency

### ISSUE THREAD

**Issue by austenc** [laravel/framework#20902]
- Laravel Version: 5.5.0
- PHP Version: 7.1
- Database Driver & Version: N/A

### Description:
[This change](https://github.com/laravel/framework/commit/a0402824bf479dc5135b40a7f40095d4e2bbb265#diff-6a9cb621261ef4a702081454957adfb2L963) (specifically changing `$this->attributes` to `$this->getAttributes()`) is not backwards compatible with some packages / apps that may override the `getAttributes()` model method. If the attribute values aren't strings, the query builder can't bind them properly [right here](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Database/Query/Builder.php#L2149) and you get an "Object could not be converted to string" message. 

Such an example is the [EloquentTrait class of the popular Stapler package](https://github.com/CodeSleeve/stapler/pull/94/commits/86fd1db830a837c189384dad0f9c6eed325b3d8d).

I'm assuming the attributes are intended to always be strings?  Regardless, I wanted to at least bring up the discussion that `$this->attributes` and `$this->getAttributes()` could yield different results if the method is overridden. I'm assuming this isn't too common, but it could be considered a breaking change for some.

#### 1. Override the `getAttributes()` method on a model to something like:
```php
public function getAttributes()
{
    return array_merge(['something' => new StdClass], $this->attributes);
}
```
#### 2. Call `$model->save()`

**Comment by themsaid** [comment]
Closing as per Taylor's response, seems like the package itself needs to adapt to the change.

**Comment by austenc** [comment]
Yep, I figured this would probably be the case, but wanted to confirm with you guys. Thanks @themsaid!

**Comment by lintaba** [comment]
have the same issue. this helped me:
https://github.com/czim/laravel-paperclip/commit/515a66b4cdb2a3f7ab3b39094d695840400523c1

**Comment by mostafaznv** [comment]
refer to this answer, you can fix it with getDirty method

https://github.com/CodeSleeve/laravel-stapler/issues/64#issuecomment-345786784
