### ISSUE TITLE
[5.4 Issue] [5.5 Feature Request] Exclude Specific Route when Auth::routes() is called

### ISSUE THREAD

**Issue by webdevhacks** [laravel/framework#20904]
- Laravel Version: 5.4.*
- PHP Version: 7.0

### Description:
I would like to have some type of functionality where I can exclude a specific route from being generated when calling the Auth::routes() method in my web.php file.

I know you can exclude routes in Resource controllers but unfortunately this isn't implemented for the Authentication Route generation. (If it is implemented it's not very well documented, because I can't figure out how to do it)

Maybe being able to pass in an array to the routes() method?

Pseudo Code:

`Auth::routes(
    ['except' => ['logout', 'login']
]);`

This is my first time ever contributing to a github repo, or even submitting an issue. I'm not very well versed in the framework and don't completely understand the workings but I think I know how to solve this issue...

In the Auth Facade routes() method, define a excludes variable, then pass that variable into the auth() method. see code below

```
public static function routes(Array $excludes = [])
    {
        static::$app->make('router')->auth($excludes);
    }
```

Then in the auth method, do some logic to exclude the generation of the specific route(s)?

What do you think of the idea? Has this not been implemented on purpose? Or has this just been overlooked. Adding this would help those using Native Multi-Authentication. I'm trying to add a LogoutController and I'm finding it difficult to keep my code clean and neat. As it sits right now I have to manually write each route for authentication in order to achieve the functionality I'm wanting.

**Comment by ntzm** [comment]
Feature requests go in laravel/internals. I think this suggestion has been declined before FYI

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.

You can copy the content of `Router::auth()` and put it in your web.php routes file instead of `Auth::route()` and pick only the routes you want to be available.
