### ISSUE TITLE
Sessions persist between jobs on the same queue worker

### ISSUE THREAD

**Issue by jojonas** [laravel/framework#20908]
- Laravel Version: 5.3.31
- PHP Version: 7.1.7
- Database Driver & Version: any

### Description:
Multiple jobs running on the same queue worker (`php artisan queue:work`) will share the same session, even if they are completely independent. Although the concept of a session within jobs does not make sense and therefore should not be relied on, this issue has become relevant to some of my code:
I use `Auth::user()` in a lot of places (e.g. repositories, which are shared between the web component and job component), and expected it to return `null` while inside a job. I encountered this bug when an independent job running before called `Auth::setUser(...)`, having side effects on all subsequent jobs.

I cannot imagine that this is desirable behavior for anyone. The jobs should run independently of each other, without side effects.

As a mitigation, we could either flush the session between each queue job or even issue a completely new session id.

### Steps To Reproduce:
Create a job that sets some session variable. Create a second job that reads this session variable. Queue both jobs after another, run `php artisan queue:work` to process both. You will observe that the second job will be seeing the value from the first.

**Comment by laurencei** [comment]
Yeah - using sessions inside a queue is likely to lead to unexpected behavior.

Your best bet is to try using `queue:listen` instead of `queue:work`. Rebooting the framework should give you a clean slate each time.

**Comment by themsaid** [comment]
> Although the concept of a session within jobs does not make sense and therefore should not be relied on

Yes it doesn't make sense at all, sessions aren't available during jobs execution, sessions are tied to the web middleware group, running a job under queue:work or queue:listen doesn't give you access to sessions correctly

You'll need to update your app and make sure sessions receive what they need to run via a serialized object. Also I'm afraid it's a bad idea to use sessions in repositories. Sessions aren't available all the time, don't rely on it in code that's not HTTP only.
