### ISSUE TITLE
Wildcarded event listeners doesn't get the same signature

### ISSUE THREAD

**Issue by challet** [laravel/framework#20912]
- Laravel Version: 5.4
- PHP Version: 7.1
- Database Driver & Version: Postgresql

### Description:

Hi, 

I'm trying to register several event listeners using the same handler. Unfortunately, the arguments passed to it differs function of wether a wildcard [is used](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Events/Dispatcher.php#L364) or [not](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Events/Dispatcher.php#L367).

It seems to be expected [to work as so](https://laravel.com/docs/5.4/events#manually-registering-events) and though it works fine if **all or none** events are wildcarded, isn't there an inconsistency between the two types ?
Or am I misleading trying to mix them both ?

### Steps To Reproduce:

```php
namespace Model {
    class User extends \Illuminate\Database\Eloquent\Model {
    }
}

namespace Model\User {
    class Role1 extends \Model\User {
    }
    class Role2 extends \Model\User {
    }
}

class ModelCreated {
    public function handle($arg1, $arg2 = null) {
        var_dump($arg1, $arg2);
    }
}

Event::listen('eloquent.created: Model\User', 'ModelCreated');
Event::listen('eloquent.created: Model\User\*', 'ModelCreated');

Event::fire('eloquent.created: Model\User', new Model\User());
Event::fire('eloquent.created: Model\User\Role1', new Model\User\Role1());
```

That outputs a different signature for each of the cases : 
* > object(Model\User)#450 (25) { [...] }
* > string(34) "eloquent.created: Model\User\Role1" 
   > array(1) { [0]=> object(Model\User\Role1)#450 (25) { [...] } }

**Comment by themsaid** [comment]
yes for wildcard events you get the event as the first argument and the payload as the second argument.

**Comment by challet** [comment]
```php
class ModelCreated {
    public function handle($model) {
    }
    public function handleChild($event, $payload) {
        $this->handle($payload[0]);
    }
}

Event::listen('eloquent.created: Model\User', 'ModelCreated');
Event::listen('eloquent.created: Model\User\*', 'ModelCreated@handleChild');
```

**Comment by themsaid** [comment]
We can't really change this since it's  a major breaking change, but will consider it in Laravel 5.6

Thanks
