### ISSUE TITLE
Laravel CSRF token mismatch

### ISSUE THREAD

**Issue by Hardiik** [laravel/framework#20914]
- Laravel Version: 5.4
- PHP Version:7

### Description:
i have a project in laravel i had used the auth controller for login and register it works completely fine on localhost but when i had uploaded it to production server it gives error like CSRF token mismatch what should has to be done ??
laravel instance is fine cuz it already works fine with my local host but when i put it online blammm! it gives error i had gone through many settings but still not found any solution (i had already mentioned {{ csrf_field() }}) .so i needs help from u guys.

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
