### ISSUE TITLE
Segfault when assertion incorrectly spelt

### ISSUE THREAD

**Issue by philcross** [laravel/framework#20925]
- Laravel Version: 5.5.0
- PHP Version: 7.1.7
- Database Driver & Version: N/A

```
homestead-7: Checking for updates to 'laravel/homestead'
homestead-7: Latest installed version: 3.0.0
homestead-7: Version constraints: >= 3.0.0
homestead-7: Provider: virtualbox
```

### Description:

I recently wrote a simple feature test that used a facade assertion, which I had (unknowingly) spelt incorrectly. When I ran phpunit, it resulted in a Segmentation Fault. Correcting the spelling of the assertion method name fixed the issue.

I don't understand segfaults very well, but when I googled how to debug it, I couldn't find anything in either the Laravel error log, or the nginx error log in homestead (/var/log/nginx/). I would have expected PHP to issue a function not found error (or similar) if I had spelt the method name incorrectly.

### Steps To Reproduce:

This is being done inside homestead

1) Create a new feature test
2) Fake the queue: `Queue::fake();`
3) Attempt to call `Queue::asertPushedOn('email', App\Jobs\SomeJob::class);`
4) Run phpunit
5) (Hopefully) see segfault
6) Fix the assertion name to `assertPushedOn()`
7) Run phpunit - don't see segfault

Hopefully others can reproduce this as well. Please let me know if you need further information.

**Comment by henriquebremenkanp** [comment]
I've got `Fatal error: Maximum function nesting level of '256' reached, aborting! in {myPath}/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php on line 120` instead of the segfault

**Comment by philcross** [comment]
Interesting why I got a segfault, and you got a nesting level error. Again, I'm not too knowledgable about segfaults so unsure why I'm getting it (aside from the method name being spelt incorrectly)

**Comment by thecrypticace** [comment]
One of the most common causes of segfaults in PHP is infinite recursion. However, if you have Xdebug installed it will instead error out with a nesting level error.

**Comment by themsaid** [comment]
Closing since it's not actually a bug in the framework.
