### ISSUE TITLE
Allowed memory size of 134217728 bytes exhausted (tried to allocate 19153517 bytes) in ManagesLayouts.php (line 156)

### ISSUE THREAD

**Issue by cdmathukiya** [laravel/framework#20928]
- Laravel Version: 5.4
- PHP Version: 7.1
- Database Driver & Version: 5.6.36-cll-lve - MySQL Community Server (GPL)

### Description: 
in my website http://partssupplymiami.com/a_parts in this page the data is load as expected
BUT, in admin side it generate error like this:

> Allowed memory size of 134217728 bytes exhausted (tried to allocate 19153517 bytes) in ManagesLayouts.php (line 156)

![memory_error](https://user-images.githubusercontent.com/18529326/29993758-f9116048-8fdd-11e7-8c6d-adcb9dd82369.png)

please help to solve this error

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue
