### ISSUE TITLE
AnonymousNotifiable does not work with Notification Fake or expectsNotification in test

### ISSUE THREAD

**Issue by hmazter** [laravel/framework#20936]
- Laravel Version: 5.5.0
- PHP Version: 7.1

### Description:

When using "On-Demand Notifications" a `AnonymousNotifiable` is created and passed to the Notification system.
When in test using Notification Fakes or the `expectsNotification` these two expects there to be a `getKey()` on the Notifiable as it would if it where a User Model.

```
Call to undefined method Illuminate\Notifications\AnonymousNotifiable::getKey()
vendor/laravel/framework/src/Illuminate/Support/Testing/Fakes/NotificationFake.php
```

### Steps To Reproduce:

1. Use `Notification::route('mail', 'taylor@laravel.com')->notify(new InvoicePaid($invoice));` to send a notification
1. write a test that triggers that function
1. use the Notification Fake, `Notification::fake();`
1. the above error is produced

**Comment by themsaid** [comment]
Thanks, fixed in https://github.com/laravel/framework/pull/20965
