### ISSUE TITLE
can use multiple mail drivers at time...?

### ISSUE THREAD

**Issue by thanush** [laravel/framework#20932]
- Laravel Version: 5.4
- PHP Version:7.0
- Database Driver & Version:

### Description:
is it possible to use multiple mail drivers at once...?

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by henriquebremenkanp** [comment]
Just like @Dylan-DPC said. 
Since we're already here, you can use the Config facade or the config() helper to swap your drivers. 
Please close this issue.
