### ISSUE TITLE
Policy method 'before' is not called in 5.5.0

### ISSUE THREAD

**Issue by masterwto** [laravel/framework#20943]
- Laravel Version: 5.5.0
- PHP Version: 7.1.8
- Database Driver & Version: MariaDB 10.2

### Description:
I was migrating my project from 5.4 to 5.5.0. When I tested the project, I got many exceptions of AccessDeniedHttpException. It really took me hours, and finally turned out that the method 'before' is not called.

### Steps To Reproduce:
I was developing off the network, and issue is through my cellphone.
When the ability is defined as a single method in the policy class, it works fine; but when I put that into the 'before' method, 'before' method is never called and I then got the AccessDeniedHttpException.

Sorry that I did not put the codes here.
Thanks for reading.

**Comment by masterwto** [comment]
My policy class is registered in another authserviceprovider class except that in app\Providers\AuthServiceProvider.

**Comment by masterwto** [comment]
Seems bug of Illuminate\Auth\Access\Gate line 437~439. The resolvePolicyCallback method wants all abilities to be written into methods.

I'll make a PR.

**Comment by browner12** [comment]
can you post some code? this was explicitly called out in the upgrade guide, so I'm not sure that it is a bug.

**Comment by masterwto** [comment]
@browner12 Thank you very much for reading.
I got the error.

class Policy
{
    public function before(User $user, $ability)
    {
        //
        dd('The \`before\`method is called.');
    }

    public function someAbility(User $user, Class $object)
    {
        //
    }
}
```

when we authorize in a controller `$this->authorize('someAbility', $someObject)`, we may get `The \`before\`method is called`; 
when we authorize in a controller `$this->authorize('otherAbility')`, we may get `AccessDeniedHttpException`.

**Comment by masterwto** [comment]
@browner12

I don't know how to write the tests. Could you please add some test classes for this issue?

**Comment by devcircus** [comment]
From the upgrade guide:
> The before Policy Method

> The before method of a policy class will not be called if the class doesn't contain a method with name matching the name of the ability being checked.

**Comment by masterwto** [comment]
@devcircus
 Thank you.

I missed this.
