### ISSUE TITLE
Custom error page not rendered when view path is not the default path

### ISSUE THREAD

**Issue by gdinko** [laravel/framework#20947]
- Laravel Version: 5.5.1
- PHP Version: 7
- Database Driver & Version:

### Description:
From AppServiceProvider I'm adding dynamicaly view path like this:

`view()->addLocation(realpath(base_path('resources/views/themes' . '/' . config('dc.theme'))));`
Then i check:
`dd(view()->getFinder()->getPaths());` 
The path is added but custom error page is not rendered. Default error page is rendered.

Path to my custom 404 error page:
resources\views\themes\simple\errors\404.blade.php

if i add custom view path in /config/view.php paths like this:
`'paths' => [
        resource_path('views'),
        resource_path('views/themes/simple'),
    ],`

again the default 404 error page is shown

**Comment by gdinko** [comment]
quick fix in App\Exception\Handler.php render method

`if ($exception instanceof NotFoundHttpException) {
            return response()->view('errors.404', [], 404);
        }`

this will render the correct view

**Comment by themsaid** [comment]
yes you'll need to manually tell laravel where to load the error view from since you're not using the default view location.

**Comment by themsaid** [comment]
You may override `renderHttpException` inside your handler to take control over loading all kinds of HTTP exceptions not just 404

**Comment by gdinko** [comment]
Why you just fix it? The default path is hard coded? In v 5.2 is working like a breeze?

**Comment by gdinko** [comment]
This behavior is hard coded here why don't you just fix it to use the view paths not hard coded ones?:

`protected function renderHttpException(HttpException $e)
    {
        $status = $e->getStatusCode();

        view()->replaceNamespace('errors', [
            resource_path('views/errors'),
            __DIR__.'/views',
        ]);

        if (view()->exists($view = "errors::{$status}")) {
            return response()->view($view, ['exception' => $e], $status, $e->getHeaders());
        }

        return $this->convertExceptionToResponse($e);
    }`
