### ISSUE TITLE
Suggestion: Add Route::other for setting route that matches all the requests that didn't match

### ISSUE THREAD

**Issue by yaronuliel** [laravel/framework#20952]
### Description:
It would be useful in some cases to have the possibility to add a route that catches all the requests that didn't match any other route

A good example would be - for cms that dynamically creates pages (page URIs are stored in database for example)

This is different from changing the behavior of 404 responses in several ways:
* 404 response doesn't use controllers for handling request
* changing 404 can only be handled on the App\Exceptions\Handler which is hardcoded in the bootstrap script - and can't be tweaked from packages without ugly workarounds

Currently, in order to achieve similar results - you can create a very broad route like 
`Route::get( '{any}', ...)`- but it has its disadvantages:
* Not explicit enough that it should catch whatever others didn't (as opposed to all requests)'
* It must be defined last in order (to prevent overwriting of more specific routes) - which makes it hard to maintain if routes are registered through several packages, or files

**Comment by Dylan-DPC** [comment]
This is not a bug. You can open a proposal in the laravel/internals repo

**Comment by codetheorist** [comment]
But wouldn't using the normal Route::resource() do exactly the same thing, as long as the defined route methods come before the resource route?

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
