### ISSUE TITLE
view()->composer(['errors.404'] not working

### ISSUE THREAD

**Issue by gdinko** [laravel/framework#20953]
- Laravel Version: 5.5.1
- PHP Version: 7.0.0
- Database Driver & Version:

### Description:
```
view()->composer(['errors.404'], function ($view) {
            $title = 'some text';
            $view->with('title', $title);
        });
```

 The title var is not defined in views/errors/404.blade.php

### Steps To Reproduce:
insert this code in AppServiceProvider->boot()

```
view()->composer(['errors.404'], function ($view) {
            $title = [config('dc.site_domain')];
            $title[] = trans('404.Ups something is missing.');
            $view->with('title', $title);
        });
```

try to print $title in /views/errors/404.blade.php

**Comment by gdinko** [comment]
quick fix in App\Exception\Handler.php render method

`if ($exception instanceof NotFoundHttpException) {
            return response()->view('errors.404', [], 404);
        }`

this will render the correct view

**Comment by themsaid** [comment]
use `errors::404` instead of `errors.404`

**Comment by carloshhr** [comment]
@themsaid useful comment ever!

**Comment by semihkeskindev** [comment]
> use `errors::404` instead of `errors.404`

  you saved my life and time :smile: thank you so much

**Comment by udeyubi** [comment]
> use `errors::404` instead of `errors.404`

thanks a lot.  but...why.....

**Comment by josefernandoperezgarcia1998** [comment]
Its works for me the coment of @themsaid,
`public function boot()
    {
        view()->composer('errors::403', function($view){
            $view->with('menus', Menu::menus());
        });
        view()->composer('layouts.pagina.pagina-plantilla', function($view){
            $view->with('menus', Menu::menus());
        });
        view()->composer('welcome', function($view){
            $view->with('menus', Menu::menus());
        });
    }
`
