### ISSUE TITLE
php artisan preset none doesn't remove bootstrap-sass from bootstrap.js

### ISSUE THREAD

**Issue by benabbottnz** [laravel/framework#20959]
- Laravel Version: 5.5.0
- PHP Version: 7.1.6
- Database Driver & Version: MySQL

### Description:

`php artisan preset none` removes most of bootstrap from the project, but not the reference to `bootstrap-sass` in the `resource/assets/js/bootstrap.js`.

### Steps To Reproduce:

1. Download fresh copy of Laravel.
2. Run `php artisan preset none`. 
3. Run `npm install`
4. Run `npm run dev`
5. See error.

**Comment by devcircus** [comment]
See https://github.com/laravel/framework/pull/19618
The try/catch is there so that bootstrap.js never has to be updated.

**Comment by benabbottnz** [comment]
That's a pretty bad implementation then. `php artisan preset none` only gets the job half done, unless you don't mind seeing the same "Can't resolve bootstrap-sass" error every time you make a change to a Sass or JS file.
