### ISSUE TITLE
Nexmo Client not found

### ISSUE THREAD

**Issue by djrausch** [laravel/framework#20960]
- Laravel Version: 5.5.1
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7.19

### Description:
I get the following error when trying to use SMS Notifications
`Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Nexmo\Client' not found in /home/forge/projectname/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php:102`

I did composer `composer require nexmo/client:@beta` to install it.

### Steps To Reproduce:
Not really sure...

**Comment by themsaid** [comment]
Sorry this doesn't seem to be an issue with the framework, I suggest that you use the forums for help :)

Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
