### ISSUE TITLE
Dev Packages auto-discovered and registered in production environment

### ISSUE THREAD

**Issue by sakibulalam** [laravel/framework#20967]
- Laravel Version: 5.5.1
- PHP Version: 7.1.6
- Database Driver & Version:

### Description
It seems that Laravel is auto-discovering dev packages and registering them in `production` environment, more specifically, Dusk is throwing its `It is unsafe to run Dusk in production.` Exception. The other dev packages are also in the application object.
Tried with clearing caches and deleting the cached **packages.php** in **bootstrap/cache** directory.

This happened after upgrading from Laravel 5.4

### Steps to Reproduce
Try running `composer install` or `php artisan optimize` with environment set to `production` with dev dependencies, particularly `laravel/dusk`

**Comment by it-can** [comment]
Try running this composer command:

```
composer install --no-dev
```

This will not install your dev packages...

**Comment by sakibulalam** [comment]
@it-can, running `composer install --no-dev` worked. But isn't package discovery supposed to automatically figure out and handle dev packages?

**Comment by it-can** [comment]
It will discovery packages that are installed...

**Comment by sakibulalam** [comment]
@it-can, thanks for clearing that out.
