### ISSUE TITLE
Problem with Route::view('xx','xx') with ->where() method

### ISSUE THREAD

**Issue by bardouni** [laravel/framework#20968]
- Laravel Version: 5.5.*
- PHP Version:7.0.1

### Description:

The new Route::view method doesn't work well when using this syntax

![image](https://user-images.githubusercontent.com/11160251/30023255-836dd7ce-9166-11e7-88b1-f52d85986f89.png)

![image](https://user-images.githubusercontent.com/11160251/30022433-3395f4b4-9163-11e7-9a24-1a6bd1460015.png)

**Comment by KKSzymanowski** [comment]
I came across this too. The router takes your `all` parameter and matches it with the first argument of the controller method in `Illuminate\Routing\ViewController`.
```php
public function __invoke($view, $data)
{
    return $this->view->make($view, $data);
}
```

I don't see any way to fix this with the current routing mechanism. Introducing something like Vue Router [meta fields](https://router.vuejs.org/en/advanced/meta.html) would provide an opportunity as it would make the view name independent of the parameters.

**Comment by bardouni** [comment]
@KKSzymanowski 
I created this pull request
https://github.com/laravel/framework/pull/21076

**Comment by themsaid** [comment]
Fixed by https://github.com/laravel/framework/pull/21113
