### ISSUE TITLE
Member has protected access

### ISSUE THREAD

**Issue by SlyDeath** [laravel/framework#20963]
$this->query is protected, need public method for get this property
https://github.com/laravel/framework/blob/a3db80b101d91a1aeac0c8d1d4aebeb815c07c60/src/Illuminate/Database/Eloquent/Relations/BelongsTo.php#L81
https://github.com/laravel/framework/blob/a3db80b101d91a1aeac0c8d1d4aebeb815c07c60/src/Illuminate/Database/Eloquent/Relations/BelongsTo.php#L97
https://github.com/laravel/framework/blob/a3db80b101d91a1aeac0c8d1d4aebeb815c07c60/src/Illuminate/Database/Eloquent/Relations/BelongsTo.php#L114

**Comment by themsaid** [comment]
Sorry but I don't understand what you want, please share more details.

**Comment by SlyDeath** [comment]
Wow, it seems there is no mistake, did not see @mixin magic methods, sorry :)
