### ISSUE TITLE
Document library updates that have breaking changes

### ISSUE THREAD

**Issue by luiz-brandao** [laravel/framework#20977]
- Laravel Version: 5.5

I'm in the process of upgrading an application to 5.5 and I encountered an issue with SwiftMailer and a custom Mail driver. Laravel 5.5 updated the required version of SwiftMailer to a new one that has breaking changes.

Shouldn't changes of this type be documented in the Upgrade Guide?

**Comment by Dylan-DPC** [comment]
If you find a breaking change is missing from the docs you can add it by submitting a PR to laravel/docs.

**Comment by themsaid** [comment]
Thanks PRed that: https://github.com/laravel/docs/pull/3614
