### ISSUE TITLE
[5.5] Validation of array on request returns bad array

### ISSUE THREAD

**Issue by mbaeuerle** [laravel/framework#20973]
- Laravel Version: 5.5.1
- PHP Version: 7.1.8
- Database Driver & Version: - 

### Description:
When trying to validate an array through `$params = $request->validate([])` the returning `$params` contains the key `*` which was not specified.

### Steps To Reproduce:
- Create a route: 
```php
Route::post('/test', function (Request $request) {
    $data = $request->validate([
        'test' => 'required|array',
        'test.*.a' => 'required|integer',
    ]);

    dump($data);
    return new \Symfony\Component\HttpFoundation\Response();
});
```
- Call it with:
```json
{
  "test": [{
    "a": 123
  }]
}
```
- Dump shows:
```php
array:1 [
  "test" => array:2 [
    0 => array:1 [
      "a" => 123
    ]
    "*" => array:1 [
      "a" => array:1 [
        0 => 123
      ]
    ]
  ]
]
```

**Comment by themsaid** [comment]
Handled in https://github.com/laravel/framework/pull/20974
