### ISSUE TITLE
Weird updateOrCreate method results

### ISSUE THREAD

**Issue by webmake** [laravel/framework#20999]
- Laravel Version: 5.4.36
- PHP Version: 7.1
- Database Driver & Version: 10.0.24-MariaDB

### Description:
How can it be possible, that using method `updateOrCreate` and having entity
```
class Image extends Model
{
    public $timestamps = false;
    protected $fillable = [
        'user_id',
        'image',
        'original_image',
    ];
    protected $primaryKey = 'user_id';
}
```
would occur error:
```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1590' for key 'images_user_id_unique' (SQL: update `images` set `user_id` = 1590, `image` = 88f66_full.jpg, `original_image` = 48e848_full.jpg where `user_id` = 1579)
```

### Steps To Reproduce:
Using xdebug, and debuging step by step, I see, if new record - then would be `insert .....`, but if existing, there is update with ONLY 2 fields (image and original image), but on live server, update with 3columns? Is it possible race condition?

**Comment by themsaid** [comment]
@webmake please add some Steps To Reproduce, issue is vague.

**Comment by BrandonSurowiec** [comment]
Your primary key for your image table is set to `protected $primaryKey = 'user_id';` Shouldn't that be something like `id`? 

If not, then your model probably shouldn't be incrementing. So you should try adding this to your model:

```
    /**
     * Indicates if the IDs are auto-incrementing.
     *
     * @var bool
     */
    public $incrementing = false;
```

**Comment by webmake** [comment]
@BrandonSurowiec you are right, this table has no regular id, it's just `user_id`, and unique, and defined by some other rules, that don't satisfy such demand for autoincrement. This table is only for caching, many to one relation. I'm not sure that
`public $incrementing = false;` would solve this problem.


**Returning to main bug or problem,** as I mentioned, while debuging, there is such method
```
$this->imageRepository->updateOrCreate(
            [
                'user_id' => $userId,
            ],
            [
                'user_id' => $userId,
                'image' => $image,
                'original_image' => $fullAvatarUrl,
            ]
        );
```
Please take carefully these queries, once again:
When inserting, query as below:
```insert into `images` (`user_id`, `image`, `original_image`) values (?, ?, ?)```
Everything OK.
When updating, query is below:
```update `images` set `image` = ?, `original_image` = ? where `user_id` = ?```
Everything OK.

Then why LIVE tolds me SOMETIMES:
```
(SQL: update `images` set `user_id` = 1590, `image` = 88f66_full.jpg, `original_image` = 48e848_full.jpg where `user_id` = 1579)
```
This is kind of update, but why the hell set **user_id = 1590**? It never happens on local while debugging.

here is laravel core code, that we are talking about
```
    public function updateOrCreate(array $attributes, array $values = [])
    {
        return tap($this->firstOrNew($attributes), function ($instance) use ($values) {
            $instance->fill($values)->save();
        });
    }
```
3 columns in update is very weird, it's like `firstOrNew` method returning object, because query is `update` type, but somehow, builds with original where query, like model would disappear,

or second guess, that `firstOrNew` returns false, but method deep in save instead of exists = false, gets now as true, like somehow other process filled database
```
    public function save(array $options = [])
    {
        $query = $this->newQueryWithoutScopes();
....
        if ($this->exists) {
            $saved = $this->isDirty() ?
                        $this->performUpdate($query) : true;
        }
...
```

**Comment by webmake** [comment]
Seems everything solved, doesn't work method `getDirty` for me, somehow fails
```
        return is_numeric($current) && is_numeric($original)
            && strcmp((string) $current, (string) $original) === 0;
``` in it.
eveything solved now, when changed string casting user_id.. It happens with huge integers, that actually is over 32bits but system is 64bit.. very strange, but thanks for your time
