### ISSUE TITLE
php artisan migrate:fresh multi database issue

### ISSUE THREAD

**Issue by kholman3** [laravel/framework#21009]
- Laravel Version: "laravel/framework": "5.5.*",
- PHP Version: 7.1
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.7.19, for Linux (x86_64) using  EditLine wrapper

### Description: When you run `php artisan migrate:fresh` command it doesn't drop tables for secondary database connection.
in my database.php I have.
        'mysql'              => [
            'driver'    => 'mysql',
            'host'      => env('DB_HOST', 'localhost'),
            'database'  => env('DB_DATABASE', 'forge'),
            'username'  => env('DB_USERNAME', 'forge'),
            'password'  => env('DB_PASSWORD', ''),
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
            'strict'    => FALSE,
            'engine'    => NULL,
        ],
        'mysql_2'     => [
            'driver'    => 'mysql',
            'host'      => env('DB_HOST_2', 'localhost'),
            'database'  => env('DB_DATABASE_2', 'forge'),
            'username'  => env('DB_USERNAME_2', 'forge'),
            'password'  => env('DB_PASSWORD_2', ''),
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
            'strict'    => FALSE,
            'engine'    => NULL,
        ],

### Steps To Reproduce:
Create a table for each database, then run the migration. After you have tables run `php artisan migrate:fresh`. It ignores the mysql_2 tables when dropping, which then throws the error "Table 'X' already exists". If you drop the table manually then run the command again it will work as it should.

**Comment by themsaid** [comment]
You can decide which database you want to drop using the `--database` option

**Comment by jrhenderson1988** [comment]
I would like to vote for this to be re-opened.

The aim of the `migrate:fresh` command is to drop all of your tables and migrate everything again, right? If you use multiple databases in an application, the command will simply drop all the tables from your default connection and then attempt to migrate everything again, which will result in errors that tables already exist in your other, non-default databases.

If we are to use the `--database` option to specify that we want to drop all tables from a different database, then the default connection wouldn't have its tables dropped and the subsequent *up* migration would fail again with similar errors, albeit for a different set of tables.

If it isn't feasible or desirable to have `migrate:fresh` drop tables from all databases before migrating again, would it instead be possible to be able to specify multiple database connections when using the `--database` option? I would be willing to submit a PR for the latter option if that's something that may be considered useful and would likely be accepted.

**Comment by Pablo-Araya** [comment]
@jrhenderson1988 
I would like to vote for this to be re-opened.
+1

**Comment by Vusys** [comment]
+1

We have multiple databases to separate admin/ CRM and customer data. It's possible to work around this by extending and replacing the command, but it would be a nice addition to the framework imo.

**Comment by Nur777** [comment]
+1 Because of the comment above (https://github.com/laravel/framework/issues/21009#issuecomment-414971613 ) describe the problem in our development too.

**Comment by Vusys** [comment]
Got tried of this not working and very quickly whipped up a solution. Obviously this just works for me and isn't ideal - the database names are hardcoded, views are not tested, database engines other than MySQL are not tested or supported. But it solves the immediate problem for me. Hopefully this helps someone out.

https://gist.github.com/Vusys/7989d824c512516d6ea4dc18057f602b

**Comment by lucadegasperi** [comment]
Recently stumbled upon this very same issue, I have both a mysql and a pgsql database and I need to run tests that touch both databases. The migrations are only stored inside one db (shouldn't the migrations for each database be stored in the corresponding database?).
The ```RefreshDatabase``` trait only freshly migrates the first database, but does not delete the tables in the second database before attempting to re-migrate them. Is there a solution to this problem? Has anyone solved this problem already somehow?

**Comment by RichardStyles** [comment]
I've stumbled upon this when setting up Telescope to use a different database, which should be possible [as per documentation]. However when you run the very common:
```php artisan migrate:fresh``` 
This throws an error reporting that the database tables still exists.

Current workaround is to publish the migration asset and wrap the create with a check to see if the table exists.

```
if($this->schema->hasTable('telescope_entries') === false) {
    $this->schema->create('telescope_entries', function (Blueprint $table) {
...
```

The migration looks like it should manage on a different schema but doesn't seem to comply.

**Comment by katsuren** [comment]
I've also stumbled upon this issue.
migrate:fresh command is used in RefreshDatabase.php, it causes migration error on testing.

**Comment by martindilling** [comment]
> I've stumbled upon this when setting up Telescope to use a different database, which should be possible [as per documentation]. However when you run the very common:
> `php artisan migrate:fresh`
> This throws an error reporting that the database tables still exists.
> 
> Current workaround is to publish the migration asset and wrap the create with a check to see if the table exists.
> 
> ```
> if($this->schema->hasTable('telescope_entries') === false) {
>     $this->schema->create('telescope_entries', function (Blueprint $table) {
> ...
> ```
> 
> The migration looks like it should manage on a different database connection but doesn't seem to comply.

This is the reason I ended up here as well.
The drop part of the command only drops the default, but the migrate part migrates everything.

One option could be a new command `php artisan migrate:drop --database="..."` then we can drop both before calling a new `migrate`
Another option could be making the `--database` option support multiple databases separated by comma. `php artisan migrate:drop --database="sqlite,sqlite_telescope"`.

**Comment by durianpeople** [comment]
I do think that the fresh part of the `migrate:fresh` command should be migration-agnostic to prevent corrupted migrations from messing up, and so it cannot know which connections should the tables be dropped. On the other hand, `migration:fresh` cannot just drop all tables from all connections available, since some DB connections are designed to not use migration mechanism.

I agree on the `php artisan migrate:drop --database="connection1, connection2"` command though, that seems nice

**Comment by navaneeth-raman-bhaskar** [comment]
Still not resolved?
migrate:fresh is not dropping all tables in different databases

**Comment by navaneeth-raman-bhaskar** [comment]
`php artisan migrate:refresh` command will help you to drop all tables from other connection also.
use `:refresh` instead of` :fresh`

**Comment by merlinro** [comment]
This is how I do it now: 
```
php artisan db:wipe --database A
php artisan db:wipe --database B
php artisan migrate:fresh --seed
```

**Comment by tylerwiegand** [comment]
i will admit this also frustrated me but it was such a specific use case i just made an alias to the effect of what @merlinro did.

`alias fresh="php artisan db:wipe --database a && php artisan db:wipe --database b && php artisan migrate:fresh --seed"`

**Comment by JohnnyWalkerDesign** [comment]
+1 Also having this issue with Laravel 8: When you run tests `RefreshDatabase` runs `migrate:fresh` which means all your tests fail when there's a secondary database. Not great :(

**Comment by nicStuff** [comment]
> You can decide which database you want to drop using the `--database` option

I hardly believe that you folks at laravel address issues by giving non-solutions. Why did you close the issue? It does appear ugly to have too many of them opened but if it exists it needs to be addressed and not to be put under a carpet.

**Comment by quickbutik-ronflorax** [comment]
Same issue here. There's no documentation on how to use testing with multiple databases either. This needs to be addressed.

**Comment by berni23** [comment]
Please reopen this issue!

**Comment by fhdalikhan** [comment]
+1

**Comment by lehien** [comment]
Same issue, though following @merlinro's way is ok.

**Comment by iteniasim** [comment]
i just moved the dropidexists from the down method to the top of up method, might not be ideal but works for me

**Comment by mozex** [comment]
+1

**Comment by fidderr** [comment]
same issue. migrate:fresh  should mean fully clearing all tables, for all databases, unless specified otherwise. 

it seems like that was the plan all along, because migrate:fresh gives a `table already exists` error, since it does want to rebuild the secondary database tables, but the dropping of the table failed.

**Comment by Itemshopp** [comment]
+1

**Comment by bralandealmeida** [comment]
> CommandStarting::class => [
>             ArtisanMigrateFresh::class
>         ]

It worked for me. Thanks!

**Comment by chuckienorton** [comment]
> CommandStarting::class => [
>             ArtisanMigrateFresh::class
>         ]

Perfect, thanks @geoffrex! Good solution for now. 

FYI for future implementers, CommandStarting class namespace is \Illuminate\Console\Events\CommandStarting

```
\Illuminate\Console\Events\CommandStarting::class => [
    \App\Listeners\ArtisanMigrateFresh::class
]
```

**Comment by rieves** [comment]
> Same problem here, for now I created an event listener that jumps in before `migrate:fresh` runs to wipe some databases:
> 
> ```
> <?php
> 
> namespace App\Listeners;
> 
> use Illuminate\Console\Events\CommandStarting;
> use Illuminate\Support\Facades\Artisan;
> 
> class ArtisanMigrateFresh
> {
>     /**
>      * Handle the event.
>      *
>      * @param  object  $event
>      * @return void
>      */
>     public function handle(CommandStarting $event)
>     {
>         if ($event->command == "migrate:fresh") {
>             $connections = config('database.refreshable');
> 
>             if (is_array($connections)) {
>                 foreach ($connections as $connection) {
>                     Artisan::call('db:wipe', [
>                         '--database' => $connection,
>                         '--force' => true,
>                     ]);
>                 }
>             }
>         }
>     }
> }
> ```
> 
> This works fine with my tests at the moment, but please point out any problems you see.

This bypasses the `confirmToProceed` production check that the `FreshCommand` does. By time it asks you, it would have wiped all your databases.

**Comment by erfaansabouri** [comment]
> Update 2023-06-23: As pointed out by @rieves below, this could wipe your production database, because it runs before `migrate:fresh` and thus bypasses the `confirmToProceed` production check of the migrate command. Since I only need it when running my tests, I added a `App::environment("testing")` check to avoid such mishaps. But you may want to add additional precautions, depending on how and where you use the `migrate:fresh`.
> 
> Same problem here, for now I created an event listener that jumps in before `migrate:fresh` runs to wipe some databases:
> 
> ```
> <?php
> 
> namespace App\Listeners;
> 
> use Illuminate\Console\Events\CommandStarting;
> use Illuminate\Support\Facades\Artisan;
> use Illuminate\Support\Facades\App;
> 
> class ArtisanMigrateFresh
> {
>     /**
>      * Handle the event.
>      *
>      * @param  object  $event
>      * @return void
>      */
>     public function handle(CommandStarting $event)
>     {
>         if ($event->command == "migrate:fresh" && App::environment("testing")) {
>             $connections = config('database.refreshable');
> 
>             if (is_array($connections)) {
>                 foreach ($connections as $connection) {
>                     Artisan::call('db:wipe', [
>                         '--database' => $connection,
>                         '--force' => true,
>                     ]);
>                 }
>             }
>         }
>     }
> }
> ```
> 
> You could hardcode which databases to wipe, but I added an array with the connection names I want to wipe to `/config/database.php` so it's all in one place:
> 
> ```
> <?php
> 
> return [
>     ...
>     'refreshable' => [
>         'maindb',
>         'otherdb'
>     ],
>     ...
> ];
> ```
> 
> And then hooked it up in the `app/Providers/EventServiceProvider.php`:
> 
> ```
> ...
> class EventServiceProvider extends ServiceProvider
> {
>     /**
>      * The event listener mappings for the application.
>      *
>      * @var array
>      */
>     protected $listen = [
>         CommandStarting::class => [
>             ArtisanMigrateFresh::class
>         ]
>     ];
> ...
> }
> ```
> 
> This works fine with my tests at the moment, but please point out any problems you see.

You saved my career <3.

**Comment by ahmadmhm** [comment]
I have this problem and did something like blow:

1. In migration file `protected $connection = 'location'; if (! Schema::hasTable('locations')) {Schema::create('locations');}`
2. in every test suit that i need that table, i've cleard table by Eloquent like this `Location::whereNotNull('id')->delete();`
Now other tests run properly.
