### ISSUE TITLE
mail::button component is not rendered correctly inside mail:message with indention.

### ISSUE THREAD

**Issue by asolopovas** [laravel/framework#21003]
- Laravel Version: 5.5.1
- PHP Version: v7.1.8
- Database Driver & Version: MariaDb 10.2.7

### Description:
`mail::button` component inside `mail::message` with additional elements renders inside the `<pre>` tag without closing `</table>`. It only happens when elements inside `mail::message` are indented like so.   
```
@component('mail::message')
    # Introduction

    The body of your message.

    @component('mail::button', ['url' => ''])
        Button Text
    @endcomponent

    Thanks,<br>
    {{ config('app.name') }}
@endcomponent
```
if everything is without indention like so: 
```
@component('mail::message')
# Introduction

The body of your message.

@component('mail::button', ['url' => ''])
Button Text
@endcomponent

Thanks,<br>
{{ config('app.name') }}
@endcomponent
```
it renders all components without an issue.

**Comment by aliusa** [comment]
Can confirm. Experiencing this since with 5.5.3


![screenshot from 2017-09-12 11-10-342](https://user-images.githubusercontent.com/9768908/30315192-c9847fec-97ab-11e7-841a-698ad55871e2.png)

**Comment by themsaid** [comment]
<img width="771" alt="screen shot 2017-09-14 at 2 23 25 pm" src="https://user-images.githubusercontent.com/4332182/30429402-9e0aea88-9957-11e7-879d-841181b5a434.png">

https://laravel.com/docs/5.5/mail

**Comment by proroot** [comment]
Try to reproduce!

**Comment by Byronsargeant** [comment]
@themsaid solved my issue right away. I don't understand why you have 3 thumbs down made sense to me straight away as I tabbed the contents of the mailable. Removed the tabs and hey presto!!!!

**Comment by Byronsargeant** [comment]
@asolopovas oh i see lol

**Comment by waleedakhlaq** [comment]
@asolopovas 
mail button is still not working in laravel email

**Comment by fklee** [comment]
The problem is always the same. 
As you add a button in the middle of component, the paragraphe is not reopen.
