### ISSUE TITLE
[5.5] Remove unnecessary lcfirst call

### ISSUE THREAD

**Issue by unstoppablecarl** [laravel/framework#21005]
https://github.com/laravel/framework/blob/1cb751263ed4cc26d632047c670ed82572a6b06c/src/Illuminate/Foundation/Auth/Access/AuthorizesRequests.php#L85

**Comment by Dylan-DPC** [comment]
This is not a bug. You can open a proposal in the laravel/internals repo

**Comment by paulofreitas** [comment]
Actually `Str::snake()` [will normalize the string anyhow](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Support/Str.php#L453), so I think you are free to send a PR changing this.
