### ISSUE TITLE
[testcase] Memory leak 

### ISSUE THREAD

**Issue by ccrims0n** [laravel/framework#21015]
- Laravel Version: 5.4.32
- PHP Version: 7.0.18
- Database Driver & Version: MySQL:  5.7.11

### Description:

Laravel is not freeing up memory during the test cases.
Our application has ~2000 test cases, with each test case the memory consumption increases by ~2MB. By the end of all the test cases, the total memory consumption is ~4224MB.

This led us to believe that there is a memory leak somewhere because of which the memory consumption is increasing. On going through the code base, we realised that the `flush()` in only resetting certain properties.
We are overriding the `\Illuminate\Foundation\Application::flush()` with following changes
```php
public function flush()
{
    parent::flush();

    $this->bootingCallbacks         = [];
    $this->bootedCallbacks          = [];
    $this->middlewares              = [];
    $this->serviceProviders         = [];
    $this->deferredServices         = [];
    $this->reboundCallbacks         = [];
    $this->resolvingCallbacks       = [];
    $this->afterResolvingCallbacks  = [];
    $this->globalResolvingCallbacks = [];
    $this->buildStack               = [];
}
```

Apparently, `$bootingCallbacks`, `$serviceProviders` and `$bootedCallbacks` properties are not freeing up the memory even when the `$this->app = null` is executing.

I want to discuss why exactly `flush()` is not resetting these properties.
I'll create a PR for this once this solution is approved as I saw that the last change in `flush()` was made 3 years ago.

### Stats

Before this change:
```
Time: 5.24 minutes, Memory: 4150.00MB
```

After this change:
```
Time: 4.71 minutes, Memory: 162.00MB
```

### Steps To Reproduce:
1. Write multiple test cases.
2. Print memory usage in `teardown()`
3. With each test case, memory consumption increases.

**Comment by dwightwatson** [comment]
Good find, I'm seeing similar improvements on one of my apps with ~400 tests. Always thought it was odd the memory usage got so high in the end.

    // Before change
    Time: 38.22 seconds, Memory: 578.00MB

    // After change
    Time: 37.65 seconds, Memory: 124.00MB

**Comment by themsaid** [comment]
This looks good to me, will ping Taylor about it this morning and see what he thinks. Thanks :)
