### ISSUE TITLE
Can't add composite index using Laravel Migrations

### ISSUE THREAD

**Issue by koushik72** [laravel/framework#21016]
- Laravel Version: 5.4
- PHP Version: 7.0.22
- Database Driver & Version: MySQL &  5.7.19-0ubuntu0.16.04.1

### Description:
I tried to add a composite index into MySQL using Laravel migration but it doesn't work and says
`1071 Specified key was too long; max key length is 3072 bytes (SQL: alter
   table `company_annc` add index `annc_info`(`company_name`, `annc`, `info`))`

This was my syntax for adding it
`$table->index(['company_name', 'annc', 'info'], 'annc_info');`

I added this line in `AppServiceProvider` in `boot` method
`Schema::defaultStringLength(191);`

But still, it didn't solve anything.
I also added this in `database.php` in `config`

`'charset' => 'utf8mb4',
'collation' => 'utf8mb4_unicode_ci',
'engine' => 'InnoDB ROW_FORMAT=DYNAMIC',`

The error only happens when I try adding the composite index. Apart from that, whenever I tried `auth`, it worked or I try adding just an index to a column, it works fine. 
I am not able to get what's happening. I have tried whatever I could find.
Please help.
Thanks in advance.

**Comment by themsaid** [comment]
Check StackOverflow: https://stackoverflow.com/questions/8746207/1071-specified-key-was-too-long-max-key-length-is-1000-bytes

Closing since it's not an issue in laravel.
