### ISSUE TITLE
[5.5] Disable Auto-Discovery with Configuration Flag

### ISSUE THREAD

**Issue by johannesschobel** [laravel/framework#21025]
- Laravel Version: 5.5.x
- PHP Version: 7.1.x
- Database Driver & Version: MySQL

### Description:
Hey community,

thank you very much for your awesome contributions with the new L5.5 framework - I really like the new features that are introduced. However, one particular feature is quite nasty in combination with my existing project -> the  `auto-discovery` feature.

The problem is:
In my project, I am not loading the `config` files from `/config` but from a different location in my project. Auto-discovered projects, however, try to load the config from `/config` - and if not found from `/vendor/...`. This causes my project to ignore the config files in my other folder (even though i am calling `mergeConfigFrom(...)` method from the `ServiceProvider` manually!

I know, that there is a dedicated `dont-discover` "flag" to set in your `composer.json` file to disable `auto-discovery` for specific packages. However, if you require packages (that also require packages that have `auto-discover`) you need to manually add *all* of these packages - which is quite nasty.

Is it possible to `disable auto-discovery` on a global Laravel configuration level? Because I really would like to include the respective ServiceProviders from 3rd-party-packages on my own, because I need to!

**Comment by themsaid** [comment]
You can use `*` to ignore all packages, this will prevent any kind of auto-discovery.

**Comment by johannesschobel** [comment]
Hey there, yes I am aware of the `*` parameter.. But wouldn't it be good to have a configuration flag to control this behaviour? Because people would actually search for a config flag to turn it off/on rather than to test this param in a `composer.json` file..

**Comment by themsaid** [comment]
If you can do it using the `*` why include other configurations and make things look more complicated than it is, just use `*` to indicate you want to ignore all packages :)

**Comment by johannesschobel** [comment]
because I think, that other people would rather look in a config file to turn on/off this feature than in the composer.json file.. I only stumbled across this setting-parameter when i _accidentally_ checked the main composer.json file from laravel/laravel and found it there.. 

If you would accept a PR i would make one?!
