### ISSUE TITLE
Declaration of Illuminate\Container\Container::make($abstract) must be compatible with Illuminate\Contracts\Container\Container::make($abstract, array $parameters = Array)

### ISSUE THREAD

**Issue by simonschaufi** [laravel/framework#21024]
- Laravel Version: 5.4.36
- illuminate/contracts: 5.5.2
- PHP Version: 7
- Database Driver & Version: doesn't matter

### Description:
Declaration of Illuminate\Container\Container::make($abstract) must be compatible with Illuminate\Contracts\Container\Container::make($abstract, array $parameters = Array)

In this commit https://github.com/illuminate/contracts/commit/336bdcdfaa6b109af376d736bc4557d9af11e7c2 a second parameter was introduced which is not compatible with laravel framework any more.

### Steps To Reproduce:
composer require illuminate/contracts

**Comment by themsaid** [comment]
You can't use these two together:

```
Laravel Version: 5.4.36
illuminate/contracts: 5.5.2
```

**Comment by simonschaufi** [comment]
ok. shouldn't composer automatically resolve the dependencies correctly when I don't specify them? I always thought that composer will install the latest POSSIBLE version
