### ISSUE TITLE
[5.5] listensFor in event listener unusable

### ISSUE THREAD

**Issue by jbbr** [laravel/framework#21030]
- Laravel Version: 5.5.2
- PHP Version: 7.1

### Description:

The [stubs for event listeners](https://github.com/laravel/framework/blob/bd352a0d2ca93775fce8ef02365b03fc4fb8cbb0/src/Illuminate/Foundation/Console/stubs/listener-duck.stub) have the property `$listensFor` to list events as introduces in #19917

But it looks like relevant changes in the `EventServiceProvider` have been reverted in 5ed4f5081f3674003919a79b346e256b162359cf 

It's confusing to have this attribute in the stub if it can't be used (yet?).

What are the reasons why the PR has been reverted? Maybe an updated PR could be included in a minor release.

**Comment by paulofreitas** [comment]
This was a feature introduced and reverted when the 5.5 release was still in development - so it's normal for this to happen. AFAIK the reasons weren't disclosed but probably it wasn't yet ready so it's better revert and discuss more.

But indeed the stubs changes went forgotten. 👍

**Comment by GrahamCampbell** [comment]
Thanks for the report. :+1:
