### ISSUE TITLE
[5.5] Got error when use 'const UPDATED_AT = null;'.

### ISSUE THREAD

**Issue by ThunderBirdsX3** [laravel/framework#21045]
- Laravel Version: 5.5.2
- PHP Version: 7.1.8
- Database Driver & Version: MySQL 5.7.18

### Description:
From #20948 about got an error when create `$subject->Message()->create(...);`.
I try to play around about it and I think i found some thing.

About const UPDATED_AT = null; in Message Model. I try to comment this code and add updated_at to table messages. The result is I didn't get any error. Then I try to uncomment and try again and I got an errors. I try one more time with const UPDATED_AT = 'created_at'; and it work. Could you look over this, Please.

### Steps To Reproduce:
Subject Model.
```
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Subject extends Model
{
  protected $fillable = [
    'client_id', 'title'
  ];

  public function Message()
  {
    return $this->hasMany(Message::class);
  }
}
```

Message Model.
```
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Message extends Model
{
  protected $fillable = [
    'user_id', 'type', 'data'
  ];

  // This code would got an error.
  const UPDATED_AT = null;
  // This code not.
  // const UPDATED_AT = 'created_at';

  public function Subject()
  {
    return $this->belongsTo(Subject::class);
  }
}
```
MessageController.
```
<?php namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Events\UserSendMessage;

use App\Subject;
use App\Message;

class MessageController extends Controller
{
  ...
  public function store(Request $request, Subject $subject)
  {
    $message = $subject->Message()->create(
      [
        'user_id' => \Auth::id(), 
        'type' => $request->type, 
        'data' => $request->data
      ]
    );

    return $message;
  }
  ...
}
```

With this route.
```
  Route::resource('/subjects/{subject}/messages', 'MessageController');
```

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.

**Comment by ThunderBirdsX3** [comment]
What the ... this is a bug, I got a bug. Are you trying?

**Comment by ThunderBirdsX3** [comment]
@themsaid

**Comment by ThunderBirdsX3** [comment]
@taylorotwell Could you help me?

![screen shot 2017-09-06 at 11 38 00 pm](https://user-images.githubusercontent.com/6513358/30123519-7fd8fdbc-935c-11e7-9866-66b2e7ded709.png)

**Comment by ThunderBirdsX3** [comment]
This is fresh install with `laravel new test55`
[test55.zip](https://github.com/laravel/framework/files/1281907/test55.zip)

**Comment by themsaid** [comment]
You can't set the timestamp constants to `null`

**Comment by ThunderBirdsX3** [comment]
@themsaid I see, But why in 5.4 is work and what the right way to go. Becuase i did't see any thing about it in document.

**Comment by rodrigopedra** [comment]
@ThunderBirdsX3 

I didn't test it out, but you could try to override the `setUpdatedAt()` method in your model to this:

~~~php
public function setUpdatedAt($value)
{
    return $this;
}
~~~

I think you won't need to override the `const UPDATED_AT` for this to work.

**Comment by a-komarev** [comment]
Confirming @rodrigopedra solution is working: #20901

**Comment by rodrigopedra** [comment]
@a-komarev 

I didn't see your solution on [#20901 (user-comment)](https://github.com/laravel/framework/issues/20901#issuecomment-326713868) before.

Thanks for linking to this issue.
