### ISSUE TITLE
[5.4][5.5] whitCount() problem with ordering

### ISSUE THREAD

**Issue by link08** [laravel/framework#21049]
- Laravel Version: 5.5.2
- PHP Version: 7.1.7
- Database Driver & Version: 10.1.25 MariaDB

### Description:
withCount() function doesn't work with relationship ordered

I know that it's useless to order a sub query just to obtain the count of some elements, but the problem happens when in the related element there are a GlobalScopes that a default order "orderBy"

### Steps To Reproduce:

This is the relationship

```php
class Designer extends Model
{
    public function images()
    {
        return $this->morphMany('App\Image', 'uploadable');
    }
}
```

#### What I Do
This is an example of the code that i exec for obtain a list of element with 'images_count'.
In the original versione I'm using a global scope for order the images.

```php
return \App\Designer::withCount(['images' => function($query){
    $query->orderBy('position');
}])->get();
```

and this is the query that I obtain:

```sql
select `designers`.*, (select count(*) from `images` where `designers`.`id` = `images`.`uploadable_id` and `images`.`uploadable_type` = App\Designer order by `position` asc) as `images_count` from `designers` where `designers`.`deleted_at` is null order by `position` asc
```
If you see the **App\Designer** string, it's without quote and this is the cause of the error.

#### How it work without order

PHP code:
```php
return \App\Designer::withCount('images')->get();
```

Sql result:
```sql
select `designers`.*, (select count(*) from `images` where `designers`.`id` = `images`.`uploadable_id` and `images`.`uploadable_type` = 'App\Designer') as `images_count` from `designers` where `designers`.`deleted_at` is null order by `position` asc
```

Without the ordering, the query builder add correctly the quote.

**Comment by Dylan-DPC** [comment]
This isn't a bug. You can't order a query by a column from its  related table in Eloquent using eager loading (even without a count).
