### ISSUE TITLE
Save/Create action on seeders

### ISSUE THREAD

**Issue by guduchango** [laravel/framework#21040]
- Laravel Version: #.#.#
- PHP Version: 7.0
- Database Driver & Version: mysql v.5.7.18

### Description:
When saving an object in the database, the ORM has different behaviors, if I do it from the seed or the path.

### Steps To Reproduce:

**Seed**
```
class TestSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $aliasArray = [
            'name' => 'details', 'slug' => 'detail','hello' => 'lalrlarla',
        ];
        $alias = Alias::create($aliasArray);
    }
}
```

**Route**
```
Route::get('Hello',function(){

    $aliasArray = [
        'name' => 'Detalles', 'slug' => 'detail','hello' => 'lalrlarla',
    ];
    $alias = Alias::create($aliasArray);

});
```

**Model**
```
class Alias extends Model
{
    protected $fillable = [
        'name',
        'slug',
        'description',
        'locked',
    ];
    protected $table = 'aliases';

    protected $casts = [
        'locked' => 'bool',
    ];
}
```
**In seed show this error**

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'hello' in 'field list' (SQL: insert into `aliases` (`name`, `slug`, `hello`, `updated_at`, `created_at`) values (Detalles, detail, lalrlarla, 2017-09-06  
   14:21:47, 2017-09-06 14:21:47))

**In route is ok**

**Comment by brunogaspar** [comment]
I believe that when seeding, the models are unguarded, therefore, Eloquent doesn't care about the fillable property (i might be wrong about this).

You can try to add the following before running the Alias::create

```php
Alias::reguard();
```

Otherwise, just remove the columns that doesn't exist before creating the entities and the seeder is properly fixed.

**Comment by Dylan-DPC** [comment]
Ya as @brunogaspar said this isn't a bug and can be closed. If you need more help you can ask in the forums or the slack channel

**Comment by guduchango** [comment]
Thank you for your time, I am clear. regards
