### ISSUE TITLE
resources withoutWrapping

### ISSUE THREAD

**Issue by shahafan** [laravel/framework#21052]
- Laravel Version: 5.5.1

### Description:
when trying to create a response of a nested resource that contain another resource without wrapping, the nested resource comes with data if it's not a collection after adding Resource::withoutWrapping() to the AppServiceProvider.
I don't want the resource to be wrapped in data at all, no matter on what level

### Steps To Reproduce:

```
class Categories extends Resource {
    public function toArray($request)
    {
        'id' => $this->id,
        'name' => $this->name,
        'subCategories' => SubCategories::collection($this->subCategories), // returns fine
        'chosen_sub' => $this->mergeWhen( // returns within a data
            isset($this->chosenSub),
            function () {
                return SubCategories::make($this->chosenSub);
            }
        ),
    }
}
```
@taylorotwell @themsaid

**Comment by Dylan-DPC** [comment]
This is not a bug. You can open a proposal in the laravel/internals repo

**Comment by shahafan** [comment]
How come it's not a bug?
The all idea of without wrapping is to allow a response clean of wrapping..
What would you suggest as a solution here?

**Comment by qerim** [comment]
@shahafan 

I'm facing the same issue:

If you add the `->data` object getter then this should remove thedata wrapping:

    $this->mergeWhen(
        isset($this->chosenSub),
        function () {
            return SubCategories::make($this->chosenSub);
        }
    )->data,

**Comment by huskicsuad** [comment]
The proposed solution using a closure with `->data` will fail when the condition is false, but can be fixed by wrapping with `optional`
```
            'prop1' => optional($this->mergeWhen(
                true,
                function () use ($pref, $request) {
                    return $this->loadsomeData1($pref, $request);
                }
            ))->data,
            'prop2' => optional($this->mergeWhen(
                false,
                function () use ($pref, $request) {
                    return $this->loadsomeData2($pref, $request);
                }
            ))->data,
```

i still dont understand why we are wrapping when developer explicitly says not to via `Resource::withoutWrapping()`
