### ISSUE TITLE
Builder updateOrInsert  problem

### ISSUE THREAD

**Issue by gaodeng** [laravel/framework#21050]
- Laravel Version: 5.4/5.5
- PHP Version:
- Database Driver & Version:

### Description:
Builder.php line 2161

public function updateOrInsert(array $attributes, array $values = [])
    {
        if (! $this->where($attributes)->exists()) {
            return $this->insert(array_merge($attributes, $values));
        }

        return (bool) $this->take(1)->update($values);
    }

the merge $attributes is not needed,and it cause problem.simply do the insert should be ok
$this->insert($values)

### Steps To Reproduce:

DB::connection('podcastdb')->table('favorite_podcast')->updateOrInsert(
            [
                ['podcast_id','=',$podcast_id,'and'],
                ['user_id','=',$user_id,'and']
            ],
            [
                'podcast_id'=>$podcast_id,
                'user_id'=>$user_id,
            ]
        );

if the record not exist,will cause error  

ksort() expects parameter 1 to be array, string given
--
in Builder.php (line 2105)

**Comment by themsaid** [comment]
````
[
['podcast_id','=',$podcast_id,'and'],
['user_id','=',$user_id,'and']
],
```

this is wrong,


Use this:

````
[
'podcast_id','=',$podcast_id,'and',
'user_id','=',$user_id,'and'
],
```

**Comment by gaodeng** [comment]
hi,themsaid,
it still cause error.  
why we need array_merge $attributes  here

**Comment by themsaid** [comment]
u can provide the first argument only if u want and leave the second empty

**Comment by gaodeng** [comment]
I can't undersand,if second argument is empty,why merge?,it don't make sense.
if the second argument is not empty,we should just use it ,no need to merge.
