### ISSUE TITLE
Is this a bug in ThrottleRequests while using api router with throttle middleware '['middleware'=>'throttle:5']'

### ISSUE THREAD

**Issue by zerozheng** [laravel/framework#21057]
- Laravel Version: 5.5.2

### Description:
While write a api with throttle middleware, i expect it can be requested 5 times per minutes, but it doesn't work.

### Steps To Reproduce:
1. add the route:
![1](https://user-images.githubusercontent.com/8703078/30143588-3aaaf954-93b9-11e7-9045-e517970472bb.png)

2. clear the cache:
![2](https://user-images.githubusercontent.com/8703078/30143701-d8782ddc-93b9-11e7-9f9e-94e5f570e0dc.png)

3. test with postman:
![3](https://user-images.githubusercontent.com/8703078/30143724-ef876c86-93b9-11e7-8bb5-2011a2dd7d33.png)
we could noticed that the X-RateLimit-Limit returned is 60, not 5, the one we specified in the routes. And what is more strange is the value 58 the X-RateLimit-Remaining returned. Why is 58? Before the test, we have clear the cache, and we have only one request here. If calculating with 60(the returned value of the X-RateLimit-Limit), it should be 59, because we have only one request here(60-1=59). However, the X-RateLimit-Remaining should be 4 if we consider our the limit we specified in the router.

**Comment by themsaid** [comment]
Make sure you remove the throttle settings in your `api` middleware group inside your Http/Kernel:

```
protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            // \Illuminate\Session\Middleware\AuthenticateSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],

        'api' => [
            'throttle:60,1', // remove
            'bindings',
        ],
    ];
```

**Comment by zerozheng** [comment]
@themsaid thank you very much! it work. In this case, is that means that the middleware specified doesn't override the default one?

**Comment by themsaid** [comment]
They're conflicting, so the results are un-expected :)

**Comment by zerozheng** [comment]
@themsaid thanks!
