### ISSUE TITLE
[5.5] Package discovery ignore list constructed wrong

### ISSUE THREAD

**Issue by afraca** [laravel/framework#21051]
- Laravel Version: 5.5
- PHP Version: 7.0
- Database Driver & Version:

### Description:
This is about the ServiceProvider discovery with the `php artisan package:discover` command.
When 2 packages you rely on have their own dont-discover array, they won't be merged correctly. That seems incorrect to me, it should result in a large dont-discover list. (I haven't really thought this through, just encountered it and in our case we want them to be merged)

### Steps To Reproduce:
- Have package 'a' with in its composer.json "dont-discover": ["foo"]
- Have package 'b' with in its composer.json "dont-discover": ["bar"]
- Have the composer.json in your application require "a", "b", "foo" and "bar"
- Observe that "bar" will be autodiscovered when executing `php artisan package:discover`

### Problematic location:
https://github.com/laravel/framework/blob/5.5/src/Illuminate/Foundation/PackageManifest.php#L122
Should not be `+=`

**Comment by Dylan-DPC** [comment]
I don't see this is a bug. You can make a proposal in the laravel/internals repo

**Comment by GrahamCampbell** [comment]
If you feel strongly about this, please send a PR with a failing unit test, and propose a fix in src. :)

**Comment by afraca** [comment]
I started a discussion at laravel/internals , if I don't see any major opponents of respecting the dont-discover of ALL packages, then I will try to make a PR somewhere in coming week. 

(Hope there are other tests dealing with composer.json files, or I'll have to figure out how to mock that part, might be tricky?)

**Comment by themsaid** [comment]
Moving to https://github.com/laravel/internals/issues/784

**Comment by afraca** [comment]
For future visitors, this was mostly addressed in this PR:
https://github.com/laravel/framework/pull/22443
