### ISSUE TITLE
@json awkwardness

### ISSUE THREAD

**Issue by KristofMorva** [laravel/framework#21068]
I might really miss something, but I think Laravel 5.5.3's new `@json` directive does not really seem to work the way it's supposed to do.

For example, with this input: `@json($places, JSON_HEX_APOS)` I get: `<?php echo json_encode(($places, JSON_HEX_APOS), 0, 512) ?>`. Which is actually realistic, because https://github.com/laravel/framework/blob/5.5/src/Illuminate/View/Compilers/Concerns/CompilesJson.php does not parse parse brackets/options like other Blade tags do. Also, as I have seen, it has no corresponding test (which is probably why it is included in the current release this way).

**Comment by themsaid** [comment]
Fixed that in https://github.com/laravel/framework/commit/2a25ee7f2f2d5e2cbc1397cc24abbb2838a9b439

thanks :)

**Comment by KristofMorva** [comment]
Thanks @themsaid, but won't that break if you have comma in the first expression? Like `@json(old('levels', []))`, our code is filled with things like these.

**Comment by themsaid** [comment]
Yeah it will, blade has a few edge cases and this is one of them, personally I'd just use php to encode to json if I'm not passing a variable
