### ISSUE TITLE
Suggestion: Replace nesbot/carbon with cakephp/chronos

### ISSUE THREAD

**Issue by KnutHelland** [laravel/framework#21066]
Sorry if this is the wrong way to post a suggestion. But I'm suggesting Laravel replaces Carbon with Chronos.

Reason: Because Carbon seems to me that it is hardly maintained. Bugs and pull requests have been open for months. For example this bug: https://github.com/briannesbitt/Carbon/issues/883

This would of course be a breaking change, so it would need to wait to a big new release. The best thing would of course be if someone could help briannesbitt to maintain the Carbon project and backport bugfixes from Chronos to Carbon...

**Comment by CupOfTea696** [comment]
This should be in [laravel/internals](https://github.com/laravel/internals)

**Comment by KnutHelland** [comment]
Ah, sorry, I didn't know. Closing this issue then.
