### ISSUE TITLE
PasswordBroker object creation exception

### ISSUE THREAD

**Issue by masterjus** [laravel/framework#21064]
- Laravel Version: 5.5.2
- PHP Version: 7.1
- Database Driver & Version: no database

### Description:
I got this exception 
``` 
Type error: Argument 2 passed to Illuminate\Auth\Passwords\PasswordBroker::__construct() must implement interface Illuminate\Contracts\Auth\UserProvider, null given, called in
  .../vendor/laravel/framework/src/Illuminate/Auth/Passwords/PasswordBrokerManager.php on line 75
```

This exception happens because on line there's code:
```php
<?php
        return new PasswordBroker(
            $this->createTokenRepository($config),
            $this->app['auth']->createUserProvider($config['provider'] ?? null)
        );
```
that makes possible to pass `null` as the second argument to the PasswordBroker constructor.
This is impossible because of PasswordBroker constructor:
```php
<?php
    public function __construct(TokenRepositoryInterface $tokens,
                                UserProvider $users)
```

### Steps To Reproduce:
- require barryvdh/laravel-ide-helper composer package
- execute `php artisan ide-helper:meta`

**Comment by themsaid** [comment]
This looks like a mis-configuration on your side, please make sure you have the correct configuration in your `config.auth.passwords`, looks like Laravel is unable to create the provider assigned.
