### ISSUE TITLE
[5.5] Json serialization is not backward compatable

### ISSUE THREAD

**Issue by aleksandrlat** [laravel/framework#21079]
- Laravel Version: 5.5.3
- PHP Version: 7.1
- Database Driver & Version: not relevant

### Description:
The change was introduced with #17875

Response in router is wrapped in JsonResponse instead of just Response. This change introduced other order of checks. Before we had in [Response](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Http/Response.php#L68):
```
if ($content instanceof Jsonable) {
    return $content->toJson();
} elseif ($content instanceof Arrayable) {
    return json_encode($content->toArray());
}
return json_encode($content);
```

But now we have in [JsonResponse](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Http/JsonResponse.php#L60):
```
if ($data instanceof Arrayable) {
    $this->data = json_encode($data->toArray(), $this->encodingOptions);
} elseif ($data instanceof Jsonable) {
    $this->data = $data->toJson($this->encodingOptions);
} elseif ($data instanceof JsonSerializable) {
    $this->data = json_encode($data->jsonSerialize(), $this->encodingOptions);
} else {
    $this->data = json_encode($data, $this->encodingOptions);
}
```

So in case class implements for example Jsonable and Arrayable and implementation of ```toJson``` method is not like this:
```
public function toJson($options = 0)
{
    return json_encode($this->toArray(), $options);
}
```
We will have different result now.

### Steps To Reproduce:

Create class like this:
```
class Foo implements Arrayable, Jsonable
{
    public function toArray()
    {
        return ['value' => 'bar'];
    }

    public function toJson($options = 0)
    {
        return json_encode(['value' => 'foo'], $options);
    }
}
```

From Controller's action return:
```
public function action()
{
    return new Foo;
}
```

Before #17875 result was ```{value: 'foo'}```, but now we have ```{value: 'bar'}```

**Comment by rodrigopedra** [comment]
@aleksandrlat 

Check PR #21136 it got merged today.
