### ISSUE TITLE
Add facade for Illuminate\Validation\Rule

### ISSUE THREAD

**Issue by ryanmortier** [laravel/framework#21073]
- Laravel Version: 5.5.2
- PHP Version: 7.1
- Database Driver & Version: MariaDB 10.1

### Description:
There doesn't seem to be a facade for `Illuminate\Validation\Rule`.

For example when using the `Rule` class in a controller, should there be a `Rule` facade?

I'm so used to using `use Illuminate\Support\Facades\[Class Here];` without the need to look up the actual namespace but today I had to look through the documentation to find that I needed to be using `Illuminate\Validation\Rule` instead.

**Comment by devcircus** [comment]
It seems that with the way Rule is currently setup, all methods are static, so you just call the static method against the class name. This isn't a use-case for a facade. Laravel facades call instance methods with the static syntax.

**Comment by Dylan-DPC** [comment]
This is not a bug. You can open a proposal in the laravel/internals repo
