### ISSUE TITLE
[HELP] /public/vendor folder on share hosting.

### ISSUE THREAD

**Issue by taimaiduc** [laravel/framework#21084]
- Laravel Version: 5.5
- PHP Version: 7.0
- Database Driver & Version:

I am using .htaccess to remove the pubic path. 
But When / vendor / css / xxx.css It throw 404 
```
<IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteCond %{REQUEST_URI} !^public
    RewriteRule ^(.*)$ public/$1 [L]
</IfModule>
```
[![https://gyazo.com/b6ded5f1da6d9f21c89ecfcdaec6f761](https://i.gyazo.com/b6ded5f1da6d9f21c89ecfcdaec6f761.png)](https://gyazo.com/b6ded5f1da6d9f21c89ecfcdaec6f761)

I have to change folder to vendor2 it work again
```
if (!function_exists('admin_asset')) {

    /**
     * @param $path
     *
     * @return string
     */
    function admin_asset($path)
    {
        $path = str_replace('vendor', 'vendor2', $path);
        return asset($path, config('admin.secure'));
    }
}
```
[![https://gyazo.com/fef8c07c7cee20452c0fe7e966c6bd18](https://i.gyazo.com/fef8c07c7cee20452c0fe7e966c6bd18.png)](https://gyazo.com/fef8c07c7cee20452c0fe7e966c6bd18)

I think request to root vendor on a server.

**Can you help me how to fix it.** :(

**Comment by srmklive** [comment]
This repo is for bug reporting only. Kindly use forums to solve your issue.
