### ISSUE TITLE
[Suggestion] to have a dedicated delay per channel

### ISSUE THREAD

**Issue by daison12006013** [laravel/framework#21082]
- Laravel Version: 5.4.x
- PHP Version: 7.1
- Database Driver & Version: MySql

### Description:
There is no way for us to make a delay for specific channel, Upon checking `NotificationSender`, based on my understanding, the loop call under [L51](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Notifications/NotificationSender.php#L151) only uses the direct value of notification delay.

We have the `sendNow()` which only possible to inject channels in real time sending, however on `send()` we don't have the option to inject, so an option would probably help to, or check out my suggestion below.

### Suggestion:
Allow the property `$delay` to be an array, if it's an array, we will map the channel based on value.

```
public $delay = [
    'push_notification' => Carbon...,
    'email' => Carbon...,
    'database' => Carbon...,
];
```

Since we can't inject carbon directly under the property, a dev can inject the call thru the constructor instead, which is a good work around.

On `NotificationSender`, the mapping will be based on the key channel, if the key doesn't exists, the default value will always be 0.

In reality, we want to limit sending of push notifications when it's evening.

---

Another option is to have a method call `{$channel}Delay()` if exists then we will use that, else we will use 0, so each notifications we can set the delay per channel too.

**Comment by Dylan-DPC** [comment]
This is not a bug. You can open a proposal in the laravel/internals repo

**Comment by daison12006013** [comment]
Yeah you are correct @Dylan-DPC
