### ISSUE TITLE
502 Bad Gateway  The server returned an invalid or incomplete response.

### ISSUE THREAD

**Issue by maguilar92** [laravel/framework#21087]
- Laravel Version: 5.1.2
- PHP Version: 7.1.4

### Description:
When goes to page give me this error after update.
If route don't exists laravel works:
Sorry, the page you are looking for could not be found.

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by maguilar92** [comment]
This occurs since I upgrade the version so it must be for an error or change in version 5.5

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
