### ISSUE TITLE
[5.5] Request has wrong alias

### ISSUE THREAD

**Issue by jimgwhit** [laravel/framework#21097]
- Laravel Version: 5.5.3
- PHP Version: 7.1.7-0
- Database Driver & Version:mysql 5.7

### Description: In aliases it has 
```
'Request' => Illuminate\Support\Facades\Request::class,
```
trying to 
```
use Illuminate\Support\Facades\Request;
// or
use Request;     //which should work
```
throws an error

Call to undefined method Illuminate\Support\Facades\Request::input()

Of course putting
```
use Illuminate\Http\Request;
```
works as expected, docs are correct but the aliases aren't.

### Steps To Reproduce:
```
public function view(Request $request)
    {
        $dogid = $request->input('dogid');
        echo $dogid;
        // more code
```
And I noticed on the laravel/laravel github site there was no place for issues.  Shouldn't there be?

**Comment by devcircus** [comment]
Request::input

**Comment by jimgwhit** [comment]
EDIT:

Found out what's going on here, Taylor seems to like static calls also, so
```
use Illuminate\Http\Request;
//works with
$dogid = $request->input('dogid');
```

but

```
use Illuminate\Support\Facades\Request;
//works with
$dogid = Request::input('dogid');    // a static call
```

Somehow in ver 5.1 never had such errors.

I kinda like the __callStatic thing myself sometimes.
