### ISSUE TITLE
[Eloquent] No error on missing value for "NOT NULL" column

### ISSUE THREAD

**Issue by aik099** [laravel/framework#21101]
- Laravel Version: 5.5.3
- PHP Version: 7.0.23 (through FCGI on Apache)
- Database Driver & Version: MySQL 5.5.27

### Description:

When attempting to persist model without providing values for all `NOT NULL` columns the HTTP connection terminates (I'm setting `Internal Server Error`). After debugging found out, that this happens at the moment, when prepared statement is executed.

### Steps To Reproduce:

Create DB table using this migration:

```php
Schema::create('topics', function (Blueprint $table) {
    $table->increments('id');
    $table->string('title');
    $table->text('body');
    $table->timestamps();
});
```

Create model in `app/Topic.php` file:

```php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Topic extends Model
{
    protected $guarded = [];
}
```

In controller action execute this code:

```php
Topic::create(array(
    'title' => 'topic model',
));
```

If I'm doing same thing though `DB` facade, then I'm getting correct error, that value for `NOT NULL` column isn't provided:

```php
DB::table('topics')->insert(array(
    'title' => 'topic model',
    'updated_at' => '2017-09-08 22:55:52',
    'created_at' => '2017-09-08 22:55:52',
));

// "SQLSTATE[HY000]: General error: 1364 Field 'body' doesn't have a default value (SQL: insert into `topics` (`title`, `updated_at`, `created_at`) values (topic model, 2017-09-08 22:55:52, 2017-09-08 22:55:52))"
```

Eloquent is doing same `DB::insert` internally so I have no idea why it's call version fails.

**Comment by jmarcher** [comment]
This is a MySQL issue, if you want that the body column is empty you should either make it nullable or set an empty string as a value

**Comment by aik099** [comment]
> This is a MySQL issue, if you want that the body column is empty you should either make it nullable or set an empty string as a value

I know that (see bottom of my previous post), thanks. I'm reporting bug, because same MySQL error isn't reported at all when record is inserted through the Eloquent model.

**Comment by niteshkumarniranjan** [comment]
Can anyone answer #21100

**Comment by Dylan-DPC** [comment]
This isn't a laravel bug

**Comment by aik099** [comment]
Using `DB::insert` directly shows correct, error, but when Eloquent calls it error isn't show. Probably Eloquent affects error reporting somehow.

Can't you reproduce what I've reported?

**Comment by aik099** [comment]
Any more details you can share about why this isn't a bug?
