### ISSUE TITLE
Base table or view already exists: 1050 Table 'users' already exists

### ISSUE THREAD

**Issue by niteshkumarniranjan** [laravel/framework#21100]
- Laravel Version: 5.5.3
- PHP Version: 7.1
- Database Driver & Version: MariaDB 10.1.26

### Description:
php artisan migrate

  [Illuminate\Database\QueryException]
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'users' already exists (SQL: create table `users` (`id` int unsigned not null aut
  o_increment primary key, `name` varchar(255) not null, `email` varchar(255) not null, `password` varchar(255) not null, `remember_token` varchar
  (100) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate utf8mb4_unicode_ci engine = InnoDB R
  OW_FORMAT=DYNAMIC)

  [PDOException]
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'users' already exists

### Steps To Reproduce:
laravel new website
php artisan make:migration create_lists_table --create=lists
php artisan migrate

### Problem
It Creates users table and give error but not creating lists table

**Comment by huglester** [comment]
there must be existing table 'users' already created, even before install

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by niteshkumarniranjan** [comment]
I have Solved My Problem Myself
by Changing My create_users_table.php
```
<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateUsersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::dropIfExists('users');
        Schema::create('users', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->string('email')->unique();
            $table->string('password');
            $table->rememberToken();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('users');
    }
}

```

**Comment by Dylan-DPC** [comment]
Then close the issue

**Comment by tzone85** [comment]
@niteshkumarniranjan thanks, your solution helped me too, viz, Schema::dropIfExists.

**Comment by shaangola** [comment]
how can we migrate without losing out the data?

**Comment by benmi18** [comment]
drop the database
create it again
php artisan migrate // will create all tables

php artisan make:migration create_test_table // create new migration file for test
php artisan migrate //check if works

it worked or me!
Good Luck

**Comment by abdo2000320** [comment]
@benmi18  thank you so much you have saved my life!
