### ISSUE TITLE
artisan make:policy typehints the wrong user class

### ISSUE THREAD

**Issue by poisa** [laravel/framework#21117]
- Laravel Version: 5.5.0
- PHP Version: 7.0.20

### Description:
I inherited an app written in Spanish where they renamed the User class to Usuarios. When creating a policy via artisan, the typehints are displaying the incorrect class.

### Steps To Reproduce:

Change the default user model in `config/auth.php`:

``` php
    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\Models\Usuarios::class,
        ],
    ],
```

Then run `artisan make:policy FooPolicy --model=Foo`. 

The generated policy has the correct class in the docblocks but the default one in the type hints:

```php
<?php

namespace App\Policies;

use App\Models\Usuarios;
use App\Foo;
use Illuminate\Auth\Access\HandlesAuthorization;

class FooPolicy
{
    use HandlesAuthorization;

    /**
     * Determine whether the user can view the foo.
     *
     * @param  \App\Models\Usuarios  $user
     * @param  \App\Foo  $foo
     * @return mixed
     */
    public function view(User $user, Foo $foo)
    {
        //
    }

    /**
     * Determine whether the user can create foos.
     *
     * @param  \App\Models\Usuarios  $user
     * @return mixed
     */
    public function create(User $user)
    {
        //
    }

    /**
     * Determine whether the user can update the foo.
     *
     * @param  \App\Models\Usuarios  $user
     * @param  \App\Foo  $foo
     * @return mixed
     */
    public function update(User $user, Foo $foo)
    {
        //
    }

    /**
     * Determine whether the user can delete the foo.
     *
     * @param  \App\Models\Usuarios  $user
     * @param  \App\Foo  $foo
     * @return mixed
     */
    public function delete(User $user, Foo $foo)
    {
        //
    }
}
````

**Comment by Dylan-DPC** [comment]
The code that is generated from these commands are stored "statically" in stubs. Certain things are computed but I feel 90% of the users use a "User" model.

**Comment by themsaid** [comment]
Feel free to open a PR to support this, currently it assumes a standard User model.

**Comment by poisa** [comment]
@themsaid I can't seem to find any unit tests for this but I may be looking in the wrong place. If you could point me in the right direction I may be able to open a PR.
