### ISSUE TITLE
Many to Many Detach after loading relation doesn't detach in object

### ISSUE THREAD

**Issue by thc1967** [laravel/framework#21111]
- Laravel Version: 5.5.1
- PHP Version: 7.1.6
- Database Driver & Version: sqlite memory, mysql 

### Description:
Using ->detach() on either side of a many-to-many relationship *after loading the relationship* removes data from the pivot table but does not remove related objects from the relation collection.

### Steps To Reproduce:

```PHP
    // In the User class
    public function clients()
    {
        return $this->belongsToMany(Client::class);
    }

    // In the Client class
    public function users()
    {
        return $this->belongsToMany(User::class);
    }
```

I wrote a PHPUnit test case to demonstrate. My PHPUnit uses SQLite memory, but I don't think the database matters because the database part works as expected.

```PHP
    /** @test */
    public function basic_user_client_detach_test()
    {
        $user = create(User::class);
        $clients = create(Client::class, [], 2);
        $user->clients()->attach($clients);

        // Important step - get clients in memory with certainty
        // If we skip this, all tests pass.
        $userClients = $user->clients;

        $user->clients()->detach([1,2]);

        // These pass, proving the records are detached in the database.
        $this->assertDatabaseMissing('client_user', [
            'client_id' => $clients[0]->id,
            'user_id' => $user->id,
        ])->assertDatabaseMissing('client_user', [
            'client_id' => $clients[1]->id,
            'user_id' => $user->id,
        ]);
        $this->assertEquals(0, DB::table('client_user')->count());

        // If we force the refresh with the following line, the next test passes.
        // $user = User::findOrFail($user->id);
        // Using $user->fresh() doesn't work as expected - clients stay in the user.

        // This fails, proving they're still in memory.
        $this->assertEquals(0, $user->clients->count());
    }
```

**Comment by thc1967** [comment]
The same seems to be true if we use `->sync([...])` to remove related objects. They are removed from the pivot table but remain on the in-memory object's collection.

**Comment by decadence** [comment]
If you loaded relation it remains the same whatever you do because it's cached. You need to reload it explicitly.

**Comment by thc1967** [comment]
So that's on purpose? Seems unexpected that I'd tell the framework to remove data from a model, the framework doesn't object in any way, yet the data is still there.

**Comment by decadence** [comment]
Collection (relation) is not updated once it's fetched. You need to `load`.
