### ISSUE TITLE
Change in database config file has caused in memory sqlite testing problem

### ISSUE THREAD

**Issue by Gramcito** [laravel/framework#21121]
- Laravel Version: 5.5.3
- PHP Version: 7.1
- Database Driver & Version: sqlite in memory

### Description:
New install of Lavarel 5.5.3 has changed the config/database.php sqlite setting to use 
`database_path(env('DB_DATABASE', 'database.sqlite'))`
from
`env('DB_DATABASE', database_path('database.sqlite'))`

This actually returns a full path such as:
`
array:3 [
  "driver" => "sqlite"
  "database" => "/Users/username/code/laraplay/database/:memory:"
  "prefix" => ""
]
`
rather than:
`array:3 [
  "driver" => "sqlite"
  "database" => ":memory:"
  "prefix" => ""
]`

which then means in-memory sqlite settings for testing try to unlink a physical file. E.g.
1) Tests\Feature\LandingPageTest::shows_a_landing_page_for_adding_data
ErrorException: unlink(/Users/username/code/laraplay/database/:memory:): No such file or directory

because the in memory database checks all fail. 

### Steps To Reproduce:
Install, set phpunit.xml file to use in-memory sqlite : 
`
<env name="DB_CONNECTION" value="sqlite"/>
<env name="DB_DATABASE" value=":memory:"/>
`

Apologies if this is not a bug or issue, but nothing in the docs about this change and a Lavavel install from last Thursday (7th sept) worked fine but same setting used on an install today throws errors as above.

**Comment by themsaid** [comment]
This change was reverted, please make sure you have the latest code.
