### ISSUE TITLE
Validator::extendDependent doesn't extend the Validator as expected

### ISSUE THREAD

**Issue by markwalet** [laravel/framework#21125]
- Laravel Version: 5.5.3
- PHP Version: 7.1.3

### Description:
I can only validate arrays when I use the normal extend method. I want to use the extendDependent method for this because the `$parameters` array will be transformed when the method is flagged dependent.

### Steps To Reproduce:
Add the following extensions for your Validator in the AppServiceProvider:

```
Validator::extendDependent('greater_than', function($attribute, $value, $parameters, $validator) {
});
Validator::extend('greater_than', function($attribute, $value, $parameters, $validator) {
     $min_field = $parameters[0];
     $data = $validator->getData();

     $min_value = array_get($data, $min_field);

     return $value > $min_value;
});
```

This will work. When you just use the `extendDependent` method, the extension will not be called and the following exception is thrown:

`BadMethodCallException thrown with message "Method [validateGreaterThan] does not exist."`

**Comment by themsaid** [comment]
```
Validator::extendDependent('greater_than', function($attribute, $value, $parameters, $validator) {
            $min_field = $parameters[0];
            $data = $validator->getData();

            $min_value = array_get($data, $min_field);

            return $value > $min_value;
        });
```

Works for me.

**Comment by markwalet** [comment]
Hmm, I tried it on my production server and it also worked. Any ideas? I am using Homestead

**Comment by themsaid** [comment]
hmm not sure really, it should work.

**Comment by themsaid** [comment]
Closing since we're unable to replicate.

**Comment by markwalet** [comment]
Isn't there anything I can do to check?

**Comment by themsaid** [comment]
Not sure really, try to trace the registration inside the validation and see where it falls.
