### ISSUE TITLE
Eager loading returns empty when different connections implemented

### ISSUE THREAD

**Issue by vinsonyung** [laravel/framework#21120]
- Laravel Version: 5.5.3
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7

### Description:
I use two separate connections for two databases, articles and article comments. Laravel failed to get relationship data with eager loading.

### Steps To Reproduce:

Article model,
```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    /**
     * The connection name for the model.
     *
     * @var string
     */
    protected $connection = 'article';

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'articles';

    public function comments()
    {
        return $this->hasMany(ArticleComment::class, 'article_id', 'id');
    }
}
```

ArticleComment model:
```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ArticleComment extends Model
{
    /**
     * The connection name for the model.
     *
     * @var string
     */
    protected $connection = 'comments';

    protected $fillable = [
        'id',
        'article_id',
        'user_id',
        'content',
        'ip',
        'active'
    ];

    public function article()
    {
        return $this->belongsTo(Article::class, 'article_id');
    }
}
```

In Artisan,

I can get article comments by
```php
$article = App\Article::first()
$article->comments
```

But fail by
```php
$article = App\Article::with('comments')->first()
```

**Comment by themsaid** [comment]
Can't replicate your issue, also if you do `$article->comments` with or without eager loading you'll get results if the model has records.

Check your code or try to replicate the same steps you shared on a fresh laravel installation and you'll see that it's working.

**Comment by vinsonyung** [comment]
@themsaid Finally I figured out that it is the column type problem. In the article database(other project), the article_id is varchar. However, I created a bigInteger column in article_comments.
