### ISSUE TITLE
Rule::in() unexpected behaviour changed from 5.5.2 to 5.5.3?

### ISSUE THREAD

**Issue by ryanmortier** [laravel/framework#21133]
- Laravel Version: 5.5.3
- PHP Version: 7.1
- Database Driver & Version: MariaDB 10.1

### Description:
I was developing in `5.5.2` today with everything working. I'm assigning a variable like this:

    $branches = Branch::all();

Then using the `in` validation rule like this:

    'branch' => ['required', Rule::in($branches->pluck('code'))],

I did a composer update which updated Laravel to `5.5.3` and now my validation fails. I've worked around the issue by adding `->all()` to the end of the `pluck()` like this:

    'branch' => ['required', Rule::in($branches->pluck('code')->all())],

Am I doing something wrong or did something break?

**Comment by devcircus** [comment]
Looks like #21012 may have changed something.

**Comment by balping** [comment]
Rule::in accepts arrays only. According to the docblocks, the parameter should have been an array before my commit too.

https://github.com/balping/framework/blob/68ba973ab944c46de1a1eb1dc88ede4e4cac6464/src/Illuminate/Validation/Rules/In.php#L12-L17

**Comment by ryanmortier** [comment]
I see. It definitely was working with a Collection before but I can modify my code to use an array instead. Thanks for clearing that up.
