### ISSUE TITLE
[5.5] Validation rule for input field with type file

### ISSUE THREAD

**Issue by jagDanJu** [laravel/framework#21139]
- Laravel Version: 5.5.3
- PHP Version: 7.1.8

### Description:

If i add an Validation for an input field with type file. 
I´m use the following rule: `mimes:csv,xlsx,xls`

But if i apply a .csv File it shows me that the file isnt a .csv file... But it is a .csv File

**Comment by themsaid** [comment]
Exception guessing depends on multiple factors, Laravel uses Symfony's `ExtensionGuesser` which does the best it can do to guess the extension, for instance I can't replicate your issue and validation works fine. Try using `mimetypes` instead.

**Comment by shahin7511** [comment]
@

> * Laravel Version: 5.5.3
> * PHP Version: 7.1.8
> 

Same thing happening to me. is there any solution ? 
> ### Description:
> If i add an Validation for an input field with type file.
> I´m use the following rule: `mimes:csv,xlsx,xls`
> 
> But if i apply a .csv File it shows me that the file isnt a .csv file... But it is a .csv File

`public function rules()
    {
        return [
            'file' => 'required|mimetypes:csv',
        ];
    }`
