### ISSUE TITLE
json_encode error when  Model  using array  casts  and default value 

### ISSUE THREAD

**Issue by dolia** [laravel/framework#21135]
- Laravel Version: 5.2.45
- PHP Version:7.1.7 

### Description:

Hi~

I would like to use  the 'casts' to convert an  array to json in my Team Model ,and I also set the default value to the 'photo' attribute ,like this:

```
class Team extends Model
{

   protected $attributes = [

          'photos'=>[],

    ];

    protected $casts = [
        'photos' => 'array',
    ];

}

```

But when I try to New a Object of Team, disappear the error:

new Team([])

`json_decode() expects parameter 1 to be string, array given`

**Comment by themsaid** [comment]
Laravel 5.2 is not supported anymore.
