### ISSUE TITLE
request()->has('any') with empty or null value always return TRUE

### ISSUE THREAD

**Issue by madun92** [laravel/framework#21134]
- Laravel Version: 5.5.2
- PHP Version: 7.1.7

Description:
request()->has('any') with empty or null value always return TRUE

**Comment by dwightwatson** [comment]
`has` just tells you if the request has input with that key. Use `filled` to check that it actually has a value.

This is noted in the Laravel 5.5 upgrade guide under "Requests".

**Comment by madun92** [comment]
ah i see, thanks @dwightwatson

**Comment by w1n78** [comment]
is this the reason why when i use this code in 5.5

```
DB::User->where(function($query) use($request) {
  if ($request->has('username')) {
    $query->where('username', 'LIKE', '%'.$request->username.'%');
  }
})->get();
```

if no value is given or null, then the query becomes something like below.

```
SELECT * FROM users WHERE username LIKE '%null%';
```

because in 5.4, the query is

```
SELECT * FROM users;
```

when there is no value or null
