### ISSUE TITLE
[5.5] Rule objects is not working

### ISSUE THREAD

**Issue by stefensuhat** [laravel/framework#21148]
- Laravel Version:5.5.7
- PHP Version: 7.1
- Database Driver & Version: Maria DB 10.1

```
PasswordController.php

$request->validate([
            'old_password'              => [new OldPassword],
            'new_password'              => 'required|numeric|min:6|confirmed',
            'new_password_confirmation' => 'required'
 ]);

Rule\OldPassword.php

 /**
     * Determine if the validation rule passes.
     *
     * @param  string $attribute
     * @param  mixed $value
     * @return bool
     */
    public function passes($attribute, $value)
    {
       return false;
    }

    /**
     * Get the validation error message.
     *
     * @return string
     */
    public function message()
    {
        return __('validation.custom.old_password.required');
    }
```

I wanted to try new validation on Laravel 5.5 using Rules. 

But it always pass the validate even though I put `return false` on the Rule section

**Comment by themsaid** [comment]
> not working as expected

Please explain.

**Comment by stefensuhat** [comment]
@themsaid it always pass the rules. even it still exists.

**Comment by devcircus** [comment]
Been using Rule objects since before the official release and all works well. Thanks everyone.

**Comment by stefensuhat** [comment]
@themsaid sorry for the delay. need to closed it before because of some issue.

I've updated my question about it.

**Comment by AlexeyPlodenko** [comment]
He is right. There is a problem. It is in the file Validator.php in method validateAttribute at line `if ($rule == '') { return; }`

And if the class implementing RuleContract will cast to boolean false, then the passes() method won't be called.

```
class MyRule implements RuleContract
{
	protected $value;

	public function passes($attribute, $value): bool
	{
		return true;
	}

       public function message(): string
	{
		return 'The :attribute is not valid.';
	}
}
```

**Comment by themsaid** [comment]
> class implementing RuleContract will cast to boolean

Why would it cast to coolean?
