### ISSUE TITLE
[5.5.3] Bug in FormRequest, authorize() method,  expected response when file is present.

### ISSUE THREAD

**Issue by eduarguzher** [laravel/framework#21146]
- Laravel Version: 5.5.3
- PHP Version: 7.1.8
- Database Driver & Version: sqlite - :memory:

### Description:
A Test case that does the following: 

1. Makes a FakeFile upload with json as indicated [in docs.](https://laravel.com/docs/5.5/http-tests#testing-file-uploads)
2. The request is "intercepted" by a FormRequest that DOES NOT authorizes the request ( for some reasonlogic bussiness).
3. The framework responds with an `Illuminate\Auth\Access\AuthorizationException` that in the end should be converted to a `403` status.

3.1. Currently this step is throwing another exception given by [this line](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Http/JsonResponse.php#L71) of the framework. 
    
```
PHPUnit 6.3.0 by Sebastian Bergmann and contributors.

E                                                                   1 / 1 (100%)

Time: 149 ms, Memory: 14.00MB

There was 1 error:

1) Tests\Feature\ExampleTest::testBasicTest
InvalidArgumentException: Type is not supported

/Users/eguzman/Documents/Code/testfileupload/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php:71
/Users/eguzman/Documents/Code/testfileupload/vendor/symfony/http-foundation/JsonResponse.php:50
/Users/eguzman/Documents/Code/testfileupload/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php:27
/Users/eguzman/Documents/Code/testfileupload/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:435
/Users/eguzman/Documents/Code/testfileupload/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:186
/Users/eguzman/Documents/Code/testfileupload/app/Exceptions/Handler.php:51
/Users/eguzman/Documents/Code/testfileupload/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:326
/Users/eguzman/Documents/Code/testfileupload/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:120
/Users/eguzman/Documents/Code/testfileupload/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:294
/Users/eguzman/Documents/Code/testfileupload/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:266
/Users/eguzman/Documents/Code/testfileupload/tests/Feature/ExampleTest.php:25
```

That's all the information I could get, I think the expected behavior is to get a response with the unauthorized message as it happens when no file is attached to the request.
You can prove that the FakeFile is giving the error by not sending it in the request, in this case the response given is

```
 "message" => "This action is unauthorized."
  "exception" => "Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException"
... 
```

### Steps To Reproduce:

1. Fresh laravel 5.5.3
2. In your `tests/Feature/ExampleTest.php` replace the `testBasicTest` method with 

```php
 public function testBasicTest()
    {
        Storage::fake();
        $response = $this->json('POST', '/test-file', [
                'rut' => UploadedFile::fake()->image('avatar.jpg')
            ]);
        $response->assertStatus(403); //unauthorized
    }
```
3. in the terminal type `php artisan make:request FileFormRequest` which will make a FormRequest namespaced in `App\Http\Requests\FileFormRequest`  that by default gives

```php
public function authorize()
    {
        return false;
    }
```

3. In `routes/web.php` add the next endpoint

```php 
Route::post('/test-file', function (App\Http\Requests\FileFormRequest $request) {
    dd('stop');
});
```

4. Run the phpunit on `Feature/ExampleTest.php` and you will see the exception happen and not the test pass

EDIT: the following [repo](https://github.com/eduarguzher/testfileupload) has the __Steps to reproduce__ already done

**Comment by Dylan-DPC** [comment]
@eduarguzher Link your repo in case anyone wants to reproduce the issue

**Comment by themsaid** [comment]
A fix was submitted, thanks :)
