### ISSUE TITLE
Non-static method '**' should not be called statically

### ISSUE THREAD

**Issue by mitoop** [laravel/framework#21158]
- Laravel Version: >5.4.28
- PHP Version: 7.1.8
- Database Driver & Version: N/A

### Description:
From laravel 5.4.29, in the `Illuminate\Database\Eloquent\Model`, added the PHPDoc Param `@mixin \Illuminate\Database\Eloquent\Builder`, and from laravel 5.4.31, in the `Illuminate\Database\Eloquent\Model`, added the PhpDoc Param `@mixin \Illuminate\Database\Query\Builder`, when `barryvdh/laravel-ide-helper` generates, the two @minin in `Illuminate\Database\Eloquent\Model`  is conflicting with the generated `\Eloquent`, so the generated `\Eloquent` cant work well because one method is static and the other is not. so hope delete the two PHPDoc Param. Now when just @mixin \Eloquent, It is work well. 

[Realtion to ide-helper](https://github.com/barryvdh/laravel-ide-helper/issues/541#issuecomment-317411918)

**Comment by themsaid** [comment]
Feel free to open a PR with your change.
