### ISSUE TITLE
Auto Discovery not functional on XAMPP & Disable Auto Discovery

### ISSUE THREAD

**Issue by xJoeyv** [laravel/framework#21151]
- Laravel Version: 5.5.*
- PHP Version: 7.1.6
- Database Driver & Version: 10.1.24-MariaDB

### Description:
Currently I have the newest version of Laravel installed ( 5.5.* ). And recently tried some packages to install. All packages didn't work with auto discover until I figure out it only worked when you visit the website by serving it via artisan.

Now I disabled auto discover via `"dont-discover": ["*"]` and added the service provider to my app.php file and it still doesn't work.

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
