### ISSUE TITLE
Null value in nullable timestamp breaks Eloquent model serialisation

### ISSUE THREAD

**Issue by simonhamp** [laravel/framework#21150]
- Laravel Version: 5.4.36
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.6.35

### Description:
A nullable timestamp column with an actual `NULL` value in it when accessed by an Eloquent model that has `public $timestamps = true;` will throw a `Carbon` `Data misssing` error.

### Steps To Reproduce:
Make a timestamp column (e.g. `updated_at`) `NULL` and serialise (i.e. `toJson()`) the model. Carbon will throw an error.

### Possible Fix
Add an `empty` check in `addDateAttributesToArray`:

```php
// In \Illuminate\Database\Eloquent\Concerns\HasAttributes trait
protected function addDateAttributesToArray(array $attributes)
{
    foreach ($this->getDates() as $key) {
        if (! isset($attributes[$key]) || empty($attributes[$key])) {
            continue;
        }

        $attributes[$key] = $this->serializeDate(
            $this->asDateTime($attributes[$key])
        );
    }

    return $attributes;
}
```

**Comment by themsaid** [comment]
Feel free to open a PR with a test case

**Comment by simonhamp** [comment]
Thanks @themsaid, your confirmation helped identify that it was a different layer of the application munging our data. Nothing wrong with Laravel.
