### ISSUE TITLE
​ Laravel preset 'none' include axios, bootstrap-sass and jQuery

### ISSUE THREAD

**Issue by AndresOchoaS** [laravel/framework#21155]
- Laravel Version: 5.5.*
- PHP Version: v7.*
- Database Driver & Version: N/A

### Description:
Laravel don't remove axios, bootstrap-sass and jQuery dependencies when run `artisan preset none`

### Steps To Reproduce:

1. Create a new laravel project with `composer create-project --prefer-dist laravel/laravel my-project`.
2. Run `artisan preset none`.
3. And check the package.json and boostrap.js files.

**Comment by devcircus** [comment]
Just tried on 5.5.3 and everything worked correctly. 

The bootstrap.js remains unchanged no matter which preset you use. That's why the "require" is within a try/catch.

**Comment by Dylan-DPC** [comment]
Possible dup #20959
