### ISSUE TITLE
Personal Access Tokens do not work with DatabaseTransactions in TestCase

### ISSUE THREAD

**Issue by craigh411** [laravel/framework#21166]
- Laravel Version: 5.4.*
- PHP Version: 5.6
- Database Driver & Version: MySql

### Description:

If you create a personal access token for a user created by a factory in testing, authorization will fail if the `DatabaseTransactions` trait is being used. 

My specific case has this token being used inside a Controller method via Guzzle.

At the moment I'm simply cleaning up the users in my `tearDown()` method, which is fine. My best guess as to what is happening is that the user gets deleted before Guzzle makes the request to the passport protected api route, so this token doesn't exist at this point.

### Steps To Reproduce:

1) add `use DatabaseTransactions;` trait in TestCase

2) Create a new user: 

`$user = factory(User::class)->create();`

3) Create an accessToken for user:

`$token = $user->createToken('test-token')->accessToken;`

4) Send a request to a controller method that uses Guzzle to call a Passport protected API route and you will get an unauthorised response.

**Comment by themsaid** [comment]
That's expected, You'll try using database migrations instead.
