### ISSUE TITLE
Question: Override factory attribute without executing original value

### ISSUE THREAD

**Issue by xxRockOnxx** [laravel/framework#21161]
- Laravel Version: 5.4
- PHP Version: 7.0.22
- Database Driver & Version: Postgresql 9.6.4

### Description:
Original value of a defined factory is being executed

### Steps To Reproduce:
1. define a factory
2. define an attribute that also uses another factory (common in relationships)
3. override it `factory()->create([])`

Question: Is this intended? Is there a way not to execute it?

**Comment by Dylan-DPC** [comment]
Your issue is not clear. Are you reporting a bug or asking for clarification? If you need any clarification then use the forums or the slack channel. If you think it is a bug provide more details with some code, outputs and what you expected

**Comment by themsaid** [comment]
You can use a closure, check the docs for more details

**Comment by xxRockOnxx** [comment]
@Dylan-DPC there's a slack now? lol thought there's an IRC channel only... been a while. Anyway, just clarification.

@themsaid not sure what you mean by closure. I re-checked the docs in case it updated but I did not see anything that can answer my question. Is the states? I checked here: https://laravel.com/docs/5.4/database-testing#using-factories

**Comment by Dylan-DPC** [comment]
Else why would I mention it? You can register yourself at https://larachat.co/ and follow the process from there

**Comment by themsaid** [comment]
Check the title "Relations & Attribute Closures"

**Comment by xxRockOnxx** [comment]
I feel dumb. It's been there since 5.2. Not sure why I was doing it that way ever since. Anyway, thanks for pointing @themsaid

**Comment by themsaid** [comment]
@xxRockOnxx you're welcome :)
