### ISSUE TITLE
[5.5] Add 404 as default code to \Illuminate\Database\Eloquent\ModelNotFoundException

### ISSUE THREAD

**Issue by eusonlito** [laravel/framework#21163]
- Laravel Version: 5.5
- PHP Version: 7.*
- Database Driver & Version:

### Description:

Add **404** as default code to `\Illuminate\Database\Eloquent\ModelNotFoundException`.

`\Illuminate\Database\Eloquent\ModelNotFoundException` extends `\RuntimeException` which extends `\Exception` that has not a default code. Then `\Illuminate\Database\Eloquent\ModelNotFoundException` has not a exception code. **404** should be fine as default code to `\Illuminate\Database\Eloquent\ModelNotFoundException`.

### Steps To Reproduce:

Any `firstOrFail` or `findOrFail` usage.

**Comment by eusonlito** [comment]
Default handler `Illuminate\Foundation\Exceptions\Handler` parse exception to return a `NotFoundHttpException` with code `404` when `ModelNotFoundException` is thrown.
```php
    /**
     * Prepare exception for rendering.
     *
     * @param  \Exception  $e
     * @return \Exception
     */
    protected function prepareException(Exception $e)
    {
        if ($e instanceof ModelNotFoundException) {
            $e = new NotFoundHttpException($e->getMessage(), $e);
        } elseif ($e instanceof AuthorizationException) {
            $e = new AccessDeniedHttpException($e->getMessage());
        } elseif ($e instanceof TokenMismatchException) {
            $e = new HttpException(419, $e->getMessage());
        }
        return $e;
    }
```
But on custom renders, users must set the code to 404 manually.

I think that should be a good idea to set the `ModelNotFoundException` with a default `404` status code.

I know that 404 is a http response code, but almost always will be used as same way on `ModelNotFoundException` thrown.

**Comment by themsaid** [comment]
`NotFoundHttpException` is related to the Http layer, `ModelNotFoundException` is related to the DB layer, it could be used in multiple other areas where a status code doesn't make sense.
