### ISSUE TITLE
Question: why registerBaseServiceProviders in Application?

### ISSUE THREAD

**Issue by alberto-bottarini** [laravel/framework#21164]
Why some service providers are registered using config.app and some others are "forced" into Application.php?

    protected function registerBaseServiceProviders()
    {
        $this->register(new EventServiceProvider($this));

        $this->register(new LogServiceProvider($this));

        $this->register(new RoutingServiceProvider($this));
    }

I needed to change some LogServiceProvider behaviour so I created a CustomLogServiceProvided extends LogServiceProvided and I register it in config.app.
This introduced a little overhead caused by a double registration of app('log'), one done by LogServiceProvider and one by my CustomLogServiceProvider.

A solution was to override Application class, but this would have caused some other issues.

Why could not they have been into config.app ?

**Comment by Dylan-DPC** [comment]
Hi. This issue board is for bug tracking. Kindly use the forums or the slack channel for help. Or create a proposals on the `laravel/internals` repo.

**Comment by crynobone** [comment]
"Event", "Log" and "Route" is essentially the core service providers for Laravel, and is loaded way earlier before anything else, even the configuration files. Now consider if we put this in the config, and for some reason one of millions developer who uses Laravel mess-up the config file, Laravel at this point wouldn't log any of this since it is waiting for LogServiceProvider to be fetched from configuration.

**Comment by themsaid** [comment]
Laravel needs the services registered by these providers early in the bootstrap cycle, and thus why we register it that early in the cycle.

**Comment by alberto-bottarini** [comment]
I don't understand.

Are you telling that Laravel needs this services (event, routing, log) while the others in config.app are not required?

I tried to comment them out, and Laravel breaks down. Logging service is also broken, I have to read errors in apache error-log.

**Comment by themsaid** [comment]
Laravel needs these services **earlier** than the rest.

**Comment by alberto-bottarini** [comment]
Does Laravel need to register routing service earlier? It's a bit strange :)

In your opinion, what's the best way to override one of these providers?

**Comment by alberto-bottarini** [comment]
@crynobone I tried to comment out all the providers in config.app.
Laravel doesn't use custom Log even if it's registered earlier.

**Comment by themsaid** [comment]
Depends on what you want to do, I suggest that you use the forums to post your questions as this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
