### ISSUE TITLE
Laravel CLI installer errors out when installing 5.5 (missing post-install-cmd script)

### ISSUE THREAD

**Issue by jpcaparas** [laravel/framework#21180]
- Laravel Version: 5.5.0
- PHP Version: `7.1`
- Database Driver & Version: `n/a`

### Description:

The latest version of Laravel (`v5.5`) does not have the `post-install-cmd` script, causing issues with the `laravel` CLI installer.

### Steps To Reproduce:

1. Run laravel new <name-of-project>`
2. You should get this error when the project has finished installing:
    
    ```
    [InvalidArgumentException]
    Script "post-install-cmd" is not defined in this package  
    ```

**Comment by far2** [comment]
You have to update the laravel installer first, before running laravel new. See #20934

**Comment by jpcaparas** [comment]
@far2 cool bro thanks!
