### ISSUE TITLE
Queue::fake enabled in service container only after the second call

### ISSUE THREAD

**Issue by challet** [laravel/framework#21189]
- Laravel Version: 5.4.36
- PHP Version: 7.1.4-1
- Database Driver & Version: N/A

### Description:

While unit testing jobs being pushed in queue, it looks like the fake queue handler is not immediatly available from the service container ([here](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Bus/Dispatcher.php#L150) and [here](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Bus/BusServiceProvider.php#L28)) after `Queue::fake()` has been called. 
The job being tested is then actually pushed to the real queue and cannot be asserted.

### Steps To Reproduce:

```php
Queue::fake();
var_dump(get_class(Queue::getFacadeRoot())); 
// |-> string(42) "Illuminate\Support\Testing\Fakes\QueueFake"
var_dump(get_class(app()->make(Illuminate\Contracts\Queue\Factory::class)->connection())); 
// |-> string(26) "Illuminate\Queue\SyncQueue" // not swapped 
Queue::fake();
var_dump(get_class(Queue::getFacadeRoot())); 
// |-> string(42) "Illuminate\Support\Testing\Fakes\QueueFake"
var_dump(get_class(app()->make(Illuminate\Contracts\Queue\Factory::class)->connection())); 
// |-> string(42) "Illuminate\Support\Testing\Fakes\QueueFake" // correctly swapped
```

Strangely, if I try to access it from the service container **before** to fake it, it works : 
```php
app()->make(QueueFactoryContract::class)->connection();
Queue::fake();
var_dump(get_class(Queue::getFacadeRoot()));
// |- string(42) "Illuminate\Support\Testing\Fakes\QueueFake"
var_dump(get_class(app()->make(Illuminate\Contracts\Queue\Factory::class)->connection()));
// |- string(42) "Illuminate\Support\Testing\Fakes\QueueFake"
```

**Comment by themsaid** [comment]
Please share an example test where Queue:fake fails to catch a job? It always worked for me.

**Comment by themsaid** [comment]
Just realised you're on Laravel 5.4, it's not supported anymore. Can you please try to replicate on a 5.5 instance and ping me to re-open the issue?

**Comment by challet** [comment]
ping @themsaid : looks like the same problem still happens on 5.5 (see #21190). 
So far I've tested three ways to push a job, I'm not really aware if other ones might exist.

**Comment by themsaid** [comment]
Can't replicate any of the cases in a fresh laravel installation.
