### ISSUE TITLE
Throttling No Longer Returns 'Retry-After' in response header

### ISSUE THREAD

**Issue by rhyanrandolph** [laravel/framework#21196]
- Laravel Version: 5.5.3
- PHP Version: 7.0
- Database Driver & Version: SQL Server 14

Description: When the throttle limit has been reached Laravel no longer returns a 'Retry-After' header element in the response.

Steps To Reproduce: Set throttling limit to a low value like 'throttle:2,1' within the App\Http\Kernel and make three requests within 60 seconds.

**Comment by themsaid** [comment]
Can't replicate, It's returned:

```
Retry-After →54
X-RateLimit-Limit →4
X-RateLimit-Remaining →0
X-RateLimit-Reset →1505477961
```

**Comment by rhyanrandolph** [comment]
Thanks for looking into this. I made some changes and now it shows.
