### ISSUE TITLE
Issue with laravel 5.3+ DB Grammar when working with Oracle (int -> string in Grammar) 

### ISSUE THREAD

**Issue by ircop** [laravel/framework#21198]
- Laravel Version: 5.3
- PHP Version: 7.1
- Database Driver & Version: Oracle 11.2

### Description:

When joining some oracle table with raw numeric value, Laravel, starting from 5.3, mutates integer value into string. Oracle throws an ORA-00904 (invalid identifier) error.

### Steps To Reproduce:

```php
$query->join('SOMETABLE', function($join){
    $join->on('SOMETABLE.A', '=', 'BASETABLE.B');
    $join->on('SOMETABLE.B', '=', 123456);  # <---- here is the problem
});
```

Error Message : ORA-00904: "50136901": invalid identifier

The problem is in Query\Builder::toSql() -> Database\Grammar::wrap( $value, $prefixAlias = false )

The wrap() result is always string, even if integer given.

The simple way is to patch it with something like " if( is_int($value) ) return $value "

**Comment by decadence** [comment]
5.3 is not supported.

**Comment by ircop** [comment]
Starting from 5.3. 5.5 have same issues as i can see in Grammar wrap() code:

```php
public function wrap($value, $prefixAlias = false) {
      # .....
      return $this->wrapSegments(explode('.', $value));
```

explode returns array of _strings_ :(

**Comment by srmklive** [comment]
Oracle is not officially supported by Laravel. Officially supported drivers are MySQL, PgSQL, SQL Server & Sqlite.

You might be using a package which adds Oracle support for Laravel. Its bettter you post this query there.
