### ISSUE TITLE
Validator considers an empty string unique even when it is a duplicate.

### ISSUE THREAD

**Issue by beyondlimits** [laravel/framework#21200]
- Laravel Version: 5.5.4
- PHP Version: 7.2.0RC1
- Database Driver & Version: SQLite 3.20.1

### Description:
Validator considers an empty string unique even when there's already record with empty string in database.

### Steps To Reproduce:

1. Create a table with unique text column.
2. Add few records with unique values in that column, including empty string.
3. Invoke validator with every string from the database and ```unique``` rule for that column and check whether it passes. It will fail on every string that's already in the table, except the empty string.

```
>>> DB::statement('CREATE TABLE test (id INTEGER, value TEXT NOT NULL, PRIMARY KEY(id), UNIQUE
(value))')
=> true
>>> DB::table('test')->insert(['value' => 'one'])
=> true
>>> DB::table('test')->insert(['value' => 'two'])
=> true
>>> DB::table('test')->insert(['value' => 'three'])
=> true
>>> DB::table('test')->insert(['value' => 'three'])
Illuminate\Database\QueryException with message 'SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: test.value (SQL: insert into "test" ("value") values (three))'
>>> DB::table('test')->insert(['value' => ''])
=> true
>>> DB::table('test')->insert(['value' => ''])
Illuminate\Database\QueryException with message 'SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: test.value (SQL: insert into "test" ("value") values ())'
>>> DB::table('test')->pluck('value')
=> Illuminate\Support\Collection {#730
     all: [
       "one",
       "two",
       "three",
       "",
     ],
   }
>>> validator(['value' => 'one'], ['value' => 'unique:test'])->passes()
=> false
>>> validator(['value' => 'on1'], ['value' => 'unique:test'])->passes()
=> true
>>> validator(['value' => 'two'], ['value' => 'unique:test'])->passes()
=> false
>>> validator(['value' => 'three'], ['value' => 'unique:test'])->passes()
=> false
>>> validator(['value' => ''], ['value' => 'unique:test'])->passes()
=> true
```

**Comment by themsaid** [comment]
Yes empty strings pass all validation rules except rules that imply the field is required, this is intended and it'd be a huge breaking change if we change it.

**Comment by Hell4Ge** [comment]
Using required rule to validate for empty string uniqueness is not a solution, or even workaround, because what if I want to allow for only one occurrence of empty string in table? Like empty Skype number for system superuser?

**Comment by devcircus** [comment]
Sounds like a "required_unless" rule would work great in this scenario.

**Comment by themsaid** [comment]
Laravel considers an empty string as a no value, so validation rules won't run. Your case is a bit weired, why can't multiple rows have an empty column in your database?
