### ISSUE TITLE
Migrate skips one migration

### ISSUE THREAD

**Issue by yooouuri** [laravel/framework#21205]
- Laravel Version: 5.5.4
- PHP Version: 7.1.7-1
- Database Driver & Version: MySQL

### Description:
I have the following migrations:

![image](https://user-images.githubusercontent.com/12934957/30497933-fed3780a-9a54-11e7-908e-c6f2378a6bce.png)

When i run `php artisan migrate`, i get the following error:

```
[Illuminate\Database\QueryException]
  SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL
  : alter table `tasks` add constraint `tasks_user_id_foreign` foreign key (`
  user_id`) references `users` (`id`))

  [PDOException]
  SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint
```

When I check in the database, the migrate skipped the "create_users_table" migration.

![image](https://user-images.githubusercontent.com/12934957/30497937-0aef4c86-9a55-11e7-9a0f-b9f9d69da8b4.png)

The weird thing is, when i remove the last migration (12 migrations instead of 13). The migration succeed...

### Steps To Reproduce:
I my case, have 13 migrations and run the migrate command.

The migrations can be found here: https://github.com/yooouuri/agile-api/tree/master/database/migrations

**Comment by Dylan-DPC** [comment]
I don't think this is a bug. Many people including me have run migrations in the last few days without any trouble. Can you try deleting all your migrations and starting afresh?

**Comment by themsaid** [comment]
The migration before this one errored, so the command exit.
