### ISSUE TITLE
Namespace resolving issue when using database seeder and additional model extending

### ISSUE THREAD

**Issue by Hell4Ge** [laravel/framework#21210]
- Laravel Version: 5.5.4
- PHP Version: 7.1.4
- Database Driver & Version: pgsql

### Description:
While using php artisan db:seed command it is not correctly resolving namespaces

### Steps To Reproduce:

1. create a directory app\Models
2. inside of this directory create some base model, let's just name it "BaseModel" that extends Illuminate\Database\Eloquent\Model
3. create yet another model to seed with data, let's say "Village" that extends app\Models\BaseModel which extends Illuminate\Database\Eloquent\Model
4. Now try to seed this "Village" model by using seeder class, and the error
_[Symfony\Component\Debug\Exception\FatalErrorException]
Class 'app\Models\BaseModel' not found_
pops out 

If I remove the BaseModel from these steps so the Village model would extend Illuminate\Database\Eloquent\Model directly then the error won't show, but it's still not a solution

Also composer dump-auto did not solve the problem

**Comment by Dylan-DPC** [comment]
This is not a bug. Check your namespace of the model. It should be `App\...` not `app\...`
