### ISSUE TITLE
Going to a route that isn't defined is throwing a session error when using the "old" method.

### ISSUE THREAD

**Issue by jaesung2061** [laravel/framework#21215]
- Laravel Version: 5.5.3
- PHP Version: 7.1.4-1+deb.sury.org~xenial+1
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.7.19, for Linux (x86_64) using  EditLine wrapper

### Description:
After upgrading from 5.4 to 5.5, going to a route that isn't defined is throwing a `Session store not set on request.` exception. I've traced it back to a form that's on every page that is using the following call:

    old('email')

### Steps To Reproduce:

1. Use `old` method anywhere in the master blade layout.
2. Go to route that isn't defined such as `localhost:8000/route-that-does-not-exist`.

**Comment by devcircus** [comment]
How are you handling page-not-found exceptions? Are you displaying an error page that extends master? If so, the session isn't loaded in those situations and the error makes sense.

**Comment by jaesung2061** [comment]
Yes, my error page is extending from master. Why would this be expected behavior? The session shouldn't disappear if the user goes to the wrong page.

**Comment by devcircus** [comment]
The session is loaded at the completion of the request. An exception short circuits the request and session isn't loaded. Search through the issues on the repo. Seems like there were solutions discussed for this exact situation, a few weeks ago.

**Comment by jaesung2061** [comment]
Actually it looks like it's not sessions in general. Just the `old` method. Calling something like `session('key')` and going to a page that isn't defined doesn't trigger this exception. So it's the `old` method specifically.

**Comment by GrahamCampbell** [comment]
This is the correct behaviour. If you only load sessions on routes that are defined, then you can't use them on route misses.

**Comment by GrahamCampbell** [comment]
If you want sessions on everything, move the middleware to the global middleware.
