### ISSUE TITLE
Route singularization problem (graves)

### ISSUE THREAD

**Issue by naurojunior** [laravel/framework#21212]
- Laravel Version: 5.5
- PHP Version: 7.0.22

### Description:
When I create the route "graves", Laravel singularize the parameter to "grafe"

### Steps To Reproduce:
Create a route
Route::resource('graves', 'GraveController');

php artisan route:list

POST          | graves
GET|HEAD  | graves
DELETE       | graves/{grafe}
PUT|PATCH | graves/{grafe}
 GET|HEAD  | graves/{grafe}

**Comment by Dylan-DPC** [comment]
I don't think this is something that can be solved since 2 words (grafe & grave) have the same plural.

**Comment by naurojunior** [comment]
Hi, does "grafe" really exists? What is the meaning? I'm not a native speaker, but I couldn't find this word anywhere.

**Comment by Dylan-DPC** [comment]
Ah my bad it is not. There is "graff" but no "grafe"

**Comment by naurojunior** [comment]
I'm adding a Pull Request to correct Doctrine's inflector :) 

https://github.com/doctrine/inflector/pull/58
