### ISSUE TITLE
Problems using Mailer from /sender address

### ISSUE THREAD

**Issue by nivanmorgan** [laravel/framework#21216]
- Laravel Version: 5.4
- PHP Version: 7.0
- Database Driver & Version: MySQL 5.7

### Description:

I have Mailer functionality built into my business app. I'm using smtp to send out client emails. The emails should be send from the client email address but instead are sent from the system. In other words the sender appears as the system email no matter what I try. I do not have a default from address in my mail config file nor in my .env file.  I'm sure the email is sent to the Mailer since these are the errors I get:

If I use $sender as a dependency as shown in the code, it sends but from the system email. When I send an email it sends from support@system.com not the user email 

If I use $from as a dependency to inject to the email I get an even worse error.

![3](https://user-images.githubusercontent.com/8334562/30518129-cf542c2a-9b42-11e7-98e3-5e837b5abfc1.PNG)

Below is another error I get when I tried to debug the Mailer class in the framework. In the image the sender email is correctly passed to the Mailer send method. 

![sender](https://user-images.githubusercontent.com/8334562/30518194-702c0716-9b44-11e7-8cb8-3cd3e9c0e511.PNG)

According to the documentation this is a lot easier than what I'm experiencing.

### Steps To Reproduce:

Here is my Mailable class

class UserEmail extends Mailable
{
    use Queueable, SerializesModels;

    public $sender,$name, $subject, $content, $attach;

    /**
     * Create a new message instance.
     *
     * @return void
     */
    public function __construct($sender, $name, $subject, $content, $attach)
    {
        //
        $this->sender = $sender;
        $this->name = $name;
        $this->subject = $subject;
        $this->content = $content;
        $this->attach = $attach;
    }

    /**
     * Build the message.
     *
     * @return $this
     */
    public function build()
    {
 
                    return  $this->from($this->sender, $this->name)
                              ->view('mailbox.sendmail')
                              ->subject($this->subject)
                              ->with(['t_body' => $this->content, 'title' => $this->subject])
                              ->withSwiftMessage(function ($message) {
                                  $message->getHeaders();
                              });

                          for ($i = 0; $i < count($this->attach); $i++) {
                              $this->attach($this->attach[$i]);
                          }
          }

    }

And in my Emailcontroller I'm sending the variables

      $sender = (isset($configuration['serveruser']) && $configuration['serveruser'] != '') ? 
      $configuration['serveruser'] : Auth::user()->email ;
                    $name = Auth::user()->name;
                    $subject = $request->subject;
                    $content = $request->input( 'content' );
                    $attach = $files;

       Mail::to($request->to)->send((new UserEmail($sender, $name,$subject, $content, $attach))->onQueue('emails'));

mail.php
     
      //    'from' => [
     //        'address' => '',
    //        'name' => '',
    //    ],

Our system is live and I can't fix this and users will not want to send emails. Is it a bug? according to the documentation, if I set $this->from(address, name) , it sends from that email address.

**Comment by Dylan-DPC** [comment]
Can you try setting the config directly instead of an array through the ternary?

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.

**Comment by designloud** [comment]
I just noticed I am also having this issue after updating to Laravel 5.4 which from what I understand uses SwiftMailer but it is completely ignoring the From field and instead of sending emails directly from the app email. Should I still go to the forums or is this indeed a bug?

**Comment by themsaid** [comment]
From field on 5.5 seems to be working fine for me.

**Comment by nivanmorgan** [comment]
@themsaid you said that with laravel 5.3 and I updated to 5.4. Notifications delay isn't working either and it again said to work in the documentation. what kind of bugs or problems do you actually solve here? My app is live and this is a real issue and you have closed it twice without helping .. the last time you said 5.3 was not supported and I guess this time 5.4 isn't @taylorotwell please help with these 2 issues if possible.

**Comment by themsaid** [comment]
@nivanmorgan thing is I really can't replicate any of these issues on 5.4 or 5.5

Delay is working fine for me as well as the sender field in Mailers, I pointed you towards the forums because it's a more active QA community where you can share your issue and people will try to help, including myself. 

We only keep bug reports here so we can work on it and fix, but if we can't replicate the issue then it's probably a mis-configuration from your side, so the forums is a better place for this.

I hope you get me point.

**Comment by nivanmorgan** [comment]
@themsaid you were right. I upgraded to 5.5 and it still didn't send from the sender  address so I changed to mailgun and it worked  fine. notify I'm not sure of though. I had use jobs to delay it. Thx

**Comment by maher70** [comment]
i'm facing same issue with laravel 5.7.. can some help me why from field in not working and sending default email instead of client email

**Comment by devender0709** [comment]
I am also having same issue in laravel 5.7 .  from address is not updating . i tried as  ->from('example@aa.com') but no luck.  Please help. Thanks..
