### ISSUE TITLE
Calling Dusk inside another command with the filter option

### ISSUE THREAD

**Issue by tutelagesystems** [laravel/framework#21223]
- Laravel Version: 5.5.4
- PHP Version: 7.1.5
- Database Driver & Version: N/A

### Description:
When attempting to call Dusk from inside another command, it will ignore the filter argument. This can make it irrelevant to be able to call dusk from another command (if wanting to use the filter option).

### Steps To Reproduce:
1. Install Laravel
2. Install Dusk
3. Create a new Test
4. Verify that you can run that test by `php artisan dusk --filter=NameOfClass`
5. Create new command
6. Register that command in the `Kernel.php`
6. In the `handle` function add the following

```php
$this->call('dusk', [
  '--filter' => 'NameOfClass',
]);
```
---
I did a die and dump in the dusk command and it returns different results based on if you call it through another command or not. I did the die and dump on [line 58](https://github.com/laravel/dusk/blob/2.0/src/Console/DuskCommand.php#L57), right after the options are set

```php
$options = array_slice($_SERVER['argv'], 2);
dd($_SERVER['argv'], $options);
```

#### Output from Dusk with filter option
`php artisan dusk --filter=BasicTest`

```
array:3 [
  0 => "artisan"
  1 => "dusk"
  2 => "--filter=BasicTest"
]
array:1 [
  0 => "--filter=BasicTest"
]
```

#### Output from Dusk called within a command with the filter option
`php artisan dusk:call`

```
λ php artisan dusk:interactive
array:2 [                     
  0 => "artisan"              
  1 => "dusk:call"     
]                             
[]                            
```

**Comment by Dylan-DPC** [comment]
Kindly create your issue here: https://github.com/laravel/dusk/issues
