### ISSUE TITLE
Call to a member function delay() on integer

### ISSUE THREAD

**Issue by sunnoy** [laravel/framework#21228]
- Laravel Version: 5.5.3
- PHP Version:7.0
- Database Driver & Version:
mysql
### Description:
when i use the 
$this->dispatch(new DoHeavyStuff($file))
            ->delay(Carbon::now()->addMinutes(10));

### Steps To Reproduce:
it give me 
Call to a member function delay() on integer

**Comment by sisve** [comment]
Your code is equal to ...

    $dispatchResult = $this->dispatch(new DoHeavyStuff($file));
    $dispatchResult->delay(Carbon::now()->addMinutes(10));

Combine that with the knowledge that `$this->dispatch(...)` in many cases returns the identifier of the job inserted into the queue, and you get the cause of the error, you're calling `->delay(...)` on an integer.

A total guess here; but you've misplaced some parentheses.

**Comment by sunnoy** [comment]
it works , mybe i need to learn much more about laravel .
