### ISSUE TITLE
vendor:publish lack of error message

### ISSUE THREAD

**Issue by salarmehr** [laravel/framework#21222]
- Laravel Version: 5.5.3
- PHP Version: 7.1
- Database Driver & Version:

### Description:
`php artisan vendor:publish  --provider=\foo\bar`

Does not return any error message if the provider name is incorrect.

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. This isn't a bug so you can open a proposal in the laravel/internals repo

**Comment by GrahamCampbell** [comment]
Yeh, the behaviour here is that is successfully published no resources.
