### ISSUE TITLE
Question : PSR-11 and get / has

### ISSUE THREAD

**Issue by harikt** [laravel/framework#21220]
- Laravel Version: 5.5
- PHP Version:
- Database Driver & Version:

### Description:

According to PSR-11 https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-11-container.md#31-psrcontainercontainerinterface 

> Finds an entry of the container by its identifier and returns it.

Now if you have not registered anything the container always throws `Illuminate\Container\EntryNotFoundException` .

But Illuminate Container can create instances via make method. This is my take, if there is a concrete class, container should be able to create the object. Else throw the exception. The `has` method need to be modified for the same.

I am looking at an implementation 
https://github.com/dms-org/web.laravel/blob/582d970393656a011ffcee4f6716ae79c5e57813/src/Ioc/LaravelIocContainer.php#L157 of psr-11 before 5.5 .

### Steps To Reproduce:

```php
<?php
require __DIR__ . '/vendor/autoload.php';

class Foo
{
    public function __construct()
    {
        echo "Constructed \n";
    }
}

$container = new \Illuminate\Container\Container();
$container->make(Foo::class);
$container->get(Foo::class);
```

**Comment by devcircus** [comment]
Seems like according to

> Finds an entry of the container by its identifier and returns it.

it is pretty explicit that it "finds an entry" of the container by its  "identifier". So just allowing Laravel's container to return a concrete, doesn't really fit. However I can see why this may be convenient.

**Comment by harikt** [comment]
@devcircus did you checked how the dms container is working ?

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.

**Comment by hakuno** [comment]
> $container->get(Foo::class);

The Laravel's PSR-11 implementation is buggy. Because `get` doesn't work like `make`.

**Comment by golaod** [comment]
> > $container->get(Foo::class);
> 
> The Laravel's PSR-11 implementation is buggy. Because `get` doesn't work like `make`.

I agree with you. If PSR-11 was added to let laravel devs replace that container with PSR-11 interface, then the entire logic which works in laravel's container should work the same under PSR-11 interface.

**Comment by driesvints** [comment]
@golaod Laravel's container already makes use of PSR-11. `get` wasn't suppose to behave the same as `make`.
