### ISSUE TITLE
Save Json objects inside mysql column database don't work

### ISSUE THREAD

**Issue by thamerbelfkihthamer** [laravel/framework#21238]
- Laravel Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Steps To Reproduce:

Actually i work to save json objects inside column that has a json as type,

when i reveice  a $request i do json_encode to all the $request object , the problem is , when i try to persist the objet , that's not work because the json_encode generate double cout "" in the begin and in the last of the new object like this 

`"{"1505779480":{"numero":"8445546451","lastname":"belfkih","firstname":"thamer","profession":"psychnoterapeute"}}"`

mysql don't accept this objet because  of the double cout as you see in this line, i don't have any solution to fix that.

any one here can help me !

@themsaid @taylorotwell 

i think we need to fix this inside the MysqlGrammer class !!

ps : i work with 5.4 version

**Comment by sisve** [comment]
1. Update your issue and add the exact Laravel version, php version and database version. 
2. Consider upgrading to 5.5 since 5.4 is no longer supported.
3. Are you asking for help? Have you tried the forums/Slack instead?

**Comment by themsaid** [comment]
Please resubmit a valid issue report.
