### ISSUE TITLE
Feature Request: config files that are environment aware.

### ISSUE THREAD

**Issue by chriscalip** [laravel/framework#21237]
- Laravel Version: 5.5
- PHP Version: 7.1
- Database Driver & Version: ANY

### Description:
The idea is to have locally aware configuration files.

/config/app.php
/config/app.local.php

**Comment by sisve** [comment]
Feature requests goes into https://github.com/laravel/internals. Move it there, and add clarification why the existing support for `.env.local` won't work for you.

**Comment by chriscalip** [comment]
Closing ticket, because .env.local works.

**Comment by decadence** [comment]
@chriscalip @sisve 
How does `.env.local` works? If I have this file it doesn't affect anything.

**Comment by sisve** [comment]
It's like `.env` with the same caveats. The most common issue is that you're running with a cached configuration; that means that the .env files will not be loaded.

**Comment by decadence** [comment]
I'm aware of config caching and I don't use it.
What mechanism of using `.env.local`. It must be included if exists and I have `APP_ENV="local"`?

**Comment by sisve** [comment]
You must have `APP_ENV=local` in your .env file or executing an artisan command with `--env=local`.

If that didn't answer your question; try rephrasing it.

**Comment by decadence** [comment]
I have `.env` with `APP_NAME="Laravel Env"` and `.env.local` with APP_NAME="Laravel Local".
Both contains `APP_ENV=local` and `config("app.name")` always returns `Laravel Env`.

Should it work on Laravel 5.5.4?

**Comment by sisve** [comment]
Here's the source. Read it. Move this support inquiry into the forums or Slack.

Source: https://github.com/laravel/framework/blob/5.5/src/Illuminate/Foundation/Bootstrap/LoadEnvironmentVariables.php
Slack: https://larachat.co/

**Comment by decadence** [comment]
@sisve Thanks for the link, now I get it. I must set `APP_ENV` on server level and not it `.env` file. Then Laravel doesn't return on this line https://github.com/laravel/framework/blob/5.5/src/Illuminate/Foundation/Bootstrap/LoadEnvironmentVariables.php#L47
