### ISSUE TITLE
potential BC on version switch from v5.4.33 to v5.4.34

### ISSUE THREAD

**Issue by null9beta** [laravel/framework#21232]
- Laravel Version: 5.4.34
- PHP Version: 7.0.19
- Database Driver & Version: -

### Description:

this is the comparison from 5.4.33 to 5.4.34
https://github.com/laravel/framework/compare/v5.4.33...v5.4.34

and in particular its about this commit
https://github.com/laravel/framework/commit/8061d9b441933c547981351879bc531379c649d0

The commit added a new verb to the any method. `vendor/laravel/framework/src/Illuminate/Routing/Router.php:204`

actually it changed from 
```
$verbs = ['GET', 'HEAD', 'POST', 'PUT', 'PATCH', 'DELETE'];
```
to
```
public static $verbs = ['GET', 'HEAD', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'];
```

Although this change seems logic in the first place it introduces a side effect which i will demonstrate and i believe due to the effect this change might be considered a breaking change.

The result of adding `OPTIONS` as well to the any method results in new Routes being added with the verb OPTIONS as well. 

Inside `vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php::match` the routes for the given request method are retrieved.

And this is where the change starts.

**Behavior in v5.4.33**
 - no routes will be found in [line 159](https://github.com/laravel/framework/blob/v5.4.33/src/Illuminate/Routing/RouteCollection.php#L159)
 - we will skip the condition in [line 166](https://github.com/laravel/framework/blob/v5.4.33/src/Illuminate/Routing/RouteCollection.php#L166)
 - checkForAlternativeVerbs will return an alternative Route (our api/user route with the post method) [lin 173](https://github.com/laravel/framework/blob/v5.4.33/src/Illuminate/Routing/RouteCollection.php#L173)
- RouteCollection.php::getRouteForMethods will recognize the OPTIONS request and return the proper response (status=200 with empty body) [line 176](https://github.com/laravel/framework/blob/v5.4.33/src/Illuminate/Routing/RouteCollection.php#L176)

**Behavior in v5.4.34**
 - because any also adds an option route for the catchall, [line 159](https://github.com/laravel/framework/blob/v5.4.36/src/Illuminate/Routing/RouteCollection.php#L159) will in fact return that route
 - the condition in [line 166](https://github.com/laravel/framework/blob/v5.4.36/src/Illuminate/Routing/RouteCollection.php#L166) is fulfilled
 - the any('{catchall}' route will be returned (status=404 with empty body) [line 167](https://github.com/laravel/framework/blob/v5.4.36/src/Illuminate/Routing/RouteCollection.php#L167)

That means the OPTIONS (pre-flight request in the browser will fail).
So without changing actual code or setup the behavior changes.

### Steps To Reproduce:

This is my sample `routes/api.php` content 
```
Route::post('/user', function (Request $request) {
    return [
        'uuid' => '840e3056-ca69-42f8-9590-4a87b6a3dd65',
        'email' => 'some@email'
    ];
});

Route::any('{catchall}', function (Request $request) {
    return response(null, Response::HTTP_NOT_FOUND);
})->where('catchall', '(.*)');
```

There is just 2 routes, one that creates something (i know does not really do it :) , but we need to add the route for an option request test later)

Here is the PHPUnit results with just 2 tests set up. The first test calls the post endpoint and checks for the result. The 2nd test calls the pre-flight request (the OPTIONS request) which a browser would typical do.

**With laravel/framework v5.4.33**
```
# phpunit
PHPUnit 4.6.6 by Sebastian Bergmann and contributors.

Configuration read from /Users/.../laravel-bc-v5.4.33/phpunit.xml

..

Time: 309 ms, Memory: 16.00Mb
OK (2 tests, 3 assertions)
```

**With laravel/framework v5.4.34**
```
# phpunit
PHPUnit 4.6.6 by Sebastian Bergmann and contributors.

Configuration read from /Users/../laravel-bc-v5.4.36/phpunit.xml

.F

Time: 192 ms, Memory: 16.00Mb

There was 1 failure:

1) Tests\Feature\ExampleTest::testRunOptionsBeforeCreateTest
Expected status code 200 but received 404.
Failed asserting that false is true.

/Users/.../laravel-bc-v5.4.36/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestResponse.php:78
/Users/.../laravel-bc-v5.4.36/tests/Feature/ExampleTest.php:39

FAILURES!
Tests: 2, Assertions: 2, Failures: 1.
```

i created 2 repos with the exact same code, only the laravel/framework version inside the compser.json is different.

the repos where create using the composer create command (i adjusted the laravel/framework version manually to v5.4.33 and v5.4.34 each)
`composer create-project --prefer-source laravel/laravel laravel-bc-5.4.33 "5.4.*"`
`composer create-project --prefer-source laravel/laravel laravel-bc-5.4.34 "5.4.*"`

https://github.com/null9beta/laravel-bc-v5.4.33
https://github.com/null9beta/laravel-bc-v5.4.34

Best 
null9beta

**Comment by devcircus** [comment]
This definitely didn't seem like a good idea at the time, but probably a little late now to address it

**Comment by null9beta** [comment]
@devcircus 

If you mean that there is already version 5.5, please keep in mind that we use laravel for our production app and simply changing a version is not as easy in a production application lifecycle. So Laravel 5.4 is what we are using at the moment and the changes introduces where just recently introduced. At least the tag was created 26 days ago.

So i am a little unsure what you mean with 
>>"but probably a little late now to address it"

Is there anything i can help with?

**Comment by srmklive** [comment]
5.4 is not officially supported. Although if such issue is occurring it should have been reported before v5.5 was tagged.

Are you able to replicate the same in a fresh 5.5 application?

**Comment by sisve** [comment]
@null9beta 

Laravel 5.4 had active support for 6 months after the 5.4.0 release, and that time elapsed July 24th. Bugs _may_ still be fixed, but there's no active support window for that. (The window for security-related issues is open until January 24th 2018).

And yes, a little bit of calendar math shows that there was about a month where no version of Laravel was officially supported.

> For general releases, bug fixes are provided for 6 months and security fixes are provided for 1 year.

Source: https://laravel.com/docs/5.5/releases

> 5.4 is not maintained anymore, please upgrade to 5.5

Source: https://github.com/laravel/framework/issues/21170#issuecomment-329221686

I expect that this post only raised more questions.

**Comment by null9beta** [comment]
@sisve alright, i fully understand the maintenance releases. Besides that i actually just wanted to still report it as it might cost people a few hours finding out what happend, i will close this one then

@srmklive 
>>Are you able to replicate the same in a fresh 5.5 application?

Actually the behavior in 5.5 is the same as described above in v5.4.34
If you define just one any-route as a catchall the behavior for OPTIONS Requests changes.

If no any-route is defined the RouteCollection.php:: match will properly return a 200 status code due to the following code.
- RouteCollection.php::match will call RouteCollection.php::getRouteForMethods [line 176](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Routing/RouteCollection.php#L176) and RouteCollection.php::getRouteForMethods will recognize the OPTIONS request and return the 
proper response (status=200 with empty body) in [line 233](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Routing/RouteCollection.php#L233)

If an any-route is defined as the last resort the behavior changes into returning the dispatched any-route instead of catching the OPTIONS request and returning 200 with empty body.

I am not sure what the desired behavior shall be.

Do you want me to open a new issue about that behavior?

It would be really interesting what the suggested setup would be. It seems like intercepting the OPTIONS Request in RouteCollection.php::getRouteForMethods [line 233](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Routing/RouteCollection.php#L233) also is a bit hidden and implicit whereas i guess it can be a little more explicit and maybe even handling the OPTIONS Request could be managed separately in a more s.o.l.i.d. way.

Thanks for your feedback

**Comment by themsaid** [comment]
Please open a new issue if you want to report something on 5.5 since the title of this issue is a bit irrelevant now.

Thanks :)
