### ISSUE TITLE
[5.5] Pipeline: Function name should be a string (AuthManager)

### ISSUE THREAD

**Issue by saiik** [laravel/framework#21249]
- Laravel Version: 5.5.4
- PHP Version: 7.1.1
- Database Driver & Version: MySQL

### Description:

Currently trying to upgrade from Laravel 5.4 to 5.5. We are using the [Cloudcreativity Laravel JSON](https://github.com/cloudcreativity/laravel-json-api) package to run a json api with laravel. Also we have our own auth provider to validate JWT tokens. 

As soon as we upgrade we get the error "Function name should be a string". After searching through the code and vendor dir, i've a found a solution:

Adding following code to the Laravel AuthManager solved the problem:

```php
public function handle($request, Closure $next) {
     return $next($request);
}
```

The question is: What tries to call AuthManager::handle? I've found nothing.

**Comment by sisve** [comment]
This sounds like you're attempting to use the middleware alias "auth", but havn't registered it or it just resolves to the Auth facade, which is backed by AuthManager.

**Comment by saiik** [comment]
Thanks, this actually solved it. The auth middleware wasn't registered properly.

**Comment by thijsw** [comment]
Thank you for writing this issue @saiik , it prevented me from another hour of debugging ;)

**Comment by razigohar** [comment]
How to register auth Middleware properly?

**Comment by abreksa4** [comment]
> How to register auth Middleware properly?

@razigohar If you're using Lumen, you'll need to uncomment the `auth` middleware being registered at https://github.com/laravel/lumen/blob/master/bootstrap/app.php#L66
