### ISSUE TITLE
FilesystemAdapter exception message not expressive

### ISSUE THREAD

**Issue by tflori** [laravel/framework#21244]
- Laravel Version: 5.4.x
- PHP Version: 7.1
- Database Driver & Version: -

### Description:
Exceptions require a message and a path is not a message - it's a path. Any system that only shows the exception message without the exception class will confuse the people. I had to run debugging to find that the `path/to/unknown/file` is a exception message for a `ContractFileNotFoundException`.

https://github.com/laravel/framework/blob/5.5/src/Illuminate/Filesystem/FilesystemAdapter.php#L107

Proposal: `sprintf('%s not found', $path)`

### Steps To Reproduce:
```php
Storage::disk('any')->get('unknown/path');
```

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. This isn't a bug so you can open a proposal in the laravel/internals repo
