### ISSUE TITLE
[5.5] Unauthenticated redirect route is hard to customise

### ISSUE THREAD

**Issue by ockle** [laravel/framework#21246]
In 5.5, the `unauthenticated` method of the exception handler has been moved into the Foundation, however, this makes the [hard-coded redirect route](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Foundation/Exceptions/Handler.php#L220) annoying to set on a per-app basis. A user now has to override the method in the app's exception handler, copying the whole method body just to change one thing. This is obviously not very user-friendly. I would think a separate method on the handler that returns the location to redirect to would be the best solution, as this is easier for a user to include in their app's handler.

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. This isn't a bug so you can open a proposal in the laravel/internals repo
