### ISSUE TITLE
Incorrect work pagination  Eloquent

### ISSUE THREAD

**Issue by lxShaDoWxl** [laravel/framework#21242]
- Laravel Version: 5.4
- PHP Version: 7.0
- Database Driver & Version: MySQL (MariaDB 10.1)

### Description:
Incorrect work pagination Eloquent from join

### Steps To Reproduce:
Else run code
```
Eloquent::query()->distinct()
            ->select('table_one.*')
            ->join('table_two', 'table_two.owner_id', '=', 'table_one.id', 'LEFT OUTER')
->paginate(20,['table_one.id'])
```
then two queries will execute
```
select count(*) as aggregate from `table_one` LEFT OUTER join `table_two` on `table_two`.`owner_id` = `table_two`.`id`
```
and
```
select distinct `table_one`.* from `table_one` LEFT OUTER join `table_two` on `table_two`.`owner_id` = `table_two`.`id`
```
as the first request is incorrect, it should be of the form
```
select count(distinct table_one.id) as aggregate from `table_one` LEFT OUTER join `table_two` on `table_two`.`owner_id` = `table_two`.`id`
```

**Comment by Dylan-DPC** [comment]
Why would it be a count?

**Comment by sisve** [comment]
A count query is required to calculate the total number of rows. The second query fetches the actual  data for the page. The second query looks like it is missing a LIMIT clause in this issue, but I think that is a authoring issue and not related to the reported issue.

The issue seems to be the logic that rewrites the query `SELECT DISTINCT *` into a `SELECT COUNT(*)` instead of understanding that it needs to keep the DISTINCT part.

Related: [Builder::runPaginationCountQuery](https://github.com/laravel/framework/blob/997e67cc2001006a43b73eaedf17fa1a2555fd66/src/Illuminate/Database/Query/Builder.php#L1785-L1791)

**Comment by lxShaDoWxl** [comment]
@Dylan-DPC if there are 2 lines in the second table, the first request for count will return 2, but the second query will return 1 model.
compare the two functions and understand that there is a mistake
Query Builder
https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Query/Builder.php#L1718
Eloquent Query Builder
https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Builder.php#L683

**Comment by Dylan-DPC** [comment]
I don't see this as a bug actually. It can be enhanced/improved though. Feel free to send in a PR or make a proposal on laravel/internals.

**Comment by sisve** [comment]
Well, it returns wrong values. Can we update the docs and state that paginate() does not support joins?

**Comment by Dylan-DPC** [comment]
yeah that's better @sisve

**Comment by rs-sliske** [comment]
it is distinct that breaks this

it looks like the regular query builder paginate method allows for passing fields to count on, but the eloquent builder always does count(*)

it looks like a fairly simple fix to mirror the behaviour of query builder (not completely sure why it isnt just delegating to that anyway tbh), but guessing changing behaviour of eloquent methods is breaking change, even if it is actually fixing a bug

@Dylan-DPC not really sure how this isnt a bug. paginator is getting the wrong value for total count, which then causes it to generate links for more pages than there are results for

**Comment by Dylan-DPC** [comment]
Paginator isn't expected to work with joins/distincts, etc. May be it isn't documented enough.

**Comment by driesvints** [comment]
A PR that would fix this was merged into the master branch. This will be released in the next version of Laravel.
