### ISSUE TITLE
[5.5.5] Collection sortBy second argument $options only works with SORT_REGULAR 

### ISSUE THREAD

**Issue by ozldmezot** [laravel/framework#21253]
Laravel 5.5.5
PHP 7.0
Commit (c10800624353c619aea07b3b01ae16cca91800b8) breaks sortby second argument $options, since the $results is an array of arrays

Steps to Replicate;
```
$collection->sortBy('title', SORT_STRING|SORT_FLAG_CASE)
```

**Comment by ionesculiviucristian** [comment]
Can confirm this.

**Comment by themsaid** [comment]
reverted in https://github.com/laravel/framework/pull/21255
