### ISSUE TITLE
[5.5.6 - 5.5.7] One of the last new releases broke my tests

### ISSUE THREAD

**Issue by santigarcor** [laravel/framework#21257]
- Laravel Version: 5.5.6 - 5.5.7
- PHP Version: 7.1

### Description:
After updating from 5.5.5 to 5.5.7 some of my tests are now failing. I tried to figure out what is the problem from my side, but I didn't touch any code related to the tests that are failing now.

The strange thing is that the stack trace of the error shows a middleware that I don't use for the action I'm testing. If I revert back to 5.5.5 everything works fine.

My test look something like this:

```php
$this->signIn($this->user)->getJson(route('users.data'))
    ->assertJsonFragment(['name' => $this->user->name]);
```

This is the: 

```
Illuminate\Database\Eloquent\ModelNotFoundException: No query results for model [App\Models\User] data

/home/santiago/htdocs/dataprotection/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:329
/home/santiago/htdocs/dataprotection/app/Http/Middleware/Owns.php:31 <- This is the middleware i don't use for this action
...
```

And these are my routes:

```php
Route::get('users/data', 'UsersDataController@index')->name('users.data');
Route::resource('users', 'UsersController');
```

### Steps To Reproduce:
I really don't know how to reproduce this issue, i think it's like it's doing some kind of redirection o something like that because it's showing a middleware that i don't use for that route.

**Comment by themsaid** [comment]
Rollback to 5.5.6 and try, you need to identify which release exactly broke your tests.

**Comment by santigarcor** [comment]
I can't install 5.5.6 i get this error:
```
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

                                                                               
  [Symfony\Component\Debug\Exception\FatalThrowableError]                      
  Type error: Too few arguments to function Illuminate\Cache\Console\ClearCom  
  mand::__construct(), 1 passed in /home/santiago/htdocs/dataprotection/vendo  
  r/laravel/framework/src/Illuminate/Foundation/Providers/ArtisanServiceProvi  
  der.php on line 217 and exactly 2 expected                                   
                                                                               

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

```

**Comment by Hell4Ge** [comment]
I will just add that I also can't update from 5.5.4 to 5.5.5 or 5.5.6 because of package discover

    "require": {
        "php": ">=7.0.0",
        "barryvdh/laravel-debugbar": "^3.0",
        "fideloper/proxy": "~3.3",
        "guzzlehttp/guzzle": "^6.3",
        "laravel/framework": "5.5.4",
        "laravel/tinker": "~1.0",
        "paquettg/php-html-parser": "^1.7"
    },

**Comment by themsaid** [comment]
@Hell4Ge what's with package discovery?

**Comment by Hell4Ge** [comment]
@themsaid I wrote this based on error

I think that there is something wrong with composer.json file and package discovery

**Comment by santigarcor** [comment]
@themsaid i think #21258 is related to this issue.

**Comment by damiani** [comment]
I suspect https://github.com/laravel/framework/pull/21261 fixes this issue.

**Comment by themsaid** [comment]
https://github.com/laravel/framework/pull/21261
