### ISSUE TITLE
Artisan commands output an "f" string

### ISSUE THREAD

**Issue by rogervila** [laravel/framework#21252]
- Laravel Version: 5.5.5
- PHP Version: 7.1.9
- Database Driver & Version: Mysql 5.7.19
- OS: Windows

### Description:
When I run a non-custom artisan command (like cahce:clear, view:clear, etc) an "f" string is shown on the console.

![capture](https://user-images.githubusercontent.com/6053012/30595334-3117e216-9d51-11e7-8b36-3d9fd4551758.PNG)

### Steps To Reproduce:
- Install Laravel 5.5 on Windows
- Run any artisan command

**Comment by themsaid** [comment]
<img width="258" alt="screen shot 2017-09-19 at 3 52 27 pm" src="https://user-images.githubusercontent.com/4332182/30595562-d2e86bf6-9d51-11e7-9c46-d2152f8a4a9b.png">

Can't replicate

**Comment by rogervila** [comment]
@themsaid which Windows version are you using? We are working on Windows 10.

**Comment by themsaid** [comment]
@rogervila I'm not on windows, just install a fresh laravel App and test with it, most probably you left an f character somewhere in your project.

**Comment by ludo237** [comment]
Can't replicate that either

```
Windows 10 Pro 
Version 1703
Build 15063.608
````

**Comment by jordyvandomselaar** [comment]
How does that even happen?

**Comment by devcircus** [comment]
Usually there is some text before the opening ```<?php``` in one of your application files.

**Comment by ConnorVG** [comment]
This will be in a non-class file (such as a routes file, likely in `routes/console.php`).
