### ISSUE TITLE
Route::resource create method broken [5.5.4 - 5.5.7]

### ISSUE THREAD

**Issue by Hell4Ge** [laravel/framework#21258]
- Laravel Version: 5.5.7
- PHP Version: 7.1
- Database Driver & Version: pgsql

### Description:
Just updated form 5.5.4 to 5.5.7 and my resource controller which was working fine started to access the show() method instead of create() method

Rolling back to 5.5.4 solves the route problem.

### Steps To Reproduce:
Create a 5.5.4 project and update it with composer to 5.5.7

**Comment by edbizarro** [comment]
+1, have the same problem with Route::get(), Route::post() etc.

**Comment by gtapps** [comment]
I also updated from 5.5.4 to 5.5.7 and I'm getting Class redirector does not exist. I have multiple broken URLS,, after rolling back everything works fine.

**Comment by benabbottnz** [comment]
An easy enough "solution" is just to put the create route before the resource route:

`Route::get('users/{user}/posts/create', 'UserPostController@create');`
`Route::resource('users.posts', 'UserPostController');`

Saves you having to miss out on future updates until this is fixed I suppose...

**Comment by amdadulhaq11** [comment]
I also have the same problem!

**Comment by damiani** [comment]
Try installing `dev-master`; there's a fix (https://github.com/laravel/framework/pull/21261) related to fallback routes that I suspect will fix all these issues.

**Comment by themsaid** [comment]
fixed in https://github.com/laravel/framework/pull/21261

**Comment by xiaalngf** [comment]
修改 vendor\laravel\framework\src\Illuminate\Routing\RouteCollection.php文件 
`    protected function matchAgainstRoutes(array $routes, $request, $includingMethod = true)
    {
            //return collect($routes)->sortBy('isFallback')->first(function ($value) use ($request, $includingMethod) {
            return Arr::first($routes, function ($value) use ($request, $includingMethod) {
            return $value->matches($request, $includingMethod);
        });
    }`
这样可以修复

**Comment by marianomd** [comment]
I have this problem on version 6.11
