### ISSUE TITLE
Laravel 5.5.7 breaks horizon interface

### ISSUE THREAD

**Issue by ibrunotome** [laravel/framework#21262]
- Laravel Version: 5.5.7
- PHP Version: 7.1.9

### Description:
Hello, I just update all my dependencies with a composer update command and after that horizon loads indefinitely on front-end, that is, the back-end works perfectly but the front doesn't show my jobs and keep loading the content forever. I see the "spinning beach ball" on Mac.

I know that is not one of my other dependencies because works perfectly if I set laravel dependecy to 5.5.5 for example.

### Steps To Reproduce:
Just update composer with the following composer.json:

```
        "php": ">=7.1",
        "barryvdh/laravel-cors": "^0.9.3",
        "fideloper/proxy": "~3.3",
        "laravel/framework": "5.5.*",
        "laravel/horizon": "^1.0",
        "laravel/passport": "^4.0",
        "laravel/tinker": "~1.0",
        "league/fractal": "^0.17.0",
```

**Comment by themsaid** [comment]
fixed in https://github.com/laravel/framework/pull/21261
