### ISSUE TITLE
[5.5] Request validate redirect back with out _token.

### ISSUE THREAD

**Issue by ThunderBirdsX3** [laravel/framework#21265]
- Laravel Version: 5.5.4
- PHP Version: 7.1.8
- Database Driver & Version: MySQL 5.7.18

### Description:
In 5.5 they have `$request->validate([...]);` It will redirect back with errors and inputs.

But how to redirect back with `$request->session()->regenerateToken()` then except `_token` or  before redirect back.

Because when use `$request->session()->regenerateToken()` after  `$request->validate([...]);` it will error when make a new request.

### Steps To Reproduce:
```
$request->validate([...]); 

$request->session()->regenerateToken();
```

**Comment by Dylan-DPC** [comment]
This is intentional. Only the fields that are validated are returned back from the validation. If you want all the fields (that are not validated) you can use `$request->input()` or any of the other methods.
