### ISSUE TITLE
Fallback route not working with groups

### ISSUE THREAD

**Issue by tillkruss** [laravel/framework#21263]
The `Route::fallback()` doesn't seem to work well with groups. In my scenario I'd have to define 6 fallbacks, which seems like overkill.

`/{site}/foobar` triggers the fallback, but `/{site}/store/foobar` does not.

<img width="1971" alt="screen shot 2017-09-19 at 6 18 21 pm" src="https://user-images.githubusercontent.com/665029/30622525-05d798c4-9d67-11e7-81a4-2ad3dde92f0c.png">

<img width="740" alt="screen shot 2017-09-19 at 6 20 51 pm" src="https://user-images.githubusercontent.com/665029/30622583-54a357cc-9d67-11e7-87f2-de3366a1d2f8.png">

Ping @themsaid.

**Comment by themsaid** [comment]
that's fixed in https://github.com/laravel/framework/pull/21261
