### ISSUE TITLE
Laravel 5.5.6 and 5.5.7 routing issue

### ISSUE THREAD

**Issue by Nael-Saeed** [laravel/framework#21272]
- Laravel Version: 5.5.6 and 5.5.7
- PHP Version: php 7.0
- Database Driver & Version: MySQL 

### Description:
I am having routing issue after updating laravel 5.5.5 to 5.5.6 or 5.5.7. I have noticed that the issue is only with one level segment URI like domain.com/login, domain.com/register, domain.com/service ..etc. Where I get 404 page not found error always. But if the route is like domain.com/service/1 for example then everything works fine.

**Comment by Kyslik** [comment]
Might be related to https://github.com/laravel/framework/pull/21261

**Comment by marcoax** [comment]
I've  the  same  issue  with domain.com/admin

**Comment by themsaid** [comment]
This is fixed in a recent commit and a release is scheduled in a few hours.
