### ISSUE TITLE
Eloquent Model global scope not working properly with belongsToMany relationship

### ISSUE THREAD

**Issue by folospace** [laravel/framework#21274]
- Laravel Version: 5.4
- PHP Version:7.0
- Database Driver & Version:mysql 5.6

### Steps To Reproduce:
1. I have three tables: posts, terms, relations;
2. Assume term model has a global scope:
```
   protected static function boot()
    {
     parent::boot();
        static::addGlobalScope('category', function (Builder $builder) {
            $builder->where('type', 'category');
        });
    }
```
3. And post model related with term model through relations table like this:

```
    public function terms()
    {
        return $this->belongsToMany(
            'App\Term', 'relations',
            'post_id', 'term_id'
        );
    }
```
4. When I query post->terms(), result sql error:
`Integrity constraint violation: 1052 Column 'type' in where clause is ambiguous`

5. After testing a while, I found I need to modify step 2 to make it work properly:
`
$builder->where('type', 'category'); => $builder->where('terms.type', 'category');
`

6. As it is not documented, I decided to submit it here, while I'm not sure it should be considered an issue or not.

**Comment by themsaid** [comment]
Yes your global scope won't work in this situation when multiple tables has the same field name in your where clause, I suggest that you don't use a global scope in this case and adjust your query as per needed.

**Comment by 3li3bdalla** [comment]
You could do that 
```
 protected static function boot()
    {
       parent::boot();
       $table = (new static )->getTable();

        static::addGlobalScope('category', function (Builder $builder) use($table) {
            $builder->where("{$table}.type", 'category');
        });
    }
```
