### ISSUE TITLE
Laravel - Processing external forms

### ISSUE THREAD

**Issue by ASMOZA** [laravel/framework#21279]
- Laravel Version: 5.5.1
- PHP Version:7.0
- Database Driver & Version: mySql

### Description:
Hello,

I am a beginner on Laravel and I need your help on a particular subject, acceptance and processing of forms coming from an external web site to my site (developed in Laravel). There must be a blocking of Laravel for requests coming from the outside and I can not lift this blockage.

The route and the controller are created. If the form comes from the internal, the controller does his job without problem. But if the form comes from another web site, I have a 'FatalError' of the genus 'MethodNotAllowedHttpException'.

Do you have solutions for this issue ? Thanks

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
