### ISSUE TITLE
DatabaseSessionHandler::read() must return empty string instead of null

### ISSUE THREAD

**Issue by RomeroMsk** [laravel/framework#21276]
- Laravel Version: 5.5.2
- PHP Version: 7.1.9
- Database Driver & Version: pgsql

### Description:
According to [PHP manual](http://php.net/manual/en/sessionhandlerinterface.read.php), `\Illuminate\Session\DatabaseSessionHandler::read()` must return an empty string if nothing was read. Now it returns `null` in case of expired session or when `payload` is not set. It entails a warning:
```
session_start(): Failed to read session data
```

**Comment by themsaid** [comment]
Addressed in https://github.com/laravel/framework/pull/21277

Thanks

**Comment by RomeroMsk** [comment]
@themsaid, thanks for the fast reply! But you also need to add `return ''` in the end of this method.
