### ISSUE TITLE
Broken routes

### ISSUE THREAD

**Issue by LasseRafn** [laravel/framework#21278]
- Laravel Version: >5.5.6
- PHP Version: 7.1.8
- Database Driver & Version: MySQL 5.7

### Description:

When upgrading to Laravel 5.5.7 (5.5.6 is completely broke for me due to `cache:clear` command, so cannot try) my routes are broken, and simply get a redirect loop. For example trying to access a route that requires auth (middleware) loops over and over.

My web.php routes work, but any other routes won't work.

### Steps To Reproduce:

- Install Laravel 5.5.7
- Add another mapping in App\Providers\RouteServiceProvider.php for auth routes (e.g.: admin)
- Attempt to access them.

### Assumptions

I assume it has something to do with the new Route fallback changes, but I cannot check right now.

I will research later tonight 👍

**Comment by themsaid** [comment]
Yes, we're making a release soon that addresses this issue.

Sorry :)

**Comment by LasseRafn** [comment]
Oh, okay! Good you're on top of it, guess I don't need to look into it later then 👍 

No problem, just wanted to put it out there, I just rolled back to 5.5.5 for now :)
