### ISSUE TITLE
Wrong date format in listener when model created

### ISSUE THREAD

**Issue by rorc** [laravel/framework#21285]
- Laravel Version: 5.5.3

### Description:
I have mysql `date` field `date_of_invoice`.

```php
class Order extends Model
{
    protected $dates = ['date_of_invoice'];
}

class OrderCreatedListener
{
    public function handle(Created $order)
    {
        dump((string) $order->date); //wrong date format 2015-03-23 00:00:00
    }
}

Order::create([
    'date_of_invoice' => '2015-03-23'
]);
```

**Comment by Dylan-DPC** [comment]
This is intended. The `$dates` property on a model is for timestamps.

**Comment by rorc** [comment]
What difference between using `$dates = ['date_of_invoice']` and `$casts = ['date_of_invoice' => 'date']`.
Second case will same thing as first (with annoying 00:00:00).
