### ISSUE TITLE
[5.5] ProcessUtils::escapeArgument() is deprecated

### ISSUE THREAD

**Issue by carbontwelve** [laravel/framework#21281]
- Laravel Version: 5.5

### Description:
The `escapeArgument` method of the `ProcessUtils` class is marked as deprecated with the following warning:

> _The escapeArgument() method is deprecated since version 3.3 and will be removed in 4.0. Use a command line array or give env vars to the Process::start/run() method instead._

This is used by the `serverCommand` function that makes up the `serve` command on lines [50](https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Console/ServeCommand.php#L50) and [53](https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Console/ServeCommand.php#L53).

**Comment by themsaid** [comment]
We can still use it as long as we're using Symfony 3.* component, but thanks for the heads up :)

**Comment by DanielFurmanov** [comment]
I want to bring some attention to this issue, because this Exception fails unit-tests. Is there a way to mute it somehow or something like that? Maybe downgrade some packages?
