### ISSUE TITLE
session()->flash() throws Error Exception

### ISSUE THREAD

**Issue by younus93** [laravel/framework#21283]
- Laravel Version: 5.5.*
- PHP Version: 7.2 
- Database Driver & Version: MySQL

### Description:
When using session to flash data, an "Array to string exception is thrown"

### Steps To Reproduce:

In any controller/helper file, use
```
 session()->flash('notification',[
    'message' => 'Hello World'
]);
````

![screen shot 2017-09-20 at 4 37 43 pm](https://user-images.githubusercontent.com/4537724/30640815-215df050-9e22-11e7-8992-67024966451e.png)

**Comment by themsaid** [comment]
I'm unable to replicate your issue, the steps of reproduction is very limited, please add more details. Try to replicate it on a fresh laravel installation using your steps and you'll see everything is working as expected.

**Comment by mijgame** [comment]
I have experienced this exact issue as well. To replicate:

- `session()->flash('someKey', [1,2,3])`
- Navigate to any page

The only way to prevent the error show in the orignal post is to clear your cookies to disassociate your session. The issue arises when you flash an array, strings work fine.

**Comment by devcircus** [comment]
Confirm working correctly on 5.5.17

```php
// web.php
Route::get('/', function () {
    session()->flash('info', ['name' => 'Clay', 'color' => 'blue']);

    return redirect('/test');
});

Route::get('/test', function() {
    return view('test');
});
```
```php
<h1>Your flashed data:</h1>
<h5>Name: {{Session::get('info')['name']}}</h5>
<h5>Color: {{Session::get('info')['color']}}</h5>
```

**Comment by NelinD** [comment]
What session driver are you using?
