### ISSUE TITLE
password reset stub extra code

### ISSUE THREAD

**Issue by mehranrasulian** [laravel/framework#21289]
https://github.com/laravel/framework/blob/20ecf233e8a81e0603271e7b4484af3414f7ecf1/src/Illuminate/Auth/Console/stubs/make/views/auth/passwords/reset.stub#L14

Do we need this line? While there is a `csrf_field()`.

**Comment by devcircus** [comment]
That's a different token.

**Comment by far2** [comment]
That's not the CSRF token, that's the password reset token. If you do a password reset and view the code, it looks like this. You can see the same token in the url.

![image](https://user-images.githubusercontent.com/8172027/30646450-f393f1b2-9e10-11e7-8b81-be8aaa268ab2.png)

**Comment by mehranrasulian** [comment]
OOOPPS!! yes got that. srry
