### ISSUE TITLE
Migration should fail but goes through silently

### ISSUE THREAD

**Issue by pambuk** [laravel/framework#21302]
- Laravel Version: 5.5.6
- PHP Version: 7.1.8
- Database Driver & Version: mysql 5.7.9

### Description:
Incorrectly written code adding foreign key should fail (probably), but migration goes through, only the index is not created.

### Steps To Reproduce:

Run migration written like this (this incorrect code was written by mistake, but the reason for missing foreign key was hard to find):

```
$table
	->foreign('foos')
	->references('id')
	->on('bars')
	->onDelete('set null')
	->name('fk_my_key');
```

**Comment by sisve** [comment]
Can you provide a complete migration that reproduces the issue? So far it could just be a mismatch between the filename and the class name so the migration isn't executed, and wouldn't be related to your foreign key.

Foreign keys are keys, not indexes. It's a mysql thing to automatically create an index for a foreign key. Also, the way you've provided your database version indicate that you're telling us what version of the mysql client tools you have (and which version of mysql those were compiled with), not which version of mysql you're running on the server.

**Comment by pambuk** [comment]
On a clean install of laravel:

```
    public function up()
    {
        Schema::create('user_foos', function (Blueprint $table) {
            $table->increments('id');
            
            $table->unsignedInteger('user_id')->nullable();
            $table->foreign('user_id')->references('id')->on('users')->onDelete('set null')->name('fk_my_key');

            $table->timestamps();
        });
    }
```

I'm not sure about the mysql version though. How should I check it correctly?

**Comment by sisve** [comment]
You didn't give a complete migration. We need the using statements, the class name, the whole content of the migration file. We also need the filename of the migration.

Can you clarify what's wrong with that foreign key? Are you saying that the user_foos table isn't created at all, or just that the foreign key isn't?

You can get the database version by running the database query `select version()`.

**Comment by pambuk** [comment]
MySQL version: 5.7.9

user_foos table is created, but not the foreign key.

```php
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateUserFoosTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('user_foos', function (Blueprint $table) {
            $table->increments('id');

            $table->unsignedInteger('user_id')->nullable();
            $table->foreign('user_id')->references('id')->on('users')->onDelete('set null')->name('fk_my_key');

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('user_foos');
    }
}
```

**Comment by sisve** [comment]
Are you perhaps using the myisam table engine that doesn't support foreign keys?

**Comment by pambuk** [comment]
No, if the migration is written correctly (so the key name is given as a second param: $table->foreign('user_id', 'fk_my_key')) the key/index are created correctly.

**Comment by themsaid** [comment]
```
$table->foreign('user_id', 'fk_my_key')->references('id')->on('users')->onDelete('set null');
```

That's how a foreign key is named.

**Comment by pambuk** [comment]
That's the point, no error if you do it incorrectly, migration goes through and you're left with the illusion of working code.

**Comment by sisve** [comment]
And to  be fair, the second parameter is nullable and is supposed to be autogenerated if not provided. So it should work without the name.

https://github.com/laravel/framework/blob/76ea45df5570f0edff226ece11586b4af2fe0ca3/src/Illuminate/Database/Schema/Blueprint.php#L1082-L1085

**Comment by pambuk** [comment]
It works without a name, sure. I never had this problem, but I reported this behaviour because my friend had hard time debugging and it turned out migration should have failed (that's our opinion), but instead it worked only partially.
