### ISSUE TITLE
[Bug] Table prefix added to database name when using database.table

### ISSUE THREAD

**Issue by LeoYang90** [laravel/framework#21305]
- Laravel Version: 5.5.#
- PHP Version:7.1
- Database Driver & Version:

### Description:
Detail in #21295 

I am sure it is a database bug, but how can we fix it ? 

### Steps To Reproduce:

```php
DB::connection()->getGrammar()->setTablePrefix('prefix_');
$sql = DB::table('public.user')->toSql();
```

result：
```php
select * from "prefix_prefix_public"."user"
```

@themsaid

**Comment by themsaid** [comment]
Why do you set the database name? Every query connection has a single database.

**Comment by LeoYang90** [comment]
Why we have the test case in Illuminate\Tests\Database\DatabaseQueryBuilderTest, line 126:

```php
public function testBasicTableWrapping()
    {
        $builder = $this->getBuilder();
        $builder->select('*')->from('public.users');
        $this->assertEquals('select * from "public"."users"', $builder->toSql());
    }
```
?

**Comment by Dylan-DPC** [comment]
I don't see how that is related. That test is teting if a `from()` or `selects` work with table wrapping

**Comment by LeoYang90** [comment]
@Dylan-DPC You should see, DB::table() will call function from():
```php
class Connection implements ConnectionInterface
{
    public function table($table)
   {
      return $this->query()->from($table);
   }
}
```

**Comment by themsaid** [comment]
Please answer my question to help us understand better:

> Why do you set the database name? Every query connection has a single database.

**Comment by LeoYang90** [comment]
When we have two databases in one machine or host, we can join different table on different database, sql 

```
select a.id, b.id from db1.a as a left join db2.b as b on a.b_id = b.id
```

I think there are some reasons that the test case exists in file `Illuminate\Tests\Database\DatabaseQueryBuilderTest`, above is just one of them. If you think the test case is unnecessary, I can take a PR to delete it, and close this issue. thanks.

**Comment by themsaid** [comment]
Why don't you define multiple connections for this, that way you're able to better show what connection you need to use for the query.

**Comment by LeoYang90** [comment]
Sometime multiple connections can not resolve our problems. For example, we can not use multiple connections to paginate, sql
```
select a.id, b.id where a.country='UK' and b.country='US' from db1.a as a left join db2.b as b on a.b_id = b.id  limit 30 offset 2
```
how can we use multiple connections to achieve this sql?

In SQL SERVER, there is function `sp_addlinkedsrvlogin` that helps us build remote connection to other databases. It is proved that it is necessary even in distributed environment.

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo, closing this here since it's not considered as a bug with the current assumption laravel makes that each query hits a single database connection.
