### ISSUE TITLE
Class Swift_Transport_Esmtp_Auth_CramMd5Authenticator does not exist

### ISSUE THREAD

**Issue by wadleo** [laravel/framework#21307]
- Laravel Version: 5.4
- PHP Version: 7.0.22
- Database Driver & Version: Mysql 10.1.26

### Description:
I can't seem to send an email with laravel 5.4 on after setting the right configurations in config/mail.php. I'm using smtp driver here is summary of my files.

### Steps To Reproduce:
Here is the config/mail.php
<?php
return [
    'driver'=>env('MAIL_DRIVER', 'smtp'),       
    'host'=>env('MAIL_HOST', 'smtp.gmail.com'),
'port' => env('MAIL_PORT', 587),
'from' => [
    'address' => env('MAIL_FROM_ADDRESS', 'info@afecamworld.org'),
    'name' => env('MAIL_FROM_NAME', 'National President'),
],
'encryption' => env('MAIL_ENCRYPTION', 'ssl'),
'username' => env('MAIL_USERNAME', 'my-gmail-email'),
'password' => env('MAIL_PASSWORD', 'my-gmail-password'),
'sendmail' => '/usr/sbin/sendmail -bs',
'markdown' => [
    'theme' => 'default',
    'paths' => [
        resource_path('views/vendor/mail'),
    ],
], 
?>

This is part of controller that sends the mail
<?php 

public function register(Request $request) {

        $user = new User;
        $user->full_names = $request->full_names;
        $user->email = $request->email;
        $user->phone_number = $request->phone_number;

        $validate = Validator::make($request->all(), User::$signup_fields_rules);

        if ($validate->fails()) {
            return response()->json(['status'=>false, 'message' => $validate->errors()]);
        } else {
            if(strlen($request->password) > 5 && $request->password == $request->password_confirmation){
                $user->password = bcrypt($request->password);
                $user->save();

                $this->sendWelcomeMail($user);

                return response()->json(['status'=>true, 'message'=>'You have succesfully registered, check your email for the verification link, thanks.', 'data'=>$user]);
            } else {
                return response()->json(['status'=>false, 'message' => 'Sorry an error occurred, ensure passwords are the same and greater than 6 characters, thanks.']);
            }
        }
    }

    public function sendWelcomeMail($user){
        //sending a welcome mail
        \Mail::send('emails.welcome', $user, function ($message) use($user){

            $message->from('info@afecam.org', 'Afecam | Account Verification');

            $message->to($user->email)->subject("Welcome to Afecam Online Community");
        });

    }

?>
This is the top part of the error

(1/1) ReflectionExceptionClass Swift_Transport_Esmtp_Auth_CramMd5Authenticator does not exist
--
in DependencyContainer.php (line 309)
at ReflectionClass->__construct('Swift_Transport_Esmtp_Auth_CramMd5Authenticator')in DependencyContainer.php (line 309)
at Swift_DependencyContainer->_createNewInstance('transport.crammd5auth')in DependencyContainer.php (line 112)
at Swift_DependencyContainer->lookup('transport.crammd5auth')in DependencyContainer.php (line 371)
at Swift_DependencyContainer->_lookupRecursive('transport.crammd5auth')in DependencyContainer.php (line 365)
at Swift_DependencyContainer->_lookupRecursive(array('transport.crammd5auth', 'transport.loginauth', 'transport.plainauth', 'transport.ntlmauth', 'transport.xoauth2auth'))in DependencyContainer.php (line 348)
at Swift_DependencyContainer->_resolveArgs(array(array('type' => 'lookup', 'item' => array('transport.crammd5auth', 'transport.loginauth', 'transport.plainauth', 'transport.ntlmauth', 'transport.xoauth2auth'))))in DependencyContainer.php (line 129)
at Swift_DependencyContainer->createDependenciesFor('transport.authhandler')in DependencyContainer.php (line 312)
at Swift_DependencyContainer->_createNewInstance('transport.authhandler')in DependencyContainer.php (line 112)
at Swift_DependencyContainer->lookup('transport.authhandler')in DependencyContainer.php (line 371)
at Swift_DependencyContainer->_lookupRecursive('transport.authhandler')in DependencyContainer.php (line 365)
at Swift_DependencyContainer->_lookupRecursive(array('transport.authhandler'))in DependencyContainer.php (line 348)
at Swift_DependencyContainer->_resolveArgs(array(array('type' => 'lookup', 'item' => 'transport.buffer'), array('type' => 'lookup', 'item' =>array('transport.authhandler')), array('type' => 'lookup', 'item' => 'transport.eventdispatcher')))in DependencyContainer.php (line 129)
at Swift_DependencyContainer->createDependenciesFor('transport.smtp')in SmtpTransport.php (line 37)

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.

**Comment by wadleo** [comment]
ok
