### ISSUE TITLE
Error render blade in a custom blade directive

### ISSUE THREAD

**Issue by jdhtm** [laravel/framework#21316]
- Laravel Version: 5.5.x
- PHP Version: 7.1.3
- Database Driver & Version: Mysql 5.7 

### Description:

We have created a custom blade directive in the AppServiceProvider.php.

```php
<?php

namespace App\Providers;

use Illuminate\Support\Facades\Blade;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Blade::directive('render', function () {
            return view()->make('element', ['title' => "Hello World"])->render();
        });
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }
}

```
We render html of the render.blade.php file. 

```html
<h1>{{ $title }}<h1>
```

In the welcome.blade.php file we have inserted the custom blade directive.

```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Lorum Ipsum</title>
    </head>
    <body>
        @render()
    </body>
</html>

```

If the. /storage/framework/view folder is empty, this results in an error. The strange thing is that in the view folder one file was created but the name is not correct.

```
include(/home/vagrant/develop/funda/storage/framework/views/53fb374f0848205086e5060b50299a1596a6c10a.php): failed to open stream: No such file or directory (View: /home/vagrant/develop/funda/resources/views/welcome.blade.php)
```

File produced in view folder:

![file](https://cdn.indicium.nu/source/dev/file.png)

Is this something that we did wrong or does something else going on? Thanks in advance!

### Steps To Reproduce:

1. Create the above blade files containing the content

- render.blade.php
- welcome.blade.php

2. Register the custom blade directive in the AppServiceProvider. php
3. Run the artisan command: php artisan view:clear
4. Then access the page that create the welcome page

**Comment by Dylan-DPC** [comment]
Blade directives shouldn't be used to render views.

**Comment by jdhtm** [comment]
Can you explain why this is bad practice?

**Comment by themsaid** [comment]
You'll have to do something like:

```
Blade::directive('render', function () {
            return "<?php echo \$__env->make('render', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>";
        });
```

This ensures the same view factory is used to render both views, thus they'll both be available.

Check how blade compiles the @include directive

**Comment by jdhtm** [comment]
@themsaid Thanks for the explanation!
