### ISSUE TITLE
Laravel dd($array) displays non-structured array in Chrome developer tools

### ISSUE THREAD

**Issue by Sergey1983** [laravel/framework#21317]
- Laravel Version: #.#.#
- PHP Version: 7.1.3
- Database Driver & Version: InnoDB

### Description:
I have noticed that writing in Laravel's Controller:
dd($array) 
outputs an un-structured view of array in Chrome Developer Tools (chome 61.0.3163.91 64-bit, MAC OS).
![1](https://user-images.githubusercontent.com/17278829/30695244-2c0151a0-9ee0-11e7-9b46-3a11905a3790.jpg)
before it was something like:
![2](https://user-images.githubusercontent.com/17278829/30695382-a5a0e93a-9ee0-11e7-8601-fa2916da4a21.jpg)

here is what I see in Chrome->DevTools->Network->Response:
[response.txt](https://github.com/laravel/framework/files/1321090/response.txt)

### Steps To Reproduce:
(1) Create a controller and link it to web route.
(2) Create array ($array) inside a controller and dd($array);
(3) Load url for a route and see Chrome->DevTools->Network->Preview:

**Comment by Kyslik** [comment]
Its because you are getting "dd" result (var_dump() kind with types). Chrome dev tools preview only valid JSON data the way you seek.

**Comment by Dylan-DPC** [comment]
This isn't a bug and can be closed :+1:

**Comment by Sergey1983** [comment]
Hi! But I still think it's a bug. Maybe of Chrome.
Here are screenshots:
1) my code with dd
![screen1](https://user-images.githubusercontent.com/17278829/30967097-c930962e-a463-11e7-8a5c-4ff767ff7e41.jpg)

2) output in most recent version of Chrome in DevTools
![screen2](https://user-images.githubusercontent.com/17278829/30967106-cd5bc03e-a463-11e7-8727-85bd7c4193be.jpg)
3) output in previous Chrome version:
![screen3](https://user-images.githubusercontent.com/17278829/30967123-dab1cdfa-a463-11e7-8114-8e30af14d145.jpg)

It's obviuosly the Chrome version that causes the problem.

**Comment by rafwell** [comment]
This bug is back on Chrome 72. Also for laravel 5.5. The easiets solution (for me and for now), is downgrade google-crome-stable to version 71.

You can download here: https://www.slimjet.com/chrome/google-chrome-old-version.php

**Comment by bryandease** [comment]
I agree with @rafwell on this one. In my case the preview pane was completely blank when moving to version 72 of google and doing a simple dd(). Going back to 71 is the only thing that worked for me.

**Comment by robclancy** [comment]
Just for the record this is also broken on Chrome 73.

**Comment by devcircus** [comment]
Isn't dd() a symfony helper? Maybe 5.5 still has the laravel version though.

**Comment by driesvints** [comment]
@devcircus I believe it wasn't in 2017. This thread is a tad old.

**Comment by duyngha** [comment]
same for me.
<img width="572" alt="screen shot 2019-02-27 at 8 51 29 am" src="https://user-images.githubusercontent.com/8712540/53459558-ea1a9380-3a6c-11e9-9752-556138a6cb21.png">

It shows blank. Nothing is showed. I have to use `var_dump` and `die` instead.

**Comment by driesvints** [comment]
I'm closing this as I doubt anyone can contribute anything more than reporting that they also have the bug. This doesn't seems like anything we can fix ourselves.
