### ISSUE TITLE
Add support for json inline path operator

### ISSUE THREAD

**Issue by fede91it** [laravel/framework#21315]
- Laravel Version: 5.4
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7.17

### Description:

As described in the MySQL 5.7 documentation, JSON columns support two search operators. The first is `->` and the second is `->>`. 

Eloquent is already able to manage the operator `->` and the resulting SQL is correct but, when using the operator `->>` in the resulting SQL, the operator `->` is used instead of `->>`.

If in normal cases the operators in practical terms have the same effect, in specific cases it is necessary for the operator `->>` and Laravel should recognize and support this second operator as well. 

### Steps To Reproduce:

Using `->`

```php
Location::where('foo->bar', 'something')
        ->get();
```

Output:

```sql
select * from `locations` where `foo`->'$."bar"' = 'something'
```

Using  `->>`

```php
Location::where('foo->>bar', 'something')
        ->get();
```

Output:

```sql
select * from `locations` where `foo`->'$."bar"' = 'something'
```

This issue is also reflected in `Eloquent:: whereIn` method that, because do not support the operator `->>`, it will not work when used on JSON columns, at least if the values of the set will be quoted.

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. This isn't a bug so you can open a proposal in the laravel/internals repo

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.

**Comment by fede91it** [comment]
See https://github.com/laravel/internals/issues/804
