### ISSUE TITLE
Single letter artisan namespace doesn't work on Windows

### ISSUE THREAD

**Issue by lancepioch** [laravel/framework#21321]
- Laravel Version: 5.4.27
- PHP Version: 7.0
- Database Driver & Version: not database related

### Description:
Having only a single letter before the first colon will prevent the command from being run on Windows. It tries to capitalize the letter, then find the namespace of that capitalized letter and fails. Having 2 or more lets the command be recognized fine.

`php artisan p:user` returns an error
`php artisan pt:user` works fine

Error in console:
```
develop.ERROR: Symfony\Component\Console\Exception\CommandNotFoundException: There are no commands defined in the "P" namespace. in C:\wamp\www\panel\vendor\symfony\console\Application.php:538
Stack trace:
#0 C:\wamp\www\panel\vendor\symfony\console\Application.php(570): Symfony\Component\Console\Application->findNamespace('P')
#1 C:\wamp\www\panel\vendor\symfony\console\Application.php(209): Symfony\Component\Console\Application->find('P:user')
#2 C:\wamp\www\panel\vendor\symfony\console\Application.php(130): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 C:\wamp\www\panel\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 C:\wamp\www\panel\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 {main} 
```

### Steps To Reproduce:

Create command with single letter before colon:
`protected $signature = 'p:test';`

If you add another letter before the colon, it works just fine.

**Comment by browner12** [comment]
ahh, windows.

how about just a PR to laravel/docs to add a note about this?

**Comment by sebdesign** [comment]
The error is triggered in the symfony component, maybe you should create an issue there.

**Comment by Dylan-DPC** [comment]
@lancepioch there is nothing we can do to solve this. You can close the issue and open it on symfony repo if needed
