### ISSUE TITLE
Broken DB aliasing

### ISSUE THREAD

**Issue by ircop** [laravel/framework#21331]
- Laravel Version: 5.5
- PHP Version: 7.1
- Database Driver & Version: MySQL 

### Description:

In laravel 5.3+ (5.3, 5.4, 5.5) native SQL aliasing (without 'as') is broken by SQL Grammar wrap operations.

This simple query works in <= 5.2 and doesn't works in 5.5:

$u = User::select('login l')->get();

gives: 

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'login l' in 'field list';

Also broken are:

JOIN aliasing ( i.e. "inner join table T")
FROM aliasing ( i.e. "select T.* from table1 T, table2 T2"), etc

It's absolutely valid and convenient expressions :(

**Comment by LeoYang90** [comment]
In general, we can use `$u = User::select('login as l')->get();`

**Comment by ircop** [comment]
I have tons of code written beginnig from Laravel 4+ without 'as' :(

Why should we limit working native sql language?

**Comment by Dylan-DPC** [comment]
I don't see this as a bug.

**Comment by kamui545** [comment]
@ircop Should be easy to regex/replace
