### ISSUE TITLE
redis throttle inside queued jobs & rate-limiting outgoing api calls

### ISSUE THREAD

**Issue by vesper8** [laravel/framework#21346]
- Laravel Version: 5.5
- PHP Version: 7.1

I've been having a hard time handling the rate limiting on Forge's API. It's 30 api calls per 60 seconds.

I've tried a few different approaches but they've all resulted in inaccuracy and race conditions. One method, using a guzzle client with a middleware that checks the X-RateLimit-Remaining header after each api call.. worked well if I only have a single queue worker doing api calls. But the moment I have multiple workers on that queue I have multiple jobs that think there's enough api calls left and they overlap and cause "Too many attempts" errors.

So I turned to the latest offerings with redis throttling. I've tried two things and they both failed:

I have one job whose job is to queue other jobs that each perform 1 API call.

First, I tried adding this inside all my jobs that each perform 1 and only 1 api call

```
        Redis::throttle('forge_api')->allow(30)->every(60)->then(function () {
            // perform 1 api call
        }, function () {
            return $this->release();
        });
```

If I queue a whole bunch of these, it all seems to work at first.. doesn't cause "too many attempts" during the first minute. But around minute 2 it suddenly causes 30 "too many attempts" all at once

I have theories on what might be failing but.. I'm not sure.

I'm also not clear what's the point of adding a delay to the `$this->release()`, or whether it's mandatory to release the job back.. what happens if I don't?

And I'm also not clear how to make it retry until it succeeds. The docs recommend using a time-based attempt.. using

```
public function retryUntil()
{
    return now()->addSeconds(5);
}
```

But I'm not clear how long I should put here. Should I just put retries to 0 (unlimited) Or would it make sense for the job to keep trying to get a lock for 5 minutes? What is this saying exactly? If I put 30 seconds.. will it keep trying to get a lock for 30 seconds and THEN it will get released back onto the queue?

While testing I also noticed what I think is a bug or an anomaly.

I tried wrapping my job that dispatches other jobs in its own Redis throttle. But with a different key then the others:

```
    public function handle()
    {
        Redis::throttle('forge_site_refresh')->allow(7)->every(60)->then(function () {

            dispatch(new \MyVendor\MyPackage\Jobs\Forge\Site\EnvFile($this->site));
            dispatch(new \MyVendor\MyPackage\Jobs\Forge\Site\NginxFile($this->site));
            dispatch(new \MyVendor\MyPackage\Jobs\Forge\Site\SslCertificates($this->site));
            dispatch(new \MyVendor\MyPackage\Jobs\Forge\Site\Workers($this->site));

            $this->site->refreshed_at = date('Y-m-d H:i:s');
            $this->site->save();

        }, function () {
            return $this->release();
        });
    }
```

This job dispatches 4 other jobs, and they each perform 1 api call. So it makes sense to throttle this job so it only fires 7 times per minute (28 calls)

Since this throttling uses a different key (forge_site_refresh) than the other throttles inside the sub-jobs (forge_api), I expected it to dispatch 7 sets of those 4 jobs above immediately, and then the sub-jobs themselves would be throttled at a 30/minute rate inside right away. But 28 of them should be started immediately.

But that's not what happens if you do this.. instead it runs the above 7 times as expected.. but then it waits a full minute before beginning to process the sub-jobs.. as if I was using the same throttle key everywhere. Why does it stagger like that? Bug?

So anyway.. this is complicated.. I'm nowhere near finding a proper way of staying clear of the "too many attempts" error.. the above code should work.. the 30/60 minute throttling.. but why doesn't it? And is there another better method?

**Comment by vesper8** [comment]
well

```
Redis::throttle('forge_api')->allow(30)->every(70)->then(function () {
            // perform 1 api call
        }, function () {
            return $this->release();
        });
```

seems to be working superbly.. maybe it's just not possible or reasonable to do 30/60 exactly.. 30/62 probably works too

**Comment by Kyslik** [comment]
I had to solve exactly same problem and if API endpoint supports returning rate_limit (like GitHub does https://api.github.com/rate_limit) you can check beforehand if you can make a API request and decide upon that. Its not throttling per se but being careful (same logic will work in case API endpoint is offline). 

If job can not make API call it returns itself back to queue without attempts field altered but with <random amount> second delay.

And yes this is complicated...

**Comment by themsaid** [comment]
@vesper8 we're going to increase the Forge limit a bit, it's also currently a bit aggressive, we'll make it more soft on requests in a future update.

**Comment by pfaffenrodt** [comment]
Why was this issue closed?
@vesper8 had a bunch of questions and non of them was answered. Now 

I am asking, because we are trying to solve the same issue. 
We have to solve a bit more throttled api. 10 api calls per minute.
I was first so happy that there is this throttle api with redis and then so unhappy of the result.

framework version 5.6.26
```
Redis::throttle('external')->allow(1)->every(90)->then(function () {
                $this->handleJob();
            }, function () {
                return $this->release(60);
            });
```
```
+----+------------+-------+---------------+---------------------+
| ID | Connection | Queue | Class         | Failed At           |
+----+------------+-------+---------------+---------------------+
| 25 | redis      | live  | App\Jobs\JobX | 2018-09-01 00:15:07 |
| 24 | redis      | live  | App\Jobs\JobX | 2018-09-01 00:15:04 |
| 23 | redis      | live  | App\Jobs\JobX | 2018-09-01 00:15:01 |
| 22 | redis      | live  | App\Jobs\JobX | 2018-09-01 00:14:58 |
| 21 | redis      | live  | App\Jobs\JobX | 2018-09-01 00:14:54 |
| 20 | redis      | live  | App\Jobs\JobX | 2018-09-01 00:14:51 |
| 19 | redis      | live  | App\Jobs\JobX | 2018-09-01 00:14:48 |
| 18 | redis      | live  | App\Jobs\JobX | 2018-09-01 00:14:45 |
| 17 | redis      | live  | App\Jobs\JobX | 2018-09-01 00:14:42 |
| 16 | redis      | live  | App\Jobs\JobX | 2018-09-01 00:14:38 |
| 15 | redis      | live  | App\Jobs\JobX | 2018-09-01 00:14:35 |
| 14 | redis      | live  | App\Jobs\JobX | 2018-09-01 00:14:32 |
| 13 | redis      | live  | App\Jobs\JobX | 2018-09-01 00:14:29 |
| 12 | redis      | live  | App\Jobs\JobX | 2018-09-01 00:14:29 |
| 11 | redis      | live  | App\Jobs\JobX | 2018-09-01 00:14:25 |
| 10 | redis      | live  | App\Jobs\JobX | 2018-09-01 00:14:22 |
| 9  | redis      | live  | App\Jobs\JobX | 2018-09-01 00:14:19 |
| 8  | redis      | live  | App\Jobs\JobX | 2018-09-01 00:14:16 |
| 7  | redis      | live  | App\Jobs\JobX | 2018-09-01 00:14:12 |
| 6  | redis      | live  | App\Jobs\JobX | 2018-09-01 00:14:09 |
| 5  | redis      | live  | App\Jobs\JobX | 2018-09-01 00:14:06 |
| 4  | redis      | live  | App\Jobs\JobX | 2018-09-01 00:14:06 |
| 3  | redis      | live  | App\Jobs\JobX | 2018-09-01 00:14:06 |
| 2  | redis      | live  | App\Jobs\JobX | 2018-09-01 00:14:05 |
| 1  | redis      | live  | App\Jobs\JobX | 2018-09-01 00:14:05 |
+----+------------+-------+---------------+---------------------+
```

Shouldn't the jobs be delayed by 90 seconds ?

I also tried to understand what is happening behind the throttle implementation (to maybe find a bug). But I was not able to understand what is happening in the lua scripts.


Is it possible that the cause of this Issue is that a job is failing at all? So if a job is failing an other job start  immediately without throttling.

I hope someone can explain more, what is happening behind the scenes.

**Comment by pfaffenrodt** [comment]
Ok, now I understood, what is happening.

In my case I reached max attempts. 

1. Job tries to obtain lock (default timeout is 3 secs)
2. timeout kicks in -> second callback is invoked.
3. In callback we call ($this->release(x)). So that the job can retry to obtain lock in a new attempt.

so for example: 
we allow 30 api calls every 60 seconds:
Redis::throttle('api')->allow(30)->every(60)

We could increase the timeout to min 60 seconds to avoid max attempts.

Redis::throttle('api')->allow(30)->every(60)->block(70)

But with this approach we will block an process for at least for 60 seconds.
And the default worker timeout for child process is 60 seconds. So we need to increase this timeout also.
php artisian queue:work --timeout=90

Alternative would be to create an new job.
