### ISSUE TITLE
Why the Illuminate\Contracts\Routing\Registrar	doesn't have the methods redirect and view?

### ISSUE THREAD

**Issue by diegosm** [laravel/framework#21345]
- Laravel Version: 5.5.0

Why the Illuminate\Contracts\Routing\Registrar	doesn't have the methods redirect and view?

**Comment by pavinthan** [comment]
redirect, view is responses, router doesn't need it.

**Comment by diegosm** [comment]
and why it is a part of Route Facade  ??? See these methods in Illuminate\Routing\Router.php

**Comment by decadence** [comment]
@pavinthan
Router has redirect and view methods.

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by pavinthan** [comment]
@decadence that router it not booting with your application, see this [https://laravel.com/docs/5.5/lifecycle](https://laravel.com/docs/5.5/lifecycle)

**Comment by devcircus** [comment]
The redirect and view methods are new in the Router class (Route facade) as a shortcut for routes that redirect or just return a view.
https://laravel.com/docs/5.5/routing#redirect-routes
