### ISSUE TITLE
PHP Fatal Error if MySQL has stopped

### ISSUE THREAD

**Issue by jeinsweiler** [laravel/framework#21340]
- Laravel Version: Laravel Framework 5.5.11
- PHP Version: PHP 7.1.9 (cli) (built: Sep  6 2017 11:45:26) ( NTS )
- Database Driver & Version: mysql 10.1.26-MariaDB

### Description:

This is minor but feel like the message could be more helpful. When mariadb is stopped for some reason I get the error pasted below in my logs and nothing in Laravel log. When the database server is then started the problem is no more. Maybe it could make a note that it could not connect instead?

2017/09/22 13:21:13 [error] 1850#0: *287 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 36864 bytes) in /var/www/*/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 47
PHP message: PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /var/www/*/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 47" while reading response header from upstream, client: *, server: _, request: "GET /* HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/www.sock:", host: "*", referrer: "*"

### Steps To Reproduce:
Stop mysql and attempt to run the Laravel application.

**Comment by Dylan-DPC** [comment]
I am not sure there is much we can do here. The error occurs in Driver vendor class.

**Comment by themsaid** [comment]
Laravel will keep retrying to connect in case of connection lost.
