### ISSUE TITLE
Paginator::resolveCurrentPage() returns string not int as stated by docblock

### ISSUE THREAD

**Issue by SlyDave** [laravel/framework#21349]
- Laravel Version: 5.5
- PHP Version: 7.1

### Description:
Paginator::resolveCurrentPage() returns string, not int as stated by its docblock, breaking strictness compliance when you enforce it on signatures, unless you cast it...

However it does return an int if it returns the default values, so its return type is also inconsistent

### Steps To Reproduce:

>     /**
>      * Resolve the current page or return the default value.
>      *
>      * @param  string  $pageName
>      * @param  int  $default
>      * @return int
>      */
>     public static function resolveCurrentPage($pageName = 'page', $default = 1)
````
    // When Paginator has a Resolver registered (as in the case for the defaults built into Laravel)
    $page = Paginator::resolveCurrentPage();
    var_dump(gettype($page)); 
    // string(6) "string"
````

**Comment by themsaid** [comment]
Addressed in https://github.com/laravel/framework/pull/21378
