### ISSUE TITLE
intersect method on the $request object doesn't work laravel 5.5

### ISSUE THREAD

**Issue by ibrhaim13** [laravel/framework#21360]
- Laravel Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
intersect method on the $request object doesn't work laravel 5.5???
it's was work with 5.4, now not ,what happens?
example 
    protected function getFilters(){

       return $this->request->intersect($this->filters);
     }

**Comment by ibrhaim13** [comment]
OK, I solved it,
before 
protected function getFilters(){
   return $this->request->intersect($this->filters);
 }
after
protected function getFilters(){
   return $this->request->only($this->filters);
 }
now it;s work

**Comment by lecongdanh5990** [comment]
This is a good  solution
