### ISSUE TITLE
Laravel 5.5 - BadMethodCallException: Method intersect does not exist

### ISSUE THREAD

**Issue by nolros** [laravel/framework#21369]
- Laravel Version: 5.5
- PHP Version: 7.16
- Database Driver & Version: mySQL 5.7

### Description:
1. Getting a BadMethodCallException: Method intersect does not exist on  return $this->request->intersect($this->filters); Looking for 

2. It is attempting to make the the call to __call magic method in Traits/Macroable.php:97 but cannot find intersect method intersect in trait InteractsWithInput

3. Works fine in 5.4 as it can find intersect in  trait InteractsWithInput

    /**
     * Intersect an array of items with the input data.
     *
     * @param  array|mixed  $keys
     * @return array
     */
    public function intersect($keys)
    {
        return array_filter($this->only(is_array($keys) ? $keys : func_get_args()));
    }
 
### ERROR MESSAGE

```
4) Tests\Feature\ReadThreadsTest::a_user_can_filter_threads_by_popularity
        BadMethodCallException: Method intersect does not exist.
        
    /Users/nolros/Documents/cmoforum/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:97
        /Users/nolros/Documents/cmoforum/app/Filters/Filters.php:64
        /Users/nolros/Documents/cmoforum/app/Filters/Filters.php:48
        /Users/nolros/Documents/cmoforum/app/CMOForum/Forum/Models/Thread.php:118
        /Users/nolros/Documents/cmoforum/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:953
        /Users/nolros/Documents/cmoforum/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:1266
        /Users/nolros/Documents/cmoforum/app/Http/Controllers/ThreadsController.php:132
        /Users/nolros/Documents/cmoforum/app/Http/Controllers/ThreadsController.php:31
```

### TEST

    /** @test */
    function a_user_can_filter_threads_by_popularity()
    {
        $threadWithTwoReplies = create(Thread::class);
        create(Reply::class, ['thread_id' => $threadWithTwoReplies->id], 2);

        $threadWithThreeReplies = create(Thread::class);
        create(Reply::class, ['thread_id' => $threadWithThreeReplies->id], 3);

        $threadWithNoReplies = $this->thread;

        $response = $this->getJson('threads?popular=1')->json();

        $this->assertEquals([3, 2, 0], array_column($response['data'], 'replies_count'));
    }

### ABSTRACT CLASS 

    abstract class Filters
    {
    /**
     * @var Request
     */
    protected $request;

    /**
     * The Eloquent builder.
     *
     * @var \Illuminate\Database\Eloquent\Builder
     */
    protected $builder;

    /**
     * Registered filters to operate upon.
     *
     * @var array
     */
    protected $filters = [];

    /**
     * Create a new ThreadFilters instance.
     *
     * @param Request $request
     */
    public function __construct(Request $request)
    {
        $this->request = $request;
    }

    /**
     * Apply the filters.
     *
     * @param  \Illuminate\Database\Eloquent\Builder $builder
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function apply($builder)
    {
        $this->builder = $builder;

        foreach ($this->getFilters() as $filter => $value) {
            if (method_exists($this, $filter)) {
                $this->$filter($value);
            }
        }

        return $this->builder;
    }

    /**
     * Fetch all relevant filters from the request.
     *
     * @return array
     */
    public function getFilters()
    { 
       ### FAILING
        return $this->request->intersect($this->filters);
    }
    }

**Comment by devcircus** [comment]
Wasn't intersect removed in 5.5?

**Comment by decadence** [comment]
https://github.com/laravel/framework/issues/21360

**Comment by devcircus** [comment]
Removed in #18695.

**Comment by nolros** [comment]
@devcircus No it still exists in  trait InteractsWithInput and trait is on Request my guess is the magic __call in Macroables added in 5.5 is executing intersect before it gets to the trait

**Comment by devcircus** [comment]
Here's the interactswithinput trait. I can't find intersect.
https://github.com/laravel/framework/blob/5.5/src/Illuminate/Http/Concerns/InteractsWithInput.php

**Comment by nolros** [comment]
@devcircus my bad I added it in to test. You right removed. Thanks a million!

**Comment by egulhan** [comment]
I've faced this situation while studying a lesson on laracasts.com. If anyone reached this page like me, here is the solution for them:

`
protected function getFilters()
{
    $filters = array_intersect(array_keys($this->request->all()), $this->filters);
    return $this->request->only($filters);
}
`

**Comment by Xbot-me** [comment]
@egulhan thanks a lot man

**Comment by ph0054** [comment]
> I've faced this situation while studying a lesson on laracasts.com. If anyone reached this page like me, here is the solution for them:
> 
> ```
> protected function getFilters()
> {
>     $filters = array_intersect(array_keys($this->request->all()), $this->filters);
>     return $this->request->only($filters);
> }
> ```

Thanks @egulhan, that works fine.

**Comment by Tenevyk** [comment]
This way is better, IMHO

   ```
 public function getFilters()
    {
        return $this->intersect($this->filters);
    }

    public function intersect($keys)
    {
        return array_filter($this->request->only(is_array($keys) ? $keys : func_get_args()));
    }
```
