### ISSUE TITLE
$request->replace Method not working as expected

### ISSUE THREAD

**Issue by brizov43** [laravel/framework#21365]
- Laravel Version: 5.5.12 (maybe earlier too)
- PHP Version: any
- Database Driver & Version: MySQL 5.6

### Description:
When using ```$request->replace()``` and subsequently ```$request->all()``` the original Data is given back instead of the replaced data.

### Steps To Reproduce:
Just create a middleware which will filter out any input with a null value:
```
public function handle($request, Closure $next)
    {
        $request->replace($this->filterNullValues($request->all()));
        return $next($request);
    }

    public function filterNullValues($dataInput)
    {
        return array_filter($dataInput, function ($element) {
            return $element != null;
        });
    }
```
Then in the controller you can ```dd(request()->all())``` to see that the data is unchanged.

### Presumed source of the problem:
Illuminate\Http\Concerns\InteractsWithInput
Line 188:
```
public function input($key = null, $default = null)
    {
        return data_get(
            $this->getInputSource()->all() + $this->query->all(), $key, $default
        );
    }
```
Removing the ```$this->query-all()``` solves the issue temporarily.

**Comment by brizov43** [comment]
It was a stupid mistake on my part, an oversight in a test - I was passing in the query string instead of the request body.

**Comment by mtx-z** [comment]
- Laravel 5.2
- Mysql
- PHP 7.1

I just ran in the kind of same issue on Laravel 5.2.
I use `replace()` to sanitize some data. I also tried with `merge()` but the result is the same. 

```
$request->get('description') //'test'
$request->replace(['description => 'test2"]);

$request->all(); // description => test2
$request->description //test2
$request->get('description') //test (wrong). 
```

Is it related ? 

Thanks

**Comment by inotloh** [comment]
```
$this->merge([$param => $new_value]);
$this->query->set($param, $new_value);
$this->request->set($param, $new_value);
if ($this->isJson()) {
    $this->json()->set($param, $new_value);
}
```

**Comment by boka18** [comment]
> Solution
> 
> ```
> $this->merge([$param => $new_value]);
> $this->query->set($param, $new_value);
> $this->request->set($param, $new_value);
> if ($this->isJson()) {
>     $this->json()->set($param, $new_value);
> }
> ```

I wanted to disable sending query params on Put and Post and this worked pretty good.
```php
    public function handle($request, Closure $next)
    {
        if ($request->getMethod() == 'PUT' || $request->getMethod() == 'POST') {
            $request->query->replace([]);
        }
        return $next($request);
    }
```
