### ISSUE TITLE
hasManyThrough with an intermediate pivot table

### ISSUE THREAD

**Issue by mtrajano** [laravel/framework#21367]
- Laravel Version: 5.4.18
- PHP Version: 7.1.4
- Database Driver & Version: mysql (14.14)

### Description:
My application is structured as follows:
`Property` has a Many-Many relationship with `Manager`, and a `Unit` has a One-Many relationship with a `Property`, i.e. A manager can manage multiple properties, one property can have multiple manager accounts and one property can have multiple units.

I would like to have a HasManyThrough relationship on the manager to get all his units, so ideally it would look something like: `$manager->units` instead of having through loop through each property and call `$property->units` on it. Is this possible with the current version of laravel?

### Tables:
managers:
- id

properties:
- id

managers_properties:
- manager_id
- property_id

units:
- id
- property_id

**Comment by Dylan-DPC** [comment]
This repo is for bug fixing. If you want to make a proposal use the `laravel/internals` repo. If you need help, use the forums or the slack channel

**Comment by mtrajano** [comment]
@Dylan-DPC thanks for letting me know, I'll move it to the correct place

**Comment by Dylan-DPC** [comment]
@mtrajano do close this issue :+1:
