### ISSUE TITLE
Can't use where like in collection

### ISSUE THREAD

**Issue by EkinOf** [laravel/framework#21375]
- Laravel Version: 5.4.36
- PHP Version: 7.1.7
- Database Driver & Version: PDO SQL (Mysql 14.14)

### Description:

I can't use the where function with "like" parameters after getting a Laravel Collection. I got empty Collection every time, but when I test the like parameter before getting the collection it works.

### Steps To Reproduce:

```
$collection = Object::all();
$collection->where('name', 'like', '%query%);
// Collection is empty
dd($collection);
```

but with that

```
$collection = Object::where('name', 'like', '%query%)->get();
// Collection is not empty
dd($collection);
```

**Comment by ntzm** [comment]
That's because it's not supported: https://github.com/laravel/framework/blob/5.5/src/Illuminate/Support/Collection.php#L487-L496

If you would like to propose this to be added, please open an issue in https://github.com/laravel/internals/issues

**Comment by EkinOf** [comment]
Thanks for the answer.
All this steps just to report issues and make suggestions, I will never get used to.

**Comment by Kyslik** [comment]
@EkinOf you make suggestions in [internals](https://github.com/laravel/internals), you open up bugs here and **reproducing bug steps** is essential in order to fix it.
