### ISSUE TITLE
Rediscluster cannot work correct when use phpredis driver (zadd command)

### ISSUE THREAD

**Issue by XiaoLer** [laravel/framework#21371]
- Laravel Version: 5.5.0
- PHP Version:7.1
- Database Driver & Version: phpredis 3.1

It's beacause `rawCommand` method has different parameters:

**redis**: proto mixed Redis::rawcommand(string $command, [ $arg1 ... $argN]) 
https://github.com/phpredis/phpredis/blob/develop/redis.c#L3318

**rediscluster**: proto mixed RedisCluster::rawcommand(string $key, string $cmd, [ $argv1 .. $argvN])
https://github.com/phpredis/phpredis/blob/develop/redis_cluster.c#L2909

**Comment by wanghanlin** [comment]
I checked the code and I think it should be working, you just need pass different arguments yourself, Laravel here is just a proxy of command.
Can you show your usage code that having the error?
