### ISSUE TITLE
Laravel foreach in blade template overiding variables

### ISSUE THREAD

**Issue by itbdw** [laravel/framework#21374]
- Laravel Version: 5.1.46
- PHP Version:7.0
- Database Driver & Version:not important

### Description:
Laravel foreach in blade template overiding variables.

It changes the variable $user after the name has been used in foreach block, while this is not in pure PHP and other systems.

```
{{ $user['username'] }}   
  
@foreach ($followers as $user)
      {{$user['username']}}
@endforeach

{{ $user['username'] }}
```

### Steps To Reproduce:
1, Define a array called $followers and a $user
```
      $data = [
            "user"=>["username"=>"original_name"]
            "followers" => [
                    ["username"=>"new_name"]
            ]
      ];
```
2, Paint it to template

**Comment by decadence** [comment]
PHP foreach (which is used under the hood) has the same behaviour

**Comment by itbdw** [comment]
Yes, my fault. And I hate this behavior. 😭
