### ISSUE TITLE
`schedule:run` command doesn't write to file specified by `sendOutputTo`

### ISSUE THREAD

**Issue by BrandonLegault** [laravel/framework#21385]
- Laravel Version: 5.2
- PHP Version: 7.0
- Database Driver & Version: Postgres 9.6

### Description:
When running schedules (Closures, not commands), the scheduler will never output to any file specified in the `->sendOutputTo()` method.

### Steps To Reproduce:

In `app/console/Kernel.php`

```php
protected function schedule(Schedule $schedule) {
    $schedule->call(function() {
        echo 'hello';
        return 'hello';
    })
    ->everyMinute()
    ->sendOutputTo('path/to/a/file');  
}
```

Tried with both a cron job as well as running via CLI. Looking into the code I see that the event returned by `$schedule->call(....` is a `CallbackEvent` which doesn't have the same `run` code that `Event` has to build a command to append output to the file.

**Comment by devcircus** [comment]
According to the documentation:
> The emailOutputTo, sendOutputTo and appendOutputTo methods are exclusive to the  command method and are not supported for call.

See: https://laravel.com/docs/5.5/scheduling#task-output

**Comment by Dylan-DPC** [comment]
@BrandonLegault you can close this issue

**Comment by hansenconnor** [comment]
Alternatively, you may use `var_dump()` to view the results in your terminal.
