### ISSUE TITLE
[5.5] Model binding isn't working on api routes in Laravel 5.5

### ISSUE THREAD

**Issue by ajoy39** [laravel/framework#21383]
- Laravel Version:5.5.5
- PHP Version: 7.1.8
- Database Driver & Version: MariaDB 10.2.8

### Description:

Trying to use model binding on my api routes, I have tried passing both an ID and a slug and in both cases am just getting a new, empty instance. 

### Steps To Reproduce:

My Route

`Route::get('credits/{user}', 'CreditsController@index');`

My Function signature

` public function index(User $user, Request $request)`

My middleware

    protected $middlewareGroups = [
        'web' => [
             \App\Http\Middleware\EncryptCookies::class,
             \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
             \Illuminate\Session\Middleware\StartSession::class,
             \Illuminate\View\Middleware\ShareErrorsFromSession::class,
             \App\Http\Middleware\VerifyCsrfToken::class,
             \Illuminate\Routing\Middleware\SubstituteBindings::class,
         ],

        'api' => [
            'throttle:60,1',
            'bindings'
            \App\Http\Middleware\EncryptCookies::class,
               \Illuminate\Session\Middleware\StartSession::class,
                \App\Http\Middleware\VerifyCsrfToken::class,
            ],
        ];

**Comment by pavinthan** [comment]
first you have syntax error in 
```
'throttle:60,1',
'bindings'
```

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
