### ISSUE TITLE
Artisan call command annotation is missing third parameter

### ISSUE THREAD

**Issue by zlokomatic** [laravel/framework#21396]
- Laravel Version: 5.5
- PHP Version: 7.1
- Database Driver & Version:

### Description:
The ```Artisan::call``` annotation in https://github.com/laravel/framework/blob/c91cf5fb04c8710b9b3e36511124a107bd70116e/src/Illuminate/Support/Facades/Artisan.php#L9 is missing the third parameter

See https://github.com/laravel/framework/blob/c91cf5fb04c8710b9b3e36511124a107bd70116e/src/Illuminate/Foundation/Console/Kernel.php#L245

### Steps To Reproduce:
```
$output = new BufferedOutput();
Artisan::call('doSomething', [], $output);
```

**Comment by themsaid** [comment]
Thanks, update here: https://github.com/laravel/framework/commit/572bade35af225818b39c6ce016ece38ed546439
