### ISSUE TITLE
In sqlsrv string() migration creates nvarchar column

### ISSUE THREAD

**Issue by ownmaster** [laravel/framework#21394]
- Laravel Version: 5.5.3
- PHP Version: 7.19
- Database Driver & Version: php_pdo_sqlsrv_71_nts.dll (x64)
- Database Server: MS SQL 2008 R2 Std x64

### Description:
`$table->string('column_name', 1)` in table creation migration file generates `nvarchar(1)` instead of `varchar(1)` as documentation states.

How can I control the generated type: i.e. select varchar or nvarchar based on project needs?

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.

**Comment by ownmaster** [comment]
Well, I guess if documentation says it should be varchar and the result is nvarchar this can be considered as a bug.
