### ISSUE TITLE
the list that result from php artisan route:list is showing in the cmd unorganized 

### ISSUE THREAD

**Issue by abdolrhman** [laravel/framework#21393]
- Laravel Version: 5.5
- PHP Version:7
- Database Driver & Version: mysql

### Description:
the list that result from php artisan route:list is showing in the cmd unorganized  , i even used git bash same problem , 
img showing the problem for cmd and git bash :- 
https://imgur.com/a/JQJ8V

**Comment by Mohamed-Elwan** [comment]
it's not an issue . it's all about the screen resolution.
if you zoomed out the CMD (on win10 CTRL+wheel down) every thing should be fine.

**Comment by ntzm** [comment]
Make the terminal window wider :)

**Comment by abdolrhman** [comment]
am sorry if isnot an issue i know its a naive question , but its giving me pain , i already tried all of this not working

**Comment by Dylan-DPC** [comment]
@abdolrhman what's the issue? the order in which rows are showing? or the fact that it looks like a mess?

**Comment by abdolrhman** [comment]
it looks like a mess :/

**Comment by Mohamed-Elwan** [comment]
windows cmd in general is not the perfect tool at all.you can use `cmder` and zoom it out.

**Comment by abdolrhman** [comment]
well i used git bash , but it did not fix the problem but any way , i will try it thanks , and sorry for how naive my question is .

**Comment by Dylan-DPC** [comment]
Then there is nothing the framework can do. You can close this issue.

**Comment by devcircus** [comment]
I second using cmder on windows. Very customizable. Looks great.
