### ISSUE TITLE
Pivot fillable fields ignored

### ISSUE THREAD

**Issue by KKSzymanowski** [laravel/framework#21401]
- Laravel Version: 5.5.13
- PHP Version: 7.1.1
- Database Driver & Version: MariaDB 10.1.21

### Description:
Given we have carts and products and a many-to-many relationship between them, if we attach a new product to the cart with some pivot values, the cart id can be overwritten resulting in attaching the product to the incorrect cart:

```php
$cart->products()->attach($id, ['cart_id' => 123, 'quantity' => 5]);
```

Calling the `withPivot` method on the relationship doesn't affect anything since it only influences what gets selected, if I'm not mistaken.
Creating a custom pivot with the fillable fields also doesn't change a thing, because `InteractsWithPivotTable::castAttributes` calls `forceFill` instead of `fill` on the pivot instance.

### Steps To Reproduce:

1. `git clone https://github.com/KKSzymanowski/laravel-pivot-fillable`
2. `cd laravel-pivot-fillable`
3. `cp .env.example .env`
4. Set up an empty database, MariaDB for example
5. Set the DB connection parameters in the `.env` file 
6. `composer install`
7. `phpunit`

First test should pass, second should fail.

8. Uncomment the `using` call in `app/Cart.php`
9. `phpunit`

Again, first test should pass, second should fail.

**Comment by themsaid** [comment]
@KKSzymanowski please don't share an entire laravel project. Help us look into it better by including easy to replicate steps of production.

**Comment by KKSzymanowski** [comment]
Please take a look at the last commit
https://github.com/KKSzymanowski/laravel-pivot-fillable/commit/e5428ace0b9421d3f51ac3793682413099b4ca2b
These are the exact steps to reproduce.

**Comment by themsaid** [comment]
> $cart->products()->attach($id, ['cart_id' => 123, 'quantity' => 5]);

This is wrong, don't include a `cart_id` key, this is for you to take care of :)

**Comment by KKSzymanowski** [comment]
But why this inconsistency? I can set the fillable fields on the model to protect my app from filling some unwanted fields in the database, but I cannot do that for pivots.

Is there a good reason for the `forceFill` call?

**Comment by themsaid** [comment]
I don't see this as an inconsistency, it's intended to forceFill so you don't have to handle the hassle of guarded attributes inside your pivot model, it's a special model where all attributes are supposed to be filled.

**Comment by KKSzymanowski** [comment]
@themsaid But the base Pivot defines the guarded fields as an empty array:
https://github.com/laravel/framework/blob/5.5/src/Illuminate/Database/Eloquent/Relations/Pivot.php#L37

Changing the `forceFill` to `fill` in `InteractsWithPivotTable::castAttributes` makes both tests pass and the correct data is inserted into the pivot table.

**Comment by themsaid** [comment]
@KKSzymanowski you have a point yeah, let me look into that.

**Comment by KKSzymanowski** [comment]
Thank you

**Comment by a-komarev** [comment]
Good catch, @KKSzymanowski! #21403

**Comment by KKSzymanowski** [comment]
@themsaid Thanks for the fix.
