### ISSUE TITLE
Query builder for json has errors

### ISSUE THREAD

**Issue by attlantick** [laravel/framework#21416]
- Laravel Version: 5.5.13
- PHP Version: 7.0.23
- Database Driver & Version: pg 9.5

### Description:
I dont show this on mySql but pg its IMPORTANT
https://www.postgresql.org/docs/9.6/static/functions-json.html
For example:
`$query->where('data->price_per_day',1000);`
Result: and `"data"->>'price_per_day' = '1000';`
Expected result: and `"data"->'price_per_day' = '1000';`
Next:
`$query->where('data->>price_per_day',1000);`
Result: and `"data"->>'>price_per_day' = '1000';`
Expected result: and `"data"->>'price_per_day' = '1000';`

**Comment by Dylan-DPC** [comment]
This has already been reported as a [proposal](https://github.com/laravel/internals/issues/804)
