### ISSUE TITLE
Http -> Resource attempts to json_encode Exception

### ISSUE THREAD

**Issue by joostlawerman** [laravel/framework#21423]
- Laravel Version: 5.5.3
- PHP Version: 7.0.22
- Database Driver & Version: MySQL 5.7.19

### Description:
When there is an error in the `toArray` method of the resource the resource attempts to encode the error to JSON and throws a bytes exhausted error.

### Steps To Reproduce:
A simple way to reproduce is to put an collection in a resource that is not a CollectionResoruce. It still attempts to send a request even if it should throw an error inside the resource instance.

#### UserController.php
```
public function users() {
    return (new UserResource(User::all()));
}
```

#### User.php
```
public function toArray() {
    return [
        'id' => $this-id // Should throw `['id'] does not exist on this collection instance`
    ];
}
```

**Comment by themsaid** [comment]
<img width="525" alt="screen shot 2017-09-28 at 1 15 49 pm" src="https://user-images.githubusercontent.com/4332182/30963594-4c0bc430-a44e-11e7-8f80-cd070fbf87b2.png">

It works as expected for me, maybe it's something in your project. Please try to replicate in a fresh installation and ping me if that went successfully.
