### ISSUE TITLE
VirtualAs & StoredAs has Invalid Mysql grammar for unsigned 

### ISSUE THREAD

**Issue by ipgdbali** [laravel/framework#21421]
- Laravel Version: 5.4.30
- PHP Version: 7.0
- Database Driver & Version: mysql 5.7

### Description:
Hi There,
Thank you for everyone hard work on laravel. 
I like it so much. I'm a seasional/hobbiest programmer.  
I've problem with migrations and I think it is a bug. 

These statements 
- `$table->unsignedInteger('total')->virtualAs('a + b + c');`
- `$table->integer('total')->unsigned()->virtualAs('a + b + c');`

is converted to : 
- `total int as (a + b + c) unsigned`

which is invalid mysql grammar

It should be converted to 
- `total int unsigned as (a + b + c)`

I'm hastily post my problem here. 

### Steps To Reproduce:
- make migration contains code above.
- execute `artisan migrate`

**Comment by deleugpn** [comment]
What is `virtualAs`?

**Comment by themsaid** [comment]
@deleugpn check https://themsaid.com/laravel-mysql-json-colum-fast-lookup-20160709
