### ISSUE TITLE
Button component not correctly rendered inside @if statements

### ISSUE THREAD

**Issue by JoeDawson** [laravel/framework#21424]
- Laravel Version: 5.4.27
- PHP Version: 5.6 and 7.0
- Database Driver & Version: MySQL 5.5.54

### Description:

Inside of my markdown email template, I am wrapping a button component inside of an `@if` statement.

When doing so, the button is rendering the raw HTML inside of the email and not the actual button.

### Steps To Reproduce:

```php
@component('mail::message')
# Hello, {{ $user->forename }}

{{ $email->body }}

@if($email->responsable)
    @component('mail::button', ['url' => route('responses.create', $email)])
        Submit Response
    @endcomponent
@endif
@endcomponent
```

Here's what the email is rendering...

![jednutu](https://user-images.githubusercontent.com/1009696/30917506-15fe813a-a394-11e7-96d8-a7903db4b4c7.jpg)

*But*, if I take the button component outside of the if statement as shown above, the button is correctly rendered.

Here's how it looks without the if statement...

![screen shot 2017-09-27 at 14 57 39](https://user-images.githubusercontent.com/1009696/30917666-75482bbe-a394-11e7-8fc7-c6615e64a710.jpg)

I've been searching around and asked on Larachat etc. but cannot find out why this happening.

**Comment by JoeDawson** [comment]
Seems related to #17333 but republishing mail files does not resolve my issue.

**Comment by sisve** [comment]
Just to clarify; your first image isn't the view of the source, but an image of the actual rendered content? As in; it is shown as source code, and not rendered html in your mail?

**Comment by JoeDawson** [comment]
Yes that’s correct, the actual source is the button wrapped in code and pre tags? Which is why I assume it shown in the rendered email.

**Comment by Pauly-** [comment]
Hi @JoeDawson 

I was able to recreate your issue and this worked out for me:
```
@component('mail::message')
# Hello, {{ $user->forename }}

{{ $email->body }}

@if($email->responsable)
@component('mail::button', ['url' => route('responses.create', $email)])
    Submit Response
@endcomponent
@endif
@endcomponent
```

Let me know if it worked out for you. (Notice the indentation)

**Comment by JoeDawson** [comment]
Hey @Pauly-,

That worked! I assume because my template is markdown it's parsing the indentation is a code block, rather than me trying to keep my code readable lol.

And I guess it's also nothing directly related to my if statement, just a matter of how it's indented. Regardless of the directive used.

Appreciate the help.

**Comment by Pauly-** [comment]
@JoeDawson 

Yes, I bet your assumptions are correct. 

No problem.

**Comment by themsaid** [comment]
<img width="699" alt="screen shot 2017-09-28 at 1 09 45 pm" src="https://user-images.githubusercontent.com/4332182/30963370-73d3dc74-a44d-11e7-8680-a764077b0118.png">

Don't use indentation in your markdown templates.

**Comment by farshidrezaei** [comment]
@pactode 

That's Worked. Thank You.
