### ISSUE TITLE
Route Always Resolving 404

### ISSUE THREAD

**Issue by samlittler** [laravel/framework#21428]
- Laravel Version: 5.5.13
- PHP Version: 7.1.7
- Database Driver & Version: MySQL 5.7.18

### Description:
A route doesn't seem to resolve (I'm always getting a 404).

### Steps To Reproduce:
My web.php routes file has the following route:

    Route::get('/api/v1, 'API\V1\HomeController@index');
    Route::get('/api/v1/users', 'API\V1\UsersController@index');

The first route resolves and returns an empty json response. The second does not resolve. I get a 404 (not even a 500).

**Comment by samlittler** [comment]
I should add, I've commented out the routes in api.php routes folder.

**Comment by stefanoruth** [comment]
Whats youre output of php artisan route:list?

**Comment by samlittler** [comment]
It's in the list

**Comment by stefanoruth** [comment]
Yeah but what about the api prefix group is that still active? and is it ind the list?

**Comment by jhoff** [comment]
It looks fine based on the information you've provided ( which includes a syntax error, so I'm assuming it isn't your actual code ). Something this basic would have broken the framework unit tests, so without more context, I don't think anyone can help you.

**Comment by jhoff** [comment]
Also, this should be closed as it's better suited for a forum post.

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
