### ISSUE TITLE
Eloquent Resource resolve() iterate over nested resources.

### ISSUE THREAD

**Issue by tobz-nz** [laravel/framework#21433]
- Laravel Version: 5.5.7
- PHP Version: 7.1.8
- Database Driver & Version:

### Description:
Manually resolve an Eloquent Resource should (in my opinion) resolve any other resources defined in the returned array.

Should be:
`(new UserResource($user))->resolve() == ['profile' => [...]]`

Not 

`(new UserResource($user))->resolve() == ['profile' => UserProfileResource {...}]`

### Steps To Reproduce:
Set a relation as an attribute in a resource then resolve that resource, should result in a nested array.
Current results in an array with an instance of the related resource.
eg:

```
class UserResource extends Resource
{
    public function toArray($request)
    {
        return [
            'profile' => new UserProfileResource($this->whenLoaded('profile')),
        ];
    }
}
```

```
dd(new UserResource($user)->resolve());
```

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
