### ISSUE TITLE
Laravel Container Why should we rely on illuminate/contracts

### ISSUE THREAD

**Issue by godruoyi** [laravel/framework#21435]
- laravel 5.5

`laravel container` is very easy to use, But why should we depend on `illuminate/contracts`, Sometimes I do not want to use `illuminate/contracts`  because it's too big

- Auth
- Broadcasting
- Bus
- Cache
- Config
........(total 27 compontent interface)

**Comment by ConnorVG** [comment]
There are many options, I have a few for you:
1) Don't use Laravel's container component, use a different one (there are many designed to be used separately), [see here](https://github.com/ziadoz/awesome-php#dependency-injection);
2) Stop complaining about a few files; a lot of packages don't even properly define their `.gitattributes` so you likely have hundreds (if not thousands) of extra files in your vendor folder already (such as tests, `.editorconfig`s etc);
3) Continue on your bandwagon against `illuminate/contracts` even though it *clearly* is designed to encompass the entirety of `Illuminate` and not just a singular component (don't be this guy).

**Comment by godruoyi** [comment]
tks
