### ISSUE TITLE
PHP Parse error:  syntax error, unexpected ')' in /var/www/vhosts/yourelitesystems.eu/beta.yourelitesystems.eu/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 233

### ISSUE THREAD

**Issue by HobbyScripter** [laravel/framework#21443]
- Laravel Version: 5.5.#
- PHP Version: Plesk Onyx php 7.0
- Database Driver & Version: mariadb/mysql 10.5

### Description:
Upgraded to Laravel 5.5 being to upgrade progress to optimize autoloader sends error:
PHP Parse error:  syntax error, unexpected ')' in /var/www/vhosts/yourelitesystems.eu/beta.yourelitesystems.eu/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 233

### Steps To Reproduce:
When upgrading the app to Laravel 5.5, this happened

sorry for my english

**Comment by m1guelpf** [comment]
https://github.com/laravel/framework/blob/64894d378f9b5a6af31e4e0a715ec67972876860/src/Illuminate/Foundation/helpers.php#L233

**Comment by themsaid** [comment]
Make sure you're running the correct php-fpm version
