### ISSUE TITLE
[5.5] $request->has(key) returns true when key exists while value is null

### ISSUE THREAD

**Issue by mm-x** [laravel/framework#21444]
- Laravel Version: 5.5.#
- PHP Version: 7.1
- Database Driver & Version: mysql

### Description:
The method "has" from Illuminate\Http\Request now returns true when the key is present and null. Initial behavior (on 5.4 and before) would be even if the key is present in the request, if the value is null, $request->has(key) would return false.

### Steps To Reproduce:
$request->offsetSet('slug', null);
$request->has('slug'); // expect false, returns true

**Comment by themsaid** [comment]
Yeah it's mentioned in the upgrade guide: https://laravel.com/docs/5.5/upgrade

**Comment by devcircus** [comment]
```$request->filled('slug');```
