### ISSUE TITLE
Auto Generated Index Names Too Long

### ISSUE THREAD

**Issue by benyanke** [laravel/framework#21446]
The following function, `Illuminate\Database\Schema\Blueprint::createIndexName()`, given longer table inputs, will generate an index name that is quite long, and has no error checking to ensure that the index name isn't too long.

```php
 protected function createIndexName($type, array $columns)
    {
        $index = strtolower($this->table.'_'.implode('_', $columns).'_'.$type);
        return str_replace(['-', '.'], '_', $index);
    }
```
[link](https://github.com/laravel/framework/blob/d4169a50d88048560ca9f418dad02a05ea67ecfb/src/Illuminate/Database/Schema/Blueprint.php#L1121)

In my brief research, MySQL limits to 64 [in most cases](https://dev.mysql.com/doc/refman/5.7/en/identifiers.html), [MSSQL limits to 128](https://stackoverflow.com/a/19296947/5374301), [PostgreSQL is 63](https://til.hashrocket.com/posts/8f87c65a0a-postgresqls-max-identifier-length-is-63-bytes), and SQLITE [seems to be 63](https://github.com/comfy/comfortable-mexican-sofa/issues/304) (though I'm having trouble finding a better reference for that).

There seems to be no good reason for autogenerated names to be breaking queries. The entire point of an autogenerated name is to make life easier for the developer, not worrying about minor things like index names.

I'd like to propose a check against the index name to get the character limits, and limit to a reasonable limit, such as 62 chars, which would make it compatible with all these databases. Additional logic could be provided to ensure that autogenerated names never go above 62 chars. Perhaps even a simple implementation could be a random string.

Thoughts?

**Comment by themsaid** [comment]
Yeah you can override the auto generated name if it's too long and select a proper name.

**Comment by benyanke** [comment]
Yes, you can override it, at which point the responsibility is yours to ensure it fits. But why would we willingly generate strings we know won't work? 

In the case of an index name which is short enough, it won't change a thing. In the case of an index name which is too long, it'll handle things behind the scenes so the dev doesn't need to worry, which is the entire point of using a framework like Laravel.

**Comment by themsaid** [comment]
Trimming the name to a limit could generate very vague names, that's why we let the develop define the shortcut he understands in case the auto generated name is too long.

**Comment by benyanke** [comment]
surely though, since indexes are never referenced in sql queries, it's not the biggest deal if they aren't perfectly named....

If I wanted everything in my database to be perfectly named, I'd either manually specify a name, or write my queries by hand.

**Comment by themsaid** [comment]
Well you could submit a proposal to https://github.com/laravel/internals, that's where we keep suggestion and discussions. I see your point, but it's a major breaking change since all keys created with this method will be impossible to drop after the change since the generated name will be different.
