### ISSUE TITLE
Relation::morphMap incorrectly merges maps with integer keys

### ISSUE THREAD

**Issue by victordzmr** [laravel/framework#21457]
- Laravel Version: 5.5.13
- PHP Version: 7.0.24
- Database Driver & Version: MySQL 5.6.37

### Description:

When using integer custom polymorphic types, [Relation::morphMap](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Database/Eloquent/Relations/Relation.php#L318) does not merge them properly because it uses `array_merge()`, which treats keys differently depending on their type:

> If the input arrays have the same string keys, then the later value for that key will overwrite the previous one. **If**, however, **the arrays contain numeric keys, the later value will not overwrite the original value, but will be appended**. [PHP Documentation](http://php.net/manual/en/function.array-merge.php).

This difference in behavior may be a problem in some cases. I'll give an example to reproduce the problem.

Before continuing I would like to clarify that I am aware that it would be more appropriate to use string keys and the `enum` type, but I can not make changes to the project model, 🤷‍♂️.

### Steps To Reproduce:

Imagine you have the following morph map:

```php
// Note that there's no key 0 or 3
$morphMap = [
    1 => Post::class,
    2 => Image::class,
    4 => Video::class,
];
```

Now, if you call to `Relation::morphMap($morphMap)`, the value of `Relation::$morphMap` would be the following:

```php
array(3){
    1 => Post::class,
    2 => Image::class,
    4 => Video::class,
}
```

But if you try to set the morph map again with new values, as it makes no sense removing the old ones before merging them, `array_merge` will merge them like this:

```php
Relation::morphMap([
    1 => Post::class,
    2 => Image::class,
    4 => Video::class,
    5 => Poll::class,
]);
```

```php
array(7){
    0 => Post::class,
    1 => Image::class,
    2 => Video::class,
    3 => Post::class,
    4 => Image::class,
    5 => Video::class,
    6 => Poll::class,
}
```

I think the expected behavior should be the following:

```php
array(4){
    1 => Post::class,
    2 => Image::class,
    4 => Video::class,
    5 => Poll::class,
}
```

### Proposed solution

Since a morph map is an associative array rather than a sequential one, I propose to modify the implementation of `Relation::morphMap` as follows:

```php
public static function morphMap(array $map = null, $merge = true)
{
    $map = static::buildMorphMapFromModels($map);

    if (is_array($map)) {
        static::$morphMap = $merge && static::$morphMap
            ? $map + static::$morphMap : $map;
    }

    return static::$morphMap;
}
```

By using the [array "+" operator](http://php.net/manual/en/language.operators.array.php) there can not be duplicate values. Note that the `$map` parameter is the left-hand value of the operation so that it is possible to replace values by calling again to `Relation::morphMap`.

**Comment by hakuno** [comment]
@victordzmr  Great!
