### ISSUE TITLE
Encapsulation in Eloquent

### ISSUE THREAD

**Issue by LuCavallin** [laravel/framework#21462]
Hello,
is it possible and do you think it would make sense to enable encapsulation in Eloquent models?
I believe this is good for abstraction, public properties seem too loose in certain situations and when depending on a class, I cannot make sure that an instance of that class will have certain properties.

```
class UserTransformer {
    public function transform(User $user) {
        return ['name' => $user->name]; // what if I want to depend on an interface instead, or if the name of the property changes, will have to change it everywhere?
    }
}
```

```
class UserTransformer {
    public function transform(UserInterface $user) {
        return ['name' => $user->getName()]; // doesn't really matter what $user is
    }
}
```

Maybe this is not a very clever idea, but I'd like to hear your opinion.

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. This isn't a bug so you can open a proposal in the laravel/internals repo

**Comment by LuCavallin** [comment]
Alright, didn't know, thanks
