### ISSUE TITLE
Resource Creation and belongsTo Relations

### ISSUE THREAD

**Issue by ragingdave** [laravel/framework#21463]
- Laravel Version: 5.5.13
- PHP Version: 7.1
- Database Driver & Version: MySQL (MariaDB 10.2)

### Description:
For example:
User Model:
id
employee_id
...
relationship to Employee via belongsTo

Employee Model:
id
....

if I don't load the employee relation via eager or otherwise, I would expect that the employee key would be blank in this example Resource:

public function toArray($request)
{
...
'employee' => new EmployeeResource($this->whenLoaded('employee')),
...
}

However the EmployeeResource proceeds to try and process the employee resource as if it was there and had properties. This is even after double checking that (and other "whenLoaded" relations) in the toArray method and it comes back with the MissingValue exception.

### Steps To Reproduce:
Outline the models as shown above (or really any belongsTo) and include it as a sub-resource. The sub-resource will error out saying properties don't exist on MissingValue.

**Comment by themsaid** [comment]
Please share complete stack trace of the error as well as the way you include the resource in your controller.

**Comment by ragingdave** [comment]
With regard to specific implementation:
`
// LoginController
// So this comes from a customer UserProvider, but the end result is that an App\User instance is passed to the Resources/User class.
protected function authenticated(Request $request, $user)
{
    $response = with (new UserResource($user))->toArray($request)
    return response()->json($response);
}

// Resources/User
public function toArray($request)
{
    return [
        'id' => $this->id,
        'employee' => new EmployeeResource($this->whenLoaded('employee'))
    ];
}
`

StackTrace: 
<pre>
local.ERROR: Call to undefined method Illuminate\Http\Resources\MissingValue::toArray() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method Illuminate
\\Http\\Resources\\MissingValue::toArray() at /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/Resource.php:195)                                                                                
[stacktrace]                                                                                                                                                                                                                                 
#0 /var/www/html/app-L55/app/Http/Resources/Employee.php(17): Illuminate\\Http\\Resources\\Json\\Resource->toArray(Object(Illuminate\\Http\\Request))                                                                            
#1 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/Resource.php(112): App\\Http\\Resources\\Employee->toArray(Object(Illuminate\\Http\\Request))                                               
#2 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/Resource.php(378): Illuminate\\Http\\Resources\\Json\\Resource->resolve(Object(Illuminate\\Http\\Request))                                  
#3 [internal function]: Illuminate\\Http\\Resources\\Json\\Resource->jsonSerialize()                                                                                                                                                         
#4 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php(67): json_encode(Array, 0)                                                                                                                
#5 /var/www/html/app-L55/vendor/symfony/http-foundation/JsonResponse.php(50): Illuminate\\Http\\JsonResponse->setData(Array)                                                                                                     
#6 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php(27): Symfony\\Component\\HttpFoundation\\JsonResponse->__construct(Array, 200, Array)                                                     
#7 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(83): Illuminate\\Http\\JsonResponse->__construct(Array, 200, Array, 0)                                                              
#8 /var/www/html/app-L55/app/Http/Controllers/Auth/LoginController.php(63): Illuminate\\Routing\\ResponseFactory->json(Array)                                                                                                    
#9 /var/www/html/app-L55/app/Http/Controllers/Auth/LoginController.php(51): App\\Http\\Controllers\\Auth\\LoginController->authenticated(Object(Illuminate\\Http\\Request), Object(App\\User))                                   
#10 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Foundation/Auth/AuthenticatesUsers.php(43): App\\Http\\Controllers\\Auth\\LoginController->sendLoginResponse(Object(Illuminate\\Http\\Request))                
#11 [internal function]: App\\Http\\Controllers\\Auth\\LoginController->login(Object(Illuminate\\Http\\Request))                                                                                                                             
#12 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)                                                                                                 
#13 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('login', Array)                                                              
#14 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Auth\\OAuthLogin
Controller), 'login') 
#15 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()                                                                                            
#16 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Routing/Router.php(645): Illuminate\\Routing\\Route->run()                                                                                                     
#17 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))                                       
#18 /var/www/html/app-L55/app/Http/Middleware/RedirectIfAuthenticated.php(24): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))                                                  
#19 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\RedirectIfAuthenticated->handle(Object(Illuminate\\Http\\Request), Object(Closure))                         
#20 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))                                   
#21 /var/www/html/app-L55/app/Http/Middleware/DetectSource.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))                                                             
#22 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\DetectSource->handle(Object(Illuminate\\Http\\Request), Object(Closure))                                    
#23 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))                                   
#24 /var/www/html/app-L55/vendor/barryvdh/laravel-cors/src/HandleCors.php(59): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))                                                  
#25 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Barryvdh\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))                                             
#26 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))                                   
#27 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))                
#28 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))                    
#29 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))                                   
#30 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))                  
#31 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure), 60, '1')             
#32 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))                                   
#33 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))                                   
#34 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Routing/Router.php(647): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))                                                                                 
#35 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Routing/Router.php(622): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))               
#36 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Routing/Router.php(588): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))                          
#37 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Routing/Router.php(577): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))                                                       
#38 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))                                                      
#39 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))                     
#40 /var/www/html/app-L55/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))                                                      
#41 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))                                         
#42 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))                                   
#43 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))         
#44 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))            
#45 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))                                   
#46 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))         
#47 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))            
#48 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))                                   
#49 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))          
#50 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))             
#51 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))                                   
#52 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))   
#53 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))      
#54 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))                                   
#55 /var/www/html/app-L55/vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/ClockworkMiddleware.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))                     
#56 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Clockwork\\Support\\Laravel\\ClockworkMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))                       
#57 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))                                   
#58 /var/www/html/app-L55/vendor/barryvdh/laravel-cors/src/HandlePreflight.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))                                             
#59 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Barryvdh\\Cors\\HandlePreflight->handle(Object(Illuminate\\Http\\Request), Object(Closure))                                        
#60 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))                                   
#61 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))                                   
#62 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))                                                                         
#63 /var/www/html/app-L55/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))                             
#64 /var/www/html/app-L55/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))                                                                                                  
#65 {main}                                                                                                                                                                                                                                   
"}
</pre>

**Comment by devcircus** [comment]
Just tried using both directions of the relationship on a fresh install and everything worked as expected. See implementation below:

```php
//UserResource

public function toArray($request)
{
    return [
        'uuid' => $this->uuid,
        'name' => $this->name,
        'email' => $this->email,
        'profile' => new ProfileResource($this->whenLoaded('profile')),
    ];
}
```
```php
//ProfileResource

public function toArray($request)
{
    return [
        'website' => $this->website,
        'about' => $this->about,
    ];
}
```
```php
// routes/web.php

Route::get('/test', function(Request $request) {
    $user = App\Models\User::find(6);
    $user->load('profile');

    return new App\Http\Resources\Users\UserResource($user);
    // also tested:
    // $resource =  new App\Http\Resources\Users\UserResource($user);
    // return response()->json($resource, 200);
});
```
A second test was done with the call to ```$user->load('profile');``` commented out and the resource was returned without the profile.
In the third and fourth versions of the test, I used the other direction of the relationship. Finding the profile first then optionally loading the associated user.
All tests succeeded as expected.

The relationships are defined as:
```php
// User.php

    public function profile()
    {
        return $this->hasOne(Profile::class);
    }
```
```php
// Profile.php

    public function user()
    {
        return $this->belongsTo(User::class);
    }
```

**Comment by ragingdave** [comment]
So in doing some more testing of my own, It's my call to `toArray` that seems to be causing an issue.
If I remove that, things work as expected. I was using that as a way to add additional properties to the response (token generated from passport) for the login response only. Perhaps this indicates the filtering done as part of response generation is not being utilized in the toArray logic flow?

**Comment by evgeniy-n** [comment]
@ragingdave Just use `response()` method.
`toArray()` - by default, just convert model to an array, or return array defined by your implementation.
Look at `\Illuminate\Http\Resources\Json\Resource@response()` in chain it call your `toArray` and wrap complete response with data provided by `with()` and `additional()` methods if they was used.

**Comment by themsaid** [comment]
Closing for being unable to replicate.
