### ISSUE TITLE
app('#facade') point to wrong class

### ISSUE THREAD

**Issue by kocoten1992** [laravel/framework#21469]
- Laravel Version: 5.5

What happen:

```php
app('artisan'); //Illuminate\Support\Facades\Artisan
```

Expected:

```php
app('artisan'); //Illuminate\Contracts\Console\Kernel
```

There are many more, I just point out one.

Reference: https://laravel.com/docs/5.5/facades#facade-class-reference

**Comment by Dylan-DPC** [comment]
This is not a bug since the underlying class of the Artisan facade actually implements the Kernel Contract.

**Comment by devcircus** [comment]
This is correct. The Kernel class is 'proxied' through the Artisan facade. The same is true for all other 'facades' in Laravel. In your tinker console, try:
```php
app('artisan')::all();
```
This is the same as 
```php
Illuminate\Support\Facades\Artisan::all();
```
or
```php
Artisan::all();
```
or 
```php
$kernel = app('Illuminate\Contracts\Console\Kernel');
$kernel->all();
```
or
```php
$kernel = app('Illuminate\Foundation\Console\Kernel');
$kernel->all();
```

**Comment by kocoten1992** [comment]
I don't get it, example:

if ```app('artisan')``` point to ```Illuminate\Support\Facades\Artisan```
with the same logic, ```app('auth')``` should point to ```Illuminate\Support\Facades\Auth::class```

But reality:
```php
app('auth'); //Illuminate\Auth\AuthManager
```

**Comment by themsaid** [comment]
`app('artisan')` doesn't exist, the docs are not correct on this.

`app('cache')` points to the Cache Store
`app('Cache')` points to the facade

**Comment by devcircus** [comment]
interesting. it gets picked up somehow.
