### ISSUE TITLE
issue with withCount method

### ISSUE THREAD

**Issue by shwhl** [laravel/framework#21464]
- Laravel Version: 5.*
- PHP Version: not related
- Database Driver & Version: not related

### Description:
There is an issue with `withCount` since it re-assign Query Builder `columns` property by `select()` but didn't clean select bindings, it cause the final SQL binding mismatch.

### Steps To Reproduce:
This issue is originally found in [here](https://stackoverflow.com/questions/46487676/laravel-withcount-on-two-models-including-constraints-and-global-scope-leads-to)

As a note:
1. there is one SQL `select "bookings".*, (select count(*) from "extras" where "bookings"."id" = "extras"."booking_id" and "app_id" = ?) as "extras_count" from "bookings"  ` , and after that, this same builder instance changed to `select count(*) as "booking_count" from "bookings"  ` but binding is kept.
2. the final SQL have this binding: `[1,"open"]` but it only have one `?` in SQL, so it replace at wrong place.

### Fix
See #21465 

### Extra
during the debugging, i found `getRelationExistenceCountQuery()` and `getRelationExistenceQuery()` in `Illuminate\Database\Eloquent\Relations\Relation` class are not using `$parentQuery` any more, should we remove this parameter in 5.6?

**Comment by themsaid** [comment]
Please share enough steps of reproduction, how can I reproduce this faulty query using Eloquent code?

**Comment by shwhl** [comment]
@themsaid Hi, the steps to reproduce is very clear in that post, basically need to have 3 models, first model has many second model, second model has many third model. Second model have protected property $withCount of third model. Third model have a global scope. Using first model Model::withCount method with a function have where query will cause the problem. You can reproduce the error easily just using the code in that post

**Comment by themsaid** [comment]
Check https://github.com/laravel/framework/pull/21468

**Comment by shwhl** [comment]
i think that doesn't fix fully, I opened another issue #21472 for more explanation
