### ISSUE TITLE
Validator "date_format"

### ISSUE THREAD

**Issue by randrienko** [laravel/framework#21467]
- Laravel Version: 5.4.33
- PHP Version: 5.6
- Database Driver & Version: -

### Description:
Failed validation in 'date_format' validator if format of date set without day

### Steps To Reproduce:

$validator = Validator::make($request->all(), [ 
    'cardExpiry' => 'required|date_format:m / Y|after_or_equal:+0 month'
]);

01 / 2018 Valid
02 / 2018 NOT VALID
03 / 2018 Valid
04 / 2018 Valid

Not valid results returns in all Februaries of not leap years.

**Comment by themsaid** [comment]
This was fixed in 5.5, 5.4 is not supported anymore. Please upgrade.
