### ISSUE TITLE
Storage url() is not updated with new S3 link

### ISSUE THREAD

**Issue by asivaneswaran** [laravel/framework#21466]
- Laravel Version: 5.5.§§
- PHP Version: 7.1
- Database Driver & Version: MYSQL

### Description:
The `Storage::url()` for s3 files are not correct. This is the url it is trying to get file is:
`https://bucket-name.s3.amazonaws.com` but if I check the link of the file directly in AWS, this is the url:
`https://s3.amazonaws.com/bucket-name`

### Steps To Reproduce:
1. Upload a file to S3
2. Check the URL from AWS and what `Storage::url()` returns

**Comment by bonzai** [comment]
http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html#access-bucket-intro

> Amazon S3 supports both virtual-hosted–style and path-style URLs to access a bucket.
