### ISSUE TITLE
Throttle not working if cache driver is set to memcached

### ISSUE THREAD

**Issue by tavicu** [laravel/framework#21475]
- Laravel Version: 5.5.13
- PHP Version: 7.1.9
- Database Driver & Version: mysql
- Env: local

### Description:

If you set the cache driver to memcached the throttle stop working.

### Steps To Reproduce:

Set CACHE_DRIVER=memcached in .env

### Memcached settings

memcached support | enabled
Version | 3.0.3
libmemcached version | 1.0.18
SASL support | yes
Session support | yes
igbinary support | no
json support | no
msgpack support | no

**Comment by themsaid** [comment]
>  stop working
how?

**Comment by tavicu** [comment]
You can try login multiple times without an error. :)

**Comment by tavicu** [comment]
My fault. First time working with memcached. Apparently the installation is not enough. You also need to start it :)

I did not know that. Added to launchagents and now it's working.

For other Mac users with this problem: https://mark.shropshires.net/blog/setting-memcached-mac-local-drupal-development
