### ISSUE TITLE
Potentially wrong IDE type hint in Route facade

### ISSUE THREAD

**Issue by SeinopSys** [laravel/framework#21489]
I've noticed that in [src/Illuminate/Support/Facades/Route.php on line 24](https://github.com/laravel/framework/blob/00fce7ee8d96c074a3b91396fa5f4b0e6bbbb12c/src/Illuminate/Support/Facades/Route.php#L24) there's a `static` keyword missing, which causes my IDE to give me an error:

>![](https://user-images.githubusercontent.com/3200580/31058105-5b6a98c8-a6ee-11e7-9f1c-866fe520fb63.png)

Is this intentional?

**Comment by Dylan-DPC** [comment]
Yes this is intentional. You can look at https://github.com/barryvdh/laravel-ide-helper. Also next time use the forums or the slack channel as this repo is for bug tracking.

**Comment by SeinopSys** [comment]
Noted, sorry.
