### ISSUE TITLE
While   `  public static $snakeAttributes = false;` on the model, yet `User::whereFooBar()` looks for `foo_bar` column instead of `fooBar`. 

### ISSUE THREAD

**Issue by salarmehr** [laravel/framework#21492]
- Laravel Version: 5.3.13, 5.5.*
- PHP Version: 7.1
- Database Driver & Version:

### Description:
While   `  public static $snakeAttributes = false;` on the model,  `User::whereFooBar()` looks for `foo_bar` column instead of `fooBar`.

**Comment by KKSzymanowski** [comment]
This is also the case for Laravel 5.5

**Comment by sisve** [comment]
This sounds like a breaking change of a behavior that has been consistent for over a year.

**Comment by salarmehr** [comment]
Unfortunately there are some other places that does not respect to `$snakeAttributes` as well. 
e.g.` \Illuminate\Database\Schema\Blueprint::rememberToken` and all similar framework generated columns. 

I hope to see consistency in the future versions as most of the programmer I know use camelCase column names for higher code maintainability.

**Comment by ChristopheB** [comment]
The only purpose of `snakeAttributes` is: [`Indicates whether attributes are snake cased on arrays`](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L67), which means shall we enforce snake casing on attributes while converting to array, or let them as is?

Coding in Laravel with camel cased attributes is not the easiest road, but it's still quite feasible. You can use the [CamelCasing trait from kirkbushell's eloquence](https://github.com/kirkbushell/eloquence), or directly set camel cased columns in your database (though you'll have to override the dynamic where, and just a few other things).

As for the generated columns in Schema issued by methods like `morphs`, `rememberToken` or `timestamps`, they use the snake case convention, and it's fine like this. They are just helpers for our convenience. Don't use them if you don't follow the snake case convention.

Anyway I agree, it would be interesting if Laravel could handle that stuff a bit more.

**Comment by salarmehr** [comment]
@chrispecoraro Thanks for commenting.  Not sure what was the purpose of your comment anyway.

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo. we can't apply this change since it's a huge breaking change and would break apps, moving the discussion to internals will help us look into it with the next 5.6 release.

**Comment by salarmehr** [comment]
@sisve Can you please provide an example of the breaking thing?

**Comment by sisve** [comment]
@salarmehr Sure. `User::whereFooBar()` would start looking for fooBar instead of foo_bar, breaking it for everyone that has the foo_bar column. Just as the issue says.

**Comment by salarmehr** [comment]
@siseve I wonder if you have read to issue description?
its all about  $snakeAttributes vale

**Comment by sisve** [comment]
Yes, I have read it. You want to change the column name that `->whereFooBar(...)` looks for when having $snakeAttributes = false. You also mention other places where the $snakeAttributes isn't taken into consideration. Changing this now will break the code for those that have already adapted to the currnet behavior; which means it is a breaking change.

**Comment by amcsi** [comment]
+1

In OP's example, `User::whereFooBar()` should look for `fooBar` instead of `foo_bar `. What we have now simply is if a model has `public static $snakeAttributes = false;` on it, then multi-word attributes referenced in dynamic where simply don't work, because they would refer to column names which don't exist in the DB.

I've even created an issue and pull request in barryvdh/laravel-ide-helper#1166 to make sure _it_ doesn't generate magic where docblocks for multi-word column names, because they simply don't work in Laravel.
