### ISSUE TITLE
PostgresBuilder getColumnType not use schema

### ISSUE THREAD

**Issue by flolivaud** [laravel/framework#21498]
- Laravel Version: 5.5.*
- PHP Version: 7.1
- Database Driver & Version:

### Description:
The `PostgresBuilder@getColumnType` method should use schema in connection just like the getColumnListing` method actually does.

**Comment by sisve** [comment]
I can't find the method mentioned, there's no getColumnType in PostgresBuilder. What method are you talking about?

Ref: https://github.com/laravel/framework/blob/5.5/src/Illuminate/Database/Schema/PostgresBuilder.php

**Comment by flolivaud** [comment]
@sisve sorry my bad. It's an inherited method from Builder.php, and need to be override in PostgresBuilder.php ...

**Comment by themsaid** [comment]
@flolivaud feel free to open a PR, let me know if I can help :)

**Comment by flolivaud** [comment]
@themsaid I'll try to do it asap, why did you close this issue?!
