### ISSUE TITLE
Split QueueManager and Application

### ISSUE THREAD

**Issue by fr05t1k** [laravel/framework#21494]
- Laravel Version: 5.5.*

### Description:
I'm using `illuminate/queue` in my project and I have to use a whole `\Illuminate\Foundation\Application` for 
`Illuminate\Queue\QueueManager`.
What would you think if we split `QueueManager` and `Application`? There only one feature which related to `Application`. Do not start a worker if the app is down for maintenance.

### Steps To Reproduce:

- [ ] We should use `Illuminate\Container` instead of `Application`. 
- [ ] Create another worker (MaintainableWorker and MaintainableQueueManager) which support this feature.

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. This isn't a bug so you can open a proposal in the laravel/internals repo

**Comment by fr05t1k** [comment]
Ok, thanks @Dylan-DPC
