### ISSUE TITLE
inject request class not working in laravel 5.5

### ISSUE THREAD

**Issue by gasner** [laravel/framework#21504]
- Laravel Version: 5.5.13
- PHP Version:7
- Database Driver & Version: mysql

### Description:
I create my "Request class" with make:request. 
`public function store(StoreUserPost $request)`

and the injection work fine in 5.4.
but when i upgrade to 5.5. the route not found.
I cameback to 5.4 and it's work.

**Comment by Dylan-DPC** [comment]
Is there something we don't know about your implementation of form requests? Cause I am using them on another project and things work fine

**Comment by devcircus** [comment]
Can you give more details? Is there an exception? Since "route not found",  can you show the route that is causing problems?

**Comment by themsaid** [comment]
`the route not found` that doesn't seem to be related to FormRequests, issue is vague, please include more details.

**Comment by gasner** [comment]
Nothing special.
I get "http exception" without message.
`
namespace App\Http\Requests;
use Illuminate\Foundation\Http\FormRequest;

class StoreUserPost extends FormRequest
{
	/**
	 * Determine if the user is authorized to make this request.
	 *
	 * @return bool
	 */
	public function authorize()
	{
		return true;
	}

	/**
	 * Get the validation rules that apply to the request.
	 *
	 * @return array
	 */
	public function rules()
	{
		return [
			'name' => 'required',
			'last_name' => 'required',
			'tz' => 'required',
			'password' => 'required',
			'email' => 'required|unique:users|max:255|email'
		];
	}

	public function response(array $errors)
	{
		return response()->json($errors, 400);
	}

}`



`<?php

namespace App\Http\Controllers\Api;

use App\Http\Requests\StoreUserPost;
use App\Training;
use App\User;
use App\UserProgram;
use App\UserSettings;
use Auth;
use Illuminate\Http\Request;
use Log;
use function json_encode;
use function public_path;

class UserController extends Controller
{

	public function store(StoreUserPost $request)
[...]
}
`

in web.php
Route::post('users', 'Api\UserController@store');

in php 5.4 it work

**Comment by haakym** [comment]
Can you check your error log after triggering the error and share the contents of the error here. You can find the error in `storage/logs/laravel.log`.

**Comment by devcircus** [comment]
Possibly because 5.5 handles customizing responses in form requests differently. See the upgrade guide :

> A Note On Form Requests

> If you were customizing the response format of an individual form request, you should now override the failedValidation method of that form request, and throw an HttpResponseException instance containing your custom response

**Comment by jeanlucnguyen** [comment]
Just for info, I had the exact same problem, I was overwriting the response() method in the Form Request. So you what you need to do is rename your response() method to failedValidation(Validator $validator) and don't forget to also add 'use Illuminate\Contracts\Validation\Validator;' at the top of your Form Request file
