### ISSUE TITLE
Resource creation with additional top level metadata when wrapping is disabled

### ISSUE THREAD

**Issue by ragingdave** [laravel/framework#21503]
- Laravel Version: 5.5.13
- PHP Version: 7.1
- Database Driver & Version: MySQL (MariaDB 10.2)

### Description:
As described in the docs, I wanted to have the resource responses not wrapped in a data index at least initially; called Resource::withoutWrapping() in AppServiceProvider and responses no longer had data as a top-level key. However, upon calling `additional(['test' => 'value'])` on a Resource, causes the data key to be added back in. Is this expected, as it seems to ignore the setting of withoutWrapping.

### Steps To Reproduce:
Create a new resource with any set of properties, disable wrapping via AppServiceProvider and then return an instance of that resource with and without additional top-level data.

### Expected ?
The expected scenario would be that for example a user resource would return like:
```
{ "id": 1, "name": "John", "test": "value"}
```
But instead the result is:
```
{ "data": { "id": 1, "name": "John"}, "test": "value"}
```

**Comment by devcircus** [comment]
It's my understanding that meta data is a separate concern from the returned data. It seems the only way to correctly separate it is to wrap the data. There are other ways to just add keys to the data if that's what you need.

**Comment by themsaid** [comment]
Yes that's how it should work.
