### ISSUE TITLE
Infinite loop toArray()

### ISSUE THREAD

**Issue by vrubiella** [laravel/framework#21506]
- Laravel Version: 5.4.36
- PHP Version: 7

### Description:
When serializes model to json with relation who acces to parent property, infinite loop bug occurs.

### Steps To Reproduce:
```php
class Product {
 protected appends ['masterApp']

 public function getMasterAppAttribute {
  return $this->apps()->master()->first(); //return one App instance
 }
}

clas App {
 protected appends ['subdomain']

public function product()
{
    return $this->belongsTo(Product::class);
}

 public function getSubdomainAttribute()
 {
  return 'sub'.$this->product->id;
 }
}

php artisan tinker

just create Product and App isntances and: $p->toArray(). fails on infinite loop.

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.

**Comment by vrubiella** [comment]
@themsaid this is not a bug??

**Comment by themsaid** [comment]
Yeah it's not, you're causing the recursive behaviour in your code, a product is showing an App, which is loading a product while building the mutator, while displaying the product inside the app an app is supposed to be serialized, and hence the loop.

**Comment by vrubiella** [comment]
Maybe I'm wrong, but I'm not serializing product when getSubdomainAttribute(), I'm just retrieving object property, but ok... i will open discussion on laracats... thanks.
