### ISSUE TITLE
Display full error info in terminal?

### ISSUE THREAD

**Issue by believer-ufa** [laravel/framework#21508]
Laravel Version: 5.5.13

In current Laravel framework, if we get error in Terminal window, we see only short message without stack trace and other additional information.

For this reason I have to constantly open the log file in order to find the complete information about the last error.

Maybe make sense to give full error information right in the terminal window?

**Comment by believer-ufa** [comment]
Found a simple solution. To achieve this, you can add a new method `renderForConsole` in your ExceptionHandler class:

```php
use Symfony\Component\Console\Application as ConsoleApplication;
use Symfony\Component\Console\Output\ConsoleOutput;
use Symfony\Component\Console\Output\OutputInterface;
// ...

class Handler extends ExceptionHandler
{

    // other methods...

    /**
     * Render an exception to the console.
     *
     * @param  OutputInterface  $output
     * @param  \Exception  $e
     * @return void
     */
    public function renderForConsole($output, Exception $e)
    {
        $output = new ConsoleOutput(ConsoleOutput::VERBOSITY_VERBOSE);

        (new ConsoleApplication)->renderException($e, $output);
    }
}
```

Now terminal displays full information about error. Thanks for this beautiful framework)

**Comment by decadence** [comment]
php artisan command -vvv

**Comment by believer-ufa** [comment]
@decadence ithanks, but it is not working for me, checked now.

**Comment by Dylan-DPC** [comment]
This is not a bug. You can close tthe issue
