### ISSUE TITLE
Route::fallback overwrites previous Route::fallback, etc

### ISSUE THREAD

**Issue by rorc** [laravel/framework#21511]
- Laravel Version: 5.5.13

### Description:
In `web.php`:
```php
Route::fallback(function() {
    return view('errors.403');
})->name(403);

Route::fallback(function() {
    return view('errors.404');
})->name(404);

Route::fallback(function() {
    return view('errors.405');
})->name(405);

Route::fallback(function() {
    return view('errors.500');
})->name(500);
```
In `Handler.php`
```php
public function render($request, \Exception $e)
{
    if ($e instanceof NotFoundHttpException || $e instanceof ModelNotFoundException) {
        return \Route::respondWithRoute(404);
    }

    return parent::render($request, $e);
}
```
If `NotFoundHttpException` or `ModelNotFoundException` occurs, rendering last defined `Route:fallback`.
In this example its 500.

**Comment by Dylan-DPC** [comment]
How is it supposed to decide which one it needs to hit?

**Comment by rorc** [comment]
Need hit `Route::fallback` named 404, not 500.

**Comment by themsaid** [comment]
Yes you can only have one fallback per route group, it's supposed to handle only 404, so if no routes found at this segment we use the fallback, that's why you can't define multiple fallbacks.

For errors other than 404, just redirect to a regular error route, `/something-wrong` for example

**Comment by rorc** [comment]
But here in example https://themsaid.com/laravel-55-better-404-response-20170921 implies presence more than one fallback per group (serverFallback or fallback)
```php
if ($exception instanceof ModelNotFoundException) {
    return $exception->getModel() == Server::class
                ? Route::respondWithRoute('serverFallback') 
                : Route::respondWithRoute('fallback');
}
```

**Comment by themsaid** [comment]
The post might not be clear, but that server fallback would be under a `/server` prefix to differentiate it from the main fallback.

**Comment by themsaid** [comment]
thill will make any `/server/asdasd` show the server fallback automatically, the handling here show how you can use the fallback route with a ModelNotFoundException

**Comment by rorc** [comment]
Ok, thanks)

**Comment by rorc** [comment]
Btw, how i can pass variables into `respondWithRoute`?
I want to do:
```php
//web.php
Route::fallback(function($exception) {
    return view('errors.500', compact('exception'));
});

//Handler.php
public function render($request, \Exception $e)
{
    if ($e instanceof \ErrorException) {
        return \Route::respondWithRoute('fallback', $e);
    }

    return parent::render($request, $e);
}
```

**Comment by projct1** [comment]
@themsaid Dude?

**Comment by Dylan-DPC** [comment]
It is better to seek help on forms or slack channel or even Twitter

**Comment by projct1** [comment]
@Dylan-DPC I lead to making this possible. Just add opportunity pass params into `\Route::respondWithRoute` like this `\Route::respondWithRoute('fallback', $params)`.

**Comment by anususmi** [comment]
### Laravel 8 fallback route is not working,
// all other routes
Route::fallback(function() {
    return 'Hm, why did you land here somehow?';
});
Need help here, thanks in advance
