### ISSUE TITLE
I can't change CamelCase column names by migration

### ISSUE THREAD

**Issue by hanachan1026** [laravel/framework#21516]
- Laravel Version: 5.4.*
- PHP Version: 7.3
- Doctrine/DBAL Version: 2.6
### Description:
For example I have this column named 'lowerCaseColumn' in my database.
I get this error when I run migration.

```
 [Doctrine\DBAL\Schema\SchemaException]
  There is no column with name 'lowercasecolumn' on table my_table'.
```

### Steps To Reproduce:
Situation: You have columns named with CamelCase in your database.

You run migration

```
Schema::table('my_table', function (Blueprint $table) {
				$table->renameColumn('lowerCaseColumn', 'lower_case_column');
```

**Comment by themsaid** [comment]
Can't replicate, what's your database driver?

**Comment by hanachan1026** [comment]
@themsaid I use mysql.

**Comment by themsaid** [comment]
@hanachan1026 can't reproduce this using mysql.

**Comment by Dylan-DPC** [comment]
@hanachan1026 
in your migration you are doing:
`lowerCaseColumn`

In your error you are getting: 
`lowercasecolumn`

That means the error is elsewhere. You might have named the column as `lowercasecolumn` but when you are renaming it, you are telling it to rename `lowerCaseColumn` and therefore it can't find it

**Comment by hanachan1026** [comment]
@themsaid 
@Dylan-DPC Sorry, this was about the different issue, I will now close this.

**Comment by chalbert-edr** [comment]
@hanachan1026 What was the issue?

**Comment by OrestHk** [comment]
Hello,
I had the same problem using postgresql
The fix in my case : 
```
Schema::table('my_table', function (Blueprint $table) {
    $table->renameColumn('"lowerCaseColumn"', 'lower_case_column');
});
```

A bit more explanations can be found in doctrine/dbal [code](https://github.com/doctrine/dbal/blob/2e54e78a61f1c6ef5c4a226744c6ef222c2e7817/lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php#L591-L592) : 
```
            $sql[] = 'ALTER TABLE ' . $diff->getName($this)->getQuotedName($this) .
                ' RENAME COLUMN ' . $oldColumnName->getQuotedName($this) . ' TO ' . $column->getQuotedName($this);
```
And [here](https://github.com/doctrine/dbal/blob/2e54e78a61f1c6ef5c4a226744c6ef222c2e7817/lib/Doctrine/DBAL/Schema/AbstractAsset.php#L144-L148) :
```
    /**
     * Gets the quoted representation of this asset but only if it was defined with one. Otherwise
     * return the plain unquoted value as inserted.
     */
    public function getQuotedName(AbstractPlatform $platform) : string
```

This means that if you provide the column name without the double quotes, the generated query will be something like `ALTER TABLE table RENAME COLUMN lowerCaseColumn TO lower_case_column`
In postgresql all identifiers that are not double quoted are transformed tolowercase

By providing the double quotes in camelCase column names you will get a query like `ALTER TABLE table RENAME COLUMN "lowerCaseColumn" TO lower_case_column` which will take into account the camelcase part during the migration

Hope it can be of help to someone,
Have a nice day
