### ISSUE TITLE
Collection::sortBy('functionName') does not work in laravel 5.5 when items are arrayable

### ISSUE THREAD

**Issue by halaei** [laravel/framework#21515]
- Laravel Version: 5.5
- PHP Version: 7.1
### Description:
This code used to work in laravel 5.4:
```php
class M extends \Illuminate\Database\Eloquent\Model
{
    var $a;
    public function a()
    {
        return $this->a;
    }
    public function __construct($a)
    {
        parent::__construct();
        $this->a = $a;
    }
}

$a = [
    new M(1), new M(3), new M(2),
];
dd(collect($a)->sortBy('a'));
```
In 5.5, it throws an exception:
                                   
    [LogicException]                           
    M::a must return a relationship instance.

**Comment by themsaid** [comment]
Can't replicate, works fine in 5.5

**Comment by themsaid** [comment]
Looking into it again, I found a breaking change that's not documented. To fix your issue don't have a method with the same name as the property. use `getA` for example.
