### ISSUE TITLE
Fatal error when calling Storage::fake() with league/flysystem < 1.0.8

### ISSUE THREAD

**Issue by Indemnity83** [laravel/framework#21522]
- Laravel Version: 5.5.14
- PHP Version: 7.0.22
- Database Driver & Version: N/A

### Description:
The framework makes use of two constants on the league/flysystem local adapter that weren't added (in their current form) until 1.0.8 (see thephpleague/flysystem@9e2c02b) when trying to Create an instance of the local driver.

https://github.com/laravel/framework/blob/cf40b97a4e8dd4ab00f133790bd6126bba1a7574/src/Illuminate/Filesystem/FilesystemManager.php#L151-L162

This results in fatal errors being thrown when attempting to create an instance of the local driver. For example attempting to call Storage::fake() produces a `Undefined class constant 'DISALLOW_LINKS'`

**It seems the most logical solution is to bump the required version of flysystem in composer.json to 1.0.8**; but I can't figure out why the travis tests which are supposed to be pulling in the minimum versions of each package aren't already catching this. 

### Steps To Reproduce:

1. Setup a new Laravel deployment
1. Run composer install with --prefer-lowest (`composer install --prefer-lowest`)
       Note that this will pull in league/flysystem:1.0.0
1. Attempt to call fake() on the Storage facade (`Storage::fake()`)

**Comment by themsaid** [comment]
A composer update should make you good to go as it'll pull the latest release.

**Comment by tomlankhorst** [comment]
The issue exists in all branches from 5.1 on. 
Submitting PR to latest LTS... #23516
