### ISSUE TITLE
`package:discover` prints an incorrect list of packages

### ISSUE THREAD

**Issue by bram1028** [laravel/framework#21538]
- Laravel Version: 5.5.14
- PHP Version: 7.1.8
- Database Driver & Version: n/a

### Description:
If you run `package:discover` by itself, the list of packages doesn't show the correct list. The cache file does get updated.

### Steps To Reproduce:
1. Remove any entry from `bootstrap/cache/packages.php`.
2. Run `artisan package:discover` and the entry you removed won't be displayed, but it will be put back in the cache file.

**Comment by themsaid** [comment]
Can't replicate, please add more details. How can I replicate the issue in a fresh laravel installation?

**Comment by bram1028** [comment]
Exactly as described above:

```
laravel new test && cd test
vi bootstrap/cache/packages.php     - remove any entry from the array
php artisan package:discover        - said package is not listed, but the file is
                                      correctly updated
```

I discovered this because I can't use composer in production. So I copy my vendor folder and then run `package:discover` manually to update the cache file. It didn't show a package that I knew was supposed to be there.

**Comment by themsaid** [comment]
I can't replicate, everything looks good to me.

Please use the forums to seek help, looks like something is wrong in your project.

**Comment by bram1028** [comment]
I posted a message on the forum, but to clarify, this _was_ a fresh install of Laravel...

```
BradMBP:~ smithb$ laravel new discover && cd discover
Crafting application...
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
... truncated ...
Generating optimized autoload files
> @php -r "file_exists('.env') || copy('.env.example', '.env');"
> @php artisan key:generate
Application key [base64:cnezXNzcncJEp/prbNS3AQQmIpooKuvaBlz3J7hroMw=] set successfully.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: fideloper/proxy
Discovered Package: laravel/tinker
Package manifest generated successfully.
Application ready! Build something amazing.
```
Remove fideloper/proxy from the packages.php array:

```
BradMBP:discover smithb$ nano bootstrap/cache/packages.php 
BradMBP:discover smithb$ cat bootstrap/cache/packages.php 
<?php return array (
  'laravel/tinker' => 
  array (
    'providers' => 
    array (
      0 => 'Laravel\\Tinker\\TinkerServiceProvider',
    ),
  ),
);
```

Run `package:discover`:

```
BradMBP:discover smithb$ php artisan package:discover
Discovered Package: laravel/tinker
Package manifest generated successfully.
BradMBP:discover smithb$ cat bootstrap/cache/packages.php 
<?php return array (
  'fideloper/proxy' => 
  array (
    'providers' => 
    array (
      0 => 'Fideloper\\Proxy\\TrustedProxyServiceProvider',
    ),
  ),
  'laravel/tinker' => 
  array (
    'providers' => 
    array (
      0 => 'Laravel\\Tinker\\TinkerServiceProvider',
    ),
  ),
);
```

This is not exactly a practical example, but it proves my point. Any new vendors won't be displayed by  `package:discover`...

**Comment by dmason30** [comment]
@themsaid I am running into this issue now on laravel 5.6. And I am able to replicate this exactly as described above. 

1. Edit `packages.php` and remove one of the packages from the `array`. 
2. Run `package:discover` and the package you have removed WILL NOT be output as a `Discovered package` but it WILL be added back into the `packages.php`,

**Comment by bram1028** [comment]
@themsaid I'd like to revive this as the problem still exists in the latest v6. I also found another way to replicate that may make more sense:

1. Install any auto-discover package like `laravel/socialite`.
2. Then add `laravel/socialite` to the composer.json's `dont-discover` array.
3. Run `package:discover` and it will still list `laravel/socialite` even though the cache file was correctly updated.

This is purely cosmetic, but is odd to see.
