### ISSUE TITLE
Convert mysql syntax to query builder laravel

### ISSUE THREAD

**Issue by azzario** [laravel/framework#21537]
i have some problem, the problem is i can't to understand how to convert sql syntax to laravel query builder. The example : 

in my sql query : 
SELECT *, REPLACE(SenderNumber,'+62','0') AS rep FROM inbox
 
im trying to make a query builder like this: 
DB::select("SELECT *, REPLACE(SenderNumber,'+62','0') AS rep FROM inbox")

But its give me an error! maybe you can help me

**Comment by browner12** [comment]
Hi @azzario .  Thanks for your interest in Laravel!  The Github issue tracker is for bug reporting only.  There are many tools available for you to find help learning Laravel, such as the Laravel Slack channel, StackOverflow, Laracasts Forum, and Laravel.io.  I would suggest closing this issue, and asking in one of those sites.

Thanks
