### ISSUE TITLE
Run eloquent query from another local virtual host with curl or api

### ISSUE THREAD

**Issue by mostafamiri65** [laravel/framework#21533]
- Laravel Version: 5.5
- PHP Version: 7.1
- Database Driver & Version:5.7.19

### Description:
I have 2 virtual host in my wamp server under Windows 10(X64).

Virtual-host1 and Virtual-host2. virtual-host1 pointed to www/virtual1 and virtual-host2 pointed to www/virtual2

both virtual host running with Laravel 5.5.

Virtual-host1 have a configured database: virtualhost1_database Virtual-host2 does not have any database, default is: homestead

I defined a resource route in Virtual-host1: /users in the store function i use Eloquent and get user list from virtualhost1_database.

I try to get the list of users with Postman and it works fine: URL: virtual-host1/users Method: POST

Now I wanna send a Curl request from Virtual-host2 to Virtual-host1 to get the list of users.

curl_setopt_array($curl, array( CURLOPT_HEADER => true, CURLOPT_URL => \'http://virtual-host1/users\', CURLOPT_POST => 1, ));

But I have the following error: Access denied for user 'homestead'@'localhost' (using password: YES) (SQL: select * from users where active=1

That means virtual-host1 wanna get query from virtual-host2 database!

Can someone help me?

**Comment by Dylan-DPC** [comment]
I don't think this is a bug. You can seek help at the forums or the slack channel

**Comment by sisve** [comment]
Two sites on Apache on Windows requires cached configurations. It's a known but non-documented problem. Run `php artisan config:cache` on both sites.

https://github.com/laravel/framework/issues/20207
https://github.com/laravel/framework/issues/19990
https://github.com/laravel/framework/issues/19454
https://github.com/laravel/framework/issues/13906
https://github.com/laravel/framework/issues/8191
https://github.com/vlucas/phpdotenv/issues/219#issuecomment-325020817

<br>

> ONLY use env inside your config files, and then you MUST use the cache command to setup the config files. Then there are ZERO env issues in production.

https://github.com/vlucas/phpdotenv/issues/76#issuecomment-224899197

**Comment by mostafamiri65** [comment]
Thank you @sisve 
Solved 👍
