### ISSUE TITLE
Cookie\Factory::make and cookie() helper parameters missing

### ISSUE THREAD

**Issue by KKSzymanowski** [laravel/framework#21542]
- Laravel Version: 5.5.13

### Description:
`Illuminate\Cookie\CookieJar::make()` accepts the following list of parameters:
```php
$name, 
$value, 
$minutes = 0, 
$path = null, 
$domain = null, 
$secure = false, 
$httpOnly = true, 
$raw = false, 
$sameSite = null
```

`Illuminate\Contracts\Cookie\Factory::make()` and `cookie()` helper however accept only these ones:
```php
$name, 
$value, 
$minutes = 0, 
$path = null, 
$domain = null, 
$secure = false, 
$httpOnly = true
```

Is it intentional?

**Comment by Dylan-DPC** [comment]
A class doesn't have to match all the parameters from the contract it is implementing

**Comment by Dylan-DPC** [comment]
This is not a bug. A class implementing the contract can have extra methods in the signature if it wants to. Kindly close the issue

**Comment by KKSzymanowski** [comment]
I didn't say it's a bug, I opened this more like a question to the maintainers. 
The `Illuminate\Cookie\CookieJar` class is the only concrete class implementing `Illuminate\Contracts\Cookie\Factory` interface, why not then make the signatures identical? Last two parameters are optional, so it won't break backward compatibility.

Lack of these two arguments made it a little bit confusing to me, especially that the `$raw` argument is not documented. Adding them might save someone some time.

**Comment by Dylan-DPC** [comment]
Well the contract just says that it needs these many params to be there in the function. Also it is not aware whether 1 class is implementing or more than that. They could be people who have written their own implementations. Also this repo is for bug tracking. So if you want, you can put forth a proposal in laravel/internals repo

**Comment by Dylan-DPC** [comment]
I checked both the functions again. And yeah the helper should match the class. I will push another PR for 5.6 so that interface matches.

**Comment by KKSzymanowski** [comment]
Please do, if you can. I don't have my computer with me.

**Comment by Dylan-DPC** [comment]
Sure but contract change will be for 5.6
