### ISSUE TITLE
Hungarian date format cause exception

### ISSUE THREAD

**Issue by RajcsanyiZ** [laravel/framework#21543]
https://github.com/laravel/framework/blob/9f178aa29d00ccc005c8c080b42aca7f025a09e4/src/Illuminate/Database/Eloquent/Model.php#L2826

If I use Hungarian time localization format in the form, the value format is _'YYYY.MM.DD.'_. Carbon makes an exception. 

Carbon can handle this problem with this solution, but the eloquent can't do that.

```php
  // carbon handle the problem above:
  Carbon::createFromFormat('Y.m.d.', $time, $timezone);
```
I can declare setFieldAttribe and it is a common solution:
```php
  class OrderModel extends Model {
    
   protected $dates = ['deadline_at']
    
    public function setDeadlineAtAttribute($value) {
        $this->attributes['deadline_at'] = Carbon::createFromFormat('Y.m.d.', $value);
    }
  }
```

But this is not a smart way of solution, because:

config('app.locale') set the localisation, but the eloquent ignores it and this problem doesn't related with the database time format. I think the eloquent model needs a new protected variable above:
```php

abstract class Model implements ArrayAccess, Arrayable, Jsonable, JsonSerializable, QueueableEntity, UrlRoutable {

  protected $input_dateformat = "Y-m-d h:j:s" // hu: Y.m.d. h:js
}
```
My final solution is that: 
```php
    /**
     * Convert a DateTime to a storable string.
     *
     * @param  \DateTime|int  $value
     * @return string
     */
    public function fromDateTime($value) {
        if (!empty($value)) {
            if (strlen($value) == 11) {
                // YYYY.MM.DD. >> YYYY-MM-DD
                return str_replace('.', '-', substr($value, 0, 10));
            } elseif(strlen($value) == 17 or strlen($value) == 20) {
                // YYYY.MM.DD. HH:mm >> YYYY-MM-DD HH:mm / YYY.MM.DD. HH:mm:SS >> YYYY-MM-DD HH:mm:ss
                return str_replace('.', '-', substr($value, 0, 10)).substr($value, 11);
            }
        }

        $format = $this->getDateFormat();
        $value = $this->asDateTime($value);
        return $value->format($format);
    }
```
I don't know where is the problem in the eloquent exactly because I don't know enough this class hierarchy. I hope somebody can solve this "bug".

**Comment by themsaid** [comment]
Can you please submit some steps of reproduction? Share how you define the format in your model and how you set the date while storing the model? It's important that you explain a detailed steps of reproduction for us to start looking into your issue, otherwise the issue will keep hanging because nobody knows enough details to answer :)

**Comment by RajcsanyiZ** [comment]
You can reproduce the problem very easy. (database and charset is utf-8, localisation is: hu-HU, but maybe it is not important)

_Model:_
```php
namespace App;

use Carbon\Carbon;
use App\Model2;
use Illuminate\Database\Eloquent\SoftDeletes;

class MyTest extends Model
{
    protected $table = 'mytest';
    protected $fillable = ['deadline_at'];
    protected $dates = ['deadline_at'];
}
```
Controler and action:_

```php
namespace App\Http\Controllers;

use App\UserDonation;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;

class UserDonationController extends Controller {
  public function index() {
    $mytest = new MyTest();
    $mytest->deadline_at = "2017.01.01."; // or "2017.01.01. 01:01", or "2017.01.01. 01:01:01"
    $mytest->save(); // trigger an exception...
  }
}
```

**Comment by themsaid** [comment]
You haven't set the date format in your model, this is required for Eloquent to format your date properly.

**Comment by RajcsanyiZ** [comment]
I haven't changed the default date format, because I would liket to store date yyyy-mm-dd hh:ii:ss format into the database. 

The multinational site use a lot of time format, but the database only store one format.

Eloquent can't handle the hungarian time unfortunately. "YYYY.MM.DD or YYYY. MM. DD.", the carbon can handle it, but eloquent within use carbon carbon trigger en exception.

I think hungarian developer can't use eloquent, but I am maybe the first who are noticed. The others use yyyy-mm-dd format, but it is not correct our grammar. 

The other programmers use the example, that you can see bellow.

How can I help you to solve this problem?
