### ISSUE TITLE
[5.4] Exception Handler always receives Request base class instead of concrete Requests

### ISSUE THREAD

**Issue by BillyBoeklunder** [laravel/framework#21547]
### System:
- Laravel Version: 5.4
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.6.35

### Description:
Hello everybody,
please have in mind that this is my first ever issue post on any open source project. Please give me a kind hint if I missed something or you need more information. Please have also in mind that I'm not a native speaker so my sentences can look a bit weird sometimes.

#### General information
- In our exception handler class we have overwritten the render()-method like it's common practice.

- Our Controller forces the usage of a custom FormRequest by type hinting it on the actions signature. 

- When the Authorization in this requests fails, an AuthorizationException is thrown (default behaviour since 5.4)

#### Problem
In the render()-method there are two attributes given, the request and the exception. Now we would have suggested that this particular request object is the concrete request object like resolved in the first place.
But this isn't the case. We get a request-object of the base class Illuminate\Http\Request. 

This leads to a major issue for us because our concrete request classes sometimes define the "wantsJson" (or maybe more attributes in the future) for their particular behaviour. In the render()-method we would like to use our defined response macros to return json objects for the appropriate exceptions if needed. If the wantsJson() or ajax() calls are false, we force the default behaviour of the core ExceptionHandler.

So now I don't have the information about wantsJson of the original request anymore and our default redirects will fire so the expected JSON-Result by the client would be a webpage instead.

#### Question
Is this something that has a reason we don't have in mind? 
Please don't run too much on "wantsJson()" and "ajax()" as I know that if calls are made properly (defining the header on call) the ajax() method would return true. 
The attributes of the concrete request class could be useful in this render()-method anyway and I wonder if this is an issue or a desired behaviour which I just don't oversee.

I didn't even know how to build a search query for google on that question. Same problem for the issues on repo. Couldn't find anything relevant for this topic. If there's something, give me a hint please! 

### Steps To Reproduce:
- Create a custom FormRequest
- Force failing of authorization by setting "return false;" on the authorize() method
- set a dd($request) to your handlers render() method at the first line.
- observer the request object

Thank you in advance
Julius

**Comment by devcircus** [comment]
Could you override the ```failedAuthorization()``` and ```failedValidation()``` methods of your Form Request and get the behavior your require? There, you should be able to check the type of request and handle as needed.

**Comment by sisve** [comment]
I understand the confusion; but your type-hinted formrequest in your controller _is not_ the captured request. The request is captured in [public/index.php](https://github.com/laravel/laravel/blob/bc91dcab93a0784efde5fcf4fba6696c95c8e1ae/public/index.php#L53) and this is the "real" Request instance you get in your exception handler and everytime you resolve a Request from `app(Request::class)` or anything that uses the container.

The FormRequest object is a separate object that has all the data _copied_ from the real Request object.  This is done in callbacks in [FormRequestServiceProvider::boot](https://github.com/laravel/framework/blob/1bc8dd90218d382e516425e7f4abb28fafb33dc1/src/Illuminate/Foundation/Providers/FormRequestServiceProvider.php#L28-L39).

This is also why `function myAction(Request $request, MyFormRequest $myFormRequest) { ... }` resolves two separate objects.

**Comment by BillyBoeklunder** [comment]
Hey Sisve,
thank you for your answer. I thought about that but to my shame I didn't really try to look at the code of laravel itself in my confusion.

It's good to know anyway, that the request is not just "decorated" but copied.
So there is no issue, I just didn't get the concepts right. Thank you!

My problem with the solution of devcircus is, that I was not able to force the response from that point how I would have suggested. I used response()->forbidden()->send(), but this doesn't interrupt the execution of following scripts. I read about it and understand why the response doesn't interrupt. So we will have to take a look at our design again.

Thank you all.

**Comment by Dylan-DPC** [comment]
Do close your issue :)
