### ISSUE TITLE
BelongsToMany breaking change undocumented

### ISSUE THREAD

**Issue by yemenifree** [laravel/framework#21550]
- Laravel Version: 5.5.x
- PHP Version: 7.0
- Database Driver & Version: mysql 5.6

### Description:

after upgrade to Laravel 5.5, some methods are missing, after a search, I found it was renamed 

Laravel 5.4 | Laravel 5.5
-- | --
getQualifiedRelatedKeyName() | getQualifiedRelatedPivotKeyName()
getQualifiedForeignKeyName() | getQualifiedForeignPivotKeyName()

but this change does documented in upgrade guide

**Comment by yemenifree** [comment]
more information check #20869

**Comment by Dylan-DPC** [comment]
This isn't a bug. You didn't have to duplicate the issue. You can make a PR to laravel/docs with the change
