### ISSUE TITLE
Laravel trans() not working only returns key

### ISSUE THREAD

**Issue by kiwo12345** [laravel/framework#21556]
- Laravel Version: 5.4
- PHP Version: 7*

My directory looks like this:

![majs](https://user-images.githubusercontent.com/10579811/31260092-dce8f5b0-aa4b-11e7-8656-e54a08897f56.png)

    /resources
        /lang
            /en
                api.php

api.php looks like this:

    <?php
    
    return [
        'couldnotlogin' => 'Login failed, please check email and password',
    
    ];

But when I try

    dd(trans('api.couldnotlogin'));

it will only output:

**api.couldnotlogin**

    dd(App::getLocale());

returns **en**

other setting

    'locale' => 'en',
    'fallback_locale' => 'en',

I also tried `dd(Lang::has('api.couldnotlogin', 'en'));` which returns false
even `dd(Lang::has('auth.failed', 'en'));` returns false

What am I doing wrong?

**Comment by jpcaparas** [comment]
The `trans` helper doesn't have a fallback if your key doesn't exist in the translation files. You could try creating `trans_fb` helper where you can specify a default return value:

```
/**
 * Makes translation fall back to specified value if definition does not exist
 *
 * @param string $key
 * @param null|string $fallback
 * @param null|string $locale
 * @param array|null $replace
 *
 * @return array|\Illuminate\Contracts\Translation\Translator|null|string
 */
function trans_fb(string $key, ?string $fallback = null, ?string $locale = null, ?array $replace = [])
{
    if (app(Illuminate\Contracts\Translation\Translator::class)->has($key, $locale)) {
        return trans($key, $replace, $locale);
    }

    return $fallback;
}
```

**Comment by kiwo12345** [comment]
@jpcaparas but my file/key do exist, `dd(trans('api.couldnotlogin'));` should output _Login failed, please check email and password_

**Comment by jpcaparas** [comment]
That's actually odd. It should work based on your directory structure. Have you tried running `php artisan clear-compiled`?

**Comment by jpcaparas** [comment]
Hold up, your lang shouldn't be nested under `assets`. It should be nested under `resources`.

**Comment by kiwo12345** [comment]
@jpcaparas Your right! It should be nested under `resources` Thanks you so much for seeing it!

**Comment by nmedelmehdi** [comment]
Hello, 
Did i have seem issue here, __(), trans() returns only key.

**Comment by vishalmandora** [comment]
🚨 Attention developers! & @kiwo12345 

If you're encountering issues with the project setup, particularly with the `lang` directory, here's a quick fix:

Inside the project structure, you'll find a `lang` directory residing in both the `/resources` and the root directory. 
To resolve the issue, kindly remove the `lang` directory located at `/resources/lang` while retaining it in the root directory. 
Once done, the project should function smoothly.

Thank you for your attention to this matter!
