### ISSUE TITLE
'Y.m.d. H:i:s' dateFormat doesn't work

### ISSUE THREAD

**Issue by RajcsanyiZ** [laravel/framework#21557]
https://github.com/laravel/framework/blob/9f178aa29d00ccc005c8c080b42aca7f025a09e4/src/Illuminate/Database/Eloquent/Model.php#L145

> "InvalidArgumentException in Carbon.php line 582: Data missing"

```php
class TestModel extends Model
{
    protected $table = 'test_model';
    protected $fillable = ['date_field'];
    protected $dates = ['date_field'];
    protected $dateFormat = "Y. m. d. H:i:s"; // or  "Y.m.d. H:i:s"
}

class TestController extends Controller {
  public function CarbonMakeAnException() {
    $testModel = new TestModel;
    $testModel->deadline_at = '2017.01.01.';
    $testModel->save(); // triggering carbon error
  }
}
```

database: UTF-8 / general-ci
timezone: Europe/Budapest
os: Windows 10

**Comment by themsaid** [comment]
Looks like the original value in DB is not formatted correctly, also notice that `updated_at` and `created_at` fields format need to be updated in the database as well..

Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
