### ISSUE TITLE
Override hostname on named route url generation.

### ISSUE THREAD

**Issue by denjaland** [laravel/framework#21552]
- Laravel Version: 5.5.14
- PHP Version:7.1
- Database Driver & Version:

### Description:
Is there a way to override the hostname being used for a url generated for a named route?
We have a Mailable that does the following:
```
<?php $activation_url = route('get.core.auth.user.confirm', ['user' => $user, 'token' => $user->confirmation_token]); ?>
```
That activation_url is then used to display a button.

The mailables are queued, so run by horizon queues (love Horizon!)
I know I can set APP_URL, but our app is multitenant, and basically what we do is, on te Mailable, I have a parameter that has the hostname to be used, so I can use it in the mailable, because we obviously want to link the user to the domain name belonging to the tenant he's signing up for.

I don't see this supported anywhere - am I correct?

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. You can post in the forums. Or if you want this feature you can make a proposal in laravel/internals repo.

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
