### ISSUE TITLE
we are getting this error Uncaught TypeError: Cannot read property 'top' of undefined     at flyToElement (boards.html:2873)     at Object.success (boards.html:2922)     at fire (jquery.js:3099)     at Object.fireWith [as resolveWith] (jquery.js:3211)     at done (jquery.js:9310)     at XMLHttpRequest.callback (jquery.js:9720)

### ISSUE THREAD

**Issue by sanganagouda1** [laravel/framework#21560]
- Laravel Version: #.#.#
- PHP Version:
- Database Driver & Version:

**Comment by Dylan-DPC** [comment]
This doesn't look like laravel issue and can be closed. When creating an issue here mention the steps to reproduce and don't dump everything in the title (description field feels jealous).

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
