### ISSUE TITLE
Eloquent API - Resources doesnt work anymore

### ISSUE THREAD

**Issue by ToxicToast** [laravel/framework#21562]
- Laravel Version: 
**5.5.13**
- PHP Version: 
**7.1.6**
- Database Driver & Version:
**MySql 5.7.18**
### Description:
What worked perfectly fine on my Macbook (which I doesnt have anymore) doesnt work on my windows... more in the steps to reproduce

### Steps To Reproduce:
Ive created a Controller (BlogController) with 2 methods (index, show)
`public function index()
    {
        $data = Post::where('active', '1')->with('category')->with('comments')->paginate(config('toxictoast.pagination.per_page'));
        return BlogPostResource::collection($data);
    }
`
and
`
    public function show($id)
    {
        $query = Post::find($id);
        if (!empty($query)) {
            $data = $query->where('active', '1')->with('category')->with('comments')->get();
        } else {
            $data = collect();
        }
        return BlogPostResource::collection($data);
    }
}
`

As you can see, both of them using Collections

Lets go over to the Resource-File and here im going pure after the doc (as i mentioned before, it worked on macOS) here's the code.

`
<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\Resource;

use App\Http\Resources\BlogCommentsResource;
use App\Http\Resources\BlogCategoryResource;

class BlogPostResource extends Resource
{
    public function toArray($request)
    {
        return [
            'id'                => $this->id,
            'title'             => $this->title,
            'slug'              => $this->slug,
            'content'           => $this->content,
            'date'              => $this->created_at,
            'category'          => (!empty($this->category)) ? BlogCategoryResource::make(collect()->push($this->category)) : null,
            'comments'          => (!empty($this->comments)) ? BlogCommentsResource::collection(collect()->push($this->comments)) : null,
        ];
    }
}
`

When i try to run this piece of code - im getting an error message that says

> Property [id] does not exist on this collection instance. 
if i comment that out... it says
> Property [title] does not exist on this collection instance. 

etc. etc.

Hope anybody can help me

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
