### ISSUE TITLE
any non-get (post, put, delete) route in api.php gets 405 Method Not Allowed error

### ISSUE THREAD

**Issue by AucT** [laravel/framework#21577]
- Laravel Version: 5.5
- PHP Version: 7.1
- Database Driver & Version: mysql 5.7

### Description:
any non-get (post, put, delete) route in api.php gets 405 Method Not Allowed error

### Steps To Reproduce:
install laravel, add any post route in api.php and try to access it, turn on production mode.

**Comment by Dylan-DPC** [comment]
And how are you accessing the route? This sounds too trivial to fail.

**Comment by AucT** [comment]
through postman (chrome app)

**Comment by Dylan-DPC** [comment]
Are you using `/api/` prefix for API routes? Can you provide some more details. This doesn't seem like a bug. You can try the forums or the slack channels for help.

**Comment by AucT** [comment]
Something with nginx. Tried via php server and it worked.

**Comment by pildit** [comment]
I tried it on php server and it's not working! Any help please?
