### ISSUE TITLE
Touches (saves) seem to include global scopes

### ISSUE THREAD

**Issue by thc1967** [laravel/framework#21570]
- Laravel Version: 5.5.13
- PHP Version: 7.1.6
- Database Driver & Version: sqlite

### Description:

I have a global scope on my Model class. This global scope adds a join to the main eloquent query. I also have a child object bound to my main model class with hasMany() and in the child class as belongsTo(). The child class includes the parent relationship in its $touches array.

When using sqlite (which I use for my test suite) and I update a child, I get a 500 error during the touch because of the inner join on the global scope.

After doing some digging into the Laravel Framework code, it doesn't seem like this should be happening because the save() method tries to exclude scopes.

```PHP
// Laravel Model::save()
    public function save(array $options = [])
    {
        $query = $this->newQueryWithoutScopes();
```

When I evaluate the error, I see clearly that my global scope with the join has been added to the update query:

```
+exception: Illuminate\Database\QueryException {#1776
      #sql: "update "tickets" inner join "client_user" as "ticket_auth" on "ticket_auth"."client_id" = "tickets"."client_id" and "ticket_auth"."user_id" = ? set "updated_at" = ? where "tickets"."id" = ? and "tickets"."deleted_at" is null"
      #bindings: array:3 [
        0 => 9
        1 => "2017-10-06 21:25:29"
        2 => 1
      ]
      #message: "SQLSTATE[HY000]: General error: 1 near "inner": syntax error (SQL: update "tickets" inner join "client_user" as "ticket_auth" on "ticket_auth"."client_id" = "tickets"."client_id" and "ticket_auth"."user_id" = 9 set "updated_at" = 2017-10-06 21:25:29 where "tickets"."id" = 1 and "tickets"."deleted_at" is null)"
      #code: "HY000"
      #file: "...\vendor\laravel\framework\src\Illuminate\Database\Connection.php"
      #line: 664
```

It seems like we shouldn't see the join because we started our save() method by excluding global scopes.

### Steps To Reproduce:

1) Create a one-to-many relationship between two models. Touch the parent when updating the child.

2) Create a Global Scope on the parent that adds an inner join to another table.

3) Use sqlite as your database.

4) Run your app, update a child model, watch the referenced error occur.

**Comment by thc1967** [comment]
I created a repo that demonstrates this using the ubiquitous post/comment example model.

https://github.com/thc1967/laravel-framework-21570

Simply run the `CommentTest` unit test.

**Comment by themsaid** [comment]
Here's a fix https://github.com/laravel/framework/pull/21604

Thanks :)
