### ISSUE TITLE
Unable to set TRUE value to a database table field with the BIT(1) type

### ISSUE THREAD

**Issue by FinesseRus** [laravel/framework#21588]
- Laravel Version: 5.4.30, 5.5.4
- PHP Version: 7.1.1
- Database Driver & Version: MySQL 5.6.35

### Description:
When a table field's type is `BIT(1)` and you try to set the field's value to `true` using the query builder, the error occurs:

```
PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'my_boolean_column'
```

It is especially actual when you have an Eloquent model with a `boolean` attribute casting. The model casts the attribute value to boolean which is passed to a query builder.

### Steps To Reproduce:
Create a table:

```sql
CREATE TABLE `test_items` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `my_boolean_column` bit(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;
```

Create a model:

```php
class TestItem extends Model
{
    $casts = [
        'my_boolean_column' => 'boolean'
    ];
}
```

Create a model instance:

```php
$testItem = new TestItem();
$testItem->my_boolean_column = true;
$testItem->save();
```

### Investigation
The Laravel database component casts `true` to string when it binds a value to a statement. When `true` is casted to string in PHP it becomes `'1'` (string). The `BIT` field is binary therefore the database converts the string value `'1'` to the binary value `0b00110001`. The binary value length is 6 which is more then the maximum length of the `my_boolean_column` field (1), that's why the «Data too long» error occurs.

### Suggested solution
Cast `true` values to `1` (integer) in `Illuminate\Database\Connection::prepareBindings`.

Or cast boolean values to the type `PDO::PARAM_BOOL` in `Illuminate\Database\Connection::bindValues`.

**Comment by themsaid** [comment]
Can you open a PR with your suggestion?

**Comment by FinesseRus** [comment]
@themsaid Which one? Is the suggestion correct? I’m not sure because I don’t know much about how the framework works inside.

**Comment by 36864** [comment]
Considering there is already a check to turn `false` into `0`, seems to me the logical thing would be to add the same check for `true` into `1`.

https://github.com/laravel/framework/blob/ee1b3b204cb29e6530f4e93135e228638897f05e/src/Illuminate/Database/Connection.php#L594-L598

**Comment by themsaid** [comment]
Fixed here: https://github.com/laravel/framework/pull/21623

**Comment by FinesseRus** [comment]
@themsaid Thanks! I would have made a PR but you didn't respond.
