### ISSUE TITLE
about registerPolicies only get This action is unauthorized.

### ISSUE THREAD

**Issue by sunnoy** [laravel/framework#21584]
- Laravel Version: 5.5.14
- PHP Version:7.0.22
- Database Driver & Version:mysql 5.6

### Description:
1 create policies
```
 public function view(User $user)
    {
        return true;
    }
```
2 registerPolicies
```
 protected $policies = [
        //'App\Model' => 'App\Policies\ModelPolicy',
        Post::class => PostPolicy::class,
 ];
```
3 in controller to use
```
dd(Gate::allows('view'));
```
i get false

4 when i add Gate to boot() in AuthServiceProvider
```
  Gate::define('view', 'App\Policies\PostPolicy@view');
```
i get true

how about handle this ? I cant work it two days

### Steps To Reproduce:
Actions That Don't Require Models
should be
```
  $this->authorize('create', Post::class);
```

**Comment by Kyslik** [comment]
Try re-reading the documentation https://laravel.com/docs/5.5/authorization#authorizing-actions-using-policies it does not mention `Gate::allows` anywhere in that section.

**Comment by sunnoy** [comment]
if i use 
```
$this->authorize('view');
```
i can get "This action is unauthorized." when Postpolicy return true in function view()
in laravel the policy will through  $this->registerPolicies() register gate
```
foreach ($this->policies as $key => $value) {
            Gate::policy($key, $value);
        }
```
so i can to use Gate::allows

**Comment by sunnoy** [comment]
Methods Without Models
should be 
```
public function create(User $user)
{
    //
}

```
Actions That Don't Require Models
should be
```
  $this->authorize('create', Post::class);

```

**Comment by Kyslik** [comment]
Its in the docs, you do not need to post it here.
