### ISSUE TITLE
Model::getArrayableRelations cause unlimited loop

### ISSUE THREAD

**Issue by 354651432** [laravel/framework#21589]
- Laravel Version: 5.2.0
- PHP Version: 5.6
- Database Driver & Version: MYSQL 7.0

### Description:
`Model::getArrayableRelations`  函数序列化的时候，使用的是缓存`$this->relations`的数据，而并没有考虑数据键值是否在 `$this->with` 里边，这样会导致隐含的死循环，最终结果就是栈溢出了

### Steps To Reproduce:
 A belongto B ,B hasOne A ,然后实例化A的时候with B  在B类里边使用 对A的引用，序列化的时候带上对A的引用，但是B里边并没有定义 with A，这个时候就会导致与逻辑不符的死循环

### 解决方案
子类重写 getArrayableRelations 方法
```php
 protected function getArrayableRelations()
 {
     return array_only(parent::getArrayableRelations(), $this->with);
 }
```

**Comment by Dylan-DPC** [comment]
Hi. Can you post in English?

**Comment by sisve** [comment]
Laravel 5.2 is no longer supported. Does this problem still occur in Laravel 5.5?

**Comment by 354651432** [comment]
my eng is so bad, so  i think chanese is mutch more accuracy
the problem is that when serialize a model to json ,it well serialize undefined relation in $this->with array,
it well cause unwanted unlimited loop

the problem is still on version 5.4.36

**Comment by Dylan-DPC** [comment]
5.4 is no longer supported. Try it on 5.5 and create a new issue if required
