### ISSUE TITLE
Database exception when session data exceeds DB limit. New exception type for catching / ignore.

### ISSUE THREAD

**Issue by myquote-dev** [laravel/framework#21587]
- Laravel Version: 5.5.14
- PHP Version: 7.0.8
- Database Driver & Version: MySQL 5.6.33

### Description:

With database based sessions, when a user (or bot) posts a large amount of data to any page with a form an exception is thrown. When redirecting back withInput() the laravel session middleware will attempt to save the full session including the posted data in the input old section which results in the following SQL error reported in the logs.

`/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, PDOException(code: 22001): SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'payload' at row 1 at /vendor/laravel/framework/src/Illuminate/Database/Connection.php:483`

Unfortunately because this error is not distinguishable from any other similar SQL error it cannot be easily ignored / filtered out.

Can the framework instead throw a specific type of session exception when the session exceeds a predefined limit? That way we could ignore that type of exception and not have the logs filled with session errors. The limit could be defined by configuration or the framework middleware could catch the error when attempting to save the session and throw a new exception indicating the session save failed.

### Steps To Reproduce:

- Install Laravel and set session type to database in the config
- php artisan session:table
- php artisan migrate
- run the following code:

```
Route::any('test-session', function()
{
	session()->put('overflow', str_repeat('*', 65536));
	return "done";
});
```
- Check the logs

Alternatively to check using a form and input old. Create a simple form with a text area and post a large amount of data.

```
Route::get('test-form', function()
{
	return '<form method="POST">'.csrf_field().'<textarea name="large"></textarea><br><button type="submit">Go</button></form>';
});

Route::post('test-form', function()
{
	return redirect()->back()->withInput();
});
```

Please let us know if you need any more info on how to reproduce the problem.

**Comment by themsaid** [comment]
well this isn't actually a bug, and such exception if added has to be for all session drivers not just DB driver, so in case of failure to write an exception is thrown with enough details to debug.

Can you please add this suggestion to the https://github.com/laravel/internals repo.

**Comment by myquote-dev** [comment]
No problem. Thanks for taking a look at it.

**Comment by maganius** [comment]
How I can ignore that type of error? it throw an exception and broken my app, its not important for me, I want eloquent save the truncated text and return true
