### ISSUE TITLE
<?php tag in ajax response or when blade render (like) have open tag php

### ISSUE THREAD

**Issue by whendytakashy** [laravel/framework#21581]
- Laravel Version: 5.5
- PHP Version: 7.1
- Database Driver & Version:

### Description:

Yesterday I was confused by the opening of php tags. Any displays or requests for ajax always appear php tags. After I see some of the same cases, for example case link : 

[<? PHP tag in ajax response](https://laracasts.com/discuss/channels/general-discussion/php-tag-in-ajax-response)

I followed a comment that could solve the problem, but for me it did not work.

this case is located on the routes.php file. If there are empty routes.php file (as shown below) : 
routes.php empty:
```
<?php
/* empty, no code */

```
![Have open tag php](https://i.imgur.com/QZqxx2W.png)

### Steps To Solved:

I just delete the php opening tag in every empty routes.php file.

**Comment by devcircus** [comment]
Those files are autoloaded. That's what happens when you autoload a file with an opening php tag but leave it empty.

**Comment by whendytakashy** [comment]
Yes, maybe i should add information. I use the laravel-module package. Maybe in every module I created there is no route. So I have to delete or create the files routes.php them.

thank.

**Comment by Dylan-DPC** [comment]
I don't see this as a bug. It can be closed
