### ISSUE TITLE
[Feature Request] allow total records count to be set manually in paginate() method

### ISSUE THREAD

**Issue by brynj-digital** [laravel/framework#21594]
The `paginate()` method, used by the Eloquent query and query builder ([laravel docs](https://laravel.com/docs/5.5/pagination)), could benefit from the ability to manually pass the total record count to it, rather than have it calculated by the `runPaginationCountQuery()` method. I'd suggest as an optional (second?) parameter.

Often, a query that needs to be paginated includes several joins and sub-queries that do not affect the total records, but that can add significant overhead to the time needed to run the count aggregate query - I have a real world example at the moment that is approximately 5 times slower than it needs to be.

Allowing a user to manually calculate the total records with their own simpler query, then pass to the `paginate()` method seems logical to me.

**Comment by danjdewhurst** [comment]
Reported for off-topic.

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
