### ISSUE TITLE
Error when executing php artisan command

### ISSUE THREAD

**Issue by michaeltansy** [laravel/framework#21597]
- Laravel Version: 5.4
- PHP Version: 5.6
- Database Driver & Version: MySQL 5.7

### Description:
`PHP Catchable fatal error:  Argument 1 passed to Illuminate\Config\Repository::__construct() must be of the type array, integer given, called in /var/www/html/project/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php on line 36 and defined in /var/www/html/project/vendor/laravel/framework/src/Illuminate/Config/Repository.php on line 24`

I got the error above and I dont know how to solve it. anyone know the solution?

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by themsaid** [comment]
5.4 is not supported anymore, please upgrade to laravel 5.5
