### ISSUE TITLE
Validator `unique` doesn't allow white space

### ISSUE THREAD

**Issue by masterwto** [laravel/framework#21591]
- Laravel Version: 5.5.14
- PHP Version: 7.1.8
- Database Driver & Version: MariaDB

### Description:
The following validate rull causes problem in Laravel 5.5

```
'var_name' => 'unique: connection.table, property,' . $foo->id . ',id'
```

Caution for the white space before `property`, the validator then execetes query  as following
```
select count(*) as aggregate from `table` where ` property` = $foo->property and `id` <> $foo->id
```

Then QueryException[42S22] is reported: Colom. not found: 1054 Unknown column `  property` in 'where clause'...

In fact, the database has cloumn `property` in the table.

I think laravel validator should trim the white space automatically.

### Steps To Reproduce:
 As described above.

**Comment by Dylan-DPC** [comment]
I don't see this as a bug. You can make a proposal in internals repo

**Comment by themsaid** [comment]
don't use white space, or use the unique rule object for better readability.
