### ISSUE TITLE
[5.5] Route::middleware doesn't accept arrays

### ISSUE THREAD

**Issue by sebastiandedeyne** [laravel/framework#21618]
- Laravel Version: 5.5
- PHP Version: Any

### Description:

Calling middleware statically behaves differently than chaining the method. 

When digging into the source this makes sense looking at the implementation, but can be very confusing in usage + the error is silent.

### Steps To Reproduce:

```php
Route::middleware('foo', 'bar')->get('/'); // Only 'foo' is registered
Route::get('/')->middleware('foo', 'bar'); // Both middlewares are registered
```

**Comment by themsaid** [comment]
Submitted a PR to allow this to work at https://github.com/laravel/framework/pull/21621
