### ISSUE TITLE
I can not find the Authenticate.php in Middleware Folder.

### ISSUE THREAD

**Issue by ParvezPatwary** [laravel/framework#21617]
- Laravel Version: 5.4
- PHP Version: 7.0
- Database Driver & Version: Mysql 5.7.19

### Description:
 I am unable to find the Authenticate.php anywhere , now how can I do my Authentication things?? I used the Auth::logout(); for user logout option. after hitting the logout option it says Route('login') undefined. I heard that Helper.php is the alternative. but I don't know how to do these things in handler. By the way I am a newbie . So, please help me. if any of you provide some codes for that it will be very helpful for me.. Thanks in Advance.

**Comment by CWallenberg** [comment]
Have you run the command `php artisan make:auth`?

**Comment by ParvezPatwary** [comment]
yes I did, but I want change the route('login') to route('user.signin') because I already made these routes and controllers.. and now I want to change the default route name of Auth::logout();

I think you understand what do I want to say.

**Comment by CWallenberg** [comment]
` Auth::logout();` is just a method to log out users of your application. 
You can just change the name of the authentication routes if you comment `Auth::routes();` in `routes/web.php` and then you are free to define all your auth routes with custom names.

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue
