### ISSUE TITLE
PHP Parse error

### ISSUE THREAD

**Issue by vuthaihoc** [laravel/framework#21610]
- Laravel Version: 5.5.13
- PHP Version: 7.1.2
- Database Driver & Version: Mysql

### Description:
Error when i deploy to server

### Steps To Reproduce:
Error:
```
Generating optimized autoload files                                                                                                                                                              
  > post-install-cmd: php artisan clear-compiled                                                                                                                                                   
  PHP Parse error:  syntax error, unexpected '?' in /###/releases/1/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 233                         
  Script php artisan clear-compiled handling the post-install-cmd event returned with error code 255  
```

**Comment by TsvetomirCh** [comment]
php -v PHP 7.1.10

php -l src/Illuminate/Foundation/helpers.php 
No syntax errors detected in src/Illuminate/Foundation/helpers.php

Are you sure you are using php 7+?

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by jmarcher** [comment]
As Dylan said here is not the place for such issues, but anyways...

You are not using PHP 7 that is for sure.

**Comment by vuthaihoc** [comment]
Thank for your replies. I resolved my issue. I will post to forum if i have next issue 😄
