### ISSUE TITLE
Can't swap PDO instance while within transaction.

### ISSUE THREAD

**Issue by rommelandrea** [laravel/framework#21620]
- Laravel Version: 5.1.31 
- PHP Version: 7.0.11
- Database Driver & Version: postgres

### Description:
I have a method that needs to connect to a named db PgSql connection. This is my code:
```
try {
        DB::reconnect('nav');
        DB::connection("nav")->beginTransaction();
        $this->createAccountingData($backInvoice);
        DB::connection("nav")->commit();
    } catch (Exception $ex) {
        DB::connection("nav")->rollBack();
        throw new GenericException($ex->getMessage());
    }
```
The code run into a laravel job. For few months it worked succesfully, but now it thrown to me this error "Can't swap PDO instance while within transaction."

Restarting db connections it still doesn't work, but restarting both db connection and queue process it seems to work successfully.

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
