### ISSUE TITLE
imagecreatefromjpeg throws fatal error not warning on corrupt image when run as a command

### ISSUE THREAD

**Issue by samthomson** [laravel/framework#21627]
- Laravel Version: 5.4.*
- PHP Version: 7.1
- Database Driver & Version: bundled lib-gd

### Description:
I’m running into a Fatal Error just when opening a corrupt jpeg, ideally I’d be able to catch it like I can in raw php, but laravel/symfony seems to raise the warning as a fatal error.

### Steps To Reproduce:
put this code in a laravel function and make a path to the attached corrupt image.
```
$im = @imagecreatefromjpeg('440.jpg');

if(!$im) {
    echo "image was bad..";
}else{
    echo "image Ok";
}
```
but instead this error is thrown:
![image](https://user-images.githubusercontent.com/6588340/31468119-5c2f143a-aed4-11e7-8e0a-1ff1223ed24e.png)

I think it's a bug that laravel/symfony is elevating a warning to a fatal error. If it is not, how can I avoid this?

UPDATE: This problem occurs only when running as console command, not as part of a web route.

![440](https://user-images.githubusercontent.com/6588340/31468070-275d1a5e-aed4-11e7-9636-458e44838477.jpg)

But if I write in raw php:
```
<?php

$im = @imagecreatefromjpeg('440.jpg');

if(!$im) {
    echo "image was bad..";
}else{
    echo "image Ok";
}
?>
```
it works as expected:
![image](https://user-images.githubusercontent.com/6588340/31468249-e4119abc-aed4-11e7-9cda-41a1f0df2fe8.png)

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.

**Comment by samthomson** [comment]
Yes, I believe it's a bug that's why I posted it here. I will see if I get any answers elsewhere..
