### ISSUE TITLE
Cannot push jobs to queue in mysql connection strict mode

### ISSUE THREAD

**Issue by khageshsaini** [laravel/framework#21630]
- Laravel Version: 5.5
- PHP Version: 7.0
- Database Driver & Version: Mysql 5.5.54

### Description:
In strict mode, laravel doesn't seem to provide a default value for 'reserved' column. 

### Steps To Reproduce:
Dispatch Job in strict mode.

**Comment by Dylan-DPC** [comment]
Can you provide more details?

**Comment by themsaid** [comment]
`reserved_at` defaults to null.
