### ISSUE TITLE
Error reporting issue

### ISSUE THREAD

**Issue by kikky7** [laravel/framework#21632]
- Laravel Version: 5.4.36
- PHP Version: 7.1.0
- Database Driver & Version: MySQL 5.7.18

### Description:
I have 2 different projects with the same configurations.
Laravel framework version is the same and php version is the same.
PHP error_reporting is set to -1 on both projects.
If I try to echo undefined variable {{ $foo }}, in one project I get null, on other project I get Whoops page: Undefined variable: foo.
The proper way would be to check if variable exists or is set, but why I am getting null on one project, instead of undefined variable notice? What can be causing this kind of behavior?
Edit: when I use undefined function, it throws Whoops on both projects, i.e. {{ dump(_check($foo)) }}

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by kikky7** [comment]
This can also be a bug, but ok.
