### ISSUE TITLE
syncWithoutDetaching inserts duplicate entries when sending concurrent requests

### ISSUE THREAD

**Issue by ketysek** [laravel/framework#21639]
- Laravel Version: 5.4.36
- PHP Version: 5.6.30
- Database Driver & Version: MySQL 5.7

### Description:

Assume tables and many to many relationship between them.
When I send concurrent requests (at same time), syncWithoutDetaching doesn't work correctly and inserts new rows in pivot table. This broke my application, because I expected unique pairs of foreign keys in my pivot table. 

### Steps To Reproduce:

- create 2 tables with many to many relationship between; my pivot table has an additional integer column called `value`
- send some number of concurrent request on method where syncWithoutDetaching is applied

**Comment by sisve** [comment]
Well, concurrency requires some kind of locking system to ensure that you're the only one doing the change. Are you using any locking? Perhaps database transactions with a high transaction level?

**Comment by themsaid** [comment]
This should be handled in your app, check Laravel 5.5 Locking feature.

**Comment by fede91it** [comment]
This problem is still present in my end

**Comment by themsaid** [comment]
@fede91it check my reply above :)

**Comment by devcircus** [comment]
This is an issue you'll need to handle in your app. You may get some assistance from the locking feature of Laravel. There are also some packages available that may help.

**Comment by fede91it** [comment]
Do you suggest someone in particolar? Thanks
