### ISSUE TITLE
set status text with abort function

### ISSUE THREAD

**Issue by mostafamiri65** [laravel/framework#21644]
- Laravel Version: 5.5.14
- PHP Version: 7.1.10

### Description:
When I try to `POST` with `X-Requested-With='XMLHttpRequest'` without `CSRF-TOKEN` I receive `null` message in response.
I add this code to `App\Exceptions\Handler`:
````
public function render($request, Exception $exception)
    {
        if($exception instanceof TokenMismatchException) {
            abort(419, 'Token Mismatch OR page has expired due to inactivity.');
        }
        return parent::render($request, $exception);
    }
````
Now I have `Token Mismatch OR page has expired due to inactivity.` message in response, but status text is: `unknown status`.

How can I set status text?

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by mostafamiri65** [comment]
It can add to next version @Dylan-DPC as new feature.

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
