### ISSUE TITLE
Laravel Blade Include tag take too much time to render.

### ISSUE THREAD

**Issue by shahidbasheer** [laravel/framework#21643]
- Laravel Version: 5.0
- PHP Version: 5.6
- Database Driver & Version: 

### Description:
Hi im using Laravel 5.0 and i use some blade @include tag to create partials file  but i face extreme slow rendering time then i remove include files and put the content of partial in content section all pages are loading within a second i wonder what is wrong with the include tag i have attached laravel-debuger states if you can take a look. 

http://prntscr.com/gwoidw

**Comment by Dylan-DPC** [comment]
Laravel 5.0 :scream: is no longer supported and this repo is only for bug tracking. If you need help try the forums or the slack channel
