### ISSUE TITLE
Caveat of (Laravel/Lumen)'s Eloquent/Query Builder `orWhere` method

### ISSUE THREAD

**Issue by elegisandi** [laravel/framework#21649]
- Lumen Version: 5.4.6
- PHP Version: 7.1
- Database Driver & Version: MySQL 15.1

### Description:
Found a very interesting caveat of Laravel's Eloquent/Query Builder orWhere` method.
This is only applicable to `equal` comparison though. It could be a rare case but make sure to explicitly set the `operator` as the 2nd argument unless you are certain with the `value`.

### Steps To Reproduce:
Example: ```TestModel::where('field', $dynamic_value);```

> The code above could return an error if `$dynamic_value` is equal to any mysql terms (eg: `like`, `between`).

**Instead do it this way**, ```TestModel::where('field', '=', $dynamic_value);```

**Comment by devcircus** [comment]
See [this comment](https://github.com/laravel/framework/issues/20530#issuecomment-322243406) by @themsaid on #20530
