### ISSUE TITLE
[5.5] Relation error on model's custom name (differ than table name)

### ISSUE THREAD

**Issue by TaronSaribekyan** [laravel/framework#21652]
- Laravel Version: **5.5**
- PHP Version: **7.0**
- Database Driver & Version: **MySQL 5.7.18** x86_64 (Ubuntu)

### Description:
If model name doesn't match with appropriate table name from database, there is an attribute `$table` or method `getTable()` which can be overridden. But attribute `$table` ignores in relational methods (to generate table name and foreign keys names).

### Steps To Reproduce:

- there is a table `roles` and the model `Role` for it (instance of `\Illuminate\Database\Eloquent\Model`)
- there is a table **`users`** and the model **`UserAuth`** for it (instance of `\Illuminate\Database\Eloquent\Model`)
- `users` connected with `roles` using many-to-many connection table: **`role_user`**
- `UserAuth` class:
      
      class UserAuth extends \Illuminate\Database\Eloquent\Model 
      {
          protected $table = 'users';
          
          public function roles()
          {
              return $this->belongsToMany('App\Role');
          }
      }
      
Now when we try to get user's first role we get an error:

> Base table or view not found: 1146 Table 'temp_db.role_user_auth' doesn't exist 

Of course, we can pass table/column names as well (`$this->belongsToMany('App\Role'), 'role_user', 'user_id'`). But is it OK to pass name for every relation, if we already set correct table name in model?

### Change suggestion:

I suggest to change method **`\Illuminate\Database\Eloquent\Concerns\HasRelationships::joiningTable()`** (which detects joining table name), and use **`$this->getTable()`** instead of **`class_basename($this)`**.
Same change may be need also in method **`\Illuminate\Database\Eloquent::getForeignKey()`**.

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. This isn't a bug so you can open a proposal in the laravel/internals repo

**Comment by themsaid** [comment]
yes you'll need to override the default values generated by `belongsToMany()` in this case and provide all five arguments of the method, check the docs for more information.
