### ISSUE TITLE
Calling `$model->load('relationship')` re-fetches all the loaded relationships.

### ISSUE THREAD

**Issue by mace015** [laravel/framework#21653]
- Laravel Version: 5.5.3
- PHP Version: 7.1.3
- Database Driver & Version: MySQL 5.7.17

### Description:
When a model is already fetched with some relationships eager loaded, and the user calls the `load()` method to eager load another relationship, all the already loaded relationships are also re-fetched, this causes unnecessary queries to be executed.

#### Model:
```
protected $with = ['relation-1', 'relation-2'];
```
#### Controller:
```
$model = SomeModel::first();
// At this point, 3 queries are executed, one for the model itself, and one for each relationship.

$model->load('relation-3');
// At this point 3 more queries are executed, one for each relationship, 
// including the already fetched relationships ('relation-1', 'relation-2' and 'relation-3') 
// while this should only execute one query for 'relation-3'.
```

# Edit:
This only seems to happen when you set the first 2 relations to be eager loaded directly in the `$with` property on the model: `protected $with = ['relation-1', 'relation-2'];`

**Comment by 36864** [comment]
Can't reproduce on latest release. Can you update and see if it's still happening?
This is what I get when I log queries after running the commands on tinker:

```
>>> $user = App\User::with(['departments', 'contract'])->first();
/* Query 1 - 2017-10-13 13:00:22 [0.84ms]  */
select * from `users` limit 1;
/*==================================================*/
/* Query 2 - 2017-10-13 13:00:22 [1.02ms]  */
select `departments`.*, `department_user`.`user_id` as `pivot_user_id`, `department_user`.`department_id` as `pivot_department_id` from `departments` inner join `department_user` on `departments`.`id` = `department_user`.`department_id` where `department_user`.`user_id` in ('0');
/*==================================================*/
/* Query 3 - 2017-10-13 13:00:22 [0.65ms]  */
select * from `contracts` where `contracts`.`id` in ('0');
/*==================================================*/

>>> $user->load('groups');
/* Query 4 - 2017-10-13 13:00:29 [0.96ms]  */
select `groups`.*, `group_users`.`user_id` as `pivot_user_id`, `group_users`.`group_id` as `pivot_group_id` from `groups` inner join `group_users` on `groups`.`id` = `group_users`.`group_id` where `group_users`.`user_id` in ('0');
/*==================================================*/

>>>
```

**Comment by mace015** [comment]
Just tried it with the latest tag (5.5.14), and the issue is still there.

What happens on your end when you set the first 2 relations to be eager loaded directly in the model: `protected $with = ['relation-1', 'relation-2'];`?

**Comment by 36864** [comment]
Defining the eager loads in the model does indeed cause it to reload the relations.
Interestingly, `loadMissing` will trigger the same load even if the relation has already been loaded (or even if it's one of the `$with` relations.
```
//Model
$with = ['relation-1'];

//Controller
$model = Model::first(); //triggers loading of relation-1
$model->loadMissing('relation-1') // loads relation-1 again
```


Looking through the code, it's easy to see why this happens. Not sure if it's an easy fix though.

(did you edit your first post to use $with or did I just misread it entirely on the first go?)

**Comment by mace015** [comment]
I edited it later after I realized I gave the wrong example in the first place! ;)

**Comment by JayBizzle** [comment]
I submitted this PR (https://github.com/laravel/framework/pull/14090) a while back to offer a `loadOnly()` method which was rejected.

I now have to included my own `loadOnly()` method in my applications. 

On the `Model` class it looks like this...

```php
    /**
     * Eager load only the specified relations on the model.
     *
     * @param  array|string  $relations
     * @return $this
     */
    public function loadOnly($relations)
    {
        if (is_string($relations)) {
            $relations = func_get_args();
        }
        $without = array_diff($this->with, $relations);
        if (empty($without)) {
            $query = $this->newQuery()->with($relations);
        } else {
            $query = $this->newQuery()->with($relations)->without($this->with);
        }
        $query->eagerLoadRelations([$this]);

        return $this;
    }
```

and on the `Eloquent\Collection` class it looks like this...

```php
    /**
     * Load only the specified relationships onto the collection.
     *
     * @param  mixed  $relations
     * @return $this
     */
    public function loadOnly($relations)
    {
        if (count($this->items) > 0) {
            if (is_string($relations)) {
                $relations = func_get_args();
            }

            $model = $this->first();
            $without = array_diff($model->with, $relations);

            if (empty($without)) {
                $query = $model->newQuery()->with($relations);
            } else {
                $query = $model->newQuery()->with($relations)->without($model->with);
            }

            $this->items = $query->eagerLoadRelations($this->items);
        }

        return $this;
    }
```

**Comment by themsaid** [comment]
Opened a PR to fix this, thanks for reporting :)

https://github.com/laravel/framework/pull/21710
