### ISSUE TITLE
Using paginate for eager loaded relationships generates two repeated queries

### ISSUE THREAD

**Issue by axelitus** [laravel/framework#21655]
- Laravel Version: 5.5.14
- PHP Version: 7.1.0
- Database Driver & Version: 5.7.16
(using Homestead 3.1.0)

### Description:
When having a one-to-many relationship and eager-loading it with the related objects paginated, the query that gathers the related model is executed two times.

### Steps To Reproduce:
1. Create a model (in this case Company) and a related model (in this case Payrolls) [one company has many payrolls].
2. Fetch the company eager-loading the related payrolls (my original query has been simplified here):
```php
$company = Company::where('id', 1)->with(['payrolls' => function($query) {
    $query->simplePaginate(24);
}])->firstOrFail();
```
3. Using barryvdh/laravel-debugbar ^3.0 the display is the following:
![2017-10-13_09h29_08](https://user-images.githubusercontent.com/732441/31551072-171d087c-aff9-11e7-884d-b3c21bc143fe.png)

This does not happen with a simple query without related models:
![2017-10-13_09h31_06](https://user-images.githubusercontent.com/732441/31551149-52596f84-aff9-11e7-9486-de80297c57b3.png)

I have tested paginate() and simplePaginate() and both yield the same result.

**Comment by devcircus** [comment]
See [this comment](https://github.com/laravel/framework/issues/19421#issuecomment-305199628) by @themsaid. I don't know if anything has changed since then but it seems like similar issues are reported from time to time with no resolution.

**Comment by Dylan-DPC** [comment]
Yeah you can close the issue :smile:

**Comment by axelitus** [comment]
I got to the same conclusion: paginating while eager is not the way to go because you lose the pagination object and cannot create the links (surely amongst other things). I ended loading my related models from outside the eager loading logic. Thank you all!

**Comment by kmihiranga** [comment]
i got the same issue.

`select `id`, `title`, `short_description`, `document_source`, `category` from `downloads` where `downloads`.`category` in (2) and `downloads`.`deleted_at` is null limit 10 offset 0`
