### ISSUE TITLE
[5.6] ThrottlesLogins occasionally fails tests

### ISSUE THREAD

**Issue by sebastiandedeyne** [laravel/framework#21651]
When running tests in quick succession, sometimes they fail because of the login throttle functionality.

I realise it's possible to inherit the `hasTooManyLoginAttempts` method and modify it, but I'd rather not maintain that exception in my application. Is this something we can fix in the framework?

Possible solutions:

- Always disable throttling during tests (with `App::runningUnitTest()`)
- Add an `auth.throttle` config key

If there's interest in this I'd be up to PR'ing it, just let me know which direction we want to go here :)

**Comment by themsaid** [comment]
imo I think disabling throttling while running tests makes sense, unless you want to test that your login throttling works :)

**Comment by laurencei** [comment]
If you are using an "array" Cache in your tests - wouldnt that solve it?

**Comment by sebastiandedeyne** [comment]
Heh, for some reason I set the cache driver to file for test cases, array solves it indeed. Explains why I hadn't come across this issue sooner.

I think this is  a good enough solution, gonna close this :)
