### ISSUE TITLE
Unreleased versions separate read-only repositories

### ISSUE THREAD

**Issue by evilebottnawi** [laravel/framework#21657]
Here we have `Support` package version `v5.5.14`, but in https://github.com/illuminate/support/tree/v5.5.2 only available `v5.5.2`. What is the reason for this out of sync? Thank you!

**Comment by ntzm** [comment]
I've brought this up multiple times and it always gets ignored for some reason, would definitely like to know the answer 👍

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. This isn't a bug so you can open a proposal in the laravel/internals repo

**Comment by GrahamCampbell** [comment]
This shouldn't go in the proposals repo either. New tags will be pushed in good time, don't worry. :)

**Comment by ntzm** [comment]
That doesn't really help...

**Comment by ntzm** [comment]
Looks like we get blanked as usual for this issue
