### ISSUE TITLE
Array to string conversion in DenyAuthorizationController.php (line 46)

### ISSUE THREAD

**Issue by kelvinhalim13** [laravel/framework#21666]
- Laravel Version: 5.5.*
- PHP Version: 7.0

Laravel passport, after show me an Authorization Request View, i try to cancel the authorize, however i got an error in 

`vendor\laravel\passport\src\Http\Controllers\DenyAuthorizationController.php`

```
        $authRequest = $this->getAuthRequestFromSession($request);

        $uri = $authRequest->getClient()->getRedirectUri();

        $separator = $authRequest->getGrantTypeId() === 'implicit' ? '#' : '?';

        return $this->response->redirectTo(
            $uri.$separator.'error=access_denied&state='.$request->input('state')
        );
```

the `$uri` is in array method which contain my client redirect_uri

can someone help me how to solve this ? edit vendor **should not a suggestion** because

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue
