### ISSUE TITLE
Type Blob not Exists? How to save image with Eloquent in Field BLOB?

### ISSUE THREAD

**Issue by fulviocanducci** [laravel/framework#21668]
- Laravel Version: 5.5
- PHP Version: 7
- Database Driver & Version: MySQL

### Description:

In Code: 
```
public function bindValues($statement, $bindings)
{
	foreach ($bindings as $key => $value) {
		$statement->bindValue(
			is_string($key) ? $key : $key + 1, $value,
			is_int($value) || is_float($value) ? PDO::PARAM_INT : PDO::PARAM_STR
		);
	}
}
```
Not exists Blob That is, PDO::PARAM_LOB ?

https://github.com/laravel/framework/blob/1bc8dd90218d382e516425e7f4abb28fafb33dc1/src/Illuminate/Database/MySqlConnection.php line 75

## How to save image with Eloquent in Field BLOB?

**Exception:** _String Data, right truncate: 1406 Data too long for column 'type' at row_ ...

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by fulviocanducci** [comment]
@Dylan-DPC is bug ...
