### ISSUE TITLE
When testing, store() method store file in storage/framework/testing instead of storage/app/public

### ISSUE THREAD

**Issue by xoco70** [laravel/framework#21665]
- Laravel Version: 5.5.4
- PHP Version: 7.1
- Database Driver & Version: Sqlite

### Description:

I am testing avatar upload, as said in docs: 

```
       Storage::fake('public');
        $this->json('POST', 'api/v1/users/' . $user->slug . '/avatar', [
            'file' => $file = UploadedFile::fake()->image('avatar.jpg')
        ]);

        $this->assertEquals($file->hashName(), auth()->user()->avatar);

        Storage::disk('public')->assertExists('avatars/' . $file->hashName());

``` 

This works great, but in my controller, just after upload, I resize pic with Intervention, so, I must do:

```
$file = request()
            ->file('file')
            ->store('/images/avatar'), 'public');
        
        Image::make(storage_path('app/public/' . $file))
            ->resize(...);
```

when testing, my controller blows because store() method upload avatar in `storage/framework/testing/images/avatar`.

I wouldn't like to add extra logic in controller like ìf (env === 'testing) ... ` to manage this case.

Is there a way to disable store() behaviour?

**Comment by gabriel-caruso** [comment]
I didn't get what's wrong. 

First: What `config('images/avatar')` returns?
Second: Are you storing the image twice? Calling `store` and `Image::make`?

Are your tests correctly?

**Comment by xoco70** [comment]
When Accessing web app, file is saved to `storage/app/public/images/avatar`

When testing app via PHPUnit, file is saved to  `/framework/testing/disks/public/images/avatar`

`Image::make(storage_path('app/public/' . $file))` doesn't create another file, it create an Intervention instance to manipulate image. 

So when testing, it tries to find `storage_path('app/public/' . $file`), but file doesn't exists.

I should do:

```
if (testing){
     return Image::make(storage_path('storage/framework/disks/public' . $file))
}
return Image::make(storage_path('app/public/' . $file))
   
```

But it is not a good practice to do that.

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.

**Comment by themsaid** [comment]
The file locations during tests is different than on production, your assertions has to take that into account.
