### ISSUE TITLE
session expired when running 2 separate laravel application

### ISSUE THREAD

**Issue by sayaamiruladli** [laravel/framework#21677]
- Laravel Version: 5.5
- PHP Version: 7.0

### Description:
i have two laravel app running on my xampp/htdocs directory.

let first app as x, second app as y.

### Steps To Reproduce:

when im running x on another browser window, y session expired and vice versa. any idea?

**Comment by gabriel-caruso** [comment]
Maybe your browser flushes the section with the same name. Try change one of application's session name

**Comment by sayaamiruladli** [comment]
@gabriel-caruso thanks, that solve the problem haha
