### ISSUE TITLE
Model::flushEventListeners does not flush events registered via the (recommended) $dispatchesEvents property

### ISSUE THREAD

**Issue by monooso** [laravel/framework#21676]
- Laravel Version: 5.5.14
- PHP Version: 7.1.10
- Database Driver & Version: SQLite 3.16.0

### Description:
The `Model::flushEventListeners` does not "flush" any events registered via the `$dispatchesEvents` array. This is very unexpected behaviour, which to all intents and purposes looks like a bug.

I realise that, technically, Laravel is raising a _custom_ event in response to a model lifecycle event, but this is an implementation detail. As far as the developer is concerned, he's hooking into a standard model lifecycle event.

This impression is backed up by [the Laravel documentation][laravel-eloquent], which clearly states that the way to hook into a model lifecycle event is via the `$dispatchesEvents` property:

[laravel-eloquent]: https://laravel.com/docs/5.5/eloquent#events

> To get started, define a `$dispatchesEvents` property on your Eloquent model that maps various points of the Eloquent model's lifecycle to your own event classes

Given that [the `flushEventListeners` method][flush-events-method] claims to "Remove all of the event listeners for the model", it is reasonable to assume that this will include those model event listeners defined via the `$dispatchesEvents` property.

[flush-events-method]: https://github.com/laravel/framework/blob/5.5/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php#L288-L304

In reality, it only "flushes" those event listeners defined via the model's static "event lifecycle" methods (`creating`, `created`, and so forth).

### Steps To Reproduce:
Create a model, and associate a custom event class with a standard model lifecycle event.

```php
<?php

namespace App;

use App\Events\UserCreated;
use Illuminate\Database\Eloquent\Model;

class User extends Model
{
    protected $dispatchesEvents = ['created' => UserCreated::class];
}
```

Create the event class, which simply dies when instantiated.

```php
<?php

namespace App\Events;

use App\User;

class UserCreated
{
    public $user;

    public function __construct(User $user)
    {
        dd('KHAAAAAN!');
    }
}
```

Create a basic unit test class, which attempts to run without model events.

```php
<?php

namespace Tests\Unit;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class FlushEventListenersTest extends TestCase
{
    use RefreshDatabase;

    public function testFlushEventListeners()
    {
        User::flushEventListeners();
        $user = factory(User::class)->create();
    }
}
```

And run it...

```bash
$> phpunit

"KHAAAAAN!"
```

**Comment by themsaid** [comment]
fixed in https://github.com/laravel/framework/pull/21688

thanks :)
