### ISSUE TITLE
When trying to validate array of fields, they get lost when returned

### ISSUE THREAD

**Issue by vladkucherov** [laravel/framework#21684]
- Laravel Version: 5.4.36
- PHP Version: 7.1

When trying this:
```
$rules = \Illuminate\Support\Facades\Validator::make([], [
    'name' => 'required',

    'schedule.*.day'  => 'sometimes|numeric',
    'schedule.*.from' => 'sometimes|date_format:H:i',
    'schedule.*.to'   => 'sometimes|date_format:H:i',
]);

dd($rules->getRules());
```
The dump will show:
```
array:1 [
  "name" => array:1 [
    0 => "required"
  ]
]
```

It happens mainly because of this function:
`\Illuminaite\Validation\ValidationRuleParser@explodeWildcardRules`

It tries to fetch data fields from the data, by removing whatever comes before `*`, after it tries to loop over the data, and see if the data key `services` starts with attribute `services.*.day`, which of course it doesn't. And that makes it skip it.

Switching the order of the condition `Str::startsWith($key, $attribute)` to `Str::startsWith($attribute, $key)` doesn't help, returns only 1 level of rules. I am not sure what it should return though.

Any ideas?

**Comment by gabriel-caruso** [comment]
That's a strange one. If you dump `$rules`, all rules will be showing in `initialRules`, but not in `rules` one :thinking:

**Comment by vladkucherov** [comment]
@gabriel-caruso Not quite. you'll see in the `initialRules` what was entered through the constructor, but in `rules` you'll see the already parsed rules, with only `name` in it.

**Comment by gabriel-caruso** [comment]
I'm trying to test it to find the path that the rules take from `Validator@make` method thought `Validation@getRules`

**Comment by themsaid** [comment]
That's how it works, what are you trying to achieve?

**Comment by vladkucherov** [comment]
@themsaid Why would you want to remove rules with `*` ?

I attached an issue I opened on a package I use which should generate API docs by scaning the validation rules to determine what parameters an endpoint accepts. But because of the way the `ValidationRuleParser` works, some parameters gets missed, which doesn't make sense.

**Comment by themsaid** [comment]
We need to remove these rules from the `$this->rules` as they're handled differently, I believe the package needs to put this behavior into account or feel free to open a PR to put a method that acts differently.
