### ISSUE TITLE
problem with paginate when use select case and parameter binding

### ISSUE THREAD

**Issue by HassanShojaei** [laravel/framework#21689]
- Laravel Version: 5.5
- PHP Version:7
Hi, I want to execute this query:
```
select (case 
   when(title like 'my-keyword') then 1
   when(description like 'my-keyword') then 2
   ) as ordering from products where id > 10;
```
When I do this by query builder:
```
$products = DB::table('products')->select(DB::raw('(case 
   when(title like '?') then 1
   when(description like '?') then 2
   ) as ordering'))->where('id', '>', 10)->setBinding(['my-keyword', 'my-keyword'])->paginage(10);
```
this will going to get count and as we know this will remove all select part and replace it with `count(*) as aggregate` so if I use setBindings on this query builder and pass `['my-keyword', 'my-keyword']` to this query for aggregate will change to this:
`select count(*) as aggregate from products where id > my-keyword;`

I changed some codes in vendor/..../Query/Builder.php:
this:
`$total = $this->getCountForPagination($columns);`
to this:
```
        $all = $this->get();
        $total = $all->count();
```
for this situation I know it's wrong but for now it works!

what should I do to resolve this problem in a correct way?!

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.

**Comment by HassanShojaei** [comment]
@themsaid So isn't it a problem?!
Query builder or eloquent with pagination doesn't support  this type of queries?

**Comment by Tofandel** [comment]
Well it kinda is a bug, getCountForPagination() will fail if there is bindings in the `select` statement, I think eloquent could be made to detect those bindings and remove them when making the count for pagination query

**Comment by Tofandel** [comment]
So after some digging, the `setBindings` or `addBinding` method needs to be called with `select` as the second argument
```php
$products = DB::table('products')->select(DB::raw('(case 
   when(title like '?') then 1
   when(description like '?') then 2
   ) as ordering'))->where('id', '>', 10)->setBindings(['my-keyword', 'my-keyword'], 'select')->paginage(10);
```
