### ISSUE TITLE
[5.1.45] Flash message with redirect() doesn't work, but works with \Redirect

### ISSUE THREAD

**Issue by dakshhmehta** [laravel/framework#21680]
- Laravel Version: 5.1.45
- PHP Version: 7.0
- Database Driver & Version: MySQL
- Session Driver: File

### Description:
The issue was found and discovered on www.learnkarts[dot]com and is using secure and encrypted cookies.
We are using redirect()->back()->with('success'', 'Thanks for submission'); syntax in order to flash a success message in whole application. However, on specific page the flash didn't come. The flashdata is being set on post method, but when get is executed, the flash message doesn't get persisted in the session.

The same code happen to work on locally and on staging server where SSL isn't installed.

### Steps To Reproduce:
The exact step not able to track it down, however changing
redirect()->back()->with('success', 'Thanks!') to \Redirect::back()->with('success', 'Thanks!');

Please let me know if it is laravel issue or anything else.

It has been resolved right now as mentioned above but something to seriously think on as why it had came on first place.

**Comment by Dylan-DPC** [comment]
5.1 is no longer supported. Kindly submit a new issue if this occurs in 5.5

**Comment by dakshhmehta** [comment]
So, not even session driver or anything is being supported?

Any specific and solid guide to upgrade to Laravel 5.1 to 5.5?

**Comment by ntzm** [comment]
@dakshhmehta You can use the upgrade guide in the documentation
