### ISSUE TITLE
[5.4] Queue worker memory leak

### ISSUE THREAD

**Issue by sakshigargit** [laravel/framework#21687]
- Laravel Version: 5.4
- PHP Version: 7.0.22
- Database Driver & Version: MySQL & 5.7.19

### Description:

I am running my queue worker on the server that contains Ubuntu, Apache, PHP, MySQL but even though I'm not even running jobs yet! It's just idle, the queue still eating up the memory 1 MB in every two seconds or so and then sooner it gets out of memory.

I am just running my queue:work command without anything else. 
Also, from the other articles I have read the issue will get resolved by queue:restart in particular timeframe but this is also not working.

Please help me out my server buffer/cache is filling very fast and it is not even releasing any memory.

Thanks in Advance

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
