### ISSUE TITLE
No file or Dir exists Example.vue

### ISSUE THREAD

**Issue by yashpokar** [laravel/framework#21696]
- Laravel Version: 5.5.15
- PHP Version:
- Database Driver & Version:

### Description:
\vendor\laravel\framework\src\Illuminate\Foundation\Console\Presets/vue-stubs/Example.v
  ue): failed to open stream: No such file or directory

after running
     php artisan preset none
and then 
    php artisan preset vue

### Steps To Reproduce:
change filename to ExampleComponent.vue

**Comment by mathieutu** [comment]
Fixed by https://github.com/laravel/framework/pull/21685
