### ISSUE TITLE
Named routes within `Route::group`

### ISSUE THREAD

**Issue by brendt** [laravel/framework#21691]
- Laravel Version: 5.5.14
- PHP Version: 7.1.8

### Description:

The name of a named route seems not to register when in a `Route::group` closure.

### Steps To Reproduce:

This setup works:

```php
// web.php

Route::view('/', 'pages/home')->name('home');
```

```php
// somewhere else

route('home');
```

This gives an exception:

```php
// web.php

Route::group(['prefix' => locale()], function () {
    Route::view('/', 'pages/home')->name('home');
}
```

```php
// route('home');

Route [home] not defined. (View: resources/views/_components/contact.blade.php) (View: resources/views/_components/contact.blade.php)
```

**Comment by 36864** [comment]
This repo is for bug reports in the framework, not your project. Please use the forums or slack channel for help, etc. etc.

You've grouped the route and added a prefix to it. Your route's name is `{locale}.home`

**Comment by brunogaspar** [comment]
@36864 You're incorrect, `prefix` has nothing to do with naming routes. The prefix is for the url part which means the route is still named `home` but the url is `{locale}/home`.

However, i'm not able to reproduce the issue.

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.

**Comment by 36864** [comment]
@brunogaspar Thank you for the correction.
In trying to reproduce I must have accidentally copy-pasted a named group from my project instead of a non-named group.

**Comment by shinodaluk** [comment]
I'm having the same issue. When I register a new group of routes under a custom Provider, if I use the chaining method to name the route, I get on the not defined error. If I register in a array like, it gives no error. I think is a bug, but right now I don't have a way to reproduce it for you.
