### ISSUE TITLE
Unique cache key with value "0" is cached for 1 minute on every request

### ISSUE THREAD

**Issue by KarlisJ** [laravel/framework#21690]
- Laravel Version: 5.4.23
- PHP Version: 7.1.6.

### Description:
For some reason production server cache folder grows in size with no particular reason. 

To start off - we do not use caching nowhere in whole project. 

In .env file we have `CACHE_DRIVER=file`. Server is deployed on Digital Ocean. This behaviour is not happening in local environment. 

I added listener to `Illuminate\Cache\Events\KeyWritten` event and did a simple log:
```
public function handle(KeyWritten $event)
    {
        Log::info('New cache written', [
            'key' => $event->key,
            'value' => $event->value,
            'minutes' => $event->minutes,
            'request' => (string) request()
        ]);
    }
```
What I wound out inspecting the logs was that on every request a new key is added to cache always with value 0 for 1 minute. So on every request 14kb are added to cache folder. 

I will tell this again - nowhere in project we explicitly call `Cache::put`. When searching in all project only this [line](https://github.com/svenanders/Laravel/blob/master/src/Illuminate/Session/CacheBasedSessionHandler.php#L63) from source code came up. 

Currently we have set up to run `php artisan cache:clear` on every deploy but still want to find what the cause of this issue is.

**Comment by sisve** [comment]
Could you also share the cache key with us? A 60 second cache time sounds like the request throttling, but that should only be active for api requests.

You can use [debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS)](https://secure.php.net/manual/en/function.debug-backtrace.php) to get a stack trace to debug who triggers the KeyWritten event, and probably track down where it starts at.

**Comment by Dylan-DPC** [comment]
Two things:
1) Laravel 5.4 is no longer supported
2) This doesn't seem like a bug. You can use a forum or slack channel to get your issue solved

**Comment by themsaid** [comment]
This looks like the requests throttler, make sure you're not using it.
