### ISSUE TITLE
[5.6] Incorrect plural forms of uncountable words when prefixed with other words

### ISSUE THREAD

**Issue by edsamonte** [laravel/framework#21702]
### Description:
Incorrect plural forms of uncountable words if they are at the end of a multi-word phrase.

### Steps To Reproduce:
```
>> str_plural('metadata')
>> "metadata"
>> str_plural('user metadata')
>> "user metadatas"
```

Willing to create a PR if this is an acceptable concern.

**Comment by edsamonte** [comment]
This also leaves `php artisan make:model UserFeedback -m` to create `create_user_feedbacks_table`.

**Comment by BenExile** [comment]
The DocBlock describes the function as being able to pluralise a _word_, not a phrase. `str_plural` uses [doctrine/inflector](https://github.com/doctrine/inflector) to pluralise words so it may be worth raising an issue there if you feel it's appropriate.

**Comment by themsaid** [comment]
laravel uses doctrine/inflector for this
