### ISSUE TITLE
[5.5] dispatch() helper returns object

### ISSUE THREAD

**Issue by stevevg** [laravel/framework#21709]
- Laravel Version: 5.5.13
- PHP Version: 7.1.10
- Database Driver & Version: 15.1 Distrib 10.2.9-MariaDB

### Description:
As I pointed out in a [stackoverflow question](https://stackoverflow.com/questions/46785656/in-laravel-5-5-how-to-get-the-job-id-after-we-dispatch-a-job-to-the-job-queue), the `dispatch()` helper now returns a `PendingDispatch` object, instead of the id of the job. 

[5.4](https://github.com/laravel/framework/blob/1bc8dd90218d382e516425e7f4abb28fafb33dc1/src/Illuminate/Foundation/helpers.php#L378)
vs.
[5.5](https://github.com/laravel/framework/blob/3a16d196bd8d2b7761c9b0060a30a3687c3ea201/src/Illuminate/Foundation/helpers.php#L383)

In fact, trying to access the result of the `dispatch()` helper returns:
`Object of class Illuminate\Foundation\Bus\PendingDispatch could not be converted to string`

What if I want to retrieve the job id of the newly created job in the queue, as I did before?
I didn't find anything in the documentation or in the upgrade guide.

### Steps To Reproduce:
```php
$job = (new JobClass());
$jobId = dispatch($job);

echo $jobId; // Generates exception
```

**Comment by themsaid** [comment]
You can use this to have the same output as in 5.4:

```
app(\Illuminate\Contracts\Bus\Dispatcher::class)->dispatch($job)
```

**Comment by stevevg** [comment]
Thank you, this solves the problem. Might be the case to add this to the 5.4 -> 5.5 upgrade guide docs?

**Comment by mstralka** [comment]
The `DispatchesJob` trait makes this easier. It's applied to controllers by default but it can be added to other classes too.
