### ISSUE TITLE
Dropping a foreign and changing a column which depends upon it cannot be accomplished in the same migration

### ISSUE THREAD

**Issue by MatteoOreficeIT** [laravel/framework#21712]
- Laravel Version: 5.4.30
- PHP Version: 5.6.31
- Database Driver & Version: MySQL PDO

### Description:

In migration up we change a column type and after we create a FK which depends upon it.

The opposite down  migration cannot be executed , it triggers this error :

`
[Illuminate\Database\QueryException]                                                                                 
  SQLSTATE[HY000]: General error: 1025 Error on rename of '.\test_argopro_2\#sql-f38_21cb' to '.\test_argopro_2\aud_u  
  tenti' (errno: 150) (SQL: ALTER TABLE mytable CHANGE coltxt coltxt VARCHAR(30) NOT NULL)
`

### Steps To Reproduce:

Create a similar migration :

```php
public function up()
{
  Schema::table('mytable',function(Blueprint $table){
    $table->string('coltxt')->change();
    $table->foreign('coltxt');    
  });
}

public function down()
{
  Schema::table('mytable',function(Blueprint $table){
    
    $table->dropForeign('coltxt');    
    $table->dropIndex('coltxt');    
    // this triggers error, It seems order is not respected
    $table->string('coltxt',30)->change();
  });
}

**Comment by Dylan-DPC** [comment]
Laravel 5.4 is no longer supported. Test this issue on a fresh 5.5 install and let us know

**Comment by MatteoOreficeIT** [comment]
Sorry , I didn't stay tuned for updates 

I definitely verified in source code of 5.5 and 5.4 , the same logic is applied

see this method Blueprint::toSql()

https://github.com/laravel/framework/blob/5.5/src/Illuminate/Database/Schema/Blueprint.php#L97

I think create/alter column commands are executed before any compileDropXXXX commands, this is right in the common **migration up** use cases  ( create columns then add foreign key ) but in **migration down** use case the order should be reversed if one need to run both FK drop and column type changes

A workaround would be split migration in two simple migrations to guarantees order , maybe a hint in the doc could save many people from and headache

Thanks

**Comment by sisve** [comment]
It can be done in one migration, but perhaps not in the same call to Schema::table.

**Comment by themsaid** [comment]
> It can be done in one migration, but perhaps not in the same call to Schema::table.

That'd work yeah.
