### ISSUE TITLE
Bug with Gates/Policies (Very weird bug?)

### ISSUE THREAD

**Issue by petersontubini** [laravel/framework#21729]
- Laravel Version: 5.5.17
- PHP Version: 7.0.23
- Database Driver & Version: MYSQL 5.7

### Description:
The bug happens when I use hyphen to define gates and use multiple parameters. If I remove the hyphen it works perfectly.

### Steps To Reproduce:
1) I've created a simple gate on AuthServiceProvider: 

`Gate::define('manager-staff', function ($account, $store) {
            return \DB::table("users_roles")->where("store_id",$store->id)
            ->where("user_id", $account->user->id)
            ->whereIn('role_id', [1, 2])->exists();
        });`

2) Try to use this gate on a controller:
`if (\Gate::allows('manager-staff', [$store]))
 {
     dd("a");
 }`

3) If I remove the hyphen of the word "manager-staff" to "managerstaff" it works. With the hyphen I got the exception: 
Missing argument 2 for App\Providers\AuthServiceProvider::App\Providers\{closure}(),

**Comment by themsaid** [comment]
Can't replicate your issue, works fine for me.

**Comment by themsaid** [comment]
Please seek help on the forums, looks like it's something in your project.
