### ISSUE TITLE
[5.5] There is already an active transaction

### ISSUE THREAD

**Issue by vrubiella** [laravel/framework#21725]
- Laravel Version: 5.5.17
- PHP Version: 7.1.10
- Database Driver & Version:  mysqlnd 5.0.12-dev

Error:
`There is already an active transaction {"exception":"[object] (PDOException(code: 0): There is already an active transaction at /www/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php:108)"} `

Piece of code manages transactions:

```php
        $nodeConnection =DB::connection(env('DB_WRITE_CONNECTION'));

        $nodeConnection->transaction(function() use ($lastJobClass,$nodeConnection){
            $nodeConnection->table((new ModelJob())->getTable())->where([
                ['name','=', $lastJobClass],
                ['process_id','=', $this->id]
            ])->update(['status' => 'processed']);
        },3);

        $processTableName = (new Process())->getTable();

        $stepUpdated = $nodeConnection->transaction(function() use($nodeConnection,$processTableName){
            return $nodeConnection->table($processTableName)->where('id',$this->getProcessId())->whereColumn('step','<','steps')->increment('step');
        },3);
```

I'm just upgrade to Laravel 5.5 and PHP 7.1.10. 

Previous version (PHP 7.1.? and Laravel 5.4) has no problems.

Error is raised sometimes, not always.

When error occurs, model status not updated on first transaction (['status' => 'processed']).

Jobs are dispatched in a execution plan. A plan defines dependences between jobs (similar new feature withChain), and can manage multiple dependences as a condition. (X job will be raised when A, C and D jobs are processed).

**Comment by Dylan-DPC** [comment]
Can you try this out on a simpler version and share the steps to reproduce here? That way others can try it out as well

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.

**Comment by philippzentner** [comment]
Why is this closed? Any ideas how to solve this?

**Comment by Dylan-DPC** [comment]
Probably because it wasn't clear whether it is a bug or not. If you had this issue and think it is a bug you can create a new issue with all details possible.

**Comment by micobarac** [comment]
I am getting the same error with latest Laravel 8 on Gallera cluster :(

```php
    /**
     * Cleanup
     *
     */
    protected function cleanup()
    {
        foreach (Sources::$sources as $source) {
            try {
                // Delete old data
                DB::transaction(function () use ($source) {
                    DB::table($source['table'])
                    ->where('period_type_id', 1)
                    ->whereRaw('STR_TO_DATE(CONCAT(date, " ", hour, ":", minute), "%Y-%m-%d %H:%i") <= DATE_FORMAT(NOW(), "%Y-%m-%d %H:00") - INTERVAL 2 DAY')
                    ->delete();
                }, 5);
            } catch (\Exception $e) {
                $now = Sources::now();
                $this->error("{$now}: Daily cleanup command for `{$source['title']}` ran with error: {$e->getMessage()}");
            }
        }
    }
```
