### ISSUE TITLE
Global Scope for Unique validation rule.

### ISSUE THREAD

**Issue by Aferz** [laravel/framework#21721]
- Laravel Version: 5.5.17
- PHP Version: 7.1
- Database Driver & Version: Mysql 5.7

### Description:

Global scopes are not being applied in built in Laravel rules.

### Steps To Reproduce:

1. Apply a global scope to any model:

```php
...

class Course extends Model
{
    ...

    protected static function boot()
    {
        parent::boot();
        
        static::addGlobalScope('center_id', function ($query) {
            $query->where('courses.center_id', 1);
        });
    }

    ...
}

...
```

2. Validate dummy data:

```php
$this->validate(request(), [
    'class' => [
        'required',
        Rule::unique('courses', 'class')
    ]
]);
```

3. Check executed query:

```php
[
    "query" => "select count(*) as aggregate from "courses" where "class" = ?"
    "bindings" => array:1 [
        0 => "dummy_data"
    ]
    "time" => 0.12
]
```

As you can see, the global scope is not being applied to the "unique" rule query. I didn't test it, but other rules could have the same problem.

Is this expected behaviour ?

Thanks !

**Comment by devcircus** [comment]
Definitely the expected behavior.  Could easily be done with a custom rule though.

**Comment by Aferz** [comment]
@devcircus But why ? I mean, why laravel doesn't inject global scopes into validation rules?

I know it can be done through custom rules, but I wanna know the reason which global scopes don't apply in validation rules.

**Comment by sisve** [comment]
The unique rule works with tables and columns, not models. Just like the DB facade, it does not apply scopes.

**Comment by devcircus** [comment]
e.g. soft deletes utilizes global scope. You can't run a unique validation check while ignoring some rows.

**Comment by Aferz** [comment]
@sisve @devcircus Okay, that makes sense. Now I know the reason behind this issue.

Thank you both.

**Comment by jaskoola** [comment]
Hi, 

unique rule without global scopes is inconsistent with exists rule.
Exists rule is similar. It is also database rule, but is uses gloabl scopes.
This happens with lates laravel. 

It should be at least some notes on documentation and some way to easily apply scopes by name.
What do you think?

WBR

**Comment by nurazimzahurin** [comment]
By default, Laravel's exists and unique validation rules use the raw query builder, which means they don't take Eloquent model global scopes into account.

To address this, I created a library for those who prefer not to manually write custom validation rules each time, keeping things DRY and more maintainable. 

Leave a like, any opening is appreciated.

https://github.com/nurazimzahurin/laravel-rule-with-scope

**Comment by jonnott** [comment]
> By default, Laravel's exists and unique validation rules use the raw query builder, which means they don't take Eloquent model global scopes into account.
> 
> To address this, I created a library for those who prefer not to manually write custom validation rules each time, keeping things DRY and more maintainable.
> 
> Leave a like, any opening is appreciated.
> 
> https://github.com/nurazimzahurin/laravel-rule-with-scope

Can you publish this on packagist.org?
