### ISSUE TITLE
Array of checkboxes validation required rule does NOP

### ISSUE THREAD

**Issue by Kyslik** [laravel/framework#21728]
- Laravel Version: 5.5.17
- PHP Version: :seven:.:zero:
- Database Driver & Version: :thought_balloon:

### Description:
Upon validating array of checkboxes, required rule does nothing, if checkbox is **not** ticked. (If its not present in request data).

### Steps To Reproduce:
Have multiple checkbox inputs as array:

```html
<form method="POST" action="http://checkbox.dev/check">
	<input type="checkbox" name="terms[]" value='1'>
	<input type="checkbox" name="terms[]" value='1'>
	<input type="submit">
</form>
```

Have following controller:

```php
class CheckboxController extends Controller
{
    public function store(CheckboxRequest $request) {
        return dd('I got here', $request);
    }
}
```

And following form-validation request rule set:

```php
public function rules()
{
    return [
        'terms.*' => 'required',
    ];
}
```

I have also tried rules `present`, `accepted` as well as their combination with no joy.

**Comment by Dylan-DPC** [comment]
What are you getting?

**Comment by Kyslik** [comment]
Well it passes the validation, I see my `dd('I got here, $request)` output.

**Comment by Dylan-DPC** [comment]
And what are you inputs? you need to be clear in your issue so that people can reproduce your issue and verify whether it is a bug or not

**Comment by Kyslik** [comment]
I am as clear as I can be, my input is simply 2 checkboxes demonstrated in steps to reproduce section.

If neither of checkboxes are checked browser does not send it to the server so if I do `dd(request()->all());` I get nothing (obviously) but at the same time validation **passes** and it should not.

**Comment by themsaid** [comment]
`terms` is empty and as a result `terms.*` won't run since there are not items at all.

You need to apply the required rule on `terms` not `terms.*`

**Comment by Kyslik** [comment]
@themsaid Yes thats exactly what I am doing, but its not correct. I need to check that all terms on page (3 checkboxes) are checked not just one.

I am ok doing custom validation rule, I am just surprised that its not possible out of box.

**Comment by themsaid** [comment]
Yeah that's not possible, also the validator doesn't know what values your checkboxes have, you'll need to write your own rule for this.

**Comment by Kyslik** [comment]
Thanks, 👍

**Comment by Kyslik** [comment]
Well solution to this is to use two validation rules:

```php
return [
    'terms' => 'required',
    'terms.*' => 'accepted'
]
```

And send data from backend using hack that involves hidden inputs:

```html
<form method="POST" action="{{ route('check.store') }}">
    {{ csrf_field() }}
    <input type="hidden" name="terms[0]" value="0" />
    <input type="checkbox" name="terms[0]" value='1'>
    <input type="hidden" name="terms[1]" value="0" />
    <input type="checkbox" name="terms[1]" value='1'>
    <input type="submit">
</form>
```

![out](https://user-images.githubusercontent.com/2067589/31768108-26bc998a-b4ce-11e7-8463-58e9f3083a4c.gif)
