### ISSUE TITLE
Optional TECHNICAL_MESSAGES parameter on Validator::make to repress stripping of underscores from attribute placeholder

### ISSUE THREAD

**Issue by martinjoiner** [laravel/framework#21726]
I am offering to fork, code and create pull-request to implement the following feature:

An enhancement to Validation whereby the replacement of underscores with spaces in the attribute name can be repressed. 

Currently line 240 of `/Validation/Concerns/FormatsMessages.php` is where the operation takes place and it cannot be disabled/overridden. 

**Use case example:** 

For when feedback messages are to be consumed by developers (not the general public) and the messages should be more technical and specific. Think public API routes. 

So for the message:

```
'The :attribute field is required.'
```

By default Laravel would still return:

> The vehicle name field is required.

But with the TECHNICAL_MESSAGES flag set it would return the more technical:

> The vehicle_name field is required.

**Proposed implementation**

I am proposing adding the flag as a constant on the Validator class for readability and then the flag would be provided in the `customAttribute` array as the fourth argument of `Validator::make()`. The FormatsMessages concern would then check if it is set before continuing to strip underscores. 

An implementation might look something like this: 

```
Validator::make( $request->all(), $params, [], [ Validator::TECHNICAL_MESSAGES ] );
```

Please, if you think this is a good enhancement just give me the thumbs up and I will do the work. 

Thanks.

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. This isn't a bug so you can open a proposal in the laravel/internals repo

**Comment by martinjoiner** [comment]
Thanks. Moved to https://github.com/laravel/internals/issues/837
