### ISSUE TITLE
Unable to override helper functions

### ISSUE THREAD

**Issue by Lidbetter** [laravel/framework#21737]
- Laravel Version: 5.5.*
- PHP Version: n/a
- Database Driver & Version: n/a

### Description:
There is currently no good way to override helper functions defined by the framework.

Previously it was possible to manually include files via `bootstrap/autoload.php`, (in 5.5 that functionality has moved into `public/index.php`) but with the upgrade to phpunit 6 (which now directly loads the autoloader) I can't run any code via phpunit which uses any of my helper functions.

### Steps To Reproduce:
run the following:

`laravel new helpers`
`cd helpers`
`mkdir app/Utilities`
```
echo "<?php

function now() {
    return gmdate('Y-m-d H:i:s');
}
" > app/Utilities/helpers.php
```
`cat composer.json > composer.original.json`
`cat composer.original.json | jq '.autoload += .autoload + {files: ["app/Utilities/helpers.php"]}' > composer.json`
`composer dump-autoload`

Output:
```
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
PHP Fatal error:  Cannot redeclare now() ...
```

**Comment by arrilot** [comment]
You just need to make a special file with such helpers and manually require it in `bootstrap/autoload.php.` before composer autloader

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by Lidbetter** [comment]
@arrilot as explained in the issue - `bootstrap/autoload.php` does not exist anymore when hitting from a web request all setup is done in `public/index.php` and when running `phpunit` the very first thing phpunit does is include the composer autoloader file

@Dylan-DPC This seems like a bug, it's not possible (without composer extensions) to prevent laravels helper functions from being defined while testing

**Comment by sisve** [comment]
Modify your `public/index.php` to include a file with your own implementations of the helper methods before you include the `vendor/autoload.php` file.

**Comment by Lidbetter** [comment]
@sisve This does not help when running tests - the first thing phpunit does is include the autoloader: https://github.com/sebastianbergmann/phpunit/blob/6.0/phpunit

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.

**Comment by Lidbetter** [comment]
@themsaid 
This is a problem which technically can be solved in other ways, but they all suck. Would you be open to a PR which changed how these helper functions are defined (probably via a service provider)?

**Comment by browner12** [comment]
If you're looking for loading helpers with a service provider, check out my package: https://github.com/browner12/helpers

**Comment by solofeed** [comment]
The same problem.

**Comment by solofeed** [comment]
@Lidbetter How you resolve your problem?

**Comment by kenorb** [comment]
Follow-up: laravel/internals/issues/709

**Comment by Swanty** [comment]
In Laravel 5.5+ you can override helper functions with this:
https://github.com/funkjedi/composer-include-files
