### ISSUE TITLE
HasMany/HasOneOrMany Relations shouldn't add WHERE key IS NOT NULL to query

### ISSUE THREAD

**Issue by ckdot** [laravel/framework#21731]
- Laravel Version: 5.5.x
- PHP Version: 5.6 - 7.1

### Description:
When defining a hasMany relationship to a model, the query to fetch the relation entities should not add a condition that the key must not be NULL.

### Steps To Reproduce:
1. Add a relation to your model, e.g.:

    public function siblings()
    {
        return $this->hasMany(Type::class, 'parent_id', 'parent_id');
    }

2. Check executed queries when calling $model->siblings

Query will be e.g.:
`select` * from `categories` where `categories`.`parent_id` = 5 and `categories`.`parent_id` is not null`

This is probably fine if you just have parent/child relations or similar but won't work for siblings like in the example, if you want to have all siblings of your root categories. The generated query would be:
`select` * from `categories` where `categories`.`parent_id` IS NULL and `categories`.`parent_id` is not null`

This will return an empty result all the time and should is not expected behaviour.

**Comment by Dylan-DPC** [comment]
It makes no sense. If foreign key is null it means it is not related. Also if you eager load with `with`, it will return you all the columns with foreign key as null. I don't see this as a bug

**Comment by ckdot** [comment]
> If foreign key is null it means it is not related

Does it? In my example I'd expect that two entities _are_ related if foreign key value is the same like the local key value. So even if both values are NULL, I'd expect both entities are related.

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.

What you're asking for would be a breaking change, so please open a ticket on the internals repo to move the discussions there.

**Comment by fisharebest** [comment]
> So even if both values are NULL, I'd expect both entities are related.

No, because in SQL `NULL` is not equal to `NULL`.
