### ISSUE TITLE
Artisan command called incorrectly when trailing :

### ISSUE THREAD

**Issue by davidpiesse** [laravel/framework#21730]
- Laravel Version: 5.5.13
- PHP Version: 7.1.7
- Database Driver & Version: SQLite

### Description:
Calling `php artisan view:` results in `view:clear` being run.
When including the trialing `:` it runs the only option (if only one)
This is ONLY the case for those with only one option. Tested on 
- db
- view
- vendor
- storage

Where > 1 option after : it does not error and responds with the "Did you mean" as expected

### Steps To Reproduce:
1. Install base Laravel as usual
2. From a terminal run `php artisan view:`

Can;t find in the code where this is coming in - but happy to fix & PR if someone can point me to the offending piece
Feels like an array search that is not exact so finds the only one that starts with that and assumes that is right

**Comment by devcircus** [comment]
This functionality comes from the symfony console component. It tries to figure out which command you intended to run and if only one command matches what you have typed, that command runs. If there are multiple possibilities, it will let you choose.

Example: php artisan ti

This will open tinker

**Comment by davidpiesse** [comment]
That's seems a little bit crappy doesn't it ?!
From a accidental mistake (`make:auth`, `db:seed`, `key:generate`, `schedule:run`) you could affect your app unintentionally.
But good from a shortcut way!

Any way we could do a check before it goes to Symfony to check it is in the list of commands?

**Comment by Dylan-DPC** [comment]
I don't think there is anything we can do here.

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
