### ISSUE TITLE
verbatim section cannot comment 

### ISSUE THREAD

**Issue by 354651432** [laravel/framework#21738]
- Laravel Version: 7.1.7
- PHP Version:5.4.36
- Database Driver & Version:

### Description:
code between `@verbatim` and `@endverbatim` cannot use `{{--` and `--}}` to comment,is it a bug?

**Comment by brunogaspar** [comment]
Doesn't seem a bug, it seems intended, since the purpose of `@verbatim` is to allow the use of these curly braces for example, without triggering Blade.

**Comment by 354651432** [comment]
yes, but it seens too strangely two type of comment in a blade file

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. This isn't a bug so you can open a proposal in the laravel/internals repo
