### ISSUE TITLE
illuminate/support 5.4 doesn't support php 5.6

### ISSUE THREAD

**Issue by Odalrick** [laravel/framework#21746]
- PHP Version: 5.6

### Description:
There is php > 5.6 syntax in illuminate/support 5.4 . Looks like it was introduced by b8cb37e15331c59da51c8ee5838038baa22d7955 .

### Steps To Reproduce:

- Use php 5.6
- Crash

**Comment by Dylan-DPC** [comment]
splat operator was introduced in PHP 5.6 not 7.0

**Comment by Odalrick** [comment]
Yeah, sorry. I was given bad input and ran with it.
