### ISSUE TITLE
[Bug 5.5] Eloquent returns all records using Model::where('any_text_field', 0)->get()

### ISSUE THREAD

**Issue by markdwhite** [laravel/framework#21741]
- Laravel Version: 5.5.14 & 5.5.17
- PHP Version: PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
- Database Driver & Version: MySql Server version: 5.7.19-0ubuntu0.16.04.1-log (Ubuntu)

### Description:
All records are returned when calling where() on any model with any text field, with the search param of (int) 0.
This does not occur with 5.1.46 (the only other install I have to hand) where no entries are returned.
Tested in three different 5.5.* projects, with numerous models and text fields.
Identified when using unit tests when a default value of (int) 0 was used instead of an empty string, so this also occurs under sqlite.
A query like this should not normally be run in practise, but the resultant behaviour seems buggy.

### Steps To Reproduce:
In any project
Using tinker
Using any model with a text field and entries in the DB
With the command in the format: \App\Models\AnyModel::where('any_text_field', 0)->get()

Eg:
\NewsLetters\Models\Template::where('name', 0)->get()
\Healthcheck\Models\Server::where('account', 0)->get()

**Comment by sisve** [comment]
What's the generated sql statements, and are you running mysql with strict mode? Have you checked if mysql issue any warnings with your queries?

According to the [mysql's type conversion rules](https://dev.mysql.com/doc/refman/5.7/en/type-conversion.html) you're comparing your values as floating-point numbers.  All your string values doesn't start with a digit will be converted to the value of zero, and thus matching your query.

**Comment by markdwhite** [comment]
Generated queries:

5.1.46 (not strict)
467 Prepare	select * from `booklend_books`.`club_books` where `Title` = ?
467 Execute	select * from `booklend_books`.`club_books` where `Title` = '0'

5.5.14 (strict)
468 Prepare	select * from `servers` where `account` = ?
468 Execute	select * from `servers` where `account` = 0

5.5.17 (strict)
469 Prepare	select * from `templates` where `name` = ?
469 Execute	select * from `templates` where `name` = 0

5.5.17 (not strict)
470 Prepare	select * from `adverts` where `author` = ? and `adverts`.`deleted_at` is null
470 Execute	select * from `adverts` where `author` = 0 and `adverts`.`deleted_at` is null

No warnings or errors in mysql error log.

For me, I've fixed my code. I can see that the type conversion rules are being correctly followed, so maybe this was a bug in 5.1 and now it's doing what it should do. 

And from experimenting, it looks as though queries of this nature on text fields always returns 0, hence the where() is satisfied:

select 0 + title from adverts limit 1
https://stackoverflow.com/questions/8005445/mysql-datatype-conversion-from-varchar-to-float

Looks like expected behaviour then.
