### ISSUE TITLE
Strange view at dd()

### ISSUE THREAD

**Issue by ForzaSFerrari** [laravel/framework#21744]
- Laravel Version: 5.5.17
- PHP Version: 7.1.1

### Description:
When I use dd(), I get a strange view on website.
![capture](https://user-images.githubusercontent.com/16107131/31765123-a1b2faae-b4c3-11e7-8a33-81bcff6fe36e.PNG)

### Steps To Reproduce:
Just use dd(Auth::user()) for example

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by ForzaSFerrari** [comment]
I think it's a bug. Just few versions ago again I hadn't this view.

**Comment by sisve** [comment]
That's the stylesheet used by dd(). I would guess that you're not rendering the html correctly, or perhaps doing ajax calls and just taking the text content of them into your dom.

**Comment by themsaid** [comment]
looks like it's something in your app, please seek help on the forums.
