### ISSUE TITLE
Daemon kill/exit might be overcomplicated 

### ISSUE THREAD

**Issue by AidasK** [laravel/framework#21747]
- Laravel Version: 5.5.#

### Description:
```php
if (extension_loaded('posix')) {
            posix_kill(getmypid(), SIGKILL);
}
exit($status);
```
https://github.com/laravel/framework/blob/9357854e3c8f15c8b6738530b3158b12ee5f7f0c/src/Illuminate/Queue/Worker.php#L544

Why do we need to kill this process twice? Isn't running `exit($status);` is not enough? Why do we need to send posix_kill(getmypid(), SIGKILL); ?

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by ntzm** [comment]
There is a difference: https://stackoverflow.com/a/6261872/2012476

**Comment by AidasK** [comment]
SIGKILL prevents shutdown functions and object destructors from execution as I can understand. 
I don't think we need this, exit should be enough and I would expect destructors to be executed. 

But in this case, there is no difference, because job was already processed.

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
