### ISSUE TITLE
Implicit model binding might be broken

### ISSUE THREAD

**Issue by Hooolm** [laravel/framework#21743]
- Laravel Version: 5.4.18
- PHP Version: 7.1.8
- Database Driver & Version:  (PostgreSQL) 9.5.8

### Description:
The implicit binding in laravel does not bind one of my Models called CostConfiguration for some reason.
I have created an explicit binding for it, but i wonder why this particular class name does not work.

### Steps To Reproduce:
I have a Model called CostConfiguration
I have this in my web.php - routes file
```
. . .

Route::group(['prefix' => 'cost-configurations', 'as' => 'cost-configurations.'], function () {
  Route::post('/', ['as' => 'store', 'uses' => 'Location\CostConfigurationsController@store']);
  Route::group(['prefix' => '{costConfiguration}'], function () {
    Route::put('/', ['as' => 'update', 'uses' => 'Location\CostConfigurationsController@update']);
  });
});

. . .
```
The parameter costConfiguration is set to the passed integer from the route not the model instance as expected.

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by Hooolm** [comment]
@Dylan-DPC yeah you are right. Although i have found a solution using the explicit model binding. I would just ensure that this is in fact not a bug.

**Comment by Dylan-DPC** [comment]
@Hooolm you are not binding any parameter to it. You can look at the docs for further info. Also do close this issue :smiley:
