### ISSUE TITLE
How I can use wherePivot in controller

### ISSUE THREAD

**Issue by zohaibniaz** [laravel/framework#21758]
- Laravel Version: 5.4
- PHP Version: 7
- Database Driver & Version:

Description:
I am using pivot columns in manytoMany relationships.
when i use wherePivot('column', '=', 'val') in relationship method of model. Its working fine.
But i need to make 'val' dynamic. It might be 1,2,3 etc.
I want to do it in controller but its not working.

$model->{relationMethod}()->wherePivot() also not working
How i can use dynamic values in where pivot???
@greut @ceejayoz @wuwx @phaza @gslin

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
