### ISSUE TITLE
PostgresGrammar Geography vs Geometry

### ISSUE THREAD

**Issue by leigeber** [laravel/framework#21754]
- Laravel Version: 5.5.18
- PHP Version: 7.1
- Database Driver & Version: PostgreSQL 9.6

### Description:

There was a recent addition to the PostgresGrammar to add some geometry-related columns which we were previously handling in our own custom grammar extension. At first glance the new code looked like it would replace what we had built but after testing it out we realized that geography is being used instead of geometry which we use now causing issues after we re-ran some migrations.

I would argue that is a pretty opinionated assumption and most applications may be better served with geometry since more data might be sourced as such and more functions are available on the geometry type without having to cast as such first or do other workarounds. Geography is also more resource intensive in general. I am admittedly not a GIS expert through so feel free to call me out on any of that.

We're back to extending the grammar for the time being but I'm assuming this may trip up other developers at some point. Is this something you are open to being configurable with a modifier, attribute, or some other approach?

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. This isn't a bug so you can open a proposal in the laravel/internals repo
