### ISSUE TITLE
php artisan db:seed [ReflectionException] Class DatabaseSeeder does not exist Version [v5.5.18]

### ISSUE THREAD

**Issue by MatteoOreficeIT** [laravel/framework#21753]
- Laravel Version: v5.5.18
- PHP Version: 7.0.9
- Database Driver & Version: pdo_mysql

### Description:

In a tipical collaboration scenario php artisan db:seed needs to be preceeded by composer dumpautoload because a git pull could fetch seeders are not yet in your autoloaders.

A *warning* in the doc could show this need.

### Steps To Reproduce:

1. Team member A execute `artisan make:seeder NewSeeder`
2. Team member A config added NewSeeder
3. Team member A commit and push on central repo
4. Team member B execute git pull
5. Team member B see only a seeder has been added
6. Team member B execute `artisan db:seed`
7. Team member B receives the following error

```
[ReflectionException] Class NewSeeder does not exist
```

**Comment by ntzm** [comment]
Developers should know to run `composer dump` when new classes are added

**Comment by Dylan-DPC** [comment]
This isn't a bug and can be closed
