### ISSUE TITLE
Redis queue prefix

### ISSUE THREAD

**Issue by Snake231088** [laravel/framework#21764]
- Laravel Version: 5.5
- PHP Version: 7.1

### Description:
add possibility to specify a prefix for queues with redis driver. Now the key on redis is:
queues:#QUEUE_NAME#
Thx

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. This isn't a bug so you can open a proposal in the laravel/internals repo

**Comment by Snake231088** [comment]
Ok sorry!
