### ISSUE TITLE
Notification Driver should throw an exception when a route cannot be found

### ISSUE THREAD

**Issue by ianhawes** [laravel/framework#21768]
- Laravel Version: 5.4.36
- PHP Version: 7.1.3

### Description:
The Notification driver silently ignores notifications if a routing method isn't defined. For example, for Slack notifications, the `routeNotificationForSlack()` method must be defined on the `Notifiable` entity. If that method is not created, or incorrectly created on the Notification itself, the notification is discarded entirely without warning or error.

### Steps To Reproduce:
1. Create a new Notification.
2. Do not define a routing method on the `Notifiable` entity (for example, the `User` model).
3. Attempt to trigger the notification.

**Comment by Dylan-DPC** [comment]
Version 5.4 is no longer supported. Do check if issue persists on 5.5 :smiley:

**Comment by tillkruss** [comment]
Could you please post sample code?

**Comment by themsaid** [comment]
That would be a breaking change, feel free to open a PR for version 5.6
