### ISSUE TITLE
Can't get property of header

### ISSUE THREAD

**Issue by deiks** [laravel/framework#21762]
- Laravel Version: 5.5
- PHP Version: 7

### Description:

Hey,

For some reason I can't get data sent via header.
What I'm trying is to send "Authorization" over header.
I tried with `$request->header('Authorization', null)` and `$request->headers->get('Authorization', null)` and only what I got is `null`.

Strange thing is that it actually sometimes works fine, and later when I try it, won't work.
I'm sending it while I'm logged in to save post with async call.
Also using Google Chrome and can see it in Request Headers section. And Authorization token is correct.

Best regards.

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
