### ISSUE TITLE
Using new Responsable interface causes exception in ThrottleRequests Middleware

### ISSUE THREAD

**Issue by jamesaspence** [laravel/framework#21775]
- Laravel Version: 5.5.3
- PHP Version: 7.1.3
- Database Driver & Version:

### Description:
I am using the new `Responsable` (`\Illuminate\Contracts\Support\Responsable`) interface to format my JSON responses on several API endpoints. After converting my endpoints to use the new interface, I received the following exception from `ThrottleRequests`: "Type error: Argument 1 passed to Illuminate\Routing\Middleware\ThrottleRequests::addHeaders() must be an instance of Symfony\Component\HttpFoundation\Response, instance of App\Http\Responses\API\APIResponse given" (`App\Http\Responses\API\APIResponse` being my `Responsable` implementation).

Is `Responsable` not quite ready to be used yet? I noticed it wasn't in the docs anywhere, so maybe I'm just a bit early to the party?

### Steps To Reproduce:
1) Create implementation of `Responsable` that returns `response()->json()` from `toResponse`
2) Create a controller with the `ThrottleRequests` middleware registered.
3) Have the controller return your new `Responsable` implementation.

**Comment by themsaid** [comment]
Can't replicate, calling `toResponse ` will return a `Illuminate\Http\JsonResponse` instance which is a Symfony Response.

Please post your code to help us replicate the exact issue.

**Comment by themsaid** [comment]
Looks like you're overriding the default response creation somewhere in your code, please try to replicate on a fresh laravel app first.

Closing for now but feel free to ping me if you could replicate in a fresh laravel app.

**Comment by jamesaspence** [comment]
Thanks for the quick response! I definitely thought this was peculiar, as the new resources uses this interface. I will do some further testing on a fresh instance, and see if I can diagnose the issue on my end. Will update when I have more details.

**Comment by lukepolo** [comment]
@jamesaspence 

Im getting this error now, what did you find out?

**Comment by jamesaspence** [comment]
I unfortunately don't have much of an update to this - I haven't had any time to work on this project since I posted this issue :/ I should have some time coming up within the next week or so, I will attempt to come back and update at this point.

@lukepolo do you get the error in a new project, or an existing project? We can perhaps compare dependencies and see if there's some sort of culprit in there.

**Comment by lukepolo** [comment]
I had a huge error in my middleware, where somehow it was returning `true` instead of `next()` request and was able to fix it by making sure it returns `next`.

**Comment by jamesaspence** [comment]
Hmm, I'll ensure it's not something like that on my end. There's some custom middleware in our system and it might be causing this issue.
