### ISSUE TITLE
unable to test filesystem temporaryUrl

### ISSUE THREAD

**Issue by saqueib** [laravel/framework#21773]
- Laravel Version: 5.5.11
- PHP Version: 7.1
- Database Driver & Version: MySQL

### Description:
I have written some test to verify that a file exists on s3 and download when tried to test `Storage::disk('s3')->temporaryUrl($url, $urlExpires);` It gives 500 error with this msg **but the code works when test by the browser**.

```
This driver does not support creating temporary URLs
```

#### Test
```php
Storage::fake('s3');

// Create attachment
$attachment = Attachment::create([
    'name' => 'PDF Doc',
    'url' => Storage::disk('s3')->put(
        'attachments', 
        UploadedFile::fake()->create('document.pdf'), 
    1000)
]);

Storage::disk('s3')->assertExists($attachment->url);
...
$this->actingAs($user)
    ->get(route('attachments.download', $attachment->id))
    ->assertRedirect()
// it fails with with 500
```

#### Implementaion
```php
$url = Attachment::find($id)->url;

if( Storage::disk('s3')->exists($url) ) {
    // link expiration time
    $urlExpires = Carbon::now()->addMinutes(10);

    try {
        $tempUrl = Storage::disk('s3')->temporaryUrl($url, $urlExpires);
        return redirect($tempUrl);
    } catch ( \Exception $e ) {
        // Unable to test temporaryUrl, its giving driver dont support it issue.
        return response($e->getMessage());
    }
}
```

**One more question?**
Is there any way to customize the URL generated by `temporaryUrl()`, problem is downloaded filename is some random string `rlbPsVUhqubaXGoEQk96wjPXfQTqurJvNgVjRMZ8.doc` which is not very good, I like to customize the name of file to something like `project-details.doc` etc 🚶

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.

**Comment by daraul** [comment]
Can't we just return the $path if the filesystem adapter doesn't support temporary URLs, instead of throwing an exception?

**Comment by ArondeParon** [comment]
I just experienced the same issue. We solved it by doing something like this:

```php
        Storage::shouldReceive('cloud')->twice()->andReturn(new class() {
            public function temporaryUrl() {
                return 'foo';
            }
        });
```

**Comment by fgilio** [comment]
Hi @driesvints, could you take a second look at this?  
Just returning a URL or a fake singed URL when faking a disk seems like a good solution.

**Comment by driesvints** [comment]
We don't support this Laravel version anymore.

**Comment by driesvints** [comment]
I think it's best that you send in a PR if something is broken here. There's a good workaround this right above here.

**Comment by korridor** [comment]
I had the same problem and the solution of @ArondeParon didn't work for me, because I didn't want to mock all `Storage` function calls. I just wanted to mock the `temporaryUrl` function call and still use the other `Storage::fake()` capabilities.
I came up with the following solution:
```php
$fakeFilesystem = Storage::fake('somediskname');
$proxyMockedFakeFilesystem = Mockery::mock($fakeFilesystem);
$proxyMockedFakeFilesystem->shouldReceive('temporaryUrl')
    ->andReturn('http://some-signed-url.test');
Storage::set('somediskname', $proxyMockedFakeFilesystem);
```

Now `Storage::disk('somediskname')->temporaryUrl('somefile.png', now()->addMinutes(20))` returns `'http://some-signed-url.test'` and I can actually store files and assert that there exist without any further changes.

I know it's not the cleanest solution, but it works well for me and I haven't found a better solution that fits my needs yet. Hope this helps anyone.

**Comment by pildit** [comment]
where did you add this ?

**Comment by korridor** [comment]
@pildit At the beginning of the test or if you want this in multiple tests in the `setUp` function.

**Comment by apsyriodis** [comment]
> I had the same problem and the solution of @ArondeParon didn't work for me, because I didn't want to mock all `Storage` function calls. I just wanted to mock the `temporaryUrl` function call and still use the other `Storage::fake()` capabilities. I came up with the following solution:
> 
> ```
> $fakeFilesystem = Storage::fake('somediskname');
> $proxyMockedFakeFilesystem = Mockery::mock($fakeFilesystem);
> $proxyMockedFakeFilesystem->shouldReceive('temporaryUrl')
>     ->andReturn('http://some-signed-url.test');
> Storage::set('somediskname', $proxyMockedFakeFilesystem);
> ```
> 
> Now `Storage::disk('somediskname')->temporaryUrl('somefile.png', now()->addMinutes(20))` returns `'http://some-signed-url.test'` and I can actually store files and assert that there exist without any further changes.
> 
> I know it's not the cleanest solution, but it works well for me and I haven't found a better solution that fits my needs yet. Hope this helps anyone.
> 
> **UPDATE:** If you need the path of the file in the temporary URL you can use this code instead:
> 
> ```
> $fakeFilesystem = Storage::fake('somediskname');
> $proxyMockedFakeFilesystem = Mockery::mock($fakeFilesystem);
> $proxyMockedFakeFilesystem->shouldReceive('temporaryUrl')
>    ->andReturnUsing(function (string $path, \DateTimeInterface $expiration, array $options = []) {
>       return 'http://some-signed-url.test/' . $path;
>    });
> Storage::set('somediskname', $proxyMockedFakeFilesystem);
> ```

Still works. Thanks
