### ISSUE TITLE
Find method not works properly

### ISSUE THREAD

**Issue by Mattiullah** [laravel/framework#21780]
- Laravel Version: 5.5.17
- PHP Version: 7.0
- Database Driver & Version: Mysql

### Description:
Find method not works properly. while i am using it with various Models
for Example:
$articles=Posts::find(5); // returns only 1 object
$articles=Posts::find(5)->get(); // returns all objects (included those objects that's id is different )

**Comment by sisve** [comment]
Posts::find($id) returns a Post. Then you call Post::get() via magical methods (__call, __callStatic) that executes another database query. That is just how Eloquent works.

    $post = new Post();
    $allPosts = $post->get();

**Comment by Mattiullah** [comment]
@sisve please check above mentioned code...both lines are different to each others.

**>>> $a=App\comments::find(1)->all()** 
returns

```
=> Illuminate\Database\Eloquent\Collection {#776
     all: [
       App\comments {#777
         id: 1,
         cbody: "comments1",
         created_at: "2017-10-19 04:00:21",
         updated_at: "2017-10-19 04:00:21",
       },
       App\comments {#778
         id: 2,
         cbody: "comments 2",
         created_at: "2017-10-22 07:36:50",
         updated_at: "2017-10-22 07:36:50",
       },
       App\comments {#779
         id: 3,
         cbody: "comments 3",
         created_at: "2017-10-22 07:46:54",
         updated_at: "2017-10-22 07:46:54",
       },
       App\comments {#780
         id: 4,
         cbody: "comments 4",
         created_at: "2017-10-18 00:00:00",
         updated_at: "2017-10-11 00:00:00",
       },
       App\comments {#781
         id: 6,
         cbody: "comments 5",
         created_at: "2017-10-22 12:03:06",
         updated_at: "2017-10-22 12:03:06",
       },
       App\comments {#782
         id: 7,
         cbody: "comments 6",
         created_at: "2017-10-22 12:03:41",
         updated_at: "2017-10-22 12:03:41",
       },
     ],
   }

```

but i am searching all objects contains id =1 but it shows these objects

**Comment by Dylan-DPC** [comment]
This is not a bug. since as sisve explained, this will create a new query
