### ISSUE TITLE
How to handler PDOException in report method

### ISSUE THREAD

**Issue by axot** [laravel/framework#21789]
- Laravel Version: 5.5.0
- PHP Version: 7.1.7
- Database Driver & Version: MySQL 5.7

Assume this code:
```php
class Handler extends ExceptionHandler
{
    public function report(Exception $exception)
    {
        if ($this->shouldntReport($exception)) {
            return;
        }
        $this->logErrorToDatabase($exception);
    }

    protected function logErrorToDatabase(Exception $exception)
    {
        try {
            db()->insert('whatever');
        } catch (Exception $_) {
            logger()->critical($_);
        }
    }
}
```

We want catch `PDOException` when `insert` method throws. Or report method will be an infinite loop. But actually in `ConnectionFactory.php`
https://github.com/laravel/framework/blob/5.5/src/Illuminate/Database/Connectors/ConnectionFactory.php#L184

`PDOException` was handled there, any way to solve this case? Thank you.

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
