### ISSUE TITLE
where('foo',null) is ignored

### ISSUE THREAD

**Issue by salarmehr** [laravel/framework#21784]
- Laravel Version: 5.5
- PHP Version:
- Database Driver & Version:

if `$token=null` then `User::where('token',$token)->first()` acts as `User::first()` and silently ruins the first user record.  

An over-smart person may say this is a feature and not a bug and he may close the issue quickly! But I expect adding a constrain to a query make a different output instead of silently breaks the app and impose a lot of debugging time.  

It should generate `select * from users where token=null` that always returns empty result set that is compatible with the way the php code is expected to work. if no token provided no user should  be returned. (the over-smart guy may say you need to check that yourself all over the appfor all `where` parameters, come on buddy!

**Comment by Upperfoot** [comment]
You must sanitise your input, your query is returning exactly what it was asked to return. 

What if I want to return all results that have a column that is null, what if I want to see how many users have no name?

`User::where('name', null)->get()`

What you are proposing is a breaking change, you are asking the query builder to always return no results if you pass null to the where clause and are executing a query when it doesn't need to be called, I would have done the following.

`$user = !empty($token) ? User::where('token',$token)->first() : null;`

It's not being over-smart, it's being logical and sensible.
