### ISSUE TITLE
Request $request->file('file') return null when upload files from Angular 4 Component

### ISSUE THREAD

**Issue by ipula** [laravel/framework#21785]
- Laravel Version: 5.4.
- PHP Version:5.6
- Database Driver & Version: mysql

When i use $_FILES it show the data, but when i use $request->file('file') it return null

In Angular 4 there is no need to use multipart/form-data ContentType

I need answers to this
Thankz

**Comment by bbashy** [comment]
Look at https://github.com/laravel/framework/issues/13457

**Comment by ipula** [comment]
still not working... i add headers.append('Content-Type', 'x-www-form-urlencoded'); to headers

**Comment by bbashy** [comment]
What does it look like in Network tab?

**Comment by ipula** [comment]
------WebKitFormBoundaryBMkkCBnexJpXEpyP
Content-Disposition: form-data; name="uploadFile"; filename="Customer Credit Report.xlsx"
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet


------WebKitFormBoundaryBMkkCBnexJpXEpyP--

this is the request payload

**Comment by bbashy** [comment]
I see you've got `uploadFile` as the input name but have `$request->file('file')` as your reading method. They should match.

**Comment by ipula** [comment]
yes. i used that way as common name i used file just for the this issue

**Comment by bbashy** [comment]
Please keep your code consistent because I'm looking over it from my point of view.

**Comment by ipula** [comment]
ok..

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by bbashy** [comment]
@Dylan-DPC Funny thing, they have as well... https://laracasts.com/discuss/channels/laravel/request-request-filefile-return-null-when-upload-files-from-angular-4-component

**Comment by Dylan-DPC** [comment]
then it is better to stick to the forums. This repo is for bug tracking

**Comment by ipula** [comment]
is this not a bug? i think it is a bug... this [#13457](https://github.com/laravel/framework/issues/13457) still going  although it closed..

**Comment by themsaid** [comment]
I'm not familiar with `Angular 4` upload process, since you're posting an issue on the laravel repository please share steps to replicate using plain code or at least enough information with someone having a fresh laravel app with no angular to replicate :)

Otherwise please use the forums for help.

**Comment by ipula** [comment]
its easy to close issues by the way @themsaid .Thank you for giving nothing... Its not about Angular 4 its about laravel Request class.. I think I show the request payload. Its contain the file but laravel not get the file. If u do not to fix this just do not comment or close.. So you are doing nothing for to fix this bug

**Comment by bbashy** [comment]
@ipula If it's not Angular related, post code to reproduce it using a form. All my uploads work fine.

**Comment by themsaid** [comment]
@ipula try this: https://stackoverflow.com/questions/41750675/angular-file-upload-via-laravel-controller

Problem here is the report is vague in a way we can't really do anything to fix, I'll keep sharing links I found on google hoping it would help you find the issue :)

Instead it'd be better if you do your research online, try to understand what's going on, and then open an issue saying something like:

File uploaded, headers are 1,2,3, expected X but got Y. Now I can open a up a fresh laravel App and try it see if it's something with Laravel or maybe file is too large so it was lost, maybe wrong encoding, etc...

This kind of help I do provide on the forums, but try to keep this space for real bugs so it's easier for us to separate bugs from questions.

**Comment by themsaid** [comment]
Closing an issue doesn't mean I'm not willing to help, it's just me saying this isn't a confirmed bug in the framework :)

**Comment by ipula** [comment]
look at this [#13457](https://github.com/laravel/framework/issues/13457)  issue even though it closed. still new comments. not for me some others have this issue.. ok. i will look in forums..

**Comment by Dylan-DPC** [comment]
@ipula the reason why we have forums is so that you can seek help there instead of clogging this issue board which makes it difficult for us to spot & solve bugs which are caused by the framework.

**Comment by iamchathu** [comment]
This is a bug in Laravel because $FILE shows file is there. Is Laravel support REST APIs It should be able to handle file upload as HTTP request. Now both issues have been closed without solution.

**Comment by Hraju07** [comment]
Hi, please delete Content-type header while making REST API call in angular... it will automatically create... Please find the attachment for more details.. it will create headers with content type ( Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryzUjwtsgKra12edJv)
![angular_header](https://user-images.githubusercontent.com/49362441/55681727-6dba8080-5947-11e9-9693-5a3c8f87d5b0.PNG)
![laravel_controller](https://user-images.githubusercontent.com/49362441/55681728-6e531700-5947-11e9-9c62-fd0ffb5be2db.PNG)
![php_laravel_issue](https://user-images.githubusercontent.com/49362441/55681729-6e531700-5947-11e9-832a-1d6155cf2ccc.PNG)
![header_file](https://user-images.githubusercontent.com/49362441/55681774-e7526e80-5947-11e9-82a5-15c0c01c17e5.PNG)

**Comment by CodeSuite** [comment]
@Hraju07 Reading your comment made me realize i had global header defined. Thanks bud!
