### ISSUE TITLE
factory(MyClass::class)->create()->each(...) can be called more than once

### ISSUE THREAD

**Issue by zhekaus** [laravel/framework#21782]
- Laravel Version: 5.5.#
- PHP Version: 7.1.10
- Database Driver & Version: MySQL PDO 7.1.10

### Description:

If you call factory without specifying number of object to create, `each` method will be called for every row in the data-set. 
I think, 1 count must be as default.

### Steps To Reproduce:
`esch` will be called more than one time, if table of MyClass has more than one row:
```
factory(MyClass::class)->create()->each(function ($row) {
});
```

**Comment by devcircus** [comment]
looks to be the same situation as #21780. When you don't specify a quantity, an instance is returned. This is just how eloquent works. It would be the same as calling 'each' on an empty instance of the model. This is the same functionality that allows us to inject an instance of a model, then call builder methods on it. 

To get the behavior you're wanting, you need to specify the number of instances you would like. This way, you'll receive a Collection that you can iterate over.
