### ISSUE TITLE
show error Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by dalingng** [laravel/framework#21799]
- Laravel Version: v5.2.45
- PHP Version:7.2
- Database Driver & Version:

### Description:
use the https://github.com/JosephSilber/bouncer
run php code
Bouncer::allow($role)->to($permission);
show the 
[ErrorException]
count(): Parameter must be an array or an object that implements Countable

error on the code
src/Illuminate/Database/Eloquent/Builder.php
1185 line

**Comment by themsaid** [comment]
5.2 is not supported anymore, please upgrade.

**Comment by dalingng** [comment]
@themsaid OK thank
