### ISSUE TITLE
TypeError: ParseError being passed to Whoops Inspector constructor originating from blade parser or compiler

### ISSUE THREAD

**Issue by vmantese** [laravel/framework#21791]
- Laravel Version: 4.2.20
- PHP Version: 7.0.24
- Database Driver & Version:
Postgres 9.3
### Description:

A ParseError is being passed to Whoops resulting in a 
`Type error: Argument 1 passed to Whoops\Exception\Inspector::__construct() must be an instance of Exception, instance of ParseError given, called in <DocumentRoot>vendor/filp/whoops/src/Whoops/Exception/Inspector.php on line 80`

### Problem Origination

Following the advice of https://stackoverflow.com/questions/24184925/unexpected-endforeach-in-blade-template/ my parse error comes from the fact that I have a syntax error in a Blade. THIS issue is not the syntax error itself (or the downstream ParseError) but the fact that it is being passed to Whoops before being wrapped as a FatalThrowableException.

The view is being parsed and throwing a syntax error. (<DocumentRoot>/vendor/nikic/php-parser/lib/PHPParser/Parser.php) this is caught my Monolog:

local.ERROR: Internal server error. {"file":"<DocumentRoot>/app/storage/views/87a20fe6020d4f76cf281982e6ca9475","line":32,"message":"syntax error, unexpected end of file, expecting elseif (T_ELSEIF) or else (T_ELSE) or endif (T_ENDIF) (View: <DocumentRoot>/app/views/pages/page.blade.php)"}

From there a PHPParser_Error(at least according to PHPParser docs) is being passed but I'm not sure if it is later being converted to my problem ParseError.

### When it doesn't happen

Intentionally created ParseErrors (such as typo in routes.php) properly result in a ParseError which is wrapped as a FatalThrowableError before being passed to Whoops. Testing throughout the codebase suggests this error is limited to view syntax errors.

### Steps To Reproduce:
In a blade template. intentionally add a nested @endif without a preceding space.
Example
`<div class="content @if($layout === 'layouts.landingNoHeaderFooter')underFakeHeader@endif">`

Additional Package Specifications

Whoops 1.0.10

**Comment by vmantese** [comment]
OK - so this is a know error within the Whoops package. Just use Whoops 2.1.12 (alias it in your composer.json) with no found conflicts with Laravel 4.2.20 as of yet.

see
https://github.com/filp/whoops/pull/284

**Comment by pythondev1** [comment]
> OK - so this is a know error within the Whoops package. Just use Whoops 2.1.12 (alias it in your composer.json) with no found conflicts with Laravel 4.2.20 as of yet.
> 
> see
> [filp/whoops#284](https://github.com/filp/whoops/pull/284)

Hot to alias it in composer?

**Comment by blueminded** [comment]
I'm having this issue, how can I solve it?
Type error: Argument 1 passed to Whoops\Exception\Inspector::__construct() must be an instance of Exception, instance of ParseError given, called in /vendor/filp/whoops/src/Whoops/Exception/Inspector.php on line 80
