### ISSUE TITLE
Notifications created_at

### ISSUE THREAD

**Issue by EazyServer** [laravel/framework#21805]
- Laravel Version: 5.5.*
- PHP Version: 7.1
- Database Driver & Version: Mysql

### Description:
Laravel [Notifications](https://laravel.com/docs/5.5/notifications) is such a useful tool! However it is not as versatile as standard Models.

Would it be possible to make laravel notification timestamps such as `created_at` property editable?

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue
