### ISSUE TITLE
Eloquent global scopes may cause "refresh" to throw an error

### ISSUE THREAD

**Issue by monooso** [laravel/framework#21809]
- Laravel Version: 5.5
- PHP Version: 7.1.10

### Description:
Eloquent throws an error if you call `refresh` on a model instance which is excluded by a default global scope.

### Steps To Reproduce:
Taking the "age" global scope used in [the Laravel documentation](https://laravel.com/docs/5.5/eloquent#global-scopes) as our starting point, assume we have the following classes:

```php
// app/User.php
<?php

namespace App;

use App\Scopes\AgeScope;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;

class User extends Model
{
    /**
     * The "booting" method of the model.
     *
     * @return void
     */
    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope('age', new AgeScope);
    }
}

// app/Scopes/AgeScope.php
<?php

namespace App\Scopes;

use Illuminate\Database\Eloquent\Scope;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;

class AgeScope implements Scope
{
    /**
     * Restrict results to users aged 18 or over.
     *
     * @param Builder $builder
     * @param Model  $model
     */
    public function apply(Builder $builder, Model $model)
    {
        $builder->where('age', '>=', 18);
    }

    /**
     * Extend the query builder with the needed functions.
     *
     * @param Builder $builder
     */
    public function extend(Builder $builder)
    {
        $this->addWithYouths($builder);
    }

    /**
     * Adds the 'withYouths' extension to the query builder.
     *
     * @param Builder $builder
     */
    protected function addWithYouths(Builder $builder)
    {
        $builder->macro('withYouths', function (Builder $builder) {
            return $builder->withoutGlobalScope($this);
        });
    }
}
```

Our database contains a 16 year old user with an ID of 999, who we retrieve using the `withYouths` builder macro:

```php
$bae = User::withYouths()->where('id', 999)->firstOrFail();
```

Having performed some changes to the `$bae` model instance, we now want to refresh the data, so we call the `refresh` method. This throws an error, because `$bae` is excluded by the "age" global scope.

```php
$bae->refresh();    // Error.
```

## Expected Behaviour:
Given that we have already retrieved the model instance, and are simply seeking to refresh the data, I would expect the `refresh` method to ignore any global scopes.

## Proposed Solution:
Update the `Model::refresh` method as follows (I'm happy to put this in a pull request, if it helps):

```php
public function refresh()
{
    if (! $this->exists) {
        return $this;
    }

    $this->setRawAttributes(static::newQueryWithoutScopes()
        ->findOrFail($this->getKey())
        ->attributes
    );

    $this->load(collect($this->relations)->except('pivot')->keys()->toArray());

    return $this;
}
```

**Comment by themsaid** [comment]
Thanks for the report, I've fixed that in: https://github.com/laravel/framework/pull/21815
