### ISSUE TITLE
forceRootUrl adds prefix to helpers, no prefix to routes

### ISSUE THREAD

**Issue by Sjoerrdd** [laravel/framework#21802]
- Laravel Version: 5.5.* (latest version)
- PHP Version: 7.1

### Description:
```forceRootUrl()``` doesn't prefix the routes, but if I prefix the routes manually, the ```asset()``` and the ```url()``` helper has the prefix 2 times.

url: "example.com/laravel"
asset helper url: "example.com/laravel/laravel"

### Steps To Reproduce:
add  ```\URL::forceRootUrl("https://example.com/laravel");``` to AppServiceProvider.php (boot)

**Comment by sisve** [comment]
Why would URL::forceRootUrl modify routes at all? It only modifies what the URL facade (and UrlGenerator and similar services) does. You can do what you want by grouping all your routes in a prefix, easiest done in RouteServiceProvider.

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
