### ISSUE TITLE
[PostgreSQL] inRandomOrder() + distinct() throws ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select   

### ISSUE THREAD

**Issue by PhPPgAdminBug** [laravel/framework#21801]
- Laravel Version: 5.4
- PHP Version: 7.1
- Database Driver & Version: PostgreSQL 9.6

### Description:
When using PostgreSQL, there is ERROR in distinct random select.

### Steps To Reproduce:
This query throws error:
```
User::select( DB::raw('DISTINCT(user.id) as user_id'), 'users.role_id')
//                    ->distinct()
                ->join('roles', 'users.role_id', '=', 'roles.id')
                ->sharedLock() 
                 ->orderByDesc('user_id')
                ->inRandomOrder()
                ->limit($limit)
                ->get();
```

**And this:**
```
User::select( 'user.id as user_id'), 'users.role_id')
                   ->distinct()
              ->join('roles', 'users.role_id', '=', 'roles.id')
                ->sharedLock() 
                 ->orderByDesc('user_id')
                ->inRandomOrder()
                ->limit($limit)
                ->get();
```

**And this:**
```
User::select( DB::raw('SELECT DISTINCT(user.id) as user_id'), 'users.role_id')
->join('roles', 'users.role_id', '=', 'roles.id')
                ->sharedLock() 
                 ->orderByDesc('user_id')
                ->inRandomOrder()
                ->limit($limit)
                ->get();
```

**this**
`->select( DB::raw('DISTINCT ON(users.id) as user_id'), `

And so on....
Also we tried use queries DB::table('users')->select('')... no luck.
And tried to use random() from PGSQL functions.

**But if we remove**
` ->inRandomOrder()`
most of queries work fine, but selecting not randomly. 

**Main ERROR:**
`SQLSTATE[42P10]: Invalid column reference: 7 ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list↵LINE 1: ...deleted_at" is null order by "user_id" desc, RANDOM() l...↵   `

 Still trying to figure out how to do distinct rand query.

**Comment by lancepioch** [comment]
Does the error still occur if you use `User::select('users.role_id')->selectRaw('DISTINCT(user.id) as user_id')` instead?
