### ISSUE TITLE
AppNameCommand fails to update auth.php users model

### ISSUE THREAD

**Issue by StarkNZ** [laravel/framework#21816]
I'm not sure whether this is intended, but according to the command, it should be replaced with the new namespace.

I've seen this occur across many Laravel versions now (from L5).

under ``config.auth.providers.users.model`` the namespace is not replaced with the new value.

I always thought it was an intended feature until a discussion popped up about 10 minutes ago, so i thought i'd look at the command.

**Comment by themsaid** [comment]
I just tested and it's replaced, make sure the original value is not altered before the commands runs.

**Comment by StarkNZ** [comment]
Yep good spotting out @themsaid - And yet the command class specifically looks for the current namespace and then the user model. I had a models directory.

Thanks a lot.
