### ISSUE TITLE
Cookie facade broken?

### ISSUE THREAD

**Issue by PhPPgAdminBug** [laravel/framework#21819]
- Laravel Version: 5.4
- PHP Version: 7.1
- Database Driver & Version: PostgreSQL

### Description:
Cookie facade does not work correctly in View blade file.

### Steps To Reproduce:
```
{{ dd( cookie('menuShow')) }}
{{ dd(Request::cookie('menuShow')) }}
{{ dd(Cookie::get('menuShow')) }}
{{ dd($_COOKIE['menuShow']) }}
{{ dd($_COOKIE) }}
```

Only last 2 methods work fine, but not Laravel's wrapper. Checked with clear 5.4 version.

**Comment by Dylan-DPC** [comment]
5.4 is no longer supported.

**Comment by patrickomeara** [comment]
@PhPPgAdminBug I ran into something similar, are you encrypting the value before setting it? Laravel uses `EncryptCookies` middleware out of the box.
