### ISSUE TITLE
Queue fails for array_key_exists()

### ISSUE THREAD

**Issue by luizguilhermefr** [laravel/framework#21823]
- Laravel Version: 5.5.19
- PHP Version: 7.0.24
- Database Driver & Version: predis
- Redis Server 3.0.7

I am trying to broadcast events using `redis` both for broadcast itself and as queue.

However, when firing `event(new MyEvent($data));` or executing `php artisan queue:listen` I get:

```
array_key_exists() expects parameter 2 to be array, null given
```

**[Full trace here](https://pastebin.com/aZ3UNJ3c)**

I have configured `config/queue.php` `connections` array with default configuration

```php
'redis' => [
        'driver' => 'redis',
        'connection' => 'default',
        'queue' => 'default',
       'retry_after' => 90,
],
```

and in `config/database.php` I added:

```php
'redis' => [
            'client' => 'predis',
            'default' => [
            'host' => env('REDIS_HOST', 'localhost'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => 0,
        ],
 ],
```

**Comment by Dylan-DPC** [comment]
Can you share us with steps to reproduce this bug? Also some more details about where it is erroring out? (stack trace)

**Comment by luizguilhermefr** [comment]
@Dylan-DPC the trace is already attached.

The steps was:

1. Create a laravel app

2. Install `predis`

3. Configure the `redis` database connection`.

4. Configure the `redis` at queues.

5. Create an event with `php artisan make:event NewEvent` and configure with `ShouldBroadcast` interface

6. Fire the event or run `php artisan queue:listen`

**Comment by Dylan-DPC** [comment]
Yeah i saw the text file at the end. But i don't think people will be comfortable downloading a file. If you want you can use something like [pastebin](https://pastebin.com/)

**Comment by luizguilhermefr** [comment]
https://pastebin.com/aZ3UNJ3c

**Comment by sisve** [comment]
1. What is the value of $config in [RedisServiceProvider::register](https://github.com/laravel/framework/blob/v5.5.19/src/Illuminate/Redis/RedisServiceProvider.php#L27)?
2. Does the error occur if you only use redis as a database?
3. Does the error occur if you only use redis as a queue driver?
4. Do you have a cached configuration, and if so, have you rebuilt it after your changes with `php artisan config:cache`?

**Comment by luizguilhermefr** [comment]
Realized the problem. At `RedisServiceProvider::register` the value of `$config` was null. I double checked the connection and compared with a fresh Laravel install and realized that `redis` shouldn't be in `connections` array, but in the root array. Fixed and worked.

**Comment by Dylan-DPC** [comment]
Great. It is recommended to test the same issue on a new repository before creating a issue (to report a bug).
