### ISSUE TITLE
->float('foo') is creating a double column?

### ISSUE THREAD

**Issue by Jakobud** [laravel/framework#21827]
- Laravel Version: 5.5.18
- PHP Version: PHP 7.1.10-1+ubuntu16.04.1+deb.sury.org+1
- Database Driver & Version: 5.7.19-0ubuntu0.16.04.1 (Ubuntu)

(This is using the latest Laravel Homestead)

### Description:
When I create a migration that uses this:
```
$table->float('population')->unsigned()->default(0);
```
It creates a double (8,2) column in the database. Why isn't it a FLOAT type?

### Steps To Reproduce:
Use `$table->float('population')->unsigned()->default(0);` in a migration.

**Comment by themsaid** [comment]
Please check previous issues and the forums for an answer https://github.com/laravel/framework/search?q=float+double+migration&type=Issues&utf8=%E2%9C%93

**Comment by Jakobud** [comment]
Okay thanks. So I tracked it down to here:

https://github.com/laravel/framework/issues/9103

The guy says its not a bug and to "ask on the forums". It seems like a bug that `typeFloat` returns `typeDouble`:

https://github.com/laravel/framework/blob/master/src/Illuminate/Database/Schema/Grammars/PostgresGrammar.php#L418

Can you comment on why this is? Or explain this?

The reason I am asking is because I am trying to recreate an existing database structure using Laravel migrations. It has to match exactly with the existing tables.

One of those tables has the column described as 
```
`foobar` float unsigned NOT NULL DEFAULT 0,
```
How do I do this with Laravel's migrations if `->float()` always creates a double?

**Comment by themsaid** [comment]
> A double IS a float if you tell the database how many bytes you want there to be.

Check https://laracasts.com/discuss/channels/laravel/schema-float-function-generated-a-double-type

**Comment by fisharebest** [comment]
> A double IS a float if you tell the database how many bytes you want there to be.

This statement has been quoted several times, and I'm not sure what you mean by it.

The only way I know to tell MySQL how many bytes to use for a floating point type is `FLOAT(p)` ([see docs](https://dev.mysql.com/doc/refman/5.7/en/floating-point-types.html)).  This gives you a column with enough precision to store `p` bits of data.

* `FLOAT(1)` ... `FLOAT(23)` are synonyms for `FLOAT`
* `FLOAT(24)` ... `FLOAT(53)` are synomyms for `DOUBLE`.

However, Laravel doesn't support this format at all.  It only supports the `DOUBLE(m,n)` syntax.  This merely rounds data to the specified number of decimal digits before writing it to an (8 byte) double-precision column.
