### ISSUE TITLE
Password reset token is invalid

### ISSUE THREAD

**Issue by devWaleed** [laravel/framework#21822]
- Laravel Version: 5.2 & 5.4
- PHP Version: 5.6.30
- Database Driver & Version: MySQL that comes with xampp 5.6 php

### Description:
I have a fresh installation of Laravel 5.4.* and i have not changed any single character of code. I just changed env data of course. When I click on password reset link and type email. I receive the reset link. When I open the form and submit all details. It says token is invalid.

Here is a stackoverflow question by me explaining same thing with more detail: https://stackoverflow.com/questions/46878287/password-reset-token-is-invalid

I have not run the migration in the new project because I used the old project database which had users/password_resets table created from migrations. So I am using them here as well.

**Comment by jtrod** [comment]
I'm having the same issue... How did you solve it?

**Comment by devWaleed** [comment]
I got this issue resolved by running migrations. Password reset token column had wrong type. It was not storing token correctly due to wrong charset/collation of column. Run migration and it should be fine.

**Comment by jtrod** [comment]
Thank You for the super fast response.. I'll try this!!

**Comment by jtrod** [comment]
Thank you very much. I dropped the password_resets table, and ran just that one migration.
