### ISSUE TITLE
PHPUnit could not load autoload.php fresh project

### ISSUE THREAD

**Issue by penance316** [laravel/framework#21839]
- Laravel Version: 5.5.*
- PHP Version: 7.1.4
- Database Driver & Version: Mysql

### Description:
I have created a new project using laravel cli but when i attempt to run the built-in unit tests I am receiving an error and which prevents the tests from running.

Im not sure if the error is caused by my configuration or not, I am happy to provide as much info as needed to anyone with ideas how to diagnose this issue.

### Steps To Reproduce:
* laravel new test-project
* ./vendor/phpunit/phpunit/phpunit --configuration ./vendor/autoload.php ./tests
* Recieve the following error:
Could not load "/Users/NeroD/Code/PHP/myneilson/vendor/autoload.php".
ParsePI: PI php never end ...
Start tag expected, '<' not found.

thanks

**Comment by ludo237** [comment]
Did you actually open `autoload.php` to check if the tag expected is there or not?

Also I can't replicate this

**Comment by penance316** [comment]
thanks for the reply, yes i have checked the autoload.php file and it seems fine.

Im pretty sure its an issue with my setup but i cant figure out what piece is broken.

<?php
// autoload.php @generated by Composer
require_once __DIR__ . '/composer/autoload_real.php';
return ComposerAutoloaderInited22552180174ec66656859be1be867f::getLoader();

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.

**Comment by lemonhead23** [comment]
--configuration tag needs to be a XML File

https://phpunit.de/manual/6.5/en/appendixes.configuration.html
