### ISSUE TITLE
first load provider ,not  middlerware

### ISSUE THREAD

**Issue by dev-kang** [laravel/framework#21835]
- Laravel Version: 5.5.4
- PHP Version:7.1
- Database Driver & Version:5.7

### Description:

framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php
``` php 
 /**
     * Resolve request signature.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return string
     * @throws \RuntimeException
     */
    protected function resolveRequestSignature($request)
    {
        if ($user = $request->user()) {
            return sha1($user->getAuthIdentifier());
        }
        if ($route = $request->route()) {
            return sha1($route->getDomain().'|'.$request->ip());
        }
        throw new RuntimeException(
            'Unable to generate the request signature. Route unavailable.'
        );
    }
```

> $user = $request->user()

this code will cause  the program to load provider first,not middleware.  So when i first set some value, it don't effect.

**Comment by themsaid** [comment]
Steps To Reproduce are missing, report is vague, please complete the issue report.

**Comment by vedantseta** [comment]
Even I am facing the same issue, can you @themsaid  please tell me why are global middlewares executed before service providers are loaded ?

**Comment by themsaid** [comment]
That's the how the framework is supposed to work, I suggest that you share your use case in the forums, I'm sure someone will be happy to help you get around this and achieve your goal.
