### ISSUE TITLE
Form Request Validation does not trigger on min:8

### ISSUE THREAD

**Issue by alexgaal** [laravel/framework#21830]
- Laravel Version: 5.5.#
- PHP Version: 7.0.2
- Database Driver & Version: MySQL, 5.7

### Description:
I've used `php artisan make:request SignUpRequest` to create a form request, when I put `'password' => 'required|min:8'` into my rules-function, it does not trigger properly.

```
<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class SignUpRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name'     => 'required',
            'email'    => 'required|email|unique:users,email',
            'password' => 'required|min:8',
        ];
    }
}
```

### Steps To Reproduce:
1. I tried to sign up with an empty password, which successfully failed.
2. I tried to sign up with an password which is too short, e.g. "short", which caused a false positive.

```
public function testPasswordValidation()
{
    $countBefore = User::all()->count();

    $user = factory(User::class)->make()->toArray();

    $response = $this->post('/api/sign-up', $user);
    $response->assertStatus(500);

    $user['password'] = 'short';

    $response = $this->post('/api/sign-up', $user);
    $response->assertStatus(500);

    $this->assertEquals($countBefore, User::all()->count());
}
```

**Comment by Dylan-DPC** [comment]
Hi

I just tested it by placing this code in the framework testcases:
```php
  $v = new Validator($trans, ['foo' => 'short'], ['foo' => 'Min:8']);
        $this->assertTrue($v->fails());
```
and it passes (validation fails). So the validation works fine

**Comment by Dylan-DPC** [comment]
Are you sure it is not calling this validation? https://github.com/laravel/framework/blob/e6e0e618c216d8f21ebb1d0d8ce21876739e29d9/src/Illuminate/Foundation/Auth/AuthenticatesUsers.php#L64

**Comment by alexgaal** [comment]
Oh my god, just close it. I forgot to add `SignUpRequest` to my controller and did not recognised it, because all other tests passed randomly. I am sorry that I disturbed you, good night.

**Comment by Dylan-DPC** [comment]
Haha it is fine. Always test your issue on a fresh repo and on a "generic use case" to confirm whether it is a bug or not. Good night
