### ISSUE TITLE
Note::onlyTrashed()->where('id', $nid)->forceDelete(); inserts a new row when not already soft deleted

### ISSUE THREAD

**Issue by alithestar2000** [laravel/framework#21837]
- Laravel Version: 5.5.13
- PHP Version: 7.1.0
- Database Driver & Version:
  mysql  Ver 14.14 Distrib 5.6.37, for Linux 
### Description:
When using forceDelete on a Note Object which is not soft deleted yet, It inserts a new row in table with garbage data. when the object is soft deleted then calling force delete doesn't create any issue.

**Comment by themsaid** [comment]
Unable to replicate your issue, please include more information, your steps of replication are missing.
