### ISSUE TITLE
[5.5] MethodNotAllowedHttpException displays symfony red Whoops error

### ISSUE THREAD

**Issue by patrickomeara** [laravel/framework#21832]
- Laravel Version: 5.5.19
- PHP Version: 7.1.10

### Description:

I believe Laravel should handle this exception, not symfony. 

The `@return` says this should be `\Illuminate\Http\Response`

```php
/**
 * Render an exception into an HTTP response.
 *
 * @param  \Illuminate\Http\Request  $request
 * @param  \Exception  $exception
 * @return \Illuminate\Http\Response
 */
public function render($request, Exception $exception)
{
    return parent::render($request, $exception);
}
```

A `405.blade.php` will display if it exists.

### Steps To Reproduce:
1. Create a new 5.5 project `laravel new laravel55`
2. Change `Route::get` to `Route::post` in `routes/web.php`
3. Set `APP_DEBUG=false` in `.env`
4. Visit site in browser.

**Comment by themsaid** [comment]
This will prevent the actual issue from appearing to a developer even in development mode, you'll look at your routes and see that the route is defined but still it gives a `Page not found` response.

For suggestions and feature requests please use the https://github.com/laravel/internals repo.
