### ISSUE TITLE
Auto increment without primary key.

### ISSUE THREAD

**Issue by mathieutu** [laravel/framework#21840]
- Laravel Version: 5.5
- PHP Version: 7.1
- Database Driver & Version: Mysql 5.7

### Description:

Hi guys, 
I'm wondering why Laravel is setted to transform automatically any integer with `auto_increment=true` property in primary key..!

This is imo a totally unintuitive way to process.

https://github.com/laravel/framework/blob/d24235a8ee57781391a795f32bc804b504d72323/src/Illuminate/Database/Schema/Grammars/MySqlGrammar.php#L885-L890

I've quickly tried to handle that easily by using `dropPrimary` but for now it doesn't work, we may have to handle that by writing raw queries directly.

### Steps To Reproduce:
```php
$table->uuid('id');
$table->primary('id');
$table->increment('bar')
$table->integer('foo', true);
```

How have you planed to do that, and why to limit standard sql abilities like that ?

Thanks.

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.

**Comment by mathieutu** [comment]
Ok, I'll do that, but I'm seeing that more like a bug, than a new feature request...

**Comment by themsaid** [comment]
It's just a helper, changing this is breaking and maybe not desirable by the majority, that's why moving it to laravel/internals is better.
