### ISSUE TITLE
Column name conflict with $table property

### ISSUE THREAD

**Issue by enghelewa** [laravel/framework#21849]
- Laravel Version: 5.0.35
- PHP Version: 7.0.0

I have a database table named `event` that has a column named `table` to make an eloquent model and used the attribute `protected $table = 'event'`.
The problem happens when using the model to select from database the value of field `table` will always be `event` because it always refers to the attribute `protected $table = 'event'` of the class.
I don't have options to change the table name so I am searching for a workaround.

**Comment by Dylan-DPC** [comment]
Laravel 5.0 :scream: is no longer supported. Kindly check if this issue persists on 5.5

**Comment by enghelewa** [comment]
I think with this same scenario is applicable for every version 😄

**Comment by enghelewa** [comment]
I think these attributes like `$table` must be prefixed like `$laravel_table` or something similar to prevent such scenarios :(

**Comment by Dylan-DPC** [comment]
well there are rarely any coincidences as this. You can't blame the framework if your column name is named the name as a crucial keyword. The better thing to do is name your column something else :stuck_out_tongue:

**Comment by enghelewa** [comment]
In fact I am making an API for a database of an existing system. So its not easy at all to rename the column

**Comment by crynobone** [comment]
```php
$model->getAttribute('table');
```

**Comment by enghelewa** [comment]
@crynobone  That worked fine bro 🥇
