### ISSUE TITLE
PHP Setting is not the same

### ISSUE THREAD

**Issue by fokoz** [laravel/framework#21848]
- Laravel Version: 5.5
- PHP Version: 7.0
- Database Driver & Version: MySQL 5.6

### Description:
I'm running laravel 5.5 on CentOS 6.8 and using plesk as a panel
When I `phpinfo()` on routing index  as follow:

```
Route::get('/', function () {
phpinfo();
});
```
or If I create a php file wherever in the directory and `phpinfo()` 
 it shows the correct setting as I set in plesk php setting, but when I put it in another routing such as:

```
Route::get('/test', function () {
phpinfo();
});
```
it shows base server php setting ( the setting is not working )

What do I miss and how could this be ?

Thank you.

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue
