### ISSUE TITLE
Model::create() returns the model instance but with incorrect ID

### ISSUE THREAD

**Issue by aprilmintacpineda** [laravel/framework#21853]
- Laravel Version: 5.5.19
- PHP Version: 7.0.22-0ubuntu0.16.04.1
- Database Driver & Version: mysql Ver 14.14 Distrib 5.7.19, for Linux (x86_64)

### Description:

- Sign up process.
- Done through ajax request.

I have the following code

```php
$user = User::create([
  'id' => Generator::uniqueId(),
  'email' => $request->email,
  'username' => $request->uname,
  'password' => $request->dpassword,
  'fname' => $request->fname,
  'mname' => $request->mname? $request->mname : null,
  'sname' => $request->sname,
  'sex' => $request->sex,
  'confirm_email_token' => Generator::uniqueToken(),
  /**
   * default account expiry is 3 days prior to date of registration
   * if in 3 days the account is not confirmed, the account is lost until the
   * user decides to reactivate it.
   */
  'confirm_email_token_expiry' => date('Y-m-d', strtotime('+ 3 day')) . ' 00:00:00'
]);
```

When I do

```php
return response()->json($user);
```

I get the user data correctly except that the `$user->id` is `0`, but in the database it's not `0` it's an integer that was returned by `Generator::uniqueId()`.

the users.id is `$table->unsignedInteger('id')->primary()`.

The database transaction completes successfully with no errors, and the data gets inserted to the database.

**Comment by sisve** [comment]
This happens if you're using a custom non-integer primary key, 

> In addition, Eloquent assumes that the primary key is an incrementing integer value, which means that by default the primary key will be cast to an int automatically. If you wish to use a non-incrementing or a non-numeric primary key you must set the public $incrementing property on your model to false. If your primary key is not an integer, you should set the protected $keyType property on your model to string.

Source: https://laravel.com/docs/5.5/eloquent#eloquent-model-conventions

**Comment by sisve** [comment]
Okay, I totally overlooked the part where you said that it was an integer key. Do you still have the problem if you hardcode an identifier in the call to User::create?

Is the id field in your fillable array?

**Comment by sisve** [comment]
We would need your complete User model to debug this further. We would also need a specific value for `Generator::uniqueId()` that we know fails. We need enough code from you to reproduce this by copy/pasting from the issue.

**Comment by aprilmintacpineda** [comment]
Hi There, you're right about the

```php
public $incrementing = false;
```

I set that on my User model and it worked fine. I'm just wondering, I didn't have to manually do that way back on 5.3 and also on 5.4.
