### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::file()

### ISSUE THREAD

**Issue by Suraj-Tiwari** [laravel/framework#21857]
- Laravel Version: 5.4
- PHP Version: 7
- Database Driver & Version: sql 

### Description:
HTML Code: 
```
<form method="post" enctype="multipart/form-data" action="">
    <input type="file" name="image">
    <button type="submit">submit</button>
</form>
```
PHP CODE 
```
public function test_submit(request $r)
    {
        return $r->all();
}
```

RESULT:
```
{
  "file": {
    
  }
}
```
if try to save file this error message: 
Call to undefined method Illuminate\Database\Query\Builder::file()

### Steps To Reproduce:
Randomly happens but once this issue started no way to fix it.

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue
