### ISSUE TITLE
Soft Delete as Char enum

### ISSUE THREAD

**Issue by sistemaswebbrasil** [laravel/framework#21879]
- Laravel Version: 5.5.*
- PHP Version:7
- Database Driver & Version:
Mysq 5.7
### Description:
Is it possible to use another type of field for soft delete instead of timestamp? I have a legacy database that is controlled by enum('F','T') text and would like to use the native soft_deletes feature of laravel.

Sorry my english came from Google Translator

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by themsaid** [comment]
@sistemaswebbrasil sorry but you need to use the forums for questions, and I think you'll need to include more details.
