### ISSUE TITLE
Overlapping routes inside group

### ISSUE THREAD

**Issue by wheatleyjj** [laravel/framework#21873]
- Laravel Version: 5.5.18
- PHP Version: 7.1.3
- Database Driver & Version: MySQL 5.7.17

### Description:
When creating a route underneath a route expecting a parameter, the route above with the parameter is called.

### Steps To Reproduce:
    // User routes
    Route::group(['prefix' => '/users'], function () {
        Route::get('/', 'UserController@get');
        Route::post('/', 'UserController@create');
        Route::get('/{user_id}', 'UserController@getForId'); 
        Route::patch('/{user}', 'UserController@update');
        Route::get('/types', 'UserController@types');
    });

- Go to `/users/types`.
- Watch `UserController@getForId` get called instead of `@types`.

This behaviour goes away when moving the `UserController@types` route above the `UserController@getForId` route.

**Comment by tomirons** [comment]
This is the natural behavior, you'll need to define any routes without a parameter before the `{user_id}` route.

**Comment by browner12** [comment]
yah, general rule of thumb, go from more specific routes to less specific.
