### ISSUE TITLE
Session cookie does not honor `expire_on_close` causing cookie leak

### ISSUE THREAD

**Issue by macdabby** [laravel/framework#21884]
- Laravel Version: 5.4 and up, possibly more
- PHP Version: all
- Database Driver & Version: NA

### Description:
When a session is saved, there are two cookies set. The cookie containing the data itself, which has an encoded name. That encoded name is stored in a standard cookie that's the same across all sessions. They are written in different places:

https://github.com/laravel/framework/blob/5.5/src/Illuminate/Session/Middleware/StartSession.php#L171

line 171 is where the content is written
line 176 is where the content key data is written (from config:session.cookie)
(sorry for the confusion, they don't have names and i'm not sure what to call them)

They pass through separate functions.

session content is written here:
https://github.com/laravel/framework/blob/5.5/src/Illuminate/Session/CookieSessionHandler.php#L85
notice that the date comes from the config, but does not check for `expire_on_close`

where as the session key is written back in the StartSession class:
https://github.com/laravel/framework/blob/5.5/src/Illuminate/Session/Middleware/StartSession.php#L177
notice that the date method uses `$this->getCookieExpirationDate()` which does check for the `expire_on_close` setting

### Steps To Reproduce:
make a request that sets a cookie. close your browser. open your browser. only the big content cookie will be there, the session id cookie will be gone. make the same request. you'll now have 2 session content cookies and 1 id cookie. close and open the browser and you'll have 2 content cookies. do this again over and over and you'll end up with a ton of content cookies which ultimately hit limits. in our specific case it's an nginx limit that prevents large cookie requests. yes we can raise this, but that's really not a good long term fix.

![dbceqqem792uc](https://user-images.githubusercontent.com/176957/32196036-47a1cfae-bd8d-11e7-98e1-2b0fe56a4050.gif)

**Comment by sisve** [comment]
Clarification; this is about the cookie used by CookieSessionHandler (`SESSION_DRIVER=cookie`).

**Comment by driesvints** [comment]
I can't seem to reproduce this in the latest Laravel release. Can you try to see if it's still happening there?
