### ISSUE TITLE
[5.5] Route Registration Middleware Omitted

### ISSUE THREAD

**Issue by ConnorVG** [laravel/framework#21896]
- Laravel Version: 5.5.19
- PHP Version: 7.1.10-1+ubuntu16.04.1+deb.sury.org+1
- Database Driver & Version: 14.14 Distrib 5.7.19, for Linux (x86_64) using  EditLine wrapper

### Description:
The `middleware` method for route registration doesn't support variadic arguments when not first in the chain.

### Steps To Reproduce:
Using the default `mapApiRoutes` method in the `RouteServiceProvider`, add a test middleware after the `api` middleware:
```php
Route::prefix('api')
     ->middleware('api', \App\Http\Middleware\TestMiddleware::class)
     ->namespace($this->namespace)
     ->group(base_path('routes/api.php'));
```

Make the test middleware:
```php
class TestMiddleware
{
    public function handle($request, Closure $next)
    {
        dd('here');
    }
}
```

When accessing an `api` route, the `TestMiddleware` will **not** be fired and `here` will not be dumped.

This does not suffer the same problem:
```php
Route::middleware('api', \App\Http\Middleware\TestMiddleware::class)
     ->prefix('api')
     ->namespace($this->namespace)
     ->group(base_path('routes/api.php'));
```

**Comment by themsaid** [comment]
Thanks, a fix was submitted at https://github.com/laravel/framework/pull/21930
