### ISSUE TITLE
Blade raw blocks (@php and @verbatim) swapped by Blade Compiler

### ISSUE THREAD

**Issue by dafonso** [laravel/framework#21897]
- Laravel Version:  5.5.19
- PHP Version: 7.0.24
- Database Driver & Version: MySQL 5.7.20

### Description:

If we use any of the defined raw blocks (`@php` and `@verbatim`) on a blade template, when compiled they will be swapped - `@verbatim` will appear first, then `@php` blocks - despite being defined in other order.

 I've researched this, but atm don't have the time to go through a PR. Will do ASAP if no one brings it to attention because it's a breaking bug. Basically it's due to the fact that BladeCompiler search first for `@verbatim` then for `@php` and stores it on the same `$this->rawBlocks` array. 

```php
...
public function compileString($value)
    {
        if (strpos($value, '@verbatim') !== false) {
            $value = $this->storeVerbatimBlocks($value);
        }

        $this->footer = [];

        if (strpos($value, '@php') !== false) {
            $value = $this->storePhpBlocks($value);
        }
...
```

When it gets restored:
```php
...
protected function restoreRawContent($result)
    {
        $result = preg_replace_callback('/'.preg_quote($this->rawPlaceholder).'/', function () {
            return array_shift($this->rawBlocks);
        }, $result);

        $this->rawBlocks = [];
...
```
It just follows the order by which raw block was added to `$this->rawBlocks[]`.

It was introduced in #20065 by @sileence . Workaround atm is not using `@verbatim` when there are `@php` blocks on the same template.

### Steps To Reproduce:

1. Create `test.blade.php` template file on `resources/views` folder  with `@php` and `@verbatim` blocks. 
```Blade
<pre>
@php
echo "#1";
@endphp

@php
echo "#2";
@endphp

@verbatim
#3
@endverbatim
</pre>
```
2. Create route to view on web.php
```php
Route::view('/test', 'test');
```

3. Navigate to the /test url and see as it appears in a different order then defined on `test.blade.php`
```
#3
#1
#2
```

**Comment by sileence** [comment]
This is a possible fix of the problem: https://github.com/laravel/framework/pull/20072

Because in this case the raw placeholder will have a sort of ID like `@__raw_block_1__@`, `@__raw_block_2__@` that will prevent them from being mixed up.

**Comment by dafonso** [comment]
@sileence: I saw that PR and saw that it probably fixed the issue, but was unsure about it because both you and @taylorotwell mentioned the Blade comments stuff... Decided to submit a bug report because it doesn't have any relation with blade comments as well as I didn't knew how to reopen a closed issue.

**Comment by sileence** [comment]
yes, because it also helps when parts of the code are commented out. 

I guess I can re-submit the PR, maybe adding more tests to describe your issue.

**Comment by ntzm** [comment]
I submitted a similar PR recently that was rejected #21715
