### ISSUE TITLE
[5.5] Envoy not working after upgrade from 1.2.2 to 1.3.4.

### ISSUE THREAD

**Issue by vrubiella** [laravel/framework#21890]
- Laravel Version: 5.5
- PHP Version: 7.1.10
- SO: Alpine 3.4.6
### Description:
After upgrade from envoy 1.2.* to 1.3.*, some comands are broken:

```
/www $ vendor/bin/envoy run disk-info --path="/var/www/conf" --depth=1
                                  
  [Exception]                       
  Task "disk-info" is not defined.  
                                    
run [--continue] [--pretend] [--path PATH] [--] <task>

/www $ vi composer.json
/www $ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating laravel/envoy (v1.3.4 => v1.2.2): Downloading (100%)         
Writing lock file
Generating autoload files
/www $ vendor/bin/envoy run disk-info --path="/var/www/conf" --depth=1
[cmsadm@10.100.0.10]: 206916	/var/www/home/000000331
[cmsadm@10.100.0.10]: 205316	/var/www/home/000000024
```

### Steps To Reproduce:
command with path and extra parameters after path.

this command works fine:
`vendor/bin/envoy run disk-info --depth=1 --path=/var/www/home/ `

this not: 
`vendor/bin/envoy run disk-info --path=/var/www/home/ --depth=1`

both commands works fine in previous releases 1.2.X

**Comment by lancepioch** [comment]
Is this still broken in 1.4.0?

**Comment by vrubiella** [comment]
No, now works fine. I'm retrying with 1.3.4 version and works fine, maybe the bug was in another envoy dependency.
