### ISSUE TITLE
Eloquent builder passthru should include "raw"

### ISSUE THREAD

**Issue by MaartenStaa** [laravel/framework#21907]
For example:

```php
$raw = MyModel::query()->raw('1');

echo get_class($raw);
```

Expected output:

> Illuminate\Database\Query\Expression

Actual output:

> Illuminate\Database\Eloquent\Builder

Since the Eloquent query builder does not have 'raw' listed in its passthru array, the raw method is called on the base query (and, in turn, on the connection class), but the result is then discarded and `$this` is returned.

https://github.com/laravel/framework/blob/2b4aa9fb285a16755afd88d28e7d1bbe4a012ae5/src/Illuminate/Database/Eloquent/Builder.php#L69

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
