### ISSUE TITLE
Package discovery not work on some package

### ISSUE THREAD

**Issue by khaninejad** [laravel/framework#21906]
- Laravel Version: 5.5.18
- PHP Version: 7.1
- Database Driver & Version: Mysql

### Description:
Laravel coudn't auto-disover some packages.

### Steps To Reproduce:
Hi, I tried to upgrade this package to 5.5 
https://github.com/larabook/gateway/
but after adding this script to composer.json
"extra": {
        "laravel": {
            "providers": [
                "Larabookir\\Gateway\\GatewayServiceProvider"
            ],
            "aliases": {
                "Gateway": "Larabookir\\Gateway\\Gateway"
            }
        }
    },
laravel couldnt disover this package and vender publish not work

**Comment by Dylan-DPC** [comment]
This is not a laravel issue. You have a mistake in your namespace of your provider

**Comment by khaninejad** [comment]
but I believe it can show deprecated ones.

**Comment by Dylan-DPC** [comment]
What do you mean by deprecated ones?
