### ISSUE TITLE
Make visible/hidden object properties using a Paginator method

### ISSUE THREAD

**Issue by martinsik** [laravel/framework#21914]
- Laravel Version: 5.5
- PHP Version: any
- Database Driver & Version: any

### Description:
 I often find myself using the `paginator()` method and then calling `makeVisible` (or `makeHidden`) on each item in the paginator. For example like this:

```
$paginator = $query->paginator($perPage);

forEach ($paginator->items() as $item) {
  $item->makeVisible('whatever');
}
```

I know a similar functionality is described in https://laravel.com/docs/5.5/eloquent-resources#conditional-attributes but it's often easier not to overload the `toArray()` method and use just `makeVisible`.

I think it would be nice to have this already in the paginator as a parameter or a method that would make visible/hidden a list of properties so I could call eg.:

```
$paginator->makeVisible('whatever');
```

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.

**Comment by sisve** [comment]
How would this work if you were paginating non-Eloquent items?
