### ISSUE TITLE
Foreign and primary keys names 

### ISSUE THREAD

**Issue by Martha-91** [laravel/framework#21915]
- Laravel Version: 5.4.36
- PHP Version: PHP 7.0.22-0
- Database Driver & Version: MySql ,  5.7.20-0ubuntu0.17.04.1
- Operating System : ubuntu0.17.04.1

### Description:
In Model with belongs relationship , it doesn't work properly unless I write the primary and foreign keys in wrong name .
It does not work if I use the correct names for keys .

### Steps To Reproduce:
1- I built CustomerPayment Model with name customer_payment table ( idCustomerPayment is Primary key - idMeetingCalendar is foreign key )

I checked my table and keys names , and They are with capital C . 
But when I retrieve CustomerPayment history it returns attribute with name 'idMeetingcalendar' instead 'idMeetingCalendar' as named in mysql !!

Thanks

**Comment by themsaid** [comment]
Please share some code so we can look into it.

**Comment by Martha-91** [comment]
1- This is my code : 
  $inprogress_retry_success = CustomerPayment::where ( 'idCustomer' , $customer [ 'idCustomer' ] )
                                            ->whereIn ( 'status' ,
                                            	[ config ('consul.paymentInProgress'),
                                            	  config ('consul.paymentUnderRetryFromPaymentGW'),
                                            	  config ('consul.paymentSuccess')
                                            	]);
  $customer_payments = $inprogress_retry_success
                                            ->select ( 'idMeetingcalendar' , 'status' , 'amount' , 'idCurrency' , 'created_at' )
                                            ->orderBy ( 'created_at' , 'desc' )
                                            ->paginate( $limit ) ;

I can guess now that error was that I select idMeetingcalendar  , not idMeetingCalendar 
but why There is no exception or error happen , instead of return customerPayment object with wrong attribute name ?

**Comment by JayBizzle** [comment]
> _Column, index, stored routine, and event names are not case sensitive on any platform, nor are column aliases._ [Source](https://dev.mysql.com/doc/refman/5.6/en/identifier-case-sensitivity.html)

Just tested this, and if you have a column named `userID` and you do `select userid from users` you will get `userid` as the column name, not the actual, exact case of the original.

TIL.

**Comment by Martha-91** [comment]
Thank JayBizzle !

**Comment by themsaid** [comment]
This isn't an issue with laravel then, that's the  database engine works. To eliminate confusion I recommend that you use snake case column names in your database.
