### ISSUE TITLE
Eloquent Resource resolve() did not contains the LengthAwarePaginator data

### ISSUE THREAD

**Issue by jety91** [laravel/framework#21928]
- Laravel Version: 5.5.19
- PHP Version: 7.1.1
- Database Driver & Version: -

### Description:
When I call the Eloquent Resource resolve() function manually on a Resource collection, the resolve function did not return with the pagination information (meta and links keys are missing) when I override the toArray function.

### Steps To Reproduce:
1. Create a model.
2. Create a related resource class and override the toArray function with custom data.
3. Call `Resource::collection(Model::paginate())->resolve()` manually

**Comment by themsaid** [comment]
Please share code of your Resource class

**Comment by jety91** [comment]
### UserResource.php
```
use Illuminate\Http\Resources\Json\Resource;

class UserResource extends Resource
{
    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'username' => $this->username,
            'email' => $this->email,
        ];
    }
}
```

### UserController.php
```
class UserController extends Controller
{
    public function index()
    {
        $this->addResponseData(UserResource::collection(User::paginate())->resolve());

        return $this->sendResponse();
    }
}
```
### Response
```
[
    {
            "id": 1,
            "username": "test1",
            "email": "test@local.site"
        },
        {
            "id": 2,
            "username": "test2",
            "email": "test2@local.site"
        }
]
```
### If I remove the toArray function from the UserResource class:
```
{
    "resource": [
        {
            "id": 1,
            "username": "test1",
            "email": "test@local.site"
        },
        {
            "id": 2,
            "username": "test2",
            "email": "test2@local.site"
        }
    ],
    "links": {
        "first": "http://127.0.0.1:8000/admin/api/system/user?page=1",
        "last": "http://127.0.0.1:8000/admin/api/system/user?page=1",
        "prev": null,
        "next": null
    },
    "meta": {
        "current_page": 1,
        "from": 1,
        "last_page": 1,
        "path": "http://127.0.0.1:8000/admin/api/system/user",
        "per_page": 50,
        "to": 2,
        "total": 2
    }
}
```

Anyway, I found a proper solution for me, which is maybe a better workflow. In the UserController@index method I used a custom response handler and I put the complete resource collection to their data store. I removed this, and don't need to be called the resolve function anymore, just only `return UserResource::collection(User::paginate())`.

My question is: When I call the resolve() function `UserResource::collection(User::paginate())->resolve()`, it's need to be contain any pagination information in normal cases?
If the answer is no, I think it's closable.

Thanks!

**Comment by themsaid** [comment]
No idea what's in your `addResponseData` and `sendResponse `, please use the forums for help and try to provide as much details as you can, having a method that we don't know how it works makes it very hard to predict what you're facing :)
