### ISSUE TITLE
multi morphOne relations to same model not work

### ISSUE THREAD

**Issue by oonxt** [laravel/framework#21923]
- Laravel Version: 5.5.#
- PHP Version: 7.1
- Database Driver & Version:

### Description:
sometimes we need 2 or more morphOne relations to same model. but  cant get correct result now.

### Steps To Reproduce:
for example:
in model Movie:

```
public function thumbnail()
{
    return $this->morphOne(Media::class, 'media');
}

public function video()
{
    return $this->morphOne(Media::class, 'media');
}
````

in model Media:

```
public function media()
{
    return $this->morphTo();
}
````

the thumbnail/video will get the same result.

add an extra 'morphClass' param to morphOne will be effective.

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
