### ISSUE TITLE
File Response throws FatalThrowableError

### ISSUE THREAD

**Issue by vincentsch** [laravel/framework#21922]
- Laravel Version: 5.5.19
- PHP Version: 7.1.8-2

### Description:
Tried to use file response as documented in https://laravel.com/docs/5.5/responses#file-responses.

I'm getting this error:

> Call to undefined method Symfony\Component\HttpFoundation\BinaryFileResponse::header()

### Steps To Reproduce:
Here's my controller code:
```
<?php
namespace App\Http\Controllers\Profile;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Storage;
class AvatarController extends Controller
{
    /**
     * Return avatar image for current user.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = \Auth::user();
        $storage_path = 'avatars/' . $user->id;
        if (Storage::exists($storage_path )) {
            $avatar_path = Storage::getDriver()->getAdapter()->applyPathPrefix($storage_path);
        } else {
            $avatar_path = '/css/dummy/profile-small.jpg';
        }
        $mime_type = Storage::mimeType($storage_path);
        $headers = ['Content-type' => $mime_type];
        return response()->file($avatar_path, $headers);
    }
}
```

### Workaround:
Use readfile():
```
<?php
namespace App\Http\Controllers\Profile;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Storage;
class AvatarController extends Controller
{
    /**
     * Return avatar image for current user.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = \Auth::user();
        $storage_path = 'avatars/' . $user->id;
        if (Storage::exists($storage_path )) {
            $avatar_path = Storage::getDriver()->getAdapter()->applyPathPrefix($storage_path);
        } else {
            $avatar_path = '/css/dummy/profile-small.jpg';
        }
        $mime_type = Storage::mimeType($storage_path);
        $headers = ['Content-type' => $mime_type];
        foreach ($headers as $key => $value) {
            header("$key: $value");
        }
        readfile($avatar_path);
        exit;
    }
}
```

**Comment by sisve** [comment]
Is everything in your code example required to reproduce the problem? Do I have to use `Auth::user()`? How about `/css/dummy/profile-small.jpg`?

Anyhow, you should either 1) download content with Storage::get() and return the content, or 2) use redirect to Storage::url() if the storage adapter supports it. Remember, the storage can be swapped out with a simple config change, and your entire setup will fail since you presume that files are stored locally.

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.

**Comment by vincentsch** [comment]
@sisve Sorry, no I just wanted to give a full example. The important line is `return response()->file($avatar_path, $headers);`. This line is suggested by the official documentation, but leads to a fatal error. 

@themsaid This is supposed to be a bug report.
