### ISSUE TITLE
Rename primary key PostgreSQL

### ISSUE THREAD

**Issue by jetexe** [laravel/framework#21921]
- Laravel Version: 5.5.19
- PHP Version: 7.1.11-1
- Database Driver & Version: psql  9.5.9

### Description:
Set name for primary key not working.

### Steps To Reproduce:
code
 ```
Schema::connection($this->getConnection())->table($this->tableName, function (Blueprint $table) {
            $table->dropPrimary('old_name');
            $table->primary('id', 'new_name');
        });
```
generate sql statment 

`alter table "table_name" add primary key ("id")`

must be 
```
ALTER TABLE table_name
	ADD CONSTRAINT new_name PRIMARY KEY (id);
```

**Comment by themsaid** [comment]
renaming keys isn't supported by laravel at the moment, check the docs there's no mention of it.

For suggestions and feature requests please use the https://github.com/laravel/internals repo.

**Comment by jetexe** [comment]
it's not just rename. It's create new primary index with name!
new issue:
```
$table->dropPrimary('promos_pkey');
```
generate:
```
alter table "promocodes" drop constraint "promocodes_pkey"
```
are u sure that is normal?
it's not a future request. it's a bug report

**Comment by jetexe** [comment]
@themsaid?
