### ISSUE TITLE
email error - response code expected

### ISSUE THREAD

**Issue by penance316** [laravel/framework#21924]
- Laravel Version: 5.5.19
- PHP Version: 7.1
- Database Driver & Version:

### Description:
When sending mail using the sendmail driver I always receive this error:
" Expected response code 220 but got code "", with message "" "
I am using the standard Mail::send facade to create this email.

When I use the php mail function the emails work fine
mail("sample@gmail.com", "My subject", 'some message here')

I have seen lots of bugs regarding laravel 5.5 and email errors around the internet but none of them include a fix.

Does anyone have any idea what could be causing this?

Thanks for your time.

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
