### ISSUE TITLE
ERROR: __clone method called on non-object Notification Queue

### ISSUE THREAD

**Issue by hudovisk** [laravel/framework#21939]
- Laravel Version: 5.5
- PHP Version: 7.1
- Database Driver & Version: mysql 5.7

### Description:
The error appears when I try to send a queued notification where the notifiable is an array of strings or a collection of strings.

I use it to send Push Notifications, where the notifiables are a collection of fcm tokens strings.
```php
$devices = Device::whereHas('user.priorities', function ($query) use ($occurrence) {
    $query->where('level', $occurrence->priority->level);
})->get()->pluck("fcm_token");

Notification::send($devices, new OccurrencePriorityNotification($occurrence));
```
The error is in `laravel/framework/src/Illuminate/Notifications/SendQueuedNotifications.php:90`, it is trying to clone the variable `$this->notifiables` that is a String instead of a Collection.
```php
   /**
     * Prepare the instance for cloning.
     *
     * @return void
     */
    public function __clone()
    {
        $this->notifiables = clone $this->notifiables;
        $this->notification = clone $this->notification;
    }
```

I need it to be serialized as a collection because in my Channel I send the notification to multiple tokens in a single request.

The error does not happen if I dont use `implements ShouldQueue` in my notification.

Another thing, if I understood it correctly, in the NotificationSender->queueNotification a new notification is queued for each notifiable. The queued notification uses the sendNow method that does the same thing, so it is like it is being iterated twice. Is it the expected behavior?

Thanks in advance!

**Comment by themsaid** [comment]
A notifiable must be an object, you need to send a collection for devices where a device uses the Notifiable Trait and a `routeNotificationsToChannel` name.

**Comment by hudovisk** [comment]
Thanks, for those with the same problem I fixed by defining this inside my Users.php
```php
public function routeNotificationForFcm() {
        return $this->devices->pluck("fcm_token")->toArray();
    }
```

Firing the notification with this:
```php
$users = User::whereHas('priorities', function ($query) use ($occurrence) {
    $query->where('level', $occurrence->priority->level);
})->get();

Notification::send($users, new OccurrencePriorityNotification($occurrence));
```

And getting the tokens inside my channel with this:
```php
public function send($notifiable, Notification $notification) {
        if(empty($tokens = $notifiable->routeNotificationFor('fcm'))) {
            return;
        }
// ...
}
```

The class `SlackWebhookChannel` is a good place for a reference.
