### ISSUE TITLE
Paginate method append skip empty params

### ISSUE THREAD

**Issue by projct1** [laravel/framework#21937]
- Laravel Version: 5.5.19

### Description:
My url request is `?admin_id=1&in_work&check_visit_client`
```php
$items->appends(Request::all())->links('vendor.pagination.bootstrap-4');
```
In 2 and next pages params `in_work` and `check_visit_client` dissapear.

**Comment by Dylan-DPC** [comment]
Can you be more clear on this? Steps to reproduce? What is the problem? What you expected to happen and what was the actual output?

**Comment by projct1** [comment]
In second page and next pages i have `?admin_id=1&page=2`
Expected is `?admin_id=1&in_work&check_visit_client&page=2`

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.

**Comment by projct1** [comment]
But its a bug of paginating... Why empty params are skipped?
`Request::all()` returns all params:
```php
[
    'in_work' => '',
    'check_visit_client' => ''
]
```

**Comment by themsaid** [comment]
@projct1 try the forums and include more details, if you try and replicate this on a fresh laravel installation you'll find it working fine, so there must be something in your code, so please open a forum thread and include as much details as possible for people to be able to assest you.

**Comment by Zuken** [comment]
Paginator ignores `null` value
```php
$p = new Paginator(['item1', 'item2', 'item3'], 2, 1);
$queryParams = ['queryParam1' => 'value1', 'queryParam2' => '', 'queryParam3' => null];
$p->appends($queryParams);
$p->url(1); //gives "/?queryParam1=value1&queryParam2=&page=1" without queryParam3
```

**Comment by projct1** [comment]
Yea, but `Request::all()` returns not null values as empty. So, paginator must be save empty (not null) values.
