### ISSUE TITLE
Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

### ISSUE THREAD

**Issue by benadavid** [laravel/framework#21932]
- Laravel Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
TravisCi gives me this. How do you fix this? thank you. I did all updates for laravel.

```
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
```
                                                                               
 ```
 [InvalidArgumentException]                                                   
  Cache directory /home/travis/build/g-harel/SOEN343/storage/app/aspect is no  
  t writable                                                                   
                                                                               
Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
The command "composer install" failed and exited with 1 during .
```

**Comment by sisve** [comment]
Cache directory /home/travis/build/g-harel/SOEN343/storage/app/aspect is not writable

Isn't the error message obvious?

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.

**Comment by aman-mod** [comment]
when i want to migrate the table the out put is this please help me!
Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

**Comment by mohannad1995** [comment]
Generating optimized autoload files

Illuminate\Foundation\ComposerScripts::postAutoloadDump
@php artisan package:discover

In ResourceRegistrar.php line 360:

Object of class Closure could not be converted to string

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
I'm using laravel 5.6
