### ISSUE TITLE
Priority queue isn't working.

### ISSUE THREAD

**Issue by ankitjain28may** [laravel/framework#21949]
- Laravel Version: 5.4
- PHP Version: 7
- Database Driver & Version: Mysql

### Description:

When i am trying to send mail using queue is working fine..
I am using `QUEUE_DRIVER=database` and send mail using jobs.

But when i need to change the priority of the mail i.e to high
```
// Controller
$this->dispatch(new SendEmail($contents_array, $meetup_details, $email_contents, $data)->onQueue('high'));
```
```
// Jobs
$mailer->send('Frontend.email-contents.email-contents', $this->contents_array, function ($message) use($this->details, $this->email_contents, $this->data) {
            $message->from($this->data['global']['contact_email'], $this->data['global']['site_title']);
            $message->to($this->details->email_address, ucwords($this->details->contact_name))->subject($this->email_contents['email_template_subject']);
        });
```
```
// config/queue.php
'database' => [
            'driver' => 'database',
            'table' => 'jobs',
            'queue' => 'low',
            'retry_after' => 90,
        ]
```

It is not sending `queue=high` in database table = jobs.

**Comment by sisve** [comment]
Do you have any queue workers that are processing the `high` queue?

These priorities aren't really priorities, but different queues. You then run `php artisan queue:work --queue=high,default` to have a worker process both queues, checking for availabile jobs in the queue `high` before checking in the `default` queue.

**Comment by ankitjain28may** [comment]
Yes, I have set `php artisan queue:work --queue=high,low` but its not setting queue to high in database table..

**Comment by Kyslik** [comment]
"Not setting" or "not processing"?

**Comment by ankitjain28may** [comment]
Its processing that mail but with the `low` value rather than `high` value

**Comment by Kyslik** [comment]
And how do you run your workers?

**Comment by ankitjain28may** [comment]
I am not using supervisord, i am testing using `php artisan queue:work --queue=high,low` and yes i have restarted my workers.

**Comment by Kyslik** [comment]
Alright.

---

I still do not understand what is going on.
When you open up database and view table with jobs, do you have any jobs that have queue = **high**?

---

I just noticed that you do not specify connection in your artisan command, try:

```shell
art queue:work --queue=high,low database
```

**Comment by ankitjain28may** [comment]
No, i dont have any jobs that have `queue` = **high**
I only have jobs having `queue` = low.

As i have set `QUEUE_DRIVER=database` so i think there isn't requirement to set the connection. And one more thing.. if there is a problem with connection then my mails wont send but they will get queue in the database with  `queue` = **high**

**Comment by Kyslik** [comment]
It seems that you are `dispatch`ing wrongly:

```php
$this->dispatch(new SendEmail($contents_array, $meetup_details, $email_contents, $data))->onQueue('high');
```

see https://laravel.com/docs/5.5/mail#queueing-mail and https://laravel.com/docs/5.5/queues#customizing-the-queue-and-connection

**Comment by ankitjain28may** [comment]
@Kyslik , Can you pls be more specific... what am i doing wrong in dispatching the mail ?

**Comment by Kyslik** [comment]
I guess I wasn't specific enough, your controllers code should look like:

...`$data))->onQueue('high');`

**Comment by ankitjain28may** [comment]
@Kyslik I have tried both the ways as on `stackoverflow`... somewhere they are using the way i write and somewhere they r using the way you write.. So i don't think that the problem is there.

**Comment by Kyslik** [comment]
I will just quote myself again:

>See https://laravel.com/docs/5./mail#queueing-mail and https://laravel.com/docs/5.5/queues#customizing-the-queue-and-connection

**Comment by ankitjain28may** [comment]
@Kyslik Thanks for your help, But as i told earlier i am getting problem in both the ways. Moreover you can try it by yourself.

**Comment by ankitjain28may** [comment]
@Kyslik, You can also check this.. 
> See [https://laravel.com/docs/5.4/queues#queue-priorities](https://laravel.com/docs/5.4/queues#queue-priorities)

**Comment by Kyslik** [comment]
Make an example repo that we can pull.

**Comment by ankitjain28may** [comment]
@Kyslik Ok I will push one example repo by tonight.. It would be a great help for me, Thanks :smile: 
I will ping here when i pushed a repo.

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
