### ISSUE TITLE
adding cors header to api doesn't respond to options for non-simple requests

### ISSUE THREAD

**Issue by ChangePlaces** [laravel/framework#21948]
- Laravel Version: 5.5
- PHP Version: 7.0
- Database Driver & Version: n/a

### Description:
I have a simple cors middleware which is responsible for sending the correct headers (listed below) and I've added a class reference to the 'api' key under the route middleware groups. For simple requests (GET), this works fine and a non-local host can access the api. However, for PUT / POST, the correct OPTIONS headers are not returned preventing the POST/PUT to continue. However, if I move the reference to the CORS middleware from the groups to the middleware array, it works as expected.

    // cors middleware code:
    {
	header('Access-Control-Allow-Origin: *');
	
	$headers = [
		'Access-Control-Allow-Methods' => 'GET, POST, PUT, DELETE, OPTIONS',
		'Access-Control-Allow-Headers' => 'X-Requested-With, Content-Type, Accept, Origin, Authorization',
		'Access-Control-Allow-Credentials' => 'true',
	];
    
	if ($request->getMethod() == "OPTIONS") {
            return Response::make('OK', 200, $headers);
        }
	
	$response = $next($request);
	
	foreach ($headers as $k => $v)
		$response->header($k, $v);

	return  $response;
    }

    // code added to 'api' key of middlewaregroups array in Kernel.php
    \App\Http\Middleware\Cors::class,

**Comment by Dylan-DPC** [comment]
Check the order of the middleware.

**Comment by Kyslik** [comment]
Use / see https://github.com/barryvdh/laravel-cors

**Comment by ChangePlaces** [comment]
@Dylan-DPC  There's only one middleware in the api key

@Kyslik The Cors middleware above should be fine? I did look at that middleware but couldn't see any difference ultimately

**Comment by Kyslik** [comment]
@ChangePlaces just read package's readme it will help you out. And yes I use that package and it works for my use.

**Comment by Dylan-DPC** [comment]
Using a package shouldn't be a solution to a problem

**Comment by ChangePlaces** [comment]
The problem here is that for "simple" cors requests like GET, the middleware is activated, however for complicated requests (POST/PUT/PATcH) the OPTIONS reques is not / doesn't appear to be activated. I think the real, underlying problem is that, for some reason how laravel handles the api requests doesn't work properly when assigning middleware to those methods.

Assigning CORS to all routes is not desirable and is not a solution.

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.

**Comment by ChangePlaces** [comment]
@themsaid this is a bug

**Comment by themsaid** [comment]
You can search this repo for similar issues, there has been a lot of discussions around that already.
