### ISSUE TITLE
Multiple attachments in Mailable emails results in duplicate files

### ISSUE THREAD

**Issue by rlitten** [laravel/framework#21944]
- Laravel Version: 5.5.19
- PHP Version: 7.1.10
- Database Driver & Version: Mysql 5.7.20

### Description:
In my controller I collect the file attachments into an array like this:
```
 foreach($request->file('attachment') as $attachment) {
                    $attachments[] = [
                                        'file' => $attachment->getRealPath(),
                                        'options' => [
                                            'mime' => $attachment->getClientMimeType(),
                                            'as'    => $attachment->getClientOriginalName()
                                        ],
                                    ];
                }
Mail::to('test@test.com')->send(new ResearchCreate($requestDetails,$attachments));
```
Then in my Mailable I attach the files like this:
```
$message = $this->subject('New research request')->markdown('app.emails.research.create');

            foreach($this->attachments as $attachment) {
                $message->attach($attachment['file'],$attachment['options']);
            }
            return $message;
```

### Steps To Reproduce:
Use the above controller and Mailable and try sending.

**Comment by Dylan-DPC** [comment]
Can you explain what happens when you run the code? What output you are getting versus what you expected to happen?

**Comment by rlitten** [comment]
If I attach 1 file lets call it File1.txt and submit it. In the email received I have 2 files both are File1.txt.
If I attach 2 files File1.txt and File2.txt I get 4 files attached to the email. 2 files of File1.txt and 2 files of File2.txt.
I have dd($this->attachments) in my Mailable build() method and it shows the correct amount of files in the array. Just seems like something in the Mailable class that is added them a 2nd time

**Comment by rlitten** [comment]
I have create a new laravel project with the code used to reproduce this issue.
NOTE: setup your .env file to use Mailtrap.io to capture the emails.

[https://github.com/rlitten/laravel-mailable-test](https://github.com/rlitten/laravel-mailable-test)

**Comment by sisve** [comment]
Your example repo has only one commit, it's hard for us to differ between the original Laravel source and the code changes you've done.

**Comment by rlitten** [comment]
Sorry, I have updated the repo to reflect the changes now

**Comment by themsaid** [comment]
`$attachements` is used in mailables to send attachements that's why you have multiple instances, use `Mailable::attach()` or change the property name in your mailable constructor.
