### ISSUE TITLE
SoftDelete on queries with a join

### ISSUE THREAD

**Issue by jonathanpel** [laravel/framework#21947]
- Laravel Version: 5.5.19
- PHP Version: 7.0.19-1
- Database Driver & Version: pgsql

### Description:

The "getDeletedAtColumn" called by the "extend" method in the SoftDeletingScope will return the full tablename + column for the update call if there is a join on the query.

This will make a SQL error when deleting because the table name will be added in the "UPDATE" SQL query (e.g: "UPDATE "tablename" SET "tablename"."deleted_at" = '2017-11-03 14:45:25' ....")

In my case I did a delete on a "hasManyThrough" relationship, so a join was made on the query, creating the SQL error.

### Steps To Reproduce:

Do a soft delete on any query that has a join (e.g: Model::join('table',...)->delete();) or delete on a "hasManyTrough" relationship.

**Comment by Dylan-DPC** [comment]
https://github.com/laravel/framework/issues/19400#issuecomment-304851029

**Comment by jonathanpel** [comment]
I can see how doing a manual join would be something you need to take care manually. But it still does the same error when you delete an Eloquent "hasManyTrough" relationship. Something like:
An "Author" has many "Book" and a "Book" has many "Sale". Then doing $author->sales()->delete(); would crash because Eloquent is doing a join on "books" to get the author's sales.

**Comment by themsaid** [comment]
Check https://github.com/laravel/framework/issues/19400#issuecomment-304851029
