### ISSUE TITLE
blade helpers file

### ISSUE THREAD

**Issue by ChangePlaces** [laravel/framework#21959]
- Laravel Version: 5.5
- PHP Version: 7
- Database Driver & Version:

### Description:
As laravel models many places where everything "fits", e.g. routes go here, model classes go here etc, it'd be nice to have a place (a directory / a file) where custom helpers for views can be placed.

This SO question recommends the app directory, but imo I think putting code that spits out html shouldn't be placed there: https://stackoverflow.com/questions/28290332/best-practices-for-custom-helpers-on-laravel-5

**Comment by Kyslik** [comment]
Move this to [internals](https://github.com/laravel/internals) mate.

**Comment by ChangePlaces** [comment]
Thanks, have done!

**Comment by Kyslik** [comment]
Mind closing this issue as well?
