### ISSUE TITLE
Laravel can’t handle the pagination with the union query

### ISSUE THREAD

**Issue by lun324** [laravel/framework#21958]
- Laravel Version: 5.5.13
- PHP Version: 7.0.23
- Database Driver MySql & Version: 5.7

### Description:
right now there is a problem with pagination when you use the $query->union() function with a subsequent $query->paginate(). You will get an error saying SQLSTATE[21000]: Cardinality violation: 1222 The used SELECT statements have a different number of columns

Laravel can’t handle the pagination with the union query, as the first SELECT that you have will be altered to be count(*) AS aggregate but the second one will not, resulting in a different number of columns and thus throwing an error.

### Steps To Reproduce:

   $a = Order::where(['a' => 2])->whereIn('status', [3, 5]);
   $b = Order::where(['b' => 1])->whereIn('status', [3, 5]);
   $result =  $a->unionAll($b)->->paginate(15);

**Comment by themsaid** [comment]
This is a known limitation and we're open to solutions for the issue, check https://github.com/laravel/framework/issues/2968#issuecomment-33741816

**Comment by akhileshdarjee** [comment]
@themsaid : Any solutions or workaround?
I'm on following stack:

- Laravel 5.5.28
- PHP 7.0.25
- MySQL 5.7.18

**Comment by akhileshdarjee** [comment]
@taylorotwell : The bug exists since Dec 16 2014, check #2968. It's very annoying, please fix this :)

**Comment by themsaid** [comment]
@akhileshdarjee please feel free to fix it, it's an open source framework :) We all help fixing stuff.

**Comment by GuidoHendriks** [comment]
But then there's like a 50% chance of it being closed without a comment. 🙈

**Comment by akhileshdarjee** [comment]
@themsaid : I lack coding skills to fix it, after lots of research I found a package which seems to solve this issue & I confirm it's working on Laravel 5.5:
https://github.com/krossroad/laravel-unionpaginator

I found one more script but haven't tested yet:
https://github.com/SMATAR/laravel-union-paginator

I hope this bug will be solved soon, probably in next release ;)

**Comment by Porrapat** [comment]
Use this one instead until bug is fixed. 
It's worked for now.
https://itsolutionstuff.com/post/how-to-add-pagination-with-union-in-laravel-4-and-laravel-5

**Comment by akhileshdarjee** [comment]
@Porrapat : The solution you suggested has a big drawback. It will first fetch all the records from the table and then perform the union+pagination. This will crash or will get considerably slow if a table has 50k+ records. Check this library, it solves the issue exactly as needed:

https://github.com/krossroad/laravel-unionpaginator

**Comment by Porrapat** [comment]
@akhileshdarjee Thank you, but, unfortunately, my project using Laravel 5.2. So, I am not sure it work with my current code with Laravel 5.2 yet.

**Comment by Porrapat** [comment]
@akhileshdarjee The second thing is my query is build from query builder but your suggest library use for Eloquent only. So, how about solution that can work with Laravel 5.2 or less and use query builder.

**Comment by Porrapat** [comment]
I found this one. Maybe, someone have to test it.
https://github.com/kaizer666/LaravelUnionPaginator

**Comment by Porrapat** [comment]
Tested!

This one solve my problems.

https://github.com/kaizer666/LaravelUnionPaginator

**Comment by nazer17** [comment]
simply use new instance of paginaton and pass your variable to that

**Comment by andresilva96** [comment]
I got a solution!

In class:

```
$todos = (new Todo())
            ->select('todos.files', 'u.name', 'todos.created_at')
            ->join('users AS u', 'u.id', '=', 'todos.user_id')
            ->whereNotNull('files');

        $comments = (new Comment())
            ->select('comments.files', 'u.name', 'comments.created_at')
            ->join('users AS u', 'u.id', '=', 'comments.user_id')
            ->whereNotNull('files')
            ->union($todos)
            ->get()
            ->toArray();

        $currentPage = $request->get('page')?:1;
        $perPage = 1;
        $currentItems = array_slice($comments, $perPage * ($currentPage - 1), $perPage);
        $files = new LengthAwarePaginator($currentItems, count($comments), $perPage, $currentPage, ['path' => 'files']);

        return view('views', ['files' => $files]);
```

On blade:
```
{{$files}}
@foreach($files as $file)
      {{$file['name']}}
@endforeach
```

**Comment by andresilva96** [comment]
I got a solution!

In class:

```
        $todos = (new Todo())
            ->select('todos.files', 'u.name', 'todos.created_at')
            ->join('users AS u', 'u.id', '=', 'todos.user_id')
            ->whereNotNull('files');

        $comments = (new Comment())
            ->select('comments.files', 'u.name', 'comments.created_at')
            ->join('users AS u', 'u.id', '=', 'comments.user_id')
            ->whereNotNull('files')
            ->union($todos)
            ->get()
            ->toArray();

        $currentPage = $request->get('page')?:1;
        $perPage = 1;
        $currentItems = array_slice($comments, $perPage * ($currentPage - 1), $perPage);
        $files = new LengthAwarePaginator($currentItems, count($comments), $perPage, $currentPage, ['path' => 'files']);

        return view('views', ['files' => $files]);
```

On blade:
```
{{$files}}
@foreach($files as $file)
        {{$file['name']}}
@endforeach
```

**Comment by andresilva96** [comment]
I got a solution!

In class:

```
        $a = Order::where(['a' => 2])->whereIn('status', [3, 5]);
        $b = Order::where(['b' => 1])->whereIn('status', [3, 5]);
        $union = $a->union($b)->get()->toArray();

        $currentPage = $request->get('page')?:1;
        $perPage = 1;
        $currentItems = array_slice($union, $perPage * ($currentPage - 1), $perPage);
        $result = new LengthAwarePaginator($currentItems, count($union), $perPage, $currentPage, ['path' => 'files']);

        return view('views', ['result' => $result]);
```

On blade:
```
{{$result}}
{{$result->links('something_here_or_delete')}}
```
