### ISSUE TITLE
[5.1] Illuminate\Foundation\Testing\CrawlerTrait::post Does Not Execute Controller Method

### ISSUE THREAD

**Issue by nkrh** [laravel/framework#21952]
- Laravel Version: 5.1.46
- PHP Version: 7.1.10

### Description:
The post method in test class does not fire any controller method.

### Steps To Reproduce:

1. Create a controller `TestController` with `store` method
2.  Add a code in `TestController::store` to log something to a log file or any code to verify that the method is executed
3.  Add this code to app\Http\Routes\routes.php:
`Route::post('/test', ['as' => 'test', 'uses' => 'TestController@store']);`
4. Create a test and put this code into a method in the test:
`$this->post('/test', [ 'id' => 'foo' ]);`
5. Run phpunit
6. Open the log file. The logged text won't be in there

Thanks!

**Comment by Dylan-DPC** [comment]
5.1 is no longer supported. Use the forums or slack channel to solve your issue
