### ISSUE TITLE
console command finished inexplicable

### ISSUE THREAD

**Issue by BigKuCha** [laravel/framework#21969]
- Laravel Version: 5.4
- PHP Version: 7.1.8
- Database Driver & Version: mysql 5.7.17

### Description:
```php
$query = TblA::select("tbl_a.*", "tbl_b.somecolumn")
            ->join('tbl_b', 'tbl_a.bid', 'tbl_b.id')
            ->whereRaw('tbl_b.somecolumn is NULL')
            ->orderBy('tbl_a.id');

$this->output->progressStart($query->count());
$query->chunk(1000, function ($tblas) {
            $ids = [];
            foreach ($tblas as $tbla) {
                $this->output->progressAdvance();
                if (xxx) {
                    $ids[] = $tbla->id;
                }
            }
           $this->info(' ' . count($ids) . ' rows deleted');
           TblA::whereIn('id', $ids)->delete();
        });
$this->output->progressFinish();
```
### result:

<img width="604" alt="la88" src="https://user-images.githubusercontent.com/5095944/32434679-c58ebc38-c319-11e7-95fb-0e2bbd7d4d3a.png">

**Comment by Dylan-DPC** [comment]
Can you elaborate? What behaviour you were expecting?

**Comment by Dylan-DPC** [comment]
Add to that, 5.4 is no longer supported

**Comment by BigKuCha** [comment]
@Dylan-DPC I want to delete about 20 million rows, with this console script, I should execute many times... I hope it will only be executed once

**Comment by Dylan-DPC** [comment]
@BigKuCha this repo is for bug tracking. You can try the forums or the slack channel

**Comment by sisve** [comment]
You're only processing half the amount of rows because you're deleting stuff, and chunk() isn't existing that. Chunk will fetch you page 1, process it, then fetch page 2, process it, etc. Since you remove the entries the items on page 2 is moved to page 1, and when chunk fetches what it believes is page 2 it is the items that was originally on page 3.

https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Concerns/BuildsQueries.php#L28

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.

**Comment by BigKuCha** [comment]
@sisve Thank you very much ,I understand 👍   And many thanks to other ones!
