### ISSUE TITLE
First() method does not return NULL

### ISSUE THREAD

**Issue by xmoroccan** [laravel/framework#21974]
- Laravel Version: 5.5.19
- PHP Version: 7.1.9
- Database Driver & Version: MariaDB 10.1.26

Actually, it's not a problem, I think `first()` method on QueryBuilder does not return a `NULL` when there are no results, so we can't check with `=== NULL`, I'm right?
But the API docs mention that this method can return a `NULL`, if yes which cases this method return `NULL`.
Note: I use `exists()` to check if there is a result.

Refs:
https://laravel.com/api/5.5/Illuminate/Database/Eloquent/Builder.html#method_first

**Comment by themsaid** [comment]
It returns `null` indeed, this issue report isn't complete thus we can't help, please submit steps to replicate the issue.

**Comment by billywatsy** [comment]
l had a similar issue , and l find out that **first** returns **null** but it can be when returned value is null on an api response  then it will return an empty object
