### ISSUE TITLE
make ThrottleRequests highest priority

### ISSUE THREAD

**Issue by ganganimaulik** [laravel/framework#21986]
- Laravel Version: 5.5.19
- PHP Version: 7.1
- Database Driver & Version: mysql  (version doesn't matter).

### Description:
I was creating api and I am using **\Illuminate\Routing\Middleware\ThrottleRequests** middleware for rate limiting. now issue is that there are many other middlewares which executes before ThrottleRequests causing high loads on cpu.

### Steps To Reproduce:
just apply throttle middleware to any route and check middleware execution order by using `Log::` statements.

### Solution
make ThrottleRequests high priority.

**Comment by sisve** [comment]
Isn't this something you can change yourself in your RouteServiceProvider?

**Comment by ganganimaulik** [comment]
I have been able to fix it for myself using $middlewarePriority in kernel.php but I am suggesting it to make it default.
