### ISSUE TITLE
[5.5] Gate facade mock fails to mock out allows() method

### ISSUE THREAD

**Issue by RikSomers** [laravel/framework#21987]
- Laravel Version: 5.5.x
- PHP Version: 7.0.22
- Database Driver & Version: -

### Description:
When using the facade mocks, an error will be returned when trying to mock out the `allows` method of the Gate facade.

### Steps To Reproduce:
- Fresh install of Laravel 5.5
- Add the following test to a phpunit test file :
```php
/** @test */
public function the_gate_will_error() { 
    Gate::shouldReceive('allows')->once()->andReturn(true);
} 
```
- Run the test

You will then get the following error:
```
 [Symfony\Component\Debug\Exception\FatalErrorException]
  Cannot redeclare Mockery_0_Illuminate_Auth_Access_Gate::allows()
``` 

This is probably caused by Mockery implementing a `allows()` and `expects()` method since version 1.0

**Comment by namelivia** [comment]
Having the same issue over here, I haven't figured out yet a possible solution for this.

**Comment by RikSomers** [comment]
We eventually just went with removing the mocking of that part entirely, since part of what we wanted to actually test was in those gate methods.

**Comment by namelivia** [comment]
I've been investigating the issue and I don't see any other solution than renaming the allow method on the Gate class which I suppose is not desirable due to prior version compatibilty issues, I wonder if someone with deeper knowledge than me comes with a better solution.

**Comment by namelivia** [comment]
Still happening on 5.6, as far as I know there is no easy way to fix this.

**Comment by aedart** [comment]
Now facing the same issue. I cannot mock this the `Gate` interface. I know that this isn't Laravel issue - therefore, I created the following issue:
https://github.com/mockery/mockery/issues/861

Hopefully they can fix it, because it is frustrating...

**Comment by driesvints** [comment]
There's a PR now for this: https://github.com/mockery/mockery/pull/868

Hope they'll merge it soon. Closing this as this is more of an issue of Mockery instead of Laravel.
