### ISSUE TITLE
Str::plural() returns singular for decimal quantity between 1 and 2

### ISSUE THREAD

**Issue by fitztrev** [laravel/framework#21983]
- Laravel Version: 5.5.19

### Description:

`Str::plural()` returns singular when `1 < $count < 2`.

I proposed a solution in #21973 but it was suggested that wasn't the right fix.

### Steps To Reproduce:

```php
$days = 1.5;
echo $days . ' ' . str_plural('day', $days);
// Actual => "1.5 day"
// Expected => "1.5 days"
```

**Comment by jeffochoa** [comment]
You can use [ceil()](http://php.net/manual/en/function.ceil.php) around the `$days`var like:

```php
str_plural('day', ceil($days));
```

**Comment by fitztrev** [comment]
That won't work if `$days == 0.5`. I added tests to the PR that show what
the expected results should be.
