### ISSUE TITLE
[Pusher] Send a native notification via the Push Notifications Api

### ISSUE THREAD

**Issue by arcanedev-maroc** [laravel/framework#22001]
Pusher has an [extra method](https://github.com/pusher/pusher-http-php/blob/master/src/Pusher.php#L636) for sending a native notification (iOS & Android) via the pusher API.

You can check the documentation about this feature:

 * https://pusher.com/push-notifications
 * https://pusher.com/docs/push_notifications

Any thoughts on this for broadcasting features ?

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. This isn't a bug so you can open a proposal in the laravel/internals repo

**Comment by arcanedev-maroc** [comment]
Moved: https://github.com/laravel/internals/issues/871
