### ISSUE TITLE
postAutoloadDump missing in ComposerScripts.php

### ISSUE THREAD

**Issue by LastxTemplar** [laravel/framework#22003]
- Laravel Version: 5.4 to 5.5
- PHP Version: 7.0

### Description:
I upgraded my Laravel version from 5.4 to 5.5 by going through the steps in the Documentation. I modified everything I needed to modify and then ran **composer update**

### Steps To Reproduce:
1. Install laravel 5.4: **composer create-project --prefer-dist laravel/laravel blog_test "5.4.*"**
2. Change the **composer.json** file according to this [Documentation](https://laravel.com/docs/5.5/upgrade)
3. run **composer update**
4. "You made a reference to a non-existent script @php artisan package:discover" appears at the end of the run

**Comment by devcircus** [comment]
Search the issues here and you'll see what's happening. You'll need an updated composer and the latest laravel installer.

**Comment by LastxTemplar** [comment]
Could you explain a bit in more detail?

**Comment by devcircus** [comment]
Just search the issues for this and you'll find a lot of details. If you can't find it, I'll post some links shortly.

**Comment by LastxTemplar** [comment]
I searched but can't seem to find anything relevant...

**Comment by LastxTemplar** [comment]
Ok, I figured it out thanks to your tips. I did **composer global update** then composer update and it seems to have worked. Not sure why **ComposerScripts.php** file and the easier **Laravel Project Init** would be so tied to each other.
