### ISSUE TITLE
[5.5] WithoutEvents trait crashes test when instantiating a model with boot events.

### ISSUE THREAD

**Issue by dlett** [laravel/framework#22007]
- Laravel Version: v5.5.19
- PHP Version: PHP 7.1.4-1
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.6.36, for Linux (x86_64) using  EditLine wrapper

### Description:
[MocksApplicationServices](https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Testing/Concerns/MocksApplicationServices.php#L101) trait defines that the event dispatcher should receive 'fire' and 'dispatch' but does not include 'listen' which is used by the model for events defined against the model directly. When these events are attempting to be added to the dispatcher, the test fails:
![image](https://user-images.githubusercontent.com/366433/32558224-44549264-c472-11e7-8d43-7aa8d957e04f.png)

### Steps To Reproduce:

Create a model that utilizes events on the model itself, eg:
```php
    protected static function boot()
    {
        parent::boot();
        static::creating(function (Model $model) {
            // snip
        });
    }
```

**Comment by dlett** [comment]
Including a proposal to fix:
https://github.com/laravel/framework/pull/22008

Not sure if there are other ramifications to this that I am not thinking of, but this would certainly fix the issue at hand.

**Comment by themsaid** [comment]
@dlett PR is wrong, will look into this in a bit.

**Comment by themsaid** [comment]
Can't replicate:

```
public function testBasicTest()
{
    $this->withoutEvents();

    User::create(['name' => 'asd', 'email' => 'asd', 'password' => 'asd']);
}
```

```
protected static function boot()
{
    parent::boot();

    static::creating(function ($model) {
        log(1);
    });
}
```

**Comment by dlett** [comment]
Calling `$this->withoutEvents();` actually has a different effect than using the `Illuminate\Foundation\Testing\WithoutEvents` trait in your class. 

If you change your test to use the trait then you will see the failure. This is because Illuminate\Foundation\Testing\TestCase::setUp() runs `$this->setUpTraits()` on line 71 and then on line 79 runs `Model::setEventDispatcher($this->app['events']);` which rebinds the event dispatcher to the model instance which does not happen if you run `$this->withoutEvents()` directly in the test.

Here is an example of the test class that will fail:
```php
class ExampleTest extends TestCase
{
    use WithoutEvents;

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testBasicTest()
    {
//        $this->withoutEvents();

        User::create(['name' => 'asd', 'email' => 'asd', 'password' => 'asd']);
    }
}
```

@themsaid

**Comment by themsaid** [comment]
Oh thanks :)

Here's a fix https://github.com/laravel/framework/pull/22012

**Comment by themsaid** [comment]
Oh thanks :)

Here's a fix https://github.com/laravel/framework/pull/22012
