### ISSUE TITLE
Rendering basic auth exception in 5.5

### ISSUE THREAD

**Issue by kevinfoley** [laravel/framework#22016]
- Laravel Version: 5.5.1
- PHP Version: 7.1.2

### Description:

Our API uses the HTTP basic auth functionality that is built into Laravel. Authentication is handled by `laravel/framework/src/Illuminate/Auth/SessionGuard.php`

 I am trying to render an HTTP basic authentication error as JSON. I have modified the `render()` method of the `app\Exceptions\Handler.php` file:

    public function render($request, Exception $exception)
    {

        //Handle API authentication failure
        if ($exception instanceof \Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException) {
            return response()->json(['error' => 'Invalid user name or password.'], 401);
        }

        return parent::render($request, $exception);
    }

However, after adding the `if` block, *every* login attempt returns the JSON error, even when valid credentials are used. If I remove the `if` block, login works again.

Am I doing something wrong, or is this a bug in Laravel?

**Comment by sisve** [comment]
Check the http requests issued. The UnauthorizedException needs to send back some headers that tells the browser to use basic authentication, and you're not setting them in the json response.

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.

**Comment by kevinfoley** [comment]
@themsaid Apologies; this seemed like a possible Laravel bug to me, or I would not have brought it up here.
