### ISSUE TITLE
Auth and redirection broke in 5.5

### ISSUE THREAD

**Issue by HawkonDK** [laravel/framework#22015]
## Routes
the web.php total ignore that people who issen't logged in should not access the middleware group

```
Route::get('/', function () {
    return view('login');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function ()
{
    Route::get('district/{id?}', 'DistrictController@index')->name('district');
});


Route::get('/logout', 'Auth\LoginController@logout');
```

## The Redirection in 5.5 are horrible

in 5.5 there are so many things you need to change before it works, example login.. oh yes login, at the documentation page you say change LoginController.php RedirectTo but in real life this do absolute nothing. instead you have to change it 3 diffrent places before it accepts it.

## Laravel Cache

The cache is horrible and make it hard to develop a page because you need to reset again and again

## Logout not clear session

the build in logout function dos not logout the user! This is so ignoring

## Lot of code

There is a lot of code there doesn't do anything, Laravel should be cleaned up

**Comment by ntzm** [comment]
Feel free to submit pull requests for these "issues"

**Comment by jeffochoa** [comment]
HI @HawkonDK 

About this issues:

## Login redirection
Yes, as you can read in the docs, it seems you have to change the redirection path in 3 locations:

> You can customize the post-authentication redirect location by defining a redirectTo property on the  LoginController, RegisterController, and ResetPasswordController:

## Logout route
It seems if like you are overwriting the logout route which should be a "POST" route, not a "GET" one

`Route::get('/logout', 'Auth\LoginController@logout');`

If you go to the terminal and run (from the project root path) : 

`php artisan route:list`

You'll see the logout rute which is created when you use `Auth::routes();`  in your routes file.

## Laravel cache
You can just change the cache driver in your `.env` file:
`CACHE_DRIVER=array`

## Lot of code

You can open a new issue to add more information about which specific block of code should be removed and why, or even better you can open a Pull Request with the fixes if you want. That's the great thing about open source :wink:

[Learn more about "how to contribute" here ](https://laravel.com/docs/5.5/contributions#bug-reports)

I hope this could help you.

**Comment by HawkonDK** [comment]
as I said this 

> You can customize the post-authentication redirect location by defining a redirectTo property on the LoginController, RegisterController, and ResetPasswordController:

not work at all. even on a clean install
