### ISSUE TITLE
Eloquent: issue when asking for a field as empty string

### ISSUE THREAD

**Issue by Scutto** [laravel/framework#22024]
I don t use Laravel but just the Eloquent package ("illuminate/database": "5.2.37")
- PHP Version: 5.6.30
- Database Driver & Version: mysql 5.6.35

Description:
In my script I was try to get different fields from a model, using an array containing the name of the fields that I want to get and lopping over it.
For my mistake one of the field was an empty string ('') and eloquent instead of throwing an error, start to do some weird stuff, it looks like its going into an infinite loop (since the script never stops to run also waiting 5 minutes (without the empty field takes 2/3 seconds) ) but the biggest issue is that somehow the memory in my pc was getting all filled up from the script.
Example I checked the available storage in my pc before run the script (40GB), after 2/3 minutes of the script running the available was around 20GB.

Steps To Reproduce:
$array = ['name', 'birth_date', 'gender', ''];
$model = Model::where('id', 1)->first();
$store = [];

foreach($array as $field_to_get){
     $store[] = $model->$field_to_get;
}

Works just fine for the first 3 fields, when it reach the last one starts the issue.

**Comment by Dylan-DPC** [comment]
Laravel or illuminate package versioned 5.2 is no longer supported. Also it is recommended to use [markdown](https://guides.github.com/features/mastering-markdown/) while pasting code in an issue.

**Comment by Scutto** [comment]
Okay, well maybe someone with the latest version can check if this error is still there or not !

**Comment by sisve** [comment]
Looks like it was fixed in 5.3.19 -https://github.com/laravel/framework/commit/cd3e3cda0e4993f7825379a5c5b3a3cdc5fd6a29
