### ISSUE TITLE
Laravel dusk failed with ckeditor

### ISSUE THREAD

**Issue by danisjohn99** [laravel/framework#22021]
- Laravel Version: 5.5
- PHP Version:7.0.10
- Database Driver & Version: MySQL & 5.7.14

### Description
I can't run dusk-cases with CKEditor  , is anyone knows how to do that?

When i tested i got this error !

Tests\Browser\DuskDepartmentTest::testDepartmentCreate Facebook\WebDriver\Exception\InvalidElementStateException: invalid element state : Element is not currently interactable and may not be manipulated

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
