### ISSUE TITLE
whereBetween pass the first value

### ISSUE THREAD

**Issue by LusenkoSasha** [laravel/framework#22025]
- Laravel Version: 5.5
- PHP Version: 7.1
- Database Driver & Version: MySql 5.6

### Description:
`$posts = Post::where('page_id', '=', $data->id)->where(function($query) use($request){
if($request->has('date_start') && $request->has('date_end')){
$query->whereBetween($request->input('date_start'), ['date_start','date_end'])
->orWhereBetween($request->input('date_end'),['date_start','date_end']);
}
 })->paginate(8);`

SQLSTATE[42S22]: Column not found: 1054 Unknown column '2017-11-08' in 'where clause' (SQL: select count(*) as aggregate from `Posts` where `page_id` = 18 and (`2017-11-08` between date_start and date_end or `2017-11-09` between date_start and date_end)) 

In sql itself it works

SELECT * FROM `posts` WHERE '2017-11-08 00:00:00' BETWEEN `date_start`  AND `date_end` OR '2017-11-09 00:00:00' BETWEEN `date_start` AND `date_end`

**Comment by Dylan-DPC** [comment]
This is intended behaviour. the first parameter passed to `whereBetween()` should be a column. You are not mentioning which column it should fetch from. 
This repo is for bug tracking. So refer the docs, or post in forums/slack channel if you need more help.
