### ISSUE TITLE
Fillable allows insert any data

### ISSUE THREAD

**Issue by deividaspetraitis** [laravel/framework#22028]
- Laravel Version: 5.5.x
- PHP Version: 7.1
- Database Driver & Version: N/A

### Description:

I was working with few features on my project and noticed that laravel $fillable is not working as expected and allows to input any columns and values.

### Steps To Reproduce:

1. Install new app: `laravel new blog`

2. Edit: DatabaseSeeder.php : 

```
        $user = \App\User::create(["test" => "test"]); // First case 

        $user = new \App\User();
        $user->fill(["test" => "test"])->save(); // Let's fill first of all and only after that try to save
```

Note that I do not changed original generated User model contents however to be more specific here its: https://gist.github.com/deividaspetraitis/4c124538bf1f254ce224b3839622cc49

3.  Run: `php artisan db:seed`

It will produce something like:

```
[Illuminate\Database\QueryException]                                                                                                                                                                               
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'homestead.users' doesn't exist (SQL: insert into `users` (`test`, `updated_at`, `created_at`) values (test, 2017-11-09 11:41:49, 2017-11-09 11:41:49)) 
```

It doesn't matter that we don't have table at this case since interested only in query it self and as we can see it is allowing to push `test` column even it's not defined and whitelisted in our model. Is it a normal behaviour, did I missed something in docs?

_Issue is produced only in CLI mode._

**Comment by Dylan-DPC** [comment]
How is this error related to `$fillable`? This repo is for bug tracking so if you need help I advise you to use forums or slack channel.

**Comment by deividaspetraitis** [comment]
@Dylan-DPC I believe it related `$fillable` property. Let me be more specific:

Inserting data:

`  $user = \App\User::create(["test" => "test"]); // test column

Our `$fillable` property:

```
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', // we do allow only these?
    ];
```
And generated query:

> `insert into `users` (`test`, `updated_at`, `created_at`) values (test, 2017-11-09 11:41:49, 2017-11-09 11:41:49)`

We do have allowed insert values only for these columns:  'name', 'email', 'password' but generated query is trying to insert into `test` column. Isn't that a bug?

**Comment by decadence** [comment]
Seeder runs with `Model::unguard`

**Comment by deividaspetraitis** [comment]
@decadence thank you!
