### ISSUE TITLE
php artisan make:auth conflicts with route:cache 'Unable to prepare route [api/user] for serialization. Uses Closure.'

### ISSUE THREAD

**Issue by lvbeck** [laravel/framework#22034]
- Laravel Version: 5.5.20
- PHP Version: 7.0.22
- Database Driver & Version: mysql 5.7

### Description:

I use 'php artisan make:auth' command to scaffold routes and views for authentication, however when I run 'php artisan route:cache', an error will occur: 
```
[LogicException] Unable to prepare route [api/user] for serialization. Uses Closure.
```
### Steps To Reproduce:

1. create a new project with "laravel/installer"
2. run 'php artisan make:auth'
3. run 'php artisan route:cache'

**Comment by haakym** [comment]
Can you check your `routes/web.php` and `routes/api.php` for closures.

Laravel comes with default route closure in [`routes/web.php`](https://github.com/laravel/laravel/blob/master/routes/web.php#L14):

```
Route::get('/', function () {
    return view('welcome');
});
```

and [`routes/api.php`](https://github.com/laravel/laravel/blob/master/routes/api.php#L16)

```
Route::middleware('auth:api')->get('/user', function (Request $request) {
    return $request->user();
});
```

 if you remove that then try again it should work I reckon.

**Comment by lvbeck** [comment]
@haakym thanks, I know it will works if I remove above code in routes/api.php, but is there any side effect to do so?
will the route "api/user" still working?

**Comment by lvbeck** [comment]
I did found a serious side effect after the changes,

now, I can run 'php artisan route:cache' with no problem,  but I got a runtime exception:
```
Session store not set on request.
```

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.

**Comment by xkovacikm** [comment]
@themsaid Please, stop throwing responsibility on the others. This is definitely a bug. 
Laravel offers predefined code in routes/api.php

`Route::middleware('auth:api')->get('/user', function (Request $request) {
    return $request->user();
});`

 which is unabled to be processed by:

`php artisan route:cache`

This definitely should be fixed.

**Comment by themsaid** [comment]
@xkovacikm feel free to open a PR

**Comment by feribg** [comment]
Why is this closed? This is an obvious bug.

**Comment by devcircus** [comment]
Straight from the documentation:
> IF your application is EXCLUSIVELY using controller based routes, you should take advantage of Laravel's route cache.
> Closure based routes cannot be cached. To use route caching, you must convert any Closure routes to controller classes.

**Comment by feribg** [comment]
@devcircus Im not really involved with laravel I just raise the point because I downloaded the framework, enabled a built in feature--> auth and it broke another built in and critical feature of any  production deployment,  notably clearing the cache. So wether the default way auth routes come out of the box changes or how the cache clearing changes doesn't matter really but a framework shouldn't break a production deployment once a core built in module is enabled with the default config in my opinion. If that's not your opinion I understand.

**Comment by devcircus** [comment]
The "auth" method has no effect on route caching. The method (below) only adds controller based routes, which are perfectly cacheable.
```php
    public function auth()
    {
        // Authentication Routes...
        $this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
        $this->post('login', 'Auth\LoginController@login');
        $this->post('logout', 'Auth\LoginController@logout')->name('logout');
        // Registration Routes...
        $this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
        $this->post('register', 'Auth\RegisterController@register');
        // Password Reset Routes...
        $this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
        $this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
        $this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
        $this->post('password/reset', 'Auth\ResetPasswordController@reset');
    }
```
The issue is that in the laravel/laravel skeleton app, there are a couple of sample Closure routes included in the api and web routes files. These routes are present for example purposes. Route caching is a documented optional feature. This documentation makes it clear that if you want to cache your routes, you'll need to be sure to use the controller based approach for it to work.

There are many features in Laravel that don't just "work" out-of-the-box. You can change your "session", "cache" and/or "queue" handling to use redis. However if you just change this to redis and expect it to just work, you'll be disappointed, as there are other libraries that need to be pulled in first. I just don't believe that we can expect everything provided by the framework to just work. Sometimes you have to do a little research and make sure everything is set up correctly first.

**Comment by haakym** [comment]
@xkovacikm IMO I don't think this can be called a bug. Sure, it's annoying that if you want to cache your routes and you don't remove the pre-defined closure routes it won't work, but it's a matter of removing them to get it to work. As @themsaid said a PR can be made which I think would be a good way of pursuing this discussion further. I'll put in a PR later with the closures moved to default controllers and see where it goes from there...

**Comment by vipertecpro** [comment]
I just remove all the files in bootstrap/cache folder and it's working, i think laravel should update with auto cache clear feature or maybe we can do something in composer file like after running composer update...it should remove the files from bootstrap folder, but anyways please let us know if bug is fixed or not ?

**Comment by xmaop** [comment]
I found the answer. https://stackoverflow.com/questions/45266254/laravel-unable-to-prepare-route-for-serialization-uses-closure

**Comment by AbdulAzizi** [comment]
Had this error `Unable to prepare route [api/user] for serialization. Uses Closure.`
Commented :
```
Route::middleware('auth:api')->get('/user', function (Request $request) {
    return $request->user();
});
```
Executed `php artisan route:cache` and it worked. I agree with @xkovacikm I think it must be fixed.

**Comment by Servietteski** [comment]
Still not fix 2 years later. Go fuck yourself

**Comment by panique** [comment]
Still an issue for me on Laravel 6.12. Not sure if it's me or the bug still exististing. Can anybody confirm for 6.12 ?

**Comment by marchershey** [comment]
also having this issue.

**Comment by seralkhatem123** [comment]
Route::middleware('auth:api')->get('/user', function (Request $request) {
    return $request->user();

**Comment by ebrahimahmadi** [comment]
still having the same issue on laravel 6.x

**Comment by devcircus** [comment]
make:auth drops in example routes that use closures. If you want to cache your routes, just remove the closure routes. There's no bug here. It's known that php doesn't serialize closures and this is pointed out in the Laravel docs. There are third party packages that allow this but Laravel doesn't include any.

**Comment by Edbtvplays** [comment]
> make:auth drops in example routes that use closures. If you want to cache your routes, just remove the closure routes. There's no bug here. It's known that php doesn't serialize closures and this is pointed out in the Laravel docs. There are third party packages that allow this but Laravel doesn't include any.

how is it fixable then?

**Comment by bremg** [comment]
Unbelievable. This is still an issue in Laravel 7.x

Deleting the default api routes fixes the problem
