### ISSUE TITLE
Immutable string in request validation output

### ISSUE THREAD

**Issue by DarkGhostHunter** [laravel/framework#22035]
https://github.com/laravel/framework/blob/8be87d4cdf7b221a58f64fe87d61b1aad49f6f68/src/Illuminate/Validation/ValidationException.php#L56

The string `The given data was invalid` cannot be changed or localized during the validation process. Any localization effort proves to be futile.

**Comment by sisve** [comment]
> Any localization effort proves to be futile.

Override the invalidJson method (I presume you're talking about a validation failure over json here) in your exception handler and return whatever you want.

https://github.com/laravel/framework/blob/8be87d4cdf7b221a58f64fe87d61b1aad49f6f68/src/Illuminate/Foundation/Exceptions/Handler.php#L267-L273

**Comment by Dylan-DPC** [comment]
True @sisve but I find the string being hardcoded in other exceptions as well. It won't be a bad idea to enable a way of customisation for this.

**Comment by themsaid** [comment]
Responses are meant to be customizable, if you don't like a default response you can always override it, as for other exceptions, I don't really see a benefit in localizing internal exceptions.

**Comment by DarkGhostHunter** [comment]
Then [`$request->validate`](https://laravel.com/docs/5.5/validation#quick-writing-the-validation-logic) uses an internal exception that is outputted? It returns an array AFAIK, so the other way around would be to edit the array before anything else (if the validation fails, of course), and override the message.
