### ISSUE TITLE
Lang::get performance

### ISSUE THREAD

**Issue by adri3nam** [laravel/framework#22047]
- Laravel Version: 5.5
- PHP Version: 7.0

### Description:
If I pass an big array as second parameter of Lang::get() to the replace place-holders in my translation string, the code is significantly slower. My array was made of 177 values, it's enough big, but it could means that several calls of Lang::get can slow down an application even with smaller arrays.

### Steps To Reproduce:
Pass an array of more than 170 items

**Comment by Dylan-DPC** [comment]
Hi. This repo is for bug tracking and this cannot be considered one. You can make a proposal in laravel/internals repo
