### ISSUE TITLE
Milliseconds being Trimmed on SQL queries.

### ISSUE THREAD

**Issue by kevupton** [laravel/framework#22048]
- Laravel Version: 5.5.*
- PHP Version: 7.1.9
- Database Driver & Version: ibmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: b396954eeb2d1d9ed7902b8bae237b287f21ad9e $

### Description:
When I select `TIME(3)` from the database the resulting millisecond precision is trimmed from the data.

### Steps To Reproduce:
1. Create a column which is of type `TIME(3)`.
2. Create some datasets for this field, with millisecond precision.
3. Run a `SELECT MAX(time) max, MIN(time) time FROM table`. Using the `\DB` Facade. (Either query builder or not).
4. `var_dump` the results.
5. Notice how the precision has been trimmed from the time fields. 

Note: I figured this is laravel specific, because when I run a raw php script. Which simply does the same thing, (outside of laravel) the result contains the precision. It also works in phpmyadmin.

**Comment by Dylan-DPC** [comment]
Which minor (last number in version) version are you on? https://github.com/laravel/framework/pull/21936 might have fixed your issue

**Comment by paulofreitas** [comment]
@Dylan-DPC Actually #21936 haven't fixed this issue because currently no grammar honor the given precision. See #22004.

**Comment by kevupton** [comment]
Dam ok, thanks. I will just do a manual workaround for now.

**Comment by paulofreitas** [comment]
@kevupton This was implemented in #22122 and should be included with Laravel 5.5.22 when released. :wink:

Do you mind closing this issue now that it got resolved? Thanks for reporting this, it was helpful to get this functionality implemented. 👍

**Comment by kevupton** [comment]
Woo ! Awesome, look forward to the release. 🥇
