### ISSUE TITLE
Using $manifestDirectory parameter with mix() helper method results in a bad path.

### ISSUE THREAD

**Issue by twilsman** [laravel/framework#22046]
- Laravel Version: 5.5
- PHP Version: 7.1
- Database Driver & Version: maria db 10.1.23

### Description:
When calling the `mix()` helper function, using the `$manifestDirectory` parameter, the value of `$manifestDirectory` gets pre-pended to the `$path` being retrieved from the manifest.  This results in a malformed url like: `http://localhost/js/custom_dir//js/custom_dir/file.js?[hash]`.

https://github.com/laravel/framework/blob/26f16799c4de44ae09384058c71d5d28feb0af12/src/Illuminate/Foundation/helpers.php#L583

### Steps To Reproduce:

I wrote a custom cache busting script.  I'm trying to use `Manifest.hash()` to cache-bust some scripts from a completely different webpack config.

```
require("laravel-mix");
let Manifest = require("laravel-mix/src/Manifest");

let manifest = new Manifest("js/custom_dir/mix-manifest.json");

manifest.hash("/js/custom_dir/file.js");
manifest.refresh();
```
This script works correctly.

Then, I try to retrieve this script using:
```
<script src="{{mix('js/custom_dir/file.js', 'js/custom_dir/') }}"></script>
```

That results in the following output:
```
<script src="/js/custom_dir//js/custom_dir/file.js?id=f44b50ab40585d355797"></script>
```

**Comment by twilsman** [comment]
Should I have posted this at https://github.com/JeffreyWay/laravel-mix/ ?

**Comment by themsaid** [comment]
This is intended, you need to do this:

```
{{mix('file.js', 'js/custom_dir') }}
```

**Comment by twilsman** [comment]
Thank you for the clarification.  I think there's still a potential bug here though.

When I call `manifest.hash("/js/custom_dir/file.js");`, `/js/custom_dir/file.js` becomes the key in the hash.

If try to get it with `{{mix('file.js', 'js/custom_dir') }}`, the mix function only uses `/file.js` to look up the value, and I get an Undefined Index exception.
