### ISSUE TITLE
Api Resource + Vuejs + Axios

### ISSUE THREAD

**Issue by Dimidel** [laravel/framework#22059]
- Laravel Version: 5.5
- PHP Version: 7.0
- Database Driver & Version: MySQL

### Description:
Hi,
I'm trying to use the new Laravel 5.5 Api Resource for the backend and VueJs + Axios for the frontend and i'm encountering a weird problem : 
The data given by the Api endpoint are wrapped into a data object and the response given by the Axios request is also wrapped into a data object. Consequently, the response of the Axios request is double wrapped into nested data object (response.data.data).
Am I doing something bad to obtain such a weird result ?
Is there a better way to achieve this properly ?
Thank in advance

### Steps To Reproduce:
Exemple : 

Vue.js
`
        methods: {
            getPosts() {
                Vue.axios.get('/api/v1/posts')
                    .then(response => this.posts = **response.data.data** )
                    .catch(error => { console.log(error) })
            },
        }
`

PostController
`
    public function index(Request $request)
    {
      (...)
      return new PostCollection(Post::all());
    }
`

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
