### ISSUE TITLE
Laravel Email Button redirection

### ISSUE THREAD

**Issue by jignesh-levaral** [laravel/framework#22053]
- Laravel Version: 5.5.19
- PHP Version: 7.1.3
- Database Driver & Version: mysql

### Description:

i have issue with mail button redirection.
![screenshot-mailtrap io-2017-11-10-16-30-30-076](https://user-images.githubusercontent.com/33521382/32724854-e766d208-c898-11e7-8f0e-ba6d94a705f3.png)

I am using command to send email, where i am setting dynamic app url, which is working,

Example
i have set base url as example.com and changing it as nl.example.com dynamically. so button in email should use that. 

when i click it redirect to

http://example.com/email/l/aHR0cDovL25sLmJ1bGRpdC5hcHAvbmwvcmV2aWV3L2xlYWQvNg==/0HeT7VzkZjjIBZFIfAKg4lkWp6SFgMCJ

where base url should be nl.example.com, so it not redirecting correctly and show page not found

please let me know how to set app url dynamic when sending mail
Config::set('app.url', 'nl.example.com');

where in footer it showing the right url, button encrypted url ignored 'nl', although i have set it dynamically

**Comment by jignesh-levaral** [comment]
Let me know what to do to have proper url 

Thanks

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.

**Comment by jignesh-levaral** [comment]
OOPS!

Okay

**Comment by jigneshparmar126** [comment]
Please
check out this one
https://laravel.io/forum/laravel-email-link-redirect
https://laracasts.com/discuss/channels/laravel/laravel-email-link

i really need help in this one.
