### ISSUE TITLE
Can't use multiple database using pivot tables in many to many relationships

### ISSUE THREAD

**Issue by mrLordiz** [laravel/framework#22058]
- Laravel Version: 5.4.0
- PHP Version: 7.0.23
- Database Driver & Version: mysql

### Description:
When i use a different database for my models, pivot table, in belongsToMany relationship, still uses the project db specified in env.

### Steps To Reproduce:
- create db that will be used by default and is specified in env file
- create db named 'sec_db' for example, create table participants(id), actions(id), participations(participant_id, action_id)
- add a connection in config/database.php representing 'sec_db'
- create model participant and action and set connection to sec_db
- add method participants in action
    public function participants(){
        return $this->belongsToMany(Participant::class, 'participations', 'action_id', 'participant_id');
    }
- create an action and add some participants then try to get participants using the many to many relationship.
It will try to get the pivot table from the main database.

**Comment by Dimimo** [comment]
You may want to have a look at `/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/BelongsToMany.php`, especially the `using`  and `as` public functions. I have no direct experience with your issue, but it seems you might find a workaround in there.

**Comment by themsaid** [comment]
5.4 is not supported anymore, please upgrade to laravel 5.5
