### ISSUE TITLE
Resetting application namespace 

### ISSUE THREAD

**Issue by marufmax** [laravel/framework#22056]
- Laravel Version: 5.5.20
- PHP Version: 7.2
- Database Driver & Version: mysql

### Description:
I just accidently change the default namespace "app" to "Different" namespace. I want back to the default namespace again. How I can do that? The official documentation does not  helping me out.

Thanks

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by marufmax** [comment]
Ok. Should I delete this?

**Comment by sisve** [comment]
You can easily revert the changes you did by just reseting your git branch to the commit before this change, or by just reverting the commit that contains it.
