### ISSUE TITLE
with() and select() not possible?

### ISSUE THREAD

**Issue by carestad** [laravel/framework#22068]
- Laravel Version: 5.5.8
- PHP Version: 7.0.19
- Database Driver & Version: mysql

### Description:

I am trying to eager load a set of relations with my model and at the same time use select() on the "main" model, filtering out the number of columns I fetch and also aliasing some of them. For example:

```php
Model::with(['rel1', 'rel2'])->select(['id', 'foo as bar', 'date'])->find(1)->toArray();
```

But this seems to fail. If I remove the select() part I get my data for Model + rel1 and rel2.

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by brunogaspar** [comment]
@carestad It's possible, just make sure to also include the column you're using for the relations on the select statement.

If that still doesn't work, then you might have something wrong on your code.

**Comment by carestad** [comment]
@Dylan-DPC Yes, and from my understanding this is a bug.

I have been trying to get to the bottom of this on my own, but I don't have enough understanding of Laravel's code to do so.

I recently set up a test Laravel setup and created a test DB and three models. To ease the testing I just did some var_dump'ing in a artisan command created with `php artisan make:command test` (source follows).

# Company
**DB Table**: companies
**Columns**: id, navn, phone, vatno

## Model
```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    protected $table = 'companies';
}
```

# Project
**DB Table**: projects
**Columns**: id, name, description, company

## Model
```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
  protected $table = 'projects';

  public function orders()
  {
    return $this->hasMany('App\Order', 'project', 'id');
  }

  public function company()
  {
    return $this->hasOne('App\Company', 'id', 'company');
  }
}
```

# Order
**DB Table**: orders
**Columns**: id, name, description, price, project

## Model
```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $table = 'orders';
}
```

# test command
```php
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\Project;

class test extends Command
{
    /* (default stuff) */
    public function handle()
    {
      $p1 = Project::with('orders', 'company')->find(1);
      $p2 = Project::with('orders', 'company')->select('id', 'name')->find(1);

      var_dump($p1->toArray());
      var_dump($p2->toArray());
    }
}
```

# Problem

When commenting out the var_dump of `$p2`, I get my expected output.

When also trying to var_dump `$p2`, CPU fans starts running like wild and memory consumption of PHP sky rockets until my computer freezes and in the end either kills PHP or the system.

**Comment by carestad** [comment]
Update: also tested in Laravel 5.5.21 and still problem still persists.

**Comment by carestad** [comment]
I will just make a note here that to make `select()` work with `with()`, one will have to also include the relation models' linked keys as part of the selection. So if `rel1` is refered to in `Model`s table in the column called `rel1_id`, the select statement needs to include `rel1_id`.

**Comment by Dylan-DPC** [comment]
So your issue is that it your query takes too long to execute and dies on the way?

**Comment by carestad** [comment]
Well now that I figured out it was a matter of including the relation's local key in the `select()` it does not happen, but when I left them out that did happen, yes.
