### ISSUE TITLE
Laravel Session in Redis

### ISSUE THREAD

**Issue by chandrapw** [laravel/framework#22065]
- Laravel Version: 5.2
- PHP Version: 5.6
- Database Driver & Version: Redis 3.2.6

### Description:
When i want to get data from session, it basically auto renew the expire time.

### Steps To Reproduce:

- Change the session driver to redis
- Make sure the redis server was running
- Store the session with this code : $req->session()->put($email, json_encode($user));
- Get data with : $req->session()->get('key');

The data was return normaly, and it was success. But it also renew the expire time. If I monitor for redis-cli monitor, it also doing setex when I get the data.

**Comment by sisve** [comment]
Yes, that is how the lifetime works. The expiration time is reset to keep it alive, and 120 minutes (default) of no activities will make it eligible to be destroyed.

What's the actual bug report here? And why are you using an unsupported Laravel version?

**Comment by chandrapw** [comment]
Oke, my bad. Actually i don't understand yet. I thought, the lifetime is just the time for the key to expire.
