### ISSUE TITLE
Should each() have a dedicated implementation?

### ISSUE THREAD

**Issue by QuakePhil** [laravel/framework#22061]
- Laravel Version: 5.4
- PHP Version: 7.1
- Database Driver & Version: mysqli 5.0.12

### Description:
I was using each() in an effort to iterate a result set and do some calculations based on the values in every row.  To my dismay, I found out that each() calls chunk() to do its bidding, rather than having its own implementation.  Unfortunately, chunk() is slow when the OFFSET part of the query becomes sufficiently large.

According to https://github.com/laravel/framework/issues/14007 and https://github.com/illuminate/database/blob/master/Concerns/BuildsQueries.php#L58 it appears this behaviour is by design.

My current workaround is something like: $x = app(db)->getPdo()->query(...); while($x->fetch()) {...}

Since it already has its own dedicated function name "each", I was hoping it would also get its own dedicated non-chunking implementation similar to the above workaround.  Please let me know if this is completely out of the scope of BuildsQueries trait, or perhaps if I've missed something simple/obvious here...

### Steps To Reproduce:
Run `each()` with an active DB listener.  Notice the default "limit 1000"

**Comment by QuakePhil** [comment]
```
    /**
     * Execute a callback over each item.
     *
     * @param  callable  $callback
     * @return bool
     */
    public function each(callable $callback)
    {
        $results = app('db')->getPdo()->query($this->toSql());
        if (!$results) {
            return false;
        }

        while ($row = $results->fetch(\PDO::FETCH_ASSOC)) {
            if ($callback($row) === false) {
                return false;
            }
        }
        return true;
    }
```
This works (maybe not every db cli will have getPdo, and maybe you want to do `$callback(collect($row))`) but is not pretty

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. This isn't a bug so you can open a proposal in the laravel/internals repo
