### ISSUE TITLE
PostDumpAutoload has problem to discover package on remove package

### ISSUE THREAD

**Issue by IgorDePaula** [laravel/framework#22070]
- Laravel Version: 5.5.18
- PHP Version: 7.0.1
- Database Driver & Version: mysql 5.7

### Description:
 Post composer update has a problem on remove a package: it no find the ServiceProvider

### Steps To Reproduce:

Instal any package with package discover
Remove this package.

![selecao_092](https://user-images.githubusercontent.com/2833993/32790529-d570d550-c945-11e7-9e7f-053b32e04357.png)

**Comment by Dylan-DPC** [comment]
I have tried the same thing in the past and things have worked flawlessly.

**Comment by themsaid** [comment]
Can't replicate either.

**Comment by IgorDePaula** [comment]
I was has a directive on AppServiceProvider to register the Dusk ServiceProvider, it is broken the removal. Sorry for false alarm.
