### ISSUE TITLE
Validate date_format empty string

### ISSUE THREAD

**Issue by serazoli** [laravel/framework#22078]
- Laravel Version: 5.5.20
- PHP Version: 7.1.11
- Database Driver & Version:

### Description:
Validation rule date_format:Y-m-d H:i:s return true also on empty string. The empty string is valid date?

### Steps To Reproduce:
```php
Psy Shell v0.8.14 (PHP 7.1.11-1+ubuntu16.04.1+deb.sury.org+1 — cli) by Justin Hileman
>>> $data['date'] = '';
=> ""
>>> $rule = ['date' => 'date_format:Y-m-d H:i:s']
=> [
     "date" => "date_format:Y-m-d H:i:s",
   ]
>>> $validator = Validator::make($data, $rule);
=> Illuminate\Validation\Validator {#784
     +customMessages: [],
     +fallbackMessages: [],
     +customAttributes: [],
     +customValues: [],
     +extensions: [],
     +replacers: [],
   }
>>> $validator->passes();
=> true
>>>
>>>
>>> $data['date'] = '2017-11-16 12:13:13';
=> "2017-11-16 12:13:13"
>>> $rule = ['date' => 'date_format:Y-m-d H:i:s']
=> [
     "date" => "date_format:Y-m-d H:i:s",
   ]
>>> $validator = Validator::make($data, $rule);
=> Illuminate\Validation\Validator {#791
     +customMessages: [],
     +fallbackMessages: [],
     +customAttributes: [],
     +customValues: [],
     +extensions: [],
     +replacers: [],
   }
>>> $validator->passes();
=> true
>>>
>>>
>>> $data['date'] = '2017-11-16 33:13:13';
=> "2017-11-16 33:13:13"
>>> $rule = ['date' => 'date_format:Y-m-d H:i:s']
=> [
     "date" => "date_format:Y-m-d H:i:s",
   ]
>>> $validator = Validator::make($data, $rule);
=> Illuminate\Validation\Validator {#790
     +customMessages: [],
     +fallbackMessages: [],
     +customAttributes: [],
     +customValues: [],
     +extensions: [],
     +replacers: [],
   }
>>> $validator->passes();
=> false
>>> 
```

**Comment by paulofreitas** [comment]
Actually this is correct for the way the framework works. Validation rules are explicit, meaning that you're required to use the `required` rule to avoid this behavior or extend them to be implicit. 😉 

This was documented at the [*Implicit Extensions*](https://laravel.com/docs/5.5/validation#using-extensions) section of [validation](https://laravel.com/docs/5.5/validation) documentation:

> By default, when an attribute being validated is not present or contains an empty value as defined by the required rule, normal validation rules, including custom extensions, are not run.

It's passing just because the `date_format` rule is not running here. You may use the `Validator::extendImplicit()` method to force any validation rule (even those included with Laravel) to be implicit required by default:

    Validator::extendImplicit('date_format', function ($attribute, $value, $parameters, $validator) {
        return $validator->validateDateFormat($attribute, $value, $parameters);
    });

**Comment by serazoli** [comment]
Thanks for quick response!
I think that I will write a custom validation rule eg. `not_null`
```php
Validator::extendImplicit('not_null',function ($attribute, $value, $parameters, $validator) {
    return  $value !== ''
});
```
and add to all field where not allowed empty string.
Thank, I closing this issue

**Comment by paulofreitas** [comment]
You're welcome! 😃 

Unless I haven't understood your intention you could be using the included `required` rule to achieve the same thing. 👍
