### ISSUE TITLE
Update model in Laravel 5.5 returns “unknown column in field list” error, but not create

### ISSUE THREAD

**Issue by mangrovestudios** [laravel/framework#22083]
- Laravel Version: 5.5.21
- PHP Version: 7.1

Using the new request validation, I ran into the error while doing an `update `to a model. Passing the same validated data on `create `worked. It seems like create can handle validated data not in the model's fields, whereas update cannot.

e.g. passing
```
array:4 [▼
  "first_name" => "Pedro"
  "last_name" => "Taco"
  "email" => "taco@example.org"
  "operators" => array:1 [▼
    0 => "1"
  ]
]
```
to `User::create()` inserts the record. Passing the same to `User::update()` returns an error.
User has `$fillable = 'first_name', 'last_name', 'email'`

**Comment by themsaid** [comment]
Yes you shouldn't pass non-existing fields or you'll get a sql error for non-existing columns

**Comment by mangrovestudios** [comment]
In that case, there's an issue in that I'm perfectly able to pass non-existing fields to `create `and a record is successfully inserted. The non-existing fields are ignored and no error is returned.
