### ISSUE TITLE
Performance Arr::flatten()

### ISSUE THREAD

**Issue by leonrenkema** [laravel/framework#22086]
- Laravel Version: 5.5.11
- PHP Version: 7.1.7

### Description:
We are experiencing problems with large arrays that are used in eloquent `whereIn()`. I have profiled it with xdebug and found that the most time is spend in `Arr::flatten()`.  

### Steps To Reproduce:
This small test shows that the array flatten method is getting really slow when large arrays are used. On my system this takes 10 seconds.

```php
$d = range(0,50000);
Illuminate\Support\Arr::flatten($d);
```

When I use an alternative implementation I found on Stackoverflow then the performance is okay, it is not the same and support for collections is not implemented but it show that PHP can deal with those large arrays.

```php
function array_flatten($array) {
            $return = array();
            foreach ($array as $key => $value) {
                if (is_array($value)){ $return = array_merge($return, array_flatten($value));}
                else {$return[$key] = $value;}
            }
            return $return;
        }
``` 

Maybe someone can confirm this on another system, or an alternative way we can solve this?

**Comment by sisve** [comment]
I can reproduce the performance issues on my end too.

    > time php test.php
    php test.php  7.54s user 6.59s system 98% cpu 14.281 total

**Comment by Kyslik** [comment]
Mind linking the other solution?

**Comment by Dylan-DPC** [comment]
flatten works recursively. So it is going to take a performance hit for sure. Also if your source has more depth, it will take longer time.

**Comment by leonrenkema** [comment]
The other solution I found, but that is not an instant replacement for `Arr::flatten`, is from https://stackoverflow.com/questions/526556/how-to-flatten-a-multi-dimensional-array-to-simple-one-in-php

I used that one to just illustrate that a recursive array flatten can performance good with my example data. 

Searching in the history I think it is introduced here. https://github.com/laravel/framework/pull/14338/files
The `$result[] = $item` is replaced by a `array_merge` on every item and that is quite expensive. 

Maybe @JosephSilber has a thought?

**Comment by crhg** [comment]
I found that `array_reduce` has performance problem. I have reported it to bugs.php.net. (https://bugs.php.net/bug.php?id=75533)

I think that it is necessary to rewrite so as not to use `array_reduce` until it is corrected.

**Comment by gitBC** [comment]
@taylorotwell Heads up:  PHP 7.3 merged the fix in https://bugs.php.net/bug.php?id=75533

**Comment by mfn** [comment]
Makes only sense to change anything in Laravel once it *requires* 7.3
