### ISSUE TITLE
Relationship name conflicting with another hidden method

### ISSUE THREAD

**Issue by renoirfaria** [laravel/framework#22081]
- Laravel Version: 5.5
- PHP Version: 7.1
- Database Driver & Version: 5.7

### Description:

Hello Guys, when i try to use the relationship `$exam->questions` the same is returning `null` but when i rename the same relationship to `$exam->questionss` or any other name i am receiveing the correct result (collection of `App\Question`). How can i solve this?

(sorry if here isn't the correct place to make this type of question).

**Comment by themsaid** [comment]
You'll have to ensure method names used for relationships aren't used anywhere else in the Model.

**Comment by renoirfaria** [comment]
@themsaid could you illuminate me where is the another `questions` method? Laravel shouldn't avoid commom names like `questions`?
