### ISSUE TITLE
Impossible to write usual html in mailable templates

### ISSUE THREAD

**Issue by projct1** [laravel/framework#22080]
- Laravel Version: 5.5.20

### Description:
I published all views throuth `php artisan vendor:publish --tag=laravel-mail`
Here is my email class:
```php
class ReviseSumChanged extends Mailable
{
    public $revises;

    public $subject = 'Отчёт по финансам';

    public function __construct(Collection $revises)
    {
        $this->revises = $revises;
    }

    public function build()
    {
        return $this->to('email@email.ru')->view('admin.emails.revise.sum-changed');
    }
}
```
Here is my `admin.emails.revise.sum-changed` template:
```php
@component('vendor.mail.html.message')

@foreach ($revises as $bar => $items)
    <p>
        <a href="{{ route('revise.index', ['revise_id' => $items->pluck('id')->toArray()]) }}" title="Открыть сверки">{{ $bar }}</a>
        {{ $items->implode('total', ', ') }}
    </p>
@endforeach

<hr>

<strong>Итого:</strong> {{ $totalComission }} руб.

<hr>

@foreach ($invoices as $bar => $items)
    <p>
        {{ $bar }}:
        @foreach ($items as $invoice)
            <a href="{{ route('osa.index', ['bar_id' => $invoice->report->bar->old_id, 'month' => $invoice->report->month, 'year' => $invoice->report->year]) }}" title="Открыть в админке">
                {{ $invoice->report->sum }}
            </a>
        @endforeach
    </p>
@endforeach

@endcomponent
```
Also i replaced all component path in `vendor.mail.html.message` from `mail::component` to `vendor.mail.html.component`.

But result email is wrong and without styles: http://joxi.ru/LmG3P9GIR9yMgm

**Comment by projct1** [comment]
How i can just write usual html templates with saving markdown beautiful styling http://joxi.ru/LmG3P9GIR9yygm ?

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
