### ISSUE TITLE
Isn't MEDIUMTEXT better when caching big data to database?

### ISSUE THREAD

**Issue by algorhythm** [laravel/framework#22085]
https://github.com/laravel/framework/blob/a7cbe215cac1ae5c05923ee2da64cd6da734c571/src/Illuminate/Cache/Console/stubs/cache.stub#L18

When using `php artisan cache:table` a cache table with a `value` field `TEXT` is created when using `MySQL`. In some cases the database cache with `MySQL` can behave different to the file cache.

Some plugins caches big data and they wasn't longer working when switching the default `CACHE_DRIVER` from `file` to `database` inside the `.env` file.

I changed the migration to work with `MEDIUMTEXT` instead of `TEXT`. 

Isn't it a good idea? Maybe it's an issue with speed?
And if is OK to do like this, shouldn't this be changed in the default stub?

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by tillkruss** [comment]
I think that's a reasonable request, why don't you open a PR about it.

PostgreSQL, SQLite and SqlServer don't even have a `text` and `longtext`, only MySQL differentiates there and MySQL `text` is limited to 64 Kb.

**Comment by algorhythm** [comment]
Here's my PR: https://github.com/laravel/framework/pull/22091
