### ISSUE TITLE
I cannot modify the content of a Response without also modifying the original property of the response

### ISSUE THREAD

**Issue by jonnybarnes** [laravel/framework#22097]
- Laravel Version: 5.5.21
- PHP Version: 7.2.0RC6
- Database Driver & Version: PostgreSQL 10.1

### Description:
I want to modify the html of outputs to include errors found by `libtidy` from [tidy-html5](https://github.com/htacg/tidy-html5). I’m doing this in a middleware where I get the `$response` and get the HTML from `$response->getContent()`. Create a modified version of the html including any errors (and is also now indented nicely) and then run `$response->setContent()`.

This has the unintended side-effect of changing two properties on the `$response`. The `content` property, which was the unmodified HTML, and which I wanted to change. But also the `original` property which is normally a `View` object. This property also becomes the modified HTML.

A consequence of this is any of the test assertions which try to inspect the View object will fail.

I attempted to solve this in https://github.com/laravel/framework/pull/22088 but it was closed. Does anyone know any other way?

**Comment by Dylan-DPC** [comment]
Hi. The PR was closed because it was a breaking change. You changed the behaviour of the function in some way. You can send the PR to the next version by targetting it to master.

**Comment by jonnybarnes** [comment]
I’ll open a new PR targeting the master branch.
