### ISSUE TITLE
error_reporting has influence on behavior of collection->where()

### ISSUE THREAD

**Issue by leonrenkema** [laravel/framework#22106]
- Laravel Version: 5.5.11
- PHP Version: 7.1.11 & 7.1.3

### Description:

When I change error_reporting to `E_NONE` the behavior of `Collection->where` changes and then a unit test fails. 

### Steps To Reproduce:

I have forked the repository and used travis to check. This build fails because of a unit test that is failing https://travis-ci.org/leonrenkema/framework/builds/303214891.

The only file I have changed is tests/Support/SupportCollectionTest.php for the sake of testing and executed `error_reporting(0)`. Changing php.ini also works. 

### Cause

The test works because of a PHP notice that gets generated when a stdClass is compared with an integer. With error reporting on `Object of class stdClass could not be converted to int` will be generated and catched and returns false.

But when error_reporting is off there is no error generated and this function will return true.

Illuminate/Support/Collection.php:484
```php 
try {
    switch ($operator) {
        default:
        case '=':
        case '==':  return $retrieved == $value;
        case '!=':
        case '<>':  return $retrieved != $value;
        case '<':   return $retrieved < $value;
        case '>':   return $retrieved > $value;
        case '<=':  return $retrieved <= $value;
        case '>=':  return $retrieved >= $value;
        case '===': return $retrieved === $value;
        case '!==': return $retrieved !== $value;
    }
} catch (Exception $e) {
    return false;
}
```

**Comment by themsaid** [comment]
Thanks for this catch, here's a PR with a fix: https://github.com/laravel/framework/pull/22172
