### ISSUE TITLE
[L5.4] Middleware in __construct() of controller not working perfect 

### ISSUE THREAD

**Issue by gzai** [laravel/framework#22105]
- Laravel Version: 5.4.36
- PHP Version: 7.1.7
- Database Driver & Version: 10.1.25-MariaDB

### Description:
Middleware in __construct() of controller not working perfect 
( dunno this is a bug or something else )

### Steps To Reproduce:

Some code :
 
AController
```
class AController extends Controller
{

    public function __construct()
    {

        echo 'outside - AController';
        echo '<br/>';

        $this->middleware(function ($request, $next) {

            echo 'inside - AController';
            echo '<br/>';

            return $next($request);
        });

    }

    public function handle()
    {

        $B = new BController;
        if ( $B->check() ) {
            $controller = BController::class;
            $action = 'index';
        } else {
            $controller = BController::class;
            $action = 'nothing';
        }

        $container = app();
        $route = $container->make(Route::class);
        $controllerInstance = $container->make($controller);

        return (new ControllerDispatcher($container))->dispatch($route, $controllerInstance, $action);

    }

}
```

BController
```
class BController extends Controller
{

    public function __construct()
    {

        echo 'outside - BController';
        echo '<br/>';

        $this->middleware(function ($request, $next) {

            echo 'inside - BController';
            echo '<br/>';

            return $next($request);
        });

    }

    public function check()
    {
        return true;
    }

    public function index()
    {
        return 'index';
    }

    public function nothing()
    {
        return 'nothing';
    }

}
```

Real result in browser : 
outside - AController
inside - AController
outside - BController 

Expected of result : 
outside - AController
inside - AController
outside - BController 
inside - BController ( why this step not working )

**Comment by leonrenkema** [comment]
I think this is not the way middleware should be used, middleware is executed before the handle function is called. At the time you are executing `$B = new BController;` the middleware is executed and wont be executed again.

**Comment by devcircus** [comment]
Correct, this is not how middleware works. If you're needing this kind of functionality, middleware isn't the solution.

**Comment by gzai** [comment]
@leonrenkema so the middleware only execute the first, can we hack only last middleware to execute? if we can't hack it's okay.

@devcircus yeah, I need this kind of functionality, so what solution can we handle this functionality?

I used this middleware to set global variable from $request in middleware and set the middleware of same function in the same one of functionality. 
I can't used middleware in route, because my route very dynamic, and in function handle() have many logic to adjust the route.

```
Route::get('/{slug1}/{slug2}/{slug3}/{slug4}/{slug5}', 'AController@handle')
    	->name('A.handle.five')
    	->where('slug1', '[A-Za-z0-9-_]+')
    	->where('slug2', '[A-Za-z0-9-_]+')
    	->where('slug3', '[A-Za-z0-9-_]+')
    	->where('slug4', '[A-Za-z0-9-_]+')
    	->where('slug5', '[A-Za-z0-9-_]+');
```

Thanks for your reply and information

**Comment by devcircus** [comment]
The thing is, middleware is gathered when the route is determined and honestly you shouldn't be calling controllers from controllers. By the time it is known that you'll be using the second controller, the middleware is already set. You need to completely rethink how your code is structured. It would be hard to say without seeing more code. Maybe go to larachat slack and post your question with more code and someone should be able to point you in the right direction.
