### ISSUE TITLE
Potential error with mocking email after multiple emails are being sent

### ISSUE THREAD

**Issue by deividaspetraitis** [laravel/framework#22111]
- Laravel Version: 5.5.x
- PHP Version: 7.1
- Database Driver & Version: MySQL

### Description:

I was writing some tests for my application and noticed some not expected behavior. When running tests inside application there is few email being to sent. I was about to catch them and test as well however after first email is sent for some reason `Mail`  facade returns `Mailer` class instead of `MailFake`.

### Steps To Reproduce:

For example test case:

```
public function test(ApiTester $I) : void
{
    // Prevent actual email being sent
    Mail::fake();

    // Do some stuff
    // Email 1 inside application is sent..
    // get_class(app('mailer')) == Illuminate\Support\Testing\Fakes\MailFake
    Mail::assertSent(Action1Mail::class, function (Action1Maill $mail) {
        return $mail->getVal() == 1;
    });
    // get_class(app('mailer')) == Illuminate\Support\Testing\Fakes\MailFake
    // Calling Mail::fake(); here makes no sense!

    // Do some stuff
    // Email 2 inside application is sent..

    // Boom, error:  [BadMethodCallException] Method assertSent does not exist.
    // Because: get_class(app('mailer')) == Illuminate\Mail\Mailer
    // And no more: get_class(app('mailer')) == Illuminate\Support\Testing\Fakes\MailFake
    Mail::assertSent(Action2Mail::class, function (Action2Mail $mail) {
        return $mail->getVal() == 2;
    });
}
```

**Comment by themsaid** [comment]
I can't replicate this, the Mail is faked without any alteration, could be something in your project re-constructing the mailer.

**Comment by deividaspetraitis** [comment]
Thank you @themsaid. I'll try to re-produce issue on clear laravel installation and will update issue accordingly.
