### ISSUE TITLE
[feature] Allow passing middleware parameters with array syntax

### ISSUE THREAD

**Issue by SAMDevelopment** [laravel/framework#22120]
- Laravel Version: 5.5.21
- PHP Version: 7.1.8
- Database Driver & Version: NA

### Description:
The router currently does not support passing middleware parameters with array syntax. It tries to use the array as an array key in the `Illuminate\Routing\MiddlewareNameReslover@resolve` method on line *26*.

### Steps To Reproduce:
Create a route like the following with array parameters middleware syntax:
```php
Route::get('/foo', [
    'middleware' => [
        'bar' => ['one', 'two'],
    ],
    function () {
        return 'Hello';
    },
]);
```

### Proposal:
Transform array syntax middleware parameters to the standard string syntax to enable more flexibility with the addition of array syntax parameters without breaking backwards compatibility.

**Comment by Dylan-DPC** [comment]
Hey. This repo is actually for bug tracking so you didn't have to open the issue here.

**Comment by SAMDevelopment** [comment]
Whoops, should I move it to the internals repo?

**Comment by Dylan-DPC** [comment]
Since Taylor has no plans of adding this, i don't see a point. If you want you can open a proposal there to see if anyone else is also interested in having this (though it may end up being a dead issue)
