### ISSUE TITLE
allow timestamps to create indexes automatically

### ISSUE THREAD

**Issue by ChangePlaces** [laravel/framework#22124]
- Laravel Version: 5.5
- PHP Version:
- Database Driver & Version:

### Description:
`$table->timestamps()` is a handy way in migrations to create `created_at` and `updated_at` fields. fields that nearly always require an index. It'd be nice if it were possible to do something like `$table->timestampsWithIndexes(['created_at', 'updated_at'])` or `$table->timestampsWithIndexes(['created_at'])` to add indexes

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. This isn't a bug so you can open a proposal in the laravel/internals repo

**Comment by ChangePlaces** [comment]
sorry - done so https://github.com/laravel/internals/issues/891
