### ISSUE TITLE
Queue customized priority

### ISSUE THREAD

**Issue by ginnerpeace** [laravel/framework#22139]
- Laravel Version: 5.2 ~ 5.5
- PHP Version: 7.0

**Comment by Dylan-DPC** [comment]
Hey

This repo is for bug tracking. So if you want to report a bug kindly provide a complete use-case with steps to reproduce. If you need help seek the forums or the slack channel.

**Comment by ginnerpeace** [comment]
@Dylan-DPC 
OK,
Thanks for reminding me.
