### ISSUE TITLE
DatabaseEloquentModelTests failing

### ISSUE THREAD

**Issue by hastinbe** [laravel/framework#22133]
- Laravel Version: 5.5.21
- PHP Version: 7.0.22

### Description:

The following tests fail on a fresh clone of 5.5:

```
1) Illuminate\Tests\Database\DatabaseEloquentModelTest::testCreateMethodSavesNewModel
Error: Call to a member function connection() on null

2) Illuminate\Tests\Database\DatabaseEloquentModelTest::testMakeMethodDoesNotSaveNewModel
Error: Call to a member function connection() on null

3) Illuminate\Tests\Database\DatabaseEloquentModelTest::testForceCreateMethodSavesNewModelWithGuardedAttributes
Error: Call to a member function connection() on null

4) Illuminate\Tests\Database\DatabaseEloquentModelTest::testWithoutMethodRemovesEagerLoadedRelationshipCorrectly
Error: Call to a member function connection() on null

5) Illuminate\Tests\Database\DatabaseEloquentModelTest::testEagerLoadingWithColumns
Error: Call to a member function connection() on null
```

### Steps To Reproduce:

Clone the repo. Install dependencies. `phpunit --filter DatabaseEloquentModelTest`

### Other

Want to make sure I'm not the only one. I fixed the errors with hastinbe/framework@a29c3fd898bcccfc6708c9be060d36655e6ea73b

**Comment by Dylan-DPC** [comment]
You can verify this by looking at CI results on any 5.5 PR

**Comment by hastinbe** [comment]
@themsaid you closed my issue, but didn't bother to reproduce it. There's static state from a previous test that is affecting other tests. I've updated my commit to fix them.

**Comment by themsaid** [comment]
Thanks for the PR, I've closed since as Dylan said Travis is not failing and thus the overall tests are running successfully, in that case opening a PR would be a great chance for us to identify the issue and discuss a change that might prevent it.
