### ISSUE TITLE
loadMissing returns an error when passing a closure

### ISSUE THREAD

**Issue by ma-mehralian** [laravel/framework#22134]
- Laravel Version: 5.5.21
- PHP Version: 7.1.9
- Database Driver & Version: mySQL

### Description:
I use `loadMissing` and it works properly, however when I call it with a Closure:

    public function getProductsAttribute(){
        $this->loadMissing(['shop.product'=> function ($query) {
         ....
        }]);
        ...
    }

returns error `"array_key_exists(): The first argument should be either a string or an integer"` on:

    public function relationLoaded($key){
        return array_key_exists($key, $this->relations);
    }

**Comment by Dylan-DPC** [comment]
Yes that is because `loadMissing` doesn't accept a closure for some strange reason :thinking:

**Comment by sisve** [comment]
It looks like this has never been supported. Is there anything in the documentation that states that loadMissing should be supporting closures?

**Comment by Dylan-DPC** [comment]
@sisve `with` and `load` accept closures so having a function `loadMissing` that doesn't accept one sounds odd

**Comment by ma-mehralian** [comment]
@themsaid Sometimes ignoring the problem is easier than solving it!

**Comment by gmatkowski** [comment]
That would be really nice to have this feature working ...
