### ISSUE TITLE
Class view does not exist

### ISSUE THREAD

**Issue by johnko89** [laravel/framework#22132]
- Laravel Version: 5.5
- PHP Version: 7.0
- Database Driver & Version:

### Description:
Today, i doing some simple staffs on my views and after that i got this error

### Steps To Reproduce:

Hi guys, i got this error:
`Fatal error: Uncaught ReflectionException: Class view does not exist in /nfsmnt/hosting2_1/0/3/03c468f0-7f40-4318-8852-b8da628d70dd/onlima.sk/web/klientska-zona/vendor/laravel/framework/src/Illuminate/Container/Container.php:752 Stack trace: #0 /nfsmnt/hosting2_1/0/3/03c468f0-7f40-4318-8852-b8da628d70dd/onlima.sk/web/klientska-zona/vendor/laravel/framework/src/Illuminate/Container/Container.php(752): ReflectionClass->__construct('view') #1 /nfsmnt/hosting2_1/0/3/03c468f0-7f40-4318-8852-b8da628d70dd/onlima.sk/web/klientska-zona/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('view') #2 /nfsmnt/hosting2_1/0/3/03c468f0-7f40-4318-8852-b8da628d70dd/onlima.sk/web/klientska-zona/vendor/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\Container\Container->resolve('view', Array) #3 /nfsmnt/hosting2_1/0/3/03c468f0-7f40-4318-8852-b8da628d70dd/onlima.sk/web/klientska-zona/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(732): Illumi in /nfsmnt/hosting2_1/0/3/03c468f0-7f40-4318-8852-b8da628d70dd/onlima.sk/web/klientska-zona/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 752`

I read a lot of about it on forums but i didnt find solution for me. 

Before it i made just simple changes on my views. I checked every views and i didnt find any error. I tried to change chmod for vendor, storage - but it didnt work.

Thank you for your every help.

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by GrahamCampbell** [comment]
Without seeing all the strack trace, it's hard to guess what's happening, but it looks like you are having an exception early in the bootstrap process, which results in the exception handler trying to get the view factory from the container, but it's not been bound yet. If this is the case, replace your handle method in the exception handler with something that just dumps the raw exception, that'll let you see the real issue.

Anyway, this does sound like one for the forums. :)
