### ISSUE TITLE
[Feature Request] Blade @foreach should accept not only array and Countable but also Traversable

### ISSUE THREAD

**Issue by mpyw** [laravel/framework#22145]
https://github.com/illuminate/view/blob/498c86e971b7f9057b2c9ce416c5cc74fe3f12bc/Concerns/ManagesLoops.php#L25

It seems that `@foreach` only accepts `array` and `Countable`. However, iteration could be done even if we don't know its length. `Traversable` such as `Iterator`, `IteratorAggregate` and `Generator` are popular interfaces. I think it should be supported.

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. This isn't a bug so you can open a proposal in the laravel/internals repo

**Comment by mpyw** [comment]
Okay
