### ISSUE TITLE
Inaccurate validation (string max length)

### ISSUE THREAD

**Issue by Aliabdulaziz** [laravel/framework#22141]
- Laravel Version: 5.5
- PHP Version: 7.1

### Description:
When I validate multi-byte strings using "Max" rule, I get inaccurate result. My guess is that the string length is measured using strlen(), while mb_strlen() is what should be used to measure the length of multi-byte characters. 

### Steps To Reproduce:

$data = 'نص عربي'; // Arabic text (7 charectors)

return Validator::make($data, [
       'name' => 'string|max:7',
]);

**Comment by Dylan-DPC** [comment]
Fixing this would mean introducing a breaking change. It may be introduced in 5.6

**Comment by Aliabdulaziz** [comment]
OK, I see.

**Comment by sisve** [comment]
We're already using mb_strlen when validating strings against 'max:7', so that isn't the issue. What do you mean with "inaccurate result"?

https://github.com/laravel/framework/blob/41ea7cc3bb898ff86505d3798d8acbb8992a0aad/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L1385-L1402

**Comment by Aliabdulaziz** [comment]
My apologies, I've just tested it again and everything just looks fine.
