### ISSUE TITLE
Multi app with modules for each

### ISSUE THREAD

**Issue by shrikanth003** [laravel/framework#22146]
- Laravel Version: 5.5
- PHP Version: 7.1
- Database Driver & Version:

### Description:
I'm looking for a solution where i can produce multiple applications or modules under the same laravel installation. For Example, my project consists of a search directory where users can find nearby professionals and businesses, a community system like flarum, a erp tool and a social network. 
In yii2 framework we have a common folder(shared resources), backend folder (for administration), frontend folder(customer facing). Each folder represents a application. We can create modules in each app for our features. Or we could clone frontend to make a new app. For example, clone frontend folder and rename it to community and adjust config and aliases. This results in a multi app. Each app has a modules folder inside to add features as modules.
And a rbac for the project to handle roles and permissions for all the folders(appplications)

I have moved to laravel as i feel more complex things could be achieved with it and also i want to use a javascript like vuejs for the frontend. All i'm confused right now is with the structure of laravel. I have gone through few articles like pingpong modules, multi tenancy, multi site and other. But i didn't find an answer.

Does anyone know how i could achieve a architecture as mentioned above in yii2 framework which makes the job easy for me. I know laravel is a different framework and im not comparing it to yii2. But i feel if that can be achieved in yii2, it should also be achieved in laravel. And the best way to learn things is by trying instead of giving up on laravel and moving back to yii2.

So any tutorials, links or suggestions will really help me kickstart my project.

**Comment by Kyslik** [comment]
This is no bug, go look in forums.

You may take a look at:

https://github.com/nWidart/laravel-modules
https://github.com/apiato/apiato

Do not forget to close this issue, since it is no issue.

**Comment by shrikanth003** [comment]
Thanks. Ill give it a try
