### ISSUE TITLE
How to run groupBy after union

### ISSUE THREAD

**Issue by jacobcyl** [laravel/framework#22142]
- Laravel Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
I have a table name videos like this

 |    id| tag1|tag2| 
 | --- | ------ | ------|
 | 1|  cartoon |comedy| 
 | 1|  Kongfu  |historical| 

I want to get the top 10 tags 
sql query below working
```sql
SELECT tag, count(*) as tagcount
FROM (
  SELECT tag1 AS tagFROM videos
  UNION ALL
  SELECT tag2 AS tagFROM videos
) AS baseview
GROUP BY tag
ORDER BY tagcount DESC
LIMIT 10
```

But how to run this query in query builder?
In another way, the question is how to run groupby after union tables view "baseview"
Anyone know please help me.
Thanks

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by jacobcyl** [comment]
Sorry. Thank u for your suggestion

**Comment by danrichards** [comment]
It sure would have been great if the solution was posted...
