### ISSUE TITLE
Update Column with Pivot Toggle

### ISSUE THREAD

**Issue by 760524mkfa00** [laravel/framework#22148]
- Laravel Version: 5.5.#
- PHP Version: 7.0
- Database Driver & Version: MySql 5.7

### Description:
With the Attach method we can add additional data to the pivot table. However with Toggle this is not possible and I need to create an if statement.

I guess this is more a feature request.

### Steps To Reproduce:
This will not work:
$trip->user()->toggle($user->id, ['accepted_hours' => $trip->hours]);

This does:
 if($trip->user->contains($user->id))
        {
            $trip->user()->detach($user);
        } else {
            $trip->user()->attach($user, ['accepted_hours' => $trip->hours]);
        }

Thanks

**Comment by Dylan-DPC** [comment]
I find this to be intended behaviour. For example, say you have a row in the pivot but value of accepted_hours is 100. Now when you toggle it with accepted_hours 200 , what do you expect? the row to be detached or attached with new value?

**Comment by 760524mkfa00** [comment]
When you toggle, if it is attaching, it will include the additional data. When detaching, toggle would ignore the additional columns.

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.

**Comment by chris-hud** [comment]
ref: https://github.com/laravel/ideas/issues/943
