### ISSUE TITLE
$loop variable in @each directive (blade)

### ISSUE THREAD

**Issue by rehmatworks** [laravel/framework#22143]
- Laravel Version: 5.5.21
- PHP Version: 7.0.24

### Description:
The `$loop` variable is of great help in general loops but I can't use in `@each` directive of Blade. Any input will be highly appreciated.

### Steps To Reproduce:
For example I can't do something like this:
In `users.blade.php`:
```
@each('partials.profile', $users, 'name')
```
And `partials/profile.blade.php`:
```
<div class="profile-loop">
	{{ $loop->iteration }} - Hi {{ $name }}
</div>
```

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by rehmatworks** [comment]
Doesn't this seem to be a bug?

**Comment by Dylan-DPC** [comment]
You can close this issue

**Comment by rosDNsf** [comment]
@Dylan-DPC seriously, you have to do this in every PR or issue of the repository?, is this kind of work all that you can contribute with?, how depressing...

Surely everybody can spot this kind of situations in seconds without needing you to do this.

**Comment by rosDNsf** [comment]
@Dylan-DPC seriously, you have to do this in every PR or issue of the repository?, is this kind of work all that you can contribute with?

Surely anyone with real authority can spot this kind of situations in seconds without needing you to do this.

So please, If you can help people with the issue at hand, HELP, if you can't, please be respectful and shut up. If this can of situations get annoying enough, all "your hard" work can be replaced with an issue template.

**Comment by brunogaspar** [comment]
@rosDNsf He's the Laravel Police, be careful. :trollface:

**Comment by devcircus** [comment]
⭐️⭐️⭐️ for those who keep these repeated questions cleaned up. A simple issue search will show this has been asked many times. It was designed that way. If you'd like to see this as a feature, test the waters in the internals repo, then maybe submit PR.  Thanks for your hard work  @Dylan-DPC. And thanks to the OP for their curiosity.

**Comment by rosDNsf** [comment]
@Dylan-DPC 

After all seems like like your work is valuable for the community. I was speaking on the behalf of the people pushed away of the repo without a real answer, but again, seems like this is what the community wants.

I apologize with you, keep it ip 👍

**Comment by Dylan-DPC** [comment]
@rosDNsf the thing is we have dedicated areas for seeking help. So clearing those out help us to get to the important bug reports faster. If you have a better way of handling this, we are all ears.

**Comment by rosDNsf** [comment]
@Dylan-DPC i know that some people is going to ignore it, but an issue template that references those "help areas" can be a helpful first barrier.

I bet that if you recover some of the time that you spend in this kind of activities, you will be able to make more valuable contributions and enjoy your personal time.

As you can see, your work is valuable for the community and you should be proud, but don't be a slave of the people that can't follow simple rules like not posting here help requests :)

**Comment by Dylan-DPC** [comment]
Yeah. It is something we can look at. Honestly though, it doesn't take much long.

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.

Thanks everyone for trying to make the repository as much helpful as possible :), we just figured out that it's better to keep questions in the forums and suggestions in the internals repo for the sake of better organization.
