### ISSUE TITLE
[5.5] Wrong method in request

### ISSUE THREAD

**Issue by ionesculiviucristian** [laravel/framework#22147]
- Laravel Version: 5.5.21
- PHP Version: 7.0.22
- Database Driver & Version: Mysql 5.7.20
- OS: Ubuntu 16.04.1
### Steps To Reproduce:
1. Send a POST request to the server through AJAX (using jQuery)
2. Don't add an exception for the URL in `VerifyCsrfToken`
3. When `VerifyCsrfToken` handles the request in the handle function, no `TokenMismatchException` is thrown because the $request param has the method set to GET so it passes through `$this->isReading($request)`.

**Comment by sisve** [comment]
Can you provide code that reproduces this? We would need the `Route::post(...)` that you can call, and the javascript that can call it and trick Laravel into believing that the post is actually a get in the csrf validation.

**Comment by ionesculiviucristian** [comment]
I'm not sending the token through the ajax request. I'm just excepecting the `TokenMismatchException` to happen.

**Comment by ionesculiviucristian** [comment]
this is my call: 
```javascript
$.post($(this).data('ajax-url'), data).done(function(data, textStatus, jqXHR) {
    if (data.success) {
        $.notify({message: data.success}, {
            type      : 'success',
            placement : {from: 'top', align: 'center'}
        });
    } else if (data.error) {
        $.notify({message: data.error}, {
            type      : 'danger',
            placement : {from: 'top', align: 'center'}
        });
    } else {
        $.notify({message: 'Undefined response!'}, {
            type      : 'warning',
            placement : {from: 'top', align: 'center'}
        });
    }
}).fail(function(jqXHR, textStatus, errorThrown) {
    $.notify({message: textStatus}, {
        type      : 'danger',
        placement : {from: 'top', align: 'center'}
    });
});
```

`ajax-url` points to `requests/modify-products` that should be handled here:
`Route::post('requests/modify-products', 'AjaxController@modifyProducts');`

**Comment by sisve** [comment]
It sounds like you've changed your exception handler to transform TokenMismatchException into 404 error codes instead of the usual 419. Anyhow, so far you've not given us enough to confirm that this is a bug in the framework. We cannot proceed with some way to reproduce the problem locally.

**Comment by ionesculiviucristian** [comment]
You are right. There is no method converting happening. I was using "Open in new tab" option in the preview tab.
The problem is that I get the `TokenMismatchException` converted to `HttpException` with an empty message. Am I supposed to check the code `419` in this case ?

OFTOPPIC: How can I view the html returned by a `dd()` function in the Preview tab of Chrome? It just returns plain text but the headers are set to text/html.

**Comment by sisve** [comment]
Yes, your exception handler should convert a TokenMismatchException into a HTTP 419 response.

https://github.com/laravel/framework/blob/62cf7cb80581f0a0b11a112bb05a81a5500c263a/src/Illuminate/Foundation/Exceptions/Handler.php#L202-L203

I cannot answer you on how Chrome's preview works.

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
