### ISSUE TITLE
MIME for .txt file type problem

### ISSUE THREAD

**Issue by woenel** [laravel/framework#22158]
- Laravel Version: 5.5.20
- PHP Version:  7.1.11
- Database Driver & Version: 10.1.28-MariaDB

### Description:
Validating file using MIME type for txt file also allows .js, .json, .md, .yml and even files with no extension to be uploaded.

Demo video here: https://youtu.be/QwBnuygXYwU

### Steps To Reproduce:
`return [
            'files' => 'required',
            'files.*' => 'mimes:jpg,jpeg,png,docx,pdf,txt',
]`

By adding that to validation rule, it is expected that we can only upload file with the mime type of JPG, PNG, DOCX, PDF and TXT but by adding TXT type, you can also upload other file types like .js or .yml.

**Comment by davidcb** [comment]
It seems that symfony/http-foundation/File/MimeType/FileInfoMimeTypeGuesser.php on its method guess($path) returns a MIME type of "text/plain" for a .js file, that's because it passes the validation with the txt in mimes rule.

I don't know how to fix it but maybe it can help.

**Comment by themsaid** [comment]
Try using the mime_type validation rule instead.

**Comment by woenel** [comment]
@themsaid Yep, I tried that too, (mimetypes:text/plain) no difference. `text/plain` is the equivalent of `txt` for mimetypes.

**Comment by devcircus** [comment]
https://github.com/symfony/symfony/issues/8354 offers further explanation

**Comment by driesvints** [comment]
Closing this as I'm afraid we can't solve this unless it's solved in the Symfony library.
