### ISSUE TITLE
Validation rule: dimensions

### ISSUE THREAD

**Issue by kikky7** [laravel/framework#22155]
- Laravel Version: 5.5.21
- PHP Version: 7.1.11
- Database Driver & Version: MySQL 5.7.18

I am using a default validation rule "dimensions":
`'image' => 'required|mimes:jpeg,png|dimensions:min_width=640,min_height=640,max_width:1920,max_height:1920',`

I upload an image with the dimensions 2560x1600 and the validation should fail because both width and height are higher than max_width and max_height, however the validation passes with 0 errors.

**Comment by savander** [comment]
You have syntax error in your code, and used colon instead of equality sign.

Change `max_width:1920` to `max_width=1920` and `max_height:1920` to `max_height=1920`

**Comment by hughgrigg** [comment]
https://laravel.com/docs/5.5/validation#rule-dimensions

**Comment by kikky7** [comment]
Ooo, I used to use : in validation rules, I didn't even notice that I have a syntax error.
