### ISSUE TITLE
Eloquent where('created_at', 'between', [$start, $end]) does not work

### ISSUE THREAD

**Issue by aleksandrlat** [laravel/framework#22151]
- Laravel Version: 5.5.17
- PHP Version: 7.1
- Database Driver & Version: mysql 5.6

### Description:
I can see 'between' operator is [allowed](https://github.com/laravel/framework/blob/6da32f35e3bad6f1f9bedd4dcf8038f5cd856ee2/src/Illuminate/Database/Query/Builder.php#L181) in where method of query builder. But it does not work.

### Steps To Reproduce:
Restrict result of db query using ```MyModel::where('created_at', 'between', ['2017-01-01', '2017-01-30'])```. You will get invalid sql error.

**Comment by paulofreitas** [comment]
You're required to use the [`whereBetween()`](https://laravel.com/api/5.5/Illuminate/Database/Query/Builder.html#method_whereBetween) method to actually make a `WHERE ... BETWEEN` query. While `between` is a valid operator it's not supposed to be used within the `where()` method. It seems to me that there's room for improvement there. 👍

**Comment by aleksandrlat** [comment]
Why it is not supposed to be used within base `where` method? Maybe there is just bug?
If it is not supposed why it is allowed? It looks confusing and looks like a bug.

**Comment by Dylan-DPC** [comment]
Strangely, the operator was added in first commit even before `whereBetween` existed.

**Comment by aleksandrlat** [comment]
@themsaid so it is not a bug? Should this operator be disallowed then?

**Comment by themsaid** [comment]
I've opened a PR to remove it from valid operator: https://github.com/laravel/framework/pull/22182

**Comment by Md-Masud-Rana-Akash** [comment]
hey, can anyone help if i want to get data between input date and created_at date? say, MyModel::where('created_at', 'between', ['2017-01-01', 'created_at']), something like this, is it possible? if not then how?

**Comment by GESUMAYOR** [comment]
@Md-Masud-Rana-Akash, the issue with your express is in the order in it was returned. The created_at field should come first before the other value of date you are looking for data between. This snippet just worked now and it was tested on Laravel 5.6 and php 7.2

\MyModel::where('status',1)->whereBetween('created_at', ['2018-10-24 00:00:00', \Carbon\Carbon::now()->format('Y-m-d')])
