### ISSUE TITLE
ReflectionException Class dose not exist in Illuminate/Container/Container.php on line 752

### ISSUE THREAD

**Issue by okbfedition** [laravel/framework#22157]
- Laravel Version: 5.5.21
- PHP Version: 7
- Database Driver & Version: MySQL 8

### Description:
I'm making my custom modular architecture with Laravel, so I have created an App Directory Called Backoffice for Controllers and Middleware that concerns only that part of the Application 
I have Other Modules like Account Modules Addresses Modules that Holds only Models.

**-app
      -Backoffice
           -Controllers
           -Middleware
      -Account
            BackofficeUser.php**

- my composer.json
   **"psr-4": {
            "App\\": "app/",
            "Api\\": "app/Api/",
            "Backoffice\\": "app/Backoffice/",
            "Account\\": "app/Account/",
            "Address\\": "app/Address/",
           .....
 }**
- my RouteServiceProvider.php

protected $backoffice_namespace = 'App\Backoffice\Controllers';

 protected function mapBackofficeRoutes()
    {
        Route::prefix('backoffice')
            ->namespace($this->backoffice_namespace)
            ->group(base_path('routes/backoffice.php'));
    }`

my routes/backoffice.php
`Route::post('/login', 'AuthController@index');
`

and I Get 
`Class App\Backoffice\Controllers\AuthController does not exist in file /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 752`

Thanks For Help

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
