### ISSUE TITLE
To upload json file validation does't work

### ISSUE THREAD

**Issue by JDamour** [laravel/framework#22154]
- Laravel Version: 5.4.36
- PHP Version:>=5.6.4
- Database Driver & Version:

### Description:
I want to validate json file with it extension only but doesn't work
these are codes i tried 
` $this->validate($request, [

                'dataset_type' => 'required|file|mimetypes:application/json'
            ]);`
other way i tried 

` $file = $request->file('dataset_type'); //i need this later to upload the file
            $rules= [
                'dataset_type' => 'mimetypes:application/json'
            ];
            $x = $request->all();
            $validator=Validator::make($x, $rules);
            if ($validator->passes()){
                dd("Passes");
            }else{
                dd("fails");
            }`

it doesn't work ⬆️ 

this one works but it validate with  txt file but I need json formatt only ⬇️ 
` $this->validate($request, [
               'dataset_type' => 'required|mimes:json,txt'
            ]);
`
How could i resolve this issue ?

Thanks

**Comment by Dylan-DPC** [comment]
Laravel 5.4 is no longer supported. Also this repo is for bug fixes. If you need help, you can consult the forums or the slack channel

**Comment by JDamour** [comment]
thank you @Dylan-DPC  could you  give slack url channel?

**Comment by Dylan-DPC** [comment]
https://larachat.co/

**Comment by JDamour** [comment]
Thank you
