### ISSUE TITLE
Grammatical error in ValidationException

### ISSUE THREAD

**Issue by hopeseekr** [laravel/framework#22166]
- Laravel Version: 5.5.21
- PHP Version: 7.1.11

### Description:

The grammar of the new 5.5 ValidationException message is **not grammatically correct.**

It says `The given data was invalid.`, however, unless the data somehow magically transformed between the time that it was submitted to the server and the time with which this message is returned to the user, it is in the wrong tense.

The proper wording should be: `The given data is invalid.`

### Steps To Reproduce:

Throw a `ValidationException`. Look at `$e->getMessage()`.

**Comment by Dylan-DPC** [comment]
Hey. This seems trivial enough. How about sending a PR?

**Comment by themsaid** [comment]
I'd say send the PR to the master branch since people might be using the current message to do different kinds of checks.
