### ISSUE TITLE
Session data missing after redirect

### ISSUE THREAD

**Issue by niekiem** [laravel/framework#22169]
- Laravel Version: 5.5.0
- PHP Version: 7.1.11
- Database Driver & Version: MySQL and ODBC

### Description:
Session data disappears after a redirect

### Steps To Reproduce:
dump(session()->all()); // All session variables present
return redirect()->to($route)->with($data);

In the $route controller:
dump($session()->all()); // Session completely blank

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.

**Comment by rosDNsf** [comment]
@Dylan-DPC if you are going to continue redirecting people, please consider using the template of @themsaid, it is great and provide useful links.

**Comment by niekiem** [comment]
Seeing that it worked in 5.1 to 5.4, but upgrading to 5.5 it’s broken, I would have seriously considdered it a bug.  Also, how many different ways are there to redirect to another URL?  What can we do wrong?  Searching on the internet provides about 7 similar forum posts with zero responses or success.  Should your opinion of it being a “support” related issue change, let me know.  I will post it on the forums but doubt whether that will solve the problem.

Regards.




On 22 Nov 2017, at 5:15 PM, Mohamed Said <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #22169<https://github.com/laravel/framework/issues/22169>.

**Comment by NelinD** [comment]
What session driver are you using?
