### ISSUE TITLE
SoftDelete trait throws PHP error with PHP7.2

### ISSUE THREAD

**Issue by EspadaV8** [laravel/framework#22162]
- Laravel Version: 5.1.46
- PHP Version: 7.2.0RC6
- Database Driver & Version: pgsql

### Description:

Using the SoftDelete trait on a model when using PHP 7.2 throws an internal error because of the usage of `count` in the `SoftDeletingScope` on line 75. The property `joins` isn't always an array and results in a call of `count(null)`.

Updating line 92 of `Illuminate/Database/Query/Builder.php` to

```php
    /**
     * The table joins for the query.
     *
     * @var array
     */
    public $joins = [];
```

is enough to stop the error from happening, although it looks like there are multiple other properties in the class that should be updated in a similar way to prevent this error from happening elsewhere.

### Steps To Reproduce:

* Install a version of PHP 7.2
* Create a model that implements `SoftDeletes`
* Attempt to delete an instance of the model
* Notice the error `count(): Parameter must be an array or an object that implements Countable`

**Comment by Dylan-DPC** [comment]
Hey

5.1 is no longer supported. I submitted a PR fixing this for 5.6

**Comment by EspadaV8** [comment]
I thought 5.1 had support for another year still (because of the LTS). 5.5 should also be updated too I think, again, because it's an LTS release.

**Comment by Dylan-DPC** [comment]
Yeah but it can be considered a breaking change for 5.5

**Comment by EspadaV8** [comment]
I don't see how it'd be a breaking change. All of the doc blocks there hint it as an array, it's just not been initialised correctly. If it is a breaking change then the call to `count` can be changed to do a check for `null` first (and revert the change initialising the array)

**Comment by paulofreitas** [comment]
This shouldn't be affecting 5.5 for what I've tested. We have tests for soft deleting feature (e.g. https://github.com/laravel/framework/blob/5.5/tests/Database/DatabaseSoftDeletingTraitTest.php) and the Continuous Integration builds for PHP 7.2 aren't failing: https://travis-ci.org/laravel/framework/builds

This indeed affects Laravel 5.1, but the support for bug fixes have been ended - just security fixes are being accepted. 👍

**Comment by GrahamCampbell** [comment]
Thanks everyone.

**Comment by assertchris** [comment]
If 5.1.x is LTS and doesn't support 7.2 then the documentation should reflect [this page](https://laravel.com/docs/5.1) only says PHP >= 5.5.9 (and not PHP >= 5.5.9 < 7.2.0) which means it is promising something that is not being delivered...

**Comment by Dylan-DPC** [comment]
Yes it does because when 5.1 was created PHP 7.2 wasn't even though about :stuck_out_tongue:

**Comment by assertchris** [comment]
I understand that. I'm not suggesting it should support 7.2. Just that releases still being supported should at least tell users which versions of PHP aren't supported. That's not unreasonable.

**Comment by odesenvolvedor** [comment]
I solved by changing "$originalWhereCount = count($query->wheres);" for "$originalWhereCount = is_null($query->wheres)
                     ? 0 : count($query->wheres);" in the function "callScope(callable $scope, $parameters = [])" in the file "/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php"

**Comment by fidahasan** [comment]
we are using Laravel 5.1.46 (LTS), PHP 7.2.4  (project is too large to upgrade)
any solution without changing core file/s ?

**Comment by JesusCieza** [comment]
Thanks!!!
