### ISSUE TITLE
artisan storage:link should create a relative symlink, not absolute

### ISSUE THREAD

**Issue by Jakobud** [laravel/framework#22177]
- Laravel Version: 5.5.21
- PHP Version: 7.1.10
- Database Driver & Version: MySQL 14.14

Currently, `artisan storage:link` creates an absolute path symlink in the `public` directory. It seems like it would be way better to create a relative url symlink. For example to `../storage/app/public`.

The most obvious reason for this is that in a given project, an absolute symlink makes the project non-portable. You can move the project to a different directory or deploy the project onto a server with a different directory structure, etc. If you do, that symlink is always going to be broken.

If you had a relative path symlink, then I would think this would fix the problem. But I also know that different systems handle symlink creation differently so I don't even know if you can commit something like this to a repo. But at least being able to move the project to a different folder on a system, you can know that this symlink won't break. This is actually how I ran across this problem. I created a Laravel install in a temporary folder, installed some dependencies (which created the storage symlink) and then I moved the project to a different folder and got some symlink storage errors, which lead me to figure it out and now I'm here.

I don't think you should require people to run `artisan storage:link` if they don't have to. 

Anyways, any thoughts on this?

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. This isn't a bug so you can open a proposal in the laravel/internals repo

**Comment by Jakobud** [comment]
Oh sorry. I'm not clear on what issues belong where I guess. Thanks,
