### ISSUE TITLE
Use Phpredis Class 'Redis' not found

### ISSUE THREAD

**Issue by haofrank** [laravel/framework#22171]
- Laravel Version: 5.5.*
- PHP Version: 7.1
- Database Driver & Version:

### Description:
I want to use phpredis,and I  rename the Redis facade to Phpredis in my config/app.php. But when I use Phpredis,it show me `Class 'Redis' not found`. I has install the php extension,and use `php -m` show the redis extension;
![image](https://user-images.githubusercontent.com/18546749/33138680-0be8b11a-cfe6-11e7-87f0-5d5a05fdd083.png)

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by themsaid** [comment]
This means the extension is not properly loaded. 

Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
