### ISSUE TITLE
Route::Domain match did not take the highest priorities

### ISSUE THREAD

**Issue by shiroamada** [laravel/framework#22184]
- Laravel Version: 5.5.21
- PHP Version: 7.1.8
- Database Driver & Version: MySQL 5.7

### Description:
I would like to have different login view for different subdomain.

My system has 2 modules for login. 
-Member: www.example.com 
-Agent: agent.example.com

I would like to implement 2 different login layout also different flow but using same users table. 
E.g agent login is fail, it should redirect back to agent login page and show the error message.

-Member: www.example.com/login 
-Agent: agent.example.com/login

inside my routes/web.php
```
Route::domain('agent.example.com')->group(function () {
    Route::get('/login', 'AgentController@showLoginForm')->name('agent.login');
});
```
However, it still show my member login screen even the url is `agent.example.com`

But if I changed to
```
Route::domain('agent.example.com')->group(function () {
    Route::get('/agent-login', 'AgentController@showLoginForm')->name('agent.login');
});
```
It displays the correct controller and view.

I already added the `Route::domain` as the filter. But how come Laravel still pick up the original login route?

Below is partial of my route:list, My sub-domain is listed.
```
|                   | GET|HEAD                               | login                                                | login                              | App\Http\Controllers\Auth\LoginController@showLoginForm                                  | web,guest                         |
| agent.example.com    | GET|HEAD                               | login                                          | agent.login                        | App\Http\Controllers\Agent\Auth\LoginController@showLoginForm                        | web,guest                         |

```

2. Test no.2, it didn't show the echo.

```
\Route::domain('agent.example.com')->group(function () {
    Route::get('login', function () {
         echo "This is my agent login page."
    });
});
```

### Expected Result

If there is domain function is stated and it is matched. It should take the highest priorities instead of look for other. I am not sure how Laravel takes the priorities on the same route.

This is my test:-
```
    \Route::domain('agent.example.com')->group(function() {
        Route::get('agent-login', function () {

            dump('agent-login 1');
        });
        Route::get('agent-login', function () {

            dump('agent-login 2');
        });
    });
```
The output is `agent-login 2`, it did not display `agent-login 1`.

If it is not bug, can I know how do I set it correctly?

Thanks!

**Comment by themsaid** [comment]
I can't replicate this, I have a project that uses a similar setup and it's working fine.

**Comment by SamSolomon0611** [comment]
> Works fine for me too.. no issues

**Comment by shiroamada** [comment]
I just pull in the new Laravel. I am confused the Laravel sequence. 
I have specific the domain(), but I put after `Auth::routes()`, it will still go Laravel default route.

But if I move it to the top, and put 2 methods with same routes, it executed the 2nd one.

```
//this line execute
Route::domain('agent.laravel55not.dev')->middleware(['web'])->group(function () {
	    Route::get('login', function () {
	         echo "This is my agent login page.";
	    });
	    //this one later but execute this one
	    Route::get('login', function () {
	         echo "This is my agent login page.2";
	    });
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


//this line of code did not execute. I put after Auth::routes(), it will go throught Auth::routes(), but I had specific the domain(), but still not having top priorities
Route::domain('agent.laravel55.dev')->middleware(['web'])->group(function () {
	
    Route::get('login', function () {
         echo "This is my agent login page.";
    });
    Route::get('login', function () {
         echo "This is my agent login page.2";
    });
    
});
```

**Comment by themsaid** [comment]
Ok it looks like your routes need to be ogranized based on priority of matching, please seek help on the forums ,his repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
