### ISSUE TITLE
Executing a POST request via Insomnia is always resulting in MethodNotAllowedHttpException

### ISSUE THREAD

**Issue by mfgabriel92** [laravel/framework#22180]
- Laravel Version: 5.5
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7

### Description:
I need to build just the API of a specific function in this project, and for testing purposes I'm using [Insomnia](http://insomnia.rest/). But when attempting to send the request, the application will throw a `MethodNotAllowedHttpException`.

I've set up the following route:

    Route::post('/backend/users/store', 'ClientUserController@insert')->name('cms.users.store');

In the `ClientUserController`, I configured the `insert` method to be allowed as a guest:

    $this->middleware('auth', [ 'except' => [ 'insert' ] ]);

Then I just set up the URL in the software and tried sending a request, causing the exception to be thrown.

![runvu](https://user-images.githubusercontent.com/26734503/33158106-1bc085e8-d042-11e7-9c8e-a82ccfd69a0e.png)

### Steps To Reproduce:
Enter the endpoint into Insomnia and send the request.

**Comment by sisve** [comment]
I do not think there's enough information in this issue to point out a bug, compared to just a general "I cannot get routes to work" support question. It could be cached routes which is cleared with `php artisan route:clear` or something weird in your routes, or it could just be something weird in your routes files.

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue
