### ISSUE TITLE
Infinite loop Eloquent API Resources

### ISSUE THREAD

**Issue by lamberttraccard** [laravel/framework#22186]
- Laravel Version: 5.5.21
- PHP Version: 7.1.8
- Database Driver & Version: MariaDB 10.2.8

### Description:
I have 2 Eloquent Api Resources :
- CartResources
- CustomerResources

Loading their relationships from each others causes an infinite loop. 

### Steps To Reproduce:

```php
class CustomerResource extends Resource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'id'           => $this->id,
            'last_name'    => $this->last_name,
            'first_name'   => $this->first_name,
            'cart'         => new CartResource($this->cart),
        ];
    }
}

class CartResource extends Resource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'id'          => $this->id,
            'customer'    => new CustomerResource($this->customer),
            'expired_at'  => $this->expired_at->toDateTimeString(),
            'products'    => ProductResource::collection($this->products),
        ];
    }
}
```

**Comment by Dylan-DPC** [comment]
I don't think there is much we can do to solve this. One reason calls the other which calls the first one again. Maybe a better way to handle "relation-resources" in the future.

**Comment by sisve** [comment]
Well, how do you expect the generated json object to look like with these recursions?

**Comment by lamberttraccard** [comment]
I needed to load the customer cart every time I load a customer, and the customer when I was loading a cart. Even without the infinite loop I understand I would end up with duplications.
But maybe Laravel could be clever enough to remove the sub level duplicated item.

So loading a cart, the json would look like :
```
{
    id: 1,
    customer: {
        id: 1,
        last_name: 'Doe',
        first_name: 'John'
    },
    expired_at: '2017-10-10 12:00:00',
    products: []
}
```

And loading a customer, the json would look like :
```
{
    id: 1,
    last_name: 'Doe',
    first_name: 'John'
    cart: {
        id: 1
        expired_at: '2017-10-10 12:00:00',
        products: []
    },
}
```

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
