### ISSUE TITLE
Doctrine connection not reset on DB::reconnect()

### ISSUE THREAD

**Issue by dan-iway** [laravel/framework#22181]
- Laravel Version: 5.4
- PHP Version: 7.0
- Database Driver & Version: MySQL

### Description:
- Calling DB::reconnect() calls DB::refreshPdoConnections() which will update the PDOs for the connection. 
- Connection::getDoctrineConnection() sets up a new doctrine connection if it does not exist yet, passes the current PDO and stores it in $this->doctrineConnection. 

If the connection's PDO gets changed via DB::reconnect() the doctrineConnection property does not get updated and still holds the old PDO information. Queries using the doctrine connection will execute using wrong settings.

### Steps To Reproduce:
Assuming two databases with identical structure ('table' containing a column 'column1'):
```php
// running on db 'firstDb' according to db config
Schema::table('table', function (Blueprint $table) {
  $table->renameColumn('column1', 'column2');
});

Config::set('database.connections.mysql.database', 'secondDb');
DB::reconnect();

Schema::table('table', function (Blueprint $table) {
  $table->renameColumn('column1', 'column2');
});
```

This results in:
> There is no column with name 'column1' on table 'table'.

Explanation:
While the first schema change works correctly, the second one wrongly still uses the old PDO information (ie running on db 'firstDb') and sees there is no 'column1' on it because it already got renamed. If the PDO change would have been propagated to the doctrineConnection it would see that the 'column1' still exists on 'secondDb'.

### Workaround:
\App\Database\MySqlConnectionWithPDOFix:
```php
<?php

namespace App\Database;

use Illuminate\Database\MySqlConnection;

class MySqlConnectionWithPDOFix extends MySqlConnection {

	public function reconnect() {
		$this->doctrineConnection = null;
		return parent::reconnect();
	}

	public function disconnect() {
		$this->doctrineConnection = null;
		parent::disconnect();
	}
}
```
\App\Providers\AppServiceProvider:
```php
Connection::resolverFor('mysql', function($connection, $database, $prefix, $config) {
  return new MySqlConnectionWithPDOFix($connection, $database, $prefix, $config);
});
```

Edit: I just realised I had another line of code that was needed to make my initial fix working (Schema::connection('mysql')->getConnection()->reconnect()). Apparently calling DB::reconnect() does not call the connections 'reconnect()' method but simply disconnects and connects again - the doctrine connection is persisted through that as well. I have updated my workaround above to also reset doctrineConnection on disconnect().

**Comment by themsaid** [comment]
5.4 is not supported anymore, please upgrade to 5.5 as we solved lots of issues between the two versions.
