### ISSUE TITLE
Laravel 5.5 Session::put not work

### ISSUE THREAD

**Issue by alihesari** [laravel/framework#22183]
- Laravel Version: 5.5
- PHP Version: 7.2

### Description:
I write a function for login by ajax. `Auth::loginUsingId` worked fine but `seession` dont set. I print session After `Auth::loginUsingId` by `print_r(Session::all())` and output is:

    Array
    (
        [_token] => E7veAvSQM2dfmOcPK83v7VmcSy9Tn597jRtzAN8k
        [login_web_59ba36addc2b2f9401580f014c7f58ea4e30989d] => 1
    ) 

**I searched many time in google and test many solution but the problem not solved. Can any person help me?**

**My login function:**

    public function login_user(Request $request)
    {
        if (!$request->ajax()) return false;
        
        $form_rule = [
            'email'     => 'required|email|max:255',
            'password'  => 'required|min:6',
        ];

        $validator  = Validator::make($request->all(), $form_rule);
        $status     = $validator->fails();

        $form_errors = [];
        foreach($form_rule as $field=>$rules){
            $form_errors[$field] = $validator->errors()->first($field);
        }

        if(!$validator->fails()){
            $user = User::where('email','=',$request['email'])->first();
            if($user != NULL){
                if (Hash::check($request['password'], $user->password))
                {
                    $remember_me = ($request['remember'] == 1)? true : false;
                    Auth::loginUsingId($user->id,$remember_me);
                    //print_r(Session::all());
                }else{
                    $status = true;//has error
                    $form_errors['email'] = $form_errors['password'] = 'Email or password is wrong';
                }
            }else{
                $status = true;//has error
                $form_errors['email'] = $form_errors['password'] = 'Email or password is wrong';
            }
        }
        return json_encode([
            'status'    => ($status)? 'fail' : 'success',
            'result'    => json_encode($form_errors)
        ]);
    }

I create a following route in `web.php` to testing and `var_dump(Session::get('session_test'))` return null;

    Route::group(['middleware' => ['web']], function () {
    
        Route::get('/set',  function(){
            Session::put('session_test', 'working');
        });
        Route::get('/get', function(){
            var_dump(Session::get('session_test'));
            return Session::get('session_test');
        });
    });

**My kernel.php:**

    <?php
    
    namespace App\Http;
    
    use Illuminate\Foundation\Http\Kernel as HttpKernel;
    
    class Kernel extends HttpKernel
    {
        /**
         * The application's global HTTP middleware stack.
         *
         * These middleware are run during every request to your application.
         *
         * @var array
         */
        protected $middleware = [
            \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
            \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
            \App\Http\Middleware\TrimStrings::class,
            \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
            \App\Http\Middleware\TrustProxies::class,
        ];
    
        /**
         * The application's route middleware groups.
         *
         * @var array
         */
        protected $middlewareGroups = [
            'web' => [
                \App\Http\Middleware\EncryptCookies::class,
                \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
                \Illuminate\Session\Middleware\StartSession::class,
                \Illuminate\Session\Middleware\AuthenticateSession::class,
                \Illuminate\View\Middleware\ShareErrorsFromSession::class,
                #\App\Http\Middleware\VerifyCsrfToken::class,
                \Illuminate\Routing\Middleware\SubstituteBindings::class,
            ],
    
            'api' => [
                'throttle:60,1',
                'bindings',
            ]
        ];
    
        /**
         * The application's route middleware.
         *
         * These middleware may be assigned to groups or used individually.
         *
         * @var array
         */
        protected $routeMiddleware = [
            'auth' => \Illuminate\Auth\Middleware\Authenticate::class,
            'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
            'bindings' => \Illuminate\Routing\Middleware\SubstituteBindings::class,
            'can' => \Illuminate\Auth\Middleware\Authorize::class,
            'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
            'throttle' => \Illuminate\Routing\Middleware\ThrottleRequests::class,
        ];
    }

**config/session.php**

    <?php
    
    return [
    
        'driver' => env('SESSION_DRIVER', 'file'),
    
    
        'lifetime' => 120,
    
        'expire_on_close' => false,
    
        'encrypt' => false,
    
        'files' => storage_path('framework/sessions'),
    
        'connection' => null,
    
        'table' => 'sessions',
    
        'store' => null,
    
        'lottery' => [2, 100],
    
        'cookie' => env(
            'SESSION_COOKIE',
            str_slug(env('APP_NAME', 'laravel'), '_').'_session'
        ),
    
        'path' => '/',
    
        'domain' => env('SESSION_DOMAIN', null),
    
        'secure' => env('SESSION_SECURE_COOKIE', false),
    
        'http_only' => true,
    
        'same_site' => null,
    
    ];

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue
