### ISSUE TITLE
Laravel 5.5 showing database details on error screen

### ISSUE THREAD

**Issue by rahulsharma841990** [laravel/framework#22189]
![error](https://user-images.githubusercontent.com/6939188/33187935-980d3a28-d0bb-11e7-992c-ea5d09571645.png)
- Laravel Version: 5.5.21
- PHP Version: 7.1.9
- Database Driver & Version: MySql

### Description:
       In laravel error screen its showing error .env file details like server details and database details, i think that should not there on error screen.

### Steps To Reproduce:
      Just change something in **web.php** and it will show error

**Comment by laurencei** [comment]
You need to set `APP_DEBUG` to `false`.

You can read more about it here: https://laravel.com/docs/5.5/errors#configuration

**Comment by Dylan-DPC** [comment]
This is not a bug and since this repo is for bug tracking it can be closed.

**Comment by rahulsharma841990** [comment]
yes its not a bug, but i think when we have to find any bug on live server then it can creates a problem..
no problem you can close this issue.. but now we should aware about that details.

Thanks

**Comment by devcircus** [comment]
This is the correct, expected behavior. You should never enable APP_DEBUG in production.

**Comment by warmwhisky** [comment]
Why is it necessary to print out the contents of the ENV on an error screen any way?

**Comment by laurencei** [comment]
Because it might be relevant to your error. i.e. perhaps it is loading the wrong config etc.
