### ISSUE TITLE
HttpExceptions are rendering a view when in debug mode.

### ISSUE THREAD

**Issue by luukhoeben** [laravel/framework#22185]
- Laravel Version: 5.5.21
- PHP Version: 7.1.11
- Database Driver & Version: MariaDB 10.2.6

### Description:
When in debug/local mode, I don't get a whoops page when a HttpException is thrown. I just one of the production error reporting views.

For example:
`Whoops, looks like something went wrong.` 
or 
`Sorry, the page you are looking for could not be found.`

**Edit:** Also, I get the same error message instead of a stacktrace when a ModelNotFoundException is thrown when using route model binding.

Is this intended behavior or should this be a whoops error page (when in debug mode at least)?

### Steps To Reproduce:
create new laravel project (5.5) and in the default route use `abort(404);` or `abort(500);`

**Comment by themsaid** [comment]
Can't replicate, looks like something is wrong in your project, test on a fresh laravel installation and you'll find that it's working as expected.

**Comment by luukhoeben** [comment]
This is happening on a fresh laravel 5.5.21 installation.

**Comment by themsaid** [comment]
Sorry, this is the intended behaviour, some exceptions are handled by Laravel and a presentable HTML output is sent instead of the whoops.

**Comment by luukhoeben** [comment]
Ah yes that was my question haha :) but why is that? and is this configurable?
