### ISSUE TITLE
Passport tokens never expire, even when lifetime explicitly set

### ISSUE THREAD

**Issue by thecodemill** [laravel/framework#22199]
- Laravel Version: 5.5
- PHP Version: 7.1
- Database Driver & Version: MySql 5.7.20

### Description:
I am using Passport's client credentials authentication process. Referring to [the Token Lifetimes documentation](https://laravel.com/docs/5.5/passport#token-lifetimes), tokens are long-lived by default, but can be explicitly set to any lifetime. However, it doesn't seem to matter what the expiry time of my token is - I can still authenticate with it way after its expiry time in the database.

Either... Passport doesn't work how I expect it to, there is something wrong in the documentation or there is something wrong with the code.

### Steps To Reproduce:
Setup client credential authentication, using the CheckClientCredentials middleware.

Set the expiration config in AuthServiceProvider:
```php
    /**
     * Register any authentication / authorization services.
     *
     * @return void
     */
    public function boot()
    {
        $this->registerPolicies();

        Passport::routes();
        Passport::tokensExpireIn(Carbon::now()->addSeconds(60));
        Passport::refreshTokensExpireIn(Carbon::now()->addSeconds(60 * 60 * 24));
    }
```

Request a new token at `oauth/token` endpoint.

Use that same token as a Bearer Authorisation token to request a protected route. Eg. `api/some-protected-route`

```php
// routes/api.php
Route::get('some-protected-route', function () {
    return 'Hello.';
})->middleware('client');
```

**Expected result:** "Hello."
**Actual result:** "Hello."

Now, go put the kettle on for a minute...

Make another request to the protected route using the same (now expired) token.

**Expected result:** 401 Authentication error
**Actual result:** "Hello."

**Comment by sisve** [comment]
I believe you've filed this issue in the wrong repository. Try https://github.com/laravel/passport/issues instead.

**Comment by thecodemill** [comment]
Thanks @sisve I hadn't noticed the separate repo.
