### ISSUE TITLE
Translator case insensitivity on Windows

### ISSUE THREAD

**Issue by royvanv** [laravel/framework#22196]
- Laravel Version: 5.5.21
- PHP Version: 7.0.10
- Database Driver & Version: Irrelevant

### Description:
The translator class looks for the translation file in a case insensitive matter on Windows. Causing it to look up a PHP translation file instead of looking for a string in the JSON file.

- Expected result:* a string from the JSON translation file (e.g. `resources/lang/en.json`)
- Actual result:* the content from a PHP translation file (e.g. `resources/lang/en/faq.php`) 

`__('faq')` should return the contents of the file `resources/lang/en/faq.php`.
`__('FAQ')` (or any other non-lowercase variant) should return a string from `resources/lang/en.json`.

### Steps To Reproduce:
- Create a file named `faq.php` in `resources/lang/en` and make it return an array:
```php
<?php
return [
  'key' => 'value',
];
```
- Make sure `resources/lang/en.json` does not exist or does not contain the key `FAQ`. 
- Call `__('FAQ')` or `app('translator')->getFromJson('FAQ')` from a controller.

**Comment by royvanv** [comment]
The quick fix for this issue to add the keys causing problems to `resources/lang/en.json`.

**Comment by themsaid** [comment]
Yeah you need to watch out from this edge case if you're using both translation methods in your project.

**Comment by royvanv** [comment]
@themsaid This is not very clear from reading the [documentation page](https://laravel.com/docs/5.5/localization#retrieving-translation-strings).

Also, I assume this is not an issue on Unix-like systems where file names are case-sensitive. I haven't tested it, yet.

**Comment by themsaid** [comment]
Laravel will first check for a JSON translation string before trying to find a PHP file, so yes including a JSON translation line for that key would fix the issue.
