### ISSUE TITLE
Blade facade mock fails

### ISSUE THREAD

**Issue by rjorel** [laravel/framework#22192]
- Laravel Version: 5.5.21
- PHP Version: 7.1
- Database Driver & Version: -

### Description:
When using the facade mocks, an error will be returned when trying to mock the Blade facade.

### Steps To Reproduce:
- Fresh install of Laravel 5.5
- Add the following test to a phpunit test file :

```php
/**
 * @test
 */
public function mockBlade()
{
    Blade::shouldReceive('compile')->once()->andReturn(null);
}
```
- Run the test

```
PHPUnit reports the following:
PHPUnit 6.4.4 by Sebastian Bergmann and contributors.

E.                                                                  2 / 2 (100%)

Time: 101 ms, Memory: 10.00MB

There was 1 error:

1) Tests\Feature\ExampleTest::mockBlade

ErrorException: Illegal offset type in isset or empty

/home/raphael/Downloads/laravel/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:90
/home/raphael/Downloads/laravel/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:48
/home/raphael/Downloads/laravel/tests/Feature/ExampleTest.php:16

ERRORS!
Tests: 2, Assertions: 1, Errors: 1.
```

The error comes from Blade facade accessor that returns an object:
```php
class Blade extends Facade
{
    /**
     * Get the registered name of the component.
     *
     * @return string
     */
    protected static function getFacadeAccessor()
    {
        return static::$app['view']->getEngineResolver()->resolve('blade')->getCompiler();
    }
}
```
In Facade class, `shouldReceive` method calls `isMock`, defined as:
```php
protected static function isMock()
{
    $name = static::getFacadeAccessor();

    return isset(static::$resolvedInstance[$name]) &&
           static::$resolvedInstance[$name] instanceof MockInterface;
}
```
Is it a bug, or simply that Blade is not intended to be mocked ?

**Comment by themsaid** [comment]
Yeah Blade is not mockable from how it's loaded into the framework, you'll need to let your tests actually generate the final output and assert on that.

**Comment by rjorel** [comment]
Ok. I'm not sure it's suitable to comment a closed issue (it's the first issue I post), but as I'm really interested to understand Laravel logic (I already spent many hours to read code source) and this behavior surprises me.
As the ViewServiceProvider defines `'blade.compiler'` in the service container, I don't understand why the Blade facade doesn't just return that...

**Comment by themsaid** [comment]
Well it really depends on what you are trying to do, I suggest that you post on the forums explaining the type of test you're trying to write, I have a feeling that there's a better approach than mocking the compiler all together, not sure what you'll be testing if the compiler is mocked.

**Comment by rjorel** [comment]
Well, I'll try to find a better approach. Thanks.
