### ISSUE TITLE
Faked uploaded file always return hasFile = false

### ISSUE THREAD

**Issue by luizguilhermefr** [laravel/framework#22203]
- Laravel Version: Lumen (5.5.1) (Laravel Components 5.5.*)
- PHP Version: PHP 7.0.24-1+ubuntu16.04.1+deb.sury.org+1
- Database Driver & Version: MySQL 5.7 PDO

### Description:

When I, for testing purposes, fake a file, it always will return `$request->hasFile('file_key') == false`.

### Steps To Reproduce:

Create a test with the following code:

```php
$response = $this->json('POST', '/videos', [
    'video' => UploadedFile::fake()->create('bear.mp4', 1024)
]
$response->assertResponseStatus(200);
```

and at Controller...

```php
if (! $request->hasFile('video')) {
    return response()->json(['success => false'], 400);
}
return response()->json(['success => true'], 200);
```

See the test fails.

**Comment by luiz-brandao** [comment]
Did you check if the dummy file is getting generated? Did you setup the fake storage?

**Comment by luizguilhermefr** [comment]
It was a problem with the fake storage setup, indeed.

**Comment by ludo237** [comment]
@luizguilhermefr Can you explain a bit what the problem was? I am facing the same issue 😢

**Comment by luiz-brandao-jr** [comment]
@ludo237 you have to setup the fake storage by calling `Storage::fake('disk_name');` 

Check https://laravel.com/docs/5.5/mocking#storage-fake

**Comment by luizguilhermefr** [comment]
Also, you must have this disk set up in your `config/filesystems.php` file.
