### ISSUE TITLE
Applying 'withoutWrapping' to a single Resource causes other resources to double up on 'data' wrappers

### ISSUE THREAD

**Issue by MrJoelKelly** [laravel/framework#22209]
- Laravel Version: 5.5.21
- PHP Version: 7.1.8

### Description:
If you call `::withoutWrapping()` on a single API Resource in a service provider, it has the desired effect of removing the wrapper from that resource.
It unfortunately causes a side-effect of double-wrapping all other resources 'data' keys, **ONLY** when those resources have had some form of pagination or ordering applied to them.

I am still working on figuring out exactly what causes this issue and will update steps to reproduce and any solution as I find them.

### Steps To Reproduce:
1. Apply the `withoutWrapping()` method to a **single** resource in your AppServiceProvider.
2. Pass a paginated collection to a resource collection.
2. Return a resourceCollection that has a `'data' => $this->collection` key.

### Temporary solution:
I managed to fix this temporarily by modifying the constructor for the resource I originally wanted to remove wrapping from.
```
public function __construct($resource)
    {
        static::$wrap = null;
        $this->resource = $resource;
    }
```

**Comment by devcircus** [comment]
You're returning 'data' => $this->collection, which will wrap the resource with a 'data' key. Paginated resources are always wrapped, even if you designate 'withoutWrapping', so you get double wrapping.

**Comment by MrJoelKelly** [comment]
I thought this was part of the issue, but the main issue still stands that `::withoutWrapping()` on a single resource applies this to every single element that `extends Resource`. 

I can't recall, is it even possible to apply `withoutWrapping` to a `ResourceCollection`?

**Comment by themsaid** [comment]
@devcircus has the issue you're looking for, if you have an issue that requires different steps to reproduce please open a new ticket with more clear steps of reproduction.
