### ISSUE TITLE
Laravel 5.5 installation dependency issue

### ISSUE THREAD

**Issue by adnansiddiq** [laravel/framework#22201]
- Laravel Version: 5.5
- PHP Version: 7.0.4
- Database Driver & Version: mysql/5.6

### Description:
As per laravel documentation laravel 5.5 require php version >= 7.0.0 but it's dependency symfony/console required minimum php version 7.0.8. so their is dependency conflict issue.

[error-log](https://screencast.com/t/xlp4nb5tYJ)

### Steps To Reproduce:
install project using command
`laravel new blog`

**Comment by themsaid** [comment]
I don't see anything laravel can do about that, what do you think?

**Comment by 36864** [comment]
If laravel were to do anything about this, the options would be to either bump the required php version or lock the dependency to version 3.3.6, which was the last version before the dependency got bumped from `>=5.5.9` to `^5.5.9|>=7.0.8`, and miss out on bugfixes.

If neither of these options are acceptable, maybe a notice in the documentation strongly suggesting that users keep their php installation up-to-date with bugfix patches.

Related issues: 
https://github.com/symfony/symfony/pull/23703
https://github.com/symfony/symfony/pull/23705

These issues reference the following php bug: https://bugs.php.net/bug.php?id=72229

**Comment by sisve** [comment]
The requirement on on symfony/console is `~3.3` which allows version 3.3.6 that supports php `>=5.5.9`.

Related: https://github.com/laravel/docs/issues/3745

**Comment by GrahamCampbell** [comment]
I think this is fine?
