### ISSUE TITLE
Cannot pass id field to route array in Form::model in laravel 5.4

### ISSUE THREAD

**Issue by AbdulRaheemGhani** [laravel/framework#22212]
- Laravel Version: 5.4
- PHP Version: 7.1
- Database Driver & Version: mysql

### Description:
When I pass the model id field as second parameter to controller action in Form::model, it gives me the following error:

`Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_RECOVERABLE_ERROR)
Type error: Too few arguments to function App\Http\Controllers\DoctorsController::update(), 1 passed and exactly 2 expected`

This is my code:
`{!! Form::model($doctor, ['route' => ['doctors.update',  $doctor->id]]) !!}`

Here is the route:
`Route::post('/doctors/update', 'DoctorsController@update')->name('doctors.update');`

This is the controller action:
`   public function update(Request $request, $id)
    {
        $this->validate($request, 
            [ 'name' => 'required|max:50',
                'percentage' => 'required|digits_between:1,2'
           ]);
        $doctor = Doctor::find($id);
        $doctor->name = $request->name;
        $doctor->percentage = $request->percentage;
        $doctor->save();
        return redirect('/doctors');
    }`

Please Help me.
@taylorotwell 
@JeffreyWay 
@adamwathan

**Comment by Dylan-DPC** [comment]
Hi. The form helper isn't part of the core. If you need help, seek the forums or the slack channel.

**Comment by AbdulRaheemGhani** [comment]
Do you mean that I should transfer my issue from somewhere else?

**Comment by Dylan-DPC** [comment]
Well there are 2 things:

1) This repo is only for bug tracking. So if you need help, ask in the forums or the slack channel

2) Secondly, Form facade isn't part of laravel core but belongs to https://github.com/LaravelCollective/html

**Comment by AbdulRaheemGhani** [comment]
Thanks for the instruction.
@Dylan-DPC
