### ISSUE TITLE
Need for Dynamic EagerLoading 

### ISSUE THREAD

**Issue by muhammadsaeedparacha** [laravel/framework#22221]
- Laravel Version: 5.5
- PHP Version: 7+
- Database Driver & Version: mysql 5.7+

###Scenario:

I have a SaaS application that has flexible database structure, so its fields are bound to change, especially given it has a Json field (for any extra database structure to be created from client side of the application), including relationship based fields. so Account Table can have dynamically created employee_id field, and thus the need to access relationships dynamically

###Problem:
I need to EagerLoad models based on this dynamic relationship. If I had something like this:

```php
// Account Model
public function employee(){
	return $this->belongsTo(App\Employee);
}
```
it would be easy. But what I have is this:
```php
public function modelBelongsTo(){
	return $this->belongsTo($dynamicClassName, $dynamicForeignKey);
}
```

Now if I eager load this, I'll get Account Model instance with related Employee on key `modelBelongsTo`. This is how Eloquent Names based on the function of eagerload. But after this I cannot use this function again to eagerload a second model because it'll just overwrite results on `modelBelongsTo` key.

### Possible Solution Directions:
1) Can I Somehow change laravel's process to use a name I provide?
or
2) Can I write functions on the fly to overcome this so I'll write employee function on the fly?
or
3) Worst Case Scenario: I iterate over all records to rename their keys individually because I am using a pagination, it wouldn't that big of a deal to loop over 10 records.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this github area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I please suggestion closing your issue ticket here. Instead trying asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.

**Comment by rosDNsf** [comment]
What a great response to redirect people to support pages, great work @laurencei!

/cc @Dylan-DPC

**Comment by Dylan-DPC** [comment]
@rosDNsf can you stop mentioning me everywhere? :stuck_out_tongue: If you want to reply to people with links to support, feel free to do so
