### ISSUE TITLE
str_plural() and zero count

### ISSUE THREAD

**Issue by jeanlucnguyen** [laravel/framework#22227]
- Laravel Version: 5.5.21
- PHP Version: 7.1.8

### Description:
str_plural() returns a plural version of the word if 0 is passed as $count argument instead of the singular version.

### Steps To Reproduce:
str_plural('home', 1) -> home
str_plural('home', 2) -> homes
str_plural('home', 0) -> homes

**Comment by zaknes** [comment]
`0 homes` is grammatically correct, `0 home` is not.

If talking about a quantity of zero, you are not counting the total number of items, you are referring to the absence of a collection, ignoring any specific value, which is why the plural is used.

**Comment by jeanlucnguyen** [comment]
Didn't know about that. Just learnt something new about English ! Thanks

**Comment by cotiga** [comment]
In French grammar the following word 0 must be written in the singular.
It is therefore not recommended to use the str_plural() helpers on French language sites, but to create its own function.
