### ISSUE TITLE
withCount and BelongsToMany: Maximum function nesting level of 'xxx' reached

### ISSUE THREAD

**Issue by sylouuu** [laravel/framework#22229]
- Laravel Version: 5.5.21
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7

### Description:

When you add `$withCount` on two models that are linked with a `BelongsToMany` and you want to retrieve one it stops because of "infinite loop".

If you comment any `$withCount` there is no error.

### Steps To Reproduce:

Exam.php

```php
protected $withCount = ['blogPosts'];

public function blogPosts(): BelongsToMany
{
    return $this
        ->belongsToMany(BlogPost::class, 'blog_post_exam_pivot', 'exam_id', 'blog_post_id')
        ->withTimestamps();
}
```

BlogPost.php

```php
protected $withCount = ['exams'];

public function exams(): BelongsToMany
{
    return $this
        ->belongsToMany(Exam::class, 'blog_post_exam_pivot', 'blog_post_id', 'exam_id')
        ->withTimestamps();
}
```

**Comment by Dylan-DPC** [comment]
This is a known issue. Since there is a cyclic relationship there is no where at this point Laravel will know not to fetch the count/relationship again

**Comment by sylouuu** [comment]
@Dylan-DPC Any tips or workaround?

Best

**Comment by sisve** [comment]
@sylouuu Do separate queries for the numbers.
