### ISSUE TITLE
where() does not work with json columns on existing collections

### ISSUE THREAD

**Issue by Marcuzz** [laravel/framework#22238]
- Laravel Version: 5.5.22
- PHP Version: 7.1.10
- Database Driver & Version: PostgreSQL 9.5.9

### Description:
Is it intentional that json/jsonb operators in where() doesn't work on collections, and only the initial query?

```php
dd(JobApplicationAction::where('blob->action', 'denied')->get());
```

This returns the items it's supposed to.

However, when I have a parent collection of `JobApplication` which has an "actions" relation that grabs from `JobApplicationAction` I get an issue:

```php
$this->each(function($item, $key) {
	dd($item->actions->where('blob->action', 'denied'));
});
```

this returns an empty collection, 

```php
Collection {#685 ▼
  #items: []
}
```

even though there are actions with the value "denied" as proven here

```php
$this->each(function($item, $key) {
	dd($item->actions);
});
```

```php
"blob" => "{"action": "denied"}"
```

if I `->where()` anything else, like the `item_id` I get the rows I want, it's just the json operators that don't seem to work. If this is intended behaviour it seems like a huge oversight as it works differently from how you'd expect it to work, considering it works on the initial query but not on the collection.

### Steps To Reproduce:
- Create a parent model
- Create a model that relates to the parent model through a primary key `id` -> `item_id` with a json or jsonb column
- Grab the parent model and eager or lazy load the related model
- `->each()` the collection you get and try to `->where('json->key', 'value')` on the related model

You'll find that you get no results even though you should get results.

**Comment by sisve** [comment]
Yes, support for json columns were just that, json _columns_. You can most easily solve this by adding the attribute containing json to your $casts and then query it as a nested array.

https://laravel.com/docs/5.5/eloquent-mutators#array-and-json-casting

**Comment by themsaid** [comment]
Yes it only works on the query builder.
