### ISSUE TITLE
'route model binding' let $request->route('param') return string or object

### ISSUE THREAD

**Issue by green-mike** [laravel/framework#22234]
laravel issue

- Laravel Version: 5.5.22
- PHP Version: 7.1.9
- Database Driver & Version: Mysql 5.7

### Description:
'route model binding' let $request->route('param') return string or object. But it depend on that the model is resolved or not. It may cause some problem because high coupling. For Example, the formRequest can't fetch origin route param by "$request->route('param')". It means the formRequest is hard to reuse. Middleware has same situation, So need to very careful the controller is resolving model or not. Thanks for reading.

### Steps To Reproduce:

laravel new Project 

at 'routes/web.php' paste:
```php
Route::get('/users/{user}', function (Illuminate\Http\Request $request, App\User $user) {
    return $request->route('user');
});
Route::get('/second-example/{user}', function (Illuminate\Http\Request $request) {
    return $request->route('user');
});```

**Comment by sisve** [comment]
What if you use explicit model binding and saying that `{user}` always is a User?

    Route::model('user', App\User::class);

https://laravel.com/docs/5.5/routing#explicit-binding

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. This isn't a bug so you can open a proposal in the laravel/internals repo

**Comment by green-mike** [comment]
thank you, I will post it in the laravel/internals repo.

**Comment by SantosVilanculos** [comment]
If you are experiencing the same issue, insert this code snippet into the `boot` method of your application's `AppServiceProvider.php` file. Everything will work correctly.

```php
Route::bind('user', function (string $value, \Illuminate\Routing\Route $route): User {
    $column = $route->bindingFieldFor('user');

    if (is_null($column)) {
        return User::query()->findOrFail($value);
    }

    return User::query()->where($column, $value)->firstOrFail();
});
```
https://laravel.com/docs/12.x/routing#customizing-the-resolution-logic
