### ISSUE TITLE
Eloquent resources and conditional attributes.

### ISSUE THREAD

**Issue by mits87** [laravel/framework#22232]
- Laravel Version: 5.5.19
- PHP Version: 7.1
- Database Driver & Version: MySQL 7.1

### Description:
Eloquent API Resources are awesome, but I have small problem. 
I would like to only include an attribute in a resource response if a value exists.
Now, I have to use `when` method and condition inside:

``` php
public function toArray($request)
{
    return [
        'id' => $this->id,
        'name' => $this->name,
        'details' => $this->when(! is_null($this->details), $this->details),
    ];
}
```

IMHO should be an extra method for instance:
`$this->whenExists($this->details)`

What are you thinking about it?

My second problem: when I use:

``` php
public function toArray($request)
{
    return parent::toArray($request);
}
```

there are date attributes `created_at`, `updated_at` etc. then the `toArray()` should return these attributes as date object but it doesn't.

If I do:

``` php
public function toArray($request)
{
    return [
        'created_at' => $this->created_at,
        'updated_at' => $this->updated_at,
   ];
}
```

then the `create_at` and `updated_at` attributes are date objects, but in previous example these attributes are only a datetime string.

**Comment by sisve** [comment]
1. This can already be done easily with the existing language features.

        'details' => $this->details ?: new MissingValue,

2. You get your timestamps as strings because your $model->toArray() returns them as strings. Json has no concept of datetime values, so it doesn't make sense to attempt to send them as such.

**Comment by mits87** [comment]
1. I don't agree with you. We have the `$this->when()` method which return `details` attribute if condition inside is true. Your solution always return 'details' attribute. 

In my previous post I wrote about extra method which will be very similar to `when` but the new method (for instance `whenExists`) will return 'details' attribute if param will be not empty. 

2. You are right, but IMHO `parent::toArray($request);` should respect all model configurations like `cast`, `date` attributes etc.

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
