### ISSUE TITLE
Problem with eloquent fresh method

### ISSUE THREAD

**Issue by mits87** [laravel/framework#22233]
- Laravel Version: 5.5.19
- PHP Version: 7.1

### Description:
I have one model with global scope. For instance:

``` php
<?php

namespace App;

use Eloquent\NestedAttributes\Model;

class Facility extends Model {
    protected static function boot(): void {
        parent::boot();
        static::addGlobalScope('f1', function (\Illuminate\Database\Eloquent\Builder $builder) {
            $builder->select('facilities.*')->addSelect(\DB::raw('NOW() AS now_date'));
        });
    }
}
```

Now we can check in `php artisan tinker`:

``` php
>>> \App\Facility::get();
=> Illuminate\Database\Eloquent\Collection {#1183
     all: [
       App\Facility {#1185
         id: 1,
         name: "sss",
         description: null,
         created_at: "2017-11-22 14:58:00",
         updated_at: "2017-11-22 14:58:00",
         now_date: "2017-11-22 15:00:05",
       },
     ],
   }

>>> $f = \App\Facility::create(['name' => 'sss1']);
=> App\Facility {#1186
     name: "sss1",
     updated_at: "2017-11-22 15:00:14",
     created_at: "2017-11-22 15:00:14",
     id: 2,
   }
```

and `fresh()` method should return extra attribute `now_date` but it doesn't.

``` php
>>> $f->fresh()
=> App\Facility {#1176
     id: 2,
     name: "sss1",
     description: null,
     created_at: "2017-11-22 15:00:14",
     updated_at: "2017-11-22 15:00:14",
   }
>>>
```

Could you fix it?

**Comment by Dylan-DPC** [comment]
This is intended: 
> fresh(): Reload a fresh model instance from the database

So it will load the row from the database not re-fire the query.

**Comment by mits87** [comment]
Maybe this is wrong way?
Now we can't pass a new row as eloquent object to Eloquent API Resources class with all data (scopes etc.).

``` php
$f = \App\Facility::create(['name' => 'sss1']);

return new FacilityResource(
  $f->fresh()
);
```

now in the `FacilityResource` we can't get any data from Facility scopes.
We can always pass new query:


``` php
$f = \App\Facility::create(['name' => 'sss1']);

return new FacilityResource(
  \App\Facility::find($f->id)
);
```

but now the `wasRecentlyCreated` attribute is always false and FacilityResource return status code 200 but should 201.

**Comment by mits87** [comment]
Yes, I know but I think it is a bug. 
We have something like `Resource` class which return automatically a status code when an eloquent object is created or updated. 

So if the `create` or `fresh` method can't get full data like query `Model::find()` then `Resource` class can't return full data and correct status code. 

That's why I think it is a bug of the `fresh` method or ... 
maybe we need another method like `fresh`which will return all data like `Model::find()` with the `wasRecentlyCreated` flag with `true` value.

**Comment by themsaid** [comment]
Fresh doesn't use scopes by default, this is by design, if you want a different behaviour you can add your own version of fresh in a base model.

To me that scope you're adding is not the best approach, using am eloquent mutator is a better approach.

**Comment by aleemb** [comment]
> Fresh doesn't use scopes by default, this is by design, if you want a different behaviour you can add your own version of fresh in a base model.

@themsaid would be swell if it could though, ran into the same limitation today.
