### ISSUE TITLE
"php artisan migrate" bug using the Artisan Facade not working.

### ISSUE THREAD

**Issue by Yaeker** [laravel/framework#22247]
- Laravel Version: 5.5.22
- PHP Version: 7.1.11
- Database Driver & Version: MySQL

### Description:
I'm trying to use Artisan::call method and on all 'migrate' options, it outputs the following Exception message:

"Symfony\Component\Console\Exception\CommandNotFoundException with message 'There are no commands defined in the "migrate" namespace.'".

Works with all other commands. 

### Steps To Reproduce:
Simply try to call Artisan::call('migrate') or Artisan::call('migrate:refresh') from the tinker.
![migrate_bug](https://user-images.githubusercontent.com/20214070/33374778-6c85a12c-d4ff-11e7-8e92-0a7663f44f45.PNG)

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
