### ISSUE TITLE
$response->assertSee Does not work properly

### ISSUE THREAD

**Issue by arzola** [laravel/framework#22253]
- Laravel Version: 5.5.21
- PHP Version: 7.1.11
- Database Driver & Version: MySQL 14.14 Distrib 5.7.17

### Description:

`$response->assertSee('Text')` does not work properly if your controller action does not exists and you will get green instead of red because it's not throwing an exception

### Steps To Reproduce:

1. Create a Controller with `php artisan make:controller Hello`;

2. Create the route defined in `web.php`

`Route::get('/myaction', 'Hello@hello');`

3. Try to do some assertion to see **Hello** and you got green even the controller action method `hello` does not exists yet

```php
public function test_if_controller_action_prints_hello()
    {
        $response = $this->get('/myaction');
        $response->assertSee('Hello');
    }
```

**Comment by Dylan-DPC** [comment]
I'm not sure if there is much the assertion can check for. Also it is recommended to check the status of the response when you do a `$this->get()` or any other call.

**Comment by laurencei** [comment]
Is this passing because the error has the word "Hello".

i.e. the assertion is correct - because "Hello" is appearing on the page.
