### ISSUE TITLE
Is it possible to modify what the `php artisan view:cache` command does?

### ISSUE THREAD

**Issue by HapLifeMan** [laravel/framework#22251]
Hey,

Is it possible to modify what the `php artisan view:cache` command does?
I want to add some scripts (JS or PHP) when we launch this command to replace some HTML tags on cached views in production...

Thanks!

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by HapLifeMan** [comment]
Of course x)
