### ISSUE TITLE
Rule::unique orWhere doesn't work

### ISSUE THREAD

**Issue by antpuleo2586** [laravel/framework#22260]
- Laravel Version: 5.4.36
- PHP Version: 7.1
- Database Driver & Version: Mysql 5.7

### Description:
When I add a `where` closure to `Rule::unique()` and call `orWhere()` on the `$query` object, this is ignored and an `AND` clause is added to the query instead.

I get `"query" => "select count(*) as aggregate from 'table' where 'column' = ? and ('another_column' = ?)"` when I log out, using both `$query->where` and `$query->orWhere`

### Steps To Reproduce:
Create a validation rule as follows:

```
Rule::unique('table')->where(function ($query) {
    $query->orWhere('column', 1);
}),
```

I need to do this as in my example, I'm validating that a `name` field is unique as well as the `slug` of the name.

Sometimes the `name` CAN be unique while the `slug` is not, which is why I need an `orWhere` to be able to achieve this.

I've ended up creating my own custom rule to do this, but would be nice if it was supported.

Cheers!

**Comment by Dylan-DPC** [comment]
Hey

5.4 is no longer supported. Can you upgrade or reproduce this issue on 5.5 and let us know if it still exists?
