### ISSUE TITLE
FilesystemAdapter->putFileAs() appends a leading '/' to the 

### ISSUE THREAD

**Issue by GitIDHere** [laravel/framework#22263]
- Laravel Version: 5.4.36
- PHP Version: 5.6.25
- Database Driver & Version: 5.7

### Description:
When saving a file with ``$file->saveAs()`` or with the facade ``Storage::putFileAs()`` the filepath returned appends a leading ``/``. This is because it is the ``/`` is hardcoded in the ``putFileAs()`` method within the ``Filesystem\FilesystemAdapter`` which gets called later down the chain.

For example, 
````
public function storeAvatarOriginal(UploadedFile $file)
{
	if($file->isValid()){
		$fileName = 'user_avatar_'.time().'.'.$file->extension();
		$dirPath = 'app/user_avatars/original/';
		$filePath =$file->storeAs($dirPath, $fileName);
	}
}
````

**Comment by Dylan-DPC** [comment]
Hey
5.4 is no longer supported. Can you verify if this behaviour still exists on 5.5?
