### ISSUE TITLE
Get wrong extention from audio files

### ISSUE THREAD

**Issue by argb** [laravel/framework#22266]
- Laravel Version: 5.5.*
- PHP Version:7.1
- Database Driver & Version:

### Description:
If the uploaded file is a mp3, Laravel guess the file as audio/mpeg file, and give the file extension .mpga, but it should be a .mp3 file.
if the .mp3 file is changed to .mpga, the HTML5 tag <audio>  can't play it on safari browser.
I tested it.

I temporily fixed it like below

` $ext = $file->extension();
        // laravel的后缀猜测有问题，mpga貌似不是一个合法的后缀,在safari的audio标签播放不了,后缀改成mp3就可以
        // 或者这里直接使用客户端后缀

        if($ext =='mpga'){
            $ext = 'mp3';
        }`

I am not sure if .mpga is a legal file extension name.
How do you guys think about this problem?

**Comment by jmarcher** [comment]
Well the extension method is working as expected this is a case you need to handle on your side.

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
