### ISSUE TITLE
Add 'unique_with' validator to support composite unique keys

### ISSUE THREAD

**Issue by kirtangajjar** [laravel/framework#22268]
There are times when we want to validate composite unique keys.

For example, in my migration I have -
```
$table->unique(['class_short_name', 'programme_short_name'], 'classes_unique_key');
```
Now `unique` validator is only able to validate a single column. We cannot validate combination of column to be unique.

Currently to implement such functionality, we have to use [external libraries](https://github.com/felixkiss/uniquewith-validator) or define custom validators as described [here](https://stackoverflow.com/a/42116158/2867422)

It would be great if laravel could provide this feature out of the box.

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
