### ISSUE TITLE
Permissions errors on new application via installer

### ISSUE THREAD

**Issue by marklabrecque** [laravel/framework#22265]
- Laravel Version: 5.5.22
- PHP Version: 7.1.11
- Database Driver & Version: MySQL 5.7.20

### Description:
Using the latest laravel/installer (v1.4.1) when generating a brand new application, there are multiple permission errors when you first load the application via the browser. The first issue is a missing ./storage/logs/laravel.log file. After fixing this, the ./storage/framework/sessions folder had restricted permissions, not allowing the session hash folder to be created. After correcting that, same issue with the ./storage/framework/views folder- unable to create the hash folder due to permissions. In each case, once I opened up permissions on the parent folder, the issue went away. Perhaps there needs to be some permission adjustments in the installer script?

### Steps To Reproduce:
Run laravel new project on the command line, setup your web server to point to that folder's public folder and hit that vhost in the browser to see the first error.

**Comment by Dylan-DPC** [comment]
I don't think this is a bug. You have to set the permissions on your own.

**Comment by themsaid** [comment]
Please ask on the forums, seems like an issue with your environment. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.

**Comment by marklabrecque** [comment]
Interesting. It's weird, because in the past, when I have created a new application, I just ran the installer and hit it in my browser and it showed the welcome screen. Not sure what changed.

Anyways, not a big deal. The only reason I brought it up at all was in case other people were experiencing the issue. If it's just me, please disregard :)

Thanks for the quick response!
