### ISSUE TITLE
MailMessage->to() function is missing

### ISSUE THREAD

**Issue by emergingdzns** [laravel/framework#22276]
- Laravel Version: 5.5.22
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.5

### Description:
MailMessage.php in Notification is still missing the to() function. I remember seeing some discussion not too long about about how it was removed in 5.5 or 5.4 (I was there in 5.3) and then it got put back in. But apparently it never made it to production because I still don't have the ability to define the to address when I'm using the notification system. I am NOT wanting to use the basic Mail function because we are sending notifications about specific things and re-coding this entire package to use the "dumb" mail program (no delay scheduling etc) would be ridiculous.

### Steps To Reproduce:
Try sending a notification (excerpted from our package):
```
return $notifiable->format(
            (new MailMessage())
                ->subject('Notification of account balance.')
                ->to($user->email)
               ->view('someview'));
```

Will this ever get added back in?

**Comment by cr0wst** [comment]
I found this which appears to be relevant https://github.com/laravel/internals/issues/516 and has a possible solution for the time being.  I'm curious why your `$user` isn't the `$notifiable` that you're trying to send the email to?  Perhaps it's the same reason in the linked issue.

The `to` method was removed in commit ff68549. I couldn't find the discussion about adding it back in.

**Comment by a-komarev** [comment]
In Laravel 5.5 you can use [On-Demand Notifications (Anonymous Notifications)](https://laravel.com/docs/5.5/notifications#on-demand-notifications). They could be sent to any custom recipient.

**Comment by emergingdzns** [comment]
@a-komarev  that's AWESOME! I hadn't noticed that. Only issue is can we format the message content? The documentation doesn't show any example of how to do so.

**Comment by a-komarev** [comment]
[Customize email views](https://laravel.com/docs/5.5/notifications#customizing-the-components). Does this helps?

**Comment by emergingdzns** [comment]
Thanks but all that does is publish the default views. But what I want to be able to do is define WHICH view I want it to use when sending. We have numerous different views we want to use depending on the notification.

**Comment by a-komarev** [comment]
Just use `view` method when you are instantiating `MailMessage` class:

```php
return (new MailMessage)
            ->view('my.awesome.view')
            ->subject('Super subject');
```
