### ISSUE TITLE
[5.5] container::makeWith() attempts to resolve optional params

### ISSUE THREAD

**Issue by lougreenwood** [laravel/framework#22271]
- Laravel Version: 5.5
- PHP Version: 7.1.10
- Database Driver & Version: N/A

### Description:
It seems the the `makeWith` method is attempting to resolve optional params:

```
final class SomeClass
{
    public function __construct( string $some_thing, User $user = null, ?OptionalObject )
    {
	    var_dump(func_get_args());
	    die();
    }
}

...

container->makeWith( SomeClass:class, [
    'some_thing' => 'my string',
    'user'             => SomeUserFactory::spawn()
]);
```
In this example, it seems that makeWith tries to resolve the omitted,`OptionalObject`. Setting the default value as null doesn't help either:

` public function __construct( string $some_thing, User $user = null, ?OptionalObject = null )`

I recently moved from PHPDI to Laravel container, which is how I stumbled across this bug.

### Steps To Reproduce:
Above

**Comment by lougreenwood** [comment]
This leads onto another bug where if some method signature looks like this:

```
public function __construct( string $some_thing, ?OptionalObject = null, ?User $user = null )
    {
	    var_dump(func_get_args());
	    die();
    }
```

```
container->makeWith( SomeClass:class, [
    'some_thing' => 'my string',
    'user'             => SomeUserFactory::spawn()
]);
```

Doesn't inject the valid `$user` param from the factory, because the preceeding`OptionalObject` failed to resolve - `func_get_args()` returns:

```
array (size=3)
  0 => string 'my string' (length=9)
  1 => null
  2 => null
```

i.e the `User` object is missing.

**Comment by lougreenwood** [comment]
FYI - (maybe not too useful, but...) If I switch out the Laravel container for a PHP DI container, it works fine in these examples.

**Comment by Dylan-DPC** [comment]
What is the error you are getting?

Also "optional dependencies" do not make sense. You eiher have a dependency or you don't. It is one of the most talked about points in discussions on DI. 

You can read [this](http://richardmiller.co.uk/2014/03/17/avoiding-optional-dependencies/)

**Comment by lougreenwood** [comment]
Yeah, I know I need to refactor and remove the optional dependencies, but unfortunately, this was discovered whilst deep on a separate refactor task 😃 

The error I receive is triggered by the 'optional' not being instanstiable by the container because it has a required param which the container can't set:

`Exception message: Unresolvable dependency resolving [Parameter #0 [ <required> integer $id ]] in class Model\AbstractModel`

This is because `SomeClass` extends `AbstractModel` and `AbstractModels constructor looks like{
`function __construct( (int) $id ){...}`

But to be honest, the second/subsequent bug (where `func_get_args()` returns null for params which explicitly had values set by `makeWith()`) is more worrying because it doesn't result in any exception by itself...

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.

**Comment by lougreenwood** [comment]
@themsaid Why was this closed, this isn't a feature request and is infact a bug and possibly quite a critical one.

If the container is incorrectly resolving parameters, that could lead to some very weird and hard to de-bug issues...

**Comment by lougreenwood** [comment]
Please carefully read my second comment...

**Comment by lougreenwood** [comment]
And even the first comment isn't really a suggestion, but is instead a bug in how the container seems to interpret PHP 7 optional/nullable method params....

**Comment by themsaid** [comment]
Feel free to open a PR with your suggested changes, it's better to discuss an implementation at this point, I don't see any further discussions leading us to somewhere, the issue will remain open for months if we keep it like this, just share with us what you think should be changed.

**Comment by themsaid** [comment]
Also what's `?OptionalObject` ??

**Comment by lougreenwood** [comment]
But why close a bug report? PR or not - unless you can explain why this is just a suggestion it seems that this should remain open...

**Comment by lougreenwood** [comment]
> Also what's `?OptionalObject` ??

http://php.net/manual/en/migration71.new-features.php

**Comment by themsaid** [comment]
I don't believe it's a bug, that's why I suggested we move it to laravel/internals, that's where we discuss things like that.

**Comment by lougreenwood** [comment]
(FYI - just fixed a typo in those method signatures...)

**Comment by themsaid** [comment]
Ok now I get it, but we really can't make such change in a point release or people might complain it broke their app, if we're going to change this we might do it in 5.6, before such releases we check laravel/internals for changes like this to see if we can implement it without introducing a huge breaking change or not.

**Comment by lougreenwood** [comment]
OK - but this is still a 'bug' (Laravel's container exhibits unexpected behaviour using standard PHP features for a supported PHP version) - so technically, it seems that this should also stay open as a bug report.

I'm not suggesting some new feature to be considered for inclusion in 5.6 - I'm reporting a bug in how Laravel 5.5 behaves with >= PHP 7.1 today.

**Comment by lougreenwood** [comment]
@themsaid so, are we going to re-open this bug (not feature suggestion)?
