### ISSUE TITLE
[5.5] Auto-registration of Artisan commands depends on composer.json

### ISSUE THREAD

**Issue by macghriogair** [laravel/framework#22272]
- Laravel Version: v5.5.21
- PHP Version: PHP 7.1

### Description:

Auto-registration of Artisan commands requires the presence of `composer.json` in order to detect App namespace.

#### Scenario:

I have a deployment process that is executing artisan commands after the artefact has been deployed to the stage or production server. The file composer.json is not included in the artefact installed.

Now in `App\Console\Kernel::commands()`

    $this->load(__DIR__.'/Commands');

will obviously fail because it defers to `App::getNamespace()` which currently looks into the autoload.psr-4 of `composer.json` as stated here https://github.com/laravel/framework/issues/16570

Setting the namespace programatically has been recently declined here https://github.com/laravel/framework/pull/17059

My quick solution was to remove the line `$this->load(__DIR__.'/Commands');`
and do manual registration.

### Steps To Reproduce:

In a fresh Laravel install:

      $ artisan make:command FooCommand
      Console command created successfully.
      $ mv composer.json composer.json.bak
      $ artisan list
                                                                                                     
        [ErrorException]                                                                             
        file_get_contents(/var/www/composer.json): failed to open stream: No such file or directory  
                                                                                                     

My scenario might be a rare edge case. But it can be somewhat tricky to foresee, because usually this won't happen locally or during Continuous Integration. And it will not occur before a Command Class is created & deployed for the first time.

I'd recommend to at least add a note to the docs: https://laravel.com/docs/5.5/artisan#registering-commands.

But I am not sure where else calls to getNamespace() might occur in production?
(Which would possibly be a legitmate argument to deploy composer.json along).

**Comment by themsaid** [comment]
That seems like an edge case, don't use the feature if it doesn't work for you :)
