### ISSUE TITLE
Eloquent builder is not using namespace with where clause

### ISSUE THREAD

**Issue by fico7489** [laravel/framework#22281]
- All Laravel Versions
- All PHP Versions

Using Illuminate\Database\Eloquent\Builder where() method like this : 

OrderItem::where(['id' => 1])->get();

Produces this query :

```
Array
(
    [0] => Array
        (
            [query] => select * from "order_items" where ("id" = ?)
            [bindings] => Array
                (
                    [0] => 1
                )
            [time] => 0.05
        )
)
```

But a better way would be this : 

```
Array
(
    [0] => Array
        (
            [query] => select * from "order_items" where ("order_items.id" = ?)
            [bindings] => Array
                (
                    [0] => 1
                )
            [time] => 0.05
        )
)
```

The problem is that eloquent is not using namespace with where clause (probably with all clauses) and this is very frustrating when I use join.

This query works well
```
OrderItem::where(['id' => 1])->get();
```
but adding join I get

```
OrderItem::where(['id' => 1])
	->join('orders', 'orders.id', '=', 'order_items.id');
	->get();
```

PDOException: SQLSTATE[HY000]: General error: 1 ambiguous column name: id

After adding join I need to change where clauses in all places from
```
OrderItem::where(['id' => 1])->get();
```
to 
```
OrderItem::where(['order_items.id' => 1])->get();
```
and this is really awkward, even if I use this : 

```
OrderItem::where([OrderItem->getTable() . '.id' => 1])->get();
```

Do you have any suggestion how to solve my problem elegant and second question is are you planning to change this in future?

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by snapey** [comment]
When you use joins you must specify the table name, wherever there is ambiguous names.  Your example is not an issue since you don't use a join, and if you did Eloquent would have no way of knowing with ID you meant so you would still end up telling it which table's ID you want to use in the where statement.

**Comment by fico7489** [comment]
My question is whether is more logical that this code

```
OrderItem::where(['id' => 1])->get();
```

produces this query 

```
select * from "order_items" where ("id" = ?)
```

or this 

```
select * from "order_items" where ("order_items.id" = ?)
```

what are you think about this ?

Many people are using join clause for logic, not for joining more data.
For example, I want to get all order items which have order, eloquent query for this case is

```
OrderItem::where(['id' => 1])
	->join('orders', 'orders.id', '=', 'order_items.order_id')
	->groupBy('order_items.id')
	->select('order_items.*')
	->get();
```

but now I have to update all my where clauses in my codebase from 

```
->where('name', 'test')
```

to

```
->where('order_items.name', 'test')
```

and is very awkward. If laravel would do this by default, this would not be necessary. 

I think that would be nice that this 3 eloquent queries produces following sql queries

```
OrderItem::where(['id' => 1])->get();
select * from "order_items" where ("order_items.id" = ?)

OrderItem::where(['order_items.id' => 1])->get();
select * from "order_items" where ("order_items.id" = ?)

OrderItem::where(['orders.id' => 1])->join('orders', 'orders.id', '=', 'order_items.order_id')->get();
select * from "order_items" inner join "orders" on "orders"."id" = "order_items"."order_id" where ("orders.id" = ?)
```

**Comment by themsaid** [comment]
Feel free to submit a PR if you can cover all the supported database engines.

For suggestions and feature requests please use the https://github.com/laravel/internals repo.
