### ISSUE TITLE
HTML getting encoded inside @foreach in markdown mail

### ISSUE THREAD

**Issue by nmfzone** [laravel/framework#22290]
- Laravel Version: 5.4.36
- PHP Version: 7.1.8
- Database Driver & Version: Mysql & Version 14.14 Distrib 5.7.16

### Description:
HTML tag inside `@foreach` loop in markdown mail getting encoded. But, HTML is rendered when placed outside `@foreach` loop.

It's just same with the actual markdown format. Markdown not getting processed when It's placed inside `@foreach` loop. But it's processed when placed outside `@foreach` loop.

### Steps To Reproduce:
1. Create markdown named `todo.blade.php`, and fill with this:
```
@component('mail::message')
  # Todo

  @foreach(range(1, 4) as $item)
    <img src="https://farm5.staticflickr.com/4273/34378170890_3901a0ac25_k.jpg" width="80px" />
  @endforeach
@endcomponent
```
2. Try to sending mail.
3. You'll get an email with HTML Source something like this:
```
<pre style="font-family: Avenir, Helvetica, sans-serif; box-sizing: border-box;"><code>
&lt;img src="https://farm5.staticflickr.com/4273/34378170890_3901a0ac25_k.jpg" width="80px" /&gt;

&lt;img src="https://farm5.staticflickr.com/4273/34378170890_3901a0ac25_k.jpg" width="80px" /&gt;

&lt;img src="https://farm5.staticflickr.com/4273/34378170890_3901a0ac25_k.jpg" width="80px" /&gt;

&lt;img src="https://farm5.staticflickr.com/4273/34378170890_3901a0ac25_k.jpg" width="80px" /&gt;
</code></pre>
```

**Comment by krecebli** [comment]
This is not a bug. The mardown mail should work like this. Try this:

```markdown
This is your logo 
![Some option text][logo]

[logo]: {{asset('/img/official_logo.png')}} "Logo"
```

Reference:
https://stackoverflow.com/questions/42503168/laravel-5-4-embed-image-in-mail

**Comment by nmfzone** [comment]
@krecebli Yes, I've tried that. It works fine when placed outside `@foreach` loop. Did you try it?

**Comment by krecebli** [comment]
@nmfzone No, I didn't. But you've tried it inside `@foreach` and it didn't worked?

**Comment by nmfzone** [comment]
@krecebli Yeah of course. That's why I posted here.

**Comment by krecebli** [comment]
@nmfzone I have tried and I confirm the issue. The code worked neither inside `@foreach` nor outside.

**Comment by nmfzone** [comment]
@krecebli Worked? hmmmm...What Laravel version you're using?

**Comment by krecebli** [comment]
@nmfzone Please, pay attention to `neither nor` :) Let me to rephrase: The code didn't work both inside @foreach and outside. That's why I confirmed the issue :)

**Comment by nmfzone** [comment]
@krecebli Whoops, sorry I missed that `neither nor` :sweat_smile:

**Comment by krecebli** [comment]
@nmfzone it happens :)

**Comment by Dylan-DPC** [comment]
Laravel 5.4 is no longer supported. If you need further help with this, you can consult the forum or the docs.  

IF you consider this a bug, you can reproduce it on a 5.5 repo and see if it still arises.

**Comment by sisve** [comment]
Lines in markdown starting with four spaces are considered code snippets.

    Same as GitHub does.

Your foreach-loop generates something that is indented that way.

**Comment by nmfzone** [comment]
@sisve Hmmmm, you're correct. I just thinking Laravel should handle `@foreach` in some way, so the code not treated as code snippets.

**Comment by tpresing** [comment]
I have this issue too, the code inserts in <pre> tag :(
