### ISSUE TITLE
Route::redirect breaks when using subdomain routing

### ISSUE THREAD

**Issue by rs-sliske** [laravel/framework#22297]
- Laravel Version: 5.5.22
- PHP Version: 7.1.11
- Database Driver & Version:

### Description:
I tried to use Route::redirect inside a Route::domain group and got and error saying "The HTTP status code "0" is not valid."

when looking into it i think the issue is because the subdomain parameter gets inserted into the start of the parameters array, so the expected variables are offset.

![image](https://user-images.githubusercontent.com/1929019/33559569-27c505dc-d905-11e7-9136-283de15c6a25.png)

"admin" is my subdomain

### Steps To Reproduce:
try to use Route::redirect inside a Route::domain group

**Comment by themsaid** [comment]
Please open a new issue and share the steps of reproduction with some code, the current issue doesn't have enough information to look into.
