### ISSUE TITLE
Mail::send fails if "to" is added with person's name, and "cc" is added without

### ISSUE THREAD

**Issue by mnpenner** [laravel/framework#22291]
- Laravel Version: v5.2.45
- PHP Version: 5.6.21
- Database Driver & Version: n/a

### Description:

The code I tried with looks like this:

```php
Mail::send('emails/customer_24hour', compact('booking', 'billing', 'is_email', 'show_billing'), function($m) use ($booking) {
    /** @var $m \Illuminate\Mail\Message */
    $m->to($booking->customer->email, $booking->customer->full_name);
    $m->from($booking->company->email ?: 'noreply@company.com', $booking->company->name);
    $m->subject("Booking Reminder #" . $booking->number);
    \MyCompany\Util::addCC($m, $booking->company, 'CUSTOMER');
});

public static function addCC(\Illuminate\Mail\Message $msg, Company $company, $type) {
    $cc = $company->getCcEmails($type);
    foreach($cc as $type => $addresses) {
        $method = strtolower($type);
        foreach($addresses as $add) {
            $msg->{$method}($add);
        }
    }
}
```

This was resulting in a `GuzzleHttp\Exception\ClientException`. 

> Client error response [url] https://api.mailgun.net/v3/redacted.com/messages.mime [status code] 400 [reason phrase] BAD REQUEST

I checked the response body to find:

```
array:1 [
  "message" => "'to' parameter is not a valid address. please check documentation"
]
```

And then checked the request which contained:

```
    -fields: array:1 [
      "to" => "REDACTED NAME <REDACTED@GMAIL.COM>,info@company.com"
    ]
```

As you can see from the "to" field and code, the customer's name is used, but the CC doesn't use a name. I guess Mailgun doesn't like it when you put one email address in `<brackets>` and the other not.

I can obviously fix this on my end by adding a name for both addresses, but I think `\Illuminate\Mail\Mailer` should sanitize the addresses so that they're all formatted the same way.

### Steps To Reproduce:

Simplified code from above:

```php
    Mail::send('some/template', [], function($m) {
        $m->to('customer@email.com', "Customer Name");
        $m->from("company@example.com", "Company name");
        $m->subject("Arbitrary subject");
        $m->cc("company@example.com"/*no 2nd arg causes mailgun to throw 400*/);
    });
```

You'll have to plug in your own email addresses and figure something out for the template.

**Comment by laurencei** [comment]
Can you firstly try and see if the problem exists on Laravel 5.5. v5.2 is really old now.

**Comment by laurencei** [comment]
Actually - reading your report a bit more - this seems like a problem with Mailgun and has nothing to do with Laravel.
