### ISSUE TITLE
Documentation DocBlock for CompilesConditionals Is Missing An Asterisk

### ISSUE THREAD

**Issue by ginnj-gilmore** [laravel/framework#22309]
- Laravel Version: master
- PHP Version: N/A
- Database Driver & Version: N/A

### Description:

The DocBlock for [ `Illuminate\View\Compilers\Concerns\CompilesConditionals::compileAuth()` ](https://github.com/laravel/framework/blob/master/src/Illuminate/View/Compilers/Concerns/CompilesConditionals.php#L20) is missing an asterisk at the beginning of the DocBlock. The [generated documentation](https://laravel.com/api/master/Illuminate/View/Compilers/Concerns/CompilesConditionals.html#method_compileAuth) does not contain the information related to the method `compileAuth()`.

### Steps To Reproduce:

N/A

**Comment by Dylan-DPC** [comment]
This seems trivial enough you can go ahead and PR it

**Comment by ginnj-gilmore** [comment]
Created the PR https://github.com/laravel/framework/pull/22311
