### ISSUE TITLE
[Proposal] Give the `all` property amiss in the `hasManyThrough` output and adding `hasOneThrough`, `belongsToThrough` and `belongsToManyThrough` aliases

### ISSUE THREAD

**Issue by khooz** [laravel/framework#22303]
This is just a proposal for better compliance of `hasManyThrough` with other relationship outputs and defining new aliases.

## Give the `all` property amiss in the `hasManyThrough` output 
The current output of `hasManyThrough` includes an `all` property which contains all returned records, eg.

```
    => App\Models\User {#806
         id: 1,
         name: "test0",
         email: "test0@example.com",
         status: 0,
         created_at: "2017-12-04 12:11:20",
         updated_at: "2017-12-04 12:11:20",
         deleted_at: null,
         state: Illuminate\Database\Eloquent\Collection {#809
           all: [
             App\Models\Generic\State {#821
               id: 1,
               district_id: null,
               name: "TestState",
               additional_data: null,
               status: 0,
               created_at: "2017-12-04 12:04:00",
               updated_at: "2017-12-04 12:04:00",
               deleted_at: null,
               state_id: 1,
             },
           ],
         },
       }
```

This particular property is not conforming the norm and the `state` in this case can be simply an array (or a Collection) of States.

## Adding `hasOneThrough`, `belongsToThrough` and `belongsToManyThrough` aliases
Also, since there is no (need for) `hasOneThrough` or `belongsToThough`, it also breaks the semantics of code and output. The above suggest the dropping of `all` property in output to fix this inconsistency; while this section proposes the addition of `hasOneThrough`, `belongsToThrough` and `belongsToManyThrough` aliases with shuffled parameter orders to comply the semantics.

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. This isn't a bug so you can open a proposal in the laravel/internals repo

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
