### ISSUE TITLE
Redis Cache many function with cache value is null, result have problems

### ISSUE THREAD

**Issue by microvnn** [laravel/framework#22305]
- Laravel Version: 5.4
- PHP Version: 7
- Database Driver & Version:

### Description:
Redis Cache problems
- Test : Cache::many([1,2,3,4,5,6]);
- Result: [1=>2,2=>3,3=>4,4=>5,5=>6,6=>null]
- Debug File : src/Illuminate/Cache/RedisStore.php   function many() => mget  => $results is  [1=>null,2=>null,3=>null,4=>null,5=>null,6=>null]
- Debug File : src/Illuminate/Cache/Repository.php   function many() => ... handleManyResult(...) ...  => 
I find codes : 
`if (is_null($value)) {
            $this->event(new CacheMissed($key));
            return isset($keys[$key]) ? value($keys[$key]) : null;
        }...`
So that final result is: [1=>2,2=>3,3=>4,4=>5,5=>6,6=>null].
Final result have problem. I think Final result must be [1=>null,2=>null,3=>null,4=>null,5=>null,6=>null] or [1=>false,2=>false,3=>false,4=>false,5=>false,6=>false]

**Comment by Dylan-DPC** [comment]
Laravel 5.4 is no longer supported. Can you reproduce the issue on 5.5 and try it?

**Comment by tillkruss** [comment]
We don't support storing null values in Redis.

**Comment by microvnn** [comment]
In case , I'm not put values in redis yet.

In file : src/Illuminate/Redis/Connections/PhpRedisConnection.php
`public function mget(array $keys)
 {
     return array_map(function ($value) {
         return $value !== false ? $value : null;    <= return null
     }, $this->client->mget($keys));
 }
`
