### ISSUE TITLE
Worker timeout has no effect when making cURL requests with no curl timeout

### ISSUE THREAD

**Issue by cristiangrama** [laravel/framework#22301]
- Laravel Version: 5.4.x
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7

### Description:
When a Job is making api calls using cURL (Guzzle 6 in this case), if cURL has not timeout set (CURLOPT_TIMEOUT) the worker's timeout will not have any effect.

I do have the `pcntl` extension installed.
```
vagrant@homestead:/vagrant/dev/apptest$ php -i | grep pcntl
pcntl
pcntl support => enabled
```

### Steps To Reproduce:
Have a job that makes api calls to an endpoint that will take longer to respond than the workers timeout. Also configure the client to not use a timeout. In this case I've commented the `timeout` for the guzzle client. When using the timeout everything will work fine since cURL will exit with an exception (cURL 28) and the worker will pick up the next job.
```
    public function handle()
    {
        $client = new \GuzzleHttp\Client([
// 'timeout' => 3
        ]);

        $client->get('127.0.0.1/sleep');
    }
```
and a route
```
$app->get('/sleep', function() {
   sleep(10);
});
```
and run the worker command with a timeout of 5
```
artisan queue:work --timeout=5
```

If the endpoint does not respond the worker will not timeout and will wait _forever_. If the endpoint decides to respond after a while but the worker timeout has passed, as soon as curl closes the connection due to the successful response, the worker detects that the timeout has passed and kills the script. So it looks like cURL is somehow interfering with the SIGALRM set by the worker but I have not clue on to how.

Video of the issue: http://screen.ac/1T2a2Z2J0I1Y

**Comment by pavinthan** [comment]
It's working as expected,  Use 0 to wait indefinitely (the default behavior) in `GuzzleHttp\Client`

**Comment by cristiangrama** [comment]
@pavinthan It's not working as expected. I've used 0 to wait indefinitely and the worker does NOT timeout and kill the script. Check this video http://screen.ac/1J0M181u2p0H

**Comment by pavinthan** [comment]
Please see [https://github.com/laravel/framework/issues/19584](https://github.com/laravel/framework/issues/19584)

**Comment by cristiangrama** [comment]
@pavinthan I've actually looked at that issue before creating this one. It's unrelated. I have installed `pcntl` and have `PHP 7.1`. Also the worker timeout works just fine when not using CURL. If I just sleep the job and have a timeout of 5 seconds on the worker the script will die after 5 seconds. The SIGALRM would work. The only time this does not work is when I have a curl request that takes longer than the worker timeout.

**Comment by laurencei** [comment]
Is it possible to update to Laravel 5.5 and see if the issue occurs there? There were some changes from memory between 5.4 and 5.5

**Comment by cristiangrama** [comment]
@laurencei Updated to Laravel 5.5 but the issue still there. It did not make any difference.

**Comment by arjasco** [comment]
This might be to do with cURL signal handling. Try `CURLOPT_NOSIGNAL` as an option maybe.

On the cURL documentation it says under `CURLOPT_TIMEOUT` -  This option may cause libcurl to use the SIGALRM signal to timeout system calls. It's indefinite by the default so possibly interfering with the worker?

**Comment by cristiangrama** [comment]
@arjasco When CURL does not have a timeout set Guzzle will automatically set the `CURLOPT_NOSIGNAL` https://github.com/guzzle/guzzle/blob/9e28b54996d260184abc9c36c59e2740be2184a4/src/Handler/CurlFactory.php#L400.

I've also thought that CURL might be setting it's own alarm which would cancel the previously set alarm. But that does not explain why after CURL alarm get's triggered, the worker alarm is still triggered as well. It feels that the worker alarm waits for the CURL alarm or whatever CURL does and only after that it will be able to trigger it's own alarm.

**Comment by arjasco** [comment]
@cristiangrama Thanks. By the looks the code in guzzle that option only gets set if you explicitly say timeout is 0 otherwise it's skipped by the isset check. $timeoutRequiresNoSignal would still be false by the time it gets to line 400.

Still sounds like it's cURL rather than Laravel in particular but a good point to raise.

**Comment by cristiangrama** [comment]
@arjasco I did try to leave timeout as not set and also to explicitly set it to `0`. The worker timeout did not work in both cases.

**Comment by laurencei** [comment]
> Still sounds like it's cURL rather than Laravel in particular but a good point to raise.

But shouldnt the worker superceeded anything/everything? i.e. if the worker process stalls, for *any* reason - we should be in control to kill it.

Relying on other code to behave seems to reduce the resilience of the worker timeout protections?

**Comment by sisve** [comment]
From the [RFC: Asynchronous Signal Handling](https://wiki.php.net/rfc/async_signals):

> Zend Engine in PHP 7.1 was extended with ability of safe time-out and interrupt handling. Actually, PHP VM checks for EG(vm_interrupt) flag on each loop iteration, user function entry or internal function exit, and call callback function if necessary.
> I propose to use this ability to implement asynchronous signal handling. Registered signal handlers are going to be called at some points during user script execution without any overhead.

This means that async signals will only execute on 1) loop iteration, 2) user function entry or 3) internal function exit. I'm unsure how sleep() works in this, but I presume it is abrupted by incoming signals (as sleeps often are) and the signal is then processed from the third type; internal function exit.

However, a external library that blocks on something wouldn't quality for any of these categories. The event is probably sent to the process, and is awaiting processing, but the handler isn't executing until the blocking code is done.

**Comment by arjasco** [comment]
So on that note, basically there isn't much that can be done here. I replicated the scenario a few days ago and had the same results. It would seem logical to also set a timeout on the cURL request if you want the worker to kill the job after a set amount of time anyway.

I wonder if it's worth being noted somewhere about this because I'm sure most people that use queues / background workers are probably forking other processes.

**Comment by mfn** [comment]
> I wonder if it's worth being noted somewhere about this because I'm sure most people that use queues / background workers are probably forking other processes.

IMHO it definitely is. I'm in the lucky position of having worked with background job systems for a long time to know that any kind of remote requests you make _absolutely need_ timeouts and the guzzle/curl one is "infinite" by default 💥

**Comment by maartenderie** [comment]
Can I re-open this issue? I found this in the docs, so I have to conclude that the behaviour described above is unintended.
![image](https://user-images.githubusercontent.com/19903985/74523033-a5f1fe80-4f1c-11ea-818f-4588b84d876c.png)
from; https://laravel.com/docs/5.8/queues#job-expirations-and-timeouts

**Comment by themsaid** [comment]
@maartenderie check https://divinglaravel.com/always-set-a-timeout-for-guzzle-requests-inside-a-queued-job

**Comment by maartenderie** [comment]
> @maartenderie check https://divinglaravel.com/always-set-a-timeout-for-guzzle-requests-inside-a-queued-job

Thank you for the clear article. I just wished the docs were clear on this. Are there other processes I should know of that survive the timeout? Maybe if the timeout can't be guaranteed it shouldn't be in there. Or called differently.
