### ISSUE TITLE
Cache::tag flush delete the tagkey

### ISSUE THREAD

**Issue by Except10n** [laravel/framework#22308]
- Laravel Version: 5.X
- PHP Version:
- Database Driver & Version:

### Description:
```
Cache::tags(['name'])->flush()

After execution, why keep “tagkey” ？
```

[https://github.com/laravel/framework/blob/5.5/src/Illuminate/Cache/RedisTaggedCache.php#L59](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Cache/RedisTaggedCache.php#L59)

[https://github.com/laravel/framework/blob/5.5/src/Illuminate/Cache/TagSet.php#L54](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Cache/TagSet.php#L54)

**Comment by sisve** [comment]
Why not?

**Comment by Except10n** [comment]
The tagkey is too much, and not cleaning it takes up a lot of memory

**Comment by sisve** [comment]
Can you clarify the "tagkey is too much" argument, and perhaps link to any documentation telling us how much memory is used by these keys?

Can you describe how we can reproduce the problem, including how we can see if the key is removed or not? We need this information to verify that any fix is complete.

If you know how to do it, send a PR with the code changes and tests.

**Comment by Except10n** [comment]
This is predictable, and each tagkey itself occupies 30+ bytes, which is permanently occupied and not cleared
My question is, why did laravel keep these tagkeys, and the data that they are associated with have been cleaned up by "flush()"

**Comment by sisve** [comment]
It's fully possible that the current implementation hasn't decided to keep them, but just didn't know that they could be removed. Can you send a PR with the changes needed for this?

**Comment by Except10n** [comment]
@deleugpn 

I don't quite understand what you mean in the pr
Can you solve this residual tagkey problem

**Comment by deleugpn** [comment]
If you want to flush everything, why are you using tags?

**Comment by Except10n** [comment]
I want to clear all of the data from a tag, including this tag's own tagkey taghash
```
Cache::tags(['tag1'])->putMany(['a' => 1, 'b' => 2], 10);
```
when i use flush() to clean the tag1
```
Cache::tags(['tag1'])->flush();
```
There will still be tagkey , like "prefix:tag:tag1:key" , It's useless, why keep the kv record ?

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.

**Comment by shehi** [comment]
@themsaid : aka STFU. Grand way of resolving questions!
