### ISSUE TITLE
When page expires, a misleading message is being displayed

### ISSUE THREAD

**Issue by neorganic** [laravel/framework#22315]
- Laravel Version: 5.5.#
- PHP Version: 7.1
- Database Driver & Version:

### Description:

The page has expired due to inactivity. 

Please refresh and try again.
![](https://i.imgur.com/NrGs87g.png)

I just feel that this is very misleading, because refreshing never helps - you just get the same message - you are stuck in an infinite loop for eternity.

### Steps To Reproduce:

Be a long time logged in an auth page and try to submit a form after that. (token expires)

**Comment by devcircus** [comment]
"Refresh and try again" is definitely the wrong suggestion in this case.

**Comment by laurencei** [comment]
What do you think is a better message?

Technically though if you reload the page, you no longer have a session - so your app should redirect them to the auth page?

**Comment by devcircus** [comment]
Not in this situation. For example, if you are on the login page and you submit the form after session expires, you get this message. Refreshing the page simply resends the POST login attempt, giving the same error ad infinitum. You have to actually submit a new GET request to the login page before you'll be able to login again.

**Comment by devcircus** [comment]
I've always just handled this at the app level so the message is never displayed, but can see how it can be confusing out-of-the-box.

**Comment by laurencei** [comment]
```diff
- Please refresh and try again.
+ Please revisit the page and try again.
```
?

**Comment by CupOfTea696** [comment]
Maybe Laravel could set a Cookie or store some session data, and then when the user refreshes, it redirects to the correct GET route?

**Comment by laurencei** [comment]
The whole problem is this page could be triggered by an expired session (and therefore not CSRF) - so that wont work.

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.

**Comment by devcircus** [comment]
I feel like it qualifies as a bug, to intentionally show a message to a user, which directs them to do something that can't possibly work. 
Seems like you could provide a "click here" link to the previous url and tweak the wording to say
> ... "try" refreshing the page or click here.
Or simply remove the misleading instruction altogether.

**Comment by laurencei** [comment]
You can set this in your app though.

The page is designed to be overriden by creating a file at: `app/resources/views/errors/419.blade.php`

So just make it whatever you want.

**Comment by devcircus** [comment]
Absolutely and that's why I've never ran across this issue. I handle this in a completely custom way. Just strange that the default suggestion doesn't work and may as well say "blink 3 times and cough". It'll accomplish the same thing.

However, no reason to continue the conversation. It definitely looks better than the previous default.

**Comment by neorganic** [comment]
@laurencei  Yeah, this  419.blade solves my issue - I can work from here easily . Of course it could be still a little bit more user friendly out of the box, but maybe this issue will have some impact for future changes regarding this "misleading feedback". Anyway, thanks for the great suggestion.
