### ISSUE TITLE
yarn-error.log present when creating a new Laravel project

### ISSUE THREAD

**Issue by dmfj** [laravel/framework#22318]
- Laravel Version: 5.5.23
- PHP Version: N/A
- Database Driver & Version: N/A

### Description:

The current zip archives (both `latest` and `latest-develop`) from Cabinet contain a `yarn-error.log` file ([yarn-error.log](https://github.com/laravel/framework/files/1533556/yarn-error.log)).

### Steps To Reproduce:

Run `laravel new laravel`

**Comment by devcircus** [comment]
I just ran ```laravel new project``` and didn't have a yarn-error.log. I also directly downloaded latest.zip and it did not contain a yarn-error.log. Maybe if it was an issue, it has been corrected?

**Comment by dmfj** [comment]
@devcircus Yup looks to have been fixed, thanks for the heads up. 👍 

(Closing now...)
