### ISSUE TITLE
path.public not being used when publishing assets from a package

### ISSUE THREAD

**Issue by vblinden** [laravel/framework#22329]
- Laravel Version: 5.5.23
- PHP Version: 7.0.22
- Database Driver & Version: MySQL v5.7.19

### Description:
Hello,

It seems that the `path.public` doesn't get loaded correctly when you `vendor:publich` from a service provider from a package. 

Am I overlooking something here or is this a bug?

Thanks.

### Steps To Reproduce:
I have installed a fresh copy of Laravel, and installed the [Voyager](https://github.com/the-control-group/voyager) package. I added the following code to change the public path of Laravel to the `AppServiceProvider.php` register method.

`$this->app->bind('path.public', function () { return base_path('public_html'); });`

I created a console command and a route where I `dd(public_path())` and they both returned the `public_html`. I also did this in the `VendorPublishCommand` class and it also returned the `public_html` path.

When I `dd(public_path())` in the following class: [VoyagerServiceProvider](https://github.com/the-control-group/voyager/blob/master/src/VoyagerServiceProvider.php#L230) it reverts back to `public`.

**Comment by srmklive** [comment]
The reason you are not seeing it is because Laravel isn't able to properly locate the `public_html` directory. That's why it is reverting back to `public` folder.

Try this, it may work though:

```
$this->app->bind('path.public', function () {
    return base_path().DIRECTORY_SEPARATOR.'public_html';
});
```

**Comment by vblinden** [comment]
I copied the exact code you posted, but it is still being placed in a newly created `public` folder.

**Comment by themsaid** [comment]
It depends on the order of providers registration, please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
