### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::getHasCompareKey()

### ISSUE THREAD

**Issue by sptdigital** [laravel/framework#22328]
- Laravel Version: 5.5.21
- PHP Version: 7.1.8
- Database Driver & Version: MySQL 5.6

### Description:
We have been receiving this error since v5.5.21 was released, any version prior to this works fine.

### Steps To Reproduce:
Use hasManyThrough relation using custom keys.

I suspect it might be as a result of [#22071](https://github.com/laravel/framework/pull/22071)

**Comment by Dylan-DPC** [comment]
Can you provide more details?

**Comment by sisve** [comment]
We would need at least a stack trace to debug this.

There's nothing in the linked PR that would cause this. getHasCompareKey was renamed to getExistenceCompareKey in Laravel 5.4.0. https://github.com/laravel/framework/commit/96fa470718120eb8569cc6068b265776fd7ebb46#diff-fac59ee2778e54567a539e9140a1a42cL1380

I don't see how your claim "any version prior to this works fine" could be true.

**Comment by themsaid** [comment]
Please provide a full stack trace.

**Comment by sptdigital** [comment]
It looks like the issue is actually with one of the packages we use, Marcelgwerder\ApiHandler. Thanks for your help everyone.
