### ISSUE TITLE
Call to undefined method Symfony\\Component\\HttpFoundation\\StreamedResponse::status()

### ISSUE THREAD

**Issue by navneetgarggate6** [laravel/framework#22323]
- Laravel Version: 5.2.45 
- PHP Version: 7.0.22-0ubuntu0.16.04.1
- Database Driver & Version:

### Description:
Trying to download csv using stream

$data = FacadeResponse::stream($callback);

Call to undefined method Symfony\\Component\\HttpFoundation\\StreamedResponse::status()

**Comment by Dylan-DPC** [comment]
5.2 is no longer supported. If you need help then seek the forums or the slack channels. If you want to report it as a bug, then reproduce the issue in a 5.5 clean project and mention the Steps To Reproduce.
