### ISSUE TITLE
MessageLogged Event needs log level, not just log name

### ISSUE THREAD

**Issue by ChangePlaces** [laravel/framework#22321]
- Laravel Version: 5.5

### Description:
When working with logs, it's typical to want to analyse the log level. This is impossible with the logged message event that only passes the log level name (e.g. 'error') instead of a numerical value as well, so simple logic like `if ($level >= \Monolog\Logger::ERROR)` can be performed. Also, regarding monolog, `$level` refers to the numerical value, and `$level_name` refers to the actual name attributed to it.

I think a log_level member should be added to the event for this reason.

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. This isn't a bug so you can open a proposal in the laravel/internals repo

**Comment by ChangePlaces** [comment]
Damn, I keep forgetting! Sorry! (Though on one hand it is kind of a bug because it doesn't allow you to work as expected)
