### ISSUE TITLE
Directive 'track_errors' is deprecated (PHP v7.2.0)

### ISSUE THREAD

**Issue by deathmagicmedia** [laravel/framework#22330]
- Laravel Version: 5.5.23
- PHP Version: 7.2.0
- Database Driver & Version: MariaDB (v10.2.11)
- OS: Windows 10 Pro (v10.0 build 16299)

### Description:
We are receiving the following errors when we used 'composer update':
- Deprecated: Directive 'track_errors' is deprecated in Unknown on line 0
- PHP Deprecated:  Directive 'track_errors' is deprecated in Unknown on line 0

### Steps To Reproduce:
1) Update PHP engine from v7.1.11 to v7.2.0.
2) Update Laravel from v5.5.22 to v5.5.23 using 'composer update'.
3) Errors will be shown in the command line.

Note: If PHP v7.2.0 is replaced with v7.1.12, then the error disappears.

**Comment by tillkruss** [comment]
Laravel does not use `track_errors`.

**Comment by sisve** [comment]
> Update Laravel from v5.5.22 to v5.5.23 using 'composer update'

That is basically a blind "upgrade every package I have"-command. It upgrades everything, not just laravel/framework. Use `composer update laravel/framework` to update a specific package, or `composer require laravel/framework:5.5.23` to grab a specific version.
