### ISSUE TITLE
PostgreSQL extensions behave erratically due to how Laravel sets PostgreSQL's "search_path"

### ISSUE THREAD

**Issue by cbj4074** [laravel/framework#22333]
- Laravel Version: 5.5.22
- PHP Version: 7.1.10
- Database Driver & Version: PostgreSQL 9.5.9

### Description

The author is of the opinion that Laravel manipulates PostgreSQL's `search_path` recklessly (though, with the best of intentions, I'm sure), given that it is possible to reference objects (e.g., tables) in other schemas in PostgreSQL.

For a primer regarding schemas, which are essentially "namespaces" (a concept that MySQL, for example, lacks), see:

https://www.postgresql.org/docs/current/static/ddl-schemas.html

The manipulation in question occurs at the following location in the Laravel Framework (Illuminate) source:

https://github.com/laravel/framework/blob/5.5/src/Illuminate/Database/Connectors/PostgresConnector.php#L95

The specific manner in which Extensions are implemented in PostgreSQL compounds the problem even further.

The manner in which Laravel manipulates the `search_path` has far-reaching implications for every aspect of the DBAL and ORM; anyone who understands Extensions in PostgreSQL can imagine what happens when Laravel paves-over the effective `search_path` any time it opens a new database Connection.

Imagine the following scenario:

The Laravel application uses a PostgreSQL database, in which `TEXT` data types are compared case-sensitively (this is PostgreSQL's default behavior).

A user registers with the application, using the email address `JDoe@example.com`.

To prevent a user's inability to authenticate using a variation in case, with respect to his email address, e.g., `jdoe@example.com`, the application developer makes use of PostgreSQL's case-**in**sensitive text comparison extension, `citext`.

For implementation details regarding extensions in PostgreSQL, see:

https://www.postgresql.org/docs/current/static/sql-createextension.html

The case for using `citext` instead of `LOWER()` on both sides of the comparison operator, for example, is articulated clearly in the following post:

https://hashrocket.com/blog/posts/working-with-email-addresses-in-postgresql

Now, imagine that the application developer is using more than one schema in the application (after all, this capability is one of PostgreSQL's strengths over MySQL, for example). Imagine further that the developer defines Eloquent Models whose relationships extend across schema boundaries; that is, relationships are defined between models whose respective connections specify different schemas.

In this scenario, Eloquent (and Query Builder, for that matter) break-down completely with respect to how they interact with any PostgreSQL extensions that may be in use on the database in question.

More specifically, in many cases, extensions are enabled on the default schema (usually `public`), and as long as `public` is in the `search_path`, the database connection is able to take advantage of those extensions, *regardless of the source and target objects' respective schema(s)* (see *Key Concepts*, below, for a more detailed explanation). This is important because if Laravel paves-over PostgreSQL's effective `search_path` when establishing any connection (which is the current behavior), the database will perform completely differently where extensions are concerned, e.g., case-insensitive text comparisons can become case-sensitive in crucial scenarios. Imagine the havoc this could wreak in certain use-cases.

To continue with the aforementioned email address example, imagine further that a second (and malicious) user registers with the application as `jdoe@example.com`. Because the `citext` extension is not effective, PostgreSQL will now treat the first and second users' email addresses as distinct. While the users would have distinct `id` values, there are a number of junctures at which this behavior could pose non-trivial problems (e.g., password resets, SSO implementations, etc.).

Yes, there are other fail-safes that should be employed to prevent this type of scenario (e.g., unique constraint), but not everybody is so shrewd. More than anything, my intention is to demonstrate that Laravel's current behavior can cause legitimate problems that are extremely difficult to debug.

### Key Concepts

1.) Crucially, just because the extension is enabled on a particular schema, it will **not** be used unless that schema is also in the effective `search_path`.

In other words, if the effective `search path` is, for example, `"$user", public`, the extension will **not** be used when processing this query:

    SELECT "email" FROM "platform"."users";

2.) Equally crucial is that an extension is "accessible" by virtue of existing ("being created") in the effective `search_path`. This means that an extension can be enabled on the `public` schema, but be used to effect change on a different schema. Consider the following scenario.

    $ sudo -H -u postgres /bin/sh -c "psql -d www -c 'CREATE EXTENSION IF NOT EXISTS citext;'"
    CREATE EXTENSION

We did not specify a schema in which to create the extension, explicitly, so the default schema, `public`, is used (I believe this default schema to be specified in `template1`, which ships with PostgreSQL).

And even though the `platform` schema is not in the effective `search_path`, we are able to use the extension against it (of course, this requires specifying the schema prefix when addressing the table):

    www=# SHOW search_path;
       search_path
    -----------------
     "$user", public
    (1 row)

    www=# ALTER TABLE "platform"."users" ALTER COLUMN "email" TYPE citext;
    ALTER TABLE

Likewise, we are able to execute queries that leverage the extension against schemas in which the extension does not exist:

    www=# SELECT "email" FROM "platform"."users" WHERE "email" = 'bjohnson@example.com';
               email
    ----------------------------
     BJOHNSON@example.com
    (1 row)

### Possible Solutions

1.) Do less; don't manipulate the `search_path` at all, and make it the developer's responsibility to set the value appropriately for his specific use-case, whether he decides to do that in PostgreSQL, or within his Laravel application.

2.) At the very minimum, Laravel should never overwrite the `search_path` completely, primarily because the `search_path` can be configured in the PostgreSQL configuration in a way that Laravel cannot replicate easily (if at all). If anything, Laravel should only *add* schemas to the `search_path`, as needed; it should never *remove* schemas (and again, that includes overwriting them). A more elegant approach might be to have two separate connection properties for `schema` and `search_path`. I haven't experimented with that approach as yet, but it seems to have merit, and may solve this problem entirely.

3.) While not ideal, it did occur to me to add every schema in my database to the `schema` value in the PostgreSQL connection configuration, e.g.

    'pgsql' => [
        'driver' => 'pgsql',
        'host' => env('DB_HOST', '127.0.0.1'),
        'port' => env('DB_PORT', '5432'),
        'database' => env('DB_DATABASE', 'forge'),
        'username' => env('DB_USERNAME', 'forge'),
        'password' => env('DB_PASSWORD', ''),
        'charset' => 'utf8',
        'prefix' => env('DB_PREFIX', ''),
        'schema' => 'public, mine', // <- This line
        'sslmode' => 'prefer',
    ],

but this is not a feasible solution for at least two reasons:

- Laravel seems to treat the "schema" and the "search_path" interchangeably, the implications of which are far-reaching and not obvious in most cases; these are two distinctly different concepts.

- Laravel employs parameter binding when it sets the `search_path` to the schema name, as part of the connection process:

    `$connection->prepare("set search_path to {$schema}")->execute();`

This causes the entire string to be quoted, which renders the `search_path` effectively invalid. For example, the `php artisan tinker` output demonstrates the problem:

    >>> DB::select('show search_path');
    => [
         {#734
           +"search_path": ""public, mine"",
         },
       ]

Furthermore, the binding precludes the use of dynamic values that PostgreSQL understands; a textbook example is the default `search_path` value: `"$user", public`, which PostgreSQL evaluates as `homestead, public`, for example.

### Conclusion

I'm fully aware that this problem affects a tiny fraction of Laravel users. I did ask myself:

> How many Laravel users use PostgreSQL? And of those, how many are using more than one schema? And of those, how many are using PostgreSQL extensions? And of those, how many are using them in more than one schema? And of those, how many are not using the default schema, `public`?

A back-of-the-napkin calculation yields about 1 in 1,000,000, which explains why nobody else seems to have documented nor addressed this limitation in Laravel's PostgreSQL implementation.

Nonetheless, it seems that if Laravel is to be regarded as "Enterprise-capable", this limitation must be addressed.

Thank you for your time and consideration.

**Comment by themsaid** [comment]
Moved to the internals repo: https://github.com/laravel/internals/issues/916
