### ISSUE TITLE
PHPUnit - Expected status code 200 but received 404.

### ISSUE THREAD

**Issue by YuK1Game** [laravel/framework#22338]
- Laravel Version: 5.4
- PHP Version: 7.0

### Description:
I use example test.
```php
class ExampleTest extends TestCase
{
    /**
     * A basic test example.
     *
     * @return void
     */
    public function testBasicTest()
    {
        $response = $this->get('/');

        $response->assertStatus(200);
    }
}
```

I do
```console
./vendor/bin/phpunit
```

Result
```console
PHPUnit 6.5.0 by Sebastian Bergmann and contributors.

F..                                                                 3 / 3 (100%)

Time: 88 ms, Memory: 10.00MB

There was 1 failure:

1) Tests\Feature\ExampleTest::testBasicTest
Expected status code 200 but received 404.
Failed asserting that false is true.

/path/to/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestResponse.php:78
/path/to/tests/Feature/ExampleTest.php:19
```

How is PHPUnit making a request, can I check the actual URL?

thank.

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by sisve** [comment]
Phpunit isn't making real http requests. It just issues "fake" requests to the router and to Laravel. So you need a route that matches / and returns a view for your example to work.

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.

**Comment by dakshhmehta** [comment]
We understand that this is not really an issue, but this is coming when default laravel installation is done.

I agree this should get fixed or at least help new devs like us.

**Comment by Dylan-DPC** [comment]
>  at least help new devs like us.

If you need help you can use the forums or our slack channel.

**Comment by dakshhmehta** [comment]
Thanks. We shall use the slack channel. 

However, I managed to fix the issue on this on my own by having php artisan serve running.
