### ISSUE TITLE
artisan list json: Add optional info to the option definition

### ISSUE THREAD

**Issue by TheColorRed** [laravel/framework#22348]
I have a [vscode extension](https://marketplace.visualstudio.com/items?itemName=ryannaddy.laravel-artisan) for laravel artisan, and one of the features to run a command requires that I get info about the commands, so I run `php artisan list --format=json`, to get the info.

Once the command is ran, it asks questions about options. Since there is nothing that says if the option is optional, I have no way of knowing if the option should be appended to the command or not, so all options (optional or not) are added to the command.

* Run the command `php artisan list --format=json`
* Under `commands[x].definition.options.y` there is nothing that says if the option is optional or not,

Here is an example of what might be nice, with an `"is_optional": true` property:

```json
{
  "commands": [
    {
      "definition": {
        "options": {
          "views": {
            "name": "--views",
            "is_optional": true,
            "shortcut": "",
            "accept_value": false,
            "is_value_required": false,
            "is_multiple": false,
            "description": "Only scaffold the authentication views",
            "default": false
          }
        }
      }
    }
  ]
}
```

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. This isn't a bug so you can open a proposal in the laravel/internals repo

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.

**Comment by TheColorRed** [comment]
Okay thanks. I have opened it there.
