### ISSUE TITLE
Try / catch not working for SQL transactions

### ISSUE THREAD

**Issue by mcblum** [laravel/framework#22349]
- Laravel Version: 5.4
- PHP Version: 7.1
- Database Driver & Version:
MySql 5.7

### Description:
When trying to catch a database error Laravel serves its own error page rather than using the specified catch block.

### Steps To Reproduce:
- Do a query that you know is going to fail like `orderBy('column_that_doesnt_exist')`
- Place that query inside a `try/catch` block
- Catch `\Exception` as well as `\Illuminate\Database\QueryException $e`

For me, Laravel always serves back its default error page rather than using my custom exception handling. It never gets to any of the catch blocks. 

Edit: further debugging (via log) shows that it is the QueryException that's being thrown, but for some reason, my `catch` isn't the one handling it.

**Comment by sisve** [comment]
This sounds like a syntax problem. Can you show your code that fails to catch it? A common problem is to forgetting to have the appropriate using-statement for the exception class.

**Comment by mcblum** [comment]
@sisve of course - here's what we are doing. At first I thought it was a namespace issue but I believe catching `\Exception` should take care of that:
```
if (request()->has('order_by')) {
            try {
                $column = request('order_by');
                if ($column[0] === '-') {
                    $column        = substr($column, 1);
                    $clonedBuilder = $clonedBuilder->orderByDesc($column);
                } else {
                    $clonedBuilder = $clonedBuilder->orderBy($column);
                }
            } catch (\Throwable $exception) {
                throw new InvalidPaginationException();
            } catch (\Illuminate\Database\QueryException $exception) {
                throw new InvalidPaginationException();
            } catch (\PDOException $exception) {
                throw new InvalidPaginationException();
            } catch (\Exception $exception) {
                throw new InvalidPaginationException();
            }
        }
```

**Comment by sisve** [comment]
You're only calling the builder at that point, which is okay. The builder doesn't know about your columns and won't throw any exceptions. It's the actual call to $clonedBuilder->get() that would throw the exception.

**Comment by mcblum** [comment]
@sisve damn it all, clearly I didn't make that connection. Thank you, I'll give it a shot right now!
