### ISSUE TITLE
FR: Password hashing in PHP 7.2 using Argon2

### ISSUE THREAD

**Issue by Jamesking56** [laravel/framework#22347]
Argon2 is a new password hashing algorithm added to PHP 7.2. It is more secure and faster than Bcrypt.

Is it possible to expose this functionality in Laravel? One way I believe this can be done with backward compatibility is to set which hashing algorithm to use using either a config value or env. Some Laravel apps will already have hashed passwords in the DB using Bcrypt.

**Comment by devcircus** [comment]
See https://github.com/laravel/framework/pull/21885

**Comment by rs-sliske** [comment]
Not against this being added, but I didnt think being "faster" was a good thing when it came to password hashing, surely that just means a brute force attack takes less time?

(A quick look into Argon and it seems the time is customizable by choosing how many iterations you want just like bcrypt can, just not sure password algorithm should be based on being fast)
