### ISSUE TITLE
How do set the my foreign key of morphTo

### ISSUE THREAD

**Issue by arunfung** [laravel/framework#22357]
- Laravel Version: laravel 5.4
- PHP Version:7.1
- Database Driver & Version: 5.7

### Description:
Polymorphic Relations
How do set the foreign key of morphTo

### Steps To Reproduce:
Source code
 /**
     * Define a polymorphic, inverse one-to-one or many relationship.
     *
     * @param  string  $name
     * @param  string  $type
     * @param  string  $id
     * @return \Illuminate\Database\Eloquent\Relations\MorphTo
     */

**Comment by sisve** [comment]
Laravel 5.4 is no longer supported. I would like to tell you to upgrade to 5.5, but it looks like you have a generic question. Try asking on the forums or in the chat instead since the github issues are for bug reports (for supported versions).
