### ISSUE TITLE
[Request] New Event BeforeMessageSending

### ISSUE THREAD

**Issue by Braunson** [laravel/framework#22368]
- Laravel Version: 5.5.24
- PHP Version: 7.1
- Database Driver & Version: MySQL

### Description:

Requesting an event that is fired before it's compiled into a SwiftMessage object. The event would be called when the Mailable has been fired. 

### Steps To Reproduce

N/A

### Use Case

A user has a column that is opt in/out of email for Canadian Anti-Spam Laws. Instead of checking on in every mailable class or extending the mailable base class an event fired before it compiles the email to a SwiftMessage object. 

It's required to be able to access the variable(s) that are passed to the custom mailable class.

This way when the event is fired, I can check if the `$user` object passed in the mailable has the column `opted_out` enabled and then stop the email from compiling/sending there and then.

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. This isn't a bug so you can open a proposal in the laravel/internals repo

**Comment by pavinthan** [comment]
@Braunson, you can add SwiftMailer plugin in Provider
```$this->app['mailer']->getSwiftMailer()->registerPlugin(new SomeClass());```
please close this issue.

**Comment by Braunson** [comment]
Thanks @Dylan-DPC, will post the proposal in laravel/internals.
