### ISSUE TITLE
Why not make 'Illuminate\ValidationValidator::getValue' become public method?

### ISSUE THREAD

**Issue by hbliang** [laravel/framework#22367]
Actually, when the user are signing up, I want to make sure the two passwords is identical after finish the validation via [After Validation Hook](https://laravel.com/docs/5.5/validation#after-validation-hook)

For example:
```php
Validator::make($request->all(), [
    'name' => 'required|string|max:255|unique:users',
    'email' => 'required|string|email|max:255|unique:users',
    'password' => 'required|string|confirmed|min:6',
    'password_confirmation' => 'required|confirmed|min:6',
])->after(function($validator) {
    if ($validator->getValue('password') !== $validator->getValue('password_confirmation')) {
        $validator->errors()->add('password_confirmation', 'The two passwords are different.');
    }
})->validate();
```

Unfortunately, it show me an exception `Method [getValue] does not exist.`. I found that the Method [getValue] is protected. So the questions are **why this method is protected instead of public?** and **is it possible to make this method become public in the future?**

Now, I implement my demand like this via passing the variable of request into the closure:
```php
Validator::make($request->all(), [
    'name' => 'required|string|max:255|unique:users',
    'email' => 'required|string|email|max:255|unique:users',
    'password' => 'required|string|confirmed|min:6',
    'password_confirmation' => 'required|confirmed|min:6',
])->after(function($validator) use ($request) {
    if ($request->get('password') !== $request->get('password_confirmation')) {
        $validator->errors()->add('password_confirmation', 'The two passwords are different.');
    }
})->validate();
```

Is there any better way to do?
Thanks a lot

**Comment by hbliang** [comment]
I am sorry. [rule-confirmed](https://laravel.com/docs/5.5/validation#rule-confirmed) is doing what I want to do.

**Comment by rs-sliske** [comment]
isnt this what the confirmed rule does?
