### ISSUE TITLE
[Request] Allow create() to accept eloquent objects / collections

### ISSUE THREAD

**Issue by bhartvigsen** [laravel/framework#22362]
Pretty simple, it came up while I was writing a script that automatically archives data into a table with an identical schema. It would be really cool if you could just take a single object or an eloquent collection and just dump it straight into create().

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. This isn't a bug so you can open a proposal in the laravel/internals repo

**Comment by laurencei** [comment]
FYI - you can already do `Model::create($collection->toArray())`
