### ISSUE TITLE
can make eloquent Observer lazy load?

### ISSUE THREAD

**Issue by junliuxian** [laravel/framework#22371]
- Laravel Version: 5.5.*
- PHP Version: 7.0.12
- Database Driver & Version: Mysql 5.6

### Description:
I want to use the events in Model, I chose to use observers.
I follow the documentation to register Observer in AppServiceProvider\boot.
When registering I found that the model will be instantiated, If I have multiple observers, this request does not need to use it.
This waste of resources I should ignore it or how to solve?
Can give me a direction? 
Thanks!

### Steps To Reproduce:

- observer
```
namespace App\Observers;
use App\Models\Link;

class LinkObserver {

    public function deleted(Link $link){

        if(!empty($link->logo))
            @unlink($link->logo);
    }
}
```

- model

```
namespace App\Models;
use Illuminate\Database\Eloquent\Model;

class Link extends Model
{
}
```

- controller

```
namespace App\Http\Controllers;
use Laravel\Lumen\Routing\Controller;
use App\Models\Link;

class LinkController extends Controller {
    
    protected $model;

    public funtion __construct(Link $model)
    {
        $this->model = $model;
    }

    public function destroy($ids)
    {
        $this->model->destroy(explode(',', $ids));
        return response('', 204);
    }
}
```

- AppServiceProvider

```
namespace App\Providers;
use App\Models\Link;
use App\Observers\LinkObserver;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    public function boot(){
        Link::observe(LinkObserver::class);
        // If I have multiple observers ...
      // But for some requests I do not use it
    }
}
```

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this github area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I please suggestion closing your issue ticket here. Instead trying asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.
