### ISSUE TITLE
SqsQueue Error: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by Brenneisen** [laravel/framework#22373]
- Laravel Version: 5.5.24
- PHP Version: 7.2
- Database Driver & Version: MySQL 5.7.17
- AWS-SDK: 3.45.2

### Description:

count(): Parameter must be an array or an object that implements Countable {"exception":"[object] (ErrorException(code: 0): count(): Parameter must be an array or an object that implements Countable

### Steps To Reproduce:

If the worker fetch 0 jobs from a sqs queue

`$response = $this->sqs->receiveMessage([
            'QueueUrl' => $queue = $this->getQueue($queue),
            'AttributeNames' => ['ApproximateReceiveCount'],
        ]);`

will return null. Than `if (count($response['Messages']) > 0)` will produce this error.

**Comment by Dylan-DPC** [comment]
Related to: https://github.com/laravel/framework/issues/20248

**Comment by laurencei** [comment]
I've done a fix in the PR above. You can close the issue here and any further discussion can be there.

**Comment by Dylan-DPC** [comment]
I think it is better to wait for the PR to be merged to close the issue.
