### ISSUE TITLE
A little suggestion

### ISSUE THREAD

**Issue by junliuxian** [laravel/framework#22381]
- Laravel Version: 5.5.*
- PHP Version: 7.0.12
- Database Driver & Version: Mysql 5.6

### Description:

laravel can not cancel verification，bail is only for a single field. If there is a field does not pass validation to jump out of verification.  

phalcon has such ability. see [https://docs.phalconphp.com/en/3.2/validation#cancelling](https://docs.phalconphp.com/en/3.2/validation#cancelling)

If you change the source code, laraval bail can also complete the above work

```
//  file: Illuminate\Validation\Validator;
// Change the place in 16 lines
public function passes()
    {
        $this->messages = new MessageBag;

        // We'll spin through each rule, validating the attributes attached to that
        // rule. Any error messages will be added to the containers with each of
        // the other error messages, returning true if we don't have messages.
        foreach ($this->rules as $attribute => $rules) {
            $attribute = str_replace('\.', '->', $attribute);

            foreach ($rules as $rule) {
                $this->validateAttribute($attribute, $rule);

                if ($this->shouldStopValidating($attribute)) {
                    break 2; // Change here
                }
            }
        }

        // Here we will spin through all of the "after" hooks on this validator and
        // fire them off. This gives the callbacks a chance to perform all kinds
        // of other validation that needs to get wrapped up in this operation.
        foreach ($this->after as $after) {
            call_user_func($after);
        }

        return $this->messages->isEmpty();
    }
```

Or use other better ways

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. This isn't a bug so you can open a proposal in the laravel/internals repo

**Comment by srmklive** [comment]
Not a bug. You can open a PR for adding this feature though.

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. As per the contribution guide, the correct place for this is https://github.com/laravel/internals/issues.
