### ISSUE TITLE
[Eloquent] 'create' method returns instance with wrong id

### ISSUE THREAD

**Issue by mputkowski** [laravel/framework#22388]
- Laravel Version: 5.5.25
- PHP Version: 7.0
- Database Driver & Version: MySQL 5.7.19

### Description:
`create` method should return saved model instance. If `id` column doesn't have `auto_increment` attribute (only primary key) and `id` value is set using `create` method, returned instance has `id` set to 0 (in DB value is correct). Tested on my project and fresh install.

### Steps To Reproduce:

- create table without `auto_increment` attribute on `id` (e.g. `$table->integer('id')->primary()`)
- create model (`id` must be fillable)
- use `create` method to insert data and check `id` of returned instance
- compare `id` with record in DB

Example code
```php
$id = rand(1, 50);

$var1 = \App\Test::create([
    'id' => $id
]);

$var2 = \App\Test::find($id);

dd([$var1->id, $var2->id]);
```

**Comment by 36864** [comment]
From the docs: https://laravel.com/docs/5.5/eloquent#eloquent-model-conventions
>In addition, Eloquent assumes that the primary key is an incrementing integer value, which means that by default the primary key will be cast to an int automatically. If you wish to use a non-incrementing or a non-numeric primary key you must set the public $incrementing property on your model to false. If your primary key is not an integer, you should set the protected $keyType property on your model to string.

Sounds like you forgot to set the `$incrementing` property.
In the future please read the documentation before filing a bug report.

**Comment by mputkowski** [comment]
@36864 It's working, I didn't see that. Thanks.

**Comment by Serhioromano** [comment]
I cannot get it. Why it creates with a different ID. For instance, I recreate DB, then I add a user it is created with ID 1 but IC 17 is returned by eloquent, And I have a primary key name `id`.
