### ISSUE TITLE
[5.5] Route pattern method doesn't handles regexes properly

### ISSUE THREAD

**Issue by driesvints** [laravel/framework#22387]
- Laravel Version: 5.5.22
- PHP Version: PHP 7.1.1
- Database Driver & Version: N/A

### Description:

The pattern matcher method for global route constraints, [as described here](https://laravel.com/docs/5.5/routing#parameters-regular-expression-constraints), doesn't handles every regex properly. For example, the regex from the example below to validate a proper UUID v4 (which can also be a route parameter) isn't being validated properly. The validation behind the `pattern` method is done by the `Str::is` method. See the example in steps to reproduce to reproduce.

Regex for UUID v4:

`/[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12}/i`

Valid UUID v4:

`5d8977f1-8809-47b0-a01d-492373fd81c6`

### Steps To Reproduce:

https://3v4l.org/QXph1

**Comment by arjasco** [comment]
Pretty sure `Str::is` isn't used in route matching. preg_quote within wouldn't allow this to work i believe.

Your regex works fine, use it without the forward slashes and flags.

```php
Route::get('/{id}', function ($id) {
    return 'UUID: ' . $id;
})->where('id', '[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12}');
```

```php
Route::pattern('id', '[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12}');
```

Both working as expected.

**Comment by driesvints** [comment]
@arjasco hmm no they don't on my end:

```
>>> str_is('[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12}', '5d8977f1-8809-47b0-a01d-492373fd81c6')
=> false
```

What version of Laravel are you running?

**Comment by arjasco** [comment]
I believe `Str::is` is not used for that case see here - https://laravel.com/docs/5.5/helpers#method-str-is

The `preg_quote` function within the implementation would escape the pattern.

Might be wrong but i think route matching is the responsibility of the Symfony Route component.

**Comment by driesvints** [comment]
@arjasco hmm, you're right I believe. No idea why I thought it was used for it. Think I was confused with the route naming matching (it's used there and also uses the word patterns).

But unfortunately the problem still happens. 

`Route::pattern('id', '[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12}');`

This doesn't let's the value `5d8977f1-8809-47b0-a01d-492373fd81c6` pass (while it should).

**Comment by themsaid** [comment]
This works for me:

```
Route::get('/{id}', function ($id) {
    return 'UUID: ' . $id;
})->where('id', '[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12}');
```

Heading to `http://laravelcurrent.dev/5d8977f1-8809-47b0-a01d-492373fd81c6` it parses it correctly.

**Comment by driesvints** [comment]
I noticed that it doesn't work when you append flags to the regex.

`/[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12}/i` won't work.

`[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12}` does but then it doesn't take the flags into account.

**Comment by driesvints** [comment]
This indeed seems to be a limitation for Symfony's Router since it does all the regex checks. So I'll close this off here.
