### ISSUE TITLE
Calling release on a queued SQS job with no delay ignores the default visibility timeout set on the queue

### ISSUE THREAD

**Issue by tomhughes-invento** [laravel/framework#22397]
- Laravel Version: 5.4.36
- PHP Version: 7.1.7-1
- Database Driver & Version: N/A

### Description:
Releasing a processing job back to an SQS queue without a delay value currently always sends the delay value up as 0, which causes a released job to ignore the default visibility timeout set on the queue.

```php
public function release($delay = 0)
{
    parent::release($delay);

    $this->sqs->changeMessageVisibility([
        'QueueUrl' => $this->queue,
        'ReceiptHandle' => $this->job['ReceiptHandle'],
        'VisibilityTimeout' => $delay,
    ]);
}
```

If this is the intended functionality for releasing back to SQS queues the docs should really make this clear as I spent the better part of a day trawling through google assuming it may be SQS at fault, otherwise as far as I can tell if you do not send up the VisibilityTimeout key when no delay argument is provided it seems like the job abides by the queue's default visibility timeout.

### Steps To Reproduce:
1) Set up an SQS queue with a default timeout (Amazon will set it to 30 seconds by default).
2) Set up a job that calls `$this->release()` in its handle method.
3) Fire the job
4) run queue:listen to start processing the job, which will ignore the timeout set on the queue and immediately pick the job back to and process it

**Comment by Dylan-DPC** [comment]
5.4 is no longer supported. Can you test if this occurs on 5.5?

**Comment by tomhughes-invento** [comment]
The method is the same on the 5.5 branch as well as 5.4

**Comment by laurencei** [comment]
> run queue:listen to start processing the job, which will ignore the timeout set on the queue and immediately pick the job back to and process it

The `timeout` is not how long to wait before trying again - it is the maximum time to allow a job to try.

So it is correct behavior as currently designed, unless I am misunderstanding something...?

**Comment by tomhughes-invento** [comment]
Sorry, I meant the default visibility timeout that is set on the SQS queue. Without passing a numeric value into `$this->release()` it releases the job straight into the available section of the queue, allowing it to immediately be picked back up ahead of all other jobs waiting, whereas my understanding of the default visibility timeout option on SQS queues was that this was always the minimum time a job must wait before being allowed to be ran again by workers.

I may well just not have gotten the point of release, and it is the intended functionality that the value you pass into release (i.e. `$this->release(60)`) overrides the default time that the queue may have set, but if that is the case IMO it's worth while to warn people setting up SQS queues with Laravel that this is the case.

**Comment by themsaid** [comment]
Feel free to send a PR to laravel/docs, this behaviour is intended and can't be changed at a point release, if you really think it should read the default value I suggest that you open the issue at laravel/internals for discussion.
