### ISSUE TITLE
Queues: job failed not providing exception

### ISSUE THREAD

**Issue by thejurassic** [laravel/framework#22398]
- Laravel Version: 5.5.24
- PHP Version: 7.1.11

### Description:
Laravel Doc says: 

> "You may define a failed method directly on your job class, allowing you to perform job specific clean-up when a failure occurs. The Exception that caused the job to fail will be passed to the  failed method"

Only to find that the exception isnt passed to the failed method.  This will cause the failed job method to  fail.  The exception parameter is set to null in Illuminate\Queue\FailingJob.php line 19.  Remove this and failed method works as described in Documentation

### Steps To Reproduce:

```
line 19 in  Illuminate\Queue\FailingJob.php:
    public static function handle($connectionName, $job, $e = null)
My custom job class
   public function failed(Exception $e){  //fails }
```
-----------------------------
However, change FailingJob.php line 19 to: 
```
public static function handle($connectionName, $job, $e)
My custom job class
  public function failed(Exception $e){  echo e->getMessage() . "WORKS" }
```

**Comment by sisve** [comment]
I have no idea how to follow these steps to reproduce the problem. Am I supposed to do something on line 19 in FailingJob.php? Couldn't you just show us an entire (even if empty) Job that fails? Enough information for us to copy/paste it to reproduce it?

**Comment by Dylan-DPC** [comment]
> The exception parameter is set to null in Illuminate\Queue\FailingJob.php line 19. Remove this and failed method works as described in Documentation

It doesn't set it to null. That is a default parameter which will set `$e` to null if it isn't passed from the caller method. If it wasn't passed from the caller, then your fix doesn't make any difference to the method.
