### ISSUE TITLE
/css route not found

### ISSUE THREAD

**Issue by marin246** [laravel/framework#22393]
- Laravel Version: 5.5.24
- PHP Version: 7.1
- Using Valet

### Description:
For some reason, the path /css can't be found by nginx and a 404 error is shown.

### Steps To Reproduce:
in routes/web.php:
`Route::view('/css', 'css');`
with a corresponding view file css.blade.php.
In contrast,
`Route::view('something/css', 'css');`
works.

**Comment by sisve** [comment]
Do you happen to have a /public/css folder? Your web server will probably prioritize static folders and files before sending requests to Laravel's routing system.

**Comment by marin246** [comment]
ah, of course, that is it, thanks!
