### ISSUE TITLE
->withoutOverlapping(); problem at 5.4

### ISSUE THREAD

**Issue by iggori** [laravel/framework#22406]
- Laravel Version: 5.4.?
- PHP Version:7.0
- Database Driver & Version: not relevant

### Description:
I have Cron that works ->hourlyAt(15) ->withoutOverlapping();
It happens that job is interrupted probably due deployments and that job stays locked forever so it's not executing. I kill that instance on aws and boot another one, still, only that job is not executing.
framework/cache is empty so I believe that there is some Memcached key that keeps information about nonfinished commands. (I use shared memcache across multiple instances) 
In same time other commands from kernel executing without a problem. Please tell me where is info about locked jobs by ->withoutOverlapping() so I can kill them via deployment script.
Thank you.

### Steps To Reproduce:
I wish I know.

**Comment by Dylan-DPC** [comment]
If you can't tell us how to reproduce the issue then we can't confirm if this is a bug or not. If you need help you can ask in the forums or the slack channel

**Comment by themsaid** [comment]
5.4 isn't supported anymore, please upgrade to 5.5
