### ISSUE TITLE
In Illuminate\Mail\Mailer::send callback is ignored if first parameter is instance of MailableContract

### ISSUE THREAD

**Issue by kikkauz** [laravel/framework#22404]
- Laravel Version: 5.0
- PHP Version: 7.x
- Database Driver & Version:

### Description:
According to its contract, the method
Illuminate\Mail\Mailer::send accept
string|array|MailableContract
array  $data
\Closure|string  $callback

however, when an instance of MailableContract is passed as first argument, the other two parameters are ignored as the first thing the method does is

        if ($view instanceof MailableContract) {            
            return $this->sendMailable($view);
        }
As Mailable has a public array $callbacks it should be enough to add the closure to this array before returning.
Something like (not correct as $callbacks are in mailable and not MailbleContract...)

if ($view instanceof MailableContract) {
            $view->withSwiftMessage($callback);
            return $this->sendMailable($view);
        }

**Comment by themsaid** [comment]
Please upgrade your laravel installation to 5.5, 5.0 is not supported anymore.

**Comment by kikkauz** [comment]
My fault, I am using 5.5 and the bug is in 5.5(well maybe it’s in 5.0) as well.

**Comment by kikkauz** [comment]
Will you reopen it or should i open a new issue?
