### ISSUE TITLE
PASSWORD_ARGON2I algorithm for password_hash and password_needs_rehash

### ISSUE THREAD

**Issue by chamav** [laravel/framework#22400]
- Laravel Version: 5.5.25
- PHP Version: 7.2.0
- Database Driver & Version:

### Description:
Please add a choice of hashing algorithm for password_hash and password_needs_rehash functions.
In php 7.2 added PASSWORD_ARGON2I algorithm.
\Illuminate\Hashing\BcryptHasher::make
\Illuminate\Hashing\BcryptHasher::needsRehash

**Comment by Dylan-DPC** [comment]
Argon has been integrated in 5.6 to avoid any possible breaking changes. You can look at https://github.com/laravel/framework/pull/21885. Also this repo is for bug tracking, so if you have any proposals you can create an issue in laravel/internals repo.

**Comment by chamav** [comment]
Ok. Thank you for your answer. We will wait for the release laravel 5.6.
