### ISSUE TITLE
[Mailable] queued cannot be deleted or failed using InteractsWithQueue

### ISSUE THREAD

**Issue by larsbo** [laravel/framework#22411]
- Laravel Version: 5.4.36
- PHP Version: 7.1.3
- Database Driver & Version: MySql 5.5.39

### Description:
A queued Mailable is not working with `InteractsWithQueue` correctly, running `$this->fail()` or `$this->delete()` just increases the attempts counter but did not move the job to the failed jobs table or delete it completely.

### Steps To Reproduce:
* Make A Mailable that implements `ShouldQueue` and uses `InteractsWithQueue`.
* Inside the `build()` method add `$this->fail()` or `$this->delete()`.
* Dispatch a new Mailable instance to the queue.
* run `php artisan queue:work`.
* The attempts counters of the job runs until 255 and stop increasing than instead of deleting the job.

**Comment by themsaid** [comment]
Please upgrade to 5.5, 5.4 is not supported anymore.
