### ISSUE TITLE
"Psr-http-message-bridge" package was not required?

### ISSUE THREAD

**Issue by emanci** [laravel/framework#22423]
- Laravel Version: 5.5.22
- PHP Version:
- Database Driver & Version: 

### Description:
This is not a problem encountered in use, but to see the code is by accident, using the package "Psr-http-message-bridge" but not required.

### Steps To Reproduce:
The file path is `/usr/local/var/www/laravel_pro/vendor/laravel/framework/src/Illuminate/Routing/Router.php`

```
public static function toResponse($request, $response)
    {
        if ($response instanceof Responsable) {
            $response = $response->toResponse($request);
        }

        if ($response instanceof PsrResponseInterface) {
            $response = (new HttpFoundationFactory)->createResponse($response);
        } elseif (! $response instanceof SymfonyResponse &&
                   ($response instanceof Arrayable ||
                    $response instanceof Jsonable ||
                    $response instanceof ArrayObject ||
                    $response instanceof JsonSerializable ||
                    is_array($response))) {
            $response = new JsonResponse($response);
        } elseif (! $response instanceof SymfonyResponse) {
            $response = new Response($response);
        }

        if ($response->getStatusCode() === Response::HTTP_NOT_MODIFIED) {
            $response->setNotModified();
        }

        return $response->prepare($request);
    }
```

`$response = (new HttpFoundationFactory)->createResponse($response);`

The class `HttpFoundationFactory` belongs to `Psr-http-message-bridge` this package, but not required.

thanks!

**Comment by devcircus** [comment]
According to the [documentation](https://laravel.com/docs/5.5/requests#psr7-requests), if you would like to use the psr7 standard for requests/responses...

> you will first need to install a few libraries. Laravel uses the Symfony HTTP Message Bridge component to convert typical Laravel requests and responses into PSR-7 compatible implementations:

```
composer require symfony/psr-http-message-bridge
composer require zendframework/zend-diactoros
``` 

so if you are indeed using the psr7 requests/responses, the appropriate libraries will be installed when needed.

**Comment by GrahamCampbell** [comment]
Composer will also tell you this when you run it. Look at the suggested package output.

**Comment by emanci** [comment]
thanks
