### ISSUE TITLE
assertExactJson() does not parse response correctly

### ISSUE THREAD

**Issue by rossjcooper** [laravel/framework#22431]
- Laravel Version: 5.5.25
- PHP Version: 7.1.4
- Database Driver & Version: MySQL 5.6.35

**Description:**
Running a JSON test with `assertExactJson()` does not pass as the response it produces is not accurate to what it expects or even to what the actual endpoint would return when tested via real HTTP via Postman.

The main problem being is that the response in the test turns all values into strings even though what it expects and returns via HTTP might be the actual data type from the database/model, for example:

Test response:
`{"user_id" : "1", "completed": "1"}`

Actual HTTP response/ what the assertion expects:
`{"user_id" : 1, "completed": true}`

**Steps To Reproduce:**
I have put together a quick demo app which you can clone and run phpunit on to see the issue happening. It is not just this project but a couple I have worked on now.
[https://github.com/rossjcooper/laravel-demo](https://github.com/rossjcooper/laravel-demo)

A [similar issue](https://github.com/laravel/framework/issues/9735) was raised a while ago and in my opinion quite rudely dismissed so hopefully with this example it may get a better response.

**Comment by rossjcooper** [comment]
That sounds correct @priidikvaikla thanks I'll give it a try and let you know.

**Comment by priidikvaikla** [comment]
It that fixed your problem, please also close this issue.
