### ISSUE TITLE
Laravel session store does not call open/close

### ISSUE THREAD

**Issue by SimplyCorey** [laravel/framework#22430]
- Laravel Version: 5.5.25
- PHP Version: 7.1.12

### Description:
Laravel doesn't call the open / closed in the session store 

https://github.com/laravel/framework/blob/5.5/src/Illuminate/Session/Store.php

This is causing issues with outside session drivers that except the open/close methods to be used.  One example currently is the MongoDBSessionHandlier from Symfony.  They have logic within the open method that stores the $sessionName.  If open isn't called, an exception is thrown when destroy is called.

In the discussion below, it is believed to be a caller issue as the PHP default file handler always uses open/close.

### Steps To Reproduce:

See: https://github.com/symfony/symfony/issues/25445

**Comment by laurencei** [comment]
How are you using the Mongo session handler in Laravel?

The problem is it is a change in upstream behavior from Symfony. Laravel uses all its own drivers now, so it doesnt directly affect Laravel anymore, except unless the framework wants to allow for other drivers by Symfony...

**Comment by SimplyCorey** [comment]
I am using Mongo with a custom driver I wrote that passes off the Symfony MongoDBHander to the driver manager in Laravel -- it was based partly on the laravel-monogodb-session package.  The issue, is that Laravel doesn't currently follow how PHP suggests a session should be handled.

`The callbacks specified in session_set_save_handler() are methods called by PHP during the life-cycle of a session: open, read, write and close and for the housekeeping tasks: destroy for deleting a session and gc for periodic garbage collection.`

http://php.net/session.customhandler

Open/Close are not currently being called and this can affect an external session driver.  I'm not sure if supporting these is desirable by Laravel as their implementation is custom.  Currently, it can lead to unexpected behavior for anyone who is writing a custom driver that excepts the session handier to behave like the PHP core one.

While I agree that Symfony committed a backwards breaking change (and should fix it) -- I think the issue lays deeper here if Laravel wants to support the way core PHP does sessions.  (Im not sure they do)

**Comment by sisve** [comment]
Do we really support the Symfony session stuff? I thought we had our own and the Symfony sessions are not used or supported.

> The reason the changes only seems to affect the NullSessionDriver is because Laravel actually uses its own implementations of every other driver, and was only using the Symfony Null driver.
>
> So this PR just creates our own Null driver, and we no longer rely on Symfony for it.

From https://github.com/laravel/framework/pull/22314

**Comment by laurencei** [comment]
It's not the "Symfony session stuff" - its the `SessionHandlerInterface` which is defined in PHP.

Symfony has changed the way it implements the interface - and made it follow the expected flow of the interface (i.e. that `open()` is always called first). That is what lead to the Null Session driver issue.

So it's really a design decision for Taylor if he wants Laravel to also follow the interface principle more strictly, or if Laravel continues along as it has done.

**Comment by FlorianWeigang** [comment]
Hey,

just i have a similar issue and maybe its related: 
Iam using Laravel v5.5.26 with sessions in files. When i call `session()->put('foo', 'bar)`; its added onto the session array stack but its not persisted. I need to call `session()->save()` so that its persisted until the next call. Is this intended? I remember in older versions that it was saved automatically?

Thanks, Flo

**Comment by sisve** [comment]
@FlorianWeigang The most common scenario is that you have a dd() or die() that terminates the request early. The session middleware persists the changes very late in the request lifecycle, after the views are rendered and sent back to the client.

**Comment by FlorianWeigang** [comment]
@sisve thank you very much! its working now..
