### ISSUE TITLE
[Feature Request] Collection isFirst() / isLast()

### ISSUE THREAD

**Issue by nathanh0** [laravel/framework#22432]
- Laravel Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
When iterating a collection it would be nice to be able to say:   

foreach( $collection as $item )
{
    if ( $item->isFirst() ) {
        // Is First Item
    }
    if ( $item->isLast() ) {
        // Is Last Item
    }
}

### Steps To Reproduce:

It's not a bug, hopefully I put this in the right section. Sorry if I didn't.

**Comment by decadence** [comment]
laravel/internals repo is for this kind of issue

**Comment by mfn** [comment]
Also I don't believe `$item->is…()` can work as the items itself are generic values of any kind.

So it's more like `$collection->isFirst($item)` but that won't do good if you've duplicates.

(Unless I'm missing something here)

**Comment by GrahamCampbell** [comment]
> laravel/internals repo is for this kind of issue

Yes please. :)
