### ISSUE TITLE
route dispatch to different controller problem

### ISSUE THREAD

**Issue by MissMyCat** [laravel/framework#22436]
- Laravel Version: 5.4.2
- PHP Version:5.6.30
- Database Driver & Version:
 MySQL 5.6.24
### Description:
I want to dispatch request to different action in two controllers by query param in url
for example:
request 1: 
` /path/action_name?type=1` 
redirect to 'a controller @function a'
request 2: 
`/path/action_name?type=2`
redirect to 'b controller @function b'

I have tried to use `route()` and `action()` method, BUT these functions need I expose two more routes.

I just want to expose **only one route** name maybe like:
```
$router->get('/path/action_name', function () {
    //but I do not know how to call DIFFERENT CONTROLLER without register in Route
});
```

**Comment by sisve** [comment]
Your action could just read the `$request->input('type')` and call one of the other actions (`functionA` and `functionB`).

    public function myAction(Request $request) {
        if ($request->input('type') == 1) {
        	return $this->functionA();
        } else {
        	return $this->functionB();
        }
    }

    private function functionA() {
    	// ...
    }

    private function functionB() {
    	// ...
    }

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
