### ISSUE TITLE
On-Demand Notifications do not work with a Queue

### ISSUE THREAD

**Issue by f00bar** [laravel/framework#22445]
- Laravel Version: 5.5.25
- PHP Version: PHP 7.1.11 (cli) (built: Nov  1 2017 19:28:11) ( NTS )
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.7.17, for osx10.12 (x86_64)

### Description:
Using "On-Demand Notifications" to send an email using a Queue throws an error.

[2017-12-15 21:20:18] local.ERROR: Trying to get property of non-object {"exception":"[object] (ErrorException(code: 0): Trying to get property of non-object at /app/Notifications/InvoiceSent.php:56)

### Steps To Reproduce:
1. Create a notification (InvoiceSent) that implements ShouldQueue and add a mail delivery channel
2. From a controller call:
Notification::route('mail', 'name@email.com')->notify(new InvoiceSent($invoice));

Invoice model and notification are using 'SerializesModels'

Note that if I remove ShouldQueue from the notification, the email goes through.

**Comment by oriceon** [comment]
Confirm the issue

**Comment by themsaid** [comment]
We can't see what's in `/app/Notifications/InvoiceSent.php:56` why do you think it's a laravel issue? It seems like something wrong in your code.

**Comment by f00bar** [comment]
For some reason I always get this in my error log - line 56 - regardless of what's actually on that line in the notification file. I understand that's weird but that's what I'm experiencing.

The reason I think it's a laravel issue is because like I mentioned if I remove ShouldQueue from my notification class - the email goes through. 

It's actually very easy to recreate the issue - if anyone can send an 'on demand' email via a Queue - I will close the issue and look further in my code but I spent a few hours and I can't quite figure out what's going on. It looks like a serialization issue to me but I can't get it to work.

This is what I see in my failed_jobs table for job payload:

{"type":"notification","timeout":null,"tags":["App\\Invoice:1"],"id":"132","data":{"command":"O:48:\"Illuminate\\Notifications\\SendQueuedNotifications\":9:{s:11:\"notifiables\";O:44:\"Illuminate\\Notifications\\AnonymousNotifiable\":1:{s:6:\"routes\";a:1:{s:4:\"mail\";s:17:\"mmateev@gmail.com\";}}s:12:\"notification\";O:29:\"App\\Notifications\\InvoiceSent\":9:{s:7:\"invoice\";O:45:\"Illuminate\\Contracts\\Database\\ModelIdentifier\":3:{s:5:\"class\";s:11:\"App\\Invoice\";s:2:\"id\";i:1;s:10:\"connection\";s:5:\"mysql\";}s:5:\"tries\";i:3;s:2:\"id\";s:36:\"407f39a8-07c0-4146-a5c0-d73e6f298598\";s:10:\"connection\";N;s:5:\"queue\";N;s:15:\"chainConnection\";N;s:10:\"chainQueue\";N;s:5:\"delay\";N;s:7:\"chained\";a:0:{}}s:8:\"channels\";a:1:{i:0;s:4:\"mail\";}s:10:\"connection\";N;s:5:\"queue\";N;s:15:\"chainConnection\";N;s:10:\"chainQueue\";N;s:5:\"delay\";N;s:7:\"chained\";a:0:{}}","commandName":"Illuminate\\Notifications\\SendQueuedNotifications"},"displayName":"App\\Notifications\\InvoiceSent","timeoutAt":null,"pushedAt":1513625383,"job":"Illuminate\\Queue\\CallQueuedHandler@call","maxTries":null,"attempts":2}

**Comment by themsaid** [comment]
Yes I can't replicate it, can send a queued anonymous notification with no issues, I think it's something with your code, try to replicate it in a fresh laravel installation.
