### ISSUE TITLE
Error route(any method, ie.GET) and extra parameter 

### ISSUE THREAD

**Issue by MarcosAugustoOliveiraSilva** [laravel/framework#22457]
Laravel Version: 5.5.24
PHP Version: 7.1.10
Database Driver & Version: N/A

### Description:
If you create a route(any method, ie.GET) with an extra parameter, and inject a dependency with the same parameter name, laravel does not recognize the extra parameter.

### Steps To Reproduce:

**In web routes**

`Route::get('test/{test}', 'TestController@test');`

**In controller**
```
namespace App\Http\Controllers;

use App\Test;
use Illuminate\Http\Request;

class TestController extends Controller
{
    public function test(Request $req, Test $test, $id)
    {
        return 'success - {$id}';
    }
}
```
**In url**

`http://localhost:8000/test/2`

![image](https://user-images.githubusercontent.com/26351465/34083068-3cda3d88-e351-11e7-821b-a194e821bd5c.png)

**Comment by xuanquynh** [comment]
The {test} notation in uri definition will be bound with Test::findOrFail($id) if you type hint Test $test in the controller's method. There is no reasons to pass the $id one more time into the method because if the Test instance was found, you had the exact id of $test instance ($test->id)

**Comment by MarcosAugustoOliveiraSilva** [comment]
Are you saying that if don't pass the findOrFail() parameter, laravel will use the route parameter(test) ?
furthermore, this does not solve the problem, laravel can't confuse route's parameters with dependency injection parameters, if i want to do another thing with route's parameters, like print the value of the parameter of the route in view

**Comment by 36864** [comment]
What exactly were you expecting to happen here?
What do you expect laravel to pass into $id?

**Comment by devcircus** [comment]
By type-hinting the Model and defining a parameter in your route with the same name, implicit binding is used. You're then trying to fetch a third parameter that you haven't defined. If you just want to pass the id, don't utilize implicit binding.

Your route only defines 1 parameter and it gets hijacked with implicit model binding. That parameter is transformed to a model.

So
```
// either

public function test(Test $test)
{
    dd($test); // returns instance of Test model
}

// or

public function test(int $id)
{
    dd($id); // returns the actual passed id
}
```

To get what you want, you'd have to:
```
Route::get('/test/{test}/{id}', 'TestController@test');
```
then hit ```www.mysite.com/test/2/2
which doesn't make sense.

**Comment by xuanquynh** [comment]
@MarcosAugustoOliveiraSilva I mean if you don't type hint the Test class, you will have the exact id from uri but if you type hint Test $test, you will receive the result like Test::findOrFail($id); statement. In fact, to do other action with the id, just use $test->getKey() ($test->id) instead. I don't know you want the id any more because it's realy held on the $test now.
```
public function test(Request $req, $id)
{
    return 'success - {$id}';
}
```
or
```
public function test(Request $req, Test $test)
{
   return $test->id;
}
```

**Comment by jagadeshanh** [comment]
For optional parameters refer to docs: https://laravel.com/docs/5.5/routing#parameters-optional-parameters

**Comment by MarcosAugustoOliveiraSilva** [comment]
I will explain with more details, after that, if you still think that this doesn't make sense, I will close the issue, in my case, I was trying to add an parameter in default resource route, and when i passed the parameter I found the same error in this example
