### ISSUE TITLE
LogicException: Session name cannot be empty

### ISSUE THREAD

**Issue by kikky7** [laravel/framework#22456]
- Laravel Version: 5.4.36
- PHP Version: 7.1.8

### Description:
When running phpunit with --process-isolation flag I get this error:
`LogicException: Session name cannot be empty, did you forget to call "parent::open()" in "Symfony\Component\HttpFoundation\Session\Storage\Handler\NullSessionHandler"?`

When running without process isolation, the test passes.

### Steps To Reproduce:
After exploring where it fails, I found that the error is thrown when attempt() method is called:
```
if (auth()->attempt($this->credentials($request), $request->remember)) {
    if ($request->isJson()) {
        return response()->json([
            'user' => auth()->user(),
            'message' => __('You have been successfully logged in!'),
        ], 201);
    }

    return redirect()->intended(route($this->redirectTo));
}
```

**Comment by Dylan-DPC** [comment]
5.4 is no longer supported. Kindly try this on a 5.5 install and let us know if the issue still persists.

**Comment by kikky7** [comment]
Ok, upgraded to laravel 5.5.25 and phpunit 6.5.5 and the test passes.
Also I don't need to run --process-isolation because it uses so much less memory now. Almost 4 times less.

**Comment by zquintana** [comment]
For anyone else struggling with this add the following to a service providers register method:

~~~ php
    $this->app->extend('session.store', function (Store $store, Container $container) {
            $handler = $store->getHandler();
            $config  = $container->make('config');
            if ($handler instanceof NullSessionHandler) {
                $handler->open(null, $config->get('auth.defaults.guard'));
            }

            return $store;
    });
~~~
