### ISSUE TITLE
Error with resource route and extra parameter

### ISSUE THREAD

**Issue by MarcosAugustoOliveiraSilva** [laravel/framework#22454]
Laravel Version: 5.5.24
PHP Version: 7.1.10
Database Driver & Version: MySQL 5.7.19

### Description:
If you create a resource route with an extra parameter, and inject a dependency with the same parameter name, laravel does not recognize the extra parameter

### Steps To Reproduce:
**In the web routes**
```
Route::resource('itemEntry', 'ItemEntryController', ['only' => ['store', 'edit', 'update', 'destroy']]);
Route::post('itemEntry/store/{entry}', 'ItemEntryController@store');
```
**In controller**
```
use App\Entry;
use Illuminate\Http\Request;
public function store(Request $req, Entry $entry)
{

}
```
**In view**
 `<form method="POST" action="{{action('ItemEntryController@store', $entry->id)}}">`

**Erro image**
![image](https://user-images.githubusercontent.com/26351465/34074706-64831716-e29c-11e7-9096-4468ebb7f148.png)

**Comment by laurencei** [comment]
You need to flip the route definitions:

```
Route::post('itemEntry/store/{entry}', 'ItemEntryController@store');
Route::resource('itemEntry', 'ItemEntryController', ['only' => ['store', 'edit', 'update', 'destroy']]);
```
