### ISSUE TITLE
Laravel webpack build not clean, generated js files under public

### ISSUE THREAD

**Issue by serak** [laravel/framework#22468]
- Laravel Version: 5.5
- PHP Version: 7.1
- Database Driver & Version: mysql 5.7

### Description:
lavaravel webpack compiles vue components with require(./component.vue) to public/0.js,1.js .... instead of public/js/0.js ,1.js ...

### Steps To Reproduce:
create two components , 1 main and on loaded dynamically using Vue.component('mycomp',()=>import('component1.vue'));
without laravel and vuejs 2.5 , vue-cli 2.9.2 npm run build builds the dist structure correctly like

dist|
.......static/
................/css
.............../js
.................../0.js
............../font

but in laravel this structure gets messed up

thanks

**Comment by mathieutu** [comment]
I think you should post this issue in the laravel-mix repo:
https://github.com/JeffreyWay/laravel-mix
🙂
