### ISSUE TITLE
Replacing attribute underscores in validation messages

### ISSUE THREAD

**Issue by diazemiliano** [laravel/framework#22466]
There is any chance to change:
https://github.com/laravel/framework/blob/d7e6a7aab600c5cfae595ea22074ac3c536cbc28/src/Illuminate/Validation/Concerns/FormatsMessages.php#L240
just with: `return $attribute;`

Why the underscores are being replaced?
The attribute name should not remain unalterable?
Thanks.

**Comment by mfn** [comment]
This belongs into https://github.com/laravel/internals , please
