### ISSUE TITLE
Model associations seems to use the model name and not the protected $table variable.

### ISSUE THREAD

**Issue by mazyvan** [laravel/framework#22469]
- Laravel Version: 5.4
- PHP Version: 7.0.10
- Database Driver & Version: IDK

### Description:
Model associations seems to use the model name and not the `protected $table ` variable.

I have one Model call **_Request** (because Request is a reserved word) and,` protected $table = 'request';`
```php
/**
 * Get the visa_order record associated with the request.
 */
public function visa_order()
{
    return $this->hasOne('App\VisaOrder');
}

```
And on the migration I have this.
```php
// Foreign keys
$table->integer('request_id')->unsigned()->nullable();
$table->foreign('request_id')->references('id')->on('request');
```
But after the success of the migration I got this error when consulting the route.

> (2/2) QueryExceptionSQLSTATE[42S22]: Column not found: 1054 Unknown column 'visa_order.__request_id' in 'where clause' (SQL: select * from `visa_order` where `visa_order`.`__request_id` in (1) and `visa_order`.`deleted_at` is null)

I think that the query must be constructed using the `$table` var. if is defined

**Comment by lagbox** [comment]
Request isn't a reserved word.

**Comment by mazyvan** [comment]
Sorry l did not make myself clear. In the api.php file we have this `use Illuminate \ Http \ Request;` that's why I changed the name, I know it's not the best solution, but that's not the problem.

The issue is that if I have the $ table var defined, I will expect the framework to read it to construct the query.

**Comment by devcircus** [comment]
What does your route and/or controller look like. I just recreated your scenario, and everything worked as expected. This is my route:
```php
Route::get('/request/{request}', 'RequestsController@show');
```
and my controller with 'show' method'
```php
public function show(_Request $request)
{
    return $request;
}
```
when I hit the route, the correct data is returned.

**Comment by 36864** [comment]
Foreign key names are derived from the class name, not table name. You'll need to manually specify the foreign key on your relationship.

**Comment by rs-sliske** [comment]
by default it will use the {method_name}_id as the foreign key name

if you want to use a different name you can pass it as the second parameter (although imo having to do this is an indicator that methods/fields could be named better)
