### ISSUE TITLE
Routes for NOT prolonging session lifetime

### ISSUE THREAD

**Issue by rtucek** [laravel/framework#22464]
I wounder if it's possible to assign a middleware to some routes, that would prevent extending session lifetime on every request.

Use case:
I have a dashboard with live charts (querying data with HTTP request on an interval of x seconds). Whenever the browser sends a request, the sessions lifetime gets extended, which is undesired. We want to have requests to those routes, specifically designed for querying dashboard live data, to allow session timeouts **on purpose**.

I can't find any hook, event, middleware, HTTP header or something similar to allow this behavior. 

Is there any other way to achieve this behavior without writing a custom session handler?
Writing a custom session handler is what I prefer at least, because using this would drop the session persistence abstraction (switching between db-, redis-, memcache-, file-based session persistance... wouldn't be possible anymore) and this is quiet important for running tests (production sites rely on redis, but unittests and CI use the file-based session handler).

Also I can't forgo the auth middleware and use stateless api routes, because I want to have users to be authenticated...

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this github area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I please suggestion closing your issue ticket here. Instead trying asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.
