### ISSUE TITLE
Could not find stored procedure 'sp_msforeachtable' for Azure Database

### ISSUE THREAD

**Issue by mtibbo** [laravel/framework#22467]
- Laravel Version: 5.5
- PHP Version: 7.1
- Database Driver & Version: SQL Server 

### Description:

When I use model factories in my unit tests phpUnit show this error

### Steps To Reproduce:

Set Up a laravel application in Microsoft Azure with a database and try to test some functionality with a factory:

`public function test()
    {
        $user= factory('App\User')->create();
    }`
And execute phpUnit command

I've seen that this procedure is undocumented by Microsoft and also doesn't exist in Azure Database architecture. I don't have any solution except change the procedure in the compileDropAllTables in SqlServerGrammar.php. Thank you for your future replies and sorry for my bad english :)

**Comment by lancepioch** [comment]
AzureDB is not completely backwards compatible with SQL Server, it's rather a subset.

However, you can still add the stored procedure yourself manually to resolve at least this issue. Googling for a replacement gave me many solutions to try.
