### ISSUE TITLE
Can not use '?&' operator of PostgreSQL

### ISSUE THREAD

**Issue by yfuseki** [laravel/framework#22472]
- Laravel Version: 5.5.25
- PHP Version: 7.1.10
- Database Driver & Version: (PostgreSQL) 9.5.9

```php
$notices = $notices->whereRaw(
            DB::raw('(deliver_json->\'hiho_kbn\')::jsonb ?& array[\''.$user->hiho_kbn.'\']')
        );

        dd($notices->get());
```

Illuminate \ Database \ QueryException (42601)
SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "$1" LINE 1: ..."notices" where (deliver_json->'hiho_kbn')::jsonb $1& array[... ^ (SQL: select * from "notices" where (deliver_json->'hiho_kbn')::jsonb ?& array['1'] order by "created_at" desc)

**Comment by 36864** [comment]
`?` is a placeholder for query parameters. You'll need to escape it.

**Comment by mfn** [comment]
@yfuseki I believe @36864 is correct and what's you're experiencing is a PHP problem, see this example:

```php
<?php
$pdo = new PDO('FILL IN);
$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
//$pdo->setAttribute(PDO::ATTR_EMULATE_PREPARES, true);
$json = <<<JSON
'["a", "b"]'::jsonb ?& array['a', 'b']
JSON;
var_dump($pdo->query("SELECT $json")->fetchAll());
```
This outputs:
```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "$1"
LINE 1: SELECT '["a", "b"]'::jsonb $1& array['a', 'b']
                                   ^ in /pdo_pgsql_json_escape.php:8
```
In line 4 I've commented prepared statement emulation. If I turn it on, I get the correct result back:
```php
array(1) {
  [0]=>
  array(2) {
    ["?column?"]=>
    bool(true)
    [0]=>
    bool(true)
  }
}
```

I think it's similar, if not the same problem, reported at https://bugs.php.net/bug.php?id=74220 . It's too about content of an SQL statement improperly being interpreted for prepared statement placeholders.

**Comment by tillkruss** [comment]
I just ran into this trying to use the `?|` operator and it's working as of PHP 7.4:

https://wiki.php.net/rfc/pdo_escape_placeholders
