### ISSUE TITLE
Laravel api resource exception is being generated

### ISSUE THREAD

**Issue by bigzoo** [laravel/framework#22477]
- Laravel Version: 5.5.25
- PHP Version: 7.0.22

### Description
I'm generating resources for my api with apiResource and exceptions I define are being ignored.

Selected content of routes/api.php
`
Route::apiResource('posts', 'PostController', ['except' => ['show']]);
`
Selected output of  `php artisan route:list`
`
GET|HEAD | api/posts/{post} | posts.show | App\Http\Controllers\PostController@show | api
`
Not sure if this is a lacking feature or a bug.

### To reproduce.
Create a project
Generate a controller:
`
php artisan m:controller PostController
`
Create an api route for the controller in routes/api.php by adding the following code:
`
Route::apiResource('posts', 'PostController', ['except' => ['show']]);
`
For this app we don't want the specific show method hence we added an extra param called except which as stated [here](https://laravel.com/docs/5.5/controllers#restful-partial-resource-routes) should instruct laravel to ignore the specific one's we instruct it to ignore.

**Comment by themsaid** [comment]
What exceptions do you define and how are you defining them?

Please include a detailed steps of replication, I don't seem to understand your issue.

**Comment by bigzoo** [comment]
@themsaid by exceptions I mean adding the ` ['except' => ['show']]` part while generating the resource.
The expected behavior is that the route posts.show shouldn't be generated but it is as shown by output of route:list command. I've updated the reproducing instructions.

**Comment by themsaid** [comment]
Yeah it seems like you can't use `except` with apiResources since `only` is already used under the hood and it overrides the `except`, switch to using `Route::resource` instead.

**Comment by bigzoo** [comment]
Thanks, I'll close this for now. Would be something nice to have in a later version though.
