### ISSUE TITLE
Fully support Request::validate method in IDE

### ISSUE THREAD

**Issue by denirun** [laravel/framework#22474]
- Laravel Version: 5.5.26
- PHP Version: 7.1.11
- Database Driver & Version: -

### Description:
IDE not fully support `Illuminate\Http\Request::validate` autocomplete for object instances.

### Steps To Reproduce:
When you using _barryvdh/laravel-ide-helper_  library, and try call `\Request::validate()` all works perfectly.

When you have instance of `Illuminate\Http\Request` class and try to call method validate IDE don't see implementation of this method.
 
Can you please fix this annoying small problem.
 
```php
public function index(\Illuminate\Http\Request $request): View
{
       // All good
      \Request::validate();

       // Method 'validate' not found
	$request->validate([
	    'name' => 'required',
	]);
}
```

**Comment by LKDevelopment** [comment]
This should go to barryvdh/laravel-ide-helper's repository and isn't an issue from laravel itself.

**Comment by denirun** [comment]
No! You are not right! If you write like this
```php
$request = new \Illuminate\Http\Request();
$request->validate();
```
Does your IDE see method **validate()** ?
Strange but my not, also i checked this class, and all traits and there is no implementation of validate method. Please add this!

**Comment by devcircus** [comment]
'validate' is implemented as a macro on request in the core, here. [FoundationServiceProvider](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Foundation/Providers/FoundationServiceProvider.php). 

Seems @LKDevelopment is correct. Don't really see another way.

**Comment by denirun** [comment]
Thanks @devcircus i get it now.  My opinion validate it's very good syntax sugar to place inside Request class. Code much smaller and elegant. But idea to make it via macros and fully lost autocomplete with check implementation, phpdoc and e.t.c..... very controversial. I personally don't like "magical", but if no way to fix this... sad :-(

**Comment by devcircus** [comment]
True. Still confused by this. I don't know of any other macros used in the core but I can't help but think that maybe there was a good reason for implementing it this way. Maybe worth opening an issue on the internals repo to discuss?

**Comment by rs-sliske** [comment]
https://github.com/laravel/framework/pull/19063#issuecomment-320365024

**Comment by devcircus** [comment]
Makes sense! Thanks.
