### ISSUE TITLE
[5.5] PSR2 Can not be followed

### ISSUE THREAD

**Issue by sfgn** [laravel/framework#22487]
- Laravel Version: 5.5.26

### Description:

It is not possible to correctly follow PSR2 standards when developing a laravel application fully.

The most obvious example is the database migrations, as they can not be namespaced because the Migrator will not be able to find it, but PSR2 requires all class to be namespaced.

### Steps To Reproduce:

Create a migration in laravel, using artisan
Install PHP Code Sniffer and run it on your project, using the --standard=PSR2

------

Is there anything that can be done, or any plans to upgrade the framework to make following PSR2 100% possible?

**Comment by laurencei** [comment]
Hi @sfgn,

This is best to be placed in https://github.com/laravel/internals for discussion there.

**Comment by sfgn** [comment]
Thanks - I did try looking for a existing one but must have missed it.
