### ISSUE TITLE
getAuthIdentifierName

### ISSUE THREAD

**Issue by blicksem** [laravel/framework#22483]
- Laravel Version: 5.526
- PHP Version: 7.0.3
- Database Driver & Version: MySql 5.7.18

### Description:
after updating composer I get the following error:
An exception has been thrown during the rendering of a template ("Call to undefined method Illuminate\Database\Query\Builder::getAuthIdentifierName()") in ...

### Steps To Reproduce:
I have updated composer with the following result:

$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 13 updates, 0 removals
  - Updating psy/psysh (v0.8.14 => v0.8.16): Downloading (100%)
  - Updating egulias/email-validator (2.1.2 => 2.1.3): Loading from cache
  - Updating erusev/parsedown (1.6.3 => 1.6.4): Loading from cache
  - Updating laravel/framework (v5.5.20 => v5.5.26): Downloading (100%)
  - Updating laravel/tinker (v1.0.2 => v1.0.3): Downloading (100%)
  - Updating filp/whoops (2.1.12 => 2.1.14): Loading from cache
  - Updating phpunit/phpunit-mock-objects (4.0.4 => 5.0.5): Downloading (100%)
  - Updating phpunit/php-file-iterator (1.4.2 => 1.4.5): Loading from cache
  - Updating phpunit/php-token-stream (2.0.1 => 2.0.2): Loading from cache
  - Updating phpunit/php-code-coverage (5.2.3 => 5.3.0): Loading from cache
  - Updating phpdocumentor/reflection-docblock (4.1.1 => 4.2.0): Loading from cache
  - Updating phpspec/prophecy (v1.7.2 => 1.7.3): Loading from cache
  - Updating phpunit/phpunit (6.4.4 => 6.5.5): Downloading (100%)
  - Installing maximebf/debugbar (1.13.1): Downloading (100%)
  - Installing barryvdh/laravel-debugbar (v2.4.3): Downloading (100%)
maximebf/debugbar suggests installing kriswallsmith/assetic (The best way to manage assets)
maximebf/debugbar suggests installing predis/predis (Redis storage)
Writing lock file
Generating optimized autoload files
Warning: Ambiguous class resolution, "App\User" was found in both "D:/_php/pos/app\Logon.php" and "D:/_php/pos/app\User.php", the first will be used.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: fideloper/proxy
Discovered Package: laravel/tinker
Package manifest generated successfully.

**Comment by KKSzymanowski** [comment]
```
Warning: Ambiguous class resolution, "App\User" was found in both 
"D:/_php/pos/app\Logon.php" and "D:/_php/pos/app\User.php", the first will be used.
```
You probably haven't changed the class name after you copied `User.php` to `Logon.php`

**Comment by blicksem** [comment]
Thank, you @KKSzymanowski for the response, It was indeed the problem, but I hadn't made the connection with the warning and the error I got, also because it wasn't a problem before the update.

**Comment by KKSzymanowski** [comment]
It probably arised after the update because only then the `composer dump-autoload` command was run and composer took the first implementation of the User class it could find which was in `Logon.php`(because of alphabetical order).
