### ISSUE TITLE
Global select list not respected in belongsToMany relationship

### ISSUE THREAD

**Issue by KKSzymanowski** [laravel/framework#22482]
- Laravel Version: 5.5.24
- PHP Version: 7.1.11
- Database Driver & Version: MySQL 15.1 Distrib 10.2.10-MariaDB

### Description:
I'm working with a legacy database with an enormous number of columns in tables and I want to fetch only few of them. Usually I restrict the column list globally by adding a query scope in the boot method of the model and it works fine with one-to-many relationships but with a many-to-many relationship all columns from the related table are being fetched.

This is because the scopes are applied *after* the column list on the query instance is checked in `BelongsToMany::get()`
```php
public function get($columns = ['*'])
{
    $columns = $this->query->getQuery()->columns ? [] : $columns;

    $builder = $this->query->applyScopes();

    // ...
}
```
Is there a reason behind this? Can this order be reversed like so:
```php
public function get($columns = ['*'])
{
    $builder = $this->query->applyScopes();

    $columns = $builder->getQuery()->columns ? [] : $columns;

    // ...
}
```

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by KKSzymanowski** [comment]
I believe it is a bug, because the scope treatment is inconsistent across relationship.

Here are steps needed to reproduce, so you have a full bug report:

### Steps to reproduce

1. Create a User model
```php
class User extends Authenticatable
{
    protected $fillable = ['name'];

    public function permissions()
    {
        return $this->belongsToMany(Permission::class);
    }
}
```
2. Create a Permission model
```php
class Permission extends Model
{
    public static function boot()
    {
        parent::boot();

        static::addGlobalScope(function(Builder $query) {
            $query->select('name');
        });
    }
}
```
3. Create migrations for the models and the intermediary table:
```php
Schema::create('users', function (Blueprint $table) {
    $table->increments('id');
    $table->string('name');
    $table->timestamps();
});
Schema::create('permissions', function (Blueprint $table) {
    $table->increments('id');
    $table->string('name');
    $table->text('description');
    $table->timestamps();
});
Schema::create('permission_user', function (Blueprint $table) {
    $table->increments('id');
    $table->integer('permission_id');
    $table->integer('user_id');
});
```
4. Migrate the database
5. Create a user
```php
\App\User::create([
    'name' => 'John Doe',
]);
```
6. Create a test route:
```php
Route::get('/', function () {
    $user = \App\User::first();

    DB::listen(function ($query) {
        dump($query->sql);
    });

    $user->permissions()->get();
});
```

### What is expected

Only the `name` column should be fetched from the `permissions` table and the dumped query 
should look something like this:

```sql
select 
    `name`, 
    `permission_user`.`user_id` as `pivot_user_id`, 
    `permission_user`.`permission_id` as `pivot_permission_id` 
from `permissions` 
inner join `permission_user` on `permissions`.`id` = `permission_user`.`permission_id` 
where `permission_user`.`user_id` = ? 
```

### What is actually happening

All columns are fetched from the `permissions` table and the query looks like this:
```sql
select 
    `name`, 
    `permissions`.*, 
    `permission_user`.`user_id` as `pivot_user_id`, 
    `permission_user`.`permission_id` as `pivot_permission_id` 
from `permissions` 
inner join `permission_user` on `permissions`.`id` = `permission_user`.`permission_id` 
where `permission_user`.`user_id` = ? 
```
