### ISSUE TITLE
Laravel 5.5 Config cacheing issue

### ISSUE THREAD

**Issue by inpothet** [laravel/framework#22491]
- Laravel Version: 5.5.26
- PHP Version: 7.1.11
- Database Driver & Version: n/a

### Description:
When i create a new laravel 5.5 application using `laravel new` it generates the code and puts the key in the .env but the config gets cached before the key is put in.
This generates the following error on a fresh install 
`[2017-12-20 13:26:59] production.ERROR: No application encryption key has been specified. {"exception":"[object] (RuntimeException(code: 0): No application encryption key has been specified. at C:\\WinNMP\\WWW\
ekoit\\vendor\\laravel\\framework\\src\\Illuminate\\Encryption\\EncryptionServiceProvider.php:42)`

this behavior never happened with the 5.4 version and it seems that the config needs to be cached now or else it doesn't even run

### Steps To Reproduce:
make a new laravel application with `laravel new`

**Comment by themsaid** [comment]
The installer doesn't cache your config, I can run `laravel new` without issues, make sure your update your laravel installer to the latest version.

**Comment by inpothet** [comment]
Everything is up to date
Ran `composer self-update`, `composer global update` and `composer update`
i can even make a screen capture of the problem if you want

**Comment by inpothet** [comment]
also if i do `php artisan config:clear` i also get the error of no key set

**Comment by themsaid** [comment]
I can't replicate the issue, everything seems to be working fine on my end.

**Comment by inpothet** [comment]
What do you run?
nginx or apache

**Comment by themsaid** [comment]
nginx, but it shouldn't really matter, config is not cached by default.

**Comment by themsaid** [comment]
Please share the entire output of the laravel new command.

**Comment by inpothet** [comment]
ok 1 sec let me run it in a new folder

**Comment by inpothet** [comment]
https://pastebin.com/nSXkaAkF here you go

**Comment by inpothet** [comment]
and mabye i worded it wrong, the problem isnt that the caching part it is that your application only works if you cache
in older versions you didn't have to do this

**Comment by inpothet** [comment]
making a gif of the problem

**Comment by themsaid** [comment]
I don't see any error messages in the output you shared, everything looks fine and key is set.l

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.

**Comment by inpothet** [comment]
@themsaid please give me a sec for the gif to transcode so i can show the problem

**Comment by inpothet** [comment]
http://i.haazen.xyz/o9zW36Ap.gif here is the problem visable

**Comment by themsaid** [comment]
I think an old cache is stuck somewhere in your system causing new applications to find the .env file missing the key, I suggest that you post on the forums for people using the same setup can help with ideas.

But please share as much details as possible so people can help fast.

**Comment by sisve** [comment]
@inpothet That gif doesn't load; Cloudflare cannot connect to the origin. Was it a good gif? Can you provide a transcript for it for us that cannot load it?

**Comment by inpothet** [comment]
@sisve 
After creating application and going to the index.php it gives a oops something happened
After doing config:cache it works
after doing config:clear it stops working

**Comment by 36864** [comment]
Does the error still persist in the new project you created in the new folder?

**Comment by inpothet** [comment]
@36864 yes

**Comment by sisve** [comment]
@inpothet That does sound weird, but it's not yet proven that this is due to a bug in Laravel. Maybe you should close this issue and ask for help on Slack at https://larachat.co/ ?

**Comment by inpothet** [comment]
True, i only think its a bug because this didn't happen on 5.4

**Comment by zemigpt** [comment]
Got exactly the same problem, using WinNMP. w/ PHP 7.2.0.

**Comment by inpothet** [comment]
tried this sadly new env vars dont show up after running that again

**Comment by sisve** [comment]
@inpothet That's exactly what the config:cache command does, it builds a cached configuration file and stops parsing the .env file at every request.

You need to rerun `php artisan config:cache` after any change to .env of environment variables to rebuild the cached configuration file.

**Comment by inpothet** [comment]
yea i know that, but even after running the command 10 times in a row the cache woudnt change
even doing `config:clear` and `cache:clear` nothing happens

**Comment by inpothet** [comment]
going to join larachat see if we can find what is wrong there

**Comment by surgiie** [comment]
@nekocentral were you able to figure out the problem?

**Comment by nekocentral** [comment]
sadly not, for now i just gave up might retest it soon with a newer version of WinNMP and laravel,
will post a update when tested
you can close for now

**Comment by janschloss** [comment]
Same problem here.
