### ISSUE TITLE
Attach method 

### ISSUE THREAD

**Issue by espositodaniele** [laravel/framework#22490]
- Laravel Version: 5.5.22
- PHP Version:  7.1.8

Hello to everyone. 
 
I would like to understand why the "attach" method returns null when successfully inserted and so how can I check that was successfully inserted?

Many thanks

D

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
