### ISSUE TITLE
Carbon Date saving

### ISSUE THREAD

**Issue by Farzoqe** [laravel/framework#22498]
- Laravel Version: 5.5
- PHP Version:5.6
- Database Driver & Version:Mysql

### Description:
The date saving sometime saves current date for a custom date attribute when mass assigned. 

$order = \App\Order::updateOrCreate(
                                        [
                                    'external_id' => "$exOrder->id",
                                        ], [
                                    'invoice' => $exOrder->name,
                                    'order_date' => $orderDate,
                                    'user_id' => $user->id,
                                    'customer_tag_id' => $customerTag->id,
                                    'total' => $exOrder->total_price,
                                    'customer_id' => $customer->id,
                                    'tax_name' => $taxName,
                                    'tax_value' => $taxRate,
                                    'tax_code_id' => $taxId,
                                    'shipping' => isset($exOrder->shipping_lines[0]->price) ? $exOrder->shipping_lines[0]->price : 0,
                                        ]
                        );

The order Date attributes save current date randomly for some entries. 
Only specific thing about this code is, it makes 1000 updates in 1 minute so it could be related to that. 

using this method fixed it: 
                        \App\Order::where('id', $order->id)->update(['order_date' => $orderDate]);

### Steps To Reproduce:
Create a model with $dates attribute and mass assign with 1000 per minute

**Comment by Dylan-DPC** [comment]
What is your input data like? Maybe the input data is invalid in some cases for which it defaults to today's date? Can you reproduce this with a simpler use case? 

Also i'm not sure how you are running Laravel 5.5 with PHP 5.6. Something seems odd here.

**Comment by mkingbe** [comment]
Are you using date mutator? as @Dylan-DPC said try to debug/validates dates to see if there are all valid or not.

**Comment by Farzoqe** [comment]
input data is like 2018-01-01. Thing is, it gets right date sometimes and sometimes it gets current date. also the field has to be a date mutated field in order for it to work. if i don't use protected $dates=[] then the data goes fine.

**Comment by devcircus** [comment]
You need to drill down to the dates that are causing the problem. You'll find the issue then. Dump every date while saving and inspect the ones that failed.

**Comment by GabrielaSaldana** [comment]
Probably it has to be with the incoming format of the date. You need to dump every step of the date updating process so you can verify it is in the correct format order.
