### ISSUE TITLE
Ratelimiter hit method doesn't update timestamp

### ISSUE THREAD

**Issue by jacobnijgh** [laravel/framework#22501]
- Laravel Version: 5.5.25
- PHP Version: 7.1.0
- Database Driver & Version: Redis 4.0.2

### Description:
I am using my own Trait to throttle certain methods/routes to limit acces to this resources. However the hit method in the RateLimiter class that i am using which is the same as the Throttleslogins trait is using, doesn't update the timestamp in the cached key, cause it using the cache add method instead of put.

This results in when the resource is locked the time to available is already started after the first hit. Is this supposed to happen, or can this be seen as a bug.

**Comment by laurencei** [comment]
That seems correct to me? 

If it changed the timestamp, then it would keep the limit going on and on - and never expire if you continually accessed it?

**Comment by jacobnijgh** [comment]
There is a third param available that expires the cached key, however, i guess that i misunderstood the use of the ratelimiter class then, my use case is to ban/lockout users for a specific time after max attempts are reached.
