### ISSUE TITLE
MethodNotAllowedHttpException

### ISSUE THREAD

**Issue by pinaksaha** [laravel/framework#22508]
- Laravel Version: 5.5.27
- PHP Version: 7.1.7
- Database Driver & Version:

### Description:

 php artisan route:list
+--------+-----------+----------------------+--------------+---------------------------------------------+--------------+
| Domain | Method    | URI                  | Name         | Action                                      | Middleware   |
+--------+-----------+----------------------+--------------+---------------------------------------------+--------------+
|        | GET|HEAD  | /                    |              | Closure                                     | web          |
|        | GET|HEAD  | api/user             | user.index   | App\Http\Controllers\UserController@index   | api          |
|        | POST      | api/user             | user.store   | App\Http\Controllers\UserController@store   | api          |
|        | GET|HEAD  | api/user/create      | user.create  | App\Http\Controllers\UserController@create  | api,api-auth |
|        | GET|HEAD  | api/user/{user}      | user.show    | App\Http\Controllers\UserController@show    | api,api-auth |
|        | PUT|PATCH | api/user/{user}      | user.update  | App\Http\Controllers\UserController@update  | api,api-auth |
|        | DELETE    | api/user/{user}      | user.destroy | App\Http\Controllers\UserController@destroy | api,api-auth |
|        | GET|HEAD  | api/user/{user}/edit | user.edit    | App\Http\Controllers\UserController@edit    | api,api-auth |
+--------+-----------+----------------------+--------------+---------------------------------------------+--------------+

But when I try to hit the store method via curl:

curl -X POST \
  http://wwe.local/api/user \
  -H 'cache-control: no-cache' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
  -H 'postman-token: de77f4d7-2fb5-5a84-7909-e9324d2dbc1a' \
  -F 'name=Pinak Saha' \
  -F email=abc@gmail.com \
  -F password=abc124

I get:

MethodNotAllowedHttpException

**Comment by pavinthan** [comment]
@pinaksaha please change the content type as `application/x-www-form-urlencoded` in postman this not related to Laravel

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
