### ISSUE TITLE
[Eloquent] Model::insert doesnt create timestamps

### ISSUE THREAD

**Issue by megaxlr** [laravel/framework#22502]
- Laravel Version: 5.5.21
- PHP Version: PHP 7.1.12-3+ubuntu17.04.1+deb.sury.org+1
- Database Driver & Version: PDO mysqlnd 5.0.12-dev - 20150407

### Description:
Creating new entries in the database using Eloquents `Model::insert` doesnt set the `created_at` timestamp

### Steps To Reproduce:
Create a table and a model
I.E. 
```
users:
    id int
    password string
    email string
    created_at timestamp
    updated_at timestamp
```
```php
Users::insert([
    'password' => bcrypt('secret'),
    'email' > 'example@exam.pl',
]);
```
Doesnt set the `created_at` timestamp

**Comment by 36864** [comment]
You'll need to use `Model::create` for this.
Model doesn't have an `insert` method. Calling `Model::insert` results in a call to `Builder::insert` through the `__call()` magic method:
https://github.com/laravel/framework/blob/514cba91467a4dd74988bed50a00e314704dbdf2/src/Illuminate/Database/Eloquent/Model.php#L1455
