### ISSUE TITLE
"npm run dev" taking longer after upgrading Vue

### ISSUE THREAD

**Issue by tareqtms** [laravel/framework#22509]
- Laravel Version: 5.5.19
- PHP Version: 7.0.25
- Database Driver & Version: mysql  Ver 15.1 Distrib 10.1.16-MariaDB, for osx10.11 (x86_64) using readline 5.1

### Description:
I am using Vue with Laravel, as it is there by default. I have 18 vue components and 4 JS files (for separate vue instances) and 4 css files to be processed by webpack. Previously, "npm run dev" took a few seconds to create the js files, but "npm run prod" was taking like over a minute. But recently I updated vue to latest version (2.5.11) and it started taking too long for "npm run dev", it's taking like around 2 minutes for each run. Even "npm run prod" is taking lower time than it.

### Steps To Reproduce:
Create some componets and vue instances as described above and run "npm run dev"

**Comment by Dylan-DPC** [comment]
`npm run dev` has nothing to do with laravel. It could be something with vue or worst case, an issue with mix/webpack.

**Comment by tareqtms** [comment]
I already created the issue for Vue, but they said, the issue is not related to them and they closed the issue immediately: https://github.com/vuejs/vue/issues/7293

**Comment by tareqtms** [comment]
I also created the issue in webpack : https://github.com/webpack/webpack/issues/6177 .
But need to make sure is it something with laravel mix, which is an extended version of webpack?

**Comment by pavinthan** [comment]
Duplicate https://github.com/JeffreyWay/laravel-mix/issues/49
