### ISSUE TITLE
sometimes mysqlconnections refused

### ISSUE THREAD

**Issue by fj123ll** [laravel/framework#22504]
- Laravel Version: 5.3.31
- PHP Version: 7.0.11
- Database Driver & Version: mysql - 5.7.16

### Description:
[2017-11-27 15:19:09] local.ERROR: SQLSTATE[HY000] [2002] Connection refused

It's really wired that most of the time, everything works fine. but sometime laravel through an exception of database connection refused. It could happen anywhere in my project, and I just need refresh the page to continue.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this github area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I please suggestion closing your issue ticket here. Instead trying asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.
