### ISSUE TITLE
Delayed event causing a 500 internal error.

### ISSUE THREAD

**Issue by agentmarine** [laravel/framework#22503]
- Laravel Version: 5.5.*
- PHP Version: 7.1.11
- Database Driver & Version: Mysql
- Queue Driver: redis

### Description:
I've been working on adding a notification to the site I am building, a standard notification works just fine, but one requirement is that they needed to be delayed. I've added `implements ShouldQueue` onto the class declaration. as suggested in the documentation and immediately ran into a low level error.

### Steps To Reproduce:
create a new notification using artisan
`php artisan make:notification EventNotification`

change class declaration to the following
`class EventNotification extends Notification implements ShouldQueue`
in a controller use the same code given from the [documentation](https://laravel.com/docs/5.5/notifications#queueing-notifications)

`   $when = Carbon::now()->addMinutes(10);
        Auth::user()->notify((new EventNotification())->delay($when));`
navigate to the route, you will receive a 500 internal error with no stack trace visible.

I've found the errors in the server logs.[here](https://pastebin.com/Eb1NNZ1d)

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this github area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I please suggestion closing your issue ticket here. Instead trying asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.

**Comment by agentmarine** [comment]
I would classify it as a bug with the framework since I am using the base notification system and following the guidance of the documentation which right now doesn't work as described. 

I've asked in the laravel slack channel first, and people have agreed with me there after extensive testing and scrutinising various configurations and came to the conclusion that it is not working as it is supposed to hence why i have created this issue.

**Comment by laurencei** [comment]
Just for the record in case people find this via google etc; from talking to @agentmarine on Slack - it seems the problem relates to `php artisan serve` somehow.

Using a "proper" server like Valet/Homestead seems to fix the problem.
