### ISSUE TITLE
Workers - max retry not working when the payload is not parsable

### ISSUE THREAD

**Issue by kikkauz** [laravel/framework#22513]
- Laravel Version: 5.5
- PHP Version: 7.0
- Database Driver & Version: mysql  Ver 15.1 Distrib 5.5.56-MariaDB, for Linux (x86_64) using readline 5.1

### Description:
Handling jobs with big payload, bigger than 1Mb, I noticed that the job was retried till crash of the worker because the max value of the attempts field (tinyint) was reached.
Debugging, I found that the issue was due to the fact that I was not saving the full payload as the option PDO::MYSQL_ATTR_MAX_BUFFER_SIZE was not set.
This caused the payload to be truncated and the method payload of the class Jobs laravel/framework/src/Illuminate/Queue/Jobs/Job.php
was failing.
In order to add robustness, this possible failure should be handled - imho. 

### Steps To Reproduce:
corrupt a payload of a job and run the worker. The job will be retried till a failure because of max value reached.

**Comment by themsaid** [comment]
Feel free to open a PR with your suggested changes, it's better to discuss implementation at this point.

For suggestions and feature requests please use the https://github.com/laravel/internals repo.
