### ISSUE TITLE
Error when Migrate Tables - Production Server

### ISSUE THREAD

**Issue by evertramos** [laravel/framework#22521]
- Laravel Version: 5.5
- PHP Version: 7.1.3
- Database Driver & Version: MariaDB 14

### Description:
Error running `php artisan migrate`:

```
In 2017_12_17_222406_create_sessions_table.php line 35:

  Cannot declare class CreateSessionsTable, because the name is already in use
```

### Steps To Reproduce:
At local environment it does not happens, but in server it is showing this error. I check the [CreateSessionsTable file](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Session/Console/stubs/database.stub) I noticed it does not have a namespace, would that be the issue? Or I am doing something else (that I am not aware of) wrong?

Thanks!

**Comment by pavinthan** [comment]
@evertramos Laravel session driver class names in same class name so you can not create a class with the same name you can create migration in a different name to fix this issue

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by sisve** [comment]
Do you have another migration that provides the class CreateSessionsTable?

**Comment by evertramos** [comment]
@sisve I do not have another classname called CreateSessionsTable... In my local computer works just fine, when deploy to server I got this error...In local machine php version 7.2, main difference.

**Comment by evertramos** [comment]
@Dylan-DPC It seems a bug, that´s why I posted here.

**Comment by evertramos** [comment]
@pavinthan I am not trying to create this table, in fact I have a couple migrations file, which has nothing to do with this name neither sessions... this error occurs when deploy (php artisan migrate) the app in server.

**Comment by pavinthan** [comment]
@evertramos please try `composer dump-auto` and use this https://larachat.slack.com

**Comment by evertramos** [comment]
@pavinthan thanks for your reply! I did a lot of tests and found my mistake...

I am making a docker environment for Laravel to comply with the [Nginx Webproxy](https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion) and in some of the script files I probably ran (by mistake) `php artisan session:table` and as it was on script it ran more than one time.

Thanks for your attention.

**Comment by adamdenverco** [comment]
I had the same error message. This fixed it for me:

1. Go to "/database/migrations/"
2. Delete all files in the folder.
3. Do your "php artisan" actions (ex. "php artisan session:table").
4. Run your "php artisan migrate".
