### ISSUE TITLE
Unnecessary query when eager loading

### ISSUE THREAD

**Issue by votemike** [laravel/framework#22522]
- Laravel Version: 5.5.14
- PHP Version: 7.1.3
- Database Driver & Version:

### Description:
When eager loading a relation, a query is still made if the values in `IN` are all empty. I feel an optimisation could be made to check to see if all the values in the `IN` will be empty and avoid the query.

### Steps To Reproduce:
```
$widget = Widget::findOrFail(1);
$widget->parent_id = null;
$widget->save();

$widget->load('parent');
```

Results in the query `SELECT * FROM widget_parents WHERE widget_parents.id IN ('')`. Unless I'm missing some edge cases that I can't think of, this will always return an empty result.

**Comment by sisve** [comment]
There may be domain logic that forbids `widget_parents.id == ''`, but it is valid on a database level. You can have strings as primary keys.

**Comment by votemike** [comment]
My point is that a relationship will never join on a field with an empty value. Will it?

**Comment by mfn** [comment]
> My point is that a relationship will never join on a field with an empty value. Will it?

Of course they can, if the field is the appropriate type. Example (postgres):
```sql
CREATE TABLE foo (
  id VARCHAR(1) PRIMARY KEY
);
CREATE TABLE bar (
  id     BIGSERIAL,
  foo_id VARCHAR(1) CONSTRAINT bar_foo_id_fkey REFERENCES foo
);

INSERT INTO foo (id) VALUES ('');
INSERT INTO bar (id, foo_id) VALUES (123, '');

SELECT *
FROM bar
  JOIN foo ON bar.foo_id = foo.id;
-- => will show the result correctly
```

Maybe you're mixing it up with `WHERE … IN (NULL)` which can never match?

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
