### ISSUE TITLE
Laravel Server Installation not worked with developed version.

### ISSUE THREAD

**Issue by HobbyScripter** [laravel/framework#22543]
- Laravel Version: 5.5.22
- PHP Version:7.1
- Database Driver & Version:mariadb/mysql 10.2

### Description:
When I open my page I get an error in my apache log data.

[Wed Dec 27 01:17:08.644679 2017] [:error] [pid 29385] [client 84.175.110.66:33140] PHP Fatal error:  Uncaught ReflectionException: Class view does not exist in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:729\nStack trace:\n#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(729): ReflectionClass->__construct('view')\n#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(608): Illuminate\\Container\\Container->build('view')\n#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(575): Illuminate\\Container\\Container->resolve('view')\n#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(728): Illuminate\\Container\\Container->make('view')\n#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1172): Illuminate\\Foundation\\Application->make('view')\n#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php(148): Illuminate\\Container\\Container->offsetGet('Illuminate\\\\Cont...')\n#6 /var/www/html/vendor/laravel/framework/sr in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 729

### Steps To Reproduce:
When I open my page I get this error again and again.

[error.log](https://github.com/laravel/framework/files/1588076/error.log)

**Comment by mfn** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this github area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I please suggestion closing your issue ticket here. Instead trying asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/)
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.

---
On a related note, it _may_ be that the service providers are not properly configured in `config/app.php`, please include this information too when asking any of the above forums, thank you!

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
