### ISSUE TITLE
Queue job with 4 hours delay

### ISSUE THREAD

**Issue by iranagame** [laravel/framework#22541]
- Laravel Version: 5.4
- PHP Version: 7.0

*** This is not an issue, it's a question. ***
I have a mission-critical queue in laravel 5.4 which is powerd by Redis and 8 workers on supervisor.

In this queue, I have to make delayed jobs with a delay about 4 hours like this:
```
        $job = (new VerifyAndOrderJob($books))
            ->onQueue('orders')
            ->delay(\Carbon::now()->addHours(4));


        dispatch($job);
```
Now since Laravel queues are based on FIFO, If I have thousands of delayed jobs like this in the queue everyday and I wanted to push a same job but without any delay, is it need to wait till other delayed jobs to be processed or this will be fired instantly?

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue
