### ISSUE TITLE
How to get Image from MS SQL Server Database. Column DataType: Image

### ISSUE THREAD

**Issue by riyasopr** [laravel/framework#22544]
- Laravel Version: 5.5.2
- PHP Version: 7.2
- Database Driver & Version: sqlsrv

### Description:
How to get Image from MS SQL Server Database. Column DataType: Image ?

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
