### ISSUE TITLE
Web and code documentation mismatch?

### ISSUE THREAD

**Issue by alshenetsky** [laravel/framework#22549]
- Laravel Version: 5.5.28

### Description:
I am new at Laravel, sorry if I misunderstood something.
Please look at the first comment at the function **handleTransactionException** (**framework/src/Illuminate/Database/Concerns/ManagesTransactions.php:61**)

It says following: «On a deadlock, MySQL rolls back the entire transaction so we can't just retry the query. We have to throw this exception all the way out and let the developer handle it in another way. »

Does it comment correct? Official documentation ([https://laravel.com/docs/5.5/database#database-transactions](url)) says that Laravel can dealing with deadlocks automatically and I am supposed to do nothing in that case.

**Comment by sisve** [comment]
That comment is related to nested transactions, thus the check for `$this->transactions > 1`.

https://github.com/laravel/framework/blob/a926eede7a37b04123c103c398664a6f0389d0e0/src/Illuminate/Database/Concerns/ManagesTransactions.php#L61-L69

**Comment by alshenetsky** [comment]
@sisve Thank you very much, it was not obvious for me
