### ISSUE TITLE
 'Predis\NotSupportedException' with message 'Cannot use 'EVAL' 

### ISSUE THREAD

**Issue by Jaspur** [laravel/framework#22558]
- Laravel Version: 5.5.28
- PHP Version: PHP 7.1.11
- Database Driver & Version: pgsql

### Description:
```
production.ERROR: exception 'Predis\NotSupportedException' with message 'Cannot use 'EVAL' with redis-cluster.' in /home/forge/website.com/vendor/predis/predis/src/Connection/Aggregate/RedisCluster.php:380
```

### Steps To Reproduce:
```
# .env
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379
QUEUE_DRIVER=redis
```

```
# config
'connections' => [
    'redis' => [
        'driver' => 'redis',
        'connection' => 'default',
        'queue' => 'default',
        'retry_after' => 90,
    ],
],
```

Queue is started as demon via Forge
![schermafdruk 2017-12-28 17 14 49_preview](https://user-images.githubusercontent.com/4254854/34416195-a7bb5408-ebf2-11e7-8ac3-6e26539e38c0.png)

**Comment by sisve** [comment]
Probably related to https://github.com/laravel/framework/issues/18527

**Comment by Jaspur** [comment]
Probably, but that issue is closed.

**Comment by alibo** [comment]
It seems you're using Redis cluster, you should change your `config/queue.php` to this:

```php
// ...
'redis' => [
    'driver' => 'redis',
    'connection' => 'default',
    'queue' => '{default}', // <-- changed
    'retry_after' => 90,
],
// ...
```

**Comment by Jaspur** [comment]
Did that, but same errors. The strange thing is that I don't use Redis for anything.

**Comment by sisve** [comment]
@Jaspur A full stack trace can help us pinpoint why you're seeing redis problems if you're not using it. It can be found in the log files in storage/logs.

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
