### ISSUE TITLE
Impossible to run tests with a MAX_USER_CONNECTIONS option on MySQL

### ISSUE THREAD

**Issue by nesk** [laravel/framework#22556]
- Laravel Version: 5.5.28
- PHP Version: 7.1.12
- Database Driver & Version: MySQL 5.7.20

### Description:
If you're running some tests involving a MySQL database with a low value for the `MAX_USER_CONNECTIONS` option, then you will encounter the following exception:

```
PDOException: SQLSTATE[HY000] [1226] User 'max_connections_user' has exceeded the 'max_user_connections' resource (current value: 5)
```

For example, if you have 10 database tests and a connection limit set to 5, then the 6th test (and the next ones) will fail with the exception above. It seems like Laravel isn't properly closing the previous connections, or not in time.

### Steps To Reproduce:
- Clone this repository: [nesk/laravel-max-connections](https://github.com/nesk/laravel-max-connections)
- Open your MySQL console and run the following commands:
```sql
CREATE DATABASE max_connections_db;

CREATE USER 'max_connections_user'@'localhost' WITH MAX_USER_CONNECTIONS 5;

GRANT ALL PRIVILEGES ON * . * TO 'max_connections_user'@'localhost';
```
- Run the tests with `phpunit`, you should see the following exception:
```
PDOException: SQLSTATE[HY000] [1226] User 'max_connections_user' has exceeded the 'max_user_connections' resource (current value: 5)
```

**Comment by sisve** [comment]
This seems related to https://github.com/laravel/framework/issues/18471

**Comment by nesk** [comment]
You're right, I'm closing the issue.
