### ISSUE TITLE
Possible code duplication in several manager type classes

### ISSUE THREAD

**Issue by michaeldzjap** [laravel/framework#22574]
- Laravel Version: 5.5.28
- PHP Version: 7.2
- Database Driver & Version: mysql, 5.7.20-0ubuntu0.16.04.1

### Description:

This is more of an observation/question than an issue. While working on my own *Laravel* package I browsed through the *Laravel* source to see if there were any *Illuminate* classes I could re-use and came across `Illuminate\Support\Manager`, an abstract class than can be used as a base for manager type classes. Indeed it is used by `Illuminate\Notifications\ChannelManager`, `Illuminate\Mail\TransportManager` to name a few.

What I also noticed though, is that there are a number of manager based classes (e.g. `Illuminate\Broadcasting\BroadcastManager`, `Illuminate\Cache\CacheManager`) that do not extend `Illuminate\Support\Manager`, but actually duplicate much, if not all, of the code of that class. Is there a good reason for this? At first sight I can't find one, but then again I might overlook something of course. Just thought it would be good to inquire about.

**Comment by mfn** [comment]
This repo is for reporting bugs, if you want to discuss something, please open an issue at https://github.com/laravel/internals/issues
