### ISSUE TITLE
Multiple Queries for same statement

### ISSUE THREAD

**Issue by Nowi5** [laravel/framework#22579]
### Environment:
- Laravel Version: 5.5.28
- PHP Version: /
- Database Driver & Version: mysql

### Description:
Also within the same controller and same request (only one page called) the same DB/SQL Statement is fired multiple times. Shouldn't be there a kind of caching? Not necessarily across multiple page calls but within one instance of an model.

![laravel_translations_queries](https://user-images.githubusercontent.com/27913135/34461164-e4da98fc-ee23-11e7-9a60-7defd581659c.JPG)

### Steps To Reproduce:
1. Create a Eloquent Model on a MySQL Database.
2. Build a controller which calls this model and run multiple times the ::find(1) method.
3. You will that the DB Query is fired multiple times also in the same page request.

### Question:
When Laravel has this caching not as default, there are [packages out which do model caching](https://github.com/GeneaLabs/laravel-model-caching/issues/45#issuecomment-354577133), but how to influence vendors model? How can I overwrite the default Laravel Model class Illuminate\Database\Eloquent\Model?

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by sisve** [comment]
No, there is no such caching in Eloquent. The Eloquent models are just wrappers against database access. How can you be sure that querying twice will return identical data? What if you've written something to the database between two calls to ::find()?

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
