### ISSUE TITLE
verify csrf token default exclude all Routes !!!!!!!!!

### ISSUE THREAD

**Issue by abdolrhman** [laravel/framework#22578]
- Laravel Version: 5.5.*
- PHP Version:7
- Database Driver & Version:

### Description:
after using the new version of laravel 55
the login route have been shut down and i got this message : "  something duo to inactivity  "
i had to write the route in vertifyCsrfToken.php file now i want to understand shouldnt the default be include all the route to this file "vertifyCsrfToken.php" then i had to exclude the routes i want , to save the time and effort rather than the default to be exclude all routes and i have to write the routes to the file ?!!

**Comment by jmarcher** [comment]
Laravel will check for the Csrf token on any non GET/HEAD http request by default any I would not disable it if I were you.

That message appeared because your Csrf token expired.
