### ISSUE TITLE
Redis serialization broadcast issue

### ISSUE THREAD

**Issue by yooouuri** [laravel/framework#22571]
- Laravel Version: 5.5.*
- PHP Version: 7.2.0 (Homestead)
- Database Driver & Version: N/A

### Description:

In my event I var dumped my public `$chatMessage` property.

```
object(App\Models\ChatMessage)#779 (26) {
  ["table":protected]=>
  string(12) "chat_message"
  ["primaryKey":protected]=>
  string(7) "Chat_id"
  ["incrementing"]=>
  bool(false)
  ["timestamps"]=>
  bool(false)
  ["casts":protected]=>
  array(5) {
    ["Chat_id"]=>
    string(3) "int"
    ["Message_id"]=>
    string(3) "int"
    ["Posted_by"]=>
    string(3) "int"
    ["Message_type"]=>
    string(3) "int"
    ["Order_id"]=>
    string(3) "int"
  }
  ["dates":protected]=>
  array(1) {
    [0]=>
    string(4) "Date"
  }
  ["fillable":protected]=>
  array(6) {
    [0]=>
    string(4) "Date"
    [1]=>
    string(9) "Posted_by"
    [2]=>
    string(7) "Message"
    [3]=>
    string(11) "Message_img"
    [4]=>
    string(12) "Message_type"
    [5]=>
    string(8) "Order_id"
  }
  ["connection":protected]=>
  string(5) "mysql"
  ["keyType":protected]=>
  string(3) "int"
  ["with":protected]=>
  array(0) {
  }
  ["withCount":protected]=>
  array(0) {
  }
  ["perPage":protected]=>
  int(15)
  ["exists"]=>
  bool(true)
  ["wasRecentlyCreated"]=>
  bool(true)
  ["attributes":protected]=>
  array(7) {
    ["Message_id"]=>
    int(57)
    ["Chat_id"]=>
    string(3) "586"
    ["Posted_by"]=>
    int(117)
    ["Message"]=>
    string(7) "Hey man"
    ["Message_img"]=>
    string(4) "none"
    ["Message_type"]=>
    string(1) "1"
    ["Order_id"]=>
    NULL
  }
  ["original":protected]=>
  array(7) {
    ["Message_id"]=>
    int(57)
    ["Chat_id"]=>
    string(3) "586"
    ["Posted_by"]=>
    int(117)
    ["Message"]=>
    string(7) "Hey man"
    ["Message_img"]=>
    string(4) "none"
    ["Message_type"]=>
    string(1) "1"
    ["Order_id"]=>
    NULL
  }
  ["changes":protected]=>
  array(0) {
  }
  ["dateFormat":protected]=>
  NULL
  ["appends":protected]=>
  array(0) {
  }
  ["dispatchesEvents":protected]=>
  array(0) {
  }
  ["observables":protected]=>
  array(0) {
  }
  ["relations":protected]=>
  array(0) {
  }
  ["touches":protected]=>
  array(0) {
  }
  ["hidden":protected]=>
  array(0) {
  }
  ["visible":protected]=>
  array(0) {
  }
  ["guarded":protected]=>
  array(1) {
    [0]=>
    string(1) "*"
  }
}
```

ChatMessage model (generated with Reliese).

```
namespace App\Models;

use Reliese\Database\Eloquent\Model as Eloquent;

class ChatMessage extends Eloquent
{
    protected $table = 'chat_message';
    protected $primaryKey = 'Chat_id';
    public $incrementing = false;
    public $timestamps = false;

    protected $casts = [
        'Chat_id' => 'int',
        'Message_id' => 'int',
        'Posted_by' => 'int',
        'Message_type' => 'int',
        'Order_id' => 'int'
    ];

    protected $dates = [
        'Date'
    ];

    protected $fillable = [
        'Date',
        'Posted_by',
        'Message',
        'Message_img',
        'Message_type',
        'Order_id'
    ];

    public function chat()
    {
        return $this->belongsTo(\App\Models\Chat::class, 'Chat_id');
    }
}
```
When I run `redis-cli monitor`, I see a total different output...

<img width="1144" alt="screen shot 2017-12-30 at 00 59 36" src="https://user-images.githubusercontent.com/12934957/34449796-d00a9d5a-ecfc-11e7-94ee-57e3c09a6418.png">

As you can see, the attributes are totally different.

### Steps To Reproduce:

**Comment by sisve** [comment]
I love images. That's how real developers code, we look at images. Text snippets that we can reformat for easier reading is for the weak!

On a separate note, that image has `"Message": "Hey Robbert"`, while you sent `"Message": "Hey man"`. Some other values differ to. It's clearly your computer being sentient.

Or could it be that you're showing an image that shows an event that isn't for the provided $chatMessage?

Seriously. What is the bug? Things differ between php and a serialized redis format. Yes. Why would that be a bug?

**Comment by yooouuri** [comment]
@sisve 

> I love images. That's how real developers code, we look at images. Text snippets that we can reformat for easier reading is for the weak!

The image is a output, so why should you reformat or so? I can upload it in text format if you want.

> Or could it be that you're showing an image that shows an event that isn't for the provided $chatMessage?

The output is from `$chatMessage`

> Seriously. What is the bug? Things differ between php and a serialized redis format. Yes. Why would that be a bug?

It is a bug because it does not serialize the right output...

**Comment by sisve** [comment]
So, where's the text "Hey Robbert" coming from? There's nothing in this bug report we can use to reproduce the problem or understand why the message says "Hey Robbert". Also note that message_id differs.
