### ISSUE TITLE
Lumen: `$request` in `Resource` class is not the same request as in the container

### ISSUE THREAD

**Issue by simonhamp** [laravel/framework#22570]
- Laravel Version: Lumen 5.5.28
- PHP Version: 7.1.12
- Database Driver & Version: n/a

### Description:
When using the `Resource` class to generate a response, it's using a new instance of the `Request`  object, which is scuppering my ability to rely on changes made to the request that I'm hoping to work with in my `Resource` object.

### Steps To Reproduce:
In Lumen, type-hint the `Request` into a controller, modify some input, and return a `Resource` object.

```
// Controller method
public function index(Request $request)
{
    $request->replace(['foo' => 'bar']);
    return new Resource(['test']);
}
```

Then modify `Resource::toArray()` to inspect the `$request` that's passed in and compare it with one from the Container, e.g.:

```
dd($request, Container::getInstance()->make('request'));
```

For this, my first one has an ID of `#167` and my second (the one I want) has an ID of `#104` - they are **not** the same instance. In my case this is very frustrating as the objects are clearly different as I have modified the request in my controller.

After some investigation, I found that it's because `\Laravel\Lumen\Concerns\RoutesRequests::prepareResponse()` is using `Request::capture()`, which is creating a new Request instance instead of reusing the existing container instance. What's the reasoning for this?

### Workaround
My workaround is to modify explicitly call `response()` from my controller, passing in the request:

```
public function index(Request $request)
{
    $request->replace(['foo' => 'bar']);
    return (new Resource(['test']))->response($request);
}
```

Possibly this is the desired behaviour, but I wasn't expecting it so it caught me out. Hopefully this helps someone else out.

**Comment by sisve** [comment]
I believe this repository is for laravel/framework, not laravel/lumen. Try using Slack to get hold of someone that can accept bug reports for laravel/lumen since https://github.com/laravel/lumen doesn't have issues enabled.

**Comment by simonhamp** [comment]
I’m sure this repository is just for Laravel, but as it’s the only repository in the whole stack that has Issues enabled, this felt like the most appropriate place.

I haven’t been able to get much conversation out of anyone on the Lumen channel in Slack before and it’s not really the place to make this sort of issue publicly available.

If @taylorottwell wants to open up Issues in Lumen, I’d be happy to field some.

**Comment by laurencei** [comment]
There is a Lumen Framework Github page with issues here: https://github.com/laravel/lumen-framework

**Comment by simonhamp** [comment]
Thanks @laurenceci! I’ll repost there.
