### ISSUE TITLE
[5.5] Api requests use SessionGuard instead of TokenGuard

### ISSUE THREAD

**Issue by KonstantinKolodnitsky** [laravel/framework#22573]
- Laravel Version: 5.5.28
- PHP Version: 7.1.12
- Database Driver & Version: mysql:5.7.16

### Description:
The method `resolveRequestSignature` in the `ThrottleRequests` was completely rebuild in v5.5 and now it calls `$request->user()` without a `$guard` argument. So any api call is using default guard which is `web` (SessionGuard). This causes `Unauthorized` error.

### Steps To Reproduce:
1. Given a `test` route exists within the api middleware group.
2. And ApiTestController::test() method exists.
3. When I do AJAX request the endpoint `http://mysite.com/api/test?api_token=mytoken` from frontend.
4. I'm getting 'Unauthorized' response.

**Comment by rs-sliske** [comment]
assuming default RouteServiceProvider, i think api routes have an api/ prefix, so the url would be http://mysite.com/api/test?api_token=mytoken

is your route defined in your web routes file?

**Comment by KonstantinKolodnitsky** [comment]
@rs-sliske  Sorry. Url is corrected.
No. The route is defined in the `routes/api.php` and there is no duplication in `web.php`.

**Comment by Dylan-DPC** [comment]
Are you sure you are passing a valid token? What are you using for token authorisation? Something like Passport?

**Comment by KonstantinKolodnitsky** [comment]
@Dylan-DPC I don't use Passport. Just in-build functionality.
Yes. I'm using correct api token. I can successfully login with with the default web form and obtain api token.

**Comment by rs-sliske** [comment]
does your route have 'auth:api' middleware on it?

(i did have a problem recently with authorization on api endpoints but i cant remember exactly how i fixed it)

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
