### ISSUE TITLE
Running migration return " Syntax error or access violation: 1071 Specified key was t   oo long; max key length is 767 bytes" error

### ISSUE THREAD

**Issue by shirkerohit** [laravel/framework#22580]
- Laravel Version: 5.3.*
- PHP Version: 5.6.11
- Database Driver & Version: Mysql 14.14

### Description:
Running "php artisan migrate" result into creation of migrated table "Users" but throws exception 
 `Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
 `

### Steps To Reproduce:
1) create a new laravel project with "composer --create-project --prefer-dist laravel/laravel MySite"
( configure .env file for database connection)
2) run **" php artisan migrate"**

(Note: Though i have mentioned about 5.3.*  i tried this with laravel 5.4 and got the same error.)

**Comment by decadence** [comment]
https://laravel-news.com/laravel-5-4-key-too-long-error
First link in Google

**Comment by shirkerohit** [comment]
Thanks.. i guess it should have been there in docs as comment or something...#closed

**Comment by devcircus** [comment]
In the docs under [migrations / indexes](https://laravel.com/docs/5.5/migrations#indexes)
