### ISSUE TITLE
Add "author" attribute to SlackAttachment

### ISSUE THREAD

**Issue by gentisaliu** [laravel/framework#22588]
- Laravel Version: 5.5.28
- PHP Version: 7.0.21
- Database Driver & Version:

### Description:
The _author name_ field seems to be missing in `Illuminate\Notifications\Messages\SlackAttachment`. This is supported by Slack though, see https://api.slack.com/docs/message-attachments . 

Or am I missing something, i.e. there is another way to do this?

**Comment by Dylan-DPC** [comment]
Hi this repo is for bug tracking. 

If you need help with this, you can consult the forums or the slack channel.
Or if you want the change made in the code, you can go ahead and submit a PR

**Comment by gentisaliu** [comment]
Huh? What a weird response and even weirder that the issue is closed. Thanks, I guess.

**Comment by GrahamCampbell** [comment]
Sorry about that @gentisaliu. Thanks for the report.

**Comment by gentisaliu** [comment]
Will submit a PR soon - I'm a bit busy at the moment porting a project to Laravel.

**Comment by kevdotbadger** [comment]
@GrahamCampbell  This can be closed.

**Comment by GrahamCampbell** [comment]
🍻
