### ISSUE TITLE
is there any hope to make str::slug supports all languages? 

### ISSUE THREAD

**Issue by Abu3safeer** [laravel/framework#22592]
- Laravel Version: 5.5
- PHP Version:7.2
- Database Driver & Version:....

### Description:
is there anyway to get sstr::slug or str_slug() to work with characters other than English?
I tried Chinese, Japanese, Arabic.
in case of  Chinese and Japanese nothing appear, in Arabic the letters get converted into English.

will laravel support it? 
### Steps To Reproduce:
str_slug('Slug goes here');

P.S: by the way, laravel-sluggable uses str_slug, so you get the same result, I tried that myself before posting here.

**Comment by mfn** [comment]
Please only use this for reporting bugs. If you want to discuss changes, please open an issue at https://github.com/laravel/internals/issues

**Comment by GrahamCampbell** [comment]
Internals is definitely the best place for this question. I suspect the answer is no though.
