### ISSUE TITLE
Accessor

### ISSUE THREAD

**Issue by hamid09430** [laravel/framework#22590]
- Laravel Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
Hi
i want to know that when $snake_attribute is false and we have write a accessor for like Parent_id that will be getParentIdAttribute() then why this fuction does not get called for such records where parent_id is null.
i mean if the 1st record in DB have the parent_id 5 then accessor will be executed but if parent_id holds null then accessor is not called and returned null.

however if snake_case is true then it called for both cases NULL and Values case.

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
