### ISSUE TITLE
key:generate fails silently

### ISSUE THREAD

**Issue by szepeviktor** [laravel/framework#22602]
When someone starts from git with an empty `.env` file

```bash
git clone -b v5.5.22 https://github.com/laravel/laravel.git laravel
cd laravel
composer update --no-dev
touch .env
php artisan key:generate
```

`key:generate` reports success and fails silently as APP_KEY is not present.

https://github.com/laravel/framework/blob/bd352a0d2ca93775fce8ef02365b03fc4fb8cbb0/src/Illuminate/Foundation/Console/KeyGenerateCommand.php#L95

Laravel Version: 5.5.22

Please advise.

**Comment by laurencei** [comment]
You should be running `composer create-project laravel/laravel laravel` - and that will run all the required post setup.

If you have any further issues - can I please suggestion closing your issue ticket here. Instead trying asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.

**Comment by szepeviktor** [comment]
@laurencei Thank you.

I'd like to have a check whether `APP_KEY` exists in .env

Is it a valid request?

**Comment by jagadeshanh** [comment]
When you 

```touch .env``` Laravel doesn't know where to put the key since ```APP_KEY``` is not present

try

```cp .env.example .env```
```php artisan key:generate```

**Comment by szepeviktor** [comment]
Yes I know that.

I've opened this issues as Laravel:

- blindly changes APP_KEY
- and does not report a failure

**Comment by Dylan-DPC** [comment]
refer: https://github.com/laravel/framework/pull/22304

**Comment by szepeviktor** [comment]
Thank you.

**Comment by szepeviktor** [comment]
Duplicate of #20719
