### ISSUE TITLE
Psr UploadFile Message - Validation

### ISSUE THREAD

**Issue by lpj145** [laravel/framework#22614]
- Laravel Version: 5.x
- PHP Version: 7.x

### Description:
On this file https://github.com/illuminate/validation/blob/33c642b752ac764b41c91f248830f5f474932269/Concerns/ValidatesAttributes.php#L1420 have problem if add OR condition with UploadFileInterface psr http message ? i can launch pr.

**Comment by jmarcher** [comment]
Can you elaborate more? What is the problem you are having?

**Comment by lpj145** [comment]
i'm using this package outside laravel, when i upload file and validate it, this compare with uploadfile laravel and File by symfony, but i have file by uploadfileinterface [This psr](https://github.com/php-fig/http-message/blob/master/src/UploadedFileInterface.php)

**Comment by jmarcher** [comment]
I do not see how this relates to Laravel, if you are using that interface better customize the Validation for your needs

**Comment by lpj145** [comment]
yes i make it, if not see, okay, bye!
