### ISSUE TITLE
chaining Artisan::call() swallows error

### ISSUE THREAD

**Issue by challet** [laravel/framework#22629]
- Laravel Version: 5.5.28
- PHP Version:  7.1.4
- Database Driver & Version: n/a

### Description:

If an artisan command is programmatically called, calls an other command and then raise an error, this error is not displayed.

### Steps To Reproduce:

```php
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class Error extends Command
{
    protected $signature = 'error';
    protected $description = 'Trigger an error';
    
    public function handle()
    {
        \Artisan::call('dumb');
        trigger_error('fail', E_USER_ERROR);
    }
}

class Dumb extends Command
{
    protected $signature = 'dumb';
    protected $description = 'Command description';

    public function handle()
    {
    }
}

// from somewhere else
var_dump(\Artisan::call('error'));
var_dump(\Artisan::output());
```

### Explanation

It is due to the fact that : 
* `App\Console\Kernel` is registered as a singleton : https://github.com/laravel/laravel/blob/master/bootstrap/app.php#L34
* It keeps one instance of `Illuminate\Console\Application` in cache (singleton as well) : https://github.com/laravel/framework/blob/5.5/src/Illuminate/Foundation/Console/Kernel.php#L313
* The *catchExceptions* flag is then shared for both `Artisan::call`s : https://github.com/symfony/console/blob/master/Application.php#L309
* It is reseted to true when the second command finished but while the first one is still running : https://github.com/laravel/framework/blob/5.5/src/Illuminate/Console/Application.php#L175..L179
* Any error raised after will be caught : https://github.com/symfony/console/blob/master/Application.php#L106 and https://github.com/symfony/console/blob/master/Application.php#L145

### Additional infos : 
* the return value of erroring Artisan::call is still `1`
* there is no buffered output from `Artisan::ouptut()`, while it looks there is [a render operation](https://github.com/symfony/console/blob/master/Application.php#L149)
* if the second call is `$this->call('dumb')` instead of `Artisan::call('dumb')` it works as expected

### Fix suggestion : 
Always create a new instance of `Illuminate\Console\Application` [here](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Foundation/Console/Kernel.php#L313)

**Comment by themsaid** [comment]
feel free to open a PR.
