### ISSUE TITLE
Merging an empty eloquent collection with a non-empty illuminate collection throws an exception

### ISSUE THREAD

**Issue by ventrec** [laravel/framework#22626]
- Laravel Version: 5.5.22
- PHP Version: 7.1.7
- Database Driver & Version: MySQL 5.7.19

### Description:
If you try to merge an empty eloquent collection with a non-empty illuminate collection, laravel throws a `FatalThrowableError` exception with the message `Call to a member function getKey() on array`. This issue is similar to #19784.

A workaround for this is to pipe `->toBase()` at the end of the eloquent collection, but that shouldn't really be necessary.

### Steps To Reproduce:

1. Run a query that returns an empty collection.

```php
$users = User::whereFirstname('LaraBoy')->get(['id']);
```

2. Create a basic collection with some values

```php
$values = collect([1, 2, 3]);
```

3. Merge both collections and watch your app die while you pull your hair

```php
$users->merge($values);
```

**Comment by devcircus** [comment]
IMO I believe the comment by @themsaid is applicable in this case as well. Maintaining an eloquent collection doesn't make sense at this point. Seems reasonable to call ```toBase()```.

Also, just tested in tinker. It doesn't matter if the collection is empty or not. You'll get the same error.
```php
$users = App\Models\User::get(['id']);
$values = collect([1,2,3]);
$users->merge($values);

//PHP Error:  Call to a member function getKey() on integer in /mnt/c/.......
```

**Comment by thiagorb** [comment]
In my opinion this request is valid. Does it make sense for `get` to return an Eloquent Collection then? Why not to make `get`/`map` to return base Collection?
