### ISSUE TITLE
Php artisan schedule:run not work when remove .env file

### ISSUE THREAD

**Issue by wingadium1** [laravel/framework#22624]
- Laravel Version: 5.4
- PHP Version: 7.1
- AWS Beanstalk 64bit Amazon Linux 2017.09 v2.6.1 

I use AWS Elasticbeanstalk to deploy Laravel App.
I do not use .env file in Environment but I use Elastic Beanstalk Environment Properties to set Env variable via $_SERVER.

I modified my database.php a little bit for load DB_HOST, DB_PORT, etc from $_SERVER instead of env file
=> It works

But when I tried to implement an scheduler, It seems use .env file to get DB_HOST, DB_PORT, etc, and it failed to run scheduler.

Do you have any suggestion for me?

**Comment by sisve** [comment]
Yes. Provide actual error descriptions, not "it failed to run scheduler". My second suggestion is to not do this. This isn't a default Laravel setup, and you'll have problems, and you'll have problems finding help for your problems.

Why are you going via $_SERVER when EBS supports environment variables that should work with the default setup?

**Comment by wingadium1** [comment]
Thank for your support.

with EBS, I follow the guide of Amazon and set value for EBS Environment Properties and get via `$_SERVER` or `get_cfg_var` function in [PHP Guide](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_PHP.container.html).

I am newbie with Laravel and do not know the best practice of setting of environment variable in EBS. Could you provide me any suggestion?

Anw, In my case, get_cfg_var function is work with **artisan schedule**, It seems strange when not work with $_SERVER variable.

**Comment by sisve** [comment]
Why are you talking about get_cfg_var? That reads from php.ini, not the environment variables.

Can you provide an exception message and stack trace for the problem you're attempting to report?

**Comment by sisve** [comment]
Have you tried following AWS guide on installing Laravel on EBS? https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/php-laravel-tutorial.html

**Comment by sisve** [comment]
Also, upgrade to Laravel 5.5 and see if the problem persists. If it does, give us an actual error report and how we can reproduce the problem from a newly installed Laravel version. So far this sounds like a forum post where you are asking for help, and not a bug report.

**Comment by gmsantos** [comment]
Just use `env()` to load from environment vars in AWS Beanstalk and don't deploy your .env.

No need to use $_SERVER directly after all.

**Comment by wingadium1** [comment]
@sisve Yes, basically I tried following that guide

**Comment by wingadium1** [comment]
@gmsantos  I just follow the guide of AWS. But as you mention about `env()`, it sounds good, I tried to use the method.

Thank you!
