### ISSUE TITLE
Unsupported use of @php?

### ISSUE THREAD

**Issue by collegeman** [laravel/framework#22621]
In my exploration of the Sage WordPress Starter Theme—a WordPress project that borrows much from Laravel, including introducing Blade as a dependency—I have found an interesting problem. I'm reporting it as a bug instead of a pull request only because I can't think of an easy way to solve the problem, and I'm hoping the community might.

The problem arises from the following (potentially unsupported use case) of the `@php` directive. Consider the following script:

```
<html @php(language_attributes())>
<head>
  <title>
    @php
       $someArbitraryThing = 'whatever';
       echo $someArbitraryThing;
    @endphp
  </title>
</head>
<body></body>
</html>
```

When compiling the above, the Blade engine produces something like the following:

```
<html <?php(language_attributes())>
<head>
  <title>
    @php
       $someArbitraryThing = 'whatever';
       echo $someArbitraryThing;
    @endphp
  </title>
</head>
<body></body>
</html>
```
Instead of what was expected, e.g.,

```
<html <?php (language_attributes()); ?>>
<head>
  <title>
    <?php $someArbitraryThing = 'whatever';
       echo $someArbitraryThing;
     ?>
  </title>
</head>
<body></body>
</html>
```

I have discovered that this is caused by the regular expression in [`BladeCompiler::storePhpBlocks`](https://github.com/laravel/framework/blob/42fb24849b712d30f862be31b67d11165fb954d6/src/Illuminate/View/Compilers/BladeCompiler.php#L208), which is used to collect all of the template content inside each section of `@php` to `@endphp`, including sections that span multiple lines of the template.

So the conflict seems to be that if one uses the single-tag form of the `@php` directive anywhere in a template, one cannot also use the open/close form of the `@php` directive anywhere thereafter in the same template. 

It's entirely possible that `@php` shouldn't be used in a single-tag form—the Laravel documentation does not say it can be used this way, though it does work, so long as no `@endphp` appears in the same template. Maybe instead of this single-tag form, folks should simply use something like `{!! functionCall() !!}` instead?

**Comment by devcircus** [comment]
According to the 5.5 upgrade guide, the inline syntax is no longer supported.  See below:

> @php Blade Directive
The @php blade directive no longer accepts inline tags. Instead, use the full form of the directive:
```
@php
    $teamMember = true;
@endphp
```

**Comment by mul14** [comment]
I believe they change `@php` Blade directive behaviour because of this https://github.com/laravel/framework/pull/20065

**Comment by collegeman** [comment]
@devcircus, @mul14, and @GrahamCampbell: thank you all for the time you spent on this. It was exactly the confirmation I needed.

**Comment by ameenross** [comment]
I found the mention of "inline tags" in the upgrade guide vague, so I googled it and landed here. So I tested this snippet, but it seems that the behavior changed again?

```psysh
>>> Blade::compileString('@php(1+2+3) {{$bar}} @php(4+5)')
=> "<?php (1+2+3); ?> <?php echo e($bar); ?> <?php (4+5); ?>"
```

**Comment by ameenross** [comment]
Ok, hold on. It seems the behavior wasn't changed, it's just unpredictable:

```psysh
>>> Blade::compileString('@php(echo"foo") @php print"bar"; @endphp')
=> "<?php(echo"foo") @php print"bar"; ?>"
```

Apparently, when you have an `@endphp` in your code, no `?>` will be added after the closing parentheses. So combining `@php()` with `@php $expr + $ession; @endphp` is problematic

**Comment by mirafzal** [comment]
regex replace:
