### ISSUE TITLE
Validation max file size doesn't work correctly with my validator

### ISSUE THREAD

**Issue by stephanebressani** [laravel/framework#22622]
- Laravel Version: 5.5
- PHP Version: 7
- Database Driver & Version: Mysql or Sqlite (not important for this ?)

### Description:

Hello, I have a problem with message of validation after uploading a file too large

### Steps To Reproduce:

MyRequest
```
'fichier' => 'required|file:1|max:500000|mimes:jpeg,bmp,png,gif'
```

I have this message with a file larger than 5mo
```
'uploaded' => "Le fichier du champ :attribute n'a pu être téléversé.",
# (sorry I have deleted the English file and I don't find it in vendor/caouecs/laravel-lang)
```

but I will obtain this message:
```
'max' => [
        'file'    => 'La taille du fichier de :attribute ne peut pas dépasser :max kilo-octets.',
]
```

and with
```
'fichier' => 'required|file:1|size:500000|mimes:jpeg,bmp,png,gif'
```
I have
```
'size' => [
   'file'    => 'La taille du fichier de :attribute doit être de :size kilo-octets.',
]
```
but I don't want the exact size, I search to obtain max limit size

thanks !

**Comment by pavinthan** [comment]
file size should be in KB

**Comment by stephanebressani** [comment]
with
```
'fichier' => 'required|file:1|max:5000kb|mimes:jpeg,bmp,png,gif'
```
i have the same message
```
'uploaded' => "Le fichier du champ :attribute n'a pu être téléversé.",
```

**Comment by pavinthan** [comment]
no need KB just
`'fichier' => 'required|file:1|max:5000|mimes:jpeg,bmp,png,gif'`

**Comment by pavinthan** [comment]
@stephanebressani please use close this issue and use [larachat.slack.com](https://larachat.slack.com/) or [laracasts.com/discuss](https://laracasts.com/discuss) to fix this

**Comment by stephanebressani** [comment]
It's doesn't work
```
'fichier' => 'required|file:1|max:5000|mimes:jpeg,bmp,png,gif'
```
i have this message
```
'uploaded' => "Le fichier du champ :attribute n'a pu être téléversé.",
```

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.

**Comment by stephanebressani** [comment]
i solved it with:
```
    public function messages() 
    {
        return [
            'fichier.uploaded' => trans('custom_validation.image_5_mo')
        ];
    }
```
in request php file
