### ISSUE TITLE
Wrong doc block for Filesystem@link

### ISSUE THREAD

**Issue by afraca** [laravel/framework#22646]
- Laravel Version: 5.5.27
- PHP Version: 7.0
- Database Driver & Version:

### Description:
The Filesystem method `link` found  [here](https://github.com/laravel/framework/blob/v5.5.27/src/Illuminate/Filesystem/Filesystem.php#L219) is confusing. It says (in the doc) it will create a **hard** link, but will in fact create a **soft** link, except on Windows. I do not know enough about windows links to tell how this will behave there, but it still is confusing. I think this should be clarified.

https://github.com/laravel/framework/blob/v5.5.27/src/Illuminate/Filesystem/Filesystem.php#L219-L234

edit: I previously opened up a thread in laravel/internals, but it's better suited here IMHO. See:
https://github.com/laravel/internals/issues/936

**Comment by themsaid** [comment]
feel free to open a PR.
