### ISSUE TITLE
Use API Resources to Notifications

### ISSUE THREAD

**Issue by BadTudou** [laravel/framework#22664]
- Laravel Version: **5.5**
- PHP Version: **PHP 7.1.7 (cli) (built: Jul 15 2017 18:08:09) ( NTS )**
- Database Driver & Version: ** SQLite version 3.19.3 2017-06-27 16:48:08**
- OS: **macOS High Sierra 10.13.2**

### Description:

When i use API Resources to Notifications.

**Model**:
```
namespace App;

use Illuminate\Database\Eloquent\Model;
class Notification extends Model
{

    protected $table = 'notifications';

}
```

**Resource**:
```

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\ResourceCollection;

class SystemNotificationCollection extends ResourceCollection
{
    public function toArray($request)
    {
        return [
            'data' => $this->collection,
            'links' => [
                'self' => 'link-value',
            ],
        ];
    }
}
```

**Controller**:
```
public function index(Request $request)
    {
        return new SystemNotificationCollection( Notification::where('type', SystemNotification::class)->paginate());
    }
```

**Database**:

![image](https://user-images.githubusercontent.com/4954182/34637548-0209f11e-f2f4-11e7-83ae-4df8a1c6c7d9.png)

**Result**:
![image](https://user-images.githubusercontent.com/4954182/34637615-e769b0be-f2f4-11e7-9f70-f4748a35bafa.png)

**Transform**:
**e58f93d1-1c44-4271-8381-0f927b7bdda4** -> **0**

**20d91d78-0075-4e6e-b7db-ec8fabe1e130** -> **20**

**The conversion process is :** `(int)id` ?

I add below code to the Model:
```
    public function getIdAttribute($value)
    {
        return $this->attributes['id'];
    }
```
That's ok:
![image](https://user-images.githubusercontent.com/4954182/34637666-212089f8-f2f6-11e7-8d72-06c631bbb14c.png)

It's a bug ?

**Comment by victorlap** [comment]
Try settings `public $incrementing = false;` in your Model file
