### ISSUE TITLE
Multi databases

### ISSUE THREAD

**Issue by airtonct** [laravel/framework#22670]
Hi, I'm trying to make a laravel use using multiple databases:
- Laravel version: 5.5.28
- Php Version 7.2.0
- Database Driver & version: MariaDB 10.1.29

Define Connections:
```
return array(

    'default' => 'mysql',

    'connections' => array(

        # Primary/Default database connection
        'mysql' => array(
            'driver'    => 'mysql',
            'host'      => 'localhost',
            'database'  => 'bdd1',
            'username'  => 'root',
            'password'  => ''
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
        ),

        # Secondary database connection
        'mysql2' => array(
            'driver'    => 'mysql',
            'host'      => 'localhost',
            'database'  => 'bdd2',
            'username'  => 'root',
            'password'  => ''
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
        ),
    ),
);
```
Define model:
```
class Products extends Model {

    protected $connection = 'mysql';

}
```
Define controller:
```
class ProductController extends BaseController {

    public function find()
    {
        $productModel= new Products;

        $productModel->setConnection('mysql2');

        $product= $productModel->find(1);

        return $product;
    }

}
```
The code above works without error, but if I change the name of the connection in the controller it continues using what was configured in the .env file

Please, could anyone help me solve this problem?

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this github area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I please suggestion closing your issue ticket here. Instead trying asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.
