### ISSUE TITLE
Route group nesting 

### ISSUE THREAD

**Issue by Epistol** [laravel/framework#22678]
- Laravel Version: 5.5.0
- PHP Version: 7.0
- Database Driver:  Mysql

### Description:

I was trying to bind my route to a Controller action, stacked in a sub-subgroup, and encountered a bug : 

### Steps To Reproduce:

In route/web.php

```
Route::group(['prefix' => 'something'], function () {

    Route::group(['prefix' => 'anotherthing'], function () {
        Route::get('/','Folder\TypeController@index')->name("type.index");
    });
});
```

The app return : 

> Cannot declare class App\Http\Controllers\TypeController, because the name is already in use

But in fact, it doesn't, and it's still in my folder Controllers\Folder\TypeController.php.

I tried to clear cache and composer dumpautoload of course, but nothing seems to happen. Tried with a fresh install, had the same problem.

**Comment by sisve** [comment]
The error message has nothing to do with routing. You have at least two controllers called App\Http\Controllers\TypeController in the same namespace. You have probably copy/pasted this file and forgot to change the class name in the new file.

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue

**Comment by Epistol** [comment]
@sisve Nop, only have one file TypeController, right named, no double.

**Comment by Epistol** [comment]
I forgot to edit the namespace
