### ISSUE TITLE
(BUG)Redis Facades ignore the timeout param(Redis::set)

### ISSUE THREAD

**Issue by iamHXQ** [laravel/framework#22682]
- Laravel Version: 5.5
- PHP Version:7.1.7
- Database Driver & Version:

#### Redis Facades ignore the timeout param,

`Redis::set('testKey','testValue',60);`
###### as same as
`Redis::set('testKey','testValue');`

**Comment by iamHXQ** [comment]
I'm using phpredis as redis driver

**Comment by gmsantos** [comment]
`Redis::set` doesn't accept expire. use `setex` instead.
