### ISSUE TITLE
artisan migrate:fresh does not drop tables on all connections

### ISSUE THREAD

**Issue by Tlapi** [laravel/framework#22681]
- Laravel Version: 5.5.27
- PHP Version: 7.1.12
- Database Driver & Version:

### Description:

Using more than one connections / databases, migrate:fresh command drops tables only on one connection / database resulting into error of "Base table or view already exists"

### Steps To Reproduce:

Set up two connections and create two migrations. One on each connection like so:
```
Schema::connection('one')->create('first_table'...
```
```
Schema::connection('two')->create('second_table'...
```

Run `artisan migrate:fresh` two times.

**Comment by laurencei** [comment]
You should be able to do `artisan migrate:fresh --database=two`?

**Comment by Tlapi** [comment]
Yes, but then this does not work for example in tests, with RefreshDatabase trait.

This should work moreover the same way as `artisan migrate` right? This handles also all connections regardless if you specify the database.

**Comment by laurencei** [comment]
`artisan migrate` works because the connection is explicity defined as in use on the way `up` and `down` via your models and migrations.

`artisan fresh` only drops the DB table itself - so there is no way to know which connections to use (other than default).

**Comment by Tlapi** [comment]
Got it. Wouldn't it be better if `artisan fresh` would drop tables based on `down` in migrations?

**Comment by laurencei** [comment]
No - the *whole* point is you dont need to write any `down` migrations.

If you want to use `down` migrations - then just run `artisan:refresh`

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.

**Comment by MyFriendlyUserName** [comment]
@themsaid But how to solve the issue when running tests? In `vendor/laravel/framework/src/Illuminate/Foundation/Testing/RefreshDatabase.php` there is just a call of `migrate:fresh`:

```
protected function refreshTestDatabase()
    {
        if (! RefreshDatabaseState::$migrated) {
            $this->artisan('migrate:fresh');

            $this->app[Kernel::class]->setArtisan(null);

            RefreshDatabaseState::$migrated = true;
        }

        $this->beginDatabaseTransaction();
    }
```

From my pov - for testing - all databases should be refreshed.

**Comment by laurencei** [comment]
@MyFriendlyUserName - the problem is it is impossible to know which databases should be refreshed after each test. 

And normally during a test you would just use the one connection anyway, there is little gained by using multiple databases.

At the end of the day, the `refreshTestDatabase` is just a "helper". You can write your own version that cycles through 2-3 different connections and add that to your `TestCase.php` setUp function.
