### ISSUE TITLE
Can I use phpredis instead of predis in laravel project?

### ISSUE THREAD

**Issue by yasinugurbelek** [laravel/framework#22685]
I use predis in Laravel project. I want to switch to phpredis because the project has gotten a lot of traffic. I am currently using predis with Illuminate \ Redis. Will there be a performance difference between Predis and PHPRedis? Do I need to use another driver instead of predis in conjunction with phpredis in a laravel project? Do I have to use predis when using phpredis?

Any ideas? Thanks!

- Laravel Version: 5.1
- PHP Version: 7.1

**Comment by mkingbe** [comment]
@yasinugurbelek try https://laracasts.com/discuss, is a great place for discussion.

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue
