### ISSUE TITLE
Iluminate/Support v5.4.* not compatible with PHP 5.6

### ISSUE THREAD

**Issue by ghunti** [laravel/framework#22690]
- Laravel Version: ?
- PHP Version: 5.6
- Database Driver & Version:

### Description:
Illuminate/Support v 5.4.* requires "doctrine/inflector": "~1.1" and PHP >=5.6.4
doctrine/inflector v1.2 now requires PHP ^7.0 so there's currently no way to install Iluminate/Support under PHP 5.6!

**Comment by mputkowski** [comment]
Why you use 1.2 if composer requires 1.1?

By the way, 5.4 isn't longer supported.

**Comment by ghunti** [comment]
I don't use 1.2, the problem is that if you require ~1.1 it will bring 1.2 if its available

**Comment by sisve** [comment]
That's not true. ~1.1 should resolve to 1.1 if 1.2 ends up being invalid for your configuration.

**Comment by ghunti** [comment]
Hi @sisve 
You pointed me in an interesting direction.
I use a composer.lock that is created in my machine which runs a docker container with composer.
I think the issue is that the container has PHP 7 hence, when I run ```composer update``` locally it creates a ```composer.lock``` file that will have dependencies that are not compatible with my staging environment which runs PHP 5.6!

Will check and report back.

**Comment by devcircus** [comment]
Usually that is indeed what is happening in these cases.

**Comment by ghunti** [comment]
Yep. The problem was solved by adding to the composer.json the following:
```
    "config": {
        "platform": {
            "php": "5.6.23"
        }
    }
```
Learned something today ;)
Sorry for the trouble guys
