### ISSUE TITLE
ProcessUtils wrong namespace

### ISSUE THREAD

**Issue by elena-roman** [laravel/framework#22697]
Hello after doing a composer update, i get this error when a scheduled command was trying to run:

[2018-01-09 11:14:01] lumen.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Illuminate\Support\ProcessUtils' not found in /srv/www/api/vendor/illuminate/console/Application.php:104

Required plugins:

"require": {
        "laravel/lumen-framework": "5.5.*",
        "illuminate/support" : "5.5.2",
        "illuminate/session": "^5.5",
        "itsgoingd/clockwork": "~1.14",
        "pathwwway/riverplay": "dev-master",
        "pathwwway/bingo": "dev-master",
        "pathwwway/auth": "dev-master",
        "pathwwway/cms": "dev-rvp",
        "pathwwway/common": "dev-rvp",
        "cocur/slugify": "^3.0",
        "guzzlehttp/guzzle": "^6.2",
        "vlucas/phpdotenv": "~2.2",
        "rcrowe/twigbridge": "^0.9.4",
        "appzcoder/lumen-routes-list": "^1.0"
    },

The solution was to replace 
Illuminate\Support\ProcessUtils with Symfony\Component\Process\ProcessUtils
in 
illuminate/console/Scheduling/CommandBuilder.php
illuminate/queue/Listener.php
illuminate/console/Application.php 

**But is there another way to do this?**

**Comment by mfn** [comment]
I think your problem is ` "illuminate/support" : "5.5.2",`

The problem with the class you have is in the `\Illuminate\Support\` namespace => `\Illuminate\Support\ProcessUtils`.

You need to update this as well IMO.
