### ISSUE TITLE
2 tests not passing

### ISSUE THREAD

**Issue by mnabialek** [laravel/framework#22705]
I'm testing Laravel 5.6 in Laravel homestead however 2 tests are not passing:

> 1) Illuminate\Tests\Filesystem\FilesystemTest::testIsReadable
> Failed asserting that true is false.
> 
> /home/vagrant/code/laravel-framework/tests/Filesystem/FilesystemTest.php:313
> 
> 2) Illuminate\Tests\Validation\ValidationValidatorTest::testValidateActiveUrl
> Failed asserting that false is true.
> 
> /home/vagrant/code/laravel-framework/tests/Validation/ValidationValidatorTest.php:1996

I'm using MacOS as host. Is it normal that tests don't pass or maybe something should be altered in my system to make them work?

**Comment by laurencei** [comment]
I have had these errors in homestead forever when running the framework test suite on Windows 10 + Homestead.

I dug into it at the time, and from memory it was something about virtual file mounts or something, so I've always just ignored them.

**Comment by Dylan-DPC** [comment]
You can verify this by checking if CI has passed or not.

**Comment by mnabialek** [comment]
Yes, I know in Travis they work, but it's not too comfortable when you run tests locally and they fail without good reason.

**Comment by devcircus** [comment]
Is this something homestead could fix?

**Comment by laurencei** [comment]
I'll have another dig around later. From memory it was a deeper issue with Vagrant and the way file system mounts work (i.e. it wasnt a homestead bug).

**Comment by themsaid** [comment]
Closing since it's not a bug in the framework.
