### ISSUE TITLE
Use Queueable not executing immediately on Laravel 5.5 Notifications

### ISSUE THREAD

**Issue by oluomotoso** [laravel/framework#22700]
- Laravel Version: 5.5.*
- PHP Version: 7.1
- Database Driver & Version: Mysql

### Description:
I have a laravel application that send notifications to users based on certain events. I use Beanstalked with 10 workers and I have 3 queue connections with priority set as high,medium,low where the low is the default connection.

I noticed that anytime a notification is sent, it take minutes or even hours before it eventually get processed. 

Even when any of the queue is not busy.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this github area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I please suggestion closing your issue ticket here. Instead trying asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.
