### ISSUE TITLE
laravel 5.5 model addHidden 

### ISSUE THREAD

**Issue by xuzili1993** [laravel/framework#22711]
- Laravel Version: 5.5
- PHP Version:
- Database Driver & Version:

### Description:
````
 $user = User::find(1);
 $userBasicInfo = $user->addHidden($basicInfoHiddenFields);
 //  return null

$userBasicInfo = $user->setHidden(array_merge($user->getHidden(), $basicInfoHiddenFields));
 // this is ok.
dump($userBasicInfo);
````

**Comment by xuzili1993** [comment]
change title

**Comment by sisve** [comment]
Are you attempting to file a bug report? Or request a new feature?

**Comment by xuzili1993** [comment]
request a new feature

**Comment by sisve** [comment]
We process requests for new features at https://github.com/laravel/internals. This repository is for bug reports for existing code. Close down this issue and open a new one in the internals repo.
