### ISSUE TITLE
hash_equals(): Expected known_string to be a string, boolean given

### ISSUE THREAD

**Issue by scottlaurent** [laravel/framework#22717]
- Laravel Version: 5.5.28
- PHP Version: 7.1
- Database Driver & Version: mySQL

### Description:
we updated clients to 7.1/5.5 this last week and every one of them are reporting intermittent "hash_equals(): Expected known_string to be a string, boolean given" << this is occurring on about 1/2% of all traffic across all platforms.

### Steps To Reproduce:
This occurs only on site that were upgraded from 5.4 to 5.5 and PHP 7.1  -- It occurs when the computer is left on long enough for the cookie to expire.  Refreshing doesn't resolve this issue.

### How we fixed it (for now)
vendor/laravel/framework/src/Illuminate/Auth/EloquentUserProvider.php
Line 78 replaced with this: $rememberToken = (string) $model->getRememberToken();

It appears like somehow a bool(true) was getting to this point.  Our db is string, and no db changes were made prior to the upgrade.

**Comment by scottlaurent** [comment]
Not sure how I didn't see your topic.  I had actually been searching for a fix.

**Comment by mnabialek** [comment]
@scottlaurent I've added this after you added this issue. However it seems quite strange remember token is boolean for you. Are you sure you have everything set in valid way? Normally it should return string, are you sure you don't have any custom accessors or casts set in your model?

**Comment by scottlaurent** [comment]
no.  we don't use casts on stuff laravel does natively (created_at, remeber_token, etc).  its just default.  in fact, i don't think we have ever even touched that field in any of our apps.

**Comment by themsaid** [comment]
fixed in https://github.com/laravel/framework/pull/22724
