### ISSUE TITLE
array_add() can't work with values which contain a dot

### ISSUE THREAD

**Issue by Fossil01** [laravel/framework#22710]
- Laravel Version: 5.4.19
- PHP Version: 7.0
- Database Driver & Version: MariaDB 10

### Description:
When a value contains a dot the array is split up

### Steps To Reproduce:
```php
<?php

$a = [];
$x = array_add($a, $value->somevalue, "Some string");
dd($x);
?>
```

When $value->somevalue is for example "Company Name B.V" then a value is added to the array called "Company Name B" and under that another one called "V".

Is this by design? How do I prevent this?

**Comment by rs-sliske** [comment]
it is by design.
that method is to make it easier to work with nested arrays

if you are just working with one level you can do 

```
$a[ $value->somevalue ] = "Some string";
```
