### ISSUE TITLE
Illegal operator and value combination while launch route:list

### ISSUE THREAD

**Issue by alexeydemin** [laravel/framework#22719]
- Laravel Version: 5.5.28
- PHP Version: 7.0.26
- Database Driver & Version: n/a

I have the `Request` injection in the constructor of my `SomethingController`:

```
    public function __construct(Request $request)
    {
        $this->somethings = Something::where('weight', '>', $request->weight);
    }
```

web.php:
```
Route::get('something/{weight}', 'SomethingController@index');
```

It works fine unless I try to launch `php artisan route:list`.
There is no request in this case, so null goes to the `where()` function and `prepareValueAndOperator()` raises "Illegal operator and value combination" error.

**Comment by mnabialek** [comment]
This is normal. You shouldn't use this in your constructor and if you really have to, you could wrap it into 

    if (!app()->runningInConsole())

condition

**Comment by Dylan-DPC** [comment]
First of all, your constructor shouldn't be accepting a request as a parameter. 
Also, this issue board is for bug tracking. so if you need further help you can close the issue and head to the forums or the slack channel.
