### ISSUE TITLE
[5.5] Wrong docblocs

### ISSUE THREAD

**Issue by ionesculiviucristian** [laravel/framework#22715]
In `Illuminate/Cookie/CookieJar.php@forever` the `$value` parameter is set to `string` but is should be set as `mixed` as is can take arrays for example.

**Comment by jerguslejko** [comment]
It's better if you submit a PR for these kind of things.

**Comment by mputkowski** [comment]
According to [dockblock](https://github.com/symfony/symfony/blob/a97f8b7954ac1df0a72f767ab80bf676982bcf57/src/Symfony/Component/HttpFoundation/Cookie.php#L85) in Symfony, looks like everything is correct but it depends of point of view... if array is given it will be encoded to string and stored in cookie.

Just like @jerguslejko said, best option is to create PR and we'll see...
