### ISSUE TITLE
Why k/v pair '%25' => '%' is in UrlGenerator::$dontEncode property

### ISSUE THREAD

**Issue by fmfsaisai** [laravel/framework#22721]
- Laravel Version: 5.2.*
- PHP Version: 7.1.12
- Database Driver & Version: n/a

### Description:
In this PR:
[https://github.com/laravel/framework/pull/6546/files](https://github.com/laravel/framework/pull/6546/files
)
added this k/v pair to $dontEncode property:
```php
'%25' => '%',
```

### Steps To Reproduce:

So if I pass the params like this
```php
 $url = action('FooController@getBar', ['id' => '100%αфå']);
```

the $url will be:
```
http://www.example.com.com/foo/bar/100%%C3%A5%CE%B1%D1%84"
```
the **%%C3** double "**%**" character will Cause Nginx server error like this:
[https://en.wikipedia.org/wiki/%%C3](https://en.wikipedia.org/wiki/%%C3)

So the correct url should be (Which % should be encoded to %25)
```
http://www.example.com/foo/bar/%25%C3%A5%CE%B1%D1%84"
```
And correct wikipedia's
[https://en.wikipedia.org/wiki/%25%C3](https://en.wikipedia.org/wiki/%25%C3)

So why don't encode % character?
Can we remove  **'%25' => '%'** k/v pair from  $dontEncode property?

**Comment by sisve** [comment]
Looking at the code and your example, doesn't the value `test?test` also end up unescaped? And `test&test`?

The problem is that rawurlencode is executed on the entire url; but that doesn't make sense. You encode individual keys and values in the url, not the entire thing.

**Comment by fmfsaisai** [comment]
@sisve 
So I think that may have two ways to solve the double "**%%**" problem？


**one is:** 
the framework don't rawurldecode() the ROUTE PARAMS( in method replaceRouteParameters() ) part,But I do
```php
#the route is /foo/bar/{id} => FooController@getBar
$url = action('FooController@getBar', ['id' => rawurldecode('100%αфå')]);
``` 
**the other is:**
in method replaceRouteParameters(),execute rawurlencode() to encode the $parameters just like getRouteQueryString() do:
```
    protected function getRouteQueryString(array $parameters)
    {
        // First we will get all of the string parameters that are remaining after we
        // have replaced the route wildcards. We'll then build a query string from
        // these string parameters then use it as a starting point for the rest.
        if (count($parameters) == 0) {
            return '';
        }

        $query = http_build_query(
            $keyed = $this->getStringParameters($parameters)
        );
       .....
``` 
http_build_query() also do the encode operation like rawurlencode()

so I can safely use action() like this
```php
 $url = action('FooController@getBar', ['id' => '100%αфå']);
```
