### ISSUE TITLE
Eloquent Insert method cannot handle Json types insert

### ISSUE THREAD

**Issue by elbakly** [laravel/framework#22720]
- Laravel Version: 5.5.*
- PHP Version:7.2
- Database Driver & Version: Maria DB 

### Description:
When trying to make a bulk insert using Eloquent Insert() Method  while my fields are json its does not have the same effect as create it gives Array to string conversion instead. 

I'm using https://github.com/spatie/laravel-translatable

### Steps To Reproduce:

```php
    Excel::load($request->import->path(),function($reader)  {
            $result = $reader->all();
            $sheet1=$result[0];
           $create= $sheet1->map(function($row){
                return [
                    'word' => [
                        'en' => $row->word_en,
                        'ar' => $row->word_ar
                    ],
                    'meaning'=>[
                        'en'=>$row->meaning_en,
                        'ar'=>$row->meaning_ar
                    ],
                    'type'=>$row->type
                ];
            });
      //      dd($create->toArray());
            Glossary::insert($create->toArray());

        });
```

if you use create on a single row it works fine 
```php 
         Glossary::create($create->toArray()[0]);
```

**Comment by devcircus** [comment]
There's a lot of extracurricular, third party code at work here. Trim this down to show how to reproduce problem using only laravel core code.

**Comment by elbakly** [comment]
@devcircus  Here is much simpler version with only pure Laravel
    ```php 
                $data= [
              [
                    'word' => [
                        'en' => "hello",
                        'ar' => "hello_ar"
                    ],
                    'meaning'=>[
                        'en'=>"hello means Hi",
                        'ar'=>"hello still means hi"
                    ],
                    'type'=>'greetings'
                ],
               [
                    'word' => [
                        'en' => "world",
                        'ar' => "world_ar"
                    ],
                    'meaning'=>[
                        'en'=>"world means Everything and everyone",
                        'ar'=>"world means what ever"
                    ],
                    'type'=>'greetings'
                ]
];
            
     
            Glossary::insert($data);

        });
```

**Comment by mfn** [comment]
It was my impression you need to serialize them yourself.

`::insert()` is just column=>value, i.e. you need to `json_encode()` the `word` and `meaning` columns yourself.

Bulk insert doesn't use any of your Models setter. It's just raw insert.

An actual error message would have helped more, btw.

**Comment by elbakly** [comment]
@mfn I know how to bypass it, I just think that it should be updated, as I expected the ```insert()``` behaviour to be exactly as ```::create()```

**Comment by 36864** [comment]
Why do you expect a query builder method to be exactly the same as an eloquent\builder method with a different name and method signature?

**Comment by elbakly** [comment]
@36864 when I said exact behavior, I meant the input specifcally, I thought it would be clear from my question above. I still like that the insert method is builder method but we need a bulkCreate or   massCreate method were it would take the input as shown above

**Comment by themsaid** [comment]
You'll need to use create for that as it'll start reading your casts and apply it before using insert.
