### ISSUE TITLE
Is it better use first Error message in ValidateException instead of dead code "The given data was invalid"?

### ISSUE THREAD

**Issue by jianfengye** [laravel/framework#22743]
- Laravel Version: 5.5
- PHP Version:7.2
- Database Driver & Version:

### Description:
Is it better use first Error message in ValidateException instead of dead code "The given data was invalid";

In VlidateException.php， there is code:
```
public function __construct($validator, $response = null, $errorBag = 'default')
    {
        parent::__construct('The given data was invalid.');

        $this->response = $response;
        $this->errorBag = $errorBag;
        $this->validator = $validator;
    }
```
if i use that code in controller:
```
Validator::make($request->all(), [
            'phone' => 'required|unique:users|numeric',
            'code' => 'required|numeric',
        ],[
            'phone.unique' => "the user has been registered"
        ])->validate();
```
and the api will response exception:
```
{message: "The given data was invalid"}
```

Is it better to set Exception's message to $validator->errors()->first()?

because first error message is meanful and can be custom or localize, but "The given data was invalid" has no meaning

### Steps To Reproduce:

NONE

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. You can open a proposal in the laravel/internals repo

**Comment by jianfengye** [comment]
ok, i will close this issue, and open a proposal in the laravel/internals repo
