### ISSUE TITLE
[5.5] Resource how to set encode options?

### ISSUE THREAD

**Issue by seekcx** [laravel/framework#22750]
https://github.com/laravel/framework/blob/f7f6f1325dde96d2f46267e524291c9f0745ac01/src/Illuminate/Http/Resources/Json/ResourceResponse.php#L37-L44

#6528 Hope to merge this PR.

**Comment by seekcx** [comment]
Maybe should provide a config option?

**Comment by themsaid** [comment]
Please open a new issue with full details in the issue template including the laravel version and more detailed description of the issue.
