### ISSUE TITLE
 Potential issue with renamed array keys passed to nested includes

### ISSUE THREAD

**Issue by joakimunge** [laravel/framework#22751]
- Laravel Version: 5.5.26
- PHP Version: 7.1.10
- Database Driver & Version:

### Description:

Sending a data set with the same key, which then gets renamed (by new key name for the include) causes the data to become undefined when iterating over it.

I believe the issue occurs when referencing a key in an assoc. array with a new key.

### Steps To Reproduce:

In a Controller, pass two collections to a view through an associative array.
_(You can reproduce the error with just one collection, but for demonstration purposes I use two, due to how I discovered this)._

```php
return view('home', [
            'collectionOne' => $collectionOne,
            'collectionTwo' => $collectionTwo
]);
```

In this view (home.blade.php) include another view and pass the collections with a new key to loop through the collection. This is so we can use the same blade template to loop through different data sets.
```php
@include('includes.spotlight', ['spotlights' => $collectionOne])
@include('includes.spotlight', ['spotlights' => $collectionTwo])
```

In this view, loop through the collections
```php
@foreach($spotlights as $spotlight)
       {{ $spotlight->attribute }}
@endforeach
```

This should return an error:
```php
Undefined variable: $spotlights
```

Although the data in the collection can still be accessed with a dump. Even a dump inside the loop will return the desired data.
```php
dd($spotlights) // Collection
dd($spotlight) // Collection index 0
```

**Comment by themsaid** [comment]
I can't replicate this.

**Comment by joakimunge** [comment]
@themsaid No errors for you? Any way to further demonstrate the issue?

**Comment by themsaid** [comment]
Well let's see if anyone else can replicate the issue, I followed your exact steps and seems to be working fine, can you please test in a fresh laravel 5.5 app?

**Comment by joakimunge** [comment]
@themsaid I'll see if I can replicate it tomorrow in a fresh app.
