### ISSUE TITLE
Cache Database Driver not Following Database "Sticky" Setting

### ISSUE THREAD

**Issue by benyanke** [laravel/framework#22763]
- Laravel Version: 5.4
- PHP Version: 7.1.x
- Database Driver & Version: MySQL

### Description:

It appears the database driver for the cache is not obeying the database sticky setting (which points all reads on a given request to the write host if the session had any writes).

Using Elastic Beanstalk and an RDS backend, using the read replicas (which typically have a delay of about 20 ms), I have a section of code which ensures the cache is working on deploy. The following code fails for me whenever I'm using a read replica.

````php
      // Cache set above
    
      // Test delete
      Cache::forget($key);

      // Check to see if key was deleted successfully.
      if(!Cache::has($key)) {
        $deleteSuccess = true;
      } else {
        $deleteSuccess = false;   // This branch taken - not what is expected
      }
````

This test code does not show the key as deleted. However, if I add a sleep longer than the replication delay, it works as expected - which is why I assume this is a sticky issue.

Note that this issue does not show itself with a single DB server.

````php
      // Cache set above
    
      // Test delete
      Cache::forget($key);
      sleep(1);
      // Check to see if key was deleted successfully.
      if(!Cache::has($key)) {
        $deleteSuccess = true; // This branch taken - works as expected.
      } else {
        $deleteSuccess = false;      
      }
````

**Comment by laurencei** [comment]
You are running Laravel `5.4`.

I did the PR for sticky writes to Laravel `5.5`.

Try upgrading, then let me know if you have any issues.

**Comment by benyanke** [comment]
I don't have time to upgrade my whole app, but I may look at using your patch in the meantime. Do you have the PR number handy?

**Comment by laurencei** [comment]
Here it is: https://github.com/laravel/framework/pull/20445

**Comment by benyanke** [comment]
I am newer to laravel, but is there any chance it would get backported to the 5.4.x version, or is the sole answer to upgrade to 5.5? I can do some testing to get a PR for 5.4 if that is "a thing."

**Comment by laurencei** [comment]
It's up to Taylor - but I would suggest the odds are very low (almost zero).

`5.4` is EOL. `5.5` is current and also the LTS version.

The time you spend backporting the feature and testing it - you could just upgrade to `5.5`. It's a quick upgrade.

**Comment by benyanke** [comment]
Ok. I will look into upgrading when I have time.
