### ISSUE TITLE
Multiple Inheritance and Constructor Eloquent Issue.

### ISSUE THREAD

**Issue by chantrea999** [laravel/framework#22760]
I tried to created multiple inheritance using Laravel Framework. But look like save and update method is not working.

For example
use Illuminate\Database\Eloquent\Model;
use Auth;
abstract class MainModel extends Model
{
	protected $userid;
	public function __construct()
	{
		$this->userid = Auth::User()->id;
	}
}

class MyModel extends MainModel
{
	public function __construct()
	{
		parent::__construct();
	}
	// I be able to userid everywhere but the problem is eloquent Save and Update is not working.
}

Another Approach 
class MyModel extends Model
{
	private $userid;
	public function __construct()
	{
		$this->userid = Auth::User()->id;
	}
	//The same thing if I want to initialize something using constructor Eloquent Save and Update is not working.
}

Please let me know 

Thank you,

**Comment by Dylan-DPC** [comment]
This repo is for bug tracking. Use the forums or slack channel for solving your issue
