### ISSUE TITLE
Enhancing the with relationship (selective withTrashed)

### ISSUE THREAD

**Issue by GitzJoey** [laravel/framework#22771]
Just suggestion

Let say I have table with relationship one to many like so [ Category -> Product -> Unit ]
usually I do Category::with('product.unit') to retrieve all the relative data, 

what if i want to include withTrashed but only for the Unit table? 

i think with will be great if we can control like so
Category::with('Product')->withTrashed('Unit') 

thanks

**Comment by sisve** [comment]
Are you sure this isn't already possible with `Category::with('product.unit', function($q) { $q->withTrashed(); })`?

If that's not the case, and you want to suggest a new feature, use https://github.com/laravel/internals instead of this repository.

**Comment by GitzJoey** [comment]
hmm just realize we can do that (cant find in docs about this)
anyway I still dont know how if the one that get deleted is the middle one (in this case is Product)

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
