### ISSUE TITLE
Content-Type header is not is available from the api.php during testing, but works with Postman

### ISSUE THREAD

**Issue by Denis4yk** [laravel/framework#22778]
- Laravel Version: 5.5.28
- PHP Version: 7.1

### Description:

I have faced this problem, when I wanted to call different controllers based on the `CONTENT_TYPE` header.

### Steps To Reproduce:

For calling different controllers I have used such a macro

```php
Route::macro('contentType', function ($url) {
    if (collect($url)->contains(request()->header('content-type'))) {
        return $this;
    }

    return optional(null);
});
```

in such a way

```php
Route::contentType(['application/json'])->post('/test','TestController@test1');
Route::contentType(['image/png'])->post('/test','TestController@test2');
```

During the `Postman` calls everything worked perfectly, but during testing

```php
$this->postJson('/test')->dump();
```

```

//gives 404
Route::contentType(['application/json'])->get('/test',function () {
    return 'hello!';
});

//returns 'hello!'
Route::get('/test',function () {
    return 'hello!';
});
```

In the middleware headers are starting to work, but if I make 

```php
dd(request()->header('content-type'));
```

in `api.php` during the testing, it would give `null`.

**Comment by sisve** [comment]
Have you tried looking into what headers are present? Is this a simple case of case sensitivity where the header is really named `Content-Type`?

**Comment by Denis4yk** [comment]
Thank you for your response. Unfortunately, it's not. Dumping all requests shows some 5 default headers. In the route closure/middleware it shows 7 with the one I need.

**Comment by themsaid** [comment]
I don't understand the issue you're trying to present? Can you please re-phrase?

**Comment by Denis4yk** [comment]
@themsaid I'm interested in this issue. Please, don't close it due to inactivity, I'll provide a detailed explanation soon. Just this week I have a lot of work :)

**Comment by crynobone** [comment]
The core is always checking against `CONTENT_TYPE`, even `postJson()` populating that header.

**Comment by themsaid** [comment]
ping @Denis4yk, any updates?

**Comment by Denis4yk** [comment]
@themsaid, yes, I'm here. These weeks were...very hard. Sorry. Please, give me 24 hours, I'll update it tomorrow.

**Comment by Denis4yk** [comment]
@themsaid 
Thank you for you patience.

Here is the steps to reproduce it:

Create a new laravel app

`laravel new test`

Add such macro to the `AppServiceProvider`

```php
Route::macro('logContentType', function () {
    Log::debug(optional(request())->header('content-type'));
});
```

Add to the beginning of the `web.php`

```php
Route::logContentType();
```

Run 

`php artisan serve` 

and 

`curl 127.0.0.1:8000 -H "Content-Type: application/json"`

In your `storage/logs/laravel.log` you will see 

`local.DEBUG: application/json`

Everything works as expected. But now change in the default `ExampleTest` the `testBasicTest` method to

```php
public function testBasicTest()
{
    $this->get('/')->withHeaders(['CONTENT_TYPE' => 'application/json']);
}
```
and run `./vendor/bin/phpunit`

And you will see 

` testing.DEBUG:  `

what is **obviously an error** or an **inconsistent behaviour**.

**Comment by Denis4yk** [comment]
@themsaid 

Have you checked it?

**Comment by InstanceOfMichael** [comment]
I'm having the same issue in Laravel 5.5. Using any of the methods like `postJson` loose the headers when they arrive in the controller. Even $request->getMethod() doesn't return 'POST' for a 'GET' request.

**Comment by InstanceOfMichael** [comment]
I would try:
```
Route::macro('logContentType', function (\Illuminate\Http\Request $request) {
    Log::debug($request->header('content-type'));
});
```
it looks like the request helper `request()` is broken during tests.

**Comment by driesvints** [comment]
```php
    $this->get('/')->withHeaders(['CONTENT_TYPE' => 'application/json']);
```

You need to set the headers before you perform the get request otherwise they won't get send along.

```php
    $this->withHeaders(['CONTENT_TYPE' => 'application/json'])->get('/');
```
