### ISSUE TITLE
App\Exceptions\Handler doesn't work as expected when the exception is thrown during compilation

### ISSUE THREAD

**Issue by ajcastro** [laravel/framework#22784]
I think this is an unexpected behavior. I encountered this scenario where I have thrown my custom exception during blade compilation and this custom exception should have its own rendering display page. But since it was thrown during compilation the rendering doesnt work as expected because it was being wrapped by `ErrorException` because of this line of code https://github.com/laravel/framework/blob/a32b087d8d3fd1085316cb6523b167ca10fb19b0/src/Illuminate/View/Engines/CompilerEngine.php#L77. I tried to comment/disable that code temporarily then I get my expected display page for the custom exception.

My render code in `App\Exceptions\Handler::render()`
```
public function render($request, Exception $exception)
    {
       // dd($exception);
        if ($exception instanceof NoDueStartException) {
            return response()->view('errors.no_due_start', [], 422);
        }

        return parent::render($request, $exception);
    }
```
Sample Screenshot

![image](https://user-images.githubusercontent.com/4918318/34917404-d268d14e-f980-11e7-9a92-b2b0ad0a8c68.png)

So currently, my workaround is this
```
public function render($request, Exception $exception)
    {
        if (
            $exception instanceof \ErrorException &&
            $exception->getPrevious()->getPrevious() instanceof NoDueStartException
        ) {
            return response()->view('errors.no_due_start', [], 422);
        }

        return parent::render($request, $exception);
    }
```

I am using laravel 5.4 on this.

**Comment by themsaid** [comment]
This doesn't seem like a bug but rather a design side effect, for suggestions and feature requests please use the https://github.com/laravel/internals repo.
