### ISSUE TITLE
Changes in original header parameter value length

### ISSUE THREAD

**Issue by aascc** [laravel/framework#22780]
- Laravel Version: 5.5
- PHP Version:7.1.9
- Database Driver & Version:mysql 5.7.19

### Description:
I am using scope feature of laravel passport and i have 200 permissions.While login it generates more than 8000 length of access_token .The issue is when i try to use those access_token in header parameter(Authorization)  the length of that header changes which most of the time generated unauthorized response. 
**Image 1**
![header-1](https://user-images.githubusercontent.com/8209956/34913584-882ab2e8-f929-11e7-8109-d3e4cde348ea.png)

**Image 2**
![header-2](https://user-images.githubusercontent.com/8209956/34913585-9fed3220-f929-11e7-9fc2-b32f106257c9.png)

### Steps To Reproduce:
Pass more than 6000 length of string in **authorization header** and check the length of the header request for upto 5 iterations , you will see the changes in **authorization** header length.

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.

**Comment by themsaid** [comment]
You could also open an issue report on laravel/passport to see if other people are having similar issues.

**Comment by aascc** [comment]
@themsaid @taylorotwell the above issue exist in all header value .It is a bug of laravel request.There is no issue with the any header value length. But in laravel request i get that issue. Its a major hurdle for my project because i have to useoauth 2 scope feature.
