### ISSUE TITLE
CSRF token regenerates every few seconds

### ISSUE THREAD

**Issue by edalati** [laravel/framework#22789]
- Laravel Version: 5.5.28
- PHP Version: 7.1.3
- OS: Windows 10
- Database Driver & Version: MySQL 5.7
- Session Driver: MySQL
- Timezone: UTC
- Session config is the framework default.

### Description:
I'm sending a post request to an existing route and redirecting back with a session message.
The csrf token regenerates every time i repeat the request or every few seconds, Making the one present in the form invalid.
### Update: 
A fresh laravel installation has the same problem with login form.

![issue](https://user-images.githubusercontent.com/4587896/34930611-8a72d998-f9df-11e7-8ebb-64d8e717f8ac.gif)

### Controller Method:
```php
public function store(Request $request)
{
    $this->validate($request, [
        'username' => 'required'
    ]);
    $username = $request->get('username');

    // check for duplicate
    $exists= ChannelRequest::where('username', $username)
        ->where('user_id', auth()->id())->exists();
    
    if ($exists) {
        return back()->with('message', 'Duplicate request.');
    }

    auth()->user()
        ->requests()
        ->create($request->only('username'));
    
    return back()->with('message', 'Success.');
}
```
### Form:
```html

<form class="form-horizontal" method="POST" action="{{ route('requests.store') }}">
{{ csrf_field() }}

    <div class="form-group{{ $errors->has('username') ? ' has-error' : '' }}">
        <label for="username" class="col-md-4 control-label">Username: </label>

        <div class="col-md-6">
            <input id="username" type="username" class="form-control" name="username" value="{{ old('username') }}" autofocus dir="ltr">

            @if ($errors->has('username'))
                <span class="help-block">
                    <strong>{{ $errors->first('username') }}</strong>
                </span>
            @endif
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-8 col-md-offset-4">
            <button type="submit" class="btn btn-success">
                Send
            </button>
        </div>
    </div>
</form>
```

**Comment by rodrigopedra** [comment]
I had the same problem when developing in windows using the built-in `serve` artisan command. It was due to some security directives from my employer's company AD. 

I couldn't fix it. Installing the fork for laravel valet for windows worked for me then.

**Comment by edalati** [comment]
I updated my PHP version to 7.1.13 and it fixed the problem.

I'll close this in a couple of days if nobody is interested but the Windows specific bug is still in there!
At least i hope it's a windows specific bug.

Thanks for the help @rodrigopedra.
