### ISSUE TITLE
Flushing tagged items from cache with Redis or Memcached driver doesn't work

### ISSUE THREAD

**Issue by benjamincrozat** [laravel/framework#22788]
- Laravel Version: 5.5.28
- PHP Version: 7.2.1
- Database Driver & Version: MySQL

Hello,

Here's a simplified version of my code.

```php
cache()->tags('posts')->flush();

cache()->tags('posts')->remember($id, function () use ($id) {
    dump('Returning fresh data…');

    return Post::findOrFail($id);
});
```

The callback is never run because the cache isn't flushed as expected. Is there any known issue I'm not aware of?
Even the Artisan command doesn't work:

```bash
php artisan cache:clear --tags posts
```

**Comment by sisve** [comment]
My first thought is that you're not using the correct cache driver in .env. Can you verify that you're using the cache driver that you think you are using? Can you cache new items and see them show up in your cache?

**Comment by benjamincrozat** [comment]
@sisve Seems like it's a known issue and nobody is motivated to fix it. :( #17713

**Comment by mattmant** [comment]
I don't know if this issue is linked to https://github.com/laravel/framework/issues/17713, but for it I suggested and explained a clean solution https://github.com/laravel/framework/issues/17713#issuecomment-278940512 which has been forgotten...

**Comment by benjamincrozat** [comment]
@mattmant Oh yeah I saw it. I don't get why he's waiting that much.

**Comment by themsaid** [comment]
Closing since there's another issue already opened https://github.com/laravel/framework/issues/17713
