### ISSUE TITLE
"actingAs" helper is broken in unit tests

### ISSUE THREAD

**Issue by timoschwarzer** [laravel/framework#22808]
- Laravel Version: 5.5.29
- PHP Version: 7.0, 7.1, 7.2
- Database Driver & Version: 

### Description:
In unit tests, the user is reset to null even after using the `actingAs` method when performing a simulated request with the `get` method.
See: https://github.com/laravel/framework/pull/22649

**Comment by abler98** [comment]
I think we need two properties for the `setUser` and request instance. But this may be cause new issues. Perhaps we should revert my changes.

**Comment by timoschwarzer** [comment]
Yes, this commit should be reverted soon as it likely breaks many unit tests.

**Comment by crynobone** [comment]
Could someone create a failing tests for this (Laravel does have Integration tests) to mimick the issues. Would really benefit to see when and why it broken. I'm using `actingAs()` without issue on the latest stable.

**Comment by abler98** [comment]
@crynobone default guards are not using `RequestGuard`. Those who use the `Passport` (or other guards based on RequestGuard) have this issue.

**Comment by crynobone** [comment]
So wouldn't it make more sense to try to fix `actingAs()` to support this scenario since it does change actual app behaviour, correct?

**Comment by abler98** [comment]
In this case, we need to come up with a new way to authorize in tests

**Comment by crynobone** [comment]
I already writen a testcase for `actingAs`, and bases on `Auth::viaRequest()` test which uses `RequestGuard` I still was unable to replicate above claim.

Without proper tests that cover above scenarios anyone might redo the same mistake of sending similar PR and it still going to return green.

To bad if you guys don't see the benefits of adding test to prevent regression bug.
