### ISSUE TITLE
Jobs not respecting timeout 

### ISSUE THREAD

**Issue by lukepolo** [laravel/framework#22811]
- Laravel Version: 5.5.28
- PHP Version: 7.2.1
- Database Driver & Version: Redis Driver
Redis server v=4.0.1 sha=00000000:0 malloc=libc bits=64 build=f37081b32886670b

### Description:

While running horizon, jobs seem to post that they have failed :

[2017-12-13 02:14:53] local.ERROR: App\Jobs\Server\SomeJob has been attempted too many times or run too long. The job may have previously timed out. {"exception":"[object] (Illuminate\\Queue\\MaxAttemptsExceededException(code: 0): App\\Jobs\\Server\\ProvisionServer has been attempted too many times or run too long. The job may have previously timed out. at /Users/LukePOLO/PhpstormProjects/CodePier/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:394)
[stacktrace]
This particular job has a timeout of
public $timeout = 900;

The job will actually complete even though it says it has failed.I initially thought this was a horizon issue but found it to happen with the built in queue too.

### Steps To Reproduce:

Create a job that will exceeds 5 mins , set the $timeout to 900 (15 mins)

It will fail but will successfully complete.

**Comment by lukepolo** [comment]
A related issue

**Comment by sisve** [comment]
The path in your stack trace indicate that you're running Windows. Timeouts aren't available on Windows.
 (They also require PHP 7.1 and later.)

**Comment by lukepolo** [comment]
That’s a Mac path , good try though !

**Comment by themsaid** [comment]
Make sure you set the `retry_after` value correctly.

**Comment by Amirhb** [comment]
> The path in your stack trace indicate that you're running Windows. Timeouts aren't available on Windows.
> (They also require PHP 7.1 and later.)
> 
> This means that there is nothing that terminates the job after 5 minutes. That's why the job succeeds. But other workers will see the job in the queue, note that it took over 5 minutes, and log it as failed after max number of attempts.

it's been hours that I've been looking for the answer and here is the meaningful one. Thanks!

**Comment by mfn** [comment]
Is it mentioned in the docs? If not, you could submit a PR for that
