### ISSUE TITLE
Individual Illuminate packages are not updated since 5.5.28

### ISSUE THREAD

**Issue by aedart** [laravel/framework#22829]
Laravel Version: 5.5.28+
PHP Version: n/a
Database Driver & Version: n/a

### Description:

The is basically the same issue as #22462. The framework is currently at 5.5.31, yet individual packages are behind.

Is this on purpose or a mistake in your release procedure or release-script(s)?

In any case, I hope that you can take a good look at this issue, because I fear that important (security) updates might not get pushed through to the individual packages, when in fact they might be available in the framework.

**Comment by ntzm** [comment]
I've asked about this before, and they always seem to ignore the issue. Would like to know why this happens as well 👍

**Comment by aedart** [comment]
Is anyone of the core team look at this?

While waiting for a reply or action to be taken, I guess the only solution (workaround) is to use the entire framework. Thus far I haven't seen nor felt any security issues, but this does somewhat keep me up at night!

**Comment by ntzm** [comment]
@themsaid?

**Comment by themsaid** [comment]
Working on an automated tool that’ll take care of that from now on.

Will release all components today, sorry guys 🙂

**Comment by ntzm** [comment]
Thanks for the update!

**Comment by abellion** [comment]
@themsaid JFYI maybe this tool could help : https://github.com/fabpot/gitter
