### ISSUE TITLE
Collection::get() is broken after commit #22554

### ISSUE THREAD

**Issue by mariosvasiliou** [laravel/framework#22830]
- Laravel Version: 5.5.29
- PHP Version: 7.1.2
- Database Driver & Version: MYSQL 5.7

### Description:
After commit "[5.5] Add the power of Arr::get() to Collection get() #22554" the functionality of collection::get() has changed. The default value is always ignored and whole collection is returned instead of null(default) value.

### Steps To Reproduce:
$users = User::where('column',value)->get()->keyBy('id');
$user = $users->get(null);

**Comment by MattMangoni** [comment]
👍  Same problem here.

**Comment by OlesKashchenko** [comment]
Same problem after update from 5.5.28 to 5.5.29

**Comment by vlakoff** [comment]
Fixed in 5.5.32
