### ISSUE TITLE
Request data out of order when mixing strings & files

### ISSUE THREAD

**Issue by josh-taylor** [laravel/framework#22834]
- Laravel Version: 5.5.31
- PHP Version: 7.1

### Description:

When making a request with an input array that mixes strings and files the order is not the same as the original request, although the keys are correct.

I'm not sure if this is intended behaviour or if it's such a massive problem that's worth fixing.

### Steps To Reproduce:

I've setup a [failing test case](https://github.com/josh-taylor/framework/commit/02c2242c8b92e2eae8b1723b9406a1b1c55db2a1) in the `laravel/framework` repo that illustrates the issue.

It's probably more obvious with this example as in some production code I have a test that does something like this:

```php
$response = $this->postJson('/my/endpoint', [
    'images' => [
        File::image('image1.jpg'),
        File::image('image1.jpg'),
        'already-uploaded-image.jpg',
        File::image('image3.jpg'),
    ]
]);
```

Then running `dd(request('images'))` in the controller outputs:

```
array:4 [
  2 => "already-uploaded-image.jpg"
  0 => Illuminate\Http\Testing\File {#984
    // ...
  }
  1 => Illuminate\Http\Testing\File {#986
    // ...
  }
  3 => Illuminate\Http\Testing\File {#982
    // ...
  }
]
```

So just doing a loop over this the results are out of order with what I am expecting.

**Comment by themsaid** [comment]
What's your use case for mixing files and strings in the same array?

**Comment by josh-taylor** [comment]
I was saving an array of images into a JSON file, sometimes the user would upload new images and sometimes they'd use an already uploaded image.

The order of the array was important as that is the order in which the images are displaying. I ended up just doing a `ksort()` on the array and I also recognise it was probably simpler (on the server side) to have a sort property but this is just how I was attempting it at the time.

**Comment by themsaid** [comment]
Checking the way we separate files from other input types I'd say this is a no-fix.

**Comment by justencc** [comment]
1. Remove `array_values()` in your test function and retrieve the element of `$request['images']` directly such as `$request['images'][1]`, the test result should be green.
2. `ksort()` just sort keys and the order of values don't change
3. If you want to retrieve the original ordered array, you should use `for` loops like this:

```php
$length = count($request['images']);

for ($i = 0; $i < $length; $i++) {
    var_dump($i);
    echo "=====>";
    var_dump($request['images'][$i]);
}
```

**Comment by laurencei** [comment]
Closing as it's been decided it wont be fixed.
