### ISSUE TITLE
Several queue workers with database driver

### ISSUE THREAD

**Issue by aleksejjj** [laravel/framework#22844]
- Laravel Version: 5.4
- PHP Version: 5.6

### Description:

Additional jobs created in the `jobs` table after fail.

### Steps To Reproduce:

1. `QUEUE_DRIVER=database` in `.env` file

2. Create a `Test` job with 
`public function handle()`
`{`
        `sleep(10);`
        `throw new \Exception();`
`}`

3. Test::dispatch(); // 1 DB record added to `jobs` table.

4. Run `php artisan queue:work` command 5 times.

5. Result: we can see 5 records in `jobs` table.

**Comment by sisve** [comment]
Could you provide everything needed to reproduce this issue? What's `Test::dispatch()`?

**Comment by aleksejjj** [comment]
@sisve `Test::dispatch();` just sent a job to the default queue as described in the docs [https://laravel.com/docs/5.5/queues#connections-vs-queues](https://laravel.com/docs/5.5/queues#connections-vs-queues). I did not add a steps like a `php artisan queue:table` to issue description because it is well documented. Feel free to ask any other questions that you deem necessary.

**Comment by themsaid** [comment]
Please upgrade to 5.5 and re create the issue with more details if still exists.
