### ISSUE TITLE
Laravel 5.3 PHP 7.2.1 compatibility in SoftDeletes

### ISSUE THREAD

**Issue by drjonnicholson** [laravel/framework#22843]
- Laravel Version: 5.3.*-dev
- PHP Version: 7.2.1-1+ubuntu16.04.1 (in homestead)
- Database Driver & Version: ?

### Description:

Calling delete on a model with the `SoftDeletes` trait causes a `count(NULL)` failure due to how `count()` now processes null values.

Exception:
```
ErrorException: count(): Parameter must be an array or an object that implements Countable in /home/vagrant/***/vendor/laravel/framework/src/Illuminate/Database/Eloquent/SoftDeletingScope.php:55
```

Offending code:
```PHP
    protected function getDeletedAtColumn(Builder $builder)
    {
        if (count($builder->getQuery()->joins) > 0) {
            return $builder->getModel()->getQualifiedDeletedAtColumn();
        }
        return $builder->getModel()->getDeletedAtColumn();
    }
```

Suggested fix, use version from Laravel 5.5/5.6:
```PHP
    protected function getDeletedAtColumn(Builder $builder)
    {
        if (count((array) $builder->getQuery()->joins) > 0) {
            return $builder->getModel()->getQualifiedDeletedAtColumn();
        }
        return $builder->getModel()->getDeletedAtColumn();
    }
```

### Steps To Reproduce:

Try something like:
```PHP
MyModel::where('id', 1)->delete();
```

**Comment by ntzm** [comment]
That version is no longer supported, you need to update to a newer version of Laravel

**Comment by zulrang** [comment]
@taylorotwell Mentioned in the docs repo that he wants 5.1 to support PHP 7.2

**Comment by drjonnicholson** [comment]
@ntzm, that’s not a helpful answer. As far as I can see there is no statement in the git read me or the main website about 5.3 no longer being supported (both happily document 5.2 onwards)

Additionally, active support compared to bug fix support are two different issues. I don’t expect new features - just the existing ones to work. 

Note that, as in my original post, the same issue is fixed elsewhere in the version we are using, it’s a simple fix.

When we can we will update, but at the moment it’s not possible. In our development roadmap.

**Comment by devcircus** [comment]
According to [laravel-news](https://laravel-news.com/laravel-release-process), all support for 5.3 has long passed, even security. That's not written in stone though, so IMO, the best option would probably be a quick pull request for 5.3 as a bug-fix with an explanation. Taylor will be sure to see it then.

**Comment by drjonnicholson** [comment]
I've posted a pull request here https://github.com/laravel/framework/pull/22858
