### ISSUE TITLE
QueryBuilder's first() method says its returning an Eloquent Model instance, docs says it returns a StdClass

### ISSUE THREAD

**Issue by Donatello-za** [laravel/framework#22854]
This is applicable to Laravel 5.6 and earlier.

QueryBuilder uses the BuildsQueries trait where its `first()` method looks like this:

```php
    /**
     * Execute the query and get the first result.
     *
     * @param  array  $columns
     * @return \Illuminate\Database\Eloquent\Model|static|null
     */
    public function first($columns = ['*'])
    {
        return $this->take(1)->get($columns)->first();
    }
```

Notice that its comment says that its returning an `Eloquent` model, `static` or `null`. The docs at https://laravel.com/docs/5.6/queries says this:

> **Retrieving A Single Row / Column From A Table**
> 
> If you just need to retrieve a single row from the database table, you may use the `first` method. This method will return a single `StdClass` object

In Lumen 5.4 it returns a `StdClass` when I test it. Only reason I noticed it is because my IDE is giving warnings. Can the code comment be fixed/updated to reflect the fact that it may also return a `StdClass`?

**Comment by JosephSilber** [comment]
Actually, can it ever return `static`? Don't think so.
