### ISSUE TITLE
New laravel installation throws error : vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php

### ISSUE THREAD

**Issue by mikeyc1030** [laravel/framework#22863]
- Laravel Version: 5.5.0
- PHP Version: 7.1
- Database Driver & Version:
- Server : Zend Server / Apache24
- Windows 10

### Description:
New Laravel installation using composer throws error : Uncaught Exception: Serialization of 'Closure' is not allowed 
 in <path>vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php

### Steps To Reproduce:
Install using composer using following command:
composer create-project --prefer-dist laravel/laravel blog
Set up virtual host in Zend Server setting document root to laravel/blog/public browse to URL and the following error is displayed:

Uncaught Exception: Serialization of 'Closure' is not allowed in C:\Program Files (x86)\Zend\Apache24\htdocs\laravel2\blog\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php:112 Stack trace: #0 C:\Program Files (x86)\Zend\Apache24\htdocs\laravel2\blog\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(89): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Exception)) #1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Exception)) #2 {main} thrown

Tried this whole procedure twice and same outcome.

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
