### ISSUE TITLE
SoftDeletes ignored for child model login

### ISSUE THREAD

**Issue by zer0lik** [laravel/framework#22869]
- Laravel Version: 5.5.32
- PHP Version: 7.1.3
- Database Driver & Version: MySQL 5.7.17

### Description:
When having separate model for authenticated users, that extends User model with SoftDeletes, but uses the same users table, then logging in using built-in authentication will ignore deleted rows (where deleted_at is not null), and log in as the first matched row.
I'm using separate authentication model, because User model has global scopes that are unnecessary for authenticated user. Also $visible array is different. But that's not the point.

The issue relates to this one:
[https://github.com/WildSideUK/Laravel-Userstamps/issues/8](https://github.com/WildSideUK/Laravel-Userstamps/issues/8)

### Steps to reproduce:
1. Generate Laravel built in authentication controllers.
```
php artisan make:auth
```
2. Make User model with SoftDeletes.
```
class User extends Authenticatable {
    use SoftDeletes;
    ...
}
```
3. Make AuthUser model which will be used for authentication. It extends User and uses the same users table.
```
class AuthUser extends User {
    protected $table = 'users';
    ...
}
```
4. Configure Laravel to use AuthUser in `auth.php`
```
'providers' => [
    'users' => [
        'driver' => 'eloquent',
        'model' => App\User::class,
    ],
],
```
5. Create first user with email `test@test.com` and delete him. Deletion will correctly update deleted_at timestamp automatically.
6. Create second user with **same** email `test@test.com` and **same** password as the first user. This also works correctly - deleted row is ignored and there is no email conflict.
7. Log in with the second user.
8. User is logged in as the **first** user, that is actually soft deleted, and not the second one.

**Comment by devcircus** [comment]
if you need authentication to consider soft deletes, just override the attemptLogin method and add the constraint.

**Comment by zer0lik** [comment]
@devcircus Sure. But isn't this a bug? AuthUser extends User, so SoftDeletes should be considered, no?

**Comment by zer0lik** [comment]
OK, that's why you should write bug reports without sleeping on it. I was overriging boot method and didn't call `parent::boot()`.
