### ISSUE TITLE
Run Laravel Database Migration after every build on Google App Engine

### ISSUE THREAD

**Issue by bmunyoki** [laravel/framework#22876]
I am running Laravel 5.5 on GAE with a MySQL instance running database. I want to be able to run database migrations after every build. I have added command "php artisan migrate" on post-install-cmd in composer.json but it does not seem to work.

"post-install-cmd": [
        "chmod -R 755 bootstrap\/cache",
        "php artisan migrate  --no-interaction --force",
        "php artisan cache:clear"
    ]
The build log shows command running but looks like down there there is command cancelled. What could be the issue? How can I run migration after every build? 
I get this error ERROR: SQLSTATE[HY000] [2002] No such file or directory (SQL: select * from information_schema.tables where table_schema = My_DB_NAME and table_name = migrations) SQLSTATE[HY000] [2002] No such file or directory (SQL: select * from information_schema.tables where table_schema = My_DB_NAME and table_name = migrations) at /app/vendor/laravel/framework/src/Illuminate/Database/Connec‌​tion.php:664, PDOException(code: 2002): SQLSTATE[HY000] [2002] No such file or directory

I replaced the actual database name with My_DB_NAME. Any help will be appreciated.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this github area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I please suggestion closing your issue ticket here. Instead trying asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.
