### ISSUE TITLE
How to modify the returned paging data format?

### ISSUE THREAD

**Issue by acodercat** [laravel/framework#22877]
- Laravel Version: 5.5
- PHP Version: 7.1
- Database Driver & Version:

### Description:
How to modify the returned paging data format

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I suggest closing your issue ticket here? Instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.

**Comment by acodercat** [comment]
please

**Comment by Dylan-DPC** [comment]
@acodercat this repo is meant for bug tracking. If you need help you can try the forums or the slack channel.

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
