### ISSUE TITLE
Laravel 5.5 - Syntax error

### ISSUE THREAD

**Issue by Tugsbayar** [laravel/framework#22878]
- Laravel Version: 5.5.32
- PHP Version: 7.0
- Database Driver & Version: 

### Description: 
After running `composer update` command, following error occurred:
`PHP Parse error:  syntax error, unexpected '?' in /home/apps/auditus/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 233`

Following the file and error line:
Helpers.php:
```
        if (is_string($arguments[0])) {
                return app('cache')->get($arguments[0], $arguments[1] ?? null);
        }
```

**Comment by laurencei** [comment]
are you sure your running PHP7? That error looks like your not...?

**Comment by Tugsbayar** [comment]
I runned `phpinfo();`  and it shows me this: `PHP Version 7.0.26`

**Comment by laurencei** [comment]
Sounds like something's gone wrong in your vendor folder to me. Just delete `vendor` and then do `composer install`.

**Comment by GuidoHendriks** [comment]
Are you sure that the CLI version of PHP is also 7.0? Run `php -v` to see this.

**Comment by Tugsbayar** [comment]
I updated PHP 7.0 to PHP 7.1. Now, It works fine for me. In conclusion, ?? syntax requires PHP version up to 7.1

**Comment by GuidoHendriks** [comment]
Nope, introduced in PHP 7.0.

**Comment by hackmigo** [comment]
I also have the same problem.
PHP 7.1.12
laravel 5.5.0

**Comment by BookNetwork** [comment]
im getting same issue in web hosting

**Comment by BookNetwork** [comment]
please help me

**Comment by GuidoHendriks** [comment]
@BookNetwork Are you on PHP 7.0+?

**Comment by Tugsbayar** [comment]
> im getting same issue in web hosting

I think that you should update your php version.

**Comment by Rajakishore9** [comment]
Even I am also. These issues in local system anyone could help me out
