### ISSUE TITLE
 drark

### ISSUE THREAD

**Issue by basisbyte** [laravel/framework#22889]
- Laravel Version: #.#.#
- PHP Version:
- Database Driver & Version:

**Comment by Dylan-DPC** [comment]
Thank you for the bug report. This issue is fixed in NaN.NaN.NaN version of laravel.

**Comment by concept-core** [comment]
@basisbyte Thanks for the heads up for this bug.
Was almost afraid that I was the only one with it.
Hope the fix will get pushed live soon 👋

**Comment by basisbyte** [comment]
Sorry for the confusion. Must have created this faulty bug report by accident -  I can't remember that I wanted to creat one?! Really strange.
