### ISSUE TITLE
Auth::attempt does not hash

### ISSUE THREAD

**Issue by yooouuri** [laravel/framework#22887]
- Laravel Version: 5.5.x
- PHP Version: 7.2.0-1
- Database Driver & Version: x

### Description:
When I want to use `Auth::attempt` it gives me false, `Hash::check` returns true on the other hand.
My password in the database is hashed.

```
dd(Auth::attempt(['Email' => $email, 'Password' => $password]), Hash::check($password, VenueUser::where('email', $email)->first()->Password));
```

returns:

```
false
true
```

Debugbar shows me a query where the password is not hashed, is that because of the debugbar or?

```
select * from `venue_user` where `Email` = 'xxxx' and `Password` = 'plain text password' limit 1
```

### Steps To Reproduce:

```
Auth::attempt(['Email' => $email, 'Password' => $password])
```

Database

![image](https://user-images.githubusercontent.com/12934957/35277124-e606e3e6-0045-11e8-81d4-bee9cf8714c9.png)

Changed in config/auth.php

`'model' => App\VenueUser::class,`

VenueUser model

```
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Cashier\Billable;

class VenueUser extends Authenticatable
{
    use Notifiable, Billable;

    protected $primaryKey = 'User_id';
    protected $table = 'venue_user';
    public $timestamps = false;

    protected $dates = ['trial_ends_at', 'subscription_ends_at'];
}
```

**Comment by jerguslejko** [comment]
not sure, but it might be that your password field is capitalised. `Password` vs `password`

**Comment by yooouuri** [comment]
@jerguslejko In the `Auth::attempt` I am using `Password`

**Comment by jerguslejko** [comment]
yeah, but if you take a look into `Illuminate\Auth\EloquentUserProvider` lowercase `password` is hardcoded. 

I haven't tried this myself, just guessing.

**Comment by yooouuri** [comment]
When i add

```
public function getAuthPassword()
{
    return $this->Password;
}
```

To my user model, it works. Maybe because of the capital P in password.
