### ISSUE TITLE
Menu Item background color not reflected in admin backend

### ISSUE THREAD

**Issue by VirtumartOz** [laravel/framework#22885]
- Laravel Version: 5.5.32
- PHP Version:7.2.1
- Database Driver & Version: 10.1.13-MariaDB

### Description:
Menu Item background color not reflected in admin backend

### Steps To Reproduce:
Tools -> Menu Builder -> Admin click bulder -> create a new menu , fill every thing including "Color in RGB or hex (optional)", select the color and save, 
after refresh page, new menu appears but no background color

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I suggest closing your issue ticket here? Instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.

**Comment by sisve** [comment]
You should probably report this in the voyager repository. https://github.com/the-control-group/voyager/issues
