### ISSUE TITLE
Queueable trait does not work on listeners

### ISSUE THREAD

**Issue by halaei** [laravel/framework#22880]
- Laravel Version: 5.5
### Description:
When using Queuable trait in a listener onConnection() and onQueue() does not work.

### Steps To Reproduce:
```php
class SomeListener implements ShouldQueue
{
    use Queueable;
    public function __construct()
    {
        $this->onConnection('some_connection')->onQueue('some_queue');
    }
...
}
```
That is because constructor is not called at all.

**Comment by themsaid** [comment]
You can use a class property:

```
public $connection = '';
public $queue = '';
```
