### ISSUE TITLE
Artisan throwing database errors when sharing data from database with views

### ISSUE THREAD

**Issue by staticwave** [laravel/framework#22898]
- Laravel Version: 5.5.32
- PHP Version: 7.0.5
- Database Driver & Version: MySQL 5.7

### Description:
I don't know whether this is a bug or there's something else going on, but when I share data with views from inside a service provider's boot method, and the data is retrieved from the database, I get errors when trying to run any artisan command.

I get the same results whether I'm running artisan in the homestead environment or on a server. It also doesn't matter which table/model I'm querying or which artisan command I'm running.

```
use App\ReadingType;

class ViewServiceProvider extends ServiceProvider
{
    public function boot()
    {
        View::share('reading_types', ReadingType::all());
    }
}
```

The following also causes the same errors with artisan

`View::share('reading_types', DB::table('reading_types')->get());`

The only time I don't have an issue is if I hard-code an array like this

`View::share('reading_types', ['one', 'two', 'three']);`

In **_all_** cases, the data **_is_** shared with the views as expected, however artisan throws errors with the noted conditions above.

```
php artisan

In Connection.php line 664:

  SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
   (SQL: select * from `reading_types`)


In PDOConnection.php line 47:

  SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.


In PDOConnection.php line 43:

  SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.

```

I did notice that if I update the `DB_PORT` setting in my .env file from `3306` to `33060` while the DB queries are present in `View::share`, the artisan errors go away - but then my application can no longer access the DB so I get errors again just in another place.

Is this a bug, problem with my code, because of php version? I'm really confused.

**Comment by birhannega** [comment]
It looks like the database service is stopped.

**Comment by staticwave** [comment]
@birhannega If that were the case then the data wouldn't get sent to the views, right? But the data is retrieved and is sent to the views.

**Comment by sisve** [comment]
The boot() method executes very early in the application lifecycle. The problem is probably not in View::share, but that you're doing database calls this early. I would use a closure-based view composer (or a class based one) to delay the execution of the database call.

    View::share('reading_types', function($view) {
        return ReadingType::all();
    });

**Comment by staticwave** [comment]
@sisve Thanks for the suggestion, but that doesn't return any data to the view.

I was able to get things back to normal by switching to `View::composer` instead.
