### ISSUE TITLE
Migrations are case sensitive

### ISSUE THREAD

**Issue by jamesez** [laravel/framework#22897]
- Laravel Version: 5.5.32
- PHP Version: 7.1.12
- Database Driver & Version: mysqlnd 5.0.12 

### Description:
Migration re-run prevention is case sensitive; if a file changes case but not contents, the migration will attempt to be re-run.

One of my developers generated a commit that had - by accident - renamed 2017_12_19_141327_AddIndexes2 to 2017_12_19_141327_addindexes2. When Jenkins tried to deploy, the migration broke with dupe indicies.

I can see the argument that Git recognizes it as a different file, even if macOS and Windows don't.  I tend to think? nobody would have two different migrations that have the same name but different case.

I can work up a PR if this sounds like a bug.

**Comment by lagbox** [comment]
How about the argument of .... they are developers how about they take some responsibility for themselves and their actions.

**Comment by themsaid** [comment]
this isn't a bug, you shouldn't rename your migration files at all.
