### ISSUE TITLE
Model->latest()->first() bug

### ISSUE THREAD

**Issue by kevinp1005** [laravel/framework#22899]
- Laravel Version: 5.3
- PHP Version: 7
- Database Driver & Version: MySQL 5.7

### Description:
Recently facing a bug with latest() function in Eloquent. It happened when I have the exact same created_at time. 

### Steps To Reproduce:

Let's say I have row with ID **78** with created at **2018-01-01 11:52:50** and row with ID 79 with created_at  **2018-01-01 11:52:50**. 

Now, when I call `Model->latest()->first()` , the ID returned is **78** , instead of **79**

And my solution was to change it to use orderBy ID instead.
`Model->orderBy('id','desc')->first()`

But what if I prefer to use latest()->first(), do I have to prevent same created_at

**Comment by sisve** [comment]
There's no easy solution to this. Defaulting to `->orderBy('id', 'desc')` will only work for auto-incrementing integer columns, not uuids or other types of integers.

**Comment by rcubitto** [comment]
You can specify the column `Model::latest('id')->first()`. It's either that or explicitly specifying the `created_at` value with different values for the rows created.

**Comment by themsaid** [comment]
5.3 isn't supported anymore, please upgrade.

**Comment by kevinp1005** [comment]
:simple_smile:
