### ISSUE TITLE
Error changing timestamp column in PostgreSQL

### ISSUE THREAD

**Issue by antonioribeiro** [laravel/framework#22908]
- Laravel Version: v5.5.31
- PHP Version: 7.1.4
- Database Driver & Version: PostgreSQL 

### Description:

Cannot alter a timestamp table from not null to nullable, Doctrine raises this exception:

```
Unknown column type "timestamp" requested. 
Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType(). 
You can get a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap(). 
If this error occurs during database introspection then you might have forgotten to register all database types for a Doctrine Type. 
Use AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#getMappedDatabaseTypes(). 
If the type name is empty you might have a problem with the cache or forgot some mapping information.
```

### Steps To Reproduce:

Create a table using pgsql driver:

```
Schema::create('processos', function (Blueprint $table) {
    $table->increments('id');

    $table->timestamp('date_column_name');

    $table->timestamps();
});
```

Then alter the table:

```
Schema::table('processos', function (Blueprint $table) {
    $table->timestamp('date_column_name')->nullable()->change();
});
```

**Comment by antonioribeiro** [comment]
I just found that if we use `timestamp()` to create and `dateTime()` to update it works:

```
Schema::table('processos', function (Blueprint $table) {
    $table->dateTime('data_distribuicao')->nullable()->change();
}); 
```

But this still looking like a bug to me.

**Comment by emilv** [comment]
The problem is the use of the TIMESTAMP type in the database instead of DATETIME. You can read more about this topic here: https://github.com/doctrine/dbal/issues/2558

Your solution changes the type of the column, which might have unintended side-effects. But DATETIME is a better type anyway in most cases.

**Comment by driesvints** [comment]
Seems to me like a problem with Doctrine rather than Laravel?
