### ISSUE TITLE
Laravel 5.5 doen't render its default error views and Apache takes over

### ISSUE THREAD

**Issue by cizario** [laravel/framework#22901]
- Laravel Version: 5.5.32
- PHP Version: 7.1.8
- Database Driver & Version: 
- Server : Apache 2.4
- Centos 7

### Description:
i installed with composer fresh Laravel with NO extra packages on VPS running apache.
i set 777 permissions for `/storage/*` and `/bootstarp/*`and i got the default Laravel welcome page, until now every thing seems working fine, but when i try to trigger 404 error (simply wrong url), laravel doesn't render its default 404 view with message `Sorry, the page you are looking for could not be found.` instead i got Apache default message `Page redirection: Check you URL` even more when i enable the maintenance mode Laravel doesn't render its 503 default view and instead i got the apache default message `Internal Server Error`

i'm wondering, because i have an other fresh Laravel installation running on my local machine (windows + wampserver) with no fault.

what i'm missing ? is there specific apache conf ? htaccess ?
### Steps To Reproduce:
VPS running apache
`composer create-project --prefer-dist laravel/laravel test`
`sudo chmod -R 775 /var/www/test/storage`
`sudo chmod -R 775 /var/www/test/bootstrap/cache`

**Comment by sisve** [comment]
Are _any_ routes except the default one working? I would expect this behavior if you do not have any rewrite module active, thus Apache handles all requests and not Laravel.

**Comment by cizario** [comment]
i can confirm : i didn't install any extra packages nor override views, controllers nor add any routes. 

`routes/web.php`
```
Route::get('/', function () {
    return view('welcome');
});
```
the installation is fresh, i just use 
`composer create-project --prefer-dist laravel/laravel test`

i kow Apache handles all requests and not Laravel, but i  mean if any error (404, 503 ..) occurs i would normally expect the default laravel views.

**Comment by cizario** [comment]
it's really ridiculous, i SIMPLY changed my public @ip and every thing works like a charm.
it was my `ISP proxy cache`. D**n; it costs me 6 days to figure it out.

http://www.pdproxy.com/blog/is-your-isp-using-a-transparent-proxy-32.htm
