### ISSUE TITLE
Redis queue bulk insert with RPUSH

### ISSUE THREAD

**Issue by fedeisas** [laravel/framework#22906]
Since Redis version >=2.4 [RPUSH allows multiple value arguments](https://redis.io/commands/rpush#history). Is there any reason why `RedisQueue` does not have an implementation of the `bulk` method as `DatabaseQueue` does? I'll be happy to submit a PR.

I'm thinking something like this:

```php
class RedisQueue
{    
    public function bulk($jobs, $data = '', $queue = null)
    {
        return $this->getConnection()->rpush(
            $this->getQueue($queue),
            ...array_map(function ($job) use ($data) {
                return $this->createPayload($job, $data);
            }, $jobs)
        );
    }
}
```

**Comment by fedeisas** [comment]
I just implemented this on a project and it works fine.

**Comment by themsaid** [comment]
Sounds cool, cal you please open a PR for that? I'll close this since it's not actually a bug.

For suggestions and feature requests please use the https://github.com/laravel/internals repo.
