### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by collegeman** [laravel/framework#22907]
https://github.com/laravel/framework/blob/2e57d9646263ceb43ed34c170291a4c1b4fb8342/src/Illuminate/Database/Query/Builder.php#L761

In working with pivot data, I was using the expression `$this->morphedByMany($related, $name)->wherePivotIn($column, $values)` and made a late decision to change from querying *in* to simply making a scalar comparison. Unfortunately, I forgot to swap out `wherePivotIn` for `wherePivot` and spent about 20 minutes trying to figure out why the same code was how failing for "Invalid argument supplied for foreach()".

This is user error, clearly, but I wonder if it's user error that we could handle better with a type check just before the loop? 

If that is worthwhile, I'll issue a test-passing pull request. Just asking the community if they think this is a worthwhile thing to try to prevent. I figure anytime we can push errors back up to application code, we're making the framework more useful and more beautiful as a result.

Thank you for your consideration.

**Comment by ntzm** [comment]
Error messages come with a file path and line number, a developer should be able to see what the issue is pretty quickly

**Comment by collegeman** [comment]
Well @ntzm I won't take that as a slight, considering I've been a developer for the last 21 years, but thanks for your comment. It may have taken me longer to find it since I was working too late on this one. The error "invalid argument supplied for foreach" inside the 700+ line long Builder at the core can definitely be debugged line by line, but my question was whether or not it makes sense to push errors closer to the application, e.g., "Wrong type of values passed to morphedByMany". Cheers.

**Comment by ntzm** [comment]
I didn't mean it as a slight, sorry if it came across that way.

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
