### ISSUE TITLE
Paginate(0) return a list of all items

### ISSUE THREAD

**Issue by stephanebressani** [laravel/framework#22916]
- Laravel Version: 5.5.*
- PHP Version: >=7.0.0
- Database Driver & Version: Mysql or Sqlite

### Description:

Hello, 

I found a bug in paginate

### Steps To Reproduce:

```
Blocks::where('id',27)->with(['LivreOr' => function ($query) { 
   $query->where('blocks_id', 27)->orderBy('created_at')->paginate(0);
}])->with('LivreOrParam')->first()
```
Return me a array with full list of 'LivreOr'

I solved the problem with a if like 1 == 0
```
$record = Blocks::where('id', 27)->with(['LivreOr' => function ($query) {
   $query->where('blocks_id', 27)->where('blocks_id', 0);
}])->with('LivreOrParam')->first();
```

**Comment by MattMangoni** [comment]
@stephanebressani and what do you think the correct behaviour is?
To me, it doesn't make any sense to have ->paginate(0) :)

**Comment by axyr** [comment]
I would assume 0 returns 0 items too.
null i would not know in this case...

**Comment by themsaid** [comment]
Closing since it's not actually a bug.
