### ISSUE TITLE
Request helper hasAny returning different booleans for arrays

### ISSUE THREAD

**Issue by bbashy** [laravel/framework#22917]
- Laravel Version: 5.5.32
- PHP Version: 7.1.13
- Database Driver & Version: MariaDB 10.2.12

### Description:
When using `hasAny()` on the request helper, it returns false when using an array but true when using multiple params.

laravel/framework/src/Illuminate/Http/Concerns/InteractsWithInput.php `hasAny()` function receives the keys like this;

// via array
```
array:1 [▼
  0 => array:3 [▼
    0 => "from"
    1 => "to"
    2 => "manager"
  ]
]
```
// via params
```
array:3 [▼
  0 => "from"
  1 => "to"
  2 => "manager"
]
```

![](https://d.pr/i/hkC65N.jpg)

### Steps To Reproduce:
URL: `http://domain.ext?from=17-01-2018`

1. When using `hasAny` with array, this will return false.
2. When using `hasAny` with multiple params, this will return true.

```
dd(
    request()->all(),
    request()->hasAny('from', 'to', 'manager'),
    request()->hasAny(['from', 'to', 'manager'])
);
```

**Comment by devcircus** [comment]
See [the code](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Http/Concerns/InteractsWithInput.php). The method expects individual parameters. So the array is recognized as a single param. Maybe a PR?

**Comment by themsaid** [comment]
PR submitted to 5.6 branch https://github.com/laravel/framework/pull/22952
