### ISSUE TITLE
migrate:fresh is broken in 5.5.32

### ISSUE THREAD

**Issue by brunocfalcao** [laravel/framework#22910]
- Laravel Version: 5.5.32
- PHP Version: 7.2.1
- Database Driver & Version: MySQL 5.7

### Description:
migrate:fresh is broken. When you try to run it, it gives an error in the Illuminate\Database\Migrations\Migrator class, line 423.

### Steps To Reproduce:
1. run laravel new <project>.
2. run php artisan migrate:fresh (after configuring a correct database connection).
3. Error appears immediately (when the 2 default migration files exist).

### Solution:
The index at the end of the array_slice is incorrect.
Instead of :
$class = Str::studly(implode('_', array_slice(explode('_', $file), 6)));
Should be :
$class = Str::studly(implode('_', array_slice(explode('_', $file), 4)));

This way it works if your migration file respects the normal migration file format Y_M_D_TS_<...>.php.

**Comment by brunocfalcao** [comment]
![capture](https://user-images.githubusercontent.com/34269950/35362204-b37e9a16-0164-11e8-861f-acb3cf2a80f0.JPG)

**Comment by laurencei** [comment]
I tried this on `5.5.32` and it works for me without issue.

Looks like something else for your project to me based upon that error message.

**Comment by sisve** [comment]
Looks like a migration file isn't named correctly.

**Comment by DariusIII** [comment]
Works just fine for me, no error whatsoever.

**Comment by brunocfalcao** [comment]
Hi,

I've checked my code and indeed there was an issue with a migration file. Sorry for your time spent.

I'll close it now.

Cheers.
