### ISSUE TITLE
Accessor running twice

### ISSUE THREAD

**Issue by luizguilhermefr** [laravel/framework#22921]
- Laravel Version: 5.5.32
- PHP Version: PHP 7.0.24-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Sep 28 2017 16:20:59)
- Database Driver & Version: MySQL 5.7

### Description:

The accessor for one of my model's attribute is running twice.
I am trying to format an url. In database I have: `/some_location/file.jpg`. I want to preppend `www.somedomain.com` to it, but it is prepending twice.

### Steps To Reproduce:

Create a Model and insert a database record named `picture_url` with value `/some_location/file.jpg`.

Define an accessor like:

```php
public function getPictureUrlAttribute($attr) {
    if (is_null($attr)) {
        return null;
    }
    return 'www.somedomain.com'.$attr;
}
```

Return the model in some route. See it returns `www.somedomain.comwww.somedomain.com/some_location/file.jpg`.

I did a test returning `microtime() ` (microtime <space>) and the result was like `0.44203700 1516913683 `, confirming that is running twice.

**Comment by arjasco** [comment]
I would check you're not actually saving "www.somedomain.com" in your picture_url attribute on your model.

**Comment by luizguilhermefr** [comment]
I'm not. I checked directly from MySQL.

Em 27 de jan de 2018 12:08 PM, "Aaron Costello" <notifications@github.com>
escreveu:

**Comment by rcubitto** [comment]
I wasn't able to reproduce the bug in a fresh install of Laravel 5.5. Did you try isolating it to a new fresh Laravel install?

**Comment by devcircus** [comment]
Could not reproduce either. Url formed as expected.

**Comment by themsaid** [comment]
Can't reproduce the error too, closing then. Please test on a fresh laravel app and open a new issue with your finding.
