### ISSUE TITLE
validate() function redirect in chrome browser not showing any validation errors (more than 3 errors)

### ISSUE THREAD

**Issue by awd22** [laravel/framework#22922]
Laravel 5.4 version
The validate() function works until I test more than 3 errors in the form.  Upon automatic redirect after buildfailedvalidationresponse function, the 4 $error messages aren't present on and neither is the old form data.  This only doesn't work in chrome. Firefox/internet explorer is fine.  I have data dumped throughout the process of validatesrequest file and it shows the $error variables being passed correctly to the buildfailedvalidationresponse function but no errors/old form data are presented after redirect.  I was just wondering if anybody has had an issue like this with different browsers.

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
