### ISSUE TITLE
A bug in the framework

### ISSUE THREAD

**Issue by yanqinsc** [laravel/framework#22926]
- Laravel Version: 5.5.0
- PHP Version: 7.1
- Database Driver & Version:

### Description:
I found code "??" many times in framework, I think it should be "?:".
E.g：
Code at vendor/laravel/framework/src/Illuminate/Foundation/helpers.php in version 5.5
`if (is_string($arguments[0])) {
            return app('cache')->get($arguments[0], $arguments[1] ?? null);
  }
`

It like below in version 5.3
`
if (is_string($arguments[0])) {
            return app('cache')->get($arguments[0], isset($arguments[1]) ? $arguments[1] : null);
 }
`

**Comment by browner12** [comment]
`??` is valid code. It is called the null coalesce operator.

You can read about it [here](http://php.net/manual/en/migration70.new-features.php).

**Comment by Kyslik** [comment]
Wow 5.3 to 7.x a big jump http://php.net/supported-versions.php
