### ISSUE TITLE
Expose Eloquent Model getAppends()

### ISSUE THREAD

**Issue by aleemb** [laravel/framework#22932]
- Laravel Version: 5.5.32
- PHP Version: 7.2

### Description:

Currently there is a `setAppends()` but corresponding `getAppends()`. It can come in handy for certain uses cases such as getting serialised data without appended values. Or maybe make `getArrayableAppends()` public, if that does the same thing?

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
