### ISSUE TITLE
Failed adding migrations

### ISSUE THREAD

**Issue by warsongkiller** [laravel/framework#22930]
- Laravel Version: 5.5.0
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7

### Description:
I tried to add a custom migration, but when I want to add it into the database it adds the user table but not the migration I added to the migrations tab.

### Steps To Reproduce:
1. `php artisan make:migration create_role_user_table --create=role_user`
2. Add info into the .php file
3. Run `php artisan migrate`
4. Check the database

Then you will see that the table did not add itself

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
