### ISSUE TITLE
session->exists() does not work with the dot notation

### ISSUE THREAD

**Issue by apokryfos** [laravel/framework#22931]
- Laravel Version: 5.5.32
- PHP Version: 7.1

### Description:
The session->exists() function does not work with the dot notation. 

### Steps To Reproduce:

I would expect the following test to pass but it fails.

```
    public function testExistsAndHas() {
        $this->session([
            "test" => [
                "empty" => null,
                "nonEmpty" => true
            ],
            "unnestedNonEmpty" => true,
            "unnestedEmpty" => null
        ]);

        $this->assertTrue(session()->has("unnestedNonEmpty"));
        $this->assertFalse(session()->has("unnestedEmpty"));
        $this->assertTrue(session()->has("test.nonEmpty"));
        $this->assertFalse(session()->has("test.empty"));
        $this->assertFalse(session()->has("dummy"));

        $this->assertFalse(session()->exists("dummy"));
        $this->assertTrue(session()->exists("unnestedNonEmpty"));
        $this->assertTrue(session()->exists("unnestedEmpty")); 
        $this->assertTrue(session()->exists("test.nonEmpty")); //Fails
        $this->assertTrue(session()->exists("test.empty")); //Fails

    }
```

The cause seems to be that `session()->exists` uses `Arr::exists` which does not work with the dot notation. 

I'm not sure what the aim of this method is but if it is meant to fulfil a supplementary role to `has` then it should work with the dot notation. 

However if the purpose is to expose the `Arr::exists` method directly on the session store then I guess the current behaviour is correct. 

Edit: Just not note, the support for the dot notation in the session is not really documented so I can see this just being a clarification in the documentation instead of an actual change in behaviour.

**Comment by themsaid** [comment]
opened a PR with the suggested feature, thanks. https://github.com/laravel/framework/pull/22934
