### ISSUE TITLE
Saving to Session File doesn't update when values are changed

### ISSUE THREAD

**Issue by richardhughes** [laravel/framework#22940]
- Laravel Version: 5.5.32
- PHP Version: 7.1.13

### Description:
When using the default session file store, if you add a value in the middleware using the Session facade or the helper function `session(['key' => 'data']);` and update it on the next request it persists the original value. Tried deleting the key using the Session facade and it still produces the same results. 

### Steps To Reproduce:
1. Create a Middleware class and set a session variable. For example 

```
session([
            'key' => true
        ]);
```

2. Open up the welcome.blade.php file and try and access the session variable `{{session('key')}}`. This will show 1 which is correct.

3. Change the session to:

```
session([
            'key' => false
        ]);
```
4. Reload the welcome.blade.php file and it still shows as 1 which is incorrect.

**Comment by Kyslik** [comment]
Does this happen in both _AfterMiddleware_ and _BeforeMiddleware_? https://laravel.com/docs/5.5/middleware#defining-middleware

How do you register your middleware? [check this SO question](https://stackoverflow.com/questions/29797952/session-not-working-in-middleware-laravel-5) - ordering is important.

This issue does not seem to be a bug and will get closed.

**Comment by themsaid** [comment]
Can't replicate this, you need to share more details on the forums for people to be able to help, show how the middleware looks like and how it's assigned to the route.

Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
