### ISSUE TITLE
Using fields casted to a date for relationships fails.

### ISSUE THREAD

**Issue by BrandonSurowiec** [laravel/framework#22942]
- Laravel Version: 5.5.32
- PHP Version: 7.1
- Database Driver & Version: Mysql

### Description:

Given the following:

```php

class ModelA {
   $casts = ['some_date' => 'date'];
}

class ModelB
{
   $casts = ['some_date' => 'date'];

    function a()
    {
        return $this->hasMany(ModelA::class, 'some_date', 'some_date');
    }

}


ModelB::first()->a;

```

Throws an `ErrorException (E_WARNING) Illegal offset type`. We'll need to make a PR/fix to allow Laravel to use the original string version of the date to make the relationship.

```php

    // vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php

    /**
     * Build model dictionary keyed by the relation's foreign key.
     *
     * @param  \Illuminate\Database\Eloquent\Collection  $results
     * @return array
     */
    protected function buildDictionary(Collection $results)
    {
        $foreign = $this->getForeignKeyName();
 
        return $results->mapToDictionary(function ($result) use ($foreign) {
            return [$result->{$foreign} => $result]; // What errors
        })->all();
    }
 ```

**Comment by themsaid** [comment]
This would be a breaking change, and could be a bit opinionated to, please move the issue to laravel/internals so people can discuss it first and collect some feedback.

For suggestions and feature requests please use the https://github.com/laravel/internals repo.

**Comment by BrandonSurowiec** [comment]
Created: https://github.com/laravel/internals/issues/978
