### ISSUE TITLE
Illuminate\Queue\CallQueuedHandler uses a non existent function in Illuminate\Contracts\Bus\Dispatcher

### ISSUE THREAD

**Issue by Naouak** [laravel/framework#22951]
- Laravel Version: 5.5.32
- PHP Version: Irrelevant
- Database Driver & Version: Irrelevant

### Description:

https://github.com/laravel/framework/blob/f50e2004dfa40de895cd841a0a94acef5b417900/src/Illuminate/Queue/CallQueuedHandler.php#L70

In this file, `$this->dispatcher`  is an instance of Illuminate\Contracts\Bus\Dispatcher.
Illuminate\Contracts\Bus\Dispatcher has no method getCommandHandler defined so when mockery create a mock of the dispatcher, the function getCommandHandler is not available.
You get this error:
```
BadMethodCallException : Method Mockery_0_Illuminate_Contracts_Bus_Dispatcher::getCommandHandler() does not exist on this mock object
 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php:70
 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php:49
 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php:76
 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php:42
 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Queue.php:44
 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:475
 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:434
 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:369
 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:200
 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:465
// ...
```

### Steps To Reproduce:

This test generates the error.
```
<?php

class BuggyListener implements \Illuminate\Contracts\Broadcasting\ShouldBroadcast
{
    public function broadcastOn()
    {
        return [];
    }
}

class LaravelBugTest extends Illuminate\Foundation\Testing\TestCase
{
    public function testBug()
    {
        $this->expectsJobs([]);
        event(new BuggyListener());
    }

    public function createApplication()
    {
        $app = require __DIR__.'/../bootstrap/app.php';
        $app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();

        return $app;
    }
}
```

**Comment by themsaid** [comment]
It's just that the contract is missing a few methods, feel free to send a PR on 5.6 to add the missing methods.

**Comment by Jnesselr** [comment]
I'm currently getting the same error: BadMethodCallException : Method Mockery_0_Illuminate_Contracts_Bus_Dispatcher::getCommandHandler() does not exist on this mock object

I've upgraded to version 5.6.26. What's weird to me is that I can use the expectsJobs in another context where I use "dispatch" directly, but it's failing in this context where I'm expecting it to be fired as a reaction from an event.

**Comment by jcooke22** [comment]
I was also getting this error on Laravel 5.3:
> BadMethodCallException : Method Mockery_0_Illuminate_Contracts_Bus_Dispatcher::getCommandHandler() does not exist on this mock object

I'm not able to upgrade the Laravel version to 5.6 right now so I implemented a workaround by overriding the `withoutJobs()` method on `TestCase` to use a custom `Dispatcher` interface which includes the missing method signatures.

[TestCase](https://gist.github.com/jcooke22/b2997c8e991a6a667f7edb68f9436015)
[Dispatcher](https://gist.github.com/jcooke22/eef2ec16e152934ebdd1aa60b953e3cb)

**Comment by coreation** [comment]
> .6.26. What's weird to me is that I can use the expectsJobs in another context where I use "dispatch" directly, but it's failing in this context where I'm expecting it to be fired as a reaction from an event.

Did you find a solution for this one?

**Comment by Jnesselr** [comment]
> > .6.26. What's weird to me is that I can use the expectsJobs in another context where I use "dispatch" directly, but it's failing in this context where I'm expecting it to be fired as a reaction from an event.
> 
> Did you find a solution for this one?

I did! Finally. And I made a pull request to boot! (Which is linked above)
