### ISSUE TITLE
[5.4] Filesystem delete() does not work with Collection wrapper

### ISSUE THREAD

**Issue by spaceemotion** [laravel/framework#22954]
- Laravel Version: 5.4.36
- PHP Version: 7.2

### Description:
I'm not sure if this has been fixed in 5.5/5.6, but I recently stumbled upon this silently failing scenario where deleting files that are passed as a laravel collection simply returns "false" without any indication as to why it failed. 

Looking closer at the [source code](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Filesystem/Filesystem.php#L177), it only seems to check via "is_array", which leads to the collection instance being interpreted as a file object.

### Steps To Reproduce:
- List some files using `$files = Storage::files()`
- `$collection = collect($files)` and do some filtering (e.g. contains a specific string)
- Try to use `Storage::delete($collection)` and see it fail (returns `false`)

**Comment by laurencei** [comment]
Hi @spaceemotion - best to upgrade to 5.5 and see if the problem persists. 5.4 is no longer supported.

**Comment by spaceemotion** [comment]
@laurencei The problem still is there in 5.5, @GrahamCampbell can we please re-open this?

I checked it via a tinker session in a newer, very recent project using v5.5.21. Same deal.

**Comment by laurencei** [comment]
@spaceemotion - does `Storage::delete($collection->toArray())` give the correct result?

**Comment by spaceemotion** [comment]
Yes, `toArray` or `all` indeed do delete the files.
