### ISSUE TITLE
Eager loading specific columns does not work when there is space between each column

### ISSUE THREAD

**Issue by Tkmilk** [laravel/framework#22968]
This would work.
`$users = App\Book::with('author:id,name,email')->get(); `

This would not. 
`$users = App\Book::with('author:id, name, email')->get();`

It gives this error.
`Unknown column ' name' in 'field list'`

I think the space is detected as part of the table's name.

**Comment by GuidoHendriks** [comment]
So follow the documentation and don't use spaces? 😏

**Comment by Tkmilk** [comment]
Yeah, but I like spaces between my columns.

**Comment by themsaid** [comment]
That's how it works currently, sorry.

**Comment by jcsoriano** [comment]
The same thing is happening to me as @mokhosh :

```
@json(\App\Models\TagSets::with('tags:id,name,color')->get());
```

Anyone else experienced this?
