### ISSUE TITLE
fails to create UploadedFile instance for AJAX PATCH/PUT requests using FormData JS API on file method for $request object (Possible Solution Proposition)

### ISSUE THREAD

**Issue by isocroft** [laravel/framework#22967]
- Laravel Version: 5.5.0
- PHP Version: 7.0.0
- Database Driver & Version: MySQL 5.3

### Description:

I'm sure this can be added to the Symphony Core as part of the `file` method API for the Laravel `Request` object. There has been a long thread up until November last year about this issue. Well, this issue log is to present a long lasting solution that works. This issue has to do with the fact that Laravel lacks the ability to properly parse and extract data from a PUT/PATCH request stream for file uploads

Is there a way i can modify the core code to include this piece of [code](https://gist.github.com/devmycloud/df28012101fbc55d8de1737762b70348) ?

If there is a way, i am willing to send in a pull request for this promptly. The gist code (see link) above was posted by @devmycloud 

### Steps To Reproduce:

```js
var file_input = document.querySelector('.document[type="file"]');

file_input.addEventListener('change', function(e){
 
      var xhr = new XMLHttpRequest, formdata = new FormData, file = e.target.files[0];

     xhr.open('PUT', 'http://localhost:4000/upload', false);

     formadata.append('document', file);

     xhr.onreadystatechange = function(e){
             if(e.type == 'load'){
                    console.log(this.responseText);
             }else if(e.type == 'readystatechange' && this.readyState == 4){
                   if(this.status === 200){
                           console.log(this.responseText);
                   }
             }
    };
    
     xhr.send(formdata);

}, false);
```
```php

      Route::put('upload', 'UploadsController@doUpload');
```

```php

class UploadsController extends Controller {

       # Assuming this to be a Laravel Controller at the '/upload' route
       # URL: http://localhost:4000/upload

        public function doUpload (Request $request){

                  return response()->json($request->file('document')); 
                  # return response()->json($request->document);
                  # return response()->json($request->all());                

                 //  all above prints an empty upload object to the screen
         }
}

```

The code above reproduces the issue

**Comment by sisve** [comment]
It would be highly relevant to give us a ling to the thread you're talking about, and perhaps add some steps to reproduce.

**Comment by themsaid** [comment]
Please complete the issue report template, this issue is messing Steps to Reproduce.

**Comment by isocroft** [comment]
@sisve here is the link to the issue I'm referencing [LINK](https://github.com/laravel/framework/issues/13457). I'm up for solutions and not debates. The issue i have confirmed is from Symphony. I just wanted to confirm a PR to the Symphony project will mean that Laravel gets the issue solved.

**Comment by themsaid** [comment]
Please open a PR with your suggested changes.
