### ISSUE TITLE
[Question] Makes sense the authorization methods accept multiple abilities?

### ISSUE THREAD

**Issue by lguima** [laravel/framework#22962]
- Laravel Version: 5.5.27
- PHP Version: 7.2.1
- Database Driver & Version: MySQL 5.7.21

### Description:
I'm creating the following abilities:
- `post`
- `post.store`
- `post.update`
- `post.delete`

So if I want to grant all post privileges, I just give the ability `post`. Or if I want to grant only `post.store`, then I give just this one.

Then on the method store() I would check for both abilities, `post` OR `post.store`.

Makes sense?

**Comment by autaut03** [comment]
Use ACL package, such as [that one](https://github.com/JosephSilber/bouncer). I believe laravel's gate only checks by given ability string and completly ignores any other circumstances - and this is right.

**Comment by lguima** [comment]
Thanks, @autaut03, I'm using [spatie/laravel-permission](https://github.com/spatie/laravel-permission) package, but both have no methods allowing the approach I mentioned.

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.

**Comment by lguima** [comment]
Sorry, I was asking to know if it could be became a PR.
