### ISSUE TITLE
Returns get route instead of post request.

### ISSUE THREAD

**Issue by prdpspkt** [laravel/framework#22978]
- Laravel Version: 5.6
- PHP Version: 7.2
- Database Driver & Version:
MYSQL
### Description:
I have a problem in sending data to server from browser. When I submit form then it takes get route instead of post route.
### Steps To Reproduce:
If this  problem is specific to my installation then steps cannot be reproduced.
`Route::resource("/pages/");`
Form has` POST` method with `action="/pages"`

**Comment by browner12** [comment]
Welcome to Laravel! We are glad to have you as part of the community.

Unfortunately GitHub is not an appropriate platform for general application issues. This is only for issues/bugs with the framework code itself.

Please close your issue, and instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

Laravel Slack (https://larachat.co/)
Laravel.io Forum (https://laravel.io/forum)
Laracasts Forum (https://laracasts.com/discuss)
StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks!

**Comment by prdpspkt** [comment]
Ok, Thanks
