### ISSUE TITLE
[5.5.33] Collection order messes up when mail view is sent

### ISSUE THREAD

**Issue by forkiven** [laravel/framework#22976]
## Description

The collection order is rendered incorrectly when mailable is actually sent out via email. It appears the last item in the collection gets put first, although I've only tried a few different combinations but the order is always incorrect, even with only 2 entities, when and only when the Mailable is actually sent (it's fine in the browser when the mailable is returned).

## Steps to reproduce

- Have collection of entities in a specific order.
- Within a mail view - loop through collection and render a separate view per entity.
- Send out mail view.

## Extra info

- Sending the mailable out manually from the route also produces the issue.
- Issue occurs whether sent via homestead or remote.
- Logs show collection order is correct just before sending mail out.
- Tests show the collection order is correct.
- Returned mailable in browser shows order is correct.

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.

Also please share code so people can help, let us know how we can replicate your issue in a fresh laravel app so we understand better what's going on.
