### ISSUE TITLE
Inflector error with php v5.6

### ISSUE THREAD

**Issue by hosseinizadeh** [laravel/framework#22979]
- Laravel Version: 5.4.36
- PHP Version: 5.6.32

### Description:
update my project and:
syntax error, unexpected ':', expecting ';' or '{' in Inflector.php (line 265) laravel

delete the composer.lock file and vendor, then run composer install.
but yet still have error

add "doctrine/inflector": "1.1.x", in require composer.json and delete the composer.lock file and vendor, then run composer install. and fix the error

tnx

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.

**Comment by prudhvi-php** [comment]
thanks @hosseinizadeh your tip solved my issue.
