### ISSUE TITLE
SessionGuard::cycleRememberToken recreates deleted user

### ISSUE THREAD

**Issue by stidges** [laravel/framework#22975]
- Laravel Version: 5.5.33
- PHP Version: 7.0.27

### Description:

While working on an account deletion feature I ran into this; I want to logout the user only if the account deletion succeeds, and want to use the logout method because it contains (single sign-on) logic which has to run. Running the logout method after deleting the user will cause the user to be recreated, because the `cycleRememberToken` method updates and saves the user model.

### Steps To Reproduce:

``` php
$user = Auth::user();

if ($user->delete()) {
    // $user->exists === false
    Auth::logout();
    // $user->exists === true
}

// Redirect back to auth-protected route...
```

**Comment by laurencei** [comment]
In what instance would `$user->delete()` realistically ever return false?

Seems fairly safe to do

```
$user = Auth::user();
Auth::logout();
$user->delete();
```

**Comment by stidges** [comment]
I'm utilizing model events. If one of the `deleting` handlers returns false the model isn't deleted and false is returned

**Comment by laurencei** [comment]
I dont really see a solution other than you extending `SessionGuard` and writing your own `cycleRememberToken`.

OR - log the user out and delete. But if the delete fails - log them back in.

```
$user = Auth::user();
Auth::logout();
if (! $user->delete()) {
    Auth::loginUsingId($user->id)`
}
```

**Comment by crynobone** [comment]
Shouldn't you be using deleted event instead of deleting?

**Comment by stidges** [comment]
I have to use `deleting` here because I want to cancel the deletion of the user if any of my preconditions fail. Using `deleted` wouldn't allow me to do this, as it is run after the model was already deleted. 

I feel like this is a bug that needs to be solved at the framework level, so I created a pull request (#22983) to address this issue.
