### ISSUE TITLE
assertSelectHasOptions passes even when an expected option value is missing

### ISSUE THREAD

**Issue by joelclermont** [laravel/framework#22972]
- Laravel Version: 5.5.21
- PHP Version: 7.2.1
- Database Driver & Version: mysql 5.7.18

### Description:
Dusk's `assertSelectHasOptions` assertion passes even when an expected option value is missing.

### Steps To Reproduce:
Add the following select element to the default home page:
```html
<select name="test">
    <option value="1">A</option>
    <option value="1">A</option>
</select>
```
Run this Dusk test:
```php
$this->browse(function (Browser $browser) {
    $browser->visit('/')->assertSelectHasOptions('test', [1, 2]);
});
```

I would expect that to fail because an option with value 2 is not present on the page, but it passes.

**Comment by themsaid** [comment]
Please report on the correct repository https://github.com/laravel/dusk
