### ISSUE TITLE
URL::previous sometimes returns undesirable URLs

### ISSUE THREAD

**Issue by Alexander--** [laravel/framework#22984]
- Laravel Version: 5.5
- PHP Version: 7

### Description:
Sometimes `URL::previous` returns me unexpected and highly undesirable things like `favicon.ico` or random nonexisting URLs. This seems to happen because `StartSession` is happy to invoke `storeCurrentUrl` before learning content type of response and even before finding out whether it succeeded or not.

This behavior is non-intuitive and makes that method largely useless (because I can not control order of HTTP requests, made by browser). I'd like `URL::previous` to return only URLs, associated with successfull requests to proper routes.

### Steps To Reproduce:

Not clear yet.

For now I am going to use an additional Middleware, that wil check content type and error code of response after everything else finishes processing.

**Comment by sisve** [comment]
Why do you execute the StartSession middleware for non-dynamic requests, like the favicon?

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
