### ISSUE TITLE
Model update fails if arbitrary values assigned beforehand.

### ISSUE THREAD

**Issue by websanova** [laravel/framework#22980]
- Laravel Version: 5.3.x
- PHP Version: 7.1
- Database Driver & Version: N/A

### Description:

The `$model->update()` call fails if we assign some arbitrary values to the model beforehand.

As a shortcut I often append some arbitrary attributes to the model when I pass them around. 

Seems the `update` call is trying to save them rather than sticking with what is specified in this call.

### Steps To Reproduce:

// This is fine and what I expect.
$model->some_val = 123;
$model->save();

// This crashes.
$model->val_does_not_exist_in_db = 123;
$model->update(['some_val' => 123]);

Seems it tries to save `val_does_not_exist_in_db`?

This seems like a bug to me, it's not specified, so it shouldn't be saved using `update`.

And NO, we should not have to use `fillable` in this case.

**Comment by 36864** [comment]
Model's update works by calling `->fill()` and then `->save()` on the model. This helps to call the Saving event, which is meant to be called any time there's an update to an existing model or a new model is stored to the database.

Even `fillable` won't help you with this. You'll need to unset any additional properties from the object before saving it.

Alternatively, you can get the builder instance and update through that, but you'd miss out on events.

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
