### ISSUE TITLE
Laravel whereHas different connection

### ISSUE THREAD

**Issue by maguilar92** [laravel/framework#22985]
- Laravel Version: 5.5.33
- PHP Version: 7.1.1
- Database Driver & Version: mysql & 5.6.35

### Description:
Using multiple database when use whereHas generates:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'hv_global.hvp_products' doesn't exist 

### Steps To Reproduce:
Generate two models in different database connection and use eloquent whereHas.

**Comment by themsaid** [comment]
Querying relationships on different connections requires some configuration so you instruct Eloquent to do what you want, please read the docs and ask on the forums for more information, try to share as much details as possible with code examples for people to be able to help.

**Comment by skalero01** [comment]
I had it working on 5.5 and after 5.6 update it crash.. someone know what happened?

**Comment by clod986** [comment]
My setup works fine for eager lading but it doesn't work for querying across connections; is this feature supported?

**Comment by maguilar92** [comment]
@clod986 Now there is a package that adds this feature, but only works when database are in same server:

https://github.com/hoyvoy/laravel-cross-database-subqueries
