### ISSUE TITLE
member of Cache::tags reference key is always growing.

### ISSUE THREAD

**Issue by Except10n** [laravel/framework#22981]
- Laravel Version: 5.5.X
- PHP Version: *
- Database Driver & Version: *

### Description:

I'm not sure if this is a bug or a design compromise.
If you use the Cache::tags feature, it can cause serious space waste.

In a system， tagged cache is limited,  but member of “standard_ref” it's always growing， Even if the key expires，member of “standard_ref“  not clear

### Steps To Reproduce:
```
Cache::tags('a')->put(k, v, 1);
```

**Comment by themsaid** [comment]
Please elaborate, I don't seem to understand what's the issue.

**Comment by Except10n** [comment]
if use "TaggedCache" , It will storage “reference key” ，The passage of time it's getting too big.

**Comment by tillkruss** [comment]
That's how the tagged cache works. If you have a better suggestion, please free to discuss it in internals, or submit a PR.
