### ISSUE TITLE
Queues: MaxAttemptsExceededException Should not be going to failed() function

### ISSUE THREAD

**Issue by odannyc** [laravel/framework#22993]
- Laravel Version: 5.5.21
- PHP Version: 7.2
- Database Driver & Version: Mysql 5.7.18

### Description:
When Dispatching a Job and the job fails Laravel will send 2 Exceptions to the `failed()` function inside of my job. The first is my true Exception I throw within my logic, and the second is: `MaxAttemptsExceededException`.
This is probably intended but I have some logging/cleanup I do in the failed() function which is triggered twice because of that second laravel exception.
Should this be different?
Or is there something else that I should be doing?

### Steps To Reproduce:
Create new Job
Set retries to 1
Add a `failed()` method to the class and Log something in there.
In your `handle()` method throw an exception
Dispatch the Job and see Logs

You will notice 2 Logs, 1 from you and the other from laravel

**Comment by laurencei** [comment]
You could always do

```
if (! $e instanceof MaxAttemptsExceededException::class) {
   // cleanup
}
```

The problem is there are some pathways that can occur which the only time `failed()` is called is from the MaxAttempts (i.e. timeouts etc) - and that is why it was added if I remember correctly.

**Comment by lancepioch** [comment]
Someone might be depending on this behavior (possibly breaking BC), so for the time being whether or not this will be changed, @laurencei's solution should work for you.
