### ISSUE TITLE
help me please

### ISSUE THREAD

**Issue by Mickey248** [laravel/framework#22992]
it error i need to fix
![image](https://user-images.githubusercontent.com/26427913/35701039-5a9d06da-07c7-11e8-8438-da70727b60be.png)

![image](https://user-images.githubusercontent.com/26427913/35701056-64526a94-07c7-11e8-85ac-3e51b46dda95.png)

please help me

**Comment by lagbox** [comment]
This is not a support forum. This issue tracker is for bugs in the framework only.

If you need Laravel related support please use the forums at laravel.io or laracasts for more help. You also have the option of getting live support on irc on freenode #laravel or on larachat (slack).

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
