### ISSUE TITLE
question: what wrong this test case?

### ISSUE THREAD

**Issue by hhniao** [laravel/framework#22994]
how to do can be success to run this test case?
    
    git clone https://github.com/laravel/framework.git
    compose install --verbose
    vendor/phpunit/phpunit/phpunit --filter testRefreshCommandCallsCommandsWithProperArguments DatabaseMigrationRefreshCommandTest tests/Database/DatabaseMigrationRefreshCommandTest.php --debug`
    
    Runtime:       PHP 7.1.12 with Xdebug 2.6.0beta1
    Configuration: D:\web\github\laravel\framework\phpunit.xml.dist
    
    Test 'Illuminate\Tests\Database\DatabaseMigrationRefreshCommandTest::testRefreshCommandCallsCommandsWithProperArguments' started
    Test 'Illuminate\Tests\Database\DatabaseMigrationRefreshCommandTest::testRefreshCommandCallsCommandsWithProperArguments' ended
    
    
    Time: 156 ms, Memory: 10.00MB
    
    There was 1 error:
    
    1) Illuminate\Tests\Database\DatabaseMigrationRefreshCommandTest::testRefreshCommandCallsCommandsWithProperArguments
    Mockery\Exception\NoMatchingExpectationException: No matching handler found for Mockery_2_Illuminate_Database_Console_Migrations_ResetCommand::run(object(Symfony\Component\Console\Input\ArrayInput), object(Illuminate\Console\OutputStyle)). Either the method was unexpected or its arguments matched no expected argument list for this method
    
    Objects: ( array (
      'Symfony\\Component\\Console\\Input\\ArrayInput' =>
      array (
        'class' => 'Symfony\\Component\\Console\\Input\\ArrayInput',
        'properties' =>
        array (
        ),
      ),
      'Illuminate\\Console\\OutputStyle' =>
      array (
        'class' => 'Illuminate\\Console\\OutputStyle',
        'properties' =>
        array (
        ),
      ),
    ))
    
    D:\web\github\laravel\framework\vendor\mockery\mockery\library\Mockery\ExpectationDirector.php:92
    D:\web\github\laravel\framework\src\Illuminate\Console\Command.php:198
    D:\web\github\laravel\framework\src\Illuminate\Database\Console\Migrations\RefreshCommand.php:104
    D:\web\github\laravel\framework\src\Illuminate\Database\Console\Migrations\RefreshCommand.php:55
    D:\web\github\laravel\framework\src\Illuminate\Container\BoundMethod.php:29
    D:\web\github\laravel\framework\src\Illuminate\Container\BoundMethod.php:87
    D:\web\github\laravel\framework\src\Illuminate\Container\BoundMethod.php:31
    D:\web\github\laravel\framework\src\Illuminate\Container\Container.php:549
    D:\web\github\laravel\framework\src\Illuminate\Console\Command.php:183
    D:\web\github\laravel\framework\vendor\symfony\console\Command\Command.php:252
    D:\web\github\laravel\framework\src\Illuminate\Console\Command.php:170
    D:\web\github\laravel\framework\tests\Database\DatabaseMigrationRefreshCommandTest.php:68
    D:\web\github\laravel\framework\tests\Database\DatabaseMigrationRefreshCommandTest.php:41

**Comment by browner12** [comment]
Welcome to Laravel! We are glad to have you as part of the community.

Unfortunately GitHub is not an appropriate platform for general application issues. This is only for issues/bugs with the framework code itself.

Please close your issue, and instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

Laravel Slack (https://larachat.co/)
Laravel.io Forum (https://laravel.io/forum)
Laracasts Forum (https://laracasts.com/discuss)
StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks!

**Comment by hhniao** [comment]
ok, thanks. 
ps: i have try to run in linux. all are ok. 
but, mabe have a small problem.
if i running with root.
tests/Filesystem/FilesystemTest.php::testIsWritable will failure.
because root can be write all?
