### ISSUE TITLE
Store only .xls file problem

### ISSUE THREAD

**Issue by betterapp** [laravel/framework#23008]
- Laravel Version: 5.4
- PHP Version: 7.1
- Windows 10
- XAMPP

### Description:
I have code like this:

`$request->file('file')->store('import');`

when I try to upload .doc, .jpg, .txt file everything is ok. But when I try to upload .xlsx file
i get:

> ErrorException                                                                         
 fopen(E:\www\site.dev\storage\app\import/cQMONMgf4qCS2t8YZNfeGALDVmtggTkq7BVj7Tzc.):  failed to open stream: Permission denied
in Local.php (line 151)
at HandleExceptions->handleError(2, 'fopen(E:\\www\\site.dev\\storage\\app\\import/cQMONMgf4qCS2t8YZNfeGALDVmtggTkq7BVj7Tzc.): failed to open stream: Permission denied', 'E:\\www\\site.dev\\vendor\\league\\flysystem\\src\\Adapter\\Local.php', 151, array('path' => 'import/cQMONMgf4qCS2t8YZNfeGALDVmtggTkq7BVj7Tzc.', 'resource' => resource, 'config' => object(Config), 'location' => 'E:\\www\\site.dev\\storage\\app\\import/cQMONMgf4qCS2t8YZNfeGALDVmtggTkq7BVj7Tzc.'))

As I see laravel try to store file without extension. Problem occured when guessExtension() return null

**Comment by betterapp** [comment]
https://github.com/laravel/framework/pull/23011

**Comment by GrahamCampbell** [comment]
Thanks for the report. This will be fixed on 5.5+.

**Comment by afliw** [comment]
This issue is still happening with Excel 97-2003 files (_.xls_).

I fixed it partially using the solution that @GrahamCampbell proposed in #23009.

Laravel 5.6
PHP 7.1.8
Windows 10

**Comment by pda-code** [comment]
`$request->file('excel_file')->store('upload_lookup_tables');`

returns

fopen(C:\MyProjects\php\tts\TechInsights\src\storage\app\upload_lookup_tables/3K9tAFQ5QUhGsLypVe9wRarrAoXO2t8lDh7JNwTH.): failed to open stream: Permission denied

Happens in .xls, .xlsx files.

- Windows 10
- Wamp64
- Laravel 5.6

**The MAJOR bug still exist.** 

Is there anyone on the planet using laravel on windows have tried to upload a single XLS file?

**Comment by biopowder** [comment]
Same for .csv files.

Windows 10
Xampp
Larvel 5.6.26
PHP 7.2
