### ISSUE TITLE
in ResourceCollection I want remove links

### ISSUE THREAD

**Issue by acodercat** [laravel/framework#23000]
- Laravel Version: 5.5
- PHP Version:7.1
- Database Driver & Version:mysql 5.7

### Description:
in ResourceCollection I want remove links

### Steps To Reproduce:
in ResourceCollection I want remove links

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I suggest closing your issue ticket here? Instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.
