### ISSUE TITLE
in ResourceCollection I want remove links

### ISSUE THREAD

**Issue by acodercat** [laravel/framework#23002]
- Laravel Version: 5.5.2
- PHP Version:7.1
- Database Driver & Version:mysql 5.7

### Description:

in ResourceCollection I want remove links

### Steps To Reproduce:

in ResourceCollection I want remove links

**Comment by acodercat** [comment]
please!!!!!!!

**Comment by decadence** [comment]
Welcome to Laravel! We are glad to have you as part of the community.

Unfortunately GitHub is not an appropriate platform for general application issues. This is only for issues/bugs with the framework code itself.

Please close your issue, and instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

Laravel Slack (https://larachat.co/)
Laravel.io Forum (https://laravel.io/forum)
Laracasts Forum (https://laracasts.com/discuss)
StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks!

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
