### ISSUE TITLE
Blade compiler has a public function “if”. Why is this, when “if” is reserved word in PHP.

### ISSUE THREAD

**Issue by drnkwati** [laravel/framework#23006]
I notice the Custom Blade "If" Directives function is declared exactly as "if" in blade compiler source code.
I felt uncomfortable about this as if is a reserved PHP keyword. Will this not raise issues? 
I suggest the name be changed to something else maybe _if.
`/**
     * Register an "if" statement directive.
     *
     * @param  string  $name
     * @param  callable  $callback
     * @return void

    public function if($name, callable $callback)
    {
        $this->conditions[$name] = $callback;
`

**Comment by godfrey3835** [comment]
I think it would not raise issue. 
You can see http://www.php.net/manual/en/reserved.keywords.php
```
As of PHP 7.0.0 these keywords are allowed as property, constant, 
and method names of classes, interfaces and traits, 
except that class may not be used as constant name.
```
