### ISSUE TITLE
Validate method returns non-validated values when using array

### ISSUE THREAD

**Issue by noamcore** [laravel/framework#23016]
- Laravel Version: v5.5.33
- PHP Version: 7.2.1

### Description:

When use the `validate` method from `Illuminate\Http\Request`, the returned value contains keys not validated.

### Steps To Reproduce:

```php
<?php

use Illuminate\Http\Request;

class Example {
  public function valid(Request $request) {
    $data = $request->validate([
      'relations.address.*.number' => 'required|integer',
      'relations.address.*.city_id' => 'required|integer|exists:cities,id'
    ]);
    dd($data); // also returns "non_validated" key with the respective value
  }
}

// POST DATA
// { relations: { address: [{ non_validated: true, number: 1111, city_id: 1 }, { non_validated: true, number: 222, city_id: 2 }]  } }
```

**Comment by themsaid** [comment]
Yes it returns the parent level keys.

**Comment by noamcore** [comment]
Have you read it at least? I'm not complain about parent level keys...

It should (as I understand) returns only validated data, something like array_intersect. But Ok, seems like this is not so important to wast time testing.

**Comment by harrysbaraini** [comment]
Sorry @themsaid, I know it's closed but I'm in the same situation as @noamcore.

I don't like breaking the chain of methods and I consider using `&$data` a bad practice and really worst, but I had to fix a issue really fast and it just worked for me...

I overwrote the `validated` method on my FormRequest class:

```php
public function validated()
    {
        $rules = $this->container->call([$this, 'rules']);

        $data = [];

        collect($rules)->keys()->map(function ($rule) {
            return $rule;
        })->unique()->each(function ($rule) use (&$data) {
            data_set($data, $rule, array_get($this->all(), $rule));
        });

        return $data;
    }
```

It's 3am.. when sun shines again, I'll try a better solution. Of course it may not work on many other cases, like have a `field.*.subfield` rule, but for associative data like `field.subfield` it does the job.
