### ISSUE TITLE
Cookies created only on main route

### ISSUE THREAD

**Issue by Naxon** [laravel/framework#23018]
- Laravel Version: 5.5.33
- PHP Version: 7.2.0
- Database Driver & Version: MySQL 5.7.20

### Description:
For some reason, cookies (such as laravel_session / XSRF-TOKEN) are created only when a visitor visits the main route (/). If he goes directly to an "inner" route, the cookies aren't created at all until he visits the main route.

### Steps To Reproduce:
Try going directly to an inner route, create cookie / simply look at the cookies existing ones (don't exist).

**Comment by sisve** [comment]
I am unable to reproduce this. It sounds like you're only registering the relevant middlewares on the root route. Can you reproduce this in a new (blank) version of Laravel?

**Comment by Naxon** [comment]
Will try.

Which middleware is responsible for this?

**Comment by sisve** [comment]
The StartSession middleware and the VerifyCsrfToken middleware.
