### ISSUE TITLE
Comments are not forward engineered to columns in postgres schema

### ISSUE THREAD

**Issue by phpguru** [laravel/framework#23012]
- Laravel Version: 5.5.32
- PHP Version: 7.1.11
- Database Driver & Version: pdo, pdo_postgres 
PostgreSQL 10.1 on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18) 6.3.0 20170516, 64-bit

### Description:

After running the following migration against Postgres database in Docker container:

    public function up()
    {
        Schema::create('sample', function (Blueprint $table) {
            $table->increments('id')->comment('primary key');
            $table->timestamps();
        });
    }

I could be doing something wrong, but it appears the comment is not created in the schema. 

The SQL that needs to happen is [1]

    COMMENT ON COLUMN sample.id IS 'primary key'; 

### Steps To Reproduce:

Try migrating against postgres with a column comment. 

If this is indeed a bug, if you can point me to the point in the code where this ought to happen I would be happy to attempt a PR for it.

[1] https://www.postgresql.org/docs/9.1/static/sql-comment.html

**Comment by mfn** [comment]
Already fixed in 5.6 via https://github.com/laravel/framework/pull/21855
