### ISSUE TITLE
Method castKey breaks big integers

### ISSUE THREAD

**Issue by mpskovvang** [laravel/framework#23022]
The `is_numeric` function does not take 64 bit unsigned integers into account which results in integer overflow.

13832357100640009167 converts to 9223372036854775807.

This is breaking my application. I'll consider a workaround later and submit a PR if I succeed to solve the issue.

https://github.com/laravel/framework/blob/00fce7ee8d96c074a3b91396fa5f4b0e6bbbb12c/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php#L502

Affected version 5.5.33 and master branch.

**Comment by mpskovvang** [comment]
Perhaps it should respect `$keyType` and `$casts` in Illuminate\Database\Eloquent\Model.php?

Unfortunatly, they are out of scope and would require some heavy changes. Another - and easier solution - would be to compare the key agianst PHP_INT_MAX.

`return is_numeric($key) && $key < PHP_INT_MAX ? (int) $key : (string) $key;`

What are your thoughts?

**Comment by mpskovvang** [comment]
@tillkruss Is this not considered as a bug or is big numbers not supported by Laravel?

I've found that the parent model's `$casts` are available at the `castKey` method but unfortunately we need the `$casts` of the pivot model.

I believe it makes sense to respect the model's `$casts` definitions as the application otherwise becomes inconsistent. The other attributes of the pivot do respect the casting by using the `castAttributes` method.

**Comment by tillkruss** [comment]
It's a limitation of PHP, not the framework. Feel free to submit a PR.

**Comment by staudenmeir** [comment]
This will be fixed in 5.7: #24168

**Comment by laurencei** [comment]
Closing as PR merged
