### ISSUE TITLE
Do not allow forward slashes for artisan app:name

### ISSUE THREAD

**Issue by pultho** [laravel/framework#23020]
- Laravel Version: 5.5
- PHP Version: 7.1
- Database Driver & Version: n.a.

### Description:
Please validate the name attribute for the **artisan app:name** command. If a user accidentally uses a forward slash instead of backsplashes the namespaces for the project are ruined.
PHP can't correctly interpret the forward slash in the changed namespaces and artisan CLI wont work afterwards.

A simple warning would be enough IMO.

### Steps To Reproduce:
Use artisan app:name App/My/Name and rename the project root namespace with forward slashes instead for two back slashes (of course not in production or your current project).

**Comment by bonzai** [comment]
#8588
