### ISSUE TITLE
Eloquent first returns stdClass instead of an Eloquent Model in version 5.5

### ISSUE THREAD

**Issue by drnkwati** [laravel/framework#23030]
Hi guys 
Why is eloquent query first returning a stdObj instead of an eloquent model
Has any one had this issue. Am using version 5.5

**Comment by BrandonSurowiec** [comment]
Do you have a code sample to reproduce this? 

It seems like you are probably using the DB facade:
```
\DB::table('something')->first(); // will return stdClass
```

This is intended since it doesn't know that it should load a specific model, nor should it. If you use your model it will return an Eloquent Model:

```
Something::first(); // App\Something Eloquent Model instance.
```

Can explain further?

**Comment by browner12** [comment]
Welcome to Laravel! We are glad to have you as part of the community.

Unfortunately GitHub is not an appropriate platform for general application issues. This is only for issues/bugs with the framework code itself.

Please close your issue, and instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

Laravel Slack (https://larachat.co/)
Laravel.io Forum (https://laravel.io/forum)
Laracasts Forum (https://laracasts.com/discuss)
StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks!

**Comment by drnkwati** [comment]
Sorry guys. I never noticed i was asking in the wrong place.
I will close the issue immediately.
