### ISSUE TITLE
getCountForpagination returns Illuminate\Database\Eloquent\Builder Object instead of int

### ISSUE THREAD

**Issue by AAniculaesei-modus** [laravel/framework#23033]
- Laravel Version: 5.3.30
- PHP Version: 5.6
- Database Driver & Version:

### Description:

I am trying to get the number of results with
`$total = $this->query->getCountForPagination();`

And instead of receiving an (int) like I see on the documentation, a `object(Illuminate\Database\Eloquent\Builder)` is returned

Any reason for that ?

**Comment by sisve** [comment]
Your steps to reproduce is not filled in. It sounds like a problem in your code, not in the getCountForPagination method.
