### ISSUE TITLE
Multiselect not 

### ISSUE THREAD

**Issue by tommym9** [laravel/framework#23037]
- Laravel Version: 5.4.28
- PHP Version: 7.1.4-1+deb.sury.org~xenial+1
- Database Driver & Version: MySQL Community Edition - Standard (GPL) 5.7.19

### Description:
When creating a multi-select field with `Form::select()` the submitted values aren't selected by default on reload.

This isn't the case for single select elements.

### Steps To Reproduce:

- Create a route that will accept GET parameters to filter a set of results
- Add a form `{!! Form::open(array('ROUTE_NAME', 'method' => 'get')) !!}`
- Add a single select field `{!! Form::select('status', [null => '-- Filter by Status --'] + $statuses, null, ['placeholder' => 'Filter by Status']) !!}`
- Add a multi-select field `{!! Form::select('years[]', [null => '-- Filter by Year(s) --'] + $report_years, null, ['placeholder' => 'Filter by Year(s)', 'multiple' => true]) !!}`
- Add a submit button `{!! Form::submit('Go', ['class' => 'btn btn--small']) !!}`

### Expected behaviour:

- The submitted options on both select fields are selected

### Actual behaviour:

- The submitted value for the single select is selected
- None of the multi-select values are selected

I note that I can pass a third parameter to the select element 

`{!! Form::select('years[]', [null => '-- Filter by Year(s) --'] + $report_years, [$value1, $value2], ['placeholder' => 'Filter by Year(s)', 'multiple' => true]) !!}` 

And this will set the default value, however this is ignored on form submit.

Cheers

Tom

**Comment by decadence** [comment]
5.4 is not supported. As well as Html package.
https://github.com/LaravelCollective/html

**Comment by tommym9** [comment]
Hi @decadence,

Is this bug resolved in 5.5? If so is there the possibility of a backport?

Also should I be logging this issue against https://github.com/LaravelCollective/html instead of here?

Cheers

Tom

**Comment by decadence** [comment]
`Html` is not in Laravel core for a long time so yes, you should report https://github.com/LaravelCollective/html

**Comment by tommym9** [comment]
Thanks @decadence
