### ISSUE TITLE
mix() helper function doesn't have a fallback if given path is undefined

### ISSUE THREAD

**Issue by lukasjuhas** [laravel/framework#23043]
- Laravel Version: 5.5.33
- PHP Version: 7.1.13
- Database Driver & Version: MySQL, 5.7.20

### Description:
Laravel `mix()` helper function [does not check if the given index](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Foundation/helpers.php#L589) (path to file) is defined which results to undefined index. 

For example, you have a folder `css`. When using Laravel mix, and you use `mix.copy()` or `mix.copyDirectory()`, versioning for the manifest file is not generated even if you use `mix.version()`. So then, If I try to use e.g.`<link href="{{ mix('css/icons/icons.css') }}" rel="stylesheet">`. This results to undefined index error. [There is an issue in laravel mix repo regarding this](https://github.com/JeffreyWay/laravel-mix/issues/1257).

I know that as an alternative I could use `asset()`, but the problem is, I have a custom helper function called `assetCDN` which uses `mix()` stitched together with custom CDN URL. 

So I think it would be a generally better approach to handle the `$path` passed into `mix()` helper function to have a fallback of returning the given `$path` instead if that makes sense.

For me, this came as a  result moving from `elixir()` to `mix()` where `elixir()` handles this better by returning something (original path) instead of an error.

### Steps To Reproduce:
Please see description.

Thanks!

**Comment by lukasjuhas** [comment]
I have done a bit of digging, and I realised that the mix() function *does* check for if the given path is set, but following that there is a check `if (! app('config')->get('app.debug')) {` which means that if you are in debug mode, you will get the mentioned `Undefined index` error. because the original path is not returned if you are in debug mode. 

I guess this should be removed? Or is there any particular reason why there is this check?

https://github.com/laravel/framework/blob/5.5/src/Illuminate/Foundation/helpers.php#L584-L586

This then brings me to the line above which indicates logs new exception saying "Unable to locate Mix FIile:... " which is not correct, because the mix file at this point is actually there, it's just the given path is not present in the mix manifest file.

I will follow up with a PR proposing a fix for this.

**Comment by kamui545** [comment]
I've got a similar helper and what I've done is simply catch the `InvalidArgumentException` thrown when the path is not present. You could as well catch `Exception` for the temporary `Undefined index` while waiting for a fix.

Or perhaps am I missing something and not fully understanding your problem?
