### ISSUE TITLE
Undefined index error for php artisan vendor:publish

### ISSUE THREAD

**Issue by mohansonar** [laravel/framework#23044]
- Laravel Version: 5.5.33
- PHP Version: 7.1.13
- Database Driver & Version:

### Description: 

Undefined index error for php artisan vendor:publish

In QuestionHelper.php line 53:
                    
  Undefined index:  

### Steps To Reproduce:

run this command php artisan vendor:publish

**Comment by timoschwarzer** [comment]
Which packages do you have installed?

**Comment by sisve** [comment]
We would need a full stack trace to debug this further. This is probably a specific package that has a bad call to the ask method.

**Comment by mohansonar** [comment]
This issue occurs after installing fresh laraval 5.5.33 using  following command composer create-project --prefer-dist laravel/laravel blog

**Comment by sisve** [comment]
Can you give us a full stacktrace of the problem? It should be available in the log files in storage/logs.

**Comment by john-dent** [comment]
I have had this issue too, here's the stack trace:

[2018-02-14 13:59:28] local.ERROR: Undefined index:  {"exception":"[object] (ErrorException(code: 0): Undefined index:  at /home/vagrant/code/osaris/vendor/symfony/console/Helper/QuestionHelper.php:53)
[stacktrace]
#0 /home/vagrant/code/osaris/vendor/symfony/console/Helper/QuestionHelper.php(53): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined index...', '/home/vagrant/c...', 53, Array)
#1 /home/vagrant/code/osaris/vendor/symfony/console/Helper/SymfonyQuestionHelper.php(53): Symfony\\Component\\Console\\Helper\\QuestionHelper->ask(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle), Object(Symfony\\Component\\Console\\Question\\ChoiceQuestion))
#2 /home/vagrant/code/osaris/vendor/symfony/console/Style/SymfonyStyle.php(294): Symfony\\Component\\Console\\Helper\\SymfonyQuestionHelper->ask(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle), Object(Symfony\\Component\\Console\\Question\\ChoiceQuestion))
#3 /home/vagrant/code/osaris/vendor/laravel/framework/src/Illuminate/Console/Command.php(391): Symfony\\Component\\Console\\Style\\SymfonyStyle->askQuestion(Object(Symfony\\Component\\Console\\Question\\ChoiceQuestion))
#4 /home/vagrant/code/osaris/vendor/laravel/framework/src/Illuminate/Foundation/Console/VendorPublishCommand.php(111): Illuminate\\Console\\Command->choice(Object(Symfony\\Component\\Console\\Question\\ChoiceQuestion), Array)
#5 /home/vagrant/code/osaris/vendor/laravel/framework/src/Illuminate/Foundation/Console/VendorPublishCommand.php(98): Illuminate\\Foundation\\Console\\VendorPublishCommand->promptForProviderOrTag()
#6 /home/vagrant/code/osaris/vendor/laravel/framework/src/Illuminate/Foundation/Console/VendorPublishCommand.php(73): Illuminate\\Foundation\\Console\\VendorPublishCommand->determineWhatShouldBePublished()
#7 [internal function]: Illuminate\\Foundation\\Console\\VendorPublishCommand->handle()
#8 /home/vagrant/code/osaris/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#9 /home/vagrant/code/osaris/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /home/vagrant/code/osaris/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#11 /home/vagrant/code/osaris/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#12 /home/vagrant/code/osaris/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#13 /home/vagrant/code/osaris/vendor/symfony/console/Command/Command.php(252): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#14 /home/vagrant/code/osaris/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#15 /home/vagrant/code/osaris/vendor/symfony/console/Application.php(938): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 /home/vagrant/code/osaris/vendor/symfony/console/Application.php(240): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Foundation\\Console\\VendorPublishCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /home/vagrant/code/osaris/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /home/vagrant/code/osaris/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /home/vagrant/code/osaris/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 /home/vagrant/code/osaris/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 {main}
"}

**Comment by felipemarques** [comment]
i got the same problem... any ideas?

**Comment by sisve** [comment]
@felipemarques We would probably need an application we could clone and reproduce the problem locally to attempt to at least provide a better error message or fix the problem.

**Comment by john-dent** [comment]
One thing I have realised is that vendor:publish requires arguments, such as the vendor to publish...  Defining the arguments should bypass the question helper, as this is being called to allow selection of what to publish.

Not exactly a fix, but hope it helps...

**Comment by barbushin** [comment]
Try to add `--provider="Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider"`

**Comment by RoachCn** [comment]
I also got the same problem...please give some idea...
if I add --provider=\"Stevenyangecho\UEditor\UEditorServiceProvider\" will no error, but also no files moved..

**Comment by sisve** [comment]
@RoachCn How is that the same problem? This issue is about a "Undefined index" error, and you say you have no error. It doesn't sound related at all.

**Comment by pmioni** [comment]
The error is due to the fact that vendor:publish is interactive, and you have to confirm which vendors you want to publish. If you just run it in a shell script with no arguments, the system won't receive a list of vendors to publish, hence the error.
If you want to avoid this error in your script, you need to add the "--all" argument to the publish command, like this:
`php artisan vendor:publish --all`

See:
https://laravel-news.com/vendorpublish
