### ISSUE TITLE
Inconsistency of relationship name when saving to morphTo

### ISSUE THREAD

**Issue by devonblzx** [laravel/framework#23048]
- Laravel Version: 5.5.34
- PHP Version:  7.1
- Database Driver & Version:  Verified on MySQL + SQLite

### Description:

When saving to a morphTo relationship with a camelCase name, the new related model can not be accessed at camelCase, only snake_case, which provides an inconsistency and breaks Model::refresh() until you obtain a fresh copy of the model.

### Steps To Reproduce:

Relationship:

```
    public function defaultPayment()
    {
        return $this->morphTo('default_payment');
    }
```

Actions:

```
## Generated a fake payment method and saved to the relationship

>>> $card = factory('App\CreditCard')->create(['user_id' => $client->id]);
=> App\CreditCard {#1310
     nickname: "Rice Shoals",
     name_on_card: "Dr. Polly DuBuque",
     type: "amex",
     expiration_month: 5,
     expiration_year: 2018,
     user_id: 1,
     updated_at: "2018-02-06 17:35:22",
     created_at: "2018-02-06 17:35:22",
     id: 184,
   }

>>> $client->defaultPayment()->associate($card)->save();
=> true

##  The related model is only accessible on snake_case

>>> $client->defaultPayment
=> null

>>> $client->default_payment
=> App\CreditCard {#1310
     nickname: "Rice Shoals",
     name_on_card: "Dr. Polly DuBuque",
     type: "amex",
     expiration_month: 5,
     expiration_year: 2018,
     user_id: 1,
     updated_at: "2018-02-06 17:35:22",
     created_at: "2018-02-06 17:35:22",
     id: 184,
   }

## Calling refresh() fails because of the invalid relation

>>> $client->refresh()
Illuminate\Database\Eloquent\RelationNotFoundException with message 'Call to undefined relationship [default_payment] on model [App\Client].'

##  Getting a fresh model returns the relationship to working order on camelCase

>>> $client->fresh()->defaultPayment
=> App\CreditCard {#1307
     id: 184,
     user_id: 1,
     nickname: "Rice Shoals",
     name_on_card: "Dr. Polly DuBuque",
     type: "amex",
     expiration_month: 5,
     expiration_year: 2018,
     created_at: "2018-02-06 17:35:22",
     updated_at: "2018-02-06 17:35:22",
   }

>>> $client->fresh()->default_payment
=> null

```

**Comment by devonblzx** [comment]
After more testing, I've found the issue is with the relationship method:

    /**
     * Define a polymorphic, inverse one-to-one or many relationship.
     *
     * @param  string  $name
     * @param  string  $type
     * @param  string  $id
     * @return \Illuminate\Database\Eloquent\Relations\MorphTo
     */
    public function morphTo($name = null, $type = null, $id = null)
    {
        // If no name is provided, we will use the backtrace to get the function name
        // since that is most likely the name of the polymorphic interface. We can
        // use that to get both the class and foreign key that will be utilized.
        $name = $name ?: $this->guessBelongsToRelation();

        list($type, $id) = $this->getMorphs(
            Str::snake($name), $type, $id
        );

        // If the type value is null it is probably safe to assume we're eager loading
        // the relationship. In this case we'll just pass in a dummy query where we
        // need to remove any eager loads that may already be defined on a model.
        return empty($class = $this->{$type})
                    ? $this->morphEagerTo($name, $type, $id)
                    : $this->morphInstanceTo($class, $name, $type, $id);
    }

So, $name is expected to be in camelCase (and matching the relationship method name).

The fix for this was either dropping the $name from my method return:

    public function defaultPayment()
    {
        return $this->morphTo();
    }

or using camelCase:

    public function defaultPayment()
    {
        return $this->morphTo('defaultPayment');
    }

The morphTo method converts this to default_payment for the later database comparisons.

I'll leave this open for now.  Either `$name` is supposed to match the database and this is a bug, or `$name` is supposed to match the relation and this just needs to be better documented.

**Comment by driesvints** [comment]
I'll take a look at this at a later time but I believe https://github.com/laravelio/portal/issues/350 may be somehow related.

**Comment by driesvints** [comment]
It's indeed necessary to match the relationship name exactly. I've sent in a PR to the docs for this: https://github.com/laravel/docs/pull/6010
