### ISSUE TITLE
[5.5] Error BadMethodCallException with message Method firstWhere does not exist.

### ISSUE THREAD

**Issue by avirdz** [laravel/framework#23054]
- Laravel Version: 5.5.20
- PHP Version: 7.2.1

### Description:
Hi, I'm receiving this error when trying to get the first row that match a validation.
In my case trying to get the first error where code is greater or equals  than 400.

```
$messages = collect([
    ['message' => 'OK', 'code' => 200],
    ['message' => 'ERROR', 'code' => 403],
]);

$error = $messages->firstWhere('code', '>=', 400);
```
BadMethodCallException with message 'Method firstWhere does not exist. at /app/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:96

Is anyone experimenting the same error?

**Comment by staudenmeir** [comment]
The `firstWhere` method was added in Laravel 5.5.23:
https://github.com/laravel/framework/releases/tag/v5.5.23

**Comment by avirdz** [comment]
You are right, thank you @staudenmeir
