### ISSUE TITLE
[BUG][5.6] API middleware before session started causes improper session

### ISSUE THREAD

**Issue by jamesaspence** [laravel/framework#23067]
- Laravel Version: 5.6.0 (and 5.5.14)
- PHP Version: 7.2.0-1+ubuntu16.04.1+deb.sury.org+1
- Database Driver & Version: MYSQL 5.7.20-0ubuntu0.16.04.1

### Description:
I had some routes that returned JSON from within the auth of the site, so I put them within the api.php routes file (just to keep all JSON routes combined).

However, after some testing, I found that having the API middleware run before the web middleware was causing my session to not properly start. When doing calls to `Auth::user()` afterwards, the user would not be returned properly (even when signed in).

### Steps To Reproduce:

1) clone repo at https://github.com/jamesaspence/laravel-api-middleware-issue and set up, including running of DB migrations
2) Navigate to /login to log yourself in after creating a user (if it doesn't exist in the DB)
3) See that the authed user is dded on the main page
4) Navigate to /api/works, confirm same output as main page
5) Navigate to /api, confirm that user is now null.

**Comment by sisve** [comment]
Your repository has one single large commit, making it very hard to see what you've changed compared to the default Laravel setup. Can you publish it as two commit, one initial Laravel commit and one with the changes you've done?

Apis usually use tokens for authentication, not sessions. There could be a conflict there. This is the first time I hear about someone attempting to use both groups at once, instead of just putting their api-related routes in the web.php route file.

**Comment by themsaid** [comment]
Don't use the two middleware groups together, they weren't meant to be used like this.

Please use the forums to ask questions, share the entire scenario and people will help you find the best approach.

**Comment by jamesaspence** [comment]
I literally shared the repo in the hopes of being to demonstrate my problem - I created a brand new repo to make it easily reproducible and cloneable.

Sorry that it's all one commit, but I can point you to the relevant files - you just need to look at `routes/web.php` and `routes/api.php` - The only other change I made was in `RouteServiceProvider` to remove the API middleware from the api.php routes file (so it could be applied manually).

This isn't a matter of both being applied causing the session to fail - it appears to be the route binding happening before the session starts that causes this issue. I will push up a new repo that demonstrates that to be more clear.

**Comment by themsaid** [comment]
@jamesaspence I was able to replicate the issue James, I don't think you need to put more efforts into this.

Either use the web group or the API group, they're designed to be used separately.

**Comment by themsaid** [comment]
You can also create a new group that works the exact way you want, these groups are just there by default as a convenience.

**Comment by jamesaspence** [comment]
@themsaid please see https://github.com/jamesaspence/laravel-bindings-before-session-start, similar instructions as before. However, I made a few changes that highlight the specific issue I'm trying to point out - if you substitute bindings on the route before the session has started, that somehow causes issues with auth and session, with the user being treated as if they're not logged in. Also consolidated all the routes into `web.php` to prove this isn't an issue with the `api` and `web` middleware being used simultaneously - I feel my original issue name was misleading and slightly confusing, so I'm sorry about that.

It definitely seems like a bug to me, as I don't see a reason why handling route bindings would affect session. However, I could just be misunderstanding how that middleware is affecting session. I basically just want to ensure that, if this is a bug, it gets properly reported.

**Comment by jamesaspence** [comment]
Updated name of issue and original post ☝️

**Comment by jamesaspence** [comment]
@themsaid any chance of this getting re-opened? I clarified the exact issue I was having here and believe that it might be a potential bug.

**Comment by devcircus** [comment]
Sessions are intentionally withheld from these exceptional cases when the route actually doesn't reach its destination. It's been discussed several times here. Laravel did provide a couple of ways to do what you want, starting in 5.5. One such possibility is documented on @themsaid's [blog](https://themsaid.com/laravel-55-better-404-response-20170921). Look back through the issues for other options.

**Comment by jamesaspence** [comment]
Hi @devcircus , thanks for the link. However, I'm not sure I understand its relevance - we are properly reaching a route here, we're not having a 404 page or something similar.

**Comment by devcircus** [comment]
My apologies I was reading two different issues  and responding at same time. Disregard.
