### ISSUE TITLE
Migrations should be improved with a factor 10

### ISSUE THREAD

**Issue by rbkkm** [laravel/framework#23064]
I really can't use migrations. I'm curious who can.

Migrations should really be improved to a professional level database tool, now it is unworkable.

r van bekkum

**Comment by browner12** [comment]
If you have a specific concern about migrations you'd like to post, we'd love to help you with your issue.  It is difficult for us to debug or improve based off of generic statements like this.

Github issues are designated for bug reporting, so if you'd like to discuss this issue further, a good place is the Laravel Slack channel.

Thanks.

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.

For suggestions and feature requests please use the https://github.com/laravel/internals repo.
