### ISSUE TITLE
Markdown not getting parsed in published email view files

### ISSUE THREAD

**Issue by tedsecretsource** [laravel/framework#23076]
- Laravel Version: 5.5
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7.17 (Homestead default)

### Description:
Markdown is not being processed in views/vendor/mail/html/header.blade.php. Markdown IS being processed in views/vendor/mail/html/footer.blade.php. One would expect Markdown to be processed either in both or in neither.

### Steps To Reproduce:
1. publish the mail files [as per the documentation](https://laravel.com/docs/5.5/mail#customizing-the-components).
2. create a mailable as per the documentation
3. add a route for previewing as per the documentation
4. add markdown to views/vendor/mail/html/message.blade.php in both the header and footer sections
5. preview the email in a browser

### Expected Results
* Either the markdown is processed and the output is formatted HTML or the markdown is not processed and the output is raw markdown

### Actual Results
* The markdown in the header **is not** processed while the markdown in the footer **is** processed.

### Notes
I see that in footer.blade.php there is this:
``` php
{{ Illuminate\Mail\Markdown::parse($slot) }}
```
and there is this in header.blade.php
``` php
{{ $slot }}
```
This behavior was described in #20791 but @themsaid closed the issue without indicating if it was a known bug or anything. I commented on it but now that I've found the discrepancy thought I should open a new case with the details. I assume there are other files either missing or including the Markdown object and the whole thing should probably be reviewed.

My real question is, what is the purpose of having an HTML folder and a MARKDOWN folder? I was under the impression that the mailer would send the processed markdown (HTML) as the formatted version and the MARKDOWN as the plain text version. If that is the case, then we should only have one folder, shouldn't we? Currently the MARKDOWN folder seems to be completely ignored.

Thanks for all the great work. Laravel is a dream and I hope this bug report helps keep it that way.

Kind regards,

Ted Stresen-Reuter

**Comment by tedsecretsource** [comment]
PS: I'm happy to submit a pull request but I need to understand where this is going first. What is the purpose of having both a markdown folder and an html folder when markdown can (should?) be used for both?

**Comment by mikew1** [comment]
I'm learning here, but from what I can make out the html folder is there to customise the html views generated by `->markdown()`, while its sibling, the so-called 'markdown' folder is exclusively about 'plain-text' emails (which in fact end up as (unparsed, raw) 'markdown', when you inspect the source of the emails actually generated, e.g. in mailtrap).

What is the thinking behind a 'plain text email' equating to markdown source?  Because that's what we're getting right now. Shouldn't the 'markdown' directory be better called 'plain-text'?  Another query is what's the value in customising that; hence why its made publishable.

**Comment by tedsecretsource** [comment]
I think it is made publishable so that you can customize headers and footers and such on a site-wide basis (rather than having to do that inside the mailable - MVC and all).

**Comment by driesvints** [comment]
The directories are explained here: https://laravel.com/docs/5.7/mail#customizing-the-components

I agree that the naming is confusing and has also bitten me at one point.

**Comment by tedsecretsource** [comment]
Thanks a lot for pointing us to the documentation. Having read the instructions, it becomes clear to me that I'm making an assumption that is not, in fact, true.

Can you please consider renaming the markdown folder to "plain-text"? The reason is that for me, and probably for many people, "markdown" is a markup language whose source represents a human-readable fallback. 

In other words, when I write markdown, it is with the expectation that it will be converted into HTML with the source being the plain text fallback in the email. Examples of this approach are ample on the Internet and the use of the word "markdown" implies something fairly different from what the documentation describes, unless I continue to misunderstand the documentation…

Thanks for your effort!

**Comment by driesvints** [comment]
I've sent in a PR to rename the directory in the next release: https://github.com/laravel/framework/pull/26938
