### ISSUE TITLE
Missing attribute in Illuminate\Notifications\Messages\SlackAttachment

### ISSUE THREAD

**Issue by fantua** [laravel/framework#23073]
In class `Illuminate\Notifications\Messages\SlackAttachment` there is at least one missing attr -  `pretext`. 

To prevent this in `Illuminate\Notifications\Messages\SlackAttachment` should be a `options` property:
```php
     /**
     * The attachment's custom options.
     *
     * @var int
     */
    public $options = [];
```
and it should be merged here:

https://github.com/laravel/framework/blob/6a64c8d37143322c5a02b978c499d0e2b303c6f6/src/Illuminate/Notifications/Channels/SlackWebhookChannel.php#L84-L100

**Comment by themsaid** [comment]
added here https://github.com/laravel/framework/pull/23075

**Comment by fantua** [comment]
@themsaid why you don't like idea with `options` prop? It's a common pattern for such cases, because there can be other missing attrs or/and slack API also can be changed any time.

**Comment by themsaid** [comment]
I don't mind it, but saw all attributes assigned fluently so it made sense to me, you can PR the options field if you want.

**Comment by fantua** [comment]
When you close issue without any comment to my suggestion, for me it's mean you against.

**Comment by themsaid** [comment]
Man I've opened a PR to add the missing attribute you want :) That's the only reason I closed the issue, because it's handled already.
