### ISSUE TITLE
What about using snake_case in tests?

### ISSUE THREAD

**Issue by benjamincrozat** [laravel/framework#23071]
I'm currently looking to send a PR, but I noticed how tests are unnecessarily hard to grasp. camelCase methods hard to read and I don't think following PSR-2 naming convention helps in this case. I don't propose to switch all the tests at once of course, but rather starting now, bit by bit. Summarizing the purpose of the test could be great too.

**Comment by themsaid** [comment]
Thanks for the feedback but I believe there are no plans to work on this at the moment, we've started writing integration tests bit by bit in a more cleaner way, by time the old tests will be removed.
