### ISSUE TITLE
RedisStore::add() is a little bit overkill

### ISSUE THREAD

**Issue by benjamincrozat** [laravel/framework#23070]
In `Illuminate\Cache\RedisStore`, the `add` method uses the `EVAL` command from Redis to run a Lua script that performs some checks before adding the key/value to the database.

```php
public function add($key, $value, $minutes)
{
    $lua = "return redis.call('exists',KEYS[1])<1 and redis.call('setex',KEYS[1],ARGV[2],ARGV[1])";

    return (bool) $this->connection()->eval(
        $lua, 1, $this->prefix.$key, $this->serialize($value), (int) max(1, $minutes * 60)
    );
}
```

In my company, the security department blocks unsafe Redis commands to ensure hackers can't do too much harm. I don't know a lot about Redis, so I'm asking here if it could be possible to re-implement it in a safer way.

I don't use the `add` method (I prefer using `remember`), but I think this is an easy and useful change anyway.

**Comment by themsaid** [comment]
If your company blocks Lua Script then I believe you'll face many issues in lots of places using teh framework.

Anyway for suggestions and feature requests please use the https://github.com/laravel/internals repo.
