### ISSUE TITLE
Laravel 5.6 upgrade issue

### ISSUE THREAD

**Issue by CrixuAMG** [laravel/framework#23077]
After I upgraded from 5.5 to 5.6, none of my routes/tests worked since there was an error in the `TrustedProxies` class.
It said it expected an int, but received an array as the second argument.

I checked this and confirmed it was receiving an array of header types.

The documentation (upgrade guide) needs to incorporate the following fix to show how to fix this annoying issue:
Change:
```
    /**
     * The trusted proxies for this application.
     *
     * @var array
     */
    protected $proxies;

    /**
     * The current proxy header mappings.
     *
     * @var array
     */
    protected $headers = [
        Request::HEADER_FORWARDED => 'FORWARDED',
        Request::HEADER_X_FORWARDED_FOR => 'X_FORWARDED_FOR',
        Request::HEADER_X_FORWARDED_HOST => 'X_FORWARDED_HOST',
        Request::HEADER_X_FORWARDED_PORT => 'X_FORWARDED_PORT',
        Request::HEADER_X_FORWARDED_PROTO => 'X_FORWARDED_PROTO',
    ];
```

Into:
```
    /**
     * The trusted proxies for this application.
     *
     * @var array
     */
    protected $proxies = [
        '192.168.1.1',
        '192.168.1.2',
    ];

    /**
     * The headers that should be used to detect proxies.
     *
     * @var string
     */
    protected $headers = Request::HEADER_X_FORWARDED_ALL;
```
Source for this fix:
[https://laravel.com/docs/5.6/requests#configuring-trusted-proxies](https://laravel.com/docs/5.6/requests#configuring-trusted-proxies)

**Comment by rodrigopedra** [comment]
Sorry if the docs were updated after you submitted this issue, but it is already there:

https://laravel.com/docs/5.6/upgrade

> ## Trusted Proxies
> 
> Due to underlying changes in the trusted proxy functionality of Symfony HttpFoundation, slight changes must be made to your application's `App\Http\Middleware\TrustProxies middleware`.
> 
> The `$headers` property, which was previously an array, is now a bit property that accepts several different values. For example, to trust all forwarded headers, you may update your `$headers` property to the following value:
> 
> ~~~
> use Illuminate\Http\Request;
> 
> /**
>  * The headers that should be used to detect proxies.
>  *
>  * @var string
>  */
> protected $headers = Request::HEADER_X_FORWARDED_ALL;
> ~~~
> 
> For more information on the available $headers values, check out the full documentation on trusting proxies.
>

**Comment by CrixuAMG** [comment]
I went through the entire documentation and did not find until now, maybe it should have a big IMPORTANT header or something since not applying the fix breaks the application?

**Comment by sisve** [comment]
This diff is hard to read, but you can see that the docs for this was written 10 days ago. https://github.com/laravel/docs/commit/834bb55fd3edc7bce8cee95db48a843813047638
