### ISSUE TITLE
Whoops shows no stack trace for FatalThrowableError

### ISSUE THREAD

**Issue by jasonvarga** [laravel/framework#23083]
- Laravel Version: 5.6.1
- PHP Version: 7.1.12

### Description:

A FatalThrowableError shows no stack trace. The only thing I see is straight from `valet/server.php` to the file with the error.

![image](https://user-images.githubusercontent.com/105211/35993661-004dbbd8-0cdc-11e8-9418-236cf6d045b5.png)

Regular exceptions are fine.

![image](https://user-images.githubusercontent.com/105211/35993629-ec634282-0cdb-11e8-8bfb-7fe47f865550.png)

It seems to also be ok when using a simple non-Laravel app with Whoops. (Screenshot shows the index file frame. The error itself is triggered the same way as above.)

![image](https://user-images.githubusercontent.com/105211/35993968-f3f706ae-0cdc-11e8-9386-13883c0eb70b.png)

### Steps To Reproduce:

Put this in your routes file:

``` php
Route::get('error', function () {
    // This shows a full stack trace.
    throw new \Exception;

    // This doesn't.
    $foo = null;
    $foo->bar();
});
```

**Comment by themsaid** [comment]
Please report on https://github.com/filp/whoops

**Comment by jasonvarga** [comment]
You're right - when throwing an `ErrorException` instead of just an `Exception` it does the same thing. Sorry!
