### ISSUE TITLE
upgrade Laravel 5.5.x to 5.6.x throw FatalThrowableError

### ISSUE THREAD

**Issue by michealzh** [laravel/framework#23090]
when upgrade Laravel version 5.5.x TO 5.6.x: 
FatalThrowableError

Undefined class constant 'HEADER_CLIENT_IP'
at require()
in ServiceProvider.php (line 59)
at ServiceProvider->mergeConfigFrom('/Users/abc/demo/vendor/fideloper/proxy/config/trustedproxy.php', 'trustedproxy')
in TrustedProxyServiceProvider.php (line 26)

**Comment by Francismori7** [comment]
How did you fix it?
