### ISSUE TITLE
Allow custom validation rules access all parameters

### ISSUE THREAD

**Issue by byCedric** [laravel/framework#23094]
So basically I'm working on a project where we need to validate the amount of days between two timestamps. Because this may vary based on the front end, I want to make this dynamic but also cap the maximum amount to prevent possible abuse. 

I was looking through the code how the `required_if` validation is working, because it looks a lot like the custom rule I described above.  I noticed that [this method](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L1102) has access to a `$this->data` property. This is exactly what I need in my custom validation, but I don't see any "support" for this in the [validator](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Validation/Validator.php#L531). 

So right now it doesn't look like it's possible by creating a custom validation rule right? I think there are some similar use cases where the custom rule needs access to all provided data and validate on certain attributes being there or not. There are some ways to get access in the custom rule, e.g. by using a trait + interface and check if it needs all data. But maybe I'm all alone in this, what do you guys (and girls) think about this?

### Possible usage
I think an example of how I want to use my custom rule might explains it even better.
```php
$input = $request->validate([
    'from' => ['required', 'date', new DateRangeRule('to', 7, 'days')],
    'to'   => ['required', 'date',  new DateRangeRule('from', 7, 'days')],
]);
```
```php
$input = $request->validate([
    'from' => ['required', 'date', new DateRangeRule('to', 1, 'week')],
    'to'   => ['required', 'date',  new DateRangeRule('from', 1, 'week')],
]);
```

**Comment by rodrigopedra** [comment]
You could pass the other field's value in the custom rule's constructor, like this:

~~~php
$input = $request->validate([
    'from' => ['required', 'date', new DateRangeRule($request->get('to'), 7, 'days')],
    'to'   => ['required', 'date',  new DateRangeRule($request->get('from'), 7, 'days')],
]);
~~~

I think that would work

**Comment by byCedric** [comment]
@rodrigopedra Yes, that's definitely a nice workaround! Although I prefer to use Laravel's `$request->input` instead of Symfony's `$request->get` method. For custom rules that require even more attributes you can also just drop the `$request` instance or `$request->all()` array in the constructor. Definitely fair points! But I was wondering if this is something that should be fixed in Laravel or worked around in projects 😄

**Comment by tillkruss** [comment]
If you come up with an elegant solution feel free to submit a PR.

**Comment by the94air** [comment]
Just in case someone is trying to access the request inside a custom rule; you can use the global request helper `request()` like so
```php
<?php

public function rules()
{
    return [
        'field' => [
            // ...
            new CustomRule(request()->field, request()->another_field)
        ]
    ];
}
```

**Comment by photonite** [comment]
> You could pass the other field's value in the custom rule's constructor, like this:
> 
> ```
> $input = $request->validate([
>     'from' => ['required', 'date', new DateRangeRule($request->get('to'), 7, 'days')],
>     'to'   => ['required', 'date',  new DateRangeRule($request->get('from'), 7, 'days')],
> ]);
> ```
> 
> I think that would work

This solutions is limiting, it does not allow to validate data that does not come from the request and it ties the rules to the request, so they cannot be defined apart from it.

I would suggest that the `Validator@passes` method passes an instance of the validator as the third parameter.

**Comment by benallfree** [comment]
No sure if this was mentioned, but the closure version does pass the validator instance as the 4th parameter:

```
$this->$method($attribute, $value, $parameters, $this)
```

@photonite I tried adding `passes($attribute, $value, $validator)`, but that changes the `Rule` contract and probably breaks all existing validators.

The other way to go is assigning `$rule->validator = $this` before calling `$rule-passes(...)`:

```
    protected function validateUsingCustomRule($attribute, $value, $rule)
    {
        $rule->validator = $this;  // Assign validator here
        if (! $rule->passes($attribute, $value)) {
            $this->failedRules[$attribute][get_class($rule)] = [];

            $this->messages->add($attribute, $this->makeReplacements(
                $rule->message(), $attribute, get_class($rule), []
            ));
        }
    }
```

@tillkruss any thoughts on this? Adding the 3rd parameter would be consistent with the closure version.

**Comment by benallfree** [comment]
Sorry for ninja edit...

@photonite I tried adding `passes($attribute, $value, $attributes)`, but that changes the `Rule` contract and breaks all existing validators on earth.

@tillkruss any thoughts on this?

I'm happy to do a PR for it, just want to get comments first :)

**Comment by ja-heller** [comment]
Any suggestion to workaround this?
Stumbled over the same problem, when it comes to building a custom validation rule, where I need to pass some request values (in my case other input values) into.
Currently still breaking:

> Declaration of App\Rules\CustomPricing::passes($attribute, $value, $parameters) must be compatible with Illuminate\Contracts\Validation\Rule::passes($attribute, $value)

**Comment by devcircus** [comment]
Pass the fields you need through the constructor

**Comment by pr4xx** [comment]
But how can I pass the fields when not using the `request()` as source?

**Comment by sasokovacic** [comment]
You can use $validator->getData() method to get the data under the validation...
I don't want to use request() helper method inside of the validation class because then I can only use that class for validating params sent over http requests...

**Comment by jeromefitzpatrick** [comment]
To solve this issue I created a value object for passing Rule Parameters. One for raw values and one for request values.

```
class RequestValueRuleParameter extends AbstractRuleParameter
{
    public function __construct( string $name, string $label = null)
    {
        $this->value = request()->input($name);
        $this->label = $label ?? str_replace('_', ' ', $name);
    }
}

class ValueRuleParameter extends AbstractRuleParameter
{
    public function __construct($value, string $label)
    {
        $this->value = $value;
        $this->label = $label;
    }
}
```

Now I can do something like this:

``` 
Validator::make($data, [
            'current_password' => ['required', new MustMatchExistingPassword(
                new ValueRuleParameter($user->password, 'existing password')
            )]]);

Validator::make($data, [
            'new_password' => ['required'],
            'current_password' => ['required', new MustNotMatchNewPassword(
                new RequestValueRuleParameter('password', 'new password')
            )]]);
```

In the rule, I pass the object through the constructor, type hinting the interface

```
    public function __construct(RuleParameter $existingPassword)
    {
        $this->existingPassword = $existingPassword;
    }
```

Abstract Rule Parameter class
```
abstract class AbstractRuleParameter implements RuleParameter
{
    protected $label;
    protected $value;

    /**
     * @return mixed
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * @return string
     */
    public function getLabel(): string
    {
        return $this->label;
    }
}
```
