### ISSUE TITLE
5.4 -> 5.5 Remember me changes (invalidates old remember me cookie)

### ISSUE THREAD

**Issue by mattbwt** [laravel/framework#23095]
- Laravel Version: 5.5.x
- PHP Version: 7

### Description:
Attempted an upgrade from 5.4 to 5.5 and noticed a high rate of my users had to login again. 
Found that the commit https://github.com/illuminate/auth/commit/4b31d5138aa549ad2aaff3be0851d805820cda72#diff-6a579b06bda168799ddac091ead0ffad has changed remember me, it is now checking the cookie has 3 segemnets instead of 2 (addition of $user->getAuthPassword()).

However I can't find where Recaller@hash is used. Is it used anywhere? Is it worth documenting on the upgrade guide that all remember me tokens will be invalidated? (if this is the case!)

Thank you!

### Steps To Reproduce:
Using 5.4, login with "remember me", remove the session, upgrade to 5.5 and your remember me won't be valid

**Comment by sisve** [comment]
Relevant: https://github.com/laravel/framework/pull/19843
