### ISSUE TITLE
Optional group prefix

### ISSUE THREAD

**Issue by oldy777** [laravel/framework#23097]
i have a problem with route group prefix implementation. I have multi language app and define routes like:
```
$locales = implode('|', config('translatable.locales'));
Route::pattern('locale', $locales);
Route::group(['prefix' => {locale?}], function(){
```
this give me routes:
/ru/page
/en/page
/de/page

but now i need url will be:
/page
/en/page
/de/page

And this is give the problem. I can't set pattern for page without locale. 
And one solution I could find it is use function for locale.
```
Route::group(['prefix' => getLocale()], function(){
```
But in this case I can't use route cache.

**Comment by lancepioch** [comment]
https://laravel.com/docs/5.5/controllers#route-caching

> #### Closure based routes cannot be cached. To use route caching, you must convert any Closure routes to controller classes.

**Comment by oldpunk** [comment]
@lancepioch yes I know it. It was the main question, how to implement this and save route cache. If I use pattern it make regexp like 
```
"#^/(?P<locale>ru|en|ch)/page$#s"
```
because of this I can't set optional locale. It always puts `/` at the beginning of the expression
