### ISSUE TITLE
[laravel] \Routing\Router\group() parameters

### ISSUE THREAD

**Issue by szepeviktor** [laravel/framework#23108]
https://github.com/laravel/laravel/blob/master/app/Providers/RouteServiceProvider.php#L56

```php
        Route::middleware('web')
             ->namespace($this->namespace)
             ->group(base_path('routes/web.php'));
```

Could it be that in the example app laravel/laravel `group()` should get `(array $attributes, $routes)` instead of a string?

https://github.com/laravel/framework/blob/5.5/src/Illuminate/Routing/Router.php#L335-L342

```php
public function group(array $attributes, $routes)
```

**Comment by arjasco** [comment]
See here: https://github.com/laravel/framework/blob/5.6/src/Illuminate/Routing/RouteRegistrar.php#L103

**Comment by szepeviktor** [comment]
@arjasco Thanks.
ide-helper + phpstan told me that `group()` is in Router.php

What could be the cause?

**Comment by szepeviktor** [comment]
It seems like ide-helper generates two `group()`-s.
