### ISSUE TITLE
5.6 sqlite some tests has been broken

### ISSUE THREAD

**Issue by webmake** [laravel/framework#23103]
- Laravel Version: 5.6.3
- PHP Version: 7.1.12
- Database Driver & Version: sqlite

### Description:
I tried to migrate from 5.5.32 to 5.6.3 version, but some of tests (**1.6% of all tests**) started to fail with very weird error:
`Integrity constraint violation: 19 CHECK constraint failed`

Is there any change was made to sqlite, like strict mode or something like that? 

error occurs on very primitive line:
```
        factory(Cart::class)->create();
```
```
Illuminate\Database\QueryException : SQLSTATE[23000]: Integrity constraint violation: 19 CHECK constraint failed: carts (SQL: insert into "carts" ("id", "name", "slug", "type", "price", "time", "order", "published", "updated_at", "created_at") values (2772147016, Alfreda Moen, fake_slug, random, 13831, 9211, 169, 1, 2018-02-10 00:44:47, 2018-02-10 00:44:47))
 /vagrant/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
 /vagrant/vendor/laravel/framework/src/Illuminate/Database/Connection.php:624
 /vagrant/vendor/laravel/framework/src/Illuminate/Database/Connection.php:459
 /vagrant/vendor/laravel/framework/src/Illuminate/Database/Connection.php:411
 /vagrant/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php:32
 /vagrant/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2188
 /vagrant/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:1281
 /vagrant/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:725
 /vagrant/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:690
 /vagrant/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:553
 /vagrant/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php:172
 /vagrant/vendor/laravel/framework/src/Illuminate/Support/Collection.php:339
 /vagrant/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php:173
 /vagrant/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php:151
 /vagrant/Modules/Cart/Tests/Http/Controllers/StoreControllerTest.php:101
```
There is no relations in that table, so I don't have any ideas what can arise such error..

http://www.sqlite.org/opcode.html#Halt maybe this can help

**Comment by lancepioch** [comment]
What's your DB schema for that table?

**Comment by webmake** [comment]
From first migration:
```
        Schema::create('carts', function(Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->enum('slug', Slug::enum());
            $table->enum('type', CartType::enum());
            $table->unsignedSmallInteger('price');
            $table->unsignedSmallInteger('time');
            $table->unsignedTinyInteger('order');

            $table->timestamps();
            $table->unique(['type', 'order']);
        });
```
and later was alter file:
```
        Schema::table('carts', function(Blueprint $table) {
            $table->boolean('published')->default(false);
            $table->softDeletes();
        });
```

**Comment by lancepioch** [comment]
Can you list out the `Slug::enum()` and `CartType::enum()`, that's possibly where the check constraint error is coming from.

**Comment by webmake** [comment]
There is nothing except simple array of values, ex.: ['slug1', 'slug2'], they are unique, so no duplicated values. As I told it worked in 5.5, even since 5.3 version those tests exists, this could not happen suddenly while code basis didn't changed :/

**Comment by webmake** [comment]
Even 5.6.0 throws same error.

Well, I changed really not existing `fake_slug` to `slug1`, and it works.. Strange why it worked up to 5.6 laravel.. We had previously problem by setting `DB::statement('PRAGMA foreign_keys = ON;');` when creating child relations without parent, so deleted foreign_keys option, but as I see it has no difference if `on` or `off` with **fake_slug**

**Comment by webmake** [comment]
I have found problem and not...
https://github.com/laravel/framework/blob/56a58e0fa3d845bb992d7c64ac9bb6d0c24b745a/src/Illuminate/Database/Schema/Grammars/SQLiteGrammar.php#L510

This place has changed

**Comment by mfn** [comment]
Indeed, was introduced in https://github.com/laravel/framework/pull/22109

**Comment by andreich1980** [comment]
For me the problem was with a case of a value I fill a enum-field with.
```
$table->enum('state', ['NEW', 'WORKING', 'CLOSED'])
	->default('NEW')
	->index();
```
and in a factory
```
'state' => 'new', // it has to be NEW
```

**Comment by staudenmeir** [comment]
@laurencei Can be closed.
