### ISSUE TITLE
Customizable  Markdown resource path?

### ISSUE THREAD

**Issue by ercanertan** [laravel/framework#23109]
- Laravel Version: 5.5
- PHP Version:7.2
- Database Driver & Version: sqlite

### Description:
Changing markdown resource path?

### Steps To Reproduce:

I have modular application and I would like to use email template for each module.

```
namespace Modules\Some-module\Emails;
class EmailNotification extends Mailable
{
.
.
    public function build()
    {
        return $this->view( base_path().'/modules/some-module/recources/views/emails/email-notification' );
    }

}
```

But markdown template path is  set to "/resources/views/email" . 

It would ne nice to have full customizable template path.

**Comment by lancepioch** [comment]
You can add custom namespaces that can be whatever path you want.

Using the view() helper, here's what I have in one of my applications that works:

    view()->addNamespace('Launchpad', storage_path('app/launchpads'));

Try the following:

    view()->addNamespace('somemodule', base_path('/modules/some-module/recources/views'));

and

    return $this->view('somemodule::emails.email-notification');

Also... if you want markdown, then you should use the `markdown($view)` instead of `view($view)`.

**Comment by ercanertan** [comment]
Thank you @lancepioch that exactly what I want!
