### ISSUE TITLE
Incorrect matching of routes and resources. 

### ISSUE THREAD

**Issue by salarmehr** [laravel/framework#23116]
- PHP: 7.1
- Laravel: 5.5.34

### Description:
```
//routes
Route::resource('role', 'RoleController'); //1
Route::resource('user/{user}/role', 'RoleUserController'); //2

```

`route('role.store');`  matches with the second route instead of the first one. reordering these two routes extinguish the bug. It should not match with the second route in the first stage.

**Comment by rs-sliske** [comment]
try changing second one to `Route::resource('user.role', 'RoleUserController');`
