### ISSUE TITLE
Artisan call - Cannot allocate memory

### ISSUE THREAD

**Issue by mybigman** [laravel/framework#23124]
Hi,

Running the command from the CLI works fine.
```
php artisan provisioning:signed-tasks
```

However calling the same command from an event listener fails.
```
Artisan::call('provisioning:signed-tasks');

PHP Warning:  proc_open(): fork failed - Cannot allocate memory in /var/www/laravel53/vendor/symfony/console/Application.php on line 937
ErrorException with message 'pcntl_fork(): Error 12'
``` 
Bug?

Laravel Framework version 5.3.31

**Comment by Kyslik** [comment]
Probably you have different settings for cli php and server php.

Laravel 5.3 is not supported anymore; upgrade to 5.6.
