### ISSUE TITLE
Migration class Blueprint renameColumn() was removed at upstream doctrine/dbal

### ISSUE THREAD

**Issue by ZerglingGo** [laravel/framework#23125]
- Laravel Version: 5.5.27
- PHP Version: 7.1.13
- Database Driver & Version: MariaDB 10.2.11

### Description:
I'm trying to change the column name but name wasn't changed.
While checking relations codes, I found renameColumn() function was removed at [doctrine/dbal](https://github.com/doctrine/dbal).

You can check reference this [Document](https://github.com/doctrine/dbal/blob/e5fe8c875f9bb0f2e0e48889e3e130cbbcf8fdbb/UPGRADE.md#doctrinedbalschematablerenamecolumn-removed) and [Source code](https://github.com/doctrine/dbal/blob/122d4ad7235f6b716d79112ea5dabaf1993e6920/lib/Doctrine/DBAL/Schema/Table.php#L338)

### Steps To Reproduce:

Occurs when using renameColumn() in migration:
```PHP
Schema::table('tables', function (Blueprint $table) {
    $table->renameColumn('beforecolumn', 'aftercolumn');
});
```

**Comment by sisve** [comment]
Yes, but that was 6 years ago in https://github.com/doctrine/dbal/commit/9b0bd8817cb74c4aefba043c7e59f94641cc5b15. Are you sure that is the problem you're having?

**Comment by ZerglingGo** [comment]
Then, The problem is that the column name does not changed, but this is not the real cause.

and I find real cause:
```
In Connection.php line 664:

  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''' NOT NULL' at line 1 (SQL: ALTER TABLE users CHANGE period testcolumn VARCHAR(191) DEFAULT ''1h'' NOT NULL)
```

Looking at the query, the quotes are written twice.

Column creation code:
```PHP
$table->string('period')->default('1h');
```

**Comment by sisve** [comment]
I see two problems;

1. You're using MariaDB. They introduced a breaking change in 10.2.7. This is a known problem and tracked in https://github.com/laravel/framework/issues/22050. Also note that MariaDB is not in the list of supported databases at https://laravel.com/docs/5.5/database
2. You're using the defaultStringLength(191) hack instead of properly configuring your database to support what you need. This is an unrelated problem to the one you're reporting.

**Comment by ZerglingGo** [comment]
Thank you for helping.
I did using raw query instead of renameColumn(). I think that is best way.
