### ISSUE TITLE
Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by adekpp** [laravel/framework#23131]
- Laravel Version: 5.1.10 
- PHP Version: 7.2

Description:
[laravel.log](https://github.com/laravel/framework/files/1716430/laravel.log)

**Comment by decadence** [comment]
Welcome to Laravel! We are glad to have you as part of the community.

Unfortunately GitHub is not an appropriate platform for general application issues. This is only for issues/bugs with the framework code itself.

Please close your issue, and instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

Laravel Slack (https://larachat.co/)
Laravel.io Forum (https://laravel.io/forum)
Laracasts Forum (https://laracasts.com/discuss)
StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks!

**Comment by GrahamCampbell** [comment]
Looking at the start of the log, the error is there:

```
ErrorException: Undefined offset: 1 in /var/www/html/app/Http/Controllers/GameController.php:1187
```
