### ISSUE TITLE
No DB Prefix in key name, When migrate with db prefix.

### ISSUE THREAD

**Issue by ThunderBirdsX3** [laravel/framework#23142]
- Laravel Version: 5.5.x, 5.6.x
- PHP Version: 7.1.13
- Database Driver & Version: MySQL 5.7.20

### Description:
In case of used prefix database.
When you run migrate, If use look at key name in `indexs` and `foreign key`. It has no prefix in `key_name` or `name`.

It will be a problem when you use same table structure in same database with not same prefix.

![screen shot 2018-02-13 at 3 46 13 pm](https://user-images.githubusercontent.com/6513358/36140859-5d4a6672-10d5-11e8-9542-128f79a68152.png)
![screen shot 2018-02-13 at 3 47 06 pm](https://user-images.githubusercontent.com/6513358/36140860-5d7cfe02-10d5-11e8-9ce4-1f169621b594.png)
![screen shot 2018-02-13 at 3 47 09 pm](https://user-images.githubusercontent.com/6513358/36140861-5dbdae16-10d5-11e8-9cb8-49b8f61d3e0d.png)

 
### Steps To Reproduce:
It should have prefix in `key_name` and `name`.

**Comment by wanghanlin** [comment]
looks like a duplication of #7889
