### ISSUE TITLE
Tests with RefreshDatabase trait fails when using the mysql driver

### ISSUE THREAD

**Issue by ventrec** [laravel/framework#23144]
- Laravel Version: 5.6.3
- PHP Version: 7.1.8
- Database Driver & Version: mysql 5.7.21

### Description:

After upgrading to 5.6, my tests are no longer working. I'm getting the following error message: `PDOException: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT trans2 does not exist`.

After debugging I've noticed that the `RefreshDatabase` trait has been updated and is now using the `DatabaseMigrations` trait. This seems to cause the error I'm having.

### Steps To Reproduce:

1. Create a few tests that touces the database and uses the trait `RefreshDatabase`.
2. Use the mysql driver when testing.
3. Run tests

### How To Fix:

Revert the `RefreshDatabase` trait back to the previous version by removing the `DatabaseMigrations` trait and include the two methods from `DatabaseMigrations` in `RefreshDatabase`.

**Comment by laurencei** [comment]
This was fixed yesterday. It will be in the next tagged verson of Laravel.

**Comment by ventrec** [comment]
Awesome. Then I'll remove my temporary trait when the next version is available.
