### ISSUE TITLE
Bug: Laravel framework 5.5 error compatibility PHP 7.0

### ISSUE THREAD

**Issue by daloni** [laravel/framework#23158]
The dependency "symfony/http-kernel ~3.3" -> this need "symfony/css-selector": "~2.8|~3.0|~4.0".
Dependency "symfony/css-selector 4.0" need PHP 7.1 and cause this error:

![image](https://user-images.githubusercontent.com/11467074/36202809-94933220-1185-11e8-8cb4-964e8fe6e5f5.png)

For solved, i fix in composer of my project of "laravel/laravel" the version of "symfony/css-selector":

```
"require-dev": {
    "symfony/css-selector": "3.3"
...
```

**Comment by toddroper** [comment]
After running into this issue while building composer on a docker image running PHP 7.0.32 multiple times I can say with 100% certainty that this is not limited to copying dependencies from a system with 7.1 to a system with 7.0.

The issues lies in the composer.json require section.

To fix the issue you need to change this block:
`"require": {
        "php": ">=7.0.0", --> "php": "7.0.*",
        "fideloper/proxy": "~3.3",
        "laravel/framework": "5.5.*",
        "laravel/tinker": "~1.0"
    },`

That change will tell the system to exclude packages that are supported by 7.1 and install 7.0 packages.
