### ISSUE TITLE
Redirect after login go wrong, When have port in url.

### ISSUE THREAD

**Issue by ThunderBirdsX3** [laravel/framework#23154]
- Laravel Version: 5.6.3
- PHP Version: 7.1.13
- Database Driver & Version: 

### Description:
After login success and send login response, When my server access with specific port in URL. It will redirect to non port URL.

![screen shot 2018-02-14 at 10 13 03 am](https://user-images.githubusercontent.com/6513358/36186256-7c33d79e-1170-11e8-8df8-3f5170293719.png)

### Steps To Reproduce:
`redirect()->intended(...);` Should redirect with port.

**Comment by kevinobama** [comment]
Maybe u can use php header function to redirect to new URL.
