### ISSUE TITLE
Translator contract is not respected by the blade complier

### ISSUE THREAD

**Issue by jeanmonod** [laravel/framework#23162]
- Laravel Version: v5.5.32
- PHP Version: all

### Description:

Here: https://github.com/laravel/framework/blob/56a58e0fa3d845bb992d7c64ac9bb6d0c24b745a/src/Illuminate/View/Compilers/Concerns/CompilesTranslations.php#L21 The blade compiler is bypassing the translator interface. Ihmo it should call `trans()` instead of `getFromJson`

### Steps To Reproduce:

Implement our own Translator service following the official interface:

    use Illuminate\Contracts\Translation\Translator as TranslatorContract;
    class Translator implements TranslatorContract
    {
        public function trans($key, array $replace = [], $locale = null) { ... }
        public function transChoice($key, $number, array $replace = [], $locale = null) { ... }
        public function getLocale() { ... }
        public function setLocale($locale) { ... }
    }

Start to use it and get the following error:

    Call to undefined method MyProject\Libraries\Translation\Translator::getFromJson() (View: /vagrant/resources/views/components/my-block.blade.php)

### Disclamer

I'm just starting to use Laravel, so I may be wrong. All my apologies if it's the case

**Comment by ntzm** [comment]
A lot of the interfaces are out of date due to features being added as new functions in minor releases, and changing the interface would result in a breaking change. If you can submit a PR to add the missing methods to the interface that targets the master branch, it can be added next BC break

**Comment by jeanmonod** [comment]
I won't do this. It make no sense. The interface is clean as it is. I'm fetching translations from a key-value database, what do you want me to implement into `getFromJson`? For now, I stupidely fix my issue by surcharging the method like this:

    // Overriding this method to fix https://github.com/laravel/framework/issues/23162
    public function getFromJson($key, array $replace = [], $locale = null) {
        return $this->trans($key, $replace, $locale);
    }

For me it's not a blocker anymore, but honestly, I think you should fix it the other way around, calling `trans()` from the blade templates. Do you want a PR for that fix?

**Comment by tillkruss** [comment]
Sure, please feel free to submit a PR.

**Comment by raphaelsaunier** [comment]
@tillkruss I submitted a PR which would've addressed this issue (see link above), but it was closed by Taylor. 

I'm happy to look into it again if you see any other ways to solve it?

**Comment by tillkruss** [comment]
I'd suggest to either add your own @trans directive, or even submit a PR for it.

I've closed this because it's not a bug.
