### ISSUE TITLE
Argon2 Hashing

### ISSUE THREAD

**Issue by HDVinnie** [laravel/framework#23163]
- Laravel Version: 5.6
- PHP Version: 7.1.3

### Description:
Laravel 5.6 announced it supports Argon2 hashing yet only requires PHP 7.1.3. From my understanding 
Argon2 requires PHP 7.2 or greater. So should Laravel 5.6 require PHP 7.2 and not 7.1.3 or am I wrong here?

**Comment by a-komarev** [comment]
Argon2 isn't selected as default. By default Laravel 5.6 using bcrypt. So it's completely up to you.

**Comment by HDVinnie** [comment]
I agree with that but it seems a little wrong to have a option for Argon2 in the framework yet the min php requirement of the framework doesn't support Argon2. I really think Laravel should change it from PHP 7.1.3 or greater to PHP 7.2 or greater. Then works out the box.

**Comment by a-komarev** [comment]
7.2 isn't widely adopted. That will mean you wouldn't be able to run Laravel at all. Even if you don't need Argon2 at all.

**Comment by HDVinnie** [comment]
I see......thank you.

**Comment by GrahamCampbell** [comment]
Just a guess, but I'd say that Laravel 5.8 will probably bump the minimum required version to 7.2. That'd be inline with bumping every year, the same as PHP's release cycle.
