### ISSUE TITLE
Vendor:publish needs to be more informative

### ISSUE THREAD

**Issue by GinoPane** [laravel/framework#23169]
- Laravel Version: 5.5.32 (does not really matter)
- PHP Version: any

### Description:

When running `php artisan vendor:publish` for a specific vendor to publish its config I got nice green successful message:

"Publishing complete".

But nothing was actually published. After debugging I found out that the system failed to determine publishing paths and there was nothing to publish actually. 

Therefore simple successful message is not enough for such case. It would be nice to tell, that nothing was published and probably the reason why.

### Steps To Reproduce:

Run `vendor:publish` for a vendor with errors in `publishes` declaration or with some invalid options (vendor without namespace or something like that). You just need to make sure that the system won't actually publish anything.

**Comment by fitztrev** [comment]
There was a PR #20372 that may have addressed this but I don't think it was resubmitted.

**Comment by GinoPane** [comment]
@fitztrev Indeed! It looks that the idea was approved, but the PR has not been merged yet.

**Comment by tillkruss** [comment]
This repository is for bug reports only. Please move the discussion to the internals or ideas repos.

**Comment by SherSpock** [comment]
I also ran into this issue when adding phpinsights to a project. The behavior can be pretty convincingly argued to be a bug -- "Publishing complete" on a noop publish attempt is clearly deviant behavior. 

I searched to see if this had a corresponding open issue and didn't see any. I'm not on the latest and greatest Laravel so I figured I'd checked closed issues and was lucky enough to find this.

@tillkruss 
I think this should be reopened and the title changed to something that indicates `vendor:publish` is giving success messages on failed publishes. What do you think?

**Comment by tillkruss** [comment]
@SherSpock: Mhh, why don't you re-submit #20372 and get it fixed?

**Comment by SherSpock** [comment]
@SherSpock Happy to. I imagine it's a simple fix, and maybe just a quick conflict resolution of @GinoPane's work with 5.5 changes. If there's an easy way for me to get that change in while leaving credit where it's due in the history that's what I'll do

**Comment by tillkruss** [comment]
Yes, looks very much straight forward: https://github.com/laravel/framework/pull/20372/files

**Comment by SherSpock** [comment]
Indeed. Which version to target?

**Comment by tillkruss** [comment]
`6.x`
