### ISSUE TITLE
Model function findMany doesn't provide paginate function

### ISSUE THREAD

**Issue by vaishnavmhetre** [laravel/framework#23175]
Hi,

I tried executing the following snippet on Laravel 5.5,
```
...
$ids = [1, 2, 3];
$answers = Answer::findMany($ids)->paginate(2);
...
```

But this results in error, `Method paginate does not exist` but rather works fine on `whereIn`.

I just had to report this bug.

**Comment by devcircus** [comment]
Yes, seems like intended behavior to me. 

Use ```findMany``` if you need a collection. 

If you need a builder or need to chain other builder methods, ```whereIn``` should be used.

If you look at the [code](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Database/Eloquent/Builder.php#L299), ```findMany``` is just a wrapper around ```whereIn```, with ```->get()``` added.
