### ISSUE TITLE
Laravel getxxxxAttribute accessor not appending to the model

### ISSUE THREAD

**Issue by badalsurana** [laravel/framework#23177]
- Laravel Version: 5.5.32
- PHP Version: 7.2.2
- Database Driver & Version: Mysql

### Description:
I have added a accessor to my User.php model `getArticlesCountAttribute`

        protected $appends = ['articles_count'];

        public function getArticlesCountAttribute()
        {
            return (int) $this->articles()->count();
        }

but when i access it from my laravel blade views articles count database query runs every-time i use the accessor in my view

**For example:** if i have `Auth::user()->articles_count` 3 times in my blade view it will run articles count query 3 times.

Shouldn't it be appended at the start and query should only run once no matter how many times i reference it in my views?

**Comment by arjasco** [comment]
This is because you are accessing the relationship and running a count query each time. 

Have you considered using `->withCount('articles')` on your query?  
You could load the relationship and then just count the collection.
Or if you really like.. use a static variable as a sort of singleton pattern on your attribute.

**Comment by staudenmeir** [comment]
Storing the attribute is **not** the purpose of `$appends`.
It's only used when you convert the model to an array, e. g. when you convert it to JSON.

**Comment by m-lotze-7o7** [comment]
Remove the parentheses after articles. Then the query will only run once.

``$this->articles->count();``

**Comment by staudenmeir** [comment]
Depending on the number of articles and their attributes this can be quite expensive if you just need the count.

**Comment by badalsurana** [comment]
@staudenmeir yes, `$this->articles->count();` will select all articles from database which is quite expensive if some has 100 articles.

What is the use of `protected $appends` if it does not add the value to the model?

**Comment by staudenmeir** [comment]
You can use `$appends` to add data to the JSON reprensentation of your model.

If you only need the count in one view, you could store it in a variable:

    @php
      $count = Auth::user()->articles()->count();
    @endphp
