### ISSUE TITLE
Upgrading To 5.5.0 From 5.4

### ISSUE THREAD

**Issue by jmichaelterenin** [laravel/framework#23171]
- Laravel Version: 5.5.34
- PHP Version: 7.1.8

### Description: I'm following the instructions for a Laravel 5.5 upgrade: https://laravel.com/docs/5.5/upgrade

Specifically:

Updating Dependencies
Update your laravel/framework dependency to 5.5.* in your composer.json file. In addition, you should update your phpunit/phpunit dependency to ~6.0. Next, add the filp/whoops package with version ~2.0 to the require-dev section of your composer.json file. Finally, in the scripts section of your composer.json file, add the package:discover command to the  post-autoload-dump event:

```
"scripts": {
    ...
    "post-autoload-dump": [
        "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
        "@php artisan package:discover"
    ],
}

```

### Steps To Reproduce:
When I add the filip/whoops package to the composer.josn file, along with the post-autoload-dump, and perform either 'composer update' or 'composer global update', the filip/whoops reference is removed from the composer.json file, and the post-autoload-dump is replaced with:

```
		"post-install-cmd" : [
			"Illuminate\\Foundation\\ComposerScripts::postInstall",
			"php artisan optimize"
		],
		"post-update-cmd" : [
			"Illuminate\\Foundation\\ComposerScripts::postUpdate",
			"php artisan optimize"
		]
```
Is there someone who can shed some light as to why this is happening? Something simple I'm missing?
Thanks in advance.

**Comment by browner12** [comment]
Welcome to Laravel! We are glad to have you as part of the community.

Unfortunately GitHub is not an appropriate platform for general application issues. This is only for issues/bugs with the framework code itself.

Please close your issue, and instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

Laravel Slack (https://larachat.co/)
Laravel.io Forum (https://laravel.io/forum)
Laracasts Forum (https://laracasts.com/discuss)
StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks!

**Comment by jmichaelterenin** [comment]
Wish I hadn't (closed it), laravel slack crowd was mystified as to what the issue was, and I've done enough googling to know that there hasn't been a duplicate issue logged by anyone else on this ...

**Comment by jmichaelterenin** [comment]
composer self-update (to v 1.6.3 from 1.4.2) didn't help

**Comment by crynobone** [comment]
The upgrade guide clearly mention about removal of Optimize command, yet
your How to reproduce step specifically add it.

**Comment by jmichaelterenin** [comment]
I'm not adding it, it's being added as a result of: `composer update`

**Comment by crynobone** [comment]
![screenshot_20180216-131427](https://user-images.githubusercontent.com/172966/36294460-d3b06ba2-131b-11e8-8308-6ec3623f89a7.png)
