### ISSUE TITLE
Auth remember_me cookie domain

### ISSUE THREAD

**Issue by MatanYed** [laravel/framework#23185]
Hi, my website have many sub-domain, for language
example.com (which redirect to en)
en.example.com
de.example.com
etc...

there is no option at login to custom cookie for shared domain and sub-domains
`Auth::login($user, true) // true for remember_me cookie`

thanks

**Comment by sisve** [comment]
This sounds like a feature request, not a bug report. We accept feature requests at https://github.com/laravel/internals or as a pr.
