### ISSUE TITLE
Bug: 5.4 not compatible with php5 because of dependency tijsverkoyen/css-to-inline-styles 2.2.1

### ISSUE THREAD

**Issue by ravinow** [laravel/framework#23186]
- Laravel Version: 5.4.36
- PHP Version: 5.6
- Database Driver & Version: N/A

### Description:

Laravel framework 5.4.36 requires tijsverkoyen/css-to-inline-styles ~2.2.

in their latest version 2.2.1, it allows a new version of symfony/css-selector (^4.0)

But symfony/css-selector 4.0.4 doesn't support php5. see https://packagist.org/packages/symfony/css-selector

### Steps To Reproduce:
1. install laravel 5.4
2. composer update
3. call any controller method you will see:

In CssSelectorConverter.php line 34:
                                                                        
  Default value for parameters with a class type hint can only be NULL

**Comment by ravinow** [comment]
it seems to be that my composer is using php7 but the project is using php5. So the installed libs are not compatible with the running environment.

**Comment by papanipapi** [comment]
Hi,

Try this "composer --prefer-dist --verbose -vvv update"
