### ISSUE TITLE
Cookie Factory and Cookie Jar have different PHPDoc on $secure parameter

### ISSUE THREAD

**Issue by dizco** [laravel/framework#23196]
- Laravel Version: 5.6.3
- PHP Version: 7.2.1
- Database Driver & Version: mysql

### Description:

I think the [Cookie Factory](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Contracts/Cookie/Factory.php) is not up to date with the [Cookie Jar](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Cookie/CookieJar.php).

Essentially, it is the `$secure` parameter that should also accept `null`.

Cookie Jar : 

```
/**
     * Create a new cookie instance.
     *
     * @param  string       $name
     * @param  string       $value
     * @param  int          $minutes
     * @param  string       $path
     * @param  string       $domain
     * @param  bool|null    $secure
     * @param  bool         $httpOnly
     * @param  bool         $raw
     * @param  string|null  $sameSite
     * @return \Symfony\Component\HttpFoundation\Cookie
     */
```

Cookie Factory : 

```
/**
     * Create a new cookie instance.
     *
     * @param  string  $name
     * @param  string  $value
     * @param  int     $minutes
     * @param  string  $path
     * @param  string  $domain
     * @param  bool    $secure
     * @param  bool    $httpOnly
     * @param  bool         $raw
     * @param  string|null  $sameSite
     * @return \Symfony\Component\HttpFoundation\Cookie
     */
```

### Steps To Reproduce:

I have a Lumen 5.6.3 installation where I have added Cookie support using this method : https://github.com/esbenp/lumen-api-oauth/issues/23#issuecomment-217417473

It worked on 5.5, but it breaks on 5.6 with 

`Type error: Argument 6 passed to Symfony\Component\HttpFoundation\Cookie::__construct() must be of the type boolean, null given, called in C:\xampp\htdocs\customers\MtBlanc\ski-school-manager-backend\vendor\illuminate\cookie\CookieJar.php on line 69`

Here is my code : 

```
$cookie = Cookie::make(
            "cookie", // Name
            "value", // Value
            10, // Max age
            null, // Path
            null, // Domain
            null, // Secure <- If I put false here, no error occurs.
            true // HttpOnly
        );
```

**Comment by laurencei** [comment]
This can be closed - the issue is fixed for 5.7

**Comment by dizco** [comment]
What should I do in the meantime, waiting for the fix to be published?

**Comment by laurencei** [comment]
That sounds like a problem in Lumen perhaps? The PHPDocs wont make a difference to the code itself.

**Comment by dizco** [comment]
@laurencei true... I'll try to investigate some more into this issue later but for now I'm using some workarounds. Thanks for your help!

**Comment by chunganhbk** [comment]
The issue still errors at 5.8
```
Argument 2 passed to Symfony\Component\HttpFoundation\Cookie::__construct() must be of the type string or null, array given, called in F:\Project\Tucozi\vendor\laravel\framework\src\Illuminate\Cookie\CookieJar.php on line 70
```
