### ISSUE TITLE
[5.6] Public Controller Subdirectory Issue

### ISSUE THREAD

**Issue by austintoddj** [laravel/framework#23222]
- Laravel Version: 5.6.0
- PHP Version: 7.1.14
- Database Driver & Version: mysql Ver 14.14 Distrib 5.7.21

### Description:
When creating a new controller within a subdirectory, it appears that usage of the name `Public` causes an issue. If the namespace and directory are anything else, it works fine.

### Steps To Reproduce:

**Create Laravel Project**
composer create-project --prefer-dist laravel/laravel laravel

**Create a basic controller in a subdirectory**
```php
php artisan make:controller Public/ExampleController --resource
```

**Add this to the `index()` method in the new controller**
```php
dd('This will not work');
```

**Create the route in routes/web.php**
```php
Route::resource('example', 'Public\ExampleController');
```

Test it
```php
php artisan route:list
```

Now, change the`Public` directory name to`Example` and update its namespace in the controller and the route. Test it again and it will work.

Why would the usage of the word _Public_ make a difference?

**Comment by devcircus** [comment]
See [this stackoverflow answer](https://stackoverflow.com/a/38961535).

**Comment by ntzm** [comment]
`public` is a reserved word in PHP

**Comment by austintoddj** [comment]
Thanks for the heads up @devcircus.
