### ISSUE TITLE
Should trans_choice() and MessageSelector::getPluralIndex() respect RFC 4646 language tags (e.g. 'en-AU')?

### ISSUE THREAD

**Issue by markokeeffe** [laravel/framework#23226]
I recently noticed that trans_choice() was not working as expected in my application. This is because my app has both 'en-US' and 'en-AU' languages available. After a bit of debugging I realised that the MessageSelector class is checking language tags with an underscore e.g. 'en_US' and 'en_AU'. Should the MessageSelector also support the [RFC 4646 language tag format](https://tools.ietf.org/html/rfc5646) (hyphens, not underscores) that the [PHP Locale class](http://php.net/manual/en/class.locale.php) references?

**Comment by markokeeffe** [comment]
Here's a proposed solution:
#23227

**Comment by sisve** [comment]
As I wrote in your PR, RFC 4646 is a lot more than dashes. Laravel uses ISO 15897 (posix locales), this is just not a specific method that uses underlines, but the entire current locale implementation. It would be more fitting if you adapted your application to the framework and switched away from RFC 4646.

**Comment by tillkruss** [comment]
Please move this discussion to the internals or ideas repos.
