### ISSUE TITLE
Pusher constructor signature is wrong

### ISSUE THREAD

**Issue by jeffersonlicet** [laravel/framework#23224]
- Laravel Version: 5.6.0
- PHP Version:7.1

### Description:
I have tried to configure Pusher by following the steps in the Laravel documentation.  
But i'm getting:  

> Pusher\Exception\HttpException (400)
> Bad request.

However I have found that the signature of the Pusher constructor in the pusher-http-php package is wrong: The official documentation instructions says that you can create a Pusher instance using: `$pusher = new Pusher\Pusher(
    'PUBLIC_KEY',
    'PRIVATE_KEY',
    'APP_KEY',
    $options
  );`

So does Laravel in Illuminate/Auth/Broadcasting/BroadcastManager.php Line 210:
`return new PusherBroadcaster(
            new Pusher($config['key'], $config['secret'],
            $config['app_id'], $config['options'] ?? [])
        );`

But taking a look to pusher/pusher-php-server/src/Pusher.php
The correct Pusher signature is: ` public function __construct($appId, $key = null, $secret = null, $options = array())`

After update BroadcastManager.php with the following:
``return new PusherBroadcaster(
            new Pusher($config['app_id'], $config['key'],
            $config['secret'], $config['options'] ?? [])
        );``
Now a can trigger events but  seems like $pusher->trigger is returning an empty object and Illuminate/Broadcasting/Broadcasters/PusherBroadcaster.php is failing to parse that response.

### Steps To Reproduce:
Install Laravel and integrate Pusher. 

Thank you.

**Comment by it-can** [comment]
Did you upgrade pusher? Since Laravel 5.5, Pusher requires version ~3.0.

https://laravel.com/docs/5.5/upgrade

**Comment by jeffersonlicet** [comment]
Yes, 3.0.x-dev 6d1977e

**Comment by devcircus** [comment]
The current Pusher constructor, shown [here](https://github.com/pusher/pusher-http-php/blob/v3.0.1/src/Pusher.php#L43), accepts parameters exactly as the current Laravel [BroadcastManager](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Broadcasting/BroadcastManager.php#L213) passes them.

Everything seems correct?

**Comment by jeffersonlicet** [comment]
Seems that, when I run `composer require pusher/pusher-php-server "~3.0"` composer is installing the branch dev-new-lib. https://github.com/pusher/pusher-http-php/blob/new-lib/src/Pusher.php Which has the new signature.

**Comment by ekaPrawira** [comment]
Got the exact same issue when running `composer require pusher/pusher-php-server "~3.0"` and get a dev-lib instead. In my case, it is caused by not having `php-curl` installed in my setup. After installing it, I remove the current dev-lib, rerun `composer require pusher/pusher-php-server "~3.0"` and it works like a charm.
