### ISSUE TITLE
getDirty method returns empty when listener implements ShouldQueue

### ISSUE THREAD

**Issue by ambengers** [laravel/framework#23228]
Hello,

I ran into this bug that when you use a getDirty() method inside the listener that implements ShouldQueue interface it always returns an empty result. 

I am not even sure if its only because my queue driver is not yet set? Here are some screenshots to help understand. Thanks!

<img width="1073" alt="screen shot 2018-02-20 at 5 37 07 pm" src="https://user-images.githubusercontent.com/17848299/36417037-cf3433fe-1665-11e8-90b7-b9adbf350788.png">
<img width="1083" alt="screen shot 2018-02-20 at 5 39 00 pm" src="https://user-images.githubusercontent.com/17848299/36417038-cf6901ba-1665-11e8-8c8a-5b3e92bfd3b0.png">

**Comment by mfn** [comment]
Please provide a short/reproducible case for this

**Comment by shieldstick** [comment]
@mfn Thanks for your response. You can clone this repo that I created:

https://github.com/shieldstick/get_dirty_test

Just run the test I have in tests/Feature/UsersTest. I am returning dump($user->getDirty()) in App\Listeners\UserUpdated. This listener currently implements ShouldQueue which shows this:

<img width="1041" alt="screen shot 2018-02-20 at 11 16 34 pm" src="https://user-images.githubusercontent.com/17848299/36432061-2f7f2c04-1694-11e8-8d01-f9925ed8b545.png">

Hope this helps. 

PS: I was using 5.5 on my original post but I created a new project for this test which is 5.6 so if in case you create a fix maybe you can also fix it in 5.5 👍

**Comment by dennisoderwald** [comment]
@ambengers Have you found a solution? I am facing the same conflict.
