### ISSUE TITLE
The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths.

### ISSUE THREAD

**Issue by balaJS** [laravel/framework#23237]
- Laravel Version: 5.4
- PHP Version:7.0.23
- Database Driver & Version:5.7.19

### Description:
Encrypter->__construct('', 'AES-256-CBC')
in EncryptionServiceProvider.php (line 27)

app.php had key value 'base64:******' and 'cipher' => 'AES-256-CBC'.
But error message had key is empty.
How to fix it?
![image](https://user-images.githubusercontent.com/28555689/36461839-ca7d8290-16e5-11e8-92b0-f6c83d998bbb.png)
Any one help me.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I suggest closing your issue ticket here? Instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.

**Comment by Kyslik** [comment]
Most likely you are not setting `APP_KEY` correctly, so triple check `.env`, `app.php` and also bust config cache using `php artisan config:clear`.

**Comment by balaJS** [comment]
Sorry, i am newbie in github. Any way thanks for your advise

**Comment by sanjarbek** [comment]
the same issue. php artizan key:generate is ok, but error still show.

**Comment by hatimhussein** [comment]
php artisan key:generate
php artisan config:clear

**Comment by SalasMerlitoJr** [comment]
> php artisan key:generate
> php artisan config:clear

we have the same issue. the generate works, but the error will show.
