### ISSUE TITLE
Email addresses can contain unicode nowadays

### ISSUE THREAD

**Issue by yeahfree** [laravel/framework#23239]
- Laravel Version: 5.5.*
- PHP Version: 7.1 and higher
- Database Driver & Version: Not applicable

### Description:
The email validation is slightly outdated. From PHP 7.1 and the fact that modern domain names can use various unicode nowadays (eg. http://müller.com/), the email validation ought to be updated. The email validation functionality can be found at /src/Illuminate/Validation/Concerns/ValidatesAttributes.php and the function is validateEmail(). Other relevant information can be found at:
https://secure.php.net/manual/en/filter.filters.validate.php (at the row with FILTER_VALIDATE_EMAIL)
http://php.net/manual/en/filter.constants.php (at the bottom at FILTER_FLAG_EMAIL_UNICODE)

### Steps To Reproduce:
Creating a Validator with an email rule and then pass "test@müller.com" into it.

---

Thank you for your time, if you need any more information, please don't hesitate to ask. I tried implementing it quickly myself by adding the flag to the filter_var (, but that did not seem to do the trick so far :( I will in the meanwhile implement it for my project as a custom validation rule (see: https://laravel.com/docs/5.4/validation#custom-validation-rules )

**Comment by tillkruss** [comment]
Could you post how you're using FILTER_FLAG_EMAIL_UNICODE?

**Comment by cwang22** [comment]
the [documentation](http://php.net/manual/en/filter.constants.php) says its only for the local part

> FILTER_FLAG_EMAIL_UNICODE (integer)
> Accepts Unicode characters in the local part in "validate_email" filter. (Available as of PHP 7.1.0)

so simply passing it as a flag to `filter_var` will not work for `test@müller.com`

there's library support this like [egulias/EmailValidator](https://github.com/egulias/EmailValidator)

This can be optional for user to choose if they want it

**Comment by mpyw** [comment]
@cwang22 @yeahfree `egulias/EmailValidator` contains lots of bug. I don't trust the library.

https://github.com/egulias/EmailValidator/issues?q=is%3Aissue+is%3Aopen+label%3Abug

I believe that developers can choose `FILTER_FLAG_EMAIL_UNICODE` as `FILTER_VALIDATE_EMAIL` option.
