### ISSUE TITLE
Laravel data_get helper has different behavior for array and object

### ISSUE THREAD

**Issue by vijaykumar1** [laravel/framework#23243]
```
$array = ['key' => null];

echo data_get($array, 'key', 'default') // Result was null
$array = (object) $array;
echo data_get($array, 'key', 'default') // Result was default 

```

- Laravel Version: 5.4
- PHP Version:7.1

### Description:
Is there any specific reason for special behavior. As per documentation we can use data_get for both array and object so can we expect same behavior on both

**Comment by vlakoff** [comment]
Indeed it should be consistent, but apparently it's not doable, as it was discussed on #12602.

**Comment by vijaykumar1** [comment]
Thanks @vlakoff 
Is there any problems using one more and condition with `is_null` here
`is_object($target) && isset($target->{$segment} && is_null($target->{$segment})`

**Comment by vlakoff** [comment]
It wouldn't work, because isset($property) gives false if $property equals null.

**Comment by vlakoff** [comment]
Haven't you inverted array and object in your example? I guess it should be returning `null` for array and `'default'` for object.

**Comment by vlakoff** [comment]
Modifying these functions has already proven to be dangerous, and there are many BC concerns. You should consider the "null value" case to be a quite edgy one.

If you want something "safer", you may consider migrating your code to: `data_get($data, 'key') ?? 'default'`. Note it would handle "null value" the same as "no value", but consistently whether data is an array or an object.

**Comment by vijaykumar1** [comment]
Thanks @vlakoff 
For now i just added a custom helper to handle null and empty string cases

```
function get_data($data, $key, $default = null)
    {
        $value = data_get($data, $key);

        return !empty($value) ? $value : $default;
    }
```

**Comment by vlakoff** [comment]
I think this can be closed, as sadly there isn't much we can do, at least without introducing a huge BC break (handling "null value" the same as "no value"). Or until PHP brings some new alternative to `property_exists()`…
