### ISSUE TITLE
[5.6] When the field is updating, the mutator does not work

### ISSUE THREAD

**Issue by andrey-helldar** [laravel/framework#23242]
- Laravel Version: 5.6.3
- PHP Version: 7.2.0
- Database Driver & Version: MySQL 5.7

### Description:
When the field is updating, the mutator does not work

### Steps To Reproduce:
I have a mutator in model:
```php
use Illuminate\Support\Str;

class Filter extends Model
{
  protected $fillable = ['slug', 'title', 'deleted_at'];

  protected function setSlugAttribute($value)
  {
    $this->attributes['slug'] = Str::slug($value);
  }
}
```

I'm trying to update the entry:
```php
$data = [
  'slug' => 'Foo',
  'title' => 'Bar'
];

$item = Filter::query()
    ->where('id', $id)
    ->update($data);
```

Result:
```php
[
    "id" => 2
    "slug" => "Foo"
    "title" => "Bar"
    "created_at" => "2018-01-30 12:48:29"
    "updated_at" => "2018-02-21 12:47:57"
    "deleted_at" => null
  ]
```

**Comment by BrandonSurowiec** [comment]
You're just doing a database query. You need to load the model.

```
$item = Filter::find($id)->update($data);
```

**Comment by decadence** [comment]
@BrandonSurowiec is right.
`update` is working on DB layer when you call it on `Builder` instead of `Model` and it doesn't consider any Eloquent features like mutators and events.

**Comment by andrey-helldar** [comment]
Probably, I have read the documentation poorly. Thank you!

**Comment by haidangdevhaui** [comment]
> You're doing a database query. You need to load the model.
> 
> ```
> $item = Filter::find($id)->update($data);
> ```

It works for me, thanks so much :D
