### ISSUE TITLE
Blade sections override. Unobvious behavior

### ISSUE THREAD

**Issue by ArtemMolotov** [laravel/framework#23257]
- Laravel Version: 5.5.34
- PHP Version: 7.1.0
- Database Driver & Version: None

### Description:
Part of issue #18788
Can blade don't execute parent code of section if we don't use `@parent`?
If we use `@push` in parent section, then blade add code when is not needed...

### Steps To Reproduce:
You need 2 views:
**index.blade.php**
```blade
@extends('layout')

@section('content')
    Child
@stop

@push('scripts')
    // Child needed scripts
@endpush
```
**layout.blade.php**
```blade
@section('content')
    Parent
    @push('scripts')
        // Parent NOT needed scripts
    @endpush
@show

@push('scripts')
    // Parent needed scripts
@endpush

@stack('scripts')
```

### Expected behavior:
```html
Child

// Child needed scripts
// Parent needed scripts
```

### Actual behavior:
```html
Child

// Child needed scripts
// Parent NOT needed scripts
// Parent needed scripts
```

**Comment by ArtemMolotov** [comment]
If we change to:
**layout.blade.php**
```blade
@section('content')
    Parent
    @push('scripts')
        // Parent NOT needed scripts
    @endpush
@show

@push('scripts')
    // Parent needed scripts
@endpush

@stack('scripts')
```

Then 
### Actual behavior:
```html
Child

// Child needed scripts
// Parent NOT needed scripts
// Parent needed scripts
```

**Comment by ArtemMolotov** [comment]
Temporary solution: 

**layout.blade.php**
```blade
@section('content')
    Parent
    @if(empty($__env->yieldContent('content')))
        @push('scripts')
            // Parent NOT needed scripts
        @endpush
    @endif
@show

@push('scripts')
    // Parent needed scripts
@endpush

@stack('scripts')
```

**Comment by ArtemMolotov** [comment]
Can anyone help me with that?

**Comment by Nathanw** [comment]
You don't need to push the parent required JavaScript files to the stack, just simply put the scripts in the layout.

For Example:
```
@section('content')
    Parent
    @push('scripts')
        // Parent NOT needed scripts
    @endpush
@show

<script src="required.js"></script>

@stack('scripts')
```

This means that the parent required JavaScript files will always be first.

**Comment by ArtemMolotov** [comment]
Hi. In my case it's impossible, because I extend **vendor** view (`layout.blade.php` for example) which can include additional views in section `content`. This additional views push scripts to the stack or append section `javascript`:
```blade
@section('javascript')
    @parent
    // ...
@stop
```

Thanks for your answer, but I need to delete `// Parent NOT needed scripts` from output, instead of `JavaScript files will always be first`.

**Comment by tillkruss** [comment]
This repository is for bug reports only.

**Comment by tillkruss** [comment]
@themsaid: Is this a bug or part of the design?

**Comment by ArtemMolotov** [comment]
In OOP with method overriding, the parent method is not called if we do not use it specifically (`parent::fooBar`). Why is it not so?

We can't override **vendor** view without problems now, because the section in vendor view calls `@push`.
`@push`, in turn, adds code that should not be on the page after section overriding.

I think, the correct design should not cause such problems.

**Comment by ArtemMolotov** [comment]
> @themsaid: Closing since it's not actually a bug, this behaviour is by design, sections are compiled in order to be able to use the @parent directive.

I believe that the code from the subsections of the parent section should be added only when we ourselves called the parent section (`@parent`).

Theoretically, it is possible to make a compilation, in which the code will be "remembered", and not immediately "added." If the call to the parent section is still defined, then add the stored code.
