### ISSUE TITLE
`->groupBy('some_column')->count()` returns the wrong number of rows.

### ISSUE THREAD

**Issue by mace015** [laravel/framework#23273]
- Laravel Version: 5.5.35
- PHP Version: 7.2.2
- Database Driver & Version: MariaDB 10.1.31

### Description:
When performing a count on the following query the results will always be limited to 1, even though the 'raw' (`->toSql()` output) query returns the correct number of rows, in my case 7.

Disclaimer: This might just be a stupid mistake on my part, or a limitation of the database driver i'm using, of that i'm unsure.

### Steps To Reproduce:

Create a `hasMany` relation on any model:

`$this->hasMany(SomeModel::class)`

Then perform a count on that relation while also grouping the results:

`$this->randomHasManyRelationHere()->groupBy('some_column')->count()` results in: '1'.

When fetching the results first, and then performing a count on the collection, the correct count is returned:

`$this->randomHasManyRelationHere()->groupBy('some_column')->get()->count()` results in: '7'.

**Comment by laurencei** [comment]
I *think* this is right... in the first example you are counting the relationship - not the result?

The second one (where you use the `->get()`) - that is the count of the result?

**Comment by mace015** [comment]
I think you're right, my bad -.-
