### ISSUE TITLE
Tests\TestCase requests will show wasRecentlyCreated = true in models generated before the simulated request.

### ISSUE THREAD

**Issue by stratease** [laravel/framework#23270]
- Laravel Version: 5.5.27
- PHP Version:  7.0.22-0ubuntu0.16.04.1
- Database Driver & Version: [MongoDB v3.3](https://github.com/jenssegers/laravel-mongodb)

### Description:
In the feature test `Tests\TestCase`, Eloquent models that were created during the mocking of a database will retain the `wasRecentlyCreated ` property when a request is issued to the same model using the `TestCase::json()` method. In effect, not simulating an "update" to an existing database entry, but showing as just created in that request.

### Steps To Reproduce:
In a feature `TestCase::setup()` generate a new model, and utilize it in a test making a request to an endpoint that accesses that model. In the controller inspect the  ` Illuminate\Database\Eloquent\Model::$wasRecentlyCreated` property, it will be bool `true`. 

I uncovered it when I saw updates returning a 201 from a Resource handler.

I'm curious if `wasRecentlyCreated` should be reset in the `Model::refresh()` method?

**\** Edit - this may only relate to the User model, I have not tested on others.**

**Comment by devcircus** [comment]
Similar to https://github.com/laravel/framework/issues/2110. Still seems like the framework should be able to handle this more appropriately, but looks like calling "fresh" before using the instance, should be enough.

**Comment by stratease** [comment]
@devcircus you mean `Model::refresh()` is working, or that it should be updated to reset the `wasRecentlyCreated` property?

I think you tagged the wrong issue btw.

**Comment by devcircus** [comment]
Ahhh I did. The other issue said you could call $model->fresh(). Seems like refresh would do the same but haven't looked at the code. I'll track down the correct issue.

**Comment by devcircus** [comment]
#21107

**Comment by stratease** [comment]
Yup, that's the same issue I'm seeing. Shall I continue in that thread?

**Comment by devcircus** [comment]
I'd stay here since yours is still open.

**Comment by tillkruss** [comment]
It's not a bug, but please feel free to submit a PR for this to v5.7.
