### ISSUE TITLE
Composer replace tightenco/collect is invalid

### ISSUE THREAD

**Issue by mathieutu** [laravel/framework#23272]
https://github.com/laravel/framework/blob/85b79bb495106bf93368428f935ffb76e501e538/composer.json#L71

The `tightenco/collect` package can't work anymore with Laravel, because framework is considered as a old version of this package, and you can't install two versions of the same package in a project. 

I'm opening this just to archive it, and to warn dev if they encounter the problem.
The complete issue is here: https://github.com/tightenco/collect/issues/88

**Comment by sisve** [comment]
#### Requiring tightenco/collect directly works.

    > composer require tightenco/collect:^5.6
    ./composer.json has been updated
    Loading composer repositories with package information
    Updating dependencies (including require-dev)
    Package operations: 1 install, 0 updates, 0 removals
      - Installing tightenco/collect (v5.6.0): Downloading (100%)
    Writing lock file
    Generating optimized autoload files
    > Illuminate\Foundation\ComposerScripts::postAutoloadDump
    > @php artisan package:discover
    Discovered Package: fideloper/proxy
    Discovered Package: laravel/tinker
    Discovered Package: nunomaduro/collision
    Package manifest generated successfully.

#### Requiring a package that depends on tightenco/collect fails

    > composer require spatie/crawler
    Using version ^4.0 for spatie/crawler
    ./composer.json has been updated
    Loading composer repositories with package information
    Updating dependencies (including require-dev)
    Your requirements could not be resolved to an installable set of packages.

      Problem 1
        - Conclusion: remove laravel/framework v5.6.7
        - Conclusion: don't install laravel/framework v5.6.7
        - spatie/crawler 4.0.0 requires tightenco/collect ^5.6 -> satisfiable by laravel/framework[v5.6.0, v5.6.1, v5.6.2, v5.6.3], illuminate/support[v5.6.0, v5.6.1, v5.6.2, v5.6.3], tightenco/collect[v5.6.0, v5.6.4, v5.6.5, v5.6.6, v5.6.7].
        - spatie/crawler 4.0.1 requires tightenco/collect ^5.6 -> satisfiable by laravel/framework[v5.6.0, v5.6.1, v5.6.2, v5.6.3], illuminate/support[v5.6.0, v5.6.1, v5.6.2, v5.6.3], tightenco/collect[v5.6.0, v5.6.4, v5.6.5, v5.6.6, v5.6.7].
        - spatie/crawler 4.0.2 requires tightenco/collect ^5.6 -> satisfiable by laravel/framework[v5.6.0, v5.6.1, v5.6.2, v5.6.3], illuminate/support[v5.6.0, v5.6.1, v5.6.2, v5.6.3], tightenco/collect[v5.6.0, v5.6.4, v5.6.5, v5.6.6, v5.6.7].
        - spatie/crawler 4.0.3 requires tightenco/collect ^5.6 -> satisfiable by laravel/framework[v5.6.0, v5.6.1, v5.6.2, v5.6.3], illuminate/support[v5.6.0, v5.6.1, v5.6.2, v5.6.3], tightenco/collect[v5.6.0, v5.6.4, v5.6.5, v5.6.6, v5.6.7].
        - spatie/crawler v4.x-dev requires tightenco/collect ^5.6 -> satisfiable by laravel/framework[v5.6.0, v5.6.1, v5.6.2, v5.6.3], illuminate/support[v5.6.0, v5.6.1, v5.6.2, v5.6.3], tightenco/collect[v5.6.0, v5.6.4, v5.6.5, v5.6.6, v5.6.7].
        - Can only install one of: laravel/framework[v5.6.0, v5.6.7].
        - Can only install one of: laravel/framework[v5.6.1, v5.6.7].
        - Can only install one of: laravel/framework[v5.6.2, v5.6.7].
        - Can only install one of: laravel/framework[v5.6.3, v5.6.7].
        - don't install illuminate/support v5.6.0|don't install laravel/framework v5.6.7
        - don't install illuminate/support v5.6.1|don't install laravel/framework v5.6.7
        - don't install illuminate/support v5.6.2|don't install laravel/framework v5.6.7
        - don't install illuminate/support v5.6.3|don't install laravel/framework v5.6.7
        - don't install tightenco/collect v5.6.0|don't install laravel/framework v5.6.7
        - don't install tightenco/collect v5.6.4|don't install laravel/framework v5.6.7
        - don't install tightenco/collect v5.6.5|don't install laravel/framework v5.6.7
        - don't install tightenco/collect v5.6.6|don't install laravel/framework v5.6.7
        - don't install tightenco/collect v5.6.7|don't install laravel/framework v5.6.7
        - Installation request for laravel/framework (locked at v5.6.7, required as 5.6.*) -> satisfiable by laravel/framework[v5.6.7].
        - Installation request for spatie/crawler ^4.0 -> satisfiable by spatie/crawler[4.0.0, 4.0.1, 4.0.2, 4.0.3, v4.x-dev].


    Installation failed, reverting ./composer.json to its original content.

#### Installing a package _and_ tightenco/collect works.

    > composer require spatie/crawler tightenco/collect:^5.6
    Using version ^4.0 for spatie/crawler
    ./composer.json has been updated
    Loading composer repositories with package information
    Updating dependencies (including require-dev)
    Package operations: 14 installs, 0 updates, 0 removals
      - Installing tightenco/collect (v5.6.0): Loading from cache
      - Installing symfony/dom-crawler (v4.0.5): Loading from cache
      - Installing spatie/temporary-directory (1.1.3): Loading from cache
      - Installing spatie/image-optimizer (1.0.13): Loading from cache
      - Installing psr/http-message (1.0.1): Loading from cache
      - Installing guzzlehttp/psr7 (1.4.2): Loading from cache
      - Installing intervention/image (2.4.1): Loading from cache
      - Installing league/glide (1.3.0): Loading from cache
      - Installing spatie/image (1.4.1): Loading from cache
      - Installing spatie/browsershot (3.17.0): Loading from cache
      - Installing nicmart/tree (v0.2.7): Loading from cache
      - Installing guzzlehttp/promises (v1.3.1): Loading from cache
      - Installing guzzlehttp/guzzle (6.3.0): Loading from cache
      - Installing spatie/crawler (4.0.3): Loading from cache
    intervention/image suggests installing intervention/imagecache (Caching extension for the Intervention Image library)
    Writing lock file
    Generating optimized autoload files
    > Illuminate\Foundation\ComposerScripts::postAutoloadDump
    > @php artisan package:discover
    Discovered Package: fideloper/proxy
    Discovered Package: intervention/image
    Discovered Package: laravel/tinker
    Discovered Package: nunomaduro/collision
    Package manifest generated successfully.
