### ISSUE TITLE
Duplicated `block` function unification suggestion

### ISSUE THREAD

**Issue by webmake** [laravel/framework#23276]
- Laravel Version: 5.5.*

### Description:
While reading documentation about queues I have found `funnel` method, which under the hood uses [`ConcurrencyLimiter` class](https://github.com/laravel/framework/blob/56a58e0fa3d845bb992d7c64ac9bb6d0c24b745a/src/Illuminate/Redis/Limiters/ConcurrencyLimiter.php#L62), but as I remember same `block` mechanism already exist in [abstract `Lock` class](https://github.com/laravel/framework/blob/56a58e0fa3d845bb992d7c64ac9bb6d0c24b745a/src/Illuminate/Cache/Lock.php#L73)
but first is more advanced and reusabel due multiple locks usage.

I think ConcurrencyLimiter could extend Lock maybe, but `Lock@block` should retake improvements   from `ConcurrencyLimiter@block`

**Comment by tillkruss** [comment]
Feel free to submit a PR!
