### ISSUE TITLE
Enhancement: Check if key actually exists in the object when using the optional() helper

### ISSUE THREAD

**Issue by teoni** [laravel/framework#23275]
Hello,

Currently when using the `optional()` helper function like this:

`optional($form)->fields`

You get an error if the property (**fields** in the example) is not exist. In my opinion the Optional class should check for key existance so this way there's no need to use the isset() function.

**Comment by TheDeadCode** [comment]
Hello! I believe `optional` was never meant to be used as a [nullsafe operator](https://wiki.php.net/rfc/nullsafe_calls) replacement.

Optional only returns null on array access, property access or function calls when you passed `null` to it.

If the underlying object is set, then all calls are forwarded to it, hence your error. Make sure you pass either a valid form (that has a `fields` property that wasn't magically-set), or `null`.
