### ISSUE TITLE
Null result when Eager loading with specified field

### ISSUE THREAD

**Issue by hendra1** [laravel/framework#23283]
- Laravel Version: 5.6.5
- PHP Version: 7.2.0-1
- Database Driver & Version: Mysql 5.6

### Description:
I've got a null result in relation when trying to eager loading with select

### Steps To Reproduce:

in CartController.php

`
$cart = $this->cart->list($id);
`

in model Cart.php

`
    public function scopeList($query, $user_id)
    {

        return $query->select( 'id','product_id','quantity','information','branch')
                ->with('product:name,price,photo_list,photo')
                ->where('user_id',$user_id)->orderBy('created_at','desc');

    }
`

and the result 

![image](https://user-images.githubusercontent.com/7359548/36629337-1ae03540-1987-11e8-8a0c-705801b096aa.png)

but if eager loading without select
the relations is working

**Comment by shadoWalker89** [comment]
You must select the product id

`->with('product:id,name,price,photo_list,photo')`

**Comment by hendra1** [comment]
Now its work.. 
its weird why do I need to add foregin key field?
While in the documentation No need to add

**Comment by shadoWalker89** [comment]
When you do `->with('product:name,price ...')` you are explicitly telling eloquent what columns to select, as you can see the `id` field isn't included.

This is from the docs

![image](https://user-images.githubusercontent.com/1449151/36676215-5357be54-1b0b-11e8-8621-e5d8cbebd765.png)
