### ISSUE TITLE
Blade  Custom Directive variable passing problem

### ISSUE THREAD

**Issue by atikrahman-ew** [laravel/framework#23281]
- Laravel Version: 5.4
- PHP Version:
- Database Driver & Version:

### Description:
I can not pass variable inside custom directive
  @cperm({{$var}})
 @endcperm

Inside
    Blade::directive('cperm', function ($permission) {
            $condition = false;
            dd($permission);
       
            return "<?php if ($condition) { ?>";
        });

Just Prinitng $var not the $var content.just printing as string.

**Comment by dracola** [comment]
Pass it without braces
```php
@cperm($var)
```
and I think you don't need @endcperm

**Comment by atikrahman-ew** [comment]
@dracola  if $var passed only without quot it prints $var as string not the variable itself

**Comment by haakym** [comment]
@atikrahman-ew The issue tracker is for reporting Laravel bugs. I think your question may be better suited for one of the support channels: https://laracasts.com/discuss, https://laravel.io/forum or you could try https://stackoverflow.com.

I think @dracola has given you the right answer as to how you should call the custom directive.

Please also note in the docs here https://laravel.com/docs/5.4/blade#extending-blade it states: 

> After updating the logic of a Blade directive, you will need to delete all of the cached Blade views. The cached Blade views may be removed using the view:clear Artisan command.

So you may need to remove your cached views to see the changes you make in the custom directive before seeing any changes visibly.

Hope this helps.

**Comment by shez1983** [comment]
actually i have come across the same problem.. 

so i have a blade helper:

        Blade::directive('date', function ($expression) {
            return "<?php echo ($expression)->format('D d, M'); ?>";
        });

and normally when i echo out a model's date like so: @date($model->start_time)

works nicely..

but i am doing a foreach (on invoices grouped by date paid) so i get a collection which has a date (or null) with another collection as 'values'.. so i am doing:

@forelse($invoiceGroup as $date => $invoices)
       @date($date) 
      @foreach($invoices as $invoice)

@date($date) is giving me problems and not working.. it doesnt pass in the actual value of $date to the @date() function and so i get an error cannot format a string '$date'..

i have dumped($expression) inside the blade directive and indeed it is = to literal '$date' and not whatever the date value should be (e.g a timestamp)

(for now i have created a php helper which does the same thing but kind of annoying..)

**Comment by OgunsakinDamilola** [comment]
Closing an issue when it is not fixed makes it impossible for others who might have faced the same problem and have solutions to recommend their solutions. @tillkruss

**Comment by tillkruss** [comment]
@OgunsakinDamilola: If you want to file a reproducible bug report, you can do that here: https://github.com/laravel/framework/issues/new?assignees=&labels=&template=1_Bug_report.md
