### ISSUE TITLE
Custom Validation message

### ISSUE THREAD

**Issue by xerifandtomas** [laravel/framework#23280]
Laravel Version:  >=5.2

For the next validation if the request is ajax and had errors.

    <?php

    namespace App\Http\Requests\Example;

    use Illuminate\Foundation\Http\FormRequest;

    class Example extends FormRequest
    {
        /**
         * Determine if the user is authorized to make this request.
         *
         * @return bool
         */
        public function authorize()
        {
            return true;
        }

        /**
         * Get the validation rules that apply to the request.
         *
         * @return array
         */
        public function rules()
        {
            return [
                'input_example' => 'Example',
            ];
        }

        public function messages()
        {
            return [
                'input_example.Example' => 'Custom field error message.'
            ];
        }
    }

We get the following answer:

    {
        "message":"The given data was invalid.",
        "errors":
            {
                "input_example":["Custom field error message."]
            }
    }

How custom the "message"?

>  "message":"The given data was invalid.",

In the ValidationException.php is hardcode

https://github.com/laravel/framework/blob/ebbefd8723125d094a09c940ff27919b9ae9f2d1/src/Illuminate/Validation/ValidationException.php#L56

I want add at i18n (/resources/lang/XX/validation.php)

**Comment by medz** [comment]
See the issue: 👉https://github.com/laravel/framework/issues/21059
We have discussed a lot here, there are some temporary methods.
