### ISSUE TITLE
A non well formed numeric value encountered

### ISSUE THREAD

**Issue by RayleBool** [laravel/framework#23296]
"message": "A non well formed numeric value encountered",
```
"debug": {
"line": 558,
"file": "/home/vagrant/Code/larabbs/vendor/laravel/framework/src/Illuminate/Cache/Repository.php",
"class": "ErrorException",
"trace": [
"#0 /home/vagrant/Code/larabbs/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(558): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'A non well form...', '/home/vagrant/C...', 558, Array)",
```

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I suggest closing your issue ticket here? Instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.
