### ISSUE TITLE
PostgreSQL Invalid username when running via artisan

### ISSUE THREAD

**Issue by simplenotezy** [laravel/framework#23293]
- Laravel Version: 5.5.24
- PHP Version: 7.1.14
- Database Driver & Version: PostgreSQL(libpq) Version 10.1 Module version 7.1.14 (homebrew/php/php71-pdo-pgsql: stable 7.1.14 (bottled)). 

### Description:
If you set database driver to `pgsql` artisan migrate (and possibly other commands) wont work via terminal. However, if you visit via browser it seems to work.

However, I don't provide `myusernam` anywhere in the app. For some strange reason, laravel could be taking myusername which also happens to be my username on my local OS user, running the artisan command.

### How to reproduce:

Set driver to `pgsql` and run `php artisan migrate` in terminal. It will fail with error

      SQLSTATE[08006] [7] FATAL:  password authentication failed for user "myusername" (SQL: select * from information_schema.tables where table_schema = public and table_name = migrations

If I visit my application in the browser, I see error message: `SQLSTATE[42P01]: Undefined table: 7 ERROR: relation \"users\" does not exist\nLINE 1: select * from \"users\" where \"email\" = $1 limit 1\n ^ (SQL: select * from \"users\" where \"email\" = some@email.com limit 1)`, so it seems as though the credentials in `.env` is correct, since it knows the table doesn't exist, but migrations are yet to be run.

### Current workaround:

Inside `web.php` routes:

    Route::get('/migrate', function () {
        dd(\Artisan::call('migrate'));
    });

Then go to browser: https://laravelapp.test/migrate

Only way I can run migrate on the postgres database.

**Comment by sisve** [comment]
This sounds like you have existing environment variables in your terminal that overrides those in your .env file.

**Comment by simplenotezy** [comment]
@sisve How can I check this?

**Comment by simplenotezy** [comment]
Hmm..

	[myusername:~/Projects/uniqkey]$ php artisan tinker                                                                                                                                         (openshift✱)
	Psy Shell v0.8.17 (PHP 7.1.14 — cli) by Justin Hileman
	>>> env('DB_USERNAME');
	=> "admin"

**Comment by sisve** [comment]
I have no idea what you're expecting. Is `admin` the correct value? Or `myusername`?

Do a `echo $DB_USERNAME` from your terminal. If it outputs anything other than a blank string, then that value is used instead of the value provided in the .env file.

**Comment by simplenotezy** [comment]
The correct username is indeed `admin`:

    [myusername:~/Projects/uniqkey]$ echo $DB_USERNAME                                                                                                                                         

Outputs nothing.

**Comment by simplenotezy** [comment]
Could it be because I ran:

    brew install php71-pdo-pgsql

?

**Comment by laurencei** [comment]
check `DB_DATABASE` and  `DB_CONNECTION`. Looks like your pointing at a different DB to me for cli vs web.

**Comment by simplenotezy** [comment]
I have checked this  `.env` files several times, it's as it should be. How can I check for specific CLI environment variables?

**Comment by sisve** [comment]
You can just echo them from your terminal. `echo $DB_DATABASE` and `echo $DB_CONNECTION`.

**Comment by DanielGuerrero94** [comment]
> However, I don't provide myusernam anywhere in the app. For some strange reason, laravel could be taking myusername which also happens to be my username on my local OS user, running the artisan command.

pdo_pgsql as well as psql from cli will use your OS user when no username is passed that give me the hint that maybe your .env keys were cached with config:cache and returning null but you can see it perfectly with tinker so thats not the case.

Depending on the APP_ENV you can be picking up other .env file like .env.testing if that is set.

Are they any calls to env() before that route hit, maybe in a middleware, or is this happening to you in a fresh laravel installation?
