### ISSUE TITLE
Laravel can't access pivot additional column from pivot model itself

### ISSUE THREAD

**Issue by shabaz-ejaz** [laravel/framework#23298]
- Laravel Version: 5.5.35
- PHP Version: 7.0.10
- Database Driver & Version: MySQL 5.7.14

### Description:
I have a pivot model called UserTask in which I have an accessor function:

```
class UserTask extends Pivot implements HasMedia
{
    use HasMediaTrait;

    public function getCompletedAttribute()
    {
        return $this->getMedia()->isEmpty() && $this->completed;
    }



    public function task()
    {
        return $this->belongsTo(Task::class);
    }

}
```

I specify the relation in my Task model like this:

```
class Task extends Model
{
    public function users()
    {
        return $this->belongsToMany(User::class, 'user_task')->using('App\Models\UserTask')->withPivot('completed');
    }
}
```

I get the following error:

> "message": "Undefined property: App\Models\UserTask::$completed",

Anyone know why this is happening?

**Comment by kevdotbadger** [comment]
Don't you need to use `->withPivot('completed');` to ask Eloquent to get this attribute?

**Comment by staudenmeir** [comment]
Do you still have that problem?

**Comment by CyberiaResurrection** [comment]
@staudenmeir , I've also tripped over this problem - to both cast the pivot values as a model and to also be able to access pivot model columns directly (without having to do an additional $PIVOT_MODEL::find($pivot_id) ), I have to use both ->using(... and withPivot(.... , like so:
```
return $this->belongsToMany(ForeignModel::class, 'pivot_table)->using(PivotModel::class)->withPivot(['firstCol', 'secondCol', .... ])

```

**Comment by staudenmeir** [comment]
@CyberiaResurrection Can you please provide more details? What exactly is the issue?

**Comment by CyberiaResurrection** [comment]
If I define the pivot table with additional columns but don't cast the pivot values to a model, then I get a bunch of values in $foo->manyToManyRelation()->first()->pivot and not a model.  This is problematic when said pivot models also have their own, independent relations to other models (not just the implied belongsTo relations to the parent models on each side of the original M:N relation).

If I go the other way, and cast the pivot values to a model but don't specify the extra columns, that usually breaks the extra relations where they are defined on the pivot models, as the requisite key value is usually missing.

As (Morph)Pivot extends the Model class, I don't see a reason why, if my application setup needs it, to refrain from adding those extra relations directly onto pivot models.

I got the impression from the documentation that `->using(PivotModel::class)` actually implied `->withPivot(['firstColumn','secondColumn', ...])`, and wasted a good few hours chasing that mistaken assumption up the garden path.

**Comment by CyberiaResurrection** [comment]
That will slow things down somewhat, yes.  I guess joining all pivot table columns (when using a pivot model) will be too much brute-force-over-ignorance?

**Comment by staudenmeir** [comment]
That's not possible: We can't just select `pivot_table.*` because we have to alias the pivot columns. In order to do this, we have to know their names.

The only way would be a separate query that retrieves the list of columns from a meta table like `information_schema.columns`.

**Comment by CyberiaResurrection** [comment]
And that would defeat the point.  I'm not sure if anything can be done except updating the docs to note that my assumption doesn't hold.

**Comment by driesvints** [comment]
Closing as this has been added to the docs.
