### ISSUE TITLE
Integrity constraint violation when using 'enum' type in unique key

### ISSUE THREAD

**Issue by igorj74** [laravel/framework#23302]
- Laravel Version: 5.6.5
- PHP Version: 7.1.14
- Database Driver & Version: SQLite version 3.14.2

### Description:
After upgrading Laravel from 5.5 to 5.6 phpunit tests fail with 'Integrity constraint violation' error on tables which uses 'enum' type field in unique index. 
SQLite with memory type database was used and unit test class is using RefreshDatabase trait.
Please note that the following example works in Laravel 5.5.
It also works in Laravel 5.6 when 'string' type is used instead of 'enum' in migration function.

### Steps To Reproduce:
For example on migration like this one:
`Schema::create('systems', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name', 20)->index();
            $table->enum('env_type', ['local', 'staging', 'production']);
            $table->unique(['name', 'env_type']);
        });`

when trying to create object using model factory in test file:

`create('App\System', [
            'name'     => 'System',
            'env_type' => 'testing'
        ]);`

running phpunit will show the following error:

Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 19 CHECK constraint failed: systems (SQL: insert into "systems" ("name", "env_type") values (System, testing)

**Comment by sisve** [comment]
Well your enum field doesn't allow the value 'testing'. That's why the constraint fail.

**Comment by igorj74** [comment]
Thank You Simon.
Adding 'testing' to the 'enum' field resolved the issue.
What confuses me is that it worked with Laravel 5.5 :)
