### ISSUE TITLE
Unexpected relation in getMorphClass

### ISSUE THREAD

**Issue by webmake** [laravel/framework#23309]
- Laravel Version: 5.5.34 and lower
- PHP Version: 7.1

### Description:
I got strange result, using such code:
```
$a->group()->associate(\Modules\X\Entities\EntityC::find(1))->group_type;
```
It gives `group-name2` instead of expected `second-group-name2`

The bug lies under https://github.com/laravel/framework/blob/master/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php#L637 in resolving, while taking first, despite actual relation
### Steps To Reproduce:
Any Model class can have
```
    public function group(): MorphTo
    {
        return $this->morphTo();
    }
```
somewhere in code first occurence:
```
       Relation::morphMap([
            'group-name1' => \Modules\Y\Entities\EntityA::class,
            'group-name2' => \Modules\X\Entities\EntityC::class,
        ]);
```
somewhere in code second occurence:
```
            $map['second-group-name1'] = \Modules\Z\Entities\EntityB::class;
            $map['second-group-name2'] = \Modules\X\Entities\EntityC::class;

        Relation::morphMap($map);
```
After that in `getMorphClass` while executing associate, `$morphMap` is as follow:
```
array (
  'group-name1' => 'Modules\\Y\\Entities\\EntityA',
  'group-name2' => 'Modules\\X\\Entities\\EntityC',
  'second-group-name1' => 'Modules\\Z\\Entities\\EntityB',
  'second-group-name2' => 'Modules\\X\\Entities\\EntityC',
)
```

Currently that bug I resolved by extending `EntityC` with unique class name `SecondGroupEntity` and replacing `second-group-name2` place for example, but it is only workaround, not solution

**Comment by staudenmeir** [comment]
Why is `second-group-name2` the expected result?

**Comment by webmake** [comment]
Because map is not associated with actual relations, this is applied global wide. So developing there must be not written rules, that ids and classes/keys must be unique

**Comment by staudenmeir** [comment]
You have the `EntityC` class twice in your map. How should Laravel know which key you want to use?

**Comment by webmake** [comment]
I know, this is the key point 
![image](https://user-images.githubusercontent.com/5016464/39202683-4f817438-47fb-11e8-8821-488a90f73e91.png)
I can't have simple book, I must to extend book and name for ex. rentablebook as a cheat, because in map can't be duplications

**Comment by staudenmeir** [comment]
What polymorphic relationships would you use in this scenario?

**Comment by webmake** [comment]
In rents module:
```       Relation::morphMap([
            'rentable_book' => \Modules\Products\Entities\Book::class,
            'rentable_movies' => \Modules\Products\Entities\Movies::class,
        ]);
```
on the other side in store module:
```
      Relation::morphMap([
            'buyable_book' => \Modules\Products\Entities\Book::class,
            'buyable_food' => \Modules\Products\Entities\Food::class,
        ]);
```
So as a cheat I had to change `'buyable_book' => \Modules\Products\Entities\BuyableBook::class,`
`class BuyableBook extends Book`

I don't know how more clearly explain, this is the problem, fully reprodusable, no need to take deep knowledge about bussiness relations

**Comment by webmake** [comment]
To duplicate database table is as alternative, to avoid such multi morph problem, I think framework should keep relations with context with parent, in case to handle repeatable entities. It's not a question about key of array, it is value in array problem

**Comment by driesvints** [comment]
I don't get why you'd define it twice. Just do this:

```php
Relation::morphMap([
    'books' => \Modules\Products\Entities\Book::class,
    'movies' => \Modules\Products\Entities\Movies::class,
    'food' => \Modules\Products\Entities\Food::class,
]);
```

**Comment by webmake** [comment]
Extend book as RentableBook and BuyableBook, this is not nice solution, to have 3classes which 2 of them differs only class name, while content will be the same - empty, because it would extend Book with whole content.

**Comment by driesvints** [comment]
Ah I see. Doesn't this work?

```php
Relation::morphMap([
    'rentable_books' => \Modules\Products\Entities\RentableBook::class,
    'buyable_books' => \Modules\Products\Entities\BuyableBook::class,
]);
```

**Comment by webmake** [comment]
Yes, it works, but I expected 
```
'buyable_book' => \Modules\Products\Entities\Book::class,
'rentable_book' => \Modules\Products\Entities\Book::class,
``` 
to work

**Comment by driesvints** [comment]
That can't possible work. How would Eloquent "guess" which model to use?

**Comment by webmake** [comment]
I think here should specify the key:
```
    public function group(): MorphTo
    {
        return $this->morphTo();
    }
```
like:
```
class Product {
    public function book(): MorphTo
    {
        return $this->morphTo('buyable_book');
    }
}
```
