### ISSUE TITLE
Illuminate\Support\Optional could not be converted to string if underlying object can

### ISSUE THREAD

**Issue by TheDeadCode** [laravel/framework#23303]
- Laravel Version: `5.6.3`
- PHP Version: `7.1.13`
- Database Driver & Version: N/A

### Description:
[Illuminate\Support\Optional](src/Illuminate/Support/Optional.php) is meant to be a transparent way of calling methods and getting attributes, although, it does not support a `__toString` direct cast even if the underlying object supports it.

### Steps To Reproduce:
```php
class CanBeCastedToString
{
    protected $theString;

    public function __construct($string)
    {
        $this->theString = $string;
    }

    public function __toString()
    {
        return $this->theString;
    }
}

$s = new CanBeCastedToString('Testing');
echo (string) $s;
echo (string)optional($s);
```

#### Expected Output
`TestingTesting`

#### Output Obtained
```
Testing
PHP Recoverable fatal error:  Object of class Illuminate\Support\Optional could not be converted to string on line 1
```

### Proposed Fix
Add a `__toString()` to the optional class, casting directly the underlying object if not null. If it failed, then the abovementioned fatal error will be thrown, like it would have if the object wasn't of type `Optional`.

**Comment by tillkruss** [comment]
Yeah, feel free to submit a PR for this to 5.6.

**Comment by themsaid** [comment]
Closing since the accompanied PR was rejected, you can discuss your proposal on larave;/internals.
