### ISSUE TITLE
interesting bug on uppercase/lowercase primary key in model

### ISSUE THREAD

**Issue by mph2labs** [laravel/framework#23314]
- Laravel Version: 5.6
- PHP Version: 7.1
- Database Driver & Version: mysql

### Description:
When using the model create method using something like 

`$f = \App\Flights::create($data) `

for a table that has a primary key Id as opposed to id , I cannot use $f->Id to access the id of the model and instead I got to use lowercase $f->id

However when I use the find method for the same table and model using something like 

`$f = \App\Flights::find($id)`

 I cannot use $f->id to access the id of the model and instead I got to use uppercase $f->Id

### Steps To Reproduce:
create a model that uses a primary key of Id as opposed to id and set the protected variable in the model to 
` protected $id = "Id";`

**Comment by haakym** [comment]
I was able to reproduce the error without `protected $id = "Id"` on the model. However, when I set the primary key on the model it stopped the issue from occuring: `protected $primaryKey = "Id"`.

My set up...

**Flights migration**
```php
class CreateFlightsTable extends Migration
{
    public function up()
    {
        Schema::create('flights', function (Blueprint $table) {
            $table->increments('Id');
            $table->string('Name')->nullable();
            $table->timestamps();
        });
    }
```

**Flight model**
```
class Flight extends Model
{
    protected $primaryKey = "Id";
}
```

Output from tinker session:
`create()`
```bash
λ art tinker                                          
Psy Shell v0.8.17 (PHP 7.1.12 — cli) by Justin Hileman
>>> $f = \App\Flight::find(1);                        
=> App\Flight {#764                                   
     Id: 1,                                           
     Name: null,                                      
     created_at: "2018-02-27 13:26:47",               
     updated_at: "2018-02-27 13:26:47",               
   }                                                  
>>> $f->Id                                            
=> 1                                                                                  
```
`find()`
```bash
>>> $f = \App\Flight::find(1);         
=> App\Flight {#753                    
     Id: 1,                            
     Name: null,                       
     created_at: "2018-02-27 13:26:47",
     updated_at: "2018-02-27 13:26:47",
   }                                   
>>> $f->Id                             
=> 1                                                 
```

Using Laravel 5.6, PHP 7.1 and MySQL DB driver.

**Comment by devcircus** [comment]
Seems like this is precisely what ```protected $primaryKey = "Id";``` is supposed to do. If your app strays from the conventions that Eloquent assumes , eg. a primary key of 'id', then you must be explicit about the name of your primary key. So if you're not following the conventions, or can't because of legacy code, then you need to override the conventions with configuration.

See [eloquent conventions](https://laravel.com/docs/5.6/eloquent#eloquent-model-conventions) in the documentation. It specifically states that Eloquent assumes a primary key of 'id'.

So, to me, instead of a 'bug', this is simply expected strange behavior due to not following the conventions Eloquent expects, and not explicitly overriding the convention with your own configuration.

**Comment by mph2labs** [comment]
@haakym thanks for responding.

Not sure what I am missing here but if I try to do this in my code

```
$f = \App\Flights::create($data);
$f->Id; 
```

It does not work even with the primary key set in the model

**Comment by haakym** [comment]
@mph2labs You're welcome.

When you say it does not work I assume you mean it's returning `null`? In addition to setting the primary key did you also remove `protected $id = "Id";` from the model? Might be a good idea to, just to clear any doubt that may be causing the issue.

Could you paste your model and migration into a response if the above get's you no further so I can try reproduce. Thanks.

**Comment by themsaid** [comment]
Please continue on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
