### ISSUE TITLE
Echo <Pre> Breaks Error UI

### ISSUE THREAD

**Issue by drumer2142** [laravel/framework#23312]
- Laravel Version: 5.6.*
- PHP Version: 7.2.2

### Description:

When printing array data with (echo "<pre>") and an error occurs the error handling UI does not appear correctly.

example:
-- Create a controller TestController.php

$store = new StoreModel;
$split_data = explode(";", $store_data);
echo "<pre>";
print_r($split_dt); // generating an issue to trigger the error handler

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I suggest closing your issue ticket here? Instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.
