### ISSUE TITLE
Allow multi character separator for str_slug() ?

### ISSUE THREAD

**Issue by kaphert** [laravel/framework#23324]
- Laravel Version: 5.5.*
- PHP Version: 7.1

### Description:
Based on this question: https://laracasts.com/discuss/channels/laravel/str-slug-ate-my-baby

The `str_slug()` method does not work as expected if the separator is not a single character. 

### Steps To Reproduce:

1. Run str_slug('1000009', '%20');
2. The result is now `1%209`

### Possible solution
https://github.com/laravel/framework/blob/56a58e0fa3d845bb992d7c64ac9bb6d0c24b745a/src/Illuminate/Support/Str.php#L434
The current regex is `[$separator\s]+`. This results in a regex of `[%20\s]+` which results in replacing all characters `%` `2` `0` and `space` that are next to each other with a `%20`. See https://regex101.com/r/qi4l48/1

If we change the regex to: `($separator|\s)+` it results in a regex of `(%20|\s)+` which results in replacing only multiple occurrences of `%20` &` spaces` next to each other . See https://regex101.com/r/hQeyps/1

### Workaround
A work around for anyone experiencing this issue:

```
$slug = str_replace('-, '%20', str_slug($input, '-'));
```

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
