### ISSUE TITLE
Subselect selects only 1st column and does not form from keyword

### ISSUE THREAD

**Issue by webmake** [laravel/framework#23327]
- Laravel Version: 5.5.*
- PHP Version: 7.1

### Description:
How to reach properly subquery select attributes as below and add from properly?

```
 SELECT attribute, COUNT(*) AS items_count
                FROM (
                    SELECT attribute, attribute2
                    FROM history
                    WHERE attribute IN ('1','2','3')
                    GROUP BY attribute, attribute2
                ) subtable
                GROUP BY attribute
```

### Steps To Reproduce:
```
        dd(\DB::query()
            ->select('attribute')
            ->selectRaw('COUNT(*) AS items_count')
            ->selectSub(function(Builder $query) use ($values){
                 $query->select(['attribute', 'attribute2'])
                    ->from('history')
                    ->whereIn('attribute', $values)
                    ->groupBy('attribute', 'attribute2');
            }, 'subtable')
            ->groupBy('attribute')
            ->toSql());
```
gives only with one and first attribute:
```
select `attribute`, COUNT(*) AS items_count, (select `attribute` from `history` where `attribute` in (?, ?, ?) group by `attribute`, `attribute2`) as `subtable` group by `attribute`
```

due this code:
```
    protected function parseSubSelect($query)
    {
        if ($query instanceof self) {
            $query->columns = [$query->columns[0]];
```

**Comment by webmake** [comment]
Notable, this can't be replaced by 
```
\DB::select('SELECT attribute, COUNT(*) AS items_count
                FROM (
                    SELECT attribute, attribute2
                    FROM history
                    WHERE attribute IN (?)
                    GROUP BY attribute, attribute2
                ) subtable
                GROUP BY attribute',
            $values
        )
```
because this returns one result, if (?) will be replaced by (?,?) - then 2results will be returned,and so on, so I am not sure how much values there will be, so expected in OOP style to build query, and get properly bindings by laravel itself, but at some point this no works?

**Comment by staudenmeir** [comment]
The line was added in #19013.

**Comment by webmake** [comment]
Yeah, but that PR solves some problem. Once again take a look at bolded query parts, that are not presented using `selectSub`

SELECT attribute, `COUNT(*)` AS items_count
                **FROM** (
                    SELECT attribute **, attribute2**
                    FROM history
                    WHERE attribute IN (?, ?, ?)
                    GROUP BY attribute, attribute2
                ) subtable
                GROUP BY attribute
I think this is not reachable using that function, so question remains how to reach same functionality without any hacks, such as string fill with lenght of parameters in where clause

**Comment by staudenmeir** [comment]
Can you please take a look at this @cdstarling?

**Comment by cdstarling** [comment]
When I created my pull request I initially tried to solve the problem in the `QueriesRelationships` to avoid this sort of situation in which I missed a use case for the subquery with multiple selects.

For some reason I couldn't get it to work within the `withCount` method but I've just tried it and it seems to work fine, so I will make a pull request for that now.

**Comment by staudenmeir** [comment]
@laurencei Can be closed.
