### ISSUE TITLE
Nested resource collections dont't have 'links' and 'meta' keys

### ISSUE THREAD

**Issue by fero** [laravel/framework#23328]
- Laravel Version: 5.6.6
- PHP Version: 7.1.9

### Description:
Ther doens't seem to be a way to for nested resource collections inside another resource to include the paginator meta data.
If you return the resource collection from a controller, like so:
```php
    public function list(): PostCollection
    {
        return new PostCollection(Post::with('author')->paginate(10));
    }
```
returns

```json
{
    "data": [
        ...
    ],
    "links": {
        "first": "http://proj21.dev/api/v1/posts?page=1",
        "last": "http://proj21.dev/api/v1/posts?page=2",
        "prev": null,
        "next": "http://proj21.dev/api/v1/posts?page=2"
    },
    "meta": {
        "current_page": 1,
        "from": 1,
        "last_page": 2,
        "path": "http://proj21.dev/api/v1/posts",
        "per_page": 10,
        "to": 10,
        "total": 15
    }
}
```

But when instantiate the collection inside the resource

```php
<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class UserResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        $data = [
            'id'    => $this->id,
            'name'  => $this->name,
            'email' => $this->email,
        ];

        if ($this->relationLoaded('posts')) {
            $collection = new PostCollection($this->posts()->paginate(2));
            $data['posts'] = $collection;
        }

        return $data;
    }
}
```
it only returns

```json
{
    "data": {
        "id": 23,
        "name": "Edyth Willms",
        "email": "gerry23@gmail.com",
        "posts": [
            {
                "id": 2,
                "post_item": "project",
                "post": {
                    "id": 4,
                    "author": {
                        "id": 1,
                        "name": "Victor Dumitru",
                        "email": "vctr.dumitru@gmail.com"
                    },
                    "title": "Officiis porro numquam quod expedita sed atque.",
                    "subtitle": "Perspiciatis sint non eos exercitationem ut ut aut dolore.",
                    "description": "Molestiae dolor quia placeat. Quaerat dolor voluptas consequatur.",
                    "start_date": "2018-03-04",
                    "start_time": "2018-03-04 04:00:00",
                    "end_date": "2018-03-25",
                    "end_time": "2018-03-25 01:00:00"
                }
            },
            {
                "id": 8,
                "post_item": "project",
                "post": {
                    "id": 17,
                    "author": {
                        "id": 21,
                        "name": "Pablo Rogahn",
                        "email": "kayden42@hotmail.com"
                    },
                    "title": "Labore porro est fugiat voluptatibus.",
                    "subtitle": "Omnis sed cupiditate quo qui voluptas quis non eum delectus officia deserunt.",
                    "description": "Id laboriosam dolores consequatur est. Facere rerum incidunt consequuntur.",
                    "start_date": "2018-05-18",
                    "start_time": "2018-05-18 21:00:00",
                    "end_date": "2018-05-21",
                    "end_time": "2018-05-21 12:00:00"
                }
            }
        ]
    }
}
```

The return value should include the 'links' and 'meta' keys.

**Comment by jacobfogg** [comment]
I have found similar restrictions. My guess is that these are complicated problems with no one-size-fits-all solution. I think for most people, they would prefer to not nest links and meta as a sub-record. 

In your use case specifically, I would guess that the assumption is that you would not typically have a need to paginate a nested result and therefore would not have a need for page related links and meta data.

Like you though, I would prefer a bit more flexibility. In fact, I like the idea of each record in a collection to contain a "links"=>["self"=>"url"] element. This may not solve your problem completely, but I have found that careful combination of both a Resource and a ResourceCollection allows me to achieve this goal. My Resource Collection is minimalistic, but my Resource wraps the record in a data object and adds in the links object. This works for both the individual record as well as the collection. I mention this for the sake of others who may stumble upon this, as well as to encourage you to experiment with your resources a bit more to see if there might be a creative solution already possible. If nothing else, you might try something like: `$data['posts'] = ['data'=>$collection, 'meta'=>['"total": $collection->resource->total, etc];` ... I know it's kind of a manual pain, but I am sure you can abstract a method into a base class to do that for you.

Best of luck!

**Comment by driesvints** [comment]
Pagination is only available for top level results.

**Comment by xerron** [comment]
And how do I add pagination in a ResourceCollection?
