### ISSUE TITLE
i have problem like you although i had rename const but it dont work for me, i can not understand why

### ISSUE THREAD

**Issue by 17Edwin** [laravel/framework#23332]
- Laravel Version: #.#.#
- PHP Version:
- Database Driver & Version:

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I suggest closing your issue ticket here? Instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.
