### ISSUE TITLE
where exists / whereHas is selecting all the columns from subquery 

### ISSUE THREAD

**Issue by rajjanorkar** [laravel/framework#23341]
`"select * from `users` where exists (select * from `social_logins` where `users`.`id` = `social_logins`.`user_id` and `provider` = ? and `social_id` = ?) and `users`.`deleted_at` is null "
`

- Laravel Version: 5.4
- PHP Version: 5.6
- Database Driver & Version: 

### Description:
When i use whereHas it is selecting all the columns from subquery can we just check whether it is exist or not something like (check subquery i replaces * with 1)

`"select * from `users` where exists (select 1 from `social_logins` where `users`.`id` = `social_logins`.`user_id` and `provider` = ? and `social_id` = ?) and `users`.`deleted_at` is null "
`

### Steps To Reproduce:
run any query with whereHas

**Comment by staudenmeir** [comment]
From the MySQL documentation:

> Traditionally, an EXISTS subquery starts with SELECT *, but it could begin with SELECT 5 or SELECT column1 or anything at all. MySQL ignores the SELECT list in such a subquery, so it makes no difference.

https://dev.mysql.com/doc/refman/5.7/en/exists-and-not-exists-subqueries.html

**Comment by rajjanorkar** [comment]
wow thanks @staudenmeir

**Comment by jmarcher** [comment]
If this solves your problem can you kindly close this issue?

**Comment by rajjanorkar** [comment]
Thank you
