### ISSUE TITLE
Paginate method wont work with having on aliases

### ISSUE THREAD

**Issue by yeknava** [laravel/framework#23347]
- Laravel Version: 5.5.35
- PHP Version: 7
- Database Driver & Version: Mysql 5.7.21

### Description:
Paginate method wont work when i try to use having on aliases.

### Steps To Reproduce:
this works:
return User::select('id as uid')->havingRaw('uid > 1')->get();
this wont work:
return User::select('id as uid')->havingRaw('uid > 1')->paginate(3);

Error:
SQLSTATE[42S22]: Column not found: 1054 Unknown column &#039;uid&#039; in &#039;having clause&#039; (SQL: select count(*) as aggregate from `users` having uid &gt; 1)

**Comment by staudenmeir** [comment]
The problem is the `HAVING` part, not the alias. See https://github.com/laravel/framework/issues/3105.

**Comment by jmarcher** [comment]
This section is for issues only. To ask questions please go to laracast's forums or stackoverflow.

**Comment by yeknava** [comment]
@staudenmeir thanks i will close this issue due to it is duplicated.
