### ISSUE TITLE
Issue sending Mailable to several 'to' recipients   

### ISSUE THREAD

**Issue by marionava** [laravel/framework#23345]
- Laravel Version: 5.6.#
- PHP Version: 7.1
- Database Driver & Version: mysql

### Description:

If I try to send this email. Only send it to the last 'to' recipient
```
Mail::to('samuel@gmail.com', 'Samuel')
            ->to('mario@gmail.com', 'Mario')
            ->send(new ContactMail('Hello World'));
```

**Comment by tillkruss** [comment]
You need to pass an array instead of calling the method twice.
