### ISSUE TITLE
[5.5] roave/security-advisories conflicts with erusev/parsedown ~1.6

### ISSUE THREAD

**Issue by markdwhite** [laravel/framework#23344]
- Laravel Version: 5.5.35
- PHP Version: PHP 7.0.25-0ubuntu0.16.04.1
- Database Driver & Version: Server version: 5.7.21-0ubuntu0.16.04.1-log

### Description:
Roave added a conflict for parsedown <=1.6.4 previously, and this was updated to < 1.7 a few hours ago. Laravel requires ~1.6 so a version bump might be in order

### Steps To Reproduce:
composer update
composer require --dev roave/security-advisories:dev-master
Results in:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - roave/security-advisories dev-master conflicts with erusev/parsedown[1.6.4].
    - roave/security-advisories dev-master conflicts with erusev/parsedown[1.6.4].
    - roave/security-advisories dev-master conflicts with erusev/parsedown[1.6.4].
    - Installation request for roave/security-advisories dev-master -> satisfiable by roave/security-advisories[dev-master].
    - Installation request for erusev/parsedown (locked at 1.6.4) -> satisfiable by erusev/parsedown[1.6.4].

**Comment by laurencei** [comment]
shouldnt `~1.6` allow composer to get the latest 1.7 version or greater ?

**Comment by markdwhite** [comment]
Er...yes. Sorry - this shows that I don't understand composer constraints as well as I thought.

Running 'composer update' again pulls the new version of parsedown, and then security-advisories installs happily.

My bad. Nothing to see here. Please move along...
