### ISSUE TITLE
Using different guard in Pusher Broadcasting authentication

### ISSUE THREAD

**Issue by willypuzzle** [laravel/framework#23353]
- Laravel Version: 5.5.34
- PHP Version: 7.2

### Description:
When I authenticate for broadcasting private channel, the system only allow authentication for default guard users only. But I have more then one user in my system and I use different guards so I need to use different guard in Broadcasting authentication. But as I see in method auth of PusherBroadcaster class the request only looks for default guard users only.

### Steps To Reproduce:

If I have this two channels:

Broadcast::channel('user.{pack}', function ($user, Pack $pack) {
    return $user->id == $pack->user_id;
});

Broadcast::channel('customer.{pack}', function ($user, Pack $pack) {
    return $user->id == $pack->customer_id;
});

Where each of them use different type of user based on guard. The authentication for no default guard user fails. It raises a AccessDeniedHttpException exception.

**Comment by devcircus** [comment]
According to @themsaid, you can [pass options](https://github.com/laravel/framework/issues/16151#issuecomment-256911184) to Broadcast::routes() in your BroadcastServiceProvider. There you can denote the guard.

**Comment by willypuzzle** [comment]
What I have understood is that Broadcast::routes(['middleware' => 'auth:admin']) only changes the default guard for all the channels. But I have two kinds of users that use broadcasting message services at the same time. What I need is that different channels use a different guard.

**Comment by willypuzzle** [comment]
I made a small correction but only for PusherBroadcaster: the interface is like:

```
Broadcast::channel('operator.{chat}', function ($user, Chat $chat) {
    return $user->id == $chat->chat_user_id;
}, ['guard' => 'operator']);
```

You can found my fork in my repository, named 'framework'.

**Comment by sukelali** [comment]
Is your solution working now? I have faced similar problem but I could not solved the problem.It is also helpful for me if you elaborate your answer. Thanks in advanced.

**Comment by willypuzzle** [comment]
Yes, it works. I'm currently using it in a project.

**Comment by willypuzzle** [comment]
I found my own solution for on a my fork [here](https://github.com/willypuzzle/framework/tree/5.5) and it works but I don't know how to create a Test Unit for this case so I can make the same change on master branch and make a pull request. Someone can help me?

**Comment by zedentox** [comment]
You can actually use multiple guards with the ```auth``` middleware. Try using ```auth:web,operator```, they should be used one after the other. You can't use only one of them separately because there is only one route ```/broadcast/auth```. Except if you create another route as authentication endpoint...

**Comment by zedentox** [comment]
@willypuzzle Have you some time to work on this ? Maybe we can make a PR ?

**Comment by driesvints** [comment]
Did you add the `web` middleware as stated here: https://github.com/laravel/framework/issues/16151#issuecomment-342488958 ?

**Comment by rauschmerscen** [comment]
I have a custom guard 'acclaim', two places where custom guards should be  mentioned while broadcasting is in the BroadcastServiceProvider:

        Broadcast::routes(['middleware' => ['auth:acclaim']]);

and in routes/channels.php as the third parameter 
Broadcast::channel(channel_name.{id}, function ($user, $id) { ... }, ['guards' => ['acclaim']]);

Soultion to Common Problems faced by many users while setting up Laravel Echo
https://gist.github.com/rauschmerscen/2f2265976d59267f3bfccb339b27be44

**Comment by ogidimitrov** [comment]
> I have a custom guard 'acclaim', two places where custom guards should be mentioned while broadcasting is in the BroadcastServiceProvider:
> 
> ```
>     Broadcast::routes(['middleware' => ['auth:acclaim']]);
> ```
> 
> and in routes/channels.php as the third parameter
> 
> ```
>     Broadcast::channel(channel_name.{id}, function ($user, $id) { ... }, ['guards' => ['acclaim']]);
> ```
> 
> Soultion to Common Problems faced by many users while setting up Laravel Echo https://gist.github.com/rauschmerscen/2f2265976d59267f3bfccb339b27be44

For me its working with only 
```
Broadcast::channel(channel_name.{id}, function ($user, $id) { ... }, ['guards' => ['acclaim']]);
```

all the rest of the channels except this are against the default guard, which is exactly what i was trying to achieve.
