### ISSUE TITLE
Impossible to make a pivot with a created_at column but no updated_at

### ISSUE THREAD

**Issue by neodc** [laravel/framework#23363]
- Laravel Version: 5.6.3
- PHP Version: 7.2.2

### Description:

With a normal model it's possible to define CREATED_AT but set UPDATED_AT to null when there is only the created_at column and no updated_at column in my table. But in a many to many relation with a pivot it's impossible to use withTimestamps with only one parameter to have the same comportement.

Since there is no setter for `pivotCreatedAt` in `\Illuminate\Database\Eloquent\Relations\BelongsToMany` I had to use this workaround to make my usecase work:

	$relation = $this->belongsToMany(User::class, 'table_name')
		->withPivot('pivot_col');

	$withCreatedAt = function(string $createdAt)
	{
		$this->pivotCreatedAt = $createdAt;

		return $this->withPivot($this->createdAt());
	};

	$withCreatedAt->call($relation, 'date_added');

	return $relation;

Do you think it would be possible to make this easier by for example create the methodes withCreatedAt et withUpdatedAt ?

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
