### ISSUE TITLE
FactoryBuilder trying to unintentionally call field

### ISSUE THREAD

**Issue by haekb** [laravel/framework#23361]
- Laravel Version: 5.6.3
- PHP Version: 7.2.2
- Database Driver & Version: MariaDB 10.1.30

### Description:
Hey there,

For testing I've created a Provider with custom functions to dish out fake data for my model's factory.

I have a function that returns 2 random amenities in an array using `->randomElements` from faker. One of these items is "Storage". 

If Storage happens to be the first item in that array, the factory will die with an error of 
`BadMethodCallException with message 'Call to undefined method League\Flysystem\Filesystem::Restaurant'` 
(Restaurant is replaceable with whatever the second element of that array might be.) 

I've tracked it down to `FactoryBuilder@expandAttributes`, where I guess it's overlapping with the Storage facade? 

To get around this I can json_encode the fields, but this model does indeed cast that field as an array/json, so I feel like this should be safe to do. 

```
$casts = [
...
"amenities" => "array", 
...
]
```

### Steps To Reproduce:
- Have a factory return an element that contains an array with the first element being `Storage`, second element can be anything.
```
$factory->define( ... your model ..., function() {
   return [
     "foo" => ["Storage", "Bar"]
   ]
}
```
- See error
`BadMethodCallException with message 'Call to undefined method League\Flysystem\Filesystem::Bar'`

**Comment by themsaid** [comment]
Fixed here: https://github.com/laravel/framework/pull/23372

thanks

**Comment by DojoGeekRA** [comment]
The problem here is that the factory is missing the random choicer:


```php
// Wrong
$factory->define( ... your model ..., function() {
   return [
     "foo" => ["Storage", "Bar"]
   ]
}

// Right
$factory->define( ... your model ..., function() {
   return [
     "foo" => $faker->randomElement(["Storage", "Bar"]),
   ]
}
```
