### ISSUE TITLE
Update Markdown Parser for 5.5 LTS

### ISSUE THREAD

**Issue by Jantho1990** [laravel/framework#23396]
I noticed for 5.6 that a security update was issued to update the markdown parser. Shouldn't the same be done for 5.5, as it's the LTS version?

**Comment by sisve** [comment]
It was. https://github.com/laravel/framework/commit/722743ce6c638fe9af01f3ea18b6ab8cf92e7b66

**Comment by Jantho1990** [comment]
Missed that. Thanks!
