### ISSUE TITLE
when() declaration difference between Collection and BuildsQueries

### ISSUE THREAD

**Issue by spaceemotion** [laravel/framework#23394]
- Laravel Version: 5.5.36
- PHP Version: 7.2.2

### Description:
The declaration in the support class is more restrictive (does not all null values for the callbacks) as compared to the BuildsQueries trait:
https://github.com/laravel/framework/blob/5.6/src/Illuminate/Support/Collection.php#L463

```php
public function when($value, callable $callback, callable $default = null)
```

https://github.com/laravel/framework/blob/5.6/src/Illuminate/Database/Concerns/BuildsQueries.php#L88

```php
public function when($value, $callback, $default = null)
```

### Steps To Reproduce:
If I do a check like `->when($callback !== null, $callback)` on a collection it errors:

```php
$callback = null; // works if it's a proper callable
collect([])->when($callback !== null, $callback)->all();
```

Personally I'd prefer the non-restrictive variant as I can use optional callbacks without a surrounding if statement doing basically the exact same check I would have done using the when() call.

**Comment by tillkruss** [comment]
Feel free to make a PR to 5.7.
