### ISSUE TITLE
$table MUST be public when defined otherwise cannot be accessed in job dispatch

### ISSUE THREAD

**Issue by ChangePlaces** [laravel/framework#23404]
- Laravel Version: 5.5.36
- PHP Version: 7.1
- Database Driver & Version: n/a

### Description:
When using a custom table name for a model, the property `$table` must be made public, otherwise when a job that is dispatched tries to make queries, the laravel expected table name will be used instead of the custom name.

### Steps To Reproduce:
(Assuming job queue is set to database, with jobs table and failed jobs table created)

1, create a model Foo with a protected $table = 'some_foos' value and migrate to create the table
2. create a job FooJob that queries the model: 
```
    public function handle()
    {
        $x = Foo::where('some_id', 5);
    }
```
3. `FooJob::dispatch()`
4. see error in failed_jobs table showing the expected table name (some_foos) doesn't exist, but error is looking for foos
5. change the property to public to solve the issue

**Comment by ludo237** [comment]
also if you need to access to the table name without an instance you could write something like this

```php
class MyModel extends Model
{
     const TABLE = "mymodels";
     protected $table = self::TABLE;
}
```

Then you can call it whenever you need it `MyModel::TABLE`

Is not the most elegant solution but it works

**Comment by ChangePlaces** [comment]
@crynobone  I'm not trying to access table specifically. The builder is internally.

**Comment by sisve** [comment]
Could you expand the steps to reproduce to show an example model, job and the exception you get? I don't see how the fact that the query is done from a job is relevant at all; the querying should work from all places identically.

**Comment by ChangePlaces** [comment]
ok, let me make a minimum case

**Comment by ChangePlaces** [comment]
I think this is associated with running a job from tinker and problems from not being able to do JobName::dispatch()

So, I'll close this
