### ISSUE TITLE
public const visibility issue when accessing from jobs

### ISSUE THREAD

**Issue by ChangePlaces** [laravel/framework#23403]
- Laravel Version: 5.5.36
- PHP Version: 7.1
- Database Driver & Version: n/a

### Description:
I have a class filled with public const's that are being used in a job. When creating an instance of the job and calling the handle method, the job succeeds, but when calling Job::dispatch(); the job fails stating the const value can not be found. When changing the const from public const to just const removes this issue.

### Steps To Reproduce:
1. create a class that has a `public const` defined in it
2. create a job that accesses this value through the class
3. check failed_jobs table to see the job fail. 
4. Remove `public` and repeat.

### Code
```
class SaleChannelIds
{
    public const EBAY_UK = 1;
    public const ETSY = 2;
}
```

job handle method:

```
public function handle()
{
        $t = SaleChannelIds::EBAY_UK;
}
```

### Exception

```
exception: Symfony\Component\Debug\Exception\FatalThrowableError: Undefined class constant 'EBAY_UK' in /var/www/manager/app/Jobs/test.php:34
Stack trace:
#0 [internal function]: App\Jobs\test->handle()
#1 /var/www/manager/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
```

**Comment by sisve** [comment]
Could you update this with code from a real case that has this problem, and the exception you get?

**Comment by ChangePlaces** [comment]
@sisve  Updated!

**Comment by ChangePlaces** [comment]
I think this may be related to problems from dispatching a job in tinker, so I'll close this for now
