### ISSUE TITLE
sync with pivot automatically

### ISSUE THREAD

**Issue by ChitaGideon** [laravel/framework#23402]
- Laravel Version: 5.5.*
- PHP Version:7.0
- Database Driver & Version:mysql

### Description:

define a relations with pivot like:
```
    public function foods()
    {
        return $this->morphToMany('App\Models\FoodInfo', 'fooddables')->wherePivot('type', 1);
    }
```
When I try to `sync` this relation，pivot column  can not be update automatically .
```
$relation->sync([1,2,3]);//can not update type

$relation->sync([1=>['type'=>1],2=>['type'=>1],3=>['type'=>1],]);//can be work

```

**Comment by devcircus** [comment]
Look at #22867. Does that solve your issue?

So try changing ```foods()``` to:
```php
    public function foods()
    {
        return $this->morphToMany('App\Models\FoodInfo', 'fooddables')->withPivotValues('type', 1);
    }
```

**Comment by ChitaGideon** [comment]
@devcircus 
 thanks for your reply;
From that example in #22867 , It looks like the right answer if `attach` method  works in the same way as `sync` works .
If I want to use this , I have to update to 5.6 version of laravel ?
