### ISSUE TITLE
[5.5+] The exception handler can cause an endless recursive loop consuming all available memory or segfault

### ISSUE THREAD

**Issue by sisve** [laravel/framework#23415]
- Laravel Version: 5.5
- PHP Version: irrelevant
- Database Driver & Version: irrelevant

### Description:
The exception handler adds some context information by default. This involves a call to [Auth::id()](https://github.com/laravel/framework/blob/3d26ad02a4bf5f080e17bcabacf99634eaf45d59/src/Illuminate/Foundation/Exceptions/Handler.php#L152) which could cause an attempt at resolving a database connection, which in turn could [invoke the exception handler again](https://github.com/laravel/framework/blob/3d26ad02a4bf5f080e17bcabacf99634eaf45d59/src/Illuminate/Database/Connectors/ConnectionFactory.php#L186) thus causing an endless recursive loop.

This would ends up as a out-of-memory problem (it hit a memory limit of 128M in the originating Slack issue), or theoretically a segmentation fault if we let the recursive loop exhaust all stack space.

The original exception that triggered this was a "SQLSTATE[HY000] [1129] Host '...' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'", but any exception thrown when connecting to the database would match this specific stack trace.

### Stack trace from debug_backtrace
    24 => array:5 [▼
      "file" => "/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php"
      "line" => 186
      "function" => "report"
      "class" => "App\Exceptions\Handler"
      "type" => "->"
    ]
    25 => array:3 [▼
      "function" => "Illuminate\Database\Connectors\{closure}"
      "class" => "Illuminate\Database\Connectors\ConnectionFactory"
      "type" => "->"
    ]
    26 => array:3 [▼
      "file" => "/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php"
      "line" => 915
      "function" => "call_user_func"
    ]
    27 => array:5 [▼
      "file" => "/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php"
      "line" => 940
      "function" => "getPdo"
      "class" => "Illuminate\Database\Connection"
      "type" => "->"
    ]
    28 => array:5 [▼
      "file" => "/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php"
      "line" => 399
      "function" => "getReadPdo"
      "class" => "Illuminate\Database\Connection"
      "type" => "->"
    ]
    29 => array:5 [▼
      "file" => "/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php"
      "line" => 325
      "function" => "getPdoForSelect"
      "class" => "Illuminate\Database\Connection"
      "type" => "->"
    ]
    30 => array:5 [▼
      "file" => "/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php"
      "line" => 657
      "function" => "Illuminate\Database\{closure}"
      "class" => "Illuminate\Database\Connection"
      "type" => "->"
    ]
    31 => array:5 [▼
      "file" => "/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php"
      "line" => 624
      "function" => "runQueryCallback"
      "class" => "Illuminate\Database\Connection"
      "type" => "->"
    ]
    32 => array:5 [▼
      "file" => "/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php"
      "line" => 333
      "function" => "run"
      "class" => "Illuminate\Database\Connection"
      "type" => "->"
    ]
    33 => array:5 [▼
      "file" => "/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php"
      "line" => 1707
      "function" => "select"
      "class" => "Illuminate\Database\Connection"
      "type" => "->"
    ]
    34 => array:5 [▼
      "file" => "/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php"
      "line" => 1692
      "function" => "runSelect"
      "class" => "Illuminate\Database\Query\Builder"
      "type" => "->"
    ]
    35 => array:5 [▼
      "file" => "/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php"
      "line" => 479
      "function" => "get"
      "class" => "Illuminate\Database\Query\Builder"
      "type" => "->"
    ]
    36 => array:5 [▼
      "file" => "/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php"
      "line" => 463
      "function" => "getModels"
      "class" => "Illuminate\Database\Eloquent\Builder"
      "type" => "->"
    ]
    37 => array:5 [▼
      "file" => "/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php"
      "line" => 77
      "function" => "get"
      "class" => "Illuminate\Database\Eloquent\Builder"
      "type" => "->"
    ]
    38 => array:5 [▼
      "file" => "/var/www/html/vendor/laravel/framework/src/Illuminate/Auth/EloquentUserProvider.php"
      "line" => 51
      "function" => "first"
      "class" => "Illuminate\Database\Eloquent\Builder"
      "type" => "->"
    ]
    39 => array:5 [▼
      "file" => "/var/www/html/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php"
      "line" => 131
      "function" => "retrieveById"
      "class" => "Illuminate\Auth\EloquentUserProvider"
      "type" => "->"
    ]
    40 => array:5 [▼
      "file" => "/var/www/html/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php"
      "line" => 205
      "function" => "user"
      "class" => "Illuminate\Auth\SessionGuard"
      "type" => "->"
    ]
    41 => array:5 [▼
      "file" => "/var/www/html/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php"
      "line" => 292
      "function" => "id"
      "class" => "Illuminate\Auth\SessionGuard"
      "type" => "->"
    ]
    42 => array:5 [▼
      "file" => "/var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php"
      "line" => 221
      "function" => "__call"
      "class" => "Illuminate\Auth\AuthManager"
      "type" => "->"
    ]
    43 => array:5 [▼
      "file" => "/var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php"
      "line" => 152
      "function" => "__callStatic"
      "class" => "Illuminate\Support\Facades\Facade"
      "type" => "::"
    ]
    44 => array:5 [▼
      "file" => "/var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php"
      "line" => 113
      "function" => "context"
      "class" => "Illuminate\Foundation\Exceptions\Handler"
      "type" => "->"
    ]
    45 => array:5 [▼
      "file" => "/var/www/html/app/Exceptions/Handler.php"
      "line" => 39
      "function" => "report"
      "class" => "Illuminate\Foundation\Exceptions\Handler"
      "type" => "->"
    ]
    46 => array:5 [▼
      "file" => "/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php"
      "line" => 186
      "function" => "report"
      "class" => "App\Exceptions\Handler"
      "type" => "->"
    ]

**Comment by tillkruss** [comment]
Same here.

**Comment by craig0990** [comment]
I've just encountered this with an `Allowed memory size of 134217728 bytes exhausted` error running in Docker. I was (ironically) trying to test the health check endpoint.

For anyone else, I've worked around this by adding the following method override to `app/Exceptions/Handler.php`:

```
    /**
     * Get the default context variables for logging.
     *
     * Fixes https://github.com/laravel/framework/issues/23415
     *
     * @override
     *
     * @return array
     */
    protected function context()
    {
        return [];
    }
```

I would kind of like to have user data as part of the context, but it isn't worth figuring out how to access the JWT data at the moment.

**Comment by laurencei** [comment]
ping @sisve - does the PR you linked fix this issue?

**Comment by sisve** [comment]
@laurencei I havn't verified it, but it seems relevant based on the change and the stacktrace. The PR was never backported to 5.5 so this issue is still open.

**Comment by mintunitish** [comment]
Any Updates on this?

**Comment by driesvints** [comment]
@mintunitish does the PR from above fixes your problem?

**Comment by mintunitish** [comment]
@driesvints I am afraid it doesn't not.

**Comment by GrahamCampbell** [comment]
@mintunitish How sure are you your memory issue is caused by a loop in the exception handler. If there is an out of memory error raised, it can sometimes look like it was caused by the exception handler, because it will run out of memory when trying to handle the real issue.

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.
