### ISSUE TITLE
[5.6.8] Validation breaks when using objects and integers

### ISSUE THREAD

**Issue by sjdaws** [laravel/framework#23417]
- Laravel Version: 5.6.8
- PHP Version: 7.1.14, 7.2.1
- Database Driver & Version: N/A

### Description:
The [recent change made to the validator](https://github.com/illuminate/validation/commit/02a21aabcfd01a4c8e4e052ac46e8781c470abae) which returns the dataset after a successful validation breaks if you're validating data which contains an object and an integer. Because the `unique` method on the collection isn't enforcing strict types `in_array` attempts to convert the object to an integer to compare them.

### Steps To Reproduce:
This block of code shows what's happening inside the `unique` method:
```
in_array(1, [new \DateTime()], false);
```

Because the strict comparison is false the method attempts to cast all items in the array to an integer to compare it with `1`.

This method could also incorrectly discard any integer `0` when comparing with a string.

**Comment by sjdaws** [comment]
Pull request to use strict type checking here: https://github.com/illuminate/validation/pull/34

**Comment by tillkruss** [comment]
You need to send that PR to the framework instead.

**Comment by sjdaws** [comment]
This was fixed with fd94fb74ae3aec60c745d2a537e766c18eedbab6
