### ISSUE TITLE
Some wrong with order where and whereIn ..

### ISSUE THREAD

**Issue by Jimmea** [laravel/framework#23419]
I'm using laravel framework with
"php": ">=7.0.0",
"laravel/framework": "5.5.*",

I'm try to query with 
1. $locations = \DB::table('locations')
                                ->where('loc_level',$level)
                                ->whereIn('id', $arrId)
                                ->get();
2.1. $locations = \DB::table('locations')
                                ->whereIn('id', $arrId)
                                ->where('loc_level',$level)
                                ->get();

I have got command query on debug bar. It's not same.. 
In case one. The values is have change. It have destroy a some value. 
In case two. It's ok..
Please check again this._

**Comment by sisve** [comment]
Can you provide the values for $arrId and $level, and the generated sql statements?

**Comment by Jimmea** [comment]
This is value of that variables
$arrId = [40, 1, 2, 3, 4, 7, 8, 46];
$level = 1;
...

**Comment by GabrielaSaldana** [comment]
Hi, can you post your error message ?

**Comment by laurencei** [comment]
I've tried this on a fresh Laravel 5.7 install and I cant replicate.

If you have more information please feel free to post it here and I'll reopen the ticket.
