### ISSUE TITLE
Cross-Database transaction hangs on PDO::execute()

### ISSUE THREAD

**Issue by denitsa-cm** [laravel/framework#23413]
- Laravel Version: 5.6.7
- PHP Version: 7.2 
- Database Driver & Version: mysql innodb 5.7.21

### Description:

I have two connections with one mysql database schema on each - `main` and `tenant`.
The problem occurred while testing with `RefreshDatabases` and a mysql database (so **not** in memory). 

I cannot not create a `tenant` model (say a Product) from a factory if that factory also calls a factory creating a `main` model (say a User), with a foreign key from the `tenant` model to the `main` model. 

Like in the example below - Product being on `tenant`, User being on `main` connections. It just hangs on the call to this factory. 

```
$factory->define(Product::class, function (Faker $faker) {
    return [
        'name' => $faker->text(10),
        'owner_id' => function () {
            return factory(User::class)->create()->id;
        },
    ];
});
```

I have been dealing with this on and off for some days now and involved someone more knowledgeable than me to help me with this. We(he) narrowed down the "hanging" to this line https://github.com/laravel/framework/blob/5.6/src/Illuminate/Database/Connection.php#L458.

Not sure if I'm trying to do something that's not allowed, or it's just not supported. 

### Steps To Reproduce:

A migration for a `tenant` model (note the foreign key referencing a `main` model): 

```
    public function up()
    {
        Schema::create('products', function (Blueprint $table) {
            $main_db = $this->getMainDatabasePrefix();

            $table->increments('id');
            $table->string('name');
            $table->integer('owner_id')->unsigned();
            $table->timestamps();
            $table->softDeletes();

            $table->foreign('owner_id')->references('id')->on('main.users'));  
        });
    }
```

The tenant model has its connection set in a base tenant model `$this->connection = config('database.tenant');` (which evaluates to `tenant`).

A `protected $connectionsToTransact = ['main', 'tenant'];` property is set in a TestCase base class.

A tinker session demonstrating the "hanging": 

```
>>> DB::connection('main')->beginTransaction();
=> null
>>> factory(App\User::class)->create();
=> App\User {#825
     name: "Shirley Kozey",
     email: "hodkiewicz.kyler@example.com",
     updated_at: "2018-03-06 18:37:23",
     created_at: "2018-03-06 18:37:23",
     id: 5,
   }
>>> $product = new Product();
[!] Aliasing 'Product' to 'App\Product' for this Tinker session.
=> App\Product {#778}
>>> $product->name = 'test';
=> "test"
>>> $product->owner_id = 5;
=> 5
>>> $product->save();

....hangs
```

For now the solution is to not have a foreign key to the main table (even though I would very much like that).

Help or advice is much appreciated!

**Comment by halaei** [comment]
Tables that you query via 2 connections in the same process should not have any foreign key to each other. Otherwise the DBMS might locks your first connection waiting for the second one to commit a transaction, while in your process you are currently querying on the first connection which can mean the second connection is logically waiting for the first, hence the deadlock which is outside the knowledge of DBMS.

**Comment by denitsa-cm** [comment]
@halaei I see, thank you for the explanation. I _guess_ I could achieve what I want with triggers at some point in the future then..

**Comment by cbj4074** [comment]
@denitsa-cm Thank you for taking the time to document this behavior so meticulously.

I have an identical use-case, but I happen to be using PostgreSQL, and this locking issue doesn't seem to manifest with PostgreSQL + InnoDB.

Have you tried this with PostgreSQL, by chance?

That said, it is entirely possible that this approach is "a bad idea", nonetheless, for the reason that @halaei describes. Although, I must admit, I don't fully understand why the deadlock occurs (more comprehensive examples would be helpful), or why it doesn't seem to occur with PostgreSQL in the limited scenarios I've explored.

One small but crucial detail I should add is that in PostgreSQL, the referring table's foreign key must be defined with `DEFERRABLE INITIALLY DEFERRED`, or the `id` value inserted into the first table is not "visible" when the referring row is inserted into the second table.

In any case, I just wanted to mention that PostgreSQL could potentially be a solution to your problem. If I find a few moments, I'll attempt your Steps to Reproduce against PostgreSQL and report my findings.

**Comment by cbj4074** [comment]
I encountered this situation again in MySQL and had to dive back into finding a solution to this (major, in my opinion) limitation.

After writing tests to prove the behavior, I can say definitively that switching from MySQL to PostgreSQL solves this problem (at least in the use-case that we're discussing).

There are 3 components to the solution:

### 1.) Switch from MySQL to PostgreSQL.

Curiously, this change alone causes the wait-lock exception error to change to a `Foreign key violation`, which notes that `Key (user_id)=(1) is not present in table "users"`. My point is only that MySQL and PostgreSQL seem to differ fundamentally in how they handle the scenario that we're discussing.

### 2.) Define the foreign key on the referencing table with `DEFERRABLE INITIALLY DEFERRED`.

Laravel does not have a built-in mechanism for this, so a raw statement is necessary, e.g., in a migration. **IMPORTANT**: The `DB::statement()` call cannot reside in the same migration file that creates the table with the column in question; it must reside in a separate, and subsequently executed, migration. A sample statement (e.g., to be placed in the migration's `up()` method):

```php
DB::statement('
    ALTER TABLE products ADD CONSTRAINT user_fk FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY DEFERRED;
');
```

### 3). Enforce a transaction on the _referring_ connection.

The referring (`products`) connection **must** be transacted, or `DEFERRABLE INITIALLY DEFERRED` has no effect, and the test fails; the referenced (`main`) connection may or may not be transacted; it doesn't affect the outcome.

Here is the simple test case (for Laravel 8), which passes when both connections use the `pgsql` driver and the other requirements, as noted above, are met:

```php
<?php

namespace Tests\Feature;

use App\Models\Product; // This model's $connection is set to 'products'.
use App\Models\User; // This model's $connection is not set, and so uses the default.
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class MultiConnectionForeignKeyTest extends TestCase
{
    use RefreshDatabase;

    // In MySQL, only the connection that the foreign key references needs to be
    // transacted for the lock-wait timeout to occur. So, as long as the above
    // trait is present and $connectionsToTransact is not set to an empty array,
    // this test will never pass with MySQL.

    // In PostgreSQL, the referring ('products') connection MUST be transacted,
    // or "DEFERRABLE INITIALLY DEFERRED" on product.user_id has no effect, and
    // the test fails. The referenced connection may or may not be transacted;
    // it doesn't affect the outcome. In other words, this test will ass as long
    // as the above trait is present, and/or the following line is un-commented.

    #protected $connectionsToTransact = ['products'];

    public function setUp(): void
    {
        parent::setUp();
    }

    /**
     * Ensure that foreign key references across separate connections do not
     * cause deadlocks within transactions.
     *
     * @return void
     * @test
     */
    public function foreignKeysAcrossConnectionsDoNotCauseLocking()
    {
        $user = User::factory()->create();

        $product = Product::factory()->make();

        $product->user_id = $user->id;

        $product->save();

        $this->assertTrue(true);
    }
}
```

This test will throw an exception in MySQL, and, to my knowledge, can never be made to pass.

The only "solution" to this problem on MySQL seems to be either: a) don't use any foreign keys (_cringe_) or b) never use more than one connection when a transaction is required.

This is all the reason I need never to use MySQL for anything important.

**Comment by malandles** [comment]
Thank you all for the documented issue, this helped a lot.

As a workaround for MySQL and only if this hangs in tests, due to `RefreshDatabase` using transactions. You can disable foreign key checks at the test level so the transaction doesn't hang in a deadlock.

In the base `TestCase`, I added the following methods:
```php
    /**
     * Disables the foreign key checks.
     *
     * @param  string  $connection
     *
     * @return void
     */
    protected function disableForeignKeyChecks (string $connection = null): void
    {
        DB::connection($connection)->statement('SET FOREIGN_KEY_CHECKS=0;');
    }

    /**
     * Enables the foreign key checks.
     *
     * @param  string  $connection
     *
     * @return void
     */
    protected function enableForeignKeyChecks (string $connection = null): void
    {
        DB::connection($connection)->statement('SET FOREIGN_KEY_CHECKS=1;');
    }
```

Then in the actual test from @cbj4074, you disable the check:
```php
    /**
     * Ensure that foreign key references across separate connections do not
     * cause deadlocks within transactions.
     *
     * @return void
     * @test
     */
    public function foreignKeysAcrossConnectionsDoNotCauseLocking()
    {
        $this->disableForeignKeyChecks();
        $this->disableForeignKeyChecks('products');

        $user = User::factory()->create();

        $product = Product::factory()->make();

        $product->user_id = $user->id;

        $product->save();

        $this->assertTrue(true);

        $this->enableForeignKeyChecks();
        $this->enableForeignKeyChecks('products');
    }
```

The test will pass and not create any deadlock.

**This workaround should only be used for tests**, and even then, it seems counter-productive to not test the foreign keys. The real solution would be to switch to PostgreSQL, as already mentionned. Commenting for other devs that might have a hard-requirement for MySQL too.
