### ISSUE TITLE
Eager loading makes unnecessary selects that will always return no results

### ISSUE THREAD

**Issue by darorl89** [laravel/framework#23429]
When eager loading based on key that is nullable, and it's the only value in the set, laravel sends query that will always return 0 results (as id in other table is not nullable).

```
   public function bucket()
    {
        return $this->belongsTo(Bucket::class);
    }

```

```
select * from `buckets` where `buckets`.`id` in (NULL)
```

**Comment by sisve** [comment]
How would Laravel know that the buckets.id column is non-nullable? What if it were?

**Comment by darorl89** [comment]
Well I guess there should be a way to prevent spamming queries if certain conditions are met,

**Comment by darorl89** [comment]
Trying to make a workaround, and returning null as relation prevents eager loading of other relations, so I'm unable to even do workaround.

**Comment by darorl89** [comment]
Ok, I made a workaround to prevent the calls, but it's really shame that framework pushes devs to add dirty workaround code just to spare db some unnecessary queries...

**Comment by devcircus** [comment]
Eloquent isn't meant to be able to handle every possible use-case, but if there's something it could do better, that you think may help other devs, submit a pr. That's how an open source project/library improves. We notice things that could be better, then help make it better.

**Comment by rbochenski** [comment]
@darorl89 can you share your workaround?

**Comment by darorl89** [comment]
@rbochenski 
https://gist.github.com/darorl89/19a6ee15a3b6f19a1cc1c3513773737f

**Comment by fisharebest** [comment]
> How would Laravel know that the buckets.id column is non-nullable? What if it were nullable?

Even it was nullable, the query cannot return anything.  `NULL` is not equal to `NULL`, so that a where clause `WHERE xxx IN (NULL)` can **NEVER** return any rows.

If your data model has a lot of nullable relations, then this issue almost doubles the number of DB calls...

**Comment by rbochenski** [comment]
@darorl89 thanks
