### ISSUE TITLE
Laravel Model Events are not detecting soft delet items

### ISSUE THREAD

**Issue by mubbi** [laravel/framework#23425]
- Laravel Version: 3.6.5
- PHP Version: 7.1.7
- Database Driver & Version:  libmysql - mysqlnd 5.0.12-dev - 20150407

### Description:
As in general in eloquent queries, Laravel automatically ignore the soft deleted items and fetch only those items which are not soft deleted. According to the eloquent model Event the "deleting" and "deleted" events are triggered when we do a soft delete or permanent delete.
And i just found that in these events the eloquent is not automatically detecting soft delete and ignore soft deleted items. Which results in that like if we want to run an action on permanent delete only but it is also running on soft delete too which must not be the case because of eloquent default nature of ignoring soft deleted items.

What i suggest is to make 2 more new events for soft deleting and soft delete in framework or make the eloquent automatically detect the item is soft deleted and act deleting only on permanent delete until the user gives directions to act on soft delete too.

Note: i know that doing a little trick with if condition in events class i can detect item is soft deleted or not but that must have been done by eloquent automatically because of its nature to soft deleted items.

### Steps To Reproduce:
1. Model: https://github.com/mubbi/laravel-blog-5.6.5/blob/master/app/Blog.php
2. Controller - check only destroy() and permanentDelet() methods: https://github.com/mubbi/laravel-blog-5.6.5/blob/master/app/Http/Controllers/Admin/BlogsController.php
3; Events: https://github.com/mubbi/laravel-blog-5.6.5/tree/master/app/Events

**Comment by sisve** [comment]
This repo is used for bug reports. Try discussing your idea in https://github.com/laravel/internals, on Slack, or just send a PR with the suggested changes.

**Comment by mubbi** [comment]
i am not just giving an idea, i am "reporting the bug" and telling the author to resolve it by my suggestions or his own ideas.

**Comment by driesvints** [comment]
@sisve is right. This should be discussed in the https://github.com/laravel/ideas repo because this is a feature request.
