### ISSUE TITLE
Get error for a specific rule.

### ISSUE THREAD

**Issue by websanova** [laravel/framework#23421]
Issue is that there is no way to map validation field rules to specific messages.

Seems the validator is removing duplicate messages and message bag does not provide any way to access a message by it's field and rule. Something like `->get('email.blah')`.

Assume we setup some simple validation for a login.

~~~
class LoginRequest extends FormRequest
{
    public function rules()
    {
        return [
            'email' => [
                'required',
                'email',
                'min:1',
                'max:2',
                'user_password',
            ]
        ];
    }

    public function messages()
    {
        return [
            'email.email' => 'Invalid credentials',
            'email.user_password' => 'Invalid credentials',
        ];
    }
}
~~~

If we sent some dummy password like: `blah`.

We will get some error messages like:

~~~
Array
(
    [email] => Array
        (
            [0] => Invalid credentials
            [1] => The email may not be greater than 2 characters.
        )
)
~~~

There should technically be a third message there for `Invalid Credentials`. If we were to modify one of the messages to something else like `Invalid Credentialssss` we would in fact see it.

The problem is that there doesn't seem to be a way to get the specific message for the rule. For instance in this case we have no idea what rule maps to what message.

This is in the error handler accessing `$e->validator` but I guess doesn't really matter.

I've tried dumping many things from:

https://laravel.com/api/5.6/Illuminate/Validation/Validator.html
https://laravel.com/api/5.6/Illuminate/Support/MessageBag.html

All the same results for messages. Would be nice if there was some easy method to get this list or some way to access a raw message rule message list.

In the end I'm trying to feed this format to the front end.

~~~
['field' => 'email', 'rule' => 'email', 'msg' => 'Invalid Credentials'],
['field' => 'email', 'rule' => 'user_password', 'msg' => 'Invalid Credentials'],
['field' => 'email', 'rule' => 'max', 'msg' => 'The email may not be greater than 2 characters.']
~~~

Need a way to associate rules with the fields errors.

**Comment by mcglonelevi** [comment]
I took a look at the MessageBag source code in https://github.com/laravel/framework/blob/5.6/src/Illuminate/Support/MessageBag.php

There is a check to make sure that values entering the MessageBag are unique.  This would explain the behavior that you are seeing.  I don't think the MessageBag was meant for what you are trying to do.  If you still need this functionality, you might consider extending Validator with a custom extension of MessageBag.

**Comment by JayBizzle** [comment]
If I understand correctly, I proposed something like this a while back, but it was rejected - https://github.com/laravel/framework/pull/19148

**Comment by laurencei** [comment]
Closing, as this PR has been mentioned and rejected before.

You are welcome to discuss it further in laravel/ideas as well.
