### ISSUE TITLE
unexpected behavior whereRaw

### ISSUE THREAD

**Issue by jfelipeara** [laravel/framework#23428]
- Laravel Version: 5.5.#
- PHP Version:7.1
- Database Driver & Version: mysql 5.7

### Description:
I'm having trouble with TIMESTAMPDIFF in a WhereRaw
``
$item->recharges()->whereRaw('TIMESTAMPDIFF(HOUR, recharges.created_at, now()) < 14 ')->get()
``
I'm getting this error:
General error: 1 no such column: HOUR

Thank you

**Comment by robclancy** [comment]
`$item->recharges()->whereRaw('TIMESTAMPDIFF(HOUR(), recharges.created_at, now()) < 14 ')->get()`

**Comment by jfelipeara** [comment]
that did not work, according to mysql docs the unit is ok

**Comment by robclancy** [comment]
Do a `->toSql()` to see the query it generates

**Comment by jfelipeara** [comment]
i did, this was the result:
``
General error: 1 no such column: HOUR (SQL: select * from "recharges" where "recharges"."sim_id" = 1 and "recharges"."sim_id" is not null and TIMESTAMPDIFF(HOUR, recharges.created_at, 2018-03-07 12:58:24) < 14)
``
seems ok to me

**Comment by jfelipeara** [comment]
i dont know why is taking the first parameter of the TIMESTAMPDIFF as a column

**Comment by robclancy** [comment]
Try sending `HOUR` in as a string just to check?

**Comment by sisve** [comment]
Could you do a `SELECT version()` and give us the exact version of mysql?

**Comment by jfelipeara** [comment]
@sisve 5.7.21-0ubuntu0.16.04.1 @robclancy when i pass HOUR as a string the error is ``General error: 1 no such function: TIMESTAMPDIFF``

**Comment by robclancy** [comment]
Tried running directly in the mysql CLI?

**Comment by jfelipeara** [comment]
yes, this works
``
select * from recharges where recharges.sim_id = 1 and recharges.sim_id is not null and ABS(TIMESTAMPDIFF(HOUR, recharges.created_at, '2018-03-07 13:21:48')) < 14
``
I don't know if maybe is related with the fact that i am doing a test in memory, but i think it shoud works anyway

**Comment by robclancy** [comment]
In memory? This was the first thing I thought of... you are running sqlite for tests?

**Comment by jfelipeara** [comment]
yes

**Comment by robclancy** [comment]
sqlite is not mysql, it doesn't support the same features

**Comment by jfelipeara** [comment]
i can't belive i didn't check that :sweat_smile: thank you very much!
