### ISSUE TITLE
Laravel 5.6.8: Routes doesn't work after update the framework to the last version

### ISSUE THREAD

**Issue by Nur777** [laravel/framework#23422]
- Laravel Version: 5.6.8
- PHP Version: 7.1.14
- Database Driver & Version: MySQL 5.7.21

### Description:
Hello to all! First, sorry for my English am not a native speaker.

Im simply run the `composer update` and the framework has been updated to the 5.6.8 version and i getting the following errors for the all routes:

http://joxi.ru/E2pqwJ4CBlpzaA - the screenshot of the stacktrace

`"Type error: Argument 1 passed to Illuminate\Routing\Router::sortMiddleware() must be an instance of Illuminate\Support\Collection, instance of Tightenco\Collect\Support\Collection given..."`

Before we use the Laravel 5.6.6 and its being works normally.

### Steps To Reproduce:
1. Simply update the Laravel Framework to the last version

**Comment by sisve** [comment]
This is not related to routes, but an incompatible package. #23420 is highly related to this issue.

**Comment by mpociot** [comment]
Please watch this issue: https://github.com/tightenco/collect/issues/92 
Hope it gets resolved soon

**Comment by Nur777** [comment]
Fixed in https://github.com/tightenco/collect/issues/92
:+1:
