### ISSUE TITLE
Right join on relations not working

### ISSUE THREAD

**Issue by panstromek** [laravel/framework#23438]
- Laravel Version: 5.4
- PHP Version: 5.6.31
- Database Driver & Version: MySQL - not important

### Description:
Right join on relation not working as expected and does inner join instead.

### Steps To Reproduce:
Consider this query to get number of upvotes on users comments for every post. If I have two comments on post and each gets 2 upvotes, one row in the result should be this post id and sum of 4 upvotes. I also want to have rows with posts where user didn't comment, with upvotes count 0, so I use right join. 

`User::comments()
  ->rightJoin('posts', 'posts.id', '=', 'comments.post_id' )
  ->groupBy('posts.id')
  ->selectRaw('posts.id as post_id, sum(comments.upvotes) as upvotes')
  ->get();
 `
But this is queried on relation so final query would end up with clause 'WHERE comments.user_id IS NOT NULL'  making it basically inner join.

Note: Query is nonsense and can be done differently, but it is just an example.

**Comment by jonpemby** [comment]
Just doing a minimal set up gets me seemingly ok results:

<img width="1364" alt="screenshot 2018-03-13 15 18 44" src="https://user-images.githubusercontent.com/8012318/37367605-e32d8b40-26d1-11e8-973d-6a8a5e9acf9c.png">

Can you elaborate a little bit more on what's not working for you? I can try to help.

**Comment by panstromek** [comment]
It doesn't return Comments with 0 upvotes from user but it should, because I used right join.

**Comment by jonpemby** [comment]
Ah yes, sorry, you did mention that in your OP. I'll play around with it a bit and see what's going on.

Hope you are doing well! 👍

**Comment by staudenmeir** [comment]
I don't see a way to fix this, since the `IS NOT NULL` constraint is automatically added to every relation query.

I would argue that a RIGHT JOIN on a relation doesn't make a lot of sense. The result would contain models with `NULL` attributes.

**Comment by panstromek** [comment]
I don't really understand why `IS NOT NULL` is added to every relation query. Relations are queried by related id, which is already unique. If related id is null, it can be checked in model before even executing query.
I know it doesn't really make much sense, I actually solved the problem differently, but since it is possible to call, I think it should work as expected. It took some time and frustration to realize that bug is not in my code. It would also make some of my queries easier to follow.

**Comment by staudenmeir** [comment]
Here's the explanation: #8033

Even without the `WHERE comments.user_id IS NOT NULL` constraint a RIGHT JOIN on a relation doesn't work.
The problem is the `WHERE comments.user_id=?` part. For a RIGHT JOIN this has to be an `ON` constraint:

    JOIN posts ON posts.id=comments.post_id AND comments.user_id=?

You would have to use something like this:

    Comment::rightJoin('posts', function($join) use($user) {
        $join->on('posts.id', '=', 'comments.post_id')
            ->where('comments.user_id', $user->id);
    })
    ->groupBy('posts.id')
    ->selectRaw('posts.id as post_id, sum(comments.upvotes) as upvotes')
    ->get();

**Comment by staudenmeir** [comment]
@laurencei Can be closed.
