### ISSUE TITLE
when i use rpc server , always appear server has gone away

### ISSUE THREAD

**Issue by xuzili1993** [laravel/framework#23435]
- Laravel Version: 5.4
- PHP Version: 7.1
- Database Driver & Version: mysql 5.6

### Description:
when i use rpc server , always appear server has gone away.

**Comment by sisve** [comment]
Do you really think that this issue has enough information for us to reproduce the problem and fix it?

**Comment by xuzili1993** [comment]
mysql server has gone away.
my rpc server based on swoole.
