### ISSUE TITLE
Eloquent Model events are not triggering if called directly from an Observer Class

### ISSUE THREAD

**Issue by sh4dw** [laravel/framework#23433]
- Laravel Version: 5.5.36
- PHP Version: 7.1.13
- Database Driver & Version:
mysql  Ver 14.14 Distrib 5.7.19, for osx10.12 (x86_64)

### Description:
When using observers to observe Eloquent events, model events are not being fired when called from within the observer itself.

If you use the `\Illuminate\Database\Eloquent\Concerns\HasEvents;` trait on the Observer class, everything works fine though. This should perhaps go with the documentation regarding Eloquent Events and Observers.

### Steps To Reproduce:
* Create two models, AModel and BModel
* Create an observer class for both models (AObserver and BObserver).
* Load both observers for the corresponding models in the Boot Method in AppServiceProvider.

1. Trigger a model event (eg `deleting`) on AModel from a Controller, and observe the `deleting` event in the AObserver (cool - works as expected).
2. From the `deleting` event (that was just fired) in the AObserver, trigger a new `deleting` event for BModel. Note the BObserver is not catching any events.
3. Validate (with Tinker or whatever one finds preferable) that the BObserver `deleting` event is actually firing when called directly (like we did with the AObserver `deleting` event).

AObserver (not triggering other observer) example:
```
<?php

namespace App\Observer;

use \App\Models\AModel;

class AObserver
{
    public function deleting(Organization $organization)
    {
        //example code for deletion of an organization with branches
        //delete organization branches one by one and call the model that triggers Eloquent events
        foreach ($organization->branches as $branch) {
           //initiliaze the Eloquent model with the first method
          //and call the delete method to trigger deletion events
          //this line does not work as expected as it does not trigger any observer events for the BModel
            \App\Models\BModel::find($branch->id)->first()->delete();
        }
    }
}
```

AObserver (triggering other observer as excepted) example:
```
<?php

namespace App\Observer;

use \App\Models\AModel;

class AObserver
{
    //use the HasEvents trait to fire the Eloquent events as expected
    use \Illuminate\Database\Eloquent\Concerns\HasEvents;
    
    public function deleting(Organization $organization)
    {
        //example code for deletion of an organization with branches
        //delete organization branches one by one and call the model that triggers Eloquent events
        foreach ($organization->branches as $branch) {
           //initiliaze the Eloquent model with the first method
          //and call the delete method to trigger deletion events
          //this line does not work as expected as it does not trigger any observer events for the BModel
            \App\Models\BModel::find($branch->id)->first()->delete();
        }
    }
}
```

**Comment by driesvints** [comment]
Hmm. I'm wondering if this is a bug or actual expected behavior.

**Comment by staudenmeir** [comment]
I can't reproduce this, it works for me without the `HasEvents` trait.

Can provide a repository with a complete example?

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.
