### ISSUE TITLE
Queue:works always fail after the first job

### ISSUE THREAD

**Issue by khushal1111** [laravel/framework#23430]
**Laravel Version: 5.5
PHP Version: 7.0**

I am facing below problem. Please help me to resolve this issue. I am dispatching multiple queues using below code using for loop:

`ProcessTask::dispatch($taskID); `

I checked queue table and Laravel sets all queues in table but when supervisor executes it, first queue works fine and remaining queues fail. When I manually run using **php artisan queue:listen**, it is working fine. 

Thanks in advance!

**Comment by sisve** [comment]
Sounds like you've done code changes that the supervisor-hosted queue worker hasn't picked up on. Try restarting it. If it still fails, tell us _how_ it fails, preferably with an exception or explanation.

**Comment by khushal1111** [comment]
It shows following error message:

```
**Message:** App\Jobs\ProcessTask has been attempted too many times or run too long. The job may have previously timed out.
**Code:** 0
**File:** /var/www/html/myapplication/vendor/laravel/framework/src/Illuminate/Queue/Worker.php
**Line:** 394
```

And Supervisor file is **laravel-worker.conf**

```
[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/myapplication/artisan queue:work --timeout=0 --tries=1
autostart=true
autorestart=true
user={{usernamehere}}
numprocs=8
redirect_stderr=true
stdout_logfile=/var/www/html/myapplication/worker.log
```

**Note:** When we run queue using **php artisan queue:listen**, it is working fine. Kindly help me to solve using supervisor.

Thanks in advance !

**Comment by sisve** [comment]
Does the log files contain any relevant errors?

This repository is for bug reporting. So far this is just general support. If you cannot find a reproducible bug, try asking on the forums or on Slack.
