### ISSUE TITLE
multi guard for authentication directive

### ISSUE THREAD

**Issue by afabros** [laravel/framework#23441]
if this is allowed:
->middleware(['auth:guard1,guard2']) 
is it possible to allow this in blade:
@guest(['guard1', 'guard2'])

**Comment by sisve** [comment]
This repository is for issues and bugs in the Laravel framework. Close this issue and ask on our forums or on Slack.

**Comment by afabros** [comment]
It's an issue because multi auth in routes is allowed but not in blade directives.

**Comment by tillkruss** [comment]
It's a feature request. Feel free to submit a PR.
