### ISSUE TITLE
[Resource API] whenPivotLoaded in conjunction with whenLoaded does not work as expected

### ISSUE THREAD

**Issue by lk77** [laravel/framework#23440]
Hello,

i'm using the resource API to return json information, i have two resources and one collection in the middle (mainResource -> subCollection -> subResource) , and i want to use whenPivotLoaded and whenLoaded functions.  

I have a collection of objects and i want to return pivot additionnal values when it exist, i also want to return default value when it does not exist. 

My problem is that i cant use whenPivotLoaded because if the pivot is not loaded, then the resource is not called (from collection perspective) so i can't set a default value. So i do not understand how this function should be used, and if there is something that i am missing ?

in mainResource :
```
'main_relation'   => SubResourceCollection::make($this->whenLoaded('mainRelation')),
```
in subCollection :
```
return parent::toArray($request);
```
in subResource :
```
return $this->whenPivotLoaded('pivot', function ()
            {
                return [$this->resource->attribute => $this->resource->pivot->pivot_attribute];
            }, 'default_value')
```

do i need to do a merge with an array of default values in subCollection ?

like:
```
       $default = array_fill_keys(SubModel::pluck('attribute')->all(), null);

        return array_merge($default, Arr::collapse(parent::toArray($request)));
```

thanks

**Comment by sisve** [comment]
This repository is for issues and bugs in the Laravel framework. Close this issue and ask on our forums or on Slack.

**Comment by lk77** [comment]
Yes, i know.
I don't see the point of asking on slack or forums, i don't need a technical solution to a problem because there is no problem at all, i just handle things manually, but i was especting a different behaviour from the framework, perhaps i misunderstood the functionnality. 
I have posted here because i wanted to know if it's something that can be implemented, i have a use case that don't seems to be handled by the framework, and wanted to know if others faces this problem too or if i'm alone.

For me it's a little awkward to do an array merge in my collection to handle defaut values, because whenLoaded and whenPivotLoaded won't work in this case, but perhaps it's the only way.
