### ISSUE TITLE
Radio button issue in edit blade template

### ISSUE THREAD

**Issue by arunrajiah** [laravel/framework#23448]
- Laravel Version: 5.5.37
- PHP Version: 7.1.3
- Database Driver & Version: mysql 5..7.17
- Laravel Collective: 5.5.3

### Description:
The database values are not set for radio button in edit form

### Steps To Reproduce:

- Add new field in form with radio button.

`<label class="radio-inline">
            {!! Form::radio('time_based', '1', true ) !!} Yes
        </label>
        <label class="radio-inline">
            {!! Form::radio('time_based', '0' ) !!} No
        </label>`
Note: time_based is a boolean

- Select any value in radio button and submit .
- Edit particular record in edit form
- The radio button will not show the selected value

**Comment by arunrajiah** [comment]
I have also found the workaround for this issue. If I set the values as integer instead of string it works.

`<label class="radio-inline"> {!! Form::radio('time_based', 1, true ) !!} Yes </label> <label class="radio-inline"> {!! Form::radio('time_based', 0 ) !!} No </label>`

**Comment by ProphitLabs** [comment]
I'll take a stab. Your field being a bool means it is expecting a 1 or 0 (true or false), which if you are passing a string to it, it will be null.  So this behavior is correct.

**Comment by arunrajiah** [comment]
Yes, it should be right. However I am facing this issue only after I update 5.5.32 to 5.5.37. Should I assume there was some bug fixed in the latest version?

**Comment by arunrajiah** [comment]
It looks like, something to do with laravel collectives https://github.com/LaravelCollective/html/issues/496

**Comment by jmarcher** [comment]
Can you close this issue, please?
This issue is not in any way related to Laravel.
