### ISSUE TITLE
Using $this when not in object context

### ISSUE THREAD

**Issue by emanci** [laravel/framework#23443]
- Laravel Version: 5.5.21
- PHP Version:7.1.8
- Database Driver & Version:

### Steps To Reproduce:

When we use macro for request validation

```php
\Illuminate\Http\Request::validate(['name' => 'required']);
```

output:

```php
FatalThrowableError {#508 ▼
  #message: "Using $this when not in object context"
  #code: 0
  #file: "/usr/local/var/www/site/vendor/laravel/framework/src/Illuminate/Foundation/Providers/FoundationServiceProvider.php"
  #line: 39
  #severity: E_ERROR
  trace: {▶}
}
```

Yes, I looked at the source code and found that Macroable uses the bind method of the Closure

```php
public static function __callStatic($method, $parameters)
{
      if (! static::hasMacro($method)) {
          throw new BadMethodCallException("Method {$method} does not exist.");
      }

      if (static::$macros[$method] instanceof Closure) {
          return call_user_func_array(Closure::bind(static::$macros[$method], null, static::class), $parameters);
      }

      return call_user_func_array(static::$macros[$method], $parameters);
}
```

However, in FoundationServiceProvider registerRequestValidate method using the $this, what should I do?

```php
public function registerRequestValidate()
{
      Request::macro('validate', function (array $rules, ...$params) {
          validator()->validate($this->all(), $rules, ...$params);

          return $this->only(collect($rules)->keys()->map(function ($rule) {
              return str_contains($rule, '.') ? explode('.', $rule)[0] : $rule;
          })->unique()->toArray());
      });
}
```
thanks

**Comment by TitasGailius** [comment]
That's expected behaviour.
You're using `$this` in your macro's callback and then statically calling `Request` which obviously fails. If you called it in an object context `$request->validate(...);` it should all work fine.

If for some reason you still want to be able to call it statically `Request::validate(...);`, the most simple solution is to simply replace `$this` to `request()`

**Comment by emanci** [comment]
@TitasGailius thank you！I know this behaviour. As you said, if you use `$request->validate(... )`, it's called the `__call` magic method of macroabe. I mean, we use `macro` to register a `validate` macro method, but we can't using static called?

Sure, we can using Facades: `\Illuminate\Support\Facades\Request::validate(['name' => 'required'])`

Well, I don't care about that either, and I don't usually use it that way. XD
