### ISSUE TITLE
 Declaration of Illuminate\Support\Carbon::__set_state($array) should be compatible with Carbon\Carbon::__set_state(array $state)

### ISSUE THREAD

**Issue by bastien-phi** [laravel/framework#23458]
- Laravel Version: latest
- PHP Version: 7.1.11

### Description:
Signature of `Carbon\Carbon::__set_state` changed in version 1.24.0, so `Illuminte\Support\Carbon::__set_state` should be updated

### Steps To Reproduce:
`composer create-project --prefer-dist laravel/laravel blog` fails in `@php artisan package:discover`

**Comment by acasar** [comment]
This commit is the source of the issue: https://github.com/briannesbitt/Carbon/commit/a05bed23de4c00040fe33cc6820c7e6be8d00c04

**Comment by Gummibeer** [comment]
fixed in https://github.com/laravel/framework/pull/23459

**Comment by mike-code** [comment]
lmao carbon guys broke it again with 1.24.1 xD

**Comment by waqasraza123** [comment]
yes its broken again.

**Comment by devcircus** [comment]
On the latest version (5.6.11) and everything seems fine. _set_state was completely removed from support\Carbon, so there's no possibility of incompatibility.
