### ISSUE TITLE
5.5.38 Carbon set_state array should be compatible

### ISSUE THREAD

**Issue by mbehnke** [laravel/framework#23467]
- Laravel Version: 5.5.38
- PHP Version: 7.1.8
- Database Driver & Version: MySQL

### Description:

cmd: php artisan down

In Carbon.php line 9:

  Declaration of Illuminate\Support\Carbon::__set_state(array $array) should be compatible with Carbon\Carbon::__set_state($state)

aquivilant to https://github.com/laravel/framework/commit/67d8a4b15ffdeeacc2c27efad05735a59dba1c44 ?

### Steps To Reproduce:

composer update
php artisan down

**Comment by edgarsn** [comment]
For now you can edit _/vendor/laravel/framework/src/Illuminate/Support/Carbon.php#55_ line, removing _array_ while they are dealing with this issue. Of course this is temporary solution.

**Comment by sburina** [comment]
v5.5.39 is out, I see the problem has been solved. :)

**Comment by mbehnke** [comment]
@sburina testing 5.5.39 at monday

**Comment by barayuda** [comment]
Hi guys, got this error today
![screenshot-localhost-8000-2018 03 12-11-22-44](https://user-images.githubusercontent.com/520463/37264341-c84f5708-25e7-11e8-8bd1-b429cb1a4a34.jpeg)

"DateTime::__construct(): Failed to parse time string (2018-03-12 03:18:52.-156944) at position 24 (9): Unexpected character"

Exception
DateTime::__construct(): Failed to parse time string (2018-03-12 03:18:52.-156944) at position 24 (9): Unexpected character
