### ISSUE TITLE
NotificationSent vs MessageSending Events

### ISSUE THREAD

**Issue by thamerbelfkihthamer** [laravel/framework#23477]
I am a little confused about MessageSending and NotificationSent events. in my application, I want to save any notification and mail send by the app inside a database Table.

for that, I create two event listeners createNotificationLogOnSending and createNotificationLogOnSendingMessage.

1) createNotificationLogOnSending is fired when success notification is sent which means Illuminate\Notifications\Events\NotificationSent event is fired by laravel notification system.

2) createNotificationLogOnSendingMessage is fired when Illuminate\Mail\Events\MessageSending fired by laravel system.

the problem here, in the 2 use cases Illuminate\Mail\Events\MessageSending is fired which means createNotificationLogOnSendingMessage listener is listen to both Illuminate\Notifications\Events\NotificationSent and Illuminate\Mail\Events\MessageSending

i want to make each listener fired for its event.

any solution for this problem or it's laravel bug ?

**Comment by tomhatzer** [comment]
These are 2 different things.

The Mail system is only sending e-mails.
From the docs:
```
Laravel provides a clean, simple API over the popular SwiftMailer library with drivers for SMTP, Mailgun, SparkPost, Amazon SES, PHP's mail function, and sendmail, allowing you to quickly get started sending mail through a local or cloud based service of your choice.
```

Notifications are the extended version of this, providing support for more different methods of notifications (eg. mail, sms, ...).
From the docs:
```
In addition to support for sending email, Laravel provides support for sending notifications across a variety of delivery channels, including mail, SMS (via Nexmo), and Slack. Notifications may also be stored in a database so they may be displayed in your web interface.
```

When you're sending mails using the notification system, indeed a mail will be sent and the MessageSending and MessageSent events will be triggered. But when you're sending an SMS, only the NotificationSent event will be triggered.

So you can see the notification system as something like the mother of the mail system.

I think you'll have to take one or the other, staying with notifications and using the NotificationSent event should be a good way to stay up2date in the future, as you have more control over every notification method that is available.

**Comment by thamerbelfkihthamer** [comment]
thank u, u clear my vision now. because I'm confused about all of this stuff. here we can see that laravel system fire MessageSending when NotificationSent is fired

**Comment by tomhatzer** [comment]
Great! I'm glad to hear that. Please feel free to close this issue if this topic is solved for you.
