### ISSUE TITLE
Database exception column length limit

### ISSUE THREAD

**Issue by maganius** [laravel/framework#23472]
Laravel Version: 5.6
    PHP Version: 7.2.1
    Database Driver & Version: MySQL 5.7.21

When a form post any input exceeding the limit string length bd, laravel throw an exception with code 22001.
Is possible avoid this type of exception and continue the app?

Error:
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'column' at row 1...

**Comment by 36864** [comment]
Sanitize your inputs before passing them into your database. That includes limiting the input length.

**Comment by maganius** [comment]
36864 thanks for your anwser, then its not possible avoid the exception.
You can recommend me a package to sanitize my inputs?

For now I put the max statements on my rule then my form validate it before submit.

**Comment by mamorunl** [comment]
I don't really think this is the place for questions like this. 

The correct way to handle this is off course to validate the input and then put in a try/catch around the database queries

**Comment by rs-sliske** [comment]
https://laravel.com/docs/5.6/validation
