### ISSUE TITLE
Memory Leak on db:seed using Model::create()

### ISSUE THREAD

**Issue by timothyasp** [laravel/framework#23486]
- Laravel Version: 5.6.9
- PHP Version: PHP 7.2.2-1+ubuntu16.04.1+deb.sury.org+1
- Database Driver & Version: MySQL 5.7.21-0ubuntu0.16.04.1 (Ubuntu)

### Description:
When running DB seed, using `Model::create()` in a loop causes what seems to be a memory leak.  I created a fresh Laravel project with a simple single text field Model and a Seeder that creates 1k records with the same string.  Memory usage consistently grows, measured using `memory_get_usage( false )`

I tried `DB::disableQueryLog()`, unsetting/setting variables to null, `	gc_collect_cycles()` and I have no debug libraries installed (referring to the solution recommended on #22797).  

https://d.pr/i/qTkYHb

### Steps To Reproduce:
* [Download the following fresh laravel project with the test model `Dummy` and the seeder](https://d.pr/f/tGRkNj)
* Migrate the DB
* run `php artisan db:seed --class=BigDatasetSeeder`

**Comment by staudenmeir** [comment]
This is a Homestead issue: https://github.com/laravel/homestead/issues/825

**Comment by browner12** [comment]
Correct, Homestead issue to be fixed in the next box.  Run your seeder with PHP7.1 for now.

This issue can be closed.

Thanks!

**Comment by timothyasp** [comment]
Phew! Excellent, thanks for the info. Closing.
