### ISSUE TITLE
error in adding routename to the group route

### ISSUE THREAD

**Issue by jasco-b** [laravel/framework#23494]
Illuminate\Routing\Router::loadRoutes(): Failed opening required 'Array' (include_path='.:/usr/share/php')

- Laravel Version: 5.6.*
- PHP Version: 7.1
- Database Driver & Version: mysql

### Description:
if i add route name for group route i have got this error
Illuminate\Routing\Router::loadRoutes(): Failed opening required 'Array' (include_path='.:/usr/share/php')

### Steps To Reproduce:
getting link via helper route('profile.show');

Route::namespace('profile')->name('profile.')->
    group(['prefix' => 'profile', 'middleware' => ['auth'], ], function () {
Route::get('/', ['action'=>'ProfileController@index', ])->name('show');
...

**Comment by tomhatzer** [comment]
The problem you have there is caused by your Route::get() call, as you provide an Array as second Parameter, though you should provide a String or a Closure.

Can you try it like this and tell me if that works for you?
```
Route::namespace('profile')
  ->name('profile.')
  ->group(['prefix' => 'profile', 'middleware' => ['auth']], function () {
    Route::get('/', 'ProfileController@index')->name('show');
});
```

Best wishes
Tom

**Comment by devcircus** [comment]
Read over the docs on route groups, this isn't right. Also, use 'as' on a group, to prefix the route names.

**Comment by tomhatzer** [comment]
Ok I'm sorry, the solution from above is wrong. You can not add an array with options for the group when specifying namespace or name beforehand.

This works in my local dev environment:
```
Route::namespace('profile')->name('profile.')->group(function() {
	Route::group(['prefix' => 'profile', 'middleware' => ['auth']], function() {
		Route::get('/', 'ProfileController@index')->name('show');
	});
});
```
