### ISSUE TITLE
ionic 3 getting undefined when retrieving user credentials during login

### ISSUE THREAD

**Issue by PattersonOfficial** [laravel/framework#23496]
This is the authentication controller codes
*********************************************************************
public function index()
    {
        //getting user token
        try{
            if(! $user = JWTAuth::parseToken()->authenticate())
            {
                return response()->json(['user_not_found'], 404);
            }
        }
        catch (Tymon\JWTAuth\Exceptions\TokenExpiredException $e)
        {
            return response()->json(['token_expired'], $e->getStatusCode());
        }
        catch (Tymon\JWTAuth\Exceptions\TokenInvalidException $e)
        {
            return response()->json(['token_invalid'], $e->getStatusCdoe());
        }
        catch (Tymon\JWTAuth\Exceptions\JWTException $e)
        {
            return response()->json(['token_absent'], $e->getStatusCode());
        }

        //Token is valid and user was found through sub claim
        return response()->json(compact('user'));
    }

public function store(Request $request)
    {
        //Storing select values for login purposes
        $credentials = $request->only('username', 'password');

        try {
            // verify the credentials and create a token for the user
            if (! $token = JWTAuth::attempt($credentials)) {
                return response()->json(['error' => 'invalid_credentials'], 401);
            }
        } catch (JWTException $e) {
            // something went wrong
            return response()->json(['error' => 'could not create token'], 500);
        }

        // if no errors are encountered we can return a JWT
        return response()->json(compact('token'));

    }

*******************************
And my API 
*******************************

Route::resource('authenticate', 'AuthenticateController');
Route::resource('user_details', 'UserDetailsController');
Route::resource('user', 'UserController');

***********************************************
Authentication Server from Ionic 3 
***********************************************
// fetch all resources from database
  getAllResource(url:string, token:string){
    return new Promise((resolve, reject) => {
      let headers = new HttpHeaders();
      this.http.get(apiUrl+url+"?token="+token, { headers: headers }).subscribe(response => {
        resolve(JSON.stringify(response));
      }, (err) => {
        reject(err);
      });
    });
  }

  // fetching out single resource using preferred id
  getSingleResource(url, id, token:string){
    return new Promise((resolve, reject) => {
      let headers = new HttpHeaders();
      this.http.get(apiUrl+url+"/"+id+"?token="+token, { headers: headers }).subscribe(response => {
        resolve(JSON.stringify(response));
      }, (err) => {
        reject(err);
      });
    });
  }

  // Fetching resource without a token
  getResourceNoToken(url, id){
    return new Promise((resolve, reject) => {
      let headers = new HttpHeaders();
      headers.append('Content-Type','application/json');
      headers.append('Access-Control-Allow-Origin', '*');
      this.http.get(apiUrl+url+"/"+id, { headers: headers }).subscribe(response => {
        resolve(JSON.stringify(response));
      }, (err) => {
        reject(err);
      });
    });
  }

  // Storing resource data into databse 
  storeResource(url,data,token){
    return new Promise((resolve, reject) => {
      let headers = new HttpHeaders();
      headers.append('Content-Type','application/json');
      headers.append('Access-Control-Allow-Origin', '*');
      this.http.post(apiUrl+url+"?token="+token,data, { headers: headers }).subscribe(response => {
        resolve(JSON.stringify(response));
      }, (err) => {
        reject(err);
      });
    });
  }

But I keep getting undefined response on the console

**Comment by wilburpowery** [comment]
I think you would get a response a lot quicker if you posted your question on a Laravel Related forum, since this is an implementation related issue and not an issue with the framework itself.
 
[Laracasts](https://laracasts.com/discuss) is a great option, the same for [https://laravel.io/](laravel.io)

**Comment by PattersonOfficial** [comment]
Thank you so much

**Comment by mace015** [comment]
@PattersonOfficial could you please close this issue? Thanks!
