### ISSUE TITLE
$user variable empty in authenticated method when using the AuthenticatesUsers trait

### ISSUE THREAD

**Issue by Astriel** [laravel/framework#23500]
- Laravel Version: 5.6.8
- PHP Version: 7.2.2
- Database Driver & Version: mysql-5.7-19

### Description:
When creating a controller for example called ApiLoginController, and creating an authenticated method using the AuthenticatesUsers, it seems it is impossible to access the $user variable passed usually in parameter. Same goes for Auth::user();

### Steps To Reproduce:
1. Installing an empty Laravel project
2. Installing Laravel Passport 
3. Installing Guzzlehttp/guzzle
4. Configurating the framework to make Laravel PassPort working
5. Creating a roule in api.php such as : 

`Route::post('login', 'Auth\ApiLoginController@authenticated');`

6. Then in your web.php route file : 

`Route::get('/', function () {
    $http = new GuzzleHttp\Client;

    $response = $http->post('http://hyvefivity.local/api/login', [
        'form_params' => [
            'grant_type'    => 'password',
            'client_id'     => '10',
            'client_secret' => 'eilJdC1Op3iA1yfCOJaAjYydnxdX67waTxuFPUKM',
            'username'      => 'my-email',
            'password'      => 'my-password',
        ],
]);

    return json_decode((string) $response->getBody(), true);
});`

7. Then finally creating that ApiLoginController.php for example like this : 

`namespace App\Http\Controllers\Auth;

use App\Models\User\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Route;
use Illuminate\Foundation\Auth\AuthenticatesUsers;

class ApiLoginController extends Controller
{
    use AuthenticatesUsers;

    protected function authenticated(Request $request, $user)
    {
    }
}`

Each time you'll try to fetch the / url, it will try to make a request to that method which will result in an ERROR 500 even if you don't put anything in the method, just because the $user parameter is not accepted.

I've created a topic on StackOverflow with all the problem description : [topic](https://stackoverflow.com/questions/49209754/laravel-passport-add-scopes-based-on-the-role-of-the-user)

**Comment by wilburpowery** [comment]
I'm not sure exactly what you are trying to achieve here. Api authentication is different from normal session authentication. The user is never really "logged in" to your application. In every request they have to send a token to verify their identity. 

I don't see this as a framework related issue. You might get help a lot faster if you post your question in a forum like Laracasts [here](https://laracasts.com/discuss)

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
