### ISSUE TITLE
App\Exceptions\Handler::renderForConsole() is ignored

### ISSUE THREAD

**Issue by thomasfw** [laravel/framework#23515]
- Laravel Version: 5.6.5
- PHP Version: 7.2.2
- Database Driver & Version: MySQL 5.7.21

### Description:

I'm unable to handle the rendering of Exceptions in the console using the [`App\Exceptions\Handler::renderForConsole()`](https://laravel.com/api/5.6/Illuminate/Foundation/Exceptions/Handler.html#method_renderForConsole) method. Is the handler included in the Collision package overriding my own App handler?

The expected/useful behaviour would be for the collision package to continue rendering any uncaught exceptions, whilst still allowing overrides for specific Exceptions in my  `App\Exceptions\Handler`, would it not?

### Steps To Reproduce:

I'm trying to catch all `\Illuminate\Validation\ValidationException` so I can output the validation errors in the console rather displaying the exception and stack trace.

**Anyways just add this `renderForConsole()` method in your `App\Exceptions\Handler`...**

```php
public function renderForConsole( $output, Exception $e )
{
    if ( $e instanceof \Illuminate\Validation\ValidationException )
    {
         dd( $e->errors() );
    }
}
```

**Add a test route in `app/routes/console.php`...**

```php
Artisan::command('testexception', function () 
{
    throw new \Illuminate\Validation\ValidationException( '' );
})->describe('Test exception handler');
```

**Run the command...**
```
php artisan testexception
```

**Get the same collision output in your console...**

**Comment by sisve** [comment]
What Collision package are you talking about? Would it be relevant to ask the author of that package instead of us?

**Comment by devcircus** [comment]
@sisve nunomaduro/collision comes via require-dev in the laravel installation now. It is the default console error handler.

**Comment by sisve** [comment]
Ah, I see, it's a require-dev for the laravel/laravel project.

Yes, that package overrides the renderForConsole method for most exceptions. Only those that implements the `Symfony\Component\Console\Exception\ExceptionInterface` interface will still have have the call to renderForConsole forwarded to your exception handler.

Source: https://github.com/nunomaduro/collision/blob/4e310ef9384f53ee8dda8736afb3cbaf320753a0/src/Adapters/Laravel/ExceptionHandler.php#L74-L88

**Comment by thomasfw** [comment]
Yeah... so that doesn't seem right to me?

**Comment by crynobone** [comment]
You can remove the package if we prefer to handle it differently.

**Comment by thomasfw** [comment]
I know I can remove the package. The point is that if it's included in the framework, it shouldn't be overriding my own Handler.

We should be able to handle specific Exceptions when required, with all others being passed on to Collision's ExceptionHandler to be rendered nicely.

**Comment by crynobone** [comment]
> We should be able to handle specific Exceptions when required, with all others being passed on to Collision's ExceptionHandler to be rendered nicely.

That just technically impossible, only the `bound` Exception Handler will be used for the request. If we include Collision directly to be used then it become a required dependencies instead of an optional dependencies as being done at the moment.
