### ISSUE TITLE
Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE)  in Passsword Reset

### ISSUE THREAD

**Issue by longestdrive** [laravel/framework#23537]
- Laravel Version: 5.5
- PHP Version:7.01
- Database Driver & Version:Mysql 5.6

### Description:
On my VPS I have PHP version 7.0 installed. When A used clicks for a password reset I get this error
```
Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) 
```
This relates to line 24 of `RedirectIfAuthenticated.php`

Researching I understand this is an issue with Mail and has been solved by others by upgrading to php7.1

I don't have that option on my server and am forced to use php7.0 which this version of laravel 5.5 is meant to support

Can you advised how to overcome this issue please

### Steps To Reproduce:
1. Default Laravel authentication being used
2. User clicks reset passowrd, completes form and then submits
3. Error occurs

**Comment by tomhatzer** [comment]
@longestdrive Are you sure that's the right file? On line 24 of the RedirectIfAuthenticated.php is no questionmark...

Have a look at the original file here: https://github.com/laravel/laravel/blob/31fce5c503d872c5389ffbbae59310413f9f9966/app/Http/Middleware/RedirectIfAuthenticated.php#L24

I just tried to reproduce this and everything worked as expected, without any error.

What does your RedirectIfAuthenticated.php file look like?

**Comment by devcircus** [comment]
That's not a core file anyway. Make the changes necessary to match the file that @tomhatzer shared above.

**Comment by TheDeadCode** [comment]
I'd probably make sure you _truly_ have PHP 7.0 installed.

Make a dummy file and put `<?php phpinfo();` in it. Look for the PHP version and make sure 7.0 is really there.

**Comment by browner12** [comment]
Welcome to Laravel! We are glad to have you as part of the community.

Unfortunately GitHub is not an appropriate platform for general application issues. This is only for issues/bugs with the framework code itself.

Please close your issue, and instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

Laravel Slack (https://larachat.co/)
Laravel.io Forum (https://laravel.io/forum)
Laracasts Forum (https://laracasts.com/discuss)
StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks!

**Comment by mutiemule** [comment]
The real issue is some dependencies are using a higher PHP version other than 7.0.

You have two choices, to upgrade to PHP7.1 or instruct composer to download only dependencies which are compatible with PHP7.0 by doing the following:
For PHP7.0 only

If your server doesn't have PHP7.1 and above and you are only restricted to use PHP7.0 
do as below:

1. Delete vendor folder
2. Delete composer.lock file
3. Add this to composer.json file under `config`

        ```
"platform": {
           "php": "7.0.0"
        }
```

As well, ensure PHP version under `require` is set to 7.0.0 as shown below in `config.platform.php`:

        ```
"config": {
            "platform": {
                "php": "7.0.0"
            }
         }
```

4. Run composer install using CMD

This now will make sure that only dependencies compatible with php7.0 are installed.

**Comment by anujs-webonise** [comment]
PHP 7.1 will work

**Comment by gopal-g** [comment]
create a simple test.php page in your public folder

put phpinfo() in it and then hit test.php in your browser

Sometimes the php version being used by the webserver can be a different version to the command line
