### ISSUE TITLE
5.6: You must run php artisan config:clear on a new install

### ISSUE THREAD

**Issue by bhartvigsen** [laravel/framework#23540]
- Laravel Version: 5.6
- PHP Version: PHP 7.2.2-3+ubuntu16.04.1+deb.sury.org+1
- Database Driver & Version: MySQL 14.14

### Description: With a new 5.6 install, database config in database.php is not picked up until user runs php artisan config:clear

This just started happening after I set up a new 5.6 install. This has not been encountered in previous Laravel versions. I would suggest that the requirement at least be in the docs if it can't simply be remvoved.

### Steps To Reproduce:
- Install Laravel 5.6
- Configure a database
- Attempt to do anything with the database, you'll see this error:
Forge – SQLSTATE[HY000] [1045] Access denied for user ”@’localhost’ (using password: NO)

Note: when this occurs, there are NO forge entries in .env or config/database.php

after running php artisan config:clear the issue goes away.

**Comment by mace015** [comment]
How do you setup a new project?
Not having this issue with the composer create-project command:
`composer create-project --prefer-dist laravel/laravel test-app`

**Comment by browner12** [comment]
you mention this is a new project, but then you talk about Forge.  Are you referring to deploying a new project to Forge for the first time?

**Comment by bhartvigsen** [comment]
No, I know nothing about what Forge is.

More detailed steps to replicate:

- Run composer create-project --prefer-dist laravel/laravel test-app
- Setup NGINX
- set encryption key
- Chmod storage to 777
- Add a mysql database in config/database.php
- Add a plain, basic model to test:
```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;
use DB;

class Job extends Model {
        protected $table = 'jobs';
        protected $guarded = [];
}
```

**Comment by bhartvigsen** [comment]
Closing this, I started detailing the list of steps to reproduce and it no longer happens. This has occurred twice in the last month so I'm sure there WAS a bug in the framework but it appears it's been patched. And no, I have no idea what Laravel Forge even is.
