### ISSUE TITLE
Replace relative references of functions in function calls with absolute references.

### ISSUE THREAD

**Issue by vpratfr** [laravel/framework#23545]
Hi,

A [famous PHPStorm plugin](https://plugins.jetbrains.com/plugin/7622-php-inspections-ea-extended-) recently hinted that I could get some performance benefits very easily by replacing `is_array` by `\is_array` (and same goes for all global PHP functions which can be fully qualified).

I was wondering if Laravel was using this tip, and it looks like it is not. A quick look at Symfony shows that they are taking care of this in their codebase: https://github.com/symfony/symfony/commit/bccab35aa2c0a6500281083414346a0417c234ac

[PHPStorm can do that automatically](https://blog.jetbrains.com/phpstorm/2017/01/phpstorm-2017-1-eap-171-2455/) 

See [the original article](https://veewee.github.io/blog/optimizing-php-performance-by-fq-function-calls/)

See [this tool to do that on the existing codebase](https://github.com/Roave/FunctionFQNReplacer)

May I submit a few PRs about that? Do you care about it?

**Comment by sisve** [comment]
This sounds like something that should be discussed at https://github.com/laravel/ideas.

I would like to point out that even if the article would like to call it abuse, it's still a valid use case to build namespaced functions for different nefarious and non-nefarious purposes. This can be used to override the global helpers during testing, as one example. So if this should be done, target the next release (5.7 at the time of writing), and not the current one, as it can have effects that would be considered breaking changes.

> This handy "feature" is frequently (ab)used during testing. A good example for this (ab)use is overwriting the functions to read from or write to the filesystem. In the source files, you can for example use the fopen() function. During the tests, you can mock this function by placing it in the namespace of the class that you are testing. An example of this can be found in the local adapter of flysystem.

**Comment by browner12** [comment]
Definitely looks very interesting. I would like to see additional benchmarks on our other supported versions of PHP as well, and maybe some real world benchmarks of common Laravel applications, before we throw ourselves into this.

Would we have a way to replicate this (ab)use for people who are using it in their testing?

TIL this is called "monkey-patching".

**Comment by vpratfr** [comment]
Any "official" comment from the laravel team would have bien appreciated on top of the simple "close".

Worth digging further? Just live without this optimisation?

**Comment by tillkruss** [comment]
@vpratfr Sorry, this repo is only for bugs. Please discuss this in internals.

On a personal note: I'd love to see a PR for this to v5.7, I'm sure we could squeeze out a couple of ns in heavily used components like routing, validation and eloquent.

**Comment by vpratfr** [comment]
Ok. Perfect. That comment is what I expected: what to do next :) I'll try to follow up with a thread in internals as well as a PR on a few components.

**Comment by tillkruss** [comment]
@vpratfr: I'd see if Blackfire can give you any insights into what's called heaps.
