### ISSUE TITLE
Validation Array of File Inputs

### ISSUE THREAD

**Issue by gravataLonga** [laravel/framework#23553]
- Laravel Version: 5.6 but also can reproduced it on 5.5
- PHP Version: 7.1
- Database Driver & Version: Not revelant.

### Description:

I'm trying to validate if file of images was provide, but is an array. It can't validate and pass along without assert if is filled.  

### Steps To Reproduce:   

I have prepared an repository to test, you can see this in action here:  
https://github.com/gravataLonga/laravel-issue-validation/blob/master/tests/Feature/MultipleImageUploadTest.php  

The validation rules is set properly, i think.  

https://github.com/gravataLonga/laravel-issue-validation/blob/master/app/Http/Controllers/HomeController.php  

If can confirm is a bug, i can fixed if you like.

**Comment by tillkruss** [comment]
Feel free to submit a PR.

**Comment by gravataLonga** [comment]
I could try to resolve if i know where to start with this "workflow of PR". 😄 I will do my best 💪wish me luck. 🍀

**Comment by gravataLonga** [comment]
@sdalmeida Hi, nop i'm not currently working to fix. Sorry, but i came with no time left to work on. But let me know if you need some help fixing, may be i could help you with "Pair-programming" mentality.

**Comment by GabrielaSaldana** [comment]
Hi, I have an application runig on Laravel 5.6 and one of the form elements is a multiple file input , currently I'm not using Laravel Collective for it, instead I'm using the old way: , <input type="file" name="f1[ ]" ...> and for the validator in server side I found that when you refer the name of the request element itself like 'f1' it will not make sure you are uploading each element of the array but if you put in the validator 'f1.*' then it would, so you need to add both like this:

$validator = Validator::make($request->all(), [
    "f1"    => "required|array|min:3",
    "f1.*"  => "required|string|distinct|min:3",
]);

**Comment by gravataLonga** [comment]
Yeah, later on i realize that. Seem to me like duplicate code, it would be nice rather than make two itens on array, put only one? 

Best Regards,

**Comment by driesvints** [comment]
@GabrielaSaldana @gravataLonga is this still an issue for you in the latest version of the framework?

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.
