### ISSUE TITLE
Eager loading nested relation with if statement produces exception.

### ISSUE THREAD

**Issue by mace015** [laravel/framework#23552]
- Laravel Version: 5.5.39
- PHP Version: 7.2.3
- Database Driver & Version: MariaDB 10.1.31

### Description:
When eager loading a nested relationship (`->load(['relation.relation'])`) with an if statement in the relation (see example below) an exception is thrown: `Call to a member function addEagerConstraints() on null`.

### Steps To Reproduce:

1) Create 3 models: `A.php`, `B.php` and `C.php`.
2) Create the following relations:
    'A' hasOne 'B'
    'B' hasMany 'C'
3) In the relation of B => C, place an if statement in the relation method:
```
public function c(){
    if (1 == 1) {
        return $this->hasMany('C');
    } else {
        return $this->hasMany('C');
    }
}
```
4) From a controller, retrieve 1 instance of `A` and then try to eager load both `B` and `C`: `$a->load(['b', 'b.c'])`

This results in: `Call to a member function addEagerConstraints() on null`.

I am positive the relation works, when calling the relation as property without eager loading (`$a->b->c`) a collection is returned.

**Comment by staudenmeir** [comment]
Can you post your relation's actual code? Just having an if statement doesn't cause problems.
