### ISSUE TITLE
Job events in AppServiceProvider not working

### ISSUE THREAD

**Issue by jilster** [laravel/framework#23557]
- Laravel Version: 5.6.12
- PHP Version: 7.2.2
- Database Driver & Version: DynamoDB

### Description:
I am trying to log some info about Jobs in the AppServiceProvider, following the docs: https://laravel.com/docs/master/queues#job-events, but i get the following error:

`Type error: Argument 1 passed to App\Providers\AppServiceProvider::App\Providers\{closure}() must be an instance of App\Providers\JobProcessing, instance of Illuminate\Queue\Events\JobProcessing given, called in /home/vagrant/Code/jilster-core/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php on line 360`

I don't know if it is relevant, but i am using Laravel Horizon (1.2.3)

This is my AppServiceProvider:

```
<?php

namespace App\Providers;

use Log;
use Illuminate\Support\Facades\Queue;
use Illuminate\Support\ServiceProvider;
use Illuminate\Queue\Events\JobProcessing;
use Illuminate\Queue\Events\JobProcessed;
use Illuminate\Queue\Events\JobFailed;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Queue::before(function (JobProcessing $event) {
            Log::info($event->job->resolveName());
        });

        Queue::after(function (JobProcessed $event) {
            Log::notice($event->job->resolveName());
        });

        Queue::failing(function (JobFailed $event) {
            Log::error($event->job->resolveName());
        });
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }
}
```

**Comment by jilster** [comment]
Disregard that, it started working after a vagrant reload --provision

**Comment by nabizada-abida** [comment]
I have the same issue, it is not working. So I have to restart the Laravel supervisor (queue:work) before jobs even I do not change anything in codes.
