### ISSUE TITLE
IIS 8 error

### ISSUE THREAD

**Issue by rasstislav-zxn** [laravel/framework#23555]
Hello,

after fresh install of laravel on IIS 8 I have got error displayed below:

<img width="960" alt="iis8-error" src="https://user-images.githubusercontent.com/31690049/37462223-7991ff6e-2851-11e8-9f41-c9eb36119b5b.png">

My configuration:
- Laravel Version: 5.6.12
- PHP Version: 7.1.7
- IIS 8

What am I supposed to do to fix this problem?

**Comment by jmarcher** [comment]
This section is meant to be only for bugs, if you are having any problem please visit Laracast's forums.

**Comment by browner12** [comment]
Welcome to Laravel! We are glad to have you as part of the community.

Unfortunately GitHub is not an appropriate platform for general application issues. This is only for issues/bugs with the framework code itself.

Please close your issue, and instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

Laravel Slack (https://larachat.co/)
Laravel.io Forum (https://laravel.io/forum)
Laracasts Forum (https://laracasts.com/discuss)
StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks!
