### ISSUE TITLE
(Laravel 5.5.39) Eloquent's groupBy breaks queries

### ISSUE THREAD

**Issue by KiddoKenshin** [laravel/framework#23565]
- Laravel Version: 5.5.39
- PHP Version: 7.2.1
- Database Driver & Version: MySQL 5.6.10 (Aurora)

### Description:
By using Eloquent's groupBy(),
all values are not properly bind as SQL query, and it produces SQL Syntax error.

### Steps To Reproduce:
```php
// Produces error... (Works in 5.5.35)
TestModel::whereIn('status', ['active', 'deleted'])
  ->where('updated_at', '<=', '2018-04-01 00:00:00')
  ->groupBy('creator_id')
  ->get();

// Works!
TestModel::whereIn('status', ['active', 'deleted'])
  ->where('updated_at', '<=', '2018-04-01 00:00:00')
//   ->groupBy('creator_id')
  ->get();
```
However, the same code works in 5.5.35, without setting database setting's "strict" to false,
where 5.5.39 requires 'strict' = 'false' in order to avoid the error.

**Comment by sisve** [comment]
Do you happen to know which exact version of Laravel that breaks the functionality? You can try installing specific versions by using `composer require laravel/framework:5.5.35`, and increasing it until it fails.

Can you provide us with the exception and the invalid sql?

Everytime I see someone using mysql and having troubles with group by I link them https://www.psce.com/en/blog/2012/05/15/mysql-mistakes-do-you-use-group-by-correctly/. It doesn't have to be relevant to this specific case.

**Comment by rs-sliske** [comment]
what exactly is the error you are getting? because this looks like an incorrect use of group by, which gives an error dependent on mysql version/config.

https://stackoverflow.com/questions/34115174/error-related-to-only-full-group-by-when-executing-a-query-in-mysql/38551525#38551525

**Comment by KiddoKenshin** [comment]
Thank you for the feedback.
I tried to revert back to 5.5.35, and I got the same error right now.
I think it's an issue on another dependencies as I start getting this error upon updating via composer.

However, like @sisve and @rs-sliske addressed,
it's more like an issue on my side using groupBy incorrectly.
Thank you for the feedback, and sorry for causing trouble ><
