### ISSUE TITLE
Bad format for date columns in jobs table

### ISSUE THREAD

**Issue by squiaios** [laravel/framework#23571]
https://github.com/laravel/framework/blob/d64e500037a198e804ad83d3adeee6708cf36659/src/Illuminate/Queue/Console/stubs/jobs.stub#L21

is it normal that it is unsignedInteger used instead of timestamps for reserved_at, available_at and created_at columns ?

**Comment by sisve** [comment]
It stores unix timestamps which are integers. So ... yes?

**Comment by iPhoneHungry** [comment]
Maybe speed but i would lean more towards Database portability
-     Some queue drivers (e.g., Redis, database, SQS) store job metadata consistently.
-     Using INT avoids DB-specific quirks (e.g., time zones, date formats).
