### ISSUE TITLE
Validation on Date passes invalid dates

### ISSUE THREAD

**Issue by joveice** [laravel/framework#23574]
- Laravel Version: 5.6.3
- PHP Version: 7.2.2-3 / 7.1.7
- Database Driver & Version: MariaDB 10.2.6

### Description:
Validation date passes invalid dates

### Steps To Reproduce:
```
Validator::make($data,
            [
                'date' => 'required|date',
            ]
          );
```

give it a date of etc 1970-8n-10 and it passes it, and the database says nope: error 1292

**Comment by joveice** [comment]
To be fair
PHP:
`strtotime('1970-8n-10')`
This works, so it might be more of a PHP issue?

**Comment by ntzm** [comment]
The `date` validations means that PHP can parse it, not your database driver.

**Comment by joveice** [comment]
So I will need to validate the validated data? this seems messy.
