### ISSUE TITLE
Feature Proposal: SuperNumber

### ISSUE THREAD

**Issue by degecko** [laravel/framework#23582]
I'm working on a class which takes a number and objectifies it so it can be used properly in an OOP environment.

Just to illustrate the idea, here are some examples which would become useful in real world applications:

```
$number = new SuperNumber(12000);
$someValue = 1e5;
$number->percentOf($someValue); // Returns 12, because 12000 is 12% of 100,000.

$number = new SuperNumber(15);
$someValue = 120;
$number->percentFrom($someValue); // Return 18, because 15% of 120 is 18.
```

It supports all the basic PHP math functions:

```
['abs', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atanh', 'ceil', 'cos', 'cosh', 'deg2rad', 'exp',
'expm1', 'floor', 'fmod', 'log10', 'log1p', 'log', 'min', 'max', 'rad2deg', 'round', 'sin', 'sinh',
'sqrt', 'tan', 'tanh', 'base_convert', 'bindec', 'decbin', 'dechex', 'decoct', 'hexdec', 'octdec',]

// E.g.:
$number = new SuperNumber(64);
$number->sqrt(); // Returns 8.
```

It also supports some additional functions, like add(), subtract(), multiply(), divide(), mod(), format() which is an alias for number_format, as well as a custom mutator to do whatever you want to the current value with a callable function.

I plan on adding more useful stuff.

And they're also chainable, which will look excellent in views for quick calculations.

This is a real world example from one of the apps that I'm working on.

I turned this:

`number_format($nextBonus->points - user()->pointsEarned, 0)`

Into this:

`$nextBonus->points->sub(user()->pointsEarned)->format()`

And this:

`number_format(user()->pointsEarned / $nextBonus->points * 100, 0)`

Into this:

`user()->pointsEarned->percentOf($nextBonus->points)`

Simply by initializing the SuperNumber class via the models' attribute getters.

```
class User extends Model
{
    // ...

    public function getPointsEarnedAttribute ($value) {
        return new SuperNumber((int) $value);
    }
}
```

Conclusion
--

I think this will be a great addition to Laravel's `$casts` model functionality, so I was thinking to create a pull request with this new class to be applied on a new casting type. But first, I'd like to see what you guys think of the idea. Maybe it's simply too much for just some silly numbers? Maybe it'll add to the load time?

I'd love to hear your oppinions on this.

**Comment by staudenmeir** [comment]
Please use the https://github.com/laravel/ideas repository for proposals.

**Comment by GrahamCampbell** [comment]
Yes, please sumit proposals to the proposals repo, instead of the bug tracker. Thank you. ;)
