### ISSUE TITLE
Decimal value is not stored in Postgresql

### ISSUE THREAD

**Issue by Kompas** [laravel/framework#23598]
- Laravel Version: 5.6.12
- PHP Version: 7.2.3
- Database Driver & Version: (pgsql) Postgresql 10.3

### Description:
Using Laravel 5.6 and Postgresql 10.3 I am not able to store a decimal value through Laravel. I can however store the value directly through SQL with PgAdmin.

### Steps To Reproduce:
The migration file:

```
        Schema::create('downloads', function (Blueprint $table) {
            $table->decimal('download_time', 4, 3)->nullable(true); 
        });
```

As expected the column is created as _download_time_ with the _numeric(4,3)_ type.

Tinker does not give any error when inserting / updating the column _download_time_ with value 0.611. When I check my table the value is not updated.

```
            Download::find(1)->update([
              'download_time' => 0.611
            ]);
```

While writing SQL in PgAdmin the value is stored correctly:

```
    update downloads
    set download_time = 0.611
    where id = 1
```

**Comment by staudenmeir** [comment]
Did you add `download_time` to `Download::$fillable`?

**Comment by Kompas** [comment]
@staudenmeir I am going to cry in the corner of the room and hit myself with a stick. Thank you.
