### ISSUE TITLE
[5.6] withTimestamps() never applied to custom pivot model

### ISSUE THREAD

**Issue by stayallive** [laravel/framework#23601]
- Laravel Version: 5.6.12
- PHP Version: 7.2.0
- Database Driver & Version: MySQL 5.7.20

### Description:

When calling `->withTimestamps()` on a belongs to many relation it is never applied to a custom pivot model registered with `->using()`.

### Steps To Reproduce:

Create a model for example `Domains` that belongs to many to `Certificates` using the following relation method:

```php
use Illuminate\Database\Eloquent\Model;

class Domain extends Model 
{
    public function certificates()
    {
        return $this->belongsToMany(Certificate::class)
                    ->using(CertificateDomain::class)
                    ->withTimestamps();
    }
}
```

_The pivot model was reduced to the bare minimum to rule out a user error:_

```php
use Illuminate\Database\Eloquent\Relations\Pivot;

class CertificateDomain extends Pivot
{
}
````

Observe that when updating the pivot model via the `updated_at` will not be updated:

```php
$certificate = Domain::find(1)->certificates()->first();
$certificate->pivot->some_column = 'something';
$certificate->pivot->save();
```

When confirming the `timestamps` attribute on the model is `true` we see it's not:

```php
$certificate = Domain::find(1)->certificates()->first();
dd($certificate->pivot->timestamps); // false
```

When defining the relationship like this:

```php
use Illuminate\Database\Eloquent\Model;

class Domain extends Model 
{
    public function certificates()
    {
        return $this->belongsToMany(Certificate::class)
                    //->using(CertificateDomain::class)
                    ->withTimestamps();
    }
}
```

The `updated_at` column will be updated when the pivot model is saved.

**Comment by cetetesoft** [comment]
I've had the same issue. Apparently the custom pivot is created using `Pivot::fromAttributes()` with an empty array as `$attributes,` so `$instance->timestamps` is always set to `false`.

**Comment by luchaos** [comment]
i took me ages to find out but came to the same conclusion:
https://github.com/laravel/framework/commit/a73812999ad2bcb5926cbdd296c723d9635e304c#r28662738
