### ISSUE TITLE
Route::apiResource() doesn't accept arrays

### ISSUE THREAD

**Issue by MichaelBelgium** [laravel/framework#23600]
- Laravel Version: 5.6.11
- PHP Version: 7.1.9
- Database Driver & Version: mysql (unknown version)

### Description: 
So I noticed this today and I assume it's a doc mistake, but who knows its actually a bug. When creating multiple resource controllers, the [docs say](https://laravel.com/docs/5.6/controllers#resource-controllers)

> You may register many API resource controllers at once by passing an array to the  apiResources method:
>```
> Route::apiResources([
>    'photos' => 'PhotoController',
>    'posts' => 'PostController'
>]);
>```

But for me it's saying 

>In Router.php line 329:

> Type error: Too few arguments to function Illuminate\Routing\Router::apiResource(), 1 passed in [...]\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php on line 221 and at least 2 expected

### Steps To Reproduce:

* Create one or more resource controllers
Example: `php artisan make:controller Api/FooController --resource --api`
* Add a `Route::apiResource` and pass all the made controllers in an array to that method

Example:
```
Route::apiResource([
	'foo' => 'Api\Foocontroller'
]);
```

* Execute `php artisan route:list` and see the error

**Comment by staudenmeir** [comment]
You have a typo: `apiResource()` → `apiResources()`

**Comment by MichaelBelgium** [comment]
Oh gosh, ok thanks for pointing out @staudenmeir 🤦‍♂️

**Comment by ToniMaunde** [comment]
I was missing a 's' as well. Thanks :laughing:

**Comment by josendulip** [comment]
But why in the documentation of laravel is written without "s"?
Route::resource('photos.comments', 'PhotoCommentController');

**Comment by staudenmeir** [comment]
@josendulip Both methods exist: https://laravel.com/docs/controllers#restful-partial-resource-routes

**Comment by ridwanhoque** [comment]
> You have a typo: `apiResource()` → `apiResources()`

it works for me
