### ISSUE TITLE
Laravel 5.1 uses insecure CSPRNG, new release needed

### ISSUE THREAD

**Issue by hackel** [laravel/framework#23611]
- Laravel Version: 5.1.46
- PHP Version: 7.2.3

### Description:
The current release of Laravel 5.1 (5.1.46) depends on paragonie/random_compat:~1.4.  This produces the following security notice from sensiolabs/security-checker:
```
paragonie/random_compat (v1.4.2)
--------------------------------
 * Uses insecure CSPRNG (openssl_random_pseudo_bytes())
   https://github.com/paragonie/random_compat/issues/96
```
This was already fixed way back in April in 93074f4 where paragonie/random_compat:~2.0 is allowed, it just needs to be released.  Since this is a security issue, and such a minor one at that, I hope it can get rolled out before it goes EOL in June.

**Comment by dpde** [comment]
From the [README.md](https://github.com/laravel/framework/blob/5.6/README.md#security-vulnerabilities) file:

> If you discover a security vulnerability within Laravel, please send an e-mail to Taylor Otwell via taylor@laravel.com. All security vulnerabilities will be promptly addressed.

**Comment by Upperfoot** [comment]
@dpde This ticket is more so about a security notice about a third party package, not a security vulnerability inherent in the framework.

**Comment by browner12** [comment]
Laravel 5.1 was released on June 9th, 2015 as an LTS, so security fixes are provided for 3 years.

It looks like this [PR](https://github.com/laravel/framework/pull/18841) added the ability to install version 2 of `random_compat`

So I'm thinking upgrading to v2 will solve your problem.

**Comment by hackel** [comment]
@browner12 Yes, that is exactly what I said, however the PR *still* has not been released.  I had to resort to pulling a raw commit to fix this, which is pretty bad.  That's why I was hoping a 5.1.47 release could be made before time is up.
    `  "laravel/framework": "5.1.x-dev#93074f403ea0ad3676aa9422f7e6ce35f3fd2c37",`

@tillkruss Any explanation for closing this issue, while a supported LTS release remains with such a security vulnerability?  The issue is clearly not fixed.  Is there a release plan?

**Comment by vlakoff** [comment]
How about a new tag for 5.1 branch? I know this branch is EOL, but it wouldn't hurt, and there are a few fixes, notably security, since latest 5.1.46 (March 2017)...

**Comment by laurencei** [comment]
Ultimately `5.1` is not supported anymore. You should consider upgrading to `5.5 LTS` which has other security fixes from recent issues (such as some XSS etc).

Alternatively you are able to pull in the latest 5.1 using the method @hackel describes above.

**Comment by laurencei** [comment]
Laravel `5.1` no longer receives security updates (it is older than 3 years) - https://laravel.com/docs/5.5/releases#support-policy

Ultimately you should consider upgrading to Laravel 5.5 for even more security updates (including some recent XSS language fixes).

Alternatively you can manually pull in the latest version of 5.1 as described by @hackel
