### ISSUE TITLE
Controller in wrong namespace when registration of route is in different namespace

### ISSUE THREAD

**Issue by tweichart** [laravel/framework#23614]
- Laravel Version: 5.6.12
- PHP Version: 7.2
- Database Driver & Version: -

### Description:
When using the namespace functionality for registering routes in external packages (e.g. loaded via composer) it fails to look for the controller at the right place.

### Steps To Reproduce:
Example project: https://github.com/tweichart/laravel-namespace-example

Here a new package that normally exists in the vendor folder is included in the app/External folder (for the sake of this example, just to keep everything in one project). This just registers a new route via it's facade, which **should result in the controller in this folder to be called**.
This is a fresh and basic laravel project. Changes are as follows:

* composer.json (ln30): registered the namespace of the external package
* routes/web.php: define a default route in the namespace 'Internal'. Afterwards register the second route via the method provided by the external package.
* app/External/Facades/External.php: Just the default facade
* app/External/Services/External.php: Register the second route in a different namespace

So the expected result would be, that the external controller is included via it's own namespace `ExternalApp\Controllers\External\Controller@index`. This is also the place to look for the controller.

The result though is, that the controller is expected to be in the same namespace as the project it's included in, meaning `App\Http\Controllers\ExternalApp\Routes\External\Controller@index`. This is (as far as I can see it) not an expected behaviour. It also does not matter in which way the route is being included (with or without the leading backslash), the basic namespace is always there as a prefix. The leading backslash having no effect is due to the laravel core trimming the path that's being included here.

For fixing this behaviour I've already created a [PR](https://github.com/laravel/framework/pull/23572). Here the trim will not be executed when the namespace is added with a leading backslash. It just modifies this case, most of the route registrations are not touched by this change.

As a sidenote, this though does not seem to be testable, as this behaviour does not seem to be present when using the testcases. I've tried to reproduce it in the RoutingRouteTest without a facade, there the namespace is not prepended, due to the fact that the method being changed in the PR is never called. This though is a different topic i guess...

**Comment by mstnorris** [comment]
I am seeing the same issue. Recent update to Laravel 5.6 from 5.5 and now my controllers in a custom namespace aren't found.

**Comment by driesvints** [comment]
I think the entire premise of doing it in the app with the way you've done the namespaces inside the `app` folder is wrong. It's probably best to map a different route group in your RouteServiceProvider for this.
