### ISSUE TITLE
React preset outputs undefined.js

### ISSUE THREAD

**Issue by zlokomatic** [laravel/framework#23617]
- Laravel Version: 5.6.12
- PHP Version: 7.2.3-1

### Description:
After creating a new project and switching to the react preset, webpack outputs a file "undefined.js" along the app.js and app.css

```
Asset     Size  Chunks                    Chunk Names
  /js/app.js  1.69 MB       0  [emitted]  [big]  /js/app
undefined.js  2.64 kB       1  [emitted]         undefined
/css/app.css   187 kB    1, 1  [emitted]         undefined, undefined
```

### Steps To Reproduce:
```
composer create-project --prefer-dist laravel/laravel blog
cd blog
php artisan preset react
npm install && npm run dev
```

**Comment by devcircus** [comment]
Can confirm. 

May be good to post on [Laravel Mix repo](https://github.com/JeffreyWay/laravel-mix).

**Comment by JeffreyWay** [comment]
Yep - this is a Mix issue exclusively.
