### ISSUE TITLE
Queue query to database missing from statement

### ISSUE THREAD

**Issue by meijdenmedia** [laravel/framework#23627]
- Laravel Version: 5.5.39
- PHP Version: 7.0
- Database Driver & Version: postgresql 9.5.4

### Description:
The queue is working correctly, items are being pushed to database and correctly processed but I'm getting a lot of errors in my PostgreSQL error log. Laravel queue workers try to read data from table but they do not use a `from jobs` statement.
Unfortunately there is no stack trace. These errors won't pop up in my Laravel error logs.

```
ERROR:  column "reserved_at" does not exist at character 36
STATEMENT:  select count(*) as aggregate where "reserved_at" is null and "queue" = $1 and "available_at" <= $2
```

### Queue configuration:
```
<?php
return [
    ****
    'database' => [
        'driver' => 'database',
        'table' => 'jobs',
        'queue' => 'default',
        'retry_after' => 180,
    ]
];
```

### Supervisor configuration:
```
[program:laravel-queue-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www artisan queue:work database --tries=5 --sleep=2
autostart=true
autorestart=true
numprocs=8
timeout=120
redirect_stderr=true
stdout_logfile=/var/log/laravel-queue-worker.log
```

**Comment by sisve** [comment]
Could you update your issue with a stack trace? It would help us track down where this faulty query is generated.

**Comment by staudenmeir** [comment]
The `FROM` part gets removed from queries when the table name is `NULL`. Is your configuration correct?

**Comment by meijdenmedia** [comment]
Everything else is working as intended. The queue is working correctly.

```
<?php
return [
    ****
        'database' => [
            'driver' => 'database',
            'table' => 'jobs',
            'queue' => 'default',
            'retry_after' => 180,
        ]```

**Comment by laurencei** [comment]
I've used this setup without issue. Looks like a local server config issue somehow.

If you can provide steps to replicate on a fresh install of Laravel 5.7 (or even 5.5) please let us know and I'll open this ticket again.
