### ISSUE TITLE
Cannot use `$wrap` as key when using eloquent resources

### ISSUE THREAD

**Issue by algorhythm** [laravel/framework#23625]
- Laravel Version: 5.5
- PHP Version: 7.1.11

### Description:
Per default the `\Illuminate\Http\Resources\Json\Resource::$wrap` property contains the value `data`. So the returning `JSON` of my `Resources` looks like following:

```js
{
    'data': {
        'key1': 'someValue1',
        'key2': 'someValue2'
    },
    'additional1': 'someAdditionalValue1'
}
```

But when I add `data` as key in the `Resource::toArray()` method of a custom resource the wrapper will not be created and my response is flattened like this:

```js
{
    'key1': 'someValue1',
    'key2': 'someValue2',
    'data': 'someValue3',
    'additional1': 'someAdditionalValue1'
}
```

What I expect is:

```js
{
    'data': {
        'key1': 'someValue1',
        'key2': 'someValue2',
        'data': 'someValue3'
    },
    'additional1': 'someAdditionalValue1'
}
```

### Steps To Reproduce:
Write a Resource that uses the wrapper as key:

```php
/**
 * Class CustomResource
 */
class CustomResource extends Resource
{
    /**
     * Transform the resource into an array.
     *
     * @param \Illuminate\Http\Request $request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'type' => $this->type,
            'name' => $this->name,
            'data' => $this->data
        ];
    }
}
```

### Responsible Code
There is a function inside `\Illuminate\Http\Resources\Json\ResourceResponse::wrap()` that does the trick. Inside there is a check if the given data `haveDefaultWrapperAndDataIsUnwrapped`. If the data does not contain the configured `wrapper` the data will be wrapped with it. Otherwise it won't.

This logic prevent me from using `data` as key when `data` is also the configured wrapper. Does this make sense? Why not allowing the wrapper string?

### Work-around
```php
/**
 * Class CustomResource
 */
class CustomResource extends Resource
{
    /**
     * Transform the resource into an array.
     *
     * @param \Illuminate\Http\Request $request
     * @return array
     */
    public function toArray($request)
    {
        $data = [
            'id' => $this->id,
            'type' => $this->type,
            'name' => $this->name,
            'data' => $this->data
        ];

        /**
         * Wrap it again
         */
        if (array_key_exists(static::$wrap, $data)) {
            $data = [static::$wrap => $data];
        }

        return $data;
    }
}
```

**Comment by 36864** [comment]
If this were changed, how would you handle pre-wrapped resources?

**Comment by algorhythm** [comment]
I am not sure if I ever had the case. What do I have to do to work with pre-wrapped resources? In which case does this happen?

**Comment by Broutard** [comment]
I confirm this issue, I didn't have this problem before when I used https://github.com/dingo/api :(

**Comment by algorhythm** [comment]
@36864: You are right, my work-around is not working when the resource will be pre-wrapped. Than I have a nested `data` wrapper inside. But in my current case it works. I will hope that this will be fixed soon.

**Comment by raftalks** [comment]
just came across this issue with my team.

**Comment by driesvints** [comment]
This is the expected behavior. This would allow overriding the data key in the `toArray` method itself. If you want to disable wrapping all together and always control this behavior you can use the `Resource::withoutWrapping();`. Or if you want a different key you can update the `$wrap` property.
