### ISSUE TITLE
[5.6] Potential race condition with model factory after callbacks

### ISSUE THREAD

**Issue by Indemnity83** [laravel/framework#23621]
- Laravel Version: 5.6.12
- PHP Version: 7.1.14
- Database Driver & Version: sqlite in memory (testing)

### Description:

It looks like I introduced an unexpected bug/race condition with the behavior of after callbacks in PR #23495. In that the model returned can become out of sync with the database state that was created inside the factory()->create() call.  

### Steps To Reproduce:

Assuming you have users and teams:

```php
class User extends Model
{
    public function team()
    {
        return $this->belongsToMany(Team::class);
    }
}

class Team extends Model
{
    public function users()
    {
        return $this->belongsToMany(User::class);
    }
}
```

Example after callback for a user, who must be a member of a team to be a valid user:

```php
$factory->define(App\User::class, function (Faker $faker) {
    return [
        // valid attributes ...
    ];
});

$factory->afterCreating(\App\User::class, function (\App\User $user, Faker $faker) {
    $team = factory(\App\Team::class)->create();
    $team->users()->attach($user);
});
```

In a test, the first test assertion will unexpectedly fail sometimes, but the second (after calling fresh()) will always pass.

```php
$user = factory(User::class)->create();

$this->assertCount(1, count($user->teams));
$this->assertCount(1, count($user->fresh()->teams));
```

**Comment by Indemnity83** [comment]
False alarm, after simplifying my particular code for the example above it looks like its working, just a bug in my slightly more complex code.

**Comment by Indemnity83** [comment]
Re-opening ... looks like this might be a race condition. I'm getting varied results even when just re-running the tests. 

I'm not sure if I can put together a test that is 100% reproducible though. Does this make sense to others that a race could be happening here?

I'm running tests with in-memory sqlite.

**Comment by unstoppablecarl** [comment]
It might be a sqlite quirk can you try mysql?

**Comment by ChrGriffin** [comment]
I've just encountered an issue myself that seems very similar.

Consider the following test:

```
$language = factory(Language::class)->create();
$story = factory(Story::class)->create();
factory(Story::class)->create();
factory(Clip::class)->create([
    'story_id' => $story->id,
    'language_id' => $language->id]
);

$stories = Story::notEmpty()->get();
$this->assertFalse($stories->isEmpty());
foreach($stories as $story) {
    $this->assertFalse($story->clips->isEmpty());
}
```

The intent of the test is fairly self-evident. I've written a custom scope called `scopeNotEmpty()`, that only returns Stories (Categories) that have media clips attached.

```
public function scopeNotEmpty($query)
{
    return $query->whereHas('clips');
}
```

This test fails or passes randomly, on the assertion: `$this->assertFalse($stories->isEmpty());`. Randomly and without apparent cause, sometimes there are Stories in the database, and sometimes there aren't.

I'm running my tests on an in-memory SQLite database, just like @Indemnity83. Notably, I have an entire test suite that runs predictably. This is the first time I've encountered this behaviour. Unlike @Indemnity83, I do not have an existing entity that I can call `fresh()` on to get a fresh copy out of the database.

**Comment by cbj4074** [comment]
@tillkruss Why was this closed?

**Comment by edwinvdpol** [comment]
Having the same problem. I need to `refresh() `my model in order to load the correct relationships which were set in `afterCreating()`. Also using SQLite.

**Comment by edwinvdpol** [comment]
Same problem here. I have to `refresh()` the model after creating and `afterCreating` is ran.
When I do a `GET` request afterwards without the refresh, it works.
When I do a `PUT` request afterwards without the refresh, it does not work.

**Comment by NickJorens** [comment]
I know the issue is closed, but I still wanted to mention that I'm getting this behaviour now.
