### ISSUE TITLE
[Suggestion] Validated data in FormRequest

### ISSUE THREAD

**Issue by miaotaizi** [laravel/framework#23631]
- Laravel Version: 5.5
- PHP Version: 7.1
- Database Driver & Version: mysql

### Description:
Is it better to replace `$rules = $this->container->call([$this->getValidatorInstance(), 'getRules']);` with `$rules = $this->container->call([$this, 'rules']);`  in `Illuminate\Foundation\Http\FormRequest` line 175

**Comment by tillkruss** [comment]
Feel free to make a PR or discuss this in internals.
