### ISSUE TITLE
Unexpected method behavior upon interpolated call of "accessor-like" method.

### ISSUE THREAD

**Issue by wreighsantos** [laravel/framework#23639]
- Laravel Version: 5.6.9
- PHP Version: 7.1.7
- Database Driver & Version: MySQL 5.7.19

### Description:
When invoking a method which is named like an "accessor/getter" through string interpolation, it will trigger the `__get` magic function resulting to unexpected method behavior.

### Steps To Reproduce:

1. Create two models.
    SampleModel.php, SampleRelatedModel.php

2. Create relationship in SampleModel.php

    ```
    public function relatedModels()
    {
        return $this->hasMany(SampleRelatedModel::class);
    }
    ```

3. Create an "accessor-like" method for relatedModels in SampleModel.php

    ```
    public function getRelatedModels()
    {
        return "Sample Method";
    }
    ```

4. Test the methods

- Call `$sampleModel->relatedModels;`. This will return a collection of `SampleRelatedModel`s related to it.

- Call `$sampleModel->getRelatedModels()`. This will return `"Sample Method"` string.

- Now, interpolate the previous call. `"$sampleModel->getRelatedModels()"`.
  - This will cause an error saying: method `getRelatedModels` should return a relationship.

I've traced the method calls, it seems to me that the interpolated call triggered the magic `__get` method of the model.

This is the result of what I've traced.

```
// Model.php
public function __get($key)
{
    return $this->getAttribute($key);
}
// |
// V
// HasAttributes.php
public function getAttribute($key)
{
    ...
    return $this->getRelationValue($key);
}
// |
// V
// HasAttributes.php
public function getRelationValue($key)
{
    ...
    if (method_exists($this, $key)) {
        return $this->getRelationshipFromMethod($key);
    }
}
// |
// V
// HasAttributes.php
protected function getRelationshipFromMethod($method)
{
    $relation = $this->$method(); // <-- lastly to this
    // $method = "getRelatedModels"
    if (! $relation instanceof Relation) {
        throw new LogicException(sprintf(
            '%s::%s must return a relationship instance.', static::class, $method
        ));
    }
    ...
}
```

I'm not sure if this bug is PHP-specific or Laravel-specific. The bug was discussed here: https://stackoverflow.com/questions/49378402/laravel-type-error-too-few-arguments-to-function-app-productgettax-0-pa/49379823#49379823

**Comment by staudenmeir** [comment]
This is neither a issue with Laravel, nor with PHP. You are just using the wrong syntax:

`"$sampleModel->getRelatedModels()"` is equivalent to `"$sampleModel->getRelatedModels"."()"`.

The usage of variables in strings is limited to `"$foo"` and `"$foo->bar"`. Function calls like `"$foo->bar()"` 
don't work. You can (but shouldn't) use curly braces for that: `"{$foo->bar()}"`

The better solution is just simple string concatenation:

    "text..." . $sampleModel->getRelatedModels() . "more text..."

**Comment by wreighsantos** [comment]
Ok thanks! Got it!
