### ISSUE TITLE
Optional failed for non defined variable

### ISSUE THREAD

**Issue by 1dnmr** [laravel/framework#23640]
- Laravel Version: 5.6.11
- PHP Version: 7.1.13
- Database Driver & Version: MySQL 

### Description:

Any call to optional($value) with underfined $value lead to exception. For example if $value is not defined for blade view.

I suggest  change function to this:

    function optional($value = null)
    {
        return new Optional($value ?? null);
    }

**Comment by ntzm** [comment]
That still won't work unfortunately

**Comment by 1dnmr** [comment]
Why?
Now using optional is not not safe. Always need to use isset() before using optional()

**Comment by ntzm** [comment]
https://3v4l.org/aC0Fl

**Comment by staudenmeir** [comment]
That's a fundamental limitation in PHP. You can't use an undefined variable as a parameter. The only exception is `isset()`.

**Comment by 1dnmr** [comment]
does not matter. make it working. my idea that curent implementation of optional is not good.

function optional($value = null)
{
    return new Optional(isset($value) ? $value : null);
}

**Comment by ntzm** [comment]
That still doesn't work

**Comment by 36864** [comment]
That still wouldn't fix anything. The error occurs when you try to pass an undefined variable into the optional helper, not when the Optional instance is created. 
Optional is meant to be used when you have a variable that may or may not be null by the time you want to use it. There is nothing we can do to handle undefined variables.

**Comment by 1dnmr** [comment]
in php variable can be undefined also. so using of optional helper is very limited. 
as my opinion if was created to reduce amount of similar coding patterns. in real life you still need to check if variable undefined. so this helper is useless.

**Comment by 36864** [comment]
This repository is for reporting bugs in the framework. Having the opinion that a helper in the framework is useless does not count as a bug, so please close this issue.
If you have any insight on how to make optional useful, feel free to submit a PR. I'm sure more people would like for optional to also work with undefined variables.
If you'd like to start a discussion on the usefulness of the framework's helper functions, either use the laravel/ideas repository, the forums, or the slack channel.

**Comment by 1dnmr** [comment]
I found working solution. Please check:

function optional(&$value) {
   return new Optional(isset($value) ? $value : null);
}

Actually I don't think this is discussion. I think this is a bug. Optional() behaviour now lead to buggy code.

**Comment by 36864** [comment]
There are no claims that the optional helper can handle undefined variables. The fact that a function does not do something it does not claim to do is not a bug.

What you're asking for for an additional functionality to be added to he helper, which is the sort of issue that should be raised in laravel/ideas or submitted to this repository as a pull request.

As for your solution, it is, at best, insufficient and actually introduces a bug. The point of using optional is to be able to attempt to call methods on variables that may not have a value at time of execution, as shown below:
```
$model = Service::findModel('myModel'); //returns null if 'myModel' does not exist
optional($model)->doTheThing();
```

I'm curious to know what your use case for having undefined variables is, but I'm going to assume you're using this in a view that may or may not be passed a variable, something like this:
```
<div class="optional-content">
{!! optional($content)->toHtml() !!}
</div>
```
This snippet would currently fail with an undefined variable notice.
With your proposed solution, it would fail by throwing an error "Call to a member toHtml() on null".

It is also a breaking change as anyone who overrides the helper would no longer have a compatible version of it, so if you're going to submit a PR for this after fixing the bug you're introducing, please send it to the 5.7 branch.

**Comment by mfn** [comment]
The shortest you can do for optional in that regard _would_ be: `$foo = optional($value ?? null);`

**Comment by 1dnmr** [comment]
@mfn thanks! you right, it's best solution
