### ISSUE TITLE
Queues stopped working after the upgrade

### ISSUE THREAD

**Issue by Batisska** [laravel/framework#23642]
- Laravel Version: 5.6.12
- PHP Version: 7.1.15
- Database Driver & Version: (PostgreSQL) 10.3 (Ubuntu 10.3-1.pgdg16.04+1)
 
[config/queue.php][1]

In the .env file:

    QUEUE_DRIVER=database

[App\Mail\MailTest.php][2]

    Route::get('testmail', function () {
    return  Mail::to('***@****', 'Джон Смит')
        ->queue(new \App\Mail\MailTest());
});

I run the queue:

    php artisan queue:work

When I try to send a message, I see an entry in the jobs table.

The failed_jobs table is empty.

After sending in the console there are no entries about the queued letters.

Also in the log file there is no information.

Queues stopped working after upgrading to 5.6 or perhaps due to a change in mysql to postgresql.

Without a queue, the mail is sent.

Tell me how can I fix this?

  [1]: https://gist.github.com/Batisska/0625e51e2353f93dc5d5a37811302408
  [2]: https://gist.github.com/Batisska/ba64251fbcb34dd23403d735c81bf1b4

**Comment by Batisska** [comment]
Tell me how can I start debugging? Errors in the logs do not appear. Even thoughts do not have anything to begin with.

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
