### ISSUE TITLE
Model::getKeyName() function truncating field with a hexadecimal value

### ISSUE THREAD

**Issue by nasiriyima** [laravel/framework#23646]
- Laravel Version: 5.5.*
- PHP Version: 7.1.13
- Database Driver & Version:  MySQL 5.6.39

### Description:
Overriding the `getKeyName();` function in a model truncates the returned field when its an hexadecimal  value

### Steps To Reproduce:
- Create a table for example `fruits` with a unique varchar field that has a length of 191. Name it anything, in my own case I called it `slug` 
- Create a model using the artisan command for example `php artisan make:model Fruit` and a resource controller using the artisan command for example `php artisan make:controller FruitController --resource --model=Fruit`
- Now override the `getKeyName();` function in the model by returning the field you created in the database for example
`public function getKeyName(){  return 'slug'; }`
- Next, seed the Fruits Table by generating a random hexadecimal value for the field previously created in the database using the `bin2hex();` php function like so `bin2hex(random_bytes(64));`
- Now trying to get the hexadecimal value of the field in the edit function in the Fruit resource controller gets truncated

**Comment by staudenmeir** [comment]
Please post your `edit` method, an example value for `slug` and how it gets truncated.

**Comment by sisve** [comment]
The getKeyName() is for the primary key, which per default is cast to an integer. Strings that starts with integers (like some hex values) will appear to be truncated.

To disable this, set `$incrementing = false` in your model.

I don't see how the slug field is relevant to the problem. Where you thinking of overriding getRouteKeyName?

**Comment by nasiriyima** [comment]
Although the truncation issue can also be replicated using any of the CRUD methods, however below is an example in the routes file:

- Example using routes file
`Route::get('/mimic-data-truncation-issue', function(){
              $id = 1;
              $fruit = Fruit::find($id);
              return $fruit->slug;  //data gets truncated here
});`

- Hexadecimal slug value = `"8825d6730de9acd87033f50e0eb7d33edb3eb051ee07a258c071375d6832b9cbd91c96dbda2200f60b5a6f3dfe79b53e0f0cb96fde4f41855fc12019de2bf2be"`

- Truncated slug value = `"8825"`

**Comment by nasiriyima** [comment]
@sisve 
 But it's interesting to note that it works whenever I use another text field for example, if I override the `getKeyName();` function using another field like say the `name`  field instead of the `slug` field in database table it returns the string normally as it should be. Correct me if am wrong though, but does it have anything to do with the properties setup for the field in the database table? because, the `slug` field has a `unique` property and a length of 191 setup, while the other fields like the `name` field are just normal `varchar` database fields with default migration properties.

**Comment by sisve** [comment]
There's nothing interesting at all in this issue. This does not have anything to do with the unique constraint, or the length of the field.

1. Why are you overriding the getKeyName() method, which is meant for the primary key, to use something that isn't the primary key?
2. Do you have `$incrementing=false` in your model?
3. Since you're talking about a slug, and not a primary key, were you thinking of getRouteKeyName instead of getKeyName?

**Comment by nasiriyima** [comment]
@sisve
- Yeah I actually wanted to override the `getRouteKeyName();` method at first which didn't work, until I tried the `getKeyName();` method in another model which worked. Although I know that it overrides the primary key on the model, but I don't mind that. I guess, I will just maintain the controller as it is for now without the controller-model binding. Anyways, Thanks for your time.
