### ISSUE TITLE
Update Many-to-Many relationships with scope

### ISSUE THREAD

**Issue by ahlechandre** [laravel/framework#23647]
Would be great if many to many update methods works with model query scopes like:

```php
$form->sections()
  ->active()
  ->sync([1, 2, 3, 4]);
```
Let's say that section id `4` correspond to a inactive section (`!$section->is_active`). Then, we expect that `sync` method ignores this specific resource and attach `[1, 2, 3]`.

**Comment by nguyenphuocnhatthanh** [comment]
I think you should check section is_active before call sync  method
