### ISSUE TITLE
PDO::prepare(): MySQL server has gone away

### ISSUE THREAD

**Issue by madaima** [laravel/framework#23652]
- Laravel Version: 5.5
- PHP Version: 7.0
- Database Driver & Version: mysql & 5.6

### Description:
My program runs in memory . When I use data transactions,This will increment $this->transactions;
![image](https://user-images.githubusercontent.com/19197922/37752230-0ea8b7c0-2dd2-11e8-8190-e1a392f20734.png)

![image](https://user-images.githubusercontent.com/19197922/37752279-5adaa68a-2dd2-11e8-9e91-fa708dcb620a.png)

Then, the database will not be relinked here. Will throw an exception.

**Comment by tillkruss** [comment]
See https://dev.mysql.com/doc/refman/5.7/en/gone-away.html
