### ISSUE TITLE
Artisan locks file - Website won't load - Windows

### ISSUE THREAD

**Issue by adam1010** [laravel/framework#23650]
If I have a long-running Artisan process (including **php artisan tinker** / Psy shell) my website will hang (not load / timeout) until the process quits.

For example:
```
Artisan::command('sleep', function () {
    sleep(60);
});
```

It would appear that Artisan is locking a file that is used by Laravel to load my website. This is not a recent change, it happens in all versions of Laravel that I have tested (5.4, 5.5, 5.6).

I'm using Windows 10, 64-bit.

**Comment by sisve** [comment]
1. Can this be repeated on a new Laravel installation?
2. Which webserver are you using?
3. Are you using any database transactions that may block?

**Comment by adam1010** [comment]
1. Yes. In fact I have multiple websites running different versions of Laravel. If I'm running artisan tinker on ANY of the Laravel installs, ALL of the websites will block!

2. Apache with mod_fcgid

3. Nope, nothing fancy on the database level. It hangs on pages with no database calls too.

**Comment by sisve** [comment]
I see that you tried filing an issue at https://github.com/bobthecow/psysh/issues/474 too.

Do you have xdebug or any other profiling/debugging tools that can help you determine where the web processes are stuck?

**Comment by adam1010** [comment]
Yeah I actually just started using xdebug to trace it. The site doesn't even start executing the first line of code in public/index.php when Psy is running.

So it would appear that **xdebug is actually the problem**, not artisan. I'll close this ticket now too :-)

**Comment by adam1010** [comment]
I found the solution so I'll post it here in case anyone else runs into this:

In PHPStorm you need to set Languages > PHP > Debug > Max Simultaneous Connections

By default it is 1 for some reason, so just jack it up to 5 and you're all set!
