### ISSUE TITLE
Variable remains visible outside of the loop in blade

### ISSUE THREAD

**Issue by ObSeSSeN** [laravel/framework#23666]
- Laravel Version: 5.6.12
- PHP Version: 7.1.14
- Database Driver & Version: 10.2.13-MariaDB Homebrew

### Description:
When using the foreach loop in Blade the variable used to represent a single item remains visible outside of the loop.

### Steps To Reproduce:
Take an array of items (it can be a simple flat array of numbers) create a foreach loop in Blade and try to display/use the item variable after the loop.

Example:
```blade
@php
    $items = [1, 2, 3, 4, 5];
@endphp

@foreach($items as $item)
    {{ $item }}
@endforeach

{{ $item }} // This should fail but in my case, it remains set and displays the last number (5)
```

**Comment by decadence** [comment]
It's the way PHP works.

```php
$items = [1, 2, 3, 4, 5];
foreach ($items as $item) {

}

dd($item); // 5
```

So there is nothing about Blade.

**Comment by ObSeSSeN** [comment]
Yes, I have just tried it with pure PHP and its the same as in Blade.
