### ISSUE TITLE
Mailable $locale does not serializes when queuing

### ISSUE THREAD

**Issue by alshenetsky** [laravel/framework#23675]
- Laravel Version: 5.6.12
- PHP Version: 7.2.1
- Database Driver & Version: MySQL 5.5.5

### Description:
Ability to set locale on Mailables was added in [https://github.com/laravel/framework/pull/23178](https://github.com/laravel/framework/pull/23178)
But there is a bug:
The $locale  variable in Mailable class does not serializes.

### Steps To Reproduce:
1. Make a Mailable class that implements ShouldQueue
2. Set mailable locale in instance constructor or build() method:

```
    /**
     * Build the message.
     *
     * @return $this
     */
    public function build()
    {
    	return $this->view('myview')->locale('lv');
    }

```

3. Let it be queued

And now, if we look into serialized job, we will see:

`s:6:\"locale\";N;` 

When job starts running, instance does not receive locale.

```
	/**
	 * Send the invoice.
	 *
	 * @param  \Illuminate\Contracts\Mail\Mailer  $mailer
	 * @return void
	 */
	public function send(MailerContract $mailer)
	{
		dd($this->locale); // NULL
	
	}
```

**Comment by themsaid** [comment]
I can't replicate this, works fine for me.
