### ISSUE TITLE
API response double quoted numeric value

### ISSUE THREAD

**Issue by ScriptMint** [laravel/framework#23679]
- Laravel Version: 5.6.12
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7 (Using mysqlnd driver)

### Description:
API response returning double quoted numeric value therefore producing undesired output.

![1](https://user-images.githubusercontent.com/31760604/37862568-1b8e1cba-2f75-11e8-8d25-140d9db1f8f5.jpg)

Why numeric values in response is double quoted?

### Steps To Reproduce:
A simple post request to http://task-king.online/api/auth/check

**Comment by Kyslik** [comment]
No code given just a picture. Share code but not here try StackOoverflow instead or maybe laracasts.com

**Comment by staudenmeir** [comment]
Did you take a look at this? https://stackoverflow.com/q/42862620/4848587

**Comment by staudenmeir** [comment]
Can you please close the issue?
