### ISSUE TITLE
\PhpRedisConnector::buildClusterConnectionString() must be of the type array

### ISSUE THREAD

**Issue by Warchiefs** [laravel/framework#23692]
**ENV:**
Laravel 5.6
Php7.2
Php72-redis
Redis 4.0.2

[]redis in database.conf
```php
'redis' => [

        'client' => 'phpredis',

        'options' => [
            'cluster' => 'redis'
        ],

        'clusters' => [
            'default' => [
                'host'     => env('REDIS_HOST', 'localhost'),
                'password' => env('REDIS_PASSWORD', null),
                'port'     => env('REDIS_PORT', 6379),
                'database' => 0,
                'serializer' => 'igbinary',
                'timeout'    => 0.5,
            ],
        ],

        'cache' => [
            'host'     => env('REDIS_CACHE_HOST', 'localhost'),
            'password' => env('REDIS_CACHE_PASSWORD', null),
            'port'     => env('REDIS_CACHE_PORT', 6379),
            'database' => 2,
        ],
    ],
```
$ php artisan config:clear

In PhpRedisConnector.php line 50:
                                                                                                                                              
  Argument 1 passed to Illuminate\Redis\Connectors\PhpRedisConnector::buildClusterConnectionString() must be of the type array, string given

**Comment by tillkruss** [comment]
Can you dump `$config` that's passed to `connectToCluster()`?

**Comment by Warchiefs** [comment]
```
array:4 [
  "host" => "127.0.0.1"
  "password" => null
  "port" => "6380"
  "database" => 0
]
```

but i have an exception (with config from docs)

`In PhpRedisConnector.php line 52:
                                                                                            
  Argument 1 passed to Illuminate\Redis\Connectors\PhpRedisConnector::buildClusterConnecti  
  onString() must be of the type array, string given   `

**Comment by Warchiefs** [comment]
Exception dumping result (first argument from this function):

string: host

**Comment by tillkruss** [comment]
This doesn't make sense, you must be calling `buildClusterConnectionString()` manually, because `connectToCluster()` would already fail, it also expects an array.

**Comment by alibo** [comment]
@Warchiefs You should change: 

```php
        'clusters' => [
            'default' => [
                'host'     => env('REDIS_HOST', 'localhost'),
                'password' => env('REDIS_PASSWORD', null),
                'port'     => env('REDIS_PORT', 6379),
                'database' => 0,
                'serializer' => 'igbinary',
                'timeout'    => 0.5,
            ],
        ],
```

to:

```php
        'clusters' => [
            'default' => [
                [
                    'host'     => env('REDIS_HOST', 'localhost'),
                    'password' => env('REDIS_PASSWORD', null),
                    'port'     => env('REDIS_PORT', 6379),
                    'database' => 0,
                    'serializer' => 'igbinary',
                    'timeout'    => 0.5,
                ],
            ],
        ],
```

In Laravel 5.4 and above, you can define multiple Redis cluster connections. Also, for each one of them, you can define an array of Redis instances.
