### ISSUE TITLE
[5.4] Custom guard logging on next refresh after login

### ISSUE THREAD

**Issue by webleyson** [laravel/framework#23700]
- Laravel Version: 5.4
- PHP Version: 7.1
- Database Driver & Version:

Maria DB

### Description:
I have created a custom guard with custom login controller.
This was all done in Laravel 5.4 (no upgrades etc).
I had the issue originally on my local machine, but suddenly the session persisted after I removed all the code from my custom model and re-entering it. 

If this was a problem to do with permissions on my sessions folder would this affect my User login also?

### Steps To Reproduce:
I crated a custom Login controller using a custom guard. I think it may be something to do with Auth middleware...???

**Comment by sisve** [comment]
It's not clear to me what you're trying to do. Are you reporting an bug in the framework? If so, Laravel 5.4 is no longer supported. Are you asking for help? Then try the forums, chat or Slack.
