### ISSUE TITLE
LIMIT doesn't work in combination with chunk

### ISSUE THREAD

**Issue by scottlaurent** [laravel/framework#23709]
- Laravel Version: 5.x

### Description:
Not sure if this is a bug, or some kind of inherent limitation due to the way the chunk() function is written. 

### Steps To Reproduce:
Assuming Model has 1000 items. This will run 10 times.
Model::query()->limit(100)->chunk(100,function($chunk) { // do something } );

#Example Use Case:  I wanted to be able to simply go back and perform a function on certain types transactions of a given type.  In this case there was no increment field by which I could simply do some kind of id trickery.  Not sure if I'm missing something here.

    static function recalculateLastCallTransactions($qty=null) {
        $query = static::inbound()->createdToday();
        if ($qty) {
            $query->limit($qty);
        }
        $query->chunk(100, function ($conferenceCalls) {
            $conferenceCalls->each(function($conferenceCall) {
                $conferenceCall->recalculateAccounting();
            });
        });
    }

**Comment by sisve** [comment]
This is a known issue that has been brought up before in https://github.com/laravel/framework/issues/9649 and something that is open for a PR, according to https://github.com/laravel/ideas/issues/103.
