### ISSUE TITLE
Calling database migration on non-default database throws Symfony\Component\Console\Exception\CommandNotFoundException

### ISSUE THREAD

**Issue by carragom** [laravel/framework#23704]
- Laravel Version: 5.5.39
- PHP Version: 7.0.27
- Database Driver & Version: Tested with mysql and pgsql

### Description:

The following command runs correctly when ran from the CLI

    php artisan migrate --database mydb

but when I try to run it from code like this:

```php
Artisan::call('migrate', ['--database' => 'mydb']);
```

I get a `Symfony\Component\Console\Exception\CommandNotFoundException`

### Steps To Reproduce:

1- Create a new Laravel project

    composer create-project --prefer-dist laravel/laravel test "5.5.*"

2- Setup some migrations, we can use the ones for the authentication

    php artisan make:auth

3- Setup a copy of the default `mysql` db configuration with a different name at `config/databases.php`

```php
'mydb' => [
        'driver' => 'mysql',
        'host' => env('DB_HOST', '127.0.0.1'),
        'port' => env('DB_PORT', '3306'),
        'database' => env('DB_DATABASE', 'forge'),
        'username' => env('DB_USERNAME', 'forge'),
        'password' => env('DB_PASSWORD', ''),
        'unix_socket' => env('DB_SOCKET', ''),
        'charset' => 'utf8mb4',
        'collation' => 'utf8mb4_unicode_ci',
        'prefix' => '',
        'strict' => true,
        'engine' => null,
];
```

4- Setup a blank mysql database to test

    create user test identified by test;
    create database test charset utf8;
    grant all on test.* to test;

5- Setup the `.env` file to reflect your database connection properties

6- Run tinker: `php artisan tinker` and try to run the following inside tinker

```php
Artisan::call('migrate', ['--database' => 'mydb']
```

This throws `Symfony\Component\Console\Exception\CommandNotFoundException`

### How to fix

Seems like the `migrate` command itself is not the problem, but the implicit call to the `migrate:install` [here](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Database/Console/Migrations/MigrateCommand.php#L97). I managed to solve this specific issue by changing this line from:

    $this->call(

to

    Artisan::call(

And adding a `use` to the `Artisan` facade. But I'm not sure if there is more to it than just this.

**Comment by driesvints** [comment]
This is because `migrate:install` isn't in the Tinker whitelist: https://github.com/laravel/tinker/blob/master/src/Console/TinkerCommand.php#L19

You'll have to create the migrations table before or add the command to the whitelist: https://github.com/laravel/tinker/blob/master/config/tinker.php#L16
