### ISSUE TITLE
Dotenv dependency

### ISSUE THREAD

**Issue by Seb33300** [laravel/framework#23715]
Symfony now provide a [Dotenv component](https://github.com/symfony/dotenv).

Since Laravel is already using multiple Symfony components, maybe the `vlucas/phpdotenv` dependency could be replaced by the Symfony component?

**Comment by mfn** [comment]
A technical case should be done as to "why", not just "because".

**Comment by martinbean** [comment]
@Seb33300 What advantages would switching to Symfony’s package provide over keeping the existing package?

**Comment by Seb33300** [comment]
I proposed this idea because I thought it could give more consistency to use dependencies from the same vendor.
I not able to tell you if there are a technical advantage to made the change.

Symfony didn't provide this component when `vlucas/phpdotenv` was added to the Laravel project, and I think this is why the Symfony component isn't used in Laravel at this time.

**Comment by Seb33300** [comment]
Fabien explained why he decided to create his own component instead of using `vlucas/phpdotenv` in this pull request: https://github.com/symfony/symfony/pull/21234

**Comment by tillkruss** [comment]
Please move this discussion to internals.
