### ISSUE TITLE
ApiResource collection method throws Builder::mapInto does not exist.

### ISSUE THREAD

**Issue by tradzero** [laravel/framework#23719]
- Laravel Version: 5.6.13
- PHP Version: 7.2.1
- Database Driver & Version: MySQL 5.7.19

### Description:

i got a model collection, and i want to build it to ApiResource and i got this error `Method Illuminate\\Database\\Query\\Builder::mapInto does not exist.`

i am sure i put a collection and NOT Builder into methods

and i try dump `$rewards` this is result
![image](https://user-images.githubusercontent.com/13845447/38016202-e62e03e4-32a0-11e8-8600-f24f8884bbb3.png)

### Steps To Reproduce:

![image](https://user-images.githubusercontent.com/13845447/38016169-c21fa02a-32a0-11e8-879c-224d1a7cbfab.png)

**Comment by tradzero** [comment]
i use `new RewardCollection($rewards)` and it works

**Comment by staudenmeir** [comment]
You have to call the `collection` method on the resource, not on the collection.

From the [documentation](https://laravel.com/docs/5.6/eloquent-resources):

    Route::get('/user', function () {
        return UserResource::collection(User::all());
    });

**Comment by tradzero** [comment]
@staudenmeir OK thanks
