### ISSUE TITLE
Required if validation doesn't work with wildcards

### ISSUE THREAD

**Issue by xAockd** [laravel/framework#23723]
- Laravel Version: 5.6.13
- PHP Version: 7.1.13
- Database Driver & Version:

### Description:
Laravel doesn't validate array items if they don't exist in the passed data.
I know that in old versions of laravel i.e. 5.2 it works as expected.

_Update:_
I've rechecked, and it also doesn't work in 5.2. It works only in case if we pass the hours array with empty values. Is it look like a bug?

### Steps To Reproduce: 
   ```
$data = ['day' => '2018-04-01', 'closed' => 0];

  $rules = [
        'day'               => 'required|date',
        'hours.*.from_time' => 'required_if:closed,0|date_format:H:i',
        'hours.*.till_time' => 'required_if:closed,0|date_format:H:i',
        'closed'            => 'boolean',
    ];
   $validator = Validator::make($data, $rules)->passes( ); //result true
```

**Comment by staudenmeir** [comment]
Adding an extra rule fixes it for me:

    'hours' => 'required_if:closed,0'

Does this solve your problem?

**Comment by xAockd** [comment]
@staudenmeir Thanks, it solves the problem!

I've added validation that the value is array and it works perfect.

`'hours' => 'required_if:closed,0|array'`
