### ISSUE TITLE
Cache::put() incompatible with Cache::putMany()

### ISSUE THREAD

**Issue by LukeTowers** [laravel/framework#23729]
A check to pass on array keys sent to `Cache::put()` to be handled by `Cache::putMany()` was added by @taylorotwell in https://github.com/laravel/framework/commit/bbd825be3c95a43a7a222fa1eeb48bc527f0e36c#diff-4c4e25be22d12269a90d3484c9e72078R183 during a refactoring of the Cache implementation. This check is pointless at best and at worst suggests official support for calling `Cache::put(['key' => 'value']);` even though none exists.

The arguments passed to `putMany()` (`$this->putMany($key, $value);`) when `put()` is called with an array key does not line up with the actual parameters used by `putMany(array $values, $minutes)`

There are two potential solutions to this, either remove the `is_array($key)` check completely from `put()` or change it to pass `$this->putMany($key, $minutes)`. 

Personally I suggest that we just remove the `is_array($key)` check entirely since there are no documented uses of `put()` being called with an array key and even if it were the mismatch between the method signatures would cause it to not work correctly. The alternative is to keep the check and pass the correct arguments, but then we would require a pointless `$value` argument to be passed to `put($key, $value, $minutes)` to even use it as intended in which case the developer is better off just calling `putMany($values, $minutes)` directly themselves.

**Comment by LukeTowers** [comment]
For additional reference: https://github.com/laravel/framework/pull/13868#issuecomment-223764289

**Comment by tillkruss** [comment]
Can this be closed now?

**Comment by LukeTowers** [comment]
Since @taylorotwell doesn't want to change it (https://github.com/laravel/framework/pull/23730#issuecomment-376956096) sure.
