### ISSUE TITLE
L5.5 apiResource with custom parameter name

### ISSUE THREAD

**Issue by leandroruel** [laravel/framework#23726]
- Laravel Version: 5.5.34
- PHP Version: 7.1
- Database Driver & Version: MSSQL

### Description:
i'm creating a api, and some route names has portuguese language, when the apiResource() method creates the singular name of some routes, their name are spelled wrong, i want add custom parameter names but i don't know how, i searched the docs but not found anything about do it inside apiResource method, searched at SO too and found nothing 
```php
Route::group([
'middleware' => 'api'
], function () {
  Route::apiResources([
      'photos' => 'PhotoController',
      'posts' => 'PostController'
  ]);
});
```
### Steps To Reproduce:
go to api.php file inside routes, add a new route inside the apiResource array, don't have a way of add parameters

**Comment by tillkruss** [comment]
This repository is for bug report only. Please move this discussion to internals.
