### ISSUE TITLE
Command and job not executing completely

### ISSUE THREAD

**Issue by jfelipeara** [laravel/framework#23728]
- Laravel Version: 5.5
- PHP Version: 7.1
- Database Driver & Version: mysql 5.7

### Description:
I have a command that runs a scraper from some website and send a slack notification, it is a cron job and it works fine most of the times here is the code:
```
try {
            if (!Cache::has('scraper-database')) {
                Cache::forever('scraper', 'proccesing');
                $lines = shell_exec('node /home/jfelipeara/htdocs/administrator/resources/assets/js/scraper/index.js');
                $sims = json_decode($lines, true);
                $verifier = new BalanceVerifier($sims);
                $verifier->verify();
                Cache::forget('scraper');
            }
        } catch (Exception $e) {
            Cache::forget('scraper');
            Log::error('Scraper catch an exception: ' . $e->getMessage());
            Log::error('trace: ' . $e->getTraceAsString());
        }
```
when i run the command manually it works fine, when i use schedule it works fine, but some times the cache key doesn't delete and it doesn't catch any error and i have to clear it  manually so it run again next time. Also it does everthing it have to do, except for the cache clearing.

I also have a button that call the command to run the scraper but the shell_exect always return null, i tried make a job with the same code and push it to a queue but no luck, it says it processed but i doesnt event pass the shell_exec.

Hope anyone can help. thank you

**Comment by sisve** [comment]
This would happen if there's a timeout and the job is killed. The code will just be abruptly terminated without any way for you to handle that.

Try increasing the timeout with `php artisan queue:work --timeout=900` where 900 seconds = 15 minutes, or use 0 to disable the timeouts entirely

**Comment by jfelipeara** [comment]
i haven't set a timeout unless there is a default timeout. I'm going to try again creating a job and setting the timeout, because with the command it doesn't work

**Comment by jfelipeara** [comment]
i've tried setting a timeout of 15 minutes and the job stops at 1.5 minutes. i'm using horizon, it says  processed and it tries the number of times defined 
![image](https://user-images.githubusercontent.com/10985977/38946702-e506c3ce-42ff-11e8-9bef-dc2ed583253f.png)

**Comment by jfelipeara** [comment]
nvm, the problem was de redis retry_after property
