### ISSUE TITLE
Is there offline document for laravel

### ISSUE THREAD

**Issue by zhoupeng** [laravel/framework#23720]
Is there offline pdf document for  the online docs "laravel.com/docs/5.6"?

Thanks.

- Laravel Version: #.#.#
- PHP Version:
- Database Driver & Version:

**Comment by ludo237** [comment]
You can download [the repository](github.com/laravel/docs)

**Comment by zhoupeng** [comment]
Thank you.

**Comment by mfn** [comment]
@zhoupeng also, there's is software like "Dash for OSX" and similar for other OS which provide docs in an offline experience, including search capability, etc.
