### ISSUE TITLE
Laravel should respect PHP `date.timezone` setting

### ISSUE THREAD

**Issue by dancryer** [laravel/framework#23743]
- Laravel Version: 5.6
- PHP Version: PHP 7.2
- Database Driver & Version: N/A

### Description:
Laravel has a `timezone` setting in the `config/app.php` file, which is set to `UTC` by default. 

It should default to the system's configured timezone, whilst still leaving you with the opportunity to change it **if you see fit**.

Could the default not be:
`'timezone' => env('APP_TIMEZONE', date_default_timezone_get())`

### Steps To Reproduce:
- Create a new Laravel app
- Interact with dates in any way.

**Comment by ludo237** [comment]
Since config is not read only you can edit it...

**Comment by GrahamCampbell** [comment]
> Since config is not read only you can edit it...

Yes, I agree, and as per the PR comments, I think the current default is already the best.

**Comment by dancryer** [comment]
@ludo237 I am well aware that the config is editable. I just think the current default is a poor choice, especially for a framework that prides itself on making developers' lives easier.

**Comment by ludo237** [comment]
It's a config file, you should edit that anyway 😕 I don't get it

**Comment by dancryer** [comment]
I understand your point, I'm aware people can and should edit the file to suit their needs. 

Like I said, I just think the **default** could be better. It seems an odd choice to have the default set to UTC, when there's an easy way for it to be both editable *and* fall back to the system time by default, meaning that developers wouldn't **need** to edit it every time.

Regardless, you clearly disagree and that's fine. This is merely an opinion.
