### ISSUE TITLE
Incorrect primary key returned from HasManyThrough relationship

### ISSUE THREAD

**Issue by pmhou** [laravel/framework#23740]
- Laravel Version: 5.6.14
- PHP Version: 7.2
- Database Driver & Version: Sqlite 3

### Description:
The primary keys of records retrieved from a HasManyThrough relationship are incorrect when using the each method to iterate over the results.

### Steps To Reproduce:
Issue has been replicated here https://github.com/pmhou/laravel-bug.
See the example in the [web routes file](https://github.com/pmhou/laravel-bug/blob/master/routes/web.php).

**Comment by staudenmeir** [comment]
This is a known problem: #21774
