### ISSUE TITLE
firstOrFail and findOrFail with custom message

### ISSUE THREAD

**Issue by ahlechandre** [laravel/framework#23742]
Add an optional parameter "message" on `Illuminate\Database\Eloquent\Builder`:

**API**:

| Method |
|-------|
| findOrFail(mixed $id, array $columns = ['*'], $message = null) |
| firstOrFail(array $columns = ['*'], $message = null) |

**Usage:**
```php
$author = Author::findOrFail(2, ['*'], 'Second author not found');
$book = Book::firstOrFail(['*'], 'First book not found');
```

**Comment by HSPDev** [comment]
I like the concept and have often missed this myself, but what about automatic injection of models?

```
public function show(Book $book) 
{
   //Code
}
```

Maybe we should have a protected parameter or function on the model class itself? 

```
class Book extends Model 
{
    protected $notFoundMessage = 'The book could not be found';
}
```

This assumes a MVC design where the Model is "heavy", but maybe this could also be extracted elsewhere; Language files, a call in a Provider, or something "new"?

**Comment by BrandonShar** [comment]
This is a better fit for the laravel/ideas project, since it's a proposal, not an issue with the framework.

I'm not sure what you'd want this to do though. *orFail methods throw an exception if not found. Why do you want that exception to contain a user message?

**Comment by HSPDev** [comment]
@BrandonShar Because many real projects have customized error views, containing code like this.

```
({{ $exception->getMessage() }})
```
It's to better the user experience, not just having a "404 page not found", but specific messages like "Sorry, we could not find your book.".

**Comment by dwightwatson** [comment]
Is it normal to display the exception message to the user? I'd worry that it might contain sensitive information or be more confusing to a user than just "whoops, something went wrong".

**Comment by 36864** [comment]
I would argue that the developer should know what constitutes sensitive information and what doesn't. In the given example, you "leak" information about whether or not a book is contained in your library. That's hardly sensitive information.

If you're using findOrFail to fetch a user's personal data, just don't use the additional custom error message.

**Comment by devcircus** [comment]
You should already be able to get any information you need from the exception then customize your "not found" page as needed.

**Comment by HSPDev** [comment]
I actually stand corrected on my previous comment. I'm using _explicit_ model binding now, and using the clousure method of resolving my models. This let's me handle failures any way I want in a centralized location; I'm happy!

```php
Route::bind('administrator', function ($id) {
        return Administrator::find($id) ?? abort(404, 'Administrator does not exist.');
});

```
I can also see how this affords much more advanced logic.

**Comment by olivernybroe** [comment]
@HSPDev For reference, you can also do it in the model. 
So in your serviceProvider add
```
Route::model('administrator', Administrator::class);
```

and in your model do
```
public function resolveRouteBinding($id) {
    return Administrator::find($id) ?? abort(404, 'Administrator does not exist.');
}
`
``

**Comment by RomuloLim** [comment]
Hey @twickstrom, i implement using ValidationException (frontend can display the error more easily) and returning the `parent::render` case false. What do you think?

`
    public function render($request, Throwable $exception)
    {
        if ($exception instanceof ModelNotFoundException) {
            $model = explode('\\', $exception->getModel());
            $modelPhrase = ucwords(implode('',preg_split('/(?=[A-Z])/', end($model))));

            throw ValidationException::withMessages([
                $modelPhrase => \App::make($exception->getModel())->modelNotFoundMessage ?? $modelPhrase . ' not found'
            ]);
        }

        return parent::render($request, $exception);
    }
`

I'm using Laravel 8.X

**Comment by OmarElewa21** [comment]
@RomuloLim Nice to add a status 404 to the ValidationException.
`throw ValidationException::withMessages([
                $modelPhrase => \App::make($exception->getModel())->modelNotFoundMessage ?? $modelPhrase . ' not found'
            ]);->status(404)`

**Comment by brijmansuriya** [comment]
add Laravel **findorfail** add custom message

**Comment by plumthedev** [comment]
Dear @brijmansuriya 
You can customize your exception message using `Handler::renderable` on exception handler.
- [Laravel 10.x](https://laravel.com/docs/10.x/errors#rendering-exceptions)
- [Laravel 11.x](https://laravel.com/docs/11.x/errors#rendering-exceptions)

You can also always wrap `findOrFail()` in `try/catch` block and use [`abort`](https://laravel.com/docs/10.x/helpers#method-abort) helper - available from ages

```php
try {
    Airport::query()->where(...)->firstOrFail()
} catch (ModelNotFound) {
    abort(404, 'Airport cannot be found')
}
```
