### ISSUE TITLE
Form open problem 

### ISSUE THREAD

**Issue by postaczech** [laravel/framework#23751]
// data
```
array:4 [▼
  "code" => 104
  "name" => "theme name"
  "files" => array:1 [▼
    0 => "header.blade.php"
  ]
]
```
I cant use parametr array, show err Array to string conversion in blade where i have the form, laravel 5.6 says:

Illuminate/Routing/RouteUrlGenerator.php, line 266
```
if (count($keyed) < count($parameters)) {
            $query .= '&'.implode(
                '&', $this->getNumericParameters($parameters)
            );
        }
 
```
```
 {{ Form::open(['route' => ['route.name', $array]]) }}
 <button type="submit" class="btn btn-primary">Detail </button>
 {!! Form::close() !!}
```

**Comment by staudenmeir** [comment]
You have to add the route parameters separately:

    {!! Form::open(['route' => ['route.name', $array[0], $array[1], ...]]) !!}

**Comment by sisve** [comment]
Form::open is probably the laravelcollective/html package, and they handle their issues at https://github.com/LaravelCollective/html.
