### ISSUE TITLE
Route parameters makes singular problems in resources route

### ISSUE THREAD

**Issue by hirenkeraliya** [laravel/framework#23758]
In the Resources route can not work parameter of the route for edit, update and delete In my case that's given below.

`Route::resource('perus', 'PeruController');`

This perus name has been generated by facker factory.

That shuld be return parameter peru but that return parameter perus
![screenshot from 2018-03-31 12-10-19](https://user-images.githubusercontent.com/22992703/38160515-1c9eefae-34dd-11e8-846c-a453ceb61228.png)

**Comment by tillkruss** [comment]
This is how route resources work.
