### ISSUE TITLE
Bug with scheduler

### ISSUE THREAD

**Issue by shivampaw** [laravel/framework#23768]
- Laravel Version: 5.6.15
- PHP Version: 7.1.3
- Database Driver & Version: MySQL 5.7

### Description:
I set my config/app.php timezone to Europe/London and have set up the scheduler execute tasks at a specific time every day. However it seems that the scheduler didn't use the app's config timezone and defaulted to something else. I had to add the timezone method to each task to get it working - seems like a bug to me as the scheduler should default to the app config?

**Comment by arjasco** [comment]
Scheduled events will be interrupted in UTC. So if you're timezone is Europe/London then your events will run an hour later than expected.

I personally prefer working in UTC and converting to different timezones (especially if you have an app used across the world)

This is probably your solution - https://laravel.com/docs/5.6/scheduling#timezones

**Comment by shivampaw** [comment]
@arjasco Yeah I realised that but shouldn't the scheduler be using the app's timezone by default? Right now it ignores the app/config set timezone.

**Comment by shivampaw** [comment]
@decadence, nope. Didn’t have any cache because I tried it on a new installation of the app as well.

**Comment by arjasco** [comment]
Just tested for myself. `app.timezone` is being respected when changed, however @decadence makes very good point. If your config is cached it will need clearing and cached again via `php artisan config:cache` if an environment var / config has changed.

**Comment by shivampaw** [comment]
I think I figured it out. I’m the app/config file I had an accidental space
in it making it “ Europe/London” and I think that was invalid and therefore
became UTC.

Maybe make it strip whitespace or show an error but I assume that’s the
issue?

On 2 Apr 2018, at 15:43, Victor Isadov <notifications@github.com> wrote:

@shivampaw <https://github.com/shivampaw> so make

Route::get("timezone", function(){   return config("app.timezone");});

and check if this returns correct value.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/laravel/framework/issues/23768#issuecomment-377944685>,
or mute the thread

**Comment by decadence** [comment]
@shivampaw Strange because Laravel uses this config in

```php
date_default_timezone_set($config->get('app.timezone', 'UTC'));
```

So it must throw exception on not existing timezone.
