### ISSUE TITLE
signedRoute and Pagination don't play nice together

### ISSUE THREAD

**Issue by DeftNerd** [laravel/framework#23779]
- Laravel Version: 5.6.14
- PHP Version: 7.2.3-1
- Database Driver & Version: MariaDB-10.2.13

### Description:
signedRoute, a great addition to Laravel IMHO, uses named routes to generate URL's with the signature and optional expiration. 

The pagination template uses plain URL's and doesn't seem to take named routes into consideration when generating the URL's for additional pages.

There does not seem to be an obvious or easy way to use pagination with signedRoutes. 

### Steps To Reproduce:

Added the following to `app/Kernel.php`
```
    protected $routeMiddleware = [
        'signed' => \Illuminate\Routing\Middleware\ValidateSignature::class,
    ];
```

Added to `routes/web.php`
```
	Route::middleware(['signed'])->group(function () {
		Route::resource('articles', 'ArticleController');
	});
```

Added to `resources/views/welcome.blade.php`
```
<a href="{{ url()->signedRoute('article.index') }}">
```

Partial contents of `app/Http/Controllers/ArticleController.php`
```
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $articles = Article::with('comments')->paginate(20);
        return view('article.index', ['articles' => $articles]);
    }
```

Partial contents of `resources/views/article/index.blade.php`
```
@foreach ($articles as $article)
<h1>{{ $article->name }}</h1>
<p>{{ $article->summary}}</p>
@endforeach

{{ $articles->links() }}
```

The result is that someone can click on the link to the article index from the home page and successfully access that paginated results. However, clicking any of the pagination links results in a `\Illuminate\Routing\Exceptions\InvalidSignatureException` exception since the pagination link template doesn't handle signature generation properly.

**Comment by arjasco** [comment]
Have you appended your signature and expiry time to your paginator? 

```php
$articles->appends([
    'expires' => request()->input('expires'),
    'signature' => request()->input('signature')
])->links();
```

**Comment by DeftNerd** [comment]
@arjasco - Doesn't work, the signature is supposed to sign not just the URL but also the additional URL elements like ?page=2. By just appending the existing signature, it ends up being invalid.

**Comment by arjasco** [comment]
I see, that’s correct. What’s the use case then? 

I’ve used them in them in the past for creating a limited time access to a restricted resource that would normally require auth. 

Your case would mean that you have to have new signed urls for every page available, which isn’t really practical. Plus If someone wanted to directly visit page 25 for example out of 100 pages they wouldn’t be able to navigate to it without knowing the signature too.

Depending on your use case maybe a url with a token (eg JWT) would be more suited.

**Comment by DeftNerd** [comment]
One possible use case would be making it more difficult for botnets to be commanded to hit pages that require extensive SQL queries. 

Regardless, pagination is such a basic feature and it should have been considered when creating the ability to lock up entire routes behind signatures. If signed routes is wanted and has use cases, then pagination should be supported rather than used as an excuse not to use the signed route feature. 

I'm not sure of the best way to fix this. Some possible methods could be:

* Creating a signedUrl function that doesn't care about a route being named and altering the pagination template to check if the current page has a signature (and optional expiration) before it generates page-change URL's
* Altering the signedRoute validator so it ignores the page attribute during verification so one signature works for all paginated pages (not ideal, but easier to achieve)

**Comment by devcircus** [comment]
IMO this is way outside the traditional scope of signed urls. Maybe if you could implement this cleanly in a pr, it would possibly be considered? However, the token suggestion above seems the best way to handle this.
