### ISSUE TITLE
Class view does not exist

### ISSUE THREAD

**Issue by joe223** [laravel/framework#23783]
- Laravel Version: `laravel/framework v5.6.11`
- PHP Version: 
```
PHP 7.1.5 (cli) (built: Jun  2 2017 19:59:44) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.5, Copyright (c) 1999-2017, by Zend Technologies
```
- Database Driver & Version:

### Description:
Here is An Error:
```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In Container.php line 767:

  Class view does not exist


Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
```

### Steps To Reproduce:

If use Blade Component Alias in `/htdocs/app/Providers/AppServiceProvider.php`,  like that:
```
use Illuminate\Support\Facades\Blade;

Blade::component('desktop._module.component.content-box-title', 'contentBoxTitle');
```
I did what document said https://laravel.com/docs/5.6/blade#components-and-slots，But got an error when execute `composer install`.

**Comment by joe223** [comment]
I can not figure it out what is going on. 🙂

**Comment by jonpemby** [comment]
Just by looking at this output:

`In Container.php line 767:

  Class view does not exist`

I suspect perhaps a simple case error? Make sure `View` is capitalized if you're trying to use the facade somewhere.

**Comment by joe223** [comment]
what a ashame！I should write in `boot` method
```
public function boot () {
    Blade::component('desktop._module.component.content-box-title', 'contentBoxTitle');
}
```

**not outside the `class` section**
