### ISSUE TITLE
Laravel 5.5.40 can't connect to mysql if password is white space

### ISSUE THREAD

**Issue by dong-jy** [laravel/framework#23791]
- Laravel Version: 5.5.40
- PHP Version: 7.0.28-0ubuntu0.16.04.1
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.7.21, for Linux (x86_64) using  EditLine wrapper

### Description:
when mysql password is set to be whitespaces , `php artisan migrate` output :

>In Connection.php line 664: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) (SQL: select * from information_schema.tables where table_schema = coach_appoint and table_name = migrations)

>In Connector.php line 67: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)

Mysql and all other software work fine, and properly configured.

### Steps To Reproduce:

set mysql password to be whitespaces, 
.env:
``` env
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=db_name
DB_USERNAME=root
DB_PASSWORD='      ' # string of whitespace as password
```
run `php artisan migrate`.

**Comment by jonpemby** [comment]
Is there a reason you don't want to have a password?

**Comment by staudenmeir** [comment]
This is an issue with dotenv: https://github.com/vlucas/phpdotenv/issues/162
