### ISSUE TITLE
Protect laravel api routes

### ISSUE THREAD

**Issue by kobimilan995** [laravel/framework#23790]
I'm building an application in laravel that will have session based authentication, but i want to have some Vue.js components used within this application. If i m using session based authentication, how can i protect my api endpoints? For example, i m having a route that returns JSON of all of the users messages. Thats a get request, so anyone who knows some users id, can go into postman and send a request and get the messages. Is there any way to protect them without doing passport authentication?

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
