### ISSUE TITLE
Inconsistency between Collection::merge() and Collection::union()

### ISSUE THREAD

**Issue by jeanlucnguyen** [laravel/framework#23808]
- Laravel Version: 5.5.18
- PHP Version: 7.1.12

### Description:
Inconsistency between Collection::merge() and Collection::union()

### Steps To Reproduce:
```
collect(['a'])->union(collect(['b']))
=> Illuminate\Support\Collection {#1202
     all: [
       "a",
     ],
   }
```

```
collect(['a'])->merge(collect(['b']))
=> Illuminate\Support\Collection {#1205
     all: [
       "a",
       "b",
     ],
   }
```

From the documentation:

> The union method adds the given array to the collection. If the given array contains keys that are already in the original collection, the original collection's values will be preferred

> The merge method merges the given array or collection with the original collection. If a string key in the given items matches a string key in the original collection, the given items's value will overwrite the value in the original collection:

It seems that the union and merge should do the same, except that if the keys are similar in the 2 collections, then in the union method, the one from the original collection is kept, and in the merge method, the one from the added collection is kept.

Shouldn't we have this result?
```
collect(['a'])->merge(collect(['b']))
=> Illuminate\Support\Collection {#1205
     all: [
       "b",
     ],
   }
```

Also, I'm not sure if the 2 non associatives collections with index 0 are supposed to be considered as the same key or if 2 non associatives collections should just be added to each other. What is the expected behavior?

**Comment by tillkruss** [comment]
Please move this to internals. It's not a bug.
