### ISSUE TITLE
View method throws ErrorException (E_ERROR) Undefined variable if the variable is not defined in the controller

### ISSUE THREAD

**Issue by vitanivanov** [laravel/framework#23800]
- Laravel Version: 5.5.40
- PHP Version:  7.2.3
- Database Driver & Version: MySQL

### Description:
In Laravel <5.5 if you try to view a blade containing parameters in php tags without passing them, they were considered null.
After upgrading from 5.4 to 5.5.40, this behavior changed and in such cases "ErrorException (E_ERROR) Undefined variable" is thrown.

### Steps To Reproduce:
1. Create the following blade:
```html
    <?php
    echo $test
    ?>
```
2. Assign a route to a function with the following body:
```php
    return view('dashboard.test');
```
3. "ErrorException (E_ERROR) Undefined variable: test" is thrown, instead of treating "$test" as null in the blade

**Comment by themsaid** [comment]
that's how it always used to work. You need to predefine all your variables.

**Comment by vitanivanov** [comment]
No, that's how it recently started working. Tried it in 5.1, 5.2, 5.3, 5.4 and it didn't throw an error.
