### ISSUE TITLE
Artisan::call() doesn't accept unnamed arguments

### ISSUE THREAD

**Issue by aleemb** [laravel/framework#23805]
- Laravel Version: 5.5.32
- PHP Version: 7.2

### Description:

Used to be, you could call `Artisan::call('list', ['' => 'view']);` which would be analogous to calling `php artisan list view` but this doesn't work anymore.

Is there any other way to pass an argument?

**Comment by aleemb** [comment]
@Quezler as mentioned in the description, it's a nameless argument analogous to `artisan list view`

**Comment by Quezler** [comment]
Could you share the signature/name/arguments code from the command in question?

**Comment by aleemb** [comment]
@Quezler it's in the bug description and again in my response above. The example command is `artisan list view`. For example

```
> artisan list view

Available commands for the "view" namespace:
  view:clear  Clear all compiled view files
```

Now try running the same command via `Artisan::call(...)` and getting the same output.

**Comment by Quezler** [comment]
@aleemb give this a try:

```
$this->call('list', [
    'namespace' => 'view'
]);
```

the named arguments can be found on `symfony/console`'s [`ListCommand.php`](https://github.com/symfony/console/blob/master/Command/ListCommand.php#L85)

**Comment by aleemb** [comment]
That works, thanks very much!

**Comment by aleemb** [comment]
@Quezler Another hurdle is that while this works for `artisan list view` it doesn't work for `artisan tinker /tmp/foo`. The `tinker` cli command accepts a path as an argument. The error is that `'The "namespace" argument does not exist`. I suspect this isn't a generic solution unless `tinker` is a special case.

**Comment by Quezler** [comment]
These are the arguments for the [`TinkerCommand.php`](https://github.com/laravel/tinker/blob/master/src/Console/TinkerCommand.php#L116):

        return [
            ['include', InputArgument::IS_ARRAY, 'Include file(s) before starting tinker'],
        ];

**Comment by aleemb** [comment]
Thanks again, that worked.
