### ISSUE TITLE
Laravel deletes server.php on first artisan serve

### ISSUE THREAD

**Issue by neverender24** [laravel/framework#23809]
- Laravel Version: 5.6.12
- PHP Version:
- Database Driver & Version:
PHP Version 7.2.3
Tested in Latest Composer Version then rollback to 2017-12-18_12-09-18-1.5.6
Windows 10 Latest update

### Description: 
server.php is automatically deleted when I first run php artisan serve in fresh install laravel.

This will result to 

> Warning: Unknown: failed to open stream: No such file or directory in Unknown on line 0
> 
> Fatal error: Unknown: Failed opening required 'E:\xampp\htdocs\blog\doctrack\server.php' (include_path='E:\xampp\php\PEAR') in Unknown on line 0

I'm not new in Laravel especially in installation, so this is the first time I encountered this. Any help will be appreciated, thank you.

**Comment by neverender24** [comment]
I have tried to create new project and then copy the new server.php to the other project seems to fix it.

**Comment by iSpri** [comment]
It also happened once or twice by my side. Avast was considering the file `server.php` as a threat and automatically deleted it. I just added an exception to Avast and it fixed it.

**Comment by neverender24** [comment]
Now that you have said it, my AV is Avast also. Will add that to exception.

**Comment by TranDucQuynh** [comment]
neverender24: try the following on your cmd line:

php -S localhost:8888 -t public

Make sure the "-S" is capitalized. Hope this resolves your issue.

**Comment by iammrnoob3** [comment]
add exception to avast

**Comment by MartinMtandi** [comment]
Avast read it as a virus threat, i added exception to avast but it didnt resolve my issue. the file is still missing in my project files.

**Comment by iSpri** [comment]
@MartinMtandi your file was probably already gone when you added an exception. Try downloading the file again from this repo and put it back in your project.

**Comment by sergeev** [comment]
> neverender24: try the following on your cmd line:
> 
> php -S localhost:8888 -t public
> 
> Make sure the "-S" is capitalized. Hope this resolves your issue.

BIG Thx! Cool!

**Comment by mtariq786** [comment]
> neverender24: try the following on your cmd line:
> 
> php -S localhost:8888 -t public
> 
> Make sure the "-S" is capitalized. Hope this resolves your issue.

big thanks!

**Comment by mcarajesh40** [comment]
php -S localhost:8888 -t public

It was really helpful.
But I couldn't understand why ?

**Comment by buhek** [comment]
well its cause avast, i have disable my avast for 10 hour, then i make new file server.php and it work
