### ISSUE TITLE
Laravel5 Datatable Custom Field Sort

### ISSUE THREAD

**Issue by chsuthar** [laravel/framework#23819]
I have used laravel yajara datable to show record with relationship hasMany. In table listing there are two fields which is not existing in table I want sort these two fields can any one help me?
Relationship : Sales hasMany payment
Example : Table name is sales below is its fields
Fields : Store, Report Period, Total sales, Royalty,Received Amount (Not in database), Balance Due (Not in database)
**Received Amount** we get its amount from another table its name is payment. In this table there is multiple entry related to single sales and I sum that amount and show Total Received Amount
**Balance Due** we get its amount from **Royalty** - **Total Received Amount**
Now how can I sort these two coloum by yajra datable ?

**Comment by decadence** [comment]
Welcome to Laravel! We are glad to have you as part of the community.

Unfortunately GitHub is not an appropriate platform for general application issues. This is only for issues/bugs with the framework code itself.

Please close your issue, and instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

Laravel Slack (https://larachat.co/)
Laravel.io Forum (https://laravel.io/forum)
Laracasts Forum (https://laracasts.com/discuss)
StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks!
