### ISSUE TITLE
Serializing an Eloquent model to a JSON response not applying Carbon::serializeUsing

### ISSUE THREAD

**Issue by luizpinheiro** [laravel/framework#23813]
- Laravel Version: 5.6.15
- PHP Version: 7.2
- Database Driver & Version: 5.6

### Description:
In the docs for [Eloquent date serialization](https://laravel.com/docs/5.6/eloquent-serialization#date-serialization) we have:

>To customize how all Carbon dates throughout your application are serialized, use the Carbon::serializeUsing method.

When sending an Eloquent model in a JSON response, and having the follow code in the AppServiceProvider (just like in the snippet in the docs), Eloquent completly ignores the defined serialization format for dates.

```php
//AppServiceProvider
public function boot()
{
        Carbon::serializeUsing(function ($carbon) {
            return $carbon->toIso8601String();
        });
}
```
The response is writen like:

```php
//Controller
function getCompanyData(Request $request) {

    $company = Company::find(1);

    return response()->json(['success' => 1, 'data' => $company]);

}

//model
class Company extends Model
{
    protected $dates = ['created_at', 'updated_at', 'deleted_at'];
    ...
}
```

And the result is:

```javascript
{
    "success": 1,
    "data": {
        "id": 1,
        "name": "Test Company",
        "cash_balance": "0.00",
        "bank_balance": "600.69",
        "logo_image_name": "ih/5iqqmvfdtq4txyfj71clxurakiaakcogw4kt0jwfckc4hjlnw",
        "created_at": "2018-04-01 22:38:01", /* Not the ISO format! */
        "updated_at": "2018-04-03 21:02:42", /* Not the ISO format! */
        "deleted_at": null
    }
}
```

**Comment by staudenmeir** [comment]
#21703
