### ISSUE TITLE
SendsPasswordResetEmails should pass Request to sendResetLinkResponse

### ISSUE THREAD

**Issue by thomasfw** [laravel/framework#23820]
- Laravel Version: 5.6
- PHP Version: 7.2

### Description:

I'm overriding the `SendsPasswordResetEmails` response methods in the default `ForgotPasswordController` in order to make it API friendly (it doesn't respond with JSON by default, it just redirects back to the original page.

The `sendResetLinkEmail()`method  passes the Request instance to `sendResetLinkFailedResponse()`, so I can check the request and return an appropriate response ...

https://github.com/laravel/framework/blob/5.6/src/Illuminate/Foundation/Auth/SendsPasswordResetEmails.php#L71

```php
protected function sendResetLinkFailedResponse(Request $request, $response)
{
	if ( $request->expectsJson() ) // ...
}
```

However the Request is not passed to `sendResetLinkResponse()`, for what looks like no good reason.

```php
protected function sendResetLinkResponse($response)
{
	// No request to check...
}
```

https://github.com/laravel/framework/blob/5.6/src/Illuminate/Foundation/Auth/SendsPasswordResetEmails.php#L59

For consistency, and to prevent the need to also override `sendResetLinkEmail()` to make this work, Request should be passed to `sendResetLinkResponse`. Or better yet, the Trait should be updated to return a json formatted response when appropriate (I notice that the docblocks suggest a '\Illuminate\Http\JsonResponse' can be returned, but this doesn't seem to be the case even when my request has the `Accept: application/json` header).

### Steps To Reproduce:

See above

**Comment by tillkruss** [comment]
This repo is for bug reports only. Please submit a PR or discuss this in laravel/internals.
