### ISSUE TITLE
Mailer does not render plain text mails

### ISSUE THREAD

**Issue by mbaierl** [laravel/framework#23822]
If there is a Mailable that has only a plain text view rendering fails.

Here is the Mailable:
```
class MessageToUserMail extends Mailable {
...
public function build()
    {
		return $this->text('emails.message-to-user');
    }
```

Here is the Controller code:
```
public function mailTests()
	{
		$mail = new MessageToUserMail();
		return $mail->render();
	}
```

The result is a "**View [] not found.**" exception.

Expected result would be the plain text of the mail rendered in the browser.

**Comment by leadegroot** [comment]
See https://github.com/laravel/ideas/issues/1058 - recently noticed bug

**Comment by mbaierl** [comment]
Yeah, it seems to be the same issue.
