### ISSUE TITLE
Pass additional parameter to API Resource

### ISSUE THREAD

**Issue by yanhao-li** [laravel/framework#23826]
- Laravel Version: 5.5
- PHP Version: 5.7
- Database Driver & Version:

### Description:
What if my api resource class need additional parameters besides the resource itself, from outside like caller controller class? How could I pass parameter to the api resource class(both single resource and resource collection), should I declare a new Json Resource class to extends?

Any comments or solutions are welcome, Thank you in advance!

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I suggest closing your issue ticket here? Instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.

**Comment by fourstacks** [comment]
@yanhao-li This is very much possible - you just have to overload the constructor of the Resource you want to pass extra params to e.g.

```

class PostResource extends Resource
{
    /**
     * @var
     */
    private $foo;

    /**
     * Create a new resource instance.
     *
     * @param  mixed  $resource
     * @return void
     */
    public function __construct($resource, $foo)
    {
        // Ensure you call the parent constructor
        parent::__construct($resource);
        $this->resource = $resource;
        
        $this->foo = $foo;
    }

    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'title' => $this->title,
            'foo' => $this->foo
        ];
    }
}

```

Then you can add the params to your resource like so:

```
return new PostResource($post, 'my variable');
```

Hope that helps

**Comment by yanhao-li** [comment]
@fourstacks Informative, thank you very much sir

**Comment by irfan88** [comment]
@yanhao-li i have some issue.

**Comment by lokielse** [comment]
This is my approach.

```php
class UserResource extends Resource{

    protected $foo;

    public function foo($value){
        $this->foo = $value;
        return $this;
    }
       
    public function toArray($request){
        return [
            'id' => $this->id,
            'name' => $this->name,
            'foo' => $this->foo,
         ];
    }

    public static function collection($resource){
        return new UserResourceCollection($resource);
    }
}
```
```php
class UserResourceCollection extends ResourceCollection{

    protected $foo;

    public function foo($value){
        $this->foo = $value;
        return $this;
    }
       
    public function toArray($request){
        return $this->collection->map(function(UserResource $resource) use($request){
            return $resource->foo($this->foo)->toArray($request);
        })->all();

        // or use HigherOrderCollectionProxy
        // return $this->collection->map->foo($this->foo)->map->toArray($request)->all()
    }
}
```

```php
(new UserResource($user))->foo('bar');
(new UserResourceCollection($user))->foo('bar');

UserResource::make($user)->foo('bar');
UserResource::collection($users)->foo('bar');
```

Any good idea?

**Comment by MovingGifts** [comment]
@yanhao-li Did you ever figure this out?

**Comment by warren32** [comment]
Why not override the constructor in the ResourceCollection class instead of the Resource class and use Resource Collections instead (https://laravel.com/docs/5.6/eloquent-resources#generating-resources)?

For example, you could create a new ResourceCollection class

```
php artisan make:resource NoteCollection
```
The above command will create a `NoteCollection` for you to use in the /resources folder.  Inside this class, just override the constructor with parameters you want to pass in:
```
class NoteCollection extends ResourceCollection
{
    protected $user;
    /**
     * Create a new resource instance.
     *
     * @param  mixed  $resource
     * @return void
     */
    public function __construct($resource, User $user = null)
    {
        $this->user = $user;

        parent::__construct($resource);
    }
    /**
     * Transform the resource collection into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'data' => $this->collection->map(function($n){
                return [
                    'note' => $n->note,
                    'public' => $this->when($this->user->isAwesome(),'secret'),
                    'created_at' => $n->created_at->timestamp,
                    'updated_at' => $n->updated_at->timestamp
                ];
            })
        ];
    }
}
```

**Comment by PaddyLock** [comment]
> Why not override the constructor in the ResourceCollection class instead of the Resource class and use Resource Collections instead (https://laravel.com/docs/5.6/eloquent-resources#generating-resources)?
> 
> For example, you could create a new ResourceCollection class
> 
> ```
> php artisan make:resource NoteCollection
> ```
> The above command will create a `NoteCollection` for you to use in the /resources folder. Inside this class, just override the constructor with parameters you want to pass in:
> 
> ```
> class NoteCollection extends ResourceCollection
> {
>     protected $user;
>     /**
>      * Create a new resource instance.
>      *
>      * @param  mixed  $resource
>      * @return void
>      */
>     public function __construct($resource, User $user = null)
>     {
>         $this->user = $user;
> 
>         parent::__construct($resource);
>     }
>     /**
>      * Transform the resource collection into an array.
>      *
>      * @param  \Illuminate\Http\Request  $request
>      * @return array
>      */
>     public function toArray($request)
>     {
>         return [
>             'data' => $this->collection->map(function($n){
>                 return [
>                     'note' => $n->note,
>                     'public' => $this->when($this->user->isAwesome(),'secret'),
>                     'created_at' => $n->created_at->timestamp,
>                     'updated_at' => $n->updated_at->timestamp
>                 ];
>             })
>         ];
>     }
> }
> ```

I tried this with typehinting to inject a service and it doesn't work. Error is it expects two arguments and only 1 given. How to inject a service into a Resource collection?

**Comment by Almusamim** [comment]
> @yanhao-li Did you ever figure this out?
> @lokielse I see this works, but is repeating code, is there any better way anyone? Ideally passing from the constructor like @fourstacks solution but for a collection. Any better way to solve this?

did you solve this somehow?

**Comment by MovingGifts** [comment]
@Almusamim Nope, just went with @lokielse solution as it worked and it was taking too long to figure out another way.

**Comment by GuntherDebrauwer** [comment]
I created a pull request that adds a function to pass extra data to an API resource: https://github.com/laravel/framework/pull/28358

**Comment by alkin** [comment]
I am using another solution. Its definitely not the best one but since taylor already declined your pull request i would like to give my answer to this problem.

I extended the JsonResource and added a static variable named using:

```php
<?php

namespace App\Responses;

use Illuminate\Http\Resources\Json\JsonResource as BaseResource;

class JsonResource extends BaseResource
{
    protected static $using = [];

    public static function using($using = [])
    {
        static::$using = $using;
    }
}
```

Now if you use this JsonResource in your Resource you may set this variable by calling: 

```php
MyResource::using(['my_extra_data' => 123]);
MyResource::collection($resources);
```

and in your Resource:

```php
$this->merge(static::$using)
```

**Comment by quangtran1357** [comment]
Hi @alkin ,
your solution is good but it can only be applied with 1 fixed variable, if each resource returned in Resource::collection needs a variable containing different values, your method cannot be used.
Can you fix it?

**Comment by AmrAlmagic** [comment]
> This is my approach.
> 
> ```
> class UserResource extends Resource{
> 
>     protected $foo;
> 
>     public function foo($value){
>         $this->foo = $value;
>         return $this;
>     }
>        
>     public function toArray($request){
>         return [
>             'id' => $this->id,
>             'name' => $this->name,
>             'foo' => $this->foo,
>          ];
>     }
> 
>     public static function collection($resource){
>         return new UserResourceCollection($resource);
>     }
> }
> ```
> 
> ```
> class UserResourceCollection extends ResourceCollection{
> 
>     protected $foo;
> 
>     public function foo($value){
>         $this->foo = $value;
>         return $this;
>     }
>        
>     public function toArray($request){
>         return $this->collection->map(function(UserResource $resource) use($request){
>             return $resource->foo($this->foo)->toArray($request);
>         })->all();
> 
>         // or use HigherOrderCollectionProxy
>         // return $this->collection->each->foo($this->foo)->map->toArray($request)->all()
> 
>         // or simple
>         // $this->collection->each->foo($this->foo);
>         // return parent::toArray($request);
>     }
> }
> ```
> 
> ```
> (new UserResource($user))->foo('bar');
> (new UserResourceCollection($user))->foo('bar');
> 
> UserResource::make($user)->foo('bar');
> UserResourceCollection::make($users)->foo('bar');
> UserResource::collection($users)->foo('bar');
> ```
> 
> Any good idea?

thanks, your solution works with me

**Comment by FMagnanWD** [comment]
You can use this method.
`<?php

namespace App\Http\Resources;

use App\Http\Resources\Child as ChildResource;
use App\Http\Resources\Event as EventResource;
use Illuminate\Http\Resources\Json\JsonResource;

class School extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'name' => $this->name,
            'events' => $this->when(request()->get('events'), function () {
                return EventResource::collection($this->events);
            }),
            'children' => $this->when(request()->get('children'), function () {
                return ChildResource::collection($this->children);
            }),
        ];
    }
}
`

**Comment by BenoitDesrosiers** [comment]
what about "hacking" the request:
$request->request->add(['foo' => 'foovalue']);

**Comment by dhufish** [comment]
@BenoitDesrosiers - thanks for sharing that.  It's not the ideal solution but it is a necessary requirement for the framework.  

In my case I am passing an array of fields into the resource that is used to dynamically format the array.  I call this resource from many different models to build arrays for datatables and want to control the scope of array flowing back to the browser.  

I tried to pass this array (of fields I want to display) to the Eloquent select however I have Accessors in some models and these alias fields can't be used in the Eloquent select, so trimming at the toArray stage was vital.

**Comment by marknuyens** [comment]
> @yanhao-li This is very much possible - you just have to overload the constructor of the Resource you want to pass extra params to e.g.
> 
> ```
> 
> class PostResource extends Resource
> {
>     /**
>      * @var
>      */
>     private $foo;
> 
>     /**
>      * Create a new resource instance.
>      *
>      * @param  mixed  $resource
>      * @return void
>      */
>     public function __construct($resource, $foo)
>     {
>         // Ensure you call the parent constructor
>         parent::__construct($resource);
>         $this->resource = $resource;
>         
>         $this->foo = $foo;
>     }
> 
>     /**
>      * Transform the resource into an array.
>      *
>      * @param  \Illuminate\Http\Request
>      * @return array
>      */
>     public function toArray($request)
>     {
>         return [
>             'title' => $this->title,
>             'foo' => $this->foo
>         ];
>     }
> }
> ```
> 
> Then you can add the params to your resource like so:
> 
> ```
> return new PostResource($post, 'my variable');
> ```
> 
> Hope that helps

Thanks, I think this is the best solution and probably the reason no special method for "importing parameters" was introduced. Anyway, for those who want to optimize their code in PHP 8, the following would work as well:

```php
/**
* Create a new resource instance.
*
* @param  mixed  $resource
* @param  mixed  $foo
* @return void
*/
public function __construct(public $resource, protected $foo)
{
     parent::__construct($resource);
}
```

**Comment by sushansht** [comment]
return new PostResource($post')->with('username' , 'sushansht');

**Comment by budimanfajarf** [comment]
> what about "hacking" the request: $request->request->add(['foo' => 'foovalue']);

I do the "hacking" request, thanks @BenoitDesrosiers

It's my approach

Controller : 
```php
        //...
        request()->request->add([
            'extra_data' => [
                'foo' => 'foo-value',
                'other' => 'something',
            ],
        ]);
        // ...
```

Resource : 
```php
        // ...
        'bar' => $this->when(array_key_exists('foo', request()->get('extra_data') ?? []), function () {
            $foo = request()->get('extra_data')['foo'];

            // do some logic or just return the value
            return $foo;

            // or return using a resource if the $foo is an instance of a model
            return $foo
                ? (new FooResource($foo))
                : null;
        }),
        // ...
```

The `bar` will be shown if the `foo` key exists in the `extra_data` array from request, even if the value of `foo` is `null`, the `bar` still showed as I expected. It can be used in a single resource or resource collection.

**Comment by Sudheer121** [comment]
It can be much simpler, you add a public set method in the resource and don't pass it in the constructor.

```php
class PostResource extends Resource
{
    private Type|null $foo;

    public function setFoo(?Type $foo): self
    {
        $this->foo = $foo;
        return $this;
    }

    public function toArray()
    {
       return [ 
         'title' => $this->title,
        'foo'  => $foo // do any manipulations on foo here
       ];
    }
}
```

When you want to return the resource
```php
return new PostResource($post)->setFoo('I love Laravel');
```

This approach doesn't involve a constructor and hence works with PostResourceCollection too.

**Comment by marknuyens** [comment]
> It can be much simpler, you add a public set method in the resource and don't pass it in the constructor.
> 
> ```
> class PostResource extends Resource
> {
>     private ?Type $foo;
> 
>     public function setFoo(?Type $foo): self
>     {
>         $this->foo = $foo;
>         return $this;
>     }
> 
>     public function toArray()
>     {
>        return [ 
>          'title' => $this->title,
>          'foo'  => $this->foo // do any manipulations on foo here
>        ];
>     }
> }
> ```
> 
> When you want to return the resource
> 
> ```
> return (new PostResource($post))->setFoo('I love Laravel');
> ```
> 
> This approach (although a bit unconventional) doesn't involve a constructor and hence works with PostResourceCollection too.

Personally I wouldn't agree on the elegance of this method. Especially since it breaks whenever you're building a `resource collection` and it makes use of the given `resource` as its `collects` parameter.

Currently I have solves this problem by adding the following method to my `resource collection` class:

```php
    /**
     * Create a new resource instance.
     *
     * @param  mixed  $resource
     * @param  ?Type  $foo
     * @return void
     */
    public function __construct($resource, protected Type $foo)
    {
        parent::__construct($resource);
    }

     /**
     * Transform the resource collection into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        return $this->collection
            ->transform(fn ($item) => $item::make($item->resource, $this->foo))
            ->toArray();
    }
```

And the following to my `resource` class:

```php

     /**
     * Create a new resource instance.
     *
     * @param  mixed  $resource
     * @param  ?Type  $foo
     * @return void
     */
    public function __construct($resource, protected Type $foo)
    {
        parent::__construct($resource);
    }
``

**Comment by Sudheer121** [comment]
@marknuyens I guess it depends on the use case.
In my case, the passed `$foo` is only relevant when we think about the PostResource individually. 

My exact use-case: This resource(here PostResource) is nested under a parent resource and the parent resource is passing the `$foo` to the child resource. Hence the $foo isn't relevant in the context of a resource collection in this case.

Also, it doesn't break the resource collection because the resource collection is very specific to the resource.

```php
class PostCollection extends ResourceCollection
{
    /**
     * The resource that this resource collects.
     *
     * @var string
     */
    public $collects = PostResource::class;

    /**
     * Transform the resource collection into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        return ['data' => $this->collection];
    }
}
```
This is in context to Laravel 8.x.

**Comment by marknuyens** [comment]
@Sudheer121 But what happens when that `PostCollection` is instantiated, it will not be aware of $foo, right? How would the `setFoo()` method be used in that case? That's the thing I considered to be challenging when I first faced this scenario.

**Comment by Sudheer121** [comment]
@marknuyens handling of ResourceCollection would be like this 

We just need to modify the `toArray()` method and add optional parameter in the constructor
```php
class PostResourceCollection extends ResourceCollection
{

    public function __construct($resource, private ?FooType $foo = null)
    {
        parent::__construct($resource);
    }

    /**
     * The resource that this resource collects.
     *
     * @var string
     */
    public $collects = Post::class;

    /**
     * Transform the resource collection into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        return ['data' => $this->collection->map(
         fn (PostResource $postResource) => $postResource->setFoo($this->foo)
        )];
    }
}
```

Usage
```php
$collection = new PortResourceCollection($model)
// or
$collection = new PortResourceCollection($model, $foo)
```

**Comment by Sudheer121** [comment]
In short, using [this](https://github.com/laravel/framework/issues/23826#issuecomment-1306937101) approach when defining the resource and [this](https://github.com/laravel/framework/issues/23826#issuecomment-1309096521) approach when defining the resourceCollection would do.


```
Note: This is in context to Laravel 8.x
```

**Comment by sajadsoft1** [comment]
i create this and work perfect for me
first create a custom JsonResource
AdditionalResource.php

`<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\AnonymousResourceCollection;
use Illuminate\Http\Resources\Json\JsonResource;

class AdditionalResource extends JsonResource
{
    public static $extra_additional = [];

    public function setAdditional($value)
    {
        self::$extra_additional = $value;
        $this->additional($value);
        return $this;
    }

    public static function additionalCollection($resource, $data): AnonymousResourceCollection
    {
        self::$extra_additional = $data;
        return parent::collection($resource);
    }

}
`

an use in controller for one item or collection
`YourResource::additionalCollection($items, ['extra_attributes' => 25])`
`YourResource::make($item)->setAdditional(['extra_attributes',25]);`

**Comment by gregordrebes** [comment]
My approach is a little close to what @sajadsoft1 done [here](https://github.com/laravel/framework/issues/23826#issuecomment-1322800021).

I add a `protected static $attribute` to my resource class.

Then I override `make()` and `collection()` methods.

Something just like this (`UserResource` extracted from [docs](https://laravel.com/docs/9.x/eloquent-resources#concept-overview))

```php
<?php
 
namespace App\Http\Resources;
 
use Illuminate\Http\Resources\Json\JsonResource;
 
class UserResource extends JsonResource
{
	protected static $short;
	
	public static function make(...$parameters)
	{
		$resource = $parameters["resource"] ?? $parameters[0];
		self::$short = $parameters["short"] ?? $parameters[1] ?? null;
		return parent::make($resource);
	}
	
	public static function collection(...$parameters)
	{
		$resource = $parameters["resource"] ?? $parameters[0];
		self::$short = $parameters["short"] ?? $parameters[1] ?? null;
		return parent::collection($resource);
	}
	
	public function toArray($request)
	{
		return [
			'id' => $this->id,
			'name' => $this->name,
			'email' => $this->email,
			$this->mergeWhen(!self::$short, [
				'created_at' => $this->created_at,
				'updated_at' => $this->updated_at,
			]),
		];
	}
}
```

**Comment by nathandaly** [comment]
`TeamsAuthController.php`
```php
return new TeamsAuthResource([
    'user' => $user,
    'token' => $token,
]);
```

`TeamsAuthResource.php`
```php
<?php

declare(strict_types=1);

namespace App\Http\Resources;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class TeamsAuthResource extends JsonResource
{
    /**
     * @param Request $request
     * @return array<string, mixed>
     */
    public function toArray($request): array
    {
        return [
            'success' => true,
            'user' => [
                'uuid' => $this->resource['user']->uuid,
                'display_name' => $this->resource['user']->display_name,
                'email' => $this->resource['user']->email,
                'created_at' => $this->resource['user']->created_at,
            ],
            'token' => [
                'abilities' => $this->resource['token']->accessToken->abilities,
                'accessToken' =>  $this->resource['token']->plainTextToken,
                'expires_at' => $this->resource['token']->accessToken->expires_at
            ],
        ];
    }
}
```

**Comment by gregordrebes** [comment]
@nathandaly great approach, and I think it work great w/ `::make()` too. 
I didn't try wet, but is a good way to solve the 'problem'.
But I don't know about using it with `::collection()`, because it is a collection of many models/data/objects, etc. Only if going through every item of collection and mapping/adding. Or maybe there's another possibility that Idk.

**Comment by mdinopol** [comment]
Why not just merge new input field in the controller, then access the request in the resource class, like this:

**Controller:**
```
public function index()
{
    request()->merge(['additional_data' => 'some_value']);
    
    return new YourResource::collection(Model::all());
}
```

**YourResource:**

```
class YourResource extends JsonResource
{
    public function toArray($request)
    {
         $request->additional_data;
    }
}
```
