### ISSUE TITLE
The page isn’t redirecting properly laravel

### ISSUE THREAD

**Issue by Akashverma11** [laravel/framework#23834]
- Laravel Version: 5.4
- PHP Version: 7.0
- Database Driver & Version:mysql

### Description:
I have facing problem with redirect in middleware, where all other conditions are working well, but the first condition where i check the variable $check_exp_grace, is not working properly. I need to redirect the dashboard page if $check_exp_grace == "fail". I keep the dashboard function in middleware in web.php

### Steps To Reproduce:
My Middleware code

$check_exp_grace="fail";
        $current_date = date('Y-m-d');

    if($about_pemission['plan_expiry_date'] >=$current_date){
        $check_exp_grace = "success";
    }else{
        if($about_pemission['grace_period']=='yes' && $about_pemission['grace_period_date'] >=$current_date){
          $check_exp_grace = "success";  
        }
    }
    if($check_exp_grace == "success" && str_contains($request->url(),['business/aboutMe'])){
            if(isset($about_pemission) && !empty($about_pemission) && $about_pemission != null){
                
                if(Auth::guard('business')->check() && str_contains($request->url(),['business/aboutMe/about']) && !str_contains($request->url(),['business/aboutMe/permissions'])){
                    // dd($request->url());
                    if($about_pemission['about_me_about'] == "no"){
                      return redirect('business/dashboard');
                    }
                }
               
                if(Auth::guard('business')->check() && !str_contains($request->url(),['business/aboutMe/permissions']) && str_contains($request->url(),['business/aboutMe/headOffice'])){
                    if($about_pemission['about_me_head_office'] == "no"){
                        return redirect('business/dashboard');
                    }
                }
                if(Auth::guard('business')->check() && !str_contains($request->url(),['business/aboutMe/permissions']) && str_contains($request->url(),['business/aboutMe/branch/add','business/aboutMe/branches/view','business/aboutMe/branch/edit'])){
                    if($about_pemission['about_me_branches'] == "no"){
                        return redirect('business/dashboard');
                    }
                }
            }
            return $next($request);
        }
        else if($check_exp_grace == "fail"){
            return redirect('business/dashboard');
        }    
    }

In web.php

Route::group(['middleware'=>'business'],function(){
        Route::match(['get','post'],'business/dashboard','BusinessController@business_dashboard');
    )};

And the output is

![screenshot-localhost-2018-04-09-15-27-16](https://user-images.githubusercontent.com/35398180/38491837-b0bf3a98-3c0a-11e8-91b3-aecd3a4292c8.png)

**Comment by laurencei** [comment]
If the setting is `false` then you never `return $next($request);`

So add that to the end of your function as a final catch.
