### ISSUE TITLE
can i use follow style of validate message?

### ISSUE THREAD

**Issue by huaiguoguo** [laravel/framework#23835]
- Laravel Version: #.#.# 5.6
- PHP Version: 7.2.3
- Database Driver & Version: mysql 5.7

### Description:
can i use follow style ?

![image](https://user-images.githubusercontent.com/1888094/38501316-43b110a4-3c3f-11e8-8db4-b4a6642a6217.png)

if i have 10 fields to verify,  evey filed have 3 verify,
i need to write 30 lines.......

like this:

![image](https://user-images.githubusercontent.com/1888094/38501740-44224ffc-3c40-11e8-976e-5fd7509091ae.png)

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I suggest closing your issue ticket here? Instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.
