### ISSUE TITLE
[Eloquent] Use a specific format only for JSON serialization

### ISSUE THREAD

**Issue by luizpinheiro** [laravel/framework#23836]
- Laravel Version: 5.6.15
- PHP Version: 7.2
- Database Driver & Version: 5.6

### Description:

Is it possible to define a cast format for JSON serialization **only**? 

For example, i have a `bank_balance` `DECIMAL(10,2)`  that stores the current bank balance of a company. It is automatically casted to `float` at runtime. I want to, when sending a JSON response from my API, cast that attribute to a specific format using `number_format()`. 

If i use Accessors, it casts the value of that attribute everytime it is accessed and not only when converting to json. I need that value to be `float` when manipulating it in the code, but to have a specific format when sending it in a JSON response.

**Comment by staudenmeir** [comment]
Take a look at API resources: https://laravel.com/docs/5.6/eloquent-resources

**Comment by luizpinheiro** [comment]
Like a charm!!!
