### ISSUE TITLE
LoadEnvironmentVariables.php

### ISSUE THREAD

**Issue by owenson** [laravel/framework#23845]
### Description:
Consider changing Dotenv()->load() to Dotenv()->overload() because when using various plugins with docker, e.g. redis and elasticsearch, the hostnames are defined in .env, but docker defines a global environment variable ELASTICSEARCH_HOST or REDIS_HOST which is in an incompatible format.

Took me 3-4 hours to trace this bug down!

**Comment by owenson** [comment]
Or atleast make this more easily debuggable.  Getting a dump from laravel saying csnt connect to http://elasticsearch:tcp://172.17.0.5. Is not very helpful for diagnosis.

I did have this problem about six months ago and i think ended up patching some other library as i couldn't work out the cause.

**Comment by tillkruss** [comment]
Please move this conversation to internals.
