### ISSUE TITLE
Rule::in not works on Windows (Chinese Simplified Version). str_getcsv function is locale related

### ISSUE THREAD

**Issue by ganlvtech** [laravel/framework#23842]
- Laravel Version: 5.5.36
- PHP Version: 7.2.2
- System Version: Windows 10 (1709) Chinese Simplified
- Code Page: 936 (GB2312)

### Description:

https://github.com/laravel/framework/blob/55b4efef29dd327af371ab35a016505f49ab1013/src/Illuminate/Validation/ValidationRuleParser.php#L257

`str_getcsv` have some problem with cp936 on Windows. In another word, UTF-8 character is not correctly decoded by `str_getcsv` on Windows if code page is wrong, and use UTF-8 as `str_getcsv` encoding is impossible because Windows not support UTF8 locale.

https://bugs.php.net/bug.php?id=72330

Everythins is OK on Ubuntu 16.04 with php 7.2.2.

### Steps To Reproduce:

```php
Route::get('test', function () {
    $result = [];
    $result[] = \Illuminate\Support\Facades\Validator::make([
        'tag' => '你好',
    ], [
        'tag' => \Illuminate\Validation\Rule::in('你好', '世界'),
    ])->passes();
    $result[] = \Illuminate\Support\Facades\Validator::make([
        'tag' => '你好',
    ], [
        'tag' => 'in:你好,世界',
    ])->passes();
    $result[] = \Illuminate\Support\Facades\Validator::make([
        'tag' => 'hello',
    ], [
        'tag' => \Illuminate\Validation\Rule::in('hello', 'world'),
    ])->passes();
    if (windows_os()) {
        $locale = setlocale(LC_CTYPE, 0);
        echo setlocale(LC_CTYPE, 'en-US');
    }
    $result[] = \Illuminate\Support\Facades\Validator::make([
        'tag' => '你好',
    ], [
        'tag' => \Illuminate\Validation\Rule::in('你好', '世界'),
    ])->passes();
    if (windows_os()) {
        setlocale(LC_CTYPE, $locale);
    }
    return $result;
});
```

### Expected Result:

```json
[true,true,true,true]
```

### Actual Result:

```json
[false,true,true,true]
```

**Comment by toohamster** [comment]
I also encountered this problem.
my php version is:
```
PHP 7.0.31 (cli) (built: Jul 18 2018 18:25:11) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
```
test code:
```
$validator = \Validator::make([
                'vv' => '身份证',
            ],[
                // 'vv' => 'in:' . join(',', \Human::constants('ID_TYPE')),
                'vv' => 'in:' . join(',', ['许x','寒稍等','消是']),
            ],[
                'vv'    =>'you ds ',
            ]);
        if($validator->fails()){//验证字段失败

        }
        dd($validator->errors());
```

**Comment by laurencei** [comment]
This looks like a bug/issue with PHP and not with Laravel?

If it is an issue specifically with Laravel let me know and I'll reopen the ticket.

**Comment by Yi-pixel** [comment]
> This looks like a bug/issue with PHP and not with Laravel?
> 
> If it is an issue specifically with Laravel let me know and I'll reopen the ticket.

@laurencei 

Yes, this problem comes from str_getcsv, because it will refer to the locale setting. In the Windows Simplified Chinese environment, this error will occur.

Appears only in PHP 7 or earlier.

**Windows Simplified Chinese:**
```bash
$ php -r "echo  setlocale(LC_ALL, 0);"
> LC_COLLATE=C;LC_CTYPE=Chinese (Simplified)_China.936;LC_MONETARY=C;LC_NUMERIC=C;LC_TIME=C
```

In other environments, typically `C`,(Much depends on your operating system's default locale settings.)

However, can we consider replacing this str_getcsv to write a custom parsing method. to avoid the impact caused by locale settings.

For example, ChatGPT gives such an implementation, which looks good.

```php
function user_str_getcsv($input, $delimiter = ',', $enclosure = '"', $escape = '\\')
{
    $output = array();
    $string = '';
    $quote = false;

    $strlen = mb_strlen($input);
    for ($i = 0; $i < $strlen; $i++) {
        $char = mb_substr($input, $i, 1);

        if ($char === $enclosure) {
            $quote = !$quote;
        } elseif (!$quote && (($char === $delimiter) || ($char === "\n"))) {
            $output[] = $string;
            $string = '';
            if ($char === "\n") {
                break;
            }
        } elseif ($char === $escape) {
            $i++;
            $string .= ($i < $strlen) ? mb_substr($input, $i, 1) : '';
        } else {
            $string .= $char;
        }
    }

    $output[] = $string;
    return $output;
}

```

Is this okay?
