### ISSUE TITLE
Polymorphic relationship counts

### ISSUE THREAD

**Issue by schajee** [laravel/framework#23851]
- Laravel Version: 5.5.34
- PHP Version: 7.2.0
- Database Driver & Version: mysql 5.7.21

### Description:
My comments table setup...
```
Schema::create('comments', function (Blueprint $table) {
    $table->increments('id');
    ...
    $table->unsignedInteger('commentable_id');
    $table->string('commentable_type');
    $table->timestamps();
});
```

The `comments` model: 
```
class Comment extends Model
{
    public function commentable()
    {
      return $this->morphTo();
    }
}
```
The `issues` that the comments can belong to...
```
class Issue extends Model
{
    public function comments()
    {
        return $this->morphMany('App\Comment', 'commentable');
    }
}
```
### Steps To Reproduce:
I need to know how many comments are there with each issue. 
```
return view('issues.index', [
    'issues' => Issue::withCount('comments')->latest()->paginate()
]);
```
My debug-bar shows the following query....
```
select `issues`.*, (
    select count(*) from `comments` 
    where `issues`.`id` = `comments`.`commentable_id` 
    and `comments`.`commentable_type` = 'App\Issue'
) as `comments_count` 
from `issues` 
order by `created_at` desc 
limit 15 offset 0
```
Which results in 0 comments against an issue, when there are some. 

The query when escaped on class name i.e. `App\\Issue` returns the correct count.

**Comment by staudenmeir** [comment]
It works for me.

Do the selected issues definitely have comments? How do you access `comments_count` in your view?

The (non-)escaping of the backslash isn't the cause. The query isn't actually executed the way the debug-bar shows it.

**Comment by schajee** [comment]
I actually ran the query on MySQL. 

![screen01](https://user-images.githubusercontent.com/166577/38665751-9f66cb14-3e56-11e8-80a3-cd47ce0f5060.png)

**Comment by schajee** [comment]
```
Collection {#1418 ▼
  #items: array:4 [▼
    0 => 0
    1 => 2
    2 => 0
    3 => 4
  ]
}
```

**Comment by schajee** [comment]
Closing issue. Turns out while the query is indeed displayed differently than executed, this was more of a coding mistake. I was calling `comment_count` instead of `comments_count`. My bad.
