### ISSUE TITLE
laravel doesn't convert empty string to null

### ISSUE THREAD

**Issue by farhadkb6868** [laravel/framework#23857]
Laravel 5.4 doesn't convert empty string like "" to null. For Example when I create a route like this

`Route::get('/string/trim' , function(){
   dd(request()->input('email'));
});`

and call this url:

`http://example.com/string/trim?email=`

I see empty string in output not null value.

In the app/Http/Kernel.php file these lines of code existed:

`protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
];`

**Comment by staudenmeir** [comment]
It works for me.

Check whether the `ConvertEmptyStringsToNull` middleware is used at all:
Put `dd($key, $value);` at the beginning of `ConvertEmptyStringsToNull::transform()`.

**Comment by farhadkb6868** [comment]
I do that and I realized that `dd($key, $value)` isn't used at all.
In the above example email parameter in query string doesn't dump.
What should I do for resolving this problem?

**Comment by farhadkb6868** [comment]
`ConvertEmptyStringToNull ` middleware convert empty string to null correctly. But in controllers when I dump an empty field like `dd($request->email)` I see empty string not null.

**Comment by farhadkb6868** [comment]
I realized that api routes works fine and empty string convert to null correctly. But empty string in web routes doesn't covert to null.
any idea?

**Comment by staudenmeir** [comment]
Do you use any custom middleware on the web routes?
Can you reproduce the issue on a fresh Laravel installation?

**Comment by amirhs712** [comment]
@staudenmeir @farhadkb6868 
Thanks, in my case a custom middleware was the cause of this issue.

**Comment by damms005** [comment]
> Do you use any custom middleware on the web routes?

Please does this mean that if I add a route definition like `Route::post(...)->middleware(...)`
, then the global middleware stack (defined in Kernel.php) which contains the `ConvertEmptyStringsToNull::class` middleware definition will not be applicable?

**Comment by amirhs712** [comment]
> > Do you use any custom middleware on the web routes?
> 
> Please does this mean that if I add a route definition like `Route::post(...)->middleware(...)`
> , then the global middleware stack (defined in Kernel.php) which contains the `ConvertEmptyStringsToNull::class` middleware definition will not be applicable?

No that's not correct, middlewares run in order, depending on your priorities, Laravel makes sure that every included middleware will run on the request (Unless the chain is interrupted and a response is returned by a middleware)
