### ISSUE TITLE
Cannot create a scope with function signature scopeValue

### ISSUE THREAD

**Issue by Hell4Ge** [laravel/framework#23861]
Using homestead:

- Laravel Version: 5.6
- PHP Version: 7.1
- Database Driver & Version: psql (PostgreSQL) 10.3 (Ubuntu 10.3-1.pgdg16.04+1)

### Description:
There is an error while running a scope that is named "Value", the exception code that appeared during migration:

PDOException::("SQLSTATE[42703]: Undefined column: 7 ERROR:  column "Firetruck" does not exist
LINE 1: select "Firetruck" from "car_dictionary" limit 1
               ^")
      /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Database/Connection.php:330

  2   PDOStatement::execute()
      /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Database/Connection.php:330

### Steps To Reproduce:
Make a table in database that structure is similar to

`CarDictionary: { cd_key, cd_value } `

Then within your `CarDictionary` model create a scope

`   public function scopeValue($query, $input) {
    	if(!empty($input)) {
    		return $query->where('cd_value', $input);
	    }
	    return $query;
    }`

Run the scope by executing `$dictPosition= CarDictionary::Value('Firetruck')->first();`

**Comment by 36864** [comment]
You can't expect a scope to work when there's already a function with the same name.
This is the same as trying to make a "scopeFind" or "scopeGet".

https://laravel.com/api/5.6/Illuminate/Database/Query/Builder.html#method_value

**Comment by Hell4Ge** [comment]
> You can't expect a scope to work when there's already a function with the same name.
> This is the same as trying to make a "scopeFind" or "scopeGet".

But I can expect a runtime exception that will tell me that I am trying to override a method

**Comment by tillkruss** [comment]
Feel free to submit a PR.
