### ISSUE TITLE
Kernel::terminate() isn't called when a FatalErrorException is thrown

### ISSUE THREAD

**Issue by railken** [laravel/framework#23868]
- Laravel Version: 5.6
- PHP Version: 7.1.10-1
- Database Driver & Version: irrelevant

### Description:
If a FatalErrorException is thrown, `Kernel::terminate()` and `Middleware::terminate()` won't be called.

I have a LoggerMiddleware that logs every request+response, this won't work with FatalErrorException.

Also a CorsMiddleware can't work properly with this error

### Steps To Reproduce:
Simply throw a FatalErrorException
```
ini_set('max_execution_time', 1); 
while(1);

```

**Comment by HSkogmo** [comment]
Also experiencing this with
- Laravel version: 5.5
- PHP version: 7.1.14

Noticed the issue while working on an API with CORS headers and middleware. Responses that caused a FatalErrorException would not append the headers in the response, while encountering an ErrorException did.

**Comment by thecrypticace** [comment]
Fatal errors are not catchable in the normal sense. Whoops (as well as Symfony Debug's exception handler) performs work using `register_shutdown_handler` to present fatal error information.

Example of being unable to catch the error:
```php
try {
  ini_set('max_execution_time', 1);
  set_error_handler(function() {
      var_dump("Caught in error handler");die;
  });
  while(1);
} catch (\Throwable $e) {
  var_dump("Caught in exception handler");die;
}
```

**Comment by railken** [comment]
I know that, but the kernel should be at least terminated when "shutdown error/error" occurs. Something like this:

```php
if ($exception instanceof \Symfony\Component\Debug\Exception\FatalErrorException) {
    $kernel = app(\Illuminate\Contracts\Http\Kernel::class);
    $kernel->terminate($request, $response);
} 
```
This piece of code works if is added in the App\Exceptions\Handler::render() method, but i don't think it's the best place to put this

**Comment by thecrypticace** [comment]
Right but you can't catch that error _at all_. Your if check would never run.

**Comment by thecrypticace** [comment]
Unless you manually construct a `FatalErrorException` yourself.

**Comment by railken** [comment]
It's already handled here [Illuminate/Foundation/Bootstrap/HandleExceptions](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php#L38)
