### ISSUE TITLE
[5.5+] Non Documented Breaking Change on dispatch() helper

### ISSUE THREAD

**Issue by dbpolito** [laravel/framework#23866]
- Laravel Version: 5.5+
- PHP Version: irrelevant
- Database Driver & Version: irrelevant

### Description:

The behavior changed here: https://github.com/laravel/framework/commit/91f535704d4f6cff5e8393825dbdf46965234fa3#diff-12ace36c0bee81cc87f38273d5fe2a07R376

The previous behavior, it was directly calling `app(Dispatcher::class)->dispatch($this->job);`, which  if you are using the `Database Queue Driver`, it returns the `id` of the `jobs` table. (not sure about other drivers).

Now it's creating a `PendingDispatch` object, which only dispatches the job on `__destruct` (https://github.com/laravel/framework/blob/5.6/src/Illuminate/Foundation/Bus/PendingDispatch.php#L110-L113), so no way for getting the `id` from the `jobs` table using this helper anymore.

I thought about adding a way for early dispatching it, something like:

`src/Illuminate/Foundation/Bus/PendingDispatch.php`

````php
    /**
     * Dispatches the job.
     *
     * @return mixed
     */
    public function dispatch()
    {
        if (! $this->dispatched) {
            $this->dispatched = true;

            return app(Dispatcher::class)->dispatch($this->job);
        }
    }

    /**
     * Handle the object's destruction.
     *
     * @return void
     */
    public function __destruct()
    {
        $this->dispatch();
    }
````

But not sure it's a good solution... for now i'm going to call `app(Dispatcher::class)->dispatch($job)` directly on my code.

Another option would be add a second param here: https://github.com/laravel/framework/blob/5.6/src/Illuminate/Foundation/helpers.php#L381-L385

Like, `$pending = true`, or something like that.

**Comment by devcircus** [comment]
Documented in the 5.5 upgrade guide :
> The dispatch Helper

> If you would like to dispatch a job that runs immediately and returns a value from the handle method, you should use the dispatch_now or Bus::dispatchNow method to dispatch the job:
```php 
use Illuminate\Support\Facades\Bus;

$value = dispatch_now(new Job);

$value = Bus::dispatchNow(new Job);
```

There's also been several dispatchNow helpers added since, to make things even more simple.

**Comment by dbpolito** [comment]
Well, i saw this one but it's not very clear, and the old `dispatch()` doesn't do the same thing as  `dispatch_now()`, different things.
