### ISSUE TITLE
\File::files() do not return files in correct sorting anymore, it is working fine in laravel version 5.4

### ISSUE THREAD

**Issue by ajcastro** [laravel/framework#23883]
- Laravel Version: 5.5.*
- PHP Version: 7.0
- Database Driver & Version: any

### Description:
I have a menu files seeder and each file is a menu.
Before when I am using laravel 5.4, `$menuFiles = \File::files(base_path('database/seeds/menus/')')` return files in correct order but now in 5.5,  it is not sorted properly. the files are:

```
01_dashboard.php
02_branches.php
02_users.php
03_items.php
04_credit_plan_groups.php
04_customers.php
05_suppliers.php
06_transactions.php
08_account_ledgers.php
08_collections.php
08_remittances.php
09_check_stocks.php
09_inventory_report.php
09_inventory_summary.php
10_reorder_items_report.php
10_sales_report.php
11_serial_tracking.php
99_sys_config.php
```

Currently the workaround I did to fix this is:
```
$menuFiles = collect(File::files(__dir__.'/menus'))->sortBy(function ($file) {
            return $file->getBasename();
        })->all();
```

**Comment by staudenmeir** [comment]
This has been [fixed in 5.6](https://github.com/laravel/framework/pull/23387), but not yet in 5.5. I'll create a Pull Request.

**Comment by ajcastro** [comment]
Cool thanks!

**Comment by staudenmeir** [comment]
The backport to 5.5 was declined. You'll have to use the workaround until you upgrade to 5.6.

**Comment by ajcastro** [comment]
Why? 

I think they should accept the PR... because some devs will not just upgrade to 5.6
