### ISSUE TITLE
Eager loading won't work when `firstOrCreate()`

### ISSUE THREAD

**Issue by yaquawa** [laravel/framework#23886]
- Laravel Version: 5.6
- PHP Version: 7.2
- Database Driver & Version: mysql

### Description:

For example if I have a comment model like this
```php
class Comment extends Model
{
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

```

The following code won't get me a `user` model in the first place, I have to fetch it myself.
```php
$comment = Comment::with('user')->firstOrCreate([
            'user_id' => Auth::id(),
            'post_id' => $request->get('post_id'),
            'content' => $request->get('content')
        ]);



// `user` property not exists, 
// I have to fetch the `user` manually by calling `$comment->user`.
$comment->toJson();
```

**Comment by staudenmeir** [comment]
You can use `load()`:

    $comment = Comment::firstOrCreate(...)->load('user');

**Comment by staudenmeir** [comment]
Can you please close the issue?

**Comment by koAndy** [comment]
Or if you are like me, and using protected $with = [...] in models, for automatically eager loading multiple relationships, you could use fresh()

`$comment = Comment::firstOrCreate(...)->fresh()`

This will... refresh your model and load all relationships. 

Anyway, not a real issue but I would consider this an inconsistency of Laravel Framework.
