### ISSUE TITLE
Eloqment how to use JOIN for relations?

### ISSUE THREAD

**Issue by JILeXanDR** [laravel/framework#23905]
- Lavavel 5.6.

**I have 2 problems with Eloqment**

1. Eloqment CAN NOT do JOINS but return data structure with nested relations
2. Eloqment CAN do JOINS but can not return data structure with nested relations

**Let's say I want to retrieve all users with their profiles.**

Model is:
```
// User.php
 public function profile()
 {
    return $this->belongsTo(Profile::class, 'profile_id', 'id');
}
```

And code `User::with('profile')->get();` will execute 2 queries: **(problem №1)**

```
[2018-04-16 18:34:44] local.DEBUG: select * from "users" where ("login" = ?) limit 1 [0.01152]  
[2018-04-16 18:34:44] local.DEBUG: select * from "profiles" where "profiles"."id" in (?) [0.00083]
```

But in result I have nice structure with nested relation.
```
{
    "id": 1,
    "registered_at": "some date here"
    ....
    "profile": {
        "id": "1"
        "email": "some email here"
        ...
    }
}
```

I can replace Eloqment's `with` using this code:

```
DB::table('users')
    ->select(['users.*', 'locations.*'])
    ->join('profiles', 'users.profile_id', '=', 'profiles.id')
    ->get();
```
and it executes query with JOIN. Unfortunately in this case I have another structure  **(problem №2)**  and there is no nested "Profile" data and it is sadly... 
```
{
    "id": 1,
    "registered_at": "some date here"
    ....
    "email": "some email here"
    ....
    }
}
```

Is there way to fix it?

**Comment by JayBizzle** [comment]
Fix what? What is the problem with `User::with('profile')->get();`?

**Comment by JILeXanDR** [comment]
@JayBizzle Problem in 2 queries instead of 1 with JOIN.

**Comment by JayBizzle** [comment]
And why do you think 2 queries is an issue?

**Comment by JILeXanDR** [comment]
It is a question - why Eloqment can use JOIN and how to solve 1 or 2 problems

**Comment by JayBizzle** [comment]
Perhaps this will help answer your questions https://github.com/laravel/ideas/issues/668
