### ISSUE TITLE
[5.5] Transactions do not commit if a sub-transaction has started

### ISSUE THREAD

**Issue by gms8994** [laravel/framework#23902]
- Laravel Version: 5.5.40
- PHP Version: 7.1.16
- Database Driver & Version: MySQL 5.6.39

### Description:
Laravel does not commit transactions if a sub-transaction has begun, nor does it give the ability to commit only a specific sub-transaction

### Steps To Reproduce:
I have code that essentially looks like this:

```
DB::beginTransaction();
$this->doAThing();
DB::commit();

public function doAThing() {
  // Do something here
  Event::fire(new MyEvent($this->thing, $something));
}
```

```
class MyEventListener {
  public function handle($event)
    {
      DB::beginTransaction();
      // Do something here
      DB::commit();
    }
}
```

When all of my code finishes, a `ROLLBACK` is performed by the server because no `COMMIT` was actually run.

Because of the nature of [DB::commit](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Database/Concerns/ManagesTransactions.php#L148-L162), commits only happen if we're at the top-level transaction.

This is specifically a problem when using the `sync` QUEUE_DRIVER, but could cause issues elsewhere.

Looking at the code, I'm fairly certain that 5.6 would be affected by this as well.

**Comment by gms8994** [comment]
If transactions are not allowed to overlap, shouldn't a second call to `DB::beginTransaction()` trigger an error of some kind?

Currently, Laravel creates a SAVEPOINT if they're supported. But there's no way in code to say that I want to commit a savepoint, only roll one back.

**Comment by sisve** [comment]
Transactions are allowed to be nested, but not overlap. Perhaps I'm using the wrong word to explain it. Think of xml; you can have `<a><b></b></a>` but not `<a><b></a></b>`.

The logic is that all nested transactions must complete successfully to have the outer one succeed. Based on that, the nested transactions doesn't really do anything, if any of them fail the outer one will fail. They are however very nice to have to let any code act as if they do things transactional without having to check if there's an active transaction or not.
