### ISSUE TITLE
[5.5] route:clear route:cache error

### ISSUE THREAD

**Issue by dulumao** [laravel/framework#23907]
My native development environment uses php 7.1, online servers use 7.0, an error occurs when the command is called, my development machine is running normally

In Macroable.php line 96:

Method call does not exist.

**Comment by tillkruss** [comment]
Please post the full stack trace.

**Comment by dulumao** [comment]
@tillkruss 

[2018-04-17 13:47:01] local.ERROR: Method call does not exist. {"exception":"[object] (BadMethodCallException(code: 0): Method call does not exist. at /www/Laravel/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:96)
[stacktrace]
#0 /www/Laravel/modules/Scheduler/Provider.php(31): Illuminate\\Console\\Scheduling\\Event->__call('call', Array)
#1 [internal function]: Modules\\Scheduler\\Provider->Modules\\Scheduler\\{closure}(Object(Illuminate\\Foundation\\Application))
#2 /www/Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(831): call_user_func(Object(Closure), Object(Illuminate\\Foundation\\Application))
#3 /www/Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(780): Illuminate\\Foundation\\Application->fireAppCallbacks(Array)
#4 /www/Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#5 /www/Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#6 /www/Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(296): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#7 /www/Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(119): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#8 /www/Laravel/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 {main}
"}

**Comment by dulumao** [comment]
@tillkruss I found the cause of the error because I used Schedule  in the Provider and it caused a problem.
