### ISSUE TITLE
i cant run migrate

### ISSUE THREAD

**Issue by hosamalzagh** [laravel/framework#23922]
- Laravel Version:  Laravel Framework 5.6.16  
- Database Driver & Version:   mysql 5.7.19
---------------------------
PS D:\h\work\wamp64\www\laravel\newhob> php artisan migrate

   Illuminate\Database\QueryException  : could not find driver (SQL: select * from information_schema.tables where table_schema = newhob and table_name = migrations)

  at D:\h\work\wamp64\www\laravel\newhob\vendor\laravel\framework\src\Illuminate\Database\Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668|

  Exception trace:

  1   PDOException::("could not find driver")
      D:\h\work\wamp64\www\laravel\newhob\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:68

  2   PDO::__construct("mysql:host=127.0.0.1;port=3306;dbname=newhob", "root", "", [])
      D:\h\work\wamp64\www\laravel\newhob\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:68

  Please use the argument -v to see more details.

----------------------
i remove (;) extension=php_pdo_mysql.dll
and i tray this

use Illuminate\Support\Facades\Schema;

public function boot()
{
//
    Schema::defaultStringLength(191);
}

i get this error
In AppServiceProvider.php line 17:

  Class 'App\Providers\Schema' not found

**Comment by Fei77** [comment]
try adding `use Schema;` below namespace.

**Comment by hosamalzagh** [comment]
<?php

namespace App\Providers;
use Schema;
use Illuminate\Support\ServiceProvider;
----------------------------

   Illuminate\Database\QueryException  : could not find driver (SQL: select * from information_schema.tables where table_schema = newhob and table_name = migrations)

  at D:\h\work\wamp64\www\laravel\newhob\vendor\laravel\framework\src\Illuminate\Database\Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668|

  Exception trace:

  1   PDOException::("could not find driver")
      D:\h\work\wamp64\www\laravel\newhob\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:68

  2   PDO::__construct("mysql:host=127.0.0.1;port=3306;dbname=newhob", "h", "lamis170", [])
      D:\h\work\wamp64\www\laravel\newhob\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:68

  Please use the argument -v to see more details.

**Comment by staudenmeir** [comment]
What error do you get using `use Schema;`?

**Comment by hosamalzagh** [comment]
thanks you i can mack migrate now
i fix my error by change server and php ver

**Comment by amoredroid** [comment]
> thanks you i can mack migrate now
> i fix my error by change server and php ver

how do you change server and php version? :D
