### ISSUE TITLE
HasAttributes::hasChanges null attributes parameter detection

### ISSUE THREAD

**Issue by eidng8** [laravel/framework#23924]
- Laravel Version: 5.6.17
- PHP Version: 7.1

### Description:
The `hasChanges()` method checks for empty $attributes at entrance.

```php
        // If no specific attributes were provided, we will just see if the dirty array
        // already contains any attributes. If it does we will just return that this
        // count is greater than zero. Else, we need to check specific attributes.
        if (empty($attributes)) {
            return count($changes) > 0;
        }
```

However, functions like `isDirty()` and `wasChanged()` calls the method like these:

```php
    public function isDirty($attributes = null)
    {
        return $this->hasChanges(
            $this->getDirty(), is_array($attributes) ? $attributes : func_get_args()
        );
    }
```

```php
    public function wasChanged($attributes = null)
    {
        return $this->hasChanges(
            $this->getChanges(), is_array($attributes) ? $attributes : func_get_args()
        );
    }
```

When called through `isDirty()` like `$this->isDirty(null);`, `hasChanges()` receives the `$attributes` parameter as an array of `[null]` due to `is_array($attributes) ? $attributes : func_get_args()`. Which in turn skips right through the empty check and returns a faulty false.

### Steps To Reproduce:
Just call `$this->isDirty(null);` on any modified model instance.

**Comment by staudenmeir** [comment]
I'll fix it.

**Comment by 36864** [comment]
If anything, that's an argument for changing the default to `[]` rather than `null` just to avoid people thinking `null` is a valid parameter value.
