### ISSUE TITLE
Inverted order of Request Json response using Accept header

### ISSUE THREAD

**Issue by SaadeMotion** [laravel/framework#23928]
- Laravel Version: 5.5.*
- PHP Version: 7.1.14
- Database Driver & Version: Mysql 5.7.18

### Description:
Adding the Header: Accept: application/json to the request:

When i try:
`return response()->json(['foo' => 'bar'], 200)`
it gives me:
`200`

So, after trying, i get to the solution:
`return response()->json(200, ['foo' => 'bar'])`
So it gives me the correct:
`{"foo":"bar"}`

Why? It shouldn't be `request()->json(content, status_code)` ?? Why its inverted?

### Steps To Reproduce:
[Using postman or any other http library such as (axios, fetch, ajax)]

Add header: Accept: application/json
Simply return a json request `return request()->json()`

**Comment by devcircus** [comment]
As-is, calling the json() method will throw an exception if you invert the parameters, like: ```json($code, $content)```. The json() method of ResponseFactory defers to Illuminate\Http\JsonResponse, which defers to Symfony's HttpFoundation's JsonResponse, in which the constructor typehints the second parameter as an ```int```. So unless you've overwritten the ResponseFactory's json() method, you shouldn't even be able to call it with the parameters in the wrong order.
