### ISSUE TITLE
Implement a MailTransport ?

### ISSUE THREAD

**Issue by Grafikart** [laravel/framework#23937]
### Description:

SwiftMailer 6.X removed the MailTransport and Laravel can't use the `mail()` function to send mail. This makes Laravel incompatible with shared hosting (sendmail being unavailable since `proc_open` function is disabled). 

### Proposal

Laravel could implement a MailTransport for SwiftMailer that relies on `mail()` making the framework compatible with shared hosting that blocks `proc_open`. This mailer would be loaded inside the MailServiceProvider when driver is set to "mail".

### Problems

- `mail()` is considered insecure in some situations and enabling it could make Laravel insecure. 
- This is out of scope and such a MailTransport should be created by the user (not offered by the framework)

Feel free to close this issue if you think the problems are too important for this feature. An external package could also be created and referenced in the documentation.

**Comment by tillkruss** [comment]
You can still use any of the other transports on shared hosting.
