### ISSUE TITLE
[Request] Validation Rule for "Exists or Null"

### ISSUE THREAD

**Issue by LasseRafn** [laravel/framework#23931]
![screenshot 2018-04-18 21 37 28](https://user-images.githubusercontent.com/2689341/38953985-b8b152fc-4350-11e8-9c77-927c2aed2dbc.png)

### Description:

So, assume you have an API-like structure, where API-consumers can update singular fields in CRUD, like for example changing the customer of an order, without changing the order date.

Sure, that's quite easy: just look at which fields are included in the request and update.

**BUT** the problem occurs when you want to:
* Allow completely removing the customer from the order (allowing a null value to be set)
* Validate that customer exists (if not null)

You'd naively try `nullable` followed by `Rule::exists`, only to get an validation error thrown into your face stating that the customer does not exist, though you have set the value to `null`.

### Potential Solution:

For our project, I created a new Rule `ExistsOrNull` that basically acts as `Rule::exists` except it returns true if the `$value` is `null`, and skips the exists check.

Example:

``` php
public function passes( $attribute, $value ) {
	if ( $value === null || $value === 'null' ) {
		return true;
	}

	// Do exists-check here
}
```
*Added a gross hack to ensure that a "null" string is not treated as not-null.*

### Optimal solution

If `nullable` would somehow be able to bypass `Rule::exists`, it would be much cleaner and predictable (+ we avoid semi-duplicated rules)

### Comments?

Does anyone see the need for this to be moved into the framework, or is it too specific? Will gladly argue or explain my thoughts.

**Comment by staudenmeir** [comment]
Please use https://github.com/laravel/ideas for suggestions. Thanks!

**Comment by tillkruss** [comment]
If avoid using null as a string, would lead to confusion. I usually stick with 0 and 1.
