### ISSUE TITLE
No authentication issue for Custom HTTP Error pages.

### ISSUE THREAD

**Issue by abhishek6262** [laravel/framework#23939]
- Laravel Version: 5.6
- PHP Version: 7.1.3
- Database Driver & Version: MySQL

### Description:
Not being able to get authenticated user on Custom HTTP Error pages stored in "resources/views/errors/*" files For example: "404.blade.php".

**Comment by devcircus** [comment]
Yes. The session isn't available for these views. There are, however, ways to do this. See https://themsaid.com/laravel-55-better-404-response-20170921
