### ISSUE TITLE
Dispatching job right after Redis operations in another databse causes jobs to be pushed into that database

### ISSUE THREAD

**Issue by SapneshNaik** [laravel/framework#23936]
- Laravel Version: 5.5.35
- PHP Version: 7.0.28
- Database Driver & Version: redis-cli 4.0.8, predis/predis: "^1.1" 

### Description:

My project uses different Redis databases for different purposes. And I have noticed Laravel uses default database (0) for storing its queue related information when used with Redis driver. But If I dispatch a job to the queue right after doing some operations in a different Redis database, It causes the job ("queue:default") to be pushed into that database rather of than the default database 0.

This is how my Redis driver configuration looks like in queue.php
```javascript
        'redis' => [
            'driver' => 'redis',
            'connection' => 'default',
            'queue' => 'default',
            'retry_after' => 90,
            'database' => 0,
        ],
```

### Steps To Reproduce:

```php
	protected function pop($data)
	{
            //Select a Redis DB
             Redis::select(3);
	     //do some operations
             //Dispatch a job
             ProcessGroupActivationJob::dispatch($data, 'group_activation');
	}
```

**Comment by thecrypticace** [comment]
This is because you're actively changing the database of the Redis connection. I recommend adding another Redis connection when you want to use other databases.

This way you can do `Redis::connection("some_connection_name")->lpush(…)` and it doesn't affect the default Redis connection used by everything else.

**Comment by thecrypticace** [comment]
Additionally, as far as I'm aware this: `'database' => 0,` does not do anything in the queue config. You have to select the database when configuring Redis connections in `config/database.php`
