### ISSUE TITLE
Schema Builder: collaction() should be wrapped by quotes

### ISSUE THREAD

**Issue by rentalhost** [laravel/framework#23944]
- **Laravel Version:** 5.6.17 (lastest)
- **PHP Version:** 7.2.2 ZTS MSVC15 (Visual C++ 2017) x64
- **Database Driver & Version:** MariaDB 10.1.14

### Description:

Else, `->collection('binary')` could fails in some cases, because of the generated code is something like `addressable_type` varchar(255) collate binary not null` (the correct is `addressable_type` varchar(255) collate "binary" not null`).

~~I think that it should be applied to both: collaction and charset.~~

It affects MariaDB 10.1, but I don't know if it affects other DBMS and which versions.

I am not the best person to PR that, so if someone could do that, it will be very useful.

### Steps to reproduce

Full test case:

```php
Schema::create('addresses', function (Blueprint $blueprint) {
    $blueprint->string('addressable_type')->collation(static::COLLATION_BINARY);
});
```

Code generated:

```php
create table `platform_addresses` (`addressable_type` varchar(255) collate binary
  not null) default character set utf8mb4 collate utf8mb4_unicode_ci
```

Code manually fixed:

```php
create table `platform_addresses` (`addressable_type` varchar(255) collate "binary"
  not null) default character set utf8mb4 collate utf8mb4_unicode_ci
```

**Comment by staudenmeir** [comment]
Do you know a case where the charset doesn't work without quotes?

**Comment by rentalhost** [comment]
Both _charset_ and _collation_ supports `binary` as value. And _binary_ is a reserved word for both MySQL and MariaDB, at least. But, binary could be used as value for `character set` as-in, but for `collate` it should be wrapped.

The code below should works:

```php
Schema::create('example', function (Blueprint $blueprint) {
    $blueprint->collation = '"binary"'; // Need be wrapped!
    $blueprint->charset   = 'binary';   // Do not need be wrapped.

    $blueprint->increments('id');
});
```

Generated SQL (_beautified_):

```sql
create table `example` 
    (`id` int unsigned not null auto_increment primary key) 

default character set binary 
        collate "binary"
```
