### ISSUE TITLE
Model attribute's "links" will always be casted to strings.

### ISSUE THREAD

**Issue by tarreislam** [laravel/framework#23950]
- Laravel Version: 5.6.6

### Description:
When using the attribute `links` on an model it will always be returned as a string. I found this out because I have an model which `$casts` `links` to an `array`.

 [See example here (Imgur)](https://i.imgur.com/ZHtvxvo.png)

### Steps To Reproduce:
Take any model record and add \ replace the attribute `links` with anything.

**Comment by Quezler** [comment]
Could you share the code of the `wikipedia` object?

(the `->links` is purple while the `->somethingelsethanlinks` is orange, so i am assuming the code editor knows more than we do right now)

**Comment by tarreislam** [comment]
Its purple because phpstorm parses comments and highlights them.

```PHP
/**
 * @property Wikipedia wikipedia
 */
   public function __construct(Wikipedia $wikipedia)
    {
        $this->wikipedia = $wikipedia;
    }
```

```PHP
/**
 * @property array $links <-- this causes the purple text
*/
Class Wikipedia extends Model{}
```

**Comment by tarreislam** [comment]
Ok here is the problem. ZZZZ

```PHP
    public function getLinksAttribute($value)
    {
        if (!$value) {
            return [];
        }
        return $value;
    }
```
