### ISSUE TITLE
submitting a form redirect to exception page and says the following

### ISSUE THREAD

**Issue by AlamTheInnov** [laravel/framework#23953]
My Form:
<form method="POST" action="posts">
            @csrf
            <div class="form-group">
              <label for="title">Post Title</label>
              <input type="text" class="form-control" id="title" name="title"  placeholder="Enter email">
            </div>

            <div class="form-group">
              <label for="body">Post Body</label>
              <textarea class="form-control" id="body" name="body"></textarea>
              <small id="body" class="form-text text-muted">Post text should be greater than 100 characters</small>
            </div>

            <button type="submit" class="btn btn-primary">Publish</button>
          </form>

Laravel Storing data to Database:
public function store(){
		$post=new Post;

		$post->title=request('title');
		$post->body=request('body');

		$post->save();
		return redirect('/');
	}

Exceptions:
RuntimeException
Could not find resource 'js/zepto.min.js' in any resource paths.(searched: C:\wamp64\www\blog\vendor\filp\whoops\src\Whoops\Handler/../Resources)

in PrettyPageHandler.php (line 613)
--
at PrettyPageHandler->getResource('js/zepto.min.js')in PrettyPageHandler.php (line 170)
at PrettyPageHandler->handle(object(FatalThrowableError))in Run.php (line 272)
at Run->handleException(object(FatalThrowableError))in Handler.php (line 338)
at Handler->renderExceptionWithWhoops(object(FatalThrowableError))in Handler.php (line 317)
at Handler->renderExceptionContent(object(FatalThrowableError))in Handler.php (line 301)
at Handler->convertExceptionToResponse(object(FatalThrowableError))in Handler.php (line 280)
at Handler->prepareResponse(object(Request), object(FatalThrowableError))in Handler.php (line 187)
at Handler->render(object(Request), object(FatalThrowableError))in Handler.php (line 51)
at Handler->render(object(Request), object(FatalThrowableError))in Pipeline.php (line 83)
at Pipeline->handleException(object(Request), object(FatalThrowableError))in Pipeline.php (line 34)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in SubstituteBindings.php (line 41)
at SubstituteBindings->handle(object(Request), object(Closure))in Pipeline.php (line 149)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php (line 67)
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php (line 149)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 149)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 63)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 149)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php (line 37)
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php (line 149)

and son on what should i do please help!

**Comment by Quezler** [comment]
does your project have a `composer.lock`? if so, try deleting the `vendor` directory and then run `composer install`, my guess is that the error originated from a file that 'might' have been manually removed 🤔

**Comment by AlamTheInnov** [comment]
i solved the issue. 
Js folder was missing in my project inside  vendor\filp\whoops\src\Whoops\Resources\ and that js folder contain many js files plus this one zepto.min.js this one is important during inserting record :)

**Comment by hadrumkadhemkilani** [comment]
@AlamTheInnov  where can i find this js folder to download them ??

**Comment by AlamTheInnov** [comment]
sorry brother for late reply, are you facing the same problem?
