### ISSUE TITLE
Query Builder increment doesn't work when the value of the column is Null

### ISSUE THREAD

**Issue by KevinYY** [laravel/framework#23954]
- Laravel Version: 5.6.14
- PHP Version: 7.2
- Database Driver & Version: mysql  5.7.18

### Description:
There is a record of votes for null. And then call `DB::table('users')->where('id', 1)->increment('votes');` .
The votes still be null. Because `null + 1 = null` in mysql.

### solution:
I solved this by chang  https://github.com/laravel/framework/blob/5.6/src/Illuminate/Database/Query/Builder.php#L2397 to `$wrapped = 'coalesce('.$this->grammar->wrap($column).', 0)';`

I know that the field is nullable is not a good practice. But, maybe we can cover this situation by modify the code or give a bit of advice in the document

**Comment by tillkruss** [comment]
Set a default value of `0` on your columns.
