### ISSUE TITLE
Custom error messages for image dimensions.

### ISSUE THREAD

**Issue by WaqasBukhary** [laravel/framework#23969]
- Laravel Version: 5.2 onwards

### Description:

There are no custom messages for different types of errors in image [dimensions](https://laravel.com/docs/5.2/validation#rule-dimensions). 

All of them (min_width, max_width, min_height, max_height, width, height, ratio) give the same error.

### Steps To Reproduce:

Steps to reproduce are mentioned here.

https://stackoverflow.com/questions/47335447/custom-error-message-for-laravel-validation-rule-dimensions

https://laracasts.com/discuss/channels/laravel/dimension-validation

https://laracasts.com/discuss/channels/lumen/custom-error-messages-for-images

**Comment by ahinkle** [comment]
This would be a good place in [Laravel/Ideas](https://github.com/laravel/ideas).

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
