### ISSUE TITLE
[5.4] Feature Request: need toObject (stdClass array) like toArray in Collection & Model

### ISSUE THREAD

**Issue by vzool** [laravel/framework#23966]
- Laravel Version: 5.4.36
- PHP Version: 7.1
- Database Driver & Version: None

### Description:
This is a feature request.

### Steps To Reproduce:
None

**Comment by staudenmeir** [comment]
You can use this:

    (object) $model->toArray();

**Comment by vzool** [comment]
I tried that but with no luck, let me clarify my objective here.

Let's suppose there is an array generated after calling `toArray()` which will give us an output (normal array inside array) like this:

```php
// init array

>>> $x = [ 
	[
		"name" => "Aziz",
		"age" => 30,
	],
	[
		"name" => "Victor",
		"age" => 35,
	],
];

// check type

>>> gettype($x)
=> "array"

// convert array of arrays to object !!! [STRANGE]
// ...
// I don't know even how can I access this data structure, ha ha ha
// try it yourself :)

>>> $y = (object) $x
=> {#1261
     +0: [
       "name" => "Aziz",
       "age" => 30,
     ],
     +1: [
       "name" => "Victor",
       "age" => 35,
     ],
   }

// check type

>>> gettype($y)
=> "object"

```

My point is that I don't need to convert the paraent array into object, I need to convert children arrays to be `stdClass`, I know how to do that by looping through all children and convert every single one of them into `stdClass` with the following code:

```php
$z = [];
foreach($x as $v){
	$z[] = (object) $v;
}

// after converting children arrays to be `stdClass` and let parent to be an array

>>> gettype($z)
=> "array"
>>> gettype($z[0])
=> "object"
>>> $z[0]->name
=> "Aziz"

```

So, I'm looking for something in laravel give us a `stdClass` array output just like `toArray` direclty.

**Comment by crynobone** [comment]
```php
$users = App\User::all()->map(function ($user) {
  return (object) $user->toArray();
})->all();
```

**Comment by vzool** [comment]
It does work after a small correction:

```php
$users = App\User::get()->map(function ($user) {
  return (object) $user->toArray();
})->all();
```

So, it is `get()` not `all()`.
Because `get()` returns a `Collection` which has `map()` function, but `all()` is just dump all data in `array` format.

Thanks for you all <3

**Comment by vzool** [comment]
Yes, indeed it does.

I tried by the following:

```php
$x = City::limit(3)->all()->map(function($city){
	return (object) $city->toArray();
});
```

And `all()` after `limit()` does not return a `Collection`, ha ha ha
