### ISSUE TITLE
Default laravel's strict mode isn't compatible with MySQL 8.0 (NO_AUTO_CREATE_USERS)

### ISSUE THREAD

**Issue by nickaguilarh** [laravel/framework#23970]
- Laravel Version: 5.6.6
- PHP Version: 7.2
- Database Driver & Version: MySQL 8.0

### Description:
MySQL 8.0 removed "NO_AUTO_CREATE_USERS" mode, since it would be unnecessary because now we can't creare a user with GRANT, we must use CREATE USER.

This removal causes that, if we have strict mode enabled on database.php throw an error:
`
ERROR 1231 (42000):Variable 'character_set_client' can't be set to the value of 'NO_AUTO_CREATE_USERS'
`

Possible Solution:
Remove 'NO_AUTO_CREATE_USERS' from 
`
   /**
     * Get the query to enable strict mode.
     *
     * @return string
     */
    protected function strictMode()
    {
        return "set session sql_mode='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'";
    }
`
on MySQLConnector.php:171

I'm resolving this issue setting mysql model manually on database.php

### Steps To Reproduce:
Use a MySQL 8.0 database and do: php artisan migrate

**Comment by ntzm** [comment]
Try this? https://github.com/laravel/framework/issues/23961#issuecomment-383286151
