### ISSUE TITLE
field name doesn't have default value when i use factories in phpunit

### ISSUE THREAD

**Issue by farhadkb6868** [laravel/framework#23976]
When I use Factories in a test class in phpunit, field value doesn't insert into database.
It returns error
`General error: 1364 Field 'name' doesn't have a default value (SQL: insert into `province` () values ())`

My factory is:

```
use Faker\Generator as Faker;

$factory->define(\App\Provinces::class, function (Faker $faker) {
    return [
        'name' => $faker->name
    ];
});


```

**Comment by devcircus** [comment]
Is "name" fillable in your model?

**Comment by browner12** [comment]
Welcome to Laravel! We are glad to have you as part of the community.

Unfortunately GitHub is not an appropriate platform for general application issues. This is only for issues/bugs with the framework code itself.

Please close your issue, and instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

Laravel Slack (https://larachat.co/)
Laravel.io Forum (https://laravel.io/forum)
Laracasts Forum (https://laracasts.com/discuss)
StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks!
