### ISSUE TITLE
updateExistingPivot update multiple IDs with pivot

### ISSUE THREAD

**Issue by AEK-BKF** [laravel/framework#23971]
- Laravel Version: 5.6.16
- PHP Version: 7.2.4
- Database Driver & Version: Mysql 5.7.11

### Description:
Using updateExistingPivot to update multiple IDs with pivot in switch may make server late when we have too many rows

### Steps To Reproduce:
What I'm doing is :
```
$acceptedIDs = $specyear->userresults()->wherePivot('result', '>=', $specyear->admission)->pluck('user_id')->toArray();
foreach ($acceptedIDs as $userID) {
           $specyear->userresults()->updateExistingPivot($userID, ['admitted' => true]);
}
```
So is there any way to do like this in one query :

` $specyear->userresults()->updateExistingPivot($acceptedIDs, ['admitted' => true]);`

Thanks :)

**Comment by tillkruss** [comment]
Is this a question, or a bug?

**Comment by AEK-BKF** [comment]
Hi !
I said : 

> So is there any way to do like this in one query :
> 
> $specyear->userresults()->updateExistingPivot($acceptedIDs, ['admitted' => true]);

**Comment by tillkruss** [comment]
Please use this issue tracker only for reporting Laravel bugs.
