### ISSUE TITLE
Method Illuminate\Database\Eloquent\Collection::delete does not exist.

### ISSUE THREAD

**Issue by yaquawa** [laravel/framework#23985]
- Laravel Version: 5.6
- PHP Version: 7.2
- Database Driver & Version: mysql

### Description:

Providing a `delete` method to eloquent collection would be very helpful.

```php
User::where('in_black_list', true)->get()->delete();
```

**Comment by sisve** [comment]
`User::where(...)` doesn't return a Collection, but a Eloquent query builder. Is this really the entire code snippet required to reproduce the problem?

**Comment by yaquawa** [comment]
@sisve Sorry! I forgot the `get()` method.

**Comment by bonzai** [comment]
Just use `->each()`:

```php
User::where('in_black_list', true)->get()->each->delete();
```

**Comment by ntzm** [comment]
Or just `User::where('in_black_list', true)->delete()`

**Comment by JoseCage** [comment]
> ```
> User::where('in_black_list', true)->get()->each->delete();
> ```

Helpful.

Thanks for your help.
