### ISSUE TITLE
Page Expired .. Non persistance Session

### ISSUE THREAD

**Issue by mousa74hassan** [laravel/framework#23986]
I use file drive for session, but every time i reload page it generate a new session file.. It works fine on local .. This problem on production

**Comment by decadence** [comment]
Welcome to Laravel! We are glad to have you as part of the community.

Unfortunately GitHub is not an appropriate platform for general application issues. This is only for issues/bugs with the framework code itself.

Please close your issue, and instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

Laravel Slack (https://larachat.co/)
Laravel.io Forum (https://laravel.io/forum)
Laracasts Forum (https://laracasts.com/discuss)
StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks!
