### ISSUE TITLE
Validation for nested fields returns all passed data instead of only fields in the rules

### ISSUE THREAD

**Issue by aromka** [laravel/framework#23988]
- Laravel Version: 5.5.40
- PHP Version: 7.1
- Database Driver & Version:

### Description:
Validation for nested fields returns all passed data instead of only fields in the rules. 
For example:

$data = $this->validate($request, [
'nested.field1' => 'string'
]);

will also return anything that was part of "nested" input, i.e. 'nested.extra_field', 'nested.$promise', etc.

**Comment by staudenmeir** [comment]
This will be fixed in 5.7: #23708

**Comment by aromka** [comment]
awesome!
