### ISSUE TITLE
Storage::allFiles() not working for simple FTP

### ISSUE THREAD

**Issue by Raccoon5031** [laravel/framework#23987]
- Laravel Version: 5.6.7
- PHP Version: 7.2.4

### Description:
I'm trying to list all the files of my FTP. I found that the command `allFiles()` should be perfect for my use case.
When I use `Storage::disk('ftp')->allFiles()` it give me the same result as `Storage::disk('ftp')->files()` so no recursive.
I tried with my local and with an SFTP driver, and it's working very well. Therefore I think that the FTP driver is not permitting `allFiles()`

### Steps To Reproduce:
Set up an simple FTP driver
Create a folder with sub-folders and files in each sub-folders
Try to use `allFiles()`

**Comment by tillkruss** [comment]
Please report your issue here: https://github.com/thephpleague/flysystem
