### ISSUE TITLE
->autoIncrement() not desirable behaviour

### ISSUE THREAD

**Issue by rocketlaunchr-cto** [laravel/framework#23997]
In mysql, the database modifier `->autoIncrement()` seems to try and set the field to an auto-increment primary key (as stated in documentation).

This is undesirable behaviour.

```
$table->uuid('id');
$table->primary('id');
$table->integer('incr_id')->unsigned()->index()->autoIncrement(); //should not also try and make this a primary key
```

This errors out but should be permitted.

```
SQLSTATE[42000]: Syntax error or access violation: 1068 Multiple primary key defined (SQL: alter table `users` add primary key `users_id_primary`(`id`))
```

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.
