### ISSUE TITLE
Mail::sendNow() behaves differently while mocked

### ISSUE THREAD

**Issue by eidng8** [laravel/framework#23993]
- Laravel Version: 5.6.17
- PHP Version: PHP 7.1
- Database Driver & Version: MySQL 5.6

### Description:
```php
class SomeMailableShouldQueue extends Mailable implements ShouldQueue {}

Mail::to('someone@example.com')->sendNow(new SomeMailableShouldQueue());
```
The above is sent immediately with `sendNow()`.

However, it is not the case after mocked:

```php
Mail::fake();
Mail::to('someone@example.com')->sendNow(new SomeMailableShouldQueue($content));
Mail::assertSent('test mail', 1);
// the above assert fails with
// The expected [SomeMailableShouldQueue] mailable was sent 0 times instead of 1 times.
```

It really is queued:

```php
Mail::fake();
Mail::to('someone@example.com')->sendNow(new SomeMailableShouldQueue($content));
Mail::assertQueued('test mail', 1); // This passes
```

**Comment by eidng8** [comment]
It seems this is not just a mocking issue. The production code does so too. Anything implementing the `ShouldQueue` will be queued, even calling `sendNow()`. Mocked or not.

```php
Mail::to('someone@example.com')->sendNow(new SomeMailableShouldQueue($content));
```

Below is the call stack:
[Mailable.php:160, Some\Mailable\Descendant\Class->queue()](https://github.com/laravel/framework/blob/0b4a5b7c5732fc213143ff30835ed29df3e21893/src/Illuminate/Mail/Mailable.php#L160)
[Mailer.php:263, Illuminate\Mail\Mailer->sendMailable()](https://github.com/laravel/framework/blob/0b4a5b7c5732fc213143ff30835ed29df3e21893/src/Illuminate/Mail/Mailer.php#L263)
[Mailer.php:218, Illuminate\Mail\Mailer->send()](https://github.com/laravel/framework/blob/0b4a5b7c5732fc213143ff30835ed29df3e21893/src/Illuminate/Mail/Mailer.php#L218)
[PendingMail.php:130, Illuminate\Mail\PendingMail->sendNow()](https://github.com/laravel/framework/blob/0b4a5b7c5732fc213143ff30835ed29df3e21893/src/Illuminate/Mail/PendingMail.php#L130)

**Comment by weeman1337** [comment]
Hi, according to the docs this is the expected behavior:
https://laravel.com/docs/5.6/mail#queueing-mail look for the "Queueing By Default" section.

If you don't use the "ShouldQueue" interface, you can decide if to queue or not.

**Comment by eidng8** [comment]
Yes, I've read that, and I'm still confused. Maybe I'm too poor in human language;p

The thing is, we have two things, Jobs and Mail, they both support `ShouldQueue`, and they both have `xxxNow()`. But, they behave differently. And the document doesn't explicitly states that.

So, I thought that the `Now` suffix means the same here. Thus I was expecting the same behavior as `dispatchNow()`.

However, I can't help disagreeing with you, if this is the expected behavior. I still hope you would consider this as a proposal.
