### ISSUE TITLE
Multiple testing with redirect fails

### ISSUE THREAD

**Issue by davidporos92** [laravel/framework#23996]
- Laravel Version: 5.6.17
- PHP Version: 7.2.3
- Database Driver & Version: None

### Description:
If i write a test function which calls multiple routes and asserts the respons after each other, the second call/assert fails.
On many routes I want to redirect the system to another route. After the redirect the response is a view which I am asserting on.

### Steps To Reproduce:
The below code just example for easy reproduction!

#### Setup

`RouteServiceProvider`:
```
protected function mapWebRoutes()
{
    Route::middleware('web')
        ->namespace($this->namespace)
        ->group(base_path('routes/web.php'));

    Route::prefix('v1')
        ->middleware('web')
        ->namespace($this->namespace . '\V1')
        ->group(base_path('routes/v1/web.php'));
}
```

`routes/web.php`:
```
Route::get('/', function() {
    return redirect('/v1/steps/visitor-type');
});
```

`routes/v1/web.php`:
```
Route::get('/', function() {
    return redirect('/v1/steps/visitor-type');
});
Route::group(['prefix' => '/steps'], function () {
    Route::get('/', function() {
        return redirect('/v1/steps/visitor-type');
    });

    Route::get('/visitor-type', function() {
        return view('welcome');
    });
});
```

#### Test

```
class RedirectTest extends TestCase
{
    public function setUp()
    {
        parent::setUp();

        $this->followingRedirects();
    }

    public function testBaseRedirect()
    {
        $response = $this->get('/');
        $response->assertViewIs('welcome');
    }

    public function testBaseV1Redirect()
    {
        $response = $this->get('/v1');
        $response->assertViewIs('welcome');
    }

    public function testBaseV1StepsRedirect()
    {
        $response = $this->get('/v1/steps');
        $response->assertViewIs('welcome');
    }

    public function testBaseRedirectFail()
    {
        $response = $this->get('/');
        $response->assertViewIs('welcome');

        $response = $this->get('/v1');
        $response->assertViewIs('welcome');

        $response = $this->get('/v1/steps');
        $response->assertViewIs('welcome');
    }
}
```

So the tests `testBaseRedirect`, `testBaseV1Redirect`, `testBaseV1StepsRedirect` are succeed, but the test `testBaseRedirectFail` fails with `The response is not a view.` on the second assert.

Thanks for any help with this! :)

**Comment by laurencei** [comment]
Yes - each test is a single instance of the framework booting.

So on the second attempt the framework is already loaded and it does not work. This is expected behaviour unforuantely and is not a bug.

Your best option is to seperate the tests so that each does a call to the framework once.

**Comment by davidporos92** [comment]
But a Redirect is still a Redirect, isn't it?
Why does it differ if the framework is already booted?

**Comment by laurencei** [comment]
An internal redirect is still only one boot of the framework. Interally the framework handles it, and it is still only one `get`.

So this will work:

```
$response = $this->get('/v1/steps');
$response->assertViewIs('welcome');
```

What you cant do is multiple `get` calls inside the one test - that is multiple boots of the framework.

**Comment by davidporos92** [comment]
I see. But shouldn't the `$this->followingRedirects();` Handle these redirects too?

**Comment by laurencei** [comment]
Yes - they do.

You can redirect as many times as you want within one given http request during a single test - ie.

```
$response = $this->get('/v1/steps');
// app redirects to A
// app redirects to B
// app redirects to C
$response->assertViewIs('welcome');
```

But you cannot do a second http call during a single test:


```
$response = $this->get('/v1/steps');
// app redirects to A
// app redirects to B
// app redirects to C
$response = $this->get('/v1/steps');  // <--- CANT DO THIS
$response->assertViewIs('welcome');
```
