### ISSUE TITLE
php artisan queue:work beanstalkd --daemon --queue="my_queue" processing first job.

### ISSUE THREAD

**Issue by ahsansalaldaha** [laravel/framework#23995]
Hi @GrahamCampbell , @taylorotwell .
**HISTORY**
I have read that queue:listen loads laravel framework every time it process the job whereas the queue:work daemon load it first time. I am facing issues in laravel 5.2. The problem started with the dead lock and i read that i should use beanstalkd, i was using database before. i configured beanstalkd now my scenario is that i have multi tenancy app so each queue has its own connection(database) and i am using beanstalkd now. so i have beanstalkd server running on defailt port and i have one queue and two processes for each tenant.
so when i push the job from the server suppose 22 job. the jobs successfully pushed to beanstalkd. now when i run 
php artisan queue:listen beanstalkd --queue=my_queue --tries=3 --sleep=3 it works fine my for just 6 tenants and i have 12 jobs and my CPU utilization is 100% of all 4 cores using supervisor.
**ISSUE**
when I do 
php artisan queue:work beanstalkd --queue=pantry_hrms --daemon
it just run for first job and it just stops it never processes the second the job. i am using daemon so it should process the next job right. Any help will be appreciated.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I suggest closing your issue ticket here? Instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.
