### ISSUE TITLE
apiResource chain order

### ISSUE THREAD

**Issue by m1kfb** [laravel/framework#24007]
- Laravel Version: 5.6.17
- PHP Version: PHP 7.2.4 (cli) (built: Apr 12 2018 02:49:37) ( NTS )
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.7.22, for osx10.13 (x86_64) using  EditLine wrapper

### Description:
Using apiResource()  after middleware()
`Route::middleware('auth:api')->apiResource('company', 'CompanyController');`

casues

In RouteRegistrar.php line 178:
                                                                         
  Method Illuminate\Routing\RouteRegistrar::apiResource does not exist.

Works when it's like:- `Route::apiResource('company', 'CompanyController')->middleware('auth:api');`

### Steps To Reproduce:
Add apiResource() after middleware()
`Route::middleware('auth:api')->apiResource('company', 'CompanyController');`

**Comment by staudenmeir** [comment]
Is there any downside to `Route::apiResource('company', 'CompanyController')->middleware('auth:api');`?

**Comment by m1kfb** [comment]
No, just an undocumented feature.

**Comment by driesvints** [comment]
When reading the docs at https://laravel.com/docs/5.7/middleware#assigning-middleware-to-routes all the examples have the middleware call after the route definition so I think it's intended as such.
