### ISSUE TITLE
 Can not add data to the collection array.

### ISSUE THREAD

**Issue by DmitrySkibitsky** [laravel/framework#24006]
- Laravel Version: 5.6.17
- PHP Version: 7.2.4

### I can not add data to that array. Tell me how to do this. Thank you in advance.

_php_
```php
$this->crawler->filter('ul[class=basic_list] > li')->each(function ($node) use ($element_name) {
    var_dump($node->text());
    var_dump($element_name);
    var_dump(is_array($this->product_compare->firstWhere('name', $element_name)['children']));
    $this->product_compare->firstWhere('name', $element_name)['children'][] = $node->text();
);
dd($this->product_compare);
```
_console_ 
```php
string(12) "893 3004.195"
string(19) "AMERICAN MOTORS AMC"
bool(true)
Illuminate\Support\Collection {#2419
  #items: array:1 [
    0 => array:2 [
      "name" => "AMERICAN MOTORS AMC"
      "children" => []
    ]
  ]
}

```

**Comment by staudenmeir** [comment]
You have to use something like this:

    $key = $this->product_compare->where('name', $element_name)->keys()->first();
    $product = $this->product_compare[$key];
    $product['children'][] = $node->text();
    $this->product_compare[$key] = $product;

**Comment by DmitrySkibitsky** [comment]
@staudenmeir , Thank you. Your option works. I somehow thought that with collections you can work so like you modify them. And it turns out that you need to reassign the data, modify it and then re-write it where it came from. For some reason I did not think of it. I wanted a minimum of variables.

**Comment by DmitrySkibitsky** [comment]
you can close. the decision was prompted.)

**Comment by staudenmeir** [comment]
You can close it ;-)
