### ISSUE TITLE
setMorphClass on MorphToMany relation class

### ISSUE THREAD

**Issue by angay9** [laravel/framework#24016]
- Laravel Version: 5.6
- PHP Version: 7.2

### Description:
I'm building my application on top of laravel orchid package, and they have the `Orchid\Platform\Core\Models\Post` class that they use internally in their core to save posts, add categories and tags, etc. When saving tags, the taggable type in database is being set to `Orchid\Platform\Core\Models\Post`.
I also my own post class `App\Post` that inherits from the base post class.
The problem occurs when I try to get tags on a post (`App\Post`):
```
$post->tags; // nothing is returned
```
that's obviously because in the database the namespace of a parent post is being stored.
I can resolve this issue by setting the `getMorphClass` on my `App\Post` class:
```
    public function getMorphClass()
    {
        return parent::class;
    }
```
but in case I would want to create some new polymorphic relations on my `App\Post` class, things would break.

### Suggestion
Add a `setMorphClass` on a `MorphToMany` relation so that for some polymorphic relations it is possible to use parent class.
Example of usage: 
```
class Post extends BasePost 
{
    public function tags() 
    {
         return $this->morphToMany(static::$tagsModel, 'taggable', 'tagged', 'taggable_id', 'tag_id')
                ->setMorphClass(parent::class)
         ;
    }
}
```
Please let me know if there is a way already to accomplish this.
Otherwise I believe this would be a useful feature to have.
Thanks.

**Comment by angay9** [comment]
@tillkruss 
Can I please know why this issue was closed?
Is it already resolved?
Thanks :)

**Comment by tillkruss** [comment]
You didn't read the text when opening a new issue. This is not a place to ask for help or suggest new features.

**Comment by angay9** [comment]
Ah, my bad. Sorry about that.
Thanks
