### ISSUE TITLE
Feature Request: Return 304 Response Code

### ISSUE THREAD

**Issue by tedsecretsource** [laravel/framework#24027]
https://github.com/laravel/framework/blob/0d276099b1283f4b20a09aff8b8a446d14ba9fb3/src/Illuminate/Routing/ResponseFactory.php#L178

I'd like to be able to return a 304 response code but I see the response code is hard-coded as 200. The use case is to improve browser-side caching for resources that haven't changed.

Thanks in advance.

**Comment by browner12** [comment]
Thanks for the suggestion.  Feature requests need to be opened in https://github.com/laravel/ideas and this repo should be for bugs only.

thanks

**Comment by tedsecretsource** [comment]
So, it says I should be willing to code this up. More than happy to attempt a pull request (would be my first) but in this case, not sure how to go about it. I'll open the case there and post and post my doubts.

Thanks!
