### ISSUE TITLE
Socialite with Facebook expiresIn become null

### ISSUE THREAD

**Issue by pierrocknroll** [laravel/framework#24025]
Hello,

I noticed that if I use userFromToken() method from Socialite, the expiresIn become null, but have a value with user() method.

Trying with :
```
$user1 = Socialite::driver('facebook')->user();
$user2 = Socialite::driver('facebook')->userFromToken($user1->token);
dd($user1->expiresIn, $user2->expiresIn);
```
Will show 5162187 and null. ( the code is an example and has no interest in production ^^ )
It's the only difference between $user1 and $user2.

Is it normal ? Or does it mean that with the second method, the token has no expiration ?

Thanks !

Versions : Laravel 5.6.17 and Socialite 3.0.9

**Comment by tillkruss** [comment]
Wrong repo 🙂

**Comment by pierrocknroll** [comment]
Since it is impossible to add an issue in https://github.com/laravel/socialite
I thought it was the good place, any idea ?

**Comment by tillkruss** [comment]
Yeah, for general questions and support go here: 

- https://laracasts.com/discuss 
- https://laravel.io/forum
