### ISSUE TITLE
Optional should implement __isset

### ISSUE THREAD

**Issue by BinotaLIU** [laravel/framework#24031]
- Laravel Version: 5.6
- PHP Version: 7.2
- Database Driver & Version: No Database

### Description:
`\Illuminate\Support\Optional` should implement __isset, there are some cases that maight need this.
For example, I have an Eloquent HasMany relation, say `contacts` on model `User`:
```php
<?php
$user = User::find(1);
$hasPhoneNumber = !empty(optional($user->contacts->first())->cellphone);
```

`$user->contacts` maight be an empty Collection, so I have to check it by optional helper.
Since the Optional didn't implement `__isset`, `$hasPhoneNumber` will always be `false`.

### Steps To Reproduce:
See code above.

**Comment by tillkruss** [comment]
Feel free to submit a pull request.
