### ISSUE TITLE
Assigning names to foreign keys and dropping foreign keys do not work (SQLite)

### ISSUE THREAD

**Issue by JanisE** [laravel/framework#24041]
- Laravel Version: 5.6.18
- PHP Version: 7.1.15
- Database Driver & Version: SQLite 3.8.2

### Description:

The key name does not get assigned, the key does not get dropped (but does not throw any exception either).

Works for unique keys, but not for foreign keys.

### Steps To Reproduce:

See [this repository](https://github.com/JanisE/demo-laravel-drop-foreign-sqlite) with a fresh Laravel 5.6 installation and [added](https://github.com/JanisE/demo-laravel-drop-foreign-sqlite/commit/cd5675af817663dedda9bb5c13c4f300bc30549b) test script, please.

**Comment by staudenmeir** [comment]
SQLite doesn't support dropping foreign keys. You have to create a new table and transfer the data: https://www.techonthenet.com/sqlite/foreign_keys/drop.php

**Comment by JanisE** [comment]
Oh wow, thanks for that info!

That still leaves throwing an exception with this explanation in case of one's trying to drop a foreign key, and naming a foreign key. (My use case for wanting a name was actually not dropping the key but reference it to another library I'm using.)

**Comment by staudenmeir** [comment]
Getting the name is also not possible: https://stackoverflow.com/a/41598892/4848587
