### ISSUE TITLE
Inconsistent handling of space character in URL generation

### ISSUE THREAD

**Issue by carragom** [laravel/framework#24044]
- Laravel Version: 7.5.40
- PHP Version: 7.0.27
- Database Driver & Version: N/A

### Description:

For the most part Laravel tries to use the newer **RFC3986** for URL encoding e.g. [here](https://github.com/laravel/framework/blob/56a58e0fa3d845bb992d7c64ac9bb6d0c24b745a/src/Illuminate/Routing/RouteUrlGenerator.php#L96) and [here](https://github.com/laravel/framework/blob/30d2f7f350e1e5bfa742e18e993deedefec2e953/src/Illuminate/Routing/UrlGenerator.php#L189). And judging from #11747 this seems to be the accepted way to do it. But there are multiple places where **RFC1738** is used indirectly just because it's the default encoding for the `http_build_query` function. The main difference between the two according to the [docs](http://php.net/manual/en/function.http-build-query.php) is related to the handling of the space character. The former encodes it as `%20` and the later as `+`. To achieve consistency in the URL generation all calls to the `http_build_query` should have `PHP_QUERY_RFC3986` as it's fourth parameter. [Here](https://github.com/laravel/framework/search?utf8=%E2%9C%93&q=http_build_query&type=) we can see the use of that function in the code.

### Steps To Reproduce:

Create a simple named route and then generate a link to it using the route helper like this.

```php
route('myroute', ['key' => 'value with spaces'])
```

### Expected result

`/myroute?key=value%20with%20spaces`

### Actual result

`/myroute?key=value+with+spaces`

**Comment by tillkruss** [comment]
Can you submit a PR to v5.7 that adds `PHP_QUERY_RFC3986` to those calls?

**Comment by carragom** [comment]
I can do that. Is there any testing I should run ?

**Comment by tillkruss** [comment]
@carragom: Travis will tell you if your changes break anything. Ideally add a new test case that ensures all those components use the same RFC.

**Comment by carragom** [comment]
Great, also I see no tag or branch v5.7. Should I send this to master ?

**Comment by carragom** [comment]
Got a commit ready [here](https://github.com/carragom/framework/commit/533947e07628a4c99cd4270c961282680f3eb479). Let me known to what branch this should be sent to. Added a couple of tests for the more general cases. The others are just indirect use of the function and don't really know how to test them. This is my first PR in Laravel, let me know if I missed anything.

**Comment by bbashy** [comment]
Looks like `master` is correct https://laravel.com/docs/5.6/contributions#which-branch

**Comment by staudenmeir** [comment]
You can replace `ini_get('arg_separator.output')` with `null`. `http_build_query()` automatically uses the default value.

**Comment by tillkruss** [comment]
@carragom: looks great, except the mentioned ini_get calls.  Send it to master.

**Comment by carragom** [comment]
@staudenmeir I don't think we can pass `null` as the third argument. Check this out.

#### With null

```php
http_build_query(['key1' => 'value', 'key2' => 'another value'], null, null, PHP_QUERY_RFC3986)
```

#### Results in the following

```
"key1=valuekey2=another%20value"
```

There is no separator between the key/value pairs. So I think we could either hard-code the separator to `&` or get it from the ini file because it looks like passing `null` literally means no separator at all. This was tested with PHP version **7.0.27** in case that is relevant.

What do you think?

**Comment by tillkruss** [comment]
I'd be okay with just hardcoding `&`. That's our use case.
