### ISSUE TITLE
[5.6] Lumen: Call to a member function parameter() on array

### ISSUE THREAD

**Issue by Korri** [laravel/framework#24084]
- Lumen Version: 5.6.20
- PHP Version: 7.1

### Description:
When using the `Illuminate\Contracts\Broadcasting\Broadcaster::auth()` method in Lumen, the following exception is raised:
```
Symfony\Component\Debug\Exception\FatalThrowableError : Call to a member function parameter() on array
/www/vendor/illuminate/http/Request.php:501
/www/vendor/illuminate/http/Request.php:665
/www/vendor/illuminate/broadcasting/Broadcasters/PusherBroadcaster.php:87
/www/vendor/illuminate/broadcasting/Broadcasters/PusherBroadcaster.php:65
/www/vendor/illuminate/broadcasting/Broadcasters/Broadcaster.php:65
/www/vendor/illuminate/broadcasting/Broadcasters/PusherBroadcaster.php:50
...
```

### Steps To Reproduce:
Create an endpoint that uses `Illuminate\Contracts\Broadcasting\Broadcaster::auth()` to generate the response in Lumen.

Basic example that checks user is accessing its own channel:
```php
<?php

namespace App\Http\Controllers;

use Illuminate\Contracts\Broadcasting\Broadcaster;
use Illuminate\Http\Request;
use App\User;

class BroadcastingController extends Controller
{
    public function auth(Request $request, Broadcaster $broadcaster)
    {
        $broadcaster->channel('user.{userId}', function (User $user, $userId) {
            return $user->id === (int)$userId;
        });

        return $broadcaster->auth($request);
    }
}
```

I narrowed it down to this commit https://github.com/laravel/framework/commit/f92b4c38b916edabf15953b0ec57c64f39b1fc17

Which by doing `$request->callback` [ends up trying to call `$route->parameter()`](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Http/Request.php#L501) (but routes are arrays in Lumen).

**Comment by sisve** [comment]
This repository is for Laravel. Report issues for Lumen at https://github.com/laravel/lumen-framework/issues

**Comment by Korri** [comment]
Oops sorry.
