### ISSUE TITLE
how to get table name of model join

### ISSUE THREAD

**Issue by ShivarajRH** [laravel/framework#24094]
- Laravel Version: 5.4.*
- PHP Version: 5.5
- Database Driver & Version: MySql 5

### Description:
Hi, Below laravel code, i am trying to get table name (alias) for joining table, 

```
PurchaseBills::with(['Expenses'=>function($q) {
        dd ( $q->getTable() ); // here, undefined getTable() method
	$q->addSelect('sup.name as expense_title')
	->leftJoin($q->getTable().' as sup','sup.id',$this->wpPurchaseBillExpenses->getTable().'.supplier_id');
}])->get();

```
An error is thrown, since I am referring a method of a Model.
How can I achieve this to get table name of a model?

### Steps To Reproduce:

```
class PurchaseBills extends Model
{
	public $table='purchase_bills';
	protected $primaryKey = 'id';
	public function Expenses()
	{
		return $this->hasMany(PurchaseBillExpenses::class,'bill_id','id')->select('bill_id','supplier_id','memo','amount');
	}
}
```

**Comment by staudenmeir** [comment]
You want the table of `PurchaseBillExpenses`, right? Use this:

    $q->getRelated()->getTable()

**Comment by browner12** [comment]
Welcome to Laravel! We are glad to have you as part of the community.

Unfortunately GitHub is not an appropriate platform for general application issues. This is only for issues/bugs with the framework code itself.

Please close your issue, and instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

Laravel Slack (https://larachat.co/)
Laravel.io Forum (https://laravel.io/forum)
Laracasts Forum (https://laracasts.com/discuss)
StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks!
