### ISSUE TITLE
Uniform cache flush success messages

### ISSUE THREAD

**Issue by szepeviktor** [laravel/framework#24098]
Could you please make them similar?
Mainly `#1` and `#4`
Thank you!

```
./artisan clear-compiled
./artisan config:clear
./artisan route:clear
./artisan cache:clear
./artisan view:clear

The compiled services & packages files have been removed.
Configuration cache cleared!
Route cache cleared!
Cache cleared successfully.
Compiled views cleared!
```

**Comment by szepeviktor** [comment]
Maybe `Cache cleared successfully.` -> `Application cache cleared!`
and `The compiled services & packages files have been removed.` -> `Compiled services and packages files removed!`

What do you think?
Should I send a PR?

**Comment by tillkruss** [comment]
Please! No. 1 might be tricky, but 4 mos def.
