### ISSUE TITLE
A failed SQL insert return true with Eloquent ->save() call

### ISSUE THREAD

**Issue by pajtai** [laravel/framework#24099]
Note sure if this is the right place to file Eloquent bugs, but I could not find where else would be the appropriate place. Please advise as needed.

- PHP Version: 5.6
- Database Driver & Version: mysqlnd 5.0.11-dev - 20120503 - $Id: 76b08b24596e12d4553bd41fc93cccd5bac2fe7a $

### Description:

->save() method returns true even when PDO insert statement fails and last_error contains a string.

### Steps To Reproduce:

Create a foreign key constraint that will be violated upon insert and run a model->save()

The insert below can error out. In this case the $id will be a 0 and no entry into the db is created:

illuminate/database/Query/Processors/Processor.php
```
public function processInsertGetId(Builder $query, $sql, $values, $sequence = null)
    {
        $query->getConnection()->insert($sql, $values);

        $id = $query->getConnection()->getPdo()->lastInsertId($sequence);

        return is_numeric($id) ? (int) $id : $id;
    }
```

`‌‌$query->getConnection()->db->last_error` can be a string, but lastInsertId is still checked for. In my case `‌‌$query->getConnection()->db->last_error;` was 

```
Cannot add or update a child row: a foreign key constraint fails (`dbname`.`table_name`, CONSTRAINT `foreign_key_name` FOREIGN KEY (`user_id`) REFERENCES `wp_users` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE)
```

The end result was that ->save() returned true but no entry in the DB was made. This is extremely confusing.

**Comment by staudenmeir** [comment]
What Laravel version are you using?

**Comment by pajtai** [comment]
@staudenmeir looks like it is:

```
            "name": "illuminate/database",
            "version": "v5.4.36",
```

Eloquent is a dependency of wp-eloquent:
https://github.com/tareq1988/wp-eloquent/blob/master/composer.json

**Comment by staudenmeir** [comment]
I can't reproduce the problem with the latest `illuminate/database` version. I strongly suspect this to be specific to `wp-eloquent`.

If the query fails, the second line of `processInsertGetId()` should not be reached.

**Comment by pajtai** [comment]
Looking some more at the wp-eloquent code, I think you're right. It uses eloquent to build the query, but then it uses `$wp_db` to run it. I'm going to close this and try and look into the details a little more.
