### ISSUE TITLE
Signed route fails with additional parameters

### ISSUE THREAD

**Issue by francoism90** [laravel/framework#24095]
- Laravel Version: 5.6.19
- PHP Version: 7.2.5
- Database Driver & Version: MySQL 5.7

### Description:
Using the following signed router will always result into `Invalid signature`:
```
Route::middleware('signed')->name('video.')->namespace('Video')->group(function () {
    Route::get('/stream/{video}/{name}', ['uses' => 'StreamController@show', 'as' => 'stream']);
});
```

URL generating:
```
return URL::temporarySignedRoute('video.stream', now()->addMinutes(240), [
            'video' => $this->slug,
            'name'  => 'video.mp4',
        ]);
```

This works fine:

```
return URL::temporarySignedRoute('video.stream', now()->addMinutes(240), [
            'video' => $this->slug,
            'name'  => 'video',
        ]);
```

I want to append the extension part so it can be used on Android to open in external device. It is possible the `dot (.)` isn't parsed correctly?

### Steps To Reproduce:
See Description.

**Comment by tillkruss** [comment]
Can you write a test case to reproduce this?

**Comment by linuxfreak90** [comment]
@tillkruss Will try to create a test.

**Comment by francoism90** [comment]
@tillkruss Sorry for the noise! After some searching it turns out I've had a nginx rule set that replaced headers on some extensions, causing the `Invalid signature` error.
