### ISSUE TITLE
[5.6] Helper dd() does not return status 500 anymore

### ISSUE THREAD

**Issue by kevin-ferradj** [laravel/framework#24093]
Since version 5.6.18 helper dd() does not return error 500 anymore. It is now painful to debug ajax calls.

Previous code for this function: 

```php
function dd(...$args)
{
    http_response_code(500);

     foreach ($args as $x) {
        (new Dumper)->dump($x);
     }

     die(1);
}

```

Today's code: 

```php
function dd(...$args)
{
    foreach ($args as $x) {
        (new Dumper)->dump($x);
    }

    die(1);
}

```

**Comment by nunomaduro** [comment]
> It is now painful to debug ajax calls.

Why is that?

**Comment by staudenmeir** [comment]
See #23930. Are you using Chrome 65+?

**Comment by kevin-ferradj** [comment]
@staudenmeir Yes i'm using Chrome 66
@nunomaduro Because now when i use dd(), the ajax call is not showing in red in the network panel of chrome dev tool

**Comment by nunomaduro** [comment]
@kevin-ferradj You can always clear all Ajax calls from your panel of chrome before doing a new one.

**Comment by kevin-ferradj** [comment]
@nunomaduro Yes of course but that's what i mean by "It is now painful to debug ajax calls"
