### ISSUE TITLE
Make:listener and make:event don't check if file allready exists.

### ISSUE THREAD

**Issue by JamesAnelay** [laravel/framework#24125]
- Laravel Version: Current.
- PHP Version: PHP 7.1.15, but I believe true in all versions

### Description:
Both make:listener and make:event don't check to see if the file already exists. This is particularly frustrating when like me you hit "up arrow > enter" in the command to run what is usually the phpunit command only to accidentally rewrite the file you just edited by running the make: command again.

I did a bit of digging and saw that in commit  307917505bbc1ef9f8e3b9442c92bbbf79cafa45 @taylorotwell implemented a fix to already exists "prevents the framework from generating listeners for listeners
that are defined in packages outside of the App namespace" that fix causes this at least for the Listener class because class_exists don't have the full path in currently, so it always returns false.

I would suggest an update like this below as getDefaultNamespace is defined to the correct Directory for each descendant:

```
    protected function alreadyExists($rawName)
    {
        return class_exists($this->getDefaultNamespace().'\\'.$rawName);
    }
```

Ideally this would just be applied to the GeneratorCommand class and the overwrites on listener, event and exceptions removed for easier maintainence.

However, this means that anything that GeneratorCommand will only be able to create classes in the Laravel Root namespace (usually App). I'm not sure if this is desired, which is why it didn't create it yet at the moment, for example, I can create a file in the root of the project by running "php artisan make:model ../testing
" and if permission allows even outside of the project directory.

Note: I'm keep to contribute the solution myselt as my first propper opensource contribution, however I am just not 100% sure if any of the make: commands that use GeneratorCommand should be able to create files outside of App. Or if we can change it at this point given other users may have overridden it themselves.

### Steps To Reproduce:
Run 
`php artisan make:listener Testing` twice expected output on the second run should be "File allready exists error" however it simply recreates it.

**Comment by tillkruss** [comment]
Can you submit a PR?
