### ISSUE TITLE
Eloquent: Nested Lazy Eager Loading will erase relations from Nested Eager Loading

### ISSUE THREAD

**Issue by SeparateReality** [laravel/framework#24121]
- Laravel Version:  slim/slim 3.10.0
- Eloquent: illuminate/database v5.6.20 
- PHP Version:  7.2.4
- Database Driver & Version: MariaDB 10.3.6

### Description:

When first using Nested Eager Loading, like
 **(1)** `$categories = Category::with(['products.adjunctProducts'])->get();` 
and put a Nested Lazy Eager Loading on top of it, like
**(2)**  `$categories->load(['products.subscriptionModel']);`
then

after (1) you will get a Collection with 'products.adjunctProducts' relation, as expected.

But after (2) you will get a Collection with 'products.subscriptionModel' relation (again as expected),
**but you will not find the relation 'products.adjunctProducts' anymore.**

**Remarks:**
- This does not happen with non-nested Eager Loads (e.g. `$categories = Category::with('products')->get();`
- One could ask 'Why not just put the nested load directly in the first `with()`'.
The described case here is simplified as much as possible. Our Eager Loaded collection normally can be changed by different modules using an event. So if a modules needs further relations it would just use `load()`
- Our temporary solution is to not use `get()` (until after the event) but work with the Builder-Object and concatenate several `with()`s. Not sure if that's the best solution!?

### Steps To Reproduce:

Take a model with different relations on a first relation and reproduce with the description above.

**Comment by staudenmeir** [comment]
That's the expected behavior. Use this:

    $categories->products->load(['subscriptionModel']);

**Comment by staudenmeir** [comment]
Sorry, I missed that. Use this:

    $categories->pluck('products')->collapse()->load(['subscriptionModel']);

The purpose of `load()` is to get the relationship results – even if a model already has results. The idea behind overwriting existing results is that you might want to get the latest data.

I can see why you would expect a different behavior. For a single model and non-nested relationships you can use the `loadMissing()` method.

Your situation would require `loadMissing()` on the collection and support for nested relationships. The latter is not trivial to implement, since you would have to check for existing results in every single model (#23027).

You're welcome to propose or implement improvements.

**Comment by SeparateReality** [comment]
Thank you very much for elaborating on that!
The suggested line of code unfortunately ends up with an "Uncaught BadMethodCallException: Method Illuminate\Support\Collection::load does not exist". But no worries, maybe I missed something specific to our implementation. I just gave it a quick try.
Anyway, I think that was the push in the right direction which I was hoping for!

**Comment by staudenmeir** [comment]
Again, my bad:

    use Illuminate\Database\Eloquent\Collection;

    new Collection($categories->pluck('products')->collapse())->load(['subscriptionModel']);

A shorter way to achieve this would definitely be nice...

**Comment by staudenmeir** [comment]
I updated my post. One would think that three attempts should be enough to write a working one-liner...

**Comment by SeparateReality** [comment]
One has to admit, its certainly not the most obvious one-liner... Thanks! 🥇

**Comment by staudenmeir** [comment]
I proposed `Collection::loadMissing()`: #24166
