### ISSUE TITLE
[5.6] Framework does not use a latest version of the Carbon

### ISSUE THREAD

**Issue by andrey-helldar** [laravel/framework#24133]
In the dependencies of the framework, the version of the package [nesbot/carbon 1.25.*](https://github.com/laravel/framework/blob/805f67b1f36c1aa747138c81067cb6d56ef21ed5/composer.json#L26) is required. While the latest version is [1.27.0](https://github.com/briannesbitt/Carbon/releases)

**Comment by 36864** [comment]
This has been changed on master.

Laravel 5.7 will require carbon "^1.26.3" but 5.6 will continue to restrict it to 1.25.*.

**Comment by andrey-helldar** [comment]
Okay, I understand. Thanks!
