### ISSUE TITLE
If an error occurs, the table still gets created

### ISSUE THREAD

**Issue by lucasjkr** [laravel/framework#24136]
It was my mistake for faulty syntax, but still got an unexpected result, that artisan reports an error, the table gets created, but the migration is not reported as having occurred in the migrations table, and so doesn't get rolled back.

Migration code:

    public function up()
    {
        //

        Schema::create('test_table', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->primary('id');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
        Schema::dropIfExists('test_table');

    }
    }

Run the migration. Get error. Rollback. Table still there.

I understand, I did it wrong, but still suggest changing the process. Understanding that different DB drivers have different limitations as far as transactions go. But if a Migration causes an error and doesn't get inserted into the migrations table, perhaps that table should be dropped outside of the `down()` method.

- Laravel Version: 5.6.18
- PHP Version: 7.1.14
- Database Driver & Version: MariaDB 5.7 (wow! I need to upgrade....)

**Comment by sisve** [comment]
This sounds more like a feature suggestion. Could you perhaps expand further on the logic that can be used to do this properly and file an issue at https://github.com/laravel/ideas/issues?

**Comment by lucasjkr** [comment]
I did as you suggested (https://github.com/laravel/ideas/issues/1159). Will close here. Thanks!
