### ISSUE TITLE
custom extensions when testing

### ISSUE THREAD

**Issue by agoalofalife** [laravel/framework#24131]
Method `setUpTraits` return uses array.
https://github.com/laravel/framework/blob/805f67b1f36c1aa747138c81067cb6d56ef21ed5/src/Illuminate/Foundation/Testing/TestCase.php#L71

I want to create a (custom)trait for the extension.
It would be convenient to do so..

```php
$this->uses = $this->setUpTraits();
```

```php
// custom trait
trait Custom
{
public function customMethod()
{
 // ....
}
}
```
```php
abstract class TestCase extends BaseTestCase
{
 protected function setUp()
 {
   parent::setUp();

   if (isset($uses[Custom::class])) {
            $this->customMethod();
        }
 }
}
```

In the current version you need to override the method `setUp` or to violate the principle `DRY`
@taylorotwell What do you think about this?

**Comment by staudenmeir** [comment]
Please use https://github.com/laravel/ideas/issues for proposals.

**Comment by agoalofalife** [comment]
@staudenmeir it is close?

**Comment by agoalofalife** [comment]
add https://github.com/laravel/ideas/issues/1158

**Comment by staudenmeir** [comment]
Yes, please close it.
