### ISSUE TITLE
[5.6] Slack log handler failing when no webhook is provided

### ISSUE THREAD

**Issue by hubertnnn** [laravel/framework#24148]
- Laravel Version: v5.6.20
- PHP Version: 7.1.16-1+ubuntu16.04.1+deb.sury.org+1

### Description:
Slack log handler failing when no webhook is provided

### Steps To Reproduce:

1. Use the default logger slack handler configuration
2. Don't set LOG_SLACK_WEBHOOK_URL in your .env file
3. Call `Log::channel('slack')->error('test');`
4. You will get an exception saying "Curl error (code 3): <url> malformed"

### Expected behavior:

When webhook is not provided or is set to null, slack driver should ignore messages.
Used to disable unused loggers in local and staging environments using env variables.

**Comment by tillkruss** [comment]
This is expected, we don't want to fail silently. Feel free to submit a PR that throws a better exception.

**Comment by hubertnnn** [comment]
If that is the case, then what is the designed way of turning loggers off?
Is there even one?

Sentry supports disabling by setting "SENTRY_DSN" to null, so I assumed other loggers will do the same.

Of course something like that will work, but this is just ridiculus and does not fit the form of a config file:
```
'default' => [
            'driver' => 'stack',
            'channels' => ['file', 'file-debug', 'sentry', (env('LOG_SLACK_WEBHOOK_URL') !== null) ? 'slack' : 'dummy'],
        ],
```
Imagine having 4 or 5 conditional loggers.

**Comment by tillkruss** [comment]
You could use your own logger service provider.
