### ISSUE TITLE
I am facing issue while upgrading Laravel 5.3 from 5.2.

### ISSUE THREAD

**Issue by piyush-azova** [laravel/framework#24145]
ReflectionException: Class does not exist in /MYPROJECT/vendor/laravel/framework/src/Illuminate/Container/Container.php:749

[2018-05-08 07:14:18] production.ERROR: ReflectionException: Class  does not exist in /opt/lampp/htdocs/MYPROJ/vendor/laravel/framework/src/Illuminate/Container/Container.php:749
Stack trace:
#0 /opt/lampp/htdocs/MYPROJ/vendor/laravel/framework/src/Illuminate/Container/Container.php(749): ReflectionClass->__construct('')
#1 /opt/lampp/htdocs/MYPROJ/vendor/laravel/framework/src/Illuminate/Container/Container.php(644): Illuminate\Container\Container->build('', Array)
#2 /opt/lampp/htdocs/MYPROJ/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(709): Illuminate\Container\Container->make('', Array)
#3 /opt/lampp/htdocs/MYPROJ/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(127): Illuminate\Foundation\Application->make('')
#4 /opt/lampp/htdocs/MYPROJ/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#5 /opt/lampp/htdocs/MYPROJ/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#6 /opt/lampp/htdocs/MYPROJ/vendor/laravel/framework/src/Illuminate/Routing/Router.php(655): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#7 /opt/lampp/htdocs/MYPROJ/vendor/laravel/framework/src/Illuminate/Routing/Router.php(629): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#8 /opt/lampp/htdocs/MYPROJ/vendor/laravel/framework/src/Illuminate/Routing/Router.php(607): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#9 /opt/lampp/htdocs/MYPROJ/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(268): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 /opt/lampp/htdocs/MYPROJ/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#11 /opt/lampp/htdocs/MYPROJ/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /opt/lampp/htdocs/MYPROJ/app/Http/Middleware/VerifyCsrfToken.php(26): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#13 /opt/lampp/htdocs/MYPROJ/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): App\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#14 /opt/lampp/htdocs/MYPROJ/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 /opt/lampp/htdocs/MYPROJ/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#16 /opt/lampp/htdocs/MYPROJ/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#17 /opt/lampp/htdocs/MYPROJ/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 /opt/lampp/htdocs/MYPROJ/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /opt/lampp/htdocs/MYPROJ/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /opt/lampp/htdocs/MYPROJ/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 /opt/lampp/htdocs/MYPROJ/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 /opt/lampp/htdocs/MYPROJ/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /opt/lampp/htdocs/MYPROJ/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 /opt/lampp/htdocs/MYPROJ/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /opt/lampp/htdocs/MYPROJ/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /opt/lampp/htdocs/MYPROJ/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))

Any help will be appreciated. Thanks in advance

**Comment by teuunn** [comment]
Maybe you can provide some more information for the people willing to help; what are the steps to reproduce? Which steps have you already took compared to the [Upgrading Guide](https://laravel.com/docs/5.3/upgrade#upgrade-5.3.0)? Etc.

**Comment by piyush-azova** [comment]
OK teuunn, Thanks for the reply. Can you please guide me that what kind of changes do I have to make for custom AuthController in laravel version 5.3? I mean I haven't used new Authentication process with 4 new controllers.

**Comment by teuunn** [comment]
@piyush-azova my advice is to change your custom auth to Laravel's auth. In that case you can also upgrade easier (in the future). Maybe you also want to take a look at [Laravel Shift](https://laravelshift.com/)
