### ISSUE TITLE
how to use no wait or skip locked in postgresql

### ISSUE THREAD

**Issue by cevin** [laravel/framework#24154]
- Laravel Version: 5.6.20
- PHP Version:7.2
- Database Driver & Version: postgresql 10.3

### Description:
sql example:
```sql
select * from test where pk = 1 for update nowait
select * from test where pk = 1 for update skip locked
```

**Comment by ibrunotome** [comment]
Hi @tillkruss, I'd like to know too, since with eloquent I can only use lockForUpdate and sharedLock, it's there a way to use skip locked without using PLpgSQL?

**Comment by cevin** [comment]
@ibrunotome
I use `pg_try_advisory_xact_lock`
```php
Model::query()->update(['column'=>'value'])->where(\DB::raw('pg_try_advisory_xact_lock(pk)'))->where('pk','integer');
```

**Comment by ibrunotome** [comment]
Thanks @cevin!

**Comment by kocoten1992** [comment]
Mysql 8 also support ```NO WAIT``` and ```SKIP LOCKED```, this question become more relevant, should we open it ?
