### ISSUE TITLE
Blade array declaration

### ISSUE THREAD

**Issue by avitruk** [laravel/framework#24157]
- Laravel Version: 5.6
- PHP Version: 7.1

### Description:
I'm using laravel envoy and I figured with some array declaration issue.
I have multiple server in "@servers". If my servers written in several lines then envoy can't find any server and returns error. But it works fine when I'm using one-line declaration.
I'm assuming that something wrong with blade compiler.

### Steps To Reproduce:
```php
@servers(['web-1' => '192.168.1.1', 'web-2' => '192.168.1.2']) //works fine
```

and

```php
@servers([
      'web-1' => '192.168.1.1',
      'web-2' => '192.168.1.2'
]) //return error
```

**Comment by devcircus** [comment]
I would suspect that is just a limitation of blade and would be the expected behavior. However maybe someone else knows a little more.

**Comment by tillkruss** [comment]
Yeah, if you need multi-line directives, please submit a PR.
