### ISSUE TITLE
I am facing issue while upgrading Laravel 5.4 from 5.3

### ISSUE THREAD

**Issue by piyush-azova** [laravel/framework#24158]
Recently i have upgraded laravel 5.4 from 5.3 and i have gone through the upgrade guide. I face below issue, Please help me out.

[2018-05-09 13:16:07] production.ERROR: ErrorException: Illegal offset type in unset in /opt/lampp/htdocs/MYPROJ/vendor/laravel/framework/src/Illuminate/Container/Container.php:1035

Stack trace:

#0/opt/lampp/htdocs/MYPROJ/vendor/laravel/framework/src/Illuminate/Container/Container.php(1035): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Illegal offset ...', '/opt/lampp/htdo...', 1035, Array)

#1/opt/lampp/htdocs/MYPROJ/vendor/laravel/framework/src/Illuminate/Container/Container.php(205): Illuminate\Container\Container->dropStaleInstances(Object(Closure))

#2/opt/lampp/htdocs/MYPROJ/vendor/laravel/framework/src/Illuminate/Container/Container.php(311): Illuminate\Container\Container->bind(Object(Closure), NULL, true)

#3 /opt/lampp/htdocs/MYPROJ/vendor/lucasromanojf/laravel5-pdf/src/Ignited/Pdf/PdfServiceProvider.php(38): Illuminate\Container\Container->singleton(Object(Closure))

#4/opt/lampp/htdocs/MYPROJ/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(574): Ignited\Pdf\PdfServiceProvider->register()

#5/opt/lampp/htdocs/MYPROJ/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(75): Illuminate\Foundation\Application->register(Object(Ignited\Pdf\PdfServiceProvider))

#6/opt/lampp/htdocs/MYPROJ/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(549): Illuminate\Foundation\ProviderRepository->load(Array)

#7/opt/lampp/htdocs/MYPROJ/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\Foundation\Application->registerConfiguredProviders()

#8/opt/lampp/htdocs/MYPROJ/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(208): Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap(Object(Illuminate\Foundation\Application))

#9/opt/lampp/htdocs/MYPROJ/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\Foundation\Application->bootstrapWith(Array)

#10/opt/lampp/htdocs/MYPROJ/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(146): Illuminate\Foundation\Http\Kernel->bootstrap()

#11/opt/lampp/htdocs/MYPROJ/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))

#12/opt/lampp/htdocs/MYPROJ/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))

#13{main}

**Comment by 36864** [comment]
Your stack trace clearly suggests that the problem lies in the lucasromanojf/laravel5-pdf package.

This repo is for tracking bugs in the framework, not for supporting third-party packages. Please post on the forums or slack channel for help with ugprading your app.
