### ISSUE TITLE
multi-request towards the same route in one method failed in testing

### ISSUE THREAD

**Issue by cloudsthere** [laravel/framework#24155]
I make two requests towards the same route in one method, like 
```
public function testDeleteObject()
{
    $response = $this->json('delete', route('object.delete', ['object_id' => 1]));
    $response = $this->json('delete', route('object.delete', ['object_id' => 2]));
}
```
The first success and the second fails. There is nothing to do with the `object_id`, because when I comment out any of them, the other will success. So, the situation is that two requests towards one route are sent in one method.

The key point is in the controller's constructor, some code like this:
```
function __constructor(Request $request)
{
    $request->api_type = 'object';
}
```
when `api_type`  save to database in an event listener later on,  it fails with sql error because `$request->api_type` is `null`.

I digged and found this:

In `vendor/laravel/framework/src/Illuminate/Routing/Route.php`:
```
    public function getController()
    {
        if (! $this->controller) {
            $class = $this->parseControllerCallback()[0];

            $this->controller = $this->container->make(ltrim($class, '\\'));
        }

        return $this->controller;
    }

```

Laravel will not create a new controller object for the second request, since the `controller` property already exists. So the constructor will only be called once. However, the request object is always a new one.

I found a solution, but I believe there must be some elegant way.
```
public function testDeleteObject()
{
    $response = $this->json('delete', route('object.delete', ['object_id' => 1]));
    unset(app()['router']->getCurrentRoute()->controller);
    $response = $this->json('delete', route('object.delete', ['object_id' => 2]));
}
```

**Comment by laurencei** [comment]
This is 100% expected behaviour.

You can only call the framework route once per test. You should modify your tests to only expect one call per test.
