### ISSUE TITLE
Failed when returned Responsable implementation from a Middleware

### ISSUE THREAD

**Issue by tzsk** [laravel/framework#24156]
- Laravel Version: 5.6.21
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7

### Description:
When you return a Concrete implementation of `Illuminate\Contracts\Support\Responsable` from a middleware it throws error:

```
ErrorException (E_NOTICE)
Undefined property: App\TestResponse::$headers
```

### Steps To Reproduce:

**1. Create a Response Class:**
```php
namespace App;

use Illuminate\Contracts\Support\Responsable;
use Symfony\Component\HttpFoundation\Response;

class TestResponse implements Responsable
{
    public function toResponse($request)
    {
        return response()->json([
            'status' => 'ERROR',
            'code' => Response::HTTP_UNAUTHORIZED,
            'message' => 'Unauthorized Access'
        ]);
    }
}
```

**2. Create a Middleware:**
```php
namespace App\Http\Middleware;

use Closure;
use App\TestResponse;

class TestMiddleware
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        if (!auth()->check()) {
            return new TestResponse;
        }

        return $next($request);
    }
}
```

**3. Add in Kernel:**
```php
protected $routeMiddleware = [
    ...
    'test' => \App\Http\Middleware\TestMiddleware::class,
]
```

**4. Add in Route (web.php):**
```php
Route::middleware('test')->get('test', function () {
    return view('welcome');
});
```

**5. Now, visit that Route:**
```
ErrorException (E_NOTICE)
Undefined property: App\TestResponse::$headers
```

**Comment by tillkruss** [comment]
Can you submit a PR?

**Comment by raheelkhan** [comment]
According to [https://laravel-news.com/laravel-5-5-responsable](https://laravel-news.com/laravel-5-5-responsable). The object will be converted to HTTP Response when returned from **controller or route closure**

However, meanwhile it can work like this.

```
if (!auth()->check()) {
            return (new TestResponse())->toResponse($request);
        }
```

**Comment by tzsk** [comment]
@rafaelbeckel Yes. I have already implemented it that way. But, the behavior conflicts with the idea that `Responsable` implementation is interchangeable with Laravel Response. It should have consistent behavior. Don't you think?

Meanwhile, I am working on a PR to fix this.
