### ISSUE TITLE
Local dev routes interfere with production version

### ISSUE THREAD

**Issue by superDuperCyberTechno** [laravel/framework#24159]
My local development version is set up to run on  the _dev._ subdomain on my production domain. 
The subdomain is configured to be hosted on 127.0.0.1, so this subdomain does not exist publicly.

Because I need to serve multiple domains with different content, have set up my `web.php` routing so that I can change what routes is served on what domains:

```
$dev_domain_1_routes = function(){
    //routes here
}

$dev_domain_2_routes = function(){
    //routes here
}

$production_domain_1_routes = function(){
    //routes here
}

$production_domain_2_routes = function(){
    //routes here
}


Route::group(['domain' => 'domain_1'], $production_domain_1_routes]);
Route::group(['domain' => 'domain_2'], $production_domain_2_routes]);
Route::group(['domain' => 'dev_domain_1'], $dev_domain_1_routes]);
Route::group(['domain' => 'dev_domain_2'], $dev_domain_2_routes]);
```
This works pretty well until users start to log out of the production version. When they do so, they get redirected to the login page for the development version, which - as mentioned earlier - doesn't exist publicly, so that's pretty bad. 

They can still log in using the original login page if they go there.

**Comment by browner12** [comment]
Welcome to Laravel! We are glad to have you as part of the community.

Unfortunately GitHub is not an appropriate platform for general application issues. This is only for issues/bugs with the framework code itself.

Please close your issue, and instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

Laravel Slack (https://larachat.co/)
Laravel.io Forum (https://laravel.io/forum)
Laracasts Forum (https://laracasts.com/discuss)
StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks!
