### ISSUE TITLE
When a Mailable is added on the queue collection loses order. 

### ISSUE THREAD

**Issue by truthuntold** [laravel/framework#24161]
- Laravel Version: 5.5.40
- PHP Version: 7.0.29 
- Database Driver & Version:
MySql-InnoDB 5.6.34
### Description:
When a Mailable is added on the queue collection loses order. 

I added the email to the queue then returned the email view. The dates when returned via the view are in desc order. The email version seems random. 

```
        $mail = new UpcomingMatches($user, $registered, $following, $previous, 'daily', $notifications);
        Mail::to($user->email)->queue($mail);

        return $mail;
```
Email Version
<img width="927" alt="screenshot 2018-05-09 12 06 42" src="https://user-images.githubusercontent.com/1406584/39832008-4f3ce758-5383-11e8-8398-554dd4adb119.png">

View Version
<img width="881" alt="screenshot 2018-05-09 12 06 35" src="https://user-images.githubusercontent.com/1406584/39832031-607026a2-5383-11e8-9cc7-410ce19ad582.png">

**Comment by tillkruss** [comment]
Just re-order the collection.
