### ISSUE TITLE
Running no schedule:run artisan command yet actually run commands defined in schedule

### ISSUE THREAD

**Issue by gmartinez** [laravel/framework#24165]
- Laravel Version: 5.6.21
- PHP Version: 7.1.14
- Database Driver & Version: MySql 5.x

### Description:
Running any combination of artisan executes logic within "protected function schedule(Schedule $schedule)" at app\Console\Kernel.php

Found this after adding a command entry there and then run an artisan migrate.

Even running "php artisan --version" executes that logic before running the intended artisan command.

### Steps To Reproduce:

1. Add line "print 'WTF!';" inside "protected function schedule(Schedule $schedule)" at app\Console\Kernel.php
2. From command line run : php artisan --version

**Comment by laurencei** [comment]
Yes - part of the console bootup is the creation of the scheduler object, along with many other parts of the framework. It is expected behavior.

**Comment by gmartinez** [comment]
Ok, I understand, let me then add some more input into it, see the following line

$schedule->command(\App\MyClass::MyFunction())->everyMinute();

That is what I have defined inside schedule.

That command, "\App\MyClass::MyFunction()", is actually being run when I run **non** schedule:run artisan command.

Is that normal ?

**Comment by laurencei** [comment]
That's just the command class being created. The `handle()` is not actually being fired.

**Comment by devcircus** [comment]
Shouldn't the parameter to "schedule" be a string?

**Comment by gmartinez** [comment]
@laurencei the logic inside the static function is being executed, I'd understand if you tell me setting a dd() is not prove of that, but that function has real business logic that do real stuff, and if I have no dd() line I can see how that business logic is being executed (it affects the db among other) when I run "php artisan --version" from the console.

@devcircus maybe I can not call a static function like that ? official doc states that one can state "either the command's name or class"

**Comment by laurencei** [comment]
@gmartinez - actually this:

   \App\MyClass::MyFunction()

should be this

    \App\MyClass::class

and then you define your schedule logic inside `handle()`

**Comment by gmartinez** [comment]
@laurencei I guess then I can not call a static function like that :)

FYI that is what happens if you do, maybe there is something you can do to not even allow stupid people like me doing this and eventually getting this problem.

I just tested defining the call to the static function as an artisan command (easier than modifying the class) and that works as expected.

I appreciate your time and patience.
