### ISSUE TITLE
Getting relation subquery

### ISSUE THREAD

**Issue by Asxer** [laravel/framework#24169]
Hello! There is some problem with ordering eloquent query results by field from related table. Every solutions which I can find suggest me to make joins to it. I don't think it is good way. In my company we have many projects on laravel and for any case of ordering be related field we need to write it again and result doesn't looks cute. 
I'm trying to make some universal solution but I see strange behavior:

Here is model:
```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use SoftDeletes;

    ....

    public function translation() {
        $lang = session('lang', 'en');

        return $this->hasOne(CategoryTranslation::class)->where('locale', $lang);
    }
}

```

And when I'm trying to make scope for ordering: 
```php
    public function scopeOrderByRelated($query, $orderField, $desc = 'DESC')
    {
        $entities = explode('.', $orderField);

        $fieldName = array_pop($entities);
        // do not pay attention to it, in the future I'm going to do here a recursive nesting in order to have support for complex relationships, but now I'm just taking the nearest relation
        $relationName = array_shift($entities);

        $relation = $this->__callStatic($relationName, []);

        $subQuery = $relation->getQuery()->toSql();
        $subQuery = str_replace('*', $fieldName, $subQuery);

        $query->selectSub($subQuery, 'orderedField')
            ->addSelect("{$this->getTable()}.*")
            ->orderBy('orderedField', $desc);
    }
```
The problem is that this `$relation->getQuery()->toSql()` returns following sql
```sql
select title from "category_translations" where "category_translations"."category_id" is null and "category_translations"."category_id" is not null and "locale" = ?
```

This part of sql looks strange. 
**"category_translations"."category_id" is null and "category_translations"."category_id" is not null**

Expected behavior: 
        $subQuery = $relation->getQuery()->toSql();
should return
```sql
select title from "category_translations" where category_translations.category_id = categories.id and "locale" = ?
```
if I get this result, then without any problems I can implement the sorting on the connected table. Or may be Сan you suggest the best way to get a subquery of relation?

Laravel version: 5.6
Php version: 7.1
Sql: PostgreSql 9.6.4

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I suggest closing your issue ticket here? Instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.

**Comment by Asxer** [comment]
@laurencei Thank you! I will ask it on Laravel.io
