### ISSUE TITLE
RefreshDatabase Trait and Expected Exceptions

### ISSUE THREAD

**Issue by hettiger** [laravel/framework#24160]
- Laravel Version: v5.6.20
- PHP Version: 7.1.7
- Database Driver & Version: MySQL 5.7.15

### Description:

`RefreshDatabase` Trait fails to refresh the database on a test that expects an exception to be thrown.
Consequent tests fail due to this.

### Steps To Reproduce:

Here's the initial version of the method:

```php
public function testThrowsIntegrityMismatchException()
{
    $this->expectException(IntegrityMismatchException::class);

    $alterStatement = <<<SQL
ALTER TABLE `replication`
MODIFY `title` VARCHAR(200);
SQL;

    DB::statement($alterStatement);
    Artisan::call('example:check-integrity');
}
```

The `Artisan::call('example:check-integrity');` call will throw a `IntegrityMismatchException` because of the modified column.

Unfortunately the `RefreshDatabase` Trait silently fails to refresh the database after this test and consequent tests fail.

Now I've found a workaround:

```php
public function testThrowsIntegrityMismatchException()
{
    $this->expectException(IntegrityMismatchException::class);

    $alterStatement = <<<SQL
ALTER TABLE `replication`
MODIFY `title` VARCHAR(200);
SQL;

    DB::statement($alterStatement);

    try {
        Artisan::call(example:check-integrity');
    } catch (Exception $exception) {
        Artisan::call('migrate:fresh');

        /** @noinspection PhpUnhandledExceptionInspection */
        throw $exception;
    }
}
```

Anyways I'm not too happy about it because now I'm no longer benefitting from the optimized Trait. Also I think this `try`& `catch` stuff should not be necessary.

I also tried to use `$this->refreshDatabase()` instead of `Artisan::call('migrate:fresh');` but it did throw the following error:

`Doctrine\DBAL\Driver\PDOException : SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT trans2 does not exist`

I think that's the reason why the `RefreshDatabase` Trait is unable to refresh correctly behind the scenes. Also this should not fail silently?

**Comment by tillkruss** [comment]
What's the exception that's thrown, are you importing the correct path?

**Comment by hettiger** [comment]
@tillkruss It's a custom Exception: `IntegrityMismatchException`

Yes I'm importing the correct path. Otherwise it would not work with the workaround either.

**Comment by laurencei** [comment]
I've tested against exceptions before and never had this issue. There must be something else causing this...

**Comment by hettiger** [comment]
@laurencei

> That's not necceasrily correct - you are catching the generic Exception in your example.

Yes but i rethrow it and assert that it is indeed the expected exception:

```php
$this->expectException(IntegrityMismatchException::class);
```

The reason that I catch the generic Exception is that I want the `migrate:fresh` command bein called no matter what.

The workaround test that is using `try` & `catch` is passing.

I will try to reproduce this in a simplified example running on a clean install and let you know.

Thanks for the quick response.

**Comment by hettiger** [comment]
@tillkruss @laurencei 

I think I found the root of all evil:

Behind the scenese the [RefreshDatabase Trait is using Transactions for performance reasons ](https://github.com/laravel/framework/blob/442577cf0a2d0856beff98ee47feeac2b0ae35b8/src/Illuminate/Foundation/Testing/RefreshDatabase.php#L60).

Because `ALTER TABLE` results in an [Implicit Commit](https://dev.mysql.com/doc/refman/5.7/en/implicit-commit.html) this change cannot be rolled back and I thought the database refresh would have failed. It didn't really fail thought. It just could not roll back this `ALTER TABLE` statement and that's what made me believe there was an issue. 

I'll keep that in mind and use my workaround since using such statements should be kind of a rare use case. Thank you guys.

**Comment by laurencei** [comment]
Interesting... thanks for reporting back...
