### ISSUE TITLE
All the sessions are getting logged out/wiped out frequently and automatically even when sessions are not idle

### ISSUE THREAD

**Issue by avinashs24** [laravel/framework#24177]
- Laravel Version: 5.5.13
- PHP Version: 7.1.9
- Database Driver & Version: MySQL 5.7.19

### Description:

All the users are getting logged out automatically after a few period of time while using our application. Session is not idle however. We have included a constant pinging with the server for every 10 seconds from the client. Our single app is being load balanced by 3 server instances. Currently we are using redis as session driver. Our redis server's CPU usage is very low. It doesn't seem to have a problem we guess. The same issue happened while using file as the session driver. We suspect there might be something happening in the laravel framework.

### Steps To Reproduce:
We could not reproduce it at required times. It happens very randomly.

1. Login multiple users to the application

2. Keep using the app without being idle.

3. Suddenly all the users get logged out.

**Comment by tillkruss** [comment]
That sounds very application specific and there is no way to reproduce this. Have a closer look at your Redis session keys and their expiry timestamp while you're using the app. Are they suddenly disappearing or actually just expiring? Are session keys expiry dates renewed after each page view?

**Comment by avinashs24** [comment]
I was monitoring the session data on my Redis Server. The data had a key named **login_web_(some_alpha_num_characters)** with the value 2091. At the instance when the logout issue happened for all the user sessions, the key went missing. Maybe the framework does this in a particular scenario causing all the sessions to expire. Looking to find any other approaches to narrow down the issue.

**Comment by tillkruss** [comment]
Can you log all Redis calls using `MONITOR` and see what command is causing this? This might narrow it down a bit.

**Comment by avinashs24** [comment]
Thanks for the tip. I will check.
