### ISSUE TITLE
[5.6] Cannot switch back to application frames in whoops screen

### ISSUE THREAD

**Issue by hubertnnn** [laravel/framework#24176]
- Laravel Version: v5.6.20
- PHP Version: 7.1.16-1+ubuntu16.04.1+deb.sury.org+1
- Whoops version: 2.1.14

### Description:
After switching stacktrace to "All frames" its impossible to switch back

### Steps To Reproduce:
1. Enable debug mode
2. Throw an exception
3. In whoops window click on "All frames" to show full stacktrace
4. Click on "Application frames" [nothing happens]

**Comment by tillkruss** [comment]
Please report to the Whoops repo.
