### ISSUE TITLE
artisan migrate:rollback error when have same class in another day

### ISSUE THREAD

**Issue by LindolfoJunior** [laravel/framework#24179]
- Laravel Version: 5.5.40
- PHP Version: 7.2
- Database Driver & Version: MySQL

### Description:
During the process of using rollback of migrations it informs that the class is being used in cases where I am changing a certain table.

### Steps To Reproduce:
1 - Create a model with migrate => php artisan make:model costumers -m
2 - Create a alter migration => php artisan make:migration alter_costumers --table=costumers
3 - Alter this table inserting a new collum for exemple name in up() and drop this Column on down()
4 - Execute migrate => php artisan migrate
5 - Create a new alter migration => php artisan make:migration alter_costumers --table=costumers
6 - Insert a new collum for exemple "email" in up() and drop this Column on down()74 - Execute migrate => php artisan migrate
7 - Execute migrate => php artisan migrate
8 - Execute Rollback => php artisan migrate:rollback

### The erro is:
PHP Fatal error:  Cannot declare class AlterGpsMarkers, because the name is already in use in C:\wamp\www\site\database\migrations\yyyy_mm_dd_hhiiss_alter_costumers.php on line 36

In yyyy_mm_dd_hhiiss_alter_costumers.php line 36:

Cannot declare class AlterCostumers, because the name is already in use

**Comment by sisve** [comment]
Could you give us the code needed to reproduce the problem? It sounds like you're declaring another AlterGpsMarkers class in the AlterCustomers migration.

**Comment by laurencei** [comment]
@LindolfoJunior - what @sisve said - the problem is you cannot have:

```
2018_01_01_00001_Alter_Costumers.php 
2018_01_01_00002_Alter_Costumers.php 
```

Even though they are different timestamped files names - they have the same class name of `AlterCostumers`

Your only way around is like

```
2018_01_01_00001_Alter_Costumers_Add_Name.php 
2018_01_01_00002_Alter_Costumers_Add_Gps.php 
```

and dont forget `composer dump` - because that is used during a `down` migration.

Alternatively just use `php artisan migrate:fresh` and you dont need down at all

**Comment by LindolfoJunior** [comment]
@sisve and @laurencei 

In a production environment we use the migrations to control the changes executed in the database (versioning), with this I am using and creating according to what I am changing in the bank, for example, I want to include a new field, I go in the migration and I use the so I can see what table / view / procedure / function I'm changing and when I get a rollback error, the question is, should not it execute the rollback in the executed migration regardless of other previous changes?

**Comment by laurencei** [comment]
@LindolfoJunior - yes, but you just need to name the classes differently. The functionality will work.

**Comment by LindolfoJunior** [comment]
@laurencei tks. 
I'm using now the timestamp on creation of migration file and this effects the class name but, in my opinion, this evolution can be added to laravel's core to make more efficient on artisan use in projects like this:

![image](https://user-images.githubusercontent.com/38046370/39952792-cf37ad2e-5574-11e8-8d1d-974c815aa553.png)

Again, tks for your attention.
