### ISSUE TITLE
Validation - Conditional Sometimes Rule

### ISSUE THREAD

**Issue by Braunson** [laravel/framework#24182]
- Laravel Version: 5.5.40
- PHP Version: 7.1.10
- Database Driver & Version: MySQL v14.14

### Description:
Validation returns both false for `passes()` and `fails()` when there is a failedRule and message in the error bag.

### Steps To Reproduce:

Put this custom sometimes conditional rule in your `AppServiceProvider.php` `boot()` method.

```php
Validator::extend('conditionalSometimes', function ($attribute, $value, $parameters, $validator) {
	$type = $parameters[0];
	$referenceColumn = $parameters[1];
	$referenceValue  = $parameters[2];

	return $validator->sometimes($attribute, $type, function($requestData) use ($referenceColumn, $referenceValue) {
		return $requestData->{$referenceColumn} == $referenceValue;
	});
}, 'The :attribute is not valid');
```

Put this in a route or a controller method for quick testing.

```php
$rules = [
   'spoke_to' => 'required|boolean',
   'lead_score' => 'required_if:spoke_to,1|nullable|conditionalSometimes:integer,spoke_to,1'
];

$data = [
   'spoke_to' => 1,
   // 'lead_score' => 1, // With this enabled it should pass
   'lead_score' => 'THIS IS WRONG', // With this enabled it should fail
];

$request->merge($data);

$validator = Validator::make($request->all(), $rules);

dump('Fails: ' . ($validator->fails() ? 'Yes' : 'No'));
dump('Passes: ' . ($validator->passes() ? 'Yes' : 'No'));
dd($validator);
```

The anticipated behavior of the rules should be this:
- if `spoke_to` is set to `1` then `lead_score` is `required`, and must be an `integer`
- if `spoke_to` is set to `0` then `lead_score` is not `required`

Results when run:
![Validation results](https://goo.gl/zjRYtW)

**Comment by tillkruss** [comment]
Remove nullable.

**Comment by Braunson** [comment]
@tillkruss Still the issue is is the same even with `nullable` removed. 

![Updated](https://goo.gl/UaxDor)

**Comment by tillkruss** [comment]
What's the result of `required_if:spoke_to,1|integer` work?

**Comment by Braunson** [comment]
@tillkruss Yes and no, a better example of why I was using `sometimes` custom conditional in the first place is described here https://github.com/laravel/framework/issues/17805

I've tried using `bail` even but if the `required_if` doesn't hit, then it still continues.

**Comment by tillkruss** [comment]
In that case this isn't a framework issue, it's your custom rule.

**Comment by Braunson** [comment]
@tillkruss Right but in this case it's the `sometimes` rule (I originally posted) acting oddly. How can the validator return both false for `passes` and `fails`?

**Comment by tillkruss** [comment]
No, of course not. I don't see any "sometimes" rule in your example.

**Comment by Braunson** [comment]
@tillkruss In the first post... in the `conditionalSometimes` rule

```
return $validator->sometimes($attribute, $type, function($requestData) use ($referenceColumn, $referenceValue) {
	return $requestData->{$referenceColumn} == $referenceValue;
});
```

**Comment by staudenmeir** [comment]
I found the problem:

`conditionalSometimes()` is called *while* `Validator::passes()` is iterating over `$rules`. So the new rule added by `Validator::sometimes()` only takes effect when `passes()` is called the *second time*. If you swap the two `dump()` lines, you get `"YES"` twice.

Apparently `Validator::sometimes()` is not meant to be used like that. You would have to add something like this to your controller:

    $validator->sometimes('lead_score', 'integer', function($requestData) {
        return $requestData->spoke_to == 1;
    });

**Comment by Braunson** [comment]
@staudenmeir ok that makes sense. The reason I put it in an extend is because I used this rule many many times over in many form requests (not a controller). Thank you for looking into this.
