### ISSUE TITLE
No application encryption key has been specified. Error on key generation

### ISSUE THREAD

**Issue by darron1217** [laravel/framework#24195]
- Laravel Version: 5.5.*
- PHP Version: 7.1.17
- Database Driver & Version: mysql 5.6

### Description:
I installed fresh laravel and ran command below
```
php artisan key:generate
```
Then got error...
```
In EncryptionServiceProvider.php line 42:

  No application encryption key has been specified.
```
![image](https://user-images.githubusercontent.com/8064923/39965118-4386cd04-56ce-11e8-8103-dae51c8e486c.png)

### Steps To Reproduce:
I'm currently using AsgardCMS https://github.com/AsgardCms/Platform
I was attempting to install it by `php artisan asgard:install` command.
(Laravel fresh install)

**Comment by laurencei** [comment]
Seems like a problem with the package to me. Remove it and just setup Laravel first - then add the package.

**Comment by darron1217** [comment]
I wondered if `php artisan key:generate` command can be affected by another package

This core and basic implement should not be affected by any attempt. I thought :)

**Comment by darron1217** [comment]
Thanks for your kind answer :)
I'll take a look at the package
