### ISSUE TITLE
Job Queue not working(not sending emails) in laravel after changing every single code

### ISSUE THREAD

**Issue by rishabhgoel9797** [laravel/framework#24208]
```
Route::get('sendEmail',function(){
	$job=(new sendEmailJob())
	->delay(Carbon::now()->addSeconds(5));
	dispatch($job);
	// sendEmailJob::dispatch()
	//             ->delay(now()->addSeconds(5));
	dd($job);
	return 'email is send properly';
});
```

what can be the issue?

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I suggest closing your issue ticket here? Instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.
