### ISSUE TITLE
FileNotFoundException($path);

### ISSUE THREAD

**Issue by alpharameeztech** [laravel/framework#24207]
- Laravel Version: 5.6.
- PHP Version: 7.1.17
- Database Driver & Version:

### Description:
I have a form that uploads a file. The file is being uploaded successfully on my local server but when I pushed my code to the server, it gives me this error and I don't know whats causing that
```
vendor/symfony/http-foundation/File/MimeType/MimeTypeGuesser.php
    /**
     * Tries to guess the mime type of the given file.
     *
     * The file is passed to each registered mime type guesser in reverse order
     * of their registration (last registered is queried first). Once a guesser
     * returns a value that is not NULL, this method terminates and returns the
     * value.
     *
     * @param string $path The path to the file
     *
     * @return string The mime type or NULL, if none could be guessed
     *
     * @throws \LogicException
     * @throws FileNotFoundException
     * @throws AccessDeniedException
     */
    public function guess($path)
    {
        if (!is_file($path)) {
            throw new FileNotFoundException($path);
        }
 
```
Under the POST Data, under Files

```
picture 
array:5 [▼
  "name" => "1.jpg"
  "type" => ""
  "tmp_name" => ""
  "error" => 6
  "size" => 0
]
```

for further details, go here https://laracasts.com/discuss/channels/laravel/filenotfoundexceptionpath

**Comment by Quezler** [comment]
Can you share the piece of code that calls the mime guesser?

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I suggest closing your issue ticket here? Instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.

**Comment by laurencei** [comment]
No dramas. FYI - you want to search for "php upload error 6" to try to find your answer.

This is one possible solution: https://stackoverflow.com/questions/27099537/upload-file-to-web-server-error-6-php
