### ISSUE TITLE
tap($model)->belongsToRelation() returns Builder instead of BelongsTo

### ISSUE THREAD

**Issue by maantje** [laravel/framework#24218]
- Laravel Version: 5.6
- PHP Version: 7.2
- Database Driver & Version: n/a

### Description:

Using tap with a belongs to relation returns a Builder instead of a BelongsTo

### Steps To Reproduce:

Make a user model for example and add a belongsTo relation

```
/**
* @return BelongsTo
*/
public function role(): BelongsTo
{
    return $this->belongsTo(Role::class);
}
```

Add a method like the following

```
/**
* @param Role $role
* @return User
*/
public function assignRole(Role $role): self
{
    return tap($this)->role()->associate($role)->save();
}
```

When using the method you get an error ```BadMethodCallException with message 'Method Illuminate/Database/Query/Builder::associate does not exist.```

**Comment by staudenmeir** [comment]
Why are you using `tap($this)`?

**Comment by staudenmeir** [comment]
You have to use `tap()` with a callback:

    return tap($this->role()->associate($role), function($user) {
        $user->save();
    });

Or shorter:

    return tap($this->role()->associate($role), function() {
        $this->save();
    });

**Comment by maantje** [comment]
I see the tap($this)->roles() now returns $this and associate then obviously does not work I got confused with the exception being ```Method Illuminate\Database\Query\Builder::associate does not exist.``` and not talking about User. I changed it to ```return tap($this->role()->associate($role))->save();```
