### ISSUE TITLE
Max connections stacktrace exposes database credentials

### ISSUE THREAD

**Issue by CliffBrown** [laravel/framework#24226]
- Laravel Version: 5.3
- PHP Version: 5.6
- Database Driver & Version: MySQL 5.7

### Description:
Max connections error produces a stacktrace that exposes connection credentials, including the password. This seems like a security risk.

```
Next exception 'Doctrine\DBAL\Driver\PDOException' with message 'SQLSTATE[HY000] [1203] User username already has more than 'max_user_connections' active connections' in /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47
Stack trace:
#0 /home/esms/public_html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(116): Doctrine\DBAL\Driver\PDOConnection::__construct('mysql:host=loca...', 'username', 'PASSWORD', Array)
```
### Steps To Reproduce:
* Trigger a max_connecitons error
* View stack trace, which includes the connection password

**Comment by tillkruss** [comment]
Make sure you set `APP_DEBUG` to `false` in `production`.
