### ISSUE TITLE
Pagination throwing Exception

### ISSUE THREAD

**Issue by TheTechnoMan** [laravel/framework#24225]
- Laravel Version: 5.6.22
- PHP Version: 7.1.11

### Description:

Hello, I am having an issue with the Pagination. It throws an exception.

I do this:

    $topics = Topic::where('category_id', '=', $id)->paginate(10);

that works fine. However, as soon as I add

`{{ $topics->render() }}`

to the view, in order to display the pagination, it throws:

> call_user_func() expects parameter 1 to be a valid callback, no array or string given

`$topics` looks like that:

    LengthAwarePaginator {#513 ▼
      #total: 267
      #lastPage: 27
      #items: Collection {#572 ▼
        #items: array:10 [▶]
      }
      #perPage: 10
      #currentPage: 1
      #path: "/"
      #query: []
      #fragment: null
      #pageName: "page"
    }

Stacktrace: https://pastebin.com/2cMQJAG7

**Comment by Gewora** [comment]
@tillkruss: Why was this issue closed without any reponse?

**Comment by TheTechnoMan** [comment]
@tillkruss: Why was this issue closed without any reponse?

**Comment by tillkruss** [comment]
>Please use this issue tracker only for reporting Laravel bugs.

**Comment by TheTechnoMan** [comment]
I did. This does appear to be a bug, I did a basic eloquent request and applied the pagination that resulted in this issue...

**Comment by tillkruss** [comment]
Please post a test case that validates this bug.

**Comment by TheTechnoMan** [comment]
After re-reading them I have to admit that they all differ from my case. One of them had a very specific query and one of them just used the laravel paginator.

I asked this on stackoverflow a couple of days ago and did not get any response.

I would appreciate if someone could look at the stracktrace. This does look like an issue with the views, but I am unable to figure out what causes this. I did not specify custom views or something like that.

Thanks..

**Comment by TheTechnoMan** [comment]
static::viewFactoryResolver is null when being requested by the viewFactory method of ApstractPaginator.

**Comment by devcircus** [comment]
Best way to narrow it down and confirm a bug with the laravel codebase, is to create a new laravel app and recreate the issue. If the issue isn't there in a fresh install, then likely it is a problem specific your app and you'll have to trace down what is actually causing the issue. 

As for a test, if it is simply as you described in the original post, a test shouldn't be too difficult to write. The test shouldn't be specific to your app.

**Comment by sisve** [comment]
It sounds like you've forgotten to enable the PaginationServiceProvider in config/app.php

**Comment by TheTechnoMan** [comment]
@sisve: Now I feel really silly, you're absolutely right... Thanks a lot!
