### ISSUE TITLE
HSCAN in PHPRedis is not iterating properly

### ISSUE THREAD

**Issue by ragingdave** [laravel/framework#24222]
- Laravel Version: 5.6.21
- PHP Version: 7.1
- Database Driver & Version: NA
- Redis Extension Version: 4.0.2

### Description:
The hscan and perhaps additional commands are broken when using phpredis vs predis.
Predis has a completely different return syntax, which includes the cursor and results.
PHPRedis returns only the results and seems to use the $cursor ($it in their examples) by reference rather than by value some something ends up getting lost. Additionally, predis starts with $it/$cursor of 0, wheras PHPRedis starts with null.

### Steps To Reproduce:
Using laravel and it's redis facade:

```php
for ($x = 0; $x < 100; $x++) {
    Redis::incrby('test_key', uniqid(), 1);
}

$it = null;
// Redis connection in Laravel already has the OPTs set shown in the readme.
do {
    $return = Redis::hscan('test_key'); // FAILS missing arg
    $return = Redis::hscan('test_key', 0); // Returns false
    $return = Redis::hscan('test_key', null); // Returns the same 10 records over and over forever
} while (!$empty($return));
```

**Comment by tillkruss** [comment]
Laravel uses Predis as a base line and it adjusts PhpRedis return values to same results in [`PhpRedisConnection`](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Redis/Connections/PhpRedisConnection.php).

If you can, please submit a PR to 5.6 to fix the return value `HSCAN`. I'd assume `SCAN`, `SSCAN` and `ZSCAN` are broken as well?

**Comment by tillkruss** [comment]
Great to hear. Whatever gets us the closest experience to Predis we can handle internally. if PhpRedis gets an update, we can always adjust.

**Comment by tillkruss** [comment]
Puh, yeah I'd assume the same, if the connection has a prefix, it should add it to the scan. I'd suggest you break up the PRs, one for fixing the `SCAN` methods, and one for prefix fixes. That way Taylor can decide whether or not to merge the prefix changes.

**Comment by ragingdave** [comment]
Would altering the assertions based on if the connection is prefixed be an acceptable bypass at this point to at least have the functions fixed and the unit tests pass? Either that or I could most likely just pass to the connections() method a param whether or not to test prefix. I'm guessing that committing default failed tests isn't the right way to handle this...

**Comment by tillkruss** [comment]
I'd test two separate connections.
