### ISSUE TITLE
Redundant namespace Schema after make:migration

### ISSUE THREAD

**Issue by projct1** [laravel/framework#24220]
- Laravel Version: 5.6.20
- PHP Version: 7.1

### Description:
After command `php artisan make:migration` path `use Illuminate\Support\Facades\Schema;` is redundant:
```php
use Illuminate\Support\Facades\Schema; //all fine without this path
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class UpdateAuditsTable extends Migration
{
    public function up()
    {

    }

    public function down()
    {

    }
}
```

**Comment by ntzm** [comment]
It's a commonly used import, so it's kept in there for convenience's sake. You're free to remove it!
