### ISSUE TITLE
Eloquent tries to fetch relationship for non persisted model instances.

### ISSUE THREAD

**Issue by jonnsl** [laravel/framework#24241]
- Laravel Version: 5.5.40 & 5.6.22
- PHP Version: PHP 7.2.4
- Database Driver & Version: Any

### Description:
Eloquent will try to fetch relationship even if model isn't persisted yet.

### Steps To Reproduce:
Given the Models:
```php
Class A extends Model{}
Class B extends Model
{
    public function a()
    {
        return $this->hasOne(A::class)->withDefault();
    }
}
```
Trying to access/load the relationship 'a': 
```php
(new B)->getRelationValue('a');
```
Eloquent will try to fetch the related model with this query:
```sql
select * from `a_s` where `a_s`.`b_id` is null and `a_s`.`b_id` is not null
```
Which obviously will return nothing, so a default model will be generated and returned.
#### Expected Behavior 
If the model is not persisted, no query should be issued at all, and the default returned right away.

**Comment by laurencei** [comment]
But there *could* be a relation there. For example - if you have events or defaults triggered when a new model is created.

**Comment by 36864** [comment]
A model doesn't know if it's persisted or not.

This also allows someone to get a model id's relationships without actually fetching the model first:
```
$student = new Student();
$student->id = 1;
$student->grades;
```

**Comment by jonnsl** [comment]
Maybe `Relation::getResults()` could first verify if it has all foreign keys necessary to fetch the related models before trying to do so.
e.g. for the HasOne relation:
```php
public function getResults()
{
    if (is_null($this->getParentKey()) {
        return $this->getDefaultFor($this->parent);
    }

    return $this->query->first() ?: $this->getDefaultFor($this->parent);
}
```
