### ISSUE TITLE
artian queue:restart not working at all

### ISSUE THREAD

**Issue by darron1217** [laravel/framework#24242]
- Laravel Version: 5.5
- PHP Version: 7.1
- Database Driver & Version: mysql 5.6

### Description:
It seems artian queue:restart not working with cache driver array

Processes never stop on `php artisan queue:restart`

I'm currently using database queue driver
with config below
`.env`
```
CACHE_DRIVER=array
QUEUE_DRIVER=light
```

`queue.php`
```php
    'connections' => [
        'sync' => [
            'driver' => 'sync',
        ],
        'light' => [
            'driver' => 'database',
            'table' => 'jobs',
            'queue' => 'light',
            'retry_after' => 60,
        ],
        'heavy' => [
            'driver' => 'database',
            'table' => 'jobs',
            'queue' => 'heavy',
            'retry_after' => 60,
        ],
    ],
```

`supervisord.conf`
```
[program:worker-light]
command=php /var/www/html/artisan queue:work light --queue=light,default --sleep=3 --tries=3
autostart=true
autorestart=true
user=root
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/worker-light.log

[program:worker-heavy]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan queue:work heavy --queue=heavy --sleep=3 --tries=1
autostart=true
autorestart=true
user=root
numprocs=4
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/worker-heavy.log
```

**Comment by sisve** [comment]
You are correct.

The `queue:restart` works by setting a timestamp in the cache, and the queue workers check this value in their main loop. Any new value means they will shut down, and count on a process manager to restart them. So there's both a requirement on shared cache, there's also the fact that a command named "restart" doesn't restart. If you had been using a shared cache like redis, then _all_ queue workers on all your servers will restart, not just the ones on your local machine.

I believe that the proper way to handle the queue workers during a deploy, and I presume this is for deploy purposes, is to stop the workers, do what you need to do, then start the workers.

    supervisorctl stop worker-light:*
    supervisorctl stop worker-heavy:*
    
    // do the deploy stuff
    
    supervisorctl start worker-light:*
    supervisorctl start worker-heavy:*

Using supervisorctl in this way will block/wait for the jobs to complete before doing the deploy. This means that there's no job that has old code already loaded, that can load some new code, or perhaps some something else in a weird state.

If you're just doing development and want jobs to pick up new source changes, use `php artisan queue:listen` in a terminal instead.

**Comment by darron1217** [comment]
After reading your answer,
I succeeded solving this issue by changing cache driver to redis

Thanks for your kind answer :)
