### ISSUE TITLE
Laravel eloquent custom primary key not working

### ISSUE THREAD

**Issue by ghasemikasra39** [laravel/framework#24253]
- Laravel Version: 5.6
- PHP Version: 7.2.2
- Database Driver & Version: XAMPP 3.2.2

### Description:
Please visit this link. The problem has been discussed here:
https://stackoverflow.com/questions/50427147/laravel-eloquent-relationship-getting-property-on-non-object

**Comment by staudenmeir** [comment]
Please close the issue.
