### ISSUE TITLE
Monolog  - MongoDBHandler - MongoDB\Client 

### ISSUE THREAD

**Issue by mohamedziada** [laravel/framework#24259]
- Laravel Version: 5.6.22
- PHP Version: 7.2
- Database Driver & Version: Mysql  5.7, MongoDB 3.6.4

### Description:
Current Monolog version is   "monolog/monolog": "~1.12"
This version of Monolog didn't support the new MongoDB functionality with php >= 7.0
The \Monolog\Handler\MongoDBHandler.php expects a MongoDB\Client which is "This extension that defines this class is deprecated" as PHP manual http://php.net/manual/en/class.mongoclient.php

### Steps To Reproduce:
using   "monolog/monolog": "dev-master" which is support MongoDBHandler for new  MongoDB extension.

**Comment by gmsantos** [comment]
It's not a Laravel issue and should be addressed to [monolog](https://github.com/Seldaek/monolog) instead.

Related https://github.com/Seldaek/monolog/issues/962
