### ISSUE TITLE
Queue Failed_jobs issue with Exception contain UNICODE 

### ISSUE THREAD

**Issue by boomhq** [laravel/framework#24263]
- Laravel Version:5.5, 5.6
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7

### Description:
Hi guys, i have an issue with method log in \Illuminate\Queue\Failed\DatabaseFailedJobProvider.

When Exception provided contain non UTF8 char (like "Aucune connexion n�a pu �tre �tablie" in french transmtited by SwiftMailer) an error occur.

In laravel.log
`[2018-05-21 11:33:47] local.ERROR: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\x92a pu ...' for column 'exception' at row 1 (SQL: insert into `failed_jobs` (`connection`, `queue`, `payload`, `exception`, `failed_at`) values (database, default, {"displayName" ...}, Swift_TransportException: Connection could not be established with host 127.0.0.1 [Aucune connexion n�a pu �tre �tablie car l�ordinateur cible l�a express�ment refus�e.
 #10061]  \vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\StreamBuffer.php:269`

In \Illuminate\Queue\Failed\DatabaseFailedJobProvider :

If i escape the $exception with an utf8_encode all run normally and the failed  job can it write in failed_job table. I have no idea if it's the good way to fix this.

```php
public function log($connection, $queue, $payload, $exception)
    {
        $failed_at = Carbon::now();

         $exception = (string) utf8_encode($exception);

        return $this->getTable()->insertGetId(compact(
            'connection', 'queue', 'payload', 'exception', 'failed_at'
        ));
    }
```

Thanks

**Comment by rbur0425** [comment]
try switching your database charset to utf8mb4 so it allows full unicode

**Comment by boomhq** [comment]
Hi @rbur0425.  I'm already on utf8mb4_unicode_ci.
At this time i have Override DatabaseFailedJobProvider by my Own handler for fix tis.

**Comment by boomhq** [comment]
> @boomhq Looks like this is happening to me as well. Could you share why you closed the ticket? Any solutions?

No idea why i have closed it. Bug always here for me.


At this time quick fix with : 

`<?php

namespace App\Override\Queue;

use Illuminate\Queue\Failed\DatabaseFailedJobProvider;
use Illuminate\Support\Carbon;

class DatabaseFailedJobFixedUnicodeProvider extends DatabaseFailedJobProvider
{
    /**
     * Log a failed job into storage. Override a cause d'un bug de encodage empechant le log du fail
     *
     * @param string     $connection
     * @param string     $queue
     * @param string     $payload
     * @param \Exception $exception
     *
     * @return int|null
     */
    public function log($connection, $queue, $payload, $exception)
    {
        $failed_at = Carbon::now();

        $exception = (string) utf8_encode($exception);

        return $this->getTable()->insertGetId(compact(
            'connection',
            'queue',
            'payload',
            'exception',
            'failed_at'
        ));
    }
}
`
`<?php

namespace App\Providers;

use App\Override\Queue\DatabaseFailedJobFixedUnicodeProvider;
use Illuminate\Queue\Events\JobFailed;
use Illuminate\Queue\Events\JobProcessed;
use Illuminate\Queue\Events\JobProcessing;
use Illuminate\Queue\Failed\NullFailedJobProvider;
use Illuminate\Support\Facades\Queue;
use Illuminate\Support\ServiceProvider;

class QueueServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     */
    public function boot()
    {
        // On récupere l'instance par defaut dans notre app
        $_ = $this->app['queue.failer'];
        // On  échange avec notre implementation en récuperant la config par defaut
        $this->app->singleton('queue.failer', function ($app) {
            $config = $this->app['config']['queue.failed'];

            return isset($config['table'])
                ? $this->databaseFailedJobProvider($config)
                : new NullFailedJobProvider();
        });
    }


    protected function databaseFailedJobProvider($config)
    {
        return new DatabaseFailedJobFixedUnicodeProvider(
            $this->app['db'],
            $config['database'],
            $config['table']
        );
    }
}
`

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by monaye** [comment]
@driesvints I opened the new issue here with steps to reproduce https://github.com/laravel/framework/issues/41016

@boomhq do you want to open the PR for the fixes?

**Comment by boomhq** [comment]
@monaye I don't think that's the cleanest way to do it. Because forcing "utf8_encode".

For my fix just place the first file in  App\Override\Queue;
And the second on App\Service provider, (or call from AppServiceProvider)
