### ISSUE TITLE
HasInDatabase not compatible with phpunit 7.1.5

### ISSUE THREAD

**Issue by webmake** [laravel/framework#24269]
- Laravel Version: 5.5.40
- PHP Version: 7.1

### Description:
After upgrading phpunit version to 7.1.5 there is some errors
```
PHP Fatal error:  Declaration of Illuminate\Foundation\Testing\Constraints\HasInDatabase::matches($table) must be compatible with PHPUnit\Framework\Constraint\Constraint::matches($other): bool in /home/docker/src/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Constraints/HasInDatabase.php on line 103
```
, due method `assertDatabaseHas` in `InteractsWithDatabase` trait. I have found that there exists only 3 methods to upgrade: 
`public function matches($table): bool`
`public function failureDescription($table): string`
`public function toString($options = 0): string`

https://github.com/sebastianbergmann/phpunit/commit/a7ab2b9b53c88a9020babcd547d6d71279fba087#diff-9b9d6dcc113db91a2499d96be8be3415

**Comment by staudenmeir** [comment]
Laravel 5.5 doesn't support PHPUnit 7.

**Comment by webmake** [comment]
As I said, only 1 test out of 1k other test failed for me, there is nothing blocking to upgrade phpunit. Otherwise you should forbid to upgrade phpunit with constraint, now it is fully compatible except mentioned exception

**Comment by staudenmeir** [comment]
`"phpunit/phpunit": "~6.0"` kind of forbids it.

**Comment by webmake** [comment]
But laravel components do not restrict. If I can rise version - I do so. Otherwise I should not be allowed to rise `composer.json`, because other components restrict to do so.

**Comment by webmake** [comment]
For example I could not upgrade any symfony to 4.0, because other libraries blocks it.
```
"name": "laravel/framework",
...
                "symfony/console": "~3.3",
                "symfony/debug": "~3.3",
                "symfony/finder": "~3.3",
                "symfony/http-foundation": "~3.3",
                "symfony/http-kernel": "~3.3",
                "symfony/process": "~3.3",
                "symfony/routing": "~3.3",
                "symfony/var-dumper": "~3.3",
```
dev dependencies aren't restricted

**Comment by webmake** [comment]
Steps to reproduce:
$ mkdir test
$ cd test
$ composer create-project --prefer-dist laravel/laravel project "5.5.*"
```
  - Installing phpunit/phpunit (6.5.8): Loading from cache
```
that's ok. Now further
$ cd project
$ nano composer.json
on 16 line edit version to this:
        "phpunit/phpunit": "*",
$ composer update
Guess what:
```
  - Updating phpunit/phpunit (6.5.8 => 7.1.5): Loading from cache
```
Now I have latest version, without any problem. This issue not closed until problem exists, otherwise somehow you should not allow upgrade phpunit, otherwise update 3methods.

**Comment by webmake** [comment]
I don't understand where is the problem to update `HasInDatabase` class because, 
`    public function matches($table): bool`
declaration compatible with phpunit 6.*
`    protected function matches($other)`
And all tests are passing in project (there is a lot), so there is no such breaking changes
