### ISSUE TITLE
5.4 validating multiple upload max cannot show custom error

### ISSUE THREAD

**Issue by ezekel** [laravel/framework#24273]
I am validating my upload file array , I tried to limit to 3mb and show error if its greater than.

```
  $validator = Validator::make($request->all(), [
                'myuploadarrayfile' => 'required',
                'myuploadarrayfile.*' => '|image|mimes:jpg,jpeg,png|max:3000',
            ],[
                'myuploadarrayfile.required' => 'Please upload image',
                'myuploadarrayfile.*.mimes' => 'Only jpeg,jpg and png images are allowed',
                'myuploadarrayfile.*.max' => 'File is too big upload only 3MB file size',
            ]

           if ($validator->fails()) {
                return Response::json(array(
                    'errors' => $validator->getMessageBag()->toArray(),
                    'success'=>false
                ), 422);
            }
```
but I get this response

```
{
    "errors": {
        "myuploadarrayfile.0": [
            "The myuploadarrayfile.0 failed to upload."
        ]
    },
    "success": false
}
```

I wan't to show "File is too big upload only 3MB file size" I know my code is correct because that is how the laravel docs says.

Thank you in advance.

**Comment by laurencei** [comment]
It's probablable that your PHP max filesize is not 3mb? It's probably 2mb by default, and your exceeding that?

**Comment by ezekel** [comment]
@laurencei 

I have this configuration 

memory_limit = 128M
post_max_size = 128M
upload_max_filesize = 100M

**Comment by staudenmeir** [comment]
It works on 5.6. Does the `myuploadarrayfile.*.mimes` message work?

**Comment by GrahamCampbell** [comment]
Please ask on the forums. I don't think this is a bug in the Laravel core. :)

**Comment by ezekel** [comment]
@staudenmeir i have not tested on 5.6.. myuploadarayfile.*.mimes the custom message is not working..it will display the defult message. @GrahamCampbell if I ask to forum they will ask the same question for me...I think it is a bug in 5.4..or maybe I miss something...
I  display the custom message by removing  the mimes...here myuploadfilearray.*=>"File is too big"

**Comment by ezekel** [comment]
Ok it's working now  sorry for my post
