### ISSUE TITLE
developing laravel application without internet

### ISSUE THREAD

**Issue by Ubaidurrehmanciit** [laravel/framework#24272]
I am working in an organization where i Have to start projects in laravel, but the problem there is that we are working on remote desktop i.e., without internet and without copy & paste of code. Is there any way to develop my web applications on remote desktop?
can I download the laravel source code and start development?
If Yes, how will I update packages or make commands on composer as composer downloads from internet?

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I suggest closing your issue ticket here? Instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.

**Comment by Ubaidurrehmanciit** [comment]
Thanks
