### ISSUE TITLE
Confusing optional dependency when altering columns

### ISSUE THREAD

**Issue by igorsantos07** [laravel/framework#24271]
- Laravel Version: 5.6
- PHP Version: 7.2
- Database Driver & Version: PostgreSQL 10.x (unrelated)

### Description:
If the user tries to write a migration following their guts and IDE auto-completion, they might stumble upon a "weird" dependency issue that's not solvable by running `composer install` again ("who knows, maybe the other package I included caused some unsolved conflict?).

According to a small section in the migrations documentation, you need to require `doctrine/dbal` for changes in columns to work. And that seems to be mentioned during initial installation as well (probably, together with a lot of other package recommendations). However, that's simply not enough for a couple of cases, such as:

-  entering a project where that dependency wasn't needed/included before (my case)
- simply overlooking the list of package suggestions

Then, the user is confronted with a generic exception stating something is not where it should be.

My suggestion is to create a try..catch for such cases that would return a more comprehensive exception, stating the issue is probably caused by a missing optional dependency called `doctrine/dbal`. Bonus points if there was a link to the missed doc section.

It's fairly easy to find a bunch of developers stumbling upon the same issue: #785, #3116, [SO 1](https://stackoverflow.com/questions/48851020), [SO 2](https://stackoverflow.com/questions/33817983), [Laracasts Forum 1](https://laracasts.com/discuss/channels/laravel/laravel-51-class-doctrinedbaldriverpdosqlitedriver-not-found), [Laracasts Forum 2](https://laracasts.com/discuss/channels/laravel/pdomysql-driver-not-found)

### Steps To Reproduce:
1. Install a fresh Laravel project
2. Create a migration that rename a column (say, rename `users.name` to `users.full_name`
3. Try to run migration
4. Receive a generic error: `Symfony\Component\Debug\Exception\FatalThrowableError  : Class 'Doctrine\DBAL\Driver\PDOPgSql\Driver' not found`

**Comment by themsaid** [comment]
feel free to open a PR.
