### ISSUE TITLE
dispatch function return

### ISSUE THREAD

**Issue by jiyis** [laravel/framework#24275]
In version 5.4, dispatch ($job) returns a jobId, but after upgrading version 5.5, it returns an object.
I compared the two versions and found different ways of implementation.
version 5.4
```php
function dispatch($job)
{
     return app(Dispatcher::class)->dispatch($job);
}
```
version 5.5+
```php
function dispatch($job)
{
     return new PendingDispatch($job);
}
```
I want to get a jobId，because other services need it for polling queue consumption results. 

Thank you in advance.

**Comment by GrahamCampbell** [comment]
Please ask on the forums, since this is not a bug report in the core. :)

**Comment by devcircus** [comment]
Check out the 5.4 to 5.5 upgrade guide. This issue is addressed there.
https://laravel.com/docs/5.5/upgrade

**Comment by jiyis** [comment]
yep...  got it,Thansk you.^_^
