### ISSUE TITLE
[5.6.23] Error in artisan key:generate

### ISSUE THREAD

**Issue by misog** [laravel/framework#24288]
- Laravel Version: 5.6.23
- PHP Version: 7.2.2
- OS: Windows 8.1

### Description:
Illuminate\Routing\Router::loadRoutes(): Failed opening required 'D:\laragon\www\kariera\routes/api.php'
  (include_path='.;D:/laragon/etc/php/pear')

![image](https://user-images.githubusercontent.com/6667651/40418071-a6d3c910-5e81-11e8-9eb5-3887c8948585.png)

### Steps To Reproduce:
`laravel new kariera` or `php artisan key:generate`

**Comment by staudenmeir** [comment]
Does the `routes/api.php` file exist?
