### ISSUE TITLE
Supress error in method delete of Filesystem

### ISSUE THREAD

**Issue by Smolevich** [laravel/framework#24287]
- Laravel Version: 5.6.18
- PHP Version: 7.2
- Database Driver & Version:

### Description: 
Why in this line [Filesystem method delete](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Filesystem/Filesystem.php#L183) is used the operator `@` that supress error and execution is never catched on line 187

**Comment by sisve** [comment]
I don't think it's clear what issue you're attempting to report? Are you just trying to start a discussion? There's better places for that, like Larachat forums or on Slack.

**Comment by Smolevich** [comment]
Thanks. I join to slack channel.
