### ISSUE TITLE
I logged in,but `Auth::user()` return null.

### ISSUE THREAD

**Issue by chuoke** [laravel/framework#24280]
[5.6] Why Auth::user() return null after logged in, and how does it work? 

- Laravel Version: 5.6
- PHP Version: 7.2

### Description:
I logged in,but `Auth::user()` return null.
Let me show you what hapened.

Route:
```php
Route::namespace('Users')->group(function () {
   // the middleware auth not work
    Route::get('/@{username}', 'UserController@home')->middleware('auth')->name('user.home');
   dd(Auth::user()); // return null
});
```
Controller:
```php
    public function __construct()
    {
        $this->middleware('auth'); // not work
        dd(Auth::check()); // false
    }

    public function show()
    {
        return view('users.test', ['user' => Auth::user()]); // worked,
    }
```
And also `Auth::user()` worked in view.

I'm a beginner, I googled and found so many people have this problem,but no one can illuminate .
I want to know how does `Auth::user` work ? where (when) can I use it with happy.

**Comment by rs-sliske** [comment]
you cant access session data in controller constructor
