### ISSUE TITLE
CSRF token regeneration

### ISSUE THREAD

**Issue by sahilgoel755** [laravel/framework#24286]
Laravel Version: 5.5
PHP Version: 7.0
Database Driver & Version: MySQL

**Description:**
When i am using the session driver as '**file**' then my CSRF token remains same during the page refresh's and all the form submits successfully but when ever i change the session driver to the '**memcached**', then Laravel generates a new CSRF token each time when the page is refreshed, resulting in the Token Mismatch exception (Page expired).

Please have a look at the issue.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I suggest closing your issue ticket here? Instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.

**Comment by sahilgoel755** [comment]
Maybe this is an issue with the framework code.
Please have a look one time...

**Comment by dpak1919** [comment]
please reopen this page . i am also facing the same issue. no actual solution found yet
