### ISSUE TITLE
DatabaseTransactions not working with non-default connection with MySql 5.7

### ISSUE THREAD

**Issue by stebogit** [laravel/framework#24296]
- Laravel Version: 5.5.40
- PHP Version: 7.1
- Database Driver & Version: 5.7.18 (MAMP)

In my case looks like the `DatabaseTransactions` trait does not work properly (the database is being modified). This is a sample of my test setup, nothing special:

```php
namespace Tests\Unit;

use App\Http\Controllers\Dashboard\WeatherForecastController;
use App\ORM\Weather\Stations\Station;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Tests\TestCase;

class WeatherForecastControllerTest extends TestCase
{
    use WithoutMiddleware;
    use DatabaseTransactions;

    public function setUp()
    {
        parent::setUp();
        Station::truncate();
        Station::insert([['station_id' => ... ], ['station_id' => ... ]]);
    }

    public function testNoaaForecast() {...}
}
```
These are my connections:
```php
// config/database.php

'default' => 'das',

'connections' => [
    'das' => [
        'driver' => 'mysql',
        // credentials here...
        'unix_socket' => '',
        'charset' => 'utf8mb4',
        'collation' => 'utf8mb4_unicode_ci',
        'prefix' => '',
        'strict' => false,
        'engine' => null,
    ],
    'weather' => [
        'driver' => 'mysql',
        // credentials here...
        'unix_socket' => '',
        'charset' => 'utf8mb4',
        'collation' => 'utf8mb4_unicode_ci',
        'prefix' => '',
        'strict' => false,
        'engine' => null,
    ],
],
```
I found https://github.com/laravel/framework/issues/16682, which was closed right away, and also read [this](https://laracasts.com/discuss/channels/laravel/databasetransaction-not-working?page=1).
They are both quite old posts, but I couldn't find anything newer so I was wondering if the issue is actually still there; not sure if it is the MySql version or the non-default connection though.

Thanks.

**Comment by thecrypticace** [comment]
Define a `connectionsToTransact` property in your test:

```php
protected $connectionsToTransact = ["das", "weather"];
```

https://github.com/laravel/framework/blob/5bd6c713a8b0c7716236c2d0485d4f20927a4866/src/Illuminate/Foundation/Testing/DatabaseTransactions.php#L35-L39

**Comment by stebogit** [comment]
Oh, super! Thanks @thecrypticace I'll try that 👍

**Comment by adamcameron** [comment]
Tangentially...

> Define a `connectionsToTransact` property in your test:
> 
> ```
> protected $connectionsToTransact = ["das", "weather"];
> ```
> https://github.com/laravel/framework/blob/5bd6c713a8b0c7716236c2d0485d4f20927a4866/src/Illuminate/Foundation/Testing/DatabaseTransactions.php#L35-L39

Looking into this as a fix for this situation... isn't this code a bug?

```
return property_exists($this, 'connectionsToTransact') 
                         ? $this->connectionsToTransact : [null];
```

The fallback value should be `[]` surely, not an array with a null in it? That value is - as far as I can tell - only ever used in this sort of situation:

```
foreach ($this->connectionsToTransact() as $name) {
    $database->connection($name)->beginTransaction();
}
```
And I can't see how `null` is ever a valid value for `$name` to have. However if the default value was `[]`, then the loop doesn't happen, which seems to be what the desired behaviour is?

I'm asking cos I'm getting a situation where I don't have any "connections to transact", so the method is falling back to the default value, which in turn just errors-out because - unsurprisingly - I have no connection called `null`.

**Comment by thecrypticace** [comment]
No, in this case `null` implies the default connection.
