### ISSUE TITLE
Numeric keys aren't preserved in resources

### ISSUE THREAD

**Issue by anqiraj** [laravel/framework#24302]
- Laravel Version: 5.6.3
- PHP Version:7.1
- Database Driver & Version: Not applicable

### Description:
When having an ObjectResource, and one of the keys has for value an array with numeric keys, the keys are not preserved.

### Steps To Reproduce:
Create an ObjectResource,
Put the following code:
`return [
    'id' => [
        555 => 'test1',
        556 => 'test2
    ]
];`

The result is the following one:
`[
    {
        "id": [
            "test1",
            "test2"
        ]
    }
]`

=> The keys are not preserved.

This bug was introduced in this commit: https://github.com/laravel/framework/commit/a4e414f4df7ebcead71eddc5c5efa3eeacbc81ff#diff-2cafcb27e3268a6371128df68acfee8c

A temporary workaround I found is to surround my array with « collect ».

A solution could be to replace `! empty($data) && is_numeric(array_keys($data)[0])` with  `! empty($data) && $numericKeys` since $numericKeys is not used anywhere in the function, but I don't know the implication of this fix.

**Comment by staudenmeir** [comment]
Please close the issue.
