### ISSUE TITLE
ENUMs model update removing parts of the query due to a matching key / value combination

### ISSUE THREAD

**Issue by KyleWardle** [laravel/framework#24309]
- Laravel Version: 5.6 - PHP Version:
- Database Driver & Version: MySQL 5.7.19

### Steps To Reproduce:

So I am currently looping through my columns to update as so:

```
   $Whitelist = Player::findOrFail($whitelistUID);
    // return $Whitelist; ---> First Array
    foreach ($sqlArray as $colName => $rank) {
      $rank++;
      $Whitelist->$colName = $rank;
    }

    $Whitelist->save();
    return $Whitelist; // ----> Second Array
```

So the first array returns the following:

`{"uid":1,"PlayerName":"Luke","PlayerID":"76561198325233186","Staff_Rank":"5","SD_Rank":"8","SD_Patrol":"1","SD_SERT":"1","SD_K9":"0","SD_Aviation":"1","SD_CID":"1","SD_Medal":"1","EMS_Rank":"8","EMS_FD":"1","EMS_EMD":"1","EMS_Aviation":"1","Blacklisted":"0","Blacklisted_Reason":null,"time_inserted":"2017-09-24 00:45:04","lastseen":"2018-05-24 22:11:36"}`

The second array returns: 

`{"uid":1,"PlayerName":"Luke","PlayerID":"76561198325233186","Staff_Rank":"5","SD_Rank":9,"SD_Patrol":2,"SD_SERT":1,"SD_K9":"0","SD_Aviation":1,"SD_CID":2,"SD_Medal":"1","EMS_Rank":"8","EMS_FD":"1","EMS_EMD":"1","EMS_Aviation":"1","Blacklisted":"0","Blacklisted_Reason":null,"time_inserted":"2017-09-24 00:45:04","lastseen":"2018-05-24 22:11:36"}`

In the database SD_CID, SD_SERT, SD_Patrol and SD_Aviation are all ENUMs with a value of either 0 or 1 but with an array key of `1=>0` and `2=>1`.

In this example i am trying to set the **values** of SD_CID and SD_Patrol to 1 and SD_SWAT and SD_Aviation to 0. In the first array they are all set to a **value** of 1 in the database and so the findorfail returns all 1's. I need to update 2 of them to be 0 however the ENUM key for them is '1'. So essentially it is trying to update the value of 1 with 1 and laravel ignores them and so creates the following query: 

```
update `whitelist` set `SD_Rank` = '9', `SD_Patrol` = '2', `SD_CID` = '2' where `uid` = '1'
```

For ENUMs because when they are referencing a **KEY** when updating, it should not check whether or not they match the existing **values** as they may match when the physical value updating is not the same.

I'm sorry if I did not explain this very well as this is my first issue creation.

**Comment by sisve** [comment]
Could you provide as small testcase as possible? I imagine that you could reproduce this by creating the model, setting the value and saving. If so, could you do that, including the smallest model necessary to reproduce the problem?

    $model = new ExampleModel();
    $model->SD_CID = 1;
    $model->save()

    class ExampleModel extends Model {
        // Something here?
    }
