### ISSUE TITLE
yarn-error.log present when creating a new Laravel project

### ISSUE THREAD

**Issue by epreston** [laravel/framework#24301]
- Laravel Version: 5.6.23
- PHP Version: 7.2
- Database Driver & Version: Mariadb 10.2 something

### Description:

yarn-error.log present when creating a new Laravel project
File is included in http://cabinet.laravel.com/latest.zip

### Steps To Reproduce:

Method 1: 

- `laravel new project`
- The installer downloads `http://cabinet.laravel.com/latest.zip` project template
- The archive contains the empty file `yarn-error.log` and extracts it.

Method 2: 

- Download `http://cabinet.laravel.com/latest.zip` project template
- The archive contains the empty file `yarn-error.log` and extracts it.

This has no impact, but it did cause me to check through to make sure the test environment built correctly.  Same issue as #22318

**Comment by themsaid** [comment]
Can't replicate, closing this as it seems an issue with your environment.

**Comment by epreston** [comment]
You sure you looked into this?

It's still in the zip archive used for deployment served from http://cabinet.laravel.com/latest.zip

It was added on the 23rd of May.
