### ISSUE TITLE
Sending email with mailgun error because .mime parameter

### ISSUE THREAD

**Issue by billyadelphia** [laravel/framework#24312]
- Laravel Version: 5.6
- PHP Version: 7.2.5
- Database Driver & Version: 

### Description:

After Two days of struggling, I found that I can't send email with mailgun because of .mime parameter in MailgunTransport.php in Illuminate\Mail\Transport, setDomain function.
`$this->url = 'https://api.mailgun.net/v3/'.$domain.'/messages.mime';`
When I change code to 
`$this->url = 'https://api.mailgun.net/v3/'.$domain.'/messages';`
I can finally able to send email.
It is suppose to be like this ?

**Comment by sisve** [comment]
Those are two different apis. It sounds like a permission problem. Mandrill supports per-api permissions, perhaps Mailgun works that way too and you need permission to use the messages.mime api?
