### ISSUE TITLE
Laravel doesn't redirect back to authorization form after login

### ISSUE THREAD

**Issue by BrandOriented** [laravel/framework#24315]
- Laravel Version: 5.5
- PHP Version: 7.1, 7.2
- Database Driver & Version: MySQL, Postgresql

### Description:
Passport doesn't redirect back to authorization form after login.
Problem only on chrome(tested from 64-67).
If I enter through the link directly in the new tab, the problem does not occur, but if it is in the same card, laravel gets an invalid url()->previous()

Related: https://github.com/laravel/passport/issues/703

**Comment by dominium** [comment]
Closed without comment? Best practices on laravel team, great job. I've never used this shit framework.

**Comment by tillkruss** [comment]
In case you didn't know: Posting duplicates is bad etiquette and so is being a dick.

Use a different framework, we don't want your sarcasm and abusive language.
