### ISSUE TITLE
Mistake in release changelog

### ISSUE THREAD

**Issue by a-komarev** [laravel/framework#24310]
@tillkruss there is mistake in release changelog:

You wrote:
`Added TestReponse::assertUri() method (#24267)`

But method was renamed lately to `assertLocation`: (https://github.com/laravel/framework/commit/6ceca14d25783733cd3755996df86de1019ca91e)

**Comment by a-komarev** [comment]
I've made PR which fixes changelog file, but need to fix it in GitHub releases too.

**Comment by themsaid** [comment]
thanks :)
