### ISSUE TITLE
Reduce Rigidity of Email Validation Support

### ISSUE THREAD

**Issue by ebollens** [laravel/framework#24327]
- Laravel Version: All
- PHP Version: All
- Database Driver & Version: N/A

### Description:

Using `FILTER_VALIDATE_EMAIL` to validate email addresses does not support

1. internationalized email addresses
2. email addresses without at least one `.` in `<domain>`
3. email addresses destined for an IP as `<domain>`

These cases are valid under the RFC 5322 ABNF with the RFC 6532 addition.

The offending code: https://github.com/laravel/framework/blob/5.6/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L590-L593

### Steps To Reproduce:

Attempt to validate the following:

1. `θσερ@εχαμπλε.ψομ`
2. `root@localhost`
3. `test@123.123.123.123`

Case (1) is important to support internationalized domain names. Case (2) is important for things like locally-routed addresses used in intranets. Case (3) is important for some email destinations that do not leverage DNS.

Together, these make Laravel's email validation pretty much unusable for applications serving international audiences or involving intranets.

### Fix:

If there is interest, I would be happy to offer a PR with a solution. However, before that, I'd like to garner a bit of feedback as to what direction the community would like to see this issue go - ie. regex, PHP [intl](http://php.net/manual/en/book.intl.php) or an existing package.

**Comment by tillkruss** [comment]
Is there a reference that covers RFC 5322 with the RFC 6532 addition?

**Comment by fragkp** [comment]
Addiotnal idea: Support for checking MX & Host like Symfony does: https://symfony.com/doc/current/reference/constraints/Email.html

**Comment by tillkruss** [comment]
Please submit a PR if PHP's `FILTER_VALIDATE_EMAIL` isn't enough.

**Comment by ebollens** [comment]
@tillkruss please save me a bit of time from going in a direction that the community won't support first:

> before that, I'd like to garner a bit of feedback as to what direction the community would like to see this issue go - ie. regex, PHP intl or an existing package.

**Comment by tillkruss** [comment]
Extension is too much to ask for such a small change. Package would be alright, but only if it's really nessesary. If you can find a reliable regex that does it, that'd be ideal. 

I usually default to this: https://fightingforalostcause.net/content/misc/2006/compare-email-regex.php

However I think it might be hard to cover both RFCs with a single regex, unless you found something?

**Comment by ebollens** [comment]
@tillkruss the regex you linked from [Fighting for a Lost Cause](https://fightingforalostcause.net/content/misc/2006/compare-email-regex.php) appears, from its test cases, to satisfy the ABNF for RFC 5322. The reason I asked if we can use PHP INTL is that, if so, we can support international domain name format from RFC 6532 simply by passing the domain component through `idn_to_ascii`.

Here's my proposal then:

* Define `$validEmailRegex` as new regex (or should we make it a constant somewhere?)
* If `method_exists("idn_to_ascii")`:
  * Define `$domain` as domain segment of `$value`
  * Replace domain segment of `$value` with `idn_to_ascii($domain)`
* Return `return preg_match($validEmailRegex, $value) > 0`

**Comment by ebollens** [comment]
@tillkruss mind if we leverage `idn_to_ascii` in the event it is defined, which would presumably be cases where the application cares about internationalization support? This would mean that if we use a closer-to-5322 regex, we can just pass through `idn_to_ascii`.

**Comment by tillkruss** [comment]
Intl isn't installed by default, I doubt Taylor would merge it, however, feel free to submit a PR.
