### ISSUE TITLE
Different results for MAX() query

### ISSUE THREAD

**Issue by LordOfDav11** [laravel/framework#24337]
- Laravel Version: 5.6.15
- PHP Version: 7.2.5-1+ubuntu16.04.1+deb.sury.org+1
- Database Driver & Version: MySQL 5.7.22-0ubuntu0.16.04.1

### Description:
Hello,
im getting wrong results when calling MAX value from DB, but It's happening on my ubuntu server. 

### Steps To Reproduce:
Into console:
> php artisan tinker
> use App\SensorData
> SensorData::where('sensor_id', 4)->whereDate('created_at', '2018-05-26 00:00:00')->min('value');
> SensorData::where('sensor_id', 4)->whereDate('created_at', '2018-05-26 00:00:00')->max('value');
> SensorData::where('sensor_id', 4)->whereDate('created_at', '2018-05-26 00:00:00')->avg('value');

I'm getting returned values for:
MIN: 9, **MAX: 10**, AVG: 19.96993060909792

But on my windows localhost server I'm getting:
MIN: 9, **MAX: 22**, AVG: 19.96993060909792

Same code, same database data. 

- Localhost software: 
- PHP Version: 7.2.0
- Database Driver & Version: 10.1.29-MariaDB

**Comment by staudenmeir** [comment]
Can you reproduce the problem in phpMyAdmin or the command line?

**Comment by LordOfDav11** [comment]
Fixed
added ->get() before max
