### ISSUE TITLE
Happy Birthday, Taylor!

### ISSUE THREAD

**Issue by wilburpowery** [laravel/framework#24351]
Let's just take a minute to wish @taylorotwell Happy Birthday.

Without his work, none of this would be possible. 

Happy Birthday Taylor! 🎉

**Comment by andreshg112** [comment]
I really appreciate your work, @taylorotwell. Thank you!
I wish you a very happy birthday and a successful life.

**Comment by jycr753** [comment]
Hurra hurra @taylorotwell Feliz cumpleanos! Can't wait for laracon EU it will be awesome like always
