### ISSUE TITLE
"ErrorException: Trying to get property 'map' of non-object" when adding a relationship resource

### ISSUE THREAD

**Issue by andreshg112** [laravel/framework#24358]
- Laravel Version: 5.6.23
- PHP Version: 7.2.5
- Database Driver & Version: MySQL 5.7

### Description:
I have this error when trying to load a relationship in a resource:
![image](https://user-images.githubusercontent.com/15859884/40630296-18eea786-6297-11e8-8dc8-bf2e06acc3e4.png)

This is the resource. If I comment the line 24, everything works perfectly. However, it works via Insomnia keeping the line 24 uncommented.
![image](https://user-images.githubusercontent.com/15859884/40630308-2ebd4932-6297-11e8-87f9-1e1e5187eb22.png)

This is the test:
![image](https://user-images.githubusercontent.com/15859884/40630313-4384d79a-6297-11e8-93d0-e6cd1487a7e9.png)

This is the other resource:
![image](https://user-images.githubusercontent.com/15859884/40630315-50aceaca-6297-11e8-94fa-8e048172b5ea.png)

Results via Insomnia:
![image](https://user-images.githubusercontent.com/15859884/40630373-d193bede-6297-11e8-9b78-3df21d6fa11e.png)

### Steps To Reproduce:
Do what is in the images.

Thanks in advance!

**Comment by tillkruss** [comment]
Bug reports only, please.

**Comment by andreshg112** [comment]
@tillkruss , isn't this a bug? This should work. I'm doing what the documentation says.

**Comment by tillkruss** [comment]
No, it's custom code.  can you provide a **unit test** to narrow down the error?

**Comment by glaucomorais** [comment]
I don't know if @andreshg112 has resolved this issue, but it happened to me in Laravel 8.x when I try to create a resource collection with an empty loaded many to many relationship:

```php
$resource['files'] = FileResource::collection(
    $this->whenLoaded('files')
);
```

**Comment by glaucomorais** [comment]
Just a follow up: when a default value is set for the relationship, the problem doesn't occurs:

```php
$resource['files'] = FileResource::collection(
    $this->whenLoaded('files', null, [])
);
```

It feels a "hacky workaround", while the relationship loaded is an empty Eloquent collection.
