### ISSUE TITLE
localized-carbon duplicate number of days in arabic language 

### ISSUE THREAD

**Issue by milanssamad** [laravel/framework#24359]
- Laravel Version: 5.6
- PHP Version:
- Database Driver & Version:

### Description:
in my page i show posts and i use diffForHumans to display how mush time pass when post created and i translate it usin Localized Carbon in arabic language . it's working but in days he display number of days two times . for exemple instead of showing 5 days ago. he display 5 5 days ago

**Comment by staudenmeir** [comment]
Please move the issue to https://github.com/LaravelRUS/localized-carbon and provide more details.

**Comment by milanssamad** [comment]
done
