### ISSUE TITLE
CLI & file sessions issue

### ISSUE THREAD

**Issue by alexmnv** [laravel/framework#24364]
I had an issue with file sessions in a long-running CLI app. After a short period of time, the sessions would expire no matter what. 
As it turned out, `Illuminate\Session\FileSessionHandler` validates the session by checking the file's modification time:
https://github.com/laravel/framework/blob/1d9194bcaefcd674ae180281c5320f798e3a5405/src/Illuminate/Session/FileSessionHandler.php#L70
The problem stems from the fact that `filemtime` caches the result and returns cached data in further calls.

> Note: The results of this function are cached. See clearstatcache() for more details.
> http://php.net/manual/en/function.filemtime.php

So `FileSessionHandler::read($sessionId)` would always check old (initial) file mtime (unless `clearstatcache()` is called before loading a session).

**Comment by laurencei** [comment]
Why would your CLI have "sessions" in the first place though?

**Comment by alexmnv** [comment]
@laurencei it's a websocket-server app. It makes use of Laravel sessions to authorize connected users.

**Comment by sisve** [comment]
Have you written a websocket-server in PHP/Laravel? That sounds like a long-running process and something PHP wasn't meant for. See [PHP is meant to die](https://software-gunslinger.tumblr.com/post/47131406821/php-is-meant-to-die).

**Comment by alexmnv** [comment]
@sisve I used [orchidsoftware/web-socket](https://github.com/orchidsoftware/web-socket) Laravel library, which is a wrapper for [Ratchet](https://github.com/ratchetphp/Ratchet) library.
As for long-running processes in PHP, these tools (ratchet, reactphp) are mature and well tested. I've been using them for years and had no problems with memory leaking or performance.

**Comment by laurencei** [comment]
I think the solution here would be to use another session driver? Otherwise it would be a performance hit to change it?

**Comment by alexmnv** [comment]
Changing `FileSessionHandler` to check if app is running in console and calling `clearstatcache()` would solve the issue. But it is a very rare case, so adding this code will be useless in 99.99% of cases. I am not sure it's worth it. On the other hand, many people may encounter this problem in future and spend their time figuring it out.
I'll try to add this information to [orchidsoftware/web-socket](https://github.com/orchidsoftware/web-socket) so that users were aware of the issue.
