### ISSUE TITLE
trait DatabaseMigrations has rollback code not needed?

### ISSUE THREAD

**Issue by shez1983** [laravel/framework#24362]
- Laravel Version: 5.6.4
- PHP Version: 7.1
- Database Driver & Version: MySQL

### Description:

In the test trait DatabaseMigrations the line that i have commented out seems not needed?

I have placed a dump(1) so i know that line gets executed after every test but since we are doing a migrate:fresh, is it really needed?

I have like 20-30 tests and they take around 3 seconds, with this disabled (Uncommented) they are reduced to < 1 sec...  

Maybe i am not getting the reason? 

```<?php

namespace Illuminate\Foundation\Testing;

use Illuminate\Contracts\Console\Kernel;

trait DatabaseMigrations
{
    /**
     * Define hooks to migrate the database before and after each test.
     *
     * @return void
     */
    public function runDatabaseMigrations()
    {
        $this->artisan('migrate:fresh');

        $this->app[Kernel::class]->setArtisan(null);

        $this->beforeApplicationDestroyed(function () {
//            $this->artisan('migrate:rollback');

            RefreshDatabaseState::$migrated = false;
        });
    }
}
```

**Comment by staudenmeir** [comment]
I think you're right. After #20090 replaced `migrate` with `migrate:fresh` it's no longer necessary.

The only difference is the database's state after the last test (rolled back vs. not rolled back). But I don't see why that would be an issue.

**Comment by staudenmeir** [comment]
Do you want to submit a pull request?

**Comment by browner12** [comment]
yah, technically the behavior would be different, but if the performance gain is significant, would probably be a good idea.

It looks like there was even a comment on #20090 asking if we could remove the rollback now that we were using `fresh` that was never answered.

It seems like the only code that would be affected is in the [`RefreshDatabase`](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Foundation/Testing/RefreshDatabase.php#L52) trait.  I was trying to think if there could be an issue if you were mixing Browser and HTTP tests, but I couldn't come up with any.

**Comment by laurencei** [comment]
The easiest solution is to just switch your traits to `RefreshDatabase` - and none of the above is a problem. I tested on a 5.6 and confirmed.


> It seems like the only code that would be affected is in the RefreshDatabase trait

No - if you look further down it's tracking its own in the trait - so there shouldnt be any cross over.

**Comment by browner12** [comment]
The documentation suggests not using the `RefreshDatabase` when running browser tests.  I think we should either fix this code, or update the documentation if appropriate.

Also our Dusk test generator comes with the `DatabaseMigrations` trait already imported, which means people are probably leaning on that.

https://laravel.com/docs/5.6/dusk#migrations

**Comment by themsaid** [comment]
The idea here is to leave the DB clean after the application is destroyed, if we remove this the database will still have tables and records after the last test runs.

For suggestions and feature requests please use the https://github.com/laravel/internals repo.
