### ISSUE TITLE
NULL Named parameter in Route generator

### ISSUE THREAD

**Issue by DieZ** [laravel/framework#24360]
- Laravel Version: 5.6.22
- PHP Version: 7.1

### Description:
In `Illuminate\Routing\RouteUrlGenerator` in method `replaceNamedParameters()` parameter not replaced if is NULL.
Because of this, the order of changing the route parameters is violated. and instead of the specified parameter, the first is added to the account in the array.

### Steps To Reproduce:
maybe replace `if (isset($parameters[$m[1]]))` to `if (array_key_exists($m1, $parameters))`?

P.S.  sorry for my bad english and description. this my first issue.

**Comment by laurencei** [comment]
Sorry - I dont understand.

Can you provide an example of a route affected by this?

**Comment by DieZ** [comment]
For example, take this route:
``` php
Route::get('/{region?}/test', 'MainController@index')->name('test');
```
If I try to get the url using the route function in the code and pass the parameters in a different order, I get the wrong url.
``` php
route('test', ['page' => 1, 'region' => null]);
// http://web.loc/1/test?
route('test', ['page' => 1, 'region' => false]);
//http://web.loc/test?page=1
route('test', ['region' => false, 'page' => 1]);
//http://web.loc/test?page=1
route('test', ['region' => null, 'page' => 1]);
//http://web.loc/test?page=1
```
The first url is not correct because of the wrong order of the passed parameters and `'region' => null`
since isset on a variable with the value null return false
if change method `replaceNamedParameters()` to:
```    php
protected function replaceNamedParameters($path, &$parameters)
    {
        return preg_replace_callback('/\{(.*?)\??\}/', function ($m) use (&$parameters) {
            if (array_key_exists($m[1], $parameters)) {
                return Arr::pull($parameters, $m[1]);
            } elseif (array_key_exists($m[1], $this->defaultParameters)) {
                return $this->defaultParameters[$m[1]];
            }

            return $m[0];
        }, $path);
    }
```
then the first example will return the correct result:
``` php
route('test', ['page' => 1, 'region' => null]);
//http://web.loc/test?page=1
```

**Comment by laurencei** [comment]
Ok. Sounds like you've got a good grasp of the issue. You should submit a PR with the above, including some tests showing what you've got above and how this fixes it. Nice work.

**Comment by themsaid** [comment]
Quoting Taylor:

Optional parameters must always be the last parameters in a route.

**Comment by sharifzadesina** [comment]
@themsaid This is really annoying, why it should be last parameter? why you define rule by yourself?
Can you tell me how I am supposed to do something like this?
```
/users/logs
/users/me/logs
/users/<id>/logs
```
?
