### ISSUE TITLE
Not Getting Array Paths in Database of Laravel Project

### ISSUE THREAD

**Issue by Moix1** [laravel/framework#24365]
Hey I have Problem with multiple files array images while submitting images.

### Description:
I have form in which form I have three files input, First one is for single image selection , and two are array in multiple way, 

Probelm is: When i submit form i'm getting everything from form except last array file images in database but getting images in public->uploads folder after submission,

What can be possible issue for it ? how i can solve it ?

- Laravel Version: 5.6
- PHP Version: 7+
- Database Driver & Version: MySql 7+

Thanks
Moix

**Comment by passionInfinite** [comment]
@Moix1  Can you show your form code?

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I suggest closing your issue ticket here? Instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.
