### ISSUE TITLE
Incorrect command description for migrate:rollback

### ISSUE THREAD

**Issue by raphaelsaunier** [laravel/framework#24363]
- Laravel Version: 5.6.*
- PHP Version: 7.1
- Database Driver & Version: n/a

### Description:

The description of the `php artisan migrate:command` is currently misleading. It should be updated to reflect what's in the [documentation](https://laravel.com/docs/5.6/migrations#rolling-back-migrations):

> This command rolls back the last "batch" of migrations, which may include multiple migration files

Alternatively, you could leave the description unchanged and set the step value to 1 by default.

### Steps To Reproduce:

1. Run `php artisan migrate:rollback -h` 
2. See the following command description: _“Rollback the last database migration”_ (source: [Illuminate/Database/Console/Migrations/RollbackCommand.php](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Database/Console/Migrations/RollbackCommand.php#L25))
3. Run the command without the `--step` flag
4. See that multiple migrations are rolled back, and not just the last one

**Comment by themsaid** [comment]
feel free to open a PR
