### ISSUE TITLE
Model - aliased table - invalid insert/update statement

### ISSUE THREAD

**Issue by xorock** [laravel/framework#24376]
Hello. I'm using latest version of Laravel with MySQL driver. When trying to insert/update on aliased table invalid query is produced.

```php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Test extends Model
{
    protected $table = 'test AS t';
}

Test::create([...]);
```

```sql
insert into `test` as `t` (`x`) values (1)
```

LOG.error: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'as `t`

**Comment by staudenmeir** [comment]
I don't think Laravel supports an aliased `$table`.

**Comment by xorock** [comment]
Of course it is:

```php
echo Test::query()->select('id')->toSql();
// select `id` from `test` as `t` 
```

Problem is mysql driver does not allow aliased insert statement.

**Comment by staudenmeir** [comment]
I think that `SELECT` queries are accidentally working but `$table` wasn't meant to be used like that.

**Comment by xorock** [comment]
Why this issue was closed without any fix? Aliased tables as described are standard and normal behaviour (in opposite to what @staudenmeir is trying to say)

**Comment by staudenmeir** [comment]
I was only referring to aliases in `Model::$table`. Of course, you can use aliases with models:

    Test::from('test AS t')->get();

**Comment by xorock** [comment]
Simple solution for this is to remove AS part from the table when using Mysql adapter and update/insert queries.
