### ISSUE TITLE
Model::create() function missed the data

### ISSUE THREAD

**Issue by PureHow** [laravel/framework#24370]
![qq 20180530111608](https://user-images.githubusercontent.com/3593472/40697011-fbdb72ae-63fa-11e8-84c9-e39f6ecc76db.png)

- Laravel Version: 5.5.40
- PHP Version:7.2.5-0ubuntu0.18.04.1 (cli) (built: May  9 2018 17:21:02) ( NTS )
- Database Driver & Version:mysql  Ver 14.14 Distrib 5.7.22, for Linux (x86_64) using  EditLine wrapper

### Description:
I use the create function in Model, but parameters has missed in function newInstance().

### Steps To Reproduce:

$attributes is not empty, but $model empty.

**Comment by PureHow** [comment]
I am already set the protected member $fillable

**Comment by staudenmeir** [comment]
Please close the issue.
