### ISSUE TITLE
Collection mode method for decimal numbers throws error

### ISSUE THREAD

**Issue by sasureshkumar** [laravel/framework#24381]
- Laravel Version:5.6.23
- PHP Version:7.2.5
- Database Driver & Version:N/A

### Steps To Reproduce:
`$mode = collect([1.5, 2.75, 3.25, 2.75, 1.5, 2.75])->mode();`

**Comment by staudenmeir** [comment]
Use strings:

    $mode = collect(['1.5', '2.75', '3.25', '2.75', '1.5', '2.75'])->mode();
