### ISSUE TITLE
Broadcasting Auth Route not working with log driver

### ISSUE THREAD

**Issue by luizguilhermefr** [laravel/framework#24387]
- Laravel Version: 5.5.40
- PHP Version: PHP 7.1.17-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: May  5 2018 04:55:21)

### Description:

I'd like to test my application without have `redis-server` always running.

However, when using `log` broadcast driver, the `/broadcasting/auth` route always returns true/http 200.

### Steps To Reproduce:

In `.env` define `BROADCAST_DRIVER` as `redis` and configure a channel as in [docs](https://laravel.com/docs/5.5/broadcasting).

In `phpunit.xml`, define the following environment modifier:

```xml
<env name="BROADCAST_DRIVER" value="log"/>
```

A test like

```php
public function testUnauthorizedCannotSubscribeToChannel()
{
        $response = $this->postJson('/broadcasting/auth',
            ['channel_name' => 'private-my.channel',],
            ['Authorization' => 'Bearer '.$this->unauthorizedUserJWT,]);
        $response->assertStatus(403);
}
```
will fail as it will return `200` status instead. :no_entry_sign: 

Now **remove the environment modifier** and run `redis-cli`. See that the test now **works**. :heavy_check_mark:

**Comment by themsaid** [comment]
Yeah the log driver doesn't contain any auth logic, this is the expected behaviour, to have such test you'll need to use an actual broadcasting driver.

**Comment by luizguilhermefr** [comment]
@themsaid Could you elaborate more on why this is the expected behavior?
