### ISSUE TITLE
New idea for migrations and seeders.

### ISSUE THREAD

**Issue by Fox4Iit** [laravel/framework#24391]
If we can make migrations available for editing at any time, even on a production server.
When a migration is being performed, we would check for the column attributes, or the column existence, if it does exists, then move to next, if not, then create it, if it DOESN'T exists, or have a different attribute, it will change or the column will be deleted from the database.
As for the seeder, we would check for the value of the column, if it does exists, then we can resume next.
I don't know how to make this myself, any help or guide to read on how to accomplish that?

**Comment by staudenmeir** [comment]
Please use https://github.com/laravel/ideas/issues for suggestions.
