### ISSUE TITLE
Allow overloading of environment variables

### ISSUE THREAD

**Issue by colynb** [laravel/framework#24403]
### Description:

In some development environments, some or all of the variables in the .env file are already loaded at the server level and take precedence as per the phpdotenv docs. However, from their docs it allows for overriding this feature:

```
$dotenv = new Dotenv\Dotenv(__DIR__);
$dotenv->overload(); // instead of  $dotenv->load();
```

If there was some way to configure that in a Laravel app this would not be a problem.

In the `LoadEnvironmentVariables::bootstrap` method on line 28, I was thinking this can be solved like this:

```
if (getenv('LARAVEL_ENV_OVERLOAD')) {
    (new Dotenv($app->environmentPath(), $app->environmentFile()))->overload();
} else {
     (new Dotenv($app->environmentPath(), $app->environmentFile()))->load();
}
```

Then the dev will just need to export a variable:

```
> export LARAVEL_ENV_OVERLOAD=true
```

**Comment by deleugpn** [comment]
Why would the development environment server already have undesired environment variables? If you own the server, wouldn't it just be easier to change the environment values?

**Comment by colynb** [comment]
@deleugpn There are many situations that I've encountered where a docker environment used in development preloads any found .env files during bootup. While this is a nice feature, it means that when I'm developing a Laravel app and messing with env vars, I have to always restart my docker container for the changes to take effect. 

Because phpdotenv already has a feature that allows for overriding the default behavior, it would be really helpful if Laravel had a hook into that feature.

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo.

**Comment by ryancwalsh** [comment]
See https://github.com/laravel/framework/issues/6096#issuecomment-544257752 for an answer.
