### ISSUE TITLE
whereHas with nested relation is broken

### ISSUE THREAD

**Issue by afraca** [laravel/framework#24407]
- Laravel Version: 5.5.x
- PHP Version: 7.0.30
- Database Driver & Version: mysql 

### Description:
When working with relations, there is the `whereHas` method, constraining things on a relation, described here:
https://laravel.com/docs/5.5/eloquent-relationships#querying-relationship-existence
There should be support for nested relations, but this will fail with an 'undefined function on Builder'. I looked into this.

### Steps To Reproduce:
Model A belongsTo B
Model B belongsToMany C

When doing
`
A::with('b.c')->whereHas('b.c', function($q){})->get();
`
we see failure of the 'undefined function c'.

------

I looked into this and saw in the `QueriesRelationship` trait multiple calls to `getRelationWithoutConstraints`. There we have `$this->getModel()` and in the reproduction case we see *that* returning A and A, not A and B. I think that's part of the problem.
Sorry I can't provide a reproducing repo here on Github, no time today.

**Comment by afraca** [comment]
ps: I think why no tests have caught this is because the tests only test with a self-referencing relation! See: 
https://github.com/laravel/framework/blob/56a58e0fa3d845bb992d7c64ac9bb6d0c24b745a/tests/Database/DatabaseEloquentIntegrationTest.php#L667

**Comment by staudenmeir** [comment]
It works for me. Can you post the models

**Comment by afraca** [comment]
Set up a clean laravel project and got a reproducable case, will put code on github in a moment. 
I'm using polymorphic relations though, perhaps that could be related, not sure at the moment.

**Comment by afraca** [comment]
Here it is: 
https://github.com/afraca/laravel-issue24407

The Spatie Medialibrary lets you tie files to anything. If you however want to use one file on multiple items in your application, you have to use some middle model, the FileAssociator in my reproducing repo. 
This FileAssociator can then be tied to multiple items (polymorphic many to many).

Now, if you want to select files which only have a page with status '1', you use the code from `web.php` , the home route, this code for retrieval:
`
   dump(File::whereHas('model.pages', function (Builder $builder) {
        $builder->where('status', '1');
    })->all());
`

That fails, with: Call to undefined method Illuminate\Database\Query\Builder::pages()

**Comment by staudenmeir** [comment]
`whereHas()` doesn't work with polymorphic relationships: #5429, #18523

**Comment by afraca** [comment]
While certainly interesting, it seems some parts DO work, and this counts as a separate, possibly fixable, issue.
We saw it working when we did things with the FileAssociator (see repo) directly. See this:
https://github.com/afraca/laravel-issue24407/blob/57302807c862843a36e86bb4b4ca49ec48ae38a3/routes/web.php#L35-L37

Produces (I think the expected) query:
```
"select * from `file_associators` where exists (select * from `pages` inner join `fileables` on `pages`.`id` = `fileables`.`fileable_id` where `file_associators`.`id` = `fileables`.`file_associator_id` and `fileables`.`fileable_type` = ? and `status` = ?)
```

**Comment by staudenmeir** [comment]
To be more specific: `MorphTo` relationships don't work with `whereHas()`.

**Comment by afraca** [comment]
@tillkruss  , can you clarify? This is not a duplicate. @staudenmeir  was talking about MorphTo, but we're going the other way if I recall correctly. It *almost* works!

**Comment by staudenmeir** [comment]
You wrote that `File::whereHas('model.pages'` isn't working. `model` is a `MorphTo` relationship.

**Comment by afraca** [comment]
You're right, sorry, I got "obsessed" by the the fact the builder was doing multiple things on the File model, and I saw the FileAssociator example working. I'll close this as a duplicate of the issues you mentioned.
