### ISSUE TITLE
Reset session on multiple servers memcached

### ISSUE THREAD

**Issue by shadrvlad** [laravel/framework#24440]
- Laravel Version: 5.5.40
- PHP Version: 7.1.17, 7.2.6
- Database Driver & Version: MariaDB 10.2.15

### Description:
When using the session driver and memcached using multiple servers configured in a redundant preservation through OPT_NUMBER_OF_REPLICAS reset session when reconnecting one of the servers.

### Steps To Reproduce:
1. Add two or more memcached servers
2. Disable one of them, the session will not be reset - taken from other servers.
3. Turn the server back on-resets the session. When excess saving sessions on the bare php and use session_path this does not happen.

**Comment by sisve** [comment]
Memcached doesn't have any replication. When you bring the second server up it will be empty, and attempts to fetch any data from it will fail. Use memcached for actual cache, where you still have a store of the original data. Don't use memcached as the only place to store data.

Redis has replication and should work for this use-case.

**Comment by shadrvlad** [comment]
session_handler = memcached has the ability to save redundant sessions on all servers, and when you connect a new server - duplicate data on it. In this case, the session will not be reset until there is at least one active server and it does not matter whether they are restarted and in what order.

**Comment by sisve** [comment]
Could you clarify the `session_handler = memcached` part? Is that an .env entry? The default .env uses `session_driver`, not `session_handler`.

**Comment by shadrvlad** [comment]
php.ini session_handler

**Comment by sisve** [comment]
Laravel does not use the session_handler directive in php as far as I know. The session system wraps the cache system (for the cache-based drivers like memcached and apc) so the session system is currently in the hands of what the cache system does.

Wouldn't it be easier to switch to a cache system that has replication support built-in?
