### ISSUE TITLE
orWhereHas on relation with whereHas

### ISSUE THREAD

**Issue by neomobil** [laravel/framework#24442]
- Laravel Version: 5.6.7
- PHP Version: 7.2.2
- Database Driver & Version:

### Description:
I'm experiencing a problem with the orWhereHas method using with a relation.
It looks like an old bug:
[https://github.com/laravel/framework/issues/7207](https://github.com/laravel/framework/issues/7207)

### Steps To Reproduce:
time() is a hasMany() relationship.
`$times = $user->time()
            ->whereHas('sample_relation', function ($query) {
                $query->whereDate('created_at', date('Y-m-d', time()));
            })
            ->orWhereHas('sample_relation_2', function($query) {
                $query->whereDate('created_at', date('Y-m-d', time()));
            })
            ->get();`

**Comment by staudenmeir** [comment]
Please indent your code with four spaces to improve the formatting.

**Comment by staudenmeir** [comment]
What exactly isn't working? What's the expected vs. actual result?

**Comment by staudenmeir** [comment]
The problem is that `AND` has precedence over `OR`. You have to nest the constraints:

    $times = $user->time()
        ->where(function ($query) {
            $query->whereHas('sample_relation', function ($query) {
                $query->whereDate('created_at', date('Y-m-d', time()));
            })
            ->orWhereHas('sample_relation_2', function($query) {
                $query->whereDate('created_at', date('Y-m-d', time()));
            });
        })
        ->get();

**Comment by rSammy** [comment]
Describe your issue properly. 

What is expected and what your query actually do.
Is sample_relation_2 different from sample_relation ?

**Comment by neomobil** [comment]
@staudenmeir Thank you for the answer.

**Comment by neomobil** [comment]
@rSammy Yes, sample_relation_2 is different. The problem is solved.
