### ISSUE TITLE
trans helper don't translate custom attributes names

### ISSUE THREAD

**Issue by set0x** [laravel/framework#24457]
- Laravel Version: Laravel Framework 5.6.23
- PHP Version: PHP 7.2.4-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Apr  5 2018 08:55:11) ( NTS )
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.7.22, for Linux (x86_64) using  EditLine wrapper

### Description:

`resources/lang/es/validation.php`
```php
/*
|--------------------------------------------------------------------------
| Validation Language Lines
|--------------------------------------------------------------------------
|
| The following language lines contain the default error messages used by
| the validator class. Some of these rules have multiple versions such
| as the size rules. Feel free to tweak each of these messages.
|
*/
'unique' => ':attribute ya ha sido registrado.',
```

`resources/lang/es/validation.php`
```php
/*
|--------------------------------------------------------------------------
| Custom Validation Attributes
|--------------------------------------------------------------------------
|
| The following language lines are used to swap attribute place-holders
| with something more reader friendly such as E-Mail Address instead
| of "email". This simply helps us make messages a little cleaner.
|
*/
'attributes' => [
    'name' => 'nombre',
]
```

The `trans` helper only translate the validation line but not translate the custom atribute name

----------------------------------------
### Steps To Reproduce:

```php
trans('validation.unique', ['attribute' => 'name']);
```

**Result:**
```
name ya ha sido registrado.
```

**Comment by GeraldPK** [comment]
Use `trans('validation.unique,['attribute' => trans('validation.attributes.name')])`

**Comment by joserick** [comment]
Hello, 

Is there currently a more elegant way to do this?
``
```php
trans('motorcycles.success', ['attributes' => trans('motorcycles.attributes.updated'));
```
Something like:
```php
trans('motorcycles.success', 'updated');
```
That when the second parameter is a string, it automatically looks for the translation in "motorcycles.attributes.updated"
I don't know if this idea has any conflict with any code.
