### ISSUE TITLE
display_errors should not be determined by environment

### ISSUE THREAD

**Issue by sazo** [laravel/framework#24455]
- Laravel Version: 5.5.40
- PHP Version: 7.0
- Database Driver & Version: MySQL 5.6

### Description:
framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php
```
public function bootstrap(Application $app) {
      # Some code before
      if (! $app->environment('testing')) {
          ini_set('display_errors', 'Off');
      }
}
```
display_errors should not be determined based on a fixed environment chosen by laravel. This should be determined by if it is in debug mode or its own setting/environment variable.

Some examples:
1. If i have multiple environments like local, development, staging, production. I want to show errors in local and development. But not in staging and production.
2. If i create a new command from a fresh installed laravel which fx exhausted memory 

```
bash-4.4# php -d memory_limit=120M artisan xdebug:some
[No output]
bash-4.4# APP_ENV=testing php -d memory_limit=120M artisan xdebug:some

Fatal error: Allowed memory size of 125829120 bytes exhausted (tried to allocate 4096 bytes) in /app/blog/routes/console.php on line 22

Fatal error: Allowed memory size of 125829120 bytes exhausted (tried to allocate 32768 bytes) in /app/blog/vendor/symfony/debug/Exception/FatalErrorException.php on line 1
bash-4.4# 
```   
I think this is a critical bug because you dont know if it fails or success. It just exits.

**Comment by laurencei** [comment]
You just need to set `APP_DEBUG=true/false` in your `.env` file

**Comment by sazo** [comment]
It is true by default in a new installed laravel?

But i think i have found the root course by xdebugging. If you run the artisan it tries to get the user? that does not make any sense in console? It tries to bootstrap SessionGuard etc and it fails inside the errorHandling. 

Illuminate/Foundation/Exceptions/Handler.php
```
protected function context()
    {
        try {
            return array_filter([
                'userId' => Auth::id(),
                'email' => Auth::user() ? Auth::user()->email : null,
            ]);
        } catch (Throwable $e) {
            return [];
        }
    }
```

**Comment by sazo** [comment]
@tillkruss may i ask why you close it? you have a bug that it does not print "exhausted memory" unless it is in testing environment. So in production you will not get any errors in the logs that your process have died.

**Comment by tillkruss** [comment]
It's not a bug, it's a feature 😉

**Comment by sazo** [comment]
@tillkruss may i ask why laravel thinks "exhausted memory" errors is NOT important to log in production?

**Comment by tillkruss** [comment]
Because `display_errors` doesn't log anything. If you need to catch error in production either log them or use an error tracking tool such as Bugsnag or Rollbar.
