### ISSUE TITLE
Error while using Cache 

### ISSUE THREAD

**Issue by Trust-Coder** [laravel/framework#24450]
- Laravel Version: 5.6.24
- PHP Version: 7.1.18
- Database Driver & Version: MySQL
- Cache Driver: Redis (also tried on default, i.e. file)

### Description:
**While using the Cache class, I'm getting the following error. **

{
    "message": "Class 'League\\Flysystem\\Cached\\Storage\\AbstractCache' not found",
    "exception": "Symfony\\Component\\Debug\\Exception\\FatalErrorException",
    "file": "D:\\Documents\\Websites\\ritechase-web\\vendor\\laravel\\framework\\src\\Illuminate\\Filesystem\\Cache.php",
    "line": 8,
    "trace": []
}

**Comment by sisve** [comment]
It sounds like you're using wrong Cache class. If you actually want to use Flysystem's cache, install the `league/flysystem-cached-adapter` package as suggested in composer.json.

https://github.com/laravel/framework/blob/b15997fa50c2e569ad081d4b3c2a75f8adbfd35e/composer.json#L120

**Comment by hamidrezaghanbari** [comment]
i think you just need to use fecade library cache not filesystem it work for me

**Comment by n3omaster** [comment]
Try this:

`use Illuminate\Support\Facades\Cache;`

**Comment by flavio-back-end** [comment]
check if you have  this use ( use Illuminate\Filesystem\Cache) change it  (use Illuminate\Support\Facades\Cache)

cause use wrong cache

)
