### ISSUE TITLE
Bootstrap/LoadConfiguration.php exception on 5.1

### ISSUE THREAD

**Issue by alpha0010** [laravel/framework#24469]
[Bootstrap/LoadConfiguration.php](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php#L72) throws `InvalidArgumentException`: Given expression is not a regex.

Although, I am not exactly certain if that is an issue.  It appears this exception has always been thrown (and later caught), without (noticeable) issue to loading configs.

**Comment by devcircus** [comment]
Strange that it would be a problem. The 'name' method's docblock in [Symfony\Component\Finder\Finder](https://github.com/symfony/finder/blob/master/Finder.php#L155), actually gives the exact line as it is used in Laravel, as an example of how to use the method.
```php
/**
     * Adds rules that files must match.
     *
     * You can use patterns (delimited with / sign), globs or simple strings.
     *
     * $finder->name('*.php')
     * $finder->name('/\.php$/') // same as above
     * $finder->name('test.php')
```
That being said, you can read more about this exception on the Symfony\Symfony [issues page](https://github.com/symfony/symfony/issues/7646).

**Comment by alpha0010** [comment]
Ah, thanks.  It appears my debug settings were just too high, and this exception is part of [normal operation](https://github.com/symfony/finder/blob/2.7/Expression/Expression.php#L44).
