### ISSUE TITLE
Carbon Exception 5.6.23 and 5.6.24

### ISSUE THREAD

**Issue by cquinoneso** [laravel/framework#24485]
composer require nesbot/carbon

Using version ^1.29 for nesbot/carbon
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel/framework v5.6.24 requires nesbot/carbon 1.25.* -> satisfiable by nesbot/carbon[1.25.0] but these conflict with your requirements or minimum-stability.
    - laravel/framework v5.6.24 requires nesbot/carbon 1.25.* -> satisfiable by nesbot/carbon[1.25.0] but these conflict with your requirements or minimum-stability.
    - laravel/framework v5.6.24 requires nesbot/carbon 1.25.* -> satisfiable by nesbot/carbon[1.25.0] but these conflict with your requirements or minimum-stability.
    - Installation request for laravel/framework (locked at v5.6.24, required as 5.6.*) -> satisfiable by laravel/framework[v5.6.24].

Installation failed, reverting ./composer.json to its original content.

**Comment by 36864** [comment]
This repo is reserved for bug reports.

Laravel depends on version 1.25 of carbon, and you're trying to load version 1.29, which is not supported.

**Comment by cquinoneso** [comment]
Sorry and Thanks for the information

**Comment by staudenmeir** [comment]
Please close the issue.

**Comment by kylekatarnls** [comment]
Hi @cquinoneso, even if Laravel locked the Carbon version to 1.25.* (before Carbon introduces its own macro layer), it's still compatible, so you can force the install with `"nesbot/carbon": "1.29.0 as 1.25.0"`

Laravel 5.7 should no longer have this version lock.
