### ISSUE TITLE
Cannot access $parameters in custom Rule class

### ISSUE THREAD

**Issue by robjbrain** [laravel/framework#24483]
- Laravel Version: 5.6.22
- PHP Version: 7.2

### Description:
The Rule class generated by `php artisan make:rule` does not allow access to $parameters which makes it very limited.

### Steps To Reproduce:
Create a custom validation rule such as this:

```php
        // Usage Example: ['required|decimal:4,2']
        Validator::extend('decimal', function ($attribute, $value, $parameters, $validator) {
            $number = (int)$parameters[0];
            $decimals = (int)$parameters[1];

            // E.g: /^[0-9]{1,3}.[0-9]{1,2}$/
            // If the decimal format is 3,2
            return preg_match("/^[0-9]{1,$number}.[0-9]{1,$decimals}$/", $value);
        });
```

If you want to refactor this into its own class you can't because the $parameters are not sent to the passes() method on the custom rule.

```php
     /**
     * Determine if the validation rule passes.
     *
     * @param  string  $attribute
     * @param  mixed  $value
     * @return bool
     */
    public function passes($attribute, $value)
    {
        //
    }

```

### Simple Solution:
It appears trivial to add this in:

4th Parameter here: https://github.com/laravel/framework/blob/4b736f75f533e53f677dff52efd80fa5088a39b6/src/Illuminate/Validation/Validator.php#L359

```php
        if ($rule instanceof RuleContract) {
            return $validatable
//                  ? $this->validateUsingCustomRule($attribute, $value, $rule)
                    ? $this->validateUsingCustomRule($attribute, $value, $rule, $parameters)
                    : null;
        }
```

And here:
https://github.com/laravel/framework/blob/4b736f75f533e53f677dff52efd80fa5088a39b6/src/Illuminate/Validation/Validator.php#L537

```php
//      protected function validateUsingCustomRule($attribute, $value, $rule)
        protected function validateUsingCustomRule($attribute, $value, $rule, $parameters)
    {
//      if (! $rule->passes($attribute, $value)) {
        if (! $rule->passes($attribute, $value, $parameters)) {
            $this->failedRules[$attribute][get_class($rule)] = [];

            $this->messages->add($attribute, $this->makeReplacements(
                $rule->message(), $attribute, get_class($rule), []
            ));
        }
    }
```

You could also make it the same as the extension based approach by sending the validator as the 4th parameter.

```php
//      if (! $rule->passes($attribute, $value)) {
        if (! $rule->passes($attribute, $value, $parameters, $this)) {
```

Happy to try and submit a PR is this is agreed?

**Comment by devcircus** [comment]
It's been brought up a few times (similar to #23331), but you can pass anything you need in the Rule, through the constructor.
