### ISSUE TITLE
Need Disable cache for specific  view

### ISSUE THREAD

**Issue by engnaguib** [laravel/framework#24494]
Hi All
I need to disable cache for specific view ,i tried many ways i can't solve it till now

**Comment by decadence** [comment]
Welcome to Laravel! We are glad to have you as part of the community.

Unfortunately GitHub is not an appropriate platform for general application issues. This is only for issues/bugs with the framework code itself.

Please close your issue, and instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

Laravel Slack (https://larachat.co/)
Laravel.io Forum (https://laravel.io/forum)
Laracasts Forum (https://laracasts.com/discuss)
StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks!

**Comment by engnaguib** [comment]
Hey 
Okay,but i think we need this option i tried may times to find solution
