### ISSUE TITLE
Logical error in the increment method in the file cache

### ISSUE THREAD

**Issue by sinchie** [laravel/framework#24496]
- Laravel Version: 5.6
- PHP Version: 7.2.5

### Description:

https://github.com/laravel/framework/blob/5.6/src/Illuminate/Cache/FileStore.php#L89

The get and put methods should be in a lock cycle and are now separated and may result in incorrect results.

**Comment by sisve** [comment]
Could you expand on the logical error and what you describe as a "lock cycle"?

**Comment by sinchie** [comment]
The current practice will allow multiple processes to read the same number to increase and save when concurrent.

The normal logic should be as follows,This is a lock cycle:

`<?php

flock($fd, LOCK_EX);

$num = stream_get_contents($fd);
$num += 1;
fwrite($fd, $num, len($num));

flock($fd, LOCK_UN);
fclose($fd);
`

**Comment by tillkruss** [comment]
Can you submit a PR?

**Comment by sinchie** [comment]
@tillkruss Ok, I can submit tomorrow
