### ISSUE TITLE
laravel 5.4 running under php 5.6 - undefined function Illuminate\Support\random_bytes()

### ISSUE THREAD

**Issue by jjrdev** [laravel/framework#24493]
- Laravel Version: 5.4
- PHP Version: 5.6
- Database Driver & Version:

### Description:
a completely clean install of laravel 5.4 running under php 5.6 is currently broken

### Steps To Reproduce:
composer create-project --prefer-dist laravel/laravel test "5.4.*" - visit site with php5.6 - Call to undefined function Illuminate\Support\random_bytes() - also occurs on an existing 5.4 site with php5.6 when composer update is run

**Comment by staudenmeir** [comment]
I can't reproduce that. What's the stacktrace?

**Comment by devcircus** [comment]
It's a project level composer dependency issue. It's  been a while but it's been discussed here a few times.

**Comment by jjrdev** [comment]
is there a workaround?

**Comment by tillkruss** [comment]
Use 5.6.

**Comment by jjrdevspace01** [comment]
thats not a resolution as i am stuck with php 5.6 and therefore can only use laravel 5.4 - suggestion seems to suggest related to composer version, any more info on that?
