### ISSUE TITLE
Cache\FileStore::getPayload causes error when using timestamp before 2001

### ISSUE THREAD

**Issue by nicolai-agersbaek** [laravel/framework#24516]
- Laravel Version: 5.5.40
- PHP Version: 7.0.27
- Database Driver & Version: MySQL 5.6

### Description:
Using `Illuminate\Cache\FileStore::getPayload` with a current timestamp -- as given by `Illuminate\Support\InteractsWithTime::currentTime` -- less than or equal to 999,999,999 (on or ealier than September 9, 2001 01:46:39 GMT) causes an `[ErrorException] unserialize(): Error at offset 0 of X bytes`. This is because of the length of the `substr` call used to isolate the expiration timestamp of the serialized (stored) string is hardcoded at 10.

### Steps To Reproduce:
The following code snippets demonstrates the issue:
```php
// Any timestamp whose length is 9 or less will trigger an ErrorException
Carbon::setTestNow(Carbon::create(2000));

Cache::remember('testCacheKey', 1440, function () {
    return new DummyClass();
});
```
With the `DummyClass` being a simple serializable class containing some information:
```php
class DummyClass
{
    public $value = 'foo';
}
```

### Solution:
Instead of using `substr`, the timestamp could be resolved using a simple regular expression: `'/^(?P<expire>\d+)(?P<serialization>.*)/'`, or something similar. The exact details of, this taking performance into account, I'm not sure of.

**Comment by laurencei** [comment]
I'm closing, as it seems like a strange edge case.

In what situation would a timestamp "currentTime" be before 2001 anyway?

**Comment by nicolai-agersbaek** [comment]
We encountered this issue in automated testing. While it certainly is not a high-priority issue, it might be something to consider, as it was quite difficult to track down the cause of the bug; though it should only occur during testing.

**Comment by flashx4u** [comment]
I have the same porblem when debugging with vscode, often it breaks, because the function throws an error. I think it's a desing failure. The working with Exceptions to implement logic is not a good design, with every exception Processor stops and registers a and stack is copied for the ErrorInfo.
A simple if could be the fix for it. 
Because the function returns an empty  Payload as stated in the comment, the fix would be easy with a simple if file exists:

`    /**
     * Retrieve an item and expiry time from the cache by key.
     *
     * @param  string  $key
     * @return array
     */
    protected function getPayload($key)
    {
        $path = $this->path($key);

        // If the file doesn't exist, we obviously cannot return the cache so we will
        // just return null. Otherwise, we'll get the contents of the file and get
        // the expiration UNIX timestamps from the start of the file's contents.
        try {
            if ($this->files->exists($path)) {
                $expire = substr(
                    $contents = $this->files->get($path, true), 0, 10
                );
            } else {
                return $this->emptyPayload();
            }
        } catch (Exception $e) {
            return $this->emptyPayload();
        }`

Cheers, Helmut
