### ISSUE TITLE
Unique Validation Issue

### ISSUE THREAD

**Issue by xzhenghao** [laravel/framework#24517]
- Laravel Version: 5.6.23
- PHP Version: 7.1.8
- Database Driver & Version: 

### Description:
I am using SoftDeletes on one of my table
- created a unique validation, excluded it to search deleted_at is NULL

count(*) from query return 0, but duplicate entry violation still appears.

Can anyone help please? Thanks!

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/4718721/41157635-0bda31f8-6b59-11e8-9308-677c41869c0a.png)

![image](https://user-images.githubusercontent.com/4718721/41157652-197921b6-6b59-11e8-9a3c-42c280a6b056.png)

![image](https://user-images.githubusercontent.com/4718721/41157683-303cb34a-6b59-11e8-8dc4-774e01a04349.png)

**Comment by decadence** [comment]
Welcome to Laravel! We are glad to have you as part of the community.

Unfortunately GitHub is not an appropriate platform for general application issues. This is only for issues/bugs with the framework code itself.

Please close your issue, and instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

Laravel Slack (https://larachat.co/)
Laravel.io Forum (https://laravel.io/forum)
Laracasts Forum (https://laracasts.com/discuss)
StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks!

**Comment by xzhenghao** [comment]
All right. Thanks.
