### ISSUE TITLE
Advanced SELECT with query builder

### ISSUE THREAD

**Issue by rudiedirkx** [laravel/framework#24539]
How would I make this SELECT with the query builder:

```
SELECT *, (sector1 IN (...)) AS m1, (sector2 IN (...)) AS m2
FROM jobs
WHERE (sector1 IN (...) OR sector2 IN (...))
```

All the `(...)` are the same list of 1-N values.

The WHERE is easy, with `whereIn()`, but how do I expand a list for `IN()` in the SELECT?

`selectSub` makes too much:

```
$query->selectSub(function(Builder $query) {
	$query->whereIn('sector1', $list);
}, 'm1');
```

makes an entire sub query, not just the `IN()` part.

`selectRaw` makes the right kind of SQL, but doesn't expand the list:

```
$query->selectRaw('(sector1 IN (?)) as m1', [$list]);
```

wants to put an array in a single `?` and that doesn't work with this builder (although it doesn't break, which is weird).

The only way I see is to expand the list manually and use scalar bindings:

```
$query->selectRaw('(sector1 IN (' . implode(',', array_fill(0, count($list), '?')) . ')) as m1', [$list]);
```

but that feels wrong in a query builder.

And of course there are many more advanced SQL features that the Builder doesn't have a method for. Nor should it have. I should be allowed to type any part, and the builder should parameterize wherever I want. Maybe a new class that works anywhere in the query: `Expression($sql, $bindings)`?

**Comment by rudiedirkx** [comment]
Another advanced IN that's not possible with the builder:

```
(x IN (...)) = (y IN (...))
```

Not even possible in the WHERE, because raw IN is impossible everywhere.

It'd be nice to write small pieces of any SQL I want, with bindings, and use the builder for all the rest.

**Comment by tillkruss** [comment]
Not a bug.

**Comment by rudiedirkx** [comment]
Yes, obviously it's not a bug. That's also not what I said... Wouldn't it be very useful though? Laravel is more than not-a-bug, isn't it?

**Comment by 36864** [comment]
This repo is for bug reports. If you have a suggestion, please use laravel/ideas.

**Comment by rudiedirkx** [comment]
> This repo is for bug reports.

Does it say that somewhere?

**Comment by staudenmeir** [comment]
The [issue template](https://github.com/laravel/framework/issues/new) says it.

**Comment by rudiedirkx** [comment]
Alright, that's pretty stupid of me. Thanks.
