### ISSUE TITLE
Call build on mailable when mocking and default to when sending emails

### ISSUE THREAD

**Issue by caiquecastro** [laravel/framework#24538]
- Laravel Version: 5.6.24
- PHP Version: 7.2

### Description:
When I am testing mailables with Mail::fake() and Mail::assertSent(), and I use the second parameter for Mail::assertSent, the argument passed to the closure is missing the attributes, I would have to build it ($mail->build()). And if no recipient for the mail is not declared and would fallback to the default mail.to config, it's not on the returned object.

### Steps To Reproduce:
```php
Mail::fake();

Mail::assertSent(ContactForm::class, function ($mail) {
            return $mail->hasTo('example@example.com'); // this email is used from mail.to config.
});
```

I tried to add this custom config for email on laravel/laravel, but it was rejected:

https://github.com/laravel/laravel/pull/4672

**Comment by themsaid** [comment]
I don't seem to understand your issue, please share more details.

**Comment by caiquecastro** [comment]
Sorry If I was not clear.

In order for the test below to work, I have to build the mailable first.

```php
// does not work
Mail::assertSent(ContactForm::class, function ($mail) {
    return $mail->hasTo('example@example.com');
});

// it works
Mail::assertSent(ContactForm::class, function ($mail) {
    $builtMail = $mail->build();
    return $builtMail->hasTo('example@example.com');
});
```

If this approach is OK, I think it's worthy to add a note on docs. What do you think?

**Comment by deleugpn** [comment]
I think somebody already tried a PR on this and was rejected because it's fair to just call the build method on the mailable.

**Comment by caiquecastro** [comment]
I think it's ok to call build, but I think it would be nice to have it documented. I want to know if it's the best practice.

**Comment by laurencei** [comment]
Please feel free to send a PR To the Laravel/Docs with the documentation idea :)
