### ISSUE TITLE
Laravel strips trailings slashes from URLs while processing route parameters

### ISSUE THREAD

**Issue by KrzysztofMadejski** [laravel/framework#24544]
- Laravel Version: 5.5, 5.6
- PHP Version: 7.1

### Description:
Laravel is stripping trailing slash from URLs while processing routes. According to HTTP standard `/path/` and `/path` are two different distinct paths.

### Steps To Reproduce:
1. Create route `Route::get('/{value}', 'Controller@action`)`
2. In browser enter URL `/path/with/trailing/slash/`
3. `{value}` will be set to `/path/with/trailing/slash` instead of what user entered.

I've tracked it down to this line of code: https://github.com/laravel/framework/blob/5.6/src/Illuminate/Http/Request.php#L138

If you made decision to have only URLs with non-trailing slashes to address the issue of duplicated pages (same content served with slash and withouth) you should at least offer a setting to get out of it, so a conscious dev can set it if really needed.

**Comment by KrzysztofMadejski** [comment]
I've hacked it with following code. Maybe it's a way to go..
```
        if (ends_with($this->request->getPathInfo(), '/')) {
            // Laravel is trailing slashes so we need to re-add it
            $value .= '/';
        }
```

**Comment by tillkruss** [comment]
Not a bug.
