### ISSUE TITLE
Failed jobs can be lost

### ISSUE THREAD

**Issue by yuloh** [laravel/framework#24549]
- Laravel Version: 5.6.0
- PHP Version: 7.1
- Database Driver & Version: N/A

### Description:

When a job fails it is completely deleted from the queue before raising the event which allows the failed job provider to log the failed job.

Since deleting the job and logging it with the `FailedJobProviderInterface` is not an atomic operation it's possible to lose a job completely.  The two operations are wrapped in a `try/finally` block which minimizes the chances of this happening, but it is still possible.  For example, the `Job::failed` method may allocate too much memory, causing the process to exit immediately.

It seems like there are two possible ways to solve this:

Option 1: Delete the job from the queue *after* it's logged by the failed job provider.  If logging the job failed it would stay reserved, so it would eventually be logged.  This is a simple change but means that failed jobs might be logged multiple times.
Option 2: Log the job as failed and remove it from the queue in an atomic operation.  How this works would depend on the queue driver and would preclude using the database to log failed jobs.  It seems like the majority of the queue drivers have a good solution for this:

- Beanstalk: use the native [`BURY` command](https://github.com/kr/beanstalkd/blob/c17f5030177f689b37ddd6cd2237c96491f6c399/doc/protocol.txt#L291).
- Redis: Add a new list, e.g. `queues:{name}:failed`.  Pop the job off of the reserved set and into the list using either a transaction or a lua script.
- SQS: SQS supports dead letter queues but it requires setting up a 'redrive policy' to send the message to the dead letter queue.  It looks like you can't atomically publish and delete in the same operation, so the SQS driver would likely have to publish to the DLX queue, then delete the message from the primary queue, which has the drawbacks of Option 1.  Using the redrive policy seems like the best option for SQS since it ensures you won't put duplicates in the DLX queue.
- Database: Execute the delete from the queue table and the insert into the failed table within the same transaction.
- Sync: Would continue to work how it does now, since it isn't actually persisted anywhere.

I attempted to solve this without making changes to the framework but it's not possible to override `FailingJob::handle` since it's resolved statically.  You also cannot override this behavior in the queue driver because there is no way to differentiate between `delete` being called for a successful job and delete being called for a failed job.

If `Job::delete` was called after raising the event you *could* implement support for burying jobs with a failed job provider, so it seems like a good solution would be to swap those two lines and allow users that want to bury jobs instead of using the database to use a custom failed job provider.

### Steps To Reproduce:

- Follow the docs to setup a new Laravel project with a non synchronous queue driver (like redis) and the database failed job provider.
- Create a new job that raises an exception in the `handle` method and causes a fatal error in the `failed` method, e.g.

```php
class TestFailedHandling implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public function handle()
    {
        throw new \Exception('Failing!');
    }

    public function failed()
    {

        $str = '';
        while (true) {
            $str .= str_repeat('x', 1024);
        }
    }
}
```

- Start a queue worker: `php artisan queue:work --tries=2`
- Dispatch the job.  Using `php artisan tinker` you can use `(function() { App\Jobs\TestFailedHandling::dispatch(); })();` (the IIFE is to force __destruct to be called immediately).
- Check for the failed job: `php artisan queue:failed`

**Comment by sisve** [comment]
> Database: Execute the delete from the queue table and the insert into the failed table within the same transaction.

I don't think this is the proper solution since the failed jobs provider could be a custom implementation that doesn't use a database. Or perhaps I'm just to focused on the "the insert into the failed table" part. If you rewrite that into "the invocation of the failed jobs provider" it sounds correct to me.

**Comment by yuloh** [comment]
@sisve I was describing how failed job handling could work if the queue driver itself handled logging failed jobs, which would likely mean removing the concept of a failed job provider entirely.  Basically I am proposing putting a method like `fail` (or some other name) on each driver that would implement the failed job handling that makes the most sense for that driver.

I think there is some merit to this idea as different drivers have their own strategies for handling this (like beanstalk's BURY command) and letting the driver decide how it handles failed jobs means it can usually fail a job transactionally.  If the queue driver does not decide how failed jobs are handled you end up with the situation you are pointing out where you can't guarantee the insert and the delete are done transactionally.

However, I realize that is a pretty large change so I proposed the simpler fix of swapping the order of the calls in `FailingJob::handle`.  If that change were implemented we *would* continue to use the failed job provider.  We wouldn't have any idea which provider was being used but it wouldn't matter.  Since the job won't be deleted until after the event has been fired and will retry until it's successful you get at least once delivery guarantees without a transaction.

Hopefully that makes sense.  Let me know if I can provide any additional clarification.

**Comment by themsaid** [comment]
For suggestions and feature requests please use the https://github.com/laravel/internals repo. We're trying to keep this repo issues for bug reporting only. Thanks for understanding.

**Comment by yuloh** [comment]
@themsaid please consider re-opening this.  I described the bug the  and included reproduction steps.  If it helps I can delete the thoughts on how the bug could be solved.

**Comment by sisve** [comment]
Wait, what? Why was this closed? Was he too helpful in ventilating some options that can be used to solve it? Shall we edit the issue and remove any attempt at solving it?

**Comment by themsaid** [comment]
Guys, closing an issue doesn't means it's not there, we're just trying to keep the repo for bug reports so it's easier for people to try to fix. I agree the described scenario is better be avoided and finding solutions for this would be great, but in a few days this post will be lost with hundreds of other bug reports and supports requests, etc...

We made the other repo so that this kind of stuff can be discussed for as long as it takes, we don't close issues there it's like an open thread for discussions.

Hope you understand why it was closed :)

**Comment by yuloh** [comment]
I edited the original issue to remove the suggestions for how to solve the issue and opened https://github.com/laravel/ideas/issues/1219 to discuss possible solutions.
