### ISSUE TITLE
Model bootTraits executes same method multiple times if two traits have the same base name

### ISSUE THREAD

**Issue by Gummibeer** [laravel/framework#24548]
- Laravel Version: 5.6
- PHP Version: 7.1
- Database Driver & Version: MySQL

*It's independent of versions so far I know.*

### Description:

The `Illuminate\Database\Eloquent\Model::bootTraits()` method executes the same `bootXyzTrait` method multiple times if the model uses two (or more) traits with the same base name.
This is simply resolvable by renaming the second trait but isn't cool if you want to extend a package trait for example.

### Steps To Reproduce:

https://github.com/spatie/laravel-activitylog/issues/392

Create a model (`App\User`) with a trait (`App\Traits\HasEmail`) which uses a trait (`Developer\Package\Traits\HasEmail`) with a trait boot method (`bootHasEmail`).

```php
class App\User {
  use App\Traits\HasEmail;
}

trait App\Traits\HasEmail {
  use Developer\Package\Traits\HasEmail;
}

trait Developer\Package\Traits\HasEmail {
  protected static function bootHasEmail() {
    var_dump('booting:HasEmail');
  }
}

// will output:
// booting:HasEmail
// booting:HasEmail
```

If the trait adds oberserver or other logic that should run just once it will run these things two times.

**Comment by tillkruss** [comment]
Can you submit a PR to resolve this?

**Comment by themsaid** [comment]
PR with a fix submitted to https://github.com/laravel/framework/pull/24556, thanks for sharing.

**Comment by Gummibeer** [comment]
Thanks for this fix. Will this get a backport to older versions?
And thanks for the fast fix - wrote this just as a copy of the linked issue on the road.
