### ISSUE TITLE
Relationships requires full model namespace for the referenced model

### ISSUE THREAD

**Issue by andreyan-andreev** [laravel/framework#24550]
Consider following relationship between two models:

```php
<?php namespace App\Models\Book;
class Page extends Model {}
//...

<?php namespace App\Models\Book;
class Book extends Model {
        public function pages() {
                 return $this->hasMany('Page'); // Not working, but I really want to be able to declare it like this.
                 return $this->hasMany('App\Models\Book\Page'); // Working
        }
}
```

I think it is fair to expect that models that do share namespace should not be expected to explicitly state the namespace when declaring relationships.

The related model instantiation happens here:
https://github.com/laravel/framework/blob/f377f9b9f2e952bd217ec9987cda5d039bf50dd5/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php#L656

To me it appears that the context namespace is not taken into consideration, the method attempts to instantiate the model based solely on the provided name;

Something in the lines of:
```php
    protected function newRelatedInstance($class)
    {
        if(strpos($class, '\\') === false) $class = (new \ReflectionObject($this))->getNamespaceName().'\\'.$class;
        return tap(new $class, function ($instance) {
            if (! $instance->getConnectionName()) {
                $instance->setConnection($this->connection);
            }
        });
    }
```
Appears to be addressing this at some extent. However I have been away from php for years, I am not really sure if by changing this protected method I am not braking some other crucial functionality.  Also if somebody can share what is the proper way to override framework internals, as apparently changing the file directly is not going to stick.

**Comment by laurencei** [comment]
You just need to do it like this:

```
return $this->hasMany(Page::class);
```

**Comment by andreyan-andreev** [comment]
Hey, thanks for input, that was helpful, it makes the declaration shorter. Its pity the framework cannot use this internally. I guess the reflection thing I tried is considered heavy in comparison with the ::class  keyword.
