### ISSUE TITLE
using $touches on parent and child falls in infinite loop

### ISSUE THREAD

**Issue by wisammechano** [laravel/framework#24553]
- Laravel Version: 5.6
- PHP Version: 7.1.9
- Database Driver & Version: MySQL 5.7.19

### Description:
It seems when having parent and child models both touching each other's timestamps, we get into an infinite loop and if debugging I get 'Maximum function nesting level of '256' reached, aborting!' Fatal exception.
Although logically it is understandable that touches will keep propagating. However, it is required sometimes to link changes to both.. Also the framework should guard against such events when it is hard to know where is the problem. The docs and google give no clue.

### Steps To Reproduce:
I have a user and profile models. When a user registers I create the user then instantiate a profile with mass filling using the constructor. Then $user->profile()->save($profile instance);

in the models of profile I used $touches = ['user'] and in user $touches = ['profile'];
profile belongsTo user and user hasOne profile

**Comment by tillkruss** [comment]
The docs section is called "Touching Parent Timestamps". If you need more than that, please submit a PR or write your own logic.

**Comment by devcircus** [comment]
IMO this is expected and reasonable. For the framework to handle this, it would have to make assumptions about your application. This is better left up to the developer. Honestly, two way touching has a very limited use-case, for most situations, it doesn't make sense for a change in the parent to cause the child to update its timestamps. 

Personally, I'd use an event in place of the parent to child touch.
