### ISSUE TITLE
Laravel 5.6.24 - Passing array or separate parameters to eloquent ::where() creates different sql query

### ISSUE THREAD

**Issue by Caroga** [laravel/framework#24551]
- Laravel Version: `5.6.24`
- PHP Version: `7.1`
- Database Driver & Version: `PostgreSQL 10.3, compiled by Visual C++ build 1800, 64-bit`

### Description:
Eloquent's database `where();` method returns different queries when it should not.
This causes problems when applying query/model caching mechanism as, well, the queries are different. 
`where();` should return SQL the same in both the use-cases of passing separate parameters or an array of parameters.

### Steps To Reproduce:
The following two queries produce different SQL statements:
```php
$users = DB::table('users')->where('id', 1)->get();
```
Gives:
```sql
select * from "users" where "id" = ?
```
While
```php
$users = DB::table('users')->where(['id' => 1])->get();
```
Gives:
```sql
select * from "users" where ("id" = ?)
```
The query is essentially the same, as is the output, but the second query is encapsulated while the first one is not, meaning this would not match a cached result and it will continue to actually query the database. 

This should produce the same query so you won't miss cached queries.

**Comment by staudenmeir** [comment]
The encapsulation of arrays is intended behaviour. Take a query like this:

````php
DB::table('users')->orWhere(['a' => 1, 'b' => 2])->where('c', 3)->get();
````
````sql
select * from "users" where ("a" = ? or "b" = ?) and "c" = ?
````

I would argue that this is the expected SQL. Without the encapsulation, the query would return a different result (`AND` has precedence over `OR`).

As you said, the queries are "essentially the same", but not *exactly* the same.

**Comment by 36864** [comment]
I think the argument here is that encapsulating a single condition is pointless and interferes with caches.

The fix would be to only encapsulate the condition if the condition array has more than one element in it.

```
DB::table('users')->where(['id' => 1, 'active' => 1])->get();
// select * from users where ("id" = ? AND "active" = ?)

DB::table('users')->where(['id' => 1])->get();
// select * from users where "id" = ?
```

**Comment by staudenmeir** [comment]
I don't think it's Laravel's job to check the array length.

**Comment by hyperized** [comment]
@staudenmeir at first that makes sense, but if not Laravel, who else is going to check the queries for this optimisation?

**Comment by 36864** [comment]
@hyperized The developer?

I'm struggling to see a legitimate use case where you would routinely be making the same query, but passing your filter as an array only some of the time.

**Comment by Caroga** [comment]
Thanks for responding @staudenmeir, @36864, @hyperized

@staudenmeir Going by what you stated, I wouldn't see a problem with encapsulating both of the clauses.
It's not about how you write your PHP statements, placing a `orWhere` before a `where` with or without arrays.
I would vote for encapsulating **all the time**, essentially writing the following:
```php
DB::table('users')->orWhere(['a' => 1, 'b' => 2])->where('c', 3)->get();
```
Would produce:
```sql
select * from "users" where ("a" = ? or "b" = ?) and ("c" = ?)
```
This would suffice.

@36864 I think that it would be the other way around. Both queries are valid SQL, but in the line of what Eloquent currently does, and that is encapsulating an array of parameters, I would vote for doing the same with separate parameters only.

**Comment by Caroga** [comment]
Also, @staudenmeir , `As you said, the queries are "essentially the same", but not exactly the same.`
Well, in the stated use-case one could argue that they are the same ;-).
But, it shouldn't depend on how you pass your arguments to your method call, should it?

**Comment by staudenmeir** [comment]
@Caroga If you use `where()` in different ways (multiple parameters vs. array), you can expect the same query result. But I would argue that you can't expect the generated SQL to match *exactly*.

**Comment by 36864** [comment]
If it can be done without a significant impact on performance, I don't see a strong argument against encapsulating everything.

I can imagine some people's tests would break if they're explicitly checking sql query strings, so I wouldn't submit the change on a point release.

Then again, this might all just be going through a lot of unnecessary work for the sake of a (presumably) rare use case that could be solved by the developer just checking inputs.

**Comment by hyperized** [comment]
If it's a minimal effort fix, it would potentially save up to 50% in any caching layer, such as model caching (https://github.com/GeneaLabs/laravel-model-caching for example) or even on the database layer itself (which also can contain a query cache). I don't think it's such a rare use-case, and a potential big win.

**Comment by 36864** [comment]
I didn't mean that caching is a rare use case. 

I meant that using `->where('field', $value)` and `->where($filter)`, with `$filter` being a single-element array in the same context isn't something I see very often.

**Comment by Caroga** [comment]
So, closed, no final argument as to why, just closed? Great action. :+1:

**Comment by Kyslik** [comment]
@Caroga I think because its not a bug, please open issue in internals https://github.com/laravel/ideas.

You see, many people get notifications because of this issue and since its not a bug it should not be here.

**Comment by Caroga** [comment]
Thank you @Kyslik for clearing that up. Knowing this makes me understand of the situation. I will continue and forward this "issue" to the appointed ideas section.
I will make sure to focus on the intention to always encapsulate.
Thanks. :+1:
