### ISSUE TITLE
Request class required drops posted data

### ISSUE THREAD

**Issue by m1kfb** [laravel/framework#24555]
- Laravel Version: 5.6.24
- PHP Version: 7.2.4
- Database Driver & Version: N/a

### Description:
Request with required rules dumps object returns messageBag

`
    public function rules()
    {
        return [
            'name' => 'required|string|max:190',
            'address_line_2' => 'string|max:190',
            'address_line_3' => 'string|max:190',
        ];
    }

}`

It's dropping all post data and returns if the form was submitted empty. If I remove the required rule, it works??

### Steps To Reproduce:
Submit to a Request class with the required rule.

**Comment by sisve** [comment]
Would you like to 1) edit your post to fix the formatting issues, and 2) tell us more details on the "dropping all post data and returns if the form was submitted empty"?

Do we need an authorize() method to reproduce the problem?
Do we need 14 rules to reproduce the rpboelm, or is one enough?

**Comment by m1kfb** [comment]
One is a enough, with the required rule check in place. Passing Order Market Ltd as name. It returns to the form with no values and the messageBag has Name is a required value. Has chosen-js on the form for some multi select but other than that not doing anything special

**Comment by m1kfb** [comment]
Sorry, it should have said: it is if there has nothing has been posted I have old on the input value attribute and it is empty. I have the name attribute correct as well

**Comment by themsaid** [comment]
> It's dropping all post data and returns if the form was submitted empty. If I remove the required rule, it works??

I don't understand what you mean, please share code example.

**Comment by sisve** [comment]
It sounds like you're asking for support, not filing an issue with the Laravel framework.

Are you saying that you're having problem using the old() helper to populate form fields when a form request failed validation?

**Comment by m1kfb** [comment]
guessing at this point its me being stupid but effective all I’ve done is create a resource controller, from the create method in the controller made a view, in the view i have a form all the correct attributes, csrf etc... I fill out the form correctly and i can post to store with Illuminate\Http\Request and have validation in the store method but if I have a separate request class \App\Http\CompanyCreateRequest and have the “required” check in there so ‘name’=>’required|string’ I get redirected back to an empty form not of the data entered its flashed back. If I had ‘name’=>’string’ it would work fine.

**Comment by m1kfb** [comment]
@sisve It is an issue with validation. I'm trying now with a fresh install as it may be a package I have installed that is causing an issue. If it is still an issue I'll add in-depth steps to replicate.

**Comment by themsaid** [comment]
@m1kfb please share more details then so we can help :)

**Comment by m1kfb** [comment]
It works fine on a fresh install sorry for wasting your time guys. Guessing it's the LaraTrust package as would touch anything that can cause this.

Thanks and sorry again @sisve  & @themsaid
