### ISSUE TITLE
Repeat records in pagination

### ISSUE THREAD

**Issue by DmitrySkibitsky** [laravel/framework#24568]
- Laravel Version: Laravel Framework 5.6.23
- PHP Version: PHP 7.2.6
- Database Driver & Version: Server version: 10.1.33-MariaDB MariaDB Server

### Description:
Records are repeated when using the paginate method
However, there are no entries that are available with the get() method
### model
```php
    public function category() {
        return $this->hasOne('App\Models\Category', 'id', 'category_id');
    }

     ...

    protected function getItems() {
        return SubCategory::orderBy('sorting_order', 'asc')
                  ->with(['category'])->paginate(10);
    }
```

### screenshots

when using the paginate method

![deepinscreenshot_ - _20180612172955](https://user-images.githubusercontent.com/20288556/41297245-68c810d6-6e67-11e8-9a87-d921ff328960.png)
![deepinscreenshot_ - _20180612173019](https://user-images.githubusercontent.com/20288556/41297246-68f6417c-6e67-11e8-84ec-abfd9d3ba6bb.png)

Here, the get method was used and a record was found by id. However, the paginate method does not have this record.
![deepinscreenshot_ - _20180612171038](https://user-images.githubusercontent.com/20288556/41297373-a820967c-6e67-11e8-99b1-d8c26760cf77.png)
![deepinscreenshot_ - _20180612171108](https://user-images.githubusercontent.com/20288556/41297374-a848725a-6e67-11e8-9f27-431efbb4a545.png)

I removed the methods withTranslation from the query thinking that this is because of the package dimsav / laravel-translatable However this did not help.

Also, the cviebrock/eloquent-taggable package is used and 'strict' => false in config/database.php

**Help to understand what the problem is**

**Comment by sisve** [comment]
Can you show us the generated sql queries from the paginator?

**Comment by DmitrySkibitsky** [comment]
@sisve 
```sql
select * from `localizations` where `status` = '1'

select * from `users` where `id` = '1' limit 1

select count(*) as aggregate from `sub_categories`

select * from `sub_categories` order by `sorting_order` asc limit 10 offset 0

select * from `categories` where `categories`.`id` in ('14', '15', '24')

select * from `category_translations` where `category_translations`.`category_id` in ('14', '15', '24') and `category_translations`.`locale` = 'uk'

select * from `sub_category_translations` where `sub_category_translations`.`sub_category_id` = '62' and `sub_category_translations`.`sub_category_id` is not null

select * from `sub_category_translations` where `sub_category_translations`.`sub_category_id` = '43' and `sub_category_translations`.`sub_category_id` is not null

select * from `sub_category_translations` where `sub_category_translations`.`sub_category_id` = '42' and `sub_category_translations`.`sub_category_id` is not null

select * from `sub_category_translations` where `sub_category_translations`.`sub_category_id` = '41' and `sub_category_translations`.`sub_category_id` is not null

select * from `sub_category_translations` where `sub_category_translations`.`sub_category_id` = '40' and `sub_category_translations`.`sub_category_id` is not null

select * from `sub_category_translations` where `sub_category_translations`.`sub_category_id` = '39' and `sub_category_translations`.`sub_category_id` is not null

select * from `sub_category_translations` where `sub_category_translations`.`sub_category_id` = '38' and `sub_category_translations`.`sub_category_id` is not null

select * from `sub_category_translations` where `sub_category_translations`.`sub_category_id` = '37' and `sub_category_translations`.`sub_category_id` is not null

select * from `sub_category_translations` where `sub_category_translations`.`sub_category_id` = '36' and `sub_category_translations`.`sub_category_id` is not null

select * from `sub_category_translations` where `sub_category_translations`.`sub_category_id` = '35' and `sub_category_translations`.`sub_category_id` is not null
```

**Comment by sisve** [comment]
Only two of the queries are relevant for the paginator. And it's obvious that you have a SELECT N+1 problem.

    select count(*) as aggregate from `sub_categories`

    select * from `sub_categories` order by `sorting_order` asc limit 10 offset 0

Anyhow, the sql statement looks okay. I presume that page 2 would be identical, except and "offset 10" at the end. So far you have not shown anything that makes it obvious that it is an issue in the Laravel framework. Can you tell us how you know that this isn't just a problem in your code?

**Comment by DmitrySkibitsky** [comment]
@sisve , 
Source: [https://github.com/DmitrySkibitsky/laravel-site-mpa/](https://github.com/DmitrySkibitsky/laravel-site-mpa/) 
Dump db: [https://dropmefiles.com/Q3WFy](https://dropmefiles.com/Q3WFy) 
Problem on Route: [https://github.com/DmitrySkibitsky/laravel-site-mpa/blob/master/routes/web.php#L42](https://github.com/DmitrySkibitsky/laravel-site-mpa/blob/master/routes/web.php#L42)
Login page: /admin
Login data: admin@admin admin

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
