### ISSUE TITLE
The model modifier cannot get the correct type?

### ISSUE THREAD

**Issue by DavidNineRoc** [laravel/framework#24560]
* Laravel Version: 5.5.40
* PHP Version: 7.1.13-nts
****
# Description
I did this for some properties of the model
```
class User extends Model
{
    protected $casts = [
        'status' => 'array'
    ];
}
```
I set`status`to array type, and if my database is inserted, the default`status`is null or null will also return a null to me. That's not what I wanted. I think that when I set`status`to array type, even if the value in my database is null or null.laravel should return an empty array for me, this is the correct type.

**Comment by Kyslik** [comment]
Just use [accessor](https://laravel.com/docs/5.6/eloquent-mutators#defining-an-accessor).

```php
return $value ?? [];
```
---

I get what you are raising tho.

**Comment by DavidNineRoc** [comment]
I'm not asking how to fix the problem, it's that the problem is actually. PHP is a weak type, but I set the property to an array, and I should force an array type to return, regardless of his data.
