### ISSUE TITLE
Creating and dropping a table during test breaks RefreshDatabase trait

### ISSUE THREAD

**Issue by flyingL123** [laravel/framework#24575]
I'm attempting to create and drop a table during a test. The test uses Laravel's `RefreshDatabase` trait. I am showing a minimal example test class below to demonstrate the issue. The class contains two tests, both of which create a `Product` with `id = 1`.

Under normal circumstances, this works fine, because the `RefreshDatabase` trait clears the database between tests. However, when I introduce a method to create a table and drop a table within the test, an error occurs. Here's the test:

```
<?php

namespace Tests\Feature;

use App\Product;
use Tests\TestCase;
use Illuminate\Support\Facades\Schema;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class ExampleTest extends TestCase
{
    use RefreshDatabase;

    public function setUp()
    {
        parent::setUp();

        $this->createStubTable();
    }

    /**
     * @test
     */
    public function example_first_test()
    {
	factory(Product::class)->create(['id' => 1]);
    }

    /**
     * @test
     */
    public function example_second_test()
    {
	factory(Product::class)->create(['id' => 1]);
    }

    public function tearDown()
    {
        $this->dropStubTable();

        parent::tearDown();
    }

    private function createStubTable()
    {
        Schema::create('stubs', function ($table) {
            $table->increments('id');
            $table->string('name');
            $table->timestamps();
        });
    }

    private function dropStubTable()
    {
        Schema::dropIfExists('stubs');
    }
}
```

The error is:

>Tests\Feature\ProjectableTest::example_second_test Illuminate\Database\QueryException: >SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'

Commenting out the methods to create and drop the table, no error occurs:

```
<?php

namespace Tests\Feature;

use App\Product;
use Tests\TestCase;
use Illuminate\Support\Facades\Schema;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class ExampleTest extends TestCase
{
    use RefreshDatabase;

    public function setUp()
    {
        parent::setUp();

        //$this->createStubTable();
    }

    /**
     * @test
     */
    public function example_first_test()
    {
	factory(Product::class)->create(['id' => 1]);
    }

    /**
     * @test
     */
    public function example_second_test()
    {
	factory(Product::class)->create(['id' => 1]);
    }

    public function tearDown()
    {
        //$this->dropStubTable();

        parent::tearDown();
    }

    private function createStubTable()
    {
        Schema::create('stubs', function ($table) {
            $table->increments('id');
            $table->string('name');
            $table->timestamps();
        });
    }

    private function dropStubTable()
    {
        Schema::dropIfExists('stubs');
    }
}
```

Why do these methods break the `RefreshDatabase` trait functionality? Is this a bug?

Also, the app is using mysql as it's database. This seems like it might be relevant, but still doesn't explain what's happening: https://github.com/laravel/framework/issues/23144

**Comment by flyingL123** [comment]
@morloderex But what is even causing the issue? I'm not having trouble deleting the table. The table gets created and deleted fine. The problem is that the normal functionality of `RefreshDatabase` doesn't seem to be working? Is my creating/dropping of the table somehow interfering with what `RefreshDatabase` is trying to do?

**Comment by morloderex** [comment]
It might be. 

Because you are calling the parent::tearDown() after you attempt to delete the table. And i know why but i don't think that you can create a temperay table without using some custom code.

**Comment by morloderex** [comment]
This is how i have archieved the same thing:
`https://github.com/Napp/dbalcore/blob/master/tests/TestCase.php`

**Comment by flyingL123** [comment]
Even if I remove the call to drop the table, and instead change the create table method to:

```
        if (!Schema::hasTable('stubs')) {
            Schema::create('stubs', function ($table) {
                $table->increments('id');
                $table->string('name');
                $table->timestamps();
            });
        }
```
The error still occurs.

**Comment by flyingL123** [comment]
I've been putting breakpoints everywhere in `Illuminate/Database/Concerns/ManagesTransactions.php` and `Illuminate/Foundation/Testing/RefreshDatabase.php` trying to find a difference between when the test runs with the create and drop methods commented out and when they are not.

I can't find any difference.

**Comment by flyingL123** [comment]
Oh and also, even if I don't use the `setUp` and `tearDown` methods, but instead just create and drop the table and the beginning and end of each test, the error still occurs.

**Comment by flyingL123** [comment]
I think this might be the answer:

https://dev.mysql.com/doc/refman/8.0/en/implicit-commit.html
