### ISSUE TITLE
Using a global scope with addSelect overwrites column names passed via find(), get() & first()

### ISSUE THREAD

**Issue by nshontz** [laravel/framework#24579]
- Laravel Version: 5.6.23
- PHP Version: 7.2.6
- Database Driver & Version: pgsql - PostgreSQL 9.5.12 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609, 64-bit

### Description:
 Using a global scope with addSelect, column names are overwritten when using first(), get & find() but appended for select()

Scope:
```
    protected static function boot()
    {
        parent::boot();
        static::addGlobalScope('shapedata', function (Builder $builder) {
            $builder->addSelect('*');
            $builder->addSelect(\DB::raw('ST_AsText(shape) as shapedata'));
        });
    }
```

```
$overwritten = Region::find($this->id, [DB::raw('ST_Contains(shape, ST_GeomFromText(\'Point(' . $point->getLng() . ' ' . $point->getLat() . ')\')) as contained')]);
```
//Returns *, shapedata

```
$appended = Region::select(DB::raw('ST_Contains(shape, ST_GeomFromText(\'Point(' . $point->getLng() . ' ' . $point->getLat() . ')\')) as contained'))->find($this->id);
```
//Returns *, shapedata, contained

### Steps To Reproduce:

Create a global scope and append columns using addSelect()
Pass column names to a query via first( ['name']),  get( ['name']) or  find($id, ['name])
Only columns from the scope will be returned

**Comment by staudenmeir** [comment]
This behavior is not caused by global scopes:

    Test::select('a')->get(['b']);    // select "a" from "tests"
    Test::addSelect('a')->get(['b']); // select "a" from "tests"

The `$columns` parameter of `first()`/`get()`/`find()` is only used, when `select()` and `addSelect()` haven't been called. It's the intended behaviour since the first version.

**Comment by hexatex** [comment]
If anyone ends up here, this is what I did from inside one of my scopes.

```php
// Param binding & lateral join don't work together, but id is validated in request so I used str interpolation
$optionIds = collect($selectedOptions)->pluck('id')->join(',');

$select = (array)($query->columns ?? '*');
$select[] = 'option_by_options.count';

$query->select($select)
    ->join(DB::raw("
        LATERAL option_by_options(array[{$optionIds}], {$category->id}) as option_by_options
    "), function (JoinClause $query) {
        $query->whereColumn('option_by_options.id', 'options.id');
    });
```

If you know a way to bind variables in my join up there please let me know, Im tired.

**Comment by SagarNaliyapara** [comment]
@hexatex Your solution won't work when you're using subquery, it doesn't bind parameters

**Comment by SagarNaliyapara** [comment]
Ended up doing this,
```
    protected static function booted()
    {
        static::addGlobalScope(function (Builder $builder) {
            $builder->when(empty($builder->getQuery()->columns), fn ($q) => $q->select('*'))
                ->addSelect(...);
        });
    }
```
