### ISSUE TITLE
`Querybuilder`'s `parseSub` throwing if you provide an `EloquentBuilder`

### ISSUE THREAD

**Issue by snags88** [laravel/framework#24594]
- Laravel Version: 5.6.24
- PHP Version: 7.2.4
- Database Driver & Version: MySql (mysql  Ver 15.1 Distrib 10.2.14-MariaDB, for osx10.13 (x86_64) using readline 5.1)

### Description:
I was looking to use the subquery functions like `fromSub` and `joinSub` but kept getting an `InvalidArgumentException`. Each of these functions use the [`parseSub`](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Database/Query/Builder.php#L320) protected function that expects an instance of `Illuminate\Database\Query\Builder` or a string representing the subquery.

The reason why I ran into the error was because I was passing along an instance of `Illuminate\Database\Eloquent\Builder`

### Steps To Reproduce:
First, generate a sub-query from an eloquent model. Then try to use the sub-query in `fromSub` or `joinSub`.
```php
// A very simple sub-query for simplicity
$subQuery = \App\Models\User::where('id', '>', 3);

\App\Models\Blog::joinSub($subQuery, 'users', 'blog.user_id', '=', 'users.id');
```
The work around for now is to call `toBase()` on the EloquentBuilder to get the QueryBuilder instance

**Comment by snags88** [comment]
@taylorotwell I was told on the [closed PR](https://github.com/laravel/framework/pull/24595) that it most likely won't get looked at so I'm going to post my discussion on this issue, but feel free to let me know the best way to continue the discussion is.

Here is my response to your question on the PR:

> Hey @taylorotwell, the `fromSub` should always return the base query builder and we shouldn't expect to be able to call Eloquent builder methods. The change I was attempting to make was to be able to define the subquery as a base query builder or Eloquent builder since that subquery is consumed by the query builder and it spits out the raw query + bindings. In other words, the subquery should be self-contained and should not impact the main query.
> 
> This is the current code:
> ```php
>     public function fromSub($query, $as)
>     {
>         list($query, $bindings) = $this->createSub($query);
>         return $this->fromRaw('('.$query.') as '.$this->grammar->wrap($as), $bindings);
>     }
> ```
> The `createSub` code:
> ```php
>     protected function createSub($query)
>     {
>         // If the given query is a Closure, we will execute it while passing in a new
>         // query instance to the Closure. This will give the developer a chance to
>         // format and work with the query before we cast it to a raw SQL string.
>         if ($query instanceof Closure) {
>             $callback = $query;
>             $callback($query = $this->forSubQuery());
>         }
>         return $this->parseSub($query);
>     }
> ```
> The `parseSub` only expects instance of self (base query builder) or a raw string query.
> ```php
>     protected function parseSub($query)
>     {
>         if ($query instanceof self) {
>             return [$query->toSql(), $query->getBindings()];
>         } elseif (is_string($query)) {
>             return [$query, []];
>         } else {
>             throw new InvalidArgumentException;
>         }
>     }
> ```
> 
> Since Eloquent builder also has `toSql` and `getBindings` it can convert itself to the raw sql and bindings.

**Comment by reinaldorauch** [comment]
+1 on this.

I'm having this exactly issue when creating a method for my model:

```php
// inside an eloquent model
public static function myMethodWithSubqueryJoin() {
  $sub = self::selectRaw('max(created_at) as created_at, line_id')
    ->whereNotNull('publish_data')
    ->groupBy('line_id');

 $tbl = $this->table;
  return self::joinSub($sub, 'lastest', function ($join) use ($tbl) {
    $join->on($tbl . '.created_at', '=', 'lastest.created_at');
    $join->on($tbl . '.line_id', '=', 'lastest.line_id');
  });
}
```

Since the documentation says that Eloquent Models are especializations of Builder, it leads one to think this should work.
