### ISSUE TITLE
Laravel throttle middleware and load balancer

### ISSUE THREAD

**Issue by LarsWith** [laravel/framework#24599]
- Laravel Version: 5.5
- PHP Version: 7.0
- Database Driver & Version: mysql 5.7

Not sure if this is a bug but if I use Laravels `\Request::ip()` while under a load balancer it always returns the balancer ip address.

This means that if I use the `throttle middleware` my users will get locked out fast, any fix to this?

**Comment by laurencei** [comment]
Hi, that's a configuration issue and not a bug. You need to look into the trustedProxy settings in Laravel, and you can configure to receive the IP of the actual user.

**Comment by astierler** [comment]
To above point, also make sure your Load Balancer is passing along the client IP's in X-Forwarded-For header. (Most should by default, but not always)
