### ISSUE TITLE
Fix support custom URLs for S3 storage

### ISSUE THREAD

**Issue by finagin** [laravel/framework#24591]
- Laravel Version: `≥5.5.21`
- PHP Version: `not relevant`
- Database Driver & Version: `not relevant`

### Description:
AWS-SDK-S3 don't support `url`. Needs `endpoint` configuration variable.

This way works only for `FilesystemAdapter::url`, but not for other methods like `exists`, `put`, `temporaryUrl` etc. with S3 adapter.

### Steps To Reproduce:
  1. In `config/filesystems.php` set `s3.url` not AWS S3 like `https://hb.bizmrg.com`
  1. Call `Storage::cloud()->put('test/test.txt', 'cloud');`

### Steps To Solution:
  1. Revert laravel/framework#22037
  1. Fix laravel/laravel#4483 change `url` to `endpoint`

**Comment by finagin** [comment]
laravel/laravel#4686 and laravel/framework#24593 must be merged together

**Comment by driesvints** [comment]
Going to close this as the PRs were closed as well. I think it's best if you lay down your use case at https://github.com/laravel/ideas first to gather support and try again with the info Taylor has requested.
