### ISSUE TITLE
Laravel 5.6 Not allowing decimal point start with zero 0.0001857710

### ISSUE THREAD

**Issue by vickygillsf** [laravel/framework#24604]
- Laravel Version: 5.6
- PHP Version: 7.2
- Database Driver & Version:

### Description:

So I have value like this 0.0001857710 i want to store in database using laravel 5.6 Eloquent ,
Eloquent is changing value to 10 i don't want to store 10 in Database i want to store 0.0001857710 this value. First i want to fix the value changing then i want to store decimal value.

My DataType is decimal(10,10),

But Still error is :-

SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'amount' at row 1 (SQL: update 'users' set 'amount' = 10, 'updated_at' = 2018-06-15 00:32:32 where 'id' = 13

Stackoverflow ; 
 https://stackoverflow.com/questions/50863942/laravel-5-6-not-allowing-decimal-point-start-with-zero-0-0001857710 
### Steps To Reproduce:

Just var_dump(0.0001857710)

Result will be  0.00018577string(2) "10"

**Comment by staudenmeir** [comment]
Please close the issue.
