### ISSUE TITLE
Use database migrations from outside laravel

### ISSUE THREAD

**Issue by kirtangajjar** [laravel/framework#24609]
Thanks to the readme at -  https://github.com/illuminate/database. I can use Laravel ORM in simple PHP projects. 

However I just want to know how to specify the migration table and trigger the effect of `php artisan migrate` command.

**Comment by decadence** [comment]
Welcome to Laravel! We are glad to have you as part of the community.

Unfortunately GitHub is not an appropriate platform for general application issues. This is only for issues/bugs with the framework code itself.

Please close your issue, and instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

Laravel Slack (https://larachat.co/)
Laravel.io Forum (https://laravel.io/forum)
Laracasts Forum (https://laracasts.com/discuss)
StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks!

**Comment by kirtangajjar** [comment]
Oh. Okay. Thanks for pointing that out @decadence
