### ISSUE TITLE
More and more members of reference are created by "RedisTaggedCache"

### ISSUE THREAD

**Issue by Except10n** [laravel/framework#24603]
- Laravel Version: 5+
- PHP Version:*
- Database Driver & Version: *

### Description:
When I use cache tags , it will create references
```
Cache::tags(['tagname'])->put('test', 'value', 1);

127.0.0.1:6379> KEYS *
1) "laravel:***********:standard_ref"
2) "laravel:tag:tagname:key"
3) "laravel:*************:test"

After the item expired

127.0.0.1:6379> KEYS *
1) "laravel:***********:standard_ref"
2) "laravel:tag:tagname:key"
```
"laravel:***********:standard_ref"  It‘s memeber will leave more and more useless "key" behind

**Comment by tillkruss** [comment]
If you can't flush your cache database on a regular basis, don't use tags or write a custom script to clean up leftovers.

**Comment by aprivette** [comment]
I experienced this issue and created a package to clean it up! https://github.com/aprivette/laravel-cache-refs
