### ISSUE TITLE
Specified key was too long error

### ISSUE THREAD

**Issue by AmitM13** [laravel/framework#24601]
- Laravel Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
Hi this is framework issue ?
I hope you will update this thing in next Laravel version.

Thanks

**Comment by BrandonSurowiec** [comment]
Check out the "Index Lengths & MySQL / MariaDB" section in the docs:

[https://laravel.com/docs/5.6/migrations#creating-indexes](https://laravel.com/docs/5.6/migrations#creating-indexes)

**Comment by paulredmond** [comment]
Check this post on it, perhaps it will help you https://laravel-news.com/laravel-5-4-key-too-long-error
