### ISSUE TITLE
Response Json is removing the port number from the Route method

### ISSUE THREAD

**Issue by filtration** [laravel/framework#24619]
- Laravel Version: 5.6.0
- PHP Version: 7.3
- Database Driver & Version: PDO, mysql

### Description:

When using the Route method inside Responses, it removes the port. 

Visiting your local machine 

    http://localhost:3000 (or any port number) 

Outside a response: 

    dd(route('like.update', 1))

produces: 

    //localhost:3000/like/1

When adding that inside a response it produces:

    ["http:\/\/localhost\/like\/1"]

### Steps To Reproduce:

Visit your localhost, with the port number, for example: http://localhost:8080

Create a route in your web:

    Route::post('like/{id}', function($id) {
        dd($id);
    })->name('like.update');

    Route::get('/', function() {
        // This will produce the port number http://localhost:8080/like/1
        dd(route('like.update', 1));
     
        // This will not include the port number, just http://localhost/like/1
        return response()->json([
            route('like.update', 1)
        ]);
    });

**Comment by Naoray** [comment]
@filtration copied your code sample and for me the port was returned in both (json response and inside `dd` call).

**Comment by filtration** [comment]
<img src="https://i.imgur.com/BogUXCD.png">

**Comment by tillkruss** [comment]
Sounds like an application/server issue to me.

**Comment by Naoray** [comment]
@filtration  ![image](https://user-images.githubusercontent.com/10154100/41509700-23c3a424-7258-11e8-8da5-05de253c5922.png)
