### ISSUE TITLE
PusherBroadcaster.php error from null socket

### ISSUE THREAD

**Issue by pursehouse** [laravel/framework#24618]
- Laravel Version: v5.6.24
- PHP Version: 7.2.1
- Database Driver & Version:
pusher/pusher-php-server              v3.0.4

### Description:

I get this error from a message submit. The message appears into the chat window, even after refresh, but every message submit returns this http:500 error.

The pusher api configs are all in the .env

Same as  #24425 which was closed with zero research/evaluation.

### Steps To Reproduce:

Follow this tutorial: 
https://pusher.com/tutorials/chat-laravel/

```
"message": "",
"exception": "Illuminate\\Broadcasting\\BroadcastException",
"file": "laravel\\vendor\\laravel\\framework\\src\\Illuminate\\Broadcasting\\Broadcasters\\PusherBroadcaster.php",
"line": 116,
"trace": [
    {
        "file": "laravel\\vendor\\laravel\\framework\\src\\Illuminate\\Broadcasting\\BroadcastEvent.php",
        "line": 48,
        "function": "broadcast",
        "class": "Illuminate\\Broadcasting\\Broadcasters\\PusherBroadcaster",
        "type": "->"
    },
    {
        "function": "handle",
        "class": "Illuminate\\Broadcasting\\BroadcastEvent",
        "type": "->"
    },
    {
        "file": "laravel\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php",
        "line": 29,
        "function": "call_user_func_array"
    },
```

**Comment by tillkruss** [comment]
Framework bug reports only please.

**Comment by pursehouse** [comment]
it is code in the framework erroring

https://github.com/laravel/framework/blob/5.6/src/Illuminate/Broadcasting/Broadcasters/PusherBroadcaster.php

what the hell are you talking about?

**Comment by tillkruss** [comment]
Reopen an issue with actual steps to reproduce the issue.
