### ISSUE TITLE
session()->replace() doesn't replace $attributes entirely like comment implies

### ISSUE THREAD

**Issue by jonaslm** [laravel/framework#24610]
- Laravel Version: 5.6.24
- PHP Version: N/A
- Database Driver & Version: N/A

### Description:

Illuminate\Session\Store has the following method `replace`:
```
/**
 * Replace the given session attributes entirely.
 *
 * @param  array  $attributes
 * @return void
 */
public function replace(array $attributes)
{
	$this->put($attributes);
}
```

The comment implies that the internal `$attributes` array gets replaced with the given array, but it rather merges it with the argument (since it just performs a normal `put`).

### Steps To Reproduce:

```
>>> session()->put(['foo' => true, 'bar' => true]);
=> null
>>> session()->all()
=> [
     "foo" => true,
     "bar" => true,
   ]
>>> session()->replace(['foo' => false, 'zed' => false]);
=> null
>>> session()->all()
=> [
     "foo" => false,
     "bar" => true,
     "zed" => false,
   ]
```

Expected `bar` to be gone after calling `replace`.

### Proposed solution:

Either clarify the comment, remove the method, or make it work like the comment implies (`flush` then `put`, or just `$this->attributes = $attributes`).

**Comment by lagbox** [comment]
It did 'replace the **given** session attributes entirely'. It doesn't say it will replace anything that wasn't 'given' to it.

**Comment by devcircus** [comment]
Yep. "given" is the keyword here.

**Comment by tillkruss** [comment]
Feel free to submit a PR.
