### ISSUE TITLE
Eloquent/Relations/HasOneOrMany vs Timestamps - Error on related model update when only using created_at timestamp

### ISSUE THREAD

**Issue by zambodaniel** [laravel/framework#24627]
On the relatedModel:
public $timestamps = true;
const UPDATED_AT = null;
when trying to do $myModel->relatedModel()->where([some conditions])->update([some fields]);
PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column '' in 'field list' 

https://github.com/laravel/framework/blob/2244814657a93959448561e5acb70cc703cdfe35/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php#L317

**Comment by staudenmeir** [comment]
What's your exact Laravel version?

**Comment by zambodaniel** [comment]
@staudenmeir hello!
$ php artisan -V
Laravel Framework 5.5.40

Sorry, my fault! Already fixed at 5.6.15
