### ISSUE TITLE
Laravel 5.6 in Windows 7 php 7.2.6 file_exists(): open_basedir error

### ISSUE THREAD

**Issue by yannakos** [laravel/framework#24630]
- OS: Windows 7
- Laravel Version: 5.6.21
- PHP Version: 7.2.6
- Database Driver & Version: MySQL 5.7.17

### Description:
i was using Laravel 5.5 in Windows 7 with php 7.1.1 before
but Server Requirements of Laravel 5.6 is PHP >= 7.1.3
so i fresh install php 7.2.6

follow the document : https://laravel.com/docs/5.6/authentication#introduction
i use command to install Laravel
composer create-project --prefer-dist laravel/laravel blog_a "5.5.*"
composer create-project --prefer-dist laravel/laravel blog_b

then create the database tables
php artisan migrate

on each of blog_a and blog_b use this command
php artisan make:auth

open browser visit localhost.blog_a AND localhost.blog_b
in both host register a new user then logout

if i click Login on each host:
[Laravel 5.5] blog_a (no error)

[Laravel 5.6] blog_b (show an error)
"file_exists(): open_basedir restriction in effect. File(...\blog_b\resources\lang/en/Forgot Your Password?.php)

if i disable open_basedir in php.ini OR
remove the "?" {{ __('Forgot Your Password?') }} in resources\views\auth\login.blade.php
all worked fine

so why in the same OS and same server settings, 5.5 is no error but 5.6 has error ?

i also tried use php 7.1.18 instead of php 7.2.6
[Laravel 5.5] blog_a (no error)
[Laravel 5.6] blog_b (same error file_exists(): open_basedir restriction)

may be i missing something ? thanks

**Comment by staudenmeir** [comment]
What's the error's stacktrace?

**Comment by yannakos** [comment]
thankyou for your reply

do it means this on the error screen left side ?

68 ErrorException
67 ErrorException
66 file_exists
65 Illuminate\Filesystem\Filesystem exists
64 Illuminate\Translation\FileLoader loadPath
63 Illuminate\Translation\FileLoader load
62 Illuminate\Translation\Translator load
61 Illuminate\Translation\Translator getLine
60 Illuminate\Translation\Translator get
59 Illuminate\Translation\Translator getFromJson
58 __
57 include
...
... and many more

**Comment by staudenmeir** [comment]
This looks like an issue with PHP and Windows 7 (it works on Windows 10).

Windows doesn't allow filenames with question marks and apparently, just checking the file existence is enough to cause an error.

It works with Laravel 5.5 because 5.6 replaced the hardcoded English strings with translations (#23342). 

In your case, the best solution is probably to replace `{{ __('Forgot Your Password?') }}` with a hardcoded string (in your language). If you need the translation feature, use `{{ __('Forgot Your Password') }}`.

**Comment by yannakos** [comment]
i don't know if this help, i captured the error screen left side bar
[laravel56_make_auth_error](http://os33.atwebpages.com/laravel56_make_auth_error.html)

**Comment by themsaid** [comment]
When using the `__()` helper laravel checks if the translation line was found in a JSON file and if not it'll try to guess the filename where it can find this line which uses `file_exists()`, with `open_basedir` this prevents laravel from looking into certain directories which will prevent you from running the framework, make sure you disable that setting.

**Comment by yannakos** [comment]
but `open_basedir` is security option, this is more important over all other things
unless you want an unknown package delete all files in E:\ , F:\ or even //My_NAS

in Laravel 5.5 with enabled open_basedir is running very well

but this is no sense
`and if not it'll try to guess the filename where it can find this line which uses file_exists()`

actually is not the open_basedir problem, is Laraver to guess the path 
and pass a wrong path fill into file_exists()

**Comment by driesvints** [comment]
This seems more like a config issue than an actual problem with Laravel tbh. Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
