### ISSUE TITLE
Parse error on install

### ISSUE THREAD

**Issue by carolinecblaker** [laravel/framework#24632]
- Laravel Installer Version: 1.1
- PHP Version: virtualbox 7.1, native 5.6.30
- Database Driver & Version: Mysql 5.7

### Description:

When generating optimized autoload files, installer quits on parse error.

### Steps To Reproduce:

laravel new project
cd /project
composer update --ignore-platform-reqs (because [this](https://github.com/laravel/homestead/issues/638).)

Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
PHP Parse error:  parse error in /Users/ccb/Code/zapooca/deploy/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 242

Parse error: parse error in /Users/ccb/Code/zapooca/deploy/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 242

composer.json:
`{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": "^7.1",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "^5.4",
        "laravel/tinker": "^1.0"
    },
    "require-dev": {
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^2.0",
        "phpunit/phpunit": "^7.0"
    },
    "autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "extra": {
        "laravel": {
            "dont-discover": [
            ]
        }
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true,
        "platform": {
            "php": "5.6.30"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
`

**Comment by staudenmeir** [comment]
Why are you using PHP 5.6 instead of 7.1?

**Comment by carolinecblaker** [comment]
Because until sometime later this fall, at least half my clients depend on me using php 5.6 on my local machine. 
There should be no need to upgrade that using Homestead for Laravel.

**Comment by carolinecblaker** [comment]
Wow. Closed already. Thanks for the help!

**Comment by taylorotwell** [comment]
Hi @carolinecblaker,

It looks like the version of Laravel you are attempting to run requires PHP 7.1 unfortunately.

**Comment by carolinecblaker** [comment]
Thanks @taylorotwell 

@mattstauffer Running it from inside the virtual machine was what I needed to do. Solved!
