### ISSUE TITLE
Can you guys add to the docs the fact that you can declare a queue in the constructor?

### ISSUE THREAD

**Issue by nkiermaier** [laravel/framework#24638]
The fact that you can do ``` $this->queue = 'my_queue' ``` inside the constructor was eye opening for me. We've been doing onQueue() this entire time.

It could be really helpful to add this to the Docs!

**Comment by staudenmeir** [comment]
You're welcome to submit a pull request: https://github.com/laravel/docs

**Comment by nkiermaier** [comment]
Thanks for the docs link.

P.R. is done.
https://github.com/laravel/docs/pull/4339
