### ISSUE TITLE
Laravel 5.6 session persistence issue

### ISSUE THREAD

**Issue by webribs** [laravel/framework#24649]
- Laravel Version: 5.6
- PHP Version: 7.1
- Database Driver & Version: MySQL

### Description:

I'm getting session persistence issue in laravel 5.6 ... the issue I'm facing is: Like I have 2 users user 1 is logged in from pc 1 and user 2 is logged in from pc 2. Sometimes user 1 gets logged in from user 2 account without logout.  Same case with other users like other user and admin.

I've tried to store session in database but again I'm getting this issue again.

PHP version: 7.1
Database: MySQL

I've tried many ways to solve this issue but still getting this issue. Please tell me what to do. I'm really stuck

Thanks,
Rizwan

### Steps To Reproduce:
I'm unable to reproduce this issue as this happens randomly.

**Comment by Kyslik** [comment]
Do you use same Chrome user by any chance? It may be that sync functionality of browsers synch all kind of data...

**Comment by webribs** [comment]
I've tried chrome & firefox. Client is in another office and we are working on another office. Even on my PC I was getting employee ID while I was logged in as admin.

**Comment by sisve** [comment]
We would need a lot more information to debug this. 

1. What web server software are you using?
2. What operating system are you using?
3. Can you reproduce this problem in a new Laravel application?

The easiest way to debug this issue is if we were to get access to a new Laravel installation (new github repository perhaps) with enough code to reproduce the problem.

**Comment by webribs** [comment]
@sisve 

1- I'm using Apache 2.4.33 with MySql version 5.6.36
2- Operating System | linux
3- Previously I was using Laravel 5.4 and I upgraded to Laravel 5.6 and getting same issue on 5.6 version as well.

After taking permission from my boss I'll add a repository on github. 




-- | --




Operating System | linux
-- | --




--

**Comment by laurencei** [comment]
Seems like a server/config/application issue, and not directly related to the framework.

If you have  more info that can point to a framework issue, please feel free to post it here.
