### ISSUE TITLE
Can not get data from `.env`.

### ISSUE THREAD

**Issue by ThunderBirdsX3** [laravel/framework#24643]
- Laravel Version: 5.6.24 and 5.6.26 too.
- PHP Version: 7.2.6 

### Description:
So, You will got this problem after you run command `php artisan config:cache`

And try to get data from `.env`. It always got `null`.

But after you run `php artisan config:clear`.

You will get data from `.env`.

**Comment by decadence** [comment]
It's intended. You should use env ONLY in config files. I bet even docs say that somewhere.

**Comment by decadence** [comment]
https://laravel.com/docs/5.6/configuration#configuration-caching

**Comment by ThunderBirdsX3** [comment]
@decadence  Ahhh!! Ok got it!
