### ISSUE TITLE
intermittent Laravel 5.6 Ramsey UUIds Exception

### ISSUE THREAD

**Issue by andreladocruz** [laravel/framework#24640]
- Laravel Version: v5.6.24
- PHP Version: 7.2
- Database Driver & Version: Mysql 5.7

### Description:
We receive an intermittent error when using the Str::orderedUuid() method.

Error Message:
Object of class Ramsey\Uuid\Codec\TimestampFirstCombCodec could not be converted to string

We are using the following trait in our models:

```php
namespace App\DMG;

use Illuminate\Support\Str;

trait Uuids
{
    protected static function boot()
    {
        parent::boot();

        static::creating(function ($model) {
            if ($model->{$model->getKeyName()} == '') {
                $model->{$model->getKeyName()} = Str::orderedUuid();
            }
        });
    }
}
```

### Steps To Reproduce:
As its an intermittent error, it's almost impossible to reproduce.

**Comment by andreladocruz** [comment]
### See how intermittent it is 

![captura de tela 2018-06-20 as 14 15 10](https://user-images.githubusercontent.com/3315596/41660584-65ec38d2-7494-11e8-831f-e8aab6c468bf.png)

**Comment by andreladocruz** [comment]
@staudenmeir 

![captura de tela 2018-06-20 as 15 04 46](https://user-images.githubusercontent.com/3315596/41663480-7251040c-749b-11e8-871e-05f5f0d56daa.png)
![captura de tela 2018-06-20 as 15 05 04](https://user-images.githubusercontent.com/3315596/41663481-7282c9ba-749b-11e8-91f6-b96be381b257.png)

**Comment by staudenmeir** [comment]
Do all errors originate in `RolesController::syncUsers()`?

**Comment by andreladocruz** [comment]
Apparently Yes. =) 

This is the code

`private function syncUsers(Role $role, Array $users)
    {
        $this->detachUsers($role);
        foreach ($users as $key => $value){
            User::find($value)->attachRole($role);
        }
    }
`

**Comment by arjasco** [comment]
Maybe try casting your UUID to a string first. I can’t see why it would have the Codec in there unless eloquent is doing some kind of unwrapping of this object under the hood.

‘’’php
$model->param = (string) Str::orderedUuid();
‘’’

**Comment by andreladocruz** [comment]
@arjasco ,

Thanks for the reply. But this won't solve the problem.

Will only mask it. =( 

As I'm using Illuminate\Support\Str class, this should be done internally.

Right?

**Comment by staudenmeir** [comment]
This looks like an issue in your code. The stacktrace shows that `Str::orderedUuid()` returns an `Uuid` object (as it should).

The actual error only occurs because the `INSERT` query fails: The second row has far too many values.

**Comment by andreladocruz** [comment]
@staudenmeir,

Just changed the code to

```php
static::creating(function ($model) {
            if ($model->{$model->getKeyName()} == '') {
                $model->{$model->getKeyName()} = Str::orderedUuid()->toString();
            }
        });
```
