### ISSUE TITLE
Can't lazy-load polymorphic relationships with different primary key columns

### ISSUE THREAD

**Issue by fitztrev** [laravel/framework#24654]
- Laravel Version: 5.6.26
- PHP Version: 7.2.6
- Database Driver & Version: MySQL 5.7.22

### Description:

You cannot lazy-load models of a polymorphic relationship that have different primary key columns.

This functionality broke with #21310.

### Scenario:

```php
$comments = Comment::all();
$comments->load('commentable'); // this fails if you have the below schema
```

#### `posts`

| post_id | title     | body        |
|---------|-----------|-------------|
| 111     | Test Post | hello world |

#### `videos`

| video_id | title      | video        |
|----------|------------|--------------|
| 222      | Test Video | my-video.mov |

#### `comments`

| id | commentable_type | commentable_id | body                 |
|----|------------------|----------------|----------------------|
| 1  | App\Post         | 111            | "comment on a post"  |
| 2  | App\Video        | 222            | "comment on a video" |

```php
// This works (eager loading):
$comments = App\Comment::with('commentable')->get();

// This fails (lazy loading):
$comments = App\Comment::all();
$comments->load('commentable');
// > Results in "no such column: videos.post_id"
```

### Steps To Reproduce:

I created [a failing integration test](https://github.com/laravel/framework/compare/5.6...fitztrev:polymorphic-diff-keys) to demonstrate.

```bash
## Pull down my fork
git clone -b polymorphic-diff-keys git@github.com:fitztrev/framework.git polymorphic-diff-keys

cd polymorphic-diff-keys
composer install

## Run the tests
## These 2 work
./vendor/bin/phpunit --filter testWithNoEagerOrLazyLoad
./vendor/bin/phpunit --filter testItCanEagerLoad

## This 1 fails
./vendor/bin/phpunit --filter testItCanLazyLoad
```

**Comment by staudenmeir** [comment]
[#24063](https://github.com/laravel/framework/pull/24063#issuecomment-386805969) has an explanation for this bug.

Currently, the only approach to fixing this is analyzing the backtrace. Since this is rather terrible, we are still looking for better ideas.
