### ISSUE TITLE
Validator ignores Collection kind of arrays

### ISSUE THREAD

**Issue by Kyslik** [laravel/framework#24657]
- Laravel Version: 5.6.26
- PHP Version: 7.1
- Database Driver & Version: n/a

### Description:
Not sure if this is a bug but I burned myself on this:

```php
$data = collect([['a' => 'b'], ['a' => 'c']]);
$validator = Validator::make(['v' => $data->pluck('a')], ['v.*' => 'lets-skip-this']);
dd($validator->passes()); // true
```

Obviously when I use `$data->pluck('a')->toArray()` validator squawks that rule does not exist (which is correct), but it took me some time to realize that **validator ignores collection kind of arrays** - and I have to pass pure arrays to it.

**Comment by laurencei** [comment]
Feel free to submit a PR to the docs to help make it more obvious
