### ISSUE TITLE
ShouldQueue interface works differently in tests

### ISSUE THREAD

**Issue by CraigHarley** [laravel/framework#24653]
- Laravel Version: 				5.6.0
- PHP Version: 					7.2
- Database Driver & Version:	N/A

### Description:
Implementing ShouldQueue on a job can be overridden by `QUEUE_DRIVER=sync` except when in PHPunit.

### Steps To Reproduce:
Job:
```
...
class BigJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;
	public function handle()
    {
        echo "job working";
	}
}
```

Command:
```
class BigQueueCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'bigjob:go';

    /**
     * Handle the command.
     *
     * @return void
     */
    public function handle()
    {
      	echo "before";
      	BigJob ::dispatch();
      	echo "after";
    }
```

Test:
```
    public function testCommand()
    {
        Queue::fake();
        Artisan::call(BigQueueCommand::class);
	}
```

PHPUnit section:
```
...
	<env name="QUEUE_DRIVER" value="sync" force="true"/>
...
```

When executing the job in artisan using the cli, setting `QUEUE_DRIVER=sync` and `QUEUE_DRIVER=database` works as expected. 
But the same is not true when setting using phpunit or `env.testing`.

Using `dd` on `env("QUEUE_DRIVER")` works as expected in all cases and shows the expected value, this looks like a bug to me.

**Comment by sisve** [comment]
> Implementing ShouldQueue on a job can be overridden by QUEUE_DRIVER=sync [...]

This phrase indicates that there's some misunderstanding what is going on. The ShouldQueue interface is still used, and the job is still sent to the queue driver. There's no overriding going on.

Your issue never explains what the problem actually is. You're saying "the same is not true", but it's unclear what happens instead.

You should never use the `env()` helper to debug stuff, the framework isn't using it. Read the `config('queue.default')` setting instead, it will show what's actually used, not what's set in the environment.

**Comment by CraigHarley** [comment]
@sisve thanks for the reply. 

To clarify the issue is that even though the queue driver is set to sync, in unit tests the queue is not sent using the sync driver, and the code (in this case `echo "job working";`) is not being executed.

`dd(config('queue.default'));` returns `"sync"` as expected.

**Comment by sisve** [comment]
You're calling `Queue::fake()` which replaces the current queue driver with a fake one that just collects the dispatched jobs, it doesn't execute them.

If you want to test the BigJob and trigger the handle() method, call it explicitly.

    $job = new BigJob();
    $job->handle();

**Comment by CraigHarley** [comment]
That works, thanks for the help.
