### ISSUE TITLE
title_case helper fails with special characters

### ISSUE THREAD

**Issue by zenichanin** [laravel/framework#24659]
If I try to convert `"this string has (special characters)"`, it converts it to `"This String Has (special Characters)"`. I feel like this helper should ignore special characters since they do not have uppercase equivalents anyways. If there's any special character before a word, it ignores that word.

**Comment by devcircus** [comment]
FWIW, this is the exact behavior of php's "ucwords" function.

**Comment by zenichanin** [comment]
Yea I know.  I think Laravel `title_case` should be a bit smarter than that. Maybe even ignore uppercasing words like as, the, in, with, a, etc... You usually don't want those uppercased even if it is a title string.

**Comment by sisve** [comment]
> [...] You usually don't want those uppercased even if it is a title string.

That presumes that the method is only passed strings with English phrases.
