### ISSUE TITLE
Laravel exception handler doesn't handle the custom exception when thrown from the view composer

### ISSUE THREAD

**Issue by abin12914** [laravel/framework#24658]
- Laravel Version: 5.5.40
- PHP Version: 7.0.30
- Database Driver & Version:

### Description:
In the default exception handler of the application, custom exception is handled to display my custom error view.
```
public function render($request, Exception $exception)
    {
        if($exception instanceof AppCustomException) {
            //custom error page when custom exception is thrown
            return response()->view('errors.app-custom-exception', compact('exception'));
        }

        return parent::render($request, $exception);
    }
```
Laravel [view composer](https://laravel.com/docs/5.5/views#view-composers) is used for passing data to the view component.

```
namespace App\Http\ViewComposers;

use Illuminate\View\View;
use App\Repositories\ProductRepository;
use Exception;
use App\Exceptions\AppCustomException;

class ProductComponentComposer
{
    protected $products;

    /**
     * Create a new product partial composer.
     *
     * @param  ProductRepository  $productRepo
     * @return void
     */
    public function __construct(ProductRepository $productRepo)
    {
        try {
            $this->products = $productRepo->getProducts();
        } catch (Exception $e) {
            throw new AppCustomException("CustomError", 1001);
        }
    }

    /**
     * Bind data to the view.
     *
     * @param  View  $view
     * @return void
     */
    public function compose(View $view)
    {
        $view->with(['productsCombo' => $this->products]);
    }
}
```
### Problem : 
**The `AppCustomException` is not handled properly when thrown from the view composer's `constructor()` or `compose()` method. Laravel's default exception error page is shown instead of my custom error page.**

### Steps To Reproduce:
Create a custom exception class extending `\Exception`
```
<?php

namespace App\Exceptions;

use Exception;

class AppCustomException extends Exception
{
    //
}
```

Handle it in the default laravel exception handler : **App\Exceptions\Handler.php**
```
public function render($request, Exception $exception)
    {
        if($exception instanceof AppCustomException) {
            //return custom error page when custom exception is thrown
            return response()->view('errors.app-custom-exception', compact('exception'));
        }

        return parent::render($request, $exception);
    }
```
Throw the **AppCustomException** from the view composer's `constructor()` or the `compose()` method.

**Comment by mihkelallorg** [comment]
Hi @abin12914. I could not replicate your problem. 

There might be an issue with the custom error view itself, you're trying to display and it might throw an error itself.

I tested your your handler and custom `Exception` class by simply creating a new route which throws the exception. I suggest you do the same so you could make sure the view itself is not causing the problem. If it's not, the issue lies somewhere else.

**Comment by abin12914** [comment]
Hi @mihkelallorg , Thank you for the reply.

I have tested the situation without any 'view' like the following code. And it still not working.
Please not that the **issue is triggering when the exception is thrown from the viewcomposer.** And it perfectly works when thrown from route, controller, etc.

```
public function render($request, Exception $exception)
    {
        if($exception instanceof AppCustomException) {
            dd("If you see this message, then its working ok."); // The execution is not getting in to this level, ie, if condition is not true
        } else {
            dd($exception); // trigger this. (Image of it's output included)
        }

        return parent::render($request, $exception);
    }
```

**Throw the AppCustomException from the view composer's constructor() or the compose() method ** to reproduce the issue.

I think if we throw a custom exception from "Viewcomposer" laravel throw a **ErrorException** over it.
![screenshot from 2018-07-31 08-58-36](https://user-images.githubusercontent.com/28228280/43435971-11f4e1d0-94a0-11e8-9fe0-b35c19116e6d.png)

**Comment by driesvints** [comment]
This works for me in the latest Laravel version. Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
