### ISSUE TITLE
SSL error thrown when using rackspace storage driver

### ISSUE THREAD

**Issue by icheko** [laravel/framework#24660]
- Laravel Version: 5.6.19
- PHP Version: 7.1.17

### Description:

```javascript
Guzzle\Http\Exception\CurlException : [curl] 60: SSL certificate problem: unable to get local issuer certificate [url] https://indentity.api.rackspacecloud.com/v2.0/tokens

at ...CurlMulti.php:338
```
Looks like `league/flysystem-rackspace` depends on `"rackspace/php-opencloud": "~1.16"` and the SSL certs bundled are throwing this error (https://github.com/rackspace/php-opencloud/issues/727). My temporary fix is to override the rackspace driver and include the option to use the system root ca certs (https://gist.github.com/icheko/6c404e80ac509012b8706bfb6111851b).

### Steps To Reproduce:
1. Use rackspace as the storage driver
2. Attempt to save a file
3. Error is thrown

**Comment by laurencei** [comment]
Would that mean the problem is in the `league/flysystem-rackspace` package? Should the ticket go there perhaps?

**Comment by icheko** [comment]
They are not planning on upgrading (https://github.com/thephpleague/flysystem-rackspace/issues/23) and doesn't look like its in active development anymore.
