### ISSUE TITLE
Failing withoutEvents method

### ISSUE THREAD

**Issue by webmake** [laravel/framework#24666]
- Laravel Version: 5.6.26
- PHP Version: 7.1

### Description:
Weird situation, when `withoutEvents` doesn't work with such error:
```
Mockery\Exception: Mockery's configuration currently forbids mocking the method fire as it does not exist on the class or object being mocked
```
I guess this is because of [code](https://github.com/laravel/framework/blob/56a58e0fa3d845bb992d7c64ac9bb6d0c24b745a/src/Illuminate/Foundation/Testing/Concerns/MocksApplicationServices.php#L101):
```
    protected function withoutEvents()
    {
        $mock = Mockery::mock(EventsDispatcherContract::class)->shouldIgnoreMissing();

        $mock->shouldReceive('fire', 'dispatch')->andReturnUsing(function ($called) {
            $this->firedEvents[] = $called;
        });

        $this->app->instance('events', $mock);

        return $this;
    }
```
there is no method named `fire` in https://github.com/laravel/framework/blob/5.6/src/Illuminate/Contracts/Events/Dispatcher.php
but strange that `shouldIgnoreMissing()` is called. I use `"mockery/mockery": "^1.1",`
And library checks `mockingNonExistentMethodsAllowed`, which is false https://github.com/mockery/mockery/blob/master/library/Mockery.php#L770

**Comment by webmake** [comment]
I believe this commit was missed https://github.com/laravel/framework/commit/2dcde6983ffbb4faf1c238544b51831b33c3a857#diff-e5a5d26b52ec02921440ba6e768a5bc9R67
when `fire` changed into `dispatch` but there was no tests for `withoutEvents`

**Comment by tillkruss** [comment]
Can you submit a PR?
