### ISSUE TITLE
Collection tap changes wrong collection

### ISSUE THREAD

**Issue by Fuzzyma** [laravel/framework#24675]
The tap method of Collection seems broken. I only read the source but to me it seems like the callack gets passed a **copy** of the collection but NOT the copy is returned. So basically the callback acts on a Collection which will be GarbageCollected afterwards:

```js
    public function tap(callable $callback)
    {
        $callback(new static($this->items));
        return $this;
    }
```

[Source](https://github.com/laravel/framework/blob/56a58e0fa3d845bb992d7c64ac9bb6d0c24b745a/src/Illuminate/Support/Collection.php#L1499-L1504)

**Comment by staudenmeir** [comment]
The original PR explains it: #17756

**Comment by JosephSilber** [comment]
@staudenmeir and the original PR [is wrong](https://github.com/laravel/framework/pull/17756#issuecomment-698711718) :cry:

**Comment by Fuzzyma** [comment]
I KNEW it!!! :D
