### ISSUE TITLE
TestResponse::assertJsonFragment doesn't match if the keys are in a different order

### ISSUE THREAD

**Issue by robertmain** [laravel/framework#24674]
- Laravel Version: 5.6.*
- PHP Version: 7.1.9
- Database Driver & Version: n/a

### Description:
[`TestResponse::assertJsonFragment`](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Foundation/Testing/TestResponse.php#L462-L481) performs a string comparison on the arrays provided, rather than actually diffing the arrays. This means that They won't match if the keys are in a different order

### Steps To Reproduce:
Have your API return the following:

```json
{
	"data": {
		"id": 35,
		"name": "The 10 of Diamonds",
		"suit": {
			"id": 3,
			"name": "Diamonds",
			"created_at": "2018-06-23 21:50:19",
			"updated_at": "2018-06-23 21:50:19"
		},
		"created_at": {
			"date": "2018-06-23 21:50:19.000000",
			"timezone_type": 3,
			"timezone": "UTC"
		},
		"updated_at": {
			"date": "2018-06-23 21:50:19.000000",
			"timezone_type": 3,
			"timezone": "UTC"
		}
	}
}
```

The following test will fail:

```php
public function returns_a_single_card()
{
    $response = $this->get('/api/card/random?suit=2');

    $response->assertStatus(Response::HTTP_OK);
    $response->assertJsonFragment([
        'suit' => [
            'id' => 2
        ]
    ]);
}
```

However, the following test will pass:

```php
public function returns_a_single_card()
{
    $response = $this->get('/api/card/random?suit=2');

    $response->assertStatus(Response::HTTP_OK);
    $response->assertJsonFragment([
        'name' => 'Spades'
    ]);
}
```

The reason being, that `assertJsonFragment` seems to look for that exact JSON string. It then finds a timestamp first under the `suit` object and then fails the test. This can be seen in the message I get from phpunit:
![image](https://user-images.githubusercontent.com/537684/41814133-bd8999c4-7712-11e8-975e-2eb40314affb.png)

**Comment by driesvints** [comment]
Heya. This is the correct behavior of this method. This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.
