### ISSUE TITLE
Eloquent : two different response for a same like query

### ISSUE THREAD

**Issue by vinaykevadia** [laravel/framework#24679]
- Laravel Version: 5.5.4
- PHP Version: v7
- Database Driver & Version: mysql

### Description:
Have some error in eloquent, so it is giving two different response for a same like query. as it is shown in image below. 
### Steps To Reproduce:
![laravel_error](https://user-images.githubusercontent.com/7442679/41856798-9912ff66-78b3-11e8-98ce-3cb9c65719f3.png)

**Comment by staudenmeir** [comment]
How are these queries the same? The first has a `WHERE` clause, the second one doesn't.

**Comment by FatBoyXPC** [comment]
In the 2nd screenshot, change `$_profile = $profile->with('doctor')->get()` to just `$_profile->load('doctor')` (notice no `get()` and it's not getting reassigned). Take a look at the [Eager Loading] documentation. You actually started a new query when you did `with()->get()`.

[Eager Loading]: https://laravel.com/docs/5.6/eloquent-relationships#eager-loading

**Comment by vinaykevadia** [comment]
@staudenmeir , both are the same because rest of the query applied on profile model instance acquired by ID.

**Comment by vinaykevadia** [comment]
@FatBoyXPC , thank you so much for your reply.  its working.

**Comment by FatBoyXPC** [comment]
@vinaykevadia just to clear things up, the queries aren't the same. `_profile->with('doctor')->get()` is directly equivalent to `Profile::with('doctor')->get()`, which would get all Profile records. The reason for this is how Eloquent handles the Query Builder methods through `__call()`. It's not exactly intuitive, but just know that `with()` and `load()` are to be used differently, and in general, you won't want to call query methods on an instance of a model.

**Comment by vinaykevadia** [comment]
@FatBoyXPC , got it, thanks for your clarifications.
