### ISSUE TITLE
MemcacheD entries not readable after saving.

### ISSUE THREAD

**Issue by pursehouse** [laravel/framework#24671]
- Laravel Version: v5.6.25
- PHP Version: PHP 7.2.1-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jan  5 2018 13:54:13) ( NTS )
- Database Driver & Version: memcached 1.4.4-14-g9c660c0

### Description:
When laravel tries to `get` a memcache entry, it does not get the saved value and the entry vanishes from memcache. But it works fine with plain-old-php.

### Steps To Reproduce:

.env:
```
CACHE_DRIVER=memcached
```
No other config values for memcache. The rest is the defaults, which are not filled out.

```php
        'memcached' => [
            'driver' => 'memcached',
            'persistent_id' => env('MEMCACHED_PERSISTENT_ID'),
            'sasl' => [
                env('MEMCACHED_USERNAME'),
                env('MEMCACHED_PASSWORD'),
            ],
            'options' => [
                // Memcached::OPT_CONNECT_TIMEOUT  => 2000,
            ],
            'servers' => [
                [
                    'host' => env('MEMCACHED_HOST', '127.0.0.1'),
                    'port' => env('MEMCACHED_PORT', 11211),
                    'weight' => 100,
                ],
            ],
        ],
```

```php
$memcached = new \Memcached();
$memcached->addServer( '127.0.0.1', 11211, 100 );
$memcached->set( "pop_test", "pop test data", 100 );
$d[] = $memcached->get( "pop_test" );
\Cache::store( 'memcached' )->put( "laravel_test", "laravel test data", 100 );
$d[] = $memcached->getAllKeys();
$d[] = \Cache::store( 'memcached' )->get( "laravel_test", "laravel test default" );
$d[] = $memcached->getAllKeys();
dd( $d );
```

outputs...

```
array:4 [
  0 => "pop test data"
  1 => array:2 [
    0 => "pop_test"
    1 => "app_cache:laravel_test"
  ]
  2 => "laravel test default"
  3 => array:1 [
    0 => "pop_test"
  ]
]
```

I also tried the `remember` method, and it also never considered a cache entry valid, even with...

```php
$res = \Cache
    ::store( 'memcached' )
    ->remember(
        "test_exchange",
        60 * 24,
        function() {
            echo 'uncached :'.__CLASS__." : ".__LINE__."\n";
            return "test";
        }
    );
```

it echos every time

**Comment by driesvints** [comment]
I'm not really sure what's going on really. I also get different results but caching itself works fine for me. Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
