### ISSUE TITLE
Field value in table database and value function conflict

### ISSUE THREAD

**Issue by pscom** [laravel/framework#24688]
- Laravel Version: 5.6
- PHP Version: 7.2
- Database Driver & Version: MySQL

### Description:
If you have in your table in databasse field with name 'value' and will use this table with Eloqument Model then it reports error like that:

> Too few arguments to function Illuminate\Database\Eloquent\Builder::value(), 0 passed in .../system/vendor/illuminate/database/Eloquent/Model.php on line 1455 and exactly 1 expected

In my mind it's call function name 'value' from Builder but we want get 'value' field from database and we have conflict.

**Comment by haakym** [comment]
What does your migration and model look like? What causes the error to occur? Is it when you are trying to read the `value` attribute, i.e. $model->value?

**Comment by sisve** [comment]
Have you tried `$model->getAttribute('value')`?
