### ISSUE TITLE
"Saving" event listener does not trigger when a model is updated through a relationship

### ISSUE THREAD

**Issue by LiamBull** [laravel/framework#24685]
- Laravel Version: 5.6.26
- PHP Version: 7.2.5
- Database Driver & Version: MySQL, 

### Description:

When trying to use the "saving" event listener in a service provider, it is not called if the model in question is updated through a relationship.

The below code will trigger the event:

    $business = Business::whereUserId($user->id)->first();

    $business->update(\request()->intersectByKeys(Business::getFillableAttributes()));

However, the below code will not:

    $user = Auth::user();

    $user->business()->update(\request()->intersectByKeys(Business::getFillableAttributes()));

I have not tested this with other event listeners, but I would presume it is the same.

### Steps To Reproduce:

Try using the "saving" event listener in the way specified in the description.

**Comment by arjasco** [comment]
In this case update is calling the underlying query builder. In order for events to be fired this needs to happen on the model instance.

**Comment by devcircus** [comment]
Yeah Eloquent events are fired from Eloquent. Don't expect query builders or collections, etc. To fire Eloquent events.

**Comment by LiamBull** [comment]
Ah okay, so this is expected behaviour? It was a bit confusing to encounter, but I understand now. Thank you both.
