### ISSUE TITLE
Remember Me is not working forever

### ISSUE THREAD

**Issue by iwasherefirst2** [laravel/framework#24697]
- Laravel Version: v5.5.34
- PHP Version: 7.2
- Database Driver & Version: MySQL 5.7.18

### Description:
When I login with "Remember me" clicked, then I would expect that I am logged in forever on this computer until I log out. However, when I login and logout on another computer, then the remember me button is not working anymore at the first computer. 

### Steps To Reproduce:
Step 1)
On a fresh install, create authentication with `php artisan make:auth` and make sure you have a "remember me" checkbox and make it work as explained it https://laravel.com/docs/5.6/authentication#remembering-users 
Publish website online
Step 2)
Login using the "Remember me" function on some computer A. If you close browser and reopen it then you should be still logged in.
Step 3)
Login and logout on the same website, with the same user, but from a different computer B
Step 4)
Go back to computer A. If your browser is still open, then your still logged in. If you close and reopen browser, then you are not logged in anymore!

**Comment by tillkruss** [comment]
That must be a configuration issue. It's working out of the box for me.

**Comment by dionmes** [comment]
The issue is that Laravel supports only 1 rememberme login per user. So if you login on your desktop and than login on your phone, the remember me token does not correspond anymore. This is a serious issue.
