### ISSUE TITLE
Out memory when creating or updating b"string"

### ISSUE THREAD

**Issue by Aderemi** [laravel/framework#24698]
- Laravel Version: 5.3.31
- PHP Version: 7.0.9
- Database Driver & Version: Jesenger/MongoDB 3.0 and above

### Description:
Creating and updating of any record with a binary string will result in out of memory
_Allowed memory size of ######### bytes exhausted (tried to allocate ********** bytes)_
The misery there is that ######### is always greater than **********
### Steps To Reproduce:
Include special character like "°ó" in any string field

**Comment by sisve** [comment]
Do you have a stack trace for this?
