### ISSUE TITLE
Sqlite json support failed after upgrade to laravel 5.6.26

### ISSUE THREAD

**Issue by gdpa** [laravel/framework#24694]
- Laravel Version: 5.6.26
- PHP Version: 7.1.18
- Database Driver & Version: Mysql5.7 / sqlite3

### Description:
I just upgraded from 5.6.23 to 5.6.26 and some functionalities which work with json fields throw error on tests. On mysql all tests pass but with sqlite database i get this error:

> This database engine does not support JSON operations

> /vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php:930)

### Steps To Reproduce:
Use a json field on migration
try to fill it on controller 
test it

**Comment by staudenmeir** [comment]
Please post the controller code where you fill the JSON field.
