### ISSUE TITLE
It's hard to use db testing functionality with postgresql

### ISSUE THREAD

**Issue by codercms** [laravel/framework#24704]
- Laravel Version: 5.6.16
- PHP Version: 7.2.3
- Database Driver & Version: pgsql

### Description:
It's frequent case when testing projects to use RefreshDatabase trait (https://laravel.com/docs/5.6/database-testing#resetting-the-database-after-each-test).
But it doesn't quite work as it should.

```php
    /**
     * Refresh a conventional test database.
     *
     * @return void
     */
    protected function refreshTestDatabase()
    {
        if (! RefreshDatabaseState::$migrated) {
            $this->artisan('migrate:fresh');

            $this->app[Kernel::class]->setArtisan(null);

            RefreshDatabaseState::$migrated = true;
        }

        $this->beginDatabaseTransaction();
    }
```
Link: https://github.com/laravel/framework/blob/5.6/src/Illuminate/Foundation/Testing/RefreshDatabase.php#L53

Now look what "migrate:fresh" command actually does: https://github.com/laravel/framework/blob/5.6/src/Illuminate/Database/Console/Migrations/FreshCommand.php#L46

It can drop all tables and views from the database schema. But PostgreSQL database has a little bit more objects in the schema, like TYPE. https://www.postgresql.org/docs/10/static/sql-createtype.html

So, when "migrate:fresh" has dropped all tables (and optionally views) from the schema, the TYPEs still persist.
When you run a test more than once you will get following error:
```
Illuminate\Database\QueryException : SQLSTATE[42710]: Duplicate object: 7 ERROR:  type "example_type" already exists (SQL: CREATE TYPE example_type AS ENUM ('file', 'image', 'text');)
```

### Steps To Reproduce:
Just create a migration with this line in the"up" method:
```
DB::unprepared("CREATE TYPE example_type AS ENUM ('file', 'image', 'text');");
```

**Comment by staudenmeir** [comment]
You could override `refreshTestDatabase()` in your `TestCase` to add this functionality.

Of course, you are also welcome to submit a pull request.
