### ISSUE TITLE
[Proposal] Ability to register a transformation callback to Eloquent relationships

### ISSUE THREAD

**Issue by esbenp** [laravel/framework#24702]
Sometimes it would be awesome to be able to transform related resources. E.g.

```
public function relatedResources()
{
   return $this->hasMany(RelatedClass::class)->registerTransformationCallback(function ($resources) {
    return $resources->map(function ($resource){
       $resource->something = 'yo';
       return $resource;
    });
  });
}
``` 

One use case, besides adding fields that are not in the DB, could be to filter the resource based on attributes that are not known at db read time. This is beneficial when dealing with multiple foreign keys.

```
public function relatedResources()
{
  return $this->hasMany(RelatedClass::class)->registerTransformationCallback(function ($resources) {
    return $resources->filter(function ($resource) {
       return $resource->someProperty === $this->attributes['somethingElse'];
    });
  });
}
```

Since `somethingElse` is not known before the model is loaded we cannot use a normal `where` clause on the relationship. This is a way to fix that.

If this feature has any interest I am very open for further discussion on edge cases, additional features like caching of transformation result, etc. Also open to collaborate on a PR.

**Comment by hvlucas** [comment]
You technically could do this using [accessors](https://laravel.com/docs/5.6/eloquent-mutators#defining-an-accessor)
```php
public function relationship(){
  return $this->hasMany(Relationship::class);
}

public function getModifiedRelationshipAttribute(){
    return $this->relationship->map(function($relation){
       $relation->attribute = 'New Value';
       return $relation;
    });
}

public function getFilteredRelationshipAttribute(){
    return $this->relationship->filter(function($relation){
      return $relation->attribute === 'value';
    });
}
```
Then just call the accessors:
```php
$model->modified_relationship;
$model->filtered_relationship;
```

**Comment by tillkruss** [comment]
Please use the internals or ideas repo.
