### ISSUE TITLE
Update the Docs for Translations and Deferred Providers

### ISSUE THREAD

**Issue by coogle** [laravel/framework#24706]
- Laravel Version: 5.6.x
- PHP Version: N/A
- Database Driver & Version: N/A

### Description:

The documentation for the Translation stuff needs to be updated a bit to prevent the mistake I just made. The documentation implies, correctly, that a good place to load translations when working with packages is in a Service Provider. However, what it fails to mention is that unlike other things translations will _not_ load if the provider has deferred loading enabled. This should be noted, as it is certain to cause a lot of unnecessary head-banging.

**Comment by tillkruss** [comment]
Please submit a PR.
