### ISSUE TITLE
invalid input syntax for type uuid

### ISSUE THREAD

**Issue by whendytakashy** [laravel/framework#24703]
Hi, I have searched everywhere but did not meet. I got into trouble with uuid 
```
auth()->user() / Auth::user()
```
The problem is as below:

```
SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for type uuid: "970" (SQL: select * from "users" where "id" = 970 limit 1)
```
where id should be string. In my model user like this.

```
protected $table = 'users';
protected $primaryKey = 'id';
public $incrementing = false;
protected $keyType = 'string'
```
and I've also tried to add

```
protected $casts = [
        'id' => 'string'
    ];
```

but still the same result. Please help.
Thank you

- Laravel Version: 5.6.*
- PHP Version: 7.2
- Database Driver & Version: postgresql

**Comment by sisve** [comment]
Well, you have a session that states that you're user "970". Did you recently change from integers to uuid? Does this session cookie come from another application you're developing on the same domain (usually localhost)?

**Comment by whendytakashy** [comment]
@sisve thank for response. yes i`m change from integer to uuid. session cookie not from other application. I search any same problem but I not found it working for me.

**Comment by emanuti** [comment]
I'm using emadadly/laravel-uuid and got the same error. After expending some time restarting server through php artisan serve, after change many things on my project and noting that the error won't stopped, I deleted the session cache file inside storage/framework/sessions and then all back to work.

**Comment by dwikyls** [comment]
protected $primaryKey = 'id';
protected $keyType = 'string';

https://laravel.com/docs/9.x/eloquent#primary-keys

**Comment by syamlal-s** [comment]
I had same problem. @dwikyls answer helped me.

I added these lines to my User model

protected $primaryKey = 'id';
protected $keyType = 'string';
