### ISSUE TITLE
Sorting paginated results when using withCount including contraints

### ISSUE THREAD

**Issue by matbeard** [laravel/framework#24701]
- Laravel Version: 5.6
- PHP Version: 7.1.7
- Database Driver & Version: mssql

### Description:
When using `orderBy` in conjunction with `paginate` and `withCount` the ordering is not correct if `withCount` includes contraints.

### Steps To Reproduce:
Perform an Eloquent query including `orderBy`, `paginate` and a `withCount` on a `hasMany` or `belongsToMany` relationship.

Check the first few pages of results... the sorting should be okay.

Now add any constraint to the `withCount` and check the sorting again. It's not in the correct order beyond the first page.

**Comment by staudenmeir** [comment]
What's your exact Laravel version (`5.6.x`)?

**Comment by matbeard** [comment]
Version is 5.6.24

**Comment by staudenmeir** [comment]
Please post the whole query.

**Comment by matbeard** [comment]
For example:
In Employee model:
````
public function expiredQualifications()
{
    return $this->belongsToMany(\App\Models\Qualification::class)->withPivot('id', 'awarded_at', 'expires_at')->wherePivot('expires_at', '<', Carbon::now());
}

public function qualifications()
{
    return $this->belongsToMany(\App\Models\Qualification::class)->withPivot('id', 'awarded_at', 'expires_at');
}
````

in EmployeeController (obviously only using one of the three example queries):
````
public function index()
{
    $employees = Employee::withCount('expiredQualifications')->orderBy('name', 'asc')->paginate(30);
    // sorting is screwed after first page

    $employees = Employee::withCount(['qualifications' => function ($query) {
        $query->where('expired_at', '<', Carbon::now());
    }])->orderBy('name', 'asc')->paginate(30);
    // sorting is screwed after first page

    $employees = Employee::withCount('qualifications')->orderBy('name', 'asc')->paginate(30);
    // sorting is okay after first page

    return $employees;
}
````

**Comment by staudenmeir** [comment]
I can't reproduce that. How exactly is the sorting incorrect? Did you check the executed queries?

**Comment by matbeard** [comment]
Hi,

Here are the relevant executed queries for the first and second pages of results:
First page. Records 1 - 30:
````
select top 30 [employees].*, (select count(*) from [qualifications] inner join [employee_qualifications] on [qualification].[id] = [employee_ qualifications].[qualification_id] where [employees].[id] = [employee_qualifications].[employee_id] and [expires_at] < '2018-08-03') as [qualifications_count] from [employees] where [employees].[deleted_at] is null order by full_name asc
````

Second page. Records 31 - 60:
````
select * from (select [employees].*, (select count(*) from [qualifications] inner join [employee_qualifications] on [qualification].[id] = [employee_ qualifications].[qualification_id] where [employees].[id] = [employee_qualifications].[employee_id] and [expires_at] < '2018-08-03') as [qualifications_count], row_number() over (order by full_name asc) as row_num from [employees] where [employees].[deleted_at] is null) as temp_table where row_num between 31 and 60
````

The sort order of the second page of results is incorrect. For example, there are names beginning with 'B' after names beginning with 'C' and 'D'.

Sample data would be tricky, but hopefully the above queries will shed some light. I'm not a complete SQL novice, but I don't understand that second query.

**Comment by matbeard** [comment]
Yup. I've tried that and yes, I get the same weird sort order in SQL Management Studio. It seems to be an SQL Server bug. If I simply remove the `and [expires_at] < '2018-08-03'` from the sub-query in Management Studio, the sorting is correct.

I guess it's over to the SQL Server forums to follow up on this.

**Comment by staudenmeir** [comment]
Very strange, that part shouldn't have any influence on the sorting. Can you post a screenshot?

**Comment by matbeard** [comment]
Here are a couple of screenshots from SSMS. 

It's employee data, so most is hidden, but you can see from the row_num column the sorting is incorrect:
![incorrect](https://user-images.githubusercontent.com/1549469/42279944-3efee07c-7f97-11e8-8a8e-608f02175018.png)

Here's after removing the date clause from the sub-query:
![correct](https://user-images.githubusercontent.com/1549469/42280235-0f193ae6-7f98-11e8-950c-38ea1707d73e.png)

**Comment by matbeard** [comment]
I posted a question on MSDN regarding this and got a really quick response: 
https://social.msdn.microsoft.com/Forums/en-US/e5dda657-6ad1-44d0-856e-4d535b4df553/rownumber-over-order-by-incorrect-sorting?forum=transactsql
"Please note that the use of ORDER BY inside ROW_NUMBER is only for generating the row number value sequence. It doesn't affect the way the overall resultset is ordered and returned"

If this is the case, why does Laravel/Query Builder use this technique when paginating/sorting?

I'm confused!

**Comment by staudenmeir** [comment]
Looks like the outer query requires an explicit sorting. Does this work?

    where row_num between 31 and 60 order by full_name asc

**Comment by matbeard** [comment]
Yes, that works. As does `order by row_num asc`

But how can I get Laravel to include that in the queries it generates?

**Comment by matbeard** [comment]
Thanks. In the meantime, I've changed line 177 of SqlServerGrammar.php:
`return "between {$start} and {$finish}";`
becomes
` return "between {$start} and {$finish} order by row_num asc";`

That seems to do the trick until your PR is merged.
