### ISSUE TITLE
Hard time debugging jobs

### ISSUE THREAD

**Issue by ravenberg** [laravel/framework#24713]
I am having a really hard time debugging jobs. I was working on a job today and after spending hours I discovered that this was due to something silly where usually I would have found an exception.

The particular case I am referring to is documented in [this stackoverflow thread](https://stackoverflow.com/questions/51122008/getting-no-response-after-sending-a-guzzle-http-request-from-within-a-job/51123397#51123397).

However I decided to make this issue to point out that the developer experience is terrible in comparison to the other parts of the framework. I think this could be improved by allowing to have the worker print exception or error messages under an increased verbosity setting `-vvv`.

**Comment by tiagoacardoso** [comment]
Hi @ravenberg, I also had a hard time trying to debug jobs too, some months ago. All I did was use debug messages everywhere to find the problem :)

**Comment by patrickbrouwers** [comment]
Making a statement like `developer experience is terrible` won't really encourage the maintainer to do something about it. Suggestions and constructive criticism are more valuable. 

Increased verbosity would be nice.
For me the job exceptions end up in the log, don't you have any log entries there? 
I often use the `sync` driver locally to debug it more easily. Also using xdebug in a job is possible.

You could also implement the `failed()` method in the Job and do some stuff there.

```
/**
     * The job failed to process.
     *
     * @param  Exception  $exception
     * @return void
     */
    public function failed(Exception $exception)
    {
        // Send user notification of failure, etc...
    }
```
