### ISSUE TITLE
json where on sqlite throws error: This database engine does not support JSON operations

### ISSUE THREAD

**Issue by gdpa** [laravel/framework#24715]
- Laravel Version: 5.6.26
- PHP Version: 7.2
- Database Driver & Version: sqlite 3

### Description:
After upgrading from 5.6.23 to 5.6.26 json where queries for sqlite throw error:

> This database engine does not support JSON operations

### Steps To Reproduce:
Add a notification class for user to notify another user want to be friend and use sqlite database driver for saving notification with friend object.
Try to markAsRead notification on accept friend request:
`auth()->user->notifications()->where('type', 'App\Notifications\FriendshipRequestNotification')->where('data->user->id', $friend->id)->get();`

**Comment by staudenmeir** [comment]
I don't see how this query could have worked before. Laravel has never supported JSON queries on SQLite.

**Comment by MannikJ** [comment]
We just updated from v5.6.14 to v5.6.34 and although it seems a little strange, I can only confirm that some tests where json columns are involved could be executed successfully before, but now fail in the same way as described above. 
You might be correct that it should'nt have worked before either, but I don't think it's coincidence that the upgrade makes it behave differently than before.

**Comment by staudenmeir** [comment]
Can you post an example?

**Comment by staudenmeir** [comment]
I'll look into it. What `laravel-tags` feature are you using?

Also, I would love to know how you managed to run SQLite with JSON support.

**Comment by staudenmeir** [comment]
The behavior has changed in 5.6.25. Before that, the query used the unmodified column selector:

```php
DB::table('test')->where('foo->bar', 'baz')->get();
// select * from "test" where "foo->bar" = 'baz'
```

This couldn't have worked, it looks for a column named `foo->bar`.

But it also didn't throw an exception because SQLite silently ignores non-existing columns.
Does this explain your issues?

**Comment by MannikJ** [comment]
That makes perfect sense. I already guessed it's something like that. That's why I wrote 'where json columns are involved'. The tests are not very extensive so it might looked like it was working as long as it didn't fail.

**Comment by MannikJ** [comment]
@staudenmeir Thank you very much for your PR. We just installed v3.6.35 and the problems are solved. I'm also glad that is properly implemented so we can use those json queries with sqlite in the future.
