### ISSUE TITLE
Service provider order and package auto discovery

### ISSUE THREAD

**Issue by eberkund** [laravel/framework#24719]
I have an issue where I would like my package to get loaded after the rest of the Laravel application service providers however using auto-discovery it gets loaded first. I looked at the code that handles this and there isn't any way to change this besides digging deep into things and overriding core files.

I think there should be support for ordering service providers loaded through auto-discovery.

The "laravel-modules" package does this by adding an additional config value "order". See: https://github.com/AsgardCms/Platform/blob/3.0/Modules/Core/module.json

**Comment by mfn** [comment]
But where in your package would you define this "order"?

How could it work with other packages / competing orders?

**Comment by eberkund** [comment]
It could be in `composer.json` with a weight value and lower weights would get loaded first or something like that

**Comment by mfn** [comment]
This isn't a bug, please move it over to https://github.com/laravel/ideas/issues

> Please use this issue tracker only for reporting Laravel bugs.
