### ISSUE TITLE
Unable to Create laravel project 

### ISSUE THREAD

**Issue by VikasSuthar007** [laravel/framework#24712]
![issue](https://user-images.githubusercontent.com/32486683/42134037-67787fa6-7d51-11e8-9552-cb374ecb3c8f.PNG)

can anyone help me with this?

**Comment by mhenselin** [comment]
since the yellow line ist stating an error about ssl 
and
I just tested that the shown composer command worked fine
and
version 5.2.29 is definitely outdated

we should close this issue
