### ISSUE TITLE
On-demand Notifications addressed to multiple recipients are broken after PR #24606 

### ISSUE THREAD

**Issue by pmatseykanets** [laravel/framework#24729]
- Laravel Version: 5.6.26
- PHP Version: 7.2
- Database Driver & Version: irrelevant to this issue

### Description:

PR #24606 unfortunately broke on-demand notifications addressed to multiple recipients.

Up until this PR the following worked just fine 

```php
Notification::route('mail', ['user1@example.com', 'user2@example.com'])
    ->notify(new InvoicePaid($invoice));
```

After this PR the notification is being sent only to the last recipient - `user2@example.com`.

https://github.com/laravel/framework/blob/9c684dcabe2002ccf8890494de18031c155240b0/src/Illuminate/Notifications/Channels/MailChannel.php#L181

is returning only the last item in the array because it's being overwritten here

https://github.com/laravel/framework/blob/9c684dcabe2002ccf8890494de18031c155240b0/src/Illuminate/Notifications/Channels/MailChannel.php#L190

### Steps To Reproduce:

- Issue an on-demand notification addressed to multiple users as in the example above
- See in the log driver or by other means (MailHog etc) that it has been sent only to the last recipient

**Comment by laurencei** [comment]
Closing as PR with fix was merged
