### ISSUE TITLE
[5.6] [Blade] Error using @json Blade helper

### ISSUE THREAD

**Issue by eusonlito** [laravel/framework#24734]
- Laravel Version: 5.6.26
- PHP Version: 7.2.7
- Database Driver & Version: -

### Description:

`@json` blade helper breaks json on template:

### Steps To Reproduce:

It works:

```
<canvas data-chart-datasets="{{ json_encode([
    [
        'label' => 'Value',
        'data' => $list->pluck('sum')->toJson()
    ],
    [
        'label' => 'Quantity',
        'data' => $list->pluck('count')->toJson()
    ]
]) }}"></canvas>
```

It works:

```
<canvas data-chart-datasets="@json([
    [
        'label' => 'Value',
        'data' => $list->pluck('sum')->toJson()
    ],
    [
        'label' => 'Quantity'
    ]
])"></canvas>
```

Generated compiled view:

```
<canvas data-chart-datasets="<?php echo json_encode([
    [
        'label' => 'Value', 'data' => $list->pluck('sum')->toJson()
    ], [
        'label' => 'Quantity'
    ]
]) ?>"></canvas>
```

It fails:

```
<canvas data-chart-datasets="@json([
    [
        'label' => 'Value',
        'data' => $list->pluck('sum')->toJson()
    ],
    [
        'label' => 'Quantity',
        'data' => $list->pluck('count')->toJson()
    ]
])"></canvas>
```

Generated compiled view:

```
<canvas data-chart-datasets="<?php echo json_encode([
    [
        'label' => 'Value', 'data' => $list->pluck('sum')->toJson()
    ], [
        'label' => 'Quantity') ?>"></canvas>
```

Regards!

**Comment by devcircus** [comment]
This [comment](https://github.com/laravel/framework/pull/23655#issuecomment-375353098) on PR #23655, may be relevant.

**Comment by eusonlito** [comment]
@devcircus these comment is about to parse json_encode additional parameters.

I think that if `@json` helper method can only parse some PHP code, should be on docs https://laravel.com/docs/5.6/blade

Thanks anyway.

**Comment by daison12006013** [comment]
Care to update update the `@json` regex? That's quite complicated.

If you will check the sample from the docs itself, it is simply a variable passed in, but if you will build your own array inside the json directive, the you should just use raw json in the first place or pass in the array before under the directive.

```
@php
$arr = [
    [
        'label' => 'Value',
        'data' => $list->pluck('sum')->toJson()
    ],
    [
        'label' => 'Quantity',
        'data' => $list->pluck('count')->toJson()
    ]
];
@endphp

<canvas data-chart-datasets="@json($arr)"></canvas>
```

**Comment by tillkruss** [comment]
Move your data construction into your controller or responses.

**Comment by eusonlito** [comment]
@tillkruss I'm actually doing. I only was reporting a bug.

Thanks anyway.

**Comment by devcircus** [comment]
Based on the link I posted earlier and many other discussions over the past several years, regarding other blade helpers, this is a known limitation of blade. Fortunately there's a simple workaround.

**Comment by eusonlito** [comment]
Yes @devcircus, it's not a problem about the blade helpers limitations.

It's only a comment about if should be documented on docs to avoid to use complex code on it.

![untitled](https://user-images.githubusercontent.com/644551/42308873-469bb68e-8037-11e8-9f16-06b6bc94ee43.png)

Anyway, closed case :P

**Comment by devcircus** [comment]
In that case, the docs are open source as well. I'll see about sending a PR, or if you know how you'd like to word it, go ahead and send one.

**Comment by adam1010** [comment]
Since this bug won't get fixed anytime soon, the workaround for those interested is to overwrite the `@json` blade directive. Here is a quick implementation you can put in your AppServiceProvider if you plan to use the same `json_encode()` arguments globally:

```
Blade::directive('json', function($expression){
  return "<?php echo json_encode($expression, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT) ?>";
});
```

**Comment by eslym** [comment]
Here is an alternative fix:
In helpers:
````php
<?php
function split_arguments($expression){
    $tokens = token_get_all("<?php $expression");
    array_shift($tokens);
    $arguments = [''];
    $p = [
        '()' => 0,
        '[]' => 0,
        '{}' => 0,
        '``' => 0,
    ];
    foreach ($tokens as $token){
        switch ($token){
            case '(':
                $p['()']++;
                break;
            case ')':
                $p['()']--;
                break;
            case '[':
                $p['[]']++;
                break;
            case ']':
                $p['[]']--;
                break;
            case '{':
                $p['{}']++;
                break;
            case '}':
                $p['{}']--;
                break;
            case '`':
                $p['``'] = !$p['``'];
                break;
            case ',':
                if(!array_sum($p)){
                    array_unshift($arguments, '');
                    $token = '';
                }
                break;
        }
        if(is_string($token)){
            $arguments[0] .= $token;
        } else {
            $arguments[0] .= $token[1];
        }
    }
    return array_reverse($arguments);
}
````
In service provider:
````php
<?php
Blade::directive('json', function ($expression){
    $args = split_arguments($expression);
    if(count($args) < 2){
        $args[]= '15';
    }
    if (count($args) < 3){
        $args[]= '512';
    }
    return "<?php echo json_encode($args[0], $args[1], $args[2]) ;?>";
});
````
Result:
````
Psy Shell v0.9.9 (PHP 7.1.23 — cli) by Justin Hileman
>>> Blade::compileString('@json([1, 2, 3, 4, 5])');
=> "<?php echo json_encode([1, 2, 3, 4, 5], 15, 512) ;?>"
````
