### ISSUE TITLE
BelongsToMany does not use a method similar to qualifyColumn found in Model to resolve related key

### ISSUE THREAD

**Issue by transistive** [laravel/framework#24733]
- Laravel Version: 5.6.26
- PHP Version: 7.2.6
- Database Driver & Version: 

### Description:

The BelongsToMany class does not use the a method comparable to qualifyColumn found in Model. This means that keys added through the belongsToMany method defined in Model can not be qualified.
This becomes a problem when you are aliasing tables. For example if I alias them with an 'x', I cannot use the resulting joined table simply by using `$this->belongsToMany(Foo::class, 'x.bar')` as this resolves to `JOIN ON foo.x.bar`.

### Steps To Reproduce:

define a relationship in a Model in this format:

`$this->belongsToMany(Foo::class)->from(function ($query) {`
`     // some internal logic`
`}, 'x');`

### Closing remark

If this is truly a bug i am willing to file a pull request but I don't feel I am qualified  enough to do this.
I believe the problem can relatively easily be solved by changing line 182 to 184 in BelongsToMany::performJoin to
`if (!Str::contains($this->relatedKey, '.')) {`
    `$baseTable = $this->related->getTable();`
    `$key = $baseTable.'.'.$this->relatedKey;`
`} else`
     `$key = $this->relatedKey;`

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not for ideas, suggestions etc. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. You are able to open a ticket at https://github.com/laravel/ideas

Alternatively you are able to open a PR using the Contributions guidelines: https://laravel.com/docs/5.7/contributions#which-branch

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
