### ISSUE TITLE
Composer update issues

### ISSUE THREAD

**Issue by nageshdudam** [laravel/framework#24744]
while updating i got the below error please check
using => laravel 5.5
Package phpoffice/phpexcel is abandoned, you should avoid using it. Use phpoffice/phpspreadsheet instead.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In ProviderRepository.php line 208:
                                                    
  Class 'Carbon\Laravel\ServiceProvider' not found  
                                                    

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

**Comment by jmarcher** [comment]
Please visit a Forum like Laracasts in order to solve such issues.
