### ISSUE TITLE
where('column_name', ['array', 'of', 'values'])` does not behave as expected

### ISSUE THREAD

**Issue by hailwood** [laravel/framework#24742]
- Laravel Version: 5.5.40
- PHP Version: 7.2.6
- Database Driver & Version: mysql 5.6

### Description:
As mentioned in the title, the below code does not behave as expected.
```php
->where('column_name', ['array', 'of', 'values'])
```

This appears to silently grab the first value and ignore the rest in effect making the above run as 
```php
->where('column_name', 'array')`.
```

I would expect (and I have a feeling it used to?) this to be transformed silently into the following code or at the very least throw an exception stating that an array was not expected.
```
->whereIn('column_name', ['array', 'of', 'values'])
```

### Steps To Reproduce:

```php
factory(\App\User::class, 5)->create();
if(count(\App\User::where('id', [1,2,3])->get()) !== 3) {
    throw new \Exception('Ah... where are my people?');
}
```

**Comment by decadence** [comment]
There was declined PR for transforming array to whereIn.
But grabbing first array value is strange indeed. It should throw InvalidArgumentException.

**Comment by hailwood** [comment]
@decadence cheers for the info, any idea why it was rejected? (A link to the PR would be awesome, I can't seem to find it by searching). But yeah, I'd be happy with the exception being thrown.

@tiagoacardoso What's up with the thumbs down?

**Comment by devcircus** [comment]
#20470

**Comment by decadence** [comment]
#19126

**Comment by decadence** [comment]
> any idea why it was rejected?
"because I don't feel it's super clear or known how this will affect wider APIs and methods"

**Comment by hailwood** [comment]
Thanks for the links guys.
