### ISSUE TITLE
Always Tokenmissmatch!

### ISSUE THREAD

**Issue by Leslie1sMe** [laravel/framework#24741]
i use Laravel`s Auth to login in my application and i add
 `{{csrf_field()}}` 
or `<input type=""hidden name="_token" value= "{{csrf_token()}}"/> in` my form in the login.blade.php 
however when i click the submit button ,it give me  a token missmatch error but in the chrome console i can see the value i post _token,name,and password .
 i used to use file to store my session and i found the session is always changing  when i request the method, so i use redis to store session  now but the problem is still alive,help me with this thank u a lot!

**Comment by sisve** [comment]
It sounds like you're looking for support. This repository is meant for bug reports. Have you tried the forum or Slack?

**Comment by decadence** [comment]
Welcome to Laravel! We are glad to have you as part of the community.

Unfortunately GitHub is not an appropriate platform for general application issues. This is only for issues/bugs with the framework code itself.

Please close your issue, and instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

Laravel Slack (https://larachat.co/)
Laravel.io Forum (https://laravel.io/forum)
Laracasts Forum (https://laracasts.com/discuss)
StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks!

**Comment by Leslie1sMe** [comment]
however i think it's a bug 😣

**Comment by crynobone** [comment]
> however i think it's a bug

If it's a bug more people would experience the same problem, including myself. Please use the forum and explain yourselves more clearly, this most likely a configuration or usage issues and not a bug with the framework itself.
