### ISSUE TITLE
Chaining multiple nested eager loads of relations leads to cleaning up before loaded data.

### ISSUE THREAD

**Issue by humunuk** [laravel/framework#24764]
- Laravel Version: 5.4
- PHP Version: 7.1.18
- Database Driver & Version: MySQL, 5.7.22

### Description:

Im not sure if this is expected behavior or bug.

Loading nested relationships to model in multiple steps deletes / clears up before loaded relations.

### Steps To Reproduce:
$model = Model::with('relation.nested1')->first();
$model->load('relation.nested2');

After the second load, nested1 is not anymore eager loaded into $model.

**Comment by staudenmeir** [comment]
This is the expected behavior (#23027, #24121). What type of relationship is `relation` in your case?

**Comment by humunuk** [comment]
Ok I went through the issues and see its expected behaviour, thank you very much for responding :)
The first relation is hasMany for Model, it goes 2 levels deep where both has hasMany with the last one being belongsTo

As with other issue creator, i have the same problem that i need to load them dependant on condition

**Comment by staudenmeir** [comment]
In Laravel 5.6 you can use `$model->loadMissing('relation.nested2')` (#24166).

Until then, use this:

```php
$model->relation->load('nested2');
```

**Comment by humunuk** [comment]
thank you so much for the help :), can close this
