### ISSUE TITLE
Laravel - update() function always return true

### ISSUE THREAD

**Issue by davidoskay** [laravel/framework#24775]
- Laravel Version: 5.6
- PHP Version: 7.2
- Database Driver & Version: Mysql

### Description:
If I use 
`User::find($id)->update(['column'=>'value']);`
I always get true, even when I don't have this column in database.

If I use 
`where('id',$user_id)`
instead of find($id), I will get error like "Column not found"

Shouldn't ::find() do the same as where()? 

### Same problem (3 years ago):
https://stackoverflow.com/questions/33053282/laravel-eloquent-update-function-always-return-true

**Comment by rs-sliske** [comment]
the difference between find and where is find will return an instance of your user model, where returns a query builder

in 1st example i expect that fillable/guarded attributes are causing the parameter to get discarded, so you are essentially calling update on an unchanged model

column not found error on the query builder update suggests it did actually try to set the column, which if it isnt in your fillable fields seems like an issue.

**Comment by davidoskay** [comment]
@rs-sliske I added question - I think that ::find() should do the same as ::where()

**Comment by rs-sliske** [comment]
find is basically just an alias for `where('id', $id)->first()`

**Comment by davidoskay** [comment]
@rs-sliske but with connect to update() i think it should check for existing columns etc too, if it's possible

**Comment by themsaid** [comment]
`User::find($id)->update(['column'=>'value'])` will return exception if column doesn't exist, however seems like your model attributes are guarded which will make the query not even run.

when using `where` it's different, you're not using an instance of the model and thus no guarded attributes are considered.

Hope this clears everything.
