### ISSUE TITLE
Schema name not working  in MSSQL

### ISSUE THREAD

**Issue by kamyar64** [laravel/framework#24774]
- Laravel Version: 5.4.36
- PHP Version: 7.2.6
- Database Driver & Version:72

hi , my laravel project connect to SQL server database
i have a big problem in my SQL server i have a different schema like  **Base.Auth.personType** Base.Auth is the name of my schema and personType name of my table
in migration file i write this codes

```
 Schema::create("Base.Automation.personType", function (Blueprint $table) {
            $table->increments('id');
            $table->char('Title',500);
            $table->boolean('IsDelete');

        });  
```
but laravel give me error   SQLSTATE[42000]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Database 'Base' does not exist.

**Comment by Dimimo** [comment]
As [described on this microsoft forum about the SQL server](https://social.msdn.microsoft.com/Forums/en-US/154c19c4-95ba-4b6f-b6ca-479288feabfb/characters-that-are-not-allowed-in-table-name-amp-column-name-in-sql-server-) in the first answer: 

**_Embedded spaces or special characters are not allowed.
Supplementary characters are not allowed._**

Table names like `T@ble` or `_#1@_cu$tomer$` are allowed but `my.table` is not.
