### ISSUE TITLE
Polymorphic relations with models having non-integer based primary key

### ISSUE THREAD

**Issue by ivuorinen** [laravel/framework#24782]
- Laravel Version: 5.*
- PHP Version: -
- Database Driver & Version: -

### Description:

[`\Illuminate\Database\Schema\Blueprint::morphs`](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Database/Schema/Blueprint.php#L1146) in 5.6 (and previous versions) expects model primary key to be an integer.

This causes problems when using non-integer based primary keys, UUIDs for example.

I don't have a clue how to solve this, maybe addition [to the documentation](https://laravel.com/docs/5.6/eloquent-relationships#polymorphic-relations) could be enough to point the not-so-obvious detail.

My current workaround is to change the column definition with a migration, but it could be an issue in the future. The table I am modifying is from [owen-it/laravel-auditing](https://github.com/owen-it/laravel-auditing/blob/master/database/migrations/audits.stub#L33) and future updates could collide with my changes.

**Comment by staudenmeir** [comment]
`Blueprint::morphs()` is just a shortcut for creating the relationship columns. You can always create the columns yourself and choose their types:

```php
$table->string('foo_type');
$table->uuid('foo_id');
```
