### ISSUE TITLE
Polymorphic relations with custom names do not load correctly

### ISSUE THREAD

**Issue by floflock** [laravel/framework#24787]
- Laravel Version: 5.6.26
- PHP Version: 7.2
- Database Driver & Version: mysql MariaDB (10.2.9-MariaDB-10.2.9+maria~jessie - mariadb.org binary distribution)

### Description:

I have the following tables:

#### Table: users

| id | email                      | password | active | user_profile_type      | user_profile_id | remember_token | created_at          | updated_at          | deleted_at |
|----|----------------------------|----------|--------|------------------------|-----------------|----------------|---------------------|---------------------|------------|
| 1  | macey.olson@example.com    | xxx      | 1      | standard_user_profiles | 1               | 2BNbGXSnE7     | 2018-07-08 15:20:00 | 2018-07-08 15:20:00 | NULL       |
| 2  | vboyle@example.net         | xxx      | 0      | premium_user_profiles  | 1               | GY3EHWm0Js     | 2018-07-08 15:20:01 | 2018-07-08 15:20:01 | NULL       |
| 3  | quinten.gibson@example.org | xxx      | 0      | standard_user_profiles | 2               | Lw46mB2Wek     | 2018-07-08 15:20:01 | 2018-07-08 15:20:01 | NULL       |

#### Table: standard_user_profiles

| id | language_id | academic_prefix | first_name | last_name   | academic_suffix | sex    | created_at          | updated_at          | deleted_at |
|----|-------------|-----------------|------------|-------------|-----------------|--------|---------------------|---------------------|------------|
| 1  | 139         | NULL            | Albin      | Stoltenberg | NULL            | male   | 2018-07-08 15:20:00 | 2018-07-08 15:20:00 | NULL       |
| 2  | 63          | NULL            | Jermey     | Konopelski  | NULL            | male   | 2018-07-08 15:20:00 | 2018-07-08 15:20:00 | NULL       |
| 3  | 156         | NULL            | Demario    | Ruecker     | NULL            | female | 2018-07-08 15:20:00 | 2018-07-08 15:20:00 | NULL       |

I have to following models:

#### Model: User

```php
class User extends Authenticatable
{
    use Notifiable, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'email',
        'password',
        'active',
        'user_profile_id'.
        'user_profile_type',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'user_profile_type',
        'user_profile_id',
    ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'active' => 'boolean',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\MorphTo
     */
    public function profile()
    {
        return $this->morphTo('user_profile');
    }
}

```

#### Model: StandardUserProfile

```php
class StandardUserProfile extends AbstractUserProfile
{
    use SoftDeletes;

    protected $fillable = [
        'language_id',
        'first_name',
        'last_name',
        'academic_prefix',
        'academic_suffix',
        'sex',
    ];

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\MorphOne
     */
    public function user()
    {
        return $this->morphOne(User::class, 'user_profile', 'user_profile_type', 'user_profile_id');
    }
}

```

#### morphMap in ServiceProvider

```php

Relation::morphMap(
  [
    PremiumUserProfile::class,
    StandardUserProfile::class,
  ]
);

```

#### This is the output from: `User::find(1)->profile`

Relationship is accessable correctly here.

```

>>> User::find(1)->profile
=> App\Models\UserProfiles\StandardUserProfile {#3170
     id: 1,
     language_id: 139,
     academic_prefix: null,
     first_name: "Albin",
     last_name: "Stoltenberg",
     academic_suffix: null,
     sex: "male",
     created_at: "2018-07-08 15:20:00",
     updated_at: "2018-07-08 15:20:00",
     deleted_at: null,
   }

```

#### This is the output from: `User::with('profile')->find(1)`

This kind of loading is not possible, because related model is loaded in the wrong property `user_profile`, property `profile` returns `null`

```
>>> User::with('profile')->find(1)
=> App\Models\User {#3154
     id: 1,
     email: "macey.olson@example.com",
     active: 1,
     created_at: "2018-07-08 15:20:00",
     updated_at: "2018-07-08 15:20:00",
     deleted_at: null,
     profile: null,
     user_profile: App\Models\UserProfiles\StandardUserProfile {#3181
       id: 1,
       language_id: 139,
       academic_prefix: null,
       first_name: "Albin",
       last_name: "Stoltenberg",
       academic_suffix: null,
       sex: "male",
       created_at: "2018-07-08 15:20:00",
       updated_at: "2018-07-08 15:20:00",
       deleted_at: null,
     },
   }
```

It does work, if I change columns and everything else to `profile_type` and `profile_id`.
However, I didn't dive deeper into framework code, but this looks like a bug by loading polymorphic relations.

**Comment by staudenmeir** [comment]
@themsaid Can you take a look at this?

You explicitly test the relation name in [`DatabaseEloquentModelTest::testMorphToCreatesProperRelation()`](https://github.com/laravel/framework/blob/8a317ddefcebe4b0855bd292c60eb5f40645c28f/tests/Database/DatabaseEloquentModelTest.php#L1061) (`morphToStubWithName` and `morphToStubWithNameAndKeys`). Aren't these tests incorrect?

**Comment by florianflock** [comment]
@staudenmeir I think, my specific case is missing in these tests.

Testing my case could look like the following snippet.
Because the relationship is called via ```name``` in ```morphTo()``` and have nothing to do with the keys in the tables.

```php
// additional test scenario in testMorphToCreatesProperRelation()

// $this->morphTo('name');
$relation5 = $model->morphToStubWithOtherName();
$this->assertEquals('some_name_id', $relation5->getForeignKey());
$this->assertEquals('some_name_type', $relation5->getMorphType());
$this->assertEquals('name', $relation5->getRelation());
```

```php
public function morphToStubWithOtherName()
{
    return $this->morphTo('name');
}
```

I hope my thesis are correct.

**Comment by staudenmeir** [comment]
Your relationship works as expected if you specify both column names and don't specify a `$name`:

```php
public function profile() {
    return $this->morphTo(null, 'user_profile_type', 'user_profile_id');
}
```

**Comment by florianflock** [comment]
@staudenmeir wow, that works! 👍 

I can see the misconception, but this looks like many dependencies in the framework. Unfortunately, I am not able to write a qualified PR... :(

**Comment by deleugpn** [comment]
Can you confirm your service provider, please? You specify the classes, but don't actually alias them up?

**Comment by florianflock** [comment]
@deleugpn you mean the ```morphMap()``` in the ServiceProvider? Yes, it is included.

The idea was to have another "Profile"-Model relation to other Models except "User"-Model, nothing to do with the current structure. So maybe in future, we have "Customer"-Models, they may can also have "Profile"-Models, but not the same as "User"-Models. So then, I would call the relation "profile"  again and get a kind of "BusinessCustomerProfile"-Model. In case of that, I can diverse the morph-fields in the database better, when naming "user_profile" and "customer_profile".

**Comment by staudenmeir** [comment]
@deleugpn was referring to the missing keys/aliases in your `morphMap()`.

**Comment by florianflock** [comment]
Is defined now, but also the same logic as @staudenmeir has evaluated.
