### ISSUE TITLE
[5.6] Collection prepend resets the array index. Possible bug?

### ISSUE THREAD

**Issue by yajra** [laravel/framework#24789]
When using prepend on collection, it seems like the key/index is being reset when using pluck values from DB. Not sure though if this is by design but it causes unseen issue in the app. It's not specified in the [prepend docs](https://laravel.com/docs/5.6/collections#method-prepend) that the indexes will be reset if a `key` is not specified in the prepend method when using indexed arrays.

```php
dump(collect([1 => 'one', 2 => 'two', 5 => 'five'])->prepend('six')->toArray());
// output
array:4 [▼
  0 => "six"
  1 => "one"
  2 => "two"
  3 => "five"
]

dump(collect([1 => 'one', 2 => 'two', 5 => 'five'])->prepend('six', 6)->toArray());
// output
array:4 [▼
  6 => "six"
  1 => "one"
  2 => "two"
  5 => "five"
]
```

Related to https://github.com/laravel/framework/pull/9289 and https://github.com/laravel/framework/issues/9327.

Real app scenario: imagine having a client list where you pluck the values from db and prepended a placeholder. Resetting the keys will cause an issue. It may not be visible on early stage of development since we usually handle an incremented id until such time...

```php
// this will be buggy when setting the client_id.
$clients = Client::pluck('name', 'id')->prepend('Select Client');
```

Although a fix is easy by adding an empty string key.

```php
$clients = Client::pluck('name', 'id')->prepend('Select Client', '');
```

**Comment by 36864** [comment]
The alternative to the current behavior would be to somehow guess what the key should be based on existing keys. A naive approach would be to check the key of the first element, and adding the new element with that value minus one. This would, of course, not work if the array starts at index 0.
You couldn't use any string key as the default without checking all the keys in the collection for a duplicate.

You'd have to check if the index `0` is available, and if not, come up with some other default that would likely not make sense in a lot of contexts.

I'm afraid the only "fix" here might be a small note in the documentation alerting to this behavior.

**Comment by driesvints** [comment]
This is indeed the correct behavior at the moment.
