### ISSUE TITLE
Pagination items on start not equal to on end

### ISSUE THREAD

**Issue by Develop-FM** [laravel/framework#24781]
- Laravel Version: 5.6.#
- PHP Version: 7.1.13
- Database Driver & Version:

### Description:
UrlWindow::getSliderTooCloseToBeginning()
needs +1 offset
>'first' => $this->paginator->getUrlRange(1, 1+ ($window + 2)),

### Steps To Reproduce:
Paginate big result and count items at 1st page and at last page.

**Comment by themsaid** [comment]
Please resubmit with proper description of the issue and share more details on how to replicate. The issue is very vague.

**Comment by UksusoFF** [comment]
Seems it's related issue: #20699
