### ISSUE TITLE
Macroable::mixin The method itself should be used instead of the method's return value

### ISSUE THREAD

**Issue by DavidNineRoc** [laravel/framework#24791]
* Laravel Version: 5.5.40
* PHP Version: 7.1.13-nts
****
# Description
`Macroable::mixin` method indicates that another object is mixed into a class. But it's actually mixing the value returned by the method, not the method itself.
# Steps To fix the issue
```
/**
 * Mix another object into the class.
 *
 * @param  object  $mixin
 * @return void
 */
public static function mixin($mixin)
{
    $methods = (new ReflectionClass($mixin))->getMethods(
        ReflectionMethod::IS_PUBLIC | ReflectionMethod::IS_PROTECTED
    );

    foreach ($methods as $method) {
        $method->setAccessible(true);

        // static::macro($method->name, $method->invoke($mixin));
        // Use this.
        static ::macro($method->name, $method->getClosure($mixin));
    }
}
```

**Comment by DavidNineRoc** [comment]
@staudenmeir 
This method will break the original test, because the original definition cannot be generated according to the comments.
```
claa A
{
     public function show1()
     {
          return function (){
               echo 1;
          };
     }
     // error
     public function show2()
     {
         echo 1;
     }
}

Macroable::mixin('show1', new A);
```
If the show1 method can be properly bound before, show2 will report an error. But I don't think that's what macros want. So I think we should have the show1 method directly, not the return value of the show1 method

**Comment by DavidNineRoc** [comment]
If that's what I want, I'll give you a test tomorrow. Because of the time difference, I may need to give you an answer tomorrow.

**Comment by staudenmeir** [comment]
I tested this with `static::macro($method->name, $method->getClosure($mixin));`

```php
class A {
    public function show2() {
        echo 1;
    }
}

class B {
    use Macroable;
}

B::mixin(new A);
(new B)->show2();
```

It throws an exception:

> Cannot bind method A::show2() to object of class B

**Comment by DavidNineRoc** [comment]
@staudenmeir My previous test was to run the closure directly , regardless of the`$this`case . It ' s true that I can ' t do it . I ' m sorry to disturb you .
