### ISSUE TITLE
Graceful handling for uploaded files above PHP's upload_max_filesize

### ISSUE THREAD

**Issue by JakeBooher** [laravel/framework#24798]
- Laravel Version: 5.6.26
- PHP Version: 7.2.6
- Database Driver & Version: Mariadb 10.3.6

### Description:

When uploading a file that is above PHP's upload_max_filesize you get `Invalid size provided for UploadedFile; must be an int`

### Steps To Reproduce:

```
$file = request()->get('file');
```

Attempt to upload a file above whatever you have `upload_max_filesize` set to, it'll throw a generic `InvalidArgumentException` rather than something a bit more useful

**Comment by JakeBooher** [comment]
Actually, seems the request()->get('file') isn't even required, making the request to any endpoint (including one that doesn't exist and should normally throw a 404) will throw this error if you're exceeding the max upload size

**Comment by JakeBooher** [comment]
Have done a bit more debugging, and it only seems to happen when the `\Laravel\Passport\Http\Middleware\CheckClientCredentials` middleware is being applied

**Comment by JakeBooher** [comment]
```
Ultimately boils down to \Zend\Diactoros\ServerRequest running:

$this->validateUploadedFiles($uploadedFiles);

Is there any way for us to bypass this as I'm only wanting to check the client credentials to ensure they're valid
```

**Comment by doncadavona** [comment]
I'm getting the same issue here on same Laravel version.

**Comment by mfn** [comment]
Isn't this rather an issue with the 3rd party code from https://github.com/zendframework/zend-diactoros ?

**Comment by laurencei** [comment]
Closing here, as you've posted it on the Laravel/Passport section, which is where this belongs?
