### ISSUE TITLE
Validateurl with underscores.

### ISSUE THREAD

**Issue by bramr94** [laravel/framework#24792]
- Laravel Version: 5.5.40
- PHP Version: 7.1.16

### Description:

The current URL validation regex cannot validate URL's with underscores.

### Steps To Reproduce:
Add the URL rule to a request and fill in the following URL:
http://www.demo_url.test/

Current regex: https://regex101.com/r/FVIJsx/1

**Comment by bonzai** [comment]
[The URL you're trying to validate is invalid:](https://en.wikipedia.org/wiki/Hostname#Restrictions_on_valid_hostnames)

> While a hostname may not contain other characters, such as the underscore character […]

Further reading:
http://www.ietf.org/rfc/rfc1738.txt

**Comment by bramr94** [comment]
What about sub domains? It is not recommended to use underscores but it is allowed.

http://sub_domain.demourl.test/
