### ISSUE TITLE
array_sort helper failed with `Undefined offset` when array keys are numeric strings

### ISSUE THREAD

**Issue by hlorofos** [laravel/framework#24799]
- Laravel Version: 5.6.27
- PHP Version: 7.1.12
- Database Driver & Version:

### Description:

array_sort helper failed with `Undefined offset` when array keys are numeric strings

### Steps To Reproduce:

```php
        $temp = new \stdClass();
        $temp->{2} = 'a';
        $temp->{1} = 'b';

        $array = (array)$temp;

// both will fail with ErrorException: Undefined offset: 1
 array_sort($array);
 array_sort($temp);
```

**Comment by Harry-Torry** [comment]
This is due to `array_key_exists('2', $array) == false`. It's also false if you try calling `array_key_exists(2, $array),`.

I'd suggest writing a PR to https://github.com/php.

Failing that, wrap `$array = (array)$temp` into a collection and then sorting works.

```php
        $temp = new \stdClass();
        $temp->{2} = 'a';
        $temp->{1} = 'b';

        $array = collect((array)$temp);

        // Sorted
        $array->sort(function($element) {
            return $element;
        });
```

**Comment by sisve** [comment]
The mentioned behavior of `array_key_exists` differs between PHP 7.1 and PHP 7.2. Can you upgrade to PHP 7.2 and retry?

**Comment by hlorofos** [comment]
In PHP 7.2 I wasn't able to get numeric strings as the array keys, 
`$array = (array)$temp;` would convert em to integers.
This is applicable only to PHP 7.1
