### ISSUE TITLE
withCount bug when using custom select

### ISSUE THREAD

**Issue by mnabialek** [laravel/framework#24797]
- Laravel Version: v5.6.26
- PHP Version: 7.2.5
- Database Driver & Version: MySQL 8.0.11

### Description:

Using `withCount` together with conditions and custom `select` causes running invalid queries.

### Steps To Reproduce:

When having relationship defined like this:

```
public function userImages()
{
    return $this->hasMany(Image::class)->where('type', 'user');
}
```

When running code like this:

```
$query = Model::where('status', 'online')->select(['*'])->withCount('userImages');
```
or

```
$query = Model::where('status', 'online')->withCount('userImages');
```

SQL looks like this:

```
select `models`.*, (select count(*) from `images` where `models`.`id` = `images`.`model_id` and `type` = ?) as `user_images_count` from `models` where `status` = ?
```

and bindings look like this:

```
array:2 [
  0 => "user"
  1 => "online"
]
```

so everything is as expected.

But running code like this

```
$query = Model::where('status', 'online')->withCount('userImages')->select(['*']);
```

SQL looks like this:

```
select * from `models` where `status` = ?
```

and bindings looks like this:

```
array:2 [
  0 => "user"
  1 => "online"
]
```

The are at least 3 problems here:

1.  $result->user_images_count will result invalid value
2. bindings are wrong so invalid data will be taken from database
3. there is no exception thrown anywhere (or any information about such behavior in documentation) so without debugging query it's really hard to detect that query is completely invalid

**Comment by Harry-Torry** [comment]
With how `select()` sets the columns (`$this->columns = is_array($columns) ? $columns : func_get_args();`), it wipes the columns that get set by the `withCount()` call.  You're explicitly stating you want XYZ field and then removing that field.

Try calling the `select()` before the `withCount()`!

**Comment by Harry-Torry** [comment]
Here's another one about the same "issue" - https://github.com/laravel/framework/issues/19388.

**Comment by mnabialek** [comment]
@Harry-Torry I'm total away that changing order fix the issue (I showed this in the issue). I also saw implementation, but it's quite risky when it works like this and there is no additional information about this in documentation.

**Comment by Harry-Torry** [comment]
Submit a PR to the docs 👍
