### ISSUE TITLE
how to fix toles in laravel voyager 

### ISSUE THREAD

**Issue by hamzataougar** [laravel/framework#24793]
Hey , 
I got an issue while i create a new user in laravel voyager  , it tells me  that it s created and got a role , then right after once i want to connect with the credentials of the new user , it takes me to the index of my front-end .
this picture is for the user created : 
![image](https://user-images.githubusercontent.com/21199501/42501723-419eb6ba-842c-11e8-9c2a-b0e3144dc0a1.png)

the second one is what i get when i try to connect : 
![image](https://user-images.githubusercontent.com/21199501/42501781-60576c1e-842c-11e8-817b-c1abbe5e71b2.png)

thank you for helping

**Comment by decadence** [comment]
Welcome to Laravel! We are glad to have you as part of the community.

Unfortunately GitHub is not an appropriate platform for general application issues. This is only for issues/bugs with the framework code itself.

Please close your issue, and instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

Laravel Slack (https://larachat.co/)
Laravel.io Forum (https://laravel.io/forum)
Laracasts Forum (https://laracasts.com/discuss)
StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks!

**Comment by hamzataougar** [comment]
okay man , thanks
