### ISSUE TITLE
There are Notifications in the Database, but i'm not able to display them in my interfaces

### ISSUE THREAD

**Issue by Nasir87** [laravel/framework#24804]
- Laravel Version: 5.5.*
- PHP Version: >=7.0.0
- Database Driver & Version: mysql

### Description:
i've created a **laravel-vuejs** project (to build up a kind of forum) in **_which each time a User creates a newReply to Question asked, it will generate a notification._** But the fact is, **_the Notifications coming from the class HasDatabaseNotifications.php show zero content, so i'm not able to display that in my app_**. It's a serious issue for me, in fact i'm stuck at that point for so long.

### **1- in NotificationController.php**
`
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Resources\NotificationResource;

class **NotificationController extends Controller**
{
  _**public function index() {
    return [
      'read' => auth()->user()->readNotifications()->get(),
      'unread' => auth()->user()->unreadNotifications()->get(),
    ];
  }**_
  
  public function markAsRead(Request $request) {
    auth()->user()->notifications->where(
      'id',
      $request->id
    )->markAsRead();
  }
}
`
### 2 - ***in api.php**
`**Route::post('notifications', 'NotificationController@index');**`

### **3- in NewReplyNotification.php**
namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Notification;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use App\Model\Reply;

class **NewReplyNotification** extends Notification
{
    use Queueable;

    public $reply;

    /**
     * Create a new notification instance.
     *
     * @return void
     */
    public function __construct(Reply $reply)
    {
        $this->reply = $reply;
    }

    /**
     * Get the notification's delivery channels.
     *
     * @param  mixed  $notifiable
     * @return array
     */
    public function via($notifiable)
    {
        return ['database'];
    }

     /**
     * Get the array representation of the notification.
     *
     * @param  mixed  $notifiable
     * @return array
     */
    **_public function toArray($notifiable)
    {
        return [
            'replyBy' => $this->reply->user->name,
            'question' => $this->reply->question->title,
            'path' => $this->reply->question->path,
        ];
    }_**
}

### 4- in AppNotification.vue, to display those unread & read notifications
`
  <div class="text-xs-center">
    <v-menu offset-y>
      <v-btn icon slot="activator">
        <v-icon color="red">
          add_alert
        </v-icon> 5
      </v-btn>
      **_<v-list>
        <v-list-tile
          v-for="item in unread"
          :key="item.id"
        >
          <router-link to="item.path">
            <v-list-tile-title @click="readIt(item)">
              {{ item.question }}
            </v-list-tile-title>
          </router-link>
        </v-list-tile>
      </v-list>_**

      <v-divider></v-divider>

      **_<v-list>
        <v-list-tile
          v-for="item in read"
          :key="item.id"
        >
          <router-link to="item.path">
            <v-list-tile-title @click="readIt(item)">
              {{ item.question }}
            </v-list-tile-title>
          </router-link>
        </v-list-tile>
      </v-list>_**
    </v-menu>
  </div>

  export default {
    data() {
      return {
        **_read: {},
        unread: {},
        unreadCount: 0_**
      }
    },
    created() {
      if(User.loggedIn()) {
        **_this.getNotifications();_**
      }
    },
    methods: {
      **_getNotifications() {
        axios.post('/api/notifications/')
        .then(res => {
          console.log('getNotif success...', res);
          this.read = res.data.read;
          this.unread = res.data.unread;
          this.unreadCount = res.data.unread.length;
          console.log('numb notif...', this.unreadCount);
        });
      }_**,
      readIt(notification) {
        axios.post('/api/markAsRead', {id: notification.id})
        .then(res => {
          this.unread.splice(notification, 1);
          this.read.push(notification);
          this.unreadCount--;
        })
      }
    }
  }
`

### 5- db tables
![db_tables](https://user-images.githubusercontent.com/31565739/42558782-971c00ae-84f2-11e8-85fc-5e73f8a89b99.PNG)

### 6- db : Notifications table with elements, i have 5 elements
![db_elts](https://user-images.githubusercontent.com/31565739/42558833-b4c3745c-84f2-11e8-819a-040e0021dc98.PNG)

### 7- App vue interface, to display read and unread notifications, showing zero notif
![app_interface](https://user-images.githubusercontent.com/31565739/42558889-d5e83e92-84f2-11e8-9572-0e1517be5ef8.PNG)

### 8- App vue inspector to check the state of read, unread notifications & count number take, from db.. which are all zero, while i have 5 notifications stored in the db
![app_vue_inspector](https://user-images.githubusercontent.com/31565739/42558997-232dee2c-84f3-11e8-9f7e-3998a5a9c9b5.PNG)

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.

**Comment by Ahmadh1** [comment]
`axios.post("/api/markAsRead", { id: notification.id, user_id: notification.user_id }).then().catch()`
then in controller
`public function markAsRead(Request $request) {
        $user = User::find($request->user_id);
        $user->notifications()->delete();
    }`
