### ISSUE TITLE
Updated Event in Trait Boot is not called

### ISSUE THREAD

**Issue by pmochine** [laravel/framework#24800]
- Laravel Version: 5.6.*
- PHP Version: 7.2.7
- Database Driver & Version: sqlite

### Description:

In my phpunit test I'm updating values:

    /** @test */
 	public function it_updates_newsletter_when_user_privacy_is_updated() 
	{
		
		$privacy = create('App\UserPrivacy', ['user_id' => auth()->id()]);

		$privacy->update(['firstname' => 'Philipp']);

	}

And I'm trying to catch the updated event in a trait. But the thing is, it is never beeing called. Here is the trait: 

    trait UpdatesNewsletter
    {
    	/**
    	 * Boot the trait.
    	 */
    	protected static function bootUpdatesNewsletter()
    	{
    	    if (auth()->guest()) return;
    
            static::updated(function ($model){
    			var_dump('is called by trait');
            });
    	    
    	}
    }

Just for my sanity check, I wrote the event catch for the model itself. 

    class UserPrivacy extends Model
    {
    	use UpdatesNewsletter;
    
         /**
          * Boot the model.
          */
        protected static function boot()
        {
            parent::boot();
    
            static::updated(function ($privacy){
            	var_dump('is called by class');
            });
        }
    }

And in my console I see the only message: 

    string(18) "is called by class"

That should be a bug or I'm to ....

### Steps To Reproduce:
clone https://github.com/pmochine/TraitBootBug

and run the php unit test in UpdatesNewsletterTest.

The updated event in class is called but not the updated event in trait

**Comment by pmochine** [comment]
@brunogaspar That is the weirdest part. Why is there not an authenticated user? I have a very similar trait that works the exact way and it works. You can look it up in [council](https://github.com/JeffreyWay/council/blob/master/tests/Unit/ActivityTest.php). You see the test is similar build and it works perfectly. The trait is called and there is no difference at the beginning. 

So why is there no session in my case? (Need help to understand it, thank you)

**Comment by devcircus** [comment]
I just cloned your repo and everything works as expected. Create a user and sign in as that user. Jeffrey isn't running ```$this->signIn()``` inside the ```setup()``` method. That should go inside each test method in which you need a user.
