### ISSUE TITLE
URL generate and route resolve bug for some parameters

### ISSUE THREAD

**Issue by dawsza** [laravel/framework#24808]
- Laravel Version: 5.5.40
- PHP Version: 7.2.3

### Description:
There is bug with proper encoding URL parameters and routes resolve with such parameters.
In example below first and second URL's works ok, but third and forth not.
In third example there is invalid encoded parameter, in forth example parameter is proper encoded but routing resolve not work proper.

### Steps To Reproduce:

```
Route::get('/test/{parameter}', function() {
    return 'single paramater action';
})->name('single_parameter_route');

Route::get('/test/{fist_parameter}/{second_parameter}', function() {
    return 'double paramater action';
})->name('double_parameter_route');

Route::get('/test', function() {
    return "\n".'Single parameter link: '. route('single_parameter_route', ['parameter' => 'abc']) .
           "\n".'Double parameter link: '. route('double_parameter_route', ['first_parameter' => 'abc', 'second_parameter' => 'xyz']) .
           "\n".'[Bug] Single parameter link with more complex parameter leads to double_parameter_route: '. route('single_parameter_route', ['parameter' => 'aaa/zzz']) .
           "\n".'[Bug] When we manually encode parameter routing still not work correct: '. route('single_parameter_route', ['parameter' => rawurlencode('bbb/ccc')]);
});
```

**Comment by pavinthan** [comment]
@dawsza It's working fine, It's not a bug.

**Comment by dawsza** [comment]
When I generate link to route "single_parameter_route" and it leads to route "double_parameter_route" then it isn't bug? Is it feature? How?

**Comment by Dimimo** [comment]
You have to put `Route::get('/test/{fist_parameter}/{second_parameter}'` above `Route::get('/test/{fist_parameter}`. First come, first serve. 

Adding a slash in a url parameter makes no sense, even encoded. You can use a dot, a hyphen, an @ anything you like (that can't be a part of the parameter itself). F.ex.. space (' ') or '%20' are treated the same.

**Comment by dawsza** [comment]
The problem is that when you generate link to one route then its come to another route. It's not depend by routes order because when routes order is changed then doesn't works too. It is bug.

Probably I can use for example hyphen instead of slash but what when I don't want or   can't?  Imagine situation when you want give full url to search results with exact phrase entered by user. Then what?

**Comment by dawsza** [comment]
@tillkruss Why you close this issue? Did you even check this bug?
