### ISSUE TITLE
Request parse JSON data differently in POST and PATCH method

### ISSUE THREAD

**Issue by pablorsk** [laravel/framework#24812]
- Laravel Version: 5.6.22
- PHP Version: 7.1.17

### Description:

Request parse JSON data differently in POST and PATCH method, when header 'Content-Type: application/vnd.api+json' or  'Content-Type: application/json'  is present.

### Steps To Reproduce:

Assume the following controller

    public function post_or_patch(Request $request)
    {
        var_dump($request->json()->all());
    }

#### When I send POST data

```bash
curl 'http://example.com/test' -H 'Content-Type: application/json' \
 --data-binary '{"data":"", "another_data": "hola"}' --compressed
```

dumps
```
array(2) {
      ["data"]=>
      string(0) ""
      ["another_data"]=>
      string(4) "hola"
}
```

#### When I send PATCH data

```bash
curl 'http://example.com/test' -X PATCH -H 'Content-Type: application/json' \
 --data-binary '{"data":"", "another_data": "hola"}' --compressed
```

```
array(2) {
      ["data"]=>
      NULL
      ["another_data"]=>
      string(4) "hola"
}
```
I try, also, with  $request->all(), $request->toArray(), $request->input() and $request->json()->all().

If ` -H 'Accept: application/vnd.api+json'` is removed, we receive allways a string.

If I use `var_dump(json_decode($request->getContent(), true));`, return same data POST and PATCH (very extrange, beacause `->json()` returns an object `ParameterBag((array) json_decode($this->getContent(), true))`)

**Comment by ybaruchel** [comment]
Tried to reproduce with Laravel 5.6.27 following the same steps you described but always got `NULL` on the `data` key.

Can you post your routes file?

**Comment by pablorsk** [comment]
@ybaruchel you got NULL on POST and PATCH? or only with PATCH call like me?

**Comment by ybaruchel** [comment]
@pablorsk I got `NULL` on both :/
