### ISSUE TITLE
Blade @inject creates new instance of singleton

### ISSUE THREAD

**Issue by arxeiss** [laravel/framework#24822]
- Laravel Version: 5.6.26
- PHP Version: 7.1.8

### Description:
I have created BreadcrumbService and registered in AppServiceProvider as singleton. In controllers and other places I resolve it via contructor parameters and it works as singleton. But if I get that service in Blade template with `@inject` directive, it creates new instance.

I asked on [StackOverflow ](https://stackoverflow.com/q/51282044/1513087)if it is bug or expected behaviour, but till now I have no answer, so I guess it is bug.

### Steps To Reproduce:
1. Creates any service
2. Register as singleton in AppServiceProviders.php

        public $singletons = [
            BreadcrumbService::class => BreadcrumbService::class,
        ];
3. Use `@inject` in Blade template. Method `isActive()` returns true if there are some crumbs in object. False is returned otherwise....

        @inject('breadcrumbs', '\SunApp\Services\BreadcrumbService')
        @php
            var_dump(resolve(\SunApp\Services\BreadcrumbService::class)->isActive());
            var_dump($breadcrumbs->isActive());
        @endphp

Here first `var_dump` prints true, second one prints false.

**Comment by lagbox** [comment]
`'\Sun\Services\BreadcrumbService' !== 'Sun\Services\BreadcrumbService'

Classes as strings are FQCN already, you don't add slashes to them for root.

**Comment by arxeiss** [comment]
You are right. My bad. Then there is no bug and it works as it should.
Thank you
