### ISSUE TITLE
Image link not stored in the database

### ISSUE THREAD

**Issue by hamzataougar** [laravel/framework#24859]
Hey people , 

I ve got a problem with image which the link is not stored in the database ,
the code in the controller  of the upload is below: 
![image](https://user-images.githubusercontent.com/21199501/42755683-22b871f4-88f1-11e8-9b68-a0e38a2d45d8.png)

and the on in the view is that :  

![image](https://user-images.githubusercontent.com/21199501/42755735-4e59a620-88f1-11e8-8ae3-3480a9595759.png)

and all i got in the database is a null value ;

![image](https://user-images.githubusercontent.com/21199501/42755760-626c6422-88f1-11e8-8092-13c1879e2ede.png)

thanks a lot .

**Comment by YanDatsyuk** [comment]
@hamzataougar Hi! Frameworks's github repository is wrong place for asking such kind of questions... You should ask this question at stackoverflow...

**Comment by hamzataougar** [comment]
okay thanks man
