### ISSUE TITLE
Cannot migrate if you have "View::share"

### ISSUE THREAD

**Issue by mokhosh** [laravel/framework#24858]
- Laravel Version: 5.6.*
- PHP Version: 7.1.14
- Database Driver & Version: irrelevant

### Description:
In my `AppServiceProvider` I have this code:
```
View::share('languages', Language::all());
```
I tried to do the migrations and this is the error I get even though it shouldn't have anything to do with views:
```
In Connection.php line 664:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'vnbase.languages' doesn't exist (SQL: select * from `languages` where `languages`.`deleted_at` is null)


In PDOConnection.php line 82:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'vnbase.languages' doesn't exist


In PDOConnection.php line 80:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'vnbase.languages' doesn't exist
```

Note that this is a fresh copy of my project and this migration is supposed to create the `languages` table.

**Comment by devcircus** [comment]
This would be expected, since you're trying to share data from a table that doesn't exist.

**Comment by shadoWalker89** [comment]
Comment that code, run the migration and then uncomment the code.

**Comment by mokhosh** [comment]
@shadoWalker89 of course that's what I did, I thought I should report this since this doesn't make sense. Thanks anyway for your answer.

@devcircus That's the thing, I'm not loading any views. Why should Laravel even try to share a variable with views that I'm not creating? I'm just trying to migrate my tables, so it seems reasonable that Laravel should only be doing database work here. Right?

**Comment by 36864** [comment]
It has nothing to do with views or View::share. When your AppServiceProvider is loaded, you attempt to load all Languages to pass them as a parameter to a function, but the base table doesn't exist.

**Comment by mokhosh** [comment]
@36864 oh silly me! I thought I'm passing a closure and the `share` function should be smart enough not to try to run it.

Thank you.
