### ISSUE TITLE
Sorting middlewares defies the priority in defining them

### ISSUE THREAD

**Issue by wisammechano** [laravel/framework#24854]
- Laravel Version: 5.6
- PHP Version: 7.1.9
- Database Driver & Version: MySql 5.7.19

### Description:
I have arranged a priority for the middlewares I am piping the app through like cors handling and authentications. But Laravel resorts the middlewares alphabetically which changes this priority. So Authentication get's applied first and throws its exception before the ability to apply other middlewares.

**Although I can change handling authentication, the main problem remains is why does Laravel sort the whole middleware groups?**

### Steps To Reproduce:
Guard your routes or controllers by 'auth:api' and other middlewares. No matter how you arrange them, auth get's applied before the others due to the alphabetical precedence.

**Comment by shadoWalker89** [comment]
I think if you would like to make use of the authenticated user in your middleware then you should use the route middlewares and not the global middlewares.

**Comment by wisammechano** [comment]
I do use it in routes and declare it in the constructor or on the route itself. Still, other route middlewares won't get applied when auth rejects.

**Comment by driesvints** [comment]
You have the `middlewarePriority` on the Kernel class which you can use for this. In the `Kernel` class of the 5.7 skeleton this is added by default: 

https://github.com/laravel/laravel/blob/6806aaa3568382e9c8c7281a64b82a52b824e46f/app/Http/Kernel.php#L72-L79
