### ISSUE TITLE
authenticated user with count return all users 

### ISSUE THREAD

**Issue by jehadja** [laravel/framework#24850]
- Laravel Version: 5.5.40
- PHP Version: 7.0.13-1
- Database Driver & Version: Ver 14.14 Distrib 5.7.19

### Description:
when you count relation of have many with authenticated user it will return all users with the relation count 

### Steps To Reproduce:
Model User.php 
```
    public function Posts(){
       return $this->hasMany('App\Post','author_id');
     }
```
then on any controller route etc.. 
```
dd(Auth::user()->withCount('posts'));

dd(Auth::user()->withCount('posts')->first());
// will return first user on database with posts_count

dd(Auth::user()->withCount('posts')->get());
// will return all users on database with posts_count

//to make it work 
$user = \App\User::withCount('Posts')->where("id",\Auth::user()->id)->first();
```

hope it will help you

**Comment by staudenmeir** [comment]
`$user->where(...)->get()` is equivalent to `User::where(...)->get()`.

In your case, just use `Auth::user()->posts()->count()`.
