### ISSUE TITLE
logoutOtherDevices breaks remember me cookie

### ISSUE THREAD

**Issue by Sergzy** [laravel/framework#24857]
- Laravel Version: 5.6.26
- PHP Version: 7.2.5

### Description:
There is a problem with "remember me" cookie when using AuthenticateSession middleware and the new "logoutOtherDevices".

When you login user with [$remember = true] a cookie is set which includes identifier, token and **password hash**. I use logoutOtherDevices after logging in the user because I want to only have one active login session per user. This function changes the password hash. Now we have a mismatch because the new password hash is not anymore the same as that one saved in "remember me" cookie.

When the session expires, user is supposed to be logged in viaRemember, but cannot be as password hashes do not match.

### Steps To Reproduce:
Login user with $remember=true. After logging in, use logoutOtherDevices. Now make sure that the session expires (either timeout or enable expire_on_close and close the browser). When you will return to the site, you will be logged out.

**Comment by padinko** [comment]
I have this problem too.
I am doing on project, where user can be logged in only on 1 browser. So i use logoutOtherDevices in login method. 

I did some solution, but this will work only in login method, because of queued cookies:

```
// logout other devices
$oldPasswordHash = $user->password;
$newPasswordHash = Hash::make($request->input('password'));
$user->forceFill([
    'password' => $newPasswordHash,
])->save();

if ($request->filled('remember')) {
    $rememberCookieName = Auth::getRecallerName();
    $rememberCookieValue = $this->cookies->getQueuedCookies()[$rememberCookieName]->getValue();
    $rememberCookieValue = str_replace($oldPasswordHash, $newPasswordHash, $rememberCookieValue);
    $this->cookies->queue(
        $this->cookies->forever($rememberCookieName, $rememberCookieValue)
    );
}
```

where `$this->cookies` is `use Illuminate\Contracts\Cookie\QueueingFactory as CookieJar;`

**Comment by laurencei** [comment]
Closing as PR merged
