### ISSUE TITLE
Will the official components consider supporting swoole extension？

### ISSUE THREAD

**Issue by kcloze** [laravel/framework#24851]
In the swoole env: initializes framework once and then handles requests/responses.
it will be more faster and more efficient. but the possibility of a problem is greater.
We very much hope that officials can support swoole extensions.

like this :
https://github.com/zendframework/zend-expressive-swoole

**Comment by sisve** [comment]
This sounds like a feature request and not a bug report. Consider filing an issue at https://github.com/laravel/ideas instead, preferably with a more extensive description of why this is a good thing, and what needs to be done in Laravel's source.
