### ISSUE TITLE
toSql() does not generate query with database name

### ISSUE THREAD

**Issue by xorock** [laravel/framework#24860]
- Laravel Version: 5.6
- PHP Version: 7.2

Sample query:

```php
class Test extends Model {
    protected $table = 'test';
    protected $connection = 'conn1';
}
```

where `conn1` is 

```
'conn1' => [
            'driver' => env('DB_DRIVER', 'mysql'),
            'host' => env('DB_HOST', 'localhost'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE_2', 'db2'),
```

```php
$sub = Test::query()->select([
            'col1', 'col2'
        ])
            ->where('col3', '>', 0)
            ->groupBy('col1');
```

dd($sub->toSQL()); produces

```sql
select `col1`, `col2` from `test`...
```

and it should be:

```sql
select `col1`, `col2` from `db2`.`test`...
```

When working with multiple connections / databases it might be a problem, especially when the query is passed as raw subquery.

**Comment by jarnovanleeuwen** [comment]
The query is built using Eloquent's query builder, which uses the same connection as the model `Test`. In your example, the query is executed on the connection of `conn1`. Therefore, the selected the database is `db2` and you do not have to use the alias in your query. 

When working with multiple connections, make sure you build your queries using the appropriate connection. Even with raw queries you can specify the connection (e.g., `DB::connection('conn1')->statement("update `test` set ..."));`)

**Comment by xorock** [comment]
Maybe I post real world example.

```php
$sub = Test::query()->select([
            'o.id', 'o.sent'
        ])
//            ->from('db2.test AS o') - I have to force database
            ->groupBy('o.id');

        $query = DB::connection('common')->table(DB::raw('( '. $sub->toSql() .' ) AS od'))
            ->select([
                'od.id', 'od.sent',
            ])
            ->leftJoin('tab2 AS k', 'k.id', '=', 'od.id');
```

```Base table or view not found: 1146 Table 'common.test' doesn't exist```
Table common.test does not exist because it's db2.test.

**Comment by 36864** [comment]
In your example, `$sub` was generated on a connection to `db2`. It had no reason to explicitly define a database name.

**Comment by jarnovanleeuwen** [comment]
You are adding raw SQL to a query on a different connection. Then, of course, it is your responsibility to explicitly specify the databases. This is not an issue.

**Comment by GabrielaSaldana** [comment]
If you were using another db connection then it would have appeared but since you are using the connection db2 it doesn't appear in your dd.
