### ISSUE TITLE
Laravel slack log but with additional fields and configuration

### ISSUE THREAD

**Issue by davidoskay** [laravel/framework#24866]
- Laravel Version: 5.6
- PHP Version: 7.2
- Database Driver & Version: MySQL

### Description:
I think that Laravel 5.6 have leaks in documentation at Logs - I'm trying to make proper slack logs and I did:
    
    'channels' => [
        'stack' => [
            'driver' => 'stack',
            'channels' => ['single', 'slack'],
        ],

        'slack' => [
            'driver' => 'slack',
            'url' => env('LOG_SLACK_WEBHOOK_URL'),
            'username' => 'TEST',
            'icon' => ':boom:',
            'level' => 'info',
        ],

It works but I want to specify additional fields and maybe customize it a little if it match some other conditions. 

I was looking at SlackWebhookHandler.php monolog file but not all parameters work in this configuration.. 
For example emoji and username doesn't work - I don't know if slack already has even options for changing bot username.
Other example is that in this file something it's called useAttachment and here it's just attachment - where the names are stored..?

Back to topic I did:

     Log::info('added test',['test'=>'test']);

And it works, but for slack I want to send additional field, in every request for example:

    'added test',['test'=>'test', 'more' => 'test2']

How I'm able to accomplish it? I need to connect to Log Class and slack driver in some way but I don't have idea how to do this?

**Comment by davidoskay** [comment]
I was able to get closer to solution but still not at all:
On logging.php now I have

    'slack' => [
        'driver' => 'slack',
        'url' => env('LOG_SLACK_WEBHOOK_URL'),
        'tap' => [App\Logging\SlackLogger::class],
        'username' => 'BOT',
        'attachment' => false,
        'emoji' => ':boom:',
        'level' => 'info',
    ],

I created App/Logging/SlackLogger.php:
 
    
    namespace App\Logging;
    
    use Monolog\Logger;
    use Monolog\Handler\SlackWebhookHandler;
    use Monolog\Formatter\LineFormatter;
    use Monolog\Formatter\JsonFormatter;
    
    
    class SlackLogger
    {
        /**
         * Customize the given logger instance.
         *
         * @param  \Illuminate\Log\Logger  $logger
         * @return void
         */
        public function __invoke($logger)
        {
            $dateFormat = "Y-m-d H:i:s";
            $checkLocal = env('APP_ENV');
    
            foreach ($logger->getHandlers() as $handler) {
                if ($handler instanceof SlackWebhookHandler) {
                    $output = "[$checkLocal]: %datetime% > %level_name% - %message% `%context% %extra%` :poop: \n";
                    $formatter = new LineFormatter($output, $dateFormat);
    
                    $handler->setFormatter($formatter);
                    $handler->pushProcessor(function ($record) {
    
                        $record['extra']['dummy'] = 'test';
    
                        return $record;
                    });
                }
            }
        }
    
    }

And It works only if I don't try to make custom attachment on slack.. When I'm trying to do:

    
    $handler->pushProcessor(function ($record) {
    
      $record['extra']['dummy'] = 'test';

      $record['attachments'] = [
          'color' => "#36a64f",
          "title" => "Slack API Documentation",
          "text" => "Optional text that appears within the attachment"
      ];

      return $record;
    });

the $record losts 'attachments' array.. I was checking it in SlackWebhookHandler in write function. I know that can be related to `$handler->setFormatter($formatter);` but I if I remove It, the problem still exists - so I still don't know how to solve it

**Comment by Bjornftw** [comment]
Do you know how I can use Slack attachments?

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
