### ISSUE TITLE
Laravel Passport scope on group route does not work

### ISSUE THREAD

**Issue by SajjadKharrazi** [laravel/framework#24863]
when i use scope in Passport authentication,
i want to add these scopes into api.php routes with different group of route
but i get an error:

> Invalid scope(s) provided.

In my AuthServiceProvider.php:
```php
public function boot()
{
    $this->registerPolicies();

    Passport::tokensCan([
        'app' => 'User Application',
        'admin' => 'Admin Application',
    ]);
    Passport::routes();
}
```
and in my api.php:
```php
Route::prefix('v1')->group(function () {

    Route::middleware(['auth:api', 'scope:app'])->group(function () {
        // Some App Route
    });

    Route::prefix('admin')->group(function () {

        // Some Admin Route without auth

        Route::middleware(['auth:api', 'scope:admin'])->group(function () {
            // Some Admin Route with auth
        });
    });
});
```

**Comment by jarnovanleeuwen** [comment]
A [`MissingScopeException`](https://github.com/laravel/passport/blob/master/src/Exceptions/MissingScopeException.php) is thrown when a request is made by a user without the required scopes (e.g., `app` or `admin`). So, the route is correctly protected, but the request is made without those scope(s).

**Comment by crock2017** [comment]
Route::group(['middleware' => ['auth:api', 'scopes:your_scope']], function(){
*****your_routes are here****
}
