### ISSUE TITLE
Inconsistency between Model and Pivot on Eloquent

### ISSUE THREAD

**Issue by itapingu** [laravel/framework#24869]
- Laravel Version: 5.6.26
- PHP Version: 7.1.19 & 7.2.7 (ubuntu)
- Database Driver & Version: mysql 5.7.22

### Description:
The default foreign key from the Model is taken using this function:
```
/**
     * Get the default foreign key name for the model.
     *
     * @return string
     */
    public function getForeignKey()
    {
        return Str::snake(class_basename($this)).'_'.$this->getKeyName();
    }
```
while the one used by the Pivot just take the value provided or the value from the parent relationship making mandatory to define the foreignKey of a sub relationship on the pivot table.

I think the sub relationship should take the right default foreignKey like the Model is doing. 

### Steps To Reproduce:
5 tables:
- companies
- company_sport
- sports
- sport_categories
- company_sport_category

sport 1->N categories
company N<->N sport on company_sport (PIVOT)
company_sport 1->N company_sport_category (WRONG FOREIGN KEY)

i set up an hasMany relationship on the CompanySport Pivot pointing to the CompanySportCategory Model but it's not taking the right key by default "company_sport_id" instead is using the "company_id" from the parent relationship.

Hope you can understand the thing, i'm a bit new on reporting issues.
Best regards

**Comment by staudenmeir** [comment]
Can you post actual Eloquent models and relationships? That's easier to read.

**Comment by itapingu** [comment]
To see the issue you just need this 3 models/pivot.
All the tables have an `id` field (even the N to N + the unique index for the 2 foreign keys)
```
class Company extends Model
{
    // GOTCHA: to use relations on pivot class i need to add the "id" using withPivot
    public function sports() {
        return $this->belongsToMany(Sport::class)->using(CompanySport::class)->withPivot(['id','enabled']);
    }
}
```

```
class Sport extends Model
{
    public function categories() {
        return $this->hasMany(Category::class);
    }

    public function companies() {
        return $this->belongsToMany(Company::class);
    }
}
```

```
class CompanySport extends Pivot
{
    public function company() {
        return $this->belongsTo(Company::class);
    }

    public function sport() {
        return $this->belongsTo(Sport::class);
    }
    
    // ISSUE IS HERE (i need to specify the foreign key, if it could take the foreign from the Pivot class name everything should be resolved automatically)
    public function categories() {
        return $this->hasMany(CompanySportCategory::class,'company_sport_id'); // by default laravel get company_id 
    }
}
```

**Comment by itapingu** [comment]
Another small note.

What i'm trying to achieve is to query the CompanySportCategory (hasMany relationship from CompanySport), and without using an `id` in the CompanySport it's causing me issues, maybe it's me missing something.... but is possible to query an hasMany relationship from a pivot table using the 2 foreign key? or the extra id i'm using is needed? otherwise i have to bring 3 foreign key on the CompanySportCategory table (2 from CompanySport + 1 from Category).

If i get anything wrong please correct me, and thanks again for your wonderful work.

**Comment by lloy0076** [comment]
Just to make it clear to me, what you want to do is still _possible_ just not as _easy_ as you'd like? i.e. this might be an enhancement but not a bug?

**Comment by itapingu** [comment]
Hi @lloy0076 it can be both of them, it depends if how i'm interpreting the Laravel logic is right or not.

If for Laravel you expect to have an `id` on the Pivot model in a pivot table to handle subsequent relationship on the Pivot model then it's a bug.

If the "right way" instead is to keep 2 foreign_key and no `id` then i cannot find a way, that make sense, to have a relationship on the Pivot model without keeping both foreign_keys on the related table.

@taylorotwell @themsaid  can you please try to explain me what is the best way to deal with this? i tried to ask for help on larachat but none seems to have a real hint on this.

Best regards

**Comment by itapingu** [comment]
@taylorotwell saw your awesome keynote, how will nova treath this kind of relationship?

**Comment by driesvints** [comment]
Heya, thanks for submitting this. This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.
