### ISSUE TITLE
request()->fullUrl() returns wrong string. parse_url() does not show port

### ISSUE THREAD

**Issue by pmochine** [laravel/framework#24861]
- Laravel Version: 5.6.*
- PHP Version: 7.2.7

### Description:
I've written a package for multilangual subdomains. With that I'm redirecting urls. For example if you go to example.test it redirects to your given browsersettings/cookies to hu.example.test

Everything works fine until I'm using Browsersync. It adds a :3000 port to the url. Now my parsing of the url is not working correctly. 

The value of request()->fullUrl() is different with added port and is even buggy, because dd(request()->fullUrl())) gives the right value, but var_dump gives the wrong string. 

Just clone the case to see it for yourself. I've added a middleware where my problem is occuring.

I'm not sure which fault it is. Webpack mix or laravel. 

### Steps To Reproduce:
- Clone https://github.com/pmochine/request-wrong-url
- valet park (url: http://request-wrong-url [important for webpack mix])
- npm install
- npm run watch
- You should be on http://request-wrong-url.test:3000/ if everything went well
- And you should see the problem. The port is not parsed...
- Go to the middleware RequestTesting to play with the values. See what happens when you comment out var_dump and dd. 
- if you need more informations go on [stackoverflow](https://stackoverflow.com/questions/51360012/laravel-request-fullurl-not-returning-port)

### Expecting to get
For request on http://request-wrong-url.test:3000/
    
     var_dump(request()->fullUrl());  // "http://request-wrong-url.test:3000"
     dd(request()->fullUrl()); // "http://request-wrong-url.test:3000"

### But getting 

     dd(request()->fullUrl()); // ""//request-wrong-url.test:3000"

or

     var_dump(request()->fullUrl());  // "http://request-wrong-url.test"
     dd(request()->fullUrl()); // "http://request-wrong-url.test"

THANK YOU

**Comment by driesvints** [comment]
That's because Browsersync probably proxies the request to the url. The actual requests are still made on the url you're getting.
