### ISSUE TITLE
Executable bit set incorrectly on several files

### ISSUE THREAD

**Issue by ght** [laravel/framework#24867]
Affected Laravel Versions: current [master (7b2e13047)](https://github.com/laravel/framework/tree/7b2e13047), current [5.6 (23f6279)](https://github.com/laravel/framework/tree/23f6279)
### Description:
A lot of files have the executable bit set, among them several `.md` and `.json` files. Most if not all should not be marked executable.

### Steps To Reproduce:
`git clone https://github.com/laravel/framework.git && find framework -type f -executable`

**Comment by laurencei** [comment]
Closing as Taylor has decided in the PRs not to accept
