### ISSUE TITLE
str_plural helper unpredictable behaviour on kebab-case strings

### ISSUE THREAD

**Issue by howey-aus** [laravel/framework#24881]
- Laravel Version: 5.5.40
- PHP Version: 7.0

### Description:
calling str_plural on kebab-case strings works _almost_ all of the time. Eg. a simple compound like "shopping-list" correctly resolves to "shopping-lists", but "deviant-child" resolves to deviant-dhildren (note the oddly placed "d").

### Steps To Reproduce:
str_plural("shopping-list")
  _=> "shopping-lists"_
str_plural("deviant-child")
 _=> "deviant-dhildren"_

**Comment by KKSzymanowski** [comment]
It's not only for kebab case
```
>>> str_plural('Deviant child');
=> "Deviant Dhildren"
```
Second, it's rather an issue with doctrine/inflector than with Laravel framework.

**Comment by 36864** [comment]
https://github.com/doctrine/common/issues/758
