### ISSUE TITLE
Feature tests - JSON Calls returns 200 HTTP on non existent resources

### ISSUE THREAD

**Issue by nighthacker** [laravel/framework#24883]
- Laravel Version: 5.6.23
- PHP Version: 7.2.6

### Description:
In this test I am trying to call an endpoint **api/cars/{car}** with an identifier which does not exist in the database. The expected result is 404, but instead I get the code 200.
This example test returns always 200 and object with empty attributes.
Expected behavior:
should return 404 code on non existent resource because there is no resource in database with this identifier.

### Steps To Reproduce:
```
    public function test404OnNotExistentCar()
    {
        $this->withoutMiddleware();

        $this->json('GET', 'api/cars/303030303')
            ->assertStatus(404)
            ->assertJson([
                'message' => 'Resource not found',
                'success' => false,
                'status' => 404,
            ])
            ->assertJsonStructure([
                'message',
                'success',
                'status',
            ]);

    }
```

**Comment by sisve** [comment]
Is this the entire test? Do we need any controllers or routes to reproduce the problem? How do you do the model binding if you skip the middlewares? Do you expec t the binding middleware to throw a ModelNotFoundException which the exception helper converts to a 404?

**Comment by sisve** [comment]
I have no idea what to look for. Can you explain the actual problem in English in this issue? You say that "test returns 200 code and empty object. should return 404", but why whould it return 404? It's unclear from the test.

Are you sure you have ordered the routes in a correct order? You usually have these swapped around.

    Route::get('cars', 'Api\CarController@index');
    Route::get('cars/{car}', 'Api\CarController@show');

**Comment by nighthacker** [comment]
Regarding to routes order. 
The routing order does not affect how these rest enpoints works. You can even delete all other routes and leave only the one tested, with the same effect.

I have a suspicion that this method does not work correctly and may cause problems:
`$this->withoutMiddleware();`

**Comment by sisve** [comment]
It's a middleware that does the model binding. The same middleware also throws exceptions that are transformed into a HTTP 404. Disabling the model binding means that Laravel will construct a blank model and send to the action since you've type-hinted it as such. Try `dd($car)` in your model, and check if it's a real model or when that says that it doesn't exist.

**Comment by nighthacker** [comment]
yes you are right. 
$this->withoutMiddleware() disables ALL middlewares, when i turned off only Authenticate middleware it works as i expected.

**Comment by GabrielaSaldana** [comment]
You need to first check weather you are firing the right method from the browser developer tool console, sometimes your browser doesn't support some methods like PUT within chrome, and that causes to default over another method that has the same structure of "api/cars/{car} ". You can also try debugging with postman your endpoints.
