### ISSUE TITLE
Eloquent uses a removed method

### ISSUE THREAD

**Issue by multiwebinc** [laravel/framework#24886]
[DateTimeInterface::getTimezone()](http://php.net/manual/en/datetime.gettimezone.php) has been removed from PHP since 5.5.0, however [these lines](https://github.com/laravel/framework/blob/16983a689d15333e7101457c3e0c0d0b7da01d69/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L725-L727) still reference it.

Trying to execute this method will trigger a `Call to undefined method` error. See [this question on StackOverflow](https://stackoverflow.com/questions/51408323/call-to-undefined-method-datetime-gettimezone-error-laravel-carbon).

**Comment by staudenmeir** [comment]
`(new \DateTime)->getTimezone()` works on PHP 7.2.

**Comment by multiwebinc** [comment]
@staudenmeir @browner12 Hmm looks like [you're both right](https://3v4l.org/hKbmi)... I saw that question on StackOverflow and just assumed the PHP docs were correct without testing anything myself.

**Comment by multiwebinc** [comment]
Just to confirm, there was an error with the PHP docs. I submitted a bug report there and it has been updated now: http://php.net/manual/en/datetime.gettimezone.php.

**Comment by med-ezzairi** [comment]
I have the same issue, just did an update via composer, so my application is down, cause of:
`Call to undefined method DateTime::getTimezone() `

If any one could help on how to solve this.

**Comment by multiwebinc** [comment]
@med-ezzairi This issue is closed as it is not an issue with Laravel; it was an issue with the PHP docs at the time, which have since been updated. I would suggest you review your own code and make sure it's not a namespace problem (i.e. use `new \DateTime` instead of `new DateTime`) and if you still can't figure it out, post a question on StackOverflow with the minimum amount of  code needed to reproduce the error.
