### ISSUE TITLE
Paginator return data without  key “meta”

### ISSUE THREAD

**Issue by jasperchou** [laravel/framework#24893]
- Laravel Version: 5.5.40 - 5.6.*
- PHP Version: 7.1
- Database Driver & Version: mysql 5.7

### Description:

Paginator return data without  key “meta”, if i call method like "makeHidden" after invoke paginate().

### Steps To Reproduce:

query some data rows and use paginate(), and then call "makeHidden".

### Sugestion

i think it must return origin paginate struct. AbstractPaginator can wrap the result which return from method __call().

**Comment by staudenmeir** [comment]
Please post actual code.

**Comment by jasperchou** [comment]
actual code, return without "meta"
```
$customers = Customer::where('shop_id', $shop_id)
            ->paginate($pageSize)
            ->makeVisible(['created_at', 'updated_at']);
return new CollectionResource($customers);
```

**Comment by staudenmeir** [comment]
Use `tap()`:

```php
$customers = tap(Customer::where('shop_id', $shop_id)->paginate($pageSize))
    ->makeVisible(['created_at', 'updated_at']);
return new CollectionResource($customers);
```

**Comment by jasperchou** [comment]
now my code :
```
$customers = Customer::where('shop_id', $shop_id)
            ->paginate($pageSize);
$customers->getCollection()->makeVisible(['created_at', 'updated_at']);
```

I just suggest that Paginator should keep its struct which it return. Or you can explain why do it like that?

**Comment by staudenmeir** [comment]
This behavior is necessary for cases where you actually need the return value:

    $customers->getCollection()->pluck('id');

**Comment by jasperchou** [comment]
OK. Now I can understand. 

But i think it is more better that paginator keeps its struct. If someone wanna get the value, can code just like.
```
$customers->getCollection()->pluck('id');
```
Thank you very much for reply.
