### ISSUE TITLE
Collection.split() doesn't split to required amount of groups

### ISSUE THREAD

**Issue by wisammechano** [laravel/framework#24890]
- Laravel Version: 5.6
- PHP Version: 7.1.9
- Database Driver & Version: 5.7.19

### Description:
Say I want to split a collection of 15 items into 12 groups, the expected behavior is that I get chunked array of 12 items containing 1 item each with the last one containing 1 + the remainder 3

what I am getting is a collection of 8 items containing 2 items each with the last one having only 1 item

This behavior is not as described in the docs that it breaks into the specified number of groups

### Steps To Reproduce:
Collect a 15 items array and split by 12 groups, you will get 8 instead

**Comment by 36864** [comment]
>the expected behavior is that I get chunked array of 12 items containing 1 item each with the last one containing 1 + the remainder 3

That sounds counter-intuitive to me. I'd expect the first 3 groups to have 2 members each and the other 9 groups to have 1 member each.
