### ISSUE TITLE
Function onlyTrashed not found in Query\Builder

### ISSUE THREAD

**Issue by Kotzilla** [laravel/framework#24903]
- Laravel Version: 5.6.28
- PHP Version: 7.1.3
- Database Driver & Version: mysql 5.7

### Description:
i was create model with soft delete trait and `use SoftDeletes;` in model and relation
i try to call Model::withTrashed() and it's return error method not found. also trough still show record with all rows include not empty `deleted_at` 

### Steps To Reproduce:
create model and call in controller 

### Stacktrace
61
BadMethodCallException 
…/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php2816
60
Illuminate\Database\Query\Builder __call
…/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php1286
59
Illuminate\Database\Eloquent\Builder __call
…/app/Model/ModelServiceTrait.php384
58
App\Model\AddressService buildQuery
…/app/Model/ModelServiceTrait.php301
57
App\Model\AddressService paginate
…/app/Http/Controllers/User/AddressController.php38
56
App\Http\Controllers\User\AddressController index
…/vendor/laravel/framework/src/Illuminate/Routing/Controller.php54
55
 call_user_func_array
…/vendor/laravel/framework/src/Illuminate/Routing/Controller.php54
54
Illuminate\Routing\Controller callAction
…/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php45
53
Illuminate\Routing\ControllerDispatcher dispatch
…/vendor/laravel/framework/src/Illuminate/Routing/Route.php212
52
Illuminate\Routing\Route runController
…/vendor/laravel/framework/src/Illuminate/Routing/Route.php169
51
Illuminate\Routing\Route run
…/vendor/laravel/framework/src/Illuminate/Routing/Router.php665
50
Illuminate\Routing\Router Illuminate\Routing\{closure}
…/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php30
49
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…/app/Http/Middleware/Lang.php29
48
App\Http\Middleware\Lang handle
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php151
47
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
46
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php41
45
Illuminate\Routing\Middleware\SubstituteBindings handle
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php151
44
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
43
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php43
42
Illuminate\Auth\Middleware\Authenticate handle
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php151
41
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
40
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php67
39
Illuminate\Foundation\Http\Middleware\VerifyCsrfToken handle
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php151
38
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
37
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php49
36
Illuminate\View\Middleware\ShareErrorsFromSession handle
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php151
35
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
34
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php63
33
Illuminate\Session\Middleware\StartSession handle
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php151
32
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
31
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php37
30
Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse handle
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php151
29
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
28
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php59
27
Illuminate\Cookie\Middleware\EncryptCookies handle
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php151
26
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
25
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php104
24
Illuminate\Pipeline\Pipeline then
…/vendor/laravel/framework/src/Illuminate/Routing/Router.php667
23
Illuminate\Routing\Router runRouteWithinStack
…/vendor/laravel/framework/src/Illuminate/Routing/Router.php642
22
Illuminate\Routing\Router runRoute
…/vendor/laravel/framework/src/Illuminate/Routing/Router.php608
21
Illuminate\Routing\Router dispatchToRoute
…/vendor/laravel/framework/src/Illuminate/Routing/Router.php597
20
Illuminate\Routing\Router dispatch
…/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php176
19
Illuminate\Foundation\Http\Kernel Illuminate\Foundation\Http\{closure}
…/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php30
18
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…/vendor/fideloper/proxy/src/TrustProxies.php57
17
Fideloper\Proxy\TrustProxies handle
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php151
16
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
15
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php31
14
Illuminate\Foundation\Http\Middleware\TransformsRequest handle
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php151
13
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
12
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php31
11
Illuminate\Foundation\Http\Middleware\TransformsRequest handle
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php151
10
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
9
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php27
8
Illuminate\Foundation\Http\Middleware\ValidatePostSize handle
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php151
7
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
6
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php62
5
Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode handle
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php151
4
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
3
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php104
2
Illuminate\Pipeline\Pipeline then
…/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php151
1
Illuminate\Foundation\Http\Kernel sendRequestThroughRouter
…/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php116
0
Illuminate\Foundation\Http\Kernel handle
…/public/index.php55

**Comment by staudenmeir** [comment]
Please post the stacktrace.

**Comment by Kotzilla** [comment]
updated

**Comment by Jamesking56** [comment]
Can we see your Model code?

**Comment by Kotzilla** [comment]
My Model Code is

```
<?php namespace App\Model;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use SoftDeletes;
}
```

**Comment by Kotzilla** [comment]
in controller is nothing fancy just like this

```
<?php namespace App\Http\Controllers;
use Illuminate\Http\Request;
class PageController extends Controller
{
    public function index()
    {
        dd(\App\Model\Category::withTrashed());
        return view('frontend/page/home');
    }
}
```

**Comment by staudenmeir** [comment]
Please close the issue.
