### ISSUE TITLE
invalid .env dies with successful return code

### ISSUE THREAD

**Issue by jpuck** [laravel/framework#24914]
- Laravel Version: v5.6.23
- PHP Version: 7.1.3
- Database Driver & Version: N/A

### Description:

Our CI environment runs phpunit, which will return non-zero for any test failures. If all tests pass, then and only then should it return 0 and the build step is considered successful.

During bootstrapping if the .env file is invalid, laravel catches the `InvalidFileException` and dies with a successful return code 0. This completely kills phpunit in its tracks without running any tests, and that build step is counted as successful.  If you've got a full CI/CD pipeline, then you've just deployed untested code 😱

### Steps To Reproduce:

Create an invalid .env file, like unquoted values with spaces, e.g.

```bash
APP_ENV=loc al
```

Then run tests and check return code.

```bash
./vendor/bin/phpunit
```
> PHPUnit 7.1.5 by Sebastian Bergmann and contributors.
> The environment file is invalid: Dotenv values containing spaces must be surrounded by quotes.

```bash
 echo $?
```
> 0

This should return non-zero to indicate the error.

### Suggestions

https://github.com/laravel/framework/pull/24904 addressed this, but was closed because it also broke backwards compatibility on an unrelated line. I don't know why laravel is silently swallowing the `InvalidPathException`, but that's a separate issue. I think if that piece were removed, then it could be a successful solution to this issue.

IMO it shouldn't be `die`ing at all, but I'll leave that decision for smarter people than myself.

**Comment by decadence** [comment]
https://github.com/laravel/framework/pull/24904

**Comment by tillkruss** [comment]
Can you submit a PR to 5.7?
