### ISSUE TITLE
Issue with API documentation on Laravel.com

### ISSUE THREAD

**Issue by KevinCathcart** [laravel/framework#24928]
This is actually a bug in the laravel/laravel.com repository, but since that one does not have an enabled issue tracker, hopefully the right people see this issue here.

The API documents on laravel.com/api/* are missing some classes in the navigation tree. For example, go to https://laravel.com/api/master/index.html, and try to locate the `Illuminate\Auth\SessionGuard` class in the navigation tree. It simply is not there, although the class can be found if you search.

This was a bug in the Sami API documentation generator. see FriendsOfPHP/Sami#62, which was fixed in Sami 4.0.10 or newer.

Please investigate updating the Sami version used to generate this documentation, so as to avoid this issue.

**Comment by tillkruss** [comment]
Works for me: https://laravel.com/api/master/Illuminate/Auth/SessionGuard.html
