### ISSUE TITLE
Universal To not being overridden by Swift_Message to() method

### ISSUE THREAD

**Issue by vinnyvimto** [laravel/framework#24958]
- Laravel Version: 5.6
- PHP Version: 7.1

### Description:
I've recently updated a Laravel project to 5.6 from 5.2 and all the mail messages are sent via the Mail::send() method. I decided to make use of the Universal To feature for my development environment only to find it was still overriding my mail in production.

### Steps To Reproduce:
Add the following to the config/mail.php array
```
'to' = [
    'address' => env('MAIL_TO_ADDRESS', 'hello@example.com'),
    'name'    => env('MAIL_TO_NAME', 'Example'),
];
```

Send mail in a controller as below
```
Mail::send('emails._invoice', $data, function ($message) use ($email, $invoice, $order, $subject) {
    $message->to($email)->subject("Your {$subject}");
    $message->bcc(env('SALES_EMAIL'));
    $message->attachData($invoice->output(), "{$order->order_no}-invoice.pdf");
});
```

**Comment by vinnyvimto** [comment]
Right ok I seemed to remember reading somewhere it was overridden. [This issue ](https://github.com/laravel/framework/issues/9770) seems to suggest it used to overwrite but this must have changed.

Would be nice if we could get an option we can just set in an environment file to trigger it. IMO goes against the grain with how I usually configure stuff to have to edit a config file like so

```
if (config('app.env') !== 'production') {
    $array['to'] = [
        'address' => env('MAIL_TO_ADDRESS', 'hello@example.com'),
        'name'    => env('MAIL_TO_NAME', 'Example'),
    ];
}
```

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not for ideas, suggestions etc. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. You are able to open a ticket at https://github.com/laravel/ideas

Alternatively you are able to open a PR using the Contributions guidelines: https://laravel.com/docs/5.7/contributions#which-branch

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
