### ISSUE TITLE
array to string conversion 

### ISSUE THREAD

**Issue by virusismine** [laravel/framework#24955]
Hi, I'm facing issue when viewing below pages. Other's link is workable for me. Any idea? public/index.php/core/pages Error msg "Array to string conversion (View: path\resources\views\core\pages \index.blade.php)" line 77: {!! SiteHelpers::gridDisplay($row->$field['field'],$field['field'],$conn) !!}

**Comment by staudenmeir** [comment]
Welcome to Laravel! We are glad to have you as part of the community.

Unfortunately, GitHub is not an appropriate platform for general application issues. This is only for issues/bugs with the framework code itself.

Please close your issue, and instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

Laravel Slack (https://larachat.co)
Laravel.io Forum (https://laravel.io/forum)
Laracasts Forum (https://laracasts.com/discuss)
StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks!
