### ISSUE TITLE
URL::defaults are permanent and not fallback

### ISSUE THREAD

**Issue by Nowi5** [laravel/framework#24968]
- Laravel Version: 5.6.28
- PHP Version: 7.1.18

### Description:
As described here https://laravel.com/docs/5.6/urls#default-values Laravel provides the option of URL defaults. My understanding of default is that there are taken in case the parameter itself is not provided e.g. to the route helper. Unfortunately the default seems to behave like a constant instead of a default. Coding or Documentation is wrong. Means when I add a parameter to the route helper which exists already as URL Default it get attached as GET-Parameter instead of overwriting the default.

Can you please have a look?

### Steps To Reproduce:
1. Define a route with required paramter e.g. testid

```
Route::group( 'prefix' => 'test/{testid}/', 'as' => 'test.'], function () {    
        Route::get('/', 'HomeController@index')->name('home');  
});
```

2. Setup a middleware which set for this parameter a default, do not forget to register

```
<?php

namespace App\Http\Middleware;

use Closure;

use Illuminate\Support\Facades\URL;

class UrlDefaults
{
    /**
     * Handle an incoming request.
     *
     * @param \Illuminate\Http\Request $request
     * @param \Closure                 $next
     *
     * @return mixed
     */
    public function handle($request, Closure $next)
    {     

        URL::defaults(
           [
                'testid'  =>24,
           ] 
        );
      
        return $next($request);
    }
}
```

3. Call the route helper with and without this parameter
{{ route('test.home', ['testid' => 12]) }} --> https://xyz/test/24?testid=12
{{ route('test.home') }} --> https://xyz/test/24

**Comment by lagbox** [comment]
I can not reproduce this, I get the expected result.  Laravel 5.6.28 PHP 7.2.7

Not sure where `account` is coming from in your example output.

**Comment by Nowi5** [comment]
Corrected the example replace account by testid, but issue remains.

**Comment by lagbox** [comment]
Is your corrected example output the actual output you get now? Or the parameter is being applied only as a default fallback now?
