### ISSUE TITLE
Wrong PHPDoc : \Illuminate\Support\Collection::concat does not return $this

### ISSUE THREAD

**Issue by Naouak** [laravel/framework#24966]
`\Illuminate\Support\Collection::concat` has never returned `$this` (the instance on which the function was called) but it return a new instance instead. 

This can lead to hard to find bugs because push function that has the same behavior with one item does modify the current instance.

**Comment by staudenmeir** [comment]
Can you submit a PR?

**Comment by Naouak** [comment]
Done
