### ISSUE TITLE
API Resources wrong wrapper when using AnonymousResourceCollection->toResponse

### ISSUE THREAD

**Issue by westphalen** [laravel/framework#24974]
- Laravel Version: 5.5.2
- PHP Version: 7.2
- Database Driver & Version: mysql

### Description:
Utilizing a simple Resource to display a collection works fine when calling the `toArray` method.
But when using `toResponse` the data wrapping is handled differently, and the `$wrap` from the original Resource is not used. 

This seems to happen, as the original Resource is first wrapped in an `AnonymousResourceCollection`, which works fine with `toArray`. But when calling `toResponse` it is then further wrapped in a `ResourceResponse`, which will then retrieve `$wrap` from the `AnonymousResourceCollection` instead of the original Resource.

### Steps To Reproduce:

`php artisan make:resource Country`

In CountryResource.php:

```php
...
    public static $wrap = null;
...
```

In a controller or route:
```php
public function index(Request $request)
{
     $countries = Country::all();

     $resource = CountryResource::collection($countries);

     dd($resource->toArray($request));

     return $resource->toResponse($request);
}
```

You will see that the dd'd data is unwrapped.
Comment out the dd line, and you will see the response data is wrapped by `data`.

### Ideas

Let me know if I should submit a pull request for this, but this is just an idea that worked in my case:

`illuminate/http/Resources/Json/ResourceResponse.php`
```php
...
    /**
     * Get the default data wrapper for the resource.
     *
     * @return string
     */
    protected function wrapper()
    {
        // If the resource is an anonymous collection, use the wrapper from the resource it collects.
        if ($this->resource instanceof AnonymousResourceCollection) {
            return $this->resource->collects::$wrap;
        }

        return get_class($this->resource)::$wrap;
    }
...
```

**Comment by westphalen** [comment]
Should anyone else have this problem, you can of course do something like this in your `AppServiceProvider`:

```php

    /**
     * Boot services for the application.
     */
    public function boot()
    {
        AnonymousResourceCollection::wrap(null);
    }
```

This will, however, affect all of your application, where you might want control over each resource independently.

**Comment by driesvints** [comment]
This is because the `toArray` and `toResponse` have two different responsibilities. `toArray` is meant to transform the data itself and `toResponse` just prepares the resource before it's sent out.
