### ISSUE TITLE
\Illuminate\Foundation\Testing\TestResponse::assertJsonFragment is broken in laravel 5.6.28

### ISSUE THREAD

**Issue by Noogic** [laravel/framework#24978]
- Laravel Version: 5.6.28
- PHP Version: 7.1.3
- Database Driver & Version: 5.7.21 Homebrew

### Description:
With *phpunit 7.2.7*, I have a test which tries to assert that a response contains *players* in it (using `assertJsonFragment`) which it indeed has.

<img width="969" alt="captura de pantalla 2018-07-26 a las 18 10 10" src="https://user-images.githubusercontent.com/5868431/43274969-e2f58076-9100-11e8-82f0-60b40a8a2825.png">

This test has been successful until a recent update, which has changed the `"laravel/framework": "5.6.27"` to `"laravel/framework": "5.6.28"`.

By rolling back to `"laravel/framework": "5.6.27"` the test passes again, so is this exact versión, **5.6.28** that makes the **assertJsonFramgent** to fail.

### Steps To Reproduce:
- Create a test and call an endpoint returning `[{"data": "players": [{}]}]`
- Call to `$response->assertJsonFragment(['players']);`

> $response is of type `\Illuminate\Foundation\Testing\TestResponse`

For example, in *api.php*, create a route
```
Route::get('mytest', function () {
    return ['data' => ['players' => []]];
});
```

And, in phpunit:
```
/** @test */
    function my_test()
    {
        $this->signIn();

        $response = $this->getJson('api/mytest');
        $response->assertJsonFragment(['players']);
    }
```

And see how it works with laravel 5.6.27 but not with laravel 5.6.28

**Comment by bruno-rodrigues** [comment]
Is this bug back?
Laravel Framework 5.7.13

<img width="485" alt="screen shot 2018-11-16 at 7 08 35 pm" src="https://user-images.githubusercontent.com/7862345/48606426-b216a580-e9d3-11e8-8a62-975545426930.png">

**Comment by edtownend** [comment]
@bruno-rodrigues I think that's because residential_address is a key rather than a value?

**Comment by bruno-rodrigues** [comment]
There original test is:
```
$response->assertStatus(StatusCode::OK)->assertJsonFragment([
            'residential_address' => [
                'unit_number' => $newStreetNumber,
                'street_number' => $newStreetNumber,
                'street_name' => $newStreetName,
                'suburb' => $newSuburb,
                'state' => $newState,
                'postcode' => $newPostcode,
                'country_code' => 'AU',
                'country' => 'Australia',
            ]
        ]);
```

I have simplified it for example purposes.
