### ISSUE TITLE
Regex like rules in translation

### ISSUE THREAD

**Issue by amirmasoud** [laravel/framework#24977]
- Laravel Version: 5.6.x
- PHP Version: 7.1.x
- Database Driver & Version: MariaDB

### Description:
Is there any kind of regex like rules for translation file? something like:

```
'groups.*.name' => 'group name',
'groups.*.fields.*.label' => 'label'
```

instead of something like:

```
'groups.0.name' => 'group name',
'groups.1.name' => 'group name',
'groups.2.name' => 'group name',
...
```

### Steps To Reproduce:
---

**Comment by hvlucas** [comment]
I usually pass my request to a method that translates it for me.  
Something like this:  
```  
$msgs = [];
foreach(array_keys((array)$request->groups) as $key){
    $msgs["groups.$key.name.required'] = "Group #$key name field is required";
    ...
}
```
or this (depending how repetitive the rules are)
```
$to_decode = [
    'required' => 'field is required.',
    'max' => 'cannot be larger than :max',
    'array' => 'must be an array.', 
];
$msgs = [];
foreach($to_decode as $rule => $msg){
    foreach(array_keys((array) $request->groups) as $key){
        $msgs["groups.$key.name.$rule"] = "Group #$key name $msg";
    }
}
```

**Comment by hvlucas** [comment]
I agree, but you're probably going to have to submit a PR for that change to happen any time soon
