### ISSUE TITLE
Use withMiddleware with a middleware group

### ISSUE THREAD

**Issue by JValck** [laravel/framework#24980]
- Laravel Version: 5.6.24

### Description:
During tests I use the `WithoutMiddleware` trait to disable all middleware and bypass the authentication.
By disabling all the middleware, the `web` middleware group is disabled, but this is needed for using the `$errors` variable in the tests.

Is it possible to use the [withMiddleware](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php#L119) method with a middleware group? This would be handy.

### Steps To Reproduce:
- Use the `WithoutMiddleware` trait
- call `$this->withMiddleware('web');`
- Create a test to verify if the old data is loaded in a form.

**Comment by lagbox** [comment]
why not just disable the middleware you want to disabled?

**Comment by devcircus** [comment]
I assume a middleware be named with the same name as a group? If so, this could cause issues?

**Comment by JValck** [comment]
As @lagbox suggested I removed the `WithoutMiddleware` and simply disabled the middleware I wanted to disable.
The docs are completely missing any information about this functionality since L5.4
I'll close this issue as it is not a bug, but rather a vagueness of the docs.

**Comment by 36864** [comment]
Feel free to submit a PR to the docs if you think they're missing something.

**Comment by LvckyAPI** [comment]
If I write a test 

```php
$response = $this->withoutMiddleware('oidc-check-user-owns-decision-project')
        ->getJson(route('cmt.borlabs.list', ['decision' => $decision->uuid]));
```

and a group

```php
        // define middleware groups
        $middleware->appendToGroup('oidc-check-user-owns-decision-project', [
            AuthenticateOidcCookieMiddleware::class,
            CheckUserOwnsProjectMiddleware::class
        ]);
```

It's not possible to remove the whole group...
