### ISSUE TITLE
Severe bug in routes incl. optional placeholders

### ISSUE THREAD

**Issue by aimeos** [laravel/framework#24989]
- Laravel Version: 5.6.29
- PHP Version: 7.2.7
- Database Driver & Version: MySQL 5.7

### Description:

Routes with optional placeholders create wrong URLs

### Steps To Reproduce:

/detail/{id}/{pos?} with params [id=>1, pos=>2, val=>3] -> /detail/1/2?val=3 (correct)
/detail/{id}/{pos?} with params [id=>1, val=>3] -> /detail/1/3 (wrong)

**Comment by staudenmeir** [comment]
Judging from the source, I think this can be seen as the expected behavior. 

You can use `null` as a placeholder:

```php
['id' => 1, 'pos' => null, 'val' => 3]
['id' => 1, null, 'val' => 3]
```

**Comment by aimeos** [comment]
This renders optional attributes unusable because then they aren't optional any more. Routers in Symfony and other frameworks behave correctly.

**Comment by tillkruss** [comment]
Please feel free to submit a PR to change the behaviour.

**Comment by hwmaier** [comment]
Is seems that Laravel is completely oblivious to route parameter naming and ordering contrary to other frameworks. Took me by surprise too until I read this:

https://laravel.com/docs/5.6/routing#parameters-optional-parameters

> Route parameters are injected into route callbacks / controllers based on their order - the names of the callback / controller arguments do not matter.

This seems to apply both ways, route generation and controller argument passing.

**Comment by staudenmeir** [comment]
That's not entirely true for the route URL generation. Laravel first fills the parameters by name. Then it fills the remaining parameters (optional or not). The rest gets appended as the query string.

So these two arrays produce the same URL:

```php
['id' => 1, 'pos' => 2, 'val' => 3]
['pos' => 2, 'id' => 1, 'val' => 3]
```
