### ISSUE TITLE
Trouble Installing

### ISSUE THREAD

**Issue by rnirnber** [laravel/framework#24984]
I'm running "php artisan migrate" on a fresh install. I've created a blank database called "laracomm". This is using MySQL.

Screenshot:
https://image.ibb.co/nGNAG8/Untitled_1.jpg

**Comment by staudenmeir** [comment]
Welcome to Laravel! We are glad to have you as part of the community.

Unfortunately, GitHub is not an appropriate platform for general application issues. This is only for issues/bugs with the framework code itself.

Please close your issue, and instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

Laravel Slack (https://larachat.co)
Laravel.io Forum (https://laravel.io/forum)
Laracasts Forum (https://laracasts.com/discuss)
StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks!
