### ISSUE TITLE
Potential bug with scope and orWhere() 

### ISSUE THREAD

**Issue by fico7489** [laravel/framework#24996]
I have tables and models users(User) and verifications(Verification)

This is my code in controller : 

	DB::enableQueryLog();

	$rows = User::where(function($query){
	    $query->where('id', '=', 'a');
	    $query->orWhere('id', '=', 'b');
	})->get();

	$rows = User::where(function($query){
	    $query->where('id', '=', 'a');
	    $query->orWhereTest('id', '=', 'b');
	})->get();

	print_r(\DB::getQueryLog());

my scope look like this : 

    public function scopeOrWhereTest(Builder $builder, $column, $operator = null, $value = null)
    {
        $builder->orWhere($column, $operator, $value);
    }

Result is : 

	(
		[0] => Array
			(
				[query] => select * from `users` where (`id` = ? or `id` = ?)
				[bindings] => Array
					(
						[0] => a
						[1] => b
					)

				[time] => 4.07
			)

		[1] => Array
			(
				[query] => select * from `users` where (`id` = ? or (`id` = ?))
				[bindings] => Array
					(
						[0] => a
						[1] => b
					)

				[time] => 0.3
			)
	)

you can see that this : 

    select * from `users` where (`id` = ? or `id` = ?)

is not equal with : 

    select * from `users` where (`id` = ? or (`id` = ?))

For current example there is no problem, but when I combine more complicated query it is a problem, for. example this one : 

	$rows = User::where('id', 'like', '%%')
		->where(function($query){
			$query->where('id', '=', 'a');
			$query->orWhere('id', '=', 'b');
			$query->orWhere('id', '=', 'c');
			$query->orWhere('id', '=', 'd');
		})->get();

generates this query : 

    select * from `users` where `id` like ? and (((`id` = ? or (`id` = ?)) or (`id` = ?)) or (`id` = ?))

Is this normal behaviour? If yes can someone explain ?

**Comment by donnysim** [comment]
From the code, it is intended https://github.com/laravel/framework/blob/a9846cd953a25ded70be3ce42c43a16fb44ce589/src/Illuminate/Database/Eloquent/Builder.php#L949-L951

**Comment by sisve** [comment]
Your two sql statements are equivalent. They work identically, and you can confirm this by checking the query plan for them.

There's no problem here.

**Comment by fico7489** [comment]
Something is really bad, look at this : 
		
	$rows = App\Models\User::where(function($query){
			$query->where('first_name', '=', 'aaaaa');
			$query->orWhereTest('first_name', '=', 'bbbb');
		})->get();
		
vs
	
	$rows = App\Models\User::where(function($query){
		$query->where('first_name', '=', 'aaaaa');
		$query->orWhere('first_name', '=', 'bbbb');
	})->get();
	
	
gives :

		
	select * from `users` where (`first_name` = ? and (`first_name` = ?)) and `users`.`deleted_at` is null
	
vs
	
	select * from `users` where (`first_name` = ? or `first_name` = ?) and `users`.`deleted_at` is null
	
Model code : 

	public function scopeOrWhereTest(\Illuminate\Database\Eloquent\Builder $builder, $column, $operator = null, $value = null)
    {
        $builder->orWhere($column, $operator, $value);
    }

@sisve  how that could be normal ? Can someone try above query and confirm ?

**Comment by fico7489** [comment]
The problem is that eloquent is generating different query for the same eloquent methods, only difference is that method is called from scope in second case, but that should not matter how query is generated and that is by my opinion huge potential for bugs.

I have 3 rows in users table  : 

    id|first_name
	1|aaaaa
	2|bbbb
	3|cccc

and two eloquent queries : 

	$rows = User::where(function($query){
			$query->whereTest('first_name', 'like', 'aaaa');
			$query->whereTest('first_name', 'like', 'aaaa');
			$query->orWhereTest('first_name', 'like', 'bbbb');
			$query->orWhereTest('first_name', 'like', 'cccc');
			$query->whereTest('first_name', 'like', 'aaaa');
		})->get();
	echo 'count=' . $rows->count() . "\n";

vs

	$rows = User::where(function($query){
			$query->where('first_name', 'like', 'aaaa');
			$query->where('first_name', 'like', 'aaaa');
			$query->orWhere('first_name', 'like', 'bbbb');
			$query->orWhere('first_name', 'like', 'cccc');
			$query->where('first_name', 'like', 'aaaa');
		})->get();
	echo 'count=' . $rows->count() . "\n";

generated mysql : 

    select * from `users` where (((`first_name` like ? and `first_name` like ? or (`first_name` like ?)) or (`first_name` like ?)) and `first_name` like ?)

vs

    select * from `users` where (`first_name` like ? and `first_name` like ? or `first_name` like ? or `first_name` like ? and `first_name` like ?)

results : 

    count=1

vs 

    count=2

Scopes : 

	public function scopeWhereTest(Builder $builder, $column, $operator = null, $value = null, $boolean = 'and')
    {
        $builder->where($column, $operator, $value, $boolean);
    }

    public function scopeOrWhereTest(Builder $builder, $column, $operator = null, $value = null)
    {
        $builder->orWhere($column, $operator, $value);
    }
 

Can someone try this and confirm ?
This is tested on laravel 5.6.29
Laravel 5.2.x have much more problem with this, something is fixed in laravel 5.6.x but obviously not all...

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
