### ISSUE TITLE
Laravel query builders : Join the same table

### ISSUE THREAD

**Issue by hamedgasemi200** [laravel/framework#25002]
First of all i'm sorry for asking this question here

## **Question  :** 

I wanted to get posts by liked-post (`like_post` table) tags

let me make an example, Imagine you like a post on a website, This website has to show you related posts based on that post tags

I wrote this following code but the problem is when I get tags from liked posts, I want to find other posts that have the same tags!

```
$posts = DB::table('post_like')
    ->where(['like' => 1, 'post_like.user_id' => Auth::user()->id])
    ->join('post_tag', function ($join) {
        $join->on('post_tag.post_id', '!=', 'post_like.post_id');
    })
    ->get();
```

Returns liked posts tags

This is what i really want, But it causes an error

```
$posts = DB::table('post_like')
    ->where(['like' => 1, 'post_like.user_id' => Auth::user()->id])
    ->join('post_tag', function ($join) {
        $join->on('post_tag.post_id', '!=', 'post_like.post_id');
    })
    ->join('post_tag', function ($join) {
        $join->on('post_tag.tag_id', '!=', 'post_tag.tag_id');
    })
    ->get();
```

I'll be appreciated if you could answer my question.

@taylorotwell, @daylerees

**Comment by decadence** [comment]
Welcome to Laravel! We are glad to have you as part of the community.

Unfortunately GitHub is not an appropriate platform for general application issues. This is only for issues/bugs with the framework code itself.

Please close your issue, and instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

Laravel Slack (https://larachat.co/)
Laravel.io Forum (https://laravel.io/forum)
Laracasts Forum (https://laracasts.com/discuss)
StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks!
