### ISSUE TITLE
Changelog hasn't been updated since v5.6.27

### ISSUE THREAD

**Issue by rossbearman** [laravel/framework#25019]
The changelog hasn't been updated in several releases, despite there being a number of changes that should have been documented, including at least one breaking change that is requiring a release to fix (#24887, fixed in #24985). We're currently holding updates across applications as a result.

Is there any reason for this?

**Comment by tillkruss** [comment]
@themsaid had an accident. I'll update the changelog.

**Comment by rossbearman** [comment]
Thanks for clarifying and updating it, @tillkruss.

**Comment by themsaid** [comment]
Sorry guys, still feeling a bit weak. Updating it as we speak.

**Comment by carestad** [comment]
Same for the newly released update for the LTS version now (5.5.42). What has been fixed/updated?

**Comment by themsaid** [comment]
@carestad you can always check the commit history and submit a PR to update the changelog, laravel/framework is opensource.
