### ISSUE TITLE
Relationship create() method does not pass constructor arguments to Model

### ISSUE THREAD

**Issue by brysonreece** [laravel/framework#25011]
- Laravel Version: 5.6.2
- PHP Version: 7.2
- Database Driver & Version: mysql (latest)

### Description:
Having implemented:

```php
// User.php

...

public function tokens() {
    return $this->hasMany(Token::class);
}
```

```php
// Token.php

public function __construct(string $label) {
    parent::__construct();

    $this->label = $label;
}

...

public function user() {
    return $this->belongsTo(User::class);
}
```

I should be able to call ```$user->tokens()->create('My Token Label');```, however I'm greeted with 

```
Too few arguments to function App\Token::__construct(), 0 passed in /var/www/html/api/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php on line 656 and exactly 1 expected
```

---

Looking into this, it seems the issue lies [here](https://github.com/laravel/framework/blob/919eff201844db5c106145248cc02ac1ad671f31/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php#L656) on Line 656 of HasRelationships.php

---

### Steps To Reproduce:
Create Models as described above and try ```$user->tokens()->create('My Token Label');```

**Comment by brysonreece** [comment]
Looking at this, I get the same error even when trying
```php
$token = new Token('My Token Label');
$user->tokens()->save($token);
```

**Comment by devcircus** [comment]
Overriding the constructor on a model, you need to pass the attributes to the parent constructor.
```php
parent::__construct($this->attributes);
```

**Comment by brysonreece** [comment]
Even modifying my Token `__construct()` method as such:

```
public function __construct(string $label, $attributes = []) {
    parent::__construct($attributes);

    $this->label = $label;
}
```
fails with the same error.
