### ISSUE TITLE
Laravel Auth retrieve wrong/unexpected user

### ISSUE THREAD

**Issue by iorix4ever** [laravel/framework#25022]
I have a problem with my laravel application, it is like a nightmare to me 😁 I've tried everything I know to solve it, but unfortunately I don't have enough luck for that, so I posted this question for you guys to guide me through this, the issue is that the auth system sometimes retrieve the wrong user as a current user... I mean sometimes when I am working in the admin area and while submitting a form or refreshing the page the application shows a wrong auth user (not the one I've logged in with)...and sometimes it logging me out completely. I don't know what causes this, I've tried many theories but it didn't work.

Any ideas on how to solve this?

My laravel version is 5.6.1 and I deployed the application on siteground servers.

I'm using database-based session,  I also use multiple auth, one for regular users and the other for the admins.
I  tried to separate the users' table into two different tables one for regular users and the other for admin, however, it didn't solve the problem.

I've registered the multiple auth as the following

Config/auth.php

guards' => [
    'web' => [
        'driver' => 'session',
        'provider' => 'users',
    ],
    'api' => [
        'driver' => 'token',
        'provider' => 'users',
    ],
    'admin' => [
        'driver' => 'session',
        'provider' => 'admin',
    ],
],
'providers' => [
    'users' => [
        'driver' => 'eloquent',
        'model' => App\User::class,
    ],
    'admin' => [
        'driver' => 'eloquent',
        'model' => App\Admin::class,
    ],
],

And i'm doing route midleware for admin like this  :

`
Route::group(['middleware' => [ 'auth:admin']], function()
{     

}
`

and for retrieving current admin I use

`
$user = Auth::guard('admin') 
`
- Laravel Version: 5.6.1
- PHP Version: 7.1
- Database Driver & Version: Mysql

**Comment by mtvbrianking** [comment]
If you have two 'users' tables named `users` and `admins` respectively; then you admin guard is wrong

```diff
'guards' => [
   // ...
   'admin' => [
      'driver' => 'session',
-      'provider' => 'admin',
+      'provider' => 'admins',
   ],
],
```

But this is not a laravel issue; so am closing this

Refer to [multi authentication implementation](https://github.com/mtvbrianking/multi-auth-diy/commits/master).

**Comment by iorix4ever** [comment]
`
guards' => [
'web' => [
'driver' => 'session',
'provider' => 'users',
],
'api' => [
'driver' => 'token',
'provider' => 'users',
],
'admin' => [
'driver' => 'session',
'provider' => 'admin',
],
],
'providers' => [
'users' => [
'driver' => 'eloquent',
'model' => App\User::class,
],
'admin' => [
'driver' => 'eloquent',
'model' => App\Admin::class,
],
],
`

Hey mtvbrianking, I think it's not wrong, if you see the provider array

`
    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
        ],
        'admin' => [
            'driver' => 'eloquent',
            'model' => App\Models\Admin::class,
        ],
        // 'users' => [
        //     'driver' => 'database',
        //     'table' => 'users',
        // ],
    ],
`
it has  defined "admin" without "s" so it's not the problem, because the defination is the same.

**Comment by iorix4ever** [comment]
I have investigated more deeper and i found out that somehow the user A and user B getting the same session ID from the server and i think the  common thing between them is they are on the same local network.

**Comment by mmukhin** [comment]
I saw you or someone else post on another site that the problem was related to the server using a micro-caching mechanism, which would send back the cached session data. I had the same problem, and realized I was using varnish in front of my api. Just turned varnish off - and will pray the bug goes away!

**Comment by volpacchiotto** [comment]
I got such problem. Authenticator returned wrong users. Users have **GUID as ID**. The issue was add 
`protected $keyType = 'string';`
into User class. That indicates to laravel not to transform string GUID to integer ID.
