### ISSUE TITLE
"app()->makeWith(..." does not work with "app()->instance(..."

### ISSUE THREAD

**Issue by Eugene-Melbourne** [laravel/framework#25041]
- Laravel Version: 5.6
- PHP Version: 7.1

### Description:

function `app()->makeWith(... `
does not work with `app()->instance(...`

It should return prepared instance, but it creates a new object all the time.

It makes `Mocking` impossible. `Unit-testing` concept is not working.

**Comment by sisve** [comment]
The `makeWith` and `make` methods return new instances if you provide any parameters. How would Laravel know that the instance you've provided earlier is built using those same parameters?

**Comment by mfn** [comment]
> I think it should also ignore parameters if the instance is given.

This does not feel right.

Getting some kind of instance from the service container with dynamic parameters is always a bit of hybrid and can pose some challenges, one of them is the problem of mocking.

For tests, you can use a factory class which will then create your instance based on your parameters. Which means, you return a mock for the factory which then is responsible for creating your mocked actual class. Sounds a bit complex, but in practice it's easy:
```php
// Instead of
$instance = app()->makeWith(Concrete::class, ['your' => $args]);

// you can do
$instance = app(ConcreteFactory::class)->yourOwnMake($args);
```
You then mock `ConreteFactory` and return via `yourOwnMake` whatever you want, and it can also be dynamic based on your `$args`

**Comment by sisve** [comment]
> 1. Make does not support parameters in laravel 5.6

Yes, it does.

https://github.com/laravel/framework/blob/56a58e0fa3d845bb992d7c64ac9bb6d0c24b745a/src/Illuminate/Container/Container.php#L592-L602

**Comment by Eugene-Melbourne** [comment]
@mfn, thank you. 

1) Your solution would work.

2)  Your solution does not omit the fact that makeWith works different from normal Container behaviour. It is breaking the pattern.

3) I don't think that making a factory only for testing is the best practice. [Many people think](https://softwareengineering.stackexchange.com/a/86845/312049)  that  `you shouldn't do anything only because it is needed for testability`.

**Comment by Eugene-Melbourne** [comment]
@sisve, I'm sorry. You are right. Thank you.

**Comment by Eugene-Melbourne** [comment]
What is going on? Why the issue is closed when the bug persists?

**Comment by devcircus** [comment]
I believe Taylor has commented a similar issue before saying that this is the expected behavior. I'll try to track it down.

**Comment by basepack** [comment]
Is there any news on this one?

**Comment by mfn** [comment]
@basepack nope, and nothing is planned. If you've a specific issue, please provide more information what your problem is and what you need help with.

**Comment by sisve** [comment]
That sounds like something that should be part of your test's setUp() method, not the service provider.

**Comment by basepack** [comment]
Thanks for your input @sisve, but: Yes, and that is exactly what not is working.
If you have a working setUp() method where you mock a service class, I will be gratefull for it. 

But keep in mind this scenario:
```php
// AppServiceprovider.php
if ( $this->app->environment( 'testing' ) ) {
	app()->instance(
		ApiService::class,
		\Mockery::mock( ApiService::class )->makePartial()
	);
}
```

```php
// SomeTest.php

public function it_can_call_a_service_which_uses_api_service(){
    $anotherService = app('AnotherService::class');

   // This service calls ApiService which is _correctly_ mocked at this stage
   // If you swap the ServiceProvider implementation to the setUp() method it will _not_ work
   $anotherService->callApiService(); 
}
```

I believe it will work if you use `setUp()` and then test/call `ApiService` directly, however if you are testing `AnotherService` which uses the IOC container to inject `ApiService`. It will not get the mocked version, but the real implementation.
So thats why we need this service provider hackish way, which I do not like.

**Comment by mfn** [comment]
I'm using mocked services in `setUp` all the time, no problems.

How does your `setUp` look exactly?

How does the code, which resolves the `ApiService` look like (or the constructor of `AnotherService`)?

**Comment by basepack** [comment]
Wow, if that does it for you, you will save my life with this one!

Here it comes:
```php
// AnotherService.php
class AnotherService {

	private $apiService;

	public function __construct( ApiService $apiService )
	{
		$this->apiService = $apiService;
	}

	public function initSubscription( )
	{
		$this->apiService->createAccount();
	}
}

// ApiService.php
class ApiService {

	public function createAccount( )
	{
		// Call the API
	}
}


// AnotherServiceTest.php
class AnotherServiceTest extends TestCase
{
	/** @var AnotherService*/
	protected $anotherService;

	/** @var Mockery\Mock */
	protected $mockApiService;

	public function setUp()
	{
		parent::setUp();

		$this->anotherService = app( AnotherService::class );

		app()->instance(
			ApiService::class,
			Mockery::mock( ApiService::class )->makePartial()
		);

		$this->mockApiService = app( ApiService::class );

	}

	public function it_can_call_a_service_which_uses_api_service(){
		// arrange
		// ...

		// expect
		$this->mockApiService
			->shouldReceive( 'createAccount' )
			->once();

		// act
		$this->anotherService->initSubscription();
	}
}
```

**Comment by sisve** [comment]
My first thought is that you have already resolved and cached an AnotherService somewhere. Is it perhaps a singleton registered from within your service provider? Then it would keep using whatever reference to ApiService it had from the beginning, and not know about any mocked instances introduced in the Container at a later time.

**Comment by basepack** [comment]
@sisve, no it is never registered in a service provider. I thought this was exactly why this issue was created for. Because this is unexpected behavior. 
Maybe I should mention https://github.com/laravel/framework/issues/19450 where this is also described.

**Comment by mfn** [comment]
The order in your `setUp` is wrong:
- your first create an instance of `AnotherService` _which_ uses `ApiService` so it will immediately create non-mocked instance of `ApiService` for that service
- only a line later your set your mocked instance

Switch the two lines and it should work.

**Comment by basepack** [comment]
@mfn, wow never expected something that obvious! Will you believe I worked a full day on this one..
So in essence @sisve was right, expecting an already cached instance of `ApiService` when he says:

> My first thought is that you have already resolved and cached an AnotherService somewhere.

**Comment by Sti3bas** [comment]
You can bypass this with `offsetSet`:
```php
app()->makeWith(Concrete::class, ['foo' => 'bar']);

// in test
app()->offsetSet(Concrete::class, $mock);
```

**Comment by mfn** [comment]
> Use bind() instead of instance()

That's interesting because I don't see anything in your example which would require that; IMHO `$this->app->instance(OrdersRequest::class, $orders_mock);` should work equally well, no?

**Comment by trip-somers** [comment]
I had been using `$this->mock()` in my tests, but it wasn't properly mocking an `app(ClassToMock::class. ['param' => $param])` instance. I switched to `Mockery::mock()` + `bind()` and the mocking worked as expected.
