### ISSUE TITLE
How can i append attribute at run time in laravel 5.0

### ISSUE THREAD

**Issue by sunilsharma0** [laravel/framework#25045]
I am trying to append attribute at run time in Laravel version 5.0 using setAppend(array) function in query while using relationship with other model.
```
 $result = InspectionOrders::with(['technician'=>function($query){
                $query->select('tech_id','profile_pic_url',
                        'tech_phone_no','tech_lat','tech_long',
                        DB::raw('concat(tech_first_name ,tech_last_name) as tech_full_name'))->setAppends(['experience','num_orders_inspected']);
            }])
```

As in above query i used **with** function for relationship. I added a attribute function in Technician model that i want to call at run time in above query.
Thanks.

**Comment by staudenmeir** [comment]
What type of relationship is `technician`?

**Comment by sunilsharma0** [comment]
belongsTo

**Comment by staudenmeir** [comment]
Use `setAppends()` after executing the query:

```php
$result = InspectionOrders::[...]->get();
$result->pluck('technician')->each->setAppends(['experience','num_orders_inspected']);
```

**Comment by sunilsharma0** [comment]
Call to undefined method Illuminate\\Database\\Eloquent\\Collection::pluck()

**Comment by staudenmeir** [comment]
What's your Laravel version?

**Comment by sunilsharma0** [comment]
laravel 5.0

**Comment by staudenmeir** [comment]
Sorry, you have to use `lists()` instead.

**Comment by sunilsharma0** [comment]
In which place?

**Comment by staudenmeir** [comment]
Sorry, the whole solution only works on current Laravel versions. This should work for you:

```php
$results = InspectionOrders::[...]->get();
foreach($results as $result) {
    $result->technician->setAppends(['experience','num_orders_inspected']);
}
```

**Comment by sunilsharma0** [comment]
Now it is working fine .
Thanks buddy.
