### ISSUE TITLE
Make addFailure function in Illuminate\Validatio\Validator public please.

### ISSUE THREAD

**Issue by test82987** [laravel/framework#25040]
- Laravel Version: 5.6
- PHP Version: 7.1
- Database Driver & Version:

### Description:

addFailure function in Illuminate\Validatio\Validator  is protected instead of being public

Thus it is impossible to add custom failure to the Validator.

Instead users need to go long way, adding custom error messages, taking care of translation,  ":attribute" naming and http statuses manually.

**Comment by tillkruss** [comment]
Feel free to submit a PR.
