### ISSUE TITLE
[5.6] Passing Request through a route causes missing required parameters

### ISSUE THREAD

**Issue by ahinkle** [laravel/framework#25056]
- Laravel Version: 5.6.29
- PHP Version: 7.2.7

### Description:
I inherited a poorly written app months ago. We have it upgraded to Laravel 5.6. We have a form that takes the `GET` `Request` data from a page and passes them from Step 1 to Step 2. So the variables are inserted into the URL such as /`refer/step_2?name='john'&phone="9999999999" etc.`

--

With [recent releases](https://github.com/laravel/framework/releases), I've seen a lot of changes with the routing system. We have a route that passes the request data via:
`return redirect()->route(‘step_2’, $request);`

This return has worked for months (with 5.6). After an unrelated deployment today, the tests failed in Travis. With the error 
`Missing required parameters for [Route: step_2] [URI: refer/step/2]`

After hours of debugging our unrelated deployment thinking that is where it came from (😅), I reverted and was getting the same issue.
So I changed 
`return redirect()->route(‘step_2’, $request);`
to:
`return redirect()->route(‘step_2’, $request->all());`

and it worked. Seems to be like an app breaking change from a recent release -- not sure which PR unfortunately.

**Comment by staudenmeir** [comment]
What's the route's declaration (`Route::get(...)`)?

**Comment by ahinkle** [comment]
```
Route::prefix('refer')->group(function () {
    // Step 1
    Route::get('/', ['uses' => 'ReferController@step_1', 'as' => 'step_1']);
    Route::post('/', ['uses' => 'ReferController@step1_request']);
    // Step 2
    Route::get('step/2', ['uses' => 'ReferController@step_2', 'as' => 'step_2']);
    Route::post('/step/2', ['uses' => 'ReferController@step2_request']);
    // Step 3 
    Route::get('step/3', ['uses' => 'ReferController@step3', 'as' => 'step_3']);
    Route::post('step/3', ['uses' => 'ReferController@step3_request']);
});
```

**Comment by staudenmeir** [comment]
So it doesn't have any parameters?

**Comment by staudenmeir** [comment]
Is the error coming from `RouteUrlGenerator::to()`? What's the result of `dd($uri);` in there?

What's the result of `dd($request->all());`?

**Comment by ahinkle** [comment]
I created a small laravel project and couldn't get it to replicate.. I'll keep trying to see if I can get to replicate. Closing for now.
