### ISSUE TITLE
Custom rules and Closures are not called if value is empty

### ISSUE THREAD

**Issue by alfonsobries** [laravel/framework#25067]
- Laravel Version: 5.7
- PHP Version: 7.2
- Database Driver & Version: mysql

### Description:
I'm trying to create a custom validation rule or at least use a closure custom validation but I cannot achieve that the function was called when the request value is empty.

### Steps To Reproduce:

1. Create a closure validation rule
2. Send an empty value for the attribute
3. The function is ignored

Example:
```
<?php
$this->validate($request->all(), [
  'users.*.email' => function($attribute, $value, $fail) {
      dd("This is not called when the $value (user[0].email = '') is empty");
      // My custom condition 
      // for example only require the email if the user is admin.
    }
]);

```

*Notice that in my real case im validating that the value is in another array in the same request, i mean it will be required based on the value of every item, so some rows will be required and some others not, otherwise i will make a condition like:
`  'users.*.email' => (/*condition*) ? 'required' : ''`

**Comment by alfonsobries** [comment]
btw i create this PR that is useful to solve this kind of rules:
https://github.com/laravel/framework/pull/25066

**Comment by alfonsobries** [comment]
I find that i need to use the extendImplicit function this solves my problem 
Validator::extendImplicit('foo', function ($attribute, $value, $parameters, $validator) {
    return $value == 'foo';
});

Its possible to achieve using validation closures?

**Comment by surgiie** [comment]
@alfonsobries same issue here. Wondering why it doesnt call when the request input is empty.
