### ISSUE TITLE
Broadcast channel routes are very greedy when matching parameter routes

### ISSUE THREAD

**Issue by valorin** [laravel/framework#25065]
- Laravel Version: 5.6.15
- PHP Version: 7.2.8

### Description:

I'm not sure if this is a bug or not, but broadcast channel routes are are very greedy when matching parameter routes. Consider the route of `user.{id}` -> you would expect it to match `user.<id>` but not `user.<id>.<random>`, however it matches both correctly.

It happens like this:

On [Broadcaster line 56](https://github.com/laravel/framework/blob/5396ac124d075de22d7599e55bb72590e7ff313c/src/Illuminate/Broadcasting/Broadcasters/Broadcaster.php#L56), the channel matching logic converts the channel route definition into a simple string wildcard match: `user.*`, which is greedy and allows it to match `user.<id>.<random>`.
```
if (! Str::is(preg_replace('/\{(.*?)\}/', '*', $pattern), $channel)) {
```

While this sounds like it still matches the route definition, you'd expect it to try and authenticate with `<id>.<random>`, but instead all it gets is `<id>`. This is due to [Broadcaster.php line 136](https://github.com/laravel/framework/blob/5396ac124d075de22d7599e55bb72590e7ff313c/src/Illuminate/Broadcasting/Broadcasters/Broadcaster.php#L136), which uses `preg_match` to extract the parameters, ensuring the `.` is a delimiter and not included.
```
preg_match('/^'.preg_replace('/\{(.*?)\}/', '(?<$1>[^\.]+)', $pattern).'/', $channel, $keys);
```

The result is the channel auth callback receives only `<id>` and the `.<random>` is completely ignored. 

The irony is that this functionality works perfectly for what I want to do (limiting events to unique browser tabs), but it's undocumented and feels a bit like a bug as the matched route and authenticated parameters don't match up. I think it either needs to be documented or fixed, to remove confusion.

### Steps To Reproduce:

In `routes/channels.php`:
```
Broadcast::channel('user.{id}', function (User $user, $id) {
    return (int) $user->id === (int) $id;
});
```
In your Javascript:
```
Echo.private('user.'+userId+'.'+random)
```

**Comment by tillkruss** [comment]
Ignoring dot seems reasonable. Would you mind submitting a PR?

**Comment by netpok** [comment]
I would rather consider a solution similar to how the routes are handled.

Meaning:
 - matching with regex using `/([^.]+)/` so at least one character that's not a dot, but maybe we could allow zero too
 - add a `where` method to the broadcaster to allow setting custom regex
 - add a notification to the docs that the `.*` regex can be only used as last part of the channel name

**Comment by driesvints** [comment]
@valorin is this still a problem for you on the latest framework release?

**Comment by valorin** [comment]
@driesvints I'm not working for that company any more, so don't have access to the codebase to test it out.  I can probably make a test app if you need me to though.

**Comment by driesvints** [comment]
Nothing urgent. Anyone's free to help out here if they want to pitch in.

**Comment by taylorotwell** [comment]
This feels like more of an opinion about how matching should work rather than a bug.
