### ISSUE TITLE
PHPDoc type dynamic is not supported, change to mixed

### ISSUE THREAD

**Issue by hordijk** [laravel/framework#25061]
Several classes are using `@param  dynamic  $parameter` in the PHP Doc for splat operators. See https://github.com/laravel/framework/search?q=%22%40param++dynamic%22&type=Code

The type `dynamic` is not supported. At least it's not mentioned in https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#appendix-a-types or http://docs.phpdoc.org/guides/types.html.

The class `Illuminate\Http\Resources\Json\JsonResource` does use `@param  dynamic` as shown in the snippet below:

https://github.com/laravel/framework/blob/5396ac124d075de22d7599e55bb72590e7ff313c/src/Illuminate/Http/Resources/Json/JsonResource.php#L49-L69

Instead of `dynamic` the type should be changed to `mixed`.

Issue found while using PHPStan

If you use [PHPStan - PHP Static Analysis Tool](https://github.com/phpstan/phpstan) you might receive 
a warning `Parameter #1 ...$parameters of static method Illuminate\Http\Resources\Json\JsonResource::make() expects Illuminate\Http\Resources\Json\dynamic, <Class> given`

Within the Laravel framework several notations are used to document splat operators:
- https://github.com/laravel/framework/blob/5396ac124d075de22d7599e55bb72590e7ff313c/src/Illuminate/Support/helpers.php#L548-L554
- https://github.com/laravel/framework/blob/5396ac124d075de22d7599e55bb72590e7ff313c/src/Illuminate/Support/helpers.php#L1048-L1057

Please note some discussions on how to document the splat operator:
- [Supporting the splat operator in function commenting sniff #1807](https://github.com/squizlabs/PHP_CodeSniffer/issues/1807)
- [Squiz.Commenting.FunctionComment doesn't work with variadic arguments #1652](https://github.com/squizlabs/PHP_CodeSniffer/issues/1652)
- https://github.com/phpDocumentor/fig-standards/issues/121#issuecomment-168749811

It seems name with `...` and without are supported in PHP Doc for the variadic arguments and `...` is preferred?
 
Please let me know whether I can change dynamic to mixed and create a pull request to change this.

**Comment by tillkruss** [comment]
@GrahamCampbell: Why are we using "dynamic"? Thoughts on this?

**Comment by driesvints** [comment]
You're free to create a PR and back it up with the above explanation. Just make sure you add it to the PR comment.
