### ISSUE TITLE
Adding custom validation failure with an auto translated message

### ISSUE THREAD

**Issue by Eugene-Melbourne** [laravel/framework#25068]
- Laravel Version: 5.6
- PHP Version: 7.1
- Database Driver & Version:

### Description:

[Based on this stackoverflow question](https://stackoverflow.com/questions/51663977/laravel-custom-validation-failure-with-a-nice-message)

We need a way to generate error message based on `\resources\lang\en\validation.php` configuration.
this functionality is sitting in addFailure function. But this function is protected.

So instead of doing:

     $validator->addFailure('my_number', 'not_in', []);

Laravel users need to do:

    $validator->errors()->add('my_number', __('validation.not_in', ['attribute' => __('validation.attributes.my_number')]));

Actually it is not the same because it will ignore `custom` section of validation.php.

Can we give an option for people to make it elegant way?

**Comment by tillkruss** [comment]
Please feel free to submit a PR.
