### ISSUE TITLE
Returning Null while accessing some fields of table

### ISSUE THREAD

**Issue by sunilsharma0** [laravel/framework#25062]
```
public function getTechStatusAttribute() {
       $a = $this->is_report_generated;  // returning null 
       $b = $this->order_status;   // returning exact value
       $c =$this->tech_journey;  // returning exact value
      return $a.$b.$c;
}
```
I am trying to append a new field with name **tech_status** . But i am surprised that i can access **order_status** and **tech_journey** but not able to access **is_report_generated**. It returns NULL.
### Table Structure

**tech_journey** | smallint(6) |   |   | No | 0 | 
**order_status** | varchar(255) | utf8_unicode_ci |   | Yes | NULL 
**is_report_generated** | varchar(255) | utf8_unicode_ci |   | Yes | NULL
is_report_generated column is also indexed.

**Comment by staudenmeir** [comment]
What's the result of `dd($this->attributes);`?

**Comment by sunilsharma0** [comment]
Thanks problem solved.

**Comment by staudenmeir** [comment]
Please close the issue.
