### ISSUE TITLE
Class aliases do not work when checking policies

### ISSUE THREAD

**Issue by jamiehd** [laravel/framework#25074]
- Laravel Version: v5.6.28
- PHP Version: PHP 7.1.10
- Database Driver & Version: 

### Description:
Class aliases aren't used when checking policies

### Steps To Reproduce:
In config/app.php set a class alias for a model
` 'aliases' => ['MyModel' => App\MyModel::class ]`

Create a policy for `App\MyModel` and add it to `AuthServiceProvider`

In a view use
 `@can('create', MyModel::class)`

It will return false even if it is authorized by the policy as Laravel does not treat them as the same class.

**Comment by tillkruss** [comment]
Yeah, that doesn't work.

**Comment by jamiehd** [comment]
I know it doesn't work. That's why I opened the issue...

**Comment by tillkruss** [comment]
And because it's a feature request and not a bug, I closed it 😉

Please feel free to submit a PR, but I doubt Taylor will merge that.

**Comment by devcircus** [comment]
An alias is used when resolving something out of the container. You can alias it and still resolve it. That's not what is happening when you use the @can method. It just checks if that string exists in an array, it doesn't touch the container.
