### ISSUE TITLE
No way of asserting subject in mail testing

### ISSUE THREAD

**Issue by TheSachin** [laravel/framework#25100]
- Laravel Version:5.6
- PHP Version:7.12
- Database Driver & Version: Mysql 5.7

### Description:
I am not able to find way of verifying the subject of mail

**Comment by derekmd** [comment]
If you're talking about `MailFake` testing on mailable objects, call `build()` to fill the `Mailable@subject` variable. e.g.,

```php
Mail::assertQueued(OrderConfirmation::class, function ($mail) use ($order) {
    $this->assertEquals('Invoice #12345 has been paid!', $mail->build()->subject);

    return $mail->order->is($order);
});
```
