### ISSUE TITLE
Non-static method 'middleware' should not be called statically

### ISSUE THREAD

**Issue by xiaoxing598** [laravel/framework#25118]
- Laravel Version: 5.4.36
- PHP Version:5.6
- Database Driver & Version:5.7

### Description:
I am writing code using IDE (phpstorm), I get a hint in several files "Non-static method 'middleware' should not be called statically", why should I tolerate this error, although the program is runnable?

The use of this kind of error makes me feel awkward. What is the purpose of this design? Is it possible to allow this encoding in the new version of PHP?

```
Non-static method 'middleware' should not be called statically less... (Ctrl+F1) 
Inspection info: Dynamic class method called as static.
```

**Comment by tillkruss** [comment]
That sounds like PHPMD complaining.

**Comment by xiaoxing598** [comment]
@tillkruss Maybe you can give me an explanation, I will thank you very much!

**Comment by xiaoxing598** [comment]
@tillkruss I want to know if the PHP syntax specification is recommended for this encoding method? Even if you can write code like this, is there really no problem?
