### ISSUE TITLE
$table->bigInteger('id')->autoIncrements()->change(); not work

### ISSUE THREAD

**Issue by erlangp** [laravel/framework#25113]
$table->bigInteger('id')->autoIncrements()->change(); 
expected: Auto Increment added to the id column.
result: statement above not add Auto Increment to the id column.
migration run successfully without error.
please help
thanks

**Comment by erlangp** [comment]
mysql
laravel 5.6

**Comment by staudenmeir** [comment]
Please post the whole migration and the migration that creates the table.

**Comment by erlangp** [comment]
public function up()
    {
        Schema::create('table_a', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->datetime('tgl');
            $table->integer('user_id')
                    ->unsigned();
            $table->timestamps();
        });
    }

    public function down()
    {
        Schema::dropIfExists('table_a');
    }

**Comment by erlangp** [comment]
// . . .

    public function up()
    {
        Schema::create('table_a', function (Blueprint $table) {
            $table->bigInteger('id')
                    ->autoIncrements()
                    ->change();
        });
    }
    
    // . . .

**Comment by erlangp** [comment]
@staudenmeir

**Comment by staudenmeir** [comment]
Why do you want to add `AUTO_INCREMENT` to the column? You already do that with `bigIncrements()`.

**Comment by erlangp** [comment]
@staudenmeir ow sorry.. i mean bigInteger.. i just edit my comment

**Comment by staudenmeir** [comment]
You have to add a `PRIMARY` index first:

```php
public function up()
{
    Schema::table('table_a', function (Blueprint $table) {
        $table->primary('id');
    });
    Schema::table('table_a', function (Blueprint $table) {
        $table->bigInteger('id', true)->change();
    });
}
```

**Comment by erlangp** [comment]
thank u very much sir :D
