### ISSUE TITLE
Model primary key is set to zero

### ISSUE THREAD

**Issue by elinxer** [laravel/framework#25125]
- Laravel Version: 5.5.×
- PHP Version: 7.2
- Database Driver & Version:

### Description:
When the table model does not have an auto-increment field and the single model sets primary_key, the model query results automatically set the primary_key field of the last data to zero

**Comment by staudenmeir** [comment]
Add this to your model:

```php
public $incrementing = false;
```

**Comment by elinxer** [comment]
@staudenmeir yet, thanks
