### ISSUE TITLE
The page has expired due to inactivity. Please refresh and try again.

### ISSUE THREAD

**Issue by wimurk** [laravel/framework#25127]
- Laravel Version: 5.6.29
- PHP Version: 7.2

### Description:
The issue occurs when a user logs in (all good here) and then logs out, gets redirected to the `/home` page. User goes back to the login page `/login` and logs back in. 

### Steps To Reproduce:
This might be a server problem for it only can be reproduced in production. 
- The user logs in using the default auth with email password
   - email
   - password
   - `@csrf`
- The logs out and gets redirected to `/home`
- User goes back to login page and tries to log back in
- Error occurs with token expired

 - step 1 https://i.gyazo.com/717ee7719c34a76dcd17e02d3f04351d.mp4
- step 2 https://i.gyazo.com/1307ebfa8111e42a58dcd0dc9f71620d.mp4

First step all works fine. Step 2 it just crashes. Somehow the token does refresh but is not passed to the `$request->session()->token()`

Inside the file `Illuminate\Foundation\Http\Middleware\VerifyCsrfToken::class`
The function `tokensMatch() line 121` the tokens are always diffrent. 
When the user goes back and refreshes the page the token is changed. I have tried to empty the cache, disabled the cache. Changed cache driver to every possible driver there is. Doens't work. I have this issue on almost 30 domains now and all happened upgrading to the `5.6.*` version

### UPDATE
After weeks of searching i found the issue and why it only happened on the production server. 
The issue is OP cache with php 7.2+. Local i don't have OP cache enabled. I disabled the OP cache on the production and it worked like a champ. It made the site also a lot faster using the default laravel cache.

**Comment by sisve** [comment]
> I disabled the OP cache on the production and it worked like a champ. It made the site also a lot faster using the default laravel cache.

Could you clarify what you mean with "OP cache"? PHP comes with [opcache](https://secure.php.net/manual/en/intro.opcache.php), but Laravel has nothing to replace this. Is this the cache you say is responsible for the issues?

**Comment by wimurk** [comment]
@sisve yes the php op cache causes the issue. Some how php caches the csrf token while the session is already refreshed. I don't know if the new php version conflicts with the csrf token. The issue can be closed if it can't be fixed within laravel.
