### ISSUE TITLE
Relationships in eloquent when using prefix's

### ISSUE THREAD

**Issue by samloft** [laravel/framework#25123]
- Laravel Version: 5.6.29
- PHP Version: 7.1.17
- Database Driver & Version: SQLSRV 5.2.0

### Description:

When having 2 database connections, one with a prefix and one without, doing a whereHas breaks the query (Appending the prefix when it shouldn't, not once, but twice).

For the example, using the prefix salesoffice_

### Steps To Reproduce:

In database.php, add two connections (Same server + database), one with a prefix and one without.

Two models, one pointing to the default connection, and one pointing to the connection with the prefix. example, one Orders and one OrderBook (Orders being the model with the prefix).

Add a function into Orders

`public static function outstanding() {
        return (new Orders)->whereDate('allocated_at', '<=', Carbon::now()->subHours(1))->whereHas('OrderBook', function($query) {
            $query->where('completed_at', null);
        })->get();
    }`

This returns the query 

`select * from [salesoffice_orders] where cast([allocated_at] as date) <= 2018-08-07 08:22:09.295 and exists (select * from [salesoffice_salesoffice_scheme].[scd_order_book] where [salesoffice_orders].[order_no] = [salesoffice_scheme].[scd_order_book].[base_order] and [completed_at] is null)`

But the table scd_order_book is using the connection that does NOT have a prefix, so the query should be

`select * from [salesoffice_orders] where cast([allocated_at] as date) <= 2018-08-07 08:22:09.295 and exists (select * from [scheme].[scd_order_book] where [salesoffice_orders].[order_no] = [scheme].[scd_order_book].[base_order] and [completed_at] is null)`

**Comment by staudenmeir** [comment]
That's currently not supported: #4649
