### ISSUE TITLE
laravel json translations cannot use numerical indexes greater than "099"

### ISSUE THREAD

**Issue by lucasecci0** [laravel/framework#25132]
- Laravel Version: 5.6.x
- PHP Version: 7.2

### Steps To Reproduce: 
1) Create a translation json filled with at least a key greater than 100.
2) Illuminate\Translation\FileLoader is decoding translation json without option JSON_BIGINT_AS_STRING, this cause a cast of our key from "100" (string) to 100 (integer)
3) Then there is this line of code: 
`$output = array_merge($output, $decoded); //line 148 of Illuminate\Translation\FileLoader`, this array merge will break our integer keys changing them this way:
100 => 0
101 => 1
...
190 => 90
4) After the JSON is loaded this way our Translator service can't find translation value for our original translation key "100"

**Comment by staudenmeir** [comment]
I don't think that integer keys are supported. __('99') doesn't work for me, only __('099').

**Comment by lucasecci0** [comment]
actually '99' is a string key, am I wrong?

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
