### ISSUE TITLE
Validator::make alters data in specific cases using wildcard syntax

### ISSUE THREAD

**Issue by apreiml** [laravel/framework#25138]
- Laravel Version: 5.6.29
- PHP Version: 7.2.8

### Description:

`Validator::make` alters data in specific cases using wildcard syntax.

### Steps To Reproduce:

```php
<?php

$stores = json_decode('[{
    "address": {
        "town": "TestTown"
    }
}]');

$values = [
    'stores' => $stores
];

dump($values);

$v = \Validator::make($values, [
    'stores.*.address.town' => 'string|required',
]);

dump($values);
```

The town gets erased:

```
array:1 [
  "stores" => array:1 [
    0 => {#3647
      +"address": {#3646
        +"town": "TestTown"
      }
    }
  ]
]
array:1 [
  "stores" => array:1 [
    0 => {#3647
      +"address": {#3646
        +"town": null
      }
    }
  ]
]
```

**Comment by apreiml** [comment]
This seems to be the line, the change happens: https://github.com/laravel/framework/blob/df5e681c811d15cee257242b802a8b6f3cf1fffc/src/Illuminate/Validation/ValidationData.php#L43

**Comment by staudenmeir** [comment]
This happens because `json_decode()` returns objects by default (`#3646`, `#3647`). When the validator modifies these objects, the input data gets changed ([Objects and references](http://php.net/manual/en/language.oop5.references.php)).

It works if you use `json_decode(..., true)` to return arrays instead of objects. Does this solve your problem?

**Comment by apreiml** [comment]
@staudenmeir I put the json_decode here only for generating test data. I'm aware that this works for arrays. I was surprised about the object behavior.  I'm not sure if objects like those are supported in the validator, but if they are, this may not be the expected behavior.

**Comment by staudenmeir** [comment]
I guess this hasn't been a problem so far because there aren't many situations where object data like this is validated.

A fix definitely wouldn't hurt, but I don't see an easy solution.

**Comment by apreiml** [comment]
@staudenmeir I'm curious why overwrite is set to true on the data_set line. Shouldn't the function fill missing attributes? If I disable overwrite there it works fine.

**Comment by taylorotwell** [comment]
No plans to modify this behavior just because it seems to have little interest from the community and is not very common to validate objects in that way. If we did ever want to fix it we could consider cloning the data before validating.

**Comment by pxlrbt** [comment]
@taylorotwell I think you are right when looking at this from the classic `request()` data. With Livewire's `Wireables` and `Synthesizers` and an increasing usage of Data  Objects, I feel like there will be more occasions of validation data containing objects, though.

**Comment by erikweisz29** [comment]
@taylorotwell Just like the previous reply, I just experienced this issue as well while trying to validate an array of Livewire `Wireable`s. Livewire doesn't send Eloquent model properties to the frontend, so if you want to access an Eloquent model on the frontend, you're kind of forced to use a DTO (Wireable), and having an array of these doesn't seem that uncommon to me.
