### ISSUE TITLE
morphToMany - SQL Selection empty because of '=' instead of 'like'

### ISSUE THREAD

**Issue by Nowi5** [laravel/framework#25137]
- Laravel Version: 5.6
- PHP Version: 7.1
- Database Driver & Version: mysqlnd 5.0.12

### Description:
I using Laravel 5.6 and I used following function for my user model:

Using Illuminate\Database\Eloquent\Relations\MorphToMany
```
public function roles(): MorphToMany
    {
        return $this->morphToMany(
            config('permission.models.role'),
            'model',
            config('permission.table_names.model_has_roles'),
            'model_id',
            'role_id'
        )->withPivot('website_id');
    }
```

My challenge is that the SQL uses "=" instead of "like" to find out if App\Models\User is in use.
The where condition is not escape to App\Models\User and therefore the result is always 0.

Simplified:
```
`select * from `roles` inner join `model_has_roles` on `roles`.`id` = `model_has_roles`.`role_id` where `model_has_roles`.`model_id` in ('1', '3') and `model_has_roles`.`model_type` = 'App\Models\User'
```

I think it should be `model_has_roles`.`model_type` like 'App\Models\User' or `model_has_roles`.`model_type` = 'App\\Models\\User'. Any idea how to use Laravel morph to many with the like comparison or how to escape the where condition? 

model_has_roles
![image](https://user-images.githubusercontent.com/27913135/43829449-3e527cfa-9aff-11e8-9c6f-1bd7324da040.png)

Checking the coding, I guess it would need to be improved here:
https://github.com/illuminate/database/blob/master/Eloquent/Relations/MorphToMany.php line:71

```
    protected function addWhereConstraints()
    {
        parent::addWhereConstraints();
        $this->query->where($this->table.'.'.$this->morphType, $this->morphClass);
        return $this;
    }
```

Thank you very much.

**Comment by staudenmeir** [comment]
The actual problem is the data in your `model_type` column. Why does it have a leading backslash? How do you create the entries?

**Comment by Nowi5** [comment]
You are right, it does not have a leading slash as visible in the example 'App\Models\User'. But the slashes from the namespace, still need to be escaped.

**Comment by Nowi5** [comment]
I think the debugbar just show the unescaped version, having a look into the data log everything looks fine. *closed*
