### ISSUE TITLE
SqlServer Database connection driver selection

### ISSUE THREAD

**Issue by paierlep** [laravel/framework#25133]
- Laravel Version: 5.5.x
- PHP Version: 7.1
- Database Driver & Version: SqlServer with sqlsrv *and* dblib driver

### Description:
The server had - for whatever reason - both dblib and sqlsrv driver installed. First one (dblib) with some error so connection was not possible. This is the database section of the env file similarily to the used one:
 
```
DB_CONNECTION=sqlsrv
DB_HOST= 10.0.0.5
DB_PORT=1433
DB_DATABASE=testdb
DB_USERNAME=testuser
DB_PASSWORD=testpassword
```

Laravel recognized the existence of dblib and ignored the driver value of the database configuration (where sqlsrv was selected), and took the dblib driver together with a very cryptic error message when using the mssql database (this however could have been due to the malfunctioning driver):

```
PDOException : SQLSTATE[HY001] Unable to allocate sufficient memory (10.0.5.87:1433) (severity 8)
/srv/www/vhosts/ds/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:67
/srv/www/vhosts/ds/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:43
/srv/www/vhosts/ds/vendor/laravel/framework/src/Illuminate/Database/Connectors/SqlServerConnector.php:32
/srv/www/vhosts/ds/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php:183
/srv/www/vhosts/ds/vendor/laravel/framework/src/Illuminate/Database/Connection.php:918
/srv/www/vhosts/ds/vendor/laravel/framework/src/Illuminate/Database/Connection.php:665
/srv/www/vhosts/ds/vendor/laravel/framework/src/Illuminate/Database/Connection.php:624
/srv/www/vhosts/ds/vendor/laravel/framework/src/Illuminate/Database/Connection.php:333
/srv/www/vhosts/ds/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:1719
/srv/www/vhosts/ds/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:1704
/srv/www/vhosts/ds/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:483
/srv/www/vhosts/ds/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:467
/srv/www/vhosts/ds/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php:77
[...]
```
I would have expected that:
- sqlsrv is used instead of dblib, because it is explicitly set in the .env file

As far as I have seen in [SqlServerConnector.php#L41](https://github.com/laravel/framework/blob/240d904606a101f5104bff8a1d09678c44f11903/src/Illuminate/Database/Connector /SqlServerConnector.php#L41) the available modules are fetched and then always used in the same order (if present): dblib, odbc and then sqlsrv. 

I suggest to take the user's database configuration into account here, or at least switch the order to prefer sqlsrv as dblib has died with php 5.3 (http://php.net/manual/en/ref.pdo-dblib.php)

If you want I can provide an pull request fixing that.

**Comment by adamtester** [comment]
I have run into this before as dblib didn't seem to support miliseconds (couldn't remember the exact reason)

I had to compile php without dblib

**Comment by paierlep** [comment]
Yes, it is clearly dblib's fault (in not correct working). However Laravel could (and should) make debugging a lot easier by adopting the user's configuration.

**Comment by X-Coder264** [comment]
@paierlep The "driver" in the database config is there just to know which connector class Laravel has to use depending on the database that you chose with `DB_CONNECTION` .env setting -> https://github.com/laravel/framework/blob/5.6/src/Illuminate/Database/Connectors/ConnectionFactory.php#L230 The "driver" config there doesn't have anything to do with the PDO driver that Laravel would use for making the PDO connection with the connector.

As for the order of the drivers, I made #25150 for that.

**Comment by paierlep** [comment]
@X-Coder264 Thank you for looking into the issue - I completely overlooked the ConnectionFactory. I believe that Laravel could (and should) be more transparent here and pass that value to the SqlServerConnector, at least it was really confusing when debugging my underlying issue.

However this is a very minor problem as:
a.) (for now) only MSSQL Server has more than one PDO driver
b.) one of the two is deprecated
c.) it is possible to detect any faulty driver and handling that should be done within the php/server configuration itself

So although i wish for said change (as it would help users today), i do believe that the current solution is fine (no legacy code in the future) - and you could close the issue ;)
