### ISSUE TITLE
$connection of custom pivot model ignored

### ISSUE THREAD

**Issue by pimoudeveldhuis** [laravel/framework#25140]
- Laravel Version: 5.6
- PHP Version: 7.2

### Description:
When using a custom pivot model, the "protected $connection" is ignored. It will always use the connection name from the target model.

A case could be made that pivot tables shouldn't link items from different tables, but still I think ignoring the $connection is unexpected behavior and should be fixed.

### Steps To Reproduce:
Create a user and group table in separate databases with a pivot table in one of them and a custom pivot model that has a "protected $connection = "conn_a". If the group table uses "conn_b" then it will always search for the pivot table in "conn_b" when using belongsToMany('App\Group').

**Comment by driesvints** [comment]
Since the connection is explicitly set from the parent I think this is rather not something that'll change soon. Feel free to open up an issue in https://github.com/laravel/ideas to see if others follow your idea.
