### ISSUE TITLE
Issue with deferred service providers and the cached manifest

### ISSUE THREAD

**Issue by Vmak11** [laravel/framework#25142]
- Laravel Version: 5.5.28
- PHP Version: 7.2.4

### Description:
Adding to the `provides` method of an existing Service Provider has unexpected results and can cause issues.

### Steps To Reproduce:
- Create a new deferred Service Provider and add a binding to the service container in the register method and add it to the provides method (An existing deferred provider with an existing deferred binding can be used as well)
- Make sure to load a script within the application afterward to ensure the new provider is added to the manifest(services.php) cache file
- Add an additional binding to the service provider and to the `provides` method.
- On next page load, a new manifest(services.php) is not generated which does not run the register method when resolving the newly added binding.

### Notes
The issues caused by this can vary and certainly be confusing.  For instance, if you are injecting in the constructor within the binding, those will not be utilized when resolved and if defaults are provided, they will be used instead.  This happens due to the following code:
https://github.com/laravel/framework/blob/df5e681c811d15cee257242b802a8b6f3cf1fffc/src/Illuminate/Foundation/Application.php#L730-L734
Rather than passing the if test and loading the deferred provider, it instead simply bypasses and runs through the parent::make call.
If default values for constructor arguments are not provided you will see the following error:
> Unresolvable dependency resolving [Parameter #...

Also, if you resolve the already cached binding before attempting to resolve the uncached binding, there will not be an issue because resolving the cached binding will call the register method of the provider

Here is where the issue exists:
https://github.com/laravel/framework/blob/df5e681c811d15cee257242b802a8b6f3cf1fffc/src/Illuminate/Foundation/ProviderRepository.php#L107-L110
There needs to be further checking here to also bring in the deferred bindings in the providers `provides` method.  However, I can imagine that would start to defeat the purpose of caching the manifest.  At the very least you might add documentation to clear services.php file or running `php artisan clear-compiled` when adding to the `provides` method of a deferred provider here:
https://laravel.com/docs/5.6/providers#deferred-providers

**Comment by mfn** [comment]
> At the very least you might add documentation to clear services.php file or running php artisan clear-compiled when adding to the provides method of a deferred provider here:
> https://laravel.com/docs/5.6/providers#deferred-providers

I think this is a reasonable thing to do and I encourage you to make a PR over at https://github.com/laravel/docs
