### ISSUE TITLE
Migration command emptying database

### ISSUE THREAD

**Issue by ionesculiviucristian** [laravel/framework#25145]
- Laravel Version: 5.6.29
- PHP Version: 7.1.20
- Database Driver & Version: MySQL 5.7.23

### Description:
When I run php artisan:migrate, the migrations runs but the data is lost from all the tables.

### Steps To Reproduce:
1. I have my projects with all the migrations ran and seeded.
2. I add 2 new file migrations manually.
3. I run migrate command and successfully add the two new tables.
```
Migrating: 2015_12_16_133834_create_settings_groups_table
Migrated:  2015_12_16_133834_create_settings_groups_table
Migrating: 2015_12_16_133836_create_setting_options_table
Migrated:  2015_12_16_133836_create_setting_options_table
```
4. When I check all database tables, they are empty.

**Comment by staudenmeir** [comment]
Can you reproduce that behavior multiple times?

**Comment by ionesculiviucristian** [comment]
Sorry, my bad. It has nothing to do with migrations. Can be closed.
