### ISSUE TITLE
queue:work  command does not work

### ISSUE THREAD

**Issue by liuerwal** [laravel/framework#25154]
- Laravel Version: `5.6`
- PHP Version: `7.1`
- Database Driver & Version:

### Description:
cache driver :  `file`
queue driver:  `database`

When you have never run the `queue:restart` command, 
`Illuminate\Queue\Worker::daemon`   Line 91
`$lastRestart = $this->getTimestampOfLastQueueRestart();`
 will report an uncaught `FileNotFoundException`.
then the job will never run.

**Comment by sisve** [comment]
Can you give us the exact Laravel version and the full exception details, including message and stack trace?
