### ISSUE TITLE
Pivot table attach() without auto sort

### ISSUE THREAD

**Issue by dev4xy** [laravel/framework#25161]
Hi,

`$item->categories()->attach([4,1,2,3]);`
This insert record order by 1 2 3 4
![xxx](https://user-images.githubusercontent.com/36417203/43897617-e22f2736-9bf1-11e8-95d8-ae18bc675bae.png)

I want it insert exactly like array order!! 4 1 2 3
How i do it ?

Thanks!

```
"laravel/framework": "5.5.*",
```

**Comment by staudenmeir** [comment]
Welcome to Laravel! We are glad to have you as part of the community.

Unfortunately, GitHub is not an appropriate platform for general application issues. This is only for issues/bugs with the framework code itself.

Please close your issue, and instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

Laravel Slack (https://larachat.co)
Laravel.io Forum (https://laravel.io/forum)
Laracasts Forum (https://laracasts.com/discuss)
StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks!

**Comment by dev4xy** [comment]
I think it's a bug. @tillkruss @standaniels

**Comment by dev4xy** [comment]
I didn't find any answer.
https://laracasts.com/discuss/channels/laravel/pivot-table-attach-without-auto-sort
https://laravel.io/forum/pivot-table-attach-without-auto-sort
https://stackoverflow.com/questions/51782569/pivot-table-attach-without-auto-sort
