### ISSUE TITLE
[5.6] alpha_num validation bug

### ISSUE THREAD

**Issue by einnar82** [laravel/framework#25165]
I don't know if i am the one who's experiencing this kind of bug in Laravel. 

Either i used any of these:

`   Validator::make($data, [
       'password' => 'required|alpha_num',
   ]);`

or

`PasswordRequest.php`
`public function rules()
{
    return [
       'password' => 'required|alpha_num',
    ];
}`

The `alpha_num` validation doesn't work.
Laravel Version: 5.6.*
PHP Version: 7.2

**Comment by staudenmeir** [comment]
What does "doesn't work" mean? What `$data` are you validating?

**Comment by einnar82** [comment]
`$data` represents data from a request

**Comment by staudenmeir** [comment]
I'm asking about the actual `password` values. Are there invalid values that pass the validation? Or valid values that get rejected?

**Comment by einnar82** [comment]
the password value pass was `12345678`, the other validation are good.

**Comment by X-Coder264** [comment]
From the documentation:

> alpha_num
The field under validation must be entirely alpha-numeric characters.

So of course `12345678` passes that as all characters in the string are numeric.

**Comment by einnar82** [comment]
so what should be the validation?

**Comment by X-Coder264** [comment]
If you want to validate that the password must have both alphabetic and numeric characters you'll have to write a custom regex for that. btw, as this obviously isn't a Laravel bug please close the issue.
