### ISSUE TITLE
[5.6.30+] Outdated changelog and maybe include in composer package?

### ISSUE THREAD

**Issue by Quix0r** [laravel/framework#25168]
When I use the latest patch level (31 as of creation of this issue) the changes are not documented in [change-log file](https://github.com/laravel/framework/blob/v5.6.31/CHANGELOG-5.6.md).

Could you please update your change-log file? And maybe also consider including it into the package that composer fetches, e.g. that it can be found in `vendor/laravel/framwork/` directory.

There are 2 reasons for it:

1. Common across almost all open-sourced projects.
2. Quicker lookup what have been changed for developers (your "end users").

**Comment by tillkruss** [comment]
I'll speak with Taylor about it.

**Comment by Quix0r** [comment]
Thank you very much in advance. :-)

**Comment by Quix0r** [comment]
I think there is a tool that can convert your git history in a change-log file automatically. I can barely remember it.

**Comment by mfn** [comment]
> I think there is a tool that can convert your git history in a change-log file automatically. I can barely remember it.

But this isn't what is wanted. It should be a "curated list of relevant points", not a dump of everything.

**Comment by Quix0r** [comment]
Okay, just an idea. :-)
