### ISSUE TITLE
[5.5] \Illuminate\Support\Facades\Route.php -> incorrect PHPDoc

### ISSUE THREAD

**Issue by fslota** [laravel/framework#25174]
- Laravel Version: 5.5
- PHP Version: 7.2.3

Class Route -> incorrect PHPDoc, line 25 of \Illuminate\Support\Facades\Route.php:

 * @method static \Illuminate\Routing\Router group(\Closure|string|array $value)

contains incorrect number of parameters (1 instead of 2), which triggers code inspector while using Route::Group(param1, param2), line should be:

 * @method static \Illuminate\Routing\Router group(\Closure|string|array $value, \Closure|string $routes)

**Comment by jmarcher** [comment]
@fslota Please send a PR in this cases.
