### ISSUE TITLE
Easier way to fetch the underlying Job model from Job event hooks

### ISSUE THREAD

**Issue by stephan-v** [laravel/framework#25189]
- Laravel Version: 5.6
- PHP Version: 7.1
- Database Driver & Version:

### Description:

Essentially what I want is a way to mark certain jobs to be picked up by the [Job event hooks](https://laravel.com/docs/5.6/queues#job-events). 

The Jobs that I want to get picked up extend from an Abstract class called `AbstractTask`. I was hoping since I could perform an `instanceof` check on the Job like so:

```
Queue::before(function (JobProcessing $event) {
    $job = $event->job;
    
    dd($job instanceof AbstractTask);
});
```

This turned on to not be the case since the `job` that is actually being referred here it not the actual but a driver specific Job like a `syncJob` which holds the actual job in its data.

This actually seems to work because the actual job is within the payload -> data -> command

```
Queue::before(function (JobProcessing $event) {
    $job = $event->job;
    
    $payload = json_decode($job->getRawBody());
    $data = unserialize($payload->data->command);

    if ($data instanceof AbstractTask) {
        dd('this works');
    }
});
```

I was hoping since this was Laravel there would be an easier way but checking out the underlying classes that does not seem like the case. Am I missing something here or is there no easier way to actually get the underlying Job which is actually used to initiate this? If there is nothing there I would love to add a method to simplify this process.

Currently I am using these hooks to create status updates for tasks so I know when certain tasks have started, are finished or have failed.

Any thoughts on an easier way to get this done or perhaps this could be an occasion to add an easier way to get this done?

**Comment by lagbox** [comment]
What about `$job->getName()` ?

**Comment by lagbox** [comment]
Not sure if it is easier, but by looking at the code you may not have to deal with the payload directly yourself.

You can **try** getting the job name from `$job` there:

```php
$class = $event->job->resolveName();
```

Once you have the name you can resolve an instance or just check if it inherits from what you want or is of what you want:
```php
// with an instance
$instance = app($class);
$instance instanceof AbstractTask

// no instance
is_subclass_of($class, AbstractTask::class);
// or to be more inclusive
is_a($class, AbstractTask::class, true);
```

**Comment by driesvints** [comment]
Heya, thanks for submitting this. This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.
