### ISSUE TITLE
Group prefix "where" constrain problem

### ISSUE THREAD

**Issue by IRONALEKS** [laravel/framework#25181]
- Laravel Version: 5.6.21
- PHP Version: 7.2.4
- Database Driver & Version: mysql

### Description:
When registering routes in web.php i am able to add a prefix with a where constrain like this
`
Route::group([
        'prefix' => 'foo/{bar}',
        'where'  => ['bar' => '[0-9a-Z]+']
    ],
    function() {}
);
`
But i am not able to add a where constrain like this
`
Route::prefix('foo/{bar}')->where(['bar' => '[0-9a-Z]+'])->group(
    function() {}
);
`
because `"Method Illuminate\Routing\RouteRegistrar::where does not exist."`, but in my opinion if the first is doable the second should be doable too.
I am not sure it is a bug but it seems like it.
Anyways let me know what you think about
### Steps To Reproduce:

Paste the two codes in routes/web.php and go to any url to see the error

**Comment by tillkruss** [comment]
Please feel free to submit a PR.
