### ISSUE TITLE
file_put_contents(.../storage/framework/cache/data/): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by Tarasovych** [laravel/framework#25186]
- Laravel Version: 5.6
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7.23

### Description:
I got an error
> file_put_contents(.../storage/framework/cache/data/**/**/<some_cache_index>): failed to open stream: No such file or directory

`<some_cache_index>` is always the same.
I have `CACHE_DRIVER=file`  inside `.env`.
Error occurs on certain cross-domain request which fetches some data from database.

What I tried so far: `php artisan cache:clear`, didn't helped. `storage/framework/cache/data/` is empty, but why framework ask that file each time? How can I make framework to forgot that file?

**Comment by X-Coder264** [comment]
If you take a look at your `cache.php` config file you'll see that for the `file` driver the `storage/framework/cache/data` folder is set for writing:

```php
'file' => [
    'driver' => 'file',
    'path' => storage_path('framework/cache/data'),
],
```

That means that your permissions for that folder should be properly set so that the web server user can successfully write to that folder.

**Comment by Tarasovych** [comment]
@X-Coder264 Thank you! I've also tried
`sudo chown -R $USER:www-data storage/*`, `sudo chown -R $USER storage/*` - no success.

**Comment by Tarasovych** [comment]
I guess, `chmod -R 775 storage` solved my problem.

**Comment by blacksrc** [comment]
`php artisan config:cache` solved my issue.

**Comment by JavierSolis** [comment]
in my case it worked to delete the bootstrap/cache/config.php file.

**Comment by abakanindex** [comment]
php artisan config:cache

**Comment by modavidc** [comment]
> `php artisan config:cache` solved my issue.

It's work for me. Thank's

**Comment by Tarasovych** [comment]
@mxl @hosamalzagh @jackgoh @yazansalhi @YNathaly @nadhifhayazee @Pezadilla still waiting for your feedback

**Comment by hamzajaved2020** [comment]
> in my case it worked to delete the bootstrap/cache/config.php file.

Perfect solution

**Comment by josepedrodiaz** [comment]
In my case i do php artisan config:cache but now my app is totally down with this error  Fatal error: Uncaught Error: Call to a member function connection() on null in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1201 Stack trace: #0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1167): Illuminate\Database\Eloquent\Model::resolveConnection(NULL) #1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(997): Illuminate\Database\Eloquent\Model->getConnection() #2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(912): Illuminate\Database\Eloquent\Model->newBaseQueryBuilder() #3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(950): Illuminate\Database\Eloquent\Model->newModelQuery() #4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(901): Illuminate\Database\Eloquent\Model->newQueryWithoutScopes() #5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1570): Illuminate\Database\Eloquent in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php on line 1201


can anyone help me?

**Comment by AngelinCalu** [comment]
In my case the problem was that he `data` folder inside `storage/framework` belonged to root instead of the correct user. `chown -R < user: group > data` did the trick.

**Comment by KAndrew340** [comment]
go to /bootstrap/app.php
edit your app.php file and see that the storage directory is not hardcoded to the path /storage/framework/cache/data/ 

mine looked something like this: $app->useStoragePath('../../../logs/Reports' );

**Comment by ugurdnlr** [comment]
I tried everything written above, but I still get this error.

ErrorException : file_put_contents(/var/www/storage/framework/cache/data/5e/3c/5e3cbbed47195384f39edf30b47d8cd8245cdff8): failed to open stream: No such file or directory

I am using Laradock in project. it is working normally but in phpunit is not working.

**Comment by driesvints** [comment]
Hey everyone,

I'm locking this issue because it either has gone off-topic, become a dumping ground for things which shouldn't be in an issue tracker or is just too old. Please try to discuss things further on one of the below channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
