### ISSUE TITLE
Problem to set 'name' in Route::group([], function(){});

### ISSUE THREAD

**Issue by IRONALEKS** [laravel/framework#25182]
- Laravel Version: 5.6.21
- PHP Version: 7.2.4
- Database Driver & Version: mysql

### Description:
When registering routes i can for example write
`
Route::name('foo')->prefix('foo')->namespace('Foo')->group(function(){});
`
But can't write
`
Route::group
            (
                [
                    'name' => 'foo',
                    'prefix' => 'foo',
                    'namespace' => 'Foo'
                ],
    function(){}
`
and have to change the 'name' to 'as' like so 
`
Route::group
            (
                [
                    'as' => 'foo',
                    'prefix' => 'foo',
                    'namespace' => 'Foo'
                ],
    function(){}
`
This is the second difference(The first one is https://github.com/laravel/framework/issues/25181) i see between `Route::group([],function(){});` and `Route::prefix('')->group(function(){});` which leads me to think that they have some more differences that have perhaps not been fixed.
Anyways let me know what you think.

**Comment by tillkruss** [comment]
That's how it works right now, feel free to submit a PR.
