### ISSUE TITLE
Query builder: undefined variable $operator

### ISSUE THREAD

**Issue by janisblaus** [laravel/framework#25180]
- Laravel Version: 5.5 and 5.6
- PHP Version: 7.3

### Description:
https://github.com/laravel/framework/blob/5.6/src/Illuminate/Database/Query/Builder.php#L1392 undefined variable $operator

**Comment by themsaid** [comment]
Please share the full exception trace as well as replication steps.

**Comment by janisblaus** [comment]
Can't you see that it's missing there by just taking a look to that method?

It comes from using whereExists, operator variable is not defined, therefore an exception is thrown

**Comment by themsaid** [comment]
Ah seem like you're using PHP7.3 that's why, we haven't adapted laravel/framework for PHP7.3 yet, will be handled when the time comes.

**Comment by lffruhling** [comment]
@themsaid thank you, it was over 1:30 hours, until I found your comment and check that my ubuntu had updated php to version 7.3. I returned the php to version 7.2 and it worked for me!
