### ISSUE TITLE
Foreign and unique keys collision during migrations

### ISSUE THREAD

**Issue by NastuzziSamy** [laravel/framework#25190]
- Laravel Version: 5.6.24
- PHP Version: 7.2
- Database Driver & Version: MariaDB 10.1.35

### Description:

Hey guys !

During migrations, contraints are not ordered:
Case 1: Primary key can not be set
 - Foreign keys are set
 - Primary key can not be set because of foreign keys are set

Case 2: Foreign key need a unique column
 - Primary/unique keys written, but not set first
 - Foreign key can not be set because the key is not unique

### Steps To Reproduce:

Case 1:
```php
        Schema::create('assos', function (Blueprint $table) {
		$table->uuid('id')->primary();
		$table->uuid('parent_id')->nullable();
	
		$table->foreign('parent_id')->references('id')->on('assos');
	});
```

Case 2:
```php
     Schema::create('visibilities', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->uuid('parent_id');

            $table->foreign('parent_id')->references('id')->on('visibilities');
        });
```

Thanks guys ! Awesome project, and awesome framework +_+

**Comment by sisve** [comment]
Your first case is expected, you cannot modify columns that is part of a foreign key without dropping the foreign key and creating it.

The second one is more of an issue. Can you provide the generated sql statements?

**Comment by staudenmeir** [comment]
Can you remove the irrelevant columns from your examples?

**Comment by NastuzziSamy** [comment]
@sisve ok thank you

@staudenmeir I just edited

I think I know why it fails. I used https://github.com/spatie/laravel-binary-uuid and after removing it, it works fine
