### ISSUE TITLE
MethodNotAllowedHTTPException on Intended Redirect

### ISSUE THREAD

**Issue by mcordingley** [laravel/framework#25196]
### Environment:

- Laravel Version: 5.5.40
- PHP Version: 7.0
- Database Driver & Version: N/A

### Description:

`redirect()->intended()` can redirect the user to a bad route if the user interacts with a form after session timeout. This leads to errors being shown to a user from reasonable use of the application and is surprisingly difficult to avoid or work around.

### Steps To Reproduce:

- Have an expired session or no session.
- POST to a route protected by the 'auth' middleware that does not have a corresponding GET route.
  - Easy way to do this is to login, navigate to a form, wait a while, then submit the form.
- Authenticate and be redirected to the POST route.
- Receive `MethodNotAllowedHTTPException`.

### Proposed Solution:

Alter `\Illuminate\Routing\Redirector::guest()` to check if the current request is suitable for redirection and if the requested route isn't suitable for redirect, either don't store it as `url.intended` or store the "previous" URL as the intended route to get the user back to being as close as possible to the failed request. I see a good set of conditions in `\Illuminate\Session\Middleware\StartSession::storeCurrentUrl()`, where the previous URL is stored in the first place.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not for ideas, suggestions etc. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. You are able to open a ticket at https://github.com/laravel/ideas

Alternatively you are able to open a PR using the Contributions guidelines: https://laravel.com/docs/5.7/contributions#which-branch

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.

**Comment by mcordingley** [comment]
@laurencei It depends on the semantics, but I'm fairly certain this is a bug, as reasonable use of the framework is netting me unavoidable exceptions.

**Comment by mcordingley** [comment]
@laurencei The description should be clear about how this is a framework issue. I don't think I can elaborate further. It only has the word "Proposed" in it as this is the kind of bug that doesn't have a straight-forward solution.

Also, I have no idea why you think I'm new to the community. I have the "Contributor" tag. There's no way to put this tactfully, but it makes me think you didn't fully read this issue before closing it. :disappointed:

**Comment by mcordingley** [comment]
Opened a PR for this.
