### ISSUE TITLE
[5.5] WhereHas method blows up on PHP 7.3 when explicitly specifying an operator

### ISSUE THREAD

**Issue by CyberiaResurrection** [laravel/framework#25192]
- Laravel Version: 5.5.42
- PHP Version: 7.3.0beta1
- Database Driver & Version: SQLite 3.24.0-1

### Description:
Running a whereHas method off a hasMany relation blows up with:
```ErrorException: compact(): Undefined variable: operator in file /var/www/testproject/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php on line 1243```

### Steps To Reproduce:
0.  Define a hasMany relation on a model.  Ensure that the child model on the relation has at least one relation other than to the parent.
1.  Query the parent's hasMany relation - here's how I tripped over it:
```
$result = $parentModel->manyRelation()->whereHas('childOtherRelation', function ($query) use ($value) {
    $query->where('name', '=', $value);
})->firstOrFail();
```
2.  Execute that query under PHP 7.3.  I tripped over this by running a test case.
3.  Bombs out with above error.

Looking at the chunk of code (addWhereExistsQuery in Query/Builder.php), I'm not seeing where $operator ever got defined.

**Comment by staudenmeir** [comment]
This will be fixed in the next release.

**Comment by CyberiaResurrection** [comment]
Sweet, thank you.

**Comment by CyberiaResurrection** [comment]
That's running clean now.

**Comment by ahlechandre** [comment]
Just:

`bash
composer update
`

**Comment by dyusip** [comment]
> Just:
> 
> ```shell
> composer update
> ```

you ruined my project. @ahlechandre

**Comment by rs-sliske** [comment]
> 
> 
> > Just:
> > ```shell
> > composer update
> > ```
> 
> you ruined my project. @ahlechandre

```bash
git checkout composer.lock
composer install
```

**Comment by jairdeon** [comment]
@dyusip Thanks, it worked for me.
Can you answer why?

**Comment by elegant-moon** [comment]
https://github.com/laravel/framework/issues/26936

@jairdeon
