### ISSUE TITLE
Remove prefix from generated filesystem URLs?

### ISSUE THREAD

**Issue by martinbean** [laravel/framework#25205]
Ref: https://github.com/thephpleague/flysystem-aws-s3-v3/issues/156

When specifying a “disk” we can specify the `root` configuration option that prepends a string to file paths when uploading. I was hoping to also use the `url` option to upload files to S3, but then access via a CloudFront distribution. My CloudFront distribution root is set to **/assets** though; so for a file stored at **/assets/foo.jpg** in my S3 bucket would be accessible via https://example.cloudfront.net/foo.jpg (no **/assets** prefix in the path).

Generating URLs is handled by [`FilesystemAdapter@getAwsUrl()`][1]. It seems I need to _remove_ a prefix rather than prepend it in this method. Is this currently possible?

[1]: https://github.com/laravel/framework/blob/2d551a849184ed55655f52559beed7ac26706bb7/src/Illuminate/Filesystem/FilesystemAdapter.php#L402

**Comment by martinbean** [comment]
> Any chance you're using FortRabbit?

Nope. Laravel application hosted on EC2.

**Comment by laurencei** [comment]
Can you just do the string subset mentioned in to the flysystem ticket? I dont see any other obvious solution, and it seems fairly edge case?
