### ISSUE TITLE
Testing a streamed response does not work

### ISSUE THREAD

**Issue by apokryfos** [laravel/framework#25228]
- Laravel Version: 5.5.42
- PHP Version: 7.1 or 7.2 (tested with both)
- Database Driver & Version: N/A (database was not accessed)

### Description:
This is basically from the SO question [Test a streamed response](https://stackoverflow.com/questions/51857346/test-a-streamed-response)

After further investigation I've realised that objects of StreamedResponse are not streamed as part of testing of routes. This makes methods like `$response->assertSee` etc make no sense as there's no content in the response. However I do think that since a user will end up "seeing" the response, the test should also be able to simulate "seeing" the response. 

### Steps To Reproduce:

Create route:
```
Route::get('echo',function (Request $req) {
    return response()->stream(function () use ($req) {
        echo json_encode($req->all());
    }, 200, [
        'Content-Type' => 'application/json'
    ]);
})->name('echo');
```

Create test

```
public function testBasicTest()
{

    $response = $this->get(route('echo', [
        "content"=>"some content"
    ]));
    $response->assertSeeText("some content"); //Doesn't work but should work since the user does see that text when accessing that route. 
}
```

I did get around the issue of actually getting the correct `TestResponse` object using code:

```
ob_start();
$response->sendContent();
$result = ob_get_clean();
$response = new TestResponse(
       new Response($result, $response->baseResponse->getStatusCode(), $response->baseResponse->headers->all())
);
```

However having to do this within a test case feels a bit hacky. Ideally this should be taken care of internally.

**Comment by driesvints** [comment]
Isn't this more of a case where Laravel Dusk would help? Since you'll need to waiting for the streamed response to finish. In Dusk you could set up a waiting time for the streamed response to finish up and then perform assertions. I don't think this is possible in Laravel itself.

https://laravel.com/docs/5.7/dusk

Feel free to respond back if you have further feedback or believe otherwise!

**Comment by apokryfos** [comment]
@driesvints As mentioned in the description it is possible to test the streaming response if you capture the streaming result in an output buffer and flush it in another test response.  Dusk should not be necessary and in fact if the streaming response is a file download then Dusk may not even be appropriate to check what the file contents are for example.

**Comment by driesvints** [comment]
@apokryfos okay, I do believe this might be something handy to be added to Laravel but I see this more as a feature request than a bug. It's best to post this at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework.
