### ISSUE TITLE
Laravel tests return alway 404 error

### ISSUE THREAD

**Issue by ArthurFelix559** [laravel/framework#25237]
- Laravel Version: 5.1
- PHP Version: 7.2.5
- PHPUNIT Version: 4.8.36

I have posted this in PHPUNIT github, but he told me to post here, so i'm pasting here.

I'm trying to make some phpunit tests in my API, i have my home route `http://site.intradecloud.test/`, i can access this page in the browser, and when i make an `$this->route('GET', '/')` on my test, it's works, but when i make an `$this->visit('/')` it returns =
```
There was 1 failure:

1) MainPageTest::testExample
A request to [http://site.intradecloud.test/pt-BR] failed. Received status code [404].

/home/vagrant/sites/site/vendor/laravel/framework/src/Illuminate/Foundation/Testing/InteractsWithPages.php:165
/home/vagrant/sites/site/vendor/laravel/framework/src/Illuminate/Foundation/Testing/InteractsWithPages.php:63
/home/vagrant/sites/site/vendor/laravel/framework/src/Illuminate/Foundation/Testing/InteractsWithPages.php:44
/home/vagrant/sites/site/tests/MainPageTest.php:11

Caused by
Symfony\Component\HttpKernel\Exception\NotFoundHttpException in /home/vagrant/sites/site/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php:161
Stack trace:
#0 /home/vagrant/sites/site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(750): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request)) #1 /home/vagrant/sites/site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(659): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /home/vagrant/sites/site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
```

And a lot of other code
How can i visit my page to make the tests like SEE anything or CLICK in a button. Thanks.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I suggest closing your issue ticket here? Instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.
