### ISSUE TITLE
Eager loading `hasOne` relationships with where clause

### ISSUE THREAD

**Issue by homersimpsons** [laravel/framework#25243]
- Laravel Version: 5.55
- PHP Version: 7.0.30
- Database Driver & Version: MySQL 5.7.22

### Description:

I've a model that stores history of a table, so to retrieve the current history I've a relationship like:
```php
    public function current()
    {
        return $this->hasOne(History::class, 'model_id')->orderBy('id', 'DESC');
    }
```
(this might have more clauses)
Currently the following query is generated when eager loading with `with('curent')`:
```
select * from `history` where `history`.`model_id` in (X, X, X, X) order by `id` desc
```
I think a more powerful query should be
```
select DISTINCT * from `history` where `history`.`model_id` in (X, X, X, X) order by `id` desc
```
(this migh be related to https://github.com/laravel/framework/issues/13387)

### Steps To Reproduce:

1. Create a `Model` class
```
class Model extends EloquentModel
{
    public function current()
    {
        return $this->hasOne(History::class, 'model_id')->orderBy('id', 'DESC');
    }
}
```

2. Create a `History` class
```
class History extends EloquentModel {}
```

3. Query `Model` with eager loading of `current` `History`
```
Model::with('current')-get();
```

**Comment by staudenmeir** [comment]
What would that achieve? If the table has a primary key, using `DISTINCT *` does not change the query result at all.

**Comment by homersimpsons** [comment]
In fact, I don't know why I though that ....
