### ISSUE TITLE
Why laravel hasn't native method for changing mail driver?

### ISSUE THREAD

**Issue by DaaGER** [laravel/framework#25246]
I can change mysql-host in realtime, but can't change mail driver?
I found a way how I can do it [concept]

https://i.stack.imgur.com/p1TEi.jpg

BUT! I'm sure that laravel developers is more smart and if Laravel hasn't this property, maybe has a reason?

**Comment by browner12** [comment]
can you give an example of why you would want to change the mail driver (or mysql host) at runtime?
