### ISSUE TITLE
Can't select specific columns on parent relation using "with"

### ISSUE THREAD

**Issue by josegus** [laravel/framework#25244]
- Laravel Version: 5.6.0
- PHP Version: 7.2
- Database Driver & Version: Mysql

### Description:
There is no way to select specific columns from parent relation when loading a child relation using "with" method.

This won't work, venta return as null:

$facturas = Factura::select(['id', 'estado'])->with('venta:id,tipo')->get();

This will work, but will return all columns in parent relation (factura):

$facturas = Factura::with('venta:id,tipo')->get();

This is annoying and consume unnecessary resources when the parent relation has a lot of columns.

**Comment by staudenmeir** [comment]
Please post the `venta` relationship.

**Comment by 36864** [comment]
You need to include the foreign key in the selected columns, otherwise laravel won't be able to query for the related models. You also need to include the related model's id column for similar reasons:

```
>>> Document::select(['id', 'status', 'id'])->with('owner')->first();
=> App\TenantModels\Document {#3246
     id: 1,
     status: "new",
     owner: null,
   }
>>> Document::select(['id', 'status', 'owner_id'])->with('owner')->first();
=> App\TenantModels\Document {#3253
     id: 1,
     status: "new",
     owner_id: "8",
     owner: App\TenantModels\User {#3250
       id: 8,
       name: "eyJpdiI6InUxQ0l0a1pjS1VcL0VBS1BPMWlnbkZRPT0iLCJ2YWx1ZSI6ImdsbXhKcWQzYlN0XC9DTWdaVGsyUjhIalYrXC9xYnpvNitabm1rRzl6Y0JBND0iLCJtYWMiOiI3ZTZhZTdhNDcwY2E4ZDNhMmNjMTAwMTdlMWVmMTU0MGJlOGI0NDAzZjg2ZDhkMmVlZGFkZDI2NmE5ZDU3MWUxIn0=",
       email: "wdooley@example.net",
       active: 1,
       created_at: "2018-08-16 09:47:46",
       updated_at: "2018-08-16 09:47:46",
     },
   }
>>> Document::select(['id', 'status', 'owner_id'])->with('owner:email')->first();
=> App\TenantModels\Document {#3244
     id: 1,
     status: "new",
     owner_id: "8",
     owner: null,
   }
>>> Document::select(['id', 'status', 'owner_id'])->with('owner:id,email')->first();
=> App\TenantModels\Document {#3260
     id: 1,
     status: "new",
     owner_id: "8",
     owner: App\TenantModels\User {#3262
       id: 8,
       email: "wdooley@example.net",
     },
   }
```

**Comment by josegus** [comment]
@36864 thanks, it works. I never thought laravel won't be able to retrieve the foreign key from the parent model, event though the parent and child models has the correct relationship.
