### ISSUE TITLE
Authentication stopped working for API request made by axios after disabling cookie serialization

### ISSUE THREAD

**Issue by zhiyong80** [laravel/framework#25256]
- Laravel Version: 5.5.42
- PHP Version:7.0
- Database Driver & Version: MariaDB 10.2

### Description:
After upgrading from previous version to 5.5.42, the version that addresses a security issue, all request made by axios to routes guarded by Passport/API will be returned as unauthorized. However, if cookie serialization is re-enabled by adding:

```
protected static $serialize = true;
```
into App\Http\Middleware\EncryptCookies

Then Passport/API authentication will work again.

### Steps To Reproduce:
1. Upgrade laravel 5.5.42
2. Issue session cookie after log in.
3. Make requests via axios to Passport/API guarded route

**Comment by pingwiniasty** [comment]
Maybe this commit https://github.com/laravel/framework/commit/b0baeff1dcf66d09cfdb0daad6a96eab0f821284 may help with this issue on 5.5 branch?
I have also problems with dusk 2.0 and cookie assertions. It needs this commit too https://github.com/laravel/dusk/commit/5facdb15f5952ed28c711e89b30adce74fa388c7

@taylorotwell Can you look at this? 5.5 is still supported.

**Comment by zhiyong80** [comment]
Just manually edited the helper functions as in commit b0baeff. That didn't solve the problem. All API requests from axios are still returned as 401 un-authorized. Request made by postman still works though.

**Comment by SirLamer** [comment]
I had the same problem... if it matters, using PHP 7.1 and MySQL, developing with Laravel Homestead.

**Comment by zhiyong80** [comment]
following up to confirm that the issue still exists in 5.5.43.

**Comment by rodrigopedra** [comment]
There is a workaround in the Passport issue tracker:

https://github.com/laravel/passport/issues/805

**Comment by carsonlius** [comment]
it works ! thx

**Comment by hashsalacop123** [comment]
Mycontroller  5.7
  public function details()
    {
        $user = Auth::user();
        return response()->json(['success' => $user], $this->successStatus);
    }

my Route

Route::group(['middleware' => 'auth:api'], function(){
	Route::get('details', 'API\UserController@details');
});



{
    "message": "Unauthenticated."
}

Still No luck
