### ISSUE TITLE
Eloquent sync do not update the timestamp

### ISSUE THREAD

**Issue by TBlindaruk** [laravel/framework#25257]
- Laravel Version: #.#.# 
- PHP Version:
- Database Driver & Version:

### Description:

I have a database with many to many relations.
[database structure](https://drive.google.com/open?id=11lnT2-ny0XQ0DFwxloLbu6boDz8izkax)

Model:
```PHP
class Post extends Model
{
    /**
     * @return BelongsToMany
     */
    public function links(): BelongsToMany
    {
        return $this->belongsToMany(ExternalUrl::class)->using(ExternalUrlPost::class);
    }
}

```
When I did 
```PHP
        $post->links()->sync($data->getLinks());
```
For inserting a new data to `ExternalUrlPost` model, then timestamd did not updated

**Comment by paulomunky1** [comment]
I've also experienced this issue with sync in Laravel 5.7.21 and PHP 7.2.4 

Removing the pivot model from the relationship allows the updated_at field to be updated as expected - not ideal but useful to know if you need a workaround.
