### ISSUE TITLE
How Can i override the authorization message of HandlesAuthorization Trait in Policy ?

### ISSUE THREAD

**Issue by bedus-creation** [laravel/framework#25260]

**Comment by rodrigopedra** [comment]
HI, this kind of question is best suited for the forums ( https://laravel.io/forum , https://laracasts.com/discuss ), this issue tracker is to report issues, bugs or related things to the Laravel's code base.

Anyway, I don't know if I understood correctly your question, but it seems to me that you can override the `HandlesAuthorization` method in your policy:

```php
<?php

namespace App\Policies;

use App\Models\User\User;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Auth\Access\HandlesAuthorization;

class MyPolicy
{
    use HandlesAuthorization;

    // your regular rules
    public function manage( User $user )
    {
        return $user->id === 1;
    }

    // ...

    // override the deny method from HandlesAuthorization;
    protected function deny( $message = 'My custom message' )
    {
        throw new AuthorizationException( $message );
    }
}
```

**Comment by bedus-creation** [comment]
If I am not wrong, The `deny` method should call when our rules method (manage in above) return false.
But this is not working I should explicitly call this deny method to override the default message. 

`
<?php

namespace App\Policies;

use App\User;
use App\Models\Jobs;
use Illuminate\Auth\Access\HandlesAuthorization;
use App\Models\UnitTransaction;
use App\Exceptions\JobUnitNotAvailableException;
use Illuminate\Auth\Access\AuthorizationException;
use App\Models\Utils\UnitType;

class JobPostPolicy
{
    use HandlesAuthorization;


    /**
     * Determine whether the user can view the jobs.
     *
     * @param  \App\User  $user
     * @param  \App\Models\Jobs  $jobs
     * @return mixed
     */
    public function view(User $user, Jobs $jobs)
    {
        //
    }


    /**
     * Determine whether the user can create jobs.
     *
     * @param  \App\User  $user
     * @return mixed
     */
    public function create(User $user)
    {
        $UnitTransaction = UnitTransaction::where('company_id', $user->id)
            ->where('unit_type', request()->type)
            ->orderBy('created_at', 'desc')
            ->first();


        $unitAvailable = $UnitTransaction->unit_after_transaction ?? 0;
        if ($unitAvailable <= 0) {

            // $this->deny("Job Unit Not available");
            return false;
        } else {
            return true;
        }

    }
    
    /**
     * Determine whether the user can update the jobs.
     *
     * @param  \App\User  $user
     * @param  \App\Models\Jobs  $jobs
     * @return mixed
     */
    public function store(User $user)
    {
        $unitType = UnitType::find(request()->unit_type_id)->name;

        $UnitTransaction = UnitTransaction::where('company_id', $user->id)
            ->where('unit_type', $unitType)
            ->orderBy('created_at', 'desc')
            ->first();

        $unitAvailable = $UnitTransaction->unit_after_transaction ?? 0;

        if ($unitAvailable <= 0) {

            $this->deny("Job Unit Not available");
            return false;
        } else {
            return true;
        }
    }

    /**
     * Determine whether the user can update the company payment.
     *
     * @param  \App\User  $user
     * @param  \App\  $companyPayment
     * @return mixed
     */
    public function update(User $user, Jobs $jobs)
    {
    }
    
    /**
     * Determine whether the user can delete the jobs.
     *
     * @param  \App\User  $user
     * @param  \App\Models\Jobs  $jobs
     * @return mixed
     */
    public function delete(User $user, Jobs $jobs)
    {

    }

    // override the deny method from HandlesAuthorization;
    protected function deny( $message = 'Jobs Unit Not Available' )
    {
        throw new AuthorizationException( $message );
    }
}
`

**Comment by rodrigopedra** [comment]
Are you using a custom `FormRequest` on your controller?

Searching for this message (`This action is unauthorized.`) the only other place it appears in the `FormRequest`'s `failedAuthorization` method which you can override in your custom class if you are extending it.

Again please don't use the issue tracker for this kind of question. This kind of question is best suited for the forums ( https://laravel.io/forum , https://laracasts.com/discuss )

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
