### ISSUE TITLE
apiResource omits the data wrapper when model has data attribute

### ISSUE THREAD

**Issue by p3ym4n** [laravel/framework#25276]
- Laravel Version: 5.6
- PHP Version: 7.2

### Description:
JsonResource omits the data wrapper for models that have a data attribute inside them.
This issue not appears in collection resources.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not for ideas, suggestions etc. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. You are able to open a ticket at https://github.com/laravel/ideas

Alternatively you are able to open a PR using the Contributions guidelines: https://laravel.com/docs/5.7/contributions#which-branch

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.

**Comment by mfn** [comment]
> as I mentioned before.

The whole bug report here so far is _very light_ on details what this really is about.

Please, be more specific or create a PR to fix it or discuss it on ideas, thank you!
