### ISSUE TITLE
`Illuminate\Events\Dispatcher` uses `newInstanceWithoutConstructor`

### ISSUE THREAD

**Issue by LastDragon-ru** [laravel/framework#25272]
- Laravel Version: v5.6.33
- PHP Version: 7.2

### Description:

Now is possible to define a `queue`, `connection` and other queue properties, but `Illuminate\Events\Dispatcher` do it like this:

```php
    protected function createListenerAndJob($class, $method, $arguments)
    {
        $listener = (new ReflectionClass($class))->newInstanceWithoutConstructor();

        return [$listener, $this->propagateListenerOptions(
            $listener, new CallQueuedListener($class, $method, $arguments)
        )];
    }
```

And for this reason is not possible to set these properties inside the constructor

```php
class MyListener implements ShouldQueue {
    public __construct() {
        $this->connection = config('my-listener.connection'); // Not work
    }
}
```

Moreover, above we can see
```php
    protected function handlerWantsToBeQueued($class, $arguments)
    {
        if (method_exists($class, 'shouldQueue')) {
            return $this->container->make($class)->shouldQueue($arguments[0]);
        }

        return true;
    }
```

I think this is a big inconsistency and it should be fixed - `Illuminate\Events\Dispatcher` should always create a normal instance and must not use the `newInstanceWithoutConstructor`.

**Comment by laurencei** [comment]
Closing as Taylor has decided in the linked PR
