### ISSUE TITLE
Incorrect syntax for nested joins in SQLite grammar (missing parenthesis)

### ISSUE THREAD

**Issue by dariusj18** [laravel/framework#25277]
- Laravel Version: 5.6.25
- PHP Version: 7.1
- Database Driver & Version: SQLite

### Description:

I have little experience with SQLite, however I seem to have come across an issue with nested joins in the Laravel Grammer.

```select * 
from "orders" 
    left join "order_user" 
        inner join "users" on "users"."id" = "order_user"."user_id" and "users"."deleted_at" is null
    on "order_user"."order_id" = "orders"."id" 
where "users"."name" = 1 and "orders"."deleted_at" is null
```

throws an error `Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1 near "on": syntax error (SQL: select * from "orders" left join "order_user" inner join "users" on "users"."id" = "order_user"."user_id" and "users"."deleted_at" is null on "order_user"."order_id" = "orders"."id" where "users"."name" = 1 and "orders"."deleted_at" is null)`

```select * 
from "orders" 
    left join ("order_user" 
        inner join "users" on "users"."id" = "order_user"."user_id" and "users"."deleted_at" is null
    ) on "order_user"."order_id" = "orders"."id" 
where "users"."name" = 1 and "orders"."deleted_at" is null
```

seems to be the correct query.  By changing the file `\Illuminate\Database\Query\Grammars\Grammar.php` method `compileJoins` from

```protected function compileJoins(Builder $query, $joins)
    {
        return collect($joins)->map(function ($join) use ($query) {
            $table = $this->wrapTable($join->table);

            $nestedJoins = is_null($join->joins) ? '' : ' '.$this->compileJoins($query, $join->joins);

            return trim("{$join->type} join {$table}{$nestedJoins} {$this->compileWheres($join)}");
        })->implode(' ');
    }
```

to this

```protected function compileJoins(Builder $query, $joins)
    {
        return collect($joins)->map(function ($join) use ($query) {
            $table = $this->wrapTable($join->table);

            $nestedJoins = is_null($join->joins) ? '' : ' '.$this->compileJoins($query, $join->joins);
            $tableWithJoins = is_null($join->joins) ? $table.$nestedJoins : '('.$table.$nestedJoins.')';
            return trim("{$join->type} join {$tableWithJoins} {$this->compileWheres($join)}");
        })->implode(' ');
    }
```

the query seems to be corrected.  Am I correct, is there something I am missing about SQLite or did I find and fix a bug?  Is there a better way of adding this parenthesis wrapper in a more Laravel/PHP style way?

**Comment by staudenmeir** [comment]
Please post the query builder that generates this SQL.

**Comment by dariusj18** [comment]
```
\DB::table('orders')->leftJoin('order_user', function ($join) {
	$join->on('orders.id', '=', 'order_user.order_id');
	$join->join('users', function ($join) {
		$join->on('order_user.user_id', '=', 'users.id');
	});
})
```

Also, I guess the compileJoin method needs to be put into the `SQLiteGrammar.php` file

**Comment by dariusj18** [comment]
Found it in my phpinfo

SQLite Library	3.20.1

**Comment by driesvints** [comment]
Does the problem still happen on the latest SQlite version? Feel free to reply back if it does and I'll re-open.

**Comment by staudenmeir** [comment]
@driesvints Two issues got a bit mixed up here: There was a bug in SQLite that has been fixed in the latest versions. The main issue is a bug in Laravel's query builder that is still unresolved.

@dariusj18, can you submit your fix as a PR? If you lack the time, I can do it.

**Comment by driesvints** [comment]
@staudenmeir gotcha

**Comment by dariusj18** [comment]
@staudenmeir I am currently lacking the time to create the PR
