### ISSUE TITLE
MyCollection does not use MyResource

### ISSUE THREAD

**Issue by pedzed** [laravel/framework#25274]
If you have `MyCollection`, it will not automatically use `MyResource`.

As [explained in this Medium article](https://medium.com/@dinotedesco/laravel-api-resources-what-if-you-want-to-manipulate-your-models-before-transformation-8982846ad22c), you can achieve it by doing this:
```php
class MyCollection extends ResourceCollection
{
    public function toArray($request)
    {
        $this->collection->transform(function (MyModel $user) {
            return (new MyResource($user));
        });

        return parent::toArray($request);
    }
}
```
Many people expect `MyCollection` to use `MyResource`, but that is not the case. It will use the model rather than the resource.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not for ideas, suggestions etc. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. You are able to open a ticket at https://github.com/laravel/ideas

Alternatively you are able to open a PR using the Contributions guidelines: https://laravel.com/docs/5.7/contributions#which-branch

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
