### ISSUE TITLE
The method getRelated doesn't return correct object in the hasOne relationship

### ISSUE THREAD

**Issue by vovchok** [laravel/framework#25279]
- Laravel Version: 5.6.33
- PHP Version: 7.1.18 (cli)
- Database Driver & Version: pdo_mysql

### Description:

When invoking the `getRelated` method in the hasOne relationship it return an object which is not the same object when invoking the model property.

### Steps To Reproduce:

1. Create one-to-one relationship
2. Invoke the `getRelated` method and the model property
```php
>>> $phone = App\Phone::find(4);
=> App\Phone {#2868
     id: 4,
     name: "Nestor Zemlak II",
     created_at: "2018-08-18 12:10:00",
     updated_at: "2018-08-18 12:10:00",
   }
>>> $phone->screen()
=> Illuminate\Database\Eloquent\Relations\HasOne {#2864}
>>> $phone->screen()->getRelated()
=> App\Screen {#2870}
>>> $phone->screen
=> App\Screen {#2869
     id: 4,
     name: "Destini Altenwerth",
     created_at: "2018-08-18 12:10:00",
     updated_at: "2018-08-20 19:05:27",
     phone_id: 4,
   }
>>> 
```

**Comment by staudenmeir** [comment]
These are two different things:

- `$phone->screen()->getRelated()` returns the empty model that is used to initialize the query builder.
- `$phone->screen` executes the query and returns the actual related model.

**Comment by vovchok** [comment]
Yes. It is. But why every time when invoking a `hasOne` method it instantiate one more instance every time, even in case when model already been instantiated?

https://github.com/laravel/framework/blob/be92f84136374919d5d506ee1c1126ca80e6e63d/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php#L57

Why do not add a condition which check if object instantiated?

```php
$relationName = Str::snake(class_basename($related));

$instance = $this->relationLoaded($relationName)
    ? $this->getRelation($relationName)
    : $this->newRelatedInstance($related);
```
With this condition the `getRelated` method will be returning expected result in case when object already been instantiated.
```php
>>> DB::listen(function ($query) { echo $query->sql, PHP_EOL; });
=> null
>>> $phone = App\Phone::find(4);
select * from `phones` where `phones`.`id` = ? limit 1
=> App\Phone {#2857
     id: 4,
     name: "Nestor Zemlak II",
     created_at: "2018-08-18 12:10:00",
     updated_at: "2018-08-18 12:10:00",
   }
>>> $phone->screen()->getRelated()
=> App\Screen {#2866}
>>> $phone->screen
select * from `screens` where `screens`.`phone_id` = ? and `screens`.`phone_id` is not null limit 1
=> App\Screen {#2856
     id: 4,
     name: "Destini Altenwerth",
     created_at: "2018-08-18 12:10:00",
     updated_at: "2018-08-21 04:31:54",
     phone_id: 4,
   }
>>> $phone->screen()->getRelated()
=> App\Screen {#2856
     id: 4,
     name: "Destini Altenwerth",
     created_at: "2018-08-18 12:10:00",
     updated_at: "2018-08-21 04:31:54",
     phone_id: 4,
   }
>>> 
```

**Comment by staudenmeir** [comment]
Why are you calling `getRelated()`? There is basically no reason to use it in an application.

You should almost always access the relationship as a property:

```php
$screen = $phone->screen;
```

Only use the relationship method when you want to adjust the query:

```php
$screen = $phone->screen()->where('foo', 'bar')->first();
```

**Comment by vovchok** [comment]
When I was in research to figure out how to simplify diassosiation for hasOne relationship I find out that I can’t access to the related object from HasOne class and in previous comment were explaned why is that. Current diassosiation mechanism in hasOne relationship is complicated.
For example, current flow:
```php
$phone->screen->phone()->dissociate();
```
I want to make:
```php
$phone->screen()->dissociate();
```

**Comment by driesvints** [comment]
Please see @staudenmeir's remarks above. It's not wanted to call the `getRelated` method directly in your code.
