### ISSUE TITLE
followingRedirects() on RedirectResponse?

### ISSUE THREAD

**Issue by royduin** [laravel/framework#25283]
I'm currently using this: https://github.com/laravel/framework/issues/18016#issuecomment-312739283 but since Laravel 5.5.19 this is implemented by https://github.com/laravel/framework/pull/21771. I just tried to migrate from the custom `followRedirects()` to `followingRedirects()` but I'm getting:
```
BadMethodCallException: Method Illuminate\Http\RedirectResponse::followingRedirects does not exist.
```
With:
```
$this->get($url)
     ->assertRedirect($redirectUrl)
     ->followingRedirects()
     ->assertSee('Something');
```

Because I was previously doing this:
```
$this->get($url)
     ->assertRedirect($redirectUrl)
     ->followRedirects($this)
     ->assertSee('Something');
```
Which worked great.

I should use it like:
```
$this->followingRedirects()
     ->get($url)
     ->assertSee('Something');
```

But in that case I can't assert for the redirect url with `assertRedirect()`. Is there another way to achieve this? Does it make sense to have `followingRedirects()` also on the `RedirectResponse`? If so, I can do my best to implement it and submit a PR.

**Comment by alchermd** [comment]
Hello @royduin, have you found a working solution?

**Comment by royduin** [comment]
I'm still using the old solution in this specific project

**Comment by driesvints** [comment]
I guess this isn't really solvable. You either follow the redirects or assert that it has been performed.
