### ISSUE TITLE
BadMethodCallException in Illuminate\Validation\Validator@fails is not working properly

### ISSUE THREAD

**Issue by leandrowkz** [laravel/framework#25287]
- Laravel Version: 5.6.16
- PHP Version: 7.2.9 (also tested on 7.1.16)

### Description:
The BadMethodCallException thrown by Illuminate\Validation\Validator@fails (which calls **passes()**, then **validateAttribute()**, then **__call()**) is not being catchable inside a try/catch block, when an invalid rule is given to Validator::make();

### Steps To Reproduce:
```
try {
    $validator = Validator::make($data, ['field' => 'invalid_rule']);
    if ($validator->fails()) {
        // do something
    } 
} catch (BadMethodCallException $e) {
    // Not firing, never catch this
}
```

### Additional information:
I've found out that if I change the parameters order on this line https://github.com/laravel/framework/blob/5.6/src/Illuminate/Validation/Validator.php#L365 then the exception is catch normally, but I have no idea why. So changing this:
```
if ($validatable && ! $this->$method($attribute, $value, $parameters, $this)) {
```
to this:
```
if (! $this->$method($attribute, $value, $parameters, $this) && $validatable) {

```
makes my try/catch works.

Please, could you guys help me to find out what is happening?

**Comment by staudenmeir** [comment]
I can't reproduce that, `catch()` works for me. Are you using the correct `BadMethodCallException` class?

**Comment by leandrowkz** [comment]
@staudenmeir yes, I'm importing BadMethodCallException on top of class. Tried by doing ```catch(\BadMethodCallException $e)``` as well but didn't work.

Did you try reproducing my code and the exception is catchable for you?
I was wondering this could be a problem with PHP but the same problem is happening on multiple environments I use.

**Comment by staudenmeir** [comment]
Yes, I can catch the exception.

**Comment by leandrowkz** [comment]
@staudenmeir 1 thing i forgot: i'm running from a console command. Do you think could have a relation with that?

**Comment by staudenmeir** [comment]
Does your `$data` have a `field` value? I can catch the exception when my `$data` has one. If it doesn't, the validator just passes (as expected).

**Comment by leandrowkz** [comment]
@staudenmeir yes, it does. But sometimes ```$data['field']``` is an empty string(""). That's the problem.

So when ```$data['field']``` is  "", the BadMethodCallException is not even threw cause $validatable inside Validator is false and the the magic __call is never invoked.

I had to modify my validator to:
```$validator = Validator::make($data, ['field' => [$rule, 'required']);```
where $rule can be an invalid rule, sometimes. This way I can force the validator to run the invalid rule even when ```$data['field']``` is an empty string.

Thanks a lot for your help!
