### ISSUE TITLE
PutFileAs and PutFile does not return false if complete stream was not saved

### ISSUE THREAD

**Issue by jcuribe** [laravel/framework#25288]
- Laravel Version: 5.6.31
- PHP Version: 7.1.13
- Database Driver & Version:

### Description:
If the complete stream is not saved to disk on local filesystem, the function does not return false as expected but return path as if the file was saved.

### Steps To Reproduce:
use PutFileAs to save a document on a filesystem where no space is left, or user has no more quota. The new file of size 0 is created, but no content is saved (no space) but function does not return false as expected.
The same happens if a file of 50Mb is saved to a location where only 20Mb is available.

Tracked down the issue to:
vendor\league\flysystem\src\Adapter\Local.php line 57:
stream_copy_to_stream($resource, $stream)

Wich is not checked to see false is returned 

Sudgested correction:
if( !stream_copy_to_stream($resource, $stream)){
            return false;
}

**Comment by X-Coder264** [comment]
As you've said the issue is in the Flysystem adapter which means that this is not a Laravel bug and that you should open this issue in the [Flysystem repo](https://github.com/thephpleague/flysystem).

**Comment by jcuribe** [comment]
ok thanks, Will report.
