### ISSUE TITLE
Laravel constructor session issue

### ISSUE THREAD

**Issue by gaursinghveer007** [laravel/framework#25305]
I am building an E-commerce website. I am tracking Ip address of user when he open the website first time. at that time i want to initialize a session variable for country according to Ip address. and I am also giving a dropdown where he can change his country. 

If session variable is already created then it will not set again until user change country from dropdown.

When user will open website first time then a session variable for country will create from detecting IP address and Products will show according to Country(which will get from Ip address). After that if I click on another page then it will check for session variable. if it is not set then it will create session variable for country. User can change country session variable from Given Dropdown.

I am trying to initialize session variable in constructor but it's not working. Please guide me another method.

**Comment by staudenmeir** [comment]
Welcome to Laravel! We are glad to have you as part of the community.

Unfortunately, GitHub is not an appropriate platform for general application issues. This is only for issues/bugs with the framework code itself.

Please close your issue, and instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

Laravel Slack (https://larachat.co)
Laracasts Forum (https://laracasts.com/discuss)
StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks!
