### ISSUE TITLE
[5.7] Command "dump-server" is not defined.

### ISSUE THREAD

**Issue by Pashaster12** [laravel/framework#25307]
I've updated my Laravel 5.6.34 project to 5.7.0 and wanted try to use the [Symfony Dump-server](https://github.com/beyondcode/laravel-dump-server) the adding of which was announced in the official [Laravel 5.7 Release notes](https://laravel.com/docs/5.7/releases).

After the Laravel version's updating according to [this quide](https://laravel.com/docs/5.7/upgrade), I ran the following command to test the dump-server running, as it was written in the docs:

`php artisan dump-server`

And got the error message in console:

`Command "dump-server" is not defined.`

Is it a bug of Laravel or I missed the sence of the release notes text and dump-server hasn't added to the Laravel's core and it would be added manually via composer? If it is, change please the release notes text for the correct perception of information.

**Comment by GrahamCampbell** [comment]
You'll need to add the package as a codependency yourself if you'd like to use it. See laravel/laravel: https://github.com/laravel/laravel/blob/develop/composer.json#L14.

**Comment by Pashaster12** [comment]
@GrahamCampbell thanks a lot. Could you modify the [upgrading docs](https://laravel.com/docs/5.7/upgrade) with this information?

**Comment by devcircus** [comment]
There are usually some late additions that are not covered in the upgrade guide until it is released.

**Comment by GrahamCampbell** [comment]
The upgrading docs do say look at the diff yourself, at the end. Also, I'd kinda argue this isn't needed to 'upgrade" and app.

**Comment by Pashaster12** [comment]
Yeah, I'm agree with you about the Laravel app will work after version upgrading without the several additional packages included in the new framework version. But I think this information must be in upgrading docs for having Laravel users all the new announces features in their apps. Or

**Comment by hanbz** [comment]
I think this is a important release in the laravel 5.7.  So maybe it should be modify in [upgrading](https://laravel.com/docs/5.7/upgrade) docs

**Comment by browner12** [comment]
Make sure you follow the very last part of the upgrade guide, the Miscellaneous section.  This will cover a lot of the smaller changes not directly addressed in the upgrade guide.

https://github.com/laravel/laravel/compare/5.6...master

You can also check out an article I wrote about addressing these miscellaneous differences.

https://medium.com/@browner12/upgrading-laravel-58900094bbb6

**Comment by eleftrik** [comment]
I totally agree with @Pashaster12 and @hanbz.
`dump-server` is an important and "advertized" change in Laravel 5.7, so I sincerely expect to read, in the upgrade guide, at least a simple statement saying "add beyondcode/laravel-dump-server to your require-dev dependencies". Why have I to dive into diffs and PRs?

**Comment by devcircus** [comment]
Meh. It's an optional feature. Easy to lookup if you need it. However, the docs are open source. A PR would likely be accepted.
