### ISSUE TITLE
Reusing query builder object issue

### ISSUE THREAD

**Issue by oldcastor** [laravel/framework#25308]
- Laravel Version: 5.5.39
- PHP Version: PHP 7.1.14
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.5.59-38.11, for Linux (x86_64) using readline 5.1

### Description:
Unexpected empty response after first `get` when trying to reuse builder object

### Steps To Reproduce:
Here is a simplified code

```
// $photo is an object with fields order_id, id_flow_detail etc
// here i'm getting builder instance

$pre = Photo::where('id_flow_detail', $photo->id_flow_detail)
                  ->where('order_id', $photo->order_id)
                  ->whereNull('date_confirmed');
$noBillingIds   = $pre->whereNull('billing_id')->get();
$withBillingIds = $pre->whereNotNull('billing_id')->get();

return response()->json([
    'noBillingIds'   => $noBillingIds,
    'withBillingIds' => $withBillingIds,
  ]);
```
So all  `get` calls on builder object after the very first one returns in empry collections. Didn't find nothing about this case in docs.

p.s. I understand that I can get results and filter whole collection like 
```
$pre = Photo::where('id_flow_detail', $photo->id_flow_detail)
                  ->where('order_id', $photo->order_id)
                  ->whereNull('date_confirmed')->get();
$noBillingIds   = $pre->where('billing_id', NULL)->values();
$withBillingIds = $pre->where('billing_id', '<>', NULL)->values();
```
and it works as expected, but in general... interresting

**Comment by staudenmeir** [comment]
You have to clone the query builder object:

```php
$noBillingIds   = (clone $pre)->whereNull('billing_id')->get();
$withBillingIds = $pre->whereNotNull('billing_id')->get();
```
