### ISSUE TITLE
updateOrCreate -- duplicating records in update

### ISSUE THREAD

**Issue by whande1992** [laravel/framework#25312]
- Laravel Version:5.6
- PHP Version:7.2
- Database Driver & Version: Versão do servidor: 10.1.26-MariaDB-0+deb9u1 - Debian 9.1

### Description:
It correctly inserts the registry, but when updating it does not validate the two conditions passed (code, language) and updates of all the codes of the condition.

### Steps To Reproduce:

My table has an id column, language and description, I'm running the method for validating the id and language. To insert everything occurs perfectly.

**ID_|_ LANGUAGE_ |_ DESCRIPTION**
1 _____1________language description 1
1 _____2________language description 2
1 _____3________language description 3

The problem occurs when it is updated, when sending to update
**id=** 1 
**language=** 3
**description=** updating language 3

`description :: updateOrCreate (['id' => 1, 'language' => 3],
             ['description' => 'updating language 3']
);`

**it will be like this**

**ID_ |_ LANGUAGE _ |_ DESCRIPTION**
1_____1________  updating language 3
1_____2________  updating language 3
1_____3________ updating language 3

**Laravel 5.6**

**Comment by staudenmeir** [comment]
Please log the executed query:

```php
\DB::enableQueryLog();
Description::updateOrCreate(['id' => 1, 'language' => 3], ['description' => 'updating language 3']);
dd(\DB::getQueryLog());
```

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
