### ISSUE TITLE
Mime type validation doesnt work

### ISSUE THREAD

**Issue by DTX-92** [laravel/framework#25332]
- Laravel Version: 5.6.34
- PHP Version: 7.1.0

### Description:
```
    //createAudio
    public function createA(Request $request)
    {

        $validator = Validator::make($request->all(), [
            'filepond' => 'required|file|mimetypes:audio/mp3'
        ]);

        //TODO:File type validation

        if ($validator->fails()) {
            echo 'File mime: ' . $request->file('filepond')->getClientMimeType() . "\n";
            return response()->json($validator->errors(), 400);
        }

        // ...
    }
```
Console output:
```
File mime: audio/mp3
{"filepond":["The filepond must be a file of type: audio\/mp3."]}
```

**Comment by staudenmeir** [comment]
The validator doesn't rely on the client mime type (`audio/mp3`), it guesses the mime type from the extension. You have to use `mimetypes:audio/mpeg`.

**Comment by DTX-92** [comment]
I tried both before asking.. Didn't work too.

```
File mime1: audio/mp3
{"filepond":["The filepond must be a file of type: audio\/mpeg."]}
```

**Comment by staudenmeir** [comment]
That's odd, `audio/mpeg` works for me.

What's the result of `dd($request->file('filepond')->getMimeType());`?

**Comment by DTX-92** [comment]
2 of 3 files pass good. And 1 fails. Can you try this one?

http://www.noiseaddicts.com/samples_1w72b820/1456.mp3

**Comment by staudenmeir** [comment]
Works for me. Did you change the filename before the upload?

**Comment by DTX-92** [comment]
Nope, 1456.mp3.
Small samples from that site work good.

**Comment by DTX-92** [comment]
```
"application/octet-stream"
```

```
UploadedFile {#239
  -test: false
  -originalName: "1456.mp3"
  -mimeType: "audio/mp3"
  -error: 0
  #hashName: null
  path: "C:\OpenServer\userdata\temp"
  filename: "php641C.tmp"
  basename: "php641C.tmp"
  pathname: "C:\OpenServer\userdata\temp\php641C.tmp"
  extension: "tmp"
  realPath: "C:\OpenServer\userdata\temp\php641C.tmp"
  aTime: 2018-08-26 21:15:12
  mTime: 2018-08-26 21:15:12
  cTime: 2018-08-26 21:15:12
  inode: 0
  size: 658016
  perms: 0100666
  owner: 0
  group: 0
  type: "file"
  writable: true
  readable: true
  executable: false
  file: true
  dir: false
  link: false
  linkTarget: "C:\OpenServer\userdata\temp\php641C.tmp"
}
```

**Comment by staudenmeir** [comment]
Please put `dd($this->guessers);` in  `Symfony\Component\HttpFoundation\File\MimeType\MimeTypeGuesser::guess()` and post the expanded result.

**Comment by DTX-92** [comment]
I tried, but it didnt have any effect. Php didnt enter this method.
However I updated PHP to 7.2.0 and everything worked good. Sorry :|

**Comment by sherryt400** [comment]
I am having same issue with php 7.1 not with 7.2
any reason why?

**Comment by jalallinux** [comment]
and i have this issue with laravel 5.8 php 7.3.1
