### ISSUE TITLE
route() with route groups

### ISSUE THREAD

**Issue by narwy** [laravel/framework#25336]
- Laravel Version: 5.6.34
- PHP Version: PHP 7.2.9-1+ubuntu18.04.1+deb.sury.org+1
- Database Driver & Version: Ver 14.14 Distrib 5.7.23, for Linux (x86_64) 

### Description:
When using a route group, with a variable exampled below. You cannot use `route()` as it's not passing back the parameter `account`. 

Usage: `{{ route('login') }}`
Error: `Missing required parameters for [Route: login] [URI: login]`

You can obviously do `route('login', ['account'] => 'test'])` , but surely there has to be a simple way to avoid this? I had to create a custom helper to avoid the issue blade side, however the Auth is /vendor based so I'd have to go to that to make adjustments, which is a no go?

### Steps To Reproduce:
Route:
```
Route::group(['domain' => '{account}.test.com'], function($account) {
    Auth::routes();
});
```
Direct to `example.test.com` then use `route('login')` on a blade template and find the error.

**Comment by narwy** [comment]
If anyone wanted a quick fix while searching for this similar problem I added a helper function:
```
if ( ! function_exists('accountRoute')) {
    function accountRoute($string) {
        return route($string, ['account' => request()->route()->account]);
    }
}
```

**Comment by narwy** [comment]
### Suggestion:
Route call back, so if there are any variables sent through the request, they can be called back on certain functions in this case `route()`.

Example use:
```
Route::group(['domain' => '{account}.test.com', 'callback' => true], function($account) {
    Auth::routes();
});
```
In the `route()` function does an if statement to call back the variables it originally sent, fixing issues like this, but you can still define custom $parameters if needed?

**Comment by lagbox** [comment]
Just have something setup that sets these based on the request. We already have the facilities to do this.

```php
URL::defaults(['locale' => $request->user()->locale]);
```
>"Once the default value for the locale parameter has been set, you are no longer required to pass its value when generating URLs via the route helper."

[Laravel Docs - Url Generation - Default Values](https://laravel.com/docs/5.6/urls#default-values)

**Comment by narwy** [comment]
@lagbox it's all good adding that but that's just a quick fix, that you'd have to setup etc. Where if you had a callback you wouldn't have to add this and it makes sense if you want the parameters else where.

A fix is needed for variables in route groups, the functions for route etc don't work as standard out of the box package.

**Comment by lagbox** [comment]
You should probably move this to laravel/ideas as this is a proposal for a new feature.

**Comment by narwy** [comment]
@lagbox Still throwing issues.

If you go to a route under the group, then set the middleware of that controller to 
`$this->middleware('auth')`
It will throw the same errors of missing required parameters. This is with the URL defaults set, works fine on `Auth::routes` but fails on any other routes 👎

**Comment by narwy** [comment]
Controller:
```
/**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
```

Route Group:
```
Route::group(['middleware' => 'CheckAccount', 'domain' => '{account}.test.com'], function($account) {
    Auth::routes();
    Route::get('/', 'App\HomeController@index')->name('dashboard');
});
```

Middleware:
```
public function handle($request, Closure $next)
    {
        URL::defaults(['account' => $request->route()->account]);
    }
```

Error:
```
Missing required parameters for [Route: login] [URI: login].
```

This is because I'm not logged in so it's trying to redirect me to `/login`

**Comment by narwy** [comment]
I managed to get it working by resetting the URL defaults in the constructor, but why would I have to re-set the URL defaults again even though it's in the middleware?

**Comment by driesvints** [comment]
@narwy this works for me. Did you add the middleware to the `$routeMiddleware` array? 

```
'CheckAccount' => \App\Http\Middleware\CheckAccount::class,
```

**Comment by narwy** [comment]
@driesvints Yes it was added to the routeMiddleware array in the kernel, Did you wrap your route in the above group? The issue is still active.

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
