### ISSUE TITLE
User email verification should come out of the box

### ISSUE THREAD

**Issue by teo1978** [laravel/framework#25333]
- Laravel Version: 5.6.33
- PHP Version: irrelevant
- Database Driver & Version: irrelevant

### Description:

On a freshly created Laravel application, after running the builtin migrations and the "make:auth" command, I tried registering a user and I was astonished to see that there is no email verification.

That is a wheel that developers shouldn't have to reinvent. It should come builtin just like password reset. An option to enable or disable it might be a good idea, but the mechanism should be provided.

**Comment by staudenmeir** [comment]
Laravel 5.7 will have email verification: https://laravel.com/docs/5.7/releases

**Comment by devcircus** [comment]
IMO how you decide to authenticate, let alone verify users, should completely be at the discretion of the user and not in the framework at all. Alas, as of 5.7, you'll basically have all of this built for you out-of-the-box.

**Comment by staudenmeir** [comment]
Please close the issue.
