### ISSUE TITLE
Bug: Does Laravel 5.6.34 have changed error page styling?

### ISSUE THREAD

**Issue by orukaz** [laravel/framework#25335]
- Laravel Version: 5.6.34
- PHP Version: 7.1.16
- Database Driver & Version: MySQL 5.7.21

### Description:

I updated my Laravel Framework version 5.6.16 -> 5.6.34 and now It shows different error pages than before:

**Before Laravel update (v 5.6.16):**

[Screenshot: Sorry, the page you are looking for could not be found.](https://app.orumets.ee/screenshots/before.png)

This is correct and beautiful.

**After Laravel update (v 5.6.34):**

[Screenshot: Whoops, looks like something went wrong.](https://app.orumets.ee/screenshots/after1.png)
[Screenshot: Sorry, the page you are looking for could not be found.](https://app.orumets.ee/screenshots/after2.png)

Why there are 2 different error views?

**Why do error page styling is buggy after updating, do somebody have uploaded an old Laravel version views?**

**Suggestion: Styling should be the same all over the Laravel Framework.**

**Comment by ankurk91** [comment]
The "something went wrong" is coming from Symfony.
How did you get this message?
Can you provide sample code.

Are you trying to upload a  file that is larger than the max upload size defined in php.ini ?

**Comment by laurencei** [comment]
As @dwightwatson said, Taylor did a small change to the font: https://github.com/laravel/framework/commit/b62ca077f6ae1d94955313b484eb3e82a007636e

**Comment by ankurk91** [comment]
@laurencei

You are doing a great job.
