### ISSUE TITLE
Laravel not using testing disks during testing

### ISSUE THREAD

**Issue by Yazan-Stash** [laravel/framework#25348]
- Laravel Version: 5.6.34
- PHP Version: 7.1.12
- Database Driver & Version: sqlite in-memory

### Description:
When testing file uploads as per the docs
```php
Storage::fake('foo');

$file = UploadedFile::fake()->image('avatar.jpg');

$response = $this->post('/', [
    'file' => $file,
]);

// Assert the file was stored...
Storage::disk('foo')->assertExists($file->hashName());
```

and in controller,

```php
$request->file('file')->store('foo');
```

Laravel seems to ignore the testing disk created by the fake, because the files are actually stored in the local "foo" disk rather than the one in the testing directory, plus the test fails with the error
`Unable to find a file at path [csf0SsOr9IN4zMC2SDhkJYcdxLmQvWIkyURpObqa.png]`

Tried to use another disk, using default disk, all the same.

### Steps To Reproduce:
1. Create a fresh Laravel 5.6 installation
2. Create a new test method with the above snippet.
3. Store file from controller
4. Run Test

**Comment by X-Coder264** [comment]
The `store` method on an `Illuminate\Http\UploadedFile` instance takes two parameters, the first being the path, and the second being the options (aka the disk etc.).

So it should be

`$request->file('file')->store($path, 'foo');`

**Comment by Yazan-Stash** [comment]
*Slaps Forehead Hard*
Oops, It's my silly fault, sorry to waste your time reviewing my fault.
Thank you a lot!
