### ISSUE TITLE
Overriding dateFormat of Eloquent error

### ISSUE THREAD

**Issue by Smoke1987** [laravel/framework#25354]
- Laravel Version: 5.6.33
- PHP Version: 7.2.0RC2
- Database Driver & Version: mysqlnd 5.0.12-dev - 20150407

### Description:

When I try to change the Date Format for Eloquent (e.g. overriding `protected $dateFormat = DateTime::ISO8601`), I get an error

### Steps To Reproduce:

Create new stock project of Laravel

```
composer create-project --prefer-dist laravel/laravel stockProject
```

Fix `storage` permissions (e.g. macos)

```
cd stockProject
chmod -R 777 storage
```

Create auth routes

```
php artisan make:auth
```

Migrate 

```
php artisan migrate
```

Sign Up in new project site

Add to `User` model (`App\User.php`) this lines

```
protected $dates = [
        'created_at',
        'updated_at'
    ];
protected $dateFormat = DateTime::ISO8601;
```

Modify `/routes/web.php` for simplify getting all users from DB (sorry for my bad english)

```
Route::get('/users', function() {
    $users = User::get();
    $array = $users->toArray();
    return response()->json($array);
});
```

In browser try to open `/users` end-point -> getting error

<img width="770" alt="2018-08-27 20 41 00" src="https://user-images.githubusercontent.com/26324597/44675611-ad2c0080-aa39-11e8-92f2-2ffb37be8857.png">

Try to register new user -> error

<img width="774" alt="2018-08-27 20 47 57" src="https://user-images.githubusercontent.com/26324597/44675946-84f0d180-aa3a-11e8-816a-22c40d74b68e.png">

**Comment by staudenmeir** [comment]
The `$dateFormat` property determines how date attributes are stored in the database.

Use `$casts` instead:

```php
protected $casts = [
    'created_at' => 'datetime:'.\DateTime::ISO8601,
    'updated_at' => 'datetime:'.\DateTime::ISO8601,
];
```

**Comment by Smoke1987** [comment]
It's work on stock project

`User.php` model
```
protected $casts = [
        'created_at' => 'datetime:Y-m-d\TH:i:s',
        'updated_at' => 'datetime:Y-m-d\TH:i:s'
    ];
```

<img width="700" alt="2018-08-28 10 34 45" src="https://user-images.githubusercontent.com/26324597/44707738-0e8db700-aaae-11e8-88b9-71cdbaed9df1.png">

but not working in another, more extended project / model

`Order.php` model

```
protected $casts = [
        'created_at' => 'datetime:'.DateTime::ISO8601,
        'date_create' => 'datetime:'.DateTime::ISO8601,
        'updated_at' => 'datetime:'.DateTime::ISO8601,
        'work_start_date' => 'datetime:'.DateTime::ISO8601,
    ];
```

`web.php` routes

```
Route::get('/orders', function() {
    $orders = Order::get();
    $array = $orders->toArray();
    return response()->json($array);
});
```

<img width="490" alt="2018-08-28 10 40 05" src="https://user-images.githubusercontent.com/26324597/44708042-c15e1500-aaae-11e8-9c68-7059694dd2e5.png">

What can influence the date conversion? What am I doing wrong? Differences from the stock project only that in the extended model there are relationships...

**Comment by Smoke1987** [comment]
Find a solution here [https://github.com/laravel/framework/pull/20404](https://github.com/laravel/framework/pull/20404)

I hope this helps someone.
