### ISSUE TITLE
Handeling ModelNotFoundExceptions in Queued Jobs

### ISSUE THREAD

**Issue by MichMich** [laravel/framework#25363]
I am working on a project which involves queued jobs with serialized references to models stored in the database.

In some cases, these models are deleted before the job is processed, resulting in a `ModelNotFoundException` upon starting the job. Of course, this exception is completely valid, since the model could not be loaded. 

As documented, the jobs can include a `public function failed(Exception $exception)` method which allows you to handle any exception the job causes. Unfortunately, this method is not being called upon a `ModelNotFoundException` caused by the deleted model. To me, this seems like unexpected behaviour. 

There are valid reasons to gracefully handle these exceptions. In the current situation the `failed_jobs` table is filled. It would be great if there is a way to mark a job as processed whenever the model cannot be found.  

Previous issues regarding this subject (#10733, #15129, #9347) without a real solution for this issue (or I might have missed the point, in that case my apologies).

What is the recommended approach for handeling these situations?

**Comment by MichMich** [comment]
@Kyslik Thanks, it seems like a good solution (haven't tried it though). I do need to interact with the model, so passing just a the properties would not work. 

What would be an option, is just passing the model id, and then loading the model myself. I think that's the cleanest approach, given the current Laravel restriction.

But I do think a cleaner solution for Laravel would be to handle the exception in the failed method. It handles all other exceptions, so would be reasonable to expect this exception to be handled there.

**Comment by lk77** [comment]
Hello,

passing an id could work, since you can always retrieve it from the database, but it's not ideal, having laravel handling such scenario would be cool indeed.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not for ideas, suggestions etc. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. You are able to open a ticket at https://github.com/laravel/ideas

Alternatively you are able to open a PR using the Contributions guidelines: https://laravel.com/docs/5.7/contributions#which-branch

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
