### ISSUE TITLE
Validate unique field with where clause and null value

### ISSUE THREAD

**Issue by set0x** [laravel/framework#25374]
- **Laravel Version**: 5.6.23
- **PHP Version**: PHP 7.2.4 (cli) (built: Mar 28 2018 04:27:01) ( ZTS MSVC15 (Visual C++ 2017) x64 )
- **Database Driver & Version**: MYSQL 5.7.21

### Description:

When you use unique validation rule with "where" clause and a"null" value cause an error in `laravel\framework\src\Illuminate\Validation\Concerns\ValidatesAttributes.php` in `getExtraConditions`
because the 'null' value is deleted from array `$segments`

![image](https://user-images.githubusercontent.com/15133015/44799389-19cb0a80-abb4-11e8-9032-337d74519228.png)

### Steps To Reproduce:

Rules to validate.
```php
return [
    'name' => Rule::unique('lodgings')->where('type_id', $this->type),
    'type' => 'required',
];
```
When not pass `type_id` attribute cause a error. 

But this, work.

```php
return [
    'name' => Rule::unique('lodgings')->where('type_id', $this->type ?? 'null'),
    'type' => 'required',
];
```

**Comment by set0x** [comment]
I don't know which is the better solution...


If the value is null, do not add the condition where

https://github.com/laravel/framework/blob/a784efcc17b1c683bb64b6e0916c4e2a6cea231c/src/Illuminate/Validation/Rules/DatabaseRule.php#L57

```php
//framework\src\Illuminate\Validation\Rules\DatabaseRule.php

/**
 * Format the where clauses.
 *
 * @return string
 */
protected function formatWheres()
{
    return collect($this->wheres)->map(function ($where) {
        return $where['column'].','. ($where['value'] ?? 'null');
    })->implode(',');
}

```

or if null add null as a value.

https://github.com/laravel/framework/blob/a784efcc17b1c683bb64b6e0916c4e2a6cea231c/src/Illuminate/Validation/Rules/DatabaseRule.php#L166

```php

//framework\src\Illuminate\Validation\Rules\DatabaseRule.php

/**
 * Set a "where" constraint on the query.
 *
 * @param  string|\Closure  $column
 * @param  array|string $value
 * @return $this
 */
public function where($column, $value)
{
    if (is_array($value)) {
        return $this->whereIn($column, $value);
    }

    if ($column instanceof Closure) {
        return $this->using($column);
    }

    if (!is_null($value)) {
        $this->wheres[] = compact('column', 'value');
    }

    return $this;
}
```

**Comment by staudenmeir** [comment]
I don't understand your first solution. Why would you ignore a `null` constraint?

We could call `whereNull()`:

```php
public function where($column, $value)
{
    if (is_array($value)) {
        return $this->whereIn($column, $value);
    }

    if ($column instanceof Closure) {
        return $this->using($column);
    }

    if (is_null($value)) {
        return $this->whereNull($column);
    }

    return $this;
}
```

**Comment by set0x** [comment]
I think that is better use `null` (null) to ignore condition and `'null'` (string) to filter by null.

This will be ignore.
```php
$type = null;

Rule::unique('lodgings')->where('type_id', $type),
```
And this will be compare with `null`.
```php
Rule::unique('lodgings')->whereNull('type_id'),
```

**Comment by driesvints** [comment]
I think @staudenmeir's suggestion is the correct solution. This probably needs to be sent to master to avoid breaking people's validation.

**Comment by driesvints** [comment]
This will be fixed in the next release.
