### ISSUE TITLE
In functionTest case /start/global.php is loaded after service providers

### ISSUE THREAD

**Issue by linslin** [laravel/framework#25371]
## In functionTest case /start/global.php is loaded after service providers

- Laravel Version: 4.2.0
- PHP Version: 7.1.8
- Database Driver & Version: MySQL 5.6

We are facing a problem in Laravel 4.2 where our `/start/global.php` is loaded/executed after some ServiceProvider. In our ServiceProvider `public function register()` and `public function boot()` are called before `/start/global.php` loaded/executed. This only happends while running our application tests via phpUnit. If we run our applicatoin via Browser on our Server the sequence of loading is correct.

### TestCase.php:

```
<?php

    namespace app\tests\base;

    class TestCase extends \Illuminate\Foundation\Testing\TestCase {
    
    	/**
    	 * Creates the application.
    	 *
    	 * @return \Symfony\Component\HttpKernel\HttpKernelInterface
    	 */
    	public function createApplication()
    	{
    		$unitTesting = true;
    		$testEnvironment = 'testing';
    
    		return require __DIR__ . '/../../../bootstrap/start.php';
    	}
    }
```

### phpunit.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit backupGlobals="false"
         backupStaticAttributes="false"
         bootstrap="bootstrap/autoload.php"
         colors="true"
         convertErrorsToExceptions="true"
         convertNoticesToExceptions="true"
         convertWarningsToExceptions="true"
         processIsolation="false"
         stopOnFailure="false"
         syntaxCheck="false">
    <testsuites>
        <testsuite name="Application Test Suite">
            <directory>./app/tests/base/</directory>
        </testsuite>
    </testsuites>
</phpunit>
```

------------
We looked deeper into the codes and recognized that `$app->booted()` in `vendor/laravel/framework/src/Illuminate/Foundation/start.php` is executed after `public function register()` and `public function boot()` (ServiceProvider).

How could we force the testing environment to load our application in the correct way? - Also refer: 
- https://laravel.com/docs/4.2/lifecycle
- https://stackoverflow.com/questions/52073643/laravel-4-2-in-functiontest-case-start-global-php-is-loaded-after-service-prov

**Comment by laurencei** [comment]
Hi,

Unfortunately Laravel 4.2 is no longer supported.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)


Thanks in advance.
