### ISSUE TITLE
[Socialite] Parameters not being set with getTargetUrl()

### ISSUE THREAD

**Issue by poppabear8883** [laravel/framework#25376]
- Laravel Version: `5.6.34`
- PHP Version: `7.2.5`
- Database Driver & Version: `MySQL  5.7.22`

### Description:
So the issue is that when using Socialite in `stateless` mode and using `->getTargetUrl()` the target url does not pass along any custom params specified in `->with(...)`

Example:
```php
public function redirectToProvider()
{
    return Socialite::driver('github')
        ->stateless()
        ->with(['user_id' => request()->user_id])
        ->scopes([
            'user',
            'repo',
            'admin:org',
            'write:discussion'
        ])
        ->redirect()
        ->getTargetUrl();
}

public function handleProviderCallback()
    {
        $user = Socialite::driver('github')
            ->stateless()
            ->user();

        $this->service->create([
            'driver' => 'github',
            'username' => strtolower($user->getNickname()),
            'password' => null,
            'token' => $user->token,
            'user_id' => request()->user_id // <--- RETURN NULL
        ]);

        return redirect()->away(config('app.url'));
    }
```
**In the above example `request()->user_id` inside the `handleProviderCallback()` method returns `null`**

The `->getTargetUrl()` is only passing along the `code` param ...

### Steps To Reproduce:
**Bare with me i will try and be as descriptive as i can be here. Hopefully I don't miss anything. However I assume most will know exactly what i am attempting to do considering my examples.**

1. Install Laravel
2. Install Socialite
3. Setup a `New OAuth App` for test in github [HERE](https://github.com/settings/developers)
4. Add to `.env`
```
GITHUB_CLIENT_ID=<YOUR OAUTH APP CLIENT ID>
GITHUB_CLIENT_SECRET=<YOUR OAUTH CLIENT SECRET>
GITHUB_REDIRECT_URL=https://<YOUR DOMAIN>/api/github/callback
```
5. Add the routes to `api.php`
```php
Route::get('github', function () {
    return Socialite::driver('github')
        ->stateless()
        ->with(['user_id' => request()->user_id])
        ->redirect()
        ->getTargetUrl();
});
Route::get('github/callback', function () {
    $user = Socialite::driver('github')
            ->stateless()
            ->user();

     return response(['user_id' => request()->user_id]);
});
```
6. Make `GET` request to the `api/github` endpoint
```javascript
this.axios.get('example.com/api/github', {
          params: {
            user_id: 1,
          },
        })
          .then(response => {
            window.location.href = response.data;
          })
          .catch(error => console.log(error));
      },
```
7. Authorize github scopes
8. Observe the response in `dev tools`

**You should find the response be `null`**

**Comment by poppabear8883** [comment]
Just to add to this issue

Looks like in order to fix this issue we MUST override the `setTargetUrl()` inside  https://github.com/laravel/framework/blob/5.6/src/Illuminate/Http/RedirectResponse.php

Where this class extends that of a `Symfony` class which holds the `getters` and `setters` for the respected methods.

**Comment by poppabear8883** [comment]
Maybe the solution is this ...

```php
return Socialite::driver('github')
            ->stateless()
            ->redirectUrl(config('services.github.redirect') . '?user_id=' . request()->user_id)
            ->scopes([
                'user',
                ...
            ])
            ->redirect()
            ->getTargetUrl();
```

**Instead of using `->with(...)` we dynamically set the redirect url**

Still think that this should happen for us if using the `->with(...)` method

Anyone care to chime in on the subject ?

**Comment by driesvints** [comment]
Heya. The socialite issue tracker was opened recently. If you're still experiencing this issue please open one there: https://github.com/laravel/socialite/issues

**Comment by gogolidze26** [comment]
> Heya. The socialite issue tracker was opened recently. If you're still experiencing this issue please open one there: https://github.com/laravel/socialite/issues

facebook: 
This is an invalid redirect URI for this application
You can make this URI valid by adding it to the list of valid OAuth redirect URIs above

**Comment by Christophvh** [comment]
For anyone struggling with this. You can use 'state', which is not stripped by most drivers.

    return Socialite::driver('facebook')
        ->stateless()
        ->with(['state' => request()->user_id])
        ->redirect()
        ->getTargetUrl();
