### ISSUE TITLE
Long lines should be wrapped in text emails generated from markdown

### ISSUE THREAD

**Issue by hackel** [laravel/framework#25383]
- Laravel Version: >= 5.3

### Description:
When generating plain-text email parts from markdown, long lines should be wrapped to 78 characters.  Currently, they are rendered as-is, which results in extremely long lines.  There is also a potential to break the email standard, which *requires* lines of no more than 998 characters.
See: https://tools.ietf.org/html/rfc5322#section-2.1.1

As far as I can tell, there is currently no way to send properly formatted text emails without creating a custom template. Even if you split the lines manually by inserting newlines or passing an array of strings to the MailMessage::line method, these get joined (as they should for HTML) prior to rendering and being parsed as Markdown for the text-only part.

### Steps To Reproduce:
Send a markdown email (or notification) with long lines.  These are rendered properly in HTML, which wraps natively, but in plain-text emails, the lines do not wrap.

**Comment by mfn** [comment]
> Laravel Version: >= 5.3

You mentioned this version: did it work _before_ ?

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not for ideas, suggestions etc. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. You are able to open a ticket at https://github.com/laravel/ideas

Alternatively you are able to open a PR using the Contributions guidelines: https://laravel.com/docs/5.7/contributions#which-branch

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.

**Comment by hackel** [comment]
@mfn I did not test this before, but I am certain it did not ever work correctly.

@laurencei This is a bug because it violates the relevant email standards, which I explained and linked to in the original issue.  At the very least, not limiting line length to 998 characters is a bug.  Choosing to wrap lines (instead of truncating them) is my "suggestion," I suppose.
