### ISSUE TITLE
File not found 404

### ISSUE THREAD

**Issue by gultyaev** [laravel/framework#25384]
I'm saving my files using `$request->file('image')->store('public/thumbnails');` and saving this path to DB. However, when I try to access it an error returns - 404 file not found.
I've tried to use `asset($filepath)`, `url($filepath)`, `storage_path($filepath)`.
It returns link as it should be

> http://api.example.com/public/thumbnails/ySOSYhaCCRcH3t9agsco3ToUwoHxMZJ3r1PhEHlM.jpeg

But that doesn't help and server responses with
> {"message":"404 Not Found","status_code":404}

The symlik has been created according to docs and `public/storage` contains `thumbnails` folder. I don't see any error neither in laravel logs nor in apache logs

**Comment by bakerkretzmar** [comment]
@gultyaev did you get this fixed?

**Comment by gultyaev** [comment]
@bakerkretzmar yes. I did

**Comment by bakerkretzmar** [comment]
@gultyaev sorry I wasn't clear—I'm having the same issue! How did you fix it?

**Comment by gultyaev** [comment]
@bakerkretzmar something like `Storage::url($model->path)`. The main problem is that I thought that this will prepend with path I used. Also I've used this `url('storage/'.$image->link)`.
