### ISSUE TITLE
log require ^7.1.3 and monolog ~1.11

### ISSUE THREAD

**Issue by shooyaaa** [laravel/framework#25380]
- Laravel Version: 5.6.4
- PHP Version: 7.1.3
- Database Driver & Version: mongo 3.6

### Description:
The question is monolog 1.xx works only when php is php5.x, not php7.x

### Steps To Reproduce:
use mono log handler
'mongo' => [
            'driver'  => 'monolog',
            'handler' => Monolog\Handler\MongoDBHandler::class,
            'formatter' => Monolog\Formatter\MongoDBFormatter::class,
            'handler_with' => [
                'mongo' => new \MongoDB\Client('mongodb://127.0.0.1:27017'),
                'database' => 'db_log',
                'collection' => 'log_' . date('Y_m_d')
            ],
        ]

**Comment by ankurk91** [comment]
It says `>=5.3.0`

https://github.com/Seldaek/monolog/blob/fd8c787753b3a2ad11bc60c063cff1358a32a3b4/composer.json#L16

**Comment by shooyaaa** [comment]
That's  not true , monolog 1.x.x doesn't support php7.x, only 2.x does

**Comment by devcircus** [comment]
monolog 1.x definitely supports php 7. Version 2 will ONLY support php 7.1 and above.

**Comment by shooyaaa** [comment]
I know it support php7.x,  But in monolog 1.x.x  class Monolog/Formatter/MongoDBFormatter use \MongoDate class which found in deprecated mongo php extension. Apparently no one use Mongo extension any more,

**Comment by mfn** [comment]
Also see this recent journey regarding Monolog/MongoDB interactions: https://github.com/laravel/framework/issues/25170
