### ISSUE TITLE
Connect mysql 8 MySQL server has gone away

### ISSUE THREAD

**Issue by fatrbaby** [laravel/framework#25385]
- Laravel Version: 5.6.35
- PHP Version: 7.1.16
- Database Driver & Version: mysql 8.0.12

### Description:
throw error `SQLSTATE[HY000] [2006] MySQL server has gone away`

view mysql status:
mysql>  show variables like '%timeout%';

+-----------------------------------+----------+
| Variable_name                     | Value    |
+-----------------------------------+----------+
| connect_timeout                   | 10       |
| delayed_insert_timeout            | 300      |
| have_statement_timeout            | YES      |
| innodb_flush_log_at_timeout       | 1        |
| innodb_lock_wait_timeout          | 50       |
| innodb_rollback_on_timeout        | OFF      |
| interactive_timeout               | 604800   |
| lock_wait_timeout                 | 31536000 |
| mysqlx_connect_timeout            | 30       |
| mysqlx_idle_worker_thread_timeout | 60       |
| mysqlx_interactive_timeout        | 28800    |
| mysqlx_port_open_timeout          | 0        |
| mysqlx_read_timeout               | 30       |
| mysqlx_wait_timeout               | 28800    |
| mysqlx_write_timeout              | 60       |
| net_read_timeout                  | 30       |
| net_write_timeout                 | 60       |
| rpl_stop_slave_timeout            | 31536000 |
| slave_net_timeout                 | 60       |
| wait_timeout                      | 604800   |
+-----------------------------------+----------+

**Comment by bolivir** [comment]
Ive got this problem once, and it appeared to be a configuration issue on the side of mysql.
Most of the times this error message has two main causes and solutions:
- Server timed out and closed the connection, but what i see from the config  the `wait_timeout` should be high enough.
- Server dropped an incorrect or too large packet, how large is the query result? did you already try to increase the value of `max_allowed_packet` ?

**Comment by fatrbaby** [comment]
@bolivir Thx for your answer。I am execute a very simple SQL only and the value of the `max_allowed_packet ` is `67108864`, so i think is not about of this setting。This problem is on MySQL version 8 only，and I never had a problem when I used mysql7.

**Comment by rodrigopedra** [comment]
It seems that you must set set higher values for both `wait_timeout` and `interactive_timeout`. I couldn`t reproduce it locally, and I am running Laravel+MySQL8 since the MySQL 8 GA release, but I found this stackoverflow link with further details:

https://stackoverflow.com/a/33250885

**Comment by isgk** [comment]
@fatrbaby I know it's been a while but I've found the answer. Use the following command to update your password with new authentication plugin. You can use MySQL 8 now. Have fun.

    ALTER USER `username`@`localhost` IDENTIFIED WITH caching_sha2_password BY 'password';

OR

    ALTER USER 'username'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';

**Comment by vanessasoutoc** [comment]
Thank You. it`s owrking for me

**Comment by cleoGson** [comment]
thanks
