### ISSUE TITLE
Eloquent load() cant access models properties.

### ISSUE THREAD

**Issue by stickeerehan** [laravel/framework#25387]
- Laravel Version: 5.6.35 && 5.6.34
- PHP Version: 7.1
- Database Driver & Version: mySQL 5.7

### Description:
In an eloquent model I had a preload function which would call `$this->load`. Example code:

````php
   public function preload($section)
    {
        switch ($section) {
            case 'overview':
                $this->load(
                    [
                        'customer',
                    ]
                );
                break;
        }
    }
````

In the `customer` function there was a check which would retrieve the one of the models properties and return a relationship based on that:

````php
    public function customer()
    {
        if ($this->recipient_type == 'dealer') {
            return $this->belongsTo(Dealer::class, 'recipient_id');
        }
   }
````
On 5.6.33 this was *working*. Retrieving `$this->recipient_type` correctly returned the relevant string used to make comparisons but 5.6.34 broke this; it now returns `null`. 5.6.35 is the same. Downgraded back to 5.6.33 and it's working again.

### Steps To Reproduce:
Detailed above.

**Comment by staudenmeir** [comment]
Relationships shouldn't/can't use `$this` like that. See #25362.

**Comment by driesvints** [comment]
Please see the linked issue above.
