### ISSUE TITLE
Class Illuminate\Auth\Listeners\SendEmailVerificationNotification does not exist

### ISSUE THREAD

**Issue by aymenbz** [laravel/framework#25409]
Hi, i have problem with laravel 5.7 
when i try to register new user 
i am getting this error 
Class Illuminate\Auth\Listeners\SendEmailVerificationNotification does not exist

**Comment by staudenmeir** [comment]
Are you definitely using Laravel 5.7?

**Comment by aymenbz** [comment]
@staudenmeir @devcircus 
i've installed the dev version through composer by typing this command 

`composer create-project --prefer-dist laravel/laravel blog dev-develop`

**Comment by staudenmeir** [comment]
Do you see the file in `vendor/laravel/framework/src/Illuminate/Auth/Listeners`?

**Comment by aymenbz** [comment]
@staudenmeir there is no Listeners Folder !!

**Comment by staudenmeir** [comment]
What does `composer show` say about the version of `laravel/framework`?

**Comment by devcircus** [comment]
You don't have 5.7. Sounds like a composer configuration issue.

**Comment by aymenbz** [comment]
Oh yeah You're right guys it's composer issue
thank you all

**Comment by kulombok** [comment]
hey how to solved it, i have the same issue

**Comment by aymenbz** [comment]
@kulombok i've tried to install Laravel 5.7 through composer but i got this error and when i checked the version it was 5.6,
 Now Laravel 5.7 has been released so you can install it normally and you will not get the issue,
you can use this command ```laravel new blog``` if you already have Laravel installer installed

**Comment by kulombok** [comment]
@aymenbz, oh i see. So just to update my laravel. 
Yeah I have got this error when doing register.
Thank you so for the explanation.

**Comment by pouryasheshgelani** [comment]
i want to make this error ,do i just update my laravel 5.6? to laravel 5.7?

**Comment by pouryasheshgelani** [comment]
i don't want to update because goldmeans in vonder work in laravel 5.6 if i install laravel 5.7 ,the goldmeans for shopping cart don't working

**Comment by pouryasheshgelani** [comment]
> i want to make this error ,do i just update my laravel 5.6? to laravel 5.7?

i found this ! in laravel 5.6 you created listeners.php  in  Illuminate\Auth\Listeners so in controller using this :
use Illuminate\Auth\Listeners\SendEmailVerificationNotification;
so in app\providers\EventServiceProvider you check $listeners because in laravel 5.6 is $listen so you change this!!!!!

**Comment by AkramChauhan** [comment]
This is just for the record.
When this Happen: When you downgrade your Laravel Version.
Solution.
Navigate to Providers/EventServiceProvider.php
Just replace entire file with the original file.
You can find the original file from GitHub (Laravel's Official Repo).
In my case, I downgraded my app from 6.0 to 5.5
**https://github.com/laravel-shift/laravel-5.5/blob/master/app/Providers/EventServiceProvider.php**
