### ISSUE TITLE
makeWith or make does not return mocked object when testing

### ISSUE THREAD

**Issue by JValck** [laravel/framework#25401]
- Laravel Version: 5.6.29
- PHP Version: 7.2.7

### Description:
The service container does not resolve the mocked object when using the `makeWith` method with parameters. It does work when using the `make` method without parameters, but neither does when using parameters.

### Steps To Reproduce:

1. In the test bind a mock: `$this->app->bind('App\Model\User', \Mockery::mock('App\Model\User'));`
2. Resolve the `App\Model\User` with the `resolve` helper or `make` method without using parameters. This will return the mock which is ok.
3. Resolve the `App\Model\User` with `makeWith` or `make` for example: `$this->app->makeWith('App\Model\User', ['name' => 'JValck']);` This will return the actual implementation instead of the mock.

**Comment by X-Coder264** [comment]
https://github.com/laravel/framework/issues/19450 https://github.com/laravel/framework/issues/25041
