### ISSUE TITLE
Mailgun usage broken for EU based developments

### ISSUE THREAD

**Issue by EntrepreneurAJ** [laravel/framework#25410]
- Laravel Version: all
- PHP Version: all
- Database Driver & Version: all

### Description:
Mailgun has changed their API so there is a new endpoint for EU customers. The file framework/src/Illuminate/Mail/Transport/MailgunTransport.php
has the api endpoint for North American servers hard coded.

### Suggestion:
Make a config or env variable that allows the developer to select which API to use eg MAILGUN_SERVERS={US|EU}

American Servers API: https://api.mailgun.net/v3/{DOMAIN}
EU Servers API: https://api.eu.mailgun.net/v3/{DOMAIN}

Can be seen by the menu showing the region as a dropdown in the top right corner of the mailgun user panel and creating a domain on the EU region. Guessing this is a GDPR thing.

**Comment by X-Coder264** [comment]
This has already been fixed for 5.7 -> https://github.com/laravel/framework/pull/24994

It should be backported to 5.6 though so feel free to send a PR.

**Comment by X-Coder264** [comment]
The mailgun driver gets created in the [TransportManager](https://github.com/laravel/framework/blob/5.7/src/Illuminate/Mail/TransportManager.php#L115). As you can see the user sets the endpoint and the domain in the services.php config file, just like before.

**Comment by EntrepreneurAJ** [comment]
Seen as 5.7 was released very shortly after I guess this is mute. I see that the documentation doesn't reflect this though. I leave this to reference issue https://github.com/laravel/docs/issues/4517
