### ISSUE TITLE
Laravel Blog?

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/framework#25420]
It would be useful to have a Laravel Blog example a bit like Cake PHP for people new to laravel looking to try it out https://book.cakephp.org/3.0/en/tutorials-and-examples/blog/blog.html

**Comment by jmarcher** [comment]
There are many examples out there.

**Comment by decadence** [comment]
https://github.com/laravel/ideas

**Comment by rodrigopedra** [comment]
Last time the official docs contained a tutorial was in Laravel 5.2:
