### ISSUE TITLE
Maintenance mode --message not working

### ISSUE THREAD

**Issue by josegus** [laravel/framework#25426]
- Laravel Version: 5.6.26
- PHP Version: 7.2
- Database Driver & Version: MariaDB 10

### Description:
Can't pass a default message to artisan down command. The --message value is simply ignored, no error or exception is added in laravel.log. The terminal doesn't show any error, the artisan down is working great, just the --message is being ignored.

**Comment by staudenmeir** [comment]
Please post the command you are using.

**Comment by josegus** [comment]
@staudenmeir the command I'm using is:

php artisan down --message="App en modo mantenimiento"

![image](https://user-images.githubusercontent.com/13947849/44989894-5fddf080-af5d-11e8-9d6a-1b2b70cbec58.png)

![image](https://user-images.githubusercontent.com/13947849/44989901-69675880-af5d-11e8-85f4-7f2f5eb675e1.png)

**Comment by AegirLeet** [comment]
Maintenance mode uses the [503.blade.php](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Foundation/Exceptions/views/503.blade.php) view, which doesn't use the message by default.

You can override the view by creating _resources/views/errors/503.blade.php_. Inside this view, the original [MaintenanceModeException](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Foundation/Http/Exceptions/MaintenanceModeException.php) will be available as `$exception`, so you can simply use `$exception->getMessage()` to access the message.

For example:
```
@extends('errors::layout')

@section('title', 'Service Unavailable')

@section('message', $exception->getMessage())
```

**Comment by staudenmeir** [comment]
Please close the issue.
