### ISSUE TITLE
Escaped @lang in 5.6 broke HTML entities

### ISSUE THREAD

**Issue by lexilya** [laravel/framework#25430]
- Laravel Version: 5.6.37
- PHP Version: 
- Database Driver & Version:

### Description:

d3c0a369057d0b6ebf29b5f51c903b1a85e3e09b broke all translations with HTML in them. Even if HTML may never have been officially supported in translations, there are default views which uses them.

### Steps To Reproduce:

Set your application to use the "simple-default" pagination, which has `@lang('pagination.next')` and `@lang('pagination.previous')` in them. It will escape the « and » characters.

**Comment by oltreseba** [comment]
Same on version 5.5.43

**Comment by brunogaspar** [comment]
https://github.com/laravel/framework/pull/25408#issuecomment-418123476

**Comment by laurencei** [comment]
Duplicate of #25515
