### ISSUE TITLE
Laravel 5.7 Upgrade Issue

### ISSUE THREAD

**Issue by vbasky** [laravel/framework#25435]
- Laravel Version: 5.6.35
- PHP Version: 7.1.16
- Database Driver & Version: MariaDB 10.3.8

### Description:

 Problem 1
    - The requested package laravel/framework 5.7.* is satisfiable by laravel/framework[5.7.x-dev] but these conflict with your requirements or minimum-stability.

### Steps To Reproduce:
composer update to a 5.6 Laravel project

Attached is the `composer.json`

```{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=7.0.0",
        "appstract/laravel-opcache": "^1.3",
        "fideloper/proxy": "~4.0",
        "laravel/framework": "5.7.*",
        "laravel/tinker": "~1.0",
        "stripe/stripe-php": "^5.7",
        "tcg/voyager": "^1.1",
        "voyager-themes": "^0.13.0"
    },
    "require-dev": {
        "filp/whoops": "~2.0",
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "~1.0",
        "phpunit/phpunit": "~6.0"
    },
    "autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    },
    "repositories": {
        "hooks": {
            "type": "composer",
            "url": "https://larapack.io"
        }
    }
}

**Comment by parasume** [comment]
It hasn't been released yet, that's why the dev version shows up

**Comment by devcircus** [comment]
And the default minimum-stability for composer.json is "stable", so composer will not allow the installation.

**Comment by vbasky** [comment]
Does that mean I can't upgrade to 5.7 at the moment?

**Comment by devcircus** [comment]
You just have to explicitly tell composer to allow the dev version. I think "5.7.*@dev" should work.

**Comment by devcircus** [comment]
If not, set the minimum stability to "dev" in your composer.json

**Comment by vbasky** [comment]
Voyager `tcg/voyager` scoffs at 5.7.0 saying its still not supported when added the dev flag, nonetheless 5.7 was supposed to released at the Laracon US happening now isn't it ?

**Comment by wilburpowery** [comment]
I think you can expect 5.7 to be released tomorrow. Today is a holiday in the US.

**Comment by devcircus** [comment]
Going to github.com/laravel/framework/releases should always be able to answer the question "Has X version been released yet."
