### ISSUE TITLE
Morph relationships does't support camel case database field name like 'userType'

### ISSUE THREAD

**Issue by jason-chang** [laravel/framework#25440]
- Laravel Version: 5.5.43
- PHP Version: 7.2.7
- Database Driver & Version: Mysql 5.7

### Description:
Morph relationships does't support camel case database field name;

### Steps To Reproduce:
this problem is because  line in `MorphToMany` class
```php
    public function __construct(Builder $query, Model $parent, $name, $table, $foreignPivotKey,
                                $relatedPivotKey, $parentKey, $relatedKey, $relationName = null, $inverse = false)
    {
        $this->inverse = $inverse;
        $this->morphType = $name.'_type';   // Notice: problem here 
        $this->morphClass = $inverse ? $query->getModel()->getMorphClass() : $parent->getMorphClass();

        parent::__construct(
            $query, $parent, $table, $foreignPivotKey,
            $relatedPivotKey, $parentKey, $relatedKey, $relationName
        );
    }
```

And line in `HasRelationships` trait 

```php
    protected function getMorphs($name, $type, $id)
    {
        return [$type ?: $name.'_type', $id ?: $name.'_id'];  // Notice: problem here 
    }
```
I think if we can add a configration in global database config file, like 'field_name_case'; and values can be `snake` or `camel` ?

**Comment by Propaganistas** [comment]
It surely does. Take a closer look at the [arguments list](https://github.com/laravel/framework/blob/4cb5bf13e0cd50015f8e6a420a52fa8b90758eb1/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php#L178) of `morphTo()`:

```php
public function morphTo($name = null, $type = null, $id = null, $ownerKey = null)
    {
        ....

        [$type, $id] = $this->getMorphs(
            Str::snake($name), $type, $id
        );
        
        ...
    }
```

This essentially means that if you **don't** provide the `$type` and `$id` parameter the field names are determined using snake case (`field_type`,  `field_id`).

So just extending your relation definition with your camel-cased field names should do the trick.

```php
public function user()
{
    return $this->morphTo('user', 'userType', 'userId');
}
```

**Comment by driesvints** [comment]
This is unfortunately by design and will probably not be changed anytime soon. There's also no way to defined this atm through the `morphToMany` method. I think its best to first discuss this in https://github.com/laravel/ideas if this is a wanted change. It'll definitely need to be done in a new major release to avoid breaks.

**Comment by mikkopursuittechnology** [comment]
Hi, Just wondering if this has been added into the roadmap?
