### ISSUE TITLE
L5.7 Undefined variable for Mail Vendor 

### ISSUE THREAD

**Issue by akr4m** [laravel/framework#25445]
- Laravel Version: 5.7.0

### Description:

Vendor mail html >
button.blade.php (Undefined color variable)
layout.blade.php
 in Laravel 5.6, it was working fine. Only problem with Laravel 5.7

**Comment by ristlin** [comment]
I'm having the same issue, but it only pops up when I run phpunit on Codeship. I think it may be related to the following: 

// Laravel 5.6...
{{ $foo or 'default' }}

// Laravel 5.7...
{{ $foo ?? 'default' }}

I will test now.
