### ISSUE TITLE
[5.7] Authenticate middleware now loads DI before checking authentication status

### ISSUE THREAD

**Issue by jslewis90** [laravel/framework#25446]
- Laravel Version: 5.7.0 & 5.7.1

### Description:
The new `app\Http\Middleware\Authenticate.php` file from 5.7 allows routes to try loading the dependency injections before checking if the user is logged in. This causes a status code of 404 to be given instead the user of being redirected to the login page in my tests since I don't mock creating the model in the tests to verify guests can't access the functionality.

Interestingly enough, the old Authenticate middleware that it extends works fine if used in the Kernel instead of the new file.

### Steps To Reproduce:
- Create a route to be guarded by the auth middleware
- On the route, use dependency injection to load a model
- Use a test like below to see the unexpected 404 result

```php
/** @test */
public function guests_may_not_access_this_functionality()
{
    // Not mocking up the model it should normally load for logged in users

    $this->withExceptionHandling()
         ->get('your-route-name-here')
         ->assertRedirect('/login');
}
```

**Comment by mvdnbrk** [comment]
Same issue here. Seems like `app\Http\Middleware\Authenticate.php` middleware doesn't get called at all.

**Comment by mvdnbrk** [comment]
routes/web.php:
```
Route::get('/users/{user}', 'UserController@show')->middleware('auth');
```

app/Http/Controllers/UserController.php:
```
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function show(User $user)
    {
        return $user;
    }
}
```

When I visit `/user/1` in my browser I do get a `302` status redirecting me to the login page.

Test:
```
/** @test */
public function assert_status_302()
{
     $response = $this->get('/users/1');

     $response->assertStatus(302);
}
```

1) Tests\Feature\ExampleTest::assert_status_302
Expected status code 302 but received 404.
Failed asserting that false is true.

**Comment by dmitry-ivanov** [comment]
Yep, same issue here.

It looks like an order of "route model binding" - "middleware" calls changed for 5.7.

For 5.6 middleware was the first.
For 5.7 - middleware called only if "route model binding" is ok.

Which is not right, in my opinion.
Unlogged users should not be able even to know does the proper resource exist or no.

**Comment by mvdnbrk** [comment]
That's right @dmitry-ivanov. Haven't got the time to look further in it.
Couldn't find what has changed since 5.6. Any suggestions?

**Comment by rookwood** [comment]
I ran into this earlier.  The problem stems from the fact that the `Authenticate` middleware is intended to be called in a [specific order](https://github.com/laravel/framework/blob/5.7/src/Illuminate/Foundation/Http/Kernel.php#L73) before applying developer-listed middleware.  In 5.7, it was changed to `App\Http\Middleware\Authenticate` but the priority still lists it as living under `Illuminate\Auth\Middleware\Authenticate`.

I fixed this by just adding that priority array to `App\Http\Kernel` and changing the reference to the userland class.  One could also chose to edit the [Kernel](https://github.com/laravel/laravel/blob/master/app/Http/Kernel.php#L54) to reference the original, framework-included middleware if no modifications are needed.

**Comment by dmitry-ivanov** [comment]
For the history, I'm adding @rookwood's PR here too:
https://github.com/laravel/laravel/pull/4757

So, probably an issue can be closed?
