### ISSUE TITLE
How can i show and hide my div with laravel fields (checkbox)

### ISSUE THREAD

**Issue by dra0w** [laravel/framework#25453]
I use laravel/frozennode adminstrator.

I need;

if i select  product parameter "az" checkbox in admin panel
`img class="filmparamboxs" src="/images/az.png"` after html show this code. 

https://imgur.com/a/xVIRQdf

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I suggest closing your issue ticket here? Instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.
