### ISSUE TITLE
make:controller --invokable produces "The --invokable option does not exist" error

### ISSUE THREAD

**Issue by bothy4g** [laravel/framework#25461]
- Laravel Version: 5.6.25
- PHP Version: 7.2.9
- Database Driver & Version: 5.5.61

### Description:
When attempting to create an API resource controller using the --invokable switch, the process fails and the following error message is displayed:

The "--invokable" option does not exist.

Running the php artisan make:controller command without the --invokable flag works as expected.
[](url)
### Steps To Reproduce:
Run the following command (taken straight from the [docs](https://laravel.com/docs/5.6/controllers#single-action-controllers) ):

`php artisan make:controller DeleteFutureGroupAssignmentController --invokable`

**Comment by AegirLeet** [comment]
This was added in 5.6.28. See https://github.com/laravel/framework/commit/530a07686c373950200da25ec050b265433fc624, https://github.com/laravel/framework/commit/b66d24c0d068eaa8398e79f02949d75a82a838eb, https://github.com/laravel/framework/commit/87e8857a38acf6a75ffc86c447252b7835548116.

**Comment by staudenmeir** [comment]
This feature requires Laravel 5.6.29.

**Comment by bothy4g** [comment]
Thanks for pointing that out. Upgraded `laravel/framework` to latest solved it.
