### ISSUE TITLE
http_only config not used when adding cookie to response in Illuminate\Foundation\Http\Middleware\VerifyCsrfToken

### ISSUE THREAD

**Issue by kkyeboah** [laravel/framework#25464]
- Laravel Version: 5.6.38

### Description:
The ```http_only``` key from config/session.php is not used in creating the cookie in ```Illuminate\Foundation\Http\Middleware\VerifyCsrfToken```.

```
protected function addCookieToResponse($request, $response)
{
    $config = config('session');

    $response->headers->setCookie(
        new Cookie(
            'XSRF-TOKEN', $request->session()->token(), $this->availableAt(60 * $config['lifetime']),
            $config['path'], $config['domain'], $config['secure'], false, false, $config['same_site'] ?? null
        )
    );

    return $response;
}
```

**Comment by kreitje** [comment]
I was going to submit a PR for this, but here is a StackExchange thread about it.  The content is available in the HTML already if you are using CSRF protection.

https://security.stackexchange.com/questions/175536/does-a-csrf-cookie-need-to-be-httponly

**Comment by barryvdh** [comment]
This is on purpose, but you can disable the cookie. See related PR https://github.com/laravel/framework/pull/24726

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
