### ISSUE TITLE
The EnsureEmailIsVerified redirect to the route

### ISSUE THREAD

**Issue by guillaumebriday** [laravel/framework#25470]
- Laravel Version: 5.7
- PHP Version: 7.2
- Database Driver & Version: Mysql 5.7

### Description:

The `EnsureEmailIsVerified` redirects to the route named `verification.notice` which does not allow us to handle it correctly with an API.

I think an exception could be thrown to catch it correctly, maybe ?

### Steps To Reproduce:

Add the middleware `verified` to a route and call it with JSON api.

**Comment by AkenRoberts** [comment]
This was just fixed in #25448. 👍

**Comment by guillaumebriday** [comment]
Ah exactly thanks !

The release has not been published yet, that's why I did not see it, sorry
