### ISSUE TITLE
Observers occasionally fails to fire after saved action

### ISSUE THREAD

**Issue by pirupius** [laravel/framework#25483]
- Laravel Version: 5.5.*
- PHP Version: 7.1.9
- Database Driver & Version: MYSQL 5.7.19

### Description:
We recently updated our app from Laravel 5.4 to 5.5 a couple about a month ago and about 5 days ago we started experiencing some irregularities with our observers. Our app is an accounting software and this is a typical flow of a basic transaction. 

1. Transaction details are entered and validated before submission and on success
2. The Transaction Journal entry and respective line items are created 
3. And if the above 2 are successful, the transaction is saved and the `observer` fires on a `saved` action 
 to increase the balance of the respective general ledger account.  

## The problem
In some unique scenarios all the above 2 steps run successfully but the observer either fails to fire or if at all it does, it fails to update the balances. 

## Question 
Is there a way to detect failed action inside an observer?  or at least trigger a failed response? 

Also if at all there's a better way we can achieve the same result, please advice.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.

**Comment by pirupius** [comment]
Hi @laurencei 
Thank you for your feedback. I did some hunting on the community forums and failed to find a similar scenario but regardless i'll share it and hopefully get a response from someone. 

As for the `issues/bugs with the framework code` is there a chance that something can be done about a failed observer or maybe adding fail safes in place incase of an exception?

**Comment by laurencei** [comment]
You can just catch the exception inside the Observer? Is there anything in your logs?

**Comment by pirupius** [comment]
Dint find any or rather couldn't pin point the exact moment when it failed.  Most because every time i tried to trigger a similar issue, i couldn't replay it and it's occurrences where only in production. No slack alerts where set either.

**Comment by laurencei** [comment]
Maybe put some logging inside the Observer, so that on production you can see if it got fired at all? I kind of feel the fact it is "random" and only in production points to some other flaw in the code?

**Comment by pirupius** [comment]
Is there a fail safe i don't know of cause i dint find one in the documentation, and it's a 1/1000 random event but i prefer it not happen at all. And lookig through the code was the first thing i did
