### ISSUE TITLE
Redis cache tags flush memory leak

### ISSUE THREAD

**Issue by doncaz** [laravel/framework#25482]
Laravel Version: 5.6.*
PHP Version: 7.2.*
Database Driver & Version: MYSQL 5.7.*
Cache Driver: Redis

we using provided Redis tagged cache to cache query results for models in this way:

`cache()->tags([model1, model2...])->remember(sql_query_hash, result_callback)`

and if in example after some time and a users peak one of tags in example `model1` have 500k of unique cached queries, and there comes update and need to do :

`cache()>tags([model1])->flush();`

my job gets allowed memory exhausted, for workers we have 128MB of memory. Yes I know if I would increase memory of workers I could flush then 1kk of keys etc. but its not a right way because we have exponential users increase and our project will grow, so maybe some of tags will have 10kk of keys on users peak, and how then I have to flush a cache for tag?

https://github.com/laravel/framework/blob/5.6/src/Illuminate/Cache/RedisTaggedCache.php#L174

this is how laravel flush tags keys, by retrieving all in memory then chunks it in memory again so this array_chunk double the memory usage after getting all keys, and then doing Redis::del operation to remove cached keys for this tag.

I don`t know how it call its a bug o not, but for me need some options does anyone dealing with that problem too, and maybe have some solutions?

**Comment by Kyslik** [comment]
Not sure if you noticed but you are linking to the [**5.7**](https://github.com/laravel/framework/blob/5.7/src/Illuminate/Cache/RedisTaggedCache.php#L174) but you claim to work with 5.6.*

**Comment by doncaz** [comment]
Nothing changed in 5.6 or 5.7

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
