### ISSUE TITLE
Value attribute not getting replaced properly for gt/gte/lt/lte validation rules

### ISSUE THREAD

**Issue by martinbean** [laravel/framework#25481]
- Laravel Version: 5.7.0 (and below)
- PHP Version: 7.1.14
- Database Driver & Version: N/A

### Description:
The `:value` attribute isn’t being replaced properly for `gt`/`gte`/`lt`/`lte` validation rules. When I specify a value, the error message always comes out as:

> The quantity must be greater than or equal 0.

Looking under the hood, it seems the replacer method is validating the _size_ rather than the integer value of the parameter.

### Steps To Reproduce:

Create a brand new application; placed this in a route:

```php
$validator = Validator::make(
    ['quantity' => 5],
    ['quantity' => 'gte:10']
);
```

Validation fails (as expected), but the error message is:

> The quantity must be greater than or equal 0.

I expect:

> The quantity must be greater than or equal 10.

**Comment by staudenmeir** [comment]
@Alymosul Can you explain why you used

```php
return str_replace(':value', $this->getSize($parameters[0], $this->getValue($parameters[0])), $message);
```
instead of just

```php
return str_replace(':value', $parameters[0], $message);
```

in #24135?

**Comment by Alymosul** [comment]
@martinbean Yes I confirm that this is a bug, I'll submit a PR to fix it. Thank you for pointing this out.

@staudenmeir The purpose of these rules at first was to compare two attributes(input fields) against each other, then I extended the functionality to include comparing against values but it seems i missed to check if you passed an attribute or a value in the ReplaceAttributes trait methods.

**Comment by staudenmeir** [comment]
Please close the issue.
