### ISSUE TITLE
Laravel Passport personal access token scope middleware

### ISSUE THREAD

**Issue by nuocgansoi** [laravel/framework#25484]
- Laravel Version: 5.7
- PHP Version: 7.1.3
- Database Driver & Version: MariaDB 10.0.36

### Description:
**Laravel version 5.4:**
`Route::middleware(['scopes:api', 'auth:api'])`
work.

**Laravel version 5.7:**
`Route::middleware(['scopes:api', 'auth:api'])`
result: `{"message":"Unauthenticated."}`

When I check on `Laravel\Passport\Http\Middleware\CheckScopes::handle()`
`$request->user()` is null

**Laravel version 5.7:**
`Route::middleware(['auth:api', 'scopes:api'])`
work.

I think someone need this.

**Comment by ThomHurks** [comment]
I had the same issue. A global API middleware stopped working after 5.7 because ```$request->user()``` was ```null```. I worked around it for now, but seems something changed in Laravel related to middleware.

**Comment by laurencei** [comment]
As suggested by @sisve - please report to https://github.com/laravel/passport/issues
