### ISSUE TITLE
Route group's 'as' parameter is prefixed to non-named routes, results in duplicates

### ISSUE THREAD

**Issue by martingrega** [laravel/framework#25496]
- Laravel Version: 5.5+, lower versions not tested

### Description:
Route group 'as' parameter is adding prefix to all routes in the group and results in duplicates. Is this expected behavior?
I think it should be prefixing only routes that are explicitly named and resources.

### Steps To Reproduce:
```
Route::group(['as' => 'admin.'], function() {
    Route::get('xxx')->name('xxx');
    Route::get('yyy');
    Route::get('zzz');
});
```

```
+--------+----------+-----+-----------+---------+------------+
| Domain | Method   | URI | Name      | Action  | Middleware |
+--------+----------+-----+-----------+---------+------------+
|        | GET|HEAD | xxx | admin.xxx | Closure | web        |
|        | GET|HEAD | yyy | admin.    | Closure | web        |
|        | GET|HEAD | zzz | admin.    | Closure | web        |
+--------+----------+-----+-----------+---------+------------+
```

**Comment by devcircus** [comment]
I'm pretty sure that's the point. If you don't want the prefix to apply to all routes in the group, leave off the "as" and name each route individually.

**Comment by laurencei** [comment]
Looks expected behaviour to me?
