### ISSUE TITLE
OptimizeCommand is back

### ISSUE THREAD

**Issue by bojcheski** [laravel/framework#25498]
Laravel Optimize Command is back, and causing some problems (if called, it tries to cache routes and the ones that use Closures throw an LogicException (src/Illuminate/Routing/Route.php:880) )

https://github.com/laravel/framework/pull/20851/

**Comment by bojcheski** [comment]
It is not a problem for me not using it. As a matter of fact I don't use it and I don't need it. I somehow installed some package that wasn't really updated and was using that command, and noticed the LogicException throwing. Digging it deeper seems the Optimize command was not included in the 5.7.1 tag, and came back in 5.7.2 tag, and that was the only reason I opened this issue, not that I need something get fixed

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not for ideas, suggestions etc. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. You are able to open a ticket at https://github.com/laravel/ideas

Alternatively you are able to open a PR using the Contributions guidelines: https://laravel.com/docs/5.7/contributions#which-branch

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
