### ISSUE TITLE
Using Generated Columns with Replicate causes error

### ISSUE THREAD

**Issue by newms87** [laravel/framework#25495]
- Laravel Version: 5.6
- PHP Version: 7.2
- Database Driver & Version: MySQL 8.0

### Description:
Using the laravel migrations, I added a storedAs generated column. On a Model using the table, when you try to call $new = $model->replicate() then $new->save() it will attempt to set the generated column causing a MySQL error:
```
SQLSTATE[HY000]: General error: 3105 The value specified for generated column 'is_something' in table 'testing' is not allowed. 
```

### Steps To Reproduce:
Create a Testing Model
```
class Testing extends Model {
    protected $table = 'testing';
}
```
Create the schema using a migration:
```
Schema::create('testing', function (Blueprint $table) {
        $table->increments('id');
        $table->boolean('is_something')->storedAs('id > 100');
});

```

On the Testing Model, replicate an instance and try to save it.
```
$testing = Testing::find(1);
$newTesting = $testing->replicate();

// This will throw a MySQL error 
$newTesting->save();
```

**Comment by staudenmeir** [comment]
Does the [StackOverflow answer](https://stackoverflow.com/a/52181337/4848587) solve your problem?

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by william-lohan** [comment]
Hello, I am experiencing a similar issue but the SO doesn't help me because I need to work with a number of different Models dynamically so the generated columns are not known and I'm not finding something like a  `isNotGenerated($key)`  on the Model class.
