### ISSUE TITLE
VerificationController extends Illuminate Controller

### ISSUE THREAD

**Issue by arxeiss** [laravel/framework#25503]
- This is about package `laravel/laravel` - but Issues there are not open
- Laravel Version: 5.7

### Description:
All controllers in `App\Http\Controllers\Auth` extends `App\Http\Controllers\Controller`, but `VerificationController ` extends `Illuminate\Routing\Controller`.

For consistency with others I would suggest to extend App Controller. Or is there any specific reason to not do this?

**Comment by Kocal** [comment]
This can be closed.
