### ISSUE TITLE
Task Scheduling work from database

### ISSUE THREAD

**Issue by MgHtinLynn** [laravel/framework#25500]
Task Scheduling with database as queue jobs with database jobs and fail jobs
option with default(current) and database
That will be smarter than current Task Scheduling.

**Comment by Kyslik** [comment]
If this is intended to be a feature request or some idea, it should be posted in [ideas issue tracker](https://github.com/laravel/ideas/issues/new)

**Comment by MgHtinLynn** [comment]
thanks @Kyslik
