### ISSUE TITLE
[5.7] Misleading error in Container

### ISSUE THREAD

**Issue by lk77** [laravel/framework#25509]
Hello

- Laravel Version: 5.7
- PHP Version: 7.2.1
- Database Driver & Version:Mysql 5.7

### Description:

When a provider does not exist, for example, if the package was uninstalled by composer,
there is a misleading error : 
```
Class hash does not exist
```
it could be another class, since it's the first class laravel will try to load (i could be auth for example).
I don't know why, but it seems that an unexisting class in a provider stop laravel from registering the remaining providers (i'm just guessing)

### Steps To Reproduce:

In AppServiceProvider 
```
if ($this->app->environment('local', 'testing')) {
            $this->app->register(NotExist::class);
        }
```

leads to :
```
In Container.php line 767:
                             
  Class hash does not exist
```

it's a very misleading error, i don't know if we could do someting about it.

thanks.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not for ideas, suggestions etc. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. You are able to open a ticket at https://github.com/laravel/ideas

Alternatively you are able to open a PR using the Contributions guidelines: https://laravel.com/docs/5.7/contributions#which-branch

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.

**Comment by lk77** [comment]
Seriously ?

**Comment by laurencei** [comment]
Hmmm... this might actually be a bug. I'll have a test shortly...

**Comment by lk77** [comment]
I think the issue is in Application, in register method
```
 public function register($provider, $force = false)
    {
        if (($registered = $this->getProvider($provider)) && ! $force) {
            return $registered;
        }

        // If the given "provider" is a string, we will resolve it, passing in the
        // application instance automatically for the developer. This is simply
        // a more convenient way of specifying your service provider classes.
        if (is_string($provider)) {
            $provider = $this->resolveProvider($provider);
        }

        // Try catch here ?
        // If something wrong throw exception provider X not working , or something like that ?
        if (method_exists($provider, 'register')) {
            $provider->register();
        }

        // If there are bindings / singletons set as properties on the provider we
        // will spin through them and register them with the application, which
        // serves as a convenience layer while registering a lot of bindings.
        if (property_exists($provider, 'bindings')) {
            foreach ($provider->bindings as $key => $value) {
                $this->bind($key, $value);
            }
        }

        if (property_exists($provider, 'singletons')) {
            foreach ($provider->singletons as $key => $value) {
                $this->singleton($key, $value);
            }
        }

        $this->markAsRegistered($provider);

        // If the application has already booted, we will call this boot method on
        // the provider class so it has an opportunity to do its boot logic and
        // will be ready for any usage by this developer's application logic.
        if ($this->booted) {
            $this->bootProvider($provider);
        }

        return $provider;
    }
```

**Comment by laurencei** [comment]
I cant replicate this. On a fresh Laravel install if I edit `app\Providers\AppServiceProvider.php`:

    public function register()
    {
        $this->app->register(NotExist::class);
    }

Then I get 

    FatalThrowableError (E_ERROR)
    Class 'App\Providers\NotExist' not found

**Comment by AegirLeet** [comment]
I don't see how the context method is related to this. If the container wasn't loaded and you tried using a Facade like Auth (or any other class that doesn't exist, like Foo::id()), you'd probably get an `Error` (https://secure.php.net/manual/en/class.error.php), which implements `Throwable`. Exceptions, such as `ReflectionException`, generally also implement the `Throwable` interface.

You should edit the `Container` and add something like `xdebug_print_function_stack()` (assuming you have Xdebug installed) right before line 767. That should at least give us an idea of where the error is coming from.

**Comment by lk77** [comment]
So,

i've found the problem,
the context method was reimplemented,
but the use Throwable was missing,
so the reflection exception was not catched.

When adding use Throwable,
i have the normal exception :
Class 'App\Providers\NotExist' not found

**Comment by totymedli** [comment]
For me this happened after I upgraded to Laravel 7. According to the upgrade guide `App\Exceptions\Handler` now uses `Throwable` instead of `Exception`. If you have traits used in this handler, update those too.

**Comment by alexkb** [comment]
If anyone else is coming across this issue and the above explanations/fixes don't resolve things for you, I found the issue occurred when I upgraded Composer to v2.x. To fix it, you can either downgrade back to Composer v1.x or if you don't want to do that, upgrade the Laravel patch version to a version that supports Composer 2. See this post here for a table of the minimum patch version to use for each Laravel release: https://github.com/composer/composer/issues/9340#issuecomment-716210369
