### ISSUE TITLE
Verification Email footer href link goes to 403 page

### ISSUE THREAD

**Issue by BITRU** [laravel/framework#25501]
- Laravel Version: 5.7.2
- PHP Version: 7.2.9
- Database Driver & Version: MySQL 5.7.23

### Description:
Verification Email generated to user have a wrong link in footer href.  Link goes to 403 page. 

`&amp;amp;signature= - extra amp; in href`

`<a href="https://XXX.test/email/verify/30?expires=1536313695&amp;amp;signature=810ede2e1c5e98693503cd86242cebd8157dc76d3f7c8dab6ff19666cee5f055" style="font-family: Avenir, Helvetica, sans-serif; box-sizing: border-box; color: #3869D4;">https://XXX.test/email/verify/30?expires=1536313695&amp;signature=810ede2e1c5e98693503cd86242cebd8157dc76d3f7c8dab6ff19666cee5f055</a></p>`

### Steps To Reproduce:
Generate Verification email

**Comment by laurencei** [comment]
Closing as duplicate
