### ISSUE TITLE
Cache Issue

### ISSUE THREAD

**Issue by sushantlp** [laravel/framework#25502]
hi,

i push laravel job via bitbuket. i run all command cache:clear and composer dump-autoload but new code not executed 
@taylorotwell @adnan5253

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I suggest closing your issue ticket here? Instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.

**Comment by sushantlp** [comment]
ok thanks

**Comment by rawzone** [comment]
@sushantlp However see this [issue](https://github.com/laravel/framework/issues/25451).
It seems like a sub folder is missing: `./storage/framework/cache/data`

And this makes the artisan cache:clear command fail at least under version 5.7. Simply creating the directory fixed this issue for me.

Hope this helps.
