### ISSUE TITLE
Collection map trim behaviour differs from map callback with trim

### ISSUE THREAD

**Issue by Sparclex** [laravel/framework#25549]
- Laravel Version: 5.7.2
- PHP Version: 7.1.3
- Database Driver & Version:

### Description:
When applying `trim` on a laravel collection using `map` where the second elements last char is a `1`. The `1` gets removed. When applying `trim` using `map` inside a callback, the `1` does not get removed. The two methods should however lead to the same result.

### Steps To Reproduce:
```php
$a = collect(['Sample type 1', 'Sample type 1', 'Sample type 1']);
$a->map('trim'); // ['Sample type 1', 'Sample type ', 'Sample type 1']
$a->map(function($item) { 
    return trim($item); 
}); // ['Sample type 1', 'Sample type 1', 'Sample type 1']

**Comment by Sparclex** [comment]
The item key is forwarded to the trim method and therefore the `1` gets removed in the second item. I think the map method is just not meant to be used like this. Therefore I close this issue

**Comment by cjke** [comment]
I've hit this exact thing a few times, usually dropping straight onto this github page - so I'll note down my approach. 

```
// A trim macro 
Collection::macro('trim', function ($character_mask = " \t\n\r\0\x0B") {
    return $this->map(function ($value) use ($character_mask) {
        return trim($value, $character_mask);
    });
});

// A more generic "mapValues" (name inspired by a similar function in lodash)
Collection::macro('mapValues', function (callable $callback, ...$args) {
    return $this->map(function ($value) use ($callback, $args) {
        return call_user_func_array($callback, array_merge([$value], $args));
    });
});

// Can be used to create your own trim:
$a = [' aaa ', ' bbb', 'ccc '];
collect($a)->mapValues('trim');

// Or other callable that takes multiple arguments
$wrap = function($value, $before, $after) {
    return $before . $value . $after;
};

$a = [' aaa', 'bbb', 'ccc'];
collect($a)->mapValues($wrap, '->', '<-');
```

**Comment by stevebauman** [comment]
For anyone else not looking to have to use a collection macro, you can use `str()->squish(...)`:

```php
$items = collect([' foo ']);

$items->map(str()->squish(...));

$items->all(); // ['foo']
```
