### ISSUE TITLE
File mimetype validation fails due to ExtensionGuesser and temp pathname

### ISSUE THREAD

**Issue by ryzr** [laravel/framework#25541]
- Laravel Version: 5.7.2
- PHP Version: 7.1.9
- Database Driver & Version: MySQL 5.7.22

### Description:
I'm currently validating files in my controller - I only want to allow text/csv mimetypes. However when I upload an image/svg file, it is still accepted.

### Steps To Reproduce:
```
$request->validate(['file' => 'file|mimetypes:text/*']);
```
Validation succeeds, even on a .svg file.

```
dd($request->file('file'), $request->file('file')->getMimeType());
```

Returns

```
UploadedFile {#304
  -test: false
  -originalName: "image.svg"
  -mimeType: "image/svg+xml"
  -error: 0
  #hashName: null
  path: "/private/var/tmp"
  filename: "phpoFTkcA"
  basename: "phpoFTkcA"
  pathname: "/private/var/tmp/phpoFTkcA"
  extension: ""
  realPath: "/private/var/tmp/phpoFTkcA"
  aTime: 2018-09-10 04:22:30
  mTime: 2018-09-10 04:22:30
  cTime: 2018-09-10 04:22:30
  inode: 17557656
  size: 250
  perms: 0100600
  owner: 501
  group: 0
  type: "file"
  writable: true
  readable: true
  executable: false
  file: true
  dir: false
  link: false
}

"text/plain"
```

I can see that the `validateMimetypes` method in `Illuminate\Validation\Concerns\ValidatesAttributes` uses the `getMimeType` method of the `UploadedFile` class, which relies on Symfony's ExtensionGuesser. The path "/private/var/tmp/phpoFTkcA" has no extension which is why text/plain is returned. `$uploadedFile->getClientMimeType()` would have returned the correct mimetype, but I'm not sure if this would have repercussions elsewhere.

**Comment by ryzr** [comment]
This issue was caused by the built-in magic database for PHP 7.1.19 being inaccurate.

**Comment by kingIZZZY** [comment]
@ryzr how did you fix this?

I'm suffering from this problem as well trying to upload a CSV file being incorrectly considered as a 'txt' extension file

**Comment by ryzr** [comment]
> @ryzr how did you fix this?
> 
> I'm suffering from this problem as well trying to upload a CSV file being incorrectly considered as a 'txt' extension file

Sorry - I know this won’t be the response you were looking for - but I just ended up accepting the text/plain mime type :/

I recall that the problem was caused by the “magic” database not having the text/csv mime type registered. I believe this file can be located at “/usr/share/mime/magic”. You could also try to update libmagic and see if that fixes anything. Sorry I couldn’t be of more help!
