### ISSUE TITLE
[5.7] cache:clear --tags=tag fails with redis

### ISSUE THREAD

**Issue by m-lotze** [laravel/framework#25547]
- Laravel Version: 5.7
- PHP Version: 7.1.20

### Description:
After upgrading to 5.7. this happens when using `php artisan cache:clear --tags=tag` with redis as cache driver:
`Failed to clear cache. Make sure you have the appropriate permissions.`

`php artisan cache:clear` works fine.

`RedisStore::flush()` returns `null` when using the tags option instead of `true`. So i think it actually completes the task successfully and only outputs the error.

Changing:

```
if (! $successful) {
    return $this->error('Failed to clear cache. Make sure you have the appropriate permissions.');
}
```

in `Illuminate\Cache\Console\ClearCommand.php` to:

```
if ($successful === false) {
    return $this->error('Failed to clear cache. Make sure you have the appropriate permissions.');
}
```

could solve this.

**Comment by Marat555** [comment]
@m-lotze I can't reproduce your problem.
When I use redis as cache driver and execute following console command
`php artisan cache:clear --tags=tag`
There is such an error 

>  BadMethodCallException  : This cache store does not support tagging.

And this is normal behavior

**Comment by X-Coder264** [comment]
@m-lotze I sent a PR (https://github.com/laravel/framework/pull/25744) to fix this.

@Marat555 No, that is not normal behavior. The only way that exception gets thrown is if the cache store does not have the `tags` method and the Redis store has that method which means that you are not using the Redis driver when you are running that command.

**Comment by Marat555** [comment]
@X-Coder264  Did ypu try to reproduce problem?

**Comment by X-Coder264** [comment]
@Marat555 Of course I did and I've managed to successfully reproduce it which is why I created the PR which fixes the problem.
