### ISSUE TITLE
collection random repeated

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [laravel/framework#25558]
Is it possible to add a parameter to the collection random method so it does never return the same item twice? like I need 3 ids, and it can return like [1,1,3], but I do not want it to be repeated, never

**Comment by staudenmeir** [comment]
Do you mean `$collection->unique()->random(3)`?

**Comment by diego-lipinski-de-castro** [comment]
No, I do not want the unique ids in the collection, they're already unique, I want that the random method do not return repeated items, if you have a collection like [1,2,3], and random it like

collect([1,2,3])->random(3);

it can return something like [1,1,3] or [2,3,2];

But I cant have repeated items in the result

**Comment by staudenmeir** [comment]
I assumed you have duplicate values because I can't reproduce this behavior. I called `random()` a million times and never got a result with repeating values.

**Comment by diego-lipinski-de-castro** [comment]
@staudenmeir just tested it and you're probs right, I'm closing for now, if happens again I will reopen
