### ISSUE TITLE
RefreshDatabase not refreshing MySQL tables when `processIsolation` is false

### ISSUE THREAD

**Issue by unlikenesses** [laravel/framework#25552]
- Laravel Version: 5.7.2
- PHP Version: 7.1.18
- Database Driver & Version: MySQL Ver 15.1 Distrib 10.3.7-MariaDB 

### Description:
When using the `RefreshDatabase` trait, my tables are not truncated at the beginning of each test. The tests therefore fail. They pass if I set `processIsolation` to `true`, but this makes them unusably slow.

**Comment by staudenmeir** [comment]
Please provide more details. What does your test look like?

**Comment by unlikenesses** [comment]
@staudenmeir Here's an example test which reproduces the problem:

```
class BugTest extends ApiTester
{
    use RefreshDatabase;

    public function setUp()
    {
        parent::setUp();

        $this->seedLanguages();

        factory('App\Theme')->create();
    }

    /** @test */
    public function bug_test_one()
    {
        factory('App\Box', 5)->create();
    }

    /** @test */
    public function bug_test_two()
    {
        factory('App\Box', 5)->create();

        var_dump(Box::count());
    }
}
```

When I run the entire class, the result of this `var_dump` is 10. I would expect it to be 5.

This is `seedLanguages`:

```
public function seedLanguages()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        DB::table('languages')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1');
        return [
            'en' => factory('App\Language')->create(['code' => 'en', 'default' => 1]),
            'fr' => factory('App\Language')->create(['code' => 'fr', 'default' => 0])
        ];
    }
```

(Note that in `seedLanguages` I have to manually truncate.)

**Comment by staudenmeir** [comment]
Please add the used models, migrations and factories.

**Comment by unlikenesses** [comment]
@staudenmeir Done. NB. the translatable models (using Spatie's Translatable package) have mutators which transform the posted data to a format usable by the package:

```
public function buildInput($languageEntries)
{
        if (! $languageEntries) return null;

        $data = [];

        foreach ($languageEntries as $languageEntry) {
            if (trim($languageEntry['text']) != '') {
                $language = Language::findOrFail($languageEntry['languageId']);
                $data[$language->code] = $languageEntry['text'];
            }
        }

        return json_encode($data);
}
```

**Comment by unlikenesses** [comment]
In the end I got around the problem by specifying the `id` of models when creating them via factories. E.g.
```
factory('App\Language')->create(['id' => 1, 'code' => 'en', 'default' => 1]),
```
