### ISSUE TITLE
[5.7] Why was removed "or" in blade

### ISSUE THREAD

**Issue by dka-develop** [laravel/framework#25576]
- Laravel Framework 5.7.2
- PHP Version: 7.2.9

_Error or New Feature?_

I use code in blade: 
`{{ $article->title or ' ' }}`

[5.6] -> framework/src/Illuminate/View/Compilers/Concerns/CompilesEchos.php

```php
public function compileEchoDefaults($value)
{
        return preg_replace('/^(?=\$)(.+?)(?:\s+or\s+)(.+?)$/si', 'isset($1) ? $1 : $2', $value);
}
```
From ver 5.7 code block was removed.

**Comment by antonkomarev** [comment]
Because you can use `??` in PHP7.
`{{ $article->title ?? ' ' }}`

**Comment by dka-develop** [comment]
OK, Now all the code requires an update.

**Comment by devcircus** [comment]
Plus there are many edge cases with "or" that you don't have to deal with when using "??".

**Comment by antonkomarev** [comment]
@dka-develop yes, but your app will be faster because this code will be executed on lower level.

**Comment by dka-develop** [comment]
@antonkomarev You Right!

**Comment by Yi-Frank** [comment]
but modifying the code is too cumbersome  .....   T.T

**Comment by antonkomarev** [comment]
@Yi-Frank Don't upgrade then.
