### ISSUE TITLE
[5.7] Hash::check does not work with $hashedValue = null like in 5.6

### ISSUE THREAD

**Issue by m-lotze** [laravel/framework#25578]
- Laravel Version: 5.7.2
- PHP Version: 7.1

I am using the package https://github.com/Adldap2/Adldap2-Laravel for several projects. This package uses the Hash::check function. In 5.6. this simply returned false for $hashedValue = null. Now it throws a RuntimeException.

This in any ..Hasher class:

```
if ($this->info($hashedValue)['algoName'] !== 'bcrypt') {
      throw new RuntimeException('This password does not use the Bcrypt algorithm.');
}
```

should be:

```
if (strlen($hashedValue) > 0 && $this->info($hashedValue)['algoName'] !== 'bcrypt') {
      throw new RuntimeException('This password does not use the Bcrypt algorithm.');
}
```

**Comment by laurencei** [comment]
Closing as duplicate of #25586
