### ISSUE TITLE
APP_LOG_LEVEL in local,error

### ISSUE THREAD

**Issue by FrancoRolandoRuben** [laravel/framework#25581]
- Laravel Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:

when APP_LOG_LEVEL has an invalid value, it affects the way of seeing all laravel in lan systems.
if APP_LOG_LEVEL = true in the local system, when you want to access the production server, it throws the same error as in local, only in the pc that has the value of APP_LOG_LEVEL wrong, the rest of the PCs see the production system without problems 

### Steps To Reproduce:

just put APP_LOG_LEVEL = true, in the local env file, and enter another laravel system hosted elsewhere, that is not local, and the error courre as if the other server was incorrectly configured

**Comment by AegirLeet** [comment]
So... you have two Laravel instances, one running locally and one on some server? And when you change APP_LOG_LEVEL to some invalid value on your local machine, this somehow also affects the server?
Maybe you accidentally uploaded your .env file to the server?

**Comment by devcircus** [comment]
Something doesn't make sense. The server has no way of knowing what you set log level to on local. You set environment variables on your server, not using an env file. 

Probably best to ask on laracasts, laravel.io, larachat slack or laravel discord.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
