### ISSUE TITLE
Auth::guard("")->attempt() session not persisting

### ISSUE THREAD

**Issue by terror2012** [laravel/framework#25587]
The issue is quite simple, when I do: 
`if(Auth::guard('test')->attempt($credentials))
        {
dd(Auth::guard('test');
            return redirect('/');
        }`
it shows the user correctly, but once I do the same DD at '/' it shows the user as null, and it passes guest() instead of check()

Once I pass the second argument as true (on attempt) it works perfectly. For the default guard, 
`if(Auth::guard('web')->attempt($credentials))
        {
            return redirect('/dashboard');
        }`
it works as intended, session going through to /dashboard.
I tried to change the session driver to redis, also did a full cache clear, including view:clear and route:clear, and the issue is still there.

Here is the code from auth.php

'test' => [
            'driver' => 'eloquent',
            'model' => App\Test::class,
        ],`

`'test' => [
            'driver' => 'session',
            'provider' => 'test'
        ],`

Here is the code from Test.php

```<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Test extends Authenticatable
{
    use Notifiable;
    public $timestamps = true;
    protected $table='test';
    protected $guarded = ['id'];

    protected $guard = 'test';

    protected $fillable = [
        'name', 'email', 'password',
    ];

    protected $hidden = [
        'password',
    ];
} 

What am I doing wrong here? Is it an actual issue with the framework, or did I do something really bad in the code?
Thanks.

**Comment by laurencei** [comment]
Are you always doing `dd()` after the login? You need to let Laravel set the response, session etc which `dd()` will not allow.

**Comment by terror2012** [comment]
I tried to dd as a debug, see if it's displaying the data or there's something wrong with authentication itself. On the dd after authentication, it does display the user, but on the next page the user is null.

**Comment by mfn** [comment]
Instead of `dd()` which terminates the request you can use `\Log::debug()` and watch the logfile (though the output isn't as convenient and you can't just dump complex objects AFAIK)

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by shahidkarimi** [comment]
I having the same issue in Laravel 8. Custom login in Laravel sucks!

**Comment by aedork** [comment]
Were you able to solve this issue?
