### ISSUE TITLE
[5.7] Hash::check breaks all apps with legacy hash

### ISSUE THREAD

**Issue by kamui545** [laravel/framework#25586]
```
>>> Hash::check('s3cr3t', '$1$0590adc6$WVAjBIam8sJCgDieJGLey0');
RuntimeException with message 'This password does not use the Bcrypt algorithm.'
```

**Use case:** We have applications with sha1 **AND** bcrypt passwords.
On successful login, an event is triggered to update the hash stored in DB to the stronger hash algorithm.

**Since the 5.7 update, all users with legacy passwords are not able to login anymore.**

Please, reconsider this check in the `Hash::check` method or make it optional, it should be consistent with how `password_verify()` works.

**Password hashing is not backward compatible nor future proof anymore...**

Breaking changes introduced in: https://github.com/laravel/framework/issues/24162 / https://github.com/laravel/framework/pull/24178
Related issues: https://github.com/laravel/docs/issues/4509, https://github.com/laravel/framework/pull/25468, https://github.com/laravel/framework/issues/25458

**Comment by kamui545** [comment]
In the meantime, for those stuck and who still would like to upgrade, here's how:

Create `app/Hashing/BcryptHasher.php`:

```php
<?php

namespace App\Hashing;

use Illuminate\Hashing\BcryptHasher as BaseHasher;

class BcryptHasher extends BaseHasher
{
    /**
     * Check the given plain value against a hash.
     *
     * @param  string  $value
     * @param  string  $hashedValue
     * @param  array  $options
     * @return bool
     */
    public function check($value, $hashedValue, array $options = [])
    {
        if (strlen($hashedValue) === 0) {
            return false;
        }

        return password_verify($value, $hashedValue);
    }
}
```

Then in your AppServiceProvider add:

```php
app('hash')->extend('legacy-bcrypt', function () {
    return new BcryptHasher($this->app['config']['hashing.bcrypt'] ?? []);
});
```

And set `'driver' => 'legacy-bcrypt'` in `config/hashing.php`

**Comment by crynobone** [comment]
I wonder why do we need to use `Hash::check()` for authentication verification if at the end we plan to support multiple hashing algorithm; `bcrypt` and `argon1`.

Shouldn't we respect whatever hashing used in the password as long as `password_verify()` can verify the password?

**Comment by crynobone** [comment]
This has been fixed in `5.7.4`

**Comment by laurencei** [comment]
Thanks @crynobone !

Closing as this issue has been resolved.

**Comment by mnabialek** [comment]
@crynobone  See me comment in https://github.com/laravel/framework/pull/25677 why we should still use `Hash::check()` if we don't want to break existing apps that uses custom hasher.

**Comment by kamui545** [comment]
Can we re-open this now that the partial fix has been reverted?

**Comment by robinvdvleuten** [comment]
This also breaks your app if the user does not have a password set. This wasn't the case before Laravel 5.7.

**Comment by Donovan-H** [comment]
#25468 has been merged, we await a new release...

**Comment by laurencei** [comment]
Closing as this issue has been resolved (again).
