### ISSUE TITLE
Router can't handle callables correctly

### ISSUE THREAD

**Issue by rapliandras** [laravel/framework#25588]
- Laravel Version: 5.7
- PHP Version: 7.2
- Database Driver & Version: irrelevant

### Description:

Laravel's router should take callables not just closures

```
Route::get("/workstation",Read::class);
```

instead of

```
Route::get("/workstation", function(){
    return (new \HR\Education\Action\Workstation\Read())();
});
```

### Steps To Reproduce:

...

**Comment by 36864** [comment]
Is this what you're looking for? https://laravel.com/docs/5.7/controllers#single-action-controllers

**Comment by rapliandras** [comment]
Does it have to be in the Controllers namespace? I want it to be elsewhere. 

```
In RouteAction.php line 89:

  Invalid route action: [App\Http\Controllers\HR\Education\Action\Workstation\Read].
```

**Comment by rapliandras** [comment]
Thanks. For further reference I'll paste how I achieved FQCNs to work:

RouteServiceProvider.php

```
    protected function mapEducationRoutes()
    {
        Route::middleware("web")
            ->namespace(null)
            ->group(base_path("routes/education.php"));
    }
```
