### ISSUE TITLE
Issue on sync with morphToMany

### ISSUE THREAD

**Issue by LonnyX** [laravel/framework#25584]
- Laravel Version: 5.6.38
- PHP Version: 7.2
- Database Driver & Version: MySQL 5.7.21 (Aws RDS)

### Description:
Since I updated to this latest version, I have a problem when I try to use sync method: 
 `$job->languagable()->sync($request->get('languages')); // let's say that $request->laguages = 1`

Maybe it's related to this commit: https://github.com/laravel/framework/commit/a8c505652b24ee7ca695033737ca7a992e750ac6
Because it was working well before and now I have this SQL Error

> SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect DOUBLE value: '4dd6ba80-9937-11e8-b3e5-eb46c2e5c9ea' (SQL: delete from `languagables` where `languagable_id` = 8903 and `languagable_type` = App\Models\Job and `language_id` in (2))

The GUID are used only on users table ... I don't know why it's on the error.

### Steps To Reproduce:
- AWS RDS (MySQL 5.7.21) with default config
- Create 3 models, exemple: User, Job, Language (in order to use the morphToMany)
- Try to `sync` language with User & Job
- It should fail

### FIX (temporary)
Just disable the Mysql strict Mode

**Comment by staudenmeir** [comment]
Please post the three models and their migrations.

**Comment by LonnyX** [comment]
```
class User extends Authenticatable
{
    use Notifiable, SoftDeletes, Sluggable;
    public $incrementing = false;
    protected $fillable = [
        'first_name',
        'last_name',
    ];

    protected static function boot()
    {
        parent::boot();

        static::creating(function ($model) {
            $model->{$model->getKeyName()} = Uuid::generate()->string;
        });
    }
    public function languagable()
    {
        return $this->morphToMany(Language::class, 'languagable')->withTimestamps();
    }
}
```

```
class Language extends Model
{
    protected $touches = ['jobs'];

    public function jobs()
    {
        return $this->morphedByMany(Job::class, 'languagable');
    }
}
```

```
class Job extends Model
{
    use SoftDeletes;
    
    public function languagable()
    {
        return $this->morphToMany(Language::class, 'languagable')->withTimestamps();
    }
}
```

```
Schema::create('users', function (Blueprint $table) {
        $table->uuid('id')->primary();
        $table->string('email')->unique();
        $table->string('password')->nullable();
        $table->rememberToken();
        $table->timestamps();
        $table->softDeletes();
    });

Schema::create('jobs', function (Blueprint $table) {
        $table->increments('id');
        $table->string('slug')->index();
        $table->uuid('user_id')->index()->nullable();
        $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
        $table->string('title')->nullable()->index();
        $table->text('description')->nullable();
        $table->string('location')->nullable()->index();
        $table->timestamps();
        $table->softDeletes();
    });

Schema::create('languages', function (Blueprint $table) {
        $table->increments('id');
        $table->string('code');
        $table->string('name');
        $table->timestamps();
    });

Schema::create('languagables', function (Blueprint $table) {
        $table->increments('id')->unsigned();

        $table->integer('language_id')->unsigned()->index();
        $table->foreign('language_id')->references('id')->on('languages')->onDelete('cascade');

        $table->string('languagable_id')->index();
        $table->string('languagable_type')->index();

        $table->timestamps();

});
```

**Comment by staudenmeir** [comment]
Which Laravel version did you use before the update? Do you know whether the MySQL version changed in the meantime?

Can you reproduce this issue on a fresh Laravel installation?

**Comment by LonnyX** [comment]
@staudenmeir hmm, this was working before... I'll try and let you know. 

Should this case be handled by Laravel?

**Comment by staudenmeir** [comment]
Does the cast work for you?

**Comment by LonnyX** [comment]
Oops, I forgot to try it. I'll try to do it this week

**Comment by LonnyX** [comment]
@staudenmeir Oki, the casts works fine. 

But, should this be handled by Laravel ? I think, it should.

**Comment by staudenmeir** [comment]
I don't think it's Laravel's responsibility to handle this. I'm not sure this would even be possible.

**Comment by LonnyX** [comment]
Ok, so I'll close the issue. Thanks
