### ISSUE TITLE
Can't comment a script tag in blade

### ISSUE THREAD

**Issue by Itemshopp** [laravel/framework#25592]
- Laravel Version: 5.5
- PHP Version: 7.1
- Database Driver & Version: MariaDB  

### Description:

I added a partial in my <head> tag in app.blade.php 
That partial has a simple <script> tag with some silly code in it

I decide to comment it with the blade comment {{--<script>  </script--}}

It does not only hide the code , it adds the full script code with blade comment in the <body> tag

### Steps To Reproduce:

1. Create a partial with a <script> tag in it and its </script> end tag and code in it 
2. add an include in the <head> tag
3. blade {{-- comment the entire script code with tags in your partial and see what happens , the code is still read

### EDIT

Try to add that script in your partial 

```
{{-- <script>
window.trans = <?php

// copy all translations from /resources/lang/CURRENT_LOCALE/* to global JS variable

$lang_files = File::files(resource_path() . '/lang/' . LaravelLocalization::getCurrentLocale());
$trans = [];
foreach ($lang_files as $f) {
    $filename = pathinfo($f)['filename'];
    $trans[$filename] = trans($filename);
}
echo json_encode($trans);
?>;
</script> --}}
```

Thanks for your help, I am perhaps making a huge mistake, I'm a Laravel amateur and kind of beginner

**Comment by m1guelpf** [comment]
Could you share the partial?

**Comment by Itemshopp** [comment]
Thanks for your quick answer , here's my partial : 

I think it is related with the <?php element. 

```
{{-- <script>
window.trans = <?php

// copy all translations from /resources/lang/CURRENT_LOCALE/* to global JS variable

$lang_files = File::files(resource_path() . '/lang/' . LaravelLocalization::getCurrentLocale());
$trans = [];
foreach ($lang_files as $f) {
    $filename = pathinfo($f)['filename'];
    $trans[$filename] = trans($filename);
}
echo json_encode($trans);
?>;
</script> --}}
```

**Comment by rodrigopedra** [comment]
Just tried and it worked, change the raw php tags `<?php ... ?>` to their blade equivalent directive: `@php @endphp`.

~~~php
{{-- <script>
window.trans = @php

// copy all translations from /resources/lang/CURRENT_LOCALE/* to global JS variable

$lang_files = File::files(resource_path() . '/lang/' . LaravelLocalization::getCurrentLocale());
$trans = [];
foreach ($lang_files as $f) {
    $filename = pathinfo($f)['filename'];
    $trans[$filename] = trans($filename);
}
echo json_encode($trans);
@endphp;
</script> --}}
~~~

I didn't dig in the code to know why, but I am guessing raw php tags have a higher priority when compiling the views.

**Comment by browner12** [comment]
I'm not understanding something here. why are you putting actual code inside of a comment? If you don't want the code to execute, just don't write it.

Am I missing something?

**Comment by rodrigopedra** [comment]
Maybe @Itemshopp  just wants to debug something...

But the point was that Laravel was running the commented out code when it was expected not to.

**Comment by devcircus** [comment]
Blade comments are for actually adding comments. Search the repo for similar issues. This is simply one of the limitations of blade.

**Comment by Itemshopp** [comment]
Exactly, I wanted to debug a thing without that script and I found that particularity.
I haven't thought profoundly enough about that blade thing. 

<?php == @php
?> == @endphp

Of course, thanks a lot @rodrigopedra !
