### ISSUE TITLE
Undocumented "breaking change" in mail templates

### ISSUE THREAD

**Issue by CodeCooler** [laravel/framework#25597]
- Laravel Version: 5.7.0

### Description:
This appears to be a documentation issue rather than an actual bug.

After updating a 5.6 project to 5.7, I noticed the "Reset Password" button in emails sent to users was not showing up. The reason for this appears to be the change in the "color" options between versions. In 5.7, supported colors are 'primary', 'success', and 'error,' but in 5.6, the options were 'blue,' 'green' and 'red.' 

Because I had previously published the vendor files, my 5.6 stylesheet did not contain the new designators, and the buttons did not render properly (screenshots below).

Doing the following within the top project directory did the trick, though:

``` 
cp vendor/laravel/framework/src/Illuminate/Mail/resources/views/html/themes/default.css resources/views/vendor/mail/html/themes/default.css
```

Not a huge deal, but should probably be noted within the 5.6 -> 5.7 upgrade guide. 

### Steps To Reproduce:

1. Create a project in 5.6.
2. `php artisan vendor:publish --tag=laravel-mail` (At this point, password reset emails should look fine)
3. Upgrade to 5.7 (At this point, password reset emails look clumsy at best).
4. (Bonus): Copy the stylesheet from the vendor directory into the previously published mail themes directory, and all appears to work again.

### Before & After Upgrade Screenshots

Screenshot from 5.6:

![2018-09-12 at 3 54 pm](https://user-images.githubusercontent.com/7704047/45449785-1d768b00-b6a4-11e8-8178-52e2ef8cda60.png)

Screenshot from 5.7:

![2018-09-12 at 3 53 pm](https://user-images.githubusercontent.com/7704047/45449747-0172e980-b6a4-11e8-99da-038b2079aee4.png)

**Comment by staudenmeir** [comment]
Can you close the issue?

**Comment by CodeCooler** [comment]
Looks like @dwightwatson beat me to it. Thanks, and closed.
