### ISSUE TITLE
Service Container breaks the PSR-11 ContainerInterface contract

### ISSUE THREAD

**Issue by Shawty81** [laravel/framework#25590]
- Laravel Version: 5.5+

### Description:
I think the current implementation of PSR-11 breaks the contract. For example I've made a composer package that can run independently from any framework, as long as you provide a PSR-11 compliant Container.

The interface only describes the has() and get() methods but the has() returns false on autowired classes. The only way to get my code to work with the Laravel Container is to use the make() method as I refuse to bind hundreds (if not thousands) of classes from the multiple Laravel repositories I maintain and their respective required composer packages. As the make() method is not defined in the PSR, this means the Laravel Container breaks the contract and I have to add some Laravel specific code.

### Steps To Reproduce:
I've made a simplified version of a Factory class to state whats wrong with the current implementation
```
<?php

namespace Vendor\Package;

class Factory {

    private $container;

    public function __construct(\Psr\Container\ContainerInterface $container)
    {

        $this->container = $container;

    }

    public function get($param)
    {

        // Do some stuff to generate a class name
        $class = $param;

        if ($this->container instanceof \Illuminate\Container\Container) {
            if (!class_exists($class)) {
                throw new ClassNotFoundException();
            }

            return $this->container->make($class);
        }
        else {
            if (!$this->container->has($class)) {
                throw new ClassNotFoundException();
            }

            return $this->container->get($class);
        }

    }

}
```

**Comment by antonkomarev** [comment]
But Laravel Container implements ContainerInterface since 5.5: https://github.com/laravel/framework/blob/5.5/src/Illuminate/Container/Container.php
It was introduced in PR #19822

**Comment by Shawty81** [comment]
@antonkomarev Yes, but the implementation is done incorrectly. The docs in the interface for the has() method say: 

> Returns true if the container can return an entry for the given identifier. Returns false otherwise.

The Service Container can return an entry for a unbound identifier if the identifier resolves to a class, thus has() should return true. But currently has() always returns false if the identifier is not bound.

**Comment by antonkomarev** [comment]
@Shawty81 propose solution in PR to the master branch (v5.8), I think if it will implement PSR-11 correctly Taylor will merge it.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not for ideas, suggestions etc. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. You are able to open a ticket at https://github.com/laravel/ideas

Alternatively you are able to open a PR using the Contributions guidelines: https://laravel.com/docs/5.7/contributions#which-branch

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
