### ISSUE TITLE
Returning a view with session variable

### ISSUE THREAD

**Issue by sadnub** [laravel/framework#25600]
- Laravel Version: 5.6.38
- PHP Version: 7.2
- Database Driver & Version: MySQL

### Description:
I came across this issue and my code was working at one point. My blade template won't show the message variable I pass to the view.

### Steps To Reproduce:
Running code in controller method
`return view('auth.register')->with('message', 'This is a message');`

In View
`{{ session('message') }}` is null
`@if session->has('message')` also doesn't work

I have also tried
`view('auth.register', ['message' => 'This is a message']);`

Is this a bug or am I doing something wrong?
Thanks!

**Comment by devcircus** [comment]
In your view, just use $message. It's not in your session.

**Comment by sadnub** [comment]
That worked! I was doing something similar with redirect()->back()->with() and it puts it in session data so I figured the view helper did the same.

Thanks!

**Comment by ahmedhamza1001** [comment]
but this is not session its a varaiable session appear one time then disappears , but this still appears @devcircus

**Comment by advename** [comment]
+1, I've seen so many guides an laracast/stackoverflow answers that use the `->with("error","No milk left")` setup so one expects that it's also available on the `return view()` method.

First after some time debugging and more research have i figured out that `->with()` is not available on `view()`.
