### ISSUE TITLE
[5.7] Policies don't redirect unauthenticated users to login page

### ISSUE THREAD

**Issue by anneheijink** [laravel/framework#25607]
- Laravel Version: 5.7.2
- PHP Version: 7.2.7
- Database Driver & Version: MySQL 5.7.23

### Description:
Laravel 5.7 introduced a new feature to allow guest authorization in policies. This is great, but I come across one problem. When guest users are not authorized to perform an action a 403 error is thrown instead of the user being redirected to the login page.

### Steps To Reproduce:
Create an action guarded by a policy which allows guests (a question mark in front of the first argument), then deny access for that guest.
````php
class ItemPolicy {
    use HandlesAuthorization;

    public function view(?User $user, Item $item) {
        return false;
    }
}
````
### Proposed solution
To overcome this, the `deny` method of the `Illuminate\Auth\Access\HandlesAuthorization` trait can be updated from:
````php
protected function deny($message = 'This action is unauthorized.') {
    throw new AuthorizationException($message);
}
````
to something like this :
````php
protected function deny($message = 'This action is unauthorized.') {
    if(Auth::guest())
        throw new AuthenticationException($message);
    else
        throw new AuthorizationException($message);
}
````
I am willing to create a PR for this, but since I'm not sure if the current behaviour is meant this way and it would be my first PR, I want to discuss it with you first.

**Comment by laurencei** [comment]
Hi @anneheijink ,

You are able to discuss ideas at https://github.com/laravel/ideas

However, given this is a small change, you might as well just create a PR for it, and include your "reasons", then let Taylor decide.

I'll close this ticket, as it is not a framework bug.

Let me know if you need anything else.
