### ISSUE TITLE
Illuminate\Foundation\Testing\TestCase has limitation in testing request headers 

### ISSUE THREAD

**Issue by scil** [laravel/framework#25601]
- Laravel Version: 5.6.28
- PHP Version: 7.2

### Description:

Illuminate\Foundation\Testing\TestCase would make an application and then  include web.php (by \App\Providers\RouteServiceProvider), and at last phpunit call `MakesHttpRequests::call()` where request headers can not come from test functions.

### Steps To Reproduce:

1. ` artisan make:test HeaderTest`

2. make this test function
```
    public function testNoLocale()
    {
        $lang = 'zh';

        $response = $this->withHeaders(
           ['Accept-Language' => $lang,]
        )->get('/loc');
       
       $response->assertSeeText($lang);
     }

```

3. edit `routes/web.php`
```
    $locale = $_SERVER['HTTP_ACCEPT_LANGUAGE'];
    Route::group(['prefix' => $locale,], function() use ($locale) {
               Route::get('/loc', function() use ($locale){
                   return return $locale;
                });
    });

```

4. `vendor/bin/phpunit  --stop-on-failure    --filter  HeaderTest `

**Comment by X-Coder264** [comment]
That is not a "limitation". You are not supposed to use PHP superglobals in your code. You should get the "Accept-Language" header from the request object and the test will pass:

```php
use Illuminate\Http\Request;

Route::get('/loc', function (Request $request) {
    return $request->header('Accept-Language');
});
```

**Comment by scil** [comment]
Thank you.

But $request is used in routes/web.php by [laravel-localization](https://github.com/mcamara/laravel-localization)

```
Route::group(['prefix' => LaravelLocalization::setLocale()], function()
{
	/** ADD ALL LOCALIZED ROUTES INSIDE THIS GROUP **/
	Route::get('/', function()
	{
		return View::make('hello');
	});

	Route::get('test',function(){
		return View::make('test');
	});
});
```

`LaravelLocalization::setLocale()`  calls app('request')

**Comment by X-Coder264** [comment]
Yeah, that package is also using the request object (just like my example above) and not the PHP superglobal so I don't understand what are you trying to say.

**Comment by scil** [comment]
routes/web.php is included before Illuminate\Foundation\Testing\Concerns::call()

so routes/web.php can  not use the info provided by tests
```
 $response = $this->withHeaders( ['Accept-Language' => $lang,] )->get('/loc');
```

**Comment by laurencei** [comment]
As described by @X-Coder264, you should not use the superglobals directly.
