### ISSUE TITLE
Invalid configuration prefix using phpredis

### ISSUE THREAD

**Issue by ivoth** [laravel/framework#25619]
- Laravel Version: 5.6.28
- PHP Version: 7.1.18
- ext-redis Version: 4.1.1
- Redis Cluster Version: 3.2.10

### Description:

Redis client uses `phpredis` to set the prefix invalid.

It is normal to use `predis`.

### Steps To Reproduce:

1. `config/database.php`:

```php
'redis' => [

        'client' => 'phpredis',

        'options' => [
            'cluster' => 'redis',
        ],

        'clusters' => [
            'options' => [
                'prefix' => 'prefix:',
            ],

            'default' => [
                [
                    'host' => env('REDIS_CLUSTER_HOST_1', '127.0.0.1'),
                    'port' => env('REDIS_CLUSTER_PORT_1', 6379),
                ], [
                    'host' => env('REDIS_CLUSTER_HOST_2', '127.0.0.1'),
                    'port' => env('REDIS_CLUSTER_PORT_2', 6379),
                ], [
                    'host' => env('REDIS_CLUSTER_HOST_3', '127.0.0.1'),
                    'port' => env('REDIS_CLUSTER_PORT_3', 6379),
                ], [
                    'host' => env('REDIS_CLUSTER_HOST_4', '127.0.0.1'),
                    'port' => env('REDIS_CLUSTER_PORT_4', 6379),
                ], [
                    'host' => env('REDIS_CLUSTER_HOST_5', '127.0.0.1'),
                    'port' => env('REDIS_CLUSTER_PORT_5', 6379),
                ], [
                    'host' => env('REDIS_CLUSTER_HOST_6', '127.0.0.1'),
                    'port' => env('REDIS_CLUSTER_PORT_6', 6379),
                ],
            ]
        ],
    ],
```

1. use:

> `cache.prefix` default is ` _cache `

```php
\Illuminate\Support\Facades\Cache::put('test', time(), 60);
```

In fact, the key in redis is `_cache:test` instead of the expected `prefix:_cache:test`

If the client uses `predis`

```php
'redis' => [

        'client' => 'predis',

        'options' => [
            'cluster' => 'redis',
        ],

        'clusters' => [
            'options' => [
                'prefix' => 'prefix:',
            ],
          ...
        ],
    ],
```

Then the key written is the correct `prefix: _cache:test`

Can you help me?

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
