### ISSUE TITLE
Carbon::now()->format(H:i:s) fetch time from server cache

### ISSUE THREAD

**Issue by ashishbansal-kmc** [laravel/framework#25615]
Carbon method fetch server previous time during 5 minutes interval in cron.

Example: my cron hit after every 5 minutes. i was assigning file_name with carbon::now()->format(H:i:s)  method.
But when again cron hit carbon method method fetch previous time not current time and seconds.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I suggest closing your issue ticket here? Instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.
