### ISSUE TITLE
Transaction should ROLLBACK on False result

### ISSUE THREAD

**Issue by sharifzadesina** [laravel/framework#25627]
The database transaction should rollback on false result,
Imagine this is our model:
```php
class User extends Model
{
    public static function boot()
    {
        static::saving(function () {
            return false;
        });
    }
}
```
And the transaction:
```php
$saved = DB::transaction(function () {
    $saved = true;
    $saved = $saved && $anotherModel->save();
    $saved = $saved && $user->save();
    return $saved;
});
```
As you know the `$anotherModel->save()` will work but the `$user->save()` will fail without any exception, so the transaction won't rollback.

**Comment by mfn** [comment]
> The database transaction should rollback on false result,

You fail to provider an argument as to why this is useful.

Also: if _you_ really need it I believe it's pretty easy to wrap `DB::transaction()` with your own logic, honoring the returned value of the closure.

**Comment by sharifzadesina** [comment]
@mfn Why transactions are usefull? they are usefull to make sure all queries run successfully together. so this is why we need this option.
How can I wrap the function while you COMMIT when the clouser run ends? (See the code [here](https://github.com/laravel/framework/blob/5.7/src/Illuminate/Database/Concerns/ManagesTransactions.php#L29-L31))
But I can create new function which is not good idea.
Without this option, transactions are actually useless.

**Comment by thecrypticace** [comment]
**This would be a breaking change.**

I also will say that if you feel that this is a pattern you have to use there's a structural problem with your code or your approach. Transactions only rollback when an error occurs. Returning false from a model observer prevents it from being saved, this is not _necessarily_ indicative of an error. I recommend throwing an exception instead if you are really running into an error which must rollback the containing transaction.

If you **must** take your outlined approach then throw an exception when you detect result is `false`. However, I will maintain that this is likely to be indicative of a problem with the approach you're taking to solve whatever it is you're encountering.

```php
try {
    $saved = DB::transaction(function () {
        $saved = true;
        $saved = $saved && $anotherModel->save();
        $saved = $saved && $user->save();

        if (! $saved) {
            throw new RuntimeException("Unable to save data");
        }

        return $saved;
    });
} catch (RuntimeException $e) {
    $saved = false;
}
```

**Comment by sharifzadesina** [comment]
@thecrypticace Yes it is a breaking change and I didn't say implement it right now ;)
but no it is not a design problem as i told, transactions are to make sure a bunch of queries run together, when one of them doesn't run we should ROLLBACK others.

**Comment by thecrypticace** [comment]
Right, **when there is an error**. This is denoted in PHP by using Exceptions.

**Comment by thecrypticace** [comment]
You _can_ also use the beginTransaction and commit/rollback primitives instead of the closure method if you want more control over when things get rolled back.

**Comment by sharifzadesina** [comment]
@thecrypticace No, when some of queries fail :)
this fail can be cause of error, or can have logical reasons, but it is failed and the transaction should rollback.

**Comment by thecrypticace** [comment]
> No, when some of queries fail.

A query **failure** is _ALWAYS_ denoted by an exception thrown by PDO. Period.<sup>1</sup> And would be rolled back by virtue of an exception being thrown.

An error because of _logical_ reasons is from a **validation** failure of some kind. Your validation is possibly in the wrong place.  In any case, if you're turning false to denote failure instead of using exceptions it is up to _you_ to handle the rollback. By throwing an exception inside `transaction()` or dropping down to using `DB::beginTransaction()` and `DB::commit`/`DB::rollBack()`.

Treating `false` as a sentinel for rollback is generally a bad idea and something that would certainly be considered an anti-pattern. Please use proper errors / exceptions. It makes developing much more future proof and easier to debug, **especially** in team environments.

<sup>1</sup> Technically, you can turn them off if you really want to but that's not the point here

**Comment by sharifzadesina** [comment]
@thecrypticace sometimes you just return false when something is wrong. true? we don't always throw exception.

**Comment by thecrypticace** [comment]
There's nuance that's kind of hard to get across without concrete code examples, but generally, no.

**Comment by sharifzadesina** [comment]
If it is generally no so why it exists in all before events?
In all events with "Continuing Verbs" you can return `false` and stop the process to continue.
`saving`, `updating`, `creating`, etc.
In GENERAL, it is yes.

**Comment by thecrypticace** [comment]
By using `return false` you can prevent the save from happening. This is not the same thing as an error occurring or needing a rollback.

My final point: Rollback triggers automatically on error. `return false` is NOT automatically indicative of an error (whereas an Exception is 100% of the time indicative of an error). Therefore, no rollback should occur. If your code requires that the situation be different, it's up to you to handle it. Not the framework. The framework is for handling common cases. return false == error is not a common case (nor should it ever be).

I'm gonna bow out of this one for now.

**Comment by sharifzadesina** [comment]
`return false` in `save` method means `false`, means the query failed,
as long as we can prevent model by `return false` this option MUST exist in the transaction of the framework.
that's all, now what you think, is just your own.
