### ISSUE TITLE
Verification url needs the user to be logged in

### ISSUE THREAD

**Issue by davidjr82** [laravel/framework#25620]
- Laravel Version: 5.7

### Description: 
With the new email verification feature, when a user has registered and receives the verification email, if he has logged out before he clicks the link, the site asks for credentials and afterwards redirects to the verification resend page. I think the verification behaviour wouldn't need to be done with an authenticated user, or, at least, after authenticate, fill the email_verified_at column and redirect him to home page.

### Steps To Reproduce: 
* Install a fresh Laravel 5.7
* php artisan make:auth
* add verify => true in web.php to enable email verification feature
* register as a new user
* Log out
* Check verification email and click the button to evrify your email
* Now you are asked to log in again
* After login, you see the verify.resend route instead the home page as would be expected. At this point, you only can ask to generate a new verify email, so you can click it once you are logged in.

**Comment by reefki** [comment]
I Just tested with Laravel 5.7.3 and everything seems to be fine. Register a new user, open the verification link on an incognito window, after logged in the site redirects me to the homepage and I see the user has been marked as verified in the database.

**Comment by davidjr82** [comment]
Hi @reefki , thanks for check it. I don't know what happened, it is working for me too now.

Thanks again.
