### ISSUE TITLE
Eloquents whereNot() method does not work and produces wrong query

### ISSUE THREAD

**Issue by jannis-a** [laravel/framework#25630]
- Laravel Version: 5.7.3
- PHP Version: 7.2.10
- Database Driver & Version: php-pgsql 7.2.10

### Description:
There `whereNot()` method from Eloquent does not work. It raises an exception that a column on the database table could not be found. The query it generates is not correct or not as I expected.

**Example:**
```php
Permission::whereNot('name', 'read users')->toSql()
```

**Result:**
```sql
select * from "permissions" where "not" = ?
```

**Expected:**
```sql
select * from "permissions" where not "name" = ?
```

### Steps To Reproduce:
Make a simple query like this :
```php
Permission::whereNot('name', 'read users')->get()
```

Will raise this exception:
```
Illuminate/Database/QueryException with message 'SQLSTATE[42703]: Undefined column: 7 ERROR:  column "not" does not exist
LINE 1: select * from "permissions" where "not" = $1
                                          ^ (SQL: select * from "permissions" where "not" = name)'
```

**Comment by decadence** [comment]
Eloquent has no method `whereNot` I guess? And it converts query by some magic and "not" become column name. For example you can use where<Attribute>(value) <-> `where("attribute", "=", value)`.
You need `where("name, "!=", "read users")->get()`

**Comment by jannis-a** [comment]
Yeah, I rechecked #24072 and saw it was rejected - thought it was merged...

My bad.
