### ISSUE TITLE
Laravel 5.7 validation rule When validation fails it return 404 error

### ISSUE THREAD

**Issue by richard457** [laravel/framework#25639]
- Laravel Version:5.7
- PHP Version:7.2
- Database Driver & Version:mysql

### Description:
When using FormRequest to validate request when one validation fails it return 404 error instead of an actual array of errors as normal.

**Comment by waitaamon** [comment]
Make sure your headers are properly set.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
