### ISSUE TITLE
Application->register() BC break

### ISSUE THREAD

**Issue by andig** [laravel/framework#25643]
With https://github.com/laravel/framework/pull/25028 our CI tests are failing on PHPstan since the function signature has changed. Its not a major thing but I'm wondering how we as a supporting library can cleanly support multiple Laravel versions with this change?

**Comment by brunogaspar** [comment]
Depends on your use case, if you follow Semantic Versioning or if you follow the Laravel Versioning which is `parading.minor.patch` or if you follow something else?

I personally follow Semantic Versioning, therefore, when a new `minor` version of Laravel is released, i do a new `major` on my library.

This gives me flexibility to support old versions of Laravel but avoid these nasty breaking changes.

**Comment by sisve** [comment]
To clarify; yes, it's an obvious breaking change. Most changes to method signatures are. However, it's targeting an non-released Laravel version (the master branch which is currently the future 5.8 release) and is considered okay. We allow breaking changes between major releases (as in between 5.7 and 5.8).

The versioning scheme in use helps communicate how breaking changes are handled, not determining if something is a breaking change or not.

You probably need to have one code-base per Laravel release. This is often (always?) done by having one package branch per Laravel release. So your package' 5.8 branch (if I may suggest the name...) would only support 5.8. You _may_ be able to have one branch for many Laravel releases, but that could require you to have checks for which Laravel version is in use.

Your composer.json file should always explicitly Laravel releases for peace of mind. Don't include version ranges that also matches non-released Laravel code, you have no idea if your current code will match Laravel 5.8 or not. When people ask about this I tell them that there has not been an official decision on if Laravel 5.8 will support VR or not, and you cannot declare that you support 5.8 before we're sure what is in the release.

A good example is orchestra/testbench which has one branch per Laravel version. I don't know about the decision behind it, but I presume it's based on the fact that they do some things that affect internal Laravel operations which may change between releases.
Ref: https://github.com/orchestral/testbench#version-compatibility

**Comment by laurencei** [comment]
Also see here: https://laravel.com/docs/5.4/releases#versioning-scheme
