### ISSUE TITLE
Carbon\Carbon::setLocale and App::setLocale do not localize dates.

### ISSUE THREAD

**Issue by Sebi2020** [laravel/framework#25658]
- Laravel Version: 5.5
- PHP Version: 7.2
- Database Driver & Version: Sqlite 3

### Description:
Months and Weekdays are only displayed in English. Carbon::setLocale or App::setLocale does not affect them.  Instead of outputting *"Dezember"* it produces *"December"* or *"May"* instead of *"Mai"*.
The only way to get localized times is to call `setlocale(LC_TIME, lang)` manually.
### Steps To Reproduce:
```php
php artisan tinker
$date = Carbon\Carbon::now();
$date->setLocale("de"); // Or any other language than english
App::setLocale("de");     // also tried de_DE on both.
$date->formatLocalized("%d. %B"); // maybe try to change the month because some months are spelled equal (like September).
```

**Comment by laurencei** [comment]
This looks like a bug in Carbon, not Laravel, as Carbon is not respecting the set locale.

Please report it in the Carbon GitHub.
