### ISSUE TITLE
Breaking change identified between v5.6.33 and v5.6.34

### ISSUE THREAD

**Issue by barnabaskecskes** [laravel/framework#25655]
- Laravel Version: 5.6.34
- PHP Version: 7.1.8
- Database Driver & Version: SQLite

### Description:
When using `morphTo()` relationship with _conditional_ statements based on the originating model's attributes, it fails in `v5.6.34` but works in `v.5.6.33`. It seems that in the newer version the model is _not_ hydrated at the time.

### Steps To Reproduce:
Please see https://github.com/barnabaskecskes/laravel-morph-to-changes - the repo has unit tests to demonstrate the difference in behaviour. Follow the readme file's instructions for convenience.

**Comment by staudenmeir** [comment]
See #25387.

**Comment by barnabaskecskes** [comment]
Actually, fair point @staudenmeir. One could do something like `User::with('relation')->where...` and that wouldn't make sense there either. Some refactoring to come... 😅 Thanks.
