### ISSUE TITLE
How to specify the type of bound value in the database query string?

### ISSUE THREAD

**Issue by xiaoxing598** [laravel/framework#25656]
I operate the database as an example below:

```php
private function findXXX(string $flag): array
{
  $objects = XXX::where([['flag', '=', $flag]])->get();
  ...
}

//call
$this->findXXX($a . ':' . $b);
```

But getting the result of the following error, it is not what I ultimately want.

```sql
select * 
from `xxx` 
where (`flag` = 2:64395845098) 
and `xxx`.`deleted_at` is null
```

This is a simple SQL statement, but there are obvious arguments. I don't know how to change the value of a string. I hope it becomes like this:

```sql
...
where (`flag` = "2:64395845098")
...
```

I tried to cast the variable type but it didn't work. Also try to specify the type of formal parameters, and also did not get the final result.

**Comment by mfn** [comment]
> XXX::where([['flag', '=', $flag]])->get();

I've never seen this, is this expected to work?

Can you try `::where('flag', $flag)`?

**Comment by YangHaHabiu** [comment]
Can you try ::where(['flag'=>$flag])?

**Comment by staudenmeir** [comment]
What's the actual error?

**Comment by laurencei** [comment]
This looks wrong to be
 
    $objects = XXX::where([['flag', '=', $flag]])->get();

it should be

    $objects = XXX::where('flag', '=', $flag)->get();
 
Then you could also forcibly cast your text to a string;

     $search = (string) $a . ':' . $b;
     $this->findXXX($search);

Either way, I will be closing your ticket here as this doesnt seem like a Framework issue.

Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

**Comment by xiaoxing598** [comment]
> What's the actual error?

```
Next Illuminate\Database\QueryException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.xxx' doesn't exist (SQL: select * from `xxx` where (`flag` = 2:64395845098) and `xxx`.`deleted_at` is null) in xxx\vendor\laravel\framework\src\Illuminate\Database\Connection.php:664
```

**Comment by laurencei** [comment]
So the table doesnt exist? You need to create it first?

**Comment by xiaoxing598** [comment]
@laurencei 
Is my problem, I did not specify the table name in the model, the default table is a plural form, which does not match the table name in the database.
In addition, I think that in order to output the error message, adding no quotation marks to the character variable misleads me to check the direction of the problem.
Finally thank you all!
