### ISSUE TITLE
Page Expired Redirect

### ISSUE THREAD

**Issue by wkasem** [laravel/framework#25670]
let's say that i have a web-page with a login form 
  - user opens it and never logs in 
  - after certain amount of time token has bean expired
 - with the same login form he tries to login but he is redirected to (Page-expired) page
 - it would be more helpful to redirect him to previous page or to login in again 
 _ current (page-expired) page does't help a lot

**Comment by laurencei** [comment]
You are able to change the behavior of this - just catch the 419 exception and put in some custom logic :)
