### ISSUE TITLE
upgrade issue

### ISSUE THREAD

**Issue by OllyTeam** [laravel/framework#25679]
hey i upgraded from laravel 5.6 to 5.7 then i added some missing file for email verification only feature in my project   but that didn't give ability to use that feature in my project so i am asking if there is any other way to enable it in my project or if i have done something wrong when adding those files in my project

**Comment by akehsanz** [comment]
hav you checked the docs properly ??

**Comment by X-Coder264** [comment]
Have you added

`'verified' => \Illuminate\Auth\Middleware\EnsureEmailIsVerified::class,`

in your `App\Http\Kernel` class in the `$routeMiddleware` attribute?

**Comment by OllyTeam** [comment]
yes i did it  but when i register it does not ask for email confirmation

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

In regards to your issue - I would suggest getting a "fresh" 5.7 install, and comparing the differences to your project. Also, as @X-Coder264 said, please follow the upgrade guide, which gives you all the required steps.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.

**Comment by OllyTeam** [comment]
thanks
