### ISSUE TITLE
snake_case convert ImgURL to img_u_r_l

### ISSUE THREAD

**Issue by cuimingda** [laravel/framework#25675]
- Laravel Version: 5.7
- PHP Version: 7.2.8
- Database Driver & Version: 10.3.8-MariaDB Homebrew

### Description:
print(snake_case("ImgURL"));
// img_u_r_l

expected: img_url

**Comment by jmarcher** [comment]
This is the expected result, if you want to have `img_url` your original string should be `ImgUrl`

**Comment by laurencei** [comment]
Closing as @jmarcher has given the answer - this is expected.

**Comment by cuimingda** [comment]
absolutely not considering the real world case. :-(
there is many situation like this：
GUIElement:  gui_element or g_u_i_element ?
IOException: io_exception or i_o_exception?
XMLHttpRequest: xml_http_request or x_m_l_http_request?

snake_case now is not expected. @jmarcher @laurencei  . sorry for your sloopy.

**Comment by laurencei** [comment]
Is there any specification or document that defines what is the industry standard? I couldnt find one? Otherwise this is just open to interpretation either way?

**Comment by cuimingda** [comment]
@laurencei if the api is written by self, we certainly can named ImgUrl. I found a api named ImgURL today, and it is always appeared in my world, may be not your world, fine, i will write one for my case. 
:-(
