### ISSUE TITLE
Cannot override deferred provider's service in 5.4

### ISSUE THREAD

**Issue by falnyr** [laravel/framework#25676]
- Laravel Version: 5.4.36
- PHP Version: 5.6

### Description:

Thorough description [here](https://stackoverflow.com/questions/52378763/overriding-mailer-service-in-laravel).

According to [this PR](https://github.com/laravel/framework/pull/20714/files) the code should be part of 5.4 branch, yet looking at the [current code](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/Application.php#L720) it looks like it never made it there.

**Comment by laurencei** [comment]
Looking at the commit history, although the PR says `5.4`, it was merged into the `5.5` branch.

As `5.4` is no longer supported, you should upgrade to `5.5` to fix this issue.
