### ISSUE TITLE
set locale breaking change

### ISSUE THREAD

**Issue by Shhu** [laravel/framework#25680]
- Laravel Version: 5.7.3
- PHP Version: 7.2
- Database Driver & Version:

### Description:
You cant set locale using `config(['app.locale' => 'fr']);` you have to use `app()->setLocale('fr')` now.
With config(), app('translator') isnt aware of the change and use the base value.

### Steps To Reproduce:
on fresh 5.6 & 5.7
```
Route::get('/', function () {
    config(['app.locale' => 'fr']);
    //app()->setLocale('fr');
    return view('welcome');
});
```

**Comment by staudenmeir** [comment]
Do you know which commit/PR caused this breaking change?

**Comment by rodrigopedra** [comment]
Why not just use `app()->setLocale('fr')` ? I had this problem migrating to 5.7 but I found the solution you already know much better now

**Comment by laurencei** [comment]
Does it occur on a fresh 5.5 install?

Either way, if it is occuring on a fresh 5.6 and 5.7 install, then you can open a PR at http://github.com/laravel/docs to update the docs.
