### ISSUE TITLE
Possible bug with SparkPost coming up. (SparkPost changes in November 2018.)

### ISSUE THREAD

**Issue by rickmacgillis** [laravel/framework#25694]
- Laravel Version: 5.7
- PHP Version: 7.2

### Description:
SparkPost just sent us the following email. I briefly examined `Illuminate\Mail\Transport\SparkPostTransport` and don't see anything that will break, but I just want to make sure there won't be an issue with the API changes coming up in November.

Here's what they sent us.

> Dear SparkPost Customer,
>
> We know how important it is that when you call the Transmissions API endpoint, we are able to accept your request quickly and return a response. We are continuously looking for ways to further improve the reliability of our service, provide consistently low API response times and improve the user experience. To that end, there are three changes planned that relate to how we handle errors:
>
> - Move single recipient template validation and message generation to be asynchronous.
> - Move all inline template syntax validation to be asynchronous, affecting both single and multi-recipient transmissions.
> - Deprecate and remove the extended error codes.
>
> These changes only affect the user experience for error cases and will not change the user experience for any successful (HTTP 200 response) API requests. The changes will take effect on Nov 17, 2018 to give our customers time to prepare.
>
> **Making single recipient transmissions asynchronous**
> SparkPost will no longer perform synchronous template validation & message generation on single recipient transmissions. This means that the Transmissions API will no longer return a HTTP response of 4xx if there is a problem with the template syntax or substitution data. Instead, it will return a 200 response, and then a subsequent “Generation Failure” webhook event that will provide details on the failure. These events will be available via webhooks or the Message Events API/UI. This behavior for single recipient transmissions will be the same as the current behavior for multi-recipient transmissions.
This is similar to changes earlier this year in which we moved single recipient suppression checks to be asynchronous.
>
> **Making inline template syntax validation asynchronous**
> The second change to the Transmission API endpoint is that inline template syntax validation will no longer be performed synchronously. For both single and multi-recipient transmissions, the syntax validation will be done asynchronously, with a HTTP response of 4xx no longer returned for syntax error on inline templates. Instead, the API will return a 200 response, and then a subsequent “Generation Failure” webhook event that will provide details on the failure. It is recommended that the template preview API is used before injecting with an inline template.
>
> **Deprecating extended error codes for API Responses**
> In order to simplify the user experience, we are deprecating the API HTTP response with extended error codes. This will not affect the extended error codes that are returned via webhooks. These are descriptions and codes, in addition to the HTTP status and custom message, returned by some API endpoints including Transmissions, Templates, Sending Domains, Inbound Domains, Relay Webhooks, and Tracking Domains. These extra error fields add extra overhead and complexity to the client. We believe that the HTTP status code is usually sufficient with an optional error message when it adds necessary context to the client.
>
> For example, a Transmissions API error currently looks like this:
> 
> ```
> HTTP 400
> {
> "errors": [
> {
> "description": "Unconfigured or unverified sending domain.",
> "code": "7001",
> "message": "Invalid domain"
> }
> ]
> }
> ```
>
> Once the changes go into effect we will return just the HTTP status code and the optional error message. There will no longer be a “code” or “description” field returned, however, the content of the “description” field will be returned in the “message” field.
>
> ```
> HTTP 400
> {
> "errors": [
> {
> "message": "Unconfigured or unverified sending domain." }
> ]
> }
> ```
> This change will eliminate redundant information from these API endpoint responses and make error responses consistent across all of our API endpoints.
>
> **Preparing For This Change**
> To prepare for these changes, we recommend that you put in place measures to begin using the Webhook or Message Event API data, if you are not already doing this. This will ensure a smooth transition. If you wish to validate a template before using it in a Transmission, you can use the template preview API endpoint or the UI. Also, if you have any code that is currently looking at the API error response for code, message, or description you will need to update those systems.
>
> **Making a Tough Decision** At SparkPost, we take backwards-compatibility very seriously. We don’t make these types of changes lightly and appreciate that our customers have code in production using our API. We also take our reliability, performance, and usability very seriously and know that is one of the primary reasons why developers and enterprises choose SparkPost. We believe these updates will provide a much better experience for our customers without a major impact to existing customers.
>
> Thank you,
> Isaac Kim
>
> Technical Product Manager

**Comment by dimgsg9** [comment]
From what i understood this change in SparkPost only affects use cases when you use their email templates via API. I guess with Laravel we always define our own templates (*.blade.php) for mailables.

**Comment by laurencei** [comment]
There doesnt seem to be any obvious breaking changes.

If anyone finds any - please submit a PR with the required fix.
