### ISSUE TITLE
selectRaw() and DB::raw() appear to use MySQL "DIV" behaviour instead of '/' when attempting arithmetic division

### ISSUE THREAD

**Issue by ok200paul** [laravel/framework#25695]
- Laravel Version: 5.6.31
- PHP Version: 7.1.16
- Database Driver & Version: mysql  Ver 8.0.11 for osx10.13 on x86_64 (Homebrew)

### Description:
When dividing one value by another in a `selectRaw` or `DB::raw` query, the resultant division returns an integer, or appears to discard the numbers after the decimal point.

Outputting the query to SQL and running in mySQL directly returns decimal numbers in the result.

### Steps To Reproduce:

1. Create a DB table
```
Schema::create('ratings', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->integer('user_id')->index();
            $table->string('rating_object');
            $table->integer('rating_object_id');
            $table->unsignedTinyInteger('rating');
            $table->string('comment')->nullable();
            $table->timestamps();
            
            $table->softDeletes();
        });
```

2. Populate the table with some data, using the same `rating_object` value.

3. Run a selectRaw query:
```
$data = DB::table('ratings')
                                     ->selectRaw('5 / 67 as nonIntResult')
                                     ->selectRaw('5 / 1 as intResult')
                                     ->groupBy('rating_object')
                                     ->get();

dd($data);
``` 

4. It looks like `nonIntResult` returns `0` and `intResult` returns `5`.

5. Export the query to SQL:
```
select 5 / 67 as nonIntResult, 5 / 1 as intResult from ratings group by rating_object;
```
.. it returns decimals.

6. Replace the division operand `/` with the `DIV` keyword, and you appear to get the same result as the main issue, possibly indicating a little bug?

**Comment by ok200paul** [comment]
This isn't presenting in the same way in tinker - the issue must be somewhere between the my seat & my screen. Closing

**Comment by ok200paul** [comment]
Update: the issue appears to be something to do with PHPUnit and how it interprets numeric array data. For some reason it's boiling decimals down to integers. The search continues

**Comment by staudenmeir** [comment]
What does your test look like?

**Comment by staudenmeir** [comment]
What's the result of `dd($ratingsData[0]->nonIntResult);`?

**Comment by ok200paul** [comment]
`"0"`

**Comment by staudenmeir** [comment]
Does your test use a different database?

**Comment by ok200paul** [comment]
It does actually, great thinking never thought of that - SQLite. Will test using the same DB server and comment!

**Comment by ok200paul** [comment]
Wow @staudenmeir thanks for this - you're on to something. Running the test suite in SQLite returns the behaviour described above. MySQL as the DB base of the test suite is returning correctly precise numbers.

I'll do some reading about (hopefully) working around this in SQLite, I'm not super-interested in rejigging our CI system to install mysql for testing..!!

**Comment by ok200paul** [comment]
https://www.sqlite.org/datatype3.html 

"Note that a declared type of "FLOATING POINT" would give INTEGER affinity". Bing-pot!

**Comment by staudenmeir** [comment]
You can use something like `->selectRaw('5 * 1.0 / 67 as nonIntResult')`.

I assume you are aware that testing your code with a different database can cause all kinds of issues and hide potential bugs?

**Comment by ok200paul** [comment]
Well, I am aware now - thanks! Running the test suite again brought up a couple of new testing issues - thankfully not many. The main set of tests are ensuring the API is working properly, it's a fairly simplistic application. 

Thanks very much for taking part and lending your expertise; I've ported the testing suite & CI/CD setup to use the same DB engine as the production app.
