### ISSUE TITLE
Changing the default “subject” field for the verification email in laravel 5.7

### ISSUE THREAD

**Issue by GabMic** [laravel/framework#25702]
I am trying to change the default `subject` field in the verification email that come with laravel 5.7. Curently it is `Verify Email address`. How and where can i change it? I have searched all over the place by myself, and online, but because it is brand new, i could not find an answer. Can you help me please? Thanks!

**Comment by staudenmeir** [comment]
Please link/post the solution from StackOverflow and close the issue.

**Comment by GabMic** [comment]
The solution is here: https://stackoverflow.com/questions/52408042/changing-the-default-subject-field-for-the-verification-email-in-laravel-5-7
