### ISSUE TITLE
[5.5+] Mockery assertions not counted and tests marked as risky

### ISSUE THREAD

**Issue by dmason30** [laravel/framework#25703]
- Laravel Version: 5.5.43 (Could be an issue in 5.6/5.7)
- PHP Version: 7.1
- PHPUnit: 6.5.13

### Description:
In #20606 there was an attempt to fix this issue by adding the below code in the `tearDown` method:

```
            if ($container = Mockery::getContainer()) {
                $this->addToAssertionCount($container->mockery_getExpectationCount());
            }
```

The issue here is in `PHPUnit 6.*` the **Mark test as risky** check was moved to before the `tearDown` function. So the change made in #20606 no longer seems to have the desired effect. 

A similar issue was discussed in https://github.com/sebastianbergmann/phpunit/issues/2758 and it appears that the above code should be handled in `assertPostConditions`. 

`Mockery` does provide a `Mockery\Adapter\Phpunit\MockeryPHPUnitIntegration` trait that handles this. 

I am not sure if this would be compatible with the `TestCase` provided in laravel. I have managed to put it in my own `TestCase` extending Laravel's class and it seems to work correctly. 

### Steps to replicate
Create a test that only contains a `Mockery` assertion/expectation and PHPUnit 6 thinks its risky. 

Below is a very crude example that replicates the issue. It is not really testing anything but it is the simplest example I came up with.

#### Foo.php

```
namespace App;

class Foo
{
    public function bar()
    {
        if ($this->baz()) {
            return true;
        }

        return false;
    }

    public function baz()
    {
        return false;
    }
}
```
    

#### FooTest.php
```
namespace Tests\Unit;

use App\Foo;
use Tests\TestCase;

class FooTest extends TestCase
{
    public function test_foo()
    {
        $m = \Mockery::mock(Foo::class)->makePartial();
        app()->instance(Foo::class, $m);

        $m->shouldReceive('baz')
            ->once()
            ->withNoArgs()
            ->andReturn(true);

        app(Foo::class)->bar();
    }
}
```

**Comment by staudenmeir** [comment]
Please post an example test.

**Comment by dmason30** [comment]
@staudenmeir I have added it to the op

**Comment by staudenmeir** [comment]
This test runs successfully on my machine. What's your exact PHPUnit version?

**Comment by dmason30** [comment]
@staudenmeir 

PHPUnit: 6.5.13
Laravel: 5.5.43

**Comment by staudenmeir** [comment]
I'm using the same versions. Can you reproduce the issue on a fresh Laravel installation?

**Comment by dmason30** [comment]
@staudenmeir I'll try that tomorrow, seemed pretty cut and dry to replicate, thanks for the help so far...

**Comment by laurencei** [comment]
I've seen this before - and the problem I had was I was overriding either the `tearDown()` or the `setUp()` in one of my main test files (cant remember which), but I forgot to call the `parent::` version during that, which caused the issue above.

Given we cant replicate on a fresh install of Laravel, I'm going to close this issue.

If @dmason30 you can provide steps to replicate on a fresh install - ping me here with the steps and I'll reopen the ticket.

**Comment by dmason30** [comment]
@laurencei I will look at this soon, however just as an FYI, Mockery`was upgraded to `v1` in Laravel 5.5 and in the Mockery Upgrading docs it states:

http://docs.mockery.io/en/latest/getting_started/upgrading.html#upgrading-to-1-0-0

> As of 1.0.0, PHPUnit test cases where we want to use Mockery, should either use the \Mockery\Adapter\Phpunit\MockeryPHPUnitIntegration trait, or extend the \Mockery\Adapter\Phpunit\MockeryTestCase test case. This will in turn call the \Mockery::close() method for us.

However the `trait` or `class` does more than just the close it handles the above assertion count issue and   coverage. 

http://docs.mockery.io/en/latest/reference/phpunit_integration.html#phpunit-integration

> To integrate Mockery into `PHPUnit` and avoid having to call the close method and have Mockery remove itself from code coverage reports,
> ...
> Extending MockeryTestCase or using the MockeryPHPUnitIntegration trait is the recommended way of integrating Mockery with PHPUnit, since Mockery 1.0.0.

**Comment by dmason30** [comment]
@laurencei Turns out it was laravel/browser-kit-testing was still on v2 which meant that the above code was missing. :flushed: My bad. Sorry.
