### ISSUE TITLE
[5.7] Verify email link is broken

### ISSUE THREAD

**Issue by joveice** [laravel/framework#25716]
- Laravel Version: 5.7.2
- PHP Version: 7.2.9
- Database Driver & Version: MariaDB (not sure)

### Description:
The link on the link in the verify email is broken, the text on it and the button is not.
Etc this link: https://mydomain.com/email/verify/5123?expires=1537460881&amp;signature=(signature)
With this text: https://mydomain.com/email/verify/5123?expires=1537460881&signature=(signature)
So the issue is the: `amp;`
I found this due to #25597 as my buttons where invisible so the users clicked on the link instead, and then came back to me and said it didn't work.
### Steps To Reproduce:
1. Send verification email
2. click on the link in the email
3. unauthorised

**Comment by staudenmeir** [comment]
See #25515.
