### ISSUE TITLE
php artisan migrate --path is not working

### ISSUE THREAD

**Issue by Kinafune** [laravel/framework#25717]
I am trying to use `php artisan migrate --path="/database/migrations/ef` to use only the migrations in that path. But I got "Nohting no migrate" and the migration files are in that direction.

I got the same using `php artisan migrate --path="/database/migrations

**Comment by joveice** [comment]
@Kinafune have not used path but when I get nothing to migrate it's already migrated.

**Comment by Kinafune** [comment]
> @Kinafune have not used path but when I get nothing to migrate it's already migrated.

I check several times, but  there is nothing in my database.

**Comment by staudenmeir** [comment]
Does `php artisan migrate` work?

**Comment by Kinafune** [comment]
@staudenmeir It works, but I am using path because I just want to use the migration files in `database/migrations/ef`

**Comment by staudenmeir** [comment]
What's your Laravel version?

**Comment by Kinafune** [comment]
I am using Laravel 5.6

**Comment by staudenmeir** [comment]
The `--path` option works for me.

Put `dd($files);` in `Illuminate\Database\Migrations\Migrator::run()`: Does Laravel even find the migration files?

**Comment by Kinafune** [comment]
> The `--path` option works for me.
> 
> Put `dd($files);` in `Illuminate\Database\Migrations\Migrator::run()`: Does Laravel even find the migration files?

Can you explain me how to do that please?

**Comment by staudenmeir** [comment]
Edit the `vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php` file.

**Comment by Kinafune** [comment]
I added the dd($files) in run function in the vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php file, then I used `php artisan migrate --path=database/migrations/ef` but I get this: [ ]

**Comment by pschmidt88** [comment]
You are mixing Unix and Windows file separators. 

Did you try it with `--path=database\migrations\ef` ?

**Comment by samundra** [comment]
@Kinafune Are you still facing this issue?

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by ahmadmayahi** [comment]
I just figured out that the absolute path doesn't work with the `--path` option:
```shell
php artisan migrate --path="/Users/ahmad/Sites/portal/database/migrations/system" 
```
This will always output:
```shell
Nothing to migrate.
```
But if I make it a relative path, then it works:
```shell
 php artisan migrate --path="/database/migrations/system/"
```

Any idea why?

**Comment by olemanxoai** [comment]
Open **Illuminate\Database\Migrations\Migrator.php** file. At line 430 (**Migrator::getMigrationFiles()**). Replace **return $this->files->glob($path.'/*_*.php');** with **return Str::endsWith($path,'.php') ? [$path] : $this->files->glob($path.'/*_*.php');**
Now the --path option will work normally
