### ISSUE TITLE
Eloquent::cursor() issue to dispatch jobs

### ISSUE THREAD

**Issue by xckon** [laravel/framework#25714]
- Laravel Version: 5.6.29
- PHP Version: PHP 7.2.4-1+ubuntu16.04.1+deb.sury.org+1
- Database Driver & Version: PostgreSQL 10.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 6.4.0) 6.4.0, 64-bit 

### Description:
I'm getting an error trying to dispatch a job with an Eloquent Entity as a param. The main reason it seems to be that I'm using cursor() to fetch the entities.

`PHP Fatal error:  Uncaught ErrorException: get_class() expects parameter 1 to be object, null given in /var/www/xxxxxxx/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:109
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'get_class() exp...', '/var/www/xxxxx...', 109, Array)
#1 /var/www/xxxxxxx/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(109): get_class(NULL)
#2 /var/www/xxxxxxx/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(120): Illuminate\Bus\Dispatcher->hasCommandHandler(NULL)
#3 /var/www/xxxxxxx/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(88): Illuminate\Bus\Dispatcher->getCommandHandler(NULL)
#4 /var/www/xxxxxxx/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(76): Illuminate\Bus\Dispatcher->dispatchNow(NULL)
#5 /var/www/xxxxxxx/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php(112): Illuminate\Bus\Dispatcher->dispatch(NULL)
#6 [internal function]: Illuminate\Foundation\Bus\Pending in /var/www/xxxxxxx/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php on line 109`

### Steps To Reproduce:

1. Create a Job:

```php
abstract class FacebookJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

}

class DownloadFacebookInsights extends FacebookJob implements ShouldQueue 
{
/**
    * @var AdAccount
    */
    protected $_AdAccount;

    /**
    * @var Initiative
    */
    protected $_Initiative;

    /**
    * @var InitiativeAdAccount
    */
    protected $_InitiativeAdAccount;

    public function __construct(InitiativeAdAccount $initiativeAdAccount)
    {

        $this->_InitiativeAdAccount = $initiativeAdAccount;
        $this->_AdAccount = $initiativeAdAccount->adAccount;
        $this->_Initiative = $initiativeAdAccount->initiative;
    }
```

2. Iterate using cursor:
```php
foreach(InitiativeAdAccount::cursor() as $initiativeAdAccount) {
    $job = \App\Jobs\DownloadFacebookInsights::dispatch($initiativeAdAccount);
}
```

**Comment by xckon** [comment]
The same code works using `::chunk`

**Comment by taita-wizard** [comment]
> The same code works using `::chunk`

got the same error. How did you fix it?
