### ISSUE TITLE
get() method of Eloquent model returns all database entries. 

### ISSUE THREAD

**Issue by Stef-Dan** [laravel/framework#25718]
- Laravel Version: 5.7.4
- PHP Version: 7.1
- Database Driver & Version: MySql

### Description:
**Its no release bug, but maybe a semantic bug.**
For me it was very unexpected to get all fake users 
from my test database by calling "->get()" on the 
model object.
```
User::find(1)->get(); // all users as Eloquent\Collection
```

### Steps To Reproduce:
```
$user = User::find(1);
echo get_class($user);  // "App\Models\User" -> like expected
echo get_class($user->get()); // "Illuminate\Database\Eloquent\Collection" -> unexpected 
```

But anyway **I love working with Laravel. Thanks to all developers.**

**Comment by nulpatrol** [comment]
But why you call get() on user instance? 😊

**Comment by devcircus** [comment]
Your case is the same as below:

```php
// UserController.php

use App\User;

class UserController extends Controller
{
    protected $users;

    public function __construct(User $users)
    {
        $this->users = $users;
    }

    public function index()
    {
        return $this->users->get();
    }
}
```

In both cases, you're calling ```get()``` on an instance of ```User```. This is just how Eloquent works.

**Comment by staudenmeir** [comment]
What would you expect to happen?

**Comment by bonzai** [comment]
#24679
