### ISSUE TITLE
Incorrect relation parsing when specific columns with constraining

### ISSUE THREAD

**Issue by BePsvPT** [laravel/framework#25712]
Assume there are `User` and `Post` models. 

The relation is `User hasMany Post`.

When executing following codes, it will result in 

`Illuminate/Database/Eloquent/RelationNotFoundException with message 'Call to undefined relationship [posts:posts] on model [App/User].'`

```php
User::with(['posts:posts.id,user_id,name' => function ($query) {
  $query->where('name', 'apple'); 
}])
  ->first()
```

```php
$user = User::first();

$user->loadMissing(['posts:posts.id,user_id,name' => function ($query) {
  $query->where('name', 'apple'); 
}])
```

**Comment by staudenmeir** [comment]
What's your Laravel version?

**Comment by 36864** [comment]
Fairly sure you can just pass in `posts:id,name` instead of `posts:posts.id,name`.

**Comment by BePsvPT** [comment]
Hi @36864,

This is an example to reproduce the bug and thanks for reminding me that I forgot to add `user_id` column.

**Comment by staudenmeir** [comment]
@36864 There are cases where have to specify the table name, e.g. with `BelongsToMany` and 
`HasManyThrough` relationships.

**Comment by staudenmeir** [comment]
I'm not sure this is supposed to work.

Since you are already using a closure, you can just add `$query->select('posts.id,user_id,name');`.

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
