### ISSUE TITLE
Validation rule date will accept a invalid date like '2018-09-10a'

### ISSUE THREAD

**Issue by steve3d** [laravel/framework#25711]
- Laravel Version: 5.7.1
- PHP Version: 7.2.9
- Database Driver & Version: not important

### Description:
I'm using `date` validation rule a lot, and recently, I just found that sometime I accidentally entered a date like `2018-09-10a`, the date rule will accept this as a valid date string, but when I insert this into database, of course this is a invalid date.

but if I use `date_format:Y-m-d` to check upon value like `2018-09-10a`, then it will report this is a invalid date.

is this a bug or it's designed to work like this?

**Comment by laurencei** [comment]
This is expected - as it is a limitation of PHP.

The reason is PHP will parse `2018-09-10a` under the hood using `strtotime()` and it will "work".

If you want to ensure the correct format of a date - that is why the `date_format` rule is there.
