### ISSUE TITLE
Multiple authentication: auth helper doesn't work

### ISSUE THREAD

**Issue by carlospalacin** [laravel/framework#25729]
- Laravel Version: 5.7.5
- PHP Version:php 7.1.12
- Database Driver & Version: MySQL 5.7.18

### Description:
When using multiple authentication, auth() helper doesn't return the guard

### Steps To Reproduce:
After get login over crm guard:
```
auth('crm')->chech(); // this return false
Auth::guard('crm')->chech(); // this return true

auth('crm')->user(): // this return null
Auth::guard('crm')->chech(); // this return user object
```
But if access to route, under the middleware auth:crm, everything is correct:

```
Route::get('test/auth', function() {
   auth('crm')->user(); // null
   \Illuminate\Support\Facades\Auth::guard('crm')->user(); // return user object
});

Route::get('test/auth/crm', function() {
    auth('crm')->user(); // return user object
    \Illuminate\Support\Facades\Auth::guard('crm')->user(); // return user object
})->middleware('auth:crm');

```

**Comment by AegirLeet** [comment]
`dd(auth('crm'), Auth::guard('crm'), auth('crm') === Auth::guard('crm'));`

What's the output? Any differences between the two?
What if you use the web guard instead?

**Comment by carlospalacin** [comment]
After log in...
```
Route::get('test/auth', function() {
    dd(
        auth('crm'), // AuhtManager Object
        \Illuminate\Support\Facades\Auth::guard('crm'), // SessionGuard Object
        auth('crm') === \Illuminate\Support\Facades\Auth::guard('crm'), // false
        auth('crm')->user() === \Illuminate\Support\Facades\Auth::guard('crm')->user(), // false
        auth('crm')->check(), // false
        \Illuminate\Support\Facades\Auth::guard('crm')->check() // true
    );
});

Route::get('test/auth/crm', function() {
    dd(
        auth('crm'), // AuhtManager Object
        \Illuminate\Support\Facades\Auth::guard('crm'), // SessionGuard Object
        auth('crm') === \Illuminate\Support\Facades\Auth::guard('crm'), // false
        auth('crm')->user() === \Illuminate\Support\Facades\Auth::guard('crm')->user(), // true
        auth('crm')->check(), // true
        \Illuminate\Support\Facades\Auth::guard('crm')->check() // true
    );
})->middleware('auth:crm');
```
If set default guard with 'crm' works fine, the problem is that the helper auth('custom-guard') always take the default guard, configured in auth.defaults.guard config file (config/auth.php)

**Comment by passionInfinite** [comment]
@carlospalacin  Can you show me Guard registration part (it will be in app/Providers/AuthServiceProvider.php) ?

**Comment by ankurk91** [comment]
I am using this package for scaffolding
https://github.com/mtvbrianking/multi-auth

**Comment by passionInfinite** [comment]
Actually, Laravel auth helper is working fine. I guess this issue should be referred to multi auth repo.

**Comment by ankurk91** [comment]
I don't think so.
After all the multi auth repo is utilizing Laravel's multi gaurds capabilities.
O.P. might not be using this package.

I will post in detailed steps soon.

**Comment by carlospalacin** [comment]
you can use for the moment:
```
auth()->guard('crm')
```

**Comment by passionInfinite** [comment]
@carlospalacin  @ankurk91 Any updates on this?

**Comment by ankurk91** [comment]
Possible duplicate of 
https://github.com/laravel/framework/issues/22096

**Comment by driesvints** [comment]
Please check my comment on the linked issue. I think it's important to have the middleware present before trying to select a guard with the auth helper so I believe this isn't an actual bug. Feel free to respond back if you believe otherwise.
