### ISSUE TITLE
Unable to update a model with only the created_at timestamp.

### ISSUE THREAD

**Issue by dkulyk** [laravel/framework#25737]
- Laravel Version: 5.6, 5.7
- PHP Version: 7.2
- Database Driver & Version: MySQL  10.2.17-MariaDB

### Description:
If const UPDATED_AT = null the builder set to the updated_at column  current date.
[Model:: updateTimestamps](https://github.com/laravel/framework/blob/v5.7.5/src/Illuminate/Database/Eloquent/Concerns/HasTimestamps.php#L41) has checking for `null` but [Builder:: addUpdatedAtColumn](https://github.com/laravel/framework/blob/v5.7.5/src/Illuminate/Database/Eloquent/Builder.php#L854) doesn't have one

### Steps To Reproduce:
1. Make DB with the created_at but without the updated_at field.
2. Set in model `const UPDATED_AT = null;`
3. Update the model.

**Comment by laurencei** [comment]
I dont understand - can you provide more explanation please?
