### ISSUE TITLE
queue:work ignores --memory parameter 

### ISSUE THREAD

**Issue by Yahav** [laravel/framework#25738]
- Laravel Version: 5.7.5
- PHP Version: 7.2.9
- Database Driver & Version: mariaDB 5.5.60
- Queue Driver: beanstalkd 1.10-2
                       pda/pheanstalk v3.2.1

### Description:
I;m running the queue:work through supervisor with the following command:
`artisan queue:work --memory=100 --queue=reportProcessing --sleep=3 --tries=3
`
In actuality, the processes start at around 400mb (which on itself is too high). 
anyway, you would expect that after one job the worker will quite, which doesn't happen.
they will never be shutdown and eventually will reach huge amount of memory.
https://i.imgur.com/2iHwSNz.png

**Comment by sisve** [comment]
This would happen if the application is down for maintenance, the workers are paused, or you are subscribing to the Looping event and return false. If neither of these scenarios match, can you tell us what `memory_get_usage(true)` returns, and make sure it matches with the observed memory usage (or at least above your memory limit)?

**Comment by Broutard** [comment]
Please provide the results of 
```
Queue::looping(function () {
     dump(memory_get_usage(true).'/'.memory_get_usage(false));
});
```

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by DeroSavage** [comment]
Im still facing the same or similar issue. I used the --memory parameter together with supervisor and the work command like this:
command=php /var/www/artisan queue:work --sleep=1 --timeout=100 --memory=512

However, a quite big job still fails with the "Allowed memory size of 134217728 bytes exhausted (tried to allocate 5988352 bytes)". What makes me thing that the memory option does not work is the message. It says "of 134217728 byes" which is 128MB, which is the default value of the memory parameter. In the php.ini memory_limit is also set to 512M.

**Comment by Broutard** [comment]
@DeroSavage The queue limit works only between two jobs but not within your job.
