### ISSUE TITLE
Backport the enhancements to Pivot to 5.5 since it is LTS

### ISSUE THREAD

**Issue by jimmypuckett** [laravel/framework#25745]
- Laravel Version: 5.5.x (LTS)
- PHP Version: >= 7
- Database Driver & Version: mysql

### Description:
We are having issues when a pivot model is used standalone to work with the pivot data.  There is logic in the model that issues that it is only being used as a pivot. For example...

```php
/**
  * Get the name of the "updated at" column.
  *
  * @return string
  */
  public function getUpdatedAtColumn()
  {
      return $this->pivotParent->getUpdatedAtColumn();
  }
```

However, as of 5.6, this bug was fixed..

```php
 /**
    * Get the name of the "updated at" column.
    *
    * @return string
    */
    public function getUpdatedAtColumn()
    {
        return ($this->pivotParent)
                        ? $this->pivotParent->getUpdatedAtColumn()
                        : parent::getUpdatedAtColumn();
    }
```

Since 5.5 is LTS, can we get this model back ported into a 5.5 tag?  

### Steps To Reproduce:

1) Make a pivot model
2) Work directly with the model

**Comment by staudenmeir** [comment]
Will be fixed in the next release (#25746).
