### ISSUE TITLE
Thread id (MySQL Connection id) is not in MySQL thread list.

### ISSUE THREAD

**Issue by anonymouse703** [laravel/framework#25753]
Hello everyone,

I tried to make LoginUser Table for me to able to get all users connected in the server.

I have this code in Login Controller.

`$con_id = DB::select('select connection_id()');`

when I `dd($con_id)`

this is the result.

```
array:1 [▼
  0 => {#797 ▼
    +"connection_id()": 279
  }
]
```
and when I dd() this `$con_id = DB::select('show full processlist');
`
This is the result

```
array:4 [▼
  0 => {#797 ▼
    +"Id": 46
    +"User": "root"
    +"Host": "localhost:51545"
    +"db": "iaccsshsc07"
    +"Command": "Sleep"
    +"Time": 24
    +"State": ""
    +"Info": null
  }
  1 => {#802 ▼
    +"Id": 64
    +"User": "root"
    +"Host": "localhost:53014"
    +"db": "iaccsshsc07"
    +"Command": "Sleep"
    +"Time": 4
    +"State": ""
    +"Info": null
  }
  2 => {#803 ▼
    +"Id": 65
    +"User": "root"
    +"Host": "localhost:53027"
    +"db": "iaccsshsc07"
    +"Command": "Sleep"
    +"Time": 4
    +"State": ""
    +"Info": null
  }
  3 => {#804 ▼
    +"Id": 279
    +"User": "root"
    +"Host": "localhost:56385"
    +"db": "iaccsshsc07"
    +"Command": "Execute"
    +"Time": 0
    +"State": "init"
    +"Info": "show full processlist"
  }
]
```
But when I go to my MySQL and query `Show full processlist`

this will be the result.

Id = 46,64,65

The 279 is not in the list.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.

**Comment by anonymouse703** [comment]
@laurencei  Good day sir, Is that not a bug or issue in Laravel? where can I asked that? I already had asked that in the forums you've recommended... and also sir the main reason why i posted it in here because of the cased i posted above. When I run that code in Visual Basic it was working but in Laravel is not...
