### ISSUE TITLE
Wierd \View issue

### ISSUE THREAD

**Issue by striderxfossility** [laravel/framework#25758]
So i got a Model called **\App\Offerte**

I got a relation that is called 
`public function werkbonnen() 
    {
        return $this->hasMany('App\Werkbonnen\Werkbon');
    }`

Now i called the view Render
`$html = \View::make($this->url, $this->array)->render();`

_(I saved this in the database for quick loading)_

In this view is will call
` $offerte->werkbonnen()->etc->get();`

After this i get the error 
`Class 'App\Werkbonnen\Werkbonnen' not found`

When i do `return view('url', compact('planning', 'offertes'));` everything works fine

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
