### ISSUE TITLE
Rest Api Logging Out User

### ISSUE THREAD

**Issue by ongyen8888** [laravel/framework#25751]
Hi,

I'm using Laravel Passport for my rest api authentication, but I'm having issues logging user out. For website logging out, the Auth::logout() method works, but when I call Auth::logout() in my AuthController for api's I kept getting method logout does not exists. I know how to delete the access token of a specific user but I'm using this package "highideas/laravel-users-online" and the number of users online still stays the same after logout from api. It seems like the session or cache is still there, I try to call Auth::logout() and it shows error, I use Session::flush() or Session::regenerate() nothing happens. Can someone help me out with this?

Thanks.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
