### ISSUE TITLE
Laravel has() has Bug

### ISSUE THREAD

**Issue by pramanadiputra** [laravel/framework#25754]
- Laravel Version: 5.6.33
- PHP Version: 7.2.6 NTS x64
- Database Driver & Version: MySQL mysql-5.7.19-winx64

### Description:
Laravel has() has a bug. 

### Steps To Reproduce:
I have these following rows in my Lectures table
| ID | TITLE | .... | .... | 
(1) Setup Localhost
(2) Download WordPress
(3) Install WordPress on Localhost
(4) Understanding WordPress Directory
(5) WordPress Theme
(6) WordPress Plugin 
(1) - (6) Belong to Course A (course-a) 

(7) Setup RoR

When I'm running this script 
```
dd($course->lectures->has($lecture->id));
```
and accessing this URL: 
app.tld/course-a/lecture/{id} 

ID from 1 to 5 output TRUE, while 6 (that also belong to Course A) output FALSE. 

Please check this Bug, Thank You.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.

**Comment by pramanadiputra** [comment]
I think it's a Framework Bug since it's very clear that some IDs are belong to proper Model.

**Comment by tuborgbeer** [comment]
Ignore him. He just has "issue closer" job. I agree, the framework is full of bugs and bloatware code
