### ISSUE TITLE
Support db transactions in seeder when being called in the tests.

### ISSUE THREAD

**Issue by ajcastro** [laravel/framework#25756]
I am preparing my unit tests pre-data in the seeders instead of calling factories in the test files. And I just call the seeder via `$this->seed(PreDataSeeder::class);`. 

My tests are using `Illuminate\Foundation\Testing\RefreshDatabase` trait so I expect that my database won't be written by tests, but apparently, the database content was changed. 

I suspect that it is because the seeder files are not being wrapped anymore by the database transaction.
Is this a bug or intended behavior? What are the possible solutions for this?

Also, my seeder files can also contain another call to another seeder file.

**Comment by laurencei** [comment]
At the start of your tests, your database will be seeded.

Then at the end of each test, your database will be rolledback to the point where the seeds are done.

> I expect that my database won't be written by tests, but apparently, the database content was changed

That is correct. The best option is to setup a test database to run your tests against.

**Comment by ajcastro** [comment]
@laurencei so do you mean that calling seeder files inside tests files will really persist even I use the `RefreshDatabase` trait?

**Comment by ajcastro** [comment]
It is somehow misleading because I expect that calling seeders files from tests should not persists if I use `RefreshDatabase`... is this a bug?

**Comment by laurencei** [comment]
> is this a bug?

Nope. The `refreshDatabase` trait does use transactions under the hood, but only after it has setup the base test database (including your seeds).

> because I expect that calling seeders files from tests should not persist if I use RefreshDatabase

If you dont want your database to be changed before/after testing, you should configure a seperate testing database. Ideally you should use `:inmemory:` as that'll be the fastest option for you.
