### ISSUE TITLE
assertExactJson() does not work for empty JSON objects

### ISSUE THREAD

**Issue by dbudwin** [laravel/framework#25769]
- Laravel Version: 5.7.5
- PHP Version: 7.1.7
- Database Driver & Version: N/A

### Description:
When comparing against a JSON structure that contains anywhere within it an empty JSON object like `"payload": {}` I would expect the tests to still pass when I make a call to `assertExactJson()` when my response contains an empty JSON object.

### Steps To Reproduce:

1. Add the following endpoint to an API controller:

```
public function empty(): JsonResponse
{
    $emptyJsonObject = [
        'payload' => (object) []
    ];

    return response()->json($emptyJsonObject);
}
```

2. Be sure to edit `api.php` to point to the new controller method:

`Route::get('/MyController/empty', 'API\MyController@empty')->name('empty');`

3. Create a test against the new endpoint:

```
public function testEmpty_AssertExactJsonGivenEmptyJsonObject(): void
{
    $response = $this->getJson('/api/devices/empty');

    $emptyJsonObject = [
        'payload' => (object)[]
    ];

    $response->assertExactJson($emptyJsonObject);
}
```

NOTE: If you test hitting this endpoint, you will get the correct response like:

```
{
    "payload": {}
}
```

4. Run the unit test and note the failure:

```
Failed asserting that two strings are equal.
Expected :'{"payload":{}}'
Actual   :'{"payload":[]}'
```

The test is saying the `actual` is an empty JSON array but when I hit my endpoint (or set a breakpoint in my test) I can see that the _real_ `actual` is an empty JSON object like I want.  I suspect the issue arises in a function called from `assertExactJson`, `decodeResponseJson`.  In `decodeResponseJson` is the line `$decodedResponse = json_decode($this->getContent(), true);`.  The `true` parameter according to PHP's documentation: "When TRUE, returned objects will be converted into associative arrays."  This is not the behavior I want, so setting this flag to `false` instead of `true` works for this test.  However, the fix is not this simple, because tests with more complex JSON structures will now fail because the `assertExactJson` function relies on being able to sort the arrays alphabetically before comparing them.

**Comment by staudenmeir** [comment]
Possible workarounds:

```php
$response->assertSee(json_encode($emptyJsonObject));
$response->assertJsonCount(0, 'payload');
```

**Comment by dbudwin** [comment]
While that may be a possible workaround for the simplest of test cases like I outlined in the bug description, it won't help me with my real world case where I have a much larger JSON structure where there is a nested item that is an empty JSON array.

**Comment by HongjiangHuang** [comment]
Our country is on holiday recently... Travel after I must compensate enough test cases and reopen the pr ....

**Comment by systemovich** [comment]
@HongjiangHuang thanks for working on it.

**Comment by dbudwin** [comment]
Yes, thanks @HongjiangHuang!  I get notifications of this thread and related pull requests so I'll keep an eye on them and provide input.  Enjoy your holiday, and let me know how I can help.  I will gladly test your pull request as well if you need me too.

**Comment by HongjiangHuang** [comment]
I have repaired it and you can close the issues @dbudwin

**Comment by driesvints** [comment]
Should be fixed in the next patch release.

**Comment by dbudwin** [comment]
@HongjiangHuang Thanks!  I'm looking forward to the next release so I can use this patch.  When will the next release be?
