### ISSUE TITLE
macOS Mohave login remember not working anymore in Safari

### ISSUE THREAD

**Issue by renege** [laravel/framework#25767]
- Laravel Version: 5.7
- PHP Version: 7.2
- Database Driver & Version: pgSQL

### Description & Steps To Reproduce:
After upgrading my MacBook to macOS Mohave my login credentials aren't remembered anymore in Safari. When loggin in, it works (I click also on the 'remember me' checkbox). When I close my Safari and re-open again the same page: I'm logged out. Wasn't like this before the upgrade.

**Comment by staudenmeir** [comment]
Which version do you upgrade from?

**Comment by laurencei** [comment]
I feel this is not framework related in anyway.

If anyone can provide support of a bug in Laravel that causes this - I'm happy to reopen  the issue. But the most likely cause is a browser issue or local config issue.
