### ISSUE TITLE
When exception message has binary characters in it, default exception handling with JsonResponse fails

### ISSUE THREAD

**Issue by tdondich** [laravel/framework#25765]
- Laravel Version: 5.6 and above
- PHP Version: 5.6 and above
- Database Driver & Version: mysql 5.7

### Description:
When an exception is thrown and the underlying exception message contains binary encoded data, such as a mysql query with binary columns that fails, the JsonException fails with invalid utf8 characers.

array(5) {
  ["message"]=>
  string(56) "Malformed UTF-8 characters, possibly incorrectly encoded"
  ["exception"]=>
  string(24) "InvalidArgumentException"
  ["file"]=>
  string(79) "/opt/processmaker/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php"
 ...
}

### Steps To Reproduce:
Attempt to execute a mysql query that has binary data in it, such as using spatie's laravel binary uuid package, but have this query fail.  The result Sql Query Exception contains the query that failed, which includes the binary data.

Fixing this would require modifying the Foundation\Exceptions\Handler.php to replace:
            'message' => $e->getMessage(),
 with:
            'message' => utf8_encode($e->getMessage()),

**Comment by sisve** [comment]
Using [utf8_encode](https://secure.php.net/manual/en/function.utf8-encode.php) is probably not the correct solution since the original data isn't in ISO-8859-1 encoding. I don't know of any better solution, json isn't really that great with binary data.

Can we perhaps strip out invalid utf8 characters from the message?

**Comment by tdondich** [comment]
Saying binary is probably incorrect.  At least in this specific context, the characters returned in the SQL Query error contain invalid characters that JsonResponse cannot parse and utilizing utf8_encode facilitates this.  It's highly probable that the result MySQL exception that bubbles up contains valid ISO-8859-1 characters but are invalid in utf8.  So we can safely refactor this ticket to state exceptions containing invalid UTF-8 characters but are valid in ISO-8859-1 triggers a JsonResponse parse exception.

**Comment by driesvints** [comment]
I'll need more info and/or code to debug this further. Please post an example binary data. Please also post relevant code like jobs, commands, notifications, events, listeners, controller methods, routes, etc. You may use https://paste.laravel.io to post larger snippets or just reply with shorter code snippets. Thanks!

**Comment by sisve** [comment]
@driesvints Any binary data with byte values > 127 will work to reproduce this. Either actual raw binary data, or strings in a non-UTF8 encoding. The following test can be thrown into the FoundationExceptionsHandlerTest.php to reproduce the issue.

    public function testReproduceIssue25765_iso88591()
    {
        $this->config->shouldReceive('get')->with('app.debug', null)->once()->andReturn(true);
        $this->request->shouldReceive('expectsJson')->once()->andReturn(true);

        $exceptionMessage = utf8_decode('Något gick galet'); // "Something went crazy", in ISO-8859-1
        $response = $this->handler->render($this->request, new Exception($exceptionMessage))->getContent();

        $this->assertNotContains('<!DOCTYPE html>', $response);
        $this->assertContains('"message": "Något gick galet"', $response);
        $this->assertContains('"file":', $response);
        $this->assertContains('"line":', $response);
        $this->assertContains('"trace":', $response);
    }

**Comment by driesvints** [comment]
Okay, thanks. I'll mark this as a bug and have a look at a later time. Feel free to send in a PR if you figure it out in the meantime.

**Comment by taylorotwell** [comment]
I don't know what Laravel can do about this. It would typically only affect applications with debug mode on and you could likely still view your logs.
