### ISSUE TITLE
$request->user() in test is not returning the expected status in a test

### ISSUE THREAD

**Issue by rfussien** [laravel/framework#25775]
- Laravel Version: 5.7.6
- PHP Version: 7.2
- Database Driver & Version: any

### Description:
With a basic installation of laravel and passport, when I run a basic test of the default route, it fails with a different response status than the one expected.

### Steps To Reproduce:
- Fresh install of laravel + passport

```php
    public function testBasicTest()
    {
        Passport::actingAs(
            factory(User::class)->create()
        );

        $response = $this->get('api/user');

        $response->assertStatus(200);
    }
```

```bash
$ ./vendor/bin/phpunit
PHPUnit 7.3.5 by Sebastian Bergmann and contributors.

.F                                                                  2 / 2 (100%)

Time: 703 ms, Memory: 22.00MB

There was 1 failure:

1) Tests\Feature\ExampleTest::testBasicTest
Expected status code 200 but received 201.
Failed asserting that false is true.

FAILURES!
Tests: 2, Assertions: 2, Failures: 1.
```

If I replace the $request->user() by something else, it works.
```php
Route::middleware('auth:api')->get('/user', function (Request $request, User $user) {
	return $user->find($request->user()->id);
	// return $request->user();
});
```

```bash
$ ./vendor/bin/phpunit
PHPUnit 7.3.5 by Sebastian Bergmann and contributors.

..                                                                  2 / 2 (100%)

Time: 328 ms, Memory: 22.00MB

OK (2 tests, 2 assertions)
```
It behaves that way in the test and correctly when call with a http client.

**Comment by devcircus** [comment]
I believe this is the cause: https://github.com/laravel/framework/pull/21625

A user was created, so laravel attaches a 201 created by default.
When you perform another query as in your second example, to retrieve the user from the database, it is no longer a newly created model.

**Comment by laurencei** [comment]
Thanks @devcircus .
