### ISSUE TITLE
Add translation in throttle exception message

### ISSUE THREAD

**Issue by m4nt4s** [laravel/framework#25770]
Hello,

it would be nice to change throttle exception message by editing translations ;)

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not for ideas, suggestions etc. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. You are able to open a ticket at https://github.com/laravel/ideas

Alternatively you are able to open a PR using the Contributions guidelines: https://laravel.com/docs/5.7/contributions#which-branch

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.

**Comment by staudenmeir** [comment]
Which message are you referring to? "Sorry, you are making too many requests to our servers."?

What's your Laravel version?

**Comment by m4nt4s** [comment]
Laravel version `5.6`
`Illuminate/Routing/Middleware/ThrottleRequests.php`
`'Too Many Attempts.'`
I just want to translate it to my language.

**Comment by staudenmeir** [comment]
Copy `vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/views/429.blade.php` to `resources/views/errors/429.blade.php` and adjust it to your needs.

**Comment by m4nt4s** [comment]
I think more simplier is to add that message to translation ;)

**Comment by laurencei** [comment]
You are welcome to submit a PR with that change :)
