### ISSUE TITLE
[5.7] Bus fake has effect on the queued listeners

### ISSUE THREAD

**Issue by solofeed** [laravel/framework#25780]
- Laravel Version: 5.7.2
- PHP Version: 7.2.8

### Description:
Bus::fake method have the strange effect on queued listeners

I have assert is the notification sent in the listener, but he does not work if he implements ShouldQueue interface. I was check, the listener does not run, because Bus if faked and the listener is queued. So, why it works like this?

How queue related to the bus? I want to leave the listener with the queue

### Steps To Reproduce:

1. Create queued listener
2. Create a test case with the Bus faked, test the listener handle method.

AR: Listener does not run
ER: Listener ran and dispatch a notification

**Comment by timacdonald** [comment]
Ran into this exact thing. The event dispatcher will push on jobs to the `Queue` not using the bus and will wrap them in a core class `Illuminate\Events\CallQueuedListener`. Here is what I'm doing...

```
Queue:fake();

$this->post('something-that-dispatches-queued-events', ['fingers' => 'crossed']);

Queue::assertPushed(\Illuminate\Events\CallQueuedListener::class, function ($job, $queue) {
    // here you can check some things about the Listener.
    // I'll just check the listener I expected was queued.
    return $job->class === \App\Listeners\PostCreatedListener::class;
});
```

**Comment by driesvints** [comment]
I can't reproduce this. Please share:

- The job
- The event
- The listener
- The test

Everything that's needed to reproduce this. Feel free to reply with above things and I'll gladly reopen.
