### ISSUE TITLE
Eloquents' Builder will not return grammar

### ISSUE THREAD

**Issue by tpetry** [laravel/framework#25789]
- Laravel Version: 5.7.6

### Description:
Calling `getGrammar()` on `Illuminate\Database\Eloquent\Builder` will return the Builder object but not the `Grammar` object: This is because `getGrammar` is not included in the `$this->passthru` definition which is used by `__call`. So the `getGrammar` method will be called on the base query but the value will be omitted as it's opt-in for the passthru mode is not set so the actual instance is returned.

### Steps To Reproduce:
```php
/** @var \Illuminate\Database\Eloquent\Builder $query */
$builder = (new SomeEloquentModel)->newQuery();

# WRONG: Builder object instead of Grammar
dump($builder->getGrammar());
```

**Comment by laurencei** [comment]
As per Tayor in the PR - you can just do

```
$builder->getQuery()->getGrammar()
```
