### ISSUE TITLE
Windows Terminal not support color

### ISSUE THREAD

**Issue by ritaswc** [laravel/framework#25798]
First,we look a picture 

https://wx3.sinaimg.cn/large/3fcf5ac9ly1fvnwac0v5xj20lw05kglu.jpg

When I run **php artisan**  command, these is word like **?[33m** color feature words

In Windows, terminal do not support color character

EXCEPT install new terminal software

Can I disable ARTISAN color feature ????

**Comment by laurencei** [comment]
Which terminal software doesnt support colors? I use Windows and colors works fine for me with PowerShell?

Try `php artisan --no-ansi` - does that work?

**Comment by ritaswc** [comment]
> Which terminal software doesnt support colors? I use Windows and colors works fine for me with PowerShell?
> 
> Try `php artisan --no-ansi` - does that work?

phpstorm's terminal

**Comment by laurencei** [comment]
Cool - glad that helped

**Comment by ritaswc** [comment]
Thank your help
