### ISSUE TITLE
Redis::funnel, lock not released when job failed

### ISSUE THREAD

**Issue by Broutard** [laravel/framework#25795]
- Laravel Version: 5.7
- PHP Version: 7.2

### Description:
I have 4 queue workers on the same queue. 
My jobs can be very long to process (several tens of minutes).
I have to limit theses workers to process simultaneously a specific type of jobs (per "projectId").

The documentation recommands to use Redis::funnel.

By default, Redis::funnel release the lock after 60sec, so that's what I did to be sure that my lock is not released before the job was finished :
```
Redis::funnel('funnel' . $this->projectId)->releaseAfter(3600)->limit(1)->then(function () {
    // Job logic...
}, function () {
    // Could not obtain lock...
    return $this->release(10);
});
```
... but if a job failed, the lock is not released automaticaly and I have to wait the lock TTL (ie. 3600sec) until another job can be processed.

**Comment by laurencei** [comment]
Can you just modify the fail code and also do a release there?

**Comment by Broutard** [comment]
A failed job is already released... but the lock in redis is still present (I find no way to remove the redis lock)

**Comment by Broutard** [comment]
Possible workaround
```
Redis::funnel('funnel' . $this->projectId)->releaseAfter(3600)->limit($limit = 1)->then(function () use ($funnelKey, $limit) {
    try {
        // Job logic...
    } catch (\Exception $e) {
        Redis::del($funnelKey.$limit);
        throw $e;
    }
}, function () {
    // Could not obtain lock...
    return $this->release(10);
});
```

**Comment by HongjiangHuang** [comment]
I have repaired it and you can close the issues  @Broutard

**Comment by Broutard** [comment]
Thanks @HongjiangHuang

**Comment by francescosalvi** [comment]
Late to the party, but wanted to point out (fort those that for whatever reason have to stick to using Laravel < 5.7.22) that @Broutard 's solution only works if `$limit = 1`, because otherwise there would be no way of knowing which exact "slot", and therefore key, has been acquired by the process (see `\Illuminate\Redis\Limiters\ConcurrencyLimiter::luaScript`)
