### ISSUE TITLE
Why are some script commands not being scheduled to work?

### ISSUE THREAD

**Issue by xiaoxing598** [laravel/framework#25796]
- Laravel Version: 5.6.28
- PHP Version: 7.1.x
- Database Driver & Version:

### Description:
I defined a set of scripts to execute in the schedule method, but not all scripts are executed. When I first ran "schedule:run", only some of the scripts were running, and the strategy they executed was to run every minute.

### Steps To Reproduce:

```php
protected function schedule(Schedule $schedule)
{
        $schedule->command('ticket:create_file 0')->cron('*/1 * * * *')->withoutOverlapping();
        $schedule->command('ticket:create_file 1')->cron('*/1 * * * *')->withoutOverlapping();
        $schedule->command('ticket:create_file 2')->cron('*/1 * * * *')->withoutOverlapping();
        $schedule->command('ticket:create_file 3')->cron('*/1 * * * *')->withoutOverlapping();
        $schedule->command('ticket:create_file 4')->cron('*/1 * * * *')->withoutOverlapping();
}
```

```sh
E:\demo>php artisan schedule:run
Running scheduled command: "D:\PhpStudy\PHPTutorial\php\php-7.2.1-nts\php.exe" artisan ticket:create_file 0 > "NUL" 2>&1
Running scheduled command: "D:\PhpStudy\PHPTutorial\php\php-7.2.1-nts\php.exe" artisan ticket:create_file 2 > "NUL" 2>&1
Running scheduled command: "D:\PhpStudy\PHPTutorial\php\php-7.2.1-nts\php.exe" artisan ticket:create_file 3 > "NUL" 2>&1
Running scheduled command: "D:\PhpStudy\PHPTutorial\php\php-7.2.1-nts\php.exe" artisan ticket:create_file 4 > "NUL" 2>&1
```

You can see that there is one less command executed above, and this is the case after repeated attempts. But not on all computers, such as on a colleague's computer, it will execute all five commands. I also tried to execute in the CentOS environment, but there is a certain probability that this problem will occur.

**Comment by laurencei** [comment]
You have `->withoutOverlapping()` - which means the script might not run every minute if the previous one is still running (or it did not correctly clear the cache).

**Comment by xiaoxing598** [comment]
@laurencei But this is five different scripts. Can't treat them as the same one. Is this a flaw?

**Comment by xiaoxing598** [comment]
I dispatched the code and found that the code exited here, not the reason for withoutOverlapping. Next I have to see why I will quit here.

```php
if (! $event->filtersPass($this->laravel)) {
                continue;
}
```

**Comment by laurencei** [comment]
> I dispatched the code and found that the code exited here, not the reason for withoutOverlapping. 

`withoutOverlapping` is determined by `filtersPass` - so this is correct.

**Comment by xiaoxing598** [comment]
I am a bit confused now, why is it not the same on all systems, one computer is running normally and the other is not working properly.

Although the commands are the same, but the parameters passed are different, the framework should treat them as two different commands, or let the developers choose. Now I have to create some files repeatedly, even if their code is very similar.

**Comment by laurencei** [comment]
> Although the commands are the same, but the parameters passed are different, the framework should treat them as two different commands

It does. I'm saying that the command 

`$schedule->command('ticket:create_file 1')->cron('*/1 * * * *')->withoutOverlapping();`

is overlapping from the previous minute.

If you run `php artisan cache:clear` - that might resolve your issue.

**Comment by xiaoxing598** [comment]
> If you run php artisan cache:clear - that might resolve your issue.

Thanks, the lost order is back, but I am worried that it will be lost twice. If I encounter such a problem again, I will report it twice, thank you!
