### ISSUE TITLE
Making model results display in terminal and does not create model

### ISSUE THREAD

**Issue by Elandlord** [laravel/framework#25801]
- Laravel Version: 5.6.7
- PHP Version: 7.1.12
- Database Driver & Version:  MariaDB V10.1.29
- Windows 10 Pro

### Description:
Today I noticed a strange thing while creating a new model called: Con. Instead of creating a model, it displays the output of the command to the terminal, followed up by the message  `Model created succesfully.` 

Ironically, the model is never created.

I asked other people with comparable set-ups, and they are having the same issue. I tried several terminals like: Git Bash and Windows Powershell.

### Steps To Reproduce:
- Set-up environment as listed above.
- Run the command `php artisan make:model Con`.
- The output of the model is displayed in your terminal rather and the model is never created.

I also have this issue while creating a Nova resource:
![image](https://user-images.githubusercontent.com/5966835/46140288-fba70780-c250-11e8-894d-ce8f53ce4768.png)

If `Con` is a reserved word while making a model, maybe a solution could be to give the user feedback in the terminal that this is not a valid name for the model?

**Comment by laurencei** [comment]
Works for me in Windows 10?

![image](https://user-images.githubusercontent.com/1210658/46140445-7b09fa80-c294-11e8-95dc-7775bcbfbeae.png)

Is `Con` a reserve word in one of your Windows scripts maybe?

**Comment by laurencei** [comment]
Reading around a little - it looks like `con` is a **Windows** command to copy console output.

https://www.computerhope.com/jargon/c/copycon.htm

So it seems a limitation of some Windows systems and nothing to do with Laravel.

Interesting issue though :)

**Comment by Elandlord** [comment]
Thanks for you answer!

Indeed, it's an interesting issue. I was pulling my hair out over this haha :)
