### ISSUE TITLE
Exists rule for nullable values

### ISSUE THREAD

**Issue by dorin-niscu** [laravel/framework#25814]
I am using Laravel 5.6.

When I send tags IDs everything works fine.
I am getting errors when sending an empty tags array (so I can dettach them.).
This happens only for arrays. If I send a single tag it works fine too.

Shouldn`t **exists rule** ignore the field if it is **null** ?

```
protected $rules = [
    'title'            => ['required', 'string', 'between:3,60'],
    'slug'             => ['required', 'string', 'between:3,60'],
    'description'      => ['sometimes', 'string', 'between:3,200'],
    'tags'             => ['sometimes', 'nullable', 'array', 'exists:tags,id', 'max:2'],
];

```

```
{
    "message": "The given data was invalid.",
    "errors": {
        "tags": [
            "The selected tags is invalid."
        ]
    }
}
```

**Comment by staudenmeir** [comment]
You are sending an empty array, right? Not an actual `null` value?

**Comment by dorin-niscu** [comment]
I am sending an empty array but the values are converted into null values by a middleware.

**Comment by staudenmeir** [comment]
So the validator receives an array that contains a `null` value?

**Comment by staudenmeir** [comment]
What data does the validator receive for `tags`?

**Comment by dorin-niscu** [comment]
Exactly. 
$tags = [0 => null];

**Comment by staudenmeir** [comment]
I'll fix it. Just out of curiosity: Is the data coming from an HTML form?

**Comment by dorin-niscu** [comment]
In this moment i am only testing it with postman.

**Comment by dorin-niscu** [comment]
In was thinking to validate the array elements instead as a compromise (tags.*).

**Comment by phannaly** [comment]
I'm not sure but look like `nullable` only validate a null value not array null

**Comment by dorin-niscu** [comment]
Yes, I think so. Probably that’s why it works when using tags.* rule for each element.

**Comment by staudenmeir** [comment]
I think an array validation with `tags.*` would be the "right" approach here. I don't think there's even a way to generate this kind of data from an HTML form.

**Comment by dorin-niscu** [comment]
Yes, or I could just not send the tags if no one checked and use sync with empty [] to detach the old tags on edit.

**Comment by dorin-niscu** [comment]
From my point of view everything is clear now.
I think we can close it.

**Comment by staudenmeir** [comment]
You can close it ;-)
