### ISSUE TITLE
illuminate/console suggest symfony/process change to require symfony/process

### ISSUE THREAD

**Issue by HongjiangHuang** [laravel/framework#25815]
- Laravel Version: 5.7
- PHP Version: php7
- Database Driver & Version: mysql 5.6

### Description:
When I try to use the console alone component and run ` composer install --no-dev `
Throw the following exception
```
PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Process\PhpExecutableFinder' not found in /Users/huanghongjiang/PhpstormProjects/BellCode/CodingMonkey/Api/vendor/illuminate/console/Application.php:105
```

If lack of ` symfony/process ` cannot run normally, should declare the require

### Steps To Reproduce:

`composer require illuminate/console:5.7 && composer install --no-dev `

**Comment by staudenmeir** [comment]
Please close the issue.
