### ISSUE TITLE
How to use the routing model in lumen

### ISSUE THREAD

**Issue by CrazyZard** [laravel/framework#25833]
I'm used "  'bindings' => \Illuminate\Routing\Middleware\SubstituteBindings::class "  in lumen 
but  it's wrong 
Target [Illuminate\\Contracts\\Routing\\Registrar] is not instantiable while building [Illuminate\\Routing\\Middleware\\SubstituteBindings]
How do I solve it

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
