### ISSUE TITLE
Improve unit-testing error reporting

### ISSUE THREAD

**Issue by FrancescoMussi** [laravel/framework#25835]
- Laravel Version: 5.7
- PHP Version: 7.1.3

### Description:

Unit-testing inside Laravel seems a bit cumbersome. Each time there is an error it's not easy to locate the actual error report. We have to scroll up hundreds of lines each single time.

![screen shot 2018-09-30 at 11 39 01](https://user-images.githubusercontent.com/5312907/46255500-5a18f380-c4a6-11e8-900d-030ccf8a2968.png)

Could be possible to avoid all those lines altogether and just report the error?
Or alternatively, could we have some settings where we can hide those lines?

**Comment by deleugpn** [comment]
Have you tried disabling debug with `APP_DEBUG=0`?

**Comment by HongjiangHuang** [comment]
Could you provide error information? The picture is not clear

**Comment by HongjiangHuang** [comment]
> Have you tried disabling debug with `APP_DEBUG=0`?

`APP_DEBUG=0`  You will not see the error message ?

**Comment by FrancescoMussi** [comment]
@HongjiangHuang  Yes in the picture I resize the font very small to try to give the idea of how many lines there were in the console :)

I have set APP_DEBUG to 0 and I don't see all that bunch of error lines anymore!

Thanks!
