### ISSUE TITLE
[5.7] Route fallback redirecting to a 404 of a missing asset

### ISSUE THREAD

**Issue by TivoSoho** [laravel/framework#25865]
- Laravel Version: 5.7.2
- PHP Version: 7.2

### Description:
I want to redirect to a proper page with navigation in case of a 404. To achieve this I used the new Route::fallback. It works if the entire page is a 404. It does not work if you are redirecting to a page that has a 404 in the background, for example trying to access a non-existent asset. The missing asset can also be a source map. This means that if you have redirects with "intended", it breaks redirects. 

### Steps To Reproduce:
1. Add a fallback.
2. Have a missing asset.
3. With login have the login response as: redirect()->intended($this->redirectPath()) [this is default btw, sendLoginResponse in trait Illuminate\Foundation\Auth\AuthenticatesUsers]
3. Log out
4. Log back in. It redirects to the missing asset instead of the true previous URL since it registered the attempt to render the asset as a "previous" URL on page load.

**Comment by TivoSoho** [comment]
To be clear. This only started happening with the fallback addition. Before we never noticed any issues. And while for now I have ended up using a custom fallback pattern to make sure the asset routes are not "logged", it does bring up a bigger issue. If for example there is a failing AJAX call on the site where I logout. The last intended route could possibly be something that is never meant to be accessed directly, let alone redirected to it!

I feel this is not thought properly through and should come with very large warning signs and proper documentation of what will start to happen if you enable this. More so it would be great that being aware of this we can perhaps start marking routes as if they should be allowed to be logged as a previous URL or not, or even give it with the request we are making (e.g. if the route itself could be accessed directly, but currently we are using a background request instead). It could offer some relief.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not for ideas, suggestions etc. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. You are able to open a ticket at https://github.com/laravel/ideas

In regards to your documentation idea - you can open a ticket at https://github.com/laravel/docs

Thanks in advance.

**Comment by TivoSoho** [comment]
So because I suggested ways to maybe fix this BUG then you are closing this BUG case? Seriously?

**Comment by laurencei** [comment]
What's the bug? If your assets does not exist it will 404 - that is expected?

**Comment by TivoSoho** [comment]
Perhaps my steps to reproduce were not clear and I have updated it. The issue with having a fallback is that it breaks previous URLs in case of a missing asset. I believe there should be a more valid workaround, especially as I am using the Laravel provided "asset" function. At the moment basically Laravel is conflicting with itself, it's own default functionality. The asset method for example could add ?nofollow, or something to the URL to make sure it knows not to add it to a list of previous URLs and thus on login it shall not redirect you to a missing asset if previously before logout you were somewhere completely different.

From my test AJAX requests seemed to be smart enough not to break it and thus there is a way to do it. 

For the record, the missing asset that triggered this is of course not intentional, but since I have dev tools open and have enabled source maps, then including Popper via webpack failed to include or remove the source map availability and thus resulting in a missing asset 404. On login instead of redirecting to an intended URL, it redirected me to js/popper.js.map all the time. As I was not using Popper I could remove it from being included as well, but this does not remove the fact that assets conflict with fallbacks.

**Comment by dbezborodovrp** [comment]
I have also encountered this issue where I had a fallback route that would be used to handle requests to legacy parts of our software and either provide a valid response or a 404 if the resource is not found in our legacy codebase. However, in the unusual circumstance that there is an asset on the page that does not exist (such as an image) the login controller will redirect to this missing asset after logging in.

I suppose a fix would be to only register the last visited resource if it is valid (as in the fallback route returns a 200 OK response.)
