### ISSUE TITLE
url()->previous() is not highlited in IDE

### ISSUE THREAD

**Issue by vladyslavstartsev** [laravel/framework#25860]
- Laravel Version: 5.6.38
- PHP Version: 7.2.9

### Description:
The `url()`  which returns `\Illuminate\Contracts\Routing\UrlGenerator` is not highlited in IDE.
This method usage you can see here
https://github.com/laravel/framework/blob/5.6/src/Illuminate/Foundation/Exceptions/Handler.php#L248-L253
### Steps To Reproduce:
call url()->previous() somewhere in code when using PHPStorm

How can it be solved
add method `previous` to `Illuminate\Contracts\Routing\UrlGenerator` interface

**Comment by X-Coder264** [comment]
Adding a new method to an interface is a breaking change and so it cannot go into 5.6, but the change was made already and it will be in 5.8 (https://github.com/laravel/framework/pull/25616).
