### ISSUE TITLE
Paginator appends not adding to meta of api resource collection json

### ISSUE THREAD

**Issue by isometriq** [laravel/framework#25879]
- Laravel Version: 5.6.11
- PHP Version: 7.1
- Database Driver & Version: 5.6

### Description:

Paginator `appends` method does not add data in the "metas" of the json data generated by an API resource collection.

### Steps To Reproduce:

```
$pagination = $query->paginate();
$pagination->appends([
    'key' => 'value',
]);
return new JsonResource::collection($pagination);
```

**Comment by isometriq** [comment]
Also would like these key/values to be in the generated "links", for instance
```
"links": {
    "first": "http://localhost:8000/api/resource?page=1&key=value",
    ...
}
```

**Comment by HongjiangHuang** [comment]
I think you can try
```
$pagination = $query->paginate();
$pagination->appends([
    'key' => 'value',
]);
return new JsonResource::collection($pagination);
```

**Comment by mfn** [comment]
> Paginator `appends` method does not add data in the "metas" of the json data generated by an API resource collection.

Why do you expect that?

**Comment by isometriq** [comment]
@HongjiangHuang Good catch, but it was only a copy-paste typo, I'm correcting the sample

**Comment by HongjiangHuang** [comment]
Hmm. I think you use ` appends `, problem solved

**Comment by isometriq** [comment]
@HongjiangHuang Problem is not solved. `appends` work when returning the paginator in a controller, but does not apply when wrapped by a resource.

By debugging the source in vendor folder, we can see that the data is there, but not used. Only specific keys are used:
https://github.com/laravel/framework/blob/bf975fa30108a873098f8bd8ee348f8f4a3130f6/src/Illuminate/Pagination/LengthAwarePaginator.php#L161

The `appends` method:
https://github.com/laravel/framework/blob/bf975fa30108a873098f8bd8ee348f8f4a3130f6/src/Illuminate/Pagination/AbstractPaginator.php#L198

**Comment by isometriq** [comment]
oh well.. after test a few times, I see that the `appends` method does indeed inject in the `links` section of the json and not the `meta`. And that seems right to me.

And if I need stuff to appear in the `meta` I can just use a `ResourceCollection`.

Thanks for the input.

**Comment by youruan** [comment]
maybe you want this 
      ` $total_fee = $builder->sum('user_fee');

        $orders = $builder->latest()->paginate(10);

        return OrderResource::collection($orders)->additional([
            'meta' => [
                'total_fee' => $total_fee,
            ]
        ]);
`

then, the meta total_fee in response's meta

**Comment by desertnightsky** [comment]
On Dec 16, 2018, at 6:08 PM, youruan <notifications@github.com> wrote:

maybe you want this
` $total_fee = $builder->sum('user_fee');

    $orders = $builder->latest()->paginate(10);

    return OrderResource::collection($orders)->additional([
        'meta' =>+1 [
            'total_fee' => $total_fee,3500
        ]
    ]);
`

then, the meta total_fee in response's meta

**Comment by isometriq** [comment]
@ddarrko you can check the snippet in my original post. You have to pass an associative array (param/value).

**Comment by shez1983** [comment]
i think this kind of thing should be baked into the framework.. because most times if you have a filter clause (e.g. filter['name'] or w/e. the pagination links dont make sense if they dont have this additional params.. just a fyi.. having to do ^ is a bit annoying
