### ISSUE TITLE
Pagination Link

### ISSUE THREAD

**Issue by shahvirag07** [laravel/framework#25894]
Page number is repeating on current page is 3rd and current page is 3rd last page,
`{{ $users->onEachSide(1)->links() }}`

![pageination2](https://user-images.githubusercontent.com/24240840/46396415-fe9c6f00-c70c-11e8-9559-a37d045f0a03.PNG)
![pageination1](https://user-images.githubusercontent.com/24240840/46396407-f93f2480-c70c-11e8-9fa3-1a1c18674e94.PNG)

**Comment by staudenmeir** [comment]
Please close the issue.
