### ISSUE TITLE
Laravel spark 7.1 blade escaping bug

### ISSUE THREAD

**Issue by nnerijuss** [laravel/framework#25893]
- Laravel Version: 5.7.7
- PHP Version: 7.2
- Database Driver & Version: Mysql 5.7
- Absolutely fresh Laravel and Spark install
- Development environment WSL

### Description:
After installing fresh laravel ant spark packages, all blade directives {!! ... !!} that should not be escaped is escaped.

### Steps To Reproduce:
Login page:
![Login page](http://www.part.lt/img/b4d201b49facf34504645ff96cc58e5b285.png)

Subscriptions page:
![Subscriptions page](http://www.part.lt/img/183d645aeaf6f3d94dd88b72a8717e01417.png)

**Comment by laurencei** [comment]
ping @themsaid

**Comment by laurencei** [comment]
although this probably should be moved to the Spark repo

**Comment by themsaid** [comment]
I can't replicate this, and yes should be reported on the Spark repo or via support email. spark@laravel.com

**Comment by lowertown** [comment]
@themsaid, there was a commit to the laravel framework yesterday that seems to be affecting links in __ helper function place holders for localization.  I'm seeing it on the Spark registration page too, but I don't think it is a Spark specific issue.

https://github.com/laravel/framework/commit/98046cb0c81b418fb4046ade034f3d33a4172239
