### ISSUE TITLE
Laravel 5.4.36 session not persisting. Creating new session file on page refresh. Please help!

### ISSUE THREAD

**Issue by Pakistani** [laravel/framework#25903]
Hi,

I am badly struggling with this problem and still unable to find solution.
It is simplest thing i am trying to do, i am just trying to store a variable in file based session.
Every time i refresh page, a new session file is being create under: storage/framework/sessions/
i am running server through "php artisan serve" at port 7865 and running PHP 5.6.25. I have create a fresh project with "composer create-project laravel/laravel laravel_test 5.4.*  --prefer-dist" command.
I already made sure that "\Illuminate\Session\Middleware\StartSession::class" is being load only once, i have kept it in "$middleware". It doesn't change anything even if i move it to "$middlewareGroups"

Following is excerpt from app/Http/Kernel.php:
`<?php
    protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
        \Illuminate\Session\Middleware\StartSession::class,
        \Illuminate\View\Middleware\ShareErrorsFromSession::class,
    ];

    /**
     * The application's route middleware groups.
     *
     * @var array
     */
    protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            // \Illuminate\Session\Middleware\AuthenticateSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],

        'api' => [
            'throttle:60,1',
            'bindings',
        ],
    ];

    /**
     * The application's route middleware.
     *
     * These middleware may be assigned to groups or used individually.
     *
     * @var array
     */
    protected $routeMiddleware = [
        'auth' => \Illuminate\Auth\Middleware\Authenticate::class,
        'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        'bindings' => \Illuminate\Routing\Middleware\SubstituteBindings::class,
        'can' => \Illuminate\Auth\Middleware\Authorize::class,
        'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
        'throttle' => \Illuminate\Routing\Middleware\ThrottleRequests::class,
    ];
`

Following is excerpt from config/session.php
`'driver' => env('SESSION_DRIVER', 'file'),
'lifetime' => 1200,
'encrypt' => false,
'domain' => env('SESSION_DOMAIN', "http://127.0.0.1:7865"),`

Following is code that i am running from a controller named TasksContoller under "index" action:
`<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class TasksController extends Controller
{
    public function index(Request $request)
    {
        print "Before:".$request->session()->get('testvar')."<br>";
        session()->put('testvar', session()->get('testvar') + 1 );
        session()->save();
        print "After:".session()->get('testvar')."<br>";
        die("ended!!!!");
    }
}
`

Many people talked about similar problem at stackoverflow but none of their solutions work, is it a bug in this version? Any idea what is wrong? Thank you!

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.

**Comment by laurencei** [comment]
> Can you please try to put a variable in session and refresh the page? 

Sorry - works for me: 

```
Before: After:1 ended!!!!
Before:1 After:2 ended!!!!
```

Can you try install Laravel 5.6.29 and let me know if that works?

**Comment by Pakistani** [comment]
Hi,
Thanks again for your response and checking it.
I tried a fresh laravel v5.7.0 installation on a new computer where i had PHP 7.1.7 installed.
With "File" as session handler, it worked only in google chrome. But session are not persisting in Firefox and Safari. Even when i try to open same url in google chrome's incognito mode, it fails to persist session. This surely seems a bug, perhaps in combination with "php artisan serve" based laravel running.

I did screen recording as well, please have a look: 
https://drive.google.com/open?id=1FAjyd1OcWnBJ_22MQj_2TSd-oTjjg1xs

**Comment by laurencei** [comment]
But did you try Laravel 5.6.29? There was a change to how files are handled in 5.6.30  - so I was wondering if it was related to that.

**Comment by Pakistani** [comment]
hi,

First of all, thank you for your help in this regard.
I think i figured out the reason behind this weird problem.
if i am setting session variable in a controller's action and don't have a view for that action or if i make it die(); in that action, session won't be persistent even if you have called session()->save();

Problem here is that if i get to set a session variable in an action and immediately redirect flow through header('Location: http://www.example.com/') to another page, Session won't be persisted.
Unfortunately it seems like that, but please correct me if it is not so. I am sure many should had faced similar situation.

PS: I have tried it on both Mac and Windows having PHP's version 5.6.25, 7.1.1 and 7.2
