### ISSUE TITLE
Text translation method escapes characters of transmitted values.

### ISSUE THREAD

**Issue by andrey-helldar** [laravel/framework#25917]
- Laravel Version: 5.7.7 (clear installed)
- PHP Version: 7.2.9 (Laravel Homestead 7.18.0)

```php
// resources/lang/en/unk.php
return [
    'foo' => 'first :value string',
    'bar' => 'second &nbsp; string',
];
```

```blade
// resources/views/welcome.blade.php
@php($q = '1&nbsp;2')

{!! $q !!}
{!! __('unk.foo', ['value' => $q]) !!}
{!! __('unk.bar') !!}
```

Result:
```
1&nbsp;2
first 1&amp;nbsp;2 string
second &nbsp; string
```
Method `trans()` produces exactly the same results.

It should be:
```
1&nbsp;2
first 1&nbsp;2 string
second &nbsp; string
```

Example from the site:
The database has a field with the cost of the car: `15366232.00`
It needs to be displayed on the page as `from 15 366 232 ₽`
File `resources/lang/*/info.php` has lines: `'priceFrom' => 'from :price ₽',`

```php
function price_format($value): string
{
    return number_format($value, 0, '.', '&nbsp;');
}
```

```blade
{!! __('info.priceFrom', ['price' => price_format($car->price)]) !!}
```

[Commit from Taylor](https://github.com/laravel/framework/commit/98046cb0c81b418fb4046ade034f3d33a4172239) added many problems when using a `trans()` helper.

Nice prices (no):
![2018-10-04 11-50-27 mercedes-benz e- - google chrome](https://user-images.githubusercontent.com/10347617/46463072-be4ff600-c7cb-11e8-82cc-7b8d88873b27.png)

Passing the space character code to a parameter is necessary so that when changing the width of the browser window, the cost does not break into two lines.
For example:
```
от 3 505
845 ₽
```

And also, in the current state of affairs, instead of
```blade
{!! __('info.priceFrom', ['price' => price_format($car->price)]) !!}
```
write
```blade
{{  __('info.from') }}
{!! price_format($car->price) !!}
{{  __('info.currency.rub') }}
```

🤷😒

**Comment by bonzai** [comment]
Related PR - #25858.

**Comment by laurencei** [comment]
This is expected behaviour due to a recent security patch.

**Comment by bonzai** [comment]
@laurencei: You're talking about d3c0a369057d0b6ebf29b5f51c903b1a85e3e09b which is not related to this issue. If you read https://github.com/laravel/framework/pull/25858#issuecomment-426552670 you'll see that related PR is a breaking change in 5.7.

**Comment by laurencei** [comment]
Thanks @bonzai - I didnt realise it was seperate.

**Comment by andrey-helldar** [comment]
Taylor recommends (#25919) using `new HtmlString('foo')` inside Blade templates. This idea looks like a wild crutch.

**Comment by taylorotwell** [comment]
I'm reverting this entire dumpster fire. Will just document if you use @lang its up to you to escape.
