### ISSUE TITLE
Validating arrays passes values, which does not described in rules

### ISSUE THREAD

**Issue by solofeed** [laravel/framework#25918]
- Laravel Version: 5.7.2
- PHP Version: 7.2

### Steps To Reproduce:
1) Make  rules
```
'address'  => 'array',
'address.address_line1' => 'string|max:250',
```

2) Send request with another values inside array
3) Get values from $request->validated()

**Comment by laurencei** [comment]
I'm not sure what you are saying?

If you allow `address` to be an `array` - then it is expected to allow that array to pass through?

If you dont want the whole array to pass through, then you would need to explicity define what sections to validate, and not have `'address'  => 'array',` at all

**Comment by solofeed** [comment]
@laurencei If send the request with data 
```
{
    "address": {
         "address_line1" : "test",
         "not_validated_value": "value"
    }
}
```
Then in $request->validated() shouldnot exists "not_validated_value"

**Comment by mfn** [comment]
@solofeed Understood, but it's not a bug. It's the way it's implemented.

If you want to alter existing behaviour, please suggest/discuss it at https://github.com/laravel/ideas
