### ISSUE TITLE
Persistent connection (MySQL connection id) still the same even if there are different user is logging-in.

### ISSUE THREAD

**Issue by anonymouse703** [laravel/framework#25916]
Hello guys, I just have a little confusion about this one.

Case: 
We had to convert the desktop application (vb 6) into web application which has a module of "Connection Monitoring"

**Connection Monitoring usage:** In the desktop app, The admin was able to list all active connection and who's this connection belongs to (user) and the admin has the authority to close the connection of that specific user.

If the admin hit "Close Button" the application will be terminated (closed) and the connection will be kill.

**Converted application(Web application):**

So far, this is my implementation.

I create a table (user_connection) to store persistent connection id in each user who will login.

In my Login Controller, I have this code.

```
public function authenticated(Request $request, $user)
  { 
    
    $con_id = DB::select('select connection_id() as id');

     Userconn::updateOrCreate(
                            [
                                'conn_id' => $con_id[0]->id
                            ],
                            [
                                'conn_user_id' => Auth::user()->id,
                                'conn_ip' =>  $request->getClientIp()
                            ]);
    
  }
```

and in my Connection Controller.

```
public function index()
    {

     $connections = DB::select('select * from information_schema.PROCESSLIST');

     $arrayOfId = [];

     foreach($connections as $connectionID) {
        $arrayOfId[] = $connectionID->ID;
     }

     $users = UserConn::whereIn('conn_id', $arrayOfId)->get();
    
     return view('connection-monitoring.index', compact('users'));

 }
```

Problem (encountered):

When I open three browsers and login three different users the connection_id is the same.

ex. In Google chrome: When I `dd($con_id)` the result is
```
array:1 [▼
  0 => {#613 ▼
    +"id": 1
  }
]
```

In Google chrome incognito: When I `dd($con_id)` the result is
```
array:1 [▼
  0 => {#613 ▼
    +"id": 1
  }
]
```

In Firefox: When I `dd($con_id)` the result is
```
array:1 [▼
  0 => {#613 ▼
    +"id": 1
  }
]
```

Is there way to get each user a unique MySQL connection id or Laravel has limitations to this for their are different ways on sending request? Just confused.

**Comment by sisve** [comment]
This doesn't translate identically between a desktop application and a web application. What you describe as a connection would be a session using web terminology. You cannot use mysql's connection identifiers for this purpose.

When looking at "connection monitoring", I presume you want to see who are using the application and be able to log them out. In this regard, try using the database-backed session provider in where you can `SELECT * FROM SESSIONS` to list them all, and remove them if necessary (`DELETE FROM sessions WHERE id = ...`).

Anyhow, this isn't really a bug in the framework. You should probably close this issue, and discuss it further elsewhere. There's always Slack, Laracasts, Discord and other places available for these discussions.

**Comment by laurencei** [comment]
Thanks @sisve
