### ISSUE TITLE
Undefined variable: subcopy (View: 

### ISSUE THREAD

**Issue by VConsulting** [laravel/framework#25921]
- Laravel Version: 5.7
- PHP Version: 7.2.8
- Database Driver & Version:

### Description:
I have the following error and no idea what to do:

Undefined variable: subcopy (View: ...

``
                                    <td class="content-cell">
                                        {{ Illuminate\Mail\Markdown::parse($slot) }}
                                        {{ $subcopy or '' }}
                                    </td>
``

**Comment by manelgavalda** [comment]
> The Blade "or" operator has been removed in favor of PHP's built-in ?? "null coalesce" operator, which has the same purpose and functionality:
> 
> // Laravel 5.6...
> {{ $foo or 'default' }}
> 
> // Laravel 5.7...
> {{ $foo ?? 'default' }}
> 

Reference: https://laravel.com/docs/5.7/upgrade

**Comment by laurencei** [comment]
Thanks @manelgavalda
