### ISSUE TITLE
Same Route and view folder name produce 404 Not Found Error

### ISSUE THREAD

**Issue by Illusionist3886** [laravel/framework#25928]
- Laravel Version:  5.7.7
- PHP Version: 7.2.10
- Database Driver & Version: MySQL [10.1.36-MariaDB]

### Description: 
If view directory name inside **resources/views** matche the **Rooute::** it produces **Not Found** error.

> The requested resource /userdashboard was not found on this server.

### Steps To Reproduce:
You can simplly create a directory inside view and use that name in route to reproduce the issue.

Example Route:
```
Route::get('/userdashboard', function(){
    return view('userdashboard.profile');
});
```

**Comment by staudenmeir** [comment]
Is the directory named `userdashboard`?

**Comment by Illusionist3886** [comment]
Yes. And the route works if I just change it a little bit. For example **/myuserdashboard**
The problem occurs with only same Route and View name.

**Comment by staudenmeir** [comment]
It works for me. Can you reproduce this issue on a fresh Laravel installation?

**Comment by 36864** [comment]
I can reproduce this on 5.7, but not on 5.6.

**Comment by staudenmeir** [comment]
What does the error message look like? Is it a [server/PHP error](https://stackoverflow.com/questions/38124626/the-requested-resource-was-not-found-on-this-server-php)? Or does it look like it comes from Laravel?

**Comment by laurencei** [comment]
> If view directory name inside resources/views matche the Rooute:: it produces Not Found error.

> The requested resource /userdashboard was not found on this server.

That's a different error to what you've listed above.

Either way - the code works fine on a fresh install of Laravel 5.7. Start with a clean install and work from there to see where your error lies.
