### ISSUE TITLE
notice issue showing 500 error

### ISSUE THREAD

**Issue by rajansinghrawat** [laravel/framework#25920]
- Laravel Version: 5.7.4
- PHP Version:7.2.10
- Database Driver & Version:Mysql 5.7.23

### Description:

When notice occured in laravel it showing status code 500 (internal server error).
And execution stopped.

        public function update(Request $request, $id)
          {
		
		$error = array();
		
		$service_data = $request->all();

		try {
			$data = Service::findorfail($id);
		} catch (ModelNotFoundException $exception) {
			
			$error = array(
				
				"name" => "Data not found",
				"message" => "Requested ID not found.",
			
			);
			
		}
		
		if(empty(trim($service_data['name']))){
			
			$error = array(
				
				"name" => "Missing fields",
				"message" => "Requested fields cannot be empty for updation.",
			
			);
			
		}
 
		if(empty($error)){
			return response()->json(['data' => $data, 'status_code' => '200'],200);
		}else{
			return response()->json(['error'=> $error, 'status_code' => '404'],404 );
		}
 
		
      }

Above code showing notice when APP_DEBUG = TRUE in .env and app.php but status is 500.
Notice is : Undefined index 'name'.

When I set APP_DEBUG = FALSE then it is not showing notice but showing 500 error.

This should not happen when APP_DEBUG is FALSE. Why it is showing 500 for notice.

If I am not checking any variable then it's working fine like

    empty(trim($service_data['name'])

then it is not showing notice and also 500.

**Comment by laurencei** [comment]
This is expected. Laravel throws 500 errors for notices.
