### ISSUE TITLE
Turning default debug mode ON for framework in .env

### ISSUE THREAD

**Issue by shirkerohit** [laravel/framework#25937]
Having quick release cycle sometimes creates burden to further loose tight checks placed before project release.

Having debug set to true is something thats left from check unless an error is been reported (and that's too late) as there is no other way to know app current environment unless checked explicitly from artisan or from file.

Setting debug default turned ON will prevent any critical details been disclosed as it can be turned on explicitly when needed.

**Comment by laurencei** [comment]
It's not clear what you are asking. You should use `.env` to handle debug mode to off in production, and on in local/dev.

**Comment by shirkerohit** [comment]
Any thoughts on this?
