### ISSUE TITLE
having an error in laravel (app.php)

### ISSUE THREAD

**Issue by kasinico** [laravel/framework#25940]
- Laravel Version: #.#.#
- PHP Version:
- Database Driver & Version:

Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In app.php line 178:
                                                                               
  syntax error, unexpected ''App'' (T_CONSTANT_ENCAPSED_STRING), expecting ']  
  '                                                                            
                                                                               

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

**Comment by sisve** [comment]
How are we expected to help you when you won't tell us which Laravel version you are using?

The file and row number mention indicates that it's a problem in your installation, in `config/app.php` and the list of service providers, and not in the framework.

**Comment by laurencei** [comment]
As @sisve said - looks like a local syntax error in your code.

**Comment by sisve** [comment]
This issue is closed, and it's a issue in your code. At first glance it could be the space after Illuminate, there shouldn't be a space there. If that doesn't solve it, ask on Slack, Discord, Laracasts or other place meant for these type of questions.
