### ISSUE TITLE
Laravel session not setting after logging in from a session timeout

### ISSUE THREAD

**Issue by heyypatrick** [laravel/framework#25946]
We're currently developing with Laravel but we are having issues when a user was logged out because of session timeout. What we did for debugging was:

1. Set the session timeout to one minute.
2. Simply login. (everything was fine)
3. Waited for a minute before the session expires.
4. After the session expires, the system logged out.
5. Upon logging in, the session wasn't set and returns no value.

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
