### ISSUE TITLE
Laravel 5.7 , Argument 2 passed to Symfony\Component\HttpFoundation\RedirectResponse::__construct() must be of the type integer, array given, called in

### ISSUE THREAD

**Issue by codepandit** [laravel/framework#25943]
Laravel Version: 5.7
PHP Version: 7.1.9

Error
Argument 2 passed to Symfony\Component\HttpFoundation\RedirectResponse::__construct() must be of the type integer, array given, called in

After searching on internet, I found the solution that works for some people is to add a line in  App/Http/Middleware/TrustedProxies from an array, to a constant:

```protected $headers = Request::HEADER_X_FORWARDED_ALL;```

However it did not work for me.

**Comment by Dinesh-Iksula** [comment]
How did you solve this issue?

**Comment by madi9660-laurier** [comment]
@Dinesh-Iksula or @codepandit Did you solve this?

**Comment by Dinesh-Iksula** [comment]
> @Dinesh-Iksula or @codepandit Did you solve this?

My issue was solved after composer update after trying above-mentioned solution.
