### ISSUE TITLE
Every artisan command stuck.

### ISSUE THREAD

**Issue by evolot** [laravel/framework#25961]
- Laravel Version: 5.7
- PHP Version:7.2.8
- Database Driver & Version:mysql 5.7

### Description:
recently when I run php artisan commands, it just stuck without any output error or message.
I have two other  projects in my computer ,The 5.2 works fine,but 5.5 has the same error.
I guess it was because my environment, but 5.2 works ,I have no clue. 
### Methods I had tried
- I tried composer install, update, dump-autoload, still get nothing.
- I tried install a new 5.7, same problem.
- Then I clear composer cache, redownload , reinstall.Still noting.
- I tried put 
````
ini_set('display_errors',1);
error_reporting(-1);
````
in the artisan file,no error message.
- Tried put a `/` in `$kernel->terminate($input, $status);`
then I get the error
````
Parse error: syntax error, unexpected '->' (T_OBJECT_OPERATOR) in /Users/xxx/Documents/devworkspace/php/integrate/artisan on line 50

````
- I checked `storage/logs`,it was writeable,and no error logs.
- DB config is fine.The project works fine, except the artisan command,  just can't publish config files 

### Steps To Reproduce:

Install laravel  5.7,and it happens

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.

**Comment by putu-bhanuartha** [comment]
Hey @glitterlip , did you find any solution regarding this? been debugging for 2 days

**Comment by glitterlip** [comment]
> Hey @glitterlip , did you find any solution regarding this? been debugging for 2 days

cant remember how did i fix this ，but this might be phpstorm debug problem 
if you enable phpstorm debug and have the break at first line checked 

You opened project a and b ,you run your command in project a ,then for project b it can find correct ptah mapping,debug  will stuck
 At project b first line of code
