### ISSUE TITLE
assertExactJson - False-Positive running

### ISSUE THREAD

**Issue by sfatihk** [laravel/framework#25960]
- Laravel Version: 5.7.7
- PHP Version: 7.2.9
- Database Driver & Version: MySQL 5.7.19
- PHPUnit : 7.3.5

### Description:
I saw this error message when testing my City Model resource show route.
Note: Database freshing after test. And i'm using **sqlite** for testing but i tested this situation on Mysql; anything change.

---
**Error Message**
```
PHPUnit 7.3.5 by Sebastian Bergmann and contributors.

F                                                                   1 / 1 (100%)

Time: 2.46 seconds, Memory: 18.00MB

There was 1 failure:

1) Tests\Unit\app\Http\Controller\Region\CityControllerTest::test_show_func_can_return_true_data
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'{"data":{"name":"West Fannieland","updated_at":"2018-10-05 20:48:11","created_at":"2018-10-05 20:48:11","id":1},"status":"success"}'
+'{"data":{"created_at":"2018-10-05 20:48:11","id":1,"name":"West Fannieland","updated_at":"2018-10-05 20:48:11"},"status":"success"}'
```

---

**City Model**
```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    protected $fillable = ['id','name'];
    
}
```
---
**City Controller Show function**
```
public function show(City $city)
    {
        return response()
            ->json([
                "status"=>"success",
                "data"=>$city
            ],200);
    }
```
---
**Test Function**
```
public function test_show_func_can_return_true_data()
    {
        $city = factory(App\City::class)->create();

        $this->json('GET', '/api/cities/'.$city->id)
            ->assertExactJson([
                'status' => 'success',
                'data' => $city
                ]);

    }
```

---

**Beautified JSON response**
```
Expected
{"data":{
    "name":"West Fannieland",
    "updated_at":"2018-10-05 20:48:11",
    "created_at":"2018-10-05 20:48:11",
    "id":1
},"status":"success"}

Actual
{"data":{
    "created_at":"2018-10-05 20:48:11",
    "id":1,
    "name":"West Fannieland",
    "updated_at":"2018-10-05 20:48:11"
},"status":"success"}
```
Exactly same data but different sorting. Why it acting like this ?

**Comment by sfatihk** [comment]
it works when I static defined.
All about sorting. Is sorting necessary?
```
public function test_show_func_can_return_true_data()
    {
        $city = factory(App\City::class)->create([
            "name" => "istanbul",
            "created_at" => "2018-10-15 21:35:46",
            "updated_at" => "2018-10-15 21:35:46"
        ]);

        $this->json('GET', '/api/cities/'.$city->id)
            ->assertExactJson([
                'status' => 'success',
                'data' => [
                    "created_at" => "2018-10-15 21:35:46",
                    "id" => 1,
                    "name" => "istanbul",
                    "updated_at" => "2018-10-15 21:35:46"
                ]
            ]);

    }

```

**Comment by sfatihk** [comment]
https://laracasts.com/discuss/channels/testing/testing-json-response-in-laravel-54-testing-a-json-array

**Comment by svenluijten** [comment]
This is because [`assertExactJson` tries to match the given response to the expected array _exactly_](https://laravel.com/docs/5.7/http-tests#assert-exact-json). To test if the given JSON is present (with the attributes in any order), you can use [`assertJson`](https://laravel.com/docs/5.7/http-tests#assert-json).

**Comment by eric-addcream** [comment]
By definition, [a json object is unordered](http://www.rfc-editor.org/rfc/rfc7159.txt).

> An object is an unordered collection of zero or more name/value
   pairs, where a name is a string and a value is a string, number,
   boolean, null, object, or array.

Maybe the assertion should take that into account?

**Comment by dbudwin** [comment]
I opened an issue the other week related to this as well #25769

I'm also having issues with `assertExactJson` due to array sorting.  However, my issue manifests itself differently.

**Comment by HongjiangHuang** [comment]
I have repaired it and you can close the issues @sfatihk

**Comment by sfatihk** [comment]
Thank you for repair, my friend @HongjiangHuang . 
I tested json example in your test case, thats works fine.

But the problem still exists on my test case. 

I included your changes  #26315, didn't work, 
and then i tried on laravel last commit f83eca8d31339c0f4b7fe701223592e764cefb07, didn't work too .

Best way to test this situation seems like to still write manual json format & sorted values.

I simplified the problem. 
```php
public function test_show_func_can_return_true_city(){
  //city model( id, name )
  $city = App\City::create(['name'=>'Istanbul']);
  $city_from_db = App\City::find($city->id);

  $response = new TestResponse((new JsonResponse([$city])));

  $response->assertExactJson([$city_from_db]);
   //->assertJson([$city_from_db]);
  
  //$this->json('GET', '/api/cities/'.$city->id)->assertExactJson(['status' => 'success','data' => $city]);

}
```
<br>

output:
```php
There was 1 failure:

1) Tests\Unit\app\Http\Controller\Region\CityControllerTest::test_show_func_can_return_true_city
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'[{"id":1,"name":"Istanbul","created_at":"2018-11-13 10:36:30","updated_at":"2018-11-13 10:36:30"}]'
+'[{"created_at":"2018-11-13 10:36:30","id":1,"name":"Istanbul","updated_at":"2018-11-13 10:36:30"}]'

C:\laragon\www\gs-api\vendor\laravel\framework\src\Illuminate\Foundation\Testing\TestResponse.php:461
C:\laragon\www\gs-api\tests\Unit\app\Http\Controllers\Region\CityControllerTest.php:41

FAILURES!
Tests: 1, Assertions: 1, Failures: 1.
```

**Comment by driesvints** [comment]
I really don't see the problem here. I agree that the spec says it should be unordered by why don't you just use `assertJson` instead?

**Comment by HongjiangHuang** [comment]
@sfatihk You can try 
```
public function test_show_func_can_return_true_city(){
  //city model( id, name )
  $city = App\City::create(['name'=>'Istanbul']);
  $city_from_db = App\City::find($city->id);

  $response = new TestResponse((new JsonResponse([$city->toArray()])));

  $response->assertExactJson([$city_from_db->toArray()]);
}
```

**Comment by sfatihk** [comment]
> I really don't see the problem here. I agree that the spec says it should be unordered by why don't you just use `assertJson` instead?

assertjson was printing same error.

<br>

> @sfatihk You can try
> 
> ```
> public function test_show_func_can_return_true_city(){
>   //city model( id, name )
>   $city = App\City::create(['name'=>'Istanbul']);
>   $city_from_db = App\City::find($city->id);
> 
>   $response = new TestResponse((new JsonResponse([$city])));
> 
>   $response->assertExactJson([$city_from_db->toArray()]);
> }
> ```

Thanks again my friend, @HongjiangHuang 
 toArray() suggestion and your pr, fixed this issue.
