### ISSUE TITLE
Integers in migrations are confusing

### ISSUE THREAD

**Issue by CaptainHypertext** [laravel/framework#25979]
I just spent 30 minutes researching a bizarre error.  This was my migration:
```
Schema::create('categories', function (Blueprint $table) {
	$table->engine = 'InnoDB';
	
	$table->increments('id');
	$table->string('name');
	$table->smallInteger('year', 4)->nullable();
	$table->boolean('enabled')->default(0);
	$table->string('legacy_key', 3)->nullable();

	$table->index('year');
});
```
And this was my error:
```
Syntax error or access violation: 1075 Incorrect table definition; there can be only one auto column and it must be defined as a key
```
How did this happen?  I kept researching the `index` command and trying to see why it would make `year` a primary key.  Turns out, this was the problem:
```
$table->smallInteger('year', 4)->nullable();
```
You can't specify length with integers in migrations.  4 was being cast to a boolean for the `autoIncrement` parameter, which is confusing since many others have length as their second parameters (string, decimal, float, double, char).  The column definition ended up being `year smallint null auto_increment primary key`.

I know I've fallen for this at least 2 other times in the past few years.  Am I the only one who finds this behavior confusing?  Especially because [the documentation doesn't reference this parameter for integer type columns](https://laravel.com/docs/5.5/migrations#columns) and there is already an `autoIncrement` modifier.

Could auto increment be typehinted to boolean?  Or a length parameter added as the second parameter?    Or at least have it put in the documentation?  I welcome any feedback on this.

**Comment by browner12** [comment]
lengths on integer columns don't really do anything.

https://www.virendrachandak.com/techtalk/mysql-int11-what-does-it-means/

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not for ideas, suggestions etc. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. You are able to open a ticket at https://github.com/laravel/ideas

Alternatively you are able to open a PR using the Contributions guidelines: https://laravel.com/docs/5.7/contributions#which-branch

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
