### ISSUE TITLE
Create a factory with the data of an array

### ISSUE THREAD

**Issue by adrienpsn** [laravel/framework#25985]
- Laravel Version: 5.7.*
- PHP Version: 7.2.9
- Database Driver & Version: sqlite 7.2.8

### Description:
I want to fill my `categories` table via a `factory()`, here is my code:

```
$factory->define(App\Category::class, function (Faker $faker) {
    $categories = ['Hardware', 'Software', 'Planning', 'Tools'];
    foreach ($categories as $category) {
        return [
            'name' => $category
        ];
    }
});
```

### Problem:

When I call this `factory` in my code: `$categories = factory(Category::class)->create();` and I check the database, the `categories` table only contains Hardware...

This is normal because the first round of loop the `return` is executed so the `foreach` ends, but then how to make my table is fully filled?

### Steps To Reproduce:
`php artisan make:factory CategoryFactory -m Category`

**Comment by antonkomarev** [comment]
Factory should create only one instance at a time. You can use seeders to create many categories.
