### ISSUE TITLE
make:job only creating the directory if not there

### ISSUE THREAD

**Issue by jlsjonas** [laravel/framework#26000]
- Laravel Version: 5.7.7
- PHP Version: 7.1.20
- Database Driver & Version: N/A

### Description:
`php artisan make:job JobName` creates an empty Jobs folder if it didn't exist yet (on Windows at least)

### Steps To Reproduce:
1. Laravel app without Jobs folder (on Windows 10 pro?)
2. `php artisan make:job JobName`
3. note an empty `Jobs` folder

**Comment by laurencei** [comment]
I cant replicate. Works fine for me on Windows 10.

**Comment by jlsjonas** [comment]
Weird... I am using Cmder; maybe that made the difference? 🤔
