### ISSUE TITLE
touch() should always trigger a model's update events

### ISSUE THREAD

**Issue by tomlankhorst** [laravel/framework#26019]
- Laravel Version: 5.7.6
- PHP Version: 7.2.8

### Description:
Calling `->touch()` on a model should i.m.o. trigger the `saving`, `saved`, `updating` and `updated` events at all times. Currently, this _only_ happens when the corresponding timestamp-update _dirtifies_ the record. This behaviour is indeterministic. 

Also, in my option, the idiomatic meaning of touching would be in favour of triggering an update. 

In general, if a model is not dirty, the `updated` events are not invoked.

### Steps To Reproduce:
```php
$user = factory(User::class)->create();
$user->touch(); // does invoke `updated` and **most probabily** not `updating`, `updated`, `saving` events. 
usleep(1e6);
$user->touch(); // does invoke `updating`, `saved`, `saving` events
```

... or a test 
```php
public function testTouchEvents()
{
    Event::fake();

    $user = factory(User::class)->create();
    Event::assertNotDispatched("eloquent.updated: ".User::class);

    usleep(1e6);
    $user->touch(); // Will invoke the updated event
    Event::assertDispatchedTimes("eloquent.updated: ".User::class, 1);

    $user->touch(); // Will not invoke 
    Event::assertDispatchedTimes("eloquent.updated: ".User::class, 2);
}
```

p.s. execuse for misclicked issue closing.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not for ideas, suggestions etc. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. You are able to open a ticket at https://github.com/laravel/ideas

Alternatively you are able to open a PR using the Contributions guidelines: https://laravel.com/docs/5.7/contributions#which-branch

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
