### ISSUE TITLE
Catch ValidationException

### ISSUE THREAD

**Issue by adrienpsn** [laravel/framework#26013]
- Laravel Version: 5.7.*
- PHP Version: 7.2.9
- Database Driver & Version: sqlite 7.2.9

### Description:
In my unit test, I try to test my `CategoryRequest`. If I comment `$this->withoutExceptionHandling();`, I have no error in my console, but when I decomment the line, this thing is displayed in the console: `Illuminate\Validation\ValidationException: The given data was invalid.`. This is normal because in my `CategoryRequest` I have this :

```
return [
    'name' => 'required|string|unique:categories,name'
];
```

The category that I try to insert already exists so I have this error, but, how I can catch this error to pass my test ? Is there any `assert...` method to catch `ValidationException` ?

**Comment by fetzi** [comment]
You should use `expectException` to check if the exception was thrown. https://phpunit.de/manual/6.5/en/writing-tests-for-phpunit.html#writing-tests-for-phpunit.exceptions

**Comment by adrienpsn** [comment]
@fetzi Yes but, when I launch my test, I still have this error:

```
PHPUnit 7.2.7 by Sebastian Bergmann and contributors.

...E.....................                                         25 / 25 (100%)

Time: 712 ms, Memory: 30.00MB

There was 1 error:

1) Tests\Feature\CategoryTest::an_administrator_logs_in_and_tries_to_create_a_category_that_already_exists
Illuminate\Validation\ValidationException: The given data was invalid.

```

What method can I use to avoid receiving the exception ?

**Comment by fetzi** [comment]
@adrienpsn maybe you are using the wrong calling order? If just tested this in a project of mine and with the following code the exception does not appear in the console output:

```php
$this->expectException(ValidationException::class);

$formRequest->validated();
```

**Comment by adrienpsn** [comment]
@fetzi When I comment `$this->withoutExceptionHandling()`, I have this error:

```
PHPUnit 7.2.7 by Sebastian Bergmann and contributors.

...F.....................                                         25 / 25 (100%)

Time: 457 ms, Memory: 30.00MB

There was 1 failure:

1) Tests\Feature\CategoryTest::an_administrator_logs_in_and_tries_to_create_a_category_that_already_exists
Failed asserting that exception of type "Illuminate\Validation\ValidationException" is thrown.

FAILURES!
Tests: 25, Assertions: 123, Failures: 1.
```

But when I uncomment `$this->withoutExceptionHandling()`, my unit test pass... Is it normal ?

**Comment by fetzi** [comment]
Can you please share your test code? I think you are not doing a classic unit test.

**Comment by adrienpsn** [comment]
@fetzi Here is my code:

```
/** @test */
    public function an_administrator_logs_in_and_tries_to_create_a_category_that_already_exists()
    {
        $this->withoutExceptionHandling();

        $this->seed(CategoriesTableSeeder::class);

        $user_administrator = factory(User::class, 1)->create([
            'password' => bcrypt($password = 'Password'),
            'role_id' => 4
        ]);

        $this->get('/login')
            ->assertSuccessful()
            ->assertViewIs('authentication.login');

        $response = $this->post('/login', [
            'username' => $user_administrator[0]->username,
            'password' => $password
        ]);

        $response->assertRedirect('/tickets');

        $this->assertAuthenticatedAs($user_administrator[0]);

        $category = ['name' => 'Hardware'];

        $this->expectException(ValidationException::class);

        $this->post('/categories', $category)
            ->assertStatus(302)
            ->assertSessionHasErrors(['name' => 'The name has already been taken.']);

    }
```

**Comment by fetzi** [comment]
Ok in your case `expectException` doesn't make sense. You have to assert the error via status code (should be 422) and the session errors. 

`withoutExceptionHandling` simply disalbes the automatic response handling by Laravel, so you should remove this call and stick to the status code.

For more information: https://laracasts.com/series/whats-new-in-laravel-5-5/episodes/17

**Comment by adrienpsn** [comment]
@fetzi Ok I have remove `$this->withoutExceptionHandling();` and `$this->expectException(ValidationException::class);`

And for the status code this is `302` as I write !

```
PHPUnit 7.2.7 by Sebastian Bergmann and contributors.

.........................                                         25 / 25 (100%)

Time: 666 ms, Memory: 30.00MB

OK (25 tests, 122 assertions)
```

Thank you for your help !

**Comment by notflip** [comment]
I'm having the same issue, when $this->withoutExceptionHandling(); is in the method, I get the following error, it's working fine without the withoutExceptionHandling line. 

    Illuminate\Validation\ValidationException: The given data was invalid.
