### ISSUE TITLE
migrate:fresh doesn't drop views

### ISSUE THREAD

**Issue by MrMadClown** [laravel/framework#26026]
- Laravel Version: 5.6.38
- PHP Version: 7.1.17
- Database Driver & Version: MySql 5.7.22-0ubuntu0.16.04.1 (Ubuntu)

### Description:
php artisan migrate:fresh doesn't drop views

### Steps To Reproduce:
1. Create some Tables
2. Create some Views
3. Run php artisan migrate:fresh

**Comment by staudenmeir** [comment]
Use `php artisan migrate:fresh --drop-views`.
