### ISSUE TITLE
withoutWrapping() applied to single resource affects other resources

### ISSUE THREAD

**Issue by DarrenChowles** [laravel/framework#26021]
- Laravel Version: 5.5.43
- PHP Version: 7.1.10
- Database Driver & Version: MySQL 5.6.17

### Description:

When applying `withoutWrapping()` to a single resource via **AppServiceProvider**, it affects other resources too.

### Steps To Reproduce:

I have a **CountryCollection** that by default produces the following, which is correct:

```
{
    "data": [
        {
            "id": 1,
            "title": "Afghanistan",
            "code": "AF",
            "dialing": "35593"
        },
        {
            "id": 2,
            "title": "Albania",
            "code": "AL",
            "dialing": "355"
        },
```

I also have a **DeviceResource** that returns a single item only, as follows:

```
{
    "data": {
        "id": 6,
        "type": "Phone",
        "language": "en-GB",
```

I want the "data" wrapping removed for this one resource only.

In my **AppServiceProvider**, I add the following:

`DeviceResource::withoutWrapping();`

This has the desired effect on my **DeviceResource** output:

```
{
    "id": 6,
    "type": "Phone",
    "language": "en-GB",
```

But for some reason, affects my **CountryResource** by stripping the "data" wrapper that I would like to stay:

```
[
    {
        "id": 1,
        "title": "Afghanistan",
        "code": "AF",
        "dialing": "35593"
    },
    {
        "id": 2,
        "title": "Albania",
        "code": "AL",
        "dialing": "355"
    },
```

The only way I can get it to work as I need, is by removing the line in **AppServiceProvider**, and adding it in the code just before returning the resource:

```
DeviceResource::withoutWrapping();

return new DeviceResource($device);
```

Am I missing something here? Why does applying `withoutWrapping()` to **DeviceResource** in the **AppServiceProvider** also affect my other resources?

**Comment by staudenmeir** [comment]
It affects all resources because [`JsonResource::$data`](https://github.com/laravel/framework/blob/473ffd34889673a3730456672fdba281febf0737/src/Illuminate/Http/Resources/Json/JsonResource.php#L47) is a static property.

`DeviceResource::withoutWrapping();` has the same effect as `JsonResource::withoutWrapping();`.

**Comment by staudenmeir** [comment]
Does this answer your question? If you want to apply `withoutWrapping()` to a single resource, you have to put `Resource::withoutWrapping();` in the respective controller.

**Comment by DarrenChowles** [comment]
> Does this answer your question? If you want to apply `withoutWrapping()` to a single resource, you have to put `Resource::withoutWrapping();` in the respective controller.

It does, thank you.

**Comment by JuanDMeGon** [comment]
Just for the record: You can set `public static $wrap = null;` and the wrapper will disappear for that API resource.

**Comment by alicompu** [comment]
add the inside resource class these code:
`  public function __construct($resource)
    {
        self::withoutWrapping();

        parent::__construct($resource);
    }
`
I'm using laravel version 9.

**Comment by mdthanik** [comment]
> add the inside resource class this code: `public function __construct($resource) { self::withoutWrapping(); parent::__construct($resource); }` I'm using laravel version 9.

 this is the best answer

**Comment by judefdoo** [comment]
> add the inside resource class this code: `public function __construct($resource) { self::withoutWrapping(); parent::__construct($resource); }` I'm using laravel version 9.

This doesn't seems to work on Laravel 10

**Comment by antoniputra** [comment]
If somebody looking for solution for apply withoutWrapping at runtime / once.

put the `->resolve()`

we can do following below:

```php
return [
    // with data
    'project' => fn () => ProjectResource::make($project),
    
    // without data
    'project' => fn () => ProjectResource::make($project)->resolve(),
]
```
