### ISSUE TITLE
Empty Post Data when Testing

### ISSUE THREAD

**Issue by summea** [laravel/framework#26029]
- Laravel Version: 5.7.9
- PHP Version: 7.1.3
- Database Driver & Version: mysql 5.1.73

### Description:
This issue might be related to something that was evidently happening on the Lumen side [here](https://github.com/laravel/lumen-framework/issues/55) and might be related to [this issue](https://stackoverflow.com/q/42303659/1167750). When running tests using PHPUnit: when passing data using `post()` or `call()`, the resulting `$_POST` variable is consistently empty.

### Steps To Reproduce:
```
<?php
// Based on ExampleTest.php
namespace Tests\Feature;
class UserTest extends TestCase
{
    public function testExample()
    {
        // ref: https://stackoverflow.com/a/33469391/1167750
        $response = $this->call('POST', '/example/action', array('_token' => csrf_token(), 'param' => 'example'));
    }
}
```

When examining the `$_POST` variable in a related controller, when running `testExample()` using PHPUnit, there is no data appearing to be passed (e.g., where I would expect to find the '`param`' value). This happens also if I try to use `$this->post()` instead of `$this->call()`. I'm able to successfully use `$this->get()`, however.

I've tried this on Laravel 5.5, 5.6, and 5.7 with the same results. Is this a known issue? Is there a way to successfully pass data via `call()` or `post()` when running tests?

**Comment by staudenmeir** [comment]
I would say that this is the expected behavior. You shouldn't use PHP's superglobals (`$_GET`, `$_POST` etc.) in Laravel. Use the [`Request`](https://laravel.com/docs/5.7/controllers#dependency-injection-and-controllers) class instead.
