### ISSUE TITLE
Illuminate/Mail/Transport/MailgunTransport - how to work with another Mailgun region?

### ISSUE THREAD

**Issue by Tarasovych** [laravel/framework#26028]
Laravel version: 5.5

Is it possible to use another API url for Mailgun? [Here](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Mail/Transport/MailgunTransport.php#L164) we have "api.mailgun.net", and I want to work with EU Mailgun region. API url for EU region is ["api.eu.mailgun.net"](https://help.mailgun.com/hc/en-us/articles/360007512013-Can-I-migrate-my-domain-to-EU-). I can't override that by `.env` or another config now.

Is there some elegant way to override API url?

**Comment by staudenmeir** [comment]
This has been discussed in #24987 and added to Laravel 5.7.

For 5.5, take a look at this package: https://github.com/WildSideUK/Laravel-MailgunEu
