### ISSUE TITLE
Missing index method from ColumnDefinition doc block

### ISSUE THREAD

**Issue by dorin-niscu** [laravel/framework#26036]
- Laravel Version: 5.7
- PHP Version: 7.2

**@method ColumnDefinition index() Add index comment** is missing from the doc block so the IDE does not find the index method.

**Warning** _Method 'index' not found in Illuminate\Database\Schema\ColumnDefinition_

```
namespace Illuminate\Database\Schema;

use Illuminate\Support\Fluent;

/**
 * Class ColumnDefinition.
 * @method ColumnDefinition after(string $column) Place the column "after" another column (MySQL)
 * @method ColumnDefinition autoIncrement() Set INTEGER columns as auto-increment (primary key)
 * @method ColumnDefinition charset(string $charset) Specify a character set for the column (MySQL)
 * @method ColumnDefinition collation(string $collation) Specify a collation for the column (MySQL/SQL Server)
 * @method ColumnDefinition comment(string $comment) Add a comment to the column (MySQL)
 * @method ColumnDefinition default(string $value) Specify a "default" value for the column
 * @method ColumnDefinition first(string $column) Place the column "first" in the table (MySQL)
 * @method ColumnDefinition nullable($value = true) Allow NULL values to be inserted into the column
 * @method ColumnDefinition storedAs($expression) Create a stored generated column (MySQL)
 * @method ColumnDefinition unique() Add a unique index
 * @method ColumnDefinition unsigned() Set the INTEGER column as UNSIGNED (MySQL)
 * @method ColumnDefinition useCurrent() Set the TIMESTAMP column to use CURRENT_TIMESTAMP as default value
 * @method ColumnDefinition virtualAs(string $expression) Create a virtual generated column (MySQL)
 */
class ColumnDefinition extends Fluent
{
}
```

**Comment by mfn** [comment]
Seems like no-brainer except ... what arguments does it take? 😄 

I believe you can specify type of index but not sure if this applies to the column->fluent->index call too.

**Comment by dorin-niscu** [comment]
It does. I tried as a test.
The same as:  **@method ColumnDefinition unique() Add a unique index**

**Comment by ZacharyDuBois** [comment]
Literally just ran into this. Working on a PR for it now.

Example of the issue:
![screen shot 2018-10-12 at 21 11 04](https://user-images.githubusercontent.com/2458289/46899639-72541f80-ce63-11e8-953e-8ee8aa6ee8b6.png)


Only happens when you chain methods after a ColumnDefinition is returned. Doesn't happen when you just call `index()` as below:

```php
$table->index('email');
```

**Comment by dorin-niscu** [comment]
You are right. I did not add the migration example to show where the warning happens.
