### ISSUE TITLE
Resources + cache always returns 201

### ISSUE THREAD

**Issue by jffsx** [laravel/framework#26042]
- Laravel Version: 5.7.6
- PHP Version: 7.2.4
- Database Driver & Version: PostgreSQL 10.3
- Redis: 4.0

### Description:

Hi guys,

I made a cache implementation in my observers, which in all creation and modification of my models it adds the data in the cache with the key (name of the table + pk column this is returned in getCacheKey ())

```
    /**
     * Handle the "created" event.
     *
     * @param  \Illuminate\Database\Eloquent\Model  $model
     * @return void
     */
    public function created(Model $model)
    {
        $table = $model->getTable();

        Cache::tags($table)->flush();
        Cache::put($model->getCacheKey(), $model, $this->time);
    }
```

This works as expected.

The problem is that at the time of creating a new data the model is set to newly created (wasRecentlyCreated = true) and when it throws the data in the cache it stays true forever.

In my creation action it is returning 201 (OK should return 201), but in my data find action it returned 200 now it is returning 201 (because it takes from the cache)

I'm using resources to return the data in my action:

`return new AuthorResource($author);`

My questions are.

Is this an error? I say when I write the newly created data in the cache and when I search the data always returns status code 201

Or should I simply return the status code in my resource?

```
return (new AuthorResource($author))
            ->response()
            ->setStatusCode(200);
```

Thank you very much in advance.

Hugs

**Comment by staudenmeir** [comment]
I don't see what Laravel could do about this. The resource doesn't know that the model is coming from the cache.

I would suggest that you change value of `$wasRecentlyCreated` before you cache the model:

```php
$clone = (clone) $model;
$clone->wasRecentlyCreated = false;
Cache::put($clone->getCacheKey(), $clone, $this->time);
```

**Comment by jffsx** [comment]
@staudenmeir,

I did this and it makes total sense.

Many thanks for responding.
