### ISSUE TITLE
Empty Semi Colon when Generate Policy using parameter --model

### ISSUE THREAD

**Issue by azuharu** [laravel/framework#26047]
- Laravel Version: 5.7
- PHP Version: 7.2
- Database Driver & Version: MariaDB 10.2.13

### Description:

Hi, I'm new to Laravel, and I think this is not a big issue

Artisan generated empty semicolon in _use definition_;

```
namespace App\Policies;

use ;
use App\Account;
use Illuminate\Auth\Access\HandlesAuthorization;

class AccountPolicy
{

```
### Steps To Reproduce:

I running this comment

`php artisan make:policy AccountPolicy --model=Account`

and this is my model

```
class Account extends Model
{
...
   public $table = 'account';
...
}

```

**Comment by staudenmeir** [comment]
What does the `providers` section of your `config/auth.php` file look like?

**Comment by wilburpowery** [comment]
Check that your `config/auth.php` file isn't like this:

```php
'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => '', // should be App\User::class not ''
        ],
```

**Comment by azuharu** [comment]
> What does the `providers` section of your `config/auth.php` file look like?

This is my providers in config/auth.php

'providers' => [
        'user' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
        ],

**Comment by azuharu** [comment]
> Check that your `config/auth.php` file isn't like this:
> 
> ```
> 'providers' => [
>         'users' => [
>             'driver' => 'eloquent',
>             'model' => '', // should be App\User::class not ''
>         ],
> ```

No, I did not change anything in config/auth.php

**Comment by erdemkeren** [comment]
The stub file being used to generate your policy looks like this:

```php
<?php

namespace DummyNamespace;

use NamespacedDummyUserModel;
use NamespacedDummyModel;
use Illuminate\Auth\Access\HandlesAuthorization;
```

The replaceNamespace which being used to replace this dummies:

```php
    protected function replaceNamespace(&$stub, $name)
    {
        $stub = str_replace(
            ['DummyNamespace', 'DummyRootNamespace', 'NamespacedDummyUserModel'],
            [$this->getNamespace($name), $this->rootNamespace(), $this->userProviderModel()],
            $stub
        );

        return $this;
    }
```

And, finally, the last element of the replace array of the str_replace call is `$this->userProviderModel()`:

```
    protected function userProviderModel()
    {
        $guard = config('auth.defaults.guard');

        $provider = config("auth.guards.{$guard}.provider");

        return config("auth.providers.{$provider}.model");
    }
```

There should be something with the replace parameter in your project. This time, it is the user model of the default guard.

Can you please try to generate after calling `$ php artisan config:clear`?

**Comment by staudenmeir** [comment]
Can you reproduce this on a fresh Laravel installation?

**Comment by azuharu** [comment]
after calling `php artisan config:clear` the issue dissappear

Thank you, I will close this issue
