### ISSUE TITLE
Laravel 5.7.9 needs php 7.3 ? - Php AST Parse error

### ISSUE THREAD

**Issue by CyrilSiman** [laravel/framework#26054]
- Laravel Version: 5.7.9
- PHP Version:  7.1.22-1

### Description:

IT seems that the new release needs PHP 7.3 

This syntax : [$ability, $arguments] = $this->parseAbilityAndArguments($ability, $arguments);
From : Illuminate\Foundation\Auth\Access\AuthorizesRequests

generate an AST Parse Error on my side.

> Generating autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
>
> In ParseToAstFailure.php line 25:
>
>  AST failed to parse in located source (in /var/www/jobmaker/vendor/laravel/
>  framework/src/Illuminate/Foundation/Auth/Access/AuthorizesRequests.php)
>
>
>In ParserAbstract.php line 280:
>
>  Syntax error, unexpected '=' on line 22`

### Steps To Reproduce:

Update your composer.json file with Laravel 5.7.9
and update your dependencies : composer update / install

**Comment by moderndevelopment** [comment]
Thus is a php 7.1 feature which is required for Laravel 5.7.

See http://php.net/manual/en/migration71.new-features.php

**Comment by staudenmeir** [comment]
What result do you get when run `php -v` on the command line?

**Comment by CyrilSiman** [comment]
@moderndevelopment Yes, you right, I've just see it, but have you an idea why it doesn' work for me. I use php 7.1.22-1

>PHP 7.1.22-1+0 20181001133718.6+stretch 1.gbp113f3b (cli) (built: Oct  1 2018 13:37:19) ( NTS )
>Copyright (c) 1997-2018 The PHP Group
>Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
>    with Zend OPcache v7.1.22-1+0~20181001133718.6+stretch~1.gbp113f3b, Copyright (c) 1999-2018, by Zend Technologies

**Comment by CyrilSiman** [comment]
After a little test made directly with a little file and cli, as expected this syntax works perfectly with my php version (7.1.22). I have to study why it doesn't work with / inside my apache.  

Thanks all, I will close this issue and reopen it or create a new one if necessary after investigation.

**Comment by CyrilSiman** [comment]
For information : my bad. An old dependency....
