### ISSUE TITLE
Performance issue with WhereIn (and with eager loading)

### ISSUE THREAD

**Issue by Arkhas** [laravel/framework#26051]
- Laravel Version: 5.7.9
- PHP Version: 7.1.21
- Database Driver & Version: MySQL 5.5.5 -10.2.15-MariaDB

### Description:

Doing a whereIn with prepared query take much more time than doing a raw query

### Steps To Reproduce:

Create 10000 users

do : 

```
$user_ids = \App\User::pluck('id');
 \App\User::whereIn('id', $user_ids->sort())->get();
```

this request take 908ms to execute ,

But when doing : 

```
 \DB::table('users')->select('*')->whereRaw("id in ('1', '2', '3', '4', [...],'10000')")->get();
```

This on is taking only 68ms to execute.

I have made a demo project here : https://github.com/Arkhas/laravel-perf-wherein

(just run `php artisan migrate:refresh --seed` and visit the homepage (PHP Debug bar is enable))

it seems that it's an issue with prepared queries of php PDO : 

https://laracasts.com/discuss/channels/general-discussion/eloquent-is-so-slow?page=2
https://stackoverflow.com/questions/4350718/why-are-certain-types-of-prepared-queries-using-pdo-in-php-with-mysql-slow

when doing eager loading with eloquent, it seems that it use the first synthax and take a lot more time to process

the question here is : Is it required to do prepared queries for eloquent eager loading ? Or is it possible to eager load using the second synthax?

**Comment by sisve** [comment]
The two queries doesn't produce the same result, one returns Eloquent models, one doesn't.

You can use something like Blackfire to figure out where the time is spent. Is it really the actual database call, and not anything related like escaping values or hydrating models?

**Comment by Arkhas** [comment]
you can replace `\DB::table('users')` by `\App\User` and is still results in lower performances,

and it's just the db query which takes time  : 

<img width="256" alt="capture d ecran 2018-10-11 a 10 30 25" src="https://user-images.githubusercontent.com/5020806/46791114-ba2e5600-cd40-11e8-890c-97d29353d18c.png">
<img width="239" alt="capture d ecran 2018-10-11 a 10 31 08" src="https://user-images.githubusercontent.com/5020806/46791181-d7632480-cd40-11e8-905c-f51838bc9f57.png">

the only difference between the 2 queries is that one is using binding while the other is not

**Comment by Kyslik** [comment]
Are you benching this in one request? Doesn't database do some caching? Try changing the order of execution.

**Comment by Arkhas** [comment]
No it's on 2 different reload (commenting the one I don't need), and same kind of result append when I do this : 

```
$user_ids = \App\User::pluck('id');
```
```
$test_1  = \App\User::whereIn('id', $user_ids->sort())->get(); // 1.37s
```
<img width="460" alt="capture d ecran 2018-10-12 a 11 50 54" src="https://user-images.githubusercontent.com/5020806/46862462-2aa6a700-ce15-11e8-9c8a-28b2520e5adf.png">

```
$test_2 = \App\User::whereRaw("id in ('" . implode("','", $user_ids->toArray()) . "')")->get(); // 111.2ms
```
<img width="462" alt="capture d ecran 2018-10-12 a 11 51 52" src="https://user-images.githubusercontent.com/5020806/46862490-3abe8680-ce15-11e8-98c7-b687d4368f91.png">


And for exemple, doing this : 

```
public function user()
    {
        return $this->belongsTo(User::class, 'id', 'id');
    }
```

then 

```
$test_3 = \App\User::with('user')->get();
```
the "relation' query is exectuted in 1.44s
<img width="539" alt="capture d ecran 2018-10-12 a 11 50 03" src="https://user-images.githubusercontent.com/5020806/46862396-fd59f900-ce14-11e8-9a70-4e9da57a105d.png">


Is it something that can be fix with a better configuration of the mySQL server ?

I have a pretty standard valet installation on my local env, but the same thing in happening on the production server.

PS: I have reflect these tests in this file : 

https://github.com/Arkhas/laravel-perf-wherein/blob/master/routes/web.php

**Comment by vlakoff** [comment]
Maybe the bottleneck in not in the `whereIn`, but in the beforehand `pluck` and/or `sort`?

**Comment by Arkhas** [comment]
Same thing when the array is manually passed in the array

` $test_4 =   \App\User::whereIn('id',  ['1', '2', [...], '10000'])->get()`

<img width="463" alt="capture d ecran 2018-10-12 a 15 13 03" src="https://user-images.githubusercontent.com/5020806/46871324-58014e00-ce31-11e8-9403-9f889cf0ec65.png">

And even if it would take more time to process, it should not have any influence on the query execution time

**Comment by Arkhas** [comment]
@JayBizzle the difference in Sequel Pro is that you are not using a prepared query if you just copy and paste that query in Sequel PRO, it seems that it is not related to building the collection, but just the prepared query (you can try to see if there is any difference using this synthax in your own code : 

`$test_2 = \App\User::whereRaw("id in ('" . implode("','", $user_ids->toArray()) . "')")->get(); // 111.2ms`

@vlakoff , we are using the same workaround for some big queries, as it seems that managing 10000 relation in 2 queries is less efficient that managing 20 queries of 1000

**Comment by FabienLucini** [comment]
I have exactly the same problem !!
It seems to be in the prepared query, when you have to handle thousands of bindings.

**Comment by Kyslik** [comment]
@JayBizzle It seems that debugbar may take a while to load (render in the browser) but its actually pretty accurate:

Tinker
```php
$ids = \App\User::pluck('id');
$m = microtime(true); \App\User::whereIn('id', $ids)->get(); microtime(true)-$m;
>>> 0.89213609695435
```

And I get same results form the debugbar ±0.05.


---

The performance hit is in the `collect()` when all the results from `PDOStatement::fetchAll()` are transformed to collection https://github.com/laravel/framework/blob/5.7/src/Illuminate/Database/Query/Builder.php#L2012-L2017

**Comment by HadrienKulik** [comment]
I have experienced this issue and came to the same conclusion than @Arkhas: it seems that Eloquent is slowing down queries with large whereIn condition by easily a factor of x10 vs. doing them raw =/

**Comment by vlakoff** [comment]
Just to clarify, is the slowdown due to the SQL prepared statement, or to some processing by Laravel? (… or both?)

**Comment by staudenmeir** [comment]
@vlakoff The slowdown is caused by the prepared statement. You can reproduce the performance gap with a standalone `PDO` connection.

The implementation is simple, just not very elegant. Of course, we can only use it for integer keys.
An example for `HasMany` relationships: https://github.com/staudenmeir/framework/commit/3be00a20c11476ecfa6affd42f438619632f40b5

**Comment by staudenmeir** [comment]
@FabienLucini It's only secure when the keys are integers.

**Comment by mfn** [comment]
But I think the final observation of @FabienLucini is very valuable. My arguments:
- the *majority* of use cases uses integers
- eager loading of relations is void of user input

Seems like a candidate for performance optimization.

**Comment by Arkhas** [comment]
I confirm that using the method of @staudenmeir , the performance are dramatically improved : 

For this relation : 

` \App\User::with('user')->get();`

Original : 

<img width="536" alt="capture d ecran 2018-10-16 a 16 24 43" src="https://user-images.githubusercontent.com/5020806/47023458-03770f00-d160-11e8-9472-2c7bda727612.png">

using : 

```
/**
     * Set the constraints for an eager load of the relation.
     *
     * @param  array  $models
     * @return void
     */
    public function addEagerConstraints(array $models)
    {
        // We'll grab the primary key name of the related models since it could be set to
        // a non-standard name and not "id". We will then construct the constraint for
        // our eagerly loading query so it returns the proper models from execution.
        $key = $this->related->getTable().'.'.$this->ownerKey;

        $whereIn = in_array($this->parent->getKeyType(), ['int', 'integer']) ? 'whereInRaw' : 'whereIn';
        $this->query->$whereIn($key, $this->getEagerModelKeys($models));
}
```

In the `BelongsTo` class : 

<img width="536" alt="capture d ecran 2018-10-16 a 16 31 44" src="https://user-images.githubusercontent.com/5020806/47023942-0b837e80-d161-11e8-99fe-2be9421e3b1e.png">

@staudenmeir said it's not very elegant, but what would be a more elegant way of doing that ?

**Comment by staudenmeir** [comment]
Taylor doesn't normally respond to pings on GitHub (from what I have seen). You can try to ask him on [Discord](https://discordapp.com/invite/mPZNm7A).

**Comment by HDVinnie** [comment]
@Arkhas did you ever hear anything?

**Comment by Arkhas** [comment]
Nope, I will try to ping @themsaid here :p

**Comment by JayBizzle** [comment]
Just add a bit more info, this PHP bug is related I think https://bugs.php.net/bug.php?id=53458

**Comment by deleugpn** [comment]
The performance impact here is incredible. Given the high (common) use of integers as foreign keys, this would be a pretty big benefit for most codebase. I know the solution isn't marvellous, but I think it would be worth pursuing.

**Comment by JayBizzle** [comment]
Is it at all feasible to put any of above fixes into a package in the interim?

**Comment by JayBizzle** [comment]
@staudenmeir Yes, I agree this being in core should be the goal, was just hoping for a quick fix as we have lots of instances in our app where this problem is very apparent.

Perhaps we should create a PR to start getting feedback and discussing ideas. Might get more attention than in here.

**Comment by staudenmeir** [comment]
I'll submit a PR.

**Comment by HDVinnie** [comment]
Surprised @taylorotwell or any of the core dev team haven't commented on this yet. Looking forward to seeing the PR.

**Comment by staudenmeir** [comment]
#26434

**Comment by deleugpn** [comment]
It hasn't occurred to me that this is a Mysql only problem until I read the PR. It made me wonder if there's anything we can do at the query compilation time. What if we just stop using prepared statement for int values when compiling the bindings at the MySQL driver?

**Comment by staudenmeir** [comment]
@deleugpn The only way I see is adjusting `Builder::cleanBindings()`. But that wouldn't affect all queries and  isn't exactly elegant.
