### ISSUE TITLE
Redirect back gives an infinite loop

### ISSUE THREAD

**Issue by Whyounes** [laravel/framework#26055]
- Laravel Version: 5.5.*
- PHP Version: 7.1
- Database Driver & Version:

### Description:

When the back URL is the same URL that throws the error, we get a redirect loop.

### Steps To Reproduce:

- Create a `posts/create` route
- Inside the controller create a method to handle the request.
- `CreateFormRequest` class to validate the request, and set `authorize` methode to return `false`.
- Since this will throw an authorization exception, inside the `Handler` we `redirect()->back()->withErrors("Authorization problem")`
- Go to your browser and navigate to `posts/create`

**Comment by AegirLeet** [comment]
Well, yes, if visiting `/posts/create` returns a redirect to `/posts/create`, which returns another redirect and so on, you end up with an infinite loop. Or were you expecting some different behavior? What would that look like?

I suggest you either return a 403 (this is the default behavior) or return a redirect to some fixed URL that won't generate another redirect.

**Comment by Whyounes** [comment]
@AegirLeet The problem here, is that when this problem happens, it's hard to find why you have an infinite redirect loop. Since `redirect()->back()` is supposed to return back, we can use the `$fallback` parameter when the back URL is the same as the current one. This will prevent the infinite redirect loop.

**Comment by laurencei** [comment]
This has already been fixed in the latest `5.7` release: https://github.com/laravel/framework/pull/25739

**Comment by LadyDeathKZN** [comment]
I am sorry to say, but in my 5.7 as soon as it redirects it says:
ErrorException (E_ERROR)
Undefined variable: logos (View: ###\resources\views\admin\website\logos\index.blade.php)
After updating something

**Comment by laurencei** [comment]
@LadyDeathKZN - that is a local error for you. It clear says the `logo` variable is undefined.
