### ISSUE TITLE
Unexpected error in JWT authentication (Status code 500 instead of 401 for "token has expired error")

### ISSUE THREAD

**Issue by greenwhitecode** [laravel/framework#26069]
- Laravel Version: 5.6.*
- PHP Version: >=7.1.3
- Database Driver & Version: MySQL
-     "tymon/jwt-auth": "dev-develop",
-     "spatie/laravel-cors": "^1.3"

### Description:
I'm testing Postman with an expired token, and expect to receive a 401 not authorised error, but I keep receiving a 500 internal server error. I have this working on another laravel installation, but cant figure out why it's failing on this particular installation.

This is the error message I receive:

`Symfony\Component\Debug\Exception\FatalThrowableError: Argument 1 passed to Illuminate\Routing\Middleware\ThrottleRequests::addHeaders() must be an instance of Symfony\Component\HttpFoundation\Response, instance of Illuminate\View\View given, called in /var/www/html/mahadum_upgrade/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php on line 61 in file /var/www/html/mahadum_upgrade/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php on line 147`

### Steps To Reproduce:

1. Start a laravel application, do necessary configurations for jwt
2. Create 2 routes in routes/api.php
3. One for login attempt, to access JWT token, the other route will require the token
4. Add the jwt.auth middleware to the route to authenticate the token
5. Create a login attempt request in Postman to generate a token 
6. With the generated token, create another request by adding the token as a header to your request

### Note
I've downgraded to Laravel 5.5, but the problem persisted
Postman does not receive any errors if the token is valid, it gives you the controller's response
I am expecting a "Status: 400" error, and not the 500 internal server error.

I'll be glad if someone could point me in the right direction. Thanks in advance.

**Comment by sisve** [comment]
> Argument 1 passed to Illuminate\Routing\Middleware\ThrottleRequests::addHeaders() must be an instance of Symfony\Component\HttpFoundation\Response, instance of Illuminate\View\View given

It looks like you're rate-limiting an api call where a view is returned. Why would an api return a view?

**Comment by greenwhitecode** [comment]
It's leaving me confused. It even sends a 'laravel_session' cookie. I don't know if it's a version issue. Or what am I missing exactly?

**Comment by greenwhitecode** [comment]
Oh!

It was my error. I had initially adjusted the Exception Handler, to return a particular view as a response for a 401 status code.

I never planned on using API's for this app.

Thanks @sisve for stopping by. You kind of gave me a clue to where I screwed up.
