### ISSUE TITLE
Get authenticated user for query - maximum function nesting level of '512'

### ISSUE THREAD

**Issue by mnabialek** [laravel/framework#26113]
- Laravel Version: 5.5.44
- PHP Version: 7.2.7
- Database Driver & Version: MySQL 5.7.23

### Description:

In case of attempt to log query and get user that is authenticated 

> Maximum function nesting level of '512' reached, aborting!

error occurs.

### Steps To Reproduce:

1. `composer create-project laravel/laravel . 5.5`

2. Setup in `.env` database connection and run `php artisan migrate`

3. Fill in `web.php` file with following code:

```php
Route::get('/login', function() {
    auth()->login(factory(\App\User::class)->create());

    return auth()->user()->name;
});


Route::get('/user', function() {
    return  auth()->user()->name;
});

Route::get('/test', function () {
    \DB::listen(function ($query, $bindings = null, $time = null) {
        dump(auth()->user());
    });

    // get all users
    \App\User::all();

    return "test";
});
```

Assuming your host for this is `laravel.local` run in your browser:

- http://laravel.local/login
- http://laravel.local/user
- http://laravel.local/test

In last one you should get the error. If you comment out:

```php
    \DB::listen(function ($query, $bindings = null, $time = null) {
        dump(auth()->user());
    });
```

there won't be any error.

I am able to reproduce it each time with above steps (tested with different browsers). Exact same situation is when installed fresh Laravel 5.7 app (5.7.9)

**Comment by X-Coder264** [comment]
`auth()->user()` calls the `retrieveById` method on the `EloquentUserProvider` which makes a query to the database to get the user model. So doing that in the `DB::listen` callback means that you are going to be stuck in an infinite loop (query -> listen callback -> query -> listen callback...).

**Comment by laurencei** [comment]
Thanks @X-Coder264

**Comment by mnabialek** [comment]
@X-Coder264 Is there any way to prevent this? I mean to get user when already current user is known.

**Comment by X-Coder264** [comment]
@mnabialek Call `auth()->user()` before `DB::listen` so that the framework can fetch the user from the database. If you then call `auth()->user()` inside the `DB::listen` callback you won't get stuck in an infinite loop as the `Guard` won't try to fetch the user again from the database as it had fetched the user already.
