### ISSUE TITLE
[5.6] Queue issue

### ISSUE THREAD

**Issue by xyrintech** [laravel/framework#26131]
- Laravel Version: 5.6
- PHP Version: 7.2
- Database Driver & Version:
MySql 5.7

### Description:
There is an issue with Queues, please refer to following example.
Queue Driver: database
Let's say there are 3 queues running on the server and in total we have 10 processes say Q1 to Q10. First of all, when we dispatch the queues then multiple queues start working on same job. 

Now, let's say if the job is taking like 10 hours to complete then the jobs (in progress) disappears from jobs table but internally the job keeps on executing in the backend. I have almost every driver like beanstalkd, database, redis etc. Same issue everywhere. 

### Steps To Reproduce:
Laravel-worker file:

[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/laravel/artisan queue:work --queue=default --daemon --timeout=2
autostart=true
autorestart=true
user=root
numprocs=30
redirect_stderr=true
stdout_logfile=/var/www/html/laravel/worker.log

Try dispatching a queue and notice the attempts in jobs table. 

Then make this code to sleep for say like 2 hours and you will realise the job disappears from jobs table after some time.

**Comment by sisve** [comment]
> First of all, when we dispatch the queues then multiple queues start working on same job.

You would dispatch _jobs_, and there are multiple _workers_ handling the queue. However, two workers will not execute the same job at the same time, under normal circumstances.

> Try dispatching a queue and notice the attempts in jobs table.

You have a very low timeout value. The job will be killed after 2 seconds.

> Then make this code to sleep for say like 2 hours and you will realise the job disappears from jobs table after some time.

What would be a good value of "after some time"? Jobs that fail repeatedly will be removed from the queue and moved to the failed_jobs table.

**Comment by xyrintech** [comment]
Thanks for your quick response. 
Let's say a job takes like 24 hours then ideally what shall be the timeout time? based on your response, I will test it again. 

After some like say like 120 minutes. 

Please suggest if you need further detail from my end in order to understand my point. 
Thanks.

**Comment by sisve** [comment]
Theoretically; if a job were to execute for 24 hour, then you would need a timeout value of more than 24 hours, and a retry value of more than the timeout value.

The timeout value is meant for the worker executing the job to see "hey, this job has taken too long, it should be terminated". The retry value is meant for all the workers when looking in the database, seeing "hey, this job was started more than $retry ago, I'll assume it has failed and will retry it myself".

Having a php-script running for 24 hours sounds like a memory issue. Consider splitting it up into lots of smaller parts with separate jobs. That way you can have it execute faster by adding more queue workers, assuming some jobs can execute in parallell.

**Comment by laurencei** [comment]
I'll close this, as it doesnt seem to be a specific error with the Framework, but just some general questions.

**Comment by xyrintech** [comment]
Hi, thanks for your response. 
I tried everything for timeout like making it 24 hours but still issue is there. 
The job does not stay long in Jobs table but in the background job is executing.

**Comment by xyrintech** [comment]
I am happy to help to replicate this issue for you.
