### ISSUE TITLE
Model and Query builder on users doesn't return the id

### ISSUE THREAD

**Issue by saeedvaziry** [laravel/framework#26146]
- Laravel Version: 5.7.9
- PHP Version: 7.1.3
- Database Driver & Version: SQL Server

### Description:
The `create` method in `User` model returns `id:0`

Also `\DB::table('users')->insertGetId([...]);` returns `null`

This problem only happens on `users` table

**Comment by staudenmeir** [comment]
Please post your model and migration.

**Comment by staudenmeir** [comment]
I assume you can't produce this `CREATE TABLE` query with a native Laravel migration? Can you explain what the last part does?

**Comment by saeedvaziry** [comment]
It is hard to create tables with migration in `laravel` and `sqlsrv` and has so many exceptions...
The last part is about `Primary Key` options and it is same of the other tables.
I don't think the last part is involved in this problem.

**Comment by staudenmeir** [comment]
I suspect the last part to be the issue. `create()` and `insertGetId()` work with a default Laravel primary key:

```php
Schema::create('users', function(Blueprint $table) {
    $table->increments('id');
    [...]
});
```

**Comment by saeedvaziry** [comment]
So why it working with other tables and models?
The last part is similar with other tables

**Comment by sisve** [comment]
I speak T-SQL! ;) The short version is that neither of his table options would affect identity columns. They are similar to how mysql would tell us "ENGINE=InnoDB AUTO_INCREMENT=1337 ROW_FORMAT=DYNAMIC". A clustered index is just how the big boy databases states how the data in a table will be stored on disk. (You could have a non-clustered primary key, and a clustered index on user_id, and in that way store all rows related to the same user next to each other...)

I would debug this further in SQL Manager and manually insert a row into the users table, and see if `SELECT SCOPE_IDENTITY(), @@identity;` both gives you the last inserted identifier.

At first glance it sounds like the table isn't an identity column (similar to what mysql calls auto_increment), but your table structure says it is.

Perhaps it could be related to the bigint, that Laravel is unable to read that into an int, but that's just me guessing without verifying anything. Do your other tables, that work properly, also contain a bigint primary key?

**Comment by saeedvaziry** [comment]
I found the problem. But i don't know how to fix it.
This line in table creation `[id] [BIGINT] IDENTITY(1,1000000000) NOT NULL,` causes the problem.
It means `autoincrement` starts from `1000000000`.
When `autoincrement` starts from `1` there is no problem.
@staudenmeir

**Comment by saeedvaziry** [comment]
@staudenmeir
I found the problem. But i don't know how to fix it.
This line in table creation [id] [BIGINT] IDENTITY(1,1000000000) NOT NULL, causes the problem.
It means autoincrement starts from 1000000000.
When autoincrement starts from 1 there is no problem.

**Comment by saeedvaziry** [comment]
Problem solved...
I updated my pdo driver from this link

https://docs.microsoft.com/en-us/sql/connect/php/system-requirements-for-the-php-sql-driver?view=sql-server-2017
