### ISSUE TITLE
Auth::user() type-hinting

### ISSUE THREAD

**Issue by Tarasovych** [laravel/framework#26166]
Laravel version: 5.5.

When I have `new UserService(Auth::user());`, and inside `UserService`:
```php
    //UserService class

    public function __construct(User $user)
    {
        $this->user = $user;
    }
```
there is a type-hinting warning at `new UserService(Auth::user());`:

> Expected \App\Models\User, got \Illuminate\Contracts\Auth\Authenticatable

but `Auth::user()` returns `User` object exactly. Do we need to change `Auth::user()` PHPDoc?

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
