### ISSUE TITLE
orWhere function 

### ISSUE THREAD

**Issue by Uchiha-AhmedSaad** [laravel/framework#26165]
orwhere function in Eloquent\Builder class not accepted array like where function
orWhere(['sender_id'  => $selected_message->receiver_id,
 'receiver_id' 		=> Auth::User()->id,
 'owner_message_id' 	=> Auth::User()->id])

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by Uchiha-AhmedSaad** [comment]
i 'have already fix issue but my request is to be function like that in larvel 
orWhere(['sender_id' 	=> $selected_message->receiver_id,
 'receiver_id' 		=> Auth::User()->id,
'owner_message_id'  => Auth::User()->id]);
