### ISSUE TITLE
Carbon::serializeUsing Do not work at all

### ISSUE THREAD

**Issue by team-bfedition** [laravel/framework#26168]
- Laravel Version: 5.7.9
- PHP Version:7.2
- Database Driver & Version:MySQL 5.6

### Description:
I'm having all my datetime TimeStamps in this format Y-m-d i-h-o coming from Laravel when it stores the timestamps in database. i want to have them in ISO 8601 or c format.

### Steps To Reproduce:
make a user table migration  with `timestampsTz()` instead of `timestamps()`
got to AppServiceProvider and add : 
```
Carbon::serializeUsing(function ($carbon) {
            return $carbon->format('c');
        });
```

 When data is returned it want change format . any explanation from the Laravel Team or others about that.
Thanks

**Comment by team-bfedition** [comment]
now the only applicabel solution is to add this function in your model: 
` protected function serializeDate(\DateTimeInterface $date)
    {
        return $date->format('c');
    }`

**Comment by mfn** [comment]
In which cases do you expect `serializeUsing` to work?

It's only invoked with you _directly_ serialize a Carbon instance via json (so: this is only about JSON serialization).

Assuming your use case if you work with the models: as you found it on your own, `serializeDate` is invoked _before_ that.

So any data you might have ending up with from a model _has already been serialized_ from the model itself. Your final payload does not have a Carbon instance anymore, so the global serialized you may have specified will not be invoked this way.

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
