### ISSUE TITLE
ViewErrorBag bag empty if ValidationException is caught

### ISSUE THREAD

**Issue by tania-pets** [laravel/framework#26172]
- Laravel Version: 5.7.8
- PHP Version: 7.2.11

### Description:
From the docs about validate():

> If the validation rules pass, your code will keep executing normally; however, if validation fails, an exception will be thrown and the proper error response will automatically be sent back to the user.

It's not clearly stated if the errors will be sent to the view in case the exception is caught manually. I noticed different behavior between versions:

### Steps To Reproduce:

```
try {
    $this->validate([..invalid_request..])
}
} catch (\Exception $e) {
    return redirect()->back();
}
```

version 5.2.45
$errors are available in view. ViewErrorBag Bag has errors.

version 5.7.8
Bag is empty.

If i don't catch the exception, it will be automatically redirect back with $errors available in view in both versions.

**Comment by xuanquynh** [comment]
If you want to handle the validation exception manually, please use the "withErrors" method of RedirectResponse.

```php
return return redirect()->back()->withErrors($exception->errors(), $exception->errorBag);
```

**Comment by xuanquynh** [comment]
If we set an error bag of session, it will be shared with any views via [ShareErrorsFromSession](https://github.com/laravel/framework/blob/9f313ce9bb5ad49a06ae78d33fbdd1c92a0e21f6/src/Illuminate/View/Middleware/ShareErrorsFromSession.php). Otherwise, an empty error bag is initialized instead.

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
