### ISSUE TITLE
No way to set maxAttempts for queued Notifications

### ISSUE THREAD

**Issue by tiawleong** [laravel/framework#26175]
- Laravel Version: 5.6
- PHP Version: 7.2.2

### Description:

Illuminate/Notifications/SendQueuedNotifications does not have the $tries property, so maxAttempts is always null when Notifications are queued. Failed notifications are retried without limit.
Please consider implementing the $tries property for this Class like what done for SendQueuedMail in this old Pull Request : https://github.com/laravel/framework/pull/18103

**Comment by driesvints** [comment]
Think this is something we can add yeah. Feel free to send in a PR.

**Comment by driesvints** [comment]
To the 5.7 branch I mean.
