### ISSUE TITLE
clientExtension() method on Illuminate\Http\File class

### ISSUE THREAD

**Issue by ankurk91** [laravel/framework#26188]
- Laravel Version: 5.7.9
- PHP Version: 7.1.21
- Database Driver & Version: MySql 5.7 (does not matter)

### Description:
The method `clientExtension` is trying to call `guessClientExtension` method but `guessClientExtension` does not exists on this class.

### Steps To Reproduce:
```php
$file = new  \Illuminate\Http\File(public_path("file-that-exists.jpg"));
$file->extension(); // works
$file->clientExtension(); // throws exception
```

**Comment by erdemkeren** [comment]
The method `guessClientExtension` is a part of `Symfony\Component\HttpFoundation\File\UploadedFile`.  However, `Illuminate\Http\File` extends `Symfony\Component\HttpFoundation\File\File`
