### ISSUE TITLE
Auth::id() makes a call to database instead of just returning the id

### ISSUE THREAD

**Issue by Joakal** [laravel/framework#26184]
- Lumen Version: 5.5.*
- PHP Version: 7.*

### Description:
I was looking at solving some performance issues. As almost every controller requires the user, there's a database call. So, if I cached a user, I want to return that instead of a new call to database. 

#### Auth cache and fallback
I don't see any way to store user details in cache with database as fallback.

#### Getting Id from Auth for key look up
I understand that I can find the id via Auth::id(); to do cache look up. But I see from database logs that it actually makes a database call. I looked at the dependencies for Auth and it actually makes a call to Auth::user(), so a database call is made, regardless. Am I missing why or is it really required that Auth::id() must call Auth::user() first before returning the id?

Someone had asked about it indirectly, but I didn't see an answer
https://stackoverflow.com/questions/41470848/get-user-id-from-session-laravel-5-3-authentication

### Steps To Reproduce:
1. Whip up a laravel application with auth.
2. ??
3. DB::enableQueryLog();
4. var_dump(Auth::id());
5. dd(DB::getQueryLog()); <-- should be empty

**Comment by laurencei** [comment]
> Am I missing why or is it really required that Auth::id() must call Auth::user() first before returning the id?

Because there are *many* ways to Auth a user, and not all of them involve an ID. So it makes sense that the first call to anything `Auth::user()` would result in the user model being loaded.

It should be noted once the model is loaded once, no further calls are made.

If you have an option to improve this performance, you are welcome to submit a PR with the changes, but I dont see how you could get around it in a clean way...

**Comment by Joakal** [comment]
If a cache has the user record, why the need to make a call to the database? Security issues? I understand that once the model is loaded, no further calls is made. But a database call would be made on every request vs one database call with a cached model.

Would a PR for Auth::raw_id() which only shows the id before making a call be acceptable or a security risk? It would be clean in that the identifier is returned without making a call to Auth::user().

Regardless, I found an answer to my first attempt of read cache with db fallback by the clever use of providers and observers with this post: https://paulund.co.uk/laravel-cache-authuser
