### ISSUE TITLE
Eloquent: groupBy breaks SoftDeletes

### ISSUE THREAD

**Issue by marcus13371337** [laravel/framework#26198]
Consider the following:

> class Post extends Model {
>        use SoftDeletes;
>        public function author() {
>                  return $this->belongsTo(User::class);
>        }
> }

Then I would expect that this:
> $posts = Post::select('author_id')->where('category', 'cats')->groupBy('author_id');
> $users = User::whereIn('id', $posts)->get();

Would give me all users which have a post written in the category of cats which are not deleted. This is not the case, now I get all users which currently or previously had a post about cats. Using Laravel 5.5.

I know the recommended method is:
> User::whereHas('posts', function($q) { $q->where('category', 'cats'); })->get();

But I still would expect the first version to work.

**Comment by staudenmeir** [comment]
This will be fixed in Laravel 5.8.

**Comment by marcus13371337** [comment]
Great! Thanks!

**Comment by staudenmeir** [comment]
Please close the issue.
