### ISSUE TITLE
Within middleware, request variables only showing during dd()

### ISSUE THREAD

**Issue by ejrudy** [laravel/framework#26197]
- Laravel Version: 5.5.44
- PHP Version: 7.2.4-1
- Database Driver & Version: MySQL 5.7.22

### Description:
Very odd behavior with `$request` in middleware. 

I was having issues with a check for a certain `token` variable on a POST request that passes through my middleware. For purposes of context, this `token` is linked to specific estimates and invoices so that a customer can view these without needing to login (link is emailed with the token in the url, takes them through the process of accepting an estimate, paying an invoice w/o needing to authenticate).

During this specific POST request (all other requests that pass through this middleware have no issues, though it's worth noting that they are GET requests) the `$request` variables are not showing up at all....except when I output them with `dd()`. Below is the code block where I'm having the issues:
![screen shot 2018-10-19 at 4 02 52 pm](https://user-images.githubusercontent.com/3301438/47242938-636af100-d3be-11e8-8ddf-335a972f5cb9.png)

After placing the die and dump, this is what is outputted:
![screen shot 2018-10-19 at 4 01 33 pm](https://user-images.githubusercontent.com/3301438/47243161-379c3b00-d3bf-11e8-948f-38197c7c4460.png)

As you can see, the variables are all there. I'm honestly not sure where the disconnect is occurring. After I saw that output, I removed the die and dump and the code reacted as if `$token` was not set, and trigger the appropriate block, sending me to login with this error message:
![screen shot 2018-10-19 at 4 02 08 pm](https://user-images.githubusercontent.com/3301438/47243244-6a463380-d3bf-11e8-9db4-13eca5c54fa7.png)

Super strange.

### Steps To Reproduce:

My case seems oddly specific, but here:

1. Create middleware that reads from any request elements (query string, post body)
2. Try using both GET and POST requests

I appreciate any and all help with this...Laravel is the best!! Thanks.

**Comment by staudenmeir** [comment]
What do you get from `dd($token);`?

**Comment by ejrudy** [comment]
The value: "5ab0b8242668b538bfc684b6468352ad" is printed.

**Comment by staudenmeir** [comment]
Can you reproduce this issue on a fresh Laravel installation?

**Comment by ejrudy** [comment]
@staudenmeir figured it out. There was a redirect happening that I didn't detect before that was _not_ sending the appropriate variables. Thought I was going mad- apologies. Will close.
