### ISSUE TITLE
Laravel auth with MYSQL stored procedure

### ISSUE THREAD

**Issue by mavinoo** [laravel/framework#26199]
I'm developing a Laravel 5.7 application with MYSQL database.

My question is, how to authenticate a given user with 'username' and 'password'.

The MYSQL stored procedure accepts these two parameters, and returns 'userLevel' and 'projectID' if the user exists, and 'false' otherwise.

The database can not be modified by any means, so I have to tweak the auth process in Laravel.

**Note:** The 'userLevel' and 'projectID' should be included in `auth()->user()` if auth succeeded. How I'm I supposed to do this?

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
