### ISSUE TITLE
notifications::email has placeholder mismatch for "actionURL" when installing through composer

### ISSUE THREAD

**Issue by vedmant** [laravel/framework#26203]
- Laravel Version: 5.7.9
- PHP Version: 7.2.7
- Database Driver & Version: NA

### Description:
I have a problem particularly with reset emails, bottom link :actionURL doesn't get replaced. The issue is a typo in template, where placeholder is ":actionURL" but replacers passed to @lang is 'actionUrl' => $actionUrl . When I checked github illuminate/notifications package Notifications/resources/views/email.blade.php has correct matching replacers, but when I install it though composer it has that problem, here is zipball of the framework package: 
https://api.github.com/repos/laravel/framework/zipball/172f69f86bb86e107fb9fafff293b4b01291cf05
if you download and unzip it you'll find placeholder - replacer mismatch in src/Illuminate/Notifications/resources/views/email.blade.php template.

Here is my lock file:
```
            "name": "laravel/framework",
            "version": "v5.7.9",
            "source": {
                "type": "git",
                "url": "https://github.com/laravel/framework.git",
                "reference": "172f69f86bb86e107fb9fafff293b4b01291cf05"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/laravel/framework/zipball/172f69f86bb86e107fb9fafff293b4b01291cf05",
                "reference": "172f69f86bb86e107fb9fafff293b4b01291cf05",
                "shasum": ""
            },
```

### Steps To Reproduce:
Try to install latest Laravel 5.7.9 and reset password to see :actionURL is not replaced in email.

**Comment by laurencei** [comment]
This has been fixed on the latest `5.7` branch - but its not "tagged" yet. When 5.7.10 comes out it will be resolved.

https://github.com/laravel/framework/blob/734d7584e4f1cdf306fb611fa6266113f962dc56/src/Illuminate/Notifications/resources/views/email.blade.php#L57

**Comment by vedmant** [comment]
Thanks, when to expect new version?

**Comment by Dmarthaller** [comment]
Thank you as I ran into the same issue as well.
