### ISSUE TITLE
Modal::find($instance) returning multiple models when passed model instance

### ISSUE THREAD

**Issue by jackcruden** [laravel/framework#26210]
- Laravel Version: 5.7.*
- PHP Version: 7.2.10
- Database Driver & Version: MySQL 5.7.17

### Description:
This is probably relevant to any Eloquent model, just using User as an example.
When using `App\User::find($user);` where `$user` is a User instance not an ID (or primary key) the User object is treated as an array of IDs (/primary keys) and it's possible for multiple models to be returned given the right data.

I understand that the data on Emma (in example below) is being treated as IDs, and the `organisation_id` of `1` is picking up Jack. And I know this isn't how `::find()` is intended to be used but shouldn't there be protections in place to stop accidentally passing an instance to the `Model::find()` method?

### Steps To Reproduce:
Add the following to the users table:

id | name | email | organisation_id
--- | --- | --- | ---
1 | jack | jack | 1
2 | emma | emma | 1

Run the following:
```
// Setup
$emma = App\User::find(2);

// To recreate bug
return App\User::find($emma);

// Result
[Jack instance, Emma instance]

// Expected result
// Exception or Emma instance?
```

**Comment by jackcruden** [comment]
No real use case. Just thought that there should maybe be some protections here against. Feel free to close if this isn't something that falls within Laravel's scope.

**Comment by xuanquynh** [comment]
I know how it behaves and how to change the behavior but this is unnecessary for me. Anyway, Laravel scope is anything that is decided by Mr.Otwell - Laravel author. Let's listen to the other ideas.

**Comment by driesvints** [comment]
Heya! This is as intended. Check out the example @d1am0nd posted :)
