### ISSUE TITLE
Cache locks are unsafe

### ISSUE THREAD

**Issue by yuloh** [laravel/framework#26213]
- Laravel Version: 5.7.9
- PHP Version: 7.1.19
- Database Driver & Version: N/A

### Description:

When using the cache locks its possible to delete another client's lock.  If this happens the lock is free and can be acquired again, even though it has not expired yet.  It is easy for this to happen if a client takes longer than it expects to finish a task and overruns the expiration, i.e.

- Client A acquires lock `foo` with a 10 second expiration
- Client A begins performing a task
- Client A takes longer than expected and the lock is automatically released by the expiration
- Client B acquires the lock
- Client A finishes it's task and attempts to release the lock, **deleting client B's lock**
- Client C is now able to acquire the lock

This issue is especially difficult to diagnose because the lock will not throw an exception if the timeout has been exceeded when `release` is called.

We can't do anything about client A exceeding it's expiration time but we can prevent client A from deleting client B's lock.  The redis docs [recommend setting a random token](https://redis.io/commands/set#patterns) instead of the value `1`.  You can then confirm the token is what you set and only delete the key if the token matches.

The reproduction steps below use Redis but this issue seems to exist with both the Redis and Memcached locks.

### Steps To Reproduce:

I've added a failing test case here: https://github.com/yuloh/framework/commit/a0acbfd60cb276d9c99091a7a56432b815993a92.  In the test `$firstLock->release();` should do nothing, as the lock has already been released.  Instead it releases `$secondLock`.

**Comment by driesvints** [comment]
Heya @yuloh. This should indeed be addressed I believe. Would be great if anyone could assist with this.

**Comment by GrahamCampbell** [comment]
Discussion can continue at #26645. :)

**Comment by driesvints** [comment]
@GrahamCampbell please leave this open until the fix has been implemented.

**Comment by driesvints** [comment]
The PR was merged and will be released once 5.8 is out.
