### ISSUE TITLE
session()->flush();  vs \Auth::user()

### ISSUE THREAD

**Issue by Eugene-Melbourne** [laravel/framework#26211]
- Laravel Version: 5.7.9
- PHP Version: 7.1
- Database Driver & Version: Mysql

### Description:

when I do 
`session()->flush(); `
It also logging out a user, but 
if you check `Auth::user()`
you will see authentication passes.

It makes a strange situation when you have logged out, but phpunit cannot assert it.

**Comment by federicotorrisi** [comment]
you mean you're loggin an user out with just ```session()->flush```?

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by Eugene-Melbourne** [comment]
@federicotorrisi , @driesvints , thank you for your attention. BUT It is not a question it is a bug report. I don't want to log out a user, even less I what to log out a user in a way that `Auth::user()` - wouldn't  know about it.  I want to clear all data that I put to session and that is it. My suggestion would be to store `sessio()` variables in separate array element to not overlap with Authentication. Or maybe make Authentication check if user was cleared from session. My bug report is about two systems that overlap/clash and break each other.
