### ISSUE TITLE
Move validation errors from general errors

### ISSUE THREAD

**Issue by ionesculiviucristian** [laravel/framework#26223]
How can I "move" the errors generated by FormRequest to a new MessageBag that are not in the default 'errors' key?
I want to be able to distinguish the errors coming from validation and those from the controller for example.
$errors->any() should point to any error that is not a validation one
$validationErrors->any() (for example) should point only to validation errors.

Returning withErrors() from a controller and having validation from FromRequest makes them "identical".
I'd like to avoid replacing withErrors() with something like withNonValidationErrors() etc.

**Comment by ionesculiviucristian** [comment]
Found a solution:
```php
<?php
namespace App\Http\Requests;

use \Illuminate\Foundation\Http\FormRequest;

class StoreLocation extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $this->errorBag = 'validation';

        return [
            'name' => ['required' => 'required', 'unique' => 'unique:locations']
        ];
    }
}
```
with
```php
@if($errors->count() || ($errors->hasBag('validation') && $errors->getBag('validation')->count()))
  @include('partials.alerts.error', ['class' => 'mt-4'])
@endif
```

**Comment by wilburpowery** [comment]
As this isn't a "Framework issue", maybe you should consider posting it on a forum like https://laracasts.com/discuss and you're more certain to get an answer there.

**Comment by staudenmeir** [comment]
Please close the issue.
