### ISSUE TITLE
Laravel + axios - CORS request fails on text/html response

### ISSUE THREAD

**Issue by Tarasovych** [laravel/framework#26220]
**What I have**:

1) Two apps: client (Vue exactly) at `https://domain.local` and API (Laravel 5.7) at `https://api.domain.local`.

2) `axios` for API calls on client:

    `axios.post( //url, { //data })`
3) API side:

```
    //routes/api.php
    Route::resource('users', 'UserController');

    //app/Http/Kernel.php
    'api' => [
        'throttle:60,1',
        'bindings',
        HandleCors::class, //<--https://github.com/barryvdh/laravel-cors
    ],

    //config/cors.php
    'supportsCredentials' => true,
    'allowedOrigins' => ['*'],
    'allowedHeaders' => ['*'],
    'allowedMethods' => ['*'],
    'exposedHeaders' => [],
    'maxAge' => 0,

    //UserController@store - method I'm testing
    public function store(Request $request)
    {
        dd($request);
    }
```
**My problem**: 
 
`dd($request)` returns `text/html` MIME response. And my POST request from client fails.
  
There are two requests from client: "OPTIONS" and "POST". Both are with 200 response by the way.
"OPTIONS" Response Headers:
```
HTTP/1.0 200 OK
    Cache-Control: no-cache, private
    Access-Control-Allow-Credentials: true
    Access-Control-Allow-Origin: https://domain.local:8080
    Access-Control-Allow-Methods: POST
    Access-Control-Allow-Headers: CONTENT-TYPE
```

"OPTIONS" Request Headers:
```
    Accept: */*
    Access-Control-Request-Headers: content-type
    Access-Control-Request-Method: POST
```

"POST" Response Headers:

   ` Content-Type: text/html; charset=UTF-8`

"POST" Request Headers:

```
    Accept: application/json, text/plain, */*
    Content-Type: application/json;charset=UTF-8
```
Browser error:
> Cross-Origin Read Blocking (CORB) blocked cross-origin response https://api.domain.local/users with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.

When I remove `dd(...)` and return appropriate response, everything is ok, but I want to get that `dd(...)` for now.

**What I've tried** (nothing helped yet):

1) send `withCredentials` flag

```
    axios.post(//url, {
              withCredentials: true,
              //data
            })
```

2) send `XMLHttpRequest` header

    `axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest'`

3) changing `cors` config:

    `'allowedHeaders' => ['Access-Control-Allow-Origin'],`
or  

    `'allowedOrigins' => ['https://domain.local:8080'],`

caused "Header not allowed" 403 response.

Any request works fine while using Insomnia or Postman.

Thanks in advance!

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
