### ISSUE TITLE
Vue 2 on laravel 5.7 didnt work in production server

### ISSUE THREAD

**Issue by yorihutagalung** [laravel/framework#26240]
- laravel 5.7.*
- vue ^2.5.7

Hello all.
recently i tried to deploy my Laravel app with vue preset in production server (ubuntu with apache).
i ran npm run production and everything worked perfectly on my local server (xampp). 
next,  i cloned it to live server (using git) , and do some composer installation steps. 

when all installation completed,i open my web and found that Vue wasn't working on my production server. (i include some vue components to my homepage (in laravel blade template) and it doesnt show up).

i tried to find any solution but i got stucked. sorry for my bad english i hope you all understand.
please help. thankyou

**Comment by browner12** [comment]
Welcome to Laravel! We are glad to have you as part of the community.

Unfortunately GitHub is not an appropriate platform for general application issues. This is only for issues/bugs with the framework code itself.

Please close your issue, and instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

Laravel Slack (https://larachat.co/)
Laravel.io Forum (https://laravel.io/forum)
Laracasts Forum (https://laracasts.com/discuss)
StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks!
