### ISSUE TITLE
Quick login logut will result in file ErrorException 

### ISSUE THREAD

**Issue by hmzlam** [laravel/framework#26253]
- Laravel Version: All
- PHP Version: All
- Database Driver & Version:All

### Description:
Quick login logut will result in file ErrorException  

file_put_contents(storage\framework/sessions/umoLEC5WUjfAEgOUXqG4SL7jws7qqTSERF5TKfEi): failed to open stream: Resource temporarily unavailable

### Steps To Reproduce:
repeated quick manual login logout

**Comment by laurencei** [comment]
Use a different session driver, such as Redis or memcachce.

Its a limitation of the technology, not Laravel...
