### ISSUE TITLE
Different Pusher keys for production and development in compiled app.js

### ISSUE THREAD

**Issue by chimit** [laravel/framework#26263]
- Laravel Version: 5.7
- PHP Version: 7.2
- Database Driver & Version: MySQL 5.7

### Description:
I'm using different Pusher apps for development, staging, and production as Pusher recommends. When I run Laravel Mix on my local machine my development Pusher app key is put into the compiled `public/js/app.js` and later goes to the VCS and appears on the production environment.

So to get a production Pusher app key on my production server I have to compile assets on a production environment, but it overrides the `app.js` in the VCS.

Should we compile assets on every environment separately and add `public/js/app.js` into `.gitignore` or are there any better ways to address this problem?

**Comment by laurencei** [comment]
> Should we compile assets on every environment separately and add public/js/app.js into .gitignore

Generally - yes. That way you can run unminified code in Dev, and compress and version it for Production.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.
