### ISSUE TITLE
sortBy on collections is returning unsorted array

### ISSUE THREAD

**Issue by jeffkarney** [laravel/framework#26276]
- illuminate/container version: v5.7.11
- PHP Version: 7.2.11

Standalone Eloquent. Not in a Laravel app. Not sure that would make a difference here.

### Description:
When trying to sort a collection created from an Eloquent model, it does not sort. 

More specifically, the sortBy function is called on the collection. The $results array is created with the values to be sorted on. It is then sorted with asort().

The sorted array no looks something like...
`$results = [`
`    5 => 'A',`
`    1 => 'B',`
`    3 => 'C',`
`    4 => 'D',`
`    2 => 'E',`
`    0 => 'F',`
`]`

Next the rebuild of the sorted collection happens...
`foreach (array_keys($results) as $key) {`
`    $results[] = $this->items[$key];`
`}`
`return new static($results);`

After the results are returned they look like this... (the original input)

`$results = [`
`    0 => 'F',`
`    1 => 'B',`
`    2 => 'E',`
`    3 => 'C',`
`    4 => 'D',`
`    5 => 'A',`
`]`

The simplest fix I have found so far is changing the return statement to... 

`
return new static(array_values($results));
`

I'd be happy to submit a pull request if this turns out to not be a local issue.

### Steps To Reproduce:
$model = \App\Models\User::where('isDeleted', 0);
$collection = $model->get();
$collection = $collection->sortBy('full_name');
echo $collection->toJson();

**Comment by staudenmeir** [comment]
Please post the JSON result.

**Comment by jeffkarney** [comment]
After writing for 20 mins and getting a correctly formatted JSON output. It seems you might be on to something. The JSON it ordered correctly. The indexes are out of order as expected, but seem to get reordered when read by just about any JSON interpreter.

This doesn't seem to strictly be toJson() function. It almost seem like observing the array changes it as xdebug only was able to show it was sorted on a past var, but never outputted it as sorted.

I 'think' this would be considered expected behavior (the behavior we aren't expecting) Meaning I believe the behavior needs to change in Laravel. But that is just an opinion based on little knowledge of the inner workings of PHP arrays and JSON parsing.

Assuming associative arrays are never passed into the sortBy() function. Adding array_values() on the $results before output will solve the issue with no backwards incompatibilities. However I don't know if that is the case and also don't know about performance issues it will introduce. Maybe adding array_values() to the toJson() and related functions makes more sense than in the sortBy() ? 

```
{
  "1": {
	"full_name": "Ada***, Jeff & L***"
  },
  "2": {
	"full_name": "Chu***, Jeff & ***her"
  },
  "3": {
	"full_name": "For***, Jeff"
  },
  "5": {
	"full_name": "GAN*** LLC-1"
  },
  "4": {
	"full_name": "Gan*** LLC"
  },
  "6": {
	"full_name": "JEFFREY  WH***"
  },
  "0": {
	"full_name": "Karney, Jeff"
  },
  "10": {
	"full_name": "Karney, Jeff"
  },
  "11": {
	"full_name": "Karney1, Jeff1"
  },
  "8": {
	"full_name": "MO***, JEFFREY"
  },
  "7": {
	"full_name": "Mo***, Jeff"
  },
  "9": {
	"full_name": "Str***, Jeffrey & ***h"
  }
}
```

**Comment by staudenmeir** [comment]
The issue here is the undefined order of keys in JSON objects. From http://json.org:

> An object is an unordered set of name/value pairs.

We can't use `array_values()` by default because, as you mentioned, this would break associative arrays.

The "solution" here is that you reset the keys yourself:

```php
$collection->values()->toJson();
```

**Comment by jeffkarney** [comment]
That makes it work as desired. Thanks for your help!

Hard to say if this could be considered a bug or not, but at least now the problem is searchable for others ;)

**Comment by iffifan** [comment]
When I want an associative array from the collection it does not provide keys if I use values method. So the problem with collection sorting and converting to array is there.
