### ISSUE TITLE
Generators commands are not tested

### ISSUE THREAD

**Issue by Arcesilas** [laravel/framework#26272]
Hi!

Hope I'm posting at the right place. If not, please let me know.

I've noticed some generators commands are bogus (some `alreadyExists` methods are not working correctly), some options with optional values are not handled properly (`artisan make:mail --markdown` for example) and some stubs (`foundation/console/stubs/event-handler*.stub`) seem to be unused.
I have found no tests for these commands. Is there a valid reason to not test generators commands ?

*Note: I can provide corrections for these commands (I'll make a PR when I'm done digging them) and I can try to write tests for them if they don't already exist **and** if it's relevant.*

**Comment by laurencei** [comment]
Hi @Arcesilas,

If you have found some commands that are not working correctly, please feel free to submit a PR with the fixes.

If you include some tests, that is a bonus and would be greatly appreciated by everyone!

**Comment by Arcesilas** [comment]
Thanks for your answer, but... it does not answer to my main question:
> Is there a valid reason to not test generators commands ?

You answer to the note where I said I would submit a PR and write tests...

**Comment by laurencei** [comment]
There's no reason not to.

I would suggest starting with a small PR of 1-2 tests and submit. Taylor will review and decide if he wants them or not...
