### ISSUE TITLE
Sync withTimestamps only works during creation and not on update

### ISSUE THREAD

**Issue by sgimmai** [laravel/framework#26284]
- Laravel Version: 5.7

### Description:
Address.php
``` 
class Address extends Model
{
    public function business(){
        return $this->belongsToMany('App\Business', 'business_address','address_id','business_id');
    }

    public function user(){
        return $this->belongsToMany('App\User', 'user_address','address_id','user_id');
    }
}
```
Business.php
```
class Business extends Model
{
    public function address(){
        return $this->belongsToMany('App\Address', 'business_address','business_id','address_id')
            ->withTimestamps();
    }
}
```
User.php
```
class User extends Model
{
    public function address(){
        return $this->belongsToMany('App\Address', 'user_address','user_id','address_id')
            ->withPivot('type')->withTimestamps();
    }
}
```
When using updating my `user()->address()`, the timestamps work correctly.
`Auth::user()->address()->syncWithoutDetaching([$address->id => ['type' => 'home']]);`
However, when updating my `business()->address()`, only the creation populated the timestamps and no longer changes during updated.
`$business->address()->sync($address->id);`

Not sure if what I am doing wrong here.

**Comment by staudenmeir** [comment]
Please provide detailed steps to reproduce this. What is the content of the pivot table before and after calling `sync()`?

**Comment by sgimmai** [comment]
@staudenmeir I have this pivot table [business_address] with timestamps
![image](https://user-images.githubusercontent.com/23491022/47689636-9ebeb880-dc25-11e8-80f9-3a91f67d96b5.png)

When creating and syncing the Address to the Business the timestamps work as expected.
Only when updating the Address and syncing to Business the `updated_at` does not update.

Here is my function for the Address Sync:
```
public function syncAddress(Request $request, Business $business){

        $address = $business->address()->first() ?? new Address();
        $address->address1 = $request->{'address.address1'};
        $address->barangay_district = $request->{'address.barangay_district'};
        $address->city_municipality = $request->{'address.city_municipality'};
        $address->zipcode = $request->{'address.zipcode'};
        $address->country = $request->{'address.country'};
        $address->save();
        
        $business->address()->sync($address->id);
        
        return $business;
    }
```

**Comment by staudenmeir** [comment]
The `updated_at` timestamp doesn't change because you aren't updating anything. You can only update a pivot entry if you specify attributes (`sync([$address->id => ['type' => 'home']])`).

**Comment by sgimmai** [comment]
How can `withTimestamps()` be used if I don't maintain additional attributes - other than the foreign keys and timestamps - in my pivot table?

**Comment by staudenmeir** [comment]
You can specify the timestamp yourself:

```php
$business->address()->sync([$address->id => ['updated_at' => Carbon::now()]]);
```
