### ISSUE TITLE
Controller not displaying image form s3 bucket

### ISSUE THREAD

**Issue by redjoni** [laravel/framework#26290]
- Laravel Version: 5.6
- PHP Version: 7.2.10

### Description:
I want to display an image from my amazon s3 bucket directly in the users browser from my controller. For this purpose I'm using [Laravel File Storage](https://laravel.com/docs/5.7/filesystem) . From the documentation it seems like my code should work but in my browser it displays nothing. It also doesn't show any errors, only a black screen in the browser.

#### Here is my controller 

     class S3ImageController extends Controller
    {
        public function imageUrl($make, $model, $year) {

             $stock = DB::table('stock_car_images')
                    ->where(compact('make', 'model', 'year'))
                    ->first();

             if (!empty($stock) && Storage::disk('s3')->url($stock->image)) {
                return response(Storage::disk('s3')->get($stock->image))->header('Content-Type', 
               'image/jpeg');
              } 
              else {
                   return 'No Image';
           }
       }
    }

Am i missing something or not?

**Comment by Redjoni1** [comment]
> > Am i missing something or not?
> 
> Yes:
> 
> > This repository is only for reporting bugs or problems. If you need help, see: https://github.com/laravel/laravel#learning-laravel

I guess this is a bug or a problem

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
