### ISSUE TITLE
[5.7] Issue with morphTo, select and eager loading

### ISSUE THREAD

**Issue by lk77** [laravel/framework#26291]
Hello

- Laravel Version: 5.7.6
- PHP Version: 7.2
- Database Driver & Version: mysql 5.7

### Description:

Some queries using the 'relation:field' syntax with eager loading don't work anymore on 5.7.6.
the relation is empty when using this syntax. 

The relation parameter needs to be `relation` or `relation:id,field` for the relation to work. If ommiting id, it's not working.

It's working on 5.7.5, so it's a breaking change, all queries need to be updated.

it's somehow related to https://github.com/laravel/framework/pull/25662.

### Steps To Reproduce:

On fresh 5.7.6 install, simple morphTo relation :
```
public function table()
{
    return $this->morphTo('table');
}
```
Queries with multiple scenarios :
```
$result1 = MainTable::with('table')->get();
$result2 = MainTable::with('table:id,field1')->get();
$result3 = MainTable::with('table:field1')->get();

dd(
$result1->first()->table, 
$result2->first()->table, 
$result3->first()->table
);
```

result 1:
```
App\Models\SecondaryTable {#798
  #table: "secondary_table"
  [..]
  #original: array:4 [
    "id" => 1
    "field1" => 7
    "field2" => 8
    "field3" => 9
  ]
  [..]
}
```
result 2:
```
App\Models\SecondaryTable {#806
  #table: "secondary_table"
  [...]
  #original: array:2 [
    "id" => 1
    "field1" => 7
  ]
  [...]
}
```
result 3 :
```
null
```

the last relation is null, when omitting the id in the select of the morphTo relation.

thanks

**Comment by staudenmeir** [comment]
The third relationship is empty because eager loading *always* requires the `id` column to match the results to their parents. From the [documentation](https://laravel.com/docs/eloquent-relationships#eager-loading):

> When using this feature, you should always include the id column in the list of columns you wish to retrieve.

`with('table:field1')` "worked" before because Laravel ignored the selected columns before #25662. Up to 5.7.5, `with('table:id,field1')` and `with('table:field1')` were equivalent to `with('table')`.

**Comment by lk77** [comment]
For me it's still a breaking change, since the behaviour has changed, even if a bug was resolved, and it should have been merged in 5.8 and not 5.7.6.

**Comment by staudenmeir** [comment]
I disagree. You were using a non-existent feature in a way that wouldn't have worked if the feature existed.

**Comment by driesvints** [comment]
The docs are pretty explicit about this and the line was added over a year ago: https://github.com/laravel/docs/commit/f768e86341b34a3e188c4ef12e028f9ce017ac22
