### ISSUE TITLE
laravel helper function array_dot empty arrays doesn't ignore 

### ISSUE THREAD

**Issue by spmsupun** [laravel/framework#26308]
- Laravel Version: 5.6
- PHP Version:7.2

### Description:
**Original Array**
```
[
  'test1' => 1230,
  'test2' => [
            "nested"=>"value"
       ],
  'test3' => []
];
```
**after using `array_dot` method**
```
[
    'test1' =>  1230,
    'test2.nested' => "value",
    'test3'=>[]
]
```

But `test3` is still an array. 

**Expected result:**

```
[
    'test1' =>  1230,
    'test2.nested' => "value",
    'test3'=>''
]
```
Shouldn't  every dot notation value must be a none array value ?

**Comment by HongjiangHuang** [comment]
I don't know what you mean... Can you make it more clear?

**Comment by staudenmeir** [comment]
I would say that it's the expected result. If you want the transformation to be reversible, this is only possible way.

**Comment by HongjiangHuang** [comment]
In that case, what problems do you have in your development?

**Comment by driesvints** [comment]
It's actually the wanted behavior. If you check the internals there's an explicit check for this:

https://github.com/laravel/framework/blob/63dd423e8c7d537d2774d9e4caf5ca16f005bc96/src/Illuminate/Support/Arr.php#L114
