### ISSUE TITLE
Saved model returning 0 as the ID.

### ISSUE THREAD

**Issue by malinky** [laravel/framework#26311]
- Laravel Version: 5.7.11
- PHP Version: 7.1.8
- Database Driver & Version: mysql 14.14

### Description:

When saving a new model the returned id is 0. I used to be able to access the newly inserted id. The model does save in the database with the correct id.

This has stopped working since upgrading to 5.7.11 and only happens on my Laravel Forge production server. Has anyone experienced this issue?

The Primary Key on that column is set to auto increment.

**Comment by eddrems** [comment]
Please how do you resolve it

**Comment by malinky** [comment]
I closed this as the solution is project specific and not with the framework. It is only affecting that one project and only on the Forge environment, not my local environment. I stumbled across a fix by logging an output before calling the save method in my repository. It obviously makes no sense why this would work but it did for now and I had to move on with the project.

```
Log::debug('Return ID Bug');
$order->save();
```

**Comment by eddrems** [comment]
Thanks for sharing your answer. At the end of the day the error was because I installed telescope, I don't know why... but after removing telescope everything worked again normally.

**Comment by driesvints** [comment]
@eddrems @malinky  there's an issue about this here: https://github.com/laravel/telescope/issues/289

**Comment by malinky** [comment]
Thank you I'll take a look at that issue.

@eddrems Thanks so much. I didn't think about Telescope and removing it has fixed the issue for me too.
