### ISSUE TITLE
`updateOrCreate` on a hasMany relationship query modifies the original query

### ISSUE THREAD

**Issue by iget-master** [laravel/framework#26317]
- Laravel Version: 5.5.44
- PHP Version: PHP 7.2.11-3+ubuntu18.04.1+deb.sury.org+1
- Database Driver & Version: sqlite

### Description:

When calling `updateOrCreate` on a hasMany relationship, the original query is modified and not work anymore.

### Steps To Reproduce:

1. Create a model that contains any HasMany relationship, for example `User` that hasMany `Contact`  
2. Create a user, and add to it 5 contacts.
3. run this script

```
$user = User::first();

$query = $user->contacts();
echo $query->count(); // 5

$query->updateOrCreate([ 'id => 999 ], [ 'number' => '99999999' ]);

echo $query->count(); // 0 (wrong value)

echo $user->contacts()->count(); // 6 (right value)
```

Investigating by `var_dump($query->getBaseQuery()->wheres)` noticed that the `wheres` in the query is not the same that before calling `updateOrCreate`.

This is causing some problems to pass relationships into helper functions that do some jobs here.

I think that `updateOrCreate` should not modify the original query, instead it should clone and work inside a different object.

**Comment by iget-master** [comment]
To work around it, I have to clone the query object before using `updateOrCreate`

**Comment by xuanquynh** [comment]
I tried to debug the code. This stack is too complex.

- HasMany forwards HasOneOrMany.
- HasOneOrMany forwards Eloquent\Builder.
- Eloquent\Builder forwards Query\Builder.

It's hard to clone because "__clone" method also exists in Relation and Eloquent\Builder with only one attribute $query Query\Builder. That means every thing finally calls to Query\Builder where each method usually returns $this.

In my opinion, It's better and safer to use instead of changing this situation.
```php
$user = User::first();
$user->contacts()->count();
$user->contacts()->updateOrCreate([ 'id => 999 ], [ 'number' => '99999999' ]);
$user->contacts()->count();
```

**Comment by iget-master** [comment]
@xuanquynh 

Yes, your solution works as expected, but it makes my helper function more complicated:

```
syncHasManyRelationship(Builder $relation, $data) {
    $relation->somemethod(); // directly operates the relation
```

turns into

```
syncHasManyRelationship(Model $model, $relationName, $data) {
    $model->$relation()->somemethod(); // must call myself the relation method
```

The 2nd code looks overkill for me, however it works.

I really understand that if I do:

    $query->where(...)

the original query is modified, that's okay for me.

but 
 
    $query->find(5)

IMO should not modify the original query, the same logic goes for `updateOrCreate`, IMO.

**Comment by xuanquynh** [comment]
I think this should be supported by Laravel Core Framework.

**Comment by driesvints** [comment]
It's best to use the way that @xuanquynh suggested. It's generally not a best practice I believe to re-use a query object for several sets of operations. Best to start with a clean one.
