### ISSUE TITLE
[5.1.46] serialization error when using nullable function return types in php >7.1

### ISSUE THREAD

**Issue by vogtdominikgit** [laravel/framework#26310]
When calling `Mail::queue(...)` from classes that implement new php 7.1 return types like `public function foo() ?string` we will recieve an `Serialization of closure failed: There was an error analyzing the closure code`-Exception.

This is due to laravel/framework dependencies in version 5.1.46 on `"psy/psysh": "0.7.*"` which itself has a dependency on `"nikic/php-parser": "^1.2.1|~2.0"`. This will break the use of Serialization from Classes, that implement nullable return types.

We are currently added a workaround, by stating the following composer-alias:

```
>composer.json
...
"nikic/php-parser": "4.1.0 as 2.1-dev"
...
```

Can anybody else report such issues and see, if this will not break anything else? Secondly i would like to ask, if it is possible to bump the psy/psysh dependecy from `0.7.*` to `0.9.*`, since I dont see any problems with it.

Regards Dominik

**Comment by staudenmeir** [comment]
Laravel 5.1 is no longer supported.

**Comment by vogtdominikgit** [comment]
Time to change to 5.5. Maybe the bugfix and workaround will help someone.
