### ISSUE TITLE
Redirect after Email Verification only works when logged in

### ISSUE THREAD

**Issue by NA-Dev** [laravel/framework#26331]
- Laravel Version: 5.7.10
- PHP Version: 7.0
- Database Driver & Version: MySql 8.0.11

### Description:
I am having new users verify their email address before I send them first time login credentials. They receive the verification email, and verification works. However, the page that they are supposed to be redirected to afterwards does not appear. The home page appears instead. Next time they log in, they are taken the the post-verification page. There is no auth middleware set on the route, and I can reach the post-verification page just fine when not logged in.

I set the redirect page in VerificationController with protected $redirectTo = '/verified'. And this is working, just not until the user logs in.

### Steps To Reproduce:
Click email verification link when not logged in.

**Comment by LastDragon-ru** [comment]
> Click email verification link when not logged in.

Verification is not possible when you not logged in 🤣

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by NA-Dev** [comment]
Sorry my php version is actually 7.2.10. Below is my controller code

`<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\VerifiesEmails;

class VerificationController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Email Verification Controller
    |--------------------------------------------------------------------------
    |
    | This controller is responsible for handling email verification for any
    | user that recently registered with the application. Emails may also
    | be re-sent if the user didn't receive the original email message.
    |
    */

    use VerifiesEmails;


    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('signed')->only('verify');
        $this->middleware('throttle:6,1')->only('verify', 'resend');
    }

    /**
     * Where to redirect users after verification.
     *
     */
    protected function redirectTo() {
        return route('verified');
    }
}
`
