### ISSUE TITLE
Migration, column change, setting default value for DATETIME column, CURRENT_TIMESTAMP quoted even when wrapped in DB::raw()

### ISSUE THREAD

**Issue by dobrebydlo** [laravel/framework#26330]
- Laravel Version: 5.7.12
- PHP Version: 7.2.7
- Database Driver & Version: MySQL 5.7

### Description:
This is to reopen the unresolved/misinterpreted/poorly described issue #19111.

I am unable to set the default value of DATETIME column to CURRENT_TIMESTAMP. It gets quoted when transformed into SQL query even when i wrap it with DB::raw(). 

MySQL will let me do this directly, no problem, this kind of default value is supported by DATETIME columns:

https://dev.mysql.com/doc/refman/5.7/en/timestamp-initialization.html
"For any TIMESTAMP or DATETIME column in a table, you can assign the current timestamp as the default value, the auto-update value, or both"

So this is definitely NOT a database level problem.

Now when I try to do this in a Laravel transaction:
Schema::table('users', function (Blueprint $table) {
$table->dateTime('created_at')->default(DB::raw('CURRENT_TIMESTAMP'))->nullable()->change();
$table->dateTime('updated_at')->default(DB::raw('CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP'))->nullable()->change();
});

I get this:
SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'created_at' (SQL: ALTER TABLE users CHANGE created_at created_at DATETIME DEFAULT 'CURRENT_TIMESTAMP', CHANGE updated_at updated_at DATETIME DEFAULT 'CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP')

As you may see, the string CURRENT_TIMESTAMP gets quoted even when wrapped in DB::raw() which is not what is expected.

This only happens when _changing_ the column. I was finally able to create a new column with this default value.

### Steps To Reproduce:
1. Create a transaction.
2. Try to change an existing column of type TIMESTAMP setting its type to DATETIME and its default value to CURRENT_TIMESTAMP.
3. See the error.

**Comment by staudenmeir** [comment]
The SQL is generated by the `doctrine/dbal` package which doesn't know about Laravel's raw expressions.
Just use a string, `dbal` [detects](https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php#L2280) it:

```php
$table->dateTime('created_at')->default('CURRENT_TIMESTAMP')->nullable()->change();
```

**Comment by dobrebydlo** [comment]
Tried using the string as is, still no luck. 
However, you are right, there seems to be a problem on the doctrine/dbal side.

Using raw SQL statement seems to be the only working solution.
