### ISSUE TITLE
Eager Loading doesn't load result if Get method receives specific columns 

### ISSUE THREAD

**Issue by belguinan** [laravel/framework#26332]
- Laravel Version: 5.7.12
- PHP Version: 7.2.8
- Database Driver & Version: MySQL 8.0.12

### Description:
The problem here is when you need to select only some columns in your database and use eager loading to optimize other relations on your model. You have to write all foreign keys in `get()` method.

### Steps To Reproduce:

Suppose we have a product belongs to category. 
We only need to select name, id and the category:

`$product = Product::whereId(300)->with('category')->get(['id', 'name']);`

`dd( $product->category )`

The output is **null** because we didn't include category_id in get( $columns )

**Comment by staudenmeir** [comment]
Are you suggesting that Laravel should automatically select the missing columns?

**Comment by belguinan** [comment]
> Are you suggesting that Laravel should automatically select the missing columns?

Yes, only if it that makes sense. 
The problem is how to make it simple?

**Comment by belguinan** [comment]
> I don't think this is going to happen since this related PR got rejected: #23377

It would useful

**Comment by mfn** [comment]
I too think it would be useful.

Have been bitten this a few times too.

**Comment by mfn** [comment]
Especially since it seems (looking at the PR) it's possible correctly identify the column due to the defined relationship.

**Comment by staudenmeir** [comment]
I absolutely agree, but I wouldn't get my hopes up.

**Comment by driesvints** [comment]
Since this has been rejected in the past I don't think a new PR will be accepted. You could propose the change in https://github.com/laravel/ideas and gather support which may convince Taylor to accept a PR.

**Comment by cirdog** [comment]
Oh so this happens on 5.7 as well, then why I was mechanically told to test again on 5.7 a few minutes earlier?

My hope sure isn't up after being canned.
