### ISSUE TITLE
Dynamic Queues not working

### ISSUE THREAD

**Issue by ARKKYN** [laravel/framework#26339]
- Laravel Version: 5.5
- PHP Version: 7.1
- Database Driver & Version: Redis

### Description:
@taylorotwell  I am using Laravel queues to process jobs in a connection , since i have a dynamic queue name , I cannot specify queue name when using `queue:work` command, since I tried search a solution for it in laravel and other forums , It turned out to be a dead end

### Steps To Reproduce:
Create a dynamic queue name while scheduling queues and check it in horizon dashboard

**Comment by laurencei** [comment]
Why are you using dynamic queue names in the first place? Just use dedicated queues?

**Comment by sisve** [comment]
Have you considered building a custom queue that would fetch from multiple queues? As an example, it could involve extending the DatabaseQueue and just remove the `WHERE queue = $queue` part of the logic that selects a new job. Or change it into `WHERE queue LIKE 'my-queues-%'`

**Comment by ARKKYN** [comment]
@sisve At which file of RedisQueue

**Comment by 4n70w4** [comment]
@laurencei The same problem! I need to handle batch of tasks, for example, 1 000 pieces. And I need to be able to stop the batch of tasks and see the progress of the handling. This is most conveniently done through a dynamic queue name. One unique queue name for each batch of tasks.
