### ISSUE TITLE
Model find returns object event though it should fail

### ISSUE THREAD

**Issue by ByteHeroes** [laravel/framework#26343]
- Laravel Version: 5.6
- PHP Version: 7.2
- Database Driver & Version: mysql 5.7

### Description:
I have a user in the users table with id 1.
If I do 
`User::find("1-some-other-text-with-dashes");`
it returns the user model with id 1!
In my opinion this should never happen!

### Steps To Reproduce:
Create users table
Create users model
Create entry in users table with id 1
run php artisan tinker
execute "User::find('1-some-text');

**Comment by ankurk91** [comment]
```php
User::where("id","1-test-string")->toSql();
```

Raw mysql query behave same.
```sql
select * from `users` where `id` = "1-test-string"
```

i dont know how to make it strict, [could not](https://stackoverflow.com/questions/11193676/mysql-is-strictly-equal-to-operator) find answer.

**Comment by devcircus** [comment]
Search the issues. This has been questioned several times. As @ankurk91 said, mysql has the same behavior.

**Comment by hichxm** [comment]
To make it strict you need to define argument type in the function parameter to int

But is possible only with php 7.2 or more
If you want to be strict you can add condition before.

**Comment by driesvints** [comment]
This is default MySQL behavior and has nothing to do with the framework.
