### ISSUE TITLE
Singular table named without specified $table and with the model named format Capitalize

### ISSUE THREAD

**Issue by noobstyle2pro** [laravel/framework#26348]
When I create a model named 'Media' without define the table in the model (`protected $table = 'media';`), it supposed to have table named 'medias' but when I try to get `tableName()` in the tinker. It said table name named 'media' but when I create a model named 'Status' it supposed to have table named 'statuses' and it's. picture [here](https://www.dropbox.com/s/aicgpd7pmlvbdgb/tinker_evidence.png?dl=0).

Created Models Code:
- [Media](https://www.dropbox.com/s/glqxj5y1cko67mw/media_model_evidence.png?dl=0)
- [Status](https://www.dropbox.com/s/wef5okkk2u2x65w/status_model_evidence.png?dl=0)
- [Post](https://www.dropbox.com/s/dtsveotxilx46vs/possible_cause.png?dl=0)

Possible Similiar Issue:
 - issue [https://github.com/laravel/framework/issues/13559](https://github.com/laravel/framework/issues/13559) 

*note: I dont understand what is the solution when I read the possible similiar issue. I'm sorry if this is not a issue and if I only ask question that has been asked.

**Comment by hichxm** [comment]
If you need to set a name you can use $table protected variable in your model.

for example:
```php
class media extends Model
{
    protected $table = "medias"
}
```

**Comment by noobstyle2pro** [comment]
I'm sorry as I thought this is not an issue. thanks for your answer btw.
