### ISSUE TITLE
Thows Command not found exception while command calling from Controller

### ISSUE THREAD

**Issue by achalj09** [laravel/framework#26368]
- Laravel Version: 5.7
- PHP Version:7.1
### Description:
I have created custom commad, While calling from Command Promt it execute Successfully, But while Calling from Controller It throws Command not Found Exception.

My code as below
```
$exitCode = Artisan::call('mentor:deletecachetables', [
       '--outlet' =>1
 ]);
```

When I debug it, I found that in Console\Application.php below code returns false.

```
if (is_subclass_of($command, SymfonyCommand::class)) {
       $command = $this->laravel->make($command)->getName();
}
```

**Comment by laurencei** [comment]
You probably need to change

`Artisan::call(`
to
`\Artisan::call(`

**Comment by achalj09** [comment]
Not Working 
Also I have already include 
`use Illuminate\Support\Facades\Artisan;`

**Comment by laurencei** [comment]
Are you only loading your custom command if you are in the CLI perhaps.

**Comment by achalj09** [comment]
I solved this issue, by using class name in as first argument as 
`$exitCode = Artisan::call(deletecachetables::class, [
       '--outlet' =>1
 ]);`
