### ISSUE TITLE
Datetime2 with 0 precision.

### ISSUE THREAD

**Issue by lazosweb** [laravel/framework#26370]
- Laravel Version: 5.5.44
- PHP Version: 7.1
- Database Driver & Version: SQL Server 2012

### Description:
SQLServerGrammar typeDateTime should accept 0 precision in case we want to use datetime2 without milliseconds. Datetime2 with 0 precision is a valid value in Microsoft SQL.

### Steps To Reproduce:
```
Schema::create('archives', function (Blueprint $table) {
$table->dateTime('presentment_date', 0);
});
//Result: datetime
Schema::create('archives', function (Blueprint $table) {
$table->dateTime('presentment_date', 1);
});
//Result: datetime2 with precision 1.
```

**Comment by staudenmeir** [comment]
You can use a raw expression:

```php
Schema::create('archives', function (Blueprint $table) {
    $table->dateTime('presentment_date', DB::raw(0));
});
```

This is not ideal, but a fix would require bigger changes.

**Comment by lazosweb** [comment]
As a temporary solution I created my own package that extends the SQLServerGrammer and overwrites all those methods so that precision 0 will create a datetime2(0).

**Comment by AlexDanault** [comment]
`DB::raw(0)` works perfectly and is totally acceptable for me, and I recognize this is an edge case that would require major changes. Thanks @staudenmeir !
