### ISSUE TITLE
Facades fail to load when running a test with the @runInSeparateProcess

### ISSUE THREAD

**Issue by Ramapitecus** [laravel/framework#26372]
- Laravel Version: 5.7.x
- PHP Version: 7.2.11
- Database Driver & Version: N/A

When trying to run a test that uses the `@runInSeparateProcess` anotation from phpunit. Facades won't load correctly. This only happens if it's not the first test to run.  

### Steps To Reproduce:
    $ composer create-project --prefer-dist laravel/laravel blog #install as per the docs
    $ cd blog
    $ vim tests/Feature/ExampleTest.php 

In that file, copy the example test, paste the copy below, and change the name. Add the metnioned anotation in the documentation above 

```php
    /**
     * @runInSeparateProcess
     */
    public function testBasicTest0()
    {
        $response = $this->get('/');

        $response->assertStatus(200);
    }
```

run the tests:

    $ ./vendor/bin/phpunit 

This will give the error:
`PHPUnit\Framework\Exception: PHP Fatal error:  Uncaught Error: Class 'Route' not found in /home/rptx/workspace/blog/routes/api.php:17`

edit "routes/api.php" and add ``use Illuminate\Support\Facades\Route;``

run the tests again, and now the error is: 
```
1) Tests\Feature\ExampleTest::testBasicTest0
PHPUnit\Framework\Exception: PHP Fatal error:  Uncaught RuntimeException: A facade root has not been set. in /home/rptx/workspace/blog/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:220
Stack trace:
#0 /home/rptx/workspace/blog/routes/api.php(17): Illuminate\Support\Facades\Facade::__callStatic('middleware', Array)
#1 Standard input code(599): require_once('/home/rptx/work...')
#2 {main}
  thrown in /home/rptx/workspace/blog/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 220

Fatal error: Uncaught RuntimeException: A facade root has not been set. in /home/rptx/workspace/blog/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 220

RuntimeException: A facade root has not been set. in /home/rptx/workspace/blog/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 220

Call Stack:
    0.0042     682424   1. {main}() Standard input code:0
    0.1541    8990136   2. require_once('/home/rptx/workspace/blog/routes/api.php') Standard input code:599
    0.1541    8990136   3. Illuminate\Support\Facades\Facade::middleware() /home/rptx/workspace/blog/routes/api.php:17
    0.1541    8990512   4. Illuminate\Support\Facades\Facade::__callStatic() /home/rptx/workspace/blog/routes/api.php:17
```

**Comment by arekpietrzyk** [comment]
@Ramapitecus it works with phpunit installed in system PATH.

```
{12:17} arekp@x:~/work/tmp/blog ➭ phpunit --debug tests/Feature/ExampleTest.php
PHPUnit 7.4.0 by Sebastian Bergmann and contributors.

Test 'Tests\Feature\ExampleTest::testBasicTest' started
Test 'Tests\Feature\ExampleTest::testBasicTest' ended
Test 'Tests\Feature\ExampleTest::testBasicTest0' started
Test 'Tests\Feature\ExampleTest::testBasicTest0' ended


Time: 318 ms, Memory: 18.00MB

OK (2 tests, 1 assertion)
```

**Comment by Ramapitecus** [comment]
This is interesting. I just downloaded the phpunit-7.4.phar and ran it directly from the root of the project and it works. It also works if placed under `~/bin/` or `/usr/local/bin/`. It's not related with the folder it's running from. It just works for the manually installed version and not for the one installed by composer when creating the project.

**Comment by arekpietrzyk** [comment]
It looks like there is a specific problem with `PHPUnit 7.4.3`, because on `7.4.0` I had locally and `7.5-gbcbb5e0` downloaded as 'nightly' everything works fine.

**Comment by Ramapitecus** [comment]
Just to add to the comment above, I detected this problem on our project that uses phpunit 6.5 (laravel 5.5), but tested with a fresh install of the latest version before reporting.

**Comment by driesvints** [comment]
I can't reproduce this with the above steps.

Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by flexchar** [comment]
It is not necessarily on point for the particular issue but I had the same error and I was overriding `setUp` method. Remember to call `parent::setUp()` inside the override. :)

> From Laravel Docs: If you define your own setUp / tearDown methods within a test class, be sure to call the respective `parent::setUp()` / `parent::tearDown()` methods on the parent class.

**Comment by yurii-github** [comment]
I has faced this today. It looks like if you disable `preserveGlobalState` it works

```
    /**
     * @test
     * @runInSeparateProcess
     * @preserveGlobalState disabled
     */
    public it_tests_something()
    {
    }
