### ISSUE TITLE
Unable to upload indd (Adobe InDesign) File

### ISSUE THREAD

**Issue by krishnathakur1** [laravel/framework#26373]
- Laravel Version: 5.5
- PHP Version: 7.0

### Description:
**I am trying to upload adobe indesign file with extension indd but it do not detect extension and mime type.**

look at dumper output

-test: false
  -originalName: "RESOURCES.indd"
  -mimeType: "application/octet-stream"
  -size: 1728512
  -error: 0
  #hashName: null
  path: "/tmp"
  filename: "phpEMdS6J"
  basename: "phpEMdS6J"
  pathname: "/tmp/phpEMdS6J"
  **extension: ""  (Shows extension blank)**
  realPath: "/tmp/phpEMdS6J"
  aTime: 2018-11-03 16:45:35
  mTime: 2018-11-03 16:45:35
  cTime: 2018-11-03 16:45:35
  inode: 2098916
  size: 1728512
  perms: 0100600
  owner: 1000
  group: 1000
  type: "file"
  writable: true
  readable: true
  executable: false
  file: true
  dir: false
  link: false

I have this validation 

$this->validate($request, [
            'uploadDesign'  => 'required|mimes:ai,eps,svg,psd,indd'
        ]);

Always it returns with error  --->   **The uploadDesign must be a file of type: ai, eps, svg, pages, txt, psd, indd.**

Does anyone have a solution for this

**Comment by arekpietrzyk** [comment]
> Does anyone have a solution for this

You need to create own validation rule to handle this. `indd` has no MIME type.

**Comment by krishnathakur1** [comment]
> > Does anyone have a solution for this
> 
> You need to create own validation rule to handle this. `indd` has no MIME type.
> 
> PS quote from Laravel docs:
> 
> `A full listing of MIME types and their corresponding extensions may be found at the following location: https://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types`

Thanks, For the reply 
Could you let me know the process for that ?

**Comment by krishnathakur1** [comment]
> > Could you let me know the process for that ?
> 
> Laravel docs has detailed section about [Custom Validation Rules](https://laravel.com/docs/5.7/validation#custom-validation-rules). Artisan's command `make:rule` do the most work for you.

Thanks, Bro I have fixed this issue using custom validation
