### ISSUE TITLE
Do HasAttributes::originalIsEquivalent public

### ISSUE THREAD

**Issue by pablorsk** [laravel/framework#26383]
This function is great for observers... For example on `saving()` event:

```php
    public function saving(Product $product): void {
        if ($product->stock !== $product->getOriginal('stock')) {
            // do stuff
        }
    }
```

Is possible to change this? Or is there a reason to keep it that way?

**Comment by laurencei** [comment]
I'm going to close the issue here, as you've done a PR. As per the PR from Taylor - send it to the `master` branch, so it can be included in Laravel 5.8
