### ISSUE TITLE
Notifications are doing queries identical

### ISSUE THREAD

**Issue by regiszanandrea** [laravel/framework#26407]
- Laravel Version: 5.7.12
- PHP Version: 7.2.7
- Database Driver & Version: MySQL 5.7

### Description:
I'm using Laravel Notifications system, and when I dispatch a notification, it's saving on the database, working fine. But, when I see the queries that Laravel do, it's doing three identical queries one after other.

This is a exemple of queries that SerializesAndRestoresModelIdentifiers.php:85 do during a dispatch:
https://drive.google.com/file/d/1Q2TDbgpleFDBa9u_5T29E0sV2Ol76lee/view?usp=sharing

Anyone know why Laravel do three queries per dispatch? 
 
### Steps To Reproduce:
Use the Laravel Notification System

**Comment by driesvints** [comment]
I'll need more info to debug this further. Please post relevant code like jobs, notifications, events, listeners, controller methods, routes, etc. You may use https://paste.laravel.io to post larger snippets or just reply with shorter code snippets. Thanks!

**Comment by regiszanandrea** [comment]
Hello @driesvints, thanks for the reply, I'll paste some code below:

`Notification::send(User::find(1), new TournamentPaymentWon(...));`

TournamentPaymentWon:
https://paste.laravel.io/c09d5bb5-8746-4d16-85e7-29f231a4c4cf

**Comment by driesvints** [comment]
What are you queue settings (env values)? Is this locally?

**Comment by regiszanandrea** [comment]
Sorry, 

It's local, env=sync.

**Comment by driesvints** [comment]
What I *suspect* is that because of the sync driver and you using queues it emulates the behavior of a queue of serializing the model and restoring it afterwards. This all happens in one request (locally) but should be ok in production. You could perhaps try to emulate the real queue behavior locally or on a staging instance to see if it also happens there.

**Comment by regiszanandrea** [comment]
Thanks @driesvints 💯 👍
