### ISSUE TITLE
BelongsTo relation returns old relation when associate() is called with model ID

### ISSUE THREAD

**Issue by joostbaptist** [laravel/framework#26401]
- Laravel Version: 5.7.12
- PHP Version: -
- Database Driver & Version: -

### Description:

When calling `associate()` with a model ID on a `BelongsTo` relation, the foreign key is updated but the (possibly) previously loaded relation is not reset on the child model. This means that calling the relation after using `associate()` with a model ID will return the old relation, which can lead to unexpected behaviour if the developer is not careful to reload the relation.

I have created a PR to fix this issue by unsetting the relation.

### Steps To Reproduce:

```php
$foo->load('bar');

$newModelId = 5;

$foo->bar()->associate($newModelId);

// $foo->bar contains the old bar, NOT the new bar, because it was previously loaded
```

**Comment by driesvints** [comment]
Can you resend your PR to master?

**Comment by joostbaptist** [comment]
You were too fast, done ;-)
