### ISSUE TITLE
Logout Drop down not working

### ISSUE THREAD

**Issue by davinchi1** [laravel/framework#26400]
- Laravel Version: 5.7.12
- PHP Version:7.2.0
- Database Driver & Version:

### Description

When the logged in user is clicked, the drop down option for logging out does not appear on clicking the caret or name.

### Steps To Reproduce

After running make:auth, modfifed the User model to enable verification via email. Added telescope, then ran migration. Registered and verified by email. Log out option not presenting itself.

**Comment by driesvints** [comment]
This works for me with a fresh Telescope setup.

Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by davinchi1** [comment]
I will do a fresh install. 

Thanks
