### ISSUE TITLE
Custom get mutators do not override relationship when calling `toArray()` method

### ISSUE THREAD

**Issue by markwalet** [laravel/framework#26404]
- Laravel Version: 5.7
- PHP Version: 7.2.7

### Description:
When calling the `toArray()` method on an Eloquent model, the custom get mutators are not getting called. This results in a unmutated relationship attribute.

Use case: I want to use this to always mutate the keys when my relationship get's called. I want the keys to match the id of the model. For example:

```php
class Post {
    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function getCommentsAttribute()
    {
        return $this->getRelationValue('comments')->keyBy('id');
    }
}
```

This works fine. Except when casting the model to an array.

### Steps To Reproduce:
- Create a model with the `getFooAttribute()` mutator.
- Add a relation `foo` to the model.
- Call the `toArray()` method on the model.

I will create a PR for this issue.

**Comment by bonzai** [comment]
You should use `$appends` array, if you want to include accessor in the array.

https://laravel.com/docs/5.7/eloquent-serialization#appending-values-to-json

**Comment by markwalet** [comment]
Didn't work because of the `toArray()` method:

```php
    /**
     * Convert the model instance to an array.
     *
     * @return array
     */
    public function toArray()
    {
        return array_merge($this->attributesToArray(), $this->relationsToArray());
    }
```

The `$appends` variable is used in the `attributesToArray()` method. The relations are coming from the `relationsToArray()`.

Because the second array in `array_merge()` overwrites the first array, the plain, unmutated, relation list overwrites the mutated relation that was coming from `attributesToArray()`.

**Comment by driesvints** [comment]
As Taylor said in the PR, mutators aren't really meant to be used with relationships so this is actually not a bug.

**Comment by markwalet** [comment]
Why are they working when using the `getAttribute()` method then? That should be removed then.
