### ISSUE TITLE
Authorize middleware stopped using null values when model doesnt exists

### ISSUE THREAD

**Issue by gilesrussi** [laravel/framework#26422]
- Laravel Version: 5.7.*
- PHP Version:7.2
- Database Driver & Version: Not important

### Description:
As from Pull Request https://github.com/laravel/framework/pull/25763 we lost the ability to use a route parameter that may or may not exist in a "can:edit,user,company" middleware.

Before that was implemented, I had the ability to have a route /post/{post}/comment/{comment} and a route /comment/{comment} point to the same controller method and apply the "$this->middleware($middleWare)->only($method);" directly on said method on __construct();

Now, when I don't have a route parameter, it is returning a string instead of null;

Can we have an option to return null as a policy parameter when "post" doesn't exist? A cool format would be "can:edit,comment,post|null";

Thanks!

**Comment by driesvints** [comment]
We'll see what happens with the second PR.

**Comment by imanghafoori1** [comment]
@driesvints should this issue be still open ?

**Comment by driesvints** [comment]
@imanghafoori1 nope, thanks!
