### ISSUE TITLE
Any code within the __construct of a command will execute even when a different command is called

### ISSUE THREAD

**Issue by itsmill3rtime** [laravel/framework#26427]
- Laravel Version: 5.7.*
- PHP Version: 7.2
- Database Driver & Version: MySQL 5.7

### Description:
When a command class has something in the `__construct()` method such as a db query it will execute even when a different command is called. 

### Steps To Reproduce:

1. Create a command and put a query inside of the `__construct()` method like `$this-users = User::all();`
2. Run another command, any command such as `php artisan migrate`. 
3. It will run the query from your command even though you are calling a different method.

I noticed this when i rebuilt my homestead and lost my tables in the db. I got an error about the query trying to access the users table which didn't exist when i was trying to run `php artisan migrate`

**Comment by staudenmeir** [comment]
IMO, it's not a good practice to execute queries in the constructor. The constructor should only initialize the object but not actually "do" anything.

**Comment by itsmill3rtime** [comment]
That makes sense. But I'm still confused on why it executed. Is it because the class has to be called to get all the signatures?

**Comment by staudenmeir** [comment]
That would be my guess, too.

**Comment by mfn** [comment]
There's only one reason you should put code into the constructor: when your "signature" (or description) has dynamic values. But still it should be avoided.
