### ISSUE TITLE
Prevent namespaces starting with an integer in app:name command

### ISSUE THREAD

**Issue by renzo-s** [laravel/framework#26420]
- Laravel Version: 5.7.*
- PHP Version: 7.*

### Description:
Namespaces starting with an integer are disallowed per spec in all PHP versions. Running `artisan app:name [name starting with a number]` doesn't check for this condition and replaces the namespace anyway. After this, the app is broken and retrying the `app:name [name]` will not work anymore.

### Steps To Reproduce:
- `laravel new app`
- `php artisan app:name 1Stupid\\Mistake # 😉`

**Comment by driesvints** [comment]
Just don't use a number in your namespace?
