### ISSUE TITLE
Dramatic difference between creating laravel project using laravel new and composer create-project

### ISSUE THREAD

**Issue by palypster** [laravel/framework#26424]
- Laravel Version: 5.7.13
- PHP Version: 7.2
- Database Driver & Version: indifferent

### Description:
According to the documentation there are two ways of installing Laravel:
https://laravel.com/docs/5.7#installing-laravel

Either using:
```
laravel new blog
```

or using composer:
```
composer create-project --prefer-dist laravel/laravel blog
```

These two leads to different codebase, that differs dramatically - there are missing some features. Diff shows the changes at least in these files:

- package.json
- phpunit.xml
- app/Http/Kernel.php
- app/Http/Controllers/Auth/RegisterController
- app/Http/* (a lot of other changes in the whole app/Http directory)
- config/* (again, a lot of changes)
- resources/* (again, some changes are missing)

Side effect of this is that npm cannot compile using second way, while it perfectly compiles using the standard method using `laravel new`. With second way it is failing with the message:

```
ERROR  Failed to compile with 1 errors                                       3:03:24 PM

This relative module was not found:

* ./components/ExampleComponent.vue in ./resources/js/app.js
```

### Steps To Reproduce:

1. install one Laravel instance using `laravel new first` method
2. install second instance using `composer create-project --prefer-dist laravel/laravel second`
3. compare the two directories and see the difference - there is a difference, but should be none
4. try to compile npm using `npm install` and `npm run dev` - it is failing in the `second` directory, but it should not fail

**Comment by devcircus** [comment]
Strange. I just installed using both options. The code is identical and both compile as expected.

**Comment by driesvints** [comment]
I can't reproduce this either. Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by ajkabajka** [comment]
I have this issue as well. I have installed new Laravel installer (v2.0.1) on a fresh virtual server (ubuntu). The source code differs when I run `laravel new` and when I run `composer create-project`.

**Comment by palypster** [comment]
@driesvints Thanks, I'll give it a shot. Quick question: what version of installer have you tried? Did you cleared a composer cache? Because I tested it on a fresh install and on a several machines (virtual and physical) so I'm guessing there must be some cache or something on your side so you cannot reproduce it.

**Comment by driesvints** [comment]
@palypster Ah I now realize what's going on. Thanks for bring this to our attention. We need to tag a new release on the skeleton repo: https://github.com/laravel/laravel/releases

Will try to do this soon.

**Comment by driesvints** [comment]
New release has been tagged but doesn't seems to solve the problem. I think there's still some caching issue or perhaps packagist hasn't been updated yet (even though I see the tag). 

I'll retry this at a later time.

**Comment by palypster** [comment]
I can confirm it works now, the two sources looks (almost) identical and both compiles. Thank you!
