### ISSUE TITLE
PostgresGrammer CITEXT issue with LIKE 

### ISSUE THREAD

**Issue by jwhulette** [laravel/framework#26425]
- Laravel Version: 5.7
- PHP Version: 7+
- Database Driver & Version: Posgresql 10.5

### Description:
In PostgresGrammper file on line 31, the whereBasic function automatically casts the column as a TEXT. This causes issues if you use CITEXT, case-insensitive TEXT. 

### Steps To Reproduce:
email = bob.smith@aol.com
Cast as TEXT - User::where('email','like','Bob.Smith@aol.com')  = NULL
Cast as TEXT - User::where('email','like','bob.bmith@aol.com')  = User
Cast as CITEXT - User::where('email','like','Bob.Smith@aol.com')  = User

It appears the change was made because the LIKE would fail if the column was not a string.

**Possible solutions:**
1 - Remove the casting to text in the function
- Would be a breaking change
- Developer would have to manually cast any non-string fields

2 - Set a configuration variable to use cast fields as CITEXT
3 - Pass the column type to the function and if not a string type, then cast to TEXT.

**Comment by staudenmeir** [comment]
I don't see a realistic way to fix this. Use `ILIKE` instead:

```php
User::where('email','ilike','Bob.Smith@aol.com')
```

**Comment by driesvints** [comment]
I also believe `ILIKE` should be used in this case. Feel free to respond if you believe otherwise.
