### ISSUE TITLE
Laravel return object instead of array

### ISSUE THREAD

**Issue by shihabudheenf** [laravel/framework#26439]
- Laravel Version: 5.6 and 5.7
- PHP Version: 7.2
- Database Driver & Version:

When I am using custom key numeric array and return, it will give object instead of array.

### Steps To Reproduce:

`
Route::get('foo', function () {
    return [1=>'first item','2'=>'second item'];
});
`
### Output
`{"1":"first item","2":"second item"}`

### Expected Output
`["first item","second item"]`

**Comment by staudenmeir** [comment]
`json_encode()` will only return an array if the keys are consecutive and start with `0`. Otherwise, it will return an object.

**Comment by driesvints** [comment]
It's indeed default behavior of the `json_encode` function. You could force this with a flag but we'd rather not influence this default behavior.

See https://3v4l.org/jcZvR
