### ISSUE TITLE
Array request validation not working

### ISSUE THREAD

**Issue by LucasLeandro1204** [laravel/framework#26433]
- Laravel Version: 5.7.12
- PHP Version: 7.2.11
- Database Driver & Version: Mongodb v4.0.3

### Description:

When validating an array field `foo.*.bar` it doesn't get validated if not present in request.
And if I set `foo` to be required, it returns all the fields present in `foo.*`.

### Steps To Reproduce:

```
Request {
    "posts": [

    ]
}
```

```php
public function index(Request $request)
{
    $data = $request->validate([
        'posts.*.title' => 'required|string',
    ]);

    // validation passes and data is an empty array.
}
```

So, if I set posts array to be required, and someone send random data in the request:

```
Request {
    "posts": [
        {
            "title": "foo",
            "randomField": "bar"
        }
    ]
}
```

```php
public function index(Request $request)
{
    $data = $request->validate([
        'posts' => 'required',
        'posts.*.title' => 'required|string',
    ]);

    // validation passes and data is
    // [
    //     'posts' => [
    //         [
    //             'title' => 'foo',
    //             'randomField' => 'bar',
    //         ]
    //     ]
    // ]
}
```

**Comment by staudenmeir** [comment]
I see why would expect a different result, but this is the correct behavior.

**Comment by LucasLeandro1204** [comment]
You sure it is? I don't think it's, because object validation doesn't act that way.
I need the array to always be present, but this can lead to a security problem.

**Comment by staudenmeir** [comment]
What is an example of "object validation"?

**Comment by LucasLeandro1204** [comment]
```
[
  'posts.0.title' => 'required',
]
```

**Comment by staudenmeir** [comment]
Are you asking why you need the `'posts' => 'required'` rule? Or why the validated data contains the whole `posts` array? Or both?

**Comment by driesvints** [comment]
This is the correct behavior. Since you don't explicitly tell the validation that at least one result is required the validation passes.
