### ISSUE TITLE
Call to undefined method Illuminate\\Database\\Query\\Builder::getOwnerKey()

### ISSUE THREAD

**Issue by BHEADRICK** [laravel/framework#26448]
- Laravel Version: 5.3.30
- PHP Version: 7.1.8
- Database Driver & Version: MySQL 5.6

It looks like this function was renamed from getOtherKey in Laravel 5.4, but the sleepingowl package indicates that it is compatible with laravel 5.2 and up.

**Comment by staudenmeir** [comment]
This has nothing to do with Laravel, you should create an issue in the package repository.

**Comment by driesvints** [comment]
Please open up an issue on their repo.
