### ISSUE TITLE
Output migration progress during the process

### ISSUE THREAD

**Issue by tflori** [laravel/framework#26442]
Nice try :smiley: but I'm not a fan of how things are solved in laravel and so I will just write an issue / feature request. If you are interested in it or not is up to you.

The migration system currently (at least in 5.4) gathers an array of notes that after all migrations where executed sucessfully are fetched with `Migrator::getNotes()`. The problems come up when you get an exception after executing some of the migrations.

First of all: exceptions are not cached and nothing indicates which migration it was - you have to guess from the exception itself or the stack trace (if you enabled verbose mode).

Second: You don't know which migrations where successfully executed before the exception.

Third: You have no feeling of how long a migration takes. Of course this could be solved by execution time appended to the 'Migrated: <migration>' line.

Here we come again to the laravel way of development: I can't output something to stdout without the output interface (at least I should not print something to STDOUT). What we did is to pass the command to the constructor of the business logic class so that it can call `Command::info()` and so on. But it's a dirty solution and I hope you come up with something better then this.

What I expect is that the lines are sent to STDOUT as soon as they are created - otherwise it does not make sense to write 'Migrating: <migration>\nMigrated: <migration>' as it is just obvious.

**Comment by staudenmeir** [comment]
This has been implemented in Laravel 5.7: #24811

**Comment by driesvints** [comment]
Please upgrade to the latest version.
