### ISSUE TITLE
TestResponse errors persist through test cases.

### ISSUE THREAD

**Issue by agentmarine** [laravel/framework#26455]
- Laravel Version: 5.7
- PHP Version:7.2.11
- Database Driver & Version: N/A

### Description:
Running some unit tests on some endpoints within my application, I am testing for some Malformed XML and an appropriate error, the issue I've come across is that when making a request, the response is then stored across unit test suites.

for example: 

> ImportUsertest.php
```
public function testInvalidXML()
    {
        header('content-type', 'application/xml');
        $body = '<?xml version="1.0"?>
        <Company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
          <Customers>
            <Customer>
              <AccountReference>JOE001</AccountReference>
              <CompanyName>TEST COMPANY</CompanyName>
              <SendElectronicInvoice>true</SendElectronicInvoice>
              <SendElectronicLettertrue</SendElectronicLetter>
            </Customer>
          </Customers>
        </Company>';
        
        $response = $this->call('POST',  '/api/v1/customer/create', [], [], [], [], $body);

        $expected = '<?xml version="1.0" encoding="UTF-8" ?>
        <Company>
            <error>
                <message>error parsing attribute name</message>
                <message>attributes construct error</message>
                <message>Couldn\'t find end of Start Tag SendElectronicLettertrue line 8</message>
                <message>Opening and ending tag mismatch: Customer line 4 and SendElectronicLetter</message>
                <message>Opening and ending tag mismatch: Customers line 3 and Customer</message>
                <message>Opening and ending tag mismatch: Company line 2 and Customers</message>
                <message>Extra content at the end of the document</message>
            </error>
        </Company>';
        $actual = $response->getContent();
        $this->assertXmlStringEqualsXmlString($expected, $actual);
    }
```
So, at the end of this test, I would expect that the response object would get destroyed when it moves onto another file

>ImportProductTest.php

 ```
   public function testMalformedXML()
    {
        header('content-type', 'application/xml');
        $xml = "<?xml version='1.0'?>
        <Company>
          <Products>
            <Product>
              <Sku>PROD001</Sku>
              <Name>Test Product</Name>
              <GroupCode>1</GroupCode>
              <IntrastatCommodityCode>71162019</IntrastatCommodityCode>
              <CommodityCode>Necklaces</CommodityCode>
              <Barcode>9789862410035</Barcode>
              <ItemTypeStock</ItemType>
              <Location>Warehouse</Location>
              <UnitWeight>12</UnitWeight>
            </Product>
          </Products>
        </Company>";
        
        $output = $this->call('POST',  '/api/v1/products', [], [], [], [], $xml);

        $shouldBe = '<?xml version="1.0" encoding="UTF-8" ?>
<Company>
    <error>
        <message>error parsing attribute name</message>
        <message>attributes construct error</message>
        <message>Couldn&#039;t find end of Start Tag ItemTypeStock line 11</message>
        <message>Opening and ending tag mismatch: Product line 4 and ItemType</message>
        <message>Opening and ending tag mismatch: Products line 3 and Product</message>
        <message>Opening and ending tag mismatch: Company line 2 and Products</message>
        <message>Extra content at the end of the document</message>
    </error>
</Company>';

        $content = $output->getContent()
        $this->assertXmlStringEqualsXmlString($shouldBe, $content);
}
```
at the end of this test, I would expect both of them to have passed. the problem though is that the error from the previous malformed xml test still exists and results in an output like this

```
1) Tests\Feature\ImportUserTest::testInvalidXML
Failed asserting that two DOM documents are equal.
--- Expected
+++ Actual
@@ @@
   <error>
     <message>error parsing attribute name</message>
     <message>attributes construct error</message>
+    <message>Couldn't find end of Start Tag ItemTypeStock line 11</message>
+    <message>Opening and ending tag mismatch: Product line 4 and ItemType</message>
+    <message>Opening and ending tag mismatch: Products line 3 and Product</message>
+    <message>Opening and ending tag mismatch: Company line 2 and Products</message>
+    <message>Extra content at the end of the document</message>
+    <message>error parsing attribute name</message>
+    <message>attributes construct error</message>
     <message>Couldn't find end of Start Tag SendElectronicLettertrue line 8</message>
     <message>Opening and ending tag mismatch: Customer line 4 and SendElectronicLetter</message>
     <message>Opening and ending tag mismatch: Customers line 3 and Customer</message>
```
It seems that the errors have been appended to each other, which causes the result to fail.

At this point after looking into it, I've traced it back to the [TestResponse](https://laravel.com/api/5.7/Illuminate/Foundation/Testing/TestResponse.html) class where I dont believe that there is any thing cleaning up after this.

The only way i have found to bypass this is to run all the unit tests within their own processes using the flag --process-isolation

**Comment by driesvints** [comment]
Isn't this more of a PHPUnit error? You can btw send your headers as server vars with the call method. If you use the `post` method you can even simplify everything much more.

Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by agentmarine** [comment]
Hi @driesvints , I thought it would have been a phpunit error my self, but since its a laravel class, Phpunit's batted it back to Laravel see [#3393 @phpunit](https://github.com/sebastianbergmann/phpunit/issues/3393) . 

I've spent quite a long time discussing this within the Larachat on slack already tried diagnosing this with @Wim Pruiksma

**Comment by driesvints** [comment]
Okay. Reopening this. I don't have time to check on this myself atm but feel free to send in a PR with a test that fixes this.

**Comment by staudenmeir** [comment]
Can you provide a simple example of controller & test that we can use to reproduce this issue?

**Comment by agentmarine** [comment]
OK So i've built a super simple Controller, two test cases to replicate how i have mine set up (except my test cases target two different endpoints)

You'll get some errors like this

```
PHPUnit 7.4.3 by Sebastian Bergmann and contributors.

FF                                                                  2 / 2 (100%)

Time: 3.36 seconds, Memory: 24.00MB

There were 2 failures:

1) Tests\Feature\test1Test::testMalformedXML
Failed asserting that two DOM documents are equal.
--- Expected
+++ Actual
@@ @@
 <?xml version="1.0"?>
-<rows>
+<Company>
   <error>
     <message>error parsing attribute name</message>
     <message>attributes construct error</message>
-    <message>Couldn't find end of Start Tag test line 3</message>
-    <message>Opening and ending tag mismatch: Company line 2 and test</message>
+    <message>Couldn't find end of Start Tag test line 1</message>
+    <message>Opening and ending tag mismatch: Company line 1 and test</message>
     <message>Extra content at the end of the document</message>
   </error>
-</rows>
+</Company>

/Users/dansmacbook/projects/test/tests/Feature/test1Test.php:32

2) Tests\Feature\test2Test::testMalformedXML
Failed asserting that two DOM documents are equal.
--- Expected
+++ Actual
@@ @@
 <?xml version="1.0"?>
-<rows>
+<Company>
   <error>
     <message>error parsing attribute name</message>
     <message>attributes construct error</message>
+    <message>Couldn't find end of Start Tag test line 1</message>
+    <message>Opening and ending tag mismatch: Company line 1 and test</message>
+    <message>Extra content at the end of the document</message>
+    <message>error parsing attribute name</message>
+    <message>attributes construct error</message>
     <message>Couldn't find end of Start Tag test line 3</message>
     <message>Opening and ending tag mismatch: Company line 2 and test</message>
     <message>Extra content at the end of the document</message>
   </error>
-</rows>
+</Company>
```

I've attached the class & tests and a route in api, you can just drop it on top of a fresh laravel installation and use the xml below.

```
<?xml version="1.0"?>
<Company>
	<test</test>
</Company>
```

[tests.zip](https://github.com/laravel/framework/files/2566072/tests.zip)

**Comment by staudenmeir** [comment]
Please add the `xmlResponse` view.

**Comment by agentmarine** [comment]
HI @staudenmeir I've attached it to this comment.
[xmlResponse.blade.php.zip](https://github.com/laravel/framework/files/2571180/xmlResponse.blade.php.zip)

**Comment by staudenmeir** [comment]
Shouldn't `test1Test` expect the errors in line `1`?

**Comment by agentmarine** [comment]
possibly, however, if you were to test it using something like postman, you would get the same response

![Postman example](https://puu.sh/C0ylJ/c234060973.png)

**Comment by agentmarine** [comment]
[updated tests.zip](https://github.com/laravel/framework/files/2572305/updated.tests.zip)
I've updated the tests you should get a better output from them using this where one test passes (which is correct) but the 2nd test appends the previous one.

**Comment by staudenmeir** [comment]
Running both tests combined works for me.

You must be doing something differently because I can only run the tests after removing `header('content-type', 'application/xml');`. Otherwise, I get a "Cannot modify header information" exception.

How are you running the tests?

**Comment by staudenmeir** [comment]
You have to call `libxml_clear_errors()` in your controller.

**Comment by agentmarine** [comment]
yep that seems to have fixed it thank you @staudenmeir  its bizzare, you would have thought it would have cleared it on its own.
