### ISSUE TITLE
Package translation only return key in Controller

### ISSUE THREAD

**Issue by sethsandaru** [laravel/framework#26467]
- Laravel Version: 5.7.13
- PHP Version: 7.1.13

### Description:
Currently I'm trying to create a Laravel package. And I'm using translation too. 

The `__` and `trans` functions work fine in package's View, but in package's **Controller**, it's only return the key

I'm load translation by using `loadTranslationsFrom`.

```php
// load
 $this->loadTranslationsFrom(__DIR__ . "/Languages", "Administration");

// get
trans('Administration::prod_lang.prod_name'); // only return key in Controller, from View is ok
```

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
