### ISSUE TITLE
Laravel CORS Error after update Laravel for 5.7.13

### ISSUE THREAD

**Issue by stonkeep** [laravel/framework#26463]
- Laravel Version: 5.7.13
- PHP Version: 7.2
### Description:
I've got CORS error after updated to 5.7.13.
I'm using barryvdh/laravel-cors package and ultil now I've not error CORS.
Some one knows if Laravel update have this error?
Or order package?

**Comment by driesvints** [comment]
Heya, it's best that you open up an issue with their repo: https://github.com/barryvdh/laravel-cors
