### ISSUE TITLE
Calling singletons in controller constructs

### ISSUE THREAD

**Issue by CrixuAMG** [laravel/framework#26490]
- Laravel Version: 5.7.13
- PHP Version: 7.2.11-3+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Oct 25 2018 06:44:08) ( NTS )
- Database Driver & Version: MariaDB v10.1.34

### Description:
When calling `php artisan route:list` (or any command line call to a controller requiring a singleton), an exception is thrown stating that the interface cannot be instantiated.

```
Target [App\\Contracts\\UserContract] is not instantiable while building [App\\Http\\Controllers\\UserController].
```

The singleton is based on the `pathInfo` property on the `Request` class, which returns `"/"`, instead of a required `/users`, based on which the correct singleton is constructed.

### Steps To Reproduce:
Setup an array in a Service Provider
```
$array = [
    'users' => [
                '__contract'  => UserContract::class,
                '__arguments' => [
                    UserRepository::class,
                    UserCache::class,
                ],
            ], 
];
```
Analyse the `pathInfo`
```
$route = rtrim(ltrim(request()->getPathInfo(), '/'), '/');

// Explode route based on `/`, then loop over the array and construct the singleton
/** Looping over array, selecting match */

$this->app->singleton($contract, function () use ($contract, $chain) {
        // Create a variable that will hold the instance
        $instance = null;

        foreach ((array)$chain as $class) {
            // Decorate the instance with the class
            $instance = $instance ?  new $class($instance) : new $class();
        }

        // Return the instance
        return $instance;
        });
```

### Problem
If the `pathInfo` is empty, the singleton cannot be constructing, thus failing generating (for example) the `route:list`.
Is there some way of faking/setting a (mocked) path, so that command line calls can function as required and still work with the controllers I created?

**Comment by sisve** [comment]
There's no valid request context when executing the service providers or in the controller constructors. This has been the case since Laravel 5.3. It would probably be better to rewrite your application logic so it worked with the framework, than looking into ways to fake the paths.

**Comment by CrixuAMG** [comment]
Do you think there's a way of setting a static path in a controller that can be used if `App::runningInConsole()` returns true? 
If it cannot work in the end I'll have to think of some other way than using route based application constructing 😅

**Comment by driesvints** [comment]
As @sisve said, this probably will need to be solved differently. There's no request context here. It's probably best that you try one of these support channels to figure this out:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
