### ISSUE TITLE
Shared hosting login redirect 

### ISSUE THREAD

**Issue by NordyVlasman** [laravel/framework#26494]
I uploaded my Laravel application to my shared hosting and got almost everything working except the authentication system. When i try to login with the default laravel authentication system. I get redirected back to the login system without any errors. To see what is going wrong check: [user.uren-management.nl ](https://user.uren-management.nl/register) . Also my log files dont give any errors and when i try to connect to the database, it returns a status OK

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

**p.s. from reading your issue - the most likely issue is your sessions are not working at all. If you can work out why, it will probably fix your issue.**

Thanks in advance.

**Comment by kamleshwebtech** [comment]
@laurencei  What is solution of this weird problem? I am using laravel 13 and trying to upload developed application on shared server. I have checked your suggested URLs. No one replied correctly about this issue. If you have any suggestion, please share with me solve this issue. Thank you.
