### ISSUE TITLE
LogManager With Monolog Driver

### ISSUE THREAD

**Issue by Newbas** [laravel/framework#26505]
- Laravel Version: 5.6.39 & 5.7.13
- PHP Version: 7.2.10
- Database Driver & Version: 

### Description:
Using Monolog driver for log manager with SocketHandler (i think same can happen with others as well) breaks application if SocketHandler throws error on connection. There is Emergency Logger that could solve it, but as i understand because SocketHandler makes connection only on write Laravel does not use this emergency logger and kill app. 

### Steps To Reproduce:
Config Logger 
`'logstash' => [
            'driver' => 'monolog',
            'handler' => \Monolog\Handler\SocketHandler::class,
            'formatter' => \Monolog\Formatter\LogstashFormatter::class,
            'with' => [
                'connectionString' => env('LOGSTASH_TCP', '')
            ],
            'formatter_with' => [
                'applicationName' => 'AppName'
            ]
        ]`

If application can't connect to Socket here it dies.

**Comment by driesvints** [comment]
Heya. Unfortunately we don't offer support for this Laravel version anymore. Can you upgrade to the latest version and see if the problem persists? Feel free to report back if it still fails in that case.

**Comment by driesvints** [comment]
Okay. Re-opening. I don't have time atm to dive deep into this but I've marked it as a bug so we don't lose track of this.

**Comment by HongjiangHuang** [comment]
Connection failure should be handled by the developer himself ?
I think the framework should not handle this kind of error.

**Comment by Newbas** [comment]
@HongjiangHuang 
In my opinion there are few things. I understand that Monolog is not part of Laravel, but then it is worth to mention in documentation that such problem may arise. Cause currently such situation just kills app. Also i think it is used emergency logger before i updated, but cause i thought to use formatter settings and it works only in newer version i updated laravel. 

Cause you won't put every logger in try catch you will need to write something around such handler. Best place for such things in my opinion is very near framework, may be it is custom handler (but again documentation need to aware about such situations) but it can be used on framework level as well, especially if it states to work with Monolog, and also cause it is worked before, not sure Monolog updated Handler to connect lazily or Laravel changed somehow. 

One situation more is that such problem may appear after few logs send and it is also will break everything. 

And last thing in my opinion logs are very important, but it is not very cool when writing something like "Job Completed" to log will break whole application just before returning result. And cause logger is part of framework it should manage such situations and as i understand emergency logger is step to solve it.

**Comment by mfn** [comment]
What's the problem exactly?

It's fine that Monolog may not connect to MongoDB due to issues but it's no ok that the fallback emergency driver crashes, is that the TL;DR ?

Can you be more specific what it means "it dies"? Can you debug a big where it dies, what's going on?

**Comment by Newbas** [comment]
I does not connect to MongoDB, connecting with SocketHandler to Logstash. And if it is not possible to connect to socket Monolog throws unhandled

I will try to be more precise. I already checked how it happens. 

Monolog throws UnexpectedValueException [here](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/SocketHandler.php#L299)

Laravel on creation catches exceptions [here](https://github.com/laravel/framework/blob/5.7/src/Illuminate/Log/LogManager.php#L98) and creates emergency logger if error appears. 

Cause Monolog SocketHandler in [constructor](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/SocketHandler.php#L45) just initialise it self and does not create actual connection it does not throw this exception in that case. 

And after any log attempt will throw unhandled exception. Tried to change into production mode to check may be it will work differently for production but no changes. As i said before one of composer updates it worked. But not sure Monolog moved to lazily initialisation or Laravel changed something.

**Comment by mfn** [comment]
> Cause Monolog SocketHandler in [constructor](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/SocketHandler.php#L45) just initialise it self and does not create actual connection it does not throw this exception in that case.

Ah, so the exception you only get _during runtime_ not when creating the driver, so the procedure for the emergencyLogger is not possible.

I think I align with https://github.com/laravel/framework/issues/26505#issuecomment-439140229 , a runtime error of log driver should be handled more gracefully by the driver.

The same would happen if there are suddenly permission or disk space issues with the regular file stream driver, wouldn't it?

I think would you need is something like a custom Monolog logger which itself uses MongoDB and has built-in fallback to wherever you want to have it otherwise (probably likely the way the emergencyLogger works).

**Comment by Newbas** [comment]
It is not about my code, i had custom log manager and logger before so it is not very problematic to solve it for me. 

The main thing that other people may caught this and it is not so obvious from document. As well as in my opinion default LogManager can suggest some ways to solve this problem may be through some sort of settings.

**Comment by gmsantos** [comment]
Monolog has WhatFailureGroupHandler to ignore those failure situations:

https://github.com/Seldaek/monolog/blob/master/doc/02-handlers-formatters-processors.md#wrappers--special-handlers

It's useful if you can't guarantee a service availability but you need to keep the application working.
I think it is out of the application scope to monitor external services.

**Comment by Newbas** [comment]
Thanks to everyone. Not sure should it appear in a feature request, but i will close it cause it is not bug. Thanks one more time for your time.
