### ISSUE TITLE
Email Verification fails to authorize route id properly

### ISSUE THREAD

**Issue by andrewalba** [laravel/framework#26507]
- Laravel Version: 5.7.10 
- PHP Version: 7.2.5
- Database Driver & Version: mysql:5.7

### Description:
Email verification link `/email/verify/{id}` will always return true for authenticated users regardless if route->parameter->id matches user->id.

### Steps To Reproduce:
- Register or log in as unconfirmed user "A" (user->id = 1) to generate email verification confirmation that contains email verification link. 
- Log out user "A".
- Register or login as unconfirmed user "B" (user->id = 2). 
- While logged in, click the email verification link from the email sent out to user "A" which will have route parameter id = 1.
- The link will successfully redirect as if the process was successful even though the route parameter id (1) does not match the user id of user "B" id(2).

We have overridden the verify() method in our VerificationController to address in our app.

```php
    /**
     * Mark the authenticated user's email address as verified.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     * @throws AuthorizationException
     */
	public function verify(Request $request)
	{
		if ($request->route('id') != $request->user()->getKey()) {
			throw new \Illuminate\Auth\Access\AuthorizationException\AuthorizationException();
		}

		if ($request->user()->markEmailAsVerified()) {
			event(new Verified($request->user()));
		}

		return redirect($this->redirectPath())->with('verified', true);
	}
```

**Comment by driesvints** [comment]
I can indeed see why this would give you trouble. Given the fact that we use user ids in the url and not a random string we should indeed require the actual user to be logged in so your solution makes sense I believe. Feel free to send in a PR to the 5.7 branch.
