### ISSUE TITLE
Why in ResetCommand::getOptions() path option could be value and array, not just a value as all other Console Migrate classes

### ISSUE THREAD

**Issue by vasymus** [laravel/framework#26506]
@see Illuminate\Database\Console\Migrations\ResetCommand::getOptions() 'path' option
compare it to others:
Illuminate\Database\Console\Migrations\FreshCommand::getOptions()
Illuminate\Database\Console\Migrations\MigrateCommand::getOptions()
Illuminate\Database\Console\Migrations\RefreshCommand::getOptions()
Illuminate\Database\Console\Migrations\RollbackCommand::getOptions()
Illuminate\Database\Console\Migrations\StatusCommand::getOptions()

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by vasymus** [comment]
@driesvints 
"Looks like this is a question which can be asked on a support channel"(c)

can you, pls, give me the link ?
