### ISSUE TITLE
app()->handle() catches exceptions when the $catch parameter is FALSE

### ISSUE THREAD

**Issue by kwebble** [laravel/framework#26502]
- Laravel Version: 5.4.36, but code of 5.7.13 looks similar
- PHP Version: 7.1.21
- Database Driver & Version: n/a

### Description:
When calling `\Illuminate\Foundation\Application::handle()` with the `$catch` parameter set to `FALSE` exceptions are still caught.

This does not match the documented behavior for `$catch`: _Whether to catch exceptions or not_.

### Steps To Reproduce:
Call `app()->handle()` with 3 parameters and throw an exception in the matching route:

    try {
        // Create $req object, in my case something like this:
        Request::create($myUrl, Request::METHOD_POST, ['some' => 'data']);

        app()->handle($req, Application::MASTER_REQUEST, FALSE);
        Log::debug('NO EXCEPTION');
    } catch(\Exception $e) {
        Log::debug('EXCEPTION THROWN');
    }

This logs the text _NO EXCEPTION_ when the route for the request throws an exception.

Looking at the implementation of `handle()` in `Application` shows the passed parameter is silently ignored:

    /**
     * {@inheritdoc}
     */
    public function handle(SymfonyRequest $request, $type = self::MASTER_REQUEST, $catch = true)
    {
        return $this[HttpKernelContract::class]->handle(Request::createFromBase($request));
    }

**Comment by driesvints** [comment]
You're correct. This doesn't matches the implementation. Although I'm not sure if implementing this is wanted in terms of how Laravel processes requests.

**Comment by kwebble** [comment]
Perhaps it's not common to do this in Laravel applications.

It's used in a package for payment processing. The application provides a notification URL when creating a payment order. The package performs a HTTP POST on this URL to pass the final result of the payment order.

Errors are now detected by checking the HTTP response code after the call to `handle()`.

**Comment by driesvints** [comment]
Okay, closing this off then.
