### ISSUE TITLE
PHP Laravel 5.4 Unresolvable dependency resolving [Parameter #0 [ <required> $items ]] in class Illuminate\Pagination\LengthAwarePaginator

### ISSUE THREAD

**Issue by JitendraThakur007** [laravel/framework#26517]
PHP Laravel 5.4 Unresolvable dependency resolving [Parameter #0 [ <required> $items ]] in class Illuminate\Pagination\LengthAwarePaginator

Illuminate\Contracts\Container\BindingResolutionException: Unresolvable dependency resolving [Parameter #0 [ <required> $items ]] in class Illuminate\Pagination\LengthAwarePaginator in /var/www/html/valuable-app-new/valueable_rest_app/vendor/illuminate/container/Container.php:843
Pagination function is not working when upgraded laravel from 5.3 to 5.4.

**Comment by driesvints** [comment]
Hey there. I'm sorry but we don't support 5.3 or 5.4 anymore. Please try to see if one of the following support channels can help you:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
