### ISSUE TITLE
ExtensionGuesser fails to guess for svg file

### ISSUE THREAD

**Issue by orckid-lab** [laravel/framework#26511]
- Laravel Version: 5.6
- PHP Version: 7.2.9

### Description:
Saving an svg file via the "store" method of the Request class fails to set the extension. The file ends up being saved with the hash and a dot at the end i.e 4fwIUbYO8KEolasAdmvRV5xDcEVOMGeA2zyoWaYk.

### Steps To Reproduce:
- Submit a file via post under an attribute i.e "file"
- Use the request instance to store the file to a specified path i.e ```` $request->file('file')->store('path') ````

Note, the above works fine for any other image format. Tested on png, jpg etc. The issue above occurs only for svg so far.

**Comment by ankurk91** [comment]
Most likely [symfony](https://github.com/symfony/symfony) framework issue

**Comment by orckid-lab** [comment]
I read an issue at [https://github.com/symfony/symfony/issues/8354](url) which might be related with the above. It seems Symfony does not use the mime type returned by file Upload to guess the extension. Am I correct to understand that this is not actually an issue and that for such cases we need to work around it?

**Comment by driesvints** [comment]
Heya, this is indeed a symfony issue I believe. You'll have to set the extension yourself.

**Comment by laratutodotcom** [comment]
**How to get file extension from path in Laravel 9?** https://laratuto.com/how-to-get-file-extension-from-path-in-laravel/**
