### ISSUE TITLE
Asset import function in blade views and using php variables in assets files

### ISSUE THREAD

**Issue by Pefren** [laravel/framework#26518]
Sometimes I paste minified assets code directly on production website to prevent 'slow' <script src="..."> <link href="..."> tags (also it's reccomended by Google PageSpeed).
And It would be nice to use php variables in assets files too. So:
It would be nice to make a function that will import assets code ('.js' and '.css' files) in blade view (like `@importAsset('js/app.js')`) before rendering php variables so I could use in assets files php variables like:

` var counter_val = {{ $counter_val }}; `
OR
` .counter { width: {{ $counter_width }}; } `

**Comment by ankurk91** [comment]
Who is stopping you. 
Just create your own directive. :)

**Comment by Pefren** [comment]
Didn't know about custom blade directives. Thanks a lot!
