### ISSUE TITLE
custom artisan command with --env option is not working in scheduler

### ISSUE THREAD

**Issue by mukeshtivari** [laravel/framework#26519]
- Laravel Version: 5.6.39
- PHP Version: 7.2.4
- Database Driver & Version:
5.7.21 - MySQL Community Server (GPL)

### Description:
I'm having multiple environment files for different subs like `.env.sub1`, `env.sub2` & many others and I have created a custom artisan command `daily:update` which i want to call for every sub in scheduler and each sub is having their own database and the credentials for the database are stored in their respecting `.env` files.

so, if I'm executing `php artisan daily:update --env=sub1` command directly from command prompt, it's working perfectly fine ( by reading the right db credentials from it's `.env.sub1` file ) but when i schedule that command inside scheduler it causes error like selecting the wrong db credentials, directly from the default `.env` file.

Question is:
`php artisan daily:update --env=sub1` from command prompt is working perfectly fine but same command is not working from scheduler and scheduler code is like below,

```
<?php

namespace App\Console;

use Illuminate\Console\Scheduling\Schedule;
use Illuminate\Foundation\Console\Kernel as ConsoleKernel;

class Kernel extends ConsoleKernel
{
    /**
     * The Artisan commands provided by your application.
     *
     * @var array
     */
    protected $commands = [
        Commands\DailyUpdate::class
    ];

    /**
     * Define the application's command schedule.
     *
     * @param  \Illuminate\Console\Scheduling\Schedule  $schedule
     * @return void
     */
    protected function schedule(Schedule $schedule)
    {
      foreach(glob('.env.*')? : [] as $file){        
        if($file != '.env.example'){
          // getting account name
          $account = str_replace('.env.', '', $file);
          
          // running a command that initializes the initial values into the database.
          $schedule->command("daily:update --env={$account}")->dailyAt('00:01');
        }
        
      }
    }

    /**
     * Register the commands for the application.
     *
     * @return void
     */
    protected function commands()
    {
        $this->load(__DIR__.'/Commands');

        require base_path('routes/console.php');
    }
}
```

### Steps To Reproduce:
1. create a artisan command which perform some db operations.
2. setup a cron for scheduler
3. set above artisan command (step: 1) to execute at every minute by specifying `--env` option like as i have done above.
4. see into `laravel.log` file it will have some errors ( in my case master database is not having those tables so, it causes error for table missing because it's selecting `.env` files ).

Thanks in advance.

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
