### ISSUE TITLE
When forcing null on attributes, hasChanges does not detect changes

### ISSUE THREAD

**Issue by joruro** [laravel/framework#26521]
- Laravel Version: 5.7
- PHP Version: 7.1

### Description:

Forcing `null` on method `isDirty`

https://github.com/laravel/framework/blob/6ff9df42c8a6d9230bbaca5171a5d6253fa71890/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L1036

Makes that `hasChanges`

https://github.com/laravel/framework/blob/6ff9df42c8a6d9230bbaca5171a5d6253fa71890/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L1074

This happens because `func_get_args()` is returning

```
array:1 [▼
  0 => null
]
```

### Steps To Reproduce:
Just force `null` on `isDirty`

**Comment by driesvints** [comment]
Hmm, I see your point. Feel free to send in a PR for this.

**Comment by staudenmeir** [comment]
Fix has been rejected in #23929.

**Comment by driesvints** [comment]
@staudenmeir thanks for making me aware. As there are no plans to change this atm I'm gonna close this. Feel free to open up an issue in https://github.com/laravel/ideas to see if you can get support to change this behavior.
