### ISSUE TITLE
Exception thrown in callable array syntax in route definition

### ISSUE THREAD

**Issue by dionysiosarvanitis** [laravel/framework#26536]
- Laravel Version: 5.7.13
- PHP Version: 7.2.10
- Database Driver & Version:

### Description:

When using Route registration as follows:

```php
Route::get('smth', [SomeController::class, 'methodName']);
```

and `methodName` is a callable like `redirect` or `reset` then UnexpectedValueException is been triggering with message Invalid route action: [redirect].

**Comment by driesvints** [comment]
I can't reproduce this. Have you defined the methods on your controller? Please post your controller and full `web.php` file.

**Comment by dionysiosarvanitis** [comment]
Add the following line at web.php of a clean laravel installation

Route::get('test', [App\Controllers\Controller::class, 'redirect']);

**Comment by driesvints** [comment]
You've added a route which doesn't links to an actual controller method.

**Comment by devcircus** [comment]
Just tested with the following:

```php
//web.php
Route::get('/', [\App\Http\Controllers\HomeController::class, 'redirect']);
```

```php
//HomeController.php
<?php

namespace App\Http\Controllers;

class HomeController extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @return \Illuminate\Http\Response
     */
    public function redirect()
    {
        dd('hit');
    }
}
```
Result in browser:
**"hit"**

**Comment by dionysiosarvanitis** [comment]
I'm really sorry, my fault! Forgot the leading backslash as @driesvints said. Had more routes like this but only `redirect` and `reset` complained!
