### ISSUE TITLE
[5.5] Mailable build the view tpl Admin/work cannot be identified

### ISSUE THREAD

**Issue by elinxer** [laravel/framework#26533]
- Laravel Version: 5.5
- PHP Version: 7.2
- Database Driver & Version:  needless

### Description:
[5.5] Mailable build the view tpl the name is work cannot be identified.
mysql system is ubuntu18.04
Under the resources/views directory,my dirname is Admin just like this `resources/views/Admin/work/test.blade.php` and content is 12312323.
And `resources/views/Admin/workkkkk/test.blade.php` is ok.
So I wanna ask, that is Is the keyword of **work** conflict?

### Mycode

`

    /**
     * Build the message.
     *
     * @return $this|mixed
     */
    public function build()
    {
        return $this->subject('title')->view('Admin.work.test')->with('data', $data = []);
    }

`

### some error:
[2018-11-16 14:23:27] local.ERROR: Session store not set on request. {"exception":"[object] (RuntimeException(code: 0): Session store not set on request. at /var/www/mihuan_v1/vendor/laravel/framework/src/Illuminate/Http/Request.php:419)

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
