### ISSUE TITLE
Same Origin Policy(Cors) seems that not works L 5.7.13

### ISSUE THREAD

**Issue by apapazisis** [laravel/framework#26545]
- Laravel Version: 5.7.13
- PHP Version: 7.1.9
- Database Driver & Version: MySQL 5.7

### Description:
When I create a middleware and return from it the $next($request) with specific headers I got error that Same Origin Policy blocked my ajax(axios) request. 

In my middleware

 `return $next($request) `
             `->header('Access-Control-Allow-Origin', '*') `
             `->header('Access-Control-Allow-Methods', 'GET, POST, PUT, PATCH, DELETE, OPTIONS') `
             `->header('Access-Control-Allow-Headers', 'Content-Type, Authorization'); `

### Steps To Reproduce:
1. Create a middleware and add the following code in `handle() function`
 `return $next($request) `
             `->header('Access-Control-Allow-Origin', '*') `
             `->header('Access-Control-Allow-Methods', 'GET, POST, PUT, PATCH, DELETE, OPTIONS') `
             `->header('Access-Control-Allow-Headers', 'Content-Type, Authorization'); `
2. Add the created middleware in global array $middleware in kernel.php so that the middleware runs for every request
3. Comment the middleware `\App\Http\Middleware\VerifyCsrfToken::class`
4. Create a POST route and make an ajax request to the route so that you get the error that Same Origin Policy blocks your request. 
**Important:** Using Postman looks that it works but using Chrome as an example throws the error

I post also some images they may help

The Error image in console
![image](https://user-images.githubusercontent.com/13486500/48640041-c8bdfc00-e9d5-11e8-81e1-07279203ac7e.png)

The request details
![image](https://user-images.githubusercontent.com/13486500/48640119-f73bd700-e9d5-11e8-95d4-081bb9e8f64a.png)

![image](https://user-images.githubusercontent.com/13486500/48640158-16d2ff80-e9d6-11e8-8167-ddefffea82db.png)

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back. You may also want to check into https://github.com/barryvdh/laravel-cors

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
