### ISSUE TITLE
Laravel broke after app:name -v 5.7.6

### ISSUE THREAD

**Issue by gharabaghi** [laravel/framework#26546]
after running app:name laravel throws an exception:
message: Class 'App\Providers\AppServiceProvider' not found
file: vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php
line: 208: return new $provider($this->app);

config:cache and composer dump-autoload not working.

**Comment by staudenmeir** [comment]
It works for me. Can you reproduce this on a fresh Laravel installation?

**Comment by gharabaghi** [comment]
> It works for me. Can you reproduce this on a fresh Laravel installation?

i will try.

**Comment by ahinkle** [comment]
Try to run `config:cache` command, if you can't delete file `bootstrap/cache/config.php` and then re-run `config:cache` command and everything will be fine again.

**Comment by laurencei** [comment]
Closing as not framework related.

**Comment by 9555643857** [comment]
Class 'App\Providers\AppServiceProvider' not found error 
![image](https://user-images.githubusercontent.com/17945452/62270846-a7624a80-b454-11e9-8d0e-581c960c4395.png)

**Comment by brunogaspar** [comment]
@9555643857 Your `AppServicerProvider.php` file has the wrong class inside.

Composer is warning you about it on the yellow box.
