### ISSUE TITLE
"php artisan migrate --verbose" not working

### ISSUE THREAD

**Issue by VokaMut** [laravel/framework#26547]
- Laravel Version: 5.7.13
- PHP Version: 7.1.21
- Database Driver & Version: MySQL 5.7.23

### Description:
Not working verbose option in any migrate commands
php artisan migrate[:ANY] [-v|-vv|-vvv|--verbose]

### Steps To Reproduce:
1. Create migration
2. Apply migration with any verbose options
3. See:
Migrating: 2018_11_17_153848_add_test_table
Migrated:  2018_11_17_153848_add_test_table

**Comment by staudenmeir** [comment]
What output are you excepting?

**Comment by VokaMut** [comment]
Something else:
```
Migrating: 2018_11_17_153848_add_test_table
creating table `test`
    unsigned int 'id'
    string 'title'
    unsigned int 'user_id'
create index 'user_id'
create foregin key 'user_id' references 'id' on 'files' on update 'cascade' on delete 'cascade'
Migrated: 2018_11_17_153848_add_test_table
```

**Comment by staudenmeir** [comment]
That's not the purpose of the verbosity options in Laravel.

These options only affect the output in case of an error.
