### ISSUE TITLE
Gate::before() not getting called

### ISSUE THREAD

**Issue by sreenadh** [laravel/framework#26559]
Laravel v5.7.13
PHP Version 7.1.19
```

namespace App\Providers;

use Illuminate\Support\Facades\Gate;
use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;

class AuthServiceProvider extends ServiceProvider
{
    /**
     * The policy mappings for the application.
     *
     * @var array
     */
    protected $policies = [
        'App\Model' => 'App\Policies\ModelPolicy',
    ];

    /**
     * Register any authentication / authorization services.
     */
    public function boot()
    {
        $this->registerPolicies();

        Gate::before(function ($user, $ability) {
            die('before called');
        });
    }
}
```

**Comment by staudenmeir** [comment]
Please provide your Laravel version.

**Comment by sreenadh** [comment]
@staudenmeir sorry. 

Laravel 5.7
PHP Version 7.1.19

**Comment by sreenadh** [comment]
Gate::after() is working fine.

**Comment by driesvints** [comment]
This works fine for me. Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
