### ISSUE TITLE
[5.7] Collection sortBy causes invalid JSON array

### ISSUE THREAD

**Issue by jaripekkala** [laravel/framework#26557]
- Laravel Version: 5.7.6
- PHP Version: 7.2.9
- Database Driver & Version:

### Description:
I would expect the two collections with same data in the same order to output the same JSON string.

This causes hard to find bugs when sometimes the output is parsed as an array and sometimes object via JavaScript.

### Steps To Reproduce:
```php
$ordered = collect([
    ['name' => 'apple'],
    ['name' => 'banana'],
    ['name' => 'orange'],
]);

$unordered = collect([
    ['name' => 'orange'],
    ['name' => 'apple'],
    ['name' => 'banana'],
]);

// fails
$this->assertEquals(
    $ordered->sortBy('name')->toJson(),
    $unordered->sortBy('name')->toJson()
);
```

```php
// passes
$this->assertEquals(
    '[{"name":"apple"},{"name":"banana"},{"name":"orange"}]',
    $ordered->sortBy('name')->toJson()
);

// passes
$this->assertEquals(
    '{"1":{"name":"apple"},"2":{"name":"banana"},"0":{"name":"orange"}}',
    $unordered->sortBy('name')->toJson()
);
```

**Comment by driesvints** [comment]
This is just how the `sortBy` method works under the hood. It uses `asort` to sort the values. If you want you can use a different sorting way that you prefer.

https://3v4l.org/23qVM

**Comment by jaripekkala** [comment]
`$unordered->sortBy('name')->values()->toJson()` re-indexes the array if somebody else tumbles into this.

When working with arrays I would expect to receive valid JSON array when calling `toJson()`.
