### ISSUE TITLE
[5.7] Case insensitive load/with are reloaded when accessed

### ISSUE THREAD

**Issue by marcus13371337** [laravel/framework#26568]
- Laravel Version: 5.7
- PHP Version: 7.2
- Database Driver & Version: General

### Description:
Doing the following:
```
$posts = Post::all();
$posts->load('authoR');
```
or
`$posts = Post::with('authoR')->get();`

And then:
```
foreach($posts as $post) {
     echo $post->author->name;
}
```
I would expect that only two queries are executed or an error is thrown because of the wrong caseing in the relation name. Currently the queuries executed will be number of posts plus 1.

I would expect that if the load() and with() functions are case insensitive then the attribute ->author should also be case insensitive.

### Steps To Reproduce:
Look at this implode.io for an example https://implode.io/4COKe9

**Comment by driesvints** [comment]
It's normal for this to be case sensitive because relations are case sensitive by nature due to their method names.

**Comment by marcus13371337** [comment]
@driesvints If that's the case, that relations are "case sensitive by nature", why doesn't the with() or the load() function throw an error? This can lead to unexpected queries

**Comment by marcus13371337** [comment]
@driesvints Buuut:
`$posts->load('auaathoR');`
Gives me the error:
`Call to undefined relationship [auaathoR] on model [Post].`

See the inconsistency? :)

**Comment by marcus13371337** [comment]
Also:
`Post::with('aaaaauthor')->get();`
Gives me:
`Call to undefined relationship [aaaaauthor] on model [Post].`

**Comment by driesvints** [comment]
Hmm. Okay I see it. Maybe we can make this more explicit for the load and with methods as well. Thanks for bringing this to our attention.

**Comment by marcus13371337** [comment]
Actually after some research functions in PHP are actually case INsensitive but attributes are not. This makes it quite confusing.

**Comment by driesvints** [comment]
Okay, thanks for investigating.
