### ISSUE TITLE
`Str::before` and `Str::after` return the original string

### ISSUE THREAD

**Issue by yaquawa** [laravel/framework#26561]
- Laravel Version: 5.7.13
- PHP Version:7.2

### Description:
`Str::before` and `Str::after` return the original string even if the given string for searching not found.

### Steps To Reproduce:

```
Str::before('account_type', 'foo') 
// returns 'account_type', I expected that it'll return `null`
// same issue with the `Str::after`
```

**Comment by driesvints** [comment]
Hmm I see your point but I believe this is more of a behavioral change rather than a bug. It's best to post this idea at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework.
