### ISSUE TITLE
$withCount breaks replicate()

### ISSUE THREAD

**Issue by tobz-nz** [laravel/framework#26562]
- Laravel Version: 5.7.13
- PHP Version: 7.2.9
- Database Driver & Version: mysql / ?

### Description:
As in other cases(that have all been fixed I think), a model with a polymorphic relation and a `$withCount` property fails to `replicate()`

### Steps To Reproduce:
```
class Board extends Model {
public $withCount = ['profiles'];
public function profiles()
    {
        return $this->morphedByMany(User::class, 'profilable');
    }
}

$b = Board::first();
$b2 = $b->replicate();
$b2->save();
```

Results in the error:
`Column not found: 1054 Unknown column 'profiles_count' in 'field list' ...`

Expected `$b2` to be a new Board instance with same properties as original.

**Comment by tobz-nz** [comment]
Am getting past this currently by manually passing in the count property to the `replicate($except)` param.

`$b->replicate(['profiles_count'])`

$this should be pretty easy to fix by using the `withCount` property in replicate's internal filtering.
...although that won't help for manually counted relations (loaded after the fact using `withCount()`).

I don't think there's a register for counted relations (ala the `$model->relations` array)

**Comment by staudenmeir** [comment]
You are calling `save()` afterwards, right? `replicate()` itself doesn't trigger the error.

**Comment by tobz-nz** [comment]
Ah yes - sorry, missed that part.

**Comment by staudenmeir** [comment]
I don't think we can make this assumption. There could be users who except the `profiles_count` attribute in the replicated model. Maybe they don't want to save it but use it for something else.

**Comment by tobz-nz** [comment]
Yep, Good point.
Maybe a register of all loaded withCount's and ignore them on save? 

Or maybe move where the count is stored from the attributes array to something else and do a check in getAttribute()? That could be a BC issue though aye?

**Comment by staudenmeir** [comment]
I'm not sure it's worth the effort.

**Comment by tobz-nz** [comment]
Seems like a pretty bad bug to me. If you have a polymorphic relation and a withCount you can't replicate?
I realize its a little bit of a edge case but still...

**Comment by staudenmeir** [comment]
It's my impression that `$withCount` is not widely used, especially in combination with `replicate()`. IMO, using `$expect` is good enough as a workaround.

**Comment by tobz-nz** [comment]
Whats `$expect`? I've not seen this.

**Comment by staudenmeir** [comment]
Sorry, I meant `$except` (the parameter of `replicate()`).

**Comment by tobz-nz** [comment]
Ah, haha here I am searching through the code for $expect :)

yeah fair enough. At least there's a record of the issue here now for others (and myself in the future when I've forgotten about it)

**Comment by staudenmeir** [comment]
Somewhat related: #25495

**Comment by tobz-nz** [comment]
Yes I think that's the same underlying issue.

Also TIL about `storedAs` :)

**Comment by staudenmeir** [comment]
The fundamental "issue" is that Laravel (unlike some other frameworks) doesn't know what columns the table contains, so there is no solution that can cover all cases. As you mentioned, we could fix it for `$withCount` but not for `withCount()`.

**Comment by tobz-nz** [comment]
Unless you move the count value out of the main attributes array to something like `$withCounts`? and access that via the `getAttribute()` method.

but doing that could break people code if they're accessing the count directly on $attributes - so that's probably a no go as well.

well, I suppose it could go into 5.8?

**Comment by staudenmeir** [comment]
Yes. Also, consider #26481.

**Comment by driesvints** [comment]
This is tricky indeed. On the one hand you could say that filtering out the counts and stored as values is twtg because they aren't actually defined on the new static class instance. On the other hand people might expect these values to still be present when replicating a model. I don't think there's an easy for for this. As @staudenmeir said manually adding the columns to the `except` array is probably the best solution at the moment so people can simply choose how to handle it.

I noticed that the `replicate` method is currently undocumented so I'll send in a PR to the docs for this together with a note on this behavior.

**Comment by driesvints** [comment]
Sent in a PR: https://github.com/laravel/docs/pull/4795

**Comment by driesvints** [comment]
The PR was closed to prevent confusion with other methods. We're going to leave this undocumented for now.
