### ISSUE TITLE
make:migration oversight maybe

### ISSUE THREAD

**Issue by JonahKlimack** [laravel/framework#26572]
- Laravel Version: 5.3.31
- PHP Version: 7.1.24

### Description:

php artisan make:model Affiliates.php -m created migration with problems

### Steps To Reproduce:
Through my own carelessness, I ran:

php artisan make:model Affiliates.php -m 

I edited the migration file and ran migrate, only to get the below console error.

### Output

created file Affiliate.php.php for the model

``` 
namespace App;

use Illuminate\Database\Eloquent\Model;

class Affiliate.php extends Model
{
    //
}
```

Create simliar problem (I erased it since, don't remember) in class file name for migration

But this console error...

  [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1049 Unknown database 'affiliate' (SQL: create table `affiliate`.`phps` (`id` int unsigned not null auto_increment primary key, `user_id` int unsigned not null, `creat
  ed_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate utf8_unicode_ci)

  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1049 Unknown database 'affiliate'

  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1049 Unknown database 'affiliate'

I realize my mistake, and fixed it but this looks a little scary to me.

Thought you should be aware.

**Comment by driesvints** [comment]
Heya, unfortunately we don't support this Laravel version anymore. Please upgrade to the latest version and check if your problem persists.
