### ISSUE TITLE
Kernel.php $middlewarePriority docblock description does not match behavior

### ISSUE THREAD

**Issue by unstoppablecarl** [laravel/framework#26571]
- Laravel Version: 5.7.13

### Description:

In the [`App\Http\Kernel.php` L68](https://github.com/laravel/laravel/blob/6806aaa3568382e9c8c7281a64b82a52b824e46f/app/Http/Kernel.php#L68) file the `$middlewarePriority` property comment says "This forces the listed middleware to always be in the given order.", but that is not exactly true.

Middleware is processed in 2 groups:

1) Global middleware is run in the order defined in the `App\Http\Kernel.php` `$middleware` property.

2) All other middleware is merged and sorted using the `$middlewarePriority` property in `App\Http\Kernel.php` to determine ordering.

After finding the behavior of the Kernel did not match this comment, someone asked me for help understanding middleware. I assumed the comment accurately described the behavior but after looking at the source found that to not be the case.

I propose that the comment be clarified to say: "This forces all non-global middleware to always be in the given order." or all middleware be merged and sorted as currently described. Does anyone know what the original intent was? I don't have a strong feeling either way. It would be nice to have all middlware sorted together but I can also see some complications with doing that.

**Comment by driesvints** [comment]
You're right. Feel free to send in a PR to update the comment.
