### ISSUE TITLE
Tests that rely on a mocked validation failing when mocking the passess method automatically succeed now..

### ISSUE THREAD

**Issue by hdimitrov1** [laravel/framework#26577]
- Laravel Version: 5.7.13
- PHP Version: 7.2.5
- Database Driver & Version: Irrelevant

### Description:
If you have a test in which you are mocking the passes method in a validation to false, then it will not fail the test. 

In our case, the example was
```	
	$failingValidation = $this->createMock(CustomValidation::class);
	$failingValidation->method('passes')->willReturn(false);
	$request = Request::create('', 'POST', ['validated_member' => 'value']);
	$this->expectException(\Illuminate\Validation\ValidationException::class);
	$this->controller->call($request, $failingPushableUrl);
```

This test fails as `\Illuminate\Validation\ValidationException::class` is never thrown.

The issue appears to be that when an empty array is returned from the `message()` method, the test will pass. See https://github.com/laravel/framework/blob/3ff3110ac14f2b4876acaff289bb55a1af74f02e/src/Illuminate/Validation/Validator.php @ Lines 545 and 591. 

The fix to this is admittedly simple, it just involves adding a secondary part of the mock.

```
		$failingValidation->method('message')->willReturn('not passing');
```

However, this is a somewhat breaking change in a normal release.
### Steps To Reproduce:

1. Create a unit test that mocks a failing request validation, and then calls the request
2. Assert that the method will throw the  `\Illuminate\Validation\ValidationException::class` exception.
3. Check that the test fails

**Comment by claudiodekker** [comment]
Seeing this one as well when using a failing custom FormRequest.
It's not specific to mocking per definition, as I'm not mocking anything.

In addition information gathered thus far, I've noticed the following behaviour:
- The exception **does** get thrown and caught by `expectException` when asserting something on the response object (for instance, `$response->assertExactJson(...)`)
- I can assert the 302 status code (default ValidationException redirect error for non-ajax requests), which indicates to me that the exception _did_ get thrown.
