### ISSUE TITLE
test where using  expectException fails when upgrading to 5.7.14 from 5.7.13

### ISSUE THREAD

**Issue by gandesc** [laravel/framework#26596]
- Laravel Version: 5.7.14
- PHP Version: 7.1.24 & 7.2.11
- Database Driver & Version: N/A

### Description:

When upgrading from L5.7.13 to L5.7.14, a test containing 
```
$this->expectException(ConflictHttpException::class)
```
 in combinantion with calling a route that throws the given exception, fails with the message:
```
Failed asserting that exception of type "Symfony\Component\HttpKernel\Exception\ConflictHttpException" is thrown.
```

As far as we can tell, there are 2 merge requests included in 5.7.14 and related to testing [here](https://github.com/laravel/framework/commit/cfab97fbed78c1eddb9a570edcf69122ae197029) and [here](https://github.com/laravel/framework/commit/ae0491875e272fb13a513bc1d5b22d0bf325767e) but we're unable to pinpoint the issue.

### Steps To Reproduce:

```php
public function failing_test()
{
    $this->expectException(ConflictHttpException::class);
    $this->delete(route('system.route', $this->myId, false));
}
```

The response for the DELETE request does have a `409` response code and does contain the expected exception.

### Expected result:

The test passes in L5.7.14 as it passes in L5.7.13

@aocneanu

**Comment by driesvints** [comment]
`ConflictHttpException` is a `HttpException` which are internally ignored in the exception handler. It's meant to be rendered properly so that's why the `expectException` doesn't work. I don't know how this worked for you in 5.7.13 because the test also doesn't pass for me in that version.

**Comment by aocneanu** [comment]
@driesvints 

So if I understand correctly, this test should fail?

```php

/** @test */
public function test()
{
    $this->expectException(ConflictHttpException::class);
    throw new ConflictHttpException;
}

```

**Comment by driesvints** [comment]
@aocneanu no. You're not hitting the framework or any route there. It's not going through Laravel's exception handler.
