### ISSUE TITLE
[Refactor sugestion] Illuminate\Foundation\Testing\TestResponse is too big

### ISSUE THREAD

**Issue by jhm-ciberman** [laravel/framework#26598]
I think the class `Illuminate\Foundation\Testing\TestResponse` is currently too big and has a lot of different concerns. 
I think it should be better to refactor it in two separate Traits. For example: `AssertsAboutJSON` and `AssertsAboutViews`, and of course, keep the other more generic methods inside the class. (Like `dump` and `assertsOk`). 

I currently find a bit difficult as a user to read the class to learn and use all the features in my test since currently this High level class has more than 1k lines of code. 

Of course, this is only a simple suggestion, and if you think for some reason that it should be keept as a single class with a lot of methods, feel free to close this issue.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not for ideas, suggestions etc. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. You are able to open a ticket at https://github.com/laravel/ideas

Alternatively you are able to open a PR using the Contributions guidelines: https://laravel.com/docs/5.7/contributions#which-branch

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
