### ISSUE TITLE
Can not test multi choice in console test

### ISSUE THREAD

**Issue by kiyonlin** [laravel/framework#26590]
- Laravel Version: 5.7.14
- PHP Version: 7.2.12
- Database Driver & Version: 

### Description:
Can not test multi choice in console test

#### new app
`laravel new testMultiChoice`
#### new command
`php artisan make:command MultiChoiceCommand`
make a choice question in `handle` method
```php
public function handle()
{
      $choice = $this->choice('multi choice', ['one', 'two'], null, 1, true);
      dump($choice); // when use console test, dump "one,two"
      $this->line('Your choice was ' . json_encode($choice));
}
```

#### new test
`php artisan make:test MultiChoiceTest -unit`

write unit test method
```php
     /**
     * A basic test example.
     *
     * @return void
     */
    public function testExample()
    {
        $this->artisan('command:name')
            ->expectsQuestion('multi choice', 'one,two')
            ->expectsOutput('Your choice was ["one","two"]')
            //->expectsOutput('Your choice was "one,two"')
            ->assertExitCode(0);
    }
```

Because the `expectsQuestion` function's answer param only support `string` type.

So the test result is 
```
Output "Your choice was ["one","tow"]" was not printed.
```

**Comment by kiyonlin** [comment]
change `expectsQuestion` function's answer param type to string|array can solve the problem

**Comment by driesvints** [comment]
I don't really get the issue. It seems everything is working fine except you'd like a different sort of syntax? It's best to post this at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework.

**Comment by kiyonlin** [comment]
@driesvints Thanks for replying! 
My point is that the function `expectsQuestion` in [PendingCommand.php](https://github.com/laravel/framework/blob/5.7/src/Illuminate/Foundation/Testing/PendingCommand.php) should change to be like this
```php
    /**
     * Specify a question that should be asked when the command runs.
     *
     * @param  string  $question
     * @param  string|array  $answer
     * @return $this
     */
    public function expectsQuestion($question, $answer)
    {
        $this->test->expectedQuestions[] = [$question, $answer];

        return $this;
    }
```

Otherwise I can't test choice in command witch maybe with multiple answers.

**Comment by driesvints** [comment]
Ah okay I get what you mean. That's indeed an feature request so you should post in the ideas repo and if others agree with you send in a PR to the repo. I'm also not 100% sure if that's possible.
