### ISSUE TITLE
Relationship with UUID force sometime a cast to integer

### ISSUE THREAD

**Issue by masterix21** [laravel/framework#26594]
- Laravel Version: 5.7.14
- PHP Version: 7.2.11
- Database Driver & Version: MySQL Ver 14.14 Distrib 5.7.24, for osx10.14 (x86_64)

### Description:
I had wrote the application using 5.6, migrated to 5.7. On the first releases (5.7) it works, now it has some casting problems. I'm using only UUID as ID, with $incrementing to FALSE.

Using the following relation
```php
public function clazz()
{
      return $this->belongsTo(Clazz::class, 'class_id', 'id');
}
```

the query will be translated to:
```sql
SELECT * FROM `classes` WHERE `classes`.`id` in (9223372036854775807, 47054, 4, 4, 51316830)
```

But if i change the previous relation with:
```php
public function clazz()
{
      return $this->hasOne(Clazz::class, 'id', 'class_id');
}
```

it works:
```sql
SELECT * FROM `classes` WHERE `classes`.`id` in ('45e24ee0-e670-11e8-a21c-f19a3bda0c2c', '47054ee0-e670-11e8-b6fd-91db92a186e6', '4ae66650-e670-11e8-82dd-f790d51163b7', '4d2b19f0-e670-11e8-b1c2-777da339fff3', '51316830-e670-11e8-a9d6-fbefcd513547')
```

Any ideas?

**Comment by masterix21** [comment]
I have downgraded now to 5.7.13 and belongsTo start again to works: i can confirm the bug with 5.7.14.

**Comment by driesvints** [comment]
Please see https://github.com/laravel/framework/issues/26591 & https://github.com/laravel/framework/issues/26582

**Comment by masterix21** [comment]
Thanks, sorry.
