### ISSUE TITLE
Request payload breaks when passing an integer with a leading zero

### ISSUE THREAD

**Issue by AndreLazari** [laravel/framework#26599]
- Laravel Version: 5.5.40
- PHP Version: 7.1.0
- Database Driver & Version: MySql 

### Description:
I have an endpoint who needs a payload data for a PUT method. One of the fields must be integer type.
My client sometimes pass a integer value starting with 0. When this happens, all the payload breaks. I can't even handle the value because it gets in controller already NULL.

One example of breaking payload:
`{"status: "waiting", "code": 09324}`

To make a diagnosis of the problem I followed the request trace and stopped in Symfony Request file (Symfony\Component\HttpFoundation\Request.php). On function "get" the $key passes by all verifications and return the default value (which is null for me)

```
public function get($key, $default = null)
    {
        if ($this !== $result = $this->attributes->get($key, $this)) {
            return $result;
        }

        if ($this !== $result = $this->query->get($key, $this)) {
            return $result;
        }

        if ($this !== $result = $this->request->get($key, $this)) {
            return $result;
        }

        return $default;
    }
```

Maybe the library is trying to understand an octal value instead of integer? I can't change my business rule (for example change from integer to a string on payload). What's the best way to fix this situation?

### Steps To Reproduce:
Make a request for a `PUT` endpoint with a integer field in body.
Pass a value starting with 0 (example: 0255)
Try to receive this value on controller with the Request library (vendor/symfony/http-foundation/Request.php)

**Comment by driesvints** [comment]
Octal values in JSON are invalid: https://stackoverflow.com/questions/27361565/why-is-json-invalid-if-an-integer-begins-with-0

In any case you can use the `json` method or `input` method to retrieve JSON values. See "Retrieving JSON Input Values" here: https://laravel.com/docs/5.7/requests#retrieving-input
