### ISSUE TITLE
Laravel Auth facade not working after changing the tenant database in login process

### ISSUE THREAD

**Issue by ani-m** [laravel/framework#26609]
When I am changing the database dynamically during login process, Auth facade do not understand it and always taking the user from default database. All things are working except Auth facade. This is the function for changing the tenant db

```php
function setDBConnection($params){

    config(['database.connections.tenant' => [

        'driver'   => $params['driver'],
        'host'     => $params['host'],
        'database' => $params['database'],
        'username' => $params['username'],
        'password' => $params['password'],
        'charset'  => 'utf8',
        'collation' => 'utf8_unicode_ci',
        'prefix' => '',
    ]]);

    DB::reconnect('tenant');

}
```

and I have in my tenant models

```php
protected $connection = 'tenant';
```

also I am using a middleware for keeping connection. Please help me out, thank you very much!

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by ani-m** [comment]
I tried it, no one can answer, please open, because Auth facade really not working when we change the db during login process. It's always showing the user from default db.

**Comment by driesvints** [comment]
@ani-m can you post the links to the places where you asked this? This may help us debug the problem further.

**Comment by ani-m** [comment]
sure, but no one could answer (
https://laracasts.com/discuss/channels/laravel/laravel-auth-facade-not-working-after-changing-the-tenant-database
https://stackoverflow.com/questions/53456697/laravel-auth-facade-not-working-after-changing-the-tenant-database

**Comment by driesvints** [comment]
Where is this method defined? 

I'll need more info and/or code to debug this further. Please post relevant code like models, jobs, commands, notifications, events, listeners, controller methods, routes, etc. You may use https://paste.laravel.io to post larger snippets or just reply with shorter code snippets. Thanks!

**Comment by ani-m** [comment]
Thank you. Let me describe in more detail.
These are my databases
db_main (here I store companies with their db info)
db_company1,
db_company2
...
etc.
db_tenant (this is not used db, just a copy  from db_company1)
I create the tenant DBs during registration process.
And this is my login method
`
   public function login(Request $request)
    {
        $this->validateLogin($request);
        $userOnFirst = AllUsers::where('email',$request->email)->with('company')->first();
        if($userOnFirst){
            setDBConnection([
                'driver'   => 'mysql',
                'host'     => $userOnFirst->company->db_host,
                'database' => $userOnFirst->company->db_name,
                'username' => $userOnFirst->company->db_user,
                'password' => $userOnFirst->company->db_pass,
            ]);
            if ($this->attemptLogin($request)) {
                return $this->sendLoginResponse($request, $userOnFirst);
            }
        }
        return $this->sendFailedLoginResponse($request);
    }
`
setDBConnection is a helper method registered in autoload.
here it is
`
      function setDBConnection($params){
        config(['database.connections.tenant' => [
            'driver'   => $params['driver'],
            'host'     => $params['host'],
            'database' => $params['database'],
            'username' => $params['username'],
            'password' => $params['password'],
            'charset'  => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix' => '',
        ]]);
        DB::reconnect('tenant');
    }
` 
In my database config I have 
`
 'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'), 
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'tenant' => [
            'driver'    => 'mysql',
            'host'      => env('DB_HOST', 'localhost'),
            'database'  => env('DB_DATABASE_TENANT', 'forge'), // here is the db_tenant database
            'username'  => env('DB_USERNAME_TENANT', 'forge'),
            'password'  => env('DB_PASSWORD_TENANT', ''),
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
        ],
`
In my tenant models I have 
`
  protected $connection = 'tenant';
`
In my routes I have
` 
   Route::group(['middleware' => ['tenantConnectDB', 'auth']], function () {
 `

also I put here links for whole LoginController, TenantConnectDB middleware, and Company model
LoginController - https://paste.laravel.io/fork/b77ba624-bbe5-49df-bd07-9756819e8828
TenantConnectDB middleware - https://paste.laravel.io/fork/ede81dd0-6b7e-4291-b48a-dd4f64f14ebf
Company model - https://paste.laravel.io/fork/76c89e5d-b8e7-4ad2-be85-63228c45732a

The issue
When we login if you type this ` dd(Auth::user()); `  in any controller, you will see the user from db_tenant (the default) database instead from changed database, but user id is right, and it will not login if you do not have user in db_tenant db with same id as your user in the tenant companies database.
Thank you very much!

**Comment by driesvints** [comment]
So what I suspect is happening is that changing the DB connection ad-hoc isn't going to work like this. 

Btw I noticed you're using `DB::reconnect('tenant');` in the example above but it's not added in the example LoginController from your paste.

I'm going to have to close this as I suspect that this isn't a bug but just a wrong sequence of steps. I don't have time to deep dive into your code at the moment so I suggest you keep on trying one of the support channels above. Especially try the Discord or Larachat channels as they're usually the fastest ways to get support.

**Comment by devcircus** [comment]
Try hitting up @tomschlick on Twitter at https://twitter.com/tomschlick to follow up. He's one of the Laravel multi tenant gurus.

**Comment by ani-m** [comment]
> Btw I noticed you're using `DB::reconnect('tenant');` in the example above but it's not added in the example LoginController from your paste.

how it's not added, it is added in setDBConnection helper and that helper is added in login method.

**Comment by driesvints** [comment]
@ani-m nvm, my bad.
