### ISSUE TITLE
Test data disappears after loading or refreshing eloquent models from the database

### ISSUE THREAD

**Issue by elimentz** [laravel/framework#26602]
- Laravel Version: 5.7.14
- PHP Version: 7.2.12
- Database Driver & Version: MariaDB 10.2.15

### Description:
We use PHPunit for unit testing. A lot of out tests rely on database testing. We use factories to enter data into the database that we can later use in our tests. This has worked for more than a year, but fails since we upgraded to Laravel 5.7.14. 

Creating the models itself is not the problem. However, the problem occurs when we run a `load()` function or a `refresh()` on an existing relationship of a model. Suddenly, the data that exists within that relationship has disappeared, which causes nullpointers in out tests. If I revert back to Laravel 5.7.13, everything works as intended

### Steps To Reproduce:
 - Install laravel 5.7.14
 - Create 2 models with an eloquent relationship between them
 - Create phpunit test 
 - Prefill a database with data, including the relationship
 - Perform a `$this->load('relationshipName')` or `$this->refresh()` on the model during the unit test
 - Run the unit test

**Comment by driesvints** [comment]
I'll need more info and/or code to debug this further. Please post relevant code like models, jobs, commands, notifications, events, listeners, controller methods, routes, etc. You may use https://paste.laravel.io to post larger snippets or just reply with shorter code snippets. Thanks!

**Comment by elimentz** [comment]
Model 1:
```
class Subscription extends Model
{
    use HasPayments;
}
```

Model 2:
```
class Payment extends Model
{
    public function payable(): MorphTo
    {
        return $this->morphTo();
    }

    public function invoice(): HasOne
    {
        return $this->hasOne(Invoice::class);
    }
}
```

Model 3:
```
class Invoice extends Model
{
    public function payment(): BelongsTo
    {
        return $this->belongsTo(Payment::class);
    }

    public static function createFromSubscription(Subscription $subscription): Invoice
    {
        $payment = $subscriptionPeriod->payment->refresh(); // Nullpointer occurs here

        $invoice = new Invoice();
        $invoice->payment_id = $payment->id;
        $invoice->save();

        return $invoice;
    }
}
```

Trait with relationship:
```
trait HasPayments
{
    public function payments(): MorphMany
    {
        return $this->morphMany(Payment::class, 'payable');
    }

    public function getPaymentAttribute(): ?Payment
    {
        $this->load('payments');

        return $this->payments->first();
    }
}
```

Unit test:
```
class MarkAsPayedTest extends TestCase
{
    /** @var Invoice */
    protected $invoice;

    /** @var \App\Models\Payment */
    protected $payment;

    public function setUp()
    {
        parent::setUp();

        $subscription = factory(Subscription::class)->create();

        $this->payment = PaymentFactory::createForPayable($subscription,1000);
        $this->payment->save();

        $subscription->payments()->save($this->payment);

        $this->invoice = Invoice::createFromSubscription($subscription);
    }

    /** @test */
    public function cannot_mark_as_payed_as_normal_user()
    {
        $user = factory(User::class)->create();

        $this->logInToApi($user);

        $this
            ->json('PATCH', "/api/invoices/{$this->invoice->id}/mark-as-payed")
            ->assertStatus(403);
    }
}
```

Like I said, all of this is old code, hasn't changed in weeks.

**Comment by fitztrev** [comment]
Are you using UUIDs by chance? on the Payment model?

If so, there was a change in 5.7.14 that would affect you too: #26582

**Comment by JorisDR** [comment]
yes,  $table->uuid('id'); $table->primary('id');

**Comment by driesvints** [comment]
Please check the other issue. You'll need to define a `$keyType` property.

@elimentz do you also have defined a UUID for your models?

**Comment by elimentz** [comment]
We're working on the same app, lol. Will check if that fixes the problem and get back to you ;-)

**Comment by elimentz** [comment]
Resolved. Thanks for the support
