### ISSUE TITLE
Doing Eloquent mass update sometimes changes updated_at, sometimes not

### ISSUE THREAD

**Issue by dsandber** [laravel/framework#26608]
- Laravel Version: 5.4
- PHP Version:
- Database Driver & Version:

### Description:

```
Model::getQuery()->update(['field' => 'value']);
```

Will NOT set updated_at, while doing:

```
Model::whereIn('id', !=, 0)->update(['field' => 'value']);
```

Will set updated_at. This is surprising behavior as a user would assume that updated_at is always set or always not set.

**Comment by staudenmeir** [comment]
Use `query()` instead of `getQuery()`:

```php
Model::query()->update(['field' => 'value']);
```

**Comment by dsandber** [comment]
Thanks for the explanation!

Curious, why does a "base query builder" have different behavior regarding updated_at than an "Eloquent query builder"?

This is some pretty counter-intuitive stuff imho.  Never would have guessed that query() vs. getQuery() vs. whereIn() would yield different results as far as updated_at updating.

**Comment by staudenmeir** [comment]
The base query builder doesn't and shouldn't know anything about models or timestamps. It only updates the columns you specify (i.e. `field`).

I've never seen anyone stumbling over this. Did you read about `getQuery()` somewhere or just try it?

**Comment by dsandber** [comment]
Not sure where I found getQuery -- either SO or looking at Laravel source code I would assume.

The documentation doesn't seem to mention query() or getQuery(), so it's not obvious how you're supposed to do an operation like "update" when you don't want to have any where/WhereIn/... clause.

Will close since this getQuery() vs query() vs whereIn behavior is by design.  Thanks!
