### ISSUE TITLE
Default format for eloquent attribute casting with type "date" should be Y-m-d

### ISSUE THREAD

**Issue by isometriq** [laravel/framework#26605]
- Laravel Version: 5.6.11
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.6

### Description:
I have a `date` type field in a MySQL table, named `my_date_only_field`
When attribute casting in eloquent models like so:
```
$cast = [
    'my_date_only_field' => 'date',
];
```
The date is formatted with time values `Y-m-d H:i:s`. It may seem an inconvenience and could written like so:
```
$cast = [
    'my_date_only_field' => 'date:Y-m-d',
];
```
However, I feel this this is a bug as it should be formatted like the native storage format by default.

Maybe it's too database specific, but a `SELECT my_date_only_field FROM my_table LIMIT 1` will yield a date formatted as `Y-m-d`.

Moreover in the docs (https://laravel.com/docs/5.6/eloquent-mutators) there is support for `date` AND `datetime`. In that regard `date` should have the default format `Y-m-d`.

### Steps To Reproduce:
1. Create a field of type `date`
2. Use the casting example above in a model for that field
3. `dd($model->first()->toArray());` ..or whatever output triggering "casting"
4. Note the `my_date_only_field` field is formatted with time values

**Comment by driesvints** [comment]
Heya, unfortunately we don't support that version anymore. Can you update to Laravel 5.7 and check if the problem persists? If so feel free to reply and I'll reopen!

**Comment by rimas-kudelis** [comment]
Looking at [the code](https://github.com/laravel/framework/blob/5.7/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L744), this still seems to be the case.

However, [it also appears](https://carbon.nesbot.com/docs/#api-formatting) that per-instance format for `__toString` is only supported in Carbon 2, and Laravel still uses Carbon 1.
