### ISSUE TITLE
Hash round setter actually sets cost factor.

### ISSUE THREAD

**Issue by c-edw** [laravel/framework#26617]
[`BcryptHasher::setRounds`](https://github.com/laravel/framework/blob/1ca55a1e5c2c0d3ba853998f1781cfa23bb9a646/src/Illuminate/Hashing/BcryptHasher.php#L97) sets the protected member `$rounds`, which is later used in [`BcryptHasher::cost`](https://github.com/laravel/framework/blob/1ca55a1e5c2c0d3ba853998f1781cfa23bb9a646/src/Illuminate/Hashing/BcryptHasher.php#L110) as a cost factor.

If I'm not mistaken, hashing rounds and hashing cost are different parameters and shouldn't be used interchangeably. I would like to submit a PR to change this, but I would like confirmation of this first.

Thanks.

**Comment by driesvints** [comment]
Bcrypt specifically uses a number of rounds to determine its cost so the terminology here is correct.

**Comment by c-edw** [comment]
According to one of the answers on [this](https://security.stackexchange.com/questions/17207/recommended-of-rounds-for-bcrypt) Stack Exchange post, cost can be computed from rounds using the formula:

```
R = 64 × 2(156/18)
R = 64 × 28.66
R = 64 × 406.8
R = 26,035.2

cost = ln(R) / ln(2)
cost = ln(26,035.2) / ln(2)
cost = 14.7
```

Where `R` is iterations (rounds).

[See also](https://security.stackexchange.com/questions/139280/how-many-bcrypt-rounds-are-necessary)

**Comment by driesvints** [comment]
Hey @c-edw. If you believe we should have another look at how we compute rounds it's best to make a suggestion in the [laravel/ideas](https://github.com/laravel/ideas) tracker.
