### ISSUE TITLE
Uncaught ReflectionException: Class env does not exist

### ISSUE THREAD

**Issue by kadinho** [laravel/framework#26627]
- Laravel Version: 5.7.15
- PHP Version: 7.2.12
- Database Driver & Version: Mariadb 10.2

### Description:

`PHP Fatal error:  Uncaught ReflectionException: Class env does not exist in /var/www/project/vendor/laravel/framework/src/Illuminate/Container/Container.php:779
Stack trace:
#0 /var/www/project/vendor/laravel/framework/src/Illuminate/Container/Container.php(779): ReflectionClass->__construct('env')
#1 /var/www/project/vendor/laravel/framework/src/Illuminate/Container/Container.php(658): Illuminate\Container\Container->build('env')
#2 /var/www/project/vendor/laravel/framework/src/Illuminate/Container/Container.php(609): Illuminate\Container\Container->resolve('env', Array)
#3 /var/www/project/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(735): Illuminate\Container\Container->make('env', Array)
#4 /var/www/project/vendor/laravel/framework/src/Illuminate/Container/Container.php(1222): Illuminate\Foundation\Application->make('env')
#5 /var/www/project/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(485): Illuminate\Container\Container-> in /var/www/project/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 779
`

### Steps To Reproduce:

`php artisan`

I followed the upgrade guide, maybe i missed something, i think not.

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

Also check the issue tracker if your issue can be found somewhere here: https://github.com/laravel/framework/issues?q=is%3Aissue+Class+env+does+not+exist+is%3Aclosed

Are you using Telescope? Is this the problem you're experiencing? https://github.com/laravel/telescope/issues/347

**Comment by kadinho** [comment]
yes, im using Telescope. Tx!

**Comment by stonkeep** [comment]
I've runned
`php artisan clear
php artisan config:clear
`
Solved for me

**Comment by nakov0301** [comment]
For someone still having the issue, it can be solved adding 

`<server name="TELESCOPE_ENABLED" value="false"/>` in `phpunit.xml`.

**Comment by nezaboravi** [comment]
Put it together:
<server name="TELESCOPE_ENABLED" value="false"/>
php artisan optimize

**Comment by webornottoweb** [comment]
I'm not using **telescope** package, but i've received the same exception on every `php artisan` call.
I didn't understand what code block crashes.
Over internet there are many resolutions with cache cleaning. Those users received the same message while running `phpunit` command.
I've tried to run `phpunit` and received an error related to configuration of one of packages that i've used. So I fixed package config problem and `phpunit` command runs well. Also, `php artisan` runs OK for now. 
Hope my solution will be useful to someone.

**Comment by andreshg112** [comment]
I had the same problem after upgrading with `composer update`. I had to downgrade. Nothing above worked for me.

**Comment by mrFANRA** [comment]
Some problem after upgrading from 6 to 7 version

**Comment by ProteanCode** [comment]
Lumen, upgrading from
  - Updating laravel/framework (v8.14.0 => v8.18.1): Downloading (100%)         
  - Updating laravel/lumen-framework (v8.2.0 => v8.2.1): Downloading (100%)

**Comment by TracKer** [comment]
If you are upgrading to Laravel 6, the problem may be in the missing `str_slug` function in configs, replace it with `Str:slug()`

**Comment by abinrimal** [comment]
> For someone still having the issue, it can be solved adding
> 
> `<server name="TELESCOPE_ENABLED" value="false"/>` in `phpunit.xml`.

Where can we find this, I don't have phpunit.xml file anywhere in my files.

**Comment by athamidn** [comment]
put dd($exception); in App\Exceptions\Handler::report() 
 It give you a better error message.
 there was an error in filesystem config for me!

**Comment by heathyboyj** [comment]
@athamidn Super star, thanks! This was tripping me up too; was referencing a constant in my config files defined in a database seeder (which had changed to being namespace in a laravel 8 update).

**Comment by munnavar** [comment]
I faced this issue and found issue in *config* folder > constants file
I was wrote "asset('/')" function in config file, we can't write such functions in config.

Hope this answer  will some one who stuck like this errors.

**Comment by agustindelgadillo** [comment]
> put dd($exception); in App\Exceptions\Handler::report()
> It give you a better error message.
> there was an error in filesystem config for me!

Thanks so much for everything, I was frustrated 🍡

**Comment by vinodraut** [comment]
> put dd($exception); in App\Exceptions\Handler::report() It give you a better error message. there was an error in filesystem config for me!

Really usefull ... thanks man

**Comment by frknasir** [comment]
> What I found: if you changed your config/app.php or any file under config/ and use something that don't exists (ie, refering to a non-existing class, forgetting to use "::class" to refering to a class, don't separating array keys with ",", and so on) you'll face this error. Double check if your files have any errors

You, Sir - are a life saver!!!

**Comment by thamibn** [comment]
> put dd($exception); in App\Exceptions\Handler::report() It give you a better error message. there was an error in filesystem config for me!

super thanks man

**Comment by statstical-anomaly** [comment]
> put dd($exception); in App\Exceptions\Handler::report() It give you a better error message. there was an error in filesystem config for me!

Everyone should try this. In my case the error was due to a stray character in one of my config file messing with parsing.
I fixed it and the error was gone
This was the actual error in my case
> ^ ParseError {#148
  #message: "syntax error, unexpected '[', expecting ']'"
  #code: 0
  #file: "./config/adminlte.php"
  #line: 250
  trace: {
    ./config/adminlte.php:250 {

**Comment by jambu43** [comment]
I solved the same by updating the composer

`composer update`

**Comment by dvsolodov** [comment]
Helped me
`composer install`

**Comment by syofyanzuhad** [comment]
My sentry tell me the error becouse of this line:
![Screenshot from 2022-01-19 17-42-59](https://user-images.githubusercontent.com/52684582/150114951-0d93a20b-89e9-45d5-8e1a-09b1ea57191e.png)

I just changing my `TelescopeServiceProvider` file from this
```php
Telescope::filter(function (IncomingEntry $entry) {
            if ($this->app->environment('local') || config('telescope.enabled', false)) {
                return true;
            }

```

to this one:
```php
Telescope::filter(function (IncomingEntry $entry) {
            if (config('app.env')=='local' || config('telescope.enabled', false)) {
                return true;
            }
```

**Comment by michabbb** [comment]
just for the docs: this error also can happen if you put code inside a config file like `/config/links.php` like:

```php
return [
  'link' => route('home').'/something.html'
];
```

**Comment by nisbeti** [comment]
A silly typo in a core config file can even cause this issue. e.g. a php syntax error in config/session.php

**Comment by alexw23** [comment]
> put dd($exception); in App\Exceptions\Handler::report() It gives you a better error message. there was an error in filesystem config for me!

This was a life saver!

**Comment by ghostza1209** [comment]
> put dd($exception); in App\Exceptions\Handler::report() It gives you a better error message. there was an error in filesystem config for me!

This helped me!
