### ISSUE TITLE
Laravel + Vitess Compatibility

### ISSUE THREAD

**Issue by hellracer** [laravel/framework#26621]
Vitess is a database clustering system for horizontal scaling of MySQL (born at youtube)

In order for us to connect our framework to vitess we can disable sending this construct
set this option first.
```
'options' => array(
                PDO::ATTR_EMULATE_PREPARES => true
             ),
vitess => true,
```

then code change on src/Illuminate/Database/Connectors/MySqlConnector.php

```protected function setModes(PDO $connection, array $config)
    {
        if (isset($config['modes'])) {
            $this->setCustomModes($connection, $config);
        } elseif (isset($config['strict'])) {
            if ($config['strict']) {
                $connection->prepare($this->strictMode($connection))->execute();
            } else {
                if(!$config['vitess'])
                $connection->prepare("set session sql_mode='NO_ENGINE_SUBSTITUTION'")->execute();
            }
        }
  }

**Comment by driesvints** [comment]
Heya, thanks for submitting this. This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

**Comment by hellracer** [comment]
Actually though it's really a feature request, my question is if you set the modes => null it shouldn't 
execute ``` $connection->prepare("set session sql_mode='NO_ENGINE_SUBSTITUTION'")->execute();```

**Comment by driesvints** [comment]
@hellracer Sorry but I still consider this to be a feature request so please open up an issue at the ideas repo.
