### ISSUE TITLE
[5.7] SVG upload extension missing

### ISSUE THREAD

**Issue by adminko** [laravel/framework#26626]
- Laravel Version: 5.7.14
- PHP Version: 7.2
- Database Driver & Version: MySQL 5.7

### Description:
When i try to upload & store svg file, Laravel response me filename without extension

### Steps To Reproduce:

1. on frontend create multipart form with file input with name testme
2. on backend try to store it with `$filename = $request->testme->store('somwhere')`
3. try to get filename by `basename($filename)`

Expected result: RANDOM_HASH_NAME.svg
Actual result: RANDOM_HASH_NAME.

**Comment by driesvints** [comment]
Please see https://github.com/laravel/framework/issues/26511
