### ISSUE TITLE
Laravel should NOT delete all my nginx configs!

### ISSUE THREAD

**Issue by argb** [laravel/framework#26629]
~/Homestead/scripts/clear-nginx.sh

#!/usr/bin/env bash
  
   # Clear The Old Nginx Sites
  
   rm -f /etc/nginx/sites-enabled/*
   rm -f /etc/nginx/sites-available/*

Please don't! 
I suddenly lost all my own custom sites configs, includes some reverse-proxy conf, but I don't know WHY, finally i found the murderer Laraval Homestead Script!

You can clear those confs which exist in Homestead.yml, but don't clear all, the vagrant machine  serve not only laravel sites.

**Comment by browner12** [comment]
If you have a suggestion for Homestead you can open it in https://github.com/laravel/homestead

**Comment by driesvints** [comment]
Please open up an issue with the Homestead repo for this like @browner12 suggested.
