### ISSUE TITLE
[Regression]: parseJsonWhilePreservingEmptyObjects(): ErrorException : Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by LastDragon-ru** [laravel/framework#26624]
- Laravel Version: v5.7.14
- PHP Version: 7.2

### Description:

The `parseJsonWhilePreservingEmptyObjects()` was added in #26353 and after is not possible to test controllers that returns primitive types. Saddly :(

### Steps To Reproduce:

```php
<?php
    /**
     * @dataProvider testJsonPrimitiveTypesSupportsDataProvider
     */
    public function testJsonPrimitiveTypesSupports($value)
    {
        $response = new TestResponse(new JsonResponse($value));

        $this->assertSame($value, $response->json());
    }

    public function testJsonPrimitiveTypesSupportsDataProvider() {
        return [[true], [false], ['string'], [123], [null]];
    }
```

All these values are valid json response. In v5.7.13 `true`, `string`, `123` are valid response (= work and you can test it), `false`/`null` not (but IMHO this is a bug too), since v5.7.14 tests with `true`, `string`, `123` will fail with "Invalid argument supplied for foreach()" (this is regression).

### Desired functionality

Should be possible returned and test primitive types.

**Comment by lesterchan** [comment]
Weird, I am seeing this issue on 5.7.15 instead on 5.7.14

**Comment by driesvints** [comment]
As suggested in the closed pr try `$response->original`
