### ISSUE TITLE
Class 'Fideloper\Proxy\TrustProxies' not found

### ISSUE THREAD

**Issue by razigohar** [laravel/framework#26638]
- Laravel Version: 5.7
- PHP Version:7.2
- Database Driver & Version:

### Error:
I installed the Lavacharts library but after installing i am facing this error

> Class 'Fideloper\Proxy\TrustProxies' not found
Kindly help me in this situation.

Thanks in advance

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by driesvints** [comment]
@razigohar it's probably best to ask this on their repo
