### ISSUE TITLE
SomeModel::getQuery()->...->get() returns array instead of stdClass

### ISSUE THREAD

**Issue by tomlankhorst** [laravel/framework#26641]
- Laravel Version: 5.7.14
- PHP Version: 7.2
- MariaDB 10.3

Normally, retrieving results from the query builder results in either a `stdClass` or a collection of them. 
However, specifically on a **queue worker** and always an amount of time varying from a minute to a couple of hours, the query builder starts to return `array`s instead of `stdClass`es. 

This sounds pretty strange, I suppose, so here's a sample that produces the issue. 

```php
$entries = SomeModel::getQuery()
    ->select([
        // ... select statements 'tbl.col AS my_col'
    ])
    // joins, wheres, orderby, limit
    ->get()
    ->keyBy('my_col');

// Always successful
assert($entries instanceof Collection);

$first = $entries->first();

// Succesfull at first but fails after time...
assert($first instanceof stdClass);
```

To me, it feels like there is something messing with the database fetch method... do you have an idea what might be going on?

**Comment by tomlankhorst** [comment]
Suspecting it might have something to do with an event listener placed by the Laravel-Excel module: 
```php
Event::listen(StatementPrepared::class, function ($event) {
  $event->statement->setFetchMode(\PDO::FETCH_ASSOC);
});
```

**Comment by tomlankhorst** [comment]
This is indeed due to a package registering an event handler on the `StatementPrepared` event. 
Having said that, should it be possible to register anything on that event at all? Seems like that would influence the behaviour of the QueryBuilder.

**Comment by devcircus** [comment]
If I'm remembering correctly, I think this was documented a few versions ago when the fetchMode was changed to the current hardcoded value. It leaves a way for edge cases to make the change.
