### ISSUE TITLE
`Model::toArray` recomputing the accessor

### ISSUE THREAD

**Issue by thiagof** [laravel/framework#26646]
- Laravel Version: master
- PHP Version: 7
- Database Driver & Version: any

### Description:
What I expect from the `toArray` call is to preserve my model mutation state and it does not.

Say I have a model that sets a value: `$user->isTall = true`. When `toArray` is called it does not respect my decision on the model and instead try to recompute the attribute in a blind way (calling `getIsTallAttribute(null)` instead of passing my `true` definition).

The code that does this call is here:
https://github.com/laravel/framework/blob/b24870a0e1fd9daefcd885abecd1a6f727b64a9b/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L109

It recomputes the mutated value and is virtually impossible to persist on-the-fly changes to the model.

I wonder how that performs on expensive computations. Imagine a script has worked on many models and set its state

```
	public function getExpensiveAttribute($value) {
		if (!$value) {
			$value = ExpensiveRepository::compute();
			$this->attributes['expensive'] = $value;
		}
		return $value;
	}
```

Normally I only touch the DB or computations once per request, but `toArray` will recompute my whole dataset.

Is that intended? Why? @taylorotwell

**Comment by driesvints** [comment]
This is indeed intended. Mutators are meant to overwrite any dynamic properties that were set.

**Comment by thiagof** [comment]
I understand. The question is how the difference between `__get` and `toArray` influences the coder (if not the system) experience.
I saw the topic had some debate and development over time but still not 100% clear in my opinion.

**Comment by driesvints** [comment]
@thiagof think it's best to discuss this on Discord or Larachat
