### ISSUE TITLE
When I run phpunit I get this error: Parse error: syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in C:\code plearning\codeEcom\vendor\symfony\var-dumper\Resources\functions\dump.php on line 18

### ISSUE THREAD

**Issue by rakeshshubhu** [laravel/framework#26649]
- Laravel Version: 5.7.*
- PHP Version:7,1,7
- Database Driver & Version:

### Description:
I've installed a new project to learn some unit tests. But i get parse error. I was expecting some kind of unit test errors. Why am I getting this error is it some kind of error because of my php version? I'm using IIS as a server.

**Comment by staudenmeir** [comment]
What's the result of `php -v` on the command line?

**Comment by rakeshshubhu** [comment]
7.1.7(cli)

**Comment by rakeshshubhu** [comment]
On my phpunit.xml i have done something like this .   <php>
        <env name="APP_ENV" value="testing"/>
        <env name="BCRYPT_ROUNDS" value="4"/>
        <env name="CACHE_DRIVER" value="array"/>
        <env name="DB_DATABASE" value="cart_testing"/>
        <env name="MAIL_DRIVER" value="array"/>
        <env name="QUEUE_CONNECTION" value="sync"/>
        <env name="SESSION_DRIVER" value="array"/>
    </php>

**Comment by rakeshshubhu** [comment]
On my phpunit.xml file I have done something like this.
`  <php>
        <env name="APP_ENV" value="testing"/>
        <env name="BCRYPT_ROUNDS" value="4"/>
        <env name="CACHE_DRIVER" value="array"/>
        <env name="DB_DATABASE" value="cart_testing"/>
        <env name="MAIL_DRIVER" value="array"/>
        <env name="QUEUE_CONNECTION" value="sync"/>
        <env name="SESSION_DRIVER" value="array"/>
    </php>`

**Comment by sisve** [comment]
The line in question is `function dump($var, ...$moreVars)` which indicates you have a problem with the variadic function declaration. This means you're using an old version of PHP. The exact error message was in used for PHP 5.4 and 5.5, which can be shown on [3v4l](https://3v4l.org/l07sN).

Your IIS is configured to use an outdated PHP version. This version is not the same as the one you run in your command line.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
