### ISSUE TITLE
419 response after updating session driver to database

### ISSUE THREAD

**Issue by Xerotherm1c** [laravel/framework#26658]
- Laravel Version: 5.7.15
- PHP Version: 7.2.2-1+ubuntu16.04.1+deb.sury.org+1
- Database Driver & Version: mysql 14.14 Distrib 5.7.21, for Linux (x86_64) using EditLine wrapper

### Description:

I'm developing on a vagrant homestead box v6.3.0 and I updated the session driver from `file` to `database`. I have already migrated the `sessions` table as instructed in the docs. When I try to log in (I've already used `make:auth`), I'm receiving a 419 error. The form uses `@csrf` and works fine if I revert the session driver to `file`. I upgraded my vagrant box to v6.4.0 with the same results.

### Steps To Reproduce:

1. Migrate `sessions` table
2. Set `SESSION_DRIVER=database` in `.env`

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
