### ISSUE TITLE
Controllers validate method returns converted keys 

### ISSUE THREAD

**Issue by nicoeg** [laravel/framework#26651]
- Laravel Version: 5.7
- PHP Version: 7.*
- Database Driver & Version: Not used

### Description:
When having request input arrays which keys contains `.` it is converted to `->` when using data returned from the `validate` method in a Controller. 

Since [#25128](https://github.com/laravel/framework/pull/25128) the [Illuminate\Foundation\Validation\ValidatesRequests::validate](https://github.com/laravel/framework/blob/b0013a2006a5bff60b845a72ba66e9dd994aa846/src/Illuminate/Foundation/Validation/ValidatesRequests.php#L42) method returns the input data directly from the validator instead of fetching it from the request. This means that the `str_replace` done in [Illuminate\Validation\Validator:parseData](https://github.com/laravel/framework/blob/b0013a2006a5bff60b845a72ba66e9dd994aa846/src/Illuminate/Validation/Validator.php#L222) to convert `.` to `->` is also returned.

I don't believe that this is expected behaviour.
Possible solution would be to convert back `->` before returning but then existing input keys containing `->` would also be affected. 
Either the `validate` method could be changed back to fetch data from the request or the dot's should be replaced with something less likely of occurring?

### Steps To Reproduce:
Basic controller:
```php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class TestController extends Controller
{
    public function index(Request $request) {
        $validated = $this->validate($request, ['*' => 'required']);
        return $validated;
    }
}
```
Route: 
```php
Route::get('/', 'TestController@index');
```
Go to the page with the following query string `?nested[config.conf]=gsdggdfg`

**Comment by driesvints** [comment]
We don't support dot notation in keys anymore sorry.
