### ISSUE TITLE
Eloquent\Builder::getModels() retrieves soft-deleted entries without being told to

### ISSUE THREAD

**Issue by dinamic** [laravel/framework#26655]
- Laravel Version: 5.6.33
- PHP Version: 7.2.8
- Database Driver & Version:

### Description:

Manually constructing a query and running it via `->getModels()` returns the soft-deleted entries while not instructed to. The cause seem obvious - `getModels()` does not call `$builder->applyScopes()`.

On top of that, getting the sql query returns the query with soft-delete filter applied, misleading you that `getModels()` uses the same query, while this is not the case.

### Steps To Reproduce:

1. have a soft-deletable model
2. create one entry and soft-delete it 
3. query all items
4. verify that `getModels()` does return soft-deleted entries

```
$entries = Models\MyModel::where(function(Builder $query){});
var_dump($entries->getModels());

$entries = Models\MyModel::where(function(Builder $query){});
var_dump($entries->get());
```

**Comment by dinamic** [comment]
I maybe misusing the `getModels()` method there. If this is the case, please, spare the hate speech and explain why it is there and what's the goal behind the implementation.

**Comment by staudenmeir** [comment]
Why are you using `getModels()` instead of `get()`?

**Comment by dinamic** [comment]
@staudenmeir, I can't remember the use case, but it had something to do with different hydration strategies. As mentioned before, I might have used the wrong method.

Help me understand the problem.

1. What are the use cases of `getModels()`?
2. Do they require soft-deleted entries to be returned without explicitly instructed to?

**Comment by staudenmeir** [comment]
I don't any reason to call `getModels()` in your application. It's basically a helper method that `get()` uses internally.

**Comment by dinamic** [comment]
@staudenmeir if it's not intended to be used by the outside world, shouldn't it be private?

**Comment by driesvints** [comment]
`getModels` isn't really meant to be used directly that's why it's not documented. It's public because the places where the framework calls it need to be able to do access it.
