### ISSUE TITLE
Translation error: htmlspecialchars() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by applyACS** [laravel/framework#26664]
- Laravel Version: 5.7.15
- PHP Version: 7.2.5
- Database Driver & Version: Postgres

### Description:
When using both json translations and php files, if a php translated file exists with the name of a key that we want to use and the key is not translated in the json file, it does not return the untranslated text but returns an array with the translations from the php file, even if the translated key does not have dots in it's name, giving us this error:
```Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: htmlspecialchars() expects parameter 1 to be string, array given```

### Steps To Reproduce:

It's easy to test
Create a translation file called documents.php in your lang folder for example, with some strings in it
Here's a simple one for documents.php. Also, make sure that in your json file the key "Documents" is not present/translated.
```
<?php

return [
    'document_type'     => [
        '10' => 'Seller',
        '20' => 'Agent',
    ];
```
Now, if anywhere in your template you try to display a translation using the name of the file, for eg ```{{ __('Documents') }}``` or ```{{ __('documents') }}``` it will give you this error since it returns the translations as an array. This is a bug as it should only return the translation array only if you have a dot ```.``` in the translated string, otherwise it should look it up in the json file.
So, ```{{ __('documents.document_type.10') }}``` should take the translation from the php file while ```{{ __('documents') }}``` should take it from the json

**Comment by driesvints** [comment]
We've recently decided to now modify the behavior of this helper to only return strings so unfortunately this is a no-fix.

**Comment by matejvelikonja** [comment]
This is still happening in the L6.10.

Is there at least some kind of workaround for this issue, if you have decided not to fix it. This bug makes translations break a lot.

**Comment by driesvints** [comment]
@matejvelikonja not that I know of

**Comment by matejvelikonja** [comment]
In my opinion this is a big bug. It's really weird that community decided not to fix it. And it's here for more than a year.

**Comment by 36864** [comment]
Related discussion: #30666

**Comment by driesvints** [comment]
@36864 thanks, I was just looking for that. @matejvelikonja please take a look at the discussion there to see why we decided to leave things be.
