### ISSUE TITLE
Сannot run a command without arguments

### ISSUE THREAD

**Issue by VokaMut** [laravel/framework#26667]
- Laravel Version: 5.6.38
- PHP Version: 7.1.23
- Database Driver & Version: nope

### Description:
My command:
```
namespace App\Console\Commands\App;

use Illuminate\Console\Command;

class Test extends Command
{
    protected $signature = 'app:test';
    public function handle()
    {
        $this->info('Test command!');
    }
}
```

When run command in another command:
`Artisan::call('app:test', ['--quiet']);` // Error: The "1" argument does not exist.
`$this->call('app:test', ['--quiet']);` // Test command!

When run in commandline: `php artisan app:test --quiet` I have empty output.

But:
```
    protected $signature = 'app:test {tmp=null}';
```
`Artisan::call('app:test', ['--quiet']);` // Empty output
`$this->call('app:test', ['--quiet']);` // Test command!

**Comment by driesvints** [comment]
The difference is that the call method in a console command is a different one than the call method from the facade which is present in the `Illuminate\Console\Application` class. If you believe these behaviors should be made similar it's best to open an issue in the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.
