### ISSUE TITLE
Eloquent::insertMany() or similar method for multiple inserts setting defaults values like timestamps.

### ISSUE THREAD

**Issue by drnkwati** [laravel/framework#26665]
Developers far back as 2013 have raised issues about inserting many records using eloquent. 
I too came across the need for this as well so am reopening the issues with a suggested solution i have been using. I wish @taylorotwell and developers can consider including in the framework. 
Here in this issue at
https://github.com/laravel/framework/issues/1295
Taylor suggested using the query builder for this. 
Eloquent::insert() does the trick, but the following errors may occur:
1. Un sequenced columns will raise an exception, they must be in the right order for it to work.
2. Timestamps on these records are not set.
Here is my suggested solution:

```php
    /**
     * Insert new records into the database.
     *
     * @param  array  $records
     * @return bool
     */
    public function insertMany(array $records)
    {
        $fillable = array_map(function ($value) {return null;}, array_flip($this->getFillable()));

        foreach ($records as $key => $row) {
            $records[$key] = array_merge($fillable, $records[$key]);
            ksort($records[$key]);
        }

        return static::insert($records);
    }
```

If we can improve this or provide better alternative solution build in eloquent core, that sets any default attributes like timestamps etc. that will be great.
thanks

**Comment by driesvints** [comment]
Heya, thanks for submitting this. This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.
