### ISSUE TITLE
[Proposal] Preview Image Embed

### ISSUE THREAD

**Issue by G3z** [laravel/framework#26668]
[Rendering Email templates](https://laravel.com/docs/5.7/mail#rendering-mailables) in the browser is cool and also [Inline Attachments](https://laravel.com/docs/5.7/mail#inline-attachments) are cool, but it's not possible to render inline attached images when previewing emails.
Would it be possible to use inline attachment when sending the email and a simple base64 when previewing?

**Comment by driesvints** [comment]
Heya, thanks for submitting this. This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.
