### ISSUE TITLE
Method `set` in cache repository does not honor the PSR-16 SimpleCache contract

### ISSUE THREAD

**Issue by plehatron** [laravel/framework#26674]
- Laravel Version: 5.7
- PHP Version: 7.2

### Description:

Class `Repository` implements the [`set` method](https://github.com/laravel/framework/blob/5.7/src/Illuminate/Cache/Repository.php#L217) whose contract is defined in [`Psr\SimpleCache\CacheInterface`](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-16-simple-cache.md#21-cacheinterface). By the contract, return value should be a boolean (true on success and false on failure). Yet, the implementation in the [Repository](https://github.com/laravel/framework/blob/5.7/src/Illuminate/Cache/Repository.php#L217) does not return any value.

Normally, this doesn't cause any problems in Laravel, but it does when using Laravel's cache repository as a dependency in third-party libraries. To illustrate the problem, take a look at the following 
code excerpt (part of the `Manager` class) from [jeremykendall/php-domain-parser](https://github.com/jeremykendall/php-domain-parser) package:

```php
/**
 * Returns true if the refresh was successful
 * @param string     $url the Public Suffix List URL
 * @param null|mixed $ttl the cache TTL
 * @return bool
 */
public function refreshRules(string $url = self::PSL_URL, $ttl = null): bool
{
    static $converter;
    $converter = $converter ?? new Converter();
    $data = json_encode($converter->convert($this->http->getContent($url)));

    return $this->cache->set($this->getCacheKey('PSL', $url), $data, $this->filterTtl($ttl) ?? $this->ttl);
}
```
Injecting Laravel's SimpleCache implementation to the `Manager` class, and calling this method results in a type error because the `set` method's return value is always void, when the expected value is a boolean.

I've checked all the implemented cache stores in Laravel and all of them have the ability to return a success status as a boolean:
- `ApcStore`: uses https://secure.php.net/manual/en/function.apcu-store.php which returns a bool.
- `ArrayStore`: can just return true.
- `DatabaseStore`: uses https://github.com/laravel/framework/blob/master/src/Illuminate/Database/Query/Builder.php#L2542 which returns a bool.
- `FileStore`: uses http://php.net/manual/en/function.file-put-contents.php which returns int on success or false on failure.
- `MemcachedStore`: uses http://php.net/manual/en/memcached.set.php which returns a bool.
- `RedisStore`: uses https://redis.io/commands/setex which returns string "OK" on success.

Ignoring the fact that these return values don't give enough info about the nature of failures when they occur, is there another reason why a return value for methods `set`, `put`, `setMultiple`, `forever` is not a boolean?

**Comment by TBlindaruk** [comment]
@driesvints , can  we close this, since https://github.com/laravel/framework/pull/26726 is merged?

**Comment by TBlindaruk** [comment]
Looks like, that is fixed in https://github.com/laravel/framework/pull/26726
