### ISSUE TITLE
Missing the primary key (id) on the model when using create

### ISSUE THREAD

**Issue by matthijs** [laravel/framework#26673]
- Laravel Version: 5.7.15
- PHP Version: 7.2
- Database Driver & Version: PostgreSQL 11

### Description:
We use uuid as primary key on our models and have $keyType set to 'string' and $incrementing to false. When we try to create the model (using static function create) it fails to set the id on the model. I can confirm that the role is created in the database.

### Steps To Reproduce:
The class in question:
```php
class Role extends Model
{
	use SoftDeletes;

	/**
	 * The "type" of the auto-incrementing ID.
	 *
	 * @var string
	 */
	protected $keyType = 'string';

	/**
	 * Indicates if the IDs are auto-incrementing.
	 *
	 * @var bool
	 */
	public $incrementing = false;

	/**
	 * The attributes that are mass assignable
	 *
	 * @var array
	 */
	protected $fillable = [
		'name', 'display_name', 'description',
	];
}
```
```php
% ./artisan tinker
Psy Shell v0.9.9 (PHP 7.2.9-1 — cli) by Justin Hileman
>>> use App\Model\Acl\Role;
>>> $x = Role::create(['name' => 'testrole', 'display_name' => 'testrole']);
=> App\Model\Acl\Role {#3349
     name: "testrole",
     display_name: "testrole",
     updated_at: "2018-11-29 19:30:45",
     created_at: "2018-11-29 19:30:45",
   }
>>> $x->id
=> null
```

**Comment by staudenmeir** [comment]
What type of column is `id`? What's the `id` value in the database?

**Comment by sisve** [comment]
What's in the database table? Where are the uuids generated?

**Comment by matthijs** [comment]
The default is to use the postgresql generated uuids. The migration looks as follows:
```php
Schema::create('roles', function (Blueprint $table) {
    $table->uuid('id')
        ->default(DB::raw('gen_random_uuid()'));
    $table->primary('id');
    $table->string('name');
    $table->string('display_name')->nullable();
    $table->string('description')->nullable();

    // Unique key is set using an DB::statement
    //$table->unique(['name', 'deleted_at']);

    $table->timestamps();
    $table->softDeletes();
});
```

**Comment by dinhquochan** [comment]
You must define value of the `id` if you don't set `incrementing`. Or automatic set key in Laravel Model Creating Event:  

```php
public static function boot()
{
    parent::boot();

    static::creating(function ($model) {
        $model->setKey(Str::uuid());
    });
}
```

**Comment by CrixuAMG** [comment]
I agree with @dinhquochan 's solution. However, I would put the logic in a trait, so it can be reused for other models easily.

**Comment by driesvints** [comment]
@matthijs did it work with @dinhquochan's solution?

**Comment by matthijs** [comment]
@driesvints I'll test it when back at home.

**Comment by CrixuAMG** [comment]
@dinhquochan exactly, but for such a little thing creating your own trait would be better imho.

**Comment by matthijs** [comment]
@zecipriano ah, that's the issue. You have explained it better to the devs then I did. See #26683.

All the workarounds here will probably work but the database have an 'auto incrementing' key, in this case the incrementing key is 'gen_random_uuid()'. When leaving $incrementing as true will cause errors as explained in #26683

I'm not sure if github can merge tickets, but otherwise this can be closed.

**Comment by driesvints** [comment]
Closing this in favor of the other issue
