### ISSUE TITLE
Possible Bug with URL in Tests

### ISSUE THREAD

**Issue by raank** [laravel/framework#26671]
- Laravel Version: 5.5.*
- PHP Version: 7.1

### Description:
I found an bug in tests of Laravel, if set url `route('api.files.store')` (route to */api/uploads*) and also define other url for api like `config('app.api')`, in file *app.php* i m setting url: *http://localhost:8000/api*, but in my tests this a url get this: *http://localhost:8000/api:8000/uploads*.

This is a possible bug? The system append port after URL defined?

sorry for english.

Thanks

**Comment by raank** [comment]
i need this configuration for subdomains, so i need append a port on URL configuration in file env.

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by raank** [comment]
I solved in my project, but wanted to share.
Thanks for your answer.
