### ISSUE TITLE
Laravel Paginate Search of Filters like Datatables

### ISSUE THREAD

**Issue by NitishKumarPatra** [laravel/framework#26680]
Hi, @taylorotwell Are we getting any search/filters in laravel paginate anytime soon? That feature would be awesome. Also, improvisations on the paginate would be good in future releases as tables with huge datasets are quite a common thing to show on websites nowadays.

**Comment by driesvints** [comment]
Heya, thanks for submitting this. This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.
