### ISSUE TITLE
Builder Select() alias as id problem

### ISSUE THREAD

**Issue by aliwesome** [laravel/framework#26687]
- Laravel Version: 5.7.13
- PHP Version: 7.1.3
- Database Driver & Version: mysql 15.1

Query Builder function `select()` alias has a problem when I tried to alias a column name as `id` like below:
`Airport::domestic()->select('iata as id', 'name as text')->get()`
and I got this as result:
`[
{
id: 0,
text: "John F. Kennedy International Airport"
}
]`
it returns `id` with `0` value which is not correct.
this is needed for select2 ajax default data format.

**Comment by staudenmeir** [comment]
Does your `airports` table have an actual `id` column?

**Comment by aliwesome** [comment]
@staudenmeir 
yes, but it should not impact on result.

**Comment by staudenmeir** [comment]
It does indirectly: Your model expects `id` to be an integer column (as it normally is), so the value gets cast to an integer (resulting in `0`).

**Comment by aliwesome** [comment]
@staudenmeir 
I tried another integer column and it resulted correctly with no casting. just `id` makes problem in results.

**Comment by staudenmeir** [comment]
"Normal" integer columns only get cast when you add them to `$casts`. As `id` is the primary key, this happens automatically:

https://github.com/laravel/framework/blob/b24870a0e1fd9daefcd885abecd1a6f727b64a9b/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L905-L912

**Comment by aliwesome** [comment]
@staudenmeir 
why it would impact on result? main column that I need to alias is `iata` not `id`.
when I alias it to plain text like `id` or anything else it should result just like raw sql results, but it doesn't.

**Comment by aliwesome** [comment]
@staudenmeir 
I think it should know :) that's a bug.
that's why I'm here and reporting this.

**Comment by staudenmeir** [comment]
It's not a bug, you just can't use Eloquent like this.

A possible workaround is the base query builder:

```php
$airports = Airport::domestic()->select('iata as id', 'name as text')->toBase()->get();
```

**Comment by aliwesome** [comment]
@staudenmeir 
you're right, thank you for response. It's worked correctly, many thanks.

**Comment by mbolaraharison** [comment]
@staudenmeir 
Thank you, that worked perfectly. Interesting,
