### ISSUE TITLE
Opis secret key in Queue Manager interferes with other libs

### ISSUE THREAD

**Issue by shrimpwagon** [laravel/framework#26691]
- Laravel Version: 5.7.15
- PHP Version: 7.2
- Database Driver & Version:  Mysql

### Description:
An instantiated \Opis\Closure\SerializableClosure in the Laravel environment will have it's static securityProvider property set because Laravel's QueueManager sets it during bootstrap. If that closure is unserialized  outside of Laravel it fails because there is no easy way to retrieve the key that was used. It is also non-intuitive that this is even happening. Yes, I eventually tracked it down and figured out it is just the Laravel app key base64 encoded. But again, this is totally non-intuitive.

I requested Opis to not have that property be static as this may be the only real solution.

Please see my issue there:

https://github.com/opis/closure/issues/22

I discovered this by using another library that also uses opis/closure, see issue there:

https://github.com/spatie/async/issues/52

### Steps To Reproduce:
Try to use the spatie/async example that I have. You will see that it is unable to unserialize the child tasks. The child tasks are unserialized outside of the Laravel framework thus not being able to use the secretProvider set by the the secretKey.

**Comment by driesvints** [comment]
From what I can see and the [solution posted here](https://github.com/spatie/async/issues/52#issuecomment-443354354) it can be easily solved.
