### ISSUE TITLE
why error page shows html twice

### ISSUE THREAD

**Issue by gaurangkumar** [laravel/framework#26699]
- Laravel Version: 5.6.12 (but 5.6 occurring too)
- PHP Version: 7.2.12
- Database Driver & Version: mysql 5.0.12-dev

## Description:
I installed laravel downloading from github and then `composer install`
when i run app by `php artisan serve` it shows error
'Whoops, looks like something went wrong.' and two time. all of html code rendered twice.
error page's html code displayed twice

## Steps To Reproduce:
download from github laravel -5.6.12 
run command `composer install`
then `php artisan serve`

**Comment by staudenmeir** [comment]
Please post a screenshot.

**Comment by gaurangkumar** [comment]
I am running in local server
It displays "Whoops, looks like something went wrong." twice.

I found that ...
'''
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate"
        ],
'''
are not running while downloaded from github and installed by `composer install`.

**Comment by gaurangkumar** [comment]
tested on laravel-5.7.15 too .problem is same....
there are actully 2 problem ..
1. why composer scripts are not running ?
2. why error page displayed twice ?
sorry, dont know how to add images...

**Comment by staudenmeir** [comment]
You can upload the screenshot to a site like https://imgur.com/upload post the link.

**Comment by gaurangkumar** [comment]
installing by `composer create-project laravel/laravel:"5.7.15"` has no error.

**Comment by gaurangkumar** [comment]
[https://imgur.com/E9RhLSG](https://imgur.com/E9RhLSG)

**Comment by staudenmeir** [comment]
I don't really see the issue here. It works when you install Laravel as described in the [documentation](https://laravel.com/docs/5.7/installation). You can't expect it to work when you choose a different way.

**Comment by gaurangkumar** [comment]
Yeah, you are right. thank you. closing this issue. have a nice day...
