### ISSUE TITLE
Always return $this in when()

### ISSUE THREAD

**Issue by powelski** [laravel/framework#26692]
Currently, `when()` Eloquent method returns either `$this` or, if the callback returns any truthful value, this value will be returned. In [official documentation](https://laravel.com/docs/5.7/queries#conditional-clauses), the `$query` is being returned, unlike callbacks in other methods that just apply changes to the query without returning anything:

```php
$users = DB::table('users')
    ->when($role, function ($query, $role) {
        return $query->where('role_id', $role);
    })
    ->get();
```

I think that can cause confusion and could be simplified. I can't think of a single useful scenario where you would want to use the value returned by `when()`. If you return anything other than the query there, that will lead to breaking the chaining, which I believe should always be expected from Query Builder. Also, checking for the value being truthful is not intuitive.

This will work:

```php
$users = DB::table('users')
    ->when($role, function ($query, $role) {
        $query->where('role_id', $role);
        return 0;
    })->get(); // 0 is falsey, so get() is being called on the query
```

But this will not:

```php
$users = DB::table('users')
    ->when($role, function ($query, $role) {
        $query->where('role_id', $role);
        return 1;
    })->get(); // 1 is truthy, so get() is being called on 1
```

I would go with always returning `$this` and just ignoring the value returned by the callback. Or, if this value must be used for some reason, it should be compared against `null`, not to soft `true`.

**Comment by driesvints** [comment]
Heya, thanks for submitting this. This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.
