### ISSUE TITLE
Laravel redirect to route not found on Auth Scaffold

### ISSUE THREAD

**Issue by IgorDePaula** [laravel/framework#26697]
- Laravel Version: 5.7 (but 5.6 occurring too)
- PHP Version: 7.2
- Database Driver & Version: mysql 5.7

### Description:
I make 
```php artisan make:auth```
and change the home route, I prefer "dashboard" route, but when I log or register me and try access the login or register page, I receive route home with 404, but have "dashboard"

This occur with laravel 5.7 and 5.6
With anonymous mode browser, this is not occur.
### Steps To Reproduce:
Make auth scaffold with "php artisan make:auth"
Remove home route, and in auth controllers, change "/home" by "/dashboard",
Try register or login with another user with logout, you'll redirect to route home and will receive 404 error

**Comment by staudenmeir** [comment]
Sounds like a caching issue. Try clearing your browser cache.

**Comment by IgorDePaula** [comment]
Yes, but this is unprofessional, some cookie cause this strange behavior

**Comment by staudenmeir** [comment]
I'm pretty sure this was only happening in *your* browser during development.

**Comment by IgorDePaula** [comment]
No, this occur in my browser and more others 2 browsers, chrome and firefox, on my 2 friends, on linux and windows, no only development, but production too.

Only can a cookie from request.

**Comment by devcircus** [comment]
As this is something specific to your app, you would probably get a lot more help on slack, laracasts, Laravel.io, or discourse.

**Comment by IgorDePaula** [comment]
Not specific of my app, on 3 installations this occur.

**Comment by devcircus** [comment]
if It’s in 3 different fresh Laravel installs then the issue has to be elsewhere in your environment. Permissions, configuration, etc.

**Comment by IgorDePaula** [comment]
3 different fresh laravel install, on 3 browsers on 3 different pcs, and on 3 different servers. Permissions, configuration cant be, I alter all place "/home" to "/dashboard".

Can someone try test od instead talk?

**Comment by IgorDePaula** [comment]
Great. change all "/home" route to "/dashboard", for example, on ```php artisan amke:auth"
Log in and try access login page or register page. Its redirect to "/home" instead of "/dashboard" route (or another of your preference)

**Comment by IgorDePaula** [comment]
Tomorow I will put a little app on github and video (now is midnight on my country).

Thanks for your attention.

**Comment by IgorDePaula** [comment]
I was do this, but this occur when already logged I try access the login page or register page.

> Have you changed the “redirectTo” property in your login and register controller to “/dashboard”? Also make sure your dashboard route name is still “home” or replace all references of route(‘home’), in the app with route(‘dashboard’) or whatever the name is.

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by IgorDePaula** [comment]
Serious? I cant report a bug? No one tried and I'm wrong. Ok.

**Comment by Azprio** [comment]
@IgorDePaula did you find any solution of it ? I'm facing the same problem.

**Comment by Azprio** [comment]
In your laravel folder open the file app->Http->Middleware->RedirectIfAuthenticated.php and replace the /home line with suitable url. Thank you.
