### ISSUE TITLE
bug when using 'some' alias for the 'contains' method Collection

### ISSUE THREAD

**Issue by chapeupreto** [laravel/framework#26695]
- Laravel version: 5.7.13
- PHP version: 7.2.12
- Illuminate\Support\Collection

Laravel `5.7.13` introduced an `alias` ([#26376](https://github.com/laravel/framework/pull/26376)), named `some`, for the `contains` method on the `Illuminate\Support\Collection` class.

Although `contains` is working , `some` is not.

For instance, this is the actual behavior using `contains`:

```php
$collection = collect(['name' => 'Desk', 'price' => 100]);
$collection->contains('New York'); // false
```

However, when using `some`, the output isn't the same as `contains`:

```php
$collection = collect(['name' => 'Desk', 'price' => 100]);
$collection->some('New York'); // true
```

Another example (same as from the Laravel documentation):

```php
$collection = collect([1, 2, 3, 4, 5]);
$collection->contains(function ($value, $key) {
    return $value > 5;
});

// false
```

Now using `some`:

```php
$collection = collect([1, 2, 3, 4, 5]);
$collection->some(function ($value, $key) {
    return $value > 5;
});

// PHP Warning:  explode() expects parameter 2 to be string, object given ...

```

I wrote a `testSome()` test using the same logic for the `testContains()` and it failed.

I believe the reason for such a odd behavior is because of the `func_num_args()` call used by the `contains` method.

Anyways, I'm going to submit a PR that tries to handle that situation.

**Comment by driesvints** [comment]
Gonna close this as your PR was merged.
