### ISSUE TITLE
PhpRedisConnection::getMultiple() throws a TypeError

### ISSUE THREAD

**Issue by crocodile2u** [laravel/framework#26709]
- Laravel Version: 5.7.0
- PHP Version: 7.2.4
- Database Driver & Version: MySQL

### Description:

Using PhpRedis driver for Redis and attempting to use getMultiple(), I get the following error: Argument 1 passed to Redis::mget() must be of the type array, string given.

### Steps To Reproduce:

Hereby, my Redis config for Laravel:

```
'redis' => [

        'client' => 'phpredis',

        'default' => [
            'host' => env('REDIS_HOST'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => 0,
        ],

    ],
```
Reproduce: setup Redis, setup Laravel to connect to it using PhpRedis, then:

```
app()->make(\Illuminate\Contracts\Cache\Repository::class)->getMultiple(["key1", "key2"]);
```

This did not happen with Laravel 5.6, so this is a regression.

**Comment by driesvints** [comment]
PR was merged
