### ISSUE TITLE
Laravel cPanel each hit login redirecting to url

### ISSUE THREAD

**Issue by yandifitriyanto** [laravel/framework#26705]
- Laravel Version: 5.2.45
- PHP Version: 5.6.38
- Database Driver & Version: MySQL

### Description:
I hosting application use cPanel and I have problem each hit login application redirect screen blank,  
![image](https://user-images.githubusercontent.com/16094167/49336572-4a996080-f637-11e8-82d8-04046838aaf1.png)

### Steps To Reproduce:
1. Structrure folder application in cPanel : 
```
root
└───helpdesk
│   └───ePusatdata
│       │   all structure laravel without folder public
│       │   ...
└───public_html
    │   all file containing in folder public
```
2. Go to the login page http://malteng-helpdesk.aplication.id/login
3. Hit button sign in
4. Result 
![image](https://user-images.githubusercontent.com/16094167/49336572-4a996080-f637-11e8-82d8-04046838aaf1.png)

can anyone please do me a favour ?

Thanks

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
