### ISSUE TITLE
[feature] add one query MAX_EXECUTION_TIME for mysql5.7.8

### ISSUE THREAD

**Issue by lopn** [laravel/framework#26704]
sometimes php script timeout ,but the query for db server still running , that bring too much load or read-write to the mysql server, the mysql5.7.8+ add the MAX_EXECUTION_TIME for select can timeout query by mysql server

https://dev.mysql.com/doc/refman/5.7/en/optimizer-hints.html#optimizer-hints-execution-time

**Comment by driesvints** [comment]
Heya, thanks for submitting this. This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.
