### ISSUE TITLE
Passing matching curly braces for route parameter value causes error

### ISSUE THREAD

**Issue by nanaya** [laravel/framework#26715]
- Laravel Version: 5.7.15
- PHP Version: 7.2.12
- Database Driver & Version: N/A

### Description:
Generating route which parameter contains matching braces throws `Illuminate\Routing\Exceptions\UrlGenerationException`.

### Steps To Reproduce:
1. `laravel new route_test`
2. `cd route_test`
3. `echo "Route::get('u/{username}', function () { return; })->name('user');" >> routes/web.php`
4. `echo "route('user', ['username' => '{fancy username}'])" | php artisan tinker`

#### expected result:

tinker outputs `http://localhost/u/%7Bfancy%20username%7D"`

#### instead got:

    Illuminate/Routing/Exceptions/UrlGenerationException with message 'Missing required parameters for [Route: user] [URI: u/{username}].'

**Comment by nanaya** [comment]
I hope you meant that as work around and not suggesting doing that everywhere string is passed as parameter...?

And then I noticed wrong result when passing `?` as the for `username` - also "fixed" by passing urlencoded value instead. Maybe the value should be encoded in the parameter replacement function instead?

**Comment by staudenmeir** [comment]
Yes, hopefully only as a workaround. But this doesn't look like a trivial issue.

**Comment by driesvints** [comment]
I believe these characters aren't allowed by default but can be allowed if you add a regex which allows them. Can you try adding a `->where('username', '.*')` statement to the route in question?

**Comment by nanaya** [comment]
@driesvints same result. I have outlined the simplest reproduction steps above if you want to try more.

**Comment by driesvints** [comment]
Seems like this is indeed not possible and you'll have to encode the characters like @staudenmeir suggested.

**Comment by nanaya** [comment]
@driesvints Should I take it that all routes which parameter contains string must be escaped before passed to `route` function? (or must be ensured that it never contains matching curly braces or question mark)

**Comment by driesvints** [comment]
@nanaya I think the latter. There's been several issue with special characters before but the general gist is to encode the parameters if they contain any.

**Comment by nanaya** [comment]
That sounds either dangerous (checking parameters and then not escaping) or tedious (escaping all parameters). But okay if you say so.
