### ISSUE TITLE
[5.7.15] pull/26012 causes assertViewHas() to break when mock is expected

### ISSUE THREAD

**Issue by markdwhite** [laravel/framework#26729]
- Laravel Version: 5.7.15
- PHP Version: 7.2.10
- Database Driver & Version: mySQL 5.7.24

### Description:

Committed pull has introduced a reliance on Eloquent\Model::is() in assertViewHas(). Where the $value being tested is a mock, this introduces the need for additional expectations to be set in the mock to cover this.

https://github.com/laravel/framework/pull/26012/files

The new code is not tested in the commit as a mock Model is used with an overridden is() method. Changing existing test suites to be compatible with this approach may be onerous. 

As the new code is not tested, and as this issue only affects mocks, could the approach be taken to allow mocks to fall through to use the old approach? Eg:

        } elseif ($value instanceof Model && !$value instanceof \Mockery\MockInterface) {
            PHPUnit::assertTrue($value->is($this->original->$key));
        } else {
            PHPUnit::assertEquals($value, $this->original->$key);
        }

**Comment by driesvints** [comment]
I'm not really sure how this method could have worked before either with a mock?

**Comment by markdwhite** [comment]
With one additional expectation, or an increase in ->times(n) where it's already in use.

    $mock->shouldReceive('getAttribute')->with('id')...

The new code requires more code for no benefit, which is why I'm questioning it. It can be worked around, or it may show that the tests that rely on this could be better. But as it stands it's a breaking change. 

Should it be one?
