### ISSUE TITLE
Ploymorphic relations slowdown

### ISSUE THREAD

**Issue by therezor** [laravel/framework#26720]
- Laravel Version: 5.6, 5.7
- Database Driver & Version: Mysql/MariaDB

### Description:
After this commit indexes for Morph tables are useless. 
https://github.com/laravel/framework/commit/d15ad0fdf2d1fef63600eeccf57d756d28571614

Query builder still produces queries in "model_id and model_type" form.
So instead of performance increase described in "whats new" we got decrease.

### Steps To Reproduce:
Create a model with relation along with polymorhic relation
try to see query withCount or whereHas;

### Query examples:

```sql
select some_item.*, (select count(*) from log where some_item.id = log.entity_id and log.entity_type = ? and log.deleted_at is null) as changes_count from some_item
```

```sql
select * from some_item where exists (select * from tags where some_item.id = tags.entity_id and tags.entity_type = ?)
```

### Expected result:

```sql
select some_item.*, (select count(*) from log where log.entity_type = ? and some_item.id = log.entity_id and log.deleted_at is null) as changes_count from some_item
```

```sql
select * from some_item where exists (select * from tags where tags.entity_type = ? and some_item.id = tags.entity_id)
```

**Comment by staudenmeir** [comment]
Have you analyzed the queries with `EXPLAIN`? The order of the constraints shouldn't have any impact on the performance.

**Comment by therezor** [comment]
I had. There is a huge impact on a performance. Queries runing more than an hour in 1M record table.
After changing combined index it takes only 5min.

**Comment by therezor** [comment]
The issue is in wrong usage of combined index.
index = entity_type + entity_id

... where entity_id = some.id and entity_type = 'type' ... <- No indexes used in this scenario
... where entity_type = 'type' and entity_id = some.id ... <- Indexes are used

**Comment by driesvints** [comment]
@therezor indexes seems the developer's responsibility to add in their migrations. Doesn't really have to do anything with the current working of Eloquent afaik?

**Comment by therezor** [comment]
@driesvints I agree, but Blueprint->morphs(...) method is doing this without any option to disable index and create it manually.

`  public function morphs($name, $indexName = null)
    {
        $this->string("{$name}_type");

        $this->unsignedBigInteger("{$name}_id");

        $this->index(["{$name}_type", "{$name}_id"], $indexName);
    }`

**Comment by driesvints** [comment]
@therezor you can still simply do the internals of the method yourself if you really want? And then leave out the index or add another one?

**Comment by therezor** [comment]
Love laravel community for such answers. 
Of course I can, and trust me I am doing it.
Is there any reason of having that out of the box if it simply does not make sense?

**Comment by driesvints** [comment]
If you're doing that atm and it fixes your problem then I believe this issue can be closed. If you suggest that this method should be altered or a new one should be added in addition then it's best to first propose something like that in [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework.
