### ISSUE TITLE
An Eloquent model attribute or relation with a name that clashes with a protected property should throw an error or warning

### ISSUE THREAD

**Issue by robjbrain** [laravel/framework#26730]
- Laravel Version: 5.7.15
- PHP Version: 7.2

### Short Description:
If you have a relationship or an attribute with a name that clashes with a protected property then you can run into a scenario where it works most of the time, but silently fails in others.

This is not just an issue when starting a new project, something like the `$changes` attribute on the HasAttributes trait was introduced in a minor release (5.5.44) and would have affected anyone who had an attribute or relation called changes.

### Longer description with examples:
Take this example:

```
class Submission extends BaseModel
{
    public function changes() {
        return $this->hasMany(Change::class, 'submission_id');
    }
}
```

If you access this from a controller like this:

```
$submission = Submission::find(1);

$submission->changes->count();
```

You won't get any issues and it would behave exactly like any other Eloquent relationship.

However if you have this method in your Submission model:

```
    public function getChangesCount() {
        return $this->changes->count();
    }
```

Calling `$submission->getChangesCount()` will throw an error because `$changes` is a protected property on the `HasAttributes` trait.

In the first instance because the `$changes` property is protected it goes through the `__get()` magic method and hits getAttribute() and getRelation() without issue.

In the second instance because we are inside the class itself we can access the protected property and so `__get()` and `getAttribute()` are never hit and we simply receive the array from the HasAttributes trait.

The `$changes` property was introduced in Laravel 5.5.44 https://github.com/illuminate/database/commit/5cb4fb0f0d8f6b48d2cb8969c7097b325ecb2354#diff-ca2c0e9e4ca2bdd7e54cc1e0a5adba1e

If you had a relation or a property called changes before this point you would have issues (or perhaps not, but still possible in the future) and this fact would not have been clear because there's no documentation of reserved words in Eloquent models.

Of course i've just used `$changes` as an example any existing property or property introduced in the future could cause this same issue.

I think it's too big an expectation to maintain a list of reserved words and instruction people to check it after every minor update (note again $changes was introduced in 5.5.44) instead I think a warning should be thrown if you try to access an attribute with the same name as a protected property.

In very simplistic pseudo code this could look something like this:

```
public function getAttribute($key)
{
    if (property_exists($this, $key)) {
         throw new ReservedWordException();
    }
}
```

It may well need to be more complicated than this using a reflection class.

We might also want to access properties sometimes, but i'm assuming that if you're hitting `getAttribute()` then you're not hitting an available public property.

Perhaps this check would be better within the `__get()` magic method?

```
public function __get($key)
{
    if (property_exists($this, $key)) {
         throw new Exception('Cannot access protected property $this::$key');
    }

   return $this->getAttribute($key);
}
```

I'm open to discussion on how it should be implemented, but I do think something should be done to alert developers when this occurs.

Some common protected properties that you can imagine being used as a column in a database table are things like `$hidden` `$visible` `$exists` `$original` `$changes`

But I think the most important thing to stress is that new properties are likely to be added in minor releases in the future and there's currently nothing in place to make this clear to devs who upgrade.

**Comment by driesvints** [comment]
Isn't it better to do `return $this->changes()->count();` anyway?

**Comment by driesvints** [comment]
With your current implementation you first retrieve and count while the suggestion above will execute a  count query.

**Comment by robjbrain** [comment]
That's true but kind of misses the point, I was just trying to use the simplest example that anyone would understand without further example code.

Imagine a "scores" table that has:

id int
points int
hidden tinyint(1)

If you do `$score->hidden` you get the attribute from the database as you would expect.

But if you have a method such as 

```
// Admins can see hidden scores
public function canBeSeen($user) {
    return $user->is_admin || !$this->hidden;
}
```

In this case `$this->hidden` refers to the protected property $hidden and no error would be shown but you'd get weird results.

Now the easy answer is "don't use attributes that are use the same name as model properties"

But

1) reserved property names are not documented anywhere 

2) using a reserved word does not throw a warning or error

3) as I've already shown properties get added in minor releases with no documentation

Now imagine 5.7.17 adds a protected property called $status. Any model with a database column called "status" would have a problem.

Does that make it clearer?

**Comment by driesvints** [comment]
@robjbrain yes it does. Thanks for point this out btw. However, I believe if we were to change how this works it would require some changes to the internals of how Eloquent works. As this isn't really a bug atm but rather just the way things work I think it's best that you raise an issue at [laravel/ideas](https://github.com/laravel/ideas) to propose some changes and gather support for your idea. We're trying to use this issue tracker for bugs only. 

Thanks!
