### ISSUE TITLE
[5.7] and PHP 7.2 - Artisan:call() throws "count() parameter must be an array or an object that implements Countable"

### ISSUE THREAD

**Issue by 949mac** [laravel/framework#26744]
- Laravel Version: 5.7.15
- PHP Version: 7.2

### Description:
I have the following Artisan::call :
```
Artisan::call('process:documents', [
            'trigger' => 'Table'
            '--booking-id' => $booking_id,
        ]);
```

When executing, I get an error stating: 
`count() parameter must be an array or an object that implements Countable`

When I downgrade the server's PHP to 7.1, the error goes away.

### Steps To Reproduce:
1. Implement an Artisan call with an `argument` and an `option`
2. Ensure your PHP version is 7.2
3. Observe error

**Comment by staudenmeir** [comment]
Please post the stacktrace.

**Comment by 949mac** [comment]
I'm closing this. After reviewing the stack trace, I was able to see the issue in my souce.
