### ISSUE TITLE
[5.5] Encrypter class doesn't work with latest versions of openssl (cipher names case problem)

### ISSUE THREAD

**Issue by iprok** [laravel/framework#26745]
- Laravel Version: 5.5.44
- PHP Version: PHP 7.0.30

### Description:
After upgrading to openssl 1.1.1 or 1.1.0j (the fresh update in  in Debian Stretch) got error
"The cipher `AES-256-CBC` is not defined"

### Steps To Reproduce:
Just try to use Encrypter class with Laravel 5.5.44 and openssl 1.1.0j or openssl 1.1.1.

The problem is caused by latest openssl versions that returns ciphers only in lower case, so there is no AES-256-CBC,  AES-128-CBC but only aes-256-cbc or aes-128-cbc. You can see it using:
php -r 'print_r(openssl_get_cipher_methods(true));' |grep -i aes-128-cbc
    [0] => aes-128-cbc
    [1] => aes-128-cbc-hmac-sha1
    [2] => aes-128-cbc-hmac-sha256

**Comment by staudenmeir** [comment]
I can't reproduce this. Please post the stacktrace.

**Comment by iprok** [comment]
@staudenmeir excuse me, I'm not familiar with laravel (not developer at all), but may be more details will help you.
I've found that strings cause the issue:
```
vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:35:    public function __construct($key, $cipher = 'AES-128-CBC')
vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:43:            throw new RuntimeException('The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths.');
vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:58:        return ($cipher === 'AES-128-CBC' && $length === 16) ||
vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:59:               ($cipher === 'AES-256-CBC' && $length === 32);
vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:70:        return random_bytes($cipher == 'AES-128-CBC' ? 16 : 32);
```

And  the reason is that php function openssl_get_cipher_methods(true) changes it results as it's described in the comment here: https://secure.php.net/manual/en/function.openssl-get-cipher-methods.php#123319 . But in  addition to openssl mentioned there - 1.1.1, also php compiled with openssl 1.1.0j is affected.

So to repeat the  bug you should use laravel frameword 5.5.44 (have not tested other) on the system with openssl 1.1.0j or openssl 1.1.1 (debian stretch or ubuntu 18.10, will latest  updates).
Try to execute
php -r 'print_r(openssl_get_cipher_methods(true));'
from your console, you will not see in cipher names in uppercase. If so you will not able to execute any code that uses this 
vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:35:    public function __construct($key, $cipher = 'AES-128-CBC')
constructor because there is no more 'AES-128-CBC' (uppercase) cipher in openssl. Only lowercase one.

The same bug:
https://github.com/oerdnj/deb.sury.org/issues/990
https://github.com/composer/composer/issues/7769

**Comment by staudenmeir** [comment]
I get the same result from `openssl_get_cipher_methods()`, but Laravel doesn't use this function anywhere. Laravel only [checks](https://github.com/laravel/framework/blob/28e53f23a76206fb130e9a54eb95aa3f010e79c9/src/Illuminate/Encryption/Encrypter.php#L54) the uppercase cipher name and the key length.

The encryption still works for me with OpenSSL 1.1.1.

**Comment by iprok** [comment]
I'm really sorry. Cipher names in uppercase make in addition to the issues with composer forced me to make this mistake. openssl_encrypt that your are using can understand cipher names in both cases.
