### ISSUE TITLE
.env variables exposed on Whoops page

### ISSUE THREAD

**Issue by PieterjanDeClippel** [laravel/framework#26750]
Everyone should be made aware of the fact that .env variables are exposed in the Whoops page.

When you accidently forget to set APP_DEBUG to false
all of your application passwords, keys and usernames are plainly exposed to the entire world.

That's just enough convincing for website owners to ditch Laravel and go for one of the like 200 other MVC frameworks (think of codeigniter, symphony itself, yii, CakePHP, and so on, and so on)

Why not just remove the .env variables from the Whoops page by default (and yeah, entirely)?
95% of the Laravel developers will be happy.
For the other 5% who are too lazy to just locate and open the .env file, just add a, I don't know, I_AM_LAZY environment variable.

**Comment by X-Coder264** [comment]
Everything is documented here: https://laravel.com/docs/5.7/configuration#hiding-environment-variables-from-debug so "everyone" is made aware of that fact. It's another matter entirely if people don't read the documentation, but there isn't really much anyone can do about that :smile:

**Comment by PieterjanDeClippel** [comment]
First lesson in Webdesign:

### YOU DON'T PRINT PASSWORDS ON A FREAKING HTML PAGE.
### NOT IN ANY CIRCUMSTANCES
### NOT EVEN A PASSWORD OF A USER ON HIS OWN ADMIN PAGE
### LET ALONE THE FREAKING SQL PASSWORD

**Comment by EliasZ** [comment]
![4b6](https://user-images.githubusercontent.com/530685/49569748-14a8f480-f935-11e8-9f0a-90afff24d842.jpg)

**Comment by fabianPas** [comment]
> First lesson in Webdesign:
> 
> ### YOU DON'T PRINT PASSWORDS ON A FREAKING HTML PAGE.
> ### NOT IN ANY CIRCUMSTANCES
> ### NOT EVEN A PASSWORD OF A USER ON HIS OWN ADMIN PAGE
> ### LET ALONE THE FREAKING SQL PASSWORD
> ### NEVER !!!!

Would you mind keeping it civil? This isn't a very constructive discussion this way.
