### ISSUE TITLE
App breaking on L 5.7.16 with hasManyThrough?

### ISSUE THREAD

**Issue by apocalyarts** [laravel/framework#26768]
I was wondering if the fixes for ````hasManyThrough```` that have been introduced in 5.7.16 are a breaking change? In one of my apps I had this relation:

```php
public function parentModels(){
  return $this->hasManyThrough(Model::class, SubModel::class, 'sub_model_id', 'model_id', 'id', 'id');
}
```

needed to change it like this to make my app work with 5.7.16:
```php
public function parentModels(){
  return $this->hasManyThrough(Model::class, SubModel::class, 'sub_model_id', 'id', 'id', 'model_id');
}
```

**Comment by driesvints** [comment]
Related to this PR? https://github.com/laravel/framework/pull/26676

Ping @staudenmeir

**Comment by apocalyarts** [comment]
One used query was this:

```php
$model = Model::where('key', $key)->with('parentModels')->first();
```

Here is the SQL Exception that I got:

````SQLSTATE[42S22]: Column not found: 1054 Unknown column 'models.model_id' in 'on clause' (SQL: select `models`.*, `sub_models`.`sub_model_id` from `models` inner join `sub_models` on `sub_models`.`id` = `models`.`model_id` where `sub_models`.`sub_model_id` in (1))````

**Comment by staudenmeir** [comment]
Can you provide an example with "real" models? Is `SubModel` a subclass of `Model`?

**Comment by apocalyarts** [comment]
It is not a subclass, both are Eloquent model classes

**Comment by staudenmeir** [comment]
Please provide an example with real models and their migrations.

**Comment by GrahamCampbell** [comment]
Ping @apocalyarts. We need more information please.

**Comment by driesvints** [comment]
@apocalyarts feel free to reply once you can provide more info.
