### ISSUE TITLE
JSON localization add path not works

### ISSUE THREAD

**Issue by Victorlerner** [laravel/framework#26765]
- Laravel Version: 5.6.24
- PHP Version:
- Database Driver & Version:

### Description:
if you add this code in boot method in any service provider
`app()['translator']->addJsonPath('C:\OpenServer\OSPanel\domains\lararent.loc\app\Themes\lang');
 `
it's not works
so in class  Illuminate\Translation\Translator
dump($this->loader->jsonPaths);
show me correct path
but
in class  /vendor/laravel/framework/src/Illuminate/Translation/FileLoader.php
in  public function loadJsonPaths($locale)
dump($this->jsonPaths);
show me []

Why is this?

will only work if I modify a method to this
  public function loadJsonPaths($locale)
    {

```

	  $this->jsonPaths[] = 'C:\OpenServer\OSPanel\domains\lararent.loc\app\Themes\lang';

        return collect(array_merge($this->jsonPaths, [$this->path]))
            ->reduce(function ($output, $path) use ($locale) {
                if ($this->files->exists($full = "{$path}/{$locale}.json")) {
                    $decoded = json_decode($this->files->get($full), true);

                    if (is_null($decoded) || json_last_error() !== JSON_ERROR_NONE) {
                        throw new RuntimeException("Translation file [{$full}] contains an invalid JSON structure.");
                    }

                    $output = array_merge($output, $decoded);
                }

                return $output;
            }, []);
    }

```
in the end, he does not see the added path and  localization files not working.
How to fix this?

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
