### ISSUE TITLE
Replicate updates the parent's timestamps

### ISSUE THREAD

**Issue by malfianrasyidin** [laravel/framework#26764]
- Laravel Version: 5.5.*
- PHP Version: 7.2.10
- Database Driver & Version: MySQL 5.7

### Description:
I tried to duplicate a model. Yes, it successfully created new instance with exactly the same data. But, why the parent's timestamps is changed to the time when the replication is created? I don't even manipulate the parent's data.

### Steps To Reproduce:
```php
public function duplicate()
{
  $new = $this->replicate();
  $new->push();
}
```

### Expected Behavior:
Parent's data shouldn't change its `updated_at`, because no changes were made on it.

**Comment by driesvints** [comment]
This is normal. The parent's key, created and updated timestamps are specifically not recreated because it's expected that these are new on a replicated instance.

https://github.com/laravel/framework/blob/79f34c859046c3ddecede41377ab2a75e208548b/src/Illuminate/Database/Eloquent/Model.php#L1055-L1063

**Comment by mfn** [comment]
@driesvints wait, no, this is something else isn't it? Specifically:
> But, why the parent's timestamps is changed to the time when the replication is created?

He says the "parent" (original model) timestamps changed.

However tried to replicate this locally (but only tested on model without loaded relation) and couldn't reproduce.

Probably needs OP to come forward here…

**Comment by driesvints** [comment]
Ah okay, sorry misread this. Yeah we'll need some code to reproduce this. Please provide a minimal setup which reproduces this.

**Comment by malfianrasyidin** [comment]
Yes, the original model's timestamps is changed on `updated_at` field to the time when the replication is created.

Here is the set up to reproduce this in more detail.

Suppose you have a Request model:
```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Request extends Model {
    /**
     * One to many relationship between Request and RequestItem.
     * Every request has many request items.
    */
    public function items()
    {
        return $this->hasMany(RequestItem::class);
    }

    /**
     * Duplicate instance.
     * 
     * @param int $month
     * @param int $year
    */
    public function duplicate($month, $year, $note)
    {
        $new = $this->replicate();
        $new->status = 1;
        $new->note = $note;
        $new->month = $month;
        $new->year = $year;
        $new->save();
        $items = [];
        foreach ($this->items as $item) {
            $newItem = $item->replicate();
            $newItem->save();
            array_push($items, $newItem);
        }
        $new->items()->saveMany($items);
    }
}
```

Then you have a RequestController which calls the duplicate method:
```php
<?php

namespace App\Http\Controllers\BudgetManagement;

use App\Request as Req;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class RequestController extends Controller
{
    /**
      * Duplicating plan.
      * 
      * @param int $id
      * @param  \Illuminate\Http\Request  $request
      * @return \Illuminate\Http\Response
    */
    public function duplicating($id, Request $request)
    {
        try {
            $req = Req::findOrFail($id);
            $req->duplicate($request->month, $request->year, $request->note);

            return redirect('requests');
        } catch (\Throwable $e) {
            return redirect()->back()->withInput($request->all);
        }
    }
}
```

That's it, when you run this, the replication is made successfully with the current time on `created_at` and  `updated_at` field. But, the original's `updated_at` field is also changed to current time. This is the problem.

Thanks!

**Comment by malfianrasyidin** [comment]
Hi @driesvints ,
Is there anyway to get this issue to be opened again ? Thanks

**Comment by fryght** [comment]
In your example, you are replicating the `RequestItem` objects and saving them right after, in which case they are still related to the original, which triggers the update to the original. Then you call `saveMany`, which updates the parent relation to the replicated instance. If you don't save the `RequestItem` right after replicating it, it should work correctly.

**Comment by driesvints** [comment]
@malfianrasyidin did you try @fryght's solution and did that help?

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.

**Comment by nbyloff** [comment]
@fryght @driesvints I know this is old, but what would you consider saving right after? In my instance, I am trying to take a snapshot of thousands of records and move them into an archive DB. I want to make sure the parent timestamps are intact. So I am looping through records, using `replicate` and then saving but experiencing the issue described here where timestamps in the parent are getting updated. 

Side note, using L6 because my project needs LTS but will be updating to the new LTS version at the end of the year.
