### ISSUE TITLE
Add InvalidArgumentException For orderBy() in Illuminate\Database\Query\Builder

### ISSUE THREAD

**Issue by cocoeyes02** [laravel/framework#26776]
Hi, I suggest improve of orderBy().
https://github.com/laravel/framework/blob/28cdb6bc2cfd4d802efe5ea7c6e7f7e581163117/src/Illuminate/Database/Query/Builder.php#L1778-L1793

If $direction is a typo (ex. 'as', 'aesc'), that means orderBy('desc').
I think it doesn't good to me because this process causes the bug of direction unintentionally.

This is why I want InvalidArgumentException before this process.

```
public function orderBy($column, $direction = 'asc')
{
    if (!in_array(strtolower($direction), ['asc', 'desc'], true)) {
        throw new InvalidArgumentException('Invalid value of direction .');
    }

    $this->{$this->unions ? 'unionOrders' : 'orders'}[] = [
        'column' => $column,
        'direction' => strtolower($direction) == 'asc' ? 'asc' : 'desc',
    ];

    return $this;
} 
```

thanks.

**Comment by driesvints** [comment]
Heya, thanks for submitting this. This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.
