### ISSUE TITLE
AuthServiceProvider Policy Registration Include Array?

### ISSUE THREAD

**Issue by gofish543** [laravel/framework#26773]
I was toying around with policies earlier today and I noticed, by default, policy registration is done on a model => policy basis. 
I'm curious if it would be beneficial to allow for a model => [policy, ...] registration instead.
Example...
```
<?php

namespace App\Providers;

use App\Policies\RoundPolicy;
use App\Round;
use Gate;
use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;

class AuthServiceProvider extends ServiceProvider {

    /**
     * The policy mappings for the application
     *
     * @var array
     */
    protected $policies = [
        Round::class => [
            RoundPolicy::class,
            ...
            SuperSecretPolicy::class,
            HeroicPolicy::class,
        ],
    ];

    /**
     * Register any authentication / authorization services
     *
     * @return void
     */
    public function boot() {
        $this->registerPolicies();
    }

    /**
     * Register the application's policies.
     *
     * @return void
     */
    public function registerPolicies() {
        foreach ($this->policies as $key => $value) {
            if (is_array($value)) {
                foreach ($value as $item) {
                    Gate::policy($key, $item);
                }
            }
            else {
                Gate::policy($key, $value);
            }
        }
    }
}
```
Take note of the registerPolicies function which allows for the policy registration to be a single value or an array, functioning similar to the EventServiceProvider event/listener registration.

Let me know what you think!

**Comment by staudenmeir** [comment]
Please use https://github.com/laravel/ideas/issues for proposals.

**Comment by driesvints** [comment]
Heya, thanks for submitting this. This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

**Comment by driesvints** [comment]
@staudenmeir I don't have admin access myself to the repos so I can't use that atm.

**Comment by staudenmeir** [comment]
@driesvints I see, I assumed this feature was also available to members.

**Comment by gofish543** [comment]
Oh, I apologize. I should've read the instructions more closely. I'll make a feature request over there.
