### ISSUE TITLE
composer update error

### ISSUE THREAD

**Issue by lifu870415** [laravel/framework#26782]
- Laravel Version: 5.5
- PHP Version: 7.2.11

### Description:
"composer update" returns "...\vendor/infyomlabs/laravel-generator does not exist and could not be created."

in composer.json:
    "infyomlabs/core-templates": "5.3.x-dev",
    "infyomlabs/generator-builder": "dev-master",
    "infyomlabs/laravel-generator": "5.3.x-dev",
    "infyomlabs/swagger-generator": "dev-master",

How can i fix this issue?

**Comment by decadence** [comment]
Welcome to Laravel! We are glad to have you as part of the community.

Unfortunately GitHub is not an appropriate platform for general application issues. This is only for issues/bugs with the framework code itself.

Please close your issue, and instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

Laravel Slack (https://larachat.co/)
Laravel.io Forum (https://laravel.io/forum)
Laracasts Forum (https://laracasts.com/discuss)
StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks!

**Comment by ahinkle** [comment]
The development branch you selected[ no longer exists ](https://github.com/InfyOmLabs/laravel-generator/branches/all) within your `composer.json`.
