### ISSUE TITLE
create CloudFront signed URL

### ISSUE THREAD

**Issue by michaelnguyen547** [laravel/framework#26797]
I am working with CloudFront to serve content from S3.

WIth S3 only

```
 // return a normal s3 url - correct
Storage::disk('s3')->url($image_path);

 // return S3 signed url - correct
Storage::disk('s3')->temporaryUrl($image_path, now()->addMinutes(30))
```

With CloudFront (Restrict Bucket Access is on, Restrict Viewer Access is on Use Signed URLs or Signed Cookies)

```
// return a normal CloudFront url - correct
Storage::disk('s3')->url($image_path); 

// return S3 signed url - incorrect . I expect CloudFront signed url
Storage::disk('s3')->temporaryUrl($image_path, now()->addMinutes(30)) 
```

**Comment by driesvints** [comment]
I don't think we support CloudFront at all?

**Comment by driesvints** [comment]
Ah I see what you mean now, sorry. This is indeed not supported at as we always get the S3 signed url. You'll have to overwrite the `getAwsTemporaryUrl` method of the `FilesystemAdapter` class for this.

**Comment by driesvints** [comment]
Actually, come to think of it, this is probably something that needs to be done in the AWS SDK. Since we're just called the correct methods to generate signed urls we shouldn't be bothered with checking if the file is served from Cloudfront before. That should be done in the AWS SDK or on AWS itself: 

https://github.com/aws/aws-sdk-php/blob/26c0ff509d1789aa63aa195efb11ef05add7e648/src/S3/S3Client.php#L339-L359

**Comment by michaelnguyen547** [comment]
S3Client cannot create CloudFront signed URL. We would need CloudFrontClient to do that 

https://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.CloudFront.CloudFrontClient.html#_getSignedUrl

Is it easy to integrate CloudFrontClient to Laravel? If this interests Laravel community, please tell me how to integrate CloudFrontClient, I would work on a PR.

**Comment by driesvints** [comment]
I think it's best if you do this in your own codebase. If you think this is of interest for the framework you can open an issue at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework.
