### ISSUE TITLE
How to pull queue data from SQS pushed using another server?

### ISSUE THREAD

**Issue by ftennali** [laravel/framework#26805]
I have two server 1st server push the value to the SQS and 2nd server retrieve it from the SQS but 2nd wont call the handle function present in the job, How can I achieve it using two laravel fremwork (one for data push and one for pull and it should work on "php artisan queue:work" command)

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
