### ISSUE TITLE
Missing dependency: nexmo-notification-channel

### ISSUE THREAD

**Issue by edgrosvenor** [laravel/framework#26818]
- Laravel Version: 5.7.6
- PHP Version: 7.2.2
- Database Driver & Version: 

### Description:

When running composer update, I get the following error: 

- laravel/framework 5.7.x-dev requires laravel/nexmo-notification-channel ^1.0 -> no matching package found.

I'm guessing this has something to do with it: https://github.com/laravel/framework/pull/26689

### Steps To Reproduce:

composer update

**Comment by driesvints** [comment]
I'm able to update so I think you might need to add the `--with-dependencies` flag in your case.

**Comment by edgrosvenor** [comment]
@driesvints - Same result.

**Comment by edgrosvenor** [comment]
[Composer\DependencyResolver\SolverProblemsException]
  Problem 1
      - The requested package laravel/nexmo-notification-channel could not be found in any version, there may be a typo in the package name.
    Problem 2
      - Installation request for laravel/framework 5.7.* -> satisfiable by laravel/framework[5.7.x-dev].
      - laravel/framework 5.7.x-dev requires laravel/nexmo-notification-channel ^1.0 -> no matching package found.
    Problem 3
      - laravel/framework 5.7.x-dev requires laravel/nexmo-notification-channel ^1.0 -> no matching package found.
      - rap2hpoutre/laravel-log-viewer dev-master requires illuminate/support 4.2.*|5.* -> satisfiable by laravel/framework[5.7.x-dev].
      - Installation request for rap2hpoutre/laravel-log-viewer dev-master -> satisfiable by rap2hpoutre/laravel-log-viewer[dev-master].

  Potential causes:
   - A typo in the package name
   - The package is not available in a stable-enough version according to your minimum-stability setting
     see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
   - It's a private package and you forgot to add a custom repository to find it

  Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by edgrosvenor** [comment]
Though to be fair, this might be more of a composer / packagist issue since I can do this:

composer search laravel/nexmo-notification-channel

and I get

laravel/nexmo-notification-channel Nexmo Notification Channel for laravel.
laravel/nexmo-notification-channel Nexmo Notification Channel for laravel.

**Comment by driesvints** [comment]
Yeah I think we're missing something here. The package can be found on packagist: https://packagist.org/packages/laravel/nexmo-notification-channel#v1.0.1

**Comment by edgrosvenor** [comment]
No. I'm not. I attempted to, just to see if that would work and let me get past the dependency, but it failed.

**Comment by driesvints** [comment]
Tried removing the vendor directory & deleting the composer.lock file and do a composer install?

**Comment by edgrosvenor** [comment]
OK. That did it. Thank you.
