### ISSUE TITLE
Optional notification channel packages.

### ISSUE THREAD

**Issue by dkulyk** [laravel/framework#26813]
- Laravel Version: 5.7.16
- PHP Version: 5.3
- Database Driver & Version: MariaDB 10.2

### Description:
Not all need to install nexmo or slack notifications

### Steps To Reproduce:
``` 
$ composer show | grep notification-channel
laravel/nexmo-notification-channel    v1.0.1             Nexmo Notification Channel for laravel.
laravel/slack-notification-channel    v1.0.3             Slack Notification Channel for laravel.
```

**Comment by CrixuAMG** [comment]
@dkulyk if I understood correctly, they will be removed for Laravel 5.8. These have been imported into the composer.json to make sure no breaking change is introduced for this version.

**Comment by staudenmeir** [comment]
See https://github.com/laravel/framework/pull/26689#issuecomment-443358120.
