### ISSUE TITLE
yarn-error.log present when creating a new Laravel project

### ISSUE THREAD

**Issue by henrieri** [laravel/framework#26812]
- Laravel Version: 5.7.16
- PHP Version: Irrelevant
- Database Driver & Version: Irrelevant

### Description:
yarn-error.log file present in root directory when creating new laravel project with laravel new command.
This issue has been here before, but it seems it has occurred again. It doesn't break anything, but the file itself is unnecessary and seems like a remnant of the build process.

### Steps To Reproduce:
1. Download http://cabinet.laravel.com/latest.zip
2. See yarn-error.log present in the unzipped directory.

OR 

1. `laravel new project`
2. See yarn-error.log in the root directory of the newly created project

**Comment by driesvints** [comment]
Hmm. You're right. Although I'm not sure how this is happening. What versions of NPM/Yarn do you have installed?

**Comment by ryanmortier** [comment]
Same here.

Yarn v1.12.3

**Comment by henrieri** [comment]
It's to do with whoever builds the release zip rather than our yarn version as it's present already before.
But it seems in this build file it doesn't appear anymore, so I'll close it. I guess it's something that accidentally seems to happen occasionally.
