### ISSUE TITLE
Retrieve original model

### ISSUE THREAD

**Issue by ionesculiviucristian** [laravel/framework#26814]
Hi. Is there a way (built in function) to retrieve the original model from an updated one? I don't want the original attributes but a new instance of the original model without a database query. 

As a side question, is there something to compare two model's attributes if there are the same?

**Comment by staudenmeir** [comment]
There is no built-in way. You could do something like this:

```php
$original = (new Model)->setRawAttributes($model->getOriginal());
```

**Comment by ionesculiviucristian** [comment]
Ok. I'll do that. Thanks.
