### ISSUE TITLE
AuthServiceProvider contains unused method Policies()

### ISSUE THREAD

**Issue by cthorne91** [laravel/framework#26810]
I was working on my AuthServiceProvider refactoring a large array assignment to the `$policies` property at the top of the file.  I came across something that looked broken inside the framework's AuthServiceProvider, but I wanted to check with the community to see if I am overlooking something.

Long story short, overwriting the framework's AuthServiceProvider's `public function policies()` inside my own AuthServiceProvider never gets called and so has no purpose as far as I can see. I would love to be able to overwrite the policies() function and return an array based on some logic.

The framework's AuthServiceProvider's `public function registerPolicies()` accesses the  `protected $policies` property directly instead of requesting the property through the policies() method.

Seems like it would make sense to update the following line 24 to `$this->policies()` as opposed to `$this->policies`? Hope I'm making sense.

https://github.com/laravel/framework/blob/f7dfb60e7bdb628b1cd7aaf344d3e93d694314ca/src/Illuminate/Foundation/Support/Providers/AuthServiceProvider.php#L17-L27

https://github.com/laravel/framework/blob/f7dfb60e7bdb628b1cd7aaf344d3e93d694314ca/src/Illuminate/Foundation/Support/Providers/AuthServiceProvider.php#L37-L45

I just ended up assigning the `$policies` property inside my `boot` method to get around this for now.

**Comment by staudenmeir** [comment]
The method was added as a public accessor for the protected `$policies`: https://github.com/laravel/framework/commit/6d8e53082c188c89f765bf016d1e4bca7802b025

**Comment by driesvints** [comment]
It's indeed just for fetching the property values if you need it.
