### ISSUE TITLE
Eager loading with specific fields should include Relationship's keys by default.

### ISSUE THREAD

**Issue by cirdog** [laravel/framework#26828]
- Laravel Version: 5.6.29
- PHP Version: 7.1.21
- Database Driver & Version: MySQL 5.7

### Description:
https://laravel.com/docs/5.7/eloquent-relationships
```
When using this feature, you should always include the id column in the list of columns you wish to retrieve.
```
The above warning seems to be not accurate since **not only** the 'id' column must be included, **but also** any other '**foreign key**' and '**local key**' of the relationship being eager-loaded, otherwise it'll fail without them being manually specified.

**First off**, the documentation is warning users inaccurately about the usage.

**Secondly**, it seems unnecessary for us to **manually specify** the foreign & local keys when using "with()", since the "relationship" already **dictates** their necessity in facilitating the eager-loading. Why not just **automatically include** them by default?

This could **greatly simplify** the with() usage that we only specify the fields we **want** but not the field we **need**, because the framework takes care of that for us, much like what Laravel is set out for.

### Steps To Reproduce:
```
Procurement\Main::with([
                'details:id,parent_id,asset_id,qty,price',
                'details.asset:id,type_id,code',
                'details.asset.type:id,description',
            ])->...
```
```
class Main extends Model
{
    public function details()
    {
        return $this->hasMany(Detail::class, 'id', 'parent_id');
    }
}

class Detail extends Model
{
    public function asset()
    {
        return $this->hasOne(Asset::class, 'id', 'asset_id');
    }
}

class Asset extends Model
{
    public function type()
    {
        return $this->hasOne(Type::class, 'id', 'type_id');
    }
}

class Type extends Model
{

}
```

**Comment by driesvints** [comment]
Heya, unfortunately we don't support that Laravel version anymore. Can you please try to upgrade and see if the problem persists?

**Comment by cirdog** [comment]
The quoted documentation clearly says 5.7 correct? It doesn't say we need to manually specify id instead of automatically handled by the framework, correct?

So why is this closed so quickly merely because I stated an outdated version? 

I can test any way I choose to but this quick closing of an issue is not allowing healthy discussion sadly.

**Comment by driesvints** [comment]
@cirdog you're reported an issue for Laravel 5.6

**Comment by staudenmeir** [comment]
This idea has been declined: https://github.com/laravel/framework/pull/23377

**Comment by cirdog** [comment]
@driesvints everyone knows that, and you've closed it, heh.

**Comment by driesvints** [comment]
@cirdog we don't support 5.6 anymore: https://laravel.com/docs/5.7/releases#support-policy

**Comment by staudenmeir** [comment]
There have also been multiple (unsuccessful) attemps to improve this sentence in the documentation.

**Comment by cirdog** [comment]
@staudenmeir Thanks man for the info!

And now THIS is healthy discussion.

But sadly the culture here is mechanical & counter-productive aside from the hot-blooded individuals.

**Comment by driesvints** [comment]
If all you're going to do is complain then please refrain from posting issues 🤷🏻‍♂️
