### ISSUE TITLE
Last migration creates table but is not registered in the migration table

### ISSUE THREAD

**Issue by NightravenJames** [laravel/framework#26829]
- Laravel Version: 5.7
- PHP Version: 7.2.9
- Database Driver & Version: **mysql**

### Description

Last migration creates table but is not registered in the migration table

### Steps To Reproduce

I have 14 migrations .
If I ran php artisan migrate 
The table is created but not registered as a ran migration
I've dropped the homestead database a couple of times

![image](https://user-images.githubusercontent.com/18738423/49930704-30cd0880-fed6-11e8-9606-10db577cc209.png)

**Comment by NightravenJames** [comment]
eventually when I want to refresh ,rollback or migrate for developement purposes I get this error telling me the table exists but however is not on the migration
`
vagrant@kakbima:~/code$ php artisan migrate
Migrating: 2018_12_13_091954_create_product_subcategories_table

   Illuminate\Database\QueryException  : SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'product_subcategories' already exists (SQL: create table `product_subcategories` (`id` int unsigned not null auto_increment primary key, `name` varchar(191) not null, `product_category_id` int unsigned not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')
`

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by dbhynds** [comment]
@NightravenJames Did you ever solve this issue? I'm experiencing the same thing, and cant figure out what's happening. The last migration in the list runs successfully but doesn't get recorded in the migrations table.

**Comment by NightravenJames** [comment]
Nope always had to drop the last table in the database then . Migrate it again , only then will it be recorded on the database
