### ISSUE TITLE
Laravel 5.7.17 missing translation method for starts_with

### ISSUE THREAD

**Issue by Robert-Hansen** [laravel/framework#26821]
- Laravel Version: 5.7.17
- PHP Version: 7.2
- Database Driver & Version:

### Description:
when using 'starts_with:test1,test2' it doesn't replace ":values" with test1 and test2, i been looking into framework/src/Illuminate/Validation/Concerns/ReplacesAttributes.php seems like it's missing the method to replace it

**Comment by themsaid** [comment]
PR already opened.
