### ISSUE TITLE
Laravel generating two different Signatures and causing a 403.

### ISSUE THREAD

**Issue by agentmarine** [laravel/framework#26834]
- Laravel Version: 5.7.*
- PHP Version: 7.2
- Database Driver & Version: NA

### Description:
I am generating a URL for someone to use to quickly access a page, but every time I generate a SignedRoute and navigate to it I get a 403 Invalid Signature

I've checked this by dumping out the variables within UrlGenerator

`"5958bba0a1843035a7514bdb12240f5d87ad1414d2c18f8676d867116b1945cc"` (original)
`"0a62b4e9bee046c02c07136c10b5e1e1924b2ede7034c65966ff5103d507f5e9"` (generated 2nd)

TargetURL: http://psgateway.eu.ngrok.io/autologin?cart=34&user=2

I've got nothing in place to modify the URL and I'm using a base install of Valet to serve the site, would anyone be able to provide some assistance with this? (i can't find anything referencing this issue on google, and larachat on slack is very slim on knowledge with SignedRoutes.)

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by agentmarine** [comment]
@driesvints I have spent a lot of time in Larachat and StackOverflow today trying to figure this one out.

**Comment by driesvints** [comment]
@agentmarine can you post some links to these discussions so we can gather some info from them?

**Comment by agentmarine** [comment]
https://larachat.slack.com/archives/C039F76DN/p1544701016284400

https://larachat.slack.com/archives/C039F76DN/p1544703189303200

I couldnt find any thing relevant on SO.

**Comment by driesvints** [comment]
I'll need more info and/or code to debug this further. Please post relevant code like models, jobs, commands, notifications, events, listeners, controller methods, routes, etc. You may use https://paste.laravel.io to post larger snippets or just reply with shorter code snippets. Thanks!

**Comment by agentmarine** [comment]
> app/Notifications/ShippingRateAssigned.php

  ```
 public function toMail($notifiable)
    {
        return (new MailMessage)
            ->line('Thank you for placing your order with us!.')
            ->line('In order for us to continue with your order we require you to make a payment for the order!.')
            ->action('Make a payment', URL::SignedRoute('autologin', ['user' => $this->cart->user, 'cart' => $this->cart]))
    }
```
>URL Generated

`https://psgateway.eu.ngrok.io/autologin?cart=34&user=2&signature=5958bba0a1843035a7514bdb12240f5d87ad1414d2c18f8676d867116b1945cc`

>autologin.blade.php

```
Route: "http://psgateway.eu.ngrok.io/autologin?cart=34&user=2"
Key (I'll regen this after): "base64:HPRasXztNozDBzwmo6i5VsFiHX9cLic3J+GpGpktLms="
New Sig: "0a62b4e9bee046c02c07136c10b5e1e1924b2ede7034c65966ff5103d507f5e9"
Orig Sig: "5958bba0a1843035a7514bdb12240f5d87ad1414d2c18f8676d867116b1945cc"
```

**Comment by driesvints** [comment]
This is just a wild guess but did you set the `APP_URL` to be the same as which is used which generated the signed route? Not 100% sure if it's relevant.

**Comment by driesvints** [comment]
You've set it to https ut the route you posted above is http?

**Comment by agentmarine** [comment]
The route in question is the following

```
Route::get('/autologin', function (Request $request) {
    Auth::login($request->query('user'));
    
    return redirect()->route('order.checkout', $request->query('cart'));
    })->name('autologin')->middleware('signed');
```

**Comment by agentmarine** [comment]
All my routes are forced to HTTPS with `\URL::forceScheme('https');` in the boot method of the AppServiceProvider.

**Comment by driesvints** [comment]
Yeah but I think you need to change the `APP_URL=https://psgateway.eu.ngrok.io` to `APP_URL=http://psgateway.eu.ngrok.io` no?

**Comment by agentmarine** [comment]
doesnt make any difference, I've just tried it.

**Comment by driesvints** [comment]
Have you tried disabling the `URL::forceScheme('https');` and using `APP_URL=http://psgateway.eu.ngrok.io` ?

**Comment by agentmarine** [comment]
that seems to have worked, however, now the site isn't operating under HTTPS.

**Comment by agentmarine** [comment]
I did, and I run through valet share with a hostname. 

the new Url generated by the urlGenerator was this http://psgateway.eu.ngrok.io/autologin?cart=34&user=2&signature=0a62b4e9bee046c02c07136c10b5e1e1924b2ede7034c65966ff5103d507f5e9

which of course would immediately take the user to a HTTP version with no redirect because im not enforcing HTTPS at this point.

**Comment by agentmarine** [comment]
I believe the issue is related with signedRoute(...) which actually uses $this->route() rather than $this->secureRoute()..

potentially a new method might be required for a securedSignedRoute(....) which uses SecureRoute() rather than route()

**Comment by driesvints** [comment]
Ah, think I know what's going on. See the note at https://laravel.com/docs/5.7/valet#sharing-sites

I don't think this is currently possible, sorry. 

Pissuble related: https://github.com/laravel/valet/issues/504

**Comment by agentmarine** [comment]
Thanks for the reply @driesvints I do think we can probably just expand the current functionality just to use the secureRoute function, which would allow us to enforce the use of HTTPS routes leaving the .env as http:// etc..

**Comment by driesvints** [comment]
Okay, well I'm going to close this as this seems more a Valet issue than a framework issue. Hope you figure it out. Good luck!

**Comment by agentmarine** [comment]
Ok I think I've finally solved this issue, its related to the UrlGenerator. it seems that the $request->url() function doesnt respect https and will return a http based url. I would probably put forward a a change to use url()->current() to get the url that way which does enforce the protocol that is being passed through.

  ```
  public function hasValidSignature(Request $request, $absolute = true)
    {

        $url = $absolute ? url()->current() : '/'.$request->path();

        $original = rtrim($url.'?'.Arr::query(
            Arr::except($request->query(), 'signature')
        ), '?');

        $expires = $request->query('expires');

        $signature = hash_hmac('sha256', $original, call_user_func($this->keyResolver));

        return  hash_equals($signature, (string) $request->query('signature', '')) &&
               ! ($expires && Carbon::now()->getTimestamp() > $expires);
    }
```

**Comment by davefv** [comment]
I have same problem on Laravel 7

**Comment by troovers** [comment]
I had the same issue. You can enforce the use of HTTPS, after which a signed route will always be prefixed with https:// instead of http://:
https://stackoverflow.com/a/62111949/6007740
