### ISSUE TITLE
app()->call('class@method', $parameter); call the method with one more extra parameter

### ISSUE THREAD

**Issue by imanghafoori1** [laravel/framework#26837]
- Laravel Version: 5.5.44
- PHP Version: 7.2.9
- Database Driver & Version:

### Description:
it seems when I use app()->call(... and I pass the second argument as an array of parameters
in case the parameters array begins with a closure the actual the method is called with wrong parameters.
the first parameters becomes an empty sting and the rest are the actual parameters.

The actual parameters passed into app()->call is like this :
![image](https://user-images.githubusercontent.com/6961695/49955462-13b92980-ff18-11e8-9e6e-5b8494accf1b.png)

but it seems laravel IOC adds an empty string at the beginning of the array and the method is called with 3 arguments in this case.

### Steps To Reproduce:
1. you can clone the https://github.com/imanghafoori1/laravel-heyman repo
2. check out the devel branch.
3. composer install

see : 
Imanghafoori\HeyMan\Conditions\ConditionsFacade class at line 12
and
Imanghafoori\HeyMan\Conditions\Traits\Callbacks line 9

see the comments there as a hint

run the tests and they pass

if you remove the $emptyString parameter from 'closureAllows' and 'methodAllows' method tests fail.
there is no reason for that parameter to exist.

**Comment by driesvints** [comment]
I'm not sure you can use it like that. This behavior is also not documented and I believe you're not suppose to use it outside the framework like this. Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by imanghafoori1** [comment]
outside the framework ?!
I don't know, but it is a normal laravel package that is using regular laravel IOC container feature `app()->call() ` to call a method on a class with desired parameters.

**Comment by imanghafoori1** [comment]
In fact it is not related to any package

This example show the exact same bug `inside` laravel: 


```php
app()->call('\App\A1@myMethod', [ function(){ }  ]);
```


```php

namespace App;

class A1
{
    function myMethod($a, $b = null)
    {
        dd($a, $b);
    }
}
```
here $a should a closure but is it not.
$b will the closure !
