### ISSUE TITLE
Using illuminate/mail outside of Laravel with driver log breaks

### ISSUE THREAD

**Issue by luceos** [laravel/framework#26833]
- Laravel Version: 5.7.17
- PHP Version: 7.2
- Database Driver & Version: MySQL 5.7

### Description:

[This recent change](https://github.com/laravel/framework/commit/5ff17b497a23ee4a0ab4333a05246a5cc879ab89) by @sebdesign has caused an issue when using illuminate/mail outside of Laravel. The `LoggerInterface` in our situation is a `Monolog\Logger` instance, as a result the `channel` method is not available to us as per [our unit test](https://travis-ci.org/flarum/core/jobs/467492972).

### Steps To Reproduce:

- Bind LoggerInterface to Monolog\Logger
- Instantiate the Mail Transport manager with driver log

```
1) Flarum\Tests\Install\DefaultInstallationCommandTest::allows_forum_installation
Error: Call to undefined method Monolog\Logger::channel()
/home/travis/build/flarum/core/vendor/illuminate/mail/TransportManager.php:166
/home/travis/build/flarum/core/vendor/illuminate/support/Manager.php:96
/home/travis/build/flarum/core/vendor/illuminate/support/Manager.php:71
/home/travis/build/flarum/core/vendor/illuminate/mail/MailServiceProvider.php:102
```

**Comment by driesvints** [comment]
Hmm you're right. We could check for a specific instance in the method and use the previous behavior if it's an instance without the `channel` method?

**Comment by sebdesign** [comment]
I'll see if I can come up with a solution.

**Comment by TBlindaruk** [comment]
Looks like that problem are solved in https://github.com/laravel/framework/pull/26842 and https://github.com/laravel/framework/pull/26855 PRs
