### ISSUE TITLE
Request locale property (herited from symfony) isn't changed when using App::setLocale($locale);

### ISSUE THREAD

**Issue by Lelectrolux** [laravel/framework#26832]
- Laravel Version: 5.7
- PHP Version: 7.1

### Description:

When using `App::setLocale($locale);`, the `$locale` property of the current Request isn't set to the new locale.

https://github.com/laravel/framework/blob/5.7/src/Illuminate/Foundation/Application.php#L1051

It bit me today when I tryied this code using a translated slug field stored as JSON :

```php
public function show(Request $request, string $model)
{
    return Model::query()
        ->where("slug->{$request->getLocale()}", $model)
        ->firstOrFail();
}
```

I tried to search for a similar issue that would explain the current behavior, but I didn't find any.

I might be overlooking something, but it seems like a bug and an easy fix to me.

**Comment by driesvints** [comment]
That's because the request locale shouldn't be changed. It's the locale the request was set for. The application locale can be changed *during* the request and you should use that one in your method call.

**Comment by Lelectrolux** [comment]
@driesvints Right now the request locale is not even set. It always use the default.

In symfony, the request locale property is THE way to track the current locale in your app.

https://symfony.com/doc/current/translation/locale.html

The equivalent to Laravel's `app()->setLocale($locale);` in symfony is setting that request property.

**Comment by driesvints** [comment]
Hmm yeah I can see how that be confusing. At the moment it works as the docs describe here under "Configuring The Locale": https://laravel.com/docs/5.7/localization

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework.
