### ISSUE TITLE
Not correct raw select witch IF - convert field type

### ISSUE THREAD

**Issue by ADSoftTeam** [laravel/framework#26847]
- Laravel Version: 5.6.25
- PHP Version: 7.2
- Database Driver & Version: MySQL 5.6

### Description:
Not correct raw select witch IF

i 'am find bug in DB fasade - selectRaw() and select(DB::raw()) sql expression include's directive IF - change output type field

### Steps To Reproduce:

example: selectRaw("IF(1=1,1,'string')") - result  = '1' - as string, but not integer, How??
 if two parametr - integer, 
selectRaw("IF(1=1,1,2)") - result = 1 - is integer - correct

**Comment by driesvints** [comment]
Heya, unfortunately we don't support this version anymore. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.
