### ISSUE TITLE
'verified' middleware does not work with 'auth' middleware?

### ISSUE THREAD

**Issue by ryanmortier** [laravel/framework#26843]
- Laravel Version: 5.7.17 (latest)
- PHP Version: 7.2.13
- Database Driver & Version: MySQL 5.7

### Description:
When adding `->middleware(['auth', 'verified'])` to a route, the verified middleware doesn't apply.

### Steps To Reproduce:
- `laravel new blog`
- `php artisan make:auth`
- Create database and modify `.env` file
- `php artisan migrate`
- `php artisan tinker` then:
```
\App\User::create([
    'name' => 'Test User',
    'email' => 'test@example.com',
    'password' => bcrypt('secret'),
]);
```
- Add `$this->middleware(['auth', 'verified']);` to the `HomeController` constructor
- Login and the home view is still shown even though you haven't verified the email address.

**Comment by driesvints** [comment]
It's normal that your login view is still shown as this is controlled by the `LoginController` and not the `HomeController`. You're sure you're not mixing up the "welcome" view and "home" view?

**Comment by ryanmortier** [comment]
It's definitely not the welcome view. It's specifically the `resources/views/home.blade.php` view, the one that says "You are logged in!" and is presented in the `HomeController` index method, the same controller that has both those middleware attached.

**Comment by driesvints** [comment]
Can you post your `User` model?

**Comment by ryanmortier** [comment]
Since this is a fresh install it's the default:

```php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}
```

**Comment by ryanmortier** [comment]
Are you able to reproduce the issue? It should only take 30 seconds.

**Comment by driesvints** [comment]
You need to implement the `MustVerifyEmail` interface: https://laravel.com/docs/5.7/verification#introduction

That should do it.

**Comment by ryanmortier** [comment]
Oops, sorry for wasting your time.

**Comment by kelvinthiongo** [comment]
@ryanmortier infact you didn't waste our tym, very many people forget this
