### ISSUE TITLE
Wrong method signature in Router Facade.

### ISSUE THREAD

**Issue by willypuzzle** [laravel/framework#26849]
- Laravel Version: 5.7.17
- PHP Version: 7.2

### Description:
In framework/src/Illuminate/Support/Facades/Route.php there is this line: 

* @method static \Illuminate\Routing\Router|\Illuminate\Routing\RouteRegistrar group(array|\Closure|string $attributes, \Closure|string $routes)

This method in the case it returns a RouteRegistrar (such as reported in [documentation](https://laravel.com/docs/5.7/routing#route-groups)) it has only one parameter. 

So my IDE warnings me about wrong method usage when, in fact, I'm using it correctly.

**Comment by driesvints** [comment]
It actually pipes the call to the router itself so I think the hint is correct. Can you share the particularly route which is causing trouble?

**Comment by willypuzzle** [comment]
```
Route::namespace('Idsign\Permission\Http\Controllers')->prefix('/acl')->group(function (){
     Route::prefix('/sections')->group(function (){
         Route::get('get-tree', 'SectionController@getTree');
     });
});
```

In both case my ide warning me but the route work as explained in documentation you provided

**Comment by driesvints** [comment]
If I use that example my IDE doesn't warns me. If you look at the examples, they all call the `group` method after a different method call. If you use `Route::group` directly you'll indeed need to provide two arguments.
