### ISSUE TITLE
Resolving console commands inconsistently

### ISSUE THREAD

**Issue by sandervanhooft** [laravel/framework#26845]
- Laravel Version: 5.7.17
- PHP Version: 7.2
- Database Driver & Version: not relevant

### Description:
While working on an `assertCommandCalled` Laravel test helper (which I would 💗) for Laravel Zero (https://github.com/laravel-zero/laravel-zero/issues/178), I noticed that commands called via another command are resolved directly from the app container. While the entry point for calling commands from the console is `Illuminate\Foundation\Console\Kernel`.

From what I can see the behaviour is the same. But for the implementation of `assertCommandCalled` I need to swap both the Kernel and the Command class, while I would expect only swapping the Kernel would do.

That's why I'd suggest to alter the Command class to call the commands via the Kernel instead of resolving them directly from the app container.

_(`callSilent(...)` methods are obviously having the same issue)_

### Steps To Reproduce:

Current `Illuminate\Foundation\Console\Kernel`:
```php
    /**
     * Run an Artisan console command by name.
     *
     * @param  string  $command
     * @param  array  $parameters
     * @param  \Symfony\Component\Console\Output\OutputInterface  $outputBuffer
     * @return int
     */
    public function call($command, array $parameters = [], $outputBuffer = null)
    {
        $this->bootstrap();

        return $this->getArtisan()->call($command, $parameters, $outputBuffer);
    }
```

Current `Illuminate\Console\Command`:

```php
/**
     * Call another console command.
     *
     * @param  string  $command
     * @param  array   $arguments
     * @return int
     */
    public function call($command, array $arguments = [])
    {
        $arguments['command'] = $command;

        return $this->getApplication()->find($command)->run(
            $this->createInputFromArguments($arguments), $this->output
        );
    }
```

### Possible solution (direction):

One option may be to adapt the `call` method in the `Command` class:

```php
/**
     * Call another console command.
     *
     * @param  string  $command
     * @param  array   $arguments
     * @return int
     */
    public function call($command, array $arguments = [])
    {
        $arguments['command'] = $command;

        return app('Illuminate\Foundation\Console\Kernel')->call(
            $command,
            $this->createInputFromArguments($arguments),
            $this->output
        );
    }
```

Another option may be to introduce a new class similar to the `Event\Dispatcher` class.

I'd love this class to be named `GoCommando` (pun intended), but there's probably a better name out there. 😉

Jokes aside, let me know if you agree (@driesvints) and what would make a nice PR to fix it. I'm happy to draft a PR.

**Comment by driesvints** [comment]
I don't think this is really a bug but rather just the way it currently works. This is more of a behavior change I believe. It's best to post this at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Good luck!

**Comment by sandervanhooft** [comment]
Done, thanks! 😄
