### ISSUE TITLE
NotifiableContract

### ISSUE THREAD

**Issue by FrontEndCoffee** [laravel/framework#26848]
There is a [Notifiable](https://github.com/laravel/framework/blob/5.7/src/Illuminate/Notifications/Notifiable.php) trait, but there is no interface/contract to go with it. This would be a great feature for the sake of type-hinting.

**Comment by driesvints** [comment]
Heya, thanks for submitting this. This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.
