### ISSUE TITLE
app()->call() has a problem calling class methods with default parameter values

### ISSUE THREAD

**Issue by imanghafoori1** [laravel/framework#26851]
- Laravel Version: 5.7.14
- PHP Version: 7.2.9

### Description:
app()->call() has a problem calling class methods with default parameter values.

### Steps To Reproduce:
1. A  fresh installation of laravel.
2 . define a simple class in app folder
```php
namespace App;

class Foo
{
    function bar($a, $b, $c = 'my C')
    {
        dd("a : $a", "b : $b", "c : $c");
    }

    function baz($a = 'my A', $b  = 'my B' , $c = 'my C')
    {
        dd("a : $a", "b : $b", "c : $c");
    }
}

```

3. define a route in web.php
```php

Route::get('/bar', function () {
    app()->call('\App\Foo@bar', ['a', 'b'] );
});

Route::get('/baz', function () {
    app()->call('\App\Foo@baz', ['a', 'b', 'c'] );
});

```
4. php artisan serve, then visit '/bar' and '/baz' in the browser, you will get totally unexpected results.

Note that this feature is documented in the docblocks like this:

 Call the given Closure / class@method and inject its dependencies.

vendor/laravel/framework/src/Illuminate/Container/Container.php

line 563

I have created the PR to fix this bug. and it is very easy to fix.

**Comment by imanghafoori1** [comment]
https://github.com/laravel/framework/pull/26852

**Comment by driesvints** [comment]
This was merged now

**Comment by imanghafoori1** [comment]
@driesvints Would it be included in the previous LTS versions? for example v5.5? 
or I have to create separate PRs for each?
because this bug is biting the users of my laravel package

**Comment by driesvints** [comment]
@imanghafoori1 you can send this as a separate PR to the 5.5 branch.
