### ISSUE TITLE
Computed properties that return a Carbon instance won't be casted

### ISSUE THREAD

**Issue by samnowakowski** [laravel/framework#26868]
- Laravel Version: 5.7
- PHP Version: 7.2
- Database Driver & Version: MySQL 5.7.24

### Description:

Computed propertys that return a Carbon instance won't be casted by returning a json object of the model. Neither ```php protected $dates = ['departureTime']```nor ```php protected $casts = ['depatureTime' => 'date:y-m-d'];```work.

### Steps To Reproduce:

Create a model with a computed property

```php
class Track extends Model
{
	/** Attention: Try this **/
	protected $dates = ['departureTime'];

	/** OR this **/
	protected $casts = ['departureTime' => 'date:y-m-d'];


	 /**
     * Append computed properties automatically.
     *
     * @var array
     */
     protected $appends = ['departureTime'];

	/**
     * Get departed time.
     *
     * @return Carbon
     */
	public function getDepartureTimeAttribute() {
		/** 
		* Avoiding logical mistakes I just 
		* return current timestamp
		*/
		
	    return Carbon::now();
	}

	/** do other stuff **/
}
```
and you''l get 
```json "departureTime":{"date":"2018-12-16 08:27:58.965143","timezone_type":3,"timezone":"Europe\/Berlin"}```

Actually it should return just the time string.

**Comment by driesvints** [comment]
This is because attribute accessors override the casting behavior.
