### ISSUE TITLE
Foreign key name incoherent methods in relation classes 

### ISSUE THREAD

**Issue by NastuzziSamy** [laravel/framework#26866]
First, thank you very much for this amazing framework! 

Retrieving the foreign key name from a relation is a bit tricky. For example: 
- For a `belongsTo` relation, to get the desired name, you have to call `getForeignKey` method 
- For a `hasOne` relation, `getForeignKeyName` 

Is it possible de define both in order to avoid breaking changes and confusions/undefined method errors? 

Thanks again guys!

**Comment by staudenmeir** [comment]
This will be fixed in Laravel 5.8: #26374

**Comment by NastuzziSamy** [comment]
Thank you, should have checked before
