### ISSUE TITLE
2 level deep nested array distinct validation

### ISSUE THREAD

**Issue by dsounded** [laravel/framework#26862]
- Laravel Version: Laravel Installer 2.0.1 / Laravel Framework 5.6.39
- PHP Version: 7.2.9
- Database Driver & Version: not important

### Description:
There is no way to proper validate `array distinct` if it's 2 level deep.

### Steps To Reproduce:
I have validation `'content.*.content.*.order' => 'required|integer|distinct',` which works I guess as it should, but there is no way to validate `content.*.order` this part only within higher level of `content`, basically I'am getting errors like `"message": "{\"content.0.content.0.order\":[\"The content.0.content.0.order field has a duplicate value.\"],\"content.1.content.0.order\":[\"The content.1.content.0.order field has a duplicate value.\"]}”` but that's not the case, this error above should be valid, in the same time this one 

`"message": "{\"content.0.content.0.order\":[\"The content.0.content.0.order field has a duplicate value.\"],\"content.0.content.1.order\":[\"The content.0.content.1.order field has a duplicate value.\"]}”`

is the case where I really need validation to fail, any suggestions ?

**Comment by dsounded** [comment]
I can get size of `content` and then build dynamically rules likes this:

```
$rules = [];
        if (!is_null($request->get('content'))) {
            foreach (range(0, count($request->get('content')) - 1) as $index) {
                $rules["content.$index.content.*.order"] = 'required|integer|distinct';
            }
        }
```

but that looks not much pretty

**Comment by driesvints** [comment]
@dsounded which version of Laravel are you using?

**Comment by dsounded** [comment]
Laravel Framework 5.6.39

**Comment by driesvints** [comment]
Heya, unfortunately we don't support this version anymore. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.

**Comment by dsounded** [comment]
@driesvints it's ok, please, provide a solution for newer version because I've checked all the docs and see no needed point.

**Comment by akkivarma10** [comment]
Hi, this issue is still present in latest laravel v8.x as well. Basically there is no way to supply an option that it needs to check level 1 only & not all levels of array. Can you provide some suggestions @driesvints

**Comment by zapz666** [comment]
whatsapp 9961964374

**Comment by kovalovme** [comment]
2021

Any advice?

**Comment by siarheipashkevich** [comment]
@driesvints any suggestions?
