### ISSUE TITLE
Custom Intermediate Table Models

### ISSUE THREAD

**Issue by mfoncho** [laravel/framework#26864]
- Laravel Version: 5.7.0
- PHP Version: 7.1
- Database Driver & Version: mysql

### Description:
custom pivot table name being ignored. The I write custom pivots is for cleaner code and 
modular design where i can swap a pivot out for some other pivot table on the fly. Laravel query builder 
seams to ignore the declared table name on the pivot table and builds a pivot table name based on
```belongsToMany``` class name, if the pivot table is not explicitly declared when declaring he relationship which  defeats the purpose of writing a CustomPivot class. 

```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    /**
     * The users that belong to the role.
     */
    public function users()
    {
        return $this->belongsToMany('App\User', 'custom_user_role')->using('App\CustomUserRole');
    }
}
``` 

### Steps To Reproduce:
```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    /**
     * The users that belong to the role.
     */
    public function users()
    {
        return $this->belongsToMany('App\User')->using('App\CustomUserRole');
    }
}
```
```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Relations\Pivot;

class CustomUserRole extends Pivot
{
    protected $table = 'custom_user_role';
}
```

**Comment by mfoncho** [comment]
@standaniels then what will be the benefit of writing a pivot table because for some reason observing the the pivot table model does not good as it doesn't fire any events [strange!!]

**Comment by staudenmeir** [comment]
> then what will be the benefit of writing a pivot table?

Do you mean pivot *model*?

**Comment by mfoncho** [comment]
@staudenmeir 
pivot model
```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Relations\Pivot;

class CustomUserRole extends Pivot
{
    protected $table = 'custom_user_role';
}
```

**Comment by staudenmeir** [comment]
It allows you to query the pivot table directly:

```php
CustomUserRole::where(...)->get();
```

**Comment by mfoncho** [comment]
@staudenmeir wouldn't it be more elegant to query the actual Model than the "Pivot Models":
```php
User::where(...)->where('custom_user_role...')->select('custom_user_role.*')->get();
```
Yes it look longer but this will integrates and is comprehensibly just by looking at it. Pivot tables are not meant to hold too much information, but sever as a mapping between table rows, and if they acted as actual models and are initialized as pivots 
```php 
$this->belongsToMany(Model::class)->using(CustomUserRole::class);
``` 
observing them would be very useful as hooking into their (pivot models) events would be a good feature. I have seen terrible hacks on stack-overflow from others trying to obverse  the pivot table.
Okay lets look at this. having declared the pivot model as having timestamps,
```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Relations\Pivot;

class CustomUserRole extends Pivot
{Illuminate\Database\Eloquent\Relations\Pivot;
    /**
    * Pivot table has both the created_at and updated_at fields
    */
    public $timestamps = true;
}
```
That design would be intuitive after using the laravel framework right, but NOPE its not too. You must explicitly declare ```witTimestamps()``` to get timestamps working
```php
$this->belongsToMany(Model::class)->using(CustomUserRole::class)->withTimestamps();
``` 
@staudenmeir I think this is a bug from the pivot table implementation, the pivot table extends the ```Illuminate\Database\Eloquent\Model``` and uses the ```Illuminate\Database\Eloquent\Relations\Concerns\AsPivot```  meaning the pivot model should be:

   - observable
   - timestamp-able

except the underlying implementation of ```using``` just returned the relation query instance

**Comment by staudenmeir** [comment]
My example of "query the pivot table directly" was more of a theoretical one. There isn't really a use case for specifying a `$table` in the pivot model.

See #14988 for pivot events, especially the last comment.

**Comment by driesvints** [comment]
As @staudenmeir has explained we're probably not going to be adding support for this anytime soon. There's already a package for this which does what you want I believe: https://github.com/fico7489/laravel-pivot

**Comment by rasmuscnielsen** [comment]
For anyone interested my personal workaround for this is to move the relationship instantiation logic to the pivot model. 

This has the added benefit that the pivot configuration can be shared by both `User` and `Role` model. 

**Model**
```php
class Role extends Model
{
    public function users()
    {
        return CustomUserRole::pivot($this, User::class);
    }
}

```

**Pivot**
```php
class CustomUserRole extends Pivot
{
    protected $table = 'custom_user_role';

    public static function pivot(Model $from, string $to)
    {
        return $from
            ->belongsToMany($to, (new static)->getTable())
            ->using(static::class);
           // Add more tweaks as you please here, ie: ->withTimestamps()->withPivot(...) etc
    }
}
```
