### ISSUE TITLE
[Regression] Infinite loop in Model()->getQueueableRelations() with circular dependency

### ISSUE THREAD

**Issue by sylouuu** [laravel/framework#26877]
- Laravel Version: 5.7.17
- PHP Version: 7.2.13
- Database Driver & Version: MySQL 5.7.24

### Description:

When you pass a model to a job constructor and this model contains a circular dependency, you are getting an infinite loop. Either your receive an "Allowed memory size of" error or a timeout.

The memory error is inside `Model()->getQueueableRelations()`.

I upgraded the framework from 5.5 to 5.7 and I spent a whole to find out it was related to this. That's why I'm marking this as a "regression".

### Steps To Reproduce:

Sorry for not having more time to post a complete step by step on a fresh install but I'm sharing what I've found.

For exemple on a `User` model, add a `UserBilling` `hasOne` relation. Inside `UserBilling` add a `User` `belongTo` relation (because the `user_billing` table contains a `user_id` foreign key), even if you won't do something like `$user->userBilling->user`.

To fix this issue, I had to do this before dispatching the job (in my case, a mailable in queue with `Mail::to()`):

```php
$userBilling = new UserBilling();
$userBilling->blabla = 'blabla';
$userBilling->user()->associate($user);
$userBilling->save();

// The fix after upgrading Laravel to 5.7
$userBilling->unsetRelation('user');
```

This is issue may be related to https://github.com/laravel/framework/issues/2717

Best

**Comment by driesvints** [comment]
Heya. I'm sorry but I really don't know what to say otherwise than just don't introduce the circular dependency? There's no possible way for us to counter this I believe.

**Comment by sylouuu** [comment]
@driesvints At least, to try to understand why it was supported before and why not anymore?

"There's no possible way for us to counter this I believe." so how do you justify that I had to update my code after the upgrade?

I didn't see anything related to this in the changelog and from the versions comparisons.

Best

**Comment by jasonlfunk** [comment]
I also agree that this seems like a regression. Code that worked fine before upgrading now is broken.

**Comment by WouterFlorijn** [comment]
@driesvints I don't really understand. So does this mean I can't dispatch any jobs that have models with relations? Having model A that `hasOne` (or many) model B, and model B that `belongsTo` model A is not a circular dependency right? How come it can't be serialized?

**Comment by AidasK** [comment]
This should be reopened. Tried dispatching a job with loaded relations without a success and spent entire day on it. It's still an issue on laravel 8.5.x. At least it would be great to have an exception instead of SIGSEGV in php-fpm log where you don't have a stack trace

**Comment by Zakini** [comment]
Why do relations need to be serialised at all? Couldn't relations just be loaded as necessary in the job?

**Comment by tractorcow** [comment]
Came here trying to track down a segfault. After much havok, I decided to simply make getQueueableRelations non-recursive (stick to a single level) and it resolved my issue.


```php
public function getQueueableRelations(): array
    {
        $relations = [];

        foreach ($this->getRelations() as $key => $relation) {
            if (!method_exists($this, $key)) {
                continue;
            }

            $relations[] = $key;
        }

        return array_unique($relations);
    }
```

**Comment by AidasK** [comment]
@Zakini Good point. I think this "feature" has only drawbacks and no benefits, such as:
 - Inefficient model loading in jobs where unused relations are loaded from the previous controller. 
 - Inconsistency, not the same relations are loaded in the jobs as they were loaded in the controller. E.g. relations loaded before with the where clause will be loaded on the job without the where clause. Easy to make a bug.
 
 To overcome this I am using this trait on all the models:
 ```php
 trait QueueWithoutRelations
{
    public function getQueueableRelations()
    {
        return [];
    }
}
```
