### ISSUE TITLE
.env files are not overriding anymore, they are now overwriting

### ISSUE THREAD

**Issue by huenisys** [laravel/framework#26873]
- Laravel Version: 5.7.17
- PHP Version: 7.2
- Database Driver & Version: 10.3.10-MariaDB

### Description:
.env files are not working as they originally were. I thought we are using this library for convenience in addition to being able to save configuration per environment. 

Saving configuration is all good.

But the merging/override function is gone. For things to work correctly and as expected, now one has to copy a current/latest/complete .env to .env.something

Before, only the values that need to be overridden is required to be placed on .env.something

### Steps To Reproduce:

1. Serve on env=something. 
2. copy original .env.example to .env
3. replace APP_NAME value to SomethingNew
3. Have your .env.something file with just APP_URL=http://something.went.wrong
4. Visit site and notice, the app name is Laravel. 

In the past, since env=something, and .env.something does not have any statement for APP_NAME, then it should just fallback to SomethingNew from the modified .env

Did I miss anything?

**Comment by CrixuAMG** [comment]
Take a look at the `config/app.php` file, that contains some fallbacks that are used if the value is empty/not set in the .env file

**Comment by huenisys** [comment]
I'm sorry but you're not making sense.

Not sure if I'm having the right expectation.

In config/app.php, we have

```
'name' => env('APP_NAME', 'Laravel'),
```

If I'm on a 'something' environment.

and in my.

.env has

```
APP_NAME=SomeDefault
```

then in my .env.something has NO entry for APP_NAME

Should I expect the app name to display as SomeDefault?

Right now, it shows as Laravel.

**Comment by CrixuAMG** [comment]
Laravel is used as the fallback, which you can change in the `config/app.php`, just replace `'name' => env('APP_NAME', 'Laravel'),` with `'name' => env('APP_NAME', 'Something else'),`.

**Comment by huenisys** [comment]
I'm not concerned with what's the fallback on the config/app.php file.

I'm focused on the .env and .env.something

Since I'm on something environment, it should check if there's APP_NAME in there. Since there's none, it should not check the .env file next?

That's how it is in the past. So this system changed?

**Comment by CrixuAMG** [comment]
I've only worked with Laravel 5.0 and above, so I cannot say anything about the previous versions.
The versions I've used have always worked this way, where the second argument provided in the `env` or `config` function is used as the fallback value.

**Comment by huenisys** [comment]
Not really what I'm looking for. But thank you

**Comment by desertnightsky** [comment]
Then speak a language both parties understand. 

On Dec 17, 2018, at 1:05 AM, Paul Dominik <notifications@github.com> wrote:

Not really what I'm looking for. But thank you

**Comment by huenisys** [comment]
Oh so we are now speaking in gibberish language?

**Comment by imanghafoori1** [comment]
Situation:
we have two .env files: 1- .env  2- .env.devel
In the .env file we have 5 key-value but 
in the .env.devel we have only 2 key-value.

(the 2 keys are the same in both files )

Then In the 'devel' environment : 
You expect to have access to 3 missing key-values.(They should automatically be read from .env) as well as the 2 common keys which are read from the .env.devel

right ?

**Comment by huenisys** [comment]
Yeah. Only the 2 values from .devel is available. It's easily confirmed in a new repo download. This isn't how it is in the past. There was override. Now, presence of .devel totally ignores .env existence

**Comment by imanghafoori1** [comment]
ok, you may need a little bit of clean up in the comments @huenisys

**Comment by JayBizzle** [comment]
> .env files are not working as they originally were. 

When you say `originally`...are you talking about Laravel 4.2

**Comment by driesvints** [comment]
I don't believe this to be malfunctioning at this time. You can read more about this here: https://laravel.com/docs/5.7/configuration#environment-configuration

Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
