### ISSUE TITLE
Laravel 5.7 authentication session flow

### ISSUE THREAD

**Issue by bilogic** [laravel/framework#26889]
Hi,

I'm trying to implement a domain wide authentication (DWA) on top of the usual user authentication. The use case is to prevent a work-in-progress site from leaking to google/public.

1. Created scaffolding code using ```php artisan make:auth```
2. Log in via ```/login``` and is redirect to ```/home``` which shows the default ```You are logged in!```
3. When I reload ```/home```, I see that ```$this->session->id``` in ```SessionGuard.php``` has an ID value which I will refer to as A, the session also has 5 ```attributes```.
4. Next, I insert the ```$this->middleware("auth");``` into the route ```/product/{id}```'s controller's constructor and load it
5. I see that ```$this->session->id``` in ```SessionGuard.php``` has a brand new ID with 0 ```attributes```
6. This causes ```authenticate()``` in ```Authenticate.php``` middleware to throw an ```Unauthenticated``` exception and redirect me to ```/login```
7. As the browser loads ```/login```, ```$this->session->id``` in ```SessionGuard.php``` now shows the ID of A with the earlier 5 ```attributes```
8. ```/login``` results in ```RedirectIfAuthenticated.php``` middleware running and redirecting to ```/home```
9. As a result of the DWA, I'm unable to load ```/product/{id}```, it just keeps redirecting me to ```/home```

I believe #5 is a bug. My expectation is for ```/product/{id}``` to load session ID A so that 6, 7, 8, 9 does not happen and instead, ```/product/{id}``` is loaded.

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by bilogic** [comment]
ok will do thanks
