### ISSUE TITLE
BoundMethod::call is broken.

### ISSUE THREAD

**Issue by dkulyk** [laravel/framework#26886]
- Laravel Version: 5.7.18
- PHP Version: 5.2
- Database Driver & Version: MariaDB 10.2

### Steps To Reproduce:
`\Illuminate\Hashing\HashManager` - is an example.
```php 
app()->call(function(\Illuminate\Hashing\HashManager $hash){
}, ['log'=>'not a HashManager type']);

//Also
app()->call(function(\Illuminate\Hashing\HashManager $hash){
}, ['log' => 'not a HashManager type', 'hash' => new \Illuminate\Hashing\HashManager]);
```
Throws exception.
```
TypeError: Argument 1 passed to {closure}() must be an instance of Illuminate/Hashing/HashManager, string given
```

Works if:
- `$log` exists in function parameters;
- additional arguments is empty;

Related https://github.com/laravel/framework/pull/26852

**Comment by driesvints** [comment]
Where/why are you calling the `HashManager` like that? I don't think it's suppose to work like this?

**Comment by imanghafoori1** [comment]
Is this kind of usage is documented anywhere or any usage in the laravel source code like this ?!

But I get it you expect the log to be ignored automatically yes ?!

**Comment by gustavofabiane** [comment]
Like @dkulyk I was using the container 'call()' to call methods with parameter binding like in 'make/makeWith' ([Here](https://laravel.com/docs/5.5/container#resolving)), where the given parameters array keys are checked with the reflected parameters names from class constructor to be injected automatically. 

Actually this behavior still working in BoundMethod as previously expected but the parameter inversion in [this commit](https://github.com/laravel/framework/pull/26852/commits/73e3ffd6d9338c772a30b2bc3ba7f8d60d361d82) breaks it.

[This line](https://github.com/laravel/framework/blob/73e3ffd6d9338c772a30b2bc3ba7f8d60d361d82/src/Illuminate/Container/BoundMethod.php#L153-L154) in BoundMethod class (153) ensures it:
```php
        if (array_key_exists($parameter->name, $parameters)) {
            $dependencies[] = $parameters[$parameter->name];
```

**Comment by Quintile** [comment]
After updating my Lumen app to include the BoundMethod change, controller injections have stopped working. If I go into BoundMethod.php and revert the changes made here: https://github.com/laravel/framework/commit/881be813c3038b32a07a104ff8c322a8093300c9#diff-62fd60bbf5999df1027491ff843c6812L119 everything works again.

For example I've got a controller method:
`public function destroy(Buckets $buckets, int $id): JsonResponse`

With this commit, it throws an exception that destroy is expecting an instance of Buckets, but got string.

Once reverted, everything works as expected.

**Comment by BasMulders** [comment]
Same here. [Spatie's event-projector](https://github.com/spatie/laravel-event-projector/) is broken too because of the parameter inversion mentioned by @gustavofabiane. Related file: https://github.com/spatie/laravel-event-projector/blob/bbac6a7731910f38cb9d5f27961835a12ecd0ef3/src/EventHandlers/HandlesEvents.php#L36

**Comment by taylorotwell** [comment]
Reverted

**Comment by imanghafoori1** [comment]
@Quintile Can you tell me please which route is pointing to that controller method ?

I want to know how it is called. To create the missing tests.
