### ISSUE TITLE
Eloquent - WhereIn does not form SQL properly on MySQL View

### ISSUE THREAD

**Issue by starvsion** [laravel/framework#26899]
- Laravel Version: 5.7.16
- PHP Version:7.2.12
- Database Driver & Version: MariaDB 10.3.10 (MySQL) 

### Description:
When I am trying to do a whereIn on a column in a view, it does not form the proper SQL Query, thus throwing an error. 

### Steps To Reproduce:
1. SQL View
```sql
CREATE VIEW `holder_classes` AS
    (SELECT 
        `entity_holders`.`entity_id` AS `id`,
        `entities`.`class_id` AS `class_id`
    FROM
        (((`user_type_a`
        JOIN `account_holders` ON (`user_type_a`.`id` = `account_holders`.`holder_id`
            AND `account_holders`.`holder_type` = 'user_type_a'))
        JOIN `entity_holders` ON (`account_holders`.`id` = `entity_holders`.`account_holder_id`
            AND `entity_holders`.`entity_type` = 'entities'))
        JOIN `entities` ON (`entity_holders`.`entity_id` = `entities`.`id`))) UNION (SELECT 
        `entity_holders`.`entity_id` AS `id`,
        'user_type_b' AS `holder_type`,
        `user_type_b`.`id` AS `holder_id`,
        `account_holders`.`account_id` AS `account_id`,
        `entities`.`class_id` AS `class_id`,
        `entities`.`quantity` AS `quantity`
    FROM
        (((`user_type_b`
        JOIN `account_holders` ON (`user_type_b`.`id` = `account_holders`.`holder_id`
            AND `account_holders`.`holder_type` = 'user_type_b'))
        JOIN `entity_holders` ON (`account_holders`.`id` = `entity_holders`.`account_holder_id`
            AND `entity_holders`.`entity_type` = 'entities'))
        JOIN `entities` ON (`entity_holders`.`entity_id` = `entities`.`id`)))
```
2. Eloquent Query
```php
ShareHolderClass::where('class_id', function ($query) use($classList) {
                if (empty($classList)) {
                    return $query;
                }
                return $query->whereIn('class_id', $classList);
            })
...
```

Running this , will result in this error : 

```
"SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'where `class_id` in (?))' at line 1 (SQL: select * from `holder_classes` where `class_id` = (select * where `class_id` in (79)))
```
Apparently, the right SQL Query should be: 
```sql
SELECT * FROM holder_classes WHERE class_id IN (79)
```
So I opted to use : 
```
ShareHolderClass::whereRaw('class_id IN ('. explode(',', $classList.')');

```
And this works, but feels a bit hacky ... Would be nice if the select statement works out of the box. 

Anyways, thanks for the great work, Laravel Team :+1: ; Love ya all.

**Comment by staudenmeir** [comment]
Your query is incorrect, use `ShareHolderClass::whereIn('class_id', $classList)`:

**Comment by starvsion** [comment]
> Your query is incorrect, use `ShareHolderClass::whereIn('class_id', $classList)`:

I tried that as well, same result

**Comment by staudenmeir** [comment]
What result? This query produces the expected `SELECT * FROM holder_classes WHERE class_id IN (79)`.

**Comment by dkulyk** [comment]
Maybe you mean this:
```php
ShareHolderClass::when($classList, function ($query, $classList) {
    return $query->whereIn('class_id', $classList);
})
```

**Comment by miklcct** [comment]
Your original query is wrong.

`$query->where('column', $subquery)` means in SQL `WHERE column = subquery`, and you definite need a FROM clause in the closure.

I believe what you want is 
```
ShareHolderClass::where(
    function ($query) use ($classList) {
        if (empty($classList)) {
            return $query;
        }
        return $query->whereIn('class_id', $classList);
    }
)
```

This created a nested where which puts the where conditions in the subquery in () in the main course, i.e.
```
select * from `holder_classes` where (`class_id` in (?, ?, ?))
```

**Comment by driesvints** [comment]
Please try one of the suggestions above or otherwise one of the following support channels. If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
