### ISSUE TITLE
Different response format from method sum using eloquent vs Builder

### ISSUE THREAD

**Issue by ibrunotome** [laravel/framework#26894]
- Laravel Version: 5.7.17
- PHP Version: 7.2.13 
- Database Driver & Version: PostgreSQL 10.4, php modules: PDO, pdo_pgsql and pgsql.

### Description:
When I use the `->sum()` in a relationship I got the response in a different format than if I use `DB::raw`, but both of them call the same `sum` method of `Illuminate\Database\Query`.

When using in DB::raw I got the response in string format (what I expect) instead of scientific notation.

### Steps To Reproduce:

```php
>>> Parent::with(['children:id,amount'])->find('1e207119-a5cb-4249-b10f-1d6ba42f4130')->children->sum('amount');
=> 1.3E-5
>>> DB::table('children')->where('parent_id', '=', '1e207119-a5cb-4249-b10f-1d6ba42f4130')->sum(DB::raw('children.amount'));
=> "0.0000130000000000"
>>> bcsub(1.3E-5, 0);
=> "0.0000000000000000"
>>> bcsub("0.0000130000000000", 0);
=> "0.0000130000000000"
>>>
```

This issue is very similar to https://github.com/laravel/framework/issues/20554, but I'm not casting anything.

**Comment by driesvints** [comment]
What happens for the sqlite and mysql drivers?

**Comment by staudenmeir** [comment]
In your first example, you are using `Collection::sum()` instead of `Builder::sum()`.

This uses `Builder::sum()`:

```php
Parent::find('1e207119-a5cb-4249-b10f-1d6ba42f4130')->children()->sum('amount');
```

**Comment by ibrunotome** [comment]
You're right @staudenmeir, my mistake.

But one last question before close the issue. It's designed to be this way?

**Comment by driesvints** [comment]
@staudenmeir nice spot.

@ibrunotome yeah, using a method allows you to use the builder directly. This is also the case for Eloquent relationships.

**Comment by ibrunotome** [comment]
Thank you @driesvints. But I wanna say: It's designed to Builder return in string format and collection doesn't?

**Comment by staudenmeir** [comment]
I don't think this was "designed". Databases and `array_sum()` just behave differently for very small numbers.

**Comment by staudenmeir** [comment]
What type of column is `amount`?

**Comment by ibrunotome** [comment]
> What type of column is `amount`?

`$table->unsignedDecimal('amount', 24, 16);` on Laravel. Becomes `numeric (24, 16) on PostgreSQL.

**Comment by staudenmeir** [comment]
The results are different because the database does an exact calculation on decimal values, while `array_sum()` converts the values to floats and returns a float.

So if you would want to calculate the sum in PHP, you should use `bcadd()` to prevent rounding errors.

**Comment by ibrunotome** [comment]
Yes, I'm using bcmath lib to make the calculations on the application layer. I had not seen that I was using a collection instead of constructor. Thank you very much @staudenmeir.
