### ISSUE TITLE
Tinker not working with php7.3

### ISSUE THREAD

**Issue by hedii** [laravel/framework#26906]
- Laravel Version: 5.7.19
- PHP Version:  7.3.0
- Database Driver & Version: NA

### Description:
Tinker exit unexpectedly whatever you enter in it. 

### Steps To Reproduce:
with php7.3, it exit when I type:
```
$ php artisan tinker
Psy Shell v0.9.9 (PHP 7.3.0 — cli) by Justin Hileman
>>> $test = 'eee';
$
```

with php7.2, it is ok:
```
$ php artisan tinker
Psy Shell v0.9.9 (PHP 7.2.12-1+0~20181112102304.11+stretch~1.gbp55f215 — cli) by Justin Hileman
>>> $test = 'eee';
=> "eeee"
```

tested with an other version of laravel as well (5.7.15)

more info on my php version:
```
php -v
PHP 7.3.0 (cli) (built: Dec  7 2018 11:00:11) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.0-dev, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.0, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by driesvints** [comment]
Heya. Please use the issue tracker on the Tinker repo to report issues with Tinker. Also see https://github.com/laravel/tinker/issues/63

**Comment by dvlpr0077** [comment]
when update to php 7.3.0 tinker exit unexpectedly
please help me 
tnx

<img width="453" alt="screen shot 2018-12-25 at 7 29 27 pm" src="https://user-images.githubusercontent.com/45126794/50424569-76e17f00-087b-11e9-8c2e-b20817179f1a.png">

**Comment by devcircus** [comment]
Search the issues here. This has been discussed.

**Comment by davidvegacl** [comment]
If you are using Mac OS Mojave and PHP 7.3.x here is a fix:
https://stackoverflow.com/a/53826601/2840335
