### ISSUE TITLE
Empty database using DatabaseMigrations trait

### ISSUE THREAD

**Issue by lovePizza** [laravel/framework#26917]
To prevent to find an empty database at the end of a test in which there aren't migrations, I suggest to use migrate:fresh instead of migrate:rollback in this file:
```
framework/src/Illuminate/Foundation/Testing/DatabaseMigrations.php
```

**Comment by mfn** [comment]
Your issue (as well as your PR https://github.com/laravel/framework/pull/26916 ) really lacks proper details what exactly are you experiencing, think is a bug, etc. Please provide some reproducible code (best: a repo to reproduce).

**Comment by driesvints** [comment]
Heya, thanks for submitting this. This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.
