### ISSUE TITLE
Queuing email with attached data fails with database queue driver

### ISSUE THREAD

**Issue by marcin-derlukiewicz** [laravel/framework#26929]
- Laravel Version: v5.6.39
- PHP Version: 7.2.13-1+ubuntu18.04.1+deb.sury.org+1
- Database Driver & Version: mysql 5.7

### Description:
When you attach file from disk, (using attachData or attachFromStorage in mailable) it's being added as raw data to swift mail object.

Mailable is then json encoded to store it in \Illuminate\Queue\Queue::createPayload method and that throws an error, because json_encode can't encode binary file

### Steps To Reproduce:
set queue driver to database
create mail and attach file using attachData method

**Comment by driesvints** [comment]
Heya, unfortunately we don't support this version anymore. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.
