### ISSUE TITLE
call attach method of BelongToMany, generate wrong sql

### ISSUE THREAD

**Issue by oknixus** [laravel/framework#26932]
- Laravel Version: laravel/lumen 5.5.2
- PHP Version: 7.1.9
- Database Driver & Version:
mysql 5.7.22
### Description:

Form Data, ids is [1];
But the data is `[0=>1]` which I received use `$ids = $request->input('ids');`

then run this code: `$model->related()->attach($ids)`, I get a sql:`insert into table(some columns, 0)values(values)`

I had try the method `array_values`,  it does not work.
Then I try to call array_map or write foreach to get a new array, ok, it works.
the method attach works well.

So why the `attach` makes a number as a column ?
Or something wrong I did ?

**Comment by staudenmeir** [comment]
Please add the relationship, the actual query and the result of `dd($request->input('ids'));`.

**Comment by oknixus** [comment]
@staudenmeir Yes, I had added the relationship.

**Comment by staudenmeir** [comment]
What I meant: Please add this information to your post.

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
