### ISSUE TITLE
Ambiguous class resolution NexmoSmsChannel, NexmoMessage, SlackWebhookChannel, SlackAttachment, SlackAttachmentField, SlackMessage

### ISSUE THREAD

**Issue by ProgJo** [laravel/framework#26943]
After running _**composer update**_ to update dependencies, I got these 6 warnings. Tried to remove the ambiguous classes, but they are not required in my _**composer.json**_.

I don't use these classes in my application.

![warning](https://user-images.githubusercontent.com/19173347/50386281-a6449000-06b1-11e9-9568-850da794059f.PNG)

**Comment by sisve** [comment]
White text on yellow background is such a wonderful way to print readable text...

Anyhow, are you sure you should be using the two packages laravel/nexmo-notification-channel and laravel/slack-notification-channel together with the laravel/framework package? It looks to me like you should only use them when you include specific illuminate packages.

**Comment by ProgJo** [comment]
Sorry for the inconveniences about the white text on yellow background. I have made a screenshot from my cmd.

As I said, I don't use these packages. They have been installed after I updated to Laravel 5.7.19 .
And I don't use specific Illuminate package that needs these packages.

**Comment by ProgJo** [comment]
I did what you said. Here is what I got : 
![screen2](https://user-images.githubusercontent.com/19173347/50441091-11b37b00-08c7-11e9-9c3c-45be66ba6587.PNG)
![screen3](https://user-images.githubusercontent.com/19173347/50441102-1841f280-08c7-11e9-87cd-f0c20c6493ef.PNG)

**Comment by X-Coder264** [comment]
Does deleting the entire vendor folder and running `composer install` again solve the problem?

**Comment by sisve** [comment]
This seems related to a recent change where these packages were extracted out of the main framework package; https://github.com/laravel/framework/pull/26689

I would try @X-Coder264's suggestion to remove the vendor folder and running `composer install`, it should clear out any old code files still present in vendor/laravel/framework. (Composer should have done that already, but I'm guessing that something went wrong that time.)

**Comment by ProgJo** [comment]
Hello.

As @X-Coder264  suggested it, this solved the problem. That means composer didn't delete the files properly as It supposed to.

Thank you very much for your time.

And Merry Christmas! Happy New Year!
