### ISSUE TITLE
Cannot use required_with with a wildcard on a static key

### ISSUE THREAD

**Issue by Korko** [laravel/framework#26957]
- Laravel Version: 5.7.19
- PHP Version: 7.2.12
- Database Driver & Version: -

### Description:
When validating a static key (without wildcard), I cannot use a wildcard a parameter for the required_with rule.

### Steps To Reproduce:
2 POST data:
- user.*.email => 'email'
- emailContent => 'required_with:user.*.email|string'

### Test Method:

    public function testRequiredWithWildcard()
    {
        $trans = $this->getIlluminateArrayTranslator();
        $v = new Validator($trans, ['names' => [['first' => 'Taylor']], 'foo' => 'bar'], ['foo' => 'required_with:names.*.first']);
        $this->assertTrue($v->passes());

        $v = new Validator($trans, ['names' => [['first' => 'Taylor']]], ['foo' => 'required_with:names.*.first']);
        $this->assertFalse($v->passes());
    }

The second assertion fails as the data "names.*.first" does not exists and so the validation passes.

**Comment by driesvints** [comment]
Might be related to https://github.com/laravel/framework/issues/26179

**Comment by taylorotwell** [comment]
When using the `*` in required_with you the field you're validating also needs to be within in array like the documentation shows:

![image](https://user-images.githubusercontent.com/463230/80748678-ecea9b80-8aea-11ea-8624-163d81a3a33e.png)

What your code example would do is currently undefined behavior in Laravel. It's undefined in the sense of we do not know if you mean that at least one first name must be present... every element in the array must have one? 

This is more of a feature request or idea that should be discussed in laravel/ideas where the behavior can actually be defined.
