### ISSUE TITLE
orWhere([...]) with array conditions is not working

### ISSUE THREAD

**Issue by leonma** [laravel/framework#26962]
- Laravel Version: 5.7.*
- PHP Version: 7
- Database Driver & Version:

### Description:
When use the orWhere function with the array params, the result will be 'and'.

### Steps To Reproduce:
$conditions = [['name', 'like', 'a%'], ['name', 'like', 'b%']];
User::orWhere($conditions)->toSql();
// should be: select * from `users` where (`name` like 'a%' or `name` like 'b%') and ...
// now: select * from `users` where (`name` like 'a%' and `name` like 'b%') and ...

### Details
File: Illuminate\Database\Query\Builder.php
Line: 658-669
```
    protected function addArrayOfWheres($column, $boolean, $method = 'where')
    {
        return $this->whereNested(function ($query) use ($column, $method, $boolean) {
            foreach ($column as $key => $value) {
                if (is_numeric($key) && is_array($value)) {
                    if (count($value) < 4) {
                        $value[3] = $boolean
                    }
                    $query->$method(...array_values($value)); // here may be missing the $boolean param
                } else {
                    $query->$method($key, '=', $value, $boolean);
                }
            }
        }, $boolean);
    }
```

I think the $value[3] should be equal to $boolean if the array condition size is 3.

**Comment by staudenmeir** [comment]
The behavior of `orWhere()` is quite inconsistent: #24755

**Comment by DarkGhostHunter** [comment]
Should be able to add a `orWhereAnd()` method?

```php
\App\User::where([
    ['name', 'Taylor']
])->orWhereAnd([
    ['genre', 'male'],
    ['role', 'developer'],
]);  
```
```sql
select * from users where name = 'Taylor' or where name = 'John' and where genre = 'male' and where role = 'developer'
```

**Comment by driesvints** [comment]
I think it's best to use the suggestion from https://github.com/laravel/framework/issues/24755#issuecomment-403003092 for now and post an issue at the [laravel/ideas](https://github.com/laravel/ideas) repo if you want this behavior to be changed.

**Comment by vinothkbest** [comment]
asdffsd
