### ISSUE TITLE
Eloquent: Specified connection is not respected and is intermittent

### ISSUE THREAD

**Issue by NHuebner1983** [laravel/framework#26970]
- Laravel Version: 5.7.17
- PHP Version: 7.2.13-1+ubuntu18.04.1+deb.sury.org+1
- Database Driver & Version: MongoDB 3.6.3 (also a problem in MySQL 5 & PostgreSQL - database driver & version appears to be irrelevant to the problem)

### Description:
Before dismissing this as a MongoDB issue, please note that this issue existed while using MySQL & PostgreSQL) and since Laravel 5.4.  It's intermittent - works for a week, then all connections point back to the main database. We have tried many things to set the connection, but the connections we're specifying are having no effect. We have performed `php artisan optimize:clear` and `php artisan config:cache` without resolution.

**In our model we have attempted to use the following ways to set the connection:**

 - `protected $connection = 'mongo_encrypt';`
 - __construct:  before parent::construct  `$this->connection = 'mongo_encrypt';`
 - __construct:  after parent::construct  `$this->connection = 'mongo_encrypt';`

`mongo_encrypt` is the database we store our encryption keys (a server isolated from this one, on the same local network, configured and working properly with migrations).

The only thing we have not done is perform $model->setConnection() which we would prefer not to use since the three methods above should have set the connection correctly, and this would muddy up code and especially difficult while using relationships.

### Steps To Reproduce:
 - Create 2 databases (separate servers from your Laravel code).
 - Create 2 config/database.php connections pointing at your 2 servers.
 - Set the main database as the default connection.
 - Create 2 Eloquent Models and point one of them to the 2nd database.
 - Since the issue is intermittent, it's hard to tell if you will be able to reproduce it.

**Comment by laurencei** [comment]
> The only thing we have not done is perform $model->setConnection() which we would prefer not to use since the three methods above should have set the connection correctly, and this would muddy up code and especially difficult while using relationships.

I kind of feel it's going to be related to this. The fact its only affecting you, and seems rare, means its going to be some edge case that the function above solves, but your custom code does not.

I've used different connections on lots of projects, and never had an issue.

**Comment by NHuebner1983** [comment]
@taylorotwell @laurencei I'm not sure why this would be effecting just me. We're not doing anything strange.  Would you possibly know of another issue reported (past or present) that might shine some light on the issue?

**Comment by NHuebner1983** [comment]
Is there instructions or some information on how I can determine where the problem is taking place? Our team rarely reports any bugs (I think this might be the first I've ever done) because we're exhausting resources trying to determine the cause.

I'm happy to dig deeper into the laravel framework to determine where the connection is being switched from the one I specified to the default one (which in theory should not be happening) - but perhaps there is a reason and it's something we need to get working to properl secure our user's data.

**Comment by NHuebner1983** [comment]
@taylorotwell @laurencei Another odd problem is that we've had tables appear in MySQL `without` a migration, even though the migration had a specified connection. This was back when we had all of our databases on a single server.

@laurencei You mentioned you've used separate connections before without problems - were you using different tables across those connections (ones that were not in one but were in the other)?  If not, then it would be hard to tell where your data landed if you were also affected by this bug. Ours thankfully uses different table names, so we're not treating it as a mirror of sorts, we just have to isolate one specific type of data away from one database in case of a database breach - making it impossible to decrypt data without both databases being compromised.

**Comment by laurencei** [comment]
> We would have expected a table not found, but instead the table got created on both connections.

Then there's something wrong with your migration files as well.

Honestly - everything you've described here is impossible to debug. The reality is many people use multiple connections and different tables all the times. There are many packages (including Telescope) and lots of people use it without issue.

The fact your using a custom implementation, and not using the given function means this is largely out of scope of this GitHub area, which is for problems with the framework itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
