### ISSUE TITLE
Flash Session & Old Input in Android Chrome

### ISSUE THREAD

**Issue by isumiring** [laravel/framework#26971]
- Laravel Version: 5.7.19
- PHP Version: 7.2.5 & 7.1
- Database Driver & Version: MySQL

### Description:
i fresh install laravel 5.7.19.
old() input and flash session is not working.  i do not get any feed back. but if form is valid, but the form still success to submit.
it happens only in android browser. 

### Steps To Reproduce:
Create a standard form 

```
<form class="needs-validation" method="POST" action="{{ $form_action }}">
    {!! csrf_field() !!}

<div class="row">
    <div class="col-md-12">
        <div class="form-message">
            @if (session('form_message'))
            {!! session('form_message')['message'] !!}
            @endif
        </div>
    </div>
</div>
    <div class="mb-3">
        <label for="card_number">No. Kartu</label>
        <div class="input-group">
            <input type="text" maxlength="16" class="form-control number-only" id="card_number" name="card_number" placeholder="No. Kartu" required="required" value="{{ (old('card_number')) ?? '' }}">
            <div class="input-group-prepend">
                <button type="submit" class="input-group-button btn btn-primary check-card"><i class="fas fa-search"></i> Cari</button>
            </div>
        </div>
    </div>
    <hr class="mb-4">
    <div class="product-list-data" style="display:none;">
    </div>
    <hr class="mb-4">
</form>
```

```
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Validator;

class HomeController extends Controller
{

	public function __construct()
	{

	}

	public function index(Request $request)
	{
        if ($request->isMethod('post')) {
            $post = $request->all();

            $validator = Validator::make($post, [
                'card_number' => 'required|digits:16',
            ]);

            if ($validator->fails()) {
                return redirect()->route('index')->with('form_message', [
                    'message' => $validator->errors()->all(),
                    'status' => 'danger',
                ])->withInput();
            }

            return 'success';
        }
        $this->parse['form_action'] = route('index');

        return view('main', $this->parse);
	}
}
```

```
Route::match(['get', 'post'], '/', 'HomeController@index')->name('index');
```

**Comment by driesvints** [comment]
I can't get the above example to work. Please provide a fully working example or a test repo to recreate the issue.

**Comment by isumiring** [comment]
hey @driesvints 
i create (fork) a new latest laravel repo
https://github.com/isumiring/laravel

flash session and old() is not generated in chrome android (pie)
i'm not sure this is a android (chrome) bug or else. but when i'm using laravel 5.6 and then update it to 5.7.19, it does work. flash session and old() is generated.

**Comment by driesvints** [comment]
@isumiring if it works on 5.7.19 then this isn't a bug I suppose?

**Comment by driesvints** [comment]
> and then update it to 5.7.19, it does work

If you managed to get it to work in this version by updating then it should also work with a fresh install. I think there's something misconfigured. Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by isumiring** [comment]
@driesvints thanks for the feedback 👍 

i'll try to ask in the forum you said above.
