### ISSUE TITLE
[Eloquent] Using "selectSub()" with "get()" or "first()" returns only the sub

### ISSUE THREAD

**Issue by DarkGhostHunter** [laravel/framework#26979]
- Laravel Version: 5.7.19
- PHP Version: 7.3.0
- Database Driver & Version: SQLite 3

### Description:

With the Eloquent Query Builder, using `selectSub()` with a `get()` or `first()`, with or without any parameters, only returns the new column declared in `selectSub` instead of all the columns combined with the `selectSub`.

### Steps To Reproduce:

The `Basket` is an Eloquent Model with four columns: `id`, `available_apples`, `consumed_apples` and `are_tasty`.

```php
<?php

var_dump(
    Basket::where('id', 1)
        ->selectSub('available_apples - consumed_apples', 'remaining_apples')
        ->first()->toArray()
);
```

#### Expected:

```
array:1 [
  "id" => 1
  "available_apples " => 10
  "consumed_apples" => 2
  "remaining_apples" => 8
  "are_tasty" => 1
]
```

#### Actual result:

```
array:1 [
  "remaining_apples" => 8
]
```

**Comment by koenhoeijmakers** [comment]
This happens because it boils down to `selectRaw` which overwrites the existing select.

There is an `addSelect` method though and given we have that maybe its an idea to also add `addSelectSub` and `addSelectRaw`?

**Comment by DarkGhostHunter** [comment]
> This happens because it boils down to `selectRaw` which overwrites the existing select.
> 
> There is an `addSelect` method though and given we have that maybe its an idea to also add `addSelectSub` and `addSelectRaw`?

Well, the chain is `selectSub()` -> `selectRaw()` -> `addSelect()`.

## So what happens?

The thing is, when calling `selectSub`, it saves the particular `select` sub-statement into the `columns` property array inside the Database Query Builder.

So, when using `get()`, `pluck()`, or the , `first()` method in the Eloquent Query Builder, these methods take the columns and eventually they end up as an argument on the `onceWithColumns()` method. 

The `onceWithColumns()` says that it will use the `$columns` we passed only if the `select` in the Builder is null, which of course is not because we used `selectSub`, and subsequently `addSelect()`, previously.

## What solution there is?

Since you can go for A or B, a nice way would be to add a method called `mergeSelects()`. This would rise a flag in the Builder to merge all the incoming Selects.

```php
// Add the "value" sub select.
$query = User::where('name', 'Taylor')->selectSub('price * 2', 'value')->mergeSelects();

if ($devWants1User) {
    return $query->first(['name', 'id']); // Would return name, id and value.
} else {
    return $query->get(); // Would return all columns and value.
}
```

Without `mergeSelects()`, the select statements can still act like they would. With it, the Builder will merge whatever comes after into the `columns` property.

A long term solution could be separating the Select statement into a more manipulable variable, where you could use `addSelect()`, `addSelectSub()`, `addSelectRaw()`, `getSelect()`, `getSelects()`, removeSelects()`, `flushSelects()`, `isSelect()`, `isSelectRaw()` and so on.

**Comment by DarkGhostHunter** [comment]
@taylorotwell just closed my PR, so that gives us time to make a better implementation of this idea.

What about making the select statements more flexible for 5.8? Could be a breaking change, but would allow to add, remove or edit a particular select statements, instead of just guessing.

Gonna make a PR with that.

**Comment by DarkGhostHunter** [comment]
> We could also fix this by adopting the solution from `withCount()` and moving it to `selectSub()`:
> 
> [framework/src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php](https://github.com/laravel/framework/blob/456eefe5bde4b6a99c41928411e4de073a9a6880/src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php#L197-L199)
> 
> Lines 197 to 199 in [456eefe](/laravel/framework/commit/456eefe5bde4b6a99c41928411e4de073a9a6880)
> 
>          if (is_null($this->query->columns)) { 
>              $this->query->select([$this->query->from.'.*']); 
>          }

What id does? Kinda lost on so much code.

**Comment by staudenmeir** [comment]
It prevents your issue when using `withCount()`:

```php
User::withCount('posts')->get();
```

```sql
select `users`.*,
  (select count(*) from `posts` where `users`.`id` = `posts`.`user_id`) as `posts_count`
from `users`
```

Without the code I posted, the query would suffer from the same problem as `selectSub()`:

```sql
select
  (select count(*) from `posts` where `users`.`id` = `posts`.`user_id`) as `posts_count`
from `users`
```

We could fix the issue by moving this code from `withCount()` to `selectSub()`.

**Comment by DarkGhostHunter** [comment]
I understand now. Im currently testing this:

```php
public function selectSub($query, $as)
    {
        [$query, $bindings] = $this->createSub($query);

        if (is_null($this->columns)) { // If there are no columns declared
            $this->select(); // Add the "all" selector so the other columns are not lost when adding sub
        }

        return $this->selectRaw(
            '('.$query.') as '.$this->grammar->wrap($as), $bindings
        );
    }
```

This solution is better since it doesn't break anything, and keeps the default behaviour of ignoring the final retrieval columns when using a select statement before.

**Comment by DarkGhostHunter** [comment]
BTW, PR added:
https://github.com/laravel/framework/pull/26994

**Comment by driesvints** [comment]
Since this is a behavioral change and not really a bug and the related PR was closed I'm going to close this.

If you still want this to be added, it's best to post this at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea first. After that you may send a PR to the framework.

**Comment by panstromek** [comment]
Is this still a problem? It was closed as not completed, but today I'm using `selectSub` on my queries and it just appends a column to my select list, like expected. Was this fixed at some point?

**Comment by panstromek** [comment]
Nevermind, it's still a problem. Very annoying one, to be honest, as it only happens sometimes, and simply adding a column breaks an existing query.
