### ISSUE TITLE
[PGSQL] multiple assignments to the same column

### ISSUE THREAD

**Issue by SoGooDFR** [laravel/framework#26995]
- Laravel Version: 5.8-master
- PHP Version: 7.3-fpm
- Database Driver & Version: pgsql - Cockroachdb 2.1.3

### Description:
When i update data in laravel 5.8, it will give me this:
`
array:3 [▼
 "user.updated_at" => "2018-12-29 16:02:23"
 "last_cache_date" => "2018-12-29T16:02:23+00:00"
 "updated_at" => "2018-12-29 16:02:23"
]
`
And this cause this error: 
> SQLSTATE[XX000]: Internal error: 7 ERROR: multiple assignments to the same column "updated_at"

On laravel 5.7 no problem:
`
array:2 [▼
 "last_cache_date" => "2018-12-29T16:08:06+00:00"
 "updated_at" => "2018-12-29 16:08:06"
]
`

### Steps To Reproduce:
Upgrade to laravel 5.8. Update data.

**Comment by SoGooDFR** [comment]
`SQLSTATE[XX000]: Internal error: 7 ERROR: multiple assignments to the same column "updated_at" (SQL: update "user" set "updated_at" = 2018-12-29 16:45:21, "last_cache_date" = 2018-12-29T16:45:21+00:00, "updated_at" = 2018-12-29 16:45:21 where "id" = 394853277715628033)`

**Comment by staudenmeir** [comment]
How are you generating the query? `[...]->update([...])`

**Comment by SoGooDFR** [comment]
In my model, i use `timestamps = true`.
This query is autogenerated by laravel in:

> Illuminate\Database\Query\Builder (line 2641)
> function update(array $values).

To get the results, i just put a dump($values).

**Comment by staudenmeir** [comment]
You must be doing something to trigger the query.

Are you updating the model (e.g. `$user->update([...]);`)?

**Comment by staudenmeir** [comment]
What does your `User` model look like?

**Comment by SoGooDFR** [comment]
```
<?php
namespace App\Model\User;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Ramsey\Uuid\Uuid;

/**
 * User model
 */
class User extends Authenticatable
{
    /**
     * @var string
     */
    protected $table = 'user';

    /**
     * @var array
     */
    protected $casts = [
        'search_key' => 'array'
    ];

    /**
     * @var array
     */
    private $join = [];

    public static function boot()
    {
        parent::boot();

        self::creating(function ($model) {
            $model->uuid = Uuid::uuid1()->toString();
        });
    }
}
```

**Comment by staudenmeir** [comment]
I can't reproduce this. Please debug where the `user.updated_at` value is coming from.

**Comment by SoGooDFR** [comment]
Debug stack trace on 5.8:
The function `save()` of `Illuminate\Database\Eloquent\Model` call `performUpdate()` function.
`Illuminate\Database\Eloquent\Model::performUpdate()` auto update the timestamps detected from the model because `public $timestamps = true` on User.

The method `Illuminate\Database\Eloquent\Concerns\HasAttributes::getDirty()` is calling and return this attributes:
```
array:2 [▼
 "last_cache_date" => DateTime @1546124401
 "updated_at" => "2018-12-29 23:00:01"
]
```
After, `Illuminate\Database\Eloquent\Builder::update()` is calling with `addUpdatedAtColumn() ` into the same class. The method `addUpdatedAtColumn() ` use `qualifyColumn` and return this attribute:
> user.updated_at

So, `addUpdatedAtColumn() ` finaly return:
```
array:3 [▼
 "user.updated_at" => "2018-12-29 23:08:55"
 "last_cache_date" => DateTime @1546124935
 "updated_at" => "2018-12-29 23:00:01"
]
```

**Comment by staudenmeir** [comment]
Has been fixed.
