### ISSUE TITLE
Next Gen Image Format validation 

### ISSUE THREAD

**Issue by idragon81** [laravel/framework#26990]
- Laravel Version: **5.7.19**
- PHP Version: **7.2.8**

### Description:
When uploading next-gen image formats(webp, jp2, jxr, etc) image validator returns saying "**field must be an image**"

### Steps To Reproduce:
Form Fields
```
<form method="post" action="/">
    @csrf
    <input type="file" name="file" enctype="multipart/form-data">
    <input type="submit">
</form>
```

Validator
```
    Validator::make(request()->all(), [
        "file" => "image"
    ])->validate();
```

**Comment by bonzai** [comment]
You can see the list of all the supported extensions in the [documentation](https://laravel.com/docs/5.7/validation#rule-image):

> image
> The file under validation must be an image (jpeg, png, bmp, gif, or svg)

If you want to support more formats, use `mimes` rule (which is used by the `image` rule):

- https://laravel.com/docs/5.7/validation#rule-mimes
