### ISSUE TITLE
QueryException: General error: 1 no such table: {table_name} (SQL: select * from "{table_name}")

### ISSUE THREAD

**Issue by ellis22** [laravel/framework#27018]
- Laravel Version: 5.7
- PHP Version: 7.2
- Database Driver: sqlite
- Database: memory

All testing on PHPUnit was working completely fine. But when I added `View::share` in `AppServiceProvider` then all the PHPUnit tests failed.

**AppServiceProvider.php**
```php
class AppServiceProvider extends ServiceProvider
{
    public function boot()
    {
        \View::share('categories', \App\Models\Category::all());
    }
}
```

**Error**
```shell
Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1 no such table: categories (SQL: select * from "categories")
```
Please guide me, how can I fix this. Where should I call `View::share` in Laravel app so, all tests should pass.

**Comment by staudenmeir** [comment]
It doesn't work because `AppServiceProvider::boot()` is executed *before* the database is migrated.

Move it into your `TestCase` class:

```php
abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    protected function setUp()
    {
        parent::setUp();

        \View::share('categories', \App\Models\Category::all());
    }
}
```

**Comment by GrahamCampbell** [comment]
@staudenmeir I think you might have misunderstood the question. The way I understood it, is that @ellis22 doesn't want to move that code to only be in the tests. The solution here will be to use Laravel's view composer feature I think. :)

**Comment by GrahamCampbell** [comment]
https://laravel.com/docs/5.7/views#view-composers. If you use `'*'` for the view, you can ensure your `categories` variable is available in all views.

**Comment by ellis22** [comment]
@GrahamCampbell you are right I want to share categories variable in all views. I had also tried view composer `'*'` also. But getting same PHPunit error.

**Comment by hkp22** [comment]
In browser end, `View::share` and `View::composer` both works. But at PHPUnit, they fail.
