### ISSUE TITLE
Mail::to($email)->send((new Mail())->local('en')) won't override the localization (As documented)

### ISSUE THREAD

**Issue by Abu3safeer** [laravel/framework#27023]
- Laravel Version: 5.7.19
- PHP Version: 7.2.12
- Database Driver & Version: MariaDB 10.1.37

### Description:
When trying to send an email with specific local using ->local() method on new Mailable class, example:
``` PHP
\Mail::to('name@mail.com')->send((new NewOrder($order)->locale('en')));
```
while if you use ->local() on the Mail directly before ->send() method, it will override the local
``` PHP
\Mail::to('name@mail.com')->locale('en')->send((new NewOrder($order)));
```
#### tr;dr:
simply use ->local('en') on any Mailable instance, it won't change the localization of that email.

#### Detailed:
1. Make several language files, (you can use files from this repository (https://github.com/caouecs/Laravel-lang ).
2. Create an email (Mailable instance), and fill it with texts from localization files inside "resources\lang".
3. Attach ->local() method on new Mailable instance like this code:
``` PHP
\Mail::to('name@mail.com')->send((new NewOrder($order)->locale('en')));
```
4. Try different localizations, it won't work.

# Additional details: 
This is the code I use exactly:
```PHP
\Mail::to([
                env('ORDER_MAIL_TO_ADDRESS_1'),
                env('ORDER_MAIL_TO_ADDRESS_2')
                ])->send((new NewOrder($order))->locale('ar'));
```
The default local is English, I am trying to send this email in Arabic, it never arrived in Arabic except with this code:
```PHP
\Mail::to([
                env('ORDER_MAIL_TO_ADDRESS_1'),
                env('ORDER_MAIL_TO_ADDRESS_2')
                ])->locale('ar')->send((new NewOrder($order)));
```

### Not overriding method
I discovered this issue from Laravel documentations here:
https://laravel.com/docs/5.7/mail#localizing-mailables
![image](https://user-images.githubusercontent.com/12091003/50566374-0db1ae00-0d4a-11e9-98da-ccc61b9ab445.png)

Link for this method on the repository:
https://github.com/laravel/framework/blob/2219c7deeb24cb1603cf3fc31abd26b87eb7e27a/src/Illuminate/Mail/Mailable.php#L417-L428

### Overriding method
and found the working method here:
https://github.com/laravel/framework/pull/25752
![image](https://user-images.githubusercontent.com/12091003/50566383-32a62100-0d4a-11e9-9177-b77f90aa1f4e.png)

Link for this method on the repository:
https://github.com/laravel/framework/blob/2219c7deeb24cb1603cf3fc31abd26b87eb7e27a/src/Illuminate/Mail/PendingMail.php#L56-L67

**Comment by koenhoeijmakers** [comment]
You should call the locale method _before_ sending, not after.
You can't change the locale for a mail that has already been sent

**Comment by Abu3safeer** [comment]
This is totally makes sense, but what about this?
```PHP
\Mail::to('name@mail.com')->send((new NewOrder($order)->locale('en')));
```
as you can see, the local is set before the mail was sent, but still didn't work.
I don't have any issues anymore, but the above code is the documented one, beside it does send the email, so if anyone tried the code above would have the same issue, and won't figure out the reason because everything will seem right, code written as documented, Maillble has ->local() method, so they will be lost unless they follow read this PR https://github.com/laravel/framework/pull/25752

to be honest I was about to use App::setLocal() to work around this issue, that PR saved me.
so I think this should be fixed since it is not difficult issue.

**Comment by derekmd** [comment]
Yeah, I never touched Mohamed's original `Mail` service implementation. The `PendingMail` locale _always_ overwrites the `Mailable` locale before the mail body is built. Someone else misunderstood the implementation here: https://github.com/laravel/framework/issues/25691

The `Mail` service is meant to select the locale, not the mailable itself. It's possible to allow both but the framework code gets messier and requires more tests.

I didn't realize the docs were written like that. I'll submit a pull request later to correct it, calling `Mail::to()->locale()` instead.

**Comment by Abu3safeer** [comment]
Thank you very much, since it was just misunderstanding, I will close this issue.
