### ISSUE TITLE
Model::loadMissing() only accepts unique relation names

### ISSUE THREAD

**Issue by phh** [laravel/framework#27039]
- Laravel Version: 5.7.19
- PHP Version: 7.2
- Database Driver & Version: 10.3.10-MariaDB

### Description:
When using `Model::loadMissing()` relations containing the same name will be ignored.

### Steps To Reproduce:
Example code:

```
$sourceRecipe->loadMissing([
    'ingredients.unit',
    'ingredients.unit.unit',
    'ingredients.unit.unit.association',
]);
```

Result:
`{"exception":"Illuminate\\Database\\Eloquent\\RelationNotFoundException","exception_message":"Call to undefined relationship [association] on model [App\\Models\\Ingredients\\Units\\Unit]."}`

Seems like it has to do with the way [`loadMissing()`](https://github.com/laravel/framework/blob/6a3dda72abc75e444c38fe4f043bcced5326af8f/src/Illuminate/Database/Eloquent/Collection.php#L104) is loading these by using the same array key and value by using [`array_combine`](https://github.com/laravel/framework/blob/6a3dda72abc75e444c38fe4f043bcced5326af8f/src/Illuminate/Database/Eloquent/Collection.php#L121) to combine these.

`$segments`:
```
array:4 [
  0 => "ingredients"
  1 => "unit"
  2 => "unit"
  3 => "association"
]
```

`$path`:
```
array:3 [
  "ingredients" => "ingredients"
  "unit" => "unit"
  "association" => "association"
]
```

Using `load()` instead seems to work but I'm interested in keeping the same relationships while loading another relation.

**Comment by driesvints** [comment]
Seems like @staudenmeir is on it. Thanks for reporting.
