### ISSUE TITLE
Request null default value in Controller overrides the object in routeDependencyResolverTrait

### ISSUE THREAD

**Issue by csimpi** [laravel/framework#27037]
- Laravel Version: 5.6.39 ( happens since ver 5.5)
- PHP Version: 7.2.2
- Database Driver & Version: MYSQL,  Ver 14.14 Distrib 5.7.21

### Description:
Hi guys, thank you for working on the framework, it's awesome :)
During upgrading an older project from 5.3 I got a problem:
I have a couple of functions in controllers that I'd call through ajax and sometimes manually from a controller.

For this, I'd need to add a default value for the Request parameter of the functions. 
Unfortunately the `routeDependencyResolverTrait` respects the default value against the passed value, so I'm getting $request == null even If I send the parameters. 

The 'issue' is below, it seems this function override the passed value with the default value that I don't understand why. Shouldn't be respected the passed value against the default and get the default value if it has no value? 

```
    protected function transformDependency(ReflectionParameter $parameter, $parameters)
    {
        $class = $parameter->getClass();

        // If the parameter has a type-hinted class, we will check to see if it is already in
        // the list of parameters. If it is we will just skip it as it is probably a model
        // binding and we do not want to mess with those; otherwise, we resolve it here.
        if ($class && ! $this->alreadyInParameters($class->name, $parameters)) {
            return $parameter->isDefaultValueAvailable()
                ? $parameter->getDefaultValue()
                : $this->container->make($class->name);
        }
    }
```

I changed this function, deleted the condition, after this I got the expected result:
```return $this->container->make($class->name);```

I know adding default parameter for the Request parameter is not the best solution but I think it should be possible though.

My concrete example (I need the Request for the JWAuth if user id hasn't passed):

Route:
```Route::get('/users/{id}/photos', 'UserController@getPhotos')->where('id', '^([0-9]+)|(me)$');```

URL:
```/api/users/1/photos?limit=5&orderBy=&page=1```

Function:
```
    public function getPhotos($id=false,Request $request = null)
    {
            if(empty($id) || $id === 'me'){
                JWTAuth::parseToken()->authenticate();
                $user = Auth::user();
            }else{
                $user = User::find($id);
            }
         //......
     }
```

### Steps To Reproduce:

See my example above

**Comment by laurencei** [comment]
> I have a couple of functions in controllers that I'd call through ajax and sometimes manually from a controller

I'm trying to understand this. 

Are you saying you are trying to call a function inside Controller A from Controller B?

**Comment by csimpi** [comment]
@laurencei 
Yes, exactly.
Sometimes I'd call a function inside Controller A from Controller A, sometimes from Controller B, sometimes through ajax request.  

Thank you for the clarifying.

The real question is now, why transformDependency() respects the default value against the passed value in the Treat? 

The PHP reference suggests I should be able to use the default value for the Request parameter:
http://php.net/manual/en/functions.arguments.php

**Comment by laurencei** [comment]
To be honest - this is well outside the scope of support. Laravel controllers are designed to be called once per request cycle, via a HTTP request (including AJAX).

They are not designed to be called as functions from other controllers (or other classes). While this might have worked in the past, it was never a supported function.

Without trying to sound rude, this is a bad design layout, and you should refactor your code, extracting the "function" into a class that can then be called independently of either Controller. 

For example:

```
class ControllerA extends Controller 
{
    public function index() {
           resolve(ExtractedClass::class)->someFunction();
    }
}


class ControllerB extends Controller 
{
    public function index() {
           resolve(ExtractedClass::class)->someFunction();
    }
}

class ExtractedClass
{
     public function someFunction()
     {
         // Your logic here
     }
}
```

**Comment by csimpi** [comment]
Dear @laurencei,
thank you for your answer, I really appreciate it, but this issue is not about the best practice of using a controller or structuring the app, maybe you misunderstood a bit (sorry for my English):

I think there is a logical mistake (or I don't get the point) with this part:
```
            return $parameter->isDefaultValueAvailable()
                ? $parameter->getDefaultValue()
                : $this->container->make($class->name);
```
There is no sense to overwrite the sent ( and excepted) value with the default value of the parameter that's clearly should be handled in the opposite way, as the PHP reference suggests.

**Comment by driesvints** [comment]
Try swapping the arguments in the controller method. It's best to keep the parameters last and other dependencies first. The `Request` class is always resolved. You're also using a fallback for the id but it's always required in your route so it can't have a fallback.

```php
   public function getPhotos(Request $request, $id)
    {
            //...
     }
```

**Comment by csimpi** [comment]
@driesvints 
I don't understand, how I can call this function from another Controller without passing a Request in the first parameter? This is not okay, but this isn't even my question. I'm telling this third time now:

This ticket is about the logic of the `routeDependencyResolverTrait`'s `transformDependency()` method is wrong, because it overwrite the passed value of the function with a default value. This is clearly a mistake in the logic since the default value should be used only if the variable(parameter) is empty/null/undefined.

I've even linked the regarding part of the PHP documentation about the function's default value how should work, and some reason Laravel goes against this logic and basically don't let the developer to pass default value because it will ALWAYS overwrite the passed value.

PHP reference says:
```
Example #3 Use of default parameters in functions

<?php
function makecoffee($type = "cappuccino")
{
    return "Making a cup of $type.\n";
}
echo makecoffee();
echo makecoffee(null);
echo makecoffee("espresso");
?>
The above example will output:

Making a cup of cappuccino.
Making a cup of .
Making a cup of espresso.
```

In our case ALL of the outputs would be:
```
Making a cup of cappuccino.
Making a cup of cappuccino.
Making a cup of cappuccino.
``` 

See my previos comment where I offered a solution how the regarding code should be changed to respect the added/passed/assigned value against the default value if it has one.
