### ISSUE TITLE
Accessors for attributes with `_number` are not called when using toArray()

### ISSUE THREAD

**Issue by axyr** [laravel/framework#27035]
- Laravel Version: 5.7.x
- PHP Version: 7.2
- Database Driver & Version:  5.7.23

Might be an edge case situation, and better served with documentation.

However in this case I have no control over the existing database and have to work with this kind of database columns, and wanted to report the unexpected behaviour.

### Description:
When a model attribute contains a number like `address_line_1`,
the `getAddressLine1Attribute()`method is never called when using `$model->toArray()`.

Accessing the attribute directly works as expected:

`$model->address_line_1` does call `getAddressLine1Attribute()` 
and the changed attribute is returned.

`HasAttributes::cacheMutatedAttributes()` uses `Str::snake` to convert the accessor methods back to the attribute names, 
but incorrectly translate `AddressLine1` to `address_line1`

This due to the fact that `Str::snake` does not add the underscore before numbers, which is probably/might be the desired behaviour for that method.

### Hack
Adding the attribute to the `$appends` array, does make toArray call the correct accessor method..

### Steps To Reproduce:
- Create  a model with attribute `address_line_1`;
- create an accessor method for the attribute;
- modify the attribute in the accessor method;
- call `$modelInstance->address_line_1` and see the attribute changed
- call `$modelInstance->toArray()` and see the attribute unchanged

```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    protected $fillable = [
        'address',
        'address_line_1'
    ];

    protected $appends = [
       // 'address_line_1', // hacky, but fixes the issue...
    ];

    public function getAddressAttribute()
    {
        return 'changed'; // check that accessors get called with toArray
    }

    public function getAddressLine1Attribute()
    {
        return 'changed';
    }
}
```

```php
$company = new \App\Company([
    'address'        => 'original',
    'address_line_1' => 'original',
]);

dump($company->address);        // changed
dump($company->address_line_1); // changed
dd($company->toArray());        // ["address" => "changed", "address_line_1" => "original"]
```

**Comment by koenhoeijmakers** [comment]
This is exactly how it should work, you add your accessors to the `$appends` property so that the model knows it should also add it to the json / array representation.

[Source](https://laravel.com/docs/5.7/eloquent-serialization#appending-values-to-json)

**Comment by driesvints** [comment]
This is indeed the correct behavior. There's no way of knowing if a `_` is between the number or not.

**Comment by mahenn** [comment]
I am also facing same issue.. .
