### ISSUE TITLE
Composer dependency resolver issue

### ISSUE THREAD

**Issue by waqas-mehmood-pk** [laravel/framework#27034]
- Laravel Version: 5.3.0
- PHP Version: 7.0
- Database Driver & Version:
MySql

### Description:
![image](https://user-images.githubusercontent.com/9881496/50612023-83329100-0ea6-11e9-8126-b6543faaaaef.png)

### Steps To Reproduce:
Here is my composer.json require block:

```

"require": {
        "php": ">=5.6.4",
        "bepsvpt/secure-headers": "^3.0",
        "florianv/laravel-swap": "^1.1.0",
        "guzzlehttp/guzzle": "^6.0",
        "laravel/framework": "5.3.*",
        "laravel/passport": "~1.0",
        "laravel/socialite": "^2.0",
        "laravelcollective/bus": "^5.1",
        "laravelcollective/html": "~5.0",
        "league/flysystem-aws-s3-v3": "^1.0",
        "lucasromanojf/laravel5-pdf": "1.0.*",
        "nesbot/carbon": "1.22.*",
        "php-http/guzzle6-adapter": "^1.1",
        "php-http/message": "^1.6",
        "razorpay/ifsc": "1.0",
        "soapbox/laravel-formatter": "^2.0",
        "spatie/laravel-backup": "^3.10",
        "spatie/laravel-permission": "^1.5",
        "torann/geoip": "^0.2.2",
        "venturecraft/revisionable": "1.*",
        "yajra/laravel-datatables-oracle": "~6.0",
        "spatie/laravel-sluggable": "1.5.*"
	},
```

Is there something wrong my side.. of this is the cause of any package update release.. and how can i fix this.. please help or guide me in here.

**Comment by devcircus** [comment]
According to that screenshot, the laravel framework isn't involved at all. You're having problems with third party packages.

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
