### ISSUE TITLE
Creating default object from empty value Laravel 5.6

### ISSUE THREAD

**Issue by niraj-lal-rahi** [laravel/framework#27043]
I am trying to update in loop but it is returning the error(heading). It is updating for the first loop and after that is is giving error.

Code is working good for single time but in loop it is creating error.
$damBillsModel1 = $damBillsModel1->where('exchange',$_data['exchange'])								->where('fy',$this->getFy($_data['bill_date']))												->where('bill_type', $_data['bill_type'])																->where('bill_no', $_data['bill_no'])																->where('client_id', $_data['client']['id'])->first();

$damBillsModel1->bill_name 				= $_data['bill_name'];
$damBillsModel1->json 							= json_encode($_data);
$damBillsModel1->update();

**Comment by driesvints** [comment]
Heya, unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases#support-policy) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.

Also: please fill in the issue template when posting an issue.
