### ISSUE TITLE
Password Reset Email does not take into account a subdomain, if it's being used

### ISSUE THREAD

**Issue by danmatthews** [laravel/framework#27045]
- Laravel Version: 5.7.9
- PHP Version: 7.2.11
- Database Driver & Version: Mysql, 5.7.20

### Description:

When `Auth::routes()` is registered from within a `Route::group` that uses the subdomain option, the reset email still only links to the root domain. This isn't ideal for those using subdomains to provide people with their own unique accounts.

I believe this is related to commit cef10551820530632a86fa6f1306fee95c5cac43 where the APP_URL is added to ensure hostname security. Unfortunately, this breaks dynamic generation that `url()` would typically handle if the hostname wasn't included as part of the argument string.

### Steps To Reproduce:

Create a route group for wildcard subdomains, then register the auth routes within that.

```php
Route::domain('{subdomain}.'.env('APP_DOMAIN'))->group(function() {
    Auth::routes();
});
```

I also have a middleware registered that adds the domain as a URL param:

```php
$subdomain = $request->route()->parameter('subdomain');
if ($subdomain) {
  if ($subdomain != 'admin') {
    // Sends a 404 if the organisation doesn't exist.
    Organisation::where('url', $request->route()->parameter('subdomain'))->firstOrFail();
  }
}

URL::defaults([
     'subdomain' => isset($subdomain) ? $subdomain : null,
]);
```

Then visit `myrealsubdomain.myapp.com/password/reset` and submit a password reset request - the URL on the action button will contain the value of `APP_URL`, without the subdomain.

**Comment by danmatthews** [comment]
For the record, i've worked around it by setting `APP_URL` at runtime in `sendResetEmailLink`

```php

public function sendResetLinkEmail(Request $request)
    {
        $this->validateEmail($request);
        config(['app.url' => url('/')]);
        // We will send the password reset link to this user. Once we have attempted
        // to send the link, we will examine the response then see the message we
        // need to show to the user. Finally, we'll send out a proper response.
        $response = $this->broker()->sendResetLink(
            $request->only('email')
        );

        return $response == Password::RESET_LINK_SENT
            ? $this->sendResetLinkResponse($request, $response)
            : $this->sendResetLinkFailedResponse($request, $response);
    }

```

**Comment by danmatthews** [comment]
Also worth noting: When resetting the password, the `$token` argument can become out-of-order thanks to the fact that the subdomain is a request parameter, so the actual reset password page will show an invalid token error, as what it's validating is the subdomain parameter instead.

**Comment by laurencei** [comment]
@danmatthews - I think I saw a PR for that for 5.8 - I think it is fixed there

**Comment by danmatthews** [comment]
@laurencei beautiful, thanks all.

**Comment by driesvints** [comment]
@laurencei thanks for pointing that out.

**Comment by danmatthews** [comment]
@driesvints @laurencei just actually checked the PR - looks like it solves the token issue, but not the subdomain issue?

**Comment by danmatthews** [comment]
@driesvints no problem - i was myself.

**Comment by Krokit** [comment]
Seems I'm not alone with the subdomain issue. RP #29919

**Comment by driesvints** [comment]
Just tried this and I believe this has been resolved with this fix: https://github.com/laravel/framework/pull/32345
