### ISSUE TITLE
Config dependency problem

### ISSUE THREAD

**Issue by GrahamCampbell** [laravel/framework#27051]
- Laravel Version: 5
- PHP Version: 7
- Database Driver & Version: N/A

### Description:

`src/Illuminate/Notifications/resources/views/email.blade.php` contains a reference to the global `config` function, which only occurs in the whole framework, thus breaking the notations package when used outside of the framework.

**Comment by GrahamCampbell** [comment]
The same is true of `src/Illuminate/Mail/resources/views/markdown/message.blade.php`.

**Comment by driesvints** [comment]
Hmm, you're right. We should try to find another way for this.

**Comment by koenhoeijmakers** [comment]
Couldn't we practically use the `@inject` blade directive for this?

**Comment by GrahamCampbell** [comment]
Inject would be less bad, since the bad use of the helper is unrecoverable, but at least with the config injection, we can recover by requiring the component.

**Comment by koenhoeijmakers** [comment]
I suppose there isn't really another way than requiring the config component and then using `@inject`?

**Comment by X-Coder264** [comment]
We can't use `@inject` as that uses the [app global helper under the hood](https://github.com/laravel/framework/blob/5.7/src/Illuminate/View/Compilers/Concerns/CompilesInjections.php#L21) so we'd be right where we started.

What we can do is type-hint the contract config repository in the `build` method of the mailable and then pass the value from there to the view. That way it still only depends on the contract (package) and there is no need to require the `illuminate/config` package.

Ideally though the mailable shouldn't know anything about the config, instead the required value should be passed in as a scalar value through its constructor, but that would break stuff when someone constructs a new instance of the mailable in his app.

**Comment by driesvints** [comment]
I'd also prefer a solution where `illuminate/config` isn't a requirement. The less dependencies the better and requiring it just for this reason is a bit too much. I'd also mean people will have to set it up when using this package separately. 

Maybe a hardcoded value would be `app.name` would be for the best for now but I don't know what to do about `config('app.url')`...

**Comment by rodrigopedra** [comment]
Hi @X-Coder264, the `@lang` directive already uses the `app()` helper [under the hood](https://github.com/laravel/framework/blob/5.7/src/Illuminate/View/Compilers/Concerns/CompilesTranslations.php#L21)

I don't have a clue on how to decouple, maybe we should provide an alternative view for using the notification package without the whole framework and make a notice?

One alternative is not giving the template property a default value, and inject the property from the Laravel Service Provider, so it wouldn't break Laravel's compatibility but would allow to provide a custom view when using it without the framework

**Comment by driesvints** [comment]
I've been looking at this again but don't see any feasible way to solve this. If people want to use the mail component outside Laravel they can provide a custom message.blade.php file without the config helper.

**Comment by GrahamCampbell** [comment]
I was already looking into this earlier, hence the changes I made to the app.url stuff not in the views. I was thinking we could pull the same trick for the views. I just never got around to making a PR. If nobody else does it within a couple of weeks, I will do it. It's not urgent anyways. :)

**Comment by driesvints** [comment]
@GrahamCampbell okay

**Comment by Henshall** [comment]
> I was already looking into this earlier, hence the other changes I made relating to reading app.url from config. I was thinking we could pull the same trick for the views. I just never got around to making a PR. If nobody else does it within a couple of weeks, I will do it. It's not urgent anyways. :)


Hi Graham - I saw that you reopened this issue but I didn't understand the solution you were suggesting. What did you mean by "pull the same trick for the views". I would like to help with this issue and can send a PR with the changes :) Thanks!

**Comment by taylorotwell** [comment]
Closing this as there is no actual "bug" reported by end users atm. It's just a hypothetical dependency problem that has been open for over a year.

**Comment by GrahamCampbell** [comment]
The bug is that you get a fatal error if you use the component outside of the framework.

**Comment by driesvints** [comment]
@GrahamCampbell they can overwrite the views if they want to.

**Comment by GrahamCampbell** [comment]
Yeh, but it shouldn't be broken out of the box. That's like saying they can fork the repo if they want and make it work. 😆
