### ISSUE TITLE
using dd in view when variabele is declared in ServiceProvider using View::share('foo', 'bar')

### ISSUE THREAD

**Issue by woetroe0803** [laravel/framework#27064]
- Laravel Version: 5.7.19
- PHP Version: 7.2.10
- Database Driver & Version: -

### Description:
When variable declared in a service provider using `View::share('foo', 'bar')` and die dump them in a view the inlcudes from an view aren't rendered anymore (using `@extends("layouts.app")`)

### Steps To Reproduce:
1. go to App\Providers\AppServiceProvider.php add following code. This makes a variable for every view. 

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\View;

```
class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        View::share('foo', 'bar');
    }
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }
}
```
2. go to a blade file make sure it has an @extends. And add `@php dd($foo); @endphp `As following it doesn't include de @extends file.

**edit: using code brackets

**Comment by staudenmeir** [comment]
`dd()` immediately stops the execution with `die(1);`. Do you mean `@php dump($foo); @endphp`?

**Comment by devcircus** [comment]
Sounds like expected behavior.

**Comment by driesvints** [comment]
This is indeed expected behavior.
