### ISSUE TITLE
Error when a form is posted

### ISSUE THREAD

**Issue by adrienpsn** [laravel/framework#27083]
- Laravel Version: 5.7.*
- PHP Version: 7.1.19
- Database Driver & Version: SQLite 3

### Description:
When I post a form, I have this error : `in_array() expects parameter 2 to be array, string given`

### The method:
`Post::create([$request]);`

### The Post model:
`protected $guarded = '';`

The error is in the file `GuardsAttributes.php`: `vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/GuardsAttributes.php`

The function:
```
public function isGuarded($key)
{
    return in_array($key, $this->getGuarded()) || $this->getGuarded() == ['*'];
}
```

**Comment by staudenmeir** [comment]
`$guarded` has to be an array:

```php
protected $guarded = [];
```

**Comment by adrienpsn** [comment]
@staudenmeir shame on me ! Thank you !
