### ISSUE TITLE
getTrace() crashed

### ISSUE THREAD

**Issue by howardhhm** [laravel/framework#27097]
- Laravel Version: 5.7.19
- PHP Version: 7.2
- Database Driver & Version: mysql 8.0.13

### Description:
I created a controller named `TestController` and add an `Exception`. When var_dump the result of `getTrace()`, it caused memory error.

### Steps To Reproduce:
Two files were modified.

- routes/web.php appends the following code.
```php
Route::resource('test', 'TestController');
```

- app/Http/Controllers/TestController.php 
```php
<?php

namespace App\Http\Controllers;

use Exception;


class TestController extends Controller
{
    public function index()
    {
        try {
            throw new Exception;
        } catch (Exception $e) {
            var_dump($e->getTrace());
        }
    }
}

```

exec the command
```bash
php artisan serve
```

And, visit http://localhost:8000/test

**Comment by mfn** [comment]
That's expected, the trace contains references to your objects which have _a lot_ of dependencies.

Use a smarter tool like `dd()` which can handle this more gracefully. In general, with `var_dump` you're not getting far with complex frameworks like this one because the dependency graphs are simply too big.

**Comment by howardhhm** [comment]
@mfn , Thank you for your reply.

As you mentioned,`dd()` is a smarter tool for code debugging. But I ran into a problem, I need to log the location where the `Exception` threw including file name and line number. 

The file `app/Http/Controllers/TestController.php` has been updated
```php
<?php

namespace App\Http\Controllers;

use Exception;

class TestController extends Controller
{
    public function index()
    {
        try {
            $this->test();
        } catch (Exception $e) {
            $trace = $e->getTrace();
            dd($trace);
        }
    }

    public function test()
    {
        throw new Exception();
    }
}
```

However, I got wrong line number
```
array:53 [▼
  0 => array:6 [▼
    "file" => "XXXX/app/Http/Controllers/TestController.php"
    "line" => 12
    "function" => "test"
    "class" => "App\Http\Controllers\TestController"
    "type" => "->"
    "args" => []
  ]
  1 => array:4 [▼
    "function" => "index"
    "class" => "App\Http\Controllers\TestController"
    "type" => "->"
    "args" => []
  ]
```

Is there a gracefully solution?

**Comment by mfn** [comment]
I can't say but I don't think this is related to a bug in Laravel, I would rather turn to forums for that kind of questions.

**Comment by howardhhm** [comment]
OK, thank you for your help.
