### ISSUE TITLE
How To achieve comma separated values from nested relationship

### ISSUE THREAD

**Issue by sunilsharma0** [laravel/framework#27090]
```
"buckets": [
{
"bucket_id": 1,
"bucket_name": "body",
"bucket_display_name": "Body",
"bucket_report_mappings": [
{
"report_typedetails": {
"id": 1,
"report_category_id": 1
}
},
{
"report_typedetails": {
"id": 2,
"report_category_id": 2
}
}
],
"data_screens": []
},
```
Here Above is relationships output of different table models.
I want comma separated values in key  "**bucket_report_mappings**" of **report_type_category**
Can anybody help me to find out optimised solution to achieve it. like

```
"buckets": [
{
"bucket_id": 1,
"bucket_name": "body",
"bucket_display_name": "Body",
"bucket_report_mappings": [
{
1,2   ////// report_category_id
},
}
],
"data_screens": []
}, 
```

**Comment by sunilsharma0** [comment]
Can anyone help me? @GrahamCampbell @adamwathan @taylorotwell

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
