### ISSUE TITLE
Inconsistent use of toJson on a resource object

### ISSUE THREAD

**Issue by dionysiosarvanitis** [laravel/framework#27091]
- Laravel Version: 5.7.19
- PHP Version: 7.2

### Description:

Calling `$resourceObject->toJson()` on a `Illuminate\Http\Resources\Json\Resource` instance, delegates to the underlying model's `toJson()` method bypassing resource's `toArray`. This happens due to `ForwardsCalls` trait that is being used.

This behaviour seems to be inconsistent because json_encode($resourceObject) resolves to the expected `$resourceObject->toArray()`. 

Is this that the intented behaviour?

**Comment by driesvints** [comment]
Can you post the code of the resource object and the model?

**Comment by dionysiosarvanitis** [comment]
Here is the code simplified.

Url: `/dispatches/28`

Route:

```php
Route::prefix('dispatches')->group(function (): void {
    Route::get('{dispatch}', [DispatchController::class, 'show']);
});
```

DispatchController:

```php
public function show(Dispatch $dispatch)
{
        $dispatch = new \App\Http\Resources\DispatchResource($dispatch);
        dd($dispatch->toJson(), json_encode($dispatch));

        // return new DispatchResponse($dispatch);
}
```

DispatchResource:

```php
<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\Resource;

class DispatchResource extends Resource
{
    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'poDate' => $this->po_date,
        ];
    }
}
```

Dispatch Model:

```php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Dispatch extends Model
{

}
```

Dump:

```json
{"id":28,"po":"768","po_date":"2018-12-25","qty":78,"comment":null,"delivery_datetime":"2019-01-17 12:55:00","epoch_id":2,"committed":1,"institution_id":823,"shipment_id":8,"testimonial_id":22,"created_by":4,"updated_by":4,"created_at":"2018-12-30 22:25:29","updated_at":"2018-12-30 22:26:08"}

{"id":28,"poDate":"2018-12-25"}
```

**Comment by dionysiosarvanitis** [comment]
Is there any further information I could provide?

**Comment by driesvints** [comment]
Just realized that https://github.com/laravel/framework/issues/26037 might be a duplicate?

**Comment by dionysiosarvanitis** [comment]
This is not about model's serialization. It has to do specifically with the serialization of a `Illuminate\Http\Resources\Json\JsonResource`. 

I think that if `JsonResource` implement `Jsonable` the issue will be resolved. For example by adding the following method:

```php
public function toJson($options = 0)
{
    return json_encode($this->jsonSerialize(), $options);
}
```

What do you think;

**Comment by driesvints** [comment]
I honestly don't have the time atm to deep-dive into this. I know that there are a bunch of issues about the JSON behavior of a resource object and the same issues keep popping up over and over again. I'll try to take a thorough look at this once I find time but at the moment other matters are keeping me from this. Appreciating any help in the meantime.

**Comment by dionysiosarvanitis** [comment]
ok thanks anyway. Maybe I'll make a PR for this in order to take my turn!

**Comment by driesvints** [comment]
I sent in a PR for this here: https://github.com/laravel/framework/pull/30801

**Comment by driesvints** [comment]
Will be fixed in the next major release.

**Comment by dionysiosarvanitis** [comment]
Excellent. Thanks!
