### ISSUE TITLE
[Windows] Error on using SMTP

### ISSUE THREAD

**Issue by danikarik** [laravel/framework#27098]
Hello!

I deployed Laravel on Windows Server 2016 and everything works fine, except mail driver. When trying to send email, I get error:

```
production.ERROR: Process could not be started [The system cannot find the path specified.
] {"exception":"[object] (Swift_TransportException(code: 0): Process could not be started [The system cannot find the path specified.
] at ...\\vendor\\swiftmailer\\swiftmailer\\lib\\classes\\Swift\\Transport\\StreamBuffer.php:299)
```

I'm using `SMTP` as `MAIL_DRIVER`.

PHP version:

```
PHP 7.2.13 (cli) (built: Dec  5 2018 07:19:53) ( NTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
```

I understand that problem is raising from `sendmail` in `mail config`. I tried to change location in params to `c:\usr\lib\sendmail.exe -t` and _**specific path**_, but no success.

**Comment by driesvints** [comment]
Please resubmit this with the filled in issue template.
