### ISSUE TITLE
Bug in $hidden

### ISSUE THREAD

**Issue by Lukentui** [laravel/framework#27102]
- Laravel Version: 5.7.19
- PHP Version: PHP 7.2.13 (Ubuntu 18.04)
- Database Driver & Version: MySQL 5.7.24

### Description:
$hidden var in model working not right.
I have
`public function versionModel() {
        return $this->hasOne('App\Versions', 'id', 'version_id');
    }`
And then I try to hide "version_model" from arrays, I add "version_model" to $hidden, but I yet see "version_model". The solution - use versionModel instead.
### Steps To Reproduce:

1. Create model
2. Add relationship(function) named in camelcase, ex. - usersObject
3. Add "users_object"(for example) to $hidden in model.

P.S sorry for my english

**Comment by mfn** [comment]
> The solution - use versionModel instead

But this is expected, isn't it? The relation _is_ called `versionModel` so you add that to `$hidden`.

Or am I missing something?

**Comment by driesvints** [comment]
This is indeed expected.
