### ISSUE TITLE
Validator with in string Rule and Rule:in()

### ISSUE THREAD

**Issue by smallmenu** [laravel/framework#27100]
- Laravel Version: 5.5.x
- PHP Version: PHP 7.1.x
- Database Driver & Version:

### Description:
in Validator::make() I use like this:

`'field' => 'nullable|in:all,china,other,河河,黑龙江,河北'`

I get the wrong validator,  '黑龙江' is the unvalid param.

then I  use Rule::in(), the same problem.

I review the code，find in ValidationRuleParser class parseParameters() method.

str_getcsv() tigger this problem.

How about fix this?

**Comment by staudenmeir** [comment]
Please add the whole code. What exactly does the error say?

**Comment by driesvints** [comment]
I can't reproduce this. Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by smallmenu** [comment]
the simple Controller test code is here:

```
<?php
namespace App\Http\Controllers\Test;

use Validator;
use Illuminate\Http\Request;

class TestController
{
    public function index(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'param' => 'required|in:all,china,other,河河,黑龙江,河北',
        ]);

        if ($validator->fails()) {
            print_r($validator->errors()->first());
        } else {
            echo 'ok';
        }
    }
}
```


request `/test/index?param=河北` , it will be ok

request `/test/index?param=河北`, it will tigger the validator's error

**Comment by staudenmeir** [comment]
It works for me. What exact version of Laravel are you using?

**Comment by smallmenu** [comment]
Thanks. @staudenmeir 
I use laravel v5.5.44

**Comment by staudenmeir** [comment]
I've tested the same version and it works for me. Can you reproduce the issue with different strings?

**Comment by mouyong** [comment]
@staudenmeir the problem ensure exists.

because `Illuminate\Validation\ValidationRuleParser:257` default enclosure is 「"」

when i use Rule::in(), it generate string is `"in:"线下付款","wechat""`

it doesn't validate pass.

when i use implode(',', ['线下付款', 'wechat'])

generate string is `线下付款,wechat`

it can be pass validate.

this is my code

![image](https://user-images.githubusercontent.com/10336437/71498777-a6650600-2898-11ea-944e-0c313fffb59b.png)
