### ISSUE TITLE
this class is not available to use illuminate/queue as a standalone package

### ISSUE THREAD

**Issue by lubobill1990** [laravel/framework#27117]
- Laravel Version: 5.7
- PHP Version: N/A
- Database Driver & Version:N/A

### Description:
I hope to use illuminate/queue as a standalone package, but I find 
```
use Illuminate\Bus\Queueable;
use Illuminate\Foundation\Bus\Dispatchable;
```
these two traits are not available in CallQueuedClosure.php.

For Queueable, I think illuminate/bus should be included to composer.json of illuminate/queue

For Dispatchable, it's under illuminate/foundation namespace, but this package is not available.

### Steps To Reproduce:
N/A

**Comment by driesvints** [comment]
It's not the only dependency which isn't referenced in the `composer.json`. I'm afraid this component can't fully be used separately. If you want it to be please open an issue at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea.

**Comment by lubobill1990** [comment]
@lubobill1990 But the trait Dispatchable is independent from other packages. If I copy Dispatchable.php to my project, and configure the autoloader to load Dispatchable.php for the  namespace of Illuminate\Foundation\Bus\Dispatchable, it can be used.

So I think Dispatchable.php can be separated to a package.
