### ISSUE TITLE
required_if_not_exists a key in request

### ISSUE THREAD

**Issue by abdurrahmanriyad** [laravel/framework#27118]
In validation rules, 
I dont see there is a check if a key exists in the request under which I can require other key.
Of course, it can be checked manually but It would be nicer to have check if a key required_if_not_exists as a validation logic.

Example: 
'key2' => 'required_if_not_exists: key1'

**Comment by theminer3746** [comment]
You can [register your own validation rule](https://laravel.com/docs/5.7/validation#custom-validation-rules).

**Comment by abdurrahmanriyad** [comment]
@theminer3746 Thank you man.
I know I can but this seems to me a common validation rule like required and stuffs.
I thinking if it can be added to actual validation rule.
Anyway thanks
