### ISSUE TITLE
CSRF token verification error on Samsung s7

### ISSUE THREAD

**Issue by yuyenkan** [laravel/framework#27111]
- Laravel Version: 5.7.*
- PHP Version: 7.1.3
- Database Driver & Version: mysql

### Description:
All devices with the ajax request working, but only Samsung s7, keep on getting 419 error on ajax request.

### Steps To Reproduce:
using samsung s7 invoke ajax call

**Comment by koenhoeijmakers** [comment]
Could you show your form / ajax request and the request received on the server before the 419 is thrown?

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
