### ISSUE TITLE
Save() doesn't work on eloquent models that got fetched with find()->first()

### ISSUE THREAD

**Issue by RSpeekenbrink** [laravel/framework#27123]
- Laravel Version: 5.5.44
- PHP Version: 7.2.10
- Database Driver & Version: 5.7.23 - MySQL Community Server (GPL)

### Description:
For a CRUD system I'm using the find($id) on my Eloquent Model called Question. Question has an order of display and id. With a function saveOrder I'm updating the order of questions when they got changed by looping trough them like this ($data is an array of arrays containing id and order number (both int)):

```php
foreach ($data['data'] as $orderData) {
      if (Question::find($orderData['id'])->exists()) {
          $question = Question::find($orderData['id'])->first();

         $question->order = $orderData['order'];
         $question->save();
     }
}
```

The model get's fetched fine. And even if I output the model before the save function (`dd($question)`) it shows the correct order i'm sending in. Although the save() function does not save it to the database but doesn't give an error/output either.

I found out to fix this I have to change the way of getting the model from:

`$question = Question::find($orderData['id'])->first();`

To:

`$question = Question::find($orderData['id']);`

And now it saves fine.

Maybe the other way should output an error message or save anyway?

### Steps To Reproduce:

1. Create a model
2. Fetch the model by using `$model = Model::find($id)->first()`
3. Change model data
4. Save the model with the `$model->save()` function
5. Check the database for changes

**Comment by RSpeekenbrink** [comment]
The save() function returns True by the way

**Comment by staudenmeir** [comment]
`Model::find($id)->first()` executes *two* queries:
- The first one fetches the exptected model that matches `$id`.
- Then, the second query replaces it with the *first* model in the table.

Just use `Model::find($id)`.

**Comment by RSpeekenbrink** [comment]
Thanks @staudenmeir,

Actually makes a lot of sense.
