### ISSUE TITLE
Queue no fifo guarantee

### ISSUE THREAD

**Issue by chris-rs** [laravel/framework#27137]
In our laravel installation (5.6) we process streaming data which is received, validated and pushed on a queue (for async handling).
This process works great except for the situation where data ingestion happens faster than queue processing. In this situation queue jobs are not always handled in FIFO order. 
In our case the ordering of the streaming data is important and if that data (spread over a serie of queued jobs) is not handled FIFO the stream is not handled FIFO either.

If I set numprocs in supervisor config to 1 all queued jobs are handled nicely in FIFO order but when I configure multiple workers FIFO handling cannot be assumed. Some jobs that are definitely queued later are processed before earlier jobs.

I also tried Redis::funnel to get grip on the handling, by setting its limit to 1 and using a common key for all data packages but in this case I also see out-of-order processing.
```
Redis::funnel(self::class . ':' . $this->usrKey)->limit(1)->then(function () {
            // handle data
        }, function () {
            // Could not obtain lock...
            return $this->release();
        });
```

Does anyone has experienced this concurrency problem as well? 
From documentation I understand that funnel let's you handle certain jobs (by its key) by a limited number of workers (...->limit(1)... should process all these kind of jobs by max 1 worker). If I understand funnel right this is the same as configuring a single supervisor worker for a specified job type.

**Comment by driesvints** [comment]
Heya, please check the issue linked above. Also: please only use this issue tracker to report bugs with the framework. You can discuss other things on one of the channels below:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
