### ISSUE TITLE
`whenLoaded` sets attribute in resource even if relation is not loaded

### ISSUE THREAD

**Issue by denitsa-cm** [laravel/framework#27139]
- Laravel Version: 5.7.19
- PHP Version: 7.2.11
- Database Driver & Version: mysql 8.0.13

### Description:

I have a `belongsTo` relation from a `SubscriptionPeriod` to a `Subscription` and have the following resource:

```
<?php

namespace App\Http\Resources\Subscriptions;

use Illuminate\Http\Resources\Json\JsonResource;

class SubscriptionPeriodResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request $request
     *
     * @return array
     */
    public function toArray($request)
    {
        dump($this->resource);  // no `subscription` relation is loaded
        dump('is it loaded', $this->resource->relationLoaded('subscription'));  // returns `false`
        return [
            'id' => $this->id,
            'name' => $this->name,
            'subscription' => new SubscriptionResource($this->whenLoaded('subscription')),
        ];
    }
}
```

Even though, the `subscription` relation is not loaded and `$this->resource->relationLoaded('subscription')` returns false, my `SubscriptionResource` is still being included.

I have simplified my calling controller function a lot to isolate this: 

```
    public function index(SubscriptionPeriod $subscriptionPeriod, GetAllMilestonesForSubscriptionPeriodWithStatus $getAllMilestonesForSubscriptionPeriodWithStatus)
    {
//        $subscriptionPeriod->load('milestones', 'previousPeriod', 'followingPeriod');

//        $subscriptionPeriod->milestones_with_status = $getAllMilestonesForSubscriptionPeriodWithStatus->execute($subscriptionPeriod);

        return response()->api('Milestone meta data', new SubscriptionPeriodResource($subscriptionPeriod));
    }
```

I haven't experienced this before and it works correctly with other relations so I'm not sure what I'm doing wrong here.

Even loading like this still loads the relation:

```
        dump($this->resource->relationLoaded('subscription')); // `false`
        return [
            'id' => $this->id,
            'name' => $this->name,
            'subscription' => $this->when($this->resource->relationLoaded('subscription'), function () {
                return new SubscriptionResource($this->subscription);
            }),   // somehow becomes `true` here
```

The response I'm getting when I hit the endpoint:

```
{
    "status": "positive",
    "messages": {
        "default": [
            "Milestone meta data"
        ]
    },
    "result": {
        "id": 2,
        "name": "Eveniet.",
        "subscription": {
            "id": 1
        }
    }
}
```

**I have resorted to doing this for the time being which works as expected for some magical reason:**

```
  $subscriptionLoaded = $this->resource->relationLoaded('subscription');

        return [
            'id' => $this->id,
            'name' => $this->name,
            'subscription' => $this->when($subscriptionLoaded, function () {
                return new SubscriptionResource($this->subscription);
            }),
```
### Steps To Reproduce:

Create a resource and try to conditionally include a `belongsTo` relation using `whenLoaded`.

**Comment by IlyasDeckers** [comment]
I was not able to reproduce, I've tested it on multiple models. I use this method many times in an application I am building atm. The only difference in our setup is MySQL version. Maybe you have defined `protected $with` on your model? Can you post your model? 

This somehow worries me for a couple of API responses in my application, if it happens, some data could be send to our frontend that really does not belong there...

**Comment by driesvints** [comment]
Hmm, I'm actually not entirely sure. Can you indeed post the models themselves as well?

**Comment by denitsa-cm** [comment]
Closing this as I've found where this is coming from on my end. It was an accessor in my `SubscriptionPeriod` model that is loading the `subscription` relation:

```
    public function getNameAttribute()
    {
        return "{$this->subscription->product->name}";
    }
```

**Comment by Mr648** [comment]
@denitsa-md I used your trick this way and it's working well, thank you ;)

```
$loadImages = $this->resource->relationLoaded('images');

return [
    $this->mergeWhen($loadImages,[
        'images' => ImageResource::collection($this->images),
    ]),
];
```

**Comment by tylerwiegand** [comment]
@Mr648 i just had this happen and your trick worked for me as well. I don't know why whenLoaded isn't working "as expected," especially because it does work as expected elsewhere in the same app.

**Comment by elvillacampa** [comment]
This happens for resources only, collections works fine.

**Comment by jamesmehorter** [comment]
I observed this issue when a new relation was added to a resource with `whenLoaded`. Making a real request in Postman showed expected behavior, e.g. 

```
return [
     'id' => $this->id,
     'rows' => RowResource::collection($this->whenLoaded('rows')),
]
```

GET response (correct—I never eager loaded 'rows')
```
{
    "data": {
        "id": 1,
    }
}
```

However PHPUnit tests which verified the JSON above began failing, as `rows` was being output. The unit test looked like this:

```
$resource = new ThingResource($thing);

self::assertSame([
    'id' => $thing->id,
], $resource->toArray($this->app->make(Request::class)));
```

Seems making the request like that ^^ somehow ignores/disregards any `whenLoaded()` usage in the resource. The solution for the tests was

```
// Simulate an actual HTTP request to serialize the resource
$responseData = (new ThingResource($thing))->response()->getData(true);
```
