### ISSUE TITLE
Laravel RedirectIfAuthenticated not working after moving from XAMPP to Laragon

### ISSUE THREAD

**Issue by juliarnasution** [laravel/framework#27134]
Previously I used XAMPP, then migrated to Laragon. when still using XAMPP my application is still functioning properly, but after migrating to Laragon it turns out that my application has an error, namely RedirectIfAuthenticated does not work, and even though the User name that is currently logged appears in the application header, but the session user that is currently logged does not appear when debug on Clockwork. Has anyone ever experienced the same thing here? how is the solution, I see on Google it seems that no one has discussed this issue.

this is RedirectifAuthenticated Class
```
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Support\Facades\Auth;

class RedirectIfAuthenticated
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @param  string|null  $guard
     * @return mixed
     */
    public function handle($request, Closure $next, $guard = null)
    {
        if (Auth::guard($guard)->check()) {
            return redirect()->route('home');
        }

        return $next($request);
    }
}

```
this is my login controller,  i using default auth
```
<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\AuthenticatesUsers;

class LoginController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Login Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles authenticating users for the application and
    | redirecting them to your home screen. The controller uses a trait
    | to conveniently provide its functionality to your applications.
    |
    */

    use AuthenticatesUsers;

    /**
     * Where to redirect users after login.
     *
     * @var string
     */
    protected $redirectTo = '/home';

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('guest')->except('logout');
    }
}
```
my master blade 
```
{{--layout header--}}
@include('layouts.header')

{{-- @includeWhen(Auth::user(),'layouts.topbar') --}}
{{--jika sudah login, maka sidebar akan muncul--}}

@if(Auth::check())
  @include('layouts.topbar')
  @include('layouts.sidebar')
@endif
{{-- @includeWhen(Auth::user(),'layouts.sidebar') --}}
{{--layout konten--}}
@yield('content')

{{-- {{(Auth::user())}} --}}
{{-- {{ --}}
  {{-- clock(Auth::user()) --}}
{{--layout footer--}}
@include('layouts.footer')

```
Thanks!

**Comment by ahinkle** [comment]
Welcome to Laravel! We are glad to have you as part of the community.

Unfortunately GitHub is not an appropriate platform for general application issues. This is only for issues/bugs with the framework code itself.

Please close your issue, and instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

Laravel Slack (https://larachat.co/)
Laravel.io Forum (https://laravel.io/forum)
Laracasts Forum (https://laracasts.com/discuss)
StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks!

**Comment by juliarnasution** [comment]
ok, thanks
