### ISSUE TITLE
Request::fullUrlWithQuery leading ? when there is no query params

### ISSUE THREAD

**Issue by fomvasss** [laravel/framework#27142]
- Laravel Version: 5.7.19
- PHP Version: 7.2.3

### Description:
I used Request::fullUrlWithQuery with `null` as query param value to remove the query param. But I get leading `?` which should not be there when there's no any parameters.

### Steps To Reproduce:
1. Create a route with following code:
```php
Route::get('test', function (\Illuminate\Http\Request $request) {
    return $request->fullUrlWithQuery([
        'param' => null,
    ]);
});
```
2. Try to navigate `example.com/test`. You will see `http://example.com/test?`. There should not be `?` after `test`.
3. Try to navigate `example.com/test?param=123`. You will see `http://example.com/test?`. There should not be `?` after `test`.

**Comment by driesvints** [comment]
I'm not sure actually. It's still a valid url. This doesn't seems to be a bug but rather just how it works. It's best to post this at the [laravel/ideas](https://github.com/laravel/ideas) repository if you want to see this changed.

**Comment by Tarik02** [comment]
So, why do we have this check `count($this->query()) > 0`: https://github.com/laravel/framework/blob/5.7/src/Illuminate/Http/Request.php#L126

While URL is valid, but the `?` at the end is not needed and looks bad.

**Comment by jordanade** [comment]
Agree. Going to try to find an alternate solution until this is fixed.

**Comment by suncoastkid** [comment]
This never got addressed? Super annoying behavior.
