### ISSUE TITLE
Auth::routes(['verify' => true]); =>ReflectionException  : Class App\Http\Controllers\Auth\VerificationController does not exist

### ISSUE THREAD

**Issue by Eugene-Melbourne** [laravel/framework#27149]
- Laravel Version: 5.7.20
- PHP Version: 7.2.11
- Database Driver & Version: mysql

### Description:

hen I add `['verify' => true]` parameter to web auth routes like so

    Auth::routes(['verify' => true]);

I cannot see routes calling 

    $ php artisan route:list

instead of a table I'm getting:

> ReflectionException  : Class App\Http\Controllers\Auth\VerificationController does not exist

And it is truth, I don't have a file called `VerificationController` nowhere on my computer.

however the file `\vendor\laravel\framework\src\Illuminate\Routing\Router.php` has routes that calling it.

I also asked it on [stackoverflow](https://stackoverflow.com/questions/54165217/laravel-5-7-class-app-http-controllers-auth-verificationcontroller-does-not-exis)

**Comment by ahinkle** [comment]
Is this file in your auth controllers directory?

https://github.com/laravel/laravel/blob/master/app/Http/Controllers/Auth/VerificationController.php

**Comment by laurencei** [comment]
As @ahinkle said - you can add the file yourself

**Comment by Eugene-Melbourne** [comment]
Thank you.

**Comment by ValentinGaudin** [comment]
This is a 404 to this link

> Is this file in your auth controllers directory?
> 
> https://github.com/laravel/laravel/blob/master/app/Http/Controllers/Auth/VerificationController.php
