### ISSUE TITLE
Provide a possibility to retrieve blade/generated php paths mappings

### ISSUE THREAD

**Issue by bzixilu** [laravel/framework#27159]
To provide Blade debugging in PhpStorm (please see details in the issue https://youtrack.jetbrains.com/issue/WI-26476 ) it's required to have mappings from blade template path to the path of generated PHP file based on given blade template as well as backward mapping.

As far as I can see, there is no such opportunity now. Please correct me if I'm mistaken.

After a little research I've found two possible small changes in illuminate/view repo that resolve our forward/backward mappings problem:

1) Add an option which forces a compiler to provide a path to blade template (or just a name of blade template) in the generated PHP file - it allows us easily retrieve mappings.

2) Generate a name of generated PHP file based on absolute path or just name of blade template (changes in Compiler#getCompiledPath) -
Now filename generation is based on some not standardized path, that can be absolute or relative (like /path/to/template or ../../template or path/../../to/template etc) depending on user choice in the settings, so it's hard for external tooling like PhpStorm realized what path is used for sha1 filename generation and restore mappings.

I didn't see any security reason to obfuscate path mappings, so I decided to file this feature request and ask you for help. Thank you in advance!

**Comment by driesvints** [comment]
Heya, thanks for submitting this. This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.
