### ISSUE TITLE
Paginator with 'onEachSide' option set to 1 shows duplicate links

### ISSUE THREAD

**Issue by CupOfTea696** [laravel/framework#27167]
- Laravel Version: 5.7.20

### Description:

When I set 'onEachSide' option to 1 on a paginator, it will show a duplicate link for page 2 when I'm on page 3 (the links show 1, 2, ..., 2, 3 [...]). Additionally, when moving to page 4, it will show the dots between page 2 and 3, even though they shouldn't be there (the links show 1, 2, ..., 3, 4 [...]).

### Steps To Reproduce:
- Create a paginator with the 'onEachSide' option set to 1
- Display the paginator in a view
- Go to page 3

**Comment by staudenmeir** [comment]
See #25580.
