### ISSUE TITLE
Can't set route name prefix with shared attributes

### ISSUE THREAD

**Issue by gpressutto5** [laravel/framework#27161]
- Laravel Version: 5.7.19
- PHP Version: 7.2.10

### Description:

When creating a group with shared attributes we would expect this to work, since that's how any other route attribute:

```php
Router::group([
    'name' => 'api.',
], function ($router) {
    $router->get('users', 'UsersController@index')->name('users');
});
```

```diff
--- Current behavior
+++ Expected behavior

-| GET | users | users | UsersController@index |
+| GET | users | api.users | UsersController@index |
```

It only works when using its alias `as`:

```php
Router::group([
    'as' => 'api.',
], function ($router) {
    $router->get('users', 'UsersController@index')->name('users');
});
```

**Comment by driesvints** [comment]
Heya, thanks for submitting this. I don't really consider this a bug but rather just the way it works atm. This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.
