### ISSUE TITLE
Undefined property: Illuminate\Routing\Redirector::$headers

### ISSUE THREAD

**Issue by mikkelbfriis** [laravel/framework#27179]
- Laravel Version: 5.7.21
- PHP Version: 7.2.2
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.5.45, for Win64 (x86)

### Description:
Undefined property: Illuminate\Routing\Redirector::$headers
```
protected function addCookieToResponse($request, $response)
{
    $config = config('session');

    $response->headers->setCookie(
        new Cookie(
            'XSRF-TOKEN', $request->session()->token(), $this->availableAt(60 * $config['lifetime']),
            $config['path'], $config['domain'], $config['secure'], false, false, $config['same_site'] ?? null
        )
    );

    return $response;
}
```

### Steps To Reproduce:
I don't know the steps, this happens when on a middleware('guest') controller and are authenticated.

**Comment by sisve** [comment]
Can you show us how you call this addCookieToResponse method? Perhaps the source code for the entire middleware?

**Comment by mikkelbfriis** [comment]
@sisve 
It's in this file:
```
\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php
```

**Comment by sisve** [comment]
Your controller/action is probably doing a `return redirect();` instead of `return redirect('/new-url');`

**Comment by mikkelbfriis** [comment]
@sisve I managed to find the issue, thanks!

**Comment by driesvints** [comment]
@mikkelbfriis you might want to add the solution for anyone else coming across this in the future.

**Comment by mikkelbfriis** [comment]
@driesvints The issue was in my RedirectIfAuthenticated - the redirect was empty (redirect('')) which resulted in this exception.

**Comment by gedeef** [comment]
Thanks it helped me. 
I tried to redirect to $request->requestUri which is protected, and got the same result as you !
