### ISSUE TITLE
Call to undefined method Illuminate\Session\Store::token()

### ISSUE THREAD

**Issue by iPhonePKAndroid** [laravel/framework#27180]
- Laravel Version: 5.7
- PHP Version: 
PHP 7.3.0 (cli) (built: Dec 22 2018 18:19:18) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.0-dev, Copyright (c) 1998-2018 Zend Technologies
- Database Driver & Version:

### Steps To Reproduce:

```
[2019-01-16 14:41:36] pro.ERROR: Call to undefined method Illuminate\Session\Store::token() {"userId":1,"email":"xxx@qq.com","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method Illuminate\\Session\\Store::token() at /fakajun/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php:54)
[stacktrace]
#0 /fakajun/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#1 /fakajun/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#2 /fakajun/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#3 /fakajun/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#4 /fakajun/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#5 /fakajun/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#6 /fakajun/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#7 /fakajun/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#8 /fakajun/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#9 /fakajun/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#10 /fakajun/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#11 /fakajun/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#12 /fakajun/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#13 /fakajun/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#14 /fakajun/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#15 /fakajun/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 /fakajun/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 /fakajun/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#18 /fakajun/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /fakajun/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /fakajun/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#21 /fakajun/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /fakajun/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /fakajun/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#24 /fakajun/vendor/laravel/framework/src/Illuminate/Routing/Router.php(684): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#25 /fakajun/vendor/laravel/framework/src/Illuminate/Routing/Router.php(659): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#26 /fakajun/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#27 /fakajun/vendor/laravel/framework/src/Illuminate/Routing/Router.php(614): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#28 /fakajun/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#29 /fakajun/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#30 /fakajun/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 /fakajun/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /fakajun/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /fakajun/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 /fakajun/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /fakajun/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /fakajun/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#37 /fakajun/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /fakajun/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /fakajun/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#40 /fakajun/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /fakajun/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /fakajun/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#43 /fakajun/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /fakajun/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /fakajun/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#46 /fakajun/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#47 /fakajun/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#48 /fakajun/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#49 {main}
"} 

```

**Comment by mfn** [comment]
>     * Laravel Version: 5.7

Can you please be more specific and include the patch level, too? 5.7.**x**? Thanks!

**Comment by iPhonePKAndroid** [comment]
Laravel Framework 5.7.21

**Comment by imanghafoori1** [comment]
Would you test the situation on 5.7.20 for example ?!

**Comment by ahinkle** [comment]
Would you be able to provide us more information such as steps that you took to reach this error?

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by onesez** [comment]
> Would you be able to provide us more information such as steps that you took to reach this error?

<?php

return [

	/*
		    |--------------------------------------------------------------------------
		    | Application Name
		    |--------------------------------------------------------------------------
		    |
		    | This value is the name of your application. This value is used when the
		    | framework needs to place the application's name in a notification or
		    | any other location as required by the application or its packages.
		    |
	*/

	'name' => env('APP_NAME', 'Laravel'),

	/*
		    |--------------------------------------------------------------------------
		    | Application Environment
		    |--------------------------------------------------------------------------
		    |
		    | This value determines the "environment" your application is currently
		    | running in. This may determine how you prefer to configure various
		    | services the application utilizes. Set this in your ".env" file.
		    |
	*/

	'env' => env('APP_ENV', 'production'),

	/*
		    |--------------------------------------------------------------------------
		    | Application Debug Mode
		    |--------------------------------------------------------------------------
		    |
		    | When your application is in debug mode, detailed error messages with
		    | stack traces will be shown on every error that occurs within your
		    | application. If disabled, a simple generic error page is shown.
		    |
	*/

	'debug' => env('APP_DEBUG', false),

	/*
		    |--------------------------------------------------------------------------
		    | Application URL
		    |--------------------------------------------------------------------------
		    |
		    | This URL is used by the console to properly generate URLs when using
		    | the Artisan command line tool. You should set this to the root of
		    | your application so that it is used when running Artisan tasks.
		    |
	*/

	'url' => env('APP_URL', 'http://localhost'),

	'asset_url' => env('ASSET_URL', null),

	/*
		    |--------------------------------------------------------------------------
		    | Application Timezone
		    |--------------------------------------------------------------------------
		    |
		    | Here you may specify the default timezone for your application, which
		    | will be used by the PHP date and date-time functions. We have gone
		    | ahead and set this to a sensible default for you out of the box.
		    |
	*/

	'timezone' => 'PRC',

	/*
		    |--------------------------------------------------------------------------
		    | Application Locale Configuration
		    |--------------------------------------------------------------------------
		    |
		    | The application locale determines the default locale that will be used
		    | by the translation service provider. You are free to set this value
		    | to any of the locales which will be supported by the application.
		    |
	*/

	'locale' => 'zh',

	/*
		    |--------------------------------------------------------------------------
		    | Application Fallback Locale
		    |--------------------------------------------------------------------------
		    |
		    | The fallback locale determines the locale to use when the current one
		    | is not available. You may change the value to correspond to any of
		    | the language folders that are provided through your application.
		    |
	*/

	'fallback_locale' => 'en',

	/*
		    |--------------------------------------------------------------------------
		    | Faker Locale
		    |--------------------------------------------------------------------------
		    |
		    | This locale will be used by the Faker PHP library when generating fake
		    | data for your database seeds. For example, this will be used to get
		    | localized telephone numbers, street address information and more.
		    |
	*/

	'faker_locale' => 'en_US',

	/*
		    |--------------------------------------------------------------------------
		    | Encryption Key
		    |--------------------------------------------------------------------------
		    |
		    | This key is used by the Illuminate encrypter service and should be set
		    | to a random, 32 character string, otherwise these encrypted strings
		    | will not be safe. Please do this before deploying an application!
		    |
	*/

	'key' => env('APP_KEY'),

	'cipher' => 'AES-256-CBC',

	/*
		    |--------------------------------------------------------------------------
		    | Autoloaded Service Providers
		    |--------------------------------------------------------------------------
		    |
		    | The service providers listed here will be automatically loaded on the
		    | request to your application. Feel free to add your own services to
		    | this array to grant expanded functionality to your applications.
		    |
	*/

	'providers' => [

		/*
			         * Laravel Framework Service Providers...
		*/
		Illuminate\Auth\AuthServiceProvider::class,
		Illuminate\Broadcasting\BroadcastServiceProvider::class,
		Illuminate\Bus\BusServiceProvider::class,
		Illuminate\Cache\CacheServiceProvider::class,
		Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
		Illuminate\Cookie\CookieServiceProvider::class,
		Illuminate\Database\DatabaseServiceProvider::class,
		Illuminate\Encryption\EncryptionServiceProvider::class,
		Illuminate\Filesystem\FilesystemServiceProvider::class,
		Illuminate\Foundation\Providers\FoundationServiceProvider::class,
		Illuminate\Hashing\HashServiceProvider::class,
		Illuminate\Mail\MailServiceProvider::class,
		Illuminate\Notifications\NotificationServiceProvider::class,
		Illuminate\Pagination\PaginationServiceProvider::class,
		Illuminate\Pipeline\PipelineServiceProvider::class,
		Illuminate\Queue\QueueServiceProvider::class,
		Illuminate\Redis\RedisServiceProvider::class,
		Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
		Illuminate\Session\SessionServiceProvider::class,
		Illuminate\Translation\TranslationServiceProvider::class,
		Illuminate\Validation\ValidationServiceProvider::class,
		Illuminate\View\ViewServiceProvider::class,

		/*
			         * Package Service Providers...
		*/

		/*
			         * Application Service Providers...
		*/
		App\Providers\AppServiceProvider::class,
		App\Providers\AuthServiceProvider::class,
		// App\Providers\BroadcastServiceProvider::class,
		App\Providers\EventServiceProvider::class,
		App\Providers\RouteServiceProvider::class,

		Jenssegers\Mongodb\MongodbServiceProvider::class,

		Jenssegers\Agent\AgentServiceProvider::class,
		itbdw\QiniuStorage\QiniuFilesystemServiceProvider::class,
		\SocialiteProviders\Manager\ServiceProvider::class,

	],

	/*
		    |--------------------------------------------------------------------------
		    | Class Aliases
		    |--------------------------------------------------------------------------
		    |
		    | This array of class aliases will be registered when this application
		    | is started. However, feel free to register as many as you wish as
		    | the aliases are "lazy" loaded so they don't hinder performance.
		    |
	*/

	'aliases' => [

		'App' => Illuminate\Support\Facades\App::class,
		'Artisan' => Illuminate\Support\Facades\Artisan::class,
		'Auth' => Illuminate\Support\Facades\Auth::class,
		'Blade' => Illuminate\Support\Facades\Blade::class,
		'Broadcast' => Illuminate\Support\Facades\Broadcast::class,
		'Bus' => Illuminate\Support\Facades\Bus::class,
		'Cache' => Illuminate\Support\Facades\Cache::class,
		'Config' => Illuminate\Support\Facades\Config::class,
		'Cookie' => Illuminate\Support\Facades\Cookie::class,
		'Crypt' => Illuminate\Support\Facades\Crypt::class,
		'DB' => Illuminate\Support\Facades\DB::class,
		'Eloquent' => Illuminate\Database\Eloquent\Model::class,
		'Event' => Illuminate\Support\Facades\Event::class,
		'File' => Illuminate\Support\Facades\File::class,
		'Gate' => Illuminate\Support\Facades\Gate::class,
		'Hash' => Illuminate\Support\Facades\Hash::class,
		'Lang' => Illuminate\Support\Facades\Lang::class,
		'Log' => Illuminate\Support\Facades\Log::class,
		'Mail' => Illuminate\Support\Facades\Mail::class,
		'Notification' => Illuminate\Support\Facades\Notification::class,
		'Password' => Illuminate\Support\Facades\Password::class,
		'Queue' => Illuminate\Support\Facades\Queue::class,
		'Redirect' => Illuminate\Support\Facades\Redirect::class,
		'Redis' => Illuminate\Support\Facades\Redis::class,
		'Request' => Illuminate\Support\Facades\Request::class,
		'Response' => Illuminate\Support\Facades\Response::class,
		'Route' => Illuminate\Support\Facades\Route::class,
		'Schema' => Illuminate\Support\Facades\Schema::class,
		'Session' => Illuminate\Support\Facades\Session::class,
		'Storage' => Illuminate\Support\Facades\Storage::class,
		'URL' => Illuminate\Support\Facades\URL::class,
		'Validator' => Illuminate\Support\Facades\Validator::class,
		'View' => Illuminate\Support\Facades\View::class,

		'Agent' => Jenssegers\Agent\Facades\Agent::class,
		'Moloquent' => Jenssegers\Mongodb\Eloquent\Model::class,

		'Util' => Wending\Utils\Util::class,
		'Socialite' => Laravel\Socialite\Facades\Socialite::class,

	],

];

**Comment by onesez** [comment]
`<?php

return [

	/*
		    |--------------------------------------------------------------------------
		    | Application Name
		    |--------------------------------------------------------------------------
		    |
		    | This value is the name of your application. This value is used when the
		    | framework needs to place the application's name in a notification or
		    | any other location as required by the application or its packages.
		    |
	*/

	'name' => env('APP_NAME', 'Laravel'),

	/*
		    |--------------------------------------------------------------------------
		    | Application Environment
		    |--------------------------------------------------------------------------
		    |
		    | This value determines the "environment" your application is currently
		    | running in. This may determine how you prefer to configure various
		    | services the application utilizes. Set this in your ".env" file.
		    |
	*/

	'env' => env('APP_ENV', 'production'),

	/*
		    |--------------------------------------------------------------------------
		    | Application Debug Mode
		    |--------------------------------------------------------------------------
		    |
		    | When your application is in debug mode, detailed error messages with
		    | stack traces will be shown on every error that occurs within your
		    | application. If disabled, a simple generic error page is shown.
		    |
	*/

	'debug' => env('APP_DEBUG', false),

	/*
		    |--------------------------------------------------------------------------
		    | Application URL
		    |--------------------------------------------------------------------------
		    |
		    | This URL is used by the console to properly generate URLs when using
		    | the Artisan command line tool. You should set this to the root of
		    | your application so that it is used when running Artisan tasks.
		    |
	*/

	'url' => env('APP_URL', 'http://localhost'),

	'asset_url' => env('ASSET_URL', null),

	/*
		    |--------------------------------------------------------------------------
		    | Application Timezone
		    |--------------------------------------------------------------------------
		    |
		    | Here you may specify the default timezone for your application, which
		    | will be used by the PHP date and date-time functions. We have gone
		    | ahead and set this to a sensible default for you out of the box.
		    |
	*/

	'timezone' => 'PRC',

	/*
		    |--------------------------------------------------------------------------
		    | Application Locale Configuration
		    |--------------------------------------------------------------------------
		    |
		    | The application locale determines the default locale that will be used
		    | by the translation service provider. You are free to set this value
		    | to any of the locales which will be supported by the application.
		    |
	*/

	'locale' => 'zh',

	/*
		    |--------------------------------------------------------------------------
		    | Application Fallback Locale
		    |--------------------------------------------------------------------------
		    |
		    | The fallback locale determines the locale to use when the current one
		    | is not available. You may change the value to correspond to any of
		    | the language folders that are provided through your application.
		    |
	*/

	'fallback_locale' => 'en',

	/*
		    |--------------------------------------------------------------------------
		    | Faker Locale
		    |--------------------------------------------------------------------------
		    |
		    | This locale will be used by the Faker PHP library when generating fake
		    | data for your database seeds. For example, this will be used to get
		    | localized telephone numbers, street address information and more.
		    |
	*/

	'faker_locale' => 'en_US',

	/*
		    |--------------------------------------------------------------------------
		    | Encryption Key
		    |--------------------------------------------------------------------------
		    |
		    | This key is used by the Illuminate encrypter service and should be set
		    | to a random, 32 character string, otherwise these encrypted strings
		    | will not be safe. Please do this before deploying an application!
		    |
	*/

	'key' => env('APP_KEY'),

	'cipher' => 'AES-256-CBC',

	/*
		    |--------------------------------------------------------------------------
		    | Autoloaded Service Providers
		    |--------------------------------------------------------------------------
		    |
		    | The service providers listed here will be automatically loaded on the
		    | request to your application. Feel free to add your own services to
		    | this array to grant expanded functionality to your applications.
		    |
	*/

	'providers' => [

		/*
			         * Laravel Framework Service Providers...
		*/
		Illuminate\Auth\AuthServiceProvider::class,
		Illuminate\Broadcasting\BroadcastServiceProvider::class,
		Illuminate\Bus\BusServiceProvider::class,
		Illuminate\Cache\CacheServiceProvider::class,
		Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
		Illuminate\Cookie\CookieServiceProvider::class,
		Illuminate\Database\DatabaseServiceProvider::class,
		Illuminate\Encryption\EncryptionServiceProvider::class,
		Illuminate\Filesystem\FilesystemServiceProvider::class,
		Illuminate\Foundation\Providers\FoundationServiceProvider::class,
		Illuminate\Hashing\HashServiceProvider::class,
		Illuminate\Mail\MailServiceProvider::class,
		Illuminate\Notifications\NotificationServiceProvider::class,
		Illuminate\Pagination\PaginationServiceProvider::class,
		Illuminate\Pipeline\PipelineServiceProvider::class,
		Illuminate\Queue\QueueServiceProvider::class,
		Illuminate\Redis\RedisServiceProvider::class,
		Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
		Illuminate\Session\SessionServiceProvider::class,
		Illuminate\Translation\TranslationServiceProvider::class,
		Illuminate\Validation\ValidationServiceProvider::class,
		Illuminate\View\ViewServiceProvider::class,

		/*
			         * Package Service Providers...
		*/

		/*
			         * Application Service Providers...
		*/
		App\Providers\AppServiceProvider::class,
		App\Providers\AuthServiceProvider::class,
		// App\Providers\BroadcastServiceProvider::class,
		App\Providers\EventServiceProvider::class,
		App\Providers\RouteServiceProvider::class,

		Jenssegers\Mongodb\MongodbServiceProvider::class,

		Jenssegers\Agent\AgentServiceProvider::class,
		itbdw\QiniuStorage\QiniuFilesystemServiceProvider::class,
		\SocialiteProviders\Manager\ServiceProvider::class,

	],

	/*
		    |--------------------------------------------------------------------------
		    | Class Aliases
		    |--------------------------------------------------------------------------
		    |
		    | This array of class aliases will be registered when this application
		    | is started. However, feel free to register as many as you wish as
		    | the aliases are "lazy" loaded so they don't hinder performance.
		    |
	*/

	'aliases' => [

		'App' => Illuminate\Support\Facades\App::class,
		'Artisan' => Illuminate\Support\Facades\Artisan::class,
		'Auth' => Illuminate\Support\Facades\Auth::class,
		'Blade' => Illuminate\Support\Facades\Blade::class,
		'Broadcast' => Illuminate\Support\Facades\Broadcast::class,
		'Bus' => Illuminate\Support\Facades\Bus::class,
		'Cache' => Illuminate\Support\Facades\Cache::class,
		'Config' => Illuminate\Support\Facades\Config::class,
		'Cookie' => Illuminate\Support\Facades\Cookie::class,
		'Crypt' => Illuminate\Support\Facades\Crypt::class,
		'DB' => Illuminate\Support\Facades\DB::class,
		'Eloquent' => Illuminate\Database\Eloquent\Model::class,
		'Event' => Illuminate\Support\Facades\Event::class,
		'File' => Illuminate\Support\Facades\File::class,
		'Gate' => Illuminate\Support\Facades\Gate::class,
		'Hash' => Illuminate\Support\Facades\Hash::class,
		'Lang' => Illuminate\Support\Facades\Lang::class,
		'Log' => Illuminate\Support\Facades\Log::class,
		'Mail' => Illuminate\Support\Facades\Mail::class,
		'Notification' => Illuminate\Support\Facades\Notification::class,
		'Password' => Illuminate\Support\Facades\Password::class,
		'Queue' => Illuminate\Support\Facades\Queue::class,
		'Redirect' => Illuminate\Support\Facades\Redirect::class,
		'Redis' => Illuminate\Support\Facades\Redis::class,
		'Request' => Illuminate\Support\Facades\Request::class,
		'Response' => Illuminate\Support\Facades\Response::class,
		'Route' => Illuminate\Support\Facades\Route::class,
		'Schema' => Illuminate\Support\Facades\Schema::class,
		'Session' => Illuminate\Support\Facades\Session::class,
		'Storage' => Illuminate\Support\Facades\Storage::class,
		'URL' => Illuminate\Support\Facades\URL::class,
		'Validator' => Illuminate\Support\Facades\Validator::class,
		'View' => Illuminate\Support\Facades\View::class,

		'Agent' => Jenssegers\Agent\Facades\Agent::class,
		'Moloquent' => Jenssegers\Mongodb\Eloquent\Model::class,

		'Util' => Wending\Utils\Util::class,
		'Socialite' => Laravel\Socialite\Facades\Socialite::class,

	],

];
`
