### ISSUE TITLE
Artisan confirm() returns string instead of boolean when testing with expectsQuestion().

### ISSUE THREAD

**Issue by koenhoeijmakers** [laravel/framework#27192]
- Laravel Version: 5.7.21
- PHP Version: PHP 7.2.10-0ubuntu1
- Database Driver & Version: Not applicable.

### Description:
When testing `artisan` commands you get the option to use the method `expectsQuestion()`, but when you have a call to:
```
$this->confirm('Should i run?')
``` 
and you test it with (notice the 'no'):
```
->expectsQuestion('Should i run?', 'no')
```
it will return the string value in the response from `$this->confirm()`, which means that that `$confirmed = $this->confirm()` will return `string(no)` instead of the expected `bool(false)`.

### Steps To Reproduce:

Create a command with:
```
$confirmed = $this->confirm('Should i run?');

dd($confirmed); //returns string(no) instead of bool(false)
``` 

Create a test with:
```
$this->artisan('command')->expectsQuestion('Should i run?', 'no');
```

**Comment by driesvints** [comment]
That's because the default of `confirm` is false and you added the expectation that it will return `no`. You need to ask it like this:

```php
->expectsQuestion('Should i run?', false)
```

**Comment by koenhoeijmakers** [comment]
The docs state that calling `$this->confirm()` returns `false` when the user fills `no` as an answer, thus when i fill `no` i would expect this to also be `false` and not the string `no`.

**Comment by driesvints** [comment]
@koenhoeijmakers where do the docs state this?

**Comment by koenhoeijmakers** [comment]
On further notice, this does seem to return `string(y)` too.
```
->expectsQuestion('Should i run?', 'y') 
```

**Comment by driesvints** [comment]
@koenhoeijmakers just like with no, you need to pass `false` here. Please note that you're dealing with internals here and that while `confirm` uses the `ConfirmationQuestion` which specifically returns booleans depending on the user input. So it always returns a boolean which cannot match one-on-one with the `no` which you mock as a return. 

Also note that the part of the docs talk about the input of the "prompt" which isn't recreated with the `expectsQuestion` method. It's just an integration test.

**Comment by driesvints** [comment]
https://github.com/symfony/console/blob/d78ff9239213a6349455d08325ae2ca9b57f25c9/Style/SymfonyStyle.php#L222

**Comment by koenhoeijmakers** [comment]
Makes sense, thanks for the clarification :)
