### ISSUE TITLE
how fetch returning cursor from called procedure with postgres?

### ISSUE THREAD

**Issue by skortabeast** [laravel/framework#27197]
I get cursor in array but how it fetch ?
![image](https://user-images.githubusercontent.com/10978770/51327128-86ae4680-1a68-11e9-828a-7a320fdfe2e5.png)

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
