### ISSUE TITLE
[5.7] Model Has breaking change

### ISSUE THREAD

**Issue by tkrause** [laravel/framework#27201]
- Laravel Version: 5.7.19
- PHP Version: PHP 7.2.10-0ubuntu0.18.04.1 (cli) (built: Sep 13 2018 13:45:02) ( NTS )
- Database Driver & Version: MySQL 5.7 using PDO

### Description:

Breaking change in has functionality for related models. 

In short, `has()` no longer respects joins but it does for wheres in `newQuery`. This results in query errors for anything more complex.

```
 SQLSTATE[42P01]: Undefined table: 7 ERROR:  missing FROM-clause entry for table "stustathist"
```

### Steps To Reproduce:

```php
     Student::with(['schedule'])->has('schedule')->get();
```

```php
<?php

// Student Model
class Student extends Model
{
    protected $primaryKey = 'studentid';

    public function schedule()
    {
            return $this->hasOne(Schedule::class, 'ssstupk', 'stupk');
    }
}
```

```php
<?php

// Schedule Model
class Schedule extends Model
{
    public $timestamps = false;

    protected $table = 'stuschedules';
    protected $primaryKey = 'sspk';

    public function newQuery()
    {
        return parent::newQuery()
            ->join('stustathist', 'stuschedules.sssthpk', '=', 'stustathist.sthpk')
            ->join('programs', 'stuschedules.sspgcode', '=', 'programs.pgcode')
            ->where('stustathist.sthdel', 0)
            ->select([
                'sspk',
                'ssstdate as schedule_start_date',
                'ssendate as schedule_end_date',
                'stuschedules.ssstupk',
                'stuschedules.sscertpk',
                'stuschedules.ssglvcode as grade_level',
                'stustathist.sthsscode',
                'stuschedules.ssrgcode as charter',
                'programs.program as location',
                'programs.pgcode',
                'sscertpk as teacher_id',
            ]);
    }
}
```

### Expected 

Truncated SQL query what is included is what is generated by the has.

5.6.x SQL generated:

```sql
where exists(
  select *
  from "stuschedules"
    inner join "stustathist" on "stuschedules"."sssthpk" = "stustathist"."sthpk"
    inner join "programs" on "stuschedules"."sspgcode" = "programs"."pgcode"
  where "sthdel" = ? and "students"."stupk" = "stuschedules"."ssstupk" and "sthdel" = ? and "ssendate" :: date >= ?
)
```

### Actual

Truncated SQL query what is included is what is generated by the has.

5.7.x SQL generated:
```sql
where exists(
  select *
  from "stuschedules"
  where "sthdel" = ? and "students"."stupk" = "stuschedules"."ssstupk" and "sthdel" = ? and "ssendate" :: date >= ?
)
```

### Solution

We hot patched a file just to see if this would solve the issue and it does. Changing `src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php` in `has()`

Broken
```
$relation->getRelated()->newQueryWithoutRelationships(), $this        
```

Fixed
```
$relation->getRelated()->newQuery(), $this
```

**Comment by driesvints** [comment]
Are we missing some code here? Where does `students` come from?

**Comment by tkrause** [comment]
@driesvints Which line are you referring to? Student is a model the table is students.

**Comment by driesvints** [comment]
@tkrause ah I see. But @staudenmeir is right, you shouldn't overwrite `newQuery` like this. It's part of the reason why this isn't documented.

**Comment by tkrause** [comment]
Why is this closed? 

I'm glad that the change made fixed a bug. However, this has created another by causing joins in a query scope to be ignored by `has()`. 

global scope cannot be using in this scenario because the joins are needed on every query for the model. Thus they should be part of the base query which is what newQuery does - returns a base query.

This is a larger bug that needs to be addressed rather than finding a work around or ignoring the issue at hand.

**Comment by driesvints** [comment]
@tkrause if you overwrite `newQuery` it means it will be applied to every single query that gets created. The `with` method underlying calls it as well for example. It's an internal undocumented method which shouldn't be overwritten like this.

Please use one of the below support channels if you want to find a solution on how to build up a proper query:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by dkulyk** [comment]
```php
public static function boot()
{
    parent::boot();

    static::addGlobalScope(function ($query) {
        $query->join('stustathist', 'stuschedules.sssthpk', '=', 'stustathist.sthpk')
            ->join('programs', 'stuschedules.sspgcode', '=', 'programs.pgcode')
            ->where('stustathist.sthdel', 0)
            ->select([
                'sspk',
                'ssstdate as schedule_start_date',
                'ssendate as schedule_end_date',
                'stuschedules.ssstupk',
                'stuschedules.sscertpk',
                'stuschedules.ssglvcode as grade_level',
                'stustathist.sthsscode',
                'stuschedules.ssrgcode as charter',
                'programs.program as location',
                'programs.pgcode',
                'sscertpk as teacher_id',
            ]);
    });
}```

**Comment by tkrause** [comment]
@dkulyk Thanks this appears to work!

@driesvints Makes sense. To be honest though, this should be documented then that it should not be overridden and be in the upgrade guide. I've seen a lot of tutorials and resources in the past that override this method.

**Comment by driesvints** [comment]
@tkrause it would be a bit overkill for us to document every single method in the codebase which cannot be used due to the size of the codebase.

**Comment by tkrause** [comment]
@driesvints I understand that. But changing a method that is used in a great many of Laravel resources to include LaraCasts that causes a breaking change should be documented in the upgrade guide.

**Comment by mfn** [comment]
I agree with @driesvints , this is simply impossible.

Especially now that you mention "upgrade guide". This guide contains the most high-level steps you absolutely need, common cases.

Think about it, you would have to document each method change in the upgrade guide. It would become unreadable.

I think, however, the changelog itself would be the correct place for this. I didn't specifically check if its there or not, however I would like to think @TBlindaruk currently does a terrific job ensuring we have it!
