### ISSUE TITLE
The result of assertJsonStructure is incorrect

### ISSUE THREAD

**Issue by crhg** [laravel/framework#27207]
- Laravel Version: 5.7.21
- PHP Version: 7.3.1
- Database Driver & Version: -

### Description:

I set `['a' => ['b' => []]]` to the `$structure` parameter expecting json with the structure of `{"a": {"b": <something>}}`, but json `{"a": null, "b": 1}` passes the test.

If `a` is non-null (ex. `{"a": 1, "b": 2}`), the test will fail as expected.

### Steps To Reproduce:

routes/api.php:
```php
<?php

use Illuminate\Http\Request;

Route::get('/foo', function () {
    return [
        'a' => null,
        'b' => 1,
    ];
});
```

tests/Feature/FooTest.php:
```php
<?php

namespace Tests\Feature;

use Tests\TestCase;

class FooTest extends TestCase
{
    public function testFoo(): void
    {
        $response = $this->get('/api/foo');

        $response->assertJsonStructure(
            [
                'a' => [
                    'b' => [],
                ],
            ]
        );
    }
}
```

**Comment by driesvints** [comment]
This is correct. Asserting structure means you're checking the structure of a JSON object according to the given input (keys, etc). A null value is valid when an array isn't present. I think you're searching for `assertExactJson`.

**Comment by crhg** [comment]
This is not such a problem.

When `['a' => ['b' => []]]` is given to the `$structure` parameter, the test result is as follows according to the value of json returned by the response.

| json | pass or fail |
----|----
| `{"a": {"b": 1}}` | pass |
| `{"a": {"c": 1}}` | fail |
| `{"a": null}` | fail |
| `{"a": null, "b": 1}}` | pass← |
| `{"a": null, "c": 1}}` | fail |

It is strange that the result of the test will be influenced by the `"b"` key in an irrelevant place not under the `"a"` key.
