### ISSUE TITLE
'config/filesystems.php' doesn't support cache store 'default'

### ISSUE THREAD

**Issue by lkreher** [laravel/framework#27210]
- Laravel Version: 5.7.20

### Description:
Using 
```
            'cache' => [
                'store' => 'default',
                'expire' => '86400',
                'prefix' => 'cache-filesystem'
            ],
```
in a filesystems disk configuration results in exception `Cache store [default] is not defined.`

**Comment by driesvints** [comment]
default isn't a cache store. It's your default one which is loaded in.

https://github.com/laravel/laravel/blob/master/config/cache.php

**Comment by lkreher** [comment]
Then how do I tell filesystem to use the store that is defined as default? Leaving 'store' empty also results in an error (contradicting [https://github.com/laravel/laravel/blob/master/config/cache.php](https://github.com/laravel/laravel/blob/master/config/cache.php) line 13-14). 
The documentation doesn't really help finding the possible configuration values.

**Comment by driesvints** [comment]
Please try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
