### ISSUE TITLE
Concurrency limiter locks are unsafe

### ISSUE THREAD

**Issue by yuloh** [laravel/framework#27224]
- Laravel Version: 5.5+
- PHP Version: Any
- Database Driver & Version: Any

### Description:

It looks like the `ConcurrencyLimiter` has the same issue described in #26213.  Because the slot key uses an expiration and we don't verify we are still holding the lock it's possible to release someone else's lock, allowing more concurrency than should be allowed.

### Steps To Reproduce:

I've added a failing test [here](https://github.com/yuloh/framework/commit/5172de81fe064f3f3793fa3d6ac32e3b370a9ea0).

Note that manually acquiring and releasing the lock in the test was only added to make reproducing this with a single process possible.  The same issue exists if you use the `block` function in two separate processes.

@janpantel's fix from #26645 should work here too.  Instead of setting `"1"` we set a random token when acquiring the lock.  We then check if the token still matches before calling `DEL`.

**Comment by driesvints** [comment]
@yuloh thanks for sending in the fix!
