### ISSUE TITLE
PHP Catchable fatal error:  Argument 1 passed to Symfony\Component\Cons...

### ISSUE THREAD

**Issue by ehsanalizad** [laravel/framework#27222]
Hello Guys,
While running command `laravel new project1` I encounter the following error:

`PHP Catchable fatal error:  Argument 1 passed to Symfony\Component\Console\Input\InputArgument::__construct() must be an instance of Symfony\Component\Console\Input\string, string given, called in /Users/example/.composer/vendor/symfony/console/Command/Command.php on line 369 and defined in /Users/example/.composer/vendor/symfony/console/Input/InputArgument.php on line 41`

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
