### ISSUE TITLE
Multiple curl requests fail within laravel on Amazon Linux

### ISSUE THREAD

**Issue by shawnhind** [laravel/framework#27223]
- Laravel Version: 5.6.39
- PHP Version: 7.1.23
- Database Driver & Version: N/A
- OS: Amazon Linux 2 AMI. Kernel Version 4.14
- Curl version: curl 7.53.1 (x86_64-redhat-linux-gnu) libcurl/7.53.1 NSS/3.36 zlib/1.2.8 libidn2/0.16 libpsl/0.6.2 (+libicu/50.1.2) libssh2/1.4.2 nghttp2/1.21.1

### Description:
When executing multiple curl requests over https with default options in laravel subsequent requests fail after the first one.  The reason why I believe this is an interaction between the curl version and laravel is for the following:

1. I could not get this problem to occur locally and my local system has a newer version of curl than the server.
2. Doing the same curl requests in php's interactive mode (php -a) does not produce the error but with tinker it does.
3. It does not occur with the command-line based curl client.

### Steps To Reproduce:
Create an EC2 instance through Amazon Web Services with Amazon Linux 2 LTS image.

Create a boilerplate laravel 5.6 application using composer.

Start an interactive tinker session
`php artisan tinker`

Run first curl request (will succeed):
```
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, "https://google.ca");
curl_setopt($ch, CURLOPT_VERBOSE, true);
$output = curl_exec($ch)
curl_close($ch)
```

Repeat the above within the same tinker session and subsequent requests after the first one will give the following error message:

````
>>> $output = curl_exec($ch);
* Hostname google.ca was found in DNS cache
*   Trying 172.217.7.131...
* TCP_NODELAY set
* Connected to google.ca (172.217.7.131) port 443 (#10)
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* NSS error -8023 (SEC_ERROR_PKCS11_DEVICE_ERROR)
* A PKCS #11 module returned CKR_DEVICE_ERROR, indicating that a problem has occurred with the token or slot.
* Closing connection 10
Curl Errno: 35
````

**Comment by driesvints** [comment]
Heya, unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.

**Comment by shawnhind** [comment]
@driesvints hey, I just tried this on 5.7 as well and the exact same situation occurs.

**Comment by sisve** [comment]
The code provided doesn't use Laravel in any way. Could you try and put it in a single test.php file and execute it without loading Laravel at all? This looks like a php/system/environment problem, not a Laravel problem.

**Comment by shawnhind** [comment]
@sisve yes, i know that it doesn't use laravel in any way.  The thing is, I've only been able to get this problem to occur when the curl code is run within a laravel app.  But if I run that same thing without loading in any laravel it does not occur.

**Comment by klfks** [comment]
I have same trouble with laravel 6.18.
php 7.3.13
With tinker.
```
[xxxx@xxxx /srv/www/xxxxxx/htdocs/current]$ php artisan tinker
Psy Shell v0.9.12 (PHP 7.3.13 — cli) by Justin Hileman
>>> $curl = curl_init();
=> curl resource #716
>>>
>>> curl_setopt_array($curl, array(
...   CURLOPT_URL => "https://------/api/v1/users/",
...   CURLOPT_RETURNTRANSFER => true,
...   CURLOPT_ENCODING => "",
...   CURLOPT_MAXREDIRS => 10,
...   CURLOPT_TIMEOUT => 0,
...   CURLOPT_FOLLOWLOCATION => true,
...   CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
...   CURLOPT_CUSTOMREQUEST => "GET",
...   CURLOPT_HTTPHEADER => array(
...     "accept: */*",
...     "Content-Type: application/json",
...     "X-Http-Token: --------
...   ),
... ));
=> true
>>>
>>> $response = curl_exec($curl);
>>> $response = curl_exec($curl);
=> "{"data":[{"id":54,"old_mongo_id":null,"display_name":"\u041a\u0441\u0435\u043d\u044c\u044f \u0421\u0442\u0430\u0440\u043e\u0441\u0442\u0438\u043d\u0430","about":null,"fb_id":nu.................
>>> $curl = curl_init();
=> curl resource #729
>>>
>>> curl_setopt_array($curl, array(
...   CURLOPT_URL => "https://xxxxxxxx/api/v1/users/",
...   CURLOPT_RETURNTRANSFER => true,
...   CURLOPT_ENCODING => "",
...   CURLOPT_MAXREDIRS => 10,
...   CURLOPT_TIMEOUT => 0,
...   CURLOPT_FOLLOWLOCATION => true,
...   CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
...   CURLOPT_CUSTOMREQUEST => "GET",
...   CURLOPT_HTTPHEADER => array(
...     "accept: */*",
...     "Content-Type: application/json",
...     "X-Http-Token: xxxxxxxxxxxx"
...   ),
... ));
=> true
>>>
>>> $response = curl_exec($curl);
=> false
>>>
>>> curl_close($curl);
```

Debug with Guzzle
First time OK
```
*   Trying xxxxx..
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x565394a17820)
* Connected to xxxxxxx (xxxxx) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: none
  CApath: none
* loaded libnssckbi.so
* ALPN, server accepted to use http/1.1
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
*     subject: CN=xxxxxx
*     start date: Mar 31 20:08:06 2020 GMT
*     expire date: Jun 29 20:08:06 2020 GMT
*     common name: xxxxxxx
*     issuer: CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US
> GET /api/v1/users/1581603798 HTTP/1.1
Host: xxxxxxx
User-Agent: GuzzleHttp/6.5.1 curl/7.64.0 PHP/7.3.13
Content-Type: application/json
X-Http-Token: xxxxxxxx
< HTTP/1.1 200 OK
< Server: nginx
< Content-Type: application/json
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-Powered-By: PHP/7.3.13
< Cache-Control: no-cache, private
< Date: Wed, 01 Apr 2020 06:06:00 GMT
< X-RateLimit-Limit: 1000000
< X-RateLimit-Remaining: 999999
<
* Connection #0 to host xxxxx
 left intact
```
Second time FAIL
```
*   Trying xx.xxxxx...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x565394b84720)
* Connected to xxxxxxxxxx (xxxxxxxxx) port 443 (#0)
*   CAfile: none
  CApath: none
* NSS error -8023 (SEC_ERROR_PKCS11_DEVICE_ERROR)
* A PKCS #11 module returned CKR_DEVICE_ERROR, indicating that a problem has occurred with the token or slot.
* Closing connection 0
=> null
```

**Comment by mfn** [comment]
The `CKR_DEVICE_ERROR` _seems_ to be a good search candidate, I found https://github.com/aws/aws-sdk-php/issues/202#issuecomment-76384680 which has interesting tidbits regarding forking.

Also https://github.com/aws/aws-sdk-php/issues/202#issuecomment-332129511
> I can confirm that this is a Tinker Shell issue. Running the same in PHP's interactive shell everything works fine.

And finally https://cohan.me/php-curl-libcurl-error-on-subsequent-requests/

🤷‍♀️

**Comment by klfks** [comment]
@mfn , Thanks.
