### ISSUE TITLE
URL set wrong by subdomain routing if using named routes?

### ISSUE THREAD

**Issue by dannygerst** [laravel/framework#27239]
Hi,

I read about some issues with subdomain routing, but did not find a clear yes or no, if that is a bug or something that matches my issue having with named routes while using subdomain routing.

I have set different routes for different urls in my RouteServiceProvider:

```
   public function map()
    {
        $this->mapApiRoutes();
        $this->mapWebRoutes();
        $this->mapDCAppRoutes();
    }

    protected function mapDCAppRoutes()
    {

        Route::domain('data.www.example.com')
            ->middleware('web')
            ->namespace($this->namespace)
            ->group(base_path('routes/dc-web.php'));
    }
    
    protected function mapWebRoutes()
    {
        Route::domain('www.example.com')
            ->middleware('web')
            ->namespace($this->namespace)
            ->group(base_path('routes/web.php'));
    }
```

That is working as expected till I use named routes, for example for forms in my blades templates:

`
{{ Form::open(array('route' => ['products.update', $product->product_id], 'method' => 'put', 'name' => 'shelfForm')) }}
`

Routes are set as resouces in both route files:

`Route::resource('products', 'MageProductController');`

It is only working for one domain, but not for the other domain. Depending on the order of the calls in the method map of the RouteServiceProvider:

```
public function map()
    {
        $this->mapApiRoutes();

        **$this->mapWebRoutes();**
        **$this->mapDCAppRoutes();**
    }
```

So I called artisan route:list and saw this output (snip): 

```
| Domain               | Method    | URI                  | Name                 | Action                                                 | Middleware   |

| data.www.example.com | PUT|PATCH | products/{product}   | products.update      | App\Http\Controllers\MageProductController@update      | web          |

| www.example.com      | PUT|PATCH | products/{product}   | products.update      | App\Http\Controllers\MageProductController@update      | web          |
```

The order change if I change the order of the methods called in the map function.

So I think that the algorithmen what is picking the routes by name does not take the current used domain into account.

Work around is now to determine the url in the map function by myself:

```
public function map()
    {
        $this->mapApiRoutes();

        if (request()->server("HTTP_HOST") == 'www.example.com')
            $this->mapWebRoutes();
        else
            $this->mapDCAppRoutes();
    }
```
But this approach is not as elegant as let the router decide that instead.

Is this behavior a bug or a feature? If that is a feature how could I achieve that the url is set correctly if the route is called from different domains?

**Comment by driesvints** [comment]
Please resubmit this with the filled in issue template.

**Comment by jfernandes-dtm** [comment]
I'm having this exact issue and the workaround I've put up is similar to the OP. Can anybody point me at the right direction, because obviously I am doing something wrong. Thank you in advance for your support and comprehension.
Kind regards

**Comment by rufaidulk** [comment]
Use prefix for names

`Route::resource('product', 'ProductController', ['as' => 'admin']);`

this will generate name routes like admin.product.store.

then u can use

`route('admin.product.store')`

for the admin subdomain
