### ISSUE TITLE
How to have none statefull Facades in 5.8 ?

### ISSUE THREAD

**Issue by imanghafoori1** [laravel/framework#27247]
Due to this Pull request : https://github.com/laravel/framework/pull/25525
some lines of code where removed for 5.8

Since facades cache the resolved objects and keep it in memory for future calls.(to avoid re-resolving)
the facade become stateful.

https://github.com/laravel/framework/blob/27469f0a700569aa7ee3256c56ad553c96ce34b2/src/Illuminate/Support/Facades/Facade.php#L171

I used to a make and return an object from the `getFacadeAccessor` to deal with a new instance each time I make a call to my facade. 

So I feel I am missing a feature.

**Comment by driesvints** [comment]
Heya, thanks for submitting this. This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

**Comment by imanghafoori1** [comment]
@driesvints 
This seems to be related to some unexpected behavior.
```php
class FooFacade extends Facade
{
    protected static function getFacadeAccessor()
    {
        return 'foo';         // Key in container as non-singleton
    }
}
```
You will still get singleton, when you can the facade.
