### ISSUE TITLE
Validation messages not translated when using JSON language files

### ISSUE THREAD

**Issue by ekvedaras** [laravel/framework#27246]
- Laravel Version: 5.6.39
- PHP Version: 7.2

### Description:

When using language files in JSON format, validation errors ar not being translated.
I am not sure if this is intended behaviour (its frontend responsibility to translate?). If so, I guess at least a warning to documentation should be added.

#### Why it happens?

`__()` uses translator `getFromJson()` method, while validator uses `trans()` which is a wrapper for `get()`. 

`get()` method resolves namespaces while `getFromJson()` uses `*` from namespace.

### Steps To Reproduce:

1. Delete default php translation files
2. Create JSON translation file. For example:
`{
  "validation.required": "Field is required"
}`
3. Trigger validation exception. For example:
`dump(Validator::make([], ['field' => 'required'])->messages()->toArray())`

* Expected: `array:1 [
  "field" => array:1 [
    0 => "Field is required"
  ]
]`
* Got: `array:1 [
  "field" => array:1 [
    0 => "validation.required"
  ]
]`

**Comment by ekvedaras** [comment]
Now that I think of it, the intended behaviour is to use english strings as keys for JSON files. So the issue is irrelevant.

**Comment by zokaman** [comment]
But what if want to use these validation error translations only in json format?
