### ISSUE TITLE
Eloquent Builder orderBy() inside whereHas() always get no result

### ISSUE THREAD

**Issue by raiika** [laravel/framework#27258]
- Laravel Version: 5.7.19
- PHP Version: 7.3.0
- Database Driver & Version: phpMyAdmin 4.8.4

### Description:
First, this is mysql bug, 
Second, Laravel should do something about it

### Steps To Reproduce:
Short answer is, 

    $model->whereHas('child', function ($q) {
        $q->orderBy('name');

        $q->whereHas('another-child', function ($q) {
            $q->orderBy('name');

            $q->where('slug', 'input');
        });
    });

(if anyone wonder why I'm doing orderBy in a whereHas statement) my case is I placed orderBy in GlobalScope, it produce the same sql syntax as above

    select * from `buildings` where (exists (
        select * from `cities` where `buildings`.`city_id` = `cities`.`id` and exists (
            select * from `provinces` where `cities`.`province_id` = `provinces`.`id` and 
            `slug` = 'test' order by `name` asc
        ) order by `name` asc
    )) and `buildings`.`deleted_at` is null

### Conclusion
Above orderBy statement caused sql to return nothing, I think eloquent should ignore orderBy in whereHas statement, because it maybe is useless (at least in this case) and causing errors

**Comment by staudenmeir** [comment]
MySQL should ignore an `ORDER BY` clause in `WHERE EXISTS`, at least it does for me.

Please provide a minimal example with migration, data and query to reproduce this issue.

**Comment by raiika** [comment]
Schema::create('buildings', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('city_id')->unsigned();
            $table->string('name');
            $table->timestamps();
        });

        Schema::create('cities', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('province_id')->unsigned();
            $table->string('name');
            $table->timestamps();
        });

        Schema::create('provinces', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->string('slug');
            $table->timestamps();
        });

Then each model needs the relation to do whereHas

Problem found when using where condition on Grand Children along with order by

        $buildings = Building::whereHas('city', function ($q) {
            $q->orderBy('name');

            $q->whereHas('province', function ($q) {
                $q->orderBy('name');

                $q->where('slug', 'input');
            });
        })->get();

and will produce this sql

        select * from `buildings` where (exists (
            select * from `cities` where `buildings`.`city_id` = `cities`.`id` and exists (
                select * from `provinces` where `cities`.`province_id` = `provinces`.`id` and 
                `slug` = 'test' order by `name` asc
            ) order by `name` asc
        )) and `buildings`.`deleted_at` is null

Weird is when deleting any one of the order by, the result will be fine, but not if twice order by

Please check if I'm wrong

**Comment by staudenmeir** [comment]
Please add the models and the sample data. What version of MySQL are you using?

**Comment by raiika** [comment]
I don't really know how to check mysql version, but I'm using latest xampp that support php 7.3.0

## Model
    use Illuminate\Database\Eloquent\SoftDeletes;

    class Building
    {
        use SoftDeletes;

        public function city()
        {
            return  $this->belongsTo(City::class);
        }
    }

    class City
    {
        public function province()
        {
            return  $this->belongsTo(Province::class);
        }
    }

    class Province
    {
        //
    }

## Sample Data

    Province::insert([
        'name' => 'one',
        'slug' => 'number-1'
    ])
    City::insert([
        'name' => 'city-one',
        'province_id' => 1
    ])
    Building::insert([
        'name' => 'try-one',
        'city_id' => 1
    ])
    Building::insert([
        'name' => 'try-two',
        'city_id' => 1
    ])
    Building::insert([
        'name' => 'try-three',
        'city_id' => 1
    ])

now query using the above;

    $buildings = Building::whereHas('city', function ($q) {
        $q->orderBy('name');

        $q->whereHas('province', function ($q) {
            $q->orderBy('name');

            $q->where('slug', 'number-1');
        });
    })->get();

**Comment by staudenmeir** [comment]
I can't reproduce this on MySQL 5.7 or MariaDB 10.3.12.

Fiddle for MySQL 5.7: https://www.db-fiddle.com/f/k8n17y1NZbp1F9P9SJDhB3/0

**Comment by raiika** [comment]
You are right, I just commit my syntax to my server and it works fine,

I wonder why did my laptop gives result different, maybe it is because of Windows or something.

I'm closing the issues, thank you for your time @staudenmeir
