### ISSUE TITLE
count() has error on php 7.2

### ISSUE THREAD

**Issue by amir2b** [laravel/framework#27261]
- Laravel Version: 5.2.45
- PHP Version: 7.2.10

### Description:
[ErrorException]                                                            
count(): Parameter must be an array or an object that implements Countable

### Steps To Resolve:
Line 1185 on this file
vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php
change this code
`$originalWhereCount = count($query->wheres);`
to
`$originalWhereCount = count((array)$query->wheres);`

**Comment by xuanquynh** [comment]
Could you provide more information about it?
What is the exact statement that raises this error message?

**Comment by amir2b** [comment]
It is an old project and when i want to migrate the database it gives me the above error.
I changed the class in vendor and problem solved. 
I know there is no support anymore but that would be really nice if you accept my pull request.

**Comment by imanghafoori1** [comment]
you should use php 7.1 and you will be ok.

**Comment by driesvints** [comment]
Heya, unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.
