### ISSUE TITLE
[5.7.10] AsPivot - SoftDelete not working anymore (#26158)

### ISSUE THREAD

**Issue by lk77** [laravel/framework#27266]
- Laravel Version:5.7.10
- PHP Version:7.2.9
- Database Driver & Version: mysql 5.7

### Description:

Hello,

we have a problem with a change made in that pull request (#26158) that was published under laravel 5.7.10.
The scopes are not taken into account anymore, and it cause unexpected problems,
we are handling the soft delete of pivot elements ourselves (something like ModelClass::deleted(closure)) and we are calling delete() function on the pivot instance,
and it's not working anymore, the entries are really deleted in the table and not soft deleted.
it's because of the replacement of newQuery() by newModelQuery() in AsPivot, which ignore the scopes.

### Steps To Reproduce:

1 \\ Check that pivot class implement SoftDelete
2 \\ Check that pivot relation has a using() call with the correct pivot class
3 \\ Get a pivot instance, like $object->relation()->first()->pivot
4 \\ Call the delete function $pivot->delete()
5 \\ Check the database, rows are gone
6 \\ Replace newModelQuery by newQuery in AsPivot
7 \\ Repeat step 3 and 4, and check that rows are now correctly soft-deleted

The only fix for us seems to be using deleted_at property directly, without calling ->delete(), but it's more like a hack than a real solution.

Thanks.

**Comment by driesvints** [comment]
@staudenmeir can you take a look at this perhaps? Thanks!

**Comment by lk77** [comment]
thanks !
