### ISSUE TITLE
[5.7] Incorrect redirect route within resource

### ISSUE THREAD

**Issue by robinvdvleuten** [laravel/framework#27264]
- Laravel Version: 5.7.21
- PHP Version: 7.2.14
- Database Driver & Version: PostgreSQL 10

I created a redirect route through the `Route::redirect` method within a resource;

```php
Route::group(['prefix' => '{parent}'], function () {
    Route::resource('child', 'ChildController')->except(['index']);
    
    Route::get('child/{foo}/{bar}', 'ChildController@index');
    
    Route::redirect('child', 'child/with/filters')->name('child.index');
});
```

I expected that when I access `/parent/child`, I would be redirected to `/parent/child/with/filters`. But this seems not be the case and am redirected to a non absolute path.

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by edh649** [comment]
I have the same issue and agree that it is unexpected behaviour
