### ISSUE TITLE
Dynamic Table & Connection Relationship

### ISSUE THREAD

**Issue by mubbashar** [laravel/framework#27278]
- Laravel Version: 5.7.dev
- PHP Version: 7.2.4
- Database Driver & Version: mysql & 5.7.24

### Description:

I have 2 models 

- Book
- BookCategory

Book use connection mysql
BookCategory can use same connection mysql or other connection

I have dynamic categories tables. Like book_categories_1, book_categories_2, book_categories_3 and so on

Now I have a relation in Book Model

```
class Book extends Model
{
    protected $fillable = ['id', 'name','account_id' ];
    protected $table = 'books';

    public function categories()
    {
        $instance = new BookCategory($this->account_id);
        $foreignKey = 'book_id';
        $localKey = 'id';
        return $this->hasMany( $instance, $foreignKey, $localKey);
    }
}

```
BookCategory Model

```
class BookCategory extends Model
{
    protected $fillable = ['book_id', 'cat_id', 'col_a','col_b' ];
    protected $table = 'book_categories'; //this name will be dynamic

    public function __construct($account_id = null, array $attributes = [])
    {
        parent::__construct($attributes);

        if ($account_id != null ) {
            $this->setTable('book_categories_'.$account_id);
        }
        /*
         * use specific connection is available
         */
        $this->connection = getClientSpecificConnection($account_id);

    }
}
```
Database Tables

```

CREATE TABLE `book_categories_7` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `book_id` int(11) DEFAULT NULL,
  `cat_id` int(11) DEFAULT NULL,
  `col_a` varchar(64) DEFAULT NULL,
  `col_b` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `books` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(11) DEFAULT NULL,
  `account_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

```

As you can see I am setting table name dynamically and also connection dynamically

Now when I call this code

$book = Book::first();
$ele  = $book->categories()->first();

Getting this error

```
"message": "SQLSTATE[42S02]: Base table or view not found: 1146 Table 'test.book_categories' doesn't exist (SQL: select * from `book_categories` where `book_categories`.`book_id` = 1 and `book_categories`.`book_id` is not null limit 1)",
```

I debug the code and found out that hasMany relationship is calling newRelatedInstance() method.

```
public function hasMany($related, $foreignKey = null, $localKey = null)
{
    $instance = $this->newRelatedInstance($related);

    $foreignKey = $foreignKey ?: $this->getForeignKey();

    $localKey = $localKey ?: $this->getKeyName();

    return $this->newHasMany(
        $instance->newQuery(), $this, $instance->getTable().'.'.$foreignKey, $localKey
    );
}
```
And in newRelatedInstance() function a (new $class) is being created. 

```
protected function newRelatedInstance($class)
{
    return tap(new $class, function ($instance) {
        if (! $instance->getConnectionName()) {
            $instance->setConnection($this->connection);
        }
    });
}
```

Shouldn't it use the same object if we are passing an object in the hasMany relationship?

I mean like this 

```

return tap( is_object( $class ) ? $class : new $class, function ($instance) {
    if (! $instance->getConnectionName()) {
        $instance->setConnection($this->connection);
    }
});

```

Changing this code fix the issue

**Comment by electron93** [comment]
If you need personal categories for each account, why not just add `account_id` to the `book_categories` table? ... creating `book_categories_*` table for each user ... this is something new.

**Comment by driesvints** [comment]
Can you provide the exact version instead of `5.7.dev`? Or do you mean you're pulling in the latest commit from the 5.7 branch?

**Comment by mubbashar** [comment]
Yep, I am pulling latest commit from 5.7 branch. 

http://prntscr.com/mb1vfr

**Comment by driesvints** [comment]
The constraint you're putting there means you're pulling in the latest release, not the latest commit. Can you check your `composer.lock` file to see which version you're pulling in?

**Comment by mubbashar** [comment]
Version 5.7.20

http://prntscr.com/mb1yi8

**Comment by mubbashar** [comment]
I have accounts.

Accounts can have multiple campaigns
Campaigns can have multiple keywords

Keywords can be in millions for one account

There are 1000+ accounts and there are lots of insertion in campaigns and keywords table.

So I have taken the approach to separate table for every client

So table like for account id 1: campaign_1, keywords_1 and so on

As data from my tables is growing and touching to terabytes so I have multiple databases and separate account across databases.


I don't want to override the newRelatedInstance($class) method because that means I have to keep checking the core of laravel and whenever there is a change in the newRelatedInstance($class) I have to update it on my end as well. I don't want to go to that path.

**Comment by electron93** [comment]
@mubbashar Try looking at the existing partitioning mechanisms in mysql. With such a number of dynamically named tables, maintaining a database can become much more difficult. If you do not want to check the changes in `newRelatedInstance($class)`, you can probably write tests.

From your example, it would not hurt to introduce a reasonable limit on the number of campaigns per account and the number of keywords per campaign.

I think that this idea can be implemented, but how many people will use it? And how can they use that? `models_<of_parent_id>`?

**Comment by mubbashar** [comment]
@electron93  again the problem is not how I am using it. The thing is if I want to have a relationship with the dynamic table, I can't have with the current setup.

**Comment by driesvints** [comment]
Is this still a problem for you?

**Comment by mubbashar** [comment]
I have implemented it like this

`class Book extends Model
{
    protected $fillable = ['id', 'name','account_id' ];
    protected $table = 'books';

    public function categories()
    {
        $instance = new BookCategory($this->account_id);
        $instance->setTable( 'book_categories_'.$this->account_id );
        $foreignKey = 'book_id';
        $localKey = 'id';

        return $this->newHasMany(
            $instance->newQuery(), $this, $instance->getTable().'.'.$foreignKey, $localKey
        );
    }
}`

Now I have to watch the `newHasMany` in every release. If that somehow change then I have to update my code as well. Not sure if this is the best way but that is serving my purpose right now.

**Comment by deleugpn** [comment]
I wouldn't consider this a bug in the framework. The use case breaks database norms as well as Active Record definition. The most sensible approach for the problem seem to be partitioning the table instead.
As for multiple connections, you can define the model to point to a dynamic connection and establish the connection on the fly. It allows relationships to work fine. It just doesn't work with joins or sub queries.

**Comment by driesvints** [comment]
Closing this as this is currently not supported and also rejected in a follow-up pr: https://github.com/laravel/framework/pull/28728

**Comment by khushbupatel24** [comment]
@mubbashar , thanks man, It worked for me as well!

I was facing the same problem in **belongsTo** relationship where I have to set table in **user** model to **guest_user**. And I used **newBelongsTo** in relation.

`    public function guestUser()
    {
        $user = new User();
        $user->setTable('guest_users');

        return $this->newBelongsTo($user->newQuery(), $this, 'userId', 'id', 'guestUser');
    }`
