### ISSUE TITLE
Multiple curl requests fail only within Laravel on Amazon Linux

### ISSUE THREAD

**Issue by shawnhind** [laravel/framework#27274]
This issue is a duplicate of #27223 but that issue was closed a couple of days ago because in my issue I had only tested this error to be occurring on 5.6 but I've since tested this on 5.7 and it is also happening on that version.

- Laravel Version: 5.6.39 and also occurs on 5.7.21
- PHP Version: 7.1.23
- Database Driver & Version: N/A
- OS: Amazon Linux 2 AMI. Kernel Version 4.14
- Curl version: curl 7.53.1 (x86_64-redhat-linux-gnu) libcurl/7.53.1 NSS/3.36 zlib/1.2.8 libidn2/0.16 libpsl/0.6.2 (+libicu/50.1.2) libssh2/1.4.2 nghttp2/1.21.1

### Description:
When executing multiple curl requests over https with default options in laravel subsequent requests fail after the first one.  The reason why I believe this is an interaction between the curl version and laravel is for the following:

1. I could not get this problem to occur locally and my local system has a newer version of curl than the server.
2. Doing the same curl requests in php's interactive mode (php -a) (with no laravel loaded in) does not produce the error but when executed within laravel (via tinker) it does.
3. It does not occur with the command-line based curl client.

### Steps To Reproduce:
Create an EC2 instance through Amazon Web Services with Amazon Linux 2 LTS image.

Create a boilerplate laravel 5.6 application using composer.

Start an interactive tinker session
`php artisan tinker`

Run first curl request (will succeed):
```
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, "https://google.ca");
curl_setopt($ch, CURLOPT_VERBOSE, true);
$output = curl_exec($ch)
curl_close($ch)
```

Repeat the above within the same tinker session and subsequent requests after the first one will give the following error message:

````
>>> $output = curl_exec($ch);
* Hostname google.ca was found in DNS cache
*   Trying 172.217.7.131...
* TCP_NODELAY set
* Connected to google.ca (172.217.7.131) port 443 (#10)
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* NSS error -8023 (SEC_ERROR_PKCS11_DEVICE_ERROR)
* A PKCS #11 module returned CKR_DEVICE_ERROR, indicating that a problem has occurred with the token or slot.
* Closing connection 10
Curl Errno: 35
````

**Comment by driesvints** [comment]
Heya, thanks for reporting. First of all, all Tinker related issues should be reported on the Tinker issue tracker: https://github.com/laravel/tinker/issues

Besides that I'm wondering if this is a problem with Tinker or with [PsySH](https://psysh.org) (which Tinker uses underneath). 

Can you perhaps try to use recreate the problem with PsySH? If you still get the same problem then you should open up an issue on their issue tracker. If not, feel free to open up one on the Tinker issue tracker.

Thanks!
