### ISSUE TITLE
A bug with the refresh method (Model class)?

### ISSUE THREAD

**Issue by djug** [laravel/framework#27288]
- Laravel Version: 5.7.13
- PHP Version: 7.3.1
- Database Driver & Version: mysql  Ver 15.1 Distrib 10.3.12-MariaDB

### Description:
in `Illuminate/Database/Eloquent/Model.php`
if we take a look at the `fresh` method we find this at the beginning:
```php
if (! $this->exists) {
   return;
}
```
which mean if the model is no longer there we just return (`null`?).

but the behavior of the `refresh` method is slightly different:

```php
if (! $this->exists) {
   return $this;
}
``` 

in other terms, if we delete the model, and we execute the `fresh()` method on it, we will get `null`, but if we execute `refresh()` we will get the model back again, which, if I understand correctly, is not the intended goal of this method.

### Steps To Reproduce:

```php
>>> $user = User::first()
[!] Aliasing 'User' to 'App\User' for this Tinker session.
=> App\User {#2919
     id: 3,
     name: "Sienna Becker",
     email: "cbrekke@example.net",
     email_verified_at: "2018-11-16 06:21:34",
     created_at: "2018-11-16 06:21:34",
     updated_at: "2018-11-16 06:21:34",
   }
>>> $user->delete()
=> true
>>> $user->fresh()
=> null
>>> $user->refresh()
=> App\User {#2919
     id: 3,
     name: "Sienna Becker",
     email: "cbrekke@example.net",
     email_verified_at: "2018-11-16 06:21:34",
     created_at: "2018-11-16 06:21:34",
     updated_at: "2018-11-16 06:21:34",
   }
>>> 

```

if someone could  confirm that this is a bug I'll send a MR for it

**Comment by mfn** [comment]
As evident by gits history, it was made on purpose albeit with no discussion I could quickly find:
- first introduced, **did not** return `$this` => https://github.com/laravel/framework/pull/19174
- 3 months later changed without much fanfare => https://github.com/laravel/framework/pull/20657

Best to ask @themsaid wo did the change.

But in any event, it's seems quite deliberate and not like a bug so a change should be discussed on https://github.com/laravel/ideas

**Comment by driesvints** [comment]
@mfn thanks for explaining!

**Comment by djug** [comment]
@driesvints I think we still need to wait for @themsaid  for this one, since he wrote the code (because there is a chance the code needs to be fixed).

could you please reopen it?

**Comment by driesvints** [comment]
@djug I pinged him but you can always reach him on discord etc

**Comment by devcircus** [comment]
These two methods were designed to have different behavior. This is what I would expect.

**Comment by themsaid** [comment]
This was made like this so `$model->refresh()->exists` return false after deletion. You still have the model object after it was refresh so you can check the `current` state.
