### ISSUE TITLE
A Eloquent database json increment and decrement bug

### ISSUE THREAD

**Issue by medz** [laravel/framework#27303]
- Laravel Version: 5.7.*
- PHP Version: 7.2
- Database Driver & Version: MySQL 5.7

### Description:

create a database table:

```php
        Schema::create('user', function (Blueprint $table) {
            $table->increments('id');
            $table->json('extra');
        });
```

the `extra`:

```json
{
    "count": 1
}
```

run: 
```php
$user->increment('extra->count'); 
```

throw:  `Unknown index: extra->count`

**Comment by staudenmeir** [comment]
This is not yet supported, I'll take a look.

**Comment by driesvints** [comment]
Heya, thanks for submitting this. This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.
