### ISSUE TITLE
Queues log jobs dispatched by themselves in sync mode

### ISSUE THREAD

**Issue by autaut03** [laravel/framework#27319]
- Laravel Version: 5.7.22
- PHP Version: 7.2
- Database Driver & Version: MySQL 5.8

### Description:
When you broadcast events in sync mode (`ShouldBroadcastNow` interface) inside of a job, processed by a queue, Laravel logs `Processing` and `Processed` lines for these events, even though this particular queue has nothing to do with the events and uses a completely different driver (beanstalkd). Here's a log of what's happening for better understanding: https://gist.github.com/autaut03/16438be32a2a0b7a76762dcd89d0f91d

Notice that jobs with classes that have `Job` suffix also have proper IDs, while other don't.

I believe that other than some kind of queue events, this bug is purely cosmetical.

### Steps To Reproduce:
1. Create a broadcast event class implementing `ShouldBroadcastNow`
2. Create a job class that broadcasts that event
3. Run queue worker
4. Dispatch the job

**Comment by driesvints** [comment]
I'll need more info and/or code to debug this further. Please post relevant code like models, jobs, commands, notifications, events, listeners, controller methods, routes, etc. You may use https://paste.laravel.io to post larger snippets or just reply with shorter code snippets. Thanks!

**Comment by autaut03** [comment]
I prepared a [repo](https://github.com/autaut03/laravel-queues-bug-example) for that. There's a short readme explaining how to reproduce the bug, as well as a separate commit showing every change I did on top of clean laravel installation.

**Comment by deleugpn** [comment]
I understood the problem, but I'm not sure if it's worth an if condition on the WorkCommand to avoid writing these log lines. Obviously we cannot avoid dispatching the events just because the queue is `sync`, however I understand that the WorkCommand is subscribing to that event and saying that  it worked something that it actually didn't. 
On the other hand, some people might even consider this a feature instead. By working a message that dispatches multiple sub-jobs, you get to see them being processed correctly in the worker output.
Is there any real world scenario you could provide that explains why this is harming your project?

**Comment by autaut03** [comment]
@deleugpn It doesn't harm my project in any way, but it was confusing to me as I thought they were dispatched into a non sync queue. 

I'm not sure if this can be considered a "feature", because to me, as a developer, it would make sense to have two different interfaces: one, `ShouldBroadcast`, that actually uses the queue under the hood to handle events, and second, `ShouldBroadcastNow`, which really has nothing to do with neither the first one or the queue at all (but it, unfortunately, does), and it's sole purpose is to just dispatch the event immediately. 

But all this is just a little bit of feedback. I understand that this is not really a major issue, but I feel like it would make a bit more sense the way I see it.

**Comment by driesvints** [comment]
I have no idea how the events even get in that log. When I run `php artisan seed-job` for that repo it gets stuck for me. I'm going to close this for now because nothing is really broken here afaik. Feel free to send in a PR if you think anything can be improved.
