### ISSUE TITLE
Why isn't getEmailForPasswordReset used for the most of the password reset?

### ISSUE THREAD

**Issue by tontonsb** [laravel/framework#27320]
The method name `getEmailForPasswordReset` in the [CanResetPassword](https://github.com/laravel/framework/blob/master/src/Illuminate/Auth/Passwords/CanResetPassword.php) trait and contract makes one think that this email would be used to send password resets.

However, it is actually only [used](https://github.com/laravel/framework/search?q=getEmailForPasswordReset) when creating or deleting the tokens in `Illuminate/Auth/Passwords/DatabaseTokenRepository`.

The reset process seems pretty inconsistent with regards to email address. The name of the method and the description implies more than they actually do.

1. User requests the reset link. 
2. PasswordBroker matches user using `retrieveByCredentials` on the `UserProvider`. And the `credentials` is whatever the user posted. It could be `'myname' => 'ricke'` or `'mailTwoo' => 'tim@example.com'`.
3. A token associated with whatever `getEmailForPasswordReset` returned on the user. Say it's `$user->mailThree` which was `tom@example.com` this time;
4. The token is sent through the notification system. This defaults to the `$user->email` attribute without invoking any getters anywhere. This could be `ted@example.com`.
5. User comes back and posts the reset form. Post contains token, new password and some credentials depending on input names.
6. PasswordBroker matches it with a user according to post. it could be `'name' => 'Jeff'` and the user will be matched.
7. PasswordBroker also checks the supplied token and matches it with the identified user using `getEmailForPasswordReset`.

Wouldn't it be reasonable to retrieve whatever `$user->getEmailForPasswordReset()` provides and use it in every step of the reset?

And even if the answer is no, could we consider stating this (what the method does and what it doesn't) explicitly in the files (trait and contract) to prevent false expectations from this method.

**Comment by driesvints** [comment]
Heya, thanks for submitting this. This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.
