### ISSUE TITLE
Verification email not sent upon registration until re-send requested; inconsistent with message given to user

### ISSUE THREAD

**Issue by teo1978** [laravel/framework#27323]
- Laravel Version: 5.7.0
- PHP Version: irrelevant
- Database Driver & Version: irrelevant

### Description:
With an out-of-the-box installation of Laravel, with all the Users boilerplate in place (Users table, authentication, email verification), when a user registers, he gets redirected to /email/verify where he gets a message that says:

> Before proceeding, please check your email for a verification link. If you did not receive the email, click here to request another.

However, at this stage **no email whatsoever has been sent** to him. Only when he clicks the link to request "another", he will receive the email verification for the very first time.

### Steps To Reproduce:
- register as a new user

### Expected behavior
Either you send the user an email verification email immediately (which would be the sensible choice as all websites do today), or you tell him that he needs to explicitly request one, if that is the case.

### Observed behavior
No email is sent upon registration. However, this misleading message:
> Before proceeding, please check your email for a verification link. If you did not receive the email, click here to request another.

suggests that an email has already been sent.

**Comment by ahinkle** [comment]
I’m unable to reproduce — works for me. 

Are you able to reproduce this error using the latest minor (5.7.*) release?

**Comment by driesvints** [comment]
Please fill in the issue template and don't post "irrelevant".

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by teo1978** [comment]
> Looks like this is a question which can be asked on a support channel.

What?? Nope, this is a bug. Another thing is whether it's already fixed in a version later than the one I'm using. I'll try to check that.

**Comment by vkyeswa** [comment]
@teo1978 did you have this fixed? have the same issue

**Comment by teo1978** [comment]
> did you have this fixed?

@vkyeswa no.

>  Are you able to reproduce this error using the latest minor (5.7.*) release?

@ahinkle I have just upgraded and yes.

However, obviously I can only upgrade the framework core. I'm not sure whether the bug is there, or in the application space, that is the boilerplate application that gets created when you create a project. I can't upgrade that. _If_ it's the latter, and _if_ it's fixed there, then a way should be provided to get it fixed on existing projects.

Either way this needs to be reopened (shouldn't have been closed in the first place).

**Comment by vkyeswa** [comment]
The docs were updated to include the fix...
`In order to send the email when a user is registered, you should register following events and listeners in your App\Providers\EventServiceProvider class:`
[5.7 upgrade documents](https://laravel.com/docs/5.7/upgrade)
