### ISSUE TITLE
Translator interface missing getFromJson method

### ISSUE THREAD

**Issue by amadeann** [laravel/framework#27331]
- Laravel Version: 5.7.22
- PHP Version: n/a
- Database Driver & Version: n/a

### Description:

`__()` translation helper depends on `getFromJson` method, which is not a part of [Translator](https://github.com/laravel/framework/blob/5.7/src/Illuminate/Contracts/Translation/Translator.php) interface:

```
function __($key, $replace = [], $locale = null)
{
    return app('translator')->getFromJson($key, $replace, $locale);
}
```

I'm not sure what would be a better way to go about it: include `getFromJson` method in the Translator interface, or change the implementation of `__()` helper, so that it uses only method from the itnerface.

This issue was reported before in various forms, but not addressed:
https://github.com/laravel/framework/pull/23258
https://github.com/laravel/framework/issues/23162

As is stands now, if I want to swap the Translator in tests, I have to implement a method not defined in the interface.

**Comment by driesvints** [comment]
Since other issues and prs were closed already I'm closing this one as well. If you really want to change this it's best to open an issue at [laravel/ideas](https://github.com/laravel/ideas) first.
