### ISSUE TITLE
Migrations break on 5.3 on CREATE INDEX CONCURRENTLY

### ISSUE THREAD

**Issue by djeux** [laravel/framework#27334]
- Laravel Version: 5.3.*
- PHP Version: *
- Database Driver & Version: postgres 10.4

### Description:
If a migration contains DB::statement('CREATE INDEX CONCURRENTLY') , which is a way in postgres to create indexes without locking. The migration will fail due to postgres unable to wrap this statement inside a transaction
```
Illuminate\Database\QueryException: SQLSTATE[25001]: Active sql transaction: 7 ERROR:  CREATE INDEX CONCURRENTLY cannot run inside a transaction block 
```

The only workaround for this is disabling them all together for migrations
```php
$this->app->afterResolving('migrator', function(Migrator $migrator)
        {
            $connection = $migrator->resolveConnection(null);
            // NoTransactionPostgresGrammar override PostgresGrammar and sets $transactions = false
            $connection->setSchemaGrammar(new NoTransactionsPostgresGrammar());
            return $migrator;
        });
```

### Steps To Reproduce:
Add DB::statement('CREATE INDEX CONCURRENTLY ...') inside a migration up() method.

**Comment by ahinkle** [comment]
Hi @djeux,

Patches and minor fixes for 5.3 are no longer supported.  See https://laravel.com/docs/5.7/releases#support-policy

Are you able to replicate this issue on 5.5 LTS or 5.7?

**Comment by driesvints** [comment]
Heya, unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.

**Comment by staudenmeir** [comment]
As a workaround, you can commit (or roll back) the transaction before executing your query:

```php
DB::commit();
DB::statement('CREATE INDEX CONCURRENTLY ...');
```

In Laravel 5.5+, you can add this to your migration (#22757):

```php
public $withinTransaction = false;
```
