### ISSUE TITLE
morphTo relation changes name with eager loading

### ISSUE THREAD

**Issue by terryShifft** [laravel/framework#27342]
- Laravel Version: 5.6.39
- PHP Version:
- Database Driver & Version:
mysql

### Description:
I've got a model called Meter which has a polymorphic relationship called meterable. In the database this relationship is defined as source_id + source_type. The definition in the model is as follows:
`public function meterable()
	{
		return $this->morphTo('source');
	}`

When I use with('meterable') the relationship will be accesible by source instead of meterable.

### Steps To Reproduce:
Migration:
`Schema::create('meters', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('source_id')->nullable();
            $table->string('source_type')->nullable();
            $table->timestamps();
        });
    }`

Model:
`declare(strict_types=1);
namespace App\Models;
class Meter extends Model
{
        public function meterable()
	{
		return $this->morphTo('source');
	}
}`

The problem:
`use App\Models\Meter;
$meterEager = Meter::with('meterable')->first();
dump($meter->meterable);//returns null
dump($meter->source);//returns the object
$meterNoneEager = Meter::first();
dump($meter->meterable);//returns the object
dump($meter->source);//returns null`

**Comment by driesvints** [comment]
Heya, unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.

**Comment by staudenmeir** [comment]
See #24815.

You can use this workaround:

```php
public function meterable() {
    return $this->morphTo(null, 'source_type', 'source_id');
}
```
