### ISSUE TITLE
Exception output of missing function in controller is wrong

### ISSUE THREAD

**Issue by SamuelNitsche** [laravel/framework#27344]
- Laravel Version: 5.7.22
- PHP Version: 7.2.4
- Database Driver & Version: -

### Description:
When you add a route to a controller function that does not exist, laravel throws a `ReflectionException` instead of a `BadMethodCallException`. The exception says that the function `()` does not exist.

![bildschirmfoto 2019-01-29 um 11 23 19](https://user-images.githubusercontent.com/24483576/51901603-5182ec00-23b8-11e9-9bc9-558cb693a464.png)

### Steps To Reproduce:
1. Edit your `web.php` file like this (does not happen when you pass the controller and function as string)
```
Route::get('/test', [TestController::class, 'index']);
```

2. Create the `TestController` but don't create function `index`
```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class TestController extends Controller
{
    //
}
```
3. Visit the new route

Expected behaviour would be that laravel tells which function does not exist.

**Comment by driesvints** [comment]
Hmm, I can see why this is a problem indeed although I wouldn't necessarily label this as a bug but rather an enhancement. Welcoming PRs which might improve this error message.

**Comment by akiyamaSM** [comment]
Is it even the good syntax? I mean even if you put a name of existing method it wouldn't work.

**Comment by SamuelNitsche** [comment]
The syntax is correct. I think this is possible since 5.6 or 5.7, not sure.

**Comment by akiyamaSM** [comment]
may be something related to the version of PHP 7.1.20

**Comment by driesvints** [comment]
A PR was merged that should address this: https://github.com/laravel/framework/pull/28397

Thanks @570studio
