### ISSUE TITLE
5.7.23 bug - ResetPassword notification passes wrong type to Lang::getFromJson

### ISSUE THREAD

**Issue by owenconti** [laravel/framework#27349]
- Laravel Version: 5.7.23
- PHP Version: 7.1
- Database Driver & Version: MySQL 8

### Description:

Looks like there was a recent change to the `ResetPassword` notification to pass the expiration time in the notification:

* https://github.com/laravel/framework/commit/80c5aecb443e7a55e868b66b9e0a93b7dfec08e8
* https://github.com/laravel/framework/commit/607caff844f1b2dd33c446576fcd3e881e91c3cb#diff-c8ea781a710f1f10006548de795a6a35

However, `Lang::getFromJson` accepts an array as its second parameter, not an integer.

### Steps To Reproduce:

Reset a user's password.

**Comment by TBlindaruk** [comment]
looks like, that issue is fixed in https://github.com/laravel/framework/releases/tag/v5.7.24 release

**Comment by jonnott** [comment]
+1 for getting this fixed!
