### ISSUE TITLE
Middleware session flash twice

### ISSUE THREAD

**Issue by AlinIonut** [laravel/framework#27345]
- Laravel Version: 5.7.22
- PHP Version: 7.2
- Database Driver & Version: MySQL

### Description:

When flashing a message in a web middleware throw Session::flash('key', 'msg') or $request->session()->flash('key', 'msg'), the message is flashed for 2 requests in a row.

### Steps To Reproduce:

1. Create a middleware
2. Set middleware in kernel under web, to affect all web routes
3. In middleware make a small Request check (if request has some query builder in it, session flash custom msg.)

`
if($request->test){
Session::flash('key', 'msg');
}
`

4. run /custom-route?test=foo (message is flashed)
5. run /custom-route (message is flashed again)

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
