### ISSUE TITLE
Carbon 2 needed

### ISSUE THREAD

**Issue by Eugene-Melbourne** [laravel/framework#27355]
- Laravel Version: 5.7.24
- PHP Version: 7.2
- Database Driver & Version: MySQL

### Description:

Help, Carbon 2 needed.

    Using version ^2.10 for nesbot/carbon

    Updating dependencies (including require-dev)
    Your requirements could not be resolved to an installable set of packages.

      Problem 1
        - laravel/framework v5.7.24 requires nesbot/carbon ^1.26.3....

    Installation failed, reverting ./composer.json to its original content.

### Steps To Reproduce:

    $composer require nesbot/carbon

**Comment by staudenmeir** [comment]
Laravel 5.8 will support Carbon 2 (#25320). Why do you need it now?

**Comment by devcircus** [comment]
This can't be changed at the framework level on 5.7. There are several discussions in the issues and PRs, concerning this, if you'd like more information.

**Comment by Eugene-Melbourne** [comment]
Thank you.
