### ISSUE TITLE
Failed to create controller named `List` during making model with -a argument

### ISSUE THREAD

**Issue by elnurxf** [laravel/framework#27365]
- Laravel Version: 5.7.19
- PHP Version: 7.1.7 (cli)
- Database Driver & Version: Not required

### Description:
Failed to create controller named `List` during making model with -a argument

### Steps To Reproduce:
``` bash
$ php artisan make:model List -a
```
 Failed with: Syntax error, unexpected 'List' (T_LIST), expecting identifier (T_STRING)

 but 
``` bash
$ php artisan make:controller List
```

 Is works!

**Comment by elnurxf** [comment]
@brunogaspar Yes, I know, but looks weird to me IMHO, because of If It works on ```make:model -a```, It should work on ```make:controller```

**Comment by brunogaspar** [comment]
Well, i don't think it should even allow the creation, since that's a reserved word, but again, i don't know how those generators work nor i really use them that much. But it's perhaps something to improve.

**Comment by elnurxf** [comment]
@brunogaspar Well, should be considered in next bug fixes. Thank you.

**Comment by ahinkle** [comment]
See https://github.com/laravel/framework/issues/26730#issuecomment-444072143.

**Comment by staudenmeir** [comment]
This is not a Laravel bug, a PHP class can't be named `List`. 

`php artisan make:controller List` doesn't throw an error, but you still can't use the invalid class.

I don't think it's Laravel's job to check the class name.
