### ISSUE TITLE
Can't change language of doctrine/inflector 🌎

### ISSUE THREAD

**Issue by fede91it** [laravel/framework#27364]
- Laravel Version: 5.7.20
- PHP Version: 7.3
- Database Driver & Version: not relevant

### Description:

From Laravel it is not possible to change the language used by doctrine/inflector for the pruralisation of words, as well as table names.

doctrine/inflector allows the use of specific rules of pluralisation and singularisation for certain languages, I would like to understand how I can define the language to be used by Laravel.

See https://www.doctrine-project.org/projects/doctrine-inflector/en/2.0/index.html

### Steps To Reproduce:

`str_plural('car')` it becomes `cars` because the word used is in english.
`str_plural('macchina')` (that it is car, in italian) it actually becomes `macchinas` that is wrong because the right plural form of `macchina` is `macchine`.

Actually there is no way to configure the underlying doctrine/inflector to use the italian rules instead of the english ones.

**Comment by staudenmeir** [comment]
The steps to reproduce are relevant, please add them.

**Comment by staudenmeir** [comment]
This feature hasn't been released yet:

> You are browsing a version that has not yet been released.

**Comment by f-liva** [comment]
Good morning, this issue is absolutely not completed and needs to be reopened also because I found out that in flaktor, dottrine has more languages available besides English. Therefore, Laravel should necessarily provide the possibility to define the language used for string inflections.
