### ISSUE TITLE
Simpler way to chain jobs of the same type

### ISSUE THREAD

**Issue by vedmant** [laravel/framework#27362]
Currently the only way to chain jobs is to use static method SomeJob::wichChain(), but it's very not convenient in case I need to chain multiple jobs of the same type, co currently I have following to do this:

```
        if ($domains->count() === 1) {
            ImportForDomain::dispatch($domains->first());
        }

        if ($domains->count() > 1) {
            ImportForDomain::withChain($domains->slice(1)->map(function ($domain) {
                return new ImportForDomain($domain);
            }))->dispatch($domains->first());
        }
```

Would be nice to have something simpler like:
```
            app(Dispatcher::class)->dispatchChain($domains->map(function ($domain) {
                return new ImportForDomain($domain);
            }));
```

**Comment by sisve** [comment]
This sounds like something for https://github.com/laravel/ideas/.

**Comment by driesvints** [comment]
Heya, thanks for submitting this. This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.
