### ISSUE TITLE
Collection concat modifies integer index of second array

### ISSUE THREAD

**Issue by Noogic** [laravel/framework#27366]
- Laravel Version: 5.7.24
- PHP Version: 7.2
- Database Driver & Version: doesn't apply

### Description:
**concat** method in _Illuminate\Support\Collection_ does not respect index keys of second array when they are integers

### Steps To Reproduce:
```
$a = collect([2 => 'a', 4 => 'b']);
$b = collect([10 => 'c', 12 => 'd']);

$result = $a->concat($b);
```

Expected
```
[
    2 => "a",
    4 => "b",
    10 => "c",
    12 => "d",
]
```

Actual Output
```
[
    2 => "a",
    4 => "b",
    5 => "c",
    6 => "d",
]
```

Using `$a->toArray() + $b->toArray();` does show the expected and desired output.

**Comment by staudenmeir** [comment]
This is the expected behavior, it doesn't respect strings keys either.

Use `union()` instead: https://laravel.com/docs/collections#method-union

**Comment by staudenmeir** [comment]
It appends the values of the second array after the last key of the first array.

**Comment by devcircus** [comment]
What if the keys conflicted? The current behavior is the only way that makes sense to me.

**Comment by Noogic** [comment]
Ok, I understand. Thank you and thank you for referencing the _union_ method
