### ISSUE TITLE
Is Laravel bloated with its defaults?

### ISSUE THREAD

**Issue by thecodingdude** [laravel/framework#27374]
So as somebody whose used Laravel for a number of years, I wanted to discuss my concerns around Laravel's 'default' state when creating a new application. And some confusion and frustrations when trying to understand what is/isn't safe to delete and how to go about doing it.

1: Default middleware

Laravel includes a bunch of middleware by default, this Middleware _can_ be deleted, but if you do, the user needs to know to delete it from app/http/kernel. If we delete "TrimStrings.pnp" file, we get an error:

```
ErrorException (E_WARNING)
include(C:\Users\dev\code\web\vendor\composer/../../app/Http/Middleware/TrimStrings.php): failed to open stream: No such file or directory
```

Which isn't very helpful letting me know I need to delete the relevant line in app/http/kernel.php.

2: Providers

This is worse, because in config/app, the BroadcastServiceProvider is commented out by default (why?), and so you _can_ delete that service provider, and your app won't complain, but if we delete EventServiceProvider we get another error:

```
ErrorException (E_WARNING)
include(C:\Users\dev\code\web\vendor\composer/../../app/Providers/EventServiceProvider.php): failed to open stream: No such file or directory
```

Again, not so helpful when it doesn't explain you need to modify the app config file.

3: Default includes

I notice things such as Redis are included by default, such as

```
Illuminate\Redis\RedisServiceProvider::class,
'Redis' => Illuminate\Support\Facades\Redis::class,
```
I appreciate Redis _is_ popular, but my point here is there is so much going on by default it almost feels unnecessary.

For example, the default API web routes, which are included by default in RouteServiceProvider where if you do delete  routes/api.php, you need to delete it on the service provider. Or the default Auth controller directory, or the Consoles/Kernel.php

Another issue is the default Middleware, we have $middleware, $middlewareGroups, $routeMiddleware and $middlewarePriority, and it's not entirely clear which we can get rid of, which are important, since there's no real explanation. They're just "there" and their purpose isn't obvious.

My point is whilst it's great Laravel bundles many things by default, I want an extremely minimalistic setup (ExpressJS is great for this but even then it has some questionable default includes) with no added extras, every extra include is extra processing resources and time. May not make an earth shattering difference, but it'd be nice to delete a file from userspace and have a friendly error message instead of the cryptic confusion we get today.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not for ideas, suggestions etc. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. You are able to open a ticket at https://github.com/laravel/ideas

Alternatively you are able to open a PR using the Contributions guidelines: https://laravel.com/docs/5.7/contributions#which-branch

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.

**Comment by thecodingdude** [comment]
Hi @laurencei 

I'd argue this is less of an idea/feature request and more of a bug in the sense that I, as a developer, am removing files included by default, that I no longer need or didn't need in the first place, and the framework is throwing errors that make no sense or have a clear way of resolution.

There are many confusing things Laravel has be default as I expressed and I wanted to engage the community on ways we can help make this clearer, such that somebody can easily delete anything and everything would work as expected.
