### ISSUE TITLE
Problem running Laravel Multitenancy on Laravel Forge, without problems on local environment

### ISSUE THREAD

**Issue by wa05** [laravel/framework#27378]
- Laravel Version: 5.7
- PHP Version: 7.2
- Database Driver & Version: MySql 5.7

### Description:
Running tenant migrations with laravel multitenancy (https://github.com/hyn/multi-tenant) on Laravel Forge im receiving this error:

Doctrine\DBAL\Driver\PDOException  : SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT trans2 does not exist

  at /home/forge/brightmind-erp.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43
    39|     {
    40|         try {
    41|             return parent::exec($statement);
    42|         } catch (\PDOException $exception) {
  > 43|             throw new PDOException($exception);
    44|         }
    45|     }
    46| 
    47|     /**

  Exception trace:

  1   PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT trans2 does not exist")
      /home/forge/brightmind-erp.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:41

  2   PDO::exec("ROLLBACK TO SAVEPOINT trans2")
      /home/forge/brightmind-erp.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:41

  Please use the argument -v to see more details.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

**Comment by wa05** [comment]
Solved removing transactions when creating tenants

**Comment by johnefe** [comment]
Capo

**Comment by medteck** [comment]
Could you please provide more details about how your performed "removing transactions when creating tenants" ?
