### ISSUE TITLE
Different validation rule not working as intended?

### ISSUE THREAD

**Issue by ryanmortier** [laravel/framework#27371]
- Laravel Version: 5.7.24
- PHP Version: 7.3.1

### Description:
I recently upgraded my application from Laravel 5.4 to Laravel 5.7 and now using the `different` validation rule, comparing a null value to a non-null value doesn't work. It used to work fine.

### Steps To Reproduce:
Set up a form with two `select` fields with one blank option and a few non-blank options each (A, B, and C).

Use these rules:
```
'primary' => 'nullable|in:A,B,C|different:secondary|required_with:secondary',
'secondary' => 'nullable|in:A,B,C|different:primary',
```

If you choose an option for `primary` but leave `secondary` blank, the `different` validation rule fails with `errors: {primary: ["The primary and secondary must be different."]}`

`dd($request->all);` outputs the following:

```
array:2 [
  "primary" => "A"
  "secondary" => null
];
```

Am I correct in that this rule should pass with the above form data?

**Comment by staudenmeir** [comment]
This will be fixed in Laravel 5.8: https://github.com/laravel/framework/pull/26807

**Comment by ryanmortier** [comment]
Great, thanks. 

Question, is there a quick way to temporarily fix this without creating a custom validation rule?

**Comment by koenhoeijmakers** [comment]
You can always just extend / override the validator

**Comment by staudenmeir** [comment]
A custom validation rule is probably the best workaround.
