### ISSUE TITLE
Raw query with same SQL as a query builder instance returns different results

### ISSUE THREAD

**Issue by CyberiaResurrection** [laravel/framework#27377]
- Laravel Version: 5.7.22
- PHP Version: 7.2.14
- Database Driver & Version: InnoDB, 10.3.12-MariaDB-debug

### Description:
A raw query has the same underlying SQL as a query builder instance.  Yet, the raw query returns a non-zero number of records while running builder->get() returns an empty collection (ie, zero number of records).

### Steps To Reproduce:
1.  Clone out https://github.com/cruxinator/LaravelIssue.git .
2.  Change into directory, run composer-update.
3.  Copy .env.example to .env, supply appropriate DB details.  The phpunit tests will spin up a database at the start of each run.
4.  Run ```phpunit --filter=testIssueFetching```  .  This fails on line 29 of CollectionTest.php.

**Comment by staudenmeir** [comment]
First query: `oqLinksParentIds != ''`
Second query: `oqLinksParentIds != null`

**Comment by CyberiaResurrection** [comment]
Fair cop @staudenmeir  - my goof.

How do I go about applying a ```having `oqLinksParentIds` is not null``` clause, other than using havingRaw?

Shouldn't there be a havingNull/havingNotNull pair, by functional analogy with whereNull/whereNotNull?

**Comment by staudenmeir** [comment]
`havingRaw()` is the only option at the moment.
