### ISSUE TITLE
PHPUnit 8 support

### ISSUE THREAD

**Issue by alphametric** [laravel/framework#27381]
In order to support PHPUnit 8, the `setUp` and `tearDown` methods in Laravel's `TestCase` need to be set to return `void`

e.g.

`tearDown() : void`

**Comment by laurencei** [comment]
ping @GrahamCampbell - your the expert at this type of stuff...

**Comment by alphametric** [comment]
It turns out, it isn't as simple as making those changes. Many tests return warnings related to Laravel's usage of assertContains():

`Using assertContains() with string haystacks is deprecated and will not be supported in PHPUnit 9. Refactor your test to use assertStringContainsString() or assertStringContainsStringIgnoringCase() instead.`

`Using assertNotContains() with string haystacks is deprecated and will not be supported in PHPUnit 9. Refactor your test to use assertStringNotContainsString() or assertStringNotContainsStringIgnoringCase() instead.`

**Comment by alphametric** [comment]
Also the `assertJson` methods use `assertArraySubset`:

assertArraySubset() is deprecated and will be removed in PHPUnit 9.

There are probably other issues too, but it looks like for now, Laravel users will need to stick with PHPUnit 7.*

Ping @driesvints

**Comment by mfn** [comment]
The release statement mentions the deprecation changes quite well: https://phpunit.de/announcements/phpunit-8.html

**Comment by alphametric** [comment]
Indeed it does, but it’ll require changes to Laravel’s TestResponse, and maybe other areas for the two to be compatible.

**Comment by mfn** [comment]
At a first glance, I see:
- orchestra/testbench-core needs to be updated itself, otherwise a no-go with 8
- ~188 failed test due to deprecated behaviours

**Comment by laurencei** [comment]
Hi everyone,

I know @taylorotwell and @driesvints are aware of this general issue with PHPUnit 8 - so they will be working on a plan/solution behind the scenes.

We'll leave the ticket open so people are aware.

**Comment by driesvints** [comment]
Heya. We're indeed aware and I'm going to try to have a look at this this week.

**Comment by lucasmichot** [comment]
I've made 2 PR for this upgrade https://github.com/laravel/framework/pull/27431 and https://github.com/laravel/framework/pull/27432, but they both require an upgrade to PHP 7.2

**Comment by driesvints** [comment]
@lucasmichot I'll probably look into this today

**Comment by driesvints** [comment]
Sent in a PR. Tests are failing atm until testbench has been updated: https://github.com/laravel/framework/pull/27441

**Comment by crynobone** [comment]
@driesvints just merge `phpunit8` to `3.8` branch. You can revert changes to `composer.json` now.

**Comment by kossa** [comment]
Which version of phpunit we should use ?

**Comment by Radoncode** [comment]
> Which version of phpunit we should use ?

I use php version 7.2, I replaced in my tests 'assertContains' by 'assertStringContainsString' and it works for me!

**Comment by driesvints** [comment]
Closing this as PHPUnit 8 support will be available once Laravel 5.8 is released.
