### ISSUE TITLE
An illuminate package "must" have a licence file

### ISSUE THREAD

**Issue by xuanquynh** [laravel/framework#27392]
Laravel framework core code is separated into many sub-packages under the name "illuminate". Although the framework is released under the MIT license, no illuminate package has a license. This is really not good if someone who wants to require just a few Laravel components. For example, I just want to use illuminate/console for my package but I have to use without a license detail.

A package must have a license to tell people what they could do with the source code or not. Therefore, please add a license file per illuminate package!

**Comment by staudenmeir** [comment]
Can you submit a PR?

**Comment by xuanquynh** [comment]
@staudenmeir Thanks! I think it completely depends on Mr.Otwell. I am not sure which license (MIT?) and how many versions he accepts (5.5?, 5.6?, 5.7?). Or he just doesn't care.

**Comment by driesvints** [comment]
I'll take this up with Taylor and see what we can do.

**Comment by xuanquynh** [comment]
@driesvints I hope to see the all licenses soon. Thanks!

**Comment by driesvints** [comment]
Done for 5.5, 5.7 & upcoming 5.8.
