### ISSUE TITLE
ELOQUENT COUNT

### ISSUE THREAD

**Issue by onmigregor** [laravel/framework#27397]
- Laravel Version: 5.4.#
- PHP Version:7.2
- Database Driver & Version: MYSQL Versión del servidor: 10.1.36-MariaDB

### Description:
        $types=Types::selectRaw('COUNT(property_types.id) as total, property_types.types, property_types.id')
                     ->join('properties', 'property_types.id', '=', 
                          'properties.property_type')
                   ->where('property_purpose', '"Sale"')
                   ->groupBy('property_types.id','property_types.id','property_types.types')
                   ->get();

                                dd($types);
 I have that query  but nothing give result  

I put -> toSql() and  I got my query

select COUNT(property_types.id) as total, property_types.types, property_types.id from `property_types` inner join `properties` on `property_types`.`id` = `properties`.`property_type` where `property_purpose` = ? group by `property_types`.`id`, `property_types`.`id`, `property_types`.`types`

change ? by "Sale" copy and paste on PhpMy admin and I Got

![image](https://user-images.githubusercontent.com/23129765/52167203-e43fc580-26ed-11e9-89ed-857597082b06.png)

**Comment by staudenmeir** [comment]
Remove the double quotes: `->where('property_purpose', 'Sale')`

**Comment by onmigregor** [comment]
THANKS!!!!!!!!!!!!!!! 100%
