### ISSUE TITLE
The elapsed time of command

### ISSUE THREAD

**Issue by Kamicloud** [laravel/framework#27408]
Hi
I want to add a time tracking in \Illuminate\Console\Events\CommandFinished, like [this](https://github.com/laravel/framework/pull/27391/commits/2e1897fb7dd45546db1d97e30dd468a8ead392f1)

So that we can easily to know how long does the command cost by watching CommandFinished event, shall we discus of that?

**Comment by ahinkle** [comment]
Sounds like a place for https://github.com/laravel/ideas

**Comment by Kamicloud** [comment]
> Sounds like a place for https://github.com/laravel/ideas

Thanks, I will close the issue
