### ISSUE TITLE
Laravel Telescope not working locally when access app using http://localhost/app/public/telescope

### ISSUE THREAD

**Issue by marwan2** [laravel/framework#27410]
As you mentioned in docs, Telescope is mainly used locally, but while trying to access it, using the regular URL on local: **http://localhost/laravelapp/public/telescope**, it doesn't work.

This is because it doesn't point correctly, also the sidebar URLs is pointing to **http://localhost/telescope**

I should run:
`php artisan serve`
to allow Telescope to work using URL:
**http://127.0.0.1:8000/telescope/requests**

This is even I added **APP_URL** in .env file correctly

**Comment by driesvints** [comment]
Please report this on the Telescope repo: https://github.com/laravel/telescope
