### ISSUE TITLE
laravel can not guess kml extension

### ISSUE THREAD

**Issue by michaelnguyen547** [laravel/framework#27416]
- Laravel Version: 5.7.20
- PHP Version: 7.2.9
- Database Driver & Version: Mysql v5.7

### Description:
When uploading a KML file, Laravel return an empty extension

### Steps To Reproduce:

$saved_path = Storage::disk('s3')->putFileAs('kml-folder', $request->file('kml_file'));
echo $saved_path;
`kml-folder/RQqcknhne9edkr2BNV42BgquqyoeVJgNI10NoyLG` without the '.kml'

**Comment by driesvints** [comment]
Please see https://github.com/laravel/framework/issues/26511 and related issues.
