### ISSUE TITLE
Mailable class seems to over-write same class objects when `build()` is called.

### ISSUE THREAD

**Issue by cjaoude** [laravel/framework#27413]
- Laravel Version: 5.6.39
- PHP Version: 7.3.1
- Database Driver & Version: n/a

### Description:
Mailable class seems to over-write same class objects when `build()` is called.

### Steps To Reproduce:
```
class Foo extends Mailable {
// ... 
public $old;
public $new;

public function __construct(Foo $old, Foo $new) {
$this->old = $old;
$this->new = $new;
}
public function build() { 
  $this->old // new
  $this->new // new
}
)
```

**Comment by mfn** [comment]
Please provide a reproducible example of your problem.

**Comment by driesvints** [comment]
Heya, unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.
