### ISSUE TITLE
Change markdown vendor path to "text" or similar

### ISSUE THREAD

**Issue by bert-w** [laravel/framework#27437]
So I was checking out https://laravel.com/docs/5.7/mail#markdown-mailables , and saw you could quite easily modify the component files by publishing them using `php artisan vendor:publish --tag=laravel-mail`.

I was slightly confused to see a file structure  with dir names `views/vendor/mail/html` and `views/vendor/mail/markdown`. I couldnt figure out why the name "markdown" was used here. After reading the documentation more carefully, it appeared to be the _text-counterpart_ of the email.

So the question arises: why is the map named `markdown` and not `text` ?

Changing `html` to `markdown` would seem logical too, but in this case either seem comprehensible.

To be specific, it is this directory:
https://github.com/laravel/framework/tree/5.7/src/Illuminate/Mail/resources/views/markdown

**Comment by driesvints** [comment]
This has already been done in the upcoming 5.8 release.
