### ISSUE TITLE
Enable possibility to localize error message of 'verified' middleware exception

### ISSUE THREAD

**Issue by Thanerik** [laravel/framework#27433]
Hi

There are serveral middlewares, where the returned exception message is "locked" in english with no possibility of localizate the string to another languages, e.g. the 'verified' middleware from `EnsureEmailIsVerified.php`:
https://github.com/laravel/framework/blob/1fb4ef72655e91b27d8d7177d02c81a25325f2f1/src/Illuminate/Auth/Middleware/EnsureEmailIsVerified.php#L24
It could be nice to add the localization possiblity by altering line 24 to `__('Your email address is not verified.')`, and the other messages from the other middlewares as well...

Best
Troels

**Comment by driesvints** [comment]
Heya, thanks for submitting this. This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.
