### ISSUE TITLE
Laravel 5.7:  blank page on IE 11

### ISSUE THREAD

**Issue by Soulnianfo** [laravel/framework#27435]
Hi!
I developed a website with laravel version 5.7, my website work well on chrome, firefox, microsoft edge. but it don't work on internet explore version 11, it render a blank page and show nothing error.
Can you help me ?

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
