### ISSUE TITLE
Paginate eager loaded relationships results

### ISSUE THREAD

**Issue by renoirfaria** [laravel/framework#27443]
Hi guys, i am trying to paginate a relationship result set by using a code very similar to this

```php
<?php

class MainController extends Controller {
    
    public function show(Main $main)
    {
        $main = $main->with([
            'secondaryMorph' => function ($query) {
                $query->orderBy('ocurred_at');
                $query->paginate(50);
            }
        ])->first();

        return view('main.show')->with(compact('main'));
    }
}
```

But when this part of the view's code run a exception is thrown:

```html
<td colspan="3">Mostrando {{ $secondary->count() }} de {{ $secondary->total() }}</td>
<td colspan="3">{{ $secondary->links() }}</td>
```

>ErrorException (E_ERROR)
>Method Illuminate\Database\Eloquent\Collection::total does not exist.

How can i use eager loading with pagination?

**Comment by staudenmeir** [comment]
For a single model, eager loading isn't necessary. Use lazy loading instead:

```php
class MainController extends Controller {
    public function show(Main $main)
    {
        $secondary = $main->secondaryMorph()->orderBy('ocurred_at')->paginate(50);

        return view('main.show')->with(compact('main', 'secondary'));
    }
}
```

**Comment by renoirfaria** [comment]
@staudenmeir occurs that i need to make nested eager loading with `sencondaryMorph()`'s relationships.

**Comment by staudenmeir** [comment]
Eager load the nested relationships:

```php
$secondary = $main->secondaryMorph()->orderBy('ocurred_at')->with('foo.bar')->paginate(50);
```

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
