### ISSUE TITLE
Cache::remember() should receive "callable" not "Closure"

### ISSUE THREAD

**Issue by shehi** [laravel/framework#27469]
- Laravel Version: 5.7
- PHP Version: 7.2
- Database Driver & Version: MariaDb latest

### Description:
```Cache::remember()``` requires Closure as an argument. It should be "callable" instead, so that we could pass class methods to it. Otherwise it is very hard to create central recache mechanisms whenever cache is "missed", without duplicating the code. Closures are "callable"s as well, thus the implementation of this request wouldn't create BC implications.

### Steps To Reproduce:
N/A

**Comment by shehi** [comment]
If the request is acceptable to you, I can try to send a PR.

**Comment by driesvints** [comment]
Heya, thanks for submitting this. This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.
