### ISSUE TITLE
WorkCommand::writeStatus() ignores $type parameter

### ISSUE THREAD

**Issue by cweiske** [laravel/framework#27483]
- Laravel Version: 5.7.25
- PHP Version: 7.2.15
- Database Driver & Version: MySQL 5.7

### Description:
Whenever a queued job is started and finished, laravel outputs log messages for them:

> Processing: \App\Jobs\Foo
> Processing: \App\Jobs\Bar
> Processed: \App\Jobs\Foo
> Failed: \App\Jobs\Bar

It is not possible to show error messages while hiding the processing + processed messages, because the method `WorkCommand::writeStatus()` that writes the log messages is ignoring the `$type` parameter that indicates the severity of the message.

The currently only way to stop the processing/processed messages to appear is using `./artisan horizon --quiet`, which also hides the failed error messages.

`WorkCommand::writeStatus()` should map the `$type` parameter to `OutputInterface::VERBOSITY_*` levels and pass it as 2nd parameter to `$output->writeln()`.

### Steps To Reproduce:

1. Run a scheduled job with `./artisan horizon` or `./artisan queue:work`
1. Output is shown: "Processing: .." and "Processed: ..."
1. Output should not be shown, because verbose output is not enabled

**Comment by driesvints** [comment]
Heya, thanks for submitting this. This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.
