### ISSUE TITLE
URL params are being stripped from grouped routes

### ISSUE THREAD

**Issue by twigg** [laravel/framework#27490]
- Laravel Version: 5.7
- PHP Version 7.3

### Description:

It seems when routes are in a group any GET params passed are being removed by Laravel, this breaks the built-in pagination as it is looking for the page GET param that isn't there.

### Steps To Reproduce:

This works fine:

`Route::get('/', 'HomeController@index')->name('home');`

I can attach GET params no problem and they show up in the request object in both the request params and query params as expected. The requestUri property displays as expected.

```
+request: ParameterBag {#50 ▼
    #parameters: array:1 [▼
      "test" => "true"
    ]
  }
```
`#requestUri: "/?test=true"`
  
```
Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware(['auth', 'auth.admin'])->group(function () {

    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

    Route::prefix('users')->group(function() {
        Route::get('', 'UserController@index')->name('user');
        Route::get('/{id}/view', 'UserController@view')->name('user.view');
        Route::get('/edit/{id}', 'UserController@edit')->name('user.edit');
        Route::get('/delete/{id}', 'UserController@delete')->name('user.delete');
        Route::post('/update', 'UserController@update')->name('user.update');
    });

}
```

When visiting any of the above URIs for example `http://localhost/admin/users` GET params are not being passed to the request object. However, the requestUri property is showing correctly with the params but the request object for both the request and query parameter arrays is empty.

```
+request: ParameterBag {#50 ▼
    #parameters: []
  }
```
`#requestUri: "/admin/users?test=true"`

**Comment by staudenmeir** [comment]
I can't reproduce that. Where is the `Request` object coming from?

**Comment by twigg** [comment]
@staudenmeir I'm simply dd() in the controller like so:

```
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use App\Role;
use App\Group;

class UserController extends Controller
{
    public function index(Request $request)
    {
        dd($request);

        $users = User::with('roles', 'group')->paginate(1);

        return view('admin.user.index')->with(['users' => $users]);
    }
```

**Comment by driesvints** [comment]
I can't reproduce this either. This works for me. Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by twigg** [comment]
@driesvints I have tried both stackoverflow and laracasts and no result. Further looking into this, it works using Laravels built-in server but doesn't when using Ngnix and PHP-FPM. The issue isn't with Laravel.

**Comment by mfn** [comment]
Please post your nginx config then, the part regarding the fcgi configuration

**Comment by staudenmeir** [comment]
Can you test it with Homestead?
