### ISSUE TITLE
how to use session with login for new database connection page

### ISSUE THREAD

**Issue by sunfarmahulla** [laravel/framework#27493]
public function Testlogin(Request $request) {

    	 $username =$request->Input('name_test');
         $pass=$request->Input('id_pass');
         $request->session()->put('user',$request->Input('name_test'));

        config(['database.connections.onthefly' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port'=> env('DB_PORT', '3306'),
            'database'  =>$username,
            'username' => env('DB_USERNAME', 'root'),
            'password' =>env('DB_PASSWORD', '')
        ]]);

        if(  DB::select('select username, Test_id from test where username=? AND Test_id=? ',[$username,$pass]) ==True){

        DB::connection('onthefly');
          	 return view('Admindash')->with('data',session()->get('user'));
          	
      }else{
      	return Redirect::back()->with('success', 'fail login');

      }
    }

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.

**Comment by sunfarmahulla** [comment]
Thanku for replay.
