### ISSUE TITLE
429: Too Many Requests

### ISSUE THREAD

**Issue by marlboro** [laravel/framework#27512]
Hi, I have been trying for the better part of a week to diagnose why my Laravel 5.7 based API has suddenly started having issues with throttling (429: Too Many Requests).  I have (for years) logged every request via a custom middleware and I don't see nearly enough requests to constitute any throttling.  To confirm this I have run Wireshark on both the affected client and the web server during the affected periods.  This confirmed that maybe 20 requests happened before my service started responding with the 429: Too Many Requests.  I'm lost as to how to proceed with troubleshooting. 

**Environment:**
IIS 10, PHP 7.1.26, Laravel 5.7.25.

**Kernel.php**
```
        'api' => [
            'throttle:120,1',
            'bindings',
             \App\Library\Cobalt\Http\Middleware\LogMiddleware::class,
        ],

```
Thanks in advance.

**Comment by staudenmeir** [comment]
Have you added logging to the `ThrottleRequests` middleware?

**Comment by marlboro** [comment]
No, but that is a great idea for a next step.  I will update when I know more.

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by driesvints** [comment]
Also: please don't ignore the issue template.

**Comment by Helveg** [comment]
@marlboro if you posted your question elsewhere, could you link it? I'm having similar issues.

**Comment by marlboro** [comment]
@Helveg No, but it's a bug or configuration issue with either PHP or Laravel.  Originally this particular API was only called by one device and there were no issues.  We added a second device and suddenly the 429's started.  I would have expected each device (unique IP's) to get N requests before they got throttled.  That is not the case or I would not be having issues.

I ended up just increasing the throttle value large enough to make it stop issuing 429's.  It's hacky, and I hate it, but I had no other choice.  Post a link if you get help somewhere else.

**Comment by r9software** [comment]
I got the same issue, my throttle was set to 270, and it is still happening, I believe it should be an issue with laravel, because there is no way for me to have 270 calls to my api from one device of testing in 1 minute

**Comment by playerrtwo** [comment]
I'm currently converting my web app UI to an SPA and running into the same issue. I get the error sporadically when I'm sure I'm nowhere near the limit.

**Comment by EvilLooney** [comment]
Just posting this if anyone else was getting the same error.

I was using Memcached as my cache store and after debugging through telnet, I found that it was never expiring my keys. I had to manually restart the service to fix the problem.

Homestead with memcached version 1.5.6.

**Comment by bskimball** [comment]
I'm having this same issue. I'm trying to do chunk file uploading. I'm getting a 429 after 30 seconds, and about 20 requests

**Comment by simonhampel** [comment]
Thanks @EvilLooney - that solved the problem for me.

My app is very low volume (I'm the only person who uses it), so I was surprised at the API rate limiter kicking in. Restarting memcached fixed the issue.

I'm wondering if this is a Laravel issue or a memcached issue?

**Comment by bissolli** [comment]
Did anyone find out the problem? We're facing same issues here.

**Comment by davidkryzaniak** [comment]
Same issue. Laravel 5.7, IIS10, PHP 7.3.

**Comment by Helveg** [comment]
It's a sporadic recurring issue, all or most of us reporting the issue face it in controlled testing environments as well where we're sure to be nowhere near the limit. @driesvints can we get some feedback, troubleshooting tips or a timeline on this?

**Comment by Helveg** [comment]
Also a firefighting tip: you can clear the throttle if it hits your production environment with:

```
php artisan cache:clear
```

**Comment by davidkryzaniak** [comment]
@Helveg Yes, logging can be done on the client. Look in the headers of the response. It should look something like this:

```shell
DK@DK:~$ curl -I -X POST http://localhost/fake/path
HTTP/1.1 400 Bad Request
Date: Tue, 01 Oct 2019 20:29:45 GMT
Server: Apache/2.4.39 (Fedora) OpenSSL/1.1.1b
X-Powered-By: PHP/7.2.19
Cache-Control: no-cache, private
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 59
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json
```

You're looking for `X-RateLimit-Limit` and `X-RateLimit-Remaining`

The issue I was having was in the Kernel. Inside of `$middlewareGroups` under api, 'throttle:120,1' was not being respected. As seen in the headers above, it was always set to 60. Here's what I needed to do to fix it:

```php
/* ... */

protected $middlewareGroups = [
    'web' => [
        /* .. */
    ],

    'throttle' => ['throttle:99,1'], //No idea why, but this works!

    'api' => [
        'throttle:5000,1', //These values did not change the throttle limit.
        'bindings',
    ],
];

/* ... */
```

I found this by adding some dump()'s here: https://github.com/laravel/framework/blob/5.7/src/Illuminate/Routing/MiddlewareNameResolver.php#L29

**Comment by apostle51** [comment]
> Ayrıca bir yangın söndürme ucu: üretim ortamınıza çarparsa gazı temizleyebilirsiniz:
> 
> ```
> php artisan cache:clear
> ``` thank's it's working... ;)

**Comment by prabodhana** [comment]
> Also a firefighting tip: you can clear the throttle if it hits your production environment with:
> 
> ```
> php artisan cache:clear
> ```
worked thanks

**Comment by akshayagarwal** [comment]
I had to remove the throttling from the `api` middleware in `app\Http\Kernel.php`. Just delete the following line in `app\Http\Kernel.php`

`'throttle:60,1',`

**Comment by Helveg** [comment]
That's not very good advice: the throttle is there for good reasons. You're now vulnerable to being spammed with requests such as login requests. Never advice to completely disable security measures even if they aren't functioning properly

**Comment by akshayagarwal** [comment]
> That's not very good advice: the throttle is there for good reasons. You're now vulnerable to being spammed with requests such as login requests. Never advice to completely disable security measures even if they aren't functioning properly

I do agree that any good system architecture should incorporate the necessary security measures. However, these measures should be supplemented with a good understanding of the internals. My response was in the context of the specific OP query assuming they know what they are doing, and not a general system architecture advice.

Also, most apps would use the `web` middleware for website functions such as Login. Laravel 6.x does not enforce any throttling for this middleware out-of-the box so it would be vulnerable to spamming, unless the developer knows what they are building and incorporates the necessary guards.

Your thoughts are absolutely valid and I appreciate you providing the helpful perspective here. I just wanted to make sure that people who find the solution helpful would know what they are working with.

Cheers!

**Comment by Isurumayanga97** [comment]
how to increase request limit in laravel.
