### ISSUE TITLE
phpunit db connection refuse with git repo

### ISSUE THREAD

**Issue by Mindexperiment** [laravel/framework#27521]
- Laravel Version: 5.7.25
- PHP Version: 7.2
- Database Driver & Version: MySql 8.0.13

### Description:
I'm having a strage behaviour with an application I'm working on.. I can run cli commands like php artisan migrate:fresh and the database populates well,
 but if I run vendor/bin/phpunit I get pdoexception connection refused

i'm on an aws vpc connecting to the database in a private layer

[laracasts forum topic](https://laracasts.com/discuss/channels/laravel/mysql-connection-problems#reply=492073)

are there any known issue about phpunit env variables?

### Steps To Reproduce:
you can try fork my project at https://github.com/Kaleskop/kaleskop.git but there's ffmpeg dependencies to setup

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
