### ISSUE TITLE
PHP layout example

### ISSUE THREAD

**Issue by jimgwhit** [laravel/framework#27526]
I don't use blade, and the docs really don't cover layout files for php.

Please see this
https://laracasts.com/discuss/channels/laravel/difference-in-section-and-render

I basically use
```
View::make
```
To replace section for php.  But if you would look at that laracast post question and my first answer, it explains all.
Just wondering could something be added to docs for php layout also, even if just a small example.

Thanks, I love laravel, and how flexible it is.

Edit: Please let me know if how I am currently doing it is alright, it seems to work fine.

**Comment by ahinkle** [comment]
`View::make` isn't traditionally used. additionally, it does the exact same thing as `view()` and has plenty of provided documentation: https://laravel.com/docs/5.7/views

This sounds like a place for [laravel/docs](https://github.com/laravel/docs/issues) and not the framework itself.

**Comment by driesvints** [comment]
Please see the answer of @ahinkle
