### ISSUE TITLE
https enforcement does not work anymore after config:cache

### ISSUE THREAD

**Issue by obaydmir** [laravel/framework#27520]
- Laravel Version: 5.7.25
- PHP Version: 7.3.0
- Database Driver & Version: mysql

### Description:
When configuration is cached the https enforcement doesn't generate https-urls anymore.

### Steps To Reproduce:
1. Clear all cached configs by `php artisan config:clear`, `php artisan route:clear` and check folder `bootstrap/cache/` to check if all cached files are removed.
1. Add `$url->forceSchema(''https)` to enforce https. See below for file `app/Providers/AppServiceProvider.php`.
1. Set to production mode with `APP_ENV=production` within `.env`.
1. Set to https url with `APP_URL=https://mywebsite.com` within `.env`.
1. Surf to `https://mywebsite.com` within my browser.
1. Check if links have https and they all do.
1. Cache configs by executing `php artisan config:cache`.
1. Surf to `https://mywebsite.com` within my browser.
1. Check if links still have https, but they don't.

File `app/Providers/AppServiceProvider.php`
```
namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Routing\UrlGenerator;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot(UrlGenerator $url)
    {
        if (env('APP_ENV') === 'production') {
            $url->forceScheme('https');
        }
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }
}
```

**Comment by laurencei** [comment]
`if (env('APP_ENV') === 'production') {`

You cannot use `env()` outside of the config files. You have to use a config variable here.

**Comment by obaydmir** [comment]
@laurencei thanks for taking the time.
