### ISSUE TITLE
BackgroundCommands miss the after-Callbacks

### ISSUE THREAD

**Issue by stevenbuehner** [laravel/framework#27535]
I am not quite shure if this is a bug or intented. But I could not find anything about it in the documentation nore any other issue.

When looking through the code of Event.php I discovered, that there is a different behavior when scheduled commands are run in foreground / background. 

See here: https://github.com/laravel/framework/blob/d4f89f9ca33c70672b0c5eeb0f9523a557841e69/src/Illuminate/Console/Scheduling/Event.php#L203-L227

In Foreground:
1. callBeforeCallbacks
2. run the Commands
3. **callAfterCallbacks**

In Background
1. callBeforeCallbacks
2. run the Commands
3.  --- missing ---

This looks almost too evidently to be a bug, so my question: is this behavior intended and why?

Thanks for clarification :-)

**Comment by driesvints** [comment]
This is because background tasks are long-running and usually have no end time and thus have no way of ever reaching the after callbacks.

**Comment by stevenbuehner** [comment]
Thanks for your quick answer. Understood. Mhh. The documentation states, that background jobs are for "long-running commands" and not for "never ending" commands that have no way of ever reaching the after callbacks. 
https://laravel.com/docs/5.7/scheduling#background-tasks

I.e. I run my backup jobs in the background schedule. It takes about 60-120 minutes but it definitely terminates some time. And therefore it makes sense to run the after callbacks afterwards.

If runInBackground is ONLY intendted to run "never ending" tasks, then you are definetely right and it doesn't make sense to run any after tasks. But then the documentation needs a change. But if the runInBackground is supposed to run "long-running" but still **terminating** commands we should handle the after tasks consistent to the foreground tasks. Don't you think?

**Comment by mfn** [comment]
I agree with @stevenbuehner , I don't quite follow the reasoning in https://github.com/laravel/framework/issues/27535#issuecomment-463605639
> This is because background tasks are long-running and usually have no end time and thus have no way of ever reaching the after callbacks.

🤔

At some point every task finishes and can execute the callback (assuming the process wasn't killed/died unexpectedly). 🤷‍♀️

**Comment by driesvints** [comment]
Looking at this closer, I was mistaken. They do get called, but in a different way. @taylorotwell let me know that they're called by using the `schedule:finish` command: 

https://github.com/laravel/framework/blob/d4f89f9ca33c70672b0c5eeb0f9523a557841e69/src/Illuminate/Console/Scheduling/CommandBuilder.php#L40-L58

Which results in this call:

https://github.com/laravel/framework/blob/d4f89f9ca33c70672b0c5eeb0f9523a557841e69/src/Illuminate/Console/Scheduling/ScheduleFinishCommand.php#L55-L60

**Comment by stevenbuehner** [comment]
Oh I see. Understood. Thank you for the clearence. I was not able to see that either 👍 .
