### ISSUE TITLE
$connection overrides testing connection

### ISSUE THREAD

**Issue by Resin01** [laravel/framework#27534]
- Laravel Version: 5.7.12
- PHP Version: 7.2
- Database Driver & Version: MSsql, mysql and sqlite (memory)

### Description:
When a model has $connection set, testing fails as it overrides the testing connection. One would expect that testing always used its own connection.

### Steps To Reproduce:
1. Setup multiple database connections
2. Add protected $connection = 'other_connection'; to model
3. Run test that involves the model

**Comment by mfn** [comment]
I'm using models with custom `$connection` property and never noticed a problem with them. I'm on 5.7.25

**But** I'm also using a custom database for the tests, which means I do have env variables setup in my `phpunit.xml.dist` for non-main connections in `config/database.php`

**Comment by Resin01** [comment]
That is strange. I have it setup in my phpunit.xml as well `<env name="DB_CONNECTION" value="testing"/>`
And I also have a .env.testing with `DB_CONNECTION=testing`

In my config/database I have 
`'testing' => [
            'driver' => 'sqlite',
            'database' => ':memory:',
            'prefix' => '',
        ],
`

**Comment by driesvints** [comment]
@Resin01 @mfn setting the connection through ENV variables/phpunit.xml will indicate the *base* connection. It's expected that the model will always overwrite the base connection. You'd have to explicitly overwrite the connection again afaik.

**Comment by kitloong** [comment]
@Resin01 Sorry for asking here.
Do you have a recommended approach to overwrite `protected $connection` in model (overwrite to sqlite during unittest)?

**Comment by Resin01** [comment]
I ended up doing this as a fix.
I just made my own model, which all of my models extend.

```
/**
     * Connection to use
     *
     * @var string
     */
    protected $connection = 'mssql';

    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
        if (App::environment('testing')) {
            $this->connection = 'testing';
        }
    }
```
