### ISSUE TITLE
Database Notification type is hardcoded in DatabaseChannel 

### ISSUE THREAD

**Issue by jhm-ciberman** [laravel/framework#27531]
Currently, the DatabaseNotification->type is generated in the DatabseChannel, but it is hardcoded in a non laravel way. 

Illuminate\Notifications\Channels\DatabaseChannel
```php
    /**
     * Build an array payload for the DatabaseNotification Model.
     *
     * @param  mixed  $notifiable
     * @param  \Illuminate\Notifications\Notification  $notification
     * @return array
     */
    protected function buildPayload($notifiable, Notification $notification)
    {
        return [
            'id' => $notification->id,
            'type' => get_class($notification),
            'data' => $this->getData($notifiable, $notification),
            'read_at' => null,
        ];
    }
```
It is difficult to use the notification type since the generated type is something like "App\Notifications\MyNotification", and not something like "my-notification".
The solution is simple. Just implement a method on the base Illuminate\Notifications\Notification class. For example:

```php
    /**
     * Returns the notification type. This value will be used for example in the "database" driver to store the notification type on the database. 
     *
     * @return string
     */
    protected function getType()
    {
        return get_class($this);
    }
```

And then in the DatabaseChannel:

Illuminate\Notifications\Channels\DatabaseChannel
```php
    /**
     * Build an array payload for the DatabaseNotification Model.
     *
     * @param  mixed  $notifiable
     * @param  \Illuminate\Notifications\Notification  $notification
     * @return array
     */
    protected function buildPayload($notifiable, Notification $notification)
    {
        return [
            'id' => $notification->id,
            'type' => $notification_>getType() ?? get_class($notification),
            'data' => $this->getData($notifiable, $notification),
            'read_at' => null,
        ];
    }
```

In this way, the getType() method can be easily owerwitten on any class (It can also be a property).

I can make a PR for this if you like, but I want to discuss it here first.

**Comment by xuanquynh** [comment]
This provides a good way to customize the notification type. But I sill prefer the notification original name.

**Comment by driesvints** [comment]
Heya, thanks for submitting this. This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

**Comment by driesvints** [comment]
FWIW: I also agree that a way to customize this would be nice. You can already overwrite the `buildPayload` method though.

**Comment by jhm-ciberman** [comment]
@driesvints Sorry for the late response. Sadly you can't overwrite the `buildPayload` method because is on the `DatabaseChannel` class, not in the `Notification` class. 

I will post this on laravel/ideas. Thanks.
