### ISSUE TITLE
Loading models by relations is way slower than loading using DB facade

### ISSUE THREAD

**Issue by wisammechano** [laravel/framework#27536]
- Laravel Version: 5.6
- PHP Version: 7.2.7 fpm
- Database Driver & Version: mysql (AWS Aurora), 5.7.12 

### Description:
I am loading some 1500 records using the relation with extra where clauses, and I noticed that the app is running really slow. I changed that line to load using DB::table().. with same clauses, and the time difference is gigantic. from 13k ms to 60 ms. same records. The table contains less than 2M records.

### Steps To Reproduce:
Slow Query:
`$answers = $assignment->answers()
            ->whereNull("score")
            ->orWhere("score", ">", 0.5)
            ->having("user_id", $this->user->id)
            ->get();`
query:
`select * from answers where (answers.assignment_id = ? and answers.assignment_id is not null and score is null or score > ?) and answers.deleted_at is null having user_id = ?`
time:
13645.93

Alternative:
`$answers = DB::table('answers')
            ->where('assignment_id', $assignment->id)
            ->whereNull('deleted_at')
            ->where(function ($q) {
                $q->whereNull('score')
                    ->orWhere('score', '>', 0.5);
            })->having('user_id', $this->user->id)
            ->get();`
query:
`select * from answers where assignment_id = ? and deleted_at is null and (score is null or score > ?) having user_id = ?`
time:
61.61

NOTE: It seems that the 2 queries are slightly different in the `score` where clauses but both returned the same number of items. Am I doing something wrong in the first query?

NOTE 2: From other experiences, the app seem to run out of memory when it returns a model instance for each record when the records are more than 10k in comparison to stdObject for the same count and object. Time difference was noticed as well.

**Comment by driesvints** [comment]
Heya, unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.
