### ISSUE TITLE
Block url after hitting same URL with same IP address in API (return 404)

### ISSUE THREAD

**Issue by kkjhamb01** [laravel/framework#27538]
When a user hitting same API continuously 4-5 time then laravel redirect on 404 error page. How to disable ThrottleRequest and throttle middleware to allow user hit continously same api.

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
