### ISSUE TITLE
mix() does not respect "asset_url" defined in config

### ISSUE THREAD

**Issue by TheBigK** [laravel/framework#27547]
- Laravel Version: 5.7.26
- PHP Version:  7.3.1
- Database Driver & Version: MariaDB 10.3.12

### Description:
The `asset_url` defined in `app/config.php` is not respected by the `mix()` function when used in blade template. The function looks at loading assets locally instead of looking at the asset_url defined. I found this troubling when the code runs in the production environment where cache bursting is defined. 

It'd be nice if mix() takes care of the asset_url on its own so that we do not have to rely on a new helper.

**Comment by driesvints** [comment]
Can you please show how you've defined the root?

**Comment by driesvints** [comment]
And how you're using the helper.

**Comment by TheBigK** [comment]
@driesvints - Here's how I've defined my asset root -

in app/config.php -

```
'asset_url' =>  (env('APP_ENV') == 'production') ? 'https://cdn.mydomain.com/assets' : 'https://local.dev',
```


I tried creating a helper like this; but didn't work. I could not debug it for the scarcity of time -

```
mix( config('app.asset_url') . '/css/app.min.css' );
```

**Comment by driesvints** [comment]
Ah, I see. It's not meant to be used like that. The `asset_url` option only works with the `asset` & `secure_asset` helpers.

**Comment by driesvints** [comment]
I'll send in a PR to the docs to clarify this.

**Comment by TheBigK** [comment]
@driesvints - Thank you for the reply. Could you clarify a bit. I'm using `mix()` in blade as follows -

```
<link href="{{mix('css/custom.min.css')}}" rel="stylesheet" type="text/css">
```

This picks up the asset from `/public` directory.  Wouldn't it be nice if we could make use of the Cache Bursting option provided by `mix()` with `asset_url`? Is there any way out?

**Comment by driesvints** [comment]
Like I said: the option only works with the `asset` helper, not the mix helper. You either use one or the other.

**Comment by TheBigK** [comment]
Thanks. Maybe `mix()` could be updated to work with it? Should I make a feature request?

**Comment by driesvints** [comment]
It's best to discuss feature requests in the laravel/ideas repo.
