### ISSUE TITLE
Authentication events don't fire using guard api with jwt

### ISSUE THREAD

**Issue by jeangomes** [laravel/framework#27546]
- Laravel Version: 5.6
- PHP Version: 7.2
- Database Driver & Version: MySql 5.7

I'm using https://laravel.com/docs/5.6/authentication#events especially the Attempting. However, when I use auth()->guard('api')->attempt($credentials) the event is not dispatched. If I use guard web the event runs. What happens, it is normal?

**Comment by driesvints** [comment]
Heya, unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.
