### ISSUE TITLE
I am getting problem on hash check using nodejs, Is there any way to check laravel generated hashed password on nodejs ?

### ISSUE THREAD

**Issue by rabin999** [laravel/framework#27542]
bcrypt.compare(req.params.password, '$2y$10$2jUm9xnjPTMyfICdtPbG8.mFWsy1GeFssHJFS3CDs7JsdQHeAfZkq', function(err, result) {
        console.log(result);
        if(result) {
            res.send('password matched');
        } else{
            res.end("doesn't match");
        }
    });

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
