### ISSUE TITLE
[5.7] Model::firstOrCreate Integrity constraint violation

### ISSUE THREAD

**Issue by SjorsO** [laravel/framework#27553]
- Laravel Version: 5.7.26
- PHP Version: 7.1.15
- Database Driver & Version: **sqlite 3.11**

### Description:
When using an sqlite database, `Model::firstOrCreate` can't find an existing model and tries to create another one. This happens when it searches for a date attribute that is in the `$casts` array.

The example code below fails when using an Sqlite database, but works correctly using a Mysql database.

### Steps To Reproduce:
Migration:
```php
Schema::create('example_models', function (Blueprint $table) {
    $table->increments('id');
    $table->date('date')->unique();
    $table->timestamps();
});
```

Model:
```php
class ExampleModel extends Model
{
    protected $guarded = [];

    protected $casts = [
        // if you comment out the cast it works correctly
        'date' => 'date',
    ];
}
```

then call the method twice:
```php
ExampleModel::firstOrCreate(['date' => now()->format('Y-m-d')]);

ExampleModel::firstOrCreate(['date' => now()->format('Y-m-d')]);
```

Will throw a `SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed` exception, because the second `firstOrCreate` somehow can't find the model and tries to create another one.

**Comment by staudenmeir** [comment]
SQLite has no dedicated column type for dates, it just stores the values as text:
- Without `date` cast: `2019-02-16`
- With `date` cast: `2019-02-16 00:00:00`

So the latter case doesn't work because the second `firstOrCreate()` can't find the existing record when querying `where date='2019-02-16'`.

This works on MySQL and SQLite:

```php
ExampleModel::firstOrCreate(['date' => now()->startOfDay()]);

ExampleModel::firstOrCreate(['date' => now()->startOfDay()]);
````

**Comment by driesvints** [comment]
Please the answer by @staudenmeir
