### ISSUE TITLE
[5.7] MSSQL database - renaming column causes mssql constraint issue

### ISSUE THREAD

**Issue by joelwmale** [laravel/framework#27563]
- Laravel Version: v5.7.22
- PHP Version: v7.2.15
- Database Driver & Version: Sqlsrv (Unknown Version)

### Description:

When trying to rename a column in a laravel migration, sqlsrv throws an error.

```
$table->renameColumn('verified', 'approved')->change();
```

results in:

```
Migrating: 2018_12_14_121213_rename_verified_to_approved_on_users_table
In Connection.php line 664:
                                                                               
  SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]'DF_  
  1483A5E9_F45FF19' is not a constraint. (SQL: ALTER TABLE users DROP CONSTRA  
  INT DF_1483A5E9_F45FF19)  

In PDOStatement.php line 119:
                                                                               
  SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]'DF_  
  1483A5E9_F45FF19' is not a constraint.                                       
                                                                               
In PDOStatement.php line 117:
                                                                               
  SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]'DF_  
  1483A5E9_F45FF19' is not a constraint.   
```

### Steps To Reproduce:

* Create a migration to create a database/column in an mssql database.
* Create a migration to rename the column.

**Comment by staudenmeir** [comment]
Please add actual migrations. I can't reproduce this with a simple example.

**Comment by joelwmale** [comment]
Initial migration:

```
<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class AddApprovedToUsersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('users', function (Blueprint $table) {
            $table->boolean('approved')->nullable()->after('id');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('users', function (Blueprint $table) {
            $table->dropColumn('approved');
        });
    }
}
```

Column rename migration:

```
<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

use App\User;

class RenameVerifiedToApprovedOnUsersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('users', function (Blueprint $table) {
            $table->renameColumn('verified', 'approved')->change();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('users', function (Blueprint $table) {
            $table->renameColumn('approved', 'verified')->change();
        });

        Schema::table('users', function (Blueprint $table) {
            $table->boolean('verified')->default(false)->change();
        });
    }
}
```

**Comment by staudenmeir** [comment]
Please add the `Schema::create()` migration.

**Comment by joelwmale** [comment]
Sorry, didn't see how that would be useful since it is just an ordinary create migration:

```
<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateUsersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            $table->uuid('id');
            $table->string('email')->unique();
            $table->string('password');

            $table->string('first_name');
            $table->string('last_name')->nullable();

            $table->boolean('verified')->default(false);
            $table->boolean('admin')->default(false);

            $table->timestamps();
            $table->softDeletes();

            $table->primary('id');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('users');
    }
}
```

**Comment by staudenmeir** [comment]
This doesn't make sense, there already is an `approved` column:

```php
$table->boolean('approved')->nullable()->after('id');
$table->renameColumn('verified', 'approved')->change();
```

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by joelwmale** [comment]
Sorry - I had a hectic day. I actually pasted the wrong migration by accident. This is the original create users table for this project:

```
<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateUsersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            $table->uuid('id');
            $table->string('email')->unique();
            $table->string('password');

            $table->string('first_name');
            $table->string('last_name')->nullable();

            $table->boolean('verified')->default(false);
            $table->boolean('admin')->default(false);

            $table->timestamps();
            $table->softDeletes();

            $table->primary('id');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('users');
    }
}
```

So just to clarify: we created the users table with with the verified column (as above), and then created the migration:

```
<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

use Credibot\Models\User;

class RenameVerifiedToApprovedOnUsersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('users', function (Blueprint $table) {
            $table->renameColumn('verified', 'approved')->change();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('users', function (Blueprint $table) {
            $table->renameColumn('approved', 'verified')->change();
        });

        Schema::table('users', function (Blueprint $table) {
            $table->boolean('verified')->default(false)->change();
        });
    }
}
```

I believe this is a bug as the framework is responsible for what it sends to the database, not the user. It could perhaps be an issue with the azure mssql configuration, which could be preventing laravel from renaming the column?

**Comment by driesvints** [comment]
I don't have the means to test on Azure myself so I think it's best you try to ask this to someone who can. Not sure if @staudenmeir is willing to have another look?

**Comment by joelwmale** [comment]
I would appreciate it if @staudenmeir is willing to have another look. I had an urgent production issue as I was trying to fix my mistake and then before I knew it the day was over.

Our Azure setup is stock standard with no real configuration changes. If this is indeed a configuration issue and not an issue with core Laravel, then perhaps this would be a good opportunity to expand on the database section of the documentation to provide some instructions into how to properly set up SQL server for Laravel.

Thanks guys.

**Comment by staudenmeir** [comment]
I can reproduce it. It's somehow caused by `->default(false)`.

Without a default value, a single query is executed:

```sql
sp_RENAME 'a.verified', 'approved', 'COLUMN'
```

If the column has a default value, there are suddenly three queries:

```sql
sp_RENAME 'a.verified', 'approved', 'COLUMN'
ALTER TABLE a DROP CONSTRAINT DF_E8B7BE43_F45FF19
ALTER TABLE a ADD CONSTRAINT DF_E8B7BE43_7C57D81D DEFAULT '' FOR approved
```

The queries are generated by the `doctrine/dbal` package. I'll take a look at it. 

In the meantime, you can use a raw statement:

```php
DB::statement("sp_RENAME 'a.verified', 'approved', 'COLUMN'");
```

**Comment by joelwmale** [comment]
Great. Thanks for confirming this is indeed a bug @staudenmeir. Are we able to re-open this issue?

I will use your suggested work around in the mean time.

**Comment by staudenmeir** [comment]
It's not really a Laravel bug and even the `doctrine/dbal` maintainers might argue that it's not their responsibility.

What I've found so far: (Very) old versions of SQL Server only support default values with a `constraint`. `doctrine/dbal` uses this legacy technique when generating a `CREATE TABLE` query:

```sql
CREATE TABLE users (verified INT NOT NULL)
ALTER TABLE users ADD CONSTRAINT DF_1483A5E9_F45FF19 DEFAULT 0 FOR verified
```

Laravel however, generates the `CREATE TABLE` query itself and uses the "normal" syntax:

```sql
create table "users" ("verified" nvarchar(255) not null default 0)
```

So your migrations use Laravel's `CREATE TABLE` query and `doctrine/dbal`'s query for renaming the column. The latter query expects a constraint named `DF_1483A5E9_F45FF19` to exist, thus causing the error.

Not sure how we could solve this. The `doctrine/dbal` maintainers could argue that it's Laravel's fault for not using their `CREATE TABLE` query.

**Comment by joelwmale** [comment]
Hm, based on your comment it would seem that it is indeed a Laravel issue (not bug)? If Laravel is using its own `CREATE TABLE` syntax, and not `doctrine/dbal`'s then surely the fix here is to use the syntax provided by `doctrine/dbal`? 

Or alternatively use Laravel syntax throughout the entire connection and not just a mixture of `Laravel` and `doctrine/dbal`?

The workaround (at the moment) for this project is to remove this migration and do it manually which defaults the purpose of migrations. Is there perhaps a way to force Laravel to use `doctrine/dbal`, or have Laravel use its own syntax?

**Comment by staudenmeir** [comment]
I see your point, but neither of these things will happen. There are good reasons for the current state:

- Creating tables is a major feature. It's worth the time and effort for Laravel to maintain its own implementation. You have full control over it and don't depend on an external package.
- In comparison, altering tables is a minor feature. The implementation is *very* complex, so it makes sense to delegate that to an optional package.

This combination of different implementations can cause issues like yours, but overall, it works quite well.

**Comment by joelwmale** [comment]
I understand your point as well - and do agree that being able to change a column is a minor feature compared to creating a table.

Thanks for looking into the issue. I guess this is just a bug that we will need to work around.

**Comment by jlsjonas** [comment]
[**@staudenmeir**](https://github.com/staudenmeir) commented on [Feb 18, 2019, 10:46 PM GMT+1](https://github.com/laravel/framework/issues/27563#issuecomment-464891821 "2019-02-18T21:46:52Z - Replied by Github Reply Comments"):
> What I've found so far: (Very) old versions of SQL Server only support default values with a `constraint`. `doctrine/dbal` uses this legacy technique when generating a `CREATE TABLE` query:

Encountering the same issue, but for different reasons; implying there's more going on:

### Situation

I'm trying to add a non-nullable column to a table, an easy way (in theory...) to accomplish this is to set a default value for pre-existing records, followed by unsetting the default value (i.e., both actions happen within a migration, it shouldn't be related to the native <> doctrine mix).

### Issue

1) When the 2nd part of the migration (removing default) is ran, it's trying to remove a constraint that doesn't exist (at least, not under that name)

2) When skipping the `->default(null)->change()` part of the migration, testing the rollback causes the same (a constraint exists, but under a different name than what laravel expects)

migration code:
```php
    public function up()
    {
        Schema::table('tablename', function (Blueprint $table) {
            $table->integer('field')->default(2);
        });
        Schema::table('tablename', function (Blueprint $table) {
            //remove default again
            $table->integer('field')->default(null)->change();
        });
    }

    
    public function down()
    {
        Schema::table('tablename', function (Blueprint $table) {
            $table->dropForeign(['field']);
            //never reaches this line
            $table->dropColumn('field');
        });
    }
```

I can't invest too much time in it right now but I'm assuming adding a column (with default number) is also handled natively, while change isn't?

[this SO possibly covers the underlying issue](https://stackoverflow.com/a/39022223/620141)

**Comment by staudenmeir** [comment]
@jlsjonas This is the same issue. In your example, Laravel generates the query that adds the column, while Doctrine generates the query that changes the default value. A single migration can use both implementations.

You'll also have to fall back on raw expressions.

**Comment by jlsjonas** [comment]
The issue with using raw queries is that we're using sqlite for testing,
which would require workarounds. Though indeed viable for now (I opted for
creating nullable, updating all, making not nullable)
