### ISSUE TITLE
swoole speed up laravel

### ISSUE THREAD

**Issue by tracenull** [laravel/framework#27560]
Hello, laravel6 will consider supporting swoole? As we all know, laravel has developed to the present day, performance is a problem that is criticized, and swoole can improve the performance of laravel so that laravel becomes the spring framework in php.

**Comment by staudenmeir** [comment]
Thanks for submitting this. This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.
