### ISSUE TITLE
"NPM install" error Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ahmedshamseldin** [laravel/framework#27562]
- Laravel Version: 5.7.26
- PHP Version: 7.2.10
- Database Driver & Version:

### Description:
This is The Log file of The error 
Full Scenario
command 
- laravel new laravelproject 
- npm install
or 
- yarn install

NPM log result 
```
3255 silly fetchPackageMetaData error for long@git://github.com/dcodeIO/long.js.git#8181a6b50a2a230f0b2a1e4c4093f9b9d19c8b69 Error while executing:
3255 silly fetchPackageMetaData undefined ls-remote -h -t git://github.com/dcodeIO/long.js.git
3255 silly fetchPackageMetaData
3255 silly fetchPackageMetaData
3255 silly fetchPackageMetaData spawn git ENOENT
3256 verbose stack RangeError: Maximum call stack size exceeded
3256 verbose stack     at RegExp.test (<anonymous>)
3256 verbose stack     at isDepOptional (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:405:45)
3256 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:414:9)
3256 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:430:9)
3256 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:430:9)
3256 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:430:9)
3256 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:430:9)
3256 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:430:9)
3256 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:430:9)
3256 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:430:9)
3256 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:430:9)
3256 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:430:9)
3256 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:430:9)
3256 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:430:9)
3256 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:430:9)
3256 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:430:9)
```
it wasnt do this before 
After My friend assist he said that "long@git" need Git installed 
and yeah after installing Git i didnt get any error

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.

**Comment by ahmedshamseldin** [comment]
I dont know is this framework issue or not ?
but i see its a bug 
try to install laravel then try install dependencies by npm or yarn or whatever you install with you will get this error 
i said i solved it by installing git 
but this error is new it wasnt happen before 
may be its wrong to make issue for that 
Thanks in advance

**Comment by mfn** [comment]
@ahmedshamseldin this looks like an error of the npm too _while_ installing the dependencies; there's not much to do here except to try again; it's not a Laravel issue.
