### ISSUE TITLE
Bug when using concat() combinend with push() on a collection

### ISSUE THREAD

**Issue by spjan1** [laravel/framework#27577]
- Laravel Version: 5.7.3
- PHP Version: 7.2.2
- Database Driver & Version:

### Description:
I encountered a bug when using the push() method after I called conact() on a collection. I expected the pushed element to be appended to the concated list. But instead the concated elements were removed and only pushed elements are remaining. 

### Steps To Reproduce on tinker
```
$c = collect();
  => Illuminate\Support\Collection {#2993
            all: [ ],
        }

$c->concat([1,2,3])
  => Illuminate\Support\Collection {#3016
            all: [
                1,
                2,
                3,
            ],
        }

$c->push(4);
  => Illuminate\Support\Collection {#2993
            all: [
                4,
            ],
        }

$c->concat([5,6]);
  => Illuminate\Support\Collection {#3009
            all: [
                4,
                5,
                6,
            ],
        } 

$c->push(7);
  => Illuminate\Support\Collection {#2993
          all: [
                4,
                7,
            ],
        }
```

### Workaround
Put the pushed element into a collection and use concat() to append it to the list.

**Comment by 36864** [comment]
This is not a bug. `concat()` does not modify the calling collection, it simply returns a new collection with the concatenated result, leaving the original collections untouched. This can be inferred from the examples in the documentation.

Maybe the documentation could be made clearer about which methods modify a collection and which simply return a new collection.

**Comment by spjan1** [comment]
@36864 Oh, that explains my misbehaving code, thanks.
