### ISSUE TITLE
SendEmailVerificationNotification not triggered from phpunit

### ISSUE THREAD

**Issue by ericdebleumortier** [laravel/framework#27570]
- Laravel Version: 5.7.25
- PHP Version: 7.2.4
- Database Driver & Version: /

### Description:
 I am doing unit testing of the verification process. So after a user has been registered, I try to test if the mail is well sent. but **the notification is never triggered**. 
This is working in the application but not in phpunit.

### Steps To Reproduce:
In a test, write the following

```
public function test_non_verified_user_receive_email_after_registration()
    {
        Notification::fake();
        $this->registerUser(); //in my case the user returned here is not the last one
        $user = User::orderBy('created_at', 'desc')->first(); //so I do this
        Notification::assertSentTo($user, SendEmailVerificationNotification::class);
    }

    protected function registerUser()
    {
        $user = factory(User::class)->make();

        $this->post(route('register'), [
            'name' => 'IamTheUser',
            'email' => $user->email,
            'password' => 'secret',
            'password_confirmation' => 'secret',
        ])->assertRedirect();

        return User::whereEmail($user->email)->first();
    }
```

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
