### ISSUE TITLE
Illuminate Queue  Fatal error: Uncaught ReflectionException: Class db does not exist

### ISSUE THREAD

**Issue by insinfo** [laravel/framework#27582]
- Laravel Version: 5.2
- PHP Version: 7.2
- Database Driver & Version: postgresql 9.4

### Description:
I'm trying to use the "The Illuminate Queue package" outside of the Laravel Framework, but this is returning the following error:

Fatal error: Uncaught ReflectionException: Class db does not exist in C:\wamp64\www\pmroPadrao\src\BackEnd\vendor\illuminate\container\Container.php:734
Stack trace:
#0 C:\wamp64\www\pmroPadrao\src\BackEnd\vendor\illuminate\container\Container.php(734): ReflectionClass->__construct('db')
#1 C:\wamp64\www\pmroPadrao\src\BackEnd\vendor\illuminate\container\Container.php(629): Illuminate\Container\Container->build('db', Array)
#2 C:\wamp64\www\pmroPadrao\src\BackEnd\vendor\illuminate\container\Container.php(1178): Illuminate\Container\Container->make('db')
#3 C:\wamp64\www\pmroPadrao\src\BackEnd\vendor\illuminate\queue\QueueServiceProvider.php(204): Illuminate\Container\Container->offsetGet('db')
#4 [internal function]: Illuminate\Queue\QueueServiceProvider->Illuminate\Queue\{closure}()
#5 C:\wamp64\www\pmroPadrao\src\BackEnd\vendor\illuminate\queue\QueueManager.php(150): call_user_func(Object(Closure))
#6 C:\wamp64\www\pmroPadrao\src\BackEnd\vendor\illuminate\queue\QueueManager.php(133): Illuminate\Queue\QueueManager->getCo in C:\wamp64\www\pmroPadrao\src\BackEnd\vendor\illuminate\container\Container.php on line 734

### Steps To Reproduce:

```php
require_once '../vendor/autoload.php';
use \Illuminate\Queue\Capsule\Manager as Queue;
$queue = new Queue;
$queue->addConnection(
    [
        'driver' => 'database',
        'host' => '192.168.133.13',
        'queue' => 'default',
        'table' => 'jobs',
        'retry_after' => 90,
        'connections' => [
            'default' => [
                'driver' => 'pgsql',
                'host' => '192.168.133.13',
                'port' => '5432',
                'database' => 'sistemas',
                'username' => 'sisadmin',
                'password' => 's1sadm1n',
                'charset' => 'utf8',
                'prefix' => '',
                'schema' => ['pmro_padrao'],
                'sslmode' => 'prefer',
            ],
        ],
    ]
    , 'default');
$queue->setAsGlobal();
use \Illuminate\Queue\Worker;
$worker = new Worker($queue->getQueueManager(), null, null);
// Run indefinitely
while (true) {
    // Parameters:
    // 'default' - connection name
    // 'default' - queue name
    // delay
    // time before retries
    // max number of tries
    $worker->pop('default', 'default', 0, 3, 1);
}
Queue::push('SendEmail',
    array(
        'email' => 'insinfo2008@gmail.com',
        'justificativa' => 'teste'
    )
);



````

**Comment by driesvints** [comment]
Heya, unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.
