### ISSUE TITLE
[5.7] Laravel database testing with refreshing database and data providers

### ISSUE THREAD

**Issue by Windstep** [laravel/framework#27599]
- Laravel Version: 5.7
- PHP Version: 7.3
- Database Driver & Version: MySQL 5.7

### Description:

We use data provider to give methods some data and expected results. But due to the "right way" if we use dataprovider in laravel it will throw an error, cos it haven't set up application before this step. So we have to include $this->createApplication() in each data provider.

But if we add $this->createApplication() to the class, which already has RefreshDatabase trait assigned to it, we will refresh database on iteration after dataProvider have been called. So we will have no one of this entries in database;

### Steps To Reproduce:

1. Create application
2. Create test like this (might have done some typos, so check it in the ide)

```
<?php

namespace Tests\Feature;

use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;

class TestSomeFeature extends TestCase
{
    use RefreshDatabase;

    /** @dataProvider provideSomething */
    public function testSomething($item, $expected)
    {
        $this->assertEquals($expected, $item);
    }

    public function provideSomething()
    {
       // Reference issue https://laracasts.com/discuss/channels/testing/unable-to-locate-factory-namedafault-in-laravel-dataprovider
       $this->createApplication();
       $user = factory(App\User::class)->create();
       return [
           [$user->toArray(), ['id' => 1, 'name' => $user->name, 'email' => $user->email]],
       ];
    }
}
```

**Comment by Windstep** [comment]
In my case, example is more complicated and includes some nested relationships.
In data provider methods are created user and roles, roles are assigned to user and in test method they are not appeared at all.

**Comment by mfn** [comment]
IMHO it's a limitation of how dataproviders are implemented in phpunit and not so much a Laravel issue, see also https://phpunit.readthedocs.io/en/8.0/writing-tests-for-phpunit.html
> All data providers are executed before both the call to the setUpBeforeClass() static method and the first call to the setUp() method. Because of that you can’t access any variables you create there from within a data provider. This is required in order for PHPUnit to be able to compute the total number of tests.

Because they're ran before the `setUp` phase, the application is not there yet. So everything else is just a hack to workaround this PHPUnit behaviour.

I _think_ the TL;DR here for you can be:
- don't use dataProvider for these cases
- only return discrete values from the dataProvider and _build_ the relation yourself in the tests, driven by the input

I can confirm the latter works quite well, have been doing this very often.

**Comment by Windstep** [comment]
@mfn, thank you for your reply. If there are nothing to do, except of stopping to use dataProviders in this case, and framework is not related to that, issue can be closed.

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
