### ISSUE TITLE
User Deprecated: Passing a command as string when creating a "Symfony\Component\Process\Process" instance is deprecated

### ISSUE THREAD

**Issue by anderson-comvex** [laravel/framework#27602]
- Laravel Version: 5.7.*
- PHP Version: 7.3.2
- Database Driver & Version: MySQL 8

### Description:

ErrorException
User Deprecated: Passing a command as string when creating a "Symfony\Component\Process\Process" instance is deprecated since Symfony 4.2, pass it as an array of its arguments instead, or use the "Process::fromShellCommandline()" constructor if you need features provided by the shell.

function_name | Callable Illuminate\Console\Scheduling\ScheduleRunCommand::handle []
-- | --

### Steps To Reproduce:

Execute any schedule jobs using the version provided above

**Comment by AidasK** [comment]
Add this line to composer.json for temp fix "symfony/process": "~4.1.0"

**Comment by driesvints** [comment]
Thanks for making us aware. I'll look into this as this indeed seems to affect quite a bit of the console part.

**Comment by driesvints** [comment]
It didn't seem to affect too much. Sent in a PR: https://github.com/laravel/framework/pull/27610

**Comment by daylaborers** [comment]
Is this also fixed in Laravel 5.7?

**Comment by CupOfTea696** [comment]
Just created a PR to apply this fix in 5.7 (#27688).

**Comment by driesvints** [comment]
We'll have to wait and see if this can also be fixed in 5.7 but it's fixed for 5.8 already.
