### ISSUE TITLE
Internet Explorer 11 issue with caching

### ISSUE THREAD

**Issue by yonihahasis** [laravel/framework#27603]
- Laravel Version: 5.5
- PHP Version: 7.0.33
- Database Driver & Version: mysql 

### Description:
I had a button on my system and the idea of the button is to update a field on my database and redirect to another page with a session message. The button should change color and the message should be displayed. But when it redirects, there is no session message or the color of the button doesn't change at all. After navigating to another page, the button color changes and the message appears our of no where.

The feature works on most browsers but I found out that it had an issue on internet explorer 11. I didn't try it out on another IE versions but Edge works too. I checked that if the field wasn't updated but it does update. 

I found out that the problem is caching issue so I add this to the top of my controller function and it seems to be fixing the issue well.

header("Cache-Control: no-cache, no-store, must-revalidate"); // HTTP 1.1.
header("Pragma: no-cache"); // HTTP 1.0.
header("Expires: 0"); // Proxies.

Is there a way to go about it that doesn't require me to add these lines?

### Steps To Reproduce:
Controller code
`Auth::user()->update([
"status" => 1
]);

$request->session()->flash('message.level', 'success');
$request->session()->flash('message.content', 'Your status has been confirmed.');

return redirect("/status/me");`

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
