### ISSUE TITLE
Class 'Pheanstalk\PheanstalkInterface' not found

### ISSUE THREAD

**Issue by AymanElarian** [laravel/framework#27605]
- Laravel Version: 5.7.25
- PHP Version:7.2
- Database Driver & Version:

### Description:
with php artisan queue:listen command i receive 
```
   Symfony\Component\Debug\Exception\FatalThrowableError  : Class 'Pheanstalk\PheanstalkInterface' not found

  at /Users/aymanelarian/xxx/xxxxxx/vendor/laravel/framework/src/Illuminate/Queue/Connectors/BeanstalkdConnector.php:35
    31|     protected function pheanstalk(array $config)
    32|     {
    33|         return new Pheanstalk(
    34|             $config['host'],
  > 35|             $config['port'] ?? PheanstalkInterface::DEFAULT_PORT,
    36|             $config['timeout'] ?? Connection::DEFAULT_CONNECT_TIMEOUT,
    37|             $config['persistent'] ?? false
    38|         );
    39|     }

  Exception trace:

  1   Illuminate\Queue\Connectors\BeanstalkdConnector::pheanstalk(["beanstalkd", "localhost", "default"])
      /Users/aymanelarian/xxx/xxxxxx/vendor/laravel/framework/src/Illuminate/Queue/Connectors/BeanstalkdConnector.php:22

  2   Illuminate\Queue\Connectors\BeanstalkdConnector::connect(["beanstalkd", "localhost", "default"])
      /Users/aymanelarian/xxx/xxxxxx/vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php:157
```

### Steps To Reproduce:
run cmd after composer require "pda/pheanstalk" and config queue setting  then listen to beanstalkd Queue it fail

**Comment by AymanElarian** [comment]
it seem that namespace changed to Pheanstalk\Contract\PheanstalkInterface; and  that mean laravel not optimised with the latest Pheanstalk

**Comment by crynobone** [comment]
Pheanstalk 4 support will be introduced in 5.8, however it could be possible to add support to 5.7 while still maintaining 3.x support if @taylorotwell okay with that.

BTW I been using pheanstalk 4 on Laravel 5.7 for a week now and running smoothly.

**Comment by driesvints** [comment]
5.7 will go into security mode only on the 4th of March but we could indeed add this in the meantime so people on 5.7 can still use it. I'll ping taylor about it.

**Comment by driesvints** [comment]
@crynobone if you can send something in for 5.7 which doesn't breaks anything you can do so :)

**Comment by driesvints** [comment]
Gonna close this then since it's not really a bug or anything.

**Comment by crynobone** [comment]
@driesvints See #27622
