### ISSUE TITLE
Maximum file upload stays even after editing php.ini

### ISSUE THREAD

**Issue by alakhrasSandy** [laravel/framework#27606]
- Laravel Version: 5.4
- PHP Version: 7.2
- Database Driver & Version: Running Apache2 on ubuntu

### Description:
So i am trying to upload multiple files in one batch in my website and am getting the maximum payload 
reached Error"413 Payload Too Large"
i tested with 20 files each around 2.5M

I Read online that this is related to php settings in the php.ini file located on my server.

I have changed (enlarged) the values of upload_max_filesize =10M,post_max_size =310M ,max_file_uploads=30 ,memory_limit=-1 (although -1 is infinite i also tried setting it to large values to test):
i 
the php.ini file in all of :
etc/php/7.2/apache2/php.ini
etc/php/7.2/cli/php.ini
etc/php/7.2/fpm/php.ini

Restarted Apache services
Restarted fpm services
and the error still persists.
I am thinking there might be a setting related to Laravel that i also need to update??

### Steps To Reproduce:
upload multiple files with big size values

**Comment by driesvints** [comment]
Heya, unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.
