### ISSUE TITLE
Email Verification

### ISSUE THREAD

**Issue by MONAROL** [laravel/framework#27604]
With new integrated functionality of email Verification, users have email_verified_at field.
When you registered and not confirmed account with link in email, you can restore your account.
But when you restore account, your email not sets verified, if it not verified. I think it must be default behavior. Because if we restored account by email, it indicate we have access to this email address.

**Comment by MONAROL** [comment]
Solving with just a few lines of code in ResetsPasswords->resetPassword trait

`if($user instanceof MustVerifyEmail) {`
            `if(!$user->hasVerifiedEmail())`
                `$user->markEmailAsVerified();`
        `}`

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
