### ISSUE TITLE
ErrorException (E_ERROR) Undefined variable: id (View: C:\xampp\htdocs\myblog\meroblog\resources\views\blogs\show.blade.php)

### ISSUE THREAD

**Issue by dhanpulami** [laravel/framework#27607]
ErrorException (E_ERROR)
Missing required parameters for [Route: edit_blog_path] [URI: blogs/{id}/edit]. (View: C:\xampp\htdocs\myblog\meroblog\resources\views\blogs\show.blade.php)
![controller](https://user-images.githubusercontent.com/46792053/53171291-73b00880-360a-11e9-97f0-c328e475974e.jpg)
![edit blade php](https://user-images.githubusercontent.com/46792053/53171292-74489f00-360a-11e9-9860-de45b45ec259.jpg)
![route file](https://user-images.githubusercontent.com/46792053/53171293-74489f00-360a-11e9-889b-f4f157334fda.jpg)
![show blade php](https://user-images.githubusercontent.com/46792053/53171294-74489f00-360a-11e9-83f3-417e146dd034.jpg)

**Comment by dhanpulami** [comment]
My proble is 
ErrorException (E_ERROR)
Missing required parameters for [Route: edit_blog_path] [URI: blogs/{id}/edit]. (View: C:\xampp\htdocs\myblog\meroblog\resources\views\blogs\show.blade.php)****

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by Bipeen123Kumar** [comment]
ErrorException (E_ERROR)
Undefined variable: users (View: C:\xampp\htdocs\aptron\resources\views\insight.blade.php)
