### ISSUE TITLE
Using database in Schedule

### ISSUE THREAD

**Issue by webacers** [laravel/framework#27608]
Hi, 
I wanted to create dynamic scheduling jobs so I have used model in Kernel.php like below 
`protected function schedule(Schedule $schedule) {$tasks = \App\Model\Task::where('enabled', true)->get();}`
It works on local But when deploying to production it throws following error. 

`>> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In Connection.php line 664:
                                                                          
  could not find driver (SQL: select * from `tasks` where `enabled` = 1)  `

If I remove the model query from kernel.php and define static schedule it works fine as expected. But I need to query database in Schedule to setup it dynamic.

Can any one guide me what is missing in production environment?

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
