### ISSUE TITLE
hasArgument missing from Console documentation

### ISSUE THREAD

**Issue by khalyomede** [laravel/framework#27600]
**Explaination**
The method to check if an argument has been provided by the user, `$this->hasArgument('foo');`, is not documented.

**Reproduce the issue**
Go to the page [https://laravel.com/docs/master/artisan](https://laravel.com/docs/master/artisan).

**Expected result**
To see a tips using this method to check if this argument has been provided by the user. It is in fact useful for optional arguments, taking a different approach on the code wether the argument is provided or not.

**Comment by mfn** [comment]
Please see https://github.com/laravel/docs

**Comment by laurencei** [comment]
As @mfn said - please open an issue on the docs repo, or better yet, create a PR there with this change. Thanks!
