### ISSUE TITLE
Schema::rename() arguments may be incorrect.

### ISSUE THREAD

**Issue by christopherarter** [laravel/framework#27615]
I believe the documentation may have the argument order swapped around.

`Schema::rename($from, $to);`

returns a `PDOException::("SQLSTATE[42S01]: Base table or view already exists` error. But, when calling it this way:

`Schema::rename($to, $from);` works as expected. 

Laravel 5.7.*

**Comment by devcircus** [comment]
The source shows ```Schema::rename($from, $to);```
See [Illuminate\Database\Schema\Builder](https://github.com/laravel/framework/blob/c0ad14fe958affdc98e0041f0ae110deca65c00a/src/Illuminate/Database/Schema/Builder.php#L225)

**Comment by driesvints** [comment]
Please don't ignore the issue template.
