### ISSUE TITLE
bug with  call Redis inside queued  job 

### ISSUE THREAD

**Issue by AymanElarian** [laravel/framework#27611]
* Laravel Version: 5.7.25
* PHP Version:7.2
* Database Driver & Version:

### Description:
if i call a laravel command that connect to redis server for operation using $redis->rawCommand  every thing is working great , but once i move the same code inside a job that i queued   it will not work and get the following errror 
`[2019-02-21 14:06:40] local.ERROR: Class 'Redis' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'Redis' not found `

it will work only if i change driver for the queue to sync ??

any help?

**Comment by driesvints** [comment]
I'll need more info and/or code to debug this further. Please post relevant code like models, jobs, commands, notifications, events, listeners, controller methods, routes, etc. You may use https://paste.laravel.io to post larger snippets or just reply with shorter code snippets. Thanks!

**Comment by AymanElarian** [comment]
Job

```
<?php

namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use \Redis;

class ProDevice implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;
    private $dtf;

    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct(dtf)
    {
        $this->dtf = $dtf;
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        ini_set('memory_limit', '-1');
       $redis = new Redis();
        $redis->connect('127.0.0.1', 8888);
        $data = $redis->rawCommand("INSPECT", "AREA", $this->dtf);
    }
}

```

command inside function handle()

       ` \App\Jobs\ProDevice::dispatch($dtf);`

if i run the following in  command handle , it work  ,or if job executed as sync

```
        ini_set('memory_limit', '-1');
       $redis = new Redis();
        $redis->connect('127.0.0.1', 8888);
        $data = $redis->rawCommand("INSPECT", "AREA", $this->dtf);
```

**Comment by mfn** [comment]
> if i call a laravel command that connect to redis server for operation using $redis->rawCommand every thing is working great , but once i move the same code inside a job that i queued it will not work and get the following errror

Is it possible that you have different PHP environments (web vs. cli) and the latter is missing the redis extension?

**Comment by AymanElarian** [comment]
@mfn both from cli , i don't have any web deploy i use it as cli only , laravel command is cli, and queue too

**Comment by ybaruchel** [comment]
@AymanElarian Are both commands being executed on the same machine?

**Comment by AymanElarian** [comment]
@ybaruchel  yes  , even same job inside queued will work with sync , will not work with database and give me the error , 
only change .env config

**Comment by driesvints** [comment]
Does `composer require ext-redis:"*"` work? Can you run that on every installation where you're using the app?

**Comment by AymanElarian** [comment]
@driesvints  yes its run and also its the same installation

**Comment by driesvints** [comment]
At this point I'd recommend uploading a test app to a Github repo which re-creates the problem for you and posting the difference in settings for the different environment.
