### ISSUE TITLE
[5.7] The Mail::queue() causes an error due to incompatible call to Mailable::queue() method

### ISSUE THREAD

**Issue by axelitus** [laravel/framework#27612]
- Laravel Version: 5.7.27
- PHP Version: 7.3.2
- Database Driver & Version: redis 4.0.9

### Description:
When calling `Mail::queue($mailable, $queue_name))` an error is created due to an incompatible call to `Mailable::queue()` which expects an `\Illuminate\Contracts\Queue\Factory` instead of the Queue name.

On the [`Mailer::queue` method](https://github.com/laravel/framework/blob/c821cbf6f20fca4c50aa9d8fb08f71425afc07b8/src/Illuminate/Mail/Mailer.php#L377) there is no check/conversion from queue string name to an `\Illuminate\Contracts\Queue\Factory` object. So, when the [line `$view->queue()`](https://github.com/laravel/framework/blob/c821cbf6f20fca4c50aa9d8fb08f71425afc07b8/src/Illuminate/Mail/Mailer.php#L383) is reached it is incompatible with the expected method signature.

### Steps To Reproduce:
1. Create a Mailable class (in console: `php artisan make:mail TestMailable`)
2. Call `Mail::queue(new TestMailable, 'my-queue');` from within your code

**Comment by axelitus** [comment]
Doing this:

```
$mailable = (new TestMailable)->onQueue('my-queue');
Mail::queue($mailable);
```

works as expected, as at some point the queue name is used to load an `Illuminate\Queue\QueueManager`, which is used when calling `$view->queue()`

Instead, doing this:

```
Mail::queue(new TestMailable, 'my-queue');
```

fails because of the error described before.

**Comment by axelitus** [comment]
I've followed the code and it seems that `$queue` and `$this->queue` are referencing totally different things.

While ` $this->queue` references the `QueueManager` to use, `$queue` seems to reference the actual queue name to use (which is contained inside the `$view` object). What I did to _fix_ this problem is to change the method code to this:

```
public function queue($view, $queue = null)
    {
        if (! $view instanceof MailableContract) {
            throw new InvalidArgumentException('Only mailables may be queued.');
        }

        if (is_string($queue)) {
            $view->onQueue($queue);
        }

        return $view->queue($this->queue);
    }
```

This replaces the view contained in the mailable to the one being set by the method.

Is this the correct approach?

**Comment by driesvints** [comment]
I think you might indeed be onto a bug. Appreciating a PR if you could whip one up.

**Comment by axelitus** [comment]
Alright, I'll setup a PR and indeed I think this is a bug (I'm guessing the variable naming ended in confusion). I also think this bug reaches beyond this use case, I'm not sure but as I was checking the code I think I saw other places with the same issues. I'll try to get them all on the PR if they exist.

**Comment by axelitus** [comment]
I've pushed the PR. I reviewed the code and I can gladly say that I did not find any other issues relating to this matter.
