### ISSUE TITLE
Required parameters and method parameter

### ISSUE THREAD

**Issue by dongm2ez** [laravel/framework#27619]
```php
public function item(Request $request, int $id)
```
This is my Controller method

```php
 Route::get('item/{id}/', 'ItemController@item')
```

This is my Route config

If my id parameter is like string， farmework throw ：

Symfony\Component\Debug\Exception\FatalThrowableError
must be of the type integer, string given

method's parameter already regular type，Why even in route file Regular Expression Constraints？

maybe framework read method parameter type dynamic config Required Parameters

**Comment by staudenmeir** [comment]
I see that you have already created an issue in the `laravel/ideas` repository.

Please close this issue here and only use the issue tracker to report bugs with the framework.
