### ISSUE TITLE
Maintain Users Password History

### ISSUE THREAD

**Issue by S-Arif** [laravel/framework#27625]
In general Laravel provides elegant Auth services in just a line of code to develop login registration and password reset options, how ever when i used to give password reset option to my client i usually have to make changes some builtin functionality for resetting password for check existing password and if it matches with old one i through an error that you should not use your old password and if it does not match then i hold it's old password in another table called users_passwords_backup and never allow user to change to any of the existing password.

I think Laravel community should implement this feature in upcoming new version maybe in Laravel 5.8

Thanks

**Comment by staudenmeir** [comment]
Thanks for submitting this. This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that, you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

**Comment by S-Arif** [comment]
Thanks for your feedback. will post there.
