### ISSUE TITLE
Cache::has('key') response different from documentation

### ISSUE THREAD

**Issue by fitztrev** [laravel/framework#27630]
- Laravel Version: 5.7.27
- PHP Version: 7.2.15

### Description:

`Cache::has('key')` returns `true` when its value is `false`, differing from the documentation:

<img width="640" alt="screen shot 2019-02-22 at 11 40 20 am" src="https://user-images.githubusercontent.com/271432/53256775-ae5f8280-3696-11e9-8a71-829c805503e7.png">

### Steps To Reproduce:

Copy + paste this code to a route, command, or test:

```php
Cache::forever('foo_string', 'string');
Cache::forever('foo_0', 0);
Cache::forever('foo_1', 1);
Cache::forever('foo_true', true);
Cache::forever('foo_empty', '');

Cache::forever('foo_null', null);
Cache::forever('foo_false', false);

dd(
    'These should be true:',
        Cache::has('foo_string'),
        Cache::has('foo_0'),
        Cache::has('foo_1'),
        Cache::has('foo_true'),
        Cache::has('foo_empty'),

    'These should be false:',
        Cache::has('foo_null'),
        Cache::has('foo_false')  // <-- issue
);
```

I've tried the above with these cache drivers: `file`, `redis`, `memcached`, `array`. Same result with each.

**Comment by driesvints** [comment]
You're correct. This indeed isn't the behavior now. However, the current behavior is correct as false is a perfect value to have in the cache. In this case, the docs are incorrect. I'll send in a PR to the docs to fix this and a PR to framework to test for this behavior.

More info on valid data types here: https://www.php-fig.org/psr/psr-16/#14-data

Thanks for reporting.
