### ISSUE TITLE
Auth::basic() and Auth::onceBasic() throw exception instead of returning Response

### ISSUE THREAD

**Issue by jansennerd10** [laravel/framework#27633]
- Laravel Version: 5.5+
- PHP Version: N/A
- Database Driver & Version: N/A

### Description:
In Laravel 5.4 and below, `Auth::basic()` and `Auth::onceBasic()` returned `null` if the user was authenticated and returned a `Response` if they were not.

In Laravel 5.5, this behavior was changed to throw an `UnauthorizedHTTPException`. For the most part this gives the same result of a 401 response being sent to the browser, but it breaks code like this:

```php
if( Auth::basic() !== null )
{
    // return a custom response or do something else
}
```

The [current documentation](https://laravel.com/docs/5.7/authentication#stateless-http-basic-authentication) still implies that these methods will return a `Response` if authentication fails: "If no response is returned by the `onceBasic` method, the request may be passed further into the application".

Additionally, no mention is made of this breaking change in the upgrade notes for Laravel 5.5.

I'm happy to submit a PR, but I'm posting here to find out whether it should be a PR to revert the change in the framework or one to update the documentation.

**Comment by laurencei** [comment]
> I'm happy to submit a PR, but I'm posting here to find out whether it should be a PR to revert the change in the framework or one to update the documentation.

Given that 5.5 has been out for more than a year, and both 5.6 and 5.7 are stable, then there will be no reverting the code.

Your best option he is submit a PR to the docs to clarify the new behaviour.
