### ISSUE TITLE
 QueryException could not find driver (SQL: select * from `blogs`) and Swift_TransportException Connection could not be established with host smtp.gmail.com [Connection refused #111]

### ISSUE THREAD

**Issue by dhanpulami** [laravel/framework#27634]
In localhost my project work but while I deploy it in live server I got this problem

![contace](https://user-images.githubusercontent.com/46792053/53286734-f23bb000-379a-11e9-9ceb-131d8a304489.png)
![database](https://user-images.githubusercontent.com/46792053/53286735-f23bb000-379a-11e9-980e-393db5f7d514.png)

**Comment by LorenzoSapora** [comment]
What was your issue here? I am hitting a similar issue using mailtrap locally. Didn't seem to have a problem a few weeks ago, but suddenly I'm getting this error when trying to send an email. Wondering if your solution could help me @dhanpulami
