### ISSUE TITLE
dd() not working Laravel 5.4 

### ISSUE THREAD

**Issue by gowthambopathyraj** [laravel/framework#27649]

**Comment by gowthambopathyraj** [comment]
please help me

**Comment by driesvints** [comment]
Heya, unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.
