### ISSUE TITLE
UUID PK not supported in ->morphs migration

### ISSUE THREAD

**Issue by mjraval** [laravel/framework#27659]
- Laravel Version: 5.7.*
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7

### Description:
When using Polymorphic Relationship  and Creating Migration using the `$table->morphs('taggable');` or `$table->nullableMorphs('taggable');` the `id` column is generated as an `UnSigned Big Int`.  This would not be compatible with systems using `UUID` as primary keys. Currently, the only option is to not use the `morphs` but create the fields manually.

Understandable that this is just a helper.

**Comment by antonkomarev** [comment]
This issue better be in https://github.com/laravel/ideas

**Comment by devcircus** [comment]
As you mentioned, this is simply a convenience helper, and is intended for the common use case. For specific implementations that fall outside the norm, just define the columns manually.

**Comment by driesvints** [comment]
Heya, thanks for submitting this. This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.
