### ISSUE TITLE
access to the public folder in laravel

### ISSUE THREAD

**Issue by amirex128** [laravel/framework#27654]
I bought a Laravel script and now I want to edit it. When I put a file like a jquery, I give a 404 error in the laravel public folder. But the files that were already in the public folder of laravel are running without problems, but when I create a file there, I encounter the error.

my laravel project cannot access to public folder in url like : http://basagan.com/js/jquery.js

but default file like : http://basagan.com/js/app.js is fine , work and run without problem

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
