### ISSUE TITLE
Migrations break on drop view as view name is case sensitive [postgres db]

### ISSUE THREAD

**Issue by AymanElarian** [laravel/framework#27667]
* Laravel Version: 5.7.25
* PHP Version:7.2
- Database Driver & Version:

### Description:
Hello,
I have to drop views inside my migration Plan, so i use the following on postgres DB

 `DB::statement("DROP VIEW reportsSummary");`

but i got the following error 
```
Doctrine\DBAL\Driver\PDOException::("SQLSTATE[42P01]: Undefined table: 7 ERROR:  view "reportssummary" does not exist")
PDOException::("SQLSTATE[42P01]: Undefined table: 7 ERROR:  view "reportssummary" does not exist")
```

 i belive that may be statement sql went over strtolower function or some thing like this

**Comment by staudenmeir** [comment]
This happens when the view doesn't exist.

Does `DB::select("select * from reportsSummary");` work?

**Comment by AymanElarian** [comment]
@staudenmeir  view is exist and happen with case sensitive  only , after rename it to lower case it work and drop

**Comment by staudenmeir** [comment]
Does `DB::statement('DROP VIEW "reportsSummary"');` work?

**Comment by staudenmeir** [comment]
How are you creating the view?

**Comment by AymanElarian** [comment]
@staudenmeir visa pgadmin  direct

**Comment by staudenmeir** [comment]
Does pgAdmin show the executed SQL?

**Comment by AymanElarian** [comment]
@staudenmeir problem happen as laravel doing a strtolower for the query and for pgsql its case sensitive

**Comment by staudenmeir** [comment]
Laravel does *not* change the raw query in any way.

Can you provide the SQL that creates the view?

**Comment by AymanElarian** [comment]
try to add any view in postgress with caps like  reportsSummary then drop it by DB::statement("DROP VIEW reportsSummary") , you will catch the problem

**Comment by staudenmeir** [comment]
What's the *actual* SQL that creates the view?

**Comment by AymanElarian** [comment]
i create it from pg admin gui

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by Ali7med** [comment]
still not work
