### ISSUE TITLE
Calling Auth::guard("api")->user() produces multiple identical database queries

### ISSUE THREAD

**Issue by neosounds** [laravel/framework#27668]
- Laravel Version: 5.7.16
- PHP Version: 7.2.12
- Database Driver & Version: MariaDB

If I authenticate a user with the correct API token and call `Auth::guard("api")->user()` multiple times within app lifecycle, it always returns the user from the cache. There is just one database query to fetch a user, which is OK and expected.

If, however, I use the wrong (not empty) token and authentication fails, each subsequent call to `Auth::guard("api")->user()` within application lifecycle produces a separate, identical database query to fetch a user. So if we call it 10 times, we get 10 identical database queries to fetch a user.

It seems that Laravel does not cache "null" user and does not take into account the fact that we already made an attempt to authenticate a user. 

How to fix the issue, please?

**Comment by driesvints** [comment]
This isn't something the framework should be keeping in check because then we would never be able to know when you'd actually want to try to retrieve the user again.

**Comment by neosounds** [comment]
Thank you Dries for the explanation. Well for `Auth::guard("api")->user()` it sounds justified. 

But what about `Auth::guard("api")->check()`? It also produces as much database queries as the number of its calls (in case the API token is wrong and not empty).

For instance, we need to check on whether a user authenticated or not in different places within an application lifecycle (in models, views etc.). In case a wrong (not empty) token is provided, Laravel will make a database query each time `Auth::guard("api")->check()` is called. The same for `Auth::guard("api")->guest()`.

So why not cache the "Auth check" result on the first call? If somewhere in the app we'd need to re-authenticate a user or clear it, we can just clear/update the cache. At least we would not have multiple database queries, which seems not optimized.

**Comment by driesvints** [comment]
Same reason. It's not the framework's task to keep the state of a login in session when no successful authentication has taken place, only when it has.
