### ISSUE TITLE
Symfony\Component\Debug\Exception\FatalThrowableError: Exception 'Symfony\Component\Debug\Exception\FatalThrowableError' with message 'Type error: Argument 1 passed to App\Widgets\Iddaa\Markets\Model::setGoogleAnalyticsCategory() must be of the type string, null given, called in /var/www/mackolik/releases/1.19.2-go/app/Http/Controllers/Ajax/Iddaa/IndexController.php on line 48' in /var/www/mackolik/releases/1.19.2-go/app/Widgets/Iddaa/GoogleAnalyticsTrait.php:32

### ISSUE THREAD

**Issue by Harsha2121992** [laravel/framework#27671]
Hi Guys,

I was getting an error like Type error: Argument 1 passed to `App\Widgets\Iddaa\Markets\Model::setGoogleAnalyticsCategory()` must be of the type string, null given called in /var/www/mackolik/releases/1.19.2-go/app/Http/Controllers/Ajax/Iddaa/IndexController.php on line 48'

Here how the null value is passed? how to find that? I was bit confused with it. Can anyone please help?

IndexController.php
`

        if ($request->request->has('iddaaCode')) {
            $model->setIddaaCode($request->request->get('iddaaCode'));
        };

        $model->setGoogleAnalyticsAction($request->query->get('googleAnalyticsAction'));
        $model->setGoogleAnalyticsCategory($request->query->get('googleAnalyticsCategory'));  // line no:48
        $model->setGoogleAnalyticsLabel($request->query->get('googleAnalyticsLabel'));

        $view = View::make(
            'widgets.iddaa.markets.' . $request->get('template', Iddaa\Markets\Model::TEMPLATE_MAIN),
            [
                'model' => $model,
            ]
        );`

GoogleAnalyticsTrait.php

` public function setGoogleAnalyticsCategory(string $googleAnalyticsCategory)    // line no:32

    {
        $this->googleAnalyticsCategory = $googleAnalyticsCategory;
        return $this;
    }`

Thanks!

**Comment by driesvints** [comment]
Please don't ignore the issue template. Also: this is more a support question for one of the following support channels. Please only use this issue tracker for reporting bugs with the framework.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
