### ISSUE TITLE
[PGSQL] Illuminate \ Database \ QueryException (42803) SQLSTATE[42803]: Grouping error: 7 ERROR

### ISSUE THREAD

**Issue by amiller911** [laravel/framework#27670]
- Laravel Version: 5.7
- PHP Version: 7.1
- Database Driver & Version: PostgreSQL 9.2.24

### Description:
I was trying to create a migration in laravel using the code here. But unfortunately it pops out an error like given here.

`Illuminate \ Database \ QueryException (42803)
SQLSTATE[42803]: Grouping error: 7 ERROR: column "suggesteds.id" must appear in the GROUP BY clause or be used in an aggregate function LINE 1: select "id", "channel_id" from "suggesteds" group by "channe... ^ (SQL: select "id", "channel_id" from "suggesteds" group by "channel_id")`

### Migration file suggesteds
`<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateSuggestedsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('suggesteds', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('channel_id')->unsigned()->index();
            $table->string('group')->nullable()->index(); // 'technology', 'lifestyle', etc.
            $table->string('language')->default('en')->index();
            $table->integer('z_index')->default(0);
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('suggesteds');
    }
}`
Before i use MySQL and don't have its error.
Any help will be highly appreciated.

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by mfn** [comment]
@amiller911 
>  Before i use MySQL and don't have its error.

PostgreSQL works differently (then older MySQL) and you need adjust your query, the error message even tells you were to look at:
> …must appear in the GROUP BY clause or be used in an aggregate
