### ISSUE TITLE
PDO::prepare(): send of 76 bytes failed with errno=32 Broken pipe

### ISSUE THREAD

**Issue by lzp9421** [laravel/framework#27674]
- Laravel Version: 5.5.44

- PHP Version: 7.2.9

- Database Driver & Version: mysql 5.7.23

### Description:

[2019-02-26 19:49:01] local.ERROR: PDO::prepare(): send of 76 bytes failed with errno=32 Broken pipe (SQL: select * from xxxxxx limit 1) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 0): PDO::prepare(): send of 76 bytes failed with errno=32 Broken pipe (SQL: select * from XXXX limit 1) at vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, ErrorException(code: 0): PDO::prepare(): send of 76 bytes failed with errno=32 Broken pipe at vendor/laravel/framework/src/Illuminate/Database/Connection.php:326)

[stacktrace]
#0 .../vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#1 .../vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\\Database\\Connection->run('select * from `...', Array, Object(Closure))
#2 .../vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1719): Illuminate\\Database\\Connection->select('select * from `...', Array, true)
#3 .../vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1704): Illuminate\\Database\\Query\\Builder->runSelect()
#4 .../vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(481): Illuminate\\Database\\Query\\Builder->get(Array)
#5.../vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(465): Illuminate\\Database\\Eloquent\\Builder->getModels(Array)
#6 .../vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(77): Illuminate\\Database\\Eloquent\\Builder->get(Array)

### Steps To Reproduce:
the first time to request every day

**Comment by DariusIII** [comment]
That is an simple query to cause errors like this. What is the context for the query? Is your database setup properly?

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by tstchong** [comment]
How to solve this problem?
