### ISSUE TITLE
[5.8] Bug: Schema is aware of the connection that was default when it was first initialized, while it should be aware of the current connection

### ISSUE THREAD

**Issue by stancl** [laravel/framework#27686]
- Laravel Version: 5.8.0
- PHP Version: 7.2
- Database Driver & Version: Doesn't matter

### Description:

Introduced in #25512.

This results in Schema using the connection that the DB manager uses when Schema is first called.

```php
// change DB connection from default to foo
Schema::getConnection()->getName(); // => foo
// change the DB connection back
Schema::getConnection()->getName(); // => foo
```

Schema remembers the connection that was used when it was first initialized.

In 5.7 Schema used the current DB connection, which I believe is more correct.

My package's tests are broken because of this.

https://github.com/stancl/tenancy/blob/e1def355f96686556edd125975e76d1018d30d24/tests/CommandsTest.php#L30-L37

On line 34 Schema is first initialized and remembers that the `sqlite` connection is used and on line 36, when the DB manager uses the `tenant` connection, Schema still uses the `sqlite` connection.

### Steps To Reproduce:

You can try to turn my pseudocode into code or you can play with my package:

```bash
cd /tmp
git clone https://github.com/stancl/tenancy/
cd tenancy
git checkout f9a819215f7350bc3aec869cf7da687cd53bfcbc
composer install
phpunit --filter migrate_command_works_with_tenants_option
```

and look at the migrate_command_works_with_tenants_option method in tests/CommandsTest.php

@taylorotwell [said](https://github.com/laravel/framework/pull/25391#issuecomment-418126152):

> Hmm, I'm scared to change this in case I forgot some reason I did it this way. :eyes:

I think that this is the reason. This facade's accessor should be obtained on demand.

**Comment by stancl** [comment]
https://github.com/laravel/framework/pull/25512
https://github.com/laravel/framework/pull/25525
https://github.com/laravel/docs/pull/4544

Should be reverted.

Possibly https://github.com/laravel/framework/pull/25512 but only if it's causing problems.

**Comment by driesvints** [comment]
I can see this being a bug but I'm wondering if we can solve this differently in a way that we don't need to revert these changes. It seems to me that we need to find a way maybe make sure the concrete always loads the correct db connection.

**Comment by driesvints** [comment]
We've had a thorough look at this and decided to revert the changes. We released a fix for this. Thanks for reporting.

**Comment by stancl** [comment]
If Schema is the only facade that doesn't use a string accessor, perhaps it would be better to find a way to make Schema use the current connection instead of doing that logic in the getFacadeAccessor method?

**Comment by taylorotwell** [comment]
Why? What tangible, actual benefit would that provide to end-users of Laravel?

**Comment by stancl** [comment]
No benefit to end-users, however since #25525 was merged, I assume such consistency is wanted.

**Comment by driesvints** [comment]
I sent this in again but with keeping this issue in mind. I'd appreciate your review @stancl: https://github.com/laravel/framework/pull/38017
