### ISSUE TITLE
Class setEventDispatcher does not exist

### ISSUE THREAD

**Issue by BenSherred** [laravel/framework#27685]
- Laravel Version: 5.8.0
- PHP Version: 7.3.0
- Database Driver & Version: MySQL 5.7.24

### Description:
I have create a new laravel application and migrated the default migrations. I have also generated the default authentication scaffolding. However, when I go to register a user I get the following error message: Class setEventDispatcher does not exist

### Steps To Reproduce:

- Create a new laravel application from scratch
- Set database details
- Migrate the default migrations (php artisan migrate)
- Generate the authentication scaffolding (php artisan make:auth)
- Try to register a user

![Image](https://i.imgur.com/LbBdkwd.png)

**Comment by ahinkle** [comment]
Try reserving your project: `valet restart` or relevant.

**Comment by BenSherred** [comment]
I have tried restarting valet. However, I am still experiencing the same issue.

**Comment by X-Coder264** [comment]
https://github.com/laravel/framework/issues/27052

This is a known PHP 7.3.0 bug. You should update your PHP version (ideally to 7.3.2).

**Comment by BenSherred** [comment]
That seemed to fix the problem @X-Coder264, thank you for your help.
