### ISSUE TITLE
Minor bug in stock pagination blade templates

### ISSUE THREAD

**Issue by jonathannlittle** [laravel/framework#27689]
- Laravel Version: 5.7.*
- PHP Version: 7.2
- Database Driver & Version: N/A

### Description:
Using pagination feature places the ROLE attribute on the UL element which is not valid HTML for attribute.  

### Steps To Reproduce:
Use any of the stock pagination templates exception of semantic-ui.blade.php which correctly places attribute on wrapping DIV element.

Simple fix to change other templates to add wrapping DIV and place ROLE attribute on that, Example existing simple-default.blade.php from:

~~~
@if ($paginator->hasPages())
    <ul class="pagination" role="navigation">
        {{-- Previous Page Link --}}
        @if ($paginator->onFirstPage())
            <li class="disabled" aria-disabled="true"><span>@lang('pagination.previous')</span></li>
        @else
            <li><a href="{{ $paginator->previousPageUrl() }}" rel="prev">@lang('pagination.previous')</a></li>
        @endif

        {{-- Next Page Link --}}
        @if ($paginator->hasMorePages())
            <li><a href="{{ $paginator->nextPageUrl() }}" rel="next">@lang('pagination.next')</a></li>
        @else
            <li class="disabled" aria-disabled="true"><span>@lang('pagination.next')</span></li>
        @endif
    </ul>
@endif
~~~

to:

~~~
@if ($paginator->hasPages())
	<div role="navigation">
	    <ul class="pagination">
	        {{-- Previous Page Link --}}
	        @if ($paginator->onFirstPage())
	            <li class="disabled" aria-disabled="true"><span>@lang('pagination.previous')</span></li>
	        @else
	            <li><a href="{{ $paginator->previousPageUrl() }}" rel="prev">@lang('pagination.previous')</a></li>
	        @endif
	
	        {{-- Next Page Link --}}
	        @if ($paginator->hasMorePages())
	            <li><a href="{{ $paginator->nextPageUrl() }}" rel="next">@lang('pagination.next')</a></li>
	        @else
	            <li class="disabled" aria-disabled="true"><span>@lang('pagination.next')</span></li>
	        @endif
	    </ul>
    </div>
@endif
~~~

**Comment by ngyikp** [comment]
According to the [Bootstrap documentation](https://getbootstrap.com/docs/4.3/components/pagination/), maybe it should be wrapped in a `<nav>` instead

**Comment by driesvints** [comment]
I think the `nav` element is indeed better than the `div` with a `navigation` role.

**Comment by jonathannlittle** [comment]
Maybe, it would certainly be simpler. In [MDN web docs: nav element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav) it says NAV elements are intended for  'major block of navigation links' which is how I considered them, such as your main navbar or breadcrumb links. Pagination links are sort of secondary, so the DIV with ROLE maybe more appropriate.

**Comment by driesvints** [comment]
Hmmm, good point. I'm not familiar that much with these aspects of HTML so I think it might be better to have this confirmed by some other people as well.

**Comment by jonathannlittle** [comment]
By all means I agree. More input would be welcomed, maybe what the developers think. What is apparent how it is implemented now  is not really incorrect.

**Comment by ajoy39** [comment]
Relevant pull request here https://github.com/laravel/framework/pull/27878

**Comment by driesvints** [comment]
PR was merged.

**Comment by driesvints** [comment]
PR was reverted and new PR was merged on master. Will be added in the next major release: https://github.com/laravel/framework/pull/27919
