### ISSUE TITLE
Override config item in artisan kernel

### ISSUE THREAD

**Issue by Resin01** [laravel/framework#27711]
- Laravel Version: 5.7.28
- PHP Version: 7.2
- Database Driver & Version:

### Description:
In 5.7.22 it was possible to override config items by overriding the bootstap method

```
public function bootstrap()
    {
        parent::bootstrap();
        if (App::environment('local')) {
            app('config')->set(['database.connections.mysql.host' => '127.0.0.1']);
        }
    }
```
This worked and used the new host when running database tasks
After upgrading to 5.7.28 this is no longer possible

### Steps To Reproduce:
Install 5.7.22 and check that it is possible to override database host.
Install 5.7.28 and see that it no longer works.

**Comment by driesvints** [comment]
Can you pinpoint the exact version which broke this? That might give a hint what's causing this.

**Comment by Resin01** [comment]
Works in 5.7.24 and breaks in 5.7.25

**Comment by driesvints** [comment]
I can't really see what might have caused this honestly: https://github.com/laravel/framework/compare/v5.7.24...v5.7.25

**Comment by Resin01** [comment]
It seems to be this
`src/Illuminate/Database/DetectsLostConnections.php`
Here you removed
`'php_network_getaddresses: getaddrinfo failed: Name or service not known',`

It seems that it first builds the connector (which generates an  error), then bootstraps artisan (overriding the config) and then getting the connector again (now with the new config)

It would seem that I need to find a better way of overriding the config :( Any suggestions would be great!

**Comment by Resin01** [comment]
Alas. There seems to be no viable method of doing this currently :(
Fingers crossed for either a config file for artisan or even better a service provider, someday.

**Comment by driesvints** [comment]
Seems like it was reverted for being to generic: https://github.com/laravel/framework/pull/27418

I indeed fear there's not a viable way to do this atm.
