### ISSUE TITLE
Undefined class constant 'MYSQL_ATTR_SSL_CA' during `laravel new`

### ISSUE THREAD

**Issue by crhg** [laravel/framework#27712]
- Laravel Version: 5.8
- PHP Version: 7.2
- Database Driver & Version: (Without pdo_mysql)

### Description:

When I run `laravel new foo` using php without `pdo_mysql` extension, the following error message was output.

```console
% laravel new foo
Crafting application...
(snip)
Generating optimized autoload files
> @php -r "file_exists('.env') || copy('.env.example', '.env');"
> @php artisan key:generate --ansi

In database.php line 58:

  Undefined class constant 'MYSQL_ATTR_SSL_CA'


Script @php artisan key:generate --ansi handling the post-create-project-cmd event returned with error code 1
Application ready! Build something amazing.
```

And the value of `APP_KEY` in the `.env` file remained empty.

### Steps To Reproduce:

Run `laravel new foo` using php without `pdo_mysql` extension.

**Comment by driesvints** [comment]
> In database.php line 58

Which file is this? Can you post a stacktrace?

**Comment by ankurk91** [comment]
Possibly
https://github.com/laravel/laravel/blob/f4ff4f4176f7d931e301f36b95a46285ac61b8b8/config/database.php#L58

**Comment by matijakovacevic** [comment]
yep...happened today as well, whilst upgrading...

The line that @ankurk91 mentioned should be wrapped in some kind of 'safe' logic...

In my case, I'm not using MySql (but Postgres), nor have the PHP extension installed...

Even though MySql is kinda out-of-the-box default, 
it should check for MySql PHP extension availability and handle it gracefully, instead of throwing an error

**Comment by driesvints** [comment]
Hmm, yeah that's probably it. We'll need to find a different solution for this.

**Comment by driesvints** [comment]
We've commented that section out for now so it's opt-in instead. You can do the same in your config: https://github.com/laravel/laravel/commit/a0f6bcc773f3895db0ca4a85101b9a3ef2f95782

**Comment by crhg** [comment]
No stack trace was displayed.

I greped under the `foo` directory and found that it is only `config/database.php` that uses `MYSQL_ATTR_SSL_CA`.

```php
        'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
            'options' => array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]),
        ],
```

Before using `PDO::MYSQL_ATTR_SSL_CA`, I think that it is necessary to check whether `pdo_mysql` extension is loaded.

For example:

```php
            'options' => !extension_loaded('pdo_mysql') ? [] : array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]),
```

**Comment by staudenmeir** [comment]
@driesvints Can you release a new version of `laravel/laravel`?

**Comment by driesvints** [comment]
@staudenmeir will try to do that tomorrow 👍

**Comment by driesvints** [comment]
@staudenmeir can you maybe remind me again why that's specifically needed?

**Comment by staudenmeir** [comment]
I think this is a pretty significant bug that should be fixed in new installations.

**Comment by driesvints** [comment]
New installations will just get the new skeleton updates. If I run `laravel new <app name>` I get the latest skeleton commits.

**Comment by driesvints** [comment]
What I'm trying to say: I believe there *was* a reason for regularly tagging the skeleton but it slipped my mind atm.

**Comment by staudenmeir** [comment]
`composer create-project --prefer-dist laravel/laravel blog` gives me the files from the last release.

**Comment by driesvints** [comment]
@staudenmeir gotcha. That was it. Thanks!

**Comment by assismoraes** [comment]
I solve it installing php*-mysql: `sudo apt-get install php7.2-mysql`

**Comment by ixysoft** [comment]
I solved it by: sudo apt install php7.2-pdo-mysql
