### ISSUE TITLE
tinker doesn't fully respect -q and -n

### ISSUE THREAD

**Issue by aksonnic** [laravel/framework#27721]
- Laravel Version: 5.7.26
- PHP Version: 7.1.19
- Database Driver & Version: n/a

### Description:

Tinker with either the -q (quiet) or the -n (no interaction) does not fully respect these options. Use case is an include file that echos stuff as part of a build process, but it cannot be run headless.

### Steps To Reproduce:

`> php artisan tinker -q`
prints prompt `>>>` and the `Exit: Goodbye.` message.

`> php artisan tinker -n`
waits for interaction before exiting.

File `hello_world.php`:
```php
<?php echo('Hello world!');
```
`> php artisan tinker -qn hello_world.php`
pauses until `exit` is typed in shell.

**Comment by driesvints** [comment]
Can you re-open this on the tinker repo? This is the issue tracker for the framework.
