### ISSUE TITLE
Creating a listener in command line

### ISSUE THREAD

**Issue by igelinas** [laravel/framework#27736]
- Laravel Version: 5.7.28
- PHP Version: 7.1.9
- Database Driver & Version: MariaDB 10.2.8

### Description:
If you create a listener using php artisan, it doesn't notice if there is already a listener with this name  and it overwrites it.

### Steps To Reproduce:

**Comment by mfn** [comment]
Please don't ignore the template, it says:
> Steps To Reproduce:

But you left it empty.

Please be specific, provide clear and reproducible directions of what you consider is a bug; thank you

**Comment by igelinas** [comment]
Steps:
1. In console: php artisan make:listener MyListener
2. Resulting of : listener created successfully.
3. In console: php artisan make:listener MyListener
4. Resulting of : listener created successfully.

it should output : "Listener already exists" and not overwriting the existing one.

**Comment by devcircus** [comment]
There's been multiple PRs that tried to change this. See [Taylor's comment](https://github.com/laravel/framework/pull/24126). Maybe if only the listener was changed, it would be accepted?

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not for ideas, suggestions etc. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. You are able to open a ticket at https://github.com/laravel/ideas

Alternatively you are able to open a PR using the Contributions guidelines: https://laravel.com/docs/5.7/contributions#which-branch

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
