### ISSUE TITLE
laravelcollective/html installation problem

### ISSUE THREAD

**Issue by andonovivan** [laravel/framework#27739]
When i try to install laravelcollective/html with the command 'composer require laravelcollective/html'  in my laravel project i get the following message on the console:

Using version ^5.7 for laravelcollective/html
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.8.2
    - Conclusion: don't install laravel/framework v5.8.2
    - laravelcollective/html 5.7.x-dev requires illuminate/view 5.7.* -> satisfiable by illuminate/view[5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.
20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].
    - laravelcollective/html 5.7.x-dev requires illuminate/view 5.7.* -> satisfiable by illuminate/view[5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.
20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].
    - laravelcollective/html v5.7 requires illuminate/view 5.7.* -> satisfiable by illuminate/view[5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v
5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].
    - laravelcollective/html v5.7.1 requires illuminate/view 5.7.* -> satisfiable by illuminate/view[5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20,
 v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].
    - don't install illuminate/view 5.7.17|don't install laravel/framework v5.8.2
    - don't install illuminate/view 5.7.18|don't install laravel/framework v5.8.2
    - don't install illuminate/view 5.7.19|don't install laravel/framework v5.8.2
    - don't install illuminate/view 5.7.x-dev|don't install laravel/framework v5.8.2
    - don't install illuminate/view v5.7.0|don't install laravel/framework v5.8.2
    - don't install illuminate/view v5.7.1|don't install laravel/framework v5.8.2
    - don't install illuminate/view v5.7.10|don't install laravel/framework v5.8.2
    - don't install illuminate/view v5.7.11|don't install laravel/framework v5.8.2
    - don't install illuminate/view v5.7.15|don't install laravel/framework v5.8.2
    - don't install illuminate/view v5.7.2|don't install laravel/framework v5.8.2
    - don't install illuminate/view v5.7.20|don't install laravel/framework v5.8.2
    - don't install illuminate/view v5.7.21|don't install laravel/framework v5.8.2
    - don't install illuminate/view v5.7.22|don't install laravel/framework v5.8.2
    - don't install illuminate/view v5.7.23|don't install laravel/framework v5.8.2
    - don't install illuminate/view v5.7.26|don't install laravel/framework v5.8.2
    - don't install illuminate/view v5.7.27|don't install laravel/framework v5.8.2
    - don't install illuminate/view v5.7.28|don't install laravel/framework v5.8.2
    - don't install illuminate/view v5.7.3|don't install laravel/framework v5.8.2
    - don't install illuminate/view v5.7.4|don't install laravel/framework v5.8.2
    - don't install illuminate/view v5.7.5|don't install laravel/framework v5.8.2
    - don't install illuminate/view v5.7.6|don't install laravel/framework v5.8.2
    - don't install illuminate/view v5.7.7|don't install laravel/framework v5.8.2
    - don't install illuminate/view v5.7.8|don't install laravel/framework v5.8.2
    - don't install illuminate/view v5.7.9|don't install laravel/framework v5.8.2
    - Installation request for laravel/framework (locked at v5.8.2, required as 5.8.*) -> satisfiable by laravel/framework[v5.8.2].
    - Installation request for laravelcollective/html ^5.7 -> satisfiable by laravelcollective/html[5.7.x-dev, v5.7, v5.7.1].

Installation failed, reverting ./composer.json to its original content.

**Comment by mfn** [comment]
> laravelcollective/html installation problem 

You correctly identifier that the problem lies with `laravelcollective/html`: the current release doesn't support 5.8 versioning.
Hence this is not a Laravel issue.

Please follow-up with the package itself => you will find out that a PR for 5.8 support already exists, please see https://github.com/LaravelCollective/html/pull/590

**Comment by ibrahem-kamal** [comment]
so what version to use

**Comment by tamzidpeace** [comment]
try this one

composer require "laravelcollective/html":"^5.8.4"  (version should be your laravel version, this one is mine)

**Comment by sarsa2012** [comment]
> try this one
> 
> composer require "laravelcollective/html":"^5.8.4" (version should be your laravel version, this one is mine)

Fantastic worked for me <3

**Comment by SirRinda** [comment]
and for 7.1.0 how can I install that

**Comment by radhikaagr18** [comment]
composer require laravelcollective/html

**Comment by Zemif** [comment]
how to install for 8.6.0

**Comment by Mnabawy** [comment]
you just need to run 
`composer require laravelcollective/html` 
without specifying the version

**Comment by arahimfahim40** [comment]
> you just need to run `composer require laravelcollective/html` without specifying the version

This worked for me, thank you!

Best,
Abdul,
islamTheCure.com

**Comment by Mnabawy** [comment]
I am ready for front end roles
