### ISSUE TITLE
Get json response from RegisterController@validator

### ISSUE THREAD

**Issue by jadamec** [laravel/framework#27737]
Hi there,
how to do from this:
```
protected function validator(array $data)
	{
		return Validator::make($data, [
			'email' => 'unique:posts|unique:users'
		]);
	}
```
something like this in RegisterController.php, please? Thanks!
```
$validator = Validator::make($request->only('email'), [
				'email' => 'nullable|unique:posts'
			]);

			if ($validator->fails()) {
				return response()->json(['errors' => $validator->errors()->all()]);
			}
```

**Comment by onetwothreeneth** [comment]
just make a new method then call it on the same controller your using

**Comment by jadamec** [comment]
@onetwothreeneth That's what I tried, but still doesn't work.

**Comment by onetwothreeneth** [comment]
Can you show your code and error ?

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
