### ISSUE TITLE
Update description link

### ISSUE THREAD

**Issue by mdandidarmawan** [laravel/framework#27746]
[Laravel framework](https://github.com/laravel/framework) description is using 
```
http://laravel.com
```
not
```
https://laravel.com
```

Like the [Laravel repository](https://github.com/laravel/laravel) does.

Thank you.

**Comment by imanghafoori1** [comment]
![image](https://user-images.githubusercontent.com/6961695/53701232-1be67e00-3e10-11e9-867d-3d596206f0fe.png)

You mean here ?

**Comment by mdandidarmawan** [comment]
Yes.

**Comment by driesvints** [comment]
Done.
