### ISSUE TITLE
Unknown release 5.5.45 ?

### ISSUE THREAD

**Issue by mikew1** [laravel/framework#27743]
If I run `composer update` on my 5.5 application, I get this in the console:

`Updating laravel/framework (v5.5.44 => v5.5.45): Loading from cache`

So I want to take a look at what changed in v5.5.45.

But I can't find [any mention](https://github.com/laravel/framework/blob/5.5/CHANGELOG-5.5.md) of v5.5.45 - last mentioned is 5.5.44.   Can someone kindly explain what I'm doing wrong? Thank you.

**Comment by staudenmeir** [comment]
You aren't doing anything wrong, the changelog just hasn't been updated yet.

**Comment by mikew1** [comment]
Thank you so much -- I just found how to do that :) 
https://github.com/laravel/framework/compare/v5.5.44...v5.5.45

**Comment by driesvints** [comment]
Please don't ignore the issue template.
