### ISSUE TITLE
Laravel Migrations with MySQL 8.0.x

### ISSUE THREAD

**Issue by thekiharani** [laravel/framework#27742]
- Laravel Version: 5.8.2
- PHP Version: 7.3.2
- Database Driver & Version: mysql 8.0.15

### Description:
`Illuminate\Database\QueryException  : SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client (SQL: select * from information_schema.tables where table_schema = ota_points and table_name = migrations)`

### Steps To Reproduce:
- Install mysql 8.0 and use the new recommended password authentication (leave the legacy option)
- Create new laravel app
- Configure db in .env file
- Try to migrate

**Comment by ahinkle** [comment]
Duplicate of #23961.

**Comment by staudenmeir** [comment]
This is a PHP issue, Laravel can't do anything to fix it: https://bugs.php.net/bug.php?id=76243

**Comment by swrshah1** [comment]
open mysql in the terminal (just type mysql)
Use the following command
ALTER USER 'username here'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password here';
Leave the password empty if you don't want a password.
Use this user in your laravel env file for the MYSQL database.

**Comment by vitormicillo** [comment]
This is the best solution until PHP not fix this issue.

> open mysql in the terminal (just type mysql)
> Use the following command
> ALTER USER 'username here'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password here';
> Leave the password empty if you don't want a password.
> Use this user in your laravel env file for the MYSQL database.

**Comment by StBlackJesus** [comment]
> open mysql in the terminal (just type mysql)
> Use the following command
> ALTER USER 'username here'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password here';
> Leave the password empty if you don't want a password.
> Use this user in your laravel env file for the MYSQL database.

Thank you very much, this solution worked in my case

**Comment by oleynikd** [comment]
Don't forget to update to PHP 7.4

**Comment by sousadgaspar** [comment]
> open mysql in the terminal (just type mysql)
> Use the following command
> ALTER USER 'username here'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password here';
> Leave the password empty if you don't want a password.
> Use this user in your laravel env file for the MYSQL database.

I was passing through the same issue. And the procedure above solved. Thank you very much @swrshah1

**Comment by ChrisBinK** [comment]
> open mysql in the terminal (just type mysql)
> Use the following command
> ALTER USER 'username here'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password here';
> Leave the password empty if you don't want a password.
> Use this user in your laravel env file for the MYSQL database.

Thanks you.

**Comment by HuyPham55** [comment]
> open mysql in the terminal (just type mysql)
> Use the following command
> ALTER USER 'username here'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password here';
> Leave the password empty if you don't want a password.
> Use this user in your laravel env file for the MYSQL database.

Thanks sir

**Comment by sgirad** [comment]
> open mysql in the terminal (just type mysql)
> Use the following command
> ALTER USER 'username here'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password here';
> Leave the password empty if you don't want a password.
> Use this user in your laravel env file for the MYSQL database.

Thank you very much, this solution worked in my case PHP7.3

**Comment by gopalrathod131** [comment]
Thanks!
Perfect solution for mysql 8.0,x
