### ISSUE TITLE
pdo_mysql is now required (MYSQL_ATTR_SSL_CA)

### ISSUE THREAD

**Issue by ProteanCode** [laravel/framework#27745]
- Laravel Version: 5.8.2
- PHP Version: 7.3.2 (using Docker php:7.3.2-fpm-alpine3.9)
- Database Driver & Version: no database configured, just pdo extension (without pdo_mysql)

### Description:
During post steps I got an error about missing constatnt MYSQL_ATTR_SSL_CA

### Steps To Reproduce:
1. composer create-project --prefer-dist laravel/laravel myIssueWithMySQL
2. cd myIssueWithMySQL
3. rm -rf vendor
4. touch Dockerfile
5. Create container using this Dockerfile

FROM php:7.3.2-fpm-alpine3.9
RUN docker-php-ext-install pdo
RUN php -r "copy('https://getcomposer.org/installer', '/tmp/composer-setup.php');" &&\
        php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer &&\
        rm /tmp/composer-setup.php

5. Build image using command docker build . -t myIssueWithMySQLImage
6. Run the container using following command docker run -it -v $(pwd):/var/www/html myIssueWithMySQLImage
7. inside the container run composer install

It ends with

Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In database.php line 58:
                                                
  Undefined class constant 'MYSQL_ATTR_SSL_CA'  
                                                

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

To fix this I had to add a pdo_mysql extension and I consider this a bug worth of rolling back to Laravel 5.7 where this does not happen

From what I see it is related to
https://github.com/laravel/framework/issues/27712

**Comment by staudenmeir** [comment]
Apply this change to your local code: https://github.com/laravel/laravel/commit/a0f6bcc773f3895db0ca4a85101b9a3ef2f95782

**Comment by staudenmeir** [comment]
Please close the issue.
