### ISSUE TITLE
[v5.7.28] php artisan package:remove deletes everything from the vendor

### ISSUE THREAD

**Issue by bilogic** [laravel/framework#27755]
- Laravel Version: 5.7.28
- PHP Version: 7.2.10
- Database Driver & Version: N/A

### Description:
```php artisan package:remove v1 p1``` is deleting everything inside ```v1```

### Steps To Reproduce:
I have 2 laravel projects ```my-own-packages``` and ```App1```

1. New packages are always created inside ```my-own-packages``` using ```php artisan package:new v1 p1```
2. ```App1```'s ```composer.json``` contains ```"repositories": [{ "type": "path", "url": "../my-own-package/packages/*/*"}]```, so my own packages can be pulled by running ```composer require v1/p1``` and so on.
3. I do this so that, in time, ```App2``` can re-use ```v1/p1``` via composer
4. While running a ```php artisan package:remove v1 p1```, artisan deleted several other packages inside ```my-own-packages/packages/v1``` before some permissions issue caused it to throw an exception.
5. Is this by design? Seems more like a bug to me
6. If by design, then is there a way to isolate packages from the app during development? i.e. the package sits inside ```App1/vendor/v1/p1``` instead of ```App1/packages/v1/p1```
7. To workaround, I had to run ```php artisan package:disable v1 p1``` in ```my-own-packages``` and then manually delete ```my-own-packages/packages/v1/p1```

Thank you.

**Comment by devcircus** [comment]
You'll need to report this on the repo of the package that is providing these commands.

**Comment by bilogic** [comment]
oh.. got it. Sorry I'm very new to laravel. Thanks!
