### ISSUE TITLE
Auth::routes(['verify' => (bool)]) always true

### ISSUE THREAD

**Issue by KyleMassacre** [laravel/framework#27759]
- Laravel Version: 5.8
- PHP Version: 7.2.8 

### Description:
Any value put in for the `verify` key always registers it as true. If I wanted to create some sort of config key or .env var, no matter what, it would return `true` and and throw:
```
Route [verification.verify] not defined.
```

### Steps To Reproduce:
In `routes/web.php` enter:
1. `Auth::routes(['verify' => false]);`
2. Navigate to `your-domain.tld/register` and register

**Comment by laurencei** [comment]
Are you sure you dont have config and/or route caching causing this?

**Comment by KyleMassacre** [comment]
Yes I am sure. And to double check I went ahead and cleared all my chaches

**Comment by driesvints** [comment]
Register and verify are two different things. Use `Auth::routes(['register' => false]);` if you want to disable them.
