### ISSUE TITLE
Laravel customizing & modifying URL::temporarySignedRoute for must verify email

### ISSUE THREAD

**Issue by shahzad-sarwar** [laravel/framework#27756]
Any help would be really appreciated.

I'm using hyn/multi-tenant. I'm trying to register the user account with tenancy in placed. The user does get registered & the email is sent to them. The email looks like the following.

http://example.com/email/verify/1?expires=1551615525&signature=b389f8c5d25c426c966ba0092ee062ab4e3febaebab5dcfd083549c7c2362150

When the user clicks on it, the account doesn't get activated.

The user will have to log in to there dashboard, and resend the verification email from http://abc.example.com, then the URL is generated correctly and the account is activated successfully.

http://abc.example.com/email/verify/1?expires=1551615525&signature=b389f8c5d25c426c966ba0092ee062ab4e3febaebab5dcfd083549c7c2362150

My actual question is can we modify or hook into URL::temporarySignedRoute? to add the sub-domain name inside the URL? so it should look like http://abc.example.com

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
