### ISSUE TITLE
Laravel Base Table or View Not Found: 1146

### ISSUE THREAD

**Issue by 01Mihail01** [laravel/framework#27752]
- Laravel Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:

   Illuminate\Database\QueryException  : SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mihaiapp.post' doesn't exist (SQL: alter table `post` add `user_id` int not null)

  at C:\xampp\htdocs\mywebsite\vendor\laravel\framework\src\Illuminate\Database\Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668| 
I'm new to Laravel , i just created my first ,,website" with navbar , login id , forgot password , and etc, i also migrated and i have made some ,,things " in database . I want to say that i don't know i receive de given error when i try to write the following command : "$php artisan migrate " . I really don't know what to say and i will let some photo's here if someone would be nice to help me ! 

Here is my error:
  Exception trace:

  1   PDOException::("SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mihaiapp.post' doesn't exist")
      C:\xampp\htdocs\mywebsite\vendor\laravel\framework\src\Illuminate\Database\Connection.php:458

  2   PDOStatement::execute()
      C:\xampp\htdocs\mywebsite\vendor\laravel\framework\src\Illuminate\Database\Connection.php:458

  Please use the argument -v to see more details.

myLaravel files:
https://www.dropbox.com/s/9ddbxz7m1wtlbpf/Screenshot%202019-03-02%2011.42.11.png?dl=0
https://www.dropbox.com/s/ukqslxeol2lcvqd/Screenshot%202019-03-02%2011.46.27.png?dl=0
https://www.dropbox.com/s/tbfhjknggw55a7y/Screenshot%202019-03-02%2011.46.24.png?dl=0
https://www.dropbox.com/s/mkvw5lul7vti4hq/Screenshot%202019-03-02%2011.46.22.png?dl=0
https://www.dropbox.com/s/e9fpsixhhfvh22h/Screenshot%202019-03-02%2011.46.20.png?dl=0
https://www.dropbox.com/s/ri82d4tn2ci3bx9/Screenshot%202019-03-02%2011.46.12.png?dl=0
https://www.dropbox.com/s/ng9w37gwb0hr10x/Screenshot%202019-03-02%2011.45.54.png?dl=0
https://www.dropbox.com/s/5z5tggmgjodito1/Screenshot%202019-03-02%2011.45.49.png?dl=0
https://www.dropbox.com/s/uz8kbldjxjexjr1/Screenshot%202019-03-02%2011.45.43.png?dl=0
phpmyadmin image:
https://www.dropbox.com/s/a00l4kla4q2iuza/Screenshot%202019-03-02%2011.49.38.png?dl=0

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
