### ISSUE TITLE
invalid request return status code 200

### ISSUE THREAD

**Issue by LucienCorreia** [laravel/framework#27754]
- Laravel Version: 5.8.2
- PHP Version: 7.3.2
- Database Driver & Version: none

### Description:
When validation does not pass it returns 200 status in json request

### Steps To Reproduce:
- Make a request
``` php
        public function rules() {
             return [
                 'email' => 'required',
             ];
         }
```
- send requisition
``` json
{
	"email": "",
}
```

return status code 200

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
