### ISSUE TITLE
Getting laravel_through_key in hasManyThrough relation

### ISSUE THREAD

**Issue by solution7** [laravel/framework#27768]
- Laravel Version: 5.8.*
- PHP Version: 7.3.2

### Description:
Getting **laravel_through_key** intead of **foreign key on the "through" model**  in hasManyThrough relation

**Comment by staudenmeir** [comment]
This has been changed in Laravel 5.8 to prevent column overriding: https://github.com/laravel/framework/pull/25812

What exactly is your issue?

**Comment by solution7** [comment]
It has not been documented in the version release.

**Comment by staudenmeir** [comment]
See https://github.com/laravel/docs/pull/4563.

**Comment by solution7** [comment]
@staudenmeir Thanks!

**Comment by mungpara** [comment]
> @staudenmeir Thanks!


look at for solution
https://github.com/laravel/framework/issues/745#issuecomment-15610315

**Comment by ashwinsabu** [comment]
I am trying to access a third table details from one but it is only displaying laravel_through_key

**Comment by monvelweb** [comment]
@ashwinsabu any success?
