### ISSUE TITLE
New tag for 5.2?

### ISSUE THREAD

**Issue by gms8994** [laravel/framework#27766]
There's a fix in the 5.2 branch that fixes an issue I'm experiencing on a legacy application. However, there hasn't been a new tag for 5.2 that contains this fix. Is there any way to get a new tag for 5.2? Commit with fix is 63c8841aa8c000d9259ea6e8683073e9dfc3af83. v5.2.45 seems to be the last tag available.

**Comment by driesvints** [comment]
Heya, unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting.

**Comment by Qh0stM4N** [comment]
@gms8994 mybe try this update all commands.
First Step: create your forked repository. And made better.

`find /path/to/old/but/good/projects/ -name "composer.json" -type f -exec bash -c 'php converter.php {} && composer update -d=$(dirname {})' \;`

in converter.php pseude Code.

> json_decode(file_get_contents($argv[1]));
> //modification like this similar answer: https://stackoverflow.com/a/13500676 
> file_put_contents(json_encode($argv[1]));

**Danger Zone:** Not tested bash code be carefull goodLuck.

**Comment by devcircus** [comment]
As 5.2 will never be overwritten, you should be able to safely make the change in vendor if you can't upgrade.
