### ISSUE TITLE
can not get json from api 

### ISSUE THREAD

**Issue by mortezamoradi72** [laravel/framework#27760]
Hello I Create a Rest Api with Laravel and get data like: 

```
> $news = News::all();
return response()->json($news, 200,['Content-Type' => 'application/json;charset=UTF-8', 'Charset' => 'utf-8'],JSON_UNESCAPED_UNICODE);
```
This Code give me A json like This: 

> [{"id":1,"title":"Hello","des":"how are","level":1,"type":"normal","jsondata":"How to handle pagination in retrofit","jsondw":"[{\"word\":\"asdf\",\"den\":\"asdf\",\"dfa\":\"asdf\"}]","stringdata":"my name is  .... 

But I Want A json Like This : 

> [
  {
    "userId": 1,
    "id": 1,
    "title": "delectus aut autem",
    "completed": false
  },
  {
    "userId": 1,
    "id": 2,
    "title": "quis ut nam facilis et officia qui",
    "completed": false
  },
  {
    "userId": 1,
    "id": 3,
    "title": "fugiat veniam minus",
    "completed": false
  },

When i Use retrofit in androdi i have an error that say your response is not json its a string !

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
