### ISSUE TITLE
Route parameter return null

### ISSUE THREAD

**Issue by ivybridge-3c33** [laravel/framework#27779]
- Laravel Version: 5.7
- PHP Version: 7.1.13
- Database Driver & Version: MariaDB 10

### Description:
I got a problem on phpunit I'm design route as

`/v1/outlet/{outlet_id}/test`

`
$router->get('/v1/outlets/{outlet_id}/test', function(){`
`    return app('request')->route('outlet_id');`
`});`

It's working when i call it in postman or browser but in phpunit show out as error

Call to a member function parameter() on array
test code

`$req = $this->call('GET', '/v1/outlets/1/test');`
`dump($req->getContent());`
`$this->assertResponseStatus(200);`

**Comment by driesvints** [comment]
Please don't post duplicate issues.
