### ISSUE TITLE
5.7.28 Warning info when using diffForHumans()'s Carbon method with tinker. transChoice() Symfony deprecated.

### ISSUE THREAD

**Issue by echayotte** [laravel/framework#27775]
Hi there ! 
I'm using Laravel 's **5.7.28.**  on a project with a **localhost** on an ubuntu 18.04 and **PHP 7.2.15**
I used **diffForHumans()'s Carbon method**.
I wanted to let you know this small **tinker PHP Symfony warning** who doesn't seems relevant anymore, but maybe I can be wrong. If so, sorry for that.
with a simple *Model Comment* using this schema :

`Schema::create('comments', function (Blueprint $table) {

    $table->increments('id'); 
    $table->string('url');  
    $table->text('body');  
    $table->timestamps();  
});`
I open **tinker** to write :

` $comment = Comment::latest()->first()`

*[!] Aliasing 'Comment' to 'App\Comment' for this Tinker session.
=> App\Comment {#2918
     id: "7",
     name: "Joe",
     url: "http://localhost:3000/page1",
     body: "Un autre commentaire",
     created_at: "2019-03-04 16:25:34",
     updated_at: "2019-03-04 16:25:34",
   }*
`$comment->created_at->diffForHumans()`

**Here is the warning I get even tho the result works fine :**

PHP Deprecated:  The "Symfony/Component/Translation/Translator::transChoice()" method is deprecated since Symfony 4.2, use the trans() one instead with a "%count%" parameter. in /var/www/*{...My Folders...}*/vendor/symfony/translation/Translator.php on line 229
PHP Deprecated:  The "Symfony/Component/Translation/Formatter/MessageFormatter::choiceFormat()" method is deprecated since Symfony 4.2, use the format() one instead with a %count% parameter. in /var/www/{...My Folders...}*/vendor/symfony/translation/Formatter/MessageFormatter.php on line 69
PHP Deprecated:  The "Symfony/Component/Translation/Translator::transChoice()" method is deprecated since Symfony 4.2, use the trans() one instead with a "%count%" parameter. in /var/www/{...My Folders...}*/vendor/symfony/translation/Translator.php on line 229
PHP Deprecated:  The "Symfony/Component/Translation/Formatter/MessageFormatter::choiceFormat()" method is deprecated since Symfony 4.2, use the format() one instead with a %count% parameter. in /var/www/{...My Folders...}*/vendor/symfony/translation/Formatter/MessageFormatter.php on line 69
**=> "il y a 4 heures"`**

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
