### ISSUE TITLE
[5.8] Storage download doesn't return file correctly

### ISSUE THREAD

**Issue by cloudbluedigital** [laravel/framework#27789]
- Laravel Version: 5.8.2
- PHP Version: 7.3
- Database Driver & Version: Mysql, 5.7

### Description:
I have code like this
```
        $file = Storage::disk('local')->exists($attachment->path);
        if (!$file) {
            return Storage::disk('s3')->download("{$attachment->path}/{$attachment->filename}", $attachment->filename);
        }
        return Storage::disk('local')->download("{$attachment->path}/{$attachment->filename}", $attachment->filename);
```

Example I will use is a png file. Now in 5.7 this code correctly returns the file. in 5.8 this code returns 200 response however the image is unreadable even when downloaded to a computer and opened via Preview on mac it shows that the file cannot be opened.

**Comment by devcircus** [comment]
Which specific 5.7 version does it work on?

**Comment by cloudbluedigital** [comment]
any 5.7 version it seems to work fine, even the latest one @devcircus

**Comment by devcircus** [comment]
Interesting. Just trying to narrow down to the commit that may have caused things to change.

**Comment by laurencei** [comment]
A few quick questions;

- Does the error occur on 5.8.0, or only on 5.8.2
- Can you check what FlySystem package version composer is installing under the hood of each on your installation - I'm wondering if the problem is there...

**Comment by cloudbluedigital** [comment]
Issue is still there with 5.8.0
FlySystem package version is 
```
╰ composer show league/flysystem                                                               02:25      10:18    03.06.19 
name     : league/flysystem
descrip. : Filesystem abstraction: Many filesystems, one API.
keywords : Cloud Files, WebDAV, abstraction, aws, cloud, copy.com, dropbox, file systems, files, filesystem, filesystems, ftp, rackspace, remote, s3, sftp, storage
versions : * 1.0.50
```

same for 5.7.*

**Comment by driesvints** [comment]
Can you maybe re-create the problem in a small test app and upload it to a repo on Github so we can test it out?

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by lloricode** [comment]
@devcircus, im also experiencing this, im using framework `5.8.18`

**Comment by cherrysoft** [comment]
I also have this issue.  v5.8.10.  I have tried adding headers and also added download attribute to anchor tag and the problem persists.
