### ISSUE TITLE
Is there any possible way to generate database from models in Laravel?

### ISSUE THREAD

**Issue by amarahajer** [laravel/framework#27798]
Is there any possible way to generate database from models in Laravel ? I am working on an existing laravel project,it contains models without their migrations.

**Comment by antonkomarev** [comment]
There are packages which could do this for you.

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:
- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co/)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
