### ISSUE TITLE
Laravel Accessor Query Issue

### ISSUE THREAD

**Issue by akramwahid** [laravel/framework#27796]
- Laravel Version: 5.6.39
- PHP Version: 7.1.19
- Database Driver & Version: mysql 5.6.43

### Description:
When I chain where and orWhere in a model accessor to count related model , I get wrong result and here is my query. the count is returned strange result without filtering by the calling event id,

```
class Event extends Model
{
    protected $table = 'events';
    public function registrations()
    {
        return $this->hasMany('App\Components\Event\Models\Registration','event_id','id');
    }

    public function getSeatsBookedAttribute()
    {
        return $this->registrations()          
            ->where('reg_status','=','Confirmed')
            ->orWhere('reg_status','=','Reserved')
            ->count();
    }
}
```

### Steps To Reproduce:
the following queries return me the expected results, however In my knowledge the first query should return the same result if i am not wrong, so i think this is a potential bug.
```
class Event extends Model
{
    public function getSeatsBookedAttribute()
    {
        return $this->registrations()          
             ->whereIn('reg_status', ['Confirmed', 'Reserved'])
            ->count();
    }

}


class Event extends Model
{
    public function getSeatsBookedAttribute()
    {
        return $this->registrations()          
          ->where(function($query){
                $query->where('reg_status','Confirmed')
                    ->orWhere('reg_status','Reserved');
           })
            ->count();
    }

}
```

**Comment by rs-sliske** [comment]
id say this will be down to order of operations

there relationship method behind the scenes is adding where(fk,id) so you end up with a query of select * from table where fk = id and status = confirmed or status = reserved

from what you have described the database is taking this as select * from table where (fk = id and status = confirmed) or status = reserved

your last example tells laravel to group the conditions how you want select * from table where fk = id and (status = confirmed or status = reserved), which i would always recommend doing when using or's

for this use case though i would go with whereIn

maybe there is a way (a pull request) to make the framework group automatically for relationship

**Comment by akramwahid** [comment]
> 
> 
> id say this will be down to order of operations
> 
> there relationship method behind the scenes is adding where(fk,id) so you end up with a query of select * from table where fk = id and status = confirmed or status = reserved
> 
> from what you have described the database is taking this as select * from table where (fk = id and status = confirmed) or status = reserved
> 
> your last example tells laravel to group the conditions how you want select * from table where fk = id and (status = confirmed or status = reserved), which i would always recommend doing when using or's
> 
> for this use case though i would go with whereIn
> 
> maybe there is a way (a pull request) to make the framework group automatically for relationship
> 
> i would be surprised if this is related to being in an accessor
I understand the query and you are correct @rs-sliske , since the documentation doesn't mention anything about this, the framework must handle it automatically in my aspect.

**Comment by akramwahid** [comment]
I understand the query and you are correct @rs-sliske , since the documentation doesn't mention anything about this, the framework must handle it automatically in my aspect.

**Comment by mfn** [comment]
```php
return $this->registrations()          
            ->where('reg_status','=','Confirmed')
            ->orWhere('reg_status','=','Reserved')
            ->count();
```
Can you create a dump of the actual query? @rs-sliske probably is right, but it would help to have this confirmed.

Can you try as a workaround to add explicit grouping and see if it works?

```php
<?php
return $this
    ->registrations()
    ->where(function (Builder $query): void {
        $query
            ->where('reg_status', '=', 'Confirmed')
            ->orWhere('reg_status', '=', 'Reserved');
    })
    ->count();

```

**Comment by rs-sliske** [comment]
i understand your point, but tbh i would expect the "fix" here to be a warning in the docs about using or without grouping explicitly

**Comment by akramwahid** [comment]
@mfn , it works fine when I do explicit grouping or `whereIn` , here is the query when I donot explicit group it.
`"select count(*) as aggregate from `events_registration` where (`events_registration`.`event_id` = ? and `events_registration`.`event_id` is not null and `reg_status` = ? or `reg_status` = ?) and `events_registration`.`deleted_at` is null " `

**Comment by akramwahid** [comment]
@rs-sliske check my query dump above, in my aspect framework should group custom query contains to separate, as in my second example. however warning in documents also fine,  but beginners of laravel will surely face hard time to understand what is going on

**Comment by rs-sliske** [comment]
im looking to see what changes would be required but dont have much time now :(

**Comment by driesvints** [comment]
Heya, unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.
