### ISSUE TITLE
Add incorrect field to model in storage after touching her

### ISSUE THREAD

**Issue by Smolevich** [laravel/framework#27791]
- Laravel Version: 5.8.2
- PHP Version: 7.3.2
- Database Driver & Version: mongodb

I use library https://github.com/jenssegers/laravel-mongodb and if model was touched by method `touch` in collection to document will added new field `collection_name.updated_at` and original field `updated_at` stay with old value. Broken commit https://github.com/laravel/framework/commit/6484744326531829341e1ff886cc9b628b20d73e. 

### Steps To Reproduce:
Create model, save her, and touch after . Example in tests https://github.com/laravel/framework/blob/e6c8aa0e39d8f91068ad1c299546536e9f25ef63/tests/Database/DatabaseEloquentIntegrationTest.php#L1319

**Comment by mfn** [comment]
Isn't this an issue with the _other_ package, i.e. see https://github.com/jenssegers/laravel-mongodb/issues/1720 ?

**Comment by Smolevich** [comment]
> Isn't this an issue with the _other_ package, i.e. see [jenssegers/laravel-mongodb#1720](https://github.com/jenssegers/laravel-mongodb/issues/1720) ?

Package jenssegers/laravel-mongodb inherits all parts of eloquent models, that i think to fix this problem in laravel

**Comment by rennokki** [comment]
@mfn AFAIK this is the line that is executed before the whole thing collapse:

https://github.com/mongodb/mongo-php-library/blob/1.4.2/src/Operation/Update.php#L179

**Comment by driesvints** [comment]
Seems like this needs to be fixed upstream.

**Comment by Smolevich** [comment]
@driesvints, what do you mean under upstream?

**Comment by driesvints** [comment]
At https://github.com/jenssegers/laravel-mongodb

**Comment by Smolevich** [comment]
@driesvints, What is reason this [changes]?(https://github.com/laravel/framework/commit/6484744326531829341e1ff886cc9b628b20d73e)
Am I to understand that library [laravel-mongodb]( https://github.com/jenssegers/laravel-mongodb) in cases broken changes must redefine parent methods of laravel eloquent entities?

**Comment by driesvints** [comment]
Here's the PR: https://github.com/laravel/framework/pull/26997
