### ISSUE TITLE
Class validator does not exist

### ISSUE THREAD

**Issue by SuperlativeEntity** [laravel/framework#27804]
- Laravel Version: 5.8.3
- PHP Version: 7.1.7
- Database Driver & Version:  mysql-5.7.19-winx64

### Description:
Class validator does not exist {"exception":"[object] (ReflectionException(code: -1): Class validator does not exist

### Steps To Reproduce:
create app/Validators folder
create file CompanyRegistrationNumberValidator.php
add code

```php
<?php

namespace App\Validators;

class CompanyRegistrationNumberValidator
{
    public static function validate($attribute, $value, $parameters)
    {
        return (preg_match('#^\d{4}/\d{6}/\d{2}$#', $value) === 1);
    }
}
```

go to app\Providers\AppServiceProvider.php

add

```php
use Illuminate\Support\Facades\Validator;
```

in

```php
public function register()
```

add

```php
Validator::extend('company_reg_no','App\Validators\CompanyRegistrationNumberValidator@validate');
```

run 

composer dump-autoload

> [2019-03-06 22:00:15] local.ERROR: Class validator does not exist {"exception":"[object] (ReflectionException(code: -1): Class validator does not exist at \\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php:794)

```
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In Container.php line 794:

  Class validator does not exist


Script @php artisan package:discover --ansi handling the post-autoload-dump even
t returned with error code 1
```

**Comment by X-Coder264** [comment]
Don't put the `Validator::extend` line in the `register` method, put it in the `boot` method. Your service provider obviously gets executed before the `ValidationServiceProvider` provider and at that time there is nothing in the container under the "validator" key. By placing it into the `boot` method (which is executed after all providers `register` method gets executed) you are sure that everything you need (in this case the validator) is registered in the container.

**Comment by tjhunkin** [comment]
Thanks, will try that. With all the previous versions of Laravel, this worked without an issue, very odd
