### ISSUE TITLE
Composite unique field validation rule only returns error message for the last field being evaluated

### ISSUE THREAD

**Issue by lasseeee** [laravel/framework#27803]
- Laravel Version: 5.7.17
- PHP Version: 7.3.2
- Database Driver & Version: MySQL 5.7.25

### Description:
When creation a form request object with a composite unique validation rules like this:

```
            'name' => [
                Rule::unique('participants')->where(function ($query) {
                    $query->where('country_code', $this->country)
                        ->where('birth_year', $this->birth_year)
                        ->where('location', $this->location);
                }),
            ],
            'country_code' => [
                Rule::unique('participants')->where(function ($query) {
                    $query->where('name', $this->name)
                        ->where('birth_year', $this->birth_year)
                        ->where('location', $this->location);
                }),
            ],
            'birth_year' => [
                Rule::unique('participants')->where(function ($query) {
                    $query->where('country_code', $this->country)
                        ->where('name', $this->name)
                        ->where('location', $this->location);
                }),
            ],
            'location' => [
                Rule::unique('participants')->where(function ($query) {
                    $query->where('country_code', $this->country)
                        ->where('birth_year', $this->birth_year)
                        ->where('name', $this->name);
                }),
            ],
```
and with corresponding form fields, the validation error message only shows for the last field in the validation list, `location` in this case. It should really display the unique validation error message for all the fields in the form, when they are attached to the fields using `$errors->first('field_name')`, not only the last one being evaluated. Is this intended behaviour?

### Steps To Reproduce:
Create a form object like the one above with corresponding form fields, add per-field validation messages and submit the form.

**Comment by driesvints** [comment]
Heya, unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.
