### ISSUE TITLE
Redirect is slow in laravel

### ISSUE THREAD

**Issue by TeslaITIR** [laravel/framework#27811]
- Laravel Version: 5.4
- PHP Version: 7.2.9
- Database Driver & Version: mysql

Hi
I want redirect page when user click on the send button and data is submitted. I do that with Laravel but in my codes redirect is doing very slow and it takes a few seconds while I want to be done immediately.

My codes:

web.php:
```
Route::get('/', 'ArticleController@index')->name('article.index');
Route::get('article/create', 'ArticleController@createView');
Route::post('article/create', 'ArticleController@create')->name('article.create');
```
ArticleController.php:
```
<?php

namespace App\Http\Controllers;

use App\Article;
use App\Http\Requests\ArticleRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\Facades\Validator;

class ArticleController extends Controller
{
    public function index()
    {
        $articles = Article::latest()->take(10)->get();
        return view('articles.index', compact('articles'));
    }

    public function createView()
    {
        return view('articles.create');
    }

    public function create(ArticleRequest $request)
    {

        Article::create([
            'user_id' => 1,
            'title' => $request->input('title'),
            'body' => $request->input('body')
        ]);

        return redirect('/');
    }
}
```
My form HTML code:
```
<form method="post" action="{{ route('article.create') }}">
    {!! csrf_field() !!}
    <div class="form-group">
		<label for="title">Title:</label>
		<input type="text" class="form-control" name="title" id="title" placeholder="Title...">
    </div>
    <div class="form-group">
		<label for="body">Text</label>
		<textarea class="form-control text-justify space-normal" name="body" id="body" placeholder="Text..." rows="15"></textarea>
	</div>
    <button class="btn btn-primary" type="submit">Send</button>
</form>
```

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
