### ISSUE TITLE
[5.8] config will loos PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT value

### ISSUE THREAD

**Issue by ac1982** [laravel/framework#27815]
- Laravel Version: 5.8.3
- PHP Version: 7.2.16
- Database Driver & Version: MySQL 5.7.24

### Description:
database config file will filter ```\PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => false```, in some case that would a important attribute must to pass.

### Steps To Reproduce:
just connect a self-sign server.

### Maybe
```
 'options' => extension_loaded('pdo_mysql') ? [
               \PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => false,
            ] : [],
```

**Comment by driesvints** [comment]
You can just edit this file in your own project if you like.
