### ISSUE TITLE
Session sharing on multiple logged-in users

### ISSUE THREAD

**Issue by ionesculiviucristian** [laravel/framework#27810]
- Laravel Version: 5.7
- PHP Version: 7.2

### Description:
Hi. I have a strange problem with multiple users logging-in in the same network on a custom Laravel application (different users on different pcs on the same network.). After the second user has logged in, the first user appears as logged in as the second. The application is hosted online, not local.

Sessions are written to files.

**Comment by laurencei** [comment]
> Sessions are written to files.

Can you try a different driver?

**Comment by driesvints** [comment]
Heya, unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.

**Comment by ionesculiviucristian** [comment]
I think that this behaviour is present from at least version 5.2 (first time I saw it), but I'll tests it with 5.8.

**Comment by brada1703** [comment]
@ionesculiviucristian , did you ever figure out what the problem was?

**Comment by brada1703** [comment]
> I think that this behaviour is present from at least version 5.2 (first time I saw it), but I'll tests it with 5.8.

I am having the same problem in 6.2
