### ISSUE TITLE
attachment is sent as email body when body is blank

### ISSUE THREAD

**Issue by byteasc** [laravel/framework#27818]
- Laravel Version: 5.7.26
- PHP Version: 7.1.18

### Description:

When sending an email with an attachment (pdf in this case), it gets sent as the email body versus being an actual attachment. 

It previously worked in 5.5 without any changes and there are noted changes in Mailer that should've affected this, that I can see.

### Steps To Reproduce:

`Mail::send('emails.html', ['html' => $variables['htmlContent']], function ($message) use ($variables) {
                $message->from($variables['from'], $variables['sender'] ?: null);
                $message->replyTo($variables['replyTo'], null);
                $message->to($variables['to'], $variables['recipient'] ?: null);
                $message->subject($variables['subject']);`

This is how we were sending emails before, with no issues previously.

Our current workaround involves setting $htmlContent to what we have in the text body. It isn't as pretty in all cases so we'd like to avoid having to do that, if we can figure out what needs to change.

`if ($htmlContent === "") {
            $htmlContent = $textContent;
        }
`

This looks like it has been reported previously in https://github.com/laravel/framework/issues/19837 but it was closed without a viable resolution

**Comment by driesvints** [comment]
Please see https://github.com/laravel/framework/issues/23580 & https://github.com/laravel/framework/issues/19837
