### ISSUE TITLE
Illuminate/Database/QueryException with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tittle' in 'field list' (SQL: insert into `posts` (`tittle`, `body`, `updated_at`, `created_at`) values (Post one, This is the body of post, 2019-03-07 09:52:15, 2019-03-07 09:52:15))'

### ISSUE THREAD

**Issue by wakaflorien** [laravel/framework#27812]
- Laravel Version: 5.7
- PHP Version:7.3.1
- Database Driver & Version:

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
