### ISSUE TITLE
Documentation issues removed

### ISSUE THREAD

**Issue by kevinfoley** [laravel/framework#27823]
When creating a new issue, there is a "Documentation" option. When this option is selected, the following message appears:
> For documentation issues, see: https://github.com/laravel/docs/issues

It looks like someone disabled issues on the documentation repo (strange, because they were there a few days ago), so this link now takes you to Pull Requests instead.

**Comment by driesvints** [comment]
Heya, thanks for pointing this out. I've made a pr to correct this: https://github.com/laravel/framework/pull/27830

We've closed the issue tracker because the time to make an issue is usually as much work as simply sending in a PR, especially since you can edit the files directly in Github.

**Comment by kevinfoley** [comment]
@driesvints The people who are reading the documentation carefully enough to notice mistakes are probably those who are not already experts in Laravel. They may notice mistakes or find confusing passages, but are not as qualified to fix those issues in the documentation. Issues are a great way for those less experienced developers to bring the documentation issues to the attention of experts who can fix them, because those experts probably aren't reading the documentation carefully (if at all) since they already know the information contained in the docs.

**Comment by driesvints** [comment]
Sorry but our decision on this is final. If you can create an issue on Github it shouldn't be too hard to figure out how to edit a file on Github and send in a PR.

**Comment by kevinfoley** [comment]
@driesvints  I think you misunderstood what I'm saying. I agree that it isn't difficult to edit a file on GitHub and send a PR. My concern is that people who are reading the documentation and noticing mistakes may not know the Laravel framework well enough to edit the documentation accurately. 
Someone reading the documentation carefully probably isn't an expert in the framework. They might notice a mistake but not be sure how to correct it - not that they don't understand how to make a PR, but they lack the knowledge of the Laravel framework to replace the inaccurate or confusing information with accurate/straightforward information.

**Comment by driesvints** [comment]
I'm sorry but like I said before, our decision on this is final. We've been over this back and forth many times in the past. As maintainers of this project we've decided that this is the best way for us to go forward.

If you have a concern with the docs, ask a question on a support channel, discuss it there and then submit a PR when you're decided on the correct course of action or just open up a PR with a suggested change.
