### ISSUE TITLE
[Documentation] Inconsistent use of middleware groups

### ISSUE THREAD

**Issue by kevinfoley** [laravel/framework#27824]
The [Middleware docs ](https://laravel.com/docs/5.8/middleware)show middleware groups used like this:

    Route::group(['middleware' => ['web']], function () {
        //
    });

But the [Routing docs ](https://laravel.com/docs/5.8/routing)show it used like this:

    Route::middleware(['first', 'second'])->group(function () {
        //
    });

This is confusing. Which syntax is preferred?

**Comment by koenhoeijmakers** [comment]
I use the latter, but either is fine.

**Comment by ManojKiranA** [comment]
If you want to use multiple middlewares for the same route 

```
Route::middleware(['first', 'second'])->group(function () {
    //
});
```

Or if you are using only single middleware 

```
Route::group(['middleware' => ['one']], function () {
    //
});
```

**Comment by driesvints** [comment]
Please send in a PR instead of opening an issue.

**Comment by kevinfoley** [comment]
@driesvints  I can't send a PR because I don't know the framework well enough to know exactly what change to make to the documentation. If I already intimately knew this stuff, I probably wouldn't be reading the documentation in the first place, and wouldn't have noticed the inconsistency.

ManojKiranA's answer seems wrong to me; both syntaxes include an array of middleware, so presumably both support multiple middlewares.

**Comment by driesvints** [comment]
@kevinfoley please use one of the following support channels to ask questions and keep only use this issue tracker for reporting bugs:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

**Comment by kevinfoley** [comment]
@driesvints I'm not asking a support question; I'm pointing out an area where the documentation is confusing and would benefit from an expert taking a couple of minutes to improve it. Going on a forum to ask a question only helps me. Making the documentation clearer benefits _every single person who reads the documentation in the future._
