### ISSUE TITLE
[5.8] PHP Fatal error:  Uncaught ReflectionException: Class request does not exist

### ISSUE THREAD

**Issue by tjipkloosterman** [laravel/framework#27837]
- Laravel Version: 5.8
- PHP Version: 7.2
- Database Driver & Version:

### Description:
i got this error after upgrading from 5.7 to 5.8  when autodiscoverpackages was running in putty.

Here is the stacktrace:

> Illuminate\Foundation\ComposerScripts::postAutoloadDump
 > @php artisan package:discover
 PHP Fatal error:  Uncaught ReflectionException: Class request does not exist in C:\Users\Tjip\Desktop\Nieuwe map (3)\premiumplus\vendor\laravel\framework\src\Illuminate\Container\Container.php:794
 Stack trace:
 #0 C:\Users\Tjip\Desktop\Nieuwe map (3)\premiumplus\vendor\laravel\framework\src\Illuminate\Container\Container.php(794): ReflectionClass->__construct('request')
 #1 C:\Users\Tjip\Desktop\Nieuwe map (3)\premiumplus\vendor\laravel\framework\src\Illuminate\Container\Container.php(671): Illuminate\Container\Container->build('request')
 #2 C:\Users\Tjip\Desktop\Nieuwe map (3)\premiumplus\vendor\laravel\framework\src\Illuminate\Container\Container.php(619): Illuminate\Container\Container->resolve('request', Array)
 #3 C:\Users\Tjip\Desktop\Nieuwe map (3)\premiumplus\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(757): Illuminate\Container\Container->make('request', Array)
 #4 C:\Users\Tjip\Desktop\Nieuwe map (3)\premiumplus\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php(121): Illuminate\Foundat in C:\Users\Tjip\Desktop\Nieuwe map (3)\premiumplus\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 794
 Script @php artisan package:discover handling the post-autoload-dump event returned

This only happens when i upgrade from 5.7 to 5.8.

I reverted it back to 5.7 for now.

### Steps To Reproduce:

upgrade from 5.7 to 5.8.

**Comment by staudenmeir** [comment]
Can you upload your `composer.lock` file before the upgrade?

**Comment by tjipkloosterman** [comment]
[composer.lock.zip](https://github.com/laravel/framework/files/2948518/composer.lock.zip)

**Comment by staudenmeir** [comment]
Sorry, I also need the `composer.json` file.

**Comment by tjipkloosterman** [comment]
> Sorry, I also need the `composer.json` file.

[composer.zip](https://github.com/laravel/framework/files/2948573/composer.zip)

**Comment by staudenmeir** [comment]
I can successfully upgrade a Laravel 5.7 installation with these Composer files.

Does putting `dd($exception);` in `App\Exceptions\Handler::report()` give you a better error message?

**Comment by tjipkloosterman** [comment]
> dd($exception);

This did the trick! it gave me a better error message and i was able to fix the **"local" issue**.

DotEnv came with a new version and added a  ::create() method and my code still used the constructor, i changed my code and i was able to upgrade to 5.8!

Thank you very much :) @staudenmeir

**Comment by abrahim9t5** [comment]
Hello I am also facing this issue, my env file is fine, i cant find what can cause the error.
This is the Error
2019/08/10 21:33:09 [error] 13633#13633: *234 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ReflectionException: Class log does not exist in /usr/share/nginx/html/shape-web/vendor/laravel/framework/src/Illuminate/Container/Container.php:734
Stack trace:
#0 /usr/share/nginx/html/shape-web/vendor/laravel/framework/src/Illuminate/Container/Container.php(734): ReflectionClass->__construct('log')
#1 /usr/share/nginx/html/shape-web/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build('log', Array)
#2 /usr/share/nginx/html/shape-web/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('log', Array)
#3 /usr/share/nginx/html/shape-web/vendor/laravel/framework/src/Illuminate/Container/Container.php(849): Illuminate\Foundation\Application->make('log')
#4 /usr/share/nginx/html/shape-web/vendor/laravel/framework/src/Illuminate/Container/Container.php(804): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /usr/share/nginx/html/shape" while reading response header from upstream, client: 182.181.214.60, server: haq.shapere.com, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "haq.shapere.com"

**Comment by devcircus** [comment]
Either .env or one of your config files.

**Comment by chigbo12345** [comment]
you can use composer dump-autoload . It should work.

**Comment by luciandex** [comment]
This error shows up (for me) after run `bin/magento setup:di:compile` command, and after that `composer dump-autoload`.

I recomend to (re)run the following commands:
`bin/magento deploy:mode:set developer`
`bin/magento c:c` (shorthand for cache:clear)

I hope someone find this helpful.
