### ISSUE TITLE
Job run many times.

### ISSUE THREAD

**Issue by AsemAlalami** [laravel/framework#27832]
- Laravel Version: 5.8.3
- PHP Version: 7.2
- Database Driver & Version: mysql
- Horizon: 3.0.3 (redis) 
- Homestead

### Description:
I notice that the jobs still running without finished.
For example:

- If assign `$tries` more than one time the job will still running more times or
- If assign `$timeoutAt` to specific time and `$tries` to one time,  the job will still running more times until `timeoutAt` time exceeded.

### Steps To Reproduce:

I think the problem in `markJobAsFailedIfAlreadyExceedsMaxAttempts` in `Worker`:

        if ($timeoutAt && Carbon::now()->getTimestamp() <= $timeoutAt) {
             return;
        }

        if (! $timeoutAt && ($maxTries === 0 || $job->attempts() <= $maxTries)) {
            return;
        }

The check separately on `timeoutAt` and `maxTries` .

if check it together we will avoid this problem.

**Comment by ahinkle** [comment]
Can you replicate this problem and provide instructions from a fresh Laravel installation?

**Comment by ahinkle** [comment]
Can you reproduce this problem from a fresh Laravel installation?

**Comment by driesvints** [comment]
I'll need more info and/or code to debug this further. Please post relevant code like models, jobs, commands, notifications, events, listeners, controller methods, routes, etc. You may use https://paste.laravel.io to post larger snippets or just reply with shorter code snippets. Thanks!

**Comment by AsemAlalami** [comment]
Thanks for replay.
I solve this problem by increase `retry_after` on `queue` config file.
But how to assign `retry_after` for every job separately(per job)?

**Comment by driesvints** [comment]
The `retry_after` is set on your connector, not your job so this can't be done on a job-level.

**Comment by fernandocoronatomf** [comment]
@driesvints Yeah, I figure this out today while trying to implement retry_after per job.
Do you guys plan to add this at a per job-level?
It would be really helpful because right now I have to create 3 different connections using database driver with different retry_after values.
