### ISSUE TITLE
[5.7] TTFB increase when using magic methods in Eloquent

### ISSUE THREAD

**Issue by tjipkloosterman** [laravel/framework#27838]
I found something interesting regarding Eloquent models and how calling relationships affects the TTFB.

My page was loading soooo slow, while others did not.
So i kinda debugged my code en then i found this situation:

```        
// TTFB 1.5sec
//  $options = $company->companies->mapWithKeys(function ($item, $key) {
//      return [$item->id => $item->name];
// });

// While TTFB in this case is < 200ms
$options = $company->companies()->get()->mapWithKeys(function ($item, $key) {
    return [$item->id => $item->name];
});

return view('page', compact('options'));
```

What is the difference between the two? and why does it affect TTFB so dramatically (in my case)?

**Server config:**

PHP 7.2.15-0ubuntu0.18.04.1 (cli) (built: Feb  8 2019 14:54:22) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.15-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans

**Comment by dwightwatson** [comment]
Have you profiled this properly and confirmed the difference is consistent and substantial? You've mentioned that one way is < 200ms but given no indication what speeds the alternative is producing.

**Comment by it-can** [comment]
Also try without xdebug activated

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Also: please don't ignore the issue template.

**Comment by X-Coder264** [comment]
@tjipkloosterman Is the `companies` relationship eager-loaded?
