### ISSUE TITLE
Invalid datetime format: 1292 Incorrect datetime value: '2019-03-10 02:40:23' for column 'updated_at'

### ISSUE THREAD

**Issue by kjjdion** [laravel/framework#27841]
Why am I suddenly getting this?

> Invalid datetime format: 1292 Incorrect datetime value: '2019-03-10 02:40:23' for column 'updated_at'

Literally just calling: `User::create(request()->all())`;

I'm assuming it has something to do with DST?

**Comment by kjjdion** [comment]
App timezone was set to `UTC` and my region of the world just experienced daylight saving change, so the date does not actually exist yet.

Just in case anyone runs into same issue.

**Comment by mfn** [comment]
> App timezone was set to `UTC` and my region of the world just experienced daylight saving change, so the date does not actually exist yet.

I your database default timezone by chance set to your local region?

**Comment by kjjd84** [comment]
> App timezone was set to `UTC` and my region of the world just experienced daylight saving change, so the date does not actually exist yet.

yeah just experienced this,

adding this to my db config for mysql fixed it:

```php
'timezone' => '+00:00',
```
