### ISSUE TITLE
Resource controller supplementation works incorrectly

### ISSUE THREAD

**Issue by andrewgorpenko** [laravel/framework#27846]
- Laravel Version: 5.8.2
- PHP Version: 7.3
- Database Driver & Version: not needed

### Description:
I'd like to describe a bug that I found today.
As we all know, we can add custom routes to an existing resource controller. This feature works correctly except one specific case: when you use custom POST route with an explicit url parameter and try to visit the route(I mean GET the page), Laravel does not throw `MethodNotAllowedHttpException`. Instead it thows 404 HTTP error.

### Steps To Reproduce:
1. Create the resource controller.
2. Add a custom POST route with an explicit url parameter. Here is the example code:
```
Route::post('orders/{order}/paymentResult', 'OrderController@processPaymentResult')
Route::resource('orders', 'OrderController');
```
3. Visit the custom route url.

### Expected
`MethodNotAllowedHttpException` error.

### Actual
404 error page

_P.S. Interesting fact: if I remove resource controller call in the `routes.php` file, then the custom route works as it should be (goes to controller's method when I make POST request and throws `MethodNotAllowedHttpException` if I make GET request)._

### Update [2019-03-10 23:26]
Monitoring the same effect even without an explicit url parameter.

**Comment by staudenmeir** [comment]
It works for me. Can you reproduce this on a fresh installation of Laravel?

**Comment by jmarcher** [comment]
Are your trying to access a `POST` route with your browser? This generates a `GET` request try using a tool like Postman and send a proper `POST` request.

**Comment by andrewgorpenko** [comment]
@jmarcher, I know that visiting a page via a browser makes `GET` request and I should have got the exception about invalid method usage, instead I get 404.
@staudenmeir, my app is almost clean, except 1 custom controller.

**Comment by setkyar** [comment]
@andrewgorpenko You describe like `Visit the custom route url.` which one is your custom URL?

**Comment by andrewgorpenko** [comment]
Obviously this one:
`Route::post('orders/{order}/paymentResult', 'OrderController@processPaymentResult')`

**Comment by jmarcher** [comment]
Well, how is your URL structured? `orders/1/paymentResult`? does an Order with id 1 exists in the database?

**Comment by andrewgorpenko** [comment]
Laravel should interrupt the request because of invalid method usage. This expected behavior occurs when I remove resource controller call from the routes.php file.

**Comment by driesvints** [comment]
Please post:

- Your `web.php` routes file
- Your `OrderController`

**Comment by andrewgorpenko** [comment]
`web.php`:
```php
Route::post('orders/paymentResult', 'OrderController@paymentResult')->name('orders.paymentResult'); 
Route::resource('orders', 'OrderController')->only([
    'index', 'show', 'paymentResult'
]);
```
`OrderController.php`:
```php
<?php

namespace App\Http\Controllers;

use App\Models\Order;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class OrderController extends Controller
{
    /**
     * Instantiate a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth')->except('show', 'paymentResult');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = request()->user()->orders()->get();

        return view('shop.orders.index')->with('orders', $orders);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Order $order
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function show(Order $order)
    {
        if (Auth::check() && !is_null($order->user_id)) {
            $this->authorize('view', $order);
        }

        return view('shop.orders.view')->with('order', $order);
    }

    /**
     * Process the payment result.
     *
     * @param Request $request
     */
    public function paymentResult(Request $request) {
        dd($request->all());
    }
}
```

When I visit `orders/paymentResult` route, it shows 404. However, if I remove `Route::resource` call, then I get `MethodNotAllowedHttpException` as expected.

**Comment by driesvints** [comment]
Your `orders/paymentResult` route is a POST, not a get. Your resource route adds a `GET orders/{id}` route because of the `show` in the `only` and can't find a order for the id of `paymentResult` so it's a 404. `paymentResult` isn't a valid resource name so it throws the `MethodNotAllowedHttpException`.
