### ISSUE TITLE
Laravel error in login route when the user is authenticated

### ISSUE THREAD

**Issue by Noryad** [laravel/framework#27840]
- Laravel Version: 5.6.5
- PHP Version: 7.1.9
- Database Driver & Version: MySQL 5.7.19

### Description:
`Trying to get property of non-object' in '…\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php 158` 

### Steps To Reproduce:
Simply use the login route when the user has already logged in.
Please do not redirect me to a forum because I already did it and I can not find answers.
Thanks in advance.

**Comment by staudenmeir** [comment]
Are you using custom middleware in `App\Http\Kernel`?

**Comment by Noryad** [comment]
[Kernel.php.txt](https://github.com/laravel/framework/files/2948996/Kernel.php.txt)
This is my Kernel.php

**Comment by staudenmeir** [comment]
Can you reproduce this on a fresh installation of Laravel 5.6?

**Comment by driesvints** [comment]
Heya, unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.
