### ISSUE TITLE
Mail::fake() doesn't detected Mails sent by Notification

### ISSUE THREAD

**Issue by flexchar** [laravel/framework#27848]
- Laravel Version: >5.7
- PHP Version: >7.2
- Database Driver & Version: Not appliciable 

### Description:
When testing that Notification sends an email with `Mail::fake()`, `Mail::assertSent()` won't detect a send email, although actually it does work. Note that case is the same with `Mail::assertQueued()`.

Example repository is set up to do the same when visiting the root page and when running test. The same logic is executed, however, the test won't pass.

I am sorry for unclear commit history, forgot to initialize repo before the first commit. :(

### Steps To Reproduce:
1. Clone [laravel_mail_testing_issue](https://github.com/flexchar/laravel_mail_testing_issue) repository
2. Install PHP Dependencies: `composer install`
3. `php artisan serve` and visit http://localhost:8000/
    - verify that mailable was sent clicking on FAKE INBOX link `optional`
5. Run `vendor/bin/phpunit` and see test failing

**Comment by driesvints** [comment]
I'll need more info and/or code to debug this further. Please post relevant code like models, jobs, commands, notifications, events, listeners, controller methods, routes, etc. You may use https://paste.laravel.io to post larger snippets or just reply with shorter code snippets. Thanks!

**Comment by Kyslik** [comment]
I think your example fails because of: [`return (new FakeMailable())->to($notifiable->routes['mail']);`](https://github.com/flexchar/laravel_mail_testing_issue/blob/master/app/Notifications/SendEmailNotification.php#L41-L45); eg. not using facade but `new`.

**Comment by driesvints** [comment]
Sorry, didn't see you posted an example repo. I think @Kyslik is correct. Can you try with the facade instead?

**Comment by Kyslik** [comment]
That won't work either; you need to test those two separately... emitting notification and then sending (queuing) the email itself.

Obviously you can test that notification (fake) has an email object.
---

If you want it to be integration test (integration of notification and email together) you just test end result - email as queued and not the notification...

This is not a bug and should be further consulted on SO, can be closed.

**Comment by flexchar** [comment]
@Kyslik I see. 

> I think your example fails because of: `return (new FakeMailable())->to($notifiable->routes['mail']);`; not using facade but `new`.

Your first reply sounds reasonable, however, it somewhat goes against [documentation](https://laravel.com/docs/5.8/notifications#mail-notifications), which, as written, requires for a mailable to be returned. 

Splitting into many tests, when notification's sole purpose is to send specific mailable, seems a bit of overkill. Could you share an example of how would you _test end result - email is queued and not the notification_ ?

**Comment by Kyslik** [comment]
(Assumption - If all fakes work the same then) Fakes do not run the handle function; fakes just store object(s) so you can assert against them.

Test the notification and check that it has proper properties maybe email class etc.

If that does not help, do ask on SO instead of here. Feel free to link this thread in SO question.

Best,
Kyslik

**Comment by Kyslik** [comment]
(Assumption - If all fakes work the same then) Fakes do not run the handle function; fakes just store object(s) so you can assert against them.


Test the notification and check that it has proper properties maybe email class etc.


If that does not help, do ask on SO instead of here. Feel free to link this thread in SO question.

Best,
Kyslik

**Comment by flexchar** [comment]
@Kyslik Understood. What do you refer by _do ask on SO_ ?

**Comment by Kyslik** [comment]
@flexchar Sorry; StackOverflow it is.
