### ISSUE TITLE
Reduce does not work with chunk

### ISSUE THREAD

**Issue by janbodnar** [laravel/framework#27844]
- Laravel Version: 5.8.3
- PHP Version: 7.2.11

### Description:

I have an example where I use reduce with chunk. In the second call,
the computation is `1*2 + 3*4 + 5*6`, which should give 44. It gives 2.

I have worked with `Collect.js`which is a port of Laravel's collections, where
it works OK.

### Steps To Reproduce:

```
$nums = [1, 2, 3, 4, 5, 6];

$data = collect($nums);

$val = $data->reduce(function($c, $e) { return $e += $c; });
dump($val);

$val2 = $data->chunk(2)->reduce(function($c, $e) { 
    // echo $e->get(0) . "\n";
    // echo $e->get(1) . "\n";
    return $c + $e->get(0) * $e->get(1);
}, 0);

dump($val2);
```

**Comment by staudenmeir** [comment]
Your code doesn't work because the keys `0` and `1` only exist in the first sub-collection:

```php
Collection {#236 ▼
  #items: array:3 [▼
    0 => Collection {#227 ▼
      #items: array:2 [▼
        0 => 1
        1 => 2
      ]
    }
    1 => Collection {#235 ▼
      #items: array:2 [▼
        2 => 3
        3 => 4
      ]
    }
    2 => Collection {#228 ▼
      #items: array:2 [▼
        4 => 5
        5 => 6
      ]
    }
  ]
}
```

Use `first()` and `last()` instead:

```php
$val2 = $data->chunk(2)->reduce(function($c, $e) { 
    return $c + $e->first() * $e->last();
}, 0);
```

If the sub-collections contain more than two values, you'll need to use a nested `reduce()`.

**Comment by janbodnar** [comment]
OK, I got it. Thanks for clarification.
