### ISSUE TITLE
Calling migrate:fresh on a prefixed connection drops all tables, irrespective of prefix

### ISSUE THREAD

**Issue by chrisforrence** [laravel/framework#27851]
- Laravel Version: 5.8.3
- PHP Version: 7.2.15-0ubuntu0.18.04.1
- Database Driver & Version: MariaDB (10.1.37-MariaDB)

### Description:

I currently have a prefix defined on my default connection since I'm currently sharing a database with another application. When setting up Dusk, I used the DatabaseMigrations trait; unfortunately, that dropped all tables in the database, including the ones that Laravel shouldn't have known about because of the prefix restriction

### Steps To Reproduce:

- Create a new Laravel application
- Define a database connection with a prefix (e.g. `'prefix' => 'foo_',`)
- Manually create the table `bar` on the database (e.g. `CREATE TABLE bar (id TINYINT PRIMARY KEY);`)
- Either...
    - Call `php artisan migrate:fresh`, or
    - Install Dusk, set up a Dusk test that uses the `Illuminate\Foundation\Testing\DatabaseMigrations` trait and run the Dusk test suite (how I originally discovered the behavior)

#### Expected

The tables in the database are `bar`, `foo_migrations`, `foo_users`, and `foo_password_resets`.

#### Actual

The tables in the database are `foo_migrations`, `foo_users` and `foo_password_resets`.

**Comment by staudenmeir** [comment]
I would argue that you should only use the testing database for a single application.

Do you *have* to share the database?

**Comment by chrisforrence** [comment]
Allowing a prefix database configuration implies that you're allowing for a database to be shared; while I originally found the issue when using Dusk and testing, I was able to reproduce the behavior without bringing Dusk or testing into the picture. It does get expounded upon when testing, though (particularly with a misconfigured system that caused the tests to be performed on a shared development database, which _was_ my fault)

I think it boils down to, "Should we drop tables that Laravel shouldn't know about?"

**Comment by staudenmeir** [comment]
I would argue that the prefix is basically only meant for production databases where you don't use `DatabaseMigrations` or `php artisan migrate:fresh`.

**Comment by rs-sliske** [comment]
im not sure what other impacts it would have, but it looks like the methods to get all tables could be made to match the prefix.

a work around would be to have a user who only has access to data for that application (i call this a workaround but it should probably be done anyway, even without this issue)

tbh each application should have its own database imo

**Comment by laurencei** [comment]
This is intended and expected behavior.

The mechanism of `migrate:fresh` is to drop all tables on the database, irrespective of any configuration or other options. This would include table prefix's - because there are scenarios where you could configure multiple prefix's etc

If this mechanism does not suit, then you can you `migate:reresh` and include custom `drop()` commands to suit your needs.

**Comment by tontonsb** [comment]
Yesterday I noticed that there is `migrate:fresh -seed` that drops the tables instead of trying to roll back migrations. Oh, cool. So no more problems with changing table names etc. and otherwise migrations becoming unable to be rolled back.

Today I noticed it has wiped all the database, not only the project. Unexpected. Won't use again.

**Comment by t-tomek** [comment]
I've lost my DB the same way....
I think the name `fresh` is misleading (one could use `db:wipe` & `migrate` instead), but `wipe` is kind of strong. One is/should be aware of wiping/deleting **everything**.  With (Re)freshing I've also assumed that prefix would be taken into account (what's more `migrate:refresh` keeps other tables; `migrate:fresh` does not)

@laurencei you should at least add warnings in docs just like with caching

> Flushing the cache does not respect the cache prefix and will remove all entries from the cache.
