### ISSUE TITLE
Illuminate\Cache\FileStore::put() does not check for hash collisions

### ISSUE THREAD

**Issue by yiranzai** [laravel/framework#27854]
version: Laravel 5.5-5.8

Any hash algorithm can hash collisions.

But `Illuminate\Cache\FileStore::put()` does not check for hash collisions

Although the chances are small, is this not a concern?

If a conflict occurs, the latter will replace the former

```
    /**
     * Store an item in the cache for a given number of minutes.
     *
     * @param  string  $key
     * @param  mixed   $value
     * @param  float|int  $minutes
     * @return void
     */
    public function put($key, $value, $minutes)
    {
        $this->ensureCacheDirectoryExists($path = $this->path($key));

        $this->files->put(
            $path, $this->expiration($minutes).serialize($value), true
        );
    }
```

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Also: please don't ignore the issue template.

**Comment by staudenmeir** [comment]
@driesvints I disagree, this is not a support question.

*Accidental* collisions are basically impossible in SHA-1. But still, I think we should consider switching to a modern algorithm like SHA-256 in Laravel 5.9.

**Comment by driesvints** [comment]
Okay but this seems like an improvement so it's best to discuss this in the ideas repo. Feel free to send in a pr to the master branch if you think this can be improved.

**Comment by yiranzai** [comment]
@driesvints @staudenmeir  
Sha-256 is only a lower probability of collision, and theoretically it is possible.
Why don't we use Chaining to solve this problem?
Each hash key stores a bucket, and each bucket has an infinite node.
But as long as there is no collision, there is only one node per bucket, and the impact on efficiency is small.
Just like the hashtable of a php array.

**Comment by yiranzai** [comment]
@driesvints And I don't understand why this issue was closed.

**Comment by staudenmeir** [comment]
*Theoretically*. But even for SHA-1, the probability is so low that an accidental collision will never occur.

**Comment by driesvints** [comment]
@yiranzai this was closed because the current approach works well but it can be _improved_ further. Please discuss this further in the ideas repo and optionally send in a PR if you feel that this can be improved.
