### ISSUE TITLE
Illuminate/Queue silently reschedules existing reserved job when using Redis

### ISSUE THREAD

**Issue by sshilko** [laravel/framework#27862]
- Laravel Version: 5.8
- PHP Version: 7.2.12
- Database Driver & Version:

Redis
phpredis

### Description:
According to current code status queue->later(...) calls zadd via https://github.com/illuminate/queue/blob/master/RedisQueue.php#L123

and 
uniqueness is done by adding id = getRandomId()
https://github.com/illuminate/queue/blob/master/RedisQueue.php#L151

`If a specified member is already a member of the sorted set, the score is updated and the element reinserted at the right position to ensure the correct ordering.
`
**Means in a queue called "myjobs" i can have reserved job A re-scheduled silently for time X2 instead of X1**

### Steps To Reproduce:
```
> ZRANGE myzset 0 -1 WITHSCORES
(empty list or set)
> ZADD myzset 1 "jobdata"
(integer) 1
> ZADD myzset 1 "jobdata"
(integer) 0
> ZADD myzset 2 "jobdata"
(integer) 0
> ZRANGE myzset 0 -1 WITHSCORES
1) "jobdata"
2) "2"

```

**Comment by driesvints** [comment]
I currently don't have the time to deep-dive into this so appreciating any help to investigate this. 

In the meantime: can you add some code which reproduces this? Which **specific** Laravel version are you running this on?

**Comment by sshilko** [comment]
The issue here is when exact payloads are added, the old one gets overwritten. In theory this will happen when random::32 will match in two jobs, or someone will use custom/weak random.

Issue is the framework never warns you about that happened, while there is possibility to do that (rely on zadd response value). Closing as probably not too relevant for real-life codebase.
