### ISSUE TITLE
Auth::viaRemember calls MyNonStatefulGuard::viaRemember

### ISSUE THREAD

**Issue by ya-tmch** [laravel/framework#27866]
- Laravel Version: 5.8.3
- PHP Version: 7.3.2 (cli) (built: Mar  5 2019 01:43:47) ( NTS )

### Description
I have my own implementation of Illuminate\Contracts\Auth\Guard. It does not have a viaRemember method. 
Auth::viaRemember call fails when trying App\Guards\MyNonStatefulGuard->viaRemember().

Why does the Auth::viaRemember method call the viaRemember method in my implementation of Guard, because it does not implement the StatefulGuard interface?

**Comment by driesvints** [comment]
The `Auth` facade is just a proxy to your guard. If your guard doesn't provides the methods then you obviously can't call those through the facade.
