### ISSUE TITLE
Possible input loss with Request::validated call

### ISSUE THREAD

**Issue by ilnicki** [laravel/framework#27873]
- Laravel Version: 5.8.4
- PHP Version: irrelevant

### Description:
Changes made in the formatting [commit](https://github.com/laravel/framework/commit/ad34b8d4eb0d1c76d55ed3173a33f6fa32ead1d4#diff-38fd116b7c7b8ac1bdd8362250d04d57) had introduced some changes besides code beautifying and made possible some input data loss in case if random generated null preserver string will match one of the input values.

It is not the most eventual scenario but still can happen. The worst part of it is the fact that all input data will pass the validation and being considered valid can be used as-is. 
I propose to revert the change cause the stdClass usage in this case introduces no disadvantages but still makes no collision possible.

**Comment by driesvints** [comment]
Which exact version of Laravel are you running. Please don't ignore the issue template and fill it in.

**Comment by ilnicki** [comment]
Let it be 5.8.4. But it also affects any of the 5.7.* releases.

**Comment by driesvints** [comment]
Please post a concrete code example of the problem.

**Comment by ilnicki** [comment]
There is no good way to demonstrate the problem because of random nature of Str::random output and Str static design which makes it not so easy to mock. But I'll try to build the demo asap.

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
