### ISSUE TITLE
BelongsTo.getOwnerKey is now BelongsTo.getOwnerKeyName ?

### ISSUE THREAD

**Issue by stasoft91** [laravel/framework#27884]
Is it just me or you forgot to mention in 5.7 to 5.8 upgrade notes, that you renamed BelongsTo functions like
getOwnerKey to getOwnerKeyName
and
getForeignKey to getForeignKeyName ?

It broke some third-party libraries, you know...

**Comment by staudenmeir** [comment]
This has been fixed. Please close the issue.
