### ISSUE TITLE
Index resource ability mapping missing

### ISSUE THREAD

**Issue by pierlon** [laravel/framework#27888]
- Laravel Version: 5.8.3
- PHP Version: 7.3.3

### Description:
After applying a policy to a resouce controller, I see that it correctly maps the `can` attribute to all the routes except `index`. After reviewing the framework's code, it seems the [mapping has been lost](https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Auth/Access/AuthorizesRequests.php#L108) (can't pinpoint the exact commit it had occurred).

**Comment by devcircus** [comment]
Here’s [Taylors comment](https://github.com/laravel/ideas/issues/772) on removing this. [This](
https://github.com/laravel/framework/commit/d2a41e46949b4cdd45bf0fe3f0fd63dac2ee4858#diff-bb6f96b7b90070077db82955aac3b8a2and) is the commit.

**Comment by pierlon** [comment]
OK thanks for that. I'll just add the mapping to the base controller for now. Perhaps the documentation could be updated to reflect this change then?

**Comment by laurencei** [comment]
Hi there,

If you believe there are still improvements that can be made to the docs, please feel free to submit a PR with the changes to the docs.

Thanks.
