### ISSUE TITLE
API Authentication Not working

### ISSUE THREAD

**Issue by kkcodes** [laravel/framework#27898]
PHP: 7.2.12
Laravel: 5.8.4
DB: MYSQL  5.5.5-10.1.37-MariaDB

I am trying to implement the API authentication. Followed the exact process mentioned [here](https://laravel.com/docs/5.8/api-authentication)

Successfully registered an User via the Registration form and the api_token column has a random token.

Then using postman trying this GET request: `localhost:8000/api/user?api_token=tokenindb`

But, it always returns, 401,

`{
    "message": "Unauthenticated."
}`

Tried the post request, guzzle request, but always getting the same error.

Also, added this to .htaccess, but no luck.

`RewriteEngine On
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]`

Please help.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
