### ISSUE TITLE
wrong locale when using artisan command

### ISSUE THREAD

**Issue by FrancoisDucobu** [laravel/framework#27905]
Hello Everyone,

We are using laravel with laravel-intl package.
We have a strange behavior since then.
I think the problem is not related with the package.

When I use php artisan command, laravel does not read the .env file...

if I put this command on config/app.php just before the return command
`var_dump(env('LANG'));`
On the brower, I see "EN" on the output.
The value sets in the .env file

But when I use "php artisan ..." command, I see "en_US.UTF-8"
The value of the LANG system variable...

Any idea ?
Regards,

Francois

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
