### ISSUE TITLE
ResourceCollection should not have collection static method.

### ISSUE THREAD

**Issue by neyaoz** [laravel/framework#27904]
- Laravel Version: 5.8.4
- PHP Version: 7.2.10
- Database Driver & Version: MySQL 5.7.23

### Description:

`\Illuminate\Http\Resources\Json\JsonResource::collection` static method should not be inherited to `\Illuminate\Http\Resources\Json\ResourceCollection`.

Because it is trying to create a new instance of `\Illuminate\Http\Resources\Json\AnonymousResourceCollection`, with `$resource` (that is the collection) and `static::class` (that is the class extended from`\Illuminate\Http\Resources\Json\ResourceCollection`) arguments. `$resource->mapInto()` is being called for each resource item, and throws an error.

> Call to undefined method App\User::mapInto()

### Steps To Reproduce:

1. Create a new class extended from ResourceCollection.
2. Call collection static method with a user collection.

> UserCollection::collection(User::all());

```php
<?php
declare(strict_types=1);

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laravel\Passport\HasApiTokens;

/**
 * Class User
 *
 * @package App
 */
class User extends Authenticatable
{
    use HasApiTokens, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}
```

```php
<?php
declare(strict_types=1);

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

/**
 * Class User
 *
 * @package App\Http\Resources
 */
class User extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request): array
    {
        return [
            'name' => $this->name,
        ];
    }
}
```

```php
<?php
declare(strict_types=1);

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\ResourceCollection;

/**
 * Class UserCollection
 *
 * @package App\Http\Resources
 */
class UserCollection extends ResourceCollection
{
    /**
     * Transform the resource collection into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'data' => $this->collection,
            'links' => [
                'self' => 'link-value',
            ],
        ];
    }
}
```

```php
Route::get('/test', function () {
    return App\Http\Resources\UserCollection::collection(App\User::all());
});
```

**Comment by driesvints** [comment]
I can't reproduce this. This works for me. Can you copy/paste the minimum amount of code that's needed to reproduce this?

**Comment by neyaoz** [comment]
@driesvints I have **updated** the issue description. I have just realized that `UserCollection::collection(App\User::all())` returns object tree of `Illuminate\Database\Eloquent\Model` if there is no `App\Http\Resources\User` class defined. 

1. Reproduce https://github.com/laravel/framework/issues/27904#issue-421914884
2. Check the response
3. Delete App\Http\Resources\User
4. Check the response

**Comment by driesvints** [comment]
You're using this wrong. A collection should always have its collection passed to its constructor. The `collection` method is only called on individual resources. You can read up on this here: https://laravel.com/docs/5.8/eloquent-resources#resource-collections

**Comment by neyaoz** [comment]
Of course I am not using it. What am i saying is, it should not be inherited to ResourceCollections. The Resource Collection itself is never using it. And it should not be used by a user as you say.

**Comment by driesvints** [comment]
Yeah, I agree that the inheritance is a bit problematic. We could figure out a way to do this differently.
