### ISSUE TITLE
firstOrCreate continuous insert new entry when inserting into double column 

### ISSUE THREAD

**Issue by Blaack-Jaack** [laravel/framework#27917]
- Laravel Version: 5.8.4
- PHP Version: 7.2.9
- Database Driver & Version:
MariaDB 10.1.26-MariaDB-0+deb9u1 - Debian 9.1 
### Description:
When i change column type to varchar issue doesn't occur.

### Steps To Reproduce:
create model
> php artisan make:model Models/Test -m

edit migrate file
> Schema::create('tests', function (Blueprint $table) {
        $table->bigIncrements('id');
        $table->double('longitude', 9, 4);
        $table->timestamps();
    });

Edit model

> namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class Test extends Model
{
     protected $fillable = ['longitude'];
}

Try insert or get 

> $marker = Test::firstOrCreate([
    'longitude' => floatval(19.9276),
]);
echo $marker->id;

I get new id all the time

**Comment by driesvints** [comment]
I'll need someone else on MariaDB to confirm this.

**Comment by staudenmeir** [comment]
Since float/double values are not precise, it's difficult to query them.

You can cast them to decimal values (https://stackoverflow.com/q/1302243/4848587).

```php
$sql = 'CAST(`longitude` AS DECIMAL(9,4)) = CAST(? AS DECIMAL(9,4))';
$marker = Test::whereRaw($sql, [19.9276])->first();

if (is_null($marker)) {
    $marker = Test::create(['longitude' => floatval(19.9276)]);
}
```

**Comment by driesvints** [comment]
@Blaack-Jaack can you try the example above?

**Comment by Blaack-Jaack** [comment]
@driesvints i try it and works.

The problem occur only with double column type and value 19.9276 (other value works)

When i run 
`$marker = Test::firstOrCreate([
'longitude' => floatval(19.9276),
]);`

laravel generate query 
`select * from `tests` where (`longitude` = 19.9276) limit 1`
and next insert new row and return new id all the time.

When i run the same query 
`select * from `tests` where (`longitude` = 19.9276) limit 1`
in phpmyadmin the existing row i returned.

**Comment by staudenmeir** [comment]
In my tests, three decimal places work, but four don't.

I thought this is related to #23850 and #25818, but using `PDO::PARAM_STR` doesn't fix it either.

**Comment by mfn** [comment]
FWIW I tried it on Postgres, it worked (as per the original descriptions values). However postgres doens't have (or at least: the blueprint doesn't use) the precisions.

**Comment by staudenmeir** [comment]
Weird, other values with four decimal places do work (e.g. `123.4567`).

This is definitely a MySQL/PDO issue and not related to Laravel.

**Comment by driesvints** [comment]
Closing this then because unrelated to Laravel. It might be worth it to post an bug report to PHP issue tracker or MySQL?

**Comment by driesvints** [comment]
@staudenmeir btw, have you tried this on MariaDB? Because it was reported under MariaDB and not MySQL

**Comment by staudenmeir** [comment]
@driesvints Yes, but I accidentally wrote "MySQL".
