### ISSUE TITLE
getenv return false after laravel 5.8 update

### ISSUE THREAD

**Issue by svikramjeet** [laravel/framework#27913]
- Laravel Version: 5.8.4
- PHP Version: 7.2.14
- Database Driver: pgsql

### Description:
If you print getenv after laravel 5.8 update it will return false.

### Steps To Reproduce:
Upgrade laravel to 5.8.4
Edit /config/database.php
Add dd(getenv('DATABASE_URL')); in the database.php
This will print `false` whereas laravle5.7 was showing exact DB url in format:
database://username:password@host:port/database_name

**Comment by driesvints** [comment]
How have you defined this in your `.env` file? Have you read the changes in https://laravel.com/docs/5.8/upgrade and https://github.com/vlucas/phpdotenv/blob/master/UPGRADING.md ?

**Comment by svikramjeet** [comment]
driesvints : Yes DATABASE url  is in .env as i haven't update .env file which was working fine in 5.7.I have gone through the changes as well but i haven't fountd any updates regarding getenv() as this is php method not laravel which i think should not be impacted while laravel upgrade.

**Comment by xuanquynh** [comment]
Laravel 5.8 will only load environment variables into $_SERVER and $_ENV. It doesn't write into the computer system anymore. That is why the `getenv` function returns `false` this situation. It's a breaking change, not a bug.

Do not use the `getenv` PHP native function, use `env` helper instead!

https://github.com/laravel/framework/pull/27462
https://github.com/laravel/framework/pull/27519

**Comment by svikramjeet** [comment]
Thanks @xuanquynh .

**Comment by mfn** [comment]
@AndyMac2508 would you mind exposing the packages? Could be useful for others to learn about them before going to 5.8

**Comment by AndyMac2508** [comment]
the main one we had an issue with was https://github.com/aws/aws-sdk-php the other ones where internal packages we use.

**Comment by nomad-software** [comment]
@taylorotwell I can't reply to you in the issue you replied to as it's been locked: https://github.com/laravel/framework/issues/27949#event-2220001966 but the fix for that issue is the same as this one, adding a single line listed 2 replies above by @AndyMac2508

**Comment by driesvints** [comment]
@nomad-software I've unlocked it again

**Comment by mgarcia96** [comment]
In my case I run the `php artisan optimize` command before adding a env variable, and then the .env was cached. Simply I run `php artisan cache:clear` !!
