### ISSUE TITLE
Method hydrate does not exist (Macroable)

### ISSUE THREAD

**Issue by philipp-brosig** [laravel/framework#27948]
- Laravel Version: 5.8.*
- PHP Version: 7.1.3
- Database Driver & Version: MySQL, 5.7.23

### Description:
if the macroable trait was added to the user model of a freshly started Laravel project, an error is thrown. 
![image](https://user-images.githubusercontent.com/37481463/54743095-8266ec80-4bc3-11e9-964a-c4b09bf7f773.png)

![image](https://user-images.githubusercontent.com/37481463/54743272-f43f3600-4bc3-11e9-8105-7d05afd593c6.png)

### Steps To Reproduce:
laravel new <project>
valet link <name>
add "use Illuminate\Support\Traits\Macroable" to user model

**Comment by driesvints** [comment]
Models don't support the macroable trait.

**Comment by philipp-brosig** [comment]
Found a way to use macroable on models: 
https://medium.com/@zarehesmaiel/dynamic-relation-by-macro-988d638b6e51.

Just in case someone do need something similar.

**Comment by 4n70w4** [comment]
https://github.com/laravel/framework/pull/31286
