### ISSUE TITLE
Container should throw or catch ReflectionException

### ISSUE THREAD

**Issue by paul-thebaud** [laravel/framework#27959]
- Laravel Version: 5.8.4
- PHP Version: 7.2.1
- Database Driver & Version: N/A

### Description:
This is not a "real" bug, but I don't know what kind of issue I should have created for this.

When using the `make` method from the `Illuminate\Container\Container` class, if the given `$abstract` does not exists in container, it will try to create a reflection class of it (on line 794).
This line can throw a ReflectionException if the class does not exits.

I think this exception should appears in the `@throws` tags of the method which are concerned, or should be try / catch to throw a BindingResolutionException.

What do you think about it ?

I will make a PR to fix this if necessary, but before I want to discuss this issue.

**Comment by mfn** [comment]
Personally I think it's a nightmare to correctly maintain all the `@throws` and they should just be removed:
- if it's an exception in the same method, you can usually easily see it yourself
- if it's deep down, it usually gets out of sync in the docs anyway

**Comment by paul-thebaud** [comment]
@mfn For me, this documentation tag has its utility.
In my case, I was trying to only catch the `BindingResolutionException`. The fact that `make` method can throw the `ReflectionException` was creating a bug, because I was catching the wrong exception.

**Comment by driesvints** [comment]
Hmm, I agree with the fact that if the exception cascades through the method it might be wanted to add to to the DocBlock. In any case, like you said, this isn't really a bug and perhaps better should be taken up on the ideas repo so I'm going to close this off. You're always free to attempt a PR. 

Thanks!

**Comment by paul-thebaud** [comment]
@driesvints Ok, no problem.

Do you think it is be a good idea to catch the `ReflectionException` and throw a `BindingResolutionException ` instead ?

I would like to create a pull-request to include this behavior, but it contains a breaking change since people who are catching `ReflectionException` will loose this exception throwing.

**Comment by driesvints** [comment]
@paul-thebaud maybe yeah. Might be worth a pr. But you also might post at the ideas repo first to get support.
