### ISSUE TITLE
Resource with whenLoaded and KeyBy

### ISSUE THREAD

**Issue by notflip** [laravel/framework#27950]
- Laravel Version: 5.8
- PHP Version: 7.3
- Database Driver & Version: MySQL

### Description:
By default Laravel will 'null' a resource key when whenLoaded returns false, however when I attach the KeyBy method to the end of the call, this will throw an error.

> Call to undefined method Illuminate\Http\Resources\Json\AnonymousResourceCollection::keyBy()

### Steps To Reproduce:

```
    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'data' => [
                'translations' => MenuTranslationResource::collection($this->whenLoaded('translations'))
                    ->keyBy(function ($trans) {
                        return $trans['locale'];
                    })
            ]
        ];
    }
```

**Comment by driesvints** [comment]
Hey there @notflip. ResourceCollections aren't really collections like the collection class but rather also JsonResources. That's why they don't share the same functionality.

**Comment by staudenmeir** [comment]
You would have to build this manually:

```php
public function toArray($request)
{
    $data = [
        'id' => $this->id,
        'data' => [],
    ];

    if ($this->resource->relationLoaded('translations')) {
        $result['data']['translations'] = MenuTranslationResource::collection($this->resource->translations)
            ->keyBy(function ($trans) {
                return $trans['locale'];
            });
    }       
    
    return $data;
}
```

**Comment by driesvints** [comment]
@staudenmeir that still wouldn't work since the `collection` method returns an instance of `AnonymousResourceCollection` which isn't an instance of `Illuminate\Support\Collection`, right?

**Comment by notflip** [comment]
@driesvints Is there a way to make this work? Can I define the keyBy somewhere else as to achieve the key => value result from that resource? Thank you.

**Comment by staudenmeir** [comment]
@driesvints `AnonymousResourceCollection` has a `__call()` method that forwards this to the underlying collection.

**Comment by driesvints** [comment]
@notflip I don't know for certain myself atm. I haven't worked with json resources a lot myself yet. I think it's best if you asked on one of the below channels. You'll probably get faster feedback there.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

**Comment by driesvints** [comment]
@staudenmeir right. Then that would work. Thanks for noting that 👍

**Comment by staudenmeir** [comment]
Forget my hacky workaround, this is the actual solution:

```php
public function toArray($request)
{
    return [
        'id' => $this->id,
        'data' => [
            'translations' => new MenuTranslationResourceCollection(
                $this->whenLoaded('translations', function () {
                    return $this->translations->keyBy(function ($trans) {
                        return $trans['locale'];
                    });
                })
            )
        ]
    ];
}

class MenuTranslationResourceCollection extends ResourceCollection
{
    public $collects = 'App\Http\Resources\MenuTranslationResource';

    public $preserveKeys = true;

    /**
     * Transform the resource collection into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        return parent::toArray($request);
    }
}
```

`whenLoaded()` accepts a closure as the second parameter to customize the result.

The latest versions of Laravel reset numeric keys in associative arrays, so we have to prevent this by adding `public $preserveKeys = true;` to `MenuTranslationResource`.

However: The example from the [documentation](https://laravel.com/docs/5.8/eloquent-resources#generating-resources) ("Preserving Collection Keys") doesn't actually work with `MenuTranslationResource::collection()`. At least for now, we need a separate `MenuTranslationResourceCollection` class.

**Comment by driesvints** [comment]
Okay, re-opening this.

**Comment by staudenmeir** [comment]
Final solution for Laravel 5.8.9:

```php
public function toArray($request)
{
    return [
        'id' => $this->id,
        'data' => [
            'translations' => MenuTranslationResource::collection(
                $this->whenLoaded('translations', function () {
                    return $this->translations->keyBy(function ($trans) {
                        return $trans['locale'];
                    });
                })
            )
        ]
    ];
}

class MenuTranslationResource extends JsonResource
{
    public $preserveKeys = true;

    [...]
}
```

**Comment by driesvints** [comment]
So is this still an issue or can this be closed?

**Comment by staudenmeir** [comment]
Can be closed.
