### ISSUE TITLE
Get Data Sent Via WebSocket

### ISSUE THREAD

**Issue by The-Code-Monkey** [laravel/framework#27953]
How do i access the data that a user sends via a websocket as i need to be able to accept a webcam stream over a websocket i know this is possible as it can be done with a java server, but i don't want to use a java server as i don't understand java but I do understand laravel and php

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
