### ISSUE TITLE
Laravel Auth Controllers use wrong database credentials

### ISSUE THREAD

**Issue by bojandurmic** [laravel/framework#27962]
- Laravel Version: 5.8
- PHP Version: 7.3.1
- Database Driver & Version: MySQL 5.8

### Description:
I just installed a fresh Laravel instance. I have put the correct MySQL data in the .env file. First, I have run the `php artisan make:auth` command, and then the `php artisan migrate`, which worked flawlessly and three tables were added.

Then, I tried to register a dummy user through the default routes, and have received the following error:

SQLSTATE[HY000] [1045] Access denied for user 'homestead'@'localhost' (using password: YES) (SQL: select * from `users` where `email` = test@gmail.com limit 1)

It looks like the default controllers are somehow using different data. From the Whoops page, I have found that the arguments to PDO construct function are:

"mysql:host=127.0.0.1;port=3306;dbname=homestead"
"homestead"
"secret"

It looks as if I didn't update the .env file at all. But, if my credentials were incorrect, then `php artisan migrate` would not run.

Also, running `php artisan tinker` and creating a user there by

`$user = new App\User` and giving it the data and hitting `$user->save();` works and the row is added to table.

### Steps To Reproduce:

1) Install fresh Laravel (using Windows 10)
2) Put the correct data in .env file
3) Run `php artisan make:auth` and then `php artisan migrate`
4) Try to open the home page, and  go to Register and try to register
5) You should see the error.

**Comment by bojandurmic** [comment]
Issue solved by closing my terminal and running `php artisan serve` again. Any reason why this might happen?

**Comment by antonkomarev** [comment]
Any `.env` file changes applies only after re-run `artisan serve`.

**Comment by mlambley** [comment]
If I'm not mistaken, `composer cache-clear` will clear the `.env` so run that after you make changes to your `.env`. It's normal behaviour for changes to `.env` to not be immediately updated when using `php artisan serve`.

**Comment by bojandurmic** [comment]
Thank you @antonkomarev, didn’t know that little piece of information. I’m closing the issue.
