### ISSUE TITLE
Laravel should suppport MySQL SET NAMES syntax unquoted

### ISSUE THREAD

**Issue by zhangchile** [laravel/framework#27969]
**PHP Version: 7.1**
**Laravel Version: 5.1(LTS)**
**MySQL Version: 5.5 with custom agent**

Hi,Guys!
My database config 
```php
'hive_meta_reader' => [
            'driver'    => 'mysql',
            'host'      => '10.21.1.8',
            'database'  => 'foo1',
            'username'  => 'someuser',
            'password'  => 'pwd@local',
            'charset'   => 'utf8',
            'collation' => 'utf8_general_ci',
            'prefix'    => '',
            'strict'    => false,
        ]
```
and I get a mysql pdo exception:
![image](https://user-images.githubusercontent.com/3659688/54811267-44e98880-4cc3-11e9-8855-8bcb0c6b1711.png)

then i edit the file MySqlConnector.php:line 38
change to 
```php
        try {
            $names = "set names '$charset'".
                (!is_null($collation) ? " collate '$collation'" : '');
            $connection->prepare($names)->execute();
        } catch (\PDOException $e) {
            $names = "set names $charset".
                    (!is_null($collation) ? " collate $collation" : '');
            $connection->prepare($names)->execute();
        }
```
then i fix the problem.

But, why ?It look like a syntax error, I find this 
[set-names syntax](https://dev.mysql.com/doc/refman/5.5/en/set-names.html)

> The optional COLLATE clause may be used to specify a collation explicitly. If given, the collation must one of the permitted collations for charset_name.
> **charset_name and collation_name may be quoted or unquoted.**
> The default mapping can be restored by using a value of DEFAULT. The default depends on the server configuration.

I know Laravel 5.1 is not supported any more,but all version of Laravel has the same problem.
I think Laravel should  support the SET NAMES syntax unquoted.

**Comment by staudenmeir** [comment]
Does the error message show the whole query?

**Comment by zhangchile** [comment]
> Does the error message show the whole query?

Yes,the SET NAMES query always execute when connect to mysql.

**Comment by staudenmeir** [comment]
Please post the whole error message.

**Comment by zhangchile** [comment]
> If you believe that all versions have the same issue then why did you reported this on a non-supported version? Which other versions did you try this with? Please try to provide accurate information in the issue template as it would allow us to pinpoint the issue more precisely.

Thanks,actually I do not need to try other version of laravel.

> charset_name and collation_name may be quoted or unquoted.

There are two style  of set names syntax: quote or unquote.
This error happen because some other version mysql(which i use) just support unquote syntax,and i don't why do not support, may be because it has an agent layer.

```sql
#style unquote
#some other version of mysql  just only support this syntax
set names utf8 collate utf8_general_ci;

#style quote, all laravel now use
#throw pdo exception because some mysql do not support this
set names 'utf8' collate 'utf8_general_ci';
```

I think laravel should be compatible with this two situation, is that right?

version of laravel MysqlConnector source code :
[5.8 MysqlConnector.php](https://github.com/laravel/framework/blob/5.8/src/Illuminate/Database/Connectors/MySqlConnector.php#L56)
[5.7 MysqlConnector.php](https://github.com/laravel/framework/blob/5.7/src/Illuminate/Database/Connectors/MySqlConnector.php#L56)
[5.6 MysqlConnector.php](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Database/Connectors/MySqlConnector.php#L56)
[5.5 MysqlConnector.php](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Database/Connectors/MySqlConnector.php#L56)
[5.4 MysqlConnector.php](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Connectors/MySqlConnector.php#L56)
[5.3 MysqlConnector.php](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Connectors/MySqlConnector.php#L38)
[5.2 MysqlConnector.php](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Connectors/MySqlConnector.php#L38)

**Comment by staudenmeir** [comment]
MySQL 5.5 does support quoted charset and collation names. This must be an issue with your setup.

I don't think Laravel should support both syntaxes. This is an extreme edge case and you are apparently the first person to have this.

**Comment by zhangchile** [comment]
> MySQL 5.5 does support quoted charset and collation names. This must be an issue with your setup.
> 
> I don't think Laravel should support both syntaxes. This is an extreme edge case and you are apparently the first person to be affected by it.

Yes, this is a special case. I can't change mysql version or settings in my project,so I have had to edit the laravel source code.
