### ISSUE TITLE
Eloquent Sync fail in 5.8

### ISSUE THREAD

**Issue by mimbar** [laravel/framework#27967]
Got problem when i try to sync data from creating new User.

```
            $user = new User();
            $user->create($request->all());
            $systemList = $request->input('system');
            $user->systems()->sync($systemList);
```

the error report:

> SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'userID' cannot be null (SQL: insert into `user_system` (`systemID`, `userID`) values (2, ))

the User Class:

```
use Illuminate\Database\Eloquent\Model;
use Modules\Systems\Entities\System;

class User extends Model
{
    protected $fillable = [
        'username', 'email', 'sex',
        'first_degree', 'name', 'degree', 'level'
    ];

    protected $hidden = [
        'password',
    ];

    public function systems()
    {
        return $this->belongsToMany(System::class, 'user_system', 'userID', 'systemID')->withPivot(['password', 'username']);
    }
}
```

**Comment by staudenmeir** [comment]
`$user->create($request->all());` is not correct. You are creating a new user, but not storing it in `$user`.

Use one of these options:

```php
$user = User::create($request->all());

$user = new User($request->all());
$user->save();
```

**Comment by driesvints** [comment]
Hey there, can you please try to update your first comment with a filled in issue template?

**Comment by devcircus** [comment]
This is the expected behavior. The "user" that you're chaining your relationship methods on is just an empty User object. 

Oh I just noticed the comment by @staudenmeir above which says the same.

**Comment by driesvints** [comment]
Closing this as it's the expected behavior.
