### ISSUE TITLE
[Blade] Child view that inherits from parent always has the same value

### ISSUE THREAD

**Issue by Athlon1600** [laravel/framework#27991]
- Laravel Version: 5.7.1
- PHP Version: 7.1.3
- Database Driver & Version: 5.7 mySQL

### Description:

Basically what the title says. It's better explained by showing an example, but I don't see how this behavior makes sense.

### Steps To Reproduce:
  

list.blade

```
@include('test.child', ['value' => 100])
@include('test.child', ['value' => 200])
@include('test.child', ['value' => 300])
```

parent.blade
```
@yield('content')
```

child.blade
```
@extends('test.parent')

@section('content')
    <p>Child Value: {{ $value }}</p>
@endsection
```

What I'm expecting to get:

- Child Value: 100
- Child Value: 200
- Child Value: 300  

  
what I'm actually getting:

- Child Value: 100
- Child Value: 100
- Child Value: 100  
  
The first $value just seems to be "cached" everytime a new instance of a child view gets rendered.

**Comment by laurencei** [comment]
This code doesnt make sense. It should *just* be:

```
@include('test.child', ['value' => 100])
@include('test.child', ['value' => 200])
@include('test.child', ['value' => 300])
```

and then `child.blade` is only

```<p>Child Value: {{ $value }}</p>```

Or - you should be doing `@incude('test.parent')` and not the child.

**Comment by devcircus** [comment]
Yeah there's a logic issue here with how you're including and inheriting views/templates. 

Although this would be best handled on one of the support forums, if you'll spin up and small reproducible repo, you can probably get some help.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
