### ISSUE TITLE
SQL Query doesn't always work in Testing

### ISSUE THREAD

**Issue by iamyaoxi** [laravel/framework#28014]
- Laravel Version: 5.8.7
- PHP Version: 7.3.1-1
- Homestead 8.1.0
- Database: MySQL
- PHPUnit: 7.5.7

### Description:
I'm trying to use FTS to search some data in my table. It works in MySQL cli, it works in the framework. But somehow it doesn't work in Testing.

In TestCase, I tried to use:
`DB::select(DB::raw('select * from mydata where match(body) against(\'+search\' in boolean mode')`. 
And it always return empty array.

**Comment by staudenmeir** [comment]
Please create a minimal application to reproduce the issue and upload it to GitHub.

**Comment by iamyaoxi** [comment]
I think this line should be enough: 
`DB::select(DB::raw('select * from mydata where match(body) against(\'+search\' in boolean mode').`
Because I did this in Controller and CLI it works, but it doesn't work in TestCase.

I was wondering, do TestUnit use different DB implementation? Which may have caused the problem.

**Comment by staudenmeir** [comment]
They use the same database implementation.

Are you sure that the table contains the same data in both cases? What's the data?

**Comment by iamyaoxi** [comment]
Yes. Because when I use direct query thru SQL CLI it worked. It just doesn't work through PHPUnit Test. They also use same PHP Migration.

But do you think `RefreshDatabase` will cause the problem, somehow? Does it destroy the schema and recreate them or just dropping the data?

**Comment by staudenmeir** [comment]
Please put `dd(DB::select('select * from mydata'));` in both places and compare the result.

**Comment by iamyaoxi** [comment]
I just commented out `RefreshDatabase` on TestCase. 
And it works as expected.

I'll take a look at how `RefreshDatabase` works to see if we can fix that.

**Comment by driesvints** [comment]
Do you use mysql in testing as well or sqlite? Can you please paste your test class or enough code to reproduce the problem?

**Comment by iamyaoxi** [comment]
@driesvints 
Yea. I use MySQL in Testing. The very same database, just different schema.


I think this problem caused by the way RefreshDatabase rollback the data before application destroyed. The data is not really persisted into MySql database, result in the data not stored in FTS index, and therefore not being able to be retrieved using the query.

The current workaround is to not use RefreshDatabase for the TestCase. And drop the data on `tearDown`.

**Comment by staudenmeir** [comment]
From the [MySQL documentation](https://dev.mysql.com/doc/refman/en/innodb-fulltext-index.html):

> InnoDB FULLTEXT indexes have special transaction handling characteristics due its caching and batch processing behavior. Specifically, updates and insertions on a FULLTEXT index are processed at transaction commit time, which means that a FULLTEXT search can only see committed data. The following example demonstrates this behavior. The FULLTEXT search only returns a result after the inserted lines are committed.

As a workaround, you could use the `MyISAM` engine for this table and then truncate the table manually in `tearDown()`.

**Comment by driesvints** [comment]
Seems like this is indeed the current behavior. If you'd like to change this or suggest improvements please open up an issue on the ideas repo.

**Comment by dillingham** [comment]
This drove me insane for almost a day :)

I changed `RefreshDatabase `to `DatabaseMigrations` and it worked

**Comment by gotroch** [comment]
The very same problem here. Had to remove RefreshDatabase. Looks like this occure with fulltext search only.

**Comment by raghavendra89** [comment]
I faced the same problem. Testing full text search query is not working with `RefreshDatabase` trait. But it works with the `DatabaseMigrations` trait.
