### ISSUE TITLE
Cache::remember() set expires at by Carbon

### ISSUE THREAD

**Issue by nuocgansoi** [laravel/framework#28012]
- Laravel Version: 5.7
- PHP Version: 7.2
- Database Driver & Version: MariaDB server - 10.1.38

### Description:
I use cache database drive.
The expiration time be add 1 day.

### Steps To Reproduce:
$hours = 24;
$expiresAt = now()->addHours($hours);
Cache::remember($key, $expiresAt, $callback);

In database I get cache.expiration is 2 days later.
When ($hours % 24 == 0), I get wrong expiration. Another it work right.
Please tell me why?

**Comment by staudenmeir** [comment]
> In database I get cache.expiration is 2 days later.

*Exactly* two days later?

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.

Thanks!
