### ISSUE TITLE
Add support of 'OPTIONS' method for `Route::apiResource()`

### ISSUE THREAD

**Issue by klimov-paul** [laravel/framework#28018]
- Laravel Version: 5.8.7
- PHP Version: 7.2.15
- Database Driver & Version: not related

### Description:

Relates to #447

Request method 'OPTIONS' is common part of the REST flow. While it is not always used particular rest resource may provide it for some meta data specification.
Unfortunally current `Route::apiResource()` lacks of support for the 'OPTIONS' method.
Following attempt of registering API resource produces no route for the 'OPTIONS' method:

```php
Route::apiResource('items', ItemController::class)->only(['index', 'show', 'store', 'update', 'destroy', 'options']);
```

The only way of addition 'OPTIONS' to the REST resource controller is writing `Route::options()` manually in addition to `Route::apiResource()`, which does not looks well in routes config:

```php
Route::options('items', ItemController::class.'@options');
Route::apiResource('items', ItemController::class);
```

### Steps To Reproduce:

Register API resource route with 'options' method:

```php
Route::apiResource('items', ItemController::class)->only(['index', 'show', 'store', 'update', 'destroy', 'options']);
```

Create controller matching 'options' method returning JSON response:
```php
class ItemController extends Controller
{
    public function options()
    {
        return response()->json([
            'meta' => [],
        ]);
    }
```

Write an feature test to check the method response:

```
public function testOptions()
    {
        $this->call('OPTIONS', route('api.items.index'))
            ->assertSuccessful()
            ->assertJson([
                'meta'
            ]);
    }
```

Test fails as response contains an empty string.

**Comment by driesvints** [comment]
Please fill out the issue template.

**Comment by klimov-paul** [comment]
PR: #28019

**Comment by driesvints** [comment]
I'm going to close this as this is more of a feature request than an actual bug imo. This has been brought up before. Let's see how your PR goes. Feel free to re-open on the ideas repo where new features are discussed.

**Comment by lionslair** [comment]
https://laravel.com/docs/5.8/routing#basic-routing 

Why is options documented then?

![Selection_010](https://user-images.githubusercontent.com/832259/55127378-dedd8500-514a-11e9-952a-2a7566899454.png)

**Comment by driesvints** [comment]
@lionslair because we still offer support for all the different HTTP verbs, we just don't want to automagically add to many routes for resources.
