### ISSUE TITLE
Add test for BelongsToMany::detach() with custom pivot class

### ISSUE THREAD

**Issue by TBlindaruk** [laravel/framework#28025]
Please add test for cover case, which was fixed in the https://github.com/laravel/framework/pull/27997.

Also please add tests for the https://github.com/laravel/framework/commit/cadea88cc2007cedb825b5d86a0fb184dcd76ab4 commit

--------------------------

This commits is fixed some bug which was created after the https://github.com/laravel/framework/pull/27571

**Comment by staudenmeir** [comment]
I think this @ralphschindler's responsibility. We should also have tests for cadea88.

**Comment by TBlindaruk** [comment]
@staudenmeir - updated description

**Comment by ralphschindler** [comment]
I will look into this this week @TBlindaruk, @staudenmeir

**Comment by TBlindaruk** [comment]
@ralphschindler

**Comment by driesvints** [comment]
Tests were added: https://github.com/laravel/framework/pull/28424
