### ISSUE TITLE
Add tests for fix incorrect event namespace in generated listener

### ISSUE THREAD

**Issue by TBlindaruk** [laravel/framework#28027]
Please add tests for issue which was fixed by the https://github.com/laravel/framework/pull/28007

**Comment by TBlindaruk** [comment]
@devcircus

**Comment by devcircus** [comment]
Yeah I’m going to punt. Simple enough, however as I’m unable to find any tests for any generators, I’ll let someone more knowledgeable take this one. Not sure how the maintainers would like to proceed in an untested area of the framework. Thx.
