### ISSUE TITLE
save a Model to the second DB connection

### ISSUE THREAD

**Issue by alextesi** [laravel/framework#28035]
I'm trying to save my model to a second database connection,
when I retrieve the record the connection works regularly and I receive the right database record.
But I update some properties and try to save, here I receive this error:

Base table or view not found: 1146 Table 'daf_db.s_blog' doesn't exist (SQL: update `s_blog` set `title` = , `author_id` = , `active` = , `short_description` = , `description` = 'rendered', `views` = , `category_id` = , `template` = , `meta_keywords` = , `meta_description` = , `meta_title` = where `id` = 2410)

but daf_db is the default database and not the one specified in the model.

Here my Model
`class SBlogProd extends Model
{
    protected $connection = 'mysqlShopwareProduction';
    protected $table      = 's_blog';
    public $timestamps    = false;

    protected $casts = [
        'author_id'   => 'int',
        'active'      => 'int',
        'views'       => 'int',
        'category_id' => 'int',
    ];

    protected $dates = [
        'display_date',
    ];

    protected $fillable = [
        'title',
        'author_id',
        'active',
        'short_description',
        'description',
        'views',
        'display_date',
        'category_id',
        'template',
        'meta_keywords',
        'meta_description',
        'meta_title',
    ];`

and here the function that receive this error:

`    /**
     * publish the given content.
     *
     * @param  \App\Contents  $contents
     * @return \Illuminate\Http\Response
     */
    public function publish(Contents $content)
    {
        // dd($content);
        if (!empty($content['live']['blog_id'])) {
            $sblogContent = SBlogProd::find($content['live']['blog_id']);
            // dump($sblogContent);
        } else {
            $sblogContent = new SBlogProd;
        }

        $renderedBlogPAge = 'rendered';
        $sblogContent->title             = (empty($content->live->title)) ? ' ' : $content->live->title;
        $sblogContent->author_id         = (empty($content->live->author_id)) ? ' ' : $content->live->author_id;
        $sblogContent->active            = (empty($content->live->active)) ? ' ' : $content->live->active;
        $sblogContent->short_description = (empty($content->live->short_description)) ? ' ' : $content->live->short_description;
        $sblogContent->description       = $renderedBlogPAge;
        $sblogContent->views             = (empty($content->live->views)) ? ' ' : $content->live->views;
        // $sblogContent->display_date      = (empty($content->live->display_date)) ? ' ':Carbon::parse($content->live->display_date)->format('Y.m.d');
        $sblogContent->category_id      = (empty($content->live->category_id)) ? ' ' : $content->live->category_id;
        $sblogContent->template         = (empty($content->live->template)) ? ' ' : $content->live->template;
        $sblogContent->meta_keywords    = (empty($content->live->meta_keywords)) ? ' ' : $content->live->meta_keywords;
        $sblogContent->meta_description = (empty($content->live->meta_description)) ? ' ' : $content->live->meta_description;
        $sblogContent->meta_title       = (empty($content->live->meta_title)) ? ' ' : $content->live->meta_title;
        $sblogContent->save();

        // redirect to a detail page
        return redirect()->route('contents.show', $content);
    }`

I searched on internet and my code seems to be right, can you see any error?
Can anyone help me with this ?
Thanks
Alessandro

**Comment by staudenmeir** [comment]
Please don't ignore the issue template, the version information is crucial.

Also, please simplify your code and format it properly.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
