### ISSUE TITLE
Problem with serializing custom date fields that are empty strings

### ISSUE THREAD

**Issue by carestad** [laravel/framework#28047]
- Laravel Version: 5.5.45 (but this also seems to be present in 5.8)
- PHP Version: 7.2.13
- Database Driver & Version: mysqlnd 5.0.12-dev - 20150407

### Description:

A pretext to this was fixed in #22107, which was reported in #21338.

Carbon will still throw an exception when trying to convert a collection via a HasMany relation of a model where a date field is an empty string (and not `NULL`). The date field (`order_date`) is of the type varchar in the DB due to a custom format (see #22385 for that).

#### Example

```php
Project::find(1)->orders->toArray()
```

Returns: `InvalidArgumentException with message 'Data missing'`.

It fails when one of the order's `order_date` is set to an empty string instead of `NULL`.

After looking through the stack trace I found that it is likely due to `addDateAttributesToArray()` in `Illuminate/Database/Eloquent/Concerns/HasAttributes.php`, where the `isset()` check would catch `NULL`ed values, but not `""` (empty strings).

#### Create project and order tables

```php
Schema::create('project', function(Blueprint $table) {
    $table->increments('id');
    $table->string('name');
    $table->timestamps();
});

Schema::create('order', function(Blueprint $table) {
    $table->increments('id');
    $table->string('name');
    $table->string('order_date');
    $table->unsignedInteger('project_id');
    $table->timestamps();
});
```

(Note the `order_date` which is `string`).

#### Create models

```php
class Project extends Model
{
    protected $table = 'project';

    public function orders() {
        return $this->hasMany(Order::class);
    }
}
```

```php
class Order extends Model
{
    protected $table = 'order';
    protected $dates = ['order_date'];
    protected $dateFormat = 'YmdHis';
}
```

#### Create seeders

```php
public function run()
{
  Project::create([
    'name' => 'Test project 1',
  ]);
  Order::create([
    'name' => 'Test order',
    'order_date' => now(),
'project_id' => 1,
  ]);
  Order::create([
    'name' => 'Test order',
    'order_date' => '',
    'project_id' => 1,
  ]);
}
```

#### Run tinker

Tinker is able to dump the collection like this:

```
>>> App\Project::find(1)->orders
=> Illuminate\Database\Eloquent\Collection {#2876
     all: [
       App\Order {#2877
         id: "1",
         name: "Test order",
         order_date: "20190328124507",
         project_id: "1",
         created_at: "20190328124507",
         updated_at: "20190328124507",
       },
       App\Order {#2884
         id: "2",
         name: "Test order",
         order_date: "",
         project_id: "1",
         created_at: "20190328124507",
         updated_at: "20190328124507",
       },
     ],
   }
```

But if I try to convert it to an array, it fails:

```
>>> App\Project::find(1)->orders->toArray()
InvalidArgumentException with message 'Data missing'
```

### Workaround

Overriding `addDateAttributesToArray()` in Order model, so that the model looks like this:

```php
(...)
protected $table = 'order';
protected $dates = ['order_date'];
protected $dateFormat = 'YmdHis';

protected function addDateAttributesToArray(array $attributes)
{
    foreach ($this->getDates() as $key) {
        if (! isset($attributes[$key])) {
            continue;
        }
        // Added this if check. Could possibly be more speficic, i.e.:
        // if ($attributes[$key] === '')
        if (empty($attributes[$key])) {
            continue;
        }

        $attributes[$key] = $this->serializeDate(
            $this->asDateTime($attributes[$key])
        );
    }

    return $attributes;
}
```

**Comment by driesvints** [comment]
Thank you for the detailed issue 👍 

If you're up for it, feel free to create a PR with a test for this. Otherwise I'll pick this up once I get around to it.

**Comment by driesvints** [comment]
If you send this in to the 5.5 branch you can also send this separately to the 5.8 branch.

**Comment by carestad** [comment]
I would love to submit a PR, but I have very little exercise in writing tests, especially for Laravel as a framework. I don't currently see any unit tests covering the `addDateAttributesToArray` method, but I also wouldn't know where to put it if it should be added :slightly_frowning_face: 

Also: edited my description. I was testing this on Laravel 5.5.45, not 5.5.42 as initially reported.

**Comment by driesvints** [comment]
Seems like a PR was attempted. @khatriafez please note that every PR needs a detailed explanation and not just a link to an issue. This is noted in the PR template: https://raw.githubusercontent.com/laravel/framework/5.8/.github/PULL_REQUEST_TEMPLATE.md

**Comment by driesvints** [comment]
I'm closing this because it has been determined that an empty string simply isn't a valid date. The thrown exception is wanted. Please see https://github.com/laravel/framework/pull/30549#issuecomment-552085930 for more info.
