### ISSUE TITLE
CSRF validates the exception when `encrypt'=> false'.

### ISSUE THREAD

**Issue by allowing** [laravel/framework#28043]
- Laravel Version: 5.8.3
- PHP Version: 7.3
- Database Driver & Version:

### Description:

When `encrypt'=> false in `config/session.php', `TokenMismatch Exception'exception will be obtained. Page performance is 419

There is no such problem when `encrypt'=> true'.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
