### ISSUE TITLE
ConsoleKernel always initializes scheduler regardless of performed function

### ISSUE THREAD

**Issue by devbazilio** [laravel/framework#28040]
- Laravel Version: 5.8
- PHP Version: 7.2
- Database Driver & Version: any

### Description:
If you try to run any console command with artisan the Console Kernel always parses and schedules events as at https://github.com/laravel/framework/blob/5.8/src/Illuminate/Foundation/Console/Kernel.php#L90 **defineConsoleSchedule** function always called after booting up the kernel.

### Steps To Reproduce:
1) Install clean project
```
composer create-project --prefer-dist laravel/laravel blog
...Installing laravel/laravel (v5.8.3)
```
2) open **app/Console/Kernel.php**, put a single line into `schedule` function
```
    protected function schedule(Schedule $schedule)
    {
        throw new \Exception("Do not call scheduler upon packages discovery!");
    }
```
3) remove all vendor packages
`rm -rf vendor`
4) install vendor packages again
`composer install`

anda  fatal error occurs:
```
composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In Kernel.php line 29:
                                                 
  Do not call scheduler upon packages discovery!
```

So what I mean - in kernel scheduler I have some logic to run specific jobs or don't run them at all. Upon clean installation sources from git **composer** runs **php artisan package:discover** command which tries to initialize scheduler. 
More debugging showed that even **php artisan** command causes kernel to enter **schedule** and queue events
As expected behavior I think only right way to call **schedule** if you do **php artisan schedule:run**

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not for ideas, suggestions etc. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. You are able to open a ticket at https://github.com/laravel/ideas

Alternatively you are able to open a PR using the Contributions guidelines: https://laravel.com/docs/5.7/contributions#which-branch

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.

**Comment by devbazilio** [comment]
The problem is that the console kernel always initializes schedule events even if you even simply type "php artisan" in a console. Why he does that at running of any command?

**Comment by curunoir** [comment]
I also think it is a framework issue. I have a project which needs to check in database if some jobs need to be scheduled or not.

Running composer install make the default post-autoload command artisan package:discover to crash. Why is the Kernel schedule() method called for something else than scheduling ? That don't make really sense.

**Comment by devbazilio** [comment]
@curunoir 
> I also think it is a framework issue. I have a project which needs to check in database if some jobs need to be scheduled or not.
> 
> Running composer install make the default post-autoload command artisan package:discover to crash. Why is the Kernel schedule() method called for something else than scheduling ? That don't make really sense.

you are correct. I added a quick-and-dirty hack to make things work properly as there are no sense to submit PR to commercial software

```
protected function schedule(Schedule $schedule)
    {
        //if artisan have been called with 'schedule:run' exit then do nothing
        if ($this->app->runningInConsole()) {
            $input      = new ArgvInput();
            $artisanArg = $input->getFirstArgument();
            if ($artisanArg && strpos($artisanArg, 'schedule:') !== 0) {
                return;
            }
        }
    }
```
