### ISSUE TITLE
L5.2 install & update fails with illuminate/filesystem v5.6.0 requires php ^7.1.3

### ISSUE THREAD

**Issue by kerog** [laravel/framework#28045]
- Laravel Version: 5.2.45
- PHP Version: 7.0.27
- Database Driver & Version:

### Description:
After clean vendor dir and composer.lock and run composer install I have an error:
  Problem 1
    - illuminate/filesystem v5.8.8 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.8.4 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.8.3 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.8.2 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.8.0 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.7.9 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.7.8 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.7.7 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.7.6 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.7.5 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.7.4 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.7.3 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.7.28 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.7.27 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.7.26 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.7.23 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.7.22 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.7.21 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.7.20 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.7.2 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.7.15 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.7.11 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.7.10 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.7.1 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.7.0 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem 5.7.19 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem 5.7.18 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem 5.7.17 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.6.9 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.6.8 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.6.7 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.6.6 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.6.5 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.6.4 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.6.39 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.6.38 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.6.37 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.6.36 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.6.35 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.6.34 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.6.33 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.6.32 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.6.31 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.6.30 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.6.3 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.6.29 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.6.28 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.6.27 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.6.26 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.6.25 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.6.24 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.6.23 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.6.22 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.6.21 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.6.20 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.6.2 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.6.19 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.6.17 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.6.16 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.6.15 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.6.14 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.6.13 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.6.12 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.6.11 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.6.10 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.6.1 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - illuminate/filesystem v5.6.0 requires php ^7.1.3 -> your PHP version (7.0.27) does not satisfy that requirement.
    - Conclusion: don't install laravel/framework v5.2.45
    - Conclusion: don't install laravel/framework v5.2.44
    - Conclusion: don't install laravel/framework v5.2.43
    - Conclusion: don't install laravel/framework v5.2.42
    - Conclusion: don't install laravel/framework 5.2.41
    - Conclusion: don't install laravel/framework v5.2.40
    - Conclusion: don't install laravel/framework v5.2.39
    - Conclusion: don't install laravel/framework v5.2.38
    - Conclusion: don't install laravel/framework v5.2.37
    - Conclusion: don't install laravel/framework v5.2.36
    - Conclusion: don't install laravel/framework v5.2.35
    - Conclusion: don't install laravel/framework v5.2.34
    - Conclusion: don't install laravel/framework v5.2.33
    - Conclusion: don't install laravel/framework v5.2.32
    - Conclusion: don't install laravel/framework v5.2.31
    - Conclusion: don't install laravel/framework v5.2.30
    - Conclusion: don't install laravel/framework v5.2.29
    - Conclusion: don't install laravel/framework v5.2.28
    - Conclusion: don't install laravel/framework v5.2.27
    - Conclusion: don't install laravel/framework v5.2.26
    - Conclusion: don't install laravel/framework v5.2.25
    - Conclusion: don't install laravel/framework v5.2.24
    - Conclusion: don't install laravel/framework v5.2.23
    - Conclusion: don't install laravel/framework v5.2.22
    - Conclusion: don't install laravel/framework v5.2.21
    - Conclusion: don't install laravel/framework v5.2.20
    - Conclusion: don't install laravel/framework v5.2.19
    - Conclusion: don't install laravel/framework v5.2.18
    - Conclusion: don't install laravel/framework v5.2.17
    - Conclusion: don't install laravel/framework v5.2.16
    - Conclusion: don't install laravel/framework v5.2.15
    - Conclusion: don't install laravel/framework v5.2.14
    - Conclusion: don't install laravel/framework v5.2.13
    - Conclusion: don't install laravel/framework v5.2.12
    - Conclusion: don't install laravel/framework v5.2.11
    - Conclusion: don't install laravel/framework v5.2.10
    - Conclusion: don't install laravel/framework v5.2.9
    - Conclusion: don't install laravel/framework v5.2.8
    - Conclusion: don't install laravel/framework v5.2.7
    - Conclusion: don't install laravel/framework v5.2.6
    - Conclusion: don't install laravel/framework v5.2.5
    - Conclusion: don't install laravel/framework v5.2.4
    - Conclusion: don't install laravel/framework v5.2.3
    - Installation request for barryvdh/laravel-snappy dev-master -> satisfiable by barryvdh/laravel-snappy[dev-master].
    - Conclusion: don't install laravel/framework v5.2.2
    - Conclusion: don't install laravel/framework v5.2.1
    - barryvdh/laravel-snappy dev-master requires illuminate/filesystem 5.5.x|5.6.x|5.7.x|5.8.x -> satisfiable by illuminate/filesystem[5.7.17, 5.7.18, 5.7.19, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40,
 v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33
, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8,
 v5.7.9, v5.8.0, v5.8.2, v5.8.3, v5.8.4, v5.8.8].
    - don't install illuminate/filesystem v5.5.0|don't install laravel/framework v5.2.0
    - don't install illuminate/filesystem v5.5.16|don't install laravel/framework v5.2.0
    - don't install illuminate/filesystem v5.5.17|don't install laravel/framework v5.2.0
    - don't install illuminate/filesystem v5.5.2|don't install laravel/framework v5.2.0
    - don't install illuminate/filesystem v5.5.28|don't install laravel/framework v5.2.0
    - don't install illuminate/filesystem v5.5.33|don't install laravel/framework v5.2.0
    - don't install illuminate/filesystem v5.5.34|don't install laravel/framework v5.2.0
    - don't install illuminate/filesystem v5.5.35|don't install laravel/framework v5.2.0
    - don't install illuminate/filesystem v5.5.36|don't install laravel/framework v5.2.0
    - don't install illuminate/filesystem v5.5.37|don't install laravel/framework v5.2.0
    - don't install illuminate/filesystem v5.5.39|don't install laravel/framework v5.2.0
    - don't install illuminate/filesystem v5.5.40|don't install laravel/framework v5.2.0
    - don't install illuminate/filesystem v5.5.41|don't install laravel/framework v5.2.0
    - don't install illuminate/filesystem v5.5.43|don't install laravel/framework v5.2.0
    - don't install illuminate/filesystem v5.5.44|don't install laravel/framework v5.2.0
    - Installation request for laravel/framework 5.2.* -> satisfiable by laravel/framework[5.2.41, v5.2.0, v5.2.1, v5.2.10, v5.2.11, v5.2.12, v5.2.13, v5.2.14, v5.2.15, v5.2.16, v5.2.17, v5.2.18, v5.2.19, v5.2.2, v5.2.20, v5.2.21, v5.2.22, v5.2.23, v5.2.24, v5.2.25
, v5.2.26, v5.2.27, v5.2.28, v5.2.29, v5.2.3, v5.2.30, v5.2.31, v5.2.32, v5.2.33, v5.2.34, v5.2.35, v5.2.36, v5.2.37, v5.2.38, v5.2.39, v5.2.4, v5.2.40, v5.2.42, v5.2.43, v5.2.44, v5.2.45, v5.2.5, v5.2.6, v5.2.7, v5.2.8, v5.2.9].

### Steps To Reproduce:
In old project remove vendor directory and composer.lock
run composer install

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.

Thanks!

**Comment by kerog** [comment]
Hey thanks for your replay, I figured what happens in my configuration.
One of package (barryvdh/laravel-snappy) set requirement to illuminate/filesystems and change reference to versions above 5.6.
