### ISSUE TITLE
postgresql partition table insert id in Eloquent model Undefined offset: 0

### ISSUE THREAD

**Issue by zhengwhizz** [laravel/framework#28042]
- Laravel Version: 5.6
- PHP Version: 7.2
- Database Driver & Version: postgresql 10

### Description:
I used the postgresql partition table, when i save a model, i got the notice and can't get the insert id.
`PHP Notice:  Undefined offset: 0 in /laravel/framework/src/Illuminate/Database/Query/Processors/PostgresProcessor.php on line 20`
and the saved event doesn't fired. but if i using 
` DB::getPdo()->lastInsertId();` , I can get the id. 
How do i avoid the ? 

Now, I want to extend the `insertGetId` of Builder, but i don't know how to do it ?
I wrote some code like this:
`trait PgsqlPartitionSave
{
    public function save(array $options = [])
    {
        $saved = false;
        try {
            $saved = parent::save($options);
        } catch (\ErrorException $e) {
            if (strpos($e->getMessage(), 'Undefined offset: 0') === false) {
                throw $e;
            }
            $saved = true;
        }
        if ($saved && !$this->id) {
            $this->exists = true;
            parent::finishSave($options);
            $this->id = (DB::select("select currval('{$this->getTable()}_id_seq') as id"))[0]->id;
        }
        return $saved;
    }

}`
 but i'm not sure if there will be any bad effects. and i think it's not a good way.

### Steps To Reproduce:
1. make a set of partition tables
2. using a model->save()

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.

Thanks!
