### ISSUE TITLE
Facade is not a singleton within phpunit tests

### ISSUE THREAD

**Issue by fideloper** [laravel/framework#28053]
- Laravel Version: **5.8.8**
- PHP Version: **7.1.23** (mac PHP), **7.2** (Vessel - docker)
- Database Driver & Version: **None used**

### Description:

Creating a Facade usually acts as a singleton for the "facade root".

I have a facade who's root has some state on it (an array of strings).

This state is kept when the Facade is used within a web request.

However this the Facade has no state within a phpunit test.

### Steps To Reproduce:

This can be replicated on a new project with just a few additions. The following test repository is setup to illustrate it:

```bash
# For SSH based:
# git clone git@github.com:fideloper/facade-bug.git

# For HTTPS based:
git clone https://github.com/fideloper/facade-bug.git

cd facade-bug

# Start a test web server, in a new terminal tab:
php artisan serve 

# You'll see the facade's state (an array of data) is returned in the web request
# Terminal:
curl http://127.0.0.1:8000/test

# Open in browser on Mac:
open http://127.0.0.1:8000/test

# Test that hits the same `/test` route fails:
./vendor/bin/phpunit
```

The test failure `Failed asserting that two strings are equal.`:

```diff
--- Expected
+++ Actual
@@ @@
-'["bar","foo"]'
+'[]'
```

This commit contains all code that was added to reproduce this:

https://github.com/fideloper/facade-bug/commit/a34e818bbcb7bbb355c06428d7060a0eb47c7391

I may just have a bad assumption about how Facades should be used, however this worked on a project on Laravel 5.7, so it seems something changed in a way that feels like a bug.

**Comment by driesvints** [comment]
There have indeed been some changes to facades. I see that Nuno already sent in a PR. If you apply that patch to your project does it fix the issue?

**Comment by fideloper** [comment]
Hi!

The patch does fix this issue!

Like both of you, I'm unclear on the implications of this. Interestingly, it's placement is 3 years old based on the `blame` from the current `5.8` branch.

![image](https://user-images.githubusercontent.com/467411/55233715-58cb4800-51f7-11e9-9a30-b7e125201bb4.png)

**Comment by driesvints** [comment]
@fideloper awesome. Let's wait and see what Taylor says on the PR :)

**Comment by driesvints** [comment]
Since the PR was rejected we'll first have to figure out if the proposed solution has unintended side effects.

**Comment by imanghafoori1** [comment]
yeah, I have encountered this before, the boot process of the framework does not happen after you call an end point like this : `$response = $this->get('/test');`
so the providers do not get called, as the result of that. 

So I changed my testing strategy since I was getting false greens.

In other words :
calling `$this->get('/test');` does not exactly simulate an http call from an external client like postman or a browser.

**Comment by taylorotwell** [comment]
I think @nunomaduro's PR was essentially correct. I will go ahead and make that change. If it breaks we will revert it but the current behavior doesn't seem totally correct to me. With the current code you could still have swapped facades in place during your afterCreatingApp callbacks which seems odd.
