### ISSUE TITLE
Request::getClientIp method missed null return type declaration

### ISSUE THREAD

**Issue by vaniyokk** [laravel/framework#28056]
- Laravel Version: 5.8.7
- PHP: 7.2.4

### Description:
There is a difference in declared return type for `Illuminate\Http\Request::ip()` method wrapper and method from base class 
https://github.com/laravel/framework/blob/5.8/src/Illuminate/Http/Request.php#L272
https://github.com/symfony/http-foundation/blob/master/Request.php#L795

Some libraries use documented return type for type checking and error throws unexpectedly when method return **null** value (it's not a rare case when using proxies), like here
https://github.com/cyrildewit/eloquent-viewable/blob/master/src/Resolvers/IpAddressResolver.php#L26

I think return types should match between both declarations.

### Steps to reproduce:
Request::ip() can return null in some environments, behind proxy

**Comment by driesvints** [comment]
Please fill out the entire issue template.

**Comment by driesvints** [comment]
The return type should indeed match the one from Symfony.
