### ISSUE TITLE
Call to undefined method Symfony\Component\HttpFoundation\StreamedResponse::content()

### ISSUE THREAD

**Issue by Tarasovych** [laravel/framework#28058]
- Laravel Version: 5.7.28
- PHP Version: 7.2.14
- Database Driver & Version: MySQL 5.7
- PHPUnit 7.5.8

### Description:

> Call to undefined method Symfony\Component\HttpFoundation\StreamedResponse::content()

is thrown when response content is an object of `StreamedResponse`.

### Steps To Reproduce:
```php
//route
    Route::get('image', 'ImageController@image')->name('image');

//ImageController@image
    public function image(Request $request)
    {
        return Storage::download('path-to-any-image');
    }

//test
    public function testImage()
    {
        $response = $this->json('GET', \route('image'));
        dd($response->content());
    }

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.

Thanks!
