### ISSUE TITLE
Rendering view causes further code in controller to be ommited from execution

### ISSUE THREAD

**Issue by tasteitnow** [laravel/framework#28060]
- Laravel Version: 5.7, 5.8
- PHP Version: 7.2
- Database Driver & Version: Mysql 

### Description:
Unable to assign rendered view to a variable in order to pass it in JSON Response to ajax call

### Steps To Reproduce:

Setup web/routes:

`Route::post('/cart/add', 'CartController@addToCartAjax')->name('add-to-cart-ajax');`

Create controller class:

```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Response;

class CartController extends Controller
{
    public function addToCartAjax(Request $request)
    {
        $product = ['id' => '1', 'name' => 'test'];
        $status = 'success';
        $modalContent = view('modals.added_to_cart.content', ['product' => $product])->render();
        $response = [
            'product' => json_encode($product),
            'modalContent' => $modalContent,
        ];

        return Response::json(['body' => $modalContent, 'product' => $product]);

    }
}
```

Add JS to view:

```

    <script type="text/javascript">
        function addToCart(id, value) {
            $.ajax({
                url: "cart/add",
                type: 'post',
                data: {
                    "_token": "{!!  csrf_token() !!}",
                },
                dataType: 'text',
                success: function (response) {
                    console.log(response);
                    response = jQuery.parseJSON(response);
                    console.log(response);
                },
                error: function (response) {
                    console.log('error');
                    console.log(response);

                }
            });
        }


    </script>
```

create views that is supposed to be rendered and passed back to ajax:
`views/modals/added_to_cart.blade.php`:
```
@include('modals.added_to_cart.content')
```

`views/modals/added_to_cart/content.blade.php`:
```
{{dd($product)}}
```

Now setup a link/button with 
`<a href="#" onclick="addToCart(0,1)">Docs</a>`

### Expected behavior

Return JSON Response to Ajax call. 

### Actual behavior

Anything after line 14 in CartController isn't executed:
 `$modalContent = view('modals.added_to_cart.content', ['product' => $product])->render();`

What's the response to Ajax call? Just plain HTML. The response isn't in json, it's just plain rendered view. 

It behaves like the line would be:

`return view('modals.added_to_cart.content', ['product' => $product])->render();`

I've searched web for 2 hours, every possible guide/tutorial/docs say you can render and assign the rendered view (HTML string) to variable. Unfortunately not in my case.

Tried on 3 different versions, tried on fresh clean install. Same result everytime.

**Comment by driesvints** [comment]
You're creating api routes in the web routes php file. It's best that these go in your api routes file. It's also best to send along an `Accepts` header with an `application/json` value so you tell the app to expect json back.

If you get an error back with the solution above you should get a json payload instead. 

In any case, this is more a support question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by tasteitnow** [comment]
You didn't answered any of my concerns nor questions.

This isn't an issue with how the route is setup, besides this ain't an API call.

The issue is about  `view('xx')->render()` behaving like `return view('xx')->render()`

Can you confirm this is intended behaviour?

**Comment by driesvints** [comment]
> The issue is about view('xx')->render() behaving like return view('xx')->render()

I suspect that an exception is thrown in this case. Can you please try asking on a support channel?

**Comment by tasteitnow** [comment]
No difference with: 

```
        headers: {
            Accept: "application/json",
        },
```



> I suspect that an exception is thrown in this case. Can you please try asking on a support channel?

There's no exception on the road, it returns the rendered view but omits any code execution down the line.

Literally behaves like 
```
return view('xxx')->render()
```

> If you get an error back with the solution above you should get a json payload instead.

So it's a bug but let's close this because you can use json payload?

**Comment by driesvints** [comment]
Ok. I'll help you debug this step by step. Going through your original message I have the following questions:

> Add JS to view:

Which view do I add this to? How is this view called?

> Now setup a link/button with

Where do I do this? How is this shown to the user?

**Comment by tasteitnow** [comment]
Insert following code inside welcome.blade.php (fresh new project):

```
<script
            src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>

    <script type="text/javascript">
        function addToCart(id, value) {
            $.ajax({
                url: "cart/add",
                type: 'post',
                data: {
                    "_token": "{!!  csrf_token() !!}",
                },
                dataType: 'json',
                success: function (response) {
                    console.log(response);
                    response = jQuery.parseJSON(response);
                    console.log(response);
                },
                error: function (response) {
                    console.log('error');
                    console.log(response);

                }
            });
        }


    </script>
```

Change the first link in `welcome.blade.php` so it can behave as the ajax submitter:
```
<a href="#" onclick="addToCart(0,1)">Docs</a>
```

**Comment by tasteitnow** [comment]
@driesvints It was my fault and PEBKAC.

I've forgot dd isn't var_dump(), it's die(var_dump());

**Comment by driesvints** [comment]
@tasteitnow that's ok, no worries. Glad you figured it out. But next time do try to ask this on a support channel first before trying the issue tracker. You wouldn't believe how many issues we get where the actual bug was somewhere in the application's code. 

Have a great weekend!
