### ISSUE TITLE
snake_case function not converting field ending with a number

### ISSUE THREAD

**Issue by e200** [laravel/framework#28083]
- Laravel Version: 5.7
- PHP Version: 7.2
- Database Driver & Version: MySQL

Laravel's `snake_case` helper not converting fields ending with numbers, ex: `snake_case('line1')` returns `line1` instead of `line_1`.

I'm using mass assignment and would be cool if `snake_case` function take care of it so I don't need to create each model manually.

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!
