### ISSUE TITLE
Without catch, thrown exception result in error page

### ISSUE THREAD

**Issue by lubobill1990** [laravel/framework#28087]
- Laravel Version: 5.8
- PHP Version: 7.3
- Database Driver & Version: MySQL 5.7

### Description:
https://github.com/illuminate/mail/pull/22
In theory, the `try finally` block can catch any exception without specific handling process. But in Mailer.php, when Swift_TransportException  is thrown, the `try finally` block doesn't avoid error.

### Steps To Reproduce:
Just send a mail to a mailer sever which is unaccessible.

**Comment by sisve** [comment]
> In theory, the try finally block can catch any exception without specific handling process.

No, a try-finally will not catch any exceptions at all. The finally block will execute before any the correct exception handler is executed. The finally block usually have some minor cleanup code.

https://www.php.net/manual/en/language.exceptions.php

**Comment by lubobill1990** [comment]
@sisve get it, thanks. So I should catch the exception by myself.

**Comment by driesvints** [comment]
@lubobill1990 yes.
