### ISSUE TITLE
Laravel storage file not found on hosting server.Is there an special way to symlink?

### ISSUE THREAD

**Issue by FCMW** [laravel/framework#28088]
I have setup a server for my laravel application.

This is my folder structure

```
/var/www/html/
        |___ MYDOMAIN.COM
                |___ MYDOMAIN_UAT           ( Contains index.php and assets)
                |___ MYDOMAIN_UAT_STAGING   ( Contains rest of the project)
```
My problem is file storage is not working on this UAT application. When i'm trying to access the files it returns a 404.

I have linked the storage using php artisan storage:link, and also using 
`ln -sfv /var/www/html/egig2go.com/egig_uat_staging/storage  /var/www/html/egig2go.com/egig_uat_staging/public`

This only happens on the server. Working fine on localhost.

Also file upload is working fine. File is uploaded to the correct folder.

This occurs only when i'm trying to get the file. (ex: Show the uploaded image in the frontend)

Like this,

`<img src="{{asset('storage/avatars/BDTQ7lPqFByfvBK1dF7RaA0zjJXT2NHppseyXmOZ.jpeg')}}">`

I'm trying to show the uploaded file in the frontend, but file is not loading.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
