### ISSUE TITLE
event:list throws an exception if the Listeners directory does not exist

### ISSUE THREAD

**Issue by sebdesign** [laravel/framework#28092]
- Laravel Version: 5.8.9
- PHP Version: 7.2
- Database Driver & Version: N/A

### Description:

When running `php artisan event:list` that was introduced in #28085 on an application that doesn't have an `app/Listeners` directory,
an `InvalidArgumentException` is thrown from the `in` method of the Symfony Finder, because it can't find that directory.

I believe this exception will also occur in the `EventServiceProvider` when `shouldDiscoverEvents` returns true, because the `DiscoverEvents` class will be invoked.

### Steps To Reproduce:

```bash
laravel new blog
cd blog
php artisan event:list
```

**Comment by driesvints** [comment]
Ping @themsaid

**Comment by themsaid** [comment]
opened a PR to exclude non-existing directories:

https://github.com/laravel/framework/pull/28098
