### ISSUE TITLE
Decimal column with float $casts attribute cast as string instead

### ISSUE THREAD

**Issue by vpillinger** [laravel/framework#28103]
- Laravel Version: 5.6.39
- PHP Version: 7.3.1-1+ubuntu18.04.1+deb.sury.org+1
- Database Driver & Version: sqlite (the one that comes with homestead)

### Description:
I have come across a bug where floats such as 0.8 do not cast to floats, but rather strings. 
This is an issue at least in sqlite (as it breaks my feature tests), but possibly with other drivers as well.

### Steps To Reproduce:

Given AnalyticData class
Migration
`
$table->decimal('percent_in_decimal_form ')->unsigned()
`
Class
```
class AnalyticData extends Model {
    protected $casts = [
        'percent_in_decimal_form ' => 'float',
    ];
}
```
Test - Logs "string"
`
\Log::info(gettype($play->percent_in_decimal_form ));
`

Possibly related to #8972

Edit: Fixed variable name being different across example.

**Comment by staudenmeir** [comment]
Is it `percent_in_decimal_form` or `percent_into_video`?

**Comment by vpillinger** [comment]
It is `percent_in_decimal_form`.
I was copying the example out of my code and changed the variable name, but missed changing that one place.

**Comment by staudenmeir** [comment]
There is a trailing space in `'percent_in_decimal_form ' => 'float',`. Do you also have that in your code?

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.

Thanks!
