### ISSUE TITLE
Queued Notifications with Dependency Injection can have problems with Serialization

### ISSUE THREAD

**Issue by DarkGhostHunter** [laravel/framework#28104]
- Laravel Version: 5.8.9
- PHP Version: 7.3.3
- Database Driver & Version: SQLite 3

### Description:

Queued Notifications that use Dependency Injection can not be serialized when there is a Service or Class with Closures. 

This will make the queue job fail miserably, with PHP saying "Serialization of Closure is not allowed"

### Steps To Reproduce:

Create a Queueable Notification with a Service containing a Closure, like the UrlGenerator that ships with Laravel.

```
namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Routing\UrlGenerator;
use Illuminate\Notifications\Notification;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;

class UnserializableNotification extends Notification implements ShouldQueue
{
    use Queueable;

    /**
     * The URL Generator, that uses Closures.
     *
     * @var UrlGenerator 
     */
    protected $url;

    /**
     * LoginAttemptNotification constructor.
     *
     * @param bool $remember
     * @param string|null $intended
     * @param Config $config
     * @param Url $url
     */
    public function __construct(UrlGenerator $url)
    {
        $this->url = $url;
    }

    /**
     * Get the notification delivery channels.
     *
     * @param mixed $notifiable
     * @return array
     */
    public function via($notifiable)
    {
        return ['mail'];
    }

    /**
     * Get the mail representation of the notification.
     *
     * @param mixed $notifiable
     * @return \Illuminate\Notifications\Messages\MailMessage
     */
    public function toMail($notifiable)
    {
        return (new MailMessage)
            ->greeting('If you see this...'))
            ->line('... some magic worked because this is not serializable');
    }
}
```

I suspect this happens being done because the Queue [creates the object payload using the `serialize()` function](https://github.com/laravel/framework/blob/e6c8aa0e39d8f91068ad1c299546536e9f25ef63/src/Illuminate/Queue/Queue.php#L138), and the [Notification Class](https://github.com/laravel/framework/blob/e6c8aa0e39d8f91068ad1c299546536e9f25ef63/src/Illuminate/Notifications/Notification.php) doesn't know how to deal with serializing instances that include Closures, meaning, using Dependency Injection in the `__construct` can become very troublesome.

Are we bound to use `app()` inside the notification for better certainty of not crashing the queue job?

**Comment by devcircus** [comment]
Definitely can't serialize closures. It's a PHP shortcoming. It's not just Notifications and it's not just laravel.

**Comment by laurencei** [comment]
@devcircus - there are packages like https://github.com/opis/closure that do allow for it.

But is this a bug, or a framework feature request? I'll let Dries decide...

**Comment by devcircus** [comment]
Definitely not a bug. It's been discussed many many times. It would be a great improvement. 

Same with caching routes with a closure. It rears it's head in many places.

**Comment by driesvints** [comment]
I think it's indeed best that we discuss this in ideas further to tackle all the concerns before proceeding with this.
