### ISSUE TITLE
cannot see digest function inside Postgresql stored function 

### ISSUE THREAD

**Issue by azegurb** [laravel/framework#28115]
- Laravel Version: 5.7.*
- PHP Version: 7.1.3
- Database Driver & Version: pgsql

### Description:
Recently I have created stored function in **Postgres SQL** which deals about with hashing passwords. When queryied via **PgAdmin** tool or pure **PHP** it works like a charm.

### Steps To Reproduce:
My **Laravel** code to select stored function.

`$token=\DB::select("SELECT * from \"horeca_user\".update_token('$type', '$user_id', '$token')");`

And my pure **PHP** code
```
$db = new PDO("pgsql:dbname=Horecami;host=127.0.0.1", "postgres", "1" );
$sql = 'Select horeca_user.update_token(?, ?, ?)';
$stmt = $db->prepare($sql);
$type=1;
$id=1;
$z='az';
$stmt->bindValue(1, $type, PDO::PARAM_INT);
$stmt->bindValue(2, $id, PDO::PARAM_INT);
$stmt->bindValue(3, $z, PDO::PARAM_STR);
$stmt->execute();
$res=$stmt->fetchAll();
return $res;
```

And finally my PostgreSql function code.

```
CREATE OR REPLACE FUNCTION horeca_user.update_token(tp integer,userid integer,token character varying)
    RETURNS character varying
    LANGUAGE 'plpgsql' VOLATILE
    PARALLEL UNSAFE
    COST 100
AS $BODY$ 
DECLARE uid INTEGER;
DECLARE tok character varying;
BEGIN
    uid:=0;
    Select count(*) as total from horeca_user.user_tokens where user_id=$2 into uid;

    if uid=0 THEN
       Insert into horeca_user.user_tokens(id, user_id, tip) values($3, $2, $1);
     else
       Update horeca_user.user_tokens set id=$3, tip=$1 where user_id=$2;
     END IF;

     SELECT encode(digest(token, 'sha256'), 'hex') as tt into tok;

     return tok;
END

$BODY$;
```
Finally I would like state that the problem is associated only this line in stored function that shown below. If I delete this line everything works as expected.

`SELECT encode(digest(token, 'sha256'), 'hex') as tt into tok;`

Thanks all who payed attention and i wish this problem will arise in next versions of Laravel framework.

**Comment by staudenmeir** [comment]
What's the error message?

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.

Thanks!

**Comment by azegurb** [comment]
İt gives this error
```
[2019-03-31 18:49:30] local.ERROR: SQLSTATE[42883]: Undefined function: 7 ERROR:  function digest(character varying, unknown) does not exist
LINE 1: SELECT encode(digest(token, 'sha256'), 'hex') as tt
                      ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
QUERY:  SELECT encode(digest(token, 'sha256'), 'hex') as tt
CONTEXT:  PL/pgSQL function update_token(integer,integer,character varying) line 14 at SQL statement (SQL: SELECT * from "horeca_user".update_token('2', '174', 'az')) {"userId":174,"email":"azegurb@gmail.com","exception":"[object] (Illuminate\\Database\\QueryException(code: 42883): SQLSTATE[42883]: Undefined function: 7 ERROR:  function digest(character varying, unknown) does not exist
LINE 1: SELECT encode(digest(token, 'sha256'), 'hex') as tt
```

**Comment by azegurb** [comment]
> Hey there,
> 
> Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.
> 
> Thanks!

I just created new **Laravel** project and connected to **Posgresql** database, and again tested stored function call, same problem exists again.
Can you help me?

**Comment by driesvints** [comment]
@azegurb does it also occur on the latest version? (5.8.10)

**Comment by azegurb** [comment]
yes I upgraded it to latest version (5.8.3)

**Comment by staudenmeir** [comment]
Does `DB::select("SELECT encode(digest('abc', 'sha256'), 'hex')");` work?

Does `DB::select("SELECT * FROM pg_extension")` contain `pgcrypto`?

**Comment by azegurb** [comment]
> Does `DB::select("SELECT encode(digest('abc', 'sha256'), 'hex')")`; work?


No It does not work. I tested it, 
It throws error like this.
`"message": "SQLSTATE[42883]: Undefined function: 7 ERROR:  function digest(unknown, unknown) does not exist\nLINE 1: SELECT encode(digest('abc', 'sha256'), 'hex')\n                      ^\nHINT:  No function matches the given name and argument types. You might need to add explicit type casts. (SQL: SELECT encode(digest('abc', 'sha256'), 'hex'))",`

> Does `DB::select("SELECT * FROM pg_extension")` contain pgcrypto?
And I tested it. This works. This gave me this.

```
[
    {
        "extname": "plpgsql",
        "extowner": 10,
        "extnamespace": 11,
        "extrelocatable": false,
        "extversion": "1.0",
        "extconfig": null,
        "extcondition": null
    },
    {
        "extname": "pgcrypto",
        "extowner": 10,
        "extnamespace": 2200,
        "extrelocatable": true,
        "extversion": "1.3",
        "extconfig": null,
        "extcondition": null
    }
]
```

**Comment by staudenmeir** [comment]
Does `SELECT encode(digest('abc', 'sha256'), 'hex')` work with pure PHP? Is this code using the same credentials as Laravel?

**Comment by azegurb** [comment]
Yes it works with pure PHP like below.

   ```
$sql = "SELECT encode(digest('abc', 'sha256'), 'hex')";
   $stmt = $db->prepare($sql);
   $stmt->execute();
    $res=$stmt->fetchAll();
   print_r($res);
```

I changed `**digest** ` to `**public.digest**`  inside stored function, then it finally worked for Laravel.
Thanks to all who payed attention. I was struggling about two weeks.

**Comment by avyadro** [comment]
> > Does `DB::select("SELECT encode(digest('abc', 'sha256'), 'hex')")`; work?
> 
> No It does not work. I tested it,
> It throws error like this.
> `"message": "SQLSTATE[42883]: Undefined function: 7 ERROR: function digest(unknown, unknown) does not exist\nLINE 1: SELECT encode(digest('abc', 'sha256'), 'hex')\n ^\nHINT: No function matches the given name and argument types. You might need to add explicit type casts. (SQL: SELECT encode(digest('abc', 'sha256'), 'hex'))",`
> 
> > Does `DB::select("SELECT * FROM pg_extension")` contain pgcrypto?
> > And I tested it. This works. This gave me this.
> 
> ```
> [
>     {
>         "extname": "plpgsql",
>         "extowner": 10,
>         "extnamespace": 11,
>         "extrelocatable": false,
>         "extversion": "1.0",
>         "extconfig": null,
>         "extcondition": null
>     },
>     {
>         "extname": "pgcrypto",
>         "extowner": 10,
>         "extnamespace": 2200,
>         "extrelocatable": true,
>         "extversion": "1.3",
>         "extconfig": null,
>         "extcondition": null
>     }
> ]
> ```

CREATE EXTENSION pgcrypto
    SCHEMA public;
