### ISSUE TITLE
show() abilitie does not work in policy

### ISSUE THREAD

**Issue by guilhermeagirardi** [laravel/framework#28119]
- Laravel Version: 5.8.10
- PHP Version: 7.2.7
- Database Driver & Version: MySQL 5.7.21 (x64)

### Description:
After creating a policy for a resource controller, I realized that the `store()`, `update()`, and `destroy()` actions are mapped correctly, they respectively call the `create()`, `update()`, and `delete()` abilities, but for some reason the `show()` abilitie does not work.
The result is always error 403 - Unauthorized.

### Steps To Reproduce:
UserPolicy.php
```php
<?php
namespace App\Policies;

use Illuminate\Auth\Access\HandlesAuthorization;

class UserPolicy {
    use HandlesAuthorization;

    public function view() {
        Log::info('This will NOT BE displayed in the log!');
        return true;
    }
...
```
UsersController.php
```php
<?php
namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;

class UsersController extends Controller
{
    public function __construct()
    {
        Log::info('This will BE displayed in the log!');
        $this->authorizeResource(User::class);
    }

    public function index() {
        Log::info('This will NOT BE displayed in the log!');
        return User::all();
    }
...
```

**Comment by krve** [comment]
I am unable to reproduce this.

The `index` method is not protected by any Gate when you use `authorizeResource(User::class)`  
https://github.com/laravel/framework/blob/f735b3d5ee81b59984da1a652f2665313a6fdb69/src/Illuminate/Foundation/Auth/Access/AuthorizesRequests.php#L105-L115

In your `UserPolicy` you also have to specify the user $parameter, e.g. `User $user` before it works.

Also remember, if the authorization allows unauthorized users you need to make the `$user` parameter nullable, so like:
```php
public function view(User $user = null) {
    Log::info('This will NOT BE displayed in the log!');
    return true;
}
```

**Comment by guilhermeagirardi** [comment]
Sorry, I wrote it right and sent the wrong code.
This question you commented on the `index()` mapping I am aware of. I mean the `show()` action that calls the ability to `view()` (or should at least call).

Correcting:
UsersController.php
```php
<?php
namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;

class UsersController extends Controller
{
    public function __construct()
    {
        Log::info('This will BE displayed in the log!');
        $this->authorizeResource(User::class);
    }

    //It does not work
    public function show(User $user) {
        Log::info('This will NOT BE displayed in the log!');
        return $user;
    }

    //It works
    public function store(Request $request) {
        return User::create($request->all());
    }

    //It works
    public function update(Request $request, User $user) {
        $user->update($request->all());
        return $user;
    }

    //It works
    public function destroy(User $user) {
        $user->delete();
        return $user;
    }
}
```

UserPolicy.php
```php
<?php
namespace App\Policies;

use Illuminate\Auth\Access\HandlesAuthorization;
use Illuminate\Support\Facades\Log;

class UserPolicy
{
    use HandlesAuthorization;

    //It does not work
    public function view()
    {
        Log::info('This will NOT BE displayed in the log!');

        return true;
    }

    //It works
    public function create()
    {
        return true;
    }

    //It works
    public function update()
    {
        return true;
    }

    //It works
    public function delete()
    {
        return true;
    }
}
```

**Comment by krve** [comment]
You are still missing the `$user` param in your policy.
```php
<?php
namespace App\Policies;

class UserPolicy
{
    use HandlesAuthorization;

    public function view($user = null)
    {
        return true;
    }

    // ...
}
```

If you don't specify the user param it doesn't work. Even if you don't require it, I'm pretty sure you have to specify it.

I just tested the above example, and it worked as expected.

**Comment by driesvints** [comment]
Heya, please try with the suggestion above.
