### ISSUE TITLE
Laravel Command "make:auth" don't check entries already exists

### ISSUE THREAD

**Issue by cryptncyrix** [laravel/framework#28116]
- Laravel Version: >=5.7
- PHP Version: >=7.1
- Database Driver & Version: all

### Description:
Laravel Auth Command "make:auth", it's not checked whether the entries already exist in web.php.

### Steps To Reproduce:
php artisan make:auth | return
php artisan make:auth | return
and it will set this

```html
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
```

For Example: 

```html
$routesContents = file_get_contents(base_path('routes/web.php'));
$stubsContents = file_get_contents(__DIR__.'/stubs/make/routes.stub');
if(strpos($routesContents, $stubsContents))
{
            dd('found');
 }
 dd('notfound');
```

**Comment by ahinkle** [comment]
Related: #22947, #15653

**Comment by driesvints** [comment]
It's best to use source control to not lose your original changes. In any case if this behavior should change than this is more of a behavioral change rather than a bug (see closed prs). Please post this in the ideas repo to get support for your idea. After that you could send in a PR.

**Comment by iamazik** [comment]
@driesvints Submitted it into the ideas repo. https://github.com/laravel/ideas/issues/1677
