### ISSUE TITLE
withInput and withErrors not Working on Huawei with Chrome

### ISSUE THREAD

**Issue by razchen** [laravel/framework#28125]
- Laravel Version: 5.8
- PHP Version: 7.*
- Database Driver & Version:

Created a new Laravel project and used the example .env file.
I haven't changed anything there except of adding the routes in web.php, creating a basic controller and creating a simple view of a form.

When redirecting either with back() or with to() and adding withInput() or withErrors() is not working, and that's only happening on Huawei phones with Chrome. I tried it in incognito mode in Chrome and it does work. 

I have also tested on Mac, iOS and Samsung and it does work. Also on Firefox it works on Huawei phones. The only way I managed to make it work with Chrome and Huawei is if I change the the form action to a different route than the route of the form, so if I the form's route is /testb and the POST route is /testb2 then it does work. Also, if I print anything to the screen from the controller itself, then it will work.

Basically it does not pass the session variables of the old input nor the session variables of the errors to the view while the middleware ShareErrorsFromSession is available for web in Kernel.php (it's enabled when creating a new Laravel project).

In the controller itself the session variables do show! 

I have tested it in a hosted Laravel on Ubuntu and CentOS and on different domains with different extensions. I've tried the put() on some test variables and they are saved. I of course followed all the installation steps from laravel.com and have given the correct file and directory permissions to the storage directory (even tried 777).

I have also tested it in Laravel 5.3 with PHP 5.6 and it did work.
I tried deleting all the privacy data in Chrome from all times in my Huawei mate20 lite and have also tried it on a Huawei m8.

Please help as I'm going insane with this for the last 4 days. Did I miss something? I have looked all over the internet for answers and couldn't find anything.

You can find a demo here:
[http://www.empty2.ml/testb](url)

### Steps To Reproduce:
I have created this test controller:

```
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Validator;

class TestController extends Controller
{
    public function testb()
    {
        return redirect()->to('/testb')->withInput();
    }

    public function testbForm()
    {
        return view('testb');
    }
}
```

And this form:
```
<form role="form" method="POST" class="main-second-font" action="testb">
    @csrf
    <?php print_r($errors) ?>

    <input type="text" name="username" id="username" class="form-control" tabindex="1" value="{{ Request::old('username') }}">

    <input type="submit" value="go" class="btn btn-primary" tabindex="11">
</form>
```

web.php:
```
Route::post('/testb', 'TestController@testB');
Route::get('/testb', 'TestController@testbForm');
```

**Comment by laurencei** [comment]
This is clearly a session bug in the Huawei phones or browser and has nothing to do with Laravel...

**Comment by driesvints** [comment]
This seems to be vendor specific. You can try one of the following support channels perhaps:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
