### ISSUE TITLE
Horizon Job: ErrorException: Warning: PDO::prepare(): MySQL server has gone away

### ISSUE THREAD

**Issue by keithbrink** [laravel/framework#28127]
- Laravel Version: 5.7.28
- PHP Version: 7.2.15
- Database Driver & Version: MariaDB 10.2.23

### Description:
Hey there, I am struggling with a bug on my production server using Horizon. 

ErrorException: Warning: PDO::prepare(): MySQL server has gone away
[internal] in unserialize

You can see a stack trace of the error here: https://sentry.io/share/issue/b105b7946b524a9e841f56f44445ea14/

As far as I can tell, this error should be caught by the Laravel framework (#19080, #19263). I'm not sure why it's not being caught and turned into a QueryException which would then trigger the reconnection and/or killing the worker.

This is an occasional error so it's difficult to reproduce; I've tried to manually throw a similar error but it is caught properly and handled properly. 

Any insight into how I can fix this would be appreciated.

**Comment by driesvints** [comment]
Hi there,

It's best that you opened this on the Horizon issue tracker: https://github.com/laravel/horizon/issues

Also: this seems like a problem with your MySQL server which has connectivity issues. Please try asking this on a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
