### ISSUE TITLE
Queued Event Subscribers always in the default queue

### ISSUE THREAD

**Issue by jf-m** [laravel/framework#28132]
- Laravel Version: 5.7.28
- PHP Version: 7.1.8
- Database Driver & Version: MySql + Redis

### Description:
The queued subscribers is always pushed into the `default` redis queue and not in the one defined in the subscribers itself (using `$queue` property).

I've tried both methods: using `public $queue` and using the `Queueable` trait + `onQueue` method.

Note that the subscribers **does** works and gets fired, just in the wrong redis queue.

### Steps To Reproduce:

1.  Create a subscribers following the [https://laravel.com/docs/5.8/events#event-subscribers](doc)
2. Make the subscriber implements the `ShouldQueue` interface
3. Add the `public $queue = 'low';` property in your subscriber.
4. Fire an event that your subscriber listens to.
5. Witness that the subscribers is queued under `default` redis queue, while it should have been pushed under the `low` redis queue.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.

Thanks!

**Comment by jf-m** [comment]
Hi there,

I've just upgraded to Laravel 5.8.10, the exact same behavior is happening.

The workaround is really easy though. Either:

- Start a queue worker for the `default` queue (in my case, I dont want a queue called "default").
- Rename the default queue to the name you want (e.g. `low`) in the config file `queue` => `queue.connections.redis.queue`.

So we could consider this bug as really low impact.

**Comment by devcircus** [comment]
For me, using the latest version of Laravel and redis, the $queue property works as expected. The correct queue is used.

**Comment by jf-m** [comment]
I just retried to reproduce it with Laravel 5.8.10, and I guess I was wrong on the whole description... I'm sorry about that.

The bug is not happening when using `public $queue = 'low';` but only when using :

`use Queueable;`

and `$this->onQueue('low');` directly in the __construct like so:

`
class MySubscriber implements ShouldQueue
{
    use Illuminate\Bus\Queueable;

    public function __construct()
    {
            $this->onQueue('low');
        //
    }
}`

Maybe it is the expected behavior because the Subscriber is not instanciated yet when pushing it onto the queue?

Sorry for the wrong description, my bad.

Thank for your help.

**Comment by devcircus** [comment]
Yes, the Queueable contract is designed to work with the Bus Dispatcher, not the Event Dispatcher. The Event Dispatcher only checks for the 'queue' property to decide which queue to use. As-is, the onQueue method will not work with Listeners. See #22880. Also see [previous issues concerning this](https://github.com/laravel/framework/issues?q=is%3Aissue+listener+onqueue+is%3Aclosed)
```php
// Illuminate\Events\Dispatcher::queueHandler
//...
$queue = $listener->queue ?? null;
```

**Comment by jf-m** [comment]
Got it, thank you!
