### ISSUE TITLE
Middleware is overwritten when the method is called twice

### ISSUE THREAD

**Issue by ludo237** [laravel/framework#28139]
- Laravel Version: 5.8.x
- PHP Version: 7.3
- Database Driver & Version: MariaDB using 10.3.x

### Description:
Not sure if this is intended or not but I notice that if you use the `->middleware()` twice inside a route declaration in `RouteServiceProvider` the last call will ignore the previous one. If it's intended shame on me 😅

### Steps To Reproduce:

Use the `web.php` or create a dedicated route file then in `RouteServiceProvider.php` type: 

```PHP
    protected function mapWebRoutes()
    {
        Route::middleware("web")
            ->middleware(EnsureEmailIsVerified::class)
            ->namespace($this->namespace)
            ->group(base_path("routes/web.php"));
    }
```

The expected results should be a merge between the two middleware but in reality only the last will be used. You can try with whatever middleware you want. For instance you could have a `FooBarMiddleware::class` that just dumps the `Auth::user()` and you will see that it's null.

Again if this is intended is a bit misleading. Of course the fix is easy, just use the array syntax with one method call.

**Comment by laurencei** [comment]
Personally I kind of feel this is expected/intended and not a bug, but I suppose I can see it from the other side too...?

**Comment by ludo237** [comment]
@laurencei Yea I still don't know if it's intended or not but if it is, then the possibility of chaining it would lead to this kind of subtle bugs.

**Comment by imanghafoori1** [comment]
I think after all it makes sense to describe the chain of middlewares as a this.
but after all there is no hard and fast rule. it's just personal preference of people.

**Comment by driesvints** [comment]
It's intended. It should be possible to do this on an actual route but the route registrar you can only set it one time.
