### ISSUE TITLE
eloquent's withCount() not working with multiple db relationships. 

### ISSUE THREAD

**Issue by thearyanahmed** [laravel/framework#28136]
I'm using two separate database,DB A holds vendor information and DB B holds products information .I've specified the connection in both models.When I call Vendor::with('products'),everything is working but when I chain withCount('products') it gives me an error,saying table does not exists.Eloquent is looking for products table in DB.A as the vendor's database.

`Table 'DB_A.products' doesn't exist (SQL: select `vendors`.*, (select count(*) from `products` where `merchants`.`id` = `products`.`vendor_id`) as `products_count` from `vendors` where (`shop_slug` = 'Some-Slug') limit 1)`

**Comment by staudenmeir** [comment]
Please see #23042.

**Comment by thearyanahmed** [comment]
thanks
