### ISSUE TITLE
sum() aggregate method issue on negative zero output

### ISSUE THREAD

**Issue by afbora** [laravel/framework#28148]
- Laravel Version: 5.8.10
- PHP Version: 7.3.3
- Database Driver & Version: MySQL 5.7.25

### Description:

At first, this bug related with MySQL too.
I have sum() method on a model like that:
````
public function balance()
{
    return $this->balances() // Relationship
        ->sum('amount');
}
````

I have balances table and need to sum all rows.
But sometimes output could be negative zero (-0.00)

### Steps To Reproduce:
Test Values: 
 - 1693.620000
 - -1608.939000
 - -84.681000

Test it like following query:
> SELECT SUM(amount) FROM balances

When you sum these values, output will be on MySQL:  `-0.00`

Laravel output is : `-3.3750779948605E-13`

Expected output is: `0.00`

Related issue on MySQL: https://bugs.mysql.com/bug.php?id=9037

Can we produce a solution by casting aggregate return value on Laravel side?

Thanks
Best Regards

**Comment by staudenmeir** [comment]
What type of column is `amount` in your case?

**Comment by afbora** [comment]
@staudenmeir double(8,2)

**Comment by staudenmeir** [comment]
Are you using the column to store amounts of money?

**Comment by afbora** [comment]
@staudenmeir Yes, this is true.

**Comment by afbora** [comment]
@staudenmeir You right! When i changed the double to decimal, gives 0.00 as expected output.

Ok, i got that and i'll use decimal for money types.
But is this a bug still for double/float usages non-money columns?

**Comment by staudenmeir** [comment]
I don't think this is really a bug. Imprecisions like this are fundamental issues of floating point numbers.

Even if we would want to fix this in Laravel, I don't see how we could.

**Comment by driesvints** [comment]
I would indeed recommend to only use integers to store money values. Try to have a look at https://github.com/moneyphp/money for a userland implementation.
