### ISSUE TITLE
Laravel Session OverWriting Every Time On Each Request

### ISSUE THREAD

**Issue by DhavIndian** [laravel/framework#28147]
- Laravel Version: 5.8
- PHP Version: 7.2
- Database Driver & Version:

### Steps To Reproduce:
File 
vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php
Issue On Line Number 66
$this->saveSession($request);  
Due this function Session FIle is OverWritten in each and Every Request
This Causes Issues in Real Time System where repeated ajax request is present
This is not good to rewrite session on each and every request i temporary rewrite in vendor

if (!$request->ajax() || $request->saveSession === true) {
			$this->saveSession($request);
}

Please Solve As Soon

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by DhavIndian** [comment]
This is not a question why you closed without solving ....

**Comment by trevorgehman** [comment]
@DhavIndian Take a look at this: https://github.com/laravel/framework/issues/30996

There is a PR that attempts basically what you are proposing: https://github.com/laravel/framework/issues/30996
