### ISSUE TITLE
Shall we prepend phpdoc before softDeletes trait?

### ISSUE THREAD

**Issue by xiaohuilam** [laravel/framework#28144]
I mean patch
https://github.com/laravel/framework/blob/5a6450486461a4c91374987af248b968d17cc956/src/Illuminate/Database/Eloquent/SoftDeletes.php#L4-L6

to

```php
<?php
...

/**
 * @method static self|\Illuminate\Database\Eloquent\Builder withTrashed()
 * @method static self|\Illuminate\Database\Eloquent\Builder onlyTrashed()
 * @method static self|\Illuminate\Database\Eloquent\Builder withoutTrashed()
 */
trait SoftDeletes 
{ 
}
```

Should we?

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!
