### ISSUE TITLE
Named route not defined when using `->name()` method

### ISSUE THREAD

**Issue by zarehesmaiel** [laravel/framework#28143]
- Laravel Version: 5.8.*
- PHP Version: 7.2.*
- Database Driver & Version:

### Description:
When naming a route with `->name()` method, this causes an error `Route [home] not defined.` when calling `route('home')`; 

### Steps To Reproduce:

When named a route by `name` method like this:

`Route::get('/', 'Controller@handle')->name('home');`

and call `route('home');` after that, make error: `Route [home] not defined.`;

because when naming a route with `name()` method, this method dont update `$nameList` of `Illuminate\Routing\RouteCollection` so when calling that route with `rout()` function, cant find it.

**Comment by laurencei** [comment]
I use this method all the time and never experienced this.

Have you cleared all the cache using `route:clear`?

**Comment by zarehesmaiel** [comment]
> I use this method all the time and never experienced this.
> 
> Have you cleared all the cache using `route:clear`?

I found problem. i forget call `parent::boot()` when i extended base route serveice provider that causes removing `route lookups` after booting.

**Comment by staudenmeir** [comment]
Please close the issue.
