### ISSUE TITLE
Model config add param. to change directory

### ISSUE THREAD

**Issue by Rene-Roscher** [laravel/framework#28156]
Would be cool if you could create a config for models, with which you can deposit the folder where the models drine should be created, if you (artisan make: model NAME) that those in the folder are:> sorry for my English.

**Comment by ahinkle** [comment]
There are many ways developers can use models with multiple locations. You can automatically store models in a directory (eg. `App/Models`) by extending the Model Command and add your own directory.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not for ideas, suggestions etc. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. You are able to open a ticket at https://github.com/laravel/ideas

Alternatively you are able to open a PR using the Contributions guidelines: https://laravel.com/docs/5.7/contributions#which-branch

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
