### ISSUE TITLE
Laravel 5.8, Changing Columns Wrong Sql, at Prefixed Table

### ISSUE THREAD

**Issue by zarehesmaiel** [laravel/framework#28157]
- Laravel Version: 5.8.*
- PHP Version: 7.2.6
- Database Driver & Version:

### Description:
 
I want change integer column into string at migration that causes this error:

`SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '1e7e_users CHANGE status status VARCHAR(191) DEFAULT 'pending' NOT NULL' at line 1 (SQL: ALTER TABLE 1e7e_users CHANGE status status VARCHAR(191) DEFAULT 'pending' NOT NULL)` 
 

### Steps To Reproduce:

i have an `integer`  column with `status`  name  and want change it at my migration by this statement:
 
    Schema::table('users', function (Blueprint $table) {

         $table->string('status')->default(\Core\Crud\Statuses::key('pending'))->change(); 

    }); 

that causes top error. after two day working i found reason.

because my table has `prefix` and my `prefix started with integer`. 

and whats wrong ... !

the error come from of laravel sql. because at builded sql, `table name` unwrapped with quotation.

this is maked sql by laravel:
`ALTER TABLE 1e7e_users CHANGE status status VARCHAR(191) DEFAULT 'pending' NOT NULL`

that shoud build like this:
    ` ALTER TABLE '1e7e_users' CHANGE status status VARCHAR(191) DEFAULT 'pending' NOT NULL `

**Comment by staudenmeir** [comment]
This is not caused by Laravel itself but by the `doctrine/dbal` package.

#22402 is related to this, but the workaround can't be applied here.

You'll have to use a raw statement instead:

```php
DB::statement("ALTER TABLE `1e7e_users` CHANGE status status VARCHAR(191) DEFAULT 'pending' NOT NULL");
```

**Comment by staudenmeir** [comment]
You could also fix this by choosing a different prefix that doesn't start with a digit.
