### ISSUE TITLE
ModelNotFoundException on Laravel Job with SerializeModels...But fixed with delay!!!

### ISSUE THREAD

**Issue by pda-code** [laravel/framework#28154]
- Laravel Version: 5.8.9
- PHP Version: 7.2.3
- Database Driver & Version: MySql 8

### Description:
I've read the entire internet about the 
`Illuminate\Database\Eloquent\ModelNotFoundException: No query results for model [App\Ticket]` raised by a failed job that uses `SerializeModels `trait.

The strange thing is that ModelNotFoundException is raised even if the Model 100% exists on the database. I tried to deserialize the `payload `from the `failed_jobs `table and search one-by-one the primary keys and all exist in the database. There is a transaction in my code and AFTER it commits i raise some events that fires the same job. No way that the PK of Eloquent Models to be null because i do not create new models inside a transaction but i use existing models.

1. If i retry to run the failed_jobs **at a later time from the console**, jobs all executing successfully. No ModelNotFoundException exception
2. If i add a **delay on the job**, job is executing successfully. No  ModelNotFoundException exception
3. If i remove the delay, job fails with `ModelNotFoundException ` from `__wakeup `

### Steps To Reproduce:
I setup a listener for some events and every time i dispatch a job. The parameter for the job is a class that implements `INotificationEvent` interface.

![image](https://user-images.githubusercontent.com/10973438/55834540-d90c7a00-5b22-11e9-95fe-c6a00a1a282b.png)

**Comment by mfn** [comment]
Does it work if you just pass the id to the job and refetch the model there in?

**Comment by andrewbroberg** [comment]
Are you dispatching the job within a transaction? I had a similar issue where I was dispatching an event inside a transaction which hadn't been commited yet when the queue picked up the event.

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by pda-code** [comment]
Sorry for the delay....

This is the job 
![image](https://user-images.githubusercontent.com/10973438/56392950-8f671200-623b-11e9-9fb0-92703dfb0aef.png)

and the contrsuctor parameter `INotificationEvent $event` is an object that holds existing eloquent models.

From the code of `SerializeModels ` i understand that when the job is queued in Redis is serialized that is
- Every Property of `INotificationEvent $event` is traversed and serialized. If one or more properties are Eloquent Models are serialized in a special way as `new ModelIdentifier`.

In the deserialization process although ModelIdentifier points to an existing Id, without the delay always ModelNotFoundException raised.

I am raise event and dispatch jobs after i commit the transaction. But either way, the models are not new...are just models that already existed in the database

**Comment by driesvints** [comment]
So what I believe is happening is that you're trying to serialize an object containing models. This isn't wanted I believe with the `SerializeModels` trait. I think it only works if you try to serialize models directly as a property on the job. If you want to serialize other objects I believe you should only use scalars like model ids and retrieve them yourselves.

Btw, the hint is in the trait's name. It only serializes models and no other objects.

**Comment by pda-code** [comment]
This is all the classes involved a complete example

```
interface INotificationEvent
{
    public function getTicket();
    public function getUser();
}

class NotificationEventBase extends Event
{
    public $ticket = null; //Eloquent Model
    public $user   = null; //Eloquent Model

    public function __construct() {

    }

    public function load(int $ticket_id, int $user_id)
    {
        $this->ticket=loadTicketFromDb($ticket_id);
        $this->user=loadUserFromDb($user_id);
    }

    public function getUser() {
        return $this->user;
    }

    public function getTicket() {
        return $this->ticket;
    }
}

class TicketCreated extends NotificationEventBase implements INotificationEvent
{
    use SerializesModels;

    public function __construct(int $ticket_id, int $user_id) {
        parent::load($ticket_id, $user_id);
    }
}

class NotificationEngineJob implements ShouldQueue
{
    use InteractsWithQueue, Queueable, SerializesModels;

    public $payload = null;

    public function __construct(INotificationEvent $payload) {
        $this->payload = $payload;
    }

    public function handle() {
        //Somw code to handle
    }
}

///*******************************************************
///------------------ Finally --------------------------//
///*******************************************************
$data=new TicketCreated(1,2);
$job=(new NotificationEngineJob($data))->delay(60);
dispatch($job);






```

**Comment by oceanapplications** [comment]
This does still seem to exist as of v7.28.3.

I dispatch a job from a model observer's created event that accepts the newly created model. If I only create a few models, the jobs dispatch fine. Running code that creates 100s of models which dispatches 100s of jobs using the new models is where the problem occurs.

The jobs all run fine if I retry from Horizon so I don't believe it's a code problem. 

```#1 /home/forge/site.com/vendor/laravel/framework/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php(57): App\Jobs\SendWebHook->restoreModel()```

The error occurs during restore which leads me to believe the new models aren't available in the database yet. 

```
namespace App\Jobs;

use App\Models\Webhook;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Collection;

class SendWebHook implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public $tries = 0;
    public $maxExceptions = 3;

    protected Model $model;
    protected string $event;
    protected ?array $changed_from;
    protected ?array $changed_to;

    /**
     * Create a new job instance.
     *
     * @param Model $model
     * @param string $event
     * @param array $changed_from
     * @param array $changed_to
     */
    public function __construct(Model $model, string $event, ?array $changed_from, ?array $changed_to)
    {
        $this->model = $model;
        $this->event = $event;
        $this->changed_from = $changed_from;
        $this->changed_to = $changed_to;
    }

    public function retryUntil()
    {
        return now()->addHours(1);
    }

  public function handle() 
  {
     \Log::info(json_encode($this->model->getAttributes());
  }

}
```

The failure isn’t a problem, it should fail if the model isn’t available. The problem I see is the jobs don’t retry automatically as they should with $maxExceptions 3 and retryUntil() 1 hour from now. It seems the model not found exception automatically fails jobs?

**Comment by bobthefairycat** [comment]
Getting this issue with Laravel 7.X; application was running fine from April 2021 - mid September 2021, on similar workloads (~1 mil jobs per day, ballpark, jobs come in chunks on the order of 20,000 jobs each chunk). The application is mainly dedicated to processing these jobs, and no reported concerns about memory / processor usage.

Model was never changed since the April deploy. Jobs fail before hitting the created Job handler, so cannot invoke custom job failures. Observing the db created at timestamps, two consecutive lines of code (that create separate entries in the db) have a latency of ~2 mins between timestamps. Not sure if this latency is why the issue exists, come time to de-serialize. Confirmed with DevOps Stage and Dev are not sharing the same resources (completely different instances) as Production.

The dispatch is as simple as 

```
$obj = New ModelName;
$obj->param = $val;
$obj->save(); // created_at time "t"
$obj->oneToManyRelation([$id]); // some one to many relationship, created_at time  shows up at "t" + 2 mins

JobName::dispatch($obj)->onQueue($queueName);
```

This is really frustrating. Is there any fix for this?

**Comment by clementmas** [comment]
For anyone still landing on this issue, you might want to check the [Database Transactions](https://laravel.com/docs/queues#jobs-and-database-transactions) documentation regarding this option:

```php
'redis' => [
    // ...
    'after_commit' => true,
],
```
That fixed my `ModelNotFound` exceptions.

**Comment by hasiashiana** [comment]
We have similar case happening. Our queue driver is Redis. Configuration for Redis is as follows. 

```
'redis' => [
            'driver'     => 'redis',
            'connection' => 'queue',
            'queue'      => 'default',
            'retry_after' => 9000,
            'after_commit' => true,
            'block_for' => 3
        ],
```

And this case is not something happening often, randomly some jobs in the default queue starts failing with 'ModelNotFoundException'. It should also be noted that all jobs in the default queue at that time are not failing. 

This exception is also not failing the jobs to the failed_jobs table. As we started reporting the ModelNotFoundException we are now getting the trace of error in the Bugsnag. It states that Model is not found while querying.

![Screenshot 2024-02-02 at 17 24 43](https://github.com/laravel/framework/assets/7097659/aeb71fa4-28a2-415b-896c-3dd89f5fb00e)

 But I am 100% sure that record does exist in the database.

We have verified that listeners are not inside a transaction and 'after_commit' is already set to true.

Really strange that it happens randomly and we still don't know what's causing this.

**Comment by hasiashiana** [comment]
Anyone faced any issue like this ?

**Comment by stuartcusackie** [comment]
I'm having a similar problem. Here's a simplified code sample:

```
public function handlePaymentIntentReturn(Request $request, Organisation $organisation): RedirectResponse
{ 
  $subscription = Subscription::create([
    'subscriber_id' => $request->get('subscriber_id')
  ]);

  Subscribed::dispatch($subscription);
}
```

I'm not using DB::transaction as you can see. Will afterCommit() make any difference in this case? e.g.

```
 Subscribed::dispatch($subscription)->afterCommit();
```

**Comment by stuartcusackie** [comment]
I'm experiencing this problem but even worse, the model is still not found when retrying the job?? I can see it in the database!

**Comment by stuartcusackie** [comment]
I was about to say I have the same problem but I remembered that I'm running two sites on the same server (production & staging). The redis jobs conflict with each other when you do this. Just in case anybody made the same mistake!

**Comment by breaktag** [comment]
Just came here to say that adding the delay also fixed my problem with this.

- Laravel Version: 7
- PHP Version: 7.3
- MySQL Version: 5.7

For me it was slightly more complicated in that the Model I was passing into the Mailer class was from a different database connection to the rest of the system and is conditional based on the customer so I have some custom code in my Model to deal with that in the `getConnectionName()` function.

Adding a 1 minute delay and changing the mailer class to accept the ID instead of the full model, and then reload the model in the Mailer class worked.

I was also calling the `Mail::later(...)` inside an event handler too.
