### ISSUE TITLE
Atomic lock fails in the test environment (with null cache driver)

### ISSUE THREAD

**Issue by pawelryznar** [laravel/framework#28161]
- Laravel Version: 5.8.10
- PHP Version: 7.1.27

### Description:
For some transactions in the API I use \Cache::lock. When calling those API endpoints in test environment, application is failing because of

> Call to undefined method Illuminate\\Cache\\NullStore::lock() in /var/www/vendor/laravel/framework/src/Illuminate/Cache/Repository.php on line 640

I guess it would be useful if NullStore class would have locking methods (returning true).

**Comment by driesvints** [comment]
Returning `true` isn't really an option because a `\Illuminate\Contracts\Cache\Lock` instance is always expected. But we could also implement a `NullLock` implementation and return that instead. I'll try to whip something up for this later today.

**Comment by driesvints** [comment]
Actually, I just realized that this doesn't makes sense. The `LockProvider` contract is specifically there to identify caches that provides locking. What you should do in this case is do a check beforehand to see if the caching implementation you're using is an instance of this class:

```php
Cache::store() instanceof \Illuminate\Contracts\Cache\LockProvider
```

**Comment by M4tini** [comment]
In Laravel 5.8 I had to change the suggested `LockProvider` identification to:
```
Cache::store()->getStore() instanceof \Illuminate\Contracts\Cache\LockProvider
```
