### ISSUE TITLE
[5.7] Maximum function nesting level on Queue::fake()

### ISSUE THREAD

**Issue by kauanslr** [laravel/framework#28163]
- Laravel Version: 5.7.*
- PHP Version: 7.2

### Description:
So, refactoring some code i've found a circular dependency in the Queue mock:
If you try to call a undefined method in the Queue mock you will see a `Error : Maximum function nesting level of '256' reached, aborting!`

Obviously you can just use an existing function, but it can be an inconvenient with any method naming change.

### Steps To Reproduce:
- Create a new test.

```php
\Queue::fake();
\Queue::undefinedMethod();
```

**Comment by Arkanius** [comment]
Interesting. I tried and this is really happening

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.

Thanks!

**Comment by kauanslr** [comment]
Yes, i've updated my version to 5.8 and the problem persists.

I pushed the correction, take a look at #28164
