### ISSUE TITLE
Laravel whereRaw, orWhereRaw with FIND_IN_SET query not running specifically

### ISSUE THREAD

**Issue by jahid56** [laravel/framework#28179]
I have a problem in my project. I have comma seperated value in my database, I want to show data that is matching any of my selected box. But I did not get my result as spected

Here is my query

$products = $products->where('status', 1);
if ($request->get('connectivity')) {
	foreach ($request->get('connectivity') as $key => $connectivity) {
		if ($key == 0) {
			$products = $products->whereRaw('FIND_IN_SET(' . $connectivity . ',connectivity)');
		} else {
			$products = $products->orWhere(function ($query) use ($connectivity){
				$query->whereRaw('FIND_IN_SET(' . $connectivity . ',connectivity)');
			});
		}
	}
}
$products = $products->get();

My whereRaw query is running successfully but when the orWhere query is running then I get extra data.

Thanks in advance

**Comment by rs-sliske** [comment]
you need to tell laravel to group the conditions when using or. see https://laravel.com/docs/5.8/queries#parameter-grouping


also your example looks like it would be vulnerable to sql injection.
you should still use parameter binding even when using raw https://laravel.com/docs/5.8/queries#raw-expressions

**Comment by jahid56** [comment]
I am using Parameter Grouping, But did not work for me. Here is my code

$products = Product::where('status', 1)->where(function ($query) use ($request) {
	if ($request->get('brand')) {
		$query->whereIn('brand_id', $request->get('brand'));
	}
	if ($request->get('connectivity')) {
		foreach ($request->get('connectivity') as $key => $connectivity) {
			if ($key == 0) {
				$query = $query->whereRaw('FIND_IN_SET(' . $connectivity . ',connectivity)');
			} else {
				$query = $query->orWhereRaw('FIND_IN_SET(' . $connectivity . ',connectivity)');
			}
		}
	}
})->get();

**Comment by driesvints** [comment]
Please use a support channel next time: 

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
