### ISSUE TITLE
Paginator resolveCurrentPage needs eloquent

### ISSUE THREAD

**Issue by cg-rsands** [laravel/framework#28175]
- Laravel Version: 5.6 or 5.8
- PHP Version: 7.1 or 7.3

### Description:
Paginator::resolveCurrentPage() or any Paginator:resolve* method does not work unless you have Eloquent loaded into the framework.  The resolvers are null however once Eloquent is loaded the resolvers work as expected.  

Should Eloquent be needed to use a paginator?

**Comment by devcircus** [comment]
You just need to override that functionality with what makes sense for your use case. Google it. There are a lot of examples available.

**Comment by cg-rsands** [comment]
@devcircus Sure, we have worked around it but that is not a fix for a bug.  Eloquent is for working with your database

**Comment by devcircus** [comment]
That's just the most common use case. Honestly the paginate component should come coupled with Eloquent because the way it is currently built, they are closely related. If you're not using Eloquent, then make it work for your situation.

**Comment by driesvints** [comment]
Why don't they work? Can you please give some more info. From what I can tell these should perfectly work out of the box.

**Comment by Tom5om** [comment]
Reference from Lumen issue:

Dont have $app->withEloquent(); in your app.php
In any controller try running Paginator::resolveCurrentPath(), it will return '/' which is the default

Looking more into it it looks that when you boot eloquent a currentPathResolver is set in the register function of PaginationServiceProvider.php:37

When you don't boot eloquent I think the PaginationServiceProvider is not loaded in Application.php on line 363. In there I can see that it only gets loaded if the database is loaded,

Could this potentially be separated by using a registerPaginationBindings function and then separately you can have a loadPagination function?

**Comment by devcircus** [comment]
heck out [Alex's guide](https://codecourse.com/watch/slim-3-pagination) on setting up Illuminate/Pagination without Laravel.

**Comment by Tom5om** [comment]
@devcircus I haven't seen all of it, but it seems like it says it uses eloquent? And this discussion is about a situation where you don't use eloquent

**Comment by devcircus** [comment]
U just need to customize the page resolver. I'll set up a demo repo asap. There's nothing specific about that method that is dependent on Eloquent anyway. I'll put together a minimum working example soon.

**Comment by driesvints** [comment]
I still don't believe Eloquent has anything to do with this. In Lumen the `withEloquent` calls initializes the DB bindings. 

https://github.com/laravel/lumen-framework/blob/f9a9c4a2f9a2a68143b3aee1521898bcdaf0bd00/src/Application.php#L715

I believe this is more of a case of figuring out how to set up pagination without any of the frameworks itself and thus this question might better be suited for a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

**Comment by Tom5om** [comment]
@driesvints have a look on this line:
https://github.com/laravel/lumen-framework/blob/f9a9c4a2f9a2a68143b3aee1521898bcdaf0bd00/src/Application.php#L363

**Comment by Tom5om** [comment]
@devcircus, an example would be great! Thanks

**Comment by driesvints** [comment]
@Tom5om ah I finally understand what you mean. So the thing is that pagination is indeed only loaded here with the DB component to use the builder's pagination methods. It's only necessary to load it for the DB component. Lumen doesn't seems to support pagination out of the box and thus you'd need a custom setup like @devcircus mentioned.

**Comment by Tom5om** [comment]
@driesvints when you say its only necessary to load it for the DB component, what do you mean?

I think it might be a good idea if you could use Pagination by itself? ie have a way to say withPagination or something like that, what do you think

**Comment by driesvints** [comment]
> @driesvints when you say its only necessary to load it for the DB component, what do you mean?

It's only loaded by the application when the DB component is loaded (see your own reference above).

> I think it might be a good idea if you could use Pagination by itself? ie have a way to say withPagination or something like that, what do you think

At the moment Lumen doesn't supports this but please have a look at the guide above or other examples on the web on how to use the Paginator standalone.

**Comment by Tom5om** [comment]
@devcircus could you spare any time to show us an example?
