### ISSUE TITLE
Create blade file from artisan call using laravel 5.7 controller

### ISSUE THREAD

**Issue by gitDharani** [laravel/framework#28178]
- Laravel Version: 5.7
- PHP Version: 7.3
- Database Driver & Version:

### Description:
How can i call php artisan make:resource test.blade.php using Laravel controller? Please help me ASP.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
