### ISSUE TITLE
Wrong resolving file to classname during event discovering

### ISSUE THREAD

**Issue by qem19** [laravel/framework#28187]
- Laravel Version: 5.8.11
- PHP Version: 7.2.15
- Database Driver & Version: psql 10.5

### Description:
My app path is 'src'
And when i want to turn on auto discovering events, laravel resolve my listener class as ' Src\Listeners\...'
But my app has another namespace.
The reason is hardcoded App path in method 'classFromFile' of class DiscoverEvents

**Comment by driesvints** [comment]
Heya. At the moment we only support auto-discovery for events in the `app` directory as this is the default for Laravel. If you have renamed your directory please manually register your events and listeners as before.
