### ISSUE TITLE
`whereDay` and `whereMonth` inconsistent when passing `int` values

### ISSUE THREAD

**Issue by oliversarfas** [laravel/framework#28184]
- Laravel Version: 5.8.11
- PHP Version: 7.3.2
- Database Driver & Version: MySQL 5.7.25

### Description:
When using `whereDay`, or `whereMonth`, passing an integer produces mixed results based on the current date

### Steps To Reproduce:
add a `whereDay`, or `whereMonth` to a builder instance, when the date is less than 10th of the month, or the month is less than 10.

**Comment by oliversarfas** [comment]
#28185 PR created

**Comment by driesvints** [comment]
Which database types do these columns have?
