### ISSUE TITLE
FileViewFinder should be able to return view array

### ISSUE THREAD

**Issue by larsemil** [laravel/framework#28197]
In Illuminate\View\FileViewFinder there is an array of $views that has all information on currently loaded views and also in which order they where loaded. 
I would like to have a getViews() method to get them.

PR Coming

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!
