### ISSUE TITLE
Eloquent update with DB::raw triggers Object of class Illuminate/Database/Query/Expression could not be converted to int

### ISSUE THREAD

**Issue by SevenOutman** [laravel/framework#28196]
- Laravel Version: 5.8.11
- PHP Version: 7.3.3
- Database Driver & Version: MySQL 5.6.33

### Description:
I have an Event Listener for `UserUpdated` event, which compares User's exp with an integer like:
```php
$lv_up_exp_goals = [8, 32, 64];
if (in_array($user->exp, $lv_up_exp_goals)) {
  $user->notify(new UserLevelUp())
}
```

When I increment exp column on a specific User like:
```php
$user->update(['exp' => DB::raw('exp + 1')]);
```
I got this notice going:

    PHP Notice:  Object of class Illuminate/Database/Query/Expression could not be converted to int in /paths/app/Listeners/CheckUserLevelUp.php on line 40

I turned to tinker and noticed that after `update()` with `DB::raw()`, the `$user->exp` turned out to be an `\Illuminate/Database/Query/Expression` instance, which I believe caused this issue.

I think the exp value should be the updated value (as integer) after calling updates, rather than the Expression.
Any ideas?

PS. I need to do increments in my app. I also tried `increment()` method on Query Builder but it doesn't seem to trigger UserUpdated events. Besides, there're still occasions that I can't avoid using `DB::raw()`.

PS. This issue also affects accessors where you may do calculations based on attributes' values.

**Comment by staudenmeir** [comment]
> I think the exp value should be the updated value (as integer) after calling updates, rather than the Expression.

This would be ideal, but is not really possible without an additional query that fetches the current value. You can achieve this with `$user->refresh()`.

> I also tried increment() method on Query Builder but it doesn't seem to trigger UserUpdated events.

I agree that `increment()` and `decrement()` should fire events.

> Besides, there're still occasions that I can't avoid using DB::raw().

Does `$user->refresh()` also solve these cases?

> This issue also affects accessors where you may do calculations based on attributes' values.

Can you provide an example?

**Comment by SevenOutman** [comment]
> > This issue also affects accessors where you may do calculations based on attributes' values.
> 
> Can you provide an example?

Say I have an accessor `lv` which indicates the User's level based on his exp:

```php
public function getLvAttribute()
{
  if ($this->exp > 10) return 2;
  return 1;
}
```
Then if I call `$user->lv` after updating it with `DB::raw()`, the same notice comes out, as I compared exp with an integer value.

> You can achieve this with $user->refresh().

The accessor issue can be solved with calling `$user->refresh()` before `$user->lv` though.
But in the Event Listener case, I don't think it's a good practice to modify the model (e.g. calling `refresh()`) in a event listener, neither in `constructor()` or `handle()`. Because there can be multiple listeners for the `updated` event, thus modifying the model in one listener could cause unexpected behavior in listeners after it.

Ideally (and rationally), I believe, an integer column should always have an integer value (or something casts to an integer).

**Comment by driesvints** [comment]
You can specific casts using the `$casts` property on the model. I'm not sure if I entirely agree on the raw behavior. There's other ways of solving that like mutators etc. 

Incrementing or decrementing firing events is a change in behavior so please open an issue on the ideas repo.
