### ISSUE TITLE
[5.7] Eloquent update with DB::raw triggers Object of class Illuminate/Database/Query/Expression could not be converted to int 

### ISSUE THREAD

**Issue by SevenOutman** [laravel/framework#28191]
- Laravel Version: 5.7.7
- PHP Version: 7.3.3
- Database Driver & Version: MySQL 5.6.33

### Description:
I have an Event Listener for `UserUpdated` event, which compares User's exp with an integer like:
```php
$lv_up_exp_goals = [8, 32, 64];
if (in_array($user->exp, $lv_up_exp_goals)) {
  $user->notify(new UserLevelUp())
}
```

When I increment exp column on a specific User like:
```php
$user->update(['exp' => DB::raw('exp + 1')]);
```
I got this notice going:

    PHP Notice:  Object of class Illuminate/Database/Query/Expression could not be converted to int in /paths/app/Listeners/CheckUserLevelUp.php on line 40

I turned to tinker and noticed that after `update()` with `DB::raw()`, the `$user->exp` turned out to be an `\Illuminate/Database/Query/Expression` instance, which I believe caused this issue.

I think the exp value should be the updated value (as integer) after calling updates, rather than the Expression.
Any ideas?

PS. I need to do increments in my app. I also tried `increment()` method on Query Builder but it doesn't seem to trigger UserUpdated events. Besides, there're still occasions that I can't avoid using `DB::raw()`.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.

Thanks!
