### ISSUE TITLE
env() returns values from fastcgi_param when config:clear and from system when config:cache

### ISSUE THREAD

**Issue by samablews** [laravel/framework#28204]
- Laravel Version: 7.2.8
- PHP Version: 5.8.8
- Database Driver & Version: MySql 5.7.18

### Description:
I have a database username set as a system environment variable and a username set in nginx using fastcgi_param. When using config:cache the variable is loaded from the system environment, when using  config:clear the variable is loaded from fastcgi_param.

### Steps To Reproduce:
Set DB_USERNAME as a system environmental variable as userA
set fastcgi_param DB_USERNAME as userB

Toggle between config:cache and config:clear, the database username changes.

**Comment by sisve** [comment]
This may seem weird, but would be the correct behavior. The env() helper reads from, in order, 1) the `$_ENV` super global, 2) environment variables (using `getenv()`) and, 3) the `$_SERVER` super global. Your fastcgi_params probably ends up in `$_SERVER`.

A non-cached configuration will use the .env to populate all the mentioned data stores. The `env()` helper will then read and see your settings from .env.

Caching a configuration using `config:cache` will populate all data stores, and then write down the config files to disk, as resolved configuration values.

The .env file will not be loaded when a cached configuration file is in use. The env() helper will still read from the the data stores mentioned, which ends up reading from `$_SERVER` where your fastcgi_param stuff is.

The current documentation for configuration caching has a red box that at least mentions this behavior. (The red box is also totally wrong about the return result...) The workaround, if you need to cache your configuration, is to put all your configuration stuff into the config files, and use the `config()` helper instead. The goal here is to only use the `env()` helper in your configuration files, so there's no one reading directly from the environment when the configuration is cached.

> If you execute the config:cache command during your deployment process, you should be sure that you are only calling the env function from within your configuration files. Once the configuration has been cached, the .env file will not be loaded ~and all calls to the env function will return null.~

The strike-through is mine. That part is wrong, the env helper will still return what's in the environment, it's just that the .env file was never used to populate the environment.

**Comment by samablews** [comment]
Thank you, that makes sense, the fastcgi_param isn't actually available to
cache when config:cache is ran so the value is coming from the system.
When config:clear is ran nothing is cached and when a page is loaded, nginx
passes the fastcgi_param in so it's available.

**Comment by driesvints** [comment]
Closing this because the question was resolved.
