### ISSUE TITLE
Using orWhere in relationship constraint gives unexpected query 

### ISSUE THREAD

**Issue by molteber** [laravel/framework#28207]
- Laravel Version: 5.8.11
- PHP Version: 7.2.17
- Database Driver & Version: sqlite

### Description:
When querying on a relationship with `orWhere` conditions, it doesn't look like it encapsulates correctly. (missing parentheses)

### Steps To Reproduce:
1. Have a relationsship between two models, ex:
User hasMany Notes
```php
User::with(['notes' => function ($query) {
    $query->where('type', 'private')
          ->orWhere('type', 'hidden');
}])->first();
```
The following queries will be produced:
* `select * from "users" where "id" = ? limit 1`
* `select * from "notes" where "notes"."user_id" in (1) and "type" = ? or "type" = ?`

To get around the problem you will have to make another wrapper.
```php
User::with(['notes' => function ($query) {
    $query->where(function ($query) {
        $query->where('type', 'private')
              ->orWhere('type', 'hidden');
    });
}])->first();
```
Which then produces the second query as: `select * from "notes" where "notes"."user_id" in (1) and ("type" = ? or "type" = ?)`

This is also the case when using `load()`.

It seems cumbersome to have to wrap the query inside another query function when you're already in a query function.

**Comment by staudenmeir** [comment]
This is the expected behavior. It would be very complicated (or even impossible) for Laravel to handle this automatically.

**Comment by molteber** [comment]
@staudenmeir Is it really?
One could possible change this call
https://github.com/laravel/framework/blob/5.8/src/Illuminate/Database/Eloquent/Builder.php#L560
To maybe `$relation->where($constraints);`
It will give the (imo) expected result as mentioned above.

The only downside is that the closures will not get the specified relation type (HasMany, HasOne etc) but rather the Builder it self. I'm not sure if the specific relation object is useful for something or if it's just how it is.
My suggestion is of course a breaking change, so hopefully there is another way to do it.

**Comment by staudenmeir** [comment]
This breaks non-`WHERE` clauses:

```php
User::with(['notes' => function ($query) {
    $query->where('type', 'private')
          ->orWhere('type', 'hidden')
          ->orderBy('created_at');
}])->first();
```

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!

**Comment by joelharkes** [comment]
I seem to get the same weird issue:
```
$organization->users()->orWhere('first_name', $firstName)
```
also finds users outside organization.

**Comment by driesvints** [comment]
@joelharkes this was added to the docs in the meantime: https://github.com/laravel/docs/pull/5202

**Comment by joelharkes** [comment]
Yes i see, i was still bluffed this is accepted as default behavior, it's very counterintuitive in my eyes. would be easily solved no?
