### ISSUE TITLE
Handle pagination with search data using links from response.

### ISSUE THREAD

**Issue by rassemdev** [laravel/framework#28205]
I'm manually handling pagination using the response it return. I'm using next_page_url and prev_page_url from the response to get to the next/previous page. However i need to append search string to that links. here is my code:

```
$searchParameter = $request->search;
$searchData = Product::where('name', 'like', '%'.$searchParameter.'%')
						->paginate(1)
						->appends($searchParameter);

return $searchData;
```

I'm sending ajax request to get the next/previous page data. So i had to use those links. When i'm using search query the link doesn't provide the result for next page.  I used appends(), but its seems not working.

`next_page_url: "http://127.0.0.1:8000/search_product?page=3`

 Can anyone help me out!

**Comment by GuntherDebrauwer** [comment]
The `appends` method expects an array of parameters, so you have to provide `['search' => $request->search]` as argument.
Instead of manually providing all the querystring parameters, you can also just provide `$request->query()` to the `appends` method

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
