### ISSUE TITLE
Error if first default attribute in model is array

### ISSUE THREAD

**Issue by KFan95** [laravel/framework#28200]
- Laravel Version: 5.8.11
- PHP Version: 7.3.1
- Database Driver & Version: pgsql 10.6
- Homestead Version: 7.1.0

### Description:
Error if first default attribute in model is array

### Steps To Reproduce:
Create model User (Or use default from make:auth)

Add properties (but if we didn't set $incrementing we have other error for the same reason)
```
    protected $attributes = [
        'token_permission' => ['offline', 'groups', 'stats', 'email']
    ];

    public $incrementing = false;
```

Create entity
```
    $user = new User([
        ...fields without token_permission
    ]);
    $user->save();
```

And we have error here
vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2624
```
foreach ($values as $key => $value) {
    ksort($value);

    $values[$key] = $value;
}
```

Reason is here:
vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2616
```
if (! is_array(reset($values))) {
    $values = [$values];
}
```

Condition detect token_permission value as array, and think this is array of entities

**Comment by staudenmeir** [comment]
What type of column `token_permission`?

**Comment by KFan95** [comment]
@staudenmeir Column type is json

```
    protected $casts = [
        'token_permission' => 'array'
    ];
```

If i set $token_permission directly (not from $attributes property), it's work correctly

```
    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);

        $this->token_permission = ['offline', 'groups', 'stats', 'email'];
    }
```

**Comment by staudenmeir** [comment]
Default attributes must be serialized:

```php
protected $attributes = [
    'token_permission' => '["offline","groups","stats","email"]'
];
```

**Comment by KFan95** [comment]
@staudenmeir 

Do i unserstand correctly?:

Whatever when i access to property, property is deserialize?

For example:
```
 foreach (['offline', 'groups', 'stats', 'email'] as $perm) {
            if (!in_array($perm, $this->token_permission)) {
                return false;
            }
        }
```

Will it be deserialize four times?

**Comment by staudenmeir** [comment]
Yes, that's correct.

**Comment by KFan95** [comment]
@staudenmeir Thanks!
