### ISSUE TITLE
Symfony Proccess breaks after update of symfony packages

### ISSUE THREAD

**Issue by vladyslavstartsev** [laravel/framework#28211]
- Laravel Version: 5.7.16
- PHP Version: 7.2.16
- Database Driver & Version:

### Description:
My code is being broken due to that I have updated symfony packages. Because the latest version (4.2) is valid for ^4.1 constraint, it have installed symfony/process:4.2 which have BC when passing non array value to `new Process`. I've found that in Laravel code there are places where you use `new Process` which is not compatible with new symfony version.

### Steps To Reproduce:
Install laravel 5.7 and update symfony packages to 4.2 (especially Process component)  

Breaking places:
https://github.com/laravel/framework/blob/8ab09fb6377eb5b6dab45ab38b0a62446b08e8ae/src/Illuminate/Support/Composer.php#L84
https://github.com/laravel/framework/blob/8ab09fb6377eb5b6dab45ab38b0a62446b08e8ae/src/Illuminate/Console/Scheduling/Event.php#L207-L209
https://github.com/laravel/framework/blob/8ab09fb6377eb5b6dab45ab38b0a62446b08e8ae/src/Illuminate/Console/Scheduling/Event.php#L224-L226
https://github.com/laravel/framework/blob/8ab09fb6377eb5b6dab45ab38b0a62446b08e8ae/src/Illuminate/Queue/Listener.php#L117-L122

**Comment by laurencei** [comment]
Try updating to Laravel 5.8 - this was refactored and is resolved there.

**Comment by laurencei** [comment]
Try updating to Laravel 5.8 - this was refactored and is resolved there.
