### ISSUE TITLE
[5.8] Rule::unique not ignoring model when value 0

### ISSUE THREAD

**Issue by TivoSoho** [laravel/framework#28215]
- Laravel Version: 5.8.10

### Description:
When model PK / ignored column value is 0, it does not get ignored because the value needs to evaluate to true in order to be ignored:

````
    public function __toString()
    {
        return rtrim(sprintf('unique:%s,%s,%s,%s,%s',
            $this->table,
            $this->column,
            $this->ignore ? '"'.addslashes($this->ignore).'"' : 'NULL',
            $this->idColumn,
            $this->formatWheres()
        ), ',');
    }
````
Considering the code this would probably fail to validate empty strings as well since they evaluate to false.

### Steps To Reproduce:
Try to evaluate a unique rule for a model or field that will evaluate to false - 0, empty string.

**Comment by driesvints** [comment]
Please fill out the entire issue template.

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by javilaurin** [comment]
@driesvints Also happening here in 5.7. Is there any workaround for this or was this solved in any newer versions?
