### ISSUE TITLE
Artisan::call('horizon:terminate') The command "horizon:terminate" does not exist.

### ISSUE THREAD

**Issue by shadoWalker89** [laravel/framework#28217]
- Laravel Version: 5.8.11
- PHP Version: 7.2.14

### Description:
Calling this from my application will cause this error

```php
        Artisan::call('horizon:terminate');
```

Symfony \ Component \ Console \ Exception \ CommandNotFoundException
The command "horizon:terminate" does not exist.

When i call the command from the command line it works.

If you ask why i'm calling the `horizon:terminate` from my application, well i have a settings module that allows users to update the application configuration by updating the .env file.

After doing so,
I want to do two things

```php
        Artisan::call('config:cache');
        Artisan::call('horizon:terminate');
```

The config:cache works but the horizon:terminate does not.

**Comment by driesvints** [comment]
You need to have Horizon installed for this. This is the issue tracker for the Laravel framework, not Horizon.

**Comment by shadoWalker89** [comment]
@driesvints That is the problem, Horizon is already installed and it says command not found

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by brunogaspar** [comment]
@shadoWalker89 Not sure where you're calling that Artisan command, but you can only call that through the "terminal".

Hope this https://github.com/laravel/horizon/blob/3.0/src/HorizonServiceProvider.php#L168 helps to understand the cause perhaps?

**Comment by shadoWalker89** [comment]
@brunogaspar Thanks, that explains why i'm getting command not found.

For now what i'm doing

```php
exec('cd '.base_path().' && /usr/local/bin/ea-php72 artisan horizon:terminate');
```

**Comment by shadoWalker89** [comment]
@brunogaspar About why i'm calling that command, like i said in the issue message, the administrator of the application can change configurations saved within the .env file. I need to terminate horizon so it can pickup the new config values

**Comment by brunogaspar** [comment]
Yup, figured much.

Your solution is not bad, although not super Laravel Clean :)

**Comment by nonoesp** [comment]
Ran into the same issue (with another package).

It seems only commands registered outside of the `if ($this->app->runningInConsole())` call are available to be called from within the app's runtime with `Artisan:call`.

[Made a little write up](https://nono.ma/laravel-artisan-the-command-does-not-exist) explaining my solution.

In my case, I'm the maintainer of the package and could easily work around the limitation. But you could probably register the `horizon:terminate` command yourself in your app's `commands()` function in `app/Console/Kernel.php`.

**Comment by Helle1** [comment]
> Ran into the same issue (with another package).
> 
> It seems only commands registered outside of the `if ($this->app->runningInConsole())` call are available to be called from within the app's runtime with `Artisan:call`.
> 
> [Made a little write up](https://nono.ma/laravel-artisan-the-command-does-not-exist) explaining my solution.
> 
> In my case, I'm the maintainer of the package and could easily work around the limitation by taking the command I want to use in Laravel out of the `if` statement.
> 
> But I just tested that you can register the `horizon:terminate` command yourself in your app's `$commands` array in `app/Console/Kernel.php`.
> 
> For instance, I did this.
> 
> ```
> protected $commands = [
>     \Nonoesp\Folio\Commands\CreateUserCommand::class,
> ];
> ```
> 
> While the `CreateUserCommand` is only registered to the console by the package, I can explicitly make it available for my entire application calling it with `Artisan::call('folio:user {email} {password}')` (which is this command's signature).

I tried that out ... after some research in the laravel files I tried to set the commands up via the `AppServiceProvider` as the solution with the `Kernel.php` did not change anything:

```
public function register()
    {
        //
        $this->commands([
            \Laravel\Horizon\Console\StatusCommand::class,
            \Laravel\Horizon\Console\TerminateCommand::class,
            \Laravel\Horizon\Console\ContinueCommand::class,
            \Laravel\Horizon\Console\HorizonCommand::class
        ]);
    }
```

But now I am running into new issues. It seams, that horizon simply is not callable via `Aritsan::call()` or did I miss something?

**Comment by junaid-A-khan** [comment]
> > Ran into the same issue (with another package).
> > It seems only commands registered outside of the `if ($this->app->runningInConsole())` call are available to be called from within the app's runtime with `Artisan:call`.
> > [Made a little write up](https://nono.ma/laravel-artisan-the-command-does-not-exist) explaining my solution.
> > In my case, I'm the maintainer of the package and could easily work around the limitation by taking the command I want to use in Laravel out of the `if` statement.
> > But I just tested that you can register the `horizon:terminate` command yourself in your app's `$commands` array in `app/Console/Kernel.php`.
> > For instance, I did this.
> > ```
> > protected $commands = [
> >     \Nonoesp\Folio\Commands\CreateUserCommand::class,
> > ];
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > While the `CreateUserCommand` is only registered to the console by the package, I can explicitly make it available for my entire application calling it with `Artisan::call('folio:user {email} {password}')` (which is this command's signature).
> 
> I tried that out ... after some research in the laravel files I tried to set the commands up via the `AppServiceProvider` as the solution with the `Kernel.php` did not change anything:
> 
> ```
> public function register()
>     {
>         //
>         $this->commands([
>             \Laravel\Horizon\Console\StatusCommand::class,
>             \Laravel\Horizon\Console\TerminateCommand::class,
>             \Laravel\Horizon\Console\ContinueCommand::class,
>             \Laravel\Horizon\Console\HorizonCommand::class
>         ]);
>     }
> ```
> 
> But now I am running into new issues (i.e. horizoncommand: `Call to undefined function Laravel\Horizon\Console\pcntl_async_signals()`) . It seems, that horizon simply is not callable via `Aritsan::call()` or did I miss something? Maybe because of Laravel 7 ?

Just did this as you suggested and the terminate command works for me. All the multiple horizon instances are terminated instantly on my local machine. Still have to test on the server.
```
 /**
     * The Artisan commands provided by your application.
     *
     * @var array
     */
    protected $commands = [
        TerminateCommand::class,
    ];
```
I am on Laravel 8 so may be that's why it worked for me without any error.
Thank You.

**Comment by MohamedLamineAllal** [comment]
Laravel 10

```php
<?php

namespace App\Console;

use Laravel\Horizon\Console\TerminateCommand;
use Illuminate\Foundation\Console\Kernel as ConsoleKernel;

class Kernel extends ConsoleKernel
{
	/**
	 * Register the commands for the application.
	 */
	protected function commands(): void
	{
		$this->load(__DIR__ . '/Commands');
		$this->registerCommand(new TerminateCommand());

		require base_path('routes/console.php');
	}
}
```

Works perfect!
