### ISSUE TITLE
Error Warning: filesize() while using cron after upgrading Laravel 5.8

### ISSUE THREAD

**Issue by Perh0rd** [laravel/framework#28228]
Hi,

We recently have updated to Laravel 5.6 to 5.8 and we randomly have this error now while using cron to call some api endpoints as we did before : 

`Warning: filesize(): stat failed for storage/framework/cache/data/aa/ba/aabaeafdb90f0d93adc97d019d71de3fd2045953`

in /public/index.php - line 55

`$request = Illuminate\Http\Request::capture() `

Do you have any idea why?

Thank you very much!

**Comment by laurencei** [comment]
What's the full stack trace?

My guess is a file permission error, where the cron user is different to the web user.

**Comment by Xpedigo** [comment]
Hi @laurencei  and thank you for your answer.

Here is the full stack trace : [Here](https://anopetia.tinytake.com/sf/MzQ2NDAzN18xMDM4MjM1OA)

Note that, the cron user is the same as the nginx user, we try every permission , every chown, chmod 777 and so on on folder, we changed the cron folder and the user of the storage folder.

We cleared cache, every of them config, routes, view, app....  We removed files manually, we call composer update and dump-autoload

A thing which is very strange is that the datetime of the file is after the datetime of the error, like the file do not exist at the time the request was called?! It was working fine on version 5.6, I really do not understand why now it's broken.

Sometimes the error is th `fopen`  `failed to open stream: No such file or director` sometime it is the error` filesize() `, we try with wget, curl, same result.....

Thank you for your light

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by driesvints** [comment]
Also: please fill in the issue template next time. Thanks!

**Comment by Xpedigo** [comment]
I did not see issue template while creating the issue .

Moreover problem still occurs, not only on cron but everywhere...

I don't know if it's a bug or not, but there is clearly something not properly working with this last version.

**Comment by wtbloom** [comment]
> I did not see issue template while creating the issue .
> 
> Moreover problem still occurs, not only on cron but everywhere...
> 
> I don't know if it's a bug or not, but there is clearly something not properly working with this last version.

Were you able to ever find any resolution to this issue?  I am having the exact same problem after upgrading to 5.8

**Comment by foxinatardis** [comment]
I am actually having this issue in version 5.7

**Comment by devsi** [comment]
Exact same problem. We can't figure it out yet. Like, the EXACT same problem.

**Comment by wtbloom** [comment]
I still haven't been able to solve it.  I ended up just caching on a Redis instance as opposed to the file system as a workaround.

**Comment by eberkund** [comment]
I am having the same issue randomly getting reported by Sentry

**Comment by djohnston08** [comment]
@driesvints I am not sure this is a support issue. We are also seeing this on numerous projects. Considering this was not an issue in previous versions, it seems like a bug. Maybe not a serious bug, but it definitely feels like a regression. The problem is that it’s intermittent so it seems to be getting ignored. Is anyone going to look into this or should we just expect to to ignore it in the future?

**Comment by driesvints** [comment]
@djohnston08 can you please try a support channel first and then report back if that didn't help?

**Comment by jamiehd** [comment]
@driesvints I'm pretty sure this is a bug rather than a support issue. We're getting it too but it's very sporadic. It seems to be an issue with the file cache driver.

ErrorException
Warning: filesize(): stat failed for /var/www/x/storage/framework/cache/data/a2/db/a2db5ca42f2189b4ea48e92035d86e01956e31a7

**Comment by infostreams** [comment]
I'm seeing this issue too, and a related issue in the same section of code (also triggered from public/index.php, line 55 like above). Seems to be a race condition, somehow. I've attached two screenshots from my Sentry instance - hope it helps.

<img width="501" alt="Screenshot 2019-09-30 at 10 41 46" src="https://user-images.githubusercontent.com/1132744/65862855-6660b680-e36f-11e9-8457-c8f0abd10b28.png">

screenshot 2:

<img width="493" alt="Screenshot 2019-09-30 at 10 42 30" src="https://user-images.githubusercontent.com/1132744/65862868-6bbe0100-e36f-11e9-95c6-0f350a82d1ba.png">

I'm convinced it's a bug, not a support issue.

**Comment by driesvints** [comment]
Okay, I'll re-open this. Appreciating anyone who could help look into this.

**Comment by infostreams** [comment]
Thanks! I'm at a loss for how as for how a filesize() call could fail on a file *after* you've acquired a lock on it (first screenshot).

**Comment by infostreams** [comment]
Ok, so I thought (and read) about it a bit more. I think there might be one of two things happening here:

1. Whatever ```flock()``` does is [*advisory*](https://www.php.net/manual/en/function.flock.php), meaning that maybe (?) you don't really get a file lock even if you do call ```flock()```. So any competing process could theoretically just call ```unlink()```, maybe to clean out the cache folder, and delete the file that we thought we had a lock on.

2. ```flock()``` operates on a file **handle**, not on a file **name**. Assuming that ```flock()``` get us an actual lock, not an advisory one, then the code above could still fail if we rename the file that we have a lock on. That wouldn't affect the lock, as the file itself still has the lock – the file just has a different name. However, in the code, after we obtain the lock, we try to do an operation on the file with the name as it was **before** the assumed rename. Since that file name no longer exists, it would fail - triggering this error.

My two cents on this. Not sure on how to best address them. Thoughts?

**Comment by masbenx** [comment]
it also happened on version 5.7

<img width="1320" alt="Screen Shot 2019-11-01 at 10 44 41" src="https://user-images.githubusercontent.com/998691/68000976-b7c4d400-fc94-11e9-87ec-5a0b31049c91.png">

**Comment by jamiehd** [comment]
Well that screenshot has given me a thought - is everyone here using sentry?

I use sentry so maybe it's related...

**Comment by donnysim** [comment]
From the stacktrace, the original issue seems more like a ThrottleRequests cache failure than related with cron itself. Using file store even sessions sometimes can throw an exception of file not found and that's present for quite some time, minimum from laravel 5.2.

**Comment by markgukov** [comment]
> Well that screenshot has given me a thought - is everyone here using sentry?
> 
> I use sentry so maybe it's related...

Yep, using Sentry here.

**Comment by jamiehd** [comment]
I wonder if its related to this: https://github.com/getsentry/sentry-laravel/issues/254

**Comment by Rishats** [comment]
Laravel 6.10.1 - same problem.

**Comment by driesvints** [comment]
@Rishats are you using sentry-laravel? Can you try upgrading to 1.4.0 to see if that fixes your problem?https://github.com/getsentry/sentry-laravel/issues/254#issuecomment-543558493

**Comment by Rishats** [comment]
> @Rishats are you using sentry-laravel? Can you try upgrading to 1.4.0 to see if that fixes your problem?[getsentry/sentry-laravel#254 (comment)](https://github.com/getsentry/sentry-laravel/issues/254#issuecomment-543558493)

I use https://packagist.org/packages/sentry/sentry-laravel

**composer.lock**
```
"name": "sentry/sentry-laravel",
"version": "1.5.0",
...
```

**Comment by andypa** [comment]
We are using Sentry as well. The error occured the first time, when following packages in our installation were updated. Some are internal packages so I just listed the public ones:

| Package | From | To|
| --- | -- | -- |
| aws/aws-sdk-php |  3.130.3  |   3.132.1 |     
| egulias/email-validator |  2.1.13  |  2.1.14 |
| facade/ignition |  1.13.1  |  1.14.0 |        
| laravel/nova |  v2.9.2  |  v2.9.3 |           
| sentry/sdk |   2.0.4  |  2.1.0 |              
| sentry/sentry |  2.2.6  |  2.3.0 |            
| phpunit/phpunit |  7.5.18  |  7.5.20 |        

The sentry/sdk had following changes:
Added: **guzzlehttp/psr7** and **symfony/polyfill-uuid**
Removed: **ramsey/uuid** and **zendframework/zend-diactoros**

I'm now trying to upgrade to sentry/sentry-laravel **1.5.0**  to check if that makes a difference.

**Comment by esbenp** [comment]
This error started happening to us right after we made some changes to enable persisting Horizon data across deploys. We made a separate Redis cache database, ala this change here https://github.com/laravel/laravel/commit/c3b99e971cd9d8213ada259b9f624a8f70ddd57b

We just reverted it back so the cache uses the default connection and so far no more errors have appeared, although it has not been in production for long enough to say its fixed. If this is the case then maybe the above commit can explain why this started occurring around 5.8??

**Comment by esbenp** [comment]
Update: the above mentioned fixed has removed the error for us. So maybe its related to having a redis database for cache thats not the default one?

**Comment by andypa** [comment]
> Update: the above mentioned fixed has removed the error for us. So maybe its related to having a redis database for cache thats not the default one?

We don't use redis at all and the same error occurs.

**Comment by driesvints** [comment]
@esbenp are you using sentry as well?

**Comment by esbenp** [comment]
Yes

**Comment by driesvints** [comment]
Since everyone here is using the same library I think it's safe to say that the problem probably lies within there and not Laravel. Please follow along with the issue here: https://github.com/getsentry/sentry-laravel/issues/254
