### ISSUE TITLE
The DB connection is wrong

### ISSUE THREAD

**Issue by run6** [laravel/framework#28227]
- Laravel Version: 5.8.3
- PHP Version: 7.2.0
- Database Driver & Version:

### Description:

![image](https://user-images.githubusercontent.com/35883111/56183675-00df6e80-604a-11e9-8da4-703986a4c749.png)

The code is very simple
![image](https://user-images.githubusercontent.com/35883111/56183703-23718780-604a-11e9-9bf7-a0557edd269f.png)

![image](https://user-images.githubusercontent.com/35883111/56183492-62eba400-6049-11e9-8fe0-5b7079acb38e.png)

Look！  I configure the DB_HOST  but, The DB connection is the other HOST？  The other HOST is my localhost IP  。The project is new.   
### Steps To Reproduce:
configure a remote db_host in .env file .

**Comment by run6** [comment]
I have resolved the problem .............
I added  quotation marks around the db_password  。

**Comment by run6** [comment]
but  why the error message like  this？？？？？？？？ I can not  understand

**Comment by staudenmeir** [comment]
Is `DB_PASSWORD` actually "secret"?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
