### ISSUE TITLE
Double subtraction issue

### ISSUE THREAD

**Issue by xyrintech** [laravel/framework#28221]
- Laravel Version: 5.8
- PHP Version: 7.2
- Database Driver & Version: Postgresql 9.3

### Description:
When we subtract 2 double numbers then this returns some unexpected result. 

### Steps To Reproduce:
```
$a = 20.05; 
$b = 20.05; 
```
Please presume that $a, $b is something I am getting from a Model's mutator which further is getting from database using sum() DB function. We are dealing with financial data and this is creating an issue with calculations everywhere. 

`return (double)$a - (double)$b;`
This returns `-3.5527136788005E-15`

**Comment by driesvints** [comment]
This isn't related to Laravel but the way to PHP works. When working with money values I recommend only to do calculations with integers and making use of https://github.com/moneyphp/money
