### ISSUE TITLE
Inconsistent use of 'name' on named routes

### ISSUE THREAD

**Issue by unpana** [laravel/framework#28239]
- Laravel Version: 5.8.12
- PHP Version: 7.2.4

### Description:
When using named routes, the use of 'name' is inconsistent depending on where it is used. 

### Steps To Reproduce:
In routes/web.php
```
Route::name('admin.')->group(function () {
    Route::get('users', function () {
        // Route assigned name "admin.users"...
    })->name('users');
});

Route::group(['name' => 'client.'], function () {
    Route::get('invoices', function () {
        // Route assigned name "client.invoices"? I don't think so...
    })->name('invoices');
});
```

This produces the following named routes when running `php artisan routes:list`
```
URI: users NAME: admin.users
URI: customers NAME: invoices //Why not clients.invoices?
```
It seems like using `Route::group(['as' => 'client.'], ...)` does the trick, but why use 'as' instead of 'name'?

**Comment by devcircus** [comment]
Yes. "name" is for a single route. "as" determines how a group is represented. (At least that's how I've always used them). 🤷🏻‍♂️

**Comment by unpana** [comment]
> Yes. "name" is for a single route. "as" determines how a group is represented. (At least that's how I've always used them). 🤷🏻‍♂️

But actually, you can use 'name' for groups too, (i.e. `Route::name('client.')->group(...)`). What I do not understand is why the nomenclature changes if used as a parameter instead of a property.

**Comment by devcircus** [comment]
Interesting. This has come up several times on the repo. You may look back through the old issues and pull requests and see if you can glean any insight.

**Comment by ankurk91** [comment]
May be related
https://github.com/laravel/ideas/issues/1521

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!
