### ISSUE TITLE
whereRaw binding Invalid parameter number: parameter was not defined

### ISSUE THREAD

**Issue by Pashedu** [laravel/framework#28230]
- Laravel Version: 5.7.28
- PHP Version: 7.2.17
- Database Driver & Version: PostgreSQL 11.2 

### Description:
I'm trying to get Events which have dates with some time frame: 
` $query = Event::query();
        $query->whereHas('date', function (Builder $query) {
            $query->whereRaw(
                "(start_date::time, end_date::time) OVERLAPS (TIME '08:00:00', TIME '10:00:00') = true"
            );
        });`
and that query works fine. 
But when I'm adding binding values like this: 
`$query->whereHas('date', function (Builder $query) use ($time) {
            $query->whereRaw(
                "(start_date::time, end_date::time) OVERLAPS (TIME '?', TIME '?') = true",
                [$time->start, $time->end]
            );
        });`
I'm getting error: 

>  Invalid parameter number: parameter was not defined

not sure is that ORM issue or it's me, but result query in both cases looks identical.

**Comment by staudenmeir** [comment]
PostgreSQL is quite picky about date/time bindings. Try this:

```php
$query->whereHas('date', function (Builder $query) use ($time) {
    $query->whereRaw( "(start_date::time, end_date::time) OVERLAPS (?::time, ?::time) = true", [$time->start, $time->end] );
});
```

**Comment by Pashedu** [comment]
Splendid!!! Very thanks!

**Comment by staudenmeir** [comment]
Please close the issue.
