### ISSUE TITLE
Cache file with laravel version 5.8 works randomly

### ISSUE THREAD

**Issue by Xpedigo** [laravel/framework#28234]
- Laravel Version: 5.8.11
- PHP Version: 7.2
- Database Driver & Version: Mysql 8

### Description: 

We recently have updated to Laravel 5.6 to 5.8 and we randomly have this error.

`Warning: filesize(): stat failed for storage/framework/cache/data/aa/ba/aabaeafdb90f0d93adc97d019d71de3fd2045953`

`in /public/index.php - line 55`

`$request = Illuminate\Http\Request::capture()`

Here is the full stack trace : https://anopetia.tinytake.com/sf/MzQ2NDAzN18xMDM4MjM1OA

We try every permissions , every chown, chmod 777 and so on on folder, we changed the cron folder and the user of the storage folder.

We cleared cache, every of them config, routes, view, app.... We removed files manually, we call composer update and dump-autoload

A thing which is very strange is that the datetime of the file is after the datetime of the error, like the file do not exist at the time the request was called?! It was working fine on version 5.6, I really do not understand why now it's broken.

Sometimes the error can be `fopen failed to open stream: No such file or director`

Thank you very much!

### Steps To Reproduce:

Launch a call to a api routes, calling controller crash on cache.

**Comment by driesvints** [comment]
Please see my comment here: https://github.com/laravel/framework/issues/28228#issuecomment-483638531

**Comment by driesvints** [comment]
Just to clarify: the issue tracker here isn't a support forum. I believe the above might be related to something in user land that's why I'd like you to first try on a support channel from the above link where others can help you figure out the problem. If the problem turns out to be a bug with Laravel then feel free to respond back and we'll figure out a solution.
