### ISSUE TITLE
Auth::id() failed after image upload.

### ISSUE THREAD

**Issue by rb196** [laravel/framework#28243]
- Laravel Version: 5.8.12
- PHP Version: 7.3.2
- OS: Windows 10 v1809 & Linux Ubuntu 18.10

-- app/Helper/BankHelper.php
```php
    // ...
    public static function uploadIcon(UploadedFile& $file)
    {
        $name = uniqid() . '.' . $file->getClientOriginalExtension();
        $file->move(public_path('/img/bank/'), $name);

        return $name;
    }
    // ...
````

-- app/Http/Controllers/Api/Dashboard/BankController.php
```php
    // ...
    public function createNew(Request $request)
    {
        $userId = Auth::id();
        $image = null;
        if ($icon = $request->file('icon')) {
            $image = BankHelper::uploadIcon($icon);
        }

        $bank = Bank::create([
            'user_id' => $userId,
            'name' => $request->post('name'),
            'image' => $image,
        ]);

        return response()->json([
            'bank' => $bank,
        ]);
    }
    // ...
```

If I use Auth::id() when I create the Bank instance I got this error `SplFileInfo::getSize(): stat failed for TEMP_FILE`. But file successfully uploaded.
```php
    // ... uploading icon
    $bank = Bank::create([
        'user_id' => Auth::id(),
        // ..
    ]);
```

But when I store logged user id in variable before uploading icon then it's work fine.
```php
    $userId = Auth::id();
    // ... uploading icon
    $bank = Bank::create([
        'user_id' => $userId,
        // ..
    ]);
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
