### ISSUE TITLE
Str::random() in Validator::validated()

### ISSUE THREAD

**Issue by maartendekeizer** [laravel/framework#28241]
- Laravel Version: 5.8
- PHP Version: n/a
- Database Driver & Version: n/a

### Description:
When trying to figure out something else I found a line of code in the Laravel framework that I found realy strange. The `validated()` method in `Illuminate\Validation\Validator` is using Str::random(). It is using Str::random() to generate a value that indicated _not set._ In normal business this should work. But theoretically it can go wrong when the generated _not set_-value matched one of the submitted values. A better solution would be to use an new object and use a reference check. And strange enough this was already the code before this commit https://github.com/laravel/framework/commit/ad34b8d4eb0d1c76d55ed3173a33f6fa32ead1d4#diff-38fd116b7c7b8ac1bdd8362250d04d57

Questions:
1. Why this change, why use random instead of object references?
2. Why has the changing commit the misleading description `formatting` 
3. Should we revert this back? It looks like somebody else was already wondering about this code in: #27874 #27873

**Comment by driesvints** [comment]
If you really believe a better solution could be implemented then please open an issue on the ideas repo. I get the idea behind what you're suggesting and it could be nice but it's more of an improvement. We haven't had issue with this before so we don't consider this to be a bug atm.

**Comment by maartendekeizer** [comment]
@driesvints They old solution was better and correct. I'm wondering that this code is changed without an underlying issue..
