### ISSUE TITLE
Filesystem S3 driver: read files that are inside a folder without a name

### ISSUE THREAD

**Issue by ManuDoni** [laravel/framework#28255]
- Laravel Version: 5.5.45
- PHP Version: 7.2.17

### Description:
Hello,
I can't read a file with a path that contains a folder without a name, like this: `folder//sub_sub_folder/file.txt` (note the double slash).
Neither the `exists` nor the `get` methods can retrieve files from this kind of path but in the S3 management console I can write and read from those paths.
I know the best thing to do is to avoid path like that but I can't because I don't have control over these auto-generated files (they weren't created by me).

The `has` and `read` methods of `League\Flysystem\AwsS3v3\AwsS3Adapter` work if I use them directly.
If I use `exists` and `get` methods from the laravel class `Illuminate\Filesystem\FilesystemAdapter` I get `false` and an `Illuminate/Contracts/Filesystem/FileNotFoundException` exception respectively

How can I read these files?

Thanks in advance

### Steps To Reproduce:
Just create a file in the S3 console with a path like the previous example and use Storage::disk('s3')->get('path//to/file')

**Comment by driesvints** [comment]
Which version of the adapter are you using?

**Comment by ManuDoni** [comment]
league/flysystem-aws-s3-v3 version 1.0.22
aws/aws-sdk-php version 3.91.5

**Comment by driesvints** [comment]
I don't have time right now to reproduce it but I'll take your word for it. Welcoming prs to look into this.

**Comment by driesvints** [comment]
Is this also the same case in 5.8?

**Comment by ManuDoni** [comment]
Thanks, I will try with Laravel 5.8 in these days to see what happens

**Comment by ManuDoni** [comment]
A colleague of mine tested it and it fails even with Laravel 5.8

**Comment by georgehanson** [comment]
I wonder if this happens with other adapters or if it is just the S3 one.

**Comment by ManuDoni** [comment]
I found the problem in League\Flysystem\Util::normalizeRelativePath, used in most of the methods of League\Flysystem\Filesystem. This function breaks these weird paths.

**Comment by driesvints** [comment]
@ManuDoni so this problem actual exists in the Filesystem library of the league? Can you reproduce this with just the basic league library?

**Comment by ManuDoni** [comment]
Yes, but feel free to close this issue because of this: https://github.com/thephpleague/flysystem-aws-s3-v3/issues/169#issuecomment-484842891.
I will use AWS SDK directly to solve this issue.
