### ISSUE TITLE
[5.8] Argument 1 passed to Illuminate\Database\Query\Builder::cleanBindings() must be of the type array, null given

### ISSUE THREAD

**Issue by Cannonb4ll** [laravel/framework#28251]
- Laravel Version: 5.8.12
- PHP Version: 7.2.14
- Database Driver & Version: MySQL 5.7.20

### Description:
Just this morning upgraded from 5.8.11 to 5.8.12 which completely broke my application on the wherePivot part.

**Broken:**
```php
$variable = $user->books()->wherePivot('owner', true)->findOrFail($id);
```

**Fixed:**
```php
$variable = $user->books()->wherePivot('owner', '=', true)->findOrFail($id);
```

Has this been done intentionally? I cannot find anything regarding this change inside the core update. My code has not changed since the upgrade from 5.8.11 -> 5.8.12

**Comment by JeroenBoesten** [comment]
It seems to me like a unintentional change, because it's not regarding every other where statement where it's just assumed that '=' is the operator if no operator is specified. Could this possibly be related to the changes made to the where here: https://github.com/laravel/framework/pull/28192

**Comment by ankurk91** [comment]
Lucky i am using `withPivotValue()` method which internally uses
```php
$this->wherePivot($column, '=', $value)
```

**Comment by Cannonb4ll** [comment]
@ankurk91 I fail to see how this is contributing to this core issue.

**Comment by ahinkle** [comment]
Hey, the original PR was reverted (04a547ee25f78ddd738610cdbda2cb393c6795e9) and was released in 5.8.13. This issue is now solved. An additional test has been submitted to prevent future issues. #28260

**Comment by mjhorninger** [comment]
This issue has arisen again in Laravel Version 5.8.23

**Comment by staudenmeir** [comment]
@mjhorninger What query causes this error for you?

**Comment by mjhorninger** [comment]
So it's a nested set of components, and needs to be refactored desparately.
We can query all the way down through three layers of models, but when we try to access a convenience method on the bottom layer that retrieves a non-related model, it breaks.

**Comment by mjhorninger** [comment]
The bottom query that fails  is: `Pair::whereIn('id', $groupOfPairIds)->get();`

**Comment by staudenmeir** [comment]
What's the last working Laravel version?

**Comment by staudenmeir** [comment]
What's the result of `dd($groupOfPairIds);`?

**Comment by mjhorninger** [comment]
dd($groupOfPairIds) gives an array - 
`[
0 => 32 
1 => 34, 
2 => 36
3 => 38
]`

**Comment by staudenmeir** [comment]
Did you see my other question?

> What's the last working Laravel version?

**Comment by mjhorninger** [comment]
I did.  Unfortunately, I got sucked into a meeting.  I'm peeling back the onion based on our upgrade path and testing with 5.8.13 now

**Comment by mjhorninger** [comment]
I'm all the way back at 5.8.0 which means this piece of functionality does not get tested very often.  I'm still seeing the issue.  
At this point it had to be something peculiar to our stack.  I have tested the call in tinker and it works all the way forward to the latest version (.26).  It's not until the datatables get involved that it starts to fall apart.

**Comment by tinhtu9x** [comment]
j
