### ISSUE TITLE
Inconsistency when eager loading releations with the wrong casing

### ISSUE THREAD

**Issue by rimace** [laravel/framework#28257]
- Laravel Version: 5.8.12
- PHP Version: 7.2.16
- Database Driver & Version: -

### Description:
Some day a made a mistake with the spelling when eagerly loading a relation. I typed (example) 
`Person::with('Computers');` (notice the big C) instead of "computers" (which was the correct name of the relation method). Instead of throwing an exception the framework just ignored it and did just not eagerly load the relation and loaded them n-times.

I would expect if I spell the method name wrong the framework throws an exception. Actually it does, but `Model::with()` checks the method name case insensitive.

### Steps To Reproduce:
I will try to explain it further with the following example:
```
class Person extends Model
{
	public function computers()
	{
		return $this->hasMany(Computer::class);
	}
}

class Computer extends Model
{
	public function person()
	{
		return $this->belongsTo(Person::class);
	}
}
```

- Calling `Computer::with('PERSON');` works fine. It will create 2 relations in for each computer object. One will be called "person" and another one "PERSON".
- Calling `Computer::with('ABC');` will throw an exception, because the method cannot be found. Which is, of course, correct.
- Calling `Person::with('COMPUTERS');` will NOT work, but also will NOT throw any exception. It will just load relations when needed "n-times" style.

The first and the last point are those which I think are strange. Personally I would expect that the given methods needs to be checked case sensitively.

**Comment by ahinkle** [comment]
Take a look at #26568

**Comment by rimace** [comment]
@ahinkle  Thanks, I did miss that.
So the issue was closed but no reason/solution documented. First possible solution that came into my mind was checking the method name (via [get_class_methods](https://www.php.net/manual/en/function.get-class-methods.php), not via method_exists, as it is case insensitive).
But I guess it was closed because it is considered as an issue on the language side?

**Comment by driesvints** [comment]
> But I guess it was closed because it is considered as an issue on the language side?

From the userland side yes. Please use the proper casing which conforms to the method name.
