### ISSUE TITLE
assertSessionHasErrors() fails to assert false or true

### ISSUE THREAD

**Issue by Lukmauu** [laravel/framework#28268]
- Laravel Version: 5.8.*
- PHP Version: 7.1.19
- Database Driver & Version: MySql 5.6.37

### Description:
I am trying to assert if the validation is failing or passing with phpunit, but no matter what I do or google I just got this:

1) Tests\Unit\TestRegistration::test_new_user
Session is missing expected key [errors].
Failed asserting that false is true.

```php
class TestRegistration extends TestCase
{
    /* test */
    function test_new_user()
    {
        $this->withExceptionHandling();

        $data = [
            '_token' => csrf_token(),
            'name' => "RealName",
            'email' => '',
            'email_verified_at' => now(),
            'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
            'remember_token' => Str::random(10),
        ];

        $this->call('post','/register', $data)
             ->assertSessionHasErrors('email');
    }
}
```

This is the only code that is difference from a fresh laravel installation of this 5.8 version, I install another to try it. I though was the csrf so place a token in the array and same thing, without the token same thing, stop all the middlewares from ever executing same thing,

### Steps To Reproduce:

install a fresh laravel
place this above function into Tests\Unit\TestRegistration::test_new_user
and try to run it 

I could not I am wonder if I am doing the right to assert my validation rule

<img width="1268" alt="Screen Shot 2019-04-18 at 5 39 10 PM" src="https://user-images.githubusercontent.com/3298781/56399100-f74c3700-6200-11e9-9f6f-81ee92ea6830.png">

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by didotsonev** [comment]
Have you found any solution for this issue?

**Comment by Lukmauu** [comment]
I did not, but I think was something on my settings because after installing homestead all was back to normal.

so I really don't know

**Comment by TranDucThanh932000** [comment]
Too late, but you can try $response->assertInvalid(['email']);

**Comment by nawazfdev** [comment]
$this->assertDatabaseHas('users', ['email' => $user->email]);
-check that the user with the given email address exists in your test environment
