### ISSUE TITLE
PasswordBroker has a hard-coded minimum password length of 8 characters (overriding ResetsPasswords::rules() has no effect)

### ISSUE THREAD

**Issue by bastones** [laravel/framework#28274]
- Laravel Version: 5.8.11
- PHP Version: 7.3.1
- Database Driver & Version: N/A

### Description:
In the `\App\Http\Controllers\Auth\ResetPasswordController` class, we make use of the `\Illuminate\Foundation\Auth\ResetsPasswords` trait to handle resetting passwords.

I have noticed that when overriding the `rules()` method [from that trait](https://github.com/laravel/framework/blob/5.8/src/Illuminate/Foundation/Auth/ResetsPasswords.php#L32), setting a lower minimum password length has no effect, because the `validatePasswordWithDefaults()` method of the `\Illuminate\Auth\Passwords\PasswordBroker` class has a hard-coded check [at line 175](https://github.com/laravel/framework/blob/5.8/src/Illuminate/Auth/Passwords/PasswordBroker.php#L175), requiring passwords to be a minimum of 8 characters.

### Steps To Reproduce:

1. On a fresh Laravel installation, add the following method to the `\App\Http\Controllers\Auth\ResetPasswordController` class:

```
    /**
     * Get the password reset validation rules.
     *
     * @return array
     */
    protected function rules()
    {
        return [
            'token' => 'required',
            'email' => 'required|email',
            'password' => 'required|confirmed|min:6',
        ];
    }
```

2. Attempt a password reset request with a password less than six characters.

3. A validation error will occur informing you that the password must be at least eight characters.

**Comment by X-Coder264** [comment]
I don't think that this should be changed. The framework forces at least 8 characters and since this is security related I think it's a very good thing. The NIST guidelines also say that there must be at least 8 characters.

If you really want to put a lower limit the `validatePasswordWithDefaults` method is `protected` so you can extend the broker and override it however you see fit.

**Comment by bastones** [comment]
No. Setting sensible defaults is reasonable, but requiring developers to strip out hard-coded limits which cause validation rules to have no effect, in a very non-obvious way, is not acceptable. The validation rules should be entirely at the discretion of the person using the framework even if you don't like them.

I don't have a problem with the concept but any developer ought to expect the framework to adhere to the validation rules set within their own controller.

I raised this bug because the behaviour is unexpected, not because I have a problem with the higher minimum length, which I agree with. If you want to force developers to go through a mundane process to set a lower minimum length, that should be made obvious if that is part of the design. I shouldn't need to go on a scavenger hunt to find that out.

**Comment by devcircus** [comment]
Though I'm hesitant to make a change here, there is a seeming inconsistency due to the fact that you can just [change the rule](https://github.com/laravel/laravel/blob/master/app/Http/Controllers/Auth/RegisterController.php#L49) while registering and it works, but just [changing the rule](https://github.com/laravel/framework/blob/5.8/src/Illuminate/Foundation/Auth/ResetsPasswords.php#L64) when resetting passwords, does not work because it is [checked again](https://github.com/laravel/framework/blob/5.8/src/Illuminate/Auth/Passwords/PasswordBroker.php#L175) against the hardcoded value in the broker.

So maybe overriding the broker is the right call here, but it does seem odd.

**Comment by driesvints** [comment]
Since this isn't an actual bug but rather how it currently works it's best that this is opened as a feature request in the ideas repo. You could always try to submit a PR to the master branch if you want to propose an improvement.

**Comment by jasonmccreary** [comment]
This _change_ is something that come up a few times with [Shift](https://laravelshift.com). I'm surprised it isn't readily changeable as most apps contain user login and the new requirement of 8 characters would actually be a _breaking change_.

In the end, I agree it's not a _bug_, but how Laravel 5.8 works. With that said, I do think the [Upgrade Guide](https://laravel.com/docs/5.8/upgrade#authentication) should be more detailed in that this isn't a "low" impact but a required change unless one wants to customize the `PasswordBroker`.

**Comment by driesvints** [comment]
@jasonmccreary it's best that an issue in the ideas repo is opened to figure out how we might do this in a better way. It's documented in the upgrade guide. If you feel that more info should be added to the upgrade guide you're free to send in a PR.

**Comment by jasonmccreary** [comment]
In fairness, it's documented in the Upgrade Guide as a "low" impact. Which is rather misleading. In reality it's a "high" impact for applications with login as their app would not function "as is". Meaning without changes in an _upgraded app_ the registration process would allow a 6 character password, but when the user went to reset their password it would require 8. If nothing else, that's inconsistent.

I think the requirement of 8 characters is good. I do think the wording should be more clear as to the requirements of this change. Maybe in future versions, the length could be configurable and honored by both the `RegistrationController` and `PasswordBroker`.

**Comment by driesvints** [comment]
@jasonmccreary the impact could perhaps be higher indeed. Can you send in a PR for that?

**Comment by SeunMatt** [comment]
For those who are left wondering, like me, how do I implement a custom `PasswordBroker`? This is for you here: [https://www.5balloons.info/extending-passwordbroker-class-laravel-5/](https://www.5balloons.info/extending-passwordbroker-class-laravel-5/)

**Comment by caferelgin** [comment]
You should use ResetsPasswords trait and then add a validator closure. To be more specific override these two methods for your version like this:
`
public function reset(Request $request)
{
    $request->validate($this->rules(), $this->validationErrorMessages());
    $this->broker()->validator(function (array $credentials){
		[$password, $confirm] = [
			$credentials['password'],
			$credentials['password_confirmation'],
		];
		return $password === $confirm && mb_strlen($password) >= 6;
	});
            
    $response = $this->broker()->reset(
        $this->credentials($request), function ($user, $password) {
            $this->resetPassword($user, $password);
        }
    );

    return $response == Password::PASSWORD_RESET
                ? $this->sendResetResponse($request, $response)
                : $this->sendResetFailedResponse($request, $response);
}

protected function rules()
{
    return [
        'token' => 'required',
        'email' => 'required|email',
        'password' => 'required|confirmed|min:6',
    ];
}
`

Here you can see the password length is required to be 6 or more characters.
