### ISSUE TITLE
where clauses querybuilder wrongly grouped

### ISSUE THREAD

**Issue by bahfheuv** [laravel/framework#28276]
- Laravel Version: 5.8
- PHP Version: 7.2
- Database Driver & Version: MySQL 5.7

### Description:
When using a combination of where and orWhere, the parameters are wrongly grouped. Since you chain methods together, you expect the where clauses to be chained as well.

When doing 
`builder->where(A)->orWhere(B)->where(C)->where(D)`
 the SQL output is: 
`WHERE (A or B and C) and D`
[In MySQL, the AND takes precedence](https://dev.mysql.com/doc/refman/5.7/en/operator-precedence.html), causing the query to behave unexpectedly.
The statement should read:
`WHERE (A or B) and C and D`

The precedence might be different for other database drivers, the safest way is to wrap each previous where clause in parentheses before adding the next. This would be:
`WHERE ((A or B) and C) and D`

**Comment by ahinkle** [comment]
Try:
```
->where(function ($query) {
    $query->where('foo', 'bar')
        ->orWhere('foo', 'bar2');
})
->where('taylor', 'otwell')
->where('laravel', 'example');

```

**Comment by staudenmeir** [comment]
With your code, I don't get any parentheses (as expected):

```php
DB::table('users')->where('a', 1)->orWhere('b', 2)->where('c', 3)->where('d', 4)->toSql();

// select * from `users` where `a` = ? or `b` = ? and `c` = ? and `d` = ?
```

As @ahinkle shows, it's your responsibility to group the clauses.

**Comment by driesvints** [comment]
Please try the solution from above.
