### ISSUE TITLE
[BUG] Math/arithmetic in DB::insert() causes variables with hyphens/dashes to be converted to a number

### ISSUE THREAD

**Issue by blackdrago** [laravel/framework#28281]
- Laravel Version: 5.4.36
- PHP Version: 5.6.23
- Database Driver & Version: Oracle 11g, using yajra/laravel-oci8 package 5.4.21

### Description:
When using DB::insert(...), string variables that contain a dash/hyphen are being treated as if they are numbers. This is true even if the string contains other non-numeric characters. All of these values I'm currently working with are formatted like this C#####-##, e.g., C12345-67.

This ultimately causes the INSERT query to fail, because the column in the database that stores these values (exclude_study_number) is defined as a VARCHAR(50). 

Wrapping the value in strval() or DB::raw() has had no effect. 

### Steps To Reproduce:
Insert a sting value that contains numbers and a hyphen into a VARCHAR column.

`DB::insert([
    'exclude_study_number' => 'C94043-01'
]);`

The example above is hard coded, but when passed as a variable, the same thing happens. 
Wrapping the value in strval() or DB::raw() has had no effect. 

Yes, the column is named exclude_study_number, but it is defined as  VARCHAR(50).

Is there a way to escape math operands in queries? Is there a reason that the letter C is being handled as a number?

**Comment by ahinkle** [comment]
Hey there,

Have you opened an issue with `yajra/laravel-oci8` or asked in one of the support channels? This is very unlikely an issue with the framework itself.

Thanks!

**Comment by laurencei** [comment]
as @ahinkle mentioned - please open an issue on the `yajra/laravel-oci8` package
