### ISSUE TITLE
setRelation - adds only the last relationship.

### ISSUE THREAD

**Issue by DmitrySkibitsky** [laravel/framework#28298]
#### Laravel Framework 5.7.28

Hi, everybody. Help add data for all relations.
Now for some reason it turns out that only the last relation is added.
``` setRelations ``` works similarly.

#### code
```php
public static function firstOrCreateModel() {
        $cart = Cart::firstOrCreate(self::getWhereQuery());

        if ($cart->delivery === 1) {
            $cart->setRelation('np_area', $cart->with('npArea')->first());
            $cart->setRelation('np_city', $cart->with('npCity')->first());
            $cart->setRelation('np_warehouse', $cart->with('npWarehouse')->first());
            dump($cart->toArray());
        }

        return $cart;
    }
```

#### result
![deepin-screen-recorder_Select area_20190422211106](https://user-images.githubusercontent.com/20288556/56519135-f2152200-6549-11e9-87e9-66a98d950fc8.gif)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
