### ISSUE TITLE
Subdomain Base Without URI , Unable to catch base url.

### ISSUE THREAD

**Issue by rainbowhat** [laravel/framework#28309]
- Laravel Version: 5.8.13
- PHP Version: 7.2.15

### Description:
Route::domain('{account}.myapp.com')->group(function () {
    Route::get('/', function ($account) {
        dd("Cant hit this area");
    });
});

When I visit my subdomain e.g. test.myapp.com it won't hit that DD but if say I do a /test and visit it, it would work. 
I tried doing Route::get(' ' too , leaving it empty but it just wouldn't catch the base subdomain.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
