### ISSUE TITLE
Getting duplicate records with both `isEmpty()` conditional and `firstOrNew`

### ISSUE THREAD

**Issue by PrafullaKumarSahu** [laravel/framework#28304]
- Laravel Version: 5.6.29
- PHP Version: 7.2.10
- Database Driver & Version:  mysql 5.7.25-0

### Description:
I am trying to avoid duplicate records for which post_id and the charm_id combination is already existing. but getting duplicate records in the database.

### Steps To Reproduce:
I have asked the question in [stackoverflow](https://stackoverflow.com/questions/55805858) but it is a better place for it.

**Comment by aqjw** [comment]
migration:   ->unique(["post_id", "charm_id"])

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
