### ISSUE TITLE
The Email validation is not working correct !!!

### ISSUE THREAD

**Issue by TiBianMod** [laravel/framework#28316]
- Laravel Version: 5.8.14
- PHP Version: 7.3.4
- Database Driver & Version: No need

### Description:
> In previous versions of Laravel, I remember only emails like `name@domain.com` will pass the Validation.
> Now emails like `name@domain` are valid ?

### Steps To Reproduce:
```php
Route::get('/', function () {

    $request = [
        'field' => 'n@d', // invalid email address
    ];

    $validator = Validator::make($request, [
        'field' => 'email',
    ]);
     
    if ($validator->fails()) {
        // We need to reach this point and the validation need to fail.
        dd('VALIDATION FAILS');
    }


    // Unfortunately the validation passes :(
    return 'VALIDATION PASSES';
});
```

**Comment by rs-sliske** [comment]
That is a valid email

**Comment by driesvints** [comment]
This is a valid email address. Please see https://github.com/laravel/framework/issues/28233, https://github.com/laravel/framework/issues/27875 and other issues.

**Comment by TiBianMod** [comment]
OK. I see.
One email address don't need to have a TLD to be valid... new stuff.

**Comment by kaythinks** [comment]
For those still having issues with this, use this **'email' => 'email:filter'** which uses the filter_var() method under the hood to check if the email is valid. Refer to https://laravel.com/docs/5.8/validation#rule-email for other email validation types .
