### ISSUE TITLE
No error when calling a non-existent policy method.

### ISSUE THREAD

**Issue by stephan-v** [laravel/framework#28318]
- Laravel Version: 5.5
- PHP Version: 7.2
- Database Driver & Version: Unrelated

### Description:

When implementing a policy no error is thrown if a policy is called that does not exist.

### Steps To Reproduce:

`$user->can('update-value', $property)`

When my PropertyPolicy does not contain an aptly named method:

`updateValue()`

The policy will just return false, but wouldn't it be a lot better to actually throw an error that the policy does not contain the actual method?

Not sure if this should be marked as a bug report but this seems like pretty strange behavior.

**Comment by driesvints** [comment]
This is normal. The `can` method is only used for boolean checking. If you want an exception thrown you could use the `authorize` method in your controllers.

**Comment by stephan-v** [comment]
How it is normal that you can try to call a non-existent method? This is not about the difference between this and an `authorize`. Normally you are also not allowed to call a method that does not exist on a class for example.

Boolean checking or not this should not be allowed if the policy method is not even there.

**Comment by driesvints** [comment]
Please open up an issue on the ideas repo if you want to see this changed.
