### ISSUE TITLE
MethodNotAllowException on Delete Request even when @method('delete') is used.

### ISSUE THREAD

**Issue by cambiotech** [laravel/framework#28320]
Hi There!

I have been getting method not allowed exception for delete request even when I have clearly specified the method as delete.

Here is the Error:
```
Symfony \ Component \ HttpKernel \ Exception \ MethodNotAllowedHttpException
The POST method is not supported for this route. Supported methods: GET, HEAD, PUT, PATCH, DELETE.
```
I have been using the resource route, resource controller, resource policy for the CRUD request. Update works fine but cannot figure out why the delete request is not working.

Did I miss something?

**Comment by devcircus** [comment]
Can you show your routes file?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
