### ISSUE TITLE
Create() method on pivot does not update ID

### ISSUE THREAD

**Issue by elb98rm** [laravel/framework#28327]
- Laravel Version: 5.8
- PHP Version: 7.2
- Database Driver & Version: MySQL 5.7

### Description:

The eloquent create() method does not update the id of a `Pivot` object. 
It should as there are some circumstances (such as complex duplication) where this manual approach is required.

Note 1: Pivots are not JUST joining table A to B. Often it's joining A to B AND instance data about that join. This is where the basic attach/sync functionality can be insufficient in some cases (even if it is valid 90% of the time) 

Note 2: The same result can also be manually achieved using the db/table method. 
However, this may require a "reload" as the actual Pivot object also has useful methods and properties.

### Steps To Reproduce:

Create a Pivot object within the system, mapped to a database such as:

* `class GenericPivot extends Pivot`

Then wherever you are testing from, attempt to 

```
$generic_pivot = GenericPivot::create([ .. ]);
dd($generic_pivot->id)
```

You should get a null response, where it should return the id.

**Comment by staudenmeir** [comment]
Override the `$incrementing` property in your pivot model:

```php
class GenericPivot extends Pivot
{
    public $incrementing = true;
}
```

**Comment by elb98rm** [comment]
That solves the issue. Excellent knowledge.
