### ISSUE TITLE
Real-Time Facades Cause Issues with Policies

### ISSUE THREAD

**Issue by vpillinger** [laravel/framework#28325]
- Laravel Version: 5.7.*
- PHP Version: 7.3
- Database Driver & Version: 

### Description:
Using a Real-Time facade will cause policies to return false without error. This is a tricky source of bugs/undefined behavior. Especially, prevalent is when the IDE auto-imports the facade instead of the base class. Or when someone tries to use Model facades for unit testing.

Instead, it should either match to the underlying model class, or throw exception about being unable to find the policy.

### Steps To Reproduce:
1) Create an empty model, MyModel.php
2) Create a policy MyModelPolicy.php (and register it) with a "view" policy that returns true
```
    public function view(User $user)
    {
        return true;
    }
```
3) Import the model via a facade, `use Facades\App\MyModel;`
4) Call `$this->authorize('view', MyModel::class)` will return false.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.

Thanks!

**Comment by vpillinger** [comment]
@driesvints I upgraded and confirmed that this is also an issue with Laravel 5.8.

**Comment by driesvints** [comment]
Using models as a facade isn't something that's supported I believe. This is more of a question for a support channel so can you try one of these?

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

**Comment by devcircus** [comment]
This definitely is not and shouldn't be supported. The facade allows you to access methods on the class. It doesn't serve as a replacement for the class itself, however, it may make sense to throw an exception when a class is passed that isn't the model. 🤷🏻‍♂️ Honestly, I think the developer should just make sure the model is passed, if that’s what is expected.

**Comment by vpillinger** [comment]
It would make sense to disallow model Facades explicitly and/or make the Policies throw some sort of warning/exception if the Policy for the passed class is not found.

Please consider how the the following affect each other:
1) Importing a Model Facade over a normal Model class does otherwise "work", even though it doesn't really make sense conceptually. They also silently fail to work with Policies and maybe other behaviors, with no Exception being thrown even though its not supported.
2) Model Facades can get auto-imported by IDEs over the normal Model. For example, it shows up as an option in PHP Storm. This can accidentally trap even experienced developers relying on auto-import.

Imo, combining these two just creates an unnecessary situation which seems very developer unfriendly. At least some warning or exception should display at some point.

Its like that old Java trap where people import java.awt.List instead of java.util.List by accident and spend hours debugging it because the interface is the same so no errors are thrown. But their program doesn't work because its the wrong class :).

**Comment by devcircus** [comment]
Specifically disallowing facades doesn’t seem right. There are many places throughout the framework where you should use a model. We shouldn’t go through and identify all of these places and disallow a facade. Also, this is not a documented use of real-time facades. Models are designed to be easy to use with static access to instance methods without resorting to making your models into facades. 

I suggest we just use this how it is documented. Otherwise, if it’s possible to disallow everything that shouldn’t be used, let’s do it. If not, do nothing.
