### ISSUE TITLE
Cache ttl get error when use CACHE_DRIVER=memcached

### ISSUE THREAD

**Issue by bolechen** [laravel/framework#28333]
- Laravel Version: 5.8.14
- PHP Version: 7.2.17-1+ubuntu18.04.1+deb.sury.org+3
- Database Driver & Version: None
- Libmemcached version: 1.0.18

### Description:
When use `CACHE_DRIVER=memcached` set ttl not return correct value.

### Steps To Reproduce:

```
$ php artisan tinker
Psy Shell v0.9.9 (PHP 7.2.17-1+ubuntu18.04.1+deb.sury.org+3 — cli) by Justin Hileman
>>> cache(['aaa'=>'bbb'], 3600)
=> true
>>> cache('aaa')
=> null
>>> cache(['aaa'=>'bbb'], 28800)
=> true
>>> cache('aaa')
=> null
>>> cache(['aaa'=>'bbb'], 28810)
=> true
>>> cache('aaa')
=> "bbb"
>>> Cache::set('aaa', 'bbb')
=> true
>>> Cache::get('aaa')
=> "bbb"
```

When the ttl set small than 28800, it always expired return null.
Change the CACHE_DRIVER to others, it works  fine.

**Comment by driesvints** [comment]
This works for me:

```bash
$ /usr/local/Cellar/php@7.2/7.2.15/bin/php artisan tinker
Psy Shell v0.9.9 (PHP 7.2.15 — cli) by Justin Hileman
>>> cache(['aaa'=>'bbb'], 3600)
=> true
>>> cache('aaa')
=> "bbb"
>>> cache('aaa')
=> "bbb"
>>> cache(['aaa'=>'bbb'], 28810)
=> true
```

Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
