### ISSUE TITLE
Migration shows "Nothing to migrate" when it is run individually

### ISSUE THREAD

**Issue by surajgusain** [laravel/framework#28332]
- Laravel Version: 5.6.39
- PHP Version: 7.3.4
- Database Driver & Version: Postgresql 11.2

### Description:
I have two migrations in my application. I want to run them individually. But they console "Nothing to migrate" to me. I tried placing the migrations into a separate folder yet it shows me the same console message "Nothing to migrate"

### Steps To Reproduce:
1. Generate two migration files. Run `php artisan migrate`
2. Manually delete migrations from `migrations` table.
3. Run migration individually using the following command:
`php artisan migrate --path="/database/migrations/2019_04_18_161256_add_user.php"

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.

Thanks!
