### ISSUE TITLE
Rate limit using different units

### ISSUE THREAD

**Issue by Adam-78** [laravel/framework#28334]
Laravel Version 5.7

Laravels api rate limit unit is per minute. I have a autocomplete api endpoint which I would like to rate limit 20 queries per second. Is this possible i.e. to define a rate limit unit?

Note I've already asked on Stackoverflow and no one has any ideas.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.

Thanks!

**Comment by Adam-78** [comment]
Hi,

I've updated to 5.8 but I still can't see any way to define the rate limit unit in seconds?

**Comment by Adam-78** [comment]
It's ok I've figured it out. The unit value accepts float so I can divide 1 minute by 60 to get the seconds e.g. 0.017 and pass in the paramter as follows:

    Route::middleware('auth:api', 'throttle:20,0.017')->group( function ()
    {
    
         Route::get('/locations/{term}', 'LocationController@index');
 
   });
