### ISSUE TITLE
Redis connection contract

### ISSUE THREAD

**Issue by Firtzberg** [laravel/framework#28340]
- Laravel Version: 5.8

Why doesn't https://github.com/laravel/framework/blob/5.8/src/Illuminate/Redis/Connections/Connection.php implement https://github.com/laravel/framework/blob/5.8/src/Illuminate/Contracts/Redis/Connection.php ?

I am injecting a Redis connection into a service and would be more comfortable with injecting a contract than a class.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
