### ISSUE TITLE
Empty vendor/illuminate/config folder

### ISSUE THREAD

**Issue by paKanhu** [laravel/framework#28344]
- Laravel Version: 5.8.14
- PHP Version: 7.3.4
- Database Driver & Version:

### Description:
`composer require illuminate/config` creates empty vendor/illuminate/config folder. This is not happening, when using GitHub repo as repository source for illuminate/config in composer.json and dependency on illuminate/config:5.8.9.

This issue is breaking all packages, which have dependency on illuminate/config.

### Steps To Reproduce:
1. `mkdir test-illuminate-config`
2. `cd test-illuminate-config`
3. `composer require illuminate/config`
4. `ls -la vendor/illuminate/config`

**Comment by driesvints** [comment]
This works for me:

![Screen Shot 2019-04-26 at 11 35 27](https://user-images.githubusercontent.com/594614/56798581-528cb380-6817-11e9-8eca-aa91a5b078d3.png)
