### ISSUE TITLE
belongsToMany, Table does not exist with two separate connections

### ISSUE THREAD

**Issue by hvlucas** [laravel/framework#28350]
- Laravel Version: 5.6.39
- PHP Version: 7.1.5
- Database Driver & Version: MySQL 14.14

### Description:
When defining a belongsToMany relationship where the end table is on a separate connection, an error occurs where a table is not found from the same connection as the initiating class. 

### Steps To Reproduce:

    class ClassA extends Model {

      protected $connection = 'connectionA';

      public function relationship()
      {
        return $this->belongsToMany('App\ClassB', 'database.pivot_table')->using('App\BrigdeTableClass');
      }

    }

    class ClassB extends Model {
      protected $connection = 'connectionB';
    }

    class BridgeTableClass extends Pivot {
      protected $connection = 'connectionA';
      protected $table = 'pivot_table';
    }

    $classA->relationship()->attach(1);
    //Outputs
    Illuminate/Database/QueryException with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'database.pivot_table' doesn't exist

**Comment by staudenmeir** [comment]
Please see https://github.com/laravel/ideas/issues/1583.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.

Thanks!
