### ISSUE TITLE
Links() render of Pagination broke when using SortBy()

### ISSUE THREAD

**Issue by Jaspur** [laravel/framework#28353]
- Laravel Version: v5.8.14
- PHP Version: 7.3
- Database Driver & Version: PostgreSQL

### Description:
When adding a ```sortBy()``` to a paginated query I returns the error:
```
Method Illuminate\Database\Eloquent\Collection::links does not exist.
```
Saying this function (which is default for pagination) isn't working:
```{{ $results->links() }}```
When I remove that function in the view, it does render correctly and also the same amount of items as given to the paginate function.

### Steps To Reproduce:
Make a Query like this:
```
$results = Company::has('location')->paginate(10)->sortBy(function ($company) {
    return $company->location->distance; // for example
}); 
```
Add in the view: ```{{ $results->links() }}``` and then you'll see the error. Remove tat from the view and it'll work.

**Comment by devcircus** [comment]
This is correct. The paginator forwards the "sortBy" call to the paginator's collection, returning the collection. Collections don't have a "links" method. There are many solutions on stackoverflow for handling this situation.

You can either swap the paginator's collection with the sorted collection, or build up a Paginator manually with the sorted data.

Either way, you'll probably get more help on one of the support channels:
[Laracasts Forums](https://laracasts.com/discuss)
[Laravel.io Forums](https://laravel.io/forum)
[Discord](https://discordapp.com/invite/KxwQuKb)
[Larachat](https://larachat.co/)
[IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
[StackOverflow](https://stackoverflow.com/)

**Comment by staudenmeir** [comment]
> You can either swap the paginator's collection with the sorted collection

```php
$results = Company::has('location')->paginate(10);

$results->setCollection(
    $results->sortBy(function ($company) {
        return $company->location->distance;
    })
);
```

**Comment by Jaspur** [comment]
@staudenmeir looks promising, but it sorts the distances of the given paginated values and no the whole collection of results ;-)

**Comment by staudenmeir** [comment]
@Jaspur I don't see how that could be happening.

What does the result of `dd($results->sortBy(...));` look like?

**Comment by Jaspur** [comment]
@staudenmeir the result is correct and shown as a paginator, but because you pagina to each 10 results.. it does the sorting for thát specific 10 results each time. you get what I mean? ;-) 
there should be a full get() to fetch all results, then sort them by location and thén paginate them.

**Comment by staudenmeir** [comment]
Now I see the issue, I misread your comment.

This requires a different query: You have to join the `locations` table and use `orderBy()`.
Do you know what I mean?

**Comment by Jaspur** [comment]
Nope? @staudenmeir

**Comment by staudenmeir** [comment]
Something like this:

```php
$results = Company::select('companies.*')
    ->join('locations', 'locations.id', '=', 'companies.location_id')
    ->orderBy('locations.distance')
    ->paginate(10);
```

**Comment by Jaspur** [comment]
@staudenmeir the problem it that it can't do the orderBy(), because the distance is only available via the sortBy() because it's calculated afterwards and not stored in the database.

**Comment by devcircus** [comment]
The implementation is immaterial to the original post. You'll have to figure out how to implement this and then swap the paginator's collection with what you need.

**Comment by staudenmeir** [comment]
Is https://stackoverflow.com/q/55872233/4848587 your question?
