### ISSUE TITLE
Bearer Token - Accept HTTP2 headers in lowercase

### ISSUE THREAD

**Issue by renanwilliam** [laravel/framework#28354]
- Laravel Version: 5.6.39
- PHP Version: 7.2.15
- Database Driver & Version: MySQL

### Description:
When I using AWS Application Load Balancer with HTTP2, it automatically convert all headers keys to lowercase. In this line it is hard coded to get header with camel case https://github.com/laravel/framework/blob/5.8/src/Illuminate/Http/Concerns/InteractsWithInput.php#L55

### Steps To Reproduce:
It's necessary setup a laravel application with passport behind a ALB in AWS.

**Comment by mfn** [comment]
I don't think your assertion is entirely correct. The trait is quite an abstraction, but in the end the code calls `$this->headers->get()` on the Laravel Request which extends `\Symfony\Component\HttpFoundation\Request` whose `$headers` is defined as `\Symfony\Component\HttpFoundation\HeaderBag`.

Now, the `HeaderBag` has `strtolower` sprinkled all over the place for set/get.

However, 5.6.39 is quite old and not supported anymore, maybe it worked differently (but I would doubt that).

**Comment by renanwilliam** [comment]
Hi @mfn 
You are right, is not the root cause of my problem.

Trying figure out what is the problem yet.
