### ISSUE TITLE
Validator should set default min and max size of integers

### ISSUE THREAD

**Issue by bjornarhagen** [laravel/framework#28365]
I feel like it would be nice to be able to just write this:
```php
Validator::make($data, [
        'input_value' => ['unsignedInteger'],
        // or:
        'input_value' => ['integer', 'unsigned', 'min:auto', 'max:auto'],
    ]);
}
```
This would make sure the input is `min:0` and `max:4294967295` by default.

With the way it works today, you have to type it out like so:
```php
Validator::make($data, [
        'input_value' => ['integer', 'min:0', 'max:4294967295'],
        // or like this:
        'input_value' => ['integer', 'min:0', 'max:' . (pow(2, 32)-1)],
    ]);
}
```
Feels a little unnecessary to have to do this. Would also be nice to have something like this for text fields.

**Comment by devcircus** [comment]
Sounds like a feature request. The more common use-case is for specific max and min values. I've never had a use for the actual smallest and largest unsigned integer values. It would be best to add an issue to the laravel/ideas repo and see what the community thinks.

**Comment by bjornarhagen** [comment]
Oops, clicked a bit too fast. I'll post it over in laravel/ideas :smile:
