### ISSUE TITLE
Redis exceptions on timed out connections

### ISSUE THREAD

**Issue by ragingdave** [laravel/framework#28368]
- Laravel Version: 5.7.x
- PHP Version: 7.2.17
- Database Driver & Version: Redis 4.0.2

### Description:
In a configuration using haproxy as a load balancer between application and redis, I am hitting an "Error while reading line from the server" error during a longer running process.
This is forcing a condition where the timeouts in haproxy are required to be fairly high, which means that connections that otherwise might be closed, are remaining open. This issue occurs only on the predis driver and upon switching to the phpredis driver, the issue is alleviated.

### Steps To Reproduce:
Fairly involved, but basically have an haproxy instance in between your app and redis instance, then have the `timeout server` and `timeout client` settings configured to something reasonable like 1 minute. Have a process that does something redis wise, sleeps for longer than the timeout, then try and run another redis command. On predis, this will fail, but on phpredis it will succeed.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.

Thanks!
