### ISSUE TITLE
SessionGuard should set the password through the user provider

### ISSUE THREAD

**Issue by netpok** [laravel/framework#28367]
- Laravel Version: 5.6+

Currently the SessionGuard regenerates the password via [a simple Hash::make call](https://github.com/laravel/framework/blob/5.8/src/Illuminate/Auth/SessionGuard.php#L550), in the rare case when the user provider is set up with a different hasher than the default this can update the password to an incompatible one. 

I think this should be fixed, the easiest solution would be to make available the hasher on the DatabaseProvider like its available on the EloquentProvider and then use a `$this->provider->hasher->make()` call, but this could break existing implementations.

**Comment by driesvints** [comment]
The hash manager is set by the driver setting in the hashing config so I'd expect this to work if the driver is properly configured? https://github.com/laravel/laravel/blob/master/config/hashing.php#L18

**Comment by netpok** [comment]
Yes, that should work, this is more like a theoretical as I think nobody would use this way, but if someone overrides the hasher with contextual binding than this can be a problem, because it's not enough to override it for one class.

**Comment by driesvints** [comment]
I that case I'd just recommend to roll with a custom hasher.
