### ISSUE TITLE
Model local scope recieves different amount of parameters

### ISSUE THREAD

**Issue by humunuk** [laravel/framework#28361]
- Laravel Version: 5.7
- PHP Version: 7.1
- Database Driver & Version: MySQL

### Description:

Model specific scope sometimes receives 2 instead of 1 parameter.
This makes it almost impossible to pass and unpredictable to pass in random parameters,
because at one point you get TooFewArgumentsPassed exception.

### Model relations

Model1 => hasMany Model3
Model3 => hasMany Model4
Model4 => belongsTo Model5

Model2 => ManyToMany Model5

Model5 => ManyToMany Model6

Scenario 1:
```
Model1->load(Model3.Model4.Model5 => function($query) {
    $query->with([Model6 => function($query) {
        $query->whereStuff($parameter);
    }]);
});
```

Scenario 2:
```
Model2->load(Model5.Model6 => function($query) {
    $query->whereStuff($parameter);
});
```

### Steps To Reproduce:

create local scope in Model6:

```
public function scopeWhereStuff() {
  dd(count(func_get_args));
}
```

Scenario 1:
dd(count(func_get_args)); => 2

Scenario 2:
dd(count(func_get_args)); => 3

In case of scenario 2 a BelongsToMany relation is also passed in.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.

Thanks!

**Comment by humunuk** [comment]
I opened new issue after validating that the problem persists. #28363
