### ISSUE TITLE
Model local scope receives different amount of parameters

### ISSUE THREAD

**Issue by humunuk** [laravel/framework#28363]
- Laravel Version: 5.8.14
- PHP Version: 7.1.28
- Database Driver & Version: MySQL

### Description:

Model specific scope sometimes receives 2 instead of 1 parameter.
This makes it almost impossible to pass and unpredictable to pass in random parameters,
because at one point you get TooFewArgumentsPassed exception.

### Model relations

Model1 => hasMany Model3
Model3 => hasMany Model4
Model4 => belongsTo Model5

Model2 => ManyToMany Model5

Model5 => ManyToMany Model6

Scenario 1:
```
Model1->load(Model3.Model4.Model5 => function($query) {
    $query->with([Model6 => function($query) {
        $query->whereStuff($parameter);
    }]);
});
```

Scenario 2:
```
Model2->load(Model5.Model6 => function($query) {
    $query->whereStuff($parameter);
});
```

### Steps To Reproduce:

create local scope in Model6:

```
public function scopeWhereStuff() {
  dd(count(func_get_args));
}
```

Scenario 1:
dd(count(func_get_args)); => 2

Scenario 2:
dd(count(func_get_args)); => 3

In case of scenario 2 a BelongsToMany relation is also passed in.

**Comment by driesvints** [comment]
Can you maybe recreate this problem on a sample app and load it up to a public repo on Github so we can reproduce? There seems to be some really specific code involved here and it would help if we got all of that. Try to commit the faulty code in a separate commit if possible.

**Comment by staudenmeir** [comment]
Please provide a minimal example with default models like `User`, `Post` and `Comment`.

**Comment by humunuk** [comment]
I will look more into it. I did create fresh project with schema I pointed out in original post and the issue didn't replicate.

I then cleaned our code to be more representable to schema and the issue persisted.

I have solved it currently with just getting param count with func_get_args, once I have a bit more time I will try go more deeply into the problem.

Thank you for helping out

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
