### ISSUE TITLE
Str::contains

### ISSUE THREAD

**Issue by emanuelpontesde** [laravel/framework#28371]
- Laravel Version: 5.2
- PHP Version: 7.2.17

### Description:
"str_contains" return incorrect value when secound arguent is ZERO;
var_dump(str_contains('1',0));
bool(false)
 
var_dump(str_contains('1',1));
 bool(true)

### Steps To Reproduce:
var_dump(str_contains('1',0));
var_dump(str_contains('1',1));

**Comment by netpok** [comment]
What should it return? This looks correct to me.

Also please note that Laravel 5.2 is not supported since [June 21st, 2016](https://laravel.com/docs/5.8/releases#support-policy) so you probably want to upgrade it to receive the latest security (and non-security) updates.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.

Thanks!
