### ISSUE TITLE
Unable to locate factory with name [default]

### ISSUE THREAD

**Issue by mesadhan** [laravel/framework#28378]
- Laravel Version: 5.8.*
- PHP Version: 7.2.5
- Database Driver & Version: sqlite

### Description:

```php
public function testCreateRecord()
{
	// case 1:
	$factory = factory('App\User')->create([
		'name' => 'test',
		'email' => 'test@laravel.com',
		'password' => Hash::make('1'),
	]);

	// case 2:
	$factory = factory('App\Http\Models\Stock')->create([
		'name' => 'mango',
		'price' => 300,
	]);

	$this->assertEquals('mango', $stock->name);
	$this->assertEquals(300, $stock->name);
}
```

> I don't know case 1  working fine but why case 2 throws an error.
` (InvalidArgumentException : Unable to locate factory with name [default] [App\Http\Models\Stock].)`

As I defined an `App\Http\Models\Stock` model and it's working properly, But not working in `factory` method.
### Steps To Reproduce:
- Create new laravel project.
- Create Model base on the given namespace
- Then Try to use factory method

**Comment by brunogaspar** [comment]
Ensure your `Stock` model has the correct namespace, otherwise the error you're receiving is normal

**Comment by mesadhan** [comment]
It's working fine. namespaces are given properly. when I execute

```
 $stock = Stock::create([
        'name' => 'mango',
       'price' => 200,
]);
```
It's working fine. and store data in database.

**Comment by brunogaspar** [comment]
Can you paste your `Stock` model code.

**Comment by mesadhan** [comment]
```

<?php

namespace App\Http\Models;

use Illuminate\Database\Eloquent\Model;

class Stock extends Model
{
    //
    protected $fillable = [
        'name',
        'price'
    ];

    public $timestamps = true;
}


```

**Comment by timur-gilauri** [comment]
Hey, how have you solved it???

**Comment by felloz** [comment]
Same problem here!

**Comment by browner12** [comment]
this most likely looks like a userland error, not a framework bug.

the problem is most likely in your StockFactory class.

please move this conversation over to:

Laravel Slack (https://larachat.co/)
Laravel.io Forum (https://laravel.io/forum)
Laracasts Forum (https://laracasts.com/discuss)
StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks!

**Comment by timur-gilauri** [comment]
I had this issue during develop artisan console command trying to pass model class full name with namespace as command option. So I found out that the class path must start with back slash `\` like `"\App\Models\Model"`. Even if you see factories defined without it.

**Comment by wdarking** [comment]
In my case it was because unit tests stubs in late laravel versions are extending `PHPUnit\Framework\TestCase` instead of the `Tests\TestCase`. In this case, the factories will not work because the framework will not be booted. More details here: https://github.com/laravel/framework/issues/30879#issuecomment-567456608

The solution for me was to make my test extend the laravel TestCase class instead of phpunit TestCase.

Something like this:
```
<?php

namespace Tests\Unit;

use Tests\TestCase;
// use PHPUnit\Framework\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;

class PaymentModelTest extends TestCase
{
    use RefreshDatabase;

    public function testPaymentModelUuidOnCreated()
    {
        $payment = factory(\App\Payment::class)->create();

        $this->assertNotNull($payment->uuid);
    }
}
```

**Comment by mitesh1409** [comment]
@wdarking 

> In my case it was because unit tests stubs in late laravel versions are extending `PHPUnit\Framework\TestCase` instead of the `Tests\TestCase`. In this case, the factories will not work because the framework will not be booted. More details here: [#30879 (comment)](https://github.com/laravel/framework/issues/30879#issuecomment-567456608)
> 
> The solution for me was to make my test extend the laravel TestCase class instead of phpunit TestCase.
> 
> Something like this:
> 
> ```
> <?php
> 
> namespace Tests\Unit;
> 
> use Tests\TestCase;
> // use PHPUnit\Framework\TestCase;
> use Illuminate\Foundation\Testing\RefreshDatabase;
> 
> class PaymentModelTest extends TestCase
> {
>     use RefreshDatabase;
> 
>     public function testPaymentModelUuidOnCreated()
>     {
>         $payment = factory(\App\Payment::class)->create();
> 
>         $this->assertNotNull($payment->uuid);
>     }
> }
> ```

I faced exactly the similar issue.
And resolved it by removing 
`use PHPUnit\Framework\TestCase;`
and then adding
`use Tests\TestCase;`

But is there anyway we can solve it by keeping 
`use PHPUnit\Framework\TestCase;`

It seems that we won't be able to make use of Laravel Model Factories in the Unit tests out of the box.

**Comment by wdarking** [comment]
@mitesh1409 the class `Tests\TestCase` actually extends the abstract class `Illuminate\Foundation\Testing\TestCase`, which extends the `PHPUnit\Framework\TestCase` class.

So, if you want to use the framework features like factories on your **Unit Tests**, you should use `Tests\TestCase`.

> It seems that we won't be able to make use of Laravel Model Factories in the Unit tests out of the box.

About that: as you can see [here](https://github.com/laravel/framework/issues/30879#issuecomment-567456608) they changed the Unit tests `TestCase` so the tests can run faster, and if you need to use factories on your tests, maybe you should consider placing them in the Feature directory.

> But is there anyway we can solve it by keeping `use PHPUnit\Framework\TestCase;`

Well i think you could create your own base TestCase class which extends `PHPUnit\Framework\TestCase` and try to load the whatever framework features you need (like factories), but i think this would be cumbersome.

**Comment by mitesh1409** [comment]
@wdarking 
Thanks for your detailed answer.

So I believe if we want to make use of Model Factory feature in unit tests, then importing 
"Tests\TestCase" instead of "PHPUnit\Framework\TestCase" is perfectly fine and is not a bad practice.
The only drawback is that it will run slow since it will boot the framework.

Thanks again :)
