### ISSUE TITLE
Route::getRoutes() returns only package routes

### ISSUE THREAD

**Issue by ellis22** [laravel/framework#28385]
I am trying to fetch all routes in Laravel package using `\Illuminate\Support\Facades\Route::getRoutes();`. But it gives only package routes, not the entire Laravel application routes. 

Is there any way to fetch entire Laravel application routes inside the package.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
