### ISSUE TITLE
Uploading XLSX file: extension method returns 'zip'

### ISSUE THREAD

**Issue by lcardosozago** [laravel/framework#28381]
- Laravel Version: 5.8.15
- PHP Version: 7.2.17

### Description:
When I upload a `xls` file, the `$request->file->extension()` works and returns "xls"
But when I upload a `xlsx` file, the same command returns "zip" instead of "xlsx"
Why?

### Steps To Reproduce:
Upload a `xlsx` file

Form example:
```
<form action="/excel" enctype="multipart/form-data" method="POST">
    <div class="row">
        <?= csrf_field() ?>
        <div class="col-4">
            <input type="file" name="excel" class="form-control"/>
        </div>
        <div class="col-2">
            <input type="submit" class="form-control btn btn-primary">
        </div>
    </div>
</form>
```

Controller:
```
return var_dump($request->excel);
#and
return var_dump($request->excel->extension());
```

**Comment by staudenmeir** [comment]
Technically, that's correct: `xlsx` files are ZIP archives.

**Comment by lcardosozago** [comment]
@staudenmeir oh, I thought `extension()` was from the filename.
So I think I have to do it manually.

**Comment by lcardosozago** [comment]
@staudenmeir thanks for your time.

**Comment by fasthold** [comment]
Which method could get the 'xlsx' extension?
