### ISSUE TITLE
laravel preset none

### ISSUE THREAD

**Issue by jksdn** [laravel/framework#28384]
- Laravel Version: 5.8
- PHP Version: 7.3
- Database Driver & Version: mysql@5.7

### Description:
When setting a preset to none and after running 'npm run dev' its also pull vue-template-compiler, also if to set preset to react and then set back to none, will pull @babel/preset-react

### Steps To Reproduce:
Set preset to none, after crafting application:
`php artisan preset none`

Installing all dependencies and run 'npm run dev'
`npm install && npm run dev`

`Additional dependencies must be installed. This will only take a moment.
 
 	Running: npm install vue-template-compiler --save-dev --production=false
 
 	Okay, done. The following packages have been installed and saved to your package.json dependencies list:
 
 	- vue-template-compiler`

**Comment by morpheus7CS** [comment]
Hey,

I have tested this and @jksdn is correct in identifying that issue. Have submitted [a pull request](https://github.com/laravel/framework/pull/28389) that fixes it.

Thanks @jksdn!

**Comment by driesvints** [comment]
PR was merged.

**Comment by jksdn** [comment]
The same problem, nothing change, laravel v5.8.15

And I noticed another issue when set preset to react, and after set back to none, in the webpack mix does not change from react to js

`
mix.react('resources/js/app.js', 'public/js').sass('resources/sass/app.scss', 'public/css');
`

**Comment by devcircus** [comment]
The release with this fix hasn't been released yet. Probably early next week.
