### ISSUE TITLE
thenPing and pingOnSuccess not running on scheduled jobs

### ISSUE THREAD

**Issue by Grayda** [laravel/framework#28390]
- Laravel Version: 5.8.15
- PHP Version: 7.2
- Database Driver & Version: `mysql` database driver, `sync` queue driver or `database` queue driver

### Description:
`thenPing`, `pingOnSuccess` and `pingOnFailure` aren't called when a *job* is scheduled. Only when a *command* is scheduled (seemingly regardless of what type of queue driver is being used). I've verified this is the case by looking at Wireshark

I haven't tried `thenPing` on 5.7 (as I migrated from 5.7 to 5.8.15 so I could use `pingOnSuccess`)

The docs don't say that it can't be used with jobs, nor does the source code indicate that, so I'm confused as to why it won't work.

### Steps To Reproduce:
1. Create a new project
2. Create a job with `php artisan make:job DoSomething`
3. Edit `app/Console/Kernel.php` and schedule a job and a command like so:

```php
$schedule->command('inspire')->everyMinute()->pingOnSuccess('http://example.com/command');`
$schedule->job(new DoSomething)->everyMinute()->pingOnSuccess('http://example.com/job');
```

4. Run the scheduler with `php artisan schedule:run`
5. Check the logs of the server you're attempting to ping, or Wireshark output or whatever
6. Only `example.com/command` will be pinged.

**Comment by driesvints** [comment]
This is based on [the following pr](https://github.com/laravel/framework/pull/28140) which tracks the exit code of commands, something that's not available for jobs. So this can't work with jobs atm. Notice also that all the examples in the docs are with commands. See the relevant pr here: https://github.com/laravel/framework/pull/28167

If you want these methods to work with jobs as well you could raise an issue in the ideas repo and perhaps send a PR. Thanks!
