### ISSUE TITLE
Collection Eloquent API Resource converting the passed collection to base

### ISSUE THREAD

**Issue by tonysm** [laravel/framework#28396]
- Laravel Version: 5.7.12 and 5.8.15
- PHP Version: 7.1.28 and 7.2.17
- Database Driver & Version: mysql:5.7 and sqlite:3

### Description:

When I pass down a paginator to a Collection API Resource, it collects the items into `\Illuminate\Support\Collection` instead of `\Illuminate\Database\Eloquent\Collection`. It also sets the new collection into the paginator itself. 

I do have a use case where I need to do lazy loading on some of the resource's relationships, so I end up wrapping the collection back to an eloquent collection whenever I need to do this. This doesn't feel right. Was this intentional?

Issue:

```php
$users = App\User::paginate();
dump($users); // \Illuminate\Pagination\LengthAwarePaginator
dump($users->getCollection()); // \Illuminate\Database\Eloquent\Collection

$resourceCollection = new App\Http\Resources\UserCollection($users);

dump($resourceCollection->collection); // \Illuminate\Support\Collection
dump($resourceCollection->resource); // \Illuminate\Pagination\LengthAwarePaginator
dump($resourceCollection->resource->getCollection()); // \Illuminate\Support\Collection
```

The workaround I mentioned:

```php
$users = App\User::paginate();

return App\Http\Resources\UserCollection::make($users)
    ->includeArticlesCount(true);
```

Then in the collection resource:

```php
    public function includeArticlesCount(bool $shouldInclude)
    {
        if (! $shouldInclude) return $this;

        $articlesCountByUser = \Illuminate\Database\Eloquent\Collection::wrap($this->collection)
            ->loadCount('articles')
            ->mapWithKeys(function ($user) {
                return [$user->id => $user->articles_count];
            });

        return $this->additional([
            'included' => [
                'articles_count' => $articlesCountByUser,
            ],
        ]);
    }
```

### Steps To Reproduce:

I have created a repository to show the issue [here](https://github.com/tonysm/laravel-issue-with-api-resources).

[Here's](https://github.com/tonysm/laravel-issue-with-api-resources/blob/master/tests/Feature/ExampleTest.php#L16) the test that shows that the paginator collection (which had an Eloquent) collection before got a new base collection.

Here's a test that demonstrates how we are using [lazy-loading](https://github.com/tonysm/laravel-issue-with-api-resources/blob/master/tests/Feature/ExampleTest.php#L37-L60) and the workaround in the [collection resource](https://github.com/tonysm/laravel-issue-with-api-resources/blob/master/app/Http/Resources/UserCollection.php#L21-L36)

**Comment by driesvints** [comment]
Think I figured it out. You basically end up on this line:

https://github.com/laravel/framework/blob/5.8/src/Illuminate/Http/Resources/CollectsResources.php#L26

Which calls the `toBase` method on the eloquent collection. Because this is a method on the support collection with a `new self` call it instantiates a new support collection instead of a new eloquent collection. 

https://github.com/laravel/framework/blob/5.8/src/Illuminate/Support/Collection.php#L2018

Now I believe the `toBase` call is probably intentional but I don't know why exactly.

**Comment by driesvints** [comment]
The override on the paginator is also definitely intentional but again, no clue why.

**Comment by staudenmeir** [comment]
I think `$resource->toBase()` is a convenient way to get a collection from both collections and paginators.

We could differentiate between these types:

```php
$this->collection = $collects && ! $resource->first() instanceof $collects
    ? $resource->mapInto($collects)
    : ($resource instanceof AbstractPaginator ? $resource->getCollection() : $resource);
```

**Comment by tonysm** [comment]
Uhm, since it replaces the collection in with the new collection of resources:

```php
$users = $this->resource->getCollection();
```

returns a collection of `App\Http\Resources\User`, so I have to re-map it, like:

```php
$users = $this->resource->getCollection()->map->resource;
```

to get a `Illuminate\Support\Collection` of `App\User` entities. IMO, we shouldn't change the paginator collection. I can try to send a PR today with this "change", but not sure if that's the desired behavior.

**Comment by themsaid** [comment]
@tonysm I'm not sure I get what you're trying to do here. Why don't you do all the Eloquent operations before you pass the Eloquent collection to the Resource collection?

**Comment by tonysm** [comment]
@themsaid yes, I can try to eager-load everything in the query itself. But, sometimes, I have embedded resources that are not mapped directly into relationships.

For instance:

```
Buildings hasMany Organizations
Organizations hasMany Users
```

And I want to return the users count in the `GET /buildings?include=users_count`. The eager-loading logic would be more complex than lazy-loading it:

```php
public function index(ListBuildingsRequest $request, UsersRepository $users)
{
  $buildings = Building::paginate();

  return \App\Http\Resources\BuildingCollection::make($buildings)
    ->includeUsersCountIf($request->includes('users_count'), $users);
}
```

Then in the `BuildingCollection` I can do:

```php
public function includeUsersCountIf(bool $shouldInclude, UsersRepository $users): BuildingCollection
{
  if (! $shouldInclude) return;

  $usersCountByBuildingId = $users->getUsersOfBuildings(
    $this->resource->getCollection()->map->resource
  );

  return $this->additional([
    'included' => [
      'users_count' => $usersCountByBuildingId,
    ],
  ]);
}
```

To eager load this, I would have to come up with something more complex data structures. Unless I'm missing something. If you see a better way of doing this, pls, let me know. :)

**Comment by themsaid** [comment]
@tonysm if I were you I'd create an aggregate on the organizations table with the number of users instead of having to run such query.

It seems you want to load all users of all organizations of the building, pass that to the Collection and check if the desired relationship is loaded or not to decide if you should load the count.

But again, if I'm writing this app I'll aggregate the users count if it's so important to know how many users in a building.

**Comment by driesvints** [comment]
Hey @tonysm. Since it seems that the current mechanics are very much intended to work as they do now I suggest that it's best that this is taken up further on a support channel or an issue is posted on the ideas repo if you feel we could improve this functionality. Thanks for reporting!
