### ISSUE TITLE
Request: public renderPlain() for debugging/testing Plain Text Output of Markdown Mailables

### ISSUE THREAD

**Issue by jakedowns** [laravel/framework#28395]
a `public` `->renderPlain()` or `->renderText()` method would be a nice addition to Mailable

it would be nice if we could get the output of buildMarkdownView > buildMarkdownText for debugging / testing against the the Plain Text output of Markdown Mailables.

currently, I have to either send it to mailtrap/mailcatcher to debug the non-html version, or I have to fully Send the Email and then use the `withSwiftMessage` callback to pull out the rendered plain text. Which works fine, but we like to display email previews in our CMS and sending an email every time someone clicks for the plain text preview seems like overkill.

```
->withSwiftMessage(function ($message) use (&$plain_text_output) {
  $plain_text_output = $message->getChildren()[0]->getBody();
});
```

am I missing something obvious?

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!
