### ISSUE TITLE
[5.8] Issue with Pivot and SoftDeletes since #27571

### ISSUE THREAD

**Issue by lk77** [laravel/framework#28407]
- Laravel Version: 5.8.15
- PHP Version: 7.2
- Database Driver & Version: mysql 5.7

### Description:

Hello,

Since laravel 5.8 and this PR **(#27571)** pivot relations that uses SoftDeletes trait are not working anymore. 

When using sync() to update a relation, removed elements are now soft-deleted, and they were hard-deleted in 5.7. It's the new expected behaviour i would say, but the problem is, the soft-delete is not taken into account when reading data from pivot tables, only when deleting.

It's an improvement, it can handle soft-delete now, but it's not working fully, since soft-deleted records still appear. I think that the SoftDeletetingScope is not applied to pivot models

### Steps To Reproduce:
1/ Delete pivot record and see that record is gone from database
2/ Add SoftDeletes Trait to pivot model
3/ Delete pivot record again and see that record is still there but soft-deleted
3/ List existing pivot record, and see that soft-deleted records still appear

Thanks.

**Comment by driesvints** [comment]
Can you please fill out the whole issue template (aka, add the patch versions for laravel that you're running)?

**Comment by lk77** [comment]
Sorry for that, it's 5.8.15,
i've updated it.

**Comment by themsaid** [comment]
I don't see how it makes sense to have SoftDeletable pivot models, does a soft deleted pivot row exists? If it's re-attached should we consider this an update or new attachement? How to differentiate between detaching (soft deleting) and another type of detaching (hard deleting)?

I think we just need to say in the docs that Pivot Modals can't be used with SoftDeletes.

**Comment by lk77** [comment]
I think it's fine if it can't be used with SoftDeletes, but it should ignore the SoftDeletes then, by hard deleting, like it does before.

**Comment by themsaid** [comment]
@lk77 you shouldn't use SoftDeletes with the model in the first place.

**Comment by lk77** [comment]
At this moment we are not using the trait anymore, since it's not working, we are setting deleted_at field manually on the pivot.

The thing is, i'm okay with the fact that the framework does not support soft-delete for pivot, but we should be able to do it ourselves, with our own implementation. The current state prevent this, since we cannot use SoftDeletes trait with pivot classes anymore.

**Comment by driesvints** [comment]
@lk77 I think it's best that in this case an issue is opened on the ideas repo if you want pivot models to support soft deletes since this was never supported in the first place. 

@themsaid it's perhaps indeed best that we add a note to the docs about this. I'll try to send in something for this.

**Comment by lk77** [comment]
@driesvints i don't want soft deletes to be supported, and i don't think it will ever be.

But it's a breaking change since SoftDeletes trait needs to be removed from all pivot classes, this needs to be on the upgrade guide, at least.

**Comment by driesvints** [comment]
@lk77 I don't see how this can be a breaking chance if you use any trait on any object wherever it can't be used. You could implement any trait in the framework on any object really and afterwards claim it "broke" something because you were using it in a way that wasn't documented.

**Comment by lk77** [comment]
For me, it's a breaking change, because the update to 5.8 change the behaviour, and code that worked before don't work anymore. And undocumented doesn't mean it can't be done.
