### ISSUE TITLE
Allow laravel to filter requests based on field types

### ISSUE THREAD

**Issue by farhankarim** [laravel/framework#28402]
So i have 300 different fields in my form generating from a database.These fields can be either a drop-down or text field which need to be saved in two different databases.
To get all the fields that are dropdown i will have to use 

`$request->input('name')`
`$request->input('email')`
`$request->input('username')`
and 100 other fields.

rather than doing that and  to filter requests based on input types

```
if(input_type==text){
save to this table
}
else if (input type==select){
save to this table
}
```

**Comment by rs-sliske** [comment]
suggestion should go on the laravel/ideas repo, issues on laravel/framework is for bug reports

for the suggestion itself, when a form is submitted, only the field name and value are sent to the server, not the input type.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
