### ISSUE TITLE
How to fix Carbon timezone after upgrading to Laravel 5.8

### ISSUE THREAD

**Issue by Xoshbin** [laravel/framework#28403]
- Laravel Version: 5.8.#
- PHP Version: 7.2.#
- Database Driver & Version: MySQL 5.7

### Description:
After upgrading to Laravel 5.8 the "created_at" field is returning a string like this

`"createdAt": "2019-05-01T16:36:25.000000Z"`

But I want to return an object like before in Laravel 5.7 like this:

`"createdAt": { "date": "2019-05-01 19:36:25.000000", "timezone_type": 3, "timezone": "Asia/Baghdad" }`

I did look around the web found nothing about it and there's nothing about it in upgrade guide too. I'm returning it from resources just like that a JSON:

```
public function toArray($request)
{
    return [
        'id' => $this->id,
        'createdAt' => $this->created_at,
    ];
}
```

**Comment by rs-sliske** [comment]
https://carbon.nesbot.com/docs/

near the bottom in section about carbon 2

**Comment by Xoshbin** [comment]
@rs-sliske I did try that it gives error:
```
Carbon::serializeUsing(function ($date) {
    return [
        'date' => $date->toDateTimeString(),
        'timezone_type' => $date->timezone_type,
        'timezone' => $date->tzName,
    ];
});
```

And:
$date = $this->created_at;
Carbon::serializeUsing(function ($date) {
    return [
        'date' => $date->toDateTimeString(),
        'timezone_type' => $date->timezone_type,
        'timezone' => $date->tzName,
    ];
});

**Comment by Xoshbin** [comment]
That's how I could solve it:

```
public function toArray($request)
{
    return [
        'id' => $this->id,
        'createdAt' => $this->created_at,
        'date' => Carbon::serializeUsing(function ($createdAt) {
            return [
                'date' => $createdAt->toDateTimeString(),
                'timezone_type' => $createdAt->timezone_type,
                'timezone' => $createdAt->tzName,
            ];
        }),
    ];
}
```
Now it returns an object like this:

```
"createdAt": {
                "date": "2019-05-01 19:36:25",
                "timezone_type": 3,
                "timezone": "Asia/Baghdad"
             },
             "date": null
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by rs-sliske** [comment]
serializeUsing is more setting config rather than a formatter.

i think it is expected that you would call that in a service provider etc, and then anywhere where you try to convert a carbon instance to json it will format it in the way you set

**Comment by MrJmpl3** [comment]
Fix! https://laravel.com/docs/5.8/eloquent-serialization#date-serialization

```php
public function boot(): void
    {
        Carbon::serializeUsing(static function ($carbon) {
            return [
                'date' => $carbon->toDateTimeString(),
                'timezone_type' => $carbon->timezone_type,
                'timezone' => $carbon->tzName,
            ];
        });
    }
```
