### ISSUE TITLE
Faker neglects locale set in the config

### ISSUE THREAD

**Issue by andrewgorpenko** [laravel/framework#28410]
- Laravel Version: latest
- PHP Version: 7.3
- Database Driver & Version: 5.7 (MySQL)

### Description:
The default Laravel installation sets the Faker's locale to 'en_US' in the config/app.php file, but Faker still uses, I believe, Latin (as Google Translator detected). As I mentioned earlier, this is a default Laravel installation, so no other library can affect the results.

### Steps To Reproduce:
Create a factory and try to fake the following fields: $faker->title and $faker->text. Both are in Latin, while the Faker's locale is set to English.

**Comment by koenhoeijmakers** [comment]
`$faker->text` and `$faker->title` return  [lorem ipsum](https://www.lipsum.com/)

**Comment by driesvints** [comment]
Heya @andrewgorpenko, please see @koenhoeijmakers's response above. This basically comes from https://github.com/fzaninotto/Faker/blob/master/src/Faker/Provider/Lorem.php
