### ISSUE TITLE
loadCount attributes on collection lost on access

### ISSUE THREAD

**Issue by kalynrobinson** [laravel/framework#28425]
- Laravel Version: 5.8.14
- PHP Version: 7.1.3
- Database Driver & Version:

### Description:
Lazy-loading a relationship's count with the new `loadCount` method echoes the expected entity with the count attribute, but accessing that attribute always yields `null`.

### Steps To Reproduce:
Assuming `Discussion` is a valid Eloquent model with a hasMany relationship to `Message`, in the `tinker` console:

```php
$discussions = Discussion::all();
$discussions->loadCount('messages');
// => echoes collection with visible `messages_count` attribute on each entity

$d = $discussions->first()
// => echoes entity with visible `messages_count` attribute
// Care\Modules\Discussions\Models\Discussion {#3092
//     discussion_id: 1,
//     slug: "neque-ex-ut-ut-id-aut-facilis-beatae-non",
//     subject: "Neque ex ut ut id aut facilis beatae non.",
//     user_id: 1,
//     team_id: 1,
//     created_at: "2019-05-06 14:27:49",
//     updated_at: "2019-05-06 14:27:49",
//     messages_count: 51,
//   }

$count = $d->messages_count
// expected value of $count is 51
// actual value is `null`

$arr = $d->toArray()
// expected value of $arr['messages_count'] is 51
// actual value is null
```

**Comment by staudenmeir** [comment]
Please post your `Discussion` model.

**Comment by devcircus** [comment]
Just performed the same steps, screenshots below, and it worked as expected:

## Get All
![image](https://user-images.githubusercontent.com/18542852/57234488-56be8b00-6fe6-11e9-8c25-99906af78e53.png)

## Load Count
![image](https://user-images.githubusercontent.com/18542852/57234539-748bf000-6fe6-11e9-9681-0b17df06fdf8.png)

## Get First
![image](https://user-images.githubusercontent.com/18542852/57234589-97b69f80-6fe6-11e9-9dbb-3f04eec0ff2b.png)

## Access count
![image](https://user-images.githubusercontent.com/18542852/57234617-abfa9c80-6fe6-11e9-9fa4-fc3b8077cf1f.png)

**Comment by kalynrobinson** [comment]
Yep, dumb user issue. Swear I tried this every which way, but maybe my Tinker session was caching something weird.

For reference,

> Please post your `Discussion` model.

Just a basic Eloquent model with a hasMany for example purposes.

```php
class Discussion extends Model
{
    protected $table = 'discussions';
    protected $primaryKey = 'discussion_id';
    protected $guarded = [];

    public function messages()
    {
        return $this->hasMany(Message::class, 'discussion_id', 'discussion_id');
    }
}
```
