### ISSUE TITLE
Authorization header seems to be not working

### ISSUE THREAD

**Issue by kandrejevs** [laravel/framework#28431]
- Laravel Version: 5.8.15
- PHP Version: 7.3.3
- Database Driver & Version: mysql 8

### Description:
Simple get and post requests work, bust if I add `Authorization: bearer ...` to my request header I get CORS errors.

### Steps To Reproduce:
Send request with Authorization header.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by kandrejevs** [comment]
@driesvints damn, I have no clue how I got here, this ticket was meant for https://github.com/barryvdh/laravel-cors . I guess 2 coffees are not enough for start of the week.
