### ISSUE TITLE
Cant Send Post Request To API Resource Route

### ISSUE THREAD

**Issue by BenQoder** [laravel/framework#28445]
- Laravel Version: 5.8.16
- PHP Version: 7.2.13
- Database Driver & Version:

### Description:
I Cannot Make A Post Request To The Resource Route. Error Says "The POST method is not supported for this route. Supported methods: GET, HEAD."

### Steps To Reproduce:
1. Fresh Laravel Installation
2. Define API nested resource routes
3. Send a post request using PostMan or Insomia

<img width="991" alt="Screenshot 2019-05-07 at 9 25 34 PM" src="https://user-images.githubusercontent.com/24754078/57331280-1ce9a380-7110-11e9-8375-cce36b7ffc76.png">
<img width="966" alt="Screenshot 2019-05-07 at 9 26 50 PM" src="https://user-images.githubusercontent.com/24754078/57331282-1ce9a380-7110-11e9-9ea5-2a3076d99a82.png">
<img width="1276" alt="Screenshot 2019-05-07 at 9 34 53 PM" src="https://user-images.githubusercontent.com/24754078/57331287-1e1ad080-7110-11e9-97ab-14e15ebf6e97.png">

**Comment by BenQoder** [comment]
Update: this only occurs when i use a form request.

**Comment by staudenmeir** [comment]
To which route are you sending the request?

**Comment by BenQoder** [comment]
Sorry I Did Not Specify. I Am Sending The Request To The Store Method

POST **http://testsite.test/api/showcase/1/comments**

**Comment by BenQoder** [comment]
Ensure you set **Accept: application/json** in your request header
Even if the error is unrelated, this solved my issue

**Comment by Steco17** [comment]
@BenQoder Hi, am getting this same error. sorry I don't understand what you mean am still new to Laravel. 

this is my form 
`<form class="form-horizontal" method="POST" action="{{url('/admin/update-pwd')}}" name="password_validate"
                                id="password_validate" novalidate="novalidate">@csrf
                                <div class="control-group">
                                    <label class="control-label">Current Password</label>
                                    <div class="controls">
                                        <input type="password" name="current_pwd" id="current_pwd" />
                                        <span id="chkPwd"></span>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label">New Password</label>
                                    <div class="controls">
                                        <input type="password" name="new_pwd" id="new_pwd" />
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label">Confirm password</label>
                                    <div class="controls">
                                        <input type="password" name="confirm_pwd" id="confirm_pwd" />
                                    </div>
                                </div>
                                <div class="form-actions">
                                    <input type="submit" value="Update Password" class="btn btn-success">
                                </div>
                            </form>
`

my Route:
`Route::group(['middleware' => ['auth']], function () {
    Route::match(['get','post'],'/admin/update-pwd','AdminController@updatePassword');
});`

controller:
`public function updatePassword(Request $request){
        echo "true"; die;
    }`
will appreciate any help thanks

**Comment by BenQoder** [comment]
@steco17, my case was different but try it like 
```php
Route::middleware([“auth”])->group(function () {
    Route::match(['get','post'],'/admin/update-pwd','AdminController@updatePassword'); 
});
```

**Comment by Steco17** [comment]
@BenQoder thanks it worked.
