### ISSUE TITLE
Date Mutators - Strange behaviour when use 'select()' with 'AS'

### ISSUE THREAD

**Issue by vlauciani** [laravel/framework#28449]
Hi all

I noticed a strange behaviour when I use **Date Mutators**.

For example I have:
```
class MyTable extends Model
{
   
}
```

```
use App\MyTable
class MyOwnModel extends Model
{
   public static function getData() {
      $query = MyTable::select(
         'name            AS  name_of_my_friend',
         'access_date     AS  last_access_date');
      );
      $query->get()
   }
}
```

The `access_date` field in the `MyTable` table is a `date` type then I want It as additional date attributes.

When:
- I set `protected $dates = ['last_access_date'];` into the **MyOwnModel** Model it doesn’t work. 
- I set `protected $dates = ['access_date'];` into the **MyTable** Model it doesn’t work. 
- I set `protected $dates = ['last_access_date'];` into the **MyTable** Model it works. 

Is this normal? My Idea is that I should use `$dates = ['last_access_date'];` into **MyOwnModel** Model (where I renamed the field) or `$dates = ['access_date'];` into **MyTable** Model (original name field).

Thank you

**Comment by staudenmeir** [comment]
That's the correct behavior.

> I set protected $dates = ['last_access_date']; into the MyOwnModel Model it doesn’t work.

The place where you execute the query (e.g. `MyOwnModel`) doesn't and shouldn't have any influence on the result. `MyTable` and `MyOwnModel` are completely separate and independent classes.

> I set protected $dates = ['access_date']; into the MyTable Model it doesn’t work.

The query result only contains a column named `last_access_date`, so the model doesn't know that the original name was `access_date`.

**Comment by vlauciani** [comment]
Ok, thank you for explanation... your point is correct but this means that I if I have more than one `MyOwnModel` with different "rename", example:
```
use App\MyTable
class MyOwnModel2 extends Model
{
   public static function getData() {
      $query = MyTable::select(
         'name            AS  name_of_my_friend2',
         'access_date     AS  last_access_date2');
      );
      $query->get()
   }
}
```
and
```
use App\MyTable
class MyOwnModel3 extends Model
{
   public static function getData() {
      $query = MyTable::select(
         'name            AS  name_of_my_friend3',
         'access_date     AS  last_access_date3');
      );
      $query->get()
   }
}
```

I need to set:
```
protected $dates = ['last_access_date', 'last_access_date2', 'last_access_date3'];
``` 
into the `MyTable` Model and this is not very intuitive.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
