### ISSUE TITLE
Routing incorrectly returns route endpoint that exists in more than one location

### ISSUE THREAD

**Issue by raulp** [laravel/framework#28457]
- Laravel Version: 5.8.13
- PHP Version: 7.3.1
- Database Driver & Version: MariaDB 10.3.14

### Description:
Routing incorrectly matches route endpoint that exists in more than one subdomain or location.

This happens when a route with the same path is defined in more than 1 location. Example: https://take.ms/ILXXb

When the routing tries to resolve the `api.domain.com/clients` route, the `Illuminate\Routing\RouteCollection@matchAgainstRoutes` fails, because of the collection->first(). https://take.ms/4xhzv. The routes collection does match both routes correctly.

I've looked in `Illuminate\Routing\Route.php@getValidators` and changing the order of the validators won't mater of course, as the problem is not that it's not matching, but it's filtered incorrectly.

I am not sure what a proper way would be here to fix it, which is why i did not opened a PR request, but a bug report, to get more feedback on the issue. I was thinking that maybe one possible solution is to add a new Validator that will validate ALL parts of the request at once, rather than 4 different validators. But again, was not sure what the best way is. I'm more than happy to provide a PR, once i know what would be the best way to handle this

Thank you

**Comment by driesvints** [comment]
I believe you need to define the rout with the subdomain first and that then both examples will work. Can you try this?

**Comment by raulp** [comment]
@driesvints thanks - silly me, i should have tested that case too. Works as expected. Seems a little bit weird though.

I guess then the only this is to update the docs with a "warning" message, in case some people use the same route path, but under different domains.

I'm not the best at writing that kind of documentation, but if you want, i can provide you a small paragraph and i can PR it. How about: "When using the same route path in more than once place in your app, you should define the routes that belong to a subdomain before all other routes."

Thanks

**Comment by driesvints** [comment]
You're always free to send in a PR for the docs, thanks!
