### ISSUE TITLE
BCC email not sent if global TO is set - is this expected? 

### ISSUE THREAD

**Issue by shez1983** [laravel/framework#28456]
- Laravel Version: 5.8.9
- PHP Version: 7.2.12 
- Database Driver & Version: MySQL 5.7

### Description:

Adding BCC or CC doesnt work (ie the extra email isnt sent) if Global TO is set?  if i turn this off then i can see duplicate emails going. 

### Steps To Reproduce:

1. Add followng to .env changing email/name to something
```
MAIL_TO_ADDRESS=email
MAIL_TO_NAME="Name"
```

2.  in config/mail add:
```
 'to' => [
        'address' => env('MAIL_TO_ADDRESS', 'hello@example.com'),
        'name' => env('MAIL_TO_NAME', 'Example'),
    ];
```

3. do a test in a route closure (or create a test Controller) 

```
Mail::to($email)
    ->cc($email2)
    ->bcc($email3)
    ->send(new OrderShipped($order));
```

**Comment by devcircus** [comment]
Yes, that is how the universal "to" works. See the snippet from the documentation below. It is meant to be used in development. 
![3C020476-DE51-4BBF-92E2-27BF98E92552](https://user-images.githubusercontent.com/18542852/57447298-64f5ec80-721c-11e9-8492-9bfd3de2187a.jpeg)

**Comment by driesvints** [comment]
See the reply above.
