### ISSUE TITLE
[5.8] Custom Validation Attributes for wildcard nesting

### ISSUE THREAD

**Issue by Yahav** [laravel/framework#28453]
- Laravel Version: 5.8
- PHP Version: 7.2

### Description:
I have an "arrayed" field: occurrences.*.end
the validation error i get is: The occurrences.1diga0nhc86jvfgraly.end field is required.
however when i'm trying to set a Custom Validation Attribute fr those fields:
`'occurrences' => [
            '*' => [
                'start ' => 'start time',
                'end ' => 'end time',
                'type ' => 'type',
                'dayOfWeekIso ' => 'day',
            ]
        ],`
This doesn't seem to work at all as i'm still getting the full nasted name.
Perhaps a better solution would be to only display the last child of a nasted element name, i can't think of any downsides or things that might go wrong with this solution.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by Yahav** [comment]
Actually, this is still pretty much relevant.
I've been trying to figure out a way to use the translations Custom Validation Attributes config to change a dot-notationed field name.

I have 10 fields named:
```
review.data.criterias.0.rank
review.data.criterias.1.rank
review.data.criterias.2.rank
...
```

Validations errors are displaying the full name so i thought i should use the Custom Validation Attributes to correct it, so first i tried the array method like so:

```
'attributes' => [
       'review' => [
            'data' => [
                'criterias' => [
                    '*' => [
                        'rank' => 'rank',
                        'name' => 'name'
                    ],
                ],
            ],
        ],
        ],
```
Didn't work, then i tried the dot-notation approach :
```
'review.data.criterias.*.rank' => 'rank',
```
Which didn't work as well, i rather doubt that Laravel haven't considered those situations but cannot find any documentation/information on this at all.

Another matter is that, consider that i have the same field name at different models sub-attribute:
```
ArticleModel: meta.description
PostModel: data.external.description
```
both should be displayed as `description` at the validation error, but now i'll have to specify the same actual name twice:
```
'meta.description' => 'Description',
'data.external.description' => 'Description',
```

Wouldn't it make more sense for Laravel to check whether a translation is available for the last string of a dot-notationed name as a fallback?

**Comment by huanes** [comment]
I've ran into the same dead-end.
Can't use wildcard(*) in the _attributes_ array as I'm using it in the _custom_ array of _lang/en/validation.php_

Following works
`
'custom' => [
        'billing_details.*' => [
            'required' => 'You must fill :attribute'
        ],
    ],
`

But neither of the following doesn't and it still returns _'billing details.address'_
`
'attributes' => [
        '*' => [
            'address' => 'address'
        ],
        '*.address' => 'address',
],
`

I don't get it why it's been simply closed and never looked upon?

**Comment by Yahav** [comment]
@driesvints this is clearly an actual issue, why is this getting closed?!

**Comment by huanes** [comment]
Hey @Yahav,

So I went and invested some time for that issue. and found **/vendor/laravel/framework/src/Illuminate/Validation/Concerns/FormatsMessages.php**

Basically there's a function called `getCustomMessageFromTranslator` that uses `getWildcardCustomMessages` for the **_custom_** array of messages.

Then there's `getAttributeFromTranslations` function that doesn't implement the same kind of code.
I simply copied and tweaked some code from the `getCustomMessageFromTranslator` so it would do the same thing and also created  `getWildcardCustomAttributes` for that as well.

```
/**
     * Get the given attribute from the attribute translations.
     *
     * @param  string  $name
     * @return string
     */
    protected function getAttributeFromTranslations($name)
    {
        if ($translatedName = Arr::get($this->translator->get('validation.attributes'), $name)) {
            return $translatedName;
        }

        // If an exact match was not found for the key, we will collapse all of these
        // attributes and loop through them and try to find a wildcard match for the
        // given key. Otherwise, we will simply return the key's value back out.
        $shortKey = preg_replace('/^validation\.attributes\./', '', $name);

        return $this->getWildcardCustomAttributes(Arr::dot(
            (array) $this->translator->get('validation.attributes')
        ), $shortKey, $name);
    }

    /**
     * Check the given attributes for a wildcard key.
     *
     * @param  array  $messages
     * @param  string  $search
     * @param  string  $default
     * @return string
     */
    protected function getWildcardCustomAttributes($attributes, $search, $default)
    {
        foreach ($attributes as $key => $attribute) {
            if ($search === $key || (Str::contains($key, ['*']) && Str::is($key, $search))) {
                return $attribute;
            }
        }

        return $default;
    }
```
Made a pull request #30525 as well, but to 6.x since they no longer make bug fixes to 5.8 I think or I don't know how all this works ... 
Hope there isn't something I missed and the solution doesn't break anything since I'm not that familiar to making changes to such a big framework, but for me it seems to work.

**Comment by Christophvh** [comment]
@driesvints This is an issue. Any change to re-open this?

**Comment by Yahav** [comment]
> It apparently does work in lang files https://laravel.com/docs/8.x/validation#specifying-attribute-in-language-files
I can confirm that this stream doesn't work in Laravel 8.x.
