### ISSUE TITLE
Updating a model issue

### ISSUE THREAD

**Issue by zeyad82** [laravel/framework#28464]
### Description:
While calling save on a model with a json attribute that not updated, it's considered as dirty and it triggers an update even though no update is needed...

I found that the issue is in originalIsEquivalent function in HasAttributes trait within the check hasCast. When casting original and current to Object, they will be always different instances therefore strict comparison will always return false even if the values are equal. 

### Steps To Reproduce:
1. Add an attribute in casts array with value object.
2. Run save on a model with the same values of object.
3. It will trigger an update and affect updated_at

**Comment by driesvints** [comment]
Can you please fill out the issue template?

**Comment by zeyad82** [comment]
What do you mean? it's with all versions!

**Comment by driesvints** [comment]
Please fill out the template with the versions you're using.

**Comment by zeyad82** [comment]
it's not relevant to a particular version!

**Comment by driesvints** [comment]
It's vital to know in which version you're experiencing the problem because code can differ between each version.

**Comment by zeyad82** [comment]
I have checked it with versions 5.5 - 5.8, it's the same no difference.

**Comment by staudenmeir** [comment]
#27946 discusses a related issue and #28029 proposed a fix for it and your issue but got rejected.
