### ISSUE TITLE
preset change method from react to js

### ISSUE THREAD

**Issue by jksdn** [laravel/framework#28461]
- Laravel Version: 5.8.16
- PHP Version: 7.3
- Database Driver & Version: -

### Description:
When set preset to react and after set back to none in the wepack.mix.js does not change method from react to js

`mix.react('resources/js/app.js', 'public/js').sass('resources/sass/app.scss', 'public/css');`

### Steps To Reproduce:
1. `php artisan preset react`
2. `php artisan preset none`

And also in laravel 5.8.16 the issue #28384 is the same

**Comment by driesvints** [comment]
Also seems to be the case for bootstrap preset. I'll send in a PR for this.

**Comment by driesvints** [comment]
Hmm, bootstrap is okay I guess since that doesn't needs to be aware of which js implementation is used.

**Comment by driesvints** [comment]
PR sent: https://github.com/laravel/framework/pull/28462

**Comment by jksdn** [comment]
OK, i'll explain the full steps

1. create a new laravel app
2. set preset to none
3. run npm install && npm run dev
4. it also pull vue-template-compiler for no reasons
5. now, let's set preset to react (in the same project)
6. run npm install && npm run dev (it seems to be ok)
7. set preset back to none
8. run npm install && npm run dev
9. it also pull @babel/preset-react for no reasons (and webpack.mix.js still point to the react compiler)

**Comment by driesvints** [comment]
@jksdn I think that's because it's in your package-lock maybe, not sure. But we can't fiddle with that I believe. Does the fix from the pr work for you?

**Comment by jksdn** [comment]
@driesvints Now it's ok, wepack.mix.js is updated after set preset to none, but the issue above from step 1 to 4 is the same

**Comment by driesvints** [comment]
@jksdn that's unrelated to Laravel and is something Mix requires: https://github.com/JeffreyWay/laravel-mix/issues/1916

**Comment by jksdn** [comment]
@driesvints Now to be more cleaner for me, the vue-template-compiler it's a package required for larave-mix or it's pulled for no reason in a project that does not require vue?
