### ISSUE TITLE
[5.8.16][Feature test] Mocking not working inside custom validation rules

### ISSUE THREAD

**Issue by lk77** [laravel/framework#28468]
- Laravel Version: 5.8.16
- PHP Version: 7.2.17
- Database Driver & Version: mysql 5.7

### Description:

Hello,

we have an issue when we feature test our application, specifically when mocking classes in the container and making a request with ->post(). 

Inside custom validation rules, the mocking does not work, aka the real class is returned by the container instead of the mocked one, defined in our tests. In the controller, the mocked class is correctly returned.

### Steps To Reproduce:

i have setup a repo to illustrate this : https://github.com/lk77/laravel-mock-issue
In this example we are trying to mock Filelink class from filestack-php

#### 1/ We need to create a test that mock a class and make a post request to our application
```
public function test_instance_mock()
{
    $random = Str::random(32);

    $this->mock(Filelink::class, function ($mock) use ($random) {
        $mock->shouldReceive('getMetaData')->andReturn(['size' => $random]);
    });

    $this->assertTrue(app(Filelink::class)->getMetaData()['size'] === $random);

    $response = $this->postJson("/file", ['random' => $random]);

    $this->assertSame('true', $response->getContent());
}
```
#### 2/ We need to add the post route we are using in our test in web.php 
`Route::post('/file', 'Controller@fileTest');`
#### 3/ We need a controller action to test that the mocking work in controller
```
public function fileTest(FileTestRequest $request)
 {
     try
     {
         $random = $request->input('random');

         $test = app(Filelink::class)->getMetaData()['size'] == $random;
     } catch (\Exception $e)
     {
         $test = false;
     }

     return response()->json($test);
 }
```
#### 4/ We need a custom request that use a custom rule
```
public function rules()
{
    return [
        'random' => [new TestContainerInstance()]
     ];
}
```
#### 5/ We need to create that custom rule and we need to test that the returned instance is not the mocked one
```
public function passes($attribute, $random)
{
    try
    {
        $random = $request->input('random');

        $test = app(Filelink::class)->getMetaData()['size'] == $random;
    } catch (\Exception $e)
    {
        $test = false;
    }

    return $test;
}
```

To test it, just clone the repo, do composer install, and run phpunit :
```
1) Tests\Feature\MockFilelinkTest::test_instance_mock
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'true'
+'{"message":"The given data was invalid.","errors":{"random":["The mocking hasn't worked"]}}'

```
this is the result returned by phpunit,
the validation is failing because in the rule we test that the instance is correcly mocked, and it's not the case 

if i replace this logic by `return true` in the passes method of the rule,
the controller action get executed,
with exactly the same logic and return `true`,
instead of `false` like in the rule.

The only way to make it work, is wrap mock in App::offsetSet
```
App::offsetSet(Filelink::class, $this->mock(Filelink::class, function ($mock) use ($random) {
            $mock->shouldReceive('getMetaData')->andReturn(['size' => $random]);
        }));
```

thanks for your help.

**Comment by driesvints** [comment]
You tagged the title with 5.8.16 but in your template you noted down 5.8.15. Which version are you using?

**Comment by lk77** [comment]
Sorry for that, it's 5.8.16.

**Comment by driesvints** [comment]
You've made a copy/paste mistake I think by adding `$random = $request->input('random');` to your validation rule. If you remove this the test passes.

**Comment by lk77** [comment]
yes, it's a mistake, it's `request()->input()` but it does not explain why we need to use App:offsetSet in our application, for the test to pass.

**Comment by lk77** [comment]
i think my issue is related to this issue :
https://github.com/laravel/framework/issues/19450

**Comment by driesvints** [comment]
You don't need the `$random = request()->input('random');` call there because `$random` is already passed with the `passes` method: `public function passes($attribute, $random)`.

**Comment by lk77** [comment]
yes, you are right, i don't need it at all.
