### ISSUE TITLE
FileNotFoundException, The file  "./." does not exist

### ISSUE THREAD

**Issue by Herjun0t** [laravel/framework#28477]
it work on my localhost, but not on live server
![fusinkhead1](https://user-images.githubusercontent.com/50481038/57513402-56045c80-7338-11e9-8597-0885b8fed3a7.jpg)

![fusinkhead](https://user-images.githubusercontent.com/50481038/57513418-60265b00-7338-11e9-8a0f-612bb64f4e70.jpg)

what should i do.?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
