### ISSUE TITLE
Default Email Template Problem [5.8.16]

### ISSUE THREAD

**Issue by TDKDEV** [laravel/framework#28479]
- Laravel Version: 5.8.16
- PHP Version: 7.3.2

I'm getting error since few hours from my current Website production. Everything seems working but for unknown reason, my verification emails still not working (Bad display).

![display](https://user-images.githubusercontent.com/12463679/57517896-1d548b00-7318-11e9-8866-38387eb3458c.png)

HTML Source received from mailtrap.io
Hastebin: https://hastebin.com/ecajerilaj.xml

`<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; box-sizing: border-box; background-color: #f8fafc; color: #74787e; height: 100%; hyphens: auto; line-height: 1.4; margin: 0; -moz-hyphens: auto; -ms-word-break: break-all; width: 100% !important; -webkit-hyphens: auto; -webkit-text-size-adjust: none; word-break: break-word;">
    <style>
        @media  only screen and (max-width: 600px) {
            .inner-body {
                width: 100% !important;
            }

            .footer {
                width: 100% !important;
            }
        }

        @media  only screen and (max-width: 500px) {
            .button {
                width: 100% !important;
            }
        }
    </style>

    <table class="wrapper" width="100%" cellpadding="0" cellspacing="0" role="presentation" style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; box-sizing: border-box; background-color: #f8fafc; margin: 0; padding: 0; width: 100%; -premailer-cellpadding: 0; -premailer-cellspacing: 0; -premailer-width: 100%;">
        <tr>
            <td align="center" style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; box-sizing: border-box;">
                <table class="content" width="100%" cellpadding="0" cellspacing="0" role="presentation" style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; box-sizing: border-box; margin: 0; padding: 0; width: 100%; -premailer-cellpadding: 0; -premailer-cellspacing: 0; -premailer-width: 100%;">
                    &lt;tr&gt;
    &lt;td class="header"&gt;
        &lt;a href="http://localhost"&gt;
            iBet
        &lt;/a&gt;
    &lt;/td&gt;
&lt;/tr&gt;

                    
                    <tr>
                        <td class="body" width="100%" cellpadding="0" cellspacing="0" style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; box-sizing: border-box; background-color: #ffffff; border-bottom: 1px solid #edeff2; border-top: 1px solid #edeff2; margin: 0; padding: 0; width: 100%; -premailer-cellpadding: 0; -premailer-cellspacing: 0; -premailer-width: 100%;">
                            <table class="inner-body" align="center" width="570" cellpadding="0" cellspacing="0" role="presentation" style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; box-sizing: border-box; background-color: #ffffff; margin: 0 auto; padding: 0; width: 570px; -premailer-cellpadding: 0; -premailer-cellspacing: 0; -premailer-width: 570px;">
                                
                                <tr>
                                    <td class="content-cell" style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; box-sizing: border-box; padding: 35px;">
                                        &lt;h1&gt;Hello!&lt;/h1&gt;
&lt;p&gt;Please click the button below to verify your email address.&lt;/p&gt;
&lt;p&gt;&amp;lt;table class=&amp;quot;action&amp;quot; align=&amp;quot;center&amp;quot; width=&amp;quot;100%&amp;quot; cellpadding=&amp;quot;0&amp;quot; cellspacing=&amp;quot;0&amp;quot; role=&amp;quot;presentation&amp;quot;&amp;gt;
&amp;lt;tr&amp;gt;
&amp;lt;td align=&amp;quot;center&amp;quot;&amp;gt;
&amp;lt;table width=&amp;quot;100%&amp;quot; border=&amp;quot;0&amp;quot; cellpadding=&amp;quot;0&amp;quot; cellspacing=&amp;quot;0&amp;quot; role=&amp;quot;presentation&amp;quot;&amp;gt;
&amp;lt;tr&amp;gt;
&amp;lt;td align=&amp;quot;center&amp;quot;&amp;gt;
&amp;lt;table border=&amp;quot;0&amp;quot; cellpadding=&amp;quot;0&amp;quot; cellspacing=&amp;quot;0&amp;quot; role=&amp;quot;presentation&amp;quot;&amp;gt;
&amp;lt;tr&amp;gt;
&amp;lt;td&amp;gt;
&amp;lt;a href=&amp;quot;&lt;a href="http://localhost:8000/email/verify/18?expires=1557484091&amp;amp;amp;amp;signature=ced8404af133efd4f7897dd7a87370cd9aa993b6b50e5e834e900128fc99a817&amp;amp;quot"&gt;http://localhost:8000/email/verify/18?expires=1557484091&amp;amp;amp;amp;signature=ced8404af133efd4f7897dd7a87370cd9aa993b6b50e5e834e900128fc99a817&amp;amp;quot&lt;/a&gt;; class=&amp;quot;button button-primary&amp;quot; target=&amp;quot;_blank&amp;quot;&amp;gt;Verify Email Address&amp;lt;/a&amp;gt;
&amp;lt;/td&amp;gt;
&amp;lt;/tr&amp;gt;
&amp;lt;/table&amp;gt;
&amp;lt;/td&amp;gt;
&amp;lt;/tr&amp;gt;
&amp;lt;/table&amp;gt;
&amp;lt;/td&amp;gt;
&amp;lt;/tr&amp;gt;
&amp;lt;/table&amp;gt;&lt;/p&gt;
&lt;p&gt;If you did not create an account, no further action is required.&lt;/p&gt;
&lt;p&gt;Regards,&amp;lt;br&amp;gt;iBet&lt;/p&gt;

                                        &lt;table class="subcopy" width="100%" cellpadding="0" cellspacing="0" role="presentation"&gt;
    &lt;tr&gt;
        &lt;td&gt;
            &amp;lt;p&amp;gt;If youÃÂ¢ÃÂÃÂre having trouble clicking the &amp;amp;quot;Verify Email Address&amp;amp;quot; button, copy and paste the URL below
into your web browser: &amp;lt;a href=&amp;quot;http://localhost:8000/email/verify/18?expires=1557484091&amp;amp;amp;amp;signature=ced8404af133efd4f7897dd7a87370cd9aa993b6b50e5e834e900128fc99a817&amp;quot;&amp;gt;http://localhost:8000/email/verify/18?expires=1557484091&amp;amp;amp;signature=ced8404af133efd4f7897dd7a87370cd9aa993b6b50e5e834e900128fc99a817&amp;lt;/a&amp;gt;&amp;lt;/p&amp;gt;
        &lt;/td&gt;
    &lt;/tr&gt;
&lt;/table&gt;
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>

                    &lt;tr&gt;
    &lt;td&gt;
        &lt;table class="footer" align="center" width="570" cellpadding="0" cellspacing="0" role="presentation"&gt;
            &lt;tr&gt;
                &lt;td class="content-cell" align="center"&gt;
                    &amp;lt;p&amp;gt;ÃÂ© 2019 iBet. All rights reserved.&amp;lt;/p&amp;gt;
                &lt;/td&gt;
            &lt;/tr&gt;
        &lt;/table&gt;
    &lt;/td&gt;
&lt;/tr&gt;
                </table>
            </td>
        </tr>
    </table>
</body>
</html>`

I'm not sure of why that happend but i haven't changed anything

Regards

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
