### ISSUE TITLE
withCount(), having() and paginate() together not working

### ISSUE THREAD

**Issue by manektechmayank** [laravel/framework#28476]
- Laravel Version: 5.7.21#.#.#
- PHP Version: 7.1.12#.#.#
- Database Driver & Version: phpMyAdmin Version : 4.7.4

### Description:
I am developing a application in which I have to put condition on count column by using having() function but it's not working. While same query working in mySql with same version. 

`lluminate\Database\QueryException: SQLSTATE[42S22]: Column not found: 1054 Unknown column &#039;upvotes_count&#039; in &#039;having clause&#039; (SQL: select count(*) as aggregate from `post` having `upvotes_count` = 1) in file D:\xampp\htdocs\hubl\vendor\laravel\framework\src\Illuminate\Database\Connection.php on line 664`

### Steps To Reproduce:

**1) Not Working**

$posts = Post::withCount('upvotes')
->having('upvotes_count', '>', 5)
->paginate(6);

**2) This will work**

$posts = Post::withCount('upvotes')
->having('upvotes_count', '>', 5)
->get();

**Comment by manektechyagnik** [comment]
Yeah the Same issue happens with me. 
Please do some needful action.

**Comment by staudenmeir** [comment]
This is a long-standing issue and not trivial to fix. Have you looked at the various workarounds?

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look and re-open this issue.

Thanks!

**Comment by AntonyForber** [comment]
Same problem. Upgrading to 5.8 did not help

**Comment by avictory6** [comment]
This problem still persist with Laravel Framework 5.8.21

**Comment by adampk90** [comment]
Can we reopen this? Encountering the same bug using 5.8.35

**Comment by dkulyk** [comment]
`having` wont work on aggregated selects properly. If you want to filter you need to use `where`
```php
Post::query()
    ->withCount([
        'upvotes' => function (Builder $builder) use (&$query) {
            $query = $builder;
        },
    ])
    ->setBindings($query->getBindings(), 'where')
    ->whereRaw("({$query->toSql()}) > ?", 1)
    ->paginate(5);
```

**Comment by adampk90** [comment]
@dkulyk nice workaround, thanks!

**Comment by ProteanCode** [comment]
While workaround exists the bug is still not fixed

**Comment by Xatta-Trone** [comment]
Has the issue not been solved yet? using laravel 9.* and the problem still exists.

**Comment by juanparati** [comment]
withCount() works perfectly for me when I use having instead for where.
