### ISSUE TITLE
Csrf 

### ISSUE THREAD

**Issue by Mahdi-Ba** [laravel/framework#28482]
I'm using axius to send post form in route web.php and use middleware web so I dont pass any x-csrf and csrf any where But send success but when use simple html 5 response error expired appear,I'm think dont work csrf in axius or ajax 
Laravel vesrion 5.8.*

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by Mahdi-Ba** [comment]
this is a bug @driesvints there isn`t any csrf and x-csrf  axius Post Method working without any error
