### ISSUE TITLE
Query builder from a relationship should always scope the query

### ISSUE THREAD

**Issue by stancl** [laravel/framework#28486]
- Laravel Version: 5.8.14
- PHP Version: 7.2.17
- Database Driver & Version: sqlite 3.22

### Description:

I have the following query:

```php
return auth()->user()->tasks()
        ->select(['id', 'text', 'points', 'type', 'completed'])
        ->whereDate('date', $date)->orWhere(function ($query) use ($date) {
            $query->whereDate('date', '<', $date)->where('completed', false);
        })->get();
```

This query is expected to return the authenticated user's tasks that have not been completed or are due today.

However, the `orWhere()` condition is applied on the same level as the `where "tasks"."user_id" = 5`.

In my opinion, such queries should *always* be scoped as per the relationship, regardless of any `orWhere()` queries. The first line of the query says "the authenticated user's tasks", so the developer should not have to worry about the rest of the query breaking that condition.

A solution is to wrap all of the `where` conditions in a pair of brackets.

This query works as expected:

```php
return auth()->user()->tasks()
        ->select(['id', 'text', 'points', 'type', 'completed'])
        ->where(function ($query) use ($date) {
            $query->whereDate('date', $date)->orWhere(function ($query) use ($date) {
                $query->whereDate('date', '<', $date)->where('completed', false);
            });
        })->get();
```

Here are the queries in SQL:

<details>
<summary>The original query</summary>

```sql
select
  "id",
  "text",
  "points",
  "type",
  "completed"
from
  "tasks"
where
  "tasks"."user_id" = 5
  and "tasks"."user_id" is not null
  and strftime('%Y-%m-%d', "date") = cast("2019-05-11" as text)
  or (
    strftime('%Y-%m-%d', "date") < cast("2019-05-11" as text)
    and "completed" = 0
  )
```

</details>

<details>
<summary>The modified query</summary>

```sql
select
  "id",
  "text",
  "points",
  "type",
  "completed"
from
  "tasks"
where
  "tasks"."user_id" = 5
  and "tasks"."user_id" is not null
  and (
    strftime('%Y-%m-%d', "date") = cast("2019-05-11" as text)
    or (
      strftime('%Y-%m-%d', "date") < cast("2019-05-11" as text)
      and "completed" = 0
    )
  )
```

</details>

**Comment by staudenmeir** [comment]
Please see #28207 why this is the expected behavior and a complicated issue.

**Comment by stancl** [comment]
Wrapping all wheres in a `where()` closure does fix this, though I see how fixing it could break constraints that come with a relationship

```php
public function notes()
{
    return $this->hasMany(Note::class)
        ->where('type', 'private')->orWhere('type', 'hidden');
}
```

I didn't find why this is the expected behavior in that thread though. The fact that fixing this could be hard doesn't mean it's the expected behavior.

Having a separate method for `where` inside a relationship could solve the issue with relationships. Or perhaps something like

```php
public function notes()
{
    return $this->hasMany(App\Note::class)->filteredBy(function ($query) {
        $query->where('foo', 'bar');
    }
}
```

Obviously with a better name.

**Comment by stancl** [comment]
I think that the solution should work like this:

```php
public function notes()
{
    return $this->hasMany(App\Note::class)->where('type', 'private);
}
```

```php
auth()->user()->notes()->where('foo', 'bar')->orWhere('x', 'y');
```

The resulting SQL:

```sql
select
  *
from
  "notes"
where
  (
    "notes"."user_id" = 5
    and "notes"."user_id" is not null
    and "notes"."type" = "private"
  )
  and 
  (
    "notes.foo" = "bar"
    or "notes.x" = "y"
  )
```

The relationship scope ("tasks.user_id" = 5) would be in the same group of brackets as the wheres in the `public function notes()`. A step further, that's probably unnecessary, would be to put the relationship scope in one pair of brackets, the relationship wheres in a second pair and the other wheres in a third pair. This would make sure that you can't break the relationship scope even in the `public function notes()`.

**Comment by staudenmeir** [comment]
Why this is expected behavior (IMO): When adding a `where()->orWhere()` clause to a query, you should always wrap it in a closure. If the query has any additional constraints before or after it, the query breaks.

**Comment by stancl** [comment]
> When adding a where()->orWhere() clause to a query, you should always wrap it in a closure. If the query has any additional constraints before or after it, the query breaks.

You don't see any other wheres when you do this:

```php
auth()->user()->tasks()->where('completed', false)->orWhereDate('date', '<', date('Y-m-d'))
```

The first part of the call says "the authenticated user's tasks". There should be no way to break the promise of getting *only* the authenticated user's tasks.

You shouldn't have to worry about what the framework does in the background. You shouldn't have to think "right, `auth()->user()->tasks` returns a `HasMany` relation which has a query builder with a `where` clause". You ask for the current user's tasks, and you should get them.

The code above is expressive, the code below is not.

```php
auth()->user()->tasks()->where(function ($query) {
    $query->where('completed', false)->orWhereDate('date', '<', date('Y-m-d'))
});
```

Anyone who hasn't experienced this problem recently won't understand why there's a where closure and might think "I can refactor this, I'll remove the where closure".

**Comment by driesvints** [comment]
As noted by @staudenmeir and numerous other issues on this repo this is currently the expected behavior. If you wish to see this changed please open up an issue on the ideas repo to get support for your idea. Then perhaps attempt a PR after that.

**Comment by stancl** [comment]
I see that the solution is probably not worth the trade-offs. @driesvints what do you think about a PR to the docs repo adding a notice that there might be unexpected behavior when using `orWhere` with relationships?

**Comment by driesvints** [comment]
@stancl you can always try to see if it gets accepted by Taylor/
