### ISSUE TITLE
[5.8] Custom column collations are ignored when changing a column in a migration.

### ISSUE THREAD

**Issue by JacksonIV** [laravel/framework#28487]
- Laravel Version: 5.8.16
- PHP Version: 7.3
- Database Driver & Version: MySQL 5.7

### Description:

Setting a custom column collation in conjunction with the `->change()` method in a migration doesn't work. The framework completely ignores the `->collation('')` method, because there is not such thing as a "setCollation" option in Doctrine DBAL. 

https://github.com/laravel/framework/blob/b4c0ef18e7c27bcbe125d5a3750e642544f7436d/src/Illuminate/Database/Schema/Grammars/ChangeColumn.php#L83

The collation can be set though by using the `setCustomSchemaOption` on Doctrine's column builder:

https://www.doctrine-project.org/projects/doctrine-dbal/en/2.9/reference/schema-representation.html#vendor-specific-options

### Steps To Reproduce:

Create a new migration:

```php
        Schema::create('tests', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('test_column');
        });
```

And create another one:

```php
        Schema::table('tests', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->integer('test_column')->collation('')->change();
        });
```

### Proposed change:

Before i create a pull request, i'd like to hear your thoughts on this:

https://github.com/JacksonIV/framework/blob/37c3a6decc9c6dc5f47dff0105b3c533bd7ac786/src/Illuminate/Database/Schema/Grammars/ChangeColumn.php#L83-L88

**Comment by driesvints** [comment]
If Doctrine doesn't offers this then isn't this more of a feature request than a bug to support it? It doesn't explicitly say in the docs that we support this (although I can understand that it's a bit confusing).

**Comment by JacksonIV** [comment]
@driesvints Doctrine does support it, please refer to https://www.doctrine-project.org/projects/doctrine-dbal/en/2.9/reference/schema-representation.html#vendor-specific-options.

**Comment by driesvints** [comment]
Okay, feel free to send in a PR with a fix if you have something.

**Comment by driesvints** [comment]
PR merged
