### ISSUE TITLE
[QQ] Facade annotation generation

### ISSUE THREAD

**Issue by CupOfTea696** [laravel/framework#28497]
Quick question, is there a tool to automatically generate the `@method` tags for Facades? If there is, can someone point me towards where I can find it? This would be super useful for annotating facades in my own application.

**Comment by staudenmeir** [comment]
You could take a look at the implementation of https://github.com/barryvdh/laravel-ide-helper.

**Comment by CupOfTea696** [comment]
Yeah, but that generates actual classes and methods. I want to create just the annotations, in the same way Laravel Facades have them, without having to create them manually.

**Comment by staudenmeir** [comment]
The package also creates `@method` tags: https://github.com/barryvdh/laravel-ide-helper/blob/master/src/Console/ModelsCommand.php#L671

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
