### ISSUE TITLE
Date fields in SQL database are returned as invalid date string in Laravel

### ISSUE THREAD

**Issue by robinnydahl** [laravel/framework#28491]
- Laravel Version: 5.8.16
- PHP Version: 7.3.5
- Database Driver & Version: MSSQL / Microsoft SQL Server 2016 - 13.0.5292.0

### Description:
When we fetch dates either from direct DB statement or Eloquent we get the `date` field in the SQL database returned as an invalid formatted date string like `Sep 12 2018 12:00:00:AM`.

First of all, the last `:` before `AM` results in Carbon giving an exception as it's an invalid date format. With that removed Carbon can recognize the date again.

However we can't seem to figure out why Laravel formats this date in the first place. We have no  models for the given table (no dates are mutated) and the date is stored as `YYYY-MM-DD` in the database.

An example DB statement is `DB::connection('database')->table('table')->get()`

We've tested this with MySQL, the problem is not present there. Once we switch back to MSSQL the issue returned.

### Steps To Reproduce:
1. Fetch a record from the database where a field with type `date` is present.
2. The returned record is formatted invalid with `Sep 12 2018 12:00:00:AM`, should be `2018-09-12`.

**Comment by laurencei** [comment]
> We've tested this with MySQL, the problem is not present there. Once we switch back to MSSQL the issue returned.

I use MSSQL and I've not seen this problem. It's something with your database configuration or setup.

Laravel does not cast the datetime of the records unless you asked it to in Eloquent, and it definetely does not do it in a `DB` statement.

**Comment by robinnydahl** [comment]
Hey @laurencei.

Thanks for the quick response. I'll close this for now to investigate.

**Comment by kokoshneta** [comment]
@robinnydahl Did you ever find out what was causing this, or if there’s a way to fix it? I’m having the same problem (see mention just above this comment), also only in SQL Server and only when fetching through Laravel (i.e., not if using a native PDO connection).
