### ISSUE TITLE
Access Denied for user robin@localhost (using password: YES)

### ISSUE THREAD

**Issue by robbietorinit** [laravel/framework#28509]
- Laravel Version: 5.8
- PHP Version: 7.0
- Database Driver & Version:  MySQL & 5.7

### Description:
When I set the correct credentials in .env file for database and clear the cache using php artisan config:cache , and then try to run a script. It says access denied.

Whereas when I try to connect to mysql using terminal by running sudo mysql -u root -p it gets me connected with the same password. and also if i try to run a core php script to check database connection. it works.

BUT NOT WITH LARAVEL.

It is a fresh laravel setup.

**Comment by svenluijten** [comment]
The error you're getting (if I were to believe the title of the issue) indicates that you're trying to log in with `robin` as username. You mention it works when  you log in with `sudo mysql -u root -p`, which is using the `root` user. Try putting `root` as `DB_USERNAME` in your `.env` file.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by driesvints** [comment]
Btw, this issue isn't locked so feel free to discuss further here as well if you wish.

**Comment by robbietorinit** [comment]
@svenluijten : even if i do sudo mysql -u robin -p it gets me connected with the password, but not with laravel.

**Comment by robbietorinit** [comment]
Could you please help at the earliest?

**Comment by svenluijten** [comment]
@robbietorinit as mentioned already, it's probably best to ask in the Laracasts forum (linked above) or other places Dries linked.

**Comment by josimarcamilo** [comment]
Mudei de DB_HOST=localhost para DB_HOST=127.0.0.1 e funcionou aqui.
