### ISSUE TITLE
Artisan migrate omits last migration record in migrations table when auto commit is disabled on MySQL server/connection

### ISSUE THREAD

**Issue by Erutan409** [laravel/framework#28503]
- Laravel Version: 5.7.28
- PHP Version: 7.2.5
- Database Driver & Version: PDO Driver for MySQL => enabled
Client API version => mysqlnd 5.0.12-dev

### Description:
Artisan migrate omits last migration record in migrations table when auto commit is disabled on MySQL server/connection.

### Steps To Reproduce:
Run migrations for Laravel app after turning off auto-commit on the server.

**Comment by staudenmeir** [comment]
Why are you disabling `autocommit`?

**Comment by Erutan409** [comment]
@staudenmeir why does it matter in context to this issue?

**Comment by staudenmeir** [comment]
I'm asking because disabling `autocommit` is quite unusual and affects every query in Laravel, not just migrations.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look and re-open this issue.

Thanks!

**Comment by Erutan409** [comment]
@staudenmeir Ah, I see.  Without being intimately familiar with how a lot of the framework works with queries, it looks like there was some detection of transactions in the migrator.

Should I infer from your response, though, that this isn't an issue and the fix is to use Laravel in an environment with auto-commit enabled?

**Comment by Erutan409** [comment]
@driesvints I'll give it a go and report back.

**Comment by staudenmeir** [comment]
Migrations only use transactions on databases that support DDL transactions, which MySQL does not.

This is not a Laravel issue, but the intended behavior of `autocommit`. If you disable it, all uncommitted DML queries are rolled back when the connection is closed. You have to commit them manually to prevent that:

```php
User::create();

DB::commit();
```

In your case, you would have to put `DB::commit();` in the last migration.

Is there a particular reason you've disabled `autocommit`?

**Comment by Erutan409** [comment]
@staudenmeir this was a personal choice for various reasons, but it wasn't something that needed to be set in stone.  Either way, this is good to know about Laravel.

Thank you
