### ISSUE TITLE
laravel locale setting dose't change php's  locale information?

### ISSUE THREAD

**Issue by xiatian** [laravel/framework#28505]
I think it's necessary to support it.

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!
