### ISSUE TITLE
[Lumen 5.8.4] string escape sequences are parsed when logging Exceptions

### ISSUE THREAD

**Issue by HenkPoley** [laravel/framework#28508]
- Laravel Lumen Version: 5.8.4
- PHP Version: 7.2.17
- Database Driver & Version:

### Description:

In storage/logs/lumen-*.log I sometimes see:

```
#17 {main} {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method Laravel\\Lumen\\Routing\\Router::middleware() at C:\\{path_to_my_project}\
outes\\web.php:33)
```

Note that the last line shouldn't be on a new line (carriage return), and that part should have read "\routes". The '\r' is interpreted as a carriage return.

In the '[stacktrace]' that follows, the string escape characters also interpreted.

### Steps To Reproduce:
Run your Lumen website on Windows, so your paths have backslashes.

This specific one, do a call to an undefined method within `routes\web.php`:

```php
$router->get('/', function () use ($router) {
    // Dummy greeting
    return env('APP_NAME');
})->middleware('foobar');
````

You probably also need these in `.env` to get full debug going 🤷‍♂️
```ini
APP_ENV=local
APP_DEBUG=true
LOG_CHANNEL=stack
```

(I don't need help with wiring the middleware to the routes the proper way, I figured that out)

**Comment by driesvints** [comment]
Can you please open up this issue on the Lumen issue tracker? Thanks.

https://github.com/laravel/lumen-framework

**Comment by HenkPoley** [comment]
Okay: https://github.com/laravel/lumen-framework/issues/914
