### ISSUE TITLE
withErrors() on a view should be a ViewErrorBag?

### ISSUE THREAD

**Issue by royduin** [laravel/framework#28526]
I'm using for example `$errors->hasBag('contact')` in my views to determine where the errors are coming from. This works because when the validation fails from a `FormRequest`; `$errors` will be a `ViewErrorBag`. But when I do the validation in my controller and pass the errors through the view with `withErrors()` I'm getting:
```
Call to undefined method Illuminate\Support\MessageBag::hasBag() 
```
Because it's a `MessageBag` instead of a `ViewErrorBag`.

Example:
```php
$validator = Validator::make($something, [
    'something' => 'rules',
]);

return view('view')->withErrors($validator);
```

So for now I'm using:
```php
return view('view')->with(
    'errors',
    (new ViewErrorBag)->put('default', $validator->getMessageBag())
);
```

I think [`withErrors()` from the view](https://github.com/laravel/framework/blob/5.8/src/Illuminate/View/View.php#L214) should act like [`withErrors()` from the RedirectResponse](https://github.com/laravel/framework/blob/5.8/src/Illuminate/Http/RedirectResponse.php#L131) right?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by royduin** [comment]
Wow, that's fast but I really think this is a bug...

**Comment by driesvints** [comment]
@royduin can you first try one of the channels from above? If you're sure it's a bug feel free to respond.

**Comment by GertjanRoke** [comment]
@driesvints I really think it should change to a function where you can override or modify the `ViewErrorBag`.

I also took a look at the links you send and went and search on it for `withErrors` and there are more people that ran into this expected functionality but came to discover that it doesn't work that way.

Here are some search results of people not understanding why this isn't working:
- https://laracasts.com/discuss?q=withErrors (19 topics)
- https://laravel.io/forum?search=withErrors (±240 topics)
- https://stackoverflow.com/search?q=%5Blaravel%5D+withErrors (2,061 results)

And they probably are not all about the `withErrors`, but seeing topics being creating for it over multiple years probably means that the functionality needs to be changed.
But if the topic is about the `withErrors` function they all think it works in a way @royduin explained

**Comment by driesvints** [comment]
I see that but I don't consider this a bug, just the way it currently works. This looks like an improvement though. Please open up an issue on the laravel/ideas repo and feel free to attempt a PR if you want.
