### ISSUE TITLE
Adding unique to a string changes sorting of table

### ISSUE THREAD

**Issue by JillevdW** [laravel/framework#28525]
- Laravel Version: 5.8.0
- PHP Version: 7.1.3
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.7.20, for osx10.13 (x86_64)

### Description:

I created a simple table that has an id (bigIncrements) and a unique string. When I insert rows into the table, they are automatically sorted by the string instead of the id. The order of items returned by the `::all()` method on the model also returns the items in this invalid order.

### Steps To Reproduce:

Create a new migration for the table:
```
Schema::create('app_metrics', function (Blueprint $table) {
    $table->bigIncrements('id');
    $table->string('name')->unique();
});
```

Now insert some rows into your database. You'll observe that they are sorted alphabetically based on the 'name' column.

**Comment by staudenmeir** [comment]
Please see https://dba.stackexchange.com/a/6053.

**Comment by JillevdW** [comment]
@staudenmeir is there a concrete reason why everything works fine if the `unique()` rule is left from the migration? I have never had to specifically add an order by clause to make it order by the id.

**Comment by staudenmeir** [comment]
I guess the `UNIQUE` index changes the way MySQL stores/queries the data internally.

**Comment by driesvints** [comment]
I feel that this is unrelated to Laravel itself like @staudenmeir explained.
