### ISSUE TITLE
Ability to use Query Scopes with Request validation Rule

### ISSUE THREAD

**Issue by amovsisyan** [laravel/framework#28529]
Hi,
I know that scopes (at least for now) used for models, but what if they can also be used with Validation Rule.

At least for Rule::exists and Rule::unique as we use other query builders (where, whereHas ...) with Rule.

F.e. Rule::exists('users', 'id')->active();

**Comment by staudenmeir** [comment]
Please use https://github.com/laravel/ideas/issues for proposals.
