### ISSUE TITLE
Sessions migration creation not using table name assigned in config/session.php

### ISSUE THREAD

**Issue by swerwajod** [laravel/framework#28531]
- Laravel Version: 5.8.16
- PHP Version: 7.2.10
- Database Driver & Version: MySQL 5.5.42

### Description:
When running ``` php artisan session:table ``` , the Migration is created with the default name 'sessions' and does not used the table name assigned in the config/session.php file.
Of course I just changed the migration file to what I wanted as a work around.

### Steps To Reproduce:
1. Change Session tale name on line ~88 of config/session.php file
2. Run ``` php artisan session:table ```

**Comment by driesvints** [comment]
This is indeed hardcoded in the stub here: https://github.com/laravel/framework/blob/5.8/src/Illuminate/Session/Console/stubs/database.stub#L16

You can just change the migration file to your own custom table name.

**Comment by swerwajod** [comment]
Indeed.  If that is the solution then the documentation should be changed.  The config/session.php file text reads as follows.
```
    /*
    |--------------------------------------------------------------------------
    | Session Database Table
    |--------------------------------------------------------------------------
    |
    | When using the "database" session driver, you may specify the table we
    | should use to manage the sessions. Of course, a sensible default is
    | provided for you; however, you are free to change this as needed.
    |
    */

    'table' => 'sys_sessions',
```
So unlike queue.php whose names are used in migration creation, session.php does not.  This documentation should then reflect that this name change assignment is only for session functions and not the migration creation as it works in other configs.

**Comment by driesvints** [comment]
I see. We could improve the `SessionTableCommand` perhaps. But that's an improvement more and not a bug. You're free to send in a PR if you want.
