### ISSUE TITLE
Redis Cache doesn't maintain original type when returns the result

### ISSUE THREAD

**Issue by calexandrepcjr** [laravel/framework#28544]
- Laravel Version: 5.7.28
- PHP Version: 7.1.3

### Description:
When I put `declare(strict_types = 1);` in my scripts, all functions expecting the proper cached types breaks when using Redis cache, though Array/File cache works well.

### Steps To Reproduce:
- Put `declare(strict_types = 1);` in the begin of your script;
- Create a function that expects and returns integer;
- Create another function that caches your prior function, expecting and returning integer;
- See that with Array Driver everything goes well, Redis Driver brings every result as string (due the redis api that only returns strings);

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists?

Thanks!
