### ISSUE TITLE
"object_get" helper missing from documentation. 

### ISSUE THREAD

**Issue by bayareawebpro** [laravel/framework#28545]
There isn't a way to open an issue on the documentation repo, and I just wanted to ask: 

1) Is this helper undocumented for a reason? (been available since 4.2)
2) Would you recommend I submit a pull request (on the docs repo) to include it?

Thank you in advance for your valuable time digesting this request.

**Comment by laurencei** [comment]
@bayareawebpro - go ahead and create a PR there for the docs.

Taylor can review your PR and he'll let you know. But generally we want to document most functionality.
