### ISSUE TITLE
Should migrations lock the database to allow concurrency?

### ISSUE THREAD

**Issue by namelivia** [laravel/framework#28548]
I've noticed that when executing migrations concurrently e.g. `php artisan migrate &; php artisan migrate` one of them will fail if there is an operation like creating a table or inserting a unique ID.
This is causing some trouble when running our applications on a multi-instance setup were all  instances run the same deployment script for creating caches, etc... and finally executing a migrate on the same database, sometimes these migrations seem to overlap and some instances will report the deployment as failed.

I know there are three ways to avoid this issue, one is dealing with it on the migrations, always checking if a unique value is present, or a table exists before inserting.
The other is dealing with it on the cloud, and just running the migrations from one machine.
The third one would be allowing the framework to execute concurrent migrations safely.

I've checked how other frameworks similar to Laravel deal with this problem to determine which of these three options is the better solution, and I've found [this issue on rails](https://github.com/rails/rails/issues/22092) discussing the same thing, and they ended up merging this code for using advisory locks to allow concurrent migrations.

Do you think this behavior is desirable and candidate to be implemented?

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not for ideas, suggestions etc. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. You are able to open a ticket at https://github.com/laravel/ideas

Alternatively you are able to open a PR using the Contributions guidelines: https://laravel.com/docs/5.7/contributions#which-branch

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.

**Comment by namelivia** [comment]
I've opened the issue there. Sorry for the inconvenience!
