### ISSUE TITLE
whereDoesntHave closure returns data when it shouldn't

### ISSUE THREAD

**Issue by nandi95** [laravel/framework#28553]
- Laravel Version: 5.8.17
- PHP Version: 7.3.0
- Database Driver & Version: 10.1.37-MariaDB

### Description:
The whereDoesntHave returns the (poll) model even though one of the relating model  (votes) is by the $this->user_id (aka constraint should fail) but if I only have ->whereDoesntHave('votes') it returns nothing as expected (as in this example this poll has 2 votes against this).
However if I extract the whereDoesntHave into a scope it works as expected eg.:
```
public function scopeUserNotVoted(Builder $query, $id)
    {
        return $query->whereDoesntHave('votes', function ($votesQuery) use ($id) {
            return $votesQuery->where('user_id', $id);
        });
    }
```
Edit: wrapping the whereDoesntHave in a where() does not help either.
Edit2: reportedly the same occurs with whereHas although I did not try it myself.

### Steps To Reproduce:
In the database I have polls, poll_options and poll_votes tables.
On my Poll model I have a hasMany relationship for votes (poll_votes)
I have one poll with 2 votes one by the current user, one by someone else

The following function is on the User model
``` 
public function pollsUnanswered()
    {
        return Poll::where(function ($genderQuery) {
            return $genderQuery->where('gender', $this->gender)->orWhereNull('gender');
        })
            ->where(function ($userCategoryQuery) {
                return $userCategoryQuery->where('user_category_id', $this->user_category_id)->orWhereNull('user_category_id');
            })
            ->where(function ($expiryQuery) {
                return $expiryQuery->where('expires_at', '>', now())->orWhereNull('expires_at');
            })->whereDoesntHave('votes', function ($votesQuery) {
                return $votesQuery->where('user_id', $this->id);
            });
    }
```
Instead of whereDoesntHave using the scope   ->userNotVoted($this->id) works as expected.

**Comment by staudenmeir** [comment]
Please provide a minimal example with migrations, sample data, relationships and query.

**Comment by nandi95** [comment]
polls migration:
```
Schema::create('polls', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->timestamps();
        });
```
poll_votes migration:
```
Schema::create('poll_votes', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->unsignedBigInteger('poll_id');
            $table->foreign('poll_id')->references('id')->on('polls');
            $table->unsignedBigInteger('user_id');
            $table->foreign('user_id')->references('id')->on('users');
            $table->timestamps();
        });
```
users migration:
```
Schema::create('users', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('email', 100)->unique();
            $table->timestamp('email_verified_at')->nullable();
            $table->string('password');
            $table->rememberToken();
            $table->timestamps();
        });
```
eloquent builder:
```
auth()->user()->pollsUnanswered()->get();
```
pollsUnanswered() method on the user model:
```
public function pollsUnanswered()
    {
        return Poll::where(function ($genderQuery) {
            return $genderQuery->where('gender', $this->gender)->orWhereNull('gender');
        })
            ->where(function ($userCategoryQuery) {
                return $userCategoryQuery->where('user_category_id', $this->user_category_id)->orWhereNull('user_category_id');
            })
            ->where(function ($expiryQuery) {
                return $expiryQuery->where('expires_at', '>', now())->orWhereNull('expires_at');
            })
            ->whereDoesntHave('votes', function ($votesQuery) {
                return $votesQuery->where('user_id');
            });
    }
```
votes relationship on the poll model
```
public function votes()
    {
        return $this->hasMany(PollVote::class);
    }
```
whereDoesntHave wrapped in a scope:
```
public function scopeUserNotVoted(Builder $query, $id)
    {
        return $query->whereDoesntHave('votes', function ($votesQuery) use ($id) {
            return $votesQuery->where('user_id', $id);
        });
    }
```
user factory:
```
$factory->define(User::class, function (Faker $faker) {
    return [
        'name' => $faker->name,
        'email' => $faker->unique()->safeEmail,
        'email_verified_at' => now(),
        'password' => '$2y$10$TKh8H1.PfQx37YgCzwiKb.KjNyWgaHb9cbcoQgdIVFlYg7B77UdFm', // secret
        'remember_token' => Str::random(10),
    ];
});
```
poll factory:
```
$factory->define(Poll::class, function (Faker $faker) {
    return [];
});
```
poll votes factory:
```
$factory->define(PollVote::class, function (Faker $faker) {
    return [
        'poll_id' => insert previously created poll.id,
        'user_id' => insert previously created user.id
    ];
});
```

**Comment by staudenmeir** [comment]
Have you looked at the executed queries? Is there a difference between scope and no scope?

**Comment by nandi95** [comment]
No difference at all. On both the toSql and getBindings are the same.

**Comment by staudenmeir** [comment]
Then this is an issue with your application and not related to Laravel.

**Comment by nandi95** [comment]
How so?

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

This issue is also not locked and everyone is still free to discuss solutions to your problem!

Thanks!
