### ISSUE TITLE
Str.php pluralStudly() providing wrong plural form in some cases

### ISSUE THREAD

**Issue by scybulski** [laravel/framework#28550]
- Laravel Version: 5.8.17
- PHP Version: 7.3.5-1
- Database Driver & Version:

### Description:
We have a model called `class PersonalProtectiveEquipment` which is bound with table `personal_protective_equipments`. In Laravel 5.7 the name of model used to be correctly converted but from 5.8 Laravel converts it remains `personal_protective_equipment` which generates errors in our application. To solve it we had to add `protected $table = 'personal_protective_equipments';` to model. 

I suspect this PR is relevant to this issue https://github.com/laravel/framework/pull/26421

### Steps To Reproduce:
I've added another test to `SupportPluralizerTest.php`:
```    public function testPluralPersonalProtectiveEquipement()
    {
        $this->assertPluralStudly('PersonalProtectiveEquipment', 'PersonalProtectiveEquipment', 1);
        $this->assertPluralStudly('PersonalProtectiveEquipments', 'PersonalProtectiveEquipment', 2);
        $this->assertPluralStudly('PersonalProtectiveEquipment', 'PersonalProtectiveEquipment', -1);
        $this->assertPluralStudly('PersonalProtectiveEquipments', 'PersonalProtectiveEquipment', -2);
    }```

which fails. 

```phpunit --filter SupportPluralizerTest```

**Comment by CupOfTea696** [comment]
That's because the word [equipment](http://learnersdictionary.com/qa/equipments-equipment-noncount-mass-noun-singular-plural) is noncount noun, and has no plural form.

**Comment by SjorsO** [comment]
This change is documented in the upgrade guide: https://laravel.com/docs/5.8/upgrade#model-names-ending-with-irregular-plurals

**Comment by scybulski** [comment]
OK, thank you for quick answer. Have a nice day!

**Comment by Kiba86** [comment]
Str::pluralStudly('Travel') return "travel" and not travels

**Comment by SjorsO** [comment]
@Kiba86 Laravel uses https://github.com/doctrine/inflector for pluralization. You can open an issue there.
