### ISSUE TITLE
Rule stub and contract not compatible with $parameters array

### ISSUE THREAD

**Issue by robjbrain** [laravel/framework#28555]
- Laravel Version: 5.7.16
- PHP Version: 7.2.6

### Description:
I'm not sure if this is a bug, feature request or documentation issue.

### Steps to reproduce
When you use `php artisan make:rule ExampleRule` you are provided with a class containing the method `passes()`.

```php
<?php

namespace App\Rules;

use Illuminate\Contracts\Validation\Rule;

class ExampleRule implements Rule
{
    /**
     * Create a new rule instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Determine if the validation rule passes.
     *
     * @param  string  $attribute
     * @param  mixed  $value
     * @return bool
     */
    public function passes($attribute, $value)
    {
        //
    }

    /**
     * Get the validation error message.
     *
     * @return string
     */
    public function message()
    {
        return 'The validation error message.';
    }
}
```

The `passes()` method has two arguments `$attribute` and `$value` as per the contract `Illuminate\Contracts\Validation\Rule`.

https://github.com/laravel/framework/blob/b1119eb359bab0cc1deea3fe40501db7ab2371db/src/Illuminate/Contracts/Validation/Rule.php#L14

If you use this rule to extend the Laravel Validator via `Validator::extend('example', 'ExampleRule@passes');` then it will be called via `callClassBasedExtension()` in `Validator.php` and this provides a third argument `$parameters` and a fourth argument $validator.

https://github.com/laravel/framework/blob/b1119eb359bab0cc1deea3fe40501db7ab2371db/src/Illuminate/Validation/Validator.php#L1163 

But you can't access these additional arguments because of the Rule contract.

```php
public function passes($attribute, $value, $parameters, $validator) {
}
```

> Declaration must be compatible with Rule->passes`

It doesn't look like you can add these arguments to the contract because when you just use `new ExampleRule()` the passes() method will only receive `$attribute` and `$value`.

But since they're sent they should be compatible.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
