### ISSUE TITLE
JsonResource renders integer foreign key attribute as string instead of number 

### ISSUE THREAD

**Issue by ddosanjh** [laravel/framework#28562]
- Laravel Version: 5.8.4
- PHP Version: 7.2

### Description:
JsonResource render's an Eloquent model's id integer value as an unquoted numeric, however a field that is a foreign key, is rendered as a double-quotes string (which screws up JS Map key reference without explicit casting).

Work-around: define model's $casts = [ 'some_foreign_id' => 'integer']

It should be rendered consistently with the foreign entity's id field however.

Should be straight-forward to reproduce. If it's at all unclear I will attach an example.

**Comment by staudenmeir** [comment]
This depends on the database you are using. Please add the information (as the issue template shows).

**Comment by ddosanjh** [comment]
DB_CONNECTION=sqlite

**Comment by staudenmeir** [comment]
Unlike most other databases, SQLite returns all values as strings and Laravel can't fix that.

You'll have to use the `$casts` workaround.

**Comment by ddosanjh** [comment]
Thanks for looking into this. However, why is the primary key value correctly rendered as numeric and not foreign keys values? Can't we get this from the schema?

I am happy to use the workaround, but it can be a pitfall. It's not great that changing the DB driver in the .env will alter client-side behavior, breaking Map lookup.

**Comment by staudenmeir** [comment]
The primary key is an exception, Laravel knows its type from `Model::$keyType` and `$incrementing`.

In Laravel, models intentionally have no knowledge of their database schema.

Are you using SQLite for testing?

**Comment by ddosanjh** [comment]
Sorry for the delayed response, yes I am using sqlite for development and testing.

I reported this only because it looks like a bug and thought it might be helpful to others. This is not a big issue for my project since I use a custom Model extension which adds schema and validation rules at the entity level.

I have always wondered why entity declaration is scattered across the framework. What is a benefit of doing it that way?

In any case, I will close this out as it doesn't seem actionable. Thanks for your attention.
