### ISSUE TITLE
Validation date_format doesn't work as expected with casted datetime attributes

### ISSUE THREAD

**Issue by hhummell81** [laravel/framework#28561]
- Laravel Version: 5.8
- PHP Version: 7.2

### Description: 

When used $casts with a column as datetime:Y-m-d and use date_format validation rule (date_format:Y-m-d), and the user sends a wrong date (ex: 62019-05-17), it won't throw the validation exception. Instead, it throws a InvalidArgumentException: The separation symbol could not be found Unexpected data found. Data missing.

If line of datetime:Y-m-d in $casts is removed, then it works as expected (but you will not get the automtic cast then).

### Steps To Reproduce:

Add a attribute as datetime:Y-m-d i $casts of a model.
Create a form request with the validation rule date_format:Y-m-d
Add a form and send a wrong date (ex: 62019-05-17)
See that you will get a InvalidArgumentException instead of a ValidationException than returns you back with the error messages.

**Comment by staudenmeir** [comment]
How is the model involved in the validation?

**Comment by hhummell81** [comment]
It is a regular model with a date column in the database, and with the $casts = ['column' => 'datetime:Y-m-d']

**Comment by staudenmeir** [comment]
How are you validating the form request?

**Comment by hhummell81** [comment]
Aren't you able to reproduce it?

**Comment by staudenmeir** [comment]
No, I can't reproduce it. Please provide the necessary code.

**Comment by driesvints** [comment]
Heya, thanks for reporting.

I'll need more info and/or code to debug this further. Please post relevant code like models, jobs, commands, notifications, events, listeners, controller methods, routes, etc. You may use https://paste.laravel.io to post larger snippets or just reply with shorter code snippets. 

Thanks!

**Comment by hhummell81** [comment]
Sure, this week I will provide a complete example (closing meanwhile). Thanks!

**Comment by hhummell81** [comment]
Ok, so I found out why was happening, and I am writing it here for future people with same problem (probably my future self).

The issue triggers when I try to set a value with data_set($model, $attribute, $value) with a wrong date formatted value, and that attribute has in $casts the datetime:Y-m-d (for instance).

So, if I write data_set($model, $attribute, '31-05-20109') and that attribute is casted with 'datetime:Y-m-d', the error message appears.

Why am I using that? Because I am setting the old input values (old() helper) of a form into a Javascript values with the [laracasts/PHP-Vars-To-Js-Transformer](https://github.com/laracasts/PHP-Vars-To-Js-Transformer) package, so I can use the old input values of the form with VueJS.

Hope this reference helps in the future if anyone is looking for a error message like "The separation symbol could not be found Unexpected data found. Data missing.".
