### ISSUE TITLE
[5.7] LogManager function stack $channel not set config name

### ISSUE THREAD

**Issue by bluetu** [laravel/framework#28560]
- Laravel Version: 5.7.#
- PHP Version: 7.1.#
- Database Driver & Version:

### Description:
\Illuminate\Support\Facades\Log::stack($channels, $channel);
$channel not set config name.

LogManager.php
![image](https://user-images.githubusercontent.com/11599308/57912688-8f4f4600-78bd-11e9-9fde-d06fb7c95bee.png)
ParsesLogConfiguration.php
![image](https://user-images.githubusercontent.com/11599308/57912749-b60d7c80-78bd-11e9-9dc1-3421d9c2dec0.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
