### ISSUE TITLE
__($variable)/trans($variable) and @lang($variable) with different results

### ISSUE THREAD

**Issue by hgferreira** [laravel/framework#28575]
- Laravel Version: 5.8.17
- PHP Version: 7.2.11

I'm from Portugal and we use accentuated characters and since my last Laravel update started having issues with UTF-8 strings with special characters like Ç, ã, etc.

I noticed that __($variable) and trans($variable) inside a blade template will give wrong results due a double utf-8 encoding. I noticed that every variable a utf-8 encoded string is encoded again giving in error.

Result of the compiled version:
`<?php echo e(utf8_encode($record->guests)); ?>`

This results that strings inside for example the languages files with special characteres to be displayed with error. 
The @lang function doesn't seems to be affected by this behaviour displaying the correct special characters.

Cheers,
Hugo Ferreira

**Comment by driesvints** [comment]
When I add `'foo' => 'Ç, ã',` to the `resources/lang/en/validation.php` file and add the following to a blade view:

```
@lang('validation.foo')<br>
{{ __('validation.foo') }}<br>
{{ __('Ç, ã') }}<br>
{{ trans('Ç, ã') }}<br>
```

All four give `Ç, ã` as their output. So I suspect there's something wrong with your setup? Can you create a repo where you can reproduce the problem?

**Comment by hgferreira** [comment]
I did the same test that you did, the code I used inside a blade was:

` lang -- @lang('Ç ç ã é')<br />`
`__ --{{ __('Ç ç ã é') }}<br />`
`trans -- {{ trans('Ç ç ã é') }}<br />`
`mb_convert_encoding -- {{ mb_convert_encoding(__('Ç ç ã é'), 'iso-8859-1') }}<br />`

The results were:

lang -- Ç ç ã é
__ --Ã Ã§ Ã£ Ã©
trans -- Ã Ã§ Ã£ Ã©
mb_convert_encoding -- Ç ç ã é

In the last one I converted the string first to iso-8859-1 and then when the __() works the string convert it back to utf-8 and prints correctly. The ones that already are in utf-8 are converted again and display uncorrectely.

The project where this happened is being developed for the last 8 months without any glitch.... 
This happened when I upgraded from Laravel 5.8.15 to 5.8.17, already tried to downgrade but it doesn't helped. 

That wasn't the only one problem with this upgrade, LaravelCollections Form:: now requires to be 
unescaped to print the html code {{ Form::text() }} has to be {!! Form::text() !!} but I will check this better d if necessary fill another issue. Also, the strings with special characters like this ones above, if aren't unescaped they will have the same issue, even if they're not translated, something is going on here...

I will install another clean environment and test it directly there. I'll updated you soon I have some more information.

Cheers

**Comment by mfn** [comment]
> already tried to downgrade but it doesn't helped.

This is very suspicious.

Did you maybe or by accident change the encoding of those lang files somehow? Do you have your sources versioned, can you double check.

**Comment by hgferreira** [comment]
Yes, it was very suspicious. Found the issue, it was a parameter added to AppServiceProvider. 
Sorry, for the time and resources consumed with this ticket. It is fixed.

Thank you.
