### ISSUE TITLE
Laravel 5.3 Eloquent return rounded float number

### ISSUE THREAD

**Issue by mediaceh** [laravel/framework#28574]
- Laravel Version: 5.3.23
- PHP Version: 7.1.29
- Database Driver & Version: MySql 5.5.55

### Description:
Hi! After update to php 7.1 eloquent model return rounded float number from db. In db field have type float(10,2). Php have standart config. Before updating all was be ok.
For example: 
in db field `weight` - 0.3 
in eloquent  property `weight`- 0.0
in db field `weight` - 2.7 
in eloquent  property `weight` - 2.0

Field saved correctly. 

Please, help me.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
