### ISSUE TITLE
Laravel Cache stores gigabytes of data and does not clear or purge on its own

### ISSUE THREAD

**Issue by timothymarois** [laravel/framework#28581]
- Laravel Version: 5.8.12
- PHP Version: 7.1.28

### Description:
I have a Laravel web API that gets millions of hits a day. 

1) I have not asked Laravel to cache anything on my side. 
2) The cache config settings are vanilla (unchanged)

But apparently, I have **8.7G of /storage/framework/cache/~** 

Yes, I can create a script to just purge the cache automatically, but that's not the point, this cache thing is becoming an issue and its sucking out the disk space on the server for no reason. 

Why? This is not sustainable. 

### Steps To Reproduce:

Not really sure, use Laravel 5.8, run a few million hits a day and see if your cache continues to grow.

**Comment by timothymarois** [comment]
So far, looks like millions of files located in random directories like `4e/25/~` and the contents of all these files are random numbers like `1558410056i:2;` .. `1557586623i:1557586623;` etc.

**Comment by staudenmeir** [comment]
Are you using the `ThrottleRequests`/`throttle` middleware?

**Comment by timothymarois** [comment]
@staudenmeir, I do have `throttle:60,1` set. But even if that's creating the cache of throttle requests, why would Laravel not automatically clean that mess up like it does with garbage collector on sessions? Something doesnt seem right.

**Comment by staudenmeir** [comment]
That's where the files are coming from.

Garbage collection for sessions is simpler to implement and faster, as all files are stored in a single folder. The nested structure of the cache directory makes this more complex.

**Comment by timothymarois** [comment]
@staudenmeir, right that makes sense. But what you're saying though, if I'm using a throttle on millions of requests a day, there's nothing I can do aside from creating my own automated cache purge action?

**Comment by staudenmeir** [comment]
You could look at other cache drivers. AFAICS, Redis automatically removes expired values.

**Comment by timothymarois** [comment]
@staudenmeir, looks like Laravel Throttle on the file driver is not good with high volume then. I'll look into other options if I decide throttling is worth using for this api project. Thanks again.

**Comment by mfn** [comment]
@timothymarois nice observation. Maybe the docs can be improved in this regarding throttling and high volume requests (which is the point for using throttling in the first place 😅)

**Comment by mirko77** [comment]
@timothymarois are there any updates on this? We are hitting the same issue on an application where we throttle auth requests via email, have you implemented anything to purge the cache?

**Comment by mirko77** [comment]
@mfn I will give it a try, thanks

**Comment by Vectorial1024** [comment]
In case anyone here in the future still want a file-based solution rather than adopting Redis or its forks, consider giving https://packagist.org/packages/vectorial1024/laravel-cache-evict a try.
