### ISSUE TITLE
Serializes Models Question

### ISSUE THREAD

**Issue by kauanslr** [laravel/framework#28584]
I'm using `withChain` to dispatch some jobs, and those jobs use a model. I've noted the `serializesModels` serializes basically the connection and the table to 'save' the job, and then uses that information to make a query and get the attributes. Why it does not serialize the model itself, with all attributes?

For example:

```php
class Job implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    /**
     * @var Payroll The Payroll model instance.
     */
    protected $payroll;

    public function __construct(Payroll $payroll)
    {
        $this->payroll = $payroll;
    }
```

Lets assume we have two jobs that has the same contructor as the above code. Let's dispatch the jobs chained with `Job::withChain([new SecondJob($payroll)])->dispatch($payroll)`.
Assuming `$payroll` as a instance of `Payroll` model but not in database, if we dispatch that chain the `SecondJob` wi'll cause a `No query results for model` (without stacktrace to the job), what make no sense, cause i've passed the required instance to the job and i want the job to use that instance.

It's similar to #15866

**Comment by mustorze** [comment]
I've got this problem too.
The first time i've used the `SerializesModels` i thought the trait may convert my instance into a serial and inside my job returns then instanced. Instead of this, they hits the DB and get the attributes.

I guess this is a mistake like the author.

**Comment by devcircus** [comment]
Look back through the PRs and issues here. This is indeed the expected behavior. At one time, serializesmodels worked the way you describe, however that behavior caused a number of issues. It was then changed to the current implementation.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
