### ISSUE TITLE
SoftDelete: forceDeleting ignores in Builder

### ISSUE THREAD

**Issue by abolabo** [laravel/framework#28585]
- Laravel Version: 5.8
- PHP Version: 7.2
- Database Driver & Version:
mysql
Steps To Reproduce:
1. create some new model MyModel with softDelete trait use
2. set protected forceDeleting as TRUE
3. try to delete with query builder 
MyModel::where('col', '=', 1)->delete();
Fail - force deleting not works! Row must be removed

Solution:
File Eloquent/SoftDeletingScope.php
replace method extend with this

    public function extend(Builder $builder)
    {
        foreach ($this->extensions as $extension) {
            $this->{"add{$extension}"}($builder);
        }

        $builder->onDelete(function (Builder $builder) {
            $column = $this->getDeletedAtColumn($builder);
            if ($builder->getModel()->isForceDeleting()) {
                return $builder->forceDelete();
            } else {
                return $builder->update([
                    $column => $builder->getModel()->freshTimestampString(),
                ]);
            }
        });
    }

**Comment by staudenmeir** [comment]
The `$forceDeleting` property is not meant to be changed.

Since PHP doesn't allow you to override trait properties in the model using the trait (only in child models), this shouldn't even be possible:

```php
class User extends Model
{
    use SoftDeletes;

    protected $forceDeleting = true;
}

new User;
```

>App\User and Illuminate\Database\Eloquent\SoftDeletes define the same property ($forceDeleting) in the composition of App\User. However, the definition differs and is considered incompatible.

What does your model look like?

**Comment by abolabo** [comment]
@staudenmeir 
It looks the same (MyModel extends Model). 
Model have  protected $forceDeleting = true;
but deleting still "soft" 
when try to delete calling MyModel::where('col', '=', 1)->delete();

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by abolabo** [comment]
Hi @driesvints .
No it's a bug, not question.
I even added solution how to fix it.

**Comment by staudenmeir** [comment]
This is not a bug. `$forceDeleting` is an internal property of the `SoftDeletes` trait and shouldn't be changed.
