### ISSUE TITLE
Can't get failed item with array validation directly

### ISSUE THREAD

**Issue by tpaksu** [laravel/framework#28599]
- Laravel Version: 5.6.39
- PHP Version: 7.1.7
- Database Driver & Version: MySQL 5.7.19

### Description:
When running an array validator, invalid items in the array can't be seen without parsing the `$validator->failedRules` array keys. 

### Steps To Reproduce:

Use this code in a controller:

```
$validator = \Illuminate\Support\Facades\Validator::make([
            "records" =>
            [
                "ABC123",
                "ABC122",
                "ABB132",
                "ADCD23"
            ]
        ],[
            "records.*" => [
                "required",
                "regex:/[A-F]{3}[0-9]{3}/"
            ]
        ]);
```

if I call

    dump($validator->invalid());

It outputs:

```
array:1 [▼
  "records" => array:4 [▼
    0 => "ABC123"
    1 => "ABC122"
    2 => "ABB132"
    3 => "ADCD23"
  ]
]

```

Which should be (IMO), 

```
array:1 [▼
  "records" => array:4 [▼   
    0 => "ADCD23"  // or indexed as 3
  ]
]
```

If I call

    dump($validator->failed());

It returns

```
array:1 [▼
  "records.3" => array:1 [▼
    "Regex" => array:1 [▼
      0 => "/[A-F]{3}[0-9]{3}/"
    ]
  ]
]
```

Which I can tell which item fails the validation, but there should be a shorter way.

**Comment by tpaksu** [comment]
To give a little more detail:

```
$validator = \Illuminate\Support\Facades\Validator::make([
    "testvalid" => "filled",
    "testinvalid" => "",
    "records" =>
    [
        "ABC123",
        "ABC122",
        "ABB132",
        "ADCD23"
    ]
],[
    "testvalid" => "filled",
    "testinvalid" => "filled",
    "records.*" => [
        "required",
        "regex:/[A-F]{3}[0-9]{3}/"
    ]
]);

if($validator->fails()){
    dump($validator->invalid());
    dump($validator->failed());
}
```

outputs:

```
array:2 [▼
  "testinvalid" => ""
  "records" => array:4 [▼
    0 => "ABC123"
    1 => "ABC122"
    2 => "ABB132"
    3 => "ADCD23"
  ]
]
```

Which is true for the first level, `testinvalid` and `records` are the reason to fail the validation, but should all the array be dumped for `records`?

**Comment by tpaksu** [comment]
And for a fix, I think we can use something like this in the validator->invalid method:

    $result = [];
    $failed = array_only(array_dot($validator->invalid()), array_keys($validator->failed()));
    foreach($failed as $key => $failure){
          array_set($result, $key, $failure);
    }
    return $result;

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by tpaksu** [comment]
@driesvints  Yes I've tested it Laravel 5.8.18 and the problem still exists.

**Comment by driesvints** [comment]
Would this also return multiple values if for example two failed but a third didn't?

**Comment by tpaksu** [comment]
Yes, I've tested the code on my second comment and it gives the exact same output.

**Comment by tpaksu** [comment]
@driesvints does it need more info? If I should provide more info, please ask.

**Comment by driesvints** [comment]
I have no idea if this is a bug or not tbh. Feel free to attempt a PR and we'll see what @taylorotwell says.

**Comment by tpaksu** [comment]
Ok I'll do so. Thank you.

**Comment by ahinkle** [comment]
Your PR looks like it needed a test to support the change -- perhaps a quick example for the maintainers to understand the change within the description area of the PR will help too.

**Comment by d3jn** [comment]
Regarding this problem, it might not be a problem (depending on how we look at it). `invalid()` method is supposed to return data that is invalid. It just happens to consider as data only first level of keys (`attributesThatHaveMessages()` will return only first level keys for messages and then intersection with data is done). All nested keys won't be changed.

Here https://github.com/d3jn/framework/commit/db35f5dfee6c0337352613643b767b060385e81b I've extended `invalid()` test with additional assertion for when wildcard `*` character is used deeper in the nested rule:

```
F                                                                   1 / 1 (100%)

Time: 489 ms, Memory: 64.00 MB

There was 1 failure:

1) Illuminate\Tests\Validation\ValidationValidatorTest::testInvalidMethod
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     'items' => Array (
         1 => 'invalid'
+        0 => 'correct'
+        2 => 'also-correct'
     )
 )
```

On one hand, data's `items` key was invalid and is returned (with all it's elements) as it is. But implementing n-level support for `invalid()` result would be way nicer IMO (so that only keys that were failed are left no matter their level in the array).

What do you think?

P. S. Also, whoever implemented `ValidationValidatorTest::testInvalidMethod::testInvalidMethod` in the first place did a poor job, since actual values are passed into PHPUnit assertion as expected (and vice versa). I don't know if it warrants separate pull request to fix such tests, but it definitely makes diffs in PHPUnit reports very confusing.

**Comment by tpaksu** [comment]
@d3jn Thanks for the detailed explanation, I'm currently on vacation and because of that I can't re-submit a detailed PR for this case, You're absolutely welcome if you want to fix this issue until I try again ;)

**Comment by tpaksu** [comment]
> And for a fix, I think we can use something like this in the validator->invalid method:
> 
> ```
> /**
> * Returns the data which was invalid.
> *
> * @return array
> */
> public function invalid()
> {
>     if (! $this->messages) {
>         $this->passes();
>     }
> 
>     $invalid = array_intersect_key(
>         $this->data, $this->attributesThatHaveMessages()
>     );
> 
>     $result = [];
>     $failed = array_only(array_dot($invalid), array_keys($this->failed()));
>     foreach($failed as $key => $failure){
>         array_set($result, $key, $failure);
>     }
> 
>     return $result;
> }
> ```

FYI @d3jn, with this modification, I can reach the invalid keys in multi level validations.

**Comment by driesvints** [comment]
The pr for this was merged and will be available in the next release.

**Comment by tpaksu** [comment]
Thanks @driesvints .
