### ISSUE TITLE
assertJsonStructure breaks comparing structure with itself

### ISSUE THREAD

**Issue by DerManoMann** [laravel/framework#28591]
- Laravel Version: 5.8.18
- PHP Version: 7.3.5

### Description:
Comparing a data structure with itself beaks with message `Failed asserting that an array has the key 1.`
Using `assertExactJson` does work, though.

### Steps To Reproduce:
```
        $data = ['data' => ['user_id' => 1, 'role' => 'admin']];
        (new TestResponse(new Response()))->assertJsonStructure($data, $data);
```

**Comment by driesvints** [comment]
Why would you want to do this? Can you provide a full test for this?

**Comment by DerManoMann** [comment]
Well, this is just a test case to demonstrate the problem.
In my test class it would look like this:
````
$response->assertJsonStructure(['data' => ['user_id' => 1, 'role' => 'admin']]);
````

**Comment by DerManoMann** [comment]
I would expect the assert to pass if the structure matches, even if the id and role values are not the same.

**Comment by driesvints** [comment]
Hmm, I think you're maybe right. It seems to me that the `$value` on this line actually needs to be `$key`: https://github.com/laravel/framework/blob/435c05b96a241d3d5e37ce524de9ea134714a9be/src/Illuminate/Foundation/Testing/TestResponse.php#L600

But this has been around for two years already and no-one ever reported problems with this so I'm not really sure if it's broken or not: https://github.com/laravel/framework/pull/17700

Maybe if I can ping the original author (@cretueusebiu) he can explain why this is implemented as `$value` and not `$key`.

**Comment by driesvints** [comment]
There are also no tests for the second `$responseData` param so it's hard to check what the actual expected behavior is.

**Comment by cretueusebiu** [comment]
At that time I just ported the method from the [browser-kit-testing](https://github.com/laravel/browser-kit-testing/blob/5.0/src/Concerns/MakesHttpRequests.php#L363) repo.

**Comment by driesvints** [comment]
I finally get what's happening. The thing is that the `$structure` argument *only* needs the structure and not the any data. So it's not a one-on-one match with the actual response.

@DerManoMann what you need to do is this:

```php
$response->assertJsonStructure(['data' => ['user_id', 'role']]);
```

The docs could use an example. I'll try to send in a PR for this but feel free to beat me to it.
