### ISSUE TITLE
Different behaviors of getRelationValue

### ISSUE THREAD

**Issue by zserhiy** [laravel/framework#28598]
- Laravel Version: 5.8.18
- PHP Version: 7.2.17
- Database Driver & Version: sqlsrv

Description:
getRelationValue has different behaviors
1. getRelationValue returns element from "relations" array if it exists there.
2. getRelationValue returns value from getRelationshipFromMethod call. 
But getRelationshipFromMethod uses setRelation to set value into "relations" array, however always returns original value.

Steps To Reproduce:

```php
class Test extends Model
{
    protected $table = 'users';

    public function rel()
    {
        return $this->hasOne(Test::class, 'id', 'id');
    }

    public function setRelation($relation, $value)
    {
        if ($relation == 'rel') $value = 1;
        return parent::setRelation($relation, $value);
    }

    public static function test()
    {
        $instance = static::find(1);
        $rel1 = $instance->rel; // $rel1 is instance of class Test
        $rel2 = $instance->rel; // $rel2 is integer 1
    }
}
```

**Comment by staudenmeir** [comment]
`getRelationValue()` isn't meant to be changed like this.

What's a real-life example where you would need this behavior?

**Comment by zserhiy** [comment]
I override setRelation to do keyBy on some relations.

**Comment by zserhiy** [comment]
I think getRelationValue could be like this.
if (!$this->relationLoaded($key) && method_exists($this, $key)) {
  $this->getRelationshipFromMethod($key);
}
return Arr::get(relations, $key);

**Comment by driesvints** [comment]
I'm sorry but at the moment we don't support overriding the methods in this way. If you wish to see the behavior of these methods to be changed please open an issue on the ideas repository. Thanks.
