### ISSUE TITLE
[5.8] Query Builder: Unexpected behavior using take and chunk.

### ISSUE THREAD

**Issue by mvdnbrk** [laravel/framework#28590]
- Laravel Version: 5.8.18
- PHP Version: 7.3.5
- Database Driver & Version: 10.3.14-MariaDB

### Description:
Using the query building using `take()` in conjunction with `chunk()` results in unexpected behavior.

### Steps To Reproduce:
- Seed `users` table with 1000 records.

```php
DB::table('users')
    ->orderBy('id')
    ->take(100)  // select * from "users" asc limit 100
    ->chunk(10, function ($users) {
        // closurse gets called 100 times:
        // 100*10 = total of 1000 users

        // expected: 10*10 = 100
    });
```

I am expecting the `chunk()` method to respect the limit of 100 that was set with the `take()` method.

>     /**
>      * Chunk the results of the query.
>      *
>      * @param  int  $count
>      * @param  callable  $callback
>      * @return bool
>      */
>     public function chunk($count, callable $callback)

The reason this happens is that the `chunk()` method uses the `forPage()` method on the query builder which will just cycle through **all** the records.

A solution may be to let the `chunk()` method take the limit (if already set) into account and return that number of records as a maximum.

**Comment by bonzai** [comment]
#23709
#9649
laravel/ideas#103

**Comment by mvdnbrk** [comment]
@bonzai thanks, searched for it but couldn't find it...

Will take a look at these later 😉

**Comment by driesvints** [comment]
Please see the linked issues above, thanks.
