### ISSUE TITLE
Formatter Config dropped in LogManager prepareHandler calls

### ISSUE THREAD

**Issue by davenorthcreek** [laravel/framework#28605]
My issue was trying to log a deeply nested JSON object, so I dug into Monolog and created a subclass of LineFormatter.  In config/logging I tried to specify the formatter to use (my class):
        'daily' => [
            'driver' => 'daily',
            'path' => storage_path('logs/lumen.log'),
            'level' => env('LOG_LEVEL'),
            'days' => 14,
            'formatter' => HigherNormalFormatter::class,
],
But similar to #24700 the $config array is not sent to prepareHandler in LogManager.
Once I modified LogManager to submit the $config array, the logging works as expected.

I will submit a PR.

**Comment by davenorthcreek** [comment]
My code is using Lumen 5.6.4, I see the code is fixed in 5.8.

**Comment by laurencei** [comment]
Thanks, the best option to resolve this is to upgrade to Laravel/Lumen 5.8 where the issue is resolved.

Laravel/Lumen 5.6 is not supported anymore.
