### ISSUE TITLE
DynamoDB cache driver forever method doesn't work

### ISSUE THREAD

**Issue by jradtilbrook** [laravel/framework#28615]
- Laravel Version: 5.8.18
- PHP Version: 7.3.5
- Database Driver & Version: N/A

### Description:
When trying to use the dynamodb cache store and caching something using the `forever` method, a PHP notice is issued and nothing is stored in the cache.

### Steps To Reproduce:
Configure the dynamodb cache store with credentials and create a table in the AWS console. From tinker, or whichever approach, run: `Cache::store('dynamodb')->forever('cache_key', 'cache_value');` and a notice is issued: `PHP Notice:  Object of class Illuminate/Support/Carbon could not be converted to int in .../vendor/laravel/framework/src/Illuminate/Cache/DynamoDbStore.php on line 459`

I can see in the source for DynamoDbStore that forever tries to use the `put` method with an expiry of `now()->addYears(5)` which makes good enough sense for dynamodb but it should chain on `getTimestamp()` to return an integer that will not raise the notice above.

I'll be happy to provide a PR if you agree this is an issue.

**Comment by laurencei** [comment]
Makes sense - feel free to submit a PR
