### ISSUE TITLE
apiKey is empty

### ISSUE THREAD

**Issue by darvishiyan-mahdi** [laravel/framework#28616]
Hi when i want to go to login page in laravel or any routes that ends to authentication it ends to
apiKey is empty  even with ajax it doesn't go to the controller
the problem is when i use default laravel auth routes and when i define my own manual  auth the problem solved
i have no idea what is wrong and it doesn't log anything

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
