### ISSUE TITLE
json blade directive and the commas

### ISSUE THREAD

**Issue by tontonsb** [laravel/framework#28622]
Expressions involving commas get broken when used in the json directive

```
@json($applications->pluck('week')->map(function($w) {return substr($w, 0, 4).'-'.substr($w, 4);})),
```

This compiles into a broken peace of code:
```
<?php echo json_encode($applications->pluck('week')->map(function($w) {return substr($w, 0, 4).'-'.substr($w) ?>
```

Issues with the directive have been brought up multiple times - #27853, #27802, #25212, #24734, #23655. And I feel like bringing this up again as the problem hasn't been addressed properly.

I suggest to drop the optional parameters and just encode what's passed to the directive with some default options. The optional parameters are undocumented and thus nonexistant to a dev relying on documentation. If some needs it, they'd encode it manually instead of trying some arbitrary syntax to a directive that appears to take single argument.

If it's too breaking of a change, at least merge #23655. The code shouldn't bug in an undocumented way because of some unexpected optional parameters.

**Comment by driesvints** [comment]
Since it's been rejected many times before I don't think we'll ever change our stance about this. The piece of code above does way too much imo and should better be implemented in a service which then provides the mapped data to the JSON directive.

I'm sorry but we won't be reconsidering this. Please try to be mindful when writing code with blade directives and not put too much logic into them.

**Comment by tontonsb** [comment]
I see, thanks for the answer. Kind of expected, but I posted this because I believe that anything that's brought up enough times will be considered and fixed eventually. Even the option to disable registration routes got it's way in eventually :)

**Comment by driesvints** [comment]
@tontonsb you're always free to start an issue in the ideas repo and who knows if it gets enough support it could be reconsidered :)
