### ISSUE TITLE
Command "..." is not defined.

### ISSUE THREAD

**Issue by Helfull** [laravel/framework#28626]
Given this setup
ConsoleServiceProvider.php
```
class ConsoleServiceProvider extends ServiceProvider
{
    protected $commands = [
        ScheduledCommand::class,
        ChainedCommand::class,
    ];

    /**
     * Bootstrap the application services.
     *
     * @return void
     */
    public function boot()
    {
        $this->registerCommands();

        $this->registerSchedule();
    }

    protected function registerCommands(): void
    {
        if ($this->app->runningInConsole()) {
            $this->commands($this->commands);
        }
    }

    protected function registerSchedule(): void
    {
        $this->app->booted(function ($app) {
            $schedule = $app->make(Schedule::class);
            $this->registerScheduleCommands($schedule);
        });
    }

    protected function registerScheduleCommands(Schedule $schedule): void
    {
        $this->schedule = $schedule;

        $schedule->command(ScheduledCommand::class)
            ->then(function (Illuminate\Contracts\Console\Kernel $kernel) {
                $kernel->call(ChainedCommand::class);
            })
            ->everyMinute();
    }

}
```

I get the error: `Command "ChainedCommand" is not defined.` (the namespaces are a correct)

If i try to run the command with `php artisan chained:command` it does work. If i do dump the console kernel i can see that it is missing the `ChainedCommand` but i call `$this->commands($this->commands)` which should register the command, which it does since i can call it with artisan.

Do i miss anything here, or is this a bug? i am confused why i the `ChainedCommand` is not listed in the kernel.

please help, thanks :)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
