### ISSUE TITLE
MorphTo Relation ignores parent $timestamp when touching

### ISSUE THREAD

**Issue by timwachsener** [laravel/framework#28638]
- Laravel Version: 5.8.18
- PHP Version: 7.3.2
- Database Driver & Version: MySQL 5.7

### Description:
When creating / updating / deleting a child belonging to a parent through a `MorphTo` relation Eloquent tries to updated the parents `updated_at` column regardless of the parents `$timestamps` property when the parent is listed in `$touches`.

Because this is a polymorphic relation and not all parents may have timestamps I would expect that parents with `$timestamps = false` are ignored when touching.

(I guess this may not only be relevant for `MorphTo` relations but others as well)

### Steps To Reproduce:

Parent.php
```
class Parent extends Model
{
    public $timestamps = false;

    public function children(): MorphMany
    {
        return $this->morphMany(Child::class, 'children');
    }

}
```

Child.php
```
class Child extends Model
{
    protected $touches = ['parent'];

    public function parent(): MorphTo
    {
        return $this->morphTo();
    }

}
```

`$parent->children()->save(new Child());` throws `Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1 no such column: updated_at (SQL: update "parents" set "updated_at" = 2019-05-28 11:02:21 where "parents"."id" = 1)`

**Comment by driesvints** [comment]
That indeed seems like a bug to me. Welcoming prs for this.

**Comment by driesvints** [comment]
Pr for this was merged.
