### ISSUE TITLE
Allow data_get to access private and protected properties

### ISSUE THREAD

**Issue by Juyn** [laravel/framework#28630]
Hi guys,

I'm working on objects with a lot of private/protected properties, and, I cannot use Laravel's awesome Collections because the data_get helper method do not know how to access private/protected values of an object. So functions like pluke or sum does not works...

Is there any way to do it ?
I would had love overwrite the method, but since it's in the helpers.php, I cannot really do this without overwriting every Collection and Arr method that are using it.

Is that a wanted behavior to only use magic call instead of Reflection for example ? Or is it any other way to do so ?

I have something like that in mind:

```php
function data_get($target, $key, $default = null)
{
    if (is_null($key)) {
        return $target;
    }

    $key = is_array($key) ? $key : explode('.', $key);

    while (($segment = array_shift($key)) !== null) {
        if ($segment === '*') {
            if ($target instanceof Collection) {
                $target = $target->all();
            } elseif (! is_array($target)) {
                return value($default);
            }

            $result = Arr::pluck($target, $key);

            return in_array('*', $key) ? Arr::collapse($result) : $result;
        }

        if (Arr::accessible($target) && Arr::exists($target, $segment)) {
            $target = $target[$segment];
        } elseif (is_object($target)) {
            $reflectedObject = new \ReflectionObject($target);

            // Use Reflection class to check if property even exist, otherwhise let's use default value
            if (!$reflectedObject->hasProperty($segment)) {
                return value($default);
            }

            $p = $reflectedObject->getProperty($segment);
            // If property is public, no need to get all the way down
            if ($p->isPublic() && isset($target->{$segment})) {
                $target = $target->{$segment};
            } else {
                // Make the property accessible before geting its value
                $p->setAccessible(true);
                $target = $p->getValue($target);
            }
        } else {
            return value($default);
        }
    }

    return $target;
}
```
Thanks for the help !

**Comment by staudenmeir** [comment]
Related: #26033

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by Juyn** [comment]
Hi,

Somehow, I do think this might be a bug on the library itself, or at least something that need to be more explicit into the doc.
I cannot think of any reason why Collection's methods cannot access private/protected data.

**Comment by driesvints** [comment]
@Juyn you're always free to attempt a PR to the docs if you feel something needs more explanation.
