### ISSUE TITLE
Database charset from default connection instead of url defined

### ISSUE THREAD

**Issue by ImJustToNy** [laravel/framework#28645]
- Laravel Version: 5.8.19
- PHP Version: 7.3.5
- Database Driver & Version: Postgres (Heroku, not sure which version exactly)

### Description:
If you're using new URL parser as a way to connect to your DB, it is possible to get the wrong charset.

### Steps To Reproduce:

1. Define `DATABASE_URL` to Postgres URL
2. Set `default` in `config/database.php` to `mysql`
3. Try to do anything using a database, you will get an error like:
![image](https://user-images.githubusercontent.com/5730766/58516146-50679d00-81a7-11e9-979b-f053a119c83d.png)
because of `utf8mb4` is default MySQL charset despite the fact we're using Postgres driver.

**Comment by mathieutu** [comment]
@ImJustToNy Actually I'm afraid that this isn't a bug here. The URL just overrides the parameters you have in your connection configuration. 
If they are wrong for the connection you need, we can't do anything: here you're using mysql options for a postgres database 🤔.

In fact it's exactly if you have written:
```php
'mysql' => [
	'driver' => 'postgres',
	'database' => 'my database...'
	...
	'charset' => 'utf8mb4',
]
```

Set the proper options in your chosen connection array, or add them to the url as query strings.

@staudenmeir thanks for the ping 😉

**Comment by ImJustToNy** [comment]
Please correct me if I'm wrong but, why it's not getting charset from postgres driver but from MySQL's one? If we are using postgres connection, shouldn't we use the charset from `config.database.connections.pgsql.charset`?

**Comment by mathieutu** [comment]
Nope ! 
As I said the result of your connection configuration object will be:
'mysql' => [
	'driver' => 'postgres',
	'database' => 'my database...'
	...
	'charset' => 'utf8mb4',
]

The connection will not be changed, the `url` key is already in a specified connection. The parameters parsed from the url will simply overwrite the ones in the chosen connection.

**Comment by ImJustToNy** [comment]
Okay, thank you.
