### ISSUE TITLE
Preset bootstrap doesn't recover popper.js and jQuery requirements

### ISSUE THREAD

**Issue by lmmalaquias** [laravel/framework#28655]
- Laravel Version: 5.8.#
- PHP Version: 7.2.#
- Database Driver & Version: postgres

### Description:

The `php artisan preset bootstrap` command does't recover the popper.js and jQuery requirements in the `resources/js/bootstrap.js` file if you executed `php artisan preset none` before.

This procedure could be util to use when you want to get rid of the Vue/React dependencies.

### Steps To Reproduce:

Execute `php artisan preset none` and after, execute `php artisan preset bootstrap`.
Check the `resources/js/bootstrap.js` file.

**Comment by driesvints** [comment]
This is normal because the bootstrap preset only adheres to css files and leaves the js untouched. The `bootstrap.js` file doesn't has anything to do with the CSS framework "Bootstrap" and is just an unfortunate naming conflict.

**Comment by lmmalaquias** [comment]
So, why the `php artisan preset none` command **removes the requirements** from the bootstrap.js file?

**Comment by driesvints** [comment]
Because that preset removes all the front-end scaffolding.

**Comment by lmmalaquias** [comment]
So,

- If i use the preset to remove the front-end scaffolding, it erases all (**including JS requirements**)
- If i use the preset to make the scaffolding to bootstrap, it is done on CSS (**but now, ignoring the JS requirements**)

Why at the first momment, the JS is considered, and at the secound, is not? Is it right?

**Comment by driesvints** [comment]
@lmmalaquias that's correct. Why are you removing the front-end scaffolding and afterwards running the bootstrap one? You only need to run the bootstrap command for the above use-case.

**Comment by devcircus** [comment]
The way I understand it is that the presets are meant to be used alone, once for your project based on your needs, not in combination with other presets. Also I think I read where Taylor said he was completely reworking the presets for 5.9 for a better experience.

**Comment by lmmalaquias** [comment]
> @lmmalaquias that's correct. Why are you removing the front-end scaffolding and afterwards running the bootstrap one? You only need to run the bootstrap command for the above use-case.


As the framework comes with everything related to **Vue** by default and the bootstrap scaffolding let some things related to Vue untouched, it was the way I thought to remove everything related to the vue, without being manually.

I don't know if this is the best way to do. Sorry if it's a beginner question. It's because i'm beginner, but ever looking for the best pratices.

**Comment by lmmalaquias** [comment]
@driesvints , it's not right?

**Comment by lmmalaquias** [comment]
@driesvints  , maybe the bootstrap preset should to remove the Vue related things. No?

**Comment by driesvints** [comment]
@lmmalaquias no because the bootstrap is for the css and vue for the js which are two different things. Like @devcircus said you usually only want to execute one preset at the beginning of your project.
