### ISSUE TITLE
assertSeeText fails when text contains escapable characters

### ISSUE THREAD

**Issue by amsoell** [laravel/framework#28651]
- Laravel Version: 5.8.19
- PHP Version: 7.2.15
- Database Driver & Version: n/a

### Description:

When asserting that text appears on the page, `assertSeeText($expected_value)` fails when the expected text contains escapable characters such as apostrophes. This can be avoided by simply running `assertSeeText(e($expected_value))` but it seems that given the fact that we have `assertSee()` and `assertSeeText()` it might be expected that the latter finds the string even with characters escaped. This has caused us intermittent problems because the Faker library often returns names with apostrophes, which in turn causes our tests to fail every 10 or 12th time they run.

I was going to attempt a PR to "fix" this, but first I wanted some confirmation that this isn't functioning as intended and that the PR is desirable.

### Steps To Reproduce:

routes/web.php
```php
Route::get('/', function () { return "O&#039;Connor"; });
```

tests/Feature/RouteTest.php
```php
use Tests\TestCase

class RouteTest extends TestCase
{
    public function test_text_that_contains_apostrophes_is_seen()
    {
        $this->get('/')->assertSeeText("O'Connor");
    }
}
```

**Comment by devcircus** [comment]
See previous discussions on the matter. https://github.com/laravel/framework/pulls?q=is%3Apr+assertseetext+is%3Aclosed

**Comment by amsoell** [comment]
> See previous discussions on the matter. https://github.com/laravel/framework/pulls?q=is%3Apr+assertseetext+is%3Aclosed

I searches the issues but not the pulls. Thanks for pointing it out!
