### ISSUE TITLE
Schema::dropIfExists() Deleted ALL tables in DB on migrate:rollback

### ISSUE THREAD

**Issue by iFabrycio** [laravel/framework#28652]
I was making TDD tests when i ran `php artisan migrate:rollback` on command line, so the migration deleted ALL TABLES in db.

the migration code is that:

>public function up()
    {
        Schema::create('products', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->integer('image')->unsigned()->nullable();
            $table->string('name', 64);
            $table->string('slug', 64)->unique();
            $table->integer('price')->unsigned();
            $table->timestamps();
        });
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('products');
    }
}

And thats the only migration created(i deleted the standard migrations)

i think `Schema::dropIfExists('products');` does not have to delete all database tables, but just the 'products' table.

Someone can help to understand this? is this a bug or my mistake?

**Comment by staudenmeir** [comment]
> I was making TDD tests when i ran php artisan migrate:rollback

Were you running a test or `php artisan migrate:rollback`?

**Comment by iFabrycio** [comment]
> > I was making TDD tests when i ran php artisan migrate:rollback
> 
> Were you running a test or `php artisan migrate:rollback`?

php artisan migrate:rollback

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by staudenmeir** [comment]
`dropIfExists()` does only drop a single table. There must be something else going on in your application/database.
