### ISSUE TITLE
Make event() return Listeners class names as array keys to distinguish certain Listener output

### ISSUE THREAD

**Issue by Tarasovych** [laravel/framework#28663]
- Laravel Version: 5.8.17
- PHP Version: 7.2.14
- Database Driver & Version: doesn't matter, DB isn't involved

### Description:
Assume we have such `Event` and many `Listeners`:
```php
    protected $listen = [
        'App\Events\FirstEvent' => [
            'App\Listeners\FirstListener',
            'App\Listeners\SecondListener',
            'App\Listeners\ThirdListener',
        ],
    ];
```
and inside each `Listener`
```php
    public function handle(/* EventName $event */)
    {
        return 'return from ' . get_class($this);
    }
```
and call event like that
```php
    $e = event(new \App\Events\FirstEvent());
```
If we need to work with `Event` output, we have to distinguish somehow where's the output of certain `Listener`.
Now
```php
    $e = event(new \App\Events\FirstEvent());
    dd($e);
```
results in
```
array:3 [▼
  0 => "return from App\Listeners\FirstListener"
  1 => "return from App\Listeners\SecondListener"
  2 => "return from App\Listeners\ThirdListener"
]
```
As for me, it will be handy to have `Listener` class names as array keys:
```
array:3 [▼
  "App\Listeners\FirstListener" => "return from App\Listeners\FirstListener"
  "App\Listeners\SecondListener" => "return from App\Listeners\SecondListener"
  "App\Listeners\ThirdListener" => "return from App\Listeners\ThirdListener"
]
```
### Steps To Reproduce:
Please, take a look in Description or clone [repository](https://github.com/Tarasovych/laravel-events-proposal).

I'm ready for digging in and/or submitting pull request.

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!
