### ISSUE TITLE
Encrypt cookie not work on dynamic cookie

### ISSUE THREAD

**Issue by ravindrasinghinbox** [laravel/framework#28673]
- Laravel Version: 5.7.2
- PHP Version:7.3
- Database Driver & Version:

### Description:
vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php

THIS FUNCTION SHOULD MATCH DYNAMIC COOKIE LIKE "version_1,version_2,version_3 ...".
this is no way to ingnore cookie for dynamic.
/**
     * Determine whether encryption has been disabled for the given cookie.
     *
     * @param  string $name
     * @return bool
     */
    public function isDisabled($name)
    {
        return in_array($name, $this->except);
    }

**Comment by sisve** [comment]
Just override the isDisabled method and do anything you want?

**Comment by ravindrasinghinbox** [comment]
Thanks sisve.
