### ISSUE TITLE
Misleading behaviour with whereJsonDoesntContain and array input

### ISSUE THREAD

**Issue by Dankirk** [laravel/framework#28678]
**Story**
You can fetch rows where a json column has 'item1' and 'item2' with the following method
`whereJsonContains('column', ['item1', 'item2']);`

However, if you wanted to do the opposite, a the simple query below is not sufficient.
`whereJsonDoesntContain('column', ['item1', 'item2']);`
This query might return rows containining, for example 'item3' and 'item2'.

To get the expected result, where neither item1 or item2 are present, you have to do this in a foreach loop instead
```
foreach (['item1', 'item2'] as $item) {
   whereJsonDoesntContain('column', $item);
}
```

**Speculation**
As I understand it the query below currently returns rows that don't contain item1 AND item2, but intuition tells this should return rows that don't contain item1 OR item2.
`whereJsonDoesntContain('column', ['item1', 'item2']);`

**Preserve functionality**
To preserve the current behaviour where query by combination of values is preferred, one should use the where() method with a callback as usual
```
where(function($q) use ($items) { 
    foreach ($items as $item) {
        $q->whereJsonDoesntContain('column', $item);
    }
});
```

**Reproduction**
1. Have a table with a json column called 'column' and a single row with json value: ['item1','item2']
2. Run `whereJsonDoesntContain('column', ['item2', 'item3']);`
3. This returns you the single row containing item2

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!
