### ISSUE TITLE
Carbon 1 deprecated

### ISSUE THREAD

**Issue by jonnott** [laravel/framework#28679]
So, composer is now saying Carbon 1.x is old news...

```
*******************************************
 /!\ Warning, you're using a deprecated
 ¨¨¨ version of Carbon, we will soon stop
     providing support and update for 1.x
     versions, please upgrade to Carbon 2.
*******************************************

Most features of Carbon 1 are still available in Carbon 2.
See how to migrate: https://carbon.nesbot.com/docs/#api-carbon-2
```

laravel/framework's composer.json states:

"nesbot/carbon": "^1.26.3 || ^2.0"

..but how can we make it choose 2.0.x over 1.x when doing 'composer install' or 'composer update'? And are there any negative side-effects? (my app doesn't use anything in carbon directly which isn't 2.x-compatible). Even if I rm -rf ./vendor and rm composer.lock and then do 'composer install', it still installs 1.x :(

**Comment by driesvints** [comment]
5.8 currently supports 2.0 so you can just do `composer require nesbot/carbon:^2.0` which should work.

**Comment by jonnott** [comment]
@driesvints Thanks.

**Comment by kylekatarnls** [comment]
Unless you specify to composer "prefer-lowest", it should take the more recent version. So a simple `composer update` should be enough to get Carbon 2 unless you have Laravel < 5.8 or other dependencies that requires Carbon 1.
