### ISSUE TITLE
timed out workers are not immediately killed

### ISSUE THREAD

**Issue by halaei** [laravel/framework#28689]
- Laravel Version: 5.7
- PHP Version: 7.2
- OS: linux
- Queue Driver: Redis

### Description:
Running command `php artisan queue:work --timeout=1` means that if it takes more than 1 second to handle a job, the corresponding worker should be killed. However, when I check it in production, I see it can takes 20 seconds for a worker to get sucked in processing before being killed.

Here is the related code in `Worker` class:
```php
    public function kill($status = 0)
    {
        $this->events->dispatch(new Events\WorkerStopping($status));

        if (extension_loaded('posix')) {
            posix_kill(getmypid(), SIGKILL);
        }

        exit($status);
    }
```
As far as I checked I haven't set any listener for `\Illuminate\Queue\Events\WorkerStopping` event. Also posix extension is loaded. Although I can't check right now, the behavior is probably the same in Laravel 5.8. Maybe it is some PHP limitation?

**Comment by sisve** [comment]
We would need some way to reproduce this to be able to fix it.

1. Does this happen every time? Under during the solstice?
2. Does this happen in any other environment, or only your production environment?
3. Does your job implement a job-specific timeout using the timeout() method?
4. Do you have the pcntl extension?

**Comment by halaei** [comment]
@sisve There is no job-specific timeout and pcntl extension is enabled. It doesn't happen every time. I haven't reproduced it on other environments yet.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by driesvints** [comment]
Btw, like I said above: feel free to validate on 5.8 and if it occurs I'll re-open :)
