### ISSUE TITLE
Validation: `integer` validator passes on (bool) true (expected: should fail)

### ISSUE THREAD

**Issue by mpiasta-ca** [laravel/framework#28685]
- Laravel Version: 5.8.18
- PHP Version: 7.1.*
- Database Driver & Version:

### Description:

Currently, validator for `integer` is passing when value equals TRUE. Expected: it should fail on boolean values.

Oddly, it does fail as expected when value is FALSE.

### Steps To Reproduce:

```
# Should Pass
$input = ['value' => 123];
$rules = ['value' => 'integer'];
$validator = Validator::make($input, $rules);
var_dump('Passes on integer value: ' . $validator->passes() . '<= expected: true');

# Should Fail
$input = ['value' => true];
$rules = ['value' => 'integer'];
$validator = Validator::make($input, $rules);
var_dump('Fails on bool value: ' . $validator->fails() . '<= expected: true');

# Temporary Fix: use numeric|integer
$input = ['value' => true];
$rules = ['value' => 'numeric|integer'];
$validator = Validator::make($input, $rules);
var_dump('Fails on bool value: ' . $validator->fails() . '<= expected: true');
```

**Comment by 570studio** [comment]
This seems to be an issue with PHP's `FILTER_VALIDATE_INT` filter itself as opposed to Laravel, see [this comment](https://www.php.net/manual/en/filter.filters.validate.php#119528) in the documentation. And take a look at the Laravel code below to see that it just uses the PHP filter in the method:

```
    /**
     * Validate that an attribute is an integer.
     *
     * @param  string  $attribute
     * @param  mixed   $value
     * @return bool
     */
    public function validateInteger($attribute, $value)
    {
        return filter_var($value, FILTER_VALIDATE_INT) !== false;
    }
```

**Comment by driesvints** [comment]
This indeed seems to be a bug with PHP itself: https://3v4l.org/J8210

You could use the temp numeric solution if you want.
