### ISSUE TITLE
Migration avoids Primary Auto Increment Key

### ISSUE THREAD

**Issue by vkiranmaniya** [laravel/framework#28700]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2.3
 - PHP: 7.2
 - Database: MySQL 5.6.39

## Description
I Recently migrated the Laravel App from Local Development Environment to Production Server. I Performed Migration and it was done without any error. But Migration does not add Primary Auto Increment Key. However, I solved it by manually adding Primary Key from the database server, But it should be reported as unexpected behavior.  I'm utilizing Laravel with Voyeger. I also Opened Issue in Voyeger.

## Steps To Reproduce
1. Create a Laravel Project in Local Env. and make 1 or 2 dummy tables with migration.
2. Copy that project and host it on production environment
3. Setup Database and configure .env file
4. Run **php artisan:migrate** command
5. Go to Database server and check the structure.

## Expected behavior
The Database structure should be the same as defined in migration

## Additional context
I have solved that issue by manual restoration on the database. I'm using Voyager as BREAD builder. maybe it's causing the issue.

**Comment by laurencei** [comment]
Seems like an issue with Voyager to me. If you can post some code that shows this is specific to Laravel Framework, we can reopen.
