### ISSUE TITLE
Problem with Single Action Controllers

### ISSUE THREAD

**Issue by AliN11** [laravel/framework#28707]
- Laravel Version: 5.8
- PHP Version: 7.2

### Description:
Hi. I defined a route for Single Action Controller, beside other routes:

```php
// web.php

Route::get('/', 'HomeController');
Route::get('/posts', 'PostsController@index');
```
And this is my `HomeController.php`:

```php
<?php

namespace App\Http\Controllers;

class HomeController extends Controller
{
    public function __invoke()
    {
        // return view ...
    }
}

exit;
```

When I open `www.example.com/posts`, the code exits because the `exit;` in the `HomeController`, while `PostsController` is the controller for `/posts` route. 

I don't know why `HomeController.php` file should be opened and checked when current url is matched with `posts` route.

**Comment by driesvints** [comment]
Classes are autoloaded by Composer. Don't place the exit code at the end of the file.

**Comment by AliN11** [comment]
@driesvints It doesn't happen when using normal controllers. It happens only on Single Action Controllers. Laravel checks if `__invoke` method exists in the controller even if that controller is not responsible for that.

**Comment by driesvints** [comment]
Hey @AliN11, I did some research and I think it boils down to the following line which checks if an invoke method is present. That probably loads the class first. This isn't really a bug but rather the way we identify invokable controllers: https://github.com/laravel/framework/blob/5.8/src/Illuminate/Routing/RouteAction.php#L88

**Comment by AliN11** [comment]
@driesvints, I see, but why Laravel tries to ensure whether `__invoke` method exists or not, when the controller and its method will never be called?

I think a better way to check `__invoke` method existence, is when the controller really needs to be called.
@taylorotwell

**Comment by driesvints** [comment]
@AliN11 if you think this can be improve you're always free to send in a PR :)
