### ISSUE TITLE
Cannot use model attribute named "table" in relations

### ISSUE THREAD

**Issue by termiyanc** [laravel/framework#28708]
Hello.

When my model (table) has attribute (column) named "table", i can not use this attribute in relations. The reason i found is that engine calls property, not attribute, when relation is processing. This can be seen, for example, in processing of "belongsTo":

```php
# src/Illuminate/Database/Eloquent/Relations/BelongsTo.php:

    public function addConstraints()
    {
        if (static::$constraints) {
            // For belongs to relationships, which are essentially the inverse of has one
            // or has many relationships, we need to actually query on the primary key
            // of the related models matching on the foreign key that's on a parent.
            $table = $this->related->getTable();
            $this->query->where($table.'.'.$this->ownerKey, '=', $this->child->{$this->foreignKey});
        }
    }
```

If "ownerKey" and/or "foreignKey" refer to attribute named "table", attributes values will not be taken, but the value of internal model property "table" will.

**Comment by browner12** [comment]
Correct, there are a number of field names you cannot use in your table/model.

It is unlikely this will change, so I would recommend picking a new field name.

**Comment by termiyanc** [comment]
But why not to use, for example, `Model::getAttribute()` method in these cases? Is there something much incorrect in this code?

```php
$this->query->where(
    $table.'.'.$this->getAttribute($this->ownerKey), '=', $this->child->getAttribute($this->foreignKey)
);
```

And is not this more logical? Because the attributes correspond to the fields of the table rather than the internal fields of the model, don't they?

**Comment by staudenmeir** [comment]
What version of Laravel are you using?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by termiyanc** [comment]
> Hi there,
> 
> Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:
> 
> * [Laracasts Forums](https://laracasts.com/discuss)
> * [Laravel.io Forums](https://laravel.io/forum)
> * [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
> * [Discord](https://discordapp.com/invite/KxwQuKb)
> * [Larachat](https://larachat.co)
> * [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
> 
> However, this issue will not be locked and everyone is still free to discuss solutions to your problem!
> 
> Thanks.

You seem to have taken this issue as something like "I don't know how to use the framework". But it's not about it. It is about the specificity of the framework that might be fixed - and the framework would be more flexible and logical.
