### ISSUE TITLE
Str::snake() causes issues with ORM model mutators on columns with numbers in them.

### ISSUE THREAD

**Issue by rickmacgillis** [laravel/framework#28710]
- Laravel Version: 5.8.19
- PHP Version: 7.3.6
- Database Driver & Version: 10.3.11-MariaDB

### Description:
When trying to fetch database columns in Eloquent ORM models with mutated attributes, it uses Str::snake($match). However, when trying to use a mutator to access billing_address_line_2 when the row is changed into JSON, will cause Eloquent ORM to assume that we're looking for the attribute billing_address_line2 which doesn't exist. Snake casing in other situation always has an _ before the numbers, just as Laravel Spark did with the DB column name.

### Steps To Reproduce:
1. Install the default Laravel environment
2. Add a column for the `\app\User` model and call it `billing_address_line_2`.
3. Make a mutator to get and set the data as described in the docs. (The contents being changed is irrelevant.)
4. Create a row for the user.
5. JSONify the User model and examine the contents of the JSONification.
6. Notice that the value of that column is not passed through the mutator, and thus shows the original value from the DB. This is because of [`Str::snake()`](https://github.com/laravel/framework/blob/7db4308c0e01fc49631c432b8b1033426eb41a1e/src/Illuminate/Support/Str.php#L477) not placing an underscore before the number.

## Proposed Fix:
Change it to read `$value = static::lower(preg_replace('/(.)(?=[A-Z0-9])/u', '$1'.$delimiter, $value));`

This could cause breaking changes, so it might be prudent to make some kind of workaround for it. (Ex. Add an option in the configuration to snake case it the original way or the new way, but default to the original way.)

**Comment by driesvints** [comment]
Can you please post some code examples for the steps above?

**Comment by rickmacgillis** [comment]
Certainly.

1. In `\App\User`, add the following method.
```
public function getBillingAddressLine2Attribute(?string $value)
    {
    	return 'test';
    }
```
Also, make sure that `billing_address_line_2` isn't listed in the `$hidden` property on the model, and that the column exists in the DB.

2. Add a new user to the DB, and make sure to set the `billing_address_line_2` column to something other than `test`.
3. Open `php artisan tinker` in the console, and type the following lines. (I'll assume your user is ID 1 in the users table.)
```
Auth::loginUsingId(1);
json_encode(Auth::user());
```
You can also use:
```
json_encode(\App\User::where('id', 1)->first());
```
or
```
json_encode(\App\User::find(1));
```
Tinker will cache your environment, so be sure to only run it once the code and DB are set up as described above.

The output of that code will show `billing_address_line_2` set to the value you manually entered in the DB instead of `test` which is what our mutator returns.

**Comment by driesvints** [comment]
Unfortunately this is a limitation by the ORM because you cannot know if you need to target `billing_address_line_2` or `billing_address_line2` with `getBillingAddressLine2Attribute`. Numbers don't have casing so it's impossible to know which one to target. If we'd change the behavior for one the other one would be "broken" instead.

**Comment by rickmacgillis** [comment]
What's wrong with my solution with adding a config setting? Shouldn't it be up to the user to determine that behavior?

**Comment by driesvints** [comment]
@rickmacgillis that's a feature request and best discussed in the ideas repo.

**Comment by rickmacgillis** [comment]
@driesvints - Is there a workaround in the meantime?

**Comment by devcircus** [comment]
A macro on Str would be one way.

**Comment by rickmacgillis** [comment]
> A macro on Str would be one way.

@devcircus - Thanks for the suggestion. I just tried overriding `Str::snake()` using a macro, but unfortunately the macros are only capable of EXTENDING the class. That's because `Illuminate\Support\Traits\Macroable` relies on PHP's `__Call()` and `__callStatic()` methods. Given that `Str::snake()` exists as a method already, then it never has the opportunity to call the macro, and thus it's not like Laravel Spark's `Spark::swap()` functionality.

Anyone else have an idea? FYI, changing the column name isn't an option, as `billing_address_line_2` is part of Laravel Spark.

**Comment by rickmacgillis** [comment]
@driesvints - If I do a PR with the config setting version so it defaults to the standard behavior, are you willing to accept it?

**Comment by driesvints** [comment]
@rickmacgillis all PRs are done by @taylorotwell. I'm not sure tbh if a config is the proper approach for this. Seems overkill to me. Can't you rename the DB column?

**Comment by rickmacgillis** [comment]
@driesvints, it's part of Laravel Spark, so unfortunately that's not an option.
