### ISSUE TITLE
[5.8] Inconsistent return values between Redis limiters

### ISSUE THREAD

**Issue by wfeller** [laravel/framework#28729]
- Laravel Version: 5.8.19
- PHP Version: 7.3
- Database Driver & Version: PostgreSQL 11.3

### Description:
The Redis DurationLimiter doesn't return the result of the callback (https://github.com/illuminate/redis/blob/master/Limiters/DurationLimiter.php#L90) while the ConcurrencyLimiter does (https://github.com/illuminate/redis/blob/master/Limiters/ConcurrencyLimiter.php#L82)

Mostly wondering if that's the expected behaviour as I can work around this.

### Steps To Reproduce:
```php
// Returns true
Redis::throttle('key')->allow(100)->every(10)->then(function () {
    return 100;
});
```

```php
// Returns 100
Redis::funnel('key')->limit(100)->then(function () {
    return 100;
});
```

**Comment by driesvints** [comment]
Please fill out the full issue template.
