### ISSUE TITLE
Validate Field Required_with and empty or nullable

### ISSUE THREAD

**Issue by joerecra** [laravel/framework#28732]
I need to validate if contact is present, validate that contact.phone or contact.mobile will be present, one of them, and the other can be null or empty . But if contact is not present, doesnt validate contact (for people who is thinking about use present)

My request is this:

Request

`{
    "firstname":"Joe",
    "contact": {
        "mobile": "",
        "phone": {"number": "3313231", "annex": ""}
    }
}`

I've already tried:

`[
'contact' => 'sometimes|required',
'contact.phone' => 'required_with:contact|sometimes|required_without:contact.mobile',
'contact.phone.number' => 'required_without:contact.mobile|sometimes|max:20',
'contact.phone.annex' => 'sometimes|max:20',
'contact.mobile' => 'required_with:contact|required_without:contact.phone|max:20''
]`

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
