### ISSUE TITLE
UriValidator in Routing fails when url contains malformed utf8, even for fallback route

### ISSUE THREAD

**Issue by andyblackwell** [laravel/framework#28746]
- Laravel Version: 5.8
- PHP Version: 7.2

### Description:
If a url contains malformed utf8 then all routing regex fails, including the fallback route.
preg_match error `PREG_BAD_UTF8_ERROR`

https://github.com/laravel/framework/blob/55b7f40a19cab647e57063fc38905aff9cfa78e9/src/Illuminate/Routing/Matching/UriValidator.php#L17-L22

Mostly concerning for the fallback route that also uses regex underneath, where failing to match bypasses middleware which would have ran otherwise.
https://github.com/laravel/framework/blob/55b7f40a19cab647e57063fc38905aff9cfa78e9/src/Illuminate/Routing/Router.php#L225-L232

Action Items:
- Would be nice to surface these errors so they don't go unnoticed
- Refactor fallback route to have a special case that does not require a regex match

### Steps To Reproduce:
a url that contains `%E6%B5%B7` (works) vs `%E6%B5` (doesn't)

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by andyblackwell** [comment]
Is broken in 5.8 and in master

**Comment by driesvints** [comment]
What do these `%E6%B5%B7` and `%E6%B5` mean actually? I can't seem to find out if it's valid UTF-8.

**Comment by andyblackwell** [comment]
`%E6%B5%B7` is an encoded asian charater 海
if you only get part of that sequence like `%E6%B5` then it is malformed utf8 and triggers that silent `PREG_BAD_UTF8_ERROR` in `preg_match`

```
// in jacascript:
encodeURIComponent('海'); // => %E6%B5%B7
decodeURIComponent('%E6%B5%B7'); // => 海
decodeURIComponent('%E6%B5'); // => Uncaught URIError: URI malformed
```

**Comment by driesvints** [comment]
How do you trigger the `PREG_BAD_UTF8_ERROR` actually? I get a 404 which seems like the correct behavior to me.

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.
