### ISSUE TITLE
Eloquent/Model::withCount add string param

### ISSUE THREAD

**Issue by VokaMut** [laravel/framework#28745]
- Laravel Version: 5.8.21
- PHP Version: 7.2.18
- Database Driver & Version: MySQL Ver 14.14 Distrib 5.6.43

### Steps To Reproduce:
```
$post = Post::where('id', 123)
    ->withCount('comments')
    ->first();

is_int($post->comments_count); // false;
is_string($post->comments_count); // true
dump($posts->comments_count); // "10"
```
But if add to $casts
```
class Post extends Model
{
    $casts = ['comments_count' => 'integer'];
}

$post = Post::where('id', 123)
    ->withCount('comments')
    ->first();

is_int($post->comments_count); // true;
is_string($post->comments_count); // false
dump($posts->comments_count); // 10
```
But it is not correct to add this field to the $casts.

**Comment by staudenmeir** [comment]
This behavior is caused by your `pdo_mysql` driver.

Please see https://stackoverflow.com/a/20123337/4848587 for details.

**Comment by driesvints** [comment]
Heya, please see the link above.

**Comment by briangoins** [comment]
Ran across this in Laravel 6.x.

Shouldn't this still be an issue? I read the link in the comments, but from what I understand, `mysqlnd` isn't the only PHP-supported MySQL base library.

@driesvints
