### ISSUE TITLE
Logged in as User (browser), deleted this User in migration (CLI), refreshed the browser and see 728 queries to EloquentUserProvider.php

### ISSUE THREAD

**Issue by mattkomarnicki** [laravel/framework#28754]
- Laravel Version: 5.8.18
- PHP Version: 7.2.9-1+ubuntu18.04.1+deb.sury.org+1
- Database Driver & Version: 5.7.23-0ubuntu0.18.04.1 _(I use Laravel Homestead, default config)_

### Description:
It may be a rare edge case but what I did was:

1) In CLI I **successfully** created a User via migration via `php artisan migrate`.
2) I **successfully** logged as this User in a browser.
3) In CLI I **successfully** rolled back that migration via `php artisan migrate:rollback`.
4) I went back to the browser and refreshed the main page via `⌘+R`
5) Check the debugbar _(728 statements were executed, 725 of which were duplicated, 3 unique)_:

<img width="1664" alt="Screen Shot 2019-06-07 at 11 08 50" src="https://user-images.githubusercontent.com/9691376/59075586-bf19c880-8914-11e9-9e6d-30a4f5859ac4.png">

Normally I would blame myself for botched code, but debugbar points to `vendor` / `Illuminate` so maybe the culprit is somewhere within Laravel?

It goes back to normal when the session is obviously destroyed. I keep sessions in `SESSION_DRIVER=redis` and as soon as I purge Redis cache via my `./bin/cache_clear.sh`

```
#!/usr/bin/env bash

# Go to the directory of the script
cd "$(dirname "${BASH_SOURCE}")"
cd ..

php artisan clear-compiled

php artisan debugbar:clear
php artisan cache:clear
php artisan config:clear
php artisan route:clear
php artisan view:clear
```

it goes back to normal page that responds in a reasonable time.

### Steps To Reproduce:
Same as Description.

**Comment by sisve** [comment]
It's important to look into the entire stack trace. It's true that EloquentUserProvider is reading from the database in this case, but to answer _why_ we need to see who calls EloquentUserProvider.

**Comment by driesvints** [comment]
Do you get the same results when using Telescope?

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.
