### ISSUE TITLE
Laravel queue job complete incompatible with phpredis

### ISSUE THREAD

**Issue by raymondtri** [laravel/framework#28758]
- Laravel Version: 5.8.21
- PHP Version: 7.3.0
- Database Driver & Version: PHPRedis 

### Description:
When an event is fired, it is processed by redis, but when it is completed successfully, instead of being marked as completed, it goes back into the pool for re-processing (I think).

The broader symptom is that the event will log as completed from a worker, have its attempt count incremented, but will then be reprocessed (even if only a single worker is running).

### Steps To Reproduce:
Base laravel setup, use phpredis instead of predis, make an event and a listener, fire the event, watch as it is processed in a loop for all eternity.

**Comment by driesvints** [comment]
Can you create an app with the minimum amount of setup that would be required to reproduce this and upload it to Github? Please detail all the env setup required to reproduce the problem.

**Comment by raymondtri** [comment]
Hey @driesvints thanks for getting back.

So things got even more weird today. Now I am unable to replicate it on the base laravel. I know this isn't the spot for support, but the issue I am running into is that the ZREM json seems to be additionally serialized and the zadd json is not. Do you have any idea what could be causing this?

`1560445285.242989 [0 lua] "zadd" "queues:default:reserved" "1560445295" "{\"timeout\":null,\"id\":\"QkuKyiHJSNVO0FyGsXKE6gsgUrgUflxc\",\"data\":{\"command\":\"O:36:\\\"Illuminate\\\\Events\\\\CallQueuedListener\\\":7:{s:5:\\\"class\\\";s:31:\\\"App\\\\Listeners\\\\TestEventListener\\\";s:6:\\\"method\\\";s:6:\\\"handle\\\";s:4:\\\"data\\\";a:1:{i:0;O:20:\\\"App\\\\Events\\\\TestEvent\\\":1:{s:6:\\\"socket\\\";N;}}s:5:\\\"tries\\\";N;s:9:\\\"timeoutAt\\\";N;s:7:\\\"timeout\\\";N;s:6:\\\"\\u0000*\\u0000job\\\";N;}\",\"commandName\":\"Illuminate\\\\Events\\\\CallQueuedListener\"},\"displayName\":\"App\\\\Listeners\\\\TestEventListener\",\"maxTries\":null,\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"timeoutAt\":null,\"delay\":null,\"attempts\":128}"`

`1560445285.249663 [0 172.22.0.1:54708] "ZREM" "queues:default:reserved" "s:590:\"{\"timeout\":null,\"id\":\"QkuKyiHJSNVO0FyGsXKE6gsgUrgUflxc\",\"data\":{\"command\":\"O:36:\\\"Illuminate\\\\Events\\\\CallQueuedListener\\\":7:{s:5:\\\"class\\\";s:31:\\\"App\\\\Listeners\\\\TestEventListener\\\";s:6:\\\"method\\\";s:6:\\\"handle\\\";s:4:\\\"data\\\";a:1:{i:0;O:20:\\\"App\\\\Events\\\\TestEvent\\\":1:{s:6:\\\"socket\\\";N;}}s:5:\\\"tries\\\";N;s:9:\\\"timeoutAt\\\";N;s:7:\\\"timeout\\\";N;s:6:\\\"\\u0000*\\u0000job\\\";N;}\",\"commandName\":\"Illuminate\\\\Events\\\\CallQueuedListener\"},\"displayName\":\"App\\\\Listeners\\\\TestEventListener\",\"maxTries\":null,\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"timeoutAt\":null,\"delay\":null,\"attempts\":128}\";"`

**Comment by raymondtri** [comment]
I found the problem, there was a package registered extremely deeply and the issue was not with the laravel framework. Posting the fix though incase anyone runs into the same issue.

The longman/lodash package with igbinary serializer is not compatible with queue workers. The redis connection that laravel uses to add or work queues needs to have no redis serialization done to it. However the longman/lodash package does allow igbinary serialization for redis usages like sessions and caching.
