### ISSUE TITLE
Proposal: dynamic appends

### ISSUE THREAD

**Issue by Donny5300** [laravel/framework#28751]
Hi!

I ran into the issue with `appends`. When you use the appends property and set it hard coded in the model, every time the model is booted, the attributes of the appends will be casted. Sometimes you want to use a property of a model in a `getExampleAttribute` method. If that property isn't loaded, it is not required to load the property. This will cause a `null` result.

Sorry for the bad explanation, i've added 2 txt files as a example.

[original.txt](https://github.com/laravel/framework/files/3262266/original.txt)
[Dynamic appends.txt](https://github.com/laravel/framework/files/3262267/Dynamic.appends.txt)

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not for ideas, suggestions etc. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. You are able to open a ticket at https://github.com/laravel/ideas

Alternatively you are able to open a PR using the Contributions guidelines: https://laravel.com/docs/5.7/contributions#which-branch

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.

**Comment by driesvints** [comment]
@laurencei you maybe want to update that url there to https://laravel.com/docs/contributions#which-branch so it always goes to the current release :)

**Comment by laurencei** [comment]
@driesvints - thanks - updated my saved reply for future ones :)
