### ISSUE TITLE
FormRequest Custom Messages with Rule::

### ISSUE THREAD

**Issue by gofish543** [laravel/framework#28761]
Laravel Version: 5.8.21
PHP Version: 7.3.6
Description:
Within the FormRequest messages() function, any item using Laravel's internal Rules will have its message overridden by Laravel's message.

Below is an example...
```php
class RegisterRequest extends FormRequest {

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules() {
        return [
            'club_id' => [
                'required',
                'registration_code' => Rule::exists('clubs', 'id')->where('registration_code', 5))
            ],
        ];
    }

    public function messages() {
        return [
            'club_id.required' => 'He who laughs last didn’t get the joke', // Works
            'club_id.registration_code' => 'Invalid registration code for the specified club', // Fails
        ];
}
```
In the example above, if the club_id is not passed, the message ''He who laughs last didn’t get the joke' will be populated in the message bag
However, if the registration_code fails the resulting message will be 'The selected club id is invalid.' rather than the expected 'Invalid registration code for the specified club'.

**Comment by staudenmeir** [comment]
You can't (re)name rules like this.

As with `required`, you need to add the rule name to the message key:

```php
public function messages() {
    return [
        'club_id.required' => 'He who laughs last didn’t get the joke',
        'club_id.exists' => 'Invalid registration code for the specified club',
    ];          ^^^^^^^
}
```

**Comment by gofish543** [comment]
Oh ok. Thanks!
It would be nice if the documentation was more clear as to what to do with Rule:: cases.
