### ISSUE TITLE
getRouteKey Function not working

### ISSUE THREAD

**Issue by Jagadhissh** [laravel/framework#28764]
- Laravel Version: 5.7
- PHP Version: 7 2
- Database Driver & Version:mysql latest

### Description:

class Task extends Model
{

    public function getRouteKey()
    {
        return \Hashids::connection(Task::class)->encode($this->getKey());
    }

### Steps To Reproduce:
getRouteKey Function not working
getRouteKey Function not working laravel 5.7

**Comment by laurencei** [comment]
Laravel 5.7 is no longer supported. Please upgrade to 5.8 and see if the problem continues.

**Comment by Jagadhissh** [comment]
I tried in 5.6 also.... But doesn't working

**Comment by driesvints** [comment]
Hey @Jagadhissh, we don't support 5.6 and 5.7 anymore. Please refer to https://laravel.com/docs/5.8/releases#support-policy to know which versions we still support.
