### ISSUE TITLE
Blade - indenting from replaced content (@include etc) is not persisted

### ISSUE THREAD

**Issue by PrinsFrank** [laravel/framework#28767]
- Laravel Version: Any
- PHP Version: NA
- Database Driver & Version: NA

### Example:

Content of included.blade.php:
```
Line 1
Line 2
```

Conent of including file:
```
<html>
     @include('included')
</html>
```

Results in the following HTML:
```
<html>
     Line 1
Line2 </html>
```

An extra line at the end of the included file resurts in the following HTML:
```
<html>
     Line 1
Line2
</html>
```

It would be more readable to have the following HTML:
```
<html>
     Line 1
     Line2
</html>
```

**Comment by PrinsFrank** [comment]
I just opened a pull request where i implemented this for __includes__ only.
As this is my first time working on framework, i would like to know if this would be implemented if i fixed this for all replaced content or if that would be time wasted.

**Comment by ahinkle** [comment]
Probably the best you can do is have the includes on their own lines, and all the way on the left margin. It will won't be perfect, but it will help.

```
   <div>
@include('included')
   </div>
```

**Comment by PrinsFrank** [comment]
@ahinkle 

I agree that's the best workaround for now.
It's sad that there is no support for solving this in blade itself, as that's quite do-able (see pull-request).

**Comment by driesvints** [comment]
Closing this as the related PR was rejected.

**Comment by PrinsFrank** [comment]
It took me a while, but i made the pullrequest into a package! For anyone stumbling across this pullrequest, the package can be found here:

https://github.com/PrinsFrank/IndentingPersistentBladeCompiler
