### ISSUE TITLE
laravel curl error

### ISSUE THREAD

**Issue by jksdn** [laravel/framework#28760]
- Laravel Version: 5.8.21
- PHP Version: 7.3
- Database Driver & Version:

### Description:
![Screen Shot 2019-06-07 at 10 51 56 PM](https://user-images.githubusercontent.com/40340108/59130079-1e102980-8977-11e9-86b3-3a6e544069f2.png)

**Comment by laurencei** [comment]
Looks like a local error? Are you behind a firewall or proxy?

**Comment by jksdn** [comment]
@laurencei, When I try to create a new project, I get the above error;I don't use a proxy

**Comment by laurencei** [comment]
It works for me. It's something about your network, proxy or config...

I'll leave this ticket open for a few days and see if anyone else reports similar issues. But given this feature is used daily hundreds (?thousands) of times - I feel if there was a more widespread issue we'd know about it by now...

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
