### ISSUE TITLE
Timeout when serializing infinity

### ISSUE THREAD

**Issue by wvffle** [laravel/framework#28763]
- Laravel Version: 5.7
- PHP Version: 7.2
- Database Driver & Version: mysql

### Description:
I had a custom attribute accessor and after I tried to call `toArray()`  or `toJSON()` I was welcomed by the timeout error. I guess that laravel doesn't know how to serialize `INF`.

### Steps To Reproduce:
Add custom accessor to the `\App\User`

```php
public function getInfinityAttribute() {
  return INF;
}

protected $appends = [ 'infinity' ];
```

Call `$user->toArray()`;

**Comment by aqjw** [comment]
```INF``` does not matter. I think it's because of this.

**Comment by aqjw** [comment]
Have you tried to return a string?

**Comment by mfn** [comment]
Can't reproduce this with a 5.8 app of mine:
```
$ ./artisan tinker
Psy Shell v0.9.9 (PHP 7.2.17-1+ubuntu18.04.1+deb.sury.org+3 — cli) by Justin Hileman
>>> $u = new App\User;
=> App\User {#3846
     language: "en",
   }
>>> $u->toArray();
=> [
     "language" => "en",
     "infinity" => INF,
   ]
>>> ^D
$ ./artisan --version
Laravel Framework 5.8.21
```
I literally did the same thing you did:
- added the magic getter
- added `$appends`
- called `toArray`

**Comment by wvffle** [comment]
Hmm, I'm also returning it as a response, maybe that's the case?

**Comment by laurencei** [comment]
> Hmm, I'm also returning it as a response, maybe that's the case?

Can you post the actual code to reproduce this?

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
