### ISSUE TITLE
Conditional attribute in API Resource, evaluates value before checking condition if using another Resource in value

### ISSUE THREAD

**Issue by hsharghi** [laravel/framework#28774]
- Laravel Version: 5.8.18
- PHP Version: 7.2.9
- Database Driver & Version: MySQL 5.7.22

### Description:
Using API resource, an attribute should be included only when a certain condition is true. If the condition is true, another API Resource generated as the value. But even the condition is not `true` the value is getting calculated. 

```php

    public function toArray($request)
    {
        $isOwner = ($this->resource->owner_id == $ownerId);

        return [
            "productId" => $this->resource->product_id,
            "quantity" => $this->resource->quantity,
            "price" => $this->resource->price,
            "ownerInfo" => $this->when($isOwner, ProductOwnerResource::make($this->resource)),
        ];
    }

// ProductOwnerResource __construct method is getting called 
// before when() method
```

But if I change the value to a closure the condition check will occurs first and the value will not be evaluated.

```php

    public function toArray($request)
    {
        $isOwner = ($this->resource->owner_id == $ownerId);

        return [
            "productId" => $this->resource->product_id,
            "quantity" => $this->resource->quantity,
            "price" => $this->resource->price,
            "ownerInfo" => $this->when($isOwner, function() {
                        return ProductOwnerResource::make($this->resource);
            }),
        ];
    }

// ProductOwnerResource __construct method is not getting called
// at all since $isOwner is false
```

### Steps To Reproduce:
Create two API Resources and use one of them in the others with `when` condition.

**Comment by staudenmeir** [comment]
That's how PHP works and Laravel can't possibly prevent the evaluation. You have to use a closure.

**Comment by hsharghi** [comment]
> That's how PHP works and Laravel can't possibly prevent the evaluation. You have to use a closure.

So if I don't use closure, every `when($condition, $value)` statement, evaluates the `$value` twice? Once when reading methods arguments and then once when returning `value($value)` ?

**Comment by staudenmeir** [comment]
No, only once. `$value` is evaluated and then passed as an argument.

`when()` behaves like any other method in PHP.
