### ISSUE TITLE
[Router] auth routes with customize modules request

### ISSUE THREAD

**Issue by quachtinh761** [laravel/framework#28776]
Hi mates, currently, we're developing a website and intending to use existing Auth::routes(). But the problem is the namespace, i mean we have to create the sub-module in our modules. So, now i request to create an option for user to custom the module.
Example:
```
Auth::routes(array(
    'register' => false,
    'module' => 'Modules\AnyModule\Controllers'
));
```
Thanks in advanced.

**Comment by quachtinh761** [comment]
So sorry, i can not create and push a new branch to create PR. Sorry for this inconvenient.

**Comment by sisve** [comment]
@quachtinh761 You can fork the entire framework repository into your own GitHub account, and then create the branches there. When you create a PR you can choose to use your own fork as the source for the PR.

Are you sure about the changes, or do you need to discuss them first in https://github.com/laravel/ideas or any chat like Slack of Discord?

**Comment by quachtinh761** [comment]
@sisve thanks for your response. It will be great if we can discuss more about this. Can we do chat more on Slack? Thanks

**Comment by sisve** [comment]
You can register for the Larachat slack at https://larachat.co/

**Comment by quachtinh761** [comment]
Got it. Thanks for you help @sisve
