### ISSUE TITLE
Where after WhereNotIn gives weird result

### ISSUE THREAD

**Issue by Peckerd** [laravel/framework#28772]
Hi,

I use Laravel 5.8 as an api backend for a Vuejs frontend. I have an endpoint that fetches tasks related to the group the user is in.

This is my code:
```php
public function listUserGroups(Request $request, User $user) {
	$filters = json_decode($request->filters);
	$closedStatuses = TaskStatus::whereIn('task_statuses.name->en', ['done'])
                        ->get()->toArray();
	
	$tasks = Task::with(['priority', 'group', 'assignee', 'status'])
         ->join('task_statuses', 'tasks.status_id', '=', 'task_statuses.id')
         ->where('group_id', '=', 6)
         ->whereNotIn('tasks.status_id', $closedStatuses)
         ->select('tasks.*')
         ->orderBy('task_statuses.sequence', 'asc');
	
	return TaskResource::collection($tasks->paginate($request->per_page));
}
```

This gives the correct result and produces these queries:
```sql
SELECT count(*) as aggregate
FROM `tasks` inner join `task_statuses`
         on `tasks`.`status_id` = `task_statuses`.`id` 
WHERE `group_id` = '6' 
and `tasks`.`status_id` not in ('6') 
and `tasks`.`deleted_at` IS NULL;

SELECT `tasks`.* 
FROM `tasks` inner join `task_statuses` 
         on `tasks`.`status_id` = `task_statuses`.`id` 
WHERE `group_id` = '6' 
         and `tasks`.`status_id` not in ('6') 
         and `tasks`.`deleted_at` IS NULL 
ORDER BY `task_statuses`.`sequence` ASC 
LIMIT 10 offset 0;
```

But if I change the order of the where clauses and put the whereNotIn first, like this:
```php
$tasks = Task::with(['priority', 'group', 'assignee', 'status'])
         ->join('task_statuses', 'tasks.status_id', '=', 'task_statuses.id')
         ->whereNotIn('tasks.status_id', $closedStatuses)
         ->where('group_id', '=', 6)
         ->select('tasks.*')
         ->orderBy('task_statuses.sequence', 'asc');
```

I produce this query (it's the where clause on the group_id that's wrong) and get zero results:
```sql
SELECT count(*) as aggregate
FROM `tasks` inner join `task_statuses`
         on `tasks`.`status_id` = `task_statuses`.`id` 
WHERE `tasks`.`status_id` not in ('6')
         and `group_id` = 'done'
         and `tasks`.`deleted_at` IS NULL;
```

I don't think I'm doing anything wrong, but do correct me if I do.

**Comment by staudenmeir** [comment]
> I produce this query

Where do you see this query? In the [debugbar](https://github.com/barryvdh/laravel-debugbar)?

What's the result of `dd($tasks->getBindings());`?

**Comment by staudenmeir** [comment]
The issue is caused by `$closedStatuses`: It contains the *whole* models with all their attributes. That's why `'done'` appears in the query.

The array can only contain the `id` values:

```php
$closedStatuses = TaskStatus::whereIn('task_statuses.name->en', ['done'])->pluck('id');
```

**Comment by Peckerd** [comment]
I changed it and it works every time now, thanks a lot!

I was focussing on the wrong piece of code it seems. But I still find the outcome strange, because it's always correct or always wrong, depending on the order of the were and whereNotIn.

I thought it was some eloquent magic that would always take the ID field, if nothing else was specified, since it seemed to work in other endpoints.

Anyways, many thanks.

**Comment by staudenmeir** [comment]
The first query only works, when `whereNotIn()` is the *last* constraint.

If you append `->where('foo', 'bar')`, you get `[...] and foo = 'done'`.
