### ISSUE TITLE
Doing migrations from path that contains special chars

### ISSUE THREAD

**Issue by colorful-bubbles** [laravel/framework#28775]
- Laravel Version: 5.8.19
- PHP Version: 7.3.0
- Database Driver & Version: mariadb 10.4

### Description:
My local Laravel application path contains some special chars (spaces and square brackets).
When i try to run migrations from that path it keeps saying "Nothing to migrate". Providing exact path to the single .php migration file makes it work fine. The problem occurs when we want it to scan the folder by itself.

### Possible solution:
After doing an investigation I've found out it's the path causing the problem. More specifically passing such path to **glob()** method makes it fail. A cross-platform fix should be surrounding each special char by "[" and "]", ex.: "/home/a nice folder/" becomes "/home/a[ ]nice[ ]folder/".
I've made 2 small changes to fix that behaviour:

1. A new method in **\Illuminate\Filesystem\Filesystem**:
```
    /**
     * Escapes special characters in path for glob.
     *
     * @param  string  $path
     * @return string
     */
    public function escapeGlobPath($path)
    {
        return preg_replace('/([\s!"#&\\\'\[\]()*?+{}|@])/', '[\\\${1}]', $path);
    }
```

2. Change in **\Illuminate\Database\Migrations\Migrator**:
```
    public function getMigrationFiles($paths)
    {
        return Collection::make($paths)->flatMap(function ($path) {
            return Str::endsWith($path, '.php') ? [$path] : $this->files->glob($this->files->escapeGlobPath($path).'/*_*.php');
        })->filter()->sortBy(function ($file) {
            return $this->getMigrationName($file);
        })->values()->keyBy(function ($file) {
            return $this->getMigrationName($file);
        })->all();
    }
```

I've changed this part:
```
$this->files->glob($path.'/*_*.php')
```
To this:
```
$this->files->glob($this->files->escapeGlobPath($path).'/*_*.php')
```

### Steps To Reproduce:
1. Put Laravel in a folder containing spaces or square brackets in name, ex.: **/home/a nice folder/**
2. Create a migration file.
3. Run **php artisan migrate**
4. Expect "Nothing to migrate." message.

I guess I could have commited that fix myself, somehow, but right now I don't really have time to learning how to contribute to Laravel code, so please forgive me :)
Also I hope I haven't duplicated such issue, tried to find existing one but with no luck.

**Comment by laurencei** [comment]
why do you have spaces in your folder names? I feel that's just going to cause more problems than its worth.

just underscore them like /home/a_nice_folder/

**Comment by colorful-bubbles** [comment]
I can not rename folders and that's not the solution (I'd rather call it bypassing the problem).
There are only 2 places where ->glob() is used in Framework (at least that's what my IDE says). One is the migration stuff and the other is view:clear command.

In case if you want it to stay broken there should be a clear statement in documentation that Laravel should not be installed in path containing spaces and characters like *'"[](){} etc.

**Comment by laurencei** [comment]
> In case if you want it to stay broken ...

I'm not saying it should stay broken - i'm just saying that folders with a "space" are likely to cause these strange edge cases.

**Comment by colorful-bubbles** [comment]
Many CLI / artisan commands that I use works just fine, the problem is only with migrations (and maybe with clearing the view cache). PHPUnit also works fine with such paths.

You are right, there may be more problems that I/we haven't find yet. Having migrations fixed will make it one problem less though. I and other people using these odd paths would be grateful for that :)

**Comment by driesvints** [comment]
@colorful-bubbles This might be something you want to avoid like @laurencei is saying. It's usually not wanted to have spaces in your directory names. Try to always use readable characters. I know this isn't much help in your situation but it's probably not something we're going to support soon.
