### ISSUE TITLE
view.finder is not a singleton

### ISSUE THREAD

**Issue by denjaland** [laravel/framework#28786]
- Laravel Version: 5.8.20
- PHP Version: 7.2.2

### Description:
For localisation purposes, we want to make use of the new app('view.finder')->setPaths option.  We have our templates set up per locale, and when our queue is sending an email to a user that talks language X, we need to set the paths in the Notification to make sure the email is being dispatched in the user's language.

I just noticed on https://github.com/laravel/framework/blob/5.8/src/Illuminate/View/ViewServiceProvider.php#L76 however that view.finder is no singleton, so we get a new instance when calling app('view.finder'), which I believe renders this useless.

Is there a reason why this is no singleton?

**Comment by denjaland** [comment]
(FYI: my current workaround is now to get the finder from app('view'), set the paths there, and then update the finder on app('view') again...)

**Comment by driesvints** [comment]
AFAIK it's because you probably want different view finder instances in different situations in the same request. Think multiple view locations (packages, app, etc). There's btw nothing stopping you from wrapping one instance in a singleton yourself.
