### ISSUE TITLE
Paginate shows duplicate numbers

### ISSUE THREAD

**Issue by preshan** [laravel/framework#28789]
- Laravel Version: 5.8.19
- PHP Version:7.1.23
- Database Driver & Version:

### Steps To Reproduce:View paginate with more than 10 numbers.
![Screen Shot 2019-06-11 at 9 42 29 AM](https://user-images.githubusercontent.com/10842407/59243410-82f4a980-8c2d-11e9-8e8f-e0f3d5bcfea5.png)

**Comment by staudenmeir** [comment]
Please post your paginated query.

**Comment by preshan** [comment]
`{!! $products->setPath(url("store/$category->slug"))->onEachSide(1)->links() !!}`

**Comment by staudenmeir** [comment]
`onEachSide()` only works properly with numbers > 2.

**Comment by preshan** [comment]
is there a way to get 1 on each side?

**Comment by staudenmeir** [comment]
Not that I know of.

**Comment by laurencei** [comment]
> onEachSide() only works properly with numbers > 2.

Should we throw an error or something if 1 is given?

**Comment by staudenmeir** [comment]
#25580
#27352

**Comment by ccdilan** [comment]
Same issue here. It is better we have a proper solution from next version update.

**Comment by driesvints** [comment]
It's not feasible to allow numbers lower than two. This has been brought up quite a bit in the past. Please refer to the issues above.

**Comment by cvaize** [comment]
Offered here is a hack that will fix the problem of: 
1) `php artisan vendor:publish --tag=laravel-pagination`
2) Insert at the beginning of the document  `resources/views/vendor/pagination/bootstrap-4.blade.php` 
this code
`<?php
if(isset($paginator->onEachSide) && $paginator->onEachSide === 1 && $paginator->currentPage() === 3)
{
	unset($elements[1]);
	unset($elements[2][2]);
}
?>`
![image](https://user-images.githubusercontent.com/26907947/59607624-23b2ff80-912d-11e9-9789-bddef1bfefe5.png)
![image](https://user-images.githubusercontent.com/26907947/59607695-40e7ce00-912d-11e9-90cf-028be8737f9f.png)

**Comment by cvaize** [comment]
If there are not enough digits, specify `onEachSide(2)` or `onEachSide(3)`and change the output values as you like. For small and middle projects this can be used.

**Comment by cvaize** [comment]
I've handled all the exceptions, I'll use that in production.
[Link on Gist](https://gist.github.com/cvaize/f12c0d5bcd8eb09bd7fc3e7f8fb4c6c3)
