### ISSUE TITLE
Cannot login to my live application, no logs on laravel.log

### ISSUE THREAD

**Issue by haydi80** [laravel/framework#28780]
Hello,

I am developing a Laravel application with login page, I am using Laravel 5.4. Locally everything works fine.
After deploying, I adjusted the env file and filled in the database connection information.

APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=myapp.nl

DB_CONNECTION=mysql
DB_HOST=db_host_name.nl
DB_PORT=3306
DB_DATABASE=db_name
DB_USERNAME=user_name
DB_PASSWORD=password

When go to myapp.nl, I get the login page, I filled in the login and password (that already exist on users table on my db_name). After that, the login and password fields got directly empty, I fill them in again, then I get:

Whoops, looks like something went wrong.

(1/1) TokenMismatchException
--
in VerifyCsrfToken.php line 68

And nothing is logged into storage/logs/laravel.log

I hope you can help me get it work..
Thanks in advance!

**Comment by Shizzen83** [comment]
Did you think about including a CSRF token into your authentication form?

https://laravel.com/docs/5.4/csrf#csrf-introduction

`VerifyCsrfToken` is a core middleware which cancels any form request without a valid token.

**Comment by haydi80** [comment]
{{ csrf_field() }} already exists in my authentication form..
And I don't get the VerifyCsrfToken the first time I try to log in. So when I fill in the login, the fileds become empty and after trying again, I get the VerifyCsrfToken error.. Strange!

**Comment by ahinkle** [comment]
Try the community support channels:

- [Laravel Discord](https://discordapp.com/invite/mPZNm7A)
- [laracasts.com/discuss](https://laracasts.com/discuss)
- [laravel.io/forum](https://laravel.io/forum)

**Comment by haydi80** [comment]
Ok ahinkle, thank you, I'll try it!
