### ISSUE TITLE
SQLSTATE[HY000]: General error: 1005 Can't create table `vanila`.`#sql-1d4a_1e`

### ISSUE THREAD

**Issue by cookiesze** [laravel/framework#28793]
Illuminate\Database\QueryException  : SQLSTATE[HY000]: General error: 1005 Can't create table `vanila`.`#sql-1d4a_1e` (errno: 150 "Foreign key constraint is incorrectly formed") (SQL: alter table `profiles` add constraint `profiles_user_id_foreign` foreign key (`user_id`) references `users` (`id`))

**Comment by cookiesze** [comment]
PLZ Help

**Comment by mfn** [comment]
It may be that the `users.id` and the` profiles.user_id` don't have the same data type, e.g. int vs. bigint.

**Comment by cookiesze** [comment]
Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `custom_properties` json not null, `responsive_images` json not n' at line 1 (SQL: create table `media` (`id` bigint unsigned not null auto_increment primary key, `model_type` varchar(191) not null, `model_id` bigint unsigned not null, `collection_name` varchar(191) not null, `name` varchar(191) not null, `file_name` varchar(191) not null, `mime_type` varchar(191) null, `disk` varchar(191) not null, `size` int unsigned not null, `manipulations` json not null, `custom_properties` json not null, `responsive_images` json not null, `order_column` int unsigned null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci')

**Comment by cookiesze** [comment]
> It may be that the `users.id` and the` profiles.user_id` don't have the same data type, e.g. int vs. bigint.

Thank @mfn

**Comment by bsam2019** [comment]
Try using $table->id() instead of $table->increament('is') in your migrations

**Comment by muhammadZaahid** [comment]
change **bigInteger** to **unsignedBiginteger**

**Comment by khateeboveskey** [comment]
Having the same problem while the are with the same data type
2023_07_30_052654_create_communities_table.php : `$table->id();`
2023_04_30_100325_add_community_id_to_photos_table.php : `$table->foreignId('community_id')->nullable()->constrained()->cascadeOnDelete();`


---

Laravel says
```
SQLSTATE[HY000]: General error: 1005 Can't create table `medalah`.`photos` (errno: 150 "Foreign key constraint is incorrecint `photos_community_id_foreign` foreign key (`community_id`) references `communities` (`id`) on delete cascade)
```
