### ISSUE TITLE
syntax error, unexpected '?', expecting variable (T_VARIABLE)

### ISSUE THREAD

**Issue by harveyelsisura** [laravel/framework#28807]
- PHP Version: 7.3.5
- Database Driver & Version:

### Description:
Having this error during deployment|

Parse error: syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in /home/mex10ho8/laravel-crud/vendor/symfony/var-dumper/Resources/functions/dump.php on line 18

### Steps To Reproduce:
Deploying repository, upload to created folder at cpanel while the public folder is in public_html. The index.php inside the public folder was changed to locate the autoload. But after that i face the issue in the descriptio

**Comment by kylekatarnls** [comment]
The title of your issue does not match the description is it unexpected `'?'` or `'.'`?

Can you check the Laravel version you gave (I really doubt you use 2.1.0, this tag don't even exist on packagist now).

And as you mention it's a deployment issue, we need your deployment process (Steps To Reproduce), the complete log to see when the error occurs. And ensure the PHP version you give is really the one of the PHP instance that execute the deployment.

**Comment by ahinkle** [comment]
Try the community support channels:

- [Laravel Discord](https://discordapp.com/invite/mPZNm7A)
- [laracasts.com/discuss](https://laracasts.com/discuss)
- [laravel.io/forum](https://laravel.io/forum)

**Comment by kylekatarnls** [comment]
I do not mean to call you a liar @harveyelsisura but if you get this error with [the current version of functions/dump.php on line 18](https://github.com/symfony/var-dumper/blob/master/Resources/functions/dump.php#L18), then you're not running PHP 7.3.5, you're running a version lower than PHP 7.1. And I'm pretty sure you installed your packages (run composer install/update) with a PHP >= 7.1.

So I insist: you need to check **ALL** your environments, you need to run the same PHP version on your personal computer (I mean the machine you use to install dependencies) and on your hosting server. Be careful, multiple versions of PHP can be installed on each machine and different versions can be run when you load page via Apache/nginx/etc. or when you run PHP from the console.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.

**Comment by harveyelsisura** [comment]
> I do not mean to call you a liar @harveyelsisura but if you get this error with [the current version of functions/dump.php on line 18](https://github.com/symfony/var-dumper/blob/master/Resources/functions/dump.php#L18), then you're not running PHP 7.3.5, you're running a version lower than PHP 7.1. And I'm pretty sure you installed your packages (run composer install/update) with a PHP >= 7.1 and loading your website with a PHP < 7.1.
> 
> So I insist: you need to check **ALL** your environments, you need to run the same PHP version on your personal computer (I mean the machine you use to install dependencies) and on your hosting server. Be careful, multiple versions of PHP can be installed on each machine and different versions can be run when you load a page via Apache/nginx/etc. or when you run PHP from the console.

You can try it for yourself this is the https://github.com/harveyelsisura/Laravel-CRUD, Then tell me if i dont check my environment very well :)

**Comment by harveyelsisura** [comment]
![image](https://user-images.githubusercontent.com/38097181/59319927-07fbc380-8cff-11e9-8828-390c49d86a04.png)

**Comment by harveyelsisura** [comment]
![image](https://user-images.githubusercontent.com/38097181/59319948-1518b280-8cff-11e9-9823-48877cb66741.png)

**Comment by harveyelsisura** [comment]
Thank you @kylekatarnls, i check my cpanel php version and its set to 5.5,
