### ISSUE TITLE
if (method_exists(self::class, $key)) {

### ISSUE THREAD

**Issue by t9221823420** [laravel/framework#28814]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Database Driver & Version:

### Description:

 have to be "if (method_exists( static::class, $key)) {" - because of inheritance produce an issue

**Comment by laurencei** [comment]
Hi, please fill in the template with all the required details, and you'll need to provide a clearer description of the issue for us to look at.

Thanks.
