### ISSUE TITLE
HasEvents trait is not registering the forceDeleted event

### ISSUE THREAD

**Issue by Abouhassane** [laravel/framework#28823]
- Laravel Version: 5.8

### Description:
I think the HasEvents trait needs to listen for the forceDeleted event just is the case for the other events ('retrieving', 'deleted'.....)

`public static function forceDeleted($callback){`
        
> `static::registerModelEvent('forceDeleted', $callback);`

`}`

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!
