### ISSUE TITLE
 Declaration of Illuminate\Foundation\Testing\Assert::assertArraySubset($subset, $array, bool $checkForObjectIdentity = false, string $message = ''): void should be compatible with PHPUnit\Framework\Assert::assertArra ySubset($subset, $array, $strict = false, $message = '')

### ISSUE THREAD

**Issue by xliyq** [laravel/framework#28827]
- Laravel Version: 5.8.21
- PHP Version: 7.1
- Database Driver & Version: doesn't matter

### Description:
 Declaration of Illuminate\Foundation\Testing\Assert::assertArraySubset($subset, $array, bool $checkForObjectIdentity = false, string $message = ''): void should be compatible with PHPUnit\Framework\Assert::assertArra ySubset($subset, $array, $strict = false, $message = '')

**Comment by devcircus** [comment]
PHPUnit updated the signature to that function in [version 7.4](https://github.com/sebastianbergmann/phpunit/blob/7.4.0/src/Framework/Assert/Functions.php#L88), so you must be using [PHPUnit <= 7.3.5](https://github.com/sebastianbergmann/phpunit/blob/7.3.5/src/Framework/Assert/Functions.php#L87).  Laravel 5.8 [requires at least PHPUnit 7.5](https://github.com/laravel/framework/blob/5.8/composer.json#L88).

**Comment by xliyq** [comment]
Laravel 5.8 How to solve this problem

**Comment by driesvints** [comment]
Please see the reply by @devcircus and update to PHPUnit 7.5
