### ISSUE TITLE
Date in method create is sometimes adding or subsracting a day.

### ISSUE THREAD

**Issue by lherreranetlink** [laravel/framework#28822]
- Laravel Version: 5.4.36
- PHP Version: 7.1.16
- Database Driver & Version:

### Description:
Hello Guys, I'm facing a really weir issue using the method `create` and a model I just created.
Turns out that when I create a record with this information:

![Captura de pantalla 2019-06-12 a la(s) 12 06 53](https://user-images.githubusercontent.com/30661966/59371455-ae999180-8d0a-11e9-8f13-f57e6153c6e6.png)

You can clearly see that the begining_date of my record is 2019-06-13 and the end date is 2019-06-29.

And now, I'll show you what it shows when I do `dd()` on  the request object

![Captura de pantalla 2019-06-12 a la(s) 12 09 45](https://user-images.githubusercontent.com/30661966/59371571-03d5a300-8d0b-11e9-97df-3ca40231f280.png)

Everything seems fine, doesn't it? but then, what happens when I actually create the record in the database?

![Captura de pantalla 2019-06-12 a la(s) 12 11 24](https://user-images.githubusercontent.com/30661966/59371653-3da6a980-8d0b-11e9-86df-2f37237ad16c.png)

You can clearly see that a day was substracted from the begining and end dates that i showed you before.

And at last, when I make a query of the records, the dates are different from the ones in the database

![Captura de pantalla 2019-06-12 a la(s) 12 13 09](https://user-images.githubusercontent.com/30661966/59371742-79417380-8d0b-11e9-8190-43295f1b787d.png)

Today earlier, it was showing the same behaviour, but instead of substracting, the day in the dates were increasing by one.

I'll show my class so that you see that I don't have any accesor that is affecting the result of the fields.

`class Coupon extends Model
{
    protected $fillable = [
        'name',
        'key',
        'amount',
        'type',
        'begining_date',
        'expiration_date',
        'status',
    ];

    /**
     * Scope for filtering only the active records
     *
     *
     * @param String $query
     * @return QueryBuilder
    */
    public function scopeActive($query)
    {
        return $query->where('status', 1);
    }

    //ACCESORS AND MUTATORS

    /**
     * Get the type attribute according to its user-friendly value
     *
     *
     * @param String $type
     * @return String
    */
    public function getTypeAttribute($type)
    {
        return $type == 0 ? 'Porcentaje de Descuento' : 'Monto';
    }

    /**
     * Get the status attribute according to its user-friendly value
     *
     *
     * @param String $status
     * @return String
    */
    public function getStatusAttribute($status)
    {
        return $status == 1 ? 'Activo' : 'Inactivo';
    }

    /**
     * Convert all the letters of the key to uppercase
     *
     *
     * @param String $key
    */
    public function setKeyAttribute($key)
    {
        $this->attributes['key'] = strtoupper($key);
    }
}
`

**Comment by 570studio** [comment]
At first glance, this **might** be a timezone issue, check to be sure the proper timezone is set in your `config/app` file. 

Also, [this article](https://javorszky.co.uk/2016/06/06/today-i-learned-about-mysql-and-timezones/) explains some other timezone issues that may cause problems. Even if this isn't the issue, it's interesting to take a deeper dive into how timezones work (and why they may not work the way you thought).

**Comment by laurencei** [comment]
As @570studio said, most likely cause is a timezone issue. Make sure both your application and database are using `UTC` to avoid these types of issues.

Also - please upgrade to Laravel 5.8, as 5.4 is not supported anymore.

**Comment by lherreranetlink** [comment]
@570studio  @laurencei  I did the query on MySQL CLI and it shows correct results. I just remembered that I updated my Database Manager this past Monday. I'm trying to do the same query in the same database manager (the previous version, I'm in my other PC) and it looks OK. There must have been some mistakes in the last realease of the program I usedfor managing my databases.
