### ISSUE TITLE
php artisan migrate improvement

### ISSUE THREAD

**Issue by javierrodenas** [laravel/framework#28839]
Hello! I have been working for some time with Laravel and I would like to know if there is a faster system to know the migrations that are still to be executed. I would like not to have all the migrations with "php artisan migrate:status", because it consumes a lot of time on a server, instead having only the "remainings migrations" would be great and faster. (f.e "php artisan migrate:last")

What would you think of a new functionality like that?

Thank you in advance.

**Comment by JayBizzle** [comment]
https://github.com/erjanmx/laravel-migrate-check

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by chriskonnertz** [comment]
@javierrodenas I think you should ask this here: https://github.com/laravel/ideas
