### ISSUE TITLE
Laravel 5.2: Class log does not exist in /vendor/laravel/framework/src/Illuminate/Container/Container.php:734

### ISSUE THREAD

**Issue by shafeeQuinin** [laravel/framework#28835]
- Laravel Version: 5.2
- PHP Version: 7.0
- Database Driver & Version: Mysql

### Description:

I had to clear config and cache, I ran into the following exception :

`PHP Fatal error: Uncaught ReflectionException: Class log does not exist in html/project/bootstrap/cache/compiled.php:1355`

I removed bootstrap/compiled.php and ran `php artisan clear-compiled`, Then the exception got changed a little bit.

`Class log does not exist in /html/project/vendor/laravel/framework/src/Illuminate/Container/Container.php:734`

Steps i took to solve it :

- Checked env for spaces and syntax errors, Which had a blank space and i removed it, but still my php artisan commands are not working.

- Ran composer update | Still not working

- Some people associate the error with mbstring and php-mysql extensions which i both have.

- Tried composer dumpautoload

**What am i missing, How should be done ?**

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by devcircus** [comment]
In the vast majority of cases, the cause of this error is syntax errors in config files.

**Comment by OzanKurt** [comment]
Thanks @devcircus, actually helped.

**Comment by guoshuaiping** [comment]
Thanks @devicus，actually helped！！！
