### ISSUE TITLE
EnvironmentDetector doesn't parse options separated with a space

### ISSUE THREAD

**Issue by matt-allan** [laravel/framework#28831]
- Laravel Version: 5.8.21
- PHP Version: 7.3.5
- Database Driver & Version: N/A

### Description:

The Symfony console component that is used by the Artisan console [allows separating option names and values with either a space or an equals (`=`) sign](https://symfony.com/doc/current/components/console/console_arguments.html). For example:

```
$ php artisan serve --port=9090 
Laravel development server started: <http://127.0.0.1:9090>
$ php artisan serve --port 9090 
Laravel development server started: <http://127.0.0.1:9090>
```

However, the `--env` option is only parsed correctly if you use an equals sign. If you use a space `app()->environment()` will return false.

This inconsistency is pretty confusing and difficult to debug. If you dump `$this->option('env')` in a command it will return the expected value but `$app()->environment()` will return false.

### Steps To Reproduce:

1. Pass the `--env` flag to `tinker`, i.e. `php artisan tinker --env testing
2. Execute `app()->environment()` in the tinker shell

```
$ php artisan tinker --env=testing
Psy Shell v0.9.8 (PHP 7.3.5 — cli) by Justin Hileman
>>> app()->environment()
=> "testing"
>>> 
```

```
$ php artisan tinker --env testing                                                                                                                                     
Psy Shell v0.9.8 (PHP 7.3.5 — cli) by Justin Hileman
>>> app()->environment()
=> false
>>> 
```

This appears to be happening because the environment detector uses `$_SERVER['argv']` and  `$_SERVER['argv']` splits the options into two separate array elements if you use a space instead of an equals sign, and the `EnvironmentDetector` [expects a single element](https://github.com/laravel/framework/blob/f0448d4df91dcec7c49b580d3fb96c21523c3b74/src/Illuminate/Foundation/EnvironmentDetector.php#L51) to contain both the name and the value.

```
$ php artisan tinker --env testing                                                                                                                                     
Psy Shell v0.9.8 (PHP 7.3.5 — cli) by Justin Hileman
>>> $_SERVER['argv']
=> [
     "artisan",
     "tinker",
     "--env",
     "testing",
   ]
```

```
$ php artisan tinker --env=testing                                                                                                                                    
Psy Shell v0.9.8 (PHP 7.3.5 — cli) by Justin Hileman
>>> $_SERVER['argv']
=> [
     "artisan",
     "tinker",
     "--env=testing",
   ]
```

**Comment by driesvints** [comment]
Thanks for reporting. Welcoming any help with this.
