### ISSUE TITLE
connection overrides by parent

### ISSUE THREAD

**Issue by tim72117** [laravel/framework#28843]
- Laravel Version: 5.8.23
- PHP Version: 7.1.10
- Database Driver & Version: sqlsrv

### Description:
i use belongsTo relation, two model Post and Comment, Comment is belongs to Post, Post model use default connection, Comment  model set other connection, when get Post from Comment, Post's connection will set to Comment's connection

### Steps To Reproduce:
```
class Post extends Eloquent
{    
}

class Comment extends Eloquent
{
    protected $connection = 'other';

    public function post()
    {
        return $this->belongsTo('Post');
    }
}
$comment->post()->exists();
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by crhg** [comment]
I also encounterd this bug.

Workaround: Explicitly specify the connection to use with $connection in the model class. Then this behavior will not occur.
