### ISSUE TITLE
Paging method, when calculating total, does not pass $columns

### ISSUE THREAD

**Issue by tengfei31** [laravel/framework#28844]
- Laravel Version: 5.8.8
- PHP Version: 7.1.19
- Database Driver & Version:

### Description:
Function paginate, when calculating total, no $columns are passed. When I paginate parameters, the function getCountForPagination () does not pass $columns. Please take a look at it.

![image](https://user-images.githubusercontent.com/15308102/59503380-d3406580-8ed2-11e9-97f7-e3a3443d8ee7.png)
![image](https://user-images.githubusercontent.com/15308102/59503388-d89db000-8ed2-11e9-8520-e39c4ad9d0d2.png)
![image](https://user-images.githubusercontent.com/15308102/59503394-dc313700-8ed2-11e9-9143-6121f06b7ff4.png)

**Comment by driesvints** [comment]
Hmm, I'm not sure actually. For the query builder they are passed in and when I add it in the Eloquent builder myself the test suite still passes. So maybe we could add this in but I'm not sure what the side effects would be.

https://github.com/laravel/framework/blob/02d242212348bddd048702f5dee8dab693ac830b/src/Illuminate/Database/Query/Builder.php#L2141

@staudenmeir can you see any downsides to passing the columns to the count query?

**Comment by staudenmeir** [comment]
This doesn't work: #23259

Why do you want the count query to include the selected columns?

**Comment by tengfei31** [comment]
Perhaps the user wants to compute by column，If it's of no use, you can ignore him. thanks

**Comment by staudenmeir** [comment]
What's a real-life example where you would want to use `count(column)` instead of `count(*)`?

The results can only be different if `null` values are involved: https://stackoverflow.com/a/3003533/4848587

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.

**Comment by driesvints** [comment]
FYI, I've sent in a PR to let the base query builder conform to this behavior as well: https://github.com/laravel/framework/pull/28937
