### ISSUE TITLE
分页方法，计算total的时候，没有传$columns

### ISSUE THREAD

**Issue by tengfei31** [laravel/framework#28842]
- Laravel Version: 5.8.8
- PHP Version: 7.1.19
- Database Driver & Version:

##### 分页方法，计算total的时候，没有传$columns，我在分页传参数的时候，getCountForPagination()  这个 function没有传$columns，请see(look)一下

![image](https://user-images.githubusercontent.com/15308102/59496946-1398e700-8ec5-11e9-8fca-f47496f8386f.png)

![image](https://user-images.githubusercontent.com/15308102/59496790-c87ed400-8ec4-11e9-9ef5-2aed1008f2ef.png)

![image](https://user-images.githubusercontent.com/15308102/59496651-7b9afd80-8ec4-11e9-8e84-29d26761ee6e.png)

**Comment by driesvints** [comment]
I'm very sorry for this but we can only provide support in English. Maybe try out one of the Chinese support forums? https://learnku.com/laravel
