### ISSUE TITLE
API Resources should not assume Eloquent models.

### ISSUE THREAD

**Issue by KieronWiltshire** [laravel/framework#28859]
Currently the implementation of `JsonResource` and `ResourceCollection` assume that the underlying model is an eloquent model, but what if it isn't? 

So in my own application, we do return eloquent models, but our application is structured in a particular way where repository interfaces and entities such as the `User` model can be swapped out. This got me thinking, if I decided I wanted to use a database management system like MongoDB in the future, I would have to use something different to the API Resource response, which is a shame, because most of it is awesome. This change would not only require me to swap out all of the models and repositories, but also the resource responses too.

Now I know someone's going to say something like, you can actually just use `API Resources` without using the eloquent functions like `whenLoaded`. My return question would be, but what if I'm not the one carrying out this task in the future, then the next developer could be somewhat confused by the documentation.

My feature request would be to separate eloquent from the resource responses and optionally provide eloquent resource responses as a separate thing altogether,

**Comment by staudenmeir** [comment]
Please use https://github.com/laravel/ideas/issues for proposals.
