### ISSUE TITLE
URL validation rule not working as expected

### ISSUE THREAD

**Issue by Nael-Saeed** [laravel/framework#28855]
- Laravel Version: 5.8.23
- PHP Version: 7.3.5
- Database Driver & Version: PostgreSQL

### Description:
URL validation rule is accepting any value starting with http://

### Steps To Reproduce:
Create a form with input type text.
Create a controller and a form request to validate that input when posting the form.
Add 'url' rule to rules array.
Enter http://hello in the input field and post the form.
No error should be returned from the form request.

**Comment by SimonJnsson** [comment]
Hey @Nael-Saeed. I think this is intended behaviour as some URLs might be formed similar to that. You can have a look at the regex that is used internally for validating URLs [here](https://github.com/laravel/framework/blob/eff2f054606e8251e59023a6f1a4f0fd773634de/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L1595). If your use case requires that a URL must follow other rules, i recommend you setup a custom validation for this as per [the documentation](https://laravel.com/docs/5.8/validation#custom-validation-rules).

**Comment by Nael-Saeed** [comment]
@SimonJnsson Aha, I didn't know that such URLs exists. Thanks
