### ISSUE TITLE
Redis sessions, after expiry, upon page refresh, reappear and are valid.

### ISSUE THREAD

**Issue by sustained** [laravel/framework#28857]
- Laravel Version: 5.8.21
- PHP Version: 7.3.5
- Database Driver & Version: Redis 4.3.0 (via `phpinfo`); Predis 1.1.1

### Description:

Redis-backed sessions are still valid even after they expire.

### Steps To Reproduce:

* Set `SESSION_DRIVER=redis`
* Set `SESSION_LIFETIME=1`
* Scaffold default auth.
* Register user.
* Log in.
* Wait > 60 seconds (check `redis-cli`, wait for data to go away for sure)
* Refresh page

### Expected result

User is logged out (as per file, database drivers).

### Actual result

User is logged in, session data in Redis has fresh 60 second expiry time.

**Comment by driesvints** [comment]
I just tried this and it works for me. So I believe there's something else going on with your installation. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks
