### ISSUE TITLE
[5.8] Adding viewAny policy ability breaks existing apps

### ISSUE THREAD

**Issue by bastianjoel** [laravel/framework#28862]
- Laravel Version: 5.8.22
- PHP Version: 7.3.6
- Database Driver & Version:

### Description:
In c9f957a8b07011b2a9d88cee24f5b0e4ed905e15 viewAny was added to policies. 

Existing policies without the viewAny function used with `authorizeResource` within a controller will throw a 403 error because of the change.

**Comment by tvbeek** [comment]
This is already pointed out in #28820 but maybe that isn't seen by maintainers.

**Comment by laurencei** [comment]
ping @driesvints - breaking change - see PR.

**Comment by danijelk** [comment]
It's a simple fix to add method to existing policies, or like we did and rename our index() if you have one. Saves us many unnecessary one liners in our controllers so I vote to keep it but to document it.

**Comment by tvbeek** [comment]
@danijelk it is indeed an easy fix (especially with a small project) but it is still a BC break that should be part of a bigger release or made backward compatible.

**Comment by laurencei** [comment]
Closing as issue fixed.

**Comment by driesvints** [comment]
FYI: this wasn't a breaking change. New functionality which doesn't changes the public api aren't breaking changes. Otherwise every single new method, etc could be a breaking change.
