### ISSUE TITLE
Database migration,$table->change,  Changes Text to LongText  not success

### ISSUE THREAD

**Issue by linxbin** [laravel/framework#28861]
- Laravel Version: 5.8.14

- PHP Version: 7.2.15
- Database Driver & Version:
databases use Mysql5.7.24
### Description:
When I used migration to change text to longtext, the terminal displayed successful execution, but the database column were still text

### migration
```
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table( 'pc_orders', function ( Blueprint $table ) {
            $table->longText( 'data' )->comment( 'content' )->change();
        } );
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table( 'pc_orders', function ( Blueprint $table ) {
            $table->text( 'data' )->comment( 'content' )->change();
        } );
    }


```

**Comment by staudenmeir** [comment]
It works for me. What does your migration look like?

**Comment by linxbin** [comment]
> It works for me. What does your migration look like?

I have added the migration code, could you please help me see what's wrong with it

**Comment by staudenmeir** [comment]
The migration looks good to me.

Can you run `Schema::table(...)` in a controller and log the executed queries?

**Comment by linxbin** [comment]
Strangely enough, when I reexecuted the migration file, it worked.

Now I repeat it many times to make sure it's ok

Maybe it was caused by some incorrect operations I made before. I will close this issue. Thank you very much for your help
