### ISSUE TITLE
Error displaying standard pagination when specifying `onEachSide(1)`.

### ISSUE THREAD

**Issue by cvaize** [laravel/framework#28867]
- Laravel Version: 5.8
- PHP Version: 7.2
- Database Driver & Version: MySQL 5.7

### Description:
Error displaying standard pagination when specifying `onEachSide(1)`.

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/26907947/59604545-ebf48980-9125-11e9-866d-c24df9881949.png)
![image](https://user-images.githubusercontent.com/26907947/59604583-02024a00-9126-11e9-9af4-740cdc29ba95.png)

**Comment by cvaize** [comment]
In other cases, everything is displayed correctly.

**Comment by staudenmeir** [comment]
Please see https://github.com/laravel/framework/issues/28789.

**Comment by cvaize** [comment]
@staudenmeir Thanks

**Comment by cvaize** [comment]
I have handled all the exceptions, I will use this code in the production.
Laravel pagination on lg( @media( >= 480px) ) screens onEachSide(5) and on xs( @media( < 480px) ) screens onEachSide(1)
[Link on Gist](https://gist.github.com/cvaize/f12c0d5bcd8eb09bd7fc3e7f8fb4c6c3)
