### ISSUE TITLE
Queue work - call multiple migrate commands keeps connections

### ISSUE THREAD

**Issue by girvydas** [laravel/framework#28873]
- Laravel Version: 5.8.22
- PHP Version: 7.3.6
- Database Driver & Version: 10.3.11-MariaDB

### Description:
Calling ```Artisan::call('migrate', ['--force' => true, '--database' => 'tenant']);``` command at ShouldQueue job, but Laravel keeps mysql connection even if ```DB::purge('tenant');``` is called and it multiplies on every new job run.

### Steps To Reproduce:
1. Create new job example "MigrateJob" and setup new database connection on-the-fly:
```
...
config(['database.connections.tenant.database' => ..)]);
...
```
2. Set new connection default:
```
DB::setDefaultConnection('tenant');
DB::reconnect('tenant');
```
3. Call migrate command:
```Artisan::call('migrate', ['--force' => true, '--database' => 'tenant']);```
4. Purge connection: 
```DB::purge('tenant');```
5. Setup queue worker, run on database/redis connection. Create new command and dispatch "MigrateJob" on that queue
6. Call multiple times "MigrateJob" for different multiple tenants/databases.
7. Check MySQL process list and there will be hangup/stuck processes for every "MigrateJob" even Laravel database connection is purged at code.

Some references about situation:
https://stackoverflow.com/questions/44550814/laravel-5-4-multi-tenant-migrations-switching-connections-for-migrations

**Comment by driesvints** [comment]
Isn't this normal because you're queueing the jobs and re-creating a connection every single time?

**Comment by girvydas** [comment]
All queued jobs needs to be on different database connection so I'm trying to re/connect before every new job start. 
When database connection is re-created on different host I expect the previous one to be fully disconnected. But it keeps hanging and overflows mysql connection limits.

**Comment by driesvints** [comment]
@girvydas you can't really expect that because previous requests maybe aren't finished processing yet. Depending on how many concurrent request you have got going on you'll always have a certain number of concurrent DB connections.

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.
