### ISSUE TITLE
@error blade directive causes vue components to break

### ISSUE THREAD

**Issue by brendt** [laravel/framework#28870]
- Laravel Version: 5.8.23

### Description:

[This commit](https://github.com/laravel/framework/commit/d5b80d727b6e426ce424be79b6016838c368504c) by @calebporzio added the `@error` blade directive. While a nice feature, it also causes existing code using Vue event handler shorthands to break.

```vue
<with-query @error="...">
```

The issue can be solved by using `v-on:error=` instead, though I believe this counts as a breaking change nevertheless.

**Comment by bonzai** [comment]
#28328

**Comment by bonzai** [comment]
#28328

**Comment by devcircus** [comment]
Should code from third party frameworks written in other languages be taken into consideration for breaking changes? Honest question. I've went back and forth on this a few times.

**Comment by brendt** [comment]
I'd expect Vue to be an exception, as it's actively promoted as the default goto JS framework within the community. I'm fine if people don't agree with me on this standpoint.

**Comment by driesvints** [comment]
@brendt unfortunately not. Even though Vuejs has a good relationship with Laravel we can't provide exceptions for it. Try the solution from the linked issue with `@@error`.
