### ISSUE TITLE
Console testing with `<info>` on output

### ISSUE THREAD

**Issue by iget-esoares** [laravel/framework#28882]
- Laravel Version: 5.8.3
- PHP Version: 7.3.6-1+ubuntu18.04.1+deb.sury.org+1
- Database Driver & Version: not used

### Description:

When trying to test a command that outputs something with `<info>` tag on message, we can't test it.

### Steps To Reproduce:

Created this project to reproduce the issue:

https://github.com/iget-esoares/console-test

See this files:

* https://github.com/iget-esoares/console-test/blob/master/app/Console/Commands/TestCommand.php
* https://github.com/iget-esoares/console-test/blob/master/tests/Unit/ExampleTest.php

Running phpunit on it results on:

```
There was 1 failure:

1) Tests\Unit\ExampleTest::testTestCommand
Output "<info>Just a test:</info> 123" was not printed.
```

**Comment by staudenmeir** [comment]
I'm not sure if `<info>Just a test:</info> 123` is a valid output.

The test works when you wrap the whole line in a tag:

```php
$this->line('<info>Just a test: 123</info>');
// $this->info('Just a test: 123');

$this->artisan('test')->expectsOutput('Just a test: 123');
```

**Comment by iget-esoares** [comment]
I think that's valid. Laravel uses this on migrate command... Also it
prints as expected.

Em ter, 18 de jun de 2019 18:56, Jonas Staudenmeir <notifications@github.com>
escreveu:

**Comment by staudenmeir** [comment]
Good point. You actually can test your command but only without the style:

```php
$this->line('<info>Just a test:</info> 123');

$this->artisan('test')->expectsOutput('Just a test: 123');
```
Do you also need to test the style?

**Comment by iget-master** [comment]
> Good point. You actually can test your command but only without the style:
> 
> ```
> $this->line('<info>Just a test:</info> 123');
> 
> $this->artisan('test')->expectsOutput('Just a test: 123');
> ```
> 
> Do you also need to test the style?

That's true, it works when not testing the styles. Testing the style is not a must, but is a should.

**Comment by gofish543** [comment]
Would Laravel be interested in adding this testing capability?
```
$this->artisan('test')->expectsInfoOutput();
$this->artisan('test')->expectsErrorOutput()'
```
Or better yet
```
$this->artisan('test')->expectsOutput('Testing', 'info' | 'error' | 'warning');
// With the stub being expectsOutput($expected, $tag = null, ...additional params)
```

**Comment by staudenmeir** [comment]
I looked at the code: It's not possible to test the output style.

Please use https://github.com/laravel/ideas/issues if you think this would be a useful feature.

**Comment by iget-master** [comment]
I really don't think that's a feature, that's why I created the issue here. IMO that's a bug, or an improvement.

**Comment by driesvints** [comment]
I also agree that this is more of a feature request than a bug. The docs currently don't document the behavior you expect. If we'd change the current behavior people's tests could break.

Please try to submit this as a feature request to the ideas repo and if you attempt a PR feel free to send it to the master branch.
