### ISSUE TITLE
Api resource missing data wrap when response is provide using response()->json(new UserResource($user))

### ISSUE THREAD

**Issue by bhaveshdaswani93** [laravel/framework#28886]
- Laravel Version: 5.8.23
- PHP Version: 7.1.9
- Database Driver & Version: Mysql 5.7

### Description:
I am having issue when providing response using api resource. 
The working response uses follows
return new UserResource($user); this works perfect as expected; 
the response looks like below:
{
   "data" :{
  "id":"123",
   "firstname":"dummy"
}
}
The below does not work:
return response()->json(new UserResource($user));
it gives following response:
{
   "id":"123",
   "firstname":"dummy"
}

**Comment by qWici** [comment]
@bhaveshdaswani93 
```
$data = new UserResource($user);
return response()->json(compact('data'));
```

**Comment by bhaveshdaswani93** [comment]
> @bhaveshdaswani93
> 
> ```
> $data = new UserResource($user);
> return response()->json(compact('data'));
> ```

@qWici Thanks for the response, this is an alternate solution, but why in response()->json(new UserResource($resource) is not working same as return new UserResource($resource);

For side note what should i do if i have pagination for example i have PostResource and have 100 post
i want pagination so i can do like this  return new PostResource(Post::paginate()); this will work but this will not work response()->json(new PostResource(Post::paginate()));

**Comment by staudenmeir** [comment]
Why are you using `response()->json()`?

**Comment by qWici** [comment]
@bhaveshdaswani93  Yeah, @staudenmeir asked a right question. Your UserResourse by default extends from [JsonResource](https://github.com/laravel/framework/blob/5.8/src/Illuminate/Http/Resources/Json/JsonResource.php) and by default converted to array by toArray method

**Comment by bhaveshdaswani93** [comment]
> Why are you using `response()->json()`?

@staudenmeir 
Thanks for response
I have created a trait for API response for my project
The final response I provide to API is like following
{"success":true/false,
"message":"",
"payload":UserResource/UserCollection(ApiResource)
}
When I provide response using this way I get only the user model 
The additional functionality goes missing.
How should I achieve this.
Or it is not possible to use ApiResource with response()->json();

**Comment by staudenmeir** [comment]
Take a look at https://laravel.com/docs/eloquent-resources#adding-meta-data.

`with()` and `additional()` should be the features you are looking for.

**Comment by bhaveshdaswani93** [comment]
OK I will try this approach
