### ISSUE TITLE
MassAssignmentException not thrown when fillable not empty

### ISSUE THREAD

**Issue by l0rb** [laravel/framework#28880]
- Laravel Version: 5.8.10
- PHP Version: 7.3
- Database Driver & Version: mysql

### Description:
When a model has no fillable fields defined a `Illuminate/Database/Eloquent/MassAssignmentException` is thrown when trying to create one with for example `firstOrCreate`. If the fillable property exists and is not an empty list the warning is not thrown even if all supplied fields are not fillable, they are just silently removed and a db query done.

### Steps To Reproduce:
run following code:
```
class SomeModel extends Model {
    protected $fillable = [""]; // putting [ ] or removing the property yields the error 
}
SomeModel::firstOrCreate(['some_field'=>123], ['other_field'=>456]); // error expected here, but none happening.
```

**Comment by staudenmeir** [comment]
To me, this is the correct behavior. The fact that the provided attributes don't include any fillable fields doesn't mean there's an error and Laravel should throw an exception.

**Comment by l0rb** [comment]
It seems to be inconsistent than. If the `$fillable` property is not set, or is empty the error is thrown and is thrown only if the provided attributes contain non-fillable fields.

**Comment by staudenmeir** [comment]
A `MassAssignmentException` is only thrown if the model is ["totally guarded"](https://github.com/laravel/framework/blob/21cb37d447a739ab2edd487adb652130493e21fb/src/Illuminate/Database/Eloquent/Concerns/GuardsAttributes.php#L174), i.e. you can't possibly provide fillable attributes.

When `$fillable` isn't empty, that's not the case and you *could* provide fillable attributes.

**Comment by l0rb** [comment]
Seeing this I agree that this is more a case of missing documentation than an actual bug.
