### ISSUE TITLE
Query Builder Paginate gives SQLSTATE[42000] syntax error if you pass columns into paginate()

### ISSUE THREAD

**Issue by awais-vteams** [laravel/framework#28890]
- Laravel Version: 5.8.22
- PHP Version: 7.2.17
- Database Driver & Version: MySql 8.0

### Description:
Database Query Builder Paginate gives SQLSTATE[42000]: Syntax error if you pass columns into paginate()

### Steps To Reproduce:

```
$results = DB::table('users')->paginate(20, ['id', 'name']);
```

> Illuminate \ Database \ QueryException (42000)
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' `name`) as aggregate from `users`' at line 1 (SQL: select count(`id`, `name`) as aggregate from `users`)

Ref: #28889

**Comment by ashokpoudelap** [comment]
The right way of doing this would be .
 
` $results = DB::table('users')->select("id,"name")->paginate(20);`

**Comment by driesvints** [comment]
Sent in a PR for this here: https://github.com/laravel/framework/pull/28937
