### ISSUE TITLE
[5.8][MySQL] migration for virtual column from JSON generates different SQL after upgrade from 5.7

### ISSUE THREAD

**Issue by NEGits** [laravel/framework#28899]
- Laravel Version: 5.8.23
- PHP Version: 7.2.17
- Database Driver & Version: MySQL 5.7.25

### Description:

I recently upgraded from 5.7.x to 5.8.23, and am seeing some unexpected changes from my migrations.

In my DB I have several JSON columns together with virtual columns for indexing some of the JSON values. After upgrading Laravel the migrations that set up these virtual columns generate different SQL than before the upgrade, which has some unexpected effects.

Example Migration:
```
$table->string('name')->virtualAs('properties->"$.name"')->after('properties');
```

Generated SQL on 5.7:
```
`name` varchar(255) COLLATE utf8mb4_unicode_ci GENERATED ALWAYS AS (json_unquote(json_extract(`properties`,'$.name'))) VIRTUAL
 ```

Generated SQL on 5.8:
```
`name` varchar(255) COLLATE utf8mb4_unicode_ci GENERATED ALWAYS AS (json_extract(`properties`,'$.name')) VIRTUAL
```

Because 5.8 does not use json_unquote a value in the virtual column is stored as `"name"` in a column created with 5.8 where in 5.7 it would be stored as `name`. Because I'm accessing these columns without going through Eloquent in some places in my code I'm also getting these extra `"`s in my content, which is unwanted.

I could not find anything about this in other issues, pull reqs or the upgrade guide. Is this new behaviour intended?

**Comment by staudenmeir** [comment]
Please see https://laravel.com/docs/5.8/upgrade#database.

**Comment by NEGits** [comment]
I saw that but don't quite understand how (or why) that change impacts existing migrations.

**Comment by staudenmeir** [comment]
What does your actual migration look like?

`->virtualAs('properties->"$.name"')` doesn't generate the query you posted.

**Comment by NEGits** [comment]
That was a copy/paste from my actual migration file. Complete function looks like this:

```
    public function up()
    {
        Schema::table('users', function (Blueprint $table) {
            $table->json('properties')->after('email');
            $table->string('name')->virtualAs('properties->"$.name"')->after('properties');
            $table->index('name');
        });
    }
```

And I copy pasted that SQL from the DDL in MySQL Workbench tbh, I'll try to get the actual queries run by that migration later today if I can find the time..

**Comment by NEGits** [comment]
Found some time!

Comparing the actual query from this migration:
5.7:
```
alter table `users` add `properties` json not null after `email`, add `name` varchar(255) as (properties->>"$.name") after `properties`
alter table `users` add index `users_name_index`(`name`)
```

5.8
```
alter table `users` add `properties` json not null after `email`, add `name` varchar(255) as (properties->"$.name") after `properties`
alter table `users` add index `users_name_index`(`name`)
```

So 5.7 adds a second `>` to the query, which apparently introduces the json_unquote server side. Manually adding the second `>` in the migration seems to fix my problems on 5.8. 

Not sure if this should be covered in the upgrade guide, but seems the opposite of what's there now..

**Comment by staudenmeir** [comment]
Your migration must have changed during the upgrade.

Laravel treats the value provided in `virtualAs()` as a raw expression and doesn't alter it in any way.

**Comment by NEGits** [comment]
I'm positive my migrations did not change. The results posted above are from the same migration file, only thing that changed is the laravel version. So if the upgrade did not alter that query it must be a package that I've installed, although I would be very surprised if that is the case. 

I will try to exclude that possibility later today or tomorrow.

**Comment by NEGits** [comment]
Hmm.. Looking at this again in our history it seems that the migrations DID change.  :flushed:

I guess I overlooked a change in a too big upgrade commit. Thanks for your time and patience!
