### ISSUE TITLE
[5.8] PHPDocs correction in Illuminate\Database\Query\Builder *MINOR*

### ISSUE THREAD

**Issue by markdwhite** [laravel/framework#28896]
- Laravel Version: 5.8 [master]
- PHP Version: 7.2.19
- Database Driver & Version: mysql 5.7.26

### Description:

Illuminate\Database\Query\Builder::join() has a doctype that declares "string $table" but accepts different types of $table. Eg: the function Illuminate\Database\Query\Builder::joinSub() calls join() with an Expression as the first param:

    `return $this->join(new Expression($expression), $first, $operator, $second, $type, $where);`

This has limited negative effects:

 - Using join(DB::raw(), ...) can be necessary when joining to subquery tables as these cause problems when submitted as strings due to Illuminate\Database\Grammar::wrapTable().

 - PHPStan will complain that join() expects a string when Expressions need to be used.

 - Any future attempt to strict_type the Laravel codebase is going to hit problems here.

I would not consider this to be a significant issue in itself, but is probably related to the cross-use of strings|Expressions throughout Eloquent (from what I see in investigating this).

So, it's raised but it's probably a known in some respect.

**Comment by staudenmeir** [comment]
You are right, but I'm not sure if we should change that.

There are dozens of places where you can provide a raw expression instead of a string. Documenting all of them would make the documentation harder to read (IMO).

**Comment by markdwhite** [comment]
There's a part of me that wouldn't want to see PHPDocs (not Doctype...) like:

    @var string|\Illuminate\Query\Expression $table

But it does seem to be an official approach:

https://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.param.pkg.html

But fixing fiddly stuff for little benefit is hard to justify. I get it.

**Comment by mfn** [comment]
> Documenting all of them would make the documentation harder to read (IMO).

🤔

First time I heard such an argument.

I'm not sure what the actual concern is with readability and what the negative impact is.

The current phpdoc is incomplete, you could almost say, it's a bug. Not sure why fixing this would have to discussed under terms of readability.

With that kind of argument you could counter argument against the whole move of PHP to introduce type declarations in the first place.

_Maybe_, but I'm just guessing, part of the readability issue is that Laravel to this day insists on its code style to _not_ import phpdoc expression; for reasons I can't fathom.

**Comment by staudenmeir** [comment]
> With that kind of argument you could counter argument against the whole move of PHP to introduce type declarations in the first place.

I'm absolutely in favor of fixing Laravel's PHPDoc and methods with (strict) type declarations.

But I see raw expressions as an exception. A lot of query builder methods have one or more parameters where you could (theoretically) provide a raw expression.

I think the [documentation](https://laravel.com/docs/queries#raw-expressions) is a better place to inform users about raw expressions. This way, they also see the SQL injection warning.

**Comment by driesvints** [comment]
I'm a bit torn myself on this because on one side I agree that we could update the DocBlocks and it would be the "proper" thing to do but on the other hand I'm thinking to myself: where does this end? I know Taylor (and myself included) aren't big fans of all these DocBlock updates and changes so I suspect if you'd now send in a PR to "fix" all of these it'd be rejected. 

At the very least I don't consider this a bug since no code is broken. The ideas repo is probably a better place to have this discussion.

Like I said you can always attempt a PR but I suspect it wouldn't be well received.

Ps.: I agree with @staudenmeir that the docs is a better place in this particularly case to inform people of raw expressions.

**Comment by mfn** [comment]
> where does this end?

IMHO simple to answer: when docblocks/types are correctly reflecting the types, not sooner 🤷‍♀️
