### ISSUE TITLE
Eager loading vs lazy loading with wrong case foreign key

### ISSUE THREAD

**Issue by ppalmtag** [laravel/framework#28897]
- Laravel Version: 5.8
- PHP Version: 7.1
- Database Driver & Version: Maria DB 10.1.40

### Description:
I have an issue with the dynamic properties for relationships and the eager loading method `with()`. In my opinion both should yield the same results, which in my example is not the case. When retrieving the relationship via diynamic property I get a result even with the wrong case foreign key. But I get no result when using eager loading. 
I encountered this while working with an old database which does not use the naming conventions. In this example the foreign key is written with uppercase first character.  

Please let me know if anything is unclear or you need more information.

### Steps To Reproduce:

These are the Order Model relationship functions:

```
    /**
     * Get the order items for the order
     */
    public function orderItems()
    {
        return $this->hasMany('App\OrderItem', 'Order_id');
    }

    /**
     * Get the order items for the order
     */
    public function orderItems2()
    {
        return $this->hasMany('App\OrderItem');
    }
```

You see that in one case I use the correct foreign key description while in the second function I let Laravel decide. When I use the dynamic propery methods to get the order items, both functions work.

```
        Order::find(17194838)->orderItems;

        Order::find(17194838)->orderItems2;
```

```
Illuminate\Database\Eloquent\Collection {#821
  #items: array:1 [
    0 => App\OrderItem {#818
      #table: "Order_Item"
      #connection: "azmanager"
      +timestamps: false
      #primaryKey: "id"
      #keyType: "int"
      +incrementing: true
      #with: []
      #withCount: []
      #perPage: 15
      +exists: true
      +wasRecentlyCreated: false
      #attributes: array:21 [
        "id" => "19070139"
        "Order_id" => "17194838"
        "item_name" => "10 x 0,25m CAT 7 Netzwerkkabel Flach"
      ]
      #original: array:21 [
        "id" => "19070139"
        "Order_id" => "17194838"
        "item_name" => "10 x 0,25m CAT 7 Netzwerkkabel Flach"
      ]
      #changes: []
      #casts: []
      #dates: []
      #dateFormat: null
      #appends: []
      #dispatchesEvents: []
      #observables: []
      #relations: []
      #touches: []
      #hidden: []
      #visible: []
      #fillable: []
      #guarded: array:1 [
        0 => "*"
      ]
    }
  ]
}
```

and

```
Illuminate\Database\Eloquent\Collection {#822
  #items: array:1 [
    0 => App\OrderItem {#804
      #table: "Order_Item"
      #connection: "azmanager"
      +timestamps: false
      #primaryKey: "id"
      #keyType: "int"
      +incrementing: true
      #with: []
      #withCount: []
      #perPage: 15
      +exists: true
      +wasRecentlyCreated: false
      #attributes: array:21 [
        "id" => "19070139"
        "Order_id" => "17194838"
        "item_name" => "10 x 0,25m CAT 7 Netzwerkkabel Flach"
       
      ]
      #original: array:21 [
        "id" => "19070139"
        "Order_id" => "17194838"
        "item_name" => "10 x 0,25m CAT 7 Netzwerkkabel Flach"
      ]
      #changes: []
      #casts: []
      #dates: []
      #dateFormat: null
      #appends: []
      #dispatchesEvents: []
      #observables: []
      #relations: []
      #touches: []
      #hidden: []
      #visible: []
      #fillable: []
      #guarded: array:1 [
        0 => "*"
      ]
    }
  ]
}
```

But when using 

```
        $o = Order::with('orderItems')->find(17194838);

        $o2 = Order::with('orderItems2')->find(17194838);
```

Results are different as when retrieving the relation via dynamic property. There are no results for the function with the lowercase foreign key.

```
Illuminate\Database\Eloquent\Collection {#815
  #items: array:1 [
    0 => App\OrderItem {#811
      #table: "Order_Item"
      #connection: "azmanager"
      +timestamps: false
      #primaryKey: "id"
      #keyType: "int"
      +incrementing: true
      #with: []
      #withCount: []
      #perPage: 15
      +exists: true
      +wasRecentlyCreated: false
      #attributes: array:21 [
        "id" => "19070139"
        "Order_id" => "17194838"
        "item_name" => "10 x 0,25m CAT 7 Netzwerkkabel Flach"
      ]
      #original: array:21 [
        "id" => "19070139"
        "Order_id" => "17194838"
        "item_name" => "10 x 0,25m CAT 7 Netzwerkkabel Flach"
      ]
      #changes: []
      #casts: []
      #dates: []
      #dateFormat: null
      #appends: []
      #dispatchesEvents: []
      #observables: []
      #relations: []
      #touches: []
      #hidden: []
      #visible: []
      #fillable: []
      #guarded: array:1 [
        0 => "*"
      ]
    }
  ]
}
```

and

```
Illuminate\Database\Eloquent\Collection {#796
  #items: []
}
```

### Database

```
        CREATE TABLE `Order` (
            `id` INT(13) NOT NULL AUTO_INCREMENT,
            `order_date` DATE NOT NULL,
            [...]
            PRIMARY KEY (`id`)
        )
        COLLATE='latin1_swedish_ci'
        ENGINE=InnoDB
        AUTO_INCREMENT=1
        ;

        CREATE TABLE `Order_Item` (
            `id` BIGINT(13) NOT NULL AUTO_INCREMENT,
            `Order_id` BIGINT(13) NOT NULL,
            `item_name` VARCHAR(255) NOT NULL,
            [...]
            PRIMARY KEY (`id`),
            INDEX `order_id` (`Order_id`)
        )
        COLLATE='latin1_swedish_ci'
        ENGINE=InnoDB
        AUTO_INCREMENT=1
        ;
```

**Comment by staudenmeir** [comment]
I wouldn't consider this a bug. Your second relationship is incorrect and lazy loading only works by accident because column names in MySQL/MariaDB are case-insensitive.

**Comment by ppalmtag** [comment]
I also would not consider it a bug but an inconsistency or undesired behavior. If lazy loading works, eager loading should work too, in my opinion. Or the other way around.
If you say column names are case insensitive, why is eager loading not working in this scenario? You mention the relation is incorrect. Are you refering to the wrong case foreign key?

**Comment by staudenmeir** [comment]
> I also would not consider it a bug but an inconsistency or undesired behavior. If lazy loading works, eager loading should work too, in my opinion. Or the other way around.

Your relationship is incorrect, but you can't expect every piece of code using it to fail. 

> If you say column names are case insensitive, why is eager loading not working in this scenario?

Eager loading doesn't work because array keys are case-sensitive in PHP: `$order->order_id` returns `null`.

> You mention the relation is incorrect. Are you refering to the wrong case foreign key?

Yes. When you use a foreign key other than `order_id`, you need to specify it.

**Comment by ppalmtag** [comment]
If the framework should make up for my mistakes? I think this is debatable. I personally think that if you load a relation and the foreign key is wrong it should fail for every piece of code that loads this relation. It would make it easier for developers to find their mistakes.

It took quiet some time for me to realize that eager and lazy loading made the difference when acquiring the relation, when one of them works as if everything was configured correctly.

If I understand correctly and based on your comments, the query works for both loading "types" (because MySQL column names are case insensitive). But the creation of the model fails because the array keys / object attributes are case sensitive and so the information is "lost on the way" when creating the related models.

Since our opinions differ on this topic it would be great to hear some other developers to this topic.

**Comment by staudenmeir** [comment]
> I personally think that if you load a relation and the foreign key is wrong it should fail for every piece of code that loads this relation.

That would be ideal but is not possible in this case. Laravel doesn't know what the correct column name is and would have to execute an additional query to check it *everytime* the relationship is used.

> If I understand correctly and based on your comments, the query works for both loading "types" (because MySQL column names are case insensitive). But the creation of the model fails because the array keys / object attributes are case sensitive and so the information is "lost on the way" when creating the related models.

Yes, that's the reason.

**Comment by driesvints** [comment]
I think this is something that's best being picked up on the ideas repo (since this isn't a bug) so more people can join the discussion. Thanks
