### ISSUE TITLE
Artisan::call('carwashdevice:run'); The command "carwashdevice:run" does not exists.

### ISSUE THREAD

**Issue by sessionliang** [laravel/framework#28907]
- Laravel Version: 5.8.13
- PHP Version: 7.1.22
- Database Driver & Version: Mysql 5.7.23

### Description:
1. This command is a custome command and can be displayed in the list.
![image](https://user-images.githubusercontent.com/12078007/59920121-18791000-945c-11e9-97b6-89309e409142.png)
2. It works on the console.
![image](https://user-images.githubusercontent.com/12078007/59920369-e61be280-945c-11e9-820e-e32754af3384.png)
3. Error in code. The command does not exists.

**Comment by staudenmeir** [comment]
Please post the command's code.

**Comment by laurencei** [comment]
My guess is you are calling this command from a http request, and you havent registered the command (only in the console kernal).

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
