### ISSUE TITLE
orWhere method adds extra parenthesis

### ISSUE THREAD

**Issue by tarek1500** [laravel/framework#28911]
- Laravel Version: 5.8.24
- PHP Version: 7.3.1
- Database Driver & Version: MySQL v5.7.24

### Description:
I have this function on Users model, which returns the current friends of this model.
```
public function friends()
{
	return Friend::where(function ($query) {
		$query->whereSender($this)->orWhereReceiver($this);
	});
}
```

and here is the scope functions on Friend model.
```
public function scopeWhereSender(EloquentBuilder $query, Model $model)
{
	return $query->where(function ($query) use ($model) {
		$query->where('sender_type', $model->getMorphClass())
		      ->where('sender_id', $model->getKey());
	});
}
public function scopeOrWhereReceiver(EloquentBuilder $query, Model $model)
{
	return $query->where(function ($query) use ($model) {
		$query->where('receiver_type', $model->getMorphClass())
		      ->where('receiver_id', $model->getKey());
	}, null, null, 'or');
}
```

The previous code generates the following query (from **DB::getQueryLog()**):
```
select * from `friends` where ((`sender_type` = ? and `sender_id` = ?) or ((`receiver_type` = ? and `receiver_id` = ?)))
```
**Same result for orWhere method**

But if I just change the Boolean 'or' to be like 'OR' or even 'Or' it gives me the following query:
```
select * from `friends` where ((`sender_type` = ? and `sender_id` = ?) OR (`receiver_type` = ? and `receiver_id` = ?))
```

The first query has extra parenthesis after the 'or' statement unlike the second (which I think is correct), I would like to ask why the first one add extra parenthesis? I feel like there is something wrong with the query.

**Comment by staudenmeir** [comment]
In this case, both queries return the same result, but the first query is the correct one.

Laravel automatically wraps scopes that contain an `or` constraint in parentheses.
The second query is different because Laravel expects the `$boolean` parameter to be lowercase.

I recommend that you use `orWhere()` instead:

```php
public function scopeOrWhereReceiver(EloquentBuilder $query, Model $model)
{
    return $query->orWhere(function ($query) use ($model) {
        $query->where('receiver_type', $model->getMorphClass())
	    ->where('receiver_id', $model->getKey());
	});
}
```

**Comment by tarek1500** [comment]
Good to know, I just had a look over 'groupWhereSliceForScope' method and found it !
But still it gives me a weird feeling about the extra parenthesis. Does it effect somehow the later nested queries?

**Comment by staudenmeir** [comment]
No, it doesn't have any side effects.
