### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found

### ISSUE THREAD

**Issue by saydulk** [laravel/framework#28919]
- Laravel Version: Laravel Framework 5.8.24
- PHP Version: PHP 7.2.19
- Database Driver & Version: mysql  Ver 15.1 Distrib 10.3.16-MariaDB

### Description:
I am using Ubuntu 18.04 LTS. I have deploy a Latavel app successfully and login page working. But when I try to register (sign up) new account it shows me Illuminate \ Database \ QueryException (42S02)
SQLSTATE[42S02]: Base table or view not found

![Screenshot from 2019-06-23 00-50-51](https://user-images.githubusercontent.com/1058663/59967892-e39bb480-9552-11e9-9216-5cb3c40ac63d.png)
![Screenshot from 2019-06-23 01-00-26](https://user-images.githubusercontent.com/1058663/59967893-e39bb480-9552-11e9-835d-8a44ca46f870.png)

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
