### ISSUE TITLE
CentOS 7 Apache Sorry, the page you are looking for could not be found

### ISSUE THREAD

**Issue by saydulk** [laravel/framework#28912]
- Laravel Version: #5.6
- PHP Version: #7.3
- Database Driver & Version: Distrib 10.3.16-MariaDB

### Description:
After deploy laravel app into a sub domain showing 
![Screenshot from 2019-06-21 21-25-46](https://user-images.githubusercontent.com/1058663/59933367-271af380-946b-11e9-920a-10278a17af16.png)

**Comment by mvdnbrk** [comment]
You are not providing enough details to point you in the right direction.

Please note: Laravel 5.6 is not supported anymore. Please see the [support policy](https://laravel.com/docs/5.7/releases#support-policy).
