### ISSUE TITLE
Warning: Ambiguous class resolution, "Illuminate\Translation\MessageSelector" was found 

### ISSUE THREAD

**Issue by steven7mwesigwa** [laravel/framework#28918]
- Laravel Version: 5.7
- PHP Version: 7.2
- Database Driver & Version: MySQL 5.6

### Description:
1. When i run` composer install `OR `composer update `i receive this **WARNING** in the output.

`Warning: Ambiguous class resolution, "Illuminate\Translation\MessageSelector" was found in both "/media/jaguar/stevenmwesigwa/stevenmwesigwa/vendor/laravel/framework/src/Illuminate/Queue/Worker.php" and "/media/jaguar/stevenmwesigwa/stevenmwesigwa/vendor/laravel/framework/src/Illuminate/Translation/MessageSelector.php", the first will be used.`

```
Carbon 1 is deprecated, see how to migrate to Carbon 2.
https://carbon.nesbot.com/docs/#api-carbon-2
    You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In Worker.php line 562:
                                                                               
  syntax error, unexpected end of file, expecting case (T_CASE) or default (T  
  _DEFAULT) or '}'   
```

2. Every time i run the commands below, i get a related error.
**Commands**
-  php artisan help:commands
-  php artisan env
- php artisan make:model Bust
-  php artisan make:controller Bust

**Error received on all above commands.**
```
In Worker.php line 562:
                                                                                               
  syntax error, unexpected end of file, expecting case (T_CASE) or default (T_DEFAULT) or '}'  
```
3. This makes me helpless if i can't create models or controllers from terminal. Please Help !!!!!

**Comment by sisve** [comment]
The worker.php file should not contain any declarations for a MessageSelector. Have you modified it yourself? It should look something like [/src/Illuminate/Queue/Worker.php](https://github.com/laravel/framework/blob/5.7/src/Illuminate/Queue/Worker.php). You can remove any local changes by reinstalling the framework files; first remove the vendor/laravel/framework folder and then execute `composer install`.

The error related to line 562 (`syntax error, unexpected end of file, expecting case (T_CASE) or default (T  
  _DEFAULT) or '}'`) sounds like you have a weird switch statement there, but the official sources doesn't have any. This too sounds like you've modified the file locally.

**Comment by steven7mwesigwa** [comment]
@sisve  I have copied the `Worker.php` file from the _link_ you provided and used it to **replace** the _"corrupt"_ one i had locally, And it has solved the problem.
Thank you for responding quickly. You're the best. Thanks.
