### ISSUE TITLE
MSSQL conversion error

### ISSUE THREAD

**Issue by laurencei** [laravel/framework#28923]
- Laravel Version: 5.8.21
- PHP Version: 7.2.11
- Database Driver & Version: MSSQL 2014

### Description:

I cant decide if this is a bug in Laravel, the PDO, or MSSQL itself.

When trying to insert certain values into the database, the MSSQL driver treats `int` special to any other type, and tries to convert all values of that same column into an `int` - even if it should be a different cast.

It is easiest to explain with the example below.

This does not occur in any other driver (mySQL, Postgres etc) - i.e. the code below works fine for those (I've tested it).

### Steps To Reproduce:

Create a simple migration:

```
<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateTestTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('test', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('name')->nullable();
            $table->decimal('value', 9, 2)->nullable();
        });
    }

}
```

Then run this:

```
// This works
DB::table('test')->insert(
    ['name' => 'test1', 'value' => 33.9],
    ['name' => 'test2', 'value' => 33.1],
);

// This works
DB::table('test')->insert(
    ['name' => 'test3', 'value' => 33.9],
    ['name' => 'test4', 'value' => 33.0],
);

// This works
DB::table('test')->insert(
    ['name' => 'test5', 'value' => 33.9],
    ['name' => 'test6', 'value' => '33'],  // a string of "33"
);

// This does NOT work
DB::table('test')->insert(
    ['name' => 'test7', 'value' => 33.9],
    ['name' => 'test8', 'value' => 33],  // an int of "33"
);
```

When running `test7/test8` - it fails with:

> [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Conversion failed when converting the nvarchar value '33.9' to data type int. (SQL: insert into [test] ([name], [value]) values (test7, 33.9), (test8, 33))

As you can see, because *one* of the `[value]` contains an `int` - it tries to convert _all_ the `[value]` in the entire array to `int` before inserting. In this case - it is trying to cast `33.9` to an `int` - even though the column definition is a `float`.

This also affects text values - for example the below also fails only in MSSQL:

```
DB::table('test')->insert(
   ['name' => 'test7', 'value' => 33.9],
   ['name' => 333, 'value' => 33.9],  // notice the name is an `int` not a string
);
```

Now one option is to always pre-cast to ensure I am inserting a float etc. But this is a very simple example of some code I'm running, which took me a while to get it to this simple example.

It would be very intensive to try to cast all the values before inserting them, and no practical. I dont understand why this only affects a MSSQL database, where as PostGres, mySQL etc all cope just fine with these inserts.

Where do we think this issue lies...?

**Comment by staudenmeir** [comment]
I would say that this is an issue with SQL Server. Your last example doesn't work without bindings either:

```php
DB::statement("insert into [test] ([name], [value]) values ('test7', 33.9), (333, 33.9)");
```

Your fourth example *does* work as a raw query:

```php
DB::statement("insert into [test] ([name], [value]) values ('test7', 33.9), ('test 8', 33)");
```

This is "caused" by Laravel binding float values as strings (since there's no `PDO::PARAM_FLOAT` type):

https://github.com/laravel/framework/blob/d53cba6e66037342c4cc26b6d9c768c114d2a641/src/Illuminate/Database/Connection.php#L573-L576

**Comment by laurencei** [comment]
@staudenmeir - I tried the raw query on the a MSSQL console, and it also failed. 

But before I close this as not Laravel related; why do we cast an `int` at all in the connection? Especially if there is only support for `int` and not `float`? 

I tested this a few times, and the results dont seem to change without casting, so why cast at all?

**Comment by laurencei** [comment]
@staudenmeir - I tried the query as a direct SQL query on the MSSQL console, and it also failed. So it's definitely an issue there, and I'll have to do more reading.

However, I did some testing of the PDO connection, and if I always cast as `PDO::PARAM_STR` - then the issue goes away for me. And the results are all correct in my DB as expected.

I did some googling, and this document implies Microsoft recommends to always use the `PDO::PARAM_STR` for a MSSQL database connection?

https://docs.microsoft.com/en-us/sql/connect/php/pdostatement-bindvalue?view=sql-server-2017

Thoughts?

**Comment by laurencei** [comment]
Actually - this works on an MSSQL console:

```
insert into [test] ([name], [value]) values ('test1', 33.9), ('test2', 33)
```

So when its a `float` and an `int` - its ok.

The problem is when it is a `string` and an `int` that it fails.

**Comment by laurencei** [comment]
My current thinking is making this a configurable option for the sqlsrv driver, and allow the system to only use `PDO::PARAM_STR` for all values if you want...

...otherwise you can end up in this edge case scenario, where a value suddenly isnt what you expect.

In my case - I am tracking GPS cordinates of a vehicle. The GPS cordinates are normally a `float`. But the other day, for a brief second, the vehicle tracking when from `-33.002, -33.001, -33, -32.999`  and that's how I ended up here...

**Comment by laurencei** [comment]
@staudenmeir - ok - now I've found something. All drivers use the code you listed, except for mySQL - it has a slightly different implementation:

https://github.com/laravel/framework/blob/a9f880df1350cd755a41ec8eaafdffa3bc982aad/src/Illuminate/Database/MySqlConnection.php#L75-L83

In that - it explicity binds a `float` as `PDO::PARAM_INT`.

I tested it, and that resolves the issue in MSSQL for me.

This is the PR where it was added - but looks like a lot of history around this: https://github.com/laravel/framework/pull/16069

**Comment by driesvints** [comment]
Fyi: just marking this as "needs more info" for now while you guys discuss things.

**Comment by staudenmeir** [comment]
> They recommend not using PDO::PARAM_INT due to possible rounding errors

But only for decimal values, right?

**Comment by laurencei** [comment]
> But only for decimal values, right?

Yeah. But my question is, if we are not going to do it for `33.9` - then why do we do it for `33`?

I've done some googling, and there does not seem to be a negative reason to just use `PDO::PARAM_STR` for everything, and not bother using `PDO::PARAM_INT` at all?

The only docs I find is that there might be a small performance increase by using `PDO::PARAM_INT`, but that is probably offset by the server work to determine which ones to convert in the first place? i.e. we are just shifts the processing cost?

@staudenmeir - do you see a massive negative option for having this as a config option, and letting people disable using `PDO::PARAM_INT` if they choose?

**Comment by staudenmeir** [comment]
> Yeah. But my question is, if we are not going to do it for 33.9 - then why do we bother doing it for 33? Both are numeric values, yet we treat them very differently.

I think we are using the terms `decimal` and `numeric` differently. The documentation and I are referring to values with fixed precision (e.g. amounts of money), but not integer or float values.

I don't think a new config option is the best solution for this issue. I would prefer testing if we can adopt the MySQL implementation and use `PDO::PARAM_INT` for both integer and float values.

**Comment by laurencei** [comment]
> I don't think a new config option is the best solution for this issue. I would prefer testing if we can adopt the MySQL implementation and use PDO::PARAM_INT for both integer and float values.

But what about when inserting string and integer data? We cant solve that?

Are you able to shed any insight into the negative of just using `PDO::PARAM_STR`? Does it actually matter if we only did that...?

**Comment by staudenmeir** [comment]
> But what about when inserting string and integer data? We cant solve that?

I don't think that's a query we should have to support since it doesn't work without bindings either.

> Are you able to shed any insight into the negative of just using PDO::PARAM_STR? Does it actually matter if we only did that...?

Without testing it, I can't name cases where this would break queries. But since PHP offers a custom type for integers, I think we should keep using it.

**Comment by driesvints** [comment]
I'm going to close this since the conclusion seems to be that this isn't something we can fix? Feel free to respond with thoughts on it.
