### ISSUE TITLE
session regenerated 2 times after login

### ISSUE THREAD

**Issue by drmovi** [laravel/framework#28927]
- Laravel Version: 5.8
- PHP Version: 7
- Database Driver & Version:

### Description:
I wonder if session is regenerated 2 times after login when using session guard:
1- first when login in SessionGuard.php login function

```php
    public function login(AuthenticatableContract $user, $remember = false)
    {
        **$this->updateSession($user->getAuthIdentifier());**

        // If the user should be permanently "remembered" by the application we will
        // queue a permanent cookie that contains the encrypted copy of the user
        // identifier. We will then decrypt this later to retrieve the users.
        if ($remember) {
            $this->ensureRememberTokenIsSet($user);

            $this->queueRecallerCookie($user);
        }

        // If we have an event dispatcher instance set we will fire an event so that
        // any listeners will hook into the authentication events and run actions
        // based on the login and logout events fired from the guard instances.
        $this->fireLoginEvent($user, $remember);

        $this->setUser($user);
    }
```

2- second time when call     $request->session()->regenerate();  in function protected function sendLoginResponse(Request $request) inside trait AuthenticatesUsers

so what is the idea behind generating session id twice ?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
