### ISSUE TITLE
php artisan dont serve

### ISSUE THREAD

**Issue by mrhili** [laravel/framework#28930]
- Laravel Version: 5.4
- PHP Version: 7.2
- Database Driver & Version:

### Description:
after i update windows 10 i cant serve anymore

i have avast and malwarebite as antiviruses

**Comment by huwamoko6210** [comment]
Hi.
It seems Avast deletes the server.php.
You should exclude server.php  from the scan in the Avast settings.

reference:
https://github.com/laravel/framework/issues/23809

**Comment by laurencei** [comment]
Please also update to Laravel 5.8, as 5.4 is no longer supported.

**Comment by mrhili** [comment]
> Hi.
> It seems Avast deletes the server.php.
> You should exclude server.php from the scan in the Avast settings.
> 
> reference:
> #23809

no he dont delete the file but he cant serve, telle me how to performe the upgrade of laravel from the command line?
