### ISSUE TITLE
`make:migration` doesn't validate the class name to be generated

### ISSUE THREAD

**Issue by liam-wiltshire** [laravel/framework#28938]
- Laravel Version: 5.8.*
- PHP Version: 7.1

### Description:
When passing the name param to the `make:migration` call, the passed value isn't validated to ensure that an invalid class name cannot be created

### Steps To Reproduce:

Running the following artisan command:

`php artisan make:migration username_stea,` (note the comma on the end as a result of missing the m key)

Generates a migration with the following classname:

`class UsernameStea, extends Migration`

### Expected Behaviour

Validation to ensure only allowable characters are used, or otherwise to omit these characters from the classname (defined in https://www.php.net/manual/en/language.oop5.basic.php)

**Comment by liam-wiltshire** [comment]
Something along the lines of:

```php
        if (!(bool)preg_match("%^[a-zA-Z_\x80-\xff][a-zA-Z0-9_\x80-\xff]*$%", $name)) {
            throw new \InvalidArgumentException("Invalid characters present in proposed classname {$name}");
        }
```

Would do the trick

**Comment by driesvints** [comment]
Thanks. Feel free to send in a PR with a test.
