### ISSUE TITLE
Signed URL's dont use HTTPS when forced

### ISSUE THREAD

**Issue by NT-andrewgosselin** [laravel/framework#28941]
- Laravel Version: 5.8.24
- PHP Version: 7.3.6

### Description:
While signing url's locally everything worked fine since everything was unsecured using "http" but upon putting this project into a production environment and securing it using "https" using Nginx or using the built in "forceScheme('https')" the signatures generated were different. Upon further investigation I data dumped some variables in the UrlGenerator class and the url's being used to create the hash are unsecured. I detailed below how I fixed this problem by modifying that class.

### Proposed Fix
Editing the hasValidSignature function in "vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php" as shown below.

`
        // Checking if the request was secure, if so then replacing "http://" with "https://".
        if($request->secure()){
            $url = str_replace("http://","https://", $url); 
        }
`

This fixed the problem for me and works both on development unsecured and on production secured.

### Steps To Reproduce:
1. Sign a url using "URL::temporarySignedRoute()".
2. Force https through either your AppServiceProvider with "URL::forceScheme('https')" or through Nginx/Apache.
3. Navigate to the signed url and you will recieve a "403 Invalid Signature" error.
4. Data dumping the variables in "vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php" on the hasValidSignature function results in showing that it is using unsecured url's.

**Comment by NT-andrewgosselin** [comment]
Update, now that we are forcing https again the $request->secure is also returning false so on the production server I am just using "$url = str_replace("http://","https://", $url); " without the if statement to solve this issue until I find a better solution.

**Comment by driesvints** [comment]
Are you behind a load balancer? Have you configured your trusted proxies correctly?

https://laravel.com/docs/5.8/requests#configuring-trusted-proxies

**Comment by NT-andrewgosselin** [comment]
I am not behind a load balancer but just in case I have configured the trusted proxies to the following with no result a few days ago.
`/**
* The trusted proxies for this application.
*
* @var array|string
*/
protected $proxies = '*';

/**
* The headers that should be used to detect proxies.
*
* @var int
*/
protected $headers = Request::HEADER_X_FORWARDED_ALL;`

**Comment by NT-andrewgosselin** [comment]
Without the line I mentioned in "UrlGenerator.php".
`$url = str_replace("http://","https://", $url);`

It returned a different signature that was based on an unsecured url which caused a "403 Invalid Signature". 

Upon adding that line back my problem was fixed and it returned the correct hash based off the secured url.

**Comment by driesvints** [comment]
I've just tested it with the steps you provided in your original comment so I believe everything works as intended and probably not a bug but somewhere a misconfiguration perhaps. It's best that you try a support channel instead:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Good luck.

**Comment by bolechen** [comment]
same issues for me +1

**Comment by andrewgosselin-nt** [comment]
https://github.com/laravel/framework/pull/31434

For anyone wondering what the root of the problem is and why it hasn't been fixed, here's the pull request I made explaining the issue that got denied for pretty much no reason at all.

**Comment by oulfr** [comment]
this issue is related to nginx configuration in the documentation there is:

#add_header X-Frame-Options "SAMEORIGIN";

you need just to comment out this line and it will work

**Comment by ProteanCode** [comment]
> this issue is related to nginx configuration in the documentation there is:
> 
> #add_header X-Frame-Options "SAMEORIGIN";
> 
> you need just to comment out and dont forget in your TrustProxies: protected $proxies="*";

You know you are punching a hole in the wall to fix another one? :)

**Comment by imtommychan1215** [comment]
My workaround for this case:

Route:
`   Route::middleware(['signed:relative'])->group(function () { ... });`

Signed Route:
`URL::temporarySignedRoute('downloadDiscoveryDocument', now()->addDay(), '', false)`

**Comment by robmoraes** [comment]
I have the same problem. In my case an aws elb environment.

I found the problem in the code below:

The signature is generated in the signedRoute method using the `$this->route` method to generate the url. This method generates the url with HTTPS.

`$this->route($name, $parameters, $absolute)`

Below is the complete code of the method:

Illuminate\Routing\UrlGenerator

`public function signedRoute($name, $parameters = [], $expiration = null, $absolute = true)
    {
        $this->ensureSignedRouteParametersAreNotReserved(
            $parameters = Arr::wrap($parameters)
        );

        if ($expiration) {
            $parameters = $parameters + ['expires' => $this->availableAt($expiration)];
        }

        ksort($parameters);

        $key = call_user_func($this->keyResolver);

        return $this->route($name, $parameters + [
            'signature' => hash_hmac('sha256', $this->route($name, $parameters, $absolute), $key),
        ], $absolute);
}`

Still in the Illuminate\Routing\UrlGenerator class, the hasCorrectSignature method is used to check the signature. It uses `$request->url()` to generate the URL, and this method generates the url with HTTP.

`$url = $absolute ? $request->url() : '/'.$request->path();`

Illuminate\Routing\UrlGenerator
`public function hasCorrectSignature(Request $request, $absolute = true)
{
    $url = $absolute ? $request->url() : '/'.$request->path();

    $queryString = ltrim(preg_replace('/(^|&)signature=[^&]+/', '', $request->server->get('QUERY_STRING')), '&');

    $signature = hash_hmac('sha256', rtrim($url.'?'.$queryString, '?'), call_user_func($this->keyResolver));

    return hash_equals($signature, (string) $request->query('signature', ''));
}`

Tenho o `URL::forceScheme('https')` configurado no projeto e mesmo assim isso ocorre.

I still haven't found a solution.

**Comment by robmoraes** [comment]
I have the same problem. In my case an aws elb environment.

I found the problem in the code below:

The signature is generated in the signedRoute method using the `$this->route` method to generate the url. This method generates the url with HTTPS.

`$this->route($name, $parameters, $absolute)`

Below is the complete code of the method:

Illuminate\Routing\UrlGenerator
```PHP
public function signedRoute($name, $parameters = [], $expiration = null, $absolute = true)
    {
        $this->ensureSignedRouteParametersAreNotReserved(
            $parameters = Arr::wrap($parameters)
        );

        if ($expiration) {
            $parameters = $parameters + ['expires' => $this->availableAt($expiration)];
        }

        ksort($parameters);

        $key = call_user_func($this->keyResolver);

        return $this->route($name, $parameters + [
            'signature' => hash_hmac('sha256', $this->route($name, $parameters, $absolute), $key),
        ], $absolute);
}
```

Still in the Illuminate\Routing\UrlGenerator class, the hasCorrectSignature method is used to check the signature. It uses `$request->url()` to generate the URL, and this method generates the url with HTTP.

`$url = $absolute ? $request->url() : '/'.$request->path();`

Illuminate\Routing\UrlGenerator
```PHP
public function hasCorrectSignature(Request $request, $absolute = true)
{
    $url = $absolute ? $request->url() : '/'.$request->path();

    $queryString = ltrim(preg_replace('/(^|&)signature=[^&]+/', '', $request->server->get('QUERY_STRING')), '&');

    $signature = hash_hmac('sha256', rtrim($url.'?'.$queryString, '?'), call_user_func($this->keyResolver));

    return hash_equals($signature, (string) $request->query('signature', ''));
}
```

I have `URL::forceScheme('https')` configured in the project and it still happens.

I still haven't found a solution.

**Comment by karna-guild** [comment]
Make sure you have the right headers being passed in your Nginx file such as 

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-Proto $scheme;

**Comment by abdallahalsamman** [comment]
this happened when I was using cloudflare's SSL

https://github.com/monicahq/laravel-cloudflare this fixed it for me, right now the readme is for laravel 11 make sure to go through README.md's history to find the install instructions for your laravel version.
