### ISSUE TITLE
Task Scheduling - method emailOutputOnFailure not work.

### ISSUE THREAD

**Issue by AndreyKachanov** [laravel/framework#28956]
If I use the method emailOutputTo, the console output is sent to my email. All is well.
But if I use the emailOutputOnFailure method, then nothing works. Nothing is sent to the email. The documentation says - If you only want to e-mail the output if the command fails, use the emailOutputOnFailure method.
 My console command code is:
    public function handle (): bool
    {
        $ this-> error ("Test error");
        return false;
    }
The latest version of laravel.

**Comment by AndreyKachanov** [comment]
The latest version of laravel - 5.8.26

**Comment by laurencei** [comment]
I think you would need to throw an uncaught exception in the function to get the result you want - does that solve it?

**Comment by AndreyKachanov** [comment]
How? I did the following in Kernel.php -
        try {
            $schedule->command(ParseIssuesCommand::class)
                ->everyMinute()
                ->emailOutputOnFailure('text123@yandex.ru');
        } catch (\Exception $e) {
            file_put_contents("test.txt", $e->getMessage());
        }
The catch block probably does not work at all, the file is not created. 
Try also does not work out - nothing is sent to the email.

**Comment by AndreyKachanov** [comment]
> I think you would need to throw an uncaught exception in the function to get the result you want - does that solve it?

How? I did the following in Kernel.php -
try {
$schedule->command(ParseIssuesCommand::class)
->everyMinute()
->emailOutputOnFailure('text123@yandex.ru');
} catch (\Exception $e) {
file_put_contents("test.txt", $e->getMessage());
}
The catch block probably does not work at all, the file is not created.
Try also does not work out - nothing is sent to the email.

**Comment by laurencei** [comment]
No - inside the command:

```
public function handle (): bool
{
      abort(500);
}
```

does that send the email?

**Comment by AndreyKachanov** [comment]
> No - inside the command:
> 
> ```
> public function handle (): bool
> {
>       abort(500);
> }
> ```
> 
> Then your schedule:
> 
> ```
> $schedule->command(ParseIssuesCommand::class)
> ->everyMinute()
> ->emailOutputOnFailure('text123@yandex.ru');
> ```
> 
> does that send the email?

Yes, it sends. And why is this happening? I did not understand how it works? Will the letter be sent if some kind of failure occurs? I thought that the email is sent when public function handle () returns false ....
