### ISSUE TITLE
Database notifications not working

### ISSUE THREAD

**Issue by abhi99sind** [laravel/framework#28953]
- Laravel Version: 5.8
- PHP Version: 7.3
- Database Driver & Version:

### Description:
I was making a notification system when someone comments on a post the post owner gets a notification which i wanted to store in database but it is saving. When I use email method it works.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
