### ISSUE TITLE
(new MailMessage)->view("email.test")->render() throws "View [] not found" error

### ISSUE THREAD

**Issue by sudkumar** [laravel/framework#28958]
- Lumen Version: 5.8.*
- illuminate/mail Version: 5.8.*
- illuminate/notifications Version: 5.8.*
- PHP Version: 7.2.14

### Description:
In my lumen based project, I am using `illuminate/notifications` and `illuminate/mail` package to set the notification emails. Before sending notification, I want to preview the rendered content of notification.

I am previewing Mail Notifications by calling the `(new MailMessage())->view("emails.testing_template")->render()` from a testing route. When accessing the route, I got an error stating `View [] not found.`

### Steps To Reproduce:

1. Bootstrap an application with lumen
2. Install the dependencies: `composer require illuminate/mail illuminate/notifications`
3. Register the service providers
```php
## bootstrap/app.php
$app->register(Illuminate\Notifications\NotificationServiceServiceProvider::class);
$app->register(Illuminate\Mail\MailServiceProvider::class)
```
4. Alias mailer
```php
## bootstrap/app.php
$app->alias('mailer', Illuminate\Mail\Mailer::class);
$app->alias('mailer', Illuminate\Contracts\Mail\Mailer::class);
$app->alias('mailer', Illuminate\Contracts\Mail\MailQueue::class);
```
5. Create a notification for testing purpose
```php
## app/Notifications/Example.php
<?php
namespace App\Notifications;

use Illuminate\Notifications\Notification;
use Illuminate\Notifications\Messages\MailMessage;

class Example extends Notification
{
    public function via()
    {
        return ['mail'];
    }

    public function toMail()
    {
        return (new MailMessage())->view("email.test");
    }
}
```
6. Create a view for testing
```php
## resources/views/email/test.blade.php
<h1>It works</h1>
```
7. Now, create a route for testing the notification
```php
## routes/web.php
$router->get("/test/email", function () {
  return (new App\Notifications\Example())->toMail()->render();
});
```

Instead of getting,
> It works

We will get an error stating
> View [] not found

### Possible Solution

After digging into the error message, I found that https://github.com/laravel/framework/blob/1d8ec9afdedc79314c18715056b8143d7e1fac31/src/Illuminate/Notifications/Messages/MailMessage.php#L290-L295
the render method only respects the `$this->markdown`, which in my case, is not even set.

There are two possible solutions

1. Use `markdown` instead of `views`. 
```diff
  (new MailMessage())
-    ->view("email.testing_template")
+    ->markdown("email.testing_template")
      ->render()
```
This will require no change in the library. But I don't know if it is what is expected by the apis. May be docs should mention it somewhere. As far as I know, Markdown is a super set of Views so any view should just work for markdowns. Please correct me if I am wrong!.

2. Update the `render` method to consider the `$this->view` along with the `$this->markdown`
```diff
  public function render () {
    return Container::getInstance()
      ->make(Markdown::class)
-    ->render($this->markdown, $this->data())
+    ->render($this->markdown ?? $this->view, $this->data())
  }
```

**Comment by driesvints** [comment]
I think it's best that in this case you just use the Laravel framework which was intended to work with these components and not Lumen. Lumen is only intended for highly scalable apis. In any case if you're facing an integration problem with any of the components it's best that you ask on a support channel.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks.

**Comment by sudkumar** [comment]
Alright. Thanks @driesvints.

**Comment by awebartisan** [comment]
Hi, I am facing the mentioned issue in Laravel framework's Notification.
Laravel version 5.8.29

I have tried on fresh Laravel's copy and still facing same exception.

**Comment by sudkumar** [comment]
@awebartisan Yes, I can confirm that. I bootstrapped a new project (`5.8.31`) and tested. It's still there. It works when `markdown` is used instead of `view` 

```diff
- return (new MailMessage)->view('dummy');
+ return (new MailMessage)->markdown('dummy');
```

The issue is with the `MailMessage->render` as mentioned in the first comment (https://github.com/laravel/framework/issues/28958#issue-460803128)

@driesvints Can you please look into it ? I am happy to create a fix PR.

**Comment by driesvints** [comment]
Can you upload a repo to github which reproduces the problem?

**Comment by sudkumar** [comment]
@driesvints  Here it is. https://github.com/sudkumar/notification_render_issue_in_laravel

**Comment by driesvints** [comment]
@sudkumar there's no "dummy" view in your repo: https://github.com/sudkumar/notification_render_issue_in_laravel/tree/master/resources/views

Please try a support channel. Thanks.

**Comment by sudkumar** [comment]
I am using the `welcome` view instead of a `dummy` view. Please see the Dummy notification:

https://github.com/sudkumar/notification_render_issue_in_laravel/blob/dc8a916e4b3f63d8ec84e79dcd8eb5f4f8fe0524/app/Notifications/Dummy.php#L41-L44

**Comment by driesvints** [comment]
@sudkumar can you please try a support channel first? If you can actually confirm the bug feel free to respond back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

**Comment by sudkumar** [comment]
Thank you. No problem. :)

**Comment by muhtarudinsiregar** [comment]
maybe you can check here, already fixed in https://github.com/laravel/framework/pull/29698

**Comment by sudkumar** [comment]
@muhtarudinsiregar Thank you for the reference.

I was sure of the bug as it was clear from the code itself and now it is fixed. 🍻
