### ISSUE TITLE
URL::route doesn't return absolute path

### ISSUE THREAD

**Issue by notflip** [laravel/framework#28962]
- Laravel Version: 7.1.3
- PHP Version: 5.8.*
- Database Driver & Version: MySQL

### Description:
When using 

    URL::route('test.index'); 

(or any route name), from the following page
http://app.test/sitemap.xml

the returned result is:
**https://test.app/sitemap.xml/test**

The desired output is 
**https://test.app/test**

Even though the absolute is set true (it is by default), by not including the third parameter.
I already tried explicitly setting it to true:

    URL::route('test.index', [], true);

### Steps To Reproduce:

Create a route to catch a visit to sitemap.xml, and return a (wrongly) generated route

    Route::get('/sitemap.xml', function () {
         return \URL::route('test');
     });

**Comment by staudenmeir** [comment]
How is the `test` route defined?

**Comment by notflip** [comment]
APP_URL = https://app.test 

Test route:
    
    Route::get('test', function() {return 'test';})->name('test');

**Comment by staudenmeir** [comment]
It works for me. Can you reproduce this on a fresh Laravel installation?

**Comment by mrcat323** [comment]
You should probably set:
```PHP
Route::get('/test', function () { return 'test'; })->name('test');
``` 
instead of:
```PHP
Route::get('test', function() {return 'test';})->name('test');
```
My bet is, it's all about the `/` before `test`

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.

**Comment by haydenk** [comment]
Adding this here because I see this being spread around without much correction.

APP_URL is for the console only, it has no effect url the web app uses. It’s in the config/app.php file.

```php
    /*
    |--------------------------------------------------------------------------
    | Application URL
    |--------------------------------------------------------------------------
    |
    | This URL is used by the console to properly generate URLs when using
    | the Artisan command line tool. You should set this to the root of
    | your application so that it is used when running Artisan tasks.
    |
    */

    'url' => env('APP_URL', 'http://localhost'),
```

You can remove APP_URL and the web app will function just fine.

I have had issues getting Laravel to work in Codespaces with php-fpm. I get the page to load but all the routes show `http://localhost:8000` instead of the proxied url from GitHub.
