### ISSUE TITLE
php artisan queue:retry all executing in the wrong order

### ISSUE THREAD

**Issue by andreladocruz** [laravel/framework#28961]
- Laravel Version: 5.8.24
- PHP Version: 7.2
- Database Driver & Version: MYSQL 

### Description:
When executing the php artisan queue:retry all command the items are being processed in the wrong order, the newest to older, instead of older to newest.

### Steps To Reproduce:
have some jobs in the failed table, run php artisan queue:retry all and see the jobs ids being pulled to queue.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by andreladocruz** [comment]
@driesvints , this is not a doubt or question.

When you do a php artisan queue:retry all the jobs are being added to the queue in the wrong order, from the more recent to the older.

This is not what a "first in, first out" queue should work.

**Comment by driesvints** [comment]
@andreladocruz can you first try a support channel? I'll be happy to help if you can actually identify this as a bug.

**Comment by andreladocruz** [comment]
@driesvints , sure! 

Thanks

**Comment by dsohanivive** [comment]
having the same issue @andreladocruz did you happen to find a solution? i've searched the forums and havent found a thread

**Comment by andreladocruz** [comment]
@dsohanivive , not yet. 

The process to report a bug is too long that I forget to follow it. 

Maybe @driesvints reopen this to solve. =)
