### ISSUE TITLE
Middleware for route groups are not validated as being valid

### ISSUE THREAD

**Issue by boyleninc** [laravel/framework#28979]
- Laravel Version: 5.8.x
- PHP Version: 7.x
- Database Driver & Version: MySQL (MariaDB)

### Description:
Not sure if this is necessarily a bug or not, but rather a suggestion to help prevent against possible security vulnerabilities or other issues.

When defining routes, you can set a group and pass in a key of 'middlware' but a value of null and no exception is thrown.  

This led to an issue recently for a project I was working on.  A developer changed the name of a config key in the middleware itself, but forgot to change it in the routes.   

For example, this code was defined originally:  

```
Route::group([
    'namespace' => 'something',
    'middleware' => config("auth-guard")
], function () {
    Route::resource('something', 'SomeController');
});
```

However, after the change was made where the config name was changed to `package-auth-guard`, `config("auth-guard")` was returning null without us knowing, which means that in this case, our routes were not protected at all and open to unauthenticated users.   

Is there any use case where a null value could be passed to a route middleware group intentionally?  Or is this something that should be changed to prevent others from having this same type of issue in the future?

My apologies in advance if this does not qualify as a bug or if I should not be posting this here.  This is my first time reporting a potential issue for Laravel.

**Comment by czzhengkw** [comment]
The code you run actually as below:
```php
Route::group([
    'namespace' => 'something',
    'middleware' => null
], function () {
    Route::resource('something', 'SomeController');
});
```

In my computer, this will crash.

![image](https://user-images.githubusercontent.com/4585146/60336057-e45c9c80-99d1-11e9-9245-b5bc7407602e.png)

**Comment by driesvints** [comment]
@boyleninc it's perfectly possible to unset middleware. In this case I recommend to write tests that verify the expected behavior so you know that the functionality keeps on working. We cannot unfortunately account for config changes as that's done in userland.
