### ISSUE TITLE
Throwing PDOException 22007 when Seeding in different MariaDB version

### ISSUE THREAD

**Issue by SupianIDz** [laravel/framework#28990]
- Larave Version: 5.8.24
- PHP Version:7.2.19
- Database Driver & Version: MariaDB - 10.3.13

### Description:
Throwing PDOException [22007] with message `Invalid datetime format: 1292 Incorrect datetime value: '2019-02-29 02:58:42' for column dev.logs.datetime at row 1")` when trying to seeding in production server.

When deploying on a production server there is always an error like the one above, but the server development has no errors at all.

this is the second specification of the server:

## dev (my laptop)
- PHP 7.3.6
- MariaDB 10.1.40
- Apache
- Linux Mint 19.1 Tessa

## production
- Google Instance
- PHP  7.2.19
- MariaDB - 10.3.13
- Apache
- Ubuntu 18.04

**Comment by mfn** [comment]
`2019-02-29 02:58:42`

This is not a valid date; there was no February 29th this year (2019 is not a leap year). This problem is not within Laravel.

**Comment by SupianIDz** [comment]
Ow, sorry, my bad.. Thanks
