### ISSUE TITLE
Reflection exception in Routes:resource()

### ISSUE THREAD

**Issue by KartaviK** [laravel/framework#28995]
- Laravel Version: 5.8
- PHP Version: 7.2
- Database Driver & Version: 10.1.34-MariaDB

### Description:
in `routes/web`  i wnat add resource for categories. I have `App\Http\Controllers\CategoryController` and add next code:
```php
use App\Http\Controllers;

Routes::resource('categories', Controllers\CategoryController::class);
```

After console command `artisan routes:list` catch an exception
```bash
ReflectionException  : Class App\Http\Controllers\App\Http\Controllers\CategoryController does not exist

  at path-to-project\vendor\laravel\framework\src\Illuminate\Container\Container.php:790
```

If to method `resource(...)` put string `'CategoryController'` - all will be ok

### Steps To Reproduce:
Create `CategoryController` with `artisan`
Add to `routes/web` next code:
```php
use App\Http\Controllers;

Routes::resource('categories', Controllers\CategoryController::class);
```

**Comment by devcircus** [comment]
Routes::resource('categories', CategoryController::class);

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by staudenmeir** [comment]
You can't pass a whole class path to `Route::resource()`, only the part after `App\Http\Controllers\`:

```php
Route::resource('categories', 'CategoryController');
```

**Comment by devcircus** [comment]
Doh! Because I use the full path in all of my routes, I typed ::class without realizing it in my response above.  Sorry @KartaviK for being misleading.
