### ISSUE TITLE
ServiceProvider::mergeConfigFrom ignores cached configs generated via the config:cache command

### ISSUE THREAD

**Issue by matthewnessworthy** [laravel/framework#28997]
- Laravel Version: 5.8.26
- PHP Version: 7.2.19
- Database Driver & Version: MySQL 5.7.26

### Description:
`mergeConfigFrom` in `Illuminate\Support\ServiceProvider` does not respect cached configs and merges irrespective on whether Laravel is using a cached config or not.
`loadRoutesFrom` correctly checks whether the app routes are cached prior to loading routes, `mergeConfigFrom` should follow the same pattern.

### Steps To Reproduce:
include a Service Provider that calls `mergeConfigFrom` (e.g., TinkerServiceProvider)
call the artisan command `config:cache` (`php artisan config:cache`)
see that the tinker configs are merged from the 3rd party package

**Comment by xuanquynh** [comment]
This issue has been solved, we can close it.
