### ISSUE TITLE
Inconsistent `Request::input` behaviour

### ISSUE THREAD

**Issue by khooz** [laravel/framework#29009]
- Laravel Version: 5.8.24
- PHP Version: 7.3.6
- Database Driver & Version: MariaDB 10.4 (Stable)

### Description:
When using `Request::input`, the expected behaviour is that it returns the wholesome input data for the specified field (or all data if argument 1 is null).

The actual behaviour is understandably different when files are involved; yet, it seems unnatural, out of the flow, and inconsistent that leads to many branching in code when dealing with optional input data. This issue is chosen to be a bug report because `Request::input` is expected to return all inputs, especially when they are mixed and indexed as multi-level arrays.

The PHP internally uses `$_FILES` (or `$HTTP_POST_FILES` [deprecated]) to store uploaded file 
information and `$_POST` for other input data, and I assume Laravel (needlessly) followed that convention. The `$_FILES` itself is a mess especially if your data is indexed as arrays (seq. or assoc.). It is represented as an `array[5][]` of `name`, `type`, `tmp_name`, `error` and `size`.

Though `$_FILES` representation is adequate, it's far from convenient; what frameworks are expected for. It's far more consistent with the current input data scheme and flow that `Request::input` actually accesses and returns all sorts of data based on their field names and at the leafs of this tree, as a value, represents files differently, like a `File` object or an associative `array[5]` just like `$_FILE`, but with one string entry for each index, instead of a mirrored array of field names in each index.

### Steps To Reproduce:

Request (using cURL):
```bash
curl -X POST \
  http://example.com \
  -H 'Accept: */*' \
  -H 'Host: example.com' \
  -H 'accept-encoding: gzip, deflate' \
  -H 'content-length: xxxxx' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
  -F 'data[0][user_id]=1' \
  -F 'data[0][name]=usr_name' \
  -F 'data[0][media][profile_picture]=@/user/home/sample-pic.png' \
  -F 'data[0][media][profile_header]=@/user/home/sample-pic.png' \
  -F 'data[0][media][additional_media][]=@/user/home/sample-pic.png' \
  -F 'data[0][media][additional_media][]=@/user/home/sample-pic.png' \
  -F 'data[0][media][additional_media][]=@/user/home/sample-pic.png'
```

Somewhere in the wild `AController@method(\Illuminate\Http\Request $request)`:
```
...php
$data = $request->input('data') ?? [];
dd($data, $_FILES);
...
```

What you get as a response:

```php
array:1 [
  0 => array:6 [
    "user_id" => "1"
    "name" => "usr_name"
  ]
]
array:1 [
  "data" => array:5 [
    "name" => array:1 [
      0 => array:1 [
        "media" => array:3 [
          "profile_picture" => "sample-pic.png"
          "profile_header" => "sample-pic.png"
          "additional_media" => array:3 [
            0 => "sample-pic.png"
            1 => "sample-pic.png"
            2 => "sample-pic.png"
          ]
        ]
      ]
    ]
    "type" => array:1 [
      0 => array:1 [
        "media" => array:3 [
          "profile_picture" => "image/png"
          "profile_header" => "image/png"
          "additional_media" => array:3 [
            0 => "image/png"
            1 => "image/png"
            2 => "image/png"
          ]
        ]
      ]
    ]
    "tmp_name" => array:1 [
      0 => array:1 [
        "media" => array:3 [
          "profile_picture" => "/tmp/php/php81CE.tmp"
          "profile_header" => "/tmp/php/php81CF.tmp"
          "additional_media" => array:3 [
            0 => "/tmp/php/php81D0.tmp"
            1 => "/tmp/php/php81D1.tmp"
            2 => "/tmp/php/php81D2.tmp"
          ]
        ]
      ]
    ]
    "error" => array:1 [
      0 => array:1 [
        "media" => array:3 [
          "profile_picture" => 0
          "profile_header" => 0
          "additional_media" => array:3 [
            0 => 0
            1 => 0
            2 => 0
          ]
        ]
      ]
    ]
    "size" => array:1 [
      0 => array:1 [
        "media" => array:3 [
          "profile_picture" => xxxxx
          "profile_header" => xxxxx
          "additional_media" => array:3 [
            0 => xxxxx
            1 => xxxxx
            2 => xxxxx
          ]
        ]
      ]
    ]
  ]
]
```

Cheers!

**Comment by driesvints** [comment]
I'm sorry but this isn't how things work at the moment. You may check the docs on how to handle files in requests: https://laravel.com/docs/5.8/requests#files

Or submit an issue to the ideas repo if you believe this can be handled differently. In any case, this isn't a bug. We cannot control for how the $_FILES global gets filled.
