### ISSUE TITLE
hasMany relationship's automatic foreign key "deduction" not working on Pivot model

### ISSUE THREAD

**Issue by MartinP7r** [laravel/framework#29017]
- Laravel Version: 5.8.26
- PHP Version: 7.1.30
- Database Driver & Version:
PostgreSQL 9.6.13
### Description:
```php
use Illuminate\Database\Eloquent\Relations\Pivot;

class Order extends Pivot
{
    public function orderItems()
    {
        return $this->hasMany('App\OrderItem');
    }
}
```
won't let me do
```php
Event::with('orders.orderItems')->find($id);
```
even though `Pivot` inherits from `Model`  
it produces an error like:
```sql
SQLSTATE[42601]: Syntax error: 7 ERROR:  """"またはその近辺で区切りつき識別子の長さがゼロです
LINE 1: select * from "order_items" where "order_items"."" in (34, 3...
                                                        ^ (SQL: select * from "order_items" where "order_items"."" in (34, 35, 36, 37))
```
Sorry about the Japanese, but you can see clearly that the foreign key value is blank in the query.

explicit mention of foreign and local key is necessary like below.
```php
use Illuminate\Database\Eloquent\Relations\Pivot;

class Order extends Pivot
{
    public function orderItems()
    {
        return $this->hasMany('App\OrderItem', 'order_id', 'id');
    }
}
```
then it works fine.

### Steps To Reproduce:
see above

edit: it works without the explicit keys for a `belongsTo` relationship

**Comment by driesvints** [comment]
I think it's probably better if you use a regular model in this situation. Pivot models where never meant to have these relationships afaik. 

That being said, can you provide a little more info? Maybe an repository that replicates the problem so we can investigate some more?

**Comment by staudenmeir** [comment]
This behavior isn't ideal, but I wouldn't necessarily consider it a bug.

Eloquent models use `getForeignKey()` to generate the default name for foreign keys, but pivot models override this method for a different purpose.

As @driesvints points out, pivot models typically don't have `HasMany` relationships. You can define these relationships, it's just not as convenient as with regular models.

**Comment by driesvints** [comment]
I think it's indeed better that you just use a regular model in this case. Pivot models aren't meant to have these sorts of relationships. Maybe a note to the docs is in order here.

**Comment by driesvints** [comment]
Sent in a PR for this here: https://github.com/laravel/docs/pull/5275

**Comment by driesvints** [comment]
@staudenmeir Taylor noted that this should be possible so there might be something else we're missing.

https://github.com/laravel/docs/pull/5275#issuecomment-507827068

**Comment by staudenmeir** [comment]
@driesvints I think we only had a misunderstanding: Pivot models do support all relationships, but require users to explicitly set the foreign key. This affects all relationships except `BelongsTo` /`MorphTo`.

**Comment by driesvints** [comment]
@staudenmeir gotcha
