### ISSUE TITLE
Factory with nested input data crashes with "Array to string conversion"

### ISSUE THREAD

**Issue by emilhem** [laravel/framework#29010]
- Laravel Version: 5.8.26
- PHP Version: 7.2.19-0ubuntu0.18.04.1
- Database Driver & Version: Postgresql (11.4-1.pgdg90+1 via Docker container)

### Description:
Utilizing factories with nested array data in its `create` input causes issues an `Array to string conversion` exception.

### Steps To Reproduce:
Create a factory that is dependent on another factory and pass the data from the original factory create in a test file through to the final factory.

I created a repo for easy reproduction: https://github.com/emilhem/laravel-factory-bug
The only changed files from a default laravel installation are two migrations, two factories, two models and one test case (list in repo).

**Comment by staudenmeir** [comment]
The values passed to `create()` are used as the model's attributes, that's why you're getting a nested array:

```php
[
    "name" => "producty",
    "box_id" => 1,
    "box" => [
        "name" => "boxy",
    ],
]
```

If you want to create boxes with custom names, you'll need to do that outside of the factory and then pass the `id` to `create()`.

**Comment by emilhem** [comment]
Hmm, that's quite unfortunate.
