### ISSUE TITLE
Collection item values were changed in loop even not using reference

### ISSUE THREAD

**Issue by lehien** [laravel/framework#29018]
- Laravel Version: 5.3.31
- PHP Version: 7.1.29
- Database Driver & Version: MySQL 5.6.44

### Description:
I just loop through a collection, find unique element by some attribute values then put it to second collection, change data in the second collection, but the original value of the first collection was changed even I did't pass by reference inside foreach.

### Steps To Reproduce:
I loop through a collection like this:
```php
$data = Collection(
['category' => 1, 'type' => 'sp', 'count' => 10], 
['category' => 1, 'type' => 'sp', 'count' => 10],
['category' => 2, 'type' => 'sp', 'count' => 20],...
);

$list = collect(); // store unique items

foreach ($data as $item) {
	$key = $item->category . '_' . $item->type;
	$check_item = $list->get($key);
	if ($check_item == null) {
		$list->put($key, $item);
	} else {
		$check_item->count += $item->count; // this causes my problem
		$list->put($key, $check_item);
	}
}
```

Expected result:
- $list:
```php
Collection(
'1_sp' => ['category' => 1, 'type' => 'sp', 'count' => 20],
'2_sp' => ['category' => 2, 'type' => 'sp', 'count' => 20],
...);
```
- $data: (as original)
```php
 Collection(
['category' => 1, 'type' => 'sp', 'count' => 10], 
['category' => 1, 'type' => 'sp', 'count' => 10],
['category' => 2, 'type' => 'sp', 'count' => 20],...
);
```
Actual result:
- $list: same as expected result above.
- $data: has been changed
```php
 Collection(
['category' => 1, 'type' => 'sp', 'count' => 20], 
['category' => 1, 'type' => 'sp', 'count' => 10],
['category' => 2, 'type' => 'sp', 'count' => 20],...
);
```
If I change 
```php
$list->put($key, $item);
```
to 
```php
$list->put($key, clone $item);
```
problem is solved.

If I repleace collection by php array, there is no problem. 
Is this Laravel Collection bug or Collection function?

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
