### ISSUE TITLE
Datatype mismatch using Eloquent Model

### ISSUE THREAD

**Issue by exy** [laravel/framework#29023]
- Laravel Version: 5.8.26
- PHP Version: 7.1.30
- Database Driver & Version: 
pgsql => 11.3

Database : Postgresql 10

### Description:
When using (new Model())->save() on PostgreSQL database, the Illuminate\Database\Connection cast boolean to integer in the prepareBindings and bindValues methods.

### Steps To Reproduce:
Create a table on MySql or Postgresql :
```
Schema::connection('postgresql')->create('test', function (Blueprint $table) {
      $table->bigIncrements('id');
      $table->boolean('column_boolean');
});
```

Create a Model :
```
use Illuminate\Database\Eloquent\Model;

class TestInsert extends Model
{
    protected $table = 'test';
    protected $primaryKey = 'id';
    protected $connection = 'postgresql';
}
```

Finally insert a new value :
$test = new TestInsert();
$test->save();

=> it should failed converting :
`SQLSTATE[42804]: Datatype mismatch: 7 ERROR: column "column_boolean" is of type boolean but expression is of type integer`

**Comment by mfn** [comment]
FTR in general PgSQLbooleans work fine/as expected for me. Laravel 5.8.26, PHP 7.2.19, PgSQL 9.6

In your example you are not setting any attributes?

Also your `column_boolean` is _not_ `nullable()`. So without setting any attribute, you should get an error; but a different one.

Is this example complete?

Can you show the actual statement generated, e.g. `\DB::listen(function ($query) { \Log::debug($query->sql);});`

**Comment by exy** [comment]
You are right, you need to add :
$table->boolean('boolean')->nullable(false)->default(false);

And set the attribute to true :
$test->column_boolean = true;

This little code cast to integer :
```
if ($value instanceof DateTimeInterface) {
     $bindings[$key] = $value->format($grammar->getDateFormat());
} elseif (is_bool($value)) {
     $bindings[$key] = (int) $value;
}
```
And you cannot insert an integer value in a boolean column type, it should be converted in string

**Comment by mfn** [comment]
Again, this totally works for me.

Is it an issue with newer Postgres _server_ version?

**Comment by exy** [comment]
I don't think it's an issue with newer Postgres server version, I've tried this on Postgres server 9.6 and 10 :
```
create table test
(
    id           integer               not null primary key,
    column_boolean          boolean default false not null
);
insert into test (id, column_boolean) values (1, 1);
```

Each time this error :
```
[42804] ERROR: column "column_boolean" is of type boolean but expression is of type integer
You will need to rewrite or cast the expression.
```

If I try with this (note that I insert string and not an integer) :
`insert into test (id, column_boolean) values (2, '1');`

It works

**Comment by staudenmeir** [comment]
Does `DB::table('test')->insert(['id' => 1, 'column_boolean' => true])` work for you?

**Comment by exy** [comment]
Same :

> SQLSTATE[42804]: Datatype mismatch: 7 ERROR: column "column_boolean" is of type boolean but expression is of type integer
> LINE 1: insert into "test" ("column_boolean") values (1)
> ^
> HINT: You will need to rewrite or cast the expression. (SQL: insert into "test" ("column_boolean") values (1))

**Comment by staudenmeir** [comment]
That's odd, it works for me on PostgreSQL 10.6 (in Homestead).

Please post the connection's settings in `config/database.php`.

**Comment by exy** [comment]
'driver' => 'pgsql',
'host' => 'db',
'port' => '5432',
'database' => 'postgres',
'username' => 'postgres',
'password' => 'toto',
'charset' => 'utf8',
'prefix' => '',
'options' => [
                PDO::ATTR_PERSISTENT => true,
                PDO::ATTR_EMULATE_PREPARES => true,
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
],

**Comment by staudenmeir** [comment]
The error is caused by `PDO::ATTR_EMULATE_PREPARES => true`, Laravel uses `false` by default.

**Comment by exy** [comment]
ok that mean we can not let PDO prepare the statement with Postgres connection

**Comment by staudenmeir** [comment]
No, not with the current implementation. Do you need `ATTR_EMULATE_PREPARES` to be `true` ?

**Comment by ionutantohi** [comment]
Be aware that having ATTR_EMULATE_PREPARES=true causes other problems with MySQL on recent versions of php. See ( #23850, #27596, #26817, #25818).

**Comment by owengo** [comment]
@staudenmeir : with postgresql, we have to use a connection pooler, which allows sharing database sessions. This makes it impossible to use prepared statements, because this creates a temporary stored procedure for each statement.

**Comment by daniel-de-wit** [comment]
FYI: [Php 8.0.5 has a bug](https://bugs.php.net/bug.php?id=80892) that causes the same message when using Postgresql

**Comment by ALTELMA** [comment]
FYI: PHP 7.4.1 still has a bug that causes the same message when using Postgresql. 
Now we try to avoid this issue by changed the boolean to a string instead.

Ex. 'true', 't' etc

This options not working PDO::ATTR_EMULATE_PREPARES => true in Lumen

If anyone found the solution please share with me :)

**Comment by Messhias** [comment]
Anyway even changing to:
```"options" => [
                PDO::ATTR_EMULATE_PREPARES => true
            ],```
            
In my pgsql connection still don't work, and even more, this is doesn't make any sense you transpile a typo bool to integer or string, since the database has their database (and so far I remember all supports bool / booleans) so why you just go and transpile it to int?

**Comment by AhmedAli-Qawafel** [comment]
Php image: 8.0-buster
Postgres image: postgres:13.2-alpine

I can confirm that the problem still exist 
```Datatype mismatch: 7 ERROR:  column "is_allowed" is of type boolean but expression is of type integer```

**Comment by ahmedofali** [comment]
Php image: 8.0-buster
Postgres image: postgres:13.2-alpine

I can confirm that the problem still exist
`Datatype mismatch: 7 ERROR: column "is_allowed" is of type boolean but expression is of type integer`

**Comment by ALTELMA** [comment]
@ahmedofali As I try to fix this issue between waiting for the next version of PHP in docker official with version 7.4.19 and 8.0.6

Try to pin your base image stick to 7.4.16-xxx-xxxx and 8.0.5-xxx-xxxx to avoid this issue see the bug report

https://bugs.php.net/bug.php?id=81002

Ex. from my Dockerfile
`FROM php-7.4.16-fpm-alpine`

Normally when you using `8.0-buster` Docker will try to pick the last minor version when building an image. Let check in the container which version exactly.

Now I solved this issue by the way as I preferred until the Docker PHP releases a new version.

Hopefully, the new version fixed this bug. Let's try it :)

PHP: https://github.com/php/php-src/releases

**Comment by koushik355** [comment]
Guys, to workaround this problem.
Use `DB::raw('true')` or `DB::raw('false')`
We can't wait for PHP to fix. This solution is the best solution since it leaves it to the database to do the operation and not depending on PHP to touch anything.
