### ISSUE TITLE
phpcs validaton error (minor)

### ISSUE THREAD

**Issue by tommym9** [laravel/framework#29021]
- Laravel Version: 5.8
- PHP Version: 7.2
- Database Driver & Version: N/A

### Description: 
There is a small code phpcs error in: laravel/framework/src/Illuminate/Http/RedirectResponse.php

<img width="613" alt="Screen Shot 2019-07-02 at 10 04 22 am" src="https://user-images.githubusercontent.com/3606130/60499684-e021cf00-9cb0-11e9-8ad7-075a0bdb090b.png">

**Comment by driesvints** [comment]
Laravel often formats its function calls in this way.
