### ISSUE TITLE
Allow for Redis 5.0

### ISSUE THREAD

**Issue by driesvints** [laravel/framework#29029]
PhpRedis 5.0 was just released but apparently some changes are needed in Laravel before it can be used with the framework. [There's nothing yet in the changelog](https://github.com/phpredis/phpredis/commit/8f1ed94f4618bfaad20ea69683ec1575540d88f2) so unsure what has changed.

We should make sure that no breaking changes are made that would disallow usage of older phpredis versions. Otherwise the changes will have to go to master.

I made a change to the build to only test on the latest 4.x release for now: https://github.com/laravel/framework/commit/05960508e0475d7ce3c501975f365a998f2a6a6d

**Comment by GrahamCampbell** [comment]
Are you referring to these changes?

```
1) Illuminate\Tests\Redis\RedisConnectionTest::it_calculates_intersection_of_sorted_sets_and_stores
ErrorException: Function Redis::zInter() is deprecated
/home/travis/build/laravel/framework/src/Illuminate/Redis/Connections/Connection.php:96
/home/travis/build/laravel/framework/src/Illuminate/Redis/Connections/Connection.php:108
/home/travis/build/laravel/framework/src/Illuminate/Redis/Connections/PhpRedisConnection.php:409
/home/travis/build/laravel/framework/src/Illuminate/Redis/Connections/PhpRedisConnection.php:245
/home/travis/build/laravel/framework/tests/Redis/RedisConnectionTest.php:263
2) Illuminate\Tests\Redis\RedisConnectionTest::it_calculates_union_of_sorted_sets_and_stores
ErrorException: Function Redis::zUnion() is deprecated
/home/travis/build/laravel/framework/src/Illuminate/Redis/Connections/Connection.php:96
/home/travis/build/laravel/framework/src/Illuminate/Redis/Connections/Connection.php:108
/home/travis/build/laravel/framework/src/Illuminate/Redis/Connections/PhpRedisConnection.php:409
/home/travis/build/laravel/framework/src/Illuminate/Redis/Connections/PhpRedisConnection.php:261
/home/travis/build/laravel/framework/tests/Redis/RedisConnectionTest.php:295
```

**Comment by driesvints** [comment]
Those errors and these failures:

```
There were 2 failures:
1) Illuminate\Tests\Redis\RedisConnectionTest::test_it_returns_range_in_sorted_set
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    'jeffrey' => 1
-    'matt' => 5
+    0 => 'jeffrey'
+    1 => 'matt'
 )
/home/travis/build/laravel/framework/tests/Redis/RedisConnectionTest.php:296
2) Illuminate\Tests\Redis\RedisConnectionTest::test_it_returns_rev_range_in_sorted_set
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    'matt' => 5
-    'taylor' => 10
+    0 => 'taylor'
+    1 => 'matt'
 )
/home/travis/build/laravel/framework/tests/Redis/RedisConnectionTest.php:309
```

https://travis-ci.org/laravel/framework/jobs/553192452

**Comment by pxgamer** [comment]
The changes are listed on PECL at the moment. Unless I've made a mistake?
https://pecl.php.net/package-info.php?package=redis&version=5.0.0

**Comment by pxgamer** [comment]
Is this possibly related to the breaking change to `zRange`?
https://github.com/phpredis/phpredis/issues/1555 (phpredis/phpredis@19f3efcfe6e1a32451a543fa186a8f38d250d941)

----

I tried testing it with the new array syntax (seems to be preferred) which seems to resolve the zRange issues:
https://github.com/pxgamer/framework/runs/164789768 (0f2cb2ba35a1e757189200647477ab29b7cf8254)

And the same with the boolean syntax.
https://github.com/pxgamer/framework/runs/164789982 (02699cd502d2ff8678dbea88f796223369b0051a)

----

The deprecated method errors seem to be related to the following commits:

- https://github.com/phpredis/phpredis/commit/a81b4f2d
- https://github.com/phpredis/phpredis/commit/95c8aab9

I've added a test to see if these can be resolved by updating the PhpRedisConnection class.
https://github.com/pxgamer/framework/runs/164800716

This seems to (when combined with the array syntax fix above) resolve the issues with those warnings.

**Comment by ragingdave** [comment]
There is also still likely this issue, https://github.com/laravel/framework/pull/24313 which was merged but then reverted so it's not actually there, but most of the prefix based functions don't work under phpredis at the moment. I unfortunately haven't had a chance to revisit those issues.

**Comment by driesvints** [comment]
@pxgamer thanks. That really helped to get the ball rolling. Sent in a PR here: https://github.com/laravel/framework/pull/29606
