### ISSUE TITLE
Pluralization of phrases in inflector. 

### ISSUE THREAD

**Issue by CristianH033** [laravel/framework#29045]
How can I add a rule to the inflector for pluralization of Spanish phrases?

I have the following problem: I have a model called "Tipo de servicio (TipoDeServicio)".
"Type of service" in English, and the plural in Spanish is "Tipos De Servicio (TiposDeServicio)" but the inflector creates "Tipo De Servicios (TipoDeServicios)", I have added several Spanish words in the irregular array to a ServiceProvider that extends from the inflector class, and the pluralization for words works well, but the order in which the pluralization is applied in the phrases is wrong, it is applied as it is done with the English grammar.

How can I create a rule to apply pluralization to a Spanish phrase?

Thank you.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
