### ISSUE TITLE
Cannot catch \Illuminate\Database\Eloquent\RelationNotFoundException

### ISSUE THREAD

**Issue by Helveg** [laravel/framework#29049]
- Laravel Version: 5.8.23
- PHP Version: 7.1.3
- Database Driver & Version: N/A

### Description:
When calling a nested `->with(['valid.invalid_relation_name'])` the exception cannot be caught.

### Steps To Reproduce:
* Create a new project
* Create 2 models, one related to the other through `valid_relation`
```php
try{ $model->with(['valid_relation.invalid_relation']); } catch(\Exception $e) { echo "caught"; }
```

Edit: It also doesn't work simply on `->with(['invalid_relation'])`

**Comment by staudenmeir** [comment]
The exception is only thrown when the query gets executed:

```php
try {
    $model->with(['valid_relation.invalid_relation'])->get();
} catch(\Exception $e) {                             ^^^^^^^
    echo "caught";
}
```

**Comment by driesvints** [comment]
Please see the response above.
