### ISSUE TITLE
Can't use time(0) columns in SQL server, defaults to time(7) becasue the SQL Server grammar drops the precision

### ISSUE THREAD

**Issue by AlexDanault** [laravel/framework#29058]
- Laravel Version: 5.8.21
- PHP Version: 7.1.19
- Database Driver & Version: SQL Server 2016

### Description:
Migrations cannot use 0 as precision for column type TIME, the schema builder ignores the 0 and doesn't pass it to SQL Server, which results in a time(7) column. time(0) is a valid column type, without fractional seconds.

The problem is here: https://github.com/laravel/framework/blob/e6c8aa0e39d8f91068ad1c299546536e9f25ef63/src/Illuminate/Database/Schema/Grammars/SqlServerGrammar.php#L547

The precision (0) gets evaluated as false, which then drops the precision from the column info.

### Steps To Reproduce:

`
Schema::create('cool_table', function (Blueprint $table) {
    $table->time('day_time', 0);
});
`

In SQL Server, the colunm will be of type time(7) (SQL Server's default for TIME columns when no precision is specified).

**Comment by AlexDanault** [comment]
If anyone is interested, here's a temporary workaround:

`Schema::create('cool_table', function (Blueprint $table) { $table->time('day_time', ' 0'); });`

Because 0 (integer zero) and "0" (string consisting of a zero) gets evaluated as false, for " 0" string consisting of a space and a zero  is true, the 0 makes it into the column definition.

Not super elegant, but it'll do the job for now.

**Comment by staudenmeir** [comment]
Unfortunately, this is a known issue without a simple solution: #26370

You can also use a raw expression:

```php
Schema::create('cool_table', function (Blueprint $table) {
    $table->time('day_time', DB::raw(0));
});
```
