### ISSUE TITLE
[5.8] Validation "different" not working with "sometimes"

### ISSUE THREAD

**Issue by vorexfaiq** [laravel/framework#29066]
The different validation fails when the other value is not present:

`$v = Validator::make(['foo' => 'bar', 'baz' => 'true'], ['foo' => 'different:baz', 'baz' => 'sometimes']);`
`$v->passes(); // true`

`$v = Validator::make(['foo' => 'bar'], ['foo' => 'different:baz', 'baz' => 'sometimes']);`
`$v->passes(); // false`

**Comment by staudenmeir** [comment]
I'm not sure if this is supposed to work.

If `foo` is always present and `baz` may be missing, you can reverse the `different` rule:

```php
$v = Validator::make(['foo' => 'bar'], ['baz' => 'different:foo|sometimes']);
$v->passes(); // true
```

**Comment by vorexfaiq** [comment]
Actually, both may be missing

```
$v = Validator::make(['foo' => 'bar'], ['foo' => 'different:baz|sometimes', 'baz' => 'different:foo|sometimes']);
$v->passes(); // false
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by driesvints** [comment]
Also please fill out the issue template next time.
