### ISSUE TITLE
Eloquent Cast date H:i:s Unexpected data found

### ISSUE THREAD

**Issue by meyer59** [laravel/framework#29064]
- Laravel Version: 5.8.26
- PHP Version: 7.3.3
- Database Driver & Version: MariaDB 10.1.38
- Are you using `PDO::ATTR_EMULATE_PREPARES => true`: n

### Description:
Hi,
It is possible to cast a `time` column with the eloquent `$cast` array? 
  ```
protected $casts = [
        'on'               => 'date:H:i:s',
        'off'              => 'date:H:i:s',
        //'operating_day_id' => 'int',
    ];
```
When trying to access the `on` attribute i have the following exception:
` "message": "Unexpected data found.\nUnexpected data found.\nData missing", "exception": "InvalidArgumentException", "file": "/home/html/dev-vuejs/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php", "line": 563,`
### Steps To Reproduce:
Create a `time` field in you db
Cast the column in the eloquent model  to `date:H:i:s`
Try to access it `$model->timeColumn`
Thank you

**Comment by staudenmeir** [comment]
From the [documentation](https://laravel.com/docs/eloquent-mutators#attribute-casting):

> When using the date or datetime cast type, you may specify the date's format. This format will be used when the model is serialized to an array or JSON:

What's your goal? Should `$model->on` return a `Carbon` instance?

**Comment by meyer59** [comment]
Yes i would like to have a ‘carbon’. I know i can have a ‘mutator’ but this less elegant. 
Since we can specify the date format why ‘H:i:s’ doesn’t work?
Also if you call ‘$model->created_at’ you will get a carbon instance event if you are not serialize it to ‘json’ or ‘array’

**Comment by staudenmeir** [comment]
You can specify a custom date format in your model, but it affects *all* date/time columns:

```php
protected $dateFormat = 'H:i:s';
```

If your model also has `created_at` and `updated_at` timestamps, you'll need to use accessors:

```php
public function getOnAttribute($value)
{
    return \Illuminate\Support\Facades\Date::createFromFormat('H:i:s', $value);
}

public function getOffAttribute($value)
{
    return \Illuminate\Support\Facades\Date::createFromFormat('H:i:s', $value);
}
```

**Comment by meyer59** [comment]
I know... but why we cannot use the custom cast format ‘date:H:i:s’ since it is a valid format for ‘Carbon::CreateFromFormat’
Is it a bug?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by meyer59** [comment]
It looks more like a bug about casting in H:i:s format

**Comment by staudenmeir** [comment]
This is not a bug. Custom cast formats are meant to describe the output, not the input.

**Comment by meyer59** [comment]
For you `dump($model->on)` is an input ? Because we are talking about that

**Comment by staudenmeir** [comment]
No, that's an output. But as the docs say, custom cast formats only affect `toArray()` and `toJson()`.

The input must have a format that `Carbon` can parse by default. You can specify a custom format with `$dateFormat`, but it affects all of a model's date/time columns.

Custom date formats per column could be a solution for your issue, but that's a feature request. https://github.com/laravel/ideas/issues is the right place to discuss that.

**Comment by meyer59** [comment]
Got it. Thank you for your help
