### ISSUE TITLE
Inconsistent response from Storage upload

### ISSUE THREAD

**Issue by lukecurtis93** [laravel/framework#29065]
- Laravel Version: 5.7.28
- PHP Version: 7.3.1
- Database Driver & Version: MYSQL 5.7y.25
- Are you using `PDO::ATTR_EMULATE_PREPARES => true`: n

### Description:
When uploading a file to S3 using the storage facade, using an instance of `UploadedFile` works fine and the path is returned as expected. However when attempting to use intervention image a simple boolean is returned.

### Steps To Reproduce:
Upload an image the usual way from a POST/PATCH request
```php
$image = $request->file('photo');
$path = \Storage::disk('s3')->put('users/'.\Auth::id().'/posts', $image, 'public');
dd($path); // /users/1/posts/39grjigrje.jpg
```

Upload an image with an `Intervention Image` instance after manipulating
```
$image = $request->file('photo');
$image = \Image::make($image);
$image->orientate();
$path = \Storage::disk('s3')->put('users/'.\Auth::id().'/posts', $image, 'public');
dd($path); // true
```

I have attempted to use `$image->stream()` & `$image->stream()->__toString()` but to no avail. Is there any reason or issue regarding why the responses would be different in each case?

I can also see the file doesn't upload to S3 either which should technically return an exception if that was the case?

Appreciate any advice, if I have misinterpreted this functionality my apologies.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
