### ISSUE TITLE
Query builder "between" operator in "where" array

### ISSUE THREAD

**Issue by raulp** [laravel/framework#29080]
- Laravel Version: 5.8.19
- PHP Version: 7.2.15
- Database Driver & Version: MariaDB 10.3.13

### Description:
As described in the [docs](https://laravel.com/docs/5.8/queries#where-clauses), you can pass an array of where conditions to the query builder. However, if passing a `between` operator, it will get converted to a `=` operator. This happens in `Database/Query/Builder.php`, method `where`, where the operator is checked with function `invalidOperator`.

A quick fix will be to add an `if` statement right before that and add a `return $this->whereBetween($column, $value, ...)`, but I'm sure that's a dirty fix. 
I am not sure what a proper fix would be here, which is why I'm reaching out.

### Steps To Reproduce:
Pass to any eloquent or query builder `where` clause an array that contains a `between` clause. Ex:
```
$where = [
    ['active', 1],
    ['created_at', 'between', ['2019-07-01', '2019-08-01']]
]
```

**Comment by staudenmeir** [comment]
I don't think this is supposed to work. The following doesn't work either:

```php
$query->where('created_at', 'between', ['2019-07-01', '2019-08-01'])
```

`where()` is only meant for `column operator value` clauses but not as an alias for methods like `whereBetween()`.

**Comment by driesvints** [comment]
Please see the answer above. Thanks.
