### ISSUE TITLE
Issue in whereJsonContains() laravel 5.8

### ISSUE THREAD

**Issue by pankajdelaine** [laravel/framework#29092]
I am using Laravel 5.8, and sending params as raw JSON in Rest API , whereJsonContains()
 not working, It does not give me any response but when I send it as form data it works
![correct](https://user-images.githubusercontent.com/36953851/60752707-b9cc9e00-9fe6-11e9-8c0d-526a74056856.png)
![wrong](https://user-images.githubusercontent.com/36953851/60752712-c4873300-9fe6-11e9-9d71-2d59739d08d1.png)

**Comment by staudenmeir** [comment]
How are you using `whereJsonContains()`?

**Comment by pankajdelaine** [comment]
By this method 
$data=DB::table('product_common_details')->whereJsonContains(['service_id',$r->service_id)->where('status',1)->where('publish',1)->get();
and by this also
$output=DB::table('product_common_details')->whereRaw('json_contains(service_id, \'["' . $r->service_id . '"]\')')->where('status',1)->where('publish',1)->get();

**Comment by staudenmeir** [comment]
The second query isn't valid PHP.

What's the result of `dd($r->service_id);`? What values does the `service_id` column contain?

**Comment by pankajdelaine** [comment]
it prints just int value like 2 or 3 whatever API sends in params either through Multipart/form-data or from JSON.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
