### ISSUE TITLE
Bug validate array 5.8.*

### ISSUE THREAD

**Issue by tonamson** [laravel/framework#29091]
- Laravel Version: 5.8.x
- PHP Version: 7.1
- Database Driver & Version:

### Steps To Reproduce:
JSON data:

> https://jsoneditoronline.org/?id=e4002e1243844af7b43f9fa39015cf40

Rule:
```
$rule = [
                        'kpi_distributes' => 'required|array',
                        'kpi_distributes.*.kpi_setting_id' => 'required|max:255',
                        'kpi_distributes.*.distrubute_id' => 'max:255',
                        'kpi_distributes.*.details' => 'required|array',
                        'kpi_distributes.*.details.*.department_id' => 'max:255',
                        'kpi_distributes.*.details.*.target' => 'required|numeric',
                        'kpi_distributes.*.details.*.weight' => 'numeric',
                    ];
```

Error message from rule:
```
 "errors": {
        "kpi_distributes.1.details.1.target": [
            "The kpi_distributes.1.details.1.target must be a number."
        ],
        "kpi_distributes.*.details.0.target": [
            "The kpi_distributes.*.details.0.target field is required."
        ],
        "kpi_distributes.*.details.1.target": [
            "The kpi_distributes.*.details.1.target field is required."
        ],
        "kpi_distributes.*.details.2.target": [
            "The kpi_distributes.*.details.2.target field is required."
        ],
        "kpi_distributes.*.details.3.target": [
            "The kpi_distributes.*.details.3.target field is required."
        ]
    },
```

Rule numeric can detect but required can not detect.

**Comment by staudenmeir** [comment]
What's the expected result?

**Comment by tonamson** [comment]
> What's the expected result?

i think it's success detect required and number but if i change number to string it's detect number but not detect required? why?

**Comment by staudenmeir** [comment]
Please provide a complete example of PHP code that returns these errors.

With your JSON data, I only get a single error:

> The kpi_distributes.1.details.1.target must be a number.

**Comment by tonamson** [comment]
> Please provide a complete example of PHP code that returns these errors.
> 
> With your JSON data, I only get a single error:
> 
> > The kpi_distributes.1.details.1.target must be a number.

Maybe my laravel something wrong, i will check in new source again. Tks
