### ISSUE TITLE
Strange behavior loading configuration files

### ISSUE THREAD

**Issue by gmslzr** [laravel/framework#29099]
- Laravel Version: 5.8.27
- PHP Version: 7.1 - 7.3 
- Database Driver & Version: N/A

### Description:
On a new laravel installation (using homestead ) created via composer (composer create-project ) I got this error:

```
Fatal error: Uncaught RuntimeException: A facade root has not been set. in /home/vagrant/_cereswiki/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 234
RuntimeException: A facade root has not been set. in /home/vagrant/_cereswiki/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 234
```

running composer update returns 

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating optimized autoload files
```

and php artisan -v

```
In LoadConfiguration.php line 68:                                           
Unable to load the "app" configuration file.  
```

Which is rather straight forward, I went to check that up and getConfigurationFiles is returning an empty array, obviously the config files are there, I ran a chmod 777 on the config folder to humor the situation and still nothing. 

I then proceeded with a basic scandir on getConfigurationFiles() and populated the $files array 'manually' and it worked.

I'm on MacOS and realize this hasn't been reported by tons of other people so I'm open to be dumb and missing something, also, first time trying to contribute here. Sorry if I'm wasting somebody's time.

### Steps To Reproduce:

1. create a new laravel project with composer create-project --prefer-dist laravel/laravel
2. set homestead up for said new project
3. I've had this problem with 7.1 and 7.3, using latest Homestead branch (git checkout release) which it might as well be their problem, so that's about it.

### Attached image of code modifications that seem to work
<img width="866" alt="2019-07-07_1641" src="https://user-images.githubusercontent.com/2286388/60774200-781b2080-a0d6-11e9-98e9-c544be5d62ba.png">

**Comment by staudenmeir** [comment]
Does `php artisan serve` work?

**Comment by gmslzr** [comment]
Oh wow, yeah, that worked... why does it work?

**Comment by gmslzr** [comment]
> Does `php artisan serve` work?

Oh wow, yeah, that worked... why does it work?

**Comment by staudenmeir** [comment]
> set homestead up for said new project

Can you provide the exact steps? Did you install Homestead globally or per project?

**Comment by gmslzr** [comment]
> > set homestead up for said new project
> 
> Can you provide the exact steps? Did you install Homestead globally or per project?

Globally, I keep all of my projects in one directory and create Homestead sites individually by updating the Homestead.yaml

If php artisan serve works means I'm just missing something out here clearly, perhaps I need to triple check on sync / directory permissions on the host.

**Comment by staudenmeir** [comment]
Does Homestead work with the other projects?

**Comment by gmslzr** [comment]
> Does Homestead work with the other projects?

Yes sir. It's only on the project I'm beggining to work on.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by staudenmeir** [comment]
Upgrade to VirtualBox 6: https://github.com/laravel/homestead/issues/1219
