### ISSUE TITLE
False positives when authenticating in the RouteMatched event listeners

### ISSUE THREAD

**Issue by imanghafoori1** [laravel/framework#29098]
- Laravel Version: 5.8 and below
- PHP Version: irrelevant
- Database Driver & Version: irrelevant

## Description :
Laravel internally fires a RouteMatched event, when a route is matched and BEFORE any middleware is executed.

So if we use `auth()->check()` in the listener of that event, it always gives us `null` (even if the user is logged in) because the middleware which is responsible for Starting the session is not run yet.
This is expected. but...

The bug is :
if we write feature tests and send a request to an end point `$this->get('/my-url')` the  `auth()->check()` within the event listener of `RouteMatched` works properly ! and returns true if the user is logged in!
So it gives false positives. in case we need to check authentication in that listener.

To be clear, let me say that again:
 in the below code sample :
- real web request from a browser: `auth()->check()` (does not work)
- a simulated request from a  feature test `$this->get('/my-url')` :  `auth()->check()` (will work)

```php
// in the AppServiceProvider.php
\Event::listen(\Illuminate\Routing\Events\RouteMatched::class, function () {
    dd(auth()->check());
});
```

that was hiding a bad bug in my package for a long time. 

In other words, your tests tell you that `auth()->check();` will work properly in the code above, and that is a lie ! it won't work....

let me note that, all the authentication stuff (like : `->id()`, `->user()`) are subject to the same thing, not just  `auth()->check();` 

The cause :
it's because if we try to login the user in your feature test before sending the request, by using `auth()->loginUsingId(1)`, then the `auth()->check();` will return true, even in the target app instance.

## Steps to Reproduce :

fresh laravel 
plus, basic setup of authentication. (users table, a sample user to login with)

```php
// in the AppServiceProvider.php
\Event::listen(\Illuminate\Routing\Events\RouteMatched::class, function () {
    dump(auth()->check());
});
```

```php
// tests/feature/ExampleTest.php
  public function testBasicTest()
  {
     $this->actingAs(User::first());
     $this->get('/');
   }
```

1- login as a user (how ever you want to) 
2- visit '/' from your browser. 
3- you should see `false` printed out by `dump` function.
4 - run the test
5- you will see that `true` is printed out. (that contradiction strep 3)

**Comment by imanghafoori1** [comment]
An appropriate fix would be to offer a new method which only sets a cookie on the request and persist the session to be checked later.

**Comment by driesvints** [comment]
Please fill out the issue template when posting issues.

**Comment by imanghafoori1** [comment]
@driesvints I think it should be more clear now.

**Comment by driesvints** [comment]
Hmm, yeah I can see that being a problem. But I'm wondering why you need to check for auth state in that listener?

**Comment by imanghafoori1** [comment]
In real-life this happened to me while working on this package : https://github.com/imanghafoori1/laravel-heyman

for example this needs it :
Heyman::whenYouRouteName('foo')->youShouldbeGuest()->otherwise()->redirect('/home');

**Comment by driesvints** [comment]
How did you solve the bug?

**Comment by imanghafoori1** [comment]
Now the routeMatched listener,only adds a middleware at the end of the middleware stacks, using the `prepend` method.
and that middleware can check for authentication and other stuff. since it is after the `SessionStart`.

RouteMatched Listener :
https://github.com/imanghafoori1/laravel-heyman/blob/master/src/WatchingStrategies/Routes/RouteEventListener.php

The middleware is:
https://github.com/imanghafoori1/laravel-heyman/blob/master/src/WatchingStrategies/Routes/MatchedRoute.php

**Comment by driesvints** [comment]
That seems a little bit overkill to me. I don't have time to deep-dive into this atm. Feel free to send in a PR.

**Comment by driesvints** [comment]
Since there has been only one report of this and nobody else experienced this since I'm closing this.
