### ISSUE TITLE
Set getAuthPassword() as accessor only works in default User model

### ISSUE THREAD

**Issue by bebetoalves** [laravel/framework#29106]
- Laravel Version: 5.8.27
- PHP Version: 7.2.17
- Database Driver & Version: mysql 5.7.24

### Description:
Laravel creates a lot of stuff out of the box, but in certain things it misses a lot. I'm talking about authentication, it's still something too complicated to create within the framework.

I still dream of a command in artisan where I can create an blank authentication, where I can customize with all the fields I want and not depend on predefined fields. But since we don't have that yet, let's settle for what we have now.

Well, it's been about two days since I've been trying a fully customizable authentication but it's been a real challenge. My problem is currently changing the default field "password" to something else, like "senha".

To do this, I followed what it says in the documentation ([Eloquent: Mutators](https://laravel.com/docs/5.8/eloquent-mutators#defining-an-accessor)). I made an accessor on my model where is the new user table, where I called it  "cliente".

So, my model is:

```php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Cliente extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'nome', 'login', 'senha',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'senha', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    //protected $casts = [
    //    'email_verified_at' => 'datetime',
    //];

    public function getAuthPassword()
    {
        return $this->senha;
    }

    protected $table = 'clientes';
    protected $guard = 'clientes';
}

```
The funny is that the accessor is only working on the standard User model, but in other models does not work.

### Steps To Reproduce:

1. Create a new laravel project.
2. Set up your database and etc.
3. Do ``php artisan make:auth`` to create auth scaffolding.
4. Create a new model with a differente name and migration too.
5. Set up your new migration and apply it.
6. Copy everything in "User" model and paste in your new model, changing the name of the class and the desired fields.
7. Create a guard and a provider for your new model.
8. Create a accessor in your new model with the field  "password" that you want:
```php
  public function getAuthPassword()
  {
      return $this->your_password_field_here;
  }
```
9. Create a controller where your users will be able to login.
10. Try to log them manually using Auth::guard('Your new gard here')->attempt ($credentials);
11. Even if your credentials is correct, it will return false since the query is probably wrong.

Query in Telescope:
![Query in Telescope](https://user-images.githubusercontent.com/13764984/60812468-f247b580-a167-11e9-8904-e2cbd47a6972.png)

12. If you change your all custom password fields by default  "password", will work.

Query in Telescope after step 12:
![Screenshot_1](https://user-images.githubusercontent.com/13764984/60812753-9af61500-a168-11e9-9b04-7fb8884aa285.png)

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by bebetoalves** [comment]
> Hey there,
> 
> Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.
> 
> * [Laracasts Forums](https://laracasts.com/discuss)
> * [Laravel.io Forums](https://laravel.io/forum)
> * [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
> * [Discord](https://discordapp.com/invite/KxwQuKb)
> * [Larachat](https://larachat.co)
> * [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
> 
> Thanks!

I've done it, no reply so far.

[Link on stackoverflow](https://stackoverflow.com/questions/56936243/set-getauthpassword-as-accessor-only-works-in-default-user-model?noredirect=1#comment100416951_56936243)

**Comment by Victor8Danny** [comment]
tengo el mismo problema. pueden ayudarme
