### ISSUE TITLE
A `hasOne()->latest()` relationship fetches all related models.

### ISSUE THREAD

**Issue by grund3g** [laravel/framework#29108]
- Laravel Version: 5.8.27
- PHP Version: 7.2.15
- Database Driver & Version: MySQL 5.7.24

### Description:
A `hasOne()->latest()` relationship fetches all related models.

### Steps To Reproduce:
Author Model
```
<?php
class Author extends Model
{
   public function latestArticle()
    {
        return $this->hasOne(Article::class)->latest();
    }
}
```

Calling `Autor::with('latestArticle')->get() `results in the following two SQL Queries (according to the barryvdh/laravel-debugbar):
`select * from `authors`;`

`select * from articles where articles.author_id in (xx, xx, xx, ...) order by updated_at desc;`

I would expect only the last of each relationship to be retrieved.

**Comment by staudenmeir** [comment]
This requires a complex query and is not supported by Laravel natively.

I've created a package for it: https://github.com/staudenmeir/eloquent-eager-limit

Use the `HasEagerLimit` trait in both the parent and the related model and apply `limit(1)` to your relationship:

```php
class Author extends Model
{
    use \Staudenmeir\EloquentEagerLimit\HasEagerLimit;

    public function latestArticle()
    {
        return $this->hasOne(Article::class)->latest()->limit(1);
    }
}

class Article extends Model
{
    use \Staudenmeir\EloquentEagerLimit\HasEagerLimit;
}
```

**Comment by grund3g** [comment]
Looks good! In my case I could simply do it with a sub-query join, but maybe a note in the Docs would be helpful, because this can lead to real performance problems if there are many related models and you could be thinking, when looking at the defined relationship, that it is just limited to the last one.

**Comment by driesvints** [comment]
Feel free to send in a pr to the docs. Thanks.
