### ISSUE TITLE
Carbon out of updated, now monolog

### ISSUE THREAD

**Issue by IgorDePaula** [laravel/framework#29119]
Carbon was out updated, we needed function (locale functions and properties) that only carbon updated has. Now is monolog, Monolog updated have a TelegramBot handler, but the installed with laravel not have.

Not does this with the devs that loves laravel.

**Comment by driesvints** [comment]
Carbon 1 is removed from the upcoming Laravel release. I'll send in a PR to master in a few days to update monolog for the next release to 2.0 is nobody beats me to it.

**Comment by IgorDePaula** [comment]
Thank you very much.

**Comment by damcclean** [comment]
> Carbon 1 is removed from the upcoming Laravel release. I'll send in a PR to master in a few days to update monolog for the next release to 2.0 is nobody beats me to it.

@driesvints, did you ever get round to updating monolog for Laravel? If not, I'd be happy to do it :)

**Comment by driesvints** [comment]
Not yet! Feel free to do so, otherwise I'll send in a pr real soon.

**Comment by damcclean** [comment]
Alright, I'm on it!

**Comment by driesvints** [comment]
It seems Monolog 2.0 isn't out yet. We'll have to wait with updating until it is.

**Comment by X-Coder264** [comment]
@driesvints https://github.com/Seldaek/monolog/releases/tag/2.0.0 :tada:

**Comment by driesvints** [comment]
Yep I saw! Thanks. I'll check in on that soon.

**Comment by Vendin** [comment]
@driesvints did not find where compatibility can break

https://github.com/laravel/framework/pull/29813

**Comment by driesvints** [comment]
Merged
