### ISSUE TITLE
Mysql SSL issue

### ISSUE THREAD

**Issue by toast777** [laravel/framework#29120]
- Laravel Version: 5.8.28
- PHP Version: 7.2.11
- Database Driver & Version:
- OpenSSL - OpenSSL 1.1.0i 14 Aug 2018 Client
- Database Server - Mysql 5.7.26-0ubuntu0.16.04.1 (Ubuntu)

### Description:
Cannot connect to mysql server from Laravel using SSL while standard PDO works

### Steps To Reproduce:
Error I get - SQLSTATE[HY000] [1045] Access denied for user 'user'@'ip' (using password: YES) 

Used the following database.config script under mysql
~~~~
'sslmode' => 'require',
            'options' => extension_loaded('pdo_mysql') ? array([
                PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => false,
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
                PDO::MYSQL_ATTR_SSL_KEY => env('MYSQL_ATTR_SSL_KEY'),
                PDO::MYSQL_ATTR_SSL_CERT => env('MYSQL_ATTR_SSL_CERT'),
            ]) : [],
~~~~
PDO Test script that works
 ~~~~
$servername = "ip";
$username = "user";
$password = "passord";
$options = array(
    PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => false,
    PDO::MYSQL_ATTR_SSL_KEY => '/location/server-key.pem',
    PDO::MYSQL_ATTR_SSL_CERT => '/location/server-cert.pem',
    PDO::MYSQL_ATTR_SSL_CA => '/location/ca.pem',
);

try {
    $conn = new PDO("mysql:host=$servername;port=3306;dbname=dbname", $username, $password, $options);
    // set the PDO error mode to exception
    $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    echo "Connected successfully";
    var_dump($conn->query("SHOW GLOBAL STATUS LIKE 'Ssl_version';")->fetchAll());
    var_dump($conn->query("select * from `table`;")->fetchAll());
    $conn = null;
}
~~~~

**Comment by staudenmeir** [comment]
Don't provide options as a nested array:

```php
'sslmode' => 'require',
'options' => extension_loaded('pdo_mysql') ? [
    PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => false,
    PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
    PDO::MYSQL_ATTR_SSL_KEY => env('MYSQL_ATTR_SSL_KEY'),
    PDO::MYSQL_ATTR_SSL_CERT => env('MYSQL_ATTR_SSL_CERT'),
] : [],
```

**Comment by toast777** [comment]
Thanks for quick response, can you provide a sample how to do multiple
options, every tutorial I have seen did it that way.

**Comment by staudenmeir** [comment]
What do you mean by "multiple options"? Doesn't my code show that?

What are some of these tutorials?

**Comment by toast777** [comment]
Sorry think I read it wrong in my email thread, now I understand. The base code when laravel is first installed uses this code snippet for mysql options - 
~~~~

            'options' => extension_loaded('pdo_mysql') ? array_filter([
                    PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
                ]) : [],
            ],
~~~~

I guess I just thought to add more options in there, I had to do array instead of array_filter because the first value was false.

**Comment by toast777** [comment]
I have my laravel install on my work computer, I will let you know tomorrow if it works

**Comment by toast777** [comment]
I got my vpn to work and your solution worked, thanks for the help. I got confused how it was passing those values to the framework by the example that was provided. Hopefully this will help someone else that gets confused by it.
