### ISSUE TITLE
'abort' function annotation and code mismatch

### ISSUE THREAD

**Issue by ghamp** [laravel/framework#29126]
`/**
     * Throw an HttpException with the given data.
     *
     * @param  \Symfony\Component\HttpFoundation\Response|int     $code
     * @param  string  $message
     * @param  array   $headers
     * @return void
     *
     * @throws \Symfony\Component\HttpKernel\Exception\HttpException
     * @throws \Symfony\Component\HttpKernel\Exception\NotFoundHttpException
     */
    function abort($code, $message = '', array $headers = [])
    {
        if ($code instanceof Response) {
            throw new HttpResponseException($code);
        } elseif ($code instanceof Responsable) {
            throw new HttpResponseException($code->toResponse(request()));
        }

        app()->abort($code, $message, $headers);
    }`

Annotations allow "Response" or an "int", 
but code allows "int", "Response" and "Responsable".

My IDE (phpstrom) is giving me errors for working code.

**Comment by staudenmeir** [comment]
This has been fixed a while ago: #25755
