### ISSUE TITLE
Problem with laravel mail sending

### ISSUE THREAD

**Issue by ChafikHadjAbdouRazack** [laravel/framework#29121]
- Laravel Version: 5.6.37
- PHP Version: 7.2.16
- Database Driver & Version:

### Description:
Hello, I have some problem wirh sending mail. I create mail class with console, create view for mail but when I try to send mail I get this error:
[2019-07-09 21:57:07] local.ERROR: Call to a member function render() on array {"userId":1,"xxx":"xxx","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function render() on array at /Users/xxxx/Documents/xxxx/xxx/vendor/laravel/framework/src/Illuminate/Mail/Markdown.php:61)

**Comment by LKnulp** [comment]
Hi,

How looks the ```build()```-method in your mail-class.
Because the error message points to a markdown-class I assume you try to use a markdown-view-tamplate.
Therfor you may call the ```markdown()```-method on the ```$this``` variable inside the ```build()```-method.

**Comment by ChafikHadjAbdouRazack** [comment]
@LKnulp Yes I used $this->markdown() but I get this error.

**Comment by ChafikHadjAbdouRazack** [comment]
```
  public function build()
    {
        $locale = $this->order->user->locale?:'en';
        $view = "emails.$locale.purchase_item";
        if(!view()->exists($view)) {
            $view = "emails.en.purchase_item";
        }
        return $this->markdown($view)
            ->subject(__("New order/request"))
            ->with([
                'name' => 'Boutique',//$this->order->listing->user->display_name,
                'title' => 'Achat',//$this->order->listing->title,
                'url' => route('account.orders.show', [$this->order]),
            ]);
    }
```
This is my mail class.

**Comment by LKnulp** [comment]
The failing line looks like that (this is 5.8 but I think it should fit):
```php
 $contents = $this->view->replaceNamespace(
   'mail', $this->htmlComponentPaths()
)->make($view, $data)->render();
```
Just a few hours ago I found a piece of code to register a directory under a special namespace via the ```app```-helper.
Unfortunately I can't find it anymore or reproduce the error which pointet me to it.

Mabe you can try to use dd withing the ```Markdown.php``` to tear appart the code and see where the array is created.
See ```Illuminate\Contracts\View\Factory.php``` for what type a particular function should return. Before running ```render()``` it should be return an implementation of ```\Illuminate\Contracts\View\View````.

**Comment by ChafikHadjAbdouRazack** [comment]
@LKnulp thanks. I'll try it.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by ChafikHadjAbdouRazack** [comment]
@driesvints OK.
