### ISSUE TITLE
Blade pass Collection as String instead of Array

### ISSUE THREAD

**Issue by iamyaoxi** [laravel/framework#29124]
- Laravel Version: 5.8.26
- PHP Version: 7.3.4
- Vue Version: 2.6.10
- Laravel Mix: 4.0.13

### Description:
Passing Collection to Vue through Blade, will be received as String instead of Array. In the past, it will be received as Array. Now it's received as String.

Some old Vue files will still receive as Array.

### Sample code:

**view.blade.php**
```
@section('content')
  <div id="todos_view">
    <vue-component-here
      :todos="{{ $todosCollection }}"
    />
  </div>

  <script src="{{ mix('/js/test.js') }}"></script>
@endsection
```

**TodoView.vue**
```
<template>
</template>

<script>
    export default {
        props: {
            todos: {
                type: Array, //This one should work. But instead, it will receive JSON-encoded String
                required: false
            }, ...
        }
    }
</script>
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
