### ISSUE TITLE
whereHas gives opposite result

### ISSUE THREAD

**Issue by psizer10** [laravel/framework#29131]
- Laravel Version: 7.2.19
- PHP Version: 5.8.21

When using whereHas(), the opposite result is returned.

So,

`$query->whereHas('userResponsible', function ($q) use ($value) {
                $q->where('name', 'LIKE', '%'.$value.'%');
 }, 'AND');`

Gives the result you would expect from having a NOT LIKE instead.

Feeling a bit stuck on this one

**Comment by staudenmeir** [comment]
Why are you providing `'AND'` as the third argument? `whereHas()`'s third parameter is the operator.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
