### ISSUE TITLE
Route::resource method show

### ISSUE THREAD

**Issue by cpekas** [laravel/framework#29135]
- Laravel Version: 5.8.28
- PHP Version: 7.3.6
- Database Driver & Version:
mysql  Ver 8.0.16 for Linux on x86_64 (MySQL Community Server - GPL)
### Description:
problem is on route/web.php
when i use Route::resource method 'show' is not worked, but when change code to below line is working!

`Route::get('/{id}', 'ClubController@show')->name('show');
Route::resource('/', 'ClubController');
`

### Steps To Reproduce:
`
Route::namespace('Clubs')->group(function (){
    Route::resource('/', 'ClubController');
    Route::post('users/checkAuth', 'ClubsUsersController@checkAuth')
        ->name('users.checkAuth');
    Route::get('users/logout', [ 'uses' => 'ClubsUsersController@logout', 'as' => 'users.logout' ]);
});
`

**Comment by devcircus** [comment]
You need a resource. 
Route::resource('something', 'SomethingController');

That's to purpose of "resource" controllers.

**Comment by devcircus** [comment]
If your use-case deviates from the norm, just define your routes explicitly.

**Comment by cpekas** [comment]
so if i want add simeting like "logout" route in "resource" should be declare all methods for "resource".
i can't use some methods beside all "resource" ?

**Comment by mrcat323** [comment]
Logout route is already in Auth routes after `artisan make:auth`

**Comment by mrcat323** [comment]
Or just define your route separately, **before** registering resource routes, *something like*:
```PHP
Route::get('foo/bar', 'FooController@bar');
Route::resource('foo', 'FooController');
```

**Comment by cpekas** [comment]
maybe i say bad about this problem.
in _"**resource**"_ we have this methods:`
index,
create,
store,
show,
edit,
update,
destroy
`
and when i use _"resource"_ and **append** some new method **before**  _"resource"_, method "**show**" in  _"**resource**"_ is not working!

**Comment by devcircus** [comment]
For this, you'll probably get more help on one of the community sites:
[Laravel Slack](https://larachat.co/)
[Laravel.io Forum](https://laravel.io/forum)
[Laracasts Forum](https://laracasts.com/discuss)
[StackOverflow](http://stackoverflow.com/questions/tagged/laravel)
