### ISSUE TITLE
Duplicate listener on each event when `shouldDiscoverEvents` is true

### ISSUE THREAD

**Issue by tdt412** [laravel/framework#29130]
- Laravel Version: 5.8.17
- PHP Version: 7.2.11

### Description:

There is a conflict between: 

(51)Illuminate\Foundation\Console\EventCacheCommand::getEvents()
`$providerEvents = array_merge($provider->discoverEvents(), $provider->listens());`

And:

(32)Illuminate\Foundation\Support\Providers\EventServiceProvider::boot()
`$events = array_merge_recursive(
    $this->discoveredEvents(),
    $this->listens()
);`

=> If use `array_merge_recursive` with `shouldDiscoverEvents` is true will duplicate Listener on each Event if not caching event.

**Comment by driesvints** [comment]
Please see https://github.com/laravel/framework/issues/28977
