### ISSUE TITLE
Impossibility Test with database and factory

### ISSUE THREAD

**Issue by IgorDePaula** [laravel/framework#29142]
- Laravel Version: v5.8.27
- PHP Version: 7.2
- Database Driver & Version: mysql 5.7 and sqlite

### Description:
All tests with database and mainly factories are locking, does not progress or advance. With mysql or sqlite does not progress or advance

### Steps To Reproduce:
Create a test
Create a factory
In test and call the factory, the test will lock the terminal.

**Comment by browner12** [comment]
Do you know this is a bug with the framework?  If not, I would recommend asking in StackOverflow or the Slack channel first, as this sounds like something more specific to your setup.

If you include more details, like your setup (Homestead, Valet, etc) and can provide any error logs, that will help people help you.

**Comment by IgorDePaula** [comment]
Was error me. I created a factory that call herself , creating a recursivity. Sorry, very sorry.
