### ISSUE TITLE
dd在terminal打印对象，没有输出

### ISSUE THREAD

**Issue by jewdore** [laravel/framework#29145]
- Laravel Version: 5.8.27
- PHP Version: 7.1
- Database Driver & Version:

### Description:
在phpstorm中执行artisan命令，命令dd 一个model，没有打印出来任何内容。
通过xdebug调试发现控制台出现类名后，显示内容又全部消失
但是直接在iTerm2 中执行却没有任何问题
### Steps To Reproduce:
vendor/symfony/var-dumper/Dumper/CliDumper.php:488
vendor/symfony/var-dumper/Dumper/CliDumper.php:494
注释掉以上两行，打印成功

**Comment by jewdore** [comment]
> * Laravel Version: 5.8.27
> * PHP Version: 7.1
> * Database Driver & Version:
> 
> ### Description:
> 在phpstorm中执行artisan命令，命令dd 一个model，没有打印出来任何内容。
> 通过xdebug调试发现控制台出现类名后，显示内容又全部消失
> 但是直接在iTerm2 中执行却没有任何问题
> 
> ### Steps To Reproduce:
> vendor/symfony/var-dumper/Dumper/CliDumper.php:488
> vendor/symfony/var-dumper/Dumper/CliDumper.php:494
> 注释掉以上两行，打印成功

初步认定是这两句打印的控制符在某些shell里面不支持（我的电脑是mac pro）

**Comment by driesvints** [comment]
I'm very sorry but we can only provide support in English. Maybe try https://learnku.com/laravel ?
