### ISSUE TITLE
Pluralisation/singularisation of multi-word models/tables

### ISSUE THREAD

**Issue by CJDennis** [laravel/framework#29140]
- Laravel Version: 5.7.14
- PHP Version: 7.3.3
- Database Driver & Version:

### Description:
By default, the last word in a multi-word name is pluralised/singularised. This changes `PartOfSpeech` to `part_of_speeches` instead of the correct `parts_of_speech`. Other names such as `KettleOfFish`, `BunchOfGrapes`, & `HeartOfGold` are affected in a similar way by not changing the first word.

### Steps To Reproduce:
Run `php artisan make:model PartOfSpeech -m` at the command line. A migration file called `database/migrations/****_**_**_******_create_part_of_speeches_table.php` will be created.

An issue at https://github.com/doctrine/inflector/issues/64 was closed as not being about single words.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by CJDennis** [comment]
Same issue in Laravel 5.5 which is still supported (for longer than Laravel 5.8).

**Comment by CJDennis** [comment]
@driesvints Same issue in Laravel 5.0, 5.1, 5.2, 5.3, 5.4, 5.6, 5.7, 5.8, & 5.9. Take your pick.

**Comment by devcircus** [comment]
IMO, it doesn't seem like a bug. Expecting the framework to handle proper pluralization of an infinite possibility of  compound words that border on phrases, is a little much. The framework helps with common words but the user should handle these uncommon words manually. I forget that the framework even provides the functionality because I always specify the names.

**Comment by driesvints** [comment]
The problem here is that we can't add the word to the uncountable list because speeches is a valid pluralization. I'm afraid that this is a little out of scope like @devcircus. There's no "smart" way for the framework to know if you meant "speach" or "speaches".

**Comment by CJDennis** [comment]
@driesvints Have you ever played Nethack? It could correctly pluralise phrases in the form "NOUN of NOUN" over twenty years ago! 

- Countable (grapes): One **bunch** of grapes. Two **bunches** of grapes.
- Uncountable (milk): One **litre** of milk. Two **litres** of milk.

I don't know of any counter examples where it would be *"two bunch of grapes" or *"two litre of milks". So whether "speech" is usually countable or uncountable is irrelevant.
