### ISSUE TITLE
Ask weakly

### ISSUE THREAD

**Issue by qifengzhang007** [laravel/framework#29158]
Hello, I would like to ask:
Why don't laravel frameworks add annotation grammar like spring? Do you think annotation grammar like spring framework is good?

**Comment by diego1araujo** [comment]
Annotation was a thing in early 5 version, as you can see [here](https://mattstauffer.com/blog/laravel-5.0-route-annotations/).

You can still use annotation through a package: https://github.com/LaravelCollective/annotations

**Comment by imanghafoori1** [comment]
It's better to discuss it at :

https://github.com/laravel/ideas/issues

I remember Taylor received a lot complain from community when he added that at laravel 5.0
