### ISSUE TITLE
[Feature request] queue:listen output to file

### ISSUE THREAD

**Issue by BasvanH** [laravel/framework#29157]
I'm running Laravel on a Windows box and registered the queue worker as a Windows Service. Windows hasn't got a Stdout mechanism for services, so I would like to request a feature to add an parameter to 'queue' to output it's progress to a logfile.

```php artisan queue:listen --log="<path>"```

**Comment by xuanquynh** [comment]
Please provide more information: Laravel version, PHP version?

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!

**Comment by BasvanH** [comment]
Done, thanks!

https://github.com/laravel/ideas/issues/1717
