### ISSUE TITLE
error for javascript commented variable

### ISSUE THREAD

**Issue by gurrrung** [laravel/framework#29168]
- Laravel Version: 5.8.28
- PHP Version: 7.1.22
- Database Driver & Version: -- 

### Description:
I'm not sure if this is intended but the commented code gives an error here.

### Steps To Reproduce:
Code:
  
    <!DOCTYPE html>
    <html>
      <head>
        <title></title>
        <script type="text/javascript">
          // {{$hello}}
        </script>
      </head>
      <body>
        Hello
      </body>
    </html>  
 
Error:
    ErrorException (E_ERROR)
      Undefined variable: hello (View: 
     /home/gurungrahul2/test/website/resources/views/welcome.blade.php)
![Screenshot Capture - 2019-07-15 - 18-58-42](https://user-images.githubusercontent.com/30543444/61219815-a5994700-a732-11e9-83eb-03927f91a29c.png)

**Comment by staudenmeir** [comment]
Blade comments work differently:

```php
{{-- $hello --}}
```
