### ISSUE TITLE
BUG? [5.8] Problem with 'Speficying Custom Values In Language Files'

### ISSUE THREAD

**Issue by JesusValera** [laravel/framework#29167]
Hello, I am working with a Laravel 5.8 version.

I need to modify the output of an error message form, so, when you select a field, another field is displayed and you must select something from the new field to be able to submit the form.
The thing is the validation is not working properly, I have tried everything.

The documentation says (https://laravel.com/docs/5.8/validation):

---
### Specifying Custom Values In Language Files

Sometimes you may need the `:value` portion of your validation message to be replaced with a custom representation of the value. For example, consider the following rule that specifies that a credit card number is required if the `payment_type` has a value of `cc`:

```php
$request->validate([
    'credit_card_number' => 'required_if:payment_type,cc'
]);
```
If this validation rule fails, it will produce the following error message:

> The credit card number field is required when payment type is `cc`.

Instead of displaying `cc` as the payment type value, you may specify a custom value representation in your `validation` language file by defining a `values` array:

```php
'values' => [
    'payment_type' => [
        'cc' => 'credit card'
    ],
],
```
Now if the validation rule fails it will produce the following message:

> The credit card number field is required when payment type is `credit card`.
---

I have a validation rule like:

```php
$request->validate([
    'foo' => [
        'required_if:bar.bizz,1',
        'numeric',
    ]
]);
```

And in my `validation.php`.

```
'required_if' => 'The :attribute field is required when :other is :value.',
```

```
'attributes' => [
 . . . // It is working properly for :attribute & :other.
],

// But :value is not working properly...
// I have tried with
'values' => [
    'foo.bar' => 'test',
    'foo.bar.1' => 'test',

    'foo.bar' => [
        '1' => 'test',
    ],
    'foo[bar]' => [ // I don't think this gonna works.
        '1' => 'test',
    ],
    'foo' => [
        'bar' => [
            '1' => 'test',
        ]
    ],
    'foo.*' => [
        '1' => 'test',
    ],
    'foo' => [
        '1' => 'test',
    ],
    'bar' => [
        '1' => 'test',
    ],
    '*.*' => [
        '1' => 'test',
    ],
    '*' => [
        '1' => 'test',
    ],
]
```

But I always get the same output:
> The `foo` field is required when `bar` is `1`.

Do you have any idea?
Thanks. :smiley:

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by JesusValera** [comment]
Problem solved!
Thanks for your response.
https://stackoverflow.com/questions/57036286/problem-with-speficying-custom-values-in-language-files
