### ISSUE TITLE
php artisan app:name 

### ISSUE THREAD

**Issue by ahKevinXy** [laravel/framework#29170]
- Laravel Version: 5.8
- PHP Version: 7.1.1
- Database Driver & Version:

### Description:

when I excute php artisan app:name www.xxx.com 

My app is change 

namespace wwww.xxxx.com\Http\Controllers\index;

I don't kown  how callback

we need to validate appname  validity

**Comment by browner12** [comment]
The issue tracker is for bugs with the Framework, not for general use questions.  Please move this question over to a site like StackOverflow.

The artisan command is working as intended. Please read a little more about its use. I would recommend not changing the app name, and leaving it as the default.

**Comment by stevebauman** [comment]
The command is working as intended, though maybe this should be "fixed" by pascal casing the name into a valid namespace before actually running the replace?

For the above example, `php artisan app:name www.xxx.com` would assign a pascal namespace of `WwwXxxCom`?

I think there should be some validation done on the namespace to ensure someone doesn't break their project if their unable to easily undo the changes.

**Comment by browner12** [comment]
honestly, we should just get rid of this command.

If you are suggesting a change, please move this over to https://github.com/laravel/ideas or open a PR.

**Comment by stevebauman** [comment]
> honestly, we should just get rid of this command.

I agree.

> If you are suggesting a change, please move this over to https://github.com/laravel/ideas or open a PR.

This is a bug since you can easily set an incompatible namespace which will then completely break your application and cannot be reversed by calling `app:name` again.

For example, running: `php artisan app:name "invalid_.(namespace)"` breaks the application and then you can no longer call `app:name` to reverse the change.

A simple regex should probably be used to validate the given namespace before renaming all project files.

**Comment by driesvints** [comment]
This command is removed from the next release.

**Comment by stevebauman** [comment]
> This command is removed from the next release.

Ah perfect, thanks :smile:

**Comment by ahKevinXy** [comment]
oh thinks ! this command remove or change
