### ISSUE TITLE
Forwarding Model::exists() function call to Eloquent Builder is ambiguous

### ISSUE THREAD

**Issue by redelschaap** [laravel/framework#29182]
- Laravel Version: 5.8.23
- PHP Version: 7.2.5

### Description:
Calling the method `Model::exists()` returns `true` when there is at least one record in it's table. The (magical) `exists()` method call can be confused with the `exists` property easily. Especially when used after a `firstOrNew()` method call.

### Steps To Reproduce:
Assuming we have a model `Thing` that extends `\Illuminate\Database\Eloquent\Model`:
1. Call `$thing = Thing::firstOrNew(['key' => 'value'], ['foo' => 'bar']);`
2. Check if the model exists with `$thing->exists()`
3. `$thing->exists()` always returns true when `Thing`'s table has at least one record, while as a developer I would expect to check whether the model already exists.

I know that this would be a breaking change, so perhaps `exists()` could be added as a public method to `\Illuminate\Database\Eloquent\Model`.

**Comment by staudenmeir** [comment]
Please see #28549 why this is the correct behavior.

**Comment by redelschaap** [comment]
I get it from a framework perspective, but from a developer's perspective it's not logical that `Thing::exists()` does not return `Thing::$exists`, but calls `\Illuminate\Database\Eloquent\Model::exists()`. instead. This is mainly because the property and the method have the same name.

**Comment by staudenmeir** [comment]
I can see how is behavior is surprising *if* you don't know about the `$exists` property. 

But if you do, I don't think you can expect a method and a property with the same name to return the same result. If they would, one of them would be superfluous.

**Comment by driesvints** [comment]
Please see the explanation by @staudenmeir.
