### ISSUE TITLE
incomplete Relation::morphMap() support

### ISSUE THREAD

**Issue by gandesc** [laravel/framework#29181]
- Laravel Version: 5.8.28
- PHP Version: 7.2.20
- Database Driver & Version:

### Description:

When using polymorphic relationships with custom polymorphic types,
when building queries with `hasMorph` (whereHasMorph), the custom polymorphic types are not
'translated' to classes in all cases and we get `Class 'myCustomPolyType' not found` errors.

As far as I can tell, the transformation from *types* to *classes* is made here

https://github.com/laravel/framework/blob/341fb54bea9693cada2a5b8d398621a57f82862d/src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php#L208 

only when `types === '*'` and I think it should be performed also when the types are specifically given.

### Steps To Reproduce:
- have models with polymorphic relationships
- build a query with a `whereHasMorph` condition, where you specify types, similar to
```php

Relation::morphMap([
    'posts' => 'App\Post',
    'videos' => 'App\Video',
]);

$comments = App\Comment::whereHasMorph(
    'commentable', 
    ['posts'], 
    function (Builder $query) {
        $query->where('title', 'like', 'foo%');
    }
)->get();
```

**Comment by driesvints** [comment]
Ping @staudenmeir

**Comment by staudenmeir** [comment]
We decided against supporting aliases in `$types`:
- If you ever change or remove the `morphMap`, these `whereHasMorph()` queries don't work anymore.
- The callback's second parameter `$type` always contains the class name. It would be confusing to provide an alias but get a class name.

**Comment by aocneanu** [comment]
The part I was missing is that the `$type` is later converted in the correct alias if an alias exists.

In my case I'm extending a package model and rewrite the alias in a local ASP, but I can always do `Relation::getMorphedModel($type)` and get the correct class from the alias.

Thank you!

**Comment by Reund0** [comment]
So Is there any solution for this issue? how use custom morph type in `WhereHasMorph()`?

**Comment by Reund0** [comment]
So Is there any solution for this issue? how use custom morph type in `WhereHasMorph()`?

**Comment by staudenmeir** [comment]
@Reund0 You pass the class instead of the alias:

```php
App\Comment::whereHasMorph(
    'commentable', 
    Relation::$morphMap['posts'],
    ...
);
```
