### ISSUE TITLE
Distinct validation rule not working on top-level array

### ISSUE THREAD

**Issue by archy-bold** [laravel/framework#29190]
- Laravel Version: 5.6.39
- PHP Version: 7.1.28
- Database Driver & Version: mariadb 10.4

### Description:

I'm not 100% sure that this is a bug or intended behaviour but I've been validating an array of values as follows:

```
$array = [
    ['id' => 1],
    ['id' => 2],
];
$rules = [
    '*' => 'array',
    '*.id' => 'required',
];
Validator::make($array, $rules)->validate();
```

Now if I use the `distinct` rule on the '*.id' column it doesn't work. However if I put it into a non-top-level property, it does eg

```
$array = [
    'items' => [
        ['id' => 1],
        ['id' => 2],
    ],
];
$rules = [
    'items' => 'array',
    'items.*.id' => 'required|distinct',
];
```

I guess the question is, are top-level array validation rules supposed to work like this?

### Steps To Reproduce:

Using the following code, the Validator instance will not fire a validation error.

```
$array = [
    ['id' => 1],
    ['id' => 1],
];
$rules = [
    '*' => 'array',
    '*.id' => 'required|distinct',
];
Validator::make($array, $rules)->validate();
```

**Comment by staudenmeir** [comment]
@driesvints This is still an issue in 5.8.29.

**Comment by vahiiiid** [comment]
I reproduced it in laravel 5.8 and without  ` '*' => 'array', `  it works fine!

$array = [
    ['id' => 1],
    ['id' => 1],
];
$rules = [
    '*.id' => 'required|distinct',
];
Validator::make($array, $rules)->validate();
