### ISSUE TITLE
模型更新绑定参数支持

### ISSUE THREAD

**Issue by zh761324952** [laravel/framework#29198]
需求：
`php
$query = Content::whereIn('id', (array)$id);

$keyword = var_export($keyword, true);
$toKeyword = var_export($toKeyword, true);

$query->update([
    'content' => DB::raw('replace(`content`, ' . $keyword . ', ' . $toKeyword . ')'),
]);
`
绑定参数支持
`
$query = Content::whereIn('id', (array)$id);

$bindings = [
    ':keyword' => $keyword,
    ':to_keyword' => $toKeyword,
];

$query->update([
    'content' => DB::raw('replace(`content`, :keyword, :to_keyword)', $bindings),
]);
`

**Comment by driesvints** [comment]
I’m very sorry but we can only provide support in English. Please try https://learnku.com/laravel
