### ISSUE TITLE
Using Event::fake() appears to cause a memory leak

### ISSUE THREAD

**Issue by nm777** [laravel/framework#29191]
- Laravel Version: 5.8.28
- PHP Version: 7.3.3
- Database Driver & Version: Only tested on sqlsrv (5.6.1) and sqlite (3.24.0). Probably others?

### Description:
When chunking results from a model, if `Event::fake()` has been used, memory usage increases with each iteration of the loop.

### Steps To Reproduce:
1. Create a new Laravel 5.8.28 project:
```
composer create-project laravel/laravel event-fake-memory-leak --prefer-dist
```
2. Edit `.env` to use sqlite (for convenience -- you can use any DB driver you like):
```
DB_CONNECTION=sqlite
# DB_HOST=127.0.0.1
# DB_PORT=3306
# DB_DATABASE=homestead
# DB_USERNAME=homestead
# DB_PASSWORD=secret
```
3. Create the sqlite database and migrate the tables:
```
cd event-fake-memory-leak
touch database/database.sqlite
php artisan migrate
```
4. Copy the following code to `app\Console\Commands\MemoryLeak.php`:
```
<?php

namespace App\Console\Commands;

use App\User;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Event;

class MemoryLeak extends Command
{
    protected $signature = 'memory-leak';

    public function handle()
    {
        if (User::count() === 0) {
            $this->info("Seeding users table");
            factory('App\User', 10000)->create();
        }

        $this->info("Looping over users without Event::fake()");
        User::chunkById(1000, function () {
            $this->reportMemory();
        });

        Event::fake();

        $this->info("\nSame loop with Event::fake() enabled");
        User::chunkById(1000, function () {
            $this->reportMemory();
        });
    }

    private function humanFilesize($bytes, $decimals = 2)
    {
        $size = array('B', 'kB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB');
        $factor = floor((strlen($bytes) - 1) / 3);
        return sprintf("%.{$decimals}f", $bytes / pow(1024, $factor)) . @$size[$factor];
    }

    private function reportMemory()
    {
        $this->info("Memory used: " . $this->humanFileSize(memory_get_usage()));
    }
}
```
5. Run the new console command and check the output:
```
$ > php artisan memory-leak
Looping over users without Event::fake()
Memory used: 14.15MB
Memory used: 14.16MB
Memory used: 14.16MB
Memory used: 14.15MB
Memory used: 14.16MB
Memory used: 14.16MB
Memory used: 14.16MB
Memory used: 14.16MB
Memory used: 14.16MB
Memory used: 14.16MB

Same loop with Event::fake() enabled
Memory used: 14.62MB
Memory used: 16.42MB
Memory used: 18.29MB
Memory used: 20.06MB
Memory used: 21.95MB
Memory used: 23.72MB
Memory used: 25.55MB
Memory used: 27.32MB
Memory used: 29.34MB
Memory used: 31.11MB
```

I'd be happy to try to help troubleshoot this further or even send a pull request, but I don't know where to start. If anyone wants to point me in a direction, I'd be happy to do some further digging.

**Comment by stevebauman** [comment]
Hmm I'm thinking this is because all events fired during the test are stored into the fake when calling `Event::fake()`:

https://github.com/laravel/framework/blob/24d3207c4693d64dca08b892c609dec2b2d2e21b/src/Illuminate/Support/Testing/Fakes/EventFake.php#L186-L225

The `shouldFakeEvent()` method returns true when the events to listen for is empty - so any event that is fired is stored in memory (via the `$events` property) for the duration of the test.

I believe these would be SQL events that are fired here per chunk:

https://github.com/laravel/framework/blob/24d3207c4693d64dca08b892c609dec2b2d2e21b/src/Illuminate/Database/Connection.php#L672-L687

I'll do some more digging.

**Comment by staudenmeir** [comment]
Yes, this is not a memory leak.

Eloquent fires a `retrieved` event for every single model and stores the retrieved instance in the event. With `Event::fake()`, these are all stored in `EventFake::$events` and cause the increasing memory usage.

**Comment by derekmd** [comment]
For non-faker `$this->withoutEvents()`, `withoutJobs()`, etc. having below in tests/TestCase.php will reduce memory use over the full suite run:

```php
    public function tearDown(): void
    {
        parent::tearDown();

        $this->firedEvents = [];
        $this->firedModelEvents = [];
        $this->dispatchedJobs = [];
        $this->dispatchedNotifications = [];
    }
```

A similar setup could be added to the `Illuminate\Support\Testing\Fakes\*` classes. e.g.,

```php
class EventFake implements Dispatcher
{
     // ...

    public function clear()
    {
        $this->dispatcher = null;
        $this->eventsToFake = null;
        $this->events = null;
    }
}
```

But the onus would be on devs to manually call it.

```php
    // Add to every class whose setUp() calls Event::fake().
    public function tearDown(): void
    {
        parent::tearDown();

        Event::getFacadeRoot()->clear();
    }
```

Unfortunately I found PHP's garbage collection delays triggering `__destruct()` for every `EventFake` instance until the very end of PHPUnit's script execution, so it's messy to manage memory for the full test suite.

**Comment by nm777** [comment]
Thanks, guys. This helps explain it and provides some strategies for coping. I really appreciate your help!
