### ISSUE TITLE
Inconsistent behavior of the \Eloquent\Builder::update method

### ISSUE THREAD

**Issue by hafezdivandari** [laravel/framework#29194]
- Laravel Version: 5.8.29
- PHP Version: 7.3.6
- Database Driver & Version: MySql 8.0

### Description:
The `\Illuminate\Database\Eloquent\Builder::update` method of Eloquent model doesn't protect against mass-assignment and causes Inconsistent behavior.

class | method | mass-assign safe
----- | --------- | ------------------------
`\Eloquent\Builder` | `create` | :heavy_check_mark:
`\Eloquent\Relations\BelongsToMany` | `create` | :heavy_check_mark:
`\Eloquent\Relations\HasOneOrMany` | `create` | :heavy_check_mark:
`\Eloquent\Builder` | `update` | :x:
`\Eloquent\Model` | `update` | :heavy_check_mark:
`\Eloquent\Relations\BelongsTo` | `update` | :heavy_check_mark:
`\Eloquent\Relations\BelongsToMany` | `createMany` | :heavy_check_mark:
`\Eloquent\Relations\HasOneOrMany` | `createMany` | :heavy_check_mark:
`\Eloquent\Builder` | `findOrNew` | :heavy_check_mark:
`\Eloquent\Relations\HasOneOrMany` | `findOrNew` | :heavy_check_mark:
`\Eloquent\Builder` | `firstOrNew` | :heavy_check_mark:
`\Eloquent\Relations\HasManyThrough` | `firstOrNew` | :heavy_check_mark:
`\Eloquent\Relations\HasOneOrMany` | `firstOrNew` | :heavy_check_mark:
`\Eloquent\Builder` | `firstOrCreate` | :heavy_check_mark:
`\Eloquent\Relations\HasOneOrMany` | `firstOrCreate` | :heavy_check_mark:
`\Eloquent\Builder` | `updateOrCreate` | :heavy_check_mark:
`\Eloquent\Relations\HasManyThrough` | `updateOrCreate` | :heavy_check_mark:
`\Eloquent\Relations\HasOneOrMany` | `updateOrCreate` | :heavy_check_mark:

### Steps To Reproduce:
Let's assume we have a `User` model that might be associated with one `Phone` (One to One relationship), `hasOne` and `belongsTo` relationships are defined and `$fillable` attributes are specified.

example | uses | mass-assign safe
--------- | ----- | ------------------------
`Phone::create()` | `\Eloquent\Builder::create` | :heavy_check_mark:
`Phone::update()` | `\Eloquent\Model::update` | :heavy_check_mark:
`$user->phone()->create()` | `\Eloquent\Builder::create` | :heavy_check_mark:
`$user->phone()->update()` | `\Eloquent\Builder::update` | :x:
`$phone->user()->update()` | `\Eloquent\Relations\BelongsTo::update` | :heavy_check_mark:
`$user->phone->update()` | `\Eloquent\Model::update` | :heavy_check_mark:
`$phone->user->update()` | `\Eloquent\Model::update` | :heavy_check_mark:
`Phone::where()->update()` | `\Eloquent\Builder::update` | :x:
`Phone::find()->update()` | `\Eloquent\Model::update` | :heavy_check_mark:

I expect `update` to behave the same as `create` method always when being called on a Eloquent model but it doesn't.
It has different behavior on different types of relationships (`hasOne` and `belongsTo`). Also there should be a difference between using Eloquent to mass update vs using DB directly but there isn't and Eloquent `update` method doesn't check `$fillable` attributes:
```
Phone::where()->update();               //uses: \Illuminate\Database\Eloquent\Builder::update
DB::table('phones')->where()->update(); //uses: \Illuminate\Database\Query\Builder::update
```

**Comment by staudenmeir** [comment]
That's the intended behavior. 

While methods like `Builder::create()` or `Model::update()` work with model instances, `Builder::update()` is meant for mass updates and executes the `UPDATE` query directly in the database. It's a wrapper around `DB::update()` and adds support for global scopes and timestamps.

**Comment by hafezdivandari** [comment]
@staudenmeir Look at the examples above and compare them 2 by 2, It doesn't seems an intended behavior. I'm using Laravel for many years but I have to think about `update` behavior on every call:

```
$user->phone()->update(); //not safe
$phone->user()->update(); //safe
```
```
$user->phone()->update(); //not safe
$user->phone->update();   //safe
```
```
$user->phone()->update(); //not safe
$user->phone()->create(); //safe
```

**Comment by staudenmeir** [comment]
I agree that the behavior of `BelongsTo::update()` is inconsistent with the other relationships. But I think that it shouldn't protect against mass-assignment either.

**Comment by hafez-bsup** [comment]
@staudenmeir we have `forceCreate` against `create` and `forceFill` against `fill` we should also have `forceUpdate` against `\Eloquent\Builder::update` too. There should be a way to allow/disallow mass-assignment on `update` like other methods to keep consistency.

**Comment by hafezdivandari** [comment]
@staudenmeir we have `forceCreate` against `create` and `forceFill` against `fill` we should also have `forceUpdate` against `\Eloquent\Builder::update` too. There should be a way to allow/disallow mass-assignment on `update` like other methods to keep consistency.

**Comment by staudenmeir** [comment]
>we have forceCreate against create

I know that's not obvious to the user, but the equivalent to `Builder::update()` is `insert()`, not `create()`. `insert()` is also a "raw" method without mass-assignment protection.

**Comment by hafezdivandari** [comment]
@staudenmeir I understand your point of view, but what I'm saying is that there should be a difference between `\Eloquent\Builder::update` and `\Query\Builder::update`. 
When I'm using `update` method on an Eloquent model, this should always be without mass-assignment protection or always with it. The problem is that it's sometimes is and sometimes isn't. Please take a look at the examples above again, It doesn't make sense at all!

**Comment by driesvints** [comment]
I think it's best to continue this discussion in the ideas repo. This is just the way it works atm and any change to it would be a severe breaking change. Please open up an issue on the ideas repo to discuss things further.

**Comment by hafezdivandari** [comment]
@driesvints done: laravel/ideas#1725
