### ISSUE TITLE
Laravel does not evenly distribute the queries on SQL Master & Read Replicas in Jobs

### ISSUE THREAD

**Issue by rennokki** [laravel/framework#29197]
There is an issue i opened on Horizon board but it seems like it's more related to Laravel rather than Horizon itself.

The issue is described well here: https://github.com/laravel/horizon/issues/629

The thing is that in jobs, the read/write hosts are not balanced nor randomized thus adding pressure on only one database while the other one stays intact without any kind of traffic.

**Comment by driesvints** [comment]
Please fill out the issue template.

**Comment by rennokki** [comment]
- Laravel Version: 5.8.x
- PHP Version: 7.2.x
- Database Driver & Version: Postgres 11.x

### Description:
I moved a workload on AWS and i use RDS for PgSQL and EB to deploy the app. Since RDS allows me to create read replicas, i have created one and i put them in the pool in my `config/database.php`. The app can read/write on master and can only read on read replicas.

```
'read' => [
        'host' => [
            'master_fqdn',
            'read_replica_fqdn',
        ],
    ],
    'write' => [
        'host' => [
            'master_fqdn',
         ],
    ],
```

I have ran some workload right now and i have to process more than 4,641 jobs. The thing is that the jobs literally just read data from the DB and create new records based on the data retrieved. Basically, i'm processing insights into a better count-readable format.

The problem is that RDS dashboard shows me that there is a lot of pressure on Master node and no pressure on the Read replica. The first one is the master and the second one is a replica.

![alt text](https://i.imgur.com/Ayatpto.png)

This occurs only when running the workload on jobs. During the full request cycle, it reads and write on according nodes evenly.

### Steps To Reproduce:
1. Deploy a master with a read replica for PgSQL
2. Configure the database to accept multiple hosts for write and read replicas.
3. Put a ton of workload on jobs
4. Watch the queries use only one of the servers (either master or read replica)

@staudenmeir came with the idea of using `DB::reconnect()` (https://github.com/laravel/horizon/issues/629#issuecomment-512399306) and it works, but the `Illuminate\Foundation\Testing\RefreshDatabase` trait won't work as it was expected. For example:

```php
// This test case uses Refresh Database
class InsightExportTest extends TestCase
{
    use RefreshDatabase;

    public function test_generate_excel_at_download()
    {
         Model::create(['id' => 0]);
        
         // Now there is a single record for Model in the DB and SomeJob will be dispatched.
         // When dispatching and using DB::reconnect() within the job as sync, DB::reconnect()
         // will trigger the RefreshDatabase trait into 
         dispatch(new SomeJob)->onConnection('sync');
    }
}

// The job. After this will be dispatched, within the test, the Model with id = 1 will be existent.
class SomeJob
{
    public function dispatch()
    {
        DB::reconnect();

        Model::create(['id' => 1]);
    }
}
```

**Comment by staudenmeir** [comment]
I don't see a good solution for this. You'll have to use the `DatabaseMigrations` trait instead and the reset the database manually.

**Comment by rennokki** [comment]
For anyone who might have encountered this, here's a short brief.

When two or more hosts are used within a job or a queued class, the first host used gets stuck as long as the queue worker lives. (https://github.com/laravel/horizon/issues/629#issuecomment-512399306)

To fix this, you should never use `DB::reconnect()` because it will bring you a lot of trouble regarding `max_connections`. I did it like this, I screwed up the whole production for a few hours - not good.

I have used the `DB::disconnect()` at the bottom of each job's execution. It does work, and I have also put it inside the `failed` method in case something nasty happens. Jobs are using all hosts like it should. YAY!

![alt text](https://i.imgur.com/6rXn5Fd.png)

For the test problem, I have used the `Illuminate\Foundation\TestingDatabaseMigrations` trait instead and within the `TestCase` i added my own `setUp()` method and used the `artisan` method to :

```php
class TestCase extends BaseTestCase
{
   protected function setUp(): void
    {
        parent::setUp();

        $this->artisan('migrate:fresh'); // nice
    }
}
```

That was a tricky problem. Thanks for the points. :D
