### ISSUE TITLE
Route conflict between resourceful routes and a prefix placeholder

### ISSUE THREAD

**Issue by Shizzen83** [laravel/framework#29202]
- Laravel Version: 5.8.0
- PHP Version: 7.1.3

### Description:
I'm trying to implement a package based on JSON:API spec. So, I came to use `apiResource` router method. It works wonderfully, except if I wish adding a placeholder prefix to the generated routes (by setting them into a route group). To illustrate, here are some routes:
https://nsa40.casimages.com/img/2019/07/17/190717052259896893.png

Trying a GET on `anything/customers` raises 
`Missing required parameters for [Route: json-api.customers.show] [URI: {tenant}/customers/{customer}].`

I thought about a conflict because of the URI starting with a placeholder, but it also fails with a non-placeholder prefix:
GET on `testing/anything/customers` raises
`Missing required parameters for [Route: json-api.customers.show] [URI: testing/{tenant}/customers/{customer}].`

**N.B:** I'm not trying to get a nested resource. In my use-case, the placeholder prefix handles multi-tenancy.

### Steps To Reproduce:
- Create a model Foo
- Generate its routes by:
```
Route::group(['prefix' => '{prefix}'], function ($router) {
    Route::apiResource('foos', 'FooController');
});
```
- GET `anything/foos` endpoint

**Comment by RFreij** [comment]
I'm not able to reproduce your error, with a relatively fresh laravel install:

web.php
```Php
Route::group(['prefix' => '{prefix}'], function () {
    Route::apiResource('foos', 'FooController');
});
```

FooController@index
```Php
    public function index($prefix)
    {
        dd($prefix);
    }
```

result:
![image](https://user-images.githubusercontent.com/15109384/61392643-909dee80-a8bf-11e9-84d9-f90de411bef8.png)

Looking at the error, it seems like your application is trying to get `json-api.customers.show` instead of `json-api.customers.index` which should be fetched on route `anything/customers`

What package are you trying to implement? Or could you give any more information to reproduce?

**Comment by Shizzen83** [comment]
Finally after 3 days on that, I found out the origin, the exception message misled me.

```php
/**
     * Get links to fetch the model or one of its relationships.
     *
     * @param  string|null  $relationshipName
     * @return array
     */
    public function getApiLinks(string $relationshipName = null)
    {
        $urlGenerator   = app()->make('url');
        $identifiers    = $this->getApiIdentifiers();

        if ($relationshipName) {
            return [
                'self'      => $urlGenerator->jsonApiRelationship($identifiers['type'], $identifiers['id'], $relationshipName, 'index'),
                'related'   => $urlGenerator->jsonApiRelationship($identifiers['type'], $identifiers['id'], $relationshipName, 'related')
            ];
        }

        return [
            'self' => $urlGenerator->route(
                'json-api.'.$identifiers['type'].'.show',
                [ Str::singular($identifiers['type']) => $identifiers['id'] ]
        ];
```

The issue came from the URL generation on the `return`, any additional URL placeholder wouldn't be included into the array and by the way led to this message.

With this fix, it works now:
```php
/**
     * Get links to fetch the model or one of its relationships.
     *
     * @param  string|null  $relationshipName
     * @return array
     */
    public function getApiLinks(string $relationshipName = null)
    {
        $urlGenerator   = app()->make('url');
        $identifiers    = $this->getApiIdentifiers();
        $otherParams    = $urlGenerator->getRequest()->route()->parameters();

        if ($relationshipName) {
            return [
                'self'      => $urlGenerator->jsonApiRelationship($identifiers['type'], $identifiers['id'], $relationshipName, 'index', $otherParams),
                'related'   => $urlGenerator->jsonApiRelationship($identifiers['type'], $identifiers['id'], $relationshipName, 'related', $otherParams)
            ];
        }

        return [
            'self' => $urlGenerator->route(
                'json-api.'.$identifiers['type'].'.show',
                array_merge(
                    $otherParams,
                    [ Str::singular($identifiers['type']) => $identifiers['id'] ]
                )
            )
        ];
    }
```

Sorry about my misunderstanding and thank you anyway about this amazing framework.
