### ISSUE TITLE
Can`t ignore update_at value when model updated

### ISSUE THREAD

**Issue by VTumanov** [laravel/framework#29216]
[Illuminate\Database\Eloquent\Model:723](https://github.com/laravel/framework/blob/1003c27b73f11472c1ebdb9238b839aefddfb048/src/Illuminate/Database/Eloquent/Model.php#L723) - we have method `performUpdate`, this method call `$this->updateTimestamps()` wich set new values for "updated_at" column.

I want to ignore updating "updated_at", when changed some unimportant columns. For this reason i can rewrite methods "updateTimestamps" or "setUpdatedAt" with my condition, i think soo, but no... 

Because in [line 745](https://github.com/laravel/framework/blob/1003c27b73f11472c1ebdb9238b839aefddfb048/src/Illuminate/Database/Eloquent/Model.php#L745) of `performUpdate` method we can see: `$this->setKeysForSaveQuery($query)->update($dirty);`

This is `update` method of [Illuminate\Database\Eloquent\Builder:818](https://github.com/laravel/framework/blob/1003c27b73f11472c1ebdb9238b839aefddfb048/src/Illuminate/Database/Eloquent/Builder.php#L820)
`    public function update(array $values)
    {
        return $this->toBase()->update($this->addUpdatedAtColumn($values));
    }`

This is second place where column added, will be more good if updated_at can be changed in one place?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
