### ISSUE TITLE
Missing nested relation on `$response->getContent()`

### ISSUE THREAD

**Issue by rickmacgillis** [laravel/framework#29210]
- Laravel Version: 5.8.28
- PHP Version: 7.3.7
- Database Driver & Version: MariaDB 10.3.11

### Description:
When pulling a nested relationship through Eloquent ORM, the relationship appears just fine. However, when running a unit test to assert its presence, the nested relationship no longer exists when using `$response->getContent()`. (It's present on `$response`, though.)

Here's the code I'm talking about.

```
$contractor = Passport::actingAs(factory(User::class)->create(), ['scope-here']);
$response = $this->actingAs($contractor)->json('GET', route('route-name'));
$response->assertStatus(200); // It's 200 in the test run.
dump($response); // Includes the nested relationship
dump($response->getContent()); // Has a JSON string WITHOUT the nested relationship.
dump($response->getOriginalContent()->contractors[0]->trackingProject); // This one works properly.
```

Before you ask, yes the parent (non-nested) relationship exists and it's not null when the test executes.

### Steps To Reproduce:
1. Create two tables and models for them. Make sure that there's a relationship between them. (In my case, I used a `BelongsTo` relationship on `User` and a `HasMany` relationship on `Project`.)
2. Make a route that returns the User's project with various contractors (Users) attached to it (first relation) who may be tracking time for a given project. (Nested relation)
3. Now write a unit test like the one above in order to try to get the nested relation.

Example code to pull the nested relationship:

```
return $user->projects()
		->with([
			'contractors',
			'contractors.trackingProject',
		])->first();
```
That's a very stripped down version of my own code. I pulled both the parent and nested relationship.

Please note that this issue only happens in a testing environment.

**Comment by staudenmeir** [comment]
Please post the result of:

```php
dump($response);
dump($response->getContent());
dump($response->getOriginalContent());
```

**Comment by rickmacgillis** [comment]
`dump($response);` will show the result as a `Illuminate\Foundation\Testing\TestResponse`.
`dump($response->getContent());` will yield the JSON string without the nested relationship.
`dump($response->getOriginalContent());` displays the top level model with all of its relationships.

**Comment by staudenmeir** [comment]
Please post actual results.

**Comment by rickmacgillis** [comment]
@staudenmeir - The results are extremely large, not to mention highly proprietary, so that's not possible.

**Comment by staudenmeir** [comment]
We can't help you without actual results or a reproducible example.

Create a minimal Laravel application that demonstrates this issue and upload it GitHub or posts the `dump()` results.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by rickmacgillis** [comment]
@driesvints I've already confirmed it's a bug. Did you try repeating the problem using the code I showed you? If you got different results, let me know.

**Comment by driesvints** [comment]
@rickmacgillis you said: 

> Please note that this issue only happens in a testing environment.

This makes me believe that it's something specific to your use case. Please try a support channel first and then report back.

**Comment by rickmacgillis** [comment]
@driesvints I appreciate your giving me a reason instead of just closing the ticket. Given that `$response->getOriginalContent()` works as a workaround, I'll just call this one case closed for now.

**Comment by j0eii** [comment]
I have experienced the same issue in this test case.

I believe this issue is occurred during the unit test only, the request/response object won't mock the getContent(); method in this case.

![image](https://user-images.githubusercontent.com/13985803/128627647-759d7bcf-5b91-47a7-b999-a93bc96626d0.png)

A temp fix to this issue is not to use the request/response->getContent() function.

```
namespace Laravel\Cashier\Http\Controllers;

class WebhookController extends Controller{

    public function handleWebhook(Request $request)
    {
//        dd($request->getContent()); // null
        dd($request->get('type')); // invoice.payment_succeed

        dd($request->get('type'));

        // Origin code
//        $payload = json_decode($request->getContent(), true);
//        $method = 'handle' . Str::studly(str_replace('.', '_', $payload['type']));

        // Temp fix
        $type = null;
        if ($request->get('type') !== null) $type = $request->get('type');
        else {
            $payload = json_decode($request->getContent(), true);
            $type = Str::studly(str_replace('.', '_', $payload['type']));
        }
        $method = 'handle' . $type;
...

}

```
