### ISSUE TITLE
Validation: date_format:c says incorrect format for 2019-03-20T15:23:20+05:30 or similar

### ISSUE THREAD

**Issue by JorgeSivil** [laravel/framework#29218]
The PHP date() man page says that the format 'c' is ISO8601. However, when passing a string like the man says "2004-02-12T15:19:21+00:00", the validation says that the format is incorrect.

I had to replace for 'Y-m-d\TH:i:sP'

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by JorgeSivil** [comment]
Hi @driesvints , it was not a question, it was a report, as the validation fails for standard input.

**Comment by driesvints** [comment]
@JorgeSivil I don't think this is related to Laravel. Please try one of the support channels first.
