### ISSUE TITLE
composer create-project --prefer-dist laravel/laravel smartCinemas Installing laravel/laravel (v5.8.17)   - Installing laravel/laravel (v5.8.17): Downloading (connecting...)^CTerminate batch job (Y/N)? y instead 5.8.29

### ISSUE THREAD

**Issue by elevatedchris** [laravel/framework#29211]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Database Driver & Version:

**Comment by xuanquynh** [comment]
Composer loads from cache by default. Just go into your project and run `composer update`, then you will get the latest version.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.

**Comment by elevatedchris** [comment]
> 
> 
> Composer loads from cache by default. Just go into your project and run `composer update`, then you will get the latest version.
I am trying to create a new laravel project using composer and i am not getting the latest version which 5.8.29
