### ISSUE TITLE
Guarding not working as expected

### ISSUE THREAD

**Issue by ragingdave** [laravel/framework#29215]
- Laravel Version: 5.8.29
- PHP Version: 7.2.18
- Database Driver & Version: N/A

### Description:
When using unguard/reguard, I would expect that functions on each model independently,
but it appears to be working on all models simultaneously. This can be somewhat mitigated in normal application flows, but the problem arose during queue processing which unguarded every model (the reguard wasn't called due to an unexpected exception) and subsequent jobs within the same worker instance were now all unguarded for any model referenced.
Granted this has to do with php and late static binding, the issue is still there and a very unexpected one.

### Steps To Reproduce:
Create 2 models extending a app level Model class (that in turn extends Illuminate\Database\Eloquent\Model). Or even just directly extend the Eloquent model.

Then in a single snippet of code:

    Model1::unguard(); 
    Model1::isUnguarded(); // Comes back true as expected.
    Model2::isUnguarded(); // Should be false but is true

I'm not totally sure how one goes about fixing this but perhaps something like a static array map of guarded/unguarded states so each class has it's own setting rather than late model binding making it an all or nothing proposition.

**Comment by driesvints** [comment]
This is the intended way how this works. The global state is set on the parent model class and not on the individual model. If you want this behavior to be different please open an issue on the ideas repo to see if others agree with your idea.
