### ISSUE TITLE
Content-Length field is missing in HEAD response header

### ISSUE THREAD

**Issue by yueyuzhao** [laravel/framework#29227]
- Laravel Version: 5.8.27
- PHP Version: 7.2.6
- Database Driver & Version: not related

### Description:

According to [Section 14.13 of the HTTP/1.1 Spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.4)

> The Content-Length entity-header field indicates the size of the entity-body, in decimal number of OCTETs, sent to the recipient or, in the case of the HEAD method, the size of the entity-body that would have been sent had the request been a GET.

And [Section 9.4 of the HTTP/1.1 Spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.4) 

> The HEAD method is identical to GET except that the server MUST NOT return a message-body in the response. The metainformation contained in the HTTP headers in response to a HEAD request SHOULD be identical to the information sent in response to a GET request.

When users made a GET request, the framework returns the right `Content-Length` filed in the response header, but when deal with HEAD request, the framework should also return  the `Content-Length`.

### Steps To Reproduce:

Route definition: 
```php
Route::get('test', function () {
    return 'hello';
});
```

```sh
$ curl -is -4 http://laravel.local/test
HTTP/1.1 200 OK
Date: Thu, 18 Jul 2019 23:19:22 GMT
Server: Apache/2.4.38 (Unix) PHP/7.2.16
X-Powered-By: PHP/7.2.16
Cache-Control: no-cache, private
Content-Length: 5
Content-Type: text/html; charset=UTF-8

hello%
```

This is what I got in HEAD request: 
```sh
$ curl -I -4 http://laravel.local/test 
HTTP/1.1 200 OK
Date: Thu, 18 Jul 2019 23:21:07 GMT
Server: Apache/2.4.38 (Unix) PHP/7.2.16
X-Powered-By: PHP/7.2.16
Cache-Control: no-cache, private
Content-Type: text/html; charset=UTF-8
```

**Comment by omdmhd** [comment]
@driesvints  @yueyuzhao 
It is the web server which is setting content-length cause Laravel does not set any content length automatically, and also symfony [Response](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/HttpFoundation/Response.php) class which Laravel extends doesn't too.
so @yueyuzhao, you should check apache for this.

**Comment by yueyuzhao** [comment]
Hi @omdmhd, thanks for your attention. 
In a `HEAD` request, the application won't return the content body, so web servers won't know the exact `Content-Length`, and could't set it for us.
And in the `Symfony\Component\HttpFoundation\Response` class  from line 293 to 300 :
```php
if ($request->isMethod('HEAD')) {
    // cf. RFC2616 14.13
    $length = $headers->get('Content-Length');
    $this->setContent(null);
    if ($length) {
        $headers->set('Content-Length', $length);
    }
}
```
we know that if `Content-Length` is already in the headers, Symfony would restore the `Content-Length` field after set the content to null.

**Comment by driesvints** [comment]
Closing this as the related PR was closed. Please take this up upstream with Symfony as Taylor suggested. Thanks.
