### ISSUE TITLE
JSON collection cannot receive additional data

### ISSUE THREAD

**Issue by nanophp** [laravel/framework#29228]
```
<?php

declare(strict_types=1);

namespace App\Http\Resources\Branch\Branch\Relationship;

use App\Http\Resources\Branch\BranchCommissionPoint\CountryBaseBranchCommissionPointResource;
use Illuminate\Http\Resources\Json\ResourceCollection;

class BranchCommissionPointsRelationshipResource extends ResourceCollection
{
    /**
     * Transform the resource collection into an array.
     *
     * @param \Illuminate\Http\Request $request
     * @return array
     */
    public function toArray($request): array
    {
        $branch = $this->additional['branch'];

        return [
            'data' => CountryBaseBranchCommissionPointResource::collection($this->collection)->additional([
                'threshold_percentage' => $branch->country->commissionThreshold
            ]),
            'links' => [
                'self' => route('branches.relationships.commission_points', ['commission_points' => $branch->id]),
                'related' => route('branches.commission_points', ['commission_points' => $branch->id]),
            ]
        ];
    }
}

```

I'm using additional method and passed some data to another resource but I'm getting an undefined index error like, "Undefined index: threshold_percentage"

```
<?php

declare(strict_types=1);

namespace App\Http\Resources\Branch\BranchCommissionPoint;

use Illuminate\Http\Resources\Json\JsonResource;

class CountryBaseBranchCommissionPointResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param \Illuminate\Http\Request $request
     * @return array
     */
    public function toArray($request): array
    {
        $thresholdPercentage = $this->additional['threshold_percentage'];

        return [
            'type' => 'branch_commission_points',
            'id' => $this->id,
            'attributes' => [
                'branch_id' => $this->branch_id,
                'user_id' => $this->user_id,
                'service' => $this->service,
                'point' => $this->point * $thresholdPercentage / 100,
                'created_at' => (string)$this->created_at,
                'updated_at' => (string)$this->updated_at,
            ],
            'links' => [
                'self' => route('branch_commission_points.show', ['branch_commission_points' => $this->id])
            ],
        ];
    }
}



```

**Comment by staudenmeir** [comment]
You can't access the additional data because you are passing it to the `CountryBaseBranchCommissionPointResource`'s collection resource, not to the resource itself.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by nanophp** [comment]
> You can't access the additional data because you are passing it to the `CountryBaseBranchCommissionPointResource`'s collection resource, not to the resource itself.

But I checked api documentations $additional variable existing for each other.
