### ISSUE TITLE
firstOrCreate does not return the id in the Model Instance

### ISSUE THREAD

**Issue by rakishii13** [laravel/framework#29221]
- Laravel Version: 5.8.17
- PHP Version: 7.2.18
- Database Driver & Version: MariaDb

### Description:
When I try to use the method firstOrCreate to create an user, the return for the tap after creating the model is not attaching the id (primary key) to the model like it was before. 

### Steps To Reproduce:

`$user = User::firstOrCreate(['email' => $email]);`
`dd($user);`

Just try to use the method firstOrCreate using the email as a unique identifier to find the user other creating it. The dd() does not contain the id field in it.

**Comment by staudenmeir** [comment]
This works for me. Please post your `User` model.

**Comment by ManojKiranA** [comment]
It's working fine for me too

**Comment by rakishii13** [comment]
Nevermind that, I was extending the wrong type of model, Sorry for the inconvenience.
