### ISSUE TITLE
dd can not print object string

### ISSUE THREAD

**Issue by jewdore** [laravel/framework#29220]
- Laravel Version: 5.8.27
- PHP Version: 7.1
- Database Driver & Version: mysql 5.7

### Description:
can not print object message using `dd` in command

### Steps To Reproduce:
vendor/symfony/var-dumper/Dumper/CliDumper.php:488
vendor/symfony/var-dumper/Dumper/CliDumper.php:494
comment this lines perform ok

**Comment by ManojKiranA** [comment]
It's not laravel issue dd is actually using VarDumper so you need to create issue in VarDumper repo

**Comment by driesvints** [comment]
Please create an issue on the symfony repo.
