### ISSUE TITLE
$casts Does not converts back to json on multiple mysql connections

### ISSUE THREAD

**Issue by irfankazi56** [laravel/framework#29239]
- Laravel Version: 5.8.29
- PHP Version: 7.2.19
- Database Driver & Version: mysql  Ver 14.14

### Description:
I have two different databases A and B and they both have some common models.
i sync data between those tables.I am using json in one of the field and using casts.

` protected $casts = [
        "details" => "array"
    ];
`

I use multiple connection to sync table data and i use eloquent query.

when i retrieve data it convert back to array but when i insert or update on a different connection it does not convert back to json.
hence the error "array to string conversion"

`
 User::on('mysql2')->withTrashed()->whereId($id)->update(['details'=>$difference]);
`

**Comment by staudenmeir** [comment]
This type of queries will be supported in Laravel 5.9: #29146

In the meantime, you need to convert the values to JSON:

```php
User::on('mysql2')->withTrashed()->whereId($id)
  ->update(['details' => json_encode($difference)]);
```

**Comment by irfankazi56** [comment]
When i do this it enters as string not as json.

**Comment by staudenmeir** [comment]
Please log the executed query with https://laravel.com/docs/5.8/database#listening-for-query-events or `DB::enableQueryLog()` and `DB::getQueryLog()`.

**Comment by irfankazi56** [comment]
> Please log the executed query with https://laravel.com/docs/5.8/database#listening-for-query-events or `DB::enableQueryLog()` and `DB::getQueryLog()`.

**Comment by staudenmeir** [comment]
Are you executing the query that you posted here or a different one?

**Comment by irfankazi56** [comment]
> Are you executing the query that you posted here or a different one?

The same query

**Comment by staudenmeir** [comment]
Something must be different. Casts don't affect this type of query, only updates on model instances:

```php
User::find($id)->update(['details' => $difference]); // with cast
User::find($id)->update(['details' => json_encde($difference)]); // without cast
```

**Comment by irfankazi56** [comment]
> ```
> difference
> ```

User::find($id)->update(['details' => $difference]); // with cast

Here in 2nd query the $difference is already json as i created that record with using cast.

User::find($id)->update(['details' => $difference]);

**Comment by staudenmeir** [comment]
What query doesn't work, what's the result of `dd($difference);` and what's the executed SQL?

**Comment by irfankazi56** [comment]
The main problem i am facing is when i try to create or update cast variable on a different mysql connection it does not convert to json format. 
instead it tries to insert an array which i am passing.
even though i use cast for that column.

**Comment by staudenmeir** [comment]
As I said, this will be changed in Laravel 5.9.

Until then, you need to differentiate between model updates and query updates:

```php
class User extends Model
{
    protected $casts = ['details' => 'array'];
}

// model update
User::find($id)->update(['details' => ['foo' => 'bar']]);

// query update
User::on('mysql2')->whereId($id)->update(['details' => json_encode(['foo' => 'bar'])]);
```

**Comment by driesvints** [comment]
This will be changed in 5.9 as @staudenmeir said.
