### ISSUE TITLE
The validators validate method should return null on empty request attribute

### ISSUE THREAD

**Issue by MarGul** [laravel/framework#29237]
Could not make a much better title unfortunately.

The issue that I run in to a lot is that I will have code like this in my controller:
```
$data = $request->validate([
    'existing_attribute' => 'required',
    'non_existing_attribute' => ''
]);
```

Meaning that some times the attribute `non_existing_attribute` will be present in the request but sometimes it won't. But because I will use the `$data` variable in further processing, in say for example a ServiceClass I need to do things like this:
```
$data['non_existing_attribute'] = $data['non_existing_attribute'] ?? null;
```

What I am proposing is that the validator will return all the keys that you entered into the validate method but the one's that are not present in the request will be set to `null`.

This could be fixed by removing the `if` statement on [Line 341 in Validator.php](https://github.com/laravel/framework/blob/1003c27b73f11472c1ebdb9238b839aefddfb048/src/Illuminate/Validation/Validator.php#L341) and replacing it with:
```
Arr::set($results, $key, $value !== $missingValue ? $value : null);
```

Haven't looked at any implications here so I opened this feature request first and if people think it sounds good and don't have any side-effects I'll open a pull-request.

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!
