### ISSUE TITLE
[Bug] Getting an error when using 'except' on routes.

### ISSUE THREAD

**Issue by natecorkish** [laravel/framework#29242]
- Laravel Version: 5.8
- PHP Version: 7.3
- Database Driver & Version: n/a

### Description:

When I use middleware with except I get an error:

> Illegal offset type in isset or empty

<img src="https://i.imgur.com/ORGlHcC.png">

Has this feature been deprecated? I can't seem to find any information on it.

### Steps To Reproduce:

Use the following code:

```
Route::middleware('auth', ['except' => ['main']])->group(function($router) {
    Route::get('/', function () {
        return view('welcome');
    })->name('main');
});
```

**Comment by staudenmeir** [comment]
Has this worked before?

**Comment by natecorkish** [comment]
> Has this worked before?

Yes. Although I'm not sure what version it stopped working on. It still works on 5.8 lumen the last version I remember it working for laravel was maybe 5.5?

**Comment by staudenmeir** [comment]
It didn't work for me on Laravel 5.5. I'll try it on Lumen.

**Comment by staudenmeir** [comment]
Are you using the same route code on Lumen?

**Comment by natecorkish** [comment]
> Are you using the same route code on Lumen?

Yep. Exactly like that.

**Comment by staudenmeir** [comment]
Laravel and Lumen don't use the exact same routing code. It looks like not all routes work on both systems.

**Comment by driesvints** [comment]
Laravel and Lumen indeed use different routers.
