### ISSUE TITLE
[laravel 4.2]Carbon 1 is deprecated, see how to migrate to Carbon 2.

### ISSUE THREAD

**Issue by camry** [laravel/framework#29257]
- Laravel Version: 4.2.22
- PHP Version: 7.0.33
- Database Driver & Version:

### Description:

`composer update`

Carbon 1 is deprecated, see how to migrate to Carbon 2.

How can I solve it?

**Comment by ahinkle** [comment]
Hey there,

Laravel 4 and Carbon 1 has been unsupported for quite some time. I would suggest upgrading to Laravel 5.* and that will allow you to upgrade to Carbon 2.

If you need help upgrading, please reach out on our community channels:

- [laracasts.com/discuss](https://laracasts.com/discuss)
- [laravel.io/forum](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/mPZNm7A)

**Comment by ahinkle** [comment]
Hey there,

Laravel 4 has been unsupported for quite some time. I would suggest upgrading to Laravel 5.* and that will allow you to upgrade to Carbon 2.

If you need help upgrading, please reach out on our community channels:

- [laracasts.com/discuss](https://laracasts.com/discuss)
- [laravel.io/forum](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/mPZNm7A)

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
