### ISSUE TITLE
BindingResolutionException when binding to an interface

### ISSUE THREAD

**Issue by nospoon** [laravel/framework#29269]
- Laravel Version: 5.8.29
- PHP Version: 7.3.5
- Database Driver & Version:

### Description:
After upgrading Laravel from 5.8.16 to 5.8.29 it is no longer possible to resolve an interface binding from the container as BindingResolutionException is thrown.

### Steps To Reproduce:
- Create service implementing an interface
- Bind the interface to implementation in the service provider
- Register a facade with `getFacadeAccessor` resolving to the interface name
- Attempt to call the service via the facade

**Comment by xuanquynh** [comment]
With your information, it's too hard to detect what exactly happened because it looks normally to me and the others perhaps. You should submit the code to reproduce this behavior.

**Comment by nospoon** [comment]
After some more testing this seems to occur when setting `$defer = true` on the service provider and running `artisan clear-compiled`

**Comment by Shigeki1120** [comment]
Can you paste all the related code?

**Comment by nospoon** [comment]
```
class TestServiceProvider extends ServiceProvider
{
    protected $defer = true;

    /**
     * Register services.
     *
     * @return void
     */
    public function register()
    {
        $this->app->singleton(TestInterface::class, TestService::class);
    }

    /**
     * Bootstrap services.
     *
     * @return void
     */
    public function boot()
    {
        //
    }
}
```

```
class TestService implements TestInterface
{
    public function run()
    {
        dd("Lorem ipsum");
    }

}
```

```
class TestFacade extends Facade
{
    protected static function getFacadeAccessor()
    {
        return TestInterface::class;
    }
}
```

**Comment by Shigeki1120** [comment]
it's working fine on my end 🤔

**Comment by nospoon** [comment]
Strange, because I can could replicate this on three separate projects, including fresh Laravel install.
@Shigeki1120 did you run `clear-compiled`?

The steps to reproduce for me were the following:

- `$defer` set to` true` on service provider
- `php artisan clear-compiled`
-  run the test command - error
- remove the `$defer` attribute from service provider
- `php artisan clear-compiled`
- run the test command - no error

**Comment by Shigeki1120** [comment]
sorry that was my mistake have you read this?
https://laravel.com/docs/5.8/providers#deferred-providers

**Comment by Shigeki1120** [comment]
after adding that interface don't forget to run `php artisan clear:compiled`

**Comment by nospoon** [comment]
Ah my bad, completely forgot about the `provides ` method!
