### ISSUE TITLE
How to return null with Illuminate\Http\Resources\Json\JsonResource?

### ISSUE THREAD

**Issue by KiddoLin** [laravel/framework#29278]
I want to return null if model has some invalid conditions, but it is always return [].For example,
`$productTemplate['gift'] = new GiftTemplate($gift);`
```
use Illuminate\Http\Resources\Json\JsonResource;

class GiftTemplate extends JsonResource
{
    public function toArray($request)
    {
        if ($this->expired_at < now() || $this->is_disabled || $request->user()->age > 20)  {
            // I want to return null here for $productTemplate['gift'],
            // but it is always return [] when resource is null in JsonResource@toArray. 
            // The [] is not friendly for frontend.
            return null; 
        }

        $this->setVisible([
            'id',
            'name',
        ]);

       $data = parent::toArray($request);
        return $data;
    }
}
```
so,how to reurn null with JsonResource? Thanks for your answer.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
