### ISSUE TITLE
The casting for appended attributes (accessors) doesn't work

### ISSUE THREAD

**Issue by vovchok** [laravel/framework#29271]
- Laravel Version: 5.8.29
- PHP Version: 7.2.18

### Description:
The casting for appended attributes (accessors) at a model doesn't work when trying to get an array or JSON representations.

### Steps To Reproduce:
1. Create a model with appended accessors and casting declaration.
```php
class EloquentModelAppendsWithCastingStub extends Model
{
    protected $casts = [
        'is_admin' => 'int',
    ];
    protected $appends = ['is_admin'];

    public function getIsAdminAttribute()
    {
        return true;
    }
}
```
2. Create an instance of a model and call `toArray` or `toJson` methods:
```shell
>>> $model = new \App\EloquentModelAppendsWithCastingStub();
=> App\EloquentModelAppendsWithCastingStub {#3009}
>>> $model->toArray();
=> [
     "is_admin" => true,
   ]
>>> $model->toJson();
=> "{"is_admin":true}"
>>> 
```
### Expected results:
```shell
>>> $model = new \App\EloquentModelAppendsWithCastingStub();
=> App\EloquentModelAppendsWithCastingStub {#3009}
>>> $model->toArray();
=> [
     "is_admin" => 1,
   ]
>>> $model->toJson();
=> "{"is_admin":1}"
>>> 
```

**Comment by staudenmeir** [comment]
This is the intended behavior, an accessor (`get[...]Attribute()`) always takes precedence:
- When a "normal" attribute has a cast and an accessor, only the accessor is used.
- Additional attributes like yours always have an accessor, so a cast is never used.

You'll need to return the desired value from the accessor. For JSON responses, consider [API resources](https://laravel.com/docs/eloquent-resources).

**Comment by driesvints** [comment]
See the above answer.
