### ISSUE TITLE
MailFake Testing: raw() method can not be asserted.

### ISSUE THREAD

**Issue by trip-somers** [laravel/framework#29280]
- Laravel Version: 5.8.27
- PHP Version: 7.2.19
- Database Driver & Version: PostgreSQL 11+

### Description:

I don't know if this is technically a bug, but it's at least something that's not completely implemented.

I am using `Mail::raw()` to send a message. My test for the method that calls it uses `Mail::fake()` to prevent actual message sending, but there are no assertions available for testing -- primarily because `MailFake::raw()` is an empty method.

My implementation is not using a Mailable because the email is coming from an Eloquent model used for logging incoming and outgoing mail messages.

(I'm open to workaround ideas that wouldn't strictly tie the message log table to the Mailable concept -- i.e. storing Mailable class name and serialized view data. `Mail::raw()` was the most appropriate choice for how the mail log was built.)

### Steps To Reproduce:

n/a

**Comment by ahinkle** [comment]
Hi there, 

Would you be able to provide some code examples including your tests?

Feel free to reach out on the community channels for assistance.

- [laracasts.com/discuss](https://laracasts.com/discuss)
- [laravel.io/forum](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/mPZNm7A)

**Comment by trip-somers** [comment]
My last paragraph was just a note for anyone that has done something similar and would like to offer help with the pattern, it should not be the focus of this issue. The focus should be on `raw()` being a testability hole in the MailFake class.

A code sample of that would literally just be anything that calls `Mail::raw()`. As stated above, the `MailFake::raw()` class is an empty method, and more generally, the `MailFake` class itself contains no assertions regarding calls to `raw()`. As such, I can not use `MailFake` to assert that `raw()` was called.

I suppose it might be possible to simply use the mock facade (`Mail::shouldReceive('raw')`?) instead of MailFake, but if it were that easy to do, then what's the purpose of the MailFake class?

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by trip-somers** [comment]
What do you mean? Are you saying that `Mail::raw()` not being assertable _isn't_ a bug?

**Comment by driesvints** [comment]
@trip-somers your question felt more like a support question to me than a bug report. Please try a support channel first and feel free to reply back if you can confirm that there's a bug. Thanks.

**Comment by trip-somers** [comment]
None of what I said is unconfirmed. I you want me to remove the last paragraph of it, to make it feel less like a support request, I can just edit it.

**Comment by trip-somers** [comment]
Additionally, `MailFake::html()` doesn't even exist.

**Comment by iwasherefirst2** [comment]
@trip-somers did you figure it out?

**Comment by trip-somers** [comment]
I wound up just using the Mockery tools built into Facade:

```
Mail::shouldReceive('html')->with($messageBody, \Mockery::type('callable'))->once();
```

This worked in the original post, and still works on 7.x.

Still not really sure what the point of MailFake is if it doesn't handle basic assertions like this.

**Comment by alecpl** [comment]
Still MailFake::raw() is an empty method in Laravel v9.
