### ISSUE TITLE
Eager Loading Specific Columns in @json blade directive

### ISSUE THREAD

**Issue by elielhaouzi** [laravel/framework#29281]
- Laravel Version: 5.8.16
- PHP Version: 7.3.5
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.7.26

### Description:
when redering an Eager loading specific column in a @json blade directive even without space between name of columns it thrown an exception 
`@json(App\Book::with('author:id,name')->get())`
`Column not found: 1054 Unknown column ' name' in 'field list'`

The bug is due to the compileJson function in `laravel/framework/src/Illuminate/View/Compilers/Concerns/CompilesJson.php` assume that the expression doesn't contain any comma since it explode according to comma to get the encodingOptions and the depth of json_encode.

**Comment by staudenmeir** [comment]
Please see #28622.

You'll need to execute the query in your controller and pass it to the view.

**Comment by elielhaouzi** [comment]
Thank you for your response.

I just send a PR that can fix the bug

https://github.com/laravel/framework/pull/29282
