### ISSUE TITLE
Cant install laravel on my composer

### ISSUE THREAD

**Issue by Usielgoncalvesweb** [laravel/framework#29291]
While i try to install laravel on my composer it gives me this error: 
[Composer\Exception\NoSslException]

 The openssl extension is required for SSL/TLS protection but is not available. If you can not enable the openssl ex
  tension, you can disable this error, at your own risk, by setting the 'disable-tls' option to true.

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

Rigth now i am lost.......

**Comment by xuanquynh** [comment]
Your computer is missing php-openssl extension.
