### ISSUE TITLE
Optional named parameters in routes produces wrong result

### ISSUE THREAD

**Issue by aimeos** [laravel/framework#29297]
- Laravel Version: 5.8 and before
See https://github.com/laravel/framework/issues/7881 and https://github.com/laravel/framework/pull/7892

@taylorotwell Is this going to be fixed in Laravel 6.0? The original patch was rejected because there's no backward compatible solution

**Comment by rimace** [comment]
I think I understand your description from issue #7881.
You have the route `/list/{f_catid?}/{f_name?}` and want to use the route `/list?f_sort=price`, right? The two things I don't understand: where does the parameter `f_sort` comes from and what prevents you to just call the route `/list?f_sort=price`? As all parameters of `/list` are optional, you can just redirect to it with a query string.
If I understand correctly, your interpretation of optional parameters is to put them all in the query string. Is that correct?

**Comment by aimeos** [comment]
Example route: `/list/{f_catid?}/{f_name?}`
Parameter: Only an additional parameter `f_sort=price`
Expected: `/list?f_sort=price`
Actual: `/list/price`

I've talked to @taylorotwell at Laracon.eu 2018 in Amsterdam about that problem. It can't be fixed in 5.x because it would break existing REST routing code (route `/product/id?` automatically gets populated with first parameter regardless of its name). Question is if it will get fixed in 6.0 where breaking changes can be made.

**Comment by rimace** [comment]
I see. And what exactly prevents you form linking to `/list?f_sort=price`? The parameter `f_sort` is in the query string so it has nothing to do with routing.
What function do you call that generates your actual result but should be the expected result? I guess if we fix that function call that will solve everything and be backward compatible^^

**Comment by aimeos** [comment]
We use `\Illuminate\Contracts\Routing\UrlGenerator -> route( $routename, $params )`
where `$params` contains `['f_sort' => 'price']`

**Comment by driesvints** [comment]
Hey @aimeos. Because the changes for this will break quite a few things for existing apps we don't consider this to be a bug but rather a behavioral change. Feel free to open up an issue in the ideas repo to discuss this change and maybe attempt a PR to the master branch again. Make sure you add enough tests and cover the scenarios discussed in the original pr as well: https://github.com/laravel/framework/pull/7892

Thanks!
