### ISSUE TITLE
Weird behavior of route helper with port

### ISSUE THREAD

**Issue by brnmonteiro** [laravel/framework#29296]
- Laravel Version: 5.8.27
- PHP Version: 7.1
- Database Driver & Version: MySQL

### Description and Steps To Reproduce:
I'm using browser sync (port 3000), and im getting weird behaviour with route helper in controller:
```php
public function index()
{
    $a = route('admin.users.index');
    dump($a);
    var_dump($a);
    dd($a);
}
```

1. With the `dump()` before: 
All the 3 functions show the **correct** url (with the port):
![Screen 2019-07-25 às 11 50 50](https://user-images.githubusercontent.com/6596579/61884352-77ee9380-aed2-11e9-96c9-c158fde950ba.jpg)

2. But, if I remove the `dump()` before:
The `var_dump()` and the `dd()` functions show a **wrong** url (without the port, and with the protocol):
![Screen 2019-07-25 às 11 55 12](https://user-images.githubusercontent.com/6596579/61884700-14b13100-aed3-11e9-9916-936d0e6319b3.jpg)

I don't know why is showing like that. Does anyone have a clue?
Thanks

**Comment by staudenmeir** [comment]
What does `return $a;` give you?

**Comment by brnmonteiro** [comment]
> What does `return $a;` give you?

The same weird behaviour.
With the `dump()`: **//comercebox.test:3000/clientes**
Without the `dump()`: **http://comercebox.test/clientes**

**Comment by staudenmeir** [comment]
Can you reproduce this on a fresh Laravel installation?

**Comment by brnmonteiro** [comment]
Yes. 

With `art serve`, show the same url (the correct one with the port).
But when you use a proxy (like a browser sync with valet), that behaviour show up..

Ok, maybe is because the proxy, but why is happen this? Just a `dump` function, change the value of the route.

**Comment by emadha** [comment]
- What's the serve command you used?

**Comment by driesvints** [comment]
Not really sure what is happening here. Can you please create a test repo with your setup that reproduces the problem? Browsersync doesn't comes automatically installed in Laravel.

**Comment by brnmonteiro** [comment]
I create a repo to reproduce the error.
https://github.com/brnmonteiro/laravel-route-behavior

At readme more info to reproduce.

**Comment by staudenmeir** [comment]
Browsersync modifies the response and replaces the URL.

If you log the variable, you always get `http://127.0.0.1:8000`: `Log::info($target);`

The URL is only replaced if the beginning of the response is (somewhat) valid HTML:
Check the difference between `echo 'The dump:<br>'`; and `echo '<br>The dump:';`.

**Comment by driesvints** [comment]
Please see the answer above, thanks.
