### ISSUE TITLE
Apply just one middleware into test cases

### ISSUE THREAD

**Issue by vishalinfyom** [laravel/framework#29307]
I have one API in which 3 middlewares are applying,

now I just want to apply only one middleware, and remains 2 should not apply, so is there any method for it ??

If yes then please suggest.

If not then I think it should be.

**Comment by staudenmeir** [comment]
You can disable middlewares for a test:

```php
$this->withoutMiddleware([\Illuminate\Routing\Middleware\ThrottleRequests::class]);

$this->get('api');
```

**Comment by vishalinfyom** [comment]
> You can disable middlewares for a test:
> 
> ```
> $this->withoutMiddleware([\Illuminate\Routing\Middleware\ThrottleRequests::class]);
> 
> $this->get('api');
> ```

@staudenmeir thanks for this, here is my code, i am already using this aaproach,


```
$this->withoutMiddleware(
 [
            \Illuminate\Auth\Middleware\Authenticate::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \App\Http\Middleware\UserAuth::class,
            \Zizaco\Entrust\Middleware\EntrustRole::class,
            \Zizaco\Entrust\Middleware\EntrustPermission::class,
        ];
);
```

My problem is, i have to do it every time, skip 5 middeware and apply just once,

so what i exactly want is, is there any method that will take given middleware and ignore others automatically. 

e.g in my test i want to apply just one middleware `SubstituteBinding`, and ignore all others.

e.g 

[`$this->applyMiddleware([SubstituteBinding])`](url)

**Comment by staudenmeir** [comment]
I don't think that's possible.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
