### ISSUE TITLE
UrlGenerator error during installation

### ISSUE THREAD

**Issue by Mindexperiment** [laravel/framework#29302]
- Laravel Version: 5.8.29
- PHP Version: 7.2.19
- Database Driver & Version: mysql

### Description:
While installing a fresh new version on my testing environment "composer install" ends with a UrlGenerator error message. Any attempt to call cli commads ends with a UrlGenerator error message.

![laravel](https://user-images.githubusercontent.com/42065357/61912298-02b6a900-af3a-11e9-8f01-f0cee165b44f.png)

### Steps To Reproduce:
My composer.json is

```
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.1.3",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.8.*",
        "laravel/tinker": "^1.0",
        "moontoast/math": "^1.0",
        "league/flysystem-aws-s3-v3": "~1.0",
        "league/flysystem-cached-adapter": "~1.0",
        "laravel/cashier": "^9.3.0"
    },
    "require-dev": {
        "beyondcode/laravel-dump-server": "^1.0",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^3.0",
        "phpunit/phpunit": "^7.5"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}


```
Run cli command "composer install"

**Comment by ash-jc-allen** [comment]
What's in your composer.json file? The package.json file relates to your JavaScript side of things. The composer.json file will have the info about your PHP dependencies? :)

**Comment by sisve** [comment]
It sounds like a service provider is trying to generate urls outside of a request context. Check your application logs for the full stacktrace to find out what is causing the problem

**Comment by Mindexperiment** [comment]
@ash-jc-allen I'm sorry I post the wrong file (I was going to sleep) I updated the post.

I try with another small project and again, after updating to laravel 5.8.29, composer ends with the same UrlGenerator error

**Comment by Mindexperiment** [comment]
@sisve I found that i have a call to and asset() with a relative path inside a config file.

**Comment by ash-jc-allen** [comment]
I've just had a quick test on my local machine and this seems to work:
- Remove the secure_asset() function from your config, but leave the path there.
- In your AppServiceProvider you can then call secure_asset(config('meta.logo')). You can then assign it a variable or whatever it is you were going to do with it.

Sorry for bad formatting and no markdown, I'm on my phone so it's a bit difficult.

**Comment by Mindexperiment** [comment]
@ash-jc-allen thank you for your help, well I can call the asset() inside the metadata view.

```
	<meta name="twitter:image:src" content="{{ asset( ( !empty( $logo )? $logo : config( 'meta.logo' ) ) }}" />
```

I definetly need a vacation. This issue can be closed. Thank you

**Comment by JohnZambrano** [comment]
Yo también tenia ese error y resulta que era porque estaba utilizando un enlace para cargar una imagen de logo a mi panel de adminLTE, Ese enlace se encontraba en el archivo adminlte.php dentro de la carpeta config, una vez lo quite ya se soluciono el error.

**Comment by JohnZambrano** [comment]
![Image](https://github.com/user-attachments/assets/ecb2a0da-6869-4ac7-8083-fd8bf965253a)

**Comment by JohnZambrano** [comment]
Luego de comentar la linea donde llamaba el enlace para cargar mi imagen de logo, ya me permitía utilizar los comandos de php artisan normal

**Comment by JohnZambrano** [comment]
![Image](https://github.com/user-attachments/assets/e722b85b-9f99-4818-9190-fd9398482efb)
