### ISSUE TITLE
Date validation passing for grater year value than 9999

### ISSUE THREAD

**Issue by nasirkhan** [laravel/framework#29308]
- Laravel Version: v5.8.24
- PHP Version: 7.3.6
- Database Driver & Version: MySQL 8.0.16

### Description:
I am using Laravel 5.8 and trying to validate a `date` field. The name of the field is `date_of_birth` and the validation is like the following, 

```
$validatedData = $request->validate([
    'date_of_birth'     => 'date|before:today',
]);
```
I was using only `date` rule but when it failed to validate i was trying with `date|before:today`. 

Both of the date rules are failing to for any year grater than `9999`. The validation i passing as success and `MySQL` is showing the error as an invalid date. 

### Steps To Reproduce:
1. Add a date field and submit any date grater than `9999`
2. Set validation rule  as `date|before:today`
3. The validation will be passed and MySQL will show you an error

**Comment by bonzai** [comment]
#28138

**Comment by driesvints** [comment]
Please see the issue above.
