### ISSUE TITLE
URL Validator doesn't follow the structure of all schemes it allows

### ISSUE THREAD

**Issue by mastacheata** [laravel/framework#29301]
- Laravel Version: 5.8.29

#### Problem 1: The URL Validation is too generic and yet too limited
The `url` validation rule in Laravel allows a total of 217 different URI schemes, but applies the same generic pattern to all of them without making any differences.   

As an example have a look at some of the 8 examples given in the URI Generic Syntax RFC 3986 (especially those not following a hierarchical pattern and those not similar to HTTP): 

 To start with a simple one, the `mailto` URI is pretty common, but fails to be validated by the Laravel URL validator because it's lacking the  double forward-slash as required by the Laravel regex and can only pass if you add the double slashes due to mismatching the user part of the email as part of the basic authentication.  

 A more crazy but supposedly acceptable (for the Laravel URL validator) scheme that fails validation is the `urn` scheme. It consists of the letters urn followed by a colon and then one or more components made up of non-reserved characters, separated by colons.  
i.e.:  `urn:oasis:names:specification:docbook:dtd:xml:4.1.2`  
This will fail Laravel's URL validator because it lacks the characteristic double-forward-slash and because it has multiple colons, but is not enclosed in square brackets and thus not an IPv6 address.

#### Problem 2: It's not obvious why some schemes are included and others not
It seems like the allowed URI schemes were just randomly picked from the IANA website at one point and are only rarely if ever updated.

Examples: The historical videotex scheme is allowed, while the actually useful android scheme for identifying android apps by their App-ID is not.

#### Why I think this qualifies as a bug and not a feature request
You include so many different schemes that are of no use to anyone or are so archaic that only less than 100 people in the world have ever heard about them, yet you fail to implement validation rules that match the schemes of even the most common non-web schemes like `mailto` and `tel`

The current URL validation was apparently mostly copied from Symfony and only made this way to exclude certain schemes with the potential of creating malicious behavior like the `javascript` scheme.

#### Suggestions on how to fix this bug
As a fix I would suggest limiting the url validator to http(s) and maybe a few more common schemes that follow the same structure and were either suggested by people or are known to be commonly used.

Then add a second validation concern that actually validates a uri just by the most generic structure specified in RFC 3986:  
`scheme ":" hier-part [ "?" query ] [ "#" fragment ]` (ABNF high-level description of a URI)

There has been a previous failed attempt at introducing custom/private schemes with hierarchical patterns (i,.e.: two forward-slashes after the scheme identifier separator) as an optional argument to the ValidatesAttributes::validateUrl method in #16840. 

That PR was declined because Taylor himself wanted to see a more custom approach where one could verify certain schemes, but not others.
I personally think this is a too specific task to handle in a Framework, because there's no obvious demand for that and it can be easily crafted in Userspace by combining the proposed generic URI validation with a validation to check for a match/mismatch with the beginning of the string.

**Comment by driesvints** [comment]
Hey @mastacheata. Thank you for your very thorough description of the issue. I have to say that I follow @taylorotwell's suggestion about maybe a more thorough implementation of this to validate multiple uri schemes or limited them. I believe this isn't a bug atm with the url validation rule as the current validation rule is more intended to validate http:// and https:// urls. 

I think this discussion is more suited for the ideas repo. Feel free to copy/paste your issue there if you like. Also feel free to send in a PR with a suggested implementation for this if you want.

Thanks!

**Comment by mastacheata** [comment]
I get that part of this might be better suited as a new idea/feature since the URL validation clearly focuses on validating http/https urls.

The part of this issue that definitely is a bug is listing hundreds of schemes to begin with, but then failing to validate 70-80 of them.
I think the bug part of this issue is to narrow down the list to those URL schemes that are actually used and useable with the current validator and I could create / suggest a more generic URI validation next to that.

**Comment by scottcate** [comment]
It was easy to write our own new rule, but do others have a more elegant way to handle "mailto:" and "SMS:" links? The current IsUrl still accepts SMS:// and mailto:// as protocols, but of course, this is failing markup.

Thanks for any additional ideas on how to solve this?

I agree with @mastacheata's labeling this a bug, as it currently accepts the protocol with an invalid markup compared to what the real world is trying to do with it.
