### ISSUE TITLE
Mailable Notifications

### ISSUE THREAD

**Issue by asivaneswaran** [laravel/framework#29316]
- Laravel Version: 5.8.29
- PHP Version: 7.3.0
- Database Driver & Version: Mysql

### Description:
Hey guys,

I am trying to use an Mailable object in the toMail method of Notifications. But, the `to` method is not resolved automatically. So the issue I am having at the moment is that when I am sending an Anonymous notification, it isn't resolved.

Here is what I mean:

```

if (isset($member->account->user)) {
$member->account->user->notify(
(new TrainingsToExpire($expiring_trainings))
->delay(Carbon::now()->addMinute(1))
);
} else {
Notification::route('mail', $member->email)
->notify(
(new TrainingsToExpire($expiring_trainings))->delay(Carbon::now()->addMinute(1)));
}

```

And this is what I have in my

```

/**
* Get the mail representation of the notification.
*
* @param mixed $notifiable
* @return Mailable
*/
public function toMail($notifiable)
{
return (new Mailable($this->trainings_to_expire))->to($notifiable->email);
}

```

This is the error, I get:

```

1 Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Undefined property: Illuminate\Notifications\AnonymousNotifiable::$email", "/home/vagrant/code/kin-ball-v4/app/Notifications/TrainingsToExpire.php", [Object(Illuminate\Notifications\AnonymousNotifiable)])

/home/vagrant/code/kin-ball-v4/app/Notifications/TrainingsToExpire.php:49

```

Thanks,

**Comment by ahinkle** [comment]
Hey there,

Your code is a bit hard to read. Try reaching out on our community channels for support:

- [laracasts.com/discuss](https://laracasts.com/discuss)
- [laravel.io/forum](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/mPZNm7A)

If your certain it's a bug with the framework itself, please reply back here.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
