### ISSUE TITLE
Default contextual information for logs

### ISSUE THREAD

**Issue by vfsoraki** [laravel/framework#29319]
Can we have a default contextual data attached to all logs?

Reading `LogManager`, it is not implemented yet, but it seems rather easy.

Use cases are easy to think of, like having ID of user in logs, or have something added to context in console commands that are scheduled to know which log lines are related.

We can implement it in two ways (or both). Having a `Log::defaultContext($context)` to set default context in current request/process, and having a `Log::withContext($context, $fun)` to provide a context while executing `$fun`. 

Opinions?

**Comment by ahinkle** [comment]
Sounds like a discussion that should be moved into [laravel/ideas](https://github.com/laravel/ideas/issues) as this repository issue area has to do with bugs and issues within the framework itself.

**Comment by vfsoraki** [comment]
Good point, I haven't seen that repository before. I will move it there. Thanks!

**Comment by vfsoraki** [comment]
Related issue there https://github.com/laravel/ideas/issues/1747
