### ISSUE TITLE
[API Resource] Document conflict between Resource Collection and additional meta data

### ISSUE THREAD

**Issue by tuanpht** [laravel/framework#29311]
In the section [Resource Collections](https://laravel.com/docs/master/eloquent-resources#resource-collections), we have a note:
> ```php
> use App\User;
> use App\Http\Resources\User as UserResource;
>
> Route::get('/user', function () {
>     return UserResource::collection(User::all());
> });
> ```
> 
> Note that this does not allow any addition of meta data that may need to be returned with the collection

But  we can add meta data by using `additional()` method as described in section **Adding Meta Data When Constructing Resources**:
```php
use App\User;
use App\Http\Resources\User as UserResource;

Route::get('/user', function () {
    return UserResource::collection(User::all())
        ->additional(['meta' => ['key' => 'value']]);
});
```

Do you think we need to update document about this case?

**Comment by staudenmeir** [comment]
You're right. The note was originally correct, the `additional()` method was only added later on.

**Comment by tuanpht** [comment]
I think we could only remove that note.

**Comment by staudenmeir** [comment]
Can you submit a PR to https://github.com/laravel/docs?

**Comment by driesvints** [comment]
Going to close this as the pr was rejected. Maybe try again but with more detailed explanation of the `additional` method?

**Comment by tuanpht** [comment]
I think it had been already documented https://github.com/laravel/docs/blob/5.8/eloquent-resources.md#adding-meta-data-when-constructing-resources

I just correct the wrong note.
