### ISSUE TITLE
Can't use whereHas if the table name is aliased

### ISSUE THREAD

**Issue by tontonsb** [laravel/framework#29324]
- Laravel Version: 5.8.29
- PHP Version: 7.3.7
- Database Driver & Version: MariaDB 10.2.24

### Description:

It seems we are not able to use `whereHas` if we use an alias for the table.

### Steps To Reproduce:

Define whatever relation, for example

```php
namespace App;

class Post extends \Illuminate\Database\Eloquent\Model
{
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}
```

Try using `whereHas` when aliasing the table.

```php
User::from('posts as p')
    ->whereHas('user', function($user) {
        $user->where('role', 'author');
    })->get();
```

Receive an error similar to:
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'posts.user_id' in 'where clause' (SQL: select * from `posts` as `p` where exists (select * from `users` where `posts`.`user_id` = `users`.`id`))
```

### Workaround

I found a workaround that's quite hacky and unreliable, but might be useful if no one finds a way to fix this in a nice way.

It turns out that the `where` is already set in the callback and we can edit it. Here is the content of `wheres` at the start of callback:

```php
wheres: array:1 [
  0 => array:5 [
    'type' => 'Column',
    'first' => 'posts.user_id',
    'operator' => '=',
    'second' => 'users.id',
    'boolean' => 'and',
  ]
]
```

You can either edit it to fix the wrong name:

```php
User::from('users as u')
    ->whereHas('posts', function($post) {
        $post->getQuery()->wheres[0]['first'] = 'p.user_id';
        $post->where('created_at', '>=', \Carbon\Carbon::now()->subYear());
    })->get();
```

Or just delete the where and recreate it correctly (this might be safer as the order of first and second is maybe different for different relations):

```php
User::from('users as u')
    ->whereHas('posts', function($post) {
        $post->getQuery()->wheres = [];
        $post->whereColumn('p.user_id', 'users.id');
        $post->where('created_at', '>=', \Carbon\Carbon::now()->subYear());
    })->get();
```

**Comment by staudenmeir** [comment]
I don't think we are going to support queries like this. We probably could find a solution, but it would require quite a few changes.

**Comment by staudenmeir** [comment]
Different workaround:

```php
$query = User::from('users as u');

$query->getModel()->setTable('u');

$users = $query->whereHas('posts', [...])->get();
```

The advantage here is that you don't need to adjust the table name for every `whereHas()` clause.

Be aware that the results will now have the alias as their table name. You need to change that if you want to update them.

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!

**Comment by G-Bruin** [comment]
goods

**Comment by G-Bruin** [comment]
good
