### ISSUE TITLE
Getting belongsTo related model through polymorphic relation

### ISSUE THREAD

**Issue by ddzobov** [laravel/framework#29320]
I have 4 models:

```
- Systems
     1. id
     2. name

- Servers implements ConnectionTargetContract
     1. id
     2. system_id
     3. hostname
- Ips implements ConnectionTargetContract
     1. id
     2. system_id
     3. address
- Connections
     1. id
     2. source (polymorphic: source_type, source_id - ConnectionTargetContract)
     3. target (polymorphic: target_type, target_id - ConnectionTargetContract)
```

I want to get source->system and target->system objects from connection object for filtering and eager loading.

Now i'm doing it by filling source_system_id and target_system_id while saving connection object, but i think that it is very bad way.

**Comment by tw99** [comment]
Correct me if I'm wrong, but aren't you able to use define these relationships using the inverse `morphTo` relation? Since both `Servers` & `Ips` abide by the `ConnectionTarget` contract, you can safely eager load the system model.

`Connection` model:

```
    /**
     * @return \Illuminate\Database\Eloquent\Relations\MorphTo
     */
    public function target()
    {
        return $this->morphTo('target', 'App\Models\Target');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\MorphTo
     */
    public function source()
    {
        return $this->morphTo('source', 'App\Models\Source');
    }
```

Usage:
```
Connection::with([
    'target.system',
    'source.system',
])->get()...
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
