### ISSUE TITLE
[5.8] Please document DB:affectingStatement() for queries where you want to know affected row count

### ISSUE THREAD

**Issue by HenkPoley** [laravel/framework#29322]
Edit: this ticket is now just about the last line.

- Laravel Version: 5.8.29
- PHP Version: 7.2.19
- Database Driver & Version: MariaDB 5.5.60 ; pdo ; illuminate/database 5.8.29

### Description:
SQL 'insert into' statements can insert a variable amount of tuples based on a SELECT subquery. Currently you only get an 'okay' / 'fail' that the query executed successfully. Which might mean that nothing was inserted perfectly fine, because the select statement's conditions didn't match anything. 

Sometimes you would like to know if there was actually any or a specific number of rows inserted.

Same with DB::statement();

**-->** Alternatively, document affectingStatement() at https://laravel.com/docs/5.8/database

**Comment by staudenmeir** [comment]
Please use https://github.com/laravel/ideas/issues for proposals.

**Comment by HenkPoley** [comment]
I understand that interface changes may be difficult, so I made patch for the documentation to add a section about the public function DB::affectingStatement()

Currently you see see bad advice floating around to check the inserted row id from PDO. Which is fine-ish. Unless.. you insert into multiple tables, and the returned row id just happens to be the same (e.g. insert one row each into two tables, both inserted row id will be "1"). Then you might expect your second insert to have failed, because you don't see a new ID pop out.

**Comment by HenkPoley** [comment]
Maybe also put in a link to [PDOStatement::rowCount](https://www.php.net/manual/en/pdostatement.rowcount.php) which does actual work in the background. Since there are some caveats for some queries and some databases. Though often the (non-)zero case does work, but even then not in every configuration.

**Comment by driesvints** [comment]
Please just sent in a pr if you want to fix something in the documentation. Thanks.

**Comment by HenkPoley** [comment]
Cool, how do I "upgrade" this to a pull request: https://github.com/HenkPoley/docs/commit/dd89452661e71373b0797ef6fad9f38250d455bc

Github interface is not clear to me.

**Comment by driesvints** [comment]
Hey @HenkPoley. Here's a guide on how to do that: https://help.github.com/en/articles/creating-a-pull-request
