### ISSUE TITLE
Model HasAttributes Accessor Only Fills $value in certain cases

### ISSUE THREAD

**Issue by Jason-Morcos** [laravel/framework#29331]
- Laravel Version: 5.8.29
- PHP Version: 7.2.19
- Database Driver & Version: MySQL 5.6.43

### Description:
When creating an accessor, there is a `$value` parameter that is passed the current value in the model's attributes array. However, this value is grabbed from the model's attribute array in the same form as the call is made. For instance, calling `$gateway->customer_id` grabs the value for `customer_id` from the attributes array and passes it to the accessor whereas calling `$gateway->customerId` grabs the value for `customerId` from the attributes array and passes that into the accessor. However, in both cases the same accessor is called. Hence, the `$value` parameter behaves inconsistently.

### Steps To Reproduce:
Create a model with an attribute snake_case. Create a simple accessor for that attribute that returns the `$value` parameter.
<img width="478" alt="image" src="https://user-images.githubusercontent.com/10710367/62080028-d8a50580-b21d-11e9-9e27-16952090c276.png">

Try calling the attribute with both camelCase and snake_case syntax. The mutator is called in both cases and it returns it's value, however in one case the value is set (snake_case, matches the value in the attribute array) and in the other case the value is null.
<img width="398" alt="image" src="https://user-images.githubusercontent.com/10710367/62079806-6a604300-b21d-11e9-90ee-3e2d9e3ab92d.png">
<img width="239" alt="image" src="https://user-images.githubusercontent.com/10710367/62080077-ec506c00-b21d-11e9-9daa-b63f3e960037.png">

**Comment by Jason-Morcos** [comment]
The call to the mutator is handled in the Model's `HasAttributes` trait and clearly matches snake_case and camelCase (`customer_id` and `customerId`) to the same accessor

<img width="672" alt="image" src="https://user-images.githubusercontent.com/10710367/62080452-aea01300-b21e-11e9-9bbd-e5e4f13c6bd7.png">

**Comment by staudenmeir** [comment]
Wouldn't this only be an issue if a model has both `customer_id` and `customerId` attributes?

How could we even define two separate accessors?

**Comment by Jason-Morcos** [comment]
The issue is that if you only have customer_id as the attribute you can call the accessor as customer_id or customerId but $value is only set for the case where you call it as customer_id. Does that make sense?

**Comment by Jason-Morcos** [comment]
I agree there would be no good way to define two accessors. Perhaps the accessor should fill value defined in either case however? I'm not sure of a good fix. I ran into the issue today as a coworker prefers to call his accessors camelCase and I snake_case and an accessor wasn't working for him as the accessor was using $value.

**Comment by staudenmeir** [comment]
> a coworker prefers to call his accessors camelCase

But aren't they using Laravel incorrectly? If an attribute is called `customer_id` and doesn't have an accessor, you have to access it with `$model->customer_id`. `$model->customerId` doesn't work. When you add an accessor for that attribute, you can't just switch to `$model->customerId` and expect it to work.

You can only choose between camel and snake case if you have an accessor for a "virtual" attribute that doesn't exist in `$attributes`.

**Comment by Jason-Morcos** [comment]
That right there indicates inconsistency between the way accessors behave. Shouldn't they behave the same way for virtual and database attributes? Ideally, shouldn't the user not have to determine if he/she is interacting with a virtual or a database attribute as long as they are using an accessor?

**Comment by staudenmeir** [comment]
Which behavior would you change?

> Ideally, shouldn't the user not have to determine if he/she is interacting with a virtual or a database attribute as long as they are using an accessor?

I don't think they have to determine that at the moment. When you access a database attribute, you use the exact column name. For virtual attributes, you use your application's naming convention (camel or snake case).

**Comment by Jason-Morcos** [comment]
But it _can_ work with a database attribute. The accessor _is_ called. The only issue is `$value` is not passed in properly. The accessor is still called.

I think I would either remove the `$value` parameter, make accessors only called for snake_case, or check for both the snake_case and camelCase versions of the attribute in the attributes array and set value to be either if existent. I'm not sure how to handle if both snake_case and camelCase attributes are defined.

In any case, the current behavior is misleading and gives the appearance of working when in fact it doesn't.

**Comment by mfn** [comment]
> I think I would…

All of these suggestions are breaking changes.

I suggest to fix this in the docs rather.

**Comment by Jason-Morcos** [comment]
I agree they all are breaking changes. It would definitely have to be a Laravel 6+ change. But it seems that it's better to put some guardrails around the functionality so that it either always "works" or at least behaves consistently. The person interacting with the model shouldn't have to handle things differently for virtual and database attributes. Isn't that the point of HasAttributes and models anyways? To separate that responsibility so that the person interacting with the model can interact with it directly without having to fully understand the database setup that supports it?

**Comment by devcircus** [comment]
Agree that maybe this could be clarified in the docs. The current behavior is what I would expect but can see how it could possibly be confusing for some.

**Comment by driesvints** [comment]
The behavior you described above is the intended behavior. There's not real way to differentiate between `customer_id` and `customerId` when applying mutators. They were primarily designed for the former. Feel free to send in a PR to the docs if you feel that this needs to be clarified some more!
