### ISSUE TITLE
php artisan migrate doesn't read .env file for database infomation

### ISSUE THREAD

**Issue by supanida** [laravel/framework#29332]
- Laravel Version: 5.8.17
- PHP Version: 7.2.10
- Database Driver & Version:

### Description:
- When I do php artisan migrate, it does't read database information from my .env file. It give error.

 Illuminate\Database\QueryException  : SQLSTATE[HY000] [1045] Access denied for user 'homestead'@'localhost' (using password: YES) (SQL: select * from information_schema.tables where table_schema = homestead and table_name = migrations and table_type = 'BASE TABLE')

  at /Users/supanida/http/utrack/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668|

  Exception trace:

  1   PDOException::("SQLSTATE[HY000] [1045] Access denied for user 'homestead'@'localhost' (using password: YES)")
      /Users/supanida/http/utrack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70

  2   PDO::__construct("mysql:host=127.0.0.1;port=3306;dbname=homestead", "homestead", "secret", [])
      /Users/supanida/http/utrack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70

  Please use the argument -v to see more details.

- But when I do try it connect database via eloquent, it can connect normally

### Steps To Reproduce:
1. composer create-project ......
2. create database
3. setup .env file
4. run php artisan migrate

**Comment by nmokkenstorm** [comment]
The credentials showing up in your stack trace are the Laravel defaults. Can you verify if you actually have a database called homestead on localhost? Easiest way to check this is using a query browser like Sequel Pro, or directly in a terminal prompt with `mysql -u homestead -D homestead -psecret`

**Comment by emadha** [comment]
- Check if you're using the correct port ( i had the same issue cuz i used mariadb which connects at 3307)
- Check if you're using the correct artisan file and not calling an other project's artisan (silly, but oh well)

- Check if you have your config cached (php artisan config:clear to clear that, because)
- Get the .env file path and check if it's correct 
```PHP
// Put something like this in AppServiceProvider boot() method
// Then run your php artisan command, this should break the artisan output
// And display the .env variable instead
// If this command didn't break the artisan then this artisan doesnt belong to this project (the same silly thing)
// And if it did break, then you will have a clear filepath of the .env file

public function boot()  // <-- AppServiceProvider's Boot method.
    {   
         // 
         dd(app()->environmentFilePath()); // <--- this command
```

Let me know how it goes.

**Comment by yordadev** [comment]
The above 2 responses are correct, try those; however... Reviewing this error there is another possible solution for you.

`Access denied for user 'homestead'@'localhost'`

I'd be willing to bet you are trying to use an external database without remote connections enables. Please see this:

https://www.digitalocean.com/community/tutorials/how-to-allow-remote-access-to-mysql

**Comment by gofish543** [comment]
@yordadev 
'localhost' will resolve to 127.0.0.1 which is a local connection not a remote connection.

**Comment by supanida** [comment]
Thank you for all of your replies. It works normally when I connect to database using eloquent models, but it just didn't work on the command line "php artisan migrate" 

I did check the port as @emadha suggested. My environment uses mysql on localhost (So @yordadev , nope I didn't use external database) which uses port 3306 as is set in the .env file

Well, I have tried everything you guys suggested, but it still didn't work. So the last choice I have was to reboot the machine. After I reboot the machine, everything works as normal without any changes.

Thank you again for all your helps.

**Comment by milosb793** [comment]
This combo worked for me: 

```
php artisan clear-compiled 
composer dump-autoload
php artisan optimize
```

**Comment by Oddward** [comment]
Sorry I'm not entirely sure if my issue fits here or requires opening a new one, but I was struggling to successfully run `php artisan migrate` for a few days and had tried all kinds of solutions, but in the end the thing that worked was this:

> in `.env` file, change `DB_HOST=127.0.0.1` to `DB_HOST=localhost`

which is strange coz they're the same and going to 127.0.0.1:8000 on the browser loads the app. Could there be some problem with how laravel resolves the `$dsn` in `Connector.php`? My error message contained the correct credentials but still didn't work when DB_HOST was assigned 127.0.0.1 instead of localhost:

```
PDO::__construct("mysql:host=127.0.0.1;port=3306;dbname=laravelnl", "mug", "secret", [])
```

- Windows 10
- Using Laragon, app served with `php artisan serve`
- - Laravel Framework 8.27.0
- - PHP 8.0.1
- - MySQL 5.7.24

Mind you, when I found this solution I had not restarted since running `composer update`, but I had done `php artisan cache:clear` and `php artisan config:clear` and was still getting errors

**Comment by milosb793** [comment]
> Sorry I'm not entirely sure if my issue fits here or requires opening a new one, but I was struggling to successfully run `php artisan migrate` for a few days and had tried all kinds of solutions, but in the end the thing that worked was this:
> 
> > in `.env` file, change `DB_HOST=127.0.0.1` to `DB_HOST=localhost`
> 
> which is strange coz they're the same and going to 127.0.0.1:8000 on the browser loads the app. Could there be some problem with how laravel resolves the `$dsn` in `Connector.php`? My error message contained the correct credentials but still didn't work when DB_HOST was assigned 127.0.0.1 instead of localhost:
> 
> ```
> PDO::__construct("mysql:host=127.0.0.1;port=3306;dbname=laravelnl", "mug", "secret", [])
> ```
> 
> * Windows 10
> * Using Laragon, app served with `php artisan serve`
> * * Laravel Framework 8.27.0
> * * PHP 8.0.1
> * * MySQL 5.7.24
> 
> Mind you, when I found this solution I had not restarted since running `composer update`, but I had done `php artisan cache:clear` and `php artisan config:clear` and was still getting errors

Not entirely sure, but I think your issue is that you have a mysql user which is created for `localhost`. Check this: https://stackoverflow.com/questions/19712307/mysql-localhost-127-0-0-1

**Comment by Oddward** [comment]
>
> Not entirely sure, but I think your issue is that you have a mysql user which is created for `localhost`. Check this: https://stackoverflow.com/questions/19712307/mysql-localhost-127-0-0-1

Oh wow that's interesting, that might be it, thanks. I haven't seen this mentioned across a dozen+ threads about this issue. I guess mysql doesn't necessarily resolve localhost into 127.0.0.1 and they have diff grants. 

Seems like laravel should use localhost as the default value, no?

**Comment by absoftware** [comment]
In my case it was about missing `"` around the password in the config and using `#`. The failure was caused by:

```
DB_PASSWORD=my1990password#1200
```

When I changed it into

```
DB_PASSWORD="my1990password#1200"
```

and executed commands

```
php artisan cache:clear
php artisan config:cache
php artisan migrate --env=production
```

then it works.
