### ISSUE TITLE
Environment based package discovery and post discover ComposerScripts hook

### ISSUE THREAD

**Issue by ycgambo** [laravel/framework#29348]
Since package discover is loaded, there are some use cases that I want to share.

## About environment

`composer  require --dev` and `npm install --dev` has totally different meaning, yet we still have the need of not to discover packages like  `laravel-debugbar` just in production.

The wired thing about **dev packages in production** is:
- if I remove the package, the code will be dead(Some Class is missing)
- if I keep the package, it may run some registration that I don't want to

The hack that I use is to extend the `Illuminate\Foundation\PackageManifest` class and overwrite the `packagesToIgnore` method, and then rebind the extended class into the IOC container:

```php
namespace App\Extend;

use Illuminate\Foundation\PackageManifest as Base;

class PackageManifest extends Base
{
    protected function packagesToIgnore()
    {
        if (! file_exists($this->basePath.'/composer.json')) {
            return [];
        }
        $extra = json_decode(file_get_contents(
                $this->basePath.'/composer.json'
            ), true)['extra']['laravel'] ?? [];
        return ($extra['dont-discover'] ?? []) + ($extra['dont-discover-' . config('app.env')] ?? []);
    }
}
```

This give me the ability to write composer.json like this:

```
   "extra": {
        "laravel": {
            "dont-discover-production": [
                "barryvdh/laravel-debugbar",
                "barryvdh/laravel-ide-helper"
            ]
        }
    },
```

## About post discover hook

Currently I use a Command that registered in `post-autoload-dump` to do custom things automatically. But it polluted the *package* command name prefix.

```
    "post-autoload-dump": [
        "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
        "@php artisan package:discover --ansi",
        "@php artisan package:post-discover"
    ],
```

Does the package discover post hook needed?

I'm not sure if all packages is discovered, that's why don't I run commands in `postAutoloadDump` Event.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
