### ISSUE TITLE
Dangerous flush

### ISSUE THREAD

**Issue by neoteknic** [laravel/framework#29349]
- Laravel Version: 5.8.29
- PHP Version: 7.3.7
- Database Driver & Version: Mariadb 10.4 Redis 5.0.5

### Description:
**Add a config option to disable Cache::flush(); and php artisan cache:clear**

As the Cache:flush(); is very dangerous because it remove the redis DB and dont use the CACHE_PREFIX.
It is possible in phpRedisAdmin to delete a cache tree, so it should be the same in Laravel (even if it's ugly). 
Just remove insecure Cache::flush() on some driver with a config option to enable it (it's safe with file driver, but not with redis driver), an application should not destroy date of another application, a simple warning on the documentation is not enought.
This method should be **disabled by default**.

### Steps To Reproduce:
Use Cache::flush(), it destroy Redis data of all other applications... (redis driver)

**Comment by jmarcher** [comment]
As a rule of thumb, use different databases for different applications

**Comment by neoteknic** [comment]
> As a rule of thumb, use different databases for different applications

No, Redis is not like a relational DB, you can't create a database without changing the config and restart, it's the same problem with memcached ... 

the cache:clear have to take the cache prefix

A simple fix is something like this in the cache:clear command (I override the command):
```php
             if($this->cache->getStore() instanceof RedisStore){
			/**
			 * @var \Redis $redis
			 */
			$redis=$this->cache()->getRedis();
			$application_keys=$redis->keys($this->cache()->getPrefix().'*');
			foreach ($application_keys as $key) {
				$redis->del($key);
			}
			$successful = true;
		}
		else{
			$successful = $this->cache()->flush();
		}
```

**Comment by jmarcher** [comment]
Redis comes with 16 Databases out of the box, that is what I'm talking about.

You fix will only work if a small number of keys are stored in Redis.

**Comment by neoteknic** [comment]
> Redis comes with 16 Databases out of the box, that is what I'm talking about.
> 
> You fix will only work if a small number of keys are stored in Redis.

if you have 100 Laravel app on a server you have to change the config... There is a cache prefix, it should be used to clear cache

**Comment by jmarcher** [comment]
Well, be responsible and do not host 100 Laravel apps on the same server. Sorry if this may sound rude but we can not implement things only to suffice the requirements of a few.

**Comment by mfn** [comment]
It's clearly in the docs https://laravel.com/docs/5.8/cache#removing-items-from-the-cache
>  Flushing the cache does not respect the cache prefix and will remove all entries from the cache. Consider this carefully when clearing a cache which is shared by other applications.

I know it's there because I added it myself after I was bitten by this.

Past issue: https://github.com/laravel/framework/issues/5034

The problem is a technical one: not all cache drivers support by removing by prefix out of the box; Redis being one of them.

It is possible with a workaround in Redis: you can iterate over the keys and filter out for the ones you care and the act on them (I see you figured this in your PR). But this is an *expensive* operation in Redis and if you've a LOT of keys this can freeze your Redis server, etc. Maybe there is something in newer version of Redis I'm not aware of.

So, as of now, the docs are the only protection and it's good to look them up before you use a certain feature 🤷‍♀️

If it's that important to you and you can live with the downsides, you have to use your own Redis driver (or maybe one exists already).

**Comment by neoteknic** [comment]
That's wrong you can select keys with a wilcard '$redis->keys('PREFIX:*')' with redis (phpredis), and not all keys, so you have to iterate, only on laravel keys, not all the db keys, you just should a config option to be able to use : destroying db, or clearing only laravel app cache (with select all laravel cache keys + iterate), it's very fast too, but I didn't tried it on more  than 1M keys.

@jmarcher it's just an exemple and it's stupid to stay that, you dont buy servers to fix a bug... , an application cache **shouldn't break another application**, it's not a requirement of a few... 
Just need a config to choose, it there is a cache_prefix, and Cache:flush() doest respect this by default, it's a bug and should be fixed if possible,the doc is OK, but many developper doesn't remember that, for redis it's possible and it's fast (many slow if more than 1M laravel keys...), for memcached it's possible too but you have to iterate over all keys.

I will try to make another driver it's you dont want to fix this bug.

**Comment by jmarcher** [comment]
I'm sorry if I triggered you but do you understand that this is not a bug? You can use the different databases in a Redis server.

And after all, clearing the cache should not break your application it is only a cache after all.

**Comment by driesvints** [comment]
Please use the recommended way of a separate Redis connection for your database and caches.

**Comment by mouhong** [comment]
This is not a bug, but it's too easy to be misused. 

Our team is bitten twice in 3 months. We thought it will just clear the local artisan file cache created by artisan optimize.
