### ISSUE TITLE
Public directory breaks urls structure

### ISSUE THREAD

**Issue by Mindexperiment** [laravel/framework#29341]
- Laravel Version: 5.8.29
- PHP Version: 7.1.19
- Database Driver & Version: -

### Description:
Hi, while building my website I noticed that a specific menu link didn't redirect correctly to the assigned path. By looking on the network section of the browser I saw that each time I click on that specific link the server respond with a "301 Permanently redirect" message and convert the path from an https to an http, causing also, a "mixed-content error message".

I start investigating the problem and find that the only place where there is a 301 redirect is inside the public .htaccess file:

```
    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} (.+)/$
    RewriteRule ^ %1 [L,R=301]

```

Here I notice that these rules checks if the path is a folder then, if true, the rule take place.

Well, the link I was using:
```
 Route::get( '/videos', 'VideosController@index' )->name( 'videos.index' );

```

and here is the problem, I have created a resources folder called /videos where I put all website generic video files then in webpack.mix.js

```
mix.copyDirectory('resources/videos', 'public/videos');
```

Et voilà! The url structure break!
I'm not sure if it's a known issue or if it's intended to work like this but it's a strange behaviour.

I don't know how to fix it.. :(
Thank you guys

### Steps To Reproduce:

1. Install a fresh new laravel instance
2. Force url scheme in AppProvider.php

```
    public function boot()
    {
        URL::forceScheme( 'https' );
    }
```

3. Open the route on web.php

```
Route::get( '/videos', function() {} )->name( 'videos.index' );
```

4. Add a folder inside your resources path with the same name as the route, for example: ***resources/videos***

5. publish the folder with webpack:

```
mix.copyDirectory('resources/videos', 'public/videos');
```

6. composer install
7. npm install
8. npm run dev
9. visit the route:

GET - https://you.com/videos
REDIRECT - http://you.com/videos/

**Comment by gofish543** [comment]
This does not sound like a Laravel bug, but rather you trying to use the same url to serve two different resources; the first is a resource folder and the other a Laravel route.

You cannot have one URL serve two different resources (unless, of course, you specify one to be a GET request and another be POST)

To fix your problem either
1) Change your Laravel route to something else
2) Move your public resources to a nested folder (Ex: 'public/resources/videos')

**Comment by Mindexperiment** [comment]
Hi @gofish

is ***/videos*** the same as ***/videos/*** ?

**Comment by gofish543** [comment]
In apache's eyes, yes. 

Your .htaccess fille
```
    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} (.+)/$
    RewriteRule ^ %1 [L,R=301]
```

This is the apache thought process with your rule inplace
---
* Alright we got a request at http://you.com/videos/
* Alright we located the http://you.com web root -> /var/www/you/
* Look!! An .htaccess file, lets load it! (Of course this is only the case if you configure apache to do so, which you did)
* Rewrite condition spotted! Time to check it
RewriteCond %{REQUEST_FILENAME} !-d then asks this question, "Does this folder exist, /var/www/you/videos"
RewriteCond %{REQUEST_URI} (.+)/$ then ask this question, "Does http://you.com/video/ end in a /"

If either are true, REDIRECT ME AWAY

**Comment by Mindexperiment** [comment]
Then, for example, serving images from a folder called ***/images/branding/googlelogo/2x/googlelogo_color_92x30dp.png*** (like google) makes that my website cannot have a section called /images to list somebody images. A bit forced imho.

**Comment by gofish543** [comment]
Keep in mind, this is not a Laravel thing. This is an apache configuration. Notice in my example that none of the requests even touched Laravel.

Now, to get around that "a bit forced imho". It really isn't... Check this out

Let's say now you have http://you.com and http://static.you.com
You can say in apache...
"I want you.com to push me into Laravel, regardless of if a folder exists or not"
"I want static.you.com to push me into my static folder content"

**Comment by Mindexperiment** [comment]
I thank you for the time you spend on answering.

Does FallbackResource directive changes the matter of the question?

vhosts.conf
```
<Directory "/var/www/vhosts">
 FallbackResource "/index.php"
</Directory>
```

this should force each request on /index.php front controller, that is Laravel.

**Comment by gofish543** [comment]
I am updating my previous answer when I was looking at my own personal .htaccess files and my documentation I found discrepancies. Give me a little bit.

**Comment by gofish543** [comment]
I apologize, I got mixed up myself. I forgot that multiple RewriteConds are implicit AND and only become 'OR' when explicitly stated. 

Now let's try to solve your problem, serving both out of the same virtual host

Because you are serving a conflicting HTTP Request space, Laravel's default .htaccess will not work for you (but we already know that)

.htaccess file
``` 
<IfModule mod_rewrite.c> // Makes sense, don't use something that doesn't exist
    <IfModule mod_negotiation.c> // Security, don't list indexes, etc.
        Options -MultiViews -Indexes // Don't list indexes, and whatever multi views is (I actually don't know)
    </IfModule> // Ending tag

    RewriteEngine On // Turn on the rewrite engine

    // We don't care about the below rule
    # Handle Authorization Header
    RewriteCond %{HTTP:Authorization} . 
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
    // End of rule we don't care about

    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d // If the target is not a directory 
    RewriteCond %{REQUEST_URI} (.+)/$ // And if the target ends in a slash
    RewriteRule ^ %1 [L,R=301] // Redirect removing the trailing slash

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d // If the target is not a directory
    RewriteCond %{REQUEST_FILENAME} !-f // And if the target is not a file
    RewriteRule ^ index.php [L] // Give the request to Laravel 
</IfModule>
```
It is now that we see the underlying issue, not the redirect, but rather the secondary set of rules. Since our target is a directory, index.php is never loaded causing Laravel to never load

To solve this, remove `RewriteCond %{REQUEST_FILENAME} !-d // If the target is not a directory`
This will break directory listings because any directory request will be rewritten to index.php

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by Mindexperiment** [comment]
Thank you @gofish543 , I choose to move the public folders to a different location on webpack.mix.js for now, it's the least invasive solution.

```
mix.copyDirectory('resources/images', 'public/resources/images');
mix.copyDirectory('resources/videos', 'public/resources/videos');

```
I want to leave the framework clean, I'll address the problem when necessary in the future.
