### ISSUE TITLE
Tests run out memory

### ISSUE THREAD

**Issue by psrumple** [laravel/framework#29344]
- Laravel Version: 5.8.30
- PHP Version: 7.3.4
- Database Driver & Version: MySQL 5.7

### Description:
After upgrading from 5.8.29 to 5.8.30, one of my tests cause php to run out of memory. After downgrading back to 5.8.29, the tests run fine. I'm using phpunit for the tests.

After further research, this appears to be linked to a single test testing Artisan commands. The particular test that fails stalls out and hangs for a good while in 5.8.30, whereas it was a fast test in 5.8.29.

### Steps To Reproduce:
It's linked to a single Artisan command test that is specific to my app, so I'm not sure how someone else could reproduce it. I can say that other tests involving that command still run fine and pass with flying colors, so I'm not sure how I can help you reproduce this.

**Comment by staudenmeir** [comment]
We won't be able to help you without a reproducible example. 

Please create a fresh Laravel installation and add code from your application until the issue appears.
