### ISSUE TITLE
PostgreSQL 11 window functions in Eloquent models

### ISSUE THREAD

**Issue by crayolaeater12** [laravel/framework#29340]
I can't seem to find anything in the documents regarding the usage of [pgsql's window functions](https://www.postgresql.org/docs/11/tutorial-window.html)
I would very much like to use this preferably via Eloquent ORM if possible.

**Comment by staudenmeir** [comment]
You can only use them with raw expressions:

```php
DB::table('empsalary')
    ->select('depname', 'empno', 'salary')
    ->selectRaw('avg(salary) OVER (PARTITION BY depname)');
```

**Comment by crayolaeater12** [comment]
I am satisfied with this answer. Thank you for your quick response...
