### ISSUE TITLE
Constraining Eager Loads - Instance of HasMany instead of Builder

### ISSUE THREAD

**Issue by kapalla** [laravel/framework#29352]
- Laravel Version: 5.8.30
- PHP Version: 7.3.7
- Database Driver & Version: SQLite

### Description:
Illuminate\Database\Eloquent\Builder::eagerLoadRelation() is passing the relation instance instead of a Builder instance.

I´ve tried to use the snippet from the [docs](https://laravel.com/docs/5.8/eloquent-relationships#constraining-eager-loads), but i always get an exception with this message:

`TypeError: Argument 1 passed to Tests\Unit\UserTest::Tests\Unit\{closure}() must be an instance of Illuminate\Database\Eloquent\Builder, instance of Illuminate\Database\Eloquent\Relations\HasMany given`

Sure, when i change the line from
```php
$constraints($relation);
```
to
```php
$constraints($relation->getQuery());
```
everything works as expected.

Am i doing something wrong, are the docs incorrect or is it bug?

### Steps To Reproduce:

1. Get a fresh copy of Laravel
2. Create a Post model (with e.g. title, body)
3. Set up the relations (User has many Posts, Post belongs to User)
```php
// User.php
public function posts()
{
    return $this->hasMany(Post::class);
}
```
```php
// Post.php
public function user()
{
    return $this->belongsTo(User::class);
}
```
4. Try the [snippet from the docs](https://laravel.com/docs/5.8/eloquent-relationships#constraining-eager-loads)
```php
$users = App\User::with(['posts' => function (Builder $query) {  // <- $query is an instance of HasMany
    $query->where('title', 'like', '%first%');
}])->get();
```

**Comment by kapalla** [comment]
Seems that only the type is wrong. I can use the code when i remove it.

```php
$users = App\User::with(['posts' => function ($query) {
    $query->where('title', 'like', '%first%');
}])->get();
```

`Relation`class uses forward calls to their `$query` property. Didn´t know that.

**Comment by staudenmeir** [comment]
Thanks, I'll fix the docs.

**Comment by ephraimlambarte** [comment]
this docs is still in [laravel 12](https://laravel.com/docs/12.x/eloquent-relationships#lazy-eager-loading).

 
![Image](https://github.com/user-attachments/assets/7aba9d5a-8318-4ce1-a153-57a1cb2dbd67)

**Comment by elburro1887** [comment]
Thanks for the help, I just encountered this issue, and also copied the code from the 11.x and 12.x docs.

Seems like commit https://github.com/laravel/docs/commit/dbb3411ad44095dcc7d6250973d084d7f6b9814c by @nunomaduro reverted this fix.

**Comment by DylanFrench** [comment]
This issue is still present in 11.x, 12.x, and Master/Upcoming docs.  I would argue to re-open the Issue.
