### ISSUE TITLE
Issue in php artisan queue:work in updated framework. [v5.8.30]

### ISSUE THREAD

**Issue by Hemant11111** [laravel/framework#29354]
As soon as i updated my laravel project to latest framework the supervisor stopped working.

For testing if i am sure about the issue i created a new project by
```
composer create-project --prefer-dist laravel/laravel testing
```
and run `php artisan queue:work --sleep=60 -v` and i got the same error.

```
  at /Users/hemant/Projects/laravel/testing/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:144
    140|         // process if it is running too long because it has frozen. This uses the async
    141|         // signals supported in recent versions of PHP to accomplish it conveniently.
    142|         pcntl_signal(SIGALRM, function () use ($job, $options) {
    143|             $this->markJobAsFailedIfWillExceedMaxAttempts(
  > 144|                 $job->getConnectionName(), $job, (int) $options->maxTries, $this->maxAttemptsExceededException($job)
    145|             );
    146| 
    147|             $this->kill(1);
    148|         });
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
