### ISSUE TITLE
Q: BroadcastException - Fail gracefully if no Pusher server is running?

### ISSUE THREAD

**Issue by nea** [laravel/framework#29351]
Hi

I am using Laravel Broadcast together with a websocket server. But I got a question regarding failing gracefully in the case the pusher server ist not running.

Right now, if the websocket serve is running all is working fine. But if the server is not running, all events trigger a

```
Illuminate \ Broadcasting \ BroadcastException
No message
exception in vendor\laravel\framework\src\Illuminate\Broadcasting\Broadcasters\PusherBroadcaster.php.
```

I could try/catch all events I am firing, but as I am also listening to Eloquent events this will become complicated.

Is there a way to fail gracefully in general? It shouldn't crash everything if the server e.g. has a hiccup, or should it?

I already checked the BroadcastServiceProvider with `auth:api` to support my Passport bearer and am allowing all channels for all users. Still, the issue.

Thanks a lot in advance

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
