### ISSUE TITLE
Model::whereHasMorph with wildcard not working as documented

### ISSUE THREAD

**Issue by zachleigh** [laravel/framework#29357]
- Laravel Version: 5.8.30
- PHP Version: 7.2.19
- Database Driver & Version: MariaDB 10.3.16

### Description:
When following the whereHasMorph with wildcard example in the docs ([Eloquent Relationships Page](https://laravel.com/docs/5.8/eloquent-relationships#querying-polymorphic-relationships)), I can't get it to work and I feel like I am missing a step. This is the example:
```php
$comments = App\Comment::whereHasMorph('commentable', '*', function (Builder $query) {
    $query->where('title', 'like', 'foo%');
})->get();
```

### Steps To Reproduce:
I followed the example directly with a model Images in my project:
```php
Image::whereHasMorph('imageable', '*', function (Builder $query) use ($attributes) {
    // nothing yet
});
```
When I called this code, I got this error message:
```
Call to undefined method App\Image::imageable()
```
I hadn't created a method on images yet for this relationship, so I did so. I wasn't sure if you could use a wildcard when defining a relationship:
```php
/**
 * Get all models that have images.
 */
public function imageable()
{
    return $this->morphedByMany('*', 'imageable');
}
```
Apparently you can't:
```
Class '*' not found
```
So then I thought that maybe I could pass an array of all models that have images:
```php
/**
 * Get all models that have images.
 */
public function imageable()
{
    return $this->morphedByMany([Project::class], 'imageable');
}
```
Nope:
```
Class name must be a valid object or a string
```
So maybe if you define all the relationships individually, it will scan for them and build an appropriate query?
```php
/**
 * Get all models that have images.
 */
public function projects()
{
    return $this->morphedByMany(Project::class, 'imageable');
}
```
No.
```
Call to undefined method App\Images\Image::imageable()
```
So I'm not quite sure what I'm supposed to do here or how this is supposed to work.

**Comment by staudenmeir** [comment]
`whereHasMorph()` can only be used with `MorphTo` relationships.

In your case, you need to add a `whereHas()` clause for every `imageable` `MorphedByMany` relationship:

```php
Image::where(function (Builder $query) {
    $query->whereHas('projects', function (Builder $query) {
        // $query->
    })->orWhereHas('relationship2', function (Builder $query) {
        // $query->
    })->orWhereHas('relationship3', function (Builder $query) {
        // $query->
    });
})->get();
```

**Comment by zachleigh** [comment]
Thanks for the clarification @staudenmeir. Closing.

**Comment by zachleigh** [comment]
If anyone is curious, you can achieve this dynamically using Builder macros to define the relationships on the fly in your query.
```php
public static function withImageables()
{
    $imageables = Imageable::all()->groupBy('imageable_type');

    $query = static::query();

    foreach ($imageables as $modelName => $collection) {
        $exploded = explode('\\', $modelName);

        $relationship = Str::plural(strtolower(end($exploded)));

        Builder::macro($relationship, function () use ($modelName) {
            return $this->getModel()->morphedByMany($modelName, 'imageable');
        });

        $query->with($relationship);
    }

    return $query->get();
}
```
