### ISSUE TITLE
Fix the Auth::id() inconsistency

### ISSUE THREAD

**Issue by emadha** [laravel/framework#29365]
Auth::id() doesn't validate if the ID of the user in the session, making the Auth::id() return wrong value if the user was deleted from the database.

this -> https://github.com/laravel/framework/issues/29259

**Comment by mpyw** [comment]
@driesvints At first, should we add documentation about this behavior?

![image](https://user-images.githubusercontent.com/1351893/62299004-1076ac00-b4af-11e9-90a3-a36a12c9f017.png)

**Comment by emadha** [comment]
@driesvints, well....

``` php
   // Get the currently authenticated user's ID
   $id = Auth::id();  🥇 
```

**Comment by emadha** [comment]
I submitted that in ideas https://github.com/laravel/ideas/issues/1750 but i still think it's more than an idea.
