### ISSUE TITLE
Making mock in setup() breaks serialization of Collection

### ISSUE THREAD

**Issue by denniskoster** [laravel/framework#29368]
- Laravel Version: 5.8.27
- PHP Version: 7.3
- Database Driver & Version: 5.7

### Description:
When I define a mock in the `setup()` method of a test case, using `shouldReceive()` and `returnUsing()`, a test serializing a collection breaks, throwing an exception: 
```
Serialization of 'Closure' is not allowed
```

### Steps To Reproduce:
Run the test below:
```php
<?php

namespace Tests\Unit;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Collection;
use Mockery;
use PHPUnit\Framework\TestCase;

class TestClass {
    public function test(): string
    {
        return 'test';
    }
}

class Test extends TestCase
{
    /**
     * @var Mockery\MockInterface|TestClass
     */
    protected $testClass;

    public function setUp(): void
    {
        parent::setUp();

        Mockery::mock(TestClass::class)
            ->shouldReceive('test')
            ->andReturnUsing(function () {
                return 'test';
            })
            ->getMock();
    }

    /**
     * @test
     */
    public function it_serializes_a_collection_with_a_mock_inside()
    {
        $collection = new Collection([Mockery::mock(Model::class)]);
        $serialized = serialize($collection);
        $unserialized = unserialize($serialized);
        $this->assertEquals($unserialized, $collection);
    }
}
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
