### ISSUE TITLE
Auth::attempt always return false

### ISSUE THREAD

**Issue by ho3einmolavi** [laravel/framework#29373]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Database Driver & Version:

### Description:

I want to login my users using passport but Auth::attempt always return false
here is my code
`<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class UserController extends Controller
{
    public function login(Request $request)
    {
        //validate data
        $val = $this->validate($request , [
            'email' => 'required|exists:users',
            'password' => 'required',
        ]);

        //check login user
        if (Auth::attempt($val))
        {
            $user = Auth::user();
            $success['token'] =  $user->createToken('jhxfjhsj')->accessToken;
            return response()->json(['success' => $success]);
        }
        else
        {
            return response()->json(['error'=>'Unauthorised'], 401);
        }
    }

    public function register(Request $request)
    {
        $this->validate($request , [
            'name' => 'required' ,
            'email' => 'required|unique:users|email' ,
            'password' => 'required' ,
            'type' => 'required' ,
        ]);

        $user = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => bcrypt($request->name),
            'type' => $request->type,
        ]);

        $success['token'] =  $user->createToken('MyApp')-> accessToken;
        $success['name'] =  $user->name;
        return response()->json(['success'=>$success]);

    }
}

`

**Comment by mputkowski** [comment]
`val` stores validation result, you should write something like that:

```php
$val = $request->only(['email', 'password']);

if (Auth::attempt($val))
{
    //rest of code
}
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by stone-hem** [comment]
Seems like the name is being hashed instead of the password
