### ISSUE TITLE
Undocumented functions

### ISSUE THREAD

**Issue by radosslav** [laravel/framework#29382]
- Laravel Version: 5.8
- PHP Version: 7.3
- Database Driver & Version: MySQL 8.0

Hello.

In Laravel API documentation, I find this method isWritable:
https://laravel.com/api/5.8/Illuminate/Filesystem/Filesystem.html#method_isWritable

It just a wrapper over is_writable PHP function.
https://github.com/laravel/framework/blob/5.8/src/Illuminate/Filesystem/Filesystem.php#L376

My question is - this method is not documented, and cant be found in the official framework documentation on https://laravel.com/docs/5.8/, and the same situation is with other methods too.

What is the reason for this? Because the method is insignificant or just because nobody before contributes and adds it to the docs?

I ask because is a good practice to fallow and write everything with "Laravel Way", for example, Eloquent over raw queries or in Blade @for/@endfor instead of just PHP native code.

How many other things are not documented in the main Docs and people don't know and not use them, simply because almost nobody read the API docs?

I open this issue and ask because for me personally all these methods are a hidden treasure and I prefer to use them and write "Laravel Way" as much as possible.

**Comment by driesvints** [comment]
You're always free to send in PRs to the docs for undocumented features. Thanks.

**Comment by radosslav** [comment]
Thanks, Dries!
