### ISSUE TITLE
make:auth reduces test coverage

### ISSUE THREAD

**Issue by sinkcup** [laravel/framework#29381]
- Laravel Version: 5.8.30
- PHP Version: 7.2.19
- Database Driver & Version: MySQL 5.7.27

### Description:

after run `php artisan make:auth`, the project's test coverage is reduced. because of this command create a new controller `HomeController`, but no test.

### Steps To Reproduce:

```
composer create-project --prefer-dist laravel/laravel blog
cd blog
./vendor/bin/phpunit --coverage-text tests/
```

> Code Coverage Report:    
>  Summary:                
>   Classes: 35.71% (5/14) 
>   Methods: 45.45% (10/22)
>   Lines:   44.44% (24/54)

```
php artisan make:auth
./vendor/bin/phpunit --coverage-text tests/
```

> Code Coverage Report:    
>  Summary:                
>   Classes: 33.33% (5/15) 
>   Methods: 41.67% (10/24)
>   Lines:   42.11% (24/57)

![image](https://user-images.githubusercontent.com/4971414/62349503-84a66380-b532-11e9-9a56-0496aa6da3cb.png)

**Comment by mputkowski** [comment]
It isn't an issue, don't expect that framework will generate tests ourselves, you should write them on your own.

**Comment by sinkcup** [comment]
I known. `make:auth` is not a framework, but a command, just like a package, it should take tests with itself. @mputkowski

**Comment by driesvints** [comment]
We're actually considering of adding these in a future update but for now please implement them yourselves.
