### ISSUE TITLE
Links to method definition/documentation

### ISSUE THREAD

**Issue by crayolaeater12** [laravel/framework#29384]
Can we have links to the API documentation when methods or builders are introduced? It may be beneficial for readers... an example would be the Eloquent model method `fresh()` which may apparently accept an array or string as a `$with` for eager loading according to [api documentation](https://laravel.com/api/5.8/Illuminate/Database/Eloquent/Model.html#method_fresh) but is not in anyway stated in [docs](https://laravel.com/docs/5.8/eloquent#query-scopes)

**Comment by driesvints** [comment]
That would be a little too much to maintain. There's so much changing on the core each day. Plus I wouldn't know how to do that since the docs are currently generated by http://sami.sensiolabs.org
