### ISSUE TITLE
Scheduling jobs throws error in tests

### ISSUE THREAD

**Issue by lorisleiva** [laravel/framework#29394]
- Laravel Version: 5.8.30
- PHP Version: 7.2.18
- Database Driver & Version: N/A

### Description:

Running `$this->artisan('schedule:run')` in a test makes the test pass but also throws a PHP Fatal Error when a Job is scheduled in the Kernel. More generally the error occurs when using `$event->name(...)` which is included by default in the helper method `$schedule->job(...)`.

![EA-0k1NXsAEY_Qw](https://user-images.githubusercontent.com/3642397/62394173-55a8e580-b564-11e9-9355-daf2e1bfc91b.jpeg)

### Steps To Reproduce:

- `laravel new project`
- `php artisan make:job MyJob`
- `php artisan make:test MyTest`

```php
// app/Console/Kernel.php
protected function schedule(Schedule $schedule)
{
    $schedule->job(new MyJob)->everyMinute();
}
```

```php
// tests/Feature/MyTest.php
class MyTest extends TestCase
{
    public function testExample()
    {
        $this->artisan('schedule:run');
        $this->assertTrue(true);
    }
}
```

- `phpunit`

**Comment by driesvints** [comment]
In your "name" example you're not providing the full namespace to the class in the `name` method. Try `name(MyJob::class)` instead. This should however work the same as the `job` method.

I can reproduce it but not sure what's going on. I only get one exception however when I cache the config. So maybe there's something going wrong there.

**Comment by lorisleiva** [comment]
Yeah, I initially had the fully qualified namespace but I used something simpler in my example to show that any string triggers the error.

**Comment by lorisleiva** [comment]
I've done a bit more digging and it looks like the issue comes from clearing the mutex for the scheduled event.

Commenting the line `$this->mutex->forget($this)` makes the tests work properly:

https://github.com/laravel/framework/blob/dd1a1edfcc1114d74a9d9ab662c81f9de37d7aba/src/Illuminate/Console/Scheduling/CallbackEvent.php#L91-L96

I think it could be something to do with the condition not checking enough variable since the condition to create the mutex is:

https://github.com/laravel/framework/blob/dd1a1edfcc1114d74a9d9ab662c81f9de37d7aba/src/Illuminate/Console/Scheduling/CallbackEvent.php#L58-L61

In fact, simply adding `$this->withoutOverlapping` to the `removeMutex` condition fixes this issue.

```php
protected function removeMutex()
{
    if ($this->description && $this->withoutOverlapping) {
        $this->mutex->forget($this);
    }
}
```

Should I create a PR for this or do you foresee any side effects?

**Comment by driesvints** [comment]
I don't know too much of the internals to know if this would have side effects.

**Comment by lorisleiva** [comment]
All tests were passing locally so I decided to create a PR.
