### ISSUE TITLE
Route::has() does not search $this->actionList

### ISSUE THREAD

**Issue by bilogic** [laravel/framework#29398]
- Laravel Version:  5.8.26
- PHP Version: 7.2.10
- Database Driver & Version: Not applicable

### Description:
```Route::has()``` does not seem to behave as documented, i.e. it does not seem to be able to find all named routes.

### Steps To Reproduce:
I have a named route as follows:
```Route::get("load/{any}", [\controller::class, "load"])->where('any', '.*')->name("c.loader");```

I expect ```Route::has("c.loader")``` to return true, but it returns false. Stepping into the code seems to indicate that ```$this->actionList``` is not searched, or that ```->name()``` is not adding the route into ```$this->nameList```

**Comment by staudenmeir** [comment]
Are you calling `Route::has()` in `routes/web.php`? That's not possible, the route names haven't been registered at that point. You can only use `Route::has()` later on, e.g. in a controller.

**Comment by bilogic** [comment]
You are right, but I see some names in ```->nameList``` when I step into ```Route::has()```, because of this, I assumed ```->name()``` did not work.

Could you point me to where ```"c.loader"``` is loaded into ```->nameList``` by Laravel? Thank you.

**Comment by staudenmeir** [comment]
It starts here: https://github.com/laravel/framework/blob/6a3b9530f8fc0e945187425ea78920da8a89a9b9/src/Illuminate/Foundation/Support/Providers/RouteServiceProvider.php#L39

**Comment by bilogic** [comment]
Thank you!
