### ISSUE TITLE
Why are attributes and relations mixed together?

### ISSUE THREAD

**Issue by CJDennis** [laravel/framework#29400]
- Laravel Version: 5.8.28

The `Illuminate\Database\Eloquent\Model` class has many Traits, two of which are `Illuminate\Database\Eloquent\Concerns\HasAttributes` and `Illuminate\Database\Eloquent\Concerns\HasRelationships`. There is not a single mention of attributes in `HasRelationships` which is how it should be. However, there are four methods solely to do with relations in `HasAttributes`:

- `public function relationsToArray()`
- `protected function getArrayableRelations()`
- `public function getRelationValue($key)`
- `protected function getRelationshipFromMethod($method)`

and one method that mixes attributes and relations:

- `public function getAttribute($key)`

Why does the `HasAttributes` Trait know about the `HasRelationships` Trait? The `Model` class uses both Traits but the Traits shouldn't know about each other. Why doesn't the `Model` check for the attribute and if it doesn't exist then check for a relation? If it was done that way there would be proper separation of concerns.

**Comment by tontonsb** [comment]
These functions populate attributes if there's a relation with a corresponding name. But they are still attributes, just created dynamically using relations. Maybe that makes the `HasAttributes` less reusable, but I feel that these concerns are separated in traits to simplify codebase not to actually reuse them.

However, I see your point. Not that these functions should be put within `HasRelations`, but separating them out in a `HasDynamicAttributes` trait would seem a decent organization as well. 

But I think the current implementation is such that these functions just don't do anything if your class doesn't has `HasRelations`. It seems you are able to sprinkle some `HasAttributes` magic without adding `HasRelations` and it just works without doing anything from relations, doesn't it? Well, unless you add some `relations` property or something that produces a collission...

**Comment by florentpoujol** [comment]
Yes, almost all other traits of the base model are also dependent on each other: for instance `HasAttributes::getArrayableItems()` also calls `HidesAtributes::getHidden()`.

Really them being traits has more to do with the idea of not shoving everything in the already very long Model class, than reusing them elsewhere or really properly separating concerns.  

The models attribute system is very central to Laravel, all integrated and quite complex, we should definitely think of all the traits as one unit instead of several independent ones.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
