### ISSUE TITLE
prefix routes redirects to default

### ISSUE THREAD

**Issue by aavinseth** [laravel/framework#29406]
- Laravel Version: 5.8.30
- PHP Version: 7.3.5
- Database Driver & Version: MariaDB 10.1.40

### Description:
created a routes with prefix and if tried to visit 123/settings/other it redirects to again to default prefix i.e 123/

Route::prefix('123')->group(function(){
Route::prefix('settings')->group(function(){
		Route::get('/', 'Controller@profile')->name('123.profile');
		Route::get('/other', 'Controller@otherprofile')->name('123.profile.otherrsettings');
	});
});

even my controller is also set to get

all this process is after authentication

I have update laravel from 5.8.29 to 5.8.30

**Comment by rimace** [comment]
I cannot reproduce this with 5.8.30. Do you have any auth middleware defined? They can also be defined in the controller, so better to look there too (once had a issue like this).
Do these routes work when you are unauthenticated?

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
