### ISSUE TITLE
resolveTableName in BelongsToMany class awaits certain Pivot model, but Pivot models usually extending from base Pivot class

### ISSUE THREAD

**Issue by 6562680** [laravel/framework#29421]
- Laravel Version: [none], using capsule, Illuminate\Database 
- PHP Version: 7.2
- Database Driver & Version: MySQL 8

### Description:
1. class Illuminate\Database\Eloquent\Relations\BelongsToMany;
2. method resolveTableName()
3.
```
        if ($model instanceof Pivot) {
            $this->using($table);
        }
```
4. Bug: Method awaits object of Pivot class instead of Pivot OR one of its children. (instanceof VS is_a())
5. Possible evade:
```
return $this->belongsToMany(Foo::class, (new FooBar)->getTable())->using(FooBar::class);
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by staudenmeir** [comment]
[`instanceof`](https://www.php.net/manual/en/language.operators.type.php) *does* work with child classes:

```php
return $this->belongsToMany(Foo::class, FooBar::class);
```

**Comment by 6562680** [comment]
By some reason i tried to use belongsToMany(Foo::class, FooBar::class) without ->using() and it wont work - #using property was null.

**Comment by staudenmeir** [comment]
What version of `illuminate/database` are you using?

**Comment by 6562680** [comment]
v5.8.27

Sorry, i found why. Its because Pivot originally is a Model.
So, if i extend Eloquent\Model - i should extend Pivot too.

I tried to pass my own pivot extended from my model using Eloquent trait \AsPivot;

Of course instanceOf will not detect my own pivot...

Check should use interface iPivot, or, yes, my mistake, i should extend Eloquent\Pivot... damn it, am using extended model with my own methods, would be great to use these methods in pivot too...

Gregory, "Dont touch the vendor" (c)
