### ISSUE TITLE
Email validator is not validating domain part

### ISSUE THREAD

**Issue by Gegirhasut** [laravel/framework#29433]
- Laravel Version: 5.8
- PHP Version: 7.2
- Database Driver & Version:

### Description:
Email validator in Laravel 5.8 accept email with wrong domain part.

### Steps To Reproduce:
1. Install Laravel 5.8
2. Add base authorization. You will have in RegisterController next function:
```
protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'min:6', 'confirmed'],
        ]);
    }
```
3. Try to Register with email "sadada@fsfdsfsdfds"- the domain part is not full.
4. Validator will accept email.

Laravel 5.7 is working fine.
Let's check the code in 5.7 and 5.8, file ValidatesAttributes.php

Laravel 5.7 (working, standard php function):
```
public function validateEmail($attribute, $value)
{
    return filter_var($value, FILTER_VALIDATE_EMAIL) !== false;
}
```

Laravel 5.8 (not working, something custom now):
```
public function validateEmail($attribute, $value)
{
    if (! is_string($value) && ! (is_object($value) && method_exists($value, '__toString'))) {
        return false;
    }

    return (new EmailValidator)->isValid($value, new RFCValidation);
}
```

**Comment by driesvints** [comment]
This is a valid email address. Please see [the related PR](https://github.com/laravel/framework/pull/26503) and tons of closed issues in the issue tracker.

**Comment by X-Coder264** [comment]
Yep, `sadada@fsfdsfsdfds` is a valid email address (with no TLD) -> https://github.com/egulias/EmailValidator/blob/master/Tests/EmailValidator/Validation/RFCValidationTest.php#L78

See

https://github.com/laravel/framework/issues/28316
https://github.com/laravel/framework/issues/27875
https://github.com/laravel/framework/issues/28596
https://github.com/laravel/ideas/issues/1555

etc
