### ISSUE TITLE
blade messes up raw html output with open="" attribute

### ISSUE THREAD

**Issue by retosteffen** [laravel/framework#29435]
- Laravel Version: 5.8.26
- PHP Version: 7.3.4

I was integration MathType with TinyMCE (https://docs.wiris.com/en/mathtype/mathtype_web/integrations/html/tinymce) in my laravel app. But when I want to output the raw html in my blade template it replaces the content of the open="[" attribute with open="open". Any html tag (span, p) with an open="" attribute gets replaced with open="open", so I don't think it's a MathType issue.

Example math formula:
`<math xmlns="http://www.w3.org/1998/Math/MathML"><mfenced open="[" close="]"><mtable><mtr><mtd><mi>d</mi></mtd></mtr><mtr><mtd><mi>a</mi></mtd></mtr></mtable></mfenced></math>`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by retosteffen** [comment]
I think that blade replacing <mfenced open="[" with <mfenced open="open" is a bug.

for info to make it work with MathType with TinyMCE  set wiriseditorsavemode = safexml for MathType
