### ISSUE TITLE
countBy bug, key disappear when you set 0 as the first item of array

### ISSUE THREAD

**Issue by LarryMckuydee** [laravel/framework#29444]
- Laravel Version: 5.8.27
- PHP Version: 7.3.5
- Database Driver & Version: MySQL Ver 14.14 Distrib 5.7.26

### Description:
There is a bug on countBy, where when you set 0 as the first item of array, keys for counted values will disappear 

### Steps To Reproduce:
Case: `collect([1, 0, 2, 0])->countBy()->all();`
Expected: `[ 1 => 1, 0 => 2, 2 => 1]`
Actual: `[ 1 => 1, 0 => 2, 2 => 1]`

But when **set 0 as the first item of array**
Case: `collect([0, 1, 2, 0])->countBy()->all();`
Expected: `[ 0 => 2, 1 => 1, 2 => 1]`
Actual: `[ 2, 1, 1]`

**Comment by staudenmeir** [comment]
This is actually not a bug in `countBy()` but the way JSON encoding works.

PHP encodes arrays differently:
- If the array has consecutive keys starting with `0`, it gets encoded as a JSON array (second case).
- Otherwise, it gets encoded as a JSON object (first case).

What does that part of your controller look like?

**Comment by LarryMckuydee** [comment]
I see,

well actually I'm not using it in controller, I use it in model to do some calculation.
And I got the **same result** doing testing in **php artisan tinker**.
but when dump inside countBy function itself, 
```
dd(new static($this->groupBy($callback)->map(function ($value) {
            return $value->count();
        })));
```

the collection items return correctly. Perhaps anyway I can **skip the JSON encoding**?

**Comment by staudenmeir** [comment]
But the code works when you test the model in a browser or a PHPUnit test?

**Comment by LarryMckuydee** [comment]
Nope, the code doesn't work,
It return correctly only when I **dd** inside **countBy function** itself in **app/vendor/laravel/framework/src/Illuminate/Support/Collection.php**

**Comment by staudenmeir** [comment]
What does the code look like?

**Comment by LarryMckuydee** [comment]
In **app/vendor/laravel/framework/src/Illuminate/Support/Collection.php**
```
...
public function countBy($callback = null)
    {
        if (is_null($callback)) {
            $callback = function ($value) {
                return $value;
            };
        }

        dd(new static($this->groupBy($callback)->map(function ($value) {
            return $value->count();
        })));

        return new static($this->groupBy($callback)->map(function ($value) {
            return $value->count();
        }));
    }
...
```

in terminal open repl with 
`php artisan tinker`

then execute 
`collect([0,1,2,0])->countBy()`

Then you should get the dump result from **dd**

**Comment by staudenmeir** [comment]
I meant the code from your model.

**Comment by LarryMckuydee** [comment]
Below is how the code look like, 

**application/app/SomeModel.php**
```
public function someActionBetween( $startDate, $endDate, $typeId) {
$records = $this->whereBetween('date', [$startDate, $endDate]);
...
$statuses = $records->where('type_id', '=', $typeId)
                                          ->pluck('status')
                                          ->countBy();
// here should return an array containing count for each status
// where the status is integer
...
}
```
$statuses should be an array containing count for each status

**Comment by staudenmeir** [comment]
How are you testing `someActionBetween()`? In Tinker?

**Comment by LarryMckuydee** [comment]
Yes

**Comment by staudenmeir** [comment]
If you want to test `countBy()` with these specific values in Tinker, you need to use `dd()`.

**Comment by LarryMckuydee** [comment]
I do use `dd()` as mention I dump result with **dd**.

**Comment by staudenmeir** [comment]
What does the exact look like?

`dd(collect([0,1,2,0])->countBy())` works for me in Tinker:

```php
Illuminate\Support\Collection {#3042
  #items: array:3 [
    0 => 2
    1 => 1
    2 => 1
  ]
}

```

**Comment by LarryMckuydee** [comment]
as mentioned 

> Nope, the code doesn't work,
> It return correctly only when I **dd** inside **countBy function** itself in **app/vendor/laravel/framework/src/Illuminate/Support/Collection.php**

anyway, still if without dd() not able to get correct result, 
`collect([0,1,2,0])->countBy()`
```
Illuminate\Support\Collection {#3082
     all: [
       2,
       1,
       1,
     ],
   }
```

**Comment by staudenmeir** [comment]
Yes, but that can't be fixed. Tinker outputs arrays as JSON and that's how JSON encoding works in PHP.

**Comment by LarryMckuydee** [comment]
I see,

Perhaps can be list as known issue,
because it is also returning wrong result when cast to string.
`$foo = collect([0,1,2,0])->countBy()`

on web browser `return $foo`
`[2,1,1]`

on tinker `return $foo`
```
Illuminate\Support\Collection {#3026
     all: [
       2,
       1,
       1,
     ],
   }

```

on `dd($foo)`  ps: this one correct
```
Illuminate\Support\Collection^ {#3026
  #items: array:3 [
    0 => 2
    1 => 1
    2 => 1
  ]
}

```

on `dd((string) $foo)`
`[2,1,1]`

on `echo $foo`
`[2,1,1]`

**Comment by driesvints** [comment]
This is unfortunately indeed a limitation of Tinker.
