### ISSUE TITLE
Cache ttl does not update after code change

### ISSUE THREAD

**Issue by imanghafoori1** [laravel/framework#29445]
- Laravel Version: 5.8.27
- PHP Version: 7.2.1
- Database Driver & Version: irrelevant

### Description:
When you cache a value with ttl of `5 hours` for example, and you run your code of course, the value get into the cache store.

Then if you change the $ttl down to 1 second and you start to re-run the code, you still get the cached value out of cache store, without hitting the actual underlying method.

It seems that it continue to get the value out of cache store until the 5 hour period finishes.

### Steps To Reproduce:
```php
Cache::remember('foo', 3600, function() {
    $int =  (string)random_int();
    dump('generating a new value to be cached... '.$int);
    return $int;
});
```
run your code, how ever you want to.

then change the $ttl down to 1:

```php
Cache::remember('foo', 1, function () { 
    $int =  (string)random_int();
    dump('generating a new value to be cached.... '.$int );
    return $int;
});
```
and re-run you code every 5 seconds...
you won't hit the closure.

It is a confusing behavior, I was confused last night and I had no idea about what's going on in my application. when I saw the $ttl was 0 and it was not hitting the closure.
It took me about 15 minutes to find out the reason.

Isn't it better to for the cache store to work according to the currently passed $ttl value ?!

**Comment by bonzai** [comment]
For me, it's not a bug because even if I change the TTL value, it doesn't mean previously cached data are invalid.

Can't you invalidate the cache?

**Comment by imanghafoori1** [comment]
Yes, it can be solved by cache::forget.

I don't think it is an explicit bug but any way it can trip a lot of people off.
I had been with laravel since version 4.0, but it easily made me : 😨  (what's going on ???!)

I don't think new comers can figure the situation out easily while in development, so it would be frustrating for them.

**Comment by X-Coder264** [comment]
I think that the documentation is pretty clear on this matter. The closure will be executed and its return value will be saved with the TTL specified only when the item does not exist in the cache. There is no mention there that you can change the TTL of an existing item via the `remember` method (and it also doesn't make sense for it to behave that way IMO).

**Comment by imanghafoori1** [comment]
I think it's just weird, you have 0 for ttl but the value is coming out from the cache.

That happens in development phase when playing around, and testing the app.

**Comment by driesvints** [comment]
This is the expected behavior.
