### ISSUE TITLE
phpredis publish not work

### ISSUE THREAD

**Issue by wenjy** [laravel/framework#29449]
- Laravel Version: 5.8.29
- PHP Version: 7.2.17
- Database Driver & Version:
Redis Extension: 4.3.0

### Steps To Reproduce:

.env 
`REDIS_CLIENT=phpredis`

database config
```
'client' => env('REDIS_CLIENT', 'predis'),
'default' => [
            'url' => env('REDIS_URL'),
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => env('REDIS_DB', 0),
        ],
```

use \Redis is work
```
$redis1 = new \Redis();
        $redis1->connect(config('database.redis.default.host'), config('database.redis.default.port'));
        $redis1->auth(config('database.redis.default.password'));
        $redis1->select(config('database.redis.default.database'));
        $clients_num = $redis1->publish('channel_test', 'message1');
```

not work
```
$redis = Redis::connection('default');
 $clients_num = $redis->publish('channel_test', 'message2');
        
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by wenjy** [comment]
Thanks!
Because I use ```redis.options.prefix```.
function subscribe() callback $channel will replace prefix to ''.

**Comment by sribna** [comment]
> Thanks! Because I use `redis.options.prefix`. function subscribe() callback $channel will replace prefix to ''.

Thanks! I spent all day trying figure out why my pu/sub channel don't work in external Nodejs script. Because Laravel automatically adds prefix to the channels 

`$prefix = config('database.redis.options.prefix')`
