### ISSUE TITLE
5.8.30 to 5.8.31 update on postgresql causes issue

### ISSUE THREAD

**Issue by bryanrscott** [laravel/framework#29443]
- Laravel Version: 5.8.31
- PHP Version: 7.3
- Postgresql (homestead or AWS)

### Description:
When updating model with timestamps enabled, an exception is thrown.  
Illuminate \ Database \ QueryException (42703)
SQLSTATE[42703]: Undefined column: 
It looks to be thrown because the "updated_at" column in the sql is prefixed with the table name. 

update "schema"."tablename" set "name" = CCCC, .....
"tablename"."updated_at" = 2019-08-07 04:20:58 where "id" = 1152

### Steps To Reproduce:
in composer.json set  "laravel/framework": "5.8.*" then run composer update

### WORK AROUND
in composer.json set  "laravel/framework": "5.8.30" then run composer update

**Comment by mfn** [comment]
From https://github.com/laravel/framework/releases/tag/v5.8.31 it seems [[5.8] Fix UPDATE queries with alias](https://github.com/laravel/framework/pull/29405) fits the bill maybe? But not sure why it would.

I've also upgraded and didn't encounter this in my tests (~6k, lots of DB); can please share the exact code producing this?

Still pinging @staudenmeir to the rescue ⛑

**Comment by jayked** [comment]
#29448 Should fix this issue. Complete strings after the first `.` were used as a column which breaks when you are using schema references. In the pull request this has been changed by exploding the string on the `.` and use the latest item of the resulting array, which is the actual column.

**Comment by staudenmeir** [comment]
Sorry about that.
