### ISSUE TITLE
When queue job class is not found, the error message is very vague

### ISSUE THREAD

**Issue by georgeboot** [laravel/framework#29459]
- Laravel Version: 5.8.30
- PHP Version: 7.3.3
- Queue driver: Redis / Horizon

### Description:
When the queue worker tries to execute a job class that does not exist, it will throw the following error:
```
Processing: App\Mail\PurchaseConfirmation
In SendQueuedMailable.php line 73:
method_exists(): The script tried to execute a method or access a property
of an incomplete object. Please ensure that the class definition "App\Mail\
PurchaseConfirmation" of the object you are trying to operate on was loaded
_before_ unserialize() gets called or provide an autoloader to load the cl
ass definition
PHP Fatal error: method_exists(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition "App\Mail\PurchaseConfirmation" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an autoloader to load the class definition in /var/www/vendor/laravel/framework/src/Illuminate/Mail/SendQueuedMailable.php on line 7
```

### Background:
We have separate deployments for our fpm and queue workers (Horizon).

We introduced a new Mailable: `App\Mail\PurchaseConfirmation`. This mailable was queued from fpm  to our redis. When the queue worker tried to execute the job, it failed with the above error.

After a lot of debugging, it turns out that our queue workers did not update to the latest code, so their code base did not contain the newly introduced `PurchaseConfirmation` class.

### Steps To Reproduce:

1. Make sure you have separate deployments for your fpm and queue.
2. Create a new mailable and update your fpm so that it now has the new mailable. Don't update your queue deployment.
3. From your fpm, push the mailable to the queue.
4. Because your queue deployment does not know the new mailable class, it will fail with the above error.

**Comment by driesvints** [comment]
Hey @georgeboot this is actually noted in the docs here: https://laravel.com/docs/5.8/queues#queue-workers-and-deployment

Maybe the error message can be better but that's an issue for the ideas repo. Feel free to open up an issue there if you think anything can be improved here.

Thanks.

**Comment by alkhachatryan** [comment]
@driesvints your link didn't help me with the same problem.

**Comment by renoirtech** [comment]
We've resolved this issue by running a simple composer update ¯\_(ツ)_/¯.
