### ISSUE TITLE
phpredis hScan While get

### ISSUE THREAD

**Issue by wenjy** [laravel/framework#29450]
- Laravel Version: 5.8.29
- PHP Version: 7.2.17
- Database Driver & Version:
Redis Extension: 4.3.0

### Steps To Reproduce:

.env 
`REDIS_CLIENT=phpredis`

database config
```
'client' => env('REDIS_CLIENT', 'predis'),
'default' => [
            'url' => env('REDIS_URL'),
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => env('REDIS_DB', 0),
        ],
```

this is work
```
$redis = Redis::connection();
        $it = null;
        $redis->setOption(\Redis::OPT_SCAN, \Redis::SCAN_RETRY);
        $key = 'test_hash1';
        $redis->hmset($key, [
            'key1' => 'val1',
            'key2' => 'val2',
        ]);
        while($data = $redis->client()->hScan($key, $it, '', 10)) {
            var_dump($data);
        }
```

this is not work
```
$redis = Redis::connection();
        $it = null;
        $redis->setOption(\Redis::OPT_SCAN, \Redis::SCAN_RETRY);
        $key = 'test_hash1';
        $redis->hmset($key, [
            'key1' => 'val1',
            'key2' => 'val2',
        ]);
        while($data = $redis->hScan($key, $it, '', 10)) {
            var_dump($data);
        }
```
This is must use $redis->client() ?

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
