### ISSUE TITLE
Unable to load the "app" configuration file. 

### ISSUE THREAD

**Issue by mouyong** [laravel/framework#29460]
- Laravel Version: #.#.# 
- PHP Version: 7.2.15
- Database Driver & Version: mysql & 5.7

### Description:

when i run project in laradock on windows 10, it cant't load `config/*` file, 

### Steps To Reproduce:

i try to know why, but i don't hao tow reproduce it.

storage/laravel.log have some exception.

```
Unable to load the "app" configuration file. {"exception":"[object] (Exception(code: 0): Unable to load the \"app\" configuration file. at /var/www/xxx/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php:67)
```

The Finder can't scan the config dir. i want know why. but fail. 

how can i do. i want to develop the project. but can't run the project in the laradock environment on windows 10.

**Comment by staudenmeir** [comment]
Please open an issue in the `laradock` repository. This doesn't look like an issue with Laravel but with your Docker environment. There was a [similar issue](https://github.com/laravel/homestead/issues/1219) with VirtualBox.

**Comment by driesvints** [comment]
Please see the answer above.

**Comment by mouyong** [comment]
Thank your answer.

Below is laradock issue.

https://github.com/laradock/laradock/issues/2234
