### ISSUE TITLE
possibility of increment more than one column 

### ISSUE THREAD

**Issue by mobayen** [laravel/framework#29484]
it would be helpful if it was possible to increment multiple columns when updating 
something like 
`
Model::where('id', 2)
  ->increment(
    ['count', 'total_count'],
    ['title', 'newtitle'],
  )
`

**Comment by staudenmeir** [comment]
Please use https://github.com/laravel/ideas/issues for proposals.

**Comment by staudenmeir** [comment]
This would also be a good first PR if you want to contribute to Laravel.

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!
