### ISSUE TITLE
Route caching vs. Non Route caching, model binding/injecting behaviour

### ISSUE THREAD

**Issue by peterfox** [laravel/framework#29487]
- Laravel Version: 5.8.30
- PHP Version: 7.2.19
- Database Driver & Version: N/A

### Description:

Model bindings behave differently using route caching to without route caching. When a model has been bound as a route parameter the parameter to the controller function has to be named the same as the route parameter it seems or otherwise it will cause a new instance of the model to be injected instead of the expected model from the route parameters. Without route caching it will work out the route binding based on the parameter's type instead of the name. I don't have a problem with the behaviour as such but it feels to me like this should be consistent across using route caching or not using it as me and colleague spent an afternoon having to check why code that was otherwise fine locally was not behaving as expected in a production like environment.

### Steps To Reproduce:

Set up a controller:

```php
class ExampleController
{
    public function invoke(User $owner)
    {
        dd($owner); // With route:cache this will be a new instance of User injected, without route:cache this will be the expected model instance injected with attributes from the database.
    }
}
```

Set up the same routing:

```php
Route::model('user', User::class);
Route::get('/user/{user}', ExampleController::class);
```

Call the route `/user/1` with a valid database etc. without route caching and the expected model is dumped, do it with route caching and simply get an empty instance.

**Comment by staudenmeir** [comment]
You need to put `Route::model()` in `RouteServiceProvider::boot()`. When the routes are cached, the `/routes` files aren't executed and `Route::model()` isn't called.

If you rename the parameter from `$owner` to `$user`, you can benefit from implicit route model binding:
https://laravel.com/docs/routing#implicit-binding

**Comment by peterfox** [comment]
Ok, thank you, I have renamed the variable to get around it.
