### ISSUE TITLE
Laravel 5.5.38 Session Memcache driver issue

### ISSUE THREAD

**Issue by ashahid007** [laravel/framework#29490]
OS: Centos 7 (Linux)
Apache WEB Server:
PHP Version 7.3.0
memcache support	enabled Version	3.0.9-dev
Laravel Framework 5.5.34

MY_MEMCACHE_SERVER server:
PHP Version 7.3.0
memcached
memcached support	enabled
Version	3.1.3
libmemcached version	1.0.18

### Description:

I am using Laravel memcched Session driver and it satrted behaving very strange after 4-5 months working perfectly fine.
I have no clue apart from diagnosing NTP issue (server time differences) both on WEB and MY_MEMCACHE_SERVER server.
I get "The page has expired due to inactivity. Please refresh and try again." once in day or two now. Which is impacting production and found out
temporary solution to restrt memcached service on MY_MEMCACHE_SERVER.

i check logs when this issue occur as below and also i am using separate logging to check if memcache itself is working out of LARAVEL. its working fine
without Laravel at that moment. all connect/get/set working and values properly set and retrieved at that moment.

Issue is only with Laravel Authentication mechanism at that time and have to restart MY_MEMCACHE_SERVER to work and avoid for a day or two
"The page has expired due to inactivity. Please refresh and try again."

I have switched to Laravel Session Database driver for now due to this and looking if the same issue arise in Database driver as well or not.

Please help.

### Memcache logs below:

memcached-tool MY_MEMCACHE_SERVER:11211 dump
Dumping memcache contents
  Number of buckets: 4
  Number of items  : 4
Dumping bucket 5 - 1 total items
Dumping bucket 6 - 1 total items
Dumping bucket 7 - 1 total items
Dumping bucket 8 - 1 total items

memcached-tool MY_MEMCACHE_SERVER:11211 display
  #  Item_Size  Max_age   Pages   Count   Full?  Evicted Evict_Time OOM
  4     192B         0s       1       0     yes        0        0    0
  5     240B         0s       1       1     yes        0        0    0
  6     304B         0s       1       1     yes        0        0    0
  7     384B         5s       1       1     yes        0        0    0
  8     480B         0s       1       1     yes        0        0    0

  
  memcached-tool MY_MEMCACHE_SERVER:11211 stats
#10.20.63.242:11211 Field       Value
         accepting_conns           1
               auth_cmds           0
             auth_errors           0
                   bytes         856
              bytes_read  1194823332
           bytes_written  1029414041
              cas_badval           0
                cas_hits           0
              cas_misses           0
               cmd_flush           0
                 cmd_get     2878242
                 cmd_set     2877754
               cmd_touch           0
             conn_yields           0
   connection_structures         369
        curr_connections          10
              curr_items           3
               decr_hits           0
             decr_misses           0
             delete_hits         993
           delete_misses        6648
       evicted_unfetched           0
               evictions           0
       expired_unfetched       16692
                get_hits     2859707
              get_misses       18535
              hash_bytes      524288
       hash_is_expanding           0
        hash_power_level          16
               incr_hits           0
             incr_misses           0
                libevent 2.0.21-stable
          limit_maxbytes    67108864
     listen_disabled_num           0
                     pid       16960
            pointer_size          64
               reclaimed       16696
            reserved_fds          20
           rusage_system  410.185345
             rusage_user  205.462989
                 threads           4
                    time  1565241530
       total_connections     2878265
             total_items     2877754
              touch_hits           0
            touch_misses           0
                  uptime      124065
                 version      1.4.15

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
