### ISSUE TITLE
Empty FormData in Laravel

### ISSUE THREAD

**Issue by manoelramos** [laravel/framework#29504]
- Laravel Version: 5.8
- PHP Version: 7.3.7
- Database Driver & Version: mysql

### Description:
I am using Vue on the front end and Laravel on the back end. I have a POST method, and I am submitting a FormData, but in Laravel I get an empty array.

### Steps To Reproduce:

Axios request: 
`export const createContent = (content) => {
    const token = localStorage.getItem('session');
    return instance.post('content', {...content}, 
        {headers: 
            {
                Authorization: `Bearer ${token}`, 
                'Content-Type': `multipart/form-data; boundary=${Math.random().toString().substr(2)}`,
            }
        }
    );
}
`

request in Vue Component: 

`
const fd = new FormData();
fd.append('text', this.text);
//fd.append('_method', 'PUT');
//fd.append('_method', 'POST');
//fd.append('_method', 'PATCH');

this.$store.dispatch('content/createContent', fd).then(res => {
    console.log(res);
});
`

in Laravel back end: 
`
Route::post('content', 'ContentsController@store')->middleware('auth:api');

public function store(Request $request)
{
    return $request;
}
`

Response: 
<img width="682" alt="image" src="https://user-images.githubusercontent.com/12393428/62834871-67575080-bc28-11e9-87a1-11ee88bdd805.png">

I already tried to put _method: PUT, POST and PATCH.

**Comment by devcircus** [comment]
You'll get help more quickly on one of the community help forums. 

I'd start by doing a quick axios post, with form data, to laravel, with everything else stripped out. Temporarily ignore vuex and just make a post request with axios. I use form data like this for 1000s of axios calls to laravel and they all work. 

Check out the sites below. I'm sure someone there will help. 

[Laravel Slack](https://larachat.co/)
[Laravel.io Forum](https://laravel.io/forum)
[Laracasts Forum](https://laracasts.com/discuss)
[StackOverflow](http://stackoverflow.com/questions/tagged/laravel)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by manoelramos** [comment]
I could do it using XMLHTTP, I think the problem is with Axios to send FormData
