### ISSUE TITLE
morphTo()->select($columns=[]) not working as expected

### ISSUE THREAD

**Issue by quangvision** [laravel/framework#29507]
Hello
  I have to model App\Product and App\Favorites:
  Model Favorite define one relationship with Product as:
 `public function favorited()
    {
        return $this->morphTo()->select('id','name','slug');
    }`
  I want to only select columns : id,name,slug of Product model when lazy-loading relationship as this:
  `$user->favorites()->with('favorited')->get();`
But only get full attributes of Product.
Do you know why?
Thanks

**Comment by staudenmeir** [comment]
What's your Laravel version?

**Comment by quangvision** [comment]
> What's your Laravel version?

Laravel 5.8.31 with Homestead 8.0.0 running on Windows

**Comment by staudenmeir** [comment]
I can't reproduce it, this has been working for me since #25662.

Please provide both models. Can you log the executed queries?

**Comment by quangvision** [comment]
> I can't reproduce it, this has been working for me since #25662.
> 
> Please provide both models. Can you log the executed queries?

Great thank for your support.
I managed to get it running as expected now. But now another mystery appears.
Two models as below:
`App\Tour
class Tour extends Model
{
    protected $appends = ['isFavorited'];
    public function favorites()
    {
        return $this->morphMany(Favorite::class, 'favorited');
    }
    public function isFavorited()
    {
        return (bool) $this->favorites->where('user_id', auth()->id())->count();
    }
    public function getIsFavoritedAttribute()
    {
        return $this->isFavorited();
    }
}`
and
`App\Favorite
class Favorite extends Model
{
    public function favorited()
    {
        return $this->morphTo();
    }
}`
And return below:
`return auth()->user()->favorites()->with('favorited:id,name')->get();`

As you can see, I only request id, name and appending isFavorited attributes to be returned but I see whole collection of favorites included as well.
Part of result like below image:
![2019-08-12_170746](https://user-images.githubusercontent.com/12606323/62858172-cea5fb00-bd23-11e9-856e-65abe03abe8f.png)
Do you know why?
Thanks :)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
