### ISSUE TITLE
Queue jobs with SerializesModels fail when eloquent collections are deserialized

### ISSUE THREAD

**Issue by Brenneisen** [laravel/framework#29525]
- Laravel Version: 5.8.29
- PHP Version: 7.3.7
- Database Driver & Version: MySQL 8.0

### Description:

After #29136 the deserialization of eloquent collections fails if elements are deleted in the meantime.

### Steps To Reproduce:

```
$event = new Event(User::all());

$serialized = serialize($event);

User::find(1)->delete();

unserialize($serialized); // It breaks with Undefined offset: 1
```

**Comment by driesvints** [comment]
PR was merged.
