### ISSUE TITLE
assertPushedWithChain's callback has the same job in callback's parameter

### ISSUE THREAD

**Issue by kangoo13** [laravel/framework#29531]
- Laravel Version: 5.8.31
- PHP Version: 7.2.19

### Description:

When I want to assert some custom stuff on the chained jobs that are in the queue, I realized that the job parameter of the callback function is 2 times the same job (FirstJob).

To be sure, i made a `var_dump(get_class($job));` and it showed 2 times FirstJob

### Steps To Reproduce:

```
Queue::assertPushedWithChain(FirstJob::class, [SecondJob::class], function (
            $job
        ) {
            if ($job instanceof SecondJob) {
                // NEVER ENTER THIS IF
                return $job->getTask()->action === Task::SEND_RESPONSE_API_ACTION;
            } else {
                return true;
            }
        });
```

### Expected behaviour 

In the callback, the first time I should have the `$job` of type FirstJob and the second time in the callback I should have a SecondJob `$job`

**Comment by driesvints** [comment]
Hmm, this is indeed how it's implemented atm but I'm wondering if this actually is the expected behavior. The `$callback` isn't documented either. At any rate, if we would change this it'd be a breaking change for sure.

**Comment by kangoo13** [comment]
Oh ok, I thought it was logic to iterate over the different jobs and not the same twice or more to assure that they assert the right data but I might be wrong ?

**Comment by driesvints** [comment]
I think the callback is only to perform assertions against the original job. But I agree it could be beneficial to also check the chained jobs. But that sounds like a feature more than a bug. Feel free to open up an issue on the ideas repo and maybe send in a PR. Thanks.

**Comment by SherSpock** [comment]
I also found this behavior confusing and would favor 'bug', minimally at the docblock level. 

Without the presence of a bool flag for single vs multiple callback application or the option to pass multiple callbacks, my expectation was that the callback would apply to every job in the chain.

The docblock for the version of Laravel I'm using reads: 
`Assert if a job was pushed with chained jobs based on a truth-test callback.`
