### ISSUE TITLE
Issue storing files with certain unicode characters

### ISSUE THREAD

**Issue by vfsoraki** [laravel/framework#29538]
Laravel: 5.8.28
Flysystem: 1.0.53

The issue is in method `putStream` in `Flysystem`, specifically line 114:

    $path = Util::normalizePath($path);

What this does is removing some characters from filename. The issue is that the "normalized" filename is not returned, and method `putFileAs` or `put` in `FilesystemAdapter` can not know whether filename is modified or not.

For example, I use it to store images like this:

    $path = Storage::putFileAs($folder, $file, $title);

and `$title` contains some characters that `Flysystem` does not like, resulting in `$path` not being the correct path of file stored.

I don't know if I'm using something wrong or not, but the current hacking solution is to use `Util::normalizePath` from `Flysystem` on `$title` before passing it to `Storage::putFileAs`.

**Comment by driesvints** [comment]
You should indeed strip out special characters before passing the parameters. I've always done this as well in my own apps.

**Comment by vfsoraki** [comment]
@driesvints

You miss understood the problem.

It's not stripping names or not. It the method returning wrong path, as it should return the real file path saved on disk.

If it is going to return it this way, it is not guaranteed that the file path is correct. Then there is no point in returning a path that maybe is nonexistent.

At least, it should throw an exception to notify user that path can not be saved correctly.

The way it works now, is not consistent, and doesn't seem logical.

**Comment by driesvints** [comment]
@vfsoraki Heya, thanks for explaining more. This is unfortunately not possible. The `put` method of the Flysystem Filesystem will only return a boolean so there's no way for us to know the new path. That's why I said that you should always make sure that the filename/path is normalized before you store it. The `Util::normalizePath` inside the Filesystem class is just a safety precaution for Flysystem itself.

**Comment by vfsoraki** [comment]
@driesvints

Thanks 

I think then the return value of function should be removed, or at least a notice should be added to documents.

My problem is solved, but it will surely happen for others again.

**Comment by driesvints** [comment]
@vfsoraki a note in the docs can definitely help. I'll send in a PR for this 👍
