### ISSUE TITLE
URL::defaults not working properly

### ISSUE THREAD

**Issue by CristianEstiber** [laravel/framework#29540]
- Laravel Version: 5.8.31
- PHP Version: 7.3.1

Afte rlaravel update I can't get URL:defaults working properly example:

Middleware:

```
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Support\Facades\URL;

class SetDefaultLocaleForUrls
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {

        URL::defaults(['locale' => app()->getLocale()]);
        return $next($request);
    }
}
```

Kernel.php:

```
protected $routeMiddleware = [
        'auth' => \App\Http\Middleware\Authenticate::class,
        'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        'bindings' => \Illuminate\Routing\Middleware\SubstituteBindings::class,
        'cache.headers' => \Illuminate\Http\Middleware\SetCacheHeaders::class,
        'can' => \Illuminate\Auth\Middleware\Authorize::class,
        'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
        'signed' => \Illuminate\Routing\Middleware\ValidateSignature::class,
        'throttle' => \Illuminate\Routing\Middleware\ThrottleRequests::class,
        'verified' => \Illuminate\Auth\Middleware\EnsureEmailIsVerified::class,
        'locale' => \App\Http\Middleware\SetDefaultLocaleForUrls::class,
    ];
```

web.php:

```
Route::group(['prefix' => '{locale}', 'middleware' => 'locale'], function () {
	Route::get(__('contact'), function () {
	    	return view('pages.welcome');
		})->name('contact');
});
```
calling the route like that: 

`<a class="nav-link" href="{{route('contact')}}">@lang('contact')</a>`

And it doesn't use the default locale from the middleware, it ask for second parameter:

`Missing required parameters for [Route: contact] [URI: {locale}/contact]`

**Comment by CaddyDz** [comment]
Add `'locale'` to your `web` middleware group like this
```php
 protected $middlewareGroups = [
        'web' => [
            // Keep other middlewares here, ommitted for brevety
            'locale',
        ],

        'api' => [
            'throttle:60,1',
            'bindings',
        ],
    ];
```

**Comment by CristianEstiber** [comment]
> Add `'locale'` to your `web` middleware group like this
> 
> ```
>  protected $middlewareGroups = [
>         'web' => [
>             // Keep other middlewares here, ommitted for brevety
>             'locale',
>         ],
> 
>         'api' => [
>             'throttle:60,1',
>             'bindings',
>         ],
>     ];
> ```

Thanks, works, but don't understand why doesn't work on routeMiddleware

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
