### ISSUE TITLE
Laravel doesn't seem to support numeric $_POST keys in validation rules

### ISSUE THREAD

**Issue by NaturalBornCamper** [laravel/framework#29544]
- Laravel Version: 5.8.21
- PHP Version: 7.3.1-fpm
- Database Driver & Version: No DB

### Description:
Laravel doesn't seem to support numeric $_POST keys when trying to validate input, including when the numeric key is between quotes to be treated as a string.

### Steps To Reproduce:
First, here is a working example:
```
$post = [
    'question1' => null
];
$validationRules = [
    'question1' => [
        'required'
    ]
];
$messages = [
    'question1.required' => 'Answer is null'
];

$validator = Validator::make($post, $validationRules, $messages);

if ($validator->fails()) {
    dd($validator->errors());
}
dd('all good');
```

Which displays:
```
    [messages:protected] => Array
        (
            [question1] => Array
                (
                    [0] => Answer is null
                )

        )

    [format:protected] => :message
```

Then a non-working example, if the `$_POST` key is only a number in a string:
```
$post = [
    '1' => null
];
$validationRules = [
    '1' => [
        'required'
    ]
];
$messages = [
    '1.required' => 'Answer is null'
];
```

Which displays:
```
    [messages:protected] => Array
        (
            [0] => Array
                (
                    [0] => The 0 field is required.
                )

        )

    [format:protected] => :message
```

As you can see, the custom message is not there, it added a non-existent index "0" validation message with the the default "required" error.

**Comment by staudenmeir** [comment]
Please see #29116.

**Comment by NaturalBornCamper** [comment]
Ah damn.. I had searched before and found a similar bug report, but failed to see this one.

And I built all my system with numeric keys after some online research to verify if this was acceptable :/ Well thanks for the info, refactoring time!
