### ISSUE TITLE
Laravel generates pagination links that contain invalid html code

### ISSUE THREAD

**Issue by liamoreilly** [laravel/framework#29551]
Invalid HTML is produced when displaying pagination results using https://laravel.com/docs/5.8/pagination#displaying-pagination-results

For example, Blade code such as 

```
<div class="pagination-wrapper">
    {{ $users->links() }}
</div>
```

produces the following HTML

```
<div class="pagination-wrapper">
    <ul class="pagination" role="navigation">

        <li class="page-item disabled" aria-disabled="true" aria-label="&laquo; Previous">
            <span class="page-link" aria-hidden="true">&lsaquo;</span>
        </li>

        <li class="page-item active" aria-current="page"><span class="page-link">1</span></li>
        <li class="page-item"><a class="page-link" href="http://trackit.test/items?page=2">2</a></li>
        <li class="page-item"><a class="page-link" href="http://trackit.test/items?page=3">3</a></li>

        <li class="page-item">
            <a class="page-link" href="http://trackit.test/items?page=2" rel="next" aria-label="Next &raquo;">&rsaquo;</a>
        </li>
    </ul>
</div>
```

The problem is the `ul` element is not allowed to have a `role` of `navigation`. This is invalid HTML (according to https://validator.w3.org/). The reported error is "Bad value navigation for attribute role on element ul."

**Comment by devcircus** [comment]
This change was made, but was reverted [here](https://github.com/laravel/framework/pull/27907), as it needs to be done in 6.0.

**Comment by driesvints** [comment]
This was sent in to the master branch and will be in the next release: https://github.com/laravel/framework/pull/27919
