### ISSUE TITLE
save and saveOrFail (different cases in deep level)

### ISSUE THREAD

**Issue by novaknole** [laravel/framework#29570]
Hello Artisans !!! 

I want to express my ideas and how I look at the situation about **save()** and **saveOrFail** functions.

**Issue 1)** If we look at the **save()**  function in laravel API docs, Its return value is only boolean and it doesn't state that it throws exceptions. If this is true, Does it mean that **save** method is never gonna throw any kind of exception at all? **NOTE**: I am not using any events in my models at all.
or what if save doesn't return boolean sometimes and throws exception? my **if, else** statement for checking if it got saved or not will not be valid.

**Issue 2)** Let's look at the following example.

```
DB::beginTransaction();
try{
  $model1 = new Type();
  $model1->test = 'great';
  $model1->save();

  $model2 = new Type();
  $model2->test2 = 'awesome';
  $model2->save();
  DB::commit();
}catch(Exception $e){
  DB::rollBack();
}
```

Let's imagine that the first **save()** didn't work and something happened, but the second **save()** worked.. Is it possible that my catch block will never get executed -  which leads to never rolling back and I will be left with the database which only stores my second **save()** ? 

I am asking this, because as I've said, **save** has return value as boolean. So it looks like to me that I have to write **if, else** statements for each save in transaction to figure out which returned false and then throw the exception myself for executing catch block.  Any ideas?

**Issue 3)** Let's look at the **saveOrFail** function which states that it's **transactional**. I've looked at the official code for it and all it does is it wraps **save** method in transaction. Seems like this mightn't always throw exception and depends on what save() will return.? so how can we say 100% that this will always throw exception ?

Would be great if someone could really say something about this as documentation really doesn't state cases like this. These kind of questions also could be asked about multiple **updateOrCreate** in transactions? will they behave like **save()** or what?

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!
