### ISSUE TITLE
 I'm using laravel socialite 3 but when I try to refresh the page, an abstract error appears. Why

### ISSUE THREAD

**Issue by danielshongo** [laravel/framework#29573]
- Laravel Version: 5.6
- PHP Version: 7.1
- Database Driver & Version: MYSQL

THAT IS THE ERROR I GET 

Client error: `POST https://graph.facebook.com/v3.0/oauth/access_token` resulted in a `400 Bad Request` response: {"error":{"message":"This authorization code has been used.","type":"OAuthException","code":100,"fbtrace_id":"A8HAtE6A6m (truncated...)

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
