### ISSUE TITLE
Validation translates with prefix do not replace custom attributes correctly

### ISSUE THREAD

**Issue by xkovacikm** [laravel/framework#29578]
- Laravel Version: 5.8.*
- PHP Version: 7.2

### Description:

Hello guys :)

i have a quite problem here. I load validation translation messages from external package. 
So i had to use `loadTranslationsFrom( $somePath, "core")` method in **ServiceProvider**.

Now i want to validate my request by FormRequest, but translates are not resolved!

So in my **CustomFormRequest** file i did following thing:
```
public function messages() {
	return [
	    'required' => __("core::validation.required" ),
	];
    }
```

But if i fill data to attributes array in my validation.php file **(in external package)**:
```
'attributes' => [
	"name" => "Name",
	"email" => "E-mail",
	"phonenumber" => "Phone number",
    ],
```
attributes are not replaced in validation error messages because of method `getAttributeFromTranslations($name)` in **Illuminate\Validation\Concerns\FormatsMessages**
```
protected function getAttributeFromTranslations($name)
    {
        return Arr::get($this->translator->trans('validation.attributes'), $name);
    }

```
there is hardcoded string `'validation.attributes'` and in my case there should be `'core::validation.attributes'`

Is there possibility to fix this issue somehow? Thanks a lot guys
Have a nice day :)

**Comment by driesvints** [comment]
Hey @xkovacikm. What does your `rules` function look like? Normally you'll need to specify the `rule.validator` in your key for your `messages` function as described here: https://laravel.com/docs/5.8/validation#customizing-the-error-messages

**Comment by xkovacikm** [comment]
My rules method looks like this:

```
public function rules() {
	return [
	    "name" => "required",
	    "email" => "required",
	    "phonenumber" => "required",
	    "subject" => "required",
	    "message" => "required",
		//
	];
    }
```

and no, i **DO NOT** need to specify rules like this:
```
public function messages() {
	return [
	    'phonenumber.required' => __("Please enter your Phone number" ),
	];
}
```

I can do: 
```
public function messages() {
	return [
	    'required' => __("core::validation.required" ),
	];
}
```
**because i want to translate EVERY required rule.**
But like i said in previous message, problem is, that attribute name is not translated. Message is, but attribute is not.

Final message look like: 
_You need to enter your phonenumber._
and it should be:
_You need to enter your Phone number._

See? i defined my attribute translation array, but it is not resolved because of 
`Illuminate\Validation\Concerns\FormatsMessages::getAttributeFromTranslations($name)` because there is hardcoded string 'validation.attributes'

I hope I clarified it a bit better

**Comment by driesvints** [comment]
The docs state: 

> This method should return an array of attribute / rule pairs and their corresponding error messages

So I'm afraid this isn't possible atm. You can open up an issue on the ideas repo if you like if you want this to be supported and maybe send in a PR request that implements the feature.

**Comment by xkovacikm** [comment]
Okay, thanks.

funny thing is I created issue in ideas repo few weeks ago and i was sent here to report a bug :) Quite an endless loop.

But maybe if I'll have free time to learn how formatting workflow works and be able to fix it, I'll sent PR request.
