### ISSUE TITLE
npm run watch won't serve the application

### ISSUE THREAD

**Issue by TadeuOliveira** [laravel/framework#29607]
- Laravel Version: 5.8.32
- PHP Version: 7.2.19
- Database Driver & Version: mysql Ver 14.14 Distrib 5.7.27

### Description:

Even starting out a fresh project, npm run watch won't work.
netstat won't show a node port whenever I run this command.
When I attempt to use browserSync, the "Proxying" URL points to an unreachable page showing either *DNS_PROBE_FINISHED_NXDOMAIN* (when I use a named domain for browserSync, such as 'my-app.dev') or *ERR_EMPTY_RESPONSE* (when I use simply 'localhost:3000' or any other port).
If the following infos help in some way, I'm using Ubuntu 19.04 (also didn't work on 18.04), npm 6.10.2 and node v10.15.2. npm works normally for me in other frameworks such as vue using vue-cli.

### Steps To Reproduce:

On the console:
laravel new app
cd app
npm install
npm run dev
npm run watch

![image](https://user-images.githubusercontent.com/12589387/63178010-833f6580-c01f-11e9-9fbe-d856c6cb34b8.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
