### ISSUE TITLE
Validator with Rule::in() not work as expected in chinese

### ISSUE THREAD

**Issue by hxshandle** [laravel/framework#29617]
- Laravel Version: 5.8.*
- PHP Version: 7.1.16
- Database Driver & Version:

### Description:

Hi team,
  The Validator with Rule::in() not works as expected when there is any Chinese items in Rule::in() array.  Details see the bellow code.

### Steps To Reproduce:
```
public function test_validator_works_as_expected()
    {
        $testData = ['abc'];
        $v = \Validator::make($testData, [
            "0" => [Rule::in(['abc', '中文'])]
        ]);
        self::assertTrue(!$v->fails());
    }
```

The above code will green as expected but when I change the $testData value to "中文", the test will fail, even the "中文" is listed in rule array.
```
public function test_validator_will_fail()
    {
        $testData = ['中文'];
        $v = \Validator::make($testData, [
            "0" => [Rule::in(['abc', '中文'])]
        ]);
        self::assertTrue(!$v->fails());
    }

```
Great thanks for any help
-Handle

**Comment by hxshandle** [comment]
Hi team,
  I think I found the root cause please see attached image, 
  The following code works wrong in chinese.
```
[$rule, $parameters] = ValidationRuleParser::parse($rule);
```

**Comment by staudenmeir** [comment]
I can't reproduce this, your example works for me.

Please open the `$parameters` array in the "Variables" section of PhpStorm and post a new screenshot.

**Comment by staudenmeir** [comment]
I can't reproduce this issue. Your last example gives me the correct result:

```php
array:2 [▼
  0 => "abc"
  1 => "中文"
]
```

Is your PHP file encoded as UTF-8?

**Comment by hxshandle** [comment]
Thanks @staudenmeir , I found the root cause, setlocale(LC_ALL,"zh_CN.UTF-8") will resolve the issue.
