### ISSUE TITLE
required_without bug

### ISSUE THREAD

**Issue by mshomali** [laravel/framework#29623]
- Laravel Version: 5.5.*
- PHP Version: 7.3.7
- Database Driver & Version: sqlsrv

### Description:
I use required_without validation rule such as following code:
```
public function rules()
{
    return [
        'national_code' => 'required_without:national_id | numeric | digits:10 | codemelli',
        'national_id'   => 'required_without:national_code | integer',
    ];
}
```
when I pass national_id parameter to request I get following error:

> national_code is required if national_id is not present.

and if I pass national_code to request and don't pass national_id I get following error:

> national_id is required if national_code is not present.

I find the problem. The problem is I put a space between required_without and pipe operator and if I remove space It's work correctly and I think this is a bug.

**Comment by nmfzone** [comment]
It's not a bug. It's just because you don't write code like what it should.

**Comment by mshomali** [comment]
@nmfzone 
Yes, You 're right. It's not a bug.
Thanks.
