### ISSUE TITLE
Eloquent Relation ignores its NULL column

### ISSUE THREAD

**Issue by emadha** [laravel/framework#29622]
- Laravel Version: 5.8.#
- PHP Version: 7.#.#
- Database Driver & Version: MariaDB

### Description:
Eloquent with a relation, say HasMany, doesn't care about the NULL column and keep trying to get the Model.

### Steps To Reproduce:
``php artisan make:model Category -mc``
Migaration should have something like `category_id` // like a parent category
```php
Schema::create('categories', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->unsignedBigInteger('category_id')->nullable(); // <- parent category
            $table->string('title');
            ...
        });
```

Model App\Category:

   ```php
   /**
     * Get the parent category
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function category()
    {
        return $this->belongsTo(Category::class);
    }
```

Until now it's fine, But:

Add the ```$with = ['category']``` to the Eloquent and you'll get a query like this when the category_id is NULL:

**Debugbar** final query:
``select * from `categories` where 0 = 1``

**App\Category->category()->toSql()** Builder query:
``select * from `categories` where `categories`.`id` is null``

And you can get the same result if you get the relation of a null colum without using the $with:
$CategoryWithCategoryIDNULL = Category->category()->toSql();

**remember** The table's name is category and it has ID and another column called category_id,
you can name it parent_id if you got confused with double the names.

**Comment by staudenmeir** [comment]
> Debugbar final query:
select * from `categories` where 0 = 1

This eager loading query is indeed unnecessary, but it would require bigger changes in the Laravel code to prevent such a query.

> App\Category->category()->toSql() Builder query:
select * from `categories` where `categories`.`id` is null

This query does not actually get executed during lazy loading. If you run `(new Category)->category` you'll see that Laravel detects the empty foreign key and doesn't execute any query (#26992).

**Comment by emadha** [comment]
@staudenmeir correct, i just checked 
```php
dump(Category::find(1)->category);
```
in Debugbar it doesn't log anything.

And as you said 
```php 
dump(Category::with(['category'])->find(1));
``` 
will log ``select * from `categories` where 0 = 1``

**Comment by emadha** [comment]
I play around with it and updated the Builder.php

```php
  /**
     * Eagerly load the relationship on a set of models.
     *
     * @param  array  $models
     * @param  string  $name
     * @param  \Closure  $constraints
     * @return array
     */
    protected function eagerLoadRelation(array $models, $name, Closure $constraints)
    {
        $keys = [];

        // First we will "back up" the existing where conditions on the query so we can
        // add our eager constraints. Then we will merge the wheres that were on the
        // query back to it in order that any where conditions might be specified.
        $relation = $this->getRelation($name);

        $relation->addEagerConstraints($models);

        foreach ($models as $model) {
            if (! is_null($value = $model->{$relation->getForeignKeyName()})) {
                $keys[] = $value;
            }
        }

        if(!$keys)
            return [];

        $constraints($relation);

        // Once we have the results, we just match those back up to their parent models
        // using the relationship instance. Then we just return the finished arrays
        // of models which have been eagerly hydrated and are readied for return.
        return $relation->match(
            $relation->initRelation($models, $name),
            $relation->getEager(), $name
        );
    }
```

Added the checks happening in BelongsTo->getEagerModelKeys() into Builder->eagerLoadRelation();

What's your feedback on this @staudenmeir ?

**Comment by emadha** [comment]
okay , i just realized that my suggestion was a disaster 💃

**Comment by driesvints** [comment]
@staudenmeir do you think these changes are worth solving this?

**Comment by staudenmeir** [comment]
@driesvints Although the required changes would be smaller than I initially thought, I'm leaning towards keeping the current behavior.

Compared to the unnecessary lazy loading queries from #26992, this issue only affects `BelongsTo`/`MorphTo` relationships and only eager loading queries where *all* foreign keys are `null`.

**Comment by emadha** [comment]
In my situation this generated 1 of that query of 500mirosecond each because my Eloquent (Article) requires Category, and Category needs to generate it's relative link from the parent category, so it checks for those, for performance reasons i had to load the view like that Article::with([....]), each one of those eventually has  root category which has no parent category, resulting in that unneeded query.

So if you say i have 50 Articles being loaded, that's 50 ``0=1`` queries.

I tried to solve the problem my self, updating the Builder.php but it always created a bug somewhere else in the code so i stopped for now.

I think it's worth taking a look at.

**Comment by emadha** [comment]
And if it's a hard fix, it's better if Laravel doesn't send invalid queries

**Comment by staudenmeir** [comment]
I'll work on a draft to put it up for discussion.

The fix isn't complicated, but it adds an overhead for all relationships, not just `BelongsTo`/`MorphTo`.

**Comment by emadha** [comment]
Thank you, when i have time i'll take a look on how that thing works in code, or if you can give a hint i'll be thankful.

**Comment by driesvints** [comment]
@staudenmeir have you had time yet to look into a draft for this?

**Comment by staudenmeir** [comment]
@driesvints No, I haven't.

**Comment by driesvints** [comment]
No worries 👍

**Comment by driesvints** [comment]
@staudenmeir is there any chance you can point me in the right direction so I can maybe tackle this myself?

**Comment by staudenmeir** [comment]
@driesvints We would need to adjust `Eloquent\Builder::eagerLoadRelation()` and only execute the eager loading query if necessary.

**Comment by taylorotwell** [comment]
No plans to change this as it does not cause any "bug" in applications.
