### ISSUE TITLE
If my gmail password contains a hash symbol(#) at the end it gets dropped in bootstrap/cache/config.php when I run the command php artisan config:cache

### ISSUE THREAD

**Issue by lycidas100** [laravel/framework#29632]
- Laravel Version: 5.8.11
- PHP Version: 7.1.31
- Database Driver & Version :MYSQL driver

### Description:
If my gmail password contains a hash symbol(#) at the end (i.e xxxxxxxxxx#) it gets omitted in bootstrap/cache/config.php when I run the command php artisan config:cache. 
This causes an error when sending an email through Laravel. It took me a while to discover what was causing the error. 

### Steps To Reproduce:
Add a password with a # at the end as described above to MAIL_PASSWORD in .env file

**Comment by staudenmeir** [comment]
You need to wrap the value in  quotes:
https://laravel.com/docs/5.8/upgrade#environment-variable-parsing
