### ISSUE TITLE
MorphPivot Model deleting events are not fired

### ISSUE THREAD

**Issue by lorado** [laravel/framework#29631]
- Laravel Version: 5.8.32
- PHP Version: 7.3.1
- Database Driver & Version: PostgreSQL 10.6

### Description:

Laravel 5.8 supports events firing on pivot models. Unfortunately I face the problem, that Pivot with Morph-relation don't fire `deleting` and `deleted` events.

### Steps To Reproduce:

Create Intermediate Table / Pivot Model and define events on boot, e.g.

```php
namespace App;
use Illuminate\Database\Eloquent\Relations\MorphPivot;

class BranchConsultant extends MorphPivot
{
    public static function boot()
    {
        parent::boot();
        $events = [
            'retrieved', 'creating', 'created', 'updating', 'updated',
            'saving', 'saved',
            'deleting', 'deleted',
        ];
        foreach($events as $event) {
            static::$event(function ($item) use ($event) {
                \Log::info("**** {$event} has been fired!");
            });
        }
    }
}
```

Try to attach, detach or sync your objects - `deleting` or `deleted` events are never fired.

### Why is it happening?

`Illuminate\Database\Eloquent\Relations\MorphPivot` extend `Illuminate\Database\Eloquent\Relations\Pivot`, as it has to implement nature of morph relations. To be able to delete correct pivot row properly, delete query has to be updated like this: `$query->where($this->morphType, $this->morphClass);` With it `delete` method overrides `delete` method from `Pivot` class (from `AsPivot`-trait better said).

In January this year `delete` method on regular Pivot model got updated - amongst other things events were implemented, but MorphPivot has still old codebase.

### Solution discussion

I don't really know what is 'laravels'-way to implement things, but I have two suggestions to solve this problem.

1. Update `Illuminate\Database\Eloquent\Relations\MorphPivot::delete()` method to something like this:

```php
/**
 * Delete the pivot model record from the database.
 *
 * @return int
 */
public function delete()
{
    if (isset($this->attributes[$this->getKeyName()])) {
        return (int) parent::delete();
    }

    if ($this->fireModelEvent('deleting') === false) {
        return 0;
    }

    $this->touchOwners();

    return tap($this->getDeleteQuery()->where($this->morphType, $this->morphClass)->delete(), function () {
        $this->fireModelEvent('deleted', false);
    });
}
```

This is actually currently implementation of `Illuminate\Database\Eloquent\Relations\Concerns\AsPivot::delete()` with only one extra code: `->where($this->morphType, $this->morphClass)`

But I am not sure, if first 3 lines of method are also relevant for morph pivots. Tbh I don't really understand the situation, where this if-statement gets executed.

Other stuff seems to be right for me - call deleting event with evtl. breaking, touchOwners and then delete pivot row with firing deleted event afterwards.

2. On the other side it is kinda duplicated code, and we are here now because of it. Isn't it better to call `parent::delete()` with some argument? E.g. give a closure as argument, that hangs this additional where to SQL statement before it gets sent to DB.

```php
// MorphPivot.php
public function delete()
{
    return parent::delete(function($query) {
        return $query->where($this->morphType, $this->morphClass);
    });
}
```

```php
// AsPivot.php
public function delete($modifyQueryClosure)
{
    if (isset($this->attributes[ $this->getKeyName() ])) {
        return (int) parent::delete();
    }

    if ($this->fireModelEvent('deleting') === false) {
        return 0;
    }

    $this->touchOwners();

    $query = $this->getDeleteQuery();
    if (isset($modifyQueryClosure) && $modifyQueryClosure instanceof \Closure) {
        $query = $modifyQueryClosure($query);
    }

    return tap($query->delete(), function () {
        $this->fireModelEvent('deleted', false);
    });
}
```

In my opinion the second solution is better. Let me know what do you think, and I will create a PR with right solution

**UPDATE**: Just tried second solution locally - it is probably not that good solution, as it violates `Model::delete()` compatibility. Well, then first one? Or is there a better solution?

**Comment by taylorotwell** [comment]
This was fixed on 6.x forward. Laravel 5.8 is no longer maintained.
