### ISSUE TITLE
Eloquent event 'retrieved' is being emitted prior to eager loading relations

### ISSUE THREAD

**Issue by denjaland** [laravel/framework#29630]
It seems that the Eloquent `retrieved`events are being emitted by the framework prior to loading the eager relationships.

This causes for the N+1 query issue to persist even when trying to eager load (in fact, it now becomes a N+1+1 issue ;-) ) a relation that is depended on in the code that listens to the `retrieved` event.

Have a look at this trait: https://github.com/laravel-enso/versioning/blob/master/src/app/Traits/Versionable.php 

It's working incredibly well, but as you can see at https://github.com/laravel-enso/versioning/blob/master/src/app/Traits/Versionable.php#L21, it is fetching the relation there, and since this code is run *before* the eager loading of the relationship, this is being executed for each individual event.

Is this expected behaviour, or am I right in thinking the event should only be dispatched after eager loading the requested relationships?

**Comment by staudenmeir** [comment]
That's expected behavior.

> This causes for the N+1 query issue to persist even when trying to eager load (in fact, it now becomes a N+1+1 issue ;-) ) a relation that is depended on in the code that listens to the retrieved event.

Can you provide a simple example?

**Comment by denjaland** [comment]
Hi,

Well, the linked line in that trait is the example.
Consider this...

    protected static function bootMyTrait()
    {
        self::retrieved(function ($model) {
            // If you require a related model here and retrieve it like this for example...
            $model->myRelation;
        }
    }

And you do this in your model:

    public class MyModel extends Model {
        protected $with = ['myRelation'];
    }

and then fetch the model:

    $myModems = MyModel::all();

You will get the following database queries:

    SELECT * FROM my_models  // retrieving the models from the database

Then, for each retrieved model:

    SELECT * FROM my_relations WHERE my_model_id = '?'

--> this is already being executed before the relation I wanted to eager load is being called!
Finally, you get an eager loading relation query:

    SELECT * FROM my_relations WHERE my_model_id IN ('?', '?', .... {n})

So, in the end, this causes for N+2 queries. I have now disabled eager loading on the model again to go back to N+1, vut I would like to get down to 2 queries again ;-)

Personally I think eager loading relations should be considered _part of the retrieval process_ and the event should only be dispatched after...

**Comment by driesvints** [comment]
Can you please fill out the issue template?

**Comment by denjaland** [comment]
@driesvints Not sure what more that you need.  I've raised this as a feature request so I didn't get the template.  Just checked the template now, and all that it seems to be asking is the versions, or am I missing something?

Anyway.
Laravel version 5.8.32
PHP version 7.3
MySQL 5.7

Here is some more information...

This is what is being executed when [fetching models](https://github.com/illuminate/database/blob/341a3743d4dc97c54912dc1623dbebaeb772f70c/Eloquent/Model.php#L412):

```php
public function get($columns = ['*'])
{
    $builder = $this->applyScopes();
    // If we actually found models we will also eager load any relationships that
    // have been specified as needing to be eager loaded, which will solve the
    // n+1 query issue for the developers to avoid running a lot of queries.
    if (count($models = $builder->getModels($columns)) > 0) {
        $models = $builder->eagerLoadRelations($models);
    }
    return $builder->getModel()->newCollection($models);
}
```

If you dive into the `$builder->getModels($columns)` bit, you will see that the models are being instantiated in [this method](https://github.com/illuminate/database/blob/06144d5504b58972f4f1f1ce42bb62ca731ab7cb/Eloquent/Builder.php#L498):

```php
public function newFromBuilder($attributes = [], $connection = null)
    {
        $model = $this->newInstance([], true);
        $model->setRawAttributes((array) $attributes, true);
        $model->setConnection($connection ?: $this->getConnectionName());
        $model->fireModelEvent('retrieved', false);
        return $model;
    }
```

As you can see, the `retrieved` event is being fired here.  However, the eager loading of the events is done *after*.

In an ideal world, the `retrieved` event should only be thrown _after_ the relations have been eager loaded, as you can now not approach any related model in your listener for the `retrieved` event without causing for an N+1 query issue.  Now - for me - the retrieval is still ongoing (it still has to fetch the related models from the database) when the `retrieved` event is being thrown.

Please let me know if you need anything else.

**Comment by driesvints** [comment]
Hey @denjaland if this is a feature request then this needs to be posted on the ideas repo. This repo is only for tracking bugs (see the issue templates). Feel free to post this on the ideas repo.

**Comment by denjaland** [comment]
The question was whether this was a bug.  I'm not even sure this is an idea or a bug.  
Anyway, I'll create a new issue and consider it a bug from my side then.

**Comment by driesvints** [comment]
Hey @denjaland. You said:

> I've raised this as a feature request

So that's why I closed this. Please see our issue templates when posting issue:

![Screen Shot 2019-08-20 at 15 05 50](https://user-images.githubusercontent.com/594614/63349602-07655600-c35c-11e9-8372-0a3cd1e6c16a.png)

**Comment by denjaland** [comment]
no worries.  I'm having a day where procedures seem more important than anything, and no one talks about the content ;)  Your response came at a bad time for me.   I see the reference now to the other repo, but I must have missed that before, so my apologies ;-)

Anyway - I just created #29658 - thanks.

**Comment by driesvints** [comment]
@denjaland no worries man. Sorry if I was a bit crude. There's just a bunch of these issue daily and it's hard to provide enough attention/feedback to all of them. Thanks for opening up a new issue.
