### ISSUE TITLE
page not found error

### ISSUE THREAD

**Issue by jasbin** [laravel/framework#29633]
- Laravel Version: 5.8
-Version: 7.2
![bugLaravel](https://user-images.githubusercontent.com/25180100/63240962-a2353600-c271-11e9-87d7-b14c7a3f4a94.PNG)

### Description:
i was about to search the database images using findOrFail(). it was working when image $id exist, but the problem occoured when the findOrFail() is unable to find the $id and instead of throwing error or exception or any message the view wont even load. it should actually throw some error but it show page 404 not found error.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
