### ISSUE TITLE
laravel 5.5 's Dependency doctrine/lexer 1.1 need php ^ 7.2

### ISSUE THREAD

**Issue by deathkel** [laravel/framework#29634]
- Laravel Version: 5.5.*
- PHP Version: 7.1.3
- Database Driver & Version:

### Description:
composer install fail due to doctrine/lexer 1.1 need php ^ 7.2
same issue happen in lumen 5.8
![image](https://user-images.githubusercontent.com/14328715/63251484-66fe2b80-c2a0-11e9-9e95-ead2c9bc9dce.png)

### Steps To Reproduce:
composer install

**Comment by driesvints** [comment]
I can perfectly install a 5.5 project on PHP 7.1
