### ISSUE TITLE
[5.8] Pivot Model Events - originals are not set

### ISSUE THREAD

**Issue by lorado** [laravel/framework#29636]
- Laravel Version: 5.8.32
- PHP Version: 7.3.1
- Database Driver & Version: PostgreSQL 10.6

### Description:

I have a pivot table with some additional attributes. I also defined a custom intermediate model for this pivot to be able to observe relation changes.

#### Tables example

|consultants|
|---|
id
...

|consultancies|
|---|
id
...

|consultancy_constultant|
|---|
consultancy_id
consultant_id
from
till
job_title

In ConsultancyConsultantObserver `updated` gets fired and executed. I want to store in history log all changes user made. So I simply call `$model->getChanges()` to get changed attributes. It works on regular eloquent models, but on pivot models I receive an object, that only has relation ids (in my case consultancy_id and consultant_id) as original attributes stored. So it is not possible to fetch old attribute values at this point.

I tried to debug it, but I could not catch the point, where it happens - I gave up after 2 hours of trying... 

@ralphschindler you seem to be a relevant contributor to the pivot models stuff. May be you can help me

**UPDATE**: forget to mention. I update pivot values via sync array. Here is a snipped from code

```php
$consultant->consultancies()->sync([
    3 => [
        'from'      => Arr::get($consultancyInput, 'from', null),
        'till'      => Arr::get($consultancyInput, 'till', null),
        'job_title' => Arr::get($consultancyInput, 'job_title', null),
    ]
]);
```

**Comment by bonzai** [comment]
Are you using [`withPivot`](https://laravel.com/docs/5.8/eloquent-relationships#defining-custom-intermediate-table-models) method on your relationship?

> By default, only the model keys will be present on the pivot object. If your pivot table contains extra attributes, you must specify them when defining the relationship:
> ```php
> return $this->belongsToMany('App\Role')->withPivot('column1', 'column2');
> ```

**Comment by staudenmeir** [comment]
Probably related to #28690.

**Comment by lorado** [comment]
> Are you using withPivot method on your relationship?

Oh sorry, yes, here is the definition of consultants in Consultancy model:

```php
    public function consultants(): BelongsToMany
    {
        return $this->belongsToMany('App\Consultant')
                    ->using(ConsultancyConsultant::class)
                    ->withPivot('from', 'till', 'job_title')
                    ->orderBy('consultancy_consultant.from', 'desc');
    }
```

**Comment by driesvints** [comment]
PR was merged
