### ISSUE TITLE
no defined route redirect to /login instead of 404

### ISSUE THREAD

**Issue by BAKTETE** [laravel/framework#29638]
- Laravel Version: 5.8
- PHP Version: 7.3.8
- Database Driver & Version: MySQL v 8.0.17

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by BAKTETE** [comment]
My mistake i have a route defined as the following `Route::get('/{slug}','PostController@show')->name('article.show');`
that's why none existing url redirect to /login page
