### ISSUE TITLE
artisan's make:test command creates some files outside tests/ folder with wrong namespace

### ISSUE THREAD

**Issue by denis-korchagin95** [laravel/framework#29642]
- Laravel Version: 5.8.32 
- PHP Version: 7.2.19

### Description:

When I trying to create some test for my model Tests command behavior is very weird.

After command execution artisan creates the test file not in `tests/Unit` or `tests/Feature`, but in the root folder of the project.

And the test file contains are an empty namespace. It looks like `namespace ;`.

I think it's a hard bug and it needs to be fixed up as soon as possible.

### Steps To Reproduce:

1. Trying to make a test file with name Tests exactly or used it as a prefix by commands:
    `php artisan make:test Tests` or `php artisan make:test Tests --unit` - exactly Tests name
    `php artisan make:test TestsModelTest` or `php artisan make:test TestsModelTest --unit` - used Tests as a prefix

2. You must get the test file in the root folder of the project. It's pretty bad :-(

Here are the demonstration pictures:
![exactly Tests name](https://user-images.githubusercontent.com/36280142/63294040-08ea3c00-c2d2-11e9-83a3-4e538aec19ba.png)
![used Tests as a prefix](https://user-images.githubusercontent.com/36280142/63294041-08ea3c00-c2d2-11e9-9e56-1dc7323a7096.png)
![wrong namespace](https://user-images.githubusercontent.com/36280142/63294186-5b2b5d00-c2d2-11e9-99ef-0e4a0bca93a9.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by denis-korchagin95** [comment]
> Hi there,
> 
> Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:
> 
> * [Laracasts Forums](https://laracasts.com/discuss)
> * [Laravel.io Forums](https://laravel.io/forum)
> * [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
> * [Discord](https://discordapp.com/invite/KxwQuKb)
> * [Larachat](https://larachat.co)
> * [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
> 
> However, this issue will not be locked and everyone is still free to discuss solutions to your problem!
> 
> Thanks.

Hi Dries Vints,

In my opinion its bug of the console system. Besides that, in the project repo, there are no tests related to "make" command for example.

But if you really think what it is no bug then as you wish.

Thanks for your response.
