### ISSUE TITLE
No way to set tries/timeout on Broadcast Events

### ISSUE THREAD

**Issue by iBotPeaches** [laravel/framework#29656]
- Laravel Version: 5.8
- PHP Version: 7.3.x

### Description:
BroadcastEvent does not have the tries/timeout property so they are set to null. Thus run unbounded on the queue. If you want to set the individual tries per broadcast there is no way. An incoming PR should resolve this.

### Steps To Reproduce:
1. Introduce exception in broadcast, with a `$tries = 1` property
2. Using
```
broadcast(new FooBar($user))->toOthers();
```
3. Run queue of broacasts with no limit defined
4. Watch event run over and over

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!

**Comment by iBotPeaches** [comment]
I think it is a bug or at least unintended behavior. If by Laravel design every other "entity" - Notifications, Mailables, and Jobs all support these properties, but Broadcast events don't that seems like a bug - especially since infinite loops and crashes get involved. 

I opened an ideas thread anyway - https://github.com/laravel/ideas/issues/1786
