### ISSUE TITLE
Eloquent emits event retrieved prior to finishing the entire retrieval process of eager loaded relations

### ISSUE THREAD

**Issue by denjaland** [laravel/framework#29658]
- Laravel Version: 5.8.32
- PHP Version: 7.3
- Database Driver & Version: n/a

### Description:

When retrieving models through Eloquent, it emits the `retrieved` event prior to retrieving the eager loaded relations, if any.  

The retrieval of the eager loaded relations are to be considered part of the retrieval process, otherwise you loose the benefit of eager loading anything if you are listening to the `retrieved` event to work with the related items.

### Analysis:

This is what is being executed when [fetching models](https://github.com/illuminate/database/blob/341a3743d4dc97c54912dc1623dbebaeb772f70c/Eloquent/Model.php#L412):

```php
public function get($columns = ['*'])
{
    $builder = $this->applyScopes();
    // If we actually found models we will also eager load any relationships that
    // have been specified as needing to be eager loaded, which will solve the
    // n+1 query issue for the developers to avoid running a lot of queries.
    if (count($models = $builder->getModels($columns)) > 0) {
        $models = $builder->eagerLoadRelations($models);
    }
    return $builder->getModel()->newCollection($models);
}
```

If you dive into the `$builder->getModels($columns)` bit, you will see that the models are being instantiated in [this method](https://github.com/illuminate/database/blob/06144d5504b58972f4f1f1ce42bb62ca731ab7cb/Eloquent/Builder.php#L498):

```php
public function newFromBuilder($attributes = [], $connection = null)
{
    $model = $this->newInstance([], true);
    $model->setRawAttributes((array) $attributes, true);
    $model->setConnection($connection ?: $this->getConnectionName());
    $model->fireModelEvent('retrieved', false);
    return $model;
}
```

As you can see, the `retrieved` event is being fired here.  However, the eager loading of the events is done *after*.

In an ideal world, the `retrieved` event should only be thrown _after_ the relations have been eager loaded, as you can now not approach any related model in your listener for the `retrieved` event without causing for an N+1 query issue.  Now - for me - the retrieval is still ongoing (it still has to fetch the related models from the database) when the `retrieved` event is being thrown.

Please let me know if you need anything else.

**Comment by driesvints** [comment]
Bit torn about this being a bug or a potential improvement. I'll mark this as a bug for now. I don't have time to deep dive into this atm so any help is appreciated.

**Comment by staudenmeir** [comment]
I don't think we should change the current behavior:
- I would argue that it's *technically* correct.
- It would be a significant breaking change.

What if we add a new event that fires *after* the eager loading?

**Comment by denjaland** [comment]
That might be a solution, but will that also work when retrieving ONE model?

**Comment by staudenmeir** [comment]
If we fire the event `Eloquent\Builder::get()`, it will also work for `User::first()`.

**Comment by denjaland** [comment]
Yes but what with find()?

**Comment by denjaland** [comment]
Not sure of the implementation - can’t check as I’m in the car, but does that also pass through the same code there?  The new event should be emitted for each retrieval, hence my question...  And will you emit it also when there are no eager loaded relations?

**Comment by staudenmeir** [comment]
Yes, all these methods are handled by `get()`.

> And will you emit it also when there are no eager loaded relations?

Yes, I think it should always fire.

**Comment by denjaland** [comment]
Then I agree this would definitely a viable solution. 
I don’t understand however why you feel it’s difficult to “move” the current event to after eager loading, but it’s possible for the new event?

Your suggestion would - if I understand correctly - alwayshave the two events shortly after another?  Any use case I’m missing where you would still want to listen to retrieved?

**Comment by staudenmeir** [comment]
> I don’t understand however why you feel it’s difficult to “move” the current event to after eager loading, but it’s possible for the new event?

If we move the `retrieved` event out of `Model::newFromBuilder()`, it breaks other methods relying on it (e.g. `cursor()`).

**Comment by denjaland** [comment]
Okay - that's clear to me.

I think this would be really beneficial to be honest.  Not sure how we could name the event though.  Something like 'eagerloading.completed' sounds tempting, but since the event needs to be emitted even if there are no eager loaded relations, it sounds a bit strange to me.

Again, this is probably a lower prio issue, but especially for an optimistic locking trait where the version is stored in a related model not to clutter the base tables, this would seriously come in handy.

**Comment by staudenmeir** [comment]
Naming is hard...

**Comment by driesvints** [comment]
After reading up a bit I'm gonna shift more to naming this an enhancement. It might indeed be better if we just add a new event. But I believe the better place to discuss this is the ideas repo. So feel free to open up an issue there.
