### ISSUE TITLE
cannot softdelete laravel Notifications

### ISSUE THREAD

**Issue by GMT95** [laravel/framework#29654]

**Comment by GMT95** [comment]
I am using laravel default database notifications, I want to add softdelete to notifications table.

I have created a migration with softdelete which has added deleted_at column to the notifications table. The problem is I have to add 'use SoftDeletes' to notifications model(according to laravel docs) but cannot find the notifications model.

I tried adding 'use SoftDeletes' to HasDatabaseNotifications trait but it still deletes the row.

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!
