### ISSUE TITLE
[6.0] Merge job payloads correctly

### ISSUE THREAD

**Issue by stancl** [laravel/framework#29664]
Originally #29643.

Payloads aren't merged correctly when using queue `createPayloadUsing()` callbacks.

See this example:

```php
class TestJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public function tags()
    {
        return ['abc'];
    }

    // ...
}
```

```php
$this->app['queue']->createPayloadUsing(function ($connection, $queue, $payload) {
    dd($payload);
    return [
        'tags' => [
            'some tag',
        ],
    ];
});
```

The tags will be overwritten by the callback, so they would be `['some tag']`, rather than `['abc', 'some tag']`.

The tags can't be accessed through the `$payload` argument inside the closure, see the output of the `dd()`:

![Screenshot from 2019-08-19 22-30-26](https://user-images.githubusercontent.com/33033094/63297165-0804da80-c2d1-11e9-92d8-8ebbb62b9c82.png)

**Comment by driesvints** [comment]
Did you mean to open this as a PR?

**Comment by stancl** [comment]
@driesvients I didn't. I don't want to resubmit the same branch a different PR. I'm not really sure about the right way to implement this, so I'd prefer to just start a discussion.

**Comment by driesvints** [comment]
@stancl can you fill out the issue template when posting bug reports please?

**Comment by stancl** [comment]
Ok, I'll resubmit this as a 5.8 bug. I'd say it's not exactly a bug nor a feature, though. I just don't want to open an laravel/ideas issue because I'd like to see this in 6.0.
