### ISSUE TITLE
[5.8] Job payloads are not merged correctly

### ISSUE THREAD

**Issue by stancl** [laravel/framework#29665]
- Laravel Version: 5.8.32
- PHP Version: 7.2
- Database Driver & Version: sqlite

### Description:

`createPayloadUsing` overrides payload values with the same key instead of merging them.

### Steps To Reproduce:

```php
// AppServiceProvider
$this->app['queue']->createPayloadUsing(function ($connection, $queue, $payload) {
    return [
        'tags' => [
            'some tag',
        ],
    ];
});
```

```php
class TestJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public function tags()
    {
        return ['abc'];
    }

    // ...
}
```

`$tags` is not part of the `$payload` argument, so it can't be merged there either. Output of `dd($payload)`:
![Screenshot](https://user-images.githubusercontent.com/33033094/63297165-0804da80-c2d1-11e9-92d8-8ebbb62b9c82.png)

`createPayloadUsing` is not really documented, so I can't say if this is a bug report or a feature request. I think fixing this in 6.0 would be ideal.

I originally opened a pull request: #29643

**Comment by stancl** [comment]
My use case for this: I want to add tenant id & domain tags to queues in Horizon, but I don't want to override the jobs' tags.

**Comment by themsaid** [comment]
Closing since https://github.com/laravel/framework/pull/29643 is closed. You have the $payload already you can merge the new value into it if you want.

**Comment by stancl** [comment]
@themsaid Look at the original comment in this thread. The callback can be executed before the payload is in $payload, so you have no way of merging it.

**Comment by themsaid** [comment]
@stancl The callbacks are executed after the payload is created, can you share some code?

**Comment by stancl** [comment]
@themsaid Can you look at the steps to reproduce (with the job tags) in my original comment?

I can make a repo later when I'm on my computer if that would help.

**Comment by themsaid** [comment]
Where do you put the tags in the payload in the first place?

**Comment by stancl** [comment]
@themsaid What do you mean where?

Anyway, my use case for this is to merge tags from my package (`tenant_id`, for example) with the job's original tags so that in Horizon, you'd see both your tags and the tenant's id. However setting the `tenant_id` tag using the callback overrides the job's original tags, so I can't do that.

**Comment by stancl** [comment]
@themsaid Please look at the steps to reproduce in my original comment.
