### ISSUE TITLE
Escape namespace for morphedByMany-relationship

### ISSUE THREAD

**Issue by Fuitad** [laravel/framework#29676]
- Laravel Version: 5.8.32
- PHP Version: 7.3.8
- Database Driver & Version: 5.7.27

### Description:

I'm having the very same issue as #16302 (which was closed without resolution). 

i.e. the SQL query generated by morphedByMany does not return any data because the _type column value is not properly escaped. When I run the same query manually, escaping the namespace correctly, then I can get data.

Laravel query: 

> select `materials`.*, `enemy_drops`.`enemy_id` as `pivot_enemy_id`, `enemy_drops`.`enemy_drop_id` as `pivot_enemy_drop_id`, `enemy_drops`.`enemy_drop_type` as `pivot_enemy_drop_type` from `materials` inner join `enemy_drops` on `materials`.`id` = `enemy_drops`.`enemy_drop_id` where `enemy_drops`.`enemy_id` in (310100101024, 310100101025) and `enemy_drops`.`enemy_drop_type` = 'App\Models\AE\Material'

returns nothing

Manual query:

> select `materials`.*, `enemy_drops`.`enemy_id` as `pivot_enemy_id`, `enemy_drops`.`enemy_drop_id` as `pivot_enemy_drop_id`, `enemy_drops`.`enemy_drop_type` as `pivot_enemy_drop_type` from `materials` inner join `enemy_drops` on `materials`.`id` = `enemy_drops`.`enemy_drop_id` where `enemy_drops`.`enemy_id` in (310100101024, 310100101025) and `enemy_drops`.`enemy_drop_type` = 'App\\\Models\\\AE\\\Material'

returns 4-5 rows.

**Comment by ankurk91** [comment]
You can use morph map 
https://josephsilber.com/posts/2018/07/02/eloquent-polymorphic-relations-morph-map

**Comment by staudenmeir** [comment]
The "Laravel query" you posted is not the exact query that actually gets executed. I suspect the 64-bit integers to be the cause for the empty result.

Please post both models, all three migrations and the eager loading query.

**Comment by Fuitad** [comment]
> The "Laravel query" you posted is not the exact query that actually gets executed. I suspect the 64-bit integers to be the cause for the empty result.
> 
> Please post both models, all three migrations and the eager loading query.

I can confirm to you that the big integer is NOT the issue. I've already isolated that part.

**Comment by Fuitad** [comment]
> You can use morph map
> https://josephsilber.com/posts/2018/07/02/eloquent-polymorphic-relations-morph-map

This works, thanks! However, I still think the behavior of morphedByMany is a bug in this case. I'd like to get an opinion from the devs.

**Comment by staudenmeir** [comment]
> I can confirm to you that the big integer is NOT the issue. I've already isolated that part.

How did you test that?

> However, I still think the behavior of morphedByMany is a bug in this case.

The class name not being escaped is *not* a bug. It's passed as a binding and doesn't need to be escaped.

What result do you get from running the "manual query" in Laravel?

```php
dd(DB::select("select `materials.*` ..."));
```

**Comment by staudenmeir** [comment]
Did you solve the issue?

**Comment by Fuitad** [comment]
> Did you solve the issue?

I did not. However, @ankurk91 suggestion is a working alternative and I don't have the time to fight with you about how I tested the bug before I reported it.

**Comment by staudenmeir** [comment]
I was trying to help find the cause of the issue. The 64-bit integers were the only thing standing out from an otherwise standard eager loading query that works for everyone else.

If you provide a reproducible example, I look into it.

**Comment by sRaH** [comment]
I'm experiencing the same issue 

select `projects`.*, `server_services_nginx_pools_domains`.`domain_id` as `pivot_domain_id`, `server_services_nginx_pools_domains`.`assignable_id` as `pivot_assignable_id`, `server_services_nginx_pools_domains`.`assignable_type` as `pivot_assignable_type` from `projects` inner join `server_services_nginx_pools_domains` on `projects`.`id` = `server_services_nginx_pools_domains`.`assignable_id` where `server_services_nginx_pools_domains`.`domain_id` = 719 and `server_services_nginx_pools_domains`.`assignable_type` = 'App\Models\Project' and `projects`.`deleted_at` is null order by `projects`.`id` desc limit 6 offset 0

.`assignable_type` = `'App\Models\Project'` does not get escaped so the MySQL can't match it must be .`assignable_type` = `'App\\Models\\Project'` according to MySQL Syntax.

@ankurk91 Solution works. But the documentation says I can use the morphedByMany without using morphMap at all.

**Comment by Cyrille37** [comment]
Some news in #16302 at https://github.com/laravel/framework/issues/16302#issuecomment-1880107321
