### ISSUE TITLE
Request helpers doesn't update data on tests

### ISSUE THREAD

**Issue by AbdelkaderBah** [laravel/framework#29673]
- Laravel Version: 5.7
- PHP Version: 7.3
- Database Driver & Version: MYSQL

### Description: ```request()``` helper has different result than ```$request```.
I'm not sure this is a bug, Maybe my way of running tests is wrong.

### Steps To Reproduce:
1- Create a web route and use within it ```request()```
2- Create two Test classes: FooTest, BarTest
3-1º) Add a function to ```FooTest``` test_do_1 with ```$this->post('route.1')```
3-2º) Add a function to ```BarTest``` test_do_2  with ```$this->post('route.2')```
4- run ```FooTest::test_do_1``` inside ```BarTest::test_do_2```

@example: 

```
//Class FooTest
public function test_do_1()
{
   $this->post('route.1', ['abc' => 123]);
} 

//class BarTest
public function setUp()
{
     parent::setUp();
     $foo = new FooTest;
     $foo->setUp();
     $foo->test_do_1();
}

public function test_do_2()
{
   $this->post('route.2', ['klm', 678]);
} 


//web.php
Route::get('1', function(){
    //result: ['abc' => 123]
    request()->all();
})->name('route.1');

Route::get('2', function(Request $request){
    //Result ['abc' => 123] instead of ['klm', 678]
    request()->all();

   //Result ['klm', 678]
  $request->all();
})->name('route.2');
```

Trying this method gives a different kind of errors like ```$this->be($user)``` doesn't work...

**Comment by laurencei** [comment]
This is expected behavior. You can only call a route once per test. 

In `test_do_2` you should preset the database to have the results of `test_do_1` and then test the single function from there.

**Comment by AbdelkaderBah** [comment]
```This is expected behavior.```
@laurencei why there is no mention on Laravel documentation ???

**Comment by laurencei** [comment]
Not sure. Feel free to submit a PR with your suggestion to make it
more obvious for everyone. Thanks.
