### ISSUE TITLE
Env 

### ISSUE THREAD

**Issue by EM-LilianaIturribarria** [laravel/framework#29677]
- Laravel Version: 5.8.31
- PHP Version: 7.1.23
- Database Driver & Version: mysql / 10.1.36-MariaDB

### Description:

- I'm not able to use env('X_ENV_VAR') on migrations, now i have to use config('FILE_X_ENV_VAR')

- I cannot longer use --env=testing to run my migrations and seeds

### Steps To Reproduce:

- For the first error, on my migrations you can:
.env
DATABASE_NAME=mydatabase

$databaseName = env('DATABASE_NAME');
dd($databaseName); <<< returns null

- For the second error...
running on terminal:
php artisan migrate:reset --env=testing
php artisan migrate --seed --env=testing

both are migrating and seeding my default database

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
