### ISSUE TITLE
'Illuminate\Contracts\Redis\Connector' not found

### ISSUE THREAD

**Issue by ehsanalizad** [laravel/framework#29683]
Hi,

After `composer update` I'm getting this error when I use `php artisan cache:clear` but Laravel is working ...

```
 Symfony\Component\Debug\Exception\FatalErrorException  : Interface 'Illuminate\Contracts\Redis\Connector' not found

  at /var/www/wmp/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PredisConnector.php:11
     7| use Illuminate\Contracts\Redis\Connector;
     8| use Illuminate\Redis\Connections\PredisConnection;
     9| use Illuminate\Redis\Connections\PredisClusterConnection;
    10| 
  > 11| class PredisConnector implements Connector
    12| {
    13|     /**
    14|      * Create a new clustered Predis connection.
    15|      *


   Whoops\Exception\ErrorException  : Interface 'Illuminate\Contracts\Redis\Connector' not found

  at /var/www/wmp/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PredisConnector.php:11
     7| use Illuminate\Contracts\Redis\Connector;
     8| use Illuminate\Redis\Connections\PredisConnection;
     9| use Illuminate\Redis\Connections\PredisClusterConnection;
    10| 
  > 11| class PredisConnector implements Connector
    12| {
    13|     /**
    14|      * Create a new clustered Predis connection.
    15|      *

  Exception trace:

  1   Whoops\Run::handleError("Interface 'Illuminate\Contracts\Redis\Connector' not found", "/var/www/wmp/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PredisConnector.php")
      /var/www/wmp/vendor/filp/whoops/src/Whoops/Run.php:433

  2   Whoops\Run::handleShutdown()
      [internal]:0
```

PHP: 7.3
Laravel: 5.8

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
