### ISSUE TITLE
Illuminate\Support\Collection@chunk() method forces keys to be preserved

### ISSUE THREAD

**Issue by andrew-sologor** [laravel/framework#29685]
Related issues: #19182, #19958, #19217 

I have no idea why there is still no second param.

My case:
```php
$items = collect([1, 2, 3, 4]);
$pairs = $items->chunk(2);

[$first, $second] = $pairs[0]; // ok
[$first, $second] = $pairs[1]; // throws "Undefined offset: 0"
```

You changed the default `array_chunk` function behavior and didn't give people any options.

**Comment by driesvints** [comment]
If you send in a new PR to the master branch with proper tests and a thorough explanation it could be reconsidered. Otherwise this is a feature request and not a bug and should be opened in the ideas repo instead.

**Comment by erdemkeren** [comment]
I came here with the same idea. The weird thing is that `array_chunk`'s default for is `$preserve_keys` variable is `false` while laravel's is `true`.

I will try to find time and create the PR.
