### ISSUE TITLE
Laravel Model Macroble Mixins

### ISSUE THREAD

**Issue by yu0307** [laravel/framework#29682]
Hi guys,Can we mixin some features into an eloquent model class?

Let's assume the following setup:

mixin class file T:
```
class T{
	public function relations(){
		return function () {
			return $this->morphToMany('users', 'target');
                }
        }

	public function myUsers(){
		return function () {
			return $this->relations->first();
		}
	}
}
```

Model A:
```
class A extends Model{

}
```

some Class:
```
class someClass{

	public function test(){
		A::mixin(new T);
		A::first()->myUsers();
	}
}
```

## Issue: 
when using A::first()->myUsers(), why is $this->relations return error saying "relations" is not defined on Builder class? 

## Note1:
When mixin features on an eloquent class, it is being applied on a queryBuilder instead of model class. 
## Note2:
It seems like the issue is when class T is "mixedIn", $this became Illuminate\Database\Query\Builder, which cannot access model resources. like, if I use $this->relations(), it will return saying morphToMany not found from Builder. So, i guess my extended question is, How can we MixIn methods into a model class.

Thanks a lot guys

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!
