### ISSUE TITLE
Eloquent whereIn doesn't work with Dynamic Scopes on NULL

### ISSUE THREAD

**Issue by jadamec** [laravel/framework#29690]
- Laravel Version: 5.8.33
- PHP Version: 7.3.5

### Description:
`$posts = Auth::user()->posts()->filter($request->except('_token'))->get();
`

This works in Controller, `query.bank` contains values NULL, 1, 2, 3. Posts of which _bank_ is NULL **are returned**.
```
if ($request->has('query.bank')) {
    $posts = $posts->whereIn('bank', $request['query']['bank']);
}
```

This doesn't work in Post model as a Dynamic Scope, posts of which _bank_ is NULL **are not returned**.
```
public function scopeFilter($query, $params) {
    if (request('query.bank', false)) {
        $query->whereIn('bank', request('query.bank'));
    }
    return $query;
}
```

**Comment by staudenmeir** [comment]
Please log the executed queries.

**Comment by jadamec** [comment]
Looks absolutelly the same. 

In Controller:
`select * from `posts` inner join `post_user` on `posts`.`id` = `post_user`.`post_id` where `post_user`.`user_id` = ? and `bank` in (?, ?)`

In Model:
`select * from `posts` inner join `post_user` on `posts`.`id` = `post_user`.`post_id` where `post_user`.`user_id` = ? and `bank` in (?, ?)`

**Comment by jadamec** [comment]
This also doesn't work in Post model as a Dynamic Scope
```
 $query->when(request('query.bank', []), function ($query, $params) {
    return $query->whereIn('bank', $params);
});
```

**Comment by staudenmeir** [comment]
Neither of these queries can work. SQL doesn't support `null` values in `WHERE IN` clauses.

You need to add `->orWhereNull('bank')` when `$params` contains `null`.

**Comment by jadamec** [comment]
So why the first one works..? :) From Controller it shows me also results with nullabne _bank_ key.

What's more, I cannot use `orWhereNull` because of multiple `when` clauses.

**Comment by staudenmeir** [comment]
> So why the first one works..?

I don't see how the query could possibly work.

> What's more, I cannot use orWhereNull because of multiple when clauses.

https://laravel.com/docs/queries#parameter-grouping

**Comment by jadamec** [comment]
> > What's more, I cannot use orWhereNull because of multiple when clauses.
> 
> https://laravel.com/docs/queries#parameter-grouping

Ok, now done like this:
```
$query->when(request('query.bank'), function ($query, $params) {
    return $query->where(function ($query) use ($params) {
        $query->whereIn('bank', $params);

        if (in_array(null, $params)) {
            $query->orWhereNull('bank');
        }
    });
});
```

Probably can be closed, not a bug.. just my misunderstanding of principles.
