### ISSUE TITLE
laravel 5.8 Installation failed full vendor could not be loaded 

### ISSUE THREAD

**Issue by NILOYDEVNATH** [laravel/framework#29706]
- Laravel Version: 5.8
- PHP Version: 7.2
- Database Driver & Version: mysql

### Description:
when try to install laravel 5.8 then show 
Uncaught Error: Class 'Symfony\Component\Console\Input\ArgvInput'
and i am check my vendor filed Symfony\Component folder is fully missing .

**Comment by aanfarhan** [comment]
What are the steps to reproduce this issue? What method are you using when you install the framework?

**Comment by NILOYDEVNATH** [comment]
I copy my vendor from another project and it works fine

**Comment by NILOYDEVNATH** [comment]
when i create a new project using composer create-project --prefer-dist laravel/laravel project_name composer failed to get Symfony\Component\Console\Input\ArgvInput,
Symfony\Component\Console\Output\ConsoleOutput and under vendor there are no folder in Following path

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
