### ISSUE TITLE
[Eloquent] lastInsertId() is wrong on char column

### ISSUE THREAD

**Issue by SergeyPodgornyy** [laravel/framework#29701]
- Laravel Version: _5.8.29 (but is version-independent)_
- PHP Version: _7.3.7 (but is version-independent)_
- Database Driver & Version: _MySQL 8.0.16_

### Description:

Last inserted ID returns always `"0"`. According to the [PDO official documentation](https://www.php.net/manual/ru/pdo.lastinsertid.php) this could happen when asking for `lastInsertId()` after commit was done in a transaction, but I am not using the transaction for this single insert :thinking:

### Steps To Reproduce:

Migration:

```php
Schema::create('countries', function (Blueprint $table) {
    $table->uuid('id')->primary()->default(new Expression('(UUID())'));
    $table->string('name');
    $table->timestampTz('created_at')->useCurrent();
    $table->timestampTz('updated_at')->default(\DB::raw('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'));
});
```

Model:

```php
class Country extends Model
{
    protected $table = 'countries';

    protected $keyType = 'string';

    public $incrementing = true;

    // ...
}
```

Adding new entry:

```php
$country = new Country();
$country->name = 'Germany';
$country->save();
```

Expected output of `$country->id` is some UUID generated by MySQL (f.e. `5daa634c-b174-11e9-8056-0242c0a89007`), but instead I am getting `"0"`, what is wrong.

**Comment by staudenmeir** [comment]
This is a limitation of MySQL and/or the database driver and not caused by Laravel.

MySQL has only been allowing expressions as default values since 8.0.13 and it looks like there's currently no way to get the generated UUID.

**Comment by SergeyPodgornyy** [comment]
@staudenmeir Laravel migration using `$table->uuid('id')` create a `CHAR` column

**Comment by staudenmeir** [comment]
I don't understand how this is related to the issue.

**Comment by SergeyPodgornyy** [comment]
Hmm :thinking: you are right, just tested it with raw SQL commands and it returns `"0"`:

```sql
mysql> INSERT INTO countries (name) VALUES ('Germany');
Query OK, 1 row affected (0,04 sec)

mysql> SELECT LAST_INSERT_ID();
+------------------+
| LAST_INSERT_ID() |
+------------------+
|                0 |
+------------------+
1 row in set (0,00 sec)

```

Anyway, it was a bit confusing for me, as according to PDO documentation `"0"` should be returned only when LAST_INSERT_ID() was asked after a transaction. Maybe it would be nice to add to the Laravel documentation, that there is no chance to manipulate Eloquent Model to achieve this result? :thinking: 

Anyway, this issue could be closed. :heavy_check_mark:  Thanks for helping me to figure it out.
