### ISSUE TITLE
Factory State not functioning when calling another factory in state

### ISSUE THREAD

**Issue by yihyang** [laravel/framework#29709]
- Laravel Version: 5.8.17
- PHP Version: 7.2
- Database Driver & Version:
MySQL 5.7.27

### Description:
When a factory contains states and the states refer to the relationship class more than once. The factory is unable to create a class instance and the following error occured:

```
PHP Warning:  opendir(/home/vagrant/code/database/factories): failed to open dir: Too many open files in /home/vagrant/code/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php on line 129
```

However when I changes the states to use closure instead of using object for  the last parameters then it worked.

### Steps To Reproduce:

The following block will cause the error message as mentioned as it's using `object` for the last parameter.

```
<?php

/* @var $factory \Illuminate\Database\Eloquent\Factory */

use App\Model;
use Faker\Generator as Faker;

$factory->define(User::class, function (Faker $faker) {
    return [
        'name' => 'John Doe',
        'country_id' => factory(Country::class)->create()->id,
    ];
});

$factory->state(User::class, 'ben', [
        'name' => 'Ben',
        'country_id' => factory(Country::class)->state('usa')->create()->id,
]);
/
```

However the following block worked because I have used closure instead of object.

```
<?php

/* @var $factory \Illuminate\Database\Eloquent\Factory */

use App\Model;
use Faker\Generator as Faker;

$factory->define(User::class, function (Faker $faker) {
    return [
        'name' => 'John Doe',
        'country_id' => factory(Country::class)->create()->id,
    ];
});

$factory->state(User::class, 'ben', function($faker) {
    return [
        'name' => 'Ben',
        'country_id' => factory(Country::class)->state('usa')->create()->id,
    ];
});
```

Thanks for looking into it.

**Comment by staudenmeir** [comment]
You need to use a closure. If you use an array, the country is already created when the factory is defined – before even creating a user. This causes an endless recursion.

**Comment by yihyang** [comment]
I see, thanks for your explanation @staudenmeir . However I'm wondering is this documented somewhere in the documentations? If not can I help to add it in? Thanks

**Comment by staudenmeir** [comment]
I don't think it is. You can submit a PR to https://github.com/laravel/docs.

**Comment by yihyang** [comment]
Thanks @staudenmeir I have submitted a PR here: https://github.com/laravel/docs/pull/5396
