### ISSUE TITLE
Strict issue for isDateAttribute check

### ISSUE THREAD

**Issue by yoramdelangen** [laravel/framework#29702]
- Laravel Version: 5.8.*
- PHP Version: 7.2.12
- Database Driver & Version: MySQL 5.7.20

### Description:
The method `isDateAttribute` of trait `HasAttributes` is checking if the given key is within the array of the dates property. Because the in_array check is not strict it will allows numeric values and returns true and when the value was an array it will cause a crash. This is mainly caused (in my experience) via the Spatie Translatable package when it checks if the property key `isTranslableAttribute(...)`.

In cases when the numeric matches an index of the `$this->getDates()` array, it will return true and it continues to heck the format. When the value is an array (in fake, translatable array's from Laravel Backpack and Spatie Translatables) it will cause an ErrorException.

### Steps To Reproduce:
Easiest to reproduce is too call the `setAttribute` on a model with the dates property set (only created and updated_at are enough):
```php
$model->setAttribute(0, ['a', 'random', 'array']);
```
It will hit the `elseif` part of the method which checks if the key was a `date` property. It will try the validate the given format but it will crash with an error: `preg_match() expects parameter 2 to be string, array given`.

### Proposition to fix:
Change the method `isDateAttribute` to check strictly:
```php
protected function isDateAttribute($key)
{
    return in_array($key, $this->getDates(), true) || $this->isDateCastable($key);
}
```

**Comment by driesvints** [comment]
PR was merged
