### ISSUE TITLE
Urgent! ATTR_EMULATE_PREPARES Problem! Save float lose decimal!

### ISSUE THREAD

**Issue by MrJmpl3** [laravel/framework#29713]
- Laravel Version: 5.8.33
- PHP Version: 7.3.8
- Database Driver & Version: MariaDB

### Description:

Two problem!

- If ATTR_EMULATE_PREPARES = true , when you save a float number , lose the decimal value
- If ATTR_EMULATE_PREPARES = false, you have the error "Prepared statement needs to be re-prepared MySQL"

I look related issues , but was closed without solution.

Like: https://github.com/laravel/framework/issues/23850

**Comment by aanfarhan** [comment]
Did you try to cast your float value into string? I looked up into this function https://github.com/laravel/framework/blob/c7acf0690385b026552ed28122509923c2b017df/src/Illuminate/Database/MySqlConnection.php#L75-L84

There are two check `is_int` or `is_float`, which is return `PDO::PARAM_INT` that make your value being saved into Integer value and lose those decimal.

**Comment by MrJmpl3** [comment]
I go to update the table_definition_cache of the Database to 2048. In somes day, i will return with the results

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
