### ISSUE TITLE
is there any security problem in FileSystem folder files?

### ISSUE THREAD

**Issue by MetaiR** [laravel/framework#29718]
I don't know this is a bug, just warning or a real security problem so I post it here and want a support help:

recently we had deploied a laravel project on a shared cpanel host (we aware of down side of this so please dont mantion u shouldn't do it and etc) and their antivirus system removes `laravel/framework/src/Illuminate/Filesystem/Filesystem.php` and when we contacted with the support they told us the file is suspicious for their security system; and they also told that they can remove it from quarantine if we accept the risk; so my question is:
is there any problem with this file or the files in this directory (`laravel/framework/src/Illuminate/Filesystem`) or we can accept the risk?

ps: we use last version of laravel

**Comment by rimace** [comment]
I guess nobody can tell you if you can accept the risk, but I have some tips that may help you.
Sometimes malware appends malicious code to php files that will be executed when the file is required. So you could check if the file you deployed is the same as the one you [find here](https://github.com/laravel/framework/blob/5.8/src/Illuminate/Filesystem/Filesystem.php) on github.
Another way to find out is to ask what exactly is suspicious about the file and what risk does it have.

**Comment by rs-sliske** [comment]
i would suggest finding out what they thought the issue was.

file uploads in general are a potential security issue

**Comment by MetaiR** [comment]
could u please tell me what are these file doing anyway? I mean the fies in FileSystem folder

**Comment by mfn** [comment]
> i would suggest finding out what they thought the issue was.

This. If you want assistance here, publish the problem reported with this file.

Only then it can be judged.

**Comment by rs-sliske** [comment]
> 
> 
> could u please tell me what are these file doing anyway? I mean the fies in FileSystem folder

you have access to all the code. in general though the answer should be fairly obvious imo, reading and writing files

**Comment by MetaiR** [comment]
@mfn
I sent a ticket to them and will publish their answer as soon as possible

**Comment by MetaiR** [comment]
they told me; they don't have the logs, but it looks like that I can ask them to change their rules for these files on my user, so if u think these files are almost safe and nothing to worry about (I don't mean about the code that we are writing which may cause a security bug, but I mean the file itself) we are good to go

**Comment by laurencei** [comment]
There are no none security issues with the FileSystem.

If you have a known issue, please review the security policy on how to notify of an issue: https://github.com/laravel/framework/security/policy
