### ISSUE TITLE
Race Condition: dispatch() saves uncommitted models to async queue

### ISSUE THREAD

**Issue by 4n70w4** [laravel/framework#29710]
- Laravel Version: 5.8.33
- PHP Version: 7.3.8
- Database Driver & Version: mysql

### Description:

Job handler (horizon for example) throws ModelNotFoundException.
Because serialized models was recently created in parallel process but still don't commited (it's not about rollback).

### Steps To Reproduce:

Create listener for `saved` (or another) model event with:

```php
dispatch(new SomeJob($UncommitedModel) );
```

I see the simplest solution - `dispatch()` should throw an exception if the models are not commited.

Also implement something like `dispatch_on_commit()` which will dispatch only after a successful commit of the models necessary for serializing the job.

See also: https://github.com/laravel/ideas/issues/1441

**Comment by mfn** [comment]
It's just a coincidence, but I updated it with a comment about a package which supports "transactional events", please see https://github.com/laravel/ideas/issues/1441#issuecomment-524582224

Here's btw an older issue talking about this problem: https://github.com/laravel/framework/issues/8627 (there are likely more)

**Comment by driesvints** [comment]
I think it's best that we stick this with the ideas issue. Feel free to submit a pr if you think this can be improved.

**Comment by mfn** [comment]
Hello everyone,

based on an existing package and with permission of its original author, I've drafted a possible solution to tackle the "transactional events" problem.

At the moment it's a draft PR in my Laravel forked repo to first gather feedback from the community before approaching to create an official PR, to give things time to unfold / develop.

I invite everyone to participate in https://github.com/mfn/laravel-framework/pull/1 and share your feedback.

Thank you!
