### ISSUE TITLE
Slack notification not working

### ISSUE THREAD

**Issue by never-potm** [laravel/framework#29717]
- Laravel Version: 5.8.28
- PHP Version: 7.2.21
- Database Driver & Version:

### Description:
Slack notifications not getting sent to any channel. I have used Notification to send the Slack notification. 

```
$user->notify(new SlackNotificationSuccess());
```
The above method is not sending the slack notification. I have tried clearing cache still it does not work.

### Steps To Reproduce:
1. Make a notification class
2. Create the config for slack webhook and attach it in config file
3. Use the above method to send notification

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
