### ISSUE TITLE
Carbon::setTestNow() producing flaky tests.

### ISSUE THREAD

**Issue by ellisio** [laravel/framework#29711]
- Laravel Version: 5.8.33
- PHP Version: 7.3.7
- Database Driver & Version: sqlite (unit testing)

### Description:

When running unit tests, Carbon randomly fails unit tests due to timestamps being 1 second apart.

For example, here is an assertion of a failed test:

```
1) Tests\Feature\Http\Contacts\CreateControllerTest::testContactIsCreated
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'{"account_id":1,"created_at":1566588448,"updated_at":1566588448}'
+'{"account_id":1,"created_at":1566588447,"updated_at":1566588447}'
```

### Steps To Reproduce:

1. Create a test using the following:

```
public function testContactIsCreated()
{
    $number = '+15551234567';
    $name = $this->faker->name;
    $email = $this->faker->email;

    $user = factory(User::class)->create();

    $response = $this->actingAs($user)->post('contacts', [
        'number' => $number,
        'name' => $name,
        'email' => $email,
    ]);

    $response->assertStatus(201);
    $response->assertExactJson([
        'account_id' => $user->account_id,
        'created_at' => Carbon::now()->timestamp,
        'updated_at' => Carbon::now()->timestamp,
    ]);
}
```

2. Rune the test using `vendor/bin/phpunit`.

Note: This is a flaky situation. This test may pass, it may not. However, I was under the assumption [this line](https://github.com/laravel/framework/blob/5.8/src/Illuminate/Foundation/Testing/TestCase.php#L180) took care of forcing Carbon to use fake times.

**Comment by JayBizzle** [comment]
Where in your test are you setting the current 'fake' time?

Something like this?

```php
$knownDate = Carbon::create(2001, 5, 21, 12);
Carbon::setTestNow($knownDate);
```

The line you linked to just resets any 'fake' times you have set after your tests have run.

**Comment by ellisio** [comment]
@JayBizzle son of a... I just realized that is in the `tearDown()` method. Sigh. Thank you :)
