### ISSUE TITLE
Why deprecate Predis?

### ISSUE THREAD

**Issue by thecodingdude** [laravel/framework#29722]
[In a recent commit](https://github.com/laravel/framework/commit/a8228dc3a42cfdba5efc499bb3d1a35b897f2e2d) Predis was deprecated.

Yet over [here](https://github.com/phpredis/phpredis) it's still being maintained.

Why deprecate?

**Comment by rs-sliske** [comment]
im not 100% sure, but i think predis and phpredis arent the same thing.

from the discussion on the pr it looks like predis was deprecated in favor of phpredis

**Comment by RFreij** [comment]
https://packagist.org/packages/predis/predis this one is no longer maintained. Phpredis is a different one

**Comment by rimace** [comment]
The discussion about that can be found here: https://github.com/laravel/ideas/issues/1779
Predis is not PHPredis. Apperently Predis is not longer maintained for 3 years now and it is already buggy with PHP 7.3.
