### ISSUE TITLE
redirect()->route() does not work well with query-string parameters and optional route parameters

### ISSUE THREAD

**Issue by nihilsen** [laravel/framework#29736]
- Laravel Version: 5.8.27
- PHP Version: 7.3.7
- Database Driver & Version: MySQL 5.7.27

### Description:
`redirect()->route()` does not work as expected when used with a route that has an optional route parameter when trying to pass query-string parameters in the `$parameters` argument.

### Steps To Reproduce:
**routes/web.php** : 

    Route::get('/profiles/{location?}', function () {
        dd('Reached the Profiles route');
    })->name('profiles.index');
    
    Route::get('/', function () {
        return redirect()->route('profiles.index', ['status' => ['single', 'married']]);
    });

### Expected behavior
The intention is that accessing **/** should redirect to **/profiles/?status[]=single&status[]=married**.

### Actual behavior
Results in _Array to string conversion ErrorException_

The reason is that `replaceRouteParameters()` in vendor/laravel/framework/src/Illuminate/Routing/RouteUrlGenerator.php uses `array_shift` to get the first element (which in this example is an array) from the `$parameters` argument and tries to insert that as a string to replace the `{location?}` parameter even though it's optional

I initially submitted this as a pull-request #29692 because it says in the [Contribution Guide](https://laravel.com/docs/5.8/contributions#bug-reports) that pull requests are __strongly encouraged__ instead of just bug reports. In the pull-request I demonstrate one approach I used which substitutes `array_shift($parameters)` with `Arr::pull($parameters, 0)` to only use non-associative elements of `$parameters` for route-parameter substitution, but I don't know if this is the optimal approach.

Another workaround was to explicitly set an empty 'location' parameter when using `redirect()->route()`. For example, the following would have worked:

    return redirect()->route('profiles.index', ['status' => ['single', 'married'], 'location' => '']);

It appears the same bug was referenced in an issue from 2015 #7881

**Comment by driesvints** [comment]
Hey @nihilsen. Thanks for reporting. I definitely agree with you that this appears to be a bug. I think the PR was closed because it lacked tests that validates the correct behavior. If you re-send it with tests then it probably can be merged. Thanks!

**Comment by nihilsen** [comment]
Hi @driesvints. I've resubmitted the PR here #29749 with tests like you suggested.

**Comment by nihilsen** [comment]
Fixed in 6.0 with merged PR #29778
