### ISSUE TITLE
I have a question, is it because of the consideration of not providing a way to remove a service that has already been registered?

### ISSUE THREAD

**Issue by CreatNameHard** [laravel/framework#29737]
#I have a question, is it because of the consideration of not providing a way to remove a service that has already been registered? Isn't this method more flexible? Let me give you an example. I want to replace the log management of laravel5.5 with the components I developed. I can only register my own LOG service in bootstarp/app.php, or is there a better implementation?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
