### ISSUE TITLE
orWherePivot issue

### ISSUE THREAD

**Issue by zeyad82** [laravel/framework#29741]
- Laravel Version: 5.8

### Description:
I am trying to use orWherePivot on a BelongsToMany relationship. When I use it per user, it cancels the filtration of user_id and it's applied to the global query so it returns all the records instead of only per user, when I try to enclose it in where closure scope, it throws  `Call to undefined method Illuminate\Database\Eloquent\Builder::orWherePivot()
` which makes it also applied to the global query.

Is that a normal behavior? How can I use it only per user scope?

### Steps To Reproduce:
The following returns all records not only per user
`
$user->BelongsToMany()
        ->wherePivot('pivot', 0)
        ->orWherePivot('another', 0)->get()
`

And the following throws the mentioned error
`
$user->BelongsToMany()
         ->where(function($query) {
             $query->wherePivot('pivot', 0)
              ->orWherePivot('another', 0);
         })->get()
`

**Comment by driesvints** [comment]
@staudenmeir do you know of any changes to this method?

**Comment by staudenmeir** [comment]
`orWherePivot()` has been around since 2013, but it looks like there has never been an actual use case. There aren't any tests either.

I'll take a look if we can make it work with closures.

You can use the "normal" `where()` methods as a workaround for `SELECT` queries:

```php
$user->BelongsToMany()->where(function ($query) {
    $query->where('pivot_table.pivot', 0)->orWhere('pivot_table.another', 0);
})->get()
```

The downside here is that `detach()`, `sync()` etc. don't respect these pivot constraints (as they do with `wherePivot()`).

**Comment by zeyad82** [comment]
I managed to use orWherePivot by adding the user_id manually:

> `$user->BelongsToMany()->wherePivot('pivot', 0)
        ->orWherePivot('another', 0)
        ->where('user_id', $user->id)->get()
`

**Comment by staudenmeir** [comment]
I don't see a feasible way to make closures work.

**Comment by driesvints** [comment]
Probably a no fix, sorry.
