### ISSUE TITLE
QueueFake size method returns wrong value

### ISSUE THREAD

**Issue by hlorofos** [laravel/framework#29755]
- Laravel Version: 5.8.33
- PHP Version: 7.1.25
- Database Driver & Version: n/a

### Description:

QueueFake size returns wrong value

### Steps To Reproduce:

- Install Laravel by any means
- make a new job by running `php artisan make:job TestJob`
- make a new test by running `php artisan make:test QueueSizeTest`
- copy the following test method:

```
   public function testQueueSize()
    {
        \Queue::fake();

    	$job = new TestJob();
	
        dispatch($job);
        dispatch($job);
        dispatch($job)->onQueue('Q2');

        $this->assertEquals(2, \Queue::size());
        $this->assertEquals(1, \Queue::size('Q2'));
    }
```

- run the test, it would fail

The flaw is in QueueFake' `size` method:

```
    /**
     * Get the size of the queue.
     *
     * @param  string|null  $queue
     * @return int
     */
    public function size($queue = null)
    {
        return count($this->jobs);
    }
```

- it doesn't use $queue parameter at all and it improperly calculates amount of jobs, since
jobs array is associative array, refer to `push` method:

```
public function push($job, $data = '', $queue = null)
    {
        $this->jobs[is_object($job) ? get_class($job) : $job][] = [
            'job' => $job,
            'queue' => $queue,
        ];
    }
```

**Comment by driesvints** [comment]
This indeed appears to be a bug. Thanks for reporting. Appreciating a PR if you could whip one up.

**Comment by mfn** [comment]
I can't believe how lazy I am, I forgot that I was using a custom `QueueFake` for years because of this.

This code is just for inspiration, it works in my project but if you base a fix on it, please vet it it works in all cases:
```php
    public function size($queue = null)
    {
        return collect($this->jobs)
            ->map(function (array $job) use ($queue) {
                return $job[0]['queue'] === $queue;
            })
            ->count();
    }
```

**Comment by hlorofos** [comment]
@mfn thanks for the inspiration, but that piece doesn't traverse through properly, I'll implement something soon

**Comment by driesvints** [comment]
PR was merged
