### ISSUE TITLE
File Descriptor Issue

### ISSUE THREAD

**Issue by zeshanfarooqi** [laravel/framework#29756]
- Laravel Version: 5.5.48
- PHP Version: 7.2.17
- Database Driver & Version: MySQL 5.7.26
- Redis: 4.0.9

### Description:
We're facing two problems and both seems to be related with each other. We've tested it on Laravel 5.5 (with QUEUE_DRIVER=redis) and on Laravel 5.8 as well. We've also tried both predis and phpredis. Changing version of redis from 4.0.9 to 5.0.5 didn't help.

#### Part-1: Invalid/Broken File Descriptor
Running `php artisan queue:work` from command line will produce an invalid/broken file descriptor as shown below:
`php     6282     root    5u     sock    0,0                      81951 can't identify protocol
`
#### Part-2: High usage of file descriptors
When we run 28 queue workers via Horizon and Supervisor, usage of file descriptors by php alone reaches around 17k. On top of this, sometimes a leak also appears i.e. count of file descriptors start increasing very slowly and after few days it will cause "Too many open files" error.

### Steps To Reproduce:
1. Create a new project composer create-project --prefer-dist laravel/laravel blog "5.5.*"
2. Set QUEUE_DRIVER=redis
3. Install predis
4. Run `php artisan queue:work`
5. In another terminal run `lsof | grep php | grep identify`

**Comment by driesvints** [comment]
This goes a bit outside my own knowledge about Redis so appreciating any help here.

A couple of things to note:

- Predis isn't maintained anymore and we're deprecating it in 6.0 and it'll probably be removed in 7.0
- 5.8 uses `QUEUE_CONNECTION` instead of `QUEUE_DRIVER`
- What version of Horizon are you using?
- Does this also happen without Horizon?

**Comment by zeshanfarooqi** [comment]
> This goes a bit outside my own knowledge about Redis so appreciating any help here.
> 
> A couple of things to note:
> 
> * Predis isn't maintained anymore and we're deprecating it in 6.0 and it'll probably be removed in 7.0
phpredis is also causing same problem. The issue seems to be with `LuaScripts` that is being called from inside RedisQueue.php.

> * 5.8 uses `QUEUE_CONNECTION` instead of `QUEUE_DRIVER`
yes, that's correct. Our main project is on 5.5 so I've referred to its configuration in report. In case of 5.8 (which was just for the sake of verification) we certainly used QUEUE_CONNECTION. The issue was producible with that as well.

> * What version of Horizon are you using?
v1.4.3

> * Does this also happen without Horizon?
yes

**Comment by driesvints** [comment]
@zeshanfarooqi which version of Horizon did you use when you tested on 5.8?

**Comment by zeshanfarooqi** [comment]
> @zeshanfarooqi which version of Horizon did you use when you tested on 5.8?

lets forget about 5.8, we simply did the following for 5.8:

- Created new new project
- Set QUEUE_CONNECTION=redis
- Run php artisan queue:work

that's all. Our main point of concern is 5.5 which is our main project.

**Comment by driesvints** [comment]
@zeshanfarooqi the thing is that Horizon isn't supported anymore for 5.5 so let's indeed focus on just the queue worker here.

**Comment by zeshanfarooqi** [comment]
> @zeshanfarooqi the thing is that Horizon isn't supported anymore for 5.5 so let's indeed focus on just the queue worker here.

Oh, that's a surprise for me. Any good reason for terminating support of Horizon?

**Comment by driesvints** [comment]
@zeshanfarooqi we always only support the latest release of our first party libraries and v3.0 doesn't supports 5.5 anymore.

Also see https://laravel.com/docs/5.8/releases#support-policy

**Comment by zeshanfarooqi** [comment]
@driesvints agreed, lets focus on queue worker and Laravel 5.5 LTS.

**Comment by driesvints** [comment]
Closing this as 5.5 isn't supported anymore.
