### ISSUE TITLE
Polymorphic many to many across two connections, wrong connection is used on pivot table.

### ISSUE THREAD

**Issue by garlian** [laravel/framework#29771]
- Laravel Version: 5.8.33
- PHP Version: 7.3.2
- Database Driver & Version: mysql

### Description:
I have two database connections:
- global (db1)
- tenant (db2)

Two models:
- User (connection set to global)
- Property (connection set to tenant)

Both models connected via polymorphic many to many relationship on a "propertable" table in tenant database.

User has a "properties" method using morphToMany(Properties::class, 'propertable')

Property has a "users" method using
morphedByMany(User::class,'propertable')

If I try to load the users via my property instance I get an error that says that db1.propertables does not exist, this is true but I defined a different connection for each model, normally it should use db2 because morphedByMany is part of the Property model using the tenant connection. Is this intended behaviour? I think I could solve this via an intermediate PivotModel but want to make sure that this isn't a bug.

Here some code:
```php
class User() {
    // db1
    protected $connection = 'global';

    public function properties()
    {
        return $this->morphToMany(Property::class, 'propertable');
    }
}

class Property() {
    // db2
    protected $connection = 'tenant';

    public function users()
    {
        // Does not work, throws "Table 'db1.propertables' doesn't exist"
        return $this->morphedByMany(User::class, 'propertable');
    }
}
```

**Comment by staudenmeir** [comment]
You need to qualify the pivot table:

```php
class Property extends Model
{
    public function users()
    {
        return $this->morphedByMany(User::class, 'propertable', 'db2.propertables');
    }
}
```

**Comment by garlian** [comment]
This approach does work, but does not solve the problem in a clean way. The problem is that my tenant connection uses different databases for different domains. I could solve this problem by prepending dynamically the database based on the connection, but this feels kinda hacky.

> Laravel doesn't know which database contains the pivot table. 


I think that is not the case. The morphedByMany part is the inverse part of the many to many and the pivot is named after the model implementing that.
[Documentation example](https://laravel.com/docs/5.8/eloquent-relationships#many-to-many-polymorphic-relations)

I would think, based on the documentation example, that the pivot class named after the model using the morphedByMany uses the same connection, too. Maybe this is a false conclusion, but I think many people would think the same after consulting the docs.

**Comment by staudenmeir** [comment]
> I think that shouldn't be the case. The morphedByMany part is the inverse part of the many to many and the pivot is named after the model implementing that.

Even if you name the pivot table like that, you could put it in the other database.

> The second problem I see is that the behaviour would be inconsistent with other relation types like hasMany (working across two connections, without explicitly specifying the database and table).

You can't compare `BelongsToMany`/`MorphToMany` with other relationships here: It's much simpler to query a relationship without a pivot table across two databases since every query only targets a single database (i.e. there are no cross-database joins).

Laravel doesn't support cross-database queries yet: #23042

**Comment by garlian** [comment]
Do you now a smart workaround for this problem or do I need to handle this via custom queries?

**Comment by staudenmeir** [comment]
What exactly doesn't work with the qualified pivot table?

**Comment by garlian** [comment]
The user can't be resolved if I try to sync.

**Comment by staudenmeir** [comment]
What's the error?

**Comment by garlian** [comment]
Okay, my bad! I tracked down the error, your soultion worked, feeling stupid right now 😅 I had an existence check in my request class, obviously using the wrong db...

Your first solution works! Thank you so much :-)

**Comment by gsingh005** [comment]
What if the the two DB are on different servers. Is it possible to make the relationship ?
