### ISSUE TITLE
Session Persistance Issue with some browser

### ISSUE THREAD

**Issue by grund3g** [laravel/framework#29773]
- Laravel Version: 5.8.30
- PHP Version: 7.3.6
- Session Driver: redis

### Description:
This issue has been described several times, but partly with other causes:
- #8172,
- https://stackoverflow.com/questions/42769388/laravel-session-always-changes-every-refresh-request-in-laravel-5-4/43893114
- https://stackoverflow.com/questions/38851524/session-not-persist-when-request-comes-from-android-device
- https://laracasts.com/discuss/channels/general-discussion/tokenmismatch-only-certain-browsers-laravel-5-freshproduction

I noticed the problem as more "Illuminate\Session\TokenMismatchException" errors occurred in my logs.

I stored every server request in a DB for a few days and saw that the session_id of the browsers listed below is renewed every time a page is visited.

In my case, the problem only occurs in some versions of **Internet Explorer, Edge, and Android browsers**.
I could not reproduce the issue in Chrome, Firefox, Chrome on Android, Safari on iPhone. 

_Here are some exact user agents of the last browsers where the problem occurred:_
```
Mozilla/5.0 (Linux; Android 9; SAMSUNG SM-G960F/G960FXXU6CSG8 Build/PPR1.180610.011) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/9.4 Chrome/67.0.3396.87 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 8.0.0; SAMSUNG SM-G965F Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/9.4 Chrome/67.0.3396.87 Mobile Safari/537.36
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.15063
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134
```

Some things I've already tried:
- changed session driver from "redis" to "file" or "database
- removed "_" from session cookie name (some people mentioned this to be a problem)
- changed SESSION_SECURE_COOKIE to "false"
- added the header `p3p: CP="IDC DSP COR ADM DEVi TAIi PSA PSD IVAi IVDi CONi HIS OUR IND CNT"`

I checked the cookies (with Browserstack) in Edge and see that they are set as expected, but the value changes on every page load.

**Comment by grund3g** [comment]
Interestingly, it looks like only the session_id is renewed with every request. I just tried to authenticate a user in the mentioned browsers and this user remains authenticated

**Comment by shardick** [comment]
i have the same problem, only in production and it could be reproduced with some PC but not all users. 
The session cookie change value every pageload.

I've tried with session driver as redis, file and cookie, setting session domain, but nothing. Authentication works, i remain authenticated but cannot send any post causing 419 Page Expired.

**Comment by driesvints** [comment]
I can't test on Edge myself so if anyone can help out here or verify that this is broken on Edge, that would be great.

**Comment by Artessan** [comment]
I can confirm that the issue exist on Android browser and edge browser including edge chromium in Windows but only when deploy with vapor, in local is working without problems

**Comment by Lirux** [comment]
I have this issue too.

This happens on MacOS 10.14.6 with Chrome, Firefox, Safari. 
But I don't get a 419 Error / TokenMismatchException.

And on Windows 10 1903 With Chrome, Edge, Firefox. 
I don't get an 419 Error / TokenMismatchException on Chrome, Edge and Firefox in **Incognito-Mode**

419 Error on Firefox in "Normal-Mode"

**Comment by davidgil** [comment]
exactly the same here, i just tested all that i read on internet without any results.

**Comment by davidgil** [comment]
In my case, not sure if same of yours, the problem is that in some routes we as for Windows Basic Autentication (NTML autentication). And for that IE11 is using this:

https://blogs.msdn.microsoft.com/ieinternals/2010/11/21/challenge-response-authentication-and-zero-length-posts/

We see a zero length post request to our forms, then as no csrf token is there it fails.

We try to solve it using different routes for form render and form submit (subfolders)

Best

**Comment by grund3g** [comment]
Although I opened this request, I don't think it has anything to do with the framework itself anymore.

It's just not easily reproducible, and only occurs in certain browser versions. 

Maybe there is a problem with cookie handling in a few browser versions that has already been fixed in the next version.
