### ISSUE TITLE
[6.0] Scaffold Auth

### ISSUE THREAD

**Issue by jimgwhit** [laravel/framework#29782]
A good reference first is:

https://laracasts.com/discuss/channels/laravel/laravel-60-appcss

The docs state:
> In fact, you don't have to use JavaScript at all.

Yet to scaffold Auth you have only two choices:
```ruby
php artisan ui vue --auth
or
php artisan ui react --auth
```
I of course do use JS, I use jquery.  
It generated everything when I ran
```
php artisan ui vue --auth
```
I did run composer require laravel/ui  first, However in app.blade.php it has:
```
<link href="{{ asset('css/app.css') }}" rel="stylesheet">
```
But no where is the file app.css found.  Where is app.css supposed to come from.

**Comment by jimgwhit** [comment]
Here is the main question. Where is app.css.  I think you might have missed that point, nowhere to be found is an app.css.

Fyi I've used laravel since 4.2 I know I can override anything.

The issue is there is a missing file. app.css.

**Comment by devcircus** [comment]
It's best to take this to one of the community forums. 

You create it. It doesn't exist. 
The most common convention for frontend assets in Laravel is to use laravel mix or a bundle of some sort, that bundles your styles into public/css/app.css and your scripts into public/js/app.js. 
Check out the laravel docs on assets. https://laravel.com/docs/5.8/mix

**Comment by jimgwhit** [comment]
This is a 6.0 issue, 5.8 has no issue with a missing app.css file.  Trying to get this stuff fixed before final release to help people.

 See my original post above I reference a link in the community forum.

**Comment by jimgwhit** [comment]
Well I deleted all and tried again, an after running:
```
php artisan ui vue --auth
```

I noticed the message:
```ruby
Please run "npm install && npm run dev" to compile your fresh scaffolding.
```
So I guess the framework now requires npm if you want the out of the box Auth scaffolding.

Yet without installing npm, renaming bootstrap.css to app.css I got ll working.  Is this just a way to force newcomers to the framework who may not know a work around to have to install npm, and have to compile assets.

Up to now since version 4.2 nothing has even been forced on you.  Maybe forced isn't the best word here, but all I can think of.  Why is npm suddenly appeared to be required, when a small app with custom css and a small amount of jquery does not need compiled.

I still think of it as an issue, it appears to remove flexibility all previous versions had.

Experienced laravel folks knows work arounds, but new comers won't have any idea that there is a work around.

**Comment by driesvints** [comment]
Everything is explained here: https://laravel.com/docs/6.0/frontend#writing-css

If you feel that this can be explained better than feel free to send in a PR.

**Comment by jimgwhit** [comment]
I don't understand the duck and run answer.  I was referring to npm now being required for authorization scaffolding yet it never was before.

**Comment by rimace** [comment]
Just to give you some support. That`s the commit in which the app.css is removed: https://github.com/laravel/laravel/commit/fc39b073f3f61a22f1b48329e294ebb881700dbe
Maybe the others will now better understand what you mean.
I also have have to say this doesn't look like a bug but rather like a question, so it doesn't fit in here.
