### ISSUE TITLE
wrong email validation

### ISSUE THREAD

**Issue by redayoub47** [laravel/framework#29781]
- Laravel Version: 5.8.29
- PHP Version: 7.2.19
- Database Driver & Version: MySql

### Description:
when i used email validation in laravel it accepted this email `xxxxx@gmailcom` which is a wrong format of emails

here my project https://github.com/redayoub47/academy_laravel_vuejs_app/blob/master/app/Http/Controllers/AuthController.php
line 21
```
public function register(Request $request)
    {
        $validatedData=$request->validate([
            "username"=>"required|max:192|unique:users",
            "email"=>"email|required|max:192|unique:users",
            "password"=>"required|max:192",
            "first_name"=>"required|max:192",
            
            "last_name"=>"required|max:192",
        ]);
        $validatedData["password"]=bcrypt($request->password);

```

**Comment by staudenmeir** [comment]
In Laravel 5.8.33, you can use the `filter` validation: https://laravel.com/docs/5.8/validation#rule-email

**Comment by redayoub47** [comment]
thanks i used filter it is working but the error message i get when invalid email is
```
"email": [
            "The email has already been taken."
        ]
```
even if the email is new , the other thing i wanna know the difference between the other validation options 
- rfc: RFCValidation
- strict: NoRFCWarningsValidation
- dns: DNSCheckValidation
- spoof: SpoofCheckValidation
- filter: FilterEmailValidation

**Comment by driesvints** [comment]
@redayoub47 that new issue seems more like something for a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks.
