### ISSUE TITLE
Redis contract missing loads of of methods

### ISSUE THREAD

**Issue by GrahamCampbell** [laravel/framework#29784]
- Laravel Version: 5
- PHP Version: 7
- Database Driver & Version: N/A

### Description:

The framework calls methods other than `->command(...)` on a redis connection, yet only specifies that it expects a `Illuminate\Contracts\Redis\Connection`, such as in caching and rate limiting. We need to add a load of methods to the contract, or avoid calling them.

**Comment by driesvints** [comment]
I'm not sure this is necessary. It would be a little bit of overkill to add all of these methods. In any case this is more of a discussion for the ideas repo.
