### ISSUE TITLE
firstOrNew returns more than one result (with datetime)

### ISSUE THREAD

**Issue by aliasbody** [laravel/framework#29787]
- Laravel Version: Lumen 5.7.7
- PHP Version: 7.1.23
- Database Driver & Version: pgsql 9.6.6

### Description:
When using a date as a condition when checking firstOrNew, because of the use of "first()" the result will be all the values from the DB that correspond to the conditions (except the date)

### Steps To Reproduce:
Do a simple query, like this one:

```
$stats = Stats::query()->where([
    'created_at' => Carbon::today()->format('Y-m-d')  
    foreign_key => '1',
])->get()
```

If we then do 
```
dd($stats->pluck('created_at'));
```
We only have one result, which is good, so once we do *$stats->save()* after adding the information we need to insert it will do the work correctly. But if we try to use *firstOrNew* like this:

```
$stats = Stats::query()->firstOrNew([
    'created_at' => Carbon::today()->format('Y-m-d')  
    foreign_key => '1',
])
```

If we then do 
```
dd($stats->pluck('created_at'));
```

If returns all the values that correspond to the conditions (except for the date) and thus returns more than one entry. After checking it is because of this:

```
/**
     * Execute the query and get the first result.
     *
     * @param  array  $columns
     * @return \Illuminate\Database\Eloquent\Model|object|static|null
     */
    public function first($columns = ['*'])
    {
        return $this->take(1)->get($columns)->first();
    }
```

But why would it be returning more than one value?

**Comment by dkulyk** [comment]
Model does not have `pluck` method and pass(__call) it to query builder

**Comment by aliasbody** [comment]
@dkulyk The pluck was just an example (and maybe not the best one). The thing is that the save really affects more than only the found row when updating and using the firstOrNew.

**Comment by staudenmeir** [comment]
`firstOrNew()` always returns a single result.

> The pluck was just an example (and maybe not the best one).

What does your actual code look like?

**Comment by dkulyk** [comment]
```php
$stats = Stats::query()->where([
    'created_at' => Carbon::today()->format('Y-m-d')  
    foreign_key => '1',
])->get()
```
$stats is Collection

```php
$stats = Stats::query()->firstOrNew([
    'created_at' => Carbon::today()->format('Y-m-d')  
    foreign_key => '1',
])
```
$stats is Model

`$stats->pluck('created_at');` fro Model is equivalent of `$stats->newQuery()->pluck('created_at');`

**Comment by driesvints** [comment]
We don't support Lumen 5.7 anymore sorry. Btw, Lumen has its own issue tracker: https://github.com/laravel/lumen-framework/issues
