### ISSUE TITLE
Broadcast Facade missing docblock for $options parameter

### ISSUE THREAD

**Issue by XGhozt** [laravel/framework#29796]
- Laravel Version: 5.8
- PHP Version: 7.2
- Database Driver & Version:

### Description:
https://github.com/laravel/framework/blob/0c85be5c4b33c3174372432a134bdb2523ce2a2c/src/Illuminate/Support/Facades/Broadcast.php#L9

`\Illuminate\Broadcasting\Broadcasters\Broadcaster` Supports 3 parameters, docblock `array $options` is missing.

https://github.com/laravel/framework/blob/0c85be5c4b33c3174372432a134bdb2523ce2a2c/src/Illuminate/Broadcasting/Broadcasters/Broadcaster.php#L47

**Comment by driesvints** [comment]
Feel free to send in a pr
