### ISSUE TITLE
illuminate/database issue / join

### ISSUE THREAD

**Issue by Prootex** [laravel/framework#29797]
- Laravel Version: 5.8
- PHP Version: 7.1
- Database Driver & Version:
MySQL 5.5

### Description:

the same query result in an error after upgrade illuminate database from 5.4 to 5.8

Illuminate\\Database\\QueryException
Column not found: 1054 Unknown column 'BETWEEN' in 'on clause'

### Steps To Reproduce:
Illuminate/database 5.4
query:
`$query->leftJoin('holidays', function($join) {
            $join->on('start_time', 'BETWEEN', DB::RAW("date AND date_add(date,  interval 1 day)"))->
            orOn('stop_time', 'BETWEEN', DB::RAW("date AND date_add(date, interval 1 day)"));
        });`

result sql:
`left join holidays on start_time BETWEEN date AND date_add(date,  interval 1 day) or stop_time BETWEEN date AND date_add(date, interval 1 day)`

Illuminate/database 5.8
query:
`$query->leftJoin('holidays', function($join) {
            $join->on('start_time', 'BETWEEN', DB::RAW("date AND date_add(date,  interval 1 day)"))->
            orOn('stop_time', 'BETWEEN', DB::RAW("date AND date_add(date, interval 1 day)"));
        });`

result sql:
`left join holidays on start_time = BETWEEN or stop_time = BETWEEN`

**Comment by staudenmeir** [comment]
This was caused by #22182.

You can use `whereRaw()` instead:

```php
$query->leftJoin('holidays', function ($join) {
    $join->whereRaw('start_time BETWEEN date AND date_add(date, interval 1 day)')
        ->orWhereRaw('stop_time BETWEEN date AND date_add(date, interval 1 day)');
});
```

**Comment by driesvints** [comment]
@staudenmeir so should we fix this or not?

**Comment by staudenmeir** [comment]
Actually, `whereBetween()` is the better/right solution:

```php
$query>leftJoin('holidays', function ($join) {
    $join->whereBetween('start_time', [DB::raw('date'), DB::raw('date_add(date, interval 1 day)')])
        ->orWhereBetween('stop_time', [DB::raw('date'),  DB::raw('date_add(date, interval 1 day)')]);
});
```

**Comment by staudenmeir** [comment]
@driesvints I don't think we should. I don't see it as a bug but "only" as a breaking change that went into the wrong version.

**Comment by driesvints** [comment]
@Prootex try out the `whereBetween` method like @staudenmeir suggested. Thanks.

**Comment by Prootex** [comment]
it works, thank you
