### ISSUE TITLE
eager loading with delete rows issue

### ISSUE THREAD

**Issue by joisarjignesh** [laravel/framework#29801]
- Laravel Version: 5.5.28
- PHP Version: 7.2.16
- Database Driver & Version:  MySQL 5.7.18

### Description:
i have issue on nested eager loading or eager loading **both** with delete rows.. 

**Course.php**

 ```
 public function section() {
        return $this->hasMany(section::class);
  }
```

**Section.php** 

```

 public function lecture() {
        return $this->hasMany(lecture::class);
 }

 public function course() {
        return $this->belongsTo(course::class);
 }
```

**Lecture.php**

```
 public function section() {
        return $this->belongsTo(section::class);
 }

```

### Steps To Reproduce:

when i try  
 it will getting proper rows ...

` App\course::with('section')->first()`

when i try to fetch rows nested eager loading then also getting proper rows..

` App\course::with('section.lecture')->first()`

but when i try like this 

` App\course::with('section')->first()->delete()`

Then only delete course row **not a section rows** i want to delete  section rows also...

again when i try like this 

` App\course::with('section.lecture')->first()->delete()`

Then only delete **course row**

> what i want 
> i want to delete also section rows as well as lecture rows using nested eager loading by this line of code..(soft delete or not)
> 

` App\course::with('section.lecture')->first()->delete()`

> at Present i m doing delete child rows using **each collection function** this code : 

        ```
       if ($course = course::where('id', $id)->first()) {
                   $course->section->each(function($section){
                        $section->each(function($lecture){
                            $lecture->lecture()->delete();
                        });
                        $section->delete();
                    });
                    $course->delete();
           }

```

**Comment by staudenmeir** [comment]
Laravel doesn't and shouldn't delete eager-loaded relationships.

Consider using cascading foreign keys: https://stackoverflow.com/a/14176326/4848587

**Comment by joisarjignesh** [comment]
@staudenmeir  if you're using soft deletes then how can we delete not permanently..

**Comment by staudenmeir** [comment]
Should the sections and lectures *always* be deleted when you delete a course?

If so, take a look at https://stackoverflow.com/a/20108037/4848587.

**Comment by joisarjignesh** [comment]
@staudenmeir  ok i try like this but  is it a good because every time **model check delete or not**  idea?

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by joisarjignesh** [comment]
@driesvints i am getting a same issue on **laravel 5.8.34 version** so please check ...
