### ISSUE TITLE
Sending array as header from test causes an array to string conversion error

### ISSUE THREAD

**Issue by damcclean** [laravel/framework#29805]
- Laravel Version: 5.8.34
- PHP Version: 7.3.5
- Database Driver & Version: N/A

### Description:
In my application, I am sending a header my controller, when I try and access the header contents using `$request->header('message')`, it returns `null`. However when I try to get a list of headers using `$request->headers`, my header shows up.

I have tried this in one of my apps and in a fresh Laravel app, both on version 3.8.34. I'm sure this was working previously.

### Steps To Reproduce:
1. Install a new Laravel app
2. Create a controller like this:
```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class TestController extends Controller
{
    public function __invoke(Request $request)
    {
    	dd($request->header('message');

    	return [
    		'text' => 'Good'
    	];
    }
}
```
3. Create a route pointing at the new controller
```
Route::get('/test', 'TestController');
```
4. Create a new test to send headers to the route.
```
<?php

namespace Tests\Feature;

use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class AwesomeTest extends TestCase
{
    /** @test */
    public function it_can_send_headers()
    {
        $response = $this->get('/test', [
            'message' => 'Hello World!'
        ]);

        $response->assertJson([
            'text' => 'Good'
        ]);
    }
}
```

**Comment by staudenmeir** [comment]
Your code works for me. Please create a sample application and upload it to GitHub.

**Comment by damcclean** [comment]
Alright, I've pushed my sample application to Github. https://github.com/damcclean/test-header-issue

**Comment by staudenmeir** [comment]
That also works for me. When I put `dd($request->header('message'));` in the controller, I get `Hello World!`.

**Comment by damcclean** [comment]
I'm just running it with PHPUnit like, `./vendor/bin/phpunit`, nothing fancy.

I just ran the same thing on my machine and it started to work.... I'll try in my other app to see if it works there. Rather strange it would work today but not yesterday.

**Comment by damcclean** [comment]
Hmm, ok. So I tried the message header (from the example) in my production app where I spotted the issue and it worked.

My issue is that the header I'm trying to send and receive in my real app is an array. 

This is how I'm sending the array from my test.

```
        $response = $this->get('/test', [
                'list' => [
                    'foo' => [
                        'title' => 'Foo'
                    ],
                    'bar' => [
                        'title' => 'Bar'
                    ]
                ]
            ]);
```

This is how I'm trying to dump it.

```
dd($request->header('list'));
```

Now I'm getting the `ErrorException: Array to string conversion` error. Should I have encoded the array as JSON or something before I sent it as headers. Maybe I'm doing something wrong.

**Comment by staudenmeir** [comment]
> My issue is that the header I'm trying to send and receive in my real app is an array.

Does the array header work in your application (how?) or did you write the test first?

**Comment by damcclean** [comment]
Sorry, I don't understand what you mean.

The same error comes up in my fresh Laravel app plus my production application.

**Comment by staudenmeir** [comment]
How does an array header work in an actual application? How does the client send an array?

**Comment by damcclean** [comment]
OK, so for normal users they don't have to send any header at all to the url as the list data they get is from an external API.

However for testing, the tests send through a list header which goes back to the class I call the API from and instead of querying the API, I'm just using the provided header. 

I know there are better ways of doing it like using mocks but I don't really want to have to duplicate more code than I really need to.

Maybe what would be easier is creating JSON files with the header contents in them and just passing a normal string header with the file's path for it to use.

**Comment by staudenmeir** [comment]
I'm asking because I've never heard of array headers and I don't think they "exist".

You'll need to use a different approach.

**Comment by damcclean** [comment]
Oh ok, no wonder why they don't work 😂 

Thanks for your time helping out with this issue.
