### ISSUE TITLE
[6.0] No upgrade path for authentication

### ISSUE THREAD

**Issue by jimgwhit** [laravel/framework#29807]
Referring to closed issue: #29782

It appears there is no update or upgrade path for a previously scaffolded authentication system going from 5.8 to 6.0.  Yet the docs has upgrading. 

With the new UI a person would have to completely redo from scratch their authentication system.

No this is not a question but an issue, please read the closed issue #29782 first.  You now need vue or react even if you only need one css file for authentication, app.css.  

Why would you require only one single css file (app.css) to have to be compiled to use Laravel.

**Comment by driesvints** [comment]
This is only for new Laravel 6 apps. Existing apps are unaffected. And if you're using Laravel 6 you're going to have to follow the instruction from the docs: https://laravel.com/docs/6.0/frontend#writing-css
