### ISSUE TITLE
when i put the (sub/add) route outside the whole function it is working but when i put this in this way it is not working and even not show on php artisan route:list also  

### ISSUE THREAD

**Issue by Mrpunk420** [laravel/framework#29819]
Route::group([
                    'prefix' => 'events',
                ], function () {
                    Route::get('/{id?}','EventController@index')->name('events.index')->where('id', '[0-9]+');
                    Route::get('/add','EventController@single')->name('events.single');
                    Route::post('/add','EventController@create')->name('events.create');
                    Route::get('/edit/{id}','EventController@showEditForm')->name('events.editForm');
                    Route::post('/edit/{id}','EventController@update')->name('events.update');
                    Route::get('/delete/{id}','EventController@delete')->name('events.delete');
                    Route::get('/{id}/{status}','EventController@status')->name('events.status');

                    Route::group([
                        'prefix' => 'sub',
                    ], function () {
                        Route::get('/{id?}','SubEventController@index')->name('subevents.index')->where('id', '[0-9]+');

                        Route::get('/add',function(){
                            return 'heyyy';
                        })->name('subevents.single');

                    });

                });

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
