### ISSUE TITLE
Why doesn't Schema::getFacadeAccessor return a string?

### ISSUE THREAD

**Issue by CyberiaResurrection** [laravel/framework#29818]
- Laravel Version: 5.8.34
- PHP Version: 7.2.21
- Database Driver & Version: N/A

### Description:
Per https://github.com/laravel/framework/pull/25525 and implied by \Illuminate\Support\Facades\Facade::swap() (as below),

```
    public static function swap($instance)
    {
        static::$resolvedInstance[static::getFacadeAccessor()] = $instance;

        if (isset(static::$app)) {
            static::$app->instance(static::getFacadeAccessor(), $instance);
        }
    }
```

Why does \Illuminate\Support\Facades\Schema return a schema Builder rather than a string, like the vast bulk, if not all, of the other defined facade classes in the core framework?

### Steps To Reproduce:
N/A

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
