### ISSUE TITLE
BadMethodInvocation inside public/index.php(58)

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [laravel/framework#29812]
- Laravel Version:  5.8.15
- PHP Version: 7.2
- Database Driver & Version: --

### Description:
Every Request generate this exception/stacktrace:
```
[2019-08-31 20:27:50] local.ERROR: Method Illuminate\View\View::send does not exist. {"exception":"[object] (BadMethodCallException(code: 0): Method Illuminate\\View\\View::send does not exist. at /home/marcober/public_html/nonsoloarredo.com/www/vendor/laravel/framework/src/Illuminate/View/View.php:410)
[stacktrace]
#0 /home/marcober/public_html/nonsoloarredo.com/www/public/index.php(58): Illuminate\\View\\View->__call('send', Array)
#1 {main}
"} 
[2019-08-31 20:27:50] local.ERROR: Uncaught BadMethodCallException: Method Illuminate\View\View::send does not exist. in /home/marcober/public_html/nonsoloarredo.com/www/vendor/laravel/framework/src/Illuminate/View/View.php:410
Stack trace:
#0 /home/marcober/public_html/nonsoloarredo.com/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(112): Illuminate\View\View->__call('send', Array)
#1 /home/marcober/public_html/nonsoloarredo.com/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(89): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(BadMethodCallException))
#2 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(BadMethodCallException))
#3 {main}
  thrown {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Uncaught BadMethodCallException: Method Illuminate\\View\\View::send does not exist. in /home/marcober/public_html/nonsoloarredo.com/www/vendor/laravel/framework/src/Illuminate/View/View.php:410
Stack trace:
#0 /home/marcober/public_html/nonsoloarredo.com/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(112): Illuminate\\View\\View->__call('send', Array)
#1 /home/marcober/public_html/nonsoloarredo.com/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(89): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(BadMethodCallException))
#2 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(BadMethodCallException))
#3 {main}
  thrown at /home/marcober/public_html/nonsoloarredo.com/www/vendor/laravel/framework/src/Illuminate/View/View.php:410)
[stacktrace]
#0 {main}
"} 
```
All the responses in every controllers have this pattern
`return response()->make(view('folder.view'), return_error);`
and on 'view()' the only method that i call is with(), where necessary

**Comment by rimace** [comment]
Change this
`return response()->make(view('folder.view'), return_error);`
into this
`return view('folder.view');`
I don't know what `return_error` could be, so i can't help with that though.

**Comment by AlbertoSinigaglia** [comment]
i can't o that, because i use `Cookie::queue(...)` to set cookies and if i change `response()->make(view('folder.view')` with `return view('folder.view')` laravel will throw a lot of errors saying ''trying to add cookie to a View, Response needed''.
And yes, sorry, with return_error i mean http_response_code, so 2xx, 3xx or 4xx

**Comment by RFreij** [comment]
Could you post your exact controller method?

**Comment by AlbertoSinigaglia** [comment]
```
public function home(Request $request){
        $request->session()->put('products', array());
        return response()->make(view("home"),200);
}
```
but i don't know in which moment during the website visit  the error is thrown, however all the controllers methods return something like this method here

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
