### ISSUE TITLE
[6.0] Error after installing Telescope

### ISSUE THREAD

**Issue by isluewell** [laravel/framework#29816]
- Laravel Version: 6.0-dev
- PHP Version: 7.3.8-1+ubuntu19.04.1+deb.sury.org+1
- Database Driver & Version: pgsql, 10

### Description:
The following error is displayed after installing Telescope

>  InvalidArgumentException  : Length must be a positive integer.

occurs when attempting to perform any action within the project, or url load.

`at vendor/ramsey/uuid/src/Generator/CombGenerator.php:63`

```php
public function generate($length)
{
   if ($length < self::TIMESTAMP_BYTES || $length < 0) {
      throw new \InvalidArgumentException('Length must be a positive integer.');
   }

   $hash = '';
}
```
### Steps To Reproduce:
`laravel new blog --dev`

`composer require laravel/telescope`

`php artisan`

**Comment by barryvdh** [comment]
Is this with the latest version? The same error was in the tests but that was fixed with that PR: https://github.com/laravel/framework/pull/29809

**Comment by isluewell** [comment]
If it has been fixed, I just did **composer update** (I had done it before) and now it works, thank you very much.
