### ISSUE TITLE
[PHP 7.4] Use of undefined constant PASSWORD_ARGON2ID - assumed 'PASSWORD_ARGON2ID' (this will throw an Error in a future version of PHP)

### ISSUE THREAD

**Issue by HepplerDotNet** [laravel/framework#29815]
- Laravel Version: 5.8.34
- PHP Version: 7.4-beta4
- Database Driver & Version: not involved

### Description:
`Hash::make('secret-password') `
throws ErrorException in /vendor/laravel/framework/src/Illuminate/Hashing/ArgonHasher.php:83

### Steps To Reproduce:

1. Install laravel/laravel on PHP 7.4-beta4
2. Set 'driver' => 'argon' in hashing.php
3. Call Hash::make('something')

**Comment by crissi** [comment]
This algorithm is only available if PHP has been compiled with Argon2 support. See here: https://www.php.net/manual/en/function.password-hash.php

**Comment by HepplerDotNet** [comment]
From repo maintainer:
php 7.3 use argon2 lib
php 7.4 use argon2 from libsodium
Had to install  php74-php-sodium
