### ISSUE TITLE
Artisan app:name command missing in V6

### ISSUE THREAD

**Issue by mknooihuisen** [laravel/framework#29817]
- Laravel Version: 6.0.x-dev
- PHP Version: 7.3.7
- Database Driver & Version: n/a

### Description:
New installations of Laravel 6 do not include the `artisan app:name` command.  Yes, you can manually change the Namespace and use a "Replace in Files..." command to get to green but this is still less convenient, especially if `app:name` did more than that behind the scenes.

### Steps To Reproduce:

1.  Install Laravel Framework 6.0.x-dev
2.  attempt to run `php artisan app:name <Namespace>`

This was probably just an oversight, but I thought it worth a mention. :)

**Comment by brunogaspar** [comment]
The command was removed [here](https://github.com/laravel/framework/commit/fe06c206fcac081d3c93ee7d38eb3174e83603f5#diff-52ce501efc27d62b35ed72232484863b) so it's intended that it's missing.

**Comment by mknooihuisen** [comment]
@brunogaspar Appreciated.  I can see the logic in this, but can't this still cause upgrade problems for people who have already changed the namespace?

I'm just making the assumption that the new version may create missing file stubs assuming the `App` namespace.

**Comment by isluewell** [comment]
The command has been removed in Laravel 6. See #27575 

https://github.com/laravel/framework/pull/27575#issuecomment-526836074

**Comment by driesvints** [comment]
This was removed.

**Comment by andrey-helldar** [comment]
If anyone needs this command and removed `str_` and `arr_` helpers, you can install this package: [andrey-helldar/laravel-helpers](https://github.com/andrey-helldar/laravel-helpers)
