### ISSUE TITLE
[6.0] Where is the command app:name? 🥺

### ISSUE THREAD

**Issue by isluewell** [laravel/framework#29810]
The app:name command, no longer available in laravel 6.0, there is some way to change the namespaces, as was being done with that command in all the necessary files.

**Comment by GrahamCampbell** [comment]
The command has been removed in Laravel 6. See https://github.com/laravel/framework/pull/27575. :)

**Comment by isluewell** [comment]
**I created a gist, in case anyone else needs it.**

https://gist.github.com/isluewell/b824c0aef32f5007170fcd0d8498b657

First we create the command with

``` php
php artisan make:command AppName
```

Then we replace the content created in the file `app/Console/Commands/AppName.php` with the content of the gist.

and then use it in the usual way, changing `Luewell` for the name of your application.

``` php
php artisan app:name Luewell
```

**Comment by andrey-helldar** [comment]
*facepalm*

**Comment by andrey-helldar** [comment]
@isluewell, you can install my package with returned deprecated `app:name` console command and `str_` and `arr_` helpers: https://github.com/andrey-helldar/laravel-helpers

**Comment by aligajani** [comment]
Why was it removed..........

**Comment by andrey-helldar** [comment]
@aligajani, see first comment in the #27575 PR.

**Comment by Jossnaz** [comment]
@andrey-helldar there is no explanation as why it was removed. "you generally dont want to use a custom namespace" ahhh? no? Well I generally want to use my own, just because. So why?

**Comment by andrey-helldar** [comment]
@Jossnaz, I can assume that this functionality is not crucial for the framework and therefore was cut out of the box.

If you need it, just use package [laravel-app](https://github.com/andrey-helldar/laravel-app) - this is the same cut functionality.

**Comment by Ojansen** [comment]
It now uses the `APP_NAME` variable in the `.env`

**Comment by andrey-helldar** [comment]
> It now uses the `APP_NAME` variable in the `.env`

What? Not.
This variable is needed to display the title of the site. This thread is about changing the namespace.

**Comment by manuelhm1993** [comment]
@isluewell excelente, me funcionó a la perfección, muchas gracias colega

**Comment by riettotek** [comment]
Thank u some much! 👍
