### ISSUE TITLE
Jobs dispatched with a delay of "0" goto the delayed queue

### ISSUE THREAD

**Issue by matthew-muscat** [laravel/framework#29820]
Laravel Version: 5.8.34

### Description

Jobs dispatched on a queue with a delay value set to `0` result in the job being created on the "delayed" queue, upon which it is then migrated onto the "primary" queue for processing.

### Steps to reproduce

1. Dispatch a job with a delay of 0
```
$delay = '0'; //$this->desiredDelay();

ProcessPodcast::dispatch($podcast)
    ->delay($delay);
```

2. Observe that the job is pushed onto the "delayed" queue initially, upon which it's migrated into the "primary" queue.

### Expected Behaviour

In my interpretation, a delay of `0` indicates no delay should be applied to the job — however, it appears that the logic expects this value to be `null`.

In our instance, this behaviour occurs as we calculate a delay metric for jobs based on the current rate of flow of activity, which always returns an integer value — in which a value of `0` would indicate no delay is requested.

**Question** Should we be treating a delay value of `0` the same as `null`?

**Comment by driesvints** [comment]
Heya. I see why you'd think that but that's indeed not how it works atm. But this could be changed perhaps. Although this isn't really a bug and more of a behavioral change. So please open up an issue on the ideas repo and maybe attempt a PR to the master branch. Thanks.
