### ISSUE TITLE
QueryProcessor->processInsertGetId() incorrectly casts string identifiers to (int)

### ISSUE THREAD

**Issue by mdzhokanov** [laravel/framework#29824]
- Laravel Version: **6.0.0**
- PHP Version: **7.3.1 (32-bit)**
- MySQL: **10.1.31-MariaDB**

### Description:
An issue was found in _src/Illuminate/Database/Query/Processors/Processor->processInsertGetId()_
Currently, this method always casts numeric identifiers to integer, even if they are explicitly declared as String objects:
`return is_numeric($id) ? (int) $id : $id;`

In case of 32-bit PHP environment this might lead to 32-bit integer overflow issues, since 32-bit PHP is unable to cast SQL BIGINT values.

### Steps To Reproduce:
1. Create table and set high BIGINT initial value
```
CREATE TABLE `items` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,  PRIMARY KEY (`id`)) ENGINE = InnoDB;
ALTER TABLE `items` AUTO_INCREMENT = 1000000000000000001;
```

2. Create Eloquent model and explicitly set that `id` is **STRING**
```
class Item extends Model{
    protected $table = 'items';
    protected $casts = ['id' => 'string'];
}
```

3. Insert new row in `items` table via Eloquent.
```
$item = new Item();
$item->save();
dd($item->id);
```

### Expected result
`1000000000000000001`

### Actual result
`2147483647`

**Comment by driesvints** [comment]
Is this even something that a 32 bit system can handle?

**Comment by rimace** [comment]
I'm not sure if it is because you used the `$casts` property for that. Actually you have to set the type of the ID like this:
```
/**
 * The "type" of the auto-incrementing ID.
 *
 * @var string
 */
protected $keyType = 'string';
```

**Comment by mdzhokanov** [comment]
> Is this even something that a 32 bit system can handle?

Yes, as long you don't make the (int) cast everything works perfectly. I guess the solution here would be to check what is the $keyType of the Eloquent model first. And if it is not integer, then please do not attempt casting it to integer.

> I'm not sure if it is because you used the $casts property for that. Actually you have to set the type of the ID like this:

Setting $keyType **does not affect** QueryProcessor->processInsertGetId() behaviour in any way. But I agree that it is expected to do so. 

My suggestion would be to add additional input parameter into processor's method:
```
public function processInsertGetId(Builder $query, $sql, $values, $sequence = null, $idKeyType = null){
        ...
        $id = $query->getConnection()->getPdo()->lastInsertId($sequence);
        $idKeyType = $idKeyType ?? (is_numeric($id) ? 'int' : 'string');
        settype($id, $idKeyType);
        return $id;
}
```

**Comment by staudenmeir** [comment]
> And if it is not integer, then please do not attempt casting it to integer.

An auto-incrementing id is by definition an integer.

**Comment by driesvints** [comment]
I with you @staudenmeir but doesn't the int casting seem a bit weird in this situation?

**Comment by staudenmeir** [comment]
@driesvints Why do you find it weird? I think it makes sense for `insertGetId()` to return an integer.

**Comment by driesvints** [comment]
@mdzhokanov I have to say I agree with @staudenmeir. It seems that it's best that you move to a 64 bit system if you want to handle 64-bit integers.

**Comment by mdzhokanov** [comment]
> An auto-incrementing id is by definition an integer.
@staudenmeir , thanks for your answer, but you are wrong! Auto-incrementing is not a prerogative for integers only. There are many databases that support custom auto-incrementing logic for strings. Actually, the code that we are discussing already supports this - please note how you pass a $sequence to the PDO:
`$query->getConnection()->getPdo()->lastInsertId($sequence);`
In this case the database increments the ID with next value in sequence (e.g. 'aaa', 'aab', 'aac', 'aad', etc.) and returns the value to Laravel's processor. Unfortunately, the QueryProcessor is bluntly attempting to cast EVERYTHING to integer. Which is wrong for so many reasons:

- REASON 1: db sequences supports other scalar types

- REASON 2: the key type has been explicitly declared as non-integer

- REASON 3: Laravel's QueryProcessor does not respect its own API ($keyType/$casts).

 
> I don't think you can except 64-bit integers to work on a 32-bit system.
This is second incorrect assumption in your statement - there are multiple examples of applications and frameworks supporting 64-bit integers in 32-bit OS - for example MySQL and MariaDB. 

> I with you @staudenmeir but doesn't the int casting seem a bit weird in this situation?
@driesvints , of course it does - since it is explicitly declared as String by Laravel's own API.

**Comment by staudenmeir** [comment]
> Unfortunately, the QueryProcessor is bluntly attempting to cast EVERYTHING to integer.

That's not true. With the `is_numeric()` check, Laravel supports string keys like auto-generated UUIDs.

**Comment by mdzhokanov** [comment]
> > Unfortunately, the QueryProcessor is bluntly attempting to cast EVERYTHING to integer.
> 
> That's not true. With the `is_numeric()` check, Laravel supports string keys like auto-generated UUIDs.

I stand corrected - " the QueryProcessor is attempting to cast every STRING that contains only digits, no matter how long this string is (I could easily overflow 64-bit PHP as well)".

**Comment by staudenmeir** [comment]
> I could easily overflow 64-bit PHP as well

That would definitely be an edge case, but I can see the issue here.

Can you draft a PR for Laravel 7?

**Comment by rimace** [comment]
I would say if the `Model::$keyType` is set to `string`, lets handle the ID as string, but if it is set to `'int'` it needs to check if the returned value is inside of the range `PHP_INT_MIN` and `PHP_INT_MAX`. If the value is outside of that range it needs also to be handled as a string.
I'd say that this is more accurate than just checking the `Model::$keyType` value.

If not it should be documented that people should set `$keyType = 'string';` even if the type is a integer, when users/develoopers think the database's int values will have greater value than PHP can handle.

Just some thougts. I like the second (also suggested by @mdzhokanov ) better.
