### ISSUE TITLE
[6.0] No upgrade path for authentication, NOT CSS, authentication, and app.css missing on new install.

### ISSUE THREAD

**Issue by jimgwhit** [laravel/framework#29829]
Login in version 5.8 comes with app.css when you scaffold authentication.  Besides app.css I also have custom css for other views.

However I use the app.css for styling the login and register as is "out of box"

In another issue I got this for an answer:

> This is only for new Laravel 6 apps. Existing apps are unaffected.

Wouldn't an upgrade from:

#### 5.8 to 6.0

Be considered a new 6.0? Again, since this is an upgrade to 6.0, thus it should be considered as a new 6.0 after a proper upgrade,  there is nothing as to how to properly handle app.css.

Also I still don't understand why app.css needs compiling, as it's required to compile it in 6.0.

6.0 left out any sentence to the effect:

> Compiling assets is optional.

I have used Laravel since ver 4.2 and compiling assets has never been mandatory.

If you search the chapter on authentication for the following words:

* compile 
* mix 
* sass 
* less 
* node 

None of those words show up.

The chapter does say:

> The ui command will also create a resources/views/layouts directory containing a base layout for your application. All of these views use the Bootstrap CSS framework, but you are free to customize them however you wish.

So according to the chapter on authentication, this layout should be ready to use out of box without compiling anything.  There should at least be the standard app.cs as was in previous versions.

Yet even when I tested a new install, there was no app.css, yet in the layout it's calling for app.css.

The authentication chapter says nothing about having to compile anything.

One single file used for login and register to style, app.css, should be there ready to go, and should not have to be compiled.

Can more than one person look over this issue as having to compile one file only doesn't make sense.

That is forcing someone to have to install node js and npm.  Having to install two extra programs to only compile one single file?

**Comment by devcircus** [comment]
I've been following all of your posts trying to understand, but just can't follow. If you upgrade, nothing changes, only your vendor which has nothing to do with your css. Compiling is never required. Concerning a new project, if you don't want to use any build tools, just drop your css in public and go to town. Also can't figure out why you seem to be the only one bringing this up. I could be missing something, but I've upgraded several apps, a couple of which do not use build tools, and everything just works.

**Comment by jimgwhit** [comment]
> just drop your css in public and go to town.

That does make sense, however in a brand-new install then, how do you get app. CSS.

You want the new one not an older one.

Seems you have to compile for that to be generated.

What I did on a new install is download bootstrap. CSS copy renamed to app.css.

Is this the correct way if not compiling assets.

**Comment by RFreij** [comment]
> What I did on a new install is download bootstrap. CSS copy renamed to app.css.

You can do exactly that.

Still, to always have the "most up-to-date" bootstrap css file for example, having it in package.json and compile it will always be best option since you don't have to download new versions yourself

**Comment by jimgwhit** [comment]
@RFreij  thanks for the reply.  I figured that.  Weird that the docs for 5.8 had:
```
php artisan preset none
```
Yet 6.0 says nothing about compiling assets is optional.  Yes an experienced person knows this.  But in a fresh install, and a fresh scaffolded Auth, it would be nice to have the app.css "out of box" like previous versions had.

And app.css never needed compiling in the past.  
The issue is there in no app.css out of box, it's only generated once you compile.
I can't seem to get that point across.

It seems as though the developers are in essence:

> Forcing new to laravel folks to compile and use mix.  Those that don't realize it's optional.

If that is the case, not saying it is, why don't someone just say:

"Yes that's the case".  At least then I will know there is no true issue.  But if that's not the case, new to laravel folks should at least see that compiling assets is very optional.

I can see it on a large app, but smaller apps (intranets) I can't see having to compile custom css.

At least let me know the intent of not letting some know, "Hey compiling is optional".

**Comment by rs-sliske** [comment]
whats the big problem with having to "compile" the css?

also i think part of the confusion here is you keep going on about "upgrade". while this has nothing to do with upgrading, it will only effect brand new laravel 6.0 apps

**Comment by jimgwhit** [comment]
> it will only effect brand new laravel 6.0 apps 

I know.  I want, wish someone couls answer this:

Are the developers forcing compiling assets now on those new to laravel, who may not realize it's optional. As npm was never required in the past.

I've been doing this stuff 32 years now, so I know better.

Just answer the simple question:

Is it yes or no.

If yes, there's no issue, if no there needs to be at least a sentence to let newbie's know it's optional.

Please just be frank, please.
