### ISSUE TITLE
Route Resource in Route Group with Prefix only loads index method of resource controller 

### ISSUE THREAD

**Issue by taghwo** [laravel/framework#29834]
- Laravel Version: 5.8.*
- PHP Version: 7.1.3
- Database Driver & Version:

### Description:
Route Resource in Route Group with Prefix only loads index method of Resource Controller. 
Index method loads fine , trying to access create & show methods redirects to '/home'. 

### Steps To Reproduce:

Route::group(
    [
    'namespace' => 'Admin',
    'prefix' => 'admin',
    ],
     function ) {
         
    Route::resource('complaints', 'ComplaintController');
    
	});
	
Route List
         
| GET|HEAD  | admin/complaints                  | complaints.index         | App\Http\Controllers\Admin\ComplaintController@index   

| GET|HEAD  | admin/complaints/create           | complaints.create        | App\Http\Controllers\Admin\ComplaintController@create  

Removing prefix loads all methods as it should.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
