### ISSUE TITLE
Str::slug() not working with other characters aside english

### ISSUE THREAD

**Issue by GabMic** [laravel/framework#29835]
- Laravel Version: 5.8.34
- PHP Version: 7.2.11

### Description:

I am trying to use `Str::slug()` with another language than English(Hebrew in my case), but it is not working.
while `$request->title` is in Hebrew, the following will not return anything:
`Str::slug($request->title);`
But with English, it will.

I have also tried this form, but also not working:
`Str::slug($request->title, '-', 'he');` 

### Steps To Reproduce:
Just send a Hebrew sentence to `Str::slug()`;

An example sentence(actually says 'this is a system test'): 

> זה ניסיון מערכת

Thanks for the help.

**Comment by driesvints** [comment]
Think we need to add those characters here: https://github.com/laravel/framework/blob/5.8/src/Illuminate/Support/Str.php#L737-L763

If you could send in a PR, that'd be great. Don't speak Hebrew myself 😅

**Comment by driesvints** [comment]
Also: 8.3.4 isn't a Laravel release. Did you mean a different version?

**Comment by GabMic** [comment]
> Also: 8.3.4 isn't a Laravel release. Did you mean a different version?

Oh, haha i have updated the version.

**Comment by GabMic** [comment]
> Think we need to add those characters here: https://github.com/laravel/framework/blob/5.8/src/Illuminate/Support/Str.php#L737-L763
> 
> If you could send in a PR, that'd be great. Don't speak Hebrew myself 😅

I will try it right now.

**Comment by GabMic** [comment]
Added this pull request:
https://github.com/laravel/framework/pull/29838
