### ISSUE TITLE
Add ability to disable pivot columns in select statement for many to many relationship "belong to many"

### ISSUE THREAD

**Issue by drmovi** [laravel/framework#29836]
in belong to many relationship every query should include the aliased foreign keys of the pivot table, this may cause problems when using GROUP BY, suggest add function in builder to remove these columns in select statement 
Thanks

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
