### ISSUE TITLE
Laravel 6 VerifyEmails.php hash parameter not detected

### ISSUE THREAD

**Issue by aadlung** [laravel/framework#29844]
- Laravel Version: 6.0
- PHP Version: 7.2.x

### Description:
After switching to Laravel 6 from 5.8 - the file framework/src/Illuminate/Foundation/Auth/VerifiesEmails.php was updated.

It now includes:
```php
if (! hash_equals((string) $request->route('hash'), sha1($request->user()->getEmailForVerification()))) {
  throw new AuthorizationException;
}
```

For some reason, the `$request->route('hash')` is `null`- I assume some signed-url-macros remove those parameters upfront? Because the `hasValidSignature()` works when debugging.

The verify method is called from the route
```php
Route::get('email/verify/{id}', 'Auth\VerificationController@verify')->name('verification.verify')->middleware('localization');
```

I am not aware of any other changes I did in this manner - as I've just migrated to the built-in e-mail validation a few minor versions ago.

### Steps To Reproduce:
Create a user with "verify mail" workflow.
The user gets logged in automatically (usually).
Clicking the "Verify Email Address" leads to a 403 error.

**Comment by aadlung** [comment]
I just realized that my installation creates verification URLs like that:

https://www.example.com/email/verify/12?expires=1567525923&hash=bb...&signature=e2b08e0d....

A fresh Laravel install generates URLs like that:

https://www.example.com/email/verify/3/6b665e9.....?expires=1567525840&signature=37a24f19dff2....

So I will check my installation where I generate this URLs in the mail - probably a leftover from the *laravel-email-verification* package I used before

**Comment by driesvints** [comment]
Feel free to reply once you figure things out 👍

**Comment by aadlung** [comment]
The issue was an old (manual) route for the E-Mail verification:
`email/verify/{id}`
In the current version, it is:
`email/verify/{id}/{hash}`
This probably only happens because I use the rules manually, and not `Auth::routes(['verify' => true]);`

**Comment by petersowah** [comment]
I am having this same issue. I am upgrading to Laravel 6 from 5.8. The hash parameter is missing in the verification url. Please see below for verification url generated.

https://app.test/email/verify/22?expires=1568134180&signature=00206fcf354e3c3ce4984d57ee0ff9ad6eaf6eb51dd6fe795c1299ce6f0fceae

@aadlung any luck with this?

**Comment by aadlung** [comment]
Hi @petersowah ,

it also ocurrewd on reddit: https://www.reddit.com/r/laravel/comments/d0ocrf/laravel_60_custom_email_verification_change_not/

So I just added the new routes and it should work - I am not sure but I think the verification package

And I use the following URL in the e-mail template:
`{{ url('user/verify', $user->verifyUser->token) }}`

Regards,
Andy

**Comment by petersowah** [comment]
Thanks @aadlung

**Comment by garygreen** [comment]
This was a pretty big breaking change when upgrading to 6.x - Taylor has merged a PR which adds some notes to the upgrade guide about this change: https://laravel.com/docs/6.x/upgrade#email-verification-route-change
