### ISSUE TITLE
[5.8.35] DelegatesToResource error

### ISSUE THREAD

**Issue by matthewnessworthy** [laravel/framework#29858]
- Laravel Version: 5.8.35
- PHP Version: 7.2.22
- Database Driver & Version: MySQL 5.7.27

### Description:

The change in https://github.com/laravel/framework/commit/dbb3b8c7f503f872d63b0fd8aecfcc60b1a19ca8#diff-051f4207f04389c85d22b75ab28c71a6R53 as part of https://github.com/laravel/framework/pull/29842 now causes an error
`Cannot use object of type Horizon\\Results\\ListingResult as array`

**Comment by driesvints** [comment]
We've identified that this error is triggered when a resource doesn't extends JsonResource object (that implements `ArrayAccess`). 

@matthewnessworthy I can't find this class in Horizon. Is this a class you created in your own app?

**Comment by matthewnessworthy** [comment]
This is unrelated to Laravel's Horizon project.

I've since modified the resource to implement `ArrayAccess`

For me, the issue no longer exists

**Comment by driesvints** [comment]
Perfect. Thanks!
