### ISSUE TITLE
[6.0] Wrong API version referenced with links in facades

### ISSUE THREAD

**Issue by jimgwhit** [laravel/framework#29857]
I wanted to do a pull request, but I do not know where Taylor gets the version variable for the docs.
```
{{version}}
```
In the 6.0 docs Facade chapter there are links to the API under:

### Facade Class Reference

It is giving links like:
```ruby
https://laravel.com/api/6.0/Illuminate/Foundation/Application.html
```

### But the actual links are:
```ruby
https://laravel.com/api/6.x/Illuminate/Foundation/Application.html
```

### 6.x not 6.0 for the API.

Again I couldn't  do a PR on this, I have no idea where the version variable comes from.
And the docs does not have an issue section.

Unless you are planning to change the API to 6.0.

**Comment by narwy** [comment]
`6.x` relates to the 6.x branch. So this is correct for the docs.

The current release version is 6.0.0.

**Comment by driesvints** [comment]
Heya, thanks for spotting this. We're aware. We're going to move the docs to 6.x links soon (while keeping redirects to 6.0) soon so better reflect the versioning scheme.

**Comment by Vusys** [comment]
This is also a problem on the contacts page:

https://laravel.com/docs/6.0/contracts#contract-reference

**Comment by driesvints** [comment]
@Vusys that's because we deleted the 6.0 branches on the illuminate repos. We're gonna rename the docs soon.
