### ISSUE TITLE
Blade bug with @lang directive

### ISSUE THREAD

**Issue by MaksTech** [laravel/framework#29859]
- Laravel Version: 6.0.0
- PHP Version: 7.2.19

### Description:
On Laravel 6, using `@lang` directive will throw ViewException. (`Method Illuminate\Translation\Translator::getFromJson does not exist`).
Because `@lang` directive renders as `app('translator')->getFromJson('...')` which was [removed](https://laravel.com/docs/6.0/upgrade#get-from-json) in this update.

### Steps To Reproduce:
Simply try to use `@lang` directive with not existing key.

**Comment by mnabialek** [comment]
Try tun run `php artisan view:clear` - it should solve the problem.
