### ISSUE TITLE
Timezone validation does not check timezone_identifiers_list()

### ISSUE THREAD

**Issue by jamesk322** [laravel/framework#29867]
- Laravel Version: LATEST

### Description:
The documentation states that the validation rule validates against `timezone_identifiers_list()` however the actual check uses `DateTimeZone()` which accepts a number of other identifiers not included in `timezone_identifiers_list` like "GB"

**Comment by driesvints** [comment]
"GB" isn't a valid timezone from that list: https://3v4l.org/FlTli

**Comment by jamesk322** [comment]
@driesvints Yes that's my point

**Comment by driesvints** [comment]
Ah I see. Atm we don't support this. Feel free to open an issue at the ideas repo or send in a PR if you believe this could be a good enhancement.

**Comment by jamesk322** [comment]
@driesvints I think we're on different pages. The issue is that the framework does currently allow "GB" when it shouldn't because it is not in the array of allowed timezones that you shared

**Comment by jamesk322** [comment]
I think the actual solution is to check if the supplied timezone is in the array returned from `timezone_identifiers_list()` instead of catching an exception thrown from `DateTimeZone` as the valid timezones are different in each

**Comment by jamesk322** [comment]
I'm happy to submit a PR for this :)

**Comment by driesvints** [comment]
I see! Thanks for explaining that. That indeed doesn't seems wanted. Maybe instead of changing the behavior we should update the docs?

**Comment by jamesk322** [comment]
I considered that, I think the best option though is to update the code as the timezones which are different between the two are the ones that are listed here https://www.php.net/manual/en/timezones.others.php

In that documentation PHP has issued a depreciation warning

**Comment by driesvints** [comment]
Hmm, that's a very good remark. Although I think that doing this on the current stable release might be unwanted. I'll run this over with the rest of the team and get back to you.

**Comment by jamesk322** [comment]
👍

**Comment by jamesk322** [comment]
@driesvints Did a decision get made on this?

**Comment by driesvints** [comment]
@jamesk322 let's send this to the master branch.

**Comment by jamesk322** [comment]
Ok, I'll get a PR together where `DateTimeZone` is switched for a check on `timezone_identifiers_list()`
