### ISSUE TITLE
Attach not refreshing the attached records

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [laravel/framework#29868]
Hi, i'm using Tinker to test my models, and whenever i attach something to a model, i need to exit tinker and then reopen it in order to find that record.
Example
tables: user -> user_order <- order
```php
$u=User::first();
$u->orders()->attach(Order::first());
$u->orders; // here no elements are displayed
```
Is this the supposed behavour? if yes, which method should i use to have always the right current associated records?
I'm using laravel 5.7.28

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
