### ISSUE TITLE
[6.0] PHPUnit can only be run from project root

### ISSUE THREAD

**Issue by marvinrabe** [laravel/framework#29862]
- Laravel Version: 6.0.0
- PHP Version: 7.3.2
- Database Driver & Version: Not important.

### Description:

Since Laravel 6 I cannot run any test with the PHPStorm PHPUnit test runner. The process dies with the following error message

```
Testing started at 00:01 ...
/usr/local/Cellar/php/7.3.4_1/bin/php /Users/marvin/Sites/test6/vendor/phpunit/phpunit/phpunit --configuration /Users/marvin/Sites/test6/phpunit.xml --teamcity

In PackageManifest.php line 168:
                                                               
  The bootstrap/cache directory must be present and writable.  
                                                               

Process finished with exit code 0
```

The folder `bootstrap/cache` is writable.

When I run phpunit from the Terminal everything works as expected.

### Steps To Reproduce:

1. Install PHPStorm (2019.2)
2. Create new Laravel 6 project with `laravel new`
3. Open Project in PHPStorm
4. Setup PHPStorm PHPUnit Testrunner with default `phpunit.xml` file and PHPUnit from `vendor/autoload.php`
5. Run Tests

**Comment by marvinrabe** [comment]
Writing this Issue I noticed that I have to specify the working directory in the Testrunner options of PHPStorm. In prior versions this was optional and in most cases not needed.

To fix the above error configure it like this:

<img width="1044" alt="Bildschirmfoto 2019-09-05 um 00 07 58" src="https://user-images.githubusercontent.com/515860/64295538-a6e83280-cf71-11e9-8be3-9c2d0356b9ef.png">

Change the `Custom working directory` accordingly.

**Comment by marvinrabe** [comment]
Should this be added to the Migration guide?

**Comment by mfn** [comment]
FTR it works for me (Laravel 6, PhpStorm 2019.2, phpunit 8.3.4) and I **don't** have an explicit "Custom working directory":
![image](https://user-images.githubusercontent.com/87493/64328881-8ac6ae80-cfce-11e9-8c47-293fd2379485.png)

![image](https://user-images.githubusercontent.com/87493/64328972-b6499900-cfce-11e9-8815-914ae82033a6.png)

But maybe because of the explicit path to the phpunit XML?

**Comment by driesvints** [comment]
I think this is related to https://github.com/laravel/laravel/pull/5050 but not sure what would exactly cause it. @timacdonald any ideas?

**Comment by nhedger** [comment]
Could this be related to the fact that in `Illuminate\Foundation\Application.php` the paths are resolved from `$this->bootstrapPath()` (which returns an absolute path) when executed normally but seem to be taken _as is_ from the `APP_CONFIG_CACHE` variable and others when running tests ?

```php
/**
 * Get the path to the configuration cache file.
 *
 * @return string
 */
public function getCachedConfigPath()
{
    return Env::get('APP_CONFIG_CACHE', $this->bootstrapPath().'/cache/config.php');
}
```

**Comment by danijelk** [comment]
Just a notice, that the new tests/bootstrap.php file crashes brianium/paratest package which runs tests in parallel.

**Comment by driesvints** [comment]
FYI: can you all try to revert the changes from here to see if that fixes your problems? https://github.com/laravel/laravel/pull/5050

**Comment by bastien-phi** [comment]
I did a PR on https://github.com/laravel/laravel/pull/5071 to fix the issue but it has been closed

Another solution is to update phpunit.xml file with absolute paths

**Comment by nhedger** [comment]
@driesvints I tried reverting and it did solve the problem. Using absolute paths in phpunit.xml also solves the problem but does not feel intuitive because all other paths in this file are relative to the root of the project.

I believe my solution (posted above) is the way to go because it forces the resolution of these paths to be done relative to the root of the project. This way, the new functionality is kept while no modifications are needed in the phpunit.xml file.

**Comment by devfrey** [comment]
Specifying an explicit configuration file path solved it for me (as mentioned by @mfn).

**Comment by timacdonald** [comment]
Hey everyone, sorry this PR has caused you these issues for you. Hopefully we can find a speedy solution (even if it requires removing the functionality).

There seems to be a few things here, so I'm gonna spend some time today digging in to see if we can find a good solution to the problems.

1. PHPStorm is setting a cwd that isn't the root file when running tests
2. ParaTest is crashing

I have previously confirmed that `vim-test` and `sublime-phpunit` are working as expected, but I will also re-confirm this with a fresh install now that Laravel 6.0 is out.

I also read previously that PHPStorm, in their docs at least, specify that the CWD is always to project root. So perhaps there is something else going on here. I will track this down again.

I will report back as I dig into this. My apologies that this is impacting all of your workflows!

**Comment by timacdonald** [comment]
> I also read previously that PHPStorm, in their docs at least, specify that the CWD is always to project root. So perhaps there is something else going on here. I will track this down again.

**Custom working directory**
... _By default, the field is empty and the working directory is the root of the project._

Source: https://www.jetbrains.com/help/phpstorm/run-debug-configuration-phpunit.html

I'm yet to actually verify this. Still digging into some possible solutions.

**Comment by timacdonald** [comment]
Think I've found a non-breaking fix. Will report back shortly.

**Comment by timacdonald** [comment]
Just did up the PR. Can anyone confirm this fixes the issue. It does for PHPUnit and ParaTest on my end.

https://github.com/laravel/framework/pull/29890
