### ISSUE TITLE
Gate only checks the first object of given array

### ISSUE THREAD

**Issue by sahandseifi** [laravel/framework#29870]
- Laravel Version: 5.5.45
- PHP Version: 7.2.0

When an array of objects are passed to Gate::allows or to the authorize method of AuthorizesRequests, the policy method on the policy class is invoked with only the first object of the array. 

In the example below, the "edit" method is called only once and the $objects parameter would be the first object of the $entities array.

```
// MyController.php

$entities = [$object1, $object2];
$this->authorize('edit', $entities);
```

```
// ObjectPolicy.php

public function edit($user, $objects) {
   return false;
}
```

So if the user is allowed to edit $object1 but not allowed to edit $object2, the authorization would pass solely based on the first object of the array.

I believe this is caused by the spread syntax used in the Gate.php class:

```
protected function callAuthCallback($user, $ability, array $arguments)
    {
        $callback = $this->resolveAuthCallback($user, $ability, $arguments);
        return $callback($user, ...$arguments);
    }
```

I am not sure if this is the expected behavior or not, but it seems non-intuitive.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
