### ISSUE TITLE
HasInDatabase::getAdditionalInfo() crashes on huge tables

### ISSUE THREAD

**Issue by panzi** [laravel/framework#29876]
- Laravel Version: 5.7.28
- PHP Version: 7.3
- Database Driver & Version: MariaDB 10.3

### Description:
`Illuminate\Foundation\Testing\Constraints\HasInDatabase::getAdditionalInfo()` does:
```SQL
        $results = $this->database->table($table)->get();

        if ($results->isEmpty()) {
...
        if ($results->count() > $this->show) {
...
```
Instead of just:
```SQL
        $count = $this->database->table($table)->count();

        if ($count === 0) {
...
        if ($count > $this->show) {
...
```
Which crashes on certain huge tables because it tries to load all the rows into memory even though it only needs the count.

**Note:** What makes it worse is that in this case PHP crashes without any message and just the exit code 255. I had to printf-debug the issue littering the framework code with echos.

### Steps To Reproduce:
Do a `$this->assertDatabaseHas()` that fails to find a row in a huge table.

**Comment by staudenmeir** [comment]
> even though it only needs the count.

`getAdditionalInfo()` fetches more than the count because it displays the first x records in the error message. We can improve the method by not fetching *all* records, but we still need to fetch *some* of them.

**Comment by panzi** [comment]
Sure! Just fetching all of them crashes for huge tables without message or trace and is a hassle to debug.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by panzi** [comment]
One look into the current source would have showed you that the body of this function didn't change *at all* since then: https://github.com/laravel/framework/blob/2f20d8875f0473d10e15e82a11a71c92a4c59864/src/Illuminate/Foundation/Testing/Constraints/HasInDatabase.php#L76

So the bug still exists and still has to be fixed.

**Comment by panzi** [comment]
This should fix it: https://github.com/laravel/framework/commit/0c325b6a686543b09279191691336b6ca9ee62cf
