### ISSUE TITLE
Composer create project does not use Ignition error page.

### ISSUE THREAD

**Issue by windstep** [laravel/framework#29889]
- Laravel Version: 6.0.0
- PHP Version: 7.3.0

### Description:

`composer require --prefer-dist laravel/laravel projectname` does not use Ignition instead of Whoops 5** error screen

### Steps To Reproduce:

Create new project by the command above. Write a code with error.

**Comment by driesvints** [comment]
This is because it's included in 6.0.1 of the skeleton which hasn't been tagged yet. I'll tag a new release today.

**Comment by driesvints** [comment]
You can get it if you use the laravel installer btw

**Comment by ankurk91** [comment]
Agree,
Version 6 was tagged 10 days ago, and it does not have `Ignition` in composer.json

https://github.com/laravel/laravel/releases
