### ISSUE TITLE
Defining $with on an Eloquent model will eager load separately for each item

### ISSUE THREAD

**Issue by JakeBooher** [laravel/framework#29883]
- Laravel Version: 5.8.34
- PHP Version: 7.3.8
- Database Driver & Version: MariaDB 10.4

### Description:

When defining `protected $with = ['users'];` (which is a `belongsToMany` relationship), for example, on my `Object` (just an example, not the actual name) when doing something along the lines of `Object::where('some_conditional', 'value')->limit(10)->get()` it will load the correct values from `objects`, but will do a separate query in `users` for each individual `object` whereas if I do `Object::with(['users'])->where('some_conditional', 'value')->limit(10)->get()` it will not.

Also, if I have the `$with` defined on the model and do the where separately in the query it'll load all of them as you would expect with the bulk eager load, but then reload all of them again on each `object`

### Steps To Reproduce:

app/Models/Object.php
```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Object extends Model
{
    protected $with = ['users'];
    
    public function users()
    {
        return $this->belongsToMany(User::class);
    }
}
```

then request the data using the Eloquent query builder methods I provided above

**Comment by staudenmeir** [comment]
What's your Laravel version?

**Comment by JakeBooher** [comment]
Sorry, could've sworn I pasted that in. Updated my original message!

**Comment by staudenmeir** [comment]
This must be caused by something (e.g. a package) in your application. The feature has always been working and I don't see how you could be the only affected by this issue.

Can you reproduce it on a fresh Laravel installation?

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.
