### ISSUE TITLE
Redis hmget should not remove keys

### ISSUE THREAD

**Issue by joshua-se** [laravel/framework#29881]
* Laravel Version: 5.* 
## Description:
Redis hashmap multi retrieval preserves the keys/fields for the values in it and laravel for some unknown reason removes them with array_values. Shouldnt the connectors try to return as much data as possible and allow users to decide

https://github.com/laravel/framework/blob/5.8/src/Illuminate/Redis/Connections/PhpRedisConnection.php#L111

**Comment by driesvints** [comment]
Please fill out the issue template.

**Comment by joshua-se** [comment]
I should perhaps create a pull request to remove the unneccessary array_values.
