### ISSUE TITLE
Artisan command --env=testing is dual purposed and can override itself

### ISSUE THREAD

**Issue by spencero91** [laravel/framework#29887]
- Laravel Version: 5.8.29

### Description:
When needing to run an artisan command using an alternate `.env` file Laravel offers the option `--env=alternate` to use `.env.alternate` instead of `.env` however this will also overwrite the `APP_ENV` variable inside `.env.alternate` with "alternate" which doesn't make sense. Why would you override a property called `APP_ENV` inside a file that is being used to override another similar file with the same command option. It makes the property "nearly" entirely useless inside the new `.env` file. (It is still accessible via `config('APP_ENV')`, but not via any of the `app()` environment accessors.)

### Steps To Reproduce:

1. Make an alternate `.env.testing`
2. Set the `APP_ENV` value to "asdf" (anything other than "testing" will demonstrate the problem)
3. Make an Artisan command that has the following lines in the "body"
```
        echo config('app.env') . PHP_EOL;
        echo app()->env . PHP_EOL;
```
4. Run any Artisan command with the option `.env.testing`

This should clearly demonstrate that this causes a discrepancy between config and the environment variables. And that the command parameter is overriding the `.env.testing`'s value that we are trying to use to override the `.env`'s value.

**Comment by spencero91** [comment]
I've found ways around this issue in my scenario. But I feel like this is a logical fallacy in having a feature that is so dual purposed as to contradict itself. Either the feature should override just the APP_ENV value or it should allow the selection of an alternate .env file. But selecting an alternate .env file and then overriding the APP_ENV value with the name of the file (arguably the most important value in the file) with the name is rather restricting and counter intuitive.

**Comment by RFreij** [comment]
#28982 And #28854 might be related

**Comment by driesvints** [comment]
Hey @spencero91. Please see the links that @RFreij posted to the reasoning behind this behavior.
