### ISSUE TITLE
phpDoc for Request::validate

### ISSUE THREAD

**Issue by denirun** [laravel/framework#29894]
Hi, can you please finally add for `lluminate\Http\Request::validate` phpDoc. You officially suggest to call this method for Request class, but because this is macros. IDE like PhpStorm don't understand this **method**. Can you please add something like this. 

```
namespace Illuminate\Http;

/**
 * @method array validate(array $rules)
 */
class Request extends SymfonyRequest implements Arrayable, ArrayAccess
``` 

It will be very useful, for IDE and autocompletion. If you add this tiny phpDoc above the class Request implementation. My IDE always show me warnings... very annoying. :)

Thank you! Very waiting.

**Comment by driesvints** [comment]
If you feel that something should be added feel free to send in a PR.
