### ISSUE TITLE
Eloquent model with compound primary key not deleted

### ISSUE THREAD

**Issue by VokaMut** [laravel/framework#29893]
- Laravel Version: 5.8.34
- PHP Version: 7.3.8
- Database Driver & Version: MariaDB 10.0.38

### Steps To Reproduce:
```
use Illuminate\Database\Eloquent\Model;

class NewsLike extends Model
{
    protected $primaryKey = ['news_id', 'fingerprint'];
    public $incrementing = false;
    public $timestamps = false;
}

$newsLike = NewsLike::firstOrNew([
    'news_id' => $request->id,
    'fingerprint' => fingerprint(),
]);

if ($newsLike->exists()) {
    $newsLike->delete(); // ErrorException
}
```

Error:

> "message": "Illegal offset type",
    "exception": "ErrorException",
    "file": "/var/www/site.local/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php",
    "line": 775,

Full log: https://pastebin.com/pTBXLDcQ

**Comment by staudenmeir** [comment]
Laravel doesn't support composite primary keys.

**Comment by driesvints** [comment]
Sorry, this is not supported.
