### ISSUE TITLE
VerificationController view customization not available

### ISSUE THREAD

**Issue by zeeforumcompany** [laravel/framework#29903]
- Laravel Version: 6.0
- PHP Version: 7.2.8
- Database Driver & Version: 10.1.21-MariaDB

### Description:
I'm creating Laravel authentication with email verification. But when I customize the blade view for verification controller using show function it does not work.

Here is my code Auth\VerificationController.php:

```
<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\VerifiesEmails;
use Illuminate\Http\Request;

class VerificationController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Email Verification Controller
    |--------------------------------------------------------------------------
    |
    | This controller is responsible for handling email verification for any
    | user that recently registered with the application. Emails may also
    | be re-sent if the user didn't receive the original email message.
    |
    */

    use VerifiesEmails;

    /**
     * Where to redirect users after verification.
     *
     * @var string
     */
    protected $redirectTo = '/client/dashboard';

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {die('END');
        $this->middleware('auth');
        $this->middleware('signed')->only('verify');
        $this->middleware('throttle:6,1')->only('verify', 'resend');
    }

    public function show(Request $request)
    {
        die('NO');

        return $request->user()->hasVerifiedEmail()
                        ? redirect($this->redirectPath())
                        : view('auth.verify');
    }
}
```

### Steps To Reproduce:
- I have created show function in app\Http\Controllers\Auth\VerificationController.php 
- In File I just created show function to give it my view.
- But it's not working when I visit the email/verify route.
- It should print "END" or "NO" but it's not working.
- It still showing me the default page.

**Comment by mishbah** [comment]
how about the router ?
try check the routers via `php artisan route:list`
and post the output here

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
