### ISSUE TITLE
[6.0] Laravel stable release

### ISSUE THREAD

**Issue by jimgwhit** [laravel/framework#29907]
Laravel doesn't have an issue section, so I am making one here.

Where is the stable release for laravel, the version that goes with 6.0 of the framework?
Yes I know I can get it from master, But---

This https://github.com/laravel/laravel/releases used to be maintained, and is where I would go to get the latest stable release.

What happened?  If laravel 6.0 framework is out, shouldn't there be a stable release of Laravel as well for that version?

Are you guys just a little behind and have to catch up, or is the stable release section going away?

Last stable is:  
v5.8.16

@driesvints driesvints released this on May 7

**Comment by brunogaspar** [comment]
While the releases are nice, the important bits are the tags https://github.com/laravel/laravel/tags, and the 6.0.x tags are there, so you can download them i guess.

**Comment by GrahamCampbell** [comment]
The best place to look is the upgrading guide in the docs, and to just do a diff via the GitHub branch comparison. That'll show you the exact differences between the version of the laravel/laravel app you started with, and the current default.

**Comment by jimgwhit** [comment]
Has tags replaced the release page.  Usually by now there is an update on release page?

And how did you find the tag page, I goto https://github.com/laravel/laravel and clik releases.

Why would there be a release page and a tag page.

I know the release page is supposed to be stable.  But is the tag page stable?

Thanks

**Comment by GrahamCampbell** [comment]
There will probably be releases too. GitHub's UI isn't very hepful. Tags are effectively releases, just with no extra data attached to them in the UI. Tags function as "releases" in the natural language sense of the word.

**Comment by jimgwhit** [comment]
@GrahamCampbell

From this page https://github.com/laravel/laravel how do you find https://github.com/laravel/laravel
 https://github.com/laravel/laravel/tags page

**Comment by brunogaspar** [comment]
There's 2 tabs

![Screen Shot on 2019-09-08 at 01-23-17](https://user-images.githubusercontent.com/2285372/64481607-51ad5a80-d1d7-11e9-9e40-a05b3b3a80b9.png)

Also you can see the newer tags link right below too.

**Comment by jimgwhit** [comment]
Page in my browser has php  framework  laravel 

Not Realeases   Tags

Why am I missing that?

**Comment by brunogaspar** [comment]
You just need to go to the releases page, then you can see the "Releases" and "Tags" tabs/subnav.

**Comment by jimgwhit** [comment]
https://i.imgur.com/XPIdJhs.jpg

**Comment by brunogaspar** [comment]
There's a releases link there, `96 releases`, click on it.

**Comment by jimgwhit** [comment]
Found it, so those tags are only laravel, not framework?

**Comment by driesvints** [comment]
I'll do the releases today. Last week was a little bit crazy.

**Comment by driesvints** [comment]
Updated the releases: https://github.com/laravel/laravel/releases
