### ISSUE TITLE
[6.0] Error display broken for view error with mix.browserSync

### ISSUE THREAD

**Issue by kylekatarnls** [laravel/framework#29909]
- Laravel Version: **6.0.1**
- PHP Version: **7.3.5**

### Description:
Raw display of JS file on view error:
![image](https://user-images.githubusercontent.com/5966783/64488139-899eb700-d244-11e9-8639-468ed32b70c7.png)

### Steps To Reproduce:
- Fresh install of Laravel 6.0
- Add `mix.browserSync({proxy: 'localhost:8000'});` to **webpack.mix.js**
- Replace **welcome.blade.php** content with `{{ 1/0 }}`
- Run `npm run watch`
- Open http://localhost:3000/

### Expected
The nice error display we have in http://localhost:8000/

### Observed
![image](https://user-images.githubusercontent.com/5966783/64488139-899eb700-d244-11e9-8639-468ed32b70c7.png)

**Comment by alec-joy** [comment]
This is an incompatibility between ignition and Laravel Mix's browsersync method, you can find a workaround on [this issue ](https://github.com/facade/ignition/issues/16) but it's not something that can be fixed in the laravel framework itself. There's an open PR for a fix on laravel mix

**Comment by driesvints** [comment]
Seems like it's best that this is an issue with Laravel mix

**Comment by kylekatarnls** [comment]
Transferred to https://github.com/JeffreyWay/laravel-mix/issues/2239
