### ISSUE TITLE
Str cascading

### ISSUE THREAD

**Issue by raftx24** [laravel/framework#29906]
Hi.
In many situations, we need to cascade some method in `Str` and it makes codes dirty.
For example, if we need to convert some word like testName to Test-Name we could do something like `Str::ucfirst(Str::snake('testName'))`. 
It can has more methods, and we Repeat Str:: Str:: each time and that makes our code ugly.
but if we have some methods like `do` in Str, we can have something like below
`Str::do('ucfirst.snake','testName')` .   
Of course, it makes code more readable and maintainable.
If you like it, then tell me to create a pull request for that.
Thank you.

**Comment by jimgwhit** [comment]
You can extend a class or have your own additional methods:  Just example in a controller I have:

```
$dogpic = Cln::fixValue($newname);
```

Which looks fine in the controller.

However the helper class called has:
```
    public static function fixValue($rvalue)
    {
        $rvalue = empty($rvalue) && !is_numeric($rvalue) ? NULL : trim(strip_tags($rvalue));
        return $rvalue;
    }
```

So you could easily extend php string functions and make any combination of added string helpers you need.

In fact laravel really don't need these helpers at all, could use php functions direct.

That's all Taylor is doing in the background in the vendor helper classes, using regular php to make helpers for you and me.  I'd rather see less helpers that php can do.

But things like the asset helper, I love that.

**Comment by derekmd** [comment]
You can start new feature discussions as an laravel/ideas thread: https://github.com/laravel/ideas/issues. This laravel/framework "Issues" tab is intended for bug reports.

https://laravel.com/docs/6.0/contributions#core-development-discussion

> "You may propose new features or improvements of existing Laravel behavior in the Laravel Ideas [issue board](https://github.com/laravel/ideas/issues)."

`Illuminate\Support\Str` class is macroable so you can define such a method yourself.

```php
// register this is AppServiceProvider
Str::macro('pipe', function ($value, $methods) {
    return collect($methods)->reduce(function ($value, $method) {
        return Str::$method($value);
    }, $value);
});
```

```php
>>> Str::pipe('testName', ['snake', 'ucFirst'])
=> "Test_name"
```

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!
