### ISSUE TITLE
Oracle Database Support

### ISSUE THREAD

**Issue by elislenio** [laravel/framework#29905]
It will be great to have Oracle as a supported DB so it is a must for building enterprise applications.
In the meantime I'd found a great proyect here https://github.com/yajra/laravel-oci8. I haven't tested yet for use whith schema migrations, in all other aspect it worked really well.

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!
