### ISSUE TITLE
Making models macroable

### ISSUE THREAD

**Issue by AmirrezaNasiri** [laravel/framework#29911]
`Macroable` trait is pretty useful when we have no control on a class however, it would be useful in scenarios in which we still have full control over the class, like custom models.

Being able to make models macroable will make our code much more readable in cases like testing environment in which we don't want to populate model with methods only used in testing.

Let me explain the need with an example:
Let say that we're going to test a model named `Video` and test if it the corresponding source file is being stored or not. So we usually define a method like this and call it in the test case:
```php
private function assertVideoSourceExists($video) { ... }
private function assertMissingVideoSource($video) { ... }
```

Now let say that we need the assertion in out of a single test case file. In this case, we usually extract assertions in a trait like `VideoAssertionTrait` or simply put them in `TestCase` file since test cases extend this one.

The problem comes in when we have more models (like `Audio`, `Music`, `Cover` and etc.) which might be related to each other and they all should be tested in single methods. So in these tests, our files will be full of these kind of method calls which I've actually seen in many projects:
```php
$this->assertMissingVideoSource($video);
// ...
$this->assertAudioSourceExists($extracted_audio);
$this->assertVideoSourceExists($video);
$this->assertCoverImageExists($cover);
```

I think it would be awesome and much more readable (since readability is important in tests) to do the assertions like this:
```php
$video->assertMissingSource();
// ...
$extracted_audio->assertSourceExists();
$video->assertSourceExists();
$cover->assertImageExists();
```

Accomplishing this readibility required models to be macroable (again, since we don't want to put test methods in the model itself) and being able to define them like this:
```php
Video::macro('assertMissingSource', function() {
   // assertion logic
})
```

The reduced code letters might not be that much but saying that a helper function like `tap()` makes it possible to[ get rid of temporary variable headaches](https://medium.com/@taylorotwell/tap-tap-tap-1fc6fc1f93a6), I think this can be useful to get rid of those redundant `$this` and model related letters in method names.

Of course, this is only an example out of other uses of macroable models in testing environment.

**Comment by 4n70w4** [comment]
https://github.com/laravel/framework/pull/31286
