### ISSUE TITLE
Unable to pass expression to join on clause

### ISSUE THREAD

**Issue by xorock** [laravel/framework#29918]
I'm trying to build query like:

```sql
SELECT
    *
FROM table1 AS ppu
JOIN table2 AS j 
    ON ST_DWithin(j.coordinates, ppu.coordinates, j.radius)
```

Because of 
```
if ($this->invalidOperator($operator)) {
    [$second, $operator] = [$operator, '='];
}
```

I'm unable to directly pass expression `ST_DWithin(j.coordinates, ppu.coordinates, j.radius)` to JOIN clause.

Workaround:
`$join->on(DB::raw('ST_DWithin(jobs.coordinates, ppu.coordinates, jobs.radius)'), '=', DB::raw('true'));`

Throwing exception will be big BC, so maybe there should be onExpression method?

PS. table1 is CTE expression (laravel-cte).

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by xorock** [comment]
It's not a question. When no operator is given whole query is automatically treated as an equal sign query, it is not possible to pass expressions as in the example without hacking the query. It is not even possible to specify TRUE directly, because it is then treated as 1 column in the query with exception thrown. I am guessing that correcting the behavior in which the lack of the operator is correct and converted into an equal sign is currently not an option. Maybe the onExpression() method should be created?

https://github.com/illuminate/database/blob/master/Query/Builder.php#L664

**Comment by devcircus** [comment]
Seems like an orm limitation that would be best solved by dropping down a layer. There are many database operations that are difficult to support in an abstraction. This may not be the case here and maybe this could be easily added, but currently looks more like a limitation than a bug. If you have an idea of how to add this without breaking any current functionality, it's a great opportunity for a PR.

**Comment by staudenmeir** [comment]
You can use all `where*()` methods on join clauses:

```php
$join->whereRaw('ST_DWithin(jobs.coordinates, ppu.coordinates, jobs.radius)');
```
