### ISSUE TITLE
Validator extend default method for Rule is  'validate' instead of 'passes'

### ISSUE THREAD

**Issue by Donkfather** [laravel/framework#29915]
- Laravel Version: 6.0.1, 5.8.35

### Description:
The default Rule class has 2 methods: `passes`,`message`
The extend method on Validator has `validate` as default method for Rules.

### Steps To Reproduce:
Create rule, Add `Validator::extend('rule',Rule::class)` to AppServiceProvider. Run code that uses the rule.

Is this desired or forgotten ?

**Comment by xuanquynh** [comment]
`Validator::extend` is designed to support `Closure` and `class@method` rule registration. `Rule` interface has been used since v5.5 and it is not for `Validator:extend`.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
