### ISSUE TITLE
[6.0] Job middleware not respected with `dispatchNow()`

### ISSUE THREAD

**Issue by erikgaal** [laravel/framework#29917]
- Laravel Version: 6.0.1
- PHP Version: 7.3.8

### Description:
In Laravel 6.0 job middleware was introduced. This works perfectly, except for when jobs are dispatched to be executed immediately using `dispatch_now()` or `Job::dispatchNow()`. Job specific middleware is never applied, as the `\Illuminate\Bus\Dispatcher::dispatchNow()` method never resolves the command specific middleware as the `\Illuminate\Queue\CallQueuedHandler::dispatchThroughMiddleware()` does.

### Steps To Reproduce:
```php
class MyJobWithMiddleware implements ShouldQueue
{
    public function middleware()
    {
        return [new MyMiddleware()];
    }

    public function handle()
    {
         //
    }
}

class MyMiddleware
{
	public function handle($command, $next)
    {
        dd('call me');
    }
}

dispatch_now(new MyJobWithMiddleware());
//

dispatch(new MyJobWithMiddleware());
// "call me"
```

**Comment by devcircus** [comment]
Seems like more of a feature request since the pull request explicitly states that the middleware is for queues jobs. https://github.com/laravel/framework/pull/29391#issue-303858409

**Comment by driesvints** [comment]
Heya, see the answer by @devcircus above.

**Comment by winkbrace** [comment]
Wow. But why? Sometimes I want to execute a job immediately, but always I want to execute the middleware.

**Comment by sharifzadesina** [comment]
This is not good. middleware should be always be executed.

**Comment by 4n70w4** [comment]
The same problem!

**Comment by sharifzadesina** [comment]
@driesvints What can we do about this?

**Comment by 4n70w4** [comment]
I found workaround:

```php
SomeJob::dispatch($arg1, $arg2, ...)->onConnection('sync');
```

**Comment by schaeferalex** [comment]
As this issue has been re-opened, will there be a way to ignore any job middleware when a job is being called with dispatchNow()? 

The documentation uses a rate limiter middleware as an example. When calling a job with dispatchNow() you very likely want to ignore any rate limit. 

Is there a way to determine if a job has been called with dispatchNow()?

**Comment by driesvints** [comment]
Taylor sent in a PR here: https://github.com/laravel/framework/pull/32559

**Comment by taylorotwell** [comment]
A new `dispatchSync` method is available in upcoming 8.x.
