### ISSUE TITLE
Validation in unique:'table'

### ISSUE THREAD

**Issue by Mahdi-Ba** [laravel/framework#29924]
- Laravel Version: "^6.0"
- PHP Version: 7.3.4-1
- Database mysql Ver 5.7.25-0

### Description:
I was using below validation in api Request But just this  **unique:users** Not Working and by pass.
I don't change any thing in model and migration user  
```
        $validator = Validator::make($request->all(), [
            'name' => 'required', 'string', 'max:255',
            'email' => 'required', 'string', 'email', 'max:255','unique:users',
            'password' => 'min:6|required_with:password_confirmation|same:password_confirmation',
            'password_confirmation' => 'min:6'
        ]);

        if ($validator->fails()) {
            return Response($validator->errors(),400);
        }
```

**Comment by devcircus** [comment]
your rules are not a valid php array. well technically it may be valid but php isn't interpreting it the way you think it is. You should do this one of two ways.
- Rules as a pipe delimited string
``` php
[
    'name' => 'required|string|max:255',
]
```
or Rules as an array
```php
[
    'name' => ['required', 'string', 'max:255'],
]
```
