### ISSUE TITLE
[6.0] Duplicate entry for primary key error when sending notifications to multiple users

### ISSUE THREAD

**Issue by jafar690** [laravel/framework#29928]
- Laravel Version: 6.0.0
- PHP Version: 7.3.1
- Database Driver & Version:

### Description:
When i try sending notifications to multiple users, i get this error 
```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'c6c5825a-ffdf-4721-9e3e-db1382000f57' for key 'PRIMARY' (SQL: insert into `notifications` (`id`, `type`, `data`, `read_at`, `notifiable_id`, `notifiable_type`, `updated_at`, `created_at`) values (c6c5825a-ffdf-4721-9e3e-db1382000f57, App\Notifications\BookedValuation, [], ?, 1, App\PartnerUser, 2019-09-10 07:05:05, 2019-09-10 07:05:05))
```
please note that the notification to the first user is completed before it fails

### Steps To Reproduce:
send notification to multiple users e.g
```
use Illuminate\Support\Facades\Notification;
use App\User;
...

$users = User::all();
Notification::send($users, new BookedValuation($data1, $data2));
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
