### ISSUE TITLE
phpredis function spop can't use param count

### ISSUE THREAD

**Issue by wenjy** [laravel/framework#29923]
- Laravel Version: 5.8.34
- PHP Version: 7.2.17
- Database Driver & Version:

### Description:

https://github.com/laravel/framework/blob/e04a7ffba8b80b934506783a7d0a161dd52eb2ef/src/Illuminate/Redis/Connections/PhpRedisConnection.php#L195

**Comment by driesvints** [comment]
Hmm yeah we'll need to add that. We'll need to make Redis 3.2 the minimum requirement for this though because it was added then: https://redis.io/commands/spop

**Comment by driesvints** [comment]
This is now fixed with https://github.com/laravel/framework/pull/30546
