### ISSUE TITLE
Tinker Crashing in Laravel 6.x

### ISSUE THREAD

**Issue by morpheus7CS** [laravel/framework#29921]
- Laravel Version: 6.0.1
- PHP Version: 7.3.9

### Description:
Tinker crashes inside a fresh Laravel installation.

### Steps To Reproduce:
1.  Create new project with `laravel new`command
2. Pull up Tinker with `php artisan tinker`
3. Type a command (e.g. `use Illuminate\Support\Str;`) and press Enter.

<img width="433" alt="Screenshot 2019-09-09 at 15 06 04" src="https://user-images.githubusercontent.com/8884582/64533496-ea48f500-d313-11e9-8a4e-3d82249c844d.png">

Kind regards,
g

**Comment by driesvints** [comment]
Hey @morpheus7CS. See https://github.com/laravel/framework/issues/27052
