### ISSUE TITLE
whereDate casting of Carbon unexpected behaviour

### ISSUE THREAD

**Issue by SlyDave** [laravel/framework#29939]
- Laravel Version: 5.7+
- PHP Version: 7.2
- Database Driver & Version: Mysql/MariaDb/Amazon Aurora

### Description:
whereDate() casting of Carbon objects causes unexpected results

`whereDate('starts_at', '>', new Carbon());`

becomes

`DATE('starts_at') > 2019-09-10`

becomes

`DATE('starts_at') > 2000`

This appears to happen because \Illuminate\Database\Query\Builder since 5.7 does:
```
WhereDate()....
if ($value instanceof DateTimeInterface) {
    $value = $value->format('Y-m-d');
}
```
But doesn't enclose the $value in quotes when passing it to the bindings.

A fix for this is to drop the minus symbols, so that `$value->format('Ymd')` is used, at least according to https://dev.mysql.com/doc/refman/8.0/en/date-and-time-literals.html

> Date and time values can be represented in several formats, such as quoted strings or as numbers, depending on the exact type of the value and other factors. For example, in contexts where MySQL expects a date, it interprets any of '2015-07-21', '20150721', and 20150721 as a date.

**Comment by SlyDave** [comment]
As a more real world example:
```
    public function __construct(Carbon $from, Carbon $to)
    {
        $this->from = $from->copy();
        $this->to   = $to->copy();
    }
```
...
```
return $builder->whereDate('starts_at', '<=', $this->to)
->whereRaw('DATE(IF(terminated_at, terminated_at, ends_at)) >= \'?\'', $this->from->format('Y-m-d'));
````
The whereRaw is working just fine, the wereDate does not.

**Comment by SlyDave** [comment]
@staudenmeir As the description demonstrates, although it could be more verbose, so here you go:

Actual:
whereDate casts a Carbon object into a string via `format('Y-m-d')` which is then assembled into the SQL `DATE('column') > Y-m-d` This string isn't encapsulated in quotes, so MySQL see it as an arithmetic expression, Y minus m minus d = value.

e.g.
`DATE('starts_at') > 2019-09-10` which MYSQL sees as arithmetic and turns into `DATE('starts_at') > 2000`
as you can see, start_at > 2000 isn't the same as start_at > 2019 so leads to many side effects.

Expected:
`DATE('starts_at') > '2019-09-10'` or `DATE('starts_at') > 20190910` or `DATE('starts_at') > '20190910'`

Hope that makes it clearer.

**Comment by staudenmeir** [comment]
Please provide a complete example with migration, sample data and query.

Are you overriding `PDO::ATTR_EMULATE_PREPARES`?

**Comment by SlyDave** [comment]
`Are you overriding PDO::ATTR_EMULATE_PREPARES`
Nope.

**Comment by staudenmeir** [comment]
Can you reproduce it on a fresh Laravel installation? I can't.

> This string isn't encapsulated in quotes, so MySQL see it as an arithmetic expression, Y minus m minus d = value.

Since Laravel passes the string as a binding, it doesn't need to be wrapped in quotes.

**Comment by SlyDave** [comment]
And that's why the problem occurs.  Please read the problem that's happening..

**Comment by SlyDave** [comment]
That's the core of the issue, because the time is being converted into a string with minus symbols in it, and it's not in a format that MySQL sees as a date, it does a mathematical operation on the string.

**Comment by staudenmeir** [comment]
Please do. I've never seen such behavior.

Even before Laravel introduced support for `DateTimeInterface` objects, people were successfully using `whereDate()` with `Y-m-d`-formatted strings.

**Comment by khalilst** [comment]
@staudenmeir This bug report is not correct and `whereDate` is working fine.

### Environement:
- Ubuntu 16.04
- Laravel 6.0
- MySql 10.3.14-MariaDB-1:10.3.14+maria~bionic

### Steps:

1. Install fresh Laravel 6.0
2. Go to tinker: `php artisan tinker`
3. Create 10 users: `factory(\App\User::class, 10)->create();`
4. Enable query log in MySQL using below command:
```
set global general_log=ON;
set global general_log_file='/tmp/query.log';
```
5. execute the below query that includes `whereDate`:
`\App\User::whereDate('created_at', new \Carbon\Carbon())->inRandomOrder->first();`
6. Open the log file by this command `tail -f /tmp/query.log`. The result is:
```
                   466 Query    use `laravel`
                   466 Prepare  set names 'utf8mb4' collate 'utf8mb4_unicode_ci'
                   466 Execute  set names 'utf8mb4' collate 'utf8mb4_unicode_ci'
                   466 Close stmt
                   466 Prepare  set session sql_mode='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
                   466 Execute  set session sql_mode='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
                   466 Close stmt
                   466 Prepare  select * from `users` where date(`created_at`) = ? order by RAND() limit 1
                   466 Execute  select * from `users` where date(`created_at`) = '2019-09-16' order by RAND() limit 1
                   466 Close stmt
```
* Consider the last line before close. There is a quoted date string.

**Comment by driesvints** [comment]
@SlyDave seems like we can't reproduce this. Feel free to submit a PR with a failing test if you can prove that way that there's a bug.
