### ISSUE TITLE
MorphTo when changing db connection

### ISSUE THREAD

**Issue by klimby** [laravel/framework#29935]
- Laravel Version: 5.8.33
- PHP Version: 7.2.15
- Database Driver & Version: pgsql

### Description:
MorphTo does not work when changing db connection.

### Steps To Reproduce:
1. Two identical databases - A end B
2. Default connection - A
3. The model Model contains:
```
public function element(): MorphTo
    {
        return $this->morphTo();
    }
```
4.
`$model = Model::with('element')->first();`
$model->element contains object.

`$model = Model::on('B')->with('element')->first();`
$model->element is null
`$model = $model -> load('element');`
$model->element is null
`$element = $model -> element() -> first();`
$element  is object.

5. Set default connection to B.
`$model = Model::with('element')->first();`
$model->element contains object.

`$model = Model::on('A')->with('element')->first();`
$model->element is null

**Comment by driesvints** [comment]
@klimby can you upgrade to 6.0 and see if the problem persists? I know quite some fixes to Eloquent have been made recently.

**Comment by klimby** [comment]
Updated to 6.0. Unfortunately, the problem is relevant.

**Comment by adhyapranata** [comment]
It works well with MySQL. Is this issue only occur with Postgres driver?

**Comment by staudenmeir** [comment]
@adhyapranata The issue affects all databases.

**Comment by straube** [comment]
I couldn't reproduce this issue running Laravel 6.4.1 with MariaBD 10.3.16.

**Comment by driesvints** [comment]
@straube can you try mysql or postgres?

**Comment by yaim** [comment]
@driesvints, @klimby, I traced the issue & found out that at [@createModelByType](https://github.com/laravel/framework/blob/6.x/src/Illuminate/Database/Eloquent/Relations/MorphTo.php#L150-L155), Eloquent lose track of the connection.

This workaround fixed the issue :
```php
public function createModelByType($type)
{
    $class = Model::getActualClassNameForMorph($type);

    return (new $class)->setConnection($this->getConnection()->getName());
}
```
but it messes up with [@testMorphToRelationsAcrossDatabaseConnections](https://github.com/laravel/framework/blob/6.x/tests/Database/DatabaseEloquentIntegrationTest.php#L1167-L1180), as the test expects the Morph models to work on different connections (so the MorphTo model should define its connection by its own not using the other model).

This behavior seems totally right, as if we change it, then the `::on()` method would override the `protected $connection` attribute, which probably breaks lots of logics.

Now I'm not sure if it's actually a bug or a planned feature. :thinking:

**Comment by driesvints** [comment]
@staudenmeir can you confirm the above? Is the current behavior correct?

**Comment by staudenmeir** [comment]
AFAICS, we need to mimic the behavior of all other relationships and only set the connection on the related model if the parent model is _not_ using the default connection.
 
https://github.com/laravel/framework/blob/005cad6a8e8577cb16c7e54e5d2a1a4df9ba06d4/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php#L716-L723

This fixes the issue for me and doesn't break `testMorphToRelationsAcrossDatabaseConnections()`.

**Comment by yaim** [comment]
@staudenmeir you're right, that did work for me as well.
I thought `getConnectionName` would fallback to parent class's property.
I'm pushing an PR for this.
