### ISSUE TITLE
Pagination Issues with V6

### ISSUE THREAD

**Issue by mikebrandl** [laravel/framework#29930]
- Laravel Version: 6.0.1
- PHP Version: 7.2.22
- Database Driver & Version: Mysql

### Description:

I cannot use the links() feature that I was using to generate pagination. 

I get the following error. 

Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: Method Illuminate\Translation\Translator::getFromJson does not exist. (View: website/vendor/laravel/framework/src/Illuminate/Pagination/resources/views/bootstrap-4.blade.php)

I have an eloquent model: \App\Quote, which returns paginated responses. 

### Steps To Reproduce:

Obtain a paginated eloquent model.
$quotes = \App\Quote::paginate(25);
Display the pagination.
{!! $quotes->appends(Request::except('page'))->links() !!}

**Comment by driesvints** [comment]
Please read the upgrade guide when upgrading and run `php artisan view:clear`: https://laravel.com/docs/6.0/upgrade#get-from-json

**Comment by hasanhasanzadeh** [comment]
I how problem in show blade paginate in laravel 7.2
![Uploading Screenshot from 2020-11-05 23-36-18.png…]()
