### ISSUE TITLE
ternary operator not working properly

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [laravel/framework#29963]
- Laravel Version: 5.7
- PHP Version: 7.2.19
### Description:
I'm trying to set a select option on a specific element choosen by if is in old(), if not, if belongs to the element (in this case, wine) with ternary opertor, but this 
```php
@foreach (App\Models\Region::all() as $reg)
     <option value="{{$reg->region_id}}" {{filled(old('region_id'))&&old('region_id')==$reg->region_id ?'selected': filled($wine->region)? $reg->region_id==$wine->region->region_id? "selected": '' :''}}>{{$reg->region_id}} - {{$reg->region_name}}</option>
 @endforeach
```
that formatted i belive that has this meaning 
```php
filled(old('region_id'))&&old('region_id')==$reg->region_id
    ?
        'selected'
    : 
        filled($wine->region)
            ? 
                $reg->region_id==$wine->region->region_id
                    ? 
                        "selected"
                    : 
                '' 
            :
                ''
```
is evaluated differently respect of this
```php
@foreach (App\Models\Region::all() as $reg)
          <option value="{{$reg->region_id}}" {{filled(old('region_id'))&&old('region_id')==$reg->region_id ?'selected': (filled($wine->region)? ($reg->region_id==$wine->region->region_id? "selected": '' ):'')}}>{{$reg->region_id}} - {{$reg->region_name}}</option>
@endforeach
```
that formatted i belive that has this meaning 
```php
filled(old('region_id'))&&old('region_id')==$reg->region_id 
    ?
        'selected'
    : 
        (
            filled($wine->region)
                ? 
                    (
                        $reg->region_id==$wine->region->region_id
                            ? 
                                "selected"
                            : 
                                '' 
                    )
                :
                    ''
        )
```
the difference is that the first one, also if the second filled ( `filled($wine->region)` ) returns false, runs the `$reg->region_id==$wine->region->region_id` and the second one, the one with the brackets, no

Tell me if you need more code or more information, there is no problem
Thanks, Alberto

EDIT: the point is that if $wine->region does not exist, when it trys to execute `$wine->region->region_id` it throw an exception because i'm reading a property of a null element, but if `$wine->region` was null, `filled($wine->region)` should has retuned false, and so that code should not have been executed

**Comment by tillkruss** [comment]
This isn't a framework issue. Extract the logic into Blade directives.
