### ISSUE TITLE
[6.0] Move command queue from ArtisanServiceProvider to QueueServiceProvider

### ISSUE THREAD

**Issue by reishou** [laravel/framework#29961]
I want to optimize my repository, this's a repository which don't need using queue. When I remove `Illuminate\Queue\QueueServiceProvider::class`, from /config/app.php, everything ok until I run composer update
```
In Container.php line 806:
                                                 
  Target class [queue.listener] does not exist.  
                                                 

In Container.php line 804:
                                       
  Class queue.listener does not exist 
```
So, I think we should remove some command `command.queue.*` to QueueServiceProvider

**Comment by nmokkenstorm** [comment]
QueueServiceProvider implements the [DefferableProvider interface](https://laravel.com/docs/5.8/providers#deferred-providers), so you probably won't see much improvement performance wise.

That being said, I recall several Laravel team members voicing their wishes to move components out of `illuminate/foundation` and into their respective parts of the framework, and it's a rather easy fix.

**Comment by reishou** [comment]
Thank you for replying. I hope next version, laravel basic setup will fast as skeleton, slim.
