### ISSUE TITLE
Renaming spatial columns changes the column type.

### ISSUE THREAD

**Issue by sikhlana** [laravel/framework#29968]
- Laravel Version: 5.8.35
- PHP Version: 7.3.8
- Database Driver & Version: MariaDB 10.3

### Description:
I was trying to rename a `LINESTRING` column of my database table through migration and got a general error as the migrator was changing it to a `VARCHAR(255)`. Here's SQL the output:

```sql
ALTER TABLE engagement_routes CHANGE path line VARCHAR(255) NOT NULL
```

### Steps To Reproduce:

1. Create a new migration file to add a new `LINESTRING` column to a table.
2. Create a new migration file to rename the newly created `LINESTRING` column to something else.
3. Run the migration.

**Comment by sikhlana** [comment]
> 
> 
> What version of `doctrine/dbal` are you using?
> 
> When I run these migrations, I don't even get to the query:
> 
> > Unknown database type linestring requested, Doctrine\DBAL\Platforms\MariaDb1027Platform may not support it.

I am using version 2.9.2.

**Comment by staudenmeir** [comment]
Weird, I'm using the same version.

**Comment by sikhlana** [comment]
Upon looking further into the packages I am using, looks like the package `grimzy/laravel-mysql-spatial` is adding the spatial column types to doctrine on the fly. How come the `Schema` facade has these column types but not in the framework itself for doctrine?

**Comment by staudenmeir** [comment]
Laravel doesn't add any types to Doctrine. If Doctrine doesn't support a type, Laravel can't modify such a column.

This would be a suggestion for Doctrine. Not sure if the `grimzy/laravel-mysql-spatial` package could do anything about it.

**Comment by sikhlana** [comment]
Yeah, will have to create an issue there. But my question right now is: how come Laravel has the blueprint functions (`$table->lineString()`, `$table->point()` and such) but not the necessary doctrine handlers?

**Comment by driesvints** [comment]
@sikhlana think that's only for renaming. For creating the columns in the first place the blueprint values are still used. Right @staudenmeir?

**Comment by driesvints** [comment]
Going to close this as this doesn't seems to be a direct bug with Laravel itself.
