### ISSUE TITLE
[5.8] [6.0] Broadcast authorization channel security issue

### ISSUE THREAD

**Issue by apoca** [laravel/framework#29971]
- Laravel Version: 5.8
- PHP Version: 7.2
- Database Driver & Version: 5.7

### Description:

I have a problem with broadcast channels. Thus, when I subscribe to a private channel the framework does not make a full match with the channel name. For example, whether I have two channels with the names "App.Employee.{employeeId}" and "App.Employee.{employeeId}.Resource.{resourceId}" and whether the first channel is true, then will be always true. Furthermore, it seems a huge security issue.

### Steps To Reproduce:

```php
Broadcast::channel('App.Company.{companyId}', function ($user, $companyId) {
    return $user->isEmployeeOf($companyId);
});

Broadcast::channel('App.Company.{companyId}.Request.{requestId}', function ($user, $requestId) {
    return $user->isEmployeeOf($companyId) && $user->isOwnerRequest($requestId);
});
```

**Comment by driesvints** [comment]
This seems like a duplicate of https://github.com/laravel/framework/issues/25065 ?

**Comment by apoca** [comment]
@driesvints I don't know whether is the same issue here, but it seems somehow correlated. Then, I have an idea to solve those incongruences, I think we must define a regex rule for ID {ID} and with some change in regex pattern, we can prevent the bad using or nomenclature of string channel pattern. Thus, we have a full match now not a partial...

```php

public function channelNameMatchPatternProvider()
    {
        return [
            ['something', 'something', true],
            ['something.23', 'something.{id}', true],
            ['something.23.test', 'something.{id}.test', true],
            ['something.23.test.42', 'something.{id}.test.{id2}', true],
            ['something-23:test-42', 'something-{id}:test-{id2}', true],
            **['something..test.42', 'something.{id}.test.{id2}', true],**
            ['23:string:test', '{id}:string:{text}', true],
            ['something.23', 'something', false],
            ['something.23.test.42', 'something.test.{id}', false],
            ['something-23-test-42', 'something-{id}-test', false],
            ['23:test', '{id}:test:abcd', false],
            ['something.23.test.45', 'something.{id}', false],
        ];
    }
```
** I don't realize why this test do... It doesn't makes any sense using to dot together in a channel name!? And I added the last line to test our idea.


My recommendation is to remove that line from channelNameMatchPatternProvider function and change channelNameMatchesPattern to:

**Actual:** 

```php
protected function channelNameMatchesPattern($channel, $pattern)
    {
        return Str::is(preg_replace('/\{(.*?)\}/', '*', $pattern), $channel);
    }
```

**New:**

```php
protected function channelNameMatchesPattern($channel, $pattern)
    {
        $regexFullMatch = preg_match('/^'.preg_replace('/\{(.*?)\}/', '(?<$1>[^\.]+)', $pattern).'$/', $channel);

        return Str::is(preg_replace('/\{(.*?)\}/', '*', $pattern), $channel) && $regexFullMatch;
    }
```

**Comment by apoca** [comment]
@driesvints Do you have news about this?

**Comment by driesvints** [comment]
Not yet sorry.

**Comment by netpok** [comment]
Looking at it, it's definitely the same issue (#25065). I'm posting my suggestions there.

**Comment by driesvints** [comment]
@netpok thanks for checking into this. I'll close this one in favor of the other.

**Comment by netpok** [comment]
@apoca 

Until this resolved if put your broadcast authorization in strict to less strict order and throw an instance of `Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException` in cawse of failure, then it will work as you expect it.

**Comment by apoca** [comment]
@netpok 

I'm not sure whether I understood your answer. With the example that I have provided above can you explain your point of view?

Honestly, I think I have tried your solution before and didn't work.

**Comment by netpok** [comment]
Yes, of course I can:

- Based on a quick look on the Broadcast.php the channels are checked in creation order
- And if all callbacks fail it will throw an AccessDeniedHttpException

So by using the following config:
```php
Broadcast::channel('App.Company.{companyId}.Request.{requestId}', function ($user, $requestId) {
    return throw_unless(
        $user->isEmployeeOf($companyId) && $user->isOwnerRequest($requestId),
        \Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException
    );
});

Broadcast::channel('App.Company.{companyId}', function ($user, $companyId) {
    return throw_unless(
        $user->isEmployeeOf($companyId)
        \Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException
    );
});
```
 
The following will happen:
- the channel will match `App.Company.{companyId}.Request.{requestId}` first, because it was registered before `App.Company.{companyId}`
- if the check fails it throws the exception which prevents the evaluation of the rest of the channel definitions
- if the check doesn't fail it will return the result (because `throw_unless` returns the value if its not false) and the channel will be authenticated because the response evaluates to true
