### ISSUE TITLE
Unable to read env file incase of heavy load on server

### ISSUE THREAD

**Issue by Prakash091293** [laravel/framework#29977]
We are having issue to read env file values during heavy load on server.

Even tried using Config and calling them through static function.

Kindly suggest any changes to fix this.

**Comment by GrahamCampbell** [comment]
Yes. We recommend using the config:cache command always. The issue you are seeing is likely not the file not being loaded, but actually the variables leaking across your website's because environment variables are not thread-safe. This is mitigated by Laravel's config caching.
