### ISSUE TITLE
compileStatements cannot go with strings contain bracket

### ISSUE THREAD

**Issue by ZsgsDesign** [laravel/framework#29981]
- Laravel Version: 5.8.32
- PHP Version: 7.3.6
- Database Driver & Version: MySQL 8.0.12

### Description:

The `compileStatements()` method cannot go with strings contain a bracket. Actually it's the regex that cannot do that, resulting in a blade rendering disaster.

### Steps To Reproduce:

1. new a blade.php file, and type:
```php
@include('errors.general',[
    'emoji'=>':-)',
    'code'=>404,
    'type'=>'Not Found',
    'description'=>'The requested URL was not found on this server.'
])
```
2. Render it and you've got a rendered php result:
```php
<?php echo $__env->make('errors.general',[
    'emoji'=>':-, \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>',
    'code'=>404,
    'type'=>'Not Found',
    'description'=>'The requested URL was not found on this server.'
])
 ?><?php /**PATH C:\Users\ZsgsD\Desktop\workspace\CodeMaster\resources\views/errors/404.blade.php ENDPATH**/ ?>
```
Of which you can see the right bracket is parsed into `, \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>`.

The Code is located in class `Illuminate/View/Compilers/BladeCompiler`, as it goes:
```php
    public function include($path, $alias = null)
    {
        $alias = $alias ?: Arr::last(explode('.', $path));
        $this->directive($alias, function ($expression) use ($path) {
            $expression = $this->stripParentheses($expression) ?: '[]';
            return "<?php echo \$__env->make('{$path}', {$expression}, \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>";
        });
    }
```

The `directive` method inserts the action of each of the alias, in this case, `include`. And then goes `compileStatements` method;

```php
    protected function compileStatements($value)
    {
        return preg_replace_callback(
            '/\B@(@?\w+(?:::\w+)?)([ \t]*)(\( ( (?>[^()]+) | (?3) )* \))?/x', function ($match) {
                return $this->compileStatement($match);
            }, $value
        );
    }
```

In this case, the regex `/\B@(@?\w+(?:::\w+)?)([ \t]*)(\( ( (?>[^()]+) | (?3) )* \))?/x` would match the first `)` and ignore the rest, thus making an error.

Actually it affects all the blade snippets. Likewise, we can do something like this:

```php
@if($val=='(string')
```

I am using a workaround here by using HTML encoding:
```php
@include('errors.general',[
    'emoji'=>':-&#41;',
    'code'=>404,
    'type'=>'Not Found',
    'description'=>'The requested URL was not found on this server.'
])
```
But I have no solution when involving PHP string operations but to use the controller to pass the variable contains brackets firstly.

I believe it's impossible to make changes to regex somehow and solve that, it is just beyond the regex's capability. Actually I have a question, why don't Laravel just parse `@xxx` and preserve the rest. Like, turn `@include` to `blade_include` thus avoid manipulating the parameters.

**Comment by fitztrev** [comment]
Recreated and confirmed on 6.0.3 too.

```bash
composer create-project --prefer-dist laravel/laravel issue-29981
cd issue-29981

echo "contents" > resources/views/child.blade.php
echo "@include('child')" > resources/views/parent-ok.blade.php
echo "@include('child', ['emoji' => ':)'])" > resources/views/parent-error.blade.php
```

```bash
$ php artisan tinker

>>> view('parent-ok')->render()
=> "contents\n"

>>> view('parent-error')->render()
=> Facade/Ignition/Exceptions/ViewException with message 'syntax error, unexpected ...
```

**Comment by ZsgsDesign** [comment]
The very problem here is it's 2019 and **NO ONE** uses regex for their template engine! I love Laravel but I was shocked last night when I saw the source code of Blade.

**Comment by driesvints** [comment]
I'm afraid we can't support this given the current state of Blade. Feel free to open up an issue in the ideas repo with thoughts on how this can be approved so the above can be supported. Thanks.

**Comment by jorgecc** [comment]
> The very problem here is it's 2019 and **NO ONE** uses regex for their template engine! I love Laravel but I was shocked last night when I saw the source code of Blade.

For the record: And what is your solution?  Parsing it manually?
