### ISSUE TITLE
Laravel 5.4 scheduled jobs are triggered multiple times occasionally. 

### ISSUE THREAD

**Issue by dilaniMaheswaran** [laravel/framework#29998]
**Set Up**
Laravel version: 5.4
server PHP version :  v7.0.33
Server: Debian

**Issue**
I have scheduled cronjobs in Kernel.php and executed them from crontab.

These jobs get executed multiple times occasionally.

These were working as expected until I put the app on maintenance mode. For a DB server maintenence, I turned down the app using php artisan down and turned it up after about 20 minutes with php artisan up. Every time a job runs, I am making an entry in a table. My table shows multiple records at times.

I have no idea what is causing this issue. I have some calculations in my cron jobs which are going incorrect because these jobs are running multiple times at once.

![image](https://user-images.githubusercontent.com/14857562/64920190-7ef49c80-d7c5-11e9-8c20-1904c23da3b8.png)

**Crontab:**
`* * * * * php /path-to-your-project/artisan schedule:run >> /dev/null 2>&1
`
**Kernel.php**
```
        $schedule->command('calculate:limit')->everyFiveMinutes();
        $schedule->command('update:catalogue')->daily();
```

**Comment by laurencei** [comment]
Do you run multiple servers in a cluster, or just the single web server?

**Comment by dilaniMaheswaran** [comment]
Hi,

No, Just this single server.

Thanks
________________________________

**Comment by laurencei** [comment]
Not sure. Sounds like a server issue, because thats the only way it can be called multiple times.

Either way - your running Laravel 5.4, which is also outdated. I suggest upgrading and seeing if the problem continues.
