### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by Baha2rM98** [laravel/framework#29997]
- Laravel Version: 6.0.1
- PHP Version: 7.3.9
- Database Driver & Version: MySQL phpmyadmin

### Description:
findOrFail, where, update, and some of database functions are missed.

**Comment by simoebenhida** [comment]
@Baha2rM98 What do you mean ? What is the issue that you are getting ?

**Comment by Baha2rM98** [comment]
When I create a model for example Post model and in controller I write
Post:: it must suggest static methods for example where, find, findOrFail
and so on...
But for me they don't exist and I should write Post::all()->
Then some of them will appear.

**Comment by simoebenhida** [comment]
`Post::all()->where` You are using collection `where` method ! but when using `Post::where()` you are using builder method so it will be generated to a query. I couldn't not replicate this issue everything is working fine ! Will you paste the exact error ? or some steps on how to produce the error.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.

**Comment by Baha2rM98** [comment]
As soon as possible I send you the code and the issue.

**Comment by Baha2rM98** [comment]
public function updatePost()
{
    $post = Post::all()->find(1);
    $post = Post::find();}

in my phpstorm Post::find() dosen't find! warning says: find method is not
defined, but when i type Post::all()->find() it is reachable. why?

**Comment by simoebenhida** [comment]
@Baha2rM98 It is working ! just PHPstorm can't read it because Laravel is using a magic method behind the scenes.

**Comment by Baha2rM98** [comment]
Yea... I tried and found out...
Unfortunately I thought my system has a bad problem!
By the way thank you for your grate responsibility and attention.
