### ISSUE TITLE
Database loss effect on sessions

### ISSUE THREAD

**Issue by halaei** [laravel/framework#29993]
- Laravel Version: 6.0.3
- PHP Version: 7.2.22
- Database Driver & Version: MySql
- Session Driver: Redis

### Description:
Due to the recent unrecoverable failure in an AWS RDS MySQL used by our Laravel application, I find the following scenario may happen:
### Steps To Reproduce:
1. Alice register in our website. We assign a user id = 1000 to her account. The id is stored in a MySQL database record as well as in a session stored in Redis.
2. MySQL crashes and we are afraid it may not recover anytime soon.
3. Fortunately we have a backup. We create a new database server using that backup. However, the backup is not up-to-date and it doesn't have Alice's records.
4. After the "partial recovery", Bob registers and we assign user id = 1000 to him as well. He then fills his profile and gives us some potentially sensitive information.
5. Alice visits our website again. Now she is seeing Bobs profile and sensitive data instead of hers because Laravel only checks session validity by the value of user id.

### How to fix
If we know in advance this could happen, we might simply clear the whole cache to prevent such issues. But we didn't know :(
However, maybe a better alternative is to store user's create_at in session as well and perform an extra validation against it:

```php
$id = $this->session->get($this->getName());
// Changing this line:
$this->user = $this->provider->retrieveById($id);
// To
$createdAt = $this->session->get('created_at');
$this->user = $this->provider->retrieveByIdAndCreateAt($id, $createdAt); 
```

I don't know if this should be taken care of inside the framework or not, but when it happens it hurts!

**Comment by rs-sliske** [comment]
if ive understood correctly, the AuthenticateSession middleware (which is provided by laravel but not enabled by default) might help with this kind of situation. can read more about it https://laravel.com/docs/6.x/authentication#invalidating-sessions-on-other-devices but basically it stores a hash of the password in session so if the password changes it invalidates the session

**Comment by halaei** [comment]
@rs-sliske thanks. `AuthenticateSession` seems to be good, except that, as you mentioned, it is password dependent, so it won't work with users registered by Google oAuth for example.

**Comment by halaei** [comment]
And AuthenticateSession is disabled by default.

**Comment by dwightwatson** [comment]
I'm not sure the framework needs to take care of this when handling manual database recovery from a backup. I wonder what the chance of this occurring during an automated database failover are (when AWS RDS flips to the replica during a failure).

I suspect in this case when you're manually restoring you'd be best to cycle the APP_KEY so that all existing cookies are invalidated forcing users to sign in again.

**Comment by rs-sliske** [comment]
@dwightwatson changing the app key will potentially do a lot more than just invalidating cookies, it will also lose any encrypted data

for session cookies you can just clear sessions

as for the framework being able to deal with this scenario properly that seems like an almost impossible problem, you have a database which says that user with id of 1000 is john, then after some set of actions your database says user 1000 is jane, but you still have references in other places that think user 1000 is still john, 

the only defenses against this are either to make sure that primary keys never get reused, or to make sure that everywhere storing the users id also stores a bunch of other data about the user incase the id gets reused

**Comment by driesvints** [comment]
Imo this can't be the responsibility of the framework. Like others have said above, id collision because of system failure can't be guarded against. Sessions being kept with ids can indeed be covered more thoroughly with the `AuthenticateSession` middleware but is opt-in.
