### ISSUE TITLE
Laravel + Redis, putting a integer number to cache is not working as well.

### ISSUE THREAD

**Issue by KevinHN** [laravel/framework#30002]
- Laravel Version: 5.7, 5.8
- PHP Version: 7.1.32
- Database Driver & Version: Redis version 3.2.12 and predis version p1.1.1

### Description:
If I put a value to cache like this:
Cache::put($cacheKey, 1, now()->addSeconds(30));
The value return by Cache::get($cacheKey) is null (the value in the redis is nil)

If I change 
Cache::put($cacheKey, '1', now()->addSeconds(30));
It works fine.

For the same key, if I put the string value first, and then put the integer. It's Ok. crazy

### Steps To Reproduce:
1. For the new key, put a integer by 
Cache::put($cacheKey, 1, now()->addSeconds(30));
2. Get the value by Cache::get($cacheKey), you may see the result is null.

**Comment by laurencei** [comment]
Can you try upgrading to Laravel 6.0 and see if the problem continues?

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
