### ISSUE TITLE
Cast is not working in Api resource/ collection 

### ISSUE THREAD

**Issue by jarda256sparktech** [laravel/framework#30003]
- Laravel Version: 6.0.3
- PHP Version: 7.3.x
- Database Driver & Version: Mysql

### Description:
Referring to this https://laravel.com/docs/6.x/eloquent-resources#resource-collections I made collection and resource for Event model so **EventCollection** and **EventResource**. There I want to override toArray method so I can decide what will be on list and what on detail. I have set cast **datetime:d.m.Y H:i** for all my datetime fields. When I let the code as it is generated all the datetime fields are in correct format. However when i edit toArray method like this, I will get all datetime fields as **2019-06-29T10:00:00.000000Z**. It should be in correct format, because if I **dd($event->starts_at)** it is a string value.

taken from EventCollection
```
public function toArray($request)
    {
        return [
            'data' => $this->collection->transform(function($event){
                return [
                    'id' => $event->id,
                    'name' => $event->name,
                    'excerpt' => $event->excerpt,
                    'slug' => $event->slug,
                    'startsAt' => $event->starts_at,
                    'endsAt' => $event->ends_at,
                    'city'=>[
                        'id'=>$event->city->id,
                        'name'=>$event->city->name,
                    ],
                    'district'=>[
                        'id'=>$event->district->id,
                        'name'=>$event->district->name,
                    ],
                ];
            }),
        ];
    }
```

### Steps To Reproduce:
1. Make model
2. Add datetime casts with format to model
3. Make resource / collection for that model and modify toArray() method
4. Compare default API response (from generated resource/collection) and modified

**Comment by driesvints** [comment]
Hey there,

There have been numerous issues already about date casting which often were caused by some misconfiguration.

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by gbradley** [comment]
@driesvints I am also seeing this happening on a clean install of 6.7.0. I've created a repo you can clone and run phpunit on to demonstrate this : https://github.com/gbradley/laravel-resource-cast-test/blob/master/README.md

**Comment by tobiasthaden** [comment]
From the laravel documentation:
> When using the date or datetime cast type, you may specify the date's format. This format will be used __when the model is serialized to an array or JSON__

So you have to be explicit: `$event->starts_at->format('Y-m-d')`

**Comment by gbradley** [comment]
@tobiasthaden Ah, OK; thanks for highlighting that. Seems like I misunderstood the intended behaviour, although now you pointed it out, its pretty obvious why this happens.
