### ISSUE TITLE
Mismatch in signature creation and verification with forceScheme('https')

### ISSUE THREAD

**Issue by MatteoPaier** [laravel/framework#30019]
- Laravel Version: 5.8.35
- PHP Version: 7.3.8

### Description:
When using `URL::forceScheme('https')` in e.g. AppServiceProvider the signature generated by `signedRoute()` and the signature verified by `hasValidSignature()` does not match.
In particular, it seems that `hasValidSignature()` does not count for the "https" in the URL.
It can be solved by replacing
`$url = $absolute ? $request->url() : '/'.$request->path();`
with
`$url = $absolute ? $this->current() : '/'.$request->path();`
in the body of `hasValidSignature()`.
A fix for the same issue was suggested in #27699, but it was not accepted.

### Steps To Reproduce:
Set `forceScheme('https')` and try to open a signed route, e.g. an email verification route.

**Comment by driesvints** [comment]
We've had so much of these issues already and 99% of the cases it was some misconfiguration of a loadbalancer or something else server related.

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
