### ISSUE TITLE
Job Handle config mail

### ISSUE THREAD

**Issue by striderxfossility** [laravel/framework#30016]
- Laravel Version: 5.8.23
- PHP-versie: 7.1.14
- Database Driver & Version: MSQL 5.5.62-0ubuntu

### Description:
When i restart the queu and test it, it works... but then after a day/hours or so. it goes back to my main config and doesnt apply /Config settings.. so my from email is always the ENV, but in this reason I do not want the ENV but an other email.

### Steps To Reproduce:
JOB:
`class SendAweberTegelexpertMail implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public $****

    public function __construct($****)
    {
        $this->**** = $****;
    }

    public function handle()
    {
        $subject = $this->subject;
        $email   = $this->email;
        $message = $this->mess;

        $config = [
            'driver'     => 'smtp',
            'host'       => '****',
            'port'       => ***,
            'username'   => '****',
            'password'   => '***',
            'encryption' => 'tls',
        ];

        \Config::set('mail', $config);

       
                \Mail::send('mails.plain', ["html"=>$message,"name"=>'****'], function($message) use($subject, $email) {
                    $message->from('****', '****');
                    $message->replyTo('****', '****');
                    $message->subject($****);
                    $message->to($****);
                });
    }`

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
