### ISSUE TITLE
Malformed UTF-8 characters, possibly incorrectly encoded

### ISSUE THREAD

**Issue by rjchauhan** [laravel/framework#30014]
- Laravel Version: 5.8.16
- PHP Version: 7.2.8
- Database Driver & Version: MySQL v5.7.25

### Description:
`Illuminate\Database\Eloquent\JsonEncodingException`

Getting `Malformed UTF-8 characters, possibly incorrectly encoded` exception when returning user object having umlaut character from controller. This only occurs when converting user object into JSON using `toJson()` or returning from controller.

for ex:  `Ö in Özcicek`

> only for some umlaut characters, not all umlaut characters generating this exception.

### Steps To Reproduce:
- Create new user in database with name `Özcicek`
```
factory(\App\User::class)->create(['name' => 'Özcicek']);
```
- Create controller and return
```
public function index() 
{
    return \App\User::first();
}
```
- Or use tinker and run this 
```
User::first()->toJson();
```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by rjchauhan** [comment]
Hey @driesvints 

Thanks for your feedback! I've checked this with Laravel v6.0.1 and it's just working fine!

Unfortunately, We can't upgrade our application to v6 yet, because it consists of too many third party packages which doesn't have Laravel v6 support :)
