### ISSUE TITLE
BrowserSync kills Error-Messages

### ISSUE THREAD

**Issue by lmeysel** [laravel/framework#30018]
- Laravel Version: 6.0
- PHP Version: 7.2.10
- Database Driver & Version: irrelevant

### Description:
BrowserSync injection destroys the JavaScript displaying server errors.

### Steps To Reproduce:
Create a new Laravel project:
`composer create-project --prefer-dist laravel/laravel blog`
`cd blog`
`npm i`

Produce an error (e.g. by just enter a non-existent view in routes/web.php).

Now, when running `php artisan serve` and access `localhost:8000`: you should see the error which tells you about the missing view, as expected.

Good. Now enable BrowserSync in the webpack.mix.js by adding
```javascript
mix.browserSync({ proxy: 'localhost:8000' });
```

Open another console, and start laravel in watch mode `npm run watch`. Tadaaa: `localhost:3000` now seems to serve some JS code which obviously misses something.

### Getting hands on it
Okay, somewhere is a script-tag closed (accidentally). Opening (using Chrome) `view-source:localhost:3000` (after some scrolling), we find this:
![image](https://user-images.githubusercontent.com/12410218/65062384-316e6000-d97c-11e9-969f-4496f1143d97.png)

Ouch! The non-escaped line-breaks interrupt a JS string and this makes line 57 a real </script>

I am not sure whether this is a problem coming with the new Laravel version or the BrowserSync-guys changed something?

**Comment by lmeysel** [comment]
Okay, after doing some research it turned out, that BrowserSync injects it's snippet into raw-html by finding `</body>` or `</pre>` via a RegExp, which is found somewhere in Laravel's generated code. Fortunately it allows to configure that as described [in the docs](https://www.browsersync.io/docs/options#option-snippetOptions) (just use the snippet as it is and pass it in to the mix.browserSync-options):
```javascript
mix.browserSync({
  proxy: 'localhost:8000',
  snippetOptions: {
    rule: {
      match: /<\/body>/i,
      fn: function (snippet, match) {
        return snippet + match;
      }
    }
  }
})
```

Maybe this should be done automatically by laravel-mix? Or at least explicitly mentioned in the docs?

**Comment by fitztrev** [comment]
I've noticed this too. It has to do with the regex that laravel-mix uses for the snippet placement. See https://github.com/JeffreyWay/laravel-mix/pull/2227

**Comment by driesvints** [comment]
Seems like this is better to be reported on the mix repository.
