### ISSUE TITLE
Memory leak on database insert function

### ISSUE THREAD

**Issue by oalkhanishvili** [laravel/framework#30012]
- Laravel Version: 6.0
- PHP Version: 7.2.14
- Database Driver & Version: PDO, 5.7.21

### Description:
I was trying to transfer 100 000 records from one table to another and got some kind of memory leak while inserting records. I checked same script on laravel 5.8 version and worked great. It seems on the new version something is not cleared from memory after inserting

### Steps To Reproduce:
```php
     \DB::connection()->disableQueryLog();
     DB::table('test_table2')->orderBy('id')->chunk(500, function ($chunk) {
            $data = [];
            foreach ($chunk as $record) {
                $data []= [
                    'test' => $record->test
                ];
            }
            DB::table('test_table')->insert($data);

            dump(memory_get_usage());
        });
```

**Comment by staudenmeir** [comment]
I can reproduce the increasing memory usage, but I get the same behavior on Laravel 5.8.

Can you share the output from both versions?

**Comment by dwightwatson** [comment]
Try disabling the query log if you haven't already (`DB::disableQueryLog()`) - Laravel could be exhausting memory usage by keeping track of every database query you perform.

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.

**Comment by programmador** [comment]
Confirming the issue with 5.5 (Symfony + EloquentBundle + illuminate/database-5.5).
```
$connection->disableQueryLog();
$connection->table($tableName)->insert($array);
```
And memory leaks with every query more and more.
`$connection->logging()` returns false;

Doing the same with bare `$connection->getPdo()` works fine;

**Comment by programmador** [comment]
Same for 5.8

**Comment by tindoantrong** [comment]
I have the same problem with laravel 5.5

**Comment by stanzani** [comment]
Same here with: PHP: v7.2.23 / Laravel Framework: v6.15.1
Workaround: `$connection->getPdo()`

**Comment by sebsel** [comment]
I don't know if this solves the above issues, but I had this issue too and found a cause.

In the `logQuery()` function, commenting out 687 got rid of my memory leak. The other lines had no effect. Ergo: someone was saving queries in an Event Listener.
https://github.com/laravel/framework/blob/ea3d291420ffd5ebcc6bb7c1deef32c853ce24a8/src/Illuminate/Database/Connection.php#L685-L692

This someone turned out to be Flare/Ignition, which ships with Laravel since 6.0.

To disable their logging, publish the config by running:
```
php artisan vendor:publish --provider="Facade\Ignition\IgnitionServiceProvider" --tag="flare-config"
```

And then under `flare.reporting`, change `report_queries`, `maximum_number_of_collected_queries` and/or `report_query_bindings`.

**Comment by edgarsn** [comment]
For me, the problem was a telescope database logging. It logs all queries even with
`\DB::connection()->disableQueryLog()`. 

I added my artisan command to `telescope.ignoreCommands` config and problem solved. So be aware when using any logging packages. They can cause the mess instead of a framework.

**Comment by mesiarm** [comment]
> I don't know if this solves the above issues, but I had this issue too and found a cause.
> 
> In the `logQuery()` function, commenting out 687 got rid of my memory leak. The other lines had no effect. Ergo: someone was saving queries in an Event Listener.
> https://github.com/laravel/framework/blob/ea3d291420ffd5ebcc6bb7c1deef32c853ce24a8/src/Illuminate/Database/Connection.php#L685-L692
> 
> This someone turned out to be Flare/Ignition, which ships with Laravel since 6.0.
> 
> To disable their logging, publish the config by running:
> 
> ```
> php artisan vendor:publish --provider="Facade\Ignition\IgnitionServiceProvider" --tag="flare-config"
> ```
> 
> And then under `flare.reporting`, change `report_queries`, `maximum_number_of_collected_queries` and/or `report_query_bindings`.

To disable events only in current connection you can use:  
`DB::getConnection()->unsetEventDispatcher();`

**Comment by snapey** [comment]
In my case it was Laravel Debugbar recording SQL queries incase it needs to print them in the view.

**Comment by slavicd** [comment]
> Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.

This is very much still an issue. The default Laravel install will include "spatie/laravel-ignition" with an unpublished config file that collects database queries (see `flare_middleware` config key) which will behave as a memory leak.

**Comment by JAyers2264** [comment]
> This is very much still an issue. The default Laravel install will include "spatie/laravel-ignition" with an unpublished config file that collects database queries (see `flare_middleware` config key) which will behave as a memory leak.

I'm encountering this issue now and trying to find a work around. I saw that in the past one could use a flare.php config file to set 'report_queries' to false, but now they seem to have classes that handle validating the config settings and I don't see 'report_queries' as a valid option anywhere.

**Comment by slavicd** [comment]
> I'm encountering this issue now and trying to find a work around.

I ended up publishing the [ignition config file](https://github.com/spatie/laravel-ignition/blob/main/config/ignition.php) and removing the `QueryRecorder` recorder.

**Comment by alohstan** [comment]
Incase anyone is still facing this issue simple use the laravel `model::withoutEvents(...)` if you're using Eloquent but when using regular DB Facade use below, also you could make it a macro 

```php
        $dispatcher = DB::getEventDispatcher(); // Disable events to avoid overhead
        try {
            DB::setEventDispatcher(new NullDispatcher($dispatcher));
            //you customer code
        } finally {
            // Ensure the dispatcher is reset to avoid affecting other queries
            DB::setEventDispatcher($dispatcher);
        }
```
