### ISSUE TITLE
Event listeners that are defined in $listen are fired twice if shouldDiscoverEvents is true

### ISSUE THREAD

**Issue by alec-joy** [laravel/framework#30027]
- Laravel Version: 5.8.35
- PHP Version: 7.2.20-2+ubuntu16.04.1+deb.sury.org+1

### Description:
If the shouldDiscoverEvents() method of the event service provider is set to true, and there are also some event/listener pairs defined in the $listen array, then the listeners in the $listen array are called twice every time an event fires

### Steps To Reproduce:
- Create an event/listener pair, set each to Log::debug that they were called
- Add them to the $listen array in EventServiceProvider
- Turn on event discovery as defined [here](https://laravel.com/docs/5.8/events#event-discovery)
- fire the event in tinker
- Open your log file and observer 1 log entry for the event, 2 for the listener

**Comment by nmokkenstorm** [comment]
The link you supplied specifies that the automatically discovered events are in addition to the manually registered ones, but I agree that having duplicates because of that doesn't make a ton of sense. I'll look into making a PR for this

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
