### ISSUE TITLE
JsonResource Collection Doesn't Take "wrap" changes.

### ISSUE THREAD

**Issue by AbbyJanke** [laravel/framework#30023]
- Laravel Version: 6.03
- PHP Version: 7.3.6
- Database Driver & Version: MySQL, 5.7.26

### Description:
Even when adding a static variable to a JsonResource for API responses, when doing a collection (Model::all() or Model::paginate()) it does not take into account the change of name and always uses `data` for the wrapping. Also does not recognize `withoutWrapping()`. It seems these only work on display single records.

### Steps To Reproduce:
```php
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return ProductResource::collection(Product::paginate());
    }
```

```php
    /**
     * The "data" wrapper that should be applied.
     *
     * @var string
     */
    public static $wrap = 'product';
```

It will then still return the collection under the `data` wrap. I feel like it would make more sense to have it pluralize the word, so `product` gets used for the single record, and `products` gets used for the collection.

**Comment by staudenmeir** [comment]
At the moment, this is only possible with a separate [collection resource](https://laravel.com/docs/eloquent-resources#resource-collections):

```php
class ProductCollection extends ResourceCollection
{
    public static $wrap = 'products';
}

return new ProductCollection(Product::paginate());
```

**Comment by AbbyJanke** [comment]
@staudenmeir Thanks, missed the collection resource docs.
