### ISSUE TITLE
[6.0] Monolog Channel can't use NullHandler in Monolog 2.0

### ISSUE THREAD

**Issue by ktanakaj** [laravel/framework#30026]
- Laravel Version: 6.0.3
- PHP Version: 7.3

### Description:
I used [Monolog Channe](https://readouble.com/laravel/6.0/en/logging.html)l with [NullHandler](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/NullHandler.php) on Laravel 5.8. It is worked fine.
But Laravel 6.0 throw following exception.

```
[2019-09-18 09:59:05] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (Error(code: 0): Call to undefined method Monolog\\Handler\\NullHandler::setFormatter() at /vagrant/server/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:376)
[stacktrace]
#0 /vagrant/server/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(347): Illuminate\\Log\\LogManager->prepareHandler(Object(Monolog\\Handler\\NullHandler), Array)
#1 /vagrant/server/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(185): Illuminate\\Log\\LogManager->createMonologDriver(Array)
```

I guess it is Monolog 1.x -> 2.0 compatibility problem.
Laravel 6.0 newly depend on Monolog 2.0 instead 1.x.

`Illuminate/Log/LogManager.php` use [`Monolog\Handler\HandlerInterface`](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/HandlerInterface.php).
The interface has `setFormatter()` in Monolog 1.x ([old](https://github.com/Seldaek/monolog/blob/1.x/src/Monolog/Handler/HandlerInterface.php)).
However In Monolog 2.0, `setFormatter()` moved to [`Monolog\Handler\FormattableHandlerInterface`](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/FormattableHandlerInterface.php).
LogManager must check `FormattableHandlerInterface` before call `setFormatter()` if there are Monolog 2.0.

### Steps To Reproduce:
My `config/logging.php` is following.
```
'fluent' => [
    'driver'  => 'monolog',
    'level' => 'info',
    'handler' => env('FLUENTD_ENABLE', true) ? App\Logging\FluentdHandler::class : Monolog\Handler\NullHandler::class,
],
```

**Comment by driesvints** [comment]
Did you add these changes? https://github.com/laravel/laravel/commit/c70c986e58fe1a14f7c74626e6e97032d4084d5f

**Comment by ktanakaj** [comment]
@driesvints 
No. I use `NullHandler` as my custom monolog channel.
But I think that this null channel will occur the same problem.

**Comment by driesvints** [comment]
I managed to reproduce this. Thanks for reporting. Appreciating a PR if you could whip one up.
