### ISSUE TITLE
Can I use Laravel 6.0 on PHP 7.0?

### ISSUE THREAD

**Issue by DavidRotert** [laravel/framework#30028]
Hello,

I want to create an application for my company to manage entries in a database. I only have restricted access the server I could use for the project and I can not upgrade from PHP 7.0 to 7.x because of compatibility to other software. I want to ask if there is a way to use Laravel 6.0 with PHP 7.0. Is it possible to use something like Polyfill? Or is Laravel 6.0 still compatible with 7.0? For my application I need standard features like ORM, authentication and templates.

**Comment by browner12** [comment]
Laravel 6 requires PHP 7.2.

https://github.com/laravel/framework/blob/6.x/composer.json

Please ask in the forums if you understand the risk, and are still looking to get around this requirement.

**Comment by DavidRotert** [comment]
Okay, thank you for your answer.
