### ISSUE TITLE
Memory limit hit by command output

### ISSUE THREAD

**Issue by EmanueleCoppola** [laravel/framework#30020]
- Laravel Version: 6.0.3
- PHP Version: 7.3.9
- Database Driver & Version: //

### Description:
The memory gets filled up very quickly when printing too much output in the console.
I created a database import command that imports about 500K record into a DB, here's a mock of what it does:

```php
<?php

namespace App\Console\Commands\Import;

use Illuminate\Console\Command;

class ImportCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'bigimport:import';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Import something.';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        for($i = 0; $i < 500000; $i++) {
            $this->info('Number i: ' . $i;
            // Write in DB $i
            for($j = 0; $j < rand(5, 15); $j++) {
                $this->info('Number j: ' . $j);
                 // Relate in DB $j with $i
            }
        }
    }
}


```

After a while the script exits saying that this file [BufferedOutput.php](https://github.com/symfony/console/blob/fcdd5b072fab9da81815eb349602b6b46e844724/Output/BufferedOutput.php#L37) is consuming too much memory (of course the higher your memory limit is, the lower the possibility to reach it).

Does the output have to be stored in memory for some reason?
Is it an expected behaviour?
Could it be changed in cases like this?

### Steps To Reproduce:
Run the code above for a few minutes (or hours) until it reaches the memory limit.

**Comment by dwightwatson** [comment]
Try disabling the query log if you haven't already (`DB::disableQueryLog()`) - Laravel could be exhausting memory usage by keeping track of every database query you perform.

**Comment by EmanueleCoppola** [comment]
@dwightwatson I'm pretty sure that the CLI output buffer is the cause of memory exhausting since I received an error pointing at the file BufferedOutput.php, also, you can see that every time you call the doWrite() function it stores in memory the message you want to output, it's probably never flushing that variable.

**Comment by nmokkenstorm** [comment]
Can not reproduce. The Symfony class used by Laravel internally is writing to the PHP output stream by default.

Tangentially related, would your use case not benefit from just using the progress bar shipped with Laravel by default?

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.
