### ISSUE TITLE
Illuminate\Database\Query\Builder::having does not support nested having clauses

### ISSUE THREAD

**Issue by mgrinspan** [laravel/framework#30022]
The `where` method automatically delegates to `whereNested` when necessary. 

I'm mostly creating this issue to find out if there's a specific reason that `having` doesn't have this functionality, or if it was simply overlooked. I don't want to work on a PR if we don't actually want it. 

Thanks!

**Comment by xuanquynh** [comment]
Please use the issue template to provide more information, specially "Steps to Reproduce"!

**Comment by staudenmeir** [comment]
Please see https://github.com/laravel/ideas/issues/999.
