### ISSUE TITLE
$redirectTo (Auth controllers)

### ISSUE THREAD

**Issue by Larsklopstra** [laravel/framework#30036]
Consider setting the `$redirectTo` variable in one place whilst still being able to overwrite per controller.

```php
# Optional, but will overwrite the global variable
protected $redirectTo = '/overwritten';
```

**Comment by YWatchman** [comment]
Keep in mind that some people redirect to other pages than default. For example on success the register route will redirect to a thank you page and the login route to the dashboard etc.

**Comment by Larsklopstra** [comment]
@YWatchman That's why you still should be able to overwrite it on controller level

**Comment by tontonsb** [comment]
Yeah, there has been a bunch of PRs addressing that issue, but that `/home` bug is still there. Even after removal of scaffoldings from framework.

Could at least change it to `/`...

**Comment by ajoy39** [comment]
I'm having a little trouble understanding what you're trying to override, do you mean where the user gets redirected to after they login, if they are already logged in but can't access that particular controller, or if they aren't logged in at all?

**Comment by tontonsb** [comment]
@ajoy39 I think the point is there should be an ability to override all five at once. It's super annoying to always have to override that `/home` in five places and usually forget on one or two.

Named route, config value, changing it to `/` that at least wouldn't 404 on every app... all of those have been offered and rejected.

**Comment by YWatchman** [comment]
> @YWatchman That's why you still should be able to overwrite it on controller level

I misunderstood you then.

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!
