### ISSUE TITLE
composer container with dependency failure (moontoast and bcmath)

### ISSUE THREAD

**Issue by mbehnke** [laravel/framework#30030]
- Laravel Version: 6.0.3
- PHP Version: 7.0
- Database Driver & Version: no deps

### Description:
Trying to install laravel through composer container (docker hub).

### Steps To Reproduce:
https://git-ce.rwth-aachen.de/itc/sub/sus/gigamove/issues/1
or
https://github.com/composer/docker/issues/97

`
PS C:\temp\gigamove20> docker run --rm -ti --tty --volume ${PWD}\laravel:/app composer:1.9 composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - moontoast/math 1.1.2 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - moontoast/math 1.1.1 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - moontoast/math 1.1.0 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - Installation request for moontoast/math ^1.1 -> satisfiable by moontoast/math[1.1.0, 1.1.1, 1.1.2].

  To enable extensions, verify that they are enabled in your .ini files:
    - /usr/local/etc/php/php-cli.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-sodium.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-zip.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
PS C:\temp\gigamove20> docker run --rm -ti --tty --volume ${PWD}\laravel:/app composer composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - moontoast/math 1.1.2 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - moontoast/math 1.1.1 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - moontoast/math 1.1.0 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - Installation request for moontoast/math ^1.1 -> satisfiable by moontoast/math[1.1.0, 1.1.1, 1.1.2].

  To enable extensions, verify that they are enabled in your .ini files:
    - /usr/local/etc/php/php-cli.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-sodium.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-zip.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

`

**Comment by staudenmeir** [comment]
As the message says, you need to enable the `ext-bcmath` PHP extension.

**Comment by belThomas84** [comment]
@mbabker There are so many things wrong with this post.

1. This is for bugs, not for support requests.
2. Laravel 6.0 doesn't support PHP 7.0.
3. (at least) double posting.
4. Not reading the error message that says: "the requested PHP extension bcmath is missing from your system."

Please always read the message and decide from which platform you want support from. Anything else is just unnecessary work for those people who want to help answering issues and spend their time for it. I expect that to be known, especially from someone who studied economic sciences.

**Comment by mbabker** [comment]
Umm, did I miss something?
