### ISSUE TITLE
Model HasEvents does not have forceDeleted method

### ISSUE THREAD

**Issue by umituz** [laravel/framework#30039]
- Laravel Version: 6.0.3
- PHP Version:7.2.1

### Description:
vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php file does not have forceDeleted method.  getObservableEvents() does have forceDeleted but method not exists.  I get error when using forceDeleted in model file in boot method 

self::deleted(function ($model) {} );
deleted is working
self::forceDeleted(function ($model) {} );
forceDeleted is not working because of method not exists

When I added this method everything is work fine but not including by default.
public static function forceDeleted($callback)
    {
        static::registerModelEvent('forceDeleted', $callback);
    }

**Comment by umituz** [comment]
> * Laravel Version: 6.0.3
> * PHP Version:7.2.1
> 
> ### Description:
> vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php file does not have forceDeleted method. getObservableEvents() does have forceDeleted but method not exists. I get error when using forceDeleted in model file in boot method
> 
> self::deleted(function ($model) {} );
> deleted is working
> self::forceDeleted(function ($model) {} );
> forceDeleted is not working because of method not exists

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
