### ISSUE TITLE
Pivot tables and markdown mailables - 

### ISSUE THREAD

**Issue by trevorpan** [laravel/framework#30034]
Hi, 

I'm not sure if this is a bug. 

However, I'm on Laravel 5.8* and unable to access two tables' data in the handle() method on the `SendOrderPlacedNotification`. 

When referencing this https://laracasts.com/series/laravel-from-scratch-2018/episodes/32
it seems like only one "event" based model is made available.

_The goal is simply to show $job-jobtitle in the message of the $order mail._

This section: https://laravel.com/docs/5.8/mail#view-data shows the ability to make a variable available to the mailable. As I'm using markdown mailable, this section applies: https://laravel.com/docs/5.8/mail#writing-markdown-messages

The event: https://laravel.com/docs/5.8/events#defining-events
```
    /**
     * Create a new event instance.
     *
     * @return void
     */
    public function __construct(Order $order)
    {
        //
        $this->order = $order;
    }
```
```
use App\Job;
use App\Order;
use Illuminate\Http\Request;
use Illuminate\Bus\Queueable;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;
use Illuminate\Contracts\Queue\ShouldQueue;

class OrderPlacedMail extends Mailable
{
    use Queueable, SerializesModels;
   /**
     * The job instance.
     *
     * @var Job
     */
    public $job;

    /**
     * The order instance.
     *
     * @var Order $order
     */
    public $order;

    /**
     * Create a new message instance.
     *
     * @param Job $job
     * @param Order $order
     * @return void
     */
    public function __construct($order, $job)
    {
        $this->order = $order;
        $this->job = $job->toArray();
    }
```
```
class SendOrderPlacedNotification implements ShouldQueue
{
....
    /**
     * Handle the event.
     *
     * @param Job $job
     * @param  object  $event
     * @return void
     */
    public function handle(OrderPlaced $event, $job)
    {
         //   dd($event);
        Mail::to($event->order->user->email)->send(
            new OrderPlacedMail($event->order, $job)
        );
    }
```
https://laravel.com/docs/5.8/mail#view-data 

https://github.com/laravel/framework/issues/18597 - this issue gave me the idea to send the $job as an array. As an array, or just a plain variable, I consistently get a 
```
Too few arguments to function App\Listeners\SendOrderPlacedNotification::handle(), 1 passed and exactly 2 expected
```
https://laracasts.com/discuss/channels/laravel/use-variables-inside-the-markdown-mailables

```
// Here's the mail component, I've added the addition $job->jobtitle variable (not sure if it should just be $job, //but it does not seem to matter, as it fails on the handle() method of the notification
@component('mail::message', ['job' => $job->jobtitle])
# Order confirmation: {{ $job->jobtitle }}

We appreciate your interest in this job posting.

@component('mail::button', ['url' => '/orders/' . $order->id . '/' . $order->confirmation_number])
View job now
@endcomponent

Thank you,<br>
{{ config('app.name') }}
@endcomponent
```

From what I can tell in the docs, only properties of "one" table can be made available to the markdown mailable. The `with()` method shows multiple variables/(columns in the table) being sent, but not different tables.

In this case, I'm using a classic orders table that does not allow me to reach the $job directly, it's through a pivot table that has this type: `job_id, order_id`

e.g. 
`$order->pivot->job->jobtitle`

Am I wrong? Is this by design? 

Are event based mails only allowed to pass in one table (in this case the order), and then you can only access what you need through the order?

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
