### ISSUE TITLE
Method Illuminate\Http\Request::validate does not exist

### ISSUE THREAD

**Issue by gorcer** [laravel/framework#30041]
- Laravel Version: 5.7.28
- PHP Version: 7.2
- Database Driver & Version: MySQL

### Description:
I'm try to login in Voyager admin panel.

In Illuminate\Foundation\Auth\AuthenticatesUsers i found method:

 ```
   protected function validateLogin(Request $request)
    {
        $request->validate([
            $this->username() => 'required|string',
            'password' => 'required|string',
        ]);
    }

```
but Request doesn't exist method validate!
And i have a error:
Method Illuminate\Http\Request::validate does not exist

Please help!

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by lenmen** [comment]
Hey,

I do also have this problem on version 6.12.0. with the following exception message:
```
Method Illuminate\Http\Request::validate does not exist.
/app/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php#103
```

I am passing the instansce `use Illuminate\Http\Request` to the function `sendResetLinkEmail` from the trait

```
use Illuminate\Foundation\Auth\SendsPasswordResetEmails
```

and it happens here:

```
    /**
     * Send a reset link to the given user.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Http\JsonResponse
     */
    public function sendResetLinkEmail(Request $request)
    {
        $this->validateEmail($request);

        ...
    }

    /**
     * Validate the email for the given request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return void
     */
    protected function validateEmail(Request $request)
    {
        $request->validate(['email' => 'required|email']);
    }
```

I am wondering what I am missing here.

**Comment by lenmen** [comment]
Never mind my comment above. I had commented out the service provider `Illuminate\Foundation\Providers\FoundationServiceProvider::class` in my config directory so thats why it didn't work. 😅
