### ISSUE TITLE
Multi-Auth using Token Guards with different storage key types

### ISSUE THREAD

**Issue by tylernathanreed** [laravel/framework#30045]
### Environment:
- Laravel Version: 6.0.3 (technically doable since 5.6)
- PHP Version: 7.3.8
- Database Driver & Version: SQL Server 2014

### Description:

I have a project that uses multiple forms of authentication, two of which are token guards.

One of the token guards has overridden the storage key name to be the primary key of the authorizing model. This was a requirement in our business as the client wanted to only use a single key, and they already knew the primary key of the model. When authenticating under this model, a request parameter of "user_id" is provided. I'll refer to this guard as the "customer" guard.

The second token guard, which authenticates a different model type, uses the more traditional storage key name of "api_token". Additionally, the authentication for this model goes through the bearer token in the request header. I'll refer to this guard as the "client" guard.

I have a use-case that requires both forms of authentication within the same request. Our application services several clients and customers, and certain customers are shared between multiple clients. We have a customer portal, some of which are client-branded, and therefore the portal uses the client authentication to establish the entity making the request, but the person signed into the portal is the customer.

However, there are a few key endpoints where only the client is authenticated, and not the customer. These are typically for customer authentication routes (like login, register, etc.), and only the information for the client authentication is provided.

Unfortunately, the request results in a bearer token intended for the client guard, but the customer guard is also capable of picking it up (as that is the intended fallback when the request input parameter is missing). This ends up throwing an exception, as the api token (which is a string) is compared against the customer id column (which is an integer). On SQL Server databases, this violates the schema and results in an exception.

### Steps To Reproduce:

Register two guards "customer" and "client", with the following configuration:

```
'guards' => [
    'customer' => [
        'driver' => 'token',
        'provider' => 'customers',
        'input_key' => 'user_id',
        'storage_key' => 'id'
    ],
    'client' => [
        'driver' => 'token',
        'provider' => 'clients'
    ]
]
```

Then submit a request containing a bearer token (intended for the "client" guard), and at any point during the request, ask for the authenticated customer (via `Auth::guard('customer')->user()`).

### Recommendation:

I can think of two solutions to this problem:

**1)** Don't look for a bearer token when an input key is explicitly provided

This would change the token guard to ignore the bearer token in the "customer" guard, and therefore return null (which is the result I'm expecting).

**2)** Add a "storage_key_type" parameter

If we could add a "storage_key_type" parameter, as set it as "integer", then if the bearer token was recognized as non-numeric, it would ignore it and return null (which is the result I'm expecting).

**Comment by driesvints** [comment]
```
Laravel Version: 6.0.3 (technically doable since 5.6)
PHP Version: 7.1.1
```

This isn't even possible since Laravel 6.0 requires PHP 7.2

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by tylernathanreed** [comment]
@driesvints My apologies. My PHP installation was swapped out for a Laravel 5.1 application when I ran `php -v`. The Laravel 6 application actually runs on PHP 7.3.8. I'll update the description.

I'm reporting this as a bug as I believe my issue describes a violation of the multi-auth agenda for token guards. Currently, I am unable to have two configured token guards (where one uses a string storage key for bearer tokens, and the other uses an integer storage key for request input) and pass a bearer token (intended for the string-storage token guard).

Since Laravel will check for a bearer token (even if I've opted for a custom input key, and have no intention of using a bearer token for that guard), the database will throw an exception when it compares a string value against an integer column.

To be clear, this is the section of code that is behaving in such a way that causes my issue:

https://github.com/laravel/framework/blob/6.x/src/Illuminate/Auth/TokenGuard.php#L92-L114

```php
/**
 * Get the token for the current request.
 *
 * @return string
 */
public function getTokenForRequest()
{
    $token = $this->request->query($this->inputKey);

    if (empty($token)) {
        $token = $this->request->input($this->inputKey);
    }

    if (empty($token)) {
        $token = $this->request->bearerToken();
    }

    if (empty($token)) {
        $token = $this->request->getPassword();
    }

    return $token;
}
```

Specifically, lines 105 to 107 look for a bearer token when a token couldn't be found in the request. Technically, it will find a bearer token, but it shouldn't be ingesting it, as I told the integer-storage guard to expect the api token to be in the request.

**Comment by driesvints** [comment]
I don't have time atm to deep dive into this but appreciating if anyone else can help out.

**Comment by tylernathanreed** [comment]
@driesvints 

Is there any additional information that I can provide for you, or are you just looking for someone (other than me) to verify and replicate the issue?

**Comment by driesvints** [comment]
Hey @tylernathanreed. I've been looking into this again and what you're asking is basically a change in behavior. The TokenGuard never was documented and I think it's the lack of that that's causing the confusing here. As you noted with the link to the affecting code, when no input key can be found, the TokenGuard falls back on checking for a bearer token. This is the expected behavior. 

What you could do is implement your custom TokenGuard that doesn't follows this behavior or open up an issue on the ideas repo to propose alterations be made to the TokenGuard.
