### ISSUE TITLE
Numeric keys in resources & $preserveKeys = true

### ISSUE THREAD

**Issue by Ir00man** [laravel/framework#30052]
- Laravel Version: 5.8.35
- PHP Version: 7.1.29
- Database Driver & Version: MySQL

### Description:

As I understand that's not a new bug and was discussed a lot and even "was fixed" but still if we have JsonResource and trying to return some Collection (via JsonResource::collection method) keyed by some numeric field - we will get a plain array not an object as a output.

I mean that even if we use `public $preserveKeys = true;`
Btw, I **can't** find any case where `$preserveKeys` has an effect, in all my tests `$preserveKeys` has no effect at all.

How to deal with that? How to have an object `{}` with keys outputted instead of array `[]`?

#27325

### Steps To Reproduce:

**/app/Http/Resources/Test.php** file:

```
namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class Test extends JsonResource
{
    public $preserveKeys = true;
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        //dd($this);
        return $this->resource;
    }
}
```

**/routes/web.php** file:

```
use Illuminate\Http\Request;
use Illuminate\Support\Collection;

Route::get('test', function () {
    $data = Collection::make([
        [
            'id' => 1,
            'name' => 'name1',
        ],
        [
            'id' => 2,
            'name' => 'name2',
        ],
    ])->keyBy('id');

    //dd($data->toArray());
    return \App\Http\Resources\Test::collection($data);
});
```

Now you will get in browser:

`[{"id":1,"name":"name1"},{"id":2,"name":"name2"}]`

But if you uncomment `//dd($data->toArray());` you will see:

```
array:2 [▼
  1 => array:2 [▼
    "id" => 1
    "name" => "name1"
  ]
  2 => array:2 [▼
    "id" => 2
    "name" => "name2"
  ]
]
```

**Comment by staudenmeir** [comment]
You are using `withoutWrapping()`, right? With a wrapper, `$preserveKeys` works correctly. Not sure if it should also work without one.

**Comment by Ir00man** [comment]
Oh yeah, I'm using `Resource::withoutWrapping();`
And I've just tested that it's working good with wrapping (which is default)
But I don't see any reason why it shouldn't work when the wrapping is turned off.
Any ideas?

**Comment by staudenmeir** [comment]
It's caused by this line:

https://github.com/laravel/framework/blob/1bbe5528568555d597582fdbec73e31f8a818dbc/src/Illuminate/Http/Resources/Json/ResourceResponse.php#L71

**Comment by Ir00man** [comment]
Nope, I've checked and this method is not called at all in my case.

**Comment by Ir00man** [comment]
Yes, you are right, this code 
```
$w = array_merge_recursive([1 => [1 => 1, 2 => 2]]);
var_dump($w);
```
outputs this
```
array(1) {
  [0]=>
  array(2) {
    [1]=>
    int(1)
    [2]=>
    int(2)
  }
}
```

As for me it's weird and undocumented behavior of `array_merge_recursive` function...

**Comment by staudenmeir** [comment]
The behavior is documented for [`array_merge()`](https://www.php.net/manual/en/function.array-merge.php):

> Values in the input arrays with numeric keys will be renumbered with incrementing keys starting from zero in the result array.

**Comment by Ir00man** [comment]
Sure it is. But look at the second level. All keys are preserved (but they are numeric as well).

**Comment by Ir00man** [comment]
Does somebody know what's an expected behavior for this input data:
```
$data = [1 => [1 => 11, 2 => 12]];
$with = [1 => [2, 3]];
$additional = ['some' => 1];
```
What should be an output with `withoutWrapping()` applied?

**Comment by driesvints** [comment]
@staudenmeir so is this a bug or not?

**Comment by staudenmeir** [comment]
@driesvints I think it is.

**Comment by Ir00man** [comment]
Seems that nobody except me using API responses without extra wrapping and keyed by primary ID to cut off an extra transformation from client-side.
For sure, this transformation is simple on client-side, like:
```
let response = [{id:1, name:'bob'}, {id:2, name:'alice'}];
let responseKeyed = {};
response.map((v)=>{responseKeyed[v.id] = v});
```

But as for me it's better to have **working** `$preserveKeys` option

**Comment by jk2** [comment]
I had a different use case but solved it by overwriting toResponse of JsonResource.

In Test.php:
```
public function toResponse($request)
{
    return $this->resource;
}
```

Then it won't call problematic wrap function in ResourceResponse.

Not sure if using array_replace_recursive instead of array_merge_recursive would fix the bug on wrap function.

**Comment by straube** [comment]
I ran a couple tests over here and it seems `array_replace_recusrive` not always gives the same result as `array_merge_recursive`. It does work for some cases but it seems simply changing the function would introduce new bugs.

**Comment by Ir00man** [comment]
@jk2 Thx for sharing.
@straube Yeah, same for me. I just don't know what is expected to be outputted in case I mentioned above https://github.com/laravel/framework/issues/30052#issuecomment-533879458

**Comment by taylorotwell** [comment]
No plans on changing any behavior here.
