### ISSUE TITLE
selectRaw() doesn't work inside of withCount()

### ISSUE THREAD

**Issue by rimace** [laravel/framework#30050]
- Laravel Version: 6.0.3
- PHP Version: 7.2.16
- Database Driver & Version: libmysql - mysqlnd 5.0.12

### Description:
When using a closure inside of `withCount()`, the method `selectRaw('...')` is ignored whereas `select(DB::raw('...'))` works perfectly fine.

### Steps To Reproduce:
	Article::withCount([
		'contracts as sum_demands' => function($query) {
			$query->select(DB::raw('SUM(`demands`)')); // <-- this works
			$query->selectRaw('SUM(`demands`)'); // <-- this doesn't work
		}
	]);

When using `$query->selectRaw('SUM(demands)'));` the output query is:
```
SELECT
	`articles`.*,
	(SELECT COUNT(*) // note the COUNT(*) here, this should me SUM(demands)
	FROM `contracts`
	WHERE `articles`.`id` = `contracts`.`article_id`
) AS `sum_demands`
FROM `articles`
```

**Comment by staudenmeir** [comment]
`select(DB::raw())` and `selectRaw()` are actually different: `selectRaw()` is equivalent to `addSelect(DB::raw())`, not `select(DB::raw())`.

I just saw that the documentation is incorrect on this point

**Comment by rimace** [comment]
Thanks for your help!
So would it make sense for future cases to create an idea to rename `selectRaw()` to `addSelectRaw()`? I'm not sure if renaming a function is worth creating an idea or if a pull request is enough.

**Comment by staudenmeir** [comment]
I don't think we should rename the method. This would be a major breaking change and affect a lot of users.

**Comment by driesvints** [comment]
I don't think changing the method name is a good idea either. Feel free to send in a PR to the docs. Thanks.

**Comment by driesvints** [comment]
I sent in a pr for this: https://github.com/laravel/docs/pull/5511
