### ISSUE TITLE
Migration Rollback not delete columns added from last migration

### ISSUE THREAD

**Issue by malayvuong** [laravel/framework#30051]
- Laravel Version: 6.x
- PHP Version: 7.1.31
- Database Driver & Version: MySQL 5.7.26

### Description:
I create a migration to add new columns into table, new column are added.
Then I rollback to fix some column informations but these column not delete from the table.
First time I think this is my mistake, but then I try do it again and it's not happen.

### Steps To Reproduce:
1. Create new migration by `php artisan make:migration products --table=products`
2. Add addition columns like this:
```
$table->double('import', 20, 2)->default(0)->comment('Import price');
$table->double('sell', 20, 2)->default(0)->comment('Sell price');
```
3. Run migration `php artisan migrate`
4. Rollback migration `php artisan migrate:rollback` (you can put step=1)
5. Column not deleted

**Comment by malayvuong** [comment]
I'm sorry,
It's may my mistake or not to complete to understand all about Laravel migration cause I'm new here for fews month.
If this code has problem to rollback please push me on an URL, and close this stupid issue for me, please.
This's my complete code:
```php
<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class Products extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('products', function (Blueprint $table) {
            $table->double('import', 20, 2)->default(0)->comment('Import price')->after('confirm');
            $table->double('sell', 20, 2)->default(0)->comment('Sell price')->after('import');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('products', function (Blueprint $table) {
            //
        });
    }
}
```

**Comment by staudenmeir** [comment]
Use `dropColumn()`:

```php
public function down()
{
    Schema::table('products', function (Blueprint $table) {
        $table->dropColumn('import', 'sell');
    });
}
```

**Comment by malayvuong** [comment]
Thanks, I'll close this issue now.
I'm so sorry to bother you, just because of my poor knowledge.
