### ISSUE TITLE
Laravel 6 proc_open

### ISSUE THREAD

**Issue by tomswinkels** [laravel/framework#30054]
- Laravel Version: 6
- PHP Version: 7.3

### Description:

After installing Laravel 6, i get the following error message:

`The Process class relies on proc_open, which is not available on your PHP installation.`

I don't have find anything in the docs about this?

**Comment by sepehrr** [comment]
I faced with the same issue when I wanted to put my Laravel 6 application on a shared host(PHP 7.2) and faced the error:

> The Process class relies on proc_open, which is not available on your PHP installation.

Problem happens on `/vendor/facade/ingnition/src/Middleware/AddGitInformation.php`
file and when `$this->command("git log --pretty=format:'%H' -n 1");` is called. I solved my problem by editing `AddGitInformation.php` but I guess it would be better if Laravel6 not to depend on `proc_open` if possible.

**Comment by antonkomarev** [comment]
I think its issue related to Symfony Process package.
https://github.com/symfony/process/blob/master/CHANGELOG.md#400

**Comment by driesvints** [comment]
Heya, this seems to be related to Symfony and not Laravel.

**Comment by manukn** [comment]
It is because of Flare error reporting service enabled
There is workaround for this.

Publish flare config file
` php artisan vendor:publish --tag=flare-config`

and in config/flare.php

Set
```php 
'collect_git_information' => false 
```

```php
'reporting' => [
        'anonymize_ips' => true,
        'collect_git_information' => false,
        'report_queries' => true,
        'maximum_number_of_collected_queries' => 200,
        'report_query_bindings' => true,
        'report_view_data' => true,
    ],
```

**Comment by thusithawijethunga** [comment]
> It is because of Flare error reporting service enabled in debug mode
> There is a workaround for this.
> 
> Publish flare config file
> ` php artisan vendor:publish --tag=flare-config`
> 
> and in config/flare.php
> 
> Set
> 
> ```
> 'collect_git_information' => false 
> ```
> 
> ```
> 'reporting' => [
>         'anonymize_ips' => true,
>         'collect_git_information' => false,
>         'report_queries' => true,
>         'maximum_number_of_collected_queries' => 200,
>         'report_query_bindings' => true,
>         'report_view_data' => true,
>     ],
> ```

This is working for Php 7.2, shared hosting. thanks

**Comment by enlajuega** [comment]
> It is because of Flare error reporting service enabled in debug mode
> There is a workaround for this.
> 
> Publish flare config file
> ` php artisan vendor:publish --tag=flare-config`
> 
> and in config/flare.php
> 
> Set
> 
> ```
> 'collect_git_information' => false 
> ```
> 
> ```
> 'reporting' => [
>         'anonymize_ips' => true,
>         'collect_git_information' => false,
>         'report_queries' => true,
>         'maximum_number_of_collected_queries' => 200,
>         'report_query_bindings' => true,
>         'report_view_data' => true,
>     ],
> ```

Muchas gracias... esta solución sirvió de mucho... thank!!!

**Comment by JASH-JARIWALA** [comment]
> It is because of Flare error reporting service enabled in debug mode
> There is a workaround for this.
> 
> Publish flare config file
> ` php artisan vendor:publish --tag=flare-config`
> 
> and in config/flare.php
> 
> Set
> 
> ```
> 'collect_git_information' => false 
> ```
> 
> ```
> 'reporting' => [
>         'anonymize_ips' => true,
>         'collect_git_information' => false,
>         'report_queries' => true,
>         'maximum_number_of_collected_queries' => 200,
>         'report_query_bindings' => true,
>         'report_view_data' => true,
>     ],
> ```

thanks man works for PHP 7.2

**Comment by vtkiet911** [comment]
> It is because of Flare error reporting service enabled in debug mode
> There is a workaround for this.
> 
> Publish flare config file
> ` php artisan vendor:publish --tag=flare-config`
> 
> and in config/flare.php
> 
> Set
> 
> ```
> 'collect_git_information' => false 
> ```
> 
> ```
> 'reporting' => [
>         'anonymize_ips' => true,
>         'collect_git_information' => false,
>         'report_queries' => true,
>         'maximum_number_of_collected_queries' => 200,
>         'report_query_bindings' => true,
>         'report_view_data' => true,
>     ],
> ```

Thanks you very much! ♥

**Comment by hbouchefra** [comment]
> It is because of Flare error reporting service enabled in debug mode
> There is a workaround for this.
> 
> Publish flare config file
> ` php artisan vendor:publish --tag=flare-config`
> 
> and in config/flare.php
> 
> Set
> 
> ```
> 'collect_git_information' => false 
> ```
> 
> ```
> 'reporting' => [
>         'anonymize_ips' => true,
>         'collect_git_information' => false,
>         'report_queries' => true,
>         'maximum_number_of_collected_queries' => 200,
>         'report_query_bindings' => true,
>         'report_view_data' => true,
>     ],
> ```

Thanks a lot from Amsterdam!

**Comment by nguyenbinh23** [comment]
i did all, but my shared host still not working

**Comment by ishendyweb** [comment]
@nguyenbinh23 What is the problem now? Is it still the same exception? can you share your ./config/flare.php file?

**Comment by nguyenbinh23** [comment]
i added ./config/flare.php in my cpanel shared host, and changed it like u but still not working

**Comment by ishendyweb** [comment]
Yes. Just share more information. Like what is the current exception? and what is the code inside your `flare.php` ?

**Comment by nguyenbinh23** [comment]
<?php

return [
    /*
    |
    |--------------------------------------------------------------------------
    | Flare API key
    |--------------------------------------------------------------------------
    |
    | Specify Flare's API key below to enable error reporting to the service.
    |
    | More info: https://flareapp.io/docs/general/projects
    |
    */

    'key' => env('FLARE_KEY'),

    /*
    |--------------------------------------------------------------------------
    | Reporting Options
    |--------------------------------------------------------------------------
    |
    | These options determine which information will be transmitted to Flare.
    |
    */
    'collect_git_information' => false,

    'reporting' => [
        'anonymize_ips' => true,
        'collect_git_information' => false,
        'report_queries' => true,
        'maximum_number_of_collected_queries' => 200,
        'report_query_bindings' => true,
        'report_view_data' => true,
    ],
];


this is my flare.php

**Comment by nguyenbinh23** [comment]
`<?php

return [
    /*
    |
    |--------------------------------------------------------------------------
    | Flare API key
    |--------------------------------------------------------------------------
    |
    | Specify Flare's API key below to enable error reporting to the service.
    |
    | More info: https://flareapp.io/docs/general/projects
    |
    */

    'key' => env('FLARE_KEY'),

    /*
    |--------------------------------------------------------------------------
    | Reporting Options
    |--------------------------------------------------------------------------
    |
    | These options determine which information will be transmitted to Flare.
    |
    */
    'collect_git_information' => false,

    'reporting' => [
        'anonymize_ips' => true,
        'collect_git_information' => false,
        'report_queries' => true,
        'maximum_number_of_collected_queries' => 200,
        'report_query_bindings' => true,
        'report_view_data' => true,
    ],
];
`

this is my flare.php, maybe i change it first in local folder and later uploading to shared host?

**Comment by nguyenbinh23** [comment]
thanks sir, i waited  30min and my website worked @@

**Comment by AhmedHdeawy** [comment]
> It is because of Flare error reporting service enabled in debug mode
> There is a workaround for this.
> 
> Publish flare config file
> ` php artisan vendor:publish --tag=flare-config`
> 
> and in config/flare.php
> 
> Set
> 
> ```
> 'collect_git_information' => false 
> ```
> 
> ```
> 'reporting' => [
>         'anonymize_ips' => true,
>         'collect_git_information' => false,
>         'report_queries' => true,
>         'maximum_number_of_collected_queries' => 200,
>         'report_query_bindings' => true,
>         'report_view_data' => true,
>     ],
> ```

thanks @manukn  it works for php7.3

**Comment by eduardosnm** [comment]
> It is because of Flare error reporting service enabled in debug mode
> There is a workaround for this.
> 
> Publish flare config file
> ` php artisan vendor:publish --tag=flare-config`
> 
> and in config/flare.php
> 
> Set
> 
> ```
> 'collect_git_information' => false 
> ```
> 
> ```
> 'reporting' => [
>         'anonymize_ips' => true,
>         'collect_git_information' => false,
>         'report_queries' => true,
>         'maximum_number_of_collected_queries' => 200,
>         'report_query_bindings' => true,
>         'report_view_data' => true,
>     ],
> ```

Work for me in shared hosting and PHP 7.3

**Comment by martenkoetsier** [comment]
The solution by manukn works, but keep in mind that the configuration might be cached in /bootstrap/cache/config.php. If that file still contains a `true` value for `flare.reporting.collect_git_information`, the error remains.
Delete this cache file to remove the cache.

**Comment by estern67** [comment]
I solved this issue by deleting everything inside **/bootstrap/cache**

**Comment by Sharifur** [comment]
> collect_git_information

save my day

**Comment by dennisvandenende** [comment]
doesn't work for me:
My PHP:

```
PHP 7.2.24-0ubuntu0.18.04.3 (cli) (built: Feb 11 2020 15:55:52) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24-0ubuntu0.18.04.3, Copyright (c) 1999-2018, by Zend Technologies

```

```
composer require brexis/laravel-workflow
Using version ^1.3 for brexis/laravel-workflow
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing brexis/laravel-workflow (1.3.3):
In Process.php line 344:

  proc_open(): fork failed - Invalid argument
```

```
my config/flare.php

    'reporting' => [
        'anonymize_ips' => true,
        'collect_git_information' => false,
        'report_queries' => true,
        'maximum_number_of_collected_queries' => 200,
        'report_query_bindings' => true,
        'report_view_data' => true,
        'grouping_type' => null,
    ],
```

and my bootstrap/cache is empty (I empty this after every try)

What i did is just install the laravel boilerplate 
then composer update.
Then I and wanted to add this laravel-workflow
and that is the moment i get this error.

running within WSL by the way.
Any suggestions?

**Comment by nelsonrod10** [comment]
> It is because of Flare error reporting service enabled in debug mode
> There is a workaround for this.
> 
> Publish flare config file
> ` php artisan vendor:publish --tag=flare-config`
> 
> and in config/flare.php
> 
> Set
> 
> ```
> 'collect_git_information' => false 
> ```
> 
> ```
> 'reporting' => [
>         'anonymize_ips' => true,
>         'collect_git_information' => false,
>         'report_queries' => true,
>         'maximum_number_of_collected_queries' => 200,
>         'report_query_bindings' => true,
>         'report_view_data' => true,
>     ],
> ```

Thanks!!, works for php 7.4

**Comment by hafizSiddiq7675** [comment]
Not working for me

**Comment by ishendywebdeveloper** [comment]
> Not working for me

Why? What have you tried so far? Can you share your flare config file?

**Comment by driesvints** [comment]
Hey everyone,

I'm locking this issue because it either has gone off-topic, become a dumping ground for things which shouldn't be in an issue tracker or is just too old. Please try to discuss things further on one of the below channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
