### ISSUE TITLE
Job middleware support for queued notifications

### ISSUE THREAD

**Issue by vigneshgurusamy** [laravel/framework#30057]
- Laravel Version: 6.0.3
- PHP Version: 7.3.9
- Database Driver & Version: Postgresql 11.5

### Description:

Job middleware works for queued jobs but it does not work with queued notification jobs.

### Steps To Reproduce:

```php
class Notification extends BaseNotification implements ShouldQueue
{
    use Queueable;
}

$user = User::find(2);
$notification = (new Notification())->through(new RateLimited);
$user->notify($notification);
```

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!
