### ISSUE TITLE
static property wrap in JsonResource

### ISSUE THREAD

**Issue by orangeShadow** [laravel/framework#30069]
- Laravel Version: 5.8.34
- PHP Version: 7.2.13
- Database Driver & Version:

### Description:
If you write tests on response from Resources extended by JsonResource and you change static property wrap (for example without Wrap) for one of them, all next test, which must have a wrapper ,does not have them

### Steps To Reproduce:
```
...
public function testOne() {
    $this->getJson(...return ResourceWithoutWrap())->assertJsonFragment([....]);
}
...
public function testTwo() {
    //Must be with wrap
    $this->getJson(...return ResourceWithWrap())->assertJsonFragment([data=>[...]]);
  //error
}
```

Yes, I know, that I must test Repository Class, but this error can generate other mistake, if I have resources chain, maybe it is a bad idea to put wrap in extended class like a static property  ?

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
