### ISSUE TITLE
exponential backoff and other rate limiting strategies in queues

### ISSUE THREAD

**Issue by rajat-guesthouser** [laravel/framework#30066]
I want to rate limit laravel queues so that they take 1 sec break after every 100 jobs. Also, I want to implement exponential backoffs when some error occurs in processing a job. Meaning the queue processing should halt till the backoff time and not just that job.

**Comment by nmokkenstorm** [comment]
You could use a trait or the recently added [Job Middleware](https://laravel-news.com/job-middleware-is-coming-to-laravel-6) to implement rate limiting in more or less the same way it's done for http requests.

I think you're unlikely to see your proposed exponential backoff to make it to the core framework code, but implementing logic like that could be done by extending the [Worker](https://github.com/laravel/framework/blob/6.x/src/Illuminate/Queue/Worker.php) class, and registering a new command for it, as several packages already do.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
