### ISSUE TITLE
SplFileInfo::getSize(): stat failed for C:\wamp64\tmp\phpC4A7.tmp in laravel 6.0

### ISSUE THREAD

**Issue by mdasiff** [laravel/framework#30064]
- Laravel Version: 6.0.0
- PHP Version: 7.2.0
- Database Driver & Version:  5.7.24 - MySQL

### Description:
I'm uploading image but unfortunately getting error the same code in lower version is working fine but in laravel 6.0 it throwing the error.
**Code**
$dir = 'public/uploads';
$filename = time().'.'.$request->file('file')->getClientOriginalExtension();
$request->file('file')->move($dir, $filename);

**Error**

(1/1) RuntimeException
SplFileInfo::getSize(): stat failed for C:\wamp64\tmp\phpC4A7.tmp
--

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by thetpainghtut** [comment]
Hello I am still getting this error, someone advice me about how.

**Comment by agencia3w** [comment]
I have a some problem. (1/1) RuntimeException
SplFileInfo::getSize(): stat failed for C:\wamp64\tmp\php299.tmp

**Comment by csesumonpro** [comment]
1/1) RuntimeException
SplFileInfo::getSize(): stat failed for C:\Users\csesumonpro\AppData\Local\Temp\php1ECE.tmp
