### ISSUE TITLE
Log with Slack: SlackRecord::generateAttachmentField() must be of the type string, integer given

### ISSUE THREAD

**Issue by pmochine** [laravel/framework#30068]
- Laravel Version: 6.0.0
- PHP Version: 7.2.7

### Description:
I upgraded to Laravel 6.0 but now I get the error: 

> Failed asserting that exception of type "TypeError" matches expected exception "\Exception". Message was: "Argument 1 passed to Monolog\Handler\Slack\SlackRecord::generateAttachmentField() must be of the type string, integer given, called in /Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/monolog/monolog/src/Monolog/Handler/Slack/SlackRecord.php on line 328" at
/Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/monolog/monolog/src/Monolog/Handler/Slack/SlackRecord.php:309
/Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/monolog/monolog/src/Monolog/Handler/Slack/SlackRecord.php:328
/Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/monolog/monolog/src/Monolog/Handler/Slack/SlackRecord.php:170
/Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/monolog/monolog/src/Monolog/Handler/SlackWebhookHandler.php:94
/Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php:42
/Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/monolog/monolog/src/Monolog/Logger.php:323
/Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/monolog/monolog/src/Monolog/Logger.php:551
/Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Log/Logger.php:176
/Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Log/Logger.php:75
/Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:493
/Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:239
/Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/app/Helpers/Sms/SmsNotifications.php:95
/Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/app/Helpers/Sms/SmsNotifications.php:25
/Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/tests/Unit/Sms/SmsNotificationsTest.php:36
.

I know this problem lies in Monolog, however, because it worked with Larvel 5.8 maybe this is an issue in Laravel.
Please tell me if I need to open an issue in Monolog.

### Steps To Reproduce:
Call this function: `\Log::critical('Some text', ['somevalue']);` 

And before that add in logging.php

    'channels' => [
        'stack' => [
            'driver' => 'stack',
            'channels' => ['single', 'slack'],
        ],

        'single' => [
            'driver' => 'single',
            'path' => storage_path('logs/laravel.log'),
            'level' => 'debug',
        ],
        'slack' => [
            'driver' => 'slack',
            'url' => env('LOG_SLACK_WEBHOOK_URL'),
            'username' => 'Laravel Log',
            'emoji' => ':boom:',
            'level' => 'critical',
        ],
    ]

A temporary solution is:
`\Log::critical('Some text', ['a string key' => 'somevalue']);`

**Comment by ajoy39** [comment]
Looks like this was a bug in monolog that should be fixed in 2.0 https://github.com/Seldaek/monolog/commit/4bfd34158614935aeca338643a620c8d6f262f88

Are you using 1.24? Did you recently update monolog? It looks like that line of code was last changed over a year ago before fixing this bug, not sure why you would just now be running in to it unless you also updated to 1.24 recently.

**Comment by driesvints** [comment]
Seems like this is an issue with monolog and not laravel.
