### ISSUE TITLE
make:migration: Class duplicate check is not working

### ISSUE THREAD

**Issue by crhg** [laravel/framework#30062]
- Laravel Version: 6.0.2
- PHP Version: 7.3.9
- Database Driver & Version: not relevant

### Description:

The `make:migration` command has class duplication checking logic, but it doesn't seem to work.

### Steps To Reproduce:

```console
% php artisan make:migration foo
% php artisan make:migration foo
```

The second `make:migration` is expected to fail with `class already exists` error, but will succeed.

An error occurs when the `php artisan migrate` command is executed later because the class name is duplicated.

### Note

This check is performed by the [`\Illuminate\Database\Migrations\MigrationCreator::ensureMigrationDoesntAlreadyExist`](https://github.com/laravel/framework/blob/3ec56b8810bc40016252977c69ba27057dcecf7d/src/Illuminate/Database/Migrations/MigrationCreator.php#L70) function. This uses the `class_exists` function to determine whether the class you are trying to create already exists.

I think it is needed to require all migration files to define the migration classes before duplication check.

**Comment by staudenmeir** [comment]
This feature stopped working after https://github.com/laravel/laravel/pull/4340.

**Comment by crhg** [comment]
Perhaps it was necessary to add code to require migration files manually like the `\Illuminate\Database\Migrations\Migrator` class does.

**Comment by driesvints** [comment]
Maybe it's indeed best we adjust the `ensureMigrationDoesntAlreadyExist` to do the check manually.
