### ISSUE TITLE
Dispatch closure inside console command not working

### ISSUE THREAD

**Issue by AbdelkaderBah** [laravel/framework#30067]
- Laravel Version: 5.7.8
- PHP Version: 7.1.3

### Description:
Dispatching a callback from console command class has an issue related to Carbon.

### Error output:
```
  Exception trace:

  1   Carbon\Carbon::__set("date", "2019-09-21 20:26:19.267166")
      [internal]:0

  2   ReflectionProperty::setValue(Object(Illuminate\Support\Carbon), "2019-09-21 20:26:19.267166")
      /Users/apple/Code/nairaex-v2/vendor/opis/closure/src/SerializableClosure.php:431
```

### Steps To Reproduce:
1) create new artisan command: ```php artisan make::command FooCommand ```
2) create FooCommand::TestAnyThing method
3) dispatch a callback:

```
dispatch(function(){
  $this->TestAnyThing();
});
```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by fjarrett** [comment]
FWIW I was having the same issue but it turned out I had switched from 
the `database` driver to `sync` without running `php artisan config:cache`, once I did that dispatch worked as you'd expect from a console command.
