### ISSUE TITLE
[5.5] Update with DB::raw triggers Object of class Illuminate/Database/Query/Expression could not be converted to float

### ISSUE THREAD

**Issue by at-quangle** [laravel/framework#30079]
- Laravel Version: 5.5.48
- PHP Version: 7.2.22
- Database Driver & Version: MySQL 5.7.19

**Description:**

When I increment point_total column on a specific UserService like:

$this->userRepo->update(['point_total' => \DB::raw('point_total + '.$point)], $userId);

I got this notice going:

Object of class Illuminate\\Database\\Query\\Expression could not be converted to float at /var/www/laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:475)

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
