### ISSUE TITLE
FileStorage FTP drive with options configuration

### ISSUE THREAD

**Issue by paulohlimamaia** [laravel/framework#30071]
I'm reporting here because i can't find it anywhere in the Documentation, Laravel forum or issues in the repository but regardless, i'm sorry if this issue was already addressed in another thread.

But the issue, basically is the following:

Some ill configured FTP servers respond the PASV command with a non-roteable (local) address and this makes impossible further communication with the FTP server.

PHP FTP Library has a option built-in to handle this by using the same address, that it used to connect, to make the ftp transactions as stated by [this](https://www.php.net/manual/en/function.ftp-set-option.php), more precisely the **FTP_USEPASVADDRESS** option.

And this works great, but i didn't find any option in Laravel to make the FileStorage using the FTP disk to set this option. There is some work around to this or plans to add it in the future?

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
