### ISSUE TITLE
Paginate has some problem

### ISSUE THREAD

**Issue by MagnusDot** [laravel/framework#30072]
- Laravel Version: 6.0.3
- PHP Version: 7.3.6
- Database Driver & Version: pgsql

### Description:
When i want to paginate my Model, laravel crash with this error : 
![image](https://user-images.githubusercontent.com/39904918/65435850-75041680-de21-11e9-9f6e-06cad8d33bcd.png)

### Steps To Reproduce:

1 . take a model and request it to the database with the pagination : 
![image](https://user-images.githubusercontent.com/39904918/65435913-906f2180-de21-11e9-8414-0635b9cabd01.png)
2 . set the Path and return the model 
![image](https://user-images.githubusercontent.com/39904918/65435956-a0870100-de21-11e9-8f7e-795c23d47eca.png)
3. add the the links() 
![image](https://user-images.githubusercontent.com/39904918/65436011-b85e8500-de21-11e9-8387-b8edac866fdd.png)
here's the error

**Comment by mobayen** [comment]
you have a typo:
`not 'ilike' but `
also you need to use dot or slash to separate view paths parts
so 
`
not 'article::listArticle' but 'article.listArticle'
not 'pagination::bootstrap' but 'pagination.bootstrap'
`

**Comment by MagnusDot** [comment]
I use in same time the Laravel module architecture from nwidart so the article::listArticle is working well ^^

**Comment by mobayen** [comment]
I have no idea how this works but it's best to code it according to the docs!
there are a lot of possibilities that might cause the problem! so you don't want to make it complicated with this kind of code practices!

**Comment by MagnusDot** [comment]
the real problem is ive just updated laravel to 6.0 before that i was in 5.3 and this was working well

**Comment by MagnusDot** [comment]
> the real problem is ive just updated laravel to 6.0 before that i was in 5.3 and this was working well

so i think this is a problèm with the framework ^^

**Comment by alec-joy** [comment]
> 
> 
> the real problem is ive just updated laravel to 6.0 before that i was in 5.3 and this was working well

That is...an ambitious jump, I would definitely go through the upgrade guides for 5.4+ and inspect your code. There are definitely a lot of breaking changes in there you'll need to clean up, I suspect this is one of them.

**Comment by MagnusDot** [comment]
Sry i miss spell it, i jumped from 5.8

> > the real problem is ive just updated laravel to 6.0 before that i was in 5.3 and this was working well
> 
> That is...an ambitious jump, I would definitely go through the upgrade guides for 5.4+ and inspect your code. There are definitely a lot of breaking changes in there you'll need to clean up, I suspect this is one of them.

**Comment by MagnusDot** [comment]
I found one clue, it's the installation of facade/ignition who's not working after the update to laravel 6.0

**Comment by ajoy39** [comment]
> 
> 
> I found one clue, it's the installation of facade/ignition who's not working after the update to laravel 6.0

The error page you're getting is still the Whoops error page, are you trying to migrate to ignition or is this just one a fresh upgrade? In either case I would try uninstalling Whoops and adding ignition 
```
composer require facade/ignition
```

Double check to see if you've made any modifictions to app/Exceptions/Handler.php that may be conflicting with as well

**Comment by timrspratt** [comment]
What is your `app/config/auth.php` providers looking like? Supported types are `database`, `eloquent` but you appear to be passing `session`

**Comment by MagnusDot** [comment]
> > I found one clue, it's the installation of facade/ignition who's not working after the update to laravel 6.0
> 
> The error page you're getting is still the Whoops error page, are you trying to migrate to ignition or is this just one a fresh upgrade? In either case I would try uninstalling Whoops and adding ignition
> 
> ```
> composer require facade/ignition
> ```
> 
> Double check to see if you've made any modifictions to app/Exceptions/Handler.php that may be conflicting with as well


that's exactly what i did i followed the tutorial on the ignition website for that. And it is exactly at this moment that my problem appears.
I even tried to remove whoops but that does not change anything

**Comment by MagnusDot** [comment]
the red circle is what i'm using ^^ 
![image](https://user-images.githubusercontent.com/39904918/65505798-5e65ca00-deca-11e9-9e4f-ac5b77858433.png)
![image](https://user-images.githubusercontent.com/39904918/65505811-658cd800-deca-11e9-87bd-ee7e2e0a3c6e.png)

**Comment by timrspratt** [comment]
You don't have a provider for "users". Is `admin` set as the default guard at the top of the file?
