### ISSUE TITLE
SyncQueue::pushRaw not implemented

### ISSUE THREAD

**Issue by cgwyllie** [laravel/framework#30083]
- Laravel Version: 5.5.x - 6.0 (all?)
- PHP Version: 7.3.x
- Database Driver & Version: N/A

### Description:

The `SyncQueue` driver is missing an implementation for `QueueContract::pushRaw`. This was encountered when trying to write tests covering interop with other services submitting 'raw' jobs (`{job: FQCN, data: {...}}`) to a Laravel app.

### Steps To Reproduce:

- Set queue driver to `'sync'`
- Push a raw job onto the queue using the Queue facade:
    ```php
    Queue::pushRaw(json_encode([
            'job' => Your\Job::class,
            'data' => (object) [],
    ]));
   ```
- Observe no handle method is called, no queue events are fired etc.

### Expected Behaviour

- Job's handle method is called
- All relevant queue events are dispatched

**Comment by driesvints** [comment]
Push raw is not available for the sync queue: 

https://github.com/laravel/framework/blob/419253f67bd914cb8729a105ee847393c22fd9c5/src/Illuminate/Queue/SyncQueue.php#L134

**Comment by cgwyllie** [comment]
Hi @driesvints, apologies I may be misunderstanding something here, but from my point of view, the fact it's not available in the sync queue is the reason I've opened this issue.

To meet the QueueContract correctly, I would expect this method to be implemented.

If it is not implemented by design, can you explain the reasoning behind that decision? In this case, I would expect the method to throw a NotImplementedException explaining why.

Thanks

**Comment by driesvints** [comment]
@cqwyllie it's because there's no implementation for "raw" with a sync queue. There's no driver. No "raw" way of handling queued jobs.

**Comment by cgwyllie** [comment]
Should it not still be possible to implement the 'raw' method?

If I read other drivers correctly, the difference seems to be that 'raw' treats what it's given as a 'payload' whilst other push methods call through 'createPayload' or similar prior to persistence/handling. In this case, it should be possible to run the 'raw' payload through the same handling pipeline after some deserialisation step (as with other drivers retrieving jobs from a persistence layer).

I appreciate this is perhaps an edge case, but it is surprising to find the driver silently ignoring calls to a method because it doesn't meet the implemented contract.

@driesvints is there any info to read about the 'raw' job stuff? It's something that's of interest to us because of interfacing with other non-laravel systems, but material seems to be a little sparse from our searches.

Thanks again for your time.

**Comment by driesvints** [comment]
I don't think it's possible to implement a raw implementation on the sync queue sorry. There's no single way to handle all cases. If you still want this please open up an issue on the ideas repo.

**Comment by cgwyllie** [comment]
Ok, cool, was unaware of the ideas repo.
