### ISSUE TITLE
pagination on hasmany relationship data

### ISSUE THREAD

**Issue by Alok77** [laravel/framework#30082]
If you have two models, let's say BlogPost and Comment. They are linked by a OneToMany relationship. If you want to get all blog posts along with the comments you could do this:

 $postsWithComments = BlogPost::with("comments")->get();

if you want to paginate the BlogPost then it will work like this

$postsWithComments = BlogPost::with("comments")->paginate(5);

however this will paginate blog post with comment 

but can we paginate on Comment

means per page 5 blogpost  and every blog post comment but those comments are also by pagination  like 5 comment per load and after click on more another 5 comment load
 
Any idea from anyone to do this is appreciated,
Thanks

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
