### ISSUE TITLE
[RFC] SphinxQL support

### ISSUE THREAD

**Issue by wucdbm** [laravel/framework#30090]
Heya,

I was using illuminate/database's query builder to simplify sphinx queries and stumbled upon LIMIT / OFFSET where sphinx QL requires the shorthand LIMIT 40, 20, rather than LIMIT 20 OFFSET 40.

I dug into the codebase and made my own SphinxConnection that uses my own SphinxQlGrammar that overrides compileLimit and compileOffset, so that works now.

ConnectionFactory also needs two new cases for `sphinx` driver config option where it returns a `MySqlConnector` @ `createConnector` and the aforementioned `SphinxConnection` @ `createConnection`.

I also have the necessary code to support the max_matches option @ queries with code completion @ query builder (Connection class needs to be properly annotated for that to work): `SELECT ... LIMIT 1000, 10 OPTION max_matches = 1000`

Would anyone be interested in that?

Generally, for my own use I need the Connection. Supporting this in the library would allow me to use it like so, without hacking around and constructing the connection myself. I guess that'd be useful in Laravel itself too, being able to configure a sphinx connection.

```php
<?php 

public static function create(
        string $driver, string $host, string $port,
        string $db, string $user, string $pass
    ): Connection {
        $capsule = new Capsule;

        $capsule->addConnection([
            'driver'    => $driver,
            'host'      => $host,
            'port'      => $port,
            'database'  => $db,
            'username'  => $user,
            'password'  => $pass,
            'charset'   => 'utf8',
            'prefix'    => '',
        ]);

        return $capsule->getConnection();
    }
```

```php
<?php

$connection = MyFactory::create('sphinx', 'host', ...$params);
```

Else:

```php
<?php 

public static function createSphinxConnection(
        string $driver, string $host, string $port,
        string $db, string $user, string $pass
    ): Connection {
        $config = [
            'driver'    => $driver,
            'host'      => $host,
            'port'      => $port,
            'database'  => $db,
            'username'  => $user,
            'password'  => $pass,
            'charset'   => 'utf8',
            'prefix'    => '',
        ];

        $connector = new MySqlConnector();
        $pdo = $connector->connect($config);

        return new SphinxConnection($pdo, $config['database'], $config['prefix'], $config);
    }
```

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!
