### ISSUE TITLE
Authorization Policy for users doesn't work when using two user models extending from a base user model

### ISSUE THREAD

**Issue by jclee100** [laravel/framework#30096]
- Laravel Version: 6.0.4
- PHP Version: 7.1.7
- Database Driver & Version: MySQL 5.7.19

### Description:
Authorization Policy for users doesn't work when using two user models extending from a base user model.

I have two types of users admins and customers. Both have their own model classes App/Admin, App/Customer and extends from a base model class App/User.

There seems to be a bug when trying to authorize for the index method.

On my CustomerPolicy:
```
    /**
     * Determine whether the user can view any customers.
     *
     * @param User $user
     * @return mixed
     */
    public function viewAny(User $user)
    {
        return $user->is_admin;
    }
```
On my controller index method:

`$this->authorize('viewAny');` Fails with `AccessDeniedHttpException`

`$this->authorize('viewAny', Admin::find(1));` Fails with `AccessDeniedHttpException`

There is no such issue on other Controller/Policies.
For example, the OrderPolicy and OrderController index method works as expected. The policy is written in the same way with `viewAny` expecting a `User $user` and returning `$user->is_admin`

The default guard policy is `customers` if that matters.

**I suspect that Laravel is failing to find the policy method due to the type of user class conflicting with the model that it's mapped to.**

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by jclee100** [comment]
Hi, I have posted to Laracasts earlier.

You can refer to this thread: https://laracasts.com/discuss/channels/code-review/authorization-policy-bug-due-to-different-user-type?page=1#reply=541124

**Comment by driesvints** [comment]
@jclee100 seems like it's only been two days (over a weekend). Give it some more time.
