### ISSUE TITLE
Eloquent: Automatic shorting of migration-identifiers if needed

### ISSUE THREAD

**Issue by mielemilos** [laravel/framework#30109]
- Laravel Version: 5.8.35
- PHP Version: 7.2.9
- Database Driver & Version: MySQL 5.7.25 - MySQL Community Server (GPL)

### Description:
Creating tables with longer names can cause foreign key names to exceed the default 64 char maximum name length

This can be solved by giving specifying a name parameter with the foreign function.
But I feel this should be done automatically.

### Steps To Reproduce:
A migration example

```
Schema::create('customers', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('name');
}):

Schema::create('accountmanagers', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('name');
 });

 Schema::create('customer_has_accountmanager', function (Blueprint $table) {
            $table->unsignedBigInteger('accountmanager_id')->unsigned();
            $table->foreign('accountmanager_id')->references('id')->on('accountmanagers');

            $table->unsignedBigInteger('customer_id')->unsigned();
            $table->foreign('customer_id')->references('id')->on('customers');

            $table->primary(['accountmanager_id', 'customer_id']);
});
```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
