### ISSUE TITLE
Max rule does not validate correctly

### ISSUE THREAD

**Issue by Bcryp7** [laravel/framework#30103]
- Laravel Version: ^6.0
- PHP Version: 7.3.9-1
- Database Driver & Version: SQLite

### Description:
Having a `string('phone', 25)->nullable();` column in `users` table, `max:25` does not return error if it receives +25 characters.

**UserRequest**

`'phone' => ['max:25'],`

**Test**

```
use RefreshDatabase;

    /**
     *   @test
     *   @throws \Throwable
     */
    public function phone_must_not_exceed_25_characters()
    {
        $this->postJson(
            route('users.store'),
            factory(User::class)->make(['phone' => Str::random(26)])->toArray()
        )->assertJsonValidationErrors('phone');
    }
```

`UserRequest` is being passed thru the `store` method.

* Note: Spark 9.1.0 Aurelius is being used.

Same tests passes in a Laravel +6.0 project without Spark.

**Comment by ahinkle** [comment]
Hey there,

Have you tried using `digits:25`?

The `max:25` field must be less than or equal to a maximum value that of `25` and doesn't include the counting of characters.

**Comment by rs-sliske** [comment]
i think you need to specify data type as well as max, in this case ['string', 'max:25']

**Comment by Bcryp7** [comment]
@ahinkle Actually as far as I know `digits` apply if the data type is integer right? the column is `string` , I have another project with same validation rule and test and passes.

@rs-sliske you were right, didn't need to do this before, thanks man.

So if I guess it's a normal behavior now.

**Comment by rs-sliske** [comment]
not too sure about the behavior changing but the min/max/size rules do some magic based on the data type

- for numeric types min/max do numeric comparison
- for strings they use string length
- for arrays they use number of elements in the array
- for files it uses the file size (bytes)

the code does look like it defaults to treating as a string though so not 100% sure what was going on :(

**Comment by Bcryp7** [comment]
I Agree, thanks man.
