### ISSUE TITLE
Strange behaviour of global objects relations if used inside relation declaration

### ISSUE THREAD

**Issue by hastom** [laravel/framework#30106]
- Laravel Version: 5.8
- PHP Version: 7.2

### Description:

I have a model defining a many to many relation. And I want to define another relation to same model but filtered by some values that I receive from globally stored model. 

```
class Tenant extends Authenticatable implements JWTSubject, BelongsToObjects
{

   // this one is filtered
    public function addressesInSystem()
    {
   // $system is an instance of System model which has "hasMany" relation "objects", this is the first time I'm trying to get system's objects
        $system = \SystemResolver::system();
        $addresses = $this->addresses()->whereIn('objectId', $system->objects->pluck('id'));
        return $addresses;
    }

   // this one is a base relation
    public function addresses()
    {
        return $this
            ->belongsToMany(Address::class, 'tenants_addresses')
            ->withPivot('isBlocked', 'confidanceId');
    }

}
```

Then I eager load this relation inside controller
```
class TenantController extends Controller
{
    public function get(Request $request)
    {
        /** @var System $system */
        $system = \SystemResolver::system();
        $tenants = $system->tenants()
            ->with('tenantsGroups')
            ->with('addressesInSystem')
            ->filter($request->input('filter'))
            ->queryFilter($request->input('query'))
            ->sort($request->input('sort', ['id' => 'DESC']))
            ->paginate(\Config::get('constants.default_pagination'));
        $tenantsCollection = new TenantsCollection($tenants);
        return \Response::success($tenantsCollection);
    }
}
```

The weird thing is instead of getting objects of the system I get all objects, so I get addresses with any objectId. I know I can filter relation inside `with` method, but this one is also used for sync and in other controller methods. The workaround is to add `protected $with = ['objects']` to `System` model, but the behavior is still unexpected. And there are no mentions in docs about this. I guess the same thing will happen to any other global objects like `Auth::user()`

**Comment by hastom** [comment]
Just checked v6.0 also affected

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
