### ISSUE TITLE
[6.0] withCount includes softdeleted models

### ISSUE THREAD

**Issue by krgaurav1992** [laravel/framework#30116]
- Laravel Version: 6.0.4
- PHP Version: 7.2.x
- Database Driver & Version:

### Description:
When using withCount on relations, It includes the soft deleted models as well.

**Comment by driesvints** [comment]
Please share some code. Otherwise it's gonna be hard to figure out what's going wrong.

**Comment by krgaurav1992** [comment]
### Steps to reproduce:
get a model using:
`$model= Model::withCount('children')->findOrFail($model_id);`

`$model->children_count` has count with soft deleted models. (In my case, I have 15 records with 2 soft-deleted models). The result is 15 instead of 13.

However, if we fetch:
`$model= Model::with('children')->findOrFail($model_id);`
`count($model->children)` has correct result.

**Comment by alec-joy** [comment]
Can you fire up tinker, enable the query log with the code below, and post the query? Should be easy enough to see if the deleted_at is in there or not. I can also say this is not happening on 5.8.24 so we can narrow the issue down to something in 6.0 

Enable query log
```
DB::enableQueryLog();
```
Run your query 
```
$model= Model::withCount('children')->findOrFail($model_id);
```
Print out the query log 
```
DB::getQueryLog();
```

**Comment by krgaurav1992** [comment]
Yes. The issue is in 6.0. Though as per query log, the query looks fine to me. As @alec-joy said, might be some grammer issue (I am using MySQL 5.7).

Here is the query log dump:
`select `topics`.*, (select count(*) from `entries` where (`topics`.`id` = `entries`.`topic_id` and `visibility` in (?, ?) or (`visibility` = ? and `author_id` = ?)) and `entries`.`deleted_at` is null) as `entries_count` from `topics` where `topics`.`id` = ? and `topics`.`deleted_at` is null limit 1`

**Comment by staudenmeir** [comment]
Please post both models.

**Comment by dkulyk** [comment]
You should to wrap `OR` сondition to `->where(function ($query) { ... })`

**Comment by krgaurav1992** [comment]
Here is the query log for `$model= Model::with('children')->findOrFail($model_id);` :
`
[
    {
        "query": "select * from `topics` where `topics`.`id` = ? and `topics`.`deleted_at` is null limit 1",
        "bindings": [
            "2"
        ],
        "time": 1.03
    },
    {
        "query": "select * from `users` where `id` = ? limit 1",
        "bindings": [
            3
        ],
        "time": 0.91
    },
    {
        "query": "select `roles`.*, `model_has_roles`.`model_id` as `pivot_model_id`, `model_has_roles`.`role_id` as `pivot_role_id`, `model_has_roles`.`model_type` as `pivot_model_type` from `roles` inner join `model_has_roles` on `roles`.`id` = `model_has_roles`.`role_id`",
        "bindings": [],
        "time": 1.04
    },
    {
        "query": "select `id`, `topic_id`, `uuid`, `slug`, `title`, `updated_at` from `entries` where (`visibility` in (?, ?) or (`visibility` = ? and `author_id` = ?) and `entries`.`topic_id` in (2)) and `entries`.`deleted_at` is null order by `sort_order` asc",
        "bindings": [
            1,
            2,
            3,
            3
        ],
        "time": 1.24
    }
]
`

**Comment by dkulyk** [comment]
You should to wrap `OR` сondition to `->where(function ($query) { ... })`

**Comment by Ashubgs90** [comment]
`withCount()` also includes soft deleted in total count and it doesn't included `where condition for deleted_at` in query. It seems a simple bug to me. It should get fixed.

If they have provided option to get count using `withCount()` then why should we wrap `OR` сondition to `->where(function ($query) { ... })`

**Comment by staudenmeir** [comment]
How is the relationship defined?

**Comment by driesvints** [comment]
@krgaurav1992 can you please share the models like @staudenmeir asked?

**Comment by krgaurav1992** [comment]
The model is defined as:
``` php
class Topic extends Model {
    public function entries() {
        return $this->hasMany(Entry::class);
    }
}
```

**Comment by dkulyk** [comment]
Your query contains
```sql
select count(*) from `entries` where (
`topics`.`id` = `entries`.`topic_id` and `visibility` in (?, ?)  # entiries for topic with visibility in 
or (`visibility` = ? and `author_id` = ?) # OR visibility is  ? and author_id is ?
) and `entries`.`deleted_at` is null
```

This query count records for topic and non topic entries.

**Comment by staudenmeir** [comment]
Where are the other `WHERE` constraints coming from?

**Comment by driesvints** [comment]
I'm gonna ask you to try a support channel first. It seems to me that there's something wrongly implemented somewhere and you're not giving us much code to investigate.

Please try one of the support channels below. If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by ArneAnka** [comment]
I also have this error.

Console.php model, doesent use softdelete
```php
    public function games(){
        return $this->hasMany(Game::class);
    }
```

Game.php uses softdelete
```php
    public function console(){
        return $this->belongsTo(Console::class);
    }
```

And with `withCount` on `Console` model, i also get the soft deleted rows.
```php
$games_count = Console::withCount('games')->get();
```
