### ISSUE TITLE
How to select Users from Database with exactly 2 roles? like users with (admin) and (client) roles together 

### ISSUE THREAD

**Issue by sahamnadeem** [laravel/framework#30117]
User.php

`public function roles(){
        return $this->belongsToMany(Role::class);
    }`
Role.php

`public function users(){
        return $this->belongsToMany(User::class);
    }`

UserController.php

`$user = User::whereHas('roles', function ($q) use ($request) {
            $q->where('role_id', $request->roles);
        })`

================Request========================
`{
     "roles":[1,2]
}`
===============Response=========================
`[]`

===============Table===============================
role_user
+=====+======+
|      1        |     1        |
|      1        |     2        |
|      2        |     2        |
|      3        |     2        |
|___ 4_____ |___ 2_____|

What should i do to get all the users with exactly two roles? 
as user 1 has 2 roles in database

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
