### ISSUE TITLE
Incompatibility of assertSoftDeleted with softDelete trait

### ISSUE THREAD

**Issue by Theremsoe** [laravel/framework#30110]
- Laravel Version: 6.0, 5.8
- PHP Version: 7.1
- Database Driver & Version: 6.0, 5.8

### Description:

Incompatibility between `assertSoftDeleted` with `softDelete` when you define a custom name column.

### Steps To Reproduce:
 - Create a migration with `softDeletes` method and a different column name. Example: `$table->softDeletes('deleted_date');`.
 - Create a model with `SoftDeletes` trait.
 - Define the soft delete column: `const DELETED_AT = 'deleted_date';`.
 - Create a test that use `assertSoftDeleted` method and check model.

**Comment by X-Coder264** [comment]
Unfortunately yes, the `deleted_at` column is currently hardcoded in the PHPUnit constraint class https://github.com/laravel/framework/blob/v6.0.4/src/Illuminate/Foundation/Testing/Constraints/SoftDeletedInDatabase.php#L54

**Comment by driesvints** [comment]
Hmm, this indeed seems unwanted.

**Comment by driesvints** [comment]
PR merged

**Comment by Theremsoe** [comment]
Thanks guys.
