### ISSUE TITLE
TypeError: window.Laravel is undefined

### ISSUE THREAD

**Issue by ankit20893** [laravel/framework#30113]
- Laravel Version: 5.8
- PHP Version: 7.2
- Database Driver & Version:

### Description:
It is having issue with specific user.

**Comment by ankit20893** [comment]
i have cross checked for this in layout :
<script>
        window.Laravel =
        <?php echo json_encode([
                   'csrfToken' => csrf_token(),
               ]); ?>
    </script>

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
