### ISSUE TITLE
Argument 1 passed to Illuminate\Database\Query\Builder::__construct() must implement interface Illuminate\Database\ConnectionInterface, instance of Illuminate\Database\Query\Builder given, called in 

### ISSUE THREAD

**Issue by iamriajul** [laravel/framework#30112]
- Laravel Version: 6.0.4
- PHP Version: 7.2
- Database Driver & Version: MySQL 8.0.15

### Description:
Errors with Model:
When Try to Login/Register/Forgot Password. or Tinker: `User::find(1)`;
```
Symfony\Component\Debug\Exception\FatalThrowableError
Argument 1 passed to Illuminate\Database\Query\Builder::__construct() must implement interface Illuminate\Database\ConnectionInterface, 
instance of Illuminate\Database\Query\Builder given, called in 
\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php     
/**
     * Create a new Eloquent query builder for the model.
     *
     * @param  \Illuminate\Database\Query\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder|static
     */
    public function newEloquentBuilder($query)
    {
        return new Builder($query);
    }
```
### Steps To Reproduce:
Try Login/Register/Forgot Password. or Tinker: `User::find(1);`
New Installation of Laravel 6.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
