### ISSUE TITLE
Sqlsrv - pagination while ordening by dynamic column throws exception

### ISSUE THREAD

**Issue by gdebrauwer** [laravel/framework#30119]
- Laravel Version: 6.0.3 _(issue is also present in 5.8)_
- PHP Version: 7.3.4
- Database Driver & Version: sqlsrv (sql server 2017)

### Description:

This is an issue specific to Sql Server.

If you want to paginate while also ordening the results based on a dynamic column (e.g. 'select column1 as column2' statement), an exception is thrown.
If you fetch the first page, then everything works correctly. But all other pages will cause an exception.

### Steps To Reproduce:

Run the following query: 

```php
 \App\User::query()
    ->select('users.*', 'password as dynamiccolumn')
    ->orderBy('dynamiccolumn')
    ->paginate(1, null, 'page', 1)
```

This will work. Now run the following query:

```php
 \App\User::query()
    ->select('users.*', 'password as dynamiccolumn')
    ->orderBy('dynamiccolumn')
    ->paginate(1, null, 'page', 2)
```

This will throw an exception: 

```
Illuminate/Database/QueryException with message
'SQLSTATE[42S22]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]
Invalid column name 'dynamiccolumn'.
(SQL: select * from (select [users].*, [password] as [dynamiccolumn],
row_number() over (order by [dynamiccolumn] asc) as row_num from [users]) as temp_table where row_num between 2 and 2 order by row_num)'
```

**Comment by driesvints** [comment]
I don't know much about sqlserver myself so appreciating any help with this.

**Comment by staudenmeir** [comment]
SQL Server requires this syntax for OFFSET queries and I don't think there's an elegant way to order by derived columns.

You can use this subquery workaround:

```php
$query = User::select('users.*', 'password as dynamiccolumn')
    ->orderByDesc('dynamiccolumn')
    ->limit(2147483647);
    
User::fromSub($query, 'alias')->paginate(1, null, 'page', 1);
```

**Comment by driesvints** [comment]
@gdebrauwer can you try the workaround?

**Comment by gdebrauwer** [comment]
The workaround work. Thanks @staudenmeir.
It's weird that SQL Server does not allow/support the order by dynamic column while paginating.

**Comment by staudenmeir** [comment]
There is a "real" OFFSET clause, but it requires SQL Server 2012+:
https://docs.microsoft.com/en-us/sql/t-sql/queries/select-order-by-clause-transact-sql

**Comment by gdebrauwer** [comment]
Oh, so that would require Eloquent to create the query based on the sqlsrv-version?

**Comment by staudenmeir** [comment]
Yes and it has been discussed: https://github.com/laravel/ideas/issues/870

It would possible to implement that, but the topic is quite complex and version-specific grammars have some downsides.

**Comment by driesvints** [comment]
closing this as there doesn't seems to be a good way to fix this.
