### ISSUE TITLE
not uploading to DB

### ISSUE THREAD

**Issue by savre** [laravel/framework#30129]
- Laravel Version: #.#.#
- PHP Version: 5.4
- Database Driver & Version:

### Description: When i am trying to upload audio(MP3) not storing in db and web, images showing
[http://bgm9new.esy.es/album/chennai-600028-ii-bgms-official-bScgcVjeCO](url)

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

I will be closing your ticket here. Instead please try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

If you feel I've closed this issue in error, please provide more information about how this is a framework issue, and I'll reopen the ticket.

Thanks in advance.
