### ISSUE TITLE
A redirection combining 'with' and 'withInput' requires a specific order

### ISSUE THREAD

**Issue by devngl** [laravel/framework#30124]
Given the code below:
```
return redirect($redirectUrl)
            ->with('success', $successMessage)
            ->withInput($request->has('only-content') ? ['only-content'] : []);
```

Method withInput seems to unset 'success' from session. 

On the other hand this works:
```
return redirect($redirectUrl)
            ->withInput($request->has('only-content') ? ['only-content'] : [])
            ->with('success', $successMessage);
```

Is this the expected behavior? Couldn't find anything on documentation about it.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
