### ISSUE TITLE
Tests that have ARRAY/JSON casts break with SQLlite

### ISSUE THREAD

**Issue by imran-concise** [laravel/framework#30128]
- Laravel Version: 6.0.0
- PHP Version: 7.3.0
- Database Driver & Version: In memory SQLlite 

### Description:
Using mysql (lluminate/Database/Query/Grammars/MySqlGrammar.php) `prepareBindingsForUpdate` correctly casts json attributes when using the `update` command.

However, running the tests, which is using SQLlite (Illuminate/Database/Query/Grammars/SQLiteGrammar.php) does not.

Is this correct behaviour? Surely even though SQLlite doesnt support JSON field it can store the json in a text field? I don't really want to "hack" my controller/model just to get the tests to work.

### Steps To Reproduce:

`Illuminate/Database/Query/Grammars/SQLiteGrammar.php` is missing (IMO) the following code block

```
        $values = collect($values)->reject(function ($value, $column) {
            return $this->isJsonSelector($column) && is_bool($value);
        })->map(function ($value) {
            return is_array($value) ? json_encode($value) : $value;
        })->all();
```

Or maybe that should be pushed up into the parent class?

My example is, where `historical_returns` is an array of data.

```
        collect($indexData)->each(function($historical_returns, $code) {
            Index::whereCode($code)->update(compact('historical_returns'));
        });
```

My model contains     `protected $casts = ['historical_returns' => 'json'];`

and my migration for the field is `$table->json('historical_returns')->nullable();`

The following code works both in production and testing environments

```
        collect($indexData)->each(function($historical_returns, $code) {
            $historical_returns = json_encode($historical_returns);
            Index::whereCode($code)->update(compact('historical_returns'));
        });
```

**Comment by imran-concise** [comment]
![Image 2019-09-28 at 9 40 46 pm](https://user-images.githubusercontent.com/53288939/65817387-d7ea1900-e238-11e9-96bf-1410d51df6f4.png)
Screenshot attached, if it helps.

**Comment by staudenmeir** [comment]
The ability to use `update()` with array values has been added very recently. This feature has only been implemented for MySQL and PostgreSQL since Laravel only supports JSON updates on those databases (i.e. `->update(['foo->bar' => 'baz'])`).

> I don't really want to "hack" my controller/model just to get the tests to work.

You don't need to "hack" anything. With `json_encode()`, the code works on all databases. Before Laravel 6, this had been the only way.

> Surely even though SQLlite doesnt support JSON field it can store the json in a text field?

Yes, it would be possible to port this improvement to SQLite. You are welcome to submit a PR.

**Comment by i-bajrai** [comment]
@staudenmeir Thanks for the feedback, I wasn't sure if adding changing the grammar files was the right way to go but what you said makes sense.

This is my first time opening a PR so I'll do some reading and see if I can figure it out :)

**Comment by driesvints** [comment]
Since this is more an improvement than an actual bug I'm closing this. Let's see how the pr goes.
