### ISSUE TITLE
Unexpected behavior change for 'numeric' validation rule

### ISSUE THREAD

**Issue by danielbachhuber** [laravel/framework#30120]
- Laravel Version: 6.0.4
- PHP Version: 7.3.6

### Description:

In Laravel 5.8, a field with the `numeric` validation rule would allow an empty string. In Laravel 6, the field errors with "must be a number".

I'm not sure whether this is an intentional or unintentional change in behavior. If it's intentional, I couldn't find any reference to it in the [upgrade guide](https://laravel.com/docs/6.x/releases)

### Steps To Reproduce:

Validate a request using the `numeric` validation rule:

```php
$this->validate($request, [
  'range_end' => 'numeric',
]);
```

Submit a form with an empty string for 'range_end' and unexpectedly see a "must be a number" error message.

**Comment by alec-joy** [comment]
Did you recently update your PHP version by any chance? The validateNumberic function itself hasn't changed in 3 years and only returns the results of php's built in is_numeric function. It could be something that changed in the request, but I'd like to rule that out first.

**Comment by danielbachhuber** [comment]
> Did you recently update your PHP version by any chance?

I haven't, nope.

**Comment by danielbachhuber** [comment]
I might be able to track down the actual problem too. Just wanted to open an issue first to make sure it wasn't a known change.

**Comment by alec-joy** [comment]
I am not sure why the behaviour would have changed from 5.8 to 6 for this, but according to [the docs](https://laravel.com/docs/6.x/validation#a-note-on-optional-fields) if you want to allow a validated field to accept an empty string, you should add "nullable" to  validation as empty strings are converted to null by a middleware. So your rule should be as follows

```
$this->validate($request, [
  'range_end' => 'nullable|numeric',
]);
```

Hope that helps

**Comment by driesvints** [comment]
```
Validator::make(['foo' => ''], ['foo' => 'numeric'])->passes()
``` 

Returns `true` for me on Laravel 6

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
