### ISSUE TITLE
Replicate continues copying in the same scope

### ISSUE THREAD

**Issue by adanzweig** [laravel/framework#30121]
- Laravel Version: 5.5.40
- PHP Version: 7.2.2
- Database Driver & Version: Mysql 5.7.17

### Description:

If i create a new object from an existing one using #replicate function and then edit the parent object, the value is copied into the inherited object.

### Steps To Reproduce:

$a = A::find(1);
$b = $a->replicate();
$b->foo = 'bar';
$b->push();

$a->replicated_to = $a->id;
$a->save();

The result is: 
$a->replicated_to = null
$b->replicated_to = $a->id

-----

Here is the ACTUAL Code:

        $rutas = new Rutas();
        $rutas->connection = $cliente->conexion;
        $rutas = $rutas->find($id);

        $ruta = $rutas->replicate();
        $ruta->connection = $rutas->connection;
        $ruta->access_token = '';
        $ruta->imei = null;
        $ruta->fecha_desde = $request->get('fecha');
        $ruta->owner = Auth::id();
        $ruta->push();

        $rutas->repactado_a = $ruta->id;
        $rutas->save();

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
