### ISSUE TITLE
invalid singular reserves => reserf

### ISSUE THREAD

**Issue by nemrutco** [laravel/framework#30131]
As it says in title, if you try to create a model named Reserve and resource as Reserve, you will end up singular name Reserf. 

Edit: 

- Laravel Version: 6.0.4
- PHP Version: 7.3.9
- Database Driver & Version: mysql  Ver 15.1 Distrib 10.4.6-MariaDB, for osx10.14 (x86_64) using readline 5.1

### Description:
Model names ends with `Reserve` become `Reserf` in singular

### Steps To Reproduce:
Make a **Model** name `Reserve` or `AnythingReserve`
Make a **Nova Resource** named `Reserve` or `AnythingReserve`

**Comment by driesvints** [comment]
@nemrutco can you please will out the issue template?

**Comment by nemrutco** [comment]
> @nemrutco can you please will out the issue template?

Edited original post.

**Comment by driesvints** [comment]
We'll need some code on how to reproduce this.

**Comment by netpok** [comment]
I wasn't been able to reproduce this as models are singular by default.

This aside the `Str::singularize('reserves')` does indeed produce `reserf` as output, but this is handled by the Doctrine Inflector, so it should be reported to them.

**Comment by driesvints** [comment]
I agree with @netpok. @nemrutco feel free to open an issue with the Doctrine Inflector.
