### ISSUE TITLE
Striping last # from mysql password in config cache file

### ISSUE THREAD

**Issue by sharadjaiswal1411** [laravel/framework#30135]
- Laravel Version: 5.8.*
- PHP Version:7.1
- Database Driver & Version: MYSQL

### Description:
This issue comes whenever your mysql password ends with a hash(#) 

### Steps To Reproduce:
In env file suppose your mysql password is DB_PASSWORD=xyz@qwe12#. then when config is cached it removes # from the password. If you open your /bootstrap/cache/config.php you see the last # of the password is striped and you will get an error msg SQLSTATE[HY000] [1045] Access denied for user

**Comment by devcircus** [comment]
Does wrapping the password in quotes help? See https://laravel.com/docs/5.8/upgrade#environment-variable-parsing

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
