### ISSUE TITLE
mix() generated URLs point to localhost on external server addresses

### ISSUE THREAD

**Issue by rivatove** [laravel/framework#30139]
- Laravel Version: 5.8.32
- PHP Version: 7.3.7

### Steps To Reproduce: Use the mix helper and check assets' url on external browserSync/ngrok address.

Mix helper: http://prntscr.com/pcwon3
Asset helper: http://prntscr.com/pcwpdl

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
