### ISSUE TITLE
Query/Builder method exists() does not go together with limit(0) or take(0) as expected

### ISSUE THREAD

**Issue by doubleb89** [laravel/framework#30136]
Hi there,

using:
Laravel Framework 5.7

From the Docs:
"Determining If Records Exist
Instead of using the count method to determine if any records exist that match your query's constraints, you may use the exists and doesntExist methods:"
```
return DB::table('orders')->where('finalized', 1)->exists();
```

I searched for this unexpected behaviour but did not find any results mentioning it.

If you are trying to "empty" a (Eloquent) query by using the $query->limit(0) or $query->take(0) functions (while using a scope limiting scope for whatever reason for example) and check if any results exist afterwards, by using the exists() function, the exists() function returns true.

E.g. entering this in artisan tinker:
```
User::query()->limit(0)->exists();
```
and
```
User::query()->take(0)->exists();
```

unexpectedly (at least imho) return:
```
true
```

whereas entering this:
```
User::query()->limit(0)->count();
```
returns:
```
0
```

and:
```
User::query()->where('id', 'noMatchingId')->exists();
```
returns:
```
false
```

So the Database\Query\Builder methods exists() and count() are not interchangeable in case of checking for existing records  as oppposed to the description in the docs.

Best Wishes,
douBleB89

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by doubleb89** [comment]
Hey,

I updated to Laravel 6.0 and the exact same unexpected behaviour occurs.

Best Wishes,
douBleB89

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by doubleb89** [comment]
I could not find anyone else stumbling across this.
Therefore i suggest to re-open this issue making it a subject to be discussed at least.
