### ISSUE TITLE
[5.8] required_if validation not working properly when combined with other rules in a single string

### ISSUE THREAD

**Issue by pablosebastianr** [laravel/framework#30137]
- Laravel Version: 5.8
- PHP Version: 7.2
- Database Driver & Version: does not apply

### Description:
Combining different rules in a single string separating them with '|' character should be the same as writing each rule in an array

### Steps To Reproduce:
```php

    $data = [
        'option'    => 'one',
    ];

    $rules = [
        'option'    => 'required | in:one,two',
        'stuff'     => ['required_if:option,one','integer'],
    ];


    $validator = validator( $data, $rules );

    if ( $validator->fails() ){
        dd( $validator->errors());
    }
    else {
        dd( $validator->validated() );
    }

```
These rules won't pass the validation as expected and we get the message "The stuff field is required when option is one."

Now, if we rewrite the the rules like this:

```php
    $rules = [
        'option'    => 'required | in:one,two',
        'stuff'     => 'required_if:option,one | integer',
    ];
```

validation passes and it shouldn't. At least, the behavior it's not consistent. 
This also happens with Laravel 6.0

**Comment by dkulyk** [comment]
Space in rules:
`required_if:option,one | integer` translated as required_if option is 'one '(with space)

**Comment by pablosebastianr** [comment]
whoa.... that was a tricky one ... closing this then.
