### ISSUE TITLE
Parse error in Laravel 5.7

### ISSUE THREAD

**Issue by unknownbreakdown** [laravel/framework#30134]
ErrorException message:
`syntax error, unexpected 'img' (T_STRING), expecting ',' or ')' 
`

The line on the Blade file:
```
<a href="/">
    <img src="{{ asset('img/brand/blue.png') }}">
</a>
```

The line on the parsed file:
```
<a href="/">
    <img src="{{ asset('img/brand/blue.png')); ?>">
</a>
```

Already tried after running:
```
php artisan view:clear
php artisan cache:clear
```

PHP version: 7.1.3

**Comment by ManojKiranA** [comment]
```
<a href="/">
    <img src="{{ asset('img/brand/blue.png')); ?>">
</a>
```

works fine for me

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
