### ISSUE TITLE
In Laravel Framework 6.0.3, I am using “table field/column” as varchar type not integer type. But why trimming first 0(zero)?

### ISSUE THREAD

**Issue by Robiullah2244** [laravel/framework#30151]
- Laravel Version: 6.0.3
- PHP Version: 7.3.2

Before I used laravel 5.*. But I didn't face this kind of problem.

Now I am using Laravel Framework 6.0.3

Here, "Phone" is a field of "Employee" table and "Phone" type is string/varchar.

**Steps:** 
1) Save one "Employee" information with **phone = "01679420786"**

**2)** Get Employee and and then dd()
`public function getEmployee()
    {
        $employee = Employee::get();
        dd($employee[0]->phone);
    }`

**3)** Output in browser: **1679420786**

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by Robiullah2244** [comment]
> Hi there,
> 
> Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:
> 
> * [Laracasts Forums](https://laracasts.com/discuss)
> * [Laravel.io Forums](https://laravel.io/forum)
> * [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
> * [Discord](https://discordapp.com/invite/KxwQuKb)
> * [Larachat](https://larachat.co)
> * [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
> 
> However, this issue will not be locked and everyone is still free to discuss solutions to your problem!
> 
> Thanks.

Sorry. Actually I am new
