### ISSUE TITLE
ShouldBroadcastNow not using .env definitions

### ISSUE THREAD

**Issue by georgimorozov** [laravel/framework#30162]
- Laravel Version: 6.0.2
- PHP Version: 7.3.5
- Database Driver & Version:

### Description:
I have my job queue set up using redis for long running jobs and I am trying to configure my user notification events to implement ShouldBroadcastNow (ie use the sync driver and bypass the queue).

### Steps To Reproduce:

When implementing ShouldBroadcastNow for a notification event, laravel attempts to use the fallback default values for mysql in config/database.php instead of using the sync driver (not sure if this is a bug in itself)

Even though I am expecting it to use the sync driver, I am fine with it using the db, however, it does not load the db configs from the .env file it seems. If switch back the implementation to ShouldBroadcast (using redis as a queue driver) everything works fine. It works fine using the database driver as well.

**Comment by driesvints** [comment]
Can you maybe create a test repo which reproduces the problem? Make sure to add any custom code in a separate commit.

**Comment by georgimorozov** [comment]
> Can you maybe create a test repo which reproduces the problem? Make sure to add any custom code in a separate commit.

I cant seem to replicate the issue in a new repo, however, I managed to "occasionally" replicate the issue in my codebase. The issue arises if you run ```php artisan config:clear``` and then try to trigger an event directly in the routes file (on a test route which is a closure). 

So lets say you have a rendered page open (with an active websockets connection), and blank page open (that you reload to trigger the closure route).

If you run ```php artisan config:clear``` and refresh the closure route page, you get the error and continue to get it on the rendered page.

Running ```php artisan config:cache``` and reloading the pages fixes the issue.

**Comment by driesvints** [comment]
If you can't replicate the issue on a fresh repo then it's a good indication that there might be something wrong specifically within your app.

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by dranes** [comment]
I had this issue too because my configuration was BROADCAST_DRIVER=redis and QUEUE_DRIVER=redis,  because of this every single event with ShouldBroadcastNow was trying to connect to redis on 127.0.0.1 instead of my actual redis server configured in my .env

the solution for me was to create a new redis connection called 'sync' 

```
'redis' => [

        'client' => 'predis',

        'default' => [
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => env('REDIS_DATABASE', 0),
        ],
        'pubsub' => [
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => env('REDIS_PUBSUB_DATABASE', 1),
        ],
        
        'sync' => [
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => env('REDIS_PUBSUB_DATABASE', 3),
        ],
```
I think this is the why

https://github.com/laravel/framework/commit/19cc052ec51ad492ca4646f7cd3d4d9bd303dfc1#diff-e526262c4637fb5e17fbe8f3788b97a9R107

**Comment by driesvints** [comment]
@dranes your config file seems a bit out of date with the current one. Also: the current ENV variable for queues is called "QUEUE_CONNECTION" so I believe you're running on a pretty old laravel version.

**Comment by dranes** [comment]
@driesvints I'm using 5.8 maybe is an old file from a previous version, but anyhow my real problem is with the config/broadcasting.php  take a look 

```
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Default Broadcaster
    |--------------------------------------------------------------------------
    |
    | This option controls the default broadcaster that will be used by the
    | framework when an event needs to be broadcast. You may set this to
    | any of the connections defined in the "connections" array below.
    |
    | Supported: "pusher", "redis", "log", "null"
    |
    */

    'default' => env('BROADCAST_DRIVER', 'null'),

    /*
    |--------------------------------------------------------------------------
    | Broadcast Connections
    |--------------------------------------------------------------------------
    |
    | Here you may define all of the broadcast connections that will be used
    | to broadcast events to other systems or over websockets. Samples of
    | each available type of connection are provided inside this array.
    |
    */

    'connections' => [

        'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'encrypted' => true,
            ],
        ],

        'redis' => [
            'driver' => 'redis',
            'connection' => 'pubsub',
        ],

        'log' => [
            'driver' => 'log',
        ],

        'null' => [
            'driver' => 'null',
        ],

    ],

];
```

The connection for broadcaster when using redis should be in my case "pubsub" that never happens it just wants to use the default connection 127.0.0.1 

I'm going to review everything again; maybe I'm misunderstanding how this should be configured. 

Thank you for the answer
