### ISSUE TITLE
[6.x] Many to Many polymorphic pivot wrong table name

### ISSUE THREAD

**Issue by Tantriss** [laravel/framework#30169]
- Laravel Version: 6.1.0
- PHP Version: 7.3.9
- Database Driver & Version: Driver Mysql for MariaDB 10.4

Hi !
### Description:
When defining a Many to Many Polymorphic relation, the Pivot model should extends `Illuminate\Database\Eloquent\Relations\MorphPivot` which extends `Pivot`.

This is important because the `Pivot` class use the `Illuminate\Database\Eloquent\Relations\Concerns\AsPivot` which override the function `getTable()` in order to singular(ize ?) the table name.

But the table name become plural when trying to get the related from the Pivot model and it crash :(
 
See the steps to reproduce in how to fix it if it's a real bug, but I'd like to discuss it in an issue before because I'm not totally sure I did all things right ^^

### Steps To Reproduce:

We have `items` with a default attribute `price`.
These items can be in a list `A` with a different price.
The same items can be in a second list `B` with a different price.

So we create a table `items`, a table `A` (representing the list `A`) another `B` (representing the list `B`) and a polymorphic pivot `listable` which store the `price` associated with the list the item is in.

Model `Listable`
-----
```php
class Listable extends MorphPivot
{
    public function a()
    {
        return $this->morphedByMany(A::class, 'listable');
    }
    public function b()
    {
        return $this->morphedByMany(B::class, 'listable');
    }
}
```

Model `A`
-----
```php
class A extends Model
{
    public function items()
    {
        return $this->morphToMany(Item::class, 'listable')
                    ->as('items')
                    ->using(Listable::class)
                    ->withPivot(['price']);
    }
}
```

Model `B`
-----
```php
class A extends Model
{
    public function items()
    {
        return $this->morphToMany(Item::class, 'listable')
                    ->as('items')
                    ->using(Listable::class)
                    ->withPivot(['price']);
    }
}
```

The table name is correctly singular when doing

```php
$obj = new Listable();
dump($obj->getTable()); // return "taskable"
```
But when trying to get the related model, the table name became plural.
The relation is defined using : 

```php
$obj = new Listable();
dump($obj->a); // Throw Exception ''Base table or view not found: 1146 Table 'listables' doesn't exist"
```

When looking at `morphedByMany` (`framework/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php@581`), it calls `morphToMany` (`framework/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php@513`).

This function don't use the `getTable()` method but this piece of code : 
```php
if (! $table) {
    $words = preg_split('/(_)/u', $name, -1, PREG_SPLIT_DELIM_CAPTURE);

    $lastWord = array_pop($words);

    $table = implode('', $words).Str::plural($lastWord);
}
```
And this pluralize the word even if the model represents a Pivot table.

Shoudn't it just call `getTable()` which is already modified by the `asPivot` trait ?

After reading it again, the problematic function is morphToMany, so even this throw an Exception : 

```php
$obj = new A();
dump($obj->items); // Throw Exception ''Base table or view not found: 1146 Table 'listables' doesn't exist"
```
I'm starting to think I made a mistake somewhere because I don't find any other issues here or I don't use the right terms....

Help ! ^^

**Comment by driesvints** [comment]
> because I'm not totally sure I did all things right ^^

Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
