### ISSUE TITLE
Verification Email not getting the hash from the request

### ISSUE THREAD

**Issue by DExploN** [laravel/framework#30163]
- Laravel Version: 6.0.4
- PHP Version: 7.3.0
- Database Driver & Version: MYSQL

### Description:

Hello, I have a similar problem https://github.com/laravel/framework/issues/29904

It is solved override method  trait VerifiesEmails::verify()

before

```
if (! hash_equals((string) $request->route('hash'), sha1($request->user()->getEmailForVerification()))) {
            throw new AuthorizationException;
        }
```

after

```
 if (! hash_equals((string) $request->query('hash'), sha1($request->user()->getEmailForVerification()))) {
            throw new AuthorizationException;
        }

```
But its not good

**Comment by driesvints** [comment]
We haven't gotten any reports about this yet and the previous other closed his own issue which leads to believe there's something wrong in the app itself.

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by DExploN** [comment]
Reason found:

namespace Illuminate\Routing\Router.php:

Laravel 5:

```
public function emailVerification()
    {
        $this->get('email/verify', 'Auth\VerificationController@show')->name('verification.notice');
        $this->get('email/verify/{id}/{hash}', 'Auth\VerificationController@verify')->name('verification.verify');
        $this->post('email/resend', 'Auth\VerificationController@resend')->name('verification.resend');
    }
```

Laravel 6:

```
public function emailVerification()
    {
        $this->get('email/verify', 'Auth\VerificationController@show')->name('verification.notice');
        $this->get('email/verify/{id}', 'Auth\VerificationController@verify')->name('verification.verify');
       $this->get('email/resend', 'Auth\VerificationController@resend')->name('verification.resend');
}
```
I native write this routes in web.php

**Comment by francois-neosurf** [comment]
Hello,

I have also the same issue, but the best solution is to override the route (Illuminate\Routing\Router.php) by an update in the route file (web.php).

Like below :
`Route::get('email/resend', 'auth\verificationcontroller@resend')->name('verification.resend');`

Regards.

**Comment by acacha** [comment]
FYI: https://laravel.com/docs/6.x/upgrade#email-verification-route-change
