### ISSUE TITLE
[Validation] Images validation rule: tiff not supported?

### ISSUE THREAD

**Issue by zack6849** [laravel/framework#30167]
- Laravel Version: 6.0
- PHP Version: 7.3
- Database Driver & Version: N/A

### Description:
Tiff isn't in the list of valid extensions for images here:
https://github.com/laravel/framework/blob/6.x/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L1030

Obviously, adding it is trivial, I'm happy to submit a PR for that, but I guess the question is do you guys actually want every image type there for coverage or do you just care about the most common ones?

Some I can think of, that aren't there:

- .tiff
- .raw
- .eps (kind of an image?)

Is the goal for this validator to validate it's a valid image, or specifically an image that's viewable to a web browser?

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!

**Comment by zack6849** [comment]
@driesvints my bad, I didn't realize improvements went somewhere else, i'll file it there.

**Comment by driesvints** [comment]
@zack6849 no worries!
