### ISSUE TITLE
[Eloquent]  selectRaw() giving different output than select(DB::raw()) ?

### ISSUE THREAD

**Issue by ipontt** [laravel/framework#30164]
- Laravel Version: 6.0
- PHP Version: 7.3.4
- Database Driver & Version: default pgsql driver, PostgreSQL (10)

### Description:
It is my understanding `selectRaw` should be used over `select(DB::raw(...))`, and that both should provide the same result according to the <a href="https://laravel.com/docs/6.x/queries#raw-methods">documentation</a>.
For some reason, I'm getting different results.

### Steps To Reproduce:
 -  Set up 2 models. `Parent` and `Child`.
 -  Give `Child` model an `allowance` attribute (Just a numeric attribute) 
 -  Set up the relationship between both models. (`Parent` has many `Child` using `children()` public method)
 -  Persist a `Parent` and 2 `Child` models after associating them.
 -  Give those children some allowance (let's say 1000 for the first and 1500 for the other)
```php
$parent = Parent::create();
Child::create(['parent_id' => $parent->id, 'allowance' => 1000]);
Child::create(['parent_id' => $parent->id, 'allowance' => 1500]);
```
```php
Parent::select('id')->withCount(['children as total_allowance' => function($count) {
    $count->selectRaw('sum(allowance)');
}])->first();
# Expected: App\Parent { id: 1, total_allowance: 2500 }
# Got:      App\Parent { id: 1, total_allowance: 2 }
```
```php
Parent::select('id')->withCount(['children as total_allowance' => function($count) {
    $count->select(\DB::raw('sum(allowance)'));
}])->first();
# Expected: App\Parent { id: 1, total_allowance: 2500 }
# Got:      App\Parent { id: 1, total_allowance: 2500 }
```
Is this a bug or am I missing something terribly obvious?

**Comment by staudenmeir** [comment]
The documentation is incorrect: https://github.com/laravel/framework/issues/30050

**Comment by ipontt** [comment]
Alright then. Hopefully that's the only wrong bit about the documentation (concerning my project at least)
