### ISSUE TITLE
Change Password Column name Issue

### ISSUE THREAD

**Issue by ahmedsayedabdelsalam** [laravel/framework#30160]
- Laravel Version: 6.0.4
- PHP Version: 7.3.9
- Database Driver & Version: mysql Ver 5.7

### Description:
I have a scenario that column password has a different name that Laravel uses, I found that `illuminate/Auth/EloquentUserProvider.php` look for password literally not the column name.

**Comment by MattStrauss** [comment]
I may be wrong, but I think you are referring to the below method in the `Illuminate\Auth\EloquentUserProvider`

```
    /**
     * Validate a user against the given credentials.
     *
     * @param  \Illuminate\Contracts\Auth\Authenticatable  $user
     * @param  array  $credentials
     * @return bool
     */
    public function validateCredentials(UserContract $user, array $credentials)
    {
        $plain = $credentials['password'];

        return $this->hasher->check($plain, $user->getAuthPassword());
    }
```
The  method takes the `password` as an argument in the `credentials` array and then checks it against the actual, in this case, DB field by using the `$user->getAuthPassword()` method. 

This method is from the `\Illuminate\Contracts\Auth\Authenticatable` trait. So you should be able to override it in your `User` model which implements the trait, to have it return the appropriate field to have the password validated against.

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!
