### ISSUE TITLE
Eager Loading: Subrelation does not work

### ISSUE THREAD

**Issue by bastian-schur** [laravel/framework#30178]
- Laravel Version: 5.8.35 (after updating from 5.7.19)
- PHP Version: 7.2.19
- Database Driver & Version: Mysql 5.7.27

### Description:
After updating to laravel 5.8 i've a problem with eager loading in one of my relations.
Code snippet:
```
class Property extends \Illuminate\Database\Eloquent\Model {

        ...
        public function zipCode()
        {
            return $this->belongsTo( ZipCode::class , 'zip_code_id' );
        }

        public function additionalTime()
        {
            return $this->zipCode->belongsTo( AdditionalTime::class , 'id' , 'zip_code_id' );
        }
        ...
    }
```

In my model i've this two relations: property to zipCode and additionalTime is an relation over zipCode.I know that would be the right way to place this in the ZipCode model, but this is in a different package.The relation itself works fine, but I have the problem that Eager Loading for additionalTime not work. If I use eager loading, I get an error that ZipCode would be null. (Thrown in the additionalTime function)

Additional note: The ZipCode table is located in a different database. But even this has not made any problems in recent years.

### Steps To Reproduce:
1) Create 3 Models, like the snippet see above
2) This code without eagerloading works:

```
foreach ( \App\Models\Property::get() as $property ) {
        dump($property->additionalTime);
    }
```

3) This code with eagerloading works NOT:
```
foreach ( \App\Models\Property::with('additionalTime')->get() as $property ) {
        dump($property->additionalTime);
    }
```

**Comment by dkulyk** [comment]
Try this:
```php
    public function additionalTime()
    {
        return $this->belongsTo(AdditionalTime::class , 'zip_code_id' , 'zip_code_id' );
    }
```

**Comment by bastian-schur** [comment]
@dkulyk thanks, it works!

Any idea what changed in this version?I have just read the change of methods in this context: 

> The getForeignKey, getQualifiedForeignKey, and getOwnerKey methods of the BelongsTo relationship have been renamed to getForeignKeyName, getQualifiedForeignKeyName, and getOwnerKeyName respectively, making the method names consistent with the other relationships offered by Laravel.

**Comment by dkulyk** [comment]
> Any idea what changed in this version?I have just read the change of methods in this context:

If you did not use this methods directly you should not worry :)
