### ISSUE TITLE
Performance issues when using multiple RouteServiceProviders

### ISSUE THREAD

**Issue by ederuiter** [laravel/framework#30171]
- Laravel Version: 5.8.35
- PHP Version: 7.3.9

### Description:

When using multiple modules where each module has it's own RouteServiceProvider, the routes are loaded/refreshed by each RouteServiceProvider (instead of once per application). Even when using route caching the (global) cached file is loaded/unserialized for each RouteServiceProvider

This leads to performance issues, especially in tests where the application is instantiated once per test. In our case the application boot time was inflated from ~15 ms to ~65ms (by having around 20 modules with each having their own RouteServiceProvider). 

#### With route caching:
Define multiple RouteServiceProvider's and observe that the cached file is included/evaluated multiple times. 

#### Without route caching:
Define multiple RouteServiceProvider's and observe that RouteCollection::refreshActionLookups is called multiple times.

### Workaround

Overload the loadCachedRoutes of RouteServiceProvider (this only fixes the cached case) with something like this:

```
  protected function loadCachedRoutes(): void
  {
        if ($this->app->has('routes_cached')) {
            return;
        }

        parent::loadCachedRoutes();
        $this->app->instance('routes_cached', true);
    }

```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by ederuiter** [comment]
Re-tested with Laravel 6.1.0 and the same issue still exists

**Comment by driesvints** [comment]
The thing is that the RouteServiceProvider isn't designed for this and that it's only meant to be used once as your main app's route file. If you need to separate into modules it might be worth to load routes using the service provider's `loadRoutesFrom` method just as you do with packages?
