### ISSUE TITLE
Running `php artisan make:model {model_name_here} -a` takes minute or more to generate controller. 

### ISSUE THREAD

**Issue by Kasparsu** [laravel/framework#30174]
- Laravel Version: 6.1.0
- PHP Version: 7.3.3
- Database Driver & Version: N/A

### Description:
Running `php artisan make:model {model_name_here} -a` takes minute or more to generate controller. 

I took a look at what causes this behavior. It seems that the culprit is the fact that it generates the migration first and then the controller. At the end of the `make:migration` it dumps composer autoload to make sure that the migrations are registered by the class loaders. This, however, takes a long time and is the culprit of the situation. I propose that order in which `-a` or in that matter any combination flag does the generation would be switched so migrations are always generated last. It would be helpful to add a small log message as well that autoload is being dumped after and it takes a couple of extra seconds and the user should not worry about the fact that all the files have appeared and generated, but the command still is keeping command line busy. 

### Steps To Reproduce:
run `php artisan make:model {model_name_here} -a` on a clean laravel installation

**Comment by devcircus** [comment]
Seems like an ok change but dump-autoload shouldn't take that long. For me, it's never been more than a few seconds.

**Comment by Kasparsu** [comment]
> Seems like an ok change but dump-autoload shouldn't take that long. For me, it's never been more than a few seconds.

oh, im running it on a docker on windows that slows it down considerably.

**Comment by driesvints** [comment]
This only takes a second or two for me on my machine so I don't think this is a huge problem. If you're running this through Docker then the culprit might elsewhere.

**Comment by Kasparsu** [comment]
> This only takes a second or two for me on my machine so I don't think this is a huge problem. If you're running this through Docker then the culprit might elsewhere.

Sure it might be the fact that it takes longer to do dump-autoload but this change will change nothing in the pipeline and will fix this kind of issue for some other parties as well. For those whose autoload does not take forever nothing will change. except for tiny line of log that says "Dumping Composer autoload" (albeit this can be dropped as it is reorder of these generations I am really after)
