### ISSUE TITLE
Custom intermediate models table name are ignored

### ISSUE THREAD

**Issue by gsylvestre** [laravel/framework#30183]
- Laravel Version: 6.1.0
- PHP Version: 7.2.17
- Database Driver & Version: MySQL 5.7.26

### Description:
When using an intermediate model in a Many To Many relationship, we expect the pivot table name defined in the Pivot model to be taken into account. It is not.

Considering the following model : 
```php
namespace App;
use Illuminate\Database\Eloquent\Model;

class ModelA extends Model
{
    public function modelB()
    {
        return $this->belongsToMany('App\ModelB')->using('App\PivotModel');
    }
}
```

and the following pivot model : 
```php
namespace App;

use Illuminate\Database\Eloquent\Relations\Pivot;

class PivotModel extends Pivot
{
    protected $table = "my_pivot";
}
```
we expect Eloquent to use `my_pivot` as the pivot table name. It is in fact using the default table name (`model_a_model_b`).

**Comment by driesvints** [comment]
Please see https://github.com/laravel/framework/issues/26864

**Comment by staudenmeir** [comment]
It's not possible for Laravel to get the pivot table from `using()`.

You can provide the pivot class like this:

```php
class ModelA extends Model
{
    public function modelB()
    {
        return $this->belongsToMany('App\ModelB', 'App\PivotModel');
    }
}
```
