### ISSUE TITLE
Request::fullUrl return non https version

### ISSUE THREAD

**Issue by Arsiirasheed** [laravel/framework#30182]
- Laravel Version: 5.7
- PHP Version: 7.2.19
- Database Driver & Version:

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
