### ISSUE TITLE
Bug Route::get(...)->name(...)

### ISSUE THREAD

**Issue by falur** [laravel/framework#30181]
- Laravel Version: 6.0.4
- PHP Version: 7.2.11
- Database Driver & Version:

### Description:
```php
Route::get('', function () {
    return view('dashboard');
})->name('dashboard');

dd(Route::has('dashboard')); // FALSE !!!

////////

Route::name('dashboard')->get('', function () {
    return view('dashboard');
});

dd(Route::has('dashboard')); // TRUE

////////

Route::get('', ['as' => 'dashboard', function () {
    return view('dashboard');
}]);

dd(Route::has('dashboard')); // TRUE

////////
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by MattStrauss** [comment]
@falur 

I tested this on my local machine and found the same issue. However, if you run the same die and dump in a controller or in views, your first example returns true as expected. So it seems to only be an issue with the routes file itself. 

Still though, it's definitely not expected behavior as you may need to perform such a check in the routes file and it would fail. Therefore I do think this is a bug in the Framework.

**Comment by devcircus** [comment]
The "name" methods used in those different situations are run at different times. It seems strange to run logic separate from actual routes, inside your routes file.

The one that "works", uses the RouteRegistrar, the other uses the Route class. 

There are possibly other examples where parts of the application are not loaded at that time, just like this example.
