### ISSUE TITLE
migrate:refresh has problem with pivot table

### ISSUE THREAD

**Issue by mitra-razmara** [laravel/framework#30180]
- Laravel Version: 5.8
- PHP Version: 7.3.0
- Database Driver & Version: mysql

Description:
I am not sure that is a bug, But maybe helps to improve "migration"
I have 3 table and there is my "up" functions content:
shots:
`$table->bigIncrements('id');
            $table->string('title');
            $table->timestamps();`
shot_tag:
`$table->unsignedBigInteger('shot_id')->index();
            $table->foreign('shot_id')->references('id')->on('shots')->onDelete('cascade')->onUpdate('cascade');
            $table->unsignedBigInteger('tag_id')->index();
            $table->foreign('tag_id')->references('id')->on('tags')->onDelete('cascade')->onUpdate('cascade');
            $table->timestamps();`
tags:
`$table->bigIncrements('id');
            $table->string('title')->unique();
            $table->timestamps();`
When I ran migrate:refresh command, I encountered this problem 'Foreign key constraint is incorrectly formed'
I removed "create_shot_tag_table" file from "database/migrations" directory and ran "migrate:refresh" again and everything works fine. Then I added "create_shot_tag_table" to "database/migrations" directory and ran "migrate" command and problem solved

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
