### ISSUE TITLE
Model ->delete() returns true for race condition where two instances both attempt to delete the same database row.

### ISSUE THREAD

**Issue by Mzril** [laravel/framework#30187]
- Laravel Version: 6.0
- PHP Version: 7.3.7
- Database Driver & Version: MySQL

### Description:

In race conditions where two separate instances attempt to delete the same model, both instances return true. Using the DB facade to delete the row simultaneously on two different instances has one return 0 and the other return 1.

This causes double model events and the like when only one deletion occurred. Considering the DB returns the number of rows deleted, one should just return false.

### Steps To Reproduce:

(You may want to use a split pane terminal for maximum race condition reproducing)

1. Open two tinker shells and get the same model from both.

2. Call $model->delete() in both shells. BOTH return true.

**Comment by driesvints** [comment]
A model indeed always returns true at the end of a delete statement. The thing is that concurrency is something you'll need to deal with in your own app and can't be done within model class itself. We have no way of knowing if a record is being manipulated at the same time.
