### ISSUE TITLE
[6.x] Maximum execution time exceeded when using relation belongsToMany with Eloquent

### ISSUE THREAD

**Issue by larsurilch** [laravel/framework#30199]
- Laravel Version: 6.1.0
- PHP Version: PHP 7.2.19-0ubuntu0.18.04.2 (cli)
- Database Driver & Version: PostgreSQL 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1)

### Description:
After you insert data into an intermediate table, data is not returned in a query. The following error occurs:
```
{
    "message": "Maximum execution time of 30 seconds exceeded",
    "exception": "Symfony\\Component\\Debug\\Exception\\FatalErrorException",
    "file": "/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php",
    "line": 604,
    "trace": []
}
```
For this error to happen it is enough that only 1 record is inserted in the database.

### Steps To Reproduce:

- Create a Basic Model of a Many To Many Relationship.
- Create a method with **find** and **with**

### Example:
- Model Sepultura.php
```
<?php

namespace App;

class Sepultura extends Model
{
    protected $table = 'sepulturas';

    protected $fillable = ['lote', 'lote_anterior', 'quadra', 'quadra_anterior'];

    protected $appends = ['proprietario_list'];

    public function proprietarios()
    {
        return $this->belongsToMany('App\Proprietario', 'proprietarios_sepulturas', 'sepultura_id', 'proprietario_id')->withTimestamps();
    }

   public function getProprietarioListAttribute()
    {
        return array_map('strval', $this->proprietarios->pluck('id')->toArray());
    }
}
```
- Model Proprietario.php
```
<?php

namespace App;

class Sepultura extends Model
{
    protected $table = 'proprietarios';

    protected $fillable = ['nome', 'rg', 'cpf', 'telefone', 'email'];

    protected $appends = ['sepultura_list'];

    public function sepulturas()
    {
        return $this->belongsToMany('App\Sepultura', 'proprietarios_sepulturas', 'proprietario_id', 'sepultura_id')->withTimestamps();
    }

    public function getSepulturaListAttribute()
    {
        return array_map('strval', $this->sepulturas->pluck('id')->toArray());
    }
}
```
- Controller ProprietariosController.php
```
<?php

namespace App\Http\Controllers;

use App\Proprietario;

class ProprietariosController extends Controller
{
    private $proprietario;

    public function __construct(Proprietario $proprietario)
    {
        $this->proprietario = $proprietario;
    }

    public function show($id)
    {
        $proprietario = $this->proprietario->with('sepulturas')->find($id);

        if(count($proprietario->toArray()) > 0)
            return response()->json($proprietario);

        return response()->json(['error' => 'Resource not found!'], 404);
    }
}
```
The **show method** simply gives the error **Maximum execution time exceeded** when something is inserted in the **proprietarios_sepulturas** table.

I have the perfect code running on Laravel 5.8.

How to fix this problem ?!

Thanks

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by larsurilch** [comment]
Hello driesvints,

Many thanks for the reply. I put the problem here because it actually seems to be a framework problem in this release. I will wait to see if anyone is having the same problem.

Best regards

**Comment by ibrahimdolas** [comment]
Any solutions yet? 

I have a datatable which gets its data with ajax request. I can fetch model itself but when i try to fetch it with its relations, i get the max execution timeout exception. Its look like there is an infinite loop somewhere in core. Here is my code;

`$data = User::with('doctor')->get()->sortByDesc('created_at')->tojson();
return response()->json($data, 200);`
