### ISSUE TITLE
Unexpected behavior when using Session\Store::hasOldInput() with ConvertEmptyStringsToNull

### ISSUE THREAD

**Issue by inxilpro** [laravel/framework#30193]
- Laravel Version: 5.4+
- PHP Version: N/A
- Database Driver & Version: N/A

### Description:

Currently, `hasOldInput()` performs an `is_null()` check to determine if the input exists in the `_old_input` session array. Normally, this is just fine, but returns a false negative when the old input is an empty string that was converted to `null` (via `ConvertEmptyStringsToNull`).

An alternative solution would be to swap out the existing logic:

```php
public function hasOldInput($key = null)
{
    $old = $this->getOldInput($key);
    return is_null($key) ? count($old) > 0 : ! is_null($old);
}
```

…for something that just checks for the existence of the key in the old input array:

```php
public function hasOldInput($key = null)
{
    $old = $this->get('_old_input', []);
    return is_null($key) ? count($old) > 0 : Arr::exists($old, $key);
}
```

This seems perhaps to be more true to the intent of the function, but could also be considered a backwards-incompatible change, or not the intended behavior. I thought I'd submit it as an issue first before submitting a PR.

### Practical Example:

You can see the effect of this in https://github.com/glhd/aire/issues/34, which uses `hasOldInput` when binding data to a form. Aire essentially handles data binding in the following order of priority:

 1. If old input exists, always re-use that first
 2. Otherwise, if data is bound to the input, use that
 3. Finally, if a "default value" was set, use that last

The problem shows up when the a user:

 - Opens a form with bound data
 - Clears that bound data from the input
 - Submits the form but validation errors prevent it from submitting
 - When the form is presented again, the bound value is used because the old input is `null`

I'm happy to submit a PR with the above code change, but I thought it's worth a discussion first.

**Comment by driesvints** [comment]
Can you just provide a simple code snippet that reproduces the problem?

**Comment by inxilpro** [comment]
Here's a test case. It's assuming a typical Laravel installation, where `TrimStrings` and `ConvertEmptyStringsToNull` are in the global middleware chain, and `StartSession` is in the `"web"` middleware group.

```php
public function test_has_nullable_old_input()
{  
  Route::post('/demo', function(Request $request) {
    $request->validate([
      'demo' => 'required', // "demo" is set to required to trigger a validation error
      'demo2' => 'nullable',
    ]);
  })->middleware('web');
  
  // Post to our route with empty strings as both values
  $this->withSession([])
    ->post('/demo', [
      'demo' => '', 
      'demo2' => ''
    ]);
  
  // Even though we did technically provide input (an empty string),
  // the following will fail. If you remove ConvertEmptyStringsToNull
  // from the middleware chain, it will pass.
  
  $this->assertTrue(session()->hasOldInput('demo2'));
}
```

**Comment by devcircus** [comment]
That seems like the expected behavior to me.  If your app needs to know the difference between empty string and null, then the middleware should be removed.

**Comment by driesvints** [comment]
I agree with @devcircus here. I don't think this can be done the way you want.

**Comment by inxilpro** [comment]
@devcircus @driesvints I'm OK with calling this the expected behavior, but just to be clear—the app doesn't need to know the difference between an empty string and `null`—it's more that `hasOldInput` treats them differently, which is somewhat unexpected when you're normalizing empty strings to `null`.

It's a pretty easy fix for our use-case, but I still would argue that providing **either** an empty string or `null` should cause `hasOldInput` to return `true`.

**Comment by devcircus** [comment]
To be clear, I've never really thought about this, so this is strictly and off-the-cuff opinion. I've always thought of that middleware to mean, "i want empty inputs to be treated the same way as null". In that case, I would expect the old input for that field to be null. On the other hand, I get what you're saying and maybe this is something you could bring to the ideas repo for discussion.

**Comment by inxilpro** [comment]
Yeah, I don't think there's anything wrong with the middleware—it behaves exactly as expected. I just think that there's a strong argument for `hasOldInput` returning true if input was provided, regardless of its value (`null`, `""`, or `[]` should all return true in my mind).
