### ISSUE TITLE
Validation problem (laravel dont validate if del array input)

### ISSUE THREAD

**Issue by vendaagil** [laravel/framework#30209]
- Laravel Version: 6.0.3
- PHP Version: 7

### Description:
Hello, I found one Bug, if you do a validation on a input name[] (array) and the user deletes the input, the validator ignore.

### Steps To Reproduce:
Make a validation on a field that is null on $request.

 request()->validate([
            'products.*' => 'required',
]);

This will not throw a error.

if use 'products' without '.*' then throws the error.

and i can not use only 'products' because when have de inputs they will become as array and validator will give a error.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by vendaagil** [comment]
Hello, why closed? this is a bug

**Comment by vendaagil** [comment]
> Hi there,
> 
> Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:
> 
> * [Laracasts Forums](https://laracasts.com/discuss)
> * [Laravel.io Forums](https://laravel.io/forum)
> * [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
> * [Discord](https://discordapp.com/invite/KxwQuKb)
> * [Larachat](https://larachat.co)
> * [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
> 
> However, this issue will not be locked and everyone is still free to discuss solutions to your problem!
> 
> Thanks.

Hello, why closed? this is a bug
