### ISSUE TITLE
Validation bug on array field

### ISSUE THREAD

**Issue by vendaagil** [laravel/framework#30211]
Laravel Version: 6.0.3
PHP Version: 7

### Description:
Hello, I found one Bug, if you do a validation on a input name[] (array) and the user deletes the input, the validator ignore.

### Steps To Reproduce:

**Create a empty form.**

create a controller for the action of this form with this:

```
request()->validate([
'products.*' => 'required',
]);
```

**This will not throw a error**, **but is REQUIRED!**

**Comment by laurencei** [comment]
I think if you do

```
request()->validate([
    'products' => 'required|array',
]);
```

that solves it?

**Comment by vendaagil** [comment]
No, because the products is a array input,
```
<input name="products[]" />
<input name="products[]" />
```

So,  then will throw error when its correct, because is array

**Comment by vendaagil** [comment]
> I think if you do
> 
> ```
> request()->validate([
>     'products' => 'required|array',
> ]);
> ```
> 
> that solves it?

No, because the products is a array input,

<input name="products[]" />
<input name="products[]" />
So, then will throw error when its correct, because is array

**Comment by vendaagil** [comment]
> I think if you do
> 
> ```
> request()->validate([
>     'products' => 'required|array',
> ]);
> ```
> 
> that solves it?


I tested and it worked, thanks,
For those who are using the application the way I said and do not know, may be at risk of users delete in the browser and save templates without the requirements.
