### ISSUE TITLE
Chunking will sometimes miss rows because it's selecting some multiple times 

### ISSUE THREAD

**Issue by tpetry** [laravel/framework#30210]
- Laravel Version: 6.1.0
- PHP Version: 7.3.9
- Database: PostgreSQL 11.5

### Description:
The problem is the way the chunk implementation works: On a sorted dataset offset conditions are used to load all database rows using multiple queries. However, if you use your own sorting criteria, the `enforceOrderBy` method in `chunk()` will not add a sort.

I noticed on PostgreSQL when manually sorting by `created_at` some rows are loaded multiple times and some are completely missing. This seems to be due to the fact that the sorting is not defined as stable: If there are several lines with the same created_at value, these rows can be sorted differently by every query (possibly postgresql's parallel sorting is the problem).

In my opinion the code of the chunk method should be changed to ensure so the primary key is _always_ included in the ordering clauses to get a stable sorting order and prevent the above mentioned problem.

### Steps To Reproduce:
This bug had been hard to find and i can not provide a reliable test case to see it's defect.

**Comment by driesvints** [comment]
Hmm, I'd like to get some more opinions on this before I label this as a bug. Thanks for reporting.

**Comment by driesvints** [comment]
You're always free to attempt a pr btw.

**Comment by Sladewill** [comment]
Does this happen on the other method chunkById.

**Comment by staudenmeir** [comment]
I think this is rather the user's responsibility than Laravel's. We could add a note about it to the docs.

**Comment by driesvints** [comment]
@tpetry maybe a note to the docs for this would suffice indeed like @staudenmeir suggests. Feel free to send in a pr.
