### ISSUE TITLE
PrettyPageHandler displays passwords for DB and mail

### ISSUE THREAD

**Issue by jtibbles** [laravel/framework#30219]
- Laravel Version: 5.8
- PHP Version: 7.2
- Database Driver & Version:

### Description:
Using the PrettyPageHandler will expose many server parameters that should never be viewable on screen, including all Environment Variables. Database login details, mail server login details etc.

### Steps To Reproduce:
Force a page to throw an error. Easy example - on a form submission, forget to include  "use DB" at the top of the controller and try to select a DB table using using raw DB.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by jtibbles** [comment]
I'll upgrade to 6 tonight but I suspect this hasn't changed since then.

thanks
