### ISSUE TITLE
Why not use timestamps in jobs table?

### ISSUE THREAD

**Issue by 4unkur** [laravel/framework#30213]
https://github.com/laravel/framework/blob/6.x/src/Illuminate/Queue/Console/stubs/jobs.stub

As you can see, jobs table have fields: 
```
            $table->unsignedInteger('reserved_at')->nullable();
            $table->unsignedInteger('available_at');
            $table->unsignedInteger('created_at');
```

I'm wondering, why they are not timestamps?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by Synchro** [comment]
FWIW, I just ran into exactly this and wondered the same thing - I expected this to be considered a bug *if there isn't some obvious reason we have missed* for it not to be, which I assume is why the original report was phrased somewhat passively. Laravel uses proper timestamps for such fields elsewhere, so it's not clear why it would not do it here as well.

In other words, if there is no particular reason for these not to be timestamps, then this is indeed a bug and it is correct that it was reported here.

**Comment by KeyShang** [comment]
Why other tables use timestamp, only the jobs table use unsignedInteger? 
Isn’t consistency what we care about when writing codes?
