### ISSUE TITLE
Cannot get orderByRaw with direction binding to work

### ISSUE THREAD

**Issue by denitsa-cm** [laravel/framework#30224]
- Laravel Version: v5.8.33
- PHP Version: 7.3
- Database Driver & Version: mysql 8.0.15

### Description:

Cannot get `orderByRaw` with bindings to work - Syntax error or access violation

### Steps To Reproduce:

I want to run this query to order users by their name, with `null` values last, hence the `-` sign in front of `users.name`.

```
        $direction = 'asc';
        $test = User::orderByRaw('-users.name ?', [$direction]);
        dd($test->get());
```

The query above will throw this error:

```
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?' at line 1 (SQL: select * from `users` where `users`.`deleted_at` is null and `active` = 1 order by -users.name asc)"
trace: [{file: "C:\www\roam\vendor\laravel\framework\src\Illuminate\Database\Connection.php", line: 624,…},…]
```

Funnily, the query inside the brackets after `line 1` works fine and the `?` is not in it at all.

The following works but I want to pass the order as bindings....

```
User::orderByRaw("-users.name {$direction}")
```

**Comment by staudenmeir** [comment]
That's not possible: https://stackoverflow.com/q/2542410/4848587

**Comment by denitsa-cm** [comment]
I see 👍 Thanks for the link @staudenmeir

**Comment by geidelguerra** [comment]
This bite me yesterday. Thank!
