### ISSUE TITLE
No hint path defined for [errors]

### ISSUE THREAD

**Issue by flexchar** [laravel/framework#30226]
- Laravel Version: 6.0.4
- PHP Version: 7.3.9

### Description:
Laravel doesn't find path for built in error page layouts such as `@extends('errors::minimal')` (for neither of `errors::minimal, errors::layout, errors::illustrated-layout`);

If I publish pages and have ordinary view path pointer it of course works. However I have done it in the past and find it very useful just to extend the vendor provided layout. If it is an intentional change for version ^6.0.0, then this, sadly, may be closed. 

#### Real world example from another L5.8 project
![image](https://user-images.githubusercontent.com/9198896/66474959-9ce6b180-ea92-11e9-981f-e15df237b500.png)

### Steps To Reproduce:
1. Create blade view that extends built in error page layout.
![image](https://user-images.githubusercontent.com/9198896/66474141-fa79fe80-ea90-11e9-96dd-d4c41a6ef5ed.png)
```blade
@extends('errors::minimal')

@section('title', $title ?? $message)
@section('code', 200)
@section('message', $message ?? $title)
```

2. Return it as a view in a route:
```php
return view('pages.simple')->withMessage('they are simple yet pretty');
```
3. Get the following error `Facade\Ignition\Exceptions\ViewException
No hint path defined for [errors].` thrown: 
![image](https://user-images.githubusercontent.com/9198896/66474464-a6bbe500-ea91-11e9-893d-5b45b7849856.png)

**Comment by driesvints** [comment]
This looks like an Ignition issue so you might want to open up an issue on their repo: https://github.com/facade/ignition

**Comment by flexchar** [comment]
@driesvints unfortunately not. I deleted Ignition package and yet:
![image](https://user-images.githubusercontent.com/9198896/66733881-48ac4a80-ee61-11e9-93ff-181373442cea.png)

**Comment by xuanquynh** [comment]
The "errors::" view namespace is only registered on throwing exceptions.
https://github.com/laravel/framework/blob/869f02783a49cd0e16c66c0d362d2e4ea371f4b6/src/Illuminate/Foundation/Exceptions/Handler.php#L382

In fact, you directly call view() helper, there are no exceptions, so it caused the error 'no hinted path defined'

**Comment by flexchar** [comment]
Hey @xuanquynh, that's a great insight. 

However I can see that this method/behaviour been there since at least v5.7. Therefore, if it has worked before shouldn't it do now?

**Comment by xuanquynh** [comment]
> shouldn't it do now?

I am not sure, it still depends on your opinions. But I think you should use customized Exceptions to render an error page.

**Comment by flexchar** [comment]
To be clear it is NOT an error I am trying to display. Throughout the application I am working on, there are functions that executes and simply returns plain messages. I want to make use of built-in pretty error pages to display those messages.

I'm hoping that someone else could take a look on it. As unless it is indented to prevent using those layouts, this is unexpected shift in framework behavior. :)

**Comment by xuanquynh** [comment]
I have no idea. You may register it manually inside a service provider of you project, I think.

**Comment by alessandrobelli** [comment]
I have the same error by doing this:
<img width="722" alt="Bildschirmfoto 2019-12-02 um 18 58 35" src="https://user-images.githubusercontent.com/3796324/69982945-e2c17280-1535-11ea-9559-5df279a539fb.png">

https://laravel.com/docs/6.x/errors#render-method
```php
    public function render($request, Exception $exception)
    {
        if ($exception
            instanceof
            \Illuminate\Database\Eloquent\ModelNotFoundException) {
            return response()->view('errors.nomodel', [], 500);


        }
        return parent::render($request, $exception);
    }
```

**Comment by MattHowdy** [comment]
Hey Guys,
I had the same issue today, what was solved by changing @extends('errors:minimal') to  @extends('errors.minimal') in the view. So change the colon to dot. Hopefully it will help you!

**Comment by xuanquynh** [comment]
@MattHowdy Add "$this->registerErrorViewPaths();" line to the very first of render method.

```
public function render($request, Exception $exception)
{
    $this->registerErrorViewPaths();

   // your logic here.
}
```

**Comment by itanea** [comment]
@taylorotwell I had the same issue today. I thanks @xuanquynh for the solution.
May be this should be commited in repository ? Perhaps do you have another idea about this ?

**Comment by vipertecpro** [comment]
How about this most obvious way :-  

Controller

```
$pageData = Page::where('pageSlug','loginPage')->first();
            if($pageData === null){
                return view('errors.404',[
                    'title' => 'Login Page is Inactive',
                    'message'   => 'Login Page is Inactive',
                    'code'      => '404'
                ]);
            }
```
Blade

```
@extends('errors.minimal')

{{--@section('title', @$title ?? '')--}}
{{--@section('code', '404')--}}
{{--@section('message', @$message ?? '')--}}

@section('title')
    {{ $title ?? '' }}
@endsection

@section('code')
    {{ $code ?? '' }}
@endsection

@section('message')
    {{ @$message ?? '' }}
@endsection
```

Output

![404 error page](https://user-images.githubusercontent.com/11619188/104824395-4f511b00-5877-11eb-8e80-cdbca1ad7025.png)

**Comment by DiogoLindoso** [comment]
> Hey Guys,
> I had the same issue today, what was solved by changing @extends('errors:minimal') to @extends('errors.minimal') in the view. So change the colon to dot. Hopefully it will help you!

It works for me,
Laravel 7

**Comment by minhlong** [comment]
> Hey Guys,
> I had the same issue today, what was solved by changing @extends('errors:minimal') to @extends('errors.minimal') in the view. So change the colon to dot. Hopefully it will help you!

I am using Laravel 8 and it works for me,

Thanks so much,

**Comment by EAvila34** [comment]
Isn't work for me, Laravel 8
```
public function checkIfFileExist($fullPathFile)
    {
        $exist = file_exists($fullPathFile);
        if($exist)
        {
            return view('errors.404', ["message" => "Este archivo ya se encuentra en el servidor"]);
            //abort(404, ["message"=>"Este archivo se encuentra en el servidor"]);
            //throw new \Exception(, Response::HTTP_BAD_REQUEST);
        }
    }
```
laravel ignores completely this exception!

**Comment by Ash214** [comment]
Laravel Version: 9.25.1
PHP Version: 8.0.22

Having such error in my 

> resources/views/errors/404.blade.php

> InvalidArgumentException

`No hint path defined for [errors].`
![image](https://user-images.githubusercontent.com/20121328/185409306-64d25019-fa98-42d1-923e-499f4fb59f4d.png)

As write @DiogoLindoso 

> > Hey Guys,
> > I had the same issue today, what was solved by changing @extends('errors:minimal') to @extends('errors.minimal') in the view. So change the colon to dot. Hopefully it will help you!
> 
> It works for me, Laravel 7

1) Change to `@extends('errors.minimal')`
2) Copy file `vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/views/minimal.blade.php` to `resources/views/errors/minimal.blade.php`
3) 404 error page is displayed correctly

**Comment by ghbob** [comment]
> Hey Guys, I had the same issue today, what was solved by changing @extends('errors:minimal') to @extends('errors.minimal') in the view. So change the colon to dot. Hopefully it will help you!

Thanks, this still (Laravel 10) helps.

@driesvints any chance you could have another look / re-open this issue?
What's the reason behind using `errors::minimal` instead of `errors.minimal`?
Thank you!

**Comment by Sasarika** [comment]
> Hey Guys, I had the same issue today, what was solved by changing @extends('errors:minimal') to @extends('errors.minimal') in the view. So change the colon to dot. Hopefully it will help you!

Using laravel 11 and this method worked, thanks !

**Comment by whendryo-wytech** [comment]
> Hey Guys, I had the same issue today, what was solved by changing [@extends](https://github.com/extends)('errors:minimal') to [@extends](https://github.com/extends)('errors.minimal') in the view. So change the colon to dot. Hopefully it will help you!

I'm using Laravel 12 and this method worked! Thank you very much!

**Comment by donakhseputa** [comment]
If you have just publish error views by `php artisan vendor:publish --tag=laravel-errors`

in `app/Providers/AppServiceProvider.php`, add line into `boot()`

```
    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        $this->loadViewsFrom(resource_path('views/errors'), 'errors'); // <-- add this
    }
```

just another solution.
