### ISSUE TITLE
Changelog usage

### ISSUE THREAD

**Issue by fridzema** [laravel/framework#30225]
Hello, 

Personally i am always very confused with the changelog of laravel/framework. 
For 9/10 packages i check the release page where is a list of changes. I there is a new version there is for a long time a placeholder instead of usable info:
![Screenshot 2019-10-09 at 09 43 32](https://user-images.githubusercontent.com/8180660/66461694-dbbc3d80-ea79-11e9-93ae-08183b6e68a6.png)

Ok most of the time you can find changes is a CHANGELOG.md file where laravel uses CHANGELOG-x.x.md files, why not default CHANGELOG.md?

Then in the changelog file itself it is confusing that it is not updated with the release, is Unreleased the changelog for 6.2?
![Screenshot 2019-10-09 at 09 43 45](https://user-images.githubusercontent.com/8180660/66461925-51280e00-ea7a-11e9-924b-ada79df69912.png)

I created a PR for this before https://github.com/laravel/framework/pull/30087

Is there any standard for this or can we create some consistency for this please?

**Comment by driesvints** [comment]
@TBlindaruk manages the changelog. It could be a few hours or a day or two until she gets to it before it's updated but it'll be updated eventually, don't worry.
