### ISSUE TITLE
Laravel's container is unable to resolve ellipsis symbol (failing with an Unresolvable primitive)

### ISSUE THREAD

**Issue by 6562680** [laravel/framework#30244]
- Laravel Version: 6.0.4
- PHP Version: 7.3
- Database Driver & Version: Mysql 8

### Description:
Laravel fails where we try to bind class where we have ...$arguments in constructor
Got the error when trying to make library with clever argument resolving (put via string, arrays or dicts)

### Steps To Reproduce:
```
interface DependInterface {}
interface MyObjectInterface {}

Class Depend implements DependInterface {}
Class MyObject implements MyObjectInterface { public function __construct(DependInterface $depend, ...$arguments) {} }
```

// provide
```
$app->bind(DependInterface::class, Depend::class);
$app->bind(MyObjectInterface::class, MyObject::class);

$app->make(MyObjectInterface::class); // Unresolvable primitive exception
```

I think in Container forgotten block with checking $reflectionArgument->allowsNull() exactly for ellipsis-like arguments.

**Comment by driesvints** [comment]
Hey @6562680. This is expected. Because `...$arguments` isn't a class based argument the container can't resolve it. Variadic parameters can't have a default either so this construct denotes that at least one argument is needed. 

What you might be looking for is binding primitives: https://laravel.com/docs/6.x/container#binding-basics

```php
        $this->app->when(MyObject::class)
            ->needs('$arguments')
            ->give(function () {
                return [];
            });
````

**Comment by 6562680** [comment]
Of course if you set type you shoul pass the value, but even then you can pass null or skip arguments to get empty array there. If you want argument you should declare (arg, ...args) there. Reflection class returns allowNull true, because its possible, man!
