### ISSUE TITLE
$casts is not respected on created models

### ISSUE THREAD

**Issue by stancl** [laravel/framework#30263]
- Laravel Version: 6.2.0
- PHP Version: 7.2
- Database Driver & Version: sqlite

### Description:

```php
/** @test */
public function product_has_a_float_price()
{
    $product = $this->factory->create(['price' => 100]);

    $this->assertSame(100.0, $product->price);
}
```

This test fails:
```
Failed asserting that 100 is identical to 100.0.
```

Despite the fact that `$price` is cast to float:
```php
protected $casts = [
    'price' => 'float',
    'vat_rate' => 'float',
    'enabled' => 'boolean',
];
```

**Comment by xuanquynh** [comment]
I can't reproduce your issue. Everything works properly for me.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by stancl** [comment]
How is this not reproducible?
