### ISSUE TITLE
Error with xdebug 

### ISSUE THREAD

**Issue by JamesKid** [laravel/framework#30262]
- Laravel Version: 5.5.0
- PHP Version: 7.3.10
- Database Driver & Version: mysql 
-Xdebug version 2.8.0alpha
-comopser  dingo/api version   2.2.3
### Description: Xdebug remote run error 
Exception has occurred.
Illuminate\Contracts\Container\BindingResolutionException: Target [League\Fractal\ScopeFactoryInterface] is not instantiable while building [Dingo\Api\Transformer\Adapter\Fractal, League\Fractal\Manager].
"Target [League\Fractal\ScopeFactoryInterface] is not instantiable while building [Dingo\Api\Transformer\Adapter\Fractal, League\Fractal\Manager]."

### Steps To Reproduce:

![图片](https://user-images.githubusercontent.com/6158899/66717729-e88cb880-ee0e-11e9-99b1-ecba68cfa459.png)

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by JamesKid** [comment]
ok, many thanks, i try to upgrade a new version.

**Comment by JamesKid** [comment]
I upgrade to the version 5.8.* but the proble is still .

**Comment by JamesKid** [comment]
I got it , it need to add this register,   in  app/Providers/appServiceProvider.php
public function register()
    {
        $this->app->bind("League\\Fractal\\ScopeFactoryInterface", "\\League\\Fractal\\ScopeFactory");
    }
