### ISSUE TITLE
[6.0] Str::ascii() test with locale broken

### ISSUE THREAD

**Issue by kylekatarnls** [laravel/framework#30267]
- Laravel Version: master (5558a114cec2ebb1050ac79ba71f3eb87789ad37)
- PHP Version: 7.3.5

### Description:
Same codebase that had passing unit tests now has 1 failure.
A dependency update probably broke this test:
```
1) Illuminate\Tests\Support\SupportStrTest::testStringAsciiWithSpecificLocale
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'h H sht Sht a A ia yo'
+'h H sht Sht a A iya yo'
/tmp/multi-tester-828109/tests/Support/SupportStrTest.php:45
```

### Steps To Reproduce:
Clone laravel/framework repo
run `composer update`
run unit tests

**Comment by driesvints** [comment]
Related to https://github.com/laravel/framework/pull/29947 ?

**Comment by driesvints** [comment]
Hmm, that was passing when it got merged.

@GrahamCampbell can you maybe pitch in?

**Comment by kylekatarnls** [comment]
That what I said in description, maybe a voku/portable-ascii change.

**Comment by kylekatarnls** [comment]
Test pass with voku/portable-ascii 1.2.3. So it probably just needs to upgrade the test accordingly as the `iya` is more likely a mistake fix.

**Comment by driesvints** [comment]
Yeah, I believe so as well. Feel free to pr or I'll do it in a bit.

**Comment by kylekatarnls** [comment]
OK. I will check the changes of voku/portable-ascii to be sure it's on purpose and will PR.

**Comment by kylekatarnls** [comment]
Change targeted: https://github.com/voku/portable-ascii/commit/62f9521b77693bb7a7be8fe855e86fa347e75f70#diff-07a0c79489ea27ae5e059a433ba83a34

**Comment by kylekatarnls** [comment]
Done: #30269 6.x branch seems not affected due to more lax test.

**Comment by driesvints** [comment]
Thanks man!
