### ISSUE TITLE
$this->foo()->attach() doesn't update the cached collection

### ISSUE THREAD

**Issue by stancl** [laravel/framework#30261]
- Laravel Version: 6.2.0
- PHP Version: 7.2
- Database Driver & Version: sqlite

### Description:

`$this->statuses` is empty after `$this->statuses()->attach()` has been called, despite the fact that `$this->statuses()->get()` is *not* empty:

```php
public function setStatus($status)
{
    $status = Status::findOrFail($status);

    $this->statuses()->attach($status, ['message' => $status->default_message]);

    dd($this->statuses, $this->statuses()->get()); // empty collection vs collection w/ $status
}
```

**Comment by staudenmeir** [comment]
You must be loading the `statuses` relationship somewhere before you call `setStatus()`. `attach()` doesn't update loaded relationships. You can reload it with `$this->load('statuses');`.

**Comment by stancl** [comment]
I'll check that. I'd expect the property to update automatically, though I see that it can be unwanted for some people and could mean unnecessary queries.

So, not sure if this is expected behavior.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
