### ISSUE TITLE
v6.2.0 changelog missing

### ISSUE THREAD

**Issue by judahnator** [laravel/framework#30270]
The changelog seems to be missing, in both the [tagged release notes](https://github.com/laravel/framework/releases/tag/v6.2.0) and the [changelog file](https://github.com/laravel/framework/blob/v6.2.0/CHANGELOG-6.x.md).

I would love to update, but want to be more sure of what exactly is updating before jumping in.

This coming soon?

**Comment by driesvints** [comment]
I'll update this later today.
