### ISSUE TITLE
Old() method modification

### ISSUE THREAD

**Issue by naveedali8086** [laravel/framework#30276]
- Laravel Version: 5.7.*
- PHP Version: 7.2.10

### Steps To Reproduce:

Two forms (for example: login and register form), submitting to two different routes, are present on the same page.  

both forms have just one field named 'email'  

laravel has a great way to find and show errors of corresponding fields of a form (i.e. by using a key in "withErrors($validator, 'key')" method )  

But the old() method shows the value of field_1 of form_1 into the field_2 of form_2 and vice versa (reason: both the fields have same name)  

can the old() be modified in such a way that it also uses the 'key' that was used with "withErrors($validator, 'key')" method so that the old value of the corresponding field can be show in corresponding form.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
