### ISSUE TITLE
Illuminate\Database\Eloquent\Collection::map() converts to base collection only if not empty

### ISSUE THREAD

**Issue by powelski** [laravel/framework#30271]
- Laravel Version: 6.2.0
- PHP Version: 7.3.7

### Description:
`Illuminate\Database\Eloquent\Collection::map()` method returns either Collection or Eloquent Collection, depending on the result set being empty or not. Seems like not a big deal at first glance, but there are certain scenarios where Eloquent Collection behaves differently.

### Steps To Reproduce:
Add at least one `User` to your database and do:

```php
dd(
    get_class(User::whereRaw('1 = 1')->get()->map(function () {})),
    get_class(User::whereRaw('1 = 0')->get()->map(function () {}))
);
```

You should get:
```php
"Illuminate\Support\Collection"
"Illuminate\Database\Eloquent\Collection"
```

**Comment by driesvints** [comment]
I can indeed reproduce this but I'm not sure if this is a bug or not. It seems okay to me since an empty collection doesn't contains any models so if doesn't needs to be an Eloquent collection?

**Comment by devcircus** [comment]
Definitely seems to me that the Eloquent Collection is a specialized collection of Eloquent models. It comes with methods specific for collections of Eloquent models. Without models, it's just an empty base collection.

**Comment by driesvints** [comment]
Yeah, @devcircus I agree. I think this is expected behavior. @powelski can you explain why you need it to be an Eloquent one?

**Comment by powelski** [comment]
Guys, the issue is that the empty mapped Eloquent Collection is still the Eloquent Collection, not the other way around.

I had some hardcore collection modification, with unions and only(). I encountered that behavior and one of the differences between Eloquent Collection and Collection is how only() behaves. It preserves keys in the Collection, but reindexes the Eloquent Collection (which by definition shouldn't be associative I suppose).

I spent a good 30 minutes to find out the bug in my code, I expected map() to always return Collection and never Eloquent Collection. My case aside, it's still not optimal pattern to return different type according to the input of the same class.

**Comment by devcircus** [comment]
🤷🏻‍♂️I don't agree but I can't imagine a scenario where I'd need to know that an empty collection would be composed of Eloquent models if it wasn't empty, so not really opposed to a change.  Maybe drop this in the ideas repo or try a pull request. Either way, i see it as a desired change in behavior, not a bug.

**Comment by driesvints** [comment]
Yeah, feel free to open up an issue in the ideas repo if you'd like to change this behavior.

**Comment by powelski** [comment]
@devcircus please read the issue once again, carefully. I said twice that map() returns an Eloquent Collection in case of empty Eloquent Collection, *which is a bug*. It should always return basic Collection, no matter if it was empty or not.

**Comment by devcircus** [comment]
Ahh yes I read the issue incorrectly, however, like I said, either way, i believe it's a change in behavior that's just a matter of preference. Maybe it should be changed but it's best to feel the pulse of the community that's likely been using it this way for years. The best way to do that would be filing an issue in the ideas repo, then maybe making a PR and seeing what Taylor has to say. 

Honestly, I would expect the same thing. I can't envision a scenario in my apps where it would matter, but I see your point.

**Comment by powelski** [comment]
It matters in some specific cases, like mine above. There are a few nuances where Eloquent Collection is different. It would be fine if Eloquent Collection was just a superset of Collection, but it’s not the case. Hence, that’s an antipattern - returning class A instance if input value is something and returning class B instance if value is something else, even though both Input values were of the same type. In my humble opinion it’s a bug, not preference. There is mo ideology behind it, just overseen behavior.

**Comment by powelski** [comment]
> Yeah, feel free to open up an issue in the ideas repo if you'd like to change this behavior.

@driesvints Can we please reopen this issue? Please re-read.

**Comment by driesvints** [comment]
@powelski I still feel that this isn't a bug sorry. But feel free to either open an issue on the ideas repo or send in a PR if you feel like something should be changed. Might be best to send this to the master branch as it'll be a change in behavior.
