### ISSUE TITLE
Imports order

### ISSUE THREAD

**Issue by sebastiansulinski** [laravel/framework#30275]
- Laravel Version: 6.2.0
- PHP Version: 7.3.4
- Database Driver & Version: N/A

### Description:
I might be missing something, but it seems that the stubs for all artisan generated classes now import classes in the string length descending order - is that intentional?

### Steps To Reproduce:
```bash
php artisan make:migration create_test_table
```

resulting file:

```php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateTestTable extends Migration
{
   //...
}
```

**Comment by netpok** [comment]
It imports them in alphabetical order, one step closer to psr-12, many more to go.

https://github.com/laravel/framework/pull/29933

**Comment by sebastiansulinski** [comment]
I see - hmm, doesn't look as neat as it did before.
