### ISSUE TITLE
[6.x] Router generates invalid routes with extra parameter

### ISSUE THREAD

**Issue by netpok** [laravel/framework#30272]
- Laravel Version: 6.2.0
- PHP Version: 7.3.10

### Description:
Passing extra parameters to routes will make router ignore the required/optional check and generate an invalid url.

### Steps To Reproduce:
Register a route:
```php
Route::get('welcome/{name}', function($name){
    return 'Welcome ' . $name;
}
```

Generate an url for it:
```php
$url = route('name', ['token' => 'token-from-elsewhere']);
```

Result: `https://foo.com/welcome?token=token-from-elsewhere`

**Comment by driesvints** [comment]
Heya, as we said on the PR, we consider this expected behavior.

**Comment by netpok** [comment]
@driesvints 
Why is this the expected behavior, it is called [**Required parameter**](https://laravel.com/docs/6.x/routing#required-parameters), if it is not required then one should use an [**Optional parameter**](https://laravel.com/docs/6.x/routing#parameters-optional-parameters)

I did not want to continue the conversation on the pull request. I'm happy to move this to the ideas repo for further discussion with others.

**Comment by driesvints** [comment]
@netpok yes feel free to do that.
