### ISSUE TITLE
Collection query issue

### ISSUE THREAD

**Issue by dwaters2018** [laravel/framework#30286]
I have recently gone through the process of upgrading my environment from laravel 5.1 to 5.8.
After making all the changes required everything is working with one exception.
I have a collection which also contains an eager loaded relationship and i then in a blade view run a query on that collection.

my old code use to do this:
$this->holidays->where('attributes.date', $date->format('Y-m-d'))->first()
and worked with no problems.
However it seems that changes in laravel 5.5 changed this behaviour. to make the code work again i had to change it to this:

$this->holidays->where('date', $date)->first()
This works but is significantly slower. My page used to load in around 10 seconds it now takes over a minute. 

I have run several tests to confirm it is this collection query that is the bottleneck.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by dwaters2018** [comment]
Hi,

It seems like a bug in the library to me since it only became an issue after an update of the framework. And the behaviour of the collection has changed.

However i will follow your suggestion and try asking in one of the forums.

**Comment by mfn** [comment]
> $this->holidays->where('date', $date)->first()

This loads _all_ `holidays` into memory and then checks them => I wager it would be faster to query it on the relation and not on the loaded collection, did you try that?

I.e. `$this->holidays()->where('date', $date)->first()`?

**Comment by dwaters2018** [comment]
I did try that and due to the number of queries being generated there was no speed benefit.
The query is in a loop where date is incremented through days of the month and an outer loop of multiple users to populate a grid view. So several hundred queries are generated.
My point really though is that this only became an issue after a change in the laravel framework.
