### ISSUE TITLE
when i use pagination with alias Columns and having constraint i get an error 

### ISSUE THREAD

**Issue by ROOKIE20570** [laravel/framework#30282]
- Laravel Version: 5.8
- PHP Version: 7.3
- Database Driver & Version:mysql

### Description:
when i use pagination with alias Columns and having constraint i get an error

### Steps To Reproduce:

Schema::create('costs', function ($table) {
            $table->increments('id');
            $table->unsignedInteger('user_id')->nullable();
            $table->integer('cost');
            $table->timestamps();
        });

$query = Cost::selectSub('sum(cost)', 'total')->having('total', '>', 3)->groupBy('user_id')->paginate();

![image](https://user-images.githubusercontent.com/30709033/66827888-47bf0a00-ef82-11e9-959f-c43f169153ef.png)

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by ROOKIE20570** [comment]
> Hey there,
> 
> Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.
> 
> Thanks!

I can reproduce this bug in version 6.2.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by ROOKIE20570** [comment]
@driesvints 
[https://stackoverflow.com/questions/33982661/laravel-having-column-not-found](url),
[https://stackoverflow.com/questions/56582706/laravel-column-not-found-1054-unknown-column-in-laravel-query](url)
This link is a discussion about this issue, everyone used an indirect method to deal with this problem.
