### ISSUE TITLE
composer require laravel/framework "5.7.*" installs 5.7.15

### ISSUE THREAD

**Issue by OddBlueDog** [laravel/framework#30284]
- Laravel Version: 5.7.*
- PHP Version: 7.2.19
- Database Driver & Version:

### Description:
On a new project running 'composer require laravel/framework "5.7.*"' installs laravel 5.7.15 instead of the latest version which is currently 5.7.28

### Steps To Reproduce:
- Create new project
- Run `composer require laravel/framework "5.7.*"`

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
