### ISSUE TITLE
The page expired due to inactivity after login

### ISSUE THREAD

**Issue by benjielim** [laravel/framework#30281]
- Laravel Version: 5.6
- PHP Version: 7.2
- Database Driver & Version:

### Description:
I load an laravel project on ionic using iframe (IOS)
After I login error shows: "The page expired due to inactivity"

(Android is working fine.)

What is fix for this?

### Steps To Reproduce:

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
