### ISSUE TITLE
SVG is not supported by most email clients

### ISSUE THREAD

**Issue by fitztrev** [laravel/framework#30290]
- Laravel Version: 7.0-dev

### Description:

The email templates just changed via 74252f30191728d650ea9515fab22dbf0863b042. Inline SVGs have [very little email client support](https://css-tricks.com/a-guide-on-svg-support-in-email/#svg-email-inline).

https://github.com/laravel/framework/blob/9e8cd8c30bf518d80475f13bb3d22f3506f044e4/src/Illuminate/Mail/resources/views/html/header.blade.php#L5-L7

### Steps To Reproduce:

Send yourself an HTML email containing the `<svg>` image. Then open it in Gmail (web or mobile). The image (even though it's present in the HTML) is not rendered.

**Comment by driesvints** [comment]
We'll need to check for a good alternative then.

**Comment by dwightwatson** [comment]
Does it need to be embedded then - would an `img` tag that points to the SVG do the trick?

**Comment by driesvints** [comment]
We were thinking a data: string

**Comment by fitztrev** [comment]
Unfortunately `<img src="data:image/...` has limited support too. I tested it on Gmail (web + mobile) and Outlook (Mac + mobile) and none worked.

Here's a gist of [the html I used](https://gist.github.com/fitztrev/6c406669055cd0d51296d28972ad669c).

**Comment by fitztrev** [comment]
@narwy The link I posted says that also has limited support.

**Comment by driesvints** [comment]
Fixed: https://github.com/laravel/framework/commit/5c7df0d19d3a77bc235b6fe81f60d457109b2337
