### ISSUE TITLE
Custom guard issue in ver 6

### ISSUE THREAD

**Issue by saeid78** [laravel/framework#30294]
- Laravel Version: 6.0.3
- PHP Version: 7.2.13
- Database Driver & Version: MariaDB, 10.3.11

### Description:
Hi,
I have decided to create a custom guard in my app and when trying to login, it throws BadMethodCallException: Method Illuminate\Auth\RequestGuard::attempt does not exist
I followed what the doc says here: https://laravel.com/docs/6.x/authentication

### Steps To Reproduce:
1-install a new Laravel 6,
2- Create a custom guard "api" to store data in different table.
3-Attempt to login user , it throws above error.

**Comment by ankurk91** [comment]
https://github.com/mtvbrianking/multi-auth

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by saeid78** [comment]
@driesvints I did that Sir!
had to hack it finally! Auth Facade dose not expect us to use it for a custom api guard! . and that's why it throws error on  attempt method.
