### ISSUE TITLE
Laravel 6.3 Action Facade\Ignition\Http\Controllers\ShareReportController not defined

### ISSUE THREAD

**Issue by abbeyahya** [laravel/framework#30298]
Hi,
I am developing a website using Laravel (v6.3.0), I downloaded a fresh version using composer.
When I run `php artisan route:cache` I get

>  LogicException  : Unable to prepare route ... for serialization. Uses Closure.

After some searches I found [a solution](https://stackoverflow.com/a/45266424/801394):
I removed the closures from api.xml
```
/*
Route::middleware('auth:api')->get('/user', function (Request $request) {
    return $request->user();
});
*/
```
and web.xml
```
/*
Route::get('/', function () {
    return view('welcome');
});*/
Route::get('/', 'PageController@GetHome');
```

Now the error disappeared but I get weird behavior. 
I am running in debug mode, but when there is an error in the code(like undefined method) Laravel shows 

> Action Facade\Ignition\Http\Controllers\ShareReportController not defined

while trying to view the page instead of the actual error.

When I un-comment the closure (from web.xml or api.xml) Laravel shows the error correctly but it shows also

> Unable to prepare route ... for serialization. Uses Closure

 if I try `php artisan route:cache` 

This happens only with the current version (Laravel v6.3.0) previousely I have worked with Laravel 5.6 and Laravel 6.0.3 and I used to solve the closures error the same way (by removing them) and this ShareReportController not defined never appeared.

Is this a bug? Should I open an issue for it?

See the following screen for the full stack
![ShareReportController not defined](https://user-images.githubusercontent.com/55587592/66909844-fd2ea380-effc-11e9-956d-350f4b84b611.JPG)

**Comment by pxgamer** [comment]
It looks like there is an issue open on the relevant repository (https://github.com/facade/ignition/issues/202).

**Comment by devcircus** [comment]
Also, the serialization error when trying to cache routes is expected. Closures can't be serialized. It's mentioned in the docs.

**Comment by driesvints** [comment]
Please see the linked issue above.

**Comment by ryryan** [comment]
Still throws this error after downgrading to 1.11.1 as suggested and clearing cache and routes. (fresh install of Laravel)

**Comment by dsaha1656** [comment]
still no response on this issue. i have found this issue while working with phpunit and tried to get 

` $user = factory(User::class)->create(['is_clinician' => 0]);
        // $this->be($user);
        $response = $this->actingAs($user)->get('/');`

**Comment by slava-vishnyakov** [comment]
As a workaround:

```
class ....Test extends TestCase
{
    use InteractsWithExceptionHandling;

    ...

    $user = factory(User::class)->create(['is_clinician' => 0]);

    $this->withoutExceptionHandling(); 

    $response = $this->actingAs($user)->get('/');
```

It should show the actual error in the code.

**Comment by notflip** [comment]
`php artisan cache:clear && php artisan route:clear` did it for me.

**Comment by tah33** [comment]
thank you @notflip , it worked for me

**Comment by Azmeer-crescent** [comment]
delete all the php files inside this folder and run again:
`\bootstrap\cache`

**Comment by reggietheroman** [comment]
@Azmeer-crescent thanks. deleting the files inside `\bootstrap\cache` worked for me.

**Comment by Zgarc** [comment]
This happened to me when I was moving files into new directories to better organize my code. Anyways, once I did that i got this error. The fix was a combination of notflip's recommendation as well as editing your controllers and views to properly reflect the changed files' paths.
For example, let's say you have an items page (items available in a store).... if you move that items directory into a new empty store directory, you would want to change the ItemsController. So in ItemsController, for the index method, you would have
```
return view('items.index', compact('items'));
```
You would need to change it to:
```
return view('store/items.index', compact('items'));
```
And, inside your view, if you have any @include statements, you would need to change those as well.
So,
```
@include(items.form)
```
would now be
```
@include(store/items.form)
```
After these changes you need to run notflips' recommendation:
```
php artisan cache:clear && php artisan route:clear
```

Hope this helps!

**Comment by rainbowhat** [comment]
> `php artisan cache:clear && php artisan route:clear` did it for me.

Seems like this is an issue that started from laravel 7 onwards, the previous didn't had this issue consistantly.

**Comment by MrEduar** [comment]
> > `php artisan cache:clear && php artisan route:clear` did it for me.
> 
> Seems like this is an issue that started from laravel 7 onwards, the previous didn't had this issue consistantly.

This is correct, actually this error has come out very often, and it is not only the cache, but for example with a simple variable that is not defined as currently has happened to me.

**Comment by netfan1993427** [comment]
Umm, I got same error today, and resolved by set correct permission to the project root, and storage dir as well.
On centos:
```shell
sudo chown apache:apache project_root
```
On ubuntu:
```shell
sudo chown www-data:www-data project_root
```
Hope it helps someone. ;)

**Comment by JustAMurph** [comment]
I ran the above ` php artisan cache:clear && php artisan route:clear` but that did not work for me. 

Adding sudo to it ` sudo php artisan cache:clear && php artisan route:clear` fixed the issue for me. 

Running Laravel `6.17.1`.

**Comment by thibodelanghe** [comment]
> `php artisan cache:clear && php artisan route:clear` did it for me.

Doing `php artisan migrate` can help

**Comment by Affaffarooq01** [comment]
nai chal raha bhai koi acha sa solution bato
