### ISSUE TITLE
Directory traversal with download function

### ISSUE THREAD

**Issue by blorange2** [laravel/framework#30304]
- Laravel Version: 5.6.*
- PHP Version: PHP/7.3.10
- Database Driver & Version: MySQL 5.7

### Description:

Having installed a fresh installation of Laravel 5.6 I noticed what could be a vulnerability whilst testing something.

One method within the `ResponseFactory` is `download` that allows you to download a file, given a path.

I made a very simple controller method that read as follows:

`return response()->download('../composer.json');`

This call downloaded my `composer.json` file to my local machine, is this a vulnerability in Laravel or an issue with the way my server has been set up? In this instance I am just using XAMPP.

### Steps To Reproduce:

1. Create a function that returns a download response
2. Provide a path containing ./ or ../
3. Use as necessary to break out of the folder containing the application

**Comment by pxgamer** [comment]
I'm not really sure if this would be an issue with Laravel. The `download()` method is designed to return the contents of any file that is specified.

I guess you could lock this down with permissions, etc. and make sure you sanitise any input paths that are provided by the user.

**Comment by blorange2** [comment]
This may be out of scope, but how would I go about implementing such protections?

**Comment by devcircus** [comment]
Same is true for even standard library calls like file_get_contents. You could dump your .env file. Never allow user input directly to these functions. Either whitelist, regex check, or some other custom validation.

**Comment by blorange2** [comment]
So, essentially because I'm allowing a user to directly input a path I'm basically opening myself up to attack?

A package I'm using has a download function but one route can be manipulated like so:

`laravel-filemanager/download?working_dir=%2Fpentest&type=Files&file=../../../../../../../../../../../../../../../../etc/hosts`

So, I'd have to check for the usage of `../`?

**Comment by ScopeyNZ** [comment]
You can `realpath` the directory (eg. `/../../../../../../etc/hosts`) and assert that it's within a given directory (or directories).

**Comment by nexxai** [comment]
> So, essentially because I'm allowing a user to directly input a path I'm basically opening myself up to attack?

Yes.

**Comment by blorange2** [comment]
How could I use realpath with the base path? I ask because the Laravel function `base_path` essentially returns the realpath of the application, however I tried something like this:

```

        $query_string = $validated_data['q'];

        $laravel_root = base_path();

        $user_real_path = realpath($query_string);

        if ($user_real_path === false || strpos($user_real_path, $laravel_root) !== 0) {
            dd('traversal');
        } else {
            dd('!traversal');
        }

        return response()->download($validated_data['q']);

```

Essentially I could still do `../.env` and this would allow me to download the `.env` because it's within the accepted path.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by netpok** [comment]
@blorange2 when you are serving files to the user, you should use the [Storage::download](https://laravel.com/docs/6.x/filesystem#downloading-files) method, the storage implementation will not allow accessing files outside the storage's root path.
