### ISSUE TITLE
Model 'object' casting

### ISSUE THREAD

**Issue by Zlob** [laravel/framework#30302]
- Laravel Version: 5.8.35
- PHP Version: 7.3.1
- Database Driver & Version: doesn't matter

### Description:
Hi!
I've noticed a strange behavior in the Model 'object' casting. If you have a model with field declared as 'object' and you'll pass an empty array into it you will get an '[]' instead of '{}'.
I can create a MR with fix via an additional param in `asJson` method of `hasAttributes` trait. Should I?

### Steps To Reproduce:
```php
class ExampleModel extends Model
{
    protected $casts = [
        'field' => 'object',
    ];
}

$model = new ExampleModel();
$model->field = [];
$model->toJson() // return {'field': []} instead of {'field': {}}
```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by Zlob** [comment]
Hey!
Version 6 have the same issue, so I`ve created a PR to fix it https://github.com/laravel/framework/pull/30341

**Comment by Zlob** [comment]
Unfortunately,  my fix doesn't work. There are a lot of transformations between array, stdCalss, '[]' and '{}'.
Maybe, i don't enough understand meaning of 'object' casting. I thought, that tranfsormation should be like this:
           | JSON | Model | DB
object | '{}'       | []         |'{}'
array  | '[]'       | []         |'[]'

But, if by object we mean stdObject, it should be
           | JSON | Model      | DB
object | '{}'       | stdObject | |'{}'
array  | '[]'       | []               |'[]'

Am I right?

**Comment by Zlob** [comment]
I've created new [PR](https://github.com/laravel/framework/pull/30352) for this issue
