### ISSUE TITLE
 one-to-one relationship accepts (->first()) and returns the first record in the table however it's related to the model used by or not

### ISSUE THREAD

**Issue by mohamed-abdelrhman** [laravel/framework#30319]
- Laravel Version: 6.0
- PHP Version:7.2
- Database Driver & Version:MYSQL

### Description:
As i know has if i used one-to-one relationship it will return one record using the foreign key but the relation accept (->first()) and returns the first record in the table  

### My Models
**User Model**
  protected $guarded = ['id'];
  public function activation()
    {
        return $this->hasOne(Activation::class, 'user_id', 'id');
    }

**Activation Model**
protected $fillable=['token']

###Steps To Reproduce:
in controller

1. retrun auth()->user->activation()    //returns the activation of the user as normal
2.return auth()->user->activation->first()    ///// returns the first record of the activation table however it's for this user or not
3. return auth()->user->activation()->first()   //returns the activation of the user as normal

**Comment by 36864** [comment]
`$user->activation` returns a single instance of the `Activation` model. Calling `->first()` on a model instance will forward the call to the underlying query builder, which is the same as calling `Model::first()`.

For your particular use case, you should not call `auth()->user->activation->first()`. Instead, call either `auth()->user->activation()->first()` or `auth()->user->activation` to get the user's activation.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by mohamed-abdelrhman** [comment]
I knew How To Work Around this Issue as i said above and how @36864 suggested,
but is this a normal  behaviour ?
to return first record of the table activations which not related to the user when using
`auth()->user->activation->first()`

**Comment by devcircus** [comment]
Yes, there are many cases like this with Eloquent. If it's a one-to-one, you already have a model so you shouldn't call "first". Doing so is like calling (new Activation)->first();
