### ISSUE TITLE
Laravel Storage Facade

### ISSUE THREAD

**Issue by mortezanasiri** [laravel/framework#30318]
- Laravel Version: 6.2.0
- PHP Version: 7.2.19

### Description:
This is my code:
`$contents = Storage::get(storage_path('logs/laravel-2019-10-14.log'));`

Laravel return this error: Illuminate\Contracts\Filesystem\FileNotFoundException

But file already exists!

I want read file contents.

**Comment by netpok** [comment]
This cannot be done this way, the underlying flysystem drops the first / so this is handled as a relative path. If this would be handled as an absolute path it would throw a LogicException, that it's outside of the storage root (which is `storage_path('app')`).

Storage is for handling files uploaded by the users or connected to it, it allows replacing the driver if needed. Also it would be a security hole to allow accessing files outside the root.

In these cases you're better of with:
```php
$contents = file_get_contents(storage_path('logs/laravel-2019-10-14.log'));
```

**Comment by mortezanasiri** [comment]
> This cannot be done this way, the underlying flysystem drops the first / so this is handled as a relative path. If this would be handled as an absolute path it would throw a LogicException, that it's outside of the storage root (which is `storage_path('app')`).
> 
> Storage is for handling files uploaded by the users or connected to it, it allows replacing the driver if needed. Also it would be a security hole to allow accessing files outside the root.
> 
> In these cases you're better of with:
> 
> ```
> $contents = file_get_contents(storage_path('logs/laravel-2019-10-14.log'));
> ```

This works :blush:

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by netpok** [comment]
@mortezanasiri 
You can also use the wrapper provided by Laravel:
```php
$contents = \Illuminate\Filesystem\Filesystem::get(storage_path('logs/laravel-2019-10-14.log'));
```

This is essentially the same as the other but will throw a FileNotFoundException if the file does not exists.
