### ISSUE TITLE
Facing Issues upon subscribing to presence channel from a Vue Single page application

### ISSUE THREAD

**Issue by deep80** [laravel/framework#30325]
I got a vue application inside laravel where i need to implement a real time feature upon successful authentication. it's a stateless authentication.

The authentication works fine, however i am not able to subscribe to a global presence channel using laravel echo. 

I am also passing the auth token inside the echo configuration object like this:

```
auth: {
headers: {
'Authorization': token
}
}
```
Also declared broadcast route which returns the auth user data.

Please advice me on this.

Thanks

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
