### ISSUE TITLE
Faker locale configuration does not work.

### ISSUE THREAD

**Issue by CristianH033** [laravel/framework#30345]
- Laravel Version: 5.8.35
- PHP Version: 7.2.19
- Database Driver & Version: psql (PostgreSQL) 11.5

The locale configuration for faker in `config > app.php` does not work.

### Steps To Reproduce:

- Set the locale to config > app.php
![image](https://user-images.githubusercontent.com/4079493/67146814-4b89af80-f254-11e9-9d2e-59fed371e6d2.png)

- Create a model factory (country)
![image](https://user-images.githubusercontent.com/4079493/67146834-960b2c00-f254-11e9-8d71-4d9691ff5322.png)

- Running the seed 
![image](https://user-images.githubusercontent.com/4079493/67146970-20a05b00-f256-11e9-9d44-020ae3b94d8d.png)

The results are in English:
![image](https://user-images.githubusercontent.com/4079493/67146994-46c5fb00-f256-11e9-81c7-3dbd4f65d2c6.png)

But if I modify the model factory this way:
![image](https://user-images.githubusercontent.com/4079493/67147049-bb993500-f256-11e9-9962-c78de0647743.png)

The results are displayed in the desired language
![image](https://user-images.githubusercontent.com/4079493/67147055-cfdd3200-f256-11e9-96d2-67dfdf6651ec.png)

**Comment by netpok** [comment]
Laravel 5.8 is not supported anymore and it works under Laravel 6. You can run `config('app.faker_locale')` to verify your setting got recognized but you should update.

<sub>Also personally I think all code and database identifier should be in English.</sub>

**Comment by andershagbard** [comment]
It's not available in 5.8. It got reverted. https://github.com/laravel/framework/pull/29250

**Comment by netpok** [comment]
But that's for the tests, the migrations should get the faker instance from here: https://github.com/laravel/framework/blob/5.8/src/Illuminate/Database/DatabaseServiceProvider.php#L78

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by Vercoutere** [comment]
I'm experiencing the same issue on the latest release (6.15.0).
The faker locale doesn't seem to be applied anywhere, no matter what I try.
I tried using my factory on an endpoint, in a test, and in a seeder. The resulting data is always from the en_US provider. Dumping my faker_locale in my factory class confirms it's not a caching issue and the faker_locale is in fact set to something else (nl_BE in my case).

**Comment by jamesfairhurst** [comment]
@Vercoutere this is happening due to the change in https://github.com/laravel/framework/pull/30992 - I can no longer get locale fake data either using the WithFaker trait.

**Comment by sidben** [comment]
I was having trouble with faker not respecting the value of app.php, turns out there was some stuff cached with the old value.

I ran **php artisan config:cache** and it solved the issue.
