### ISSUE TITLE
Passing an array of conditions to the where function in collection giving wrong results

### ISSUE THREAD

**Issue by abd-iubat** [laravel/framework#30344]
- Laravel Version: 6.2
- PHP Version: 7.2.18
- Database Driver & Version: MySQL & 5.7.26

### Description:
**Passing an array of conditions to the where function in collection giving wrong results**

> After getting my collection If I need to use some filter by using where on the collection it's going wrong with an array of conditions in where.

When I am using multiple where conditions in a collection in a normal way like **ex:** where('column', value).

`$data = $articles->where('category_id' , 4)->where('featured', 1);`

 it is giving me the actual results
But Instead of multiple where if I use an array of conditions to where the function is giving **me an empty collection.**

`$data = $articles->where(['category_id' => 4, 'featured' => 1]);`

But the expected result was the same as the first one.

**Comment by devcircus** [comment]
I may be mistaken but I don't think the collection 'where' method works like that.

**Comment by abd-iubat** [comment]
@devcircus 
Thank you for your thinking. 
But in the collection I can use groupBy, multiple were as like eloquent.

> My question is if it is working then why not array of conditions where will not work?

**Comment by devcircus** [comment]
See the code below. When you pass an array, it sets the 'value' parameter to the boolean 'true' and the operator to '=' (which operates the same as '=='). So when you call ```$articles->where(['category_id' => 4, 'featured' => 1]);``` it gets translated into:

```$articles->where(['category_id' => 4, 'featured' => 1], '=', true);```
which searches each article for the key, ['category_id' => 4, 'featured' => 1], which doesn't exist.

So what I was saying is the Collection 'where' method doesn't work like you think it does.

```php
    protected function operatorForWhere($key, $operator = null, $value = null)
    {
        if (func_num_args() === 1) {
            $value = true;

            $operator = '=';
        }

        if (func_num_args() === 2) {
            $value = $operator;

            $operator = '=';
        }

        return function ($item) use ($key, $operator, $value) {
            $retrieved = data_get($item, $key);
            $strings = array_filter([$retrieved, $value], function ($value) {
                return is_string($value) || (is_object($value) && method_exists($value, '__toString'));
            });

            if (count($strings) < 2 && count(array_filter([$retrieved, $value], 'is_object')) == 1) {
                return in_array($operator, ['!=', '<>', '!==']);
            }

            switch ($operator) {
                default:
                case '=':
                case '==':  return $retrieved == $value;
                case '!=':
                case '<>':  return $retrieved != $value;
                case '<':   return $retrieved < $value;
                case '>':   return $retrieved > $value;
                case '<=':  return $retrieved <= $value;
                case '>=':  return $retrieved >= $value;
                case '===': return $retrieved === $value;
                case '!==': return $retrieved !== $value;
            }
        };
    }
```

**Comment by abd-iubat** [comment]
> See the code below. When you pass an array, it sets the 'value' parameter to the boolean 'true' and the operator to '=' (which operates the same as '=='). So when you call `$articles->where(['category_id' => 4, 'featured' => 1]);` it gets translated into:
> 
> `$articles->where(['category_id' => 4, 'featured' => 1], '=', true);`
> which searches each article for the key, ['category_id' => 4, 'featured' => 1], which doesn't exist.
> 
> So what I was saying is the Collection 'where' method doesn't work like you think it does.
> 
> ```
> protected function operatorForWhere($key, $operator = null, $value = null)
> {
>     if (func_num_args() === 1) {
>         $value = true;
> 
>         $operator = '=';
>     }
> 
>     if (func_num_args() === 2) {
>         $value = $operator;
> 
>         $operator = '=';
>     }
> 
>     return function ($item) use ($key, $operator, $value) {
>         $retrieved = data_get($item, $key);
>         $strings = array_filter([$retrieved, $value], function ($value) {
>             return is_string($value) || (is_object($value) && method_exists($value, '__toString'));
>         });
> 
>         if (count($strings) < 2 && count(array_filter([$retrieved, $value], 'is_object')) == 1) {
>             return in_array($operator, ['!=', '<>', '!==']);
>         }
> 
>         switch ($operator) {
>             default:
>             case '=':
>             case '==':  return $retrieved == $value;
>             case '!=':
>             case '<>':  return $retrieved != $value;
>             case '<':   return $retrieved < $value;
>             case '>':   return $retrieved > $value;
>             case '<=':  return $retrieved <= $value;
>             case '>=':  return $retrieved >= $value;
>             case '===': return $retrieved === $value;
>             case '!==': return $retrieved !== $value;
>         }
>     };
> }
> ```

@devcircus 
Here is my database table design where I have data that belongs to category_id = 4 and also featured = 1.

![bug_latest](https://user-images.githubusercontent.com/23525905/67353523-9406dd00-f574-11e9-9a1a-dcf71d01afaa.PNG)

My question is, will it becoming a key like '['category_id' => 4, 'featured' => 1]' as one, or will it searching for every data for both two key category_id and featured?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by robjbrain** [comment]
I just came here to report the same thing. I realise it's not documented or implemented that `where` works in the same was as Eloquent but it's an easy mistake to make and could at least throw an error.

Is there a situation where `$key` being an array is valid? If not then presumably an `InvalidArgumentException` could be thrown?

Alternatively it could loop through the array and replicate the behaviour of the Eloquent Query Builder?

Right now it just sort of fails silently.
