### ISSUE TITLE
Timed out queue workers leak resource

### ISSUE THREAD

**Issue by halaei** [laravel/framework#30351]
- Laravel Version: 6.4.0
- PHP Version: 7.2.24
- Database Driver & Version: 5.6.44

### Description:
When a queue worker is timed out `Worker::kill()` is called. The function sends 9 signal to the current process, which kills the process without letting it to clean the resources. Currently, one resource type I find is leaking in our server is the files created by `file_get_contents("https://...")` inside the server `/tmp` directory. Apparently, if you kill a process while file_get_contents() in progress, the temporary files will never be cleaned from /tmp.
```php
    /**
     * Kill the process.
     *
     * @param  int  $status
     * @return void
     */
    public function kill($status = 0)
    {
        $this->events->dispatch(new Events\WorkerStopping($status));
        if (extension_loaded('posix')) {
            posix_kill(getmypid(), SIGKILL);
        }
        exit($status);
    }
```
### Steps To Reproduce:
1. Run workers with small timeout for jobs that call `file_get_contents` to fetch files from http urls.
2. `ls /tmp/php* -l`
### Bug history and fix
As I remember, this is actually introduced by one of my pull requests. My reason to call posix_kill(9) instead of die is to prevent workers to be stuck inside a __destruct() or functions registered by register_shutdown_function, which in turn may leads to queue or possibly memory overflow.
A solution to alleviate this is to first try to terminate the process normally, e.g. by die command or signal SIGTERM instead of SIGKILL, then register some watchdog timer to send SIGKILL to the process if the termination takes too long. I am not sure if this is even possible to be safely done.
Another fix is to schedule cron commands to regularly clear /tmp files and other resources.

**Comment by halaei** [comment]
Recently I deleted +100GB /tmp files from one of our servers. I am not entirely sure this bug is the reason, but I can't think of any other reason at the moment. I wonder if others see old /tmp/php* files in their servers as well.

**Comment by driesvints** [comment]
Please fill out the issue template properly (correct versions).

**Comment by halaei** [comment]
@driesvints I know the template can help you a lot but it is sometimes irrelevant and confusing for me.
For one thing, I don't know what does database driver has to do with an issue regarding queues.
I find the bug in a version which you may or may not maintain anymore and checked the code in master (laravel 6) and see still the issue is there. The issue probably there since laravel 5.5 or so, and PHP version on our systems has nothing to do with it.
So in order to fill this correctly, I should search what is the latest version of laravel and php and mysql or what version is installed in our system that laravel still supports.

**Comment by halaei** [comment]
I now feel like it is more of a server configuration issue. There should be some scheduling on servers to clean /tmp anyway. So if you think the same way, this can be closed. Maybe I ask for some default configuration regarding that on Laravel forge servers later.

**Comment by driesvints** [comment]
@halaei yeah I agree.
