### ISSUE TITLE
[6.x] Event:list command displays discovered events when event discovery is disabled

### ISSUE THREAD

**Issue by netpok** [laravel/framework#30360]
- Laravel Version: 6.2.0
- PHP Version: 7.3

### Description:
The event:list command shows the discovered events when event discovery is off.

### Steps To Reproduce:
- Create an event named A
- Create a listener named B
- Manually register B to A while leaving event discovery off
- Run `event:list`, it will show that event A is subscribed by listener B (our, valid listener) and B@handle (the autodiscovered, invalid listener)

**Comment by netpok** [comment]
It's the same problem like in #28872. I can send a PR if needed.

**Comment by driesvints** [comment]
Going to close this as the PR was rejected.

**Comment by tricki** [comment]
@driesvints 
Does this mean it is expected behavior that `event:list` always uses automatic event discovery even if it's disabled? This means by default all manually registered listeners will show up twice, once with and once without the `@handle` suffix.
