### ISSUE TITLE
Why `artisan` loads service providers again?

### ISSUE THREAD

**Issue by 6562680** [laravel/framework#30366]
```
class DoctrineServiceProvider
{
  public function register()
  {
    Type::addType('tinyinteger', TinyIntType::class);
    Type::addType('tinyint', TinyIntType::class);
  }
}
```

App works well.

Now, am writing: `artisan config:cache`

I expect "load app.php, clear cache, store vars to cache"

```
Configuration cache cleared!

   Doctrine\DBAL\DBALException  : Type tinyinteger already exists.

  at D:\OSPanel\domains\insta.loc\vendor\doctrine\dbal\lib\Doctrine\DBAL\DBALException.php:257
    253|      * @return \Doctrine\DBAL\DBALException
````

because there is TWO artisan commands, each from both loads ServiceProviders again. But there's the function who should be called once (as Doctrine wants it)

**Comment by 6562680** [comment]
up

**Comment by mfn** [comment]
> there is TWO artisan commands, each from both loads ServiceProviders

I think you try to say the framework is booted twice because to artisans are executed, but from the description it's not clear what the 2nd is. Can you elaborate?

**Comment by 6562680** [comment]
I wrote 1 command (artisan config:cache) and get same result as i wrote 2 different commands, each from both loads Service provider again

**Comment by mfn** [comment]
Please print a trace within your service provider, from there we may see where it's called from the second dump.

Something like `dump(debug_backtrace());` or `echo (new \RuntimeException('')->getTraceAsString(), "\n";` right within `register()` at the top should do it.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by 6562680** [comment]
> Hi there,
> 
> Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:
> 
> * [Laracasts Forums](https://laracasts.com/discuss)
> * [Laravel.io Forums](https://laravel.io/forum)
> * [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
> * [Discord](https://discordapp.com/invite/KxwQuKb)
> * [Larachat](https://larachat.co)
> * [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
> 
> However, this issue will not be locked and everyone is still free to discuss solutions to your problem!
> 
> Thanks.

kidding me, huh? 
its not a bug??? XDD
