### ISSUE TITLE
Sqlite configure the absolute path,goes wrong:Database (absolute path) does not exist

### ISSUE THREAD

**Issue by minororange** [laravel/framework#30379]
- Laravel Version: 6.0.4
- PHP Version: 7.3
- Database Driver & Version:

### Description:
I set the `DATABASE_URL=/www/sqlite/sqlite.php` in the `env` file

but it's changed by `\Illuminate\Support\ConfigurationUrlParser()->getDatabase($url)`

 the code is `return $path ? substr($path, 1) : null;`  

And the DB config got `www/sqlite/sqlite.php`,it's a wrong path

why remove the first string?

**Comment by mathieutu** [comment]
Hi @minororange.
I think you missed the doc about it. The URL env var let you specify an url with all the parameters of your database connection.

What you're looking for is DB_DATABASE: 
https://laravel.com/docs/6.x/database#configuration

```
DB_CONNECTION=sqlite
DB_DATABASE=/absolute/path/to/database.sqlite
```

If you want to use the url shape, here are the way the url are parsed: 
```php
'sqlite relative URL with host' => [
    'sqlite://localhost/foo/database.sqlite',
    [
        'database' => 'foo/database.sqlite',
        'driver' => 'sqlite',
        'host' => 'localhost',
    ],
],
'sqlite absolute URL with host' => [
    'sqlite://localhost//tmp/database.sqlite',
    [
        'database' => '/tmp/database.sqlite',
        'driver' => 'sqlite',
        'host' => 'localhost',
    ],
],
'sqlite relative URL without host' => [
    'sqlite:///foo/database.sqlite',
    [
        'database' => 'foo/database.sqlite',
        'driver' => 'sqlite',
    ],
],
'sqlite absolute URL without host' => [
    'sqlite:////tmp/database.sqlite',
    [
        'database' => '/tmp/database.sqlite',
        'driver' => 'sqlite',
    ],
],
'sqlite memory' => [
    'sqlite:///:memory:',
    [
        'database' => ':memory:',
        'driver' => 'sqlite',
    ],
],
```

Thanks @staudenmeir.
I think you can close it as a question 😉.

BUT it can be interesting to add more doc about it, or at least a link to the test file, which contains all the cases, and can be used as a doc: https://github.com/laravel/framework/blob/6.x/tests/Support/ConfigurationUrlParserTest.php

See you, 
Matt'

**Comment by minororange** [comment]
I sorry about this issue

In my project,the main database is MySQL, `DB_CONNECTION=mysql` in my `.env` file

I want migrate the SQLite data to MySQL，only set up `DATABASE_URL=/sqlite/file/path` in the `.env`

thanks for your reply!
