### ISSUE TITLE
InvalidArgumentException Action Facade\Ignition\Http\Controllers\ShareReportController not defined

### ISSUE THREAD

**Issue by smartraysam** [laravel/framework#30375]
i got this issue when i tried open a page.. i do rally understand what happen . i have clear caches but not resolved

**Comment by rimace** [comment]
I could reproduce something similar.
Create a route `/test` with a controller holding this method:
```
public function test()
{
	$result = 123 / 0;
	
	dd($result);
}
```
When calling the route the following exception is thrown: `Action Facade\Ignition\Http\Controllers\ShareReportController not defined.`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by rimace** [comment]
@driesvints A new Laravel installation still doesn't throw the right exception. Is there a recommended way to create bug reports for laravel/laravel ?
