### ISSUE TITLE
Eloquent Orm Builder Error

### ISSUE THREAD

**Issue by Smokietr** [laravel/framework#30374]
- Laravel Version: 6.x
- PHP Version: 7.1.18
- Database Driver & Version: Mariadb 10.3.14

### Description:
`\App\Products::join('brands', 'brands.id', '=', 'products.product_brand')
                ->selectRaw('brands.id, brands.brand_name, COUNT(products.id) as Counts')
                ->groupBy('products.product_brand')
                ->orderBy('brands.brand_name', 'ASC')
                ->get()`

Eloquent Orm builder gives error.
The error it produces : 

> SQLSTATE[42000]: Syntax error or access violation: 1055 'proje.brands.id' isn't in GROUP BY (SQL: select brands.id, brands.brand_name, COUNT(products.id) as Counts from `products` inner join `brands` on `brands`.`id` = `products`.`product_brand` group by `products`.`product_brand` order by `brands`.`brand_name` asc)

but there is no error when you use the sql direct you produce. What could be the reason?

**Comment by netpok** [comment]
That's an SQL constraint, you need to have all selected non-aggregate columns in the group by.
[See this StackOverflow thread](https://stackoverflow.com/questions/25800411/mysql-isnt-in-group-by)

**Comment by Smokietr** [comment]
![image](https://serving.photos.photobox.com/275023590984ba87eddc825f05a86414f6bee1aaa5a3bccaa2812b6812aed31853e2ebca.jpg)

this query is running.

**Comment by Smokietr** [comment]
i found the answer. https://github.com/laravel/framework/issues/14997#issuecomment-242129087

**Comment by driesvints** [comment]
> Laravel Version: 6.x
> PHP Version: 7.1.18

This isn't possible. Laravel 6 doesn't works on PHP 7.1.

**Comment by Smokietr** [comment]
Really ? It works on me !!!
