### ISSUE TITLE
6.3 ? or 6.2 

### ISSUE THREAD

**Issue by sanhar** [laravel/framework#30371]
- Laravel Version: 6.3.0
- PHP Version: 7.2.22
- Database Driver & Version:

### Description:

- in console command 
php artisan --version 

Laravel Framework 6.3.0

in composer.json 

"laravel/framework": "^6.2",

I guess it is bug .

**Comment by devcircus** [comment]
? That is how composer works. The composer.json simply has a constraint for the version. 
```^6.2``` allows 6.2 up to(but not including) 7.0.

**Comment by Mo7sin** [comment]
`^6.2` means any version after 6.2 will be included if you need version `6.2` specifically, just remove `^` from `composer.json` file and run composer update.
