### ISSUE TITLE
AWS EB EC2 - Nesting level too deep - recursive dependency

### ISSUE THREAD

**Issue by SHELA** [laravel/framework#30387]
- Laravel Version: 5.8.35
- PHP Version: 7.2.19
- Database Driver & Version: mysql(rds) 

### Description:
After we moved to amazon queues start to have issues. we use AWS SQS.
When we run the all the same in old server - all working without any issues
production.ERROR: Nesting level too deep - recursive dependency? {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Nesting level too deep - recursive dependency? at /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/GuardsAttributes.php:176)
[stacktrace]
#0 {main}
"} 

### Steps To Reproduce:
1. SQS queue
2. Dispatch Queue
3. Issue

**Comment by crynobone** [comment]
https://twitter.com/laravelphp/status/1186756672901005317

Not related to this issue?

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
