### ISSUE TITLE
Can't install laravel on a fresh catalina version

### ISSUE THREAD

**Issue by rustx5** [laravel/framework#30386]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Database Driver & Version:

### Description:
Trying to install latest version of laravel 6 without success

### Error Message / Output
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for laravel/installer ^2.2 -> satisfiable by laravel/installer[v2.2.0].
    - laravel/installer v2.2.0 requires ext-zip * -> the requested PHP extension zip is missing from your system.

### Composer Diagnose
Checking composer version: OK
Composer version: 1.9.0
PHP version: 7.3.8
PHP binary path: /usr/bin/php

**Comment by rimace** [comment]
Quote: "the requested PHP extension zip is missing from your system."
Solution: Install the php-zip extension and it will work. 
By the way, there are other ways to request support if you are having trouble setting it up. This is actually only for bugs inside of laravel.

**Comment by colorado-kid** [comment]
@rimace Thank you for your reply, I have no clue how to install this `zip` extension on macOS

**Comment by colorado-kid** [comment]
I did not install any PHP, macOS Catalina comes with the latest PHP version: 7.3.8, for some reasons the `zip` extension is not isntalled (should be) or needs to be activated (don't know how) since when I execute `php --ini` the php.ini file says `(none)`

**Comment by bbashy** [comment]
Ah then; `sudo pecl install zip`. May or may not need sudo. I always install via brew.

**Comment by alec-joy** [comment]
I'd recommend using [Laravel Valet](https://laravel.com/docs/6.x/valet) on MacOS if you aren't familiar with setting up PHP development environments

**Comment by rustx5** [comment]
@alec-joy I can't even install Valet without this extension since it's required. 
But I'll try @bbashy 's solution and see what it returns.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by IstvanLovas** [comment]
I am facing the same issue. Since upgraded to catalina I am unable to install zip extension. Any help would be much appreciated as i have been trying to resolve this for over 9 hours and still cannot find any helpful discussion online.

Thank You

**Comment by alec-joy** [comment]
@IstvanLovas what error message are you getting when trying to install the zip extension?

**Comment by rustx5** [comment]
@IstvanLovas I had to reinstall my MacBook and when I did so I got the most recent version of PHP (7.3.9). To solve your error all what you need to do is a `brew search php` and take really the last one, yesterday I installed the newest 7.4 version php and worked like a charm. Please let me know

**Comment by IstvanLovas** [comment]
I was getting the laravel/installer v3.0.1 requires ext-zip error message than I was simply unable to install the zip extension. Finally I have managed to resolve it by
`brew install php@7.3`
`echo 'export PATH="/usr/local/opt/php@7.3/bin:$PATH"' >> ~/.zshrc`
`echo 'export PATH="/usr/local/opt/php@7.3/sbin:$PATH"' >> ~/.zshrc`
and reloding the cli.

**Comment by rustx5** [comment]
Nope, I will not work with `PHP 7.3`, I'd really recommend to install the `7.4` version and retry.

**Comment by Hujjat** [comment]
I have purchased a MacBook 16 and I can't install laravel via Composer. 

`
 Problem 1
    - laravel/installer v3.0.1 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - laravel/installer v3.0.0 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - Installation request for laravel/installer ^3.0 -> satisfiable by laravel/installer[v3.0.0, v3.0.1].
`

**Comment by Hujjat** [comment]
I finally found the fix
 
Quote from [Stackoverflow](https://stackoverflow.com/questions/58290566/install-ext-zip-for-mac?answertab=active#tab-top)

I had the same problem after updating my Mac to Catalina. Here is what worked for me.

brew update
brew install php@7.3
brew link php@7.3
Then reload your console.

It will install php 7.3.10 with zip module. You can use php -v to check for the version, and php -m for the modules.

The last command might give you some message or instruction to add some files to .zshrc or etch. 

`sudo -s`

Then run those instruction commands.

**Comment by rustx5** [comment]
@Hujjat As I said before install `PHP 7.4` Via Homebrew it will automatically give you the necessary extension, you’ll just need to put it in you .bashrc or .zshrc environment path like the installer will tell you to do.

**Comment by Pushkarjk** [comment]
Laravel Documentation is not helpful for the setup! could not install Laravel/Installer

**Comment by rustx5** [comment]
> Laravel Documentation is not helpful for the setup! could not install Laravel/Installer

Have you installed the latest version of PHP ? What does the error say exactly ?

**Comment by garyfalkland** [comment]
> I was getting the laravel/installer v3.0.1 requires ext-zip error message than I was simply unable to install the zip extension. Finally I have managed to resolve it by
> `brew install php@7.3`
> `echo 'export PATH="/usr/local/opt/php@7.3/bin:$PATH"' >> ~/.zshrc`
> `echo 'export PATH="/usr/local/opt/php@7.3/sbin:$PATH"' >> ~/.zshrc`
> and reloding the cli.

That fixed it for me

**Comment by Pushkarjk** [comment]
> > Laravel Documentation is not helpful for the setup! could not install Laravel/Installer
> 
> @Pushkarjk Have you installed the latest version of PHP ? What does the error say exactly ?
@rustx5 @Hujjat 
Yeah I have the latest php
Composer  global require  Laravel/Installer Did not work 

Problem 1
    - Conclusion: don't install laravel/installer v3.0.1
    - Conclusion: remove symfony/console v3.4.35
    - Installation request for laravel/installer ^3.0 -> satisfiable by laravel/installer[v3.0.0, v3.0.1].
    - Conclusion: don't install symfony/console v3.4.35
    - laravel/installer v3.0.0 requires symfony/console ^4.0|^5.0 -> satisfiable by symfony/console[v4.0.0, v4.0.1, v4.0.10, v4.0.11, v4.0.12, v4.0.13, v4.0.14, v4.0.15, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.1, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.1, v5.0.0, v5.0.1].
    - Can only install one of: symfony/console[v4.0.0, v3.4.35].



Anyways, I directly gave, composer create-project laravel/laravel projectname
This worked perfectly on MacOS catalina 10.15.1!

**Comment by devcircus** [comment]
Those aren't errors that would be covered in the docs. You have to make sure your dependencies are met when installing any package.

**Comment by berkeonurs** [comment]
> Nope, I will not work with `PHP 7.3`, I'd really recommend to install the `7.4` version and retry.

That fixed it for me thanks @rust-rs

**Comment by BaktybekNurbakyt** [comment]
### Laravel 6x
### Mac os terminal

```
brew install php@7.4
composer global require laravel/installer
```

**_WORK_**

**Comment by lperry65** [comment]
All of these answers presume your willing to 1 install homebrew and 2 have php installed twice, is there no solution to using the built in version ?

**Comment by sachithamh** [comment]
> ### Laravel 6x
> ### Mac os terminal
> ```
> brew install php@7.4
> composer global require laravel/installer
> ```
> 
> **_WORK_**

this is work not PHP 7.3, php 7.4 working fine

**Comment by adrianorsouza** [comment]
> All of these answers presume your willing to 1 install homebrew and 2 have php installed twice, is there no solution to using the built in version ?

macOS built in php version does not have all you need for development like XDebug, Zip etc. So the short answer is: Don’t use it, instead use one of the following:

- Compile your own php version with all you need, which is not that complicated if you have XCode installed.
- Use Laravel Homestead / Vagrant
- Install binaries from php-osx.liip.ch 
- Use Homebrew

Unfortunately the built in php version in any macOS is not suitable for the most development cases specially Laravel.

**Comment by oshell** [comment]
for me it just did not work after brew install, because I did not restart the cli.

**Comment by caglardursunn** [comment]
It works! 🔥[Look at this](https://medium.com/@jjdanek/installing-php-extensions-on-mac-after-homebrew-acfddd6be602)

**Comment by ydchauh** [comment]
> Laravel Documentation is not helpful for the setup! could not install Laravel/Installer

Here you go: https://www.yogeshchauhan.com/307/php/how-to-install-php-laravel-in-macos-catalina

I've created step by step guide.

**Comment by vkeysheoran** [comment]
Why everyone want a Composer install ? why can't you **_just clone this github Repo of Laravel_** ?

**Comment by alec-joy** [comment]
> 
> 
> Why everyone want a Composer install ? why can't you **_just clone this github Repo of Laravel_** ?

Because dependency management is important, and if you clone this exact repository you're going to have to do all the work of scaffolding an actual application (as seen in  https://github.com/laravel/laravel) by yourself.

**Comment by jremeh** [comment]
> > > Laravel Documentation is not helpful for the setup! could not install Laravel/Installer
> > 
> > 
> > @Pushkarjk Have you installed the latest version of PHP ? What does the error say exactly ?
> > @rustx5 @Hujjat
> > Yeah I have the latest php
> > Composer  global require  Laravel/Installer Did not work
> 
> These are the errors!
> Problem 1
> - Conclusion: don't install laravel/installer v3.0.1
> - Conclusion: remove symfony/console v3.4.35
> - Installation request for laravel/installer ^3.0 -> satisfiable by laravel/installer[v3.0.0, v3.0.1].
> - Conclusion: don't install symfony/console v3.4.35
> - laravel/installer v3.0.0 requires symfony/console ^4.0|^5.0 -> satisfiable by symfony/console[v4.0.0, v4.0.1, v4.0.10, v4.0.11, v4.0.12, v4.0.13, v4.0.14, v4.0.15, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.1, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.1, v5.0.0, v5.0.1].
> - Can only install one of: symfony/console[v4.0.0, v3.4.35].
> 
> Anyways, I directly gave, composer create-project laravel/laravel projectname
> This worked perfectly on MacOS catalina 10.15.1!

I still run into the same issue currently

**Comment by driesvints** [comment]
Hey everyone,

I'm locking this issue because it either has gone off-topic, become a dumping ground for things which shouldn't be in an issue tracker or is just too old. Please try to discuss things further on one of the below channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
