### ISSUE TITLE
Hydrating a model with a casted attribute, re-casts that attribute upon reference

### ISSUE THREAD

**Issue by khooz** [laravel/framework#30397]
- Laravel Version: 5.8.29
- PHP Version: 7.3.9
- Database Driver & Version: MySQL Community Server - GPL 8.0.17

### Description:
When a model with a casted attribute is hydrated with already casted attributes, upon accessing the hydrated model, eloquent tries to re-cast those attributes.

### Steps To Reproduce:
1. Make a model (`SomeModel`) with an attribute (`some_column`) casted to array or json.
```php
/**
 * The attributes that should be cast to native types.
 *
 * @var array
 */
protected $casts = [
    'some_column' => 'array',
];
```
2. Make an array of `SomeModel`
```php
$some_model_data = [
    [
        'some_column' => [
            'some_key' => 'some_data',
        ],
    ],
];
```
3. Use hydrate to assign current data to another variable.
```php
$some_models = SomeModel::hydrate($some_model_data);
```

4. Access the said attribute (`some_column`) from the hydrated variable.
```php
foreach ($some_models as $some_model)
{
    if (isset($some_model->some_column['some_key'])) // Throws ErrorException (E_WARNING)
    // json_decode() expects parameter 1 to be string, array given
    {
        echo $some_model->some_column['some_key'] . "\n";
    }
}
```

**Comment by khooz** [comment]
As a hotfix, I just commented the casting of the attribute that bugs, and use pure Mutator/Accessor on the model.

```php
protected $casts = [
   //  'some_column' => 'array',
];

public function getSomeColumnAttribute()
{
    if (!isset($this->attributes['some_column']) || $this->attributes['some_column'] === null)
    {
        return null;
    }
    if (is_array($this->attributes['some_column']))
    {
        return $this->attributes['some_column'];
    }
    return json_decode($this->attributes['some_column'], true);
}

public function setSomeColumnAttribute(array $value)
{
    if ($value === null)
    {
        return $this->attributes['some_column'] = $value;
    }
    return $this->attributes['some_column'] = json_encode($this->attributes['some_column']);
}
```

**Comment by mfn** [comment]
There is no bug here, this is the expected behaviour.

Hydration happens with the "raw data from the database", _that_ is the use case.

That's why the code (called through `->hydrate()`) looks like this, emphasis on `setRawAttributes`:
```php
    public function newFromBuilder($attributes = [], $connection = null)
    {
        $model = $this->newInstance([], true);

        $model->setRawAttributes((array) $attributes, true);
```

So if you want to make it work manually, you've to make sure your data is json encoded in this case already.

**Comment by khooz** [comment]
Thanks @mfn! I thought `hydrate` is tolerant. I think I should close this issue then and move it to laravel/ideas as having a more tolerant way of converting things (arrays/collections) to models.
