### ISSUE TITLE
.env variables not working when putenv() is disabled

### ISSUE THREAD

**Issue by vaites** [laravel/framework#30396]
- Laravel Version: 6.3.0
- PHP Version: 7.3.10
- Database Driver & Version: not applicable

### Description:

When putenv() function is disabled (some hosting providers do this because of security reasons) the env() funcion doesn't detect the variable value. This is because [dotenv](https://github.com/vlucas/phpdotenv) can't put the environment variable using putenv() and env() relies on getenv()...

Must Laravel throw an exception here? If Laravel relies on putenv()/getenv() and is not avaliable the developer must know that if .env exists and is not empty the variables will not be loaded. 

### Steps To Reproduce:

1. Add putenv to disabled_functions in php.ini and restart webserver
2. Check any value on .env with env('VARIABLE_NAME');

### Suggested solution

Then, the fix can be added to the env() function with a fallback to check $_ENV global variable instead of returning the default value:

```php

function env($key, $default = null)
    {
        $value = getenv($key);

        if ($value === false && array_has($_ENV, $key) {
            $value = array_get($_ENV, $key);
        } elseif ($value === false) {
            return value($default);
        }

        // ...

        return $value;
    }

```
I can make a pull request if you think this solution is acceptable.

**Comment by driesvints** [comment]
When I add `\Illuminate\Support\Env::disablePutenv();` to the `AppServiceProvider` I can still use the `env` helper properly so it's not required.

**Comment by vaites** [comment]
Thanks @driesvints, didn't know this method because is not documented. 

Anyway, I think this must be detected and disabled automatically if `putenv()` is not available. Is just a simple check with `function_exists()`. Why use an adapter that will fail?

**Comment by vaites** [comment]
@driesvints, Is this issue definitely closed? We should not discuss whether it is necessary for Laravel to automatically call `\Illuminate\Support\Env::disablePutenv();` if `putenv()` is not available.
