### ISSUE TITLE
Column not found: 1054 Unknown column in Laravel Query

### ISSUE THREAD

**Issue by shandongwuyanzu** [laravel/framework#30393]
- Laravel Version: 6.2
- PHP Version: 7.3
- Database Driver & Version: Mysql

### Description:
I get an error when i use paginate method with having method
### Steps To Reproduce:
$totalAmount = Order::selectSub("sum(price)","totalAmount")
    ->having("totalAmount",">", 100)
    ->groupBy('user_id')
    ->paginate(10);

**Comment by netpok** [comment]
It would help a lot if you provide the full error message. Does it work without the pagination?

**Comment by ROOKIE20570** [comment]
> It would help a lot if you provide the full error message. Does it work without the pagination?

I also made a similar issue but did not respond. #30282

**Comment by shandongwuyanzu** [comment]
@netpok, @ROOKIE20570  it work without the pagination

**Comment by ROOKIE20570** [comment]
I already have a pr for this, but it has been closed. #30295

**Comment by netpok** [comment]
Well this is definitely a bug, calling paginate will change
```sql
select (sum(price)) as `totalAmount` from `users`
group by `user_id`
having `totalAmount` > ?
```
to
```sql
select count(*) as aggregate from `users`
group by `user_id`
having `totalAmount` > ?
```

**Comment by shandongwuyanzu** [comment]
I temporarily used @ROOKIE20570's code, it 's work for me.

**Comment by driesvints** [comment]
Since the PR was rejected, It seems like this is a no-fix, sorry.

**Comment by devcircus** [comment]
This is a longstanding Laravel issue, for which a working fix has never been discovered. The "fixes" that have been introduced usually have edge cases for which they introduce more bugs. There is, however, [this package](https://github.com/justbetter/laravel-pagination-with-havings), which may help.
