### ISSUE TITLE
Scheduling: runInBackground always fire onFailure and emailOutputOnFailure methods

### ISSUE THREAD

**Issue by pavelforever** [laravel/framework#30392]
- Laravel Version: 6.3
- PHP Version: 7.3.9

### Description:
When I run a schedule with runInBackground parameter it's always fire onFailure and emailOutputOnFailure events though no errors happen. Why?

### Steps To Reproduce:
In routes/console.php
```
Artisan::command('hi', function () {
    echo 'hi';
});
```

In Console/Kernel.php
`$schedule->command('hi')->everyMinute()->emailOutputOnFailure('MY_EMAIL@GMAIL.COM')->runInBackground();`

**Comment by driesvints** [comment]
This is a duplicate of https://github.com/laravel/framework/issues/28992

**Comment by pavelforever** [comment]
maybe it's a duplicate, but the problem still exists

**Comment by driesvints** [comment]
@pavelforever you're free to help out by sending in a PR if you can
