### ISSUE TITLE
PSR7 requests do not contain route attributes

### ISSUE THREAD

**Issue by pjordaan** [laravel/framework#30415]
- Laravel Version: 5.8, but probably lower versions are affected too.
- PHP Version: 7.3

### Description:
I wanted to incorporate a library with PSR7 controllers. According the documentation Laravel supports PSR7 requests. However the library tries to get route attributes, and those are missing in the PSR7 request Laravel creates. This is because the library used is made for symfony which stores them in Request::attributes. Laravel stores them in the route resolver.

### Steps To Reproduce:

Any controller using PSR7 and any attribute method.
```php
class ExampleController
{
    public function method(ServerRequestInterface $request) {
       return $request->getAttribute('attribute');
    }
}
```

And a route like:
```php
// route.php
Route::get('/{attribute}', 'ExampleController::method');
```
I expect to get $request->getAttribute('attribute'); returns the url, but it returns null.

### Workaround for now:
I have fixed it now by using extend in my service provider:
```php
$this->app->extend(ServerRequestInterface::class, function (ServerRequestInterface $psrRequest) {
    $route = $this->app->make('request')->route();
    if ($route) {
        $parameters = $route->parameters();
        foreach ($parameters as $key => $value) {
            $psrRequest = $psrRequest->withAttribute($key, $value);
        }
    }
    return $psrRequest;
});
```

Would it be possible this works out of the box?

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
