### ISSUE TITLE
Laravel 6 still uses stray instances of str_and array_ 

### ISSUE THREAD

**Issue by connecteev** [laravel/framework#30428]
- Laravel Version: #.#.# 6.4
- PHP Version: #.#.# 7.3
- Database Driver & Version: MySQL 8

### Description:
Laravel 6 still uses stray instances of str_and array_ when they should be removed.
See https://laravel.com/docs/6.x/upgrade#helpers

### Steps To Reproduce:
After doing "laravel new myapp", I did a grep and found these:
```
$ grep -ri "array_" *
config/database.php:            'options' => extension_loaded('pdo_mysql') ? array_filter([
$ grep -ri "str_" *
resources/views/welcome.blade.php:<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
```

**Comment by it-can** [comment]
These are php functions not laravel helpers...

**Comment by connecteev** [comment]
@it-can the documentation isn't very clear...

**Comment by devcircus** [comment]
None of Laravel's helper methods are named the same as existing PHP functions, so there's no chance these are from laravel. You can see the available laravel helpers in the helpers package @ [github.com/laravel/helpers](https://github.com/laravel/helpers)

**Comment by connecteev** [comment]
What I was looking for was a link to this in the docs.
https://laravel.com/docs/5.6/helpers
since these are the functions I need to search and replace.
