### ISSUE TITLE
Running artisan up without w permission doesn't display an error message

### ISSUE THREAD

**Issue by robchava** [laravel/framework#30421]
- Laravel Version: 5.8
- PHP Version: PHP 7.2.19-0ubuntu0.18.04.2
- Database Driver & Version: NA

### Description:
Running `./artisan down` with incorrect permissions fails with an error message. However running `./artisan up` does not, but instead indicates it did exit maintenance mode but it does not remove the app from maintenance mode.

### Steps To Reproduce:
cd into your app directory (in which your current user doesn't have w permission)
`./artisan down`
Verify you get an error message on the console
Verify your site is not in maintenance mode
`sudo ./artisan down`
Verify your site is in maintenance mode
`./artisan up`
Verify you didn't get any error message on the console, but instead a success message ("Application is now live.")
Verify your site is still in maintenance mode

**Comment by fitztrev** [comment]
Which 5.8 release are you on? This PR #28765 landed in 5.8.22

**Comment by robchava** [comment]
Sorry about that. It's 5.8.19
