### ISSUE TITLE
Laravel String Validation Failing on “True” and “False”

### ISSUE THREAD

**Issue by FriendlyUser** [laravel/framework#30424]
- Laravel Version: 5.6.39
- PHP Version:  7.3.2
- Database Driver & Version:

Postgres 10
### Description:
Can't seem to use string validations with Boolean like strings such as "True" and "False"
![image](https://user-images.githubusercontent.com/13860264/67587650-32c44280-f709-11e9-8512-ec6d59bdb0ae.png)

### Steps To Reproduce:

1. Send JSON to an endpoint with the format of {"last_name": "True"}, validations throws an error

Validiation rules are like 

```
            'application_borrowers.*.first_name'               => 'sometimes|required|string|max:255',
            'application_borrowers.*.last_name'                => 'sometimes|required|string|max:255',
```

**Comment by fitztrev** [comment]
Can you try against 6.x with a minimal example? This is working for me:

```php
\Illuminate\Support\Facades\Validator::make([
    'a' => 'true',
    'b' => 'TRUE',
    'c' => true,
    'd' => 'false',
    'e' => 'FALSE',
    'f' => false,
], [
    'a' => 'string',
    'b' => 'string',
    'c' => 'string',
    'd' => 'string',
    'e' => 'string',
    'f' => 'string',
])->errors();
```

**Comment by FriendlyUser** [comment]
Looks like it was a middleware issue not a problem with laravel, my bad

**Comment by natsu90** [comment]
@FriendlyUser sorry what do you mean by middleware issue? I have the same issue using Laravel 6, may I know what's your solution or workaround?

**Comment by FriendlyUser** [comment]
This was a long time along, think there was some legacy php code designed for older versions of php that was massaging the data, so that "True" and/or "False" became the expecting values. This happens when you are working with older versions of php, some bad code can seep in.
