### ISSUE TITLE
Can't log in after running the logoutOtherDevices function

### ISSUE THREAD

**Issue by andrew-montague** [laravel/framework#30434]
- Laravel Version: 6.4.0
- PHP Version: 7.3.9

### Description:

After following the [Laracasts tutorial](https://laracasts.com/series/whats-new-in-laravel-5-6/episodes/7) on how to invalidate all other sessions for a user's account, I have found that when attempting to log in again after the session has been successfully invalidated, the credentials no longer work meaning the user cannot log in again.

### Steps To Reproduce:

Un-comment the following line in `app/Http/Kernel.php` class' `web` middleware group:
`\Illuminate\Session\Middleware\AuthenticateSession::class,`

Add the following route in `routes/web.php` - this is exactly what is typed in the Laracast episode:

```php
Route::get('/logoutOthers', function() {
   auth()->logoutOtherDevices('password');
   
   
   return redirect('/');
});
```

Open two browsers (Safari & Chrome) and then log into the same account on both. On one of the browsers, go to `/logoutOthers`

Then on the other browser refresh the page. As expected, the user has been signed out. But when the user tries to sign in again, using the password that has been hardcoded in the route above, they receive the following message:

> These credentials do not match our records.

**Comment by driesvints** [comment]
Everything seems to be working for me just fine.

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
