### ISSUE TITLE
Insert float  type into database  table but fractional part loses

### ISSUE THREAD

**Issue by liugj** [laravel/framework#30435]
- Laravel Version: 5.4+
- PHP Version: 7.2+
- Database Driver & Version: mysql

### Description:
Insert float  type into database  table but fractional part loses

### Steps To Reproduce:

CREATE TABLE `order` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `cast` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '订单总金额',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB
DB::table('order')->insert(['cast' => 10.11]);
```
 select * from order where id  =1
+--------+----------+ 
| id     | cast     | 
+--------+----------+ 
| 1      | 10.00    | 
+--------+----------+ 
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
