### ISSUE TITLE
ensureCacheDirectoryExists Does Not Check Writeability

### ISSUE THREAD

**Issue by socialknowledge** [laravel/framework#30447]
- Laravel Version: 5.6.x - current
- PHP Version: #.#.#
- Database Driver & Version:

### Description:
ensureCacheDirectoryExists does not check if directory is writeable.  If a cache entry is created via cron by a user that the webserver user cannot access, it will cause a 500 error.  The file directory will exist, however, it is inaccessible to the user.  

### Steps To Reproduce:
Run a cron job with a user who is different from the web server user, and create a cached entry.   To to write in the same directory created by the cron user, as the web user..

**Comment by driesvints** [comment]
You'll need to make sure of your own that this directory is writeable.
