### ISSUE TITLE
Using relationship in withCount returns all table data

### ISSUE THREAD

**Issue by victor-priceputu** [laravel/framework#30449]
- Laravel Version: 6.0.3
- PHP Version: 7.3.11
- Database Driver & Version:
MySQL 5.7.25

### Description:
In a model, retrieving a count for a relationship based on the role of the user making the call, the all the roles are being populated and not filtered.

### Steps To Reproduce:
I have a `User` model with a `belongsToMany` relationship for roles.
I have a `Profile` model where I am overriding the `query` method to add counts for a relationship:

```
public static function query()
    {
        $query = parent::query();
        if (Auth::hasUser()) {
            return $query
                ->withCount('bookings');
        }

        return $query;
    }
```

In the `bookings` relationship I need to do some logic based on the user making the request, but doing `Auth::user()->roles` returns the roles for ALL the users in the database.

Whenever I use the relationship in any other context (the `roles`, or `bookings`) I get the right amount of roles, but only when the relationship is called from within the `withCount` it does not filter for the current user.

To hack-fix this I have to get the roles in the `query` method, so they are eager loaded, and then it works fine in the relationship.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by victor-priceputu** [comment]
But is this not a bug that should be investigated? Or is it the intended functionality?

**Comment by victor-priceputu** [comment]
@driesvints so is this not a bug that should be investigated? Does this mean that the work-around needs to be applied for each relationship which is used?
