### ISSUE TITLE
[6.3] Migration --seed with --path

### ISSUE THREAD

**Issue by narwy** [laravel/framework#30457]
- Laravel Version: latest
- PHP Version: latest
- Database Driver & Version: mongodb + mysql

### Description:
Running `php artisan migrate --path="Modules/Accounting/Database/Migrations" --seed` with `--path` will run the migrations in that path, however the `--seed` option on top of that will also seed the default seeders in the base `database/seeds`, an option to provide a seeder path should be supported?

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!
