### ISSUE TITLE
Container.php -> findInContextualBindings() unexpected external slash

### ISSUE THREAD

**Issue by 6562680** [laravel/framework#30452]
- Laravel Version: 6
- PHP Version: 7.3
- Database Driver & Version: MySQL8

### Description:
Application provides unresolvable primitive even if primitives is passed in service provider using "when" syntax

### Steps To Reproduce:
```
class My {
  public function __construct(string $locale) {}
}

$this->app->when(My::class)->needs('$locale')->give(function () {
  return app()->getLocale();
});

$this->app->make(My::class);
```

Reason:
```
    protected function findInContextualBindings($abstract)
    {
        return $this->contextual[end($this->buildStack)][$abstract] ?? null;
    }

// dump($this->buildStack); // [ 0 => \My::class; ]
// dump($this->contextual); // My::class => [ '$locale' => Closure ];
```
two dumps differs with forward backslash

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
