### ISSUE TITLE
NOAUTH failure when clearing cache on password-protected Redis cluster

### ISSUE THREAD

**Issue by joshuadwire** [laravel/framework#30463]
- Laravel Version: 6.4.1
- PHP Version: 7.3.8
- Database Driver & Version: php-redis 5.0.2

### Description:
When clearing the cache on a password-protected Redis cluster, the flushdb function does not properly authenticate against each master. If a password is set for the Redis cluster, the flushdb command needs to access the password and call `->auth()` on each connection before calling `->flushDb()`

### Steps To Reproduce:

1. Configure Laravel cache to use a password protected Redis cluster using the phpredis driver.
2. Run `php artisan cache:clear`
3. The following error message is received:
```
   RedisException  : NOAUTH Authentication required.

  at /var/www/html/vendor/laravel/framework/src/Illuminate/Redis/Connections/PhpRedisConnection.php:404
    400|             return $this->command('flushdb');
    401|         }
    402| 
    403|         foreach ($this->client->_masters() as [$host, $port]) {
  > 404|             tap(new Redis)->connect($host, $port)->flushDb();
    405|         }
    406|     }
    407| 
    408|     /**

  Exception trace:

  1   Redis::flushDB()
      /var/www/html/vendor/laravel/framework/src/Illuminate/Redis/Connections/PhpRedisConnection.php:404

  2   Illuminate\Redis\Connections\PhpRedisConnection::flushdb()
      /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/RedisStore.php:217
```

**Comment by joshuadwire** [comment]
As a temporary workaround, overriding flush in RedisStore with the following resolves the issue. I'm unsure of the best way to fix this in the core framework though:

```php
public function flush()
{
    $connection = $this->connection();
    $client = $connection->client();

    if (class_exists('RedisCluster') && $client instanceof \RedisCluster) {
        $config = \Config::get('database.redis', []);
        $options = $config['clusters'][$this->connection];

        // Authenticate with each master individually.
        foreach ($client->_masters() as [$host, $port]) {
            $redis = tap(new \Redis())->connect($host, $port);
            if (!empty($options) && !empty($options[0]['password'])) {
                $redis->auth($options[0]['password']);
            }

            $redis->flushdb();
        }
    } else {
        $connection->flushdb();
    }

    return true;
}
```

**Comment by driesvints** [comment]
Nvm, you need help with clearing your cache, not with authenticating. 

The problem seems to be that it's not using the Redis client set in the connection instance. I'm not sure why that is. Maybe there's a specific reason?

**Comment by joshuadwire** [comment]
@driesvints Right, this is only when clearing the cache. When clearing the cache on the cluster, the flush command needs to be run on each master rather than just once on the whole cluster, so the driver is creating a separate connection to each master. The issue is that it's not authenticating that new connection.

**Comment by taylorotwell** [comment]
Fixed.
