### ISSUE TITLE
Password confirmation middleware - only works with default auth provider?

### ISSUE THREAD

**Issue by ohnotnow** [laravel/framework#30464]
- Laravel Version: 6.4.1
- PHP Version: 7.3.10
- Database Driver & Version: MySQL 5.7

### Description:

We have a custom auth provider (using LDAP) which creates local users in the db when they first log in - the password field is just set to a bcrypted long random string.  There are also regular 'local' users with a conventional bcrypted password.

Normal 'local' users can use the password confirmation route a-ok, but the ones using the LDAP  fail to validate the password.

I'm wondering if I can change my provider to allow it to work (I didn't see anything in the custom provider docs) - or if this is just how things are?  If that's the case I can maybe do a PR for the docs to mention it?

### Steps To Reproduce:

Write a custom provider using LDAP and try the password confirmation middleware.

**Comment by driesvints** [comment]
The current implementation expects the user to already be logged in. With that in mind, your default provider should be set to whatever your user's authed with. I'm not sure what you're exactly doing that's causing something to not work for you? It would be best if you shared some code. Maybe upload a Github repo to reproduce the problem?

**Comment by ohnotnow** [comment]
Hi,

I did a bit of diving around the source - it _looks like_ the `password` validator is pulling the hashed password from the local random/dummy password field in the db as I hadn't implemented a local `getAuthPassword()`.  But I don't think I _can_ implement it as the password is over in the LDAP service so I have no way of pulling it out.  I'd kind of assumed (wrongly) that somewhere it was just calling `validateCredentials` on the provider.

So I guess it's a no-go for me.  Never mind - I'll go back to a modal just saying 'Are you really sure?' :-)  Still might be worth adding a little note to the docs I think - assuming I'm right in my digging around.

**Comment by driesvints** [comment]
No worries at all. Feel free to send in a PR to the docs if you think something needs clarifying.
