### ISSUE TITLE
Accessor where field name ends with a number doesn't get mutated value

### ISSUE THREAD

**Issue by NikolayOskin** [laravel/framework#30477]
- Laravel Version: 6.3.0
- PHP Version: 7.2.0
- Database Driver & Version:

### Description:
When the model has the field which ends with the number ($user->photo_1 as an example), then getPhoto1Attribute($value) doesn't mutate the value and returns $user->photo_1 as it is.

### Steps To Reproduce:
Create a model with fields like 'something_number' ('something_1').
Then try to test getSomething1Attribute() 
```
    public function getSomething1Attribute($value)
    {
        return 'test';
    }
```
When you get your model from eloquent you will see the field is not mutated.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
