### ISSUE TITLE
route() method 2nd arg (URI items) doesnt accept collection (instead of array)

### ISSUE THREAD

**Issue by kapposds** [laravel/framework#30481]
- Laravel Version: 6.0.3
- PHP Version: 7.2.15

### Description:
route() function second argument where we define URI parameters accepts an array. Why not accept data structures that are compatible with arrays like collections for example? When i pass a collection i get the error `Missing required parameters for [Route: items.index] [URI: items].`

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!
