### ISSUE TITLE
Give a Generic Error Message for php artisan make:auth 

### ISSUE THREAD

**Issue by noamanahmed** [laravel/framework#30499]
I am aware the that authentication has been moved to a seperate package but when a newbie/new to laravel types this command there shoudl be a generic error message to help him install the  package

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!
