### ISSUE TITLE
Dynamic Rate Limiting

### ISSUE THREAD

**Issue by Dewbud** [laravel/framework#30498]
- Laravel Version: 6.0.3
- PHP Version: 7.3.9
- Database Driver & Version: MySQL 5.7.27

### Description:
The method to dynamically rate limit users in the documentation doesn't work as described.
[https://laravel.com/docs/master/routing#rate-limiting](https://laravel.com/docs/master/routing#rate-limiting)

### Steps To Reproduce:
Clean install
Add a rate_limit field to the user model and give it a value > `0`
add 'throttle:rate_limit,1' middleware to a route
Rate limit will return `0` because ```((int) 'rate_limit') === 0```

### Solution:
This is caused by the request not having resolved the user yet, so it can't get the rate_limit attribute.
Place the ThrottleRequests middleware to a lower priority than the Authenticate Middleware.
This allows the user model to be usable in ThrottleRequests::resolveMaxAttempts.

I'm not sure where the default middleware priority is set in the framework or I'd submit a PR to go with this. It's a simple fix.

Or just update the documentation to add a note about the middleware order.

```php

    protected $middlewarePriority = [
        ...
        \App\Http\Middleware\Authenticate::class,
        \Illuminate\Routing\Middleware\ThrottleRequests::class,
        ...
    ];
```

**Comment by netpok** [comment]
This was already 4 months ago to the default Kernel.php

**Comment by Dewbud** [comment]
You're correct, I was looking in the wrong repo.
