### ISSUE TITLE
[6.x] The ensureMigrationDoesntAlreadyExist method should not check recursively

### ISSUE THREAD

**Issue by stancl** [laravel/framework#30505]
- Laravel Version: 6.1.0+
- PHP Version: any
- Database Driver & Version: any

### Description:

#30095 introduced a backwards incompatible change. The `ensureMigrationDoesntAlreadyExist` method checks for existing migrations recursively, which is wrong.

If you're creating a migration in `database/migrations/`, you don't care that the same migration exists in `database/migrations/tenant/` because `php artisan migrate` only executes migrations in the main directory by default.

### Steps To Reproduce:

Put the same migration in `database/migrations/` and `database/migrations/tenant/`. `php artisan migrate` doesn't execute migrations inside the `tenant/` subdirectory, but it will complain about the same migration existing in both directories.

**Comment by netpok** [comment]
Actually it should, because Migrations are not namespaced so having the same migration in two paths will result in `Cannot declare class CreateRandomMigratedTable, because the name is already in use` error when both paths are passed to the migrate command.

**Comment by stancl** [comment]
The migrator looks for migrations only in the root directory, so despite using the same namespace, using path-based separation of migrations worked in all previous versions.

**Comment by netpok** [comment]
But the migrate command accepts multiple paths.

**Comment by stancl** [comment]
I see.
