### ISSUE TITLE
TestResponse::assertJsonFragment is sorting the response by keys

### ISSUE THREAD

**Issue by lasselehtinen** [laravel/framework#30501]
- Laravel Version: 6.4.0
- PHP Version: 7.2.19
- Database Driver & Version: SQLite 3.22.0

### Description:

Why is assertJsonFragment using Arr::sortRecursive to sort the response by keys? This makes using assertJsonFragment in test pretty difficult when actually trying to test if the JSON contains certain fragment when you have collections in the resource. Below is a typical resource with contains the attributes of the actual model and some relationships. I am not really interested in the relationships, I just want to see that it returns the correct model. For me it does not make much sense, why does it even have to manipulate the JSON response?

```php
/**
 * Test that user can add DX entities that he/she worked already
 *
 * @return void
 */
public function testUserCanAddDxEntitiesThroughApi()
{
    $user = factory(\App\User::class)->create();

    // Check that the user does not have any entities yet
    $response = $this->json('GET', '/api/v1/users/1/dxentities');
    
    $response
        ->assertStatus(200)
        ->assertExactJson([
            'data' => [],
        ]);
    
    // Add Finland as worked entity
    $response = $this->json('PUT', '/api/v1/users/1/dxentities/204');

    $response
        ->assertStatus(200)
        ->assertJsonFragment([
            'data' => [
                [
                    'id' => 204,
                    'name' => 'Finland',
                ],
            ],
        ]);
}
```

```php
class DxEntity extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'name' => $this->name,
            'continents' => Continent::collection($this->continents),
            'prefixes' => Prefix::collection($this->prefixes),
            'cq_zones' => CqZone::collection($this->cqZones),
            'itu_zones' => ItuZone::collection($this->ituZones),
        ];
    }
}
```

_Actual response:_
![image](https://user-images.githubusercontent.com/1290186/68081864-45cbc680-fe1d-11e9-8acb-3c5308d5ba16.png)

_After the response has been sorted:_
![image](https://user-images.githubusercontent.com/1290186/68081808-5cbde900-fe1c-11e9-8d21-77c259834411.png)

**Comment by driesvints** [comment]
This is because these methods don't assert the exact order of the results. What you're looking for is `assertJsonStructure`: https://laravel.com/docs/6.x/http-tests#assert-json-structure
