### ISSUE TITLE
Too few arguments to function assertQueued Illuminate/Support/Testing/Fakes/MailFake.php

### ISSUE THREAD

**Issue by CasperEngl** [laravel/framework#30511]
- Laravel Version: 5.7
- PHP Version: 7.3.9
- Database Driver & Version: SQLite

### Description:
```
ArgumentCountError: Too few arguments to function Tests\Feature\Test::Tests\Feature\{closure}(), 1 passed in /Users/User/Website/vendor/laravel/framework/src/Illuminate/Support/Testing/Fakes/MailFake.php on line 202 and exactly 2 expected
```
When too many arguments are passed to the callable callback in `assertQueued` the argument count error says there's too few arguments, when in fact there are too many.

### Steps To Reproduce:
Pass too many arguments (`$EXTRA_ARG`) to callable in assertQueued:
```php
class Test extends TestCase
{
    public function some_test_case()
    {
        Mail::fake();

        Mail::assertQueued(
            Mailable::class,
            function ($mail, $EXTRA_ARG) {
                // ...
            }
        );
    }
}
```

**Comment by netpok** [comment]
This is the expected output, the mail fake calls the provided callback with one parameter but that wants two.

You are passing the callback not the argument list of the callback, the mail fake passes the arguments to the callback.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
