### ISSUE TITLE
Log [] is not defined.

### ISSUE THREAD

**Issue by JamesKid** [laravel/framework#30510]
- Laravel Version: 6.4.1
- PHP Version: 7.3.10
- Database Driver & Version:mysql 5.6.0
-Xdeubg Version 2.8.0 beta

### Description:  Exception has occurred.
InvalidArgumentException: Log [] is not defined. with xdebug 

### Steps To Reproduce:
![图片](https://user-images.githubusercontent.com/6158899/68122023-575bbe00-ff44-11e9-8f63-a29e5279b421.png)

**Comment by adamhopkinson** [comment]
`$name` is blank, so the function can't fetch a `$config`.

Are you sending your log message to the default channel, or specifying one? Is there a matching config in `config/logging.php`? And if you are using the default, is it set up in that file and does it have a config?

**Comment by JamesKid** [comment]
thank you !, i lose my config/logging.php file , i copy it from " laravel/laravel.com-next"  then ,it's ok , many thanks .
