### ISSUE TITLE
Url validation accept wrong domain format

### ISSUE THREAD

**Issue by devlifeX** [laravel/framework#30512]
- Laravel Version: 6.2
- PHP Version: 7.3
- Database Driver & Version: mariadb

### Description:
URL validation rule accept wrong domain format
Like: a@.com
A@.com is not valid domain. it supposes to wrong URL but laravel ok with that.

**Comment by ahinkle** [comment]
I think this is intended behavior [as some URLs might be formed similar to that](https://stackoverflow.com/questions/19509028/can-i-use-an-at-symbol-inside-urls/19737890). You can have a look at the regex that is used internally for validating URLs [here](https://github.com/laravel/framework/blob/6.x/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L1656)
 
If your use case requires that a URL must follow other rules, I recommend you setup a custom validation rule.

**Comment by devlifeX** [comment]
I think wrong domain can't be a valid URL. Ofcourse custom validation rule can solve my problem.
I trusted laravel URL validation and it made me confused.

**Comment by dwightwatson** [comment]
The point is that *A@.com* is technically a valid domain.

You might instead want to consider the [`active_url`](https://laravel.com/docs/6.x/validation#rule-active-url) validation rule, or if you have other requirements then implement your own custom rule.

**Comment by driesvints** [comment]
It's indeed a valid email address. If you want to use the pre-5.8 behavior you can use the `filter` validator: https://laravel.com/docs/6.x/validation#rule-email
