### ISSUE TITLE
Target class [env] does not exist

### ISSUE THREAD

**Issue by marbuser** [laravel/framework#30531]
- Laravel Version: 6.0
- PHP Version: 7.3.11
- Database Driver & Version: MySQL 8.0.18

### Description:
Last night all my tests were working correctly, but this morning they appear to just like, not work? If I run a test individually, it works fine. But if I try run more than 1 test at once, I get the error;
`Illuminate\Contracts\Container\BindingResolutionException : Target class [env] does not exist.`

After some research I found that others were having this issue because of telescope, so I tried setting the env variables in the PHPUnit XML but no luck, it is still happening.

I even went as far as removing everything I did last night since I thought maybe I pulled in a bad dependency or something, but even after removing everything it still happens. No clue what is causing it.

### Steps To Reproduce:
I have no idea. It randomly started happening.

**Comment by RVxLab** [comment]
I found that this happens when trying to register middleware conditionally.

app/Http/Kernel.php:

```php
public function handle($request)
{
    if ($this->app->environment([ 'local', 'dev' ])) {
        $this->middleware[] = DevMode::class;
    }

    return parent::handle($request);
}
```

- Laravel version: 6.5.0
- PHP version: 7.3.9

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by DanielFloris** [comment]
@marbuser Did you ever find out what caused this? I'm suffering the same.
