### ISSUE TITLE
The artisan command reads configuration files from different environments

### ISSUE THREAD

**Issue by SayHe110** [laravel/framework#30537]
hello~

Environment version: php: 7.2.15 , laravel: 5.5

I configured profiles for different environments, `.env.dev` `.env.production`, and configured `nginx.conf` params `fastcgi_param APP_ENV production;`;

However, when the artisan command reads the env file, it cannot get the configuration information, for example `env('REDIS_HOST');`, result is `null`;

Why is that?

thanks.

**Comment by netpok** [comment]
Because artisan commands are not called by the nginx, you can pass the env  with the `--env` variable.

**Comment by SayHe110** [comment]
> Because artisan commands are not called by the nginx, you can pass the env with the `--env` variable.

Thank you for reply.
I know that way, but I don't want to. Because it's too inconvenient.

I'd better configure the default config.
