### ISSUE TITLE
Can not apply .env changes if running on artisan serve

### ISSUE THREAD

**Issue by magai** [laravel/framework#30530]
- Laravel Version: 6.5.0 (and old versions)
- PHP Version: 7.3.11
- Database Driver & Version: MySQL 5.7.24

### Description:
ServeCommand executes PHP built-in server by using passthru().
passthru() (and other command excecute functions) inherits environment variables.
And Laravel do not overload environment variable.
Built-in server proccesses can not apply .env changes.

I have no idea for fix this behavior.

For example, using Dotenv::overload() instead of safeLoad() (or load()) fixes this behavior.
But this fix has too large side effects I think.

### Steps To Reproduce:

$ laravel new --dev test
$ cd test

edit routes/web.php
```
+ return config('app.name');
- return view('welcome');
```

$ php artisan serve

visit http://localhost/ shows "Laravel"

edit .env and change APP_NAME
```
+ APP_NAME=Changed!
- APP_NAME=Laravel
```

visit http://localhost/ shows "Laravel" again.

**Comment by xmoroccan** [comment]
I think this the intended behavior, and I believe this mentioned somewhere in the docs!

**Comment by netpok** [comment]
This is because artisan serve handles the requests without starting a new instance for every request.

Think about artisan serve like an opcached php instance with config:cache: if anything changes in the code/.env you should restart it.

**Comment by magai** [comment]
Thanks for replies.

@netpok 
artisan serve is not handle requests directly.
artisan process sets environment variables and inherits it to PHP built-in server is problem.
If PHP built-in server directly executed(Like `php -S 127.0.0.1:8000 /path/to/server.php`), `.env` changes applies correctly.

**Comment by driesvints** [comment]
This is the current and expected behavior.

**Comment by magai** [comment]
@driesvints 

Thanks for reply.

I think this behavior must document.
But my English is very ugly.
Please rewrite and document this behavior.

1. `php artisan serve` sets environment variables from .env (or other .env files).
2. Application process that ran by artisan inherits environment variables and can't overwrite variables, therefore can't apply `.env` changes.
3. If you want to ignore this behavior, use `php -S` directly.
