### ISSUE TITLE
There is an exhaust of memory when call ->toSlq() on \Illuminate\Database\Eloquent\Builder in global scope class in handle method.

### ISSUE THREAD

**Issue by vasymus** [laravel/framework#30535]
- Laravel Version: 6.0.4
- PHP Version: 7.2.19
- Database Driver & Version:

php --version
PHP 7.2.19-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: May 31 2019 11:16:55) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.19-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

### Description:
There is an exhaust of memory when call ->toSlq() on \Illuminate\Database\Eloquent\Builder in global scope class in handle method.

### Steps To Reproduce:
create any scope class using
php artisan make:scope SomeScopeClass
apply this scope class to any Eloquen model in protected static function boot() method
in this scope class in handle method call
$builder->toSql();

**Comment by netpok** [comment]
I think this is an infinite recursion and not a bug. 

You are in a method which is executed while a query is being created and toSql will create a query.

**Comment by driesvints** [comment]
Please see the answer by @netpok

**Comment by driesvints** [comment]
@netpok btw, don't know how to reach you besides here but really appreciate all your help on the issues and prs lately 👍

**Comment by vasymus** [comment]
@driesvints 
Ok, thanks. But, maybe somebody should put some warning in documentation at least ?
