### ISSUE TITLE
Can't Remove or Modify any uploaded files from request instance!

### ISSUE THREAD

**Issue by soheilrt** [laravel/framework#30532]
- Laravel Version: 5.8
- PHP Version: 7.3.11
- Database Driver & Version: maria-db 10.3.17

### Description:
Hey guys,
I'm trying to flatten request files.
I've also tried to remove uploaded files from request instance but it seems that I cant remove or modify uploaded files! I tried following codes inside my request instance but it didn't work!

```php
<?php

namespace App\Http\Requests\Dashboard\Admin\Content;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Arr;

class ContentStoreRequest extends FormRequest
{
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [...];
    }

    protected function prepareForValidation()
    {
        $this->merge([
            'is_active' => $this->get('is_active', 'on') == 'on',
            'image' => Arr::flatten($this->image),
        ]);
    }
}

```

I've also tried to remove all data from request with `$this->replace([])`  method but it does not remove or touch any uploaded files!

**Comment by xmoroccan** [comment]
If you have multiple file, I believe you can do something like this: `$this->allFiles()->flatten()` !

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
