### ISSUE TITLE
collection->sortBy not sort if return value is same

### ISSUE THREAD

**Issue by erlangp** [laravel/framework#30550]
- Laravel Version: 6
- PHP Version: 7.2

### Description:
$collection->sortBy not sort if return value is same

**Comment by rimace** [comment]
Yes, that is true, as for every sort function.
Could you describe the how it should sort instead?

**Comment by erlangp** [comment]
for example 1,1,1,2,2,3,3,3,3,4,5,5,5

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by erlangp** [comment]
?
