### ISSUE TITLE
Unit testing Jobs inside event listener

### ISSUE THREAD

**Issue by TNChalise** [laravel/framework#30556]
How can you test jobs dispatched from event listeners ?

**Event**
```
class EventReceived should ShouldQueue{}
```
**Event Listener**
```
class EventListener extends ShouldQueue{
    public function handle(){
          /// Class SomeHeavyJob implements ShouldQueue
          dispatch(SomeHeavyJob()); // Dispatching Job
     }
}
```

Unit Test:
```
Event::fake();
Queue::fake();

Event::assertDispatched(EventReceived::class); // assets true

/// [ErrorException] Illegal offset type in isset or empty
Queue::assertPushedOn(EventListener::class, function ($job) {
            dd($job);
           // return $job->class === SomeHeavyJob::class;
 });

/// The expected [SomeHeavyJob] job was not pushed.
Queue::assertPushed(SomeHeavyJob::class);
```

**Comment by mfn** [comment]
If you event listener contains _relevant business logic to test_ (which it probably shouldn't), you need to "make" it and invoke it's handle method.

Otherwise it works exactly like the Queue fake: jobs dispatched are **not** executed, hence you _don't test for the effects of a job, only it's presence.

Your test does the same: asserts the presence of an Event, not it's effect.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
