### ISSUE TITLE
Address in mailbox given [name key instead of email] does not comply with RFC 2822, 3.6.2.

### ISSUE THREAD

**Issue by VicGUTT** [laravel/framework#30557]
- Laravel Version: 6.5.0
- PHP Version: 7.2.4
- Database Driver & Version: SQLite v3.20.1

### Description:
If `$to` in `Mail::to($to)->send(...)` is not an array/collection of arrays or an object containing the `name` and `email` keys `/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php@normalizeRecipient` will mess up the said keys.

Therefore the following will throw a `Swift_RfcComplianceException` with the message `Address in mailbox given [User name] does not comply with RFC 2822, 3.6.2.` :

```php
$to = [
    'name'  => 'User name',
    'email' => 'email@example.com',
];

// OR

$to = collect([
    'name'  => 'User name',
    'email' => 'email@example.com',
]);

return Mail::to($to)->send(...);
```

On the other hand the following will not :

```php
$to = (object) [
    'name'  => 'User name',
    'email' => 'email@example.com',
];

// OR

$to = [[
    'name'  => 'User name',
    'email' => 'email@example.com',
]];

// OR

$to = collect([[
    'name'  => 'User name',
    'email' => 'email@example.com',
]]);

return Mail::to($to)->send(...);
```

The problem lies in the fact that `setAddress` in `/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php:577` loops over the keys and passes each individual key to the `normalizeRecipient` method which will return :

```php
{#1697 ▼
  +"email": "BC Sports Bretagne"
}
{#1731 ▼
  +"email": "bcsportsbretagne@gmail.com"
}
```

Is this the intended behavior ?
It is true that [the docs](https://laravel.com/docs/6.x/mail#sending-mail) does not state that the `to` method would accept an array but states : 

> The `to` method accepts an email address, a user instance, or a collection of users.

However, a one dimensional array would make a lot of sense and would be intuitive to use as well.

### Steps To Reproduce:

```php
use App\Mail\SomeMailableClass;
use Illuminate\Support\Facades\Mail;

Route::get('/mails', function () {
    $to = [
        'name'  => 'User name',
        'email' => 'email@example.com',
    ];

    return Mail::to($to)->send(new SomeMailableClass(...));
});
```

**Comment by driesvints** [comment]
This is the expected behavior. The quote you shared above is correct in regard to this.
