### ISSUE TITLE
email/resend on GET method not supported

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [laravel/framework#30558]
- Laravel Version: 6.5.0
- PHP Version: 7.2.24
- Database Driver & Version: not necessary

### Description:
after registration, if we try to log in before the mail with the confirmation link for the correct password change has been open and confirmed, the user get a link in order to resend that email, but that link use GET method and Auth routes doesn't support it

### Easy solve
on line 18 of verify view, use 
```php
{{ __('If you did not receive the email') }}, <form  method="post" action="{{ route('verification.resend') }}">@csrf <button type="submit">{{ __('click here to request another') }}</button></form>
``` 
and that's it

**Comment by AlbertoSinigaglia** [comment]
also, in the "Verify Email Address" email, in order to generate the link, is used the link reported on the .env, but on the "Reset Password Notification" not, infact in the first one i get http://mywebsite.lab/... and in the second one i get ''localhost/...''

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
