### ISSUE TITLE
Model::having('anything', '=', 'anyvalue')->delete() erase all the table

### ISSUE THREAD

**Issue by RomainMazB** [laravel/framework#30563]
- Laravel Version: 6.2
- PHP Version: 7.2.19
- Database Driver & Version: MySQL 5.7.24

### Description:
Initially, I tried to use `having` and `delete` eloquent's helper to clear the table from unused keywords (with no relation to a Website model from a pivot table), as you can see in my [Laracast post](https://laracasts.com/discuss/channels/eloquent/using-withcounta-havinga-count-0-delete-erase-all-the-table), I didn't know the `doesntHave` helper so I used:
```PHP
Keyword::withCount('websites')
        ->having('websites_count','=', 0)
        ->delete();
```
This command erased all my keywords table, I looked in telescope, the SQL generated was simply `DELETE FROM keywords`. In my use case, as mentioned by another Laracast user, I can use the `doesntHave` helper, but I tried just to confirm the issue:
```PHP
Keyword::having('id', '=', 11)->delete();
```
And again, all the table was cleared!
### Steps To Reproduce:
```PHP
λ php artisan tinker                                                   
Psy Shell v0.9.9 (PHP 7.2.19 — cli) by Justin Hileman                  
Keyword::all()                                                     
[!] Aliasing 'Keyword' to 'App\Models\Keyword' for this Tinker session.
=> Illuminate\Database\Eloquent\Collection {#3234                      
     all: [                                                            
       App\Models\Keyword {#3236                                       
         id: 11,                                                       
         created_at: "2019-11-11 21:07:47",                            
         updated_at: "2019-11-11 21:07:47",                            
         text: "aaa",                                                  
       },                                                              
       App\Models\Keyword {#3235                                       
         id: 12,                                                       
         created_at: "2019-11-11 21:07:53",                            
         updated_at: "2019-11-11 21:07:53",                            
         text: "bbb",                                                  
       },                                                              
       App\Models\Keyword {#3237                                       
         id: 13,                                                       
         created_at: "2019-11-11 21:07:58",                            
         updated_at: "2019-11-11 21:07:58",                            
         text: "ccc",                                                  
       },                                                              
     ],                                                                
   }                                                                   
Keyword::having('id', '=', 11)->delete();                          
=> 3                                                                   
Keyword::all()                                                     
=> Illuminate\Database\Eloquent\Collection {#3252                      
     all: [],                                                          
   }                                                                   
```

**Comment by mfn** [comment]
Interestingly, I tried this (but I'm on 5.8 and Postgres!) and I got an error:
> `Illuminate/Database/QueryException with message 'SQLSTATE[08P01]: <<Unknown error>>: 7 ERROR:  bind message supplies 1 parameters, but prepared statement "pdo_stmt_00000005" requires 0 (SQL: delete from "posts")'`

However:
- `having` is for `groupBy`
- `doesntHave` is something else (not related to having), rather it completes `has`
- in your case you just could have used `where()` instead of having, no?

**Comment by RomainMazB** [comment]
Hi @mfn ,
I could have accomplished it in many ways, my problem was solved with `doesntHave()` which looks IMO more readable than `where()` clause with a COUNT().

I reported the issue because I felt disappointed when `having('websites_count','=', 0)->get()` didn't returns the same rows as `having('websites_count','=', 0)->delete()` did.

Again my problem is solved, I'm not here to search for some kind of help, I just wanted to report an issue which may cause more trouble in other use cases.

**Comment by staudenmeir** [comment]
> I reported the issue because I felt disappointed when having('websites_count','=', 0)->get() didn't returns the same rows as having('websites_count','=', 0)->delete() did.

MySQL (and probably every other database) doesn't support `DELETE` queries with `HAVING` clauses.

**Comment by RomainMazB** [comment]
@staudenmeir Thanks for the link, but I don't think (maybe I'm totally wrong) this is the cause: the SQL generated by Laravel is `DELETE FROM keywords`.

I could have agreed your answer if SQL was `DELETE FROM keywords HAVING something` and MySQL would surely have reported to me an error.

Or maybe Laravel knows that the request will work so the framework modify it? In this case, an enhancement to throw an error should probably be envisaged.

**Comment by staudenmeir** [comment]
> Thanks for the link, but I don't think (maybe I'm totally wrong) this is the cause: the SQL generated by Laravel is DELETE FROM keywords.

My point was that even your `SELECT` query is only somewhat valid.

> Or maybe Laravel knows the request will not work so the framework modifies it?

Yes. The `HAVING` clause is not compiled because there is no use case for it in a `DELETE` query. Even if it would be valid, there's no `websites_count` column it could filter.

**Comment by RomainMazB** [comment]
> > Or maybe Laravel knows the request will not work so the framework modifies it?
> 
> Yes. The `HAVING` clause is not compiled because there is no use case for it in a `DELETE` query. Even if it would be valid, there's no `websites_count` column it could filter.

In this case, using `delete` with `having` should throw an alert, or compile the `DELETE` with `HAVING` clause so the database throws the error.

The facts are:
- `DELETE` with `HAVING` can't be accomplished in (any) database.
- Laravel doesn't mention there is an error but silently "modifies"(by ignoring `having`) what developers want to do.
- The database receives the "modified" but valid query, so it doesn't throw any error.

**Comment by driesvints** [comment]
> In this case, using delete with having should throw an alert, or compile the DELETE with HAVING clause so the database throws the error.

We could debate about the silent failure but that's more of a discussion for the ideas repo. At the moment this is just the way it's implemented. Feel free to open up an issue on the ideas repo or to open a PR for the master branch if you want to try to change the behavior.

Appreciating the report though! 👍
