### ISSUE TITLE
bad character in console!

### ISSUE THREAD

**Issue by Lablnet** [laravel/framework#30566]
- Laravel Version: 6.5.0
- PHP Version: 7.3.1
- Database Driver & Version: Mysql & 10.4.8
- Operating System: Windows 10

### Description:
When i run command
``` php artisan```
it show me following output with ` ?[32m6.5.0?[39m` bad character including
![image](https://user-images.githubusercontent.com/27757785/68660689-7cab8600-055b-11ea-86c0-26b0fdd7042d.png)

**Comment by driesvints** [comment]
Seems like a duplicate of https://github.com/laravel/framework/issues/30216

Have you tried updating the symfony component to the latest version? Or running `composer require symfony/console:4.3.4`?

**Comment by Lablnet** [comment]
> composer require symfony/console:4.3.4

Oh yeah fixed after running upgrading symfony console 
thanks
