### ISSUE TITLE
Made it possible suspend/resume specific observer during runtime

### ISSUE THREAD

**Issue by prodigy7** [laravel/framework#30567]
I tried a few things, but couldn't find a solution to my problem:

I am working on a software which handles many data sets. When a data set is processed, an observer is triggered, which calculates a value and calculates it into another table. That's okay so far.
In certain situations, however, we process a larger amount of data at once and here it would make sense to perform certain calculations only once at the end.
At the moment, the Observer is triggered at each data set, which leads to a longer delay. I know that I have the option to disable Observer completely. But this would not fit for our situation, because e.g. one observer documents a history and has to be triggered all the time, another observer performs a calculation and here it makes more sense to trigger it manually once at the end of the complete run.

It would be nice, suspend and resume somehow a observer. E.g. 
```
$model->suspendObserver('\App\Observers\MyObserver'); // suspend observer, is not triggerd next event
$model->resumeObserver('\App\Observers\MyObserver'); // resume observer operation
```
Optional a second parameter maybe limit suspend/resume to specific events.

In my own observers I can implement something check session for set suspend and handle it, but when I am using foreign packages, I have to build every time something special and can not use a package out of the box.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
