### ISSUE TITLE
SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint

### ISSUE THREAD

**Issue by modnar1226** [laravel/framework#30572]
- Laravel Version: 5.8
- PHP Version: 7+
- Database Driver & Version:
mysql
elasticssearch 7 
### Description:
can not add constraint to a table when the migration references a table that hasn't been created yet.

### Steps To Reproduce:
create account migration with following
    
    $table->unsignedBigInteger('org_id');
    $table->foreign('org_id')->references('id')->on('orgs');

then create a org migration with following

    $table->bigIncrements('id');

result:

    SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL: alter table `accounts` add constraint `accounts_org_id_foreign` foreign key (`org_id`) references `orgs` (`id`))

possible solution:

Add to documentation to verify the order of creation when adding foreign keys that the table with foreign key constraints must come after the parent table. It seems obvious after the fact but when updating migrations in a dev environment it was an easy thing to overlook.  

Also adding this to the error reporting as a note would be helpful too as it would be in our faces as soon as it happened.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
