### ISSUE TITLE
Errors from validation not structured as expected when using translations

### ISSUE THREAD

**Issue by MoogyG** [laravel/framework#30585]
- Laravel Version: 6.5.0
- PHP Version: 7.2.4
- Database Driver & Version: Mysql 5.7

### Description:

When a validation fails using a file upload with this constraint : 
```php
'document' => 'required|mimes:pdf,jpg,jpeg,gif,png|between:1,2000',
```

errors in session are stored like this :

```php
debug(\Session::get('errors'));
```
```php
ViewErrorBag {#2297 ▼
  #bags: array:1 [▼
    "default" => MessageBag {#2298 ▼
      #messages: array:1 [▼
        "document" => array:1 [▼
          0 => "The document must be between 1 and 2000 kilobytes."
        ]
      ]
      #format: ":message"
    }
  ]
}
```

but when I use translations in `resources/lang/en/validation.php` file :
```php
'custom' => [
        'document' => [
            'between' => [
                "file" => "My message overide",
            ],
        ],
    ],
```
Errors are stored like this :
```php
ViewErrorBag {#2298 ▼
  #bags: array:1 [▼
    "default" => MessageBag {#2299 ▼
      #messages: array:1 [▼
        "document" => array:1 [▼
          0 => array:1 [▼
            "file" => "My message overide"
          ]
        ]
      ]
      #format: ":message"
    }
  ]
}
```

Why `0` is not the key of `"My message overide"`?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by MoogyG** [comment]
For me it's a bug, I made a question to be kind..

**Comment by MoogyG** [comment]
Found solution, it needs to be write like this :
```
'custom' => [
        'document' => [
            'between' => "My message overide",
        ],
    ],
```
