### ISSUE TITLE
Migration function change has a weird behavior 

### ISSUE THREAD

**Issue by Legion112** [laravel/framework#30589]
- Laravel Version: v5.8.31
- PHP Version: 7.2.23
- Database Driver & Version:  5.7.28  MySQL Community Serve

### Steps To Reproduce:
I have a table 
```
+--------------+---------------------+------+-----+---------+----------------+
| Field        | Type                | Null | Key | Default | Extra          |
+--------------+---------------------+------+-----+---------+----------------+
| id           | bigint(20) unsigned | NO   | PRI | NULL    | auto_increment |
| status       | tinyint(1)          | YES  |     | NULL    |                |
+--------------+---------------------+------+-----+---------+----------------+
```

I have a migration 

```
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('sites', function (Blueprint $table) {
            $table->string('status')->change();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        /**
         * @todo rollback does not work without setting collation and charset to null
         * problems in doctrine
         * @see \Doctrine\DBAL\Platforms\MySqlPlatform.php:604
         * need to submit issue to doctrine
         */
        Schema::table('sites', function (Blueprint $table) {
            $table->boolean('status')->change();
        });
    }
```
After applying migration `php artisan migrate`
I do rollback  `php artisan migrate:rollback`

The SQL that rollback generates for me is 
```
ALTER TABLE sites CHANGE status status TINYINT(1) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`;
```  
This SQL is invalid. 

The desired behavior I want to get is `ALTER TABLE sites CHANGE status status TINYINT(1);`

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by Legion112** [comment]
We have updated to version 6.5

Issues still exist.

Maybe it is not related to Laravel itself but Doctrine but still I would like to use migration in the way I expect how they should work.

**Comment by driesvints** [comment]
@Legion112 think it's best you pick this up on Doctrine's end. We've had this issue before but it always boiled down that Doctrine didn't support this.

**Comment by nvahalik** [comment]
If anyone else finds this issue, it can be fixed by simply appending: 

    ->collation(null)->charset(null)

For example:

    $table->integer('program_type')->unsigned()->change(); // Will not work.

    $table->integer('program_type')->collation(null)->charset(null)->unsigned()->change(); // Will.
