### ISSUE TITLE
[6.x] Misspelling in release change log of Laravel 6.5.1

### ISSUE THREAD

**Issue by m-naderian** [laravel/framework#30587]
Unfortunately there's a misspelling in the [release page of Laravel 6.5.1](https://github.com/laravel/framework/releases/tag/v6.5.1
) which is highlighted in the attached picture.

![laravel release misspelling](https://user-images.githubusercontent.com/54891627/68827078-18510980-06b6-11ea-89ac-e88893bdcf6e.PNG)

Also it appears in Laravel Blog too.

![Capture](https://user-images.githubusercontent.com/54891627/68827262-90b7ca80-06b6-11ea-95d0-88d78de1f4a0.PNG)

**Comment by driesvints** [comment]
Feel free to open up a PR next time 👍

**Comment by brunogaspar** [comment]
@driesvints The typo is on the tag release notes https://github.com/laravel/framework/releases/tag/v6.5.1

Which is mentioned in one of the OP links..so sending a Pull Request is not really an option..

**Comment by driesvints** [comment]
Ah good point. Fixed. Thanks!
