### ISSUE TITLE
Space in .env does not throw an error

### ISSUE THREAD

**Issue by roni-estein** [laravel/framework#30586]
- Laravel Version: 6.5.1
- PHP Version: 7.3.5
- Database Driver & Version:
sqlite
### Description:
Having space space in the .env file produces a white screen.

### Steps To Reproduce:
In my case this key was the issue

MAIL_FROM_NAME=BROCK CORYDON PAC ADMIN

of course quotes fixed it. However, there was no error thrown at all simply a white screen. Had I not been the person who had just updated it, I would have been baffled for a while having never seen that issue before.

It should throw some sort of error or exception to the screen in a development environment, and at the very least a log.

Hope this helps someone, cheers and thanks.

**Comment by driesvints** [comment]
Just use quotes like you suggested:

    
MAIL_FROM_NAME="BROCK CORYDON PAC ADMIN"

**Comment by roni-estein** [comment]
Yeah, I wasn’t asking for the solution, I was pointing out it doesn’t throw an exception. Since laravel is all about developer experience, and not wasting time, you may want to throw one.

Is this monumentally hard to do? Would you accept a pr?

**Comment by driesvints** [comment]
@roni-estein Laravel uses a third party package for this so maybe check if they'd be interesting in adding this? https://github.com/vlucas/phpdotenv

**Comment by 36864** [comment]
>of course quotes fixed it. However, there was no error thrown at all simply a white screen. 

I just tested this by replacing every newline with a single space character. An error is logged to my apache error log:
```The environment file is invalid!
Failed to parse dotenv file due to unexpected whitespace. Failed at [...]```

Something that might be worth pointing out is that this outputs your environment values to the log file (in this case, that included database credentials)
