### ISSUE TITLE
Case insensitive search in json - translatable field 

### ISSUE THREAD

**Issue by kpapag** [laravel/framework#30583]
- Laravel Version: 5.8
- PHP Version: 7.3.5
- Database Driver & Version:
MySQL: 5.7.26
### Description:
I am unable to perform a case insensitive search through a controller in a translatable field. My issue is mostly when greek characters have accents.

**what i have already tried:**
say i search for a title containing the greek word "είμαι"

_this query works in pure sql_
`select * from table where UPPER(`title`->'$.el') LIKE '%ειμαι%' COLLATE utf8mb4_unicode_ci;`

notice this brings result, despite the fact i searched for "ειμαι" (without the accent). And this is what i try to achieve.

### Steps To Reproduce:
`$var= MyModel::with('relation')
            ->when($title, function ($query) use ($title) {
                $title = '%' . Str::upper($title) . '%';
                return $query->whereRaw("UPPER(`title`->'$.".'el'."') LIKE ? COLLATE utf8mb4_unicode_ci", [$title]);
            })
            ->paginate(5);`

gives the error

SQLSTATE[42000]: Syntax error or access violation: 1253 COLLATION 'utf8mb4_unicode_ci' is not valid for CHARACTER SET 'binary' (SQL: select count(*) as aggregate from `table` where UPPER(`title`->'$.el') LIKE %ΕΊΝΑΙ% COLLATE utf8mb4_unicode_ci.

show variables like '%collation%';
returns

'collation_connection', 'utf8mb4_general_ci'
'collation_database', 'utf8mb4_unicode_ci'
'collation_server', 'utf8mb4_unicode_ci'

show variables like '%char%';
returns

'character_set_client', 'utf8mb4'
'character_set_connection', 'utf8mb4'
'character_set_database', 'utf8mb4'
'character_set_filesystem', 'binary'
'character_set_results', 'utf8mb4'
'character_set_server', 'utf8mb4'
'character_set_system', 'utf8'
'character_sets_dir', 'c:\\wamp64\\bin\\mysql\\mysql5.7.26\\share\\charsets\\'

**(note that this is a development local machine)**

config/database.php regarding mysql

`'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ]`

i have searched for hours online without any luck. I am aware that due to my collations, had this field been a text instead of json, i would not face any problem but my project demands the use of translatable fields so i am in need of any help.

Thank you for your time.

**Comment by staudenmeir** [comment]
You need to convert the JSON string, not the binding:

```php
$query->whereRaw("UPPER(title->'$.".'el'."') COLLATE utf8mb4_unicode_ci LIKE ?", [$title]);
```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by kpapag** [comment]
@staudenmeir actually gave the simple solution i needed. God bless ya mate, thanks a lot.
