### ISSUE TITLE
Undocumented breaking change in Mailer when upgrading from 5.5 to 5.6+

### ISSUE THREAD

**Issue by lucasvdh** [laravel/framework#30592]
- Laravel Version: 6.0.4
- PHP Version: 7.2.21
- Database Driver & Version: not applicable

### Description:
I am required to keep a record of all email messages which have been sent. It used to be that I could use the callback in the mailer _(`Illuminate\Mail\Mailer`)_ to fetch the raw content of an email message _(`Illuminate\Mail\Message`)_ so I could persist it to storage.

In Laravel 5.5 the callback given to the `Mailer@send` is ran **after** the body is set on the  message.

Since Laravel 5.6 the callback given to the `Mailer@send` is ran **before** the body is set on the message.

This causes the body of the message to not be present in the callback. There is no documentation in the [5.6 upgrade guide](https://laravel.com/docs/5.6/upgrade) about this breaking change that changes the callback from a "after"-callback to a "before"-callback.

### Steps To Reproduce:
1. have a Laravel 5.5 project
2. send a mail
3. validate that the email body is present if you call `->toString()` on the `$message` in the callback of `Mailer@send`
4. upgrade to Laravel 5.6+
5. send a mail
6. call `->toString()` on the `$message` in the callback of `Mailer@send`
7. only the header and attachments are returned

### Misc
This issue has previously been reported here: https://github.com/laravel/ideas/issues/1646
This issue regards this PR: https://github.com/laravel/framework/pull/22995
This issue regards this specific commit: https://github.com/laravel/framework/pull/22995/commits/0cd889942c7dfd17c25551aab681eb6d9a96182a

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by petermein** [comment]
The not supported comment is great, but then there should be an upgrade guide from 5.5 to 6.x right?

**Comment by lucasvdh** [comment]
@driesvints

**Comment by driesvints** [comment]
@petermein there's an upgrade guide for each version between 5.5 and 6.0. You're always free to send in a PR to one of those.

@lucasvdh but you mention

> have a Laravel 5.5 project

Which we don't support anymore. So I didn't understand why you said that 6.0.4 in your issue template. If there's something missing from an upgrade guide, feel free to send in a pr to the docs: https://github.com/laravel/docs/

**Comment by 36864** [comment]
>There is no documentation in the 5.6 upgrade guide about this breaking change that changes the callback from a "after"-callback to a "before"-callback.

While the upgrade guide could use an itemized index, I'd expect anyone who has trouble with mails after upgrading to ctrl+f the word mail: https://github.com/laravel/docs/blob/5.6/upgrade.md#mail

>Mail
withSwiftMessage Callbacks
>
>In previous releases of Laravel, Swift Messages customization callbacks registered using withSwiftMessage were called after the content was already encoded and added to the message. These callbacks are now called before the content is added, which allows you to customize the encoding or other message options as needed.
