### ISSUE TITLE
Could not change notification event name when broadcasting

### ISSUE THREAD

**Issue by pkarczmarczyk94** [laravel/framework#30599]
- Laravel Version: 6.5.1
- PHP Version: 7.3.9
- Database Driver & Version: n/a

### Description:
When trying to change notification event name with method `broadcastType` it has no effect. There is a method `broadcastType` in `\Illuminate\Notifications\Events\BroadcastNotificationCreated` but it does not change event name (I can see it in laravel-echo-server logs). In some point there was a method named 'broadcastAs' but it was changed to `channelName` ( `\Illuminate\Notifications\Events\BroadcastNotificationCreated`). 
Commit where it was changed: [4227bd7](https://github.com/laravel/framework/commit/4227bd78d5ab2743e694bfd34784a5ccced20bef#diff-ed9dd116d2004b188b86268332142ed1)

In `\Illuminate\Broadcasting\BroadcastEvent::handle` you still use `broadcastAs`  to set event name.

So there are two ways either add `broadcastAs` method to `\Illuminate\Notifications\Events\BroadcastNotificationCreated` class that can be later overwritten in notification class or change `broadcastAs` to `broadcastType` in `\Illuminate\Broadcasting\BroadcastEvent::handle`.

For now, I do not see any way to change notification event's name on broadcasting channel.

There is also an issue about it [#202](https://github.com/laravel/ideas/issues/202)

@taylorotwell

**Comment by driesvints** [comment]
Closing because the PR was rejected.
