### ISSUE TITLE
 invalid signature on email verification.

### ISSUE THREAD

**Issue by GIVasco** [laravel/framework#30594]
- Laravel Version: 5.8.15
- PHP Version: 7.1
- Database Driver & Version: mariadb

### Description:

Hello, i'm working on Laravel 5.8.15 and i have the same error !

I did set the .env file
APP_ENV=production
APP_URL=https://domain.co/
APP_USE_HTTPS=true

in the AppServiceProvider
public function boot(UrlGenerator $url)
{
URL::forceScheme('https');
}

In web.php and api.php
if (App::environment('production')) {
URL::forceScheme('https');
}

In UrlGentator file:
$url = str_replace("http://","https://", $url);

and in the TrustProxies file
protected $proxies = '*';

but I still getting the same error (403 | Invalid signature.) on the email verification!
someone can helpme ?

The lastes pages that i visit :
https://github.com/laravel/framework/issues/26930
https://github.com/laravel/framework/issues/25501
https://stackoverflow.com/questions/52917152/laravel-5-7-email-verification-throws-403
https://stackoverflow.com/questions/52525958/signed-route-for-email-verification-does-not-pass-signature-validation
https://laracasts.com/discuss/channels/laravel/hitting-403-page-when-clicking-verify-link-in-email-using-new-laravel-verification-57
https://laracasts.com/discuss/channels/laravel/email-verification-403-invalid-signature?page=0#reply=553418

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by GIVasco** [comment]
??? 
https://laravel.com/docs/5.8/releases#support-policy
https://laravel.com/docs/6.x/releases#support-policy

I'm using Laravel in the 5.8 version ! What is the problem ???

**Comment by devcircus** [comment]
Just confirm the issue on 6.0 and submit an issue for that version. New features and bug fixes are closed on 5.8.

**Comment by GIVasco** [comment]
yes :/ i see it now ! thnks guys !

**Comment by jdoubleu** [comment]
In my case the signature validation fails because `request->query()` returns the current relative path as query param `q` in https://github.com/laravel/framework/blob/6.x/src/Illuminate/Routing/UrlGenerator.php#L383.

**Comment by hirenkeraliya** [comment]
> In my case the signature validation fails because `request->query()` returns the current relative path as query param `q` in https://github.com/laravel/framework/blob/6.x/src/Illuminate/Routing/UrlGenerator.php#L383.
> 
> However this is not an issue in Laravel. Somehow my webserver or PHP added this `q` param to the global `$_GET` array.

If you are using an Nginx then in your Nginx configuration please change this line
`try_files $uri $uri/ /index.php?q=$uri&$args;` to  `try_files $uri $uri/ /index.php?$query_string;`
At the
`/etc/nginx/sites-available/[Project Name]`

**Comment by Victorlerner** [comment]
Thank you hirenkeraliya!
