### ISSUE TITLE
Collection 'contains' method returns true on non-existent values

### ISSUE THREAD

**Issue by ProgrammerZ** [laravel/framework#30595]
- Laravel Version: 6.4.1
- PHP Version: 7.2.22

### Description:
Collection 'contains' method returns true on non-existent values.

### Steps To Reproduce:
Originally I have json, but tested with pure array as well.

```
$input = '{"id":"Start123456enD","object":"payment_intent","amount":200,"amount_capturable":0,"amount_received":0,"application":null}'

$collectionData = collect(json_decode($input, true));

dd($collectionData, $collectionData->contains('payment_NON-EXISTENT_intent')); 
```

Output

```
Collection {#321 ▼
  #items: array:10 [▼
    "id" => "Start123456enD"
    "object" => "payment_intent"
    "amount" => 200
    "amount_capturable" => 0
    "amount_received" => 0
    "application" => null
  ]
}


true
```

also is returns:
`->contains('Start123456enD'))                   // true  (as expected)`
`->contains('ssssssssStart123456enD'))       // true`
`->contains('11111Start123456enD'));         // false`
`->contains('StartXXXXXXXX123456enD'));         // true`

It does work correctly with `containsStrict()`

**Comment by mfn** [comment]
> It does work correctly with `containsStrict()`

That's your answer. `contains` vs. `containsStrict` is the same as `in_array(…,…)` vs. `in_array(…,…, true)`.

Not sure what you are asking for?

**Comment by staudenmeir** [comment]
With loose comparison, PHP considers `0` equal to any string that doesn't start with a digit.

**Comment by mfn** [comment]
👍 

In a perfect would, `contains` would actually be the strict version and for those who need it, we would have a `conaintsLoose` or something :p

**Comment by ProgrammerZ** [comment]
@staudenmeir Thank you.
Pardon me, I was not aware of this.  It makes perfect sense now.
