### ISSUE TITLE
Eloquent::findOFail($id) Returns A Collection Instance 

### ISSUE THREAD

**Issue by tobiasthaden** [laravel/framework#30606]
- Laravel Version: 6.5.1
- PHP Version: 7.3.9
- Database Driver & Version: MySql 5.7.27

### Description:
`Eloquent::findOrFail($id) ` returns a ` Eloquent ` instance.

But if i build something like:

```
public static function fromEncodedId($encodedId)
{
    $id = decode_the_id($encodedId);

    return static::findOrFail($id);
}
```
An `EloquentCollection` instance will be returned.

### Steps To Reproduce:

Build a wrapper method around `findOrFail ` and call it.

```
public static function fromId($id)
{
    return static::findOrFail($id);
}
```

**Comment by tobiasthaden** [comment]
I just noticed that `Builder::findOrFail()`can return an `EloquentCollection`, so this might be expected behaviour.

**Comment by tobiasthaden** [comment]
@driesvints Should in this case `findOrFail` return the model instead of an `EloquentCollection` with one item?

**Comment by mfn** [comment]
Your decoded was likely something array-ish?
