### ISSUE TITLE
Subquery Selects Advanced Subqueries

### ISSUE THREAD

**Issue by SagarNaliyapara** [laravel/framework#30601]
- Laravel Version: 6.5.1
- PHP Version: 7.3.10
- Database Driver & Version: MySQL 8

I'm trying to implement this - https://laravel.com/docs/6.x/eloquent#advanced-subqueries
### Steps To Reproduce:
```
use App\Destination;
use App\Flight;

return Destination::addSelect(['last_flight' => Flight::select('name')
    ->whereColumn('destination_id', 'destinations.id')
    ->orderBy('arrived_at', 'desc')
    ->limit(1)
])->get();
```
When you define custom attribute `name` in Flight model, it does not return that custom value it returns straight from database

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
