### ISSUE TITLE
subdomain routes, become new domain

### ISSUE THREAD

**Issue by linducip2208** [laravel/framework#30609]
hi
 i want to ask.
laravel subdomain routes, like domain1.laravel.com become domain1.com

this is possible?

thanks
lindu

**Comment by tisuchi** [comment]
I guess it's not possible. @linducip2208

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
