### ISSUE TITLE
Dispatching to queue always chooses the default connection

### ISSUE THREAD

**Issue by rtroost** [laravel/framework#30615]
- Laravel Version: 5.8.35
- PHP Version: 7.3
- Database Driver & Version: MySQL 8

### Description:
I have an application running many different kinds of jobs that run for several seconds to an hour. This requires me to have two seperate queue connection due to retry_after being bound to a connection instead of a queue (even though they both use Redis, which is annoying but not the issue right now). One connection has a retry_after of 600 seconds, the other 3600 seconds (or one hour). My jobs implement `ShouldQueue` and use traits `Queueable, SerializesModels, Dispatchable, InteractsWithQueue`. 

Now for the problem. I created a `TestJob` that sleeps for 900 seconds to make sure we pass the retry_after limit. When I try to dispatch a job on a specific connection using:
`dispatch(new Somejob)->onConnection('redis-long-run')`
or as I used to do it previously in the constructor of the job (which always used to work):
```
public function __construct() {
    $this->onConnection('redis-long-run');
}
```
The job gets picked up by the queue worker, it runs for 600 seconds after which the worker restarts job, notices it has already run once and fails it. 300 seconds later, the job processes successfully. If my worker allow for more than one try, the duplicate jobs will run in parallel for 300 seconds.

In my test job I'm also printing out `$this->connection` which does show the correct connection being used so my guess is the broadcaster is just ignoring it completely.

### Steps To Reproduce:
1. Set your queue driver to Redis.
2. Create two different Redis connections in queue.php, one named `redis` having a retry_after of 600, the other named `redis-long-run` with a retry_after of 3600. In my case they also have different queue's, though I'm not sure this is required for this test.
3. Create a little command to dispatch our test job three times
```
<?php

namespace App\Console\Commands;

use App\Jobs\TestFifteen;
use Illuminate\Console\Command;

class TestCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'test:fifteen';

    /**
     * Create a new command instance.
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return void
     */
    public function handle()
    {
        for ($i = 1; $i <= 3; $i++) {
            dispatch(new TestFifteen($i))->onConnection('redis-long-run');
        }
    }
}
```
4. Create the test job
```
<?php

namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use function sleep;
use function var_dump;

class TestFifteen implements ShouldQueue
{
    use Queueable, SerializesModels, Dispatchable, InteractsWithQueue;

    private $testNumber;

    public function __construct($testNumber)
    {
        $this->onConnection('redis-long-run');
        $this->testNumber = $testNumber;
    }

    public function handle()
    {
        var_dump("Started test job {$this->testNumber} on connection {$this->connection}");
        sleep(900);
        var_dump("Finished test job {$this->testNumber} on connection {$this->connection}");
    }
}
```
5. Run your queue workers
6. Execute the artisan command `php artisan test:fifteen`

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by rtroost** [comment]
Hi @driesvints. I just upgraded to (framework) version 6.5.1 and the behavior is exactly the same, unfortunately.

**Comment by driesvints** [comment]
> dispatch(new TestFifteen($i))->onConnection('redis-long-run');

This dispatches the job first and only sets the connection afterwards. 

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
