### ISSUE TITLE
Database Query Builder Not Fast Enough To Get Data Inside Foreach Loop

### ISSUE THREAD

**Issue by Elvis254** [laravel/framework#30618]
- Laravel Version: 6
- PHP Version: 7
- Database Driver & Version: MySql

The following function gets all user profiles from the database but they do not have all information which is contained in other tables:

`public function getAll($offset)
    {
        try {
            $new_profiles_data = [];
            
            $profiles_data = $this->profiles->where([
                ['status', 1],
                ['deleted', 0]
            ])->orderBy('profile_id', 'desc')->offset($offset)->limit(60)->get();

            foreach ($profiles_data as $profile) {
                $new_profiles_data[] = [
                    'profile_id' => $profile->profile_id,
                    'avatar' => ($profile->avatar != NULL ? $this->commons->uploads_path().$profile->avatar : 'assets/images/avatar.png'),
                    'username' => $this->commons->render_string($this->getUser($profile->user_id, 'keyword')),
                    'phonenumber' => $this->getUser($profile->user_id, 'phonenumber'),
                    'coverletter' => $this->commons->render_string($profile->coverletter),
                    'town' => $this->commons->render_string($profile->town),
                    'county' => $this->getCounty($profile->county_id)
                ];
            }

            if ($new_profiles_data) {
                return $new_profiles_data;
            } else {
                return false;
            }
        } catch (\Exception $e) {
            $this->logger->error('Error in Profiles Module Class: ' . $e);
        }
    }`

The functions are:

`protected function getUser($user_id, $value)
    {
        try {
            $user_data = $this->users->where('user_id', $user_id)->value($value);

            if ($user_data) {
                return $user_data;
            } else {
                return false;
            }
        } catch (\Exception $e) {
            $this->logger->error('Error in Profiles Module Class: ' . $e);
        }
    }`

`protected function getCategory($category_id)
    {
        try {
            $category_data = $this->categories->where('category_id', $category_id)->value('title');

            if ($category_data) {
                return $category_data;
            } else {
                return false;
            }
        } catch (\Exception $e) {
            $this->logger->error('Error in Profiles Module Class: ' . $e);
        }
    }`

`protected function getCounty($county_id)
    {
        try {
            $county_data = $this->counties->where('county_id', $county_id)->value('title');

            if ($county_data) {
                return $county_data;
            } else {
                return false;
            }
        } catch (\Exception $e) {
            $this->logger->error('Error in Profiles Module Class: ' . $e);
        }
    }`

Please, help out. It seems the query builder doesn't fetch any data in between itterations in the foreach loop. I don't know why but either its not fast enough or gets aborted.

**Comment by mfn** [comment]
Please don't ignore the issue template:
![image](https://user-images.githubusercontent.com/87493/69082712-f4d4e880-0a40-11ea-9165-37a43e74a447.png)

=> https://laravel.com/docs/6.x/contributions#support-questions

Specifically, you need to learn about [Eager Loading](https://laravel.com/docs/5.8/eloquent-relationships#eager-loading) to avoid the classical n+1 problem.
