### ISSUE TITLE
Error 404 without any header

### ISSUE THREAD

**Issue by tiaguinhor** [laravel/framework#30613]
- Laravel Version: 5+
- PHP Version: 7+

### Description:
I was just trying to replicate the abort 404 with a header:
` abort(404, 'testing', ['White-Label' => true]);`

and I found something curious. Is there any reason why the 404 is not showing the Header like all the others?

**Application.php**
```public function abort($code, $message = '', array $headers = [])
    {
        if ($code == 404) {
            throw new NotFoundHttpException($message);
        }

        throw new HttpException($code, $message, null, $headers);
 }
```

Why don't do like this?

```public function abort($code, $message = '', array $headers = [])
    {
        if ($code == 404) {
            throw new NotFoundHttpException($message, null, $code, $headers);
        }

        throw new HttpException($code, $message, null, $headers);
    }
```

Thanks in advance, cheers!

**Comment by brunogaspar** [comment]
Probably an oversight.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
