### ISSUE TITLE
LengthAwarePaginator returns wrong array of $elements in links()

### ISSUE THREAD

**Issue by pavelpolitaev** [laravel/framework#30617]
- Laravel Version:  6.1.0
- PHP Version: 7.2.5
- Database Driver & Version:

### Description:
LengthAwarePaginator returns wrong array of $elements in links()

### Steps To Reproduce:
`$collection = new Collection();`
`$collection->push([]);`
`$paginator = new LengthAwarePaginator($collection, 10, 1, 3);`
`$paginator->onEachSide = 1;`

`$paginator->links()` in `$elements` I got doubles `2 => "/?page=2"`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
