### ISSUE TITLE
Supervisor process access the active queue.

### ISSUE THREAD

**Issue by Muthukumar-Kannan** [laravel/framework#30614]
- Laravel Version: 5.7
- PHP Version: 7.2
- Database Driver & Version:

Description:
In here I added my supervisor configuration.

```
command=php artisan queue:work --tries=1 --env=local
directory=/var/www/html/dev/
stdout_logfile=/var/www/html/dev/storage/logs/myqueue_supervisord.log
redirect_stderr=true
numprocs=2
process_name=%(program_name)s_%(process_num)02d
autostart=true
autorestart=true 
```
when I dispatch the queue from the laravel. it running properly after some it throws the to many attempts exception message. because I mentioned the two supervisor process here. in the initial time, the first process runs the queue. after some time the second process tries to run that same queue.
I think this is the reason for this issue. please help me to solve the above issue.

Steps To Reproduce:
1. Configure the supervisor with Two processes.
2. Then Dispatch the one database queue (Some Time Taking Process).
3. Then Check the Queue Failed Event.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by Muthukumar-Kannan** [comment]
Hi, @driesvints 
The same issue also happens in laravel 6.x.

**Comment by driesvints** [comment]
Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
