### ISSUE TITLE
EloquentCollection->intersect misbehaves when called with null argument

### ISSUE THREAD

**Issue by jonaslm** [laravel/framework#30626]
- Laravel Version: 6.5.1
- PHP Version: 7.3
- Database Driver & Version: N/A

### Description:

When calling `$collection->intersect(null)` on an Eloquent Collection the whole `$collection` is returned. I would expect an error or, possibly, an empty collection to be returned. Note that doing the same thing on a regular base collection returns an empty collection.

We had this happen, causing silent errors (we called intersect with a nonexistant relation as argument, which gets returned as null).

### Steps To Reproduce:

Assuming you have an Eloquent Collection `$eloquentCollection` that isn't empty, simply call
```
$eloquentCollection->intersect(null);
```

The entire collection will be returned. Expected behavior would be an error or, possibly, an empty collection. Again, note that doing the same thing on a base collection returns an empty collection.

**Comment by driesvints** [comment]
Tested this and confirmed. This indeed seems like unwanted behavior. Welcoming prs for this.

**Comment by ahinkle** [comment]
Hmm, am I missing something here? `$collection->intersect(null)` returns an empty collection.

https://github.com/laravel/framework/blob/1bbe5528568555d597582fdbec73e31f8a818dbc/tests/Support/SupportCollectionTest.php#L1151-L1158

https://github.com/laravel/framework/blob/1bbe5528568555d597582fdbec73e31f8a818dbc/tests/Support/SupportCollectionTest.php#L1160-L1167

**Comment by if4lcon** [comment]
@ahinkle this bug only occurs on Eloquent collection
