### ISSUE TITLE
[7.x] Add Job typehints in worker

### ISSUE THREAD

**Issue by GrahamCampbell** [laravel/framework#30622]
Extracted from @driesvints's comments in https://github.com/laravel/framework/pull/30610.

**Comment by driesvints** [comment]
Let's not create issues for this. Feel free to send in when you have some time.

**Comment by GrahamCampbell** [comment]
The issue allows me to track this task. Otherwise, it is highly likely that I will forget to do it.

**Comment by driesvints** [comment]
@GrahamCampbell feel free to open one in the ideas repo.
