### ISSUE TITLE
Mailgun endpoint hardcoded. 

### ISSUE THREAD

**Issue by saffabook** [laravel/framework#30623]
Please click this [laravel file location](https://github.com/laravel/framework/blob/6.x/src/Illuminate/Mail/Transport/MailgunTransport.php) which is the MailgunTransport.php file and look at line 51, you will see 
`
$this->endpoint = $endpoint ?? 'api.mailgun.net';  `

Can the url ie (api.mailgun.net) be changed to allow an .env parameter?

This will allow for any kind of api endpoint that mailgun decides to use or even changes. 
They have  a new **'api.eu.mailgun.net'** endpoint so this issue might crop up a bit. 

Best regards.

**Comment by NEGits** [comment]
You can, in fact, change this parameter in your .env. For details see the docs: https://laravel.com/docs/6.x/mail#driver-prerequisites

**Comment by saffabook** [comment]
Yes indeed. How silly of me. Thanks for that.
