### ISSUE TITLE
Debug Mode is not working in laravel on different environment

### ISSUE THREAD

**Issue by hariprasath-yadav** [laravel/framework#30634]
- Laravel Version: 6.2.0
- PHP Version: 7.2.4
- Apache 2.4

### Description:
If I use the below-given lines in the .env file, debugging is working

```
APP_ENV=local
APP_DEBUG=true
```
But if I use

```
APP_ENV=test
APP_DEBUG=true
```
debugging is not working

If I change the `App_Env `value from **local** to any other value debugging is not working, I can't use local as `App_Env `value at all times, because I use this same application in more than one system for dev, test, and production. some functionalities in the application are differs based on the environment.

I want to debug on both dev and test application systems.

**Comment by Keirul** [comment]
Pretty sure your config is being cached somewhere.
Or a server configuration.

Can't reproduce.

**Comment by Shohan494** [comment]
Try clearing your application cache with - 
`php artisan cache:clear
php artisan config:cache 
`  
Then give it a try..

**Comment by hariprasath-yadav** [comment]
Yes I did even though it's not working

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by hariprasath-yadav** [comment]
Thank You very much

**Comment by sousadgaspar** [comment]
I used 
php artisan cache:clear
php artisan config:cache

and it solved the issue.

**Comment by joydeep-bhowmik** [comment]
this issue occurred to me in laravel 10 ...any solutiuon yet?
