### ISSUE TITLE
Fake file creation fails

### ISSUE THREAD

**Issue by vroomfondle** [laravel/framework#30641]
- Laravel Version: 6.5.2
- PHP Version: 7.3
- Database Driver & Version:
n/a

### Description:

In our tests we create a fake file:

```
        use Illuminate\Http\UploadedFile;
        $uploadedFile = UploadedFile::fake()->create('foo.docx', '20');
```

This causes an error:

```
ErrorException : file_put_contents() expects parameter 1 to be a valid path, resource given
 /var/www/api/vendor/laravel/framework/src/Illuminate/Http/Testing/FileFactory.php:21
 /var/www/api/tests/Api/v2/File/Controllers/FileControllerTest.php:42
```

I believe the bug was introduced in https://github.com/laravel/framework/commit/181db51595d546cbd24b3fac0cb276255e147286

The return value of `tmpfile()` is being passed to `file_put_contents()`. However, `tmpfile()` returns a resource, whereas `file_put_contents()` expects a string containing a path.

### Steps To Reproduce:

```
        use Illuminate\Http\UploadedFile;
        $uploadedFile = UploadedFile::fake()->create('foo.docx', '20');
```

**Comment by vroomfondle** [comment]
For now we can "work around" the problem by just passing the number of kilobytes as an integer (which is probably what the developer who wrote our test intended anyway) but I thought I should flag this up.

**Comment by driesvints** [comment]
Bit torn on this being a bug or not since the docblock clearly marked it that you should pass an int. I think I'm gonna close this up as the current api was just expanded rather than changed. Thanks for reporting this though.

**Comment by vroomfondle** [comment]
Well, okay, but it seems odd to me that the call to file_put_contents() is there at all, given that it will never succeed. It's a useless line of code.

We've worked around the problem in our code so in future we'll just remember to always pass an int.

**Comment by driesvints** [comment]
@vroomfondle ah I misunderstood the actual problem. Thanks for mentioning this. We'll look into it 👍

**Comment by driesvints** [comment]
Seems like this is already fixed in https://github.com/laravel/framework/pull/30632. Will be good for the next release.
