### ISSUE TITLE
composer create-project --prefer-dist laravel/laravel blog

### ISSUE THREAD

**Issue by ramoty** [laravel/framework#30650]
- Laravel Version: 6.5.2
- PHP Version: 7.2.0
- Database Driver & Version:

### Description:
 ErrorException  : Return value of "Illuminate\Foundation\Console\PackageDiscoverCommand::execute()" should always be of the type int since Symfony 4.4, NULL returned.

  at C:\Projetos\hemaeducacao\vendor\symfony\console\Command\Command.php:258
    254|         } else {
    255|             $statusCode = $this->execute($input, $output);
    256|
    257|             if (!\is_int($statusCode)) {
  > 258|                 @trigger_error(sprintf('Return value of "%s::execute()" should always be of the type int since Symfony 4.4, %s returned.', \get_class($this), \gettype($statusCode)), E_USER_DEPRECATED);
    259|             }
    260|         }
    261|
    262|         return is_numeric($statusCode) ? (int) $statusCode : 0;

  Exception trace:

  1   trigger_error("Return value of "Illuminate\Foundation\Console\PackageDiscoverCommand::execute()" should always be of the type int since Symfony 4.4, NULL returned.")
      C:\Projetos\hemaeducacao\vendor\symfony\console\Command\Command.php:258

  2   Symfony\Component\Console\Command\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
      C:\Projetos\hemaeducacao\vendor\laravel\framework\src\Illuminate\Console\Command.php:189

  Please use the argument -v to see more details.
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

**Comment by ahinkle** [comment]
Works for me. Clear your composer cache and try again.
