### ISSUE TITLE
“file does not exist or is not readable” in laravel while the image has been uploaded successfully

### ISSUE THREAD

**Issue by tihootech** [laravel/framework#30664]
- Laravel Version:6.4.0
- PHP Version: 7.3.11

Here is the code in my project, in `BlogController.php` file and in `store` method :
```
public function store(Request $request)
    {
        $data = self::validate_and_upload($request);
        Blog::create($data);
        return redirect()->route('blog.index')->withMessage(__('CHANGES_MADE_SUCCESSFULLY'));
    }
```

`validate_and_upload()` method, validates incoming data in request and, uploads files from request into storage folder and finally returns an array. When `Blog::create($data);` is executed I face following error:
![image](https://user-images.githubusercontent.com/42317059/69473368-cf413980-0dc8-11ea-999f-0537b6015314.png)

_The "C:\xampp\tmp\php534B.tmp" file does not exist or is not readable._
This error is so confusing and even though file is successfully uploaded, it made me think that error is related to file upload process.
After I wrote following code in store method:
```
try {
  Blog::create($data);
} catch (\Exception $e) {
  dd($e);
}
```
and dumped `$e` I realized the actual error is something else.
![MK4Vp](https://user-images.githubusercontent.com/42317059/69473412-7b832000-0dc9-11ea-936d-7fc171044635.png)
The actual error was "_Field 'author_type' doesn't have a default value_", while Laravel showed me an unrelated error:  "The "_C:\xampp\tmp\php534B.tmp" file does not exist or is not readable._"

after I fixed the actual error problem was solved.

The problem is, this error page is so confusing and took me hours to find out the actual error. I thought this is happened only for me, but I saw a question on stackoverflow which proves it has happened for many Users. [This is the link to stackoverflow question](https://stackoverflow.com/questions/58414093/how-to-solve-file-does-not-exist-or-is-not-readable-in-laravel-while-the-image)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
