### ISSUE TITLE
Migration default() doesn't escape apostrophe

### ISSUE THREAD

**Issue by LinusCDE** [laravel/framework#30674]
- Laravel Version: 6.5.2
- PHP Version: 7.3.11-1
- Database Driver & Version:
MySQL
DB: MariaDB 15.1

### Description:
The default specification while creating a new table with a string column, doesn't escape the apostrophe (') character.  
It just gets passed along which makes the query fail, since the string is already enclosed in them.

Example
```php
public function up()
{
    Schema::create('users', function (Blueprint $table) {
         // ...
        $table->string('status', 255)->default("Hi. I'm using this messenger!");
        // ...
    });
}
```

### Steps To Reproduce:
- Create a migration
- Add a string column
- Select a default with apostrophe in it: `->default("Let's fail!")`
- Run `php artisan migrate`

**EDIT**: Layout improvements

**Comment by driesvints** [comment]
Just escape it yourself:

```
$table->string('status', 255)->default("Hi. I\'m using this messenger!");
```
