### ISSUE TITLE
Double Response/ Exception On RuntimeException For No application encryption key

### ISSUE THREAD

**Issue by bobbyaxe61** [laravel/framework#30678]
- Laravel Version: 5.8.35
- PHP Version: 7.1.23
- Database Driver & Version: 10.4.6-MariaDB

### Description:
i received double responses when i removed my application key and ran the application and visited a general path as "/" which was supposed to return the *welcome.blade.php* page

### Steps To Reproduce:

Create a new laravel project

````
    composer create-project laravel/laravel "project-name"
    cd project-name
    nano .env
````

Delete the application key if any has been set 

````
    APP_KEY=
````

save the .env file 
go to the Handler.php file and add the following

````
    cd App\Exceptions
    nano Handler.php
````

Add the following to the render function

````
    /**
     * Render an exception into an HTTP response.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Exception  $exception
     * @return \Illuminate\Http\Response
     */
    public function render($request, Exception $exception)
    {
        // Thrown when an exception occurs.
        if ($exception instanceof Exception) {
            return response()->json('okay', 500);
        }

        return parent::render($request, $exception);
    }
````

Then run on your browser visit http://127.0.0.1:8000/ or http://serving_address/
You should receive two json response instead of one.

Yes i understand that this is not an issue of such as the application key must be set to use laravel i am only concerned about the exception handling.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
