### ISSUE TITLE
laravel test "remembers" api_token authentication for unauthenticated followup request 

### ISSUE THREAD

**Issue by davewood** [laravel/framework#30677]
- Laravel Version: 6.0.4
- PHP Version: 7.3.9
- Database Driver & Version: postgres 11

### Description:

I see this behaviour only with the laravel test system, cannot reproduce when i make the same sequence of requests with curl or browser.

1) get('/api/foo?api_token='.$wrong_token, 401) // ok ... 401 
2) get('/api/foo?api_token='.$correct_token, 200) // ok ... 200 
3) get('/api/foo?api_token='.$wrong_token, 401) // NOTOK ... app returns 200 

if i make the same requests with curl from a remote host 

1) curl -X GET -H "Content-type: application/json" -H "Accept: application/json" http://localhost:8000/api/users?api_token=$wrong_token // ok ... 401 
2) curl -X GET -H "Content-type: application/json" -H "Accept: application/json" http://localhost:8000/api/users?api_token=$correct_token // ok ... 201 
3) curl -X GET -H "Content-type: application/json" -H "Accept: application/json" http://localhost:8000/api/users?api_token=$wrong_token // ok ... 401 

why does the laravel test environment behaviour differ and "remember" the authentication?

### Steps To Reproduce:

```
namespace Tests\Unit;
    
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;
use App\User;
//(...)
    public function _get($url, $status = 200) {
        $res = $this->json('GET', $url);
        $res->assertStatus($status);
        return $res;
    }
//(...)
        $res = $this->_get('/api/users?api_token=wrong_token', 401);
        $res = $this->_get('/api/users?api_token='.$api_token, 200);
        $res = $this->_get('/api/users?api_token=wrong_token', 401); 

There was 1 failure:

1) Tests\Unit\UserTest::testBasic
Expected status code 401 but received 200.
Failed asserting that false is true.

/home/ratis/ratis-api/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestResponse.php:151
/home/ratis/ratis-api/tests/Unit/UserTest.php:14
/home/ratis/ratis-api/tests/Unit/UserTest.php:21
/home/ratis/ratis-api/tests/Unit/UserTest.php:76
```

```
# routes/api.php
Route::namespace('Api')->group(function () {
    Route::post('/users/register', 'UserController@register');
    Route::post('/users/login', 'UserController@login');
});
Route::middleware('auth:api')->group(function () {
  Route::namespace('Api')->group(function () {
    Route::apiResource('users', 'UserController');
    Route::apiResource('akten', 'AkteController');
  });
});
```

```
# config/auth.php
    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
            'hash' => false,
        ],
    ],
```

I tried discord before, then posted to the laracast forums and now im posting this issue. (https://laracasts.com/discuss/channels/testing/laravel-test-differs-from-same-requests-made-with-curl-or-browser)

**Comment by mfn** [comment]
I believe that simulating multiple requests within a single test does not exactly match the environment three actual independent requests would have. That's why you see that state "stick".

The answer very often is that "it's a bad idea" (simulating multiple requests within a test) and it shouldn't be done etc.

I've seen people finding workarounds for the _various_ issues they have, like trying to reset the internal state of cached authenticated users.

However I don't want to get ahead of this problem, maybe there's a solution. Just wanted to chime in what I remember the last times I saw similar issues coming up.

**Comment by davewood** [comment]
thanks mfn your feedback helped alot.

i put each request in a separate test function and now it works, i have to use phpunits `@depends` feature though to make sure the tests are executed in the correct order.

register > login > ...

I keep stumbling about "it's a bad idea" remarks, but no one seems to elaborate how else it should be done.

here is a small code sample in case someone else has the same problem (`_post()` is just a small helper function im using)
```
    public function test_register() {
        $password = 'asdfasdf';
        $data = [ 'name'     => 'John Doe',
                  'email'    => 'john@doe.com',
                  'password' => $password,
                  'password_confirmation' => $password,
        ];
        $res = $this->_post( '/api/users/register', $data, 201 );
        $res->assertJsonStructure([ 'data' => ['id', 'name', 'email'] ]);
        $user_id = $res->getData()->data->id;

        // get token from DB
        $u = User::findOrFail($user_id);
        $api_token = $u->api_token;
        $this->assertTrue(strlen($api_token) > 30); // no idea what size hashed api_tokens are but at least 30
        return [
            'email'     => $data['email'],
            'password'  => $data['password'],
            'name'      => $data['name'],
            'api_token' => $api_token,
            'user_id'   => $user_id,
        ];
    }
    /**
     * @depends test_register
     */
    public function test_login($data) {
        $api_token = $data['api_token'];

        $login = [
            'email'    => $data['email'],
            'password' => $data['password']
        ];

        $res = $this->_post('/api/users/login', $login);
        $res->assertJsonStructure([ 'data' => ['api_token'] ]);
        $new_api_token = $res->getData()->data->api_token;
        $this->assertTrue(strlen($new_api_token) === 80);
        $this->assertTrue($new_api_token !== $api_token);
        $data['api_token'] = $new_api_token;
        return $data;
    }
```

**Comment by mfn** [comment]
> I keep stumbling about "it's a bad idea" remarks, but no one seems to elaborate how else it should be done.

When phpunit setup/teardown runs, the whole framework is booted and destroyed, correctly and properly isolating each test from each other, as it should be.

Now, when you think about request coming in, for each individual request the same happens.

This already highlights the BIG difference, that _within_ a test you cannot have this. Unless you _manually_ start to fiddle around (and this is what people often do).

I think your `@depends` approach, if it's possible for the SUT, is one of the more elegant solutions I've seen so far. Nice 👍
