### ISSUE TITLE
two indexes instead of one created on migration

### ISSUE THREAD

**Issue by Eugene-Melbourne** [laravel/framework#30675]
- Laravel Version: 6.4.1
- PHP Version: 7.2.17
- Database Driver & Version: MYSQL 5.7.25 (Ubuntu)

### Description:

Two unique indexes are created on the table in case of a migration has modified an existing record.

### Steps To Reproduce:

Migration to run 

    public function up(): void
    {
       Schema::create('some_records', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('field_1')->nullable();
        });

        Schema::table('some_records', function (Blueprint $table) {
            $table->unsignedInteger('field_1')->nullable()->unique()->change();
        });
    }

check indexes for the some_records table, you will see 2 of them:

- field_1 - unique
- some_records_field_1_unique - unique

When it is expected to be one:

- some_records_field_1_unique - unique

**Comment by driesvints** [comment]
I get the same result. Even if I split up the migrations into two separate ones. Not sure what's going on but that indeed seems to be unwanted.

**Comment by driesvints** [comment]
In the meantime you can circumvent it with:

```php
public function up(): void
{
   Schema::create('some_records', function (Blueprint $table) {
        $table->increments('id');
        $table->unsignedInteger('field_1')->nullable();
    });

    Schema::table('some_records', function (Blueprint $table) {
        $table->unique('field_1');
    });
}
```

**Comment by danielsuguimoto** [comment]
Hi! I didn't debug enough to find the problem but noticed that this simple migration executes these two queries in the database

```
ALTER TABLE some_records CHANGE field_1 field_1 INT DEFAULT NULL UNIQUE
alter table 'some_records' add unique 'some_records_field_1_unique' ('field_1')
```
So, I guess `change()` method is executing a diff comparison between the database and the `Blueprint` and `unique()` is adding a `unique add command`.
