### ISSUE TITLE
Double Response/ Exception On RuntimeException For No application encryption key 

### ISSUE THREAD

**Issue by bobbyaxe61** [laravel/framework#30688]
- Laravel Version: 6.0.0
- PHP Version: 7.3.12
- Database Driver & Version: 10.4.6-MariaDB

### Description:

i received double responses when i removed my application key and ran the application and visited a general path as "/" which was supposed to return the welcome.blade.php page or in this case a handled exception message.

### Steps To Reproduce:

Create a new laravel project

````
    composer create-project laravel/laravel "project-name"
    cd project-name
    nano .env
````

Delete the application key if any has been set 

````
    APP_KEY=
````

save the .env file 
go to the Handler.php file and add the following

````
    cd App\Exceptions
    nano Handler.php
````

Add the following to the render function

````
    /**
     * Render an exception into an HTTP response.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Exception  $exception
     * @return \Illuminate\Http\Response
     */
    public function render($request, Exception $exception)
    {
        // Thrown when an exception occurs.
        if ($exception instanceof Exception) {
            return response()->json('okay', 500);
        }

        return parent::render($request, $exception);
    }
````

Then run on your browser visit http://127.0.0.1:8000/ or http://serving_address/
You should receive two json response instead of one.

Yes i understand that this is not an issue of such as the application key must be set to use laravel i am only concerned about the exception handling.

First issue was closed due to my version not being supported, i tried a newer supported version and the same issue occurred. hope it can be looked into. thanks.

**Comment by driesvints** [comment]
Since there's no issue if you correctly set your app key I'm closing this. Feel free to send in a PR if you can find a solution for the double response problem.
