### ISSUE TITLE
Ignition fails to report the correct Exception

### ISSUE THREAD

**Issue by ThibaudDauce** [laravel/framework#30682]
- Laravel Version: 6.5.2
- PHP Version: 7.3.12

### Description:

When using a specific number of non ASCII characters and in a view with an exception, Ignition fails to generate the correct source map and breaks the Blade compilation. The exception shown is `ErrorException:  Undefined offset: 1` in `vendor/laravel/framework/src/Illuminate/View/Compilers/Concerns/CompilesLoops.php:95` and not the correct exception thrown.

### Steps To Reproduce:

You can clone the repository https://github.com/ThibaudDauce/ignition-fails and go to `/failing_correct` and `/failing_incorrect`. The views are really simple and the only difference is one more non ASCII character (`à` here but it's working with any special character) in `failing_incorrect.blade.php`.

To illustrate the problem, here is the result of the source map generation from Ignition (you can see the same thing by going into `vendor/facade/ignition/src/Views/Compilers/BladeSourceMapCompiler.php` and adding a `dd($map)` line 11):

The correct version (it's not really correct but the correct exception is thrown and shown):

```
<!DOCTYPE html>
<html lang="|---LINE:2---|<?php echo e(str_replace('_', '-', app()->getLocale())); ?>">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>
    </head>
    <body>
        ààààààà
        <?php
  |---LINE:12---|          throw new Exception   
        ?>|---LINE:13---|

        <ul>
            @foreac|---LINE:16---|h ([1, 2, 3] as $i => $test)
                <li><?php echo e($tes|---LINE:17---|t); ?></li>
            <?php endfor; ?>|---LINE:18---|each
        </ul>
    </body>
</html>
```

If I had a single `à`, Ignition generates `@foreach|---LINE:16---| ([1, 2, 3] as $i => $test)` and Blade cannot parse the `@foreach` anymore.

This error was reported one month ago in https://github.com/facade/ignition/issues/193 without any consideration from the Ignition team. My workflow is currently totally broken in Laravel, I cannot get the correct information. When I run my tests, if I do a mistake in my view, I only see the Blade error in the results (and in the logs) so I cannot see what is the real problem. When I go on the page I see the beautiful Ignition error page but with the wrong exception (so totally useless).

Thanks!

**Comment by driesvints** [comment]
We don't maintain ignition. Please continue the discussion on the ignition repo.
