### ISSUE TITLE
Safari auto load request ?

### ISSUE THREAD

**Issue by ShamanNguyen** [laravel/framework#30699]
- Laravel 5.8
- Safari 12.1

My handle middleware:

`public function handle($request, Closure $next, $guard = 'web') {
        saveCurrentURL($request->fullUrl());
        return $next($request);
 }
`

My goal is save some routes, but not all, to session.
Firefox and Chrome work well.
But Safari work incorrect.
I debug and I see, when I typing address on safari, after short period time, the middle ware is called, although have not load page yet.

Any one recommend me a solution to fixed it.
Thank you!

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
