### ISSUE TITLE
Wrong return type for Mailable::render

### ISSUE THREAD

**Issue by RSully** [laravel/framework#30694]
- Laravel Version: 6.6.0

### Description:

`Mailable::render()` says it returns a View, but it returns the rendered `string`, at least for HTML views:

https://github.com/laravel/framework/blob/8105ee48e12c32182b12ba65c27b57b517edf688/src/Illuminate/Mail/Mailable.php#L205

**Comment by RSully** [comment]
I was going to fix this while on the train but the wifi is shoddy and seriously why is this repo more than 10MB?

**Comment by driesvints** [comment]
You're correct. I've fixed this for the next release. Thanks
