### ISSUE TITLE
Arr::pluck doesn't work with parameters: `key`, `value`

### ISSUE THREAD

**Issue by mahdyfo** [laravel/framework#30696]
- Laravel Version: 6.0.3
- PHP Version: 7.3.11
- DB: MariaDB 10.4.8

### Description:
`Arr::pluck()` doesn't return correct results when its first param is `key` and second is `value`.

### Steps To Reproduce:
```
$keys = ['email.smtp.host', 'email.smtp.port'];
$results = DB::table('settings')->select('key', 'value')->whereIn('key', $keys)->get();
dd($results->pluck('value', 'key'));
```

Table `settings`:
```
key               |   value
__________________________________
email.smtp.host   |   example.com
email.smtp.port   |   2525
```

Result:

```
Illuminate\Support\Collection {#3640
  #items: array:1 [
    "" => null
  ]
}
```

However it works fine with names other than `key` and `value` in pluck parameters.

**Comment by driesvints** [comment]
Works fine for me in the latest Laravel release with your code example.

![Screen Shot 2019-11-28 at 18 40 14](https://user-images.githubusercontent.com/594614/69825144-8b0dc900-120e-11ea-8eb1-405ca8ee3210.png)
