### ISSUE TITLE
Date formatting in InteractsWithPivotTable::addTimestampsToAttachment()

### ISSUE THREAD

**Issue by rudiedirkx** [laravel/framework#30692]
- Laravel Version: 5.7.28 (but still)

[InteractsWithPivotTable::addTimestampsToAttachment()](https://github.com/laravel/framework/blob/5d96db229d18fd5ee5bc4f57f60303868035a033/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php#L383) should use the pivot model's `formatDate()` to format the date, instead of directly calling `$fresh->format()`, like everywhere else.

Now:

    $fresh = $fresh->format($pivotModel->getDateFormat());

Better:

    $fresh = $pivotModel->formatDate($fresh);

That way, the pivot model is responsible for the formatting, not the `$fresh` object. So the developer can customize the formatting, not just the format. And it works like that everywhere else.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by rudiedirkx** [comment]
Like I said:

> Laravel Version: 5.7.28 (but still)

The code is exactly the same in 6.0, so the problem persists, and the solution is the same. Do you want me to make a new issue with another version number?

**Comment by driesvints** [comment]
@rudiedirkx can you please try this out on an actual v6.x app first? It's best to not make assumptions if this is actually still present in the latest release. Maybe also try a support channel first:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by rudiedirkx** [comment]
I'm not assuming... I can read code... https://github.com/laravel/framework/blob/6.x/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php#L383
