### ISSUE TITLE
Mimes validation produces error with PHP version 7.3 even with correct file uploaded.

### ISSUE THREAD

**Issue by ambengers** [laravel/framework#30707]
- Laravel Version: 5.8.35
- PHP Version: 7.3.12
- Database Driver & Version: MySQL 5.5.5-10.4.6-MariaDB

### Description:
I've decided to upgrade my local machine PHP version from 7.2 to 7.3 and suddenly the request mimes validations are now producing errors.

<img width="990" alt="Screen Shot 2019-11-28 at 3 46 09 PM" src="https://user-images.githubusercontent.com/17848299/69787589-d4065300-11f7-11ea-8106-3941aadc4657.png">

My validations are for excel mimes as you can see on the screenshot. And I am not sure if I am just missing something on this or if it's an actual bug.

### Steps To Reproduce:
1. Setup an endpoint that validates excel spreadsheet mimes:

`$request->validate(['document' => 'required|file|mimes:xlsx,csv,xls']);`

2. Send an excel file with the correct extension to the endpoint

Expected result: Validation will pass
Actual result: Validation will fail

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
