### ISSUE TITLE
Artisan DevCommands

### ISSUE THREAD

**Issue by kohlerdominik** [laravel/framework#30705]
- Laravel Version: 6.x

I’ve got a question about a the [ArtisanServiceProvider::register()](https://github.com/laravel/framework/blob/1bbe5528568555d597582fdbec73e31f8a818dbc/src/Illuminate/Foundation/Providers/ArtisanServiceProvider.php#L157)-method:
```php
public function register()
{
    $this->registerCommands(array_merge(
        $this->commands, $this->devCommands
    ));
}
```
---
#### A short history to introduce (this stuff is old!)

1. Taylor introduced a change to the ArtisanServiceProvider to differentiate between Commands and DevCommands in this [commit]( https://github.com/laravel/framework/commit/7c5e340d374471efb1ebc04dbd1ab4a81e0cd9ed#diff-52ce501efc27d62b35ed72232484863bR99):
```php
public function register()
{
    $this->registerCommands($this->commands));

    if (! $this->app->environment('production')) {
        $this->registerCommands($this->devCommands);
    }
}
```

2. It got commented from Tylor in this [change](https://github.com/laravel/framework/commit/478076b1c61a637acfee137cbfc3862f22cc573c#diff-52ce501efc27d62b35ed72232484863bR109), the reason is not very clear to me.

3. The commented code got [removed](https://github.com/laravel/framework/commit/17651100b39554aeaf6a54645e6aaa4242e21756) and eventually [refactored](https://github.com/laravel/framework/commit/b892805124ecdf4821c2dac7aea4f829ce2248bc#diff-52ce501efc27d62b35ed72232484863bR117), ending up with the version we have right now (see the first code-block).
---
So, finally arriving to ask my question: is there any specific reason it got removed?
From my opinion, it would make sense to hide obvious useless commands in production like `make:` or `:table`, meaning to re-introduce this feature.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by kohlerdominik** [comment]
Thanks for your feedback. I need to point out that this is **not a support question**, but rather a question to the core team about a specific implementation decision. 

I will create a Pull Request changing this behavior, if there’s no specific reason against it. But I wanted to ask if the reason is remembered why it got removed in first place, before starting to work on it. Maybe @taylorotwell remembers this?
