### ISSUE TITLE
[6.x] artisan route:list not displaying GET routes when head route method is used on a route

### ISSUE THREAD

**Issue by samstreet** [laravel/framework#30708]
- Laravel Version: 6.x
- PHP Version:  7.2.24
- Database Driver & Version: MySql 5.7

### Description:
Since the addition of the new `head` method to the router, when running the route list command, GET methods are ignored in favour of the HEAD methods in the tabular output.

```
+---------+-------------------------------------------------+
| Method  | URI                                             |
+---------+-------------------------------------------------+
| HEAD    | /                                               |
| HEAD    | reports                                         |
| HEAD    | reports/institution/{id}                        |
| OPTIONS | reports/institution/{id}                        |
| HEAD    | users/{userId}/portfolio                        |
| OPTIONS | users/{userId}/portfolio                        |
| OPTIONS | users/{userId}/portfolio/evidence               |
| POST    | users/{userId}/portfolio/evidence               |
| HEAD    | users/{userId}/portfolio/evidence               |
| PATCH   | users/{userId}/portfolio/evidence/{evidenceId}  |
| PUT     | users/{userId}/portfolio/evidence/{evidenceId}  |
| OPTIONS | users/{userId}/portfolio/evidence/{evidenceId}  |
| HEAD    | users/{userId}/portfolio/evidence/{evidenceId}  |
| OPTIONS | users/{userId}/portfolio/ojt                    |
| HEAD    | users/{userId}/portfolio/ojt                    |
| OPTIONS | users/{userId}/portfolio/taskplans              |
| HEAD    | users/{userId}/portfolio/taskplans              |
| OPTIONS | users/{userId}/portfolio/taskplans/{idTaskPlan} |
| HEAD    | users/{userId}/portfolio/taskplans/{idTaskPlan} |
| OPTIONS | users/{userId}/portfolio/tiles                  |
| HEAD    | users/{userId}/portfolio/tiles                  |
| POST    | vapor/signed-storage-url                        |
+---------+-------------------------------------------------+
```

The issues arrises when methods are defined as follows:

```
$this->getRouter()->get('/', [
    'uses' => 'CoreController@get',
    'name' => 'core.get'
]);

$this->getRouter()->head('/', [
    'uses' => 'CoreController@head',
    'name' => 'core.head'
]);
```
The issues is caused by this line; https://github.com/laravel/framework/blob/6.x/src/Illuminate/Routing/Route.php#L143-L145 If I comment these lines out, then I can see GET and HEAD in my tabular output on separate lines.

### Steps To Reproduce:
- Clone a new Laravel project
- Add new routes for a project; one GET and one HEAD for the same route
- Run `php artisan r:l --compact` and see that the GET method is not listed

**Comment by driesvints** [comment]
Probably caused by https://github.com/laravel/framework/pull/30646

I think we can maybe remove that now that we have a dedicated HEAD method.

**Comment by driesvints** [comment]
Actually, I just tested this and I correctly get the following output:

```
$ a route:list --compact                                                                                                                                ~/Sites/test-indexes
+----------+----------+---------+
| Method   | URI      | Action  |
+----------+----------+---------+
| HEAD     | /        | Closure |
| GET|HEAD | api/user | Closure |
+----------+----------+---------+
```

For:

```
Route::get('/', function () {
    return view('welcome');
});

Route::head('/', function () {
    return view('welcome');
});
```

Is there anything we're missing? Please note that the GET route definition still registers as HEAD as well so you can't register duplicate routes atm.

**Comment by samstreet** [comment]
The only difference I have is that I have duplicate routes, I want to target each of the HTTP Methods on a route to a specific controller method. This will lead to duplicate routes, it is odd that a duplicated route that does OPTIONS, for example, showed correctly in the tabular format alongside the methods.

**Comment by driesvints** [comment]
@samstreet the thing is that before this route was added, everything worked fine. Laravel already returns an empty response with the headers for you. I don't see the need for a separate route method.

**Comment by driesvints** [comment]
@samstreet I still mis the GET route if I remove the lines you mentioned btw.

**Comment by samstreet** [comment]
@driesvints I understand that, but I also see it from the other side that we may not want to directly tie our HEAD calls to the same GET method and developers may want to provide other functionality (logging, different middleware rules etc.). The method itself doesn't differ from any of the other route mapping methods, it's only at the point where we `route:list` that the routs do not show. I can happily call the route still and get the desired route matching.

**Comment by driesvints** [comment]
I think at this point it's better that we reverse the PR and maybe attempt a new one once we can pinpoint the location of the actual bug.

**Comment by driesvints** [comment]
Made a PR here: https://github.com/laravel/framework/pull/30710

**Comment by samstreet** [comment]
@driesvints id have to disagree, if I didn’t  the get, post, put methods and used addRoute instead with the method type and had a duplicate url that would produce the same result. The underlying issue is the fact the command can’t parse the duplicate urls, not the addition of the head method.

**Comment by driesvints** [comment]
@samstreet if you can provide a solution to the route list issue we can reconsider it
