### ISSUE TITLE
SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for type integer: ""

### ISSUE THREAD

**Issue by jeffersoncostaIfma** [laravel/framework#30701]
- Laravel Version: 5.6.39
- PHP Version: 7.3.11
- Database Driver & Version:PostgreSQL 12

### Description:
I have the following error while entering data in Store HELP ME PLZ:

> SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for type integer: "" (SQL: insert into "pmieducar"."servidor_alocacao" ("ref_usuario_cad", "ref_usuario_exc", "data_cadastro", "ano", "ref_cod_escola", "periodo", "data_admissao", "ref_cod_servidor_funcao", "ref_cod_funcionario_vinculo", "hora_inicial", "hora_final", "carga_horaria", "hora_atividade", "horas_excedentes") values (1, 1, 2019-11-27 10:34:05, 2019, 39, 1, 2018-10-26, , , 16:54:06, , 12:38:00, , ) returning "cod_servidor_alocacao")

Controller
`<?php

namespace App\Http\Controllers\Servidor;

use Illuminate\Http\Request;
use App\Instituicao;
use App\Http\Controllers\Controller;
use App\Models\Servidor\Servidor;
use App\Models\Servidor\ServidorAlocacao;
use App\Models\Pmieducar\Escola;
use App\Models\Portal\FuncionarioVinculo;
use App\Models\Servidor\ServidorFuncao;
use App\Models\Servidor\TipoFuncao;

class ServidorAlocacaoController extends Controller
{
    private $rota = 'Admin/servidor/servidor/alocao';
    // public  $rotaAlocacao = 'Admin/servidor/servidor/alocao';
    private $view = 'admin.servidor.servidor.alocacao';
    private $titulo = 'Alocação de Servidor';

    
    public function __construct(){
        view()->share('rota', 'alocacao.');
        // view()->shere('rota' , 'alocacao.');
        view()->share('titulo', $this->titulo);
        view()->share('instituicao', Instituicao::orderBy('nm_instituicao', 'asc')->get());
        view()->share('vinculo', FuncionarioVinculo::orderBy('cod_funcionario_vinculo' , 'asc')->get());
        view()->share('funcao', TipoFuncao::orderBy('cod_funcao' , 'asc')->get());

    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($cod_servidor)
    {
        
        $servidor = Servidor::find($cod_servidor);
        
        return view('Admin.servidor.servidor.alocacao.index' , compact('servidor'));
    
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($cod_servidor )
    {
        
        

        $servidor = Servidor::find($cod_servidor);
        // return $servidor;        
        $escola = Escola::where('ref_cod_instituicao', $servidor->ref_cod_instituicao)->OrderBy('ref_cod_instituicao')->get();
        
        return view('Admin.servidor.servidor.alocacao.create' , compact('servidor' , 'escola'));

        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request , ServidorAlocacao $data)
    {
        
        $data->carga_horaria               = $request->carga_horaria;
        $data->periodo                     = $request->periodo;
        $data->ref_cod_servidor_funcao     = $request->ref_cod_servidor_funcao;
        $data->ref_cod_funcionario_vinculo = $request->ref_cod_funcionario_vinculo;
        $data->ano                         = $request->ano;
        $data->data_admissao               = $request->data_admissao;
        $data->hora_inicial                = $request->hora_inicial;
        $data->hora_final                  = $request->hora_final;
        $data->hora_atividade              = $request->hora_atividade;
        $data->horas_excedentes            = $request->horas_excedentes;
    // dd($data)        ;
        $data->save();

        if($data->fill($request->all())->save() != null){
            return redirect('Admin/servidor/servidor/alocacao/cod_servidor}')->with(['success' => 'Servidor alocado com sucesso.']);
        }else{
            return redirect('Admin/servidor/servidor/alocacao/{cod_servidor}')->with(['error' => 'Ocorreu um erro. Tente novamente mais tarde.']);
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}
`
Model
`<?php

namespace App\Models\Servidor;

use App\Models\Pmieducar\Escola;
use App\Models\Portal\FuncionarioVinculo;
use Illuminate\Database\Eloquent\Model;

class ServidorAlocacao extends Model
{
    protected $table = 'pmieducar.servidor_alocacao';
    protected $primaryKey = 'cod_servidor_alocacao';
    protected $fillable = ['cod_servidor_alocacao', 'ref_ref_cod_instituicao', 'ref_usuario_exc',
        'ref_usuario_cad', 'ref_cod_escola', 'ref_cod_servidor', 'data_cadastro', 'data_exclusao',
        'ativo', 'carga_horaria', 'periodo', 'ref_cod_servidor_funcao', 'ref_cod_funcionario_vinculo',
        'ano', 'data_admissao', 'hora_inicial', 'hora_final', 'hora_atividade', 'horas_excedentes',
        ];
    public $timestamps = false;

    public function servidor(){
        return $this->belongsTo(Servidor::class, 'ref_cod_servidor', 'cod_servidor');
    }

    public function escola(){
        return $this->belongsTo(Escola::class, 'ref_cod_escola', 'cod_escola');
    }

    public function funcao(){
        return $this->belongsTo(ServidorFuncao::class, 'ref_cod_servidor_funcao', 'cod_servidor_funcao');
    }
    public function vinculo(){
        return $this->belongsTo(FuncionarioVinculo::class, 'ref_cod_funcionario_vinculo', 'cod_funcionario_vinculo');
    }
}
`
View
`@extends('dashboard.app')

@section('htmlheader_title')
    - {{$titulo}}
@endsection

@section('contentheader_title')
    {{$titulo}}
@endsection

@section('contentheader_icon')
    fa-graduation-cap
@endsection

@section('main-content')
    <div class="container-fluid mt--6">
        {{-- Listagem dos Cursos --}}
        <div class="row">
            <div class="col">
                <div class="card">
                    
                    <div class="card-header">
                        <h3 class="mb-0">{{$titulo}}</h3>
                    </div>
                    
                    <div class="card-body">
                        <form id="form-curso" action="{{route($rota.'store')}}" method="POST"
                              enctype="multipart/form-data" autocomplete="off">
                            {{ csrf_field() }}
                            <input type="hidden" name="ref_usuario_cad" value="{{\Auth::user()->ref_idpes}}">
                            <input type="hidden" name="ref_usuario_exc" value="{{\Auth::user()->ref_idpes}}">
                            <input type="hidden" name="data_cadastro" value="{{date('Y-m-d H:i:s')}}">
                            
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Instituição: </label>
                                        <input class="form-control" type="text" disabled="disabled" name="" id="" 
                                        placeholder="{{$servidor->instituicao->nm_instituicao}}">

                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Servidor:</label>
                                        <input class="form-control" type="text" disabled="disabled" name="" id="" 
                                        placeholder="{{$servidor->pessoa->nome}}">
                                    </div>
                                </div>
                            </div>
                            
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Carga Horária do Servidor:</label>
                                        <input class="form-control" type="text" disabled="disabled" name="" id="" 
                                        placeholder="{{$servidor->carga_horaria}} horas">                                    </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label>Ano *:</label>
                                            <input class="form-control" type="text" name="ano" id="" required
                                            placeholder="Ano">                                    
                                        </div>
                                    </div>
                                        <div class="col-md-6">
                                                <div class="form-group">
                                                    <label>Escola *:</label>
                                                    <select class="form-control" name="ref_cod_escola" id="" required>
                                                        <option value="ref_cod_escola">Selecione
                                                                
                                                        </option>
                                                        @if (isset($escola))
                                                            @foreach ($escola as $it)
                                                                <option value="{{$it->cod_escola}}"> {{$it->pessoa->nome}} </option>
                                                            @endforeach
                                                        @endif
                                                    </select>                                   </div>
                                                </div>
                                        </div>
                                        <div class="row">
                                                <div class="col-md-6">
                                                        <div class="form-group">
                                                            <label>Periodo *:</label>
                                                            <select required class="form-control" name="periodo" id="" required>
                                                                <option value="">Selecione</option>
                                                                <option value="1">Matutino</option>
                                                                <option value="2">Vespertino</option>
                                                                <option value="3">Noturno</option>
            
            
            
                                                            </select>
                                                        </div>
                                                </div>
                                                
                                                <div class="col-md-3">
                                                        <div class="form-group">
                                                            <label>Data de admissão :</label>
                                                            <input class="form-control" type="date" name="data_admissao" id="" 
                                                            placeholder="dd/mm/yyyy">                                    
                                                        </div>
                                                </div>
                                                
                                        </div>
                                        <div class="row">
                                                <div class="col-md-6">
                                                        <div class="form-group">
                                                            <label>Função *:</label>
                                                            <select required class="form-control" name="ref_cod_servidor_funcao" id="" >
                                                                    <option value="">Selecione</option>
                                                                @if (isset($funcao))
                                                                    @foreach ($funcao as $it)
                                                                        @if($it->cod_funcao !== null)
                                                                        <option value="{{$it->ref_cod_servidor_funcao}}"> {{$it->nm_funcao}} </option>
                                                                        @endif
                                                                    @endforeach
                                                                @endif
                
                
                
                                                                </select>                        
                                                        </div>
                                                </div>  
                                                <div class="col-md-6">
                                                        <div class="form-group">
                                                            <label>Vunculo *:</label>
                                                            <select required class="form-control" name="ref_cod_funcionario_vinculo" id="" >
                                                                    <option value="">Selecione</option>
                                                                    
                                                                @if (isset($vinculo))
                                                                    @foreach ($vinculo as $it)
                                                                        @if($it->cod_funcionario_vinculo !== null)
                                                                        <option value="{{$it->ref_cod_funcionario_vinculo}}"> {{$it->nm_vinculo}} </option>
                                                                        @endif
                                                                    @endforeach
                                                                @endif
                
                
                                                                </select>                        
                                                        </div>
                                                </div>  
                                        </div>
                                    </div>
                                    <div class="card-header">
                                            <h3 class="mb-0">Informações Sobre Carga Horaria</h3>
                                    </div>
                                    <div class="row">
                                        
                                        
                                        <div class="col-md-2">
                                                <div class="form-group">
                                                    <label>Horario de Início:</label>
                                                    <input class="form-control" type="time" step="2" name="hora_inicial" id="" 
                                                    >                                    
                                                </div>
                                        </div>
                                        <div class="col-md-2">
                                                <div class="form-group">
                                                    <label>Horario de termíno:</label>
                                                    <input class="form-control" type="time" step="2" name="hora_final" id="" 
                                                    >                                    
                                                </div>
                                        </div>  
                                        <div class="col-md-2">
                                            <div class="form-group">
                                                <label>Carga horária *:</label>
                                                <input class="form-control" type="time" step="2" name="carga_horaria" id="carga_horaria" 
                                                required>                                    
                                            </div>
                                    </div> 
                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <label>Hora atividade:</label>
                                            <input class="form-control" type="time" step="2" name="hora_atividade" id="" 
                                            >                                    
                                        </div>
                                </div> 
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label>Horas excedentes:</label>
                                        <input class="form-control" type="time" step="2" name="horas_excedentes" id="" 
                                        >                                    
                                    </div>
                                </div> 
                                </div>
                                <div class="row">
                                </div>
                            
                            

                            <div style="width:100%;text-align:center">
                                <div class="form-group ">
                                    <button class="btn btn-primary" type="submit">Salvar</button>
                                    <a class="btn btn-danger" href="{{route($rota.'index' , $servidor->cod_servidor)}}"> Voltar </a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection

@section('scripts-footer')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.js"></script>
    <script src="{{ asset('/admins/js/servidor/servidor.js') }}"></script>
@endsection
`

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
