### ISSUE TITLE
FileViewFinder cannot render directory names with period

### ISSUE THREAD

**Issue by PhoenixPeca** [laravel/framework#30709]
- Laravel Version: v6.6.0
- PHP Version: 7.3.10
- Database Driver & Version: None

### Description:
`FileViewFinder.php` cannot render directory names with period.
The class must have only considered that all foldernames with period is a "/" to indicate a sub directory.

### Steps To Reproduce:

Inside the views directory, I have a folder named `super.hero`.
full path `resources/views/super.hero/`. inside the "super.hero" folder, I have `index.blade.php` file.
I tried to add a route for the view like so:
````php
Route::get('/super.hero', function () {
    return view('super.hero.index');
});
````
But I get an error instead:
![image](https://user-images.githubusercontent.com/9730242/69818027-db008600-1236-11ea-8e7c-6cd1b5f6a3b4.png)

**Comment by driesvints** [comment]
We unfortunately don't support dots in directory names. This might be worth adding to the docs here: https://laravel.com/docs/6.x/views

**Comment by PhoenixPeca** [comment]
@driesvints perhaps this is a bug for the ignition engine since it gives a misleading "Did you mean?" suggestion. I'll open a separate issue for ignition.

**Comment by driesvints** [comment]
Sent in a PR for this: https://github.com/laravel/docs/pull/5802
