### ISSUE TITLE
E-mail validation doesn't work as expected

### ISSUE THREAD

**Issue by bashovski** [laravel/framework#30703]
- Laravel Version: 6
- PHP Version: 7.3.3

### Description:

E-mail validator doesn't return any message bags representing validation errors in case format of email is something like: lorem@ipsum 
Valid e-mail format should be: lorem@ipsum.tld. This case is somehow an exception and isn't properly validated, while other variations of irregular formats of e-mails do get caught by the validator (e.g. lorem@.tld)
Perhaps, (dot)tld should be required for a valid e-mail.

If needed, I'll provide code examples in the comments.

**Comment by devcircus** [comment]
Check out the different options for validating email in the docs. The tld isn't actually required for a valid address but you can use one of the newer options available in version 6 if you need different/more strict validation. Also a quick search of the issues turns up a lot of related conversations. 

https://laravel.com/docs/6.x/validation#rule-email

**Comment by bashovski** [comment]
I haven't noticed new validation styles since the release of the new version. Thank you.
