### ISSUE TITLE
dump() breaks class resolution from container in unit tests

### ISSUE THREAD

**Issue by ionutantohi** [laravel/framework#30700]
- Laravel Version: 6.6.0
- PHP Version: 7.3.11
- Database Driver & Version:

### Description:
Kindly hard to explain and I didn't found the root cause for it (I think is related to how laravel is booted before each test).

Considering the example below, If you use `dump` helper in the second test, after it you can no longer resolve a class from container. 

`get_class(app('db'))` will throw the following error: Illuminate\Contracts\Container\BindingResolutionException: Target class [db] does not exist.

If you remove the dump statement, `get_class(app('db'))` will output correctly `Illuminate\Database\DatabaseManager`

This behaviour **starts with the second test**. If used in the first test it works fine.

Note: in 5.8 it works fine

### Steps To Reproduce:

Run test suite `vendor/bin/phpunit --filter=DumpTest`

Note: when test_2 is executed individually it works ok `vendor/bin/phpunit --filter=test_2`
```php
<?php

namespace Tests\Unit;

use Tests\TestCase;

class DumpTest extends TestCase
{
    public function test_1()
    {
        $this->assertTrue(true);
    }

    public function test_2()
    {
        dump('something');

        echo get_class(app('db'));

        $this->assertTrue(true);
    }
}
```

**Comment by mfn** [comment]
It works for me if I do the following: `composer remove --dev facade/ignition`

How I came to this:
- when I debugged it, I realized that `\Symfony\Component\VarDumper\VarDumper::$handler` was already set
- it had a closure reference to facade/ignition

**Comment by ionutantohi** [comment]
I see a similar issue reported in the ignition repo: https://github.com/facade/ignition/issues/181 

@freekmurze @mpociot

**Comment by driesvints** [comment]
Please report this to the ignition repo, thanks.
