### ISSUE TITLE
Route Url Generator throw an exception when a null parameter is assigned to route helper

### ISSUE THREAD

**Issue by sergiq** [laravel/framework#30717]
- Laravel Version: 6.6.0
- PHP Version: 7.2.23
- Database Driver & Version:

### Description:
The version 6.6.0 throws an UrlGenerationException when some route url param is null. This does not affect to any version less than 6.6.0

### Steps To Reproduce:

Laravel version < 6.6.0
```
$some_var = null;
Route::get('/some-example/{slug}', 'SomeController@someAction')->name('test');
route('test', ['slug'=>$some_var ]); // some-example
```
Laravel version = 6.6.0

```
$some_var = null;
Route::get('/some-example/{slug}', 'SomeController@someAction')->name('test');
route('test', ['slug'=>$some_var ]); // UrlGenerationException
```

**Comment by driesvints** [comment]
Please see https://github.com/laravel/framework/issues/30698 and https://github.com/laravel/framework/pull/30659
