### ISSUE TITLE
Loading schedule on every artisan command run

### ISSUE THREAD

**Issue by iwex** [laravel/framework#30711]
- Laravel Version: Any
- PHP Version: Any

### Description:

Hello! Why does Laravel run \App\Console\Kernel::schedule in its constructor. Why do we need to have some schedule on every artisan call? I think it's a bit overhead for non-schedule commands. 
 A similar issue was closed by its creator https://github.com/laravel/framework/issues/24165

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
