### ISSUE TITLE
Queue priorities & `block_for` shouldn't be used together

### ISSUE THREAD

**Issue by trevorgehman** [laravel/framework#30728]
- Laravel Version: 5.6.x & above
- Queue Driver: Redis

### Description:

If you use `block_for` and also utilize queue priorities, the worker will block on each queue sequentially. This could result in much longer queue processing times.

```
// config/queue.php

'redis' => [
   'driver'      => 'redis',
   'connection'  => 'queue',
   'queue'       => 'default',
   'retry_after' => 90,
   'block_for'   => 5,
],
```

### Steps To Reproduce:

For example, suppose you set `block_for=5` and spawn a worker like this:

```
php artisan queue:work --queue=high,medium,low,default --sleep=0
```

The worker will block on the `high` queue for 5 seconds, then the `medium` queue, then the `low` queue, and finally the `default` queue. This means that it could take up to 15 seconds before a job in the `default` queue is picked up, even if it is the only job in any of the queues.

More seriously, if you set `block_for=0` the worker will indefinitely block on the `high` queue, and the other queues will never be reached.

### Solution:

I'm not sure if this is a bug, but I initially assumed that the worker would block on _all_ the queues set for the worker and immediately pick up a new job in _any_ of them. 

Perhaps all that's needed is an addition to the documentation recommending that the `block_for` setting only be used when workers listen to a single queue...

**Comment by driesvints** [comment]
> Laravel Version: 5.6.x & above

Did you test this on Laravel 6?

**Comment by trevorgehman** [comment]
I've actually only just noticed it in 5.8.35.  I imagine this works the same in 6.x since this code is the same:

The worker calls `getNextJob` for each queue in order:

https://github.com/laravel/framework/blob/dfb4c1c3111d63383ed1f7ae67c79c1f83c8ec49/src/Illuminate/Queue/Worker.php#L260-L267

Which calls `pop` and `retrieveNextJob` on the Redis queue:

https://github.com/laravel/framework/blob/dfb4c1c3111d63383ed1f7ae67c79c1f83c8ec49/src/Illuminate/Queue/RedisQueue.php#L219-L238

You can see that `BLPOP` is called for each queue (line 233):

https://github.com/laravel/framework/blob/dfb4c1c3111d63383ed1f7ae67c79c1f83c8ec49/src/Illuminate/Queue/RedisQueue.php#L232-L235

So it's going to block for (in this case) 5 seconds before checking the next queue in the priority list.

**Comment by driesvints** [comment]
@trevorgehman feel free to open up a new issue once you were able to confirm this on 6.x

**Comment by z5864703** [comment]
> @trevorgehman feel free to open up a new issue once you were able to confirm this on 6.x

It can be confirmed that this problem exists in 6.x and 7.x
