### ISSUE TITLE
diffrent validation not work correctly

### ISSUE THREAD

**Issue by hshafiei374** [laravel/framework#30725]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Database Driver & Version:

### Description:
'result1'=>'nullable|numeric|different:
			result2|different:result3|different:result4|different:result5|different:result6|
			different:result7|different:result8|different:result9|different:result10|different:result11|different:
			result12|different:result13|different:result14|different:result15|different:result16|different:
			result17|different:result18|different:result19|different:result20',

			'result2'=>'nullable|numeric|different:result1|different:
			result3|different:result4|different:result5|different:result6|different:
			result7|different:result8|different:result9|different:result10|different:result11|different:
			result12|different:result13|different:result14|different:result15|different:result16|different:
			result17|different:result18|different:result19|different:result20',

			'result3'=>'nullable|numeric|different:result1|different:
			result2|different:result4|different:result5|different:result6|different:
			result7|different:result8|different:result9|different:result10|different:result11|different:
			result12|different:result13|different:result14|different:result15|different:result16|different:
			result17|different:result18|different:result19|different:result20',

			'result4'=>'nullable|numeric|different:result1|different:
			result2|different:result3|different:result5|different:result6|different:
			result7|different:result8|different:result9|different:result10|different:result11|different:
			result12|different:result13|different:result14|different:result15|different:result16|different:
			result17|different:result18|different:result19|different:result20',

			'result5'=>'nullable|numeric|different:result1|different:
			result2|different:result3|different:result4|different:result6|different:
			result7|different:result8|different:result9|different:result10|different:result11|different:
			result12|different:result13|different:result14|different:result15|different:result16|different:
			result17|different:result18|different:result19|different:result20',

			'result6'=>'nullable|numeric|different:result1|different:
			result2|different:result3|different:result4|different:result5|different:
			result7|different:result8|different:result9|different:result10|different:result11|different:
			result12|different:result13|different:result14|different:result15|different:result16|different:
			result17|different:result18|different:result19|different:result20',

			'result7'=>'nullable|numeric|different:result1|different:
			result2|different:result3|different:result4|different:result5|different:result6|different:
			result8|different:result9|different:result10|different:result11|different:
			result12|different:result13|different:result14|different:result15|different:result16|different:
			result17|different:result18|different:result19|different:result20',

			'result8'=>'nullable|numeric|different:result1|different:
			result2|different:result3|different:result4|different:result5|different:result6|different:
			result7|different:result9|different:result10|different:result11|different:
			result12|different:result13|different:result14|different:result15|different:result16|different:
			result17|different:result18|different:result19|different:result20',

			'result9'=>'nullable|numeric|different:result1|different:
			result2|different:result3|different:result4|different:result5|different:result6|different:
			result7|different:result8|different:result10|different:result11|different:
			result12|different:result13|different:result14|different:result15|different:result16|different:
			result17|different:result18|different:result19|different:result20',

			'result10'=>'nullable|numeric|different:result1|different:
			result2|different:result3|different:result4|different:result5|different:result6|different:
			result7|different:result8|different:result9|different:result11|different:
			result12|different:result13|different:result14|different:result15|different:result16|different:
			result17|different:result18|different:result19|different:result20',

			'result11'=>'nullable|numeric|different:result1|different:
			result2|different:result3|different:result4|different:result5|different:result6|different:
			result7|different:result8|different:result9|different:result10|different:
			result12|different:result13|different:result14|different:result15|different:result16|different:
			result17|different:result18|different:result19|different:result20',

			'result12'=>'nullable|numeric|different:result1|different:
			result2|different:result3|different:result4|different:result5|different:result6|different:
			result7|different:result8|different:result9|different:result10|different:result11|different:
			result13|different:result14|different:result15|different:result16|different:
			result17|different:result18|different:result19|different:result20',

			'result13'=>'nullable|numeric|different:result1|different:
			result2|different:result3|different:result4|different:result5|different:result6|different:
			result7|different:result8|different:result9|different:result10|different:result11|different:
			result12|different:result14|different:result15|different:result16|different:
			result17|different:result18|different:result19|different:result20',

			'result14'=>'nullable|numeric|different:result1|different:
			result2|different:result3|different:result4|different:result5|different:result6|different:
			result7|different:result8|different:result9|different:result10|different:result11|different:
			result12|different:result13|different:result15|different:result16|different:
			result17|different:result18|different:result19|different:result20',

			'result15'=>'nullable|numeric|different:result1|different:
			result2|different:result3|different:result4|different:result5|different:result6|different:
			result7|different:result8|different:result9|different:result10|different:result11|different:
			result12|different:result13|different:result14|different:result16|different:
			result17|different:result18|different:result19|different:result20',

			'result16'=>'nullable|numeric|different:result1|different:
			result2|different:result3|different:result4|different:result5|different:result6|different:
			result7|different:result8|different:result9|different:result10|different:result11|different:
			result12|different:result13|different:result14|different:result15|different:
			result17|different:result18|different:result19|different:result20',

			'result17'=>'nullable|numeric|different:result1|different:
			result2|different:result3|different:result4|different:result5|different:result6|different:
			result7|different:result8|different:result9|different:result10|different:result11|different:
			result12|different:result13|different:result14|different:result15|different:result16|different:
			result18|different:result19|different:result20',

			'result18'=>'nullable|numeric|different:result1|different:
			result2|different:result3|different:result4|different:result5|different:result6|different:
			result7|different:result8|different:result9|different:result10|different:result11|different:
			result12|different:result13|different:result14|different:result15|different:result16|different:
			result17|different:result19|different:result20',

			'result19'=>'nullable|numeric|different:result1|different:
			result2|different:result3|different:result4|different:result5|different:result6|different:
			result7|different:result8|different:result9|different:result10|different:result11|different:
			result12|different:result13|different:result14|different:result15|different:result16|different:
			result17|different:result18|different:result20',

			'result20'=>'nullable|numeric|different:result1|different:
			result2|different:result3|different:result4|different:result5|different:result6|different:
			result7|different:result8|different:result9|different:result10|different:result11|different:
			result12|different:result13|different:result14|different:result15|different:result16|different:
			result17|different:result18|different:result19'

**Comment by devcircus** [comment]
You would, at a minimum, need to explain why you don’t think this is working. What is your expectation vs. what is the actual result. 

You may actually get help faster on one of the community help sites like Laracasts, Laravel.io, Laravel’s Discord channel, or Larachat Slack.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
