### ISSUE TITLE
Using custom pagination outputs raw code

### ISSUE THREAD

**Issue by sebastiaanluca** [laravel/framework#30733]
- Laravel Version: 6.6.60
- PHP Version: 7.3.12

### Description:

The Laravel documentation notes to use the following code to output pagination for a resource in combination with a custom view:

```php
{{ $paginator->links('view.name') }}
```

However, using this in Laravel 6.6.0 does not work. The following does work:

```php
// No custom view, regular curly echo braces
{{ $paginator->links() }}

// Using a custom view requires unescaped output
{!! $paginator->links('view.name') !!}
```

The reason for reporting this is simply because they're using the same method, but both require a different way of using it which might indicate a breaking change or just outdated documentation.

### Steps To Reproduce:

According to the docs, the following should work, but outputs raw code:

```php
{{ $paginator->links('view.name') }}
```

**Comment by driesvints** [comment]
Hey @sebastiaanluca. I just tested this on the latest release and it works fine for me. Maybe there's something we're missing?

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
