### ISSUE TITLE
pluck makes force sort

### ISSUE THREAD

**Issue by 4n70w4** [laravel/framework#30734]
- Laravel Version: 5.8.35
- PHP Version: 7.3.11
- Database Driver & Version:

### Description:

After call `pluck` correction returns sorted.

### Steps To Reproduce:

```php
return collect([['title' => 'b', 'id' => 5], ['title' => 'a', 'id' => 3]])->pluck('title', 'id');
```

returns 

```
{
"3": "a",
"5": "b"
}
```

Why? I expected without resort by keys.

https://laravel.com/docs/5.8/collections#method-pluck

The documentation also does not notes that sorting is makes.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by 4n70w4** [comment]
I investigate deep! Return from routes and dd get different results of collection.

```php
        Route::get('/', static function (Request $request) {
            return collect([['title' => 'b', 'id' => 3], ['title' => 'a', 'id' => 5]])->pluck('title', 'id')->all();
        });
```

gets

```json
{
"3": "a",
"5": "b"
}
```


but `dd`:

```php
        Route::get('/', static function (Request $request) {
            dd(collect([['title' => 'b', 'id' => 3], ['title' => 'a', 'id' => 5]])->pluck('title', 'id')->all() );
        });
```

```json
^ array:2 [▼
  5 => "b"
  3 => "a"
]
```

**Comment by 4n70w4** [comment]
@driesvints at v6.6.0 the same problem.

**Comment by driesvints** [comment]
@4n70w4  Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by ionutantohi** [comment]
I think you use a json formatter extension.

![image](https://user-images.githubusercontent.com/4609521/70044934-ebfd1e80-15cb-11ea-8e57-a2228c988d3e.png)

![image](https://user-images.githubusercontent.com/4609521/70044939-ef90a580-15cb-11ea-906c-dee23233d013.png)

**Comment by 4n70w4** [comment]
@ionutantohi 
Really! Thanks!

**Comment by 4n70w4** [comment]
https://github.com/callumlocke/json-formatter/issues/152
