### ISSUE TITLE
'when' method in API resource calls 2nd parameter even the coniditan was false

### ISSUE THREAD

**Issue by foremtehan** [laravel/framework#30732]
- Laravel Version: 6.3
- PHP Version: 7.3
- Database Driver & Version: 5.0 mysql

### Description:

As my understanding from doc `when` method checks the condition, then includes the attribute

> Sometimes you may wish to only include an attribute in a resource response if a given condition is met

### Steps To Reproduce:

```php
class ThreadResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param Request $request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'id'   => $this->id,
            'title' => $this->title,
            'optional_column' => $this->when($this->myBoolMethod(), $this->pivot->column)
        ];
    }
}
```

Even the `$this->myBoolMethod()` returns false the `$this->pivot->column` will executed :

```
Trying to get property 'column' of non-object
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
