### ISSUE TITLE
Different context for Job's "failed" method.

### ISSUE THREAD

**Issue by Aferz** [laravel/framework#30739]
- Laravel Version: 6.6.0
- PHP Version: 7.3.12
- Database Driver & Version: MySQL 5.7

### Description:

The failed method is executed in a different context instead of using the current one at the time the job crashed.

### Steps To Reproduce:

I'll put a little piece of code instead of steps:

```php
class ExampleJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    /**
     * @var Dep
     */
    public $dep;

    /**
     * @var Client
     */
    public $client;

   /**
     * @var bool
     */
    protected $flag = true;

    public function __construct(Dep $dep)
    {
        $this->dep = $dep;
    }

    public function handle(Client $client): void
    {
        $this->client = $client;

        try {
          $this->client->doThings();
        } catch (\Exception $e) {
          $this->flag = false;

          $this->fail($e);
        }
    }

    public function failed(Exception $exception)
    {
        if ($this->flag === false) {
            // This is never executed, because $this is the 
            // very initial $this, due to  Laravel queue handler.
        }

        // $this->client is null here.
    }
}
```

The Code is self-explanatory, but the main problem is when the failed method is called, instead of using the current instance, the Queue Handler deserializes again the payload of the job, which gets the initial state of the job.

This forces you to make all your instance properties "immutable" because if you change any it won't be reflected in the failed method.

Of course, the same applies to instance properties added in "handle" invocation. All property assignations are not going to be reusable in the "failed" method, which IMO I find it useful to not being forced to pass them via arguments to every method I've created in my job.

Is this on purpose? If it really is, this is extremely confusing because "$this" doesn't is the expected "$this" inside the "failed" method. It gives you a completely different instance.

**Reference:**
\Illuminate\Queue\CallQueuedHandler@failed

**Comment by driesvints** [comment]
Heya, yes this is on purpose and the way it currently works. Unfortunately you don't have DI in the failed method atm. You could use the `app` helper to resolve dependencies though. If you'd like to make an improvement to this it's best that you open up an issue on the ideas repo. Thanks.

**Comment by Aferz** [comment]
It's not really DI what bothers me, because it can be used with app helper.

Is the fact that is counter-intuitive. This is not some of the magic which Laravel get us used to. This is something really weird that goes against the basic knowledge of OOP programming. "'this' is 'this' everywhere, excepting this little method here".

To be clear. I'm ok if this works like this. I just want to point it out to future issues. And maybe we should clarify this in the docs. It seems something that needs to be explained.

I'll open a PR to the docs when I get my laptop.

Just for curiosity: why this works like this? Why would be a problem in calling the failed method with the current job context? @driesvints @taylorotwell 

If I can understand it maybe I could try to figure a solution out and open a PR.

Thanks!
