### ISSUE TITLE
Route helper generate url with domain instead of APP_URL

### ISSUE THREAD

**Issue by meyer59** [laravel/framework#30740]
- Laravel Version: 6.6
- PHP Version:7.3
- Database Driver & Version: mysql 7.26

### Description:
I wrote the issue here https://github.com/laravel/nova-issues/issues/2194
They said it is more a Laravel issue than a nova issue.
Any solution to that ?
Cordially

**Comment by driesvints** [comment]
We've done some investigation into this. Please check https://github.com/laravel/nova-issues/issues/2194#issuecomment-561209398
