### ISSUE TITLE
TransactionCommitted event doesn’t contain transaction level I’d expect it to

### ISSUE THREAD

**Issue by martinbean** [laravel/framework#30756]
- Laravel Version: 6.6.1
- PHP Version: 7.3.11
- Database Driver & Version: MySQL 5.7.27

### Description:
When the `TransactionCommitted` event is dispatched, it seems to contain the transaction level _after_ the transaction has been committed, rather than the transaction level the connection was at when the transaction was committed.

For example, if I begin a transaction, that dispatches a `TransactionBeginning` event and the transaction level on the connection is incremented to `1`. When that transaction is committed, a `TransactionCommitted` event is dispatched but the transaction level is `0`. I’d expect the transaction level for the corresponding `TransactionCommitted` event to be `1` as well, so I can listen for when a transaction is started and committed.

### Steps To Reproduce:
1. Start a transaction. Transaction level in `TransactionBeginning` event is `1`.
2. Commit transaction. Transaction level in `TransactionCommitted` event is `0` (one less than transaction level in `TransactionBeginning` event).

## Test Code

I created a simple route that writes a row within a transaction, and set up listeners on the `TransactionBeginning` and `TransactionCommitted` events to log the transaction level:

```php
Route::get('/', function () {
    DB::transaction(function () {
        App\User::create([
            'name' => 'John Doe',
            'email' => sprintf('john.doe+%s@example.com', uniqid()),
            'password' => Hash::make('password'),
        ]);
    });

    return response('Done.');
});
```
```php
<?php

namespace App\Listeners;

use Illuminate\Database\Events\ConnectionEvent;
use Illuminate\Support\Facades\Log;

class LogTransactionLevel
{
    public function handle(ConnectionEvent $event)
    {
        Log::debug(
            sprintf('Transaction level for %s event is %d', get_class($event), $event->connection->transactionLevel())
        );
    }
}
```

Contents of log file after hitting route:

```
[2019-12-04 13:12:53] local.DEBUG: Transaction level for Illuminate\Database\Events\TransactionBeginning event is 1  
[2019-12-04 13:12:53] local.DEBUG: Transaction level for Illuminate\Database\Events\TransactionCommitted event is 0  
```

**Comment by driesvints** [comment]
Hmm I can indeed see that as problematic. Appreciating a PR if you could whip up one. Thanks for reporting.

**Comment by martinbean** [comment]
@driesvints Thanks for confirming! Will work on a PR 🙂

**Comment by driesvints** [comment]
Probably master

**Comment by AReyes-cl** [comment]
> @driesvints Thanks for confirming! Will work on a PR 🙂 What branch should I open the PR against?

Please read https://laravel.com/docs/6.x/contributions

**Comment by martinbean** [comment]
@AReyes-cl Was that really necessary? @driesvints already gave an answer. A week ago.

I wasn’t sure whether this was a bug fix or a “major new feature”, which is why I asked.

**Comment by simoebenhida** [comment]
@martinbean I think it makes sense that `TransactionCommitted` returns `$transactions - 1` since it means that the previous transaction has been resolved or committed ?

**Comment by denvit** [comment]
@martinbean according to the docs [https://laravel.com/docs/6.x/contributions#which-branch](https://laravel.com/docs/6.x/contributions#which-branch):

> All bug fixes should be sent to the latest stable branch or to the current LTS branch. Bug fixes should never be sent to the master branch unless they fix features that exist only in the upcoming release.

**Comment by driesvints** [comment]
@denvit an answer was already provided for this and someone already noted this above. 

I'm going to lock this as I believe there isn't really anything left to discuss here. Anyone's free to pr in a fix for this.

**Comment by driesvints** [comment]
PR was merged.

**Comment by driesvints** [comment]
https://github.com/laravel/framework/pull/30883
