### ISSUE TITLE
Vendor:publish --provider=* does not seem to work

### ISSUE THREAD

**Issue by MrMoonbag** [laravel/framework#30750]
Good day,

I can't seem to php artisan vendor:publish --provider={package name} to work.

I receive an error -> 'Unable to locate publishable resources.', which seems to be located in the function that tried to publish tags.

If I do php artisan vendor:publish, and select the index of the provider I wish to publish, it publishes, but with the argument --provider it does nothing but throw that error.

I hope I am not doing anything wrong?
![Screenshot from 2019-12-04 11-07-04](https://user-images.githubusercontent.com/46529598/70128811-3f33a780-1686-11ea-9e85-6830fa4b736b.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by LorenzoSapora** [comment]
For future reference: it required double quotes around the package name.

`php artisan vendor:publish --provider="Some\Package\Name"`
