### ISSUE TITLE
Missing required parameters for route if parameter is zero

### ISSUE THREAD

**Issue by alex-LE** [laravel/framework#30751]
- Laravel Version: 6.6.1
- PHP Version: 7.2.21

### Description:
After upgrading from 6.6.0 to 6.6.1 the route() helper produces a "Missing required parameters for ..." Exception for some of my routes when one parameter is 0.

### Steps To Reproduce:

The route looks like this:
`Route::get('order/{order}/status/{status}', 'OrderController@changeStatus')->name('order.change_status');`

Controller method:

`public function changeStatus(Order $order, $status)`

this works:

`route('order.change_status', ['order' => $order, 'status' => 1])`

but this not:

`route('order.change_status', ['order' => $order, 'status' => 0])`

even if i add `->where('status', '[0-9]+')` to the route it doesn't work.

**Comment by driesvints** [comment]
Gonna close this in favor of https://github.com/laravel/framework/issues/30760
