### ISSUE TITLE
Resource::withoutWrapping(); is not working

### ISSUE THREAD

**Issue by punithht** [laravel/framework#30753]
I added (Resource::withoutWrapping();) to AppServiceProvider but data key still persist for all the responses.
ProfileController : 
public function show($id)
    {
        $user_detail = User_profile::with('user')->where('user_id', $id)->first();
        return new ProfileResource(['user_detail' => $user_detail]);
    }

**In Profile Resources i have added below code.**
public function toArray($request)
    {
        return parent::toArray($request);
    }

    public function with($request)
    {
        return [
            'module_version' => '1.0.0',
            'author_url' => url('https://www.domain.com')
        ];
    }

Here is the json response in postman :--
{
    "data": {
        "user_detail": {
            "user_profile_id": 1,
            "user_id": 1,
            "loc_id": 1,
            "family_id": null,
            "first_name": "punith",
            "middle_name": "ht",
            "last_name": "paduval",
            "date_of_birth": "1993-12-04",
            "gender": "Male",
            "house_number": "55",
            "photograph": "5183_images (2).jpg",
            "full_name": "punithhtpaduval",
            "created_at": "2019-12-04 07:40:12",
            "updated_at": "2019-12-04 07:40:40",
            "user": {
                "id": 1,
                "email": "test@gmail.com",
                "country_code": "91",
                "phone_number": "9999999999",
                "email_verified_at": null,
                "status": "1",
                "verified": null,
                "created_at": "2019-12-04 07:40:11",
                "updated_at": "2019-12-04 07:40:40"
            }
        }
    },
    "module_version": "1.0.0",
    "author_url": "https://www.domain.com"
}

I want to remove "data" key from this json. Could you please help me to resolve this?.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
