### ISSUE TITLE
TranslatorInterface not compatible with LocalAwareInterface

### ISSUE THREAD

**Issue by ampersand** [laravel/framework#30769]
- Laravel Version: 6.6.2
- PHP Version: 7.3.10
- Database Driver & Version: ?

### Description:
Running `composer update` will install:
- symfony/translation (4.4.1)
- symfony/translation-contracts (2.0.1)

Within these packages TranslatorInterface extends from LocalAwareInterface.  However  the `setLocale` methods are not compatible.

- [TranslatorInterface::setLocale](https://github.com/symfony/translation/blob/v4.4.1/TranslatorInterface.php#L62)
- [LocaleAwareInterface::setLocale](https://github.com/symfony/translation-contracts/blob/v2.0.1/LocaleAwareInterface.php#L23)

The results in the following error being generated.
> Declaration of Symfony\Component\Translation\TranslatorInterface::setLocale($locale) must be compatible with Symfony\Contracts\Translation\LocaleAwareInterface::setLocale(string $locale) 

### Steps To Reproduce:

```
composer update
```

**Comment by driesvints** [comment]
I think you'd want to report this on the symfony repository and not the Laravel repo.
