### ISSUE TITLE
Memory leak from symfony console component

### ISSUE THREAD

**Issue by Sunappnio** [laravel/framework#30779]
- Laravel Version: 6.5.2
- PHP Version: 7.2.25
- Database Driver & Version:

### Description:
our laravel queue worker has a  memory leak issue, after some debugging, i found that it's related to symfony console output component.

### Steps To Reproduce:
fresh install of laravel, generate a console command,  write a big while loop like:

while(true) {
 $this->line('xxxx');
}

the memory usage just keeps growing.

To debug this. "print debug log" is not useful, simply add some sides effects to the file 
https://github.com/symfony/console/blob/master/Output/BufferedOutput.php, notice that doWrite() is called on every output but  fetch() is never called, so the internal string length keeps growing and cause a memory leak.

This isn't a problem for short-live commands like "php artisan make:controller XXX", but will cause memory leak for long running console commands. This affects both laravel 5 and laravel 6, I believe the bug came from this commit https://github.com/symfony/console/commit/21fe51593bc84b5f132b69a4abf5fb3c949afab9

**Comment by driesvints** [comment]
Please report this on the symfony issue tracker.
