### ISSUE TITLE
Validator `gt` `lt` `gte` `lte` don't work.

### ISSUE THREAD

**Issue by allowing** [laravel/framework#30773]
- Laravel Version: 6.6.0
- PHP Version: 7.4.0beta4
- Database Driver & Version: MySQL 5.7

### Description:

Validator `gt` `lt` `gte` `lte` don't work.

### Steps To Reproduce:

See the pics
![批注 2019-12-06 172244](https://user-images.githubusercontent.com/20262949/70312136-f29ac880-184d-11ea-9868-9161a4b52077.png)
![批注 2019-12-06 172346](https://user-images.githubusercontent.com/20262949/70312137-f3335f00-184d-11ea-8a57-c484ae9413df.png)

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
