### ISSUE TITLE
 PHP Fatal error: Uncaught RedisException: LOADING Redis is loading the dataset in memory

### ISSUE THREAD

**Issue by sohrabafard** [laravel/framework#30775]
- Laravel Version: 5.8.35
- PHP Version: 7.3.11
- Database Driver & Version: Mariadb 
- Session && cache: Redis

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
