### ISSUE TITLE
WithBatchInsert not firing static::creating and static::created events

### ISSUE THREAD

**Issue by jangraviren** [laravel/framework#30771]
- Laravel Version: 5.8.35
- PHP Version: PHP 7.3.4
- Database Driver & Version: mysql & Mysql 8 

### Description:
Everything is working fine when I am bulk importing the records using Laravel Excel (maatwebsite/excel~3.1). Issue starts when I enabled the WithBatchInserts. On batchSize 1, its working fine but more than 1, its not firing the creating and created events. 

As context, I am importing list of companies. After successful company insert, I need to attach them to the particular user and need to create admin user account for these companies. I am doing attaching and admin user creation when static::created event is firing. On static::creating boot event I am adding some extra information to the model details like Uuid generation etc. 

```
protected static function boot()
    {
parent::boot();
static::creating(function($model){
            $model->uuid = Uuid::generate()->string;
        });
static::created(function ($model) {
            $model->onModelCreated();
        });
}

protected function onModelCreated() {       
            $this->attachEntityToParent();
            $this->registerCompanyAdminUser();        
    }

....
```
So everything is working fine until I have enabled multiple inserts. Is I am doing something wrong or events will not fire in this multiple inserts.  

### Steps To Reproduce:
1. Use maatwebsite/excel~3.1 package, I am sure issue might be with normal multiple inserts too. Haven't tested yet.
2. Create a company eloquent.
3. Register boot static::creating and static::created events.
4. Now, create a CompanyImport class and try enable/disable WithBatchInserts
5. You will see events will not fire when batchSize is more than 1.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
