### ISSUE TITLE
Blade directive using quoted parameter value

### ISSUE THREAD

**Issue by ionesculiviucristian** [laravel/framework#30785]
- Laravel Version: 6.6.2
- PHP Version: 7.2.25

### Description:
When I declare a custom blade directive, the argument's value is wrapped around '', which is not what I want. For example if I pass the string 
```php 
'gdpr-cookie-notice/script.js' 
``` 
as the argument, I'm expecting $script to be 
```php
"gdpr-cookie-notice/script.js"
``` 
and not 
```php
"'gdpr-cookie-notice/script.js'"
``` 
when using dd();

### Steps To Reproduce:
I have made a BladeServiceProvider to declare some directives like this one:
```php
    public function boot()
    {
        Blade::directive('script', function ($script) {
            dd($script);
        });
    }
```
and use it in my views like this:
```php
    @script('gdpr-cookie-notice/script.js')
```

**Comment by driesvints** [comment]
This is the way custom directives work. You don't pass in arguments which you can immediately use. You pass in arguments which you can compile as a php execution. See the docs here: https://laravel.com/docs/6.x/blade#extending-blade

**Comment by ionesculiviucristian** [comment]
That should do also. Thanks for the reply.
