### ISSUE TITLE
[7.x] Pivot models' table names should be automatically pluralized

### ISSUE THREAD

**Issue by stancl** [laravel/framework#30788]
- Laravel Version: 6.6.0
- PHP Version: 7.2
- Database Driver & Version: sqlite

### Description:

Pivot models' table names are not automatically pluralized like normal models' table names.

### Steps To Reproduce:

```php
class ProductOption extends Pivot
{
    protected $table = 'product_options';

    // ...
}
```

Without the `$table` property, running `ProductOption::find()` will look into the `product_option` table.

IMO This should be either documented or changed in 7.x.

**Comment by devcircus** [comment]
Pivot tables have always been the singular version of each table, more specifically the model names, in alphabetical order. It's documented that way. Unless I'm misunderstanding what you're saying. 
https://laravel.com/docs/6.x/eloquent-relationships#many-to-many

**Comment by stancl** [comment]
Hmm, makes sense. Didn't see it mentioned in the section about using custom Pivot classes for the relationships.
