### ISSUE TITLE
Request Class validation not failing on first rule hit.

### ISSUE THREAD

**Issue by gokigoks** [laravel/framework#30789]
- Laravel Version: 5.8.35
- PHP Version: 7.2.11

Description: I have 2 parameters on an API endpoint. One takes either an Array or a String, the 2nd parameter determines the type of the first parameter). 
Here is my rule. `'foo' => 'required|string|digits_between:3,50'`
Problem is that this throws array to string conversion when passed with an array. I had the idea that the Validator immediately fails just from the string rule. 

Steps To Reproduce: Create a validator class which has 2 parameters. One parameter with a dynamic data type, and the 2nd which determines the type then use this rule.

 `'foo' => 'required|string|digits_between:3,50'`

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
