### ISSUE TITLE
Notification not escaped

### ISSUE THREAD

**Issue by himan72** [laravel/framework#30787]
- Laravel Version: 6.6.1
- PHP Version: 7.3.5
- Database Driver & Version:

### Description:
Mail Notification line got a &lt;code> tag added to the rendered html.

### Steps To Reproduce:
Send a mail notification

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
