### ISSUE TITLE
Event generater did not work as expectation with third party events

### ISSUE THREAD

**Issue by ac1982** [laravel/framework#30796]
- Laravel Version: 6.6.2
- PHP Version: 7.3.12
- Database Driver & Version: MySQL & 5.7.22

### Description:
```php artisan event:generate //get something wrong.```

### Steps To Reproduce:
Case A works fine
```
//A
protected $listen = [
    \Overtrue\LaravelWeChat\Events\WeChatUserAuthorized::class => [
    	'App\Listeners\RegisterUser',
    ],
];
```

Case  B generate a listener with wrong event ```App\Events\Overtrue\LaravelWeChat\Events\WeChatUserAuthorized```
```
//B
protected $listen = [
   'Overtrue\LaravelWeChat\Events\WeChatUserAuthorized' => [
    	'App\Listeners\RegisterUser',
    ],
];
```

Case C get the right event in listener, but listener dose not work as expectation, it never be called.
```
//C
protected $listen = [
   '\Overtrue\LaravelWeChat\Events\WeChatUserAuthorized' => [
    	'App\Listeners\RegisterUser',
    ],
];
```

**Comment by driesvints** [comment]
Just don't get the name wrong when generating events I guess?
