### ISSUE TITLE
restore with hasManyThrough throws ambiguous 'deleted_at'

### ISSUE THREAD

**Issue by krgaurav1992** [laravel/framework#30808]
- Laravel Version: 5.8.35
- PHP Version: 7.2.1
- Database Driver & Version: MySQL 5.7

### Description:
"Column 'deleted_at' in field list is ambiguous" is thrown when trying to restore model with relationship on hasManyThrough.

### Steps To Reproduce:

Model:
```php
class Category extends Model {
 public function articles() {
        return $this->hasManyThrough(Article::class, Section::class);
    }
}
```

```php
class Section extends Model {
 public function articles() {
    	return $this->hasMany(Article::class)->orderBy('sort_order', 'asc');
    }
}
```
Controller:
```php
public function restore(){
        $cat = \App\Models\Category::find(19);
        $cat->articles()->withTrashed()->restore(); // This is where error occurs
}
```

Error Messaage:
Illuminate \ Database \ QueryException (23000)
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'deleted_at' in field list is ambiguous (SQL: update `articles` inner join `sections` on `sections`.`id` = `articles`.`section_id` set `deleted_at` = ?, `articles`.`updated_at` = 2019-12-11 06:16:48 where `sections`.`deleted_at` is null and `sections`.`category_id` = 19)

As far as I understand we need to mention table name when using joins and deleted_at does not have table name like `article.deleted_at` but as it seems in query it only has `deleted_at = ?`

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by kdion4891** [comment]
Good news then @driesvints because this happens on Laravel 6 as well.

**Comment by driesvints** [comment]
This isn't possible atm afaik. Maybe https://github.com/laravel/framework/pull/31070 will solve this?

**Comment by kdion4891** [comment]
It's not a huge problem but it exists. It can easily be resolved by prepending pivot table names to the columns in the queries.
