### ISSUE TITLE
Eloquent, QueryBuilder: needless copying of PHP arrays

### ISSUE THREAD

**Issue by brandon942** [laravel/framework#30805]
- Laravel Version: 6
- PHP Version: 7.3
- Database Driver & Version:

### Description:
I see all Eloquent, QueryBuilder (, and other) API functions take arrays by value, not by reference, and pass them around from method to method many times. And there is a ton of nesting in the framework. The problem is PHP arrays are copied, including all their values (unless the value is a class instance), when they are assigned from one variable to another. The copying of arrays creates a lot of unnecessary work and increases the memory footprint as new arrays are created and held in memory on every nesting level. It's a needless waste of resources that I find unacceptable, since these arrays can be large and hold a lot of data. To me that's a flaw in the framework. 
  

Now I understand that people want to be able to do this:
`DB->table($table)->insert(["column1"=>"c1", "column2"=>"c2", ...])`  
which cannot be passed by reference because the array would first need to be assigned to a variable. To fix that, one could accept a one-time copying of the array and use references internally, or switch to \stdClass and stop using arrays entirely, which in the example above amounts to adding a (object) cast:
`DB->table($table)->insert((object)["column1"=>"c1", "column2"=>"c2", ...])`  
that still wouldn't be ideal because it involves creating an array and then creating an object - all because PHP lacks an easy way to initialize objects, but that's a flaw in PHP. To me it's still preferable since table rows are already returned as objects and JSON strings are decoded into objects by default.

**Comment by vlakoff** [comment]
No, PHP is smart enough and doesn't duplicate the array internally. PHP would create a new array only if modifying the original array. As long as the array is passed as-is from functions to functions, possibly reading it, but not modifying it, there is only one copy of the array in memory.

**Comment by brandon942** [comment]
@vlakoff Are you sure about that? PHP is a dynamic language. That means it is impossible for an interpreter to know whether an array will be modified or not. Expressions like the one below can only be resolved at runtime and at that point the array either exists as a new one or as an an existing one. The test shows it's a new one.  

$a = [55];  
function f($a)  { 
    ${implode(["a"])}[0] = 66;  
    echo $a[0]; // 66   
}  
f($a);  
echo $a[0]; // 55

**Comment by vlakoff** [comment]
Yes, don't worry. It's known as "lazy copy" or "copy on write", and it's a PHP fundamental.

Some reading about this:
* [Will copy-on-write prevent data duplication on arrays?](https://stackoverflow.com/questions/11074970/will-copy-on-write-prevent-data-duplication-on-arrays/11075245#11075245)
* [Memory management](http://www.phpinternalsbook.com/php5/zvals/memory_management.html)

In your example, you are indeed modifying the array, hence the need for a copy…

**Comment by brandon942** [comment]
@vlakoff Well that's good to know. I didn't know about "copy on write". Thanks for clearing that up.
