### ISSUE TITLE
Eager loading with cursor (lazy collections)

### ISSUE THREAD

**Issue by G3z** [laravel/framework#30804]
Hello, I noticed eager loading is ignored works when fetching entities with cursors (kinda makes sense, extra magic is probably needed)

I think this should throw an error if it's not supported
```
>>> ServiceTimeSlot::with(['service'])->cursor()->all()
=> [
     App\ServiceTimeSlot {#3678
       service_id: 1,
       time_table_id: 1,
       week_day: 0,
       start_at: "10:44:46",
       end_at: "11:44:00",
     },
   ]
```

```
>>> ServiceTimeSlot::with(['service'])->get()
=> Illuminate\Database\Eloquent\Collection {#3677
     all: [
       App\ServiceTimeSlot {#3688
         service_id: 1,
         time_table_id: 1,
         week_day: 0,
         start_at: "10:44:46",
         end_at: "11:44:00",
         service: App\Service {#3703
           id: 1,
           name: "Prof. Richie O'Connell",
           description: "Eos perspiciatis aut officia enim.",
           price: 4.0,
           cost: 9.0,
           slot_count: 3.0,
           created_at: "2019-11-13 08:55:30",
           updated_at: "2019-11-13 08:55:30",
           needs_doctor: 1,
           admin_only: 1,
           show_frontend: 1,
           organization_id: 1,
           color: "#00dd99",
           partecipants: 7,
           is_course: 0,
         },
       },
   ]
}
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by heiswald** [comment]
Hi there, would it be implemented? 
Because, in my opinion, it is a very useful functionality, especially that in result we have instance of the Eloquent Model (when iterating LazyCollection), so it would be great if we are able to eager load relations when using, f.e. 64 rows per cursor query...

**Comment by garygreen** [comment]
@driesvints I think this needs to be revisited. Ran into this problem and noticed eager loading is totally ignored when using `->cursor()` it's most strange behaviour. Should probably throw an exception if eager loading is detected and using `cursor`, or ideally support it.

**Comment by driesvints** [comment]
@garygreen please see the docs: https://laravel.com/docs/10.x/eloquent#cursors

<img width="795" alt="Screenshot 2023-03-23 at 07 45 16" src="https://user-images.githubusercontent.com/594614/227124512-9a4080ee-d24e-4ec4-8ecd-c462a50601e2.png">
