### ISSUE TITLE
Custom validation rule does not work

### ISSUE THREAD

**Issue by guilhermeagirardi** [laravel/framework#30815]
- Laravel Version: 6.7.0
- PHP Version: 7.3.6

### Description:
Hi guys!

I am trying to create a custom validation rule, but I am not succeeding.

For some reason the `passes()` function is not executed and my rule is ignored.

Check out my source code:

app/Http/Requests/TriggerRequest.php
```php
<?php

namespace App\Http\Requests;

use App\Rules\TestRule;
use Illuminate\Foundation\Http\FormRequest;

class TriggerRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize() {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules() {
        return [
            'subject' => 'required',
            'body' => 'required',
            'action_id' => 'required|integer',
            'event_id' => 'required|integer',
            'status' => 'in:ACTIVE,INACTIVE',
	    'to' => [new TestRule]
        ];
    }
}
```

app/Rules/TestRule.php
```php
<?php

namespace App\Rules;

use Illuminate\Contracts\Validation\Rule;

class TestRule implements Rule
{
    /**
     * Create a new rule instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Determine if the validation rule passes.
     *
     * @param  string  $attribute
     * @param  mixed  $value
     * @return bool
     */
    public function passes($attribute, $value)
    {
        //Don't pass here
        return $value == 'foo';
    }

    /**
     * Get the validation error message.
     *
     * @return string
     */
    public function message()
    {
        return 'The validation error message.';
    }
}
```

Can someone help me?

King regards,

**Comment by gocanto** [comment]
does this happen even if rules are like below? 

```php
public function rules() {
        return [
             'to' => [new TestRule]
        ];
}
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
