### ISSUE TITLE
Different values for sum() in Query Builder and Eloquent  

### ISSUE THREAD

**Issue by tuytoosh** [laravel/framework#30810]
- Laravel Version: 5.6.*
- PHP Version: 7.2
- Database Driver & Version: MySQL - 10.2.23-MariaDB-log

It seems that there is a difference between result of `sum()` aggregation in Query Builder and Eloquent.

`User::where('role', '1')->sum('credit');` returns `194660`
`DB::table('users')->where('role', '1')->sum('credit');` returns `204660`

When I run following query in phpmyadmin: `SELECT SUM(credit) FROM users WHERE role = '0'` it returns : `204660`

_I got version of MySQL by running `SELECT VERSION() as version` in phpmyadmin and I don't know that it is same as what you want or not..._

**Comment by gerardnll** [comment]
It's hard to tell without code but it could be the SoftDeletes Trait.

**Comment by tuytoosh** [comment]
@gerardnll Thank you, it was the reason.
