### ISSUE TITLE
Fire event without listener get queued immediately

### ISSUE THREAD

**Issue by meyer59** [laravel/framework#30829]
- Laravel Version: 6.6.2
- PHP Version: 7.3
- Database Driver & Version: mysql 5.7

### Description:
Hi
I have multiple custom `event` in my app. I am using them to notify real time change through the `ShouldBroadcast` interface. I don't have any listener bind to them.
 When i am firing them, they are queued automatically event if i don't implement the `ShouldQueue` interface.
Here is the code in my event class:

```
class GetZoningEvent implements ShouldBroadcast
{
    //no traits at all
}
```
I am firing the event with the following code:
`event(new GetZoningEvent());`

I cannot change my queue settings to `sync` since i need for other jobs.

### Steps To Reproduce:
setup your queue to `database` (with the job table)
create an event `php artisan make:event testEvent`
set `QUEUE_CONNECTION=database` in your `.env`
fire the event `event(new testEvent());`

the event should be queued instead of being executed synchroniously

Cordially

**Comment by driesvints** [comment]
I think you need `broadcast` for that instead, not `event`.

```
broadcast(new testEvent());
```

**Comment by meyer59** [comment]
Same thing. Still add to the job table

**Comment by JackEllis** [comment]
@meyer59 What happens if you implement ShouldBroadcastNow instead?

**Comment by devcircus** [comment]
Like @JackEllis mentioned, your events should extend ShouldBroadcastNow. Broadcasting uses the queue by default which actually gives a better user experience in most cases. If you prefer to bypass this, implement ShouldBroadcastNow.

**Comment by driesvints** [comment]
I completely forgot about `ShouldBroadcastNow`. Thanks @JackEllis & @devcircus.

See https://laravel.com/docs/6.x/broadcasting#broadcast-queue

**Comment by meyer59** [comment]
Thank you guys!
