### ISSUE TITLE
Documented log driver "papertrail" not found

### ISSUE THREAD

**Issue by johankrijt** [laravel/framework#30826]
- Laravel Version: 5.8 and up

The documentation talks about "papertrail" being a supported channel driver for logging since Laravel 5.8, but using it results in a "Driver [papertrail] is not supported." error in the Laravels LogManager. Not sure if this is a bug or a documentation error.

**Comment by driesvints** [comment]
What does your `logging.php` file look like?

**Comment by johankrijt** [comment]
Hi Dries, I pulled the new config file and there it was. More of a documentation issue I think because papertrail is mentioned there as a driver, not a preconfigured monolog channel. Thanks for your help!
