### ISSUE TITLE
l not post api after clone project from git ( “CSRF token mismatch.” ) laravel 6.0 on mac os x

### ISSUE THREAD

**Issue by sarunopassawas** [laravel/framework#30831]
- Laravel Version: 6.0
- PHP Version: 7.3.9

### Description:

l not post api after clone project from git ( "CSRF token mismatch." ) laravel 6.0 on mac os

Steps after clone
1.composer install
2.npm install
3.Create a copy of your .env file 4.php artisan key:generate

Post api format

General

Request URL: http://127.0.0.1:8000/login
Request Method: POST
Status Code: 200 OK
Remote Address: 127.0.0.1:8000
Referrer Policy: no-referrer-when-downgrade

Response Headers

Connection: close
Content-type: text/html;
charset=UTF-8 Date: Fri, 13 Dec 2019 03:05:21 GMT Host: 127.0.0.1:8000
X-Powered-By: PHP/7.3.9

Request Headers

Accept: application/json, text/plain, /
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,th;q=0.8
Connection: keep-alive
Content-Length: 84 Content-Type: application/json;charset=UTF-8
Cookie: XSRF-TOKEN=eyJpdiI6IkxaNDc4UkdKQ0FJeDNxR0tVT3dEcmc9PSIsInZhbHVlIjoiTjdKQUo1OUNKV3ZmXC9NNnEreGdyNmtueVVYaVVseGVzeFAxanF2aFlyWm9nUVpKMm1EdlBaMTlaNFZQN0lHaFYiLCJtYWMiOiI4Y2M0ZTQ2YzNiMTllYzhiMWJhMTY0OTM4NDFhMmUwZmNmMTg2YWUxYWZkYTJiMzk1NGNhYTA0OWE2OGY0MmY5In0%3D; laravel_session=eyJpdiI6IlkyVjduS3ZMUnN2NU5tSHRxYURBSkE9PSIsInZhbHVlIjoiVVducUtRXC9xMHc0SGdvUEhqdlBTM2g1NTBscUw2MzdhRkR3RWxvZEtzajRrd2tvOEQwVURqcHViXC9RRDlTS3FDIiwibWFjIjoiZDNiZTA1M2I1MDkzZDM4ODQ3NTY4ZTQ2NjE0NGYzN2E0ZTRjNGMzYjU0OGQyNTNhZWIxYTRmMWVlNDhiNmFiNyJ9
Host: 127.0.0.1:8000
Origin: http://127.0.0.1:8000
Referer: http://127.0.0.1:8000/
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
X-CSRF-TOKEN: TaSalYsNVkqlI37gaRCKKw6QNzJE9UwyPKNISzV2
X-Requested-With: XMLHttpRequest
X-XSRF-TOKEN: eyJpdiI6IkxaNDc4UkdKQ0FJeDNxR0tVT3dEcmc9PSIsInZhbHVlIjoiTjdKQUo1OUNKV3ZmXC9NNnEreGdyNmtueVVYaVVseGVzeFAxanF2aFlyWm9nUVpKMm1EdlBaMTlaNFZQN0lHaFYiLCJtYWMiOiI4Y2M0ZTQ2YzNiMTllYzhiMWJhMTY0OTM4NDFhMmUwZmNmMTg2YWUxYWZkYTJiMzk1NGNhYTA0OWE2OGY0MmY5In0=

error message

exception: "Symfony\Component\HttpKernel\Exception\HttpException" file: "/Users/sarun/Documents/GitHub/lottothai-frontend/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php"
line: 223
message: "CSRF token mismatch."

The same code can be used normally on windown.

But the difference on windown
**Response Headers

Set-Cookie: XSRF-TOKEN=eyJpdiI6IjErRkVVSUhxclhWbHBvOEtXMFd2Mnc9PSIsInZhbHVlIjoidzNwejVHc21qUzl5Yk9sVFE5QkxhbFpDdjl3OGVJNG1yMmZGdW4zWXBHMkFJNXR2NWVYTVZGbzVOOVwvN0hnQjMiLCJtYWMiOiI0ODQzMzMwMWE1OGIwMjQ2ZTJmYjExZGIyODlmN2RlMDQ5M2Q4NjFmNDk5MjI1OTI5NGIyZjQwMjFjN2VlNjU2In0%3D; expires=Fri, 13-Dec-2019 05:34:01 GMT; Max-Age=7200; path=/
Set-Cookie: laravel_session=eyJpdiI6Ik84SmFleElLaWd4alJvM2NYa2hIdlE9PSIsInZhbHVlIjoic2ZPaW0yd3kwMkVlUWRmZ29rQnBKZlBadTh1N2J2Slpkd3dvcnpYbkE2UU45WkZCXC9vYUNxbXJra0NuMUJYNVYiLCJtYWMiOiJjZmY0NWJlNmQ4ZTQyYTY2MzhjZWRlZWE2MDNmNTI3YTYwOGI3OWQ2NjNjMzU2ZjhlMDgzMzE1NGY2YmVjY2ZhIn0%3D; expires=Fri, 13-Dec-2019 05:34:01 GMT; Max-Age=7200; path=/; httponly

But on the mac os the clone came down, not in this section**

Please help me. Thank you.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
