### ISSUE TITLE
Attach method using array not working properly

### ISSUE THREAD

**Issue by samuelhgf** [laravel/framework#30836]
- Laravel Version: 5.8
- PHP Version: 7.2
- Database Driver & Version:

### Description:

When using the attach method passing an array where the key is the id of the related table and the value is an array of other columns data to the pivot table... 

I need to pass the same key for different column data, but the far key override the other ones

### Steps To Reproduce:

```
$modelo->funcionarios()->attach([
        1 => ['funcionario_tipo' => 0],
        1 => ['funcionario_tipo' => 1],
        2 => ['funcionario_tipo' => 3]
    ]);
```

Trying this make that in database:

<img width="524" alt="Captura de Tela 2019-12-13 às 19 34 16" src="https://user-images.githubusercontent.com/16768378/70836636-8edd4600-1ddf-11ea-928c-af73945afd81.png">

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
