### ISSUE TITLE
Soft deleting collection using model observers leaves orphaned models.

### ISSUE THREAD

**Issue by jdbolts** [laravel/framework#30833]
- Laravel Version: 6.7.0
- PHP Version: 7.4.0
- Database Driver & Version: MySql 5.7.28

### Description:
When soft deleting a collection of models using a model observer, the 'deleting' event is not called on the model instances inside the collection resulting in orphaned models.

### Steps To Reproduce:
For example, consider a user model which has photos attached, those photos also have tags.
When deleting a user the model observer should delete the collection of photos, which in turn, should delete the tags, however, the tags will remain but the photos will be deleted.

**Comment by driesvints** [comment]
Can you maybe post a full code example that reproduces the problem?

**Comment by jdbolts** [comment]
Yes sure, consider the following model observer:
```
class UserObserver
{

    /**
     * Handle the user "deleting" event.
     *
     * @param  \App\Models\User  $user
     * @return void
     */
    public function deleting(User $user)
    {
        $user->photos()->delete();
    }
}
```
When deleting a user, the users photos should also be deleted when the 'deleting' event is fired.

```
class PhotoObserver
{

    /**
     * Handle the photo "deleting" event.
     *
     * @param  \App\Models\Photo  $photo
     * @return void
     */
    public function deleting(Photo $photo)
    {
        $photo->tags()->delete();
    }
}
```
And the above should also be executed when the photo is being deleted, thus deleting the tags which belonged to the photo.

However, intermittently, this is not the case and the tags still persist when they should be deleted.

Hope this helps?

**Comment by driesvints** [comment]
@staudenmeir do you maybe know what's going on here?

**Comment by staudenmeir** [comment]
Please post the code where you are soft-deleting the collection of models.

Does the observer work when you soft-delete a single model?

**Comment by alec-joy** [comment]
This is expected behaviour, the docs make a note of this. 

> When executing a mass delete statement via Eloquent, the deleting and deleted model events will not be fired for the deleted models. This is because the models are never actually retrieved when executing the delete statement.

The tags aren't being deleted because $user->photos()->delete() doesn't fire the deleteing or deleted model events, so there is no even for your second listener to act on.

**Comment by jdbolts** [comment]
I must've missed this in the docs, I'll close the issue. Thanks.
