### ISSUE TITLE
Blade not able to parse array casted by Eloquent?

### ISSUE THREAD

**Issue by zyxxyzyxz** [laravel/framework#30830]
- Laravel Version: 6.0
- PHP Version: 7.4.0
- Database Driver & Version: MySQL 8.0.18

### Description:
I have a model `Transaction` that has a column `line_items`. The column is populated with a serialised json string. This is primarily used for invoice/receipt generation and keeping track of what the user purchased. I have a cast for this column inside my model like so;
```php
protected $casts = [
    'line_items' => 'array'
];
```

Now when I try even use a basic reference to this inside my blade template like so;
`{{ $transaction->line_items }}`

it errors with;
`Facade\Ignition\Exceptions\ViewException
[E_WARNING] htmlspecialchars() expects parameter 1 to be string, array given`

I'm not entirely sure if this is a bug or just me doing something wrong, but there is no documentation on it and every "solution" I've found involves some really messy double for-loop as well as inlining a `json_decode` inside the blade template and I'm not particularly keen on using that solution as it seems  not only unnecessary but also completely against the principle of Laravel imo.

**Comment by devcircus** [comment]
Definitely seems like the expected output. Take any array and stick it between curly braces and you should get the same.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
