### ISSUE TITLE
Schema builder does not create default value for "decimal" column type

### ISSUE THREAD

**Issue by jv2222** [laravel/framework#30842]
- Laravel Version: 5.8.35
- PHP Version: 7.1.29
- Database Driver & Version: mySQL 5.7.19

### Description:

Schema builder does not create default value for "decimal" column type

### Steps To Reproduce:

1) Create a new migration like:

```
Schema::create('test_table', function (Blueprint $table) {
    $table->increments('id');
    $table->decimal('test1', 5, 2)->defualt(0);
    $table->decimal('test2', 5, 2)->defualt('0');
    $table->decimal('test3', 5, 2)->defualt(1);
    $table->decimal('test4', 5, 2)->defualt('1');
    $table->decimal('test5', 5, 2)->defualt(1.5);
    $table->decimal('test6', 5, 2)->defualt('1.5');
    $table->nullableTimestamps();
});
```

2) Test columns will be created but no default value will be added.

3) However it does work from a mySQL point fo view because this works:

`\DB::statement('ALTER TABLE test_table ADD test1 decimal(5,2) DEFAULT 0');`

**Comment by brunogaspar** [comment]
You have typos, you're calling `defualt` it should be `default`.

Now, not sure why it does not trigger the method not defined error (or similar), but that's a different issue.

**Comment by jv2222** [comment]
Ack! How embarrassing. You are completely right.

Looking for someone or something to blame.... grr why didn't Atom underline
show it as spelling mistake.

But at the end of the day, I should have caught this.

Thanks so much!
