### ISSUE TITLE
API routes return 404

### ISSUE THREAD

**Issue by dukinfotech** [laravel/framework#30846]
- Laravel Version: 5.8.*
- PHP Version: 7.2.12
- Database Driver & Version:

### Description:

Although i ran php artisan route:list, api routes are shown but when I access apl routes from postman or browser, they return 404.
### Steps To Reproduce:
In file api.php
```
Route::get('/test', 'AuthController@test');
```
The web routes worked. but api route not working. Yesterday it worked perfectly but today they return 404. I also clear config cache and route cache and deleted vendor folder and reinstall composer

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
