### ISSUE TITLE
Custom api middleware does not automatically loaded

### ISSUE THREAD

**Issue by skyrocketeer** [laravel/framework#30859]
- Laravel Version: 6.6.2
- PHP Version: 7.2
- Database Driver & Version:

### Description: 
I registered a custom middleware route in Kernel file. In routes/api.php, I use group middleware for a resource of endpoints that is I define Route::middleware('name-of-my-middleware').
When I hit those endpoints that are protected by the customized middleware, it does not get to the middleware class but instead turn back to the original 'web' authenticate file.
If I explicit the middleware path (Route::middleware('path-to-the-middleware-class')) it works like a champ but only a workaround
What I want to say it is there any way to automatically load the middleware as in the first route writing style I mentioned above. In RouteService provider I also changed the middleware in mapapiroute function into my middleware name.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
