### ISSUE TITLE
invalid signature on email verification. Laravel 6

### ISSUE THREAD

**Issue by GIVasco** [laravel/framework#30850]
- Laravel Version: 6.0.x
- PHP Version: 7.2.24
- Database Driver & Version: mysql  Ver 15.1 Distrib 10.4.8-MariaDB

Hello guys, resently i post the same bug , but it was declined by the versions. (https://github.com/laravel/framework/issues/30594)
I did update my php and laravel workspace to the lasted versions but i got the same error ! 

I did set the .env file
APP_ENV=production
APP_URL=https://domain.co/
APP_USE_HTTPS=true

in the AppServiceProvider
public function boot(UrlGenerator $url)
{
URL::forceScheme('https');
}

In web.php and api.php
if (App::environment('production')) {
URL::forceScheme('https');
}

In UrlGentator file:
$url = str_replace("http://","https://", $url);

and in the TrustProxies file
protected $proxies = '*';

but I still getting the same error (403 | Invalid signature.) on the email verification!
someone can helpme ?

The lastes pages that i visit :
#26930
#25501
https://stackoverflow.com/questions/52917152/laravel-5-7-email-verification-throws-403
https://stackoverflow.com/questions/52525958/signed-route-for-email-verification-does-not-pass-signature-validation
https://laracasts.com/discuss/channels/laravel/hitting-403-page-when-clicking-verify-link-in-email-using-new-laravel-verification-57
https://laracasts.com/discuss/channels/laravel/email-verification-403-invalid-signature?page=0#reply=553418

**Comment by driesvints** [comment]
Please try a support channel first. As far as I can see the posts above weren't created by you. There might be some specific gotchas in your case which could leave to uncovering why it's not working for you specifically. If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by GIVasco** [comment]
man , i post this same bug in Laracasts Forums, StackOverflow but i dont got any answer ! 
really do you need make this more hard ?????

**Comment by driesvints** [comment]
Which of the links above were posted by you?

**Comment by devcircus** [comment]
At the very least, if you're wanting help debugging your app, you'll need to create a small repo on github that reproduces the problem. Otherwise, there's not much that can be done with the information provided.  

Just create an app with the smallest amount of code possible to reproduce the issue and when other devs get a chance, they can look at it and help you out. 

The support forums are still the best place to get help, but you have to provide enough information for others to be able to help. In this case, a small app is the best information you can provide.

**Comment by GIVasco** [comment]
> Por lo menos, si quiere ayuda para depurar su aplicación, necesitará crear un pequeño repositorio en github que reproduzca el problema. De lo contrario, no se puede hacer mucho con la información proporcionada.
> 
> Simplemente cree una aplicación con la menor cantidad de código posible para reproducir el problema y cuando otros desarrolladores tengan la oportunidad, puedan verlo y ayudarlo.
> 
> Los foros de soporte siguen siendo el mejor lugar para obtener ayuda, pero debe proporcionar suficiente información para que otros puedan ayudar. En este caso, una pequeña aplicación es la mejor información que puede proporcionar.

Hello, yes, The problem is that i dont have this problem using laravel localy, the problem is when i post my app on a server and y add the SSL certificate! 
i have 3 workspace (develop, testing and production) and in develop and testing , it works fine, but in the production server i have the problem !

**Comment by GIVasco** [comment]
> Which of the links above were posted by you?

let me find them !

**Comment by GIVasco** [comment]
> Which of the links above were posted by you?

" i post this same bug in Laracasts Forums, StackOverflow but i dont got any answer !" Correction, was Github and laracast!

https://laracasts.com/discuss/channels/laravel/email-verification-403-invalid-signature
https://github.com/laravel/framework/issues/30594

**Comment by driesvints** [comment]
@GIVasco the github issue was closed because you reported it as an unsupported version. The Laracasts post wasn't created by you. Like I said: please try the support channels by posting yourself with your particularly issue. I suspect there's something specific failing for you. Most issues were related to SSL/middleware misconfiguration. Since it's working for you locally and not on production I suspect there's something specific on your production server going wrong.

**Comment by GIVasco** [comment]
> @GIVasco the github issue was closed because you reported it as an unsupported version. The Laracasts post wasn't created by you. Like I said: please try the support channels by posting yourself with your particularly issue. I suspect there's something specific failing for you. Most issues were related to SSL/middleware misconfiguration. Since it's working for you locally and not on production I suspect there's something specific on your production server going wrong.

man , i have many usernames ! ._.
look, i post the same text in different sites !
https://laracasts.com/discuss/channels/laravel/invalid-signature-on-email-verification-laravel-6-github-30850#
https://laravel.io/forum/invalid-signature-on-email-verification-laravel-6
https://stackoverflow.com/questions/59362592/invalid-signature-on-email-verification-laravel-6-github-30850
https://larachat.slack.com/archives/C039F76DN/p1576522575208700
and discord !
men , help me pleace ! i'm really stucked !

**Comment by jbroudou** [comment]
@GIVasco I had the same issue with Laravel 5.8

https://github.com/symfony/http-foundation/blob/0e96db44b3f84e6f3b02dc91d8f6798836974fc9/Request.php#L1132

This line if looking for 'HTTPS'. Try changing "APP_USE_HTTPS" to HTTPS

**Comment by hirenkeraliya** [comment]
If you are using an Nginx then in your Nginx configuration please change this line
`try_files $uri $uri/ /index.php?q=$uri&$args;` to  `try_files $uri $uri/ /index.php?$query_string;`
At the
`/etc/nginx/sites-available/[Project Name]`

**Comment by doncadavona** [comment]
Getting this issue on Fresh Laravel 8 on Homestead.
