### ISSUE TITLE
QueryBuilder locks do not work in joins with SqlServerGrammar

### ISSUE THREAD

**Issue by tonila** [laravel/framework#30852]
- Laravel Version: 5.8.19
- PHP Version: 7.3.11
- Database Driver & Version: 
Microsoft ODBC Driver 17 for SQL Server 

### Description:

SqlServerGrammar does not support locks inside joins.

I have the following code:

```
$query = DB::table('test.dbo.ROWS as R')->lock('WITH(NOLOCK)')
    ->select('*')
    ->join('test.dbo.COLUMNS as C', function ($join) {
        $join->on('C.row_id', '=', 'R.id')
            ->lock('WITH(NOLOCK)');
    })
    ->where('R.ID', '>', 0);
```

### Actual resulting SQL

```
select * from [test].[dbo].[ROWS] as [R] WITH(NOLOCK) 
    inner join [test].[dbo].[COLUMNS] as [C] 
    on [C].[row_id] = [R].[id] where [R].[ID] > '0'""
```

### Expected resulting SQL

```
select * from [test].[dbo].[ROWS] as [R] WITH(NOLOCK) 
    inner join [test].[dbo].[COLUMNS] as [C] WITH(NOLOCK) 
    on [C].[row_id] = [R].[id] where [R].[ID] > '0'"
```

### How to fix?

Override Grammar.php compileJoins function in SqlServerGrammar.php and implement lock functionality.

```
    /**
     * Compile the "join" portions of the query.
     *
     * @param  \Illuminate\Database\Query\Builder  $query
     * @param  array  $joins
     * @return string
     */
    protected function compileJoins(Builder $query, $joins)
    {
        return collect($joins)->map(function ($join) use ($query) {
            $table = $this->wrapTable($join->table);

            /*
            I am not really an expert with MSSQL, so maybe someone knows proper way of implementing this...
            if (is_string($join->lock)) {
                $table = $table.' '.$join->lock;
            }
            else if (! is_null($join->lock)) {
                $table = $table.' with(rowlock,'.($query->lock ? 'updlock,' : '').'holdlock)';
            }*/

            $nestedJoins = is_null($join->joins) ? '' : ' '.$this->compileJoins($query, $join->joins);

            $tableAndNestedJoins = is_null($join->joins) ? $table : '('.$table.$nestedJoins.')';

            return trim("{$join->type} join {$tableAndNestedJoins} {$this->compileWheres($join)}");
        })->implode(' ');
    }
```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by tonila** [comment]
Hi,

Yes, I checked it persists with 6.x.

compileJoins does not implement lock.

https://github.com/laravel/framework/blob/6.x/src/Illuminate/Database/Query/Grammars/Grammar.php#L168

There is no specific implementation in SqlServerGrammar.php

https://github.com/laravel/framework/blob/6.x/src/Illuminate/Database/Query/Grammars/SqlServerGrammar.php

**Comment by driesvints** [comment]
Thanks for reporting. Feel free to send in a PR.

**Comment by dunhamjared** [comment]
@tonila Will you be working on this? 

I can implement this if you want.

**Comment by tonila** [comment]
@dunhamjared I don't have enough MS SQL server knowledge about locks to implement this properly, so feel free to implement.

**Comment by taylorotwell** [comment]
This isn't a documented feature of Laravel, nor have we attempted to implement it. As such, this is a feature request better suited for laravel/ideas repository.

**Comment by rodrigopedra** [comment]
@tonila this should work:

~~~php
$query = DB::table(DB::raw('test.dbo.ROWS as R WITH(NOLOCK)'))
    ->select('*')
    ->join(DB::raw('test.dbo.COLUMNS as C WITH(NOLOCK)'), function ($join) {
        $join->on('C.row_id', '=', 'R.id');
    })
    ->where('R.ID', '>', 0);
~~~

If there are no other join condition you can simplify it to:

~~~php
$query = DB::table(DB::raw('test.dbo.ROWS as R WITH(NOLOCK)'))
    ->select('*')
    ->join(DB::raw('test.dbo.COLUMNS as C WITH(NOLOCK)'), 'C.row_id', '=', 'R.id')
    ->where('R.ID', '>', 0);
~~~

I use it in a project that uses MS SQL Server.

In an eloquent model I usually add the following scope:

~~~php
public function scopeWithNoLock(Builder $builder)
{
    $builder->fromRaw($this->getTable() . ' WITH(NOLOCK)');

    return $builder;
}
~~~

So you can call it like this:

~~~php
return Model::withNoLock()->get();
~~~
