### ISSUE TITLE
Package:discover no longer working on 6.8.0

### ISSUE THREAD

**Issue by iamthefreeman** [laravel/framework#30866]
- Laravel Version: 6.8.0
- PHP Version: 7.3.7
- Database Driver & Version: N/A

### Steps To Reproduce:
Running `php artisan package:discover --ansi` will exit with the following error:
`An option with shortcut "s" already exists.`

**Comment by iamthefreeman** [comment]
Update: running any command (`php artisan`) results in `An option with shortcut "s" already exists.`

**Comment by driesvints** [comment]
I can run artisan just fine on 6.8.0. Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by iamthefreeman** [comment]
I've just downgrade to Laravel 6.7 and it's working correctly, then upgraded and i'm getting the issue again.

**Comment by devcircus** [comment]
The new option to generate seeders when generating models uses the "s" option now. Do you have a custom command with an "s" option?

**Comment by iamthefreeman** [comment]
I think that one of the packages I use may implement the `-s` option: `babenkoivan/scout-elasticsearch-drive`. 

Does this classify as a BC or should I create an issue on the repo?

**Comment by driesvints** [comment]
Extending the public api on a minor release isn't a BC break, no. It's best that you open up an issue on their repo.
