### ISSUE TITLE
Chaining views results in weird stack and section behaviour

### ISSUE THREAD

**Issue by sergiz** [laravel/framework#30863]
- Laravel Version: 6.7.0
- PHP Version: 7.2.24
- Database Driver & Version: none

### Description:
If you have a view that extends a view that depends on another (f.e. final extends middle, which extends base), then using `@section` and `@stack` result in a behaviour that I believe is not as intended.

### Steps To Reproduce:
Let's create a simple view route:
`Route::view('/test', 'final');`

And three views:
```
{{-- resources\views\base.blade.php --}}

@stack('content')
@yield('content')
```
```
{{-- resources\views\middle.blade.php --}}
@extends('base')
```
```
{{-- resources\views\final.blade.php --}}
@extends('middle')
```

a) Firstly, I will explain the `@stack`:
Let's push some content.
```
{{-- resources\views\middle.blade.php --}}
@push('content', ' middle')
```
```
{{-- resources\views\final.blade.php --}}
@push('content', ' final')
```

When we visit our /test route we get
> final middle

while I would expect to get 

> middle final

If we read the view file from the top to the bottom, I would expect that the push in the middle view would be executed before the one in final, since the final extends the middle one (so it is supposed to build on it).
The current behaviour kinda breaks the full functionality of stacks when you chain multiple views. There is no way to push to the bottom of the stack in the final view, since the views which it extends from will push their content after the final view. If we use `@prepend` in the middle view, then the final view's push content will be actually on the bottom, but then `@prepend` will have no effect since the middle view will always have its content at the first place.

b) And now moving on to `@section`:
Here we can mitigate the issue using the `@parent` directive. However, I would like to use a dedicated `@append` directive, but it gives me a different results than I would expect it to give.
```
{{-- resources\views\middle.blade.php --}}
@section('content')
    middle
@append
```
```
{{-- resources\views\final.blade.php --}}
@section('content')
    final
@append
```
Resullt: `final middle` - the order is wrong I believe, same problem as with stack.

```
{{-- resources\views\middle.blade.php --}}
@section('content')
    middle
@endsection
```
```
{{-- resources\views\final.blade.php --}}
@section('content')
    final
@append
```
Result: `final` - This is interesting.

Considering all said things, the only "stable" way I could think of to maintain a desired order of content from multiple chained views is using a traditional `@section` and `@parent`.

**Comment by driesvints** [comment]
The current behavior is the expected one. The most "child" view is the one you return and the one that is "rendered" first. Since there's probably a lot of apps our there expecting the current behavior we probably won't change this behavior anytime soon, sorry.

**Comment by sergiz** [comment]
It is indeed true, that you return the most child view, but does this behaviour make any sense?

You build you theme like:
1) some basic layout that includes elements that are shared by all views.
2) some more specific layout that extends the basic one, for example which is shown to all logged in users
3) a specific page that extends the previous layout with the main content that is displayed to the visitor.

I wanted to use stacks for my css/js includes (where latter ones depend on the previous, but sometimes you want to put something in front of everything else), but with the current behaviour that is not really possible (since the order is in the reverse at the end).

Anyway, thanks for you input. I understand it is hard to change that now, but I hope it can be considered some day.

**Comment by sergiz** [comment]
@driesvints I see that even official documentation states that stacks 
https://laravel.com/docs/6.x/blade#stacks

> [...] can be particularly useful for specifying any JavaScript libraries required by your child views [...]

but as I demonstrated above, they are really not unfortunately. Since the order is reverse, your child views' JS and CSS cannot really depend on that which is specified in parent's, which directly contradicts what documentation states as intended usage.

So I believe this would be worth looking into.

**Comment by driesvints** [comment]
@sergiz this would be too much of a breaking change unfortunately so we probably won't change this anytime soon. You're free to send in a pr to the docs if you believe something could be clarified better.
