### ISSUE TITLE
[Bug] New request instance mutating the original request when in phpunit

### ISSUE THREAD

**Issue by ajcastro** [laravel/framework#30872]
- Laravel Version: 5.8.35
- PHP Version: 7.2.11
- Database Driver & Version:

### Description:
I tried a simple code that will clone a request and change some params in the duplicate request. In the browser it is working fine but in phpunit the original request is also displaying the same value same with the duplicate request.

```php
public function index(Request $request)
    {
        $request->merge(['foo' => '100']);

        $dup = clone $request;
        $dup->merge(['foo' => '200']);

       // this is both 200 in phpunit but in browser it is correct, 100 and 200
        return [
            $request->foo, 
            $dup->foo, 
        ];

    }
```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
