### ISSUE TITLE
[Bug|Dupplication] Eloquent/Laravel generating duplicat model in database, but only once

### ISSUE THREAD

**Issue by ThaDaVos** [laravel/framework#30871]
- Laravel Version: 6.7.0
- PHP Version: 7.2.25
- Database Driver & Version: MySQL 5.7.x

### Description:
When running the below code, there is a duplicate generated for the Address Model, but only once...
Can't figure out why, even added extra saves after mutation didn't fix it...

### Steps To Reproduce:
See below code:

### Code
```PHP
    private function startDebugDuplicationTest() {
        $this->debugDuplication();
        $this->debugDuplication();
        $this->debugDuplication();
    }


    private function debugDuplication()
    {
        $customerModel = Customer::updateOrCreate([
            'id' => 9999,
        ], [
            'name' => 'Test Company',
            'created_via_import' => 1
        ]);

        $address = Address::updateOrCreate([
            'id' => $customerModel->postal_address_id
        ], [
            'street' => 'Testlane 666',
            'postal_code' => '1234 AB',
            'city' => 'Testcity',
            'created_via_import' => 1
        ]);

        $customerModel->postal_address()->associate($address);

        if ($customerModel->isDirty()) $customerModel->save();

        $this->info(json_encode([
            'Customer' => $customerModel,
            'Address' => $address
        ], JSON_PRETTY_PRINT));
    }
```

### Log output
See: https://termbin.com/f6bw

**Comment by ThaDaVos** [comment]
Is fixed by adding the following line after the `Customer::updateOrCreate` - did this change? If I remember correctly it wasn't needed...

#### Code
```php
if (!$customerModel->wasRecentlyCreated) $customerModel->refresh();
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
