### ISSUE TITLE
RedirectResponse tries to use non-existing session

### ISSUE THREAD

**Issue by VladReshet** [laravel/framework#30875]
- Laravel Version: 6.7.0
- PHP Version: 7.3.6
- Database Driver & Version:

### Description:
When session is disabled, validation error throws an exception, which cause creating \Illuminate\Http\RedirectResponse object, and calling withInput method. withInput method doesn't check if there is session, which cause "Call to a member function flashInput() on null" error

### Steps To Reproduce:
- Totally disable session
- Create custom request
- Create custom method "failedValidation"
- throw App\Exceptions\ValidationException with error message and error bag

**Comment by VladReshet** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/7568590/71098858-097cdb80-21bb-11ea-9a0e-cda58beabdf2.jpg)

**Comment by driesvints** [comment]
The problem here is that there's no way to properly make use of validation when sessions aren't enabled. Because the errors can't be held inside the session, there's no way to flash them to response. So I don't believe this is possible what you're trying to do.

**Comment by VladReshet** [comment]
I have the next base request class, which being extended by all my next custom request classes.

```
class BaseRequest extends FormRequest
{
    public $message;

    protected function failedValidation(Validator $validator)
    {
        throw (new ValidationException($validator))
                    ->setErrorMessage($this->message ?? Errors::REQUIRED_FIELDS)
                    ->errorBag($this->errorBag);
    }
}

```

My application it's an SPA (without session), so i just catch ValidationException in my middleware, and make special json response in case of validation error. Should i write my custom ValidationException class, instead of using App\Exceptions\ValidationException?

**Comment by driesvints** [comment]
I think I know what the problem is. If you're making API requests and you're hitting the `invalid` method of the exception handler, it means you're not sending the `application/json` accept header in your requests. When you do, the handler will call `invalidJson` and not make use of `withInput` because it's indeed, stateless.

https://github.com/laravel/framework/blob/6.x/src/Illuminate/Foundation/Exceptions/Handler.php#L258

Can you check if you're sending the proper headers with your API requests?

**Comment by VladReshet** [comment]
Yes, my API requests had "Accept: */*" header. It seems that it was a source of a problem. I have just tested it - yeah, it works! Thanks a lot, i think that issue can be closed.
