### ISSUE TITLE
Too few arguments to function Illuminate\Database\Eloquent\Model::setRawAttribute()

### ISSUE THREAD

**Issue by vaites** [laravel/framework#30884]
- Laravel Version: 6.8.0
- PHP Version: 7.3.11
- Database Driver & Version:  MariaDB 10.3.18

### Description:

Pull request #30853 introduced a bug when the `raw` attribute of a model is set:

> Too few arguments to function Illuminate\Database\Eloquent\Model::setRawAttribute(), 1 passed in /home/vaites/projects/laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php on line 619 and at least 2 expected

Also, as @goodeas said in the pull request, a model can't have a mutator for the `raw` attribute.

### Steps To Reproduce:

 Just set the `raw` attribute of any model:

```php
$user = new \App\User();
$user->raw = 'foo bar';
```

If `raw` attribute usage is not allowed, Laravel must throw an exception...

**Comment by devcircus** [comment]
Yes this is very unfortunate. Not technically a break, but “raw” is extremely common and will likely cause many problems. This should be looked at again, at least for version 7.

**Comment by driesvints** [comment]
Thanks for reporting. We're reverting the pr that caused this.

**Comment by vaites** [comment]
Thanks @driesvints

**Comment by driesvints** [comment]
Released v6.9.0 with this

**Comment by vaites** [comment]
I confirm it works again. Thanks @driesvints ...
