### ISSUE TITLE
Installation of Laravel using composer resulted in error saying “Class 'Route' not found”

### ISSUE THREAD

**Issue by boundariesg** [laravel/framework#30897]
- Laravel Version:  6.9 framwork
- PHP Version:  7.3.12
- Database Driver & Version:

### Description:
I have installed laravel using composer, however I get an error saying

Class Route not found

Why is that?

The error is:

Fatal error: Uncaught Error: Class 'Route' not found in C:\xampp\htdocs\laravel\routes\web.php:14 Stack trace: #0 {main} thrown in C:\xampp\htdocs\laravel\routes\web.php on line 14

I tried other classes none of them appear to be working I have the same error every time.

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
