### ISSUE TITLE
Accessing an external API

### ISSUE THREAD

**Issue by iBeef** [laravel/framework#30899]
I've just finished my first website and now moved to trying to learn react as I want to incorporate Js front end frameworks into my site. I've started doing it with Laravel as I've invested a fair bit of time into PHP and a lot of the jobs in my area are php based.

Everything has been going great until I've come across tutorials that want to access some external API's.

I came across one the other day that wanted me to access the pixabay api and had trouble with my requests being blocked by the cors policy. After many hours of googling and tinkering, I installed the barryVDH/laravel-cors module which also didn't work to my frustration. Eventually I came across the problem which was this line of code located in the bootstrap.js file laravel provides:

```window.axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';```

To get around this I created an instance of axios in another js file that I could call on that got rid of this header:

```
import axios from 'axios';

// Enables a axios without CSRF Token for cross domain requests that cause issues
let extAxios = axios.create();
delete extAxios.defaults.headers.common['X-Requested-With'];

export default extAxios;
```

This worked perfectly and enabled me to access the API with no issues so I thought I'd cracked how to access external APIs.

Fast forward to yesterday, I've got the same issue with another API but my old solution is not working and I'm absolutely lost on what to do.

The Api in question this time is the musixmatch API and I for the life of me can't get this to work nor can find any solution on the net.

So as before I have barryVDH/laravel-cors set up in my application as stated by their github page:

In my app.php we have:
```
        /*
         * Laravel Framework Service Providers...
         */

        ...

        Barryvdh\Cors\ServiceProvider::class,
```

In my kernel.php we have:
```
        protected $middleware = [

        ...

        \Barryvdh\Cors\HandleCors::class,
    ];
```

I'm using the same extAxios instance as last time:

```
extAxios(
    'https://api.musixmatch.com/ws/1.1/chart.artists.get?page=1&page_size=3&country=it&apikey=MY_API_KEY'
)
.then(res => console.log(res.data))
.catch(err => console.log(err));
```

Upon sending the request I get the following errors in my chrome console:

Access to XMLHttpRequest at 'https://api.musixmatch.com/ws/1.1/chart.artists.get?page=1&page_size=3&country=it&apikey=MY_API_KEY' from origin 'http://current-dev.test' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Error: Network Error
    at createError (index.js:745)
    at XMLHttpRequest.handleError (index.js:280)

Cross-Origin Read Blocking (CORB) blocked cross-origin response https://api.musixmatch.com/ws/1.1/chart.artists.get?page=1&page_size=3&country=it&apikey=MY_API_KEY with MIME type text/plain. See https://www.chromestatus.com/feature/5629709824032768 for more details.

If i make the request from my my web browser then it works fine and I get a json response.

I'm at a loss with this and I'm not sure what's happening to cause this so any help would really be appreciated as I was hoping to use laravel as a base to build full stack applications from now on.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by keremgocen** [comment]
Were you able to find a solution @iBeef?
