### ISSUE TITLE
Using forward-slash on artisan make:seeder command resulting wrong class name in the generated seeder

### ISSUE THREAD

**Issue by esyede** [laravel/framework#30901]
- Laravel Version: 6.x
- PHP Version: PHP 7.3.2
- Database Driver & Version: -

### Description:
When running the artisan make:seeder with class name containing forward-slash, it resulting a non-valid class name in the generated seeder.

Duplicates to issue on Laravel 5 ([this issue](https://github.com/laravel/framework/issues/17407))

### Steps To Reproduce:
Run `php artisan make:seeder Foo/Bar`
It produce wrong class name like:
```php
class Foo/Bar {
```

Suspected line: https://github.com/laravel/framework/blob/70e0dc2c39ee251f7101bfc0a3c22b3b9f9e6688/src/Illuminate/Database/Console/Seeds/SeederMakeCommand.php#L92-L95

**Comment by staudenmeir** [comment]
What result are you expecting? Slashes are not valid in PHP class names.

**Comment by devcircus** [comment]
Double slash will give you what you need.

**Comment by esyede** [comment]
@staudenmeir I'm expecting the resulted seeder files to be created inside subdirectory like when i run `make:seeder Foo/Bar` it will creates `seeds/Foo/Bar.php` and the class name should be `Bar`.

@devcircus Yes. thank you sir, I saw your answer on that Laravel 5 issue, I just want to know is this an intended behavior or just a small bug, I read your last comment on that L5 issue, and it says you have it working perfectly in a test repo so i assume it's a bug

**Comment by browner12** [comment]
Part of the issue, I believe, is that the `database` directory does not use namespaces and PSR autoloading, so it doesn't behave like a lot of the other generators.

When I run this, it correctly makes the directory and file, but as you noted, the class name is incorrect.

We could strip everything before the last slash, but then you run the risk of having colliding class names.

**Comment by esyede** [comment]
@browner12 Wouldn't it be better if we just strip all the slashes?

**Comment by browner12** [comment]
so if I understand correctly, running `php artisan make:seeder Foo/Bar`, you would want it to create a file at `database/seeds/Foo/Bar.php`, and then create a class in the global namespace called `FooBar`?

I mean, I guess.  Seems weird.

What is your need for having your seeders in different directories?

**Comment by esyede** [comment]
No, i mean it will creates `seeds/FooBar.php`  so the `GeneratorCommand::alreadyExists()` can check if the class exists or not.

**Comment by browner12** [comment]
If you want a seeder at `seeds/FooBar.php`, just run `php artisan make:seeder FooBar`

**Comment by esyede** [comment]
Haha, you're right. I just confused how to avoid class collision when creating seeder inside subdirectory since (as you already mentioned) seeder classes are by default resides in the root namespace

**Comment by driesvints** [comment]
As mentioned, Laravel's seeders aren't namespaced atm and therefor the make command doesn't supports subdirectories. Feel free to send in a PR if you want to implement support for this.
