### ISSUE TITLE
Failed to change column data type

### ISSUE THREAD

**Issue by ayazdev** [laravel/framework#30908]
- Laravel Version: 5.6.*
- PHP Version: 7.2.11
- Database Driver & Version: MySQLi 5.6.39-83.1
For Database Driver & Version Kindly Check Below Image
![image](https://user-images.githubusercontent.com/47497070/71352872-e1152880-2590-11ea-998f-f45fa2140e8b.png)

### Description:
There is no error but column data type does not changing from `text` to `longtext`

### Steps To Reproduce:
1 - Created migration `2019_12_10_075609_create_log_requests_table.php`
```
public function up()
{
    Schema::create('log_requests', function (Blueprint $table) {
        ...
        $table->text('request')->nullable();
        $table->text('response')->nullable();
        ...
    });
}
```
2 - executed `php artisan migrate`
3 - executed `composer require doctrine/dbal`
4 - executed `composer dump-autoload`
5 - Created migration `2019_12_23_065820_change_response_column_data_type_in_log_requests_table.php` for changing column data types of  `log_requests` table

```
public function up()
{
    Schema::table('log_requests', function (Blueprint $table) {
        $table->longText('request')->nullable()->change();
        $table->longText('response')->nullable()->change();
    });
}
```
6 - executed `php artisan migrate`

Then I checked in mysql database through `http://localhost/phpmyadmin/`, the `request` and `response` column's data type is still `text`
![image](https://user-images.githubusercontent.com/47497070/71352813-baef8880-2590-11ea-81f0-263e60bd0c09.png)

**Comment by ayazdev** [comment]
Can someone kindly help and guide me about it? Thanks

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
