### ISSUE TITLE
[Proposal] Classmap for MorphTo

### ISSUE THREAD

**Issue by tomschlick** [laravel/framework#3090]
If there is not currently, it would be great to have a class to (int/char) map for the MorphTo database ability. 

This would save a ton of space in the db as each record would not have to store the full path of a class. It would also provide portability for moving classes around (changing namepace) without having to update the database records, just a mapping.

Ideally this map might be passed as a parameter on the morphTo method or read from a config file that may look like this

```php

<?php

return array(
    1 => '\Domain\Folder\ClassOne',
    2 => '\Domain\Folder\ClassTwo',
);

```

**Comment by phroggyy** [comment]
This can be accomplished with mutators, but will not work if

1. We wish to access the original `type` attribute (because of the accessor)
2. We wish to eager load the parent model.

See #9407 for more details

**Comment by tomschlick** [comment]
Yeah. I don't think this is exactly the same thing as #9407 but you've done the legwork to show what needs to be done to allow this to happen.

Basically the goal of this one for me is to have global class map of strings/integers to classnames. Keeps the storage low and the indexes fast.

It looks like #9407 is to fix a bug with eager loading... unless I'm missing something

Also re-opening this since I forgot to so many moons ago. @cheelahim said, its not possible without overriding some classes in it's current form.

**Comment by phroggyy** [comment]
@tomschlick well, my issue is an extension of this. In fact, as you can see, I have pretty much solved this issue by simply overwriting the MorphTo method on the Eloquent `Model`. I decided to use a class map there. However, it will fail for eager loading since our model isn't available before the `MorphTo` is instantiated.

**Comment by GrahamCampbell** [comment]
We don't process proposal issues, sorry.

**Comment by tomschlick** [comment]
What does that even mean? You don't allow discussion on potential changes anymore? 

It has always been said that we should create an issue on a core feature before coding it up so we don't waste time. This one was created for that reason. It was determined that it couldn't be done with existing features as originally thought so I re-opened it to spark the discussion again.

**Comment by taylorotwell** [comment]
You can just leave them open Graham. Doesn't hurt. I think he means we
don't typically code the proposals ourselves, we let the community make a
PR.

**Comment by GrahamCampbell** [comment]
Sure. I think we need a "community" label or something so we can filter those issues out when we're looking through.

**Comment by lukasgeiter** [comment]
@GrahamCampbell A community label or such would be great!

**Comment by GrahamCampbell** [comment]
Further discussion can continue on the open PR. :)
