### ISSUE TITLE
Invalid exception code

### ISSUE THREAD

**Issue by andrey-helldar** [laravel/framework#30904]
- Laravel Version: 6.9.0
- PHP Version: 7.4.1

### Description:
When throwing my exception, a `500` response code is returned instead of the one I selected.

### Steps To Reproduce:
0. `APP_DEBUG=true`

1. I created my exception file (`app/Exceptions/Unknown.php`):
```php
<?php

namespace App\Exceptions;

use Exception;

class UnknownHostException extends Exception
{
    public function __construct(string $host = null)
    {
        $host = $host ?: 'EMPTY';

        $message = "Unknown host ({$host})!";

        parent::__construct($message, 403);
    }
}
```

2. `app/Exceptions/Handler.php` is default.

3. Create the controller:
```php
<?php

namespace App\Http\Controllers;

use App\Exceptions\UnknownHostException;

class FooController extends Controller
{
    public function index()
    {
        throw new UnknownHostException();
    }
}
```

4. Create route in `routes/web.php`:
```php
<?php

app('router')->get('/', 'FooController@index');
```

5. Call the `php artisan serve` command.

6. Open `http://localhost/` url and see:
![2019-12-23_10-15-28](https://user-images.githubusercontent.com/10347617/71342235-38090680-256d-11ea-85da-c62e1e3d143e.png)

**NEXT**

7. Create a unit test:
```php
<?php

namespace Tests\Unit;

use Tests\TestCase;

class FooTest extends TestCase
{
    public function testBasic()
    {
       $res = $this->get('/');

       dd($res->getStatusCode());
    }
}
```

and see too:
![2019-12-23_10-17-46](https://user-images.githubusercontent.com/10347617/71342348-861e0a00-256d-11ea-8fe8-607f792305b4.png)

### Solution
See #30905 PR

Method `getCode` is mandatory with exceptions, so there is no need to conduct additional verification of its existence (https://www.php.net/manual/en/class.exception.php).

I also consider it wrong to return the 500th error on each occasion.
If I want the production code to have a different response code for different exceptions, now I can’t get it because the application will always return 500.
My #30905 PR suggests correcting this situation.

![2019-12-23_10-53-24](https://user-images.githubusercontent.com/10347617/71344002-7a811200-2572-11ea-8a42-e9336f068228.png)
![2019-12-23_10-52-44](https://user-images.githubusercontent.com/10347617/71344004-7a811200-2572-11ea-894d-2c081ce26ff6.png)

**Comment by GrahamCampbell** [comment]
Thanks, but this is not a bug. The exception code is not the same as the http status code. You need to use http exceptions and set the status code if you want to set the http status code.

**Comment by GrahamCampbell** [comment]
You should probably extend `Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException` instead.

**Comment by GrahamCampbell** [comment]
Alternatively, if you want a way for the internals of your app to not know about HTTP, you could use https://github.com/GrahamCampbell/Laravel-Exceptions. You can then specify "transformers" that determine what status codes non-http exceptions should have.

**Comment by andrey-helldar** [comment]
Hm... @GrahamCampbell, thanks! 🍻
