### ISSUE TITLE
Saving value into too-small DB field does not update the model

### ISSUE THREAD

**Issue by SamuelNorbury** [laravel/framework#30917]
- Laravel Version: 5.8.35
- PHP Version: 7.3.11
- Database Driver & Version: Mysql 8.0

### Description:
A DB table has a varchar field with a length of 32. By mistake, a string with more than 32 chararacters is assigned to the model corresponding to that table and then being saved to the DB, resulting in the value being cut off in the DB. However, the model, after calling `->save()`, still shows the too-long value in both `attributes` and `original`.

This behaviour is hard to prevent with testing, unless an actual save to the DB is allowed.

### Steps To Reproduce:
Save a model to a table, making sure one of the values is larger than supported by column in the table. Then call `dd($model);`, and see the too-large value as an attribute of the model.

**Comment by mfn** [comment]
This is a problem of your database, because it _silently truncates data_ => never a good idea.

You've to turn on strict mode for MySQL, in which case you'll get an exception and don't suffer this problem. Nothing what Laravel / Eloquent can do here otherwise.

**Comment by SamuelNorbury** [comment]
@mfn Noted, thanks for your response, and yes, I probably should turn on strict mode for MySQL.

However, shouldn't the model at least update its attributes with the real, in-database data after `->save()`? To me it's unexpected that the object in memory does not reflect the DB unless I call `->fresh()` after saving, something I assumed `->save()` would already do.

**Comment by 36864** [comment]
Saving a model to the database is often the last thing your script does before returning, such as when saving a model in the `store` method of a ResourceController right before redirecting to the `show` route which will then load the model.

If `->save()` automatically refreshed the model, you would have an extra SQL statement that would, in a lot of cases, be completely unnecessary.

**Comment by mfn** [comment]
> To me it's unexpected

Yes, but you base your whole observation and thus expectation on the one database which can throw away parts if your data. You are simply trying to fix this from the wrong end.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
