### ISSUE TITLE
Bug: Str::plural('Natural Person') returns "Natural Neople"

### ISSUE THREAD

**Issue by 4n70w4** [laravel/framework#30912]
- Laravel Version: 6.9.0
- Laravel Nova 2.9.2
- PHP Version: 7.3.11

### Description:

Also affected Laravel Nova resource naming

![image](https://user-images.githubusercontent.com/38257723/71371061-f1dd9280-25c0-11ea-88fb-37b1e097cb43.png)

### Steps To Reproduce:

```php
 Str::plural('Natural Person')
```

![image](https://user-images.githubusercontent.com/38257723/71370914-7ed41c00-25c0-11ea-9143-251412044f3c.png)

**Comment by browner12** [comment]
is this function intended to work with multiple words?

**Comment by Krisell** [comment]
Laravel uses `doctrine/inflector` for the pluralization and the issue seems to have been discussed there: https://github.com/doctrine/common/issues/758

I don't think it's intended to handle more than single words though.

**Comment by 4n70w4** [comment]
@browner12 @Krisell 

from docs:

> The Str::plural method converts a string to its plural form. This function currently only supports the English language:

It speaks of a string with no word count limit.

from `laravel-nova / Resource.php`

```php
    /**
     * Get the displayable label of the resource.
     *
     * @return string
     */
    public static function label()
    {
        return Str::plural(Str::title(Str::snake(class_basename(get_called_class()), ' ')));
    }
```

`class_basename()` deliberately divided into separate words with a space via `Str::snake(class_basename(get_called_class()), ' ')`. Then pluralized.

Do you think this is a logical mistake in Laravel Nova or a Laravel Framework problem?

@davidhemphill FYI.

**Comment by browner12** [comment]
Have made a PR to clarify the docs.

https://github.com/laravel/docs/pull/5679

How does one even pluralize multiple words?

Let's take it to the absurd.

`The quick brown fox jumps over the lazy dog.`

Should that convert to

`The quick brown foxes jump over the lazy dogs.`

That's a lot of natural language processing right there.  First, it needs to pull out the nouns, and then it needs to update the verb accordingly.  I think a little more than this simple function is meant to do.

**Comment by devcircus** [comment]
I suggest, if anything, we update the docs to clarify. Additionally, as it is a doctrine package that handles this, it would be best to continue the conversation there.

**Comment by GrahamCampbell** [comment]
Thanks for the docs PR.
