### ISSUE TITLE
new CSRF token is not generated after logging out.

### ISSUE THREAD

**Issue by jlem** [laravel/framework#30914]
- Laravel Version: 6.6.2
- PHP Version: 7.4.0
- Database Driver & Version: MySQL 8.0

### Description:

When logging out, the current session is invalidated/destroyed, but a new CSRF token is not generated automatically. When this happens, a `null` value is set for the `XSRF-TOKEN` cookie.

This becomes a problem for single-page apps consuming Laravel as a JSON API since they rely on that cookie in the response from the logout request, and cannot rely on the token being refreshed due to a page reload (e.g. visiting `/login` or being redirected to `/`). 

As such, the client side SPA will send the blank CSRF token back to the server on the next POST request, and CSRF verification will fail.

Here is the offending code:

* class: `Illuminate\Foundation\Http\Middleware\VerifyCsrfToken`
* method: `addCookieToResponse($request, $response)`
* line: 187

```
        $response->headers->setCookie(
            new Cookie(
                'XSRF-TOKEN', $request->session()->token(), $this->availableAt(60 * $config['lifetime']),
                $config['path'], $config['domain'], $config['secure'], false, false, $config['same_site'] ?? null
            )
        );
```

As you can see `$request->session()->token()` is used to supply the cookie with the token value.

However, the act of logging out evidently wipes out the session in such a way that `token()` comes back `null`, and thus even though the XSRF-TOKEN cookie is present, the value of the CSRF token contained within the cookie is an empty string as a result.

I would expect that after logging out, a fresh token is generated for the current session, such that the response can set a valid token value in the cookie.

### Steps To Reproduce:

1. Create a new Laravel application
2. Generate the various auth views and what not
3. Create a user, log in with that user
4. Set a breakpoint at the start of the codeblock listed above
5. Log out
6. Inspect the value of $request->session()->token() after the breakpoint is hit.
7. Observe that the value is `null`. 

### Expected Behavior:

I would expect that logging out still generates a fresh token so that the XSRF-TOKEN cookie contains a valid token value instead of `null`.

### Proposed Solution:

Add a call to `$request->session()->regenerateToken();` to  `AuthenticatesUsers->logout(Request $request)`

```
    public function logout(Request $request)
    {
        $this->guard()->logout();

        $request->session()->invalidate();

        $request->session()->regenerateToken(); // add this line here

        return $this->loggedOut($request) ?: redirect('/');
    }
```

### Workaround

If you are running into the issue, the workaround is fairly straight-forward:

1. In the controller where `AuthenticatesUsers` trait is included, override the protected `loggedOut(Request $request)` method from the trait (you will likely be doing this anyway if you are using this through a SPA)

2. Add this line before returning your response: `$request->session()->regenerateToken();`

Full example of my LogoutController:

```
<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\AuthenticatesUsers;
use Illuminate\Http\Request;

class LogoutController extends Controller
{
    use AuthenticatesUsers;

    public function __invoke(Request $request)
    {
        return $this->logout($request);
    }

    protected function loggedOut(Request $request)
    {
        $request->session()->regenerateToken(); // make sure this line is present in this override
        
        return response()->json(true);
    }
}
```

**Comment by jlem** [comment]
I'm happy to open a pull request to address the proposed solution, but would love to hear feedback from others about the proposal.

**Comment by driesvints** [comment]
Hmm. I think this might be best solved within the `VerifyCsrfToken` itself but not sure.

**Comment by driesvints** [comment]
@jlem we've implemented a fix for this: https://github.com/laravel/framework/commit/b2af428e60188ea55fb06f3a1e0b0b0c690bbe86

Will be in the next release.
