### ISSUE TITLE
Unable to force create on association

### ISSUE THREAD

**Issue by robinvdvleuten** [laravel/framework#30911]
- Laravel Version: 6.9.0
- PHP Version: 7.4.0
- Database Driver & Version: Postgres 11

### Description:

When I forcefully create an associated model, the identifier is set to `null`. I expected to be able to force create associations this way.

### Steps To Reproduce:

```php
$post->comments()->forceCreate(['body' => 'Lipsum...']);
```

Will throw the error;

```
ERROR: SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "post_id" violates not-null constraint
```

**Comment by driesvints** [comment]
We'll need a lot more code to reproduce this. Please post the `Post` & `Comment` model and the migrations.

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.
