### ISSUE TITLE
Mockery v1.3.0 removed NoMatchingExpectationException::getMethodName()

### ISSUE THREAD

**Issue by crynobone** [laravel/framework#30929]
- Laravel Version: 6.0+
- PHP Version: 7.2+
- Database Driver & Version: n/a
- Mockery: 1.3.0+

### Description:

https://github.com/laravel/framework/blob/6.x/src/Illuminate/Foundation/Testing/PendingCommand.php#L137-L143

`getMethodName()` is being used under `PendingCommand` class and has been removed in mockery v1.3.0.

**Comment by X-Coder264** [comment]
Shouldn't this be reported to the Mockery repository instead as a breaking change in a minor release?

**Comment by GrahamCampbell** [comment]
I agree with @X-Coder264. They say they follow semantic versioning: https://github.com/mockery/mockery#versioning.

**Comment by GrahamCampbell** [comment]
// cc @robertbasic, @davedevelopment

**Comment by GrahamCampbell** [comment]
I'd certainly expect that `NoMatchingExpectationException` is part of the public API?

**Comment by robertbasic** [comment]
Yes, this is our mistake. Sorry, we'll get around fixing it.

**Comment by robertbasic** [comment]
I just tagged Mockery 1.3.1 reverting the changes made to the `NoMatchingExpectationException`. Sorry for the troubles this might have caused to some.

**Comment by GrahamCampbell** [comment]
Thanks. 👍
