### ISSUE TITLE
Elixir vs mix oddity

### ISSUE THREAD

**Issue by GrahamCampbell** [laravel/framework#30928]
Why does the elixir helper return a string, but the mix helper returns HtmlString?

**Comment by GrahamCampbell** [comment]
Looks like it has been like that since the beginning: https://github.com/laravel/framework/commit/6ea4997fcf7cf0ae4c18bce9418817ff00e4727f.

**Comment by driesvints** [comment]
Let's keep these discussions on slack etc and not on the issue tracker
