### ISSUE TITLE
Removing SHOW, on Route::resource, conflict on delete

### ISSUE THREAD

**Issue by lloricode** [laravel/framework#30939]
- Laravel Version: 6.9.0
- PHP Version: 7.2.25
- Database Driver & Version: MySql, 5.7.28

### Description:

Im using `Route::resource` to make less code written then ignore some functions.

in my case, removing `show` then trying to visiting it, it will throw exception, instad of `404`

### Steps To Reproduce:

route:
```php
Route::resource('menus', 'MenuController', ['except' => ['show', 'create', 'store']]);
```
then try to visit `http://localhost/menus/randomxx`

will return 
`The GET method is not supported for this route. Supported methods: PUT, PATCH, DELETE.`

thanks,

**Comment by xuanquynh** [comment]
You have to use HTTP `DELETE` method to delete resource. Please read about [REST](https://restfulapi.net/)!

**Comment by lloricode** [comment]
@xuanquynh sorry you dont get it,

my point is,

we dont need `show`, so we `except` it

then when we try to visit it, the resource, it must be `404` status code return

but it gives an error,,


visiting GET show, it will also trigger even it is for DELETE

**Comment by xuanquynh** [comment]
The **resource** method with RESTFul is a standard. If you don't need it or expect something else, you have to go on your own way.

**Comment by lloricode** [comment]
hmm, so it is normal to expect exception when trying to visit `show` that was excluded?

**Comment by lloricode** [comment]
i just want to check if it is a bugs? or is a project level handling

**Comment by lloricode** [comment]
my fix here is by adding `abort` on show method

```php
// MenuController

    public function show(string $routeKeyName)
    {
        abort(404);
    }

```

**Comment by crynobone** [comment]
> so it is normal to expect exception when trying to visit show that was excluded?

As described in the exception, the route exists for PUT, PATCH and DELETE, just not GET. So the exception is correct.

**Comment by devcircus** [comment]
This has been discussed several times here. Search the issues to see. Like @crynobone mentioned above, 404 doesn’t make sense because the route does exist, but not for GET, therefore the exception is expected.

**Comment by lloricode** [comment]
@crynobone, @devcircus 

thanks for the info, now i satisfy that you are already know this, so putting a `404` on `show` is the on way solution

thanks for the feed back :+1:
