### ISSUE TITLE
withTimestamps not working beside of withPivot

### ISSUE THREAD

**Issue by foremtehan** [laravel/framework#30942]
- Laravel Version: 6.9.0
- PHP Version: 7.3.5
- Database Driver & Version: mysql 5.7

### Description:

`withTimestamps` not working when there is a `withPivot` in the chain.

Not Working:

```php
return $this->belongsToMany(Thread::class)
    ->withTimestamps()->withPivot('active');
```

Working:

```php
return $this->belongsToMany(Thread::class)->withTimestamps();
    
```

**Comment by MattStrauss** [comment]
Looking over the applicable items in the framework below, I'm wondering if changing the order would make any difference, i.e.:

```
return $this->belongsToMany(Thread::class)
    ->withPivot('active')->withTimestamps();
```
In `BelongsToMany.php`, below, you can see that the `withTimestamps` method calls `withPivot`, which is available as this class uses the `Concerns\InteractsWithPivotTable` trait.

```
    public function withTimestamps($createdAt = null, $updatedAt = null)
    {
        $this->withTimestamps = true;

        $this->pivotCreatedAt = $createdAt;
        $this->pivotUpdatedAt = $updatedAt;

        return $this->withPivot($this->createdAt(), $this->updatedAt());
    }
```

The `Concerns\InteractsWithPivotTable` trait itself has the `withPivot` method mentioned above, which is called directly (as it is a public method) with the `->withPivot('active')` from your relationship. 

```
    public function withPivot($columns)
    {
        $this->pivotColumns = array_merge(
            $this->pivotColumns, is_array($columns) ? $columns : func_get_args()
        );

        return $this;
    }
```
So, perhaps I am looking at it incorrectly, but **it seems that they would override one another (via the `withPivot` method) regardless of the order that they are in.

**Comment by foremtehan** [comment]
I also just used with `withPivot('active')` alone and still not working.

**Comment by MattStrauss** [comment]
> I also just used with `withPivot('active')` alone and still not working.

It sounds like the issue may not have to do with the combination of `withTimestamps` and `withPivot`

What is the name of your other model involved in this Many-to-Many relationship (besides `Thread`)? I am assuming you created the intermediary/lookup table with [proper Laravel naming convention](https://laravel.com/docs/6.x/eloquent-relationships#many-to-many) (singular model names in alphabetical order).

**Comment by foremtehan** [comment]
Only `created_at` and `updated_at` wouldnt fill by laravel the other things is ok.

**Comment by driesvints** [comment]
Please post your entire models.

**Comment by foremtehan** [comment]
```php
class Artist extends Model {

    /**
     * @return BelongsToMany
     */
    public function bands()
    {
        return $this->belongsToMany(Artist::class, 'artist_bands', 'artist_id', 'band_id')
            ->withPivot('active');
    }

    /**
     * @return BelongsToMany
     */
    public function members()
    {
        return $this->belongsToMany(Artist::class, 'artist_bands', 'band_id', 'artist_id')
            ->withPivot('active');
    }


}

```

```php
public function up()
{
    Schema::create('artist_bands', function (Blueprint $table) {
        $table->primary(['artist_id', 'band_id']);
        $table->unsignedBigInteger('artist_id');
        $table->unsignedBigInteger('band_id');
        $table->boolean('active');
        $table->timestamps();
    });
}
```

**Comment by MattStrauss** [comment]
Double check your relationships, typically the `belongsToMany` relationship would indicate a second model that is involved in the relationship, so in your first relationship, below, I would think that you would use the `Band` class as opposed to the `Artist` class:

```
class Artist extends Model {

    /**
     * @return BelongsToMany
     */
    public function bands()
    {
        return $this->belongsToMany(Band::class, 'artist_bands', 'artist_id', 'band_id')
            ->withPivot('active');
    }
```

Then your second relationship, below, which appears to be defined in the `Artist` model, should likely be defined in the `Band` model. 

** Define in Band model**
```
/**
     * @return BelongsToMany
     */
    public function members()
    {
        return $this->belongsToMany(Artist::class, 'artist_bands', 'band_id', 'artist_id')
            ->withPivot('active');
    }
```

**Comment by foremtehan** [comment]
I used Artist model for both relation because member and artist both come from the Artist model an creating a separated model in my opinion is duplication, I closed the issue because i tested it on another belongsToMany relationship and it worked! nvm thanks mate.
