### ISSUE TITLE
Auth User table doesn't work on other db connection

### ISSUE THREAD

**Issue by kletellier** [laravel/framework#30941]
- Laravel Version: 5.8.36
- PHP Version: 7.1.2
- Database Driver & Version: PDO_mysql 

### Description:
I've a project to monitoring one production database (main db connection in database.php), i've added another connection for auth : dbuser in database.php (i can't add table to the production database).

The 2 connections are on different database.
```

'mysql' => [
            'driver' => 'mysql',
            'url' => env('DATABASE_URL'),
            'host' => env('DBMYSQL_HOST', '127.0.0.1'),
            'port' => env('DBMYSQL_PORT', '3306'),
            'database' => env('DBMYSQL_DATABASE', 'forge'),
            'username' => env('DBMYSQL_USERNAME', 'forge'),
            'password' => env('DBMYSQL_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],

        'dbuser' => [
            'driver' => 'mysql',
            'url' => env('DATABASE_URL'),
            'host' => env('DBUSER_HOST', '127.0.0.1'),
            'port' => env('DBUSER_PORT', '3306'),
            'database' => env('DBUSER_DATABASE', 'forge'),
            'username' => env('DBUSER_USERNAME', 'forge'),
            'password' => env('DBUSER_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],
```

I've change the migration to create user table to point to dbuser connection, it works fine, tables are successfully created.

When i wan't to register a new user with default auth form i've one error : `"Base table or view not found: 1146 Table 'rdv-prod.users' doesn't exist (SQL: select count(*) as aggregate from `users` where `email` = myemail)"`

It seems the auth search in primary database instead of dbuser database

### Steps To Reproduce:
- create dbuser in database.php for auth db
- change connection in migration for creating auth tables  (Schema::connection('dbuser')->create)
- php artisan migrate
- php artisan make:auth
- change connection in User model : protected $connection = 'dbuser';
- trying to register a new user with register route

**Comment by 36864** [comment]
You'll have to modify the validation rules in Auth\RegisterController 
https://github.com/laravel/laravel/blob/195faa16cbeabc84b0eb9c9f4227ead762c93575/app/Http/Controllers/Auth/RegisterController.php#L54

`unique:users` looks in the default connection. Try `unique:dbuser.users` or `unique:App\User` as per the docs: https://laravel.com/docs/6.x/validation#rule-unique

**Comment by kletellier** [comment]
Works fine !! Thx for your help !!!
