### ISSUE TITLE
'no such table' when generating unit test from artisan

### ISSUE THREAD

**Issue by foremtehan** [laravel/framework#30961]
- Laravel Version: 6.9.0
- PHP Version: 7.3
- Database Driver & Version: 5

In new laravel version when we generates a unit test from artisan it set up a different namespace from previous versions which was `Tests\TestCase` but now it uses `PHPUnit\Framework\TestCase`

And when i try to use `factory()->create()` under this namespace ill got the 'no such table' error, Note that when i change it to previous one it works.

**Comment by RFreij** [comment]
See #30879

**Comment by foremtehan** [comment]
Just wondering if i unable to use factories inside if unit tests, How to test my models?

**Comment by devcircus** [comment]
extend the skeleton app's base test class
