### ISSUE TITLE
Call to undefined function GuzzleHttp\json_decode()

### ISSUE THREAD

**Issue by SharafMHD** [laravel/framework#30969]
- Laravel Version: 6.0
- PHP Version: 7.3.13
- Database Driver & Version:

### Description:
Call to undefined function GuzzleHttp\json_decode()

### Steps To Reproduce:
  $jsonString = file_get_contents(base_path('public/rates.json'));
        // dd($jsonString , true);
        $data = json_decode($jsonString, true);

**Comment by Jon4t4n** [comment]
If you want to use the `GuzzleHttp\json_decode` function you need to install `guzzlehttp/guzzle` or remove the use statement and use the built-in PHP function.

**Comment by GrahamCampbell** [comment]
@SharafMHD Can you put your `composer.lock` file in a [gist](https://gist.github.com/), and link it here please?

**Comment by GrahamCampbell** [comment]
> Steps To Reproduce:

Can you show the entire file. In particular, what `namespace` is at the top, and what function imports, if any?

**Comment by SharafMHD** [comment]
> If you want to use the `GuzzleHttp\json_decode` function you need to install `guzzlehttp/guzzle` or remove the use statement and use the built-in PHP function.
 This works  .  thanks a lot @Jon4t4n  
and @GrahamCampbell
