### ISSUE TITLE
route:cache succeeds but afterwards an exception is thrown

### ISSUE THREAD

**Issue by byGits** [laravel/framework#30979]
- Laravel Version: 6.9.0 (output of `php artisan -V`)
- PHP Version: 7.4.1 (for CLI, where I run artisan commands) and 7.3.7 (on the server)
- Database Driver & Version: MySQL 5.7.26

### Description:
Running `php artisan route:cache` succeeds:

> Route cache cleared!
> Routes cached successfully!

But afterwards the following error is thrown when accessing the any page:

> ErrorException
> Erroneous data format for unserializing 'Symfony\Component\Routing\CompiledRoute' 

After running `php artisan route:clear` the application is accessible again.

### Steps To Reproduce:

Simply running `php artisan route:cache` and then accessing any route...

**Comment by driesvints** [comment]
I can cache routes just fine. Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by byGits** [comment]
@driesvints Thank you for your time,

I found that there already is a topic on [Laracasts](https://laracasts.com/discuss/channels/laravel/laravel-artisan-routecache-causes-erroneous-data-exception) and a lot of people have this exact same issue:

I will try to investigate further, to hopefully find what's causing this.

**Comment by ahmic** [comment]
That error also affects Horizon. If routes are cached supervisor can not start

```
sudo supervisorctl restart all
laravel_horizon:laravel_horizon_00: stopped
laravel_horizon:laravel_horizon_00: ERROR (spawn error)
```

horizon.log
```
In routes.php line 15:

  Erroneous data format for unserializing 'Symfony\Component\Routing\Compiled
  Route'
```

**Comment by X-Coder264** [comment]
I've recently had a similar problem. I was updating my app from PHP 7.3 to 7.4. The issue was that I ran `php artisan route:cache` on 7.4 CLI while I still haven't switched FPM from 7.3 to 7.4. After switching FPM to 7.4 everything worked. Make sure that both your PHP CLI and FPM versions match as it looks like that PHP 7.3 cannot unserialize strings which were serialized by PHP 7.4.

**Comment by byGits** [comment]
> I've recently had a similar problem. I was updating my app from PHP 7.3 to 7.4. The issue was that I ran `php artisan route:cache` on 7.4 CLI while I still haven't switched FPM from 7.3 to 7.4. After switching FPM to 7.4 everything worked. Make sure that both your PHP CLI and FPM versions match as it looks like that PHP 7.3 cannot unserialize strings which were serialized by PHP 7.4.

That was indeed the reason. Thank you.

**Comment by romicaiarca** [comment]
> I've recently had a similar problem. I was updating my app from PHP 7.3 to 7.4. The issue was that I ran `php artisan route:cache` on 7.4 CLI while I still haven't switched FPM from 7.3 to 7.4. After switching FPM to 7.4 everything worked. Make sure that both your PHP CLI and FPM versions match as it looks like that PHP 7.3 cannot unserialize strings which were serialized by PHP 7.4.

This solution also worked for me . Thank you!

**Comment by mydnic** [comment]
> I've recently had a similar problem. I was updating my app from PHP 7.3 to 7.4. The issue was that I ran `php artisan route:cache` on 7.4 CLI while I still haven't switched FPM from 7.3 to 7.4. After switching FPM to 7.4 everything worked. Make sure that both your PHP CLI and FPM versions match as it looks like that PHP 7.3 cannot unserialize strings which were serialized by PHP 7.4.

If anyone STILL have this issue even though PHP versions match, try restarting the server.
I'm using Laravel Forge, I upgraded to PHP7.4 and everything was correct in the config (nginx, php-fpm, php-cli). But the error remained. Then I restarted the server through forge UI and everything works fine now.
