### ISSUE TITLE
Unable connect DB Mysql Laravel Version: 5.8.x and 6.x

### ISSUE THREAD

**Issue by mtv9098** [laravel/framework#30983]
- Laravel Version: 5.8.x and 6.x
- PHP Version: 7.2.x
- Database Driver & Version: MySQL

### Description:
`[previous exception] [object] (PDOException(code: 1044): SQLSTATE[42000] [1044] Access denied for user 'pha29410_userConn'@'localhost' to database 'pha29409_userData' at /home/29410/public_html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70)
[stacktrace]`
Unable to connect the db mysql to the user and the password is correct with Laravel Version: 5.8.x and 6.x. But it is possible to connect the DB to version 5.7 or earlier. The server connects Plesk and Cpanel

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
