### ISSUE TITLE
$errors global variable is empty when an error has length greater than 75 characters

### ISSUE THREAD

**Issue by hvlucas** [laravel/framework#31007]
- Laravel Version: 6.9.0
- PHP Version: 7.2.25
- Database Driver & Version: mysql  Ver 8.0.18 for osx10.14 on x86_64 (Homebrew)

### Description:
When passing validator or an array of field errors to `withErrors()` the `$errors` blade global variable is empty and no errors can be found in the Session. 

The route being used is the `register` in `Auth::routes()`. `web` middleware is only being passed once
``` POST | register| App\Http\Controllers\Auth\RegisterController@register| web,guest ```

### Steps To Reproduce:
```
$validator = Validate::make($request->all(), $rules);
if($validator->fails(){
$errors = ['field' => 'A sentence that contains more than 75 characters. We keep writing until we reach that goal'];
return redirect()->back()->withErrors($errors);
// or when passing $validator directly
return redirect()->back()->withErrors($validator);
}
```
On redirect in blade file
```
{{ dd($errors->all(), Session::get('errors') }}
```
```
[]
null
```

**Comment by driesvints** [comment]
This works fine for me. Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by bacodekiller** [comment]
@driesvints I have the same problem like @hvlucas . How did you fix it? @hvlucas

**Comment by hvlucas** [comment]
@bacodekiller I had to use a different `CACHE_DRIVER` in the environment file. Changing it to file fixed this for me

**Comment by hvlucas** [comment]
@bacodekiller I typed the wrong driver, I fixed it in the comment above
