### ISSUE TITLE
I cannot use the with() method, after set the uuid as DB table id column type

### ISSUE THREAD

**Issue by QuasarZero** [laravel/framework#31001]
- Laravel Version: 5.8.36
- PHP Version: 7.3.12
- Database Driver & Version: 8.0.17
### Description:
My team is use **uuid** as our db table records' id, **not bigIncrease**, so we cannot use the **with()** method to query chained call.

### Steps To Reproduce:
4 Example.
Table A is related to table B, b_id on table A is related with id on table B.
I write a belongsTo(B) on A model for this relation.
Query their data records on somewhere, cannot get any related data from B by **with()** method.
Because the framework uses the integer default to execute the correlated subqueries (where in), **you force convert my uuid to be an integer**.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by QuasarZero** [comment]
> Hey there,
> 
> Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.
> 
> Thanks!

Do any of the currently released versions support this feature?

**Comment by berbare** [comment]
@QuasarZero I spent a good time trying to understand what was causing the `load()` and `with()` methods not to work (getting the related model via arrow worked) and this issue helped me figure out I wasn't crazy. What I did to fix was include the following line of code at my models:

`public $incrementing = false;`

This tells Laravel 5.8 not to treat your primary key as an integer, and the queries should work correctly.
