### ISSUE TITLE
Symfony Http Message Bridge Dropped Support for Diactoros

### ISSUE THREAD

**Issue by ivannovak** [laravel/framework#31017]
- Laravel Version: 5.1 through current 6.*

### Description:
Top level indication: 
```
Symfony\Component\Debug\Exception\FatalThrowableError
Class 'Symfony\Bridge\PsrHttpMessage\Factory\DiactorosFactory' not found
```

Discovered that Symfony recently removed support for Diactoros:

- https://github.com/symfony/psr-http-message-bridge
- https://github.com/symfony/psr-http-message-bridge/commits/master

Per the current [Symfony PSR 7 Bridge docs](https://symfony.com/doc/current/components/psr7.html) Diactoros is no longer referenced. Instead they recommend `nyholm/psr7`. 

### Steps To Reproduce:
Follow the instructions to take advantage of [PSR7 Requests](https://laravel.com/docs/6.x/requests#psr7-requests). 

Observe the deprecation (and likely abandonment warning as Zend Diactoros is now an archived repo and responsibility has moved to https://github.com/laminas/laminas-diactoros for future development of Diactoros).

**Comment by ivannovak** [comment]
PR to Framework: https://github.com/laravel/framework/pull/31018
PR to Docs: https://github.com/laravel/docs/pull/5703

**Comment by GrahamCampbell** [comment]
Just to be clear, this drop only happened in v2 of the symfony component, and not v1? Laravel 6 only says to use `^1.2`, so users should be fine.

In Laravel 7 we can change this to `^2.0` and delete the remaining zend code after your 6.x PR is merged.

**Comment by ivannovak** [comment]
Correct. Though the `composer require...` instructions should definitely be updated in the docs to include `^1.2` on the psr http message bridge.
