### ISSUE TITLE
Route model binding on resource route parameters

### ISSUE THREAD

**Issue by quantumwebco** [laravel/framework#31015]
- Laravel Version: 6.x
- PHP Version: 7.3
- Database Driver & Version: mysql 8.0

### Description:
Naming Resource Route Parameters 
https://laravel.com/docs/master/controllers#restful-naming-resource-route-parameters

When redirecting to a resource route with a parameter it adds it as a query string rather than part of the path which means route model binding doesn't work

In the docs it says it passes it as part of the path but this is not the case

### Steps To Reproduce:
In routes file
```
Route::resource('subscriptions', 'SubscriptionController')->parameters([
    'create' => 'subscriber'
]);
```
Expected route 
```
/subscriptions/create/{subscriber}
```
Got
```
/subscriptions/create?subscriber={subscriber}
```
In subscriber controller controller
```
return redirect()->route('subscriptions.create', ['subscriber' => $subscriber]);
```
In subscriptions controller
```
public function create(Subscriber $subscriber)
{
    dd($subscriber);
    ...
}
```
Expected result to dump the $subscriber model object but just get an empty subscriber model 

Obviously the solution is to just 
```
Subscriber::find($request->subscriber);
```

But shouldn't route model binding work for the resource route params?

**Comment by Stokoe0990** [comment]
Your "expected route" is incorrect by your examples.

```php
Route::resource('subscriptions', 'SubscriptionController')->parameters([
    'create' => 'subscriber'
]);

route('subscriptions.create', ['subscriber' => 55]);

//output:
http://app.test/create/{subscriber}
```

https://laravel.com/docs/5.8/routing#implicit-binding says:

> "Since the $user variable is type-hinted as the App\User Eloquent model and the variable name matches the {user} URI segment, Laravel will automatically inject the model instance that has an ID matching the corresponding value from the request URI."

#### Laravel will automatically inject the model instance that has an ID matching the corresponding value from the request URI.

I'm not sure if this means you must pass the ID to the route helper like so:

```php
return redirect()->route('subscriptions.create', ['subscriber' => $subscriber->id]);
```

Maybe someone else can clear that last point up for you.

**Comment by quantumwebco** [comment]
I think you've misread or misunderstood.

**Comment by Stokoe0990** [comment]
The exact paragraph you linked to in the documentation _tells you_ what you've done wrong.

> The array passed into the parameters method should be an associative array of resource names and parameter names

This does not say "resource verbs" (Such as create/edit/destroy), but resource names.

**Comment by Stokoe0990** [comment]
Oh also - "create" is a GET route with no parameters, unless it's a nested resource.

Therefor there is no route parameter to fill in. The framework is falling back to a query string parameter because the route parameter doesn't exist.

**Comment by quantumwebco** [comment]
OK understood now. Thanks.

**Comment by quantumwebco** [comment]
NB: Another solution is to do 
```
Route::resource('subscriptions', 'SubscriptionController')->except([
    'create'
]);
```
And to set up your own create method 
```
Route::get('subscriptions/create/{subscriber}', 'SubscriptionController@create')->name('subscriptions.create');
```
