### ISSUE TITLE
Undefined function: 7 ERROR: operator does not exist: text ->> unknown

### ISSUE THREAD

**Issue by mantey-github** [laravel/framework#31029]
- Laravel Version: 6.6.0
- PHP Version: 7.3.13
- Database Driver & Version: PostgreSQL 9.6.4 (Heroku)

### Description:
Running my application  Laravel 6 on heroku with Postgresql.
I get the above error when querying a JSON column, with the -> operator:

The code works well locally (Laravel Framework 6.6.0, PHP Version: 7.2.25, MySQL) but does not work when deployed to heroku..

```
 $user->unreadNotifications()->where('data->type', $notificationType)->update(['read_at' => now()]);

```

Full error
```
SQLSTATE[42883]: Undefined function: 7 ERROR: operator does not exist: text ->> unknown LINE 1: ...fiable_type" = $4 and "read_at" is null and "data"->>'type' ... ^ HINT: No operator matches the given name and argument types. You might need to add explicit type casts. (SQL: update "notifications" set "read_at" = 2020-01-04 12:32:13, "updated_at" = 2020-01-04 12:32:13 where "notifications"."notifiable_id" = 1 and "notifications"."notifiable_id" is not null and "notifications"."notifiable_type" = App\User and "read_at" is null and "data"->>'type' = message)
```

### Steps To Reproduce:
<img width="975" alt="Screen Shot 2020-01-04 at 7 32 34 PM" src="https://user-images.githubusercontent.com/39991756/71770790-16266100-2f29-11ea-9d0c-f4b56c3d377d.png">

Screenshot of the error on heroku
<img width="1173" alt="Screen Shot 2020-01-04 at 7 33 51 PM" src="https://user-images.githubusercontent.com/39991756/71770798-3bb36a80-2f29-11ea-8253-1043f9cd6c9b.png">

**Comment by rs-sliske** [comment]
what type is the 'data' column in your database?

**Comment by mantey-github** [comment]
> what type is the 'data' column in your database?

The data type is `text`

**Comment by staudenmeir** [comment]
It needs to be a `json` or `jsonb` column.

**Comment by mantey-github** [comment]
@rs-sliske and @staudenmeir changing the column type to `json` works now. 
I got the column set as `text` when used the `notifications:table` command from https://laravel.com/docs/5.8/notifications#database-notifications

**Comment by staudenmeir** [comment]
We could add a note about that to the documentation.

**Comment by driesvints** [comment]
Feel free to send a PR to the docs. Thanks.

**Comment by Nurbek0525** [comment]
I have same error like this my column datatype is json when I use  -> operator it gives me error
