### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Dotenv\Environment\Adapter\EnvConstAdapter' not found in C:\Users\trang\blog\web3-kien-trang\vendor\laravel\framework\src\Illuminate\Support\Env.php:67

### ISSUE THREAD

**Issue by trangtuty** [laravel/framework#31023]
Hello. I got some problem like this. Please help me.
Fatal error: Uncaught Error: Class 'Dotenv\Environment\Adapter\EnvConstAdapter' not found in C:\Users\trang\blog\web3-kien-trang\vendor\laravel\framework\src\Illuminate\Support\Env.php:67
Stack trace:
#0 C:\Users\trang\blog\web3-kien-trang\vendor\laravel\framework\src\Illuminate\Support\Env.php(85): Illuminate\Support\Env::getFactory()
#1 C:\Users\trang\blog\web3-kien-trang\vendor\laravel\framework\src\Illuminate\Support\Env.php(100): Illuminate\Support\Env::getVariables()
#2 C:\Users\trang\blog\web3-kien-trang\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(980): Illuminate\Support\Env::get('APP_PACKAGES_CA...')
#3 C:\Users\trang\blog\web3-kien-trang\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(908): Illuminate\Foundation\Application->normalizeCachePath('APP_PACKAGES_CA...', 'cache/packages....')
#4 C:\Users\trang\blog\web3-kien-trang\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(183): Illuminate\Foundation\Application->getCachedPackagesPath()
#5 C:\Users\tran in C:\Users\trang\blog\web3-kien-trang\vendor\laravel\framework\src\Illuminate\Support\Env.php on line 67

Please help me. I am very desperate. Thank you.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by rannmann** [comment]
Did you ever figure it out?  This is the first result when you google search the error.

**Comment by rannmann** [comment]
I resolved my issue by destroying and re-creating the docker containers and running composer install / dump-autoload.  Dunno if that'll help anyone else.
