### ISSUE TITLE
Migration not found on migrate:reset with --path 

### ISSUE THREAD

**Issue by zotopteam** [laravel/framework#31038]
- Laravel Version: 6.9.0
- PHP Version: 7.2.12
- Database Driver & Version: mysql 5.7

### Description:

when running migrate:reset with --path option，show ：Migration not found 2020_01_05_165208_create_modules，but This migration belongs to another path, not this path, and is not expected to be reset

### Steps To Reproduce:

**Run:**

`php artisan migrate:reset --path=modules/Content/Database/Migrations
`

**Show：**

`Migration not found: 2020_01_05_165208_create_modules
` 

The migration '2020_01_05_165208_create_modules' is in ‘database/migrations’

if i run migrate:reset with --path option，Shouldn't it just reset the specified path?
The result is correct, but the message displayed feels wrong

Thanks for your help！

**Comment by zotopteam** [comment]
Looking at the source code：

vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php

```
    public function reset($paths = [], $pretend = false)
    {
        // Next, we will reverse the migration list so we can run them back in the
        // correct order for resetting this database. This will allow us to get
        // the database back into its "empty" state ready for the migrations.
        $migrations = array_reverse($this->repository->getRan());

        if (count($migrations) === 0) {
            $this->note('<info>Nothing to rollback.</info>');

            return [];
        }

        return $this->resetMigrations($migrations, $paths, $pretend);
    }
```

The paths is correct, only included ‘modules/Content/Database/Migrations’，but the $migration is all migrations，I think it should only scan migrations in this path and exclude migrations in other path

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
