### ISSUE TITLE
Mocking of Schema facade is currently impossible

### ISSUE THREAD

**Issue by muglug** [laravel/framework#31030]
- Laravel Version: 6.9.0
- PHP Version: NA
- Database Driver & Version: NA

### Description:

`Schema::getFacadeAccessor` returns an object, which means a bunch of logic fails as it's impossible to mock out the schema facade.

I imagine it wouldn't be too hard to add a check in `Facade::swap` so as to allow this behaviour.

In my use-case I want to process database migrations in bulk to build up a general idea of a database schema, so as to better understand the property types of associated models.

If the Schema builder instance cannot be swapped then this is impossible (my workaround will be to parse the PHP files and statically analyse the migration files, but that's a little cumbersome).

cc @nunomaduro

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!

**Comment by muglug** [comment]
Yeah, I understand how this might seem like a bug to one person and like a feature to another. I won't be adding it to `laravel/ideas`, mainly because I'm not a Laravel user (so I lack a lot of context), and in the end I was able to work around this with static analysis.

**Comment by JoshMoreno** [comment]
@driesvints Pretty sure this is a bug. From the [docs](https://laravel.com/docs/7.x/facades)
> This method's job is to return the name of a service container binding

In addition, the docblock's return tag is a string, and every other core facade returns a string.

The Schema facade is the only one that returns an object which breaks the ability to mock it using `shouldReceive`
