### ISSUE TITLE
Invalid Carbon date from unixtimestamp in milliseconds working with eloquent models

### ISSUE THREAD

**Issue by MaksimTsoi** [laravel/framework#31049]
- Laravel Version: 6.8
- PHP Version: 7.2
- Database Driver & Version:

### Description:

Invalid Carbon date from unixtimestamp in milliseconds.

if I add value `1578393739123` to `$model` property date like `updated_at`, I will get wrong date:
`2007-04-23 01:18:43.0 UTC `
but correct date is
`2020-01-07 10:42:19.123 UTC` 

### Steps To Reproduce:
```
$user = new User();
$user->updated_at = 1578393739123;
dd($user->updated_at);
```
### Suggestion to fix:
in method `Illuminate\Database\Eloquent\Concerns\HasAttributes.php:asDateTime()`

after line `792`

add checking like
```
define(UNIX_TIMESTAMP_MILLI_SEC_DIGITS_LENGTH, 13);

if (is_numeric($value)) {
            if(strlen((string)$value) === UNIX_TIMESTAMP_MILLI_SEC_DIGITS_LENGTH) {
                return Date::createFromTimestampMs($value);
            }
            return Date::createFromTimestamp($value);
        }
```

**Comment by 36864** [comment]
I think a better solution would be to have a way to explicitly indicate that your want millisecond timestamps, especially if you want to import historical data from before 2001.

**Comment by driesvints** [comment]
I don't think it's meant to work like this. Use a DateTime or Carbon object to set the timestamps instead.

**Comment by MaksimTsoi** [comment]
Make sense, but what's reason allow to use unixtimestamp with seconds and doesnt allow with milliseconds. I mean below works correctly

```
$user = new User();
$user->updated_at = 1578393739;
dd($user->updated_at);
```

Could you explain, please?
