### ISSUE TITLE
Unit test classes extend PHPUnit TestCase class instead of Laravel TestCase class

### ISSUE THREAD

**Issue by juvpengele** [laravel/framework#31046]
- Laravel Version: ^6.2
- PHP Version: 7.2.19
- Database Driver & Version: Sqlite

### Description

I have a fresh laravel installation. When I tried to create tests using the command line, I saw that unit test classes extend the PHPUnit TestCase class. The consequence is in the unit test classes, we can not use Laravel helpers for testing instead of manually extend the right class

```
<?php

namespace Tests\Unit;

use PHPUnit\Framework\TestCase;

class UserTest extends TestCase
{
    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function testExample()
    {
        $this->assertTrue(true);
    }
}
```

### Steps To Reproduce:
- Install laravel
- Create a unit test using the command line

**Comment by driesvints** [comment]
Please see the discussion [here](https://github.com/laravel/laravel/pull/5169) and [here](https://github.com/laravel/framework/commit/e30a0c979d98f2f1f7b6c565e4002734237a280b). Use a feature test if you need the framework or replace the test case with the Laravel test case.
