### ISSUE TITLE
Usage of dump() leads to auth() helper returning AuthManager only once while phpunit is running

### ISSUE THREAD

**Issue by pr4xx** [laravel/framework#31055]
- Laravel Version: 6.10.0
- PHP Version: 7.4.1
- Database Driver & Version: -

### Description:

**Edit:** It seems like the real issue here is using the `dump()` method. When using good old `var_dump()` everything is fine. How so?

---

While running phpunit, using the `auth()` helper in order to gain access to the current user, calling it more then once will result in an undesired behaviour.
The first call to `auth()` will return the correct `AuthManager` instance. Any subsequent call in the same test method will return the `Auth` facade class. I am no longer able to call `auth()->user()`.
This will only occur if you run more then one feature(!) test.

### Steps To Reproduce:
1. Create fresh laravel project.
2. Edit the `tests/Feature/ExampleTest.php` file like so:
```php
class ExampleTest extends TestCase
{
    public function testBasicTest()
    {
        $this->assertTrue(true);
    }

    public function testBasicTest2()
    {
        dump(get_class(auth()));
        dump(get_class(auth()));
        $this->assertTrue(true);
    }
}
```

**Comment by driesvints** [comment]
hey there. `dump` isn't part of Laravel but of Symfony. If there's a problem with the helper it's best to open an issue on the Symfony issue tracker.

**Comment by ionutantohi** [comment]
@pr4xx @driesvints In a way It seems related to #30700 

@mfn posted in that issue that this behaviour is related to facade/ignition

Once ignition package is removed it outputs correct classes.
