### ISSUE TITLE
Eloquent event hooks show odd `getDirty()` behaviour

### ISSUE THREAD

**Issue by bert-w** [laravel/framework#31061]
- Laravel Version: `6.10.0`
- PHP Version: `7.3.5`
- Database Driver & Version: `mysqlnd 5.0.12-dev`

### Description:
Im not sure if this is a bug or a feature, but at least it is an oddity. When you update a model, lets assume a `User`, you can hook into the Eloquent events like `updating`/`updated`/`saving`/`saved` etc. 

Eloquent models keep track of dirty properties using the syntax `$user->getDirty()` (returns array with all properties) or `$user->isDirty('username')` (returns boolean).

Consider the following case:

```
// Register event hooks.
User::created(function($model) {
    dump($model->getDirty());
    $model->update([
        'username' => 'Foobar'
    ]);
});

User::updating(function($model) {
    // Expecting just "username" to be dirty, which is not the case (all 3 properties are dirty).
    dump($model->getDirty());
});

// Create a user.
User::create([
    'username' => 'John',
    'points' => 25,
    'email' => 'test@example.com'
]);
```

The `created` hook is called *after* the model has been created, i.e. an autoincremented `id` is available at this moment. All good up to this point.

Now, I expect the `$model->getDirty()` from the `created` hook to actually be empty, but it is not (see first `dump()`. It holds all properties as passed to the `User::create()` method. Even when calling `$model->update(...)` inside the `created` hook, will also result in a full dirty properties array inside the `updating` hook, with an updated `'username'` that is (see second `dump()`).

I can kinda understand why this is the case but it also conflicts with the idea that a persisted model should not have `dirty` properties.

Is there any reason why this is happening?

**Comment by mfn** [comment]
> Laravel Version: `5.8.36`

Not supported anymore, please update first

**Comment by bert-w** [comment]
Updated to latest version `6.10.0`, the same issue applies.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
