### ISSUE TITLE
Custom translator singleton are overriding by default translator

### ISSUE THREAD

**Issue by elvinas21** [laravel/framework#31067]
- Laravel Version: 6.10.0
- PHP Version: 7.2.14
- Database Driver & Version: mysql 5.7.24

### Description:
After I upgraded my Laravel from v6.9.0 to v6.10.0 third party translation library stopped working.
In Laravel v6.9.0  firstly are registering Laravel native 'translator' singleton and after that it registering third party libraries singletons, but in Laravel v6.10.0 firstly are registered third party libraries singleton named 'translator' and after that it will be overridden by Laravel native 'translator' singleton.

It could be caused by this changes: https://github.com/laravel/framework/pull/31009 @GrahamCampbell  please check it. Thanks.

### Steps To Reproduce:
Use one of the package which extends translations functionality and register translator singleton
I'm using this https://github.com/joedixon/laravel-translation library which takes translations from database

**Comment by driesvints** [comment]
I'm not sure how these changes break that package. We'll need some more info on this to determine what has broken.

/cc @joedixon @GrahamCampbell

**Comment by joedixon** [comment]
I'm going to try and take a look at this tonight.

**Comment by joedixon** [comment]
@elvinas21, I have a fix coming for this so I think the issue can be closed.

**Comment by crynobone** [comment]
It could be caused when 3rd party is loading the service provider as eagered while Laravel translator is deferred.

**Comment by joedixon** [comment]
Hi @elvinas21, I just [pushed a fix to master](https://github.com/joedixon/laravel-translation). Any chance you can pull down and let me know if the issue is resolved?

Thanks,
Joe

**Comment by elvinas21** [comment]
Hi @joedixon, i will check, and let you know the results.
