### ISSUE TITLE
join 子查询中  里面用where 查询goods.template_id 

### ISSUE THREAD

**Issue by luolaifa000** [laravel/framework#31064]
- Laravel Version: 6.2.0
- PHP Version: 7.2.19
- Database Driver & Version: mysql5.6

### Description:
join 子查询中  里面用where 查询goods.template_id

### Steps To Reproduce:
`$query->join(GoodsStreamTemplateState::getTableName(), function ($q) {
            $q->on(Goods::getTableName() . '.state', '=', GoodsStreamTemplateState::getTableName() . '.state')
                ->where(GoodsStreamTemplateState::getTableName() . '.template_id', '=',  'goods.template_id');
        });
        /*$query->join(GoodsStreamStateConfig::getTableName(), 'goods.state', '=', GoodsStreamStateConfig::getTableName() . '.state');
            $query->select(
            Goods::getTableName() . '.*',
                GoodsStreamStateConfig::getTableName() . '.default_sort'
        );*/
        $query->orderBy(GoodsStreamStateConfig::getTableName() . '.default_sort');
        $query->orderBy('created_at', 'desc');

`
上面查询代码打印的sql语句

"select count(*) as aggregate from `goods` inner join `goods_stream_template_state` on `goods`.`state` = `goods_stream_template_state`.`state` and `goods_stream_template_state`.`template_id` = ? where `product_id` = ? and `goods`.`project_id` in (?) and `goods`.`created_at` >= ? and `goods`.`created_at` <= ? 

上面查询代码 打印的bindings

array:53 [▼
  0 => "goods.template_id"
  1 => 8
  2 => "9"
  3 => "2019-12-01 00:00:00"
  4 => "2020-01-08 23:59:59"
]
返回的结果
array:1 [▼
  0 => {#1404 ▼
    +"aggregate": 0
  }
]

  0 => "goods.template_id" 这个子查询中 数据为0, 用完整的SQL 在数据库查询是有2条数据的。
$query->join(GoodsStreamStateConfig::getTableName(), 'goods.state', '=', GoodsStreamStateConfig::getTableName() . '.state');
            $query->select(
            Goods::getTableName() . '.*',
                GoodsStreamStateConfig::getTableName() . '.default_sort'
        );
用这个方式处理是没问题的

**Comment by dkulyk** [comment]
You should use whereColumn
```php
->whereColumn(GoodsStreamTemplateState::getTableName() . '.template_id', '=', 'goods.template_id');
```

**Comment by luolaifa000** [comment]
whereColumn， you are right。
 but since the above where can be used, the return is not expected。

**Comment by driesvints** [comment]
I'm very sorry but we can only provide support in English. Please try https://learnku.com/laravel
