### ISSUE TITLE
Migration overwrite $connection property don't work

### ISSUE THREAD

**Issue by iamine** [laravel/framework#31060]
- Laravel Version: 6.10.0
- PHP Version: 7.2.18
- Database Driver & Version: Mysql - 5.7

### Description:
I overwrite $connection property in migration, but still migrate on the default database connection

as its described on the "abstract class Migration"

```php
abstract class Migration
{
    /**
     * The name of the database connection to use.
     *
     * @var string|null
     */
    protected $connection;
```

`The migration file i used`

```php
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateProjectsTable extends Migration
{
    protected $connection = 'pgsql';
    
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('projects', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('projects');
    }
}
```

Note: the default connection i use on .env is mysql

**Comment by crynobone** [comment]
If the connection name is hardcoded you can use:

```php
Schema::connection('pgsql')->table(...)
```

**Comment by driesvints** [comment]
Please see the answer above.

**Comment by iamine** [comment]
Yes i know this is a  solution, but by the concept presented in the $connection property comment is not working...
```php
    /**
     * The name of the database connection to use.
     *
     * @var string|null
     */
    protected $connection;
```

**Comment by iraklisg** [comment]
Indeed the `$connection` property does not work in Laravel Framework 8.46.0.

The `Schema::connection('...')` works as expected

@iamine Is there a way to make `$connection` property work?

**Comment by iamine** [comment]
@iraklisg Yes, you can check the pull request i have made.

extend the Migrator class and make the needed changes.

**Comment by JohnnyWalkerDesign** [comment]
I am also having this issue. The [documentation](https://laravel.com/docs/8.x/migrations#setting-the-migration-connection) states this is the way to set your migration connection.
