### ISSUE TITLE
WithFaker references $this->app which might be missing

### ISSUE THREAD

**Issue by czesieq** [laravel/framework#31071]
- Laravel Version: 6.10.0
- PHP Version: 7.4.0
- Database Driver & Version:

### Description:

Recent change to `src/Illuminate/Foundation/Testing/WithFaker.php` added resolving of Faker instance from the container. 

```php
    protected function makeFaker($locale = null)
    {
        $locale = $locale ?? config('app.faker_locale', Factory::DEFAULT_LOCALE);

        if ($this->app->bound(Generator::class)) {
            return $this->app->make(Generator::class, [$locale]);
        }

        return Factory::create($locale);
    }
```

Up to this change, this trait was not depending on any properties of the class that it's used in. This allowed for easy injection of Faker into other elements of code.

### Steps To Reproduce:

Add the `Illuminate\Foundation\Testing\WithFaker` trait to any class that's not a `Illuminate\Foundation\Testing\TestCase` or object with $app property, it results with an error that the property is undefined.

**Comment by driesvints** [comment]
Thanks for reporting. I've sent in a fix for this here: https://github.com/laravel/framework/pull/31083

**Comment by crynobone** [comment]
@czesieq may I know how are you actually using `WithFaker`?  Is it still within a Laravel project or outside of Laravel.

**Comment by vomitHatSteve** [comment]
My team is having this issue too.
Our use case is that some of our TestCases include a non TestCase object that has the WithFaker trait and generates our test data.
#31083 resolves the issue. Thank you.
