### ISSUE TITLE
Laravel Echo does not listen to broadcast notifications on heroku

### ISSUE THREAD

**Issue by mantey-github** [laravel/framework#31077]
- Laravel Version: 6.6.0
- PHP Version: 7.3.13
- Database Driver & Version: PostgreSQL 9.6.4 (Heroku)
-  laravel-echo  ^1.6.1
-  pusher-js  ^5.0.3
- vue ^2.5.17

### Description:
So I have been able to implement successfully laravel echo with pusher for my notification and everything seems to work well on my local dev.
But deploying the app to heroku, it seems that echo cannot listen to the notification and nothing is also logged to the console with ` logToConsole: true` set

bootstarp.js
```
import Echo from 'laravel-echo'

window.Pusher = require('pusher-js');

window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    cluster: process.env.MIX_PUSHER_APP_CLUSTER,
    encrypted: true,
    logToConsole: true
});
```

MessageContent.vue
```
Echo.private(`App.User.${userId}`)
      .notification((notification) => {
       console.log('[notification]', notification)
});
```

I also tried this
```
Echo.private(`App.User.${userId}`)
        .listen(".Illuminate\\Notifications\\Events\\BroadcastNotificationCreated", (notification) => {
        console.log('[got notification on man]', notification)
});
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
