### ISSUE TITLE
Route parameters won't work in middleware kernel

### ISSUE THREAD

**Issue by darklight9811** [laravel/framework#31088]
- Laravel Version: 6.7.0
- PHP Version: 7.2.0

### Description:
Routes that contain parameters won't show it's value when called from the global middleware group.

### Steps To Reproduce:
Create a route that takes an parameter

``` php
Route::delete("/{value}",    "Lot\Controller@delete");
```

Create a middleware that reads it

``` php
class TestMiddleware {
    public function handle ($request, Closure $next) {
        dd($request->route("value");
    }
}
```

Add the middleware the the kernel middleware variable:

``` php/**
     * The application's global HTTP middleware stack.
     *
     * These middleware are run during every request to your application.
     *
     * @var array
     */
    protected $middleware = [
        \App\Http\Middleware\TrustProxies::class,
        \App\Http\Middleware\CheckForMaintenanceMode::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
        \App\Http\Middleware\TestMiddleware::class,
    ];
```

Now you should see that the values return null instead of anything you actually place when calling the route.

**Comment by X-Coder264** [comment]
That is the expected behavior. Global middleware are called on each request before the router tries to match the route. After the router matches a route the route middleware are run (and they are called **route** middleware exactly because they are ran after a specific route is matched which means that you can access route parameters in those middleware).

**Comment by darklight9811** [comment]
But shouldn't the route middleware be run before the global middleware? Even thou this could not be a "good practice", it's still a bug nonetheless.

**Comment by X-Coder264** [comment]
No, the global middleware never ran before the route middleware and I don't see any reason why should it behave that way. So this definitively can't be a bug, it's a known behavior of how the framework works since the beginning.

**Comment by driesvints** [comment]
Please see the answers above by @X-Coder264
