### ISSUE TITLE
Validator turning values to null

### ISSUE THREAD

**Issue by narwy** [laravel/framework#31082]
- Laravel Version: Latest
- PHP Version: 7.3 + 7.4 (FPM)
- Database Driver & Version: Not used

### Description:
`Validator::make()` is setting the original value of to null.

### Steps To Reproduce:

Do a API post to a controller with the multipart as `roles`

`roles` post value:
```
[
    {
        "role": "Advisor"
    }
]
```

Controller Code (see comments):
```
$roles = (array) json_decode($request->get('roles'));
// dd($roles);
// Will return the array values
$rolesValidator = Validator::make($roles, [
    '*.role'   => 'required|string',
]);
// dd($roles);
// Won't return the array values
```

You will see that before it hits the `Validator::make()` the data is fine and unchanged, but afterwards when you try to access `$roles` it's been overridden, is this the correct behaviour of this function?

### Video:
https://vimeo.com/383716545

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by narwy** [comment]
@driesvints I'm an admin on one of those and I believe this is a bug?

**Comment by driesvints** [comment]
@narwy this works just fine for me

**Comment by 36864** [comment]
Confirmed this happens on tinker on latest release:
```
>>> $roles = (array) json_decode('[{"role":"Advisor"}]');
=> [
     {#3166
       +"role": "Advisor",
     },
   ]
>>> $rolesValidator = Validator::make($roles, ['*.role' => 'required|string']);
=> Illuminate\Validation\Validator {#3171
     +customMessages: [],
     +fallbackMessages: [],
     +customAttributes: [],
     +customValues: [],
     +extensions: [],
     +replacers: [],
   }
>>> $roles
=> [
     {#3166
       +"role": null,
     },
   ]
```

Not quite sure why yet, possibly related to using objects in the array.

**Comment by UncertaintyP** [comment]
Can confirm the exact same behavior as @36864 on PHP v7.4, Laravel v6.9.0.

**Comment by narwy** [comment]
@driesvints We classing this as a bug?

**Comment by jmarcher** [comment]
I can not reproduce this on the last version:

```
>>> $roles = (array) json_decode('[{"role":"a"}]', true);
=> [
     [
       "role" => "a",
     ],
   ]
>>> Validator::make($roles, ['*.role'=>'required|string'])->validated()
=> [
     [
       "role" => "a",
     ],
   ]
>>> $roles
=> [
     [
       "role" => "a",
     ],
   ]
>>> 

```

@narwy If you are decoding a string to an assoc array, you need to pass the second parameter as `true`

**Comment by narwy** [comment]
@jmarcher Yeh that's what I'd do if I wanted it to all become an array, but surely objects should be supported in the validator?

**Comment by narwy** [comment]
@driesvints Look's like this could be a feature for objects in the future. Not a bug, confirmed.

**Comment by cby016** [comment]
How can this not be a bug?  The validator accepts objects and then sets the objects property to null after it passes validation.

**Comment by pxlrbt** [comment]
Just cross-linking this older issue: #25138
