### ISSUE TITLE
Laravel project issue (Abdulwaaheed.17@gmail.com)

### ISSUE THREAD

**Issue by jole786** [laravel/framework#31096]
- "laravel/framework": "5.8.*"
-  "php": "^7.1.3",
- Database Driver & Version:localhost phpmyadmin Server: 127.0.0.1 

### Description:
**I have need of solution any one tell me the proper solution.Its very urgent.**

[``](url
![issue](https://user-images.githubusercontent.com/57205857/72157338-7d388f80-33d9-11ea-947c-f0b53b4c22c8.PNG)
)

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by jole786** [comment]
I am working of lms project and i am working on this version.

**Comment by hamidafghan** [comment]
@jole786 You need to upgrade your project.
