### ISSUE TITLE
xmlReader Issue -> ZipArchive::getFromName(): Invalid or uninitialized Zip object

### ISSUE THREAD

**Issue by manoj11patel** [laravel/framework#31093]
- Laravel Version: 5.8
- PHP Version: 7.1
- Database Driver & Version: Mysql  & 5.7

### Description: 
When upload doc file getting below error my file extension is "doc", when tried with "DOC" its working fine

"message": "ZipArchive::getFromName(): Invalid or uninitialized Zip object",
"file": "/var/www/html/nine2five_api/vendor/phpoffice/common/src/Common/XMLReader.php",
"line_number": 56

### Steps To Reproduce:
Just upload doc file extension file from postman.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
