### ISSUE TITLE
Custom Validation Rules runs even when the field is empty

### ISSUE THREAD

**Issue by return0ir** [laravel/framework#31090]
- Laravel Version: 6.10.1
- PHP Version: 7.3.10
- Database Driver & Version:

### Description:
Custom validation rules runs even when the field is empty.

`Validator::make(['foo'=>null], ['foo'=>new \App\Rules\IfEmptyShouldNotRunRule])->validate();`

 and the rule was running while the documents have emphasized that:

> By default, when an attribute being validated is not present or contains an empty string, normal validation rules, including custom extensions, are not run.

This bug is because you always change any empty field to null and for checking empty field in Illuminate\Validation\Validator class, you check whether the field is a string type(while null is not a string)

`protected function presentOrRuleIsImplicit($rule, $attribute, $value)
    {
        if (is_string($value) && trim($value) === '') {
            return $this->isImplicit($rule);
        }

        return $this->validatePresent($attribute, $value) ||
               $this->isImplicit($rule);
    }`

**Comment by driesvints** [comment]
> when an attribute being validated is not present or contains an empty string

The attribute is present and it's not an empty string (it's `null`).

**Comment by return0ir** [comment]
By default, Larval converts all blank fields on the form to null...
Suppose an empty field is received from a web form, so it is converted to null:

`Validator::make($request->all(), ['foo'=>new \App\Rules\IfEmptyShouldNotRunRule])->validate();`

**Comment by KolyaSlisarenko** [comment]
For a custom rule to run even when an attribute is empty, the rule must be implicit. An "implicit" rule only implies that the attribute is required. Whether it actually invalidates a missing or empty attribute is up to you.

https://laravel.com/docs/11.x/validation#implicit-rulestom
