### ISSUE TITLE
Undefined property when belongs to fk name matches relation name

### ISSUE THREAD

**Issue by matt-allan** [laravel/framework#31098]
- Laravel Version: 6.10.1
- PHP Version: 7.3.13
- Database Driver & Version: Any

### Description:

When the foreign key name for a belongsTo relation is the same as the relationship name, accessing the relationship method throws an undefined property error unless the field has previously been set (i.e. when fetching from the database).

### Steps To Reproduce:

In a standard Laravel app add the following method to `App\User`:

```php
    public function state()
    {
        return $this->BelongsTo(State::class, 'state');
    }
```

Open a tinker shell and attempt to access the `state` property or the `state` method

```
>>> (new App\User)->state
PHP Notice:  Undefined property: App/User::$state in /Users/matt/code/model-issue/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/BelongsTo.php on line 99
>>> (new App\User)->state()
PHP Notice:  Undefined property: App/User::$state in /Users/matt/code/model-issue/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/BelongsTo.php on line 99
```

Here's the stack trace:

```
1) Tests\Feature\ExampleTest::testBasicTest
ErrorException: Undefined property: App\User::$state

/Users/matt/code/model-issue/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/BelongsTo.php:99
/Users/matt/code/model-issue/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php:71
/Users/matt/code/model-issue/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/BelongsTo.php:69
/Users/matt/code/model-issue/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php:210
/Users/matt/code/model-issue/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php:194
/Users/matt/code/model-issue/app/User.php:42
/Users/matt/code/model-issue/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:415
/Users/matt/code/model-issue/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:401
/Users/matt/code/model-issue/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:333
/Users/matt/code/model-issue/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1523
/Users/matt/code/model-issue/tests/Feature/ExampleTest.php:18
```

Expected output:
- Accessing the property returns `null`
- Accessing the method returns the `BelongsTo` relation

Note that the error does not occur if the property has been set, either manually or when fetching from the database.

I pushed a sample app with seeds, migrations, etc [here](https://github.com/matt-allan/framework/tree/model-issue).

**Comment by 36864** [comment]
I think this is a known limitation.

How would Eloquent know if `$user->state` should fetch the relationship or simply return the property?

**Comment by matt-allan** [comment]
Hi @36864, I didn't see any mentions of this in the docs or in existing issues so I opened an issue.

> How would Eloquent know if $user->state should fetch the relationship or simply return the property?

In this example Eloquent is accessing the property itself and it knows it wants to fetch the property, not the relationship.

**Comment by 36864** [comment]
>In this example Eloquent is accessing the property itself and it knows it wants to fetch the property, not the relationship.

But if in your code you try to access `$user->state`, are you trying to get the property or the relationship? How do you get the other? I think this was never made to work because that question was never answered unanimously.

Just use a different name for either the relation or the property.

**Comment by matt-allan** [comment]
But if in your code you try to access $user->state, are you trying to get the property or the relationship? How do you get the other?

In this case I would expect `$user->state` to return the string for the column. If I need to get the related model I can use `$user->state()->first()`.

This is how it works currently if you fetch the model from the database or instantiate it with the property explicitly set.

```
>>> $user = App\User::first()
=> App\User {#3014
     id: 1,
     name: "fWHafxtduH",
     email: "xwLoZIPyQr@gmail.com",
     email_verified_at: null,
     state: "FL",
     created_at: null,
     updated_at: null,
   }
>>> $user->state
=> "FL"
>>> $user->state()->first()
=> App\State {#3013
     id: "FL",
   }
```

If I could easily use a different property name I would but I'm working in an existing codebase with an existing database; refactoring everything is rather difficult at this point.

This issue doesn't seem too difficult to fix (i.e. calling `$this->child->getAttributeValue($this->foreignKey)` instead of `$this->child->{$this->foreignKey}` should work) and I think it's preferable that Eloquent doesn't throw an exception if it doesn't have to.

**Comment by 36864** [comment]
I am 0/2 today on this type of issue, sorry.

Traced the issue to https://github.com/laravel/framework/blob/917ee514d4bbd4162b6ddb385c643df97dcfa7d3/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L326-L331

This is called from the magic `__get()` method in the model, which is called when eloquent attempts to retrieve the property value.

This appears to be intentional, but maybe it can be changed?

**Comment by driesvints** [comment]
Hey @matt-allan, this is indeed not supported but you're right that the docs aren't clear on this. I also didn't find a note immediately. I've sent in a PR to clarify this at the top of the relationship docs. Thanks for reporting.

https://github.com/laravel/docs/pull/5718
