### ISSUE TITLE
Transaction error with MySQL 8

### ISSUE THREAD

**Issue by RERE110** [laravel/framework#31104]
- Laravel Version: 6.10.1
- PHP Version: 7.4.1
- Database Driver & Version: MySQL 8.0.18

Hello,
I just made updates on my development environment. Since the update from MySQL 5.7 to MySQL 8.0.18 I get this error during the rollback.

SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT trans2 does not exist

Have you ever experienced this error. Am I missing a configuration in MySQL? How to solve it ?

**Comment by nishijain127** [comment]
1.  You should always used **!empty()**  before using save..

2.  May be it can be help

/* ... */
$bool = false;
DB::transaction(function() use ($bool, $model, $bar) {
    $model->save();

    if($bool) {
        $model->relationship()->save($bar);
    }
}

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
