### ISSUE TITLE
Declaration of ArraySubset::evaluate incompatible with PHPUnit 7.5

### ISSUE THREAD

**Issue by okdewit** [laravel/framework#31101]
- Laravel Version: 6.10.1
- PHP Version: 7.3
- PHPUnit: 7.5.20

### Description:

@GrahamCampbell 

I'm getting a very similar issue to #28827 on Laravel 6.10.1 in combination with PHPUnit 7.5.20

_ErrorException : Declaration of Illuminate\Foundation\Testing\Constraints\ArraySubset::evaluate($other, string $description = '', bool $returnResult = false) should be compatible with PHPUnit\Framework\Constraint\Constraint::evaluate($other, $description = '', $returnResult = false)_

This type signature was not updated in PHPUnit, but it has been changed 11 days ago in Laravel Framework with the release of 6.10.x

https://github.com/sebastianbergmann/phpunit/blob/7.5.20/src/Framework/Constraint/Constraint.php#L47

https://github.com/laravel/framework/blame/02a326ce5641b741fafb017f3d02b8917ba5e563/src/Illuminate/Foundation/Testing/Constraints/ArraySubset.php#L58

**Comment by driesvints** [comment]
I think the actual culprit is probably https://github.com/laravel/framework/blame/02a326ce5641b741fafb017f3d02b8917ba5e563/src/Illuminate/Foundation/Testing/Constraints/ArraySubset.php#L193 because the line you highlighted is only used when PHPUnit is installed.

**Comment by okdewit** [comment]
@driesvints If PHPUnit 7.x is not supported on versions higher than Laravel 6.9.0, maybe it's an idea to at least retroactively add that requirement to the Laravel 5.8 > 6 upgrade guide?

**Comment by driesvints** [comment]
@okdewit PHPUnit 7 is definitely supported. We're attempting to fix this: https://github.com/laravel/framework/pull/31113

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/pull/31113 will be merged soon (probably tomorrow), and released as 6.12.0, most likely on Tuesday 21st January.

**Comment by GrahamCampbell** [comment]
> If PHPUnit 7.x is not supported on versions higher than Laravel 6.9.0, maybe it's an idea to at least retroactively add that requirement to the Laravel 5.8 > 6 upgrade guide?

PHPUnit 7 is supported on Laravel 6. We are treating it as a bug that the latest version of Laravel 6 doesn't support it. A fix will be merged shortly (see my above comment).

**Comment by GrahamCampbell** [comment]
Supported versions matrix:


|Laravel Version|PHP 7.0|PHP 7.1|PHP 7.2|PHP 7.3|PHP 7.4|PHP 8.0|PHPUnit 6|PHPUnit 7|PHPUnit 8|PHPUnit 9|
|--|--|--|--|--|--|--|--|--|--|--|
| 5.5 |YES|YES|YES|YES|NO|NO|YES|NO|NO|NO|
| 5.8 |NO|YES|YES|YES|NO|NO|YES|YES|YES|NO|
| 6.x |NO|NO|YES|YES|YES|YES|NO|YES|YES|YES|
| 7.x |NO|NO|YES|YES|YES|YES|NO|NO|YES|YES|

**Comment by GrahamCampbell** [comment]
Note that there may be some breaks with PHP 8.0 and PHPUnit 9.0, but these will be fixed, as we are saying we will support them going forward, since Laravel 6 is LTS.
