### ISSUE TITLE
Laravel 6 Can't get error message of validation of array input (input with same name) with other inputs if total input are greater than 85

### ISSUE THREAD

**Issue by mhabib555** [laravel/framework#31109]
- Laravel Version: 6.10
- PHP Version: 7.3.12
- Windows 7 , Wampserver 3.2.2.2

I am validating 1 array input and 2 text inputs. I get validation error message in blade if array size is 84 or less than that. If i increase the array size to 85. I don't get any error message.

The validation function work as it redirect back if input is invalid but it doesn't show error message if array size is greater than 85. If input is valid, then no problem

here is blade

```
@if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif          
   <div class="flex-center position-ref full-height">
        <form method="post" action="{{url('form')}}" id="infoForm" >
            @csrf
            <input type="text" class="form-control" name="name" placeholder="Section A" value="{{ old('name') }}">
            <input type="text" class="form-control" name="king" placeholder="Section A" value="{{ old('king') }}">
            @for($i=0;$i<85;$i++)
                <input type="hidden" name="test[]" value="{{$i}}">
            @endfor
            <button type="submit">Submit</button>
        </form>         
    </div>
```

Controller

```
 public function store(Request $request)
{
    $validatedData = $request->validate([
        'name' => 'bail|required',
        'king' => 'bail|required',
        'test.*' => 'required'
    ]);
    dd('test');
    return redirect('form')->with('success', 'Information has been added');    

}
```
@dd(session()->all()) Result in blade if array size is less than 84

```
array:4 [▼
  "_token" => "s3kZaeGmEI9C7lNcH8mDLnzU0KNcXkO9luPeIzQa"
  "_flash" => array:2 [▶]
  "_old_input" => array:4 [▶]
  "errors" => Illuminate\Support\ViewErrorBag {#246 ▶}
]

```

@dd(session()->all()) Result in blade if array size is great than 84

```
array:3 [▼
  "_token" => "HjFH5QBSYaqnBAx8QG6PEGiIObueWYr6AjpVPolZ"
  "_previous" => array:1 [▶]
  "_flash" => array:2 [▶]
]

```

Is this a problem related to web server or related to laravel. Kindly help me to solve it. Here is the project on github https://github.com/mhabib555/LaravelMultipleInputWithSameNameValidation

Hosted on live server
http://mhtest00001.herokuapp.com/form

**Comment by nishijain127** [comment]
You Can Also Count Array >>>>>>>>>>>>>>
count( $input = $request->all())
and used if statement as condition....

**Comment by mhabib555** [comment]
Problem solved by changing session driver from cookie to file in .env

SESSION_DRIVER=file

**Comment by celorodovalho** [comment]
@mhabib555 I'm having the same problem as you! But I already changed my session driver I nothing changes in the results.
