### ISSUE TITLE
Storing an array on session is not working on Laraval 6.10

### ISSUE THREAD

**Issue by kleberangotti** [laravel/framework#31111]
- Laravel Version: 6.10.1
- PHP Version: 7.4.1
- Database Driver & Version: mysql

### Description:
I have an app in 5.8 and started migration to 6.10. In this app I add an array (privileges) in the session to make validation quick than check in the database.
After migrate code to 6.10 Laravel simply stop working and return no errors on Laravel log and on Nginx log.
Code is working fine on 5.8.

### Steps To Reproduce:
Code is very simple and it's on Login Controller:
foreach ($funcs as $func) {
    array_push($data, $func->func_id);
}
$data      = array_unique( Arr::sort($data) );
session()->put('privileges', $data);

If session command is commented than code works fine, but $data is not stored on session.

Bottomline, steps are:
- Login Page (email and password)
- Login Controller
  - Get privileges and add ID on an array
  - Store this array ($data) on the session  <= ERROR
- redirect to main page

Really appreciate any help.. I'm stucked on this for +7 days.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by kleberangotti** [comment]
I created it here because this code worked on 5.8 and not working anymore on 6.X. I thought it was an issue.

Waiting for someone to help :)
