### ISSUE TITLE
redirect()->secure($request->fullUrl()) do not redirect through HTTPS scheme

### ISSUE THREAD

**Issue by BoGnY** [laravel/framework#31116]
- Laravel Version: 6.10.1
- PHP Version: 7.3.13
- Database Driver & Version: MariaDB 10.4.11

### Description:
This is similar as #30182.
Using `redirect()->secure($request->fullUrl())` do not redirect through HTTPS scheme, but `redirect()->secure($request->getRequestUri())` works correctly..
Is it a bug??

### Steps To Reproduce:
Run `php artisan make:middleware ForceHttps`

Modify `app\Http\Middleware\ForceHttps.php`:
```php
<?php

declare(strict_types=1);

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;

class ForceHttps
{
    /**
     * @param \Illuminate\Http\Request $request
     * @param \Closure $next
     *
     * @return mixed
     */
    public function handle(Request $request, Closure $next)
    {
        if ( ! $request->isSecure()) {
            return redirect()->secure($request->getRequestUri());
        }

        return $next($request);
    }
}
```

Edit `app\Http\Kernel.php`:
```php
protected $middleware = [
    [...]
    \App\Http\Middleware\ForceHttps::class,
];
```

Thanks!

**Comment by BoGnY** [comment]
Ok I have found the problem:
- `fullUrl()` return `http://www.my_site/my_page`
- `getRequestUri()` return `/my_page`

And `redirect()` do not redirect if full url is specified.

**Comment by rs-sliske** [comment]
this kind of thing is better to put in nginx etc config, that way it doesnt need to waste resources spinning up php processes/ laravel framework, and it will apply to all requests (including static files) rather than just ones handled by php
