### ISSUE TITLE
Illuminate\Mail\Markdown::parse(null) now results in Exception

### ISSUE THREAD

**Issue by ziming** [laravel/framework#31122]
- Laravel Version: 6.10.1
- PHP Version: 7.3.10
- Database Driver & Version: 8.0.18 for osx10.14 on x86_64

### Description:
In the past Illuminate\Mail\Markdown::parse(...) accepts both string and null. But now passing in null results in League\CommonMark\Converter::convertToHtml() must be of the type string, null given Exception

### Steps To Reproduce:
Illuminate\Mail\Markdown::parse(null)

**Comment by driesvints** [comment]
Its method signature says to pass a string so typecast it to a string before passing it.
