### ISSUE TITLE
Not send validate errors in session and not show in blade, when errors too much 

### ISSUE THREAD

**Issue by DExploN** [laravel/framework#31123]
- Laravel Version: 6.8.0 ,6.10.1
- PHP Version: 7.4
- Languages from https://github.com/caouecs/Laravel-lang

### Description:
For some languages, when validated errors  too much, errors not show in blade (not send in session) 

Language example: ru (not show >=6 erros), si (not show >=8 errors) in my code. 

### Steps To Reproduce:

New laravel 6 app + https://github.com/caouecs/Laravel-lang

conf/app.php 

```
locale' => 'ru',
// locale' => 'si',
```

View: 

```
@extends('layouts.app')
@section('content')
<div class="container">
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form class="form" method="post" action="{{route('testvalid')}}">
        @csrf
        <input class="form-control" name="field1" />
        <input class="form-control" name="field2" />
        <input class="form-control" name="field3" />
        <input class="form-control" name="field4" />
        <input class="form-control" name="field5" />
        <input class="form-control" name="field6" />
        <input class="form-control" name="field7" />
        <input class="form-control" name="field8" />
        <input class="form-control" name="field9" />
        <input class="form-control" name="field10" />
        <input class="form-control" name="field11" />
        <input type="submit" class="btn btn-primary">
    </form>
</div>
@endsection
```

Action:

```
 public function testvalidpost(Request $request){
        $request->validate([
            'field1'=>['required'],
            'field2'=>['required'],
            'field3'=>['required'],
            'field4'=>['required'],
            'field5'=>['required'],
            'field6'=>['required'],
            'field7'=>['required'],
            'field8'=>['required'],
            'field9'=>['required'],
            'field10'=>['required'],
            'field11'=>['required'],
        ]);
        echo ok;
    }
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by DExploN** [comment]
In oldest versions SESSION_DRIVER=cookie  (with my errors)  
in newest verios SESSION_DRIVER=file (its work)

https://stackoverflow.com/questions/59614407/laravel-6-9-0-validation-php-translated-messages-not-showing-if-they-do-not-star
