### ISSUE TITLE
`QueueFake->assertPushedWithChain` ambiguously describes use of $callback parameter

### ISSUE THREAD

**Issue by SherSpock** [laravel/framework#31127]
- Laravel Version: 5.8.xx

### Description:
This is a recast of #29531. 

The **PHPDoc** for `QueueFake->assertPushedWithChain` is ambiguous at best. This together with the lack of dedicated documentation on passing an array of Queueables to $expectedChain led to some lost hours for me.

### Actual PHPDoc:
```php
    /**
     * Assert if a job was pushed with chained jobs based on a truth-test callback.
     *
     * @param  string $job
     * @param  array $expectedChain
     * @param  callable|null $callback
     * @return void
     */
```

### Expected PHPDoc:
Should clearly indicated that $callback is only applied to $job, and that an array of Queueable trait-bearing instances can be passed to $expectedChain for detailed assertions. 

I am actually very sympathetic to the viewpoint expressed in #29531 that applying the callback only to $job is a bug.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by SherSpock** [comment]
@driesvints I checked 6.xx before I opened this. I wouldn't have otherwise opened it. The problem is there as well

**Comment by driesvints** [comment]
@SherSpock as said on the other PR, we don't consider this to be a bug, sorry.
