### ISSUE TITLE
Models with customized pivot attribute name can't refresh

### ISSUE THREAD

**Issue by shehi** [laravel/framework#31124]
- Laravel Version: 6 latest
- PHP Version: 7.3
- Database Driver & Version: Mariadb latest

### Description:
Considering relationships can have Pivot attribute names customized to something other than ```pivot```, how [this line](https://github.com/laravel/framework/blob/6.x/src/Illuminate/Database/Eloquent/Model.php#L1153) reconcile? While trying to load such model, I get "Couldn't find relationship X" (where X is the name of the pivot). This line specifically tries to ```except()``` a relationship named "pivot", whereas the actual attribute name isn't "pivot", it is "X" in our case. Thus, down the line, it tries to load actual relationship "X" which doesn't exist.

**Comment by driesvints** [comment]
We'll need some code to reproduce this.

**Comment by shehi** [comment]
Sorry, I don't have a code for you. It's easy, just create a pivot-based relationship, customize it's name according to your documentation, and then attempt refreshing that model while it has that named pivot in ```$model->relationships``` field of the model.

**Comment by shehi** [comment]
Pivots are in ```$model->relations``` field as seen below

![image](https://user-images.githubusercontent.com/653569/72346449-4e226680-36d6-11ea-9b13-6ceccde2d1ae.png)
