### ISSUE TITLE
Static variables are never reset when running queue:work (expected?)

### ISSUE THREAD

**Issue by Frederick888** [laravel/framework#31120]
- Laravel Version: 6.10.1
- PHP Version: 7.4.1

### Description:
When the queue job daemon is started via `queue:work`, (some?) static variables are persistent across jobs, which results in outputs that are different from what `queue:listen` generates.

As much as I understand why this happens (as `queue:work` doesn't actually 'restart' the worker), having different outputs from `queue:work` `queue:listen` still tends to be counterintuitive and a bit odd at first sight. If this is actually the expected behaviour, I reckon it should at least be documented somewhere (didn't find any relevant workings after some quick searches through https://laravel.com/docs/6.x/queues, apologies if it's actually documented already).

### Steps To Reproduce:
I noticed this issue whilst rendering views in a queue and here's my simplified test case:

1. Set `MAIL_DRIVER=log`
2. Add the pasted files
3. Run `php artisan queue:work --tries=1 --timeout=900`
4. Hit `GET /test` for several times and inspect the logs

```php
<?php
// app/Jobs/DebugMail.php

namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;

class DebugMail extends Mailable
{
    use Queueable, SerializesModels;

    public function build()
    {
        return $this->view('email.test')->with(['foo' => self::getFoo()]);
    }

    public static function getFoo()
    {
        static $localFoo;
        if ($localFoo === null) {
            $localFoo = 1;
        }
        $localFoo++;
        return $localFoo;
    }
}
```
```
{{-- resources/views/email/layout.blade.php --}}

Layout

@yield('content')
```
```
{{-- resources/views/email/test.blade.php --}}

@extends('email.layout')

@section('content')
    {{ $foo }}
@endsection
```
```php
// api/web.php
Route::get('/test', static function () {
    Mail::queue(new \App\Jobs\DebugMail());
});
```

### Expected Result
All HTMLs have got `2` in the place of `$foo`.

### Actual Result
HTMLs have got `2` `3` `4` ... since `$localFoo` is not reset to `null`.

**Comment by mfn** [comment]
It's expected.

I think the best in terms of documentation is this paragraph:
> Remember, queue workers are long-lived processes and store the booted application state in memory. As a result, they will not notice changes in your code base after they have been started. So, during your deployment process, be sure to restart your queue workers.

Specifically:
> long-lived processes

This basically explains anything.

I suggest to make a PR at https://github.com/laravel/docs to improve it!

**Comment by Frederick888** [comment]
@mfn There you go laravel/docs#5720 :) Hope it makes things clearer.
