### ISSUE TITLE
[Bug?] Unreliability of auth Authenticated Event

### ISSUE THREAD

**Issue by DarkGhostHunter** [laravel/framework#31130]
- Laravel Version: 6.x
- PHP Version: 7.4
- Database Driver & Version: MySQL 8.0

### Description:

When the User returns to the application using a remember cookie, the application doesn't fire the `Authenticated` event.

Listeners/Subscribers that depend on this event won't run the first request, which may break the application or produce unwanted behaviour. For example, applying a scope to protected records.

### Steps To Reproduce:

All good here:

1. When a user logs in, the `Login` event will be fired by the Session Guard.
2. The application will redirect him to a auth-protected route.
3. Subsequent requests will fire  the `Authenticated` event.

Now the weird:

1. When a remember cookie is set, the `Login` event will be fired.
2. **[No `Authenticated` event will be fired](https://github.com/laravel/framework/blob/master/src/Illuminate/Auth/SessionGuard.php#L142-L153)**.
3. The application won't redirect the user, but proceed into the route, if auth-protected or not.

![authevent](https://user-images.githubusercontent.com/5141911/72406289-7cd22880-373a-11ea-8ab1-20a3a77e2b1f.gif)

I posted a sample application where this is demonstrated. You can skip the npm line if you want to test it fast.

    git clone https://github.com/darkghosthunter/laravel-bug-1 /test
    cd /test
    composer update
    npm install && npm run dev
    php artisan serve

1. Go to `/dont-see` route.
2. **Ensure you check `Remember Me`**.
3. You will be asked for credentials. Use `admin@admin.com` and password `123456`.
4. **Ensure you check `Remember Me`** and log in.
5. Check you see `Authenticated Event fired!`.
6. Clear your browser session cookie called `laravel_session`. **Leave the remember cookie**.
7. Go to `/dont-see` route.
8. Check you see `Authenticated Event wasn't fired! Content is visible!`.
9. Reload the page and check you see `Authenticated Event fired!`.
10. Run in circles (optional).

#### The f*ck you fix: I'm wrong. 
All applications must hook into both the Login and Authenticated Events if necessary. Luckly, both of these are never fired at the same time, so a Subscriber may be good solution. I should rethink my choices in life.

#### The one line fix
This could be fixed by firing the `Authenticated` event after login in the user with the remember cookie.

#### The two events fix
Go to the `user()` method of the Guards and fire the `Authenticated` event when the user is retrieved and exists. `Login` and `Authenticated` will fire in the same Request.

**Comment by RTippin** [comment]
@DarkGhostHunter Although I do not use the Authenticated event, I did setup a middleware that can catch when it auths via remember and either reload the page right there, or I use the 418 teapot method to tell my JS handler to retry the exact same request

![image](https://user-images.githubusercontent.com/3917769/72425052-04c52c00-3755-11ea-8820-8dbec6de53ef.png)

**Comment by driesvints** [comment]
The current behaviour is correct. The Authenticated event is only fired when the user actively does the login, not when the system performs it (e.g. a remember cookie).

**Comment by DarkGhostHunter** [comment]
> The current behaviour is correct. The Authenticated event is only fired when the user actively does the login, not when the system performs it (e.g. a remember cookie).

I'll rethink my choices in life.
