### ISSUE TITLE
`@json` Blade directive does not support direct array as parameter

### ISSUE THREAD

**Issue by bert-w** [laravel/framework#31149]
- Laravel Version: 6.10.0
- PHP Version: 7.3.x
- Database Driver & Version: N/A

### Description:
The `@json` directive does not support passing an actual PHP array directly as its parameter, like `@json(['key' => 'foo\'bar'])`. I assumed it would, because other blade directives support the syntax as well, not limited to `@component`, `@include`, `@if`.

### Steps To Reproduce:
Consider the following code sample, that tries to echo a php array into a serialized JSON string so Vue components can use it:
```html
<lottery-component :init-data='@json(['prizes' => 'test\'s','credits' => 1])'></lottery-component>
```

Although not explicitly said in the docs, the `@json` directive does not fully support passing a PHP array directly using `[...]`. The example above results in an error because the `'` (single quote) is not escaped in this case.

The following example does work:
```html
<?php $prop = ['prizes' => 'test\'s','credits' => 1]; ?>
<lottery-component :init-data='@json($prop)'></lottery-component>
```

**Comment by driesvints** [comment]
The json directive isn't meant to be used like this. The example you posted which works is the intended usage. Please see other issues opened previously on the issue tracker and the docs here: https://laravel.com/docs/6.x/blade#displaying-data

**Comment by bert-w** [comment]
The best usage would be a oneliner, something like `:init-data="{{ json_encode(['arr']) }}"`, which defeats the purpose of the `@json` directive.

The `@json` directive is imo meant to be used like this. A lot of blade directives accept PHP syntax so why shouldnt this one?

**Comment by driesvints** [comment]
@bert-w the json directive was meant to accept a variable which contains some data that you'd pass from a controller.

**Comment by 36864** [comment]
If you're hard-coding a php array to be parsed as json, you might as well just type the corresponding json representation instead.

`{"prizes": "test's", "credits": 1}` is arguably even easier to type than `@json(['prizes' => 'test\'s', 'credits' => 1)`

**Comment by bert-w** [comment]
my bad i missed the docs part where it said:

> You should only use the @json directive to render existing variables as JSON. The Blade templating is based on regular expressions and attempts to pass a complex expression to the directive may cause unexpected failures.

Would still be cool if this could be supported though.

**Comment by bert-w** [comment]
@36864 it was given as a minimal example, the actual code contained php variables.

**Comment by driesvints** [comment]
@bert-w we tried to support it at some point but as the note in the docs hints, it was exceptionally difficult to support all sorts of complex expressions for this Blade directive.
