### ISSUE TITLE
BelongsToMany::sync not syncing the pivot values

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [laravel/framework#31142]
Hi,
I'm trying to duplicate an Eloquent model object, with also the many to may relations, and at the moment, the code i've wrote to copy the many to many relations looks like this:
```php
foreach ($obj->getRelations() as $relationName => $values){
            $elements = $obj->{$relationName}();
            if($relationName == 'relationX') $objs->withPivot('pivot_field');
            $elements = $elements->get();
            $newObj->{$relationName}()->sync($elements);
}
```
But then if i check the pivot table, MySQL has inserted the default value, and so sync doesn't have put the pivot value correctly.

Is there any way to do this kind of thing?

I'm using Laravel 6.0

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
