### ISSUE TITLE
http-tests can not request cookie info

### ISSUE THREAD

**Issue by tu6ge** [laravel/framework#31147]
- Laravel Version: 5.8.34
- PHP Version: 7.1.0
- Database Driver & Version:mysql 5.6

### Description:
my test code:
```php
$response = $this
            ->call('GET', '/seller/goods.php', ['act'=>'list'],['aaa'=>"bbb"]);

        $response->assertStatus(200);
```
in my project file:
```
$rs = request()->cookie();
        var_dump($rs);die;
```
this return info:
```
array(1) {
  ["aaa"]=>
  NULL
}

```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
