### ISSUE TITLE
SQLServer Unable to Write Migration Entries in Migrations Table

### ISSUE THREAD

**Issue by scs-ben** [laravel/framework#31153]
- Laravel Version: 6.11.0
- PHP Version: 7.3.13
- Database Driver & Version: SQL Server sqlsrv & pdo_sqlsrv: 5.6.1

### Description:
Migrations are failing to write to the migrations table:
`Illuminate\Database\QueryException  : SQLSTATE[23000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot insert the value NULL into column 'id', table 'database.dbo.migrations'; column does not allow nulls. INSERT fails. (SQL: insert into [migrations] ([migration], [batch]) values (2020_01_16_112845_create_customers_table, 10))`

### Steps To Reproduce:
Run migrations, it creates the table but not the migrations table entry

**Comment by driesvints** [comment]
This is the first time we've had a report about the migrations table not working for Sqlsrv. Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
