### ISSUE TITLE
Adding deleted_at to $dates will break restore method

### ISSUE THREAD

**Issue by WouterFlorijn** [laravel/framework#31154]
- Laravel Version: 5.8.35
- PHP Version: 7.1.9
- Database Driver & Version: MySQL 5.7

### Description:

When adding `deleted_at` to the `$dates` property of a model, calling restore on a soft-deleted instance doesn't restore the model in the database

#### Class

```php
...

class MyModel
{
    use SoftDeletes;
    $dates = ['deleted_at'];

    ...
}
```

#### Example

```php
$model = new MyModel();
$model->delete();
$model->restore();

var_dump($model->deleted_at); // Will correctly output null.

$modelFromDatabase = MyModel::find($model->id);
var_dump($modelFromDatabase->deleted_at); // Will incorrectly output a Carbon instance.

// Looking into the database directly, the deleted_at column incorrectly contains a date/time.
```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by WouterFlorijn** [comment]
@driesvints The support policy states that support for Laravel 5.8 (and 5.5) ended before 6.0 was even released. Isn't that a bit worrisome?

Also, I can't test if this problem persists in 6.x right now, but please at least update the documentation for 5.x to state that you should not add `deleted_at` to `$dates`. Right now it only says that it's already done by the trait, but not that you shouldn't do it yourself.
