### ISSUE TITLE
Downloading large files gives out of memory errors

### ISSUE THREAD

**Issue by sebsel** [laravel/framework#31159]
- Laravel Version: 6.5.2
- PHP Version: 7.4.0

### Description:
This bug manifested itself when I pointed Laravel Nova's `File` field to a file of 1,04 GB. Nova is unable to download those files. The log shows an out-of-memory error.

I investigated the problem and I think it lies with `Illuminate\Filesystem\FilesystemAdapter`, which uses a `fpasstru()` of the stream. 
https://github.com/laravel/framework/blob/f3c1f4898552ef7cfd7f422a164c3ed791ff8d29/src/Illuminate/Filesystem/FilesystemAdapter.php#L163-L167

This loads the whole file in memory. The following would work:

```php
        $response->setCallback(function () use ($path) {
            $stream = $this->readStream($path);
            while (! feof($stream)) {
                echo fread($stream, 2048);
            }
            fclose($stream);
        });

```

### Steps To Reproduce:

Get yourself a large file and point a tinker session to it:

`>>> Storage::download('large-file.csv')->send()`

With `fpassthru()`, you get a "Allowed memory size of 134217728 bytes exhausted (tried to allocate 1041674240 bytes)".
With the `while` loop it just streams data.

Happy to PR.

---

Credits: https://www.php.net/manual/en/function.fpassthru.php#29162
More examples on that page too.

**Comment by taylorotwell** [comment]
Feel free to send in a PR. Thanks.

**Comment by driesvints** [comment]
PR was merged.

**Comment by cameronjohnson-mz** [comment]
@driesvints how come this change isn't in the Laravel 9.x? And do you know the best way to get his commit in my working version?

https://github.com/laravel/framework/blob/9.x/src/Illuminate/Filesystem/FilesystemAdapter.php#L298

**Comment by sebsel** [comment]
Because it was reverted, see the MR: https://github.com/laravel/framework/pull/31163#issuecomment-590881417
