### ISSUE TITLE
Emails showing raw HTML after upgrade to 6.10

### ISSUE THREAD

**Issue by danilopinotti** [laravel/framework#31151]
- Laravel Version: 6.11
- PHP Version: 7.3
- Database Driver & Version: -

### Description:
After 6.10 upgrade, all of my emails are broked because the HTML inside `mail::panel` component is now inside a `<pre>` tag and shows the raw HTML for user.

I have published all vendor assets of emails and I tried to remove indentation (like the Taylor's commit), and no results.

I needed to rollback Laravel to version 6.9. I think if is this the right behaviour, it should be documented in release upgrade guide because it is a broke change.

There is a definitive fix for this problem?

**Comment by taylorotwell** [comment]
Share your entire Markdown email file.

**Comment by danilopinotti** [comment]
emails/layouts/main.blade.php // All extends this
```
@component('mail::message', ['unsubscribeUrl' => $unsubscribeUrl ?? null])

{{-- Body --}}
@yield('mail-body')

Atenciosamente,<br>
Equipe {{ config('app.name') }}
@endcomponent
```

vendor/mail/html/message
```
@component('mail::layout')
    {{-- Header --}}
    @slot('header')
        @component('mail::header', ['url' => config('app.url')])
            {{ config('app.name') }}
        @endcomponent
    @endslot

    {{-- Body --}}
    {{ $slot }}

    {{-- Subcopy --}}
    @isset($subcopy)
        @slot('subcopy')
            @component('mail::subcopy')
                {{ $subcopy }}
            @endcomponent
        @endslot
    @endisset

    {{-- Footer --}}
    @slot('footer')
        @component('mail::footer', ['unsubscribeUrl' => $unsubscribeUrl ?? null])
            &copy; {{ date('Y') }} {{ config('app.name') }}. All rights reserved.
        @endcomponent
    @endslot
@endcomponent
```

Sample broken email
```
@extends('emails.layouts.main')

@section('mail-body')
    Hello!
   @component('mail::panel')
        <b>{{ e(number_format($product->quantity, 2, ',', '.')) }} - {{ e($product->unit->name) }}</b><br />
    @endcomponent
@endsection
```

**Comment by taylorotwell** [comment]
De-indent everything. Try adding an extra line break after your panel @endcomponent.

**Comment by taylorotwell** [comment]
Also add a line break after your "Hello!"

**Comment by danilopinotti** [comment]
@taylorotwell Removing the indentation from **all** files involved in the email, it works, but we have dozens of different emails. It would be a full day job to ajust and test they.

Searching about this problem, I found a solution developed by @MarekGogol: https://github.com/MarekGogol/framework/commit/5d0b1d5e75542821bc6fcfe72eaefde0dc303e24

Any chance to apply on 6.x?

**Comment by taylorotwell** [comment]
That PR won't solve every case. Markdown considers indented stuff to be code blocks. So, we just have to de-indent everything. Sorry for the inconvenience.

**Comment by humaneguy** [comment]
Thanks @taylorotwell.

 It took me time to figure this out. Been struggling since yesterday.
https://github.com/laravel/framework/issues/31065#issuecomment-616101110 fixed it for me.😁

**Comment by princewillopah** [comment]
i am using laravel 8.40 and  i am still having the errors " Class 'League\CommonMark\Environment' not found (View: C:\laragon\www\gms\vendor\laravel\framework\src\Illuminate\Mail\resources\views\html\subcopy.blade.php)"
my "vendor/mail/html/message" is de-indented but i still have the error

**Comment by driesvints** [comment]
@princewillopah Update to the latest Laravel version which fixes this.

**Comment by princewillopah** [comment]
Dries Vints, thank you very much. the solution worked perfectly. i am grateful

**Comment by Ifriqiya** [comment]
@driesvints I'm getting malformed table/raw html code in emails that have a table. I'm not getting any errors. I just upgraded to L9.

**Comment by Ifriqiya** [comment]
De-indenting every line of code in the email blade resolved this.
