### ISSUE TITLE
Package moontoast/math is abandoned

### ISSUE THREAD

**Issue by andrey-helldar** [laravel/framework#31157]
- Laravel Version: 6+

Package [moontoast/math](https://github.com/laravel/framework/blob/6.x/composer.json#L86) is abandoned, you should avoid using it. Use [brick/math](https://packagist.org/packages/brick/math) instead.

**Comment by iamthefreeman** [comment]
`moontoast/math` is required because of `ramsey/uuid`. 

https://github.com/laravel/framework/issues/23291#issuecomment-573825311

Looks like the package is planning a new major version to replace the math library (hopefully in time for the 7.x release).
