### ISSUE TITLE
 Error - 419 Sorry, your session has expired.

### ISSUE THREAD

**Issue by hsntngr** [laravel/framework#31169]
- Laravel Version: 5.7.28
- PHP Version: 7.2.24
- Database Driver & Version: MariaDB - 10.3.18

- Session Driver: file
- Session Lifetime: 120

Before the close report, I would like you to know, I'm sending csrf token in my form and it works well almost all the time.

Problem causes when user close the browser and turn back after session expired, it shows 419 response by change.

Problem doesn't happen regularly.  It doesn't happen whenever a session expired. That's actually we can't sure what causing this response specifically. Also it happens only on production server. 

we used several methods to get csrf token like `@csrf`, `csrf_token` or `csrf_field`. No effect.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
