### ISSUE TITLE
redis lock expire fail

### ISSUE THREAD

**Issue by rozbo** [laravel/framework#31166]
- Laravel Version: 6.0.0
- PHP Version: 7.4.0
- Database Driver & Version:Redis 5
### Description:
now logic to acquire a redis lock need 2 steps.
setnx and set expire .
I meet a bug that setnx is sucessed  but  set expire not. this may cause by network or other weird reasons, but I think this can fix by atomic operation
I fount a pr but it have't be accept,  #29076 

### Steps To Reproduce:
1.breakpoint in https://github.com/laravel/framework/blob/dca45985ab1b2353615cef14d9d4d70ba7b1cd15/src/Illuminate/Cache/RedisLock.php#L40
2. try to acquire a redislock
3. wait the breakpoint fire, stop the redis server
4.resume the breakpoint and return
5. restore the  redis server

then you will get a never  expires lock...
Although the probability of its occurrence is very low, once it occurs, it will cause very serious consequences. In a real business scenario, I have been experiencing this problem recently. Just now I finally discovered the source of the problem.
I hope to be able to fix it.
Thank you.

**Comment by ChanJuiHuang** [comment]
Hi, Laravel. 
Could you reopen this PR https://github.com/laravel/framework/pull/29076 ?
I send this PR, previously!

**Comment by driesvints** [comment]
Should be fixed in the next release.
