### ISSUE TITLE
Can't use storage_path() in unit test

### ISSUE THREAD

**Issue by electrolinux** [laravel/framework#31167]
- Laravel Version: 6.11.0
- PHP Version: 7.2.26
- Database Driver & Version: None

### Description:

One of my class use storage_path(), so I've discovered this class can't be tested because of this bug.

### Steps To Reproduce:

`$ laravel new app
$ cd app
$ php artisan make:test --unit HelpersTest
$ sed -i 's/assertTrue(true)/assertEquals(storage_path(),"whatever")/' tests/Unit/HelpersTest.php
$ vendor/bin/phpunit
`
### Output:
`
PHPUnit 8.5.2 by Sebastian Bergmann and contributors.

.E.                                                                 3 / 3 (100%)

Time: 141 ms, Memory: 16.00 MB

There was 1 error:

1) Tests\Unit\HelpersTest::testExample
Illuminate\Contracts\Container\BindingResolutionException: Target class [path.storage] does not exist.

/demo/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:805
/demo/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:681
/demo/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:629
/demo/app/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:121
/demo/app/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:846
/demo/app/tests/Unit/HelpersTest.php:16

Caused by
ReflectionException: Class path.storage does not exist

/demo/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:803
/demo/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:681
/demo/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:629
/demo/app/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:121
/demo/app/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:846
/demo/app/tests/Unit/HelpersTest.php:16`

**Comment by electrolinux** [comment]
### Steps to reproduce:
laravel new app
cd app
php artisan make:test --unit HelpersTest
sed -i 's/assertTrue(true)/assertEquals(storage_path(),"whatever")/' tests/Unit/HelpersTest.php
vendor/bin/phpunit

**Comment by X-Coder264** [comment]
This is not a bug. `storage_path()` works only when the container is booted/filled and that only happens in feature tests when the entire framework gets booted. For unit tests you cannot have global dependencies on the container, everything should be injected via the constructor, otherwise we are talking about integration/functional/feature tests.

**Comment by mfn** [comment]
It's the most confusing thing changed in the 6.x series. You don't want to a `--unit` test, if you want to use the framework.

No one understands this change:
```php
    protected $signature = 'make:test {name : The name of the class} {--unit : Create a unit test}';
…
    protected $description = 'Create a new test class';

```
It doesn't explain what means what 🤷‍♀️

**Comment by X-Coder264** [comment]
I don't know what is so confusing about that change. The definition of an unit test was in the Laravel community (prior to this change in 6.x) different than what is the universal definition of an unit test. Now finally an unit test means the same thing everywhere again.

**Comment by mfn** [comment]
> I don't understand what is so confusing about that change

I just echoed the feedback (=confusion) of the general impression on this code change is, really (personally I've no side in this).

**Comment by driesvints** [comment]
@electrolinux please the see answer by @X-Coder264 here: https://github.com/laravel/framework/issues/31167#issuecomment-575953513

@mfn I have to agree with @X-Coder264 here. We even explain it in the docs:

> By default, your application's tests directory contains two directories: Feature and Unit. Unit tests are tests that focus on a very small, isolated portion of your code. In fact, most unit tests probably focus on a single method. Feature tests may test a larger portion of your code, including how several objects interact with each other or even a full HTTP request to a JSON endpoint.
