### ISSUE TITLE
Use Model query make memory  overflow

### ISSUE THREAD

**Issue by Linij** [laravel/framework#31172]
- Laravel Version: v6.9.0
- PHP Version: 7.4.0
- Database Driver & Version:8.0

- TELESCOPE_ENABLED=false （try close this）

### Description:
```
Artisan::command('test:test', function () {
    for ($i = 0; $i < 10000; $i++) {
            $user =  \App\Models\User::query()->first();
            unset($user);
            if ($i % 1000 == 0) {
                var_dump(memory_get_usage() / 1024 / 1024);
            }
        }
});
```
use this code in routes/console.php
### Steps To Reproduce:
run : php artisan test:test

result:
![image](https://user-images.githubusercontent.com/8857514/72707011-6abd1380-3b9a-11ea-9224-72dbe0806c94.png)

###  The following code is ok.
```
Artisan::command('test:test', function () {
    for ($i = 0; $i < 10000; $i++) {
       $user =  \App\Models\User::query();
        if ($i % 1000 == 0) {
            var_dump(memory_get_usage() / 1024 / 1024);
        }
    }
});
```

### Result
![image](https://user-images.githubusercontent.com/8857514/72706615-6ba17580-3b99-11ea-8d20-0ed3ba76a64e.png)

### Expect the result
keep memory no growth

### Description
so  , why GC not work when i query anything？

memory Sustained growth in production , 

similar code make php memory exceed expectation.

my expectation is that memory stays constant.

**Comment by browner12** [comment]
What is the expected behavior?

Less than half a MB doesn't seem excessive for 1000 queries.

**Comment by Linij** [comment]
> What is the expected behavior?
> 
> Less than half a MB doesn't seem excessive for 1000 queries.

in production ,similar code make php memory exceed expectation。

My expectation is that memory stays constant。

so，I suspect there was a memory leak during the query

**Comment by Linij** [comment]
> What is the expected behavior?
> 
> Less than half a MB doesn't seem excessive for 1000 queries.

I've added some descriptions

**Comment by mfn** [comment]
My this description my observation / guess would be: only the code which _actually_ executes the query "leaks" memory, which could be related to queries being logged somewhere (`QueryExecuted` objects lingering around somewhere). Can you check this?

I know you said you disabled telescope, but maybe somehow query logging is still enabled?

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by Linij** [comment]
> 嘿，
> 
> 您能否先尝试以下支持渠道之一？如果您确实可以将其识别为错误，请随时进行报告，我们很乐意为您提供帮助并重新打开此问题。
> 
> * [拉腊卡斯论坛](https://laracasts.com/discuss)
> * [Laravel.io论坛](https://laravel.io/forum)
> * [堆栈溢出](https://stackoverflow.com/questions/tagged/laravel)
> * [不和谐](https://discordapp.com/invite/KxwQuKb)
> * [拉拉恰特](https://larachat.co)
> * [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
> 
> 谢谢！

I find the reason , Thx for your help, I use the DB Listen cause memory leak.

![image](https://user-images.githubusercontent.com/8857514/72767464-eec0db00-3c2e-11ea-87c3-d446e07d05a1.png)
