### ISSUE TITLE
Too few arguments to function Foo::__construct(), 0 passed in src/Illuminate/Validation/Rules/DatabaseRule.php on line X and at least 4 expected.

### ISSUE THREAD

**Issue by ls-dac-chartrand** [laravel/framework#31180]
- Laravel Version: 6.11.0
- PHP Version: 7.3.1
- Database Driver & Version: http://www.laraveldoctrine.org/

### Description:

When upgrading our code to use the latest version of laravel/framework, this PR: https://github.com/laravel/framework/pull/30653

Throws: `Too few arguments to function Foo::__construct(), 0 passed in src/Illuminate/Validation/Rules/DatabaseRule.php on line X and at least 4 expected.`

When doing `\Illuminate\Validation\Rule::unique(Foo::class)` with a model that has more than zero parameters, 

### Steps To Reproduce:

Pass a sting to`resolveTableName` that resolves to an object with more than 0 parameters.

### Possible Fix:

Change:

```php
    /**
     * Resolves the name of the table from the given string.
     *
     * @param  string  $table
     * @return string
     */
    public function resolveTableName($table)
    {
        if (! Str::contains($table, '\\') || ! class_exists($table)) {
            return $table;
        }

        $model = new $table;

        return $model instanceof Model
                ? $model->getTable()
                : $table;
    }
```

To:

```php
    public function resolveTableName($table)
    {
        if (! Str::contains($table, '\\') || ! class_exists($table)) {
            return $table;
        }
        
        try {
            $model = new $table;
        } catch (\ArgumentCountError $e) {
            return $table;
        }

        return $model instanceof Model
                ? $model->getTable()
                : $table;
    }
```

Better ideas welcome.

_PS: Upgrading from 6.5.1_

**Comment by driesvints** [comment]
We don't support overriding the model's default constructor, sorry.

**Comment by ls-dac-chartrand** [comment]
That's not the issue at all.

Your new code: `if (! $model instanceof Model) {`

Where the accepted param of the function, for years now, is a string.

The string can be a class that is NOT an instance of Model.

**Comment by driesvints** [comment]
> Too few arguments to function Foo::__construct(), 0 passed in src/Illuminate/Validation/Rules/DatabaseRule.php on line X and at least 4 expected.

Can you please tell what X is here?

**Comment by mfn** [comment]
drive-by shooting, but my guess would be `Foo::class` is anything but not a model class

**Comment by ls-dac-chartrand** [comment]
> Can you please tell what X is here?

X is the line number. The original message was "on line 65"

> drive-by shooting, but my guess would be Foo::class is anything but not a model class

Yup. We're using:  http://laraveldoctrine.org/docs/1.5/orm/validation
Aka :https://github.com/laravel-doctrine/orm/tree/1.5/src/Validation

When I do: `\Illuminate\Validation\Rule::unique(Foo::class)` I am **_not_** passing a string of a class that is an instanceof `\Illuminate\Database\Eloquent\Model`

> We don't support overriding the model's default constructor, sorry.

I am not overriding the model's default constructor. I am not using the eloquent model.

The old code was like this up until [at least August 2017](https://github.com/laravel/framework/commit/636581b3cefd29d230528fe4a884b2ff9422ab5f#diff-2b497a8366519749eaba7e4de80a43c3):

```
    public function __construct($table, $column = 'NULL')
    {
        $this->table = $table;
        $this->column = $column;
    }
```

[The code I linked](https://github.com/laravel/framework/pull/30653) which breaks something that was working fine before is effectively doing:

```php
    public function __construct($table, $column = 'NULL')
    {
        $this->table = $table;
        // Is this a string that looks like a class? Any class at all?! If yes then:
       $model = new Model()
    }
```

Hardcoding a class inside a constructor where a string, any string, was the only required parameter for years, and where that string doesn't have to be a Model, is breaking something that was working fine before.

**Comment by driesvints** [comment]
We only support Eloquent models for this rule. Because you're not using an Eloquent model, this rule won't work. You'll have to ask the maintainers of laravel doctrine to provide a custom database rule.
