### ISSUE TITLE
Can't set static to new self() while testing

### ISSUE THREAD

**Issue by Vortelf** [laravel/framework#31199]
- Laravel Version: 5.8.36
- PHP Version: 7.4.1
- PHPUnit Version: 8.5.1

### Description:
What I'm trying to do is reset a static instance by setting it to `new self()`, and it works fine in tinker, but when I run PHPUnit I get this.

`ReflectionException: Class config does not exist`

### Steps To Reproduce:

```php
private static StaticClass $instance;

public static function resetStaticClass(): void
{
    static::$instance = new static();
}
```
If the instance variable is set to be nullable, `?StaticClass`, and set to `null` it works just fine with the tests.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
