### ISSUE TITLE
Notification Middleware is called twice

### ISSUE THREAD

**Issue by kieranbrown** [laravel/framework#31192]
- Laravel Version: v6.11.0
- PHP Version: 7.4.0
- Database Driver & Version: n/a

### Description:
`SendQueuedNotifications` contains a middleware property and a middleware method through the `Queueable` trait, causing middleware to be called twice.

The NotificationSender will dispatch an instance of `SendQueuedNotifications` and pass the notification middleware with the `through` method. The `through` method exists on the `Queueable` trait, which adds the middleware to the property.

https://github.com/laravel/framework/blob/8e189a8dee7ff76bf50acb7e80aa1a36afaf54d4/src/Illuminate/Notifications/NotificationSender.php#L193-L204

The snippet below fires the middleware then eventually handles the sending of the notification. If you take a look at line 80, it's merging a `middleware()` method with a `middleware` property.  This merge  is what's actually causing duplication of middleware. Because `through` was called earlier on the `SendQueuedNotifications` class the property contains the middleware, but a `middleware()` method also exists which returns that property's data. Causing the array merge to contain an array of duplicates which then essentially means they'll be called twice.

https://github.com/laravel/framework/blob/8e189a8dee7ff76bf50acb7e80aa1a36afaf54d4/src/Illuminate/Queue/CallQueuedHandler.php#L77-L86

Hopefully this makes sense, you should be able to follow the steps to replicate to see this issue.

### Steps To Reproduce:
Create a Notification class, add a `middleware()` method that returns an example middleware. In the handle method simply put `dump('called')`. Notify a user and you should see this output twice.

I'm happy to submit a PR but really can't think of a nice solution for this, any thoughts?

**Comment by driesvints** [comment]
Why would you define/need both the property and method?

**Comment by kieranbrown** [comment]
@driesvints thanks for the reply. I'm only defining the middleware method, not the property. The steps to replicate are rather simple, you should be able to see the middleware called twice.

**Comment by kieranbrown** [comment]
```php

<?php

declare(strict_types=1);

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Notification;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;

class SomeClass extends Notification implements ShouldQueue
{
    use Queueable;

    /**
     * Get the middleware the job should be dispatched through.
     *
     * @return array
     */
    public function middleware()
    {
        return [new SomeMiddleware()];
    }

    /**
     * Get the mail representation of the notification.
     *
     * @param User $notifiable
     *
     * @return MailMessage
     */
    public function toMail($notifiable)
    {
        //
    }

    /**
     * Get the notification's delivery channels.
     *
     * @param User $notifiable
     *
     * @return array
     */
    public function via($notifiable)
    {
        return ['mail', 'database'];
    }
}
```

**Comment by ankurk91** [comment]
Are you using a queue ot horizon or similar?

**Comment by driesvints** [comment]
A fix for this was merged.
