### ISSUE TITLE
Failed method in jobs is not triggered when model is not found

### ISSUE THREAD

**Issue by Cannonb4ll** [laravel/framework#31209]
- Laravel Version: 6.12.0
- PHP Version: 7.4.1
- Database Driver & Version: MySQL 5.6

### Description:
It seems that whenever you dispatch a delayed job with an eloquent model as argument, and that model gets deleted in between the delayed job & firing, the `failed()` method is not being triggered.

### Steps To Reproduce:

Create TestJob, that accepts argument model User and failed method:

```php
public $user;

/**
 * Create a new job instance.
 *
 * @return void
 */
public function __construct(User $user)
{
    $this->user = $user;
}

/**
 * Execute the job.
 *
 * @return void
 */
public function handle()
{
    dump($this->user->name);
}

public function failed(\Exception $exception)
{
    dump('Did it fail?');
}
```

```php
dispatch(new TestJob(User::find(1))->delay(now()->addSeconds(15));
```

After dispatching to the queue, make sure to move the user's ID in database from 1 to 2 (or any other number) within 15 seconds.

The job will fail & recorded in failed_jobs table with:

```
Illuminate\Database\Eloquent\ModelNotFoundException: No query results for model [App\User]
```

I'd expected that the `failed()` method gets triggered and the dump would get outputted, but for some reason it is not. 

However, I am not sure if this is intentional behaviour. Let me know if additional info is needed.

**Comment by themsaid** [comment]
This is a known limitation https://github.com/laravel/framework/issues/25363

The problem here is that if we can't unserialize the object there's no way we can call methods on it.

If it's critical in your app to run some code from `failed()` if the model is not found then pass the model ID to the job instead of the model itself and catch the exception if the model isn't found in the job.

**Comment by Cannonb4ll** [comment]
Thanks!

**Comment by ejunker** [comment]
I found that setting `$deleteWhenMissingModels = true;` in my job worked for me. It didn't call `failed()` as far as I know but it did prevent there from being an exception thrown when the model was missing. https://laravel.com/docs/7.x/queues#ignoring-missing-models
