### ISSUE TITLE
(Mailable) Duplicate attachments prevention update disallows multiple attachments

### ISSUE THREAD

**Issue by cnsaavedra** [laravel/framework#31204]
- Laravel Version: 6.8.0
- PHP Version: 7.4.1
- Database Driver & Version: mysql

### Description:
The update for: 

> An update that prevents. duplicate attachments.
> Commit https://github.com/laravel/framework/commit/3c8ccc2fb4ec03572076e6df71608f6bbb7d71e1.

Disallows having multiple attachments for a mail despite having different file names and content.
I reverted the attach() method to previous version and I was able to attach multiple files afterwards.

### Steps To Reproduce:
1. Create 2 different files (in my case they are 'Excel' files) (with different file names and content)
2. Attach the files through attach() method to a mailable.
3. Send mail (receiving only one file, from the two specifically the first ->attach() specified)

**Comment by driesvints** [comment]
How is that possible? The commit just makes sure you never add an attachment twice from the same pathname: https://github.com/laravel/framework/commit/3c8ccc2fb4ec03572076e6df71608f6bbb7d71e1#diff-5e21ce4b000d10420529bd908fab8b86R788

**Comment by cnsaavedra** [comment]
So it does not check content and size difference but only pathnames?
If that's the case, I made two Excel files using Laravel Excel. I checked the file details and these are the follows results (using Tinker):

**File 1**:
```
=> Symfony\Component\HttpFoundation\File\File {#4628
     path: "/private/var/folders/0x/theSameAsBelow/T",
     filename: "laravel-excel-difCode123",
     basename: "laravel-excel-difCode123",
     pathname: "/private/var/folders/0x/theSameAsBelow/T/laravel-excel-difCode123",
     extension: "",
     realPath: "/private/var/folders/0x/theSameAsBelow/T/laravel-excel-difCode123",
```

**File 2**:
```
=> Symfony\Component\HttpFoundation\File\File {#4840
     path: "/private/var/folders/0x/theSameAsAbove/T",
     filename: "laravel-excel-notthesameasabove",
     basename: "laravel-excel-notthesameasabove",
     pathname: "/private/var/folders/0x/sameAsAbove/T/laravel-excel-notthesameasabove123",
     extension: "",
     realPath: "/private/var/folders/0x/sameAsAbove/T/laravel-excel-notthesameasabove123",
```.
Note that I made it easier to compare the two files by replacing the long string tokens by explicitly saying they're different.
So in this scenario, the key 'path' are both the same. But the filename, basename, pathname and realPath are different.

So does the laravel unique file method only check for 'path'? No size, content, realPath, basename differentiable check?

**Comment by driesvints** [comment]
yes only path. Why would the two different files be on the same path? That doesn't seems possible? 🤔

**Comment by cnsaavedra** [comment]
Yeah, not too sure as I haven't explored too much with this Laravel Excell package. Probably has to do something because they were made through Laravel Excell instead of being actual files.

**Comment by driesvints** [comment]
Feel free to report back when you've figured things out 👍
