### ISSUE TITLE
ErrorException  : DOMDocument::loadHTML(): Empty string supplied as input

### ISSUE THREAD

**Issue by ManuelSteiner89** [laravel/framework#31203]
- Laravel Version: Laravel Framework 5.8.24
- PHP Version: PHP 7.2.19 

### Description:
Hi guys, out of nowhere i get the error bellow.
This happens only when i trigger the mail through commands locally ( or the cronjobs on the server).
Sending mail directly from a controller works fine and doesnt throw any exception.

i allready saw the following thread, but that wasnt useful at all.
https://github.com/laravel/framework/issues/21493

```
 ErrorException  : DOMDocument::loadHTML(): Empty string supplied as input

  at E:\laragon\www\selbstmakler-laravel\vendor\tijsverkoyen\css-to-inline-styles\src\CssToInlineStyles.php:113
    109|     protected function createDomDocumentFromHtml($html)
    110|     {
    111|         $document = new \DOMDocument('1.0', 'UTF-8');
    112|         $internalErrors = libxml_use_internal_errors(true);
  **> 113|         $document->loadHTML(mb_convert_encoding($html, 'HTML-ENTITIES', 'UTF-8'));**
    114|         libxml_use_internal_errors($internalErrors);
    115|         $document->formatOutput = true;
    116| 
    117|         return $document;

  Exception trace:

  1   DOMDocument::loadHTML("")
      E:\laragon\www\selbstmakler-laravel\vendor\tijsverkoyen\css-to-inline-styles\src\CssToInlineStyles.php:113

  2   TijsVerkoyen\CssToInlineStyles\CssToInlineStyles::createDomDocumentFromHtml("")
      E:\laragon\www\selbstmakler-laravel\vendor\tijsverkoyen\css-to-inline-styles\src\CssToInlineStyles.php:36
```

### Steps To Reproduce:
The Command class looks like this and worked perfectly fine:
```
public function handle()
    {
        // set start and endtimes for weeks
        Carbon::setWeekStartsAt(Carbon::MONDAY);
        Carbon::setWeekEndsAt(Carbon::SUNDAY);

        $customersThisWeekCounted = Customer::whereBetween('created_at', [Carbon::now()->startOfWeek(), Carbon::now()->endOfWeek()])->count();
        $meetingsThisWeekCounted = ActivityMeeting::whereBetween('created_at', [Carbon::now()->startOfWeek(), Carbon::now()->endOfWeek()])->count();
        $selbstmaklersThisWeekCounted = Selbstmakler::whereBetween('created_at', [Carbon::now()->startOfWeek(), Carbon::now()->endOfWeek()])->count();
    
        Mail::to('myemail@example.com')->send(new WeeklyStatusMail($customersThisWeekCounted, $selbstmaklersThisWeekCounted, $meetingsThisWeekCounted));
    }
``` 
The mailclass itself looks like this:
```
public $customerCount;
    public $selbstmaklerCount;
    public $meetingCount;

    /**
     * Create a new message instance.
     *
     * @return void
     */
    public function __construct($customerCount, $selbstmaklerCount, $meetingCount)
    {
        $this->customerCount = $customerCount;
        $this->selbstmaklerCount = $selbstmaklerCount;
        $this->meetingCount = $meetingCount;
    }

    /**
     * Build the message.
     *
     * @return $this
     */
    public function build()
    {
        return $this->from('weeklystatus@selbstmakler.ch')
            ->subject('Wöchentlicher Status Selbstmakler')
            ->markdown('emails.admin.weekly.status');
    }
}
```

The E-Mail-HTML itself gets printed out before the error occures:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/>
</head>
<body>
    <style>
        @media  only screen and (max-width: 600px) {
            .inner-body {
                width: 100% !important;
            }

            .footer {
                width: 100% !important;
            }
        }

        @media  only screen and (max-width: 500px) {
            .button-comment {
                width: 100% !important;
            }
        }
    </style>

    <table class="wrapper" width="100%" cellpadding="0" cellspacing="0" role="presentation">
        <tr>
            <td align="center">
                <table class="content" width="100%" cellpadding="0" cellspacing="0" role="presentation">
                    <tr>
</tr>

                    <!-- Email Body -->
                    <tr>
                        <td class="body" width="100%" cellpadding="0" cellspacing="0">
                            <table class="inner-body" align="center" width="560" cellpadding="0" cellspacing="0" role="presentation">
                                <!-- Body content -->
                                <tr>
                                    <td class="content-cell">
                                        <h1>Hallo zusammen</h1>
<p>Wieder eine Woche vorbei, wieder ein Statusmail &#128516;<br>
In diesem findet Ihr diverse statistische Angaben. Diese lauten wie folgt:<br/></p>
<p>Neue registrierte Interessenten:<br/>
<b>0</b></p>
<p>Neue registrierte Selbstmakler:<br/>
<b>6</b></p>
<p>Die Interessenten haben diese Woche <b>0</b> Termine angefragt.<br/></p>
<p>Für weitere Statistiken oder Möglichkeiten, bitte Manuel / Dario kontaktieren.</p>


                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>

                    <tr>
    <td>
        <table class="footer" align="center" width="570" cellpadding="0" cellspacing="0" role="presentation">
            <tr>
                <td class="content-cell" align="center">
                    &#169;
                </td>
            </tr>
        </table>
    </td>
</tr>
                </table>
            </td>
        </tr>
    </table>
</body>
</html>
```

Kind regards, 
Manuel

**Comment by voyula** [comment]
> ```
>     public $selbstmaklerCount;
>     public $meetingCount;
> 
>     /**
>      * Create a new message instance.
>      *
>      * @return void
>      */
>     public function __construct($customerCount, $selbstmaklerCount, $meetingCount)
>     {
>         $this->customerCount = $customerCount;
>         $this->selbstmaklerCount = $selbstmaklerCount;
>         $this->meetingCount = $meetingCount;
>     }

Try:

> ```
>     public $customerCount;
>     public $selbstmaklerCount;
>     public $meetingCount;
> 
>     /**
>      * Create a new message instance.
>      *
>      * @return void
>      */
>     public function __construct($customerCount, $selbstmaklerCount, $meetingCount)
>     {
>         $this->customerCount = $customerCount;
>         $this->selbstmaklerCount = $selbstmaklerCount;
>         $this->meetingCount = $meetingCount;
>     }

**Comment by ManuelSteiner89** [comment]
> > ```
> >     public $selbstmaklerCount;
> >     public $meetingCount;
> > 
> >     /**
> >      * Create a new message instance.
> >      *
> >      * @return void
> >      */
> >     public function __construct($customerCount, $selbstmaklerCount, $meetingCount)
> >     {
> >         $this->customerCount = $customerCount;
> >         $this->selbstmaklerCount = $selbstmaklerCount;
> >         $this->meetingCount = $meetingCount;
> >     }
> > ```
> 
> Try:
> 
> > ```
> >     public $customerCount;
> >     public $selbstmaklerCount;
> >     public $meetingCount;
> > 
> >     /**
> >      * Create a new message instance.
> >      *
> >      * @return void
> >      */
> >     public function __construct($customerCount, $selbstmaklerCount, $meetingCount)
> >     {
> >         $this->customerCount = $customerCount;
> >         $this->selbstmaklerCount = $selbstmaklerCount;
> >         $this->meetingCount = $meetingCount;
> >     }
> > ```

Thx for the anwser, this was a accident of mine, missed the part from copy to git. 
I appreciate your help, but that wasnt the solution :(

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by dbeniamine** [comment]
I encountered a similar issue with Laravel 6.x on a view that used to work and stopped to work for no identified reason a few days (weeks ?) ago ...

For me the fix was simply to delete the view cache : `php artisan view:clear`.

I am not sure of how it happened but I'm putting that here in case it can help someone someday
