### ISSUE TITLE
PHP 7.2 parse error

### ISSUE THREAD

**Issue by kylekatarnls** [laravel/framework#31217]
- Laravel Version: https://github.com/laravel/framework/commit/e1fb7b1507947911f408ffdbc1fd95d02507a9c7#diff-87cb1ee8a1f6d98f9ceebfba806b3a72R153
- PHP Version: 7.2

https://travis-ci.org/laravel/framework/jobs/640922227#L871

Will PHP 7.2 be dropped for Laravel 7? If so the composer.json should be updated or the syntax error (trailing comma) should be fixed. I may send a PR for any of those.

**Comment by GrahamCampbell** [comment]
Thanks. This was just a typo. Fixed now. :)
