### ISSUE TITLE
Classname inversion in Eloquent Builder error message

### ISSUE THREAD

**Issue by 3rgo** [laravel/framework#31213]
- Laravel Version: 6.11.0
- PHP Version: 7.3.10
- Database Driver & Version: MySQL 5.7.27

### Description:
When using a closure with a `Builder` dependency injection, if the `Eloquent\Builder` use statement is missing, the following error message is returned :
`Argument 1 passed to App\Http\Controllers\API\AcmeController::App\Http\Controllers\API\{closure}() must be an instance of App\Http\Controllers\API\Builder, instance of Illuminate\Database\Eloquent\Builder given, called in /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php on line 978`
The message indicates that the given Builder instance was `Eloquent\Builder`, and it's expecting `Controllers\API\Builder` when it is in fact the opposite. Adding the use statement makes the error go away

This was tested in 6.11, but no corresponding fix appear in patch notes of 6.12, so it should also be present.

### Steps To Reproduce:

1. Create a controller and use a Closure with a Eloquent\Builder parameter (in my case I used the `Model::whereHas` method of the query builder)
2. Do not add (or remove) the use statement for `Illuminate\Database\Eloquent\Builder`
3. Execute code and read the error message

*In my context, the controller is in an "API" subnamespace, but a "root" controller should cause the same error. I believe (but have not tested) that the error can be reproduced in any context, since it seems to be caused by the DI mechanism.*

**Comment by 36864** [comment]
Can you post the actual code that you were using that originated the error?

**Comment by 3rgo** [comment]
Sure : https://gist.github.com/3rgo/dd5ed94fff90c685b197142c58931513 (Line 70)

**Comment by 36864** [comment]
>$manager = User::where('id', $value)->whereHas('roles', function(Builder $query){

If you don't import the `Eloquent\Builder` class, `Builder` resolves to the namespace it is being used in. Meaning the function is expecting an instance of `App\Http\Controllers\API\Builder`.

There is no error in the error message. You defined a function that should receive an instance of `App\Http\Controllers\API\Builder`, while the framework is passing in an instance of `Eloquent\Builder`.

**Comment by 3rgo** [comment]
Oh OK, my bad ! Thanks for the explanation.

I understand the rules of namespace resolution, but I misunderstood the error message, not taking into account the fact that the framework DI mechanics correctly injects the Eloquent/Builder class. 

I'm closing the thread
