### ISSUE TITLE
Asterisk keys in validator input bypass array validation rules

### ISSUE THREAD

**Issue by alex-fenwick-myhrtoolkit** [laravel/framework#31228]
- Laravel Version: 6.11.0
- PHP Version: 7.4.0
- Database Driver & Version: N/A

### Description:

When validating an array that has an asterisk (\*) as any of the keys: the value corresponding to that key will _bypass_ any array/wildcard rules in the validator (i.e. rules whose key includes an asterisk such as `data.*.date`).

### Steps To Reproduce:

Run the following code:
```
$input = [
    'data' => [
        0 => ['date' => '2019-01-24'],
        1 => ['date' => 'blah'],
        '*' => ['date' => 'blah']
    ]
];

$validator = \Illuminate\Support\Facades\Validator::make($input, [
    'data.*.date' => 'required|date'
]);

if($validator->fails()) {
    dd($validator->errors());
}
```
Note the lack of validation errors in the output regarding the asterisk entry in the data array:

```
Illuminate\Support\MessageBag {
  #messages: array:1 [
    "data.1.date" => array:1 [
      0 => "The data.1.date is not a valid date."
    ]
  ]
  #format: ":message"
}
```

### Further Details

I examined the code to find out what was happening and the issue occurs in `ValidationRuleParser::explodeRules`.  Each entry in an array to be validated has to have rules generated by the rule parser specifically for that entry.  An asterisk entry in the incoming data has rules generated for it that are _identical_ to the original rules set on the validator, and these rules are automatically unset and lost leading to zero validation on these entries.

Unfortunately we cannot simply detect this special case and stop the unset.  This is because there is a deeper issue (for this _specific_ case) in the way rules are generated, which involves an array merge leading to rule duplication (`ValidationRuleParser::mergeRulesForAttribute`).

I have not made a pull request as, due to the recursion occurring in this code, I am not confident enough to make a fix here.  In particular: I can't guarantee that any fix I thought up wouldn't break more complex rules e.g. `data.*.user.*.name`.

**Comment by driesvints** [comment]
Because of the asterisk being a reserved character for wildcard matching, I doubt that what you're attempting is possible at all. 

You're free to open up an issue on the ideas repo to investigate if there could be possible support for this. Also feel free to send in a PR to the docs if you feel this should be clarified.

**Comment by alex-fenwick-myhrtoolkit** [comment]
Hi @driesvints, I think there's been a bit of confusion.  I didn't raise this issue as a feature suggestion but to point out a potential **security flaw**.  Nowhere in the documentation can I find mention of the fact that an asterisk key on input will _bypass_ validation (I would expect such a thing [here](https://laravel.com/docs/6.x/validation#validating-arrays)).

As an example of the implications of this; consider a publicly facing API running Laravel (of which there must be hundreds?).  _Any_ user on the internet can bypass _all_ array validation by simply sending data keyed by an asterisk.  Surely this is a fairly big concern to Laravel LLC?

**Comment by driesvints** [comment]
Heya! Sorry, I indeed misread this. Thanks for making us aware. We're looking into this.

**Comment by driesvints** [comment]
Sent in a PR here: https://github.com/laravel/framework/pull/31253

**Comment by driesvints** [comment]
Was solved by a different solution by @themsaid
