### ISSUE TITLE
Exceptions\Handler in method unauthenticated empty $exception->redirectTo()

### ISSUE THREAD

**Issue by shadrvlad** [laravel/framework#31223]
- Laravel Version: 6.12.0
- PHP Version: 7.4.1
- Database Driver & Version: 10.3.21-MariaDB

### Description:
When using AuthenticateSession and the name of the authorization route other than "login" when resetting the session, we get Route [login] not defined

### Steps To Reproduce:
1. Uncomment \Illuminate\Session\Middleware\AuthenticateSession::class
2. php artisan ui vue --auth
3. Rename the route login to login1 - Route::get('login', 'Auth\LoginController@showLoginForm')->name('login1');
4. Replace login with login1 in views and App\Middleware\Authenticate
5. Register and log in to your account from two browsers.
6. In one of them, run Auth::logoutOtherDevices
7. In the other case, we get the error Route [login] not defined.
Because in the unauthorized method in Illuminate\Foundation\Exceptions\Handler $exception->redirectTo() === null

**Comment by driesvints** [comment]
Please open this on the laravel/ui repo and report which laravel/ui version you're using.

**Comment by driesvints** [comment]
I'm sorry, this did belong in this repo.

**Comment by driesvints** [comment]
Overriding the `unauthorized` method seems the only way to solved this atm. I've sent in a PR to the docs here: https://github.com/laravel/docs/pull/5748

**Comment by shadrvlad** [comment]
> Overriding the `unauthorized` method seems the only way to solved this atm. I've sent in a PR to the docs here: [laravel/docs#5748](https://github.com/laravel/docs/pull/5748)

When you normally go to a page that is closed by authorization, there are no errors. in $exception->redirectTo() , the value from App\Middleware\Authenticate and route ('login') does not work.
