### ISSUE TITLE
Queue not honouring job specific timeout

### ISSUE THREAD

**Issue by svscherpenseel** [laravel/framework#31226]
- Laravel Version: 6.12.0
- PHP Version: 7.4.1 (with `pcntl` extension enabled)
- Database Driver & Version: MariaDB 10.4

### Description:

According to the Laravel docs I should be able to specify a job specific timeout:

> If the timeout is specified on the job, it will take precedence over any timeout specified on the command line [...]

All I have to do is define `public $timeout = 120;` inside the job. Unfortunately, the job still times out after 60 seconds. I use the database driver to run the jobs.

### Steps To Reproduce:

- Configure Laravel to use the database as the queue driver;
- Create a new job and define `public $timeout = 120;` inside its class;
- Make its execution take longer than the `max_execution_time` by setting `sleep(420)` in the `handle()` method, for example;
- Run `php artisan queue:listen`;
- Experience getting a `ProcessTimedOutException`.

**Comment by themsaid** [comment]
That's for when you use `queue:work`, if you use `queue:listen` the timeout you set on the command will take precedence.

**Comment by svscherpenseel** [comment]
@themsaid it looks like you're right. When using `queue:work` the timeout specified inside the job takes precedence. Thanks!

Is there any reason why this doesn't work with `queue:listen`? I like using `queue:listen` during development because I don't have to restart the queue after making changes to my code.

**Comment by themsaid** [comment]
`queue:listen` runs several processes while `queue:work` is a single process. `queue:listen` sets a timeout for the process it runs so we don't leave ghost processes running on the machine in case the master process was killed for some reason.

In development, I always run `queue:listen --timeout=1000` so I give the jobs more time than usual to work normally.

**Comment by svscherpenseel** [comment]
I understand, thanks for the explanation. This wasn't clear from the docs though, so it might be worth mentioning this?

**Comment by driesvints** [comment]
@svscherpenseel feel free to send in a pr 👍
