### ISSUE TITLE
No error show when inexistent policy is called

### ISSUE THREAD

**Issue by PEscar** [laravel/framework#31225]
- Laravel Version: 5.6.39
- PHP Version: 7.2.24-0ubuntu0.18.04.2 (cli) (built: Jan 13 2020 18:39:59) ( NTS )
- Database Driver & Version: 14.14 Distrib 5.7.28, for Linux (x86_64) using  EditLine wrapper

### Description:
If you call a policy from a controller method, you don't get any error message (eather log error message) in the case that policy doesnt exist (or even not registered in /var/www/html/PMFARMA/app/Providers/AuthServiceProvider.php )
### Steps To Reproduce:
1 ) Create a policy named ExamplePolicy related to an User model
2 ) In that policy, create a method like this:

public function examplePolicy(User $user, User $user2){
return true;
}

3 ) Define a route to a controller method like this:

public function example(){
$user2 = User::find(2);
$ret = $this->authorize('examplePolicy', $user2);
 }

4 ) Check that $ret value is true;
5 ) Change controller method in this line:
$ret = $this->authorize('examplePolicy', $user2);
TO:
$ret = $this->authorize('exampleInexistentPolicy, $user2);

6 ) Check that value of $ret is false and you dont get any error message (answer of call es 403 Forbidden, like when a policy denied an action)
7 ) Check 6 ) in your web server error log file and in your laravel log error file (by default, storage/logs/laravel.log)

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by PEscar** [comment]
Hi there !
Thanks for your response ! Upgrade our project version is scheduled for the future. Once upgraded, i will check if this thing still happening.
Regards,
Pedro.
