### ISSUE TITLE
Missing event handler:queueJobExceptionOccurredhandler

### ISSUE THREAD

**Issue by darcyrailip** [laravel/framework#31234]
- Laravel Version: 6.12.0
- PHP Version: 7.4.1

### Description:
All queued jobs in Redis are encountering this issue:

![image](https://user-images.githubusercontent.com/13946257/73107259-601cba00-3ecb-11ea-9aad-167d3c652747.png)

This occurred after upgrading our Laravel and PHP versions, but I'm unable to find anything regarding that event handler...

**Comment by X-Coder264** [comment]
Fixed in Laravel Sentry 1.6.1 -> https://github.com/getsentry/sentry-laravel/pull/322
