### ISSUE TITLE
@error directive not working as documented

### ISSUE THREAD

**Issue by gRoberts84** [laravel/framework#31240]
- Laravel Version: 6.12.0
- PHP Version: 7.2.4
- Database Driver & Version: N/A

### Description:

The @error directive is not displaying the error message as documented/expected.

Quite possibly related to #31094 

### Steps To Reproduce:

- Run `composer create-project --prefer-dist laravel/laravel blog` to create a new instance.
- Add `Auth::routes();` to `routes/web.php`
- Adjust .env to point to a database.
- Run `php artisan migrate`
- Create basic login form  with `email` and `password` fields to be able to submit a successful login attempt.
- At the top of the form, add `@error('email') <div>{{ $message }}</div> @enderror`.
- Submit the form.
- Note the lack of the error (not even an empty div)

### More Information

When doing the above steps to reproduce the issue, I receive no error message, however if I replace the `@error` directive with

```
@if ($errors->has('email')) <div>{{ $errors->first('email') }}</div> @endif
```

I successfully see an error.

Apologies if I have missed anything blatantly obvious in the documentation that relates to this. If I have, please let me know. 

Thanks

**Comment by gRoberts84** [comment]
Ignore me, I was being stupid. It wasn't working at first, bunged the bag name into the `@error` directive as the second parameter and it still didn't work but when I removed the second parameter it started work.

Me being a idiot it seems.

**Comment by rashidabbas7865** [comment]
> Ignore me, I was being stupid. It wasn't working at first, bunged the bag name into the `@error` directive as the second parameter and it still didn't work but when I removed the second parameter it started work.
> 
> Me being an idiot it seems.

Can you explain this in details please? Because I'm having the same issue.

**Comment by saleempbt5** [comment]
I am having the same issue, i have installed laravel and did all the steps required for Auth. Unfortunately, @error in login view blade doesn't show any errors related to that particular field. 
Though `@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif`
shows a common error message like 
"These credentials do not match our records."
Can anyone have a solution for this ?

**Comment by driesvints** [comment]
@saleempbt5 please use a support channel:
- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks.

**Comment by Bobokhuja** [comment]
what's inside @error should be on 1 line

@error('title')
<div class="invalid-feedback">{{ $message }}</div>
@enderror
